### ISSUE TITLE
Enable editing the default admin from UI

### ISSUE THREAD

**Issue by ajfriesen** [rancher/rancher#22727]
**What kind of request is this (question/bug/enhancement/feature request):**

feature

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

It is not possible to add groups or users from azure ad to the default admin user via the web interface.
it is only possible with this curl:

```
curl -u "${ACCESS_TOKEN}" \
-X PUT \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"annotations":{"lifecycle.cattle.io/create.mgmt-auth-users-controller":"true"}, "conditions":[], "created":"2019-04-11T21:29:02Z", "creatorId":null, "description":"", "id":"user-bwwtn", "labels":{"authz.management.cattle.io/bootstrapping":"admin-user", "cattle.io/creator":"norman"}, "me":true, "mustChangePassword":false, "name":"Default Admin", "ownerReferences":[], "principalIds":["local://user-bwwtn", "azuread_user://some-group-id"], "state":"active", "transitioning":"no", "transitioningMessage":"", "username":"admin", "uuid":"d3cf154a-5ca0-11e9-b9ba-0eadc8878f18"}' \
'https://rancher-url.com/v3/users/user-bwwtn'
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8
- Installation option (single install/HA): HA

**Comment by deniseschannon** [comment]
We wouldn't recommend adding to the default admin, but in v2.4, you can add roles to a group. So you would be able to add a group and provide them with the admin role. 

https://github.com/rancher/rancher/issues/22707
