### ISSUE TITLE
RequestError: send request failed\ncaused by: Post https://ec2.cn-northwest-1.amazonaws.com/: dial tcp: lookup ec2.cn-northwest-1.amazonaws.com on 10.17.255.2:53: no such host

### ISSUE THREAD

**Issue by linbingdouzhe** [rancher/rancher#22720]
hi team 
I am failed launch a ec2 kuberenetes cluster on rancher . my region is cn-northwest-1.

my rancher is build by docker 
docker logs -f imageID

2019/09/09 10:40:34 [INFO] Generating and uploading node config ihb3
2019/09/09 10:40:34 [INFO] Generating and uploading node config ihb2
2019/09/09 10:40:49 [ERROR] NodeController c-dznp7/m-xct2p [node-controller] failed with : Error with pre-create check: "RequestError: send request failed\ncaused by: Post https://ec2.cn-northwest-1.amazonaws.com/: dial tcp: lookup ec2.cn-northwest-1.amazonaws.com on 10.17.255.2:53: no such host"
2019/09/09 10:40:49 [ERROR] NodeController c-dznp7/m-jcvw2 [node-controller] failed with : Error with pre-create check: "RequestError: send request failed\ncaused by: Post https://ec2.cn-northwest-1.amazonaws.com/: dial tcp: lookup ec2.cn-northwest-1.amazonaws.com on 10.17.255.2:53: no such host"
2019/09/09 10:40:49 [ERROR] NodeController c-dznp7/m-gxjh2 [node-controller] failed with : Error with pre-create check: "RequestError: send request failed\ncaused by: Post https://ec2.cn-northwest-1.amazonaws.com/: dial tcp: lookup ec2.cn-northwest-1.amazonaws.com on 10.17.255.2:53: no such host"
2019/09/09 10:40:49 [INFO] Creating jail for c-dznp7
2019/09/09 10:40:49 [INFO] Generating and uploading node config

But, if I Ichoose aws region cn-north-1 ,that ec2 will be succesfully created.
So, is this a bug ?

**Comment by linbingdouzhe** [comment]
the endpoint should be ec2.cn-northwest-1.amazonaws.com.cn , not ec2.cn-northwest-1.amazonaws.com, but i can find that option on anywhere......

**Comment by linbingdouzhe** [comment]
on branch master-head is work but look like ... it can not destroy ec2 when i delete the cluster

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
