### ISSUE TITLE
Custom ingress-ip-domain urls are generated but 503 is returned

### ISSUE THREAD

**Issue by mr-falken** [rancher/rancher#22728]
### Brief history: 
Been using release 2.2.8 for a while, everything worked as expected, except for custom ingress-ip-domain: when setting custom domain no url gets auto generated (probably related to https://github.com/rancher/rancher/issues/19915 ?)

### Actual situation 
Updated rancher to 2.3.0-rc1 and the bug described before seems fixed.
The issue I am experiencing now is the that every autogenerated ingress url with custom domain returns 503 when accessed.

### Steps to reproduce
 - Install rancher 2.3.0-rc1
 - Change ingress-ip-domain in global settings to a custom dns
 - Create a layer 7 ingress with auto generated url

### Result
When accessing url 503 is returned instead of correct service.

### Environment
 - Rancher 2.3.0-rc1
 - OpenStack cloud provider 
 - Single node
 - Self hosted custom dns server 

FYI: our custom dns is self hosted with powerdns, customized with xip source code https://github.com/basecamp/xip-pdns: tested it for other projects and works like a charm :)

**Comment by loganhz** [comment]
Thanks! Close in favor of https://github.com/rancher/rancher/issues/24018
