### ISSUE TITLE
Feature Request: mirror rancher assets

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#22737]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Description**
Mirror Rancher assets for each release on a Rancher specific domain for companies that do not allow github.com through their network proxy.

gz#6054

**Comment by patrick0057** [comment]
https://github.com/rancher/rancher/issues/23569

**Comment by leodotcloud** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/23569
