### ISSUE TITLE
Update api endpoints for kubedns and calico addons to work with 1.16

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#22732]
Looks like we've missed a couple of api endpoints updates for non-default addons like calico and kubedns to work with k8s 1.16

**Comment by sangeethah** [comment]
Tested with latest rancher server build from master-head - `ad92680c1`
Able to bring up a 3 node cluster(all roles) with following configuration on K8s version - `v1.16.0-beta.1` and `v1.15.3`

1. Cluster with dns set to `kube-dns` 
2. Cluster with network policy set to `calico`

<img width="1154" alt="Screen Shot 2019-09-10 at 7 04 59 PM" src="https://user-images.githubusercontent.com/4266958/64662612-e7c2ca00-d3fd-11e9-9ea6-d9f0ccb060a6.png">

<img width="1162" alt="Screen Shot 2019-09-10 at 7 04 39 PM" src="https://user-images.githubusercontent.com/4266958/64662625-f5784f80-d3fd-11e9-8411-2c018381908f.png">
