### ISSUE TITLE
Understanding the Rancher cluster dashboard

### ISSUE THREAD

**Issue by fmunteanu** [rancher/rancher#22746]
Looking at following Cluster `local` dashboard:

![Dashboard](https://i.imgur.com/A87z1HD.png)

What represents the blue and green gauges? I could not find anything documented. Once I enabled the Cluster monitoring, the green gauges appeared.

After enabling Project monitoring I saw no changes, where can I see the monitoring details?

**Comment by kapolos** [comment]
@fmunteanu The green gauge corresponds to the green letters, the blue one to the blue letters.

It can take a while for monitoring to fully get working but it will look like this below the gauges:

![image](https://user-images.githubusercontent.com/10794126/64615537-6cecb580-d3e3-11e9-94b1-c94bca7694fe.png)

**Comment by fmunteanu** [comment]
@kapolos From my understanding, the blue one shows the total max cluster capacity (24 CPU), while the green show only the max `local` cluster capacity (8 CPU). I do not know where the [Project Monitoring](https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/monitoring/#configuring-project-monitoring) graphs are displayed.

**Comment by tfiduccia** [comment]
Closing in favor of: #23314
