### ISSUE TITLE
Adding an AWS EC2 fails on selection of security group that has duplicate group name in other VPC

### ISSUE THREAD

**Issue by wonderslug** [rancher/rancher#2274]
AWS EC2 allows for duplicate group names of security groups between VPCs in a zone.  It also creates a "default" security group that allows access to all other EC2 instances that have the same security group.  Since it creates a "default" per VPC when you have multiple VPCs in a zone you have issues just selecting the "default" as the group name for adding a host.

When Rancher is creating an EC2 host with docker-machine it is passing the security group name.  if you have duplicate group names it allows docker-machine to grab the wrong one and gives an error that the security group selected is not in the same VPC.

I think this can be solved by passing the security group id instead of just the group name.

**Comment by deniseschannon** [comment]
This sounds like a duplicate of this: https://github.com/rancher/rancher/issues/2084.

**Comment by wonderslug** [comment]
I dont see this as a duplicate because it seems that that is talking about the UI presentation when selecting a VPC and the security groups for it.  This is actually what is passed to docker-machine in that its only passing the group name not the id.

I agree with #2084 in that a better view of the security groups available are necessary but when you select a VPC or subnet only one default shows up.    When its selected and used as the selection "default" is passed to docker-machine instead of an exact security group identifying it.

**Comment by deniseschannon** [comment]
I looked into the machine driver docs, but the driver options only have security group name. 

https://docs.docker.com/machine/drivers/aws/

So, thinking more about it, I think it's still about the UI presentation. And I will close this one in favor of the UI one.
