### ISSUE TITLE
rancher-load-images.sh does not push images

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#22740]
bug in rancher/rancher:v2.3.0-rc2

get the script `rancher-load-images.sh` from: https://github.com/rancher/rancher/releases/tag/v2.3.0-rc2

The script does only `docker tag` but not `docker push` images.

**Comment by loganhz** [comment]
I think we should support push manifest images.

 `rancher/hyperkube:v1.15.3-rancher3` is a manifest 

In a Windows cluster, both linux node and windows node will pull it from the private registry. If we don't support manifest, we cannot do the air-gap install for Windows cluster.

cc @cloudnautique @drpebcak

**Comment by cjellick** [comment]
The original issue is fixed, but @loganhz's comment is not. That issues is capture in #22463 
We may want to hold off on testing this as it may need retested when #22463 goes through

**Comment by jiaqiluo** [comment]
The bug fix is validated with the `rancher-load-images.sh` from release `v2.3.0-rc6`

Images are tagged and pushe to the private registry.
