### ISSUE TITLE
[rancher/rancher-agent] Websocket do not use proxy settings

### ISSUE THREAD

**Issue by Wykiki** [rancher/rancher#22750]
**What kind of request is this (question/bug/enhancement/feature request):**

BUG

**Steps to reproduce (least amount of steps as possible):**

- Setup Rancher behind corporate proxy
- Provide Proxy configuration

**Result:**

- `cattle-cluster-agent` and `cattle-node-agent`s are unable to connect via `wss://` to my Rancher instance.

**Other details that may be helpful:**

I will be talking only about `cattle-cluster-agent` here.

Just setup a fresh install of Rancher behind a corporate proxy.

Without proxy settings, `cattle-cluster-agent` timeout after those lines :

```
INFO: Environment: CATTLE_ADDRESS=10.42.1.12 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-74555999ff-v9ksz CATTLE_SERVER=https://<rancher_host>
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.sub.aws svc.sub.aws sub.aws options ndots:5
```

With proxy settings set in environment ('HTTP_PROXY', 'HTTPS_PROXY' and 'NO_PROXY'), the pod timeout after trying to connect to Rancher via WebSocket : 

```
INFO: Environment: CATTLE_ADDRESS=10.42.1.12 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-74555999ff-v9ksz CATTLE_SERVER=https://<rancher_host>
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.sub.aws svc.sub.aws sub.aws options ndots:5
INFO: https://<rancher_host>/ping is accessible
INFO: <rancher_host> resolves to <load_balancer_ip>
time="2019-09-10T09:45:14Z" level=info msg="Listening on /tmp/log.sock"
time="2019-09-10T09:45:14Z" level=info msg="Rancher agent version v2.2.8 is starting"
time="2019-09-10T09:45:14Z" level=info msg="Connecting to wss://<rancher_host>/v3/connect/register with token <token>"
time="2019-09-10T09:45:14Z" level=info msg="Connecting to proxy" url="wss://<rancher_host>/v3/connect/register"
time="2019-09-10T09:47:25Z" level=error msg="Failed to connect to proxy" error="dial tcp <load_balancer_ip>:443: connect: connection timed out"
```

I dont't see connection attempts on my proxy access logs.

It looks like it get proxy settings for the `/ping`, but not for the `wss://`.

Is there another way to provide proxy settings to this pod ?

Thanks a lot for reading this brick of text !

**Environment information**
- Rancher version (stable) : `rancher/rancher:v2.2.8`
- Installation option (single install/HA) : `HA`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud
- Kubernetes version (use `kubectl version`):
```
lient Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:24:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:25:33 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24876
