### ISSUE TITLE
No DNS resolution after upgrading Kubernetes 1.13 to 1.14 (Rancher 2.2.8)

### ISSUE THREAD

**Issue by Napsty** [rancher/rancher#22755]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Upgrade Kubernetes version of a cluster (through UI) from 1.13 to 1.14
Reboot all cluster nodes (one after another)

**Result:**
DNS resolution not working anymore in containers. 
Neither kube-dns or coredns pods are deployed in the kube-system namespace of this cluster. 

**Other details that may be helpful:**
Please find more details including screenshots in the Rancher forums
https://forums.rancher.com/t/no-dns-resolution-after-upgrading-kubernetes-1-13-to-1-14/15253

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM (4 vCPU, 16GB RAM)
- Kubernetes version (use `kubectl version`): 1.14.6
- Docker version: 18.9.7
- OS: Ubuntu 18.04

**Comment by superseb** [comment]
We can keep it in one place on the forum for now, there is no need to duplicate info on multiple places.

**Comment by Napsty** [comment]
@superseb  Agreed. But if it turns out to be a bug, this issue should be opened again (or marked as duplicate of an already existing issue which I was not able to find yet)
