### ISSUE TITLE
Add a global suspension button for the kubectl webshell window

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#22759]
**What kind of request is this (question/bug/enhancement/feature request):**

enhancement

**Steps to reproduce (least amount of steps as possible):**

For example, in a specific project, when you need to do some work on a workload, but the work can not be done or it's too inconvenience to done on UI, you must leave the current project level page and switch to the cluster level page, or open a new window to access the cluster page to execute the `kubectl` webshell command , which greatly affects the use experience.

So, can we add a global Launch kubectl button in the Rancher UI? This allows you to `Launch kubectl ` directly from any page. The kubectl window that opens is preferably floating and supports minimizations so that you can see the state changes of the workload in the current project in real time through commands, as well as manipulate other content on the UI.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/64745521-c4ea0000-d53a-11e9-8dd6-c8faaf13d146.png)

You can use `Tilde` (Press `~`) to go to the kubectl quickly. You don't have to go to cluster dashboard page first
