### ISSUE TITLE
[azure] "Use Private IP To Connect" setting is not persistent

### ISSUE THREAD

**Issue by elfrinjo** [rancher/rancher#22752]
When creating or editing an azure node-template, the setting "Use Private IP To Connect" is not retained on next edit when the "Public IP" field is set to "dynamic" or "static"

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a new azure node-template
- Set "Public IP" to "dynamic" or "static"
- Enable "Use Private IP To Connect"
- Edit the new template again

**Result:**
- "Use Private IP To Connect" is no longer checked

**Other details that may be helpful:**

**Environment information**
- Rancher version: 2.2.8
- Installation option (single install/HA): single node

**Comment by tfiduccia** [comment]
Version - master 9/10
This is a UI bug.  The API field "usePrivateIp": true, so we are not reading it back correctly on edit or clone.  We should fix this.

**Comment by sowmyav27** [comment]
**reproduced the issue on v2.2.8**

**Steps:**

- Create a new azure node-template
- Set "Public IP" to "dynamic" or "static"
- Enable "Use Private IP To Connect". Enter all other details. Click on create.
- Edit the template created.
- The "Use Private IP To Connect" field is unchecked.

**Validated on master-head - commit id: `805d3a42c`**

**Steps:**
- Create a new azure node-template
- Set "Public IP" to "dynamic" or "static"
- Enable "Use Private IP To Connect". Enter all other details. Click on create.
- Edit the template created.
- The "Use Private IP To Connect" field is seen checked.
