### ISSUE TITLE
Rollback for inServiceUpgrade feature

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2277]
We should provide a way of rolling back to a previous launchConfig (compose.yml) for the upgraded services. So if the user changes his mind, he can get back to the old configuration for his service.

@will-chan

**Comment by alena1108** [comment]
@aruneli more fun stuff to test is coming soon ;)

**Comment by sangeethah** [comment]
Tested with server version - v0.43.0-rc1

User has the option to "rollback" when service is in "upgraded" state and "cancelled upgrade" state.

In both the cases , all instances of the service get  back to the previous launchConfig (before upgrade was attempted).
