### ISSUE TITLE
[UI] help text to explain that when change nodeTemplate on existing cluster won't apply until scale up

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22782]
Version: v2.x
Version: master-head (v2.3) (9/10/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster
- Edit the cluster, change the nodeTempalte for one of the node pools and change something like the VM size and save.

**Result:**
The cluster updates. The UI claims (when view list of nodes in rancher ui) that the node is now of the new VM size. This is not true.

**_We should at a minimum add a small helper bubble to explain that the new node template won't take effect except for any nodes we scale up to._**

It would be better to also fix the UI so it doesn't show the new vm size for an existing node (because the old nodes actually do not get torn down and replaced with the new nodeTemplate/VM size). Technically the UI is showing what's in the nodeTemplate but when I look at the nodes list page it looks like my existing 1-cluster node is now the bigger vm size I specified...)

**Other details that may be helpful:**
I think this might be an API issue but am not certain. When we query info for the old node the API seems to be showing the new node template info / vm size.

**Comment by davidnuzik** [comment]
I opened an enhancement request to add a feature in the future to allow changing nodeTemplates for nodepools with existing nodes (no need to scale up only to see new nodes get new nodeTempalte spec, instead ALL nodes would always get updated regardless)

https://github.com/rancher/rancher/issues/22784

**Comment by tfiduccia** [comment]
@deniseschannon & @davidnuzik - This need to be separated into two distinct issues.
1.  Bug - A Developer needs to determine why we are showing incorrect info on the old nodes.  I'm not sure if this is a backend or frontend issue.
2. Design Issue - Add helper text so that user knows only new nodes will reflect size changes.  I'll take the design one.

**Comment by davidnuzik** [comment]
@tfiduccia @deniseschannon done. Backend issue: https://github.com/rancher/rancher/issues/23362

We can use this as the Design issue and I tweaked it a bit.

**Comment by tfiduccia** [comment]
Add text under "Number of nodes" to say: "Changed node template will only affect newly created nodes."

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by sowmyav27** [comment]
Verified on master- head latest 
Ui tag: latest2

Cluster --> Edit Cluster --> Text - "Changed node template will only affect newly created nodes" is seen under "Number of nodes"

<img width="1279" alt="Screen Shot 2019-11-04 at 8 34 00 PM" src="https://user-images.githubusercontent.com/26032343/68131190-9d178700-ff42-11e9-870f-71bf9c123bfc.png">
