### ISSUE TITLE
Only the latest monitoring version is available when enabling Cluster Monitoring. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#22789]
Rancher server version - Latest build from master - Sep 10 

When enabling Cluster Monitoring, only the latest monitoring version (`0.0.4`) is shown in "Monitoring Version" drop down even though versions  `0.0.1`,`0.0.2`,`0.0.3` and `0.0.4` are available for this rancher version.

UI Should not be have the logic of showing only the latest version from the list of supported versions. It should simply show all the versions available to it.

This logic should be removed from UI side.

In order to not show   `0.0.1`,`0.0.2`,`0.0.3` version for this release , system-charts for `rancher-monitoring` should set `rancher_max_version` for  `0.0.1`,`0.0.2`,`0.0.3` version to be set `2.2` . This issue is tracked in - https://github.com/rancher/rancher/issues/22788

**Comment by sowmyav27** [comment]
verified on latest master-head UI tag

Monitoring shows 4 available versions
Istio shows 2 available version.
