### ISSUE TITLE
Elasticsearch logging authorisation issue with X-Pack

### ISSUE THREAD

**Issue by chendo** [rancher/rancher#22793]
**What kind of request is this (question/bug/enhancement/feature request): ** BUG

**Steps to reproduce (least amount of steps as possible):**

1. Set up Elasticsearch cluster with X-Pack on.
2. Create an ES role called `rancher_logging` and grant `logs-* all index operations.
3. Create ES user named `rancher_logging` with password.
4. Test project logging with above credentials.
5. Test passes
6. Save logging configuration.

**Result:**

No logs are shipped to elasticsearch.

**Other details that may be helpful:**

It turns out that the logging agent performs a `HEAD /` and `GET /` and expects a 2xx before shipping logs, which is not validated when testing the logging configuration. The ES role must have `monitor` permission otherwise this request will fail and the user will have to spend time debugging what is wrong.

Either the TEST button should confirm `HEAD /` and `GET /` 2xxs accordingly, or this check should be removed.

**Environment information**
v2.2.6, single master.

**Comment by djdreidel** [comment]
same with 2.2.7 and 2.2.8 version(s) of Rancher UI.   one will also notice when selecting 'Edit from File' that nothing is actually populated.
