### ISSUE TITLE
[UI] Answers for Monitoring Disappear After Save (will return if UI is hard refreshed)

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#22801]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1. Expand advanced options for cluster monitoring
2. Add an additional answer
3. Click Save

**Result:**

Answers disappear.

**Other details that may be helpful:**

If you do a full browser refresh the answers come back, but until the UI is forced to reload they will remain gone.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.0-rc2
- Installation option (single install/HA): HA

**Comment by tfiduccia** [comment]
Version - master 9/11
Checked and this is reproducible.  All Answers disappear on Save and don't come back until you refresh the browser.

**Comment by izaac** [comment]
@tfiduccia I see the answers persist after clicking save. But in the following scenario I'm left without user entered answers wiped:

- Enter custom answers answers and save. UI will refresh and the answers persist in Advanced Options.  ✅ 
- Stay in the same page do not refresh Disable monitoring. I still see the answers in the UI.
- Do not refresh or navigate somewhere else. Click Enable
- The user entered answers are not there anymore. ❌
