### ISSUE TITLE
Upgrade hyperkube glusterfs to 4.1.5

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#22802]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

**Details:**

A customer needs the glusterfs binaries upgraded from 3.8.8 to 4.1.5. This can be accomplished by adding the following to the hyperkube dockerfile:

```
echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
apt-get update
apt-get -t stretch-backports install glusterfs-client glusterfs-common
```

It is required by their GlusterFS setup to have the newer version of the client.

**Comment by bentastic27** [comment]
Worth noting that their success may also hinge on this:

https://github.com/rancher/rancher/issues/19383

**Comment by alena1108** [comment]
The new library is available in the following images:

```
v1.16.2-rancher2
v1.15.5-rancher2
v1.14.8-rancher2
```

**Comment by sangeethah** [comment]
Tested with latest build from `v2.3-head` - `032f65c63`

Deployed cluster with K8s version - `1.15.5-rancher2-2`.

`glusterfs 4.1.5` is available from within the kubelet container.

Deployed cluster with K8s version - `v1.16.2-rancher2-1`.
```
root@santest115c1:/# glusterfs --version
glusterfs 4.1.5
```

Deployed cluster with K8s version - `v1.14.8-rancher2-1`.
root@santest114w1:/# glusterfs --version
glusterfs 4.1.5
```

root@santest116w1:/# glusterfs --version                                                                                                                                            
glusterfs 4.1.5

**Comment by sangeethah** [comment]
Automation runs on clusters with K8s versions `1.15.5-rancher2-2`  , `v1.16.2-rancher2-1` and `v1.14.8-rancher2-1` did not report any new issues.
