### ISSUE TITLE
Rename `Create Cluster Templates` global role to `Create RKE Templates`

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#22805]
We need to change the  `Create Cluster Templates` global role to `Create RKE Templates` - this is also displayed on the UI.

**Comment by tfiduccia** [comment]
@mrajashree Still called "Create Cluster Templates" on master
![image](https://user-images.githubusercontent.com/11514927/64731859-cb26a080-d496-11e9-8cd6-2b4f08fe04d3.png)

**Comment by prachidamle** [comment]
@tfiduccia I just checked on latest master, I see the role renamed:

The change should be in the image built with coomit 2bd183e6141442e87beea1d0ea958c1d855e15cc

<img width="1411" alt="Screen Shot 2019-09-11 at 1 31 51 PM" src="https://user-images.githubusercontent.com/1470602/64732925-9c112e80-d498-11e9-9a26-dcb0e7768cff.png">
