### ISSUE TITLE
the some host display on the rancher ui

### ISSUE THREAD

**Issue by ryanli870929** [rancher/rancher#22815]
hi，i have installed therancher 2.2.8。but when i login into the UI。i find that there are two host with some ip address and Different machine id。

the node in the k8s cluster：
# kubectl  get nodes
NAME        STATUS   ROLES                      AGE   VERSION
10.0.7.28   Ready    controlplane,etcd,worker   39h   v1.14.6
10.0.7.63   Ready    controlplane,etcd,worker   39h   v1.14.6
10.0.7.69   Ready    controlplane,etcd,worker   39h   v1.14.6

the ui display：
![image](https://user-images.githubusercontent.com/3827331/64749603-c3bfcf80-d548-11e9-8a7b-08b8647aafba.png)
one machine id：local:machine-s27w2
another machine id: local:machine-sw5n5

how can i fix this problem?

**Comment by superseb** [comment]
Please provide more info on how to reproduce the issue. Giving this seems to be the `local` cluster,  you are using HA and have used RKE to create the cluster. Please share the `cluster.yml` used, the agents logs (https://rancher.com/docs/rancher/v2.x/en/troubleshooting/imported-clusters/) and at what time the issue occurs exactly (is it seen directly or did you run `rke up` again or something else)

**Comment by superseb** [comment]
Let us know when you can provide the requested info.
