### ISSUE TITLE
k8s v1.16.0-beta.1 cluster provisioning fails with aws cloud provider 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#22814]
rancher/rancher:master-head 80f300b37487 

- Create RKE Amazon EC2 Cluster with cloud provider enabled. Make sure to enter IAM profile name in node template. 
- Cluster provisioning fails with msg on the lines of `failed to bring up worker plane: node not found` 
- Works with v1.15 

`kube-proxy` logs from 1.15: 
```
W0912 00:16:02.268231   14433 server_others.go:249] Flag proxy-mode="" unknown, assuming iptables proxy
W0912 00:16:02.278599   14433 node.go:113] Failed to retrieve node info: nodes "sangee-wc1" not found
I0912 00:16:02.278634   14433 server_others.go:143] Using iptables Proxier.
W0912 00:16:02.278739   14433 proxier.go:316] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP
I0912 00:16:02.280104   14433 server.go:534] Version: v1.15.3
I0912 00:16:02.302670   14433 server.go:550] Running in resource-only container "/kube-proxy"
``` 

from 1.16:
```
W0912 01:10:06.956236   17680 server_others.go:250] Flag proxy-mode="" unknown, assuming iptables proxy
E0912 01:10:06.966309   17680 node.go:124] Failed to retrieve node info: nodes "sanwc116-node1" not found
E0912 01:10:07.973511   17680 node.go:124] Failed to retrieve node info: nodes "sanwc116-node1" not found
E0912 01:10:10.050642   17680 node.go:124] Failed to retrieve node info: nodes "sanwc116-node1" not found
E0912 01:10:14.310481   17680 node.go:124] Failed to retrieve node info: nodes "sanwc116-node1" not found
E0912 01:10:23.060735   17680 node.go:124] Failed to retrieve node info: nodes "sanwc116-node1" not found 
```

Not sure if related, kubelet logs from 1.16: 
```
W0912 02:09:48.028419    8415 setters.go:150] replacing cloudprovider-reported hostname of ip-172-31-13-98.ap-northeast-1.compute.internal with overridden hostname of ip-172-31-13-98
```
followed by cni uninitialized msgs 
``` 
W0912 02:09:51.467083    8415 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
E0912 02:09:52.659987    8415 kubelet.go:2186] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
W0912 02:09:56.467358    8415 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
E0912 02:09:57.679520    8415 kubelet.go:2186] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

**Comment by alena1108** [comment]
Per offline discussion with @kinarashah the issue existed since `v2.3.0-rc1`; tested with canal cni. Can be possibly related to https://github.com/kubernetes/kubernetes/commit/dd9402f4514c4c268e10a1c8be74c67006527657

**Comment by superseb** [comment]
The code added in https://github.com/kubernetes/kubernetes/pull/77167 makes not being able to resolve the node IP a hard error vs a soft error before 1.16. The change is made because the IP is needed when using ipvs proxier for nodeport services. We don't use/support that today, our kube-proxy defaults to iptables proxier.

This is what happens on 1.15:

```
W0918 11:55:41.522203       1 server_others.go:249] Flag proxy-mode="" unknown, assuming iptables proxy
W0918 11:55:41.532599       1 node.go:113] Failed to retrieve node info: nodes "seb-yolotest1" not found
I0918 11:55:41.532629       1 server_others.go:143] Using iptables Proxier.
W0918 11:55:41.532707       1 proxier.go:316] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP
```

Quick fix/workaround is to use `--bind-address=127.0.0.1`, setting this via `extra_args` will make the cluster come up. Have to run some more tests on how to see how this is supposed to work with aws cloud provider.

**Comment by jiaqiluo** [comment]
The bug is reproduced in  Rancher: v2.3.1, the steps are the same as the issue provides.

The RKE cluster is configured with a could provider (AWS).

**Comment by sangeethah** [comment]
https://github.com/rancher/rancher/pull/23550

**Comment by sangeethah** [comment]
https://github.com/rancher/rancher/pull/23550

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version b160c76c8`

Create RKE Amazon EC2 Cluster with cloud provider enabled with `IAM Instance Profile Name` in node template.
Cluster provisioning succeeds.
![Screen Shot 2019-11-15 at 2 00 40 PM](https://user-images.githubusercontent.com/57409052/68975532-c17c2a80-07b0-11ea-834f-fcbde3133a4d.png)
