### ISSUE TITLE
Legacy logging and alerting images

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#22816]
Found legacy image in https://github.com/rancher/rancher/releases/tag/v2.3.0-rc3 rancher-images.txt
rancher/alertmanager-helper:v0.0.2
rancher/prom-alertmanager:v0.15.2
rancher/fluentd-helper:v0.1.2
rancher/fluentd:v0.1.11
rancher/log-aggregator:v0.1.4

**Comment by sangeethah** [comment]
Wait for rc4 to validate this issue.

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher:v2.3.0-rc4

All the images mentioned in the issue are either removed or updated to a newer version in the `rancher-images.txt` file from both the UI and the Github release page
