### ISSUE TITLE
Add service container to existing loadbalancer during creation by rancher-compose

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#2282]
Is it possible to add a new service like web container to an existing LB during creation by rancher-compose?

Example
In the default stack is a global loadbalancer for http requests by domain to the backend web container inside stacks.
During creation of the new stack "test" the web container of the service should be added to the global http lb as target.

**Comment by deniseschannon** [comment]
In the next release of rancher-compose and rancher, you should be able to use a selector link on a load balancer (https://github.com/rancher/rancher/issues/2239), which would allow any additional services to be linked to an existing service. 

Note: there is one known use case that is still missing after selectors are release, which is that hostname routing rules can not be applied to selector links. There is an enhancement to track that use case https://github.com/rancher/rancher/issues/2288
