### ISSUE TITLE
Add Windows node failed after add layer-4 load balancer

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#22826]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Launch a GCE cloud provider windows cluster
2. Add a Linux node with the all role
3. Deploy an Nginx workload and configure Layer-4 load balancer
4. Continue to add the windows node

**Result:**

`cattle-node-agent-windows` failed to start, error log:

![image](https://user-images.githubusercontent.com/19684717/64757179-e4e1e980-d563-11e9-97b9-57e259576d91.png)

![image](https://user-images.githubusercontent.com/19684717/64757200-f88d5000-d563-11e9-8886-eded6cef0a4b.png)

![image](https://user-images.githubusercontent.com/19684717/64759755-ac91d980-d56a-11e9-91d2-22e074c2ccf1.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher/rancher:master-head(09/12/2019)
- Installation option (single install/HA):
single

**Cluster information**

- Kubernetes version (use `kubectl version`):  v1.15.3

**Comment by thxCode** [comment]
It seems the GCE cloud provider modified the `cbr0` HNS network with LB address, then led to the failure of bootstrapping flanneld: https://github.com/coreos/flannel/blob/288fb58f91f5a157a7b14df2ce56604df5024829/main.go#L210-L213

As a workaround, we need to drop the previous LB and then add the fresh Windows host. For the existing failed host, we could try to clean up it via `c:\etc\rancher\cleanup.ps1`.
