### ISSUE TITLE
AWS Instances Launched via Node Templates Do Not Take Requested Hostname

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#22838]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a Node Template that use AWS
2. Launch a Node

**Result:**

1. Host does not take requested hostname, neither RancherOS or Ubuntu

**Other details that may be helpful:**

IMHO the best way to solve this is to generate a default cloud-config and if a user provides UserData manually via the API, merge the two together with the user provided one taking precendence.

Using the cloud-config to test the hostname ensures that the hostname is actually taken (at least with cloud-config compatible operating systems).

The biggest problem I'm running into right now is that when RancherOS gets added to kubernetes, the kubernetes.io/hostname gets set to the friendly-name/requested-name, but the node name in kubernetes is the AWS ip-X-X-X-X hostname. This leads to the inability to schedule OpenEBS volumes for example because it creates scheduling rules based on the node name targeting the kubernetes.io/hostname which do not match. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.7 & 2.3.0-rc3
- Installation option (single install/HA): HA

**Comment by superseb** [comment]
Node resource name being changed when AWS cloudprovider is configured is expected. There is a lot of discussion about this behavior in https://github.com/kubernetes/kubernetes/issues/48929 and https://github.com/kubernetes/kubernetes/pull/76689 and many other places. As far as I can find, currently there is no way to override the Node name set by the aws cloud provider. This would mean if we fix this on our side, we sync the node name to the label to make them match. There are missing pieces regarding cloud provider setting the node resource name and labels and our agents that use the initially set hostname as well which is not used to validate the node when the agent comes in, this is described in https://github.com/rancher/rancher/issues/17431. I'll probably merge this into there to address the gaps, unless you say it is fixable by setting a hostname via cloud-config as this seems to be unrelated, as the cloud provider changes the node resource name while the hostname is set correctly on the node itself.

**Comment by ekristen** [comment]
I’m pretty sure it’ll get set to the correct hostname if the hostname is set correctly. Which just doesn’t seem to happen with node templates and docker machine by default.

I’ll try and test this by manually setting user data today.

**Comment by ekristen** [comment]
Well the hostname does get set properly when using cloud config but since there's no way to dynamically change the cloud config per instance when using a node pool is value is pretty limited.

However it seems that README for the provider clearly states that internal DNS will be used for host names. 

So I wonder if Rancher 2 needs to make sure that the kuberentes.io/hostname matches when the cloud provider is enabled? 

Feel free to close/merge this into another issue, as long as it's being tracked.

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/22849
