### ISSUE TITLE
API call to create service does not honor launchConfig/logConfig option

### ISSUE THREAD

**Issue by ccirello** [rancher/rancher#2283]
When making a service creation call specifying log driver, rancher daemon does not honor logConfig options. For this call:
```json
{
    ...
    "launchConfig": {
        "logConfig": {
            "config": {
                "fluentd-address": "10.0.1.28:24224"
            },
            "driver": "fluentd"
        },
    },
    "name": "test-logging",
    ...
}
```

I get on container dashboard:
```ShellSession
d4f15c9c-9a5c-44cd-b939-58c1c6d4716a : LogConfig.type must be one of (json-file, syslog, none)
```

If I send: 
```json
{
    ...
    "launchConfig": {
        "logConfig": {
            "driver": "fluentd"
        },
    },
    "name": "test-logging",
    ...
}
```

It does not seem to be doing anything whatsoever connecting to a local fluentd.

**Comment by deniseschannon** [comment]
This was added in Docker 1.8 (I think), so we just need to enable it for our API.

**Comment by alena1108** [comment]
@deniseschannon its already supported in our APIs. 

@ibuildthecloud looks like docker-py we use, needs to be upgraded, to enable support for all the drivers latest docker/docker-py supports.

**Comment by deniseschannon** [comment]
Closed in favor of https://github.com/rancher/rancher/issues/2313
