### ISSUE TITLE
Oracle Enterprise Linux Test

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#22839]
Validate Oracle Enterprise Linux and Rancher 2.3 work together.

Deploy Rancher HA control plane with RKE CLI.
Deploy custom downstream cluster
Deploy EC2 node driver cluster with OEL AMI

**Comment by jiaqiluo** [comment]
found a bug during validation: https://github.com/rancher/rancher/issues/23329

**Comment by jiaqiluo** [comment]
The workaround is to delete all rules in the iptables before installing docker 
```
sudo iptables -F
```

**Comment by jiaqiluo** [comment]
Two setups are used for the validation tests:

- Setup 1: install Rancher in a ubuntu box, then add a custom cluster which uses Oracle Enterprise Linux 
- Setup 2: install Rancher in HA mode which has 3 nodes using Oracle Enterprise Linux, then add a custom cluster which uses the same Oracle Enterprise Linux   

Configuration of the custom cluster:
 
- AMI: OL7.6-x86_64-HVM-2019-01-29 (ami-062fed7f76f714d8d)
- Docker version 19.03.3, build a872fc2f86
- 1 control plane, 3 etcd, 3 worker
 

The following tests are done on the custom cluster:

- API test on workload, DNS, service discovery, ingress, secret, registry, catalog app, NFS storage
- cluster and project monitoring

**Comment by sangeethah** [comment]
https://github.com/rancher/rancher/issues/23384
