### ISSUE TITLE
Monitoring - Garafana is not working after upgrading Rancher 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#22843]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:v2.2.8 in airgap HA mode with the chart variable `CATTLE_SYSTEM_CATALOG  = external` which is the default value
- add a custom cluster 
- enable the cluster and project monitoring 
- confirm the monitoring works, and Grafana works as well
- upgrade Rancher to v2.3.0-rc3 
- Since I host the system chart by myself, and there is no new version for monitoring to upgrade to 

**Result:**
- Both the cluster and project Garafana stop working
- Can not open the link to Grafana from the app 

<img width="722" alt="Screen Shot 2019-09-12 at 3 03 16 PM" src="https://user-images.githubusercontent.com/6218999/64830425-35b60a00-d585-11e9-9571-d2b15e49859e.png">

- the specific target is unhealthy in Prometheus

<img width="958" alt="Screen Shot 2019-09-12 at 3 04 42 PM" src="https://user-images.githubusercontent.com/6218999/64830439-4797ad00-d585-11e9-99c6-a5867807bb60.png">

- Grafana related pods restart once

<img width="1470" alt="Screen Shot 2019-09-12 at 5 48 13 PM" src="https://user-images.githubusercontent.com/6218999/64830501-96dddd80-d585-11e9-81b9-502b6c04c809.png">

- The events of the  Workload: grafana-cluster-monitoring
```
Normal 	SandboxChanged 	Pod sandbox changed, it will be killed and re-created. 	an hour ago
Normal 	Killing 	Stopping container grafana 	an hour ago
Normal 	Killing 	Stopping container grafana-proxy 	an hour ago
Normal 	Pulled 	Container image "ec2-13-57-47-108.us-west-1.compute.amazonaws.com:443/rancher/grafana-grafana:5.4.3" already present on machine 	an hour ago
Normal 	Created 	Created container grafana-init-plugin-json-copy 	an hour ago
Normal 	Started 	Started container grafana-init-plugin-json-copy 	an hour ago
Normal 	Pulled 	Container image "ec2-13-57-47-108.us-west-1.compute.amazonaws.com:443/rancher/prometheus-auth:v0.2.0" already present on machine 	an hour ago
Normal 	Created 	Created container grafana-init-plugin-json-modify 	an hour ago
Normal 	Started 	Started container grafana-init-plugin-json-modify 	an hour ago
Normal 	Pulled 	Container image "ec2-13-57-47-108.us-west-1.compute.amazonaws.com:443/rancher/grafana-grafana:5.4.3" already present on machine 	an hour ago
Normal 	Created 	Created container grafana 	an hour ago
Normal 	Started 	Started container grafana 	an hour ago
Normal 	Pulled 	Container image "ec2-13-57-47-108.us-west-1.compute.amazonaws.com:443/rancher/nginx:1.15.8-alpine" already present on machine 	an hour ago
Normal 	Created 	Created container grafana-proxy 	an hour ago
Normal 	Started 	Started container grafana-proxy 	an hour ago
Warning 	Unhealthy 	Readiness probe failed: Get http://172.17.0.2:3000/api/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) 	an hour ago
Warning 	Unhealthy 	Readiness probe failed: Get http://172.17.0.2:3000/api/health: dial tcp 172.17.0.2:3000: connect: no route to host 	an hour ago
```

- after a while, the event is cleaned up and gone, but the worklaods is not re-deployed 

<img width="1495" alt="Screen Shot 2019-09-12 at 5 49 35 PM" src="https://user-images.githubusercontent.com/6218999/64830533-bffe6e00-d585-11e9-8a2e-e401cd810f97.png">

More info
- not see this error in the test from v2.2.8 to v2.3.0-rc2

**Comment by leodotcloud** [comment]
@jiaqiluo Since the setup is not around any more and also there are not enough logs I won't be able to continue debugging unless you can reproduce it again.

The Pod getting the IP `172.17.0.2` is definitely not a good sign. It should have been something like `10.42.x.x`. Would need to look at kubelet logs, and output of `docker inspect` for those problematic containers.

**Comment by jiaqiluo** [comment]
Failed to reproduce the bug with the same steps in a new setup. 

This time I have two clusters with cluster monitoring and project monitoring enabled before upgrading and both work fine after upgrading Rancher. 

Will do more tries when new RCs comes.

**Comment by leodotcloud** [comment]
@jiaqiluo were you able to reproduce this issue with any of the later builds? If not, could you close this issue?

**Comment by jiaqiluo** [comment]
This issue is closed since is not reproduced in later builds.
