### ISSUE TITLE
Disabling AWS Cloud Provider Breaks Existing Cluster

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#22851]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Create Cluster using Node Templates on AWS
2. Do a single Etcd/Control Node and 1 Worker node
3. Disable AWS cloud provider

**Result:**

The cluster will break.   More specifically kubectl still works, but the cluster goes unhealthy in Rancher 2, the node agent will be unable to connect.

The etcd/control node will go offline because the cattle agent will change it's information to the requested hostname and no longer match the node information registered in k8s. 

**Other details that may be helpful:**

Once you disable it, I get a Cluster spec validation error and cannot turn it back on.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.7
- Installation option (single install/HA): HA

**Comment by superseb** [comment]
The agent issue is handled in https://github.com/rancher/rancher/issues/22849

**Comment by jiaqiluo** [comment]
This is reproduced in v2.3.2

- add an ec2 cluster using RancherOS and cluster provider enabled
- 1 etcd, 1 control plane, 2 worker
- wait for the cluster to be active
- edit the cluster to set cloud provider to None

Results:
- failed to update the cluster
- etcd and control plane nodes are failed to connect

<img width="1425" alt="Screen Shot 2019-11-06 at 11 22 41 AM" src="https://user-images.githubusercontent.com/6218999/68325981-ca218200-0087-11ea-9240-09c5b6fd30d3.png">

**Comment by jiaqiluo** [comment]
This is reproduced in v2.3-head 4f04dda

- add an ec2 cluster using RancherOS and cluster provider enabled
- 1 etcd, 1 control plane, 2 worker
- wait for the cluster to be active
- edit the cluster to set cloud provider to None

Results:
- all nodes go to a bad state

<img width="1172" alt="Screen Shot 2019-11-06 at 1 32 26 PM" src="https://user-images.githubusercontent.com/6218999/68335551-e4fcf200-0099-11ea-9bdb-4067cca0e034.png">

**Comment by superseb** [comment]
My suggestion would be to implement https://github.com/rancher/rancher/issues/22852, similar as what we do with network provider. Choose one on cluster creation and be able to change any configuration of it, but block changing it.

**Comment by ekristen** [comment]
Long term I think that’s great. 

If there’s any work around for Disabling a cloud provider now for older clusters that would be great!

I have one I don’t want to rebuild but will if I have too.

**Comment by deniseschannon** [comment]
We are going to implement https://github.com/rancher/rancher/issues/22852, which means you won't be able to disable cloud providers in the future. 

Unfortunately @ekristen I think you'll have to rebuild your cluster. I'm going to close this in favor of #22852
