### ISSUE TITLE
Prevent Disabling of Cloud Provider Once Set

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#22852]
**What kind of request is this (question/bug/enhancement/feature request):** feature request

**Result:**

Disabling the cloud provider can break the cluster as hostnames and node names will change and cause mass confusion to k8s and rancher 2 when it comes to the node agents and connectivity.

Attempting to re-enable can lead to cluster spec validation errors depending on what state Rancher 2 believes the cluster is in.

**Other details that may be helpful:**

See Related Bug https://github.com/rancher/rancher/issues/22851

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.7
- Installation option (single install/HA): HA

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by soumyalj** [comment]
In v2.3.0 , created a cluster with Azure cloud provider. Edit the cluster and we do have an option to disable the cloud provider .
<img width="730" alt="Screen Shot 2019-11-11 at 11 25 55 AM" src="https://user-images.githubusercontent.com/18536626/68614589-1436a900-0476-11ea-8afd-d748d77ad80a.png">

Tested with rancher v2.3-head. 
Create a cluster with Azure cloud provider. 
Edit the cluster and the option to disable the cloud provider is not presented in the UI anymore
<img width="756" alt="Screen Shot 2019-11-11 at 11 28 11 AM" src="https://user-images.githubusercontent.com/18536626/68614742-624bac80-0476-11ea-9048-af48fa6179a9.png">
