### ISSUE TITLE
[UI] Partner apps label is hard to read in Dark Mode

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#22859]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement/Bug

**Steps to reproduce (least amount of steps as possible):**
Use Dark Mode from Preferences.
Go to Apps in Global/Projects, check the Partners App labels.

**Result:**

The contrast of that word plus combined with the gold color that surrounds it makes it hard to read.

![Screen Shot 2019-09-13 at 1 39 06 PM](https://user-images.githubusercontent.com/27659/64893555-305fca80-d62c-11e9-906d-c79e2fd7473d.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version: `master-head (v2.3) (09/13/2019)`
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sowmyav27** [comment]
**Verified on 2.3-head latest**
ui tag: `https://releases.rancher.com/ui/latest-2.3/index.html`

- Use Dark Mode from Preferences.
- Go to Apps in Global/Projects, check the Partners App labels.
