### ISSUE TITLE
can't hide the port in url

### ISSUE THREAD

**Issue by wohenbushuang** [rancher/rancher#22869]
I have set the base URL without the `8080` port, and use apache2 for reverse proxy. It could open the webpage using url without the `8080` port, but latter when I click some buttons, api request will use `127.0.0.1:8080` and then result in a fail page. If I enter url with `:8080`, everything works fine. However, I still want to hide the port postfix in url.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.28` Cattle: `v0.183.79` UI: `v1.6.50` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by vincent99** [comment]
You need to set the x-forwarded-port header..  https://rancher.com/docs/rancher/v2.x/en/installation/single-node/single-node-install-external-lb/#3-configure-load-balancer
