### ISSUE TITLE
Rancher Cluster keeps recreating

### ISSUE THREAD

**Issue by MatteoJoliveau** [rancher/rancher#22868]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Context**
At my company, we have an internal Kube cluster, managed by Rancher on EC2 machines. We use Velero to back up applications and persistent volumes. We regularly do test restores to ensure backups are fine, and we do this by creating a mirror copy of the cluster and simulating a disaster recovery scenario. After last Monday's restore session, the mirror cluster cannot be deleted. When destroyed using `rancher rm` or the UI it correctly tears down all machines and disappears, only to start reprovisioning after some times (ranging from 15 minutes to 1 hour).

Editing the cluster also doesn't work, as it will reset itself to the configuration that was provided when first created last week.

**Steps to reproduce:**
- Export existing cluster with `rancher cluster export $NAME > rancher-cluster.yml`
- Change cluster name in YAML file to something else (`NEW_NAME` in this example). We also changed the node prefixes to avoid clashing, as it was run on the same AWS account as the main one.
- `rancher up -f rancher-cluster.yml`
- `rancher rm $NEW_NAME`

**Result:**
After some time (a few minutes normally) the deleted cluster will come back and reprovision.

**Environment information**
- Rancher version: `rancher/rancher:2.2.0-rc13`
- Installation option: single install

**Cluster information**
- Cluster type: Infrastructure Provider (AWS EC2)
- Machine type: cloud instances, mainly `t3.medium`
- Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-29T18:43:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
I don't have SSH to the machine ATM, the installer configured in Rancher settings is `18.09`.

**Comment by superseb** [comment]
We need a lot more information here, please specify exact steps to reproduce and logging from Rancher. Also running RC is not recommended, and 2.2.0 is 6 months old so it's recommended to upgrade to the latest version if you avoid running into known bugs.
