### ISSUE TITLE
docker install gets stuck due to interactive prompt of libssl1.1:amd64

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#22867]
- Create a linode instance running Ubuntu 18.04 LTS
- Run: `curl -sSL https://raw.githubusercontent.com/rancher/install-docker/master/18.09.6.sh | sh -`
- The installation stops due to the interactive prompt of libssl1.1:amd64

This causes a lot of problems during automation when using terraform/ansible.

Workaround:
```
export DEBIAN_FRONTEND=noninteractive
```

<img width="561" alt="Screen Shot 2019-09-14 at 8 45 13 AM" src="https://user-images.githubusercontent.com/19392926/64910536-48872680-d6cc-11e9-8ea3-1c15193b76af.png">

Looks like the workaround is being used in docker-machine: https://github.com/docker/machine/blob/7a9ce457496353549916e840874012a97e3d2782/libmachine/provision/debian.go#L63

**Comment by leodotcloud** [comment]
Decided not to fix it, as an user can just set the environment variable before invoking this script.

**Comment by phillycheeze** [comment]
Thanks for posting the workaround. This happened to me too, as the rancher quickstart repository doesn't have this flag and fails

**Comment by yyds-tang** [comment]
thanks，解决了ansible卡住的问题
export DEBIAN_FRONTEND=noninteractive
