### ISSUE TITLE
unknown flag --quiet running the rancher-save-images.sh with docker 18.06

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#22878]
**Rancher version**
v2.3.0-rc3

**Steps to reproduce (least amount of steps as possible):**
Prepare images for air-gapped environments, run the following step:
```
$ rancher-save-images.sh --image-list ./rancher-images.txt
```

**Result:**
```
unknown flag: --quiet
See 'docker pull --help'.
Image pull failed: busybox
unknown flag: --quiet
See 'docker pull --help'.
Image pull failed: quay.io/jetstack/cert-manager-cainjector:v0.9.1
unknown flag: --quiet
...
```
**Other details that may be helpful:**
This flag is added in docker 19.03(https://github.com/moby/moby/issues/13588#issuecomment-448985916), so is not available in the supported versions(17.03.x, 18.06.x, ~~18.09.x~~)

Edit:
Checked that the option is available in docker 18.09.9

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/22936

**Comment by jiaqiluo** [comment]
The bug fix is validated with the `rancher-save-images.sh` from release `v2.3.0-rc6`

The option ` --quiet` is removed and running `./rancher-save-images.sh --image-list ./rancher-images.txt` will pull and save images successfully.
