### ISSUE TITLE
Can not find RKE state file: open /var/lib/rancher/management-state/rke/rke-156711546/cluster.rkestate: no such file or directory

### ISSUE THREAD

**Issue by taibc** [rancher/rancher#22872]
Hi. I cleaned all nodes on my cluster (as the guide  https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/ ), then I re-installed rancher server using the command: 

`sudo docker run -d --name rancher_server --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:v2.2.7
`
Then, I created a custom cluster and after adding the new node (include both master and etcd), I got the error: 

`Can not find RKE state file: open /var/lib/rancher/management-state/rke/rke-156711546/cluster.rkestate: no such file or directory`

Do you know how to fix this ?
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.7` UI: `v2.2.93` |
|Route|`global-admin.clusters.index`|

**Comment by zeidoo** [comment]
http://bbs.xuegod.cn/thread-2555-1-1.html

According to this Chinese forum post (I just looked at the pictures, I don't speak Chinese), it might have something to do with your node's hostname.

I changed my hostname from having underscores "_" to having hyphens "-" and this error went away.

**Comment by lucasctd** [comment]
@taibc were u able to fix this?
I have three hyper v virtual machines running Ubuntu Server 18.04 here. I have Rancher Single Node in one, a etcd node and another as worker and contropanel node.
Once I have registered the nodes, I got the same message in the dashboard, I have no idea what's wrong.

**Comment by lucasctd** [comment]
@zeidoo It solved my problem, thank you so much xD

**Comment by sudhirbitsgoa** [comment]
I'm facing the same issue while setting up locally with hostname as 0.0.0.0

**Comment by superseb** [comment]
Thanks for reporting, I am merging this into https://github.com/rancher/rancher/issues/25376

**Comment by PhilipSchmid** [comment]
Thanks @zeidoo for the hint with the node name! My problem was a `.` at the end of the node names...

(In a Rancher version `2.4.5` RKE HA K8s 3 node setup.)

Regards,
Philip

**Comment by tskinnerarlo** [comment]
i am still a bit of a rancher nube, how do you rename nodes without rebuilding whole cluster? I know I have underscore in my node names

**Comment by ilker1997-69** [comment]
I have a similar problem, I try to use rke for the cluster but I get:  FATA[0003] Failed to write state file: open ./rancher-cluster.rkestate: permission denied
I could solve the problem.
