### ISSUE TITLE
Choose which node to delete when scaling down

### ISSUE THREAD

**Issue by pthrasher** [rancher/rancher#22871]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1. Navigate to nodes page
2. Scale down a node pool

**Result:**
The one I didn't want deleted was deleted.

**Expected Result:**
To be able to choose which node to remove.

**Question:**
Is there some alternate way for me to delete a node and scale down at the exact same time? I need to scale down by 1 and I need to choose the node that gets deleted.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.8
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider (aws)

gz#9849
gz#12232
gz#11020

gz#14529

**Comment by dkeightley** [comment]
Additionally, when not choosing a node, Rancher defaults to the oldest node. This is not ideal in all circumstances, for eg: if it's the only good node in the cluster at the time. The oldest of the non-Active nodes should take precedence when selecting a node to remove in a scale down.

**Comment by deniseschannon** [comment]
This enhancement should be implemented as:

* Ability to select which node(s) to delete when scaling down based on node ID(s)/node name(s)
* Ability to select whether or not to drain the node before terminating the nodes

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/27458

**Comment by ricky-sb** [comment]
@pthrasher, do you have a workaround for this?

**Comment by sowmyav27** [comment]
**On 2.5.6-rc5**

- Deployed a node driver cluster - 3 worker node, enable Drain on delete
- Deploy a deployment with replicas on W1, W2 and W3
- Select W1, W3 and "Scale Down"
- Nodes W1 and W3 get drained. The pods are rescheduled on W2.
- And the nodes W1 and W3 are deleted
- Scale up Worker nodes by 2
- W1, W2, W3 are available.

**Comment by luthermonson** [comment]
Feature adds new member to the v3 node spec called 'scaledownTime' which is defaulted to empty. When set as an rfc3339 time stamp the node pool will delete the node and decrement the pool removing the node from the pool. This allows you to select which node to remove from the pool.

Note... the scale down event is kept in memory, if rancher is restarted the K8s client go enqueue event will be lost. if rancher comes back up the node will delete when the pool is updated so just know you may have to trigger the scale down again or edit the pool some how to get it to trip and enter the controller logic.

**Comment by sowmyav27** [comment]
**On 2.5.6-rc5**

- Set scaleDownTime for a node (invalid value). Error seen in logs: `2021/02/21 01:50:34 [ERROR] [nodepool] failed to parse scaledown time, is it in RFC3339? 2021-02-21 01:48:00.52Z: parsing time "2021-02-21 01:48:00.52Z" as "2006-01-02T15:04:05Z07:00": cannot parse " 01:48:00.52Z" as "T"`
- in future - 5 minutes from when being set . `2021-02-20T18:35:42+00:00` Logs show and the node scales down
```
2021/02/21 02:31:53 [DEBUG] [node] enqueing nodepool np-pbz5r for scaledown in 3m48.896188285s
```
- time is in the past, the node scales down immediately.

**Comment by anupama2501** [comment]
On master-head[master-dbf18389c36b56983c9848c1de1832faea2fc0a6-head]

1. Deployed a node driver cluster - 4 worker node, 2 control plane enable Drain on delete
2. Set scale down time to one of the worker nodes to a future time.
3. At the time set from step 2, the node is not deleted.
4. Perform either scale up node or send an API request setting the scale-down time on a different node. Once the request is sent, the node gets deleted from option 2 immediately.

**Comment by anupama2501** [comment]
The above issue is seen on v2.5-a85f4d1f87feea0083ebf8ae517a140f39de7fbd-head as well.
Followed same steps as above and see the node deletion happens only by scaling another node up/down.

The issue on v2.5-head is not happening always

**Comment by sowmyav27** [comment]
Logged [issue](https://github.com/rancher/rancher/issues/31507) for the issue seen when scaleDownTime set in future

**Comment by anupama2501** [comment]
Rancher | v2.5-361d3a420bb0d08763d157cd5fd1dfc37a3ccf29-head
Verified the test scenario:

- Create a cluster - 3 etcd, 2 cp, 3 worker nodes.
- For a worker node W1 set scaledownTime (From View in API of the node)
- Restart Rancher
- Wait to see if the node gets deleted - Node wasn't deleted - PASS
- If it does not, edit node pool of the worker node change by scaling up.Check if the worker node W1 gets deleted - PASS
[Node wasn't deleted] - PASS
- Node was deleted at the time scheduled.

**Comment by anupama2501** [comment]
Rancher | master-465bb3b80cb9f2d8c002fa9d7c37be20d38ed411-head

1. Create a cluster - 3 etcd, 2 cp, 3 worker nodes.
2. For a worker node W1 set scaledownTime to a future time(From View in API of the node)
3. Restart Rancher
4. Verified node doesn't get deleted at the future time set.
5. After the time set in step 2 has passed, if we scale up/down another node, the W1 gets deleted 
will be validated as part of  https://github.com/rancher/rancher/issues/31523

**Comment by oxr463** [comment]
During a Support call, we attempted to Scale Down a couple of worker nodes in a pool.

The first node immediately scaled down. For the second two, we needed to Cordon, then Drain, and then Scale Down.

Clicking Scale Down before Cordoning and Draining gave no indicators or warnings. Once the application workloads were finally gone, the node(s) simply disappeared.

Is this the desired behavior? It seems like the UI/UX could be improved so that the Scale Down button is greyed out until the node has been drained.

**Comment by sowmyav27** [comment]
@oxr463 Can you give us more details on these:
- What rancher version is this? 
- What is the cluster config? 
- Is the issue related to "Scale Down" option not _greyed out_ when a node is draining? If so, could you please log a separate issue for this

**Comment by oxr463** [comment]
> @oxr463 Can you give us more details on these:

Per the customer.
 
>     * What rancher version is this?

Rancher: v2.5.6 

>     * What is the cluster config?

```
nodes:
  [{"nodeName": "c-998mx:m-7ps7b", "address": "10.7.3.45", "port": "22", "internal_address": "10.7.3.45",
      "role": ["etcd"], "hostname_override": "sspp-web-cp-preprod-etcd-0-us-east-1a1",
      "user": "centos", "sshKey": "[ . . . REDACTED . . . ]", "ssh_key_path": "~/.ssh/id_rsa", "labels": {"cattle.io/creator": "norman"}},
    {"nodeName": "c-998mx:m-95qks", "address": "10.7.5.217", "port": "22", "internal_address": "10.7.5.217",
      "role": ["controlplane"], "hostname_override": "node1",
      "user": "centos", "sshKey": "[ . . . REDACTED . . . ]", "ssh_key_path": "~/.ssh/id_rsa", "labels": {"cattle.io/creator": "norman"}},
    {"nodeName": "c-998mx:m-cl792", "address": "10.7.5.105", "port": "22", "internal_address": "10.7.5.105",
      "role": ["etcd"], "hostname_override": "node2",
      "user": "centos", "sshKey": "[ . . . REDACTED . . . ]", "ssh_key_path": "~/.ssh/id_rsa", "labels": {"cattle.io/creator": "norman"}},
    {"nodeName": "c-998mx:m-hx7f2", "address": "10.7.4.240", "port": "22", "internal_address": "10.7.4.240",
      "role": ["etcd"], "hostname_override": "node3",
      "user": "centos", "sshKey": "[ . . . REDACTED . . . ]", "ssh_key_path": "~/.ssh/id_rsa", "labels": {"cattle.io/creator": "norman"}},
    {"nodeName": "c-998mx:m-k4fkh", "address": "10.7.3.195", "port": "22", "internal_address": "10.7.3.195",
      "role": ["controlplane"], "hostname_override": "node4",
      "user": "centos", "sshKey": "[ . . . REDACTED . . . ]", "ssh_key_path": "~/.ssh/id_rsa", "labels": {"cattle.io/creator": "norman"}},
    {"nodeName": "c-998mx:m-lmcq2", "address": "10.7.4.8", "port": "22", "internal_address": "10.7.4.8",
      "role": ["controlplane"], "hostname_override": "node5",
      "user": "centos", "sshKey": "[ . . . REDACTED . . . ]", "ssh_key_path": "~/.ssh/id_rsa", "labels": {"cattle.io/creator": "norman"}}]

services:
  {"etcd": {"image": "rancher/coreos-etcd:v3.4.14-rancher1", "extraArgs": {"election-timeout": "5000",
        "heartbeat-interval": "500"}, "snapshot": false, "retention": "12h", "creation": "6h",
      "backupConfig": {"enabled": true, "intervalHours": 3, "retention": 24, "s3BackupConfig": {
          "accessKey": "[ . . . REDACTED . . . ]", "secretKey": "[ . . . REDACTED . . . ]",
          "bucketName": "etcd-backups", "region": "us-east-2", "endpoint": "s3.amazonaws.com"},
        "timeout": 300}}, "kubeApi": {"image": "rancher/hyperkube:v1.20.4-rancher1",
      "serviceClusterIpRange": "10.43.0.0/16", "serviceNodePortRange": "30000-32767",
      "auditLog": {"enabled": true, "configuration": {"maxAge": 30, "maxBackup": 10,
          "maxSize": 100, "path": "/var/log/kube-audit/audit-log.json", "format": "json",
          "policy": {"kind": "Policy", "apiVersion": "audit.k8s.io/v1", "metadata": {
              "creationTimestamp": null}, "rules": [{"level": "Metadata"}]}}}}, "kubeController": {
      "image": "rancher/hyperkube:v1.20.4-rancher1", "clusterCidr": "10.42.0.0/16",
      "serviceClusterIpRange": "10.43.0.0/16"}, "scheduler": {"image": "rancher/hyperkube:v1.20.4-rancher1"},
    "kubelet": {"image": "rancher/hyperkube:v1.20.4-rancher1", "clusterDomain": "cluster.local",
      "infraContainerImage": "rancher/pause:3.2", "clusterDnsServer": "10.43.0.10"},
    "kubeproxy": {"image": "rancher/hyperkube:v1.20.4-rancher1"}}

network:
  {"plugin": "canal", "options": {"canal_flannel_backend_port": "8472", "canal_flannel_backend_type": "vxlan",
      "canal_flannel_backend_vni": "1", "canal_flex_volume_plugin_dir": "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds"},
    "updateStrategy": {"strategy": "RollingUpdate", "rollingUpdate": {"maxUnavailable": 1}}}

authentication:
  {"strategy": "x509", "sans": ["*.rancher.local", "subdomain.rancher.local"]}

system_images:
  {"etcd": "rancher/coreos-etcd:v3.4.14-rancher1", "alpine": "rancher/rke-tools:v0.1.72",
    "nginxProxy": "rancher/rke-tools:v0.1.72", "certDownloader": "rancher/rke-tools:v0.1.72",
    "kubernetesServicesSidecar": "rancher/rke-tools:v0.1.72", "kubedns": "rancher/k8s-dns-kube-dns:1.15.10",
    "dnsmasq": "rancher/k8s-dns-dnsmasq-nanny:1.15.10", "kubednsSidecar": "rancher/k8s-dns-sidecar:1.15.10",
    "kubednsAutoscaler": "rancher/cluster-proportional-autoscaler:1.8.1", "coredns": "rancher/coredns-coredns:1.8.0",
    "corednsAutoscaler": "rancher/cluster-proportional-autoscaler:1.8.1", "nodelocal": "rancher/k8s-dns-node-cache:1.15.13",
    "kubernetes": "rancher/hyperkube:v1.20.4-rancher1", "flannel": "rancher/coreos-flannel:v0.13.0-rancher1",
    "flannelCni": "rancher/flannel-cni:v0.3.0-rancher6", "calicoNode": "rancher/calico-node:v3.17.2",
    "calicoCni": "rancher/calico-cni:v3.17.2", "calicoControllers": "rancher/calico-kube-controllers:v3.17.2",
    "calicoCtl": "rancher/calico-ctl:v3.17.2", "calicoFlexVol": "rancher/calico-pod2daemon-flexvol:v3.17.2",
    "canalNode": "rancher/calico-node:v3.17.2", "canalCni": "rancher/calico-cni:v3.17.2",
    "canalControllers": "rancher/calico-kube-controllers:v3.17.2", "canalFlannel": "rancher/coreos-flannel:v0.13.0-rancher1",
    "canalFlexVol": "rancher/calico-pod2daemon-flexvol:v3.17.2", "weaveNode": "weaveworks/weave-kube:2.8.1",
    "weaveCni": "weaveworks/weave-npc:2.8.1", "podInfraContainer": "rancher/pause:3.2",
    "ingress": "rancher/nginx-ingress-controller:nginx-0.43.0-rancher1", "ingressBackend": "rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1",
    "metricsServer": "rancher/metrics-server:v0.4.1", "windowsPodInfraContainer": "rancher/kubelet-pause:v0.1.6",
    "aciCniDeployContainer": "noiro/cnideploy:5.1.1.0.1ae238a", "aciHostContainer": "noiro/aci-containers-host:5.1.1.0.1ae238a",
    "aciOpflexContainer": "noiro/opflex:5.1.1.0.1ae238a", "aciMcastContainer": "noiro/opflex:5.1.1.0.1ae238a",
    "aciOvsContainer": "noiro/openvswitch:5.1.1.0.1ae238a", "aciControllerContainer": "noiro/aci-containers-controller:5.1.1.0.1ae238a",
    "aciGbpServerContainer": "noiro/gbp-server:5.1.1.0.1ae238a", "aciOpflexServerContainer": "noiro/opflex-server:5.1.1.0.1ae238a"}
```
 
>     * Is the issue related to "Scale Down" option not _greyed out_ when a node is draining? If so, could you please log a separate issue for this

The "scale down" button is not greyed out but I"m also seeing it not work even after cordoning and draining a node. The feature only works sporadically.
