### ISSUE TITLE
Can't import cluster

### ISSUE THREAD

**Issue by d3y** [rancher/rancher#22877]
*Describe your issue here*
I used command "curl --insecure -sfL https://10.30.8.80/v3/import/gphmwxtppkmjxfqb2hwh7f52xd6fvm2qb27zksv94pj2fbttnjhll8.yaml | kubectl apply -f -" ,then I still can't add my kubernetes cluster.

I used command "kubectl apply -f https://10.30.8.80/v3/import/gphmwxtppkmjxfqb2hwh7f52xd6fvm2qb27zksv94pj2fbttnjhll8.yaml".
It's "Unable to connect to the server: x509: certificate signed by unknown authority"

I need help! please 
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.8` UI: `v2.2.94` |
|Route|`authenticated.cluster.edit`|

**Comment by superseb** [comment]
The first command is the command that you need to use as you are using self signed certificates. Please supply the output from that command and use https://rancher.com/docs/rancher/v2.x/en/troubleshooting/imported-clusters/ to troubleshoot.
