### ISSUE TITLE
Bug: editing cluster settings in form not consistent with "edit as yaml"

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#22886]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a custom cluster or aws cluster
2. Have some sort of password manager that auto fills passwords for you on this page.  This may or may not be necessary but was how this bug was initially found.
3. Make some changes to the cluster by editing cluster as yaml.  Specifically in the etcd section, setup s3 snapshots with the intention of using iam roles for authentication.
4. save changes.

**Result:**
If your password manager auto fills a password in the form side for the s3 access key it will be saved in the edit as YAML section even though you didn't see it in there.  If you go back in and edit as YAML a second time you will now see that setting in there from your previous save.  If you try to delete this setting while in "edit as yaml" mode, it will be replaced because it was still filled in on the form side of things by your password manager.  Currently there are two ways to prevent this from happening, don't let your password manager fill it out on the form or explicitly set the key to "" instead of removing the setting altogether. 

**Other details that may be helpful:**

The expected outcome is that if you edit the cluster as yaml, anything you've added to the form should be shown in edit as yaml even before you've saved changes.  If you change something in edit as YAML that change should be reflected in the form side even if you don't switch back to the form before editing.  This way the changes you make when you hit save are 100% what you expect.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom / AWS

**Comment by codyrancher** [comment]
@patrick0057 which password manager did you use and which browser?

I wasn't able to reproduce in chrome with the built in password manager or 1password. Typing it in updates the yaml and so does pasting it in.

**Comment by patrick0057** [comment]
@codyrancher Chrome built in password manager is what was used.

**Comment by codyrancher** [comment]
@patrick0057 alright. I'll give it another try and see if I can reproduce.

**Comment by codyrancher** [comment]
I got on a call with @patrick0057 and we weren't able to reproduce. I'm going to go ahead and close this but feel free to re-open if you find some new reproduction steps.
