### ISSUE TITLE
Deprecate containerized kubelet

### ISSUE THREAD

**Issue by varac** [rancher/rancher#22882]
**What kind of request is this (question/bug/enhancement/feature request):**  feature request

[Kubernetes officially deprecated the use of containerized kubelets](https://github.com/kubernetes/kubernetes/issues/74148).
There were several bug reports related to containerized kubelets, i.e. the still outstanding [volume hostpath with subpath](#14836) issue. There are workarounds floating around, i.e. [bind-mounting the whole host rootdir into the kubelet container](https://github.com/rancher/rancher/issues/14836#issuecomm) but they look far from optimal, potentially being a security issue ([or is this the recommended workaround](https://github.com/rancher/rancher/issues/14836#issuecomment-495154436) ).

I think it's time that rancher deprecates the containerized kubelet, at least make it optional. Are there any plans to do so ?

**Steps to reproduce (least amount of steps as possible):**

For the [volume hostpath with subpath](#14836) issue see these steps to reproduce: https://github.com/rancher/rancher/issues/14836#issuecomment-472398431

**Result:**

Data is not persisted on the host.

**Environment information**
- Rancher version: -
- rke version: 0.2.7
- Installation option (single install/HA): single node cluster

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 4 CPU, 8 GB RAM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version (use `docker version`): 

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:14:13 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by janeczku** [comment]
@varac  While RKE does run Kubelet in a container, it does not leverage or depend on Kubelet's "containerized" feature (previously enabled via the `--containerized` flag) and therefore is not affected by the deprecation of that feature. Since the issue regarding subpath is already tracked in https://github.com/rancher/rancher/issues/14836 i will close this one. Thanks!
