### ISSUE TITLE
Persistent storage options for Prometheus and Grafana display horizontally but would be better vertical

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#22885]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
In the cluster or project monitoring pages (Tools > Monitoring) the options to `Enable Persistent Storage for Prometheus` and `Enable Persistent Storage for Grafana` appear side by side but if you enable either, the `Persistent Volume Size` and `Default StorageClass` options for Prometheus and Grafana appear in rows underneath.  

It would be much more intuitive to have them appear in columns under each option or place `Enable Persistent Storage for Prometheus` and `Enable Persistent Storage for Grafana` in separate sections, one above the other.

**Result:**
How it appears:
![image](https://user-images.githubusercontent.com/8906089/64963471-32769300-d891-11e9-86d1-6bdf2a63ece6.png)

It would be better if they were separated in some way like:
![image](https://user-images.githubusercontent.com/8906089/64964689-74a0d400-d893-11e9-81bc-83a8726564f3.png)
or
![image](https://user-images.githubusercontent.com/8906089/64965121-512a5900-d894-11e9-9e98-8f115fe640cc.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8
User Interface: v2.2.94

**Comment by tfiduccia** [comment]
We should really have the Enable Persistent Storage for Grafana below the Prometheus fields.  It is confusing that the granfana fields are now in the middle of the prometheus fields.

**Comment by codyrancher** [comment]
I went ahead and moved grafana options to be below the tolerations and above the advanced options which just appear to be answers. 

![43103c29.ngrok.io_c_local_monitoring_cluster-setting.png](https://zube.io/files/rancher/730922a9970527a21a88eaecdc2c5537-43103c29-ngrok-io_c_local_monitoring_cluster-setting.png)

**Comment by westlywright** [comment]
Available in UI tag `latest-2.3`

**Comment by sowmyav27** [comment]
**Issue in `2.3.0`:**
<img width="1418" alt="Screen Shot 2019-10-17 at 2 55 41 PM" src="https://user-images.githubusercontent.com/26032343/67050776-385ccf80-f0ee-11e9-9a2d-ea752fe69dee.png">

Validated the fix in 2.3 head with ui tag: **`latest-2.3`**
<img width="1473" alt="Screen Shot 2019-10-17 at 3 15 04 PM" src="https://user-images.githubusercontent.com/26032343/67051821-144ebd80-f0f1-11e9-915b-46c8bd7af8d5.png">
<img width="1453" alt="Screen Shot 2019-10-17 at 3 15 14 PM" src="https://user-images.githubusercontent.com/26032343/67051823-16b11780-f0f1-11e9-8da3-ddcaad654056.png">
