### ISSUE TITLE
Disable deletion of system-charts catalog and disable editing if its the airgapped bundled one

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#22889]
This is the backend api changes for this issue: https://github.com/rancher/rancher/issues/22771

In addition to showing the system-charts catalog, we also want to do the following:
1. At the API level, prevent the deletion of the system-chart. This should do two things:
  - remove the delete link from the system chart catalog so the UI automatically knows it cannot be deleted
  - in a validator or a store, throw a validation error if the user still attempts to delete it (ie via `curl -X DELETE https:///.../system-chart
2. If the user has set the new environment variable that causes rancher to use the embedded version of the chart, then prevent editing the system-chart. This should be done similar to 1 above.

**Comment by sangeethah** [comment]
Tested with rancher server version - v2.3.0-rc4 ( Default behavior) 

1. When trying to delete catalog entry -  `system-library` ( https://<ip>/v3/catalogs/system-library), user is presented with following error message:

{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "not allowed to delete system-library catalog",
"status": 422,
"type": "error"
}

2. Editing catalog entry -  `system-library`  is allowed. User is able to edit catalog entry to point to a different branch and it succeeds.

Tested with rancher server version - v2.3.0-rc4 by passing `-e CATTLE_SYSTEM_CATALOG=bundled` option.

1. When trying to delete catalog entry -  `system-library` ( https://<ip>/v3/catalogs/system-library), user is presented with following error message:

{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "not allowed to delete system-library catalog",
"status": 422,
"type": "error"
}

2. Editing catalog entry -  `system-library`  is NOT allowed. User is presented with following error message as expected:
{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "not allowed to edit system-library catalog",
"status": 422,
"type": "error"
}
