### ISSUE TITLE
[UI] Google Auth - Fix translation to mention different page and fix hyperlink

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22887]
Version: master-head (v2.3) (9/16/19) 

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Go to the Google Auth page (config page)
- Follow the steps. Notice step one says that you:
> Login to your account. Navigate to "APIs & Services" and then select "Credentials".

**Result:**
This is wrong. It may have been this way in the recent past and Google might have changed the their UI.
It should now say this instead:
> Login to your account. Navigate to "APIs & Services" and then select "OAuth Consent Screen".
And the hyperlink should instead link to https://console.developers.google.com/apis/credentials/consent

Proof:
Clicking on the "click here" link (https://console.developers.google.com/apis/credentials)
Takes us to the Credentials page. This is for the second step, not the first step.

The second step is also wrong. It mentions going to the OAuth page to set up our client id... that is step one. It's like these two steps got reversed or something. The auth page needs review and must be fixed before v2.3 release.

**Other details that may be helpful:**
Step 1 and Step 2 need to be fixed. Page needs review.

**Comment by davidnuzik** [comment]
As the issue mentions basically it looks like steps are in the wrong spot. Step 1 brings you to the link to do step 2 and the text is wrong. For step one if we are setting up google api scopes then we go to the oauth page.

Step 2 has content for step 1 if we are creating credentials...

We might be able to more easily fix this by fixing the steps (bullets) in step one and step two and leave the hyperlink alone. The page needs review.

**Comment by loganhz** [comment]
Hi @davidnuzik 

For step 1, changed `Credentials` to `OAuth Consent Screen` in step one. We can change the URL to `https://console.developers.google.com/apis/credentials/consent` if you want.

The design is via https://xd.adobe.com/view/1036add8-5175-4b0e-620b-53f139c74cd9-6607/

It looks like the step 2 is by design.

**Comment by davidnuzik** [comment]
Here's what's confusing to me (this is before your change). Sorry it is difficult to explain all the issues via words.

Login to your account. Navigate to "APIs & Services" and then select "Credentials".
> The link takes us directly to the Credentials page already no need to select this...
> There is no mention that we need to create a credential (OAuth client ID) that should be a bullet point...

Authorized domains: david-test.qa.rancher.space  
Application homepage link: https://david-test.qa.rancher.space/ 
Under Scopes for Google APIs, enable "email", "profile", and "openid".
> These steps are wrong. Those are steps of what we do in step 2 under "OAuth consent screen"
> We should actually bet setting authorized Javascript origins and Authorized redirect URIs when creating our Oauth client id (step one) the "Credentials" page is where we do this!

Step two is also wrong
> Should have "Authorized domains" and "Application homepage link" steps and "google apis enable email, profile, openid.

We may need to zoom @loganhz to discuss
cc: @sangeethah @sowmyav27 @mrajashree

**Comment by sowmyav27** [comment]
On latest `master-head`, there are a few issues with the steps provided for setting up Google Auth.

### In Step One:
**Expected:**
Login to your account. Navigate to "APIs & Services" and then select "OAuth consent screen"

**Actual:** 
Login to your account. Navigate to "APIs & Services" and then select "Credentials"

<img width="699" alt="Screen Shot 2019-09-17 at 3 04 05 PM" src="https://user-images.githubusercontent.com/26032343/65084020-eeea5a80-d95e-11e9-9254-d3c93935f524.png">

### In Step Three:
**Expected:**
- Click here, for information on creating and managing your service account.
- _Select the "Create Credentials" dropdown, and select Service Account key._
- Select your service account.

**Actual:**
- Click here, for information on creating and managing your service account.
- Select your service account.

<img width="1289" alt="Screen Shot 2019-09-17 at 3 21 10 PM" src="https://user-images.githubusercontent.com/26032343/65083980-d417e600-d95e-11e9-8d95-0fa781f2d998.png">

**Comment by sowmyav27** [comment]
Observations/issues mentioned here -- https://github.com/rancher/rancher/issues/22887#issuecomment-532425226 are seen fixed.

In Step One
<img width="910" alt="Screen Shot 2019-09-19 at 12 39 31 PM" src="https://user-images.githubusercontent.com/26032343/65275541-bcfe0300-dada-11e9-86d3-38037f5e01ec.png">

In step Two
<img width="1337" alt="Screen Shot 2019-09-19 at 12 39 44 PM" src="https://user-images.githubusercontent.com/26032343/65275553-c38c7a80-dada-11e9-8f27-61eb44611cda.png">
