### ISSUE TITLE
[API] - Can't create Linode Node template as rootPass shouldn't be nullable

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#22888]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Try creating a node Template in latest v2.3 `master-head (09/16/2019)`

**Result:**
	
`Validation failed in API: linodeConfig rootPass=NotNullable 422:`

**Other details that may be helpful:**

**Environment information**
- Installation option (single install/HA): Single

**Comment by davidnuzik** [comment]
FWIW I do not see in the API that rootPass is required: true

v3/schemas/linodeconfig

"rootPass": {
"create": true,
"description": "Root Password",
"dynamicField": true,
"type": "password",
"update": true
},

Not sure this is an API issue? But also not sure why UI would suddenly claim this is required when it is not (and _should not be required_)

**Comment by izaac** [comment]
Rancher version: `master-head (v2.3) (09/17/2019)`

I was able to create a Linode cluster with a node template with today's latest `master-head` build.
