### ISSUE TITLE
Allow to define hostname routing rules for services when using a selector link

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2288]
http://forums.rancher.com/t/defining-load-balancers-using-rancher-compose-and-sharing-with-primary-load-balancer/495/5

As service selectors (https://github.com/rancher/rancher/issues/2239 ) are being added into Rancher, this allows users to be able to create a selector link on a LB and add services to an existing LB. 

One use case that is not covered is the ability to add hostname routing rules when using the selectors. This issue is to track the ability to allow it.

**Comment by kaos** [comment]
+11 :D

**Comment by alena1108** [comment]
@kaos :) I knew you would like this feature

**Comment by blackjid** [comment]
:+1: awesome feature, I was planning to have an agent that takes care of this.... but now, i'll just wait... :)

**Comment by ndelitski** [comment]
I will praying for this feature lol

**Comment by AnalogJ** [comment]
I also have the same issue. While I waited for this to be implemented, I created a simple agent that updates my load balancer whenever a new service starts/stops. Its pretty basic code but feel free to use/modify it as you need. 

https://github.com/mediadepot/docker-rancher-events/blob/master/events.rb

**Comment by kaos** [comment]
Thanks @AnalogJ, looks like something we could adapt until @alena1108 has implemented #2288.

**Comment by jmcarbo** [comment]
Also vote for this feature being implemented.

**Comment by jschilperoord** [comment]
It would be really cool to have this :+1:

**Comment by kaos** [comment]
@alena1108 any plans for this feature?
Does it depend on the refactoring for the LB code, or something that could be done parallell to that? (was thinking if it would help, should I pitch in in case it's not a too big job to implement..)

**Comment by fbrbovic** [comment]
Any update on this feature, I need it too :)

**Comment by blackjid** [comment]
I understand they are deciding if push this to GA or right after that... :) Can wait!

**Comment by cdrx** [comment]
This is the one feature blocking me from moving from kontena to rancher, so +1 for implementing for GA

**Comment by alena1108** [comment]
Covered by https://github.com/rancher/rancher/issues/2179; closing as a duplicate

**Comment by mrproper** [comment]
Im a little late to the party on this one but i've started a dynamic backend haproxy load balancer image which uses the rancher-metadata to dynamically route http host headers to a stack name, eg. $stack_name.$domain -> $stack_name/app
Its obviously still in development but is working: https://hub.docker.com/r/nodeintegration/rancher-haproxy/
