### ISSUE TITLE
[UI] Cannot edit v1.14 k8s EKS cluster

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22894]
Reference:
https://github.com/rancher/rancher/issues/22642#event-2636823298
https://github.com/rancher/ui/pull/3337

Version: master-head (v2.3) (9/16/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create any EKS cluster
- Edit the EKS cluster

**Result:**
Upon entering credentials you'll get to the section for the k8s version. The drop-down menu will be empty (so you cannot proceed with edit). The browser dev console will report an uncaught type error "Invalid Version: 1.14"

![Screen Shot 2019-09-16 at 11 32 28 AM](https://user-images.githubusercontent.com/21316915/64989021-87aaa880-d881-11e9-930d-248b5b623b2f.png)

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 006998b45

* Created a 1.14 EKS cluster
* Cluster provisioned
* Edit cluster
* k8s versions show correctly
* No error in console
* Cluster can be updated
