### ISSUE TITLE
In Site Access on Github, if you click on the "+" button with no user/org in the text field, it gets stuck

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2289]
UI v0.55.0

Steps to Reproduce:
1. Enable Github
2. Site Access, click on "+" with no text in box. 

Result: The "+" just turns into a spinning disk and doesn't resolve.

Expected Result: Throw error that some text should be included.

**Comment by tfiduccia** [comment]
Version - 1.1.0-dev2-rc6
Verified fixed
