### ISSUE TITLE
Support S3 snapshot remove when rancher server is not configurated to access s3 bucket

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#22900]
This is to support functional S3 backup for cases where IAM profiles are used to authenticate managed clusters cluster backup, while rancher server doesn't have access to use the same IAM profile. Use cases may include:
- Rancher server running outside of AWS, and cluster nodes are provisioned on AWS with IAM auth. 
- Rancher Server is running on AWS but in a different AWS account. 
- Rancher server nodes are not configured with the same IAM profile as the clusters for security reasons. 

An example use case: https://github.com/rancher/rancher/issues/22711#issuecomment-530177536

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (12/02/2019)` 1304c55a2

- Rancher server in Linode, the etcd nodes having IAM policy - cluster creation succeeds when access/secret key are not provided. Snapshot creation is successful
- Created a Daemonset workload, and an ingress.
- Triggered a manual snapshot.
- Clicked `Restore Snapshot`  in the cluster and selected the first snapshot created during cluster creation.

The cluster gets completly frozen in Rancher as it says the API is unavailable and the docker logs show lots for norman errors due to this:

`
[etcd] Failed to restore etcd snapshot: Failed to start [etcd-remove-snapshot] container on host [x.x.x.x]: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/opt/rke-tools/rke-etcd-backup\": stat /opt/rke-tools/rke-etcd-backup: no such file or directory": unknown
`
Reopening.

**Comment by alena1108** [comment]
@izaac does restore work fine in Linode cluster that has API/Secret key set in the snapshot configuration section of a cluster? As opposed to being read from IAM creds on the node.

**Comment by izaac** [comment]
@alena1108 I will check that scenario too. I was going through the first of these: 

https://github.com/rancher/rancher/issues/22711#issuecomment-531018019

**Comment by izaac** [comment]
@alena1108 it does fail with credentials too. Same error message:

`[etcd] Failed to restore etcd snapshot: Failed to start [etcd-remove-snapshot] container on host [x.x.x.x]: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/opt/rke-tools/rke-etcd-backup\": stat /opt/rke-tools/rke-etcd-backup: no such file or directory": unknown`

**Comment by alena1108** [comment]
@izaac can you open a separate bug for the ^ as it seems to be its own separate issue. 

As a part of this bug, we should just verify that snapshot delete functionality works with IAM credentials from the disk. You can close this issue once delete scenario is verified.

**Comment by izaac** [comment]
@alena1108 opened #24360 for the restore fails. I checked this was working in Rancher v2.3.3 I'm still validating the delete, once I'm finished with the scenarios I'll proceed to close this issue, I will move it To Test status in the meantime.

I assigned you and set the status To Triage.

**Comment by izaac** [comment]
Validated functionality with Rancher v2.3.3

Tested with Rancher version `2.4 master-head (12/03/2019)` 1df888a33

1. S3 Snapshot files are not getting deleted without IAM profile and providing amazon keys in cluster.
2. S3 Snapshot files are not getting deleted using IAM profile without credentials.


Above issues are passing in v2.3.3

Reopening.

**Comment by izaac** [comment]
Tested in Rancher version: `2.4 master-head (12/05/2019)` 

For all scenarios:

- One time snapshots create and remove. Passed.
- Recurring snapshots. Passed
- Snapshot backup restore. Passed.
- Snapshot create and Remove with AD user for RBAC. Passed.
- Backup restore with offline etcd. Passed

### Scenario 1:  HA installation - S3
In AWS with Rancher nodes without IAM Profile Ubuntu. Cluster under tests etcd nodes with IAM profile.

### Scenario 2:  HA installation - S3
In AWS with Rancher nodes without IAM Profile Ubuntu. Cluster under tests etcd nodes **without** IAM profile. Using AWS  credentials.

### Scenario 3: Single install Rancher not in AWS - S3
Rancher single install in Linode. Cluster under tests etcd nodes with IAM profile.

### Scenario 4: Single install Rancher not in AWS - S3
Rancher single install in Linode. Cluster under tests etcd nodes **without** IAM profile Using AWS credentials

### Scenario 5: Single install Rancher in Linode - Local
Rancher single install in Linode. Etcd backups local


I'm just missing the dual AWS account scenario from the above description. cc @sangeethah

**Comment by izaac** [comment]
Made the following basic checkups in Rancher version: `2.4 master-head (12/06/2019)` c08cedf76

- One time snapshots create and remove. Passed.
- Snapshot backup restore. Passed.

### Scenario 1: Different account for Rancher server and cluster nodes. S3
Cluster under test etcd nodes with IAM profile.

### Scenario 2: Different account for Rancher server and cluster nodes. S3
Cluster under test etcd nodes **without** IAM profile. Using AWS access keys.
