### ISSUE TITLE
Cannot connect to rancher server with self-signed certificate from windows agent

### ISSUE THREAD

**Issue by stephenpope** [rancher/rancher#22908]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create self signed cert (mkcert) for `rancher.example.com`
2. Create rancher server using docker-machine ..
```
docker-machine create -d virtualbox --virtualbox-boot2docker-url https://releases.rancher.com/os/latest/rancheros.iso --virtualbox-memory 2048 rancher
```
3. Copy certs to machine
```
docker-machine scp -r ~/Certs/rancher rancher:/home/docker/certs
```
4. Start rancher server with self-signed cert
```
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /home/docker/certs/rancher.pem:/etc/rancher/ssl/cert.pem -v /home/docker/certs/rancher-key.pem:/etc/rancher/ssl/key.pem -v /home/docker/certs/ca.pem:/etc/rancher/ssl/cacerts.pem rancher/rancher:master-head
```
5. Create cluster (with Flannel + Windows Support enabled)
6. Create linux worker (worker + etcd + control plane) - No problems
7. Start Windows 2019 + Docker image
8. Update `windows\system32\drivers\etc\hosts` with IP of `rancher.example.com`
9. Run Powershell to create agent
```
PowerShell -NoLogo -NonInteractive -Command "& {docker run -v c:/:c:/host rancher/rancher-agent:master-head bootstrap --server https://rancher.example.com --token 48ndb4kr55lg7dhb5gzkqq94b728wtrgpw5qhpgz2txdxgxxs2t6k8 --ca-checksum 7e3da678628ee9d7b390981bfe979c6b472a39b9500a1cb5b7f0f4a967f3cbbb --address 192.168.99.126 --internal-address 192.168.99.126 --worker | iex}"
```

**Result:**

The agent is unable to connect to the rancher server.

```
C:\Users\Administrator>docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                         PORTS               NAMES
cbf2207fce76        rancher/rancher-agent:master-head   "pwsh -NoLogo -NonInÖ"   11 minutes ago      Restarting (0) 4 seconds ago                       focused_nash

C:\Users\Administrator>docker logs cbf2207fce76
FATA: https://rancher.example.com is not accessible
FATA: https://rancher.example.com is not accessible
FATA: https://rancher.example.com is not accessible
FATA: https://rancher.example.com is not accessible
FATA: https://rancher.example.com is not accessible
FATA: https://rancher.example.com is not accessible
FATA: https://rancher.example.com is not accessible
FATA: https://rancher.example.com is not accessible
FATA: https://rancher.example.com is not accessible
FATA: https://rancher.example.com is not accessible
FATA: https://rancher.example.com is not accessible
FATA: https://rancher.example.com is not accessible
FATA: https://rancher.example.com is not accessible
```

**Other details that may be helpful:**
If I do this exact same thing **without** self-signed certs it works great!

Things I have tried:
1. Passing `--add-host rancher.example.com:<IP>` into the docker command
2. Adding the Root CA cert to the windows machine 

The rancher server is pingable/reachable from the host machine via IP and hostname.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (i have tried all other versions too)
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM Windows 2019 = 2 CPU / 4096 Memory
- Kubernetes version (use `kubectl version`): v1.15.3

- Docker version (use `docker version`):

```
Client: Docker Engine - Enterprise
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        c92ab06ed9
 Built:             09/03/2019 16:38:11
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.8
  Git commit:       c92ab06ed9
  Built:            09/03/2019 16:35:47
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by thxCode** [comment]
@stephenpope , might be the same as https://github.com/rancher/rancher/issues/20436, could you try again?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by romandolinsky** [comment]
@stephenpope it looks like #24255 
Certificate problem I solve when I install certificate directly to image
