### ISSUE TITLE
Amazon Node Template missing instance types

### ISSUE THREAD

**Issue by fun3md** [rancher/rancher#22907]
I'm missing instance types to provision AWS (Amazon) EC2 machines.
We are currently running on Rancher 2.2.6

Can i somehow edit the instance types in "Add Node Template" -> "EC2" -> eu-central1 -> Instance Type?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.6` UI: `v2.2.90` |
|Route|`authenticated.cluster.nodes.index`|

**Comment by tfiduccia** [comment]
@fun3md - You can set the Instance type in Step 4.
![image](https://user-images.githubusercontent.com/11514927/65559806-faa2c780-def0-11e9-98d7-fd16306e979f.png)

**Comment by stokowski** [comment]
I think that @fun3md meant that there are not all instance types to choose. For example t3a.* instance types are missing.

**Comment by tfiduccia** [comment]
@westlywright - do we hard-code in the instance types or pull them from amazon?

**Comment by westlywright** [comment]
@tfiduccia - Yes, amazon does not provide an API to fetch this data so it is hard coded in the following file.

https://github.com/rancher/ui/blob/2.2-fixes/lib/shared/addon/utils/amazon.js

**Comment by deniseschannon** [comment]
@alena1108 can someone from engineering find out what the new list of instance types were introduced into 2.2.x and what needs to be added into 2.3.x and 2.4

**Comment by fun3md** [comment]
thanks a lot. exactly what @stokowski said. was missing some c5.* types. i used the api to adjust my node templates. worked a treat. an ui would ideal or an editable instace type field in the node template form (like an override) but an updated ec2 instance types file works as well

**Comment by deniseschannon** [comment]
Keeping this one around to manually add in the requested c5 and t3a types into the next release.

Refer to #23244 for longer term solution.

**Comment by westlywright** [comment]
This is available in the `latest-2.3`. QA can test with a 2.3 release or 2.3-master by replacing ui-index with `https://releases.rancher.com/ui/latest-2.3/index.html`

**Comment by jiaqiluo** [comment]
The bug is reproduced in v2.2.6 There are not `t3a` types and some `c5` types missing: `c5.12xlarge`, `c5.24xlarge`, `c5.metal`

The bug fix is validated in v2.3.0 with UI index `https://releases.rancher.com/ui/latest-2.3/index.html`
all those missing types are now shown in the list

**Comment by Pravka** [comment]
rancher version v2.5.1 (eb990af66) --> g4 instance types missing. 

Could someone update templates and add g4 instance types?

**Comment by stlaurentc** [comment]
Rancher version 2.5.5 is missing C5a instance types
