### ISSUE TITLE
UI hangs when trying to launch "View Config" , when metadata for service is ~900kb.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2290]
Server version - Build from master- Oct 8

Steps to reproduce the problem:
Create a service with metadata size ~900kb.
UI hangs when trying to launch "View Config" , when metadata for service is ~900kb.

**Comment by vincent99** [comment]
There doesn't seem to be any error happening so I think it will eventually render sometime before the heat-death of the universe.

The example is a string full of JSON which gets syntax highlighted as YAML.  So it's sort of a pathological worst case that becomes several hundred thousand DOM nodes.  And then jQuery wants to loop over them all for mutation observers for some reason.

So we can probably optimize this, but for now:

![image](https://cloud.githubusercontent.com/assets/753917/10402610/3f5ce652-6e7b-11e5-9a4b-f6274e6e1907.png)
