### ISSUE TITLE
Error seen on editing and saving a workload

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22913]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster 1 etcd, 1 control plane and 1 worker node. Have taints on all the nodes.
- deploy a workload without any toleration.
- The workload will be in `Updating` state and will fail to deploy as there as no tolerations set on it.
- Go to Workload --> Edit workload --> Node Scheduling --> Add Toleration.
- Add the required toleration.
- Click on Save.

**Expected Result:**
The changes should get saved.

**Actual Result:**
Error is seen while saving the changes made.

**Response:** 
`{"baseType":"error","code":"Invalid","message":"Deployment.apps \"wk02\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{}: `selector` does not match template `labels`","status":422,"type":"error"}`
**UI:**
<img width="1357" alt="Screen Shot 2019-09-17 at 11 08 25 AM" src="https://user-images.githubusercontent.com/26032343/65069983-a8860300-d940-11e9-8874-1c1f33cccd72.png">

**Note:**
This set of steps does NOT always result in the error.
Another way to help reproduce the issue.

- Deploy a workload with the default node Scheduling values. (If the worker node has taint, add appropriate tolerations on the workload)
- The workload should get dpeloyed successfully.
- Now, edit workload --> node Scheduling.
- Select option `Run all pods for this workload on a specific node` and select worker node from the drop down. 
- Click on Save.
- You will see the error.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.3.0-rc4
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
v1.15.3
```

- Docker version (use `docker version`):

```
19.3.2
```

**Comment by alena1108** [comment]
@sowmyav27 does the issue happen on edit only? Does it ever happen on the initial workload deployment?

**Comment by sowmyav27** [comment]
@alena1108 I have not seen it on the initial workload deployment. I have always seen it on an edit.

**Comment by panho66** [comment]
Saw the same error in this issues. Using API to create catalogs app is ok in 2.2.x but failed in 2.3.x. After removing http proxy setting, catalogs app can be created but can’t add http setting via UI have to use kubectl set env to patch it.

https://github.com/rancher/rancher/issues/22715

**Comment by mrajashree** [comment]
This error is thrown during edit when the PUT request contains an empty labels field, whereas the workload has a label set for the workload selector. This label is set on creation by backend. We confirmed that this label is set upon creation, by checking the response of the create call’s POST request, and by viewing the workload in API before editing it. But just during edit somehow in the UI’s PUT request labels is sometimes empty, causing this bug intermittently. Seems to be a UI issue? @vincent99 @alena1108

**Comment by virusthesyrus** [comment]
It happens when you click edit on the workload
![image](https://user-images.githubusercontent.com/55526101/65216380-f15cc980-dab0-11e9-8ec4-d0b595ac88fb.png)
after a refresh in edit mode the label is present and you can save the workload without the errors
![image](https://user-images.githubusercontent.com/55526101/65216436-2537ef00-dab1-11e9-9ec5-4391e9185dac.png)

**Comment by loganhz** [comment]
Reproduce step is

1. Go to workload detail page first
2. Click edit in workload detail page.

Submitted a PR to fix it.

**Comment by sowmyav27** [comment]
**verified on `2.3.0-rc6`**

**Steps:**

- Deploy a cluster 1 node - all roles. Have taints the node.
- deploy a workload without any toleration.
- The workload will be in Updating state and will fail to deploy as there as no tolerations set on it.
- Go to Workload --> Edit workload --> Node Scheduling --> Add Toleration.
- Add the required toleration.
- Click on Save.
- No error was seen.
- The workload upgraded successfully. And was `Active`
