### ISSUE TITLE
k8s metadate - getSvcOptions and getK8sServiceOptions error after upgrading Rancher

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#22919]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run v2.2.8 single install
- add a cluster with k8s version `v1.14.6-rancher1-1`
- upgrade Rancher to v2.3.0-rc4

**Result:**
- In Rancher's log, the following errors are shown repeatedly
```
2019/09/17 18:03:43 [ERROR] getSvcOptions: error finding system image for v1.14.6-rancher1-1 rkek8ssystemimages.management.cattle.io "v1.14.6-rancher1-1" not found
2019/09/17 18:03:43 [ERROR] getK8sServiceOptions: k8sVersion v1.14.6-rancher1-1 [rkek8ssystemimages.management.cattle.io "v1.14.6-rancher1-1" not found]
```

**Other details that may be helpful:**
k8s versions in v2.2.8
```
- v1.12.10-rancher1-2
- v1.13.10-rancher1-2
- v1.14.6-rancher1-1
- v1.15.3-rancher1-1
```

k8s versions in v2.3.0-rc4
```
- v1.13.10-rancher1-3
- v1.14.6-rancher3-1
- v1.15.3-rancher3-1
- v1.16.0-beta.1-rancher2-1
```

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.0-rc4

With k8s clusters: 
* 1.12.10
* 1.13.10
* 1.14.6

I see the following logs repeated: 
```
2019/09/17 22:33:10 [ERROR] getK8sServiceOptionsWindows: k8sVersion v1.12.10-rancher1-2 [getSvcOptions: no service-option key present for v1.12.10-rancher1-2]
2019/09/17 22:33:10 [ERROR] getK8sServiceOptionsWindows: k8sVersion v1.13.10-rancher1-2 [getSvcOptions: no service-option key present for v1.13.10-rancher1-2]
2019/09/17 21:28:47 [ERROR] getK8sServiceOptions: k8sVersion v1.14.6-rancher1-1 [rkek8ssystemimages.management.cattle.io "v1.14.6-rancher1-1" not found]
```

**Comment by alena1108** [comment]
@bmdepesa @jiaqiluo does the error go away eventually?

**Comment by bmdepesa** [comment]
@alena1108 The error is still repeating in the logs after ~16 hours

**Comment by alena1108** [comment]
@leodotcloud the code that throws an error tries to load k8s service options from corresponding crd in etcd, and it fails by some reason. Per @kinarashah the crds should get synced on the rancher startup. Can you take a first stab on the issue

**Comment by leodotcloud** [comment]
Inspecting @jiaqiluo 's  setup:

Rancher startup:
```
 2019/09/17 18:03:23 [INFO] Rancher version v2.3.0-rc4 is starting
```

First time, the error was seen in the logs:
```
2019/09/17 18:03:37 [ERROR] getSvcOptions: error finding system image for v1.14.6-rancher1-1 rkek8ssystemimages.management.cattle.io "v1.14.6-rancher1-1" not found
```

Last time, the error was seen in the logs:
```
2019/09/17 18:04:19 [ERROR] getSvcOptions: error finding system image for v1.14.6-rancher1-1 rkek8ssystemimages.management.cattle.io "v1.14.6-rancher1-1" not found
```

Latest log message in the logs:
```
2019/09/18 17:39:02 [ERROR] API error response 401 for POST /v3-public/localProviders/local?action=login. Cause: crypto/bcrypt: hashedPassword is not the hash of the given password
```

Checking the CRDs:
```
kubectl get rkek8ssystemimages.management.cattle.io --all-namespaces | grep v1.14.6-rancher1-1
cattle-global-data   v1.14.6-rancher1-1          23h
```

```
kubectl get rkek8sserviceoptions.management.cattle.io --all-namespaces | grep v1.14
cattle-global-data   v1.14    23h
```

The errors were seen for only about 2 minutes after rancher started. The CRDs were probably created afterwards and hence there are no more complaints.

>The error is still repeating in the logs after ~16 hours

@bmdepesa Did you get a chance to check the timestamps of the error messages?

**Comment by leodotcloud** [comment]
@bmdepesa From your setup:

```
2019/09/17 21:27:46 [INFO] Rancher version v2.3.0-rc4 is starting
...
2019/09/17 21:28:01 [ERROR] getSvcOptions:
...
2019/09/17 21:28:47 [ERROR] getSvcOptions: error
```

As seen in Jack's setup, the error is transient for few minutes before the CRDs are installed.

The other error messages seen are related to https://github.com/rancher/rancher/issues/22870

**Comment by leodotcloud** [comment]
The error message is being printed in the context of a connect handler (RKENodeConfigServer). It's not a controller where we can have a wait/retry logic. We wouldn't want to suppress this message as it might hide any potential issues in the future.

**Comment by alena1108** [comment]
Closing as it's a one time error that might happen after only the very first upgrade to 2.3.x, and taking any action on it is regression-prone.
