### ISSUE TITLE
Feature Request: Amazon EKS custom security groups, option to not modify

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#22910]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Description:**
Currently you can select your own Security Group when creating an Amazon EKS cluster however the Security Group settings will be changed after the cluster is deployed.  Specifically the outbound rules are changed to allow only 443 and 1025-65535.  This feature request is for the ability to have the chosen Security Group unmodified if the user has specific rules they want used instead.

gzrancher/rancher#6173

**Comment by rmweir** [comment]
These are not modified in EKSv2. @sowmyav27 please validate.

**Comment by sowmyav27** [comment]
Blocked by issue - https://github.com/rancher/rancher/issues/28144

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `9b0dd20b7`**

- Deploy a hosted EKS cluster from rancher.
- Select subnets and security groups.
- Create the cluster. When the cluster comes up Active, verified that the security group selected during cluster creation, the outbound and inbound rules are not changed.
