### ISSUE TITLE
Editing and changing cluster template revision does not take into effect

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#22920]
Version : master-head

Steps:

1. Create a cluster template/revision T1/R1 with K8s version v1.14.6
2. Create another revision T1/R2 with K8s version v1.15.3
3. Create a cluster using R1
4. Edit the cluster and change the template revision to R2

Revision change does not take into effect. The cluster does not go to "updating" state

The request shows that UI does not send the new template revision (cattle-global-data:ctr-wqkbs) in the request. 
The revision cattle-global-data:ctr-8skd8 is being sent

<img width="588" alt="Screen Shot 2019-09-17 at 4 14 42 PM" src="https://user-images.githubusercontent.com/18536626/65086367-56f06f00-d966-11e9-90b7-620174b28a97.png">

Note: Changing the cluster template revision through API is functional

**Comment by codyrancher** [comment]
I haven't figured out why yet. But it's actually this line in this commit which is causing the bug https://github.com/rancher/ui/commit/9621b09fb0830d9c22de17fb1fe1259a63c0622b#diff-9fb8eb2d13ba5649202f0c6db5bb8f46R1452

**Comment by codyrancher** [comment]
I misinterpreted what I saw not noticing the url was getting edited when I changed the revision and going back and refreshing the page. rancher/ui@9621b09#diff-9fb8eb2d13ba5649202f0c6db5bb8f46R1452 was not the cause of this issue.

**Comment by soumyalj** [comment]
https://github.com/rancher/rancher/issues/22977

**Comment by codyrancher** [comment]
Just for my own knowledge, is there a reason that this issue needs to be blocked by the other issue? They're completely unrelated from a code perspective and reproduced differently though I suspect while testing this issue you discovered the other.

**Comment by soumyalj** [comment]
Editing and changing to the new template revision with a different K8s version takes effect.
@codyrancher :  Left it open since we wanted to make sure that when we choose a new template revision, UI displays the k8s version correctly.
