### ISSUE TITLE
Cannot create a rancher os node using rancher node template in azure

### ISSUE THREAD

**Issue by dan-evolvere** [rancher/rancher#22927]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create an azure node template and set the image to any of the marketplace images for Rancher OS ie rancher:rancheros:os152:1.5.2

**Result:**
VM Creation fails in the azure UI/rancher UI with the error message;
Provisioning failed. Creating a virtual machine from Marketplace image requires Plan information in the request. VM: 'test-azure-2-1'.. VMMarketplaceInvalidInput

**Other details that may be helpful:**

**Environment information**
- Rancher version 2.2.4 & 2.2.8
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Azure created Node (NOT AKS)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM Standard_D2_V2
- Kubernetes version (use `kubectl version`): 1.13.5-rancher1-3 & 1.14.6-rancher1-1

- Docker version (use `docker version`): 18.09

**Comment by dan-evolvere** [comment]
API output for the node template;
{

"amazonec2Config": null,
"annotations": { },
"azureConfig": {
"availabilitySet": "docker-machine",
"clientId": "",
"customData": "",
"dns": "",
"dockerPort": "2376",
"environment": "AzurePublicCloud",
"image": "rancher:rancheros:os152:1.5.2",
"location": "uksouth",
"noPublicIp": false,
"openPort": [ 10 items
"6443/tcp",
"2379/tcp",
"2380/tcp",
"8472/udp",
"4789/udp",
"9796/tcp",
"10256/tcp",
"10250/tcp",
"10251/tcp",
"10252/tcp"
],
"privateIpAddress": "",
"resourceGroup": "docker-machine",
"size": "Standard_D2_v2",
"sshUser": "docker-user",
"staticPublicIp": false,
"storageType": "Standard_LRS",
"subnet": "docker-machine",
"subnetPrefix": "192.168.0.0/16",
"subscriptionId": "XXXredactedXXX",
"usePrivateIp": false,
"vnet": "docker-machine-vnet"
},
"baseType": "nodeTemplate",
"cloudCredentialId": "azure-creds",
"created": "2019-09-18T10:06:46Z",
"createdTS": 1568801206000,
"creatorId": "XXXredactedXXX",
"digitaloceanConfig": null,
"driver": "azure",
"engineInsecureRegistry": null,
"engineInstallURL": "https://releases.rancher.com/install-docker/18.09.sh",
"engineRegistryMirror": null,
"id": "XXXredactedXXX",
"labels": {
"cattle.io/creator": "norman"
},
"name": "test-azure",
"state": "active",
"transitioning": "no",
"transitioningMessage": "",
"type": "nodeTemplate",
"useInternalIpAddress": true,
"uuid": "XXXredactedXXX",
"vmwarevsphereConfig": null
}

**Comment by snasovich** [comment]
This work is now tracked as part of https://github.com/rancher/rancher/issues/33518, so closing this one in favor of the referenced issue.
