### ISSUE TITLE
Upgrade Istio to v1.3.0

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#22923]
Upgrade istio to v1.3.0

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 

Jaeger fails to deploy with an ImagePullBackoff error
```
Failed to pull image "rancher/jaegertracing-all-in-one:1.12": rpc error: code = Unknown desc = Error response from daemon: manifest for rancher/jaegertracing-all-in-one:1.12 not found: manifest unknown: manifest unknown
--
```

The image is not able to be pulled manually either:
```root@localhost:~# docker pull rancher/jaegertracing-all-in-one:1.12
Error response from daemon: manifest for rancher/jaegertracing-all-in-one:1.12 not found```

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 006998b45

* Deploy Cluster
* Enable Istio w/ version `1.3.0`
* Prometheus / Grafana deployed from monitoring
* P1 Workflow succeeds
* All namespaces show in traffic graph
* Disable / re-enable functions
* Edit / disable individual components functional (workloads are deployed or removed as necessary)
* Node scheduling / tolerations successful
* Ingress gateway functional
* Create resources via kubectl functional
* Create resources via Rancher CLI functional
* External links functional (Kiali, Jaeger, Grafana, Prometheus)
* CRDs removed when Istio disabled
* Kiali / Jaeger RBAC
