### ISSUE TITLE
How to link containers in Rancher UI ?

### ISSUE THREAD

**Issue by taibc** [rancher/rancher#22929]
I have two workloads: a Springboot app and a Mysql database. My app was deployed in namespace "dev" from my image and the mysql database was deployed via rancher catalog and in the namespace "mysql-standalone-p-lggjt". How can I link the database to app ? 

If using docker, I use below command: 
`$ docker run --name springboot-docker-mysql-app --link mysql-standalone:mysql -d springboot-docker-mysql`

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.7` UI: `v2.2.93` |
|Route|`containers.index`|

**Comment by oskapt** [comment]
You don't link containers in Kubernetes like you do in Docker. Your database install created a service - look in the Service Discovery tab under Workloads. Your springboot app can access that service by name. 

For example, if the database service is in the namespace `mysql-standalone-p-lggjt` and is called `mysql-standalone`, then you can direct your springboot app to connect to `mysql-standalone.mysql-standalone-p-lgglt.svc.cluster.local` and it will be routed to the correct pod. (Incidentally, this is why I prefer to create or choose a namespace name when installing from the app catalog.)

Please join the Rancher Users Slack at https://slack.rancher.io - there is a community of people there who can help you with these types of questions.

Welcome to Rancher!

**Comment by taibc** [comment]
> You don't link containers in Kubernetes like you do in Docker. Your database install created a service - look in the Service Discovery tab under Workloads. Your springboot app can access that service by name.
> 
> For example, if the database service is in the namespace `mysql-standalone-p-lggjt` and is called `mysql-standalone`, then you can direct your springboot app to connect to `mysql-standalone.mysql-standalone-p-lgglt.svc.cluster.local` and it will be routed to the correct pod. (Incidentally, this is why I prefer to create or choose a namespace name when installing from the app catalog.)
> 
> Please join the Rancher Users Slack at https://slack.rancher.io - there is a community of people there who can help you with these types of questions.
> 
> Welcome to Rancher!

Thank you. But when I config the connection as: jdbc:mysql://mysql-standalone-p-lggjt-mysql.mysql-standalone-p-lggjt.svc.cluster.local:3306/test?useSSL=false . I got the error: Caused by: 

> java.net.UnknownHostException: mysql-standalone

Do I need to use port-forward for mysql service to access via localhost ?
