### ISSUE TITLE
rke up logs for kubernetes clusters provisioned by Rancher available within the Cluster interface

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#22931]
When provisioning a new Kubernetes cluster, it can be desirable to have the ability to view the `rke up` logs from the provisioning process of that cluster in an interface within the Rancher UI. This can be for both audit as well as troubleshooting purposes.

**Comment by deniseschannon** [comment]
We have added in provisioning logs in the cluster management page under a specific cluster into the UI to be able to review the logs. 

![Uploading Screen Shot 2022-03-10 at 9.01.23 PM.png…]()
