### ISSUE TITLE
UI does not have File System Type input field for Storage Class with Google Persistent Disk provisioner

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22932]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Default File system format for a storage class for **`Google Persistent Disk`** provisioner is **`ext4`**. This is NOT a supported file system for windows.

When you try to deploy a workload with a volume claim using storage class it will fail as mentioned here -- https://github.com/rancher/rancher/issues/20839#issuecomment-530556962.

To overcome this, user has to create a storage class through the api as mentioned here --https://github.com/rancher/rancher/issues/20839#issuecomment-532838777

It would be of help if the UI exposes an input field - `File System Type` similar to what is exposed for Persistent Volumes.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0-rc5
- Installation option (single install/HA): single

**Comment by deniseschannon** [comment]
This already exists in Persistent Volume UI, so QA is asking the same field to be present in the storage class options. 

![Screen Shot 2019-09-18 at 1.51.31 PM.png](https://zube.io/files/rancher/8c3260e373aa8cc56212822cb4617619-screen-shot-2019-09-18-at-1-51-31-pm.png)

**Comment by sowmyav27** [comment]
verified on latest `master-head`

Cluster --> Storage --> Storage Class --> Add Storage class --> Provisioner `Google Persistent Disk` --> UI has input field `Filesystem Type`
<img width="1532" alt="Screen Shot 2019-09-19 at 2 54 31 PM" src="https://user-images.githubusercontent.com/26032343/65284150-9d240a80-daed-11e9-98e8-27c82bf381ce.png">

- Verified on a windows cluster - GCE custom cluster
```
1 all roles -linux node
1 worker - windows node 
cloud provider enabled
```
- After cluster is up and `Active`, Cluster --> Storage --> Storage Class --> Add Storage class --> Provisioner `Google Persistent Disk` 
- In `Filesystem Type` field enter - `NTFS` for windows storage (default is ext4 when nothing is passed in this field)
- Create a storage class
- Go to Project --> Volume --> Add Volume Claim --> Use the above created storage class to create a volume claim
- Deploy a workload, attach this volume claim 
- The volume attached and can be seen in the google --> Disks.
Scale up the pods in workload, verified the volume is shared.
