### ISSUE TITLE
New install asks for telemetry permission twice

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#22930]
The initial login process for a new cluster has a checkbox for telemetry on the "set a new password" page. This was the original location. That's now duplicated after completing the "set servername" page, with a more detailed dialog box popping up that explains the reason and details for the request.

I don't know if the two are connected - if checking one checks the other, but I don't think we need to ask twice. Perhaps remove the first one?

**Comment by deniseschannon** [comment]
@oskapt What version is this? I haven't been able to reproduce it on v2.3.0-rc9.

**Comment by oskapt** [comment]
sorry - should have included that. 2.2.8 for sure. i'll check again in rc9.

**Comment by oskapt** [comment]
present in v2.3.0-rc9. images attached.
![Screen Shot 2019-09-25 at 18 31 00](https://user-images.githubusercontent.com/171292/65641327-d44d5c80-dfc2-11e9-885d-2be21df48887.png)
![Screen Shot 2019-09-25 at 18 31 39](https://user-images.githubusercontent.com/171292/65641328-d4e5f300-dfc2-11e9-89ae-652bb5f27750.png)

**Comment by davidnuzik** [comment]
Was this a fresh install of v2.3.0-rc9? (not an upgrade)

**Comment by vincent99** [comment]
The 2nd one is mostly left over from 1.x when it prompted if not already set because it may have not existed yet.  But it should only be showing up if the setting isn't set yet.  And the set password screen should be setting it all the time.

So seems like either the UI's not sending it, the API isn't saving it, or the 2nd one is being erroneously shown even though it is set & saved.

**Comment by oskapt** [comment]
@davidnuzik fresh install

i like the second one because it explains what it we collect. the first one, being just a checkbox, i think is more likely to be unchecked by the user to err on the side of caution.

**Comment by davidnuzik** [comment]
I like the second one better as well.
I don't recall seeing this in v2.2.8 and in master-head a couple of weeks ago, but it's obviously there and an issue. I think if we decide to fix before release we should opt for just the 2nd one with the modal/pop-up.

**Comment by vincent99** [comment]
It's an API race.  The UI POSTs out, the API returns `out`, then later gets settings again and returns the default (`prompt`).

PUT Request:

![image](https://user-images.githubusercontent.com/753917/65791634-f821b700-e116-11e9-9bf6-6c1c16ab8b38.png)

Response:

![image](https://user-images.githubusercontent.com/753917/65791655-040d7900-e117-11e9-876f-b97e78cec6df.png)

Subsequent GET /v3/settings: 

![image](https://user-images.githubusercontent.com/753917/65791693-15ef1c00-e117-11e9-9e61-2795b03e652f.png)

Later request having changed nothing else:

![image](https://user-images.githubusercontent.com/753917/65792350-687d0800-e118-11e9-9226-f273ce7fabf1.png)
