### ISSUE TITLE
In-service upgrade takes very long time for larger service scale

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#2293]
setup: master

image: "docker:sangeetha/testclient:latest"
only launchConfig and no secondaryLaunchConfigs
upgrade adds a simple label
scale = 25
default batchSize and intervalMillis

It takes ~ 30 min for upgrade to complete. disk size was not an issue. 

For smaller scale like 5, I did not see this issue. For larger scale, it is reproducible for larger batchSize as well.

**Comment by sangeethah** [comment]
Tested with server version - v0.43.0-rc1

image: "docker:sangeetha/testclient:latest"
only launchConfig and no secondaryLaunchConfigs - upgrade adds a simple label and default batchSize and intervalMillis
scale = 50

It takes ~ 5 min for upgrade to complete. 

When batchSize of 10 was used , upgrade took about 1.5 minutes.
