### ISSUE TITLE
Vulnerability in nginx-ingress-controller: 0.21.0

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#22940]
Description:
Several CVEs have been addressed in nginx-ingress-controller: 0.25.1
https://github.com/kubernetes/ingress-nginx/pull/4440

Additionally, Rancher user has reported that Nginx 1.15.6 has security vulnerability issues which are fixed in Nginx 1.16.1+.

Need a path for users on Rancher 2.2.x to upgrade to Nginx 1.16.1+ without needing to upgrade to Rancher 2.3. 

Rancher version issue reported:
v2.2.8

**Comment by dnoland1** [comment]
See also https://github.com/rancher/rancher/issues/21826

**Comment by deniseschannon** [comment]
nginx 0.25.1 is available in 2.2.9. Sending to QA to validate.

**Comment by sowmyav27** [comment]
verified on latest 2.2-head
on clusters - k8s v 1.15, 1.14 and 1.13
ingress-controller version seen is `rancher/nginx-ingress-controller:nginx-0.25.1-rancher1`

**Comment by shinebayar-g** [comment]
>Starting in Version 0.22.0, ingress definitions using the annotation nginx.ingress.kubernetes.io/rewrite-target ref: https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target

So how do we use this new capture group in ingress path? For example, in version 0.21.x with `nginx.ingress.kubernetes.io/rewrite-target` `/` annotation `mydomain.com/blog` address would rewrited to `mydomain.com` to backend service. How can we achieve similar functionality in new nginx version?

**Comment by riveryc** [comment]
> > Starting in Version 0.22.0, ingress definitions using the annotation nginx.ingress.kubernetes.io/rewrite-target ref: https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target
> 
> So how do we use this new capture group in ingress path? For example, in version 0.21.x with `nginx.ingress.kubernetes.io/rewrite-target` `/` annotation `mydomain.com/blog` address would rewrited to `mydomain.com` to backend service. How can we achieve similar functionality in new nginx version?

Have you fixed this? We got exactly the same issue here.
