### ISSUE TITLE
Update docker-compose

### ISSUE THREAD

**Issue by mattapperson** [rancher/rancher#2295]
Current state:
- Supports / uses 1.2.0

Desired state:
- Support 1.4.x+

Reason:
docker-compose 1.2 supports only alpha numeric names, upgrading to 1.4, relaxes those rules (among many other things). This makes tooling easier to build for names services that are programaticly named/iterated ala dockers own container names (for example: <service name>_funny_rabbit) or via a clear hash (example: <service name>_423kj4h) or better yet, versioned with your app (example: <service name>-1.2.0)

**Comment by vincent99** [comment]
rancher-compose uses (and we contributed...) [libcompose](https://github.com/rancher/rancher/issues/1673#issuecomment-146935838), not docker-compose.  And we will have additional issues with relaxed names, such as creating DNS entries for them.

**Comment by deniseschannon** [comment]
@mattapperson We have made some DNS improvements that would only allow specific characters for service names. Therefore, I'm going to close this.
