### ISSUE TITLE
Monitoring - NodeSelector does not work

### ISSUE THREAD

**Issue by SkySonR** [rancher/rancher#22955]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Add label on specific node
Deploy monitoring with NodeSelector parametes selected

**Result:**
Monitoring workloads scheduled on different nodes.
Any of NodeSelector or NodeAffinity does not exist in the components yaml files
**Other details that may be helpful:**
Rancher 2.2.7 deployed as helm chart to EKS cluster

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/22760

Fixed in v2.3.
