### ISSUE TITLE
Feature request: Allow adding annotations and labels during PVC creation in Rancher UI

### ISSUE THREAD

**Issue by nickngch** [rancher/rancher#22952]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Description**
Allow adding annotations and labels during PVC creation in Rancher UI. This option enables the ability to select which array the PVC mounts on when using Pure-Storage FlashArray block-presenting device.  

gz#6198

**Comment by junkiebev** [comment]
Upon review, we need to be able to specify a selector as well
Here is an example snippet: 

```
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
spec: 
selector: 
matchExpressions: 
- key: datacenter 
operator: In 
values: 
- chicago
```
