### ISSUE TITLE
Mirror weave images to rancher

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#22954]
**RKE Version**
v0.2.8/v0.3.0-rc10
The related image list comes from RKE cli but it is used in the air gap docs so I think we should track it here.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
[Prepare images](https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/prepare-private-registry/) for air-gapped environments.

You will run:
```
$ rke config --system-images >> ./rancher-images.txt
```
This is the output for the rke command:
```
INFO[0000] Generating images list for version [v1.14.6-rancher1-1]:
rancher/coreos-etcd:v3.3.10-rancher1
rancher/rke-tools:v0.1.42
rancher/k8s-dns-kube-dns:1.15.0
rancher/k8s-dns-dnsmasq-nanny:1.15.0
rancher/k8s-dns-sidecar:1.15.0
rancher/cluster-proportional-autoscaler:1.3.0
rancher/coredns-coredns:1.3.1
rancher/hyperkube:v1.14.6-rancher1
rancher/coreos-flannel:v0.10.0-rancher1
rancher/flannel-cni:v0.3.0-rancher1
rancher/calico-node:v3.4.0
rancher/calico-cni:v3.4.0
rancher/calico-ctl:v2.0.0
rancher/coreos-flannel:v0.10.0
weaveworks/weave-kube:2.5.0
weaveworks/weave-npc:2.5.0
rancher/pause:3.1
rancher/nginx-ingress-controller:0.21.0-rancher3
rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1
rancher/metrics-server:v0.3.1
```

**Other details that may be helpful:**
Related issues:
https://github.com/rancher/rancher/issues/19435
https://github.com/rancher/rancher/issues/19520

**Comment by deniseschannon** [comment]
Since weaveworks isn't under our [support matrix](https://rancher.com/support-maintenance-terms/), we don't need to move it under the Rancher Dockerhub repo.
