### ISSUE TITLE
InServiceUpgrade: Consecutive upgrade doesn't work

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2296]
Steps to reproduce:

1) Create a service.
2) Do in service upgrade. Finishes successfully
3) Repeat 2). Nothing happens

@aruneli we have to add validation test for it

**Comment by sangeethah** [comment]
Tested with v0.43.0-rc1

1) Create a service with image:v1.
2) Do in service upgrade to image:v2. Finishes successfully.
3) Do in service upgrade to image:v3. Finishes successfully. All the instances in the service upgrade to v3 successfully.
