### ISSUE TITLE
Support k8s 1.16 as default

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#22965]

**Comment by sangeethah** [comment]
Tested with rancher server built from latest `v2.3-head` .
On changing the `rke-metadata-config` to point to `dev` branch ,  k8s 1.16 is offered as default version on cluster creation and is not experimental anymore.

<img width="1291" alt="Screen Shot 2019-10-17 at 7 09 00 PM" src="https://user-images.githubusercontent.com/4266958/67061798-44f51e00-f116-11e9-9012-2ecf417069a5.png">

**Comment by sd2302** [comment]
Hello What should i use in this line so i can import a k8 16.4 kubernetes cluster ?

image: rancher/rancher-agent:v2.2.1
