### ISSUE TITLE
Issues on Google Auth UI screen

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22968]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Navigate to Security --> Authentication --> Google Auth

### **Issue#1:**

Expected - At the end of **Step One:**, there can be a step saying `Click on Save`, as the user has to save all the changes he does in this screen

### **Issue#2**
The `Double Quotes` can be made consistent across all steps on the page

In Step Two:
**Actual:** Click "Create", and then click on the Download JSON button.

**Expected:** Click "Create", and then click on the "Download JSON" button.

### **Issue#3**

In Step One:

**Actual:** `Authorized domains: <fully qualified domain name>` with a tool tip that states - `Note: This must be a fully qualified domain name; ip addresses are not valid`.

When user enters the copied text from this to the google api page, the domain is not saved and a message is seen `Must be a top private domain.`

<img width="503" alt="Screen Shot 2019-09-19 at 1 25 51 PM" src="https://user-images.githubusercontent.com/26032343/65278521-2bde5a80-dae1-11e9-96d4-445e19e729a3.png">

**Expected:** 
Instead it can be shown on the UI as 

`Authorized domains: Top private domain of <fully qualified domain name>`

<img width="910" alt="Screen Shot 2019-09-19 at 12 39 31 PM" src="https://user-images.githubusercontent.com/26032343/65278391-e15cde00-dae0-11e9-91ed-958f2c43c79f.png">

### Issuerancher/rancher#4

Step 3 can be just this --

`Follow [this](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/google/#creating-service-account-credentials) guide for creating a service account, generating a key for the service account and adding it as an OAuth client in your google domain.`

@mrajashree 's comments ^^^

**Note:**
An appropriate heading and a bullet has to be present consistent with the other steps

The heading of this step `Navigate to the "Credentials" tab again to create your Service account key` is also not required.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest
- Installation option (single install/HA): single

**Comment by mrajashree** [comment]
Can the "Step Three" be this:
```
Step Three: Create Service Account credentials

Follow [this](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/google/#creating-service-account-credentials) guide for:
> Creating a service account
> Generating a key for the service account
> Adding the service account as an OAuth client in your google domain
```

**Comment by mrajashree** [comment]
Can "Step Two" include the following as the last instruction:
Upload the downloaded JSON file in the OAuth credentials box

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/65366306-ad0a2e80-dc54-11e9-8534-5faa6cc652bd.png)

@sowmyav27 @mrajashree Please help to review.

**Comment by sowmyav27** [comment]
**Verified on rancher:master-head latest**

Issues reported are fixed.
The UI is as below:
<img width="1388" alt="Screen Shot 2019-09-24 at 3 50 02 PM" src="https://user-images.githubusercontent.com/26032343/65556045-215a0180-dee3-11e9-8ee2-de9cc7db5955.png">
