### ISSUE TITLE
Support "backup" HAproxy option in our LoadBalancers

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2297]
Currently, we do not enable a backend server to operate in "backup" mode, which would allow the request to be re-directed when "Regular servers" are unavailable. (https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#5.2-backup)

Use Case: There are 2 servers ('nicheweb' & 'nichemaintenance'). I have the proxy setup to route to 'nicheweb' with a health check of '/ping'. If I take down the 'nicheweb' service, the health checks will fail, when that happens, I would like it to just proxy to 'nichemaintenance' which is just nginx serving our maintenance page instead.

**Comment by vincent99** [comment]
This is something that could be handled with https://github.com/rancher/rancher/issues/1871 , and I don't think is common enough to warrant adding a first-class option.
