### ISSUE TITLE
Enhancement on Rancher UI timeout in HA deployment

### ISSUE THREAD

**Issue by nickngch** [rancher/rancher#22979]
What kind of request is this (question/bug/enhancement/feature request):
enhancement

Steps to reproduce (least amount of steps as possible):

1. Deploy Rancher in HA deployment
2. Issue shutdown or docker stop command on one of the Rancher VMs
3. Try refresh the Rancher UI after issued the command

Result:
Rancher UI will become unresponsive for around 1 ~ 3 minutes 

Other details that may be helpful:
default timeout in Rancher ingress  (nginx.ingress.kubernetes.io/proxy-connect-timeout: "30")

**Comment by alena1108** [comment]
After talking to @cloudnautique, it looks like the relatively high - 30s - periodSeconds value was put to address an initial container start. If we dial it down, then we might need to increase `initialDelaySeconds` (currently 60 seconds) https://github.com/rancher/rancher/blob/master/chart/templates/deployment.yaml#L109
