### ISSUE TITLE
Mixed Linux/Windows workers in 2.3rc5: cattle.io/os=linux:NoSchedule

### ISSUE THREAD

**Issue by HippyRock** [rancher/rancher#22978]
Hi, I'm new to Rancher. I recently instantiated hybrid cluster with linux/windows nodes and noticed that linux nodes are marked with `cattle.io/os=linux:NoSchedule`. So I had to add extra tolerations to all my linux workloads (see [this related issue](https://github.com/rancher/rancher/issues/22403)).

So, should I consider to use just a linux cluster if 99% of my workloads are linux? Or it is OK to keep using mixed cluster with tolerations? Are there any possible drawbacks using mixed environment besides extra tolerations inconvenience?
Are you expecting to remove these taints in the future or that by design and will stay forever? 
If I stay in 2.3rc5, how hard it will be patch my cluster after funal release available? Is that some kind of in-place upgrade or will require cluster recreation?

Thanks!

**Comment by cartyc** [comment]
I get that same issue as well with my mixed cluster in rc5. If you have the resources it might be best to keep 2 clusters one for your Linux workloads and one for Windows.

**Comment by ScorchedHands** [comment]
I submitted the original issue and did not get any real response, and the issue was closed. THIS NEEDS TO BE ADDRESSED for the reasons I stated in the original issue. I think we can all agree that having the linux nodes tainted is bad form.

**Comment by WeetA34** [comment]
Hello
i have the same with final 2.3
i create a fresh cluster with windows enabled.
I only added a master and a linux worker.
It has cattle.io/os=linux:NoSchedule taint

**Comment by vincent99** [comment]
Create two separate clusters if you want user-addressable Linux and Windows nodes. 

We are not supporting mixed clusters (except for the system services), and that is the response clearly given in the previous issue.

It is more complicated to test, limits features that can be used, is more confusing for users to use, and the cost savings on a couple extra Linux nodes for the system services are negligible compared to what you're going to spend on Windows licensing.

If you're not a customer then you don't have to like that, and can technically do whatever you want, but we are not testing or commercially supporting mixed clusters.

**Comment by WeetA34** [comment]
Thank you for your clear answer :)

**Comment by lippertmarkus** [comment]
@vincent99 I'm ok with such a limitation and understand that mixed clusters make testing difficult for Rancher, but I would wish we have a setting to allow disabling the Linux taints with a clear warning that there's no official support for that, so you can use it on your own risk.

**Comment by goldsam** [comment]
We perform our builds in our Rancher cluster. We accept the risk of a mixed cluster. Unfortunately, these taints force use to introduce ugly tolerations into our deployement pod specs. This leaks details of the build environment into our projects.

**Comment by goldsam** [comment]
I feel like a fool. To future readers, this can easily be achieved as follows:
```
kubectl taint nodes <node-name> cattle.io/os-
```

**Comment by lippertmarkus** [comment]
@goldsam this only works temporarily, after some minutes, the taints are added again

**Comment by Mohkam** [comment]
I unable to install ingress.  i think Helm  does not support setting taints and tolerations. so there is no way to deploy Linux pods on mixed cluster? I agree with @lippertmarkus
