### ISSUE TITLE
Rancher v2.2.8 navbar showing different names

### ISSUE THREAD

**Issue by saiyam1814** [rancher/rancher#22985]
Rancher v2.2.8 the navbar is showing the names differently sometimes. Confirmed that it's not only me there are few users experiencing the same. 

![image](https://user-images.githubusercontent.com/8190114/65326185-830e2900-dbce-11e9-9b39-7d85d075fb65.png)

**Comment by AlexisDucastel** [comment]
Same case here, most of the time when having chrome tab opened on Rancher UI, then pc goes asleep and wake up.

**Comment by cartyc** [comment]
Can confirm I've had the same issue. It's been very intermittent so I haven't been able to pinpoint a cause. It does pop up most often in similar cases to the above ^

**Comment by deniseschannon** [comment]
We will plan to backport this into the 2.3.x series but the fix is already in master.

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by soumyalj** [comment]
Observed this issue as below in older release
![Navigation Error 2019-10-26 at 11 36 09 AM](https://user-images.githubusercontent.com/18536626/68046612-84d10f00-fc99-11e9-919c-76c9b5c0c586.png)

Tested with v2.3-head with UI-index latest-2.3 , did not observe the navigation bar error .
