### ISSUE TITLE
new cluster can not create successfully，and some existed cluster can not provisioning successfly

### ISSUE THREAD

**Issue by xinxinzhao1212** [rancher/rancher#22982]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
I had upgrade rancher release before

**Result:**
cluster provisioning fail and do not do any action，in the above of the rancher page ，one cluster shows：

***********************************************************************************
	
This cluster is currently Updating; areas that interact directly with it will not be available until the API is ready.

Exit status 1, unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request ; failed to get Kubernetes server version: Get https://10.200.1.84:6443/version?timeout=32s: read tcp 10.200.1.84:41356->10.200.1.84:6443: read: connection reset by peer

***********************************************************************************

and another cluster shows ：
********************************************************************************
This cluster is currently Updating; areas that interact directly with it will not be available until the API is ready.

Exit status 1, unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request ; failed to get Kubernetes server version: Get https://10.200.1.88:6443/version?timeout=32s: x509: certificate has expired or is not yet valid

*******************************************************************************

when i  want to  create a new  cluster ，the new cluster always shows ：

**Error with pre-create check: "resource pool '****-ha' not found"; Timeout waiting for ssh key**

and in the above of the cluster ，it shows 

**This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

Waiting for etcd and controlplane nodes to be registered**
--

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher version is 2.2.5
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
all the clusters above are vsphere Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by stefanvangastel** [comment]
Same issue with air gap 2.3.0, docker 19.3 ce.
