### ISSUE TITLE
[rancher-python] rancher.Client connect with specify certificate

### ISSUE THREAD

**Issue by dommgifer** [rancher/rancher#22980]
I tried to use rancher-python to controller rancher.

My code:   `client = rancher.Client(url=BASE_URL, token=token, verify=True)`

I get certificate from Rancher UI  -> Setting -> cacerts.

I checked source code of rancher.py, 

the Client function of __init__() only support these parameter: 
```
def __init__(self, access_key=None, secret_key=None, url=None, cache=False,
                 cache_time=86400, strict=False, headers=None, token=None,
                 verify=True, **kw)
```
How to specify certificate in rancher.Client ?

**Comment by jmaroeder** [comment]
`verify` is a parameter to the underlying `requests` library powering the HTTP calls. To specify a CA file, pass a str containing the path to a CA_BUNDLE file (`.pem` file) or a directory of trusted CAs (see https://requests.readthedocs.io/en/master/user/advanced/#ssl-cert-verification for more)
