### ISSUE TITLE
When adding git type of Catalogs, kind is helm

### ISSUE THREAD

**Issue by cabbage89** [rancher/rancher#22981]
When I add custom catalogs  ，
https://192.168.15.30:60443/v3/projectCatalogs/p-7zskj:puffinchart

`{
"actions": {
"refresh": "…/v3/projectCatalogs/p-7zskj:puffinchart?action=refresh"
},
"annotations": { },
"baseType": "projectCatalog",
"branch": "master",
"conditions": [
{
"lastUpdateTime": "2019-09-20T09:09:59Z",
"message": "Unexpected HTTP status code 404 from [https://github.com/xxx/xxxx.git/index.yaml], expected 200",
"reason": "Error",
"status": "False",
"type": "Refreshed"
}
],
"created": "2019-09-20T09:09:58Z",
"createdTS": 1568970598000,
"creatorId": "user-n6ms8",
"description": "",
"id": "p-7zskj:puffinchart",
"kind": "helm",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"exportYaml": "…/v3/projectCatalogs/p-7zskj:puffinchart/exportyaml",
"remove": "…/v3/projectCatalogs/p-7zskj:puffinchart",
"self": "…/v3/projectCatalogs/p-7zskj:puffinchart",
"templates": "…/v3/templates?projectCatalogId=p-7zskj%3Apuffinchart",
"update": "…/v3/projectCatalogs/p-7zskj:puffinchart"
},
"name": "puffinchart",
"namespaceId": null,
"projectId": "c-8zzhh:p-7zskj",
"state": "refreshed",
"transitioning": "error",
"transitioningMessage": "Unexpected HTTP status code 404 from [https://github.com/xxxxx/xxxx.git/index.yaml], expected 200",
"type": "projectCatalog",
"url": "https://github.com/xxx/xxxxx.git",
"uuid": "6b3f3c6d-db86-11e9-94e7-0242ac110002"
}`

There is a bug here
**"kind": "helm"**
should be
**"kind": "helm:git"**

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4` UI: `v2.2.70` |
|Route|`authenticated.project.project-catalogs`|

**Comment by superseb** [comment]
This is auto detected as described in https://github.com/rancher/rancher/issues/15330, you can check manually why it doesn't work over Git using `git ls-remote $URL` in the container.
