### ISSUE TITLE
2.3 rc5 Not Reporting CPU cores properly

### ISSUE THREAD

**Issue by cartyc** [rancher/rancher#22988]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Add windows node to the cluster.

**Result:**

Cluster only reports having a cpu of `0.5` cores.

**Environment information**
- Single Node Rancher 2.3 rc5
- k8s v1.15.4

**Comment by davidnuzik** [comment]
How many CPU cores does the Windows machine have? We follow k8s recommendations and reserve CPU cores and Memory for the Windows host OS. I believe 1.5 CPU cores are reserved for the windows host OS and I believe 2GB is reserved of memory.

**Comment by loganhz** [comment]
@orangedeng @thxCode Can we only reserve memory for Windows node?
It only mentioned the memory reservation for Windows, Docker, and Kubernetes processes via https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#memory-reservations-and-handling

**Comment by cartyc** [comment]
@davidnuzik The machine have 2 CPU's each so that makes sense that they'd be reporting only .5 cores free. The odd part is that I would still expect it to say that 2 cores are there instead of saying `0.5` core exists (in the node list view).

**Comment by deniseschannon** [comment]
@tfiduccia do you think we should do something to note that we only show the cores of what is free versus what exists?

**Comment by tfiduccia** [comment]
@deniseschannon - Yes I think we should do something. @lvuch and I will take a look.

**Comment by tfiduccia** [comment]
Closing in favor of: #23314
