### ISSUE TITLE
Convert a existing cluster to start using RKE templates 

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#22992]
Cluster templates need to be leveraged with existing clusters. 

Applying a new template to a cluster configuration is potentially dangerous and could break the downstream cluster.

A clusters current configuration should be exportable into a cluster template. 
From then on the cluster can be managed via revisions of this template. 
This template can be applied to other clusters.

**Comment by prachidamle** [comment]
Corresponding UI ticket: https://github.com/rancher/rancher/issues/23325

**Comment by westlywright** [comment]
Removing myself because I am now attached to the UI ticket.

**Comment by prachidamle** [comment]
This fix can be tested via API now - this is available only via API.
The UI changes are being worked on.

**Comment by soumyalj** [comment]
Tested with v2.3-head using UI-index latest-2.3
Feature to export a RKE template from an existing cluster is functional. 
Subset of the tests executed from the test plan : 
1.  Export rke template/revision  (T1/R1) from an existing cluster. Create a cluster C1 using R1
2.  Create a new revision from R2 from R1. Create a cluster C2 using R2
3.  Edit cluster C1 and change revision to R2
4.  Export rke template/revision  (T1/R1) from an existing cluster. Create a cluster C1 using R1
5.  Create another revision R2 (by cloning R1) with overrides for K8s version and other fields
6.  Create a cluster with S3 configuration parameters set. Export rke template from the cluster (T1/R1) and create another cluster using R1. The cluster gets created successfully with all S3 config parameters and the cluster is functional.
