### ISSUE TITLE
Issues in edit storage class and persistent volumes of unsupported volume sources when  `unsupported-storage-drivers` is to false

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22998]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. under `/v3/features`, `unsupported-storage-drivers` is set to true.
2. Create a storage class and a persistent volume in a cluster for a Volume source from the unsupported list, say `StorageOS`.
3. Through the API, set `unsupported-storage-drivers` is to false.

**Issue#1**

- Go to Cluster --> Storage --> Storage Classes
- Edit the storage class created in Step 2.
- Add parameters and click on Save. User is forbidden from making changes. An error is seen.

<img width="1300" alt="Screen Shot 2019-09-20 at 1 09 34 PM" src="https://user-images.githubusercontent.com/26032343/65355935-01a3a000-dba8-11e9-931c-fb8810072aa8.png">

**response:** `{"baseType":"error","code":"Invalid","message":"StorageClass.storage.k8s.io \"test1\" is invalid: parameters: Forbidden: updates to parameters are forbidden.","status":422,"type":"error"}`

- Whereas go to Cluster --> Storage --> Persistent Volume 
- Edit volume created in Step 2. 
- User is able to modify the volume and save the changes

Issuerancher/rancher#1 is tracked here -- https://github.com/rancher/rancher/issues/23015

**Issue#2**
- go to Cluster --> Storage --> Persistent Volume 
- Edit volume created in Step 2. 
- UI fails to show details in certain fields.
- - `Plugin Configuration` section does not show the actual text/details
- - Volume Plugin is seen as n/a
<img width="1289" alt="Screen Shot 2019-09-20 at 1 24 47 PM" src="https://user-images.githubusercontent.com/26032343/65357098-dec6bb00-dbaa-11e9-9351-5c3e49619ce2.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest
- Installation option (single install/HA): single

**Comment by codyrancher** [comment]
I have a change coming in to fix issue 2. However I don't think that issue 1 and issue 2 are related. I reverted my change https://github.com/rancher/ui/commit/348c1c38e20ba8dbbf4bfb0e74f457518a15f46c and issue 1 is still present. Is it not intended behavior? 

If it's not intended behavior how do we want to proceed? Should we add support to edit those fields? Should we make the fields non-editable like we see in the storage class editor?

**Comment by sowmyav27** [comment]
verified issue#2 on master-head - latest

Steps:

- Under /v3/features, unsupported-storage-drivers is set to true.
- Create a storage class and a persistent volume in a cluster for a Volume source from the unsupported list, say StorageOS.
- Through the API, set unsupported-storage-drivers is to false.
- go to Cluster --> Storage --> Persistent Volume
- Edit volume created in Step 2.
- UI shows expected data in all the fields. 
- Verified using couple of other volume sources - Ceph Filesystem, Gluster Volume

Closing the issue.
