### ISSUE TITLE
ui components don't rendered well

### ISSUE THREAD

**Issue by christian1607** [rancher/rancher#22997]
*Describe your issue here*
![image](https://user-images.githubusercontent.com/16766274/65355035-9ca37680-dbb6-11e9-90e5-4dd09a936e57.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.7` UI: `v2.2.93` |
|Route|`ingresses.index`|

**Comment by superseb** [comment]
Duplicate of https://github.com/rancher/rancher/issues/22985
