### ISSUE TITLE
Vsphere Node Template Selectors

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#23002]
Placeholder for UI changes for updates to vsphere node templates. we will want to pull data frmo vsphere and populate selectors for `docker-machine` so the node template creation process is simpler. 

Related issue to add endpoints: https://github.com/rancher/rancher/issues/23001

**Comment by deniseschannon** [comment]
@cjellick @luthermonson is the backend ready for this?

**Comment by luthermonson** [comment]
@deniseschannon you asked on 3 cards but ill respond here since this is the one the backend is actually being created on. https://github.com/rancher/rancher/pull/23242 is the WIP and a rancher server container was passed to @codyrancher who is working on the front end. so it's ready enough to proceed with front end. i'm still investigating http connection leaks and have been asked for minor tweaks which ill update before this is final.

**Comment by deniseschannon** [comment]
Thanks @luthermonson. I was triaging the UI tickets. @codyrancher can you move the UI issues into the "working" column for the ones that you're working on for vsphere?

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
UI: `latest-2.3` 

* Fields are populated by data from vCenter:
  * Datacenter
  * Resource Pool
  * Data store
  * Folder
  * Host
  * Networks
  * Tags
  * Custom Attributes
