### ISSUE TITLE
Support for updating metadata for a service using rancher-compose.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2300]
Rancher server version - v0.41.0-rc1
Rancher compose version - rancher-compose-v0.4.1-rc2

API allows for editing metadata field for a service. There is no way in rancher-compose to edit a metadata field for a service.

**Comment by deniseschannon** [comment]
This is solved by updating the metadata in rancher-compose.yml and doing a `rancher-compose up --upgrade`.

**Comment by sangeethah** [comment]
Tested with rancher compose version - rancher-compose-v0.5.0 , we are allowed to update metadata field by setting the metadata value in rancher-compose and using  rancher-compose up --upgrade command.
