### ISSUE TITLE
Vsphere API Lookup Endpoints

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#23001]
With this [PR](https://github.com/rancher/machine/pull/37) we will start supporting vsphere cloning and we will upgrade our UI experience to allow for flags to be set in `docker-machine`. The field values for `docker-machine` are kind of cryptic and this is an issue to track adding in support for API endpoints to allow the UI to make requests into Vsphere and get answers to questions like "give me vms matching ubuntu-*" and populate selectors to make this process easier.

From a quick conversation with UI it sounds like we'll need an auth endpoint to validate cloud credentials and an endpoint to pull all data back from the vsphere server.

Fields we will want to have selectors for
* data centers
* hosts
* content libraries
* resource pools
* data stores
* folders?
* hosts
* networks

**Comment by luthermonson** [comment]
UI Issue: https://github.com/rancher/rancher/issues/23002

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/23242

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
UI: `latest-2.3` 

* Fields are populated by data from vCenter using endpoints:
  * Datacenter
  * Resource Pool
  * Data store
  * Folder
  * Host
  * Networks
  * Tags
  * Custom Attributes
  * Content libraries
  * Existing VMs
  * Templates
