### ISSUE TITLE
no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by getvivekv** [rancher/rancher#23006]
Possible Bug due to Kubernetes API depreciation. 
Steps to reproduce

- Spin up a VM that has Ubuntu 18.
- Install Docker 18.09
- Install kubernetes v1.16.0
- Install Rancher 2.2.8
- Open Racher UI and import existing cluster

You'll see errors
- no matches for kind "Deployment" in version "extensions/v1beta1"
- no matches for kind "DaemonSet" in version "extensions/v1beta1"

```

root@k8s-m-1:~# kubectl apply -f 9bjzpbp4rft5tv4qhkgrgk6l5rjw8754c8mfntm8hbvv8czlrkhcq8.yaml 
clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver unchanged
clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master unchanged
namespace/cattle-system unchanged
serviceaccount/cattle unchanged
clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged
secret/cattle-credentials-d61ffc4 unchanged
clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged
unable to recognize "9bjzpbp4rft5tv4qhkgrgk6l5rjw8754c8mfntm8hbvv8czlrkhcq8.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "9bjzpbp4rft5tv4qhkgrgk6l5rjw8754c8mfntm8hbvv8czlrkhcq8.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
root@k8s-m-1:~# 
```

Note: I had to download the .yaml file locally because of the certificate issue. 

```
root@k8s-m-1:~# kubelet --version
Kubernetes v1.16.0
root@k8s-m-1:~# 
root@k8s-m-1:~# docker -v
Docker version 18.09.7, build 2d0083d
root@k8s-m-1:~# 
```

Rancher 2.2.8

**Comment by JerryCurl** [comment]
Rancher does not support Kubernetes 1.16 yet

**Comment by superseb** [comment]
This is fixed in https://github.com/rancher/rancher/pull/22457 and will be in the next release.

**Comment by cipianpascu** [comment]
just tried to upgrade to 1.17.0 and got the same error:
unable to recognize "/etc/config/rke-network-plugin.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
