### ISSUE TITLE
Support for Custom Image Name or ID on Azure Node Templates

### ISSUE THREAD

**Issue by dragoicaru** [rancher/rancher#23010]
Is there a workaround to beb able to use Custom Images names or IDs for Azure Node Templates? Currently Rancher Node Template Image field only support Image with URN format publisher:offer:sku:version

Best regards,

Edgar.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.7` UI: `v2.2.93` |
|Route|`global-admin.clusters.index`|

**Comment by bentastic27** [comment]
A customer is running into this. Adding related tags.

**Comment by bentastic27** [comment]
Likely related? https://github.com/docker/machine/issues/4233

**Comment by kinarashah** [comment]
Available to test in `2.4.3-rc1`

**Comment by aiyengar2** [comment]
Custom images can now be supplied using the ARM resource identifier (the fully qualified ID of the resource used by the [Resource Management API](https://docs.microsoft.com/en-us/rest/api/resources/resources/getbyid)) of the custom image you would like to use. Just providing the custom image name is not supported.

This ID can be found by locating the resource on the Azure portal and using the ARM resource identifier embedded in the URL. The link to any Azure resource follows the format https://portal.azure.com/{organization}/resource/{arm-resource-identifier}/overview.

I created some dummy resources to test with within the [CustomImagesTestingResources resource group](https://portal.azure.com/#@rancher.com/resource/subscriptions/14a619f7-a887-4635-8647-d8f46f92eaac/resourceGroups/CustomImagesTestingResources/overview). We should be able to spin up a VM with both the Image and Image Version within the provided resource group.

We maintain support for the Image URN format (provider:sku:offer:version) as well.

**Comment by soumyalj** [comment]
Tested with Rancher version v2.4.3-rc1. 
**Use case 1.**

- Created a azure node template using a custom image in the same resource group as the image. 
- Created a Azure cluster(node driver) using this template. Cluster was active and workload creation was successful. 

**Use case 2.**

- Created a azure node template using a custom image in a new resource group(different than the resource group where custom image exists)
- Created a Azure cluster(node driver) using this template. Cluster was active and workload creation was successful.

**Comment by soumyalj** [comment]
Validated with master-head build(7e3542bcf)
**User case 1:**
1. Created a azure node template using a custom image in the same resource group as the image.
2. Created a Azure cluster(node driver) using this template. Cluster was active and workload creation was successful.

**Use case 2:**
1. Created a azure node template using a custom image in a new resource group(different than the resource group where custom image exists)
2. Created a Azure cluster(node driver) using this template. Cluster was active and workload creation was successful.
