### ISSUE TITLE
Rancher 2.4 Scaling Targets

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#23013]
# Rancher aims to hit 2,000 clusters and 100,000 nodes under management. 

Based on Kubernetes published limits a single cluster can have 5000 nodes. If we were to run maxed out nodes, we could have (20) clusters with our 100,000 node target. At the opposite end of the spectrum, we would like to achieve a maximum configuration from a cluster stand point we could have 10,000 clusters with 50 nodes each. 

We need to determine in these tests, where etcd tips over. Once determined, we need to prove we can exceed these limits with k3s against alternate backends.

Test cases:
Hit a maximum of 10,000 single node clusters. (maximum of 10,000 clusters)
Attach 400 clusters with 250 nodes per cluster. (100,000 nodes)
Attach 20 clusters each with 5,000 nodes per cluster. (Maximum sized k8s clusters)
Hit a maximum of 2,000 clusters with 50 nodes in each cluster. (max clusters with max nodes)
Attach 1,000 clusters each with 100 nodes per cluster. (Mid point test)

Constraints:
This will be a test of Rancher in HA mode. A single Rancher server node **Should not** need more than 32vCPUs and 128GB of Ram.

For each of these tests:
Clusters will be imported.
All Rancher agents need to be deployed, operational and in a green state from the UI, and maintain status. 
Rancher management pods need to be able to go down to scale 0, and back up to the number of nodes.
Rancher management pods need to be upgraded from one version to the next. 
Rancher should be able to deploy a multi-cluster app to all clusters.
Rancher needs to be able to support 100 concurrent cluster provisions.

API SLOs / SLAs:
Any single object DELETE,POST,GET,PUT response should return in <200ms, in cases of large objects TTFB can be used.
Any list API call <5s
UI Load should <10s

## Deliverables:
- Enable Rancher server level prometheus metrics for increased visibility in the the Rancher controllers. This can be based on work of one of our community members: https://github.com/rancher/rancher/pull/21351
  - This should produce a Grafana dashboard for monitoring Rancher servers with Rancher metrics if deployed into the local cluster.

###
- UI Should introduce a concept of tagging/grouping to accommodate management of nodes and clusters.

This issue will likely spawn additional issues to address bottlenecks.

**Comment by dramich** [comment]
On restart at 2k clusters rancher should:

- Connect to all downstream clusters within 1min - The UI should be usable in the downstream cluster with the expectation that side affects of the controllers running won't happen until they are running for that cluster
- Within 5 min all downstream clusters controllers are running and CPU load on the rancher host/s have settled into an idle state.

**Comment by deniseschannon** [comment]
Please refer to https://rancher.com/docs/rancher/v2.x/en/installation/requirements/#hardware-requirements for the latest sizing guide based on number of nodes and clusters that you want to manage.
