### ISSUE TITLE
OpenStack: extend openstack auth options

### ISSUE THREAD

**Issue by kayrus** [rancher/rancher#23018]
* Use user_domain_name/user_domain_id auth options, when the keystone user is created not in the same domain, where the auth scope is required. Similar request in the kuberneter openstack cloud provider: https://github.com/kubernetes/cloud-provider-openstack/pull/733
* Add OpenStack application credential auth support. App cred allows to impersonate the keystone user without using its original credentials. This is useful, when keystone uses LDAP as a backend. More info about application credentials:
  * https://docs.openstack.org/keystone/queens/user/application_credentials.html
  * https://www.youtube.com/watch?v=fm1pVRIpjjo
  * https://www.openstack.org/assets/presentation-media/Enabling-Cloud-Native-Applications-with-Application-Credentials-in-Keystone.pdf

New auth options should be added at least into:
* rancher terraform provider:
  * https://github.com/rancher/terraform-provider-rancher2/blob/a336212ab6fb913011f9b5353c6ecd9b16d1f800/rancher2/structure_cluster_rke_config_cloud_provider_openstack.go#L25
  * https://github.com/rancher/terraform-provider-rancher2/blob/a336212ab6fb913011f9b5353c6ecd9b16d1f800/rancher2/structure_cluster_rke_config_cloud_provider_openstack.go#L244
  * https://github.com/rancher/terraform-provider-rancher2/blob/a336212ab6fb913011f9b5353c6ecd9b16d1f800/rancher2/schema_node_template_openstack.go
  * https://github.com/rancher/terraform-provider-rancher2/blob/a336212ab6fb913011f9b5353c6ecd9b16d1f800/rancher2/structure_node_template_openstack.go
  * https://github.com/rancher/terraform-provider-rancher2/blob/a336212ab6fb913011f9b5353c6ecd9b16d1f800/website/docs/r/nodeTemplate.html.markdown#L187
  * https://github.com/rancher/terraform-provider-rancher2/blob/a336212ab6fb913011f9b5353c6ecd9b16d1f800/website/docs/r/cluster.html.markdown#L249
* rancher openstack auth type: https://github.com/rancher/types/blob/59fbe5e3a97f16784ca344e72d4d03455f42fc88/apis/management.cattle.io/v3/rke_types.go#L546
* https://github.com/rancher/charts

As a side effect, it will be possible to automatically generate application credentials using [openstack terraform provider](https://www.terraform.io/docs/providers/openstack/r/identity_application_credential_v3.html) and consume them in the rancher terraform provider.

**Comment by SvenMW** [comment]
Was this issue just never updated?
I'm confused by the state of appilcation credential support in rancher.

The GUI in the node templates has at least the necessary fields to input application credentials, but I couldn't make it work, yet.
Is this implemented?

Via the above reference to:
https://github.com/rancher/types/blob/59fbe5e3a97f16784ca344e72d4d03455f42fc88/apis/management.cattle.io/v3/rke_types.go#L546
I at least can't find any corresponding declaration of an application credential type on current master:
https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/rke_types.go#L621

But I'm not that familiar with the rancher codebase, so maybe this was implemented differently?
Any insights would be appreciated.

**Comment by kayrus** [comment]
@SvenMW application credentials were implemented in docker machine and should work. can you investigate API calls via mitmproxy?

**Comment by SvenMW** [comment]
yeah, sorry for not following up on this here.

It kind of works, the application credentials seem to get accepted, but I can't for the life of me provision openstack vms with it, with the same node template I was using successfully with my personal openstack account (this is a private cloud).

I guess this might be related to the specified ssh keypair in openstack. as far as I could find, this resource is bound to the user who created it.

I'll try and recover the logs from the failed attempts. I must say, though, that in general the rancher-machine logs aren't really helpful when debugging issues with it and openstack

**Comment by SvenMW** [comment]
working node template for the openstack node driver (using personal account data, not what I really want):

https://gist.github.com/SvenMW/96f1ff2fe3874c19a67db73046fa8f42

not working node template, trying to use appcredentials:

https://gist.github.com/SvenMW/d6ad33a56f6b75588beaed4dcb33089b

error in rancher gui:

Error creating machine: Error in driver during machine creation: No suitable endpoint could be found in the service catalog.; Timeout waiting for ssh key


the service catalog thing comes from gophercloud when it can't find some specific service in openstack.

as all these things exists in openstack (train release btw), and the app credentials provided live in the same project and have admin scoped credentials I figured it might be due to the ssh keypair mentioned.

Because the keypair is bound to my user, and might be therefore not visible with application credentials.

it's also weird that I still have to provide a username when providing application credentials, I would, in fact, consider this a bug?

This is the latest rancher version running on ubuntu 20.04 btw.

Any help or hints would be appreciated.

**Comment by kayrus** [comment]
@SvenMW how exactly did you create app creds? Did you specify limited roles?
For app creds auth you have to specify very limited information, in your case you specified username and user domain name.

See https://github.com/gophercloud/gophercloud/issues/1365#issuecomment-448294161 for more details.

**Comment by SvenMW** [comment]
> @SvenMW how exactly did you create app creds? Did you specify limited roles?
via the openstack cli:
```bash
openstack application credential create --role admin --description "brandnew rancher creds" rancher_new 
openstack application credential show rancher_new                                                                                                                                     
+--------------+------------------------------------------------------------------+
| Field        | Value                                                            |
+--------------+------------------------------------------------------------------+
| description  | brandnew rancher creds                                           |
| expires_at   | None                                                             |
| id           | b7f9b9d5f7c64b9bbc52959af0701063                                 |
| name         | rancher_new                                                      |
| project_id   | 2c7386b4743244c3a5f67023e54a35d0                                 |
| roles        | admin                                                            |
| system       | None                                                             |
| unrestricted | False                                                            |
| user_id      | 8bde5b55927ac22d06e71e55d18d83f5f90b321997f17daca81d86ded88220a9 |
+--------------+------------------------------------------------------------------+

```

> For app creds auth you have to specify very limited information, in your case you specified username and user domain name.
> 
> See [gophercloud/gophercloud#1365 (comment)](https://github.com/gophercloud/gophercloud/issues/1365#issuecomment-448294161) for more details.

so I went ahead and altered the template: i deleted username and user domain name and added the user id.
I get no authentication error, but still the same error about the service catalog:
```
 Error creating machine: Error in driver during machine creation: No suitable endpoint could be found in the service catalog.; Timeout waiting for ssh key 
```

I also could not find any documentation which states that the user id is required.
To me, the whole point of application credentials is, to have some sort auf auth token, _without_ tying it to a specific user.

**Comment by kayrus** [comment]
@SvenMW usually admin role is not enough, it is used only for project user management. Try not specifying the role, therefore application credential will inherit all the current user roles.

**Comment by SvenMW** [comment]
> @SvenMW usually admin role is not enough, it is used only for project users management. Try not specifying the role, therefore application credential will inherit all the current user roles.

First, thanks for all your help! really appreciated!

what you say makes sense, so I went ahead and created brand new credentials, which now look like this:
```bash
openstack application credential create --description "rancher cred test without role" rancher_test_july                                                                                         ✔  10284  10:05:35
+--------------+----------------------------------------------------------------------------------------+
| Field        | Value                                                                                  |
+--------------+----------------------------------------------------------------------------------------+
| description  | rancher cred test without role                                                         |
| expires_at   | None                                                                                   |
| id           | 5e768a4b42764d299854cbb0a12c1ca3                                                       |
| name         | rancher_test_july                                                                      |
| project_id   | 2c7386b4743244c3a5f67023e54a35d0                                                       |
| roles        | admin reader member                                                                    |
| secret       | REDACTED |
| system       | None                                                                                   |
| unrestricted | False                                                                                  |
| user_id      | 8bde5b55927ac22d06e71e55d18d83f5f90b321997f17daca81d86ded88220a9                       |
+--------------+----------------------------------------------------------------------------------------+

```

In order to not mess up the node templates I cloned the working version (see above) with the username/password combination and changed the following:

- added credential name and secret
- deleted UserDomainName and User
- added UserID
- resubmitted the private key files contents

and it works!

can I buy you a beer or a beverage of your liking, maybe at fosdem next year @kayrus ? awesome! thanks for your guidance!

**Comment by kayrus** [comment]
> can I buy you a beer or a beverage of your liking, maybe at fosdem next year @kayrus ? awesome! thanks for your guidance!

I'll keep this in mind for the next February ;)

**Comment by SvenMW** [comment]
note for anyone stumbling on this:
the role ``` --role member``` is enough to provision vms in openstack with rancher, you do not need to grant admin permissions!
