### ISSUE TITLE
Main Epic for Zero Downtime upgrades

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#23038]
The MVP for zero down time upgrades is that a user's application can not be impacted by Rancher's upgrade process of Kubernetes. At a minimum this means that the user's workloads need to be available on at least a single node and that all critical add on services are available, though possibly degraded, during the upgrade.

The following needs to be true of a user's cluster:
1. 3 or more etcd nodes 
1. 2 or more control plane nodes
1. 2 or more worker nodes 
1. Ingress, DNS and other add ons are schedulable to more than a single node.
1. The upgrade is from minor release to the next or within the same patch release series. Skipping minor releases will not be supported as zero downtime.

From a user workload perspective the following will need to be true:

1. User's applications are deployed with a scale >1 and across more than a single node.
1. User's applications make use of liveness and readiness probes.

To achieve MVP:
* Before starting the upgrade of worker nodes, the etcd and control plane nodes need to be upgraded first. 
* Worker nodes will be updated in a user specified batch size.
  * The next batch will only be upgraded when the previous batch has returned to service.
* Configure the addon upgrade options and disruption budgets based on the number of nodes in the cluster.
  * The max.unavailable and max.surge values should be user specified.
  * Use Pod Disruption Budgets where it makes sense.
* Documentation to explain the upgrade process of RKE provisioned clusters needs to be provided.

Upgrades of the Kubernetes control plane should be handled similarly.
1. Control plane nodes should be upgraded 1 node at a time.
1. The control plane node should come completely back up before moving to the next. 

Etcd nodes:
1. Current upgrade procedures already handle zero downtime upgrades.

Granular control of when upgrades happen:
1. Operationally user's would upgrade the etcd plane first. Followed by control and then upgrading the worker pool. Allowing user's the ability to control the upgrade of the various tiers is key.

As part of this, we also need to be able to rollback to the previous version and restore a snapshot of the data. Such that the recommended best practice would be:
1. take a snapshot of cluster.
1. initiate upgrade.
If upgrade fails
1. rollback to previous version
1. restore etcd snapshot.

----
Related issues:
rancher/rancher#20465
rancher/rancher#17057

**Comment by lvuch** [comment]
https://xd.adobe.com/view/ebd4dccd-69a0-41fb-78af-907601a6a2f6-9de5/

**Comment by cloudnautique** [comment]
To elaborate on the restore/rollback functionality.

The user flow for the feature is that:
1. The user took a snapshot before initiating a cluster upgrade. 
1. The user initiated an upgrade once the snapshot was complete.
1. During the upgrade, the user decided it is not going well and needs to revert/rollback the changes.
1. The user selects to revert the kubernetes upgrade to the pre-upgraded version and restore the snapshot taken just before upgrade.

In this workflow we need to assume the following:
1. Rancher should know the version of the Kubernetes version running before the upgrade at the time the snapshot was taken. This should be used by Rancher when rolling back to prevent user error.
1. The cluster is likely in a failed state, and Rancher might have to be aggressive in how it handles reverting.
1. Before using the snapshot in the etcd datastore, the cluster should be running the pre-upgrade kubernetes version.

Constraints:
1. When initiating the upgrade, the user should have the option to specify a snapshot be taken.
1. The operation can be initiated via the API (Terraform UX should be able to follow the same workflow)
1. The restore operation will work on a cluster that is not in a healthy / Active state.

**Comment by Oats87** [comment]
https://github.com/rancher/rancher/issues/24975 We should also keep in mind this.

**Comment by mitchellmaler** [comment]
@cloudnautique  One use case we are trying to pursue is immutable infrastructure for OS patches and even installed software like docker and kubernetes. The no downtime approach to upgrades is great but it still re-uses the same VM that could have been spun up with a node-driver. We were wondering if there could be an option to replace (rebuild) the node that way it could use an upgraded VM template/image if the node template was updated as well. We rebuild our VM images often for OS patches, etc.

Right now we have to run a script that rolling re-creates nodes by either looping through each in a pool and deleting them and waiting for it to come back.

**Comment by sowmyav27** [comment]
**Verified on latest master-head.**

- Control plane nodes get upgraded based on maxUnavailable_control param. 
- Worker node gets upgraded based on maxUnavailable_worker param
