### ISSUE TITLE
UI for vSphere Tags

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#23031]
UI Place holder for custom tags in vSphere node pool templates. They will probably function like the guest info k/v pairs and be passed to a new stringslice param on `docker-machine`

Related Backend Issue: https://github.com/rancher/rancher/issues/22660

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
UI: `latest-2.3` 

* Tags are retrieved from vCenter and displayed in a dropdown. 
* Multiple tags can be added
* When node is created from template, the tags are assigned correctly.
