### ISSUE TITLE
Kuberntes 1.15 as officially supported on Rancher 2.2.x

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#23041]
Currently k8s 1.15 is experimental on 2.2.x. We have to enable an official support for it, and drop support for k8s 1.12 with that change.

**Comment by jiaqiluo** [comment]
The validation is done in rancher:v2.2.9-rc1 

Checks:
- v1.15.4-rancher1-1 is shown as the default and not experimental 
- v1.12 is not shown in the list 


Deploy a cluster with  k8s v1.15.4-rancher1-1
- cluster and project monitoring works
- cluster and project alerting works
- pipeline works
