### ISSUE TITLE
Documentation Link Broken

### ISSUE THREAD

**Issue by bscott** [rancher/rancher#2304]
https://rancherio.github.io/rancher/docs/infrastructure/hosts/amazon/#EC2Ports does not work

![image](https://cloud.githubusercontent.com/assets/191290/10408742/9b1764dc-6ebb-11e5-9556-67f75f45d895.png)

**Comment by deniseschannon** [comment]
What version of Rancher are you using? Can you click on the cow in the upper left corner. We updated the docs site/links in the product about 3 months ago?

**Comment by deniseschannon** [comment]
The new link is http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/amazon/#EC2Ports and is in hte latest version.
