### ISSUE TITLE
Edit Alert Rule -> No metic graph data.

### ISSUE THREAD

**Issue by sauber** [rancher/rancher#23049]
**What kind of request is this (question/bug/enhancement/feature request):**
Spelling

**Steps to reproduce (least amount of steps as possible):**
Edit Alert Rule "Database usage close to the quota 500M"

**Result:**
Below Expression is highlighted in red "No metic graph data."

**Other details that may be helpful:**
"metic" is misspelled. It should spell "metric".

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
v2.2.8.
I have seen same in previous versions

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by tfiduccia** [comment]
@sauber - This was fixed for 2.3. 
![image](https://user-images.githubusercontent.com/11514927/65541675-a385fe00-dec2-11e9-8d4b-b42d490c4595.png).  I'm going to close this, if after upgrading you see again can you take a screen shot.  Thanks.
