### ISSUE TITLE
SUSE Linux sp5 Support

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#23044]
Suse Enterprise Linux 12 SP5 needs to be supported fully.

* Validate Rancher HA setup
* Validate Rancher custom cluster
* Validate Rancher AMI / node driver

**Comment by sangeethah** [comment]
https://www.suse.com/releasenotes/x86_64/SUSE-SLES/12-SP5/

**Comment by aaronRancher** [comment]
Found the following while validating SUSE:
#25067 
#25071 
#25072

**Comment by aaronRancher** [comment]
#25082

**Comment by cloudnautique** [comment]
For Rancher 2.4.0 we only need coverage for the Custom cluster workflow. The AMI/Node driver flow will be handled in a follow up release.

**Comment by sangeethah** [comment]
SUSE Enterprise Linux 12 SP5 with kernel version 4.12.14-122.12 and docker 19.03.5 has been validated for Rancher HA setup and Rancher Rancher custom cluster.

AWS ami used - suse-sles-12-sp5-v20191209-hvm-ssd-x86_64 - ami-0d808701ac55e8ef7 with
kernel version 4.12.14-122.12

Support for SUSE Enterprise Linux  OS with a node driver cluster is tracked in https://github.com/rancher/rancher/issues/25071
