### ISSUE TITLE
v2.3.0-rc8 storageclass/persistentvolume some items are dissapeared in webUI

### ISSUE THREAD

**Issue by freeloop914** [rancher/rancher#23047]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Just want to create storage class for openstack cinder volume then I found there was no option.
But I can create it by API

**Result:**
![image](https://user-images.githubusercontent.com/47173356/65492161-07b8ba00-dee3-11e9-8016-ed8dd50110d3.png)

**Comment by tfiduccia** [comment]
@freeloop914  - To view all the drivers including the unsupported ones, you have to set the unsupported-storage-drivers setting to true.  To do this go to ...v3/features/unsupported-storage-drivers and edit, change the value to true.  Then you will see openstack and all the other drivers again.
