### ISSUE TITLE
Add Alibaba App Hub in catalog and disable it by default

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23042]
Add Alibaba App Hub in catalog and disable it by default

![image](https://user-images.githubusercontent.com/21168270/65478792-a9c5ab80-debd-11e9-81f8-4c5160d5cd71.png)

**Comment by sangeethah** [comment]
Tested with latest build from master.
We see global catalog "alibaba-app-hub" disable it by default in the Global->Tools->Catalog page.

<img width="1029" alt="Screen Shot 2019-09-24 at 11 03 57 AM" src="https://user-images.githubusercontent.com/4266958/65538833-0eccd180-debd-11e9-859c-2f347b814faf.png">

**Comment by rootwuj** [comment]
Version: master-head 883c41e02
Environment: aliyun, aws
* Global catalog can see `alibaba-app-hub` and is disabled by default.
* Enable `alibaba-app-hub`, global and project apps can see all AppHub charts.
* Launch some apps in `alibaba-app-hub` and the apps can Launch successfully.
