### ISSUE TITLE
UI: bubble user's node templates to top of list

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#23054]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Expected:**
When using node template drop down or node templates view, all node templates will be presented in an order that ignores who created them

**Desired:**
Users own node templates should be at the very top.
_Note:_ node templates view should also probably include the node template author/owner now.

**Backend:**
https://github.com/rancher/rancher/issues/12186

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/23026

**Comment by cjellick** [comment]
Per a previous discussion, Until we hear differently from @vincent99 @westlywright or @codyrancher, going to assume this can be achieved with the API as-is.

**Comment by vincent99** [comment]
@cjellick I don't think "probably include the node template author/owner" is possible in general, regular users can't see other User resources so the UI will have no way to map u-xxxxx to a name unless you add a principalId to them.

But if the only person that can see more than their own templates is admins that may not matter for now.

**Comment by tfiduccia** [comment]
@vincent99 & @lvuch - Do you think we can actually separate user's templates from templates that are created by others?  We should make it look Project/namespaces with the grey bar.  Top section would be My Templates, bottom section would be User Templates.

**Comment by codyrancher** [comment]
@tfiduccia 

I have a few questions about the template page.
1. Do we want to group by the user's Templates or TemplateRevisions?
2. What info do you want the grey bar to contain? Right now it's just RKE Template: {{Template name}}. Do you want something like "My Templates" and "Other's Templates"?
3. As of right now each group represents a single cluster template and the rows represent the template revisions. If we switch to the new grouping do we want to have sub bars that give the cluster template name? This would effectively be nested groups and I don't think the tables support that atm. I could work on adding support or we could just have two separate sortable tables. One for Me and one for Others.

**Comment by tfiduccia** [comment]
@codyrancher 
2.  Gray Bar should have "My Templates" & "User Templates".  I chose User cause that is what we refer to them as when you Add User.

1 & 3 - The node template page will stay exactly the same, except with Grey bar on top.

**Comment by codyrancher** [comment]
I just noticed the backend isn't complete for this yet so I'm moving this back to next up but will leave myself assigned since I've already started.

**Comment by codyrancher** [comment]
I ended up not bubbling the owners templates to the top of the node templates page. I instead made it behave like the referenced "Project/namespaces". If we wanted the owners templates to bubble to the top I think we'd need to create a completely separate table but then sorting could only be done on the individual tables.

**Comment by jiaqiluo** [comment]
The UI is validated in Rancher:v2.3-head with UI index `https://releases.rancher.com/ui/latest-2.3/index.html`

Results:
- under the node template page, the templates are listed under owners
<img width="1316" alt="Screen Shot 2019-10-29 at 4 09 25 PM" src="https://user-images.githubusercontent.com/6218999/67816282-b746f600-fa66-11e9-96d3-775f63418d08.png">

- [for admin only] in the page of creating/editing a cluster, the dropdown list of node templates show mine at the top.

<img width="1328" alt="Screen Shot 2019-10-29 at 4 13 20 PM" src="https://user-images.githubusercontent.com/6218999/67816512-6aafea80-fa67-11e9-88a4-31c6e84a4884.png">
