### ISSUE TITLE
Expose Redeploy from REST API Actions?

### ISSUE THREAD

**Issue by SudoBrendan** [rancher/rancher#23053]
Adding a redeploy action to the UI and on edit workload that sets `cattle.io/timestamp` annotation to the current time.

_Originally posted by @vincent99 in https://github.com/rancher/rancher/issues/13389#issuecomment-426033543_

Is there a way that this functionality could be exposed from the Rancher REST API ( maybe under a new action like .../v3/project/c-foo:p-foo/workloads/deployment:bar:bar?action=redeploy ) ? That way, we don't need to do a GET / modify / PUT ourselves if we want to redeploy something?

**Comment by keepitsimple** [comment]
A lot of people straggle without this action. I do not understand - there is stop/resume/rollback but it's not possible to redeploy via API?

**Comment by vincent99** [comment]
It is entirely possible to do that in the API today.  The UI is just an API client, anything it is doing can be done in the API by definition.  This issue is to make that action somewhat more convenient.

**Comment by westlywright** [comment]
UI has been merged. When the backend pr has been merged the UI will use the new action if available.

**Comment by rmweir** [comment]
PR has been reverted and issue reopened due to test flakiness- see post-merge feedback on PR https://github.com/rancher/rancher/pull/24777

**Comment by jiaqiluo** [comment]
this enhancement is rancher:master-head f84c1e8f7

The following validations are done for `cornjob`, `deployment`, `statefulSet`, and `daemonSet`

- deploy such kind of workload
- click the collapsed options on the workload and see `redeploy` as an action 
- view in API and confirm `redeploy` is shown as an action 
- trigger the redeploy action and confirm the workload is redeployed by checking the value of `cattle.io/timestamp` changed 
- for deployment, a new revision is shown in the list when doing an rollback
