### ISSUE TITLE
UI: should be able to change cloud credential name

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#23059]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create cloud credential.
2. Edit cloud credential.

**Result:**
There is no field to edit name.

**Comment by rmweir** [comment]
@tfiduccia confirmed that the desired behavior is to be able to edit name

**Comment by deniseschannon** [comment]
@sowmyav27 this was merged to master before 2.3 branched, so it's available in 2.3-head and in master.

**Comment by sowmyav27** [comment]
verified on v2.3-head - latest
ui tag: `latest-2.3`

User is NOT able to change the cloud credential name on Edit.
<img width="969" alt="Screen Shot 2019-10-30 at 7 57 45 PM" src="https://user-images.githubusercontent.com/26032343/67867138-f43ae780-fb4f-11e9-95bf-ab6e612e2864.png">

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sowmyav27** [comment]
**verified on ui tag: `latest-2.3.` on 2.3-head latest**

- User can change the cloud credential name on Edit.

<img width="982" alt="Screen Shot 2019-10-31 at 1 57 41 AM" src="https://user-images.githubusercontent.com/26032343/67896265-059ce780-fb82-11e9-8d48-a3734aad5265.png">
