### ISSUE TITLE
New template revision created from existing default revision does not reflect the correct default values of the fields

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#23056]
Version: Master-head

Steps:
1. Create a template/revision T1 /V1 with K8s version as v1.13.11 and set node port range and make them as questions
2. Create another revision V2 and choose K8s version as v1.15.4 and node port range with a different value and set them as questions.

For V2, the the default revisions remain the same as in V1

![Screen Shot 2019-09-24 at 10 52 20 AM](https://user-images.githubusercontent.com/18536626/65537334-e394b300-deb9-11e9-8694-7883ec92fa81.png)
![Screen Shot 2019-09-24 at 10 52 28 AM](https://user-images.githubusercontent.com/18536626/65537347-e8f1fd80-deb9-11e9-9e51-bb8f11b40cf5.png)

The default values in the new revision V2 are the same as V1

![Screen Shot 2019-09-24 at 10 57 41 AM](https://user-images.githubusercontent.com/18536626/65537491-29ea1200-deba-11e9-8dac-d275dd3c0d5c.png)

**Comment by westlywright** [comment]
Available to test on master.

**Comment by soumyalj** [comment]
Tested with build from master-head. 
Create a template/revision T1 /V1 with K8s version as v1.13.11 and set node port range and make them as questions
Create another revision V2 and choose K8s version as v1.14.7 and node port range with a different value and set them as questions.

For V2, the default revisions change accordingly
<img width="1239" alt="Screen Shot 2019-09-26 at 11 05 55 AM" src="https://user-images.githubusercontent.com/18536626/65713403-fa6c0e80-e04d-11e9-837d-83cb751ed36c.png">

<img width="659" alt="Screen Shot 2019-09-26 at 11 10 52 AM" src="https://user-images.githubusercontent.com/18536626/65713591-5a62b500-e04e-11e9-8039-8150987241eb.png">

Also verified that when creating clusters, toggling between template revisions displays the fields with questions and without questions correctly.
