### ISSUE TITLE
When cloning/Viewing template revisions created with (Latest - allows patch version upgrades) , k8s version shows the derived version instead of "Latest - allows patch version upgrades". 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#23065]
Rancher Version - Latest build from master

Steps to reproduce the problem:
Create a cluster Template revision by choosing "Latest 1.15(allows patch version upgrades" (with or without overrides).

Scenario 1:
View this template created.
Kubernetes version that is present in "v1.15.4-rancher1-1". It should be "Latest 1.15(allows patch version upgrades" 

Scenario 2:
Create a template revision using "Clone Revision" from this template.
Kubernetes version that is present in "v1.15.4-rancher1-1". It should be "Latest 1.15(allows patch version upgrades"

**Comment by westlywright** [comment]
Available to test on master.

**Comment by sangeethah** [comment]
Tested on master build.
When cloning/Viewing template revisions created with (Latest - allows patch version upgrades) , k8s version shows the correct value - "Latest 1.x (allows patch version upgrades)" as expected.
