### ISSUE TITLE
Incorrect text in "RKE Templates" view when selecting template revisions for Enable/Disable/Delete.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#23068]
Rancher server version - Build from master

Steps to reproduce the problem:

Create few templates with revision.
Select few entries and choose "Enable/Disable/Delete" option.

Notice the "cluster" text show up instead of "template revisions"

<img width="1256" alt="Screen Shot 2019-09-24 at 3 47 35 PM" src="https://user-images.githubusercontent.com/4266958/65557331-cf67aa80-dee7-11e9-97a8-c4c38d705aa1.png">

**Comment by westlywright** [comment]
Available to test on master.

**Comment by sangeethah** [comment]
Tested with build from master.

"Template Revisions" presented in  "RKE Templates" view when selecting template revisions for Enable/Disable/Delete as expected.
