### ISSUE TITLE
Hide "Custom Cluster Overrides" section in the Edit Cluster section

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#23069]
Since there is no ability to create custom overrides in the UI, in the edit cluster section, we should be hiding the "Custom Cluster Overrides" section as the UI will already allow you to "override" the values in the cluster options section.

This section was previously kept for "custom" overrides and since we had removed the ability to add custom overrides, this section should not be shown on edit cluster.

**Comment by westlywright** [comment]
Available to test on master.

**Comment by sangeethah** [comment]
Tested with build from master.

There is no "Custom Cluster Overrides" section presented in the `Edit Cluster` section.
