### ISSUE TITLE
Ability to see what templates are using a cloud credential

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#23064]
When on the page that lists cloud credentials, users should be able to see what credentials are in use and if they are in use, which node templates are using them.

One of the main reasons for this change is so that admins can clean up unused cloud credentials. v2.3.2 will have a change that allows global admins to CRUD all node templates. This change will enable global admins to fully manage the node templates and cloud credentials in their rancher install. So, this UI change completes the story of being able to fully manage NTs and CCs.

**Comment by cjellick** [comment]
related issue https://github.com/rancher/rancher/issues/12186

**Comment by tfiduccia** [comment]
Let add a column in front of the "Created" column that says, # Node Templates.  Then have a number amount underneath.  This way they can easily see how many templates are using them and bulk delete the ones that are 0.

**Comment by sowmyav27** [comment]
**verified on master-head - latest** 
ui tag: `https://releases.rancher.com/ui/latest2/index.html`
Cloud credentials show an additional column - `# Node Templates`
<img width="1176" alt="Screen Shot 2019-10-22 at 1 40 53 AM" src="https://user-images.githubusercontent.com/26032343/67239525-012f4b00-f46d-11e9-8568-78c833a049a0.png">

**Comment by sowmyav27** [comment]
**verified on 2.3-head - latest**
**ui tag: `latest-2.3`**

- Cloud credentials show an additional column - `# Node Templates`

![Screen Shot 2019-10-31 at 1 55 29 AM](https://user-images.githubusercontent.com/26032343/67896104-b3f45d00-fb81-11e9-97ac-f7f198f8a0e2.png)
