### ISSUE TITLE
[UI] Hints of public key import UI page of AKS creation is misleading

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#23073]
1. In Rancher UI, click create cluster.
2. Choose AKS, input credential information as required. Click next.
3. In node options page, scroll down to the button. 
4. The "SSH public key" field has hints information as " paste in the CA certificate. starting with -----BEGIN Certificate------".
5. This hint is incorrect, we just need to paste the ssh public key, which is like:
 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOPt3h9cQPRcL5ekeXHbeLUiznxeotqrBOgfW9uUhHCRt7/inceXhYa4RJcinc9LaeEw2hqBRt7y2LSw0PKp0Yk/6MsEqtuPKZLckJ6akbmdTEpZv6JhoERY9lumPWAeD2LkEJJTraexmSXBKCQWgaoMcgSvsklu9pj3ctitq1QAM9OQtRWwEQhboMiNpCtXVTIifxHfUd+gb3+uFpnBuk67QD2iRohXNHYULhLVQ0ynKyiVH/oBZLT7KgD4KXsO6MWJm081LDQXh3bZeRD12WOOYitcCkXKgEHEx5k9kn8otDzQ6P0mv/fbiChoutY3IlBro+pa6jsUtheKxF4/jf xxx@xxxxx

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.0-rc7` UI: `v2.3.9` |
|Route|`global-admin.clusters.new.launch`|

**Comment by jiaqiluo** [comment]
See the bug in v2.3.0-rc9

<img width="1406" alt="Screen Shot 2019-09-25 at 11 11 20 AM" src="https://user-images.githubusercontent.com/6218999/65627926-3a1af380-df85-11e9-9cef-b8109199290d.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated in rancher:master-head 58e0a2faf

now hint is `Paste in your public SSH key`

<img width="1413" alt="Screen Shot 2019-09-25 at 11 14 51 AM" src="https://user-images.githubusercontent.com/6218999/65628213-dcd37200-df85-11e9-8997-61e366c213da.png">
