### ISSUE TITLE
FATA: Only support with English System Locale

### ISSUE THREAD

**Issue by gmeks** [rancher/rancher#23078]
Rancher version: 2.3.0.0-rc8
I had Rancher 2.3.0.0-rc3/4 was working.

When adding a windows node i get the error message: FATA: Only support with English System Locale . ( Screenshot: https://imgur.com/a/xGXKgcp ) 

First of all its hard to know what this means? (Im work mostly with windows). Is it complaining about Region? Character set? Keybaord layout,TimeZone? Who knows.
Its NOT windows language. Because my windows is in English ( But setup with Norwegian keyboard)

**Comment by gmeks** [comment]
From:
rancher/package/windows/bootstrap.ps1 
Log-Info "Detecting host system locale ..."
`$sysLocale = Get-WinSystemLocale | Select-Object -ExpandProperty "IetfLanguageTag"
if (-not `$sysLocale.StartsWith('en-'))
{
    Log-Fatal "Only support with English System Locale"
}

But i have no idea why this check is done, whats the goal here?

**Comment by thxCode** [comment]
@gmeks For now, a library used by flannel depends on the system locale of Windows: `github.com/rakelkar/gonetsh`, this verification could avoid getting failed when running: like https://github.com/rancher/rancher/issues/22118.

**Comment by thxCode** [comment]
@gmeks https://github.com/rancher/rancher/blob/21be0ba445c273a504ba11468f16a594a4eed456/package/windows/bootstrap.ps1#L188-L191 it's hard to test fully different language system, there is an env variable to skip these checks. You could try to use it to and go ahead :

```
PowerShell -NoLogo -NonInteractive -Command "& {docker run -e WITHOUT_VERIFICATION=true -v c:/:c:/host rancher/rancher-agent:<version> bootstrap --server <server> --token<token> --ca-checksum <ca-checksum> --worker | iex}"
```

If you find everything works fine, especially flannel, please ping me, thanks~

**Comment by gmeks** [comment]
@thxCode 
Before there used to be different versions of windows pr language, but i was unable to find a list.  I did find that there are china spesific versions of windows(Pr the other issue). 
I did try go down the rabit hole of finding out why it would have this requirement, im guessting something is parsing console output?

I left the windows node running a few minutes (Around 10min), and it got itself working

**Comment by thxCode** [comment]
@gmeks, yes, you are right, that repo parses the output from the console. Could you share some screenshots as below:
- run `Get-WinSystemLocale | fl` via PowerShell 
- run `netsh interface ipv4 show addresses` via CMD

**Comment by thxCode** [comment]
@gmeks , I saw your shared screenshot, you have already set the **Region** and the **Region Format**, how about the Language? Have you configured it to your target? 
![image](https://user-images.githubusercontent.com/3394724/65813775-0bfb1500-e20c-11e9-98bf-4ff0006a0e73.png)

**Comment by gmeks** [comment]
>     * Get-WinSystemLocale | fl

https://imgur.com/4mEpLK5

and

https://imgur.com/GlFdNVV

Just to repeat, when i run it without verfication it works fine. I have a working rancher cluster with windows nodes again :) 

Background:
For Norwegian servers i have the normal setup, Region and Region Format set to Norwegian + keyboard. 
The language of the Interface is english.

https://imgur.com/SG3krh1

Is there a somewhere i can check what your reading from console? Perhaps i could make a standalone C# app that outputs in correct format, but does not depend on being on a english OS.

**Comment by sowmyav27** [comment]
**reproduced the issue on `rancher:v2.3.2`.** 

**Steps:**

- Create a custom cluster
- 1 linux node - all roles
- 1 windows node - AMI: `2019 Windows Server (2019 Server) with Chinese (Simplified) Language`
- Run the agent command on the windows node.
- Error is seen.

```
Status: Downloaded newer image for rancher/rancher-agent:v2.3.2
INFO: Detecting running permission ...
INFO: Detecting host CPU reservation ...
INFO: Detecting host RAM reservation ...
INFO: Detecting host DISK reservation ...
INFO: Detecting host system locale ...
FATA: Only support with English System Locale
```

**Comment by sowmyav27** [comment]
**Verified on rancher:v2.3-head - latest - commit id: `1b51a5911`**

**Steps:**

- Create a custom cluster
- 1 linux node - all roles
- 1 windows node - AMI: 2019 Windows Server (2019 Server) with Chinese (Simplified) Language
- Run the agent command on the windows node.
- No error is seen on running the command on windows node.
- The windows node registers successfully.
- Deployed workloads and ingress successfully
