### ISSUE TITLE
Kubelet on different nodes uses different configurations

### ISSUE THREAD

**Issue by wuzhihui1123** [rancher/rancher#23075]
Hello, I have a requirement like this.  I built a k8s cluster with rke, There are many nodes under the cluster. The hardware resources of each node are different, so I want to use different configurations for kubelet on different nodes (eg: some nodes use --kube-reserved=memory=1Gi , some nodes use --kube-reserved=memory=500Mi), but I have searched your documentation and network information and have not seen any relevant information. I would like to ask if the subsequent version provides this feature. Thank you and Thank you for providing such a good open source product.

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/22818

**Comment by dnoland1** [comment]
This may be a duplicate of https://github.com/rancher/rke/issues/1285
