### ISSUE TITLE
Not able to deploy traefik app.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#23070]
Rancher server version - Build from master -`630029df4`

Steps to reproduce the problem:
Change "library" catalog entry to point to "dev" branch.

Deploy "traefik" app (wit default configuration)
App fails to get deployed with following error

```
Failed to install app traefik. Error: release traefik failed: Service "traefik" is invalid: spec.type: Unsupported value: "Loadbalancer": supported values: "ClusterIP", "ExternalName", "LoadBalancer", "NodePort"
```

**Comment by guangbochen** [comment]
This is a typo error of `Loadbalancer `, fixed in the PR https://github.com/rancher/charts/pull/253, @sangeethah can u please test with the upstream `dev` after refreshing it, thanks.

**Comment by sangeethah** [comment]
Tested with latest version of library  catalog from `dev` branch.

Able to deploy "traefik" app successfully and workloads relating to the app get deployed successfully.
