### ISSUE TITLE
[backport v2.2] Sometimes worker nodes are Unavailable for long time on scaling up #22669

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#23081]
backport rancher/rancher#22669

**Comment by daxmc99** [comment]
This may also need @ibuildthecloud's fix from here https://github.com/rancher/rancher/pull/22866

**Comment by rmweir** [comment]
I have a backport for that: https://github.com/rancher/rancher/pull/23159

First we were trying to reproduce the issue on 2.2 which was not happening

**Comment by cjellick** [comment]
There might be a little difficult in reproducing the exact failure scenarios, but Ricky has some ideas for what to look for and I think the main thing is just regression testing, as this is basically a logic change to avoid an infinite loop

**Comment by rmweir** [comment]
In 2.2 it appears that the "generate" count usually has a value of 1. resourceVersion is also an measure of object writes. It would probably be a good indicator if the average resourceVersion is lower after the fix. It appeared to be when I tested it. I would also look for spikes. Prior to fix you may have a worker node that takes longer than the others to become available- that node would have a much higher resourceVersion than the rest. You could scale a few times on the old version to validate that this happens, and scale a few times on the new one and observe whether this happens. Ultimately, the node taking longer to become available are what we are concerned with. If we could show that these spikes definitely occur in prior version and we cannot repro in new version- that would be ideal.

**Comment by sowmyav27** [comment]
**Verified on 2.2-head - latest - `1375ef26`**
**Steps:**

- Deploy and rke AWS cluster with 3 nodes - 1 etcd, 1 control plane and 1 worker node.
- The worker node is initially in Unavailable state - with the Runtime error on the UI.
- But it comes to Active quickly, less than a minute.
- Verified by scaling up the worker nodes also. (to 6 worker node in total, but gradual scale up)
- The nodes come up to Active state quickly. 

On 2.2.8, the `resourceVersion` number showed spikes as expected on scaling up the worker nodes.
```
kubectl get nodes.management.cattle.io -n c-js4gq -o yaml | grep "resourceVersion"
    resourceVersion: "4908"
    resourceVersion: "6426"
    resourceVersion: "4923"
    resourceVersion: "2650"
    resourceVersion: "2583"
    resourceVersion: "5493"
    resourceVersion: "6698"
    resourceVersion: "2582"
  resourceVersion: ""

```
On v2.2-head, the spike was not see
```
kubectl get nodes.management.cattle.io -n c-h9kzp -o yaml | grep "resourceVersion"
    resourceVersion: "2132"
    resourceVersion: "2188"
    resourceVersion: "4044"
    resourceVersion: "5026"
    resourceVersion: "2131"
    resourceVersion: "3513"
    resourceVersion: "3548"
    resourceVersion: "5027"
  resourceVersion: ""
```
