### ISSUE TITLE
Enable apparmor on Rancher (apparmor_parser missing)

### ISSUE THREAD

**Issue by degerrit** [rancher/rancher#23082]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

Following up on an issue I created in the forum (https://forums.rancher.com/t/apparmor-and-rancher-2-x/12763) and related to closed v1.6 issue https://github.com/rancher/rancher/issues/6317

It seems Apparmor is not working on Rancher 2, but surprisingly appears fairly trivial to enable : if /sbin/apparmor_parser exists on the host where the kubelet is running, then **bind it into the kubelet container**.

This was our previous sleuthing on Rancher 1.x, but it applies equally to Rancher 2.x:
* We have AppArmor enabled and working on the host OS, etc.
* AppArmor Feature gate is not explicitly disabled, so we have to assume it’s enabled
* Neither kube-apiserver nor kubelet logs show anything related to AppArmor being disabled (https://github.com/rancher/kubernetes/blob/v1.11.3-rancher/pkg/security/apparmor/validate.go has some nice errors, not sure if they would be logged though)
* We noticed that /sys/kernel/security/ is properly mounted in the kubelet containers on our workers
* The binary /sbin/apparmor_parser is not present in the kubelet, although it appears that func [IsAppArmorEnabled()](https://github.com/kubernetes/kubernetes/blob/master/pkg/security/apparmor/validate.go#L222) requires it to be!
* AppArmor on a newly deployed /non-Rancher/ k8s cluster works

Following up on this I copied `/sbin/apparmor_parser` (x86-64 binary) into the kubelet container ```docker cp `which apparmor_parser` kubelet:/sbin/apparmor_parser``` on a worker node, and then ran `docker restart kubelet`. Suddenly, AppArmor shows now as enabled, whereas previously it was not!

```
$ kubectl get nodes -o=jsonpath=$'{range .items[*]}{@.metadata.name}: {.status.conditions[?(@.reason=="KubeletReady")].message}\n{end}'
s10: kubelet is posting ready status
s20: kubelet is posting ready status
s30: kubelet is posting ready status. AppArmor enabled
```
Further testing (loading an apparmor profile on the worker node(s), and adding the necessary apparmor annotation in a deployment (spec: template: metadata: annotations:) indicates that **with the apparmor_parser binary in place, AppArmor now works as intended** in the Kubernetes docs! - https://kubernetes.io/docs/tutorials/clusters/apparmor/

**Environment information**
I tested AppArmor on a cluster deployed using rke v0.2.2 - rancher (k8s v1.13.5 / ubuntu 16.04lts

- Docker version (use `docker version`):
```
Client: Docker Engine - Community
 Version:           19.03.0
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.5
 Git commit:        aeac949
 Built:             Wed Jul 17 18:16:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

So the obvious question: can Rancher do this out-of-the-box?

**Comment by xanderificnl** [comment]
Walked right into this one as well when I tried to deploy cert-manager.

I edited cluster.yml as follows:
```
services:
  kubelet:
    extra_binds:
      - "/sbin/apparmor_parser:/sbin/apparmor_parser"
```
I'm not entirely sure if this is the best way. Please advise.

**Comment by fabiorauber** [comment]
Still needed.

**Comment by fluktuid** [comment]
still needed

**Comment by chfrank-cgn** [comment]
Still occuring on SLES
