### ISSUE TITLE
k8s version 1.12 is shown is 'not allowed by template' on the UI when rancher is upgraded from 2.2.8 to 2.3.0-rc9

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23085]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy an rke cluster in k8s v1.12.10 in rancher:v2.2.8
- Upgrade rancher to v2.3.0-rc9
- Edit the cluster
- In the kubernetes version dropdown, user will see `v1.12.10-rancher1-2 (not allowed by template)`. 

<img width="830" alt="Screen Shot 2019-09-24 at 9 08 11 PM" src="https://user-images.githubusercontent.com/26032343/65628405-3cca1880-df86-11e9-8c65-876955352739.png">

**Expected Result:**
A better text message can be shown for the unsupported k8s version.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): upgrade from 2.2.8 to 2.3.0-rc9
- Installation option (single install/HA): single/HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO/AWS
- Kubernetes version (use `kubectl version`):

```
1.12.10
```

**Comment by westlywright** [comment]
Available to test on master.

**Comment by sowmyav27** [comment]
**Verified with latest `master-head`**

**Steps:**

- Deploy an rke cluster in k8s v1.12.10 in rancher:v2.2.8
- Upgrade rancher to v2.3.0-rc9
- Edit the cluster
- k8s v1.12 is seen as `Unsupported`

<img width="769" alt="Screen Shot 2019-09-26 at 9 50 04 AM" src="https://user-images.githubusercontent.com/26032343/65708316-27ff8a80-e043-11e9-9de5-f0e563e05f5a.png">
