### ISSUE TITLE
Rebalancing service containers across hosts

### ISSUE THREAD

**Issue by umesh2409** [rancher/rancher#23095]
*Describe your issue here*

The Rebalancing service containers across hosts is not happening in the rancher (V 1.6.21).
I have stopped all the services before adding 2 more hosts to the environment and made all their services up but the services are running only from the first host, it supposes to run from all the hosts(load balancing).

Is there any configuration needed for this? 
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.21` Cattle: `v0.183.60` UI: `v1.6.45` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by superseb** [comment]
There are scheduling examples to spread the containers as much as possible here: https://rancher.com/docs/rancher/v1.6/en/cattle/scheduling/#examples

See https://github.com/rancher/rancher/issues/2558#issuecomment-382673071 for an actual rebalancing feature.
