### ISSUE TITLE
Rancher single move to another host possible ?

### ISSUE THREAD

**Issue by ds2k5** [rancher/rancher#23091]
Hello,
is it possible to move a Rancher 2.2.4 installation to another host with rancher stable 2.2.8 ?

old_host:

cd /tmp
docker stop rancher-server
docker run  --volumes-from rancher-server -v $PWD:/backup busybox tar zcvf /backup/rancher-data-backup.tar.gz /var/lib/rancher
tar cf - /var/lib/docker/volumes/rancher-server-data | gzip -9 > /tmp/rancher-volume.tar.gz
docker start rancher-server

new_host:

docker run -d -v rancher-server-data:/var/lib/rancher -v rancher-server-log:/var/log/auditlog  --restart=unless-stopped -p 80:80 -p 443:443 --name ranger-server rancher/rancher:stable
docker run busybox

wait 3 minutes

docker stop rancher-server
rm /var/lib/rancher/*
cd /
tar xvfz rancher-data-backup.tar.gz
tar xvfz rancher-volume.tar.gz
docker start rancher-server

wait 1 minute

docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.2.8 --server https://new_host.domain.tld --token b.....r --ca-checksum 6....3 --etcd --controlplane --worker

Stop Agents and connect it to the new host ?

Thanks

**Comment by superseb** [comment]
Backup and restore for single install is described on https://rancher.com/docs/rancher/v2.x/en/backups/, if you are changing the server-url where Rancher is accessible you will run into https://github.com/rancher/rancher/issues/14731 but there is a workaround mentioned.

Did you try the steps and are you running into anything? Can you provide logs of what is not working?
