### ISSUE TITLE
Configure AD login authentication

### ISSUE THREAD

**Issue by ziyou987** [rancher/rancher#23093]
*Describe your issue here*
	
dear all:
I configure AD login authentication
appear ： authentication failed
help me 
thx
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.8` UI: `v2.2.94` |
|Route|`global-admin.security.roles.index`|

**Comment by mrajashree** [comment]
Please include details of your setup, such as the Rancher server version, single node/HA, and the exact error you got from AD while configuring auth
