### ISSUE TITLE
API returns "404 - Not Found" error when trying to fetch container logs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2310]
Server version - Build from master on Oct 10.

Following test cases which validates container logs fails with "404 - Not Found" error when trying to fetch container logs.
Manually when I try to fetch the logs of the container , I am able to get the container logs:

_______________________________ test_native_logs _______________________________

client = <cattle.Client object at 0x7f358a832c50>, socat_containers = None
native_name = 'native-test-728364', pull_images = None

```
def test_native_logs(client, socat_containers, native_name, pull_images):
    docker_client = get_docker_client(host(client))
    test_msg = 'LOGS_WORK'
    docker_container = docker_client. \
        create_container(NATIVE_TEST_IMAGE,
                         name=native_name,
                         tty=True,
                         stdin_open=True,
                         detach=True,
                         command=['/bin/bash', '-c', 'echo ' + test_msg])
    rancher_container, _ = start_and_wait(client, docker_container,
                                          docker_client,
                                          native_name)
```

> ```
>   found_msg = search_logs(rancher_container, test_msg)
> ```

cattlevalidationtest/core/test_native_docker.py:223: 

---

cattlevalidationtest/core/test_native_docker.py:280: in search_logs
    logs = container.logs()
.tox/py27/local/lib/python2.7/site-packages/gdapi.py:233: in <lambda>
    _args, *_kw)
.tox/py27/local/lib/python2.7/site-packages/gdapi.py:399: in action
    return self._post(url, data=self._to_dict(_args, *_kw))
.tox/py27/local/lib/python2.7/site-packages/gdapi.py:62: in wrapped
    return fn(_args, *_kw)
.tox/py27/local/lib/python2.7/site-packages/gdapi.py:273: in _post
    self._error(r.text)

---

self = <cattle.Client object at 0x7f358a832c50>
text = '{"id":"db6259a2-6bbf-4c2a-af01-cdcbd3dfa74c","type":"error","links":{},"actions":{},"status":404,"code":"Not Found","message":"Not Found","detail":null}'

```
def _error(self, text):
```

> ```
>   raise ApiError(self._unmarshall(text))
> ```
> 
> E       ApiError: (ApiError(...), "Not Found : Not Found\n{'id': u'db6259a2-6bbf-4c2a-af01-cdcbd3dfa74c', 'actions': {}, 'type': u'error', 'status': 404, 'links': {}, 'code': u'Not Found', 'message': u'Not Found', 'detail': None}")

**Comment by sangeethah** [comment]
This issue happened again with runs on Oct 15

**Comment by sangeethah** [comment]
This issue happened again with runs on Oct 27 and oct 28.

**Comment by soumyalj** [comment]
Found this issue again in v1.1.0-dev4-rc1.
