### ISSUE TITLE
Hide Istio VirtualServices and DestinationRules in Rancher UI

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#23108]
[ ] - Remove the Destination Rule/Virtual Services Tabs (The UI workflow is confusing as most Istio docs talk about yamls)

<img width="1378" alt="Screen Shot 2019-09-26 at 2 26 08 PM" src="https://user-images.githubusercontent.com/1989084/65726318-a8d17d00-e069-11e9-996e-a05ea47982ba.png">

[ ] - Add Heading on Istio page similar to Pipelines heading. Instead of Configure Repositories button, it should be a "Import Yaml" button that pops open the modal that was in the destination rule/virtual services tab. 

[ ] - Add a "Istio" and underline bar similar to the way pipelines work.

<img width="1301" alt="Screen Shot 2019-09-26 at 2 26 23 PM" src="https://user-images.githubusercontent.com/1989084/65726335-b25ae500-e069-11e9-95d2-a9d33c07af1c.png">

**Comment by westlywright** [comment]
The proposed design doesn't fit without our current design patterns. I had some discussion with @tfiduccia offline and we found an alternative that I think still satisfies the original requirements aim to simplify the ux. 

UI will drop the `Destination Rules` & `Virtual Services` tabs from the nav.
UI will add `Import Yaml` button on the right side of tab nav, to the right of the external link icons. It will be available on both tabs.
UI will prepend `Istio` to both nav tab texts to add some indication of what resource you're viewing rather then use an additional header above the tabbed nav (this is the anti pattern and is typically accomplished the way we do things like global dns or the old cluster launcher view).

**Comment by westlywright** [comment]
See design below: 


<img width="1418" alt="Screenshot 2019-09-26 16 38 22" src="https://user-images.githubusercontent.com/858614/65731805-15ee0e00-e07c-11e9-969f-86212dc72bf6.png">

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 21be0ba44

* Destination Rules & Virtual Services tabs are removed
* Traffic Metrics & Graph are prepended with Istio
* Import YAML button is present and functional
* Created workloads & destination rules & virtual services via Import YAML
* Traffic Metrics are functional
* Traffic Graph is functional
* Links to external tools are functional
