### ISSUE TITLE
When adding port mapping to workload, the auto-generated service discovery record is incompatible with Istio

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23105]
rancher/rancher:master-head 58e0a2faf

* Deploy Rancher
* Create a cluster
* Enable Istio
* Create a project / ns and enable istio ns auto injection
* In the created project, create a workload with a port mapping

![Screen Shot 2019-09-26 at 1.17.55 PM.png](https://zube.io/files/rancher/e9b22db1118237f3461a2b109f0e9dd2-screen-shot-2019-09-26-at-1-17-55-pm.png)

* View the created service discover record in Rancher UI (advanced options in view/edit service discovery record) and note the name of the port mapping specified in the workload creation
  * For a workload with port 8080 mapped to a NodePort, the service discovery port mapping name is `8080tcp1`

![Screen Shot 2019-09-26 at 1.19.29 PM.png](https://zube.io/files/rancher/cedc6f877bd622cd4f881f7153e76e45-screen-shot-2019-09-26-at-1-19-29-pm.png)

* Access Kiali and view the service created
  * Kiali shows an error that the port name is in an invalid format
* Editing the port mapping name in the Service Discovery record clears the error

![Screen Shot 2019-09-26 at 1.03.32 PM.png](https://zube.io/files/rancher/69108456abdbbf288721b5a72f39f22e-screen-shot-2019-09-26-at-1-03-32-pm.png)
![Screen Shot 2019-09-26 at 1.03.40 PM.png](https://zube.io/files/rancher/011c0eff10c7ce3ef85e3745349f552c-screen-shot-2019-09-26-at-1-03-40-pm.png)

**Comment by cloudnautique** [comment]
I think if we allow the user to specify a `name` here it would address the issue. This is how service discovery does it.

**Comment by alena1108** [comment]
@cloudnautique API support for port.name is already in; you can pass it optionally. So it's just a matter of exposing it in the UI.

**Comment by westlywright** [comment]
UI is available in master

**Comment by bmdepesa** [comment]
rancher/rancher:master-head a9241c072

* Create a cluster
* Enable Istio
* Create a workload
  * Create a port mapping and include a name in the correct format
* Workload is created
* SD record is created with the specified name
* Kiali shows the service is configured correctly

* If a name for the port is not included, the name will be auto-generated in the same manner as previously done -- we may want to call this out in Istio docs?
