### ISSUE TITLE
Rancher does not allow addition of cluster "Read Only" users in 2.2.8

### ISSUE THREAD

**Issue by mikhail-arundo** [rancher/rancher#23112]
I have a bunch of AKS clusters in Rancher 2.2.8.

I am unable to add read-only users, or github groups to those clusters. i am able to add members.

https://screencast.com/t/3qvCpABOKFv

This effects both the imported and the instantiated with rancher ones.

type: Bug

Go into the UI, Select the cluster,  click update on the cluster, add a group in the drop down and select read only as the access from the other drop down. Click save.

Not sure where the dropdown of admin options comes form but it seems to be incomplete.

https://screencast.com/t/DbpKk5tl

It results in: Validation failed in API: Cannot edit context [project] from [cluster] context

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/23061
