### ISSUE TITLE
Backport: Catalog apps should not re-use existing image and tag if the version is upgraded

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#23115]
Backport https://github.com/rancher/rancher/issues/22265

**Comment by westlywright** [comment]
Available in UI version `2.2.95` when the new rc is released

**Comment by sowmyav27** [comment]
**Reproduced the issue on `v2.2.8`**

**Steps:**

- Have an rke cluster deployed - 1 Node - DO cluster.
- Deploy `drone` app - template version : `1.4.0` Workload with Image: `docker.io/drone/agent:0.8.5` gets deployed
- Upgrade the app deployed to template version `1.7.4`. Workload gets updated, but the image is still seen as `docker.io/drone/agent:0.8.5 

**Validated on `2.2-head` - latest with UI Tag: `2.2.96`**
**Steps:**

- Have an rke cluster deployed - 1 Node - DO cluster.
- Deploy `drone` app - template version : `1.4.0` Workload with Image: `docker.io/drone/agent:0.8.5` gets deployed
- Upgrade the app deployed to template version `1.7.4`. Workload gets updated, but the image is still seen as `docker.io/drone/agent:0.8.6`
