### ISSUE TITLE
Project Monitoring Apps don't get created

### ISSUE THREAD

**Issue by Crokoking** [rancher/rancher#23120]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1) Activate cluster monitoring
2) Activate project monitoring on a project

**Result:**
Cluster monitoring creates the necessary apps and pods. 
Project monitoring claims it is activated but no apps or workloads are being created

**Other details that may be helpful:**
The cluster has been created with rancher 2.0 and upgraded over time. 
We have attempted activating project monitoring since 2.2.4 with the same result.
The rancher log shows no attempt at creating the app.

**Environment information**
Rancher 2.2.8 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): GKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMs with 2 vCPU and 7.5GB RAM
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version:
```
Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.10.3
 Git commit:   f5ec1e2
 Built:        Tue Jun 18 23:09:23 2019
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by loganhz** [comment]
Please check the log in prometheus operator

**Comment by Crokoking** [comment]
The prometheus-operator-monitoring-operator logs seem to only contain
```
level=info ts=2019-09-29T03:53:11.678833148Z caller=operator.go:970 component=prometheusoperator msg="sync prometheus" key=cattle-prometheus/cluster-monitoring
```
No changes when turning project monitoring on or off.
