### ISSUE TITLE
Browser freezes when viewing HPA

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#23127]
This is in a fresh install of 2.3.0-rc9
- EC2 nodes
- standalone rancher server container
- cluster installed with custom - one cp/etcd, 4 workers
- ubuntu 18.04
- docker 18.09.latest, installed by our script

Steps to reproduce:
- create HPA
- from the HPA screen, select it
- browser will sometimes (often) hang

I was able to sometimes view the HPA in the Default project, but I was never able to view the Istio HPAs in the System project.

If I refresh the page, it fails. If I hard refresh the page, it fails. If I click back, it will take me to the previous page (listing all the HPAs), but sometimes the top nav is missing. Another time the hamburger menu didn't open when clicked.

Video showing issue with console output from browser is at https://www.dropbox.com/s/kgp2g3m7m0zym6h/hpa-wonk.mp4?dl=0.

**Comment by tfiduccia** [comment]
Version - master 9/30
this is throwing a bunch of errors in the console:
![image](https://user-images.githubusercontent.com/11514927/65924911-99bd3880-e3a3-11e9-9ec2-79edaaa17fca.png)

**Comment by soumyalj** [comment]
Reproduced the issue with v2.3.0-rc9
Create a HPA 
Click on the HPA and browser hangs

![Screen Shot 2019-10-01 at 11 04 49 AM](https://user-images.githubusercontent.com/18536626/65987759-53b3b380-e43b-11e9-82dd-62e3de347d60.png)

Tested with master-head build from Oct 1
Create a HPA in default/system project
Click on the HPA. After clicking we can view the HPA details with no blurry screen. 
There is no browser freeze
