### ISSUE TITLE
Unable to use private registry with wildcard SSL cert

### ISSUE THREAD

**Issue by brightcommerce** [rancher/rancher#2312]
I am having issues trying to get rancher to authenticate against a private registry sitting behind an nginx proxy secured using a commercial Wildcard PositiveSSL certificate from Comodo CA. The certificate chain has been concatenated into a single file. I have no issues with accessing servers secured with this certificate. I am running 1 management node, 1 private registry node and 1 web host. Nginx is used as a reverse proxy and SSL terminator for both the Rancher UI and the private registry. I can successfully push and pull to the registry using docker login with the credentials I created when adding the registry. When I try to deploy a container using an test image I have in the private registry I get a `failed to pull : Authentication is required` error. After a few moments the container is cleaned up and disappears. I do not have an option to select a registry from a dropdown when specifying the image for the container and have to type the registry-name/image-name instead. I am running `CATTLE_RANCHER_SERVER_IMAGE=v0.40.0` and `DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/0.54.0`. I have read issues #1020 and #1059. I am hoping this can be resolved and that spinning up hosts and containers can be fully automated including any SSL steps as our platform requires full autonomy as it's extremely dynamic.

**Comment by deniseschannon** [comment]
When launching the service, are you using the syntax `[registry-name]/[namespace]/[imagename]:[version]` in the image? That is the required syntax for image names in the UI. It would be the same image name that you use in a `docker run` command. 

http://docs.rancher.com/rancher/configuration/registries/#using-registries

**Comment by brightcommerce** [comment]
I have resolved the issue by starting again and following the instructions at https://github.com/docker/distribution/blob/master/docs/deploying.md and https://github.com/docker/distribution/blob/master/docs/nginx.md. I also installed docker-compose on the host and created a `docker-compose.yml` with help from https://docs.docker.com/compose/yml. I had to copy CA certificate to /etc/docker/certs.d/<mydomain>/ca.crt also. I am now able to build, tag, push and pull images to/from the secure private repo. Deploying a container with an image from the private works works beautifully.

Thanks for your assistance.
