### ISSUE TITLE
Disabled template revisions are displayed as revisions available for upgrade

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#23126]
Version: master-head

Steps:

1. Create a cluster template T1 and revisions V1, V2, V3
2. Create a cluster using T1/V1
3. Once cluster is created, V3 is displayed as  a revision available for upgrade
4. Disable R3.
V3 continues to be displayed as a revision available for upgrade though it is disabled.

![Screen Shot 2019-09-27 at 11 00 23 AM](https://user-images.githubusercontent.com/18536626/65791179-0d4a1600-e116-11e9-9fc7-784acfbef181.png)
![Screen Shot 2019-09-27 at 11 00 32 AM](https://user-images.githubusercontent.com/18536626/65791187-10450680-e116-11e9-9a25-4b5f7da2d03a.png)

Disabled versions should not be displayed for upgrade available notification . [While editing clusters, disabled templates are anyways not displayed for selection]

Edit cluster screen below:

![Screen Shot 2019-09-27 at 11 02 26 AM](https://user-images.githubusercontent.com/18536626/65791329-526e4800-e116-11e9-8692-79fccd3cf31f.png)

**Comment by soumyalj** [comment]
Tested with build from master-head(599faa8da80c)
1. Create a cluster template T1 and revisions V1, V2, V3
2. Create a cluster using T1/V1
3. Once cluster is created, V3 is displayed as a revision available for upgrade
Disable R3.
V3 is NOT displayed as a revision available for upgrade since its disabled. 
But this can be seen only after a page refresh. 
It should reflect without a page refresh.

**Comment by westlywright** [comment]
Available in master.

**Comment by soumyalj** [comment]
Tested with build from master-head(599faa8da80c)

Create a cluster template T1 and revisions V1, V2, V3
Create a cluster using T1/V1
Once cluster is created, V3 is displayed as a revision available for upgrade
Disable V3.
V3 is NOT displayed as a revision available for upgrade since its disabled. 
Enable V3. V3 is displayed as a revision available for upgrade as expected. 
Page refresh is not required.
