### ISSUE TITLE
 "Upgrade available" icon for clusters should not be displayed for cluster members, project members and project owners 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#23128]
Version: Master-head

Steps:
1. Create a RKE template/revision T1/R1 as an admin
2. Create users, user1, user2, user3 
3. Create a cluster using T1/R1 and add user1 as a member to the cluster 
4. Provide template T1 "user" access to "user1"

Login as user1 who is a member

In the main page (global level), "Upgrade available" icon is displayed for the cluster (for user1 who is a member)
It is also displayed in the cluster dashboard page

The same is true for project member and project owners who have "user" access to the cluster template. 
Cluster members, project members, project owners cannot edit the cluster and upgrade their templates. "Upgrade Available" icon should not be displayed for these users
![Screen Shot 2019-09-27 at 12 56 28 PM](https://user-images.githubusercontent.com/18536626/65798352-3ecadd80-e126-11e9-8d8d-c89804263a00.png)

**Comment by codyrancher** [comment]
I personally don't think this is a bug but I can see it go either way. I think it's still actionable information for the user. The user could ping the admin to get the cluster updated. 

@tfiduccia do you have any thoughts on this one?

**Comment by tfiduccia** [comment]
@soumyalj & @codyrancher - We have the same kind of option for Catalog Apps.  What do we do there?  Do we hide the upgrade?

**Comment by codyrancher** [comment]
@tfiduccia @soumyalj I just verified the catalog apps show the upgrade notification even if the user doesn't have permission to perform the upgrade.

**Comment by tfiduccia** [comment]
@codyrancher @soumyalj - Then I say we should just leave it displaying.

**Comment by soumyalj** [comment]
Verified that catalog apps do show upgrade notifications for cluster members, project members. 
We want to uniformly maintain the pattern across different objects.
