### ISSUE TITLE
Add VirtualServices and DestinationRules UI support feature flag

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23137]
The UI support is hidden in https://github.com/rancher/rancher/issues/23108

Instead of removing it, we can use feature flag to turn it off. Users can turn it on if they want

**Comment by westlywright** [comment]
Available in master.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 343a56707

* Deploy Rancher w/ no feature flag settings
* Check v3/features
  * `istio-virtual-service-ui` is `False` by default
* Deploy Cluster
* Enable Istio
* Virtual Services & Destination Rules tabs are hidden
* Edit v3/features to enable `istio-virtual-service-ui` flag
* Virtual Services & Destination Rules tabs are shown / functional

* Deploy Rancher w/ the feature flag enabled:
```
docker run -d -p 80:80 -p 443:443 -e CATTLE_FEATURES="istio-virtual-service-ui=true" --restart=unless-stopped rancher/rancher:master-head
# or 
docker run -d -p 80:80 -p 443:443 --restart=unless-stopped rancher/rancher:master-head --features="istio-virtual-service-ui=true"
```
* The feature flag is set to true by default

**Comment by bmdepesa** [comment]
Small related UI issue: https://github.com/rancher/rancher/issues/23155
