### ISSUE TITLE
Can not access application from Rancher UI

### ISSUE THREAD

**Issue by taibc** [rancher/rancher#23139]
I have a question: Please see my nodes, why they show two ip addresses ? And I can't access my application (workload), because it link to the first IP (192.168.94.146), but actual ip is the second IP (192.168.94.148), so I must change IP address in the url, after that I can access the application 

How can I fix this ?
![error1](https://user-images.githubusercontent.com/37021673/65814456-16b5aa00-e20c-11e9-9292-3311028964bb.png)
![error2](https://user-images.githubusercontent.com/37021673/65814458-21703f00-e20c-11e9-9ef3-1273b668faa4.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.7` UI: `v2.2.93` |
|Route|`authenticated.cluster.nodes.index`|

**Comment by tfiduccia** [comment]
@taibc - Why type of Cluster is this?  Is it a custom cluster and did you run the command twice?

**Comment by taibc** [comment]
> @taibc - Why type of Cluster is this? Is it a custom cluster and did you run the command twice?

@tfiduccia : Yes, It is a custom cluster. I don't remember how many times I run the join command. Maybe I run once and it doesn't show on the cluster then I run again, but I am not sure .

Is it a rancher error ?

**Comment by tfiduccia** [comment]
@taibc - I have not been able to reproduce it.  Even by running the command a couple of times.  Have you tried just deleting the node that isn't supposed to be there?

**Comment by taibc** [comment]
> @taibc - I have not been able to reproduce it. Even by running the command a couple of times. Have you tried just deleting the node that isn't supposed to be there?

Yes, I tried to delete nodes and add them again to the cluster. But some case after delete/clean nodes, the cluster status is not ready, so I must delete my cluster :(
