### ISSUE TITLE
2.2: add regions to eks

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#23150]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. create an eks cluster

**Result:**
1. 'ap-east-1' and 'me-south-1' are missing

**Comment by westlywright** [comment]
Available in UI tag `2.2.96`

**Comment by jiaqiluo** [comment]
Validated in Rancher:v2.2-head with UI v2.2.96

See the EKS regions `ap-east-1` and `me-south-1` in the droplist when creating a new EKS cluster.

<img width="402" alt="Screen Shot 2019-09-30 at 3 02 32 PM" src="https://user-images.githubusercontent.com/6218999/65920326-90c46b00-e393-11e9-9767-20fb7a17a7c1.png">

**Comment by jiaqiluo** [comment]
Failed to provision an EKS cluster in the region `me-south-1` 

```
Error parsing state: rancher does not support region me-south-1, no entry for ami lookup
```

<img width="1421" alt="Screen Shot 2019-09-30 at 4 22 32 PM" src="https://user-images.githubusercontent.com/6218999/65924082-07676580-e3a0-11e9-8bda-3d4be4405a2f.png">

**Comment by deniseschannon** [comment]
@rmweir did these regions get added into the backend for 2.2?

**Comment by jiaqiluo** [comment]
https://github.com/rancher/rancher/issues/23189
