### ISSUE TITLE
Automate EKS AMIs

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#23153]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**What:**
Currently, eks AMIs in kontainer-engine have to be updated manually. This can be an error-prone process that's a good candidate for automation. Also, the AMI's are updated often, causing rancher to be outdated until someone is able to make a PR.

**Desired:**
A process for automatically pulling AMIs, possible requiring some manual review.

**Comment by dkeightley** [comment]
Is this a duplicate of https://github.com/rancher/rancher/issues/23700?
