### ISSUE TITLE
Import YAML button duplicated in Virtual Services & Destination Rules tabs for Istio after virtual services UI feature flag enabled

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23155]
rancher/rancher:master-head 343a56707

* Deploy Rancher
* Create a cluster
* Enable Istio
* Enable the virtual services ui feature flag
* Navigate to Istio - Virtual Services or Destination Rules
* The Import YAML button is displayed twice

![Screen Shot 2019-09-30 at 11.02.55 AM.png](https://zube.io/files/rancher/3252d7733809b43f1f6b7f240f9fb55f-screen-shot-2019-09-30-at-11-02-55-am.png)

**Comment by westlywright** [comment]
Available in master

**Comment by bmdepesa** [comment]
rancher/rancher:master-head de4448e87

The duplicate button is removed from the Virtual Services and Destination Rules pages.
