### ISSUE TITLE
vmwarevsphere Validation Tests

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#23157]
Create validation tests for the vmwarevsphere driver using the python libraries. Tests will be considered passing if a cloudcredential and nodepool are made and a cluster in a given vsphere server is created and functioning.

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/23877

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/23918

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/23927

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head

* Tests from validation PR executed - no failures
* Validation test PR merged
