### ISSUE TITLE
Ability for  containers/service links to leave a service similar to being able to join a service using selectorContainer/selectorService.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2316]
Server version - v0.41.0-rc1

We have the ability to join containers/ add service links to a service by specifying selectorContainer/selectorService.
Since we do not have the ability to edit a container/service label , once containers get added / service links get added to a service , there is no way them to be delinked from the service.

It would be useful to have a way to delink the containers/service links from a service similar to having the ability to join the service.

**Comment by alena1108** [comment]
@sangeethah for service link, you can remove it using removeServiceLink API, just the way you would do for a regular link.

For container that joined the service using selector, currently there is no way to leave the service, this is correct. Could you change bug description so it reflects only selectorContainer use case?

**Comment by alena1108** [comment]
This bug should be fixed with this https://github.com/rancher/rancher/issues/2321. So closing as a duplicate.
