### ISSUE TITLE
Make jailer script timeout configurable (or at least increased)

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#23160]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Steps to reproduce (least amount of steps as possible):**

When a customer is running Anti-virus software on their Rancher nodes, the jailer script can take take more than it's hard-coded 10second timeout to complete, and the Rancher container therefore fails to start (per https://github.com/rancher/rancher/issues/22379). The user would therefore like the jailer timeout to be configurable, or at least increased above 10 seconds.

**Environment information**
- Rancher v2.2.8

**Comment by fizzyduck** [comment]
I'm also seeing this on Rancher v2.3.0-rc9 on hardware which is not running AV software but is otherwise heavily loaded.

**Comment by dramich** [comment]
After some internal discussion this is going to be turned into a setting with a default of 60 seconds. We feel the 60 seconds will cover the majority of issues users are running into while also allowing operators to configure it with the understanding there could be other system impacts by doing so.

**Comment by sangeethah** [comment]
Tested with 2.3-head - c45ec3648

Currently the default setting for jailer-timeout is 60 seconds.

To simulate the jailer scripts failing to complete before timeout , did the following steps:
In the jailer script (/usr/bin/jailer.sh) , induce a sleep of 15 sec.

Set jailer-timeout to 10 seconds ( < sleep set in jailer script).

Create a cluster with DO node driver.
Node provisioning fails with following error message that states the reason:

Following are the error message seen when jailer script fails to complete before timeout:

2019/10/11 23:48:26 [ERROR] NodeController c-ff8nn/m-dmf2n [node-controller] failed with : node create jail error: error running the jail command: timed out waiting for the script to complete: signal: killed

Set jailer-timeout to 20 seconds ( > sleep set in jailer script)

Try to Provision a new node. Provisioning of new node succeeds as expected.

**Comment by fizzyduck** [comment]
Out of interest, is the test automated?

**Comment by bmdepesa** [comment]
@fizzyduck this test is not automated
