### ISSUE TITLE
Support Windows 1809 and 1903 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#23163]
Currently, 2.3 is shipping with Windows 1903 support, but we need to introduce the ability to support both 1809 and 1903

**Comment by sowmyav27** [comment]
Verified the following scenarios

- **On 2.3.0-rc11 - Deployed a Windows cluster - 1903**
```
- k8s v 1.15
- cluster spec: 1 Linux master node, 1 Linux worker node, 2 windows worker node. - AWS nodes
- Basic cases including workload deployment, node port, dns resolution, cross namespace ping on workload - worked
```
- **Verified Windows 1809 - on `master-head` - (Oct 2nd)**
```
- k8s version - 1.15.4
- docker version:  18.9.9
- CLuster spec: 1 master node and 1 worker node - linux; WIndows: 2 worker nodes
- Test case verified:
- LB
- Workload deployment - deployment, demonset, nodeport, exec shell, view logs
- kubectl launch works
- Storage class and PV
- DNS resolution works, across namespace also
```

**Comment by rgl** [comment]
@sowmyav27 how did you launch "2.3.0-rc11 - Deployed a Windows cluster - 1903"? are you using the rancher UI to launch the cluster?

I'm scratching my head at https://github.com/rancher/rke/issues/1683 because I do not see a way to rke up a cluster with windows. Can you help me?

**Comment by sowmyav27** [comment]
@rgl 
Yes this https://github.com/rancher/rancher/issues/23163#issuecomment-539140257 verification was done from the Rancher UI.

**Comment by rgl** [comment]
@sowmyav27 thank you!

Sorry to nag you, but can you look at https://github.com/rancher/rke/issues/1683? Essentially, I'm stuck getting `rke up` working with a windows node. You known if there's documentation about this?

**Comment by suvl** [comment]
It is now 2021 and still no CLI support for windows nodes?
