### ISSUE TITLE
[Windows] k8s.gcr.io/pause:3.1\": no matching manifest for windows/amd64 10.0.18362 in the manifest list entries

### ISSUE THREAD

**Issue by stayfrostnl** [rancher/rancher#23161]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
With 2.3.0-rc9 joining a Windows worker node to a 5 node Linux cluster.

**Result:**
Joining will work, but no workloads are scheduled. The kubelet on the node gives the following logs:

E1001 14:29:03.759095    8072 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed pulling image "k8s.gcr.io/pause:3.1": no matching manifest for windows/amd64 10.0.18362 in the manifest list entries
E1001 14:29:03.759095    8072 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "exporter-node-windows-cluster-monitoring-ts5zq_cattle-prometheus(9fb6560f-6778-4f34-b9bf-ebe37ea4d94f)" failed: rpc error: code = Unknown desc = failed pulling image "k8s.gcr.io/pause:3.1": no matching manifest for windows/amd64 10.0.18362 in the manifest list entries
E1001 14:29:03.759095    8072 kuberuntime_manager.go:692] createPodSandbox for pod "exporter-node-windows-cluster-monitoring-ts5zq_cattle-prometheus(9fb6560f-6778-4f34-b9bf-ebe37ea4d94f)" failed: rpc error: code = Unknown desc = failed pulling image "k8s.gcr.io/pause:3.1": no matching manifest for windows/amd64 10.0.18362 in the manifest list entries
E1001 14:29:03.759095    8072 pod_workers.go:190] Error syncing pod 9fb6560f-6778-4f34-b9bf-ebe37ea4d94f ("exporter-node-windows-cluster-monitoring-ts5zq_cattle-prometheus(9fb6560f-6778-4f34-b9bf-ebe37ea4d94f)"), skipping: failed to "CreatePodSandbox" for "exporter-node-windows-cluster-monitoring-ts5zq_cattle-prometheus(9fb6560f-6778-4f34-b9bf-ebe37ea4d94f)" with CreatePodSandboxError: "CreatePodSandbox for pod \"exporter-node-windows-cluster-monitoring-ts5zq_cattle-prometheus(9fb6560f-6778-4f34-b9bf-ebe37ea4d94f)\" failed: rpc error: code = Unknown desc = failed pulling image \"k8s.gcr.io/pause:3.1\": no matching manifest for windows/amd64 10.0.18362 in the manifest list entries"

What to do? Create my own pause image?

Docker pull doesn't work either:

docker pull rancher/pause:3.1
3.1: Pulling from rancher/pause
no matching manifest for windows/amd64 10.0.18362 in the manifest list entries

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
1.15.4
```

- Docker version (use `docker version`):

```
Docker version 18.09.7, build b81f47481d
```

**Comment by stayfrostnl** [comment]
Fixed by using this image with a matching Kernel. This has to match else a Container wil never schedule on a Windows node. After a patch this version can differ and you need to rebuild the pause image:

https://hub.docker.com/r/e2eteam/pause/tags

And retaged it as k8s.gcr.io/pause:3.1, like:

docker tag e2eteam/pause:3.1 k8s.gcr.io/pause:3.1

You could also inspect it with the docker manifest command, to check the version available.

**Comment by pacoxu** [comment]
Currently, k8s.gcr.io/pause:3.4.1 works on both windows and Linux.
