### ISSUE TITLE
[UI] Center apps on screen

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#23178]
Version: master-head (v2.3.0) 10/2/19

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- View the apps screen (Launch apps)

**Result:**
They are not centered and so there is extra white space to the right. It doesn't look good.
![image](https://user-images.githubusercontent.com/45179589/66062485-5d4e2180-e4f6-11e9-9ac9-3f2fa6663776.png)

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by sowmyav27** [comment]
**verified on `master-head` latest**

Ui tag: `latest2`

Go to Cluster --> Project --> Apps --> Launch

Apps are centered on the screen
<img width="1362" alt="Screen Shot 2019-11-04 at 8 29 50 PM" src="https://user-images.githubusercontent.com/26032343/68130863-1f537b80-ff42-11e9-8e38-856d4496d1f7.png">
