### ISSUE TITLE
Node will not drain properly with Istio installed on v2.3.0-rc9

### ISSUE THREAD

**Issue by dsargent3220** [rancher/rancher#23175]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1.  With Rancher 2.3.0-rc9 install Istio on a cluster.
2.  Wait for all pods to come up in the System namespace
3.  Attempt to drain one of the worker nodes that has some istio workloads on it.  I used the following settings
  {"force":true,"ignoreDaemonSets":true,"deleteLocalData":true,"gracePeriod":"30","timeout":600}

**Result:**
The entire timeout is used and node never drains properly

**Other details that may be helpful:**
I can turn this on and off by uninstalling and reinstalling Istio.  When Istio is not installed, the nodes drain fine, when it is installed the nodes do not drain.

**Environment information**
- 2.3.0-rc9
- Single node

**Cluster information**
- Custom on prem
- VMWare VM with fully patched CentOS 7
- Kubernetes 1.15.4
- Docker 18.9.2

**Comment by dsargent3220** [comment]
I can confirm this is still an issue in rc11.

**Comment by dsargent3220** [comment]
Note that the test cluster I'm running this on only has worker nodes.  Not sure if that has anything to do with it.

**Comment by ibrokethecloud** [comment]
The node drain issue is caused due to a combination of pod disruption budgets and the defaults we specify in the helm chart.

```
NAME                     MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
istio-galley             1               N/A               1                     5m22s
istio-pilot              1               N/A               1                     5m22s
istio-policy             1               N/A               1                     5m22s
istio-sidecar-injector   1               N/A               1                     5m22s
istio-telemetry          1               N/A               1                     5m22s
```

This can be fixed by tweaking the replica count for the various control plane components by override default values when enabling istio.

The settings are:

```
galley.replicaCount: 2
pilot.autoScaleMin: 2
mixer.policy.autoScaleMin: 2
sidecarInjectorWebhook.replicaCount: 2
mixer.telemetry.autoscaleMin: 2
```

**Comment by loganhz** [comment]
Vanilla Istio chart has `minAvailable: 1` PDB by default for the following workloads.

```
NAME                     MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
istio-galley             1               N/A               1                     5m22s
istio-pilot              1               N/A               1                     5m22s
istio-policy             1               N/A               1                     5m22s
istio-sidecar-injector   1               N/A               1                     5m22s
istio-telemetry          1               N/A               1                     5m22s
```

When you drain a node, maybe you can check if there is a Istio (galley/pilot/policy/sidecar-injector/telemetry) pod on the target node.  You scale it up in workload page to try to have another pod running on another node. Then you can drain the node.

Also we can use @ibrokethecloud 's solution to make the replica to 2 by default. But it will take more CPU/Memory resources.

**Comment by cloudnautique** [comment]
@loganhz @deniseschannon 

If the scale is 1 then pdbs should be disabled. I agree that there are a lot of resources consumed when deploying the Istio components, and we should leave the current defaults as is. So for that I would suggest we disable the PDB resources.

We should document how to scale up the deployment for an HA Istio installation, along with the PDB configurations, through the extra chart args.

As a nice to have, scaling up is likely common in some environments, we should add UI form elements for PDB and scale.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24700
