### ISSUE TITLE
how to disable local k3s cluster ?

### ISSUE THREAD

**Issue by philpep** [rancher/rancher#23174]
Hi, I'm running an existing kubernetes 1.16 cluster (imported in rancher), so I'm using rancher on tag v2.3.0-rc9

Unfortunatelly, rancher seems now to start a local k3s cluster, which put my VM under high CPU  and memory charge.

I tried to start rancher with `--add-local false` but this doens't seems to have an effect, k3s cluster is still started.

How to disable the local k3s cluster then ?

**Comment by philpep** [comment]
The problem seems to be the process ``etcd --data-dir=management-state/etcd`` requiring a huge amount of memory. Any idea how to debug this ?

**Comment by vincent99** [comment]
You can't, the embedded cluster is the "database" that rancher uses.  The `--add-cluster` option just controls whether it shows up as a cluster inside rancher.

(You _can_ technically follow the HA installation instructions to use the actual cluster itself instead of running another inside of it, but this is a configuration we only commercially support if the cluster was made with RKE)

**Comment by philpep** [comment]
Ok, thanks for the explanation @vincent99 , so maybe there's an issue with memory comsumption of etcd ? IIUC, the etcd server was embeded in rancher 2.2 and now (2.3) it live in /usr/bin/etcd.
I was able to run rancher 2.2 in a VM with 2G of RAM, maybe it just now require more RAM ?

**Comment by vincent99** [comment]
2.3 is packaged a little differently but essentially doing the same thing as 2.2. The `docker run rancher/rancher` version runs an embedded copy of kubernetes and uses that to run the management controllers and persist the management state.  If you go to the HA install then it's a helm chart which is installed into an existing cluster you provide instead.

2GB has never _really_ been enough to run Rancher on its own... And if you're additionally running inside of another k8s cluster then there's another chunk of RAM going to that kubelet and whatever else is running.

This may have worked or been okay for a while with a minimal set of stuff running and in etcd or swap on or something, but etcd's state is kept in memory and just it by itself can itself hold up to 2GB of data.

**Comment by philpep** [comment]
Ok, I'll set more ram for rancher, thanks @vincent99
