### ISSUE TITLE
UI for Missing Dropdown for PodSecurityPolicies on imported Clusters #21039

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#23177]
UI changes for https://github.com/rancher/rancher/issues/21039

Fairly minor UI change. Where you decide to show/hide the pod security policy buttons, the logic will change a little bit

**Comment by rmweir** [comment]
After backend is merged this issue is also related and can be addressed: https://github.com/rancher/rancher/issues/21548

**Comment by rmweir** [comment]
and this issue: https://github.com/rancher/rancher/issues/12155

**Comment by rmweir** [comment]
Logic should just be driven off pspEnabled field found in cluster capabilities.

**Comment by jiaqiluo** [comment]
The bug fix is validated in  latest-2.3

now if the annotation  **capabilities/pspEnabled= true** is set to the imported cluster, the dropdown list for psp will show up in the project create/edit page.
