### ISSUE TITLE
UI for Feature Flags

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#23184]
We need a page that shows all the available feature flags and being able to turn them on/off for a Rancher install. 

_Edit from wes:_
@tfiduccia and I discussed the requirements for this offline, I have outlined them below. 

- [ ] Expose features flag as a tabbed view on the settings page
- [ ] Available feature flags will be listed in a table view with the follow columns
- [ ] Table Row Headers: Bulk Selector/State/Name/Description/Action Menu
- [ ] The default view for settings page is settings tab

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sowmyav27** [comment]
Verified the following on 2.3-head - latest, ui tag: `latest-2.3`

- Features flag is available as a tabbed view on the settings page
<img width="1313" alt="Screen Shot 2019-11-18 at 1 31 30 PM" src="https://user-images.githubusercontent.com/26032343/69095867-0fd73680-0a08-11ea-972f-7d45ff39a740.png">

- Available feature flags are listed in a table view with the follow columns
 Table Row Headers: State/Name/Description/Action Menu
`Bulk Selector` is NOT available.
- The default view for settings page is Advance settings tab

**Comment by westlywright** [comment]
I removed the bulk actions selector because I do not think it makes sense in this case. Feature flags are intended to be a one off type resource. It is fairly unlikely that a user would want to come in and turn ALL features on at once. If they do the likelihood that there are more that a few feature flags is low. I think the risk of using it incorrectly outweighs the benefits.

**Comment by sowmyav27** [comment]
the issue is good to be closed based on comments - https://github.com/rancher/rancher/issues/23184#issuecomment-555228272 and validations - https://github.com/rancher/rancher/issues/23184#issuecomment-555221644
