### ISSUE TITLE
[Forwardport] Ability to see what templates are using a cloud credential

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23193]
Forwardport of rancher/rancher#23064

**Comment by westlywright** [comment]
available in master

**Comment by sowmyav27** [comment]
**verified on master-head - latest** 
ui tag: `https://releases.rancher.com/ui/latest2/index.html`
Cloud credentials show an additional column - `# Node Templates`
<img width="1176" alt="Screen Shot 2019-10-22 at 1 40 53 AM" src="https://user-images.githubusercontent.com/26032343/67239525-012f4b00-f46d-11e9-8568-78c833a049a0.png">
