### ISSUE TITLE
[Forwardport] Apps: answers.yaml not in sync with "Edit as YAML" yaml

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23194]
Forwardport of rancher/rancher#20087

**Comment by westlywright** [comment]
Available in master

**Comment by jiaqiluo** [comment]
the bug fix is validated in Rancher:master-head 8d57a1cfb with UI index `https://releases.rancher.com/ui/latest2/index.html`

Used the same app and values from the original issue, and now the values are synced between the `edit as yaml` and `edit as form` modes when switching between them. Also, loading values from files also work and the values are sync between those two modes as well.
