### ISSUE TITLE
[Forwardport] Persistent storage options for Prometheus and Grafana display horizontally but would be better vertical

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23195]
Forwardport of rancher/rancher#22885

**Comment by westlywright** [comment]
Available in master

**Comment by sowmyav27** [comment]
**verified on master-head - latest - commit id: `8d57a1cfb`**

Go to cluster --> Tools --> Monitoring.
<img width="1669" alt="Screen Shot 2019-10-21 at 10 40 49 PM" src="https://user-images.githubusercontent.com/26032343/67227166-4e52f300-f454-11e9-9015-b6c1cfdcf0d7.png">

Persistent Storage for Grafana is given another section in the Monitoring page
<img width="1413" alt="Screen Shot 2019-10-21 at 10 41 32 PM" src="https://user-images.githubusercontent.com/26032343/67227157-42ffc780-f454-11e9-840f-4ae8127ebb55.png">
