### ISSUE TITLE
[Forwardport] Fix node dashboard "Docker Version" to change label to "Containerd Version" when containerd detected

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23191]
Forwardport rancher/rancher#21099

**Comment by westlywright** [comment]
Available in master

**Comment by sowmyav27** [comment]
**Verified on 2.3.1**
- Import a k3s cluster in Rancher UI
- Node dashboard shows "Docker Version: containerd "
<img width="1300" alt="Screen Shot 2019-10-23 at 2 09 25 AM" src="https://user-images.githubusercontent.com/26032343/67330738-7452c300-f53a-11e9-9cbb-8239a29b5f86.png">


**Verified on master head latest - ui tag: `latest2`**

- Import a k3s cluster in Rancher UI
<img width="1326" alt="Screen Shot 2019-10-23 at 1 59 26 AM" src="https://user-images.githubusercontent.com/26032343/67329784-f80bb000-f538-11e9-80d2-5ee9a9928763.png">
