### ISSUE TITLE
[Forwardport] Admin user icons differ between nav bar icon and edit cluster view Member Roles area

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23190]
Forwardport: rancher/rancher#21440

**Comment by westlywright** [comment]
Available in master.

**Comment by sowmyav27** [comment]
**Verified on latest -master**
ui tag: latest2
The admin icons are the same.

**On add cluster page.**
<img width="1309" alt="Screen Shot 2019-10-22 at 2 09 22 AM" src="https://user-images.githubusercontent.com/26032343/67241449-18703780-f471-11e9-802f-469dcb97da41.png">

**On edit cluster page.**
<img width="1297" alt="Screen Shot 2019-10-22 at 2 08 27 AM" src="https://user-images.githubusercontent.com/26032343/67241464-1efeaf00-f471-11e9-9d87-e912dcee23e4.png">
