### ISSUE TITLE
[Backport] Multicluster app does not show correct template version on Edit app

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23209]
Backport of rancher/rancher#23101

**Comment by sowmyav27** [comment]
Verified on `rancher:2.2.9-rc1`
**Steps:**

- Deploy a cluster1 - rke with 1 node. (A minimum of 1 cluster is required to launch mcapp)
- Global --> Apps --> Launch --> Select Mysql
- Select template version 0.3.7
- Select Target --> Default project from cluster1
- Click on Launch
- After the app is in Active status, click on Upgrade
- Template Version shown is 0.3.7 as Current.
