### ISSUE TITLE
UI - cannot open notifier page

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23207]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug 

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:master-head 10/3
- add ec2 cluster
- after the cluster is active, in the  cluster, go to tools -> notifiers

**Result:**
- UI crashes 
<img width="760" alt="Screen Shot 2019-10-03 at 11 06 29 AM" src="https://user-images.githubusercontent.com/6218999/66153026-93130900-e5cf-11e9-931b-dd4b8a4b3e01.png">

- only notifier has the bug, all other options under tools can be loaded successfully 

Info: 

Rancher | master-head
-- | --
User Interface | v2.3.12
UI Index | https://releases.rancher.com/ui/latest2/index.html

**Comment by deniseschannon** [comment]
Please use UI tag:  `2.3.12`

UI has branched and `master-head` will be pointing to the latest UI which has fixes that are for the next patch release.

**Comment by jiaqiluo** [comment]
Go to Settings -> UI Index to change the index to `https://releases.rancher.com/ui/2.3.12/index.html`, now the notifier page can be loaded successfully.

One thing to notice here is that by default, the UI tag is also v2.3.12, but the ui index is `https://releases.rancher.com/ui/latest2/index.html`
