### ISSUE TITLE
[Backport] Catalog app does not show correct template version on Edit app

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23208]
Backport of rancher/rancher#23051

**Comment by sowmyav27** [comment]
Verified on `rancher:2.2.9-rc1`

**Steps:**

- Deploy a cluster - rke with 1 node.
- In a project --> Apps --> Select an app i.e. mysql
- Select template version 0.3.7
- Click on Launch
- After the app is in Active status, click on Upgrade
- Template Version shown is 0.3.7 - as Current
- Upgrade app to version 0.3.8. Click on Upgrade.
- After the app comes up Active, click on edit app - Upgrade
- Version shown is 0.3.8 as current
