### ISSUE TITLE
Cluster owner cannot add authorized users to Istio RBAC

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23215]
rancher/rancher:master-head bc57ac2d1

* Deploy Rancher
* Create two standard users
* As the standard user create a cluster
* Add the second user as a project member
* Enable istio
* In Istio settings, add the second user as an authorized user in member access
* Save

The payload to `<project>:cluster-istio?action=upgrade` does not contain the member info for authorized access. 

When adding an authorized user as a Global Admin, the payload correctly contains the member info and the operation succeeds:
![Screen Shot 2019-10-03 at 1.30.21 PM.png](https://zube.io/files/rancher/fa10537978e28ecabb5679b14d9f0a46-screen-shot-2019-10-03-at-1-30-21-pm.png)

**Comment by bmdepesa** [comment]
I also see that when searching `principals` as the cluster owner, the request is using the plain user id instead of the principal user id.

Cluster owner:
![Screen Shot 2019-10-03 at 2 06 27 PM](https://user-images.githubusercontent.com/21316915/66164801-51428c80-e5e8-11e9-9056-687340ed09d8.png)

Admin:
<img width="822" alt="Screen Shot 2019-10-03 at 2 08 52 PM" src="https://user-images.githubusercontent.com/21316915/66164804-530c5000-e5e8-11e9-9775-287f9e0a3227.png">

**Comment by bmdepesa** [comment]
This also occurs when initially enabling Istio.

**Comment by loganhz** [comment]
https://github.com/rancher/system-charts/blob/dev/charts/rancher-istio/0.0.2/templates/istio-service-rbac.yaml#L14-L28

We need to pass the user id instead of principal id to the charts.  principal id doesn't work. But standard users cannot list users so they can not see the user id.

**Comment by westlywright** [comment]
Logan is correct about what is happening. We're using a standard user to add new members to the istio install. Those members are searched and retrieved from the `principals` api. The logic in the UI then looks through the global `users` list to find the correct user and grab that id rather than using the principal id. This doesn't work in this case because we have two standard users who do not have access to the corresponding each others user info (only principal).

I think the bug is in the Istio implementation. When creating PRTB/CRTB's we use the principal info and the backend is able to derive the info it needs for RBAC from that. I am not sure why the istio backend (or rancher inbetween) can't use that to determine it's RBAC roles like we do everywhere else.

**Comment by bmdepesa** [comment]
When using external auth, the Global Admin is hitting this issue as well -- the user info is not supplied in the answers to Istio.

**Comment by cjellick** [comment]
Compromise solution is to only expose groups in this area (because they work).

**Comment by bmdepesa** [comment]
As a quick recap of the functionality / issues as it stands pre-fix:

* Local Auth
  * Admin - can add user, can allow all
  * Standard user - cannot add user, can allow all

* External Auth
  * Admin - cannot add user (unless user logs in first), can add group, can allow all
  * Standard user - cannot add user, can add group, can allow all

* Standard users cannot view existing users added by admin (500 on request to principals search - id is in wrong format - https://<>/v3/principals/u-75s76v6b2h?sort=name)

**Comment by westlywright** [comment]
New functionality will limit the search to groups only. Verbiage has changed to indicate as much. You're either opening the ui's up to all auth'd members or individual groups. Will be available in UI tag 2.3.13.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.0-rc11

* Local Auth: 
  * Cluster owner
    * Can allow all
  * Admin
    * Can allow all 

* External Auth: 
  * Cluster owner
    * Can allow groups
    * Can allow all
  * Global admin
    * Can allow groups
    * Can allow all

* Text in UI is changed to reflect the change to allow group access or all only
* Regular members do not show in search when adding to group access
* Cluster owners can view all external links
* When 'allow all' is selected, all users with project access can view Kiali / Jaeger / Traffic Graph
* When a group is added, members of the group can view allowed resources
