### ISSUE TITLE
UI: Cannot login when connecting to a different Rancher API

### ISSUE THREAD

**Issue by kleoken** [rancher/rancher#23224]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Run rancher on VPS (I'm using DigitalOcean)
2. Clone and run the latest Rancher UI from GitHub pointing at the rancher instance in step 1
3. Login

**Result:**
In the UI at `localhost:8000`
```
NotFound (404)
no such schema
```
And then red boxes on the right side saying
```
Error
failed to find schema features: undefined
```

**Other details that may be helpful:**
Had this working the other day without a problem. Had some bad experiences with an addon so I wiped the UI repo and re-cloned from GitHub today and now it's not allowing me to login. Rancher instance is running on a DO droplet and not over https. Command I'm using to start the ui is simply `RANCHER="192.XXX.XXX.XXX" yarn start`. I do already have 1 cluster setup on the rancher instance.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8
- Installation option (single install/HA):
Single Install

**Comment by kaybinwong** [comment]
+1
