### ISSUE TITLE
Labels update support for External and Alias service

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2322]
Through service.update command. We start with just these 2 types of services as they don't have any containers; and the update won't introduce any inconsistencies between service/container. Labels update in this case would cause only:

* trigger metadata update
* selector based links updates

@ibuildthecloud

**Comment by alena1108** [comment]
Should be merged along with InServiceUpgrade/Rollback support

**Comment by alena1108** [comment]
Labels get upgraded via service.upgrade for all kinds of services now.

**Comment by sangeethah** [comment]
Tested with server version - v0.43.0-rc1

We are allowed to edit lables for DNS and External service as part of upgrade services now.
