### ISSUE TITLE
rancher-compose attempts to fetch logs for services that are deployed with selectorContainer and no image/image: rancher/none and reports failure.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2323]
Rancher server version - v0.41.0-rc2
Rancher compose version - rancher-compose-v0.4.1-rc2

When trying to start a service with selectorContainer and no image/ image: rancher/none using "up",
ancher-compose attempts to fetch logs for services and reports failure.

 ./rancher-compose -p noscale -f noscale.yml up

```
INFO[0000] Creating stack noscale                       
INFO[0001] Project [noscale]: Starting project          
INFO[0001] [0/2] [noscale]: Starting                    
INFO[0001] [0/2] [noscalenoimage]: Starting             
INFO[0001] Creating service noscale                     
INFO[0001] Creating service noscalenoimage              
INFO[0002] [1/2] [noscalenoimage]: Started              
ERRO[0002] Failed to get logs for test123: Failed to find action: logs 
INFO[0002] [2/2] [noscale]: Started                     
INFO[0002] Project [noscale]: Project started           
ERRO[0003] Failed to get logs for test123: Failed to find action: logs 
```

docker-compose.yml used:

```
noscale:
  labels:
    io.rancher.service.selector.container: foo=bar
```

**Comment by deniseschannon** [comment]
@sangeethah Can you provide the relevant docker-compose.yml?

**Comment by deniseschannon** [comment]
I am unable to reproduce. @sangeethah can you please try again? 

Steps I tried:
1. Create a standalone container with label `foo1=bar1`.
2. Use `rancher-compose up` with associated docker-compose.yml
```
noscale:
  labels:
    io.rancher.service.selector.container: foo1=bar1
```

The container joins the `noscale` service with no issues.

**Comment by sangeethah** [comment]
Not able to reproduce this issue.
