### ISSUE TITLE
[cli] Unable to install chart in multiple catalogs

### ISSUE THREAD

**Issue by kevinfrommelt-wf** [rancher/rancher#23238]
If a chart is available in multiple catalogs, it cannot be installed. It would be nice if you could specify the catalog as a parameter.

**What kind of request is this (question/bug/enhancement/feature request):**
bug/feature request

**Steps to reproduce (least amount of steps as possible):**
Enable the helm and library catalogs
```
rancher app install redis test-app
FATA[0001] Multiple resources of type template found for name redis: [cattle-global-data:helm-redis cattle-global-data:library-redis]
```

**Comment by xeor** [comment]
I just hit the same issue trying to install a chart that is deprecated in the main helm repo, but lives on in another..

@kevinfrommelt-wf did you get around this issue somehow? Weird that this issue is not more common

**Comment by mattsdevop** [comment]
`rancher app install -n another-namespace cattle-global-data:helm-redis` works

**Comment by kevinfrommelt-wf** [comment]
@mattsdevop Thanks, that does work.

Might be worth updating the error message to mention that you just need to pick one of the fully qualified names
