### ISSUE TITLE
Istio -Cluster owner is allowed to add himself in "Group Access" section which results in other cluster owners seeing the group access list as empty in UI (including other groups added).

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#23247]
Rancher server version - `v2.3.0-rc11`

Set up - Rancher server with AD auth enabled.

Steps to reproduce the problem:
As a regular user  say `testnewuser` who has access to rancher server, deploy a cluster and enable Istio by providing access to 1 group say `testgroup1` and himself `testnewuser`.

Note - Only the logged in user is presented as an option in addition to all the groups when trying to add contents in the `Member` search bar in `Group Access` section.

Add another user say `testnewuser1` as cluster member.

Log in as `testnewuser1`  and go to `Tools->Istio` page. 

Notice that "Group Access" page is empty. 
If this user added a new group say `testgroup12` , only this group gets added to the access list and  
existing `testgroup1` gets removed from the list.

Note - This behavior is seen only in the case were a user gets added to the the istio's group access list. 

Expected Behavior:
We should restrict the case of being able to select current logged in user in `Member` search bar in `Group Access` section.

**Comment by westlywright** [comment]
It doesn't sound like you have an up to date server (or perhaps we have a caching issue) as the ui tag `2.3.13` has a fix that disables adding members and you should not even be able to search members. So adding the logged in member to the cluster shouldn't be possible. The search box should only return groups. Can you retest this on a fresh install? I have a server up and running (`v2.3.0-rc11/v2.3.13`) and when I search I do not see any members return, only groups.

**Comment by sangeethah** [comment]
I am testing with a fresh install of v2.3.0-rc11 which comes with UI tag - v2.3.13.
When I am logged in as `testuser2` , this is the options presented in the dropdown menu

<img width="670" alt="Screen Shot 2019-10-06 at 12 26 08 PM" src="https://user-images.githubusercontent.com/4266958/66274545-c0acbc00-e834-11e9-80a0-7644469be89c.png">


and when logged in as `testuser4` , 

<img width="1128" alt="Screen Shot 2019-10-06 at 12 29 45 PM" src="https://user-images.githubusercontent.com/4266958/66274592-02d5fd80-e835-11e9-9918-bc35cb3dbbc6.png">

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.0-rc11
UI: 2.3.14

* Login as a standard user (with authorized access) 
* Create a cluster
* Enable Istio
* Navigate to Group access
* Cluster owner cannot view himself in the Groups list.
* Add a group to the access list
* Add another standard user as a cluster owner
* Login as the newly added user.
* The existing group can be viewed
* Add another group
* The new group is added without removing the previous group
