### ISSUE TITLE
Amazon Region/Instance Type Improvements

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#23244]
Currently, today, Amazon does not have an API to search region or instance types.

Research if it's possible to get the information so that users wouldn't have to rely on a Rancher server release to populate these fields.

Would solve issues like: 

https://github.com/rancher/rancher/issues/22150 - solution proposed here
https://github.com/rancher/rancher/issues/22907

**Comment by snasovich** [comment]
Closing due to age and lack of recent updates/interest in this.
