### ISSUE TITLE
[forwardport] Jailer script enhancements

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#23241]
https://github.com/rancher/rancher/issues/23160

https://github.com/rancher/rancher/issues/22379

**Comment by sowmyav27** [comment]
**verified on master-head latest - commit id: `a45722bb4`**

Currently the default setting for jailer-timeout is `60 seconds`.

- To simulate the jailer scripts failing to complete before timeout , did the following steps:
In the jailer script (/usr/bin/jailer.sh) , add a sleep of 15 seconds.
- Set jailer-timeout to 10 seconds ( < sleep set in jailer script).
- deploy a cluster with DO node driver.
- Node provisioning fails with following error message that states the reason:
- Following are the error message seen when jailer script fails to complete before timeout:
- Error: `Node create jail error: error running the jail command: timed out waiting for the script to complete: signal: killed`
- Error in logs:
`2019/10/21 21:48:52 [ERROR] NodeController c-jss7z/m-gzv8t [node-controller] failed with : node create jail error: error running the jail command: timed out waiting for the script to complete: signal: killed`

<img width="1306" alt="Screen Shot 2019-10-22 at 3 21 02 AM" src="https://user-images.githubusercontent.com/26032343/67246018-fe3b5700-f47a-11e9-92da-d1253b196ba1.png">

- Set `jailer-timeout` to 20 seconds ( > sleep set in jailer script)
- Provision a new node in the cluster. Provisioning of new node succeeds as expected.
