### ISSUE TITLE
Error restoring Rancher: This cluster is currently Unavailable; areas that interact directly with it will not be available until the API is ready.

### ISSUE THREAD

**Issue by taibc** [rancher/rancher#23245]
I am trying to backup and restore rancher server (single node install), as the link: [https://rancher.com/docs/rancher/v2.x/en/backups/backups/single-node-backups/](url)

After backup, I tried to turn off the rancher server node, and I run a new rancher container on a new node (in the same network), then I restored using the backup file as the link [https://rancher.com/docs/rancher/v2.x/en/backups/restorations/single-node-restoration/](url)

After restoring, I logined to the rancher UI and it showed below error 

![restore_rancher](https://user-images.githubusercontent.com/37021673/66258114-98d53e00-e7cb-11e9-997f-26da5f8fc115.PNG)

So, I checked the log of the rancher server and it showed as below:

> 2019-10-05 16:41:32.197641 I | http: TLS handshake error from 127.0.0.1:38388: EOF
> 2019-10-05 16:41:32.202442 I | http: TLS handshake error from 127.0.0.1:38380: EOF
> 2019-10-05 16:41:32.210378 I | http: TLS handshake error from 127.0.0.1:38376: EOF
> 2019-10-05 16:41:32.211106 I | http: TLS handshake error from 127.0.0.1:38386: EOF
> 2019/10/05 16:42:26 [ERROR] ClusterController c-4pgjl [user-controllers-controller] failed with : failed to start user controllers for cluster c-4pgjl: failed to contact server: Get https://192.168.94.154:6443/api/v1/namespaces/kube-system?timeout=30s: waiting for cluster agent to connect
> 2019/10/05 16:44:34 [ERROR] ClusterController c-4pgjl [user-controllers-controller] failed with : failed to start user controllers for cluster c-4pgjl: failed to contact server: Get https://192.168.94.154:6443/api/v1/namespaces/kube-system?timeout=30s: waiting for cluster agent to connect
> 2019/10/05 16:48:50 [ERROR] ClusterController c-4pgjl [user-controllers-controller] failed with : failed to start user controllers for cluster c-4pgjl: failed to contact server: Get https://192.168.94.154:6443/api/v1/namespaces/kube-system?timeout=30s: waiting for cluster agent to connect
> 2019-10-05 16:50:19.114475 I | mvcc: store.index: compact 75951
> 2019-10-05 16:50:19.137825 I | mvcc: finished scheduled compaction at 75951 (took 22.527694ms)
> 2019-10-05 16:55:19.120803 I | mvcc: store.index: compact 76282
> 2019-10-05 16:55:19.124813 I | mvcc: finished scheduled compaction at 76282 (took 2.746382ms)

How can I fix this error ?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.8` UI: `v2.2.94` |
|Route|`authenticated.cluster.nodes.index`|

**Comment by taibc** [comment]
When I checked log of the master nodes, I found the rancher agent still try to connect to the old rancher server (old ip address), not as the new one

**Comment by svenluzar** [comment]
I had the same problem. I'm using rke to deploy my cluster. After changing node rules, I have executed `rke up` again, but 'rke up' used the latest kubernetes version (1.16). The rancher-server and api were not compatible with this new kubernetes version. As a result, the cluster jumped back and forth between being active and unavailable.

The solution was to find a compatible version mix:

https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.3.3/

After that you have to specify the tag `kubernetes_version` in the cluster.yml file:

https://rancher.com/docs/rke/latest/en/config-options/#kubernetes-version

Finally you have to call `rke up` again.

**Comment by namebrandon** [comment]
@taibc Did you ever find a solution for this? I am seeing the exact same problem. I restored from single-node backup per docs, and am now getting a similar response.

    2020/01/03 12:17:40 [ERROR] ClusterController _all_ [user-controllers-controller] failed with : failed to start user controllers for cluster c-nm65z: failed to contact server: Get https://172.16.20.12:6443/api/v1/namespaces/kube-system?timeout=30s: waiting for cluster agent to connect

I can hit the API on the 172.16.20.12 using basic curl (though I get a auth failure). I've restarted the 172.16.20.12 server which is running the cluster-agent container.. still no luck on getting the rancher server container to talk to the cluster-agent on 172.16.20.12.

**Comment by aleksey005** [comment]
I got the same mistake. When installing one of the clusters, when determining the node, the public ip address was specified as its external Internet address, which the provider gives me. As a result, when the cluster is restarted, everything works for a while, but then the cluster agent tries to connect to this incorrectly specified address, which now I can not delete and not edit. In my case, the decision was to make rules for marking traffic on port 6443 and this external public ip address and the rules nat. As a result, as soon as I ensured availability for the server rancher of this IP address, the cluster instantly became available.

**Comment by taibc** [comment]
@namebrandon : Hi, I don't remember how to resolve this. Because, now I am using k8s, not Rancher. However, you can try below ways:

1. Restart all nodes
2. If option 1 is not successful, check logs of all system container/pods, to find something wrong
3. If option 2 is not successful, find all config files for old ip address, try to update it to new ip address and restart cluster
4. If option 3 is not successful, try to install another rancher version

Hope this can help you !

**Comment by linbingdouzhe** [comment]
any update?

**Comment by linbingdouzhe** [comment]
facing the same problem . but my rancher running aws ec2 instance by docker single node install, when i try backup and restoration , error appeared

**Comment by cgojanur123** [comment]
I am having the same issue when restoring the etcd snapshot from rancher. Can anyone please help

![image](https://user-images.githubusercontent.com/95447569/161891063-f1246b8b-d446-4243-bef5-a2b0c3b0e026.png)
