### ISSUE TITLE
Removing the resource ID or process name from the text box by deleting text does not cause the search to be cleared 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2325]
v0.41.0-rc1

Steps To Reproduce
1. Do a search on processes with text in either resource ID or process name
2. Remove the text in the text box (Note that the clear and search button are disabled)
3. Click on "All" or "Running"

Result: Search continues happening on the text that was deleted. 

Expected Result: Since there is no text in the textboxes, clicking on All or Running should not be running the search from the previous search.

**Comment by tfiduccia** [comment]
Version - master 1/29
Verified fixed

Clear is left as active so you can still clear everything out after you remove the text
