### ISSUE TITLE
Does canal support network encryption (like weave does)?

### ISSUE THREAD

**Issue by GameScripting** [rancher/rancher#23255]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
- Install Rancher 2.2.8 on a vm/bare metal with kubernetes 1.14.6
- Create custom cluster with Canal as network provider which results in:
rancher/calico-cni:v3.7.4
rancher/calico-node:v3.7.4
rancher/coreos-flannel:v0.11.0

**Question:**
In this setup:
- Is there any network encryption?
- If not, is there "easy" support for network encryption like for weave, where a [password is automatically set up for me](https://github.com/rancher/rancher/issues/22751#issuecomment-531221178)?
- If not, will there be support for network encryption with canal in rancher?
- If not, is weave the recommended network provider for network encryption?

**Notes from what I tried:**
I think there is currently NO encryption in place, I checked the [public network interface listening on udp 8472](https://rancher.com/docs/rancher/v2.x/en/installation/references/#commonly-used-ports) with tcpdump and I was able to see (unencrypted) traffic.

**Comment by superseb** [comment]
CNI provider information is documented at https://rancher.com/docs/rancher/v2.x/en/faq/networking/cni-providers/

For Flannel ipsec backend we have https://github.com/rancher/rancher/issues/19809 open.
