### ISSUE TITLE
catalog refreshes constantly

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#23256]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Add a catalog from an internal repo served by Harbor for helm charts

**Result:**
kubectl logs -n cattle-system --tail 10 rancher-7fbb8ff996-j7ztv
2019/08/23 15:41:37 [INFO] Updating project catalog ***********
2019/08/23 15:41:37 [INFO] Updating project catalog ***********-***********
2019/08/23 15:41:37 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/08/23 15:41:37 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/08/23 15:41:38 [INFO] Updating project catalog ***********
2019/08/23 15:41:38 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/08/23 15:41:39 [INFO] Updating project catalog ***********
2019/08/23 15:41:39 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/08/23 15:41:39 [INFO] Updating project catalog ***********
2019/08/23 15:41:39 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted

**Other details that may be helpful:**
- This worked fine with v2.2.7 but after upgrading to v2.2.8 this issue started

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.8
- Installation option (single install/HA): HA

**Comment by splattner** [comment]
same here

```
2020/02/12 12:54:14 [INFO] Updating global catalog *****
2020/02/12 12:54:14 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2020/02/12 12:54:15 [INFO] Updating global catalog *****
2020/02/12 12:54:15 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2020/02/12 12:54:16 [INFO] Updating global catalog *****
2020/02/12 12:54:16 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2020/02/12 12:54:17 [INFO] Updating global catalog *****
2020/02/12 12:54:17 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2020/02/12 12:54:18 [INFO] Updating global catalog *****
2020/02/12 12:54:18 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2020/02/12 12:54:19 [INFO] Updating global catalog *****
2020/02/12 12:54:19 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2020/02/12 12:54:20 [INFO] Updating global catalog *****
2020/02/12 12:54:20 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2020/02/12 12:54:20 [INFO] Updating global catalog *****
2020/02/12 12:54:21 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed

```

**Comment by brendarearden** [comment]
@splattner Are you able to run in debug mode and post that log? We added additional debug logging around this area in 2.3.4, so that might be able to give us a little more information as we have been unable to reproduce this problem in the past.

**Comment by splattner** [comment]
```
2020/02/14 13:10:49 [DEBUG] Helm preparing catalog cache [puzzle] for update
2020/02/14 13:10:49 [DEBUG] Helm updated http-helm catalog [https://charts.k8s.puzzle.ch]
2020/02/14 13:10:49 [DEBUG] Chart hash comparison for global catalog puzzle: new -- a532d378913ac63a17e3e20e365c4ec7 --- current -- 2920ee086e0f2b1c403a5ef33b1902b8
2020/02/14 13:10:49 [INFO] Updating global catalog puzzle
2020/02/14 13:10:49 [DEBUG] REST UPDATE apis/management.cattle.io/v3//catalogs/puzzle
2020/02/14 13:10:49 [DEBUG] chart mgob has not been changed. Skipping generating templates for it
2020/02/14 13:10:49 [DEBUG] chart postgres-backup-s3 has not been changed. Skipping generating templates for it
2020/02/14 13:10:49 [DEBUG] chart quay-builder has not been changed. Skipping generating templates for it
2020/02/14 13:10:49 [DEBUG] chart quay-enterprise has not been changed. Skipping generating templates for it
2020/02/14 13:10:49 [DEBUG] chart centos-apache-modsecurity has not been changed. Skipping generating templates for it
2020/02/14 13:10:49 [DEBUG] chart demo-app has not been changed. Skipping generating templates for it
2020/02/14 13:10:49 [DEBUG] chart gitlab-ci-pipelines-exporter has not been changed. Skipping generating templates for it
2020/02/14 13:10:49 [DEBUG] chart juicy-ctf has not been changed. Skipping generating templates for it
2020/02/14 13:10:49 [DEBUG] CatalogController calling handler system-image-upgrade-catalog-controller puzzle
2020/02/14 13:10:49 [DEBUG] chart quay-clair has not been changed. Skipping generating templates for it
2020/02/14 13:10:49 [DEBUG] CatalogController calling handler catalogCache puzzle
2020/02/14 13:10:49 [DEBUG] chart quay-redis has not been changed. Skipping generating templates for it
2020/02/14 13:10:49 [DEBUG] chart vaultsecretcontroller has not been changed. Skipping generating templates for it
2020/02/14 13:10:49 [DEBUG] chart cloudscale-csi has not been changed. Skipping generating templates for it
2020/02/14 13:10:49 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
```

does this helps?

I guess somehow the hashes are not equal: `Chart hash comparison for global catalog puzzle: new -- a532d378913ac63a17e3e20e365c4ec7 --- current -- 2920ee086e0f2b1c403a5ef33b1902b8`
altought no changes on the chartmuseum

**Comment by brendarearden** [comment]
Generally the hash should not change if there aren't changes to be processed for a chart(s). Can you confirm that there are no changes occurring in the index.yaml that is being served up from your chart repo? It might be that something is being updated there, but it isn't making changes to your charts so its triggering the refresh.

**Comment by splattner** [comment]
No, no changes in the helm chart but it seems the
`generated: "2020-03-16T13:17:07Z"`
does change each time the index.yaml is loaded. And I guess this does change the hash used for comparison.

**Comment by splattner** [comment]
This seems to be the problem: https://github.com/helm/chartmuseum/issues/152

**Comment by splattner** [comment]
the v0.12.0 release of ChartMuseum https://github.com/helm/chartmuseum/releases/tag/v0.12.0 has resolved this issue on my Rancher Instance

**Comment by samartzidis** [comment]
I am that same problem in Rancher (Version 5.3.3) but with ProGet as the Helm charts repository instead of ChartMuseum.

**Comment by flostru** [comment]
Same issue with https://charts.gitlab.io
Constantly refreshing in rancher 2.5.5

`time="2021-01-31T02:40:03Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"
31.1.2021 03:40:04 time="2021-01-31T02:40:04Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"
31.1.2021 03:40:04 time="2021-01-31T02:40:04Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"
31.1.2021 03:40:05 time="2021-01-31T02:40:05Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"
31.1.2021 03:40:06 time="2021-01-31T02:40:06Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"
31.1.2021 03:40:07 time="2021-01-31T02:40:07Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"
31.1.2021 03:40:08 time="2021-01-31T02:40:08Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"
31.1.2021 03:40:08 time="2021-01-31T02:40:08Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"
31.1.2021 03:40:09 time="2021-01-31T02:40:09Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"
31.1.2021 03:40:10 time="2021-01-31T02:40:10Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"
31.1.2021 03:40:11 time="2021-01-31T02:40:11Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"
31.1.2021 03:40:12 time="2021-01-31T02:40:12Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"
31.1.2021 03:40:13 time="2021-01-31T02:40:13Z" level=info msg="Downloading repo index from https://charts.gitlab.io/index.yaml"`

Other repos refresh a few times in a row but not as constantly

`31.1.2021 03:45:16 time="2021-01-31T02:45:16Z" level=info msg="Downloading repo index from https://grafana.github.io/helm-charts/index.yaml"
31.1.2021 03:45:16 time="2021-01-31T02:45:16Z" level=info msg="Downloading repo index from https://grafana.github.io/helm-charts/index.yaml"
31.1.2021 03:45:17 time="2021-01-31T02:45:17Z" level=info msg="Downloading repo index from https://grafana.github.io/helm-charts/index.yaml"
31.1.2021 03:45:17 time="2021-01-31T02:45:17Z" level=info msg="Downloading repo index from https://grafana.github.io/helm-charts/index.yaml"
31.1.2021 03:49:19 time="2021-01-31T02:49:19Z" level=info msg="Downloading repo index from https://charts.longhorn.io/index.yaml"
31.1.2021 03:49:19 time="2021-01-31T02:49:19Z" level=info msg="Downloading repo index from https://charts.longhorn.io/index.yaml"
31.1.2021 03:50:16 time="2021-01-31T02:50:16Z" level=info msg="Downloading repo index from https://grafana.github.io/helm-charts/index.yaml"
31.1.2021 03:50:16 time="2021-01-31T02:50:16Z" level=info msg="Downloading repo index from https://grafana.github.io/helm-charts/index.yaml"
31.1.2021 03:50:17 time="2021-01-31T02:50:17Z" level=info msg="Downloading repo index from https://grafana.github.io/helm-charts/index.yaml"
31.1.2021 03:50:17 time="2021-01-31T02:50:17Z" level=info msg="Downloading repo index from https://grafana.github.io/helm-charts/index.yaml`

**Comment by wyrie** [comment]
Same issue with https://charts.bitnami.com/bitnami
Rancher version 2.5.5

**Comment by wyrie** [comment]
#32217 - that fixes my issue

**Comment by dramich** [comment]
This issue has morphed from a v1 catalog refresh issue into a v2 refresh issue. The work that was previously done by @brendarearden most likely already fixed the v1 refresh issues that were seen in the original issue way back in rancher 2.2. The current issue that is being seen is in v2 (using dashboard to create the catalog). 
QA: In order to test this issue now:
1. Add the catalog https://charts.bitnami.com/bitnami through the dashboard UI 
2. After the catalog is done syncing edit the catalog yaml and add the line `gitBranch: master` directly under the `url` field. 
3. Watch the rancher server logs and it will repeat `2021/04/22 09:43:45 [INFO] Downloading repo index from https://charts.bitnami.com/bitnami/index.yaml` consistently. 
4. Upgrade rancher to a version with this fix and the logs will not repeat with the same catalog. Repeat removing and adding the same catalog and the logs should still not repeat.

**Comment by dramich** [comment]
https://github.com/rancher/terraform-provider-rancher2/issues/637

**Comment by slickwarren** [comment]
tested with the following setup: 
* on v2.5.7, followed instructions from [above comment](https://github.com/rancher/rancher/issues/23256#issuecomment-824971111)
  * saw logs repeat `Downloading repo index from` 
* upgraded rancher from 2.5.7 to 2.5.8-rc9 containing the latest fixes
* info message no longer displays

* also tested clean install of 2.5.8-rc9, added bitnami chart + gitBranch, and did not see the message there as well

@dramich is it expected that there is no initial message in logs that the chart is downloading?

**Comment by abelnieva** [comment]
I have upgraded to 2.5.8 version however I still seeing a lot of info messages 

2021/05/17 13:26:00 [INFO] Updating project catalog starburstdata
2021/05/17 13:26:00 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2021/05/17 13:26:01 [INFO] Updating project catalog starburstdata
2021/05/17 13:26:01 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2021/05/17 13:26:01 [INFO] Updating project catalog starburstdata
2021/05/17 13:26:01 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2021/05/17 13:26:01 [INFO] Updating project catalog starburstdata
2021/05/17 13:26:02 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2021/05/17 13:26:02 [INFO] Updating project catalog starburstdata
2021/05/17 13:26:02 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2021/05/17 13:26:02 [INFO] Updating project catalog starburstdata
2021/05/17 13:26:02 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
2021/05/17 13:26:03 [INFO] Updating project catalog starburstdata
....

**Comment by SchuhMichael** [comment]
Seeing this also on 2.5.9 following the documentation how to add a private gitlab package repository from [here](https://docs.gitlab.com/ee/user/packages/helm_repository/#install-a-package)

The catalog seems to work though, but it is constantly refreshing.

**Comment by zolech** [comment]
> Seeing this also on 2.5.9 following the documentation how to add a private gitlab package repository from [here](https://docs.gitlab.com/ee/user/packages/helm_repository/#install-a-package)
> 
> The catalog seems to work though, but it is constantly refreshing.

Same here. 2.59 and trying to add private gitlab elm repository. It works but it's constantly refreshing.

**Comment by dramich** [comment]
@zolech @SchuhMichael Can either of you open a new issue and provide as much information as possible that our issue template requests. Can you also turn on debug and grab the relevant portion and include that in the issue as well? 

This issue has already morphed a couple of times as to what it's for so let's get a clean one we can track.

**Comment by zolech** [comment]
> @zolech @SchuhMichael Can either of you open a new issue and provide as much information as possible that our issue template requests. Can you also turn on debug and grab the relevant portion and include that in the issue as well?
> 
> This issue has already morphed a couple of times as to what it's for so let's get a clean one we can track.

Right now I am not sure if it's a rancher's issue. I've switched to chartmuseum and everything works fine. It looks like it should be repoted to gitlab because it's similiar to https://github.com/helm/chartmuseum/issues/152. Every request is regenerating index.yaml
