### ISSUE TITLE
Error installing private registry 

### ISSUE THREAD

**Issue by taibc** [rancher/rancher#23252]
I install a private registry using catalog via Rancher UI. When I click "Launch", it show an alert without content as the image

![Registry](https://user-images.githubusercontent.com/37021673/66277192-39f3ef80-e8c5-11e9-8d74-4d84a0888783.PNG)
![Registry2](https://user-images.githubusercontent.com/37021673/66277202-63148000-e8c5-11e9-95ae-0a6108ec589c.PNG)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.8` UI: `v2.2.94` |
|Route|`catalog-tab.launch`|

**Comment by jiaqiluo** [comment]
I can launch the same app `docker-registry` from the built-in catalog with no problems.  All values are default values.


Rancher | v2.2.9-rc1
-- | --
User Interface | v2.2.98
Helm | v2.10.0-rancher11
Machine | v0.15.0-rancher8-1
