### ISSUE TITLE
When initially adding a group to Istio access with Github auth enabled, the member type shows as 'group' instead of 'Organization'

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23264]
rancher/rancher:v2.3.0-rc12

* Enable Github external auth
* Create a cluster
* Enable Istio
* Add a group to Istio's member access
* When initially adding the group, the Member type shows as 'group'
* After navigating away  and returning / refreshing the page, the member type now shows as 'Organization'

Expected: When first adding the group, the type should match the existing groups - 'Organization'

Immediately after adding:
![Screen Shot 2019-10-07 at 11.12.48 AM.png](https://zube.io/files/rancher/52434a8039e0e5e6df7f68bdfb5d3b46-screen-shot-2019-10-07-at-11-12-48-am.png)

After refreshing:
![Screen Shot 2019-10-07 at 11.14.09 AM.png](https://zube.io/files/rancher/62e621b816fb1c169d9bc02210308e9a-screen-shot-2019-10-07-at-11-14-09-am.png)

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
UI: latest-2.3

When adding a group, the group now correctly shows as type `Organization` upon adding to the list.
On refresh, the type is still `Organization`

![Screen Shot 2019-10-22 at 1 30 38 PM](https://user-images.githubusercontent.com/21316915/67329842-489af300-f4d0-11e9-9f71-72d47dd71d6d.png)
