### ISSUE TITLE
Can't click some UI elements in the Cluster Dashboard in master-head.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#23268]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

After creating a cluster I get JS errors in the Chrome Dev Tools console and I can't click in any element of the Cluster Dashboard `body` section.

I tried `Kubectl Config` and `Events` but nothing happened. Clicking `Launch kubectl` works.

**Steps to reproduce (least amount of steps as possible):**

- Install latest master I used latest `master-head v2.3 10/07/2019`
- Create a cluster. I used a GKE cluster.

**Result:**

Can't get kubectl config file and some elements are not clickable.

<img width="1299" alt="Screen Shot 2019-10-07 at 2 22 42 PM" src="https://user-images.githubusercontent.com/27659/66349641-2faa1380-e90e-11e9-9a84-6f9879e1c0ee.png">

**Other details that may be helpful:**

```
Uncaught (in promise) TypeError: Cannot read property 'parentNode' of undefined
    at m (percent-gauge.js:267)
    at g (percent-gauge.js:272)
```

**Environment information**
- Rancher version: `master-head v2.3 10/07/2019`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): GKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3 Nodes

**Comment by izaac** [comment]
I wasn't able to reproduce this with `rancher v2.3.0-rc12`

**Comment by izaac** [comment]
I'm not able to reproduce in latest `rancher master-head 10/21/2019`. Without monitoring.
I have to test with monitoring enabled but that is blocked by: https://github.com/rancher/rancher/issues/23573

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 9930781c8`

Create a cluster.
No Errors were seen in Dev Tools.
![Screen Shot 2019-11-15 at 10 01 57 AM](https://user-images.githubusercontent.com/57409052/68961169-fd05fd00-078e-11ea-8ec3-f97c4345c86b.png)

`Kubectl Config` can be accessed.
![Screen Shot 2019-11-15 at 9 57 56 AM](https://user-images.githubusercontent.com/57409052/68961292-45251f80-078f-11ea-9501-c8d6f39c140c.png)

`Events` can be accessed.
![Screen Shot 2019-11-15 at 9 58 42 AM](https://user-images.githubusercontent.com/57409052/68961336-5cfca380-078f-11ea-95e6-2c5b4ce9949f.png)

`Launch kubectl` can be accessed.
![Screen Shot 2019-11-15 at 9 58 26 AM](https://user-images.githubusercontent.com/57409052/68961305-4e15f100-078f-11ea-851b-0323aa8197a9.png)

`Edit` dropdown can be accessed.
![Screen Shot 2019-11-15 at 9 59 05 AM](https://user-images.githubusercontent.com/57409052/68961267-39395d80-078f-11ea-9b08-9e2a133b7d8d.png)
