### ISSUE TITLE
FreeIpa groups doesn't work

### ISSUE THREAD

**Issue by Ultrafenrir** [rancher/rancher#23277]
bug/question

Tried on 2.2.3 2.2.6 2.3.0-rc10

Setup FreeIpa  auth provider than restrict access to "devops" group only

Search of users and groups works fine, but no luck with groups mapping

Rancher DEBUG LOG
2019/10/08 12:20:36 [DEBUG] REST GET apis/management.cattle.io/v3//authconfigs/freeipa
2019/10/08 12:20:36 [DEBUG] Create Token Invoked
2019/10/08 12:20:36 [DEBUG] REST GET apis/management.cattle.io/v3//authconfigs/freeipa
2019/10/08 12:20:36 [DEBUG] REST GET api//v1/cattle-global-data/secrets/freeipaconfig-serviceaccountpassword
2019/10/08 12:20:36 [DEBUG] Now generating Ldap token
2019/10/08 12:20:36 [DEBUG] Now creating Ldap connection
2019/10/08 12:20:36 [DEBUG] Binding service account username password
2019/10/08 12:20:36 [DEBUG] Binding username password
2019/10/08 12:20:36 [DEBUG] getPrincipals: user attributes: [0xc00296d8c0 0xc00296d9c0 0xc00296dac0 0xc00296db00] 
2019/10/08 12:20:36 [DEBUG] SearchResult memberOf attribute {[cn=devops,cn=groups,cn=accounts,dc=ldap,dc=blabla,dc=com ipaUniqueID=asdada, other groups  etc. ]}
2019/10/08 12:20:36 [DEBUG] Ldap: Query for pulling user's groups: (&(objectClass=groupofnames)(|(dn=cn=devops,cn=groups,cn=accounts,dc=ldap,dc=blablabla,dc=com) all groups from perevious query memberof etc. )))

very similar to this problem -> https://forums.rancher.com/t/freeipa-ldap-group-problem/14412

**Comment by Ultrafenrir** [comment]
P.S. Also i have checked that all attributes that i set in rancher presents in FreeIpa via LDAPsearch

**Comment by cjellick** [comment]
What do you mean by "groups mapping" ?

**Comment by mrajashree** [comment]
> Setup FreeIpa auth provider than restrict access to "devops" group only

have you restricted access to only users from "devops" groups? then only they can login

> but no luck with groups mapping 

are you referring to group based memberships

**Comment by Ultrafenrir** [comment]
> > Setup FreeIpa auth provider than restrict access to "devops" group only
> 
> have you restricted access to only users from "devops" groups? then only they can login
> Yes, i do , and users from this group not able to login after this restriction set. If i add some user in allowed to login, he is able to login without issues
> > but no luck with groups mapping
>
> are you referring to group based memberships?
> Yes

**Comment by Ultrafenrir** [comment]
> What do you mean by "groups mapping" ?
group based membership
I'm able to add users and groups from my FreeIpa but if i set permission on some group, users of that group don't get needed rights.

**Comment by Ultrafenrir** [comment]
And the same problem with OpenLdap
If i add permissions to particular users they get rights , but if i set it on groups - users from those groups don't get needed rights 
my configuration is 
[https://prnt.sc/pgrj2h](url)

**Comment by Ultrafenrir** [comment]
P.S. configuration -> https://prnt.sc/pgrj2h

**Comment by Ultrafenrir** [comment]
Sorry guys, this problem is no related to rancher itself. Problem was that service account that i use to bind does not have rights to read entryDN attribute. Some time ago ldap disable ability to search by dn attribute, so the inly way get your groups work is using entryDN for Group Member User Attribute and Group DN Attribute. Hope this can help someone struggling with the same problem.
This issue can be closed.
