### ISSUE TITLE
Rancher min/max is not honored when trying to view a templateVersion using API call

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23275]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy an rke cluster.
2. deploy a custom catalog with rancher min max value set, so that one of the versions will not be available in the drop list of template version on rancher:v2.3.0-rc13.

e.x.: template version `0.2.1` (fluentd-aggregator) is not valid for rancher:v2.3.0-rc13 as its rancher_max = 2.2.99

**API request:**
`https://<rancher:server>/v3/templateVersions/p-hz87j:test-123-fluentd-aggregator-0.2.1?rancherVersion=v2.3.0-rc11`
OR
`https://<rancher-server>/v3/templateVersions/p-hz87j:test-123-fluentd-aggregator-0.2.1`
Both ^^^ lists the details of the template version 0.2.1

User should not be able to list the details of invalid template version.

**Question:** Presence of `rancherVersion=v2.3.0-rc11` in the API call does not matter. Do we need to have the rancherVersion in the API call for templateVersions?

Rancher UI uses `rancherVersion` while getting the template versions: 
`https://<rancher-server>/v3/templateVersions/c-n76z2:test-2-fluentd-aggregator-0.3.0?rancherVersion=v2.3.0-rc12`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:v2.3.0-rc13
- Installation option (single install/HA): HA

**Comment by dramich** [comment]
This is expected behavior of the API. The filter applies to calls on templates, not when specifically getting a templateVersion. We do not limit this on purpose as the UI or other consumers still need to reference the templates directly and don't want to filter that call. If you know a version you can get it.

**Comment by cjellick** [comment]
back to QA for closing

**Comment by sowmyav27** [comment]
As per this comment - https://github.com/rancher/rancher/issues/23275#issuecomment-540195505 closing the issue.
Tracking this`Presence of rancherVersion=v2.3.0-rc11 in the API call does not matter. Do we need to have the rancherVersion in the API call for templateVersions?` in a separate issue -https://github.com/rancher/rancher/issues/23327
