### ISSUE TITLE
Packet node driver out of date (backend and UI)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#23279]
Version: v2.3.0-rc13
Version: (older versions also affected)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a Packet node template

**Result:**
Images are out of date. Ubuntu 18.04 should be listed for example.
We only show a small handful of images.

Here is what is on the Packet website:
![image](https://user-images.githubusercontent.com/45179589/66407533-384c2980-e9a2-11e9-8935-c02fe083421d.png)

We may want to double-check to ensure all the instance details are still accurate too just in case things have changed since the last time this was looked at.

**Comment by deniseschannon** [comment]
This issue is to track the update to the latest packet release and the latest UI release provided by packet as part of our built-in components: 

https://github.com/packethost/ui-driver-packet

**Comment by deniseschannon** [comment]
Per packet, this is working as expected.
