### ISSUE TITLE
Kubernates on rancher on new OpenStack cluster dont get node info

### ISSUE THREAD

**Issue by lfdominguez** [rancher/rancher#23286]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create cluster with custom provider and OpenStack config as provider

**Result:**
Stale on provisioning with message "["node-x" not found]"

**Other details that may be helpful:**
I'm installed Rancher HA on OpenStack (private cloud), all working great, then I create another tenant on OpenStack (proyect) and then add a new cluster on Rancher UI, configuring the Node Template with the information of the cloud and put the custom provider openstack config.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher version 2.2.8

- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Cloud/VM 2 vCPU 4 GB RAM x 3 nodes
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
18.9.7
```

The main problem is that the cluster create the machines, install docker on them, download kubernates images, but when it run kubelet then this error is inside logs:

```
E1008 22:21:45.488414   25005 kubelet.go:2244] node "servicicio-rancher-1" not found
E1008 22:21:45.559624   25005 controller.go:204] failed to get node "servicicio-rancher-1" when trying to set owner ref to the node lease: nodes "servicicio-rancher-1" not found
```

Kubernates cant find the node on OpenStack instance, but the node is there, because that kubelet on that docker is running in that machine, so how can fix this?

**Comment by lfdominguez** [comment]
I see on my nginx (reverse proxy for OpenStack API) logs how the nodes call de Compute API to get instances info
```
request_time:0.213 upstream_time:0.212 response_size:15 status=200 from="10.128.14.14" host="compute.cloud.domain.xu" method="GET" upstream="192.168.128.203:8774" uri="/v2.1/servers/detail"
```

**Comment by lfdominguez** [comment]
Umm, the API receive the request from kubernates with
```
GET /v2.1/servers/detail?name=%5Eservicicio-rancher-1%24
```
but the server respond with
```
{"servers": []}
```
but the server (instance) is there... ummmm strange behavior

**Comment by lfdominguez** [comment]
never mind... my mistake, closing now, I was setted another project ID on the config... sorry

**Comment by Born2Bake** [comment]
Hi mate,

I ve raised same issue as yours, https://github.com/rancher/rancher/issues/24403 ; However, I am a bit confused since all my details related to openstack are correct; Openstack driver for Rancher is working fine as it should. How did you resolve that issue, can you share please?
cloud conf:

  cloud_provider:
    name: openstack
    openstackCloudProvider:
      block_storage:
        ignore-volume-az: true
        trust-device-path: false
      global:
        auth-url: "http://10.0.225.254:35357/v3"
        domain-id: "default"
        tenant-id: "e87e623e917b422c9c5160b119d3a528"
        username: "admin"
        password: "xxxxxxxxxxx"
      load_balancer:
        create-monitor: false
        manage-security-groups: false
        monitor-max-retries: 0
        use-octavia: false
      metadata:
        request-timeout: 0
      route: {}

**Comment by lfdominguez** [comment]
> fault

that i can see is that domain-id cant be "default", should be an ID, like the tenant-id

**Comment by Born2Bake** [comment]
We deployed openstack using kolla-ansible and default domain id in there is - "default".

http://prntscr.com/q6lant

Also, Openstack driver is working without any issues (except public/private key so we left it empty).
