### ISSUE TITLE
helm charts are broken in v2.3

### ISSUE THREAD

**Issue by evannorstrand** [rancher/rancher#23283]
2019/10/08 20:03:03 [ERROR] CatalogController library [catalog] failed with : Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
fatal: unable to access 'https://git.rancher.io/charts/': Failed to connect to git.rancher.io port 443: Connection timed out
: exit status 128
2019/10/08 20:03:03 [ERROR] CatalogController system-library [catalog] failed with : Clone failed: Cloning into 'management-state/catalog-cache/346ec2a1b7d48302a17ec6186e4713b5028d004fceacff4dc976fb20f9617766'...
fatal: unable to access 'https://git.rancher.io/system-charts/': Failed to connect to git.rancher.io port 443: Connection timed out
: exit status 128
2019/10/08 20:05:14 [ERROR] CatalogController library [catalog] failed with : Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
fatal: unable to access 'https://git.rancher.io/charts/': Failed to connect to git.rancher.io port 443: Connection timed out
: exit status 128
2019/10/08 20:05:14 [ERROR] CatalogController system-library [catalog] failed with : Clone failed: Cloning into 'management-state/catalog-cache/346ec2a1b7d48302a17ec6186e4713b5028d004fceacff4dc976fb20f9617766'...
fatal: unable to access 'https://git.rancher.io/system-charts/': Failed to connect to git.rancher.io port 443: Connection timed out
: exit status 128

**Comment by cjellick** [comment]
Any more details about your setup that might help us investigate? These charts generally working are critical path for rancher and we haven’t seen them fail in this manner in our testing.

**Comment by evannorstrand** [comment]
@cjellick the issue seems to be the happening on a new deployment of 3.2.8 as well.


Clone failed: Cloning into 'management-state/catalog-cache/2284e9d6c1e82c5a56a5cb7c1d5c0144835734b1b66da6f75122d99c7989618f'... fatal: unable to access 'https://git.rancher.io/system-charts/': Failed to connect to git.rancher.io port 443: Connection refused : exit status 128
--

**Comment by evannorstrand** [comment]
@cjellick it looks as if it's an issue at the endpoint, not local to our network. Tested on two networks (4g and local)

**Comment by leodotcloud** [comment]
Could you try `git clone https://git.rancher.io/charts/` and see if you are facing any problems?

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.0
Single node

I am unable to reproduce.

* Enabled external auth (Github)
* Logged in as standard user
* Create cluster
* Deployed app from library
* Enabled logging to deploy app from system-library
* Refreshed catalogs

All catalog apps and logging from system-charts deployed successfully.
After refreshing catalogs I see: 
```
2019/10/08 20:52:15 [DEBUG] Helm preparing catalog cache [library] for update
2019/10/08 20:52:15 [DEBUG] Helm updated git-helm catalog [https://git.rancher.io/charts:master]
2019/10/08 20:52:52 [DEBUG] Helm preparing catalog cache [system-library] for update
2019/10/08 20:52:52 [DEBUG] Helm updated git-helm catalog [https://git.rancher.io/system-charts:release-v2.3]
```

**Comment by evannorstrand** [comment]
Some other notes, we deployed rancher in HA on top of the latest RKE. I will try using the previous release or a low availability deployment shortly

**Comment by cjellick** [comment]
@evannorstrand we identified that this was a problem at git.rancher.io and it looks like service has been restored. is it working for you now?

**Comment by evannorstrand** [comment]
We are getting the same issue

```Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'... fatal: unable to access 'https://git.rancher.io/charts/': Failed to connect to git.rancher.io port 443: Connection timed out : exit status 128```

**Comment by evannorstrand** [comment]
```This git.rancher.io page can’t be foundNo webpage was found for the web address: https://git.rancher.io/charts/
HTTP ERROR 404```

**Comment by evannorstrand** [comment]
Some more information:

git clone https://git.rancher.io/charts/ works on the localhosts running the kubernetes cluster. it does NOT work within the rancher pod.

**Comment by bmdepesa** [comment]
@evannorstrand are you able to resolve DNS for other resources (rancher.com, google) from within the cluster?

**Comment by evannorstrand** [comment]
@bmdepesa @cjellick 

After downgrading to rke-0.2.8 our checkout issues have been resolved. No other changes have been made.

**Comment by evannorstrand** [comment]
https://github.com/rancher/rke/issues/1687

**Comment by leodotcloud** [comment]
@evannorstrand can you ping me on https://slack.rancher.io?

**Comment by evannorstrand** [comment]
So for anyone who runs into this issue....

After many hours of debugging and hunting, it turns out our network service provider has shit dns. Once I forced our router to use Google's dns (8.8.8.8, 8.8.4.4), everything worked.

**Comment by cjellick** [comment]
😱
