### ISSUE TITLE
Upgrade to 2.3.0 causes Projects with malformed certs to fail to display in the UI

### ISSUE THREAD

**Issue by rajha-korithrien** [rancher/rancher#23285]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Start with a Rancher v2.2.8 cluster.
Create a certificate (which I think is malformed) with a format similar to the following.
* tls.cert:
```text
Bag Attributes
    friendlyName: broker
    localKeyID: 3A 5E EF 3F 97 4A DF 1F C8 55 8B 6C 96 46 17 3F 28 36 58 6D 
subject=/C=US/ST=strogbadia/O=burniator/CN=pulp-qpid.paas-pulp.svc.cluster.local
issuer=/C=US/ST=strogbadia/O=burniator/CN=trogdor
-----BEGIN CERTIFICATE-----
REDACTED
-----END CERTIFICATE-----
```
* tls.key:
```text
Bag Attributes
    friendlyName: broker
    localKeyID: 3A 5E EF 3F 97 4A DF 1F C8 55 8B 6C 96 46 17 3F 28 36 58 6D 
Key Attributes: <No Attributes>
-----BEGIN PRIVATE KEY-----
REDACTED
-----END PRIVATE KEY-----
```
This certificate does not display correctly in the UI in v2.2.8 via: `Resources --> Certificates` however the Project containing it does display as expected.

After the upgrade to v2.3.0, when navigating to the Project with the malformed certificates the following error is displayed in a red box in the upper right of the UI:
```text
Status [422 Unprocessable Entity]. Body: [code=InvalidBodyContent, fieldName=certs, message=failed to parse certificate: asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:1 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} tbsCertificate @2, baseType=error]
```
**Result:**
After upgrading to v2.3.0 certain projects can not be displayed in the Rancher UI due to what seems to be existing malformed certificates.

**Other details that may be helpful:**
When I use `kubectl` to manually edit the certificates in question such that they consist of only:
```text
-----BEGIN CERTIFICATE-----
REDACTED
-----END CERTIFICATE-----
```
and:
```text
-----BEGIN PRIVATE KEY-----
REDACTED
-----END PRIVATE KEY-----
```
The project will display as expected, and the certificates show correctly in the UI under: `Resources --> Secrets --> Certificates`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom (created via the Rancher UI)

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
bare metal via RancherOS 1.5.4
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
> 
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.2-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        6d37f41
 Built:             Sun Feb 10 03:43:40 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       6d37f41
  Built:            Sun Feb 10 03:51:58 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by Aisuko** [comment]
I have been hit this issue in our dev environment. I upgraded rancher from v2.2.8 to v2.3 and got this issue. The rancherHA cluster was deployed by rke `v0.2.8`.  Now, I can't load the resources under the project name system. The error below.

```
Error
Validation failed in API: certs failed to parse key: key must be PEM encoded PKCS1 or PKCS8: asn1: structure error: tags don't match (16 vs {class:0 tag:6 length:8 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs8 @2
```

```
master1   Ready    controlplane,etcd   52d   v1.14.6   10.16.18.21    <none>        Red Hat Enterprise Linux Server 7.5 (Maipo)   3.10.0-1062.el7.x86_64   docker://19.3.2
```

**Comment by mrajashree** [comment]
@rajha-korithrien @Aisuko were these certs created through rancher ui?

**Comment by rajha-korithrien** [comment]
Mine were not, they were created by bash scripts calling kubectl.

**Comment by Aisuko** [comment]
> @rajha-korithrien @Aisuko were these certs created through rancher UI?

In my situation, our cluster was deployed by rancher rke, the certs were created by following the `rke deploy Rancher(HA) cluster document`

**Comment by sowmyav27** [comment]
verified the issue and the fix.

**Steps:**

- On rancher:v2.2.8, deploy an rke cluster.
- Deploy Cert Manager on a cluster - project on Rancher UI (default project)
- Deploy a certificate from kubectl into a namespace
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  commonName: example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
```
- edit the cert - kubectl edit secret <name> -n <namespace> and change the `tls.key` or `tls.cert` value. (to make this cert and invalid one)
- Save the changes made.
- Now upgrade rancher to **`rancher:v2.3.0`**
- Navigate to Cluster --> Default Project
- Error is seen on the UI
<img width="970" alt="Screen Shot 2019-10-23 at 12 15 25 AM" src="https://user-images.githubusercontent.com/26032343/67322346-83337880-f52e-11e9-8529-f1493db3421f.png">
- Error in API request
```
{"baseType":"error","code":"InvalidBodyContent","fieldName":"certs","message":"failed to decode key: not valid pem format","status":422,"type":"error"}
```
- Upgrade rancher to v2.3-head - latest - commit id: ``
- Navigate to Cluster --> Default Project
- No error is seen on the UI.
- Error is seen in logs:
```
2019/10/22 18:50:43 [ERROR] Error certs=InvalidBodyContent 422: failed to decode key: not valid pem format parsing cert selfsigned-cert-tls. Will not display correctly in UI
2019/10/22 18:50:43 [ERROR] Error certs=InvalidBodyContent 422: failed to decode key: not valid pem format parsing cert selfsigned-cert-tls. Will not display correctly in UI
2019/10/22 18:50:43 [ERROR] Error certs=InvalidBodyContent 422: failed to decode key: not valid pem format parsing cert selfsigned-cert-tls. Will not display correctly in UI
```
