### ISSUE TITLE
Catalog UI is not showing apps icon correctly

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#23291]
**What kind of request is this (question/bug/enhancement/feature request):**
UI bug

**Steps to reproduce (least amount of steps as possible):**
1. Go to the catalog apps page
2. both catalog apps page and catalog page only showing the same icon for all apps.

![image](https://user-images.githubusercontent.com/4569037/66444323-6189ba00-ea75-11e9-906f-67a5c1246589.png)
![image](https://user-images.githubusercontent.com/4569037/66444347-76664d80-ea75-11e9-9963-68930882dea5.png)

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA):
Both

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
Move to 2.4 as it only happens in master-head

**Comment by westlywright** [comment]
This is available in the `latest-2.3`. QA can test with a 2.3 release or 2.3-master by replacing ui-index with `https://releases.rancher.com/ui/latest-2.3/index.html`

**Comment by jiaqiluo** [comment]
The bug fix is validated in 
- v2.3.1 with  ui-index `https://releases.rancher.com/ui/latest-2.3/index.html`
- matster-head with the default ui-index  `https://releases.rancher.com/ui/latest2/index.html`

Results:
- apps show their own icons in the catalog apps list
- deployed apps also show their own icons
