### ISSUE TITLE
catalog app is still showing when all of the templates are hidden by max_rancher_version

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#23295]
**What kind of request is this (question/bug/enhancement/feature request):**
UI bug

**Steps to reproduce (least amount of steps as possible):**
1. add custom catalog e.g  https://github.com/guangbochen/charts with `istio-2.3` branch
2. go to the catalog apps page and click istio app
3. will redirect to the catalog apps launch page since all template versions are filtered by the `max_rancher_version` 
![image](https://user-images.githubusercontent.com/4569037/66458067-6154e300-eaa4-11e9-869e-3f2caca74c51.png)

**Result:**
Hide those catalog apps if no template version matches the Rancher min/max version filter.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0
- Installation option (single install/HA):
Both

**Comment by westlywright** [comment]
This is available in the `latest-2.3`. QA can test with a 2.3 release or 2.3-master by replacing ui-index with `https://releases.rancher.com/ui/latest-2.3/index.html`

**Comment by sowmyav27** [comment]
**reproduced the issue on `rancher:v2.3.0`**

**Steps:**

- Add a catalog app: which has all of the templates hidden by max_rancher_version.
- Go to Apps --> Launch
- You will see the app listed on the apps page.
- On selecting the app, it navigates you back to the Apps page

**Comment by sowmyav27** [comment]
**Verified with `rancher:v2.3.1-rc2`**

**Steps:**

- Add a catalog app: which has all of the templates hidden by max_rancher_version.
- Go to Apps --> Launch
- User will NOT be able to see the app (hidden by the rancher_max_version)
- App here is fluentd-aggregator

<img width="1282" alt="Screen Shot 2019-10-12 at 11 35 35 AM" src="https://user-images.githubusercontent.com/26032343/66706194-ab2c0c00-ece4-11e9-9075-b543636d49cd.png">
