### ISSUE TITLE
when rancher login , i get a errer:"Unable to parse response https://xxxx/v3/settings/cacerts"

### ISSUE THREAD

**Issue by caliahub** [rancher/rancher#23296]
FATA[0127] Unable to parse response from https://xxxx/v3/settings/cacerts
Error: invalid character '<' looking for beginning of value
Response:
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by superseb** [comment]
This is returned by NGINX (I assume NGINX ingress in HA setup), which means it can't route the request to one of the pods. You can check the NGINX ingress pod logs or use https://rancher.com/docs/rancher/v2.x/en/troubleshooting/ to troubleshoot the cluster to see what is causing it.
