### ISSUE TITLE
Dropdown not working on mobile (ipadOS)

### ISSUE THREAD

**Issue by gregod-com** [rancher/rancher#23298]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug (did work fine with 2.2.7 and 2.2.8)

**Steps to reproduce (least amount of steps as possible):**
Update to Rancher 2.3 & access WebUI with iPad (tested with iPadOS 13)

**Result:**
No interaction with dropdown menus possible

**Other details that may be helpful:**
Zooming to 150% shows that the functionality is there. With 100% zoom only the first element in a dropdown is clickable. The problem occurs on all dropdown menus.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.3
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Imported (rke on bare metal)
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
-
- Kubernetes version (use `kubectl version`):
1.15.2

**Comment by Dzamir** [comment]
I can confirm this also happens to me, tested on iPadOS 13.2.2

**Comment by dmitryzykov** [comment]
I confirm this problem too:
Rancher 2.3.3
iPad Pro 13” with iPadOS 13.2.3

![B845E810-F337-4E16-9342-4859252C6903](https://user-images.githubusercontent.com/15911918/69903759-8d0a9000-13a6-11ea-8e92-e9735e418b46.jpeg)

![861DC3C3-BC6B-4768-8C6C-C933C2A5289C](https://user-images.githubusercontent.com/15911918/69903777-c2af7900-13a6-11ea-8086-54f719857e10.jpeg)

**Comment by fisherwei** [comment]
Same issue

![96E7F105-A640-43C2-B704-A47FDFF6847C](https://user-images.githubusercontent.com/214470/70307391-03464100-1844-11ea-908a-ce0e30c44d12.jpeg)

**Comment by hameno** [comment]
Same issue on chrome on Android. Unusable now :( 
Please improve, it's quite important for us

**Comment by gregkeys** [comment]
This has been happening for some time now, it makes rancher unusable on a mobile device, which is really annoying

**Comment by dmitryzykov** [comment]
Issue still exist in 2.4.2

**Comment by dwene** [comment]
Can confirm, issue still exists in 2.4.2.

**Comment by xlanor** [comment]
Can I check, when will https://github.com/rancher/ui/pull/4130 be merged or reviewed?

**Comment by DoNotSayYes** [comment]
**Rancher version:** `v2.4.2`
Can be reproduced by using the simulators of Chrome

**iPad Pro:**
![image](https://user-images.githubusercontent.com/57614736/93193608-a506a100-f779-11ea-8a46-a3d42b847b24.png)

**Glaxy S5:**
![image](https://user-images.githubusercontent.com/57614736/93194016-2f4f0500-f77a-11ea-996f-ff26fad6b74c.png)

**Comment by DoNotSayYes** [comment]
**Rancher version:** `master-head`
**Commit:** [9531d6e](https://github.com/rancher/ui/pull/4130/commits/9531d6e71cddec5785d28ed6c88ee33dde77f3d2)

Verified by using simulators of Chrome

**iPad:**
![image](https://user-images.githubusercontent.com/57614736/93194653-e77cad80-f77a-11ea-9682-d9db687c7d2e.png)

**Galaxy S5:**
![image](https://user-images.githubusercontent.com/57614736/93194747-03804f00-f77b-11ea-8d8d-c8789c39b63a.png)
