### ISSUE TITLE
Find out on which cluster is a node.

### ISSUE THREAD

**Issue by garelp** [rancher/rancher#23305]
Hello,

I don't find an easy way for search for a node in the web interface. I'm starting to have a lot of clusters and I'd like to ease the life of the oncall person when an issue is detected on a node.
Currently when I search in the field in the cluster list, it only filter out the cluster name. I would like the same for the nodes.

Is there a way to add this feature in a future release?

Thanks.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.7` UI: `v2.2.93` |
|Route|`global-admin.clusters.index`|

**Comment by pulberg** [comment]
We do something like this with the Rancher CLI, in addition to adding several host labels - 

```
rancher inspect --type node k8sworker121355 | jq . | grep k8s_cluster
      "k8s_cluster": "dev-devops-dev"
```

**Comment by garelp** [comment]
Hello,

Thanks for the advice. At least this is workaround until the feature is implemented into the web interface. 

Regards.

**Comment by aaronRancher** [comment]
The feature is verified with Rancher server `rancher\rancher:master-head` `version bc8175f6f`
The search box can now sort through clusters by node name.
![Screen Shot 2020-02-04 at 2 14 16 PM](https://user-images.githubusercontent.com/57409052/73787925-5dd31f00-4759-11ea-9440-5f453b3dce9f.png)
For example, to find node `ip-172-31-3-133`:
![Screen Shot 2020-02-04 at 2 15 26 PM](https://user-images.githubusercontent.com/57409052/73787717-164c9300-4759-11ea-8078-e8e09e3acdc5.png)
Enter node name in the search field, and the results will present the node containing cluster.
![Screen Shot 2020-02-04 at 2 14 27 PM](https://user-images.githubusercontent.com/57409052/73787728-19e01a00-4759-11ea-8da0-147bb38b599e.png)
