### ISSUE TITLE
[forwardport] fluentd pod CPU is high when enable plenty of project logging.

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23303]
forwardport https://github.com/rancher/rancher/issues/23113

**Comment by alena1108** [comment]
@aiwantaozi what kind of regression test qa need to do, in addition to validating the original issue?

**Comment by aiwantaozi** [comment]
@alena1108 Hi, the step in this issue is enough for testing https://github.com/rancher/rancher/issues/23113, could test one more target link elasticsearch for regression test

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 48a2c4ffc

* Enabled cluster logging w/ fluentd target
* Enabled project monitoring w/ elasticsearch target on multiple projects
* All targets are receiving logs
