### ISSUE TITLE
[UI] Support Istio Gateway as first class resource in Rancher UI #20892

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23302]
UI for https://github.com/rancher/rancher/issues/20892

**Comment by westlywright** [comment]
Available in `latest-2.3`

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
UI: latest-2.3

* Gateway navigation tab is shown
* All Istio navigation tabs are shown
* Imported gateways appear in UI w/ correct values
* Created gateways are functional
* Gateway inputs match resulting CRD
