### ISSUE TITLE
Provisioner Quobyte v2.3.0

### ISSUE THREAD

**Issue by aloisiobilck** [rancher/rancher#23304]
**What kind of request is this (question/bug/enhancement/feature request):** question

**Steps to reproduce (least amount of steps as possible):**

In the Storage Classes UI the Provisioner **Quobyte** option does not appear. In version 2.2.8 appears.

**Environment information**
- Rancher version: 2.3.0
- Installation option (single install/HA): single install

**Cluster information**

```
Cluster type: vSphere
Kubernetes version: 1.14.7
```

- Docker version (use `docker version`):

```
18.9.8
```

**Comment by superseb** [comment]
See https://rancher.com/docs/rancher/v2.x/en/admin-settings/feature-flags/enable-not-default-storage-drivers/.

Let me know if that doesn't solve the issue.
