### ISSUE TITLE
setting up node alert for memory reservation also sets cpu reservation

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#23308]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. create a node alert selecting memory reservation
2. select and modify memory reservation only (cpu is greyed out but shows 70%)
3. save rule

**Result:**
cputhreshold gets set as well
```
  nodeRule:
    condition: mem
    cpuThreshold: 70
    memThreshold: 30
```

**Other details that may be helpful:**
<img width="728" alt="Screen Shot 2019-10-09 at 9 07 41 AM" src="https://user-images.githubusercontent.com/474978/66499594-f7711500-ea74-11e9-8a9a-ed4237199663.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
HA v2.2.8

**Comment by westlywright** [comment]
Available in UI tag `latest2`

**Comment by sowmyav27** [comment]
**Reproduced the issue on `rancher:v2.3.1`**

**Steps:**

- On a cluster, create a node alert selecting memory reservation
- Select and modify memory reservation only (cpu is greyed out but shows 70%)
- save rule
- Request sends the below values: `cpuThreshold` is seen set

```
condition: "mem"
cpuThreshold: 70
memThreshold: "30"
nodeId: "c-gtpht:m-mqtv2"
selector: null
type: "nodeRule"
```
- View in API of the alert shows `cpuThreshold` also to be set
```
"nodeRule": {
"condition": "mem",
"cpuThreshold": 70,
"memThreshold": 30,
"nodeId": "c-gtpht:m-mqtv2",
"selector": null,
"type": "/v3/schemas/nodeRule"
},
```

**Validated the fix on `master-head` - latest - commit id: `8d57a1cfb`**

**Steps:**
- On a cluster, create a node alert selecting memory reservation
- Select and modify memory reservation only (cpu is greyed out but shows 70%)
- save rule
- Request sends the below values: `cpuThreshold` is NOT set. only `memThreshold` is set
```
nodeRule: {condition: "mem", memThreshold: "30", type: "nodeRule", nodeId: "c-42qwk:m-9kvmm", selector: null}
condition: "mem"
memThreshold: "30"
nodeId: "c-42qwk:m-9kvmm"
selector: null
type: "nodeRule"
```
- But View in API of the alert shows `cpuThreshold` is set. 
```
"nodeRule": {
"condition": "mem",
"cpuThreshold": 70,
"memThreshold": 30,
"nodeId": "c-42qwk:m-9kvmm",
"selector": null,
"type": "/v3/schemas/nodeRule"
},
```

**Comment by sowmyav27** [comment]
@loganhz The UI seems to be sending correct values. But the backend seems to set the other value `cpuThreshold`

**Comment by loganhz** [comment]
```  
nodeRule:
    condition: mem
    cpuThreshold: 70
    memThreshold: 30
```

If condition is `mem`, backend will ignore `cpuThreshold` field when we generate the alert. This is by design.
