### ISSUE TITLE
Cannot connect to rancher server with self-signed certificate from agent (Etcd)

### ISSUE THREAD

**Issue by shown1985** [rancher/rancher#23306]
**What kind of request is this (question):**
Cannot connect to rancher server with self-signed certificate from agent (Etcd)

**Steps to reproduce (least amount of steps as possible):**

**First**,
install a standalone rancher server with self-signed certificate

docker run -d --restart=unless-stopped \
-p 80:80 -p 443:443 \
-v rancher:/var/lib/rancher \
-v /var/lib/certs/server.crt:/etc/rancher/ssl/cert.pem \
-v /var/lib/certs/server.key:/etc/rancher/ssl/key.pem \
-v /var/lib/certs/ca.crt:/etc/rancher/ssl/cacerts.pem \
-v /var/lib/cacerts:/container/certs \
-e SSL_CERT_DIR="/container/certs" \
--name rancher \
rancher/rancher:v2.3.0

**And**
run the command on the node

sudo docker run -d --privileged --restart=unless-stopped --net=host \
-v /etc/kubernetes:/etc/kubernetes \
-v /var/run:/var/run rancher/rancher-agent:v2.3.0 \
--server https://cloud.uat.qa.mojorycorp.cn \
--token skdx8zxmc82596xvm9vh7kttpfjxj27ddxhsd4txgtfbfz5wbfhl6j \
--ca-checksum ca1d3204dbfc07bd7588ce75e263d2e6f84b514f078038dcc4ad749b74f49e69 \
--etcd --controlplane --worker

**Result:**

Provisioning: [etcd] Failed to bring up Etcd Plane: [etcd] Etcd Cluster is not healthy

etcd log:

2019-10-09 14:25:10.482758 I | embed: rejected connection from "192.168.1.121:35058" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kube-ca\")", ServerName "")

**Environment information**
rancher:v2.3.0

any one can help?

**Comment by superseb** [comment]
The certificates mounted are for accessing Rancher, and they are not used for anything else. This error is 9 out of 10 times seen when the node added has not been properly cleaned from previous attempts. See https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/ what containers/directories should be removed before attempting to add it again.

If this doesn't solve the problem, please share the complete provisioning log from the container using the `rancher/rancher` image.

**Comment by shown1985** [comment]
> The certificates mounted are for accessing Rancher, and they are not used for anything else. This error is 9 out of 10 times seen when the node added has not been properly cleaned from previous attempts. See https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/ what containers/directories should be removed before attempting to add it again.
> 
> If this doesn't solve the problem, please share the complete provisioning log from the container using the `rancher/rancher` image.

Thank you , it resloved my problem!
