### ISSUE TITLE
Adding crd to installation manual

### ISSUE THREAD

**Issue by exocode** [rancher/rancher#23317]
**What kind of request is this (question/bug/enhancement/feature request):**
Manual enhancement

**Steps to reproduce (least amount of steps as possible):**
- Docker for Mac 2.1.0.3 (most recent)
- Docker for Mac built in Kubernetes activated
- follow steps here: https://rancher.com/blog/2018/2018-05-18-how-to-run-rancher-2-0-on-your-desktop/

**Result:**
Last step before adding Rancher via Helm
```
╰─ helm install stable/cert-manager --name cert-manager --namespace kube-system --wait
Error: validation failed: [unable to recognize "": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1", unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"]
```

**Other details that may be helpful:**
Found suggestion here: https://github.com/helm/charts/issues/10949#issuecomment-458466188

Fix could be `kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.6/deploy/manifests/00-crds.yaml`
(worked in my case)

**Comment by dramich** [comment]
@exocode The link you provided is for a blog post which we don't update once posted. The correct install docs for cert-manager live [here](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#optional-install-cert-manager) as part of the HA install guide.
