### ISSUE TITLE
bug menu translation

### ISSUE THREAD

**Issue by andruwa13** [rancher/rancher#23312]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.0` UI: `v2.3.15` |
|Route|`global-admin.multi-cluster-apps.index`|

<img width="1792" alt="Rancher 2019-10-09 20-50-21" src="https://user-images.githubusercontent.com/5846351/66506928-e953e080-ead6-11e9-8cd3-026ebac26c1f.png">

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24300
