### ISSUE TITLE
UI: Need UI for creating RKE templates from a existing cluster

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#23325]
This is the placeholder ticket for UI changes needed when the backed changes are ready for https://github.com/rancher/rancher/issues/22992

**Comment by tfiduccia** [comment]
Requirements:
1.  Create a item in the Cluster's menu that says "Use RKE Template"
2.  Selecting that item will bring up a modal that says: "Create & Use RKE Template", Name field, Checkbox with "Create & Edit template" label, Cancel & Create buttons.

IF checkbox is check == create another verison of template and put them in edit mode
IF checkbox is not checked  == create main version of template and put them back in cluster list.

**Comment by tfiduccia** [comment]
Updated requirements:
1.  Just prompt for the Name
2.  Automatically set template revision name to v1
3.  Take to v1 details page
4.  Add submenu to details page that will allow them to: "Disable, Clone, View in API"

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by soumyalj** [comment]
Tested with v2.3-head using UI-index latest-2.3
Feature to export a RKE template through UI from an existing cluster is functional.
The template/revision exported is displayed in the RKE templates page. Creating new revisions from the template is also functional through UI.
