### ISSUE TITLE
Imported clusters can't recover when cluster-agent is down

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#23331]
There is a logic in rancher dialer builder code where for rke clusters, when dialer fails to be built to a cluster-agent, we fall back to the node agent. It doesn't work the same way for imported clusters although they also have the node-agent running. This restriction is a legacy from times where we didn't run node-agents in imported clusters, and have to be relaxed.

Steps to reproduce for QA:

* Import cluster to Rancher
* Simulate cluster-agent failure. Can be as simple as removing cluster-agent deployment
* Try to access the cluster's projects from the UI. It fails.

The same steps work for RKE provisioned cluster.

**Comment by soumyalj** [comment]
Reproduced the issue in v2.3.0
1. Created an imported RKE cluster in Rancher
2. Deleted the cluster-agent deployment to simulate cluster-agent failure
3. Accessing the cluster's projects from UI was not possible
