### ISSUE TITLE
Support exposing istio gateway status port

### ISSUE THREAD

**Issue by n3v3rf411** [rancher/rancher#23335]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
1. Go to the cluster Istio page
2. Under Ingress Gateway, `Enable Ingress Gateway`
3. Set `Service Type of Ingress Gateway` to NodePort
4. Be able to set an optional `Status Port` in addition to `Http2 Port` and `Https Port`

**Result:**
Can call `http://<node ip address>:<status port>/healthz/ready`

**Other details that may be helpful:**
This seems to be already supported:
https://github.com/istio/istio/issues/9385

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher v2.3.0
- Installation option (single install/HA): single install

**Comment by loganhz** [comment]
As a workaround, you can do something like this to config it via custom answers


![image](https://user-images.githubusercontent.com/21168270/66693521-4c629480-ecdc-11e9-8f70-949aafc844be.png)

https://github.com/rancher/system-charts/blob/dev/charts/rancher-istio/0.1.1/charts/gateways/values.yaml#L85-L87
