### ISSUE TITLE
[forwardport] Support Istio Gateway as first class resource in Rancher UI

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#23334]
[forwardport] https://github.com/rancher/rancher/issues/20892

**Comment by bmdepesa** [comment]
Currently blocked by reopen of #23370

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 1304c55a2
ui: `vmaster-dev`

* Gateway navigation tab is shown
* All Istio navigation tabs are shown
* Imported gateways appear in UI w/ correct values
* Created gateways are functional
* Gateway inputs match resulting CRD
