### ISSUE TITLE
[forwardport] catalog app is still showing when all of the templates are hidden by max_rancher_version

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23336]
forwardport https://github.com/rancher/rancher/issues/23295

**Comment by westlywright** [comment]
Available in master.

**Comment by sowmyav27** [comment]
waiting for preview build to validate this issue.

**Comment by sowmyav27** [comment]
**Verified with rancher:v2.4.0-alpha1**

**Steps:**

- Add a catalog app: which has all of the templates hidden by max_rancher_version.
- Go to Apps --> Launch
- User will NOT be able to see the app (hidden by the rancher_max_version)
- App here is fluentd-aggregator
