### ISSUE TITLE
Rancher UI websocket connection failed after 2.3 upgrade

### ISSUE THREAD

**Issue by dnauck** [rancher/rancher#23337]
Hello,

after the upgrade from 2.2.5 to 2.3.0 i get the following error in rancher UI:

![image](https://user-images.githubusercontent.com/97584/66541243-e684da00-eb2e-11e9-9050-f100d23eeace.png)

Using latest google chrome and rancher single node install.

What else can i check / test to resolve this issue? (i've not found infos about websocket stuff in the log)

**Comment by MSandro** [comment]
Same on my RKE (0.3.0) HA Cluster ...

**Comment by adampl** [comment]
same on my Rancher 2.2.8 (single node)...

**Comment by MSandro** [comment]
Interesting, I and some other had simular issues after upgrading from 2.2.7 to 2.2.8, #22318

**Comment by adampl** [comment]
In my case it all started when I removed all nodes and then re-added them with different public and internal IP addresses (advanced options).

**Comment by kodelint** [comment]
I have been dealing with this problem,,, not sure what fixed it but I am guessing it was the security groups. All my nodes are **private**  and rancher URL is exposed using **nlb**

**Comment by alex-stout** [comment]
It seems my issue has been resolved as well. It resolved itself. Possibly a new release on the `:latest` image tag?
