### ISSUE TITLE
DataVolumeContainer id is not set on service instances sometimes

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2333]
Several people observed the problem when volumesFromContainer is not being set on the service's instances although dataVolumesFrom=<service> is set on the corresponding launch config. Happens occasionally.

**Comment by alena1108** [comment]
Fixed with d202748273f5b2f949efe142566a2601c27b50d3 (already in master). 

@sangeethah to test things:

1) create a service with one sidekick as a data service. Put start_once=true on the data service (important). Set scale 5
2) activate the service.

To verify: on the docker side, check if all containers of the "main" service has not null VolumesFrom (use "docker inspect" for it). Checking for container.dataVolumesFrom not being null on Rancher is not enough, as by some reason python agent doesn't error out when id of the container that hasn't been created yet, is passed as a data container id to another container (you can file a bug for python-agent for that)

The issue is reproducible on rancher builds prior to October 7th. Related main container not waiting for the complete data container start, before its own startup.

**Comment by sangeethah** [comment]
Tested with server version - V0.41.0

1) create a service with one sidekick as a data service. Put start_once=true on the data service (important). Set scale 10
2) activate the service.

Made sure that  docker inspect for ["HostConfig"]["VolumesFrom"] has values set and that we are able to inspect the container from this value which means that the data containers are deployed in the same container.

The above usecase succeeded multiple times.

**Comment by tobowers** [comment]
@alena1108 we are still seeing this issue on v0.42.0-rc3

**Comment by alena1108** [comment]
@tobowers let me know what the testing reveals
