### ISSUE TITLE
Enabling monitoring fails

### ISSUE THREAD

**Issue by skbki** [rancher/rancher#23347]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Newly provisioned cluster on vmware using rancheros v1.5.4
Provisioned using dhcp ipv4 only
Enabling monitoring fails

**Result:**

2019/10/10 12:00:04 [ERROR] ClusterController c-22gqw [cluster-monitoring-handler] failed with : failed to deploy etcd cert: Secret "exporter-etcd-cert" is invalid: [data[kube-etcd-fe80::250:56ff:fea7:fac9-key.pem]: Invalid value: "kube-etcd-fe80::250:56ff:fea7:fac9-key.pem": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[kube-etcd-fe80::250:56ff:fea7:fac9.pem]: Invalid value: "kube-etcd-fe80::250:56ff:fea7:fac9.pem": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')]

**Other details that may be helpful:**
I have 3 other identical clusters under this rancher install where monitoring works 

**Environment information**
- Rancher version:
v2.8.0
- Installation option:
Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
vmware integrated cluster
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
3 master vms 2cpu-4g-50g
2 worker vms 8cpu-32g-100g
- Kubernetes version (use `kubectl version`):
Version: v1.14.6
- Docker version (use `docker version`):
17.3.2

**Comment by mkostersitz** [comment]
![enable monitoring failure](https://user-images.githubusercontent.com/6709322/71679585-cce6dd80-2d7f-11ea-82d0-6e9669698539.PNG)
![enable monitoring failure expanded](https://user-images.githubusercontent.com/6709322/71679586-cce6dd80-2d7f-11ea-8410-f461ec86c178.PNG)

adding screenshots of the state after enabling monitoring
