### ISSUE TITLE
Stack removal didn't trigger services removal

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2334]
Noticed on user setup. Stack in removed state happened to have not removed services.

**Comment by alena1108** [comment]
Happens because we don't check for the stacks state while adding the service; and with concurrent stack.remove and service.create its possible to end up with orphaned stacks. Steps to reproduce @sangeethah ^^ in python test:

```
 client.create_service(name=random_str(),
                                     environmentId=env.id,
                                     launchConfig=launch_config)

    client.create_service(name=random_str(),
                                     environmentId=env.id,
                                     launchConfig=launch_config)

    env.remove()

    client.create_service(name=random_str(),
                                     environmentId=env.id,
                                     launchConfig=launch_config)
    client.create_service(name=random_str(),
                                     environmentId=env.id,
                                     launchConfig=launch_config)

```

2 last services are created successfully

**Comment by sangeethah** [comment]
#1644 - tracks this issue.

**Comment by alena1108** [comment]
@tobowers found the root cause for that buggy behavior; PR is submitted

**Comment by sangeethah** [comment]
Tested with build from master:

I am not allowed to create a service in an environment that is in "Removed" state .

Error seen - Validation failed in API: environment

API returns following error message:

{"id":"b635b012-b4f7-4d21-bc18-19d8852f546c","type":"error","links":{},"actions":{},"status":422,"code":"InvalidState","message":null,"detail":null,"fieldName":"environment"}

**Comment by sangeethah** [comment]
Tested with build from master - oct 15

When the snippet of code provided in the bug was executed , service creation after stack removal fails with following API error:

```
E       ApiError: (ApiError(...), "InvalidState : None\n{'status': 422, 'code': u'InvalidState', 'links': {}, 'detail': None, 'actions': {}, 'fieldName': u'environment', 'message': None, 'type': u'error', 'id': u'58367809-88fa-4230-bdb5-37fe781f4a52'}")
```
