### ISSUE TITLE
Feature Request: add back minasg and maxasg on Amazon EKS Cluster creation

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#23349]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Description**
In Rancher 2.3.0 DesiredASG was added but MinASG and MaxASG settings were removed.  This feature request is for the options of MinASG and MaxASG to be added back to the menu.

2.2.8 Screenshot:
![image](https://user-images.githubusercontent.com/44879867/66586345-75591d00-eb56-11e9-81fe-2b8628d6d1eb.png)

2.3.0 Screenshot:
![image](https://user-images.githubusercontent.com/44879867/66586369-7ee28500-eb56-11e9-9672-58969e9bc723.png)

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/23349 // the options were removed as a part of this fix

**Comment by cbron** [comment]
PR with more info here: https://github.com/rancher/kontainer-engine/pull/180

**Comment by cbron** [comment]
Reason for this change was that min/max weren't used post-deployment because there was no autoscaler setup, so the node count would scale up to min and then never move again. The UI now reflects how it actually works.

**Comment by patrick0057** [comment]
Thank you.
