### ISSUE TITLE
Change View/Edit YAML functionality for namespaces

### ISSUE THREAD

**Issue by kylerome** [rancher/rancher#23348]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

when i click `View/Edit YAML` on a namespace, currently it shows the YAML for all resources in the namespace which doesn't make sense from a users perspective.  

I would suggest we change this button to function like it does everywhere else in Rancher's UI, and to move the current functionality to an additional menu item called `Export Namespace Resources` or something to that effect.

**Comment by superseb** [comment]
Previous discussion in https://github.com/rancher/rancher/issues/15038
