### ISSUE TITLE
Using NodePort/HostPort mode deployment, SVC YAML still displays clusterIP mode

### ISSUE THREAD

**Issue by LincolnBruce** [rancher/rancher#23340]
**What kind of request is this (question/bug/enhancement/feature request):**
Using NodePort mode deployment, SVC YAML still displays clusterIP mode

**Steps to reproduce (least amount of steps as possible):**
Using NodePort mode deployment, SVC YAML still displays clusterIP mode

**Result:**
Using NodePort mode deployment, SVC YAML still displays clusterIP mode

**Other details that may be helpful:**
Using NodePort mode deployment, SVC YAML still displays clusterIP mode

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
Could you please provide more info about reproduce steps? Screenshots will be helpful
