### ISSUE TITLE
[Monitoring] Add Ability to Edit Prometheus Additional Scrape Configuration

### ISSUE THREAD

**Issue by toddexp** [rancher/rancher#23352]
The Prometheus additional scrape configuration is the best practice for scraping targets outside of Kubernetes.  Currently there is not a way within Rancher to configure the Prometheus additional scrape configuration. When Rancher enables the monitoring it deploys it’s own additional scrape config as a secret  “prometheus-cluster-monitoring-additional-scrape-configs” automatically. If you need to add your own configuration to what Rancher has deployed you need to edit this secret manually with kubectl. Since Rancher owns this object I am not sure if it might change this object and wipe out the custom configuration in it. 

It would be great if there was a way to edit this within Rancher preferably as a file so it could be a declarative definition.

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Enable monitoring.

**Result:**
There is no way within Rancher to edit the additional scrape configuration that Rancher owns and deploys automatically.

**Other details that may be helpful:**
For reference, Prometheus additional scrape config: https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.3.0
- Installation option (single install/HA): both

**Comment by amagura** [comment]
I'm having this issue as well: currently, I'm trying to add [node-problem-detector](https://github.com/kubernetes/node-problem-detector), however while their `/metrics` endpoints are working, I have not been able to get them to appear in Prometheus.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/23239
