### ISSUE TITLE
Azure Cloud Credentials: Wrong AzureUSGovernmentCloud Endpoint

### ISSUE THREAD

**Issue by jarett-cyxtera** [rancher/rancher#23350]
**What kind of request is this (question/bug/enhancement/feature request):** 
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a new cluster - no special options except choosing AzureUSGovernmentCloud when creating node templates, and entering AzureUSGovernmentCloud under the Kubernetes/Cloud Provider/Cloud section.

**Result:**
Node provisioning fails with error:
Error with pre-create check: "autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/my-subscription-id/oauth2/token?api-version=1.0 failed with 400 Bad Request: StatusCode=400"; Timeout waiting for ssh key

**Other details that may be helpful:**
I have verified the credentials I am using are correct, but they are only valid on the US gov cloud endpoint (login.microsoftonline.us) not the one shown in the error (.com).  I have tried multiple variations of the  Kubernetes/Cloud Provider/Cloud value but this doesn't seem to change anything, so I think it's happening earlier in the process.  There doesn't seem to be a way to mark a cloud credential as belonging to a specific cloud environment.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher v2.3.0
User Interface  v2.3.15
Helm    v2.10.0-rancher12
Machine v0.15.0-rancher12-1

- Installation option (single install/HA):
HA

**Comment by alena1108** [comment]
@kinarashah looks somewhat similar to https://github.com/rancher/rancher/issues/23060

**Comment by jarett-cyxtera** [comment]
After a bit of research I have determined that this is actually a bug in docker-machine (both the upstream and rancher/machine fork).  The issue is from an incorrect endpoint the Azure/go-autorest library being used, which is defined here:

https://github.com/rancher/machine/blob/master/vendor/github.com/Azure/go-autorest/autorest/azure/environments.go

The Auzre/go-autorest version is locked at 7.2.1 which is fairly ancient.

The fix on the Azure side (9.7.1):
https://github.com/Azure/go-autorest/commit/6311d7a76f54cf2b6dea03d737d9bd9a6022ac5f

Hacking in the correct endpoints and rebuilding resolves the issue (tested).  Updating to a fixed version of go-autorest (9.7.1) is going to take a little more work as other things have changed.  Updating to the current version (13.1.0) will require some significant work.

**Comment by deniseschannon** [comment]
@kinarashah can you help move this community PR though our review process?

**Comment by luthermonson** [comment]
@jarett-cyxtera just an fyi if youre still looking for this https://github.com/rancher/machine/pull/72 will ultimately include the azure sdk and autorest uplifts

**Comment by kinarashah** [comment]
Available to test in `2.4.3-rc1`

**Comment by maggieliu** [comment]
@jarett-cyxtera will you be able to help with testing the latest `2.4.3-rc1` and see if this issue has been fixed or not?

**Comment by maggieliu** [comment]
Closing it for 2.4.3 release. We can reopen if the issue persists.
