### ISSUE TITLE
[Monitoring] Add Ability to Edit Alerts as a File

### ISSUE THREAD

**Issue by toddexp** [rancher/rancher#23351]
It would be great to have the ability to edit alerts as a file. Editing the alerts as a file would allow for the definitions to become declarative. The alert config could be stored and then pasted in.

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Enable monitoring.
In the alerts section edit an existing alert (or make a new one).

**Result:**
The alert can only be edited in the GUI. There is no option for editing the alert as a file.

**Other details that may be helpful:**
The edit as a file option is available in other sections of Rancher such as deploying an app or the logging section.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.3.0
- Installation option (single install/HA): both

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24215
