### ISSUE TITLE
UI- RKE Templates: Create Cluster shows Empty KubernetesVersion dropdown when a cloned revision is chosen

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#23361]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug reported by a user

**Steps to reproduce (least amount of steps as possible):**
- Create a new RKE Template and choose the KubernetesVersion: "Latest v1.16 (allows patch version upgrades)(experimental)" - NO override. This is saved as revision "v1"
- Now Clone a New Revision "v2" from the default and make sure to choose the  KubernetesVersion: "Latest v1.16 (allows patch version upgrades)(experimental)" - Allow override. 

- Go to Add Cluster, set all node-template, clustername and other required paremeters and choose this template from the dropdown to create the cluster
- Choose the second revision "v2" from the Revisions drop-down
- The "Kubernetes Version" dropdown shown on the create cluster UI form shows as Empty after the "v2" revision is chosen.

- Screenshot added showing the empty dropdown

<img width="990" alt="Screen Shot 2019-10-10 at 2 45 00 PM" src="https://user-images.githubusercontent.com/1470602/66610757-73508780-eb71-11e9-9235-b28eade3c712.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0
- Installation option (single install/HA): single node

**Comment by soumyalj** [comment]
Tested with rancher version v2.3.1-rc2. 
1. Create a new RKE Template and choose the KubernetesVersion: "Latest v1.16 (allows patch version upgrades)(experimental)" - NO override. This is saved as revision "v1"
2. Clone a New Revision "v2" from the default and make sure to choose the KubernetesVersion: "Latest v1.16 (allows patch version upgrades)(experimental)" - Allow override.
3. Go to Add Cluster, set all node-template, clustername and other required paremeters and choose this template from the dropdown to create the cluster
Choose the second revision "v2" from the Revisions drop-down . The k8s version dropdown is not empty. K8s version is displayed and we can also choose other versions

![Screen Shot 2019-10-12 at 7 49 54 PM](https://user-images.githubusercontent.com/18536626/66710264-a2a9f480-ed29-11e9-9580-23e9787afd0e.png)

There were no errors in the Console.  This use case was tested several times.

**Comment by ragaar** [comment]
For the sad souls that stumble into this:
https://github.com/rancher/rancher/issues/24091
