### ISSUE TITLE
New single-node rancher installs using let's encrypt fail

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#23365]
If you use the Let's Encrypt certificate option for single node rancher installs, it will fail. I'm referring to the Let's Encrypt option specified in this doc:
https://rancher.com/docs/rancher/v2.x/en/installation/single-node/

The cause of this is that Let's Encrypt is EOLing their v1 API. This is detailed here:
https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

And a schedule of "brown outs" is detailed here:
https://calendar.google.com/calendar/embed?src=letsencrypt.org_caqskun93lgiabjj4ba9cb1rek%40group.calendar.google.com

You see this error:
```
2019/10/10 23:33:10 [INFO] 2019/10/10 23:33:10 http: TLS handshake error from 63.232.146.98:58877: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

**Comment by cjellick** [comment]
@drpebcak found this, so just tagging him here.
The wording seems to indicate that _existing_ installs should continue to work until we have a fix, but we don't have a great way of verifying that.

**Comment by cjellick** [comment]
Upstream: https://github.com/golang/go/issues/21081

**Comment by codejamninja** [comment]
I'm having the same problem

https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

**Comment by jmhodges** [comment]
I don't use rancher, but I poked around since this ticket[1] was linked to another I answered on. It looks like the current autocert code rancher uses doesn't make this easy to workaround. 

If I've understood the code correctly, rancher relies on `autocert.Manager` to create the `acme.Client`, but, by default, it uses the constant for the API URL that's currently not been updated (see [1] again).

So, rancher will have to learn how to create it's own `acme.Client` and set the DirectoryURL like I describe in [a comment on the other ticket](https://github.com/golang/go/issues/21081#issuecomment-540855037). It'll also have to handle not reusing v01 accounts (if it saves the keys for them) because those accounts won't work in v02.

[1] https://github.com/golang/go/issues/21081

**Comment by codejamninja** [comment]
Just curious, but why is this being worked on now when letsencrypt scheduled to deprecate it today?

**Comment by alena1108** [comment]
@jmhodges thanks for following up on the upstream ticket. 

There is a pending pr https://go-review.googlesource.com/c/crypto/+/199520, will pull/vendor it in and give it a test

**Comment by codejamninja** [comment]
@alena1108 did it work?

**Comment by sowmyav27** [comment]
Reproduced the issue in `rancher:v2.3.0`

Bring up rancher server using command
```
docker run -d --restart=unless-stopped   -p 80:80 -p 443:443   rancher/rancher:v2.3.0   --acme-domain <domain>
```

Error seen in logs:
```
2019/10/11 17:28:05 [INFO] 2019/10/11 17:28:05 http: TLS handshake error from 63.205.203.156:24988: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

On `rancher:v2.3-head`
Steps:
- Bring up rancher server using command
```
docker run -d --restart=unless-stopped   -p 80:80 -p 443:443   rancher/rancher:v2.3-head   --acme-domain <domain>
```

**Comment by sowmyav27** [comment]
**On `rancher:v2.3-head` - latest**

**Steps:**

- Bring up rancher server using command
- docker run -d --restart=unless-stopped   -p 80:80 -p 443:443   rancher/rancher:v2.3-head   --acme-domain <domain>
- The server is up and running.
- User is able to access the URL. No errors seen in the logs.
- Deployed an rke cluster and automation run - all pass.

**Comment by codejamninja** [comment]
Works great! thanks
