### ISSUE TITLE
UI- RKE Templates: Create cluster using an RKE Template for Latest v1.16 fails with API validation error

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#23360]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug reported by a user 

**Steps to reproduce (least amount of steps as possible):**
- Create a new RKE Template  and choose the KubernetesVersion: "Latest v1.16 (allows patch version upgrades)(experimental)" - NO override.
- Go to Add Cluster, set all node-template, clustername and other required paremeters and choose this template from the dropdown to create the cluster
- Click "Create"
- Create fails and you get API validation error. Error message as shown in the screenshot
- This usecase also reproduces for an RKE Template for Latest v1.15.x Kubernetes Version.

**Result:**
- Cluster cannot be created 

<img width="1018" alt="Screen Shot 2019-10-10 at 2 12 41 PM" src="https://user-images.githubusercontent.com/1470602/66610224-d0e3d480-eb6f-11e9-996c-f3812675d347.png">

**Other details that may be helpful:**
- This usecase fails intermittently - some timing issue involved - create a cluster immediatey after adding the new template

- HTTP traffic captured shows that the "answers" sent by UI contain the "rancherkubernetesconfig.kubernetesVersion" as incorrect value due to which API validation fails.

<img width="931" alt="Screen Shot 2019-10-10 at 2 11 59 PM" src="https://user-images.githubusercontent.com/1470602/66610283-f7097480-eb6f-11e9-8e43-f5c3f8353a58.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0
- Installation option (single install/HA): single fresh install

**Comment by soumyalj** [comment]
Tested with rancher v2.3.1-rc2. 
Create a new RKE Template and revision R1 and choose the KubernetesVersion: "Latest v1.16 (allows patch version upgrades)(experimental)" - NO override.
Create cluster with revision R1
Cluster creation was successful with no errors. 

This use case was tested with K8s version with Latest v1.15, Latest  v1.14 . No errors were observed . K8s version was correctly sent through the UI.

![Screen Shot 2019-10-12 at 8 37 24 PM](https://user-images.githubusercontent.com/18536626/66711007-5e722080-ed38-11e9-947c-8e6c61c99c1d.png)

![Screen Shot 2019-10-12 at 8 41 58 PM](https://user-images.githubusercontent.com/18536626/66711008-68941f00-ed38-11e9-889f-868d82d44e28.png)

![Screen Shot 2019-10-12 at 9 25 12 PM](https://user-images.githubusercontent.com/18536626/66711011-6df16980-ed38-11e9-930d-4b0d141ecb08.png)
