### ISSUE TITLE
[UI] In mcapp answers keys included dots don't apply values but make them empty

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#23379]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
 - create multi cluster app with answers keys included points:
   normalKey: value
   NormalKey2: value2
   lost.key: value1
   lost.key.value: value1
![Screenshot (62)](https://user-images.githubusercontent.com/4653589/66657280-3dca9d80-ec48-11e9-94cb-300c86b3dab1.png)

- deploy app in another project

**Result:**
- UI send all keys, but keys with point send empty value ""
![Screenshot (63)](https://user-images.githubusercontent.com/4653589/66657291-40c58e00-ec48-11e9-8d9c-abecffa13284.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version: 2.3.0
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): ANY
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM/4cpu/8gb
- Kubernetes version (use `kubectl version`): v1.15.4
- Docker version (use `docker version`): ANY

**Comment by sowmyav27** [comment]
@Negashev Can you give us more information on how you deployed the multi cluster app, which page in the Rancher UI was used to deploy it, as I am unable to see `Answers` section on my rancher setup for an mcapp.

**Comment by Negashev** [comment]
@sowmyav27 stolon chart from official (and another helm repos):
Global | helm | https://kubernetes-charts.storage.googleapis.com/

**Comment by sowmyav27** [comment]
Reproduced the issue on rancher:v2.3.0

**Steps:**

- On rancher:v2.3.0 - single node
- Add a catalog: 
- Launch a mcapp - Stolon
- Add answers:

```
test1: value1
test2.key: value2
test3: value3
test4.key: value4
```

- Select a target, name. And click on Launch
- In the request, UI Send the answers as:

```
values: {test1: "value1", test2.key: "", test3: "value3", test4.key: ""}
test1: "value1"
test2.key: ""
test3: "value3"
test4.key: ""
```

**Comment by Negashev** [comment]
it's repeated deeper
```
test5.deep.key: ""
test5.deep.and.deep.key: ""
```

**Comment by Negashev** [comment]
Rancher CLI work normal

**Comment by sowmyav27** [comment]
Verified on master-head - commit id: `8d57a1cfb`
UI-index: `latest2`

**Steps:**

- On rancher:v2.3.0 - single node
- Add a catalog: URL: https://github.com/helm/charts.git
- Launch a mcapp - Stolon
- Add answers:

```
test1=value1
test2.key=value2
test3=value3
test4.key.one=value4
```

- Select a target, name. And click on Launch
- In the request, UI Send the answers as:
```
values: {test1: "value1", test2.key: "value2", test3: "value3", test4.key.one: "value4"}
test1: "value1"
test2.key: "value2"
test3: "value3"
test4.key.one: "value4"
```
- View in API:
```
"answers": [
{
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer",
"values": {
"test1": "value1",
"test2.key": "value2",
"test3": "value3",
"test4.key.one": "value4"
}
}
],
```
