### ISSUE TITLE
Can not create k8s cluster on cn-northwest-1 on release 2.3.0

### ISSUE THREAD

**Issue by linbingdouzhe** [rancher/rancher#23373]
hi team .
    i have been a long time to wait release 2.3.0 ,because i can not create cluster on cn-northwest-1 .... 
    now 2.3.0 is released , but look like no different ...still can not create cluster on cn-northwest-1,i use rancheros and ssh user is "rancher", it can be create ec2 machine on aws when i choose  amazon ec2 .but it will be stuck on "Waiting for SSH to be available..." i have to wait a long time ~ finally , it 's have nothing change about ec2 machine , still waitting for ssh (i do the same action on cn-north-1 , it's normal .) . And the ec2 machine still on my console when i delete the rancher cluster  :(
    So dose the bug still in here ? 
@loganhz

**Comment by loganhz** [comment]
The origin issue is https://github.com/rancher/rancher/issues/19379

@kingsd041 can you try again?

**Comment by linbingdouzhe** [comment]
i change my ec2 type from t3a.small to t2.small , it working now . (at least will not stuck on waitting for ssh )
but i am facing another problem ,the log is 


"2019/10/11 08:16:54 [ERROR] NodeController c-vbd89/m-78xxl [node-controller] failed with : Unable to find image 'rancher/rancher-agent:v2.3.0' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
Process exited with status 125
: exit status 1"

it will be relaunch ec2 machine  agian and again .... still the same error log ..
Into an infinite loop

So i have to login the ec2 server pull the images by manually , it doesn't work too  :(
more information : 

[root@ranchertesttest1 ~]# docker pull rancher/rancher-agent:v2.3.0




error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/images/create?fromImage=rancher%2Francher-agent&tag=v2.3.0: EOF
[root@ranchertesttest1 ~]#
[root@ranchertesttest1 ~]#
[root@ranchertesttest1 ~]#
[root@ranchertesttest1 ~]#
[root@ranchertesttest1 ~]# docker pull rancher/rancher-agent:v2.2.8





^C
[root@ranchertesttest1 ~]# docker pull rancher/rancher-agent:stable
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[root@ranchertesttest1 ~]# docker version
Client: Docker Engine - Community
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:38:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd87f
  Built:            Wed Jul 17 17:48:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by linbingdouzhe** [comment]
forgive me .. this problem is about my os problem (can not docker pull)

**Comment by loganhz** [comment]
Cool. Thanks for the feedback.
