### ISSUE TITLE
[Forwardport] [UI] Support Istio Gateway as first class resource in Rancher UI #20892 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23370]
Forwardport https://github.com/rancher/rancher/issues/23302

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 781cd0fdc
ui: latest2

When trying to access the Istio Gateway UI, there is an error 'Cannot read property 'authenticated.project' of undefined'

![Screen Shot 2019-11-26 at 2 59 02 PM](https://user-images.githubusercontent.com/21316915/69677383-0d0bbf80-1060-11ea-8f17-dcfd3b57982c.png)

* Create a cluster
* Enable Istio
* Navigate to a project's Istio dashboard
* Click on 'Gateways'

**Comment by bmdepesa** [comment]
rancher/rancher:master-head
ui: `vmaster-dev`

* Gateway navigation tab is shown
* All Istio navigation tabs are shown
* Imported gateways appear in UI w/ correct values
* Created gateways are functional
* Gateway inputs match resulting CRD
