### ISSUE TITLE
namespace is not being created in a project

### ISSUE THREAD

**Issue by dbones** [rancher/rancher#23376]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug / Question

**Steps to reproduce (least amount of steps as possible):**

- on a new rancher setup, with a cluster registered and nothing in the default project
- log in via via the rancher CLI (using a non-scoped token)
- on your computer create a folder to run the following yaml files
- download the yaml files from here: https://github.com/dbones-simple-shop/infra/tree/master/k8s
- run "rancher kubectl apply -f ."

**Result:**

- The namespace is created but  "Not In a Project" - see below
- the workloads are always in the default project in a namespace called default - see below

![image](https://user-images.githubusercontent.com/183849/66585296-7e5de480-eb7e-11e9-958c-0ac2768a5f73.png)

![image](https://user-images.githubusercontent.com/183849/66641340-751e5780-ec12-11e9-9fe7-32639e9a2a67.png)

**Other details that may be helpful:**

if we put all the Yaml into a single file, workloads do not show in rancher initially (they do not show anywhere, we can see them via kubectl)

if we move the data namespace into a project, then all workloads appear. 

**Environment information**
- Rancher version: 2.3.0
- Installation option (single install/HA): single (using both clusters where setup via Vagrant on VirtualBox)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom (using the rancher wizzard to setup the network)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Virtual box, Rancher 2Gb and 1 Node 6gb Ram
- Kubernetes version (use `kubectl version`): 1.15.4

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): tested it with 2 verisions

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:29:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

we initial were using this, and then upgraded to the above:

```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by dbones** [comment]
we have tried 

```rancher kubectl annotate namespace data field.cattle.io/projectId=c-9t2mr:p-dw8t6```

this moves the namespace into the project, however if we run the other files as is these still do not associate with the namespace.  (slightly confused)

if we apply the annotation inside the Yaml this does not work (https://github.com/rancher/rancher/issues/14382)


rancher associate namespace does not exist (https://github.com/rancher/rancher/issues/15474)


as we are running in the CLI, and had to choose a project, it would be excellent not have have to include it

**Comment by gabrielcalderon** [comment]
This also happens if you create a namespace via Kubectl, helm, etc. It has been happening for months but rancher has not fix it.

Solution is easy: Rancher should create any new Namespace in the Default Project unless specified.

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/16493, the command `rancher namespaces associate` was changed to `rancher namespaces move`

**Comment by dbones** [comment]
hey, before we close this can we confirm why the yaml files do not associate with the data namespace

> this moves the namespace into the project, however if we run the other files as is these still do not associate with the namespace. (slightly confused)

**Comment by gabrielcalderon** [comment]
@superseb That does no help for people NOT using rancher cli. 

We currently use kubectl/helm from within gitlab-ci and we can't cannot create dynamic namespaces becuase Rancher creates the namespace with NO project associated.

If Rancher is adding this custom "Project" layer it should assing default values. We spent an hour debugging why our workloads didnt show up in the UI but did in kubectl, turns out it was because of the project association in Rancher.

**Comment by ahmedwaleedmalik** [comment]
I agree with @gabrielcalderon. For our set-up till now we don't really need rancher cli but associating a namespace with a project is adding a redundant dependency. Cluster id is retrievable but to retrieve project id we need cli/api. 
The current annotation `field.cattle.io/projectId=c-9t2mr:p-dw8t6` needs to be tweaked a bit to remove this dependency. Since duplicate project names are not allowed anyways something like this should be possible: 
`field.cattle.io/projectId=c-9t2mr:projectName` or even `field.cattle.io/projectId=clusterName:projectName`

**Comment by ahmedwaleedmalik** [comment]
Any update on this ? This is literally a big blocker, since logging in via scoped(to a certain cluster) api key is not even possible using rancher CLI. 
`FATA[0000] Bad response statusCode [401]. Status [401 Unauthorized]. Body: [message=clusterID does not match] from [https://rancher.stakater.com/v3] `

So, we'll have to first write a script to retrieve the clusterId, then use rancherCLI to retrieve projectId, JUST for project association that shouldn't even be a requirement. Since, by default all namespaces should be associated with "default" project or else the annotation  `field.cattle.io/projectId` should be able to handle it in a better way !
@superseb  sorry but had to tag you here, since i don't know about other concerning person that i could refer this issue to.

**Comment by Ronsevet** [comment]
This a huge issue, and basically a blocker from using Rancher in a CD flow

**Comment by atsai1220** [comment]
We use Jinja templates to deploy our workloads by utilizing environment variables to dictate where namespaces are living. rancherproject has the format "<clusterid>:<projectid>". We also use Kubeconfig to access our clusters for our service accounts.


```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: {{ userid }}
  name: {{ userid }}
  annotations:
    field.cattle.io/projectId: {{ rancherproject }}
```

**Comment by curieux** [comment]
Not sure why this was closed.   This still occurs in v1.20.8+rke2r1

**Comment by gaby** [comment]
@superseb This is still an on-going issue. It happens with Rancher 2.5.9 and latest k8s versions.

We need a way to either create Projects via YAML, or specify Projects via Name not ID.

**Comment by gaby** [comment]
@atsai1220 That only works if you go digging into Rancher for the project ID, it should work with just the name... Since they are unique.

**Comment by atsai1220** [comment]
> @atsai1220 That only works if you go digging into Rancher for the project ID, it should work with just the name... Since they are unique.

Would the annotation look like this?
`field.cattle.io/projectName: {{ projectName }} `

**Comment by gaby** [comment]
> > @atsai1220 That only works if you go digging into Rancher for the project ID, it should work with just the name... Since they are unique.
> 
> Would the annotation look like this?
> `field.cattle.io/projectName: {{ projectName }} `

I'm suggesting it should work with the project name, but it doesn't. Rancher expects you to use the Rancher cli for these kind of stuff, no idea why.

**Comment by bstrdsmkr** [comment]
More than a year later, this is still a problem :(

**Comment by princeba84** [comment]
Hi, Do we have some update on this. For me it is still not possible to create namespace using yaml manifest using suggested annotation (field.cattle.io/projectName: {{ projectName }} )  . User trying to do this has project-owner role assigned which should normally allow to create namespaces .

**Comment by princeba84** [comment]
Thanks but even with projectId ,it does not work and throws an error about RBAC which should not be the case if the user has been assigned a project-owner role.

**Comment by bstrdsmkr** [comment]
Back when I dug into this, we opened a ticket with support and they basically said it was unsupported, which was infuriating :(

In our case, we were able to use Helmfile's support for hooks to call the rancher API to ensure the Namespace was associated with the project which is pretty dirty, but hopefully it helps you find an alternative.

IIRC from the investigation, the RBAC error is bc the user needed some permission on the management cluster, not the target cluster. It's been a while so I'm short on details, but maybe that gives you a lead to investigate?

**Comment by keriisan** [comment]
The information is available in the "local" cluster. Here is a short bash script which dumps the "displayName: projectId" for projects. The kubectl context must be local to run this:
```shell
#!/bin/bash
set -euo pipefail
cluster_list=( $(kubectl get ns -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep "c-m-") )
for cluster in "${cluster_list[@]}"; do 
  echo -e "\ncluster: ${cluster}"
  kubectl get -n "${cluster}" projects -o jsonpath='{range .items[*]}{.spec.displayName}{":"}{.metadata.name}{"\n"}{end}'
done
```
