### ISSUE TITLE
Oracle Linux - Standard AMI has default firewall rules that block Helm's communication

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23384]
Enhancement 

The standard OEL image  In AWS (AMI: `OL7.6-x86_64-HVM-201` `ami-062fed7f76f714d8d`) has REJECT rules that stop Helm from communicating to tiller when installing Rancher in HA mode. 
Here is the default iptable in the instance
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:ssh
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

My temporary workaround is to drop all the rules before installing Docker.
We should document the required ports and firewall rules (if possible) for installing Rancher in HA mode.

**Comment by deniseschannon** [comment]
@catherineluse please work with @paraglade to get the correct firewall rules.
