### ISSUE TITLE
Rancher Kubeconfig is missing Certificate Authority with self-signed certs

### ISSUE THREAD

**Issue by aperullo** [rancher/rancher#23380]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

I have a rancher HA cluster running with self-signed certs and a CA:
```
> kubectl -n cattle-system create secret tls tls-rancher-ingress --cert={{path}}/tls.crt --key={{path}}/tls.key

> kubectl -n cattle-system create secret generic tls-ca --from-file=certs/cacerts.pem

> helm install rancher-latest/rancher --name rancher --namespace cattle-system --set hostname=ranch.my.test --set ingress.tls.source=secret
```
Then I provision a cluster from the UI using the custom nodes option and they join with the command:
```
> sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run -v /cacerts.pem:/etc/ssl/certs/ca-certificates.crt rancher/rancher-agent:v2.3.0 --server https://ranch.my.test --token <token> --etcd --controlplane --worker
```
The cluster comes up successfully. I then try to get he kubeconfig from rancher's UI, and I see that it is **missing the CA data**. Also the `launch kubectl` option won't work either.

**Kubeconfig:** Notice how **stage4** is missing the CA data section
![noCA](https://user-images.githubusercontent.com/18688190/66658323-418dfe00-ec0f-11e9-9192-fa06e9759591.png)

**Kubectl**:
![kubectl](https://user-images.githubusercontent.com/18688190/66658443-7bf79b00-ec0f-11e9-910a-11bc08157332.png)

I've been able to recreate this problem even after creating completely new VMs, rancher HA cluster, and stage4 cluster

Why is this happening and how can I fix it?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom from existing nodes
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMs running CentOS with 16gb ram each/
- Kubernetes version (use `kubectl version`): Server version v1.14.6 

- Docker version (use `docker version`):
```
Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
```

**Comment by superseb** [comment]
At https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#certificates-from-files, it states:

```
Set hostname and set ingress.tls.source to secret.
If you are using a Private CA signed certificate , add --set privateCA=true to the command shown below.
```

You also shouldnt need to mount the cert into the agent as its retrieved from Rancher on start and used to connect to Rancher.

Let me know if that doesn't solve the issue.
