### ISSUE TITLE
Validate cert-manager chart

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#23385]
Validate cert-manager chart using

2.2.x with k8s 1.15
2.3.x with k8s 1.16

https://github.com/rancher/charts/tree/cert-manager

**Comment by sowmyav27** [comment]
**Verified on latest 2.3-head**

Catalog: https://github.com/rancher/charts/tree/cert-manager

On k8s1.16 cluster - 
Deployed cert manager - v0.9.0 in `Systems` Project under `kube-system` (only allowed to be deployed in kube-system namespace.

**On 2.2-head - latest**

- on k8s 1.15 cluster
- deployed cert manager - `v 0.5.2` under project `Default`.
- Upgrade app version to `0.9.0`.
- The app goes into installing state.
- 2 workloads - `kube-system-cainjector` and `kube-system-cert-manager` are created in Default namespace in Default project.
- When you click on Upgrade/edit workload, you can see, for the app

```
Required Namespace
kube-system
```

**Comment by sowmyav27** [comment]
Verified on latest 2.3-head

Updated Catalog: https://github.com/rancher/charts/tree/cert-manager

On k8s1.16 cluster -

- Deployed cert manager - v0.9.1 in Systems Project under kube-system (only allowed to be deployed in kube-system namespace.
- The app gets deployed successfully. All the workloads get deployed successfully. - kube-system-cainjector, kube-system-cert-manager and kube-system-webhook

Verified on latest 2.2-head

Updated Catalog: https://github.com/rancher/charts/tree/cert-manager

On k8s1.15 cluster -

- Deployed cert manager - v0.9.1 in Systems Project under kube-system (only allowed to be deployed in kube-system namespace.
- The app gets deployed successfully. All the workloads get deployed successfully. - kube-system-cainjector, kube-system-cert-manager and kube-system-webhook

**Comment by guangbochen** [comment]
cert-manager `v0.9.1` it is required to be deployed to the `kube-system` namespace so testing with another namespace like `Default` will cause error message as below:
```
Failed to install app kube-system. Error: UPGRADE FAILED: no APIService with the name "v1beta1.admission.certmanager.k8s.io" found
```

**Comment by deniseschannon** [comment]
@sowmyav27 @sangeethah 

Please validate:

1. If we deploy the cert-manager in kube-system using v0.5.2, can it be upgraded without an issue?
2. Fresh install of v2.3.x only shows v0.9.1 available. 
3. The description in the readme shows the upgrade notes for v0.9.1

**Comment by sowmyav27** [comment]
Verified the below scenarios

In a fresh install of `2.3.0-rc2`,
- Add catalog: `https://github.com/rancher/charts/tree/cert-manager`
- Go to Cluster --> Project --> Apps --> Only v0.9.1 is available.
<img width="1367" alt="Screen Shot 2019-10-14 at 9 28 22 AM" src="https://user-images.githubusercontent.com/26032343/66767377-2288a980-ee65-11e9-8191-cbc4b41352f7.png">

**Comment by sangeethah** [comment]
From @sowmyav27's testing:

```
Scenario#1
In 2.2.8, Default project - cert-manager namespace
upgrade rancher to 2.2-head.
Upgrade app to 0.9.1. Namespace says `Required namespace: kube-system` and not given as an option to modify
App comes up active

Scenario#2
In 2.2.8 under System project - deployed app in kube-system namespace (manually select this namespace. Default is cert-manager)
Upgrade rancher to 2.2-head
Upgrade app to 0.9.1. Namespace says `Required namespace: kube-system` and not given as an option to modify
App comes up active

Scenario#3
In 2.2-head
Kube-system - deploy app v0.5.2
Upgrade app to 0.9.1. The app becomes Active

Scenario#4
In 2.2.8 under System project - deployed app in cert-manager namespace.
Upgrade rancher to 2.2-head
Upgrade app to 0.9.1. Namespace says `Required namespace: kube-system` and not given as an option to modify
App fails to come up. Error: Failed to install app cert-manager. Error: UPGRADE FAILED: timed out waiting for the condition
```

**Comment by sangeethah** [comment]
@guangbochen Why does `Scenario#4` fail when `Scenario#1` succeeds ?

**Comment by guangbochen** [comment]
@sangeethah @sowmyav27  both `Scenario #4 & #2` should be working, I can't reproduce the case 4 and since the error message `Error: UPGRADE FAILED: timed out waiting for the condition`
could be a random network issue, can u please test it few more times and keep the env for me to check if you can reproduce it, thanks.

**Comment by deniseschannon** [comment]
Due to the changes to cert-manager, we will not be updating cert manager application at this time. 

 https://forums.rancher.com/t/update-on-cert-manager-application-in-the-catalog/15598
