### ISSUE TITLE
UI- RKE Templates: Updating Cluster to a new RKE Template Revision does not take into effect

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#23383]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug - from a user 

**Steps to reproduce (least amount of steps as possible):**
1. Create a new RKE Template with Revision R1- Set some settings say 
"Node Port Range: 30000 - 32767" and "Docker Root Directory: /var/lib/docker123"
2. Clone a new Revision R2 and set these values to
"Node Port Range: 30000 - 32769" and "Docker Root Directory: /var/lib/docker678"

3. Add a Cluster C using the RKE Template Revision R1. Wait for the cluster to become active. Verify that the cluster is tied to the correct Revision R1.
4. Edit the Cluster and switch to the Revision R2. Click Save.
5. Cluster does not get updated with new settings, the RKETemplate Revision tied to the Cluster still remains the same - R1
6. It is seen that the new clustertemplaterevision Id is not sent to the backend in cluster update request.

Note that if there are any settings in the new revision that are set as "overrides" or questions, upon updating the cluster, these settings get updated because the new values are being sent to the backend in the "answers" field of the update cluster API call.

**Result:**
Cluster is not updated to new revision.

**Other details that may be helpful:**
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0
- Installation option (single install/HA): single

**Comment by sangeethah** [comment]
This is very similar to the issue that was fixed earlier - https://github.com/rancher/rancher/issues/22920

**Comment by soumyalj** [comment]
Tested with v2.3.1-rc1. The above test case was tested and worked successfully. Also, the below test cases were tested :
1. Create a RKE template T1 
   Create revision R1 with K8s version fixed (v1.14.7-rancher1-1)    
   Create revision R2 as a new revision from default with K8s version fixed (v1.15.4-rancher1-2) 
   and node port range and docker directory set   
   Create cluster with R1.   
   Edit cluster and change revision to R2
   Cluster goes to updating state and updates the cluster K8s version to v1.15.4 as expected
2. Create a RKE template T1 
   Create revision R1 with K8s version set as override (v1.14.7-rancher1-1)    
   Create revision R2 as a new revision from default with K8s version set as override (v1.15.4-rancher1-2) and node port range and docker directory set   
   Create cluster with R1.   
   Edit cluster and change revision to R2
   Cluster goes to updating state and updates the cluster K8s version to v1.15.4 as expected
3. Create a RKE template T1 
   Create revision R1 with K8s version set as override (v1.14.7-rancher1-1)    
   Create revision R2 as a new revision from default with K8s version fixed (v1.15.4-rancher1-2) 
   and node port range and docker directory set   
   Create cluster with R1.   
   Edit cluster and change revision to R2
   Cluster goes to updating state and updates the cluster K8s version to v1.15.4 as expected
4. Create a RKE template T1 
   Create revision R1 with K8s version fixed (v1.14.7-rancher1-1)    
   Create revision R2 as a new revision from default with K8s version set as override (v1.15.4-rancher1-2)  and node port range and docker directory set   
   Create cluster with R1.   
   Edit cluster and change revision to R2
   Cluster goes to updating state and updates the cluster K8s version to v1.15.4 as expected

The same tests were repeated with creating R2 as a clone of revision R1
