### ISSUE TITLE
javascript error on "Add notifier", from the "Tools > Notifiers" menu

### ISSUE THREAD

**Issue by pierredavidbelanger** [rancher/rancher#23389]
*Describe your issue here*

I get a javascript error when I click on "Add notifier", from the "Tools > Notifiers" menu in a cluster.

```
Uncaught Error: Property set failed: object in path "function(t,n,i,a,o){var s=3===arguments.length?(0,r.meta)(t):a
e.setup(t,n,i,s)
var l,u,c={enumerable:e.enumerable,configurable:e.configurable,get:(l=n,u=e,function(){return u" could not be found.
    at metal.js:3086
    at Object.tt [as set] (metal.js:3007)
    at schema.js:78
    at Array.forEach (<anonymous>)
    at n.getCreateDefaults (schema.js:77)
    at n.createRecord (store.js:946)
    at n.setModel (component.js:178)
    at n.init (component.js:73)
    at n [as init] (utils.js:365)
    at b (core_object.js:89)
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3-head` UI: `v2.3.12` |
|Route|`undefined`|

**Comment by n313893254** [comment]
@pierredavidbelanger Sorry I cannot reproduce in version `v2.3.0`, but I can reproduce in `master-head`.

**Comment by n313893254** [comment]
Change milestone to v2.4 because the UI version is `v2.3.12`, which is the master branch.

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher:master-head with the UI index `https://releases.rancher.com/ui/latest2/index.html`

Result:

There is no error in the console log when clicking on the `Add Notifier` button from the `Tools` -> `Notifiers` menu in a cluster.
