### ISSUE TITLE
[backport] New single-node rancher installs using let's encrypt fail

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#23391]
Backport the fix for https://github.com/rancher/rancher/issues/23365

**Comment by sowmyav27** [comment]
verified on 2.2-head - commit id: `40154cff`
Automation run was good.

**Comment by sowmyav27** [comment]
**Reproduced the issue on rancher:v2.2.8**

- Bring up the rancher server using command:
```
docker run -d --restart=unless-stopped   -p 80:80 -p 443:443   rancher/rancher:v2.2.8   --acme-domain <domain>
```
- The rancher server URL is not accessible.
- Error seen in logs:
```
2019/10/17 00:43:23 [INFO] 2019/10/17 00:43:23 http: TLS handshake error from 76.102.13.123:52537: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

**Verified on v2.2.9 and it works fine**
- Bring up the rancher server using command:
```
docker run -d --restart=unless-stopped   -p 80:80 -p 443:443   rancher/rancher:v2.2.9   --acme-domain <domain>
```
- The rancher server URL is accessible and the rancher server is up and accessible.
