### ISSUE TITLE
[forwardport] New single-node rancher installs using let's encrypt fail

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#23392]
Forward port https://github.com/rancher/rancher/issues/23365

**Comment by aaronRancher** [comment]
The feature is validated in `rancher\rancher:master-head` `version 1df888a33`.

- Bring up rancher server using command
- `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:v2.3-head --acme-domain <domain>`
- The server is up and running.
- User is able to access the URL. No errors seen in the logs.
- Deployed an RKE cluster.
