### ISSUE TITLE
Rancher doesn't work with arm32v7 (Raspberry Pi4 Cluster)

### ISSUE THREAD

**Issue by iMerica** [rancher/rancher#23397]
Hi, I just imported a  k3s RasPi 4 cluster into Rancher and it's stuck in pending state. It looks like it's stuck "pending" because of an image pulling error.

```
kubectl get pods --all-namespaces
```

```
NAMESPACE       NAME                                   READY   STATUS             RESTARTS   AGE
cattle-system   cattle-cluster-agent-5d5c498cf-mbt28   0/1     ImagePullBackOff   0          32m
cattle-system   cattle-node-agent-5w2dw                0/1     ImagePullBackOff   0          32m
cattle-system   cattle-node-agent-j5wv6                0/1     ImagePullBackOff   0          32m
cattle-system   cattle-node-agent-npt96                0/1     ImagePullBackOff   0          32m
cattle-system   cattle-node-agent-sfqlb                0/1     ImagePullBackOff   0          32m
kube-system     coredns-b7464766c-hqw8t                1/1     Running            2          48m
kube-system     helm-install-traefik-lrh2z             0/1     CrashLoopBackOff   9          48m
```

```
kubectl get events --all-namespaces
```

```
NAMESPACE       LAST SEEN   TYPE      REASON                    OBJECT                                      MESSAGE
cattle-system   29m         Normal    Scheduled                 pod/cattle-cluster-agent-5d5c498cf-mbt28    Successfully assigned cattle-system/cattle-cluster-agent-5d5c498cf-mbt28 to node-3
cattle-system   28m         Normal    Pulling                   pod/cattle-cluster-agent-5d5c498cf-mbt28    Pulling image "rancher/rancher-agent:v2.3.0"
cattle-system   28m         Warning   Failed                    pod/cattle-cluster-agent-5d5c498cf-mbt28    Failed to pull image "rancher/rancher-agent:v2.3.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/rancher-agent:v2.3.0": fail
ed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:5933fb5d6669c790aa65d0937f92f48d8143ae60b5bd181ef1da3fa41e0fc4e4: not found
cattle-system   28m         Warning   Failed                    pod/cattle-cluster-agent-5d5c498cf-mbt28    Error: ErrImagePull
cattle-system   4m44s       Normal    BackOff                   pod/cattle-cluster-agent-5d5c498cf-mbt28    Back-off pulling image "rancher/rancher-agent:v2.3.0"
cattle-system   27m         Warning   Failed                    pod/cattle-cluster-agent-5d5c498cf-mbt28    Error: ImagePullBackOff
cattle-system   29m         Normal    SuccessfulCreate          replicaset/cattle-cluster-agent-5d5c498cf   Created pod: cattle-cluster-agent-5d5c498cf-mbt28
cattle-system   29m         Normal    ScalingReplicaSet         deployment/cattle-cluster-agent             Scaled up replica set cattle-cluster-agent-5d5c498cf to 1
cattle-system   29m         Normal    Scheduled                 pod/cattle-node-agent-5w2dw                 Successfully assigned cattle-system/cattle-node-agent-5w2dw to node-4
cattle-system   28m         Normal    Pulling                   pod/cattle-node-agent-5w2dw                 Pulling image "rancher/rancher-agent:v2.3.0"
cattle-system   28m         Warning   Failed                    pod/cattle-node-agent-5w2dw                 Failed to pull image "rancher/rancher-agent:v2.3.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/rancher-agent:v2.3.0": fail
ed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:5933fb5d6669c790aa65d0937f92f48d8143ae60b5bd181ef1da3fa41e0fc4e4: not found
cattle-system   28m         Warning   Failed                    pod/cattle-node-agent-5w2dw                 Error: ErrImagePull
cattle-system   4m37s       Normal    BackOff                   pod/cattle-node-agent-5w2dw                 Back-off pulling image "rancher/rancher-agent:v2.3.0"
cattle-system   14m         Warning   Failed                    pod/cattle-node-agent-5w2dw                 Error: ImagePullBackOff
cattle-system   29m         Normal    Scheduled                 pod/cattle-node-agent-j5wv6                 Successfully assigned cattle-system/cattle-node-agent-j5wv6 to node-2
cattle-system   28m         Normal    Pulling                   pod/cattle-node-agent-j5wv6                 Pulling image "rancher/rancher-agent:v2.3.0"
cattle-system   28m         Warning   Failed                    pod/cattle-node-agent-j5wv6                 Failed to pull image "rancher/rancher-agent:v2.3.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/rancher-agent:v2.3.0": fail
ed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:5933fb5d6669c790aa65d0937f92f48d8143ae60b5bd181ef1da3fa41e0fc4e4: not found
cattle-system   28m         Warning   Failed                    pod/cattle-node-agent-j5wv6                 Error: ErrImagePull
cattle-system   4m32s       Normal    BackOff                   pod/cattle-node-agent-j5wv6                 Back-off pulling image "rancher/rancher-agent:v2.3.0"
cattle-system   24m         Warning   Failed                    pod/cattle-node-agent-j5wv6                 Error: ImagePullBackOff
cattle-system   29m         Normal    Scheduled                 pod/cattle-node-agent-npt96                 Successfully assigned cattle-system/cattle-node-agent-npt96 to node-1
cattle-system   28m         Normal    Pulling                   pod/cattle-node-agent-npt96                 Pulling image "rancher/rancher-agent:v2.3.0"
```
Does the image not exists?

**Comment by jiaqiluo** [comment]
Hi @iMerica the image exists, I can pull it in my local machine, can you check your network or try it again? 
```
> docker pull rancher/rancher-agent:v2.3.0
v2.3.0: Pulling from rancher/rancher-agent
5667fdb72017: Pull complete
d83811f270d5: Pull complete
ee671aafb583: Pull complete
7fc152dfb3a6: Pull complete
65ceb10a6e91: Pull complete
9a9035f7c757: Pull complete
fb492ec03242: Pull complete
dd5e0720bf0d: Pull complete
2a1c3528050a: Pull complete
b7bc87a14740: Pull complete
Digest: sha256:5933fb5d6669c790aa65d0937f92f48d8143ae60b5bd181ef1da3fa41e0fc4e4
Status: Downloaded newer image for rancher/rancher-agent:v2.3.0
> docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
rancher/rancher-agent   v2.3.0              5c682ce38688        3 days ago          288 MB
```

**Comment by iMerica** [comment]
I think I see the problem:

**no match for platform in manifest** 

```
 Failed to pull image "rancher/rancher-agent:v2.3.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/rancher-agent:v2.3.0": fail
ed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:5933fb5d6669c790aa65d0937f92f48d8143ae60b5bd181ef1da3fa41e0fc4e4: not found
```

Does Rancher not work on Raspberry Pis?

**Comment by iMerica** [comment]
Yep, appears that ` rancher/rancher-agent:v2.3.0` does not work with my `ARMv7 Processor rev 3 (v7l)` in the new RasPi 4.

**Comment by iMerica** [comment]
Issue persists even when pulling the image using the Docker CLI

```
pi@node-1:~ $ docker pull rancher/rancher-agent:v2.3.0
v2.3.0: Pulling from rancher/rancher-agent
no matching manifest for linux/arm/v7 in the manifest list entries
```

**Comment by iMerica** [comment]
Related:
- https://github.com/rancher/rancher/issues/2101
- https://github.com/rancher/rancher/issues/10868

**Comment by bd8392** [comment]
Have the same problem. Rancher is not working on the pi 4 (hypriotos as rancheros is also not working)

**Comment by Capr1sna** [comment]
Also having the same problem.
Did you found a working solution meanwhile ? I am failing updating the image for the cattle-node-agent and cattle-cluster-agent to use this instead:
rancher/rancher-agent:v2.2-head-linux-arm64

**Comment by iMerica** [comment]
I did not find a workaround, but I'm curious if this new Docker feature could work:

https://docs.docker.com/docker-for-mac/multi-arch/

**Comment by chinausers** [comment]
so long time

**Comment by MINI-Qiang** [comment]
```
NAME                                        READY   STATUS             RESTARTS   AGE
pod/cattle-node-agent-26zqp                 0/1     ImagePullBackOff   0          6m25s
pod/cattle-cluster-agent-745db996cc-2lwzr   0/1     ImagePullBackOff   0          6m25s

NAME                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/cattle-node-agent   1         1         0       1            0           <none>          6m26s

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cattle-cluster-agent   0/1     1            0           6m26s

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/cattle-cluster-agent-745db996cc   1         1         0       6m26s
```
yes, just **rancher/rancher-agent**  no rancher-agent-armhf  image
only  linux-amd64，linux-arm64，windows-amd64

ubuntu arm64  K3S docker ：No container started

**Comment by paxinos** [comment]
I was previously able to import a K3S cluster on PI-4's into  Rancher, but the PI-4's were running Ubuntu,  I've had to go back to Raspbian for various reasons and am now experiencing this problem.  Strange.      I'll have to try and reboot on Ubuntu to see what image it is using (could ubuntu on pi-4  support linux-arm64?)
 
I'd really like to stick with Raspbian - or is this a dead-end since images haven't been built for so long...

**Comment by paxinos** [comment]
ok, doesn't seem to be an issue between ubuntu or raspbian.   i can no longer get ubuntu connected either.    Is it possible an earlier release of rancher-agent briefly support the Pi 4 ?

**Comment by paxinos** [comment]
This is the exact error - same message on both unbuntu and raspbian - 

Feb 27 19:35:44 Pi4-51 k3s[9563]: E0227 19:35:44.292758    9563 kuberuntime_image.go:50] Pull image "rancher/rancher-agent:v2.3.5" failed: rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/rancher-agent:v2.3.5": failed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:e6aa36cca0d3ce9fea180add5b620baabd823fb34f9d100b7a8d3eb734392c37: not found

**Comment by paxinos** [comment]
So a bit more investigation reveals that rancher-agent:v2.3.5 doesn't support arm64.  but doing a docker pull on rancher/rancher-agent:v2.3.5-arm64 succeeds on raspbery pi 4:

pi@raspberrypi:~ $ sudo docker pull rancher/rancher-agent:v2.3.5-linux-arm64
v2.3.5-linux-arm64: Pulling from rancher/rancher-agent
Digest: sha256:8809281719c6cca7a11c1d61dea44475e7388f6a36e2b9b3fb84275b98a8d39e
Status: Image is up to date for rancher/rancher-agent:v2.3.5-linux-arm64
pi@raspberrypi:~ $ sudo docker pull rancher/rancher-agent:v2.3.5
v2.3.5: Pulling from rancher/rancher-agent
no matching manifest for unknown in the manifest list entries
pi@raspberrypi:~ $ 


So I downloaded the yaml that was provided by Rancer import.  Added '-linux-arm64' to the end of the images (two statements in the yaml).   And then applied the YAML.   And get further - but still not working.

Here is where it is now failing:
Feb 27 17:10:29 raspberrypi k3s[31210]: I0227 17:10:29.400171   31210 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
Feb 27 17:10:35 raspberrypi k3s[31210]: E0227 17:10:35.046920   31210 pod_workers.go:191] Error syncing pod fbb3be69-7c04-48fe-b4ea-b8f02d516e7c ("cattle-node-agent-jjjl4_cattle-system(fbb3be69-7c04-48fe-b4ea-b8f02d516e7c)"), skipping: failed to "StartContainer" for "agent" with CrashLoopBackOff: "back-off 2m40s restarting failed container=agent pod=cattle-node-agent-jjjl4_cattle-system(fbb3be69-7c04-48fe-b4ea-b8f02d516e7c)"
Feb 27 17:10:49 raspberrypi k3s[31210]: E0227 17:10:49.053513   31210 pod_workers.go:191] Error syncing pod fbb3be69-7c04-48fe-b4ea-b8f02d516e7c ("cattle-node-agent-jjjl4_cattle-system(fbb3be69-7c04-48fe-b4ea-b8f02d516e7c)"), skipping: failed to "StartContainer" for "agent" with CrashLoopBackOff: "back-off 2m40s restarting failed container=agent pod=cattle-node-agent-jjjl4_cattle-system(fbb3be69-7c04-48fe-b4ea-b8f02d516e7c)"
Feb 27 17:11:02 raspberrypi k3s[31210]: E0227 17:11:02.044207   31210 pod_workers.go:191] Error syncing pod fbb3be69-7c04-48fe-b4ea-b8f02d516e7c ("cattle-node-agent-jjjl4_cattle-system(fbb3be69-7c04-48fe-b4ea-b8f02d516e7c)"), skipping: failed to "StartContainer" for "agent" with CrashLoopBackOff: "back-off 2m40s restarting failed container=agent pod=cattle-node-agent-jjjl4_cattle-system(fbb3be69-7c04-48fe-b4ea-b8f02d516e7c)"

**Comment by iMerica** [comment]
> So a bit more investigation reveals that rancher-agent:v2.3.5 doesn't support arm64. but doing a docker pull on rancher/rancher-agent:v2.3.5-arm64 succeeds on raspbery pi 4:

Yes, this has already been established by my earlier posts above.

**Comment by tehKapa** [comment]
Same situation. 
I also tried to install the 2.4.0-rc1 but nothing changed.

**Comment by gsmlg** [comment]
+1

**Comment by papandadj** [comment]
最后咋解决的啊

**Comment by MINI-Qiang** [comment]
> 最后咋解决的啊
应该无解

**Comment by martdah** [comment]
+1

**Comment by felixmw** [comment]
+1
Any news whether there will be a fix?

**Comment by mzac** [comment]
+1 here too !!! Just got 3 x RPi 4 and while I got it working with Ubuntu 64 bit with Rancher (as Arm64 is supported) there are lots of docker images out there that don't support Arm64 and work with Arm32  / Armhf

**Comment by tompaschenda** [comment]
+.5
I am experiencing the same issue - but on a Raspberry Pi 2B

**Comment by NerdyShawn** [comment]
Same issue, tried various 2.3.x version in the past and upgraded to 2.4.3 today with no luck. k3s cluster is a mix of pi 2/3's.
`9s          Warning   Failed              pod/cattle-node-agent-r6t8w                  Failed to pull image "rancher/rancher-agent:v2.4.3": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/rancher-agent:v2.4.3": failed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:4eb38352d8221640dd13257974028758579211853ac0a10aa9ac90223a30f43d: not found
`

**Comment by clwillingham** [comment]
I've tried K3S and docker with the same results. the system wants to pull rancher-agent:2.4.3. if I force it to use master-head-linux-arm64 by modifying the docker command it does download and attempts to run but fails with the error
`standard_init_linux.go:211: exec user process caused "exec format error"`
trying a couple other versions results in the same issue.

**Comment by shocky** [comment]
+1

**Comment by shocky** [comment]
Found this blog:
 - https://qiita.com/yamaneko_usg3/items/56a55d7e461c8bf0c67a

Since I already have a rancher server, I have to import an rpi3 k3s cluster.
With above instruction, I can deploy the rancher-agent:v2.5.3-linux-arm64 successfully on my raspberry pi 3/B+ k3s cluster to import it into my Rancher server.

More detailed instructions: >>

# 1. Prepare (Optional) 
1. Get k3os-rootfs-arm64.tar.gz from https://github.com/rancher/k3os.
2. Create your own config.yaml for server/master or agents/workers.
 -  for server
```
...
hostname: pi1.local.net
k3os:
  k3s_args:
  - server
...
```
 - for workers
```
...
hostname: pi2.local.net
k3os:
  server_url: https://pi1.local.net:6443
  token: $NODE_TOKEN_FROM_SERVER
  k3s_args:
  - agent
...
```
# 2. K3s server on a raspberry pi 3 b+
1. Create the bootable SD card  with 2020-02-13-raspbian-buster-lite.img.
2. (Optional) touch /boot/ssh
3. Add a "arm_64bit=1" line to /boot/config.txt
4. Append the "cgroup_memory=1 cgroup_enable=memory" options to /boot/cmdline.txt
5. Boot up the rpi3 b+.
6. Login (or SSH) into the pi.
7. Get k3os-rootfs-arm64.tar.gz
8. sudo tar xzvf  k3os-rootfs-arm64.tar.gz --strip-components=1 -C /
9. Create or cp /k3os/system/config.yaml for server
10. sudo rpi-update. (check if this can be skipped.)
11. Reboot
12. Login (or SSH) into the pi1.local.net server. 
13. If everything goes fine, you could see followings.
```
Welcome to k3OS!

Refer to https://github.com/rancher/k3os for README and issues

By default mode of k3OS is to run a single node cluster. Use "kubectl"
to access it.  The node token in /var/lib/rancher/k3s/server/node-token
can be used to join agents to this server.
```

# 3. Import k3s cluster into your Rancher server.
1. Browse to your Rancher server's web UI.
2. Select _Add Cluser_ > _Import an existing cluster_ then check the notifications.
3. Login (or SSH) into the pi1.local.net server.
4. curl  --insecure -sfL https://your.rancher.server/v3/import/XXXXX.yaml  > rancher.yaml
5. vi rancher.yaml
```
:%s,image: rancher/rancher-agent:v2.3.5,image: rancher/rancher-agent:v2.3.5-linux-arm64
```
6. kubectl apply -f rancher.yaml
7. Check this k3s cloud is imported successfully.

# 4. Add some workers
1. Login (or SSH) into the pi1.local.net server.
2. cat /var/lib/rancher/k3s/server/node-token 
3. Do the same things 2.1~2.11 except 2.9. 
4. Edit config.yaml for k3os.token with above node-token contents.
5. Reboot
6. After a few minutes, you can see your worker node at the rancher server.

That's all folks.

Good luck!

**Comment by theAkito** [comment]
>     3\. Add a "arm_64bit=1" line to /boot/config.txt

Does this line convert the OS dynamically into 64-bit or what?
Else, how is it possible to run a 64-bit app on a 32-bit OS?

**Comment by shocky** [comment]
k3os and rpi-update might be the magic.
But please check if rpi-update is a must.

**Comment by felts94** [comment]
Same problem with raspberry pi 4

**Comment by liuyibo123** [comment]
same problem

**Comment by SolaceZA** [comment]
As listed the issue is you are not running the 64bit version of Raspbian. I'm running three PI4's with SSD only.

Steps I followed to get my cluster up:

Adjust Raspbian to run 64bit, adding this line informs rpi-update to update with the 64bit version.

Update: /boot/config.txt with 
**arm_64bit=1**

Run 
**rpi-update**
 to update the pi to 64bit

To confirm run 
**uname -a**

(Source: https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=250730)


1 - Setup Master
run the following to install K3S:
**curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644**

Validate that it's up:
**sudo kubectl get nodes**
**sudo systemctl status k3s.service**

Make sure the cluster is up and happy before adding the workers.

2 - Setup the Worker
On the master export the token from:
**sudo cat /var/lib/rancher/k3s/server/node-token**

On the worker:
**export K3S_TOKEN="paste above token here"**
**export K3S_URL=https://<your master ip>:6443**
**curl -sfL https://get.k3s.io | sh -**

Then create the cluster in Rancher, Import custom.

Run the two commands to add the user and add the master:
**kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user pi**
**sudo kubectl apply -f https://<rancher server ip>/v3/import/2r3131231231231231231231231313123.yaml**

**Comment by felts94** [comment]
Ok this worked, 

I also changed the deployment file to the image name **rancher/rancher-agent:v2.5.1-linux-arm64 ** in this step

curl --insecure -sfL https://
/v3/import/dlzwxczz5vcrx4xk5kq4t97s8l2bm6zwf2cptx946txjjsbtxhv4kk.yaml | kubectl apply -f -

**Comment by felts94** [comment]
Something is now changing the deployment to set the image name back to **rancher/rancher-agent:v2.5.1**

**Comment by bostondigitalio** [comment]
1+

**Comment by johnrkriter** [comment]
To append onto what @SolaceZA  and @felts94  suggested, I was able to use my existing Rancher 2.4.5 to adopt a current 1.16 K3S cluster.

I was able to convert existing pi's to arm64 using @SolaceZA  suggested steps. This process seems to have worked nicely without damaging anything I was paying attention to.

to @felts94 point I did find(though I am not sure if this is a sequencing problem or an actual issue) that I needed to edit BOTH the `deployment/cattle-cluster-agent` and `daemonset/cattle-node-agent` and explicitly force the use of *-linux-arm64 images. From here the cluster seems okay and I can confirm that I have been able to add nodes repeatedly using this method.

**Comment by xinmans** [comment]
+1 

pi@raspberrypi:~ $ sudo docker run --platform linux/arm/v7 -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher 
Unable to find image 'rancher/rancher:latest' locally
latest: Pulling from rancher/rancher
Digest: sha256:10e938f788e725d1d2ed7bc909bae8c7a83b756c520fb2596bf559e44e13587d
Status: Image is up to date for rancher/rancher:latest
WARNING: image with reference rancher/rancher was found but does not match the specified platform: wanted linux/arm/v7, actual: linux/amd64
docker: Error response from daemon: image with reference rancher/rancher was found but does not match the specified platform: wanted linux/arm/v7, actual: linux/amd64.
See 'docker run --help'.

**Comment by MaxKramarenko** [comment]
Please find a solution. We love rancher!

**Comment by johnynfulleffect** [comment]
I'm also seeing this issue on a RPi 4 with the latest Rasperry Pi OS with bullseye.  Pointing to the image tage `v2.6.2-linux-arm64` allows me to download the image, however, it will not run on k3s due to an incompatible architecture:

```
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by catherineluse** [comment]
Reopening this issue because we recently had someone in the Rancher Users Slack asking for help importing an ARM cluster as well.

**Comment by catherineluse** [comment]
I asked about it internally. They said that Rancher is not expected to work with ARM32 and there is no plan to support it. 

For ARM64, it's experimental and not officially supported, although it is expected to work. Two of my colleagues said they got Rancher to run on ARM64 and manage clusters that were also running it. They said that when you import an ARM64 cluster into Rancher, the agent image is pulled based on the architecture of the node, so there shouldn’t be any special configuration needed for it to work.

There's a bit more information about Rancher ARM64 here, for example the requirement that for a custom cluster, the CNI plugin must be Flannel. https://rancher.com/docs/rancher/v2.6/en/installation/resources/advanced/arm64-platform/ But there is no plan for ARM64 to be officially supported.

**Comment by unixorn** [comment]
Doesn't graviton use ARM64? It seems odd to not support ARM nodes in EC2
