### ISSUE TITLE
[UI] Can't enable Windows Support on RKE template with Latest v1.15 selected

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#23395]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Log in as admin
2. Go to `Tools -> RKE Templates`
3. Click `Add Templates` button in top right corner
4. Select `Latest v1.15 (allow patch version upgrades)` from the `Kubernetes` version drop down.
5. Select `Flannel` from `Network Provider` drop down.
6. Attempt to Enable Window Support, but can't, UI is grayed out and disabled:

![image](https://user-images.githubusercontent.com/468462/66689465-d3adfa80-ec3f-11e9-9f98-735e886cecf2.png)

The Windows Support radio buttons should be enabled for Latest v1.15. Works fine if v1.15.4-rancher1-2 is selected.

**Other details that may be helpful:**
Using Firefox 69.0.1 on MacOS 10.14.6

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.0
- Installation option (single install/HA):
single install

**Comment by sangeethah** [comment]
@soumyalj When verifying this issue , please make sure that we are also able to create Windows template using `v1.16.1.-rancher1-1(experimental) and `Latest v1.16 (allow patch version upgrades) (Experimental)  K8s selected with Flannel.

**Comment by soumyalj** [comment]
Tested with version v2.3.1-rc2. 
1. Create a RKE template T1 and revision R1 and select K8s version Latest v1.15. 
2. Choose Flannel network plugin. 
Enabling/Disabling  Windows is allowed. The UI is not greyed out .
![Screen Shot 2019-10-12 at 7 17 39 PM](https://user-images.githubusercontent.com/18536626/66710030-f9f99600-ed24-11e9-87b5-282bfbf5b9d5.png)

Also tested with other K8s 1.16 versions presented as below. The windows enabling/disabling buttons are active.
![Screen Shot 2019-10-12 at 7 18 52 PM](https://user-images.githubusercontent.com/18536626/66710042-5eb4f080-ed25-11e9-9da9-713980f857ce.png)

![Screen Shot 2019-10-12 at 7 20 22 PM](https://user-images.githubusercontent.com/18536626/66710043-6379a480-ed25-11e9-9cca-b3e5ed843326.png)
