### ISSUE TITLE
Add support for EtcD Azure Blob Storage backup

### ISSUE THREAD

**Issue by michaelandrepearce** [rancher/rancher#23402]
Ability to backup and recover from Azure Blob storage is important for anyone in Azure. As like s3 solution that exists for aws users/customers. But currently this is not present in the current backup options

**What kind of request is this**

Enhancement

**Steps to reproduce (least amount of steps as possible):**
 Na

**Result:**
Able to select Azure Blob storage as a backup option for etcd and recovery as like S3

**Other details that may be helpful:**

**Environment information**

**Cluster information**
Azure cloud provider

**Comment by alena1108** [comment]
The issue for it is already tracked https://github.com/rancher/rancher/issues/19818
