### ISSUE TITLE
Incorrect version (1.16-Experimental) shown for clusters created with TR that has K8s version with "latest" and override option.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#23413]
Rancher Server Version - v2.3.1-rc2

Steps to reproduce the problem:
Create a Template Revision with K8s version set to `Latest 1.15` (or `Latest 1.13`  or ``Latest 1.14`) and override. 
Create a cluster with this template revision with the default K8s presented to the user which `1.15.4`.
Once cluster is created successfully, go to "Edit Cluster" page.

Notice that the cluster version that get selected is always 1.16.1:

<img width="762" alt="Screen Shot 2019-10-12 at 6 08 30 PM" src="https://user-images.githubusercontent.com/4266958/66709540-5952a880-ed1b-11e9-8866-e3fd85c73003.png">

**Comment by westlywright** [comment]
I was unable to reproduce this with the steps given. I suspect there may have been a different issue going on with this template that may have been related to rancher/rancher#23415 and I think this may prevent this issue from occurring in the future.

**Comment by westlywright** [comment]
Available in UI tag `2.3.17`

**Comment by soumyalj** [comment]
Tested with rancher v2.3.1-rc2 
1.Create a Template Revision with K8s version set to Latest 1.15 and set override.
2. Once cluster is created successfully, go to "Edit Cluster" page.
The K8s version is displayed as v1.15.4 correctly
<img width="964" alt="Screen Shot 2019-10-14 at 9 28 38 PM" src="https://user-images.githubusercontent.com/18536626/66800366-c9069600-eec9-11e9-8936-ddaa553819d5.png">
