### ISSUE TITLE
Why are windows worker nodes limited to Docker EE?

### ISSUE THREAD

**Issue by rgl** [rancher/rancher#23418]
I'm trying to add a windows worker node to a Rancher 2.3.0 launched cluster but it failed to install due to:

```
FATA: Only support with Docker EE
```

Why is it requiring Docker EE? Is there any particular reason why can't it work with Docker CE?

**Comment by thxCode** [comment]
For now, Docker EE is the requirement runtime of the Windows K8S cluster: https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#container-runtime.

https://github.com/rancher/rancher/blob/21be0ba445c273a504ba11468f16a594a4eed456/package/windows/bootstrap.ps1#L188-L191
If you want to try on Docker CE, you could skip all verifications when adding a Windows worker:
```
PowerShell -NoLogo -NonInteractive -Command "& {docker run -e WITHOUT_VERIFICATION=true -v c:/:c:/host rancher/rancher-agent:<version> bootstrap --server <server> --token<token> --ca-checksum <ca-checksum> --worker | iex}"
```

**Comment by loganhz** [comment]
I tried to use Docker CE. It doesn't work when I tried to start a docker container.

Maybe you can have a try by following https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-nodes/

Note:

If you have a Windows Server license, you will automatically get the Docker EE license

**Comment by rgl** [comment]
Thanks for the pointers!

But do you known why, technically, Docker EE is required? I'm asking because the last time I've read about this, the EE-basic was technically the same as Docker CE, but without support.

**Comment by GehanPanapitiya** [comment]
@loganhz  does it mean 
Windows server will come docker EE installed ?  so licensing is not version dependent

currently docker ee is  installed manually via MSFT , which lets you to install latest or force a version.
```
Install-Module DockerMsftProvider -Force
Install-Package Docker -ProviderName DockerMsftProvider -Force
```

**Comment by loganhz** [comment]
https://hub.docker.com/editions/enterprise/docker-ee-server-windows

Maybe this is helpful. @GehanPanapitiya

**Comment by sirredbeard** [comment]
Docker EE and soon containerd are the only Microsoft supported runtimes for Windows containers.

**Comment by GehanPanapitiya** [comment]
> Docker EE and soon containerd are the only Microsoft supported runtimes for Windows containers.

do you have a rough date for this change over ?

**Comment by halldong** [comment]
> @loganhz does it mean Windows server will come docker EE installed ? so licensing is not version dependent
> 
> currently docker ee is installed manually via MSFT , which lets you to install latest or force a version.
> 
> ```
> Install-Module DockerMsftProvider -Force
> Install-Package Docker -ProviderName DockerMsftProvider -Force
> ```

I followed the command as yours plus version requirement. But same error produced.
