### ISSUE TITLE
Compatibility issues with cert-manager v0.11.0

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [rancher/rancher#23424]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug/request

**Steps to reproduce (least amount of steps as possible):**
Install cert-manager v0.11.0 by following the guidelines from https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html

**Result:**
The issue being that in cert-manager v0.11.0 the label `certmanager.k8s.io` has been replaced with `cert-manager.io`. But this is yet to be handled the helm chart for rancher.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0
- Installation option (single install/HA): HA

**Comment by mschickervxob** [comment]
I updated cert-manager because of the advice from rancher regarding 1st of November. Cert-manager was on 0.5.2. Now I have 0.11.0 and cannot upgrade from rancher 2.2.8 to 2.2.9 via helm.

**Comment by gregbacchus** [comment]
@mschickervxob if it helps, downgrading to cert-manager 0.10 should resolve this issue. It's caused by the changing of the cert-manager CRDs in v0.10. So if downgrading, make sure that you install the earlier CRDs as well.

**Comment by mschickervxob** [comment]
Thanks @gregbacchus - but this also means to change all resources to the old format certmanager.k8s.io from cert-manager.io again and later again back which I prefer not to do.

**Comment by gregbacchus** [comment]
Yes, I can understand that. It may be possible to run both versions of cert-manager, but I haven't tried (and probably wouldn't).

**Comment by deniseschannon** [comment]
Update to the latest cert-manager version as this was written awhile ago and cert-manager updates very quickly. 

Create docs on how to upgrade to cert-manager v0.11.0+

Test the current docs for all installation and update wherever we indicate v0.9.1.
https://rancher.com/docs/rancher/v2.x/en/installation/

**Comment by dnauck** [comment]
Currently it's not possible to install cert-manager v0.11, see #23850

**Comment by cipianpascu** [comment]
Thank you for working on this, guys. And, don't forget to update rancher-latest helm chart also.
Kind regards,
Ciprian

**Comment by deniseschannon** [comment]
On hold until docs are written of how to use the new cert-manager version for HA installs

**Comment by jiaqiluo** [comment]
Follow the new documentation to install Rancher in HA mode successfully:

- Rancher version: v2.3.4-rc3
- Rancher Chart version: 2.3.4-rc3
- Cert-manager version: v0.12.0
- RKE command-line tool: v1.1.0-rc2

**Comment by jiaqiluo** [comment]
Wait for a v2.4 preview release to validate master-head

**Comment by jiaqiluo** [comment]
The issue is reopened, we need to find the proper upgrading path for upgrading cert-manager and Rancher together

**Comment by jiaqiluo** [comment]
Because of the API change in cert-manager since v0.11 
https://cert-manager.io/docs/installation/upgrading/upgrading-0.10-0.11/
and how helm handles upgrading apps(helm compares the running app with the original template used to install it), we have to upgrade Rancher with the following steps if we want to run Rancher with cert-manager 0.12:


Step1: make a one-time snapshot of Rancher data
```
rke etcd snapshot-save --name rancher-2-3-3-backup.db --config rancher-cluster.yml
```
Result: RKE takes a snapshot of etcd running on each etcd node. The file is saved to /opt/rke/etcd-snapshots.

Step2: uninstall Rancher
```
helm delete rancher -n cattle-system
```

Step3: uninstall cert-mananger
```
helm delete cert-manager -n cert-manager
```

Step4: Delete the CustomResourceDefinition using the link to the version v0.9.1 you installed
```
kubectl delete -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.9/deploy/manifests/00-crds.yaml
```

Step5: Install the new CustomResourceDefinition resources
```
kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml
```

Step6: Re-install cert-manager
```
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v0.12.0 
```

Step7; Re-install Rancher
```
helm install rancher rancher-latest/rancher --version 2.3.4-rc4 --namespace cattle-system --set hostname=jiaqi-ha.qa.rancher.space  
```

**Comment by alekc** [comment]
I followed latest instructions but I am still having some issues. 

I am installing on a single node in ha mode
```
nodes:
  - address: 163.172.183.120
    internal_address: 10.68.6.17
    user: root
    role: [controlplane, worker, etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"
```
with following bash script assembled from the current official documentation (+ steps given by @jiaqiluo )
```
#
rke up --config rancher_cluster.yml
RANCHER_BRANCH=latest

#check nodes
KUBECONFIG=$(pwd)/kube_config_rancher_cluster.yml
kubectl get nodes
kubectl get pods --all-namespaces

#add helm repo
helm repo add rancher-${RANCHER_BRANCH} https://releases.rancher.com/server-charts/${RANCHER_BRANCH}
kubectl create namespace cattle-system

# cert-manager
kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml
kubectl create namespace cert-manager
kubectl label namespace cert-manager certmanager.k8s.io/disable-validation=true
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v0.12.0

kubectl -n cert-manager rollout status deploy/cert-manager

helm install rancher rancher-${RANCHER_BRANCH}/rancher \
  --version 2.3.4-rc4 \
  --namespace cattle-system \
  --set hostname=rancher.domain.com \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=email.domain \
  --set letsEncrypt.environment=staging

kubectl -n cattle-system rollout status deploy/rancher
```
Installation succeeds (besides some race condition bugs such as 
```
+ helm install rancher rancher-latest/rancher --version 2.3.4-rc4 --namespace cattle-system --set hostname=rancher.55px.xyz --set ingress.tls.source=letsEncrypt --set letsEncrypt.email=tech@binweevils.com --set letsEncrypt.environment=staging
Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: dial tcp 10.43.80.85:443: connect: connection refused
```
and cluster stuck in setting host mode (resolvable with edit&save), but then I am presented with issue where **rancher.domain.com** is being served by a certificate **ingress.local**, and my workloads **cattle-node-agent** and **cattle-cluster-agent** are stuck in 
```
Get https://rancher.55px.xyz: x509: certificate is valid for ingress.local, not rancher.domain.com
```

Might be something trivial (or completely unrelated to this issue, in that case I will open a separate ticket). 

Thx

**Comment by jiaqiluo** [comment]
@alekc I think you just ran into this issue: https://github.com/rancher/rancher/issues/24770 
v2.3.4-rc7 has the fix.

**Comment by alekc** [comment]
yes, I actually came here from that ticket, but put rc4 and not rc7 following your comment above >.<
with rc7 it looks like everything is working as expected. Thx.

**Comment by alekc** [comment]
Is it possible that there is some non update helm cache somewhere? I am getting inconsistent results on new installs with single ha node, lets encrypt, rancher 
```

Rancher | v2.3.4-rc7
-- | --
User Interface | v2.3.30
Helm | v2.14.3-rancher1
Machine | v0.15.0-rancher28
```
(for full config see my message above)

When doing a deployment there is pretty much consistent error 
```
 helm install rancher rancher-latest/rancher --version 2.3.4-rc7 --namespace cattle-system --set hostname=rancher.domain.com --set ingress.tls.source=letsEncrypt --set letsEncrypt.email=tech@domain.com --set letsEncrypt.environment=production
null_resource.install_rancher: Still creating... [40s elapsed]
null_resource.install_rancher (local-exec): Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: dial tcp 10.43.149.2:443: connect: connection refused
```

Cattle-node-agent 
```
time="2020-01-05T13:58:58Z" level=fatal msg="Get https://rancher.55px.xyz: x509: certificate is valid for ingress.local, not rancher.55px.xyz"
```

the weird thing is that sometimes it works (cname is being assigned properly) and sometimes it's not. 
Since this stack is being deployed through terraform (destroy && apply), I am at loss.

**Comment by jiaqiluo** [comment]
Hi @alekc, thank you for the feedback.
Did you wait to see if the setup gets the proper certificate after a couple of minutes? 
There is a brief gap between Rancher running up and LetsEncrypyt issuing the cert, and during that time Rancher uses a self-signed cert and will replace it with the one from LetsEncrypt. I doubt that is the reason for the inconsistent.

**Comment by alekc** [comment]
Yes, I think so. I will try to trigger this situation again and see the time delta.

**Comment by tryhardest** [comment]
hi @jiaqiluo we are in the exact same situation as @alekc.

**Comment by jiaqiluo** [comment]
@alekc @tryhardest  I cannot reproduce the error you see in the console after running `helm install rancher ...`:
```
null_resource.install_rancher: Still creating... [40s elapsed]
null_resource.install_rancher (local-exec): Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: dial tcp 10.43.149.2:443: connect: connection refused
```

Did you wait for all cert-manager’s pods to be ready before installing Rancher? 
```
> kubectl get pods --namespace cert-manager
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-6ff9c88f48-xl64l              1/1     Running   0          108s
cert-manager-cainjector-785c778cb9-tvqqf   1/1     Running   0          108s
cert-manager-webhook-785fd76b4-c8b78       1/1     Running   0          108s
```
This requirement is mentioned in Rnacher's documentation: https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#optional-install-cert-manager

**Comment by jiaqiluo** [comment]
We need to upgrade the documentation for upgrading Rancher and cert-manager, which is tracked by this issue: https://github.com/rancher/docs/issues/2117
