### ISSUE TITLE
Cloning/Upgrading system labels doesn't work. Need to clone the system labels that make sense to clone. 

### ISSUE THREAD

**Issue by sonicsnes** [rancher/rancher#2342]
io.rancher.container.pull_image is a system label, but it would be nice if it cloned along with user labels, as it's added by users rather than the system.

**Comment by deniseschannon** [comment]
Thinking more about this, this is a bug where those type of labels should be copied. 

This should not be limited to only `io.rancher.container.pull_image` but the other list of labels that we allow users to set that don't have a specific UI area to input.

http://docs.rancher.com/rancher/labels/

**Comment by vincent99** [comment]
But some make no sense to copy (like `sidekicks`), so it's going to have to be a whitelist/blacklist.

**Comment by deniseschannon** [comment]
@vincent99 I trust your judgment on which ones should be copied. :)

**Comment by sangeethah** [comment]
When cloning a service that was created from"ExternalDns" catalog , cloned service does not start successfully because of the following 2 labels missing in the cloned service:

"io.rancher.container.agent.role"
"io.rancher.container.create_agent"

**Comment by deniseschannon** [comment]
This is breaking in cloning and upgrading.

**Comment by deniseschannon** [comment]
Start-once is not copied over for cloning/upgrading, if selected in original service in UI. 
Requested IP is not copied over for cloning/upgrading. If you clone or upgrade a stopped service, they might want to keep the same IP. Should we add it back in during clone/upgrade?

Still need to test DNS as the UI enhancement part wasn't working when I tested.

**Comment by vincent99** [comment]
Fixed in https://github.com/rancher/ui/pull/382

**Comment by tfiduccia** [comment]
Verified fixed - v0.50.2-rc2
Start-once and requested IP are updating for clone/upgrade.
