### ISSUE TITLE
2.3.0 upgrade - cattle-cluster-agent & cattle-node-agent CrashLoopBackOff

### ISSUE THREAD

**Issue by modemhead** [rancher/rancher#23441]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Upgraded High Availability (HA) Install , 2.2.8 to 2.3.0 using helm.

helm upgrade rancher rancher-latest/rancher --set hostname=rancher-dev.corp****--set tls=external --set auditLog.level=3

**Result:**
cattle-cluster-agent & cattle-node-agent entered state CrashLoopBackOff 

**Other details that may be helpful:**
INFO: Environment: CATTLE_ADDRESS=10.42.2.68 CATTLE_CA_CHECKSUM=3c5745f051626ff302c53d93c*******e7f26896f518d4b653bbc2 CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-7bbdc67b56-d97gq CATTLE_SERVER=https://rancher-dev.corp*********
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local  options ndots:5
INFO: https://rancher-dev.corp*********/ping is accessible
INFO: rancher-dev.corp********* resolves to ****
ERROR: The environment variable CATTLE_CA_CHECKSUM is set but there is no CA certificate configured at https://rancher-dev.corp*****/v3/settings/cacerts

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.3.0
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke / centos 7 / vmware
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 16gb RAM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64
 Experimental:    false
```

ive "fixed" the workloads deleting the CATTLE_CA_CHECKSUM key manually on cattle-cluster-agent & cattle-node-agent , now they seem to  be running ok.

UI local / system / cattle-cluster-agent / Edit >> and deleted the "CATTLE_CA_CHECKSUM" environment 

UI local / system / cattle-node-agent / Edit >> and deleted the "CATTLE_CA_CHECKSUM" environment 

is this procedure ok or im i risking breaking another function doing that ?

**Comment by modemhead** [comment]
i've used **--set tls=external** on the deployment, because i have a balanced nginx with ssl in front of Rancher

**Comment by aleksey005** [comment]
I have almost the same high availability installation. Thanks, I did it according to your method and the containers stopped restarting.

**Comment by aleksey005** [comment]
In general, this did not help much when I turned off and on all the fall nodes continued:


CrashLoopBackOff: Back-off 1m20s restarting failed container=rancher pod=rancher-7fb7645fc9-rz7nz_cattle-system(773cecac-ef44-11e9-a11b-000c293f3d4e)
--

![image](https://user-images.githubusercontent.com/6145279/66840052-1b01f700-ef70-11e9-8cd8-ce5d36268455.png)


`2019/10/15 14:17:55 [INFO] Rancher version v2.3.0 is starting
2019/10/15 14:17:55 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features:}
2019/10/15 14:17:55 [INFO] Listening on /tmp/log.sock
2019/10/15 14:17:55 [INFO] Running in clustered mode with ID 10.42.0.22, monitoring endpoint cattle-system/rancher
2019/10/15 14:17:56 [INFO] Starting API controllers
2019/10/15 14:17:57 [INFO] Listening on :443
2019/10/15 14:17:57 [INFO] Listening on :80
2019/10/15 14:17:57 [INFO] Adding peer wss://10.42.1.17/v3/connect, 10.42.1.17
2019/10/15 14:17:57 [INFO] Adding peer wss://10.42.2.25/v3/connect, 10.42.2.25
2019/10/15 14:17:57 [INFO] Starting cluster controllers for local
2019/10/15 14:17:57 [ERROR] Failed to connect to peer wss://10.42.2.25/v3/connect [local ID=10.42.0.22]: websocket: bad handshake
2019/10/15 14:17:57 [ERROR] Failed to connect to peer wss://10.42.1.17/v3/connect [local ID=10.42.0.22]: websocket: bad handshake
2019/10/15 14:17:58 [INFO] Starting cluster agent for local [owner=false]
2019/10/15 14:18:02 [ERROR] Failed to connect to peer wss://10.42.2.25/v3/connect [local ID=10.42.0.22]: websocket: bad handshake
2019/10/15 14:18:02 [ERROR] Failed to connect to peer wss://10.42.1.17/v3/connect [local ID=10.42.0.22]: websocket: bad handshake
2019/10/15 14:18:07 [FATAL] error running the jail command: : signal: killed`

**Comment by modemhead** [comment]
@aleksey005 , i think the error you are getting is not the same as mine, please note that what i've posted is a bug and a question, not to be taken my workaround as a definitive solution, lets wait for the experts to answer

**Comment by aleksey005** [comment]
@modemhead Yes, you’re right, I don’t have such a mistake, I paid attention to it late. I added 2 core resources and 3 GB of memory (there was one core and 2 GB of memory) and restarted the nodes. As a result, the cluster was able to synchronize with fewer restarts.

![image](https://user-images.githubusercontent.com/6145279/66843135-08d68780-ef75-11e9-9aa5-e510f7205155.png)

**Comment by dramich** [comment]
@aleksey005 Your rancher server was killed due to the jail script not completing in under 10 seconds which is an indication of an under powered system. You solved this by upgrading your instance.

**Comment by bmdepesa** [comment]
Reproduced in v2.2.8 -> v2.3.0 HA upgrade, with TLS termination offloaded to an Nginx LB.

Deployed with:
```
helm install rancher-latest/rancher \
--version 2.2.8 \
--name rancher \
--namespace cattle-system \
--set hostname=<hostname> \
--set tls=external
```

Local cluster and RKE provisioned cluster came up successfully, cluster and node agents are not restarting. Deployed a simple workload and was able to access it via ingress. 

I noticed in this fresh install, we encountered this bug: #20573, where `--no-cacerts` was not included in the Rancher deployment. 

CA certs were set, and `CATTLE_CA_CHECKSUM` was present in node and cluster agents. 

* Note there is a workaround here: https://github.com/rancher/rancher/issues/20573#issuecomment-504511147 -- this was not included when doing the fresh install

Upon upgrading to 2.3.0, I encountered the same problem as @modemhead; the local cluster and node agents were in a crash loop backoff. 

In this case, `--no-cacerts` was added to the Rancher deployment, and the CA certs were cleared. 

Removing the value of `CATTLE_CA_CHECKSUM` in the affected deployments  resolved the CrashLoopBackoff and the workloads were able to deploy successfully.

**Comment by deniseschannon** [comment]
The current workaround is to remove the `CATTLE_CA_CHECKSUM` from the affected deployments.


The fix would be when we are passig in `--no-cacerts` to Rancher server to start and it clears the CA cert, the agent upgrade should also include clearing out the `CATTLE_CA_CHECKSUM` values.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.2-rc2

* Fresh install of v2.2.8 in HA
  * `--set tls=external`
  * Reproduced original issue
    * cacerts is set
    * `--no-cacerts` is missing from Rancher deployment
    * Created a cluster
      * Node and cluster agents are in a crash loop backoff
    * `CATTLE_CA_CHECKSUM` value is present in all agents
* Upgrade to v2.3.2-rc2
  * `cacerts` is cleared
  * `--no-cacerts` is correctly added to the Rancher deployment
  * `CATTLE_CA_CHECKSUM` is removed from all agents
  * All workloads in system projects are functional
  * All clusters available.
