### ISSUE TITLE
Service delete seems to remove containers sequentially

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rancher#2344]
With a large service of hundreds of containers, a delete of the service goes quite slow.  It seems to delete containers sequential.

**Comment by alena1108** [comment]
Should be fixed long ago

**Comment by sangeethah** [comment]
Tested with latest build from master:

Created a service with scale 100.
When all instances where up and running , deleted the service.
As part of service deletes , multiple instances of the service get deleted in parallel.
Multiple instances get to "stopping" state at the same time in DB.
