### ISSUE TITLE
[backport]Remove Project Monitoring In System Project

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#23445]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
None

**Result:**
None

**Other details that may be helpful:**
The project monitoring in system project make no senses. The cluster monitoring should do its job. It has been removed from system project in v2.3.x. So we should remove it in v2.2.x also.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2-head d3dfcff0
UI: `latest-2.2`

* Monitoring can not be enabled in System project, and provides a message: `	
If you want to collect custom metrics for pods in System Project, please enable cluster level monitoring directly.`
