### ISSUE TITLE
AzureAD: server error while authenticating: parameter 'authorizationCode' cannot be empty

### ISSUE THREAD

**Issue by andreastoermer** [rancher/rancher#23440]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
I try to activate AzureAD for my rancher installation, enter the three keys inside the rancher gui and the endpoint inside the azure configuration. After clicking on the "Authenticate with Azure" button, i get the following error message:

server error while authenticating: parameter 'authorizationCode' cannot be empty

**Result:**
I get this error message and cannot activate AzureAD for Rancher.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by Turb0Fly** [comment]
Hi, 
I ran into the same issue recently with Rancher 2.3.3.
In Azure, under App Registration, if you click on App Registrations (Legacy) and you use the endpoints from there in your Rancher Azure AD setup page, it will work.

I tried again, disabled Azure AD, reverted back to the new App Registrations and was greeted with the same error message 
AzureAD: server error while authenticating: parameter 'authorizationCode' cannot be empty

I went back and tried it again with Legacy and it worked.

Seems to me like Rancher is not compatible with the new App Registrations in Azure.

**Comment by Sharma-Rajat** [comment]
hello,

Please note you can use the new app registration. Please see up your permissions accordingly to the docs using legacy AD as delegated auth.
https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/azure-ad/

**Comment by yaron** [comment]
I had the same problem, was unable to get it to work with the new app registrations. And since the legacy app registrations will be removed from azure in march this year it looks like Rancher just doesn't support app registrations after that date.
To get it to work I used legacy app registrations and was able to follow the documentation. With the new app registrations I couldn't even get it to work using the old urls or giving it way too many permissions.

**Comment by mrajashree** [comment]
Hi @andreastoermer @Turb0Fly and @yaron , have you given all these permissions within the new app registrations portal too? https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/azure-ad/#3-set-required-permissions-for-rancher

**Comment by yaron** [comment]
Hello @mrajashree, thanks for getting back so quickly. I've tried to translate the documentation to the new app registration process, but couldn't get it to work. So at the minimum the issue is that the documentation is not up to date.

**Comment by Turb0Fly** [comment]
Hello @mrajashree . I will have to try with the Supported Legacy API Azure Active Directory Graph.  Somehow, I only used Microsoft Graph and it worked.

![image](https://user-images.githubusercontent.com/58305889/73881654-b7f1e400-482e-11ea-8e94-b241bb595454.png)
