### ISSUE TITLE
prometheus chart v9.1.0 fails to deploy in k8s 1.16 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23458]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Add catalog using this branch - from this PR - https://github.com/rancher/charts/pull/272
- Go to Cluster --> Project(Default) --> Apps --> Launch
- Launch prometheus chart v9.1.0.
- Give the default values, and Launch the app. 

**Actual Result:**
The app fails to deploy.
Error: `Failed to install app prometheus. Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"`

**Expected Result:**
The app should deploy successfully

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): dramich/rancher:dev
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke
- Kubernetes version (use `kubectl version`):

```
v1.16.1-rancher1-1
```

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/charts/pull/289

**Comment by sowmyav27** [comment]
**Verified on 2.3-head - latest**
**Steps:**

- Deploy a k8s 1.16 cluster - 3 nodes, all roles(AWS)
- Deploy a global catalog: `https://git.rancher.io/charts` branch: `k8s-1.16` (10/17/2019)
- Deploy prometheus in a project, say Default project.
- The app is deployed successfully and comes up `Active`

- But 3 endpoints of Prometheus App - of (`prometheus-node-exporter` workload) do not load/work.

**Note:** in a k8s 1.15 cluster, 3 nodes, all roles (DO), the App is Active and all the endpoints work/good.

**Comment by jiaqiluo** [comment]
I cannot reproduce the bug in the following two clusters in a Rancher:v2.3-head e7ac6ffe6 setup

```
- k8s 1.16.2 with 1 etcd + control plane, 3 workers
- k8s 1.16.2 with 3 all-roles 
```

**Comment by sowmyav27** [comment]
After opening the corresponding ports in AWS security group, the endpoints worked as mentioned here https://github.com/rancher/rancher/issues/23458#issuecomment-543365328
Closing the issue.
