### ISSUE TITLE
[UI] Custom global role creation

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#23453]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**What:**
UI for a admin to create custom global role and set it as default. Admin should be able to clone existing global role.

**Backend Issue**:
https://github.com/rancher/rancher/issues/16216

**Comment by tfiduccia** [comment]
UI - Will be same as it is for Cluster and Projects.

1.  Add button to top of Global role list that says "Add Global Role"
![image](https://user-images.githubusercontent.com/11514927/66876226-e2f5b680-ef65-11e9-8fdc-d70e8a4fea40.png)
2.  Click on button and there it should match Project & Cluster Add pages:
![image](https://user-images.githubusercontent.com/11514927/66876221-dbcea880-ef65-11e9-8023-0195fbc2af60.png)

**Comment by westlywright** [comment]
Updates to the requirements for global roles:
1. Locked is not a concept that exists on a global role so it will not be displayed in the UI.
2. Inheritence isn't a concept that is applied to global roles as well so it is not displayed in the UI.

**Comment by jiaqiluo** [comment]
The feature is validated in master-head 5845c2d

- Admin can add a custom global role
- Admin can clone  existing global roles 

the global role page:
<img width="1327" alt="Screen Shot 2019-12-03 at 4 55 50 PM" src="https://user-images.githubusercontent.com/6218999/70100025-c6810c80-15ed-11ea-925a-9e1c65f166d4.png">


adding/cloning a role:
<img width="1294" alt="Screen Shot 2019-12-03 at 4 52 25 PM" src="https://user-images.githubusercontent.com/6218999/70099921-77d37280-15ed-11ea-99ba-fcc494a935e3.png">

the role shows in the list:
<img width="1284" alt="Screen Shot 2019-12-03 at 4 52 35 PM" src="https://user-images.githubusercontent.com/6218999/70099946-8d489c80-15ed-11ea-9eef-11c32aa35178.png">

More tests will be done and bugs will be tracked by independent issues.
