### ISSUE TITLE
Magento v5.1.4 app fails to deploy in k8s 1.16 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23459]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Add catalog using this branch - from this PR - https://github.com/rancher/charts/pull/272
- Go to Cluster --> Project(Default) --> Apps --> Launch
- Launch Magento v5.1.4
- Give the default values, and Launch the app. 

**Actual Result:**
The app fails to deploy.
Error: `Failed to install app prometheus. Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"`

**Expected Result:**
The app should deploy successfully

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): dramich/rancher:dev
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke
- Kubernetes version (use `kubectl version`):

```
v1.16.1-rancher1-1
```

**Comment by guangbochen** [comment]
@sowmyav27 I was able to deploy the Magento v5.1.4 successfully, also there is no `Deployment` with apiVersion `extensions/v1beta1` in the Magento v5.1.4.

The error message says `Failed to install app prometheus`, any reason why the name is prometheus?

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/charts/pull/290

**Comment by guangbochen** [comment]
It can be tested upon https://github.com/rancher/charts/pull/290 merge.

**Comment by jiaqiluo** [comment]
The template is tested in both k8s 1.15.5 and 1.16.2 clusters, and it works as expected. 
```
Rancher: v2.3-head, single install 
catalog branch: k8s-1.16
cluster: 1 etcd + control plane, 3 workers
```
