### ISSUE TITLE
Unable to Set Cloud 

### ISSUE THREAD

**Issue by moberlander08** [rancher/rancher#23468]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by dramich** [comment]
@moberlander08 Can you fill out the template with information in order for people to help you

**Comment by moberlander08** [comment]
Figured out the issue, the UI was inserting the https:// automatically.
