### ISSUE TITLE
Cluster template revision displays incorrect K8s version in the UI after rke-metadata-config update

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#23465]
Version: v2.3.1-rc2 

Steps:

Scenario 1:

1. Create a cluster template and revision T1/R1 with K8s version v1.13.11
2. Create a cluster using R1 
3. Upgrade the rke-metadata-config in UI to branch "dev" to obtain the recent metadata fixes. With this, the latest k8s version of v1.13.12  and other latest versions will be available . 

<img width="314" alt="Screen Shot 2019-10-15 at 3 59 20 PM" src="https://user-images.githubusercontent.com/18536626/66875984-f3596180-ef64-11e9-9f60-6ed9b7c8ec7d.png">

After this update, the K8s version displayed in the UI for the template revision is v1.15.5-rancher1-2 . (The K8s version v1.13-11 is no longer available and it picks up v1.15.5-rancher1-2)

<img width="1085" alt="Screen Shot 2019-10-15 at 3 55 39 PM" src="https://user-images.githubusercontent.com/18536626/66875781-539bd380-ef64-11e9-8ccc-5dd0bd89073b.png">

Also, when a new revision from default or a Clone is created from this template , the version 
v1.15.5-rancher1-2 is chosen by default in UI.

The API shows the correct K8s version:
<img width="456" alt="Screen Shot 2019-10-15 at 3 56 01 PM" src="https://user-images.githubusercontent.com/18536626/66875794-5dbdd200-ef64-11e9-916a-3ac93621f07a.png">

Scenario 2:

1. Create a cluster template and revision T1/R1 with **Latest K8s version v1.13.11**
2. Create a cluster using R1 
3. Upgrade the rke-metadata-config in UI to branch "dev" to obtain the recent metadata fixes. 

After this update, the K8s version displayed in the UI for the template revision is v1.15.5-rancher1-2 . (The K8s version v1.13-11 is no longer available and it picks up v1.15.5-rancher1-2)

On Refresh this issue is resolved. But on reentering the view revision page, the issue is seen again.

Scenario 3:
1. Create a cluster template and revision T1/R1 with K8s version v1.13.11
2. Create a cluster using R1 
3. Upgrade the rke-metadata-config in UI to branch "dev" to obtain the recent metadata fixes. With this, the latest k8s version of v1.13.12  and other latest versions will be available . 
4. Create a cluster with the template R1 and the UI displays the incorrect version v1.15.5-rancher1-2
(Note: API creates the cluster with k8s version v1.13.11)

**Comment by sangeethah** [comment]
Can be tested with `2.3.18` UI tag with `v2.3.1-rc3` rancher server version.

**Comment by soumyalj** [comment]
Tested the above scenarios in v2.3.1-rc4. The issues are fixed. 
Also reproduced the above issues on a setup with v2.3.1-rc2 with dev meta-data-config. 
Upgraded the UI tag and verified that they are fixed.
