### ISSUE TITLE
[backport] Helm Chart: `--set tls=external` is using Self Signed certificates instead of External

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#23464]
https://github.com/rancher/rancher/issues/20573

When fixing this, we also need to backport: https://github.com/rancher/rancher/issues/23441

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2.10-rc1

* Reproduced both issues in fresh install of v2.2.8 in HA with tls=external and an ec2 cluster
* Upgrade to v2.2.10-rc1
* Rancher deployment now has `--no-cacerts`
* Cluster & node agents all have `CATTLE_CA_CHECKSUM` cleared and are not in a crash loop
