### ISSUE TITLE
kafka app fails to deploy with default values

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23460]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Add catalog using this branch - from this PR - https://github.com/rancher/charts/pull/272
- Go to Cluster --> Project(Default) --> Apps --> Launch
- Launch Kafka v0.8.0
- Give the default values, and Launch the app. 

**Actual Result:**
The app fails to deploy.
The workloads do not come to `Active` status.
Error on `kafka-cp-schema-registry` workload - `ImagePullBackOff: Back-off pulling image "ranchercharts/confluentinc-cp-schema-registry:5.3.0"`
<img width="1421" alt="Screen Shot 2019-10-15 at 2 40 39 PM" src="https://user-images.githubusercontent.com/26032343/66873194-b7ba9980-ef5c-11e9-907e-a1fdfd96d1e8.png">

**Expected Result:**
The app should deploy successfully

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): dramich/rancher:dev
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke
- Kubernetes version (use `kubectl version`):

```
v1.16.1-rancher1-1 and v1.15 rancher
```

**Comment by guangbochen** [comment]
the mirror image is missing, it is pushed now, can u please re-test it now, thanks.

**Comment by sowmyav27** [comment]
**Verified on `2.3-head - latest` (10/17/2019)**

**Steps:**
- Changed catalog `https://git.rancher.io/charts` to point to `k8s-1.16` branch.
- Deployed 2 clusters - k8s 1.15.5 - 3 nodes - all roles and k8s 1.16.2 - 3 nodes - all roles.
- Go to project --> Apps --> Launch
- Launch kafka with default values.
- Workloads are seen restarting in both the clusters.
- The App fails to come to `Active` state.
<img width="1442" alt="Screen Shot 2019-10-17 at 1 16 27 PM" src="https://user-images.githubusercontent.com/26032343/67044077-5d4a4600-f0e0-11e9-8eeb-311df386aa15.png">

**Comment by jiaqiluo** [comment]
See the same issue in v2.3-head e7ac6ffe6 following the same steps.

**Comment by guangbochen** [comment]
Should be fixed in https://github.com/rancher/charts/pull/298, validated in k8s 1.16 cluster.

![image](https://user-images.githubusercontent.com/4569037/67074712-3bbe8c80-f1bc-11e9-80ca-0129934eec9f.png)

**Comment by jiaqiluo** [comment]
The template is tested in both k8s 1.15.5 and 1.16.2 clusters, and it works as expected. 
```
Rancher: v2.3-head, single install 
catalog branch: k8s-1.16
cluster: 1 etcd + control plane, 3 workers
```
