### ISSUE TITLE
Show health_state for containers when health_check is enabled for services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2346]
Sever version - v0.41.0

When we enable health check for a service , with invalid values ( port/url is incorrect) , the health_state for the containers are in "Initilaizing" state but the service is up and "running" and expected.

From UI , there is no indication that the health_check for this service is misconfigured. 
UI should display health_state .

**Comment by vincent99** [comment]
This used to do that but was broken last release...

**Comment by sangeethah** [comment]
Tested with server version - V0.43.0-rc2

When we enable health check for a service , with invalid values ( port/url is incorrect) , the health_state for the containers are stuck in "Initilaizing" state which is shown in the UI.

<img width="353" alt="screen shot 2015-10-25 at 11 41 46 am" src="https://cloud.githubusercontent.com/assets/4266958/10717197/8286a7ee-7b0d-11e5-9a30-7615e092ea4c.png">
