### ISSUE TITLE
Creating a cluster from a Cluster Template Revision  that has K8s version set to latest (with/without override), shows incorrect k8s version in drop down.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#23478]
Rancher server version -` v2.3.1-rc4`

Steps to reproduce the problem:
Scenario 1:
Create a CTR (Cluster template revision) that has K8s version set to latest and override .
Create a cluster using this CTR.
Notice that there is incorrect version presented in the K8s dropdown menu

<img width="1039" alt="Screen Shot 2019-10-15 at 11 06 22 PM" src="https://user-images.githubusercontent.com/4266958/66892520-c6c33b00-efa0-11e9-8241-a34e95a785b9.png">

Scenario 2:
Create a CTR that has K8s version set to latest .
Create a cluster using this CTR.
Notice that there is incorrect version presented in the K8s dropdown menu

<img width="1258" alt="Screen Shot 2019-10-15 at 11 21 11 PM" src="https://user-images.githubusercontent.com/4266958/66893267-81a00880-efa2-11e9-9baf-3cbc0f4d1a52.png">

**Comment by westlywright** [comment]
Available in UI tag `latest-2.3`

**Comment by soumyalj** [comment]
Tested with K8s v2.3-head with UI tag ```latest-2.3```

Scenario 1:
Create a CTR (Cluster template revision) that has K8s version set to latest and override .
Create a cluster using this CTR.
Correct version is presented in K8s dropdown menu as below:

<img width="1445" alt="Screen Shot 2019-10-17 at 3 48 27 PM" src="https://user-images.githubusercontent.com/18536626/67053241-9e008a00-f0f5-11e9-967f-9073d5600df2.png">

Cluster gets created successfully with the correct K8s version

Scenario 2:
Create a CTR that has K8s version set to latest without an override
Create a cluster using this CTR.
The correct revision is presented in K8s dropdown as below:
<img width="1420" alt="Screen Shot 2019-10-17 at 3 49 56 PM" src="https://user-images.githubusercontent.com/18536626/67053303-cc7e6500-f0f5-11e9-9200-1491c499a7a6.png">

Cluster gets created successfully with the correct K8s version
