### ISSUE TITLE
update packet node driver, enable custom iPXE from UI

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#23476]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement request

**Request:**
Packet's latest machine driver is at version 0.2.0 [0], rancher 2.3 uses 0.1.4 [1]

[0] https://github.com/packethost/docker-machine-driver-packet/releases 

[1] https://github.com/rancher/rancher/blob/f65aecc166484e04cb38dffc390a7f598e2359fa/app/machinedriver_data.go#L101

Packets node-template UI is also out of date – it defaults to Ubuntu 16.04 and does not have an Ubuntu 18.04 option. Looks related to this ticket (rancher/rancher#23279 )[https://github.com/rancher/rancher/issues/23279] It does not have Custom iPXE support, which is a driver for this request.

https://github.com/rancher/ui/blob/master/lib/nodes/addon/components/driver-packet/component.js

**Comment by mclamb** [comment]
As a Rancher customer and Packet user, I would love for this to be updated.

**Comment by zadunn** [comment]
Same deal here.  Rancher customer and packet user.  This is seems like a bit of a gap for folks who want a consistent deployment across providers.

**Comment by dsieczko** [comment]
Yes, would be awesome to see this updated. I work at Packet, let me know if we can help @aemneina

**Comment by deniseschannon** [comment]
@dsieczko An update to the machine driver can be made here: 
https://github.com/rancher/rancher/blob/master/app/machinedriver_data.go#L102

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/25680 this only adds packet 0.2.2 to rancher default drivers. there will still need to have a UI update so only merge if we're going to bother to do that work too.

UI: https://github.com/packethost/ui-driver-packet

**Comment by deniseschannon** [comment]
@dsieczko Are you able to help have someone make UI changes to be able to bump up to packet version 0.2.2?

**Comment by deniseschannon** [comment]
From what I've heard from packet, the docker machine driver doesn't support custom iPXE support. As after you install it, there are additional extra steps that are required to actually SSH into the instance, which means docker machine would never SSH in to be able to install Docker, let alone let Rancher SSH in to provision the k8s components. 

To update the machine driver in Rancher, you could use Packet's current workaround which recommends removing the built-in driver and adding your own to get the latest updates, and add your own if you follow these docs: 

https://github.com/packethost/ui-driver-packet

We'll be using this ticket to update the latest driver and UI directly from packet: 
https://github.com/rancher/rancher/issues/23279
