### ISSUE TITLE
Make RC builds of rancher server point to "dev" branch of kontainer-driver-metadata.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#23485]
Make RC builds point to "dev" branch of kontainer-driver-metadata.

Currently it gets set to "master" branch and we have to manually change it  to "dev" branch once RC build is installed.

**Comment by deniseschannon** [comment]
@alena1108 can you coordinate with @cloudnautique  on what would need to happen? If we can't do it in time for 2.3.2, let's push it out to 2.3.3

**Comment by sangeethah** [comment]
Reopening to get this  PR merged https://github.com/rancher/rancher/pull/23606

**Comment by sangeethah** [comment]
Rancher server built with latest build from `v2.3-head`  - rke-metadata-config points to "dev" branch.
Rancher server built with latest build from `v2.3-head` using server_version as `v2.3.2-rc1` - rke-metadata-config points to "dev" branch
Rancher server built with latest build from `v2.3-head` using server_version as `v2.3.2-alpha1` - rke-metadata-config points to "dev" branch

Rancher server built with latest build from `v2.3-head` using server_version as `v2.3.2` - rke-metadata-config points to "master" branch
