### ISSUE TITLE
Not allowed to edit clusters (in 1.14 or 1.14.x)  to go to a cluster template with same latest version(1.14.x)

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#23489]
Rancher version - v2.3.1-rc4

Steps to reproduce the problem:
Scenario 1:
Create a a CT with following revisions:
R1 - K8s version - 1.14
R2 - K8s version - 1.14.x (latest)
Deploy a cluster with R1.
Once cluster is deployed , edit cluster and try to switch templates. R2 will be greyed out.

Scenario 2:
Create a a CT with following revisions:
R1 - K8s version - 1.14.x (latest)
R2 - K8s version - 1.14.x (latest)
Deploy a cluster with R1.
Once cluster is deployed , edit cluster and try to switch templates. R2 will be greyed out.

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by soumyalj** [comment]
Tested with v2.3-head using UI tag latest-2.3
Scenario 1:
Create a a CT with following revisions:
R1 - K8s version - 1.14
R2 - K8s version - 1.14.x (latest)
Deploy a cluster with R1.

Once cluster is deployed , edit cluster and try to switch templates. R2 is not greyed out.
<img width="295" alt="Screen Shot 2019-10-22 at 1 25 22 PM" src="https://user-images.githubusercontent.com/18536626/67331926-3e2e2880-f4d3-11e9-927a-feed7b53e0ec.png">

Scenario2:
Create a a CT with following revisions:
R1 - K8s version - 1.14.x (latest)
R2 - K8s version - 1.14.x (latest)
Deploy a cluster with R1.
Once cluster is deployed , edit cluster and try to switch templates. R2 is not greyed out.

<img width="648" alt="Screen Shot 2019-10-22 at 1 44 35 PM" src="https://user-images.githubusercontent.com/18536626/67332028-6158d800-f4d3-11e9-89bd-923a8768a94f.png">
