### ISSUE TITLE
Icons Missing from Rancher Server UI In Chrome

### ISSUE THREAD

**Issue by Shaidar20** [rancher/rancher#2348]
Chrome looks like it is blocking the glyphicons from loading due to it being interpreted as font but actually transferred via MIME type "application/x-gzip". 

I'm running chrome version: 39.0.2171.99 m and also confirmed that this is still an issue on another person's computer.

**Comment by deniseschannon** [comment]
What version of Rancher are you running? What is your Rancher server setup like? 

Could you share a screenshot so I could see which ones are missing? 

We use Chrome during the QA process, and haven't noticed anything.

**Comment by vincent99** [comment]
I saw this with another user.. Not sure why it only affects a small portion of people, it's probably a certain version of Chrome it a certain extension installed.  Anyway the content types are wrong and should be fixed, https://github.com/rancher/rancher/issues/2199
