### ISSUE TITLE
[UI] AWS existing ssh key pair

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#23488]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Go to create an ec2 node template

**Result:**
 Cannot use pre-existing ssh key

**Requirements:**
* Need a dropdown of keypairs available, this will need to be fetch from aws
* Field for pasting in private ssh key

**Backend Issue:**
https://github.com/rancher/rancher/issues/16798

**Comment by HarrisonWAffel** [comment]
Just want to note that currently there is no way for rancher to determine a user-provided key-pair and one that is automatically created, it currently deletes any key-pair that is in use. If this issue is ever picked up we need to determine a way to differentiate between the two.

**Comment by jmmckenz** [comment]
bump...

This looks like it has been on the radar for a while.  Any plans for implementation?

Related: 
#15606 
#16798 
#34729
