### ISSUE TITLE
UI issue while creating an EKS cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23493]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. On rancher UI, create an EKS cluster
2. Give in cluster name, access key and secret key and click on next.
3. Select required `Cluster Options` and click on `Next: Select VPC & Subnet`.
4. Select required `VPC & Subnet` Click on `Next: Select Instance options`
5. Select `Node Options` and click on `Create`

**Actual Result:**
UI takes user back to this step:  **`VPC & Subnet` Click on `Next: Select Instance options`**

**Expected Result:**
UI should direct the user to `Clusters` page and show that the EKS cluster is deploying.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.1-rc5
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sowmyav27** [comment]
**verified on 2.3-head**
**ui-tag:** `https://releases.rancher.com/ui/latest-2.3/index.html`

**Steps to reproduce (least amount of steps as possible):**

1. On rancher UI, create an EKS cluster
2. Give in cluster name, access key and secret key and click on next.
3. Select required `Cluster Options` and click on `Next: Select VPC & Subnet`.
4. Select required `VPC & Subnet` Click on `Next: Select Instance options`
5. Select `Node Options` and click on `Create`
6. The `create` button changes to `Saving` on the same page
7. UI directs the user to Clusters page and show that the EKS cluster is deploying.
