### ISSUE TITLE
UI of Rancher 2.3.0 does not load in chrome browser

### ISSUE THREAD

**Issue by cjohn001** [rancher/rancher#23492]
Hello together,
when trying to load the Rancher UI in Chrome browser on mac
Version 77.0.3865.120 (Offizieller Build) (64-Bit)

The screen stays white.
The chrome debugger gives me the followed error message:

rancher.my-nutri-diary.de/:26 GET https://rancher.my-nutri-diary.de:8443/assets/vendor-602f56f6b7593841763b51a31099c325.js net::ERR_ABORTED 404 (Not Found)
service.js:1 Uncaught ReferenceError: define is not defined
    at service.js:1

Interesting might also be that I can load the page in chrome when using private mode, and I can also load it in safari browser. Maybe some concurrency issue when loading javascipts?

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/67060586-19af1500-f190-11e9-8334-4bad43708b4a.png)

Could you try to disable the cache?

**Comment by cjohn001** [comment]
Hello Logan,
disabling the cache let the UI load as expected.
