### ISSUE TITLE
Catalog refresh action does not return the catalog list

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#23496]
Refresh a catalog and the response is always nil. This makes it hard to determine if anything actually happened.

**Comment by dramich** [comment]
To test: refresh a catalog and watch the dev tools, the response should now contain the name of the catalog/s that get updated. This can also be done through the API UI.

**Comment by sowmyav27** [comment]
**Reproduced the issue on v2.2.9 and v2.3.1.**
Refresh a catalog, the response in the dev tools is `null`.

**On 2.3-head - latest - commit id: `d23f064ad`**
Refresh a catalog.
In the dev tools: response: 
- single catalog on the UI/API UI - `{"baseType":"catalogRefresh","catalogs":["library"],"type":"catalogRefresh"}`
- In the api UI - /v3/catalogs - Hit refresh. Response seen: `{"baseType":"catalogRefresh","catalogs":["library","system-library"],"type":"catalogRefresh"}
`
