### ISSUE TITLE
添加主机 ssh端口非标准22端口怎么修改

### ISSUE THREAD

**Issue by 758109577** [rancher/rancher#23503]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.8` UI: `v2.2.94` |
|Route|`global-admin.clusters.index`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Or you can find Chinese support via `rancher2` in WeChat
