### ISSUE TITLE
[Forwardport] InsufficientSubnetSize error when deploying AKS cluster with /24 subnet 

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23518]
Forwardport for rancher/rancher#22616

**Comment by westlywright** [comment]
Available in master.

**Comment by soumyalj** [comment]
Tested with master-head build (2142fc94b9c2)
1. Create a subnet using CLI as below:
az network vnet create
--resource-group $RS_GROUP
--name $VNET_NAME
--address-prefixes 10.0.0.0/8
--subnet-name $SUBNET_NAME
--subnet-prefix 10.164.15.0/24
2. In Rancher UI, create a new AKS cluster. On the second screen, select advanced networking and enter:
Virtual Network - Subnet (Subnet CIDR): 10.164.15.0/24
Kubernetes service address range" 10.13.0.0/16
Kubernetes DNS service IP address: 10.13.0.10
Docker bridge address: 10.11.0.1/16

AKS cluster got created successfully. Workload creation was fine and the cluster was functional.
kubectl shell within the cluster was functional.
```
> kubectl get node
NAME                     STATUS   ROLES   AGE   VERSION
aks-rancher-27663526-0   Ready    agent   17m   v1.14.7
aks-rancher-27663526-1   Ready    agent   17m   v1.14.7
aks-rancher-27663526-2   Ready    agent   16m   v1.14.7
> 

```

azurekubernetesConfig below:

```
azureKubernetesServiceConfig": {
"aadClientAppId": "",
"aadServerAppId": "",
"aadServerAppSecret": "",
"aadTenantId": "",
"adminUsername": "azureuser",
"agentOsdiskSize": 100,
"agentPoolName": "rancher",
"agentStorageProfile": "ManagedDisks",
"agentVmSize": "Standard_D2_v2",
"authBaseUrl": "https://login.microsoftonline.com/",
"baseUrl": "https://management.azure.com/",
"clientId": "5d059201-760f-454a-9dd2-03ac92128c56",
"count": 3,
"displayName": "",
"dnsServiceIp": "10.13.0.10",
"dockerBridgeCidr": "10.11.0.1/16",
"driverName": "azurekubernetesservice",
"enableHttpApplicationRouting": false,
"enableMonitoring": true,
"kubernetesVersion": "1.14.7",
"location": "centralus",
"logAnalyticsWorkspace": "",
"logAnalyticsWorkspaceResourceGroup": "",
"masterDnsPrefix": "",
"maxPods": 110,
"name": "",
"networkPlugin": "kubenet",
"networkPolicy": "",
"podCidr": "172.244.0.0/16",
"resourceGroup": "testrg",
"serviceCidr": "10.13.0.0/16",
"sshPublicKeyContents": "ssh-rsa abcdef",
"subnet": "soumyasubnet",
"subscriptionId": "testerere",
"tags": null,
"tenantId": "testeteet",
"virtualNetwork": "soumyanewvnet",
"virtualNetworkResourceGroup": "soumyaoct21ag"
},


```

The same tests were followed and AKS cluster with azure network plugin was created. The cluster creation was successful and the cluster was functional
