### ISSUE TITLE
How to add node to imported cluster which is managed by another rancher server previously

### ISSUE THREAD

**Issue by xshrim** [rancher/rancher#23512]
We previously created a cluster on a single-node rancher server (v2.2.7) and added several nodes to this cluster. 

Later we deployed a new rancher server cluster in HA mode (v2,3.0) and imported this cluster into the new rancher server, so the cluster becomes an imported cluster. 

As rancher server do not support adding nodes to the imported cluster and the original single-node rancher server that manages this cluster is no longer available, I can not extend this cluster any more

So, is there any way to add nodes to this cluster?

**Comment by FerdinandPiette** [comment]
Hi,

Any news here ?

I am in the same situation : a previous rancher node no longer available ; a new rancher and an imported cluster. In this configuration I am stuck ; I cannot extend my cluster.

I am looking for a way to let the new rancher take control over the cluster (or a way to create nodes without rancher)

**Comment by kevinkjt2000** [comment]
This possibly duplicates https://github.com/rancher/rancher/issues/16471
