### ISSUE TITLE
Update log volume description

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#23510]
![image](https://user-images.githubusercontent.com/5936271/66989310-b624d900-f0f6-11e9-8181-1d856ee20723.png)
This feature is supported on GKE cluster and RKE cluster (cluster provider in Amazon EC2, Azure, DigitalOcean, Linode, vSphere).

**Comment by tfiduccia** [comment]
@aiwantaozi - The current didn't make sense to me so after consulting with Bill, I'm changing the text to say "A volume will be mounted into the container, and all logs written will be exported to the logging target. This feature is supported on GKE and RKE clusters."

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sowmyav27** [comment]
**Verified on `2.3-head` with ui tag: `latest-2.3`**

**Steps:**

- Enable Logging on a cluster (fluentd)
- When the logging has been enabled, go to Project Default --> Workloads --> Deploy --> Volumes section
- The text has been changed as below

<img width="1655" alt="Screen Shot 2019-10-22 at 3 56 48 AM" src="https://user-images.githubusercontent.com/26032343/67247907-5a54aa00-f480-11e9-905f-c64410bc17e6.png">
