### ISSUE TITLE
[Forwardport] Translation for banners are broken on Apps page when autorefresh fires

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23522]
Forwardport rancher/rancher#23322

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by soumyalj** [comment]
Tested with master-head with UI index set to latest2. 
Go to Global Apps page
Wait until backend refresh for catalog fires( refresh time is 1 hour. Waited for 2+ hours)
The Translation of banners was not lost. The catalogs showed the details correctly.
![Screen Shot 2019-10-26 at 1 07 54 PM](https://user-images.githubusercontent.com/18536626/67625328-a5a8e880-f7f1-11e9-852e-ae0620dbc3a7.png)
