### ISSUE TITLE
[Forwardport] UI for Feature Flags

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23520]
Forwardport for rancher/rancher#23184

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 781cd0f
ui: latest2

* Feature flags tab is shown in Global Settings
* Toggling feature flags enables/disables features appropriately
* No bulk selection
* Default settings view is Advanced Settings
