### ISSUE TITLE
Catalog App - Harbor failed to pull image 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23529]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:`v2.3-head` e7ac6ffe6
- change the global library's branch to `k8s-1.16` 
- enable Github Auth 
- log in as a Github user, provision a k8s `1.16.2` cluster with 1 etcd + control plane, 3 workers
- add a new project and deploy Harbor

**Result:**
- the workload `harbor-harbor-core` failed to pull the image `ranchercharts/goharbor-harbor-core:v1.9.1`
``` 
Failed to pull image "ranchercharts/goharbor-harbor-core:v1.9.1": rpc error: code = Unknown desc = Error response from daemon: pull access denied for ranchercharts/goharbor-harbor-core, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

<img width="1326" alt="Screen Shot 2019-10-17 at 2 18 56 PM" src="https://user-images.githubusercontent.com/6218999/67052462-229dd900-f0f3-11e9-88d2-c574fdb3d567.png">

**Comment by jiaqiluo** [comment]
The same issue in the cluster with k8s 1.15.5

**Comment by guangbochen** [comment]
missing mirror image is synced, can u re-test it, thanks.

**Comment by jiaqiluo** [comment]
Follow the same steps to test in clusters with k8s 1.16.2 and 1.15.5 and the app is deployed successfully.
