### ISSUE TITLE
rancher-compose.yml is empy in preview mode.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2352]
Build from master - oct 15

When trying to add a new Stack using a template from catalog that has rancher-compose.yml,
preview mode shows empty rancher-compose.yml file:

<img width="766" alt="screen shot 2015-10-15 at 6 26 46 pm" src="https://cloud.githubusercontent.com/assets/4266958/10531748/6b1900ca-736a-11e5-80dd-262cefa1b207.png">

**Comment by deniseschannon** [comment]
Re-opened to let Sangeetha test.

**Comment by sangeethah** [comment]
Tested with latest UI from master.

rancher-compose.yml now shows up in the preview mode.
