### ISSUE TITLE
[Forwardport] Creating a cluster from a Cluster Template Revision that has K8s version set to latest (with/without override), shows incorrect k8s version in drop down.

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23523]
Forwardport rancher/rancher#23478

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by soumyalj** [comment]
Tested with master-head using UI index latest2
Scenario 1:
Create a CTR (Cluster template revision) that has K8s version set to latest and override .
Create a cluster using this CTR.
Correct version is presented in K8s dropdown menu as below:
![Screen Shot 2019-10-26 at 2 59 18 PM](https://user-images.githubusercontent.com/18536626/67626529-5ec2ef00-f801-11e9-922d-997d5de9f6d1.png)

Cluster creation was successful with the right K8s version

Scenario 2:
Create a CTR that has K8s version set to latest without an override
Create a cluster using this CTR.
The correct revision is presented in K8s dropdown as below:

![Screen Shot 2019-10-26 at 2 59 32 PM](https://user-images.githubusercontent.com/18536626/67626539-769a7300-f801-11e9-94ec-aa904e478f2e.png)
