### ISSUE TITLE
Catalog App - openebs fails in k8s 1.16.2

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23534]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:`v2.3-head` e7ac6ffe6
- change the global library's branch to `k8s-1.16` 
- enable Github Auth 
- log in as a Github user, provision a k8s `1.16.2` cluster with 1 etcd + control plane, 3 workers
- add a new project and deploy openebs, template version 1.2.0

Results:
- failed to deploy the app
`Wait helm template failed. Error: failed parsing --set data: key "fd0\\" has no value (cannot end with ,) : exit status 1`
`Wait helm template failed. Error: failed parsing --set data: key "OpenEBS" has no value (cannot end with ,) : exit status 1`

**Comment by guangbochen** [comment]
since this is a partner's PR, @ChandanSagar can u PTAL, thanks

**Comment by kmova** [comment]
@guangbochen .. will https://github.com/rancher/charts/pull/269 fix this issue with syntax of the questions.yaml, has something changed recently in how the charts are being parsed?

**Comment by panlith** [comment]
Same issue occurs on 2.3.1 and with k8s version 1.15.5.

**Comment by ChandanSagar** [comment]
This issue has been fixed as part of https://github.com/rancher/charts/pull/311 .
Now openebs 1.3.0 works with rancher 2.3.2 with Kubernetes 1.16.2.
But parsing fail error will arise if openebs 1.3.0 deployed on rancher version 2.2.x or lower.
To overcome this error we can update the below sections

1. NDM DISK FILTER BY VENDOR with `CLOUDBYT\,OpenEBS` 
2. NDM DISK FILTER BY PATH with `loop\,fd0\,sr0\,/dev/ram\,/dev/dm-\,/dev/md`

Once we update the above openebs installation works fine.

**Comment by deniseschannon** [comment]
This fix is in `master` of charts.

**Comment by jiaqiluo** [comment]
The fix is validated in 
- `Rancher:master-head` 22801ee
- catalog `library` branch `master` 
- k8s v1.16.2 

The steps are the same as the issue provides, now the app `openebs` is deployed successfully
