### ISSUE TITLE
Catalog App - neuvector fails in k8s 1.16.2

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23533]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:`v2.3-head` e7ac6ffe6
- change the global library's branch to `k8s-1.16` 
- enable Github Auth 
- log in as a Github user, provision a k8s `1.16.2` cluster with 1 etcd + control plane, 3 workers
- add a new project and deploy neuvector, template version 1.2.3 

Results:
- failed to deploy the app
`Failed to install app neuvector. Error: validation failed: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]`

**Comment by guangbochen** [comment]
@deniseschannon this is a partner chart, can we request a change from their side, thanks.

**Comment by MKlimuszka** [comment]
Closing since we don't support k8s 1.16 anymore.
