### ISSUE TITLE
Not able to parse questions when default values are present in questions section

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2353]
Sever version - build from master - Oct 16

Tried to create a stack with template - logstash from catalog:

"CONFIGURATION OPTIONS" section is not able to show editable fields for the questions with default values prepopulated:

<img width="872" alt="screen shot 2015-10-16 at 7 57 31 am" src="https://cloud.githubusercontent.com/assets/4266958/10545832/865a21c8-73df-11e5-87b6-3bed0a10c5a2.png">

questions section:
```

.stack:
  questions:
    - variable: "collector_inputs"
      description: |
        Logstash collection tier inputs. These will be added
        directly to input { } section of logstash.conf
      label: "Logstash inputs"
      type: "multiline"
      required: true
      default: |
        udp {
          port => 5000
          codec => "json"
        }
    - variable: "indexer_filters"
      description: |
        Logstash indexing tier filters. These will be added
        directly to filter { } section of logstash.conf
      label: "Logstash filters"
      type: "multiline"
      required: true
      default: ""
    - variable: "indexer_outputs"
      description: |
        Logstash indexing tier outputs. These will be added
        directly to output { } section of logstash.conf
      label: "Logstash outputs"
      type: "multiline"
      required: true
      default: |
        elasticsearch {
          host => "elasticsearch"
          protocol => "http"
          index => "logstash-%{+YYYY.MM.dd}"
        }
```

**Comment by vincent99** [comment]
Its the `type: multiline`, not the defaults.  The UI needs to add support for mutiline -> a textarea.

**Comment by sangeethah** [comment]
Tested with latest UI from master:

Tried to create a stack with template - logstash from catalog:

We are now presented with 3 config parameters which have defaults prepopulated.
