### ISSUE TITLE
Catalog App - artifactory-ha fails in k8s 1.16.2

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23532]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:`v2.3-head` e7ac6ffe6
- change the global library's branch to `k8s-1.16` 
- enable Github Auth 
- log in as a Github user, provision a k8s `1.16.2` cluster with 1 etcd + control plane, 3 workers
- add a new project and deploy artifactory-ha, template version 0.12.16 

Results:
- failed to deploy the app
`Failed to install app artifactory-ha. Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]`

**Comment by guangbochen** [comment]
@deniseschannon this is a partner's chart, can we please request an update, thanks.

**Comment by deniseschannon** [comment]
This is available to test in the `partners` branch in the charts repo.

**Comment by jiaqiluo** [comment]
Steps:
- run Rancher:master-head 22801ee single install 
- add a cluster with the `cloud provider` enabled (AWS)Cluster's  and using k8s `v1.16.2`
- switch the catalog library branch to `partners`
- deploy the app `artifactory-ha` which template version `v1.0.0`

Result:
- the app seems working because I can open the UI from the browser via either the 443/tcp or 80/tcp link
- but some pods show the state `unknown`
- also I can NOT open the shell or view logs on those pods

<img width="1338" alt="Screen Shot 2019-11-06 at 4 57 22 PM" src="https://user-images.githubusercontent.com/6218999/68348635-b42bb580-00b7-11ea-909c-b9fe7f40e758.png">
<img width="1336" alt="Screen Shot 2019-11-06 at 5 05 24 PM" src="https://user-images.githubusercontent.com/6218999/68348636-b42bb580-00b7-11ea-9f00-f39ccf0fc2f9.png">
<img width="1349" alt="Screen Shot 2019-11-06 at 5 05 31 PM" src="https://user-images.githubusercontent.com/6218999/68348637-b42bb580-00b7-11ea-98d7-83d3ce927eb7.png">

**Comment by jiaqiluo** [comment]
It turns out the failure of deploying the app is caused by insufficient memory resources in the worker node. The deployment `artifactory-ha-artifactory-ha-member` requires 4 GB free memory to initialize, and the worker node (t2.medium) does not have that much free memory.  

This template is re-tested in clusters in which workers have more memory and the app is deployed successfully and works as expected.

Rancher: v2.3-head 
Chart version: 1.0.0
Clusters' k8s version: 1.15 and 1.16
