### ISSUE TITLE
[Bug] Cloning a secret changes its contents

### ISSUE THREAD

**Issue by iwilltry42** [rancher/rancher#23538]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

- create a secret containing e.g. a Kerberos Keytab (binary format)
- check the contents of the secret, e.g. via `kubectl get secret mykeytab -o yaml`
- clone the secret to another namespace using the Rancher UI 
- compare the contents of the cloned secret to the contents of the original secret

Note: we're comparing the base64 encoded value here, which already differs.

**Result:**

- the value of the cloned secret differs from the value of the original secret (usually, it appends a few bytes, which makes the secret unusable)

**Other details that may be helpful:**

- the same happens, if you create the secret as a project secret (where it gets clone to other namespaces

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
  + this happened to us since v2.0.3 (first version we used) and is still happening under v2.3.0
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE (on-premise)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): bare metal
- Kubernetes version (use `kubectl version`): v1.15.6 (and earlier versions)

- Docker version (use `docker version`): 18.06 and 18.09

Maybe, secrets are cloned while being decoded, instead of cloning the b64-encoded thing?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24577

**Comment by loganhz** [comment]
Hi @iwilltry42 would you mind to upload a keytab for testing? Thanks a lot :)

**Comment by iwilltry42** [comment]
Hi @loganhz , I generated some random example keytab now for demo purposes. You can find it here: https://filebin.net/iqsmcd9wnsh0mvyf
The filebin also contains a screenshot of the file contents (displayed in vim).
