### ISSUE TITLE
Catalog App - Mariadb fails in k8s 1.15.5 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23531]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:`v2.3-head` e7ac6ffe6
- change the global library's branch to `k8s-1.16` 
- enable Github Auth 
- log in as a Github user, provision a k8s `1.15.5` cluster with 1 etcd + control plane, 3 workers
- add a new project and deploy mariadb (template version 6.7.4)

**Result:**
- failed to start pods in the workload `mariadb-slave`

`
Readiness probe failed:  mysqladmin: connect to server at 'localhost' failed error: 'Access denied for user 'root'@'localhost' (using password: YES)' `

<img width="1325" alt="Screen Shot 2019-10-17 at 4 35 05 PM" src="https://user-images.githubusercontent.com/6218999/67055527-47974980-f0fd-11e9-9f79-4717543390c3.png">

More Info:
- the same template works in the cluster with k8s `1.16.2`

**Comment by guangbochen** [comment]
Hi @jiaqiluo I can deploy the `Mariadb 6.7.4` on both k8s 1.15 and k8s 1.16, can u please try to install the app again?
![image](https://user-images.githubusercontent.com/4569037/67065709-eaa19f00-f1a1-11e9-9edd-1ab87dd1818c.png)
![image](https://user-images.githubusercontent.com/4569037/67065721-f2f9da00-f1a1-11e9-9676-6a21c8f90449.png)

**Comment by jiaqiluo** [comment]
@guangbochen  thanks for the feedback. I tried it again and the app Mariadb 6.7.4 is deployed successfully in both k8s 1.15 and 1.16

The issue is closed since the error is transient.
