### ISSUE TITLE
Cannot import EKS-cluster

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#23536]
**What kind of request is this (question/bug/enhancement/feature request):**
Error/Problem

**Steps to reproduce (least amount of steps as possible):**
Install Rancher
Create EKS cluster
Import EKS

**Result:**
time="2019-10-18T06:15:52Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2019-10-18T06:16:02Z" level=info msg="Connecting to wss://rancher.pnv-blue/v3/connect with token czqnjdn2r52cjvcjz975cqbf7-remove-for-security"
time="2019-10-18T06:16:02Z" level=info msg="Connecting to proxy" url="wss://rancher.pnv-blue.policy/v3/connect"
time="2019-10-18T06:16:02Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-2z7mv/m-821b7c5f894c\" not found" error="websocket: bad handshake"

**Other details that may be helpful:**
Rancher master in AWS account #1 and EKS in another AWS account #2
AWS set up without internet access (via VPN)

**Environment information**
Rancher HA with RKE version 2.3.rc9

![image](https://user-images.githubusercontent.com/15118220/67070565-189bd900-f1cc-11e9-8ae9-a4e3d2eef325.png)

**kubectl get node**
NAME                                             STATUS   ROLES    AGE   VERSION
ip-10-96-5-210.ap-southeast-2.compute.internal   Ready    <none>   17h   v1.13.7-eks-c57ff8

**kubectl -n cattle-system get pods -l app=cattle-agent -o wide**
NAME                      READY   STATUS    RESTARTS   AGE   IP            NODE                                             NOMINATED NODE   READINESS GATES
cattle-node-agent-d9fs5   1/1     Running   0          62m   10.96.5.210   ip-10-96-5-210.ap-southeast-2.compute.internal   <none>           <none>

**kubectl -n cattle-system logs -l app=cattle-agent**
time="2019-10-18T06:25:14Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-2z7mv/m-821b7c5f894c\" not found" error="websocket: bad handshake"
time="2019-10-18T06:25:14Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2019-10-18T06:25:24Z" level=info msg="Connecting to wss://rancher.pnv-blue/v3/connect with token czqnjdn2r52cjvcjz9-removed-for-security"
time="2019-10-18T06:25:24Z" level=info msg="Connecting to proxy" url="wss://rancher.pnv-blue/v3/connect"
time="2019-10-18T06:25:24Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-2z7mv/m-821b7c5f894c\" not found" error="websocket: bad handshake"
time="2019-10-18T06:25:24Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2019-10-18T06:25:34Z" level=info msg="Connecting to wss://rancher.pnv-blue/v3/connect with token czqnjdn2r52cjvcjz9-removed-for-security""
time="2019-10-18T06:25:34Z" level=info msg="Connecting to proxy" url="wss://rancher.pnv-blue/v3/connect"
time="2019-10-18T06:25:34Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-2z7mv/m-821b7c5f894c\" not found" error="websocket: bad handshake"
time="2019-10-18T06:25:34Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"

**kubectl -n cattle-system get pods -l app=cattle-cluster-agent -o wide**
NAME                                    READY   STATUS    RESTARTS   AGE   IP          NODE                                             NOMINATED NODE   READINESS GATES
cattle-cluster-agent-66d9bbc967-pqcx9   1/1     Running   0          64m   10.32.0.5   ip-10-96-5-210.ap-southeast-2.compute.internal   <none>           <none>

**kubectl -n cattle-system logs -l app=cattle-cluster-agent**
INFO: https://rancher.pnv-blue/ping is accessible
INFO: rancher.pnv-blue resolves to 10.98.144.4 10.98.144.60 10.98.144.81
INFO: Value from https://rancher.pnv-blue/v3/settings/cacerts is an x509 certificate
time="2019-10-18T05:22:42Z" level=info msg="Rancher agent version v2.3.0-rc9 is starting"
time="2019-10-18T05:22:42Z" level=info msg="Listening on /tmp/log.sock"
time="2019-10-18T05:22:42Z" level=info msg="Connecting to wss://rancher.pnv-blue/v3/connect/register with token czqnjdn2r52cjvcjz9-removed-for-security"
time="2019-10-18T05:22:42Z" level=info msg="Connecting to proxy" url="wss://rancher.pnv-blue/v3/connect/register"
time="2019-10-18T05:22:42Z" level=info msg="Starting user controllers"
time="2019-10-18T05:22:42Z" level=info msg="Registering namespaceHandler for adding labels "
time="2019-10-18T05:22:42Z" level=info msg="Starting workload controllers"

**kubectl get pod --all-namespaces**
NAMESPACE       NAME                                    READY   STATUS    RESTARTS   AGE
cattle-system   cattle-cluster-agent-66d9bbc967-pqcx9   1/1     Running   0          67m
cattle-system   cattle-node-agent-d9fs5                 1/1     Running   0          67m
kube-system     coredns-6cbd86b99d-4rfcz                1/1     Running   1          17h
kube-system     coredns-6cbd86b99d-6hd66                1/1     Running   1          17h
kube-system     genie-plugin-499wq                      1/1     Running   1          17h
kube-system     kube-proxy-986qc                        1/1     Running   1          17h
kube-system     weave-net-mwcnc                         2/2     Running   4          17h

Any idea?

**Comment by glourenco** [comment]
How did you solve this?

**Comment by rshiva777** [comment]
how the issue got resolved? i too face the same issue

**Comment by seth-hawthorne** [comment]
Hitting an issue with the same symptoms. 

Tried running rancher using docker 18.06.3-ce on CentOS 7.4 and Ubuntu 18.04 
`docker run -d -e HTTP_PROXY="http://my.corporate.proxy:8080" \
  -e HTTPS_PROXY="http://my.corporate.proxy:8080" \
  -e NO_PROXY="localhost,127.0.0.1,0.0.0.0,16.124.128.0/20" \
  --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher`

Have several existing K3s clusters. From Rancher I import the cluster, download the kubectl file to the cluster, and apply it.   

The node agent's fails to handshake with Rancher and Rancher indicates the cluster is in a Waiting state. 
    kubectl logs cattle-node-agent-k5ghw -n cattle-system
    time="2020-05-08T19:34:41Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
    time="2020-05-08T19:34:51Z" level=info msg="Connecting to wss://16.124.128.140/v3/connect     with token kh6hqqzm87jrllnbx4bwlkxnmlwd6n8284tpbvf24qmcr2v5978wzb"
    time="2020-05-08T19:34:51Z" level=info msg="Connecting to proxy" url="wss://16.124.128.140/v3/connect"
    time="2020-05-08T19:34:51Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-cghqd/m-a30843cb4160\" not found

It looks like the node has connectivity to the Rancher server but that there is an inconsistency in the data that is exchanged.  Greatly appreciate any insights, ideas, ...

**Comment by xkkker** [comment]
> 

Hitting the same issue..
Did't you fix that?
