### ISSUE TITLE
Changing URL doesn't work with existing DATA folder

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#2354]
If you run rancher-catalog-service with one catalogUrl and then change it to another, it doesn't clean up the old data or pull down the new repo.

**Comment by prachidamle** [comment]
https://github.com/rancher/rancher-catalog-service/pull/6 submitted to fix this issue

**Comment by prachidamle** [comment]
This is fixed, pr is merged.

**Comment by sangeethah** [comment]
Tested with server version - v0.43.1

After changing catalog.url , the DATA directory is rancher-server becomes empty and the gets clones with the new catalog.url. Also rancher-catalog-service gets restarted.

I am able to see the catalog from the updated catalog.url .
