### ISSUE TITLE
cert-manager / ranger chart / apiVersion wrong

### ISSUE THREAD

**Issue by tkltz** [rancher/rancher#23542]
When you install ranger in a k8s cluster with helm and cert-manager (as described in the [HA manual](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/)) with 'Rancher Generated Certificates' you will run into the error:
`$# helm install rancher-latest/rancher --name rancher --namespace cattle-system --set hostname=myrancher.url.com`
`Error: validation failed: unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"`

If you look at the cert-manager documentation, they use the 
`apiVersion: cert-manager.io/v1alpha2`
There is also a method to verify cert-manager is deployed correctly. If you test it with `certmanager.k8s.io/v1alpha1` it will fail (same error), if you use `apiVersion: cert-manager.io/v1alpha2` everything is ok.
> https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html#verifying-the-installation

**Solution:**
If you manipulate the `apiVersion` (rancher/templates/issuer-rancher.yaml) in the ranger "latest" chart, the ranger installation with helm will succeed.

`$# helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

$# helm list
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION NAMESPACE
cert-manager    1               Thu Oct 17 13:47:56 2019        DEPLOYED        cert-manager-v0.11.0    v0.11.0     cert-manager
rancher         1               Fri Oct 18 11:56:35 2019        DEPLOYED        rancher-2.3.1           v2.3.1      cattle-system

`

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.1` UI: `v2.3.18` |

**Comment by jiaqiluo** [comment]
The documentation recommends using the cert-manager version `v0.9.1` which is fully tested, it looks like yours is `v0.11.0`. Did you try the version `v0.9.1` ? 

https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/

**Comment by cloudnautique** [comment]
We are aware extra work needs to be done, and only recommend going to v0.9.1 right now. We have work on the chart in progress coming in a future release to handle the v0.11.x+ upgrades.
#23501

**Comment by tkltz** [comment]
@jiaqiluo I didn't test the `v0.9.1` :( my fault. I will let it run with the `v0.11.0` now, seems to work fine atm.
@cloudnautique Aye, thx! :)

**Comment by aliabbasjaffri** [comment]
Just in case anyone comes looking for an answer here, I've been banging my head trying to install HA cluster using cert-manager `v0.11.0`, but there are still compatibility issues with the stable release of rancher with it.`v0.10.1` worked like a charm.

**Comment by titou10titou10** [comment]
@cloudnautique , the current rancher install documentation shows how to install cert-manager v0.12! :
[link here](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#optional-install-cert-manager) 

I find nowhere in the current rancher installation doc  that v0.9.1 is the only supported version...    
This issue should be reopened or either :   
- correct the install documentation 
- update the chart, (ie`v1alpha2`) and make rancher compatible with the version of cert-manger that the docs tell us to install...

As a newcommer to rancher, I spend 2 days fuguring oiut what was wrong (and a couple of other days having rke running on Centos 8 because of iptables->nftables)
