### ISSUE TITLE
rancher/system-charts@charts/rancher-monitoring/v0.0.5 - Permissions issue in upstream NGINX container

### ISSUE THREAD

**Issue by westonmyers** [rancher/rancher#23548]
**What kind of request is this (question/bug/enhancement/feature request):**
`Bug`

**Steps to reproduce (least amount of steps as possible):**

While performing the upgrade of `rancher-monitoring` from `v0.0.4` to `v0.0.5`, on commits https://github.com/rancher/system-charts/commit/417ff9668c40c3897ecaeb4b4b43ec2b4ad83520 / https://github.com/rancher/system-charts/commit/ecda15b8db43f596a77fa41363ecc1beb1876e0f , there was an upgrade in the NGINX container. This has caused the following containers to fail to start with these corresponding error logs.

**Result:**
`prometheus-proxy`:
```
cp: can't create '/var/cache/nginx/nginx-start.sh': Permission denied
chmod: /var/cache/nginx/nginx-start.sh: No such file or directory
/bin/sh: /var/cache/nginx/nginx-start.sh: not found
``` 

`grafana-proxy`:
```
2019/10/18 18:29:03 [warn] 1#1: duplicate MIME type "text/html" in /nginx/nginx.conf:55
nginx: [warn] duplicate MIME type "text/html" in /nginx/nginx.conf:55
2019/10/18 18:29:03 [emerg] 1#1: mkdir() "/var/cache/nginx/cache" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/cache" failed (13: Permission denied)
```

**Other details that may be helpful:**
The permission change can be seen via a quick look at the filesystem in the relevant containers. (Obviously both on `rancher/nginx` and `nginx`):
```
rancher:~$ docker run --rm rancher/nginx:1.15.8-alpine ash -c "ls -lha /var/cache/nginx"
total 8
drwxr-sr-x    2 nginx    nginx       4.0K Jan 31  2019 .
drwxr-xr-x    1 root     root        4.0K Jan 31  2019 ..
rancher:~$ docker run --rm rancher/nginx:1.17.4-alpine ash -c "ls -lha /var/cache/nginx"
total 8K     
drwxr-xr-x    2 root     root        4.0K Sep 24 23:33 .
drwxr-xr-x    1 root     root        4.0K Sep 24 23:33 ..
```

As a "cheap" bypass I have created an ephemeral mount on both of those containers at `/var/cache/nginx`, in order to allow them to start.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
`rancher/rancher:master-head` (`rancher/rancher@sha256:9220d982f4cbc67cfaed5bd72c1e08c6efbe1a86c30ed112dd6fcf912649b29d`)
- Installation option (single install/HA):
`Single`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
`Custom`
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
`VM`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
```
Client:
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.13.1
 Git commit:        a872fc2f86c042e6992e17db6cdd9826c9c4232b
 Built:             Wed Oct  9 16:48:03 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.1
  Git commit:       a872fc2f86c042e6992e17db6cdd9826c9c4232b
  Built:            Wed Oct  9 16:47:24 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.0
  GitCommit:        36cf5b690dcc00ff0f34ff7799209050c3d0c59a
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Comment by westonmyers** [comment]
Forgot to mention that this is seen at both the cluster and project levels for monitoring.

**Comment by DarthSlider** [comment]
Double this. We have exactly the same problem after upgrading to 0.0.5
Any fixes yet?

**Comment by westonmyers** [comment]
The following is a duplicate of mine: https://github.com/rancher/rancher/issues/23573

**Comment by westonmyers** [comment]
This seems to go back to the following change seen during creation of the nginx user's home directory of `/var/cache/nginx` where they're setting UID.

Upstream's dockerfile at 1.15.8: [here](https://github.com/nginxinc/docker-nginx/blob/baa050df601b5e798431a9db458e16f53b1031f6/mainline/alpine/Dockerfile#L54).
Upstream's dockerfile at 1.17.4: [here](https://github.com/nginxinc/docker-nginx/blob/23a990403d6dbe102bf2c72ab2f6a239e940e3c3/mainline/alpine/Dockerfile#L12).

So, the following discussion at upstream ties in: https://github.com/nginxinc/docker-nginx/issues/329

I have adhered to the Rancher hardening documentation, so maybe that's contributing here.

The relevant containers are indeed running as the `nginx` user vs root; as seen by something like the following: `docker exec $(docker ps -q --filter "name=grafana-proxy_grafana-cluster-monitoring*") ash -c "id"`

Few ways to correct this issue. Really a pick your poison type of thing. Even discussed in that upstream issue.

**Comment by westonmyers** [comment]
To base off of the `nginx:1.15.8-alpine` dockerfile:
```
docker run --rm -it alpine:3.8 ash -c "addgroup -S nginx && adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx && ls -lhan /var/cache/"
total 24
drwxr-xr-x    1 0        0           4.0K Oct 22 03:53 .
drwxr-xr-x    1 0        0           4.0K Mar  6  2019 ..
drwxr-xr-x    2 0        0           4.0K Mar  6  2019 apk
drwxr-xr-x    2 0        0           4.0K Mar  6  2019 misc
drwxr-sr-x    2 100      101         4.0K Oct 22 03:53 nginx
```
Cool. We have our `/var/cache/nginx` as the `nginx` user (Before they changed the UID).

To base off of the `nginx/1.17.4-alpine` dockerfile:
```
docker run --rm -it alpine:3.10 ash -c "addgroup -g 101 -S nginx && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx && ls -lhan /var/cache/"
total 16K    
drwxr-xr-x    4 0        0           4.0K Oct 21 13:39 .
drwxr-xr-x   11 0        0           4.0K Oct 21 13:39 ..
drwxr-xr-x    2 0        0           4.0K Oct 21 13:39 apk
drwxr-xr-x    2 0        0           4.0K Oct 21 13:39 misc
```

So the directory isn't created at user creation due to the `-H` on the `adduser`.

Since it's not there already and the `root` user touches that folder via script/daemon-forking later, the ownership is set as `root`.

When the folder *is* there (As it was created via the prior versions `adduser` command.), ownership isn't *changed*.

**Comment by loganhz** [comment]
Thanks Weston! https://github.com/rancher/system-charts/pull/113 submitted a PR for it.

Close in favor of https://github.com/rancher/rancher/issues/23573
