### ISSUE TITLE
service discovery was not working

### ISSUE THREAD

**Issue by liwei0802** [rancher/rancher#23555]
i create workload with image nginx:latest, after created I run 'kubectl get svc' and found not any svc generated, then I manually created item in 'service discovery' tab mapping svc to workloads. But I found not any endpoints when I run 'kubectl describe svc'..
I have to manually expose service via 'kubectl expose deployment' to manually expose service

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.9` UI: `v2.2.98` |
|Route|`authenticated.project.dns.index`|

**Comment by sowmyav27** [comment]
Verified on `rancher:v2.2.9`

**Steps:**

- Deploy an rke cluster.
- Deploy a workload with image: `ubuntu:xenial`
- Do a kubectl get svc. Service discovery is generated for the workload.
```
> kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   x.x.x.x    <none>        443/TCP   4m56s
wk01         ClusterIP   None         <none>        42/TCP    17s
```

**Comment by liwei0802** [comment]
> Verified on rancher:v2.2.9
> Steps:
> 
> Deploy an rke cluster.
> Deploy a workload with image: ubuntu:xenial
> Do a kubectl get svc. Service discovery is generated for the workload.
> 
> > kubectl get svc
> NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
> kubernetes   ClusterIP   x.x.x.x    <none>        443/TCP   4m56s
> wk01         ClusterIP   None         <none>        42/TCP    17s

thanks much for your reply;
My rancher running on single host, I created cluster(1 cluster+1worker) with command generated by rancher(From my existing nodes which are azure VMs).. Then deploy a workload with image: nginx:latest. I have to manually create service/record with option 'The set of pods which match a selector'..
The service never generated itself..
Shall I know what kinds of log can I check for such issue?
Appreciate your help!

**Comment by loganhz** [comment]
are you using xip.io?

**Comment by loganhz** [comment]
Did you deploy the workload via yaml or Rancher API

**Comment by loganhz** [comment]
If you are using Rancher API, please check if the cluster agent pod is running well.

**Comment by adrianovieira** [comment]
This malfunction happened here on 2.4.x and still happens on 2.5.9.

Is there a setup trick to have the service autodiscovery work well as it was (in older versions)?
