### ISSUE TITLE
[backport] Canal readiness probe failed with statuscode 503 for k8s 1.15

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#23558]
[backport] rancher/rancher#23430

**Comment by bmdepesa** [comment]
rancher/rancher:v2.2-head d3dfcff0

* Created 1.15.5 cluster
* Canal deployment correctly contains:
```
- name: USE_POD_CIDR
    value: "true"
```
* CRD is present in cluster: `networksets.crd.projectcalico.org`
* No failing readiness checks observed
