### ISSUE TITLE
prometheus kube state exporter looks for  v1beta1 resources in 1.16.2

### ISSUE THREAD

**Issue by chrisbulgaria** [rancher/rancher#23556]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug likely

**Steps to reproduce (least amount of steps as possible):**
Fresh Rancher launched RKE cluster Kubernetes 1.16.1 , later upgraded to 1.16.2 , enable cluster monitoring.

**Result:**
Flooding of logs of 	exporter-kube-state-cluster-monitoring with below. No other symptoms it seems.

**Other details that may be helpful:**
020 07:53:14.845753 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.DaemonSet: the server could not find the requested resource
E1020 07:53:14.945528 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.ReplicaSet: the server could not find the requested resource
E1020 07:53:14.946056 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.Deployment: the server could not find the requested resource
E1020 07:53:15.846559 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1020 07:53:15.847481 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.DaemonSet: the server could not find the requested resource
E1020 07:53:15.946816 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.ReplicaSet: the server could not find the requested resource
E1020 07:53:15.947610 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.Deployment: the server could not find the requested resource
E1020 07:53:16.848946 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1020 07:53:16.849003 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.DaemonSet: the server could not find the requested resource
E1020 07:53:16.948598 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.ReplicaSet: the server could not find the requested resource
E1020 07:53:16.949074 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.Deployment: the server could not find the requested resource
E1020 07:53:17.852796 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.DaemonSet: the server could not find the requested resource
E1020 07:53:17.852864 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1020 07:53:17.949873 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.ReplicaSet: the server could not find the requested resource
E1020 07:53:17.950558 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.Deployment: the server could not find the requested resource
E1020 07:53:18.854336 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.DaemonSet: the server could not find the requested resource
E1020 07:53:18.854820 1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/builder.go:508: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource

**Environment information**

Rancher v 2.3.1 , Kubernetes 1.16.2, kube state exporter image 	rancher/coreos-kube-state-metrics:v1.5.0

**Comment by jiaqiluo** [comment]
Hi @chrisbulgaria, I am trying to reproduce the bug, is this the steps you did?
```
- run rancher v2.3.0
- add a cluster with k8s 1.16.1
- upgrade rancher to v2.3.1
- upgrade cluster to k8s .1.16.2
- enable the cluster monitoring
- see errors
```
Do I miss anything? 

The issue mentioned there are no other symptoms, do you mean the cluster monitoring still works fine?

**Comment by chrisbulgaria** [comment]
Yes exactly - the “add cluster” is a rancher spawned RKE cluster.
Indeed the cluster seems to work fine apart from the huge logging , in however not so familiar with the monitoring , don’t know whether everything is monitored what should .
Best ,
Christ

**Comment by chrisbulgaria** [comment]
Sorry one step I forgot : I enabled monitoring not only for the cluster but as well for one of the projects in it .

**Comment by twitchax** [comment]
I am actually getting the same issue with a _completely clean_ install of `Rancher v2.3.2` and `Kubernetes v1.16.2`.

Looks like that `kube-state-metrics` is still querying for deployments with the old `apps/v1beta` deployment version, instead of the new (in `1.16.*`) `apps/v1` deployment version.

**Comment by twitchax** [comment]
@chrisbulgaria, as a workaround, I just changed the `exporter-kube-state-cluster-monitoring` to use `bitnami/kube-state-metrics`, and that made the deployment logs go away; however, it introduces log spew for cert stuff since the service account does not have rights to those.

However, my use case was to get proper deployment metrics, so that is fixed, at least. :)

**Comment by chrisbulgaria** [comment]
Ok thanks a lot , indeed it is as well failing on a clean 2.3.2.
Maybe not many people using 1.16 yet ...

**Comment by rpo-fr** [comment]
I confirm, i have the same problème since upgrade to 1.16

**Comment by bernardyoung** [comment]
me too

**Comment by chrisbulgaria** [comment]
Hello @jiaqiluo - did you manage to reproduce ? 
Thanks

**Comment by jiaqiluo** [comment]
This is reproduced in `v2.3-head` 160e3b691 with monitoring `v0.0.6`

steps:
- run rancher v2.3.0
- add a cluster with k8s 1.16.1
- upgrade rancher to v2.3.1
- upgrade cluster to k8s .1.16.2
- enable the cluster monitoring
- check the logs of the pod under worklaod `exporter-kube-state-cluster-monitoring` 
- see errors

**Comment by jiaqiluo** [comment]
@chrisbulgaria  thank you for the feedback. I got this reproduced, the issue is passed to engineer for further investigation

**Comment by deniseschannon** [comment]
Updated in 0.0.6 chart of monitoring.

**Comment by twitchax** [comment]
The Rancher team is awesome.

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher:v2.3-head 5ac58c6d6 with monitoring v0.0.6

Result: no such errors show up any more.

**Comment by Michaellaneous** [comment]
The error is happening again with the following setup:
Rancher 2.4.5
Monitoring 0.11
Logging to Fluentd

**Comment by roman-golovakho** [comment]
had this when I was using image: quay.io/coreos/kube-state-metrics:v1.4.0
switched to latest tag and it solved the issue
