### ISSUE TITLE
Catalog App Install Error: function "splitn" not defined

### ISSUE THREAD

**Issue by armsnyder** [rancher/rancher#23554]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* Install the `external-dns` app into a project.
   * chart version 2.9.3 (current)
   * using its default configuration
   * chart is from the `helm` catalog (https://kubernetes-charts.storage.googleapis.com/)

**Result:**

Error during app installation:

```
Wait helm template failed. Error: parse error in "external-dns/templates/clusterrole.yaml": template: external-dns/templates/clusterrole.yaml:40: function "splitn" not defined : exit status 1
```

**Other details that may be helpful:**

Related issue in the helm repository: https://github.com/helm/charts/issues/18057

The `splitn` function has been in `sprig` since v2.16.0, released in September 2018. Rancher is likely using an old version of Helm.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.1
- Installation option (single install/HA): HA

**Comment by superseb** [comment]
Needs Helm v2.11, merging into https://github.com/rancher/rancher/issues/16971
