### ISSUE TITLE
When there are multiple templates for the same category, catalog listing shows the categories listed multiple times.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2355]
Server version - Build from master oct 15

When there are multiple templates for the same category, catalog listing shows the categories listed multiple times.

In this example: 2 Templates - "Elasticsearch" and "Logstash" have the same category - "ELK".

<img width="835" alt="screen shot 2015-10-16 at 10 12 41 am" src="https://cloud.githubusercontent.com/assets/4266958/10548504/14877558-73f0-11e5-9fe9-a60eb412aa1d.png">

**Comment by prachidamle** [comment]
UI calls API /listTemplates to list all templates - the reponse is a collection of templates and the API response is not arranged per category.
'category' is a property of each template returned by /listTemplates API which the UI uses to group them into categories. This looks like a UI issue.

**Comment by sangeethah** [comment]
Tested with latest UI from master , there is no duplicate category entries when there are multiple templates under a category.
