### ISSUE TITLE
High amount of data send from node-agent to controlplane

### ISSUE THREAD

**Issue by johnjcool** [rancher/rancher#23553]
**What kind of request is this (question):**
We have setup a private cluster on GKE and connect to our company network via VPN (10Mbit/s up and downstream). After this we imported the cluster in our rancher 2.2.8. For the first 2 months it works fine. 

But now we noticed some connection and performance problems of our services. 
After a while of analyzing we saw taht the VPN tunnel dropped packets because the bandwidth was reached every 2 minutes. The node-agents sends 700Mi data over wss every second minute to the controlplane. First we increased the bandwidth up 50 Mbit/s but the transfered 
data increases up to 900Mi and we also noticed connection and perfomance problems

Can you help to fix this problem? Which logs can help to find the issue? How can we analyze which data was send and how can we reduce this data? Are there parameter to send only a minimum of data to the controlplane?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
```
K8s	v2.2.8
User Interface	v2.2.94
Helm	v2.10.0-rancher11
Machine	v0.15.0-rancher8-1
```
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Imported): Imported
- Machine type (cloud) and specifications (CPU/memory): Container-Optimized OS (cos), n1-standard-4
- Kubernetes version (use `kubectl version`): 1.14.7-gke.10

```
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.10", GitCommit:"8cea5f8ae165065f0d35e5
de5dfa2f73617f02d1", GitTreeState:"clean", BuildDate:"2019-10-05T00:09:55Z", GoVersion:"go1.12.9b4", Compiler:"gc",
 Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.10", GitCommit:"8cea5f8ae165065f0d35e5
de5dfa2f73617f02d1", GitTreeState:"clean", BuildDate:"2019-10-05T00:09:55Z", GoVersion:"go1.12.9b4", Compiler:"gc",
 Platform:"linux/amd64"}
```

- Docker version (use `docker version`): 

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.11.2
 Git commit:        2d0083d
 Built:             Tue Sep  3 10:03:35 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       2d0083d
  Built:            Tue Sep  3 10:02:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by ChrisHaPunkt** [comment]
https://forums.rancher.com/t/high-amount-of-data-send-from-node-agent-to-controlplane/15594/3
