### ISSUE TITLE
Kiali

### ISSUE THREAD

**Issue by phaneesh11** [rancher/rancher#23560]
*Describe your issue here*

I have enabled istio injection for default namespace and it is not visible in kiali for default namespace
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.0` UI: `v2.3.15` |
|Route|`authenticated.project.istio.project-istio.graph`|

**Comment by loganhz** [comment]
Please file a new issue and supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md) Thanks!
