### ISSUE TITLE
[forwardport] Not allowed to edit clusters (in 1.14 or 1.14.x) to go to a cluster template with same latest version(1.14.x)

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23578]
Forwardport of rancher/rancher#23489

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by soumyalj** [comment]
Tested with master-head build with UI tag latest. 
Scenario 1:
Scenario 1:
Create a a CT with following revisions:
R1 - K8s version - 1.14
R2 - K8s version - 1.14.x (latest)
Deploy a cluster with R1.

Once cluster is deployed , edit cluster and try to switch templates. R2 is not greyed out.

![Screen Shot 2019-10-26 at 11 46 35 AM](https://user-images.githubusercontent.com/18536626/67624644-2236c980-f7e8-11e9-814f-dc006796ee5e.png)

Scenario2:
Create a a CT with following revisions:
R1 - K8s version - 1.14.x (latest)
R2 - K8s version - 1.14.x (latest)
Deploy a cluster with R1.
Once cluster is deployed , edit cluster and try to switch templates. R2 is not greyed out.

![Screen Shot 2019-10-26 at 11 56 39 AM](https://user-images.githubusercontent.com/18536626/67624642-18ad6180-f7e8-11e9-952e-20fa5eb992c1.png)
