### ISSUE TITLE
Cluster reserved memory&cpu incorrect when multiple STS with same name in diff NS

### ISSUE THREAD

**Issue by GiGurra** [rancher/rancher#23571]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug report

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster
2. Create at least 2 namespaces within a project (I used 3)
3. Create an identical stateful set/with the same name in each namespace (and request some ram/cpu for it). (our actual use case is multiple test environments running their own sql server instances, but the bug appears for any sts)

**Result:**
 - CPU/mem reservations shows incorrect values on the rancher node/cluster view/webpage (even though there are 3 sts running with one instance each, they only get counted once). If you rename one of the sts to something unique, it gets counted :P.
( - Shows correct in kubectl and kube-ops-view (if you have heard of that))

**Other details that may be helpful:**

Works fine with duplicate names for deployments - the bug only affects sts. (I havent tried daemonsets)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  2.2.8
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): onprem/custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3 x 16 gig ram, 4 x cpu
- Kubernetes version (use `kubectl version`): 1.14.6
- Docker version (use `docker version`): 18.9.9

**Comment by alena1108** [comment]
Would be quite an easy fix: we have to either change the key in the map https://github.com/rancher/rancher/blob/b939e5e92b3ad8f9dd2bf65d2e6be588315296de/pkg/controllers/user/nodesyncer/nodessyncer.go#L677 to include the node namespace, or change the data structure to be a slice as there seems to be nothing uses the key

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 5ccf85b5a`

Create a cluster.

Starting view
![Screen Shot 2019-11-19 at 2 06 00 PM](https://user-images.githubusercontent.com/57409052/69188076-0f5aa080-0ad9-11ea-8dbd-cdf4d3369ccd.png)
:

Create multiple namespaces.
Create an identical stateful set with the same name in each namespace and partition some ram and cpu for each. 
![Screen Shot 2019-11-19 at 2 12 44 PM](https://user-images.githubusercontent.com/57409052/69188100-1da8bc80-0ad9-11ea-9bfc-d563df853357.png)

View with one sts initialized:
![Screen Shot 2019-11-19 at 2 22 16 PM](https://user-images.githubusercontent.com/57409052/69188123-2a2d1500-0ad9-11ea-8433-dfe09875adae.png)

View with two sts initialized:
![Screen Shot 2019-11-19 at 2 22 59 PM](https://user-images.githubusercontent.com/57409052/69188132-2ef1c900-0ad9-11ea-89dd-a1eb10fe3f3a.png)

Namespaces:
![Screen Shot 2019-11-19 at 2 23 14 PM](https://user-images.githubusercontent.com/57409052/69188180-42049900-0ad9-11ea-8a03-18536c1a8127.png)

**Comment by aaronRancher** [comment]
Was not able to recreate with Rancher server `rancher\rancher:v2.3-head` `version 3ec12535e`
Create a cluster.

Initial view:
![Screen Shot 2019-11-19 at 4 27 43 PM](https://user-images.githubusercontent.com/57409052/69196019-86e4fb80-0aea-11ea-9b26-00cce5a7a43d.png)

Create multiple namespaces.
Create an identical stateful set with the same name in each namespace and partition some ram and cpu for each.
![Screen Shot 2019-11-19 at 4 34 11 PM](https://user-images.githubusercontent.com/57409052/69196026-8f3d3680-0aea-11ea-99ff-9d960d6699e7.png)

View with one sts:
![Screen Shot 2019-11-19 at 4 30 37 PM](https://user-images.githubusercontent.com/57409052/69196055-9fedac80-0aea-11ea-9d3f-ee0225af84bc.png)

View with two sts:
![Screen Shot 2019-11-19 at 4 32 21 PM](https://user-images.githubusercontent.com/57409052/69196043-982e0800-0aea-11ea-89aa-80f41208d759.png)
Cluster view updates.

Tested with Rancher server `rancher\rancher:master-head` `version 5ccf85b5a`
Create a cluster.
Create multiple namespaces.
Create an identical stateful set with the same name in each namespace and partition some ram and cpu for each.
Cluster view updates.

**Comment by aaronRancher** [comment]
Was not able to recreate with with Rancher server `rancher\rancher:v2.2.8` `version 2.2.8`

Create a cluster.

Initial view:
![Screen Shot 2019-11-20 at 9 34 38 AM](https://user-images.githubusercontent.com/57409052/69258315-a8d98f00-0b79-11ea-9afe-94387d069b9b.png)

Create multiple namespaces.
Create an identical stateful set with the same name in each namespace and partition some ram and cpu for each.
![Screen Shot 2019-11-20 at 9 36 06 AM](https://user-images.githubusercontent.com/57409052/69258350-b1ca6080-0b79-11ea-8083-376bec6da488.png)

View with one sts:
![Screen Shot 2019-11-20 at 9 35 36 AM](https://user-images.githubusercontent.com/57409052/69258404-c27ad680-0b79-11ea-93fc-9071af525dc1.png)

View with two sts:
![Screen Shot 2019-11-20 at 9 36 22 AM](https://user-images.githubusercontent.com/57409052/69258413-c60e5d80-0b79-11ea-9b1d-892465789e65.png)

Cluster view updates.

**Comment by GiGurra** [comment]
How strange. We still have the issue in 2.3.2.

Here is the result from kubectl describe nodes
`╰─>$ kubectl describe nodes s******************
Name:               s**************
Roles:              worker
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    hostname=s***************
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=s*****************
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/worker=true
                    sql-node=true
Annotations:        flannel.alpha.coreos.com/backend-data: ***********
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: ***********
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4IPIPTunnelAddr: ***********
                    rke.cattle.io/external-ip: ***********
                    rke.cattle.io/internal-ip: ***********
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 16 Oct 2019 12:38:40 +0200
Taints:             <none>
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Wed, 20 Nov 2019 17:48:40 +0100   Wed, 06 Nov 2019 14:45:03 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Wed, 20 Nov 2019 17:48:40 +0100   Wed, 06 Nov 2019 14:45:03 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Wed, 20 Nov 2019 17:48:40 +0100   Wed, 06 Nov 2019 14:45:03 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Wed, 20 Nov 2019 17:48:40 +0100   Wed, 06 Nov 2019 14:48:06 +0100   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  ****************
  Hostname:    *****************
Capacity:
 cpu:                4
 ephemeral-storage:  41019616Ki
 hugepages-2Mi:      0
 memory:             16425928Ki
 pods:               110
Allocatable:
 cpu:                4
 ephemeral-storage:  37803678044
 hugepages-2Mi:      0
 memory:             16323528Ki
 pods:               110
System Info:
 Machine ID:                 ***********
 System UUID:                ***********
 Boot ID:                    ***********
 Kernel Version:             4.15.0-65-generic
 OS Image:                   Ubuntu 18.04.3 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.9
 Kubelet Version:            v1.16.2
 Kube-Proxy Version:         v1.16.2
PodCIDR:                     10.42.3.0/24
PodCIDRs:                    10.42.3.0/24
Non-terminated Pods:         (11 in total)
  Namespace                  Name                                     CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                                     ------------  ----------  ---------------  -------------  ---
  cattle-system              cattle-node-agent-ggqwh                  0 (0%)        0 (0%)      0 (0%)           0 (0%)         14d
  default                    sql-server-7758577d46-ccncg              0 (0%)        0 (0%)      0 (0%)           0 (0%)         26d
  digor-ft                   sql-server-0                             500m (12%)    0 (0%)      3Gi (19%)        4Gi (25%)      8d
  digor-st                   sql-server-0                             500m (12%)    0 (0%)      3Gi (19%)        4Gi (25%)      8d
  digor                      sql-server-0                             500m (12%)    0 (0%)      3Gi (19%)        4Gi (25%)      8d
  ingress-nginx              default-http-backend-67cf578fc4-dshvn    10m (0%)      10m (0%)    20Mi (0%)        20Mi (0%)      14d
  ingress-nginx              nginx-ingress-controller-sr4w5           0 (0%)        0 (0%)      0 (0%)           0 (0%)         35d
  kube-system                canal-qjklf                              250m (6%)     0 (0%)      0 (0%)           0 (0%)         14d
  kube-system                coredns-5c59fd465f-hncb4                 100m (2%)     0 (0%)      70Mi (0%)        170Mi (1%)     14d
  kube-system                coredns-autoscaler-d765c8497-wc97g       20m (0%)      0 (0%)      10Mi (0%)        0 (0%)         14d
  kube-system                metrics-server-64f6dffb84-ln7pq          0 (0%)        0 (0%)      0 (0%)           0 (0%)         14d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests      Limits
  --------           --------      ------
  cpu                1880m (47%)   10m (0%)
  memory             9316Mi (58%)  12478Mi (78%)
  ephemeral-storage  0 (0%)        0 (0%)
Events:              <none>
`

and here is the result from rancher dashboard
![usage-3](https://user-images.githubusercontent.com/1761299/69259484-9f264a80-0bbe-11ea-8a55-07ac6b94df34.jpg)

**Comment by aaronRancher** [comment]
Was able to recreate with Rancher server `rancher\rancher:v2.2.8` `version 2.2.8`

The cluster view does not update when running a single node cluster.

Initial view:
![Screen Shot 2019-11-20 at 1 07 55 PM](https://user-images.githubusercontent.com/57409052/69275665-13022c00-0b9a-11ea-9bb8-e243cb9e80b3.png)

View with one sts:
![Screen Shot 2019-11-20 at 1 13 45 PM](https://user-images.githubusercontent.com/57409052/69275722-31682780-0b9a-11ea-9285-68280f1cce9f.png)

View with two sts:
![Screen Shot 2019-11-20 at 1 15 56 PM](https://user-images.githubusercontent.com/57409052/69275739-36c57200-0b9a-11ea-9734-7a8bb8907622.png)

Setup:
![Screen Shot 2019-11-20 at 1 31 49 PM](https://user-images.githubusercontent.com/57409052/69275750-3d53e980-0b9a-11ea-9147-1f5d1e700613.png)

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests     Limits
  --------           --------     ------
  cpu                2380m (59%)  10m (0%)
  memory             356Mi (4%)   190Mi (2%)
  ephemeral-storage  0 (0%)       0 (0%)
```

**Comment by GiGurra** [comment]
Our cluster has 4 nodes though ( 3 shared etcd/ctrl/worker and 1 pure worker).
Management env/rancher-server is single-node however, if you mean that.

**Comment by aaronRancher** [comment]
Recreated with Rancher server `rancher\rancher:v2.2.8` `version 2.2.8` using a multi node cluster.

Bug shows up when sts workloads with the same name are scheduled/land on the same node. 
![Screen Shot 2019-11-20 at 3 28 49 PM](https://user-images.githubusercontent.com/57409052/69283941-a93e4e00-0baa-11ea-83d3-9185d1f30800.png)

Initial view:
![Screen Shot 2019-11-20 at 3 20 57 PM](https://user-images.githubusercontent.com/57409052/69283997-c8d57680-0baa-11ea-9d6e-cf54750114e5.png)

With one sts:
![Screen Shot 2019-11-20 at 3 21 15 PM](https://user-images.githubusercontent.com/57409052/69284024-d559cf00-0baa-11ea-888a-eef91de8a978.png)

With two sts:
![Screen Shot 2019-11-20 at 3 22 19 PM](https://user-images.githubusercontent.com/57409052/69284026-d8ed5600-0baa-11ea-8ad6-19c9ec81cb2a.png)

This bug is not seen in Rancher server `rancher\rancher:master-head` `version ebe495938`
