### ISSUE TITLE
Default values for one of the fields gets truncated during variable substitution.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2357]
Server version - Build from master

Tried to  create a stack using template - "Logstash" from catalog. 
Set LOGSTASH FILTERS to "kv{}" and used defaults for both LOGSTASH INPUTS and LOGSTASH OUTPUTS parameters.

service gets to "Error" state. Substitution  for LOGSTASH INPUTS is  " "udp {\n  port \n" andLOGSTASH OUTPUTS  "2+" both of which are not the default values that were provided.

rancher-compose.yml generated by rancher-server for the service created:
 
```
logstash-indexer-config:
  scale: 1
  metadata: &id002
    logstash:
      filters: |
        kv{}
      inputs: |
        redis {
          host => "redis"
          port => "6379"
          data_type => "list"
          key => "logstash"
        }
      outputs: |2+

redis:
  scale: 1
logstash-collector-config:
  scale: 1
  metadata: &id001
    logstash:
      inputs: "udp {\n  port \n"
      outputs: |
        redis {
          host => "redis"
          port => "6379"
          data_type => "list"
          key => "logstash"
        }
logstash-collector:
  scale: 1
  metadata: *id001
logstash-indexer:
  scale: 1
```

**Comment by vincent99** [comment]
The values are sent to the stack (environment) create correctly, I think this is a bug in rancher-compose.

**Comment by sangeethah** [comment]
Related libcompose PR - https://github.com/docker/libcompose/pull/87

**Comment by sangeethah** [comment]
Tested with rancher-compose version - v0.4.3

When using exported variables that have "=" ,  variable substitution happens as expected.

**Comment by tobowers** [comment]
On further inspection, we don't have start_once set... we're using that stdin: open and cat trick that was needed before start_once. We'll switch over to start_once and see if it still fails. Seems like still a bug doing it the "old" way though.
