### ISSUE TITLE
[Forwardport] Deep nested types are not sent correctly by the UI

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23576]
Forwardport of rancher/rancher#23210

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by sowmyav27** [comment]
**verified on `master-head` - latest**

**ui tag: `latest2`**

- input yaml in cluster (rke cluster)
<img width="490" alt="Screen Shot 2019-11-04 at 7 40 32 PM" src="https://user-images.githubusercontent.com/26032343/68127924-d2b97180-ff3c-11e9-9c91-9d58cf0ff87c.png">

**Request:**
<img width="573" alt="Screen Shot 2019-11-04 at 7 50 45 PM" src="https://user-images.githubusercontent.com/26032343/68127933-d64cf880-ff3c-11e9-96d7-c28cced165dc.png">


- Also verified the depth is increased to 20
- Input yaml:
<img width="591" alt="Screen Shot 2019-11-04 at 7 39 29 PM" src="https://user-images.githubusercontent.com/26032343/68127858-b4537600-ff3c-11e9-9c36-14902dab3168.png">

- Request:
<img width="544" alt="Screen Shot 2019-11-04 at 7 39 56 PM" src="https://user-images.githubusercontent.com/26032343/68127866-b74e6680-ff3c-11e9-82b0-253068d24fc2.png">
