### ISSUE TITLE
[forwardport] White theme helper text too light/bright

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23577]
Forwardport of rancher/rancher#22917

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by soumyalj** [comment]
Tested with master-head (7875bc193c3e) with UI index : ```https://releases.rancher.com/ui/latest2/index.html```
Observed the login page  and the helper text is visible.

<img width="442" alt="Screen Shot 2019-10-25 at 1 06 01 PM" src="https://user-images.githubusercontent.com/18536626/67601499-5e572500-f729-11e9-9ecc-e9147606e318.png">
Helper text in other places are also readable : 

<img width="1667" alt="Screen Shot 2019-10-25 at 1 06 54 PM" src="https://user-images.githubusercontent.com/18536626/67601503-62834280-f729-11e9-90f2-3223d7d94217.png">
