### ISSUE TITLE
Cluster monitoring - fails to enable in master 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23573]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:`master-head` 8d57a1cfb single install (also `v2.3-head d4e5fb2dc`)
- As a standard user, add two clusters: cluster1 with k8s `1.15.5`, cluster2 with k8s `1.16.2`
- notice the monitoring version is `0.0.5` in the `dev` branch of `system-library` catalog
- enable the cluster monitoring in both clusters 

**Result:**
- workload `grafana-cluster-monitoring` is stuck in the `CrashLoopBackOff` loop
- errors in pod `grafana-cluster-monitoring-798bd9b988-h7pkc`
```
2019/10/21 17:36:58 [warn] 1#1: duplicate MIME type "text/html" in /nginx/nginx.conf:55
nginx: [warn] duplicate MIME type "text/html" in /nginx/nginx.conf:55
2019/10/21 17:36:58 [emerg] 1#1: mkdir() "/var/cache/nginx/cache" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/cache" failed (13: Permission denied)
```
- workload `prometheus-cluster-monitoring` is stuck in the `CrashLoopBackOff` loop
- errors in pod `prometheus-cluster-monitoring`
```
cp: can't create '/var/cache/nginx/nginx-start.sh': Permission denied
chmod: /var/cache/nginx/nginx-start.sh: No such file or directory
/bin/sh: /var/cache/nginx/nginx-start.sh: not found
```

**More info:**

disabling the cluster monitoring in the 1.16 cluster can not delete workloads in the namespace `cattle-prometheus`, whcih does not happen in the 1.15 cluster.

**Comment by bmdepesa** [comment]
Also occurs in `v2.3-head`

**Comment by gitlawr** [comment]
https://github.com/nginxinc/docker-nginx/issues/376

**Comment by loganhz** [comment]
Submitted a chart PR to fix it.

FYI, it looks like monitoring UI is broken in master. It only shows 1 graph in cluster dashboard. It works well in 2.3-master.

**Comment by jiaqiluo** [comment]
the cluster monitoring is enabled successfully in v2.3-head 6d40dad33 in the clusters with the following versions:
```
- 1.14.8
- 1.15.5
- 1.16.2
```

the cluster monitoring is enabled successfully in master-head f6a4da476 in the clusters with the following versions:
```
- 1.16.2
```

**Comment by centrnchadm** [comment]
Still happening with 1.17.4
