### ISSUE TITLE
Text changes - forward port to 2.4

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#23575]
**What kind of request is this (question/bug/enhancement/feature request):**
Text changes

**Steps to reproduce (least amount of steps as possible):**
1.  Update Volume Description - original issue: https://github.com/rancher/rancher/issues/23510
2.  Clarify description text for the Delete Reclaim Policy - original issue: https://github.com/rancher/rancher/issues/22600
3.  Clarify 'Labels & Annotations' detail text for non-workload views - original issue: 
https://github.com/rancher/rancher/issues/20329

**Comment by sowmyav27** [comment]
**Verified on latest-`master-head` - ui tag: `https://releases.rancher.com/ui/latest2/index.html`**

1. **Update Volume Description**

- Enable Logging on a cluster (fluentd)
- When the logging has been enabled, go to Project Default --> Workloads --> Deploy --> Volumes section
- The text has been changed as below
<img width="1251" alt="Screen Shot 2019-10-28 at 7 51 52 PM" src="https://user-images.githubusercontent.com/26032343/67686239-67abf000-f9bc-11e9-8341-b81aec623096.png">


2. **Clarify description text for the Delete Reclaim Policy**
Cluster --> Storage Class--> Add Storage Class --> Customize Section --> Reclaim Policy shows text `Delete volumes and underlying device when volume claim is deleted`
<img width="1270" alt="Screen Shot 2019-10-28 at 7 49 03 PM" src="https://user-images.githubusercontent.com/26032343/67686139-40552300-f9bc-11e9-94a2-5a3e4306014e.png">


3. **Clarify 'Labels & Annotations' detail text for non-workload views**
Labels and Annotations show `Key/Value pairs that can be used to label/annotate resources.`
**On create Workload page:**
<img width="1267" alt="Screen Shot 2019-10-28 at 5 43 29 PM" src="https://user-images.githubusercontent.com/26032343/67677670-a20c9180-f9aa-11e9-8130-1b97788b7db2.png">

**On create Ingress page:**
![Screen Shot 2019-10-28 at 5 45 04 PM](https://user-images.githubusercontent.com/26032343/67677712-bcdf0600-f9aa-11e9-9176-c9e3d78332e2.png)

And also on Pod Security Policy --> Add Policy page
