### ISSUE TITLE
Multi Cluster app - Bulk entry of Answers does not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23587]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Add catalog `https://github.com/helm/charts.git`.
2. Go to Global --> Apps --> Launch --> Stolon
3. Under Answers Section, paste the following answers

```
test=one
t2=value2
t3=value3
```

**Expected Result:**
Three answers with above 3 variables and corresponding values should get added

**Actual Result:**
It get pasted in the Variable section on the first answer. 
<img width="1310" alt="Screen Shot 2019-10-22 at 3 09 08 AM" src="https://user-images.githubusercontent.com/26032343/67245389-79037280-f479-11e9-8eae-65942c7f0ec8.png">

**Note:** 
It works in 2.3.1 rancher

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Comment by jiaqiluo** [comment]
ran into the same issue while testing cluster monitoring in master-head 

User Interface: vmaster-dev

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `fa2cbfc57`**

ui tag: latest2

Steps:

- Add catalog https://github.com/helm/charts.git.
- Go to Global --> Apps --> Launch --> Stolon
- Under Answers Section, paste the following answers

```
test=one
t2=value2
t3=value3
```

Three answers with above 3 variables and corresponding values get added

<img width="1256" alt="Screen Shot 2020-01-01 at 12 11 40 PM" src="https://user-images.githubusercontent.com/26032343/71645648-1c4de080-2c90-11ea-9a5c-2973b9a2acb3.png">

Closing the issue
