### ISSUE TITLE
Helm charts not found at https://releases.rancher.com/server-charts

### ISSUE THREAD

**Issue by metrafonic** [rancher/rancher#23588]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

```
helm repo add rancher-stable https://releases.rancher.com/server-charts/stable

helm install rancher-stable/rancher \
  --name rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org
```

**Result:**
```
 Error: render error in "rancher/templates/deployment.yaml": template: rancher/templates/deployment.yaml:76:7: executing "rancher/templates/deployment.yaml" at <gt .Values.auditLog.level 0.0>: error calling gt: incompatible types for comparison
```
Content at https://releases.rancher.com/server-charts/stable
```
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: releases.rancher.com/server-charts/stable</Details></Error>
```
**Other details that may be helpful:**

Is it correct that i should not be able to access https://releases.rancher.com/server-charts/stable in my browser? It gives me the error shown above

**Environment information**

Following the HA kubernetes guide https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/23516

**Comment by naveen230** [comment]
@superseb still having the issue when trying to upgrade rancher with new ssl certificates
"helm get values rancher" returns
Error: release: "rancher" not found

helm repo list returns
NAME URL
stable https://kubernetes-charts.storage.googleapis.com
local http://127.0.0.1:8879/charts
rancher-stable https://releases.rancher.com/server-charts/stable
jetstack https://charts.jetstack.io

helm version
Client: &version.Version{SemVer:"v2.16.2", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.2", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
