### ISSUE TITLE
Set docker_root option when starting cAdvisor

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#2358]
cAdvisor does not currently work if the storage root is anything other than the default `/var/lib/docker`.

https://github.com/rancher/python-agent/blob/837406c64602789079fa16a6f836c54fb165e534/cattle/plugins/cadvisor/cadvisor.py#L10-L13

**Comment by ibuildthecloud** [comment]
Now that makes sense....  Been meaning to figure that one out.

**Comment by deniseschannon** [comment]
We are no longer using cadvisor as of v1.2.0 instead we're using `docker stats` for container stats and https://github.com/shirou/gopsutil for host stats.
