### ISSUE TITLE
[forwardport] UI Updates for vSphere Templates

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23583]
Forward port of:
- rancher/rancher#21580
- rancher/rancher#23031
- rancher/rancher#23002
- rancher/rancher#19032

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by aaronRancher** [comment]
Tested in `rancher\rancher:master-head` `version 781cd0fdc`.

Fields are populated by data from vCenter:
- Datacenter
- Resource Pool
- Data store
- Folder
- Host
- Networks
- Tags
- Custom Attributes
User is able to select creation method
Fields are updated and populated based on creation method
Deploy from RancherOS ISO is marked as deprecated
Install from Boot2Docker ISO (Legacy) added

Tags are retrieved from vCenter and displayed in a dropdown.
Multiple tags can be added
When node is created from template, the tags are assigned correctly.

Created vSphere node template
All fields are being sent as strings:
```
cpuCount: "2"
diskSize: "20000"
memorySize: "2048"
sshPort: "22"
vcenterPort: "443"
```
