### ISSUE TITLE
Remove "istio-virtual-service-ui" feature flag

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23582]
rancher/rancher:v2.3-head

Now that there is UI support for Istio gateways, there is no need to hide Virtual Services & Destination Rules. 

Currently, the feature flag seems to have no effect. It is set to `false` by default, and all Istio navigation tabs are shown.

**Comment by deniseschannon** [comment]
@loganhz has something changed in release/v2.3 that would make it so that all the istio navigation shown?

**Comment by bmdepesa** [comment]
All navigation being shown only started after Gateway UI was merged.

**Comment by loganhz** [comment]
@deniseschannon Yes. In 2.3-master, they will show by default. Can I remove the feature flag or we should still use the feature flag and hide it by default?

**Comment by deniseschannon** [comment]
@loganhz i don't believe we should remove teh feature flag but it should be turned on by default. is that what's happening now?

**Comment by loganhz** [comment]
If we want to keep the feature flag and set it to `true` by default. Please merge https://github.com/rancher/ui/pull/3494 and https://github.com/rancher/rancher/pull/23625

If we want to remove the feature flag directly. Please merge https://github.com/rancher/rancher/pull/23624

**Comment by deniseschannon** [comment]
@loganhz We've decided to move forward with setting the feature flag to true by default. Can you please make forwardport PRs for the UI and backend?

**Comment by westlywright** [comment]
Available in `2.3-fixes`

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head cd74c3592
UI: latest-2.3

* `istio-virtual-service-ui` feature flag is enabled by default and UI features are shown
* When flag is set to `false` the UI features are hidden
