### ISSUE TITLE
Add max_rancher_version to existing old charts

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#23594]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):** 
1. Add `max_rancher_version` to existing charts that are not compatible with k8s 1.16
2. All those old templates with `max_rancher_version: 2.2.99` label should not appear in rancher `v2.3.0`.
3. The user should be able to view the old template version chart if upgrade from the previous version like Rancher 2.2.8 to 2.3.0.

**Comment by guangbochen** [comment]
link PR to https://github.com/rancher/charts/pull/300

**Comment by deniseschannon** [comment]
Since v2.3.0 and v2.3.1 shipped with k8s 1.15 as default, all those old templates with max_rancher_version: `2.3.1` label should not appear in rancher v2.3.2.

**Comment by jiaqiluo** [comment]
the expected chart versions are from https://github.com/rancher/rancher/issues/22005

**Comment by jiaqiluo** [comment]
Here is the list of apps and their versions show in v2.3.2-rc1 

App | Template version
-- | --
etcd-operator | 0.9.0
vault-operator | 0.1.3
chartmuseum | 2.3.1
drone | 2.0.7
traefik | 1.0.0
docker-registry | 1.8.1
memcached | 2.9.0
nfs-server | 0.3.0
mongodb-replicaset | 3.9.6
kubernetes dashboard | 1.8.0
efk | 7.3.0
datadog | 1.33.0
Hadoop | 1.1.1
grafana | 3.8.6
prometheus | 9.1.0
mariadb | 6.7.4
mongodb | 7.2.6
wordpress | 7.3.8
Harbor | 1.2.0
phpbb | 6.0.1
Fluentd-aggregator | 0.3.1
redis | 9.0.2
redskyops | 0.1.1
Kafka | 0.8.0
Magento | 5.1.4
Harbor | 1.2.0
mysql | 1.3.1

---------------

Istio has an issue https://github.com/rancher/rancher/issues/23660

**Comment by jiaqiluo** [comment]
will do this upgrade test: 
- install 2.2.9
- add cluster 1.15.5 
- install some apps from the list 
- upgrade to 2.3.2.-rc2
- the apps should work, edit variables (except version) should take effect 
- upgrade app1 to the current version presented
- app1 should work, edit variables (except version) should take effect
- NOT upgrade app2
- upgrade the cluster to 1.16
- app1 should continue to work, edit variables (except version) should take effect 
- the app2 should still work, but it will fail if edit the variable and save
- upgrade app2 to current supported version
- app2 should work now

**Comment by jiaqiluo** [comment]
If the template version is deprecated for the upgraded Rancher version, then the old app cannot be edited.
