### ISSUE TITLE
[UI] Partner apps label is hard to read in Dark Mode - Forward port to 2.4

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#23593]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement/Bug - original issue https://github.com/rancher/rancher/issues/22859

**Steps to reproduce (least amount of steps as possible):**
Use Dark Mode from Preferences.
Go to Apps in Global/Projects, check the Partners App labels.

**Result:**

The contrast of that word plus combined with the gold color that surrounds it makes it hard to read.

![Screen Shot 2019-09-13 at 1 39 06 PM](https://user-images.githubusercontent.com/27659/64893555-305fca80-d62c-11e9-906d-c79e2fd7473d.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version: `master-head (v2.3) (09/13/2019)`
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by izaac** [comment]
Verified on `2.4 master-head 902c8ba19`
ui: `vmaster-dev`

- Use Dark Mode from Preferences.
- Go to Apps in Global/Projects, check the Partners App labels.
- Partner apps labels are easily readable in Dark Mode

User experience is way better now.

<img width="1317" alt="Screen Shot 2019-11-27 at 8 08 26 AM" src="https://user-images.githubusercontent.com/27659/69739363-d2a03200-10f4-11ea-9689-cc82f31d8fef.png">
