### ISSUE TITLE
Rancher CLI does not work with 2.3.1

### ISSUE THREAD

**Issue by AnSmol** [rancher/rancher#23597]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Rancher CLI v0.6.14 connect to Rancher 2.3.1

**Result:**

```
Bad response statusCode [404]. Status [404 Not Found]. Body: [404 page not found
] from [https://rancher.domain.com/v2-beta]

```
**Other details that may be helpful:**
Looks like Rancher 2.3.1 has only /v3 api endpoint. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher 2.3.1 deployed on RancherOS
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
You can use the link in the UI for the CLI needed for that version (bottom right), for Rancher v1.6.x, that is v0.6.x and for Rancher v2.3.x, it's v2.3.x. See https://github.com/rancher/cli/releases
