### ISSUE TITLE
cattle-prometheus  -  waiting for cluster agent to connect - Unavailable cluster

### ISSUE THREAD

**Issue by ok2uec** [rancher/rancher#23596]
Hello,
 
I have a problem, after upgrading the kubernetes cluster from 1.15 to 1.16.2, rancher2 showed me a problem with cattle-prometheus and prevented me from working with the cluster.

**I need to guide you how to solve it. There is a lot of advice on google, but no working. **

**what with this?**

Thank you!    

```
This cluster is currently Unavailable; areas that interact directly with it will not be available until the API is ready.

Failed to ensure monitoring project name: failed to find "cattle-prometheus" Namespace: Get https://10.96.0.1:443/api/v1/namespaces/cattle-prometheus?timeout=30s: waiting for cluster agent to connect; Failed to communicate with API server: Get https://10.96.0.1:443/api/v1/componentstatuses?timeout=30s: waiting for cluster agent to connect
```
![Screenshot from 2019-10-22 09-36-59](https://user-images.githubusercontent.com/6108616/67266070-96533380-f4af-11e9-8140-c8811c904f7b.png)

--
```
[s1d55se@kmaster works]$ kubectl get all -n cattle-prometheus
NAME                                         READY   STATUS    RESTARTS   AGE
pod/exporter-node-cluster-monitoring-9z7vr   1/1     Running   4          6d16h
pod/exporter-node-cluster-monitoring-c766x   1/1     Running   1          6d16h
pod/exporter-node-cluster-monitoring-hrqcn   1/1     Running   3          6d16h
pod/exporter-node-cluster-monitoring-mw7fq   1/1     Running   4          6d16h
pod/exporter-node-cluster-monitoring-v9kj4   1/1     Running   5          6d16h

NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/access-grafana              ClusterIP   10.102.228.31    <none>        80/TCP              6d16h
service/access-prometheus           ClusterIP   10.111.155.113   <none>        80/TCP              6d16h
service/expose-grafana-metrics      ClusterIP   None             <none>        3000/TCP            6d16h
service/expose-kubelets-metrics     ClusterIP   None             <none>        10250/TCP           6d16h
service/expose-kubernetes-metrics   ClusterIP   None             <none>        8080/TCP,8081/TCP   6d16h
service/expose-node-metrics         ClusterIP   None             <none>        9796/TCP            6d16h
service/expose-operator-metrics     ClusterIP   None             <none>        8080/TCP            6d16h
service/expose-prometheus-metrics   ClusterIP   None             <none>        9090/TCP            6d16h

NAME                                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
daemonset.apps/exporter-node-cluster-monitoring   5         5         5       5            5           beta.kubernetes.io/os=linux   6d16h
```
--
```
NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)
service/kubernetes                ClusterIP   10.96.0.1       <none>        443/TCP
```
 
 
**Environment information**
- Cluster 5 Nodes (1master , 4 worker)
- PV, LB, DB .... extra VM

HW - Dedicated Server + Proxmox Virtual Environment 5.4-13
(2*12 CPU + 256GB RAM + 1TB SSD)

For Rancher2 special Virtual Machine 
rancher/rancher     stable 
(PV folder /opt/rancher)

**Component | Version**
xxx production cluster | v2.2.4
User Interface | v2.2.70
Helm | v2.10.0-rancher11
Machine | v0.15.0-rancher8-1

All Virtual Machine - Centos 

---

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Client: Docker Engine - Community
Version:           19.03.4

**Comment by ok2uec** [comment]
After upgrade kubernetes, rancher does not have the right to read the API.

Through a proxy API is available without authorization. 
- ssh  -NL 8001:127.0.0.1:8001 root@xxxxx.cz 
- kubectl proxy

Now I am solving how to fix it.

**Comment by ricardo-aspira** [comment]
Did you solve that ?

**Comment by myl82** [comment]
@ok2uec Same question... How did you solve that?

**Comment by xuxusheng** [comment]
same question
![image](https://user-images.githubusercontent.com/15248446/85200472-58522c00-b32a-11ea-91e8-3062a6c4547a.png)

**Comment by ok2uec** [comment]
> @ok2uec Same question... How did you solve that?

Manual start "node agents - cattle", over ssh terminal in master node. 

(Hidden containers agents - only runs) 
(Not started new container witch image)

Sorry my english...

**Comment by veselinn** [comment]
@ok2uec How do you manually start [`cattle-node-agent`](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/rancher-agents/#cattle-node-agent) when connected over ssh to the master node?

Sorry for the silly question :blush:

**Comment by tulid** [comment]
> @ok2uec How do you manually start [`cattle-node-agent`](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/rancher-agents/#cattle-node-agent) when connected over ssh to the master node?
> 
> Sorry for the silly question
`docker ps -a | grep "cattle-node"`

`docker restart <caontainers_id> `

**Comment by hhstu** [comment]
kubectl  delete  cluster  -n  fleet-default   {{ clustername}}  and restart rancher 、 rancher agent, then rancher will auto generator a new kubeconfig.
