### ISSUE TITLE
[forwardport] Convert a existing cluster to start using RKE templates

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#23608]
[forwardport] https://github.com/rancher/rancher/issues/22992

**Comment by soumyalj** [comment]
Tested with master-head from Dec 4(f6feafa9af2b)
1. Created RKE template(T1) and revision (R1) with K8s version v1.14.9. Created cluster with R1
and cluster came up successfully. Created revision R2 (v1.15.6) . Edited cluster and changed revision to R2. Cluster got updated successfully to K8s v1.15.6 
2. 
   a. As a global admin, create a cluster template T1 and revision R1 with cluster level monitoring enabled in the yml file. 
   b.Create a standard user “user1". Share the template T1 to "user1"
  c. Login as “user1” and  deploy a cluster using this template T1/R1
Cluster came up successfully and monitoring was functional in the cluster.

**Comment by soumyalj** [comment]
Tested with master-head from Dec 4(f6feafa9af2b)
Feature to export a RKE template from an existing cluster is functional.
Tests executed:
1. Export rke template/revision (T1/R1) from an existing cluster. Create a cluster C1 using R1
2. Create a new revision from R2 from R1. Create a cluster C2 using R2
3. Edit cluster C1 and change revision to R2
4. Export rke template/revision (T1/R1) from an existing cluster. Create a cluster C1 using R1
5. Create another revision R2 (by cloning R1) with overrides for K8s version and other fields
6. Create a cluster with S3 configuration parameters set. Export rke template from the cluster (T1/R1) and create another cluster using R1. The cluster gets created successfully with all S3 config parameters and the cluster is functional.

Cluster template automation tests on master-head worked fine.
