### ISSUE TITLE
[forwardport] UI issue while creating an EKS cluster

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23609]
Forward port of rancher/rancher#23493

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by sowmyav27** [comment]
**Verified on master-head - latest**
ui tag: `https://releases.rancher.com/ui/latest2/index.html`

**Steps:**

- On rancher UI, create an EKS cluster
- Give in cluster name, access key and secret key and click on next.
- Select required Cluster Options and click on Next: Select VPC & Subnet.
- Select required VPC & Subnet Click on Next: Select Instance options
- Select Node Options and click on Create
- The create button changes to Saving on the same page
- UI directs the user to Clusters page and show that the EKS cluster is deploying.
