### ISSUE TITLE
Open shell/logs in new window

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2360]
In the UI, it would be nice to be able to detach both the logs and shell access to a container so multiple ones can be used simultaneously.

**Comment by zijam** [comment]
+1

**Comment by nhumrich** [comment]
:+1:

**Comment by fernandoneto** [comment]
+1

**Comment by alejom99** [comment]
+1

**Comment by rvion** [comment]
+1

**Comment by pedrommone** [comment]
:+1:

**Comment by vincent99** [comment]
This would have to do some interesting magic to keep a socket open and the terminal open while transferring it to a new window, but I think is possible...

**Comment by will-chan** [comment]
or open it up detached already.

**Comment by vincent99** [comment]
As an option if you hold the alternate key (Cmd on mac, Ctrl on others) while clicking the action, with a ProTip in the dialog to tell you about it.

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed/added
