### ISSUE TITLE
Incorrect K8s version is displayed on a cluster edit when changing from revision with v13.12 to v1.14(Latest)

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#23616]
Version v2.3-head

Steps
1. Create a cluster template T1 and Revision R1 using K8s version v1.13.2-rancher1-1 (no override)
2. Create revision R2 using K8s version v1.14(Latest) (no override)
3. Create a cluster using R1
4. Edit the cluster and choose R2. 
The K8s version points to v1.13.2-rancher1-1 in the dropdown and it becomes an override
<img width="1289" alt="Screen Shot 2019-10-22 at 5 14 21 PM" src="https://user-images.githubusercontent.com/18536626/67345316-73487400-f4ef-11e9-95f6-c08e841b94de.png">

If the user clicks on the dropdown, the correct Latest v1.14.x is displayed which the users can choose from.

<img width="410" alt="Screen Shot 2019-10-23 at 11 27 17 AM" src="https://user-images.githubusercontent.com/18536626/67423114-86f3e900-f588-11e9-9aa0-9b7126351f5f.png">

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by soumyalj** [comment]
Tested with rancher v2.3.2-rc2 using UI tag `latest-2.3`
Create a cluster template T1 and Revision R1 using K8s version v1.14.8-rancher1-1 (no override)
Create revision R2 using K8s version v1.15(Latest) (no override)
Create a cluster using R1
Edit the cluster and choose R2. The K8s version points to v1.15.5-rancher1-2 as expected
<img width="1689" alt="Screen Shot 2019-10-25 at 4 03 01 PM" src="https://user-images.githubusercontent.com/18536626/67609331-02989600-f741-11e9-91d2-ffb6969acb8a.png">
