### ISSUE TITLE
[forwardport] Upgrade to 2.3.0 causes Projects with malformed certs to fail to display in the UI

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#23620]
Forwardport https://github.com/rancher/rancher/issues/23285

**Comment by sowmyav27** [comment]
verified the issue and the fix.

**Steps:**

- On rancher:v2.2.8, deploy an rke cluster.
- Deploy Cert Manager on a cluster - project on Rancher UI (default project)
- Deploy a certificate from kubectl into a namespace
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  commonName: example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
```

- edit the cert - kubectl edit secret <name> -n <namespace> and change the `tls.key` or `tls.cert` value. (to make this cert and invalid one)
- Save the changes made.
- Now upgrade rancher to **`rancher:v2.3.0`**
- Navigate to Cluster --> Default Project
- Error is seen on the UI

<img width="1047" alt="Screen Shot 2019-10-25 at 11 04 28 PM" src="https://user-images.githubusercontent.com/26032343/67591817-e2d29380-f77b-11e9-8ce7-207162cfa784.png">

- request Response error: `{"baseType":"error","code":"InvalidBodyContent","fieldName":"certs","message":"failed to decode key: not valid pem format","status":422,"type":"error"}`

- Upgrade rancher to master-head - latest (10/25/2019)
- Navigate to Cluster --> Default Project
- No error is seen on the UI.
- Error is seen in logs:
```
2019/10/25 17:39:37 [ERROR] Error certs=InvalidBodyContent 422: failed to decode key: not valid pem format parsing cert selfsigned-cert-tls. Will not display correctly in UI
2019/10/25 17:39:37 [ERROR] Error certs=InvalidBodyContent 422: failed to decode key: not valid pem format parsing cert selfsigned-cert-tls. Will not display correctly in UI
2019/10/25 17:39:37 [ERROR] Error certs=InvalidBodyContent 422: failed to decode key: not valid pem format parsing cert selfsigned-cert-tls. Will not display correctly in UI
2019/10/25 17:39:37 [ERROR] Error certs=InvalidBodyContent 422: failed to decode key: not valid pem format parsing cert selfsigned-cert-tls. Will not display correctly in UI
```
