### ISSUE TITLE
AWS ELB Setup

### ISSUE THREAD

**Issue by DaveBlooman** [rancher/rancher#2362]
I decided to change our Rancher setup to include a ELB as the latest version we just pulled now supports it.  I'm having trouble working out why the web sockets aren't working and wondering if its a ports issue or an Apache issue.  

My setup is using an ELB with HTTP, below is a cloudformation sninppet.  

```json
{
  "LoadBalancerSecurityGroup": {
    "Type": "AWS::EC2::SecurityGroup",
    "Properties": {
      "SecurityGroupIngress": [
        {
          "ToPort": 80,
          "IpProtocol": "tcp",
          "FromPort": 80,
          "CidrIp": "0.0.0.0/0"
        },
        {
          "ToPort": 4500,
          "IpProtocol": "tcp",
          "FromPort": 4500,
          "CidrIp": "0.0.0.0/0"
        },
        {
          "ToPort": 500,
          "IpProtocol": "tcp",
          "FromPort": 500,
          "CidrIp": "0.0.0.0/0"
        }
      ],
      "VpcId": {
        "Ref": "VpcId"
      },
      "GroupDescription": "An ELB group allowing access only to from the corresponding component"
    }
  },
  "ComponentSecurityGroup": {
    "Type": "AWS::EC2::SecurityGroup",
    "Properties": {
      "SecurityGroupIngress": [
        {
          "FromPort": 7080,
          "ToPort": 7080,
          "IpProtocol": "tcp",
          "SourceSecurityGroupId": {
            "Ref": "LoadBalancerSecurityGroup"
          }
        },
        {
          "FromPort": 4500,
          "ToPort": 4500,
          "IpProtocol": "udp",
          "SourceSecurityGroupId": {
            "Ref": "LoadBalancerSecurityGroup"
          }
        },
        {
          "FromPort": 500,
          "ToPort": 500,
          "IpProtocol": "udp",
          "SourceSecurityGroupId": {
            "Ref": "LoadBalancerSecurityGroup"
          }
        }
      ],
      "VpcId": {
        "Ref": "VpcId"
      },
      "GroupDescription": "A component security group allowing access only from the corresponding ELB"
    }
  },
  "ComponentElasticLoadBalancer": {
    "Type": "AWS::ElasticLoadBalancing::LoadBalancer",
    "Properties": {
      "CrossZone": true,
      "Subnets": [
        {
          "Ref": "PublicSubnet1Id"
        },
        {
          "Ref": "PublicSubnet2Id"
        },
        {
          "Ref": "PublicSubnet3Id"
        }
      ],
      "Listeners": [
        {
          "InstancePort": 7080,
          "LoadBalancerPort": 80,
          "Protocol": "tcp",
          "InstanceProtocol": "tcp"
        },
        {
          "InstancePort": 4500,
          "LoadBalancerPort": 4500,
          "Protocol": "tcp",
          "InstanceProtocol": "tcp"
        },
        {
          "InstancePort": 500,
          "LoadBalancerPort": 500,
          "Protocol": "tcp",
          "InstanceProtocol": "tcp"
        }
      ],
      "SecurityGroups": [
        {
          "Ref": "LoadBalancerSecurityGroup"
        }
      ],
      "Policies": [
        {
          "PolicyName": "EnableProxyProtocol",
          "InstancePorts": [
            "80"
          ],
          "PolicyType": "ProxyProtocolPolicyType",
          "Attributes": [
            {
              "Name": "ProxyProtocol",
              "Value": "true"
            }
          ]
        }
      ]
    }
  }
}

```

I am using Apache as a proxy, with all traffic going via port 80 to 7080 which forwards on to 8080.  This will later form part of a SSL termination setup which is done on the instance.  For now though, HTTP should work fine.

Initially, the service didn't work at all until i used the Apache conf in the SSL guide, here is my final Apache conf that works.  

```apache
Listen 7080

<IfModule mpm_prefork_module>
    ServerLimit          512
    MaxClients           512
    StartServers         128
    MinSpareServers      64
    MaxSpareServers      128
    MaxRequestsPerChild  100
</IfModule>

<VirtualHost *:7080>

ServerName localhost

Timeout 40
KeepAlive on
KeepAliveTimeout 15

RequestHeader unset SSLClientCertIssuer
RequestHeader unset SSLClientCertNotValidAfter
RequestHeader unset SSLClientCertNotValidBefore
RequestHeader unset SSLClientCertSerialNumber
RequestHeader unset SSLClientCertSignatureAlgorithm
RequestHeader unset SSLClientCertStatus
RequestHeader unset SSLClientCertSubject
RequestHeader unset SSLClientCertSubjectPublicKey
RequestHeader unset SSLClientCertVersion
RequestHeader unset SSLClientCipher
RequestHeader unset SSLSessionID

ProxyRequests Off

<Proxy *>
    Order deny,allow
    Allow from all
</Proxy>

ProxyPreserveHost On

  RewriteEngine On
  RewriteCond %{HTTP:Connection} Upgrade [NC]
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteRule /(.*) ws://localhost:8080/$1 [P,L]


  <Location />
    ProxyPass "http://localhost:8080/"
    ProxyPassReverse "http://localhost:8080/"
  </Location>
</VirtualHost>
```

Finally, I am having trouble actually getting slaves to connect to the master, is this because the slaves talk over WS too?  

Security groups for slaves look like this 

![screenshot 2015-10-17 20 59 47](https://cloud.githubusercontent.com/assets/1492067/10560948/1412cac8-7512-11e5-816b-c2137fefb859.png)

Running behind an ELB is has a lot of benefits for us, hence why i'm moving it over, hopefully it's something simple I have missed.

**Comment by vincent99** [comment]
Yes, agent communication is WebSocket too.  Is there a reason you're involving Apache at all instead of ELB (with SSL termination if desired) straight to Rancher?  

Do you have a module loaded to handle proxy protocol?  Do any (non WebSocket) requests make it through and back? (i.e. loading the UI)

What needs to make it to Rancher is either a Proxy Protocol leader or X-Forwarded-{Port,Host,Proto} headers so that it can construct absolute URLs with the correct info.

**Comment by DaveBlooman** [comment]
Eventually I will be using SSL, but at BBC we use certs baked onto instances rather than directly onto the ELB.  I want to cut SSL out of the equation for now though.

I don't have a module loaded no, the full apache config is above, so I guess I should carry on there.  Do you have any docs on this sort of configuration?

**Comment by vincent99** [comment]
I would think you'd need to load and enable something like http://roadrunner2.github.io/mod-proxy-protocol/mod_proxy_protocol.html or https://github.com/ggrandes/apache24-modules to handle the proxy protocol coming from ELB..

Then `mod_proxy` adds `X-Forwarded-Host`, but not `-Proto` or `-Port` to the Apache -> Rancher segment, so add `mod_headers` if not already enabled and
```
Header set X-Forwarded-Proto "http"
Header set X-Forwarded-Port "8080"
```

**Comment by deniseschannon** [comment]
@DaveBlooman Please re-open if you still have any remaining questions on this setup. 

Also, here is some documentation about requirements for when using AWS ELB. 

http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/#running-rancher-server-behind-an-ELB-in-AWS-with-ssl
