### ISSUE TITLE
Rancher monitoring pod metrics not working for imported cluster

### ISSUE THREAD

**Issue by nathankodilla** [rancher/rancher#23628]
With imported clusters (kubernetes 12.x & 13.x tested) created by kops, Rancher Monitoring only displays gathers/displays cpu/ram usage metrics for nodes and not pods themselves. I have tested both Monitoring 0.0.3 & 0.0.4 and Rancher versions 2.2x but am currently on 2.3.1. When looking at both workload and pod metrics in the Rancher UI they will show "Not enough data for graph" no matter what time period you select. Going into Grafana, it will only show the cpu/ram limits and requests but not actual usage. I can confirm previously we had a cluster on 1.11.6 and these features worked for that version.

Rancher version: 2.3.1
Rancher monitoring version: 0.0.4
Kubernetes version: 1.13.5
Kops version: 1.13.0

**Comment by loganhz** [comment]
Can you check the targets in prometheus UI? Some targets might be red in prometheus ui

**Comment by nathankodilla** [comment]
Some targets are indeed red in the prometheus UI
![image](https://user-images.githubusercontent.com/22841858/67633240-d9345300-f883-11e9-90f5-fa8837a70c4b.png)

**Comment by loganhz** [comment]
Could you try https://github.com/rancher/rancher/issues/20546#issuecomment-501488156 , please?

**Comment by nathankodilla** [comment]
That value will not stick. Every-time I click save it will just reload and that answer will be gone from the list.

**Comment by zacharysells** [comment]
I'm experiencing the same thing. `cattle-prometheus/exporter-kubelets-cluster-monitoring` target is down in the prometheus UI. Adding `exporter-kubelets.https = true` in the monitoring config page will never actually save

**Comment by phthano** [comment]
I am experiencing the same thing, ```exporter-kubelets.https = true``` is enabled and still having the issue.

**Comment by loganhz** [comment]
how about exporter-kubelets.https = false

**Comment by phthano** [comment]
@loganhz I also did try that, and it did not change anything. It's an ICP cluster I imported from if that matters. All the targets are green

**Comment by phthano** [comment]
And I'm on 2.3.2.

**Comment by vitobotta** [comment]
Hi! I just enabled monitoring for an imported k3s cluster. I can see metrics in Grafana for individual pods, but nothing for deployments/statefulsets/daemonsets. Is this normal with k3s/imported clusters?

**Comment by huegelc** [comment]
Same issue here:
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/6955465/70167076-437fb500-16c6-11ea-9a2e-59a7b4ede29d.png">

**Comment by huegelc** [comment]
Ok it turned out there were some missing iptables rules on the nodes:

```
firewall-cmd --add-port=10250/tcp --permanent
firewall-cmd --add-port=10251/tcp --permanent
firewall-cmd --add-port=10252/tcp --permanent
firewall-cmd --add-port=10254/tcp --permanent
firewall-cmd --add-port=9796/tcp --permanent
firewall-cmd --reload
```
and re-deploying  	`exporter-node-cluster-monitoring` fixed it for me.

Cheers

**Comment by huegelc** [comment]
I found the issue in my case. It turned out that following pods were getting IP addresses from a different ippool than the default

` kubectl annotate namespace cattle-prometheus "cni.projectcalico.org/ipv4pools"='["default-ipv4-ippool"]'`

and 

```
kubectl delete po -n cattle-prometheus           exporter-node-cluster-monitoring-q7xbh 
kubectl delete po -n cattle-prometheus           grafana-cluster-monitoring-65cbc8749-79bb8                  
kubectl delete po -n cattle-prometheus           prometheus-cluster-monitoring-0 
```
fixed it

**Comment by lxkaka** [comment]
@loganhz add `exporter-kubelets.https=false` can resolve. Thanks!
