### ISSUE TITLE
extra_env arguments wrongly reformatted on RKE template upon template save

### ISSUE THREAD

**Issue by panlith** [rancher/rancher#23631]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
While creating an RKE template on Rancher v2.3.1, edit the template as YAML from UI and provide `extra_env` arguments similar to the following:
```
      extra_env:
        - 'HTTP_PROXY=http://test.test.com:8080/'
        - 'NO_PROXY=localhost,127.0.0.1,127.0.0.0,127.0.0.*,0.0.0.0,localaddress,test.test.com,10.0.0.0/8,10.,10*'
```
**Result:**
-Template has been created, but listing the YAML from UI shows the last entry unquoted along with `>-` characters added in the last entry.

```
      extra_env:
        - 'HTTP_PROXY=http://test.test.com:8080/'
        - >-
          NO_PROXY=localhost,127.0.0.1,127.0.0.0,127.0.0.*,0.0.0.0,localaddress,test.test.com,10.0.0.0/8,10.,10*
```

Expectation was that should remain quoted.

**Comment by vincent99** [comment]
There are many ways to represent strings in YAML and those are both equivalent (represent the same array of 2 strings).  

What is really being stored and manipulated is JSON, so it is not possible to guarantee that the YAML provided round-trips from YAML->JSON->YAML and produces exactly the same format as the original.
