### ISSUE TITLE
[forwardport] 2.3.0 upgrade - cattle-cluster-agent & cattle-node-agent CrashLoopBackOff

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#23634]
https://github.com/rancher/rancher/issues/23441

**Comment by alena1108** [comment]
LGTM

**Comment by kinarashah** [comment]
Thank you @alena1108 🙂

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 17a40f50

* Fresh install of v2.2.8 in HA
  * `--set tls=external`
  * Reproduced original issue
    * cacerts is set
    * `--no-cacerts` is missing from Rancher deployment
    * Created a cluster
      * Node and cluster agents are in a crash loop backoff
    * `CATTLE_CA_CHECKSUM` value is present in all agents
* Upgrade to v2.4/master-head
  * `cacerts` is cleared
  * `--no-cacerts` is correctly added to the Rancher deployment
  * `CATTLE_CA_CHECKSUM` is removed from all agents
  * All agents deploy successfully
  * All workloads in system projects are functional
  * All clusters available.
