### ISSUE TITLE
extra_bind arguments wrongly reformatted on RKE template upon template save

### ISSUE THREAD

**Issue by panlith** [rancher/rancher#23630]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
-While creating an RKE template on Rancher v2.3.1, edit the template as YAML from UI and provide `extra_bind` arguments similar to the following:
```
      extra_binds:
        - '/etc/iscsi:/etc/iscsi'
        - '/sbin/iscsiadm:/sbin/iscsiadm'
        - '/var/lib/iscsi:/var/lib/iscsi'
        - 'lib/modules'
```
-Hit Create

**Result:**
-Template has been created, but listing the YAML from UI shows the last entry unquoted:
```
      extra_binds:
        - '/etc/iscsi:/etc/iscsi'
        - '/sbin/iscsiadm:/sbin/iscsiadm'
        - '/var/lib/iscsi:/var/lib/iscsi'
        - lib/modules
```
Expectation was that should remain quoted.

**Comment by deniseschannon** [comment]
Per @vincent99 from this issue (https://github.com/rancher/rancher/issues/23631):

There are many ways to represent strings in YAML and those are both equivalent (represent the same array of the same 2 strings).

What is really being stored and manipulated is JSON, so it is not possible to guarantee that the YAML provided round-trips from YAML->JSON->YAML and produces exactly the same format as the original.
