### ISSUE TITLE
[forwardport ]Catalog refresh action does not return the catalog list

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#23636]
https://github.com/rancher/rancher/issues/23496

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 4beb5cf3e`

In the dev tool response:

`UI/API UI`
`{baseType: "catalogRefresh", catalogs: ["library", "system-library"], type: "catalogRefresh"}
baseType: "catalogRefresh"
catalogs: ["library", "system-library"]
type: "catalogRefresh"`
