### ISSUE TITLE
[Forwardport] Imported clusters can't recover when cluster-agent is down

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#23637]
Forwardport https://github.com/rancher/rancher/issues/23331

**Comment by soumyalj** [comment]
Tested with master-head build from Nov 11(7a6c2e55561f)

Steps:
1. Created an imported RKE cluster in Rancher
2. Deleted the cluster-agent deployment to simulate cluster-agent failure
3. Accessing cluster's projects from UI was functional. Cluster was in active state. Creating new projects/workloads was also functional.
