### ISSUE TITLE
Translation broken in the UI during login process

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23643]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Bring up a rancher server in rancher:v2.3-head - latest
- Launch the url.
- Enter password
- Click on Continue.

**Actual Result:**
Translation is broken on the `Rancher Server URL` settings page
<img width="745" alt="Screen Shot 2019-10-23 at 11 24 24 PM" src="https://user-images.githubusercontent.com/26032343/67425434-99f0d280-f5f5-11e9-8255-8db722b563d6.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3-head
- Installation option (single install/HA): single

**Comment by deniseschannon** [comment]
Is this consistently broken or just a one time thing? @sowmyav27

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sowmyav27** [comment]
**Verified on `latest 2.3-head`**
**ui tag: `https://releases.rancher.com/ui/latest-2.3/index.html`**

**Steps:**
- Bring up a rancher server in rancher:v2.3-head - latest
- Launch the url.
- Enter password
- Click on Continue.
- Rancher Server URL settings page looks good.

<img width="770" alt="Screen Shot 2019-11-02 at 3 35 14 AM" src="https://user-images.githubusercontent.com/26032343/68059269-e472fd00-fd21-11e9-9ef7-830836589573.png">
