### ISSUE TITLE
[Forwardport] After adding a global role as a new user default, editing the user in UI changes the GlobalRoleBinding from `user` to `user-base`

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23644]
Forwardport of rancher/rancher#21749

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by bmdepesa** [comment]
rancher/rancher:master-head efa6c3cc7

* UI is updated

* Local Auth
  * New user with Admin, Standard User, user-base has all 3 GRB, admin can still perform admin actions
  * New user with Admin has Admin GRB
  * New user with Standard user has User GRB
  * New user with User base has user-base GRB
  * New user with a role and custom roles shows all expected GRB
  * Removing custom roles removes associated GRB
  * Edit a user with some custom roles adds the associated GRB
