### ISSUE TITLE
rancher2.3配置pipline gitlab流水线报错

### ISSUE THREAD

**Issue by 758109577** [rancher/rancher#23656]
*Describe your issue here*
页面报错如下
TestAndApply Error
{"error":"You need to sign in or sign up before continuing."}

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.1` UI: `v2.3.18` |
|Route|`authenticated.project.pipeline.settings`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Or you can find China User WeChat group `rancher2`
