### ISSUE TITLE
[UI] CPU Speed Details incorrectly displayed

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#2365]
- CPU speed shows the current clock speed of the CPU, not it's max. For CPU's with SpeedStep technology the current speed can vary by a large amount resulting in inconsistent reports between identical hosts.
- Number of CPU's is tricked by hyper-threading and actually reports back 64x cores on a 32core box when HT is enabled. This could in theory be by design but i would think something denoting hyper-threading being enabled would be more 'correct'

I'm going to have a go at a pull request for this, just logging the issue first to relate to it.

**Comment by Rucknar** [comment]
Current CPU info is obtained from /proc/cpuinfo, plenty of other way's i've found of reporting back the correct speed however rancherOS is pretty bare bones, subsequently it doesn't support most the common methods. Of course it's wanted to be supported across all systems.

Having a look for a suitable solution.

**Comment by vincent99** [comment]
Those are both going to be in python-agent (https://github.com/rancher/python-agent/blob/837406c64602789079fa16a6f836c54fb165e534/cattle/plugins/host_info/cpu.py).  There's no better CPU MHz without parsing the vendor string.

Hyperthreading cores I would not call a bug, those are cores as far as software is concerned and can be pinned to.

**Comment by Rucknar** [comment]
@vincent99 Could i not use something like 'cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq' for the CPU speed?

HT - Fine, i did suspect that might be by design but thought i'd raise it.

**Comment by Rucknar** [comment]
*heh - works on rancherOS but not on ubuntu.

**Comment by cloudnautique** [comment]
We display the CPU model number in the tooltip fly out now on host details.

**Comment by vincent99** [comment]
If you have something else that works on all the common OSes that's fine..  Is that going to include the turbo boost and sort of have the opposite problem where it's displaying a frequency it can't actually run at consistently?  I'd rather it show the "normal" speed that would match the model name string.

**Comment by Rucknar** [comment]
@vincent99 I'll give it go this morning (for me at least!). I agree around that last statement, we want the max clock speed without any turbo-boost stuff. I'll have a dig.

**Comment by ibuildthecloud** [comment]
@Rucknar I'm guessing you already found this, but https://github.com/rancher/python-agent/blob/master/cattle/plugins/host_info/cpu.py is where we collect this.

**Comment by Rucknar** [comment]
Thanks @ibuildthecloud Just testing a branch now, think we might have it. I'm VERY slow at this stuff though :)

**Comment by Rucknar** [comment]
^ Had a go, passed testing on my local install. Tried to make it fall back to the current method should itf fail to find a correct value. Worth double checking this over though to make sure it's robust and i've not made any silly mistakes.

**Comment by vincent99** [comment]
hmm, I was hoping to avoid string parsing but don't see any better source for the nominal speed among the many different ways to get the wrong one :smile:

Falling back to the old path is good; Can you make the parsing a little looser, like `[0-9\.]+\s?GHz` in case there's not 2 decimal places or the spacing varies.  And possibly another block for detecting MHz (not sure if any ARM CPUs have speeds in their model name).

**Comment by Rucknar** [comment]
I agree, 'll make the updates now and squash to a single commit, i'll also add the test @cloudnautique mentioned on the issue ticket. Regarding the additional Mhz checking though, don't we already handle the edge cases through the fall-back code? 

I don't think ARM CPU's report the speed in the model name at all from what i can see online, I figured that in this case the code correctly falls back to the original code, i'm not sure if ARM has any dynamic frequency scaling that could throw the result off.

**Comment by Rucknar** [comment]
Right, took me longer than i'd care to admit but the tests are now there and i've updated the regex based on your input. @vincent99 Let me know if it needs any more polish.

**Comment by Rucknar** [comment]
Closing, fix merged. Thanks for the guidance guys, much appreciated.
