### ISSUE TITLE
Tiller does not deploy in a HA setup with k8s 1.16

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23651]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Bring up a cluster using rke up - rke version - `0.3.2-rc3`, k8s version - `1.16.2`
- Follow the instructions from Rancher's document to setup HA. - https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-init/

The following step fails - tiller fails to deploy
```
helm init --service-account tiller
$HELM_HOME has been configured at /Users/<.>/.helm.
Error: error installing: the server could not find the requested resource
```
```
kubectl -n kube-system  rollout status deploy/tiller-deploy
Error from server (NotFound): deployments.apps "tiller-deploy" not found
```

**Comment by dramich** [comment]
This needs to be a docs issue to document that helm < 2.15 will NOT work with k8s 1.16 and is a known issue https://github.com/helm/helm/issues/6374

**Comment by jiaqiluo** [comment]
Successfully install Rancher v2.3.2-rc2 with helm v2.15.1 following the documentation mentioned above

**Comment by deniseschannon** [comment]
This was documented in part of the HA docs, but not in every location. 

https://github.com/rancher/docs/pull/1914/files

Also, needs to be updated in these locations as well. 
rancher/v2.x/en/installation/ha/helm-rancher/
rancher/v2.x/en/installation/ha/helm-init/

**Comment by superseb** [comment]
The docs PR was for an issue specifically for v2.15.0 breaking parsing/comparing numbers (https://github.com/rancher/rancher/issues/23516). This needs documentation on describing the requirements for k8s 1.16.
