### ISSUE TITLE
Only the first metrics graph is visible in cluster monitoring

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#23654]
**Rancher Version**
master - 30db13e74

**Steps to reproduce (least amount of steps as possible):**
1. Add a EC2 cluster and enable cluster monitoring
2. Check metrics graphs

**Result:**
![image](https://user-images.githubusercontent.com/5697937/67459346-f04c2880-f66a-11e9-9eab-c94006c0bab0.png)

**Other details that may be helpful:**
API looks good.
It works in v2.3-master.

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version ebe495938`

Add a EC2 cluster and enable cluster monitoring
Check metrics graphs
Result:
![Screen Shot 2019-11-21 at 9 15 21 AM](https://user-images.githubusercontent.com/57409052/69358116-8f047e80-0c43-11ea-9048-773bda899deb.png)
![Screen Shot 2019-11-21 at 9 15 30 AM](https://user-images.githubusercontent.com/57409052/69358126-91ff6f00-0c43-11ea-8f20-ca8d15cc4c8e.png)
