### ISSUE TITLE
[cli] docker images on docker hub are seg faulting

### ISSUE THREAD

**Issue by abuisine** [rancher/rancher#23659]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
```
docker run --rm -ti --entrypoint=/bin/sh rancher/cli:latest --version
/mnt # rancher
```
also
```
docker run --rm -ti --entrypoint=/bin/sh rancher/cli2:latest --version
/mnt # rancher
```

**Result:**
`Segmentation fault`

**Other details that may be helpful:**

**Environment information**
tested on cli:latest, cli:v0.6.14, cli:v0.6.13, cli2:latest, fails on all tested versions
Docker version 19.03.2

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/23433
