### ISSUE TITLE
Catalog App - istio fails in k8s 1.16.2

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23660]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug 

**Steps to reproduce (least amount of steps as possible):**
in v2.3.1-rc1, cluster k8s 1.16.2
istio shows 3 templates and neither of them work in 1.16.2

<img width="925" alt="Screen Shot 2019-10-24 at 9 52 27 AM" src="https://user-images.githubusercontent.com/6218999/67507997-f202f580-f644-11e9-9caf-80e7e8cb0722.png">

<img width="933" alt="Screen Shot 2019-10-24 at 9 52 12 AM" src="https://user-images.githubusercontent.com/6218999/67507999-f4654f80-f644-11e9-8ebe-b50ec755e303.png">

**Comment by deniseschannon** [comment]
@jiaqiluo what charts branch are you looking at? this looks like it's coming from charts verus system-charts. 

the istio catalog in the charts branch (library) should not show any versions.

**Comment by deniseschannon** [comment]
@jiaqiluo If you are pointing to the `k8s-1.16` branch, it doesn't have the max version for istio, but it is already in `master`, but it breaks CI when we bring that commit into that branch. Therefore, that chart has a unique case where it's already fixed to hide all versions in master branch.
