### ISSUE TITLE
502 error when deleting EKS cluster

### ISSUE THREAD

**Issue by ibrokethecloud** [rancher/rancher#23665]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** 
* Launch an EKS cluster using Rancher ui.
* Try and delete EKS cluster from Rancher ui.

**Result:**
EKS cluster deletion fails due to error: 502 UnknownError: 502

**Other details that may be helpful:**
Rancher container logs indicate the additional information:
```
rancher-79db5c7b9-6ls25 rancher 2019/10/24 23:56:08 [INFO] Failed to proxy: invalid host: eks.us-east-1.amazonaws.com
rancher-79db5c7b9-6ls25 rancher 2019/10/24 23:56:08 http: proxy error: unsupported protocol scheme ""
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Managed controlplane, 1 worker node.
- Kubernetes version (use `kubectl version`):  1.14

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by ibrokethecloud** [comment]
Seems like the delete from the UI makes the call to `https://${MYCLUSTER}/meta/proxy/eks.us-east-1.amazonaws.com/clusters`

Where as from the API page inside the cluster, I can delete the cluster by making a delete call which is of the form.
`https://${MYCLUSTER}/v3/clusters/c-nzrjt`

The latter works.

**Comment by ebauman** [comment]
+1 I have run into this as well.

**Comment by savealive** [comment]
Confirming the same issue on v2.4.2
```
2020/04/28 00:37:15 [INFO] Failed to proxy: invalid host: eks.us-east-1.amazonaws.com
2020/04/28 00:37:15 http: proxy error: unsupported protocol scheme ""
```

**Comment by izaac** [comment]
I tried in Rancher `v2.3.7-rc3` 

```
Request URL: https://<hostname>/v3/clusters/c-7wt45
Request Method: DELETE
Status Code: 200 
```

**Comment by savealive** [comment]
Yes, API request starts deleting cluster. However, it doesn't control all required pre-requisites.
In my case I was tried to delete EKS cluster which was created using federated account credentials with session token. Rancher started EKS deleting process without creds validation. As result I've got cluster disappeared from UI but not from AWS account.
Logs:
```
2020/04/28 00:43:10 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:35959
2020/04/28 00:43:10 [INFO] Starting delete cluster
2020/04/28 00:43:10 [ERROR] Error removing cluster [c-twnhm] with driver [amazonelasticcontainerservice]. Check for stray resources on cloud provider: error deleting cluster: ExpiredTokenException: The security token included in the request is expired
	status code: 403, request id: 63aa4988-5bfc-4f55-806c-a1e8a46f5096
2020/04/28 00:43:10 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2020/04/28 00:43:10 [INFO] Deleted cluster [c-twnhm]
2020/04/28 00:43:10 [INFO] [mgmt-cluster-rbac-remove] Deleting namespace c-twnhm
2020/04/28 00:43:10 [ERROR] ClusterController c-twnhm [mgmt-cluster-rbac-remove] failed with : clusters.management.cattle.io "c-twnhm" not found
2020/04/28 00:43:17 [INFO] [mgmt-auth-users-controller] Deleting projectRoleTemplateBinding u-mzos772pk7-member for user u-mzos772pk7
2020/04/28 00:43:17 [INFO] [mgmt-project-rbac-remove] Deleting namespace p-j22hd
2020/04/28 00:43:17 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding rolebinding-9p966
2020/04/28 00:43:17 [INFO] [mgmt-auth-users-controller] Deleting projectRoleTemplateBinding u-xwmphlwm54-member for user u-xwmphlwm54
```
I believe it worth a new github issue dedicated to this.

**Comment by izaac** [comment]
Rancher `v2.4.3-rc2`

```
Request URL:https://<hostname>/v3/clusters/c-f2q2g
Request Method: DELETE
Remote Address: <IP address>:443
Status Code: 200
```

**Comment by izaac** [comment]
> Yes, API request starts deleting cluster. However, it doesn't control all required pre-requisites.
> In my case I was tried to delete EKS cluster which was created using federated account credentials with session token. Rancher started EKS deleting process without creds validation. As result I've got cluster disappeared from UI but not from AWS account.
> Logs:
> 
> ```
> 2020/04/28 00:43:10 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:35959
> 2020/04/28 00:43:10 [INFO] Starting delete cluster
> 2020/04/28 00:43:10 [ERROR] Error removing cluster [c-twnhm] with driver [amazonelasticcontainerservice]. Check for stray resources on cloud provider: error deleting cluster: ExpiredTokenException: The security token included in the request is expired
> 	status code: 403, request id: 63aa4988-5bfc-4f55-806c-a1e8a46f5096
> 2020/04/28 00:43:10 [INFO] kontainerdriver amazonelasticcontainerservice stopped
> 2020/04/28 00:43:10 [INFO] Deleted cluster [c-twnhm]
> 2020/04/28 00:43:10 [INFO] [mgmt-cluster-rbac-remove] Deleting namespace c-twnhm
> 2020/04/28 00:43:10 [ERROR] ClusterController c-twnhm [mgmt-cluster-rbac-remove] failed with : clusters.management.cattle.io "c-twnhm" not found
> 2020/04/28 00:43:17 [INFO] [mgmt-auth-users-controller] Deleting projectRoleTemplateBinding u-mzos772pk7-member for user u-mzos772pk7
> 2020/04/28 00:43:17 [INFO] [mgmt-project-rbac-remove] Deleting namespace p-j22hd
> 2020/04/28 00:43:17 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding rolebinding-9p966
> 2020/04/28 00:43:17 [INFO] [mgmt-auth-users-controller] Deleting projectRoleTemplateBinding u-xwmphlwm54-member for user u-xwmphlwm54
> ```
> 
> I believe it worth a new github issue dedicated to this.

@savealive yes this sounds like a separate issue to the reported here so far I'm using Access and Secret keys not session tokens in the tests I've been covering so far.
