### ISSUE TITLE
Catalog App - Longhorn shows old template versions in v2.3.2

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23661]
Bug

In v2.3.2-rc1, Longhorn shows all old template versions 
versions < 0.6.0 are not working in k8s 1.16 cluster 

<img width="765" alt="Screen Shot 2019-10-24 at 10 56 06 AM" src="https://user-images.githubusercontent.com/6218999/67512902-a48b8600-f64e-11e9-9f2d-d66b144d09f5.png">

**Comment by guangbochen** [comment]
@yasker can u have someone to add the `rancher_max_version: 2.3.1` in the `questions.yml` to those old template versions, thanks.

**Comment by yasker** [comment]
@shuo-wu can you update the charts?

**Comment by shuo-wu** [comment]
Longhorn versions < 0.6.0 not working in k8s 1.16 doesn’t mean Rancher v2.3.2 supports k8s v1.16 only. It's too aggressive to deprecate all old Longhorn versions in Rancher v2.3.2.

At least we can support v0.5.0, which is a stable version and has all important functionalities. And it works fine in k8s v1.14.8 cluster which is supported by Rancher v2.3.2-rc1.

**Comment by yasker** [comment]
Can we limit the Kubernetes version instead of the Rancher version?

**Comment by deniseschannon** [comment]
No, we can only limit based on Rancher version today.

**Comment by jiaqiluo** [comment]
The enhancement is validated in `Rancher:v2.3.2-rc3` with the library's branch `master`

There are versions starting from v0.0.5 in the list, and all of them work in both k8s 1.15 and 1.16 clusters. 
<img width="730" alt="Screen Shot 2019-10-28 at 2 10 51 PM" src="https://user-images.githubusercontent.com/6218999/67718310-c35e8500-f98c-11e9-888c-97a4cb49c6a0.png">
