### ISSUE TITLE
[forwardport]Remove "istio-virtual-service-ui" feature flag

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23668]
https://github.com/rancher/rancher/issues/23582

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 781cd0f
UI: latest-2

* istio-virtual-service-ui feature flag is enabled by default and UI features are shown
* When flag is set to false the UI features are hidden
