### ISSUE TITLE
istio sidecar and k8s jobs results in error

### ISSUE THREAD

**Issue by gregkeys** [rancher/rancher#23672]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. create a namespace
2. enable istio sidecar injection for the namespace
3, deploy a job

**Result:**
job status success results in an error and envoy container continues to run as sidecar to the job

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI) rancher v2.3.1:
- Installation option (single install/HA): HA

**Comment by loganhz** [comment]
Not sure if this helps `https://medium.com/redbox-techblog/handling-istio-sidecars-in-kubernetes-jobs-c392661c4af7`. Could you share what you expect Rancher to handle for this? Thanks!

**Comment by gregkeys** [comment]
@loganhz yes that helps thank you. Sounds like we need to annotate the jobs with `sidecar.istio.io/inject: “false”` for our purpose, maybe rancher could add that to their documentation so others dont post it as a bug?

**Comment by samirspatel** [comment]
I ran into the same issue and realized that there is a KEP open that addresses sidecars in a more generic way specifically for jobs https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/sidecarcontainers.md

**Comment by cbron** [comment]
More info here: https://github.com/istio/istio/issues/6324
