### ISSUE TITLE
Typo in syslog configuration

### ISSUE THREAD

**Issue by pcasis** [rancher/rancher#23673]
Hello,

There is a typo in the syslog configuration page on Rancher.
Version : v2.2.9

![image](https://user-images.githubusercontent.com/25147189/67553708-15de3e00-f70e-11e9-9ba1-460cc5777067.png)

Must change Ctitical to Critical

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 9930781c8`

![Screen Shot 2019-11-15 at 9 38 41 AM](https://user-images.githubusercontent.com/57409052/68959679-c084d200-078b-11ea-94cb-defe32cec4eb.png)
