### ISSUE TITLE
vSphere cloud provider enabled, cluster monitoring integration breaks

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#23678]
I've not tested this, it is feedback from @dnoland1. Someone should try to repro this and see what is breaking. See: https://github.com/rancher/rancher/issues/23677

**Comment by dnoland1** [comment]
Getting this error:

> Failed to install app cluster-monitoring. Error: release cluster-monitoring failed: Endpoints "expose-kube-cm-metrics" is invalid: [subsets[0].addresses[0].ip: Invalid value: "": must be a valid IP address, (e.g. 10.9.8.7), subsets[0].addresses[0].ip: Invalid value: "": must be a valid IP address, subsets[0].addresses[1].ip: Invalid value: "": must be a valid IP address, (e.g. 10.9.8.7), subsets[0].addresses[1].ip: Invalid value: "": must be a valid IP address]

Running a `kubectl get nodes -o wide` shows the nodes do not have an InternalIP set.

Working fine when cloud provider is disabled.

**Comment by terafirmanz** [comment]
on 2.3.1 on vSphere (6.7) with multiple clusters and `kubectl get nodes -o wide` runs as expected. I can enable cluster monitoring fine and all works both with PVC and without.

Happy to compare if something is needed.
