### ISSUE TITLE
[ForwardPort] Rancher-created registry secret is missing the auth field

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#23686]
[ForwardPort]https://github.com/rancher/rancher/issues/19177

**Comment by sowmyav27** [comment]
### on master-head - latest

- Create a registry secret from the UI
- Inspect it via kubectl
- Decode the .dockerconfigjson field - echo '<dockerconfigjson-value>' | base64 -d in kubectl in cluster
`{"auths":{"index.docker.io":{"auth":"c293bXlhdjp0ZXN0","password":"password","username":"username"}}}`


### On upgrade from 2.3.2 to master-head

- Create a registry secret from the UI in 2.3.2 rancher
- Inspect it via kubectl
- Decode the .dockerconfigjson field - echo '<dockerconfigjson-value>' | base64 -d in kubectl in cluster
`{"auths":{"index.docker.io":{"password":"password","username":"username"}}}`
- Upgrade rancher to master-head
- Existing registry secrets will continue to have
`{"auths":{"index.docker.io":{"password":"password","username":"username"}}}`
- Create a new registry secret
- Decode the .dockerconfigjson field - echo '<dockerconfigjson-value>' | base64 -d in kubectl in cluster
`{"auths":{"index.docker.io":{"auth":"c293bXlhOnNvd215YQ==","password":"password","username":"username"}}}`

### Including email in the registry credentials

- Create a registry secret in master-head
- View in API of the secret
- You can edit/create a new secret
- Give in email in registries
`{"email":"email","username":"sowmya","password":"password"}`
- Inspect it via kubectl
- Decode the .dockerconfigjson field - echo '<dockerconfigjson-value>' | base64 -d in kubectl in cluster
`{"auths":{"index.docker.io":{"auth":"c293bXlhOnBhc3N3b3Jk","email":"email","password":"password","username":"sowmya"}}}`
