### ISSUE TITLE
Unable to fully drain nodes with istio enabled due to PodDisruptionBudgets

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#23680]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Steps to reproduce (least amount of steps as possible):**

1. Enable istio on a cluster managed by Rancher v2.3.1
2. Attempt to perform an aggresive drain on a node running one of the following components: istio-galley, istio-ingressgateway, istio-pilot, istio-policy, istio-sidecar-injector or istio-telemetry.
3. Observe the drain timesout

**Other details that may be helpful:**

Upstream issue for this is in https://github.com/istio/istio/issues/12602 Should 2 replicas of these components be provisioned (with an anti-affinity preference) if these are so critical, to provide HA and enable draining nodes?

**Environment information**
- Rancher v2.3.1

**Comment by pirminjanka** [comment]
+1

**Comment by cloudnautique** [comment]
Closing this, issue tracked in #23175
