### ISSUE TITLE
[Forwardport] Incorrect K8s version is displayed on a cluster edit when changing from revision with v13.12 to v1.14(Latest)

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23682]
Forwardport of rancher/rancher#23616

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by soumyalj** [comment]
Tested with master-head with UI index latest2.
 Create a rke template with K8s version v1.13.12-rancher2-1, the template gets created with version v1.15.5-rancher1-1. 
The following errors are seen .
<img width="714" alt="Screen Shot 2019-10-25 at 1 24 14 PM" src="https://user-images.githubusercontent.com/18536626/67602867-6b294800-f72c-11e9-99f4-3e8d9d71ae71.png">

<img width="1279" alt="Screen Shot 2019-10-25 at 1 36 22 PM" src="https://user-images.githubusercontent.com/18536626/67602889-77ada080-f72c-11e9-9d70-0b64e7b4829e.png">

API :
```
},
"rancherKubernetesEngineConfig": {
"addonJobTimeout": 30,
"authentication": {
"strategy": "x509",
"type": "/v3/schemas/authnConfig"
},
"ignoreDockerVersion": true,
"ingress": {
"provider": "nginx",
"type": "/v3/schemas/ingressConfig"
},
"kubernetesVersion": "v1.15.5-rancher1-2",


```

**Comment by westlywright** [comment]
The bug was unrelated to this change but is resolved in `latest2` now.

**Comment by soumyalj** [comment]
Tested with master-head build with ui index `https://releases.rancher.com/ui/latest2/index.html`
Steps:

1. Create a cluster template T1 and Revision R1 using K8s version v1.13.2-rancher2-1 (no override)
2. Create revision R2 using K8s version v1.14(Latest) (no override)
3. Create a cluster using R1
The cluster gets created correctly with version v1.13.2-rancher2-1. [There are no errors as shown in the comment above]
There is another issue which prevents from testing the forward port fix.
Edit the cluster and choose R2. The k8s version does not change to v1.14.8-rancher1-1
![Screen Shot 2019-10-26 at 5 53 16 PM](https://user-images.githubusercontent.com/18536626/67627921-79559200-f81a-11e9-9c40-e44bf40a109d.png)

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by soumyalj** [comment]
Tested with master-head from Nov 5th
Create a cluster template T1 and Revision R1 using K8s version v1.13.2-rancher2-1 (no override)
Create revision R2 using K8s version v1.14(Latest) (no override)
Create a cluster using R1
The forward port fix has the issue below:
Edit the cluster and choose R2. The k8s version does remains at v1.13.2-rancher2-1

<img width="1653" alt="Screen Shot 2019-11-05 at 11 24 36 AM" src="https://user-images.githubusercontent.com/18536626/68238918-e0174000-ffbe-11e9-8d91-32a79b0ee363.png">

**Comment by soumyalj** [comment]
Tested with master-head build with ui index https://releases.rancher.com/ui/latest2/index.html

Steps:
Create a cluster template T1 and Revision R1 using K8s version v1.13(Latest) (no override)
Create revision R2 using K8s version v1.14(Latest) (no override)
Create a cluster using R1
The cluster gets created correctly with version v1.13.2-rancher2-1. 
Edit the cluster and choose R2. K8s version changes to v1.14.8-rancher2-1

<img width="1355" alt="Screen Shot 2019-11-11 at 2 21 50 PM" src="https://user-images.githubusercontent.com/18536626/68625864-fd508080-048e-11ea-9de5-5e1dac432c36.png">
