### ISSUE TITLE
Process log is too long for id [N] truncating executions

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2369]
I'm getting a lot of the following errors in my rancher/server log:

    2015-10-19 16:19:18,379 ERROR [:] [] [] [] [ecutorService-9] [i.c.p.e.m.i.j.JooqProcessRecordDao  ] Process log is too long for id [49214] truncating executions

This is followed by a really long JSON blob.

**Comment by gordontyler** [comment]
Full logs, database dumps, etc. available on request.

**Comment by deniseschannon** [comment]
I wonder if this is related to your issue in https://github.com/rancher/rancher/issues/2339#issuecomment-150337370

**Comment by gordontyler** [comment]
Not seeing it in the logs for my new Rancher Server instance...

**Comment by deniseschannon** [comment]
I bet it's related so I'll label as a performance issue to investigate when we start looking how to improve it.

**Comment by deniseschannon** [comment]
Please re-open if you are still seeing this.
