### ISSUE TITLE
The namespace project resource availability data is incorrect

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#23707]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Create project and namespace.
* Add project resource quota, project limit and namespace default limit fill in the same value, for example, 1000, 2000.
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/42061003/67646897-29d2ab80-f96b-11e9-8f38-ebcfc39936a4.png">

**Result:**
In addition to `cpu limit/reservation`, `memory limit/reservation`, `storage reservation`, all other display errors. Other namespaces are negative.

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/42061003/67646914-40790280-f96b-11e9-9d09-c19afe6900c8.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
Version: v2.3.1
- Installation option (single install/HA): single install

**Comment by MKlimuszka** [comment]
Closing as stale. This has most likely been fixed in a version since this has been reported. After reviewing with engineering and QA, this has not been seen recently. If it is seen again, this ticket can be reopened with more details.
