### ISSUE TITLE
DataAccessException: Could not read result set: unexpected end of stream

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2370]
I'm seeing the following in my rancher server logs:

    2015-10-19 16:22:50,769 ERROR [:] [] [] [] [p1167130569-145] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@723df5e4] org.jooq.exception.DataAccessException: <... sql elided...> Could not read result set: unexpected end of stream, read 489016bytes from 779304

**Comment by gordontyler** [comment]
Full logs, database dumps, etc. available on request.

**Comment by deniseschannon** [comment]
Do you think these are related to the OOM issue that you had previously filed? https://github.com/rancher/rancher/issues/2339#issuecomment-150337370

**Comment by gordontyler** [comment]
No, I just checked and I'm still getting these in my new Rancher Server.

**Comment by gordontyler** [comment]
Two instances of the error in the last two days. Both approximately around the time that I was scaling up services.

**Comment by deniseschannon** [comment]
Okay, I"ll leave it as a performance issue when scaling up something that already has a lot of services. That's what it sounds like to me.

**Comment by gordontyler** [comment]
Oh, wait! My bad... I misread the issue description and got it confused with another issue I had been looking at when I read your email. Similar exception name :P

I see no instances of this exception in my current set of Rancher Server logs.

**Comment by deniseschannon** [comment]
Okay, good to hear that these are probably all related to your OOM issue and your general setup (1 LB for 400 containers . :))

**Comment by deniseschannon** [comment]
Closing as it doesn't seem to be happening now.
