### ISSUE TITLE
[Forwardport] 2.4: Missing Dropdown for PodSecurityPolicies on imported Clusters

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#23705]
Forwardport: https://github.com/rancher/rancher/issues/21039

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 9930781c8`

Import a rke cluster with activated PSP
Create a new Project/ Edit an existing Project
See dropdown for PSP
![Screen Shot 2019-11-14 at 11 59 03 AM](https://user-images.githubusercontent.com/57409052/68887431-32024900-06d6-11ea-914a-19e2429100e2.png)

**Comment by aaronRancher** [comment]
Testing with Rancher server rancher\rancher:master-head version 9930781c8

**Comment by aaronRancher** [comment]
Testedwith Rancher server rancher\rancher:master-head version 9930781c8

use RKE to provision a cluster with PSP is enabled
the snippet of the rancher-cluater.yml file
```services:
  kube-api:
    pod_security_policy: true
run Rancher v2.3.1 single install```
add the cluster as an imported cluster into Rancher
add a project
edit the project, notice that there is no option for PSP
view the project in API, notice the action setpodsecuritypolicytemplate is available, but sending this action returns 422 error
now edit the cluster to add the annotation: capabilities/pspEnabled= true
view the cluster in API, see "pspEnabled": true under the capabilities
if adding/editing project, the option for psp shows up
![Screen Shot 2019-11-15 at 9 06 51 AM](https://user-images.githubusercontent.com/57409052/68957903-3d15b180-0788-11ea-92dc-84805a985ad5.png)
