### ISSUE TITLE
[forwardport] Refresh EKS-Optimized AMIs for supported EKS versions

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#23701]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

Refresh EKS AMIs with the latest available for 1.11 -> 1.14

**Comment by soumyalj** [comment]
Tested with rancher master-head .

Created EKS clusters in different regions us-east2 and us-west2 without providing any AMIs. The default AMIs from the new updated list were used and clusters came up correctly
```
		"us-east-2":      "ami-053250833d1030033",
		"us-west-2":      "ami-07be7092831897fd6",
```
The recent list used is from the commit below:
https://github.com/rancher/rancher/commit/8454c0aebe75b2ec2114929e90d6eacb21f45cc9
