### ISSUE TITLE
[Feature Request] Support Load-Balancer-SKU selection in AKS cluster creation

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#23715]
AKS now supports two SKU of LBs in AKS cluster creation: basic and standard. More information can be found at https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard 

The option is available in az cli cluster creation like below with --load-balancer-sku parameter

az aks create \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --node-count 1 \
    --load-balancer-sku standard \

Note: Not sure the Azure UI in global Azure, but it seems it's not available in Azure China UI yet.

We may need to add an option to let user choose basic or standard for load-balancer-sku in rancher cloud driver UI.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.1` UI: `v2.3.18` |
|Route|`global-admin.clusters.index`|

gzrancher/rancher#13068

**Comment by mscbpi** [comment]
Any update on that ? Azure official documentation will suggest SKU Standard is in use by default, but Rancher creates cluster with Basic LB.

then if you follow the doc for [deploying the nginx ingress](https://docs.microsoft.com/en-us/azure/aks/ingress-static-ip) you will fail because it creates a Public IP with Standard SKU and both SKU must match. 

Alternative is to create a Basic SKU IP Address with fewer feature (as well as fewer feature / lower SLA in the Basic LB)

**Comment by junkiebev** [comment]
I have ticket #13068 in for this - it's a fairly pressing need.

**Comment by cbron** [comment]
@sowmyav27 when we test this we want to double check that existing clusters from earlier versions of rancher upgrade without issue or change. So if a AKS cluster is provisioned with Rancher 2.4.5 then upgraded to this, and then an upgrade occurs on the cluster, that the LB stays the same and cluster continues to work, feel free to reach out to @nickgerace with any questions.

**Comment by sowmyav27** [comment]
**Validated on 2.4-head commit id: `a61621e57`**

- Deploy an AKS cluster - set `loadBalancerSku` to Basic
<img width="822" alt="Screen Shot 2020-11-03 at 2 34 57 PM" src="https://user-images.githubusercontent.com/26032343/98053176-d6503480-1dec-11eb-83d9-a3c61d3012d6.png">

- When the cluster comes up, verified in the backend LB is set as basic.
```
Traffic routing
Load balancer : Basic
```

**Comment by junkiebev** [comment]
FYI @sowmyav27  LB sku is immutable once the cluster is created - one may only specify it at creation time.

**Comment by nickgerace** [comment]
Confirmed that pre-existing clusters on 2.4.8 will have the `LoadBalancerSku` field incorrectly set. Working on a fix.

**Comment by sowmyav27** [comment]
**On 2.4-head - commit id: `add5c9a04`**

- Create a new AKS cluster through the API and do not pass in the `LoadBalancerSku` field.
- The value of `LoadBalancerSku` on the Cluster in View in API is `""`

**Expected:**
It should be Standard

**Comment by sowmyav27** [comment]
**On 2.4-head - commit id: `2bc5432cd`**

**Scenario#1**

- On a fresh install of 2.4-head - create an AKS cluster - choose LoadBalancerSku - standard/basic in the UI
- When the cluster is Active, in the backend verified "LoadBalancerSku" is set to standard/basic

**Scenario#2**
Upgrade from 2.4.8 to 2.4-head

- On 2.4.8 create an AKS cluster, by default LoadBalancerSku is set to basic in the backend for the cluster
- upgrade to 2.4-head
- "LoadBalancerSku" is seen set as `""`
- Edit cluster --> LoadBalancerSku is set to basic --> Upgrade k8s version of the cluster to 1.18 from 1.17.
- k8s version of the cluster is updated and in View in API LoadBalancerSku is set as `""`

**Scenario#3**
- Create a new AKS cluster through the API and do not pass in the `LoadBalancerSku` field.
- The value of `LoadBalancerSku` on the Cluster in View in API is `""` The LoadBalancerSku on the backend is set to Basic.
