### ISSUE TITLE
Vsphere master parity with 2.3-fixes

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23714]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Result:**
Master is missing some of the vsphere changes that are present in the 2.3-fixes pr rancher/ui#3475. These changes will bring master to parity with the above pr.

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by aaronRancher** [comment]
Tested in `rancher\rancher:master-head` `version 781cd0fdc`.

vSphere Driver UX changes are available:
![Screen Shot 2019-11-26 at 10 11 55 AM](https://user-images.githubusercontent.com/57409052/69656243-6e6a6900-1035-11ea-81af-b0e763f3349f.png)
![Screen Shot 2019-11-26 at 10 12 07 AM](https://user-images.githubusercontent.com/57409052/69656255-71fdf000-1035-11ea-84a7-192490b1d6ca.png)

Spinner on search select:
![image](https://user-images.githubusercontent.com/57409052/69656213-63173d80-1035-11ea-9a9d-0549b0626ec3.png)
