### ISSUE TITLE
rke upgrade 0.2.8 => 0.3.0 fail

### ISSUE THREAD

**Issue by dmitry-rancher** [rancher/rancher#23713]
Hello,

During rke version upgrade there's an error message:

**Failed to get /health for host  [PRIVATE-HOST-HERE]: Get https://PRIVATE-HOST:2379/health: remote error: tls: bad certificate.**

**What kind of request is this (question/bug/enhancement/feature request):**
Private CA is in use, passed with --set privateCA=true && --set additionalTrustedCAs=true

Private registry is also in use, passed with --set 'extraEnv[0].name=CATTLE_SYSTEM_DEFAULT_REGISTRY' && --set 'extraEnv[0].value=...:8156'

Rancher 2.2.4 is HA-installed as Helm chart.

The goal is to upgrade to hyperkube:v1.14.6-rancher1, which is synchronised to private registry.

**Comment by barryboubakar** [comment]
Hello, I can confirm, we are facing the same issue in our environment. Solving this issue is very important for us. 

Thanks in advance.

**Comment by superseb** [comment]
This was solved in a way that might not be generic enough to approach other issues, so for anyone hitting this issue, please file a new issue with all the information requested in the issue template so we can asses whats going on and provide a solution for it.
