### ISSUE TITLE
System Charts Branch did not Update with Upgrade to 2.3.1

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#23722]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Upgrade from 2.2.9 to 2.3.1

**Result:**

Catalog entry for system-charts remained at `release-v2.2`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.1
- Installation option (single install/HA): HA

**Comment by sowmyav27** [comment]
verified the following on an upgrade from `2.2.9` to `2.3.1`, HA setup

System-library catalog chart in 2.2.9 - `release-v2.2`
System library catalog chart in 2.3.1 - `release-v2.3`

**Comment by ekristen** [comment]
Interesting. Perhaps the fact that in my case that they did not update to `release-v2.3` is related (and an additional symptom) to the other problems that have been seen in upgrading? https://github.com/rancher/rancher/issues/23284
