### ISSUE TITLE
EC private key unsupported by Rancher server

### ISSUE THREAD

**Issue by mecseid** [rancher/rancher#23727]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Generate certificate with EC private key
* Start cluster from https://github.com/rancher/quickstart
* Add certificate from UI

**Result:**
Private Key is invalid. Please make sure it is a RSA key.

**Other details that may be helpful:**
If I convert the key to PKCS#8 format, then I got the following error:
Validation failed in API: certs failed to find cert that matched private key

**Environment information**
- Rancher version: 2.3.1
- Installation option: single install

**Cluster information**
- Cluster type: Custom
- Machine type: VM
- Kubernetes version: v1.15.5

I think it's a Rancher server related problem, because I can put the TLS certificate to Kubernetes as a secret:
`kubectl create secret tls test-ec-cert --key test-ec.key --cert test-ec.crt`

On the UI if I click to the Default project, I got this error:
Validation failed in API: certs failed to find cert that matched private key

Related issue:
https://github.com/rancher/rancher/issues/13156#issuecomment-409884609

**Comment by mecseid** [comment]
The current issue affects the v2.2.9 version too.

**Comment by proligde** [comment]
We might have a similar problem here, although working with an official ACME/Let'sEncrypt certificate. At least we get the same error "Validation failed in API: certs failed to find cert that matched private key" when accessing one of our Rancher cluster's Projects, while the other projects on the closter can be accessed without any problems. Furthermore: Using kubectl we can also access all workloads in the project without any problems (and they are running flawlessly). This happened to one of our other projects as well some days ago. We had no other option as to completely remove the project in rancher2's web gui and to recreate it, which we don't want to do again. Could anyone point us into the right direction here? Thanks in advance - Max

**Comment by mecseid** [comment]
I think its closable, because in version 2.4.8, I can add an EC certificate from Rancher UI.

**Comment by maximmasiutin** [comment]
There is a discussion at https://stackoverflow.com/questions/67995687/which-of-the-elliptic-curves-are-supported-for-the-kubernetes-certificates
