### ISSUE TITLE
[UI] Do not show pod security policy selection if not enabled

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#23730]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. do not enable psp for a cluster
2. go to add project to cluster

**Result:**
user can set psp

**Backend Issue:**
https://github.com/rancher/rancher/issues/21548

**Other details that may be helpful:**
Once backend is merged, cluster will have a capabilities field called "pspEnabled". This will provide the necessary info for showing or not showing this option.

**Comment by cjellick** [comment]
@vincent99 I cant really remember if we said 1) "dedicated UI for this" or 2) "there's already an annotations section on the cluster create page so we can just tell the user (and document) how to do it via the annotation"
Do you recall? I think 2 could be sufficient for now

**Comment by cjellick** [comment]
had a commented and deleted it bc i was thinking of something else, but now im writing this bc i know vincent is going to see that ghost comment and woner what happened

**Comment by rmweir** [comment]
closing and will combine with https://github.com/rancher/rancher/issues/23730
