### ISSUE TITLE
[2.3.x ?] regression: openstack custom cloud provider not working anymore

### ISSUE THREAD

**Issue by patriziobassi** [rancher/rancher#23738]
**What kind of request is this (question/bug/enhancement/feature request):**
when deploying an Openstack cluster using the custom cloud provider (by manually editing the yaml) the setting seems lost

**Steps to reproduce (least amount of steps as possible):**

**Result:**
no cloud-config in /etc/kubernates/ on provisioned nodes

**Other details that may be helpful:**
it was working fine on 2.2.4/5

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.2
- Installation option (single install/HA):
single docker

**Comment by alena1108** [comment]
@patriziobassi can you share the example of modified cluster.yml that you use?

**Comment by alena1108** [comment]
@patriziobassi just ran a quick test on the latest rancher by modifying customCloudProvider directive in `cluster.yml`:

```
rancher_kubernetes_engine_config:    
  addon_job_timeout: 30
  authentication:
    strategy: x509|webhook
  authorization: {}
  bastion_host:
    ssh_agent_auth: false
  cloud_provider: 
    name: openstack
    customCloudProvider: |-
      [Global]
      username=${OS_USERNAME}
      password=${OS_PASSWORD}
      auth-url=https://${OS_AUTH_URL}/identity/v3
      tenant-id=${OS_TENANT_ID}
      domain-id=${OS_DOMAIN_ID}

      [LoadBalancer]
      subnet-id=${SUBNET_ID}
  ignore_docker_version: true
```
As a result, the config file was placed on the host:

```
root@alenadolocal1:~# cat  /etc/kubernetes/cloud-config
[Global]
username=${OS_USERNAME}
password=${OS_PASSWORD}
auth-url=https://${OS_AUTH_URL}/identity/v3
tenant-id=${OS_TENANT_ID}
domain-id=${OS_DOMAIN_ID}

[LoadBalancer]
subnet-id=${SUBNET_ID}
```

The only diff between 2.2.x and 2.3.x I can think of is - in 2.3.x, there was `rancher_kubernetes_engine_config:    ` top level directive introduced in cluster.yml. And all cluster config parameters should be defined under it. I suspect that it might be causing this issue you are seeing.

**Comment by patriziobassi** [comment]
So probably the problem Is with the UK not beong update when you edit yaml when selecting custom yaml. Can you try from web ui?

**Comment by alena1108** [comment]
@patriziobassi I was trying from web UI. Just tried it again on a v2.3.2 Steps taken:

1) Click on cluster edit.
2) Pick custom radio button

![image](https://user-images.githubusercontent.com/1562176/68430395-db8c8c00-0164-11ea-8d70-b0dc6a6e7026.png)

3) Open edit as yaml, and update cloud provider section

![image](https://user-images.githubusercontent.com/1562176/68430408-dfb8a980-0164-11ea-95be-96e315ed70da.png)

4) Click Save. Cloud provider config gets stored on the host

**Comment by alena1108** [comment]
@sangeethah can you validate this issue on the latest 2.3.3 too?

**Comment by jiaqiluo** [comment]
The following tests are done in v2.3-head 5187fce31

Test 1: 
- add a DO single-node cluster, edit as YAML to add the following section from the above comment under the `rancher_kubernetes_engine_config`  section
```
  cloud_provider: 
    name: openstack
    customCloudProvider: |-
      [Global]
      username=${OS_USERNAME}
      password=${OS_PASSWORD}
      auth-url=https://${OS_AUTH_URL}/identity/v3
      tenant-id=${OS_TENANT_ID}
      domain-id=${OS_DOMAIN_ID}

      [LoadBalancer]
      subnet-id=${SUBNET_ID}
```
- SSH to the node and see the values are put under ` /etc/kubernetes/cloud-config`

Test 2:
- similar to test 1, edit as YAML but this time put the `cloud_provider` section outside of `rancher_kubernetes_engine_config` 
- edit the cluster as YAML again and notice the `cloud_provider` section is gone

Test 3:
- add Azure cluster, and choose Azure as the cloud provider, provide all required info via the UI
- SSH to the node and see the values are put under ` /etc/kubernetes/cloud-config`

Test 4:
- Edit the cluster from test 3 as YAML  to copy the  `cloud_provider` section
- add a new Azure cluster, choose Azure as the cloud provider, this time edit as YAML  to past the `cloud_provider` section
- SSH to the node and see the values are put under ` /etc/kubernetes/cloud-config`

**Comment by deniseschannon** [comment]
@patriziobassi If you have any additional issues/questions, please let us know. For now, I'm going to close this issue.
