### ISSUE TITLE
Re-label 'Custom Metrics' tab to 'Custom Metrics Endpoints' in Workload view

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#23737]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Steps to reproduce (least amount of steps as possible):**

Re-label 'Custom Metrics' tab to 'Custom Metrics Endpoints' in the View/Edit Workload view, to make it explicitly clear this is only for configuring the custom endpoint(s) to scrape, and does not display any metrics themselves unlike under the 'Workload Metrics' tab.

**Environment information**
- Rancher v2.2.8

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by jiaqiluo** [comment]
This is validated in `v2.3-head` with UI index `latest-2.3`

- enable the project monitoring
- deploy/edit a workload  
- see the section `Custom Metrics Endpoints` under the advanced options

<img width="1544" alt="Screen Shot 2019-11-05 at 3 44 27 PM" src="https://user-images.githubusercontent.com/6218999/68252708-70677c00-ffe3-11e9-9a31-973097dc3966.png">
