### ISSUE TITLE
[backport] OpenStack Node Driver - "Waiting for SSH to be available" when using privateKeyFile

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#23743]
https://github.com/rancher/rancher/issues/23511

**Comment by sangeethah** [comment]
@dan I am still able to reproduce the issue with new line character being stripped for userdata and cacert fields when testing with latest build from `v2.3-head` - `032f65c63`. 

New line character at the end of `privateKeyFile` field is not lost. But new line character is stripped from the end for `userdata` and `cacert` fields. We should be fixing this for all multi-line fields ?

**Comment by dramich** [comment]
After discussing with @vincent99 we are going to add a new line to cacert and userdata as well.

**Comment by sangeethah** [comment]
Able to reproduce the issue on `v2.3.1`. 
Trailing new line characters  in `privateKeyFile` , `userdata` and `cacert` field are lost when being passed as part of create cmd to driver machine.


Tested with latest build from `v2.3-head` - `75c231e51`
Trailing new line characters  in `privateKeyFile` , `userdata` and `cacert` field are NOT lost when being passed as part of create cmd to driver machine.

Note - Even when there are no Trailing new line characters  `privateKeyFile` , `userdata` and `cacert` field in the templates , the new line characters get appended to the values of these multi-line fields when being sent as part of create cmd to driver machine.
