### ISSUE TITLE
[forwardport] vSphere Lookup API

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#23746]
https://github.com/rancher/rancher/issues/23001

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/23721

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 04965bbe8
UI: `master-dev` 

* Fields are populated by data from vCenter using endpoints:
  * Datacenter
  * Resource Pool
  * Data store
  * Folder
  * Host
  * Networks
  * Tags
  * Custom Attributes
  * Content libraries
  * Existing VMs
  * Templates
