### ISSUE TITLE
Use Helm as the packaging format for RKE Addons

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#23748]
Currently, RKE add ons are customized Golang templates of kubernetes manifests. The add ons have upstream counter parts that have additional options and configurations that are not accessible to the end user. 

Add ons should be updated to use the helm chart counter parts upstream. For instance the nginx-ingress controller helm chart provides several options, such as a validating webhook for verifying configuration. 

The UX for using the new addons in the RKE cluster yaml, both CLI and in Rancher, should be the same. For common flags that are already implemented, we should continue to use the typed interface:

```
ingress:
  provider: nginx
  node_selector:
      app: ingress
  ...
```

Additionally, each add on should have an additional field `chart_options`(flexible on the naming) that allows the user to leverage non-typed chart deployment options. These would be key value pairs, where the values can be any acceptable helm chart input. 

RKE will need to reconcile the options passed via `chart_options` with the typed options. 
A version should be provided via the typed interface. A default version should be pinned to an RKE release, but specifiable by the user.

Order of add on migration:
- [ ]  ingress-nginx
        - chart must support admission webhook.
        - networking via host or service type.
- [x] CoreDNS
- [ ] Network plugins

All charts must support tolerations and node affinity either through the typed or chart option interface. 

Migration from Helm based version should be done with zero downtime. (Unless it is a single node installation) 

Chart updates should be releasable out of band from an RKE/Kubernetes release.
The default charts should be packaged inside the RKE command line and cached within Rancher.

Any update to the addon section in the cluster yaml should cause RKE/Rancher to perform the cluster update using zero downtime methods where possible.

In the Rancher UI, these will continue to show up as they do in Rancher 2.3.2, just workloads within the System Project.

**Comment by fabiorauber** [comment]
I was looking into RKE Templates feature of Rancher, to create a template for our clusters, and noticed we use the same Helm Charts on several clusters. I was hoping to use the template feature for this, but not supporting Helm charts was a dealbreaker. So, +1 for this issue.

**Comment by fabiorauber** [comment]
+1 for this issue
