### ISSUE TITLE
[forwardport] UI: bubble user's node templates to top of list

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23747]
Forwardport of rancher/rancher#23054

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 276702446`

Results:

under the node template page, the templates are listed under owners
![Screen Shot 2019-11-21 at 11 50 49 AM](https://user-images.githubusercontent.com/57409052/69367457-96cd1e80-0c55-11ea-8012-9379e97f2df4.png)

[for admin only] in the page of creating/editing a cluster, the dropdown list of node templates show mine at the top.
![Screen Shot 2019-11-21 at 11 52 59 AM](https://user-images.githubusercontent.com/57409052/69367467-9a60a580-0c55-11ea-8d29-b4eb9c5bdd3a.png)
