### ISSUE TITLE
Add MVP Support for OPA Gatekeeper - Experimental (v2.4)

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#23753]
Rancher should deploy and support Gatekeeper out of the box. 

**Key MVP requirements:**
- Install OPA:
   * Delivered via a system chart, and will have UX similar to the way Rancher deploys Istio into an existing cluster. 
- Dashboard UI:
   * at a minimum, there needs to be UI at the cluster level for editing the Gatekeeper CR objects. This can be a simple editor with Rego syntax highlighting in phase 1.  
   * Stretch for MVP is to have the global level policy manager. 
- Policies:
   * Will reside at the cluster level initially, with plans to be able to apply from a global catalog.

Additional constraints: 
Users should be able to leverage the Custom Resources provided by Gatekeeper directly without using Rancher’s interface. 

Users should be able to enable this through the Terraform provider / cluster provisioning process.

---
Nice to have and future design considerations. These are all tracked under https://github.com/rancher/rancher/issues/26210

**Nice to have:**
Rancher should have some pre-canned policies for whitelisting registries, PSP functionality.
* Nice to have: Simple enable toggle during RKE provisioning similar functionality as monitoring.
**Design Implications:**

Users should be able to setup global policies and apply to one or many clusters.

If rancher has a predefined policy, it should be editable by the user. If the user would like to “reset” and go back to the default setting that should be an option to them.

Out of the box policies that could be included:
1. Policy for whitelisting registries in a namespace, cluster, and globally.
    1. A user should be able to add Registries easily from the UI/API at each scope.
2. Policy for enforcing a specific registry.
    1. At a project, cluster and global level, an admin should be able to rewrite the images to use a specific registry.
3. Policy to enforce cluster level unique ingress names.

Users should be able to leverage Gatekeeper's ability to mutate deployments.

**Comment by skaven81** [comment]
To tack onto this request, the Rancher UI should include a Rego editor that works more-or-less like the Rego playground (https://play.openpolicyagent.org/) except should take advantage of the Rancher API to tune the interface specifically to the Gatekeeper+Rancher schema.  For example, it should allow the user to use a drop-down + search box or something to select an extant resource in a cluster and experiment with how different policies will react to the resource.  The user should be able to make changes to the extant resource, to experiment with how changes to the resource result in a pass/fail (and/or mutation) for the policy.

OPA policy should be stored at the Rancher master level and be distributed to all managed clusters.  A tagging system should be used to determine which policies get applied to which clusters.  The idea being that by centralizing the policy, it will reduce duplication and will work hand-in-hand with cluster templates.

We have a Rancher support case #7680 open to track this implementation as well.

**Comment by khushboo-rancher** [comment]
Tested on Rancher server master-2523-head- 371ec137f.

Things tested:
API:
1. Enabling OPA gatekeeper on a cluster level using v1 API.
2. Template create edit and delete.
3. Constraint create, edit and delete.
4. Constraint for whitelisting repos and constraint for enforcing labels.
5. Verified violations with enforcement type deny and dryrun. 

Issues going to be addressed in coming releases : 
https://github.com/rancher/rancher/issues/25844
https://github.com/rancher/rancher/issues/25816
https://github.com/rancher/rancher/issues/25769

UI:
1. Enabling OPA gatekeeper on a cluster level using UI.
2. UI Dashboard for Constraint template and constraint creation, editing.
3. Constraint applied for whitelisting repos and enforcing labels.
4. Verified violations with enforcement type deny and dryrun.

Issues related to UI: 
https://github.com/rancher/dashboard/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fopa
