### ISSUE TITLE
[Forwardport] Need UI for creating RKE templates from a existing cluster

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23752]
Forwardport of rancher/rancher#23325

**Comment by soumyalj** [comment]
Tested with mater-head using UI-index latest2
Feature to export a RKE template through UI from an existing cluster is functional.
<img width="753" alt="Screen Shot 2019-11-18 at 9 59 46 PM" src="https://user-images.githubusercontent.com/18536626/69122227-22c32880-0a53-11ea-9e57-e1d9e7c678d5.png">
The template/revision exported is displayed in the RKE templates page. Creating new revisions from the template is also functional through UI.
