### ISSUE TITLE
Add ability to issue cluster and project scoped API tokens for Rancher CLI use

### ISSUE THREAD

**Issue by panoslith** [rancher/rancher#23766]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature reqeust

**Details:**
API tokens at the moment can be created with either no scope or with cluster scope. 

The Rancher CLI works with tokens created with no scope as opposed to those with cluster scope that can only be used with the Authorized Cluster Endpoint. 

Adding the ability to generate cluster or project scope tokens for use by Rancher CLI, means permissions will be limited to the cluster/project rather than using global permissions(e.g. in case the user creating the token happens to be Rancher admin).

gz#6819

**Comment by lfdominguez** [comment]
you can check https://gitlab.com/lfdominguez/rancher_proxy
