### ISSUE TITLE
No Ca in kubeconfig file from UI 2.3.1

### ISSUE THREAD

**Issue by quadrinho** [rancher/rancher#23764]
**What kind of request is this (question/bug/enhancement/feature request):**

After creation of AKS Cluster, when we download kubeconfig, in the config file is not present the certificate-authority-data 

**Steps to reproduce (least amount of steps as possible):**
Click on button kubeconfig file

**Result:**

we can't execute any command with kubectl, we receive:

Unable to connect to the server: x509: certificate signed by unknown authority

**Other details that may be helpful:**

In the cluster page we don't see in green the "Controll MAnager" and "scheduler"; they are both in grey.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

Rancher 2.3.1 HA
We use our certificate signed by Recognized CA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Cluster AKS
Kubernetes version --> 1.14.7
VM --> 8 core / 64 gb RAM for 3 nodes
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
The kubeconfig that is generated includes the CA cert that is configured when setting up certificates for Rancher, as it connects to Rancher. When you specify that you are using a recognized CA, you don't need the CA cert as it should already be present on the device (as its recognized). What CA is the certificate from that you are using? Usually this means that you didn't supply the needed intermediate certificate from the CA.

The status for controller manager and scheduler are hidden for AKS as they don't work (and componentstatuses get deprecated at some point), see https://github.com/rancher/rancher/issues/17344

**Comment by quadrinho** [comment]
Hi,

we create the secret for the Rancher ingress with this command:

kubectl -n cattle-system create secret tls tls-rancher-ingress   --cert=tls.crt   --key=tls.key

we don't specify any ca.

Do we have to specify the ca? Which is the parameter? In the ca file , do we put the intermediate and the ca file?

Thanks,

Alessio

**Comment by quadrinho** [comment]
I have re-created the secret for the ingress of rancher adding in one file with cert, intermediate and ca.

After that, the kubectl command works fine.

Just one question to close the issue, AKS Api Server doesn't support a CA ?

**Comment by superseb** [comment]
Great. What does `AKS Api Server doesn't support a CA` mean? What are you trying to do or what have you read that doesn't work?
