### ISSUE TITLE
Rancher Pipeline starts on all branches

### ISSUE THREAD

**Issue by aliazlan4** [rancher/rancher#23765]
I have configured Rancher Pipeline on my project. It should trigger build and deploy when there is a new commit to master branch. But it starts pipeline process if I commit any branch in the repo. It should only make build and deploy on master branch.

---
Rancher Version: 2.3.1
With Github repo

**Comment by gitlawr** [comment]
This is expected. It is not a common practice to trigger builds only on the master branch. You can configure it according to your need, see: https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/pipelines/#trigger-rules

**Comment by aliazlan4** [comment]
@gitlawr thanks man, i got your point.
