### ISSUE TITLE
[Windows] Update upstream flannel plugin

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23761]
Now we are using a forked branch for flannel as upstream flannel doesn't have a release which contains some important Windows commits.

We should switch to use upstream flannel plugin once there is a release which contains the commits

Related issue https://github.com/rancher/rancher/issues/20330

**Comment by StrongMonkey** [comment]
@loganhz Does https://github.com/rancher/flannel-cni need to be updated to constantly rebase upstream?

**Comment by loganhz** [comment]
@StrongMonkey  No, Windows is not using https://github.com/rancher/flannel-cni any more. 

We need to change the flannel download url here https://github.com/rancher/rke-tools/blob/master/package/Dockerfile.windows#L70

But we have to wait https://github.com/coreos/flannel/pull/1209 or https://github.com/coreos/flannel/pull/1238 merged and released.

**Comment by rajatchopra** [comment]
I like #1238 better. If powershell/routing was all the code that we ever wanted (not much btw), lets pull it in. Ideal solution would be an org repo like github.com/Microsoft or something, but anyhow..

**Comment by luthermonson** [comment]
v0.12.0 added to windows rke-tools container https://github.com/rancher/rke-tools/pull/96

**Comment by sowmyav27** [comment]
**Validated using windows 1809 and 1903 on `2.4.6-rc2`**

- Ingress, DNS checks fail in the automation checks
- Manually deploy a daemonset - 3 pods, deploy an ingress.
- The ingress fails to resolve to all the 3 pods.
- It resolves always to only 1 pod.
- On the windows nodes -
```
C:\opt\bin>rancher-wins-flanneld.exe --version                                                                                                        
v0.12.0
```

**Comment by sowmyav27** [comment]
**Verified on 2.4-head - commit id: `fb2c5fb2d`**

- Bring up windows clusters using k8s versions - 1.18.3-rancher2-3, 1.17.7-rancher2-3, 1.16.10-rancher2-3 and 1.15.12-rancher2-4 - 3 linux - etcd, control and worker nodes, and 3 windows nodes.
- Validation checks including Ingress, deployments, daemonsets, nodeport, dns resolution work fine.
- flannel version on the windows nodes:
```
C:\opt\bin>rancher-wins-flanneld.exe   --version                                                                                                      
v0.12.0-rancher1-dirty   
```

**Comment by sowmyav27** [comment]
Reopening this issue to get a fix in master-head

**Comment by sowmyav27** [comment]
**Verified on master-head - `f7e83e3e4`**

- Bring up windows clusters using k8s versions - 1.18.3-rancher2-3, 1.17.6-rancher2-3, 1.16.10-rancher2-3 and 1.15.12-rancher2-4 - 3 linux - etcd, control and worker nodes, and 3 windows nodes.
- flannel version on the windows nodes:
```
C:\opt\bin>rancher-wins-flanneld.exe   --version                                                                                                      
v0.12.0-rancher1-dirty   
```
- Basic checks - ingress, daemonsets, dns resolution works.
