### ISSUE TITLE
Istio mtls network issue on namespaces created by rancher

### ISSUE THREAD

**Issue by mbchristoff** [rancher/rancher#23767]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Install istio on rancher using tools>istio;
- Enable mtls (mesh)policy and destination rule
- Create namespace using rancher and another using kubectl
- Deploy some client-server setup (like the httpbin + sleep sample included with istio);
- Try to connect to the servers using the clients.

Basically following this guide from istio but create the foo namespace using rancher.
[https://istio.io/docs/tasks/security/authn-policy/](url)

**Result:**
Connecting to the server in the namespace created by Rancher will return an upstream error while the server in the namespace created using kubectl will work fine..

```
/ # curl http://httpbin.foo.svc.cluster.local:8000
upstream connect error or disconnect/reset before headers. reset reason: connection failure

/ # curl http://httpbin.bar.svc.cluster.local:8000
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
(truncated)
```

**Other details that may be helpful:**
This issue is related to the namespace where the server side is in, client side can be in either of the created namespaces.
Kiali does not mark the traffic flow on the rancher created namespace as "mtls enabled" while the traffic in the other namespace is.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Nextpertise RKE-dev | v2.3.2 (also tested on v.2.3.1)
User Interface | v2.3.22
Helm | v2.14.3-rancher1
Machine | v0.15.0-rancher12-1

- Installation option (single install/HA): HA

**Comment by teunis90** [comment]
Subscribe to ticket

**Comment by loganhz** [comment]
Is there any difference if you compare the yaml between the working one and not-working one?

**Comment by mbchristoff** [comment]
I already did a diff on the yaml output, the only differences where a label and annotation rancher adds to the namespace to know who made it.
Rancher namespace:
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2019-10-31T08:55:57Z"},{"Type":"ResourceQuotaValidated","Status":"Unknown","Message":"Validating
      resource quota","LastUpdateTime":""},{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2019-10-31T08:55:57Z"}]}'
    field.cattle.io/creatorId: user-zcbzr
    field.cattle.io/projectId: local:p-m4prf
    field.cattle.io/resourceQuota: "null"
    lifecycle.cattle.io/create.namespace-auth: "true"
  creationTimestamp: "2019-10-31T08:55:56Z"
  finalizers:
  - controller.cattle.io/namespace-auth
  labels:
    cattle.io/creator: norman
    field.cattle.io/projectId: p-m4prf
    istio-injection: enabled
  name: foo
  resourceVersion: "17295211"
  selfLink: /api/v1/namespaces/foo
  uid: 402b1792-fbbc-11e9-9952-7a6e5853864d
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

Kubectl namespace:
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2019-10-31T08:56:01Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2019-10-31T08:56:01Z"}]}'
    field.cattle.io/projectId: local:p-m4prf
    lifecycle.cattle.io/create.namespace-auth: "true"
  creationTimestamp: "2019-10-31T08:56:00Z"
  finalizers:
  - controller.cattle.io/namespace-auth
  labels:
    field.cattle.io/projectId: p-m4prf
    istio-injection: enabled
  name: bar
  resourceVersion: "17295337"
  selfLink: /api/v1/namespaces/bar
  uid: 42993f60-fbbc-11e9-9952-7a6e5853864d
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

I've tried digging into the serviceaccounts and their permissions but couldn't find the culprit.
