### ISSUE TITLE
[forwardport] Make 1.15 as default K8s version and 1.16 as GA (not experimental) in the K8s dropdown version presented during RKE cluster provisioning.

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#23774]
https://github.com/rancher/rancher/issues/23689

**Comment by aaronRancher** [comment]
Tested in `rancher\rancher:master-head` `version 781cd0fdc`.

v1.16.3-rancher1-1 is deafult.
![Screen Shot 2019-11-26 at 1 20 11 PM](https://user-images.githubusercontent.com/57409052/69669753-b4342b00-104f-11ea-90b5-14755cd07745.png)
