### ISSUE TITLE
[Forwardport] Translation broken in the UI during login process

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23776]
Forwardport of rancher/rancher#23643

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by sowmyav27** [comment]
**verified on master-head - commit id: `5ccf85b5a` ui tag: `latest2`**

**Steps:**

- Bring up a rancher server
- Launch the url.
- Enter password
- Click on Continue.
- Rancher Server URL settings page looks good.

<img width="1114" alt="Screen Shot 2019-11-18 at 6 23 19 PM" src="https://user-images.githubusercontent.com/26032343/69110815-a586bc00-0a30-11ea-9ab8-5adcfc6529f2.png">
