### ISSUE TITLE
Error in UI console when users navigate to Global --> Settings

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23771]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Navigate to Global --> Settings

**Error in Console:**
<img width="1617" alt="Screen Shot 2019-10-30 at 7 42 17 PM" src="https://user-images.githubusercontent.com/26032343/67886355-53f4bb00-fb6f-11e9-8f06-a3d94964c550.png">

The settings page fails to load.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3-head - latest, ui tag: `latest-2.3`
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sowmyav27** [comment]
**Verified on 2.3-head latest** 

**ui tag: `https://releases.rancher.com/ui/latest-2.3/index.html`**

- Navigate to Global --> Settings
- No error is seen on the UI/console.
- The page loads successfully.
