### ISSUE TITLE
update worker nodes upgrade flow 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#23777]
Currently, worker nodes are updated independently of etcd/controlplane nodes. They also get updated independent of each other. This also implies that once cluster shows up as "active" after control/etcd nodes are upgraded, there's no cluster state that indicates worker nodes' state. We should make the following changes: 

- Worker nodes shouldn't get updated before etcd/controlplane nodes 
- Worker nodes also respect some kind of upgrade strategy such that not all of them are updated simultaneously 
- Introduce logic for upgrade strategy and state transitions so that this information is easily available to be displayed in UI 

https://github.com/rancher/rancher/issues/23038

**Comment by kinarashah** [comment]
created individual issues for these, closing this issue

**Comment by Mapiac** [comment]
Hi @deniseschannon @kinarashah I see alot of these roadmap issues including these 3, slated for 2.4 but they appear to not be in the 2.4-Alpha release. At least not yet. Does that mean they will still be or will more likely be in a later release? Or did I miss them in the alpha commits? Any expected timeframe for this release to be GA?
