### ISSUE TITLE
Sort issue on columns in Cloud Credential Page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23781]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On `2.3-head` latest - ui tag: `latest-2.3`
- Go to Cloud Credentials page.
- Add few cloud credentials.  - 2 in DO, 1 in AWS
- Sort using `#Node Templates` and `Name` happens across all the cloud credentials
- But sort on the `Created` column occurs only for one type of cloud credential - DO.

Sorting should be consistent across all columns

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3 -head
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sowmyav27** [comment]
verified on `2.3-head` ui tag: `latest-2.3`

- Go to Cloud Credentials page.
- Add few cloud credentials. 
- Sorting happens consistently across all columns.
- It happen first based on provider, and the cloud creds of each the provider.
