### ISSUE TITLE
vSphere Node Template - Can add duplicate custom attributes

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23782]
rancher/rancher:v2.3-head 
UI: `latest-2.3`

Users are able to select duplicate custom attribute keys. 

When adding multiple custom attributes, keys that have already been selected should be removed from the dropdown, similar to how `Tags` operate.

![Screen Shot 2019-10-30 at 4.19.23 PM.png](https://zube.io/files/rancher/f7fba0d0444722fea86f569b4bb8af45-screen-shot-2019-10-30-at-4-19-23-pm.png)
(Notice in the `Tags`, `Team/K3S` is unavailable in the second tag)

**To Reproduce**
* Create a vsphere node template
* Add a custom attribute
* Add a second custom attribute
  * All attributes are shown, including the attribute selected in the previous step

**Expected**
* Attributes that have already been selected should not be shown in subsequent dropdowns

**Actual**
* User can select duplicate attributes

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 6611960c9
UI: `latest-2.3`

When adding multiple custom attributes, attributes that have already been selected can not be added again.

When all custom attributes have been added, the button is disabled.
