### ISSUE TITLE
vSphere Node Template - Add Network button is disabled

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23780]
rancher/rancher:v2.3-head 032f65c63
UI: `latest-2.3`

When creating a vSphere Node Template, the `Add Network` button is disabled. 

![Screen Shot 2019-10-30 at 12.52.40 PM.png](https://zube.io/files/rancher/422ce99b48fb36c4c45ff5c45195b90e-screen-shot-2019-10-30-at-12-52-40-pm.png)

This causes cluster creation to fail as it cannot find the default network:

![Screen Shot 2019-10-30 at 3.22.09 PM.png](https://zube.io/files/rancher/3fd9b5f987c5ed02b4d8563e2de0dacc-screen-shot-2019-10-30-at-3-22-09-pm.png)

**To reproduce**
* Login as a standard user
* Create a vSphere node template
* Attempt to click `Add Network` in Instance Options

**Comment by codyrancher** [comment]
Are you still able to reproduce? I just pulled down the latest and it seems to be working fine for me.
![Screen Shot 2019-10-30 at 4.49.07 PM.png](https://zube.io/files/rancher/a10ef9bc27dd4f18701dfc3d463564c5-screen-shot-2019-10-30-at-4-49-07-pm.png)

**Comment by sangeethah** [comment]
@codyrancher We are using UI tag : `latest-2.3` . Do you see this issue fixed with this UI tag?

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
UI: `latest-2.3`

The add network button is no longer disabled and cluster can be created successfully.
