### ISSUE TITLE
Feature request: re-build container

### ISSUE THREAD

**Issue by JulianKingman** [rancher/rancher#2378]
I would love to easily rebuild containers, with a few changes here and there. Basically, this would do the same thing as 'clone', but would let me use the same container name, almost providing the appearance of being able to edit containers.

**Comment by deniseschannon** [comment]
This can be done with an in-service upgrade. This has been available for any release v0.43.1+ which was released at end of October. 

In the UI, there is now an "Upgrade" option which will bring up a screen like adding a new service or cloning, which will end up replacing your service. 

Using Rancher-Compose: 
http://docs.rancher.com/rancher/rancher-compose/upgrading/#in-service-upgrade
