### ISSUE TITLE
Ability to specify API Group when editing roles via the Rancher UI

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#23785]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Steps to reproduce (least amount of steps as possible):**

When creating and editing Cluster and Project roles in the Rancher UI it is not possible to specify an API Group for a rule. Similarly, if you create a rule with an API Group via the API, the API Group does not display in the rule when viewed via the UI. User would like the API Group shown in the UI and the ability to edit the API Group for a rule via the UI also.

**Environment information**
- Rancher v2.2.8

**Comment by loganhz** [comment]
FYI we have added it in 2.3.0 https://github.com/rancher/rancher/issues/16254

**Comment by axeal** [comment]
Thanks @loganhz I did have a search, but had missed that. Closing this.
