### ISSUE TITLE
[ui] Delete and Download YAML buttons not aligned in deployment pod section

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#23784]
**What kind of request is this (question/bug/enhancement/feature request):**
cosmetic UI bug

**Steps to reproduce (least amount of steps as possible):**
On the UI, go to a workload and drill into the pod view

**Result:**
The Delete button is below the Download YAML button. They should be on the same line. 
![image](https://user-images.githubusercontent.com/468462/67908003-0b211000-fb37-11e9-95f1-e62c741518b8.png)

**Other details that may be helpful:**
Page reloads and looks fine.
MacOS X 10.14.6 / Firefox 70.0

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.2
- Installation option (single install/HA):
HA

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version ebe495938`

UI shows  Download and Delete next to each other. 
![Screen Shot 2019-11-20 at 4 28 06 PM](https://user-images.githubusercontent.com/57409052/69287350-279eee00-0bb3-11ea-9556-69bd8838a89e.png)
Unfortunately, it takes about a few minutes for these changes to happen upon refresh. Until then, buttons are not aligned.
![Screen Shot 2019-11-20 at 4 29 51 PM](https://user-images.githubusercontent.com/57409052/69287355-2cfc3880-0bb3-11ea-9e4d-df911a51fc4f.png)

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 276702446`

Buttons are aligned instantly:
![Screen Shot 2019-11-21 at 10 13 52 AM](https://user-images.githubusercontent.com/57409052/69360458-cffe9200-0c47-11ea-9a1b-e5c85612e910.png)
