### ISSUE TITLE
[Regression] rancher/lb-service-haproxy:v0.9.13:  Malformed encoding found in chunked-encoding (v0.9.11 is ok)

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#23787]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

When using `rancher/lb-service-haproxy:v0.9.13`, getting this error with curl on our backend:

```
curl: (56) Malformed encoding found in chunked-encoding
```

**Result:**

Works fine with `rancher/lb-service-haproxy:v0.9.11`.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v1.6.29
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 17:24:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by konvergence** [comment]
Hi may be there are some correction to do into custom haproxy.cfg because of haproxy 2.0.5 ?
the previous rancher/lb-service-haproxy:v0.9.11 has bring with haproxy  1.8.19

```
root@abac4b6b0483:/# /usr/sbin/haproxy -v
HA-Proxy version 2.0.5-1ppa1~xenial 2019/08/16 - https://haproxy.org/
```

**Comment by jloisel** [comment]
I tried with and without custom config, none work fine in `v0.9.13`. Here is the custom config we use:

```
defaults
compression algo gzip
compression type application/json text/html text/plain
```

The issue prevents responses with "Transfer-Encoding: chunked" from being properly downloaded from our server. The load balancer seems to truncate the response.

**Comment by konvergence** [comment]
I tried rancher/lb-service-haproxy:v0.9.13
I think like jloisel there is a regression.


I have 2 haproxy :
- the first receive external IP  with HTTPS TLS 1.2 and backend on another haproxy 
- the 2de use himself HTTPS TLS 1.2

On the 1st haproxy I get error "SD" error
And see on de 2de en error "CD"

     CD   The client unexpectedly aborted during data transfer. This can be
          caused by a browser crash, by an intermediate equipment between the
          client and haproxy which decided to actively break the connection,
          by network routing issues between the client and haproxy, or by a
          keep-alive session between the server and the client terminated first
          by the client.


     SD   The connection to the server died with an error during the data
          transfer. This usually means that haproxy has received an RST from
          the server or an ICMP message from an intermediate equipment while
          exchanging data with the server. This can be caused by a server crash
          or by a network issue on an intermediate equipment

**Comment by konvergence** [comment]
I tested with haproxy 2.0.9 and the result is better

root@cc338474ab06:/# haproxy -v
HA-Proxy version 2.0.9-1ppa1~xenial 2019/11/17 - https://haproxy.org/

When you look https://www.haproxy.org/download/2.0/src/CHANGELOG
there  was a BUG/MAJOR : ssl: ssl_sock was not fully initialized since 2.0.6+

Please release a correction into the dockerfile : 

RUN add-apt-repository -y ppa:vbernat/haproxy-2.0 \
    && apt-get update \
    && apt-get install -y haproxy=2.0.9-1ppa1~xenial

**Comment by denisgolius** [comment]
Yaybe someone can help me to add acl white-ip.lst into balancer while running as Volume or something else?
Because I find only one solution - build own rancher/lb-service-haproxy ...
