### ISSUE TITLE
[forwardport] vSphere Node Template - Add Network button is disabled

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23793]
Forwardport of rancher/rancher#23780

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested in `rancher\rancher:master-head` `version 781cd0fdc`.

The add network button is no longer disabled and cluster can be created successfully.
![Screen Shot 2019-11-26 at 8 57 35 AM](https://user-images.githubusercontent.com/57409052/69650141-63124000-102b-11ea-897c-acf26359a9ac.png)
![Screen Shot 2019-11-26 at 8 58 31 AM](https://user-images.githubusercontent.com/57409052/69650162-6b6a7b00-102b-11ea-9225-b8046d513bf6.png)

![Screen Shot 2019-11-26 at 9 11 18 AM](https://user-images.githubusercontent.com/57409052/69651053-bc2ea380-102c-11ea-9d4c-c5add64122a3.png)
