### ISSUE TITLE
[Forwardport] UI Issue while adding a Service Discovery record

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23791]
Forwardport of rancher/rancher#23772

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by sowmyav27** [comment]
**verified on master-head latest commit id: `6ef25c42c`- ui tag: `latest2`**

**Steps:**

- Go to Cluster --> project (Default) --> Workload --> Deploy a workload
- Go to Service Discovery --> Add Record
- Select One or more workloads
- Click on Add Target Workload
- User is able add workloads and create service discovery
<img width="1383" alt="Screen Shot 2019-11-18 at 6 18 36 PM" src="https://user-images.githubusercontent.com/26032343/69110508-e0d4bb00-0a2f-11ea-9e06-d4a3a33748d3.png">
