### ISSUE TITLE
vSphere - Docker fails to install on Ubuntu 19.04 using Rancher's Docker install script

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23799]
rancher/rancher:v2.3-head
UI: `latest-2.3`

Docker fails to install on Ubuntu 19.04 using the default Docker install URL. 

Users should be able to install Docker using Rancher's install scripts.

```
[ERROR] NodeController c-7t7g7/m-z8dfr [node-controller] failed with : Error creating machine: Error running provisioning: error installing docker:
```

To reproduce:
* Create a Rancher server in Fremont DC
* Create a node template for vSphere which uses creation method from a a template: `ubuntu-disco-19.04-cloudimg`
* Create the cluster
* Provisioning fails with an error that Docker cannot be installed

Workaround:
* Use `https://get.docker.com` as the Docker install URL

**Comment by luthermonson** [comment]
this is an ubuntu issue and we can't do anything about it. if you use the 18.04 or 17.04 images older versions of the docker install scripts work fine.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head

Cloned from an Ubuntu 18.04 template w/ Rancher Docker install script and created cluster successfully.
