### ISSUE TITLE
Cannot edit vSphere node template that creates from RancherOS or Clone

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23796]
rancher/rancher:v2.3-head
UI: `latest-2.3`

After creating a vSphere node template that has `RancherOS` selected in the creation method, or `Clone from another virtual machine`, the node template edit screen does not appear when attempting to edit.

Console error:
```
Uncaught (in promise) TypeError: Cannot read property 'map' of null
    at n.initCustomAttributes (component.js:532)
    at n.init (component.js:118)
    at n [as init] (utils.js:366)
    at m (core_object.js:83)
    at Function.e.create (core_object.js:611)
    at e.n.create (container.js:554)
    at t.i.create (glimmer.js:4320)
    at Object.evaluate (runtime.js:1559)
    at e.t.evaluate (runtime.js:72)
    at e.t.evaluateSyscall (runtime.js:3471)
```

![Screen Shot 2019-10-31 at 2.53.49 PM.png](https://zube.io/files/rancher/480556a15577dcf24ab221892bfd4b03-screen-shot-2019-10-31-at-2-53-49-pm.png)

To reproduce:
* Create a node template for vSphere
* Select `RancherOS` in creation method
* Save
* Attempt to edit node template

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
UI: `latest-2.3`

When editing an existing template, all lookup fields are spinning without showing data. 
I see the data getting returned by the lookup endpoints in the browser network console. 

This also occurs on the `Add node template` screen, but only for `Creation method` field.

<img width="1465" alt="Screen Shot 2019-11-01 at 10 07 38 AM" src="https://user-images.githubusercontent.com/21316915/68042513-4edb5d00-fc90-11e9-8b7c-8407545f7dc5.png">

<img width="1366" alt="Screen Shot 2019-11-01 at 9 58 15 AM" src="https://user-images.githubusercontent.com/21316915/68042549-6a466800-fc90-11e9-9025-e942f27c84ce.png">

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 75c231e51
UI: `latest-2.3`

* Can create and edit vSphere node templates without issue
