### ISSUE TITLE
[forwardport] Cannot edit vSphere node template that creates from RancherOS or Clone

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23809]
Forwardport of rancher/rancher#23796

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested in `rancher\rancher:master-head` `version 781cd0fdc`.
Can create and edit vSphere node templates without issue.

![Screen Shot 2019-11-26 at 8 49 26 AM](https://user-images.githubusercontent.com/57409052/69649656-986a5e00-102a-11ea-91af-9afa60a7f972.png)
![Screen Shot 2019-11-26 at 8 50 10 AM](https://user-images.githubusercontent.com/57409052/69649666-9c967b80-102a-11ea-8262-cceac8cb7b4a.png)
