### ISSUE TITLE
UI loads slow with 100 clusters

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#23807]
When attempting to view the cluster page with 100 clusters the UI fetches all resources and the spinning box is seen for a long while.

**Comment by westlywright** [comment]
Both myself and @dramich looked at this and the slowness is coming from rancher server. Testing with 150 clusters. Slowness was seen when retrieving data from rancher server via the network analyzer in chrome dev tools while the clusters were provisioning. The call to `v3/clusters`, for example, was taking 10-12 seconds before the first byte of the response was sent, subsequently it only took 55ms to load the response data when sent by the server according to chrome. The bottleneck is not the UI. When the clusters finish provisioning, the responses from the server start to become fast again.

**Comment by dramich** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/24931
