### ISSUE TITLE
mgmt-auth-crtb-controller keeps attempting to create the same object

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#23804]
The controller is making hard create calls every time instead of validating if the object exists first. This appears to happen in multiple places in the same area. 

```2019/10/29 18:44:19 [ERROR] ClusterRoleTemplateBindingController c-k424m/creator-cluster-owner [mgmt-auth-crtb-controller] failed with : couldn't create role cluster-owner: roles.rbac.authorization.k8s.io "cluster-owner" already exists```

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 2/4

* Reproduced in v2.3.3 
* Created a cluster and some test users and cluster/project roles
* Assigned different users to the clusters/projects w/ varying roles
* Deleted some and assigned again
* Check logs and see several instances of:
```
2020/02/04 21:39:14 [ERROR] ProjectRoleTemplateBindingController p-kj8p5/creator-project-owner [cluster-prtb-sync] failed with : couldn't create role project-owner-promoted: clusterroles.rbac.authorization.k8s.io "project-owner-promoted" already exists
2020/02/04 21:39:14 [ERROR] GlobalRoleBindingController globalrolebinding-znd2q [grb-sync] failed with : clusterrolebindings.rbac.authorization.k8s.io "globaladmin-user-842tp" already exists
2020/02/04 21:39:14 [ERROR] ProjectRoleTemplateBindingController p-kj8p5/creator-project-owner [cluster-prtb-sync] failed with : couldn't create role project-owner-promoted: clusterroles.rbac.authorization.k8s.io "project-owner-promoted" already exists
```

* Deploy `master-head` 
* Follow same steps as above
* No related errors seen in the logs
