### ISSUE TITLE
docker-machine Updates for UI

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#23803]
some params need to change and work for the UI to work properly per conversation with @codyrancher functionally won't change but will add/remove params so the UI can work properly with the editing process as some of the selections get lost with how many fields we have today.

creation types: `vm, template, library, legacy`
```
1. method - enum of 4 values discussed above
2. datacenter-template
3. content-library
4. library-template
5. virtual-machine
6. boot2dockerUrl
```

**Comment by luthermonson** [comment]
https://github.com/rancher/machine/pull/45

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/23910

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/23921

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 22801eeed
UI: `latest-2.3`

* Can create a node from a nodeTemplate with each creation type: `vm, template, library, legacy`
* Node templates created pre-upgrade to v2.3.3+ can be used without any changes
