### ISSUE TITLE
grb-sync runs a lot

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#23806]
grb-sync runs a lot when provisioning and deleting clusters. 3x the next closest controller is not uncommon and this appears to be because of the contention of all the handlers attempting to get their finalizer on a cluster. The more clusters the more of an issue this becomes. 

Is it possible to drop the finalizer and just turn this into a sync? Or perhaps an owners reference.

**Comment by dramich** [comment]
![Load-test mariadb](https://user-images.githubusercontent.com/13897607/68054964-cd45f800-fcac-11e9-9dd3-e08d92c0f7de.png)

**Comment by dramich** [comment]
This is seen when attempting to create many clusters, in my case 100, in quick succession. Using the metrics endpoint hooked into grafana using the above dashboard is the best way to see this issue.

**Comment by dramich** [comment]
grb-sync is now a global level lifecycle which is used to enforce the deletion of cluster role bindings based off deletion of GRBs in the management cluster. 
There is a cluster scoped sync that creates the initial role of admin bindings at the time of cluster creation which adds a condition to ensure the sync completes once. 
A 2nd cluster scoped sync for GRBs runs for all create/updates to grbs which creates/updates the user cluster cluster role binding.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 2/11

These issues re: scalability are hard to reproduce without testing at scale, so focused on regressions via automation: 

* Deployed Rancher
* Deployed multiple custom clusters
* Ran automation smoke tests and long running tests for a total of ~400 tests
* Automation runs succeeded with only a few known failures
