### ISSUE TITLE
VSphere node template doesn't populate some fields on edit

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23812]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

The Creation Method section of the form doesn't populate the saved values when editing a VSphere node template unless it's a RancherOS ISO method.

**Steps to reproduce (least amount of steps as possible):**
1. Create a VSphere node template using the "Clone an existing virtual machine" creation method.
1. Edit the node template

**Result:**
Creation method will be "Deploy from template: Data center"

To resolve this issue we're going to need these backend changes: rancher/rancher#23803

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 75c231e51
UI: `latest-2.3`

* Reproduced in earlier version of `v2.3-head`
* Created a node template for each creation method and saved
* Edited each node template - Deploy from Datacenter Template, Deploy from Content Library, Clone existing VM, RancherOS
  * Each node template contained the correct creation method and values
