### ISSUE TITLE
Cannot delete cluster role

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23823]
v2.2.8

Steps:

1. Go to create Cluster Role page
2. Add "a Inherit from a Role" 
3. Create the role
4. Edit the newly created role and delete the Inherit Role.
5. Click Save
6. Try to delete any cluster roles in UI

Results:

No role can be deleted

Expected:

Users should be able to delete the roles in this case

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sowmyav27** [comment]
### **Reproduced the issue on `v2.3.2`**

**Steps:**

- Go to Global --> Security --> Roles --> Clusters --> Add Cluster Role page
- Add "a Inherit from a Role"
- Create the role
- Edit the newly created role and delete the Inherit Role.
- Click Save
- Try to delete the created user role.
- Cluster role will not be deleted.

Another way to reproduce the issue:
- Go to Global --> Security --> Roles --> Clusters --> Add Cluster Role page
- Add "a Inherit from a Role", Create the role
- Try to delete the created user role.
- Cluster role will not be deleted.

### Verified the fix in 2.3 head with ui tag: `latest-2.3`

**Steps:**

- Go to Global --> Security --> Roles --> Clusters --> Add Cluster Role page
- Add "a Inherit from a Role"
- Create the role
- Edit the newly created role and delete the Inherit Role.
- Click Save
- Try to delete the created user role.
- Cluster role will be deleted.

Another scenario:
- Go to Global --> Security --> Roles --> Clusters --> Add Cluster Role page
- Add "a Inherit from a Role", Create the role
- Try to delete the created user role.
- Cluster role will be deleted.
