### ISSUE TITLE
[Forwardport] Incorrect node memory usage gauge when cluster monitoring is enabled

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23824]
Forwardport https://github.com/rancher/rancher/issues/23786

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 9930781c8`

add a cluster with 2 workers, worker-1 has 4GB memory and worker-2 has 16GB
enable the cluster monitoring

The correct values are shown:
![Screen Shot 2019-11-15 at 9 45 17 AM](https://user-images.githubusercontent.com/57409052/68960123-c16a3380-078c-11ea-8a3c-a667b613b27f.png)
