### ISSUE TITLE
Cannot clone workloads with sidecar

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#23821]
Currently on the Rancher platform, sidecar's workload cannot be cloned, but many customers currently use the sidecar method to initialize the application POD. It is not very convenient to use the clone function. It is recommended to increase the workload with sidecar clone function. In most cases, sidecar does not need to be modified. It only needs to modify the application POD, so you only need to add the clone after editing the POD. You can see the requirement to modify the clone of the sidecar page.

@loganhz

**Comment by d3473r** [comment]
This is not fixed yet
