### ISSUE TITLE
[Forwardport] Sort issue on columns in Cloud Credential Page

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23828]
Forwardport of rancher/rancher#23781

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by sowmyav27** [comment]
**verified on `master-head` ui tag: `latest2`**

- Go to Cloud Credentials page.
- Add few cloud credentials.
- Sorting happens consistently across all columns.
- It happen first based on provider, and the cloud creds of each the provider.
