### ISSUE TITLE
[Forwardport] Cannot delete cluster role

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23825]
https://github.com/rancher/rancher/issues/23823

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by sowmyav27** [comment]
**Verified on master-head latest - commit id: `6ef25c42c` UI tag: `latest2`**

**Steps:**

- Go to Global --> Security --> Roles --> Clusters --> Add Cluster Role page
- Add "a Inherit from a Role"
- Create the role
- Edit the newly created role and delete the Inherit Role.
- Click Save
- Try to delete the created user role.
- Cluster role will be deleted.
