### ISSUE TITLE
[forwardport] podsecuritypolicytemplateprojectbindings does not validate template exists

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#23833]
https://github.com/rancher/rancher/issues/22556

PR https://github.com/rancher/rancher/pull/23110

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 276702446`

If the podSecurityPolicyTemplateId is an invalid value, 422 error is returned
`{"baseType":"error","code":"InvalidBodyContent","message":"podSecurityPolicyTemplate not found","status":422,"type":"error"}`

If the podSecurityPolicyTemplateId is missing, 422 error is returned
`{"baseType":"error","code":"MissingRequired","fieldName":"podSecurityPolicyTemplateId","message":"","status":422,"type":"error"}`
