### ISSUE TITLE
Create "protect"/"unprotect" actions on higher level resources (stack, environment, host)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2383]
When multiple users share an environment, there could be a potential to accidentally delete someone else's stack (Despite the confirmation page). 

It would be nice to add in a "protect"/"unprotect" action on stacks so that it would be another hurdle for people who are accidentally deleting stacks. 

http://forums.rancher.com/t/is-it-possible-to-protect-stack-from-editing/711/6

**Comment by antmanler** [comment]
+1

**Comment by demarant** [comment]
+1
Yes just put a "Lock-icon" on the upper right corner of a stack will help a lot.

**Comment by demarant** [comment]
related to possibility to restore (aka regret) of a deleted Stack https://github.com/rancher/rancher/issues/3272

**Comment by gcallsen** [comment]
+1 to the 'Lock" concept. Regardless of user, it would be fantastic to lock against accidentally stopping a Stack or Service (similar to how AWS has termination protection in a sense).  This is particularly helpful for mission critical stacks/services like a database.  We just accidentally clicked "Stop" on a whole cassandra cluster stack - so this is coming from experience!

**Comment by vincent99** [comment]
@gcallsen FYI there's a confirm modal now for that in either the last or next release.

**Comment by gcallsen** [comment]
@vincent99 - great, thank you for heads up!  I'd love the 'Lock' feature to still be considered for a future release only because it's easy to get on 'Auto Pilot' and dismiss modals without really reading the message.  That's clearly user-error but this would be a key feature to 'save you from yourself' when running production apps.

**Comment by jjscarafia** [comment]
+1 for this Lock concept!
