### ISSUE TITLE
rancher app install from local directory fails with 404 Not Found

### ISSUE THREAD

**Issue by rextca** [rancher/rancher#23832]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a helm chart in directory mychart.
cd mychart
login to rancher server: rancher login -t token-g4htb:glfbmnb48g7q2dblln645etc https://ustr-rancher.myco.com
rancher --debug app install . my-name

**Result:**
DEBU[0000] Namespace create wait - Name: mychart-u9nhi, State: activating, Transitioning: yes
DEBU[0001] Namespace create wait - Name: mychart-u9nhi, State: activating, Transitioning: yes
FATA[0001] Bad response statusCode [404]. Status [404 Not Found]. Body: [baseType=error, code=NotFound, message=failed to find resource by id] from [https://ustr-rancher.myco.com/v3/project/c-trxcm:p-2ssw8/apps]

**Other details that may be helpful:**
This also fails with Rancher 2.3.2 and CLI 2.0.6.  It worked on Rancher 2.3.0 with CLI 2.0.6.

I tried various paths to the chart, like ./mychart while in the parent of mychart and fully specifying the path with no success.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.2
Rancher CLI version: v2.3.1
- Installation option (single install/HA):
Single

- Machine type (cloud/VM/metal) and specifications (CPU/memory): docker container
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- Docker version (use `docker version`):

Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:56:24 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Tue Feb 12 22:47:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Here is the log for the period before and through a few seconds after a failure:
2019/11/01 16:48:40 [INFO] Updating global catalog harbor-sing
2019/11/01 16:48:40 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:48:46 [INFO] Updating global catalog harbor-sing
2019/11/01 16:48:46 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:48:51 [INFO] Updating global catalog harbor-sing
2019/11/01 16:48:51 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:48:57 [INFO] Updating global catalog harbor-sing
2019/11/01 16:48:57 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:49:03 [INFO] Updating global catalog harbor-sing
2019/11/01 16:49:03 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:49:08 [INFO] Updating global catalog harbor-sing
2019/11/01 16:49:08 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:49:14 [INFO] Updating global catalog harbor-sing
2019/11/01 16:49:14 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:49:19 [INFO] Updating global catalog harbor-sing
2019/11/01 16:49:19 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:49:25 [INFO] Updating global catalog harbor-sing
2019/11/01 16:49:25 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:49:30 [INFO] Updating global catalog harbor-sing
2019/11/01 16:49:30 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:49:36 [INFO] Updating global catalog harbor-sing
2019/11/01 16:49:36 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:49:41 [INFO] Updating global catalog harbor-sing
2019/11/01 16:49:41 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:49:47 [INFO] Updating global catalog harbor-sing
2019/11/01 16:49:47 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:49:53 [INFO] Updating global catalog harbor-sing
2019/11/01 16:49:53 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:49:58 [INFO] Updating global catalog harbor-sing
2019/11/01 16:49:58 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:50:04 [INFO] Updating global catalog harbor-sing
2019/11/01 16:50:04 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
2019/11/01 16:50:06 [INFO] Creating roleBinding User user-fqmgc Role project-owner
2019/11/01 16:50:06 [INFO] Creating roleBinding User user-fqmgc Role admin
2019/11/01 16:50:06 [INFO] Creating roleBinding User u-hjwixeg6bo Role edit
2019/11/01 16:50:06 [INFO] Creating roleBinding User u-hjwixeg6bo Role project-member
2019/11/01 16:50:09 [INFO] Updating global catalog harbor-sing
2019/11/01 16:50:09 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted

gzrancher/rancher#8933

**Comment by Quantas** [comment]
I also experience this exact same issue since Rancher 2.3.2. Currently it is preventing me from deploying new applications. I am on Rancher 2.3.2, CLI 2.3.1, K8s 1.15.5, CentOS 7. Please let me know what other information you need.

**Comment by ericlarssen-wf** [comment]
Confirmed in Rancher 2.3.3 as well

**Comment by rextca** [comment]
Thanks for the confirmation, Eric.  

This problem presents a major inconvenience during development and debug of a new chart because every iteration must be packaged and pushed to a repository in order to test it.  We had developers switch to using Linux when a similar problem ([Issue 22484](https://github.com/rancher/rancher/issues/22484)) was introduced in the Rancher CLI for Windows.  Now we seem to have no alternative to cluttering up the repo with every iteration.

Rex

**Comment by ericlarssen-wf** [comment]
This is a breaking change. Is there anything that can be done to get the attention of the maintainers?

**Comment by ericlarssen-wf** [comment]
@sowmyav27 we are looking for a contributor to look at this

**Comment by sowmyav27** [comment]
**Verified on `2.3.0` rancher**

- create a chart in directory - 
- login to rancher through the CLI
- install app

```
./rancher app install . my-name
run "app show-notes my-name" to view app notes once app is ready

$ ./rancher app ls
ID                NAME      STATE       CATALOG           TEMPLATE             VERSION
p-wvv5c:my-name   my-name   deploying   local directory   fluentd-aggregator   0.2.1
```

- App gets installed

**On 2.3.3 rancher's CLI,**

- create a chart in directory - 
- login to rancher through the CLI
- install app
- error seen on running the following command
```
./rancher app install . my-name
FATA[0002] Bad response statusCode [404]. Status [404 Not Found]. Body: [baseType=error, code=NotFound, message=failed to find resource by id] from [https://<rancher-server>/v3/project/c-xf6km:p-9rm9t/app
```

**Comment by benzman81** [comment]
We keep running into this issue whenever we are upgrading rancher. Then we always have to downgrade again. Our policy now is to block rancher upgrades until this is fixed.

**Comment by rhangelxs** [comment]
Any workaround on current version? I tried to make a raw API request, but didn't find right method.

**Comment by ericlarssen-wf** [comment]
@sowmyav27  Can we get some context on what is going on with this bug?  Why is this not a bug? Why this is getting put on the backlog?

**Comment by maggieliu** [comment]
Hi @ericlarssen-wf,  We are currently reprioritizing the backlog in preparation for the next maintenance release. We finalized the 2.4 release and this one didn't make it. That's why it got moved back to the backlog.

**Comment by ericlarssen-wf** [comment]
@maggieliu Not being able to deploy a local chart seems like a pretty Major bug in the scheme of things. This is a feature many people use to test changes to their chart without publishing to a registry.

**Comment by rextca** [comment]
I agree with ericlarssen-wf.  Not being able to use this forces us to push every experiment to the registry.

**Comment by dedsm** [comment]
I switched to using the api directly via ansible because of this, maybe an option for you

**Comment by ScOut3R** [comment]
Worked with 2.4.2 but failing with this error with 2.4.3.

**Comment by rawmind0** [comment]
Verified
> Worked with 2.4.2 but failing with this error with 2.4.3

Failing on rancher v2.4.3 with cli v2.4.0 and v2.4.3. [`ProjectClient.App.Create(app)`](https://github.com/rancher/cli/blob/v2.4.3/cmd/app.go#L721) function is returning error. 

Same issue creating APP from rancher API. Doing POST on `/v3/project/local:p-qrs4z/apps`

**Comment by rancher-max** [comment]
#### Validated in both `master-3301-head` and `v2.4-3302-head` using CLI version v2.4.5

- Installing apps from local works successfully. There is no more 404 error.
- Validated with helm v2 apps and helm v3 apps. Helm v3 apps can fail due to the apps installing with helm v2 by default and there being no option to install v3 (https://github.com/rancher/rancher/issues/27916)
- Also used automation to validate 404 error is not received

**Comment by bcarriou** [comment]
Hi,
What's version of rancher-cli  which supposed to be use with rancher-v2.4.5 ?
It's not clear for me ...
 Thx

**Comment by rancher-max** [comment]
Hi @bcarriou, you should be able to use cli v2.4.5: https://github.com/rancher/cli/releases/tag/v2.4.5

Generally I find it easiest to just download the CLI directly from the Rancher UI (bottom right side of the screen).
