### ISSUE TITLE
[forwardport] vSphere Node Template - Can add duplicate custom attributes

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23841]
Forwardport of rancher/rancher#23782

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested in `rancher\rancher:master-head` `version 781cd0fdc`.

Create a vsphere node template.
Add a custom attribute.
Add a second custom attribute.
Attributes that have already been selected can not be added again.
![Screen Shot 2019-11-26 at 9 34 39 AM](https://user-images.githubusercontent.com/57409052/69653268-285ed680-1030-11ea-8876-9607a0655a25.png)
When all custom attributes have been added, the button is disabled.
