### ISSUE TITLE
UI - On deploying a workload, incorrectly shows 0 pods created

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23842]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On an rke cluster, deploy a workload.
- The workload goes into Updating state and becomes Active. But the number of pods shown is 0.

<img width="1320" alt="Screen Shot 2019-11-02 at 4 03 34 AM" src="https://user-images.githubusercontent.com/26032343/68060419-4d5c7400-fd26-11e9-9662-afaead18f6b3.png">
<img width="1268" alt="Screen Shot 2019-11-02 at 4 03 41 AM" src="https://user-images.githubusercontent.com/26032343/68060420-4e8da100-fd26-11e9-891a-de69bb9bae0b.png">

**Note:** on doing a hard refresh of the page, the pods deployed are shown correctly.
<img width="1278" alt="Screen Shot 2019-11-02 at 4 06 50 AM" src="https://user-images.githubusercontent.com/26032343/68060425-50576480-fd26-11e9-88b9-c082ff206807.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `2.3-head` - latest - ui tag: `latest-2.3`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): do rke
- Kubernetes version (use `kubectl version`):

```
1.15.5
```

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by westlywright** [comment]
I think this may be related to https://github.com/rancher/rancher/issues/23973, I am going to hold off on investigating this more until we have more info on that ticket. https://github.com/rancher/rancher/issues/23973

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sangeethah** [comment]
Tested with latest rancher server version - `5187fce31`.

On deployment of a workload , pod count gets updated correctly.
