### ISSUE TITLE
I want a view of resource usage and availability at the Env level in the UI

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#2384]
I would like to be able to see the resource usage and availability  environment level in the UI. I know the data points will be a bit different. Like you may just show available memory, CPU, and a total count of containers running, and things like this. Mesos provides something like this, but I know you guys will do something much nicer. :-)

**Comment by vincent99** [comment]
There is actually an API call for aggregated stats on all the hosts of an environment already, we just haven't figured out where to fit displaying it into the UI.

**Comment by lavvy** [comment]
Lol. Api for that already exists, please you can place it in a dashboard
like in openstack or you can stick it the rancher admin page.
We have actually been expecting something like this.

**Comment by eebjr** [comment]
@vincent99, What is this API for aggregated stats? And what access and secret key would I pass to it?

**Comment by vincent99** [comment]
Containers, hosts, stacks (environments in the API) and environments (projects in API) all have a `containerStats` and/or `hostStats` link in them.. you GET that link and get back a `ws://` URL and a `token`, which you can either send as a header `Authorization: Bearer long_token_string` or add to the URL as a query param `?token=long_token_string`.

You'll get an initial flood of frames with data for the past minute, then a continual stream of them for each resource once a second.  The data is more or less straight out of cAdvisor and many of them are just always-increasing counters so there is some massaging and comparing to the previous data point(s) needed to get useful things like CPU used% out.

**Comment by deniseschannon** [comment]
We have a request for a dashboard. @eebjr @lavvy Would you like to add your feedback on that page and then close this duplicate issue?

https://github.com/rancher/rancher/issues/2718

**Comment by eebjr** [comment]
it's a duplicate of  [UI] Proposal of a Dashboard as default home page #2718

**Comment by demarant** [comment]
related to #3362
