### ISSUE TITLE
vSphere - Create Node Template page fails to completely load

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23845]
rancher/rancher:v2.3-head
UI: `latest-2.3`

When creating a new vSphere node template, the `Creation method` field fails to load, spinning forever. 
Additionally, the `Custom Attributes` section is completely empty. 

To reproduce, just create a new vSphere node template.

![Screen Shot 2019-11-01 at 4.14.03 PM.png](https://zube.io/files/rancher/bcfe88fa153513982fa554ee98afbc76-screen-shot-2019-11-01-at-4-14-03-pm.png)

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 6611960c9
UI: `latest-2.3`

Node template creation page loads and cluster creation succeeds
