### ISSUE TITLE
DNS resolution does not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23847]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a custom cluster - 1 linux node - all roles, 2 windows nodes - 1809 version - Azure nodes - cloud provider set.
- Deploy 2 windows workload.
- curl on wk01 from wk02.

**Result:**

```
C:\>curl wk04/name.html
curl: (6) Could not resolve host: wk04
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3-head latest
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom windows
- Kubernetes version (use `kubectl version`):

```
v1.15.5
```

- Docker version (use `docker version`):

```
19.3.4
```

**Comment by nvivo** [comment]
Looks like there are some major DNS issues with 2.3, not only with windows.

I started getting strange errors after upgrading to 2.3. cattle pods kept restarting, and then cert-manager was unable to register new certificates due to not resolving the acme servers.

@sowmyav27 may this be related to #23284?

**Comment by kingsd041** [comment]
This problem may be related to the k8s_agent_cattle-node-agent-windows startup failure, error log:
```
time="2019-11-04T04:39:06Z" level=info msg="Connecting to wss://45.33.37.148/v3/connect with token m8w9rmpqpn28x6kt42cjhbsrrrbgjmhbdrvjjx7kglxm7679fxhb99"
time="2019-11-04T04:39:06Z" level=info msg="Connecting to proxy" url="wss://45.33.37.148/v3/connect"
time="2019-11-04T04:39:06Z" level=error msg="Remotedialer proxy error" error="Error response from daemon: invalid volume specification: 'c:/lib/modules:c:/host/lib/modules': invalid mount config for type \"bind\": bind source path does n
ot exist: c:\\lib\\modules"
```

I tried to manually create the `c:/lib/modules` directory on windows ndoe, k8s_agent_cattle-node-agent-windows started successfully, then the DNS resolution worked

**Comment by loganhz** [comment]
It looks like it is introduced in the IPVS PR https://github.com/rancher/rke/pull/1724

**Comment by loganhz** [comment]
Hi @prachidamle , could you help to revert the IPVS change for Windows please? IPVS not supported in Windows. Now windows agent is broken in 2.3-head due to this.

**Comment by sowmyav27** [comment]
IPVS related issue - https://github.com/rancher/rancher/issues/13769

**Comment by sowmyav27** [comment]
**Verified on latest 2.3-head - commit id: `22483d475`**

- Deploy a custom cluster - 1 linux node - all roles, 2 windows nodes - 1809 version - AWS nodes
- Deploy 2 windows workload.
- curl on wk01 from wk02 works.
- Curl on workload cross namespace with full FQDN works.
