### ISSUE TITLE
Keys with dot, return results with empty values in UI and API when multi cluster catalog application 'nfs-client-provisioner' is deployed

### ISSUE THREAD

**Issue by panlith** [rancher/rancher#23859]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
-When multi cluster app 'nfs-client-provisioner' is launched:
For keys that include dot, their values do not appear in Answers in UI, if are not overridden.
For keys that include dot, their values do not appear in API under Answers section.
For keys that include dot, their values do not appear in UI when selecting to Upgrade the app.

Setup:
-Rancher v2.3.2 
-Global->Tools->Catalogs->Enable Helm catalog, with [default](https://kubernetes-charts.storage.googleapis.com/) catalog url

Test 1(working) - no dot used in key:

-Global->Apps->Launch->nfs-client-provisioner
-Provide values for: Name, Target Project
-Provide the following Answers:
path=/
key=value
foo=bar

-Override an Answer and assign to a project:
foo=tar

-Should look like this:
![image](https://user-images.githubusercontent.com/55960073/68128125-08dffc80-ff0f-11e9-8e8b-60b00de60a75.png)
-Click Launch

Results Test 1:
-Click on the Target Project link for the app and then Expand Answers. All values will be present.
![image](https://user-images.githubusercontent.com/55960073/68128169-201eea00-ff0f-11e9-9cd2-dbdeb7787ca6.png)

-Select from the app `View in API` and values will be present:
```
"answers": [ 2 items
{
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer",
"values": {
"foo": "bar",
"key": "value",
"path": "/"
}
},
{
"clusterId": null,
"projectId": "c-vxjcp:p-qhdgd",
"type": "/v3/schemas/answer",
"values": {
"foo": "tar"
}
}
],
```
-Try `Upgrade` the app, all key values pairs should be present:
![image](https://user-images.githubusercontent.com/55960073/68128505-c5d25900-ff0f-11e9-8090-fb7d0032a404.png)

Test 2(not working) - use of dot in key:

-Global->Apps->Launch->nfs-client-provisioner
-Provide values for: Name, Target Project
-Provide the following Answers:
nfs.mountOptions[0]=nolock
nfs.path=/
nfs.server=1.1.1.1

-Override an Answer and assign to a project:
nfs.path=/env/prod
nfs.server=2.2.2.2

-Should look like this:
![image](https://user-images.githubusercontent.com/55960073/68128762-409b7400-ff10-11e9-8895-f29630ac0e0f.png)

-Click Launch

Results Test 2:
-Click on the Target Project link for the app and then Expand Answers. Only the overridden key value pairs will be present. The non overridden are missing. They should be present, since are default for all projects.

![image](https://user-images.githubusercontent.com/55960073/68128892-7f312e80-ff10-11e9-8dd4-c01976ba4b39.png)

 -Select from the app `View in API`. 
All values from Answers are missing. Only overridden key values pairs appear.
```
"answers": [ 2 items
{
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer",
"values": {
"nfs.mountOptions[0]": "",
"nfs.path": "",
"nfs.server": ""
}
},
{
"clusterId": null,
"projectId": "c-vxjcp:p-qhdgd",
"type": "/v3/schemas/answer",
"values": {
"nfs.path": "/env/prod",
"nfs.server": "2.2.2.2"
}
}
],
```

-Try `Upgrade` the app. Only the keys are present, all values are missing.

![image](https://user-images.githubusercontent.com/55960073/68129084-ddf6a800-ff10-11e9-8d9e-3efe31e30ccd.png)

**Comment by sowmyav27** [comment]
Related bug : https://github.com/rancher/rancher/issues/23379

**Comment by deniseschannon** [comment]
@codyrancher Can we backport the fix from `master` into the `2.3-fixes` branch so it could be part of 2.3.3?

**Comment by codyrancher** [comment]
@deniseschannon sure. I'll create a backport issue.

**Comment by deniseschannon** [comment]
Opening this to get specifically tested for QA.

**Comment by soumyalj** [comment]
Reproduced the issue with v2.3.0

Steps:
Create a multi cluster app with nfs-client-provisioner. Provide answer keys with dot and they are not passed correctly through UI.
```
answers: [{type: "answer", clusterId: null, projectId: null,…}]
0: {type: "answer", clusterId: null, projectId: null,…}
clusterId: null
projectId: null
type: "answer"
values: {nfs.mountOptions[0]: "", nfs.path: "", nfs.server: ""}
nfs.mountOptions[0]: ""
nfs.path: ""

```

Tested with v2.3-head from Nov 11.
Create a multi cluster app with nfs-client-provisioner. Provide answer keys with dot and they are passed correctly through UI.
```
{revisionHistoryLimit: 10, timeout: 300, wait: false, type: "multiclusterapp",…}
answers: [{type: "answer", clusterId: null, projectId: null,…}]
0: {type: "answer", clusterId: null, projectId: null,…}
clusterId: null
projectId: null
type: "answer"
values: {nfs.path: "/", nfs.server: "1.1.1.1", nfs.mountOptions[0]: "nolock"}

```
View in API for answers section:
```

answers": [
{
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer",
"values": {
"nfs.mountOptions[0]": "nolock",
"nfs.path": "/",
"nfs.server": "1.1.1.1"
}
}
],

```

View in API when overrides are also provided:
```
answers": [ 2 items
{
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer",
"values": {
"nfs.mountOptions[0]": "nolock",
"nfs.path": "/",
"nfs.server": "1.1.1.1"
}
},
{
"clusterId": null,
"projectId": "c-m57q6:p-k26xk",
"type": "/v3/schemas/answer",
"values": {
"nfs.server": "2.2.2.2"
}
}
]


```

**Comment by qubusp** [comment]
Reproducing the same issue while using tf rke platform 
version 2.3.5 
resource looks like this: 
```
resource "rancher2_cluster" cluster {
  name        = var.cluster_name
  description = "Cluster: ${var.cluster_name}"
  rke_config {
    network {
      plugin = "canal"
    }
    cloud_provider {
      aws_cloud_provider {
        global {
          kubernetes_cluster_id = var.cluster_name
          kubernetes_cluster_tag = var.cluster_name
          role_arn = aws_iam_role.rancher.arn
   }
  }
 }
}
```
var.cluster_name is a string, the result i'm getting in the api is: 

```
"answers": {
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer"
},
"appliedEnableNetworkPolicy": false,
"appliedPodSecurityPolicyTemplateId": "",
"appliedSpec": {
"agentImageOverride": "",
"answers": {
"clusterId": null,
"projectId": null,
"type": "/v3/schemas/answer"
},
```

It has never worked so far.
