### ISSUE TITLE
Unable to install cert-manager v0.11 via Rancher 2.3.2

### ISSUE THREAD

**Issue by dnauck** [rancher/rancher#23850]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug?

**Steps to reproduce (least amount of steps as possible):**
1. Add jetstack ( https://charts.jetstack.io ) repository as app catalog via rancher ui.
2. Install cert-manager CRDs: ```kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml```
3. Create "cert-manager" namespace in System project.
4. Launch "cert-manager" app from catalog with name "cert-manager" and in existing namespace "cert-manager"

![image](https://user-images.githubusercontent.com/97584/68499741-3bb12a00-025a-11ea-960e-1b039a0fcd05.png)

**Result:**

Error: resource's namespace kube-system doesn't match the current namespace cert-manager

```
[main] 2019/11/02 11:47:05 Starting Tiller v2.14+unreleased (tls=false)
[main] 2019/11/02 11:47:05 GRPC listening on :47978
[main] 2019/11/02 11:47:05 Probes listening on :36421
[main] 2019/11/02 11:47:05 Storage driver is ConfigMap
[main] 2019/11/02 11:47:05 Max history per release is 10
[tiller] 2019/11/02 11:47:06 getting history for release cert-manager
[storage] 2019/11/02 11:47:06 getting release history for "cert-manager"
Release "cert-manager" does not exist. Installing it now.
[tiller] 2019/11/02 11:47:06 preparing install for cert-manager
[storage] 2019/11/02 11:47:06 getting release history for "cert-manager"
[tiller] 2019/11/02 11:47:06 rendering cert-manager chart using values
2019/11/02 11:47:06 info: manifest "cert-manager/charts/cainjector/templates/psp-clusterrolebinding.yaml" is empty. Skipping.
2019/11/02 11:47:06 info: manifest "cert-manager/templates/servicemonitor.yaml" is empty. Skipping.
2019/11/02 11:47:06 info: manifest "cert-manager/templates/psp.yaml" is empty. Skipping.
2019/11/02 11:47:06 info: manifest "cert-manager/templates/psp-clusterrolebinding.yaml" is empty. Skipping.
2019/11/02 11:47:06 info: manifest "cert-manager/charts/cainjector/templates/psp.yaml" is empty. Skipping.
2019/11/02 11:47:06 info: manifest "cert-manager/templates/psp-clusterrole.yaml" is empty. Skipping.
2019/11/02 11:47:06 info: manifest "cert-manager/charts/cainjector/templates/psp-clusterrole.yaml" is empty. Skipping.
[tiller] 2019/11/02 11:47:06 performing install for cert-manager
[tiller] 2019/11/02 11:47:06 executing 0 crd-install hooks for cert-manager
[tiller] 2019/11/02 11:47:06 hooks complete for crd-install cert-manager
[tiller] 2019/11/02 11:47:06 executing 0 pre-install hooks for cert-manager
[tiller] 2019/11/02 11:47:06 hooks complete for pre-install cert-manager
[storage] 2019/11/02 11:47:06 getting release history for "cert-manager"
[storage] 2019/11/02 11:47:06 creating release "cert-manager.v1"
[storage] 2019/11/02 11:47:06 getting release history for "cert-manager"
[kube] 2019/11/02 11:47:06 building resources from manifest
[tiller] 2019/11/02 11:47:06 warning: Release "cert-manager" failed: resource's namespace kube-system doesn't match the current namespace cert-manager
[storage] 2019/11/02 11:47:06 updating release "cert-manager.v1"
[tiller] 2019/11/02 11:47:06 failed install perform step: release cert-manager failed: resource's namespace kube-system doesn't match the current namespace cert-manager
2019/11/02 11:47:07 [ERROR] AppController p-sv954/cert-manager [helm-controller] failed with : failed to install app cert-manager. Error: release cert-manager failed: resource's namespace kube-system doesn't match the current namespace cert-manager

```

**Other details that may be helpful:**

**Environment information**
Rancher 2.3.2 single instance, aks 1.14.7 cluster

**Comment by dnauck** [comment]
It was also reported on an older version and closed as rancher bug by jetstack:

https://github.com/jetstack/cert-manager/issues/1380

**Comment by insekticid** [comment]
you are using two different namespaces cert-manager and kube-system, define namespace cert-manager when installing from helm chart

**Comment by dnauck** [comment]
@insekticid  I can only select **one** namespace via rancher ui, an that is "cert-manager"

**Comment by insekticid** [comment]
Look here:
https://github.com/jetstack/cert-manager/blob/dddc6abd2e0075648df2eddcff765b4986e9497d/deploy/charts/cert-manager/templates/webhook-rbac.yaml#L36

and here
https://github.com/jetstack/cert-manager/blob/57f6dad0c273f6c091329fda0e8935d4f535cc20/design/release-notes/release-0.11/draft-release-notes.md

Change the default leader election namespace to 'kube-system' instead of the same namespace as the cert-manager pod, to avoid multiple copies of cert-manager accidentally being run at once (#2155, @munnerz)

Maybe there is bug when installing via helm chart, report it here https://github.com/jetstack/cert-manager/issues

**Comment by r734** [comment]
I installed cert-manager v0.11.0 with Helmv3 into Rancher 2.3.2 with the following commands, as described on the [official helm chart page](https://hub.helm.sh/charts/jetstack/cert-manager):

```bash
kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml
helm repo add jetstack https://charts.jetstack.io
kubectl create namespace cert-manager
helm install --generate-name --namespace cert-manager jetstack/cert-manager -f k8s/files/cert-manager-cfg.yaml
```

Contents of `k8s/files/cert-manager-cfg.yaml`:
```yaml
podDnsConfig: None
podDnsConfig:
  nameservers:
    - 1.1.1.1
```

(Necessary in my setup to avoid issues with the internal network's DNS preventing cert-manager from seeing that TXT records are propagated)

I don't really trust installing this sort of thing from a GUI...Something always seems to go wrong.

Hope this helps!

**Comment by dnauck** [comment]
So it is a limitation or bug in Rancher's helm handling ?! :(

**Comment by wc-matteo** [comment]
same issue. It seems rancher doesn't handle installing on multiple ns.

**Comment by blackholegalaxy** [comment]
If you want to use the catalog, you can add the following option:
`global.leaderElection.namespace = cert-manager`

cert-manager allow us to override the second destination namespace.

**Comment by wc-matteo** [comment]
thanks @blackholegalaxy. Does it have any consequence installing everything in the same ns?

**Comment by munnerz** [comment]
It's not uncommon for a single Helm chart to need to deploy resources into more than once namespace, although it isn't necessarily 'expected'. In this instance, it is required as we need to ensure that leader election is performed between *all* installations of cert-manager, to prevent two instances running in a single cluster due to being installed multiple times via app catalogs etc.

It seems like Rancher has a Helm operator of some description that is responsible for applying/installing things from the catalog - IMO, this should be extended to not fail/error in cases where resources need to go in other namespaces, as it is an arbitrary restriction and cert-manager will not be the only tool that requires this.

**Comment by dnauck** [comment]
> If you want to use the catalog, you can add the following option:
> `global.leaderElection.namespace = cert-manager`
> 
> cert-manager allow us to override the second destination namespace.

Sadly that does not work (tested with v.0.12) .. i still get the same error .. strange

**Comment by dnauck** [comment]
It only works with ```webhook.enabled = false```

**Comment by mkanakis** [comment]
For me it does not work even with @blackholegalaxy settings.

cert-manager pod gets up however I get the following on cert-manager-cainjector:

`
cert-manager/controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"Certificate\" in version \"cert-manager.io/v1alpha2\"" "kind"={"Group":"cert-manager.io","Kind":"Certificate"}
error registering controllers: no matches for kind "Certificate" in version "cert-manager.io/v1alpha2"
`

Does anyone have the same?

**Comment by himpierre** [comment]
well, with webook disabled it's pretty much useless, no?

**Comment by avluis** [comment]
@himpierre if you need the webhook (in my case for testing), I just edited the annotation `webhook.enabled` after install and set it to true:

![Capture](https://user-images.githubusercontent.com/875593/71792203-d6817700-3005-11ea-8da6-8d824b7ef92b.PNG)

**Comment by himpierre** [comment]
@avluis Thanks. Seems to work.

**Comment by soriyath** [comment]
for some reasons, it did not work for me.
I had to install it in the `kube-system` namespace, with this config:

```
---
  image: 
    tag: "v0.12.0"
  ingressShim: 
    defaultIssuerKind: "ClusterIssuer"
    defaultIssuerName: "letsencrypt-staging"
  webhook: 
    enabled: "true"
```

**Comment by beshkenadze** [comment]
My work solution is:

1. Install the custom resource definition **before** the helm app: `kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/v0.13.0/deploy/manifests/00-crds.yaml`

2. Install the helm app with values: 
```
---
  global: 
    leaderElection: 
      namespace: "cert-manager"
  webhook: 
    enabled: "false"
```

3. Upgrade the helm app with values: 
```
---
  global: 
    leaderElection: 
      namespace: "cert-manager"
  webhook: 
    enabled: "true"
```

3. Profit!  
<img width="765" alt="Screenshot 2020-02-04 at 18 24 57" src="https://user-images.githubusercontent.com/167288/73758447-aa2f5680-477b-11ea-9ca3-4810f9751fc9.png">

**Comment by caiconkhicon** [comment]
Thank @beshkenadze , your solution works for me. However, it's really bad for your automation (using Terraform). Do you have any idea when will Rancher/Cert-manager fix this issue?

**Comment by chrisfosterelli** [comment]
It seems kind of surprising how challenging it is to get letsencrypt running on Rancher. We've got great out of the box support for nginx ingress controllers on RKE clusters... I feel like letsencrypt is another part of that puzzle that could be a first class integration. To do that this needs to be wayyyyy more smooth and without issues like this one.
