### ISSUE TITLE
Rancher logo clickable, but does nothing

### ISSUE THREAD

**Issue by Sheldonwl** [rancher/rancher#23851]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Open rancher, login and click on the blue Rancher logo in the top left corner. 

**Result:**
Nothing happens

**Other details that may be helpful:**

**Environment information**
Rancher 2.x

**Comment by loganhz** [comment]
Please see https://github.com/rancher/rancher/issues/13153
