### ISSUE TITLE
[rancher-compose]  non-zero exit status on incorrect usage

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#2385]
When you type `rancher-compose blarg` the CLI returns a 0 exit status. The CLI should return a non-0 exit status in this case (typically in this case, its 1 or 2). Zero is used in scripting to denote that the command was successful.

    $ rancher-compose blarg; echo $?;
    0
    $ git blarg; echo $?;
    1
    $ cd blarg; echo $?;
    1
    $ ls blarg; echo $?;
    2
    $ aws blarg; echo $?;
    2
    $ tar blarg; echo $?;
    2
    $ apt-get blarg; echo $?;
    100

**Comment by tombmurphy** [comment]
Any ETA on this please ?

**Comment by vincent99** [comment]
This is really 3 levels deep, rancher-compose -> docker/libcompose -> https://github.com/codegangsta/cli/issues/276

**Comment by deniseschannon** [comment]
Exits correctly if the correct command is selected, but if you use the original poster's use case, it still exists 0.

**Comment by deniseschannon** [comment]
```
$ rancher-compose blarg; echo $?;
-bash: rancher-compose: command not found
127
```
Verified with v0.9.3-rc1

**Comment by flaccid** [comment]
@deniseschannon I think that might be not in your PATH.
But to confirm it appears to work in a basic example:
```
$ rancher-compose blarg; echo $?;
No help topic for 'blarg'
3
```
