### ISSUE TITLE
Improve performance of cluster cluster/project logging

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#23858]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

Fluent Bit provides a lightweight log collection and forwarding solution and uses approx. 1/10th of the resources (memory and  cpu) compared to Fluentd. This makes it much better suited as a per node log collection solution in general and especially for edge environments where resources are limited.

**Expected behaviour**

Cluster/project logging uses fluent bit as log collector.

**Comment by cbron** [comment]
Closing, as this will be completed via logging v2 in https://github.com/rancher/rancher/issues/27935 and its other issues.
