### ISSUE TITLE
[Forwardport] 2.4: Should not be able to assign pod security policy in project

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#23862]
Forwardport: https://github.com/rancher/rancher/issues/21548

**Comment by aaronRancher** [comment]
The bug fix is validated in `Rancher:v2.3-head da8cbdb` with the default UI-index `latest-2.3`
https://github.com/rancher/rancher/issues/21548#issuecomment-549490946

**Comment by aaronRancher** [comment]
Fix validated with Rancher server `rancher\rancher:master-head` `version 4beb5cf3e`

When the cluster's psp is disabled, the project create/edit page does not show the option for psp anymore.
![Screen Shot 2019-11-14 at 10 16 12 AM](https://user-images.githubusercontent.com/57409052/68880080-d7fa8700-06c7-11ea-8db8-1c48264ce2a1.png)
