### ISSUE TITLE
[Forwardport] - UI - On deploying a workload, incorrectly shows 0 pods created

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23866]
Forwardport of rancher/rancher#23842

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version abd6f58c6`

On deployment of a workload , pod count gets updated correctly.
