### ISSUE TITLE
Allow for the configuration of the livenessProbe settings for prometheus-cluster-monitoring

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#23874]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement/feature request

It would be helpful to be able to modify the livenessProbe setting for prometheus-cluster-monitoring in the Rancher UI.

In clusters with large Prometheus databases, it can take upwards of 3 minutes to spin up Prometheus workloads and we need to configure the `​initialDelaySeconds` `livenessProbe​` in the `prometheus-cluster-monitoring` yaml to account for the additional time it takes to start TSDB, so we can prevent crash looping.

**Comment by cloudnautique** [comment]
@loganhz @thxCode , are we only going to add some variables to the chart and document? That feels like it would be sufficient initially vs. adding UI. Are you going to add to all the deployments?

**Comment by loganhz** [comment]
@cloudnautique agree, we will make it configurable all the deployments in chart only.

**Comment by jbilliau5668** [comment]
@shanewxy It looks like PR #153 from rancher/system-charts this was closed and merged into this issue? Any idea when that will get merged and released? We need this functionality for writing to a remote prometheus endpoint and are currently stuck until we can get it.

**Comment by jiaqiluo** [comment]
The enhancement is validated in master-head ff24cb9e3 with the monitoring template 0.0.8

When enabling the cluster monitoring or project monitoring, pass the following answers under the advanced section in the monitoring enabling page
```
prometheus.livenessProbe.initialDelaySeconds = 33
prometheus.readinessProbe.initialDelaySeconds = 33
exporter-kube-state.livenessProbe.initialDelaySeconds = 33
exporter-kube-state.readinessProbe.initialDelaySeconds = 33
grafana.readinessProbe.initialDelaySeconds = 33
grafana.livenessProbe.initialDelaySeconds = 30
grafana.livenessProbe.failureThreshold = 10
grafana.livenessProbe.httpGet.path = /api/health
grafana.livenessProbe.httpGet.port = 3000
grafana.livenessProbe.periodSeconds = 1
grafana.livenessProbe.successThreshold = 1
grafana.livenessProbe.timeoutSeconds = 1 
```
![image](https://user-images.githubusercontent.com/6218999/74786848-ef1eb700-526a-11ea-8dea-f0dfbe5d4924.png)

then after the monitoring app is deployed and active, go to check the corressponding workloads' YAML files (the option View/Edit YAML for each workload). We can see that those values are applied.

<img width="321" alt="Screen Shot 2020-02-18 at 4 22 21 PM" src="https://user-images.githubusercontent.com/6218999/74786863-f8a81f00-526a-11ea-8266-80ff217e8a48.png">

Note:
- For project monitoring, only the values for Grafana are applied to the workload `grafana-project-monitoring`
