### ISSUE TITLE
remove EKS 1.11 support

### ISSUE THREAD

**Issue by gliptak** [rancher/rancher#23876]
Kubernetes v1.11 End of Support (Nov 4, 2019)
https://github.com/aws/containers-roadmap/issues/464

**Comment by soumyalj** [comment]
Tested with master-head (Rancher version a70698d25 )
1. Create a EKS cluster in UI 
2. EKS 1.11 is not a supported version in Rancher
![Screen Shot 2020-02-24 at 9 45 16 AM](https://user-images.githubusercontent.com/18536626/75179313-a8a7dd00-56ee-11ea-83a2-c41c2ce885e7.png)

Verified EKS cluster comes up correctly with the supported version v1.14
