### ISSUE TITLE
Errors when getting library catalog (rancher/charts)

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#23873]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
start rancher

**Result:**
logs show the following:
`2019/11/04 12:08:21 [INFO] Updating global catalog library
2019/11/04 12:08:22 [INFO] Helm icon error: unknown file type [files://../grafana-logo.png]
2019/11/04 12:08:22 [INFO] Helm icon error: open management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078/charts/kafka/v0.8.0/logo.png: no such file or directory
2019/11/04 12:08:22 [INFO] Helm icon error: unknown file type [files://../logo.png]
2019/11/04 12:08:22 [INFO] Helm icon error: unknown file type [files://../logo.png]
2019/11/04 12:08:22 [INFO] Catalog sync done. 38 templates created, 0 templates updated, 0 templates deleted
2019/11/04 12:08:22 [ERROR] CatalogController library [catalog] failed with : failed to sync templates. Resetting commit. Multiple error occurred: [yaml: unmarshal errors:
 line 5: cannot unmarshal !!seq into map[string]string]`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master (11/4/2019)

**Comment by guangbochen** [comment]
Link to PR https://github.com/rancher/charts/pull/316 . 
The error message is raised by [helm.go#L527](https://github.com/rancher/rancher/blob/master/pkg/catalog/helm/helm.go#L527), update rancher/charts to use `file://` prefix of local icon path.

**Comment by deniseschannon** [comment]
This is available in `master` of charts.

**Comment by sangeethah** [comment]
When testing with `v2.3.1` (and latest `v2.3.head`) , logs mentioned in the issue is not seen.

But we see the following error message which is tracked in https://github.com/rancher/rancher/issues/23969

```
2019/11/07 19:26:36 [INFO] Updating global catalog library
2019/11/07 19:26:37 [INFO] driverMetadata initialized successfully
2019/11/07 19:26:37 [INFO] Helm icon error: open management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078/charts/neuvector/NeuVector-Logo.png: no such file or directory
2019/11/07 19:26:38 [INFO] Helm icon error: open management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078/charts/kafka/v0.8.0/logo.png: no such file or directory
2019/11/07 19:26:38 [INFO] Catalog sync done. 38 templates created, 0 templates updated, 0 templates deleted
```
