### ISSUE TITLE
While editing an EKS cluster there's problems with subnet modifications

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23879]
Component | Version
-- | --
Rancher | v2.2.5
User Interface | v2.2.89
Helm | v2.10.0-rancher11
Machine | v0.15.0-rancher8-1

![image](https://user-images.githubusercontent.com/83597/61453964-70ba0980-a957-11e9-8914-f4bcb407b1a7.png)

On VPC & Subnet options VPC & subnet is greyed out and set to standard (it carries the standard through to next section on click) ignoring that the vpc was previously configured.

You have to click public ip to yes then back to no to be able to select custom again.
The subnets are all deselected at this point (again it's ignoring previous config).

Once you've made it to the save button, you can see the previous edit you made to the node config is there, but looking in AWS nothing has actually been applied (CF template params are the same / asg hasn't altered etc)

Originally reported in rancher/rancher#21611

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by izaac** [comment]
@westlywright I'm testing this in `rancher master-head (11/21/2019) 276702446`

This issue is specific to Edit but Im getting errors while adding the EKS clusters, not sure if this is a known issue:

Scenario 1: Using all automatic options in the UI.

```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.
Error creating stack with VPC template: stack failed to create: reason unknown
```

Scenario 2: using a custom VPC a different VPC is selected in security groups step.

- Enter Keys and select region us-east-2. Next
- Select Rancher Service role and left k8s 1.14 selected. Next
- VPC & Subnet choose custom and select the last vpc-* in the dropdown. Next
- Make sure to choose custom (The previously selected VPC is not chosen).
    - Select the vpc-* selected previously and all its subnets. Next
- Notice a different VPC and subnets are selected

**Comment by izaac** [comment]
Creating EKS clusters with default Rancher UI values is now working. There's an issue with Scenario 2 mentioned above that I've created a new issue for. https://github.com/rancher/rancher/issues/24481

**Comment by izaac** [comment]
`Rancher version 2.4 master-head (12/17/2019)` e8fbc0c84

1. I create a cluster with a VPC which has 4 subnets.
2. Cluster gets created. 
3. I am able to edit the cluster and the VPC can be selected now.
4. After selecting the VPC, I unselect one of the subnets. 
5. After saving I see the subnet I unselected is no longer listed.
6. Save the security group.
7. Finally save settings.

After all that I now edit the cluster again and I see the cluster is listing 3 subnets. But in AWS EKS web console I see the original 4 subnets from step 1. So this not seems to be applying the settings in the EKS cluster.

**Comment by westlywright** [comment]
@izaac this behavior seems to indicate that rancher allows you to change these but the provider does not. The backend should change the schemas to not be updatable if they are not available to update. A new ticket should be created for this. The changes the UI is making are persisting to the backend which is the scope of this ticket.

**Comment by izaac** [comment]
Opened a separate issue: https://github.com/rancher/rancher/issues/24652
