### ISSUE TITLE
[forwardport] VSphere node template doesn't populate some fields on edit

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23875]
Forwardport of rancher/rancher#23812

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested in `rancher\rancher:master-head` `version 781cd0fdc`.

Create a node template for each creation method and saved.
Edited each node template - Deploy from Datacenter Template, Deploy from Content Library, Clone existing VM, Install from boot2docker ISO (Legacy).
Each node template contained the correct creation method and values.
