### ISSUE TITLE
Load Balancing entry stucked in Initialzing Rancher 2.3.1

### ISSUE THREAD

**Issue by pcasis** [rancher/rancher#23885]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug/Question

**Result:**
Ingress entry is stucked in Initializing but works well.

**Environment information**
- Rancher version : 2.3.1
- Installation option : Single

![image](https://user-images.githubusercontent.com/25147189/68191870-bce59400-ffb0-11e9-9b1d-fb9db9d07052.png)

However, it is possible to access the application. So it works welle even if this message is present

**Comment by zhuer0632** [comment]
一样的问题
