### ISSUE TITLE
Can't enable cluster monitoring

### ISSUE THREAD

**Issue by basroovers** [rancher/rancher#23889]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Upgrade to 2.3.2 from 2.2.8.
Enable cluster monitoring.

**Result:**
Workload: prometheus-cluster-monitoring is not running
```
create Pod prometheus-cluster-monitoring-0 in StatefulSet prometheus-cluster-monitoring failed error: Pod "prometheus-cluster-monitoring-0" is invalid: spec.containers[2].volumeMounts[1].name: Not found: "nginx-home"
```

**Environment information**
- Rancher version 2.3.2
- Single install cluster

**Cluster information**
- Cluster type : Custom
- Machine type : VM (4 vCPU - 4096MB
- Kubernetes version : v1.15.5 also didn't work on v1.14
- Docker version : 19.3.4
- Guest OS: Ubuntu 18.04.3 LTS

**Comment by rudymccomb** [comment]
I'm noticing what may be a similar issue on all of my clusters. I deployed 2.3.1 last week and updated to 2.3.2 today and nothings changed
Rancher was deployed via helm on KOPS 1.13.11 cluster in AWS
I'm unable to enable monitoring and there is no version in my monitoring drop down
![image](https://user-images.githubusercontent.com/3885192/68236687-40ac7a00-ffcb-11e9-9a9b-c926475ce1a5.png)

![image](https://user-images.githubusercontent.com/3885192/68236724-5326b380-ffcb-11e9-946c-700c4b486467.png)

**Comment by DJAyth** [comment]
Just ran into this myself. If you look under Apps there is another app called monitoring-operator. That one should have an upgrade available for it, if you upgrade that then the cluster monitoring should upgrade as well. Worked for me.

**Comment by basroovers** [comment]
That seems to work for me too. I've been able to successfully execute this on 1 of our clusters which has the issue.

**Comment by jiaqiluo** [comment]
I cannot reproduce the bug, here are what I did:

- run Rancher v2.2.8 single install
- add two identical clusters: K8s v1.14.6, 1 etcd + control plan, 3 workers 
- enable the cluster monitoring(v0.0.3) in cluster2
- upgrade Rancher to 2.3.2
- enable the cluster monitoring(v0.0.5) in cluster1
- upgrade the cluster monitoring to v0.0.5 in cluster2

Results:
- the cluster monitoring works in both cluster

@basroovers  Are my steps different from yours? Do I miss anything?

**Comment by basroovers** [comment]
I never enabled monitoring on the 2.2.8 cluster. Only after the upgrade to 2.3.2. That might be the difference.

**Comment by rudymccomb** [comment]
My local cluster is showing the following error 
Failed to get System Project ID: failed to find any cattle system project

This error appeared after I tried to enable monitoring.
![image](https://user-images.githubusercontent.com/3885192/68517139-ec63fd00-024b-11ea-83c1-d610e66db13d.png)

**Comment by Sssamyy** [comment]
>  I'm unable to enable monitoring and there is no version in my monitoring drop down

I had the same issue with my cluster.
To correct it you can configure Rancher server to use the packaged copy of Helm system charts.
In your helm template you have to add : `--set useBundledSystemChart=true`
Then `kubectl -n cattle-system apply -R -f ./rancher` to reload it.

source : https://rancher.com/docs/rancher/v2.x/en/installation/air-gap/install-rancher/

But after enabling monitoring the  Workload: prometheus-cluster-monitoring is not running !

`create Pod prometheus-cluster-monitoring-0 in StatefulSet  prometheus-cluster-monitoring failed error: Pod  "prometheus-cluster-monitoring-0" is invalid:  spec.containers[2].volumeMounts[1].name: Not found: "nginx-home"`

It seems this pod ask for a persistent volume even if you set  `Enable Persistent Storage for Grafana` at `false `when activating monitoring.

Disabling and deleting the cattle-prometheus namespace in the system project and enabling again monitoring few times have solved this issue for me but I'm unable to know where the error came from or to reproduce it...

**Comment by h3d-haivq** [comment]
Same here
Upgraded from Rancher 2.2.7 to Rancher 2.3.2

I upgrade the Monitoring tool from 0.0.3 to 0.0.5 or disable Monitoring tool and recreate 0.0.5 version but failed everytime, I also try the 0.0.4 version and it works fine. But on another cluster, upgrading 0.0.3 to 0.0.5 it doesn't cause any issue. The only different from the two is the error cluster having NVIDIA driver daemonset.

**Comment by eroji** [comment]
Encountered this problem as well after upgrading to 2.3.3 from 2.3.2. I'm attempting to enable monitoring on the Rancher cluster itself with non-persistent storage.

**Comment by liquid-cloud** [comment]
Have you tried upgrading the `monitoring-operator` first before updating monitoring to version 0.5?
