### ISSUE TITLE
External TLS on single node install (with AWS load balancer and ACM certs)

### ISSUE THREAD

**Issue by larsderidder** [rancher/rancher#23887]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
- Install Rancher as single node following instructions
- Configure node to open port 80 and 443 for ingress
- Request certificate through ACM
- Configure L7 load balancer (AWS ALB) to use certificate and to redirect to the node
- Attempt to do requests through the CLI through `rancher kubectl <something>`

**Result:**
Errors:
Unable to connect to the server: x509: certificate signed by unknown authority

To work around, I can provide `--insecure-skip-tls-verify=true`, but it's cumbersome.

**Other details that may be helpful:**
The interface (and everything else that I can see) works fine.

I saw that the HA install allows for configuring --set tls=external. My question is if there's an equivalent for single node install? I couldn't find it.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.2
- Installation option (single install/HA): single install

**Comment by superseb** [comment]
The instructions to run Rancher single node install with an external load balancer are described at https://rancher.com/docs/rancher/v2.x/en/installation/single-node/single-node-install-external-lb/. Please supply what kind of certificate you are using and what exact command to run Rancher.

**Comment by larsderidder** [comment]
The certificate is provided by Amazon's certificate service, which does not allow exporting the keys. So basically I have no certificate for Rancher as it's not really relevant.

I found here: https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#external-tls-termination, that Rancher HA could be configured to work with such a config. But single node indeed only gives options given that you provide the certificate.

**Comment by superseb** [comment]
The docs say that if you use a certificate signed by a recognized CA, you have to start the container like this:

```
docker run -d --restart=unless-stopped \
-p 80:80 -p 443:443 \
rancher/rancher:latest --no-cacerts
```

Please supply what command you used to run the container.

**Comment by larsderidder** [comment]
I executed this:

```
docker run -d \
    --name=rancher \
    --restart=unless-stopped \
    -p 80:80 \
    -p 443:443 \
    rancher/rancher:stable
```

So I did not add the --no-cacerts. Would restarting with the new option be OK?

Also, the docs state `The certificate files must be in PEM format.`. I don't see them being used anywhere however. Any idea why that is?

**Comment by superseb** [comment]
Not sure if you see that in FAQ and troubleshooting, but there are more sections on that page regarding the use of an external load balancer. If you relaunch, you need to provide the flag to reuse the volume if you want to keep your state. Then generate a kubeconfig that will not contain the cacert so the connection will be valid.
