### ISSUE TITLE
[forwardport] Re-label 'Custom Metrics' tab to 'Custom Metrics Endpoints' in Workload view

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23892]
Forwardport of rancher/rancher#23737

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 9930781c8`

- enable the project monitoring
- deploy/edit a workload
- see the section Custom Metrics Endpoints under the advanced options
![Screen Shot 2019-11-14 at 11 42 25 AM](https://user-images.githubusercontent.com/57409052/68886162-d931b100-06d3-11ea-91fd-f73e366fb3fe.png)
