### ISSUE TITLE
Migrate rke launched cluster to rancher launched

### ISSUE THREAD

**Issue by ColonelBundy** [rancher/rancher#23894]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Question**
I currently have a relatively big rancher cluster that was launched using RKE, however, since a lot of people are using this cluster and we'd like to administrate the cluster using the ui instead of config files. A rancher launched cluster has the option in the to update/take snapshots and much more straight from the ui which we also would like. Setting up rke on everyone's pc who wishes to administrate the cluster is time-consuming and the person needs prior knowledge of rke to use it, and we'd like to avoid that if we can. Would it be possible to convert a rke launched cluster to the "rancher launched" version instead?

**Comment by superseb** [comment]
Not at this time, this is covered in https://github.com/rancher/rancher/issues/22763
