### ISSUE TITLE
Add state transition for cluster when nodes are upgrading 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#23898]
Introduce logic for upgrade strategy and state transitions so that this information is easily available to be displayed in UI. 

https://github.com/rancher/rancher/issues/23777

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id:`926997017`**

- Update on cluster.yml
```
kubelet:
      extra_args: 
        max-pods: 2
```
- Cluster goes into `Updating` state
<img width="1442" alt="Screen Shot 2020-03-09 at 11 18 51 AM" src="https://user-images.githubusercontent.com/26032343/76244863-1d533f00-61f8-11ea-9989-33a071bf6a93.png">

- When the worker nodes are upgrading, the status of the cluster is `Upgrading`
<img width="1432" alt="Screen Shot 2020-03-09 at 11 18 58 AM" src="https://user-images.githubusercontent.com/26032343/76244867-1f1d0280-61f8-11ea-920a-72ea24e53143.png">
