### ISSUE TITLE
Failed to provision volume with StorageClass "sc": Cloud provider not initialized properly

### ISSUE THREAD

**Issue by sreehsn771** [rancher/rancher#23899]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.1` UI: `v2.3.18` |
|Route|`authenticated.cluster.edit`|

**Comment by loganhz** [comment]
Could you file a new issue and supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md) , please? Thanks
