### ISSUE TITLE
Cannot edit buffer parameters when logging to Elasticsearch

### ISSUE THREAD

**Issue by ajchiarello** [rancher/rancher#23891]
**What kind of request is this (question/bug/enhancement/feature request):**
Question - How can I edit the buffering parameters when setting up cluster logging to ElasticSearch. Specifically, I am trying to set the flush_thread_count. I have tried adding a buffer block to the advanced logging configuration, which throws the following error: 

> unexpected configure element: expected 1 configure element buffer, but got 2

While the GUI allows you to change the flush_interval, is there any way to set the other buffering parameters?

**Steps to reproduce (least amount of steps as possible):**

In Rancher, go to cluster logging, choose ElasticSearch > Edit Ad File, and attempt to configure any buffering parameters.

**Result:**
Error about there being multiple buffer configure elements

**Other details that may be helpful:**

**Environment information**
Running Rancher 2.3.2 in an HA configuration.

**Comment by hrbu** [comment]
Any news here? Would like the override the buffer section too.
