### ISSUE TITLE
Introduce upgrade strategy for workers 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#23897]
Worker nodes also respect some kind of upgrade strategy such that not all of them are updated simultaneously. It would include maxUnavailable count, default to 1 for control plane/etcd nodes. 

https://github.com/rancher/rancher/issues/23777

**Comment by sowmyav27** [comment]
**On master-head - commit id: `926997017`**

- max_unavailable_worker: 10% is available by default on a cluster
- With default values upgrade_strategy, the sequence of how the upgrade happens in the cluster is given below
```
- etcd nodes - will upgrade one by one with the etcd components upgrading
- control plane nodes - will upgrade one by one - will be cordoned when this is happening. Control plane components - sidekick, kube-apiserver, kube-controller-manager, kube-scheduler and worker plane components - kubelet, kubeproxy
- etcd nodes will be cordoned - when the worker plane components - kubelet, kubeproxy are getting upgraded
- currently in rancher - worker plane nodes and add ons will get executed/upgraded in parallel.
- Default max_unavailable_worker: 10% so 1 worker node gets upgraded at a time. 
```
- If Drain is enabled, the nodes are drained.
- Else they go into cordoned state. and then Upgrade and to Active.
- State transition wrt to worker nodes from UI
- When Drain : false
```
-  Active --> Cordoned (Upgrading message) --> Active
```
- When Drain: True
```
-  Active --> Cordoned (Upgrading message) (might not be visible as it might happen really fast --> Draining --> Drained (Upgrading message) --> Active
```
