### ISSUE TITLE
EKS not supported on sa-east-1

### ISSUE THREAD

**Issue by nvivo** [rancher/rancher#23895]
[EKS is now supported on South America](https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-eks-generally-available-in-sao-paulo-region/) (sa-east-1), but rancher does not support it.

I tried manually setting the region, but the provisioning failed saying Rancher does not support the region.

**Comment by jugleni** [comment]
https://docs.aws.amazon.com/pt_br/eks/latest/userguide/eks-optimized-ami.html

**Comment by superseb** [comment]
Same as https://github.com/rancher/rancher/issues/24400
