### ISSUE TITLE
[UI] console does not display UTF-8 characters properly

### ISSUE THREAD

**Issue by Mmdixon** [rancher/rancher#2389]
If I click on a container from the Rancher UI and "Execute Shell", the console does not display UTF-8 characters correctly.
I.e. `echo -e "\xec\x95\x88"` should show `안`
But instead shows something like `ì` (Usually without the black diamond UTF-8 replacement characters)

Note: I am able to see UTF-8 characters properly on the host machine, and within an `exec` bash session of that same container. So the problem seems to be with the webview.

Version:
```
Rancher	v0.41.0
Cattle	v0.100.0
User Interface	v0.55.0
```

Thanks

**Comment by vincent99** [comment]
I think maybe https://github.com/chjj/term.js/pull/97 will fix this

**Comment by tfiduccia** [comment]
Version - master 8/5
New version of the shell has enabled this.
Verified fixed
