### ISSUE TITLE
[CIS] Ability to specify skip tests

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#23905]
As a user, I should be able to specify certain tests (Level 1) to be skipped

**Comment by sowmyav27** [comment]
@leodotcloud As discussed, reopening this issue, as there would be changes in this area.

**Comment by leodotcloud** [comment]
The new skip value is no more an array of string. Here is a sample: {"skip": { "rke-cis-1.4": [ "1.1.1", "1.2.2"] }}

**Comment by sowmyav27** [comment]
Reopening this issue.

Skip value in the API is to be given as `{"skip": { "rke-cis-1.4": [ "1.1.1", "1.2.2"] }}` 

But ideally it should just include `{ "rke-cis-1.4": [ "1.1.1", "1.2.2"] }` and not the `skip` again in its value

**Comment by codyrancher** [comment]
@sowmyav27 I think that we should retain skip. This is used inside a generic config file so we should give appropriate names. Doing so makes the config easier to read and more extensible in the future.

Maybe we need to change the order so skip is nested inside the version but I don't think it should be omitted.

**Comment by sowmyav27** [comment]
On master-head, currently this is how skip works from the API

1. runSecurityScan with no value passed in `skip`, the default skip values from the config.json (in the UI) are applied.
2. runSecurityScan with blank string `""` value passed in `skip`, the skip values from the config.json are ignored, and no tests are skipped.
3. runSecurityScan with skip values like `{"skip": { "rke-cis-1.4": [ "1.1.1", "1.2.2"] }}` value passed in `skip`, the tests mentioned are skipped.

@leodotcloud Question about the first scenario.

Should there be an API call to list of default skip values from the config.json or should the API rely on the config.json (from the UI)

**Comment by sowmyav27** [comment]
**Verified on master head - commit id: `48a2c4ffc`** 

currently this is how skip works from the API

runSecurityScan with overrideSkip is an array of strings

- overrideSkip - [] - overrides the skips configured in the config.json
- overrideSkip - [""] - overrides the skips configured in the config.json
- overrideSkip - ["1.1.2"] - overrides the skips configured in the config.json and skips only "1.1.2" test
