### ISSUE TITLE
[CIS] Modify the report format for new requirements

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#23904]
- Modify the summarizing logic to record all results, including pass, skipped, not just failures
- Change the results structure to include, fail, pass and skip section - 1

**Comment by sowmyav27** [comment]
Verified on `master-head` latest.

- Report on the API summarizes the results. 
- It gives the total checks, passed/failed/mixed state.
- The details of different tests, with the status is also available in the result.
- The details on which node the test has to be run is available.
- The details about which nodes the test has failed in case the state of the test is "mixed" is available on the report

.
