### ISSUE TITLE
Existing vSphere node template can't be used after upgrading to 2.3.3

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23919]
rancher/rancher:v2.3-head 75c231e51
UI: `latest-2.3`

* Deploy Rancher v2.3.2
* Create a vSphere node template using RancherOS
* Create a cluster from the node template
* Upgrade Rancher to v2.3-head
* Create a new cluster from the existing vSphere node template

Cluster provisioning fails with an error: `	Error setting machine configuration from flags provided: Creation type manual not supported; Timeout waiting for ssh key`

**Comment by bmdepesa** [comment]
After upgrading, creationType is set to `manual` which was not present in 2.3.2.
```2019/11/05 23:12:26 [INFO] successfully migrated node template [vsphere-232]```

Editing to `legacy` allows the cluster to be provisioned.

**Comment by luthermonson** [comment]
https://github.com/rancher/machine/pull/47

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
UI: `latest-2.3`

* Create vSphere node template in 2.3.2
* Create cluster from node template
* Upgrade to v2.3-head
* Create cluster from existing node template
* vSphere node template contains `creationType=legacy`

Cluster creation succeeds.

#23920 Still occurs
