### ISSUE TITLE
[forwardport] hostPort defined on workload via YAML lost after editing workload via the UI

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#23915]
Forwardport https://github.com/rancher/rancher/issues/23375

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 5ccf85b5a`

Create a new deployment with the hostport from the UI. On Edit view, able to see the host port displayed correctly.
On editing(with/without any changes) and saving , does not result in host port loss.
![Screen Shot 2019-11-19 at 10 10 26 AM](https://user-images.githubusercontent.com/57409052/69175036-41abd400-0ac0-11ea-814d-7173803259b2.png)

Create a new deployment with the hostport from kubectl. On Edit view from UI, able to see the host port displayed correctly.
```> kubectl run porttest --image=nginx --port=80 --hostport=8080
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/porttest created```
![Screen Shot 2019-11-19 at 11 34 23 AM](https://user-images.githubusercontent.com/57409052/69175231-9b140300-0ac0-11ea-8be4-6835495345b2.png)
On editing(with/without any changes) and saving , does not result in host port loss.
Further edits done on this deployment also does not result in host port loss.
