### ISSUE TITLE
v0.42.0-rc3 "Failed to clone catalog from github" air-gapped network.

### ISSUE THREAD

**Issue by clemenko** [rancher/rancher#2391]
We are trying to run Rancher on a air-gapped network. So no github. Is there a way to disable this function? Is there a way to create my catalogs?

**Comment by deniseschannon** [comment]
Currently, we'll only be supporting Catalog in a public repository. Note: catalog is not going to come out until the next release or two, so you got a sneak peek using the RC candidate. The link is not shown in the official v0.42.0. :)

**Comment by vincent99** [comment]
I'm not sure if anyone has really tested this yet, but you should be able to change `/v1/settings/catalog.url`to any internal URL that `git clone $url` can pull to use your own catalog repo.  There's no documentation on making your own entries yet (and the file layout will probably change a bit before public release) but you can basically copy https://github.com/rancher/rancher-catalog.

**Comment by kaos** [comment]
I've tested it now, and it works! :+1:
