### ISSUE TITLE
[Forwardport] Typo in dropdown when choosing the node template 

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23924]
Forwardport of rancher/rancher#23922

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version abd6f58c6`

Create a node template.
While creating a cluster, when choosing a node template, `templates` is spelt correctly.
![Screen Shot 2019-11-13 at 4 52 39 PM](https://user-images.githubusercontent.com/57409052/68814552-5d355b80-0636-11ea-83cb-cd4e22896789.png)
