### ISSUE TITLE
cluster-roletemplate-sync runs excessively 

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#23923]
This controller runs excessively and appears to be a good candidate to stop it from being a lifecycle and move it over to an owner reference relationship. 

`pkg/controllers/user/rbac/roletemplate_handler.go`

![Screen Shot 2019-11-05 at 4 45 51 PM](https://user-images.githubusercontent.com/13897607/68255901-c17b6e00-ffeb-11e9-947e-c9a969d0e8e3.png)

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 2/11

These issues re: scalability are hard to reproduce without testing at scale, so focused on regressions via automation: 

* Deployed Rancher
* Deployed multiple custom clusters
* Ran automation smoke tests and long running tests for a total of ~400 tests
* Automation runs succeeded with only a few known failures
