### ISSUE TITLE
Typo in dropdown when choosing the node template

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#23922]
Version: v2.3-head

Steps:
1. Create node template (Ex: DO)
2. Click on add cluster and choose any RKE cluster (Ex: DO). When choosing the node template, there is a type for "My Templates". Its displayed as "My Teplates" :
<img width="273" alt="Screen Shot 2019-11-05 at 3 27 59 PM" src="https://user-images.githubusercontent.com/18536626/68255237-8ffda500-ffe1-11e9-9d46-92a6766afd8b.png">

This issue is in master-head also.

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sangeethah** [comment]
Issues is fixed in latest UI tag  - `https://releases.rancher.com/ui/latest-2.3/index.html`.
<img width="485" alt="Screen Shot 2019-11-07 at 1 46 38 PM" src="https://user-images.githubusercontent.com/4266958/68430693-5fdf0f00-0165-11ea-98a9-887a24a4ae18.png">
