### ISSUE TITLE
[forwardport] FATA: Only support with English System Locale

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23926]
forwardport https://github.com/rancher/rancher/issues/23078

**Comment by sowmyav27** [comment]
Verified on rancher:master-head - commit id: `2a08c3a9f`

Steps:

- Create a custom cluster
- 1 linux node - all roles
- 1 windows node - AMI: 2019 Windows Server (2019 Server) with Chinese (Simplified) Language
- Run the agent command on the windows node.
- No error is seen on running the command on windows node.
- The windows node registers successfully.
- Deployed workloads and ingress successfully
