### ISSUE TITLE
Forwardport: Custom search filter for openldap and freeipa

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#23929]
Forwardport https://github.com/rancher/rancher/issues/18630

**Comment by soumyalj** [comment]
Tested with master-head build (b19342add855)
Enabled OPEN LDAP auth: "Search Filter" field option is presented for User and Groups in "Customize Schema" section.
Users have the option to set these fields when OpenLdap auth is enabled. When the field is set , this filter gets applied to the list of users/groups that get searched when adding users to add members to cluster/projects.
The following tests were done:
User Search Filter
(memberOf=cn=abcd,ou=groups,dc=us-west,dc=xxx,dc=xxx) - It returned the users testuser1,testuser2,testuser3 as expected
