### ISSUE TITLE
Editing an existing vSphere node template does not populate correct values after upgrading to v2.3.3

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#23920]
rancher/rancher:v2.3-head 75c231e51
UI: `latest-2.3`

* Deploy Rancher v2.3.2
* Create a vSphere node template using RancherOS
* Create a cluster from the node template
* Upgrade Rancher to v2.3-head
* Edit the existing node template

Many fields are not populated correctly:
* Resource pool
* Data store
* Creation method

Cluster creation also fails with the existing node template, tracked in rancher/rancher#23919

![Screen Shot 2019-11-05 at 3.28.21 PM.png](https://zube.io/files/rancher/d4faa0adf06d63d79a524eb23e530616-screen-shot-2019-11-05-at-3-28-21-pm.png)

**Comment by codyrancher** [comment]
I suspect this may be entirely resolved by the change rancher/rancher#23919 so I'm going to hold off working on this.

**Comment by bmdepesa** [comment]
This was not resolved by #23919

The existing node template can now be used to create another cluster post-upgrade, but editing the node template still does not contain the correct values when viewed in UI.

**Comment by codyrancher** [comment]
So I blew away everything and started fresh. After performing the upgrade I was able to see the correct values for data center, resource pool, data store and folder I however did not see the correct value for creation method. If you saw the wrong values for data center, resource pool data-store or folder would you mind demoing for me later today? I suspect it could be that the data you entered wasn't an exact match but vsphere accepted it anyway.

After an upgrade the node template didn't return creationType. Also as I mentioned above I'm concerned that there may need to be data-normalization. For example if the user entered in "/RNCH-HE-FMT/" for datacenter in v2.3.2 but you return "/RNCH-HE-FMT" as an option and "/RNCH-HE-FMT/" as a value  in 2.3.3 the front end won't match it.

**Comment by codyrancher** [comment]
Since this issue occurs because the user can enter in values that aren't valid options in 2.3 we decided that we're going to provide a small message which informs the user that it's an invalid option and ask them to change it.

@luthermonson also made a backend change to reduce the likelihood of this message from showing rancher/rancher#23972

The messaging looks like:
![Screen Shot 2019-11-07 at 4 20 55 PM](https://user-images.githubusercontent.com/55104481/68438066-35e71600-0180-11ea-99ec-907528cfbf43.png)

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 160e3b691
UI: `latest-2.3`

* Created vSphere node template in 2.3.2 w/ RancherOS
* Created cluster
* Upgraded Rancher to v2.3-head
* Edit previously created node template and all values load correctly
* Created a new cluster from the existing node template
