### ISSUE TITLE
Translation errors when choosing the target projects for multicluster apps

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#23925]
Version: v2.3-head 
UI Index: https://releases.rancher.com/ui/latest-2.3/index.html

Steps:
1. Create 2 DO clusters
2. At the global level , click on Apps . Launch a catalog and choose the "Target Projects"  from the dropdown
The translation is lost for the "Target Projects"
<img width="539" alt="Screen Shot 2019-11-05 at 3 40 03 PM" src="https://user-images.githubusercontent.com/18536626/68256481-18ca1000-ffe5-11e9-8b57-738f6fd56bad.png">

<img width="600" alt="Screen Shot 2019-11-05 at 3 59 23 PM" src="https://user-images.githubusercontent.com/18536626/68256535-4b740880-ffe5-11e9-87e7-66e5f93b4390.png">

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sangeethah** [comment]
This issue is not seen when testing with latest `v2.3-head`  and UI Index: https://releases.rancher.com/ui/latest-2.3/index.html

<img width="821" alt="Screen Shot 2019-11-07 at 2 16 48 PM" src="https://user-images.githubusercontent.com/4266958/68432420-42ac3f80-0169-11ea-82a0-08f12c7c851d.png">
