### ISSUE TITLE
Document the need for the shortname in /etc/hosts on 1.6 nodes.

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#23948]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Details:**

Customers have been hitting issues where if the nodes short name (nodename from nodename.example.com) isn't in the /etc/hosts file, the kubelet will not properly start with the following errors:

```
I1029 20:57:42.098088   48431 rancher.go:702] InstanceID [nodename.example.com]
E1029 20:57:42.114286   48431 kubelet.go:2236] node "nodename.example.com" not found
F1029 20:57:42.132778   48431 kubelet.go:1354] Kubelet failed to get node info: failed to get instance ID from cloud provider: instance not found
```

Since this has always happened with 1.6, it should be in the node requirements docs for 1.6 nodes.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/docs/issues/2148
