### ISSUE TITLE
rancher2.3 应用商店添加失败

### ISSUE THREAD

**Issue by fangfuhaomin** [rancher/rancher#23941]
*Describe your issue here*

  | Timeout in HTTP GET to [http://182.20.10.204:8888/root/rancher-catalog.git/index.yaml], did not respond in 30s
-- | --

错误提示，在rancher机器上git可以获取项目

项目结构,是不是有问题，有没有相关的完整文档能查看下，谢谢

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.2` UI: `v2.3.22` |
|Route|`global-admin.clusters.index`|

**Comment by Okabe-Kurisu** [comment]
不用写.git

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
Or you can find WeChat group via `rancher2` in WeChat

**Comment by fangfuhaomin** [comment]
thank you
我是先安k8s，然后另外在其他服务器上安装rancher，通过ui导入k8s集群，之后在k8s server上安装helm，目前不知道是什么原因导致出现问题
