### ISSUE TITLE
[Forwardport] Translation errors when choosing the target projects for multicluster apps

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23946]
Forwardport rancher/rancher#23925

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version abd6f58c6`

Create DO clusters
At global level, click Apps. Launch a catalog and choose the `Target Projects` from the dropdown. Translation shows as intended.
![Screen Shot 2019-11-13 at 4 45 43 PM](https://user-images.githubusercontent.com/57409052/68814191-670a8f00-0635-11ea-854c-8853cfc2b2e9.png)
