### ISSUE TITLE
worker node goes to unavailable and never back active 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#23953]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

- run Rancher:master-head 22801ee single install
- add a cluster with the cloud provider enabled (AWS) and using k8s `v1.16.2`
- and a second cluster  with the cloud provider enabled (AWS) and using k8s `v1.15.5`
- the nodes run Ubuntu `16.04.4 LTS`, docker `19.3.4`
- switch the catalog library branch to `partners`
- deploy the app `artifactory-ha` which template version `v1.0.0`

**Result:**
For both clusters:
- the cluster is provisioned successfully and be active 
- I notice some pods from the app are in `unknown` state
- then check the Node page, notice that one worker node goes to `Unavailable` and UI shows `Kubelet stopped posting node status.`
- the node is running in AWS console
- download the keys for this node from Rancher UI, 
- try to ssh to the node from the terminal, there is no error message returned, but the window is stuck in the connecting state.

This may be related to https://github.com/rancher/rancher/issues/22849

**Comment by superseb** [comment]
Tried to reproduce on `master-head` (https://github.com/rancher/rancher/commit/bce4539c6)

Created the following clusters:

- Custom - Cloud provider AWS - 1.15 - 1 etcd, 1 controlplane, 1 worker
- Custom - Cloud provider AWS - 1.16 - 1 etcd, 1 controlplane, 1 worker
- Node driver/template - Cloud provider AWS - 1.15 - 1 etcd, 1 controlplane, 1 worker
- Node driver/template - Cloud provider AWS - 1.16 - 1 etcd, 1 controlplane, 1 worker

All nodes in each cluster are active and responsive, and can be logged into using the SSH key from the UI.

This sounds like a resource issue on the node(s).

**Comment by jiaqiluo** [comment]
it turns out this failure is caused by insufficient memory resources in the worker node.

The deployment `artifactory-ha-artifactory-ha-member` requires 4 GB free memory to initialize, but the worker node (t2.medium) does not have that much free memory. It eventually causes the workload and the worker being `unavailable`  

This problem does not happen in a cluster with workers having more memory.
