### ISSUE TITLE
Rancher compose Environment Interpolation not working

### ISSUE THREAD

**Issue by summerQLin** [rancher/rancher#2395]
Hi,

I am trying to use environment variables in docker-compose.yml, just fount it doesn't work at all.

This is part of setting for loadbalancer container lable, `env | grep URL1` or `env | grep URL2` has values set. But after `rancher-compose up`, from rancher UI docker-compose.yml, I saw the variables are not replaced, it's like `io.rancher.loadbalancer.target.service1: ${URL1}:443=5000`
```
labels:
  io.rancher.loadbalancer.target.service1: "${URL1}:443=5000"
  io.rancher.loadbalancer.target.service2:"${URL2}:8443=5001"
```
It also fails with container environment setting:
```
environments:
  MYENV: "${URL1}:443"
```
Rancher	v0.37.1
Cattle	v0.91.1
User Interface	v0.47.0
Rancher Compose	beta/latest
rancher-compose version v0.4.0

Thanks.

**Comment by Rucknar** [comment]
I'm currently using them without issue in my config, for example:
`image: registry.mydomain.com:5000/web:$APPS_VERSION` 

I suspect the issue is with the interpolation replacing values within a quoted string. 
It should work fine without the quotes, we don't use any in our code.

**Comment by Rucknar** [comment]
Also, interpolation was only added in v0.41.0 of rancher. Make sure you update rancher compose, i always download it through the GUI for the version of rancher i'm using.

**Comment by summerQLin** [comment]
I downloaded from GUI too, but my rancher version might be too old, Rancher v0.37.1, so prividing rancher-compose version is v0.4.0?

**Comment by Rucknar** [comment]
I suspect your version is too old. I'm on v0.4.3 now. Well worth upgrading.

**Comment by deniseschannon** [comment]
Yes, environment interpolation didn't come out until v0.4.1.

Also, you don't need the quotes for the labels. I don't think it would work if you had the quotes. 

http://docs.rancher.com/rancher/rancher-compose/rancher-services/#load-balancer-example-l7
