### ISSUE TITLE
 cannot add work machine join into cluster

### ISSUE THREAD

**Issue by catterlai** [rancher/rancher#23956]
*Describe your issue here*
i have 3 machine (etcd controll work).now i need to add a work to the cluster,and copy the ssh cmd,and run it in the work machine.but the rancher cluster have not any response.so why ?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.2` UI: `v2.3.22` |
|Route|`authenticated.cluster.edit`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
