### ISSUE TITLE
Network Provider is changeable on cluster edit

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#23950]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create custom cluster
Edit cluster

**Result:**
See `Network Provider` being changeable, while it is not in v2.2.9

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.2
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sangeethah** [comment]
Tested with latest build from `v2.3-head` with UI tag - `https://releases.rancher.com/ui/latest-2.3/index.html`.
We do not allow for Network Provider to be changed on edit cluster as expected.
