### ISSUE TITLE
Unable to run with built-in CI/CD

### ISSUE THREAD

**Issue by 839838703** [rancher/rancher#23959]
2019/11/07 07:38:53 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/07 07:38:53 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/07 07:38:53 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/07 07:38:53 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019-11-07 07:41:06.952852 I | mvcc: store.index: compact 144410
2019-11-07 07:41:06.959719 I | mvcc: finished scheduled compaction at 144410 (took 3.707576ms)
2019-11-07 07:46:06.967748 I | mvcc: store.index: compact 145039
2019-11-07 07:46:06.973805 I | mvcc: finished scheduled compaction at 145039 (took 4.964838ms)
2019-11-07 07:51:06.978040 I | mvcc: store.index: compact 145668
2019-11-07 07:51:06.980275 I | mvcc: finished scheduled compaction at 145668 (took 935.533µs)
2019/11/07 07:52:30 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/07 07:52:30 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/07 07:52:46 [ERROR] PipelineExecutionController p-8wtz2/p-l44tk-1 [pipeline-execution-controller] failed with : Get http://10.43.24.223:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): dial tcp 10.43.24.223:8080: connect: connection refused
2019/11/07 07:52:48 [ERROR] PipelineExecutionController p-8wtz2/p-ps7p7-2 [pipeline-execution-controller] failed with : Get http://10.43.24.223:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): dial tcp 10.43.24.223:8080: connect: connection refused
2019/11/07 07:54:56 [ERROR] PipelineController p-8wtz2/p-xhx5x [pipeline-controller] failed with :  422: {"error":"Invalid url given"}
2019-11-07 07:56:06.983614 I | mvcc: store.index: compact 146298
2019-11-07 07:56:06.985908 I | mvcc: finished scheduled compaction at 146298 (took 957.389µs)
2019/11/07 07:58:57 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/07 07:58:57 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/07 07:58:57 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)

**Comment by 839838703** [comment]
Currently, the pipeline startup report the above error, the interface has been please wait

**Comment by loganhz** [comment]
Can you check the log in cluster agent and node agent?
