### ISSUE TITLE
Rancher create then delete service automatically during create Ingress

### ISSUE THREAD

**Issue by KeynesLee** [rancher/rancher#23960]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Global-->Settings-->ingress-ip-domain
 Custom ingress-ip-domain instead of xip.io , like **test-2.demo.com**

2. Workload
Create a simple workload nginx , with image **nginx**

3. Load Balancing
Add an ingress  with **Automatically generate a .test-2.demo.com hostname**

4. Watch in "Service Discovery"
You can see a service "ingress-xxxxxx" created but then disappeared soon

5.  Found kube-proxy logs as below
{"log":"I1107 08:59:04.518888   13413 service.go:332] Adding new service port \"default/ingress-ff53204a63e729b2b8734de61d74c257:\" at 10.43.52.34:80/TCP\n","stream":"stderr","time":"2019-11-07T08:59:04.519102432Z"}
{"log":"I1107 09:00:02.354143   13413 service.go:357] Removing service port \"default/ingress-ff53204a63e729b2b8734de61d74c257:\"\n","stream":"stderr","time":"2019-11-07T09:00:02.354269378Z"}

**Result:**
As service disappeared, the ingress will never work

**Other details that may be helpful:**
If I create the same ingress with **Specify a hostname to use**, this issue won't happen.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

Rancher | v2.3.2
User Interface | v2.3.22
Helm | v2.14.3-rancher1
Machine | v0.15.0-rancher12-1

- Installation option (single install/HA): HA

**Cluster information**
- Cluster type : Deployed by RKE , HA installation , 3 Controller nodes, 3 Worker nodes.
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
   Machine type : Metal 
   CPU : 2P12C 
   Memory : 
   - Master Node : 32 GB
   - Worker Node : 192GB 
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:51:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:22:32 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by KeynesLee** [comment]
We found this issue was caused by missing WorkloadID.
Just the same with the issue #16052

**Comment by KeynesLee** [comment]
We found this issue is the same with 
#16052

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24018
