### ISSUE TITLE
Upgrade single container within a service?

### ISSUE THREAD

**Issue by alejom99** [rancher/rancher#2396]
If you had a service with two containers A and B. A mounts a volume from B (or B is a sidekick of A). How do I upgrade A without affecting the data in the volume exposed by B?

**Comment by deniseschannon** [comment]
With the upcoming feature of in=service upgrade, you will be able to do your exact scenario.

Upgrade service A without affecting service B. 

https://github.com/rancher/rancher/issues/1874
