### ISSUE TITLE
pipeline issue

### ISSUE THREAD

**Issue by 839838703** [rancher/rancher#23961]
2019/11/07 08:59:07 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/07 08:59:07 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/07 08:59:30 [ERROR] PipelineExecutionController p-8wtz2/p-l44tk-1 [pipeline-execution-controller] failed with : Get http://10.43.24.223:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): dial tcp 10.43.24.223:8080: connect: connection refused
2019/11/07 08:59:32 [ERROR] PipelineExecutionController p-8wtz2/p-ps7p7-2 [pipeline-execution-controller] failed with : Get http://10.43.24.223:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): dial tcp 10.43.24.223:8080: connect: connection refused
2019-11-07 09:01:07.073963 I | mvcc: store.index: compact 154489
2019-11-07 09:01:07.077004 I | mvcc: finished scheduled compaction at 154489 (took 1.305233ms)
2019/11/07 09:01:36 [ERROR] PipelineController p-8wtz2/p-xhx5x [pipeline-controller] failed with :  422: {"error":"Invalid url given"}
2019/11/07 09:02:38 [ERROR] PipelineExecutionController p-8wtz2/p-xhx5x-1 [pipeline-execution-controller] failed with : Get http://10.43.24.223:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb): dial tcp 10.43.24.223:8080: connect: connection refused
2019-11-07 09:06:07.080131 I | mvcc: store.index: compact 155120
2019-11-07 09:06:07.083563 I | mvcc: finished scheduled compaction at 155120 (took 1.568956ms)
2019/11/07 09:08:25 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/07 09:08:25 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/07 09:08:25 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/07 09:08:25 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)

**Comment by DeepLJH0001** [comment]
disable project network isolation . Because the cluster-agent in the system project，and pipeline was in other project.

**Comment by DeepLJH0001** [comment]
集群升级那边，把项目隔离关掉
