### ISSUE TITLE
[forwardport] vSphere Legacy Normalizer

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#23978]
https://github.com/rancher/rancher/issues/23972

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/23976

**Comment by aaronRancher** [comment]
Tested in `rancher\rancher:master-head` `version 781cd0fdc`.
UI: `latest2`

Created vSphere node template in `v2.3.3-rc4` w/ RancherOS
Created cluster
Upgraded Rancher to master-head
Edit previously created node template and all values load correctly
