### ISSUE TITLE
Node count not reflected on cluster list view , until refreshed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#23973]
Rancher server version - `v2.3-latest`

Steps to reproduce the problem:
Create a DO cluster.
When user is brought back to the cluster list view , node count is 0.
Wait for the node provisioning to succeed and cluster get to active state.
Notice that the node count continues to be reported as 0 .
Also trying to access "Default" project from Global->Cluster-> shows that the cluster have no project.

<img width="1083" alt="Screen Shot 2019-11-07 at 1 51 34 PM" src="https://user-images.githubusercontent.com/4266958/68430908-e136a180-0165-11ea-8bbc-3bec4982905c.png">

**Comment by westlywright** [comment]
I do not believe this is a UI issue as the code that controls this hasn't changed in months. I've tested this with two different rancher server versions, `v2.3.2` and `v2.3-head`, and the `2.3-fixes` UI branch (essentially head branch for 2.3 development). When I point my local ui running `2.3-fixes` to my live rancher server tagged with `v2.3.2` the node count updates as expected. When I point my local ui running `2.3-fixes` to my live rancher server tagged with `v2.3-head` the node counts do not update. I can see node events firing but I don't see as many on `v2.3-head` server so I think we may have some sort of regression in the node events sent over the subscribe websocket.

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sangeethah** [comment]
Rancher server version - v2.3-latest

Steps to reproduce the problem:
Create a DO cluster.
When user is brought back to the cluster list view , node count is 1  as expected.
Once the cluster gets to "Active" state , Global->Cluster-> shows that the cluster has "System" and "Default" project as expected.
