### ISSUE TITLE
Container in RECONNECTING state after one day of working

### ISSUE THREAD

**Issue by baio** [rancher/rancher#2397]
Hi 
I added my azure vm to rancher via add custom host. It is added and working correctly one day and then on next day it  displays always RECONNECTING status, only way to reactivate it  is to recreate docker/agent container (add again as a custom host), it was happen already twice.

Same time host machine with both rancher/server and rancher/agent always work correctly.

**Comment by deniseschannon** [comment]
This might be duplicate of https://github.com/rancher/rancher/issues/2196#issuecomment-149975548.

It seems there might be an issue with Azure. @cusspvz mentioned that there were some networking issues on Azure and was going to do some tests among a mix of cloud providers to see if it's an Azure issue.

**Comment by cusspvz** [comment]
Hello @baio ,

You might wanna check my [comment](https://github.com/rancher/rancher/issues/2196#issuecomment-150659003) regarding how I solved this.

Hope it helps.

**Comment by baio** [comment]
Hi @cusspvz  , I've tried your container and at first it was looking like this helped but after 3 days, same problem, on mine 2 other azure VM's same problem again. Looks like rancher yet is very unstable on azure

**Comment by cusspvz** [comment]
@baio it isn't happening only with Azure, @cloudnautique is also experiencing with GCE and I've already replicated on AWS. Apart from this issue, Rancher seems stable enough for production.

If you're interested on seeing this solved, I suggest you to subscribe and follow up issue #2196.

**Comment by cusspvz** [comment]
As this seems to be a duplicated, you can also close it. :)

**Comment by baio** [comment]
sure, thanks for help
