### ISSUE TITLE
Monitoring - Monitor kubelet without turning on monitoring in rancher/my own prometheus operator

### ISSUE THREAD

**Issue by Devin-Holland** [rancher/rancher#23970]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.3

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Hosted Azure 1.15.5

- Docker version (use `docker version`):
19.03.4

I am trying to use my own prometheus operator setup without using the monitoring option or the prometheus option in the catalog. The intent of this is to keep it kubernetes flavor indifferent (vanilla vs rancher vs aks etc.). 

On the cluster that is stood up there is a service called kubelet in the kube-system namespace that has port 10250. There is a corresponding Endpoints object with 15ips specified. When I create a service monitor that selects those endpoints, my prometheus job gives the error `dial tcp ip:10255: connect: connection refused`.

I ssh'd into the master node and checked for the kubelet docker container running and it does not have any ports exposed (which makes sense with the error).

So the question is: Is there a way to expose the metrics port for kubelet without turning on the monitoring option in rancher?

**Comment by davidcorbin** [comment]
It seems the easiest way would be to add something like NodePort or Ingress controller to the cluster and pointed at the kubelet monitoring port.

**Comment by Devin-Holland** [comment]
One of the problems with that is that I ssh'd into the server, looked at the kubelet docker container with `docker inspect` and there were no ports listed as being exposed when the monitoring option in rancher is turned off.

The other problem with that is that the point of what I'm trying to deliver is a monitoring platform that can be put on any rancher (or really any flavor) cluster and have it work out of the box. If I manually add a service and endpoints I need to know the IP of each node at the time of applying. Which means I need to edit code before I deploy to any server which I'm trying to avoid doing.

**Comment by rendhalver** [comment]
Kubelet doesn't run as a pod in Rancher. It's a container running with host networking.
If you run docker inspect kubelet you can see whether it's running with tls or now and set this flag accordingly.
```
kubelet:
  serviceMonitor:
    https: true
```
