### ISSUE TITLE
vSphere Legacy Template Normalizing

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#23972]
The old fields in vmwarevsphere templates were free form text fields and the finder methods in govmomi allowed for something like "My Network" to be a lookup when the real object path was "/CLUSTER_NAME/networks/My Network". We need a shim during the upgrade process which looks at a template and tries to upgrade the data to the full path we now use w/ the lookup api in 2.3.3+

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/23975

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 160e3b691
UI: `latest-2.3`

* Created vSphere node template in 2.3.2 w/ RancherOS
* Created cluster
* Upgraded Rancher to v2.3-head
* Edit previously created node template and all values load correctly
* For values that do not map correctly, a warning is displayed and does not impact other fields
