### ISSUE TITLE
Deploy/Edit Workload page - Drop down icon disappears when hovering over protocol and port type field.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#23987]
Rancher server version - `v2.3-head` - `add7bda8f` 
ui-index- https://releases.rancher.com/ui/latest-2.3/index.html

Steps to reproduce the problem:
Deploy/Edit Workload page - Drop down icon disappears when hovering over protocol and port type field.
On clicking the "Add Port" , the portMapping entry initially had the drop down icon for  protocol and port type field. But they disappear when hovering on these fields.

<img width="1112" alt="Screen Shot 2019-11-07 at 9 38 59 PM" src="https://user-images.githubusercontent.com/4266958/68452782-693d9b00-01a8-11ea-8787-a1b402eb53c5.png">

<img width="1124" alt="Screen Shot 2019-11-07 at 9 49 35 PM" src="https://user-images.githubusercontent.com/4266958/68452826-84100f80-01a8-11ea-94e1-26304c717d54.png">

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sangeethah** [comment]
Tested with UI tag - `latest-2.3`
Drop down icon dont disappears when hovering over protocol and port type field anymore.
But on selecting any entry from the drop down list , the drop down icon is lost.

<img width="1041" alt="Screen Shot 2019-11-11 at 11 47 34 AM" src="https://user-images.githubusercontent.com/4266958/68616177-5f05f000-0479-11ea-9bfd-780ff5e61836.png">
<img width="1048" alt="Screen Shot 2019-11-11 at 11 47 18 AM" src="https://user-images.githubusercontent.com/4266958/68616178-5f05f000-0479-11ea-88b8-d92f5da31c5e.png">

Reopening this issue .

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sangeethah** [comment]
Tested with latest build from `v2.3.-head` with ui-index- https://releases.rancher.com/ui/latest-2.3/index.html

Drop down icon dont disappears when hovering over protocol and port type field anymore.
They also dont disappear on selecting any entry from the drop down list .
