### ISSUE TITLE
[forwardport] Editing an existing vSphere node template does not populate correct values after upgrading to v2.3.3

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#23980]
Forwardport of rancher/rancher#23920

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested in `rancher\rancher:master-head` `version 781cd0fdc`.
UI: `latest2`

- Created vSphere node template in `v2.3.3-rc4` w/ RancherOS
- Created cluster
- Upgraded Rancher to master-head
- Edit previously created node template and all values load correctly
- For values that do not map correctly, a warning is displayed and does not impact other fields
