### ISSUE TITLE
Failed to communicate with API server

### ISSUE THREAD

**Issue by fmunteanu** [rancher/rancher#23995]
I recently upgraded to 2.3.2 from 2.2.9, I have 2 imported EKS clusters into a HA 3 nodes Rancher cluster, one in `us-east-1` and another identical one in `us-west-2`. This is the strange part:
I can import fine the `us-east-1` cluster, as soon as I import the `us-west-2` one, `us-east-1` cluster will throw this error:
```
Failed to communicate with API server: Get https://172.20.0.1:443/api/v1/namespaces/kube-system?timeout=30s: waiting for cluster agent to connect
```

If I delete the `us-east-1` cluster and import it again, this time the `us-west-2` cluster will throw the same error. I tried this several times, I'm trapped. Reverting back to 2.2.9 fixes the issue. I also started a fresh new Rancher HA install and imported the two EKS clusters, same outcome.

### Setup
- HA mode running on 3 minimal CentOS 7.7 EC2 instances with Selinux enabled
- Docker 1.13.1
- EKS cluster with 70 nodes, see details below

![Screen Shot 2019-11-08 at 10 37 44 AM](https://user-images.githubusercontent.com/19806136/68489540-4d241300-0215-11ea-8ae2-956e45b374f3.png)

**Comment by fmunteanu** [comment]
I tried something I never thought it could help, I deleted all my contexts and imported each EKS cluster with a clean `.kube/config` file, containing only one cluster configuration at the time.
```
$ kubectl config get-contexts
$ kubectl config delete-context arn:aws:eks:us-east-1:*:cluster/default-compute-us-east-1
$ kubectl config delete-context arn:aws:eks:us-west-2:*:cluster/default-compute-us-west-2
$ kubectl config get-contexts
CURRENT   NAME   CLUSTER   AUTHINFO   NAMESPACE
$ aws eks --region us-east-1 update-kubeconfig --name default-compute
$ kubectl apply -f https://rancher.domain.com/v3/import/qbxssnlkcqb5bbsdncbbgn1vshlzdpvs6c57h8wwlmpnh9plsrkg5l.yaml
clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver unchanged
clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master unchanged
namespace/cattle-system unchanged
serviceaccount/cattle unchanged
clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding created
secret/cattle-credentials-699f05d created
clusterrole.rbac.authorization.k8s.io/cattle-admin created
deployment.apps/cattle-cluster-agent configured
daemonset.apps/cattle-node-agent configured
```

So far, both clusters are not throwing any errors. I'll leave this ticket open, in case this is an intermittent issue.

**Comment by smetal1** [comment]
> I recently upgraded to 2.3.2 from 2.2.9, I have 2 imported EKS clusters into a HA 3 nodes Rancher cluster, one in `us-east-1` and another identical one in `us-west-2`. This is the strange part:
> I can import fine the `us-east-1` cluster, as soon as I import the `us-west-2` one, `us-east-1` cluster will throw this error:
> 
> ```
> Failed to communicate with API server: Get https://172.20.0.1:443/api/v1/namespaces/kube-system?timeout=30s: waiting for cluster agent to connect
> ```
> 
> If I delete the `us-east-1` cluster and import it again, this time the `us-west-2` cluster will throw the same error. I tried this several times, I'm trapped. Reverting back to 2.2.9 fixes the issue. I also started a fresh new Rancher HA install and imported the two EKS clusters, same outcome.
> 
> ### Setup
> * HA mode running on 3 minimal CentOS 7.7 EC2 instances with Selinux enabled
> * Docker 1.13.1
> * EKS cluster with 70 nodes, see details below
> 
> ![Screen Shot 2019-11-08 at 10 37 44 AM](https://user-images.githubusercontent.com/19806136/68489540-4d241300-0215-11ea-8ae2-956e45b374f3.png)

Even I am also facing the same issue when I am trying to access the API though : <my url>/v3 . Its giving auth error though my auth key is valid . I am running HA cluster with external nginx with ssl configured
