### ISSUE TITLE
Execute docker scripts as root

### ISSUE THREAD

**Issue by Martin-Hogge** [rancher/rancher#23992]
**What kind of request is this (question/bug/enhancement/feature request):**
QUESTION

**Steps to reproduce (least amount of steps as possible):**
Having 4 hosts: all Ubuntu 18.03 64bits.
1. Install RKE on one host;
2. Provide the 3 others hosts as kubernetes's nodes.
3. Add Rancher Server with Docker Image (https://rancher.com/quick-start/)
4. Import cluster: the one created previously with RKE;
5. Add GitLab Helm chart;
6. Deploy GitLab Helm chart;

**Result:**
Gitlab-runner pod is not deploying due to:
```
ERROR: Registering runner... failed runner=gdYcleh7 status=couldn't execute POST against https://gitlab.example.com/api/v4/runners: Post https://gitlab.example.com/api/v4/runners: dial tcp: lookup gitlab.example.com on 10.43.0.10:53: no such host
PANIC: Failed to register this runner. Perhaps you are having network problems
Registration attempt 29 of 30
Runtime platform arch=amd64 os=linux pid=443 revision=05161b14 version=12.4.1
WARNING: Running in user-mode.
WARNING: The user-mode requires you to manually start builds processing:
WARNING: $ gitlab-runner run
WARNING: Use sudo for system-mode:
WARNING: $ sudo gitlab-runner... 
```

Trying to Execute Shell and run `sudo gitlab-runner`:

> sudo: not found

**Environment information**
- Rancher version: v2.3.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported from RKE setup;
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by superseb** [comment]
The error displayed is coming from the gitlab-runner, we don't control what's in there. But the error above is a cluster related issue (`dial tcp: lookup gitlab.example.com on 10.43.0.10:53: no such host`), which you can troubleshoot by following https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/.

Please file a new issue if you still experience problems with using the cluster.
