### ISSUE TITLE
[Forwardport] Network Provider is changeable on cluster edit

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23999]
Forwardport rancher/rancher#23950

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version abd6f58c6`

Create custom cluster
Edit cluster
`Network Provider` is not changeable
![Screen Shot 2019-11-13 at 3 55 47 PM](https://user-images.githubusercontent.com/57409052/68811511-13487780-062e-11ea-81e4-3e28c342ea92.png)
