### ISSUE TITLE
Wrap lines doesn't actually wrap lines

### ISSUE THREAD

**Issue by TheLastProject** [rancher/rancher#23993]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Go to a pod in a workload
2. Click 3 dots menu
3. Click View Logs
4. Check Wrap Lines

**Result:**
The lines aren't actually wrapped, but a horizontal scrollbar is introduced.

**Other details that may be helpful:**
This may not happen with short lines. Java applications are great to trigger this with.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.1
- Installation option (single install/HA): Unknown

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version abd6f58c6`

View pod in workload
View logs
![Screen Shot 2019-11-13 at 4 30 17 PM](https://user-images.githubusercontent.com/57409052/68813488-30cc1000-0633-11ea-95f3-0c9cf2d873b5.png)

Check Wrap Lines
![Screen Shot 2019-11-13 at 4 30 27 PM](https://user-images.githubusercontent.com/57409052/68813492-33c70080-0633-11ea-97e2-bae6669f5a0f.png)
