### ISSUE TITLE
[Forwardport] Prevent Disabling of Cloud Provider Once Set

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#24008]
Forwardport rancher/rancher#22852

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version abd6f58c6`

Create a cluster with Amazon cloud provider.
Edit the cluster and the option to disable the cloud provider is not presented.
![Screen Shot 2019-11-13 at 3 02 08 PM](https://user-images.githubusercontent.com/57409052/68808382-db8a0180-0626-11ea-91fc-f92969ce193c.png)
