### ISSUE TITLE
[forwardport] vsphere ds clusters lookup api

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#24003]
https://github.com/rancher/rancher/issues/19706

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/24004

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 9f8763def`


![Screen Shot 2019-11-18 at 4 59 43 PM](https://user-images.githubusercontent.com/57409052/69104225-e2e54c80-0a24-11ea-980e-26333c4790ac.png)
Create a Vsphere template using datastore cluster option and `Creation method` set as `Clone an existing virtual machine` .

Able to create a vsphere cluster successfully using this template.
Machines created for the cluster use the selected datastore cluster (that was set in the template) . This check was done in Vsphere Client UI.
`
2019/11/18 21:00:25 [INFO] cluster [c-52nzs] provisioning: Finished building Kubernetes cluster successfully
`
