### ISSUE TITLE
[backport] weave password changes on cluster updates causing network outages

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#24000]
[backport] https://github.com/rancher/rancher/issues/23702

**Comment by sangeethah** [comment]
Tested with rancher server version - `v2.3.2`

Able to reproduce the issue:
1. Deploy a cluster with Network set to "Weave".
2. Once the cluster gets created successfully , notice that the `weave-net` workload under `kube-system`  using "Edit/View Yaml" option shows weave password being set -"name":"WEAVE_PASSWORD","value":"<value>"}
3. Edit cluster   and modify any aspect of the cluster (say `addon_job_timeout`) via edit as yaml.
4. As part cluster update , notice that `weave-net` workload  gets redeployed and  there is no weave password being set anymore.

Tested with latest build from `v2.3-head` - `5187fce31`
1. Deploy a cluster with Network set to "Weave".
2. Once the cluster gets created successfully , notice that the `weave-net` workload under `kube-system`  using "Edit/View Yaml" option shows weave password being set -"name":"WEAVE_PASSWORD","value":"<value>"}
3. Edit cluster   and modify any aspect of the cluster (say `addon_job_timeout`) via edit as yaml.
4. As part cluster update , notice that `weave-net` workload  does NOT get redeployed  anymore.`WEAVE_PASSWORD` continues to be set in the `weave-net` workload as expected.
