### ISSUE TITLE
Not able to access catalog when there is no service  created.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2400]
Server version - v0.43.0-rc1

I am not able to load apps/catalog/all , when there are no stacks .  I am redirected to stacks view.
when I have at least 1 stack created , I see the catalog page load up.

**Comment by vincent99** [comment]
The welcome page has a link for catalog now.  It will still redirect to the welcome if you directly go to the catalog path, but that's fine/don't do that.

**Comment by sangeethah** [comment]
Tested with Server version - v0.43.0-rc3

Able to access catalog, when there are no stacks.
