### ISSUE TITLE
vSphere datastore cluster UI

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#24002]
We need to add a dropdown and a toggle to enable selecting datastore clusters over datastores.

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sangeethah** [comment]
Tested with rancher server version - `v2.3.3-rc1`.

We have a dropdown and a toggle to enable selecting datastore clusters over datastores.

<img width="414" alt="Screen Shot 2019-11-12 at 12 21 06 PM" src="https://user-images.githubusercontent.com/4266958/68707641-fa18cb80-0546-11ea-8252-7a4d164ca9e3.png">

Able to pick datastore cluster from the dropdown when creating a vsphere template.
Able to create a vsphere cluster successfully using this template. Able to see the machines created  using the selected datastore cluster from the template in Vsphere Client UI.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 9f8763def`

We have a dropdown and a toggle to enable selecting datastore clusters over datastores.
![Screen Shot 2019-11-18 at 9 09 27 AM](https://user-images.githubusercontent.com/57409052/69069500-cd036780-09e3-11ea-9b6f-5deaf4f5f6da.png)
