### ISSUE TITLE
[forwardport] Deploy/Edit Workload page - Drop down icon disappears when hovering over protocol and port type field.

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#24001]
Forwardport of rancher/rancher#23987

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head version` `abd6f58c6`

Deploy/edit workload pag - Drop down icons stays when hovering over protocol and port type field.
![Screen Shot 2019-11-13 at 3 19 14 PM](https://user-images.githubusercontent.com/57409052/68809462-34f33000-0629-11ea-87f2-42c9ae471294.png)

On clicking "Add Port", both protocol and port type drop down icons stay and function.
![Screen Shot 2019-11-13 at 3 19 36 PM](https://user-images.githubusercontent.com/57409052/68809502-4e947780-0629-11ea-9159-890d08a82b68.png)

![Screen Shot 2019-11-13 at 3 19 47 PM](https://user-images.githubusercontent.com/57409052/68809516-52c09500-0629-11ea-9e85-7eae4be37263.png)
