### ISSUE TITLE
Add ability to enable snapshots for Prometheus data

### ISSUE THREAD

**Issue by panoslith** [rancher/rancher#24019]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
It would be convenient to have an option in monitoring in UI to enabe snapshots(wal directory + Prometheus data) for Prometheus. 

This can possibly be configured by passing the `- --web.enable-admin-api` in prometheus statefulset.

By having this configuration in place, would make it possible to create snapshots by hitting directly the cluster IP of prometheus service `access-prometheus` making a POST like the following:
`curl -XPOST http://1.2.3.4/api/v1/admin/tsdb/snapshot`

When persistent storage is enabled for Prometheus, there should be a folder created in that storage with the generated snapshot. 

gz#7024

**Comment by leodotcloud** [comment]
It's possible to take snapshots of the Prometheus Data in the new monitoring v2.

- Step 1: When installing the monitoring chart, enable Admin API. See screenshot attached.

- Step 2: Create an API key.

- Step 3: Do a POST using curl command to take a snapshot. (See here for more info.)

Sample command:

```bash
curl -u  token-abcde:secretvalue -XPOST https://rancher.example.com/k8s/clusters/c-12345/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/api/v1/admin/tsdb/snapshot
```

Sample response:

```
{"status":"success","data":\{"name":"20211126T125653Z-70a75ff98f18f8e4"}}
```
