### ISSUE TITLE
[backport] vSphere datastore cluster UI

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#24027]
Backport of rancher/rancher#24002

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by sangeethah** [comment]
Tested with rancher server version - v2.3.3-rc1.

We have a dropdown and a toggle to enable selecting datastore clusters over datastores.

<img width="414" alt="Screen Shot 2019-11-12 at 12 21 06 PM" src="https://user-images.githubusercontent.com/4266958/68708115-e28e1280-0547-11ea-8fe7-6cb425079028.png">


Able to pick datastore cluster from the dropdown when creating a vsphere template.
Able to create a vsphere cluster successfully using this template. Able to see the machines created using the selected datastore cluster from the template in Vsphere Client UI.
