### ISSUE TITLE
Rancher UI won't work on IE11

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#24028]
Version: v2.3-head (11/11/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Attempt to launch Rancher UI on IE11 on Windows 10

**Result:**
This will fail with:
![image](https://user-images.githubusercontent.com/45179589/68612918-d8eaa900-047a-11ea-8cad-e397f62a5635.png)

In the browser console.

**Expected Result:**
We expected the UI to at least render so we can be redirected to the /ie page to notify that IE is not supported.

**Other details that may be helpful:**
Related to: https://github.com/rancher/rancher/issues/23909#issuecomment-552572102

**Comment by izaac** [comment]
IE11 reached EOL
