### ISSUE TITLE
Update default storage driver for RancherOS in vsphere to use overlay2

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#24033]
Currently, when using vsphere and RancherOS, the default storage driver is `overlay`, but it should be updated to `overlay2`. 

https://github.com/rancher/os/issues/2808

**Comment by deniseschannon** [comment]
@sangeethah it seems that the default Docker install URL for RancherOS is using 17.03.2. Is that the case? 

The use cases to test are:

Check that in both use cases that the storage driver would be `overlay2` as default (no input).

1. Test with default docker install URL
2. Test with latest Docker install version

**Comment by sangeethah** [comment]
@deniseschannon , When creating a Vsphere template with ROS , the default docker version gets set to `19.03` .
ROS - 1.5.4 itself comes with default docker version - `18.09`

**Comment by deniseschannon** [comment]
@sangeethah What is the default storage solution?

**Comment by sangeethah** [comment]
@deniseschannon It is `overlay2`. But this is the also the default value when we get when getting an ROS 1.5.4 VM created.  
I will test with `v2.3.2` version to see if the default that we are getting is `overlay` when provisioning vsphere with ROS 1.5.4 VM to confirm that docker machine update done in `v2.3.3-rc1`  resulted in   storage to be defaulted to overlay2`.

**Comment by sangeethah** [comment]
Tested with rancher server version  - `v2.3.3-rc1` .
Created a Vsphere cluster with template having default values for docker install url  , creation method  and providing no value for "Storage Driver"

<img width="830" alt="Screen Shot 2019-11-12 at 4 45 40 PM" src="https://user-images.githubusercontent.com/4266958/68722969-0bc09a00-056c-11ea-8e87-1be48e24b9a3.png">
<img width="828" alt="Screen Shot 2019-11-12 at 4 45 27 PM" src="https://user-images.githubusercontent.com/4266958/68722970-0bc09a00-056c-11ea-9fc1-2be505cd434f.png">

Storage driver gets set to "overlay2" as expected on the Vsphere ROS nodes that are provisioned as part the K8s cluster.

` Storage Driver: overlay2`
