### ISSUE TITLE
[forwardport] Update instance types in EKS worker template

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#24035]
The current [EKS template](https://github.com/rancher/kontainer-engine/blob/master/drivers/eks/templates.go#L219) is behind on some instance type releases, as such selecting an instance from the UI can throw a parameter validation in the following CloudFormation stack when launching EKS workers.

**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** Launch and EKS cluster with an instance type that is currently in the UI (for eg, t3a.medium), but not in the template.

**Result:**

```
2019/11/11 04:06:04 [ERROR] ClusterController c-6whkr [cluster-provisioner-controller] failed with : error creating stack with worker nodes template: error creating master: ValidationError: Parameter NodeInstanceType failed to satisfy constraint: Must be a valid EC2 instance type
	status code: 400, request id: c314b250-abb3-4b3c-9e04-6534748a8ce6
```

**Other details that may be helpful:**

A longer term solution to maintaining these in the [UI](https://github.com/rancher/ui/blob/master/lib/shared/addon/utils/amazon.js) and template may be possible [with an API call](https://github.com/rancher/rancher/issues/19812#issuecomment-552617771)

**Comment by dramich** [comment]
@dkeightley KE was merged, can you open a PR to update rancher's go mod files?

**Comment by soumyalj** [comment]
Reproduced the issue with v2.3.0
Created a EKS cluster with `t3a.medium ` nodes. EKS cluster fails with the below error
```

Error creating stack with worker nodes template: error creating master: ValidationError: Parameter NodeInstanceType failed to satisfy constraint: Must be a valid EC2 instance type status code: 400, request id: bd485ba5-3496-4768-9f8c-344fd0de49a7
--




```

**Comment by dkeightley** [comment]
This will also solve #20652

**Comment by soumyalj** [comment]
Tested with master-head build from Dec 12(bdb8e67c907d)
Created a EKS clusters with t3a.medium nodes, c3.large nodes. Clusters came up successfully and were functional. Verified the node types in AWS and API. 
```
amazonElasticContainerServiceConfig": {
"accessKey": "dasdasdasdas",
"ami": "",
"associateWorkerNodePublicIp": true,
"desiredNodes": 1,
"displayName": "",
"driverName": "amazonelasticcontainerservice",
"ebsEncryption": false,
"instanceType": "t3a.medium",
"keyPairName": "",
"kubernetesVersion": "1.14",
"maximumNodes": 1,
"minimumNodes": 1,
"nodeVolumeSize": 20,
"region": "us-west-2",
"serviceRole": "",
"sessionToken": "",
"subnets": null,
"userData": "#!/bin/bash\nset -o xtrace\n/etc/eks/bootstrap.sh ${ClusterName} ${BootstrapArguments}/opt/aws/bin/cfn-signal --exit-code $? --stack  ${AWS::StackName} --resource NodeGroup --region ${AWS::Region}",
"virtualNetwork": ""
}



```



```
"amazonElasticContainerServiceConfig": {
"accessKey": "sdfdsfdsfds",
"ami": "",
"associateWorkerNodePublicIp": true,
"desiredNodes": 1,
"displayName": "",
"driverName": "amazonelasticcontainerservice",
"ebsEncryption": false,
"instanceType": "c3.large",
"keyPairName": "",
"kubernetesVersion": "1.14",
"maximumNodes": 1,
"minimumNodes": 1,
"nodeVolumeSize": 20,
"region": "us-west-2",
"serviceRole": "",
"sessionToken": "",
"subnets": null,
"userData": "#!/bin/bash\nset -o xtrace\n/etc/eks/bootstrap.sh ${ClusterName} ${BootstrapArguments}/opt/aws/bin/cfn-signal --exit-code $? --stack  ${AWS::StackName} --resource NodeGroup --region ${AWS::Region}",
"virtualNetwork": ""
}

```

**Comment by stomplee** [comment]
Just tried this and used t2.micro instance type and got the same error.  If an instance type is not supported why is it available in the cluster provisioning drop down?
