### ISSUE TITLE
[Forwardport] Node count not reflected on cluster list view , until refreshed.

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#24034]
Forwardport of rancher/rancher#23973

**Comment by westlywright** [comment]
Available in `latest2`.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version abd6f58c6`

Steps to reproduce the problem:
Create a DO cluster.
When user is brought back to the cluster list view , node count is 1 as expected.
Once the cluster gets to "Active" state , Global->Cluster-> shows that the cluster has "System" and "Default" project as expected.
