### ISSUE TITLE
Rancher 2.4 HA migration path from K8s

### ISSUE THREAD

**Issue by lopf** [rancher/rancher#24043]
**What kind of request is this (question/bug/enhancement/feature request):**
question
feature request

**Summary**
We recently discovered on the roadmap that Rancher 2.4 will support non-Kubernetes HA deployments (https://github.com/rancher/rancher/wiki/Rancher-2.4):
>Leveraging the flexibility and simplicity of Rancher K3S, Rancher 2.4 HA will ship as an appliance. There will no longer be a requirement to run Rancher HA on a Kubernetes cluster or dependency on Docker. Just install a single Rancher binary, with a systemd unit file, on two or more nodes pointed at a database will be all that is needed.

Will you support the (data) migration from an installation on Kubernetes (Helm) to the new architecture? If not, could you please consider this? We're really looking forward to it!

**Comment by marvin-w** [comment]
Any update on this?
