### ISSUE TITLE
Rancher 2.3 vsphere Cloud Provider Issues

### ISSUE THREAD

**Issue by Spookman** [rancher/rancher#24045]
**What kind of request is this : bug

I have just try Rancher 2.3 and created a new cluster and adding the cloud_provider setting in the yaml the same way I did it in Rancher 2.2.8
I am adding the cloud_provider at the bottom of the YAML file

cloud_provider: 
  name: "vsphere"
  vsphereCloudProvider: 
global: 
  insecure-flag: true
  soap-roundtrip-count: 0
virtual_center: 
  myvc: 
    datacenters: "CLOUD"
    soap-roundtrip-count: 0
    user: "administrator@vsphere.local"
    password: "MyPassword"
workspace: 
  datacenter: "CLOUD"
  default-datastore: "vsanDatastore01"
  folder: "Rancher"
  server: "myvc"
But for some reason rancher is not automatically deploying the PVC, I have tested this multiple times, and in 2.2.8 it works perfectly in 2.3 it’s not ?

**Result:**
Cloud provider not initialized properly

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.3.2
- Installation option (single install/HA):
Single

**Cluster information**
- Machine type VM

- Docker version (use `docker version`):
16.
```
(paste the output here)
```

**Comment by sangeethah** [comment]
@Spookman With 2.3 , we need to have the `cloud_provider:`  section created under the `rancher_kubernetes_engine_config` section . 
Could you please try having the  `cloud_provider:`  section under `rancher_kubernetes_engine_config` section and see if the cloud provider settings works ?

**Comment by Spookman** [comment]
@sangeethah Thanks for the response, I have re attempted this under the rancher_kubernetes_engine_config which I am sure I have always done, but this is still having the same problem. just to iterate the same cloud_provider config works 100% in Rancher 2.8.x

**Comment by Spookman** [comment]
I have found the issue, it's was an incorrect line in the config file,

**Comment by PavelZaytsev** [comment]
@Spookman What line are you referring to?
