### ISSUE TITLE
Rancher logo should go back to main page rather than show version

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2404]
The Rancher icon should link to "home" rather than the Rancher version.  This keeps things consistent with every other websites.

**Comment by lukerandall** [comment]
+1

**Comment by vincent99** [comment]
Step 1: define "main page"
Step 2: find another easy place to tell people to click to get the version (or maybe just always show the rancher version and click that, @lvuch)

**Comment by sshipway** [comment]
-1.  I'm with @vincent99 on this one.

**Comment by lukerandall** [comment]
I tend to expect clicking on the logo in a nav bar to take me to the home page. In this case that would be wherever `/` takes you (in this case that would be the Applications page at `/apps`). I think a tooltip on the icon could reveal versions.

That said, I personally don't feel that strongly about this. In the course of using Rancher for a few weeks I've trained myself to not click the logo :)

**Comment by demarant** [comment]
this is also related to #2718 where the dashboard is the new home of rancher

**Comment by vincent99** [comment]
There's still no dashboard but the version is in the footer now so the cow is no longer a link at all.  This should make both camps equally unhappy.

**Comment by tfiduccia** [comment]
Version - master 2/24
Verified everyone unhappy and logo does not link.
