### ISSUE TITLE
is there a documented rancher 2.x API to manage projects and so on

### ISSUE THREAD

**Issue by ohauer** [rancher/rancher#24046]
**What kind of request is this:** 
question

**Environment information**
- Rancher version 2.3.2

Background:
We want to create e.g. projects, roles, access tokens and so on dynamically in rancher without touching the web UI.

**Comment by kleoken** [comment]
I've been using rancher for the past couple months and as far as I can tell, this is the extent of the [API documentation](https://rancher.com/docs/rancher/v2.x/en/api/). It tells you how to create "resources" i.e projects, roles, tokens, etc... in a generic way by sending `POST` requests and then you can modify/update them with `PUT` and then delete with `DELETE`.

**Comment by superseb** [comment]
See https://rancher.com/docs/rancher/v2.x/en/api/ and https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-automate-task-x-in-rancher.

For progress on more extended docs, see https://github.com/rancher/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22API+docs%22
