### ISSUE TITLE
[Forwardport] Creating an App with xip.io and then upgrading the app switching to Hostname allows to leave the Hostname blank.

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#24057]
Forwardport rancher/rancher#22733

**Comment by soumyalj** [comment]
Tested with master-head. 
Install grafana as a multi cluster app. 
After an upgrade of the grafana app , UI hangs and many fields are not displayed.

**Comment by soumyalj** [comment]
Tested with master-head with UI index latest2
Steps:
Launch grafana multicluster app and choose "Automatically generate a .xip.io hostname"
After the app is launched successfully, upgrade the app and choose "Specify a hostname"
and leave the field blank. The app gives the error as expected. 
<img width="437" alt="Screen Shot 2019-11-18 at 1 44 15 PM" src="https://user-images.githubusercontent.com/18536626/69096577-917b9400-0a09-11ea-9b05-17cfdc2e829b.png">
Once the "Hostname is required" error is seen, click on cancel .
Click on "upgrade" again , then "Automatically generate a .xip.io hostname" is selected as expected
<img width="900" alt="Screen Shot 2019-11-18 at 1 45 34 PM" src="https://user-images.githubusercontent.com/18536626/69096710-cab40400-0a09-11ea-832f-344cbb2b72cf.png">
