### ISSUE TITLE
can not ssh when creating ec2 instance

### ISSUE THREAD

**Issue by linbingdouzhe** [rancher/rancher#24061]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
rebuild ec2 machine 

**Result:**
2019/11/13 02:47:10 [ERROR] NodeController c-bz2qn/m-25jm9 [node-controller] failed with : Error creating machine: Error running provisioning: error selecting docker: (ssh command error:

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
rancher 2.3.0 release 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
19.3.4
```
(paste the output here)
```

**Comment by linbingdouzhe** [comment]
sometimes this error appears ，sometimes not . is this is a bug ?

**Comment by superseb** [comment]
Please describe in more detail what steps you are taking to make sure we can investigate it properly. How was the cluster created and what exact steps are taken to `rebuild ec2 machine`? Also, full logging of the `rancher/rancher` container can help here as well.

**Comment by superseb** [comment]
Please let us know when you can provide the information.
