### ISSUE TITLE
Add a Rancher provisioning plugin for Jenkins

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2406]
Create a provisioning plug-in for Jenkins.

**Comment by qrpike** [comment]
This would be pretty great

**Comment by cloudnautique** [comment]
This one is pretty vague, if its for Jenkins slaves, we have the Swarm plugin with Jenkins server in the catalog. If its for deploying services, we have some good blog posts on how to do it. 

In both cases, there are things we could do to make it better. What would be your ideal use case?e

**Comment by JulianKingman** [comment]
Can't speak for others, but a plugin that simply installs rancher-compose would be handy.

**Comment by knohr** [comment]
@cloudnautique Do you have any links? I have been digging on this topic for a few hours.

**Comment by deniseschannon** [comment]
![screen shot 2016-05-05 at 2 48 31 pm](https://cloud.githubusercontent.com/assets/11410997/15058339/7adf4d1a-12d0-11e6-8c4e-f469dca1dd21.png)

He was referencing the plugin in the Catalog.

**Comment by knohr** [comment]
@deniseschannon I have those up and running, and they work great.  I suppose I was really just looking for methods of cross environment deployment from Jenkins in a CD pipeline.

I've tabled it for now, as the demo I'm working on will be fine with a single environment, but it's still something I would need to get going before integrating rancher with an existing pipeline.

**Comment by astewart-twist** [comment]
Is this in regards to a jenkins-plugin that would allow jenkins to deploy to rancher via the rancher api?  Because that would be neat.

**Comment by JulianKingman** [comment]
@astewart-twist that's what I was hoping for

**Comment by steventarver** [comment]
**Goal**: A Jenkins plugin that allows trigging a Rancher Stack upgrade via Rancher api using environment api keys.

**Scenario**: Currently, I have a jenkins job that builds code, creates a docker image, pushes that image to a repository, ssh's into a host cleaning up old containers and running a new one.

Security boundaries prevent me from ssh'ing into some servers to `rancher-compose up`. Communicating via an https endpoint authenticated by api key/secret is sufficiently secure. 

I would like to specify a rancher-server deploy post build step where I could identify a rancher-server, an environment by name, a stack by name, options to finish the upgrade. I am writing a script to do this now, but a jenkins plugin would be an elegant addition, especially as the jenkins job count grows.

**Comment by yuvrajh** [comment]
Hi frendss

I am newbee to Rancher so i want to know whether it's possible **launching jenkins slave using rancher-compose**??

Thanx In advance

**Comment by yunlzheng** [comment]
I have create a new jenkins rancher plugin https://github.com/yunlzheng/rancher-plugin to support deploy/upgrade service instance in rancher. 

Current use Rancher account API key, and support the follow variables

|       variable |         description |       example |
|----------------|---------------------|---------------|
| API Endpoint   | Rancher Account API Endpoint | http://rancher-server/v2-beta |
| AccessKey      | Account API Access Key | F39583DE2EB3DABD28B0 |
| SecretKey      | Account API Secret Key | 2AAHwT3YVXpNT9rMhxSs3egFrwFgKK3c3bYaXK7w |
| Rancher Environment Id | Environment id | 1a5558 |
| Service Name | Target service name | stackname/servername |
| Docker Image | Docker image tag | busybox |
| Auto Confirm   | Auto finish upgrade service  | true |
