### ISSUE TITLE
[Forwardport] Ingress doesn't work due to missing related svc when using custom domain instead of xip.io

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#24068]
https://github.com/rancher/rancher/issues/24018

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/rancher/pull/24181

**Comment by deniseschannon** [comment]
Closing as we will only have 1 issue that tracks 2.3.x and 2.4 issues. 1 issue should be linked to 2 PRs.
