### ISSUE TITLE
[UI] in branch master, error message never pop up when user add action in global scope 

### ISSUE THREAD

**Issue by hubert-he** [rancher/rancher#24064]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. click Add user in Admin scope
2. never select one of base user item
3. browser log: findTranslationByKey is not a function 

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 5ccf85b5a`

`Add User` in Global view.
Uncheck `Global Permissions`.
![Screen Shot 2019-11-19 at 9 24 34 AM](https://user-images.githubusercontent.com/57409052/69165303-95adbd00-0aae-11ea-9e64-71044cbcf82d.png)

Create user.
Error message:
![Screen Shot 2019-11-19 at 9 25 00 AM](https://user-images.githubusercontent.com/57409052/69165329-a4946f80-0aae-11ea-99ef-559fa72dd7b2.png)
