### ISSUE TITLE
Allow scraping custom metrics at the cluster level

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#24063]
This issue is a detailed break out of issue 3 in issue #23239
`Users can not scrape custom endpoints at the cluster level.`

### Current Pain Points
 
* If there are many projects, users have to enable project level Prometheus in each project. Then they can scrape custom metrics. It's complex and take many CPU and Memory resources.
* Users are not able to use HPA based on custom metrics in the current implementation of Rancher monitoring. 
* The Prometheus adapter can only bind to one Prometheus instance. Multiple project Prometheus instances can not be used.
* Cluster level Prometheus only scrapes ServiceMonitor custom resources in the system project.
 
### Proposed solution
 
* Remove the System project only limitation in cluster level Prometheus. So it can scrape all custom metrics in the cluster.
* Project prometheus will scrape project metrics (CPU, Memory and Custom metrics) from cluster level Prometheus as usual through Prometheus auth.
* Disable custom metrics in project level Prometheus. Otherwise, the metrics will be duplicated if we scrape metrics in both cluster level and project level Prometheus.
* When a cluster admin enables cluster monitoring, they should be able to define either a white or black list of projects to control where the cluster level Prometheus should look for ServiceMonitor resources.
* A user can also have the option to specify no projects ('none') which will mimic the current behavior monitoring behavior. Also, an 'All' option will be available which will scrape all projects.
* Workloads in an observed project should also be able to use the  `prometheus.io` annotations. Users should be use them out of box just like using original Prometheus Operator.
* Allow a user to specify a custom annotation to select projects/namespaces for monitoring. In this case the user would be responsible for annotating the projects/namespaces themselves.
* Allow the user to specify a secret in the system project for additional scrape configs. This should not be altered by Rancher during upgrades.
* HPA should be able to leverage custom metrics from the cluster level monitoring endpoints.
### Constraints

* Upgrading from previous versions should not cause data loss moving to the new model.
* Any upgrades should not overwrite any users customizations using this functionality going forward.

**Comment by adampl** [comment]
The additional scrape configs should be a ConfigMap rather than a Secret, right?

**Comment by cloudnautique** [comment]
@adampl, scrape configs can have basic auth, bearer tokens and TLS information that might be sensitive so that is the motivation behind using secret vs. configmap.

**Comment by adampl** [comment]
OK, that makes sense.

**Comment by iwin4aids** [comment]
+1 

customer metrics should be supported at project level , current prometheus's config file ignore the "prometheus.io" scrape annotations
