### ISSUE TITLE
Update node-agent upgrade strategy

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#24062]
For `node-agent` daemonset the `updateStrategy` is set to rollingUpdate. 
Configure it so that upgrade batchSize is 25% through rollingUpdate field `maxUnavailable`

Part of https://github.com/rancher/rancher/issues/23038

**Comment by khushboo-rancher** [comment]
Node agent upgrade is working in batch of 25% when upgraded to master-head.
1. Rancher upgrade from v2.3.4 to master-head.
    Tested on a cluster of 10 nodes. 
    Node upgrade happened in batch of 25%. 2 Nodes upgraded at same time.  
    Yaml file - 
     updateStrategy:
           rollingUpdate:
                maxUnavailable: 25%
           type: RollingUpdate
2. Rancher upgrade from v2.3.4 to 2.3.5-rc2
     Tested on a cluster of 11 nodes.
      Node upgrade happened one by one.
3. Rancher rollbacked from master-head to v2.3.4
      Tested on a cluster of 11 nodes.
      Node upgrade happened one by one.
4. Tested for multiple clusters, functionality worked fine.

**Comment by khushboo-rancher** [comment]
Node-agent upgrade strategy tested on HA env, functionality worked fine.

Tested on HA set up with 3 nodes(each node - 1etcd/1control/1worker)
ec2 cluster created with 8 nodes(1etcd/1control/6worker)
1. Upgraded from v2.3.4 to v2.3.5 - maxunavailable - 1 - upgraded one by one
2. Upgraded from v2.3.5 to rancher version ff4dfd753 - maxunavailable - 25% - upgrade 2 nodes at a time.

However, an issue #25154 is observed of failure cluser-agent pods.
