### ISSUE TITLE
Monitoring - project Prometheus can't fetch metrics from workloads 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#24072]
This happens in both k8s 1.13 and 1.14 cluster, with Monitoring v0.0.6 and 0.0.5

Steps:
- run Rancher v2.3-head 5187fce31
- add an RKE cluster with k8s 1.14 (or 1.13)
- add a project
- enable the project monitoring using template v0.0.6 (or v0.0.5)
- deploy a workload with custom metrics (image: loganhz/web)
- go to the project's Prometheus's page
- check the `Configuration` under `status`, we see the workload is added as a job
- check the `Targets` under `status` cannot see the endpoint for the workload
<img width="1605" alt="Screen Shot 2019-11-13 at 10 07 06 AM" src="https://user-images.githubusercontent.com/6218999/68787261-686c9500-05fe-11ea-9e95-6450cb778d65.png">

More Info:
This is NOT seen in k8s 1.15, 1.16 with Monitoring 0.0.6

**Comment by thxCode** [comment]
Steps of Custom Metric troubleshooting:
1. Prometheus Operator: confirm the status from Prometheus Web UI
    - [x] It seems you could get the scrape target in the Target page from Prometheus Web UI, so this means Prometheus Operator has already translated the ServiceMonitor into Prometheus scraping configuration. 
1. Metric Service: confirm that is there a `${WORKLOAD_NANE}-metrics` existing in the same Namespace
    - [ ] In your case, we could check is there a `test3-metrics` Service below `test2` Namespace.
1. Cluster Agent: confirm the logs of it
    - [ ] The metric service is controlled by the controller of cluster agent, after configuring a **NEW** custom metric, you could view some logs as below:
    ```
    time="2019-11-12T23:56:21Z" level=info msg="Creating [test-49687/test-27134-nodeport] service of type [NodePort] with ports [[{8080tcp01 TCP 8080 {0 8080 } 0}]] for workload deployment:test-49687:test-27134"
    time="2019-11-12T23:56:21Z" level=info msg="Creating [test-49687/test-27134] service of type [ClusterIP] with ports [[{8080tcp01-test-web TCP 8080 {0 8080 } 0}]] for workload deployment:test-49687:test-27134"
      ```

If `#2, #3` could not be satisfied, please restart the cluster agent Pod to observe again.

**Comment by jiaqiluo** [comment]
@thxCode Thanks for the investigation. 
I did not get the issue reproduced in a new setup. It is more like a transient issue rather than a bug. How do you think?
