### ISSUE TITLE
Management Plane components such as cattle-cluster-agent should not rely on CoreDNS on the worker nodes

### ISSUE THREAD

**Issue by stefanlasiewski** [rancher/rancher#24078]
Some Rancher control plane services rely on internal DNS resolution. The coredns servers run on worker nodes. If a worker node is rebooted, degraded, misconfigured or nonresponsive, the Rancher control plane can become degraded which will affect the entire cluster.

The Rancher control plane should be isolated from problems on the worker nodes. Core services should not become degraded simply due to the failure of services on the worker nodes.

**What kind of request is this (question/bug/enhancement/feature request):**

Bug/feature request.

**Steps to reproduce (least amount of steps as possible):**

These steps *should* reproduce my issue. 

1. Spin up a Kubernetes cluster for user workloads via Rancher Launched Kubernetes. In my case, my workload cluster consists of a pretty standard configuration:

- A 3 node cluster for with the roles of control plane & etcd: rancher0,1,2
- 2 nodes to run workloads, rancher3 & rancher4

I also have a management cluster running Rancher which is running and is not touched by this maintenance. The Rancher API sits behind an Nginx load balancer.

2. Looks to see where the coredns, cattle-cluster-agent services are running. CoreDNS is running on the two worker nodes, rancher3 & rancher4.

```
root@mgmt1:~# kubectl get pods --all-namespaces -o wide |egrep "cattle-system|coredns"
cattle-system                     cattle-cluster-agent-abcdefg123-98099                      1/1     Running            0          21h     10.42.0.12      rancher0   <none>           <none>
cattle-system                     cattle-node-agent-asdd9                                    1/1     Running            2          4d16h   192.168.100.61   rancher4   <none>           <none>
cattle-system                     cattle-node-agent-dasdt                                    1/1     Running            0          4d16h   192.168.100.57   rancher0   <none>           <none>
cattle-system                     cattle-node-agent-vqasd                                    1/1     Running            2          4d16h   192.168.100.59   rancher2   <none>           <none>
cattle-system                     cattle-node-agent-xasd5                                    1/1     Running            2          4d16h   192.168.100.58   rancher1   <none>           <none>
cattle-system                     cattle-node-agent-123as                                    1/1     Running            2          4d18h   192.168.100.60   rancher3   <none>           <none>
kube-system                       coredns-asdasdasd-sasd4                                    1/1     Running            0          26m     10.42.4.76      rancher4   <none>           <none>
kube-system                       coredns-asdasdasd-12398                                    1/1     Running            0          15m     10.42.7.65      rancher3   <none>           <none>
kube-system                       coredns-autoscaler-f97674f9f-pjkvj                         1/1     Running            0          26m     10.42.4.74      rancher4   <none>           <none>
root@mgmt1:~#
```

3. Shutdown both worker nodes, rancher3 & rancher4. This will shutdown the coredns service for the entire cluster.

4. Restart or reschedule 'cattle-cluster-agent'. It will fail to come back because it cannot resolve the hostname for the loadbalancer. The loadbalancer is up, running, available. DNS resolution works from all hosts.

If cattle-cluster-agent cannot come up, the entire cluster is left in a degraded state. This prevents us from scheduling some kinds workloads. If I deployed Rancher Monitoring a this point, it would fail to deploy completely.

```
root@mgmt1:~# kubectl -n cattle-system logs cattle-cluster-agent-abcdefg123-98099
INFO: Environment: CATTLE_ADDRESS=10.42.0.3 CATTLE_CA_CHECKSUM=<removed> CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-abcdefg123-98099  CATTLE_SERVER=https://rancher.example.org
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local c
luster.local example.org options ndots:5
ERROR: https://rancher.example.org/ping is not accessible (Could not resolve host: rancher.example.org)
```

Also, note it's stuck in a crash loop and will remain in a loop forever:

```
root@mgmt1:~# kubectl get pods -n cattle-system |grep cattle-cluster-agent
NAME                                    READY   STATUS             RESTARTS   AGE
cattle-cluster-agent-abcdefg123-98099   0/1     CrashLoopBackOff   708        2d15h
root@mgmt1:~#
```

The DNS pods, network pods, etc. are all running.

### To recover

5. Start the worker nodes. Notice that CoreDNS has also started.

6. Watch as cattle-cluster-agent restarts. It **can** now resolve the DNS for the API server and will start running again.

**Other details that may be helpful:**

**Environment information**
- Rancher version: v2.3.2
- Installation option: HA

**Cluster information**
- Cluster type: Custom. Ubuntu 18.04. Rancher Launched Kubernetes.
- Machine type: VMware VMs.
- Kubernetes version:
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Docker version 18.09.9, build 039a7df9ba
```

SURE-1497

**Comment by Sahota1225** [comment]
This is a known issue in Rancher for RKE1 clusters. On startup, cattle-cluster-agent connects to CATTLE_SERVER (Rancher Server URL) and if this is set such that it requires DNS resolution, agent requires coredns to be running to start successfully. coredns can only be scheduled on worker nodes, so coredns pods fail to be scheduled when there are no worker nodes.
For more details, see: https://github.com/rancher/rancher/issues/31244#issuecomment-790274280 
Both the worker nodes are shut down in the reproduction steps, so this behavior is expected.
