### ISSUE TITLE
[backport] Refresh EKS-Optimized AMIs for supported EKS versions

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#24074]
https://github.com/rancher/rancher/issues/23701

**Comment by soumyalj** [comment]
Tested with rancher v2.3-head . 
Created EKS clusters with new AMIs from different regions us-east1 and us-east2. 
Cluster got created successfully and were functional. 
<img width="1758" alt="Screen Shot 2019-11-13 at 4 59 11 PM" src="https://user-images.githubusercontent.com/18536626/68817566-f2385480-0636-11ea-984d-4b6ad0493415.png">
