### ISSUE TITLE
Version 1.6.29 buggy in Safari

### ISSUE THREAD

**Issue by staegi** [rancher/rancher#24083]
Rancher 16.29 is not updating the GUI in Safari when the process is finished. There appears an error in the console:
[Error] WebSocket connection to 'ws://rancher.warehouseplus.de:8080/v2-beta/projects/1a5/subscribe?eventNames=resource.change&limit=-1&sockId=1' failed: Invalid UTF-8 sequence in header value

It's working in Chrome and earlier Rancher versions. I am running version 1.6.18 on another server and it's fine.

**Comment by staegi** [comment]
The last running version is 1.6.25! So it's broken since version 1.6.26

**Comment by staegi** [comment]
Any updates on this issue?

**Comment by vincent99** [comment]
2.0 was released two and half years ago and we no longer support or maintain 1.x.

But plenty of people have used versions >=1.6.26 in the last 2 years.. so whatever the problem is, it's probably something to do with your environment and not happening for everyone.
