### ISSUE TITLE
UI stuck in 'Saving" state when launching Grafana app

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#24080]
Version: v2.3-head

Single node setup

Steps:
1. As an admin, launch "Grafana" app on a DO cluster. 
2. Once launch is clicked, the UI is stuck is "Saving" state as below
<img width="829" alt="Screen Shot 2019-11-13 at 11 45 12 AM" src="https://user-images.githubusercontent.com/18536626/68798378-2c8bfc80-060b-11ea-9017-839a882f92b3.png">

The console has the below error : 
<img width="581" alt="Screen Shot 2019-11-13 at 11 45 17 AM" src="https://user-images.githubusercontent.com/18536626/68798424-42012680-060b-11ea-8979-bbf70180f824.png">

**Comment by westlywright** [comment]
Available in `latest-2.3`.

**Comment by soumyalj** [comment]
Tested with v2.3-head with latest UI index latest-2.3
Steps:
As an admin, launch "Grafana" app on a DO cluster.
Launching the app was successful. There were no errors in the console
