### ISSUE TITLE
Create new "developer" role in environment

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2408]
An environment current has three roles.

1. Admin/Owner - A member that can also invite other members
2. Member - A member with full privileges except inviting members 
3. Read-Only Member - A member that can only "read", no updates, creates, or deletes on any Rancher resources.

Support a new "developer" role that has no access to CRUD hosts within an environment.  No UI for Infrastructure should show up within this environment.

**Comment by vincent99** [comment]
No access to hosts doesn't really make sense... You need them for public IP addresses, labels for scheduling and other things.  And if a host goes down a bunch of service containers will go red but there will be no way to see what's going on with no access to the host tab at all.

Who would expect "developer" to be locked down more than "read only"?

**Comment by will-chan** [comment]
The owner simply does not want other members to add/remove/view hosts.  They do want them to create services.

**Comment by sshipway** [comment]
I definitely want a way to be able to allow users to create services/containers but not Add/delete Hosts or Add/Delete Registries.  See #2580

**Comment by hibooboo2** [comment]
rancher/cattle#1069 Is now merged to master.

**Comment by deniseschannon** [comment]
Verified with master build 11/23. 

Not able to add/edit/clone/delete hosts. Able to do all actions on services.
