### ISSUE TITLE
UI - Support creating storage class for local persistent volumes

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#24082]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

The use of Local Persistent Volumes requires creating a storage class with attribute `volumeBindingMode: WaitForFirstConsumer` to ensure pods are properly scheduled to nodes.

We should support creating this type of storage class in the GUI.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/

**Comment by sowmyav27** [comment]
**Verified on latest master-head - commit id: `189e4337c`**

- go to Cluster level --> Storage --> Storage classes --> Add storage
- Volume Binding Mode - two options are available on the UI
- - Bind and provision a persistent volume once the PersistentVolumeClaim is created
- - Bind and provision a persistent volume once a Pod using the PersistentVolumeClaim is created
<img width="1283" alt="Screen Shot 2019-12-27 at 10 18 06 AM" src="https://user-images.githubusercontent.com/26032343/71528028-c1cd1280-2892-11ea-8960-ecb892599380.png">

**Scenario#1**
- Created storage classes with Binding Mode : `Bind and provision a persistent volume once the PersistentVolumeClaim is created`
- Created volume claims. The state of the VC is `Active`
- Created workloads with the above PVC attached as volume
- User is able to access the volume

**Scenario#2**

- Created storage classes with Binding Mode : `Bind and provision a persistent volume once the PersistentVolumeClaim is created`
- Created volume claims. The state of the VC is `Pending`
- Created workloads with the above PVC attached as volume
- The state of the VC is `Active`
- User is able to access the volume
