### ISSUE TITLE
[forwardport] Vsphere Template - Creation method defaults to "RancherOS ISO(Deprecated)"

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#24086]
Forwardport of rancher/rancher#24060

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 9f8763def`

We default to "Deploy from template: Data Center" and "Rancher ISO" is called out as legacy.
![Screen Shot 2019-11-18 at 9 17 52 AM](https://user-images.githubusercontent.com/57409052/69069824-60d53380-09e4-11ea-8371-bf87cbe37d21.png)

**Comment by Coolfeather2** [comment]
is there any documentation on how to use Deploy from template: Data Center?

**Comment by codyrancher** [comment]
The only documentation we have on that is https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/node-pools/vsphere/provisioning-vsphere-clusters/#a-configure-the-vsphere-credential

If there's something specific you're looking for @luthermonson might be able to point you in the right direction.
