### ISSUE TITLE
UI - Persistent Volume plugin naming should match Kubernetes naming

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#24081]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Navigate to Cluster->Storage->Persistent Volumes
Click Add Volume
Expand Volume Plugin list
Notice that following Volume Plugin names don't match any [documented Kubernetes volume types](https://kubernetes.io/docs/concepts/storage/volumes/):

- Local Node Disk
- Local Node Path

**Expected Result:**

Volume plugin naming should match documented Kubernetes naming so that a user can easily discern what the plugins are.

Propose to rename:

Local Node Disk -> Local
Local Node Path -> HostPath

Rancher 2.3.2

**Comment by aaronRancher** [comment]
Tested in `rancher\rancher:master-head` `version 781cd0fdc`.

Create a cluster.
In Cluster -> Storage -> Persistant volumes -> Add Persistent Volume
In Volume Plugin dropdown:
Naming now reflects documented Kubernetes naming.
![Screen Shot 2019-11-26 at 10 59 23 AM](https://user-images.githubusercontent.com/57409052/69659634-d91ea300-103b-11ea-844b-bba6bcb92ff6.png)
