### ISSUE TITLE
can not find the ceph storageclass

### ISSUE THREAD

**Issue by chengzn** [rancher/rancher#24098]
*Describe your issue here*

in rancher v2.3.2  

can not find the ceph-rbd and ceph-filesystem storageclass
![image](https://user-images.githubusercontent.com/42170032/68867514-e7fa8100-0730-11ea-9e52-8b9f31e4d1f5.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.2` UI: `v2.3.22` |
|Route|`authenticated.project.pipeline.settings`|

**Comment by LeandroPT** [comment]
+1
