### ISSUE TITLE
RancherUI Refused connection

### ISSUE THREAD

**Issue by yyykl** [rancher/rancher#24090]
**What kind of request is this (question/bug/enhancement/feature request):**
 **question**

**Steps to reproduce (least amount of steps as possible):**

1. 使用了各项调优（https://www.rancher.cn/docs/rancher/v2.x/cn/install-prepare/best-practices/os/）

2.启动命令：
docker run -d --restart=unless-stopped   -p 30080:80 -p 30443:443  -v /etc/localtime:/etc/localtime:ro -v /var/lib/rancher/:/var/lib/rancher/  -e HTTP_PROXY="http://10.12.33.6:8095"   -e HTTPS_PROXY="http://10.12.33.6:8095"   -e NO_PROXY="localhost,127.0.0.1,0.0.0.0,10.12.33.0/24,10.13.33.0/24,rc.genesysinfo.net" --name rancher  10.13.33.32:5000/rancher:stable2.3  && docker logs -f rancher |grep ERROR

3. custom 添加集群 ，2个etcd，2个Control，2个worker

4.启动了监控、Traefik

**Result:**
每次搭建好集群，第二天凌晨1点多，rancher webUI 请求被拒绝，k8s集群还是好的，Traefik还是可以用。

**Other details that may be helpful:**
2019-11-14 01:06:53.637710 W | etcdserver: failed to revoke 694d6e642f69d8d7 ("lease not found")
2019-11-14 01:07:26.578553 W | etcdserver: read-only range request "key:\"/registry/management.cattle.io/users\" range_end:\"/registry/management.cattle.io/usert\" count_only:true " with result "range_response_count:0 size:8" took too long (4.569185176s) to execute
2019-11-14 01:07:26.578576 W | etcdserver: request "header:<ID:7587842323760404951 > lease_revoke:<id:694d6e642f69d991>" with result "size:30" took too long (3.090365027s) to execute
2019-11-14 01:07:26.578859 W | etcdserver: failed to revoke 694d6e642f69d991 ("lease not found")
2019/11/14 01:07:33 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019-11-14 01:08:07.714255 W | etcdserver: failed to revoke 694d6e642f69da4d ("lease not found")
2019/11/14 01:09:08 [ERROR] Failed to update cluster [c-8nrhb]: Operation cannot be fulfilled on clusters.management.cattle.io "c-8nrhb": the object has been modified; please apply your changes to the latest version and try again
E1114 01:10:15.529828      40 leaderelection.go:306] error retrieving resource lock kube-system/kube-controller-manager: Get https://localhost:6444/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1114 01:10:16.039964      40 server.go:252] lost master
F1114 01:10:16.040188      40 controllermanager.go:248] leaderelection lost
E1114 01:10:16.417784       7 reflector.go:280] github.com/rancher/norman/controller/generic_controller.go:175: Failed to watch *v3.MultiClusterAppRevision: Get https://localhost:6443/apis/management.cattle.io/v3/watch/multiclusterapprevisions?allowWatchBookmarks=true&resourceVersion=507&timeout=30m0s&timeoutSeconds=391: dial tcp 127.0.0.1:6443: connect: connection refused

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/server：2.3.2
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
cloud
rancher-server:8V16G
master/node:4V8G

- Kubernetes version (use `kubectl version`):

```
(1.15.5-rancher1-2)
```

- Docker version (use `docker version`):

```
(Version: 18.03.1-ce)
```

**Comment by loganhz** [comment]
Please join WeChat group by searching `rancher2` if you want to describe your issue in Chinese. Thanks.
