### ISSUE TITLE
Ability to set MTU in cluster yaml/config

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#24096]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

**Details:**

The ability to set the MTU for the network providor would be very helpful for a number of our customers that have interfaces set to MTUs other than 1500. An example customer requires an MTU of 9000 on a bonded interface.

While under most circumstances you can set the MTU in the canal config map and just delete the pods and let them be rescheduled, this config map gets recreated when kubernetes is updated.

The ability to set the interface MTU in the cluster yaml/config is what is desired here.

**Comment by superseb** [comment]
Can be tested using:

```
network:
  plugin: canal
  mtu: 4500
```

**Comment by jiaqiluo** [comment]
tested in Rancher:v2.3-head baa64d48a

Steps:
- provision RKE cluster with different CNI (Canal, Calico, Weave) with `mtu: 4500` under the network section in the config yaml file

Results:
- For the cluster with Canal, go to project `System` to check the Config Map `canal-config` to see the value for `mtu`
 
<img width="1423" alt="Screen Shot 2019-12-13 at 1 24 01 PM" src="https://user-images.githubusercontent.com/6218999/70831008-b962db00-1dae-11ea-8736-dee2d834dc14.png">


- For the cluster with Calico, go to project `System` to check the Config Map `calico-config` to see the value for `veth_mtu`
<img width="1463" alt="Screen Shot 2019-12-13 at 1 45 19 PM" src="https://user-images.githubusercontent.com/6218999/70831063-d39cb900-1dae-11ea-883b-0ad750ea6d6e.png">

- For the cluster with Weave, exec into the workload `weave-net` under the project `System`  to check environment variables 
```
/home/weave # env | grep  MTU
WEAVE_MTU=4500
```

**Comment by jiaqiluo** [comment]
@superseb  Should there be a forward port to Rancher:master-head ?

**Comment by leodotcloud** [comment]
@superseb with this setting, we need to add documentation that the cluster admin needs to configure the host MTU less 50 for vxlan encap.

Example: If MTU of `eth0` is 9000, then we need to pass 8950 in cluster.yml
