### ISSUE TITLE
RFE: Add ability to use Azure Private Link when creating AKS clusters

### ISSUE THREAD

**Issue by ebauman** [rancher/rancher#24102]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
n/a

**Result:**
n/a

**Other details that may be helpful:**

Azure Private Link is a service similar to AWS VPC Endpoints that allows one to create a service endpoint inside of a VPC instead of external. AKS supports (currently in preview) the ability to create an AKS endpoint that is a private link endpoint. We should too.

**Comment by janeczku** [comment]
Closing as pre-duplicate since we track the RFE [here](https://github.com/rancher/rancher/issues/25273)
