### ISSUE TITLE
vSphere node template with cloud config fails to provision with `Waiting for SSH`

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#24101]
rancher/rancher:v2.3-head 160e3b691

* Create a vSphere node template with cloud config
example:
```
#cloud-config
packages:
 - redis-server
```
* Create a cluster
* Nodes are stuck in provisioning with `Waiting for SSH to be available`

**Comment by luthermonson** [comment]
https://github.com/rancher/machine/pull/50

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/24104

**Comment by bmdepesa** [comment]
https://github.com/rancher/rancher/pull/24109

**Comment by sangeethah** [comment]
Tested with rancher server version - `v2.3-head` - `5ac58c6d6`

Create a vSphere node template with cloud config
example:
```
#cloud-config
packages:
 - redis-server
```
Create a cluster
Nodes get created successfully.
Node have `redis-server` installed.

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/24113
