### ISSUE TITLE
UI/UX epic for Zero Downtime Upgrades

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#24110]
https://github.com/rancher/rancher/issues/23038

**Comment by maggieliu** [comment]
UI screenshot: https://xd.adobe.com/view/ebd4dccd-69a0-41fb-78af-907601a6a2f6-9de5/

**Comment by kinarashah** [comment]
Another field that got added later on is a boolean `drain` option. When `drain` is set to true, UI should ask for nodeDrainInput parameters, similar to how we ask them currently while draining a node from UI. 

types PR: https://github.com/rancher/types/pull/1069/files

**Comment by codyrancher** [comment]
@kinarashah when can I expect these changes to be in master-head?

I have most of my changes completed and I'd like to verify it against the backend.

**Comment by sowmyav27** [comment]
Verified on master-head - UI Tag: Latest2

maxUnavailable field and Drain input is available on the UI
<img width="1285" alt="Screen Shot 2020-02-19 at 6 31 31 PM" src="https://user-images.githubusercontent.com/26032343/74895304-1e562680-5346-11ea-8ae6-152071fe08a7.png">

**Comment by sowmyav27** [comment]
Related issue -- https://github.com/rancher/rancher/issues/25670

**Comment by sowmyav27** [comment]
**Current behavior on latest - master - head - commit id: `37363ba67`**

- deploy a cluster.
- Edit on cluster --> Edit as YAML
```
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
```

**Comment by sowmyav27** [comment]
Being tracked in https://github.com/rancher/rancher/issues/25501 and https://github.com/rancher/rancher/issues/25670. 
Closing this epic issue.
