### ISSUE TITLE
[forwardport] vSphere SSH Timeout

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#24114]
https://github.com/rancher/rancher/issues/24101

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 9f8763def`

Create a vSphere node template with cloud config
```
#cloud-config
packages:
 - redis-server
```
![Screen Shot 2019-11-18 at 4 50 02 PM](https://user-images.githubusercontent.com/57409052/69103760-7f0e5400-0a23-11ea-8fb1-1a9b38c87750.png)

Create a vSphere cluster
Nodes get created successfully.
Node have redis-server installed.
```
Last login: Mon Nov 18 23:33:40 2019 from 172.16.128.100
$ redis-server
19581:C 18 Nov 23:41:12.478 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
19581:C 18 Nov 23:41:12.478 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=19581, just started
19581:C 18 Nov 23:41:12.478 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
19581:M 18 Nov 23:41:12.480 * Increased maximum number of open files to 10032 (it was originally set to 1024).
19581:M 18 Nov 23:41:12.480 # Creating Server TCP listening socket *:6379: bind: Address already in use
```

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/24113

**Comment by sangeethah** [comment]
https://github.com/rancher/rancher/pull/24087

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 9f8763def`

Create a vSphere node template with cloud config
Create a vSphere cluster
Nodes get created successfully.
Node have redis-server installed.
