### ISSUE TITLE
Show tooltips for container names

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2412]
Please add tooltips for container names and ability to extend host box area or toggle word wrapping in user ui settings, because as you can see in an image below all containers look the same :) At least add tooltips...
<img width="288" alt="screenshot 2015-10-23 14 00 54" src="https://cloud.githubusercontent.com/assets/3070298/10691066/ea7566b8-798e-11e5-8f30-44a466353bac.png">

**Comment by deniseschannon** [comment]
There are some new views of the UI that should help with this issue in our latest release (v0.42.0), where you can see what services are from what stack. 

![screen shot 2015-10-23 at 9 18 01 am](https://cloud.githubusercontent.com/assets/11410997/10698665/0589cc8c-7967-11e5-9450-b52bebe3e1c6.png)

**Comment by tfiduccia** [comment]
Highlighting over the container name in host view now shows the whole container name.  Enabled tooltip.
