### ISSUE TITLE
[UI]a bug about add user feature in global scope which is all checkbox turn into text when generate button clicked

### ISSUE THREAD

**Issue by hubert-he** [rancher/rancher#24122]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. open add user page in global scope 
2. input password using generate button

**Result:**
all checkbox turn into text 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 5ccf85b5a`

`Add User` in global view.
`Generate` a new password.
Checkboxes remain and function.
![Screen Shot 2019-11-19 at 9 14 02 AM](https://user-images.githubusercontent.com/57409052/69164370-1e2b5e00-0aad-11ea-8129-3fcfdceed41c.png)
