### ISSUE TITLE
[Question] Configured cacerts checksum does not match given --ca-checksum

### ISSUE THREAD

**Issue by IAkumaI** [rancher/rancher#24125]
I'm getting error "Configured cacerts checksum does not match given" in cattle-node-agent and cattle-cluster-agent after machine restart. Sometimes. Sometimes not.

Why it so?

**What kind of request is this (question/bug/enhancement/feature request):**

Question.

**Steps to reproduce (least amount of steps as possible):**

I have a VirtualBox with Ubuntu ubuntu-18.04.3-live-server-amd64.iso
Installed rke k8s with zero config (just node + ssh setting).
Then, I run rancher in docker with `docker run -d --restart=unless-stopped -p 8080:80 -p 8443:443 -v /opt/rancher:/var/lib/rancher rancher/rancher:latest`
Then, I add cluster to the rancher UI. All works fine.

Next, I reboot machine (or turn off/on, no matter).

**Result:**

Sometimes (50/50) rancher lost the cluster. Just empty cluster list. Sometimes i getting error of issue. Sometimes all works fine.

Cluster not fail. k8s work fine. It's just rancher trouble.

**Other details that may be helpful:**

I can't figure out the reason of error. It just happend after 1-3 machine restarts.

**Cluster information**
- Cluster type: Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 4 CPU/ 6Gm RAM
- Kubernetes version: 1.15.5

- Docker version: 19.03.4

**Comment by IAkumaI** [comment]
Update. After getting an error i tried to reboot machne several times. After 6 try - error gone, it works.

**Comment by superseb** [comment]
This is not a setting that should change randomly, if it does, we'll need some more steps to reproduce. Regarding "losing the cluster", it sounds like there is a resource issue that might cause this behavior. Please share in more detail how the cluster is built (how many nodes with what specs) and the machine where Rancher is running (and what version) so we can investigate.

**Comment by superseb** [comment]
Let us know when you can provide the requested information.

**Comment by ricardo-aspira** [comment]
I am facing this issues with an imported cluster.

I created 12 machines using ansible:
- 1 RKE
- 1 LB of local cluster (Nginx outside cluster)
- 3 Nodes for Rancher Server with three k8s roles controlplane, etc and worker
- 1 LB of dev cluster (Nginx outside cluster)
- 3 Nodes for controlplane and etc
- 3 Nodes for worker

I provisioned the clusters using rke up config for both local and cluster.

I regenerated the certificates for local cluster domain and upgraded them into rancher (tls-ca and tls-rancher-ingress) and also into the LB of local cluster.
It is working fine, excepting for having to delete de pods of ingress-controller on all 3 nodes of local cluster.

The controlplane 01 of dev cluster started to be shown as NotReady and there were just a few of Pods there.
I executed the rke up again at dev clusters and controlplane 01 of dev cluster started to be shown as Ready.

After that, the dev cluster (imported) stopped to work on Rancher Server UI, showing me this:
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.
Exit status 1, unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request.

I rebooted the controlplane 01 but it was not enough.

I checked the differences between node 01 and 02 of the controlplanes and see a missing pod at 01: k8s_agent_cattle-node-agent-*

When I got the logs, I saw:
...
ERROR: Configured cacerts checksum (c375f6d7fbb3d0978819f82c7fea4d65c245d1367456c26646a04232b0c4dfa7) does not match given --ca-checksum (ccad03d073a2f3b4ff72fa32b45e9a3be1a9cbc05ed4a9040c04587fc95c2006)
ERROR: Please check if the correct certificate is configured at https://local.rancher.company.io/v3/settings/cacerts

So I went for a rke certificates rotate with rke cert rotate --rotate-ca --config ../rancher-cluster.yml but error continues.

**Comment by superseb** [comment]
This is all about how Rancher is configured, Rancher is installed using a certain certificate setup (Rancher generated/cert-manager/certificates from files) and based on certain flags we populate `/v3/settings/cacerts` (basically needed when using self signed certificates). Based on that configuration we deploy the agents (and include the checksum for the value in `/v3/settings/cacerts` to make sure the agent retrieves the value that it should be). If anything changes in how Rancher's certificates are configured (which is not automatically updated, see https://github.com/rancher/rancher/issues/14731), the values from the previous config are not valid anymore, making this validation fail. This is not related and fixable by RKE cert commands, which apply to the cluster's component certificates.
