### ISSUE TITLE
move ns to a default project automatically

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#24136]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature (or maybe bug?)

**Steps to reproduce (least amount of steps as possible):**
In CI eg. gitlab-managed  clusters the namespace is created on the fly.
Usually a schema like "projectname-projectid-environment".

**Result:**
These end up without any project-membership. And nothing can be deployed (at least when PSPs are used).

It would be very useful, if one could provide a default project - like the existing "Default", where all namespaces will be moved.
This could be extended by regex-filters.

regards,
strowi

**Comment by superseb** [comment]
Covered in https://github.com/rancher/rancher/issues/16493
