### ISSUE TITLE
Grafana only accessible with Manage Services Permission

### ISSUE THREAD

**Issue by phpboyscout** [rancher/rancher#24137]
We have multiple members of our team at different permissions levels. In order for them all to be able to view Grafana we have to give them the "Manage Services" permission on the System project... this seems wrong and that it should be tied to the View Services permission

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3-rc2` UI: `v2.3.24` |
|Route|`apps-tab.detail`|

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24213
