### ISSUE TITLE
[forwardport]user settings shouldn't get overridden by driver metadata

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#24132]
https://github.com/rancher/rancher/issues/22572

**Comment by jiaqiluo** [comment]
THe enhancement is validated with the upgrade path from v2.3.3-rc3  to master-head 781cd0fdc

Variable | Default values in v2.3.2-rc3 | User's Change
-- | -- | --
k8s-version | "v1.16.3-rancher1-1" | "v1.14.9-rancher1-1"
k8s-versions-current |  "v1.14.9-rancher1-1,v1.15.6-rancher1-2,v1.16.3-rancher1-1" | "v1.14.9-rancher1-1,v1.15.6-rancher1-2,v1.99.99-rancher1-1"
k8s-versions-deprecated | "{}" | {"v1.16.3-rancher1-1":true}

Steps:

- run Rancher v2.3.3-rc3
- add a cluster with v1.16.3-rancher1-1
- set those three setting variables according to the table above 
- check that user's change takes effect:
	- the default version is set to v1.14.9-rancher1-1
	- the version list is the same as the user's change
	- edit the cluster with v1.16.3-rancher1-1 fails
- upgrade Rancher to master-head 781cd0fdc

Results:
- user's changes are kept and also take effect
