### ISSUE TITLE
Pull from Optional Private Registry results in "no basic auth credentials"

### ISSUE THREAD

**Issue by theAkito** [rancher/rancher#24141]
I've read most issues on private registries, but I'm not sure if my problem is already mentioned, as those do not provide enough information, sometimes it is not even clear, if they are talking about private registries as the default image provider or registries as an optional provider, that is set in Resources -> Secrets -> Registry Credentials. My problem is regarding the latter.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug/Question

**Steps to reproduce (least amount of steps as possible):**
1. Add Cluster.
2. Add optional private registry through Resources -> Secrets -> Registry Credentials.
3. Let a pod pull an image from this private registry.

**Result:**
```
ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: Get https://hub.example.org:5000/v2/imagename/manifests/0.1.2: no basic auth credentials
```

**Other details that may be helpful:**
* I was trying to find a solution for hours over days, nothing worked out. Once I let Rancher run in the background idling with the error. I returned to it hours later and suddenly the error was and is still gone, even after several restarts of this environment.
It magically started working.

* Problem is, I set up an identical cluster in a different place and now I receive the above error again. Do I need to let the magic happen again or is there a better solution?

* Switching from specific namespace to all does not have any relevant effect.

* Using a simple password with only alphanumeric characters does not help either.

* This private registry works a 100% outside of Rancher, absolutely perfectly. Tested in many environments, by many people.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.2
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by Akito13** [comment]
@loganhz 
Greetings and thank for the tip.

If I change `imagePullPolicy` to `Never` or `IfNotPresent` it does not complain anymore, as the image is already there. However I don't see a mention of my registry within `imagePullSecrets`. 

From what I read [this step](https://kubernetes.io/docs/concepts/containers/images/#referring-to-an-imagepullsecrets-on-a-pod) is missing? So I guess that is a bug?

**Comment by loganhz** [comment]
If you use yaml to deploy the workload, you need to deal with the imagePullSecrets stuff by yourself in yaml. If you use Rancher UI to deploy workload, please make use you add the registry credential before you create the workload in UI. Then Rancher will add the imagePullSecrets automatically.

**Comment by Akito13** [comment]
@loganhz 
Thanks for your help.

I did not know there is this degree of importance to the chronological order of setting this up. I will try it out when I'm back at work and see if it works when I first set up the secrets and create the workloads afterwards.
Thanks again, appreciate the support.

**Comment by Akito13** [comment]
@loganhz 
Seems like a bug. I followed your advice and the credentials indeed were **not** added to the YAML. I added the credentials, then created the workloads and it still is not part of the YAML. Somehow it fails to be added.

**Comment by imwower** [comment]
> If you use yaml to deploy the workload, you need to deal with the imagePullSecrets stuff by yourself in yaml. If you use Rancher UI to deploy workload, please make use you add the registry credential before you create the workload in UI. Then Rancher will add the imagePullSecrets automatically.

newly deployed workload doesn't work as well, 
even I add password before create new workload, but old app works fine
