### ISSUE TITLE
UI: Browser back button skips some pages

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2415]
Steps to reproduce:

1. Load Rancher UI, defaults to Applications page.
2. Click Infrastructure link at the top.
3. Click a host on Infrastructure page.
4. Click brower back button.

Expected: Browser navigates back to the Infrastructure page.
Actual: Browser navigates back to the Applications page.

Further steps, from a specific host's (A) page:

1. Click Hosts link.
2. Click another host on the Infrastructure page.
3. Click browser back button.

Expected: Browser navigates back to the Infrastructure page.
Actual: Browser navigates back to the initial host's page (A).

**Comment by deniseschannon** [comment]
Verified with latest UI (11/24 evening).

The above examples are working.
