### ISSUE TITLE
Why can't pod and container restart? No entry for restart

### ISSUE THREAD

**Issue by jiahuei2cs** [rancher/rancher#24153]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.2` UI: `v2.3.22` |
|Route|`pod`|

**Comment by MSandro** [comment]
on the workload, click 'redeploy' to restart your pods

**Comment by superseb** [comment]
Please share the use case around your request, as there is probably a better way to implement what you want. Redeploy replaces pods, deleting pods will schedule new ones, but without knowing what problem you are trying to solve, it's hard to give an advice.
