### ISSUE TITLE
openstack cinder storage class has gone away 

### ISSUE THREAD

**Issue by wowsel** [rancher/rancher#24155]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
I just installed the rancher 2.3.2 and created a 1.15.5 cluster.
I used openstack for provisioning cluster.  nothing more.

**Result:**
I can't add a cinder storageclass. he just disappeared from the rancher's list.
<img width="270" alt="image" src="https://user-images.githubusercontent.com/18245332/69138091-18df0b00-0acf-11ea-95a5-bb8af9d4476d.png">

**Other details that may be helpful:**
the cloud provider normally deployed on all nodes in the config.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
2.3.2
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): openstack
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): 1.15.5

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```
Thanks

**Comment by albertdb** [comment]
Same here.

**Comment by albertdb** [comment]
@wowsel Found solution: https://github.com/rancher/rancher/issues/23047#issuecomment-534720192

**Comment by loganhz** [comment]
Please see https://rancher.com/docs/rancher/v2.x/en/admin-settings/feature-flags/enable-not-default-storage-drivers/
