### ISSUE TITLE
rancher imported k3s - logging

### ISSUE THREAD

**Issue by superboris** [rancher/rancher#24157]
Hi ranchers! The only problem I have is when I import k3s into a rancher, and I activate the Logging (Splunk) section in rancher, it doesn't work :( and when I look at fluentd it's full of weird characters.

I hope this rancher v2.3.x functionality of rancher can work for k3s too, it would be great!

I have not considered other solutions as it is a rancher functionality.

screenshot
![image](https://user-images.githubusercontent.com/44072415/69146884-87ac6c00-0aaf-11ea-95c2-306f2d06f464.png)

thanks team rancher!

gzrancher/rancher#9907

gzrancher/rancher#10627

**Comment by dramich** [comment]
@superboris This should be fixed in the latest release, are you able to test it out?

**Comment by izaac** [comment]
@dramich this is happening in 2.4 `master-head` Rancher version 721d5e24b but only with imported k3s clusters.

Steps:

1. Import a k3s cluster
2. deploy workload `izaac/nginx-json-log` and create an ingress for it
3. enable cluster level logging for the k3s cluster (enable JSON parsing) 
4. test the settings using the TEST button in the UI and check the fluentd server for message like:
   - 2020-01-30 23:34:11.000000000 +0000 rancher: {"message":"Rancher logging target setting validated"}
5. Hit the ingress created in step 2 with curl or a browser.
6. Nothing will reach the fluentd server after that but looking into the logs of `rancher-logging-fluentd-linux` there will be logs collected and with the backslashes issue.

**Comment by ludopaquet** [comment]
Hello same issue in rancher 2.3.5. 
Containerd doesn't log in json. There is a solution here https://github.com/cri-o/cri-o/issues/897 to handle both json docker and containerd format. Found no workaround for the moment.

**Comment by superboris** [comment]
@dramich, Hi, updated the latest versions of rancher (v3.2.5) and k3s (v1.17.2 + k3s1) when importing the k3s cluster, the same problem occurs to me as @izaac I'm still looking for a solution.

**Comment by dramich** [comment]
@superboris Yes, this is still an issue with imported k3s and is being looked into.

**Comment by cjellick** [comment]
Solution will be a change to our fluentd logging configuration (possibly to use the mult_format plugin referenced here https://github.com/cri-o/cri-o/issues/897#issuecomment-329865461), not a change to k3s.

**Comment by izaac** [comment]
Just for completeness I also tested this without the `Enable JSON Parsing` same steps as my previous comment here https://github.com/rancher/rancher/issues/24157#issuecomment-580519460 but I've just used the default `nginx` docker image in a project.

**Comment by cjellick** [comment]
and you got the same result or it worked? JSON should definitely not work because, yeah, CRI doesnt to json logs output

**Comment by izaac** [comment]
> and you got the same result or it worked? JSON should definitely not work because, yeah, CRI doesnt to json logs output

I got the same result @cjellick the logs in `rancher-logging-fluentd-linux` are with the backslashes issue.

**Comment by sunpeinju** [comment]
Hit same issue. And I followed this tip(https://github.com/rancher/k3s/issues/356) to update the `rancher-logging-fluentd` secret and replace "format  json" with a regexp "<parse>" section.

The work around do work, but will be overwrite by Rancher again some time later...

**Comment by spicysomtam** [comment]
Still an issue in rancher 2.4.4. The advice was not very clear. @sunpeinju maybe you can confirm? I see there are lots of fluentd `.conf` blocks in the secret. I just unloaded the first one `cluster.conf`, base64 decoded it, changed `format json` to:

```
<parse>
        @type regexp
        expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
        time_format %Y-%m-%dT%H:%M:%S.%NZ
 </parse>
```
Then encoded back (`base64 -w0`). Then did a `kubectl edit` on the secret and pasted in the base64 encoded `cluster.conf` for that section. The secret was loaded into the pods and they picked up the change without needing to redeploy them. Now pod logs look sane and am receiving logging in eleasticsearch from all node pods. 

@sunpeinju hopefully that is sufficient, or do I need to do all the `.conf` file blocks?

**Comment by spicysomtam** [comment]
Still getting loads of \\\ on the logging. Maybe I should try [this](https://github.com/cri-o/cri-o/issues/897#issuecomment-329865461)?

**Comment by spicysomtam** [comment]
The [link](https://github.com/cri-o/cri-o/issues/897#issuecomment-329865461) in my last post is what is needed. I applied it to all `.conf` entries in secret `rancher-logging-fluentd`. Replace all occurances of `format json` with that `parse` block.

**Comment by izaac** [comment]
> The [link](https://github.com/cri-o/cri-o/issues/897#issuecomment-329865461) in my last post is what is needed. I applied it to all `.conf` entries in secret `rancher-logging-fluentd`. Replace all occurances of `format json` with that `parse` block.

Using this suggestion also mitigates the `\\` feedback @spicysomtam

**Comment by izaac** [comment]
I no longer see the backlash feedback even when the match type in the fluentd target server is set to `stdout` as previously observed. And neither in the `rancher-logging-fluentd-linux` workload container logs.

A Standard User was used while creating all resources in the Rancher server.

Rancher version `v2.4-head (07/16/2020)` _e28427e4a_
Imported k3s cluster `k3s version v1.18.4+k3s1 (97b7a0e9)` 1 master 2 workers
RKE cluster with DO as infrastructure provider.  `v1.18.6-rancher1-1`


Rancher version `master-head (07/16/2020)` _16616de9c_
Imported k3s cluster `k3s version v1.18.4+k3s1 (97b7a0e9)` 1 master 2 workers
RKE cluster with DO as infrastructure provider.  `v1.18.3-rancher2-3`

The following steps [here](https://github.com/rancher/rancher/issues/24157#issuecomment-580519460) were done for the k3s and RKE clusters. Now the logs are flowing as expected to the target server and no backlash feedback.


1. Import a k3s cluster
2. deploy workload `izaac/nginx-json-log` and create an ingress for it
3. enable cluster level logging for the k3s cluster (enable JSON parsing) 
4. test the settings using the TEST button in the UI and check the fluentd server for message like:
   rancher: {"message":"Rancher logging target setting validated"}
5. Hit the ingress created in step 2 with curl or a browser.


I've submitted a separate issue about the Test settings button in `master-head` #27969
