### ISSUE TITLE
Overrides in Multi Cluster Apps are not rendered correctly after upgrade to 2.3.2

### ISSUE THREAD

**Issue by infinytum** [rancher/rancher#24159]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy any multi-cluster apps and add overrides
2. Select Upgrade to change the overrides

**Result:**
The overrides are partially blank, mutli-level overrides don't render at all.

**Other details that may be helpful:**
What it looks like:
![image](https://user-images.githubusercontent.com/43315617/69156642-06230100-0ae4-11ea-9914-28d443b3ff63.png)

What it should look like:
![image](https://user-images.githubusercontent.com/43315617/69157094-c3adf400-0ae4-11ea-8e0c-d0e9023efb9d.png)

```answers:
  - values:
      image.registry: REDACTED
      image.repository: REDACTED
      image.tag: latest
      ingress.custom.enabled: "false"
      ingress.default.dev: "false"
      ingress.default.enabled: "true"
      limits.cpu: "1"
      limits.memory: 2000Mi
      name: someproject
      port.enabled: "true"
      port.expose: "80"
      port.port: "3030"
      replicas: "1"
      requests.cpu: 200m
      requests.memory: 200Mi
  - projectName: c-kbmpt:p-8s7b5
    values:
      image.tag: devel
      ingress.default.dev: "true"
      ingress.default.enabled: "true"
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
  - 3x VMWare VM (4 Cores / 8GB)
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by rchench** [comment]
I met the same issue. no response yet. #23769

**Comment by infinytum** [comment]
Apparently the related issue #23769 has been fixed.
