### ISSUE TITLE
Where i can find self generate ssl of rancher and edit it?

### ISSUE THREAD

**Issue by dinhanhhuy** [rancher/rancher#24169]
**What kind of request is this (question):**

**Environment information**
- Rancher HA v2.2.8 (Centos 7 Core).

I install Rancher HA ([offical link](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher)) with [Rancher Generated Certificates](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#rancher-generated-certificates). Now, I want to switch CA manager to [Let’s Encrypt](https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/#let-s-encrypt), or at least edit the existing SSL key of rancher cluster with my new one.

Is that possible, and how to do that?
Thank you.

**Comment by dinhanhhuy** [comment]
I edit the tls secret key and it works perfectly. But I still not sure how to switch from `self generate` type to use `Let's Encrypt` without re-create a new cluster. Do rancher support switch type, or it needs to be done at the init time?

**Comment by superseb** [comment]
Changing certificates is covered in https://github.com/rancher/rancher/issues/14731
