### ISSUE TITLE
Cluster Upgrade stuck if EKS Cluster was updated manually

### ISSUE THREAD

**Issue by ms-dennis** [rancher/rancher#24171]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* Create EKS Cluster with Rancher(use a previous version to be able to upgrade ot the newest one)
* Manually Update the EKS Cluster via AWS Console
* Edit the Cluster in Rancher and set k8s Version to the most recent one

**Result:**
Cluster is stuck in upgrade process:

InvalidParameterException: Unsupported Kubernetes minor version update from 1.14 to 1.14 status code: 400, request id: 0ccda22c-e6ad-47ba-a0e4-4bdbf1b0f4ce

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
* Cluster was initially created with Rancher 2.2.x
* Updated the Cluster with Rancher 2.3.2 to k8s Version 1.14
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): c5.4xlarge (16/32G)
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-29T18:43:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Mon Mar  4 21:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Mon Mar  4 21:27:07 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by dkeightley** [comment]
This discrepancy can also occur during EKS version deprecation, where clusters are automatically updated out of band.

As such, an enhancement could be to sync the current EKS version with DescribeCluster. This could be periodically, before an update, or when handling this exception to alleviate looping on the UpdateCluster API call.

**Comment by rmweir** [comment]
@dkeightley what you described is a separate issue. As far as rancher is concerned, the version has not changed, so it will not communicate anything to EKS. In the first case mentioned, the version has changed and rancher attempts to communicate an update to EKS, which ends returns an errors because eks is already on that version.

**Comment by rmweir** [comment]
Created backport issue, this will be used to track master, the other will be for 2.4. There is no milestone for 2.5 yet, so it will stay as 2.4.

**Comment by rancher-max** [comment]
#### Validated in master-2689-head commit id `d18a0b6b4`

Scenario 1:
- Upgrading purely through Rancher is successful and updates the cluster to the selected version in AWS

Scenario 2:
- Upgrading through AWS UI upgrades the cluster in AWS but does not communicate the upgrade to Rancher
- Edit cluster through Rancher UI to sync the version to be what it is in AWS UI is successful


**NOTE: Remember that when updating the cluster whether with Rancher or AWS, it does not automatically upgrade the nodes, so those must be done separately. This can be done through CloudFormation by changing at minimum the AMI that is used.**

**Comment by rancher-max** [comment]
#### Validated in v2.4-2696-head (commit id `04159d027`)

Performed the same scenarios as above. **For scenario 2, I waited a bit longer before editing the cluster, and AWS did communicate properly to Rancher. It appears the sync just takes a little bit of time (my rough guess looks like approx. 5-15 minutes)**
