### ISSUE TITLE
为什么要写死域名，写死https ?

### ISSUE THREAD

**Issue by chinaboy007** [rancher/rancher#24185]
*Describe your issue here*
![image](https://user-images.githubusercontent.com/5228314/69331003-f8f64580-0c8e-11ea-993a-0d115f9cf8e4.png)

如何解决？
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.2` UI: `v2.3.22` |
|Route|`global-admin.clusters.index`|

**Comment by loganhz** [comment]
Docker默认认为所有的registry都是https的，如果你想用http的 要在docker deamon里设置insecure-registry
