### ISSUE TITLE
rke  FATA[0035] [etcd] Failed to bring up Etcd Plane: [etcd] Etcd Cluster is not healthy 

### ISSUE THREAD

**Issue by huyifanstar** [rancher/rancher#24184]
![image](https://user-images.githubusercontent.com/15685376/69330007-19250500-0c8d-11ea-9ed3-5945d1182a1c.png)
![image](https://user-images.githubusercontent.com/15685376/69330228-8173e680-0c8d-11ea-805c-a5de4f1eb9f4.png)

![image](https://user-images.githubusercontent.com/15685376/69330299-a405ff80-0c8d-11ea-8871-6ad6aad739ab.png)

FATA[0035] [etcd] Failed to bring up Etcd Plane: [etcd] Etcd Cluster is not healthy 

version:
ubuntu  18.04
docker   18.09.5

![image](https://user-images.githubusercontent.com/15685376/69330128-538ea200-0c8d-11ea-8965-cf34dfc2189c.png)

what should I do？

**Comment by loganhz** [comment]
merge into https://github.com/rancher/rancher/issues/24189
