### ISSUE TITLE
Make navigating to config maps mapped as volume or environment more convenient

### ISSUE THREAD

**Issue by krishofmans** [rancher/rancher#24188]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Navigate to the volumes of for example a deployment:
![image](https://user-images.githubusercontent.com/999774/69357085-cf382100-0c84-11ea-814c-bc5a1a06925d.png)

Wonder what is inside the configmap

**Result:**
I have to manually click through menu's to see what is inside the configmap, this feels quite cumbersome, since you could have a hyperlink take me to that page or even something embedded that would show configmap content?

**Comment by aaronRancher** [comment]
The feature is verified with Rancher server `rancher\rancher:master-head` `version 552eb2896`

Using Rancher server `rancher\rancher:v2.3.3`:
![Screen Shot 2020-01-06 at 2 27 16 PM](https://user-images.githubusercontent.com/57409052/71850107-c82c6d00-3090-11ea-9ba2-bb3a03e61735.png)

Using Rancher server `rancher\rancher:master-head` `version 552eb2896`:
![Screen Shot 2020-01-06 at 2 27 32 PM](https://user-images.githubusercontent.com/57409052/71850119-ce224e00-3090-11ea-96bd-828e08bb8809.png)
Following the hyperlink:
![Screen Shot 2020-01-06 at 2 27 45 PM](https://user-images.githubusercontent.com/57409052/71850130-d24e6b80-3090-11ea-8bde-c764936440e9.png)
