### ISSUE TITLE
failed to create volume, 409 Confict

### ISSUE THREAD

**Issue by sweetanran** [rancher/rancher#24186]
**What kind of request is this**
bug

**Steps to reproduce (least amount of steps as possible):**
Cluster of 16 physical machines，i start 100~200 containers at the same by rancher api 

**Result:**
![QQ图片20191121190413](https://user-images.githubusercontent.com/10240902/69332461-b4b87480-0c91-11ea-8ef1-3d24d2d31ff4.png)

What is the possible reason?

**Comment by jeremyhamm** [comment]
Having this issue as well, also looks like a duplicate of #5426
