### ISSUE TITLE
Rancher Metadata Service

### ISSUE THREAD

**Issue by shotai** [rancher/rancher#2418]
Hi, I am now working with Metadata service.
I have two questions here:

1.
If I have two services with same name in different stacks  (i.e. Default/nd1,  stack2/nd1), the `http://rancher-metadata/2015-07-25/services/nd1` would only return the first one it found.

```
root@f93a52f152c9:/# curl --header 'Accept: application/json'  'http://rancher-metadata/2015-07-25/self/stack'
{"environment_name":"Default","name":"Default","services":["nd1"]}

root@f93a52f152c9:/# curl --header 'Accept: application/json'  'http://rancher-metadata/2015-07-25/services/nd1'
{"containers":["Default_nd1_1"],"external_ips":[],"hostname":null,"kind":"service","labels":{"location":"/getRequest1"},"links":{},"metadata":{},"name":"nd1","ports":[],"sidekicks":[],"stack_name":"Default","vip":"169.254.113.62"}



root@f8ba45f30e7e:/# curl --header 'Accept: application/json'  'http://rancher-metadata/2015-07-25/self/stack'
{"environment_name":"Default","name":"stack2","services":["nd1"]}

root@f8ba45f30e7e:/# curl --header 'Accept: application/json'  'http://rancher-metadata/2015-07-25/services/nd1'
{"containers":["Default_nd1_1"],"external_ips":[],"hostname":null,"kind":"service","labels":{"location":"/getRequest1"},"links":{},"metadata":{},"name":"nd1","ports":[],"sidekicks":[],"stack_name":"Default","vip":"169.254.113.62"}

```

Is that possible to add one API that only returns the current stack's services or let the current API return all the services with the same name in different stacks?

2.
I noticed that 
```Note: Metadata service is not available for system containers, i.e. Network Agent and LB Agent. ```
So it means only the Metadata cannot be used in system containers or all the API cannot work?

 I can get the LB service (i.e. gateway) using 
`curl --header 'Accept: application/json'  	'http://rancher-metadata/2015-07-25/services/gateway' `,
However, if I modified the LB or add one from rancher web UI at run time, the Labels (`io.rancher.loadbalancer.target`) would not change.

Thank you for your help.

**Comment by alena1108** [comment]
@shotai 

1) We are aware of the usability bug when you can't query the service only for a particular stack name; and its in plans to be fixed soon.

2) rancher-metadata is not available to system containers, but all the information about Lb services and corresponding targets gets programmed to the metadata.

3) Regarding changing the targets. It is a bug that the load balancer host name routing rules are not being propagated to the metadata properly. You can only see all the target services registered to an LB by querying "links" field:

http://rancher-metadata/2015-07-25/services/gateway/links

but corresponding host name routing rules are not being updated. @deniseschannon ^^ its something we need to fix

**Comment by deniseschannon** [comment]
Created https://github.com/rancher/rancher/issues/2446 for the fact that you can't find the hostname routing rules using the metadata service

**Comment by deniseschannon** [comment]
@shotai For what Alena mentioned about having issues with duplicate service names in different stacks, there is an existing issue: #2091

If there are any other questions, please open a new issue.
