### ISSUE TITLE
Update base images used by Rancher to be current

### ISSUE THREAD

**Issue by mbulkeley** [rancher/rancher#24187]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Other details that may be helpful:**
Update the base images used by Rancher to be current.  For instance,  Auth Proxy (Image rancher/kube-api-auth) uses Ubuntu 16.04.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/15756
