### ISSUE TITLE
Rancher Machine Rename

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#24190]
Remove shim machine-pacakge repo and rename docker-machine to rancher-machine.

**Comment by luthermonson** [comment]
machine
https://github.com/rancher/machine/pull/51
https://github.com/rancher/machine/pull/52
https://github.com/rancher/machine/pull/53

and 

rancher
https://github.com/rancher/rancher/pull/24161

**Comment by sangeethah** [comment]
@izaac  As part of validating this issue , we need to make sure that all driver machine works as expected when provisioning nodes from all the supported node drivers:

Amazon EC2
Azure
Digital Ocean
Linode
Vsphere

**Comment by izaac** [comment]
Could this other GKE issue be related to this renaming? https://github.com/rancher/rancher/issues/24218 @luthermonson

**Comment by luthermonson** [comment]
@izaac not related and i do see you closed out that other issue. just thought i'd respond :)

**Comment by izaac** [comment]
Tested with Rancher version "2.4 master-head (11/25/2019) addeb8399"

Clusters created (and also removed) for:

- Amazon EC2
- Azure
- Digital Ocean
- Linode
- vSphere

vSphere cluster:
![Screen Shot 2019-11-25 at 11 37 07 AM](https://user-images.githubusercontent.com/27659/69568182-5d0f5700-0f78-11ea-8e9f-82a1f5ba91c7.png)

The others:
![Screen Shot 2019-11-25 at 11 37 17 AM](https://user-images.githubusercontent.com/27659/69568199-64366500-0f78-11ea-8776-a9c7ccf5daee.png)

@luthermonson as per our conversation, please check if this coverage is enough to QA all the changes made in the renaming. If this is good we can close the issue.

**Comment by luthermonson** [comment]
@izaac legit, this makes me happy to see. thanks!

**Comment by luthermonson** [comment]
@izaac back ported this issue, will put it back to test when it's merged: https://github.com/rancher/rancher/pull/24618

**Comment by luthermonson** [comment]
Version bump and rancher-machine rename in 2.3 now. Please run cluster creation automation against release/v2.3 and let's see how this goes.

**Comment by izaac** [comment]
Tested with Rancher version `2.3-head` d73dff8df

Clusters created (and also removed) for:

- Amazon EC2 (Automation)
- Azure (Automation)
- Digital Ocean (Automation/Manual)
- Linode (Manual)
- vSphere (Manual)

I've notice an issue but I logged it separately https://github.com/rancher/rancher/issues/24695 @luthermonson 

Closing.
