### ISSUE TITLE
rancher-compose 

### ISSUE THREAD

**Issue by silviupanaite** [rancher/rancher#2419]
Using rancher-compose outputs "No help topic for 'upgrade' " no matter what I through at it.
Rancher	v0.39.0
Cattle	v0.95.0
User Interface	v0.52.0
Rancher Compose	beta/latest

**Comment by deniseschannon** [comment]
Can you do `rancher-compose -v` to see what version of rancher-compose you are running? 

Were you trying `rancher-compose upgrade -h`? This should work in the release that has upgrade implemented.

**Comment by silviupanaite** [comment]
rancher-compose version v0.1.3, I downloaded rancher-compose through the UI. Tried oder build from the git the also show the same version.

**Comment by silviupanaite** [comment]
It turns out that I'm using on an old machine that had older compose installed, ./rancher-compose -v outputs the correct version v0.4.3
