### ISSUE TITLE
Invalid K8S version is used for AKS provisioning

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#24199]
**Rancher Version**
master 11/22 - 2a08c3a9f

**What kind of request is this (question/bug/enhancement/feature request):**
bug-qa

**Steps to reproduce (least amount of steps as possible):**
1. Click `Add Cluster` and select AKS.
2. Input AKS credentials
3. Input resource group name and ssh key, use the default for the rest. Note that the kubernetes version is v1.14.8 as the default.
4. Create and wait for cluster provisioning.

**Result:**
![image](https://user-images.githubusercontent.com/5697937/69409961-f6562780-0d44-11ea-890f-cbe5a2bec976.png)

**Other details that may be helpful:**
The version field in the API request is set to 1.11.5, not the 1.14.8 shown in the UI.
![image](https://user-images.githubusercontent.com/5697937/69410036-230a3f00-0d45-11ea-8b62-e7e671f37288.png)

**Comment by izaac** [comment]
Validated this happening in Rancher version `2.3-head (11/25/2019) 31b42402c` @deniseschannon @sangeethah

**Comment by westlywright** [comment]
Available in `2.3.25` or `latest-2.3`

**Comment by izaac** [comment]
This is now working in latest `2.3-head 31b42402c` Using default value I see the API is now setting 1.14.8 and selecting non-default value like 1.14.7 is also setting the `kubernetesVersion` value as expected.

@westlywright @sangeethah

**Comment by izaac** [comment]
Reopening. @sangeethah the issue report was for `master-head` should we also validate the fix there or should we open a separate forward port GH issue for that?

**Comment by sangeethah** [comment]
@izaac There is a  forward port issue to track this fix in master -https://github.com/rancher/rancher/issues/24239

This issue can be closed with your findings from latest v2.3-`head` should be good to close this issue - https://github.com/rancher/rancher/issues/24199#issuecomment-558419679
