### ISSUE TITLE
Annotations for Load Balancer when deploying workload into Azure

### ISSUE THREAD

**Issue by Rancheroo** [rancher/rancher#24195]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
Select a project / Switch to Project context in the GUI
Select Resources menu then Workloads
Click deploy
Fill in mandatory fields with test info
Then select the + add port button
Select Layer-4 Load Balancer

The request is for annotations to be allowed as optional for use on the Azure Load Balancers

**Result:**
Customer can deploy Load Balancers using the 'Import yaml' button, however would like to be able to do this using Workloads on the Rancher Interface

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.2
- Installation option (single install/HA): HA RKE

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 
- Machine type (cloud/VM/metal) and specifications (CPU/memory):  
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

gz#7082

**Comment by loganhz** [comment]
You could create Layer-4 Load Balancer with annotations in creating service discovery page.
