### ISSUE TITLE
Imported AKS clusters show in error.  Can we mark Imported AKS to silence alarms?

### ISSUE THREAD

**Issue by slessardjr** [rancher/rancher#24203]
**What kind of request is this (question/bug/enhancement/feature request): Enhancement/Bug**

**Steps to reproduce (least amount of steps as possible):**

1. Create AKS Cluster in Azure Portal
2. Create Cluster in Rancher, select import
3. Run kubectl command to import AKS Cluster in Rancher

**Result:**
1. Rancher will show the cluster in error.  Specifically the Controller Manager and Scheduler are shown as unhealthy.  This is already a known upstream k8s bug from rancher/rancher#23451 

**Other details that may be helpful:**
1.  If you create an AKS cluster, Rancher seems to know that it's managed and will gray out those errors and ignore. Ideally, there would be a way to annotate if the imported cluster is from a managed service so the same "feature" of ignoring the error could be used.
2.  This could affect other cloud providers EKS or GKE.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.1
- Installation option (single install/HA): HA

gz#11712

gz#12343

**Comment by cjellick** [comment]
@deniseschannon I had a user point this out at KubeCon as well. Apparently, this did not happen in v2.2, but it started happening in v2.3

**Comment by mikearruda** [comment]
Glad to hear I am not the only one facing this issue. Looking forward to the fix.

**Comment by davesykeselateral** [comment]
Yes, happening to me too.

**Comment by ThEWiZ76** [comment]
v2.3.3 same issue

**Comment by codyrancher** [comment]
I did digging to see if we could carry over the AKS Cluster fix to an AKS Import Cluster. Unfortunately there doesn't appear to be any information we can use to determine the provider of an Import Cluster. Without the provider information we can't mute these alerts without muting them for all providers.

@deniseschannon I think we either need someone from the backend to tell us a way to determine the provider or we may need to close this issue.

**Comment by iboware** [comment]
Having the same problem with the version 2.4.1

**Comment by elvishsu66** [comment]
I have this problem for a while and found this issue now. Can't UI team check out a good way to mute the alert and warning? Or check out the nodes' system info?

**Comment by slessardjr** [comment]
@codyrancher I was hoping that we could use an annotation or some configuration options to disable to monitoring of the scheduler and controller manager.  I don’t need Rancher to figure it out.  I’m more than happy to just not have an imported Managed-Kubernetes show as in error.  Is not helpful because there are times where the cluster is in error, but we ignore because the icon is always there.

**Comment by okram2000** [comment]
I don't really get why this problem was fixed a year ago for AKS and now reappears?
https://github.com/rancher/rancher/issues/17344

I have the problem with managed and imported Azure clusters.

**Comment by jonesbusy** [comment]
Same issue here on 2.4.4 with imported AKS cluster

**Comment by mschiessl** [comment]
Same issue on a similar setup (managed k8s by 3rd party cloud provider), master nodes not visible to rancher.
Just assuming this runs into an identical direction.

**Comment by spmoreno** [comment]
Same issue here on Rancher version 2.4.4 and AKS 1.16.9
![image](https://user-images.githubusercontent.com/11148132/86867026-13572500-c0a0-11ea-8444-8efd5373d279.png)

**Comment by maggieliu** [comment]
Need to keep in mind this issue: https://github.com/rancher/docs/pull/2717

**Comment by cbron** [comment]
Summary of this issue as of November '20
* We can't see the component status for controller manager or scheduler for AKS clusters, this is a bug inside AKS.
* ComponentStatus itself is being deprecated starting in 1.19, which is why AKS isn't fixing the bug.
* For Rancher created AKS clusters we simply hide these components (17344), but for imported clusters we don't know its AKS and therefore can't hide.
* In the medium/long term for 2.5.x we'll handle the deprecation of component status by transitioning to something else which would ideally also work on AKS imported clusters https://github.com/rancher/rancher/issues/28943
* The proposed (2.4 compatible) alternative is the annotation PR above. Beyond that we could also look into better identifying imported clusters.

**Comment by deniseschannon** [comment]
I'm closing this issue in favor of this one which will address this for all clusters that we detect and others can configure their status to hide it for their cluster type: https://github.com/rancher/rancher/issues/11496#issuecomment-727641496
