### ISSUE TITLE
Users should be able to directly configure alert rules through YAML

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#24215]
Part of #23239

Users should be able to deploy `PrometheusRules` directly to configure alerts as part of their deployments.

Users should also be able to use selectors when creating rules on pods, nodes, workloads etc. when not using custom metrics. Today, users can select a specific pod, or a specific node.

When an object is deployed, the project level Alert notifier should be used.

**Comment by ekristen** [comment]
I found that under the hood this is what is being done, but the default deployment is very specific to how the alerts have to be labelled for them to be pulled into the prometheus instance. Namely have to be added to the System Project (not ideal), and have to be labelled with `source: rancher-alert` (not a huge deal, but also misleading when you don't create it via the rancher ui)
