### ISSUE TITLE
Enable Thanos Endpoints

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#24214]
Enable Thanos endpoint configuration, part of rancher/rancher#23239

This PR has been provided:
https://github.com/rancher/system-charts/pull/95

Update Rancher UI enable monitoring page to make it easy to add the options outlined in the above PR.

Success Criteria:
Once enabled the Thanos sidecars are deployed.

**Comment by jiaqiluo** [comment]
Followed the steps in the PR to validate the thanos for monitoring: https://github.com/rancher/system-charts/pull/95

The following are the values I passed in when enabling the cluster monitroing, 
```
prometheus.thanos.enabled=true
prometheus.thanos.objectConfig.type=S3
prometheus.thanos.objectConfig.config.bucket=jiaqi-thanos
prometheus.thanos.objectConfig.config.region=us-west-1
prometheus.thanos.objectConfig.config.endpoint=s3.amazonaws.com
prometheus.thanos.objectConfig.config.signature_version2=false
prometheus.thanos.objectConfig.config.insecure=true
prometheus.thanos.objectConfig.config.access_key=*****
prometheus.thanos.objectConfig.config.secret_key=*****
```

Result:
- the sidecar container is deployed successfully, 
- not see any values written in the S3 bucket (may need to wait for Prometheus start sending data to the bucket)
- and the url to access to thanos is not working
```
https://server-ip/k8s/clusters/c-kjf4m/api/v1/namespaces/cattle-prometheus/services/access-thanos:10901/proxy/
https://server-ip/k8s/clusters/c-kjf4m/api/v1/namespaces/cattle-prometheus/services/access-thanos:10902/proxy/
```
<img width="732" alt="Screen Shot 2019-12-23 at 3 59 15 PM" src="https://user-images.githubusercontent.com/6218999/71384846-09a51e80-25a1-11ea-8f84-bec097775b48.png">

**Comment by jiaqiluo** [comment]
Rancher master-head 189e4337c
k8s v1.17.0
monitoring template 0.0.7

Use the same configurations as the previous comment to enable cluster monitoring with Thanos
```
prometheus.thanos.enabled=true
prometheus.thanos.objectConfig.type=S3
prometheus.thanos.objectConfig.config.bucket=jiaqi-thanos
prometheus.thanos.objectConfig.config.region=us-west-1
prometheus.thanos.objectConfig.config.endpoint=s3.amazonaws.com
prometheus.thanos.objectConfig.config.signature_version2=false
prometheus.thanos.objectConfig.config.insecure=true
prometheus.thanos.objectConfig.config.access_key=*****
prometheus.thanos.objectConfig.config.secret_key=*****
```

Results:
- see the Thanos sidecar is deployed successfully
- see the data saved to the S3 bucket 

<img width="828" alt="Screen Shot 2019-12-27 at 3 26 21 PM" src="https://user-images.githubusercontent.com/6218999/71534620-4b91d580-28bd-11ea-994f-113513788557.png">
<img width="1788" alt="Screen Shot 2019-12-27 at 3 26 28 PM" src="https://user-images.githubusercontent.com/6218999/71534621-4c2a6c00-28bd-11ea-9913-22d05e94a4ba.png">
