### ISSUE TITLE
Grafana enhancements in Rancher monitoring

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#24213]
This is part of rancher/rancher#23239 

The current implementation of Grafana in Rancher needs to be extended to allow:
Cluster Monitoring
1. As a cluster owner I can optionally allow project members to view grafana.
1. Users to bring their own dashboards/playlists via configmaps/secrets
1. Users to configure their own datasources via secrets/configmaps

Project Monitoring
1. Users to bring their own dashboards via configmaps/secrets
1. Users to configure their own datasources via secrets/configmaps

## Post Custom scrape configs for Rancher Cluster Monitoring.
1. Cluster owner should be able to specify which namespaces can add / remove dashboards for cluster monitoring dashboards.
1. Cluster owner should be able to specify which namespaces can add / remove datasources for cluster monitoring.

These are capabilities are currently possible via the existing grafana stable helm chart.

gzrancher/rancher#5697

gzrancher/rancher#4326

gzrancher/rancher#7401

gzrancher/rancher#9894

gzrancher/rancher#11143

**Comment by maggieliu** [comment]
With Monitoring v2 the ability to configure your dashboard and data sources will exist at the cluster level and not project level.

**Comment by bradenwright** [comment]
@maggieliu any idea when is Monitoring v2 going to be released?  Or is there a good way to watch for this / track. 

Also will it allow ability to configure additional dahsboards / datasources via configmaps as supported by Prometheus Operator / Grafana Chart?  https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L530

I'd like to be able to configure dashboards / datasources and alerts via configmaps so I can deploy them via Helm.

**Comment by aiyengar2** [comment]
https://github.com/rancher/rancher/issues/26549 should allow users with permissions to create ConfigMaps within certain namespaces to bring in Grafana Dashboards and Datasources. You should be able to set any custom configuration you can currently set on the Prometheus Operator / Grafana charts.

Regarding RBAC: While the configuration of Monitoring V2 will allow cluster owners to specify options in the upstream charts such as which namespaces to look at for certain CRs or Grafana ConfigMaps, cluster owners will need to set up the permissions for their own users to be able to create/modify these resources in those namespaces just like when deploying the Prometheus Operator chart.

**Comment by jiaqiluo** [comment]
The new feature of Grafana will be validated in the monitoring v2. 
This issue is closed and new issues will be opened if needed.
