### ISSUE TITLE
question:rancher apiserver timeout

### ISSUE THREAD

**Issue by playboy756** [rancher/rancher#24226]
**What kind of request is this (question/bug/enhancement/feature request):**

question

**Steps to reproduce (least amount of steps as possible):**

1,sometime,the rancher ui is very slowly and show me timeout.
2,then i login the k8s master ,run kubectl get node also show me timeout.
3,i stop  k8s_agent_cattle-node-agent-xxxx ,then the rancher ui is ok.

**Result:**

fail

**Other details that may be helpful:**

some logs
kube-apiserver logs (master01)
1125 03:26:50.902568       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:27:50.904970       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:28:50.907978       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:29:50.910781       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:30:02.355236       1 trace.go:81] Trace[810075069]: "List /apis/apps/v1/namespaces/bzy-dev/replicasets" (started: 2019-11-25 03:29:59.389642087 +0000 UTC m=+3282814.255507237) (total time: 2.965559309s):
Trace[810075069]: [2.965556386s] [2.949981435s] Writing http response done (242 items)
I1125 03:30:50.913509       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1125 03:30:55.438747       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:30:55.439447       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:30:55.439480       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:30:55.439506       1 writers.go:163] apiserver was unable to write a JSON response: write tcp 172.19.152.132:6443->172.19.152.133:4508: write: broken pipe
E1125 03:30:55.440382       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:30:55.441021       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:30:55.441187       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:30:55.441309       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:30:55.441358       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:30:55.441567       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:30:55.441630       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:30:55.447625       1 writers.go:163] apiserver was unable to write a JSON response: write tcp 172.19.152.132:6443->172.19.152.133:44198: write: broken pipe
E1125 03:30:55.480423       1 status.go:71] apiserver received an error that is not an metav1.Status: &net.OpError{Op:"write", Net:"tcp", Source:(*net.TCPAddr)(0xc011159e30), Addr:(*net.TCPAddr)(0xc011159ec0), Err:(*os.SyscallError)(0xc00e721da0)}
E1125 03:30:55.490329       1 status.go:71] apiserver received an error that is not an metav1.Status: &net.OpError{Op:"write", Net:"tcp", Source:(*net.TCPAddr)(0xc011159c80), Addr:(*net.TCPAddr)(0xc011159d10), Err:(*os.SyscallError)(0xc013ca5b60)}
E1125 03:31:03.105664       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:31:13.624013       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:31:13.624636       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:31:13.625736       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:31:13.626072       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:31:13.626399       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:31:13.626399       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:31:13.626754       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
I1125 03:31:17.279413       1 trace.go:81] Trace[1336064642]: "List /apis/apps/v1/namespaces/bzy-test/replicasets" (started: 2019-11-25 03:31:13.627016862 +0000 UTC m=+3282888.492882003) (total time: 3.652367793s):
Trace[1336064642]: [3.652365499s] [3.627616028s] Writing http response done (231 items)
I1125 03:31:50.916129       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:32:50.918473       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:33:50.921206       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:34:50.923820       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:35:50.926462       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:36:50.928991       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:37:50.931561       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:38:20.429520       1 controller.go:606] quota admission added evaluator for: deployments.apps
I1125 03:38:50.934375       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:39:50.937503       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io

kube-apiserver logs(master02)
docker logs -f --tail -n 500 k8s_agent_cattle-node-agent-8r5tr_cattle-system_84be50cf-5f0f-401b-92ed-506a450f1b33_3
docker logs -f --tail -n 500 k8s_agent_cattle-node-agent-8r5tr_cattle-system_84be50cf-5f0f-401b-92ed-506a450f1b33_3
I1125 02:53:32.933463       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1125 02:53:58.329254       1 writers.go:77] error encountered while streaming results via websocket: tls: use of closed connection
I1125 02:53:58.329394       1 trace.go:81] Trace[1093240220]: "Get /api/v1/namespaces/bzy-dev/pods/bzy-gateway-deployment-848fb9968f-hj6ql/log" (started: 2019-11-25 02:53:35.389390889 +0000 UTC m=+409952.676572841) (total time: 22.939968425s):
Trace[1093240220]: [22.939965778s] [22.936109119s] Transformed response object
I1125 02:54:32.936655       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 02:55:32.939944       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 02:56:32.942985       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 02:57:32.946068       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 02:58:07.799770       1 trace.go:81] Trace[483015214]: "Get /api/v1/namespaces/bzy-dev/pods/bzy-auth-deployment-ddfbbd9dd-b4phv/log" (started: 2019-11-25 02:57:13.465503742 +0000 UTC m=+410170.752685889) (total time: 54.334213255s):
Trace[483015214]: [54.334210239s] [54.330416212s] Transformed response object
I1125 02:58:07.799777       1 trace.go:81] Trace[599317765]: "Get /api/v1/namespaces/bzy-dev/pods/bzy-auth-deployment-ddfbbd9dd-b4phv/log" (started: 2019-11-25 02:55:41.27022219 +0000 UTC m=+410078.557404258) (total time: 2m26.529532512s):
Trace[599317765]: [2m26.529531646s] [2m26.52581999s] Transformed response object
I1125 02:58:32.949252       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1125 02:58:48.372372       1 writers.go:77] error encountered while streaming results via websocket: tls: use of closed connection
I1125 02:58:48.372639       1 trace.go:81] Trace[880941546]: "Get /api/v1/namespaces/bzy-dev/pods/bzy-auth-deployment-9bd966596-v9cpt/log" (started: 2019-11-25 02:58:09.860239662 +0000 UTC m=+410227.147421633) (total time: 38.512344086s):
Trace[880941546]: [38.512341348s] [38.508465729s] Transformed response object
E1125 02:58:48.372889       1 writers.go:77] error encountered while streaming results via websocket: tls: use of closed connection
I1125 02:58:48.373646       1 trace.go:81] Trace[1404640360]: "Get /api/v1/namespaces/bzy-dev/pods/bzy-auth-deployment-9bd966596-v9cpt/log" (started: 2019-11-25 02:58:26.257904142 +0000 UTC m=+410243.545086095) (total time: 22.115706044s):
Trace[1404640360]: [22.115704403s] [22.112384226s] Transformed response object
I1125 02:59:32.952258       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:00:32.954863       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:01:11.395917       1 trace.go:81] Trace[364874124]: "Get /api/v1/namespaces/bzy-dev/pods/bzy-auth-deployment-9bd966596-v9cpt/log" (started: 2019-11-25 02:58:36.418940917 +0000 UTC m=+410253.706122890) (total time: 2m34.976905224s):
Trace[364874124]: [2m34.976902531s] [2m34.972503196s] Transformed response object
I1125 03:01:32.958194       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:02:32.961523       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:03:18.918127       1 trace.go:81] Trace[917742574]: "Get /api/v1/namespaces/bzy-dev/pods/bzy-auth-deployment-9bd966596-cfbrp/log" (started: 2019-11-25 03:02:03.736100011 +0000 UTC m=+410461.023281963) (total time: 1m15.181978422s):
Trace[917742574]: [1m15.181975433s] [1m15.178497964s] Transformed response object
I1125 03:03:19.229983       1 trace.go:81] Trace[277684138]: "Get /api/v1/namespaces/bzy-dev/pods/bzy-auth-deployment-9bd966596-cfbrp/log" (started: 2019-11-25 03:01:19.183045574 +0000 UTC m=+410416.470227527) (total time: 2m0.046886016s):
Trace[277684138]: [2m0.046882825s] [2m0.042914766s] Transformed response object
I1125 03:03:32.964649       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:04:32.967914       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:05:32.970899       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:06:32.973903       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1125 03:07:03.184303       1 writers.go:77] error encountered while streaming results via websocket: tls: use of closed connection
I1125 03:07:03.184449       1 trace.go:81] Trace[576451924]: "Get /api/v1/namespaces/bzy-dev/pods/bzy-auth-deployment-75f7cc985-2hf6k/log" (started: 2019-11-25 03:04:25.899359252 +0000 UTC m=+410603.186541204) (total time: 2m37.285053735s):
Trace[576451924]: [2m37.285050677s] [2m37.281406406s] Transformed response object
I1125 03:07:32.976844       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1125 03:08:00.886828       1 writers.go:77] error encountered while streaming results via websocket: tls: use of closed connection
I1125 03:08:00.887016       1 trace.go:81] Trace[1201123725]: "Get /api/v1/namespaces/spt-dev/pods/spt-spm-service-deployment-6c5bb6f77f-q459x/log" (started: 2019-11-25 03:07:23.106336558 +0000 UTC m=+410780.393518509) (total time: 37.78063047s):
Trace[1201123725]: [37.780627922s] [37.77713956s] Transformed response object
I1125 03:08:32.979889       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:08:48.869359       1 trace.go:81] Trace[1238004007]: "Get /api/v1/namespaces/bzy-dev/pods/bzy-message-deployment-597b6c87d4-tcl4j/log" (started: 2019-11-25 03:07:34.688099068 +0000 UTC m=+410791.975281021) (total time: 1m14.181213486s):
Trace[1238004007]: [1m14.181210638s] [1m14.17720124s] Transformed response object
I1125 03:09:32.983136       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:10:32.986309       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:12:32.992638       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1125 03:12:57.717997       1 writers.go:77] error encountered while streaming results via websocket: tls: use of closed connection
I1125 03:12:57.718145       1 trace.go:81] Trace[1558658440]: "Get /api/v1/namespaces/bzy-dev/pods/bzy-message-deployment-5675b8fff-dfmcw/log" (started: 2019-11-25 03:08:50.802284633 +0000 UTC m=+410868.089466584) (total time: 4m6.915823804s):
Trace[1558658440]: [4m6.915821077s] [4m6.912229341s] Transformed response object
I1125 03:13:32.995444       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:14:32.998301       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:15:33.001226       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1125 03:15:56.304574       1 writers.go:77] error encountered while streaming results via websocket: tls: use of closed connection
I1125 03:15:56.304735       1 trace.go:81] Trace[62328686]: "Get /api/v1/namespaces/spt-dev/pods/spt-spm-service-deployment-6c5bb6f77f-zvgdq/log" (started: 2019-11-25 03:07:36.802534076 +0000 UTC m=+410794.089716047) (total time: 8m19.502155133s):
Trace[62328686]: [8m19.502152604s] [8m19.498336795s] Transformed response object
I1125 03:16:33.004042       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:17:33.006650       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:18:33.009247       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:19:33.012074       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:20:33.014831       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:21:33.017984       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:22:33.020832       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:23:33.025999       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:24:33.028987       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:25:33.032823       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:26:33.035873       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1125 03:27:16.988158       1 writers.go:77] error encountered while streaming results via websocket: context canceled
I1125 03:27:16.988214       1 trace.go:81] Trace[1896578254]: "Get /api/v1/namespaces/hpms-test/pods/hpms-iot-deployment-d7b575459-hhfhz/log" (started: 2019-11-25 03:26:10.108991151 +0000 UTC m=+411907.396173136) (total time: 1m6.879190199s):
Trace[1896578254]: [1m6.87918765s] [1m6.875412243s] Transformed response object
E1125 03:27:32.848916       1 writers.go:77] error encountered while streaming results via websocket: context canceled
I1125 03:27:32.848983       1 trace.go:81] Trace[116242018]: "Get /api/v1/namespaces/hpms-test/pods/hpms-iot-deployment-d7b575459-hhfhz/log" (started: 2019-11-25 03:26:30.810674412 +0000 UTC m=+411928.097856382) (total time: 1m2.038266408s):
Trace[116242018]: [1m2.038264162s] [1m2.034728628s] Transformed response object
I1125 03:27:33.038852       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1125 03:28:28.768238       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:28:29.341996       1 writers.go:77] error encountered while streaming results via websocket: tls: use of closed connection
I1125 03:28:29.342147       1 trace.go:81] Trace[1819648890]: "Get /api/v1/namespaces/hpms-test/pods/hpms-iot-deployment-d7b575459-hhfhz/log" (started: 2019-11-25 03:24:09.036740234 +0000 UTC m=+411786.323922204) (total time: 4m20.305371651s):
Trace[1819648890]: [4m20.305367863s] [4m20.301872358s] Transformed response object
I1125 03:28:33.041911       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1125 03:28:57.825125       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
I1125 03:29:33.045317       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:30:33.048249       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1125 03:30:55.437858       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
E1125 03:30:55.437858       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
I1125 03:31:33.051137       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:32:33.054204       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:33:33.056910       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:34:33.059779       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:35:33.062780       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:36:33.065662       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
I1125 03:37:33.068631       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E1125 03:38:14.265019       1 writers.go:77] error encountered while streaming results via websocket: write tcp 172.19.152.133:6443->10.42.2.4:38742: write: connection reset by peer
I1125 03:38:14.265598       1 trace.go:81] Trace[623370164]: "Get /api/v1/namespaces/bzy-dev/pods/bzy-pt-tmc-deployment-7dcf569d65-nwhzk/log" (started: 2019-11-25 03:24:37.714202529 +0000 UTC m=+411815.001384500) (total time: 13m36.551340341s):
Trace[623370164]: [13m36.551336394s] [13m36.547596229s] Transformed response object
I1125 03:38:33.071670       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io

docker logs -f --tail -500 k8s_agent_cattle-node-agent-8r5tr_cattle-system_84be50cf-5f0f-401b-92ed-506a450f1b33_5
INFO: Environment: CATTLE_ADDRESS=172.19.152.133 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM=ab11dbda6a1ca77db5f9a7a6e746b1cf34a39ede922b6ae1cf0f3b629cc6125c CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=devtest-k8s-master02 CATTLE_SERVER=https://rancher123.hhotel.com
INFO: Using resolv.conf: nameserver 172.19.152.1 nameserver 172.19.152.2 search hhotel.com options timeout:2 attempts:3 rotate single-request-reopen
INFO: https://rancher123.hhotel.com/ping is accessible
INFO: rancher123.hhotel.com resolves to 172.19.168.74
INFO: Value from https://rancher123.hhotel.com/v3/settings/cacerts is an x509 certificate
time="2019-11-25T03:36:45Z" level=info msg="Rancher agent version v2.3.2 is starting"
time="2019-11-25T03:36:45Z" level=info msg="Listening on /tmp/log.sock"
time="2019-11-25T03:36:45Z" level=info msg="Option customConfig=map[address:172.19.152.133 internalAddress: label:map[] roles:[] taints:[]]"
time="2019-11-25T03:36:45Z" level=info msg="Option etcd=false"
time="2019-11-25T03:36:45Z" level=info msg="Option controlPlane=false"
time="2019-11-25T03:36:45Z" level=info msg="Option worker=false"
time="2019-11-25T03:36:45Z" level=info msg="Option requestedHostname=devtest-k8s-master02"
time="2019-11-25T03:36:45Z" level=info msg="Connecting to wss://rancher123.hhotel.com/v3/connect with token 6wzjwxwpzzpqpfcgbcmggv48trzc2fch4sdznq7t6srl8mspgs2krt"
time="2019-11-25T03:36:45Z" level=info msg="Connecting to proxy" url="wss://rancher123.hhotel.com/v3/connect"
time="2019-11-25T03:36:45Z" level=info msg="Starting plan monitor"

rancher ui error

Error
Get https://172.19.152.133:6443/api/v1/namespaces/cattle-prometheus-p-ctchd/replicationcontrollers?timeout=30s: context deadline exceeded

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

rancher v2.3.2
k8s v 1.15.5
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
alicloud ecs
4c16G
- Kubernetes version (use `kubectl version`):
v1.15.5
```
(paste the output here)
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
- Docker version (use `docker version`):

```
(paste the output here)
```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:58:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:56:46 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by coderLinJ5945** [comment]
@playboy756 Hello, I have the same problem, how did you solve it? Is it convenient for you to tell me? Thank you for your
