### ISSUE TITLE
Docker build fails when using custom namespace ID

### ISSUE THREAD

**Issue by alen-z** [rancher/rancher#24229]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Docker daemon is running with `"userns-remap": "jenkins"` and `jenkins` looks like this:
```
# cat /etc/subuid
jenkins:1001:65536
```
While running `docker build`:
```
Sending build context to Docker daemon  6.656kB
Step 1/3 : FROM rancher/rancher:v2.3.2
v2.3.2: Pulling from rancher/rancher
22e816666fd6: Pull complete
079b6d2a1e53: Pull complete
11048ebae908: Pull complete
c58094023a2e: Pull complete
8a37a3d9d32f: Pull complete
e403b6985877: Pull complete
9acf582a7992: Pull complete
bed4e005ec0d: Pull complete
74a2e9817745: Extracting [==================================================>]  99.63MB/99.63MB
322f0c253a60: Download complete
883600f5c6cf: Download complete
ff331cbe510b: Download complete
e1d7887879ba: Download complete
5a5441e6019b: Download complete
failed to register layer: Error processing tar file(exit status 1): Container ID 1922357897 cannot be mapped to a host ID
``` 

**Result:**
Not able to create Docker image in custom namespace.

**Other details that may be helpful:**
While searching for mentioned ID:
```
root@dac8e42c8606:/var/lib/rancher# find / \( -uid 1922357897 \)  -ls 2>/dev/null
 25828794  21532 -rwxr-xr-x   1 1922357897 root     22045312 Aug 16 23:27 /usr/bin/etcd
 25828795  17272 -rwxr-xr-x   1 1922357897 root     17684608 Aug 16 23:27 /usr/bin/etcdctl
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
latest/stable/v2.3.2
- Installation option (single install/HA):
Single install

It would be great if `etcd` and `etcdctl` are in lower ID namespace. Thank you.

**Comment by caffeinism** [comment]
The same issue exists on my machine. It did not appear in v2.2.9.
