### ISSUE TITLE
How should Enabling/Disabling alerts through cluster.yml file reflect in the API ?

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#24220]
Create an RKE template revision R1 with enable_cluster_alerting:true
Launch a cluster using R1. In the API, `enableClusterAlerting` is set to true in the Applied spec and `enableClusterAlerting` is set to false at the cluster level initially
Once notifier is created, and alerts are set, `enableClusterAlerting` is set to true at the cluster level in API

Is the `enableClusterAlerting` setting at the cluster level be considered as the true setting or the setting in applied spec be considered.     

Please provide more info on the expected behavior for this `enable_cluster_alerting` field

**Comment by prachidamle** [comment]
@soumyalj  `enableClusterAlerting` setting at the cluster level should be considered as the true _state_ of alerts in the cluster.

In general the settings in the applied spec are for internal use, and should not be considered at the API level for client use. Always the cluster's spec will hold true from a user's perspective.

Now w.r.t this flag `enableClusterAlerting` being set to true via cluster.yml or via an RKE template, it does stays as `true` when the cluster is being created and provisioning. But later it will be changed to false by backend controllers  if the cluster has no  alert notifiers configured.

Thus this flag does not mean that any alerts are auto deployed in the cluster. It does not even control disabling the alerting. It only indicates whether or not cluster has any alerts configured.
