### ISSUE TITLE
最新版本的rancher 单个pods监控没有数据

### ISSUE THREAD

**Issue by xusir1** [rancher/rancher#24228]
部署了rancher:latest之后 对于单个pods 看不到使用的内存和cpu以及网络的状态，只能看到整个集群和node的状态

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

Or you can join WeChat group by adding `rancher2` if you would like to ask questions in Chinese

**Comment by xusir1** [comment]
OK  i already add rancher2 weichat group,  i hope to permit me to jion you

**Comment by xusir1** [comment]
> Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)
> 
> Or you can join WeChat group by adding `rancher2` if you would like to ask questions in Chinese

OK i already add rancher2 weichat group, i hope to permit me to jion you
