### ISSUE TITLE
question: Rancher pipeline requires administrator privileges of bitbucket code repository

### ISSUE THREAD

**Issue by 467441053** [rancher/rancher#24225]
**What kind of request is this (question):**

**Steps to reproduce (least amount of steps as possible):**
- I have created two users in bitbucket and a code repository, one account is the administrator of the code repository, the other is only read-write permission
- Then use these two accounts to the pipeline to authenticate the code repository

**Result:**
- When I use the administrator account to authenticate，rancher while list the public repository and private repository whice i have premission.
- When I use the read-write account to authenticate, rancher only list the public repository.
- Why rancher pipeline need administrator rights of code repository? I think the read-write permission should be enough.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):V2.3.2
- Installation option (HA):

**Comment by hbudde** [comment]
I think this is because the rancher pipeline installs a webhook on the repository and therefore it needs admin rights. So this is more a bitbucket specific problem?

**Comment by 467441053** [comment]
> I think this is because the rancher pipeline installs a webhook on the repository and therefore it needs admin rights. So this is more a bitbucket specific problem?

Thank you for your reply, 
I have studied your suggestion carefully and I found that Rancher does not create a webhook under any repository when list code repository.
The time for rancher to create webhook is when enable the target code repository.
So I don't think that's the reason

**Comment by gitlawr** [comment]
>To use this automation, webhook management permission is required for the repository. Therefore, when users authenticate and fetch their repositories, only those on which they have webhook management permission will be shown.

**Comment by gitlawr** [comment]
It is explained in the [docs](https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/pipelines/#pipeline-triggers):
>To use this automation, webhook management permission is required for the repository. Therefore, when users authenticate and fetch their repositories, only those on which they have webhook management permission will be shown.
