### ISSUE TITLE
Automation - Implement RBAC cases for Workloads

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#24223]
Task 1: Implement the infrastructure for implementing RBAC testing
Task 2: Add RBAC related testing cases for workloads:
- cluster member can create projects, deploy, edit and delete workloads in them, but cannot access to other projects that he has no access to in the same cluster 
- project member can deploy, edit and delete workloads in the project he has access to, but cannot access to other projects that he has no access to in the same cluster 
- project owner can deploy, edit and delete workloads in the project he has access to, but cannot access to other projects that he has no access to in the same cluster 
- Cluster owner can create new projects, and deploy, edit, delete workloads in any project in the cluster 
- Project Read-only user can not deploy new workload, edit or delete existing workloads in the project

**Comment by sangeethah** [comment]
@jiaqiluo Could you also include RBAC cases for Cluster owner and project_readonly roles?

**Comment by jiaqiluo** [comment]
@sangeethah  Sure, the issue is updated with new test cases.

**Comment by sangeethah** [comment]
Project Read-only user can not deploy new workload, edit or delete existing workloads in the project -> Can you also add the check for this user to be able to view workloads in the project he has access to , but not in other projects.
