### ISSUE TITLE
When attempting to upgrade only the primary launch config for a  service with sidekick , sidekick also gets stopped and recreated.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2422]
Server version - v0.43.0-rc2

Choose "upgrade" option for a service which has 1 sidekick. On the upgrade page , update launch config values from only primary service and click on "upgrade".

Notice that both the primary service and side kick service get upgraded.
We  should have a way to upgrade individual launch configs.

**Comment by vincent99** [comment]
Checkboxes at the top to choose which services to upgrade now.

**Comment by sangeethah** [comment]
Server version - v0.43.0-rc3

We are allowed to select services to upgrade now. I am able to upgrade only the primary service now. But attempting to upgrade all services / only sidekicks have issue which is tracked in - #2451
