### ISSUE TITLE
UI for Ping + OpenLDAP User/Group Search

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#24236]
Original Issue https://github.com/rancher/rancher/issues/24235

We will be adding another couple sections of configuration to the ping saml auth provider. we will provide the user/group search services of openldap to the ping saml provider so it will probably need all the params from the openldap auth provider.

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/24957
