### ISSUE TITLE
Each userContext gets it's own managementContext

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#24233]
When creating each userContext, scaledContext.NewManagementContext() is called which creates another managementContext causing everything in management to be duplicated. 

github.com/rancher/types/config/context.go

**Comment by dramich** [comment]
Two options to fix have been discussed.
1. Stop doing the duplication 
2. Move all user controllers to the agent

**Comment by dramich** [comment]
https://github.com/rancher/rancher/pull/25006

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 2/11

These issues re: scalability are hard to reproduce without testing at scale, so focused on regressions via automation: 

* Deployed Rancher
* Deployed multiple custom clusters
* Ran automation smoke tests and long running tests for a total of ~400 tests
* Automation runs succeeded with only a few known failures
