### ISSUE TITLE
[forwardport] Invalid K8S version is used for AKS provisioning

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#24239]
Forwardport of rancher/rancher#24199

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by izaac** [comment]
Validated working in rancher `2.4 master-head (11/26/2019) 781cd0fdc`

AKS cluster was deployed and active for the kubernetes version selected during creation. `v1.14.8` and `v1.14.7`.
