### ISSUE TITLE
Implement Rolling restart

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2423]
Sometimes apps don't dynamically refresh something, like a setting.  So a restart is the only way to upgrade. And it should be done in a rolling fashion

**Comment by demarant** [comment]
+1
Indeed a graceful rolling restart is often required in a production environment.

**Comment by demarant** [comment]
It looks like same feature request as #2330

**Comment by deniseschannon** [comment]
@demarant #2330 is related to rancher-compose, where as this issue is to track what Rancher should do with upgrades. slightly different.

**Comment by sangeethah** [comment]
Tested with latest build from master:

Rolling restart is now supported for services.  UI does not extend support for rolling restart yet and this is tracked in - #3089
