### ISSUE TITLE
ConfigMap "name.v9" is invalid: []: Too long: must have at most 1048576 characters

### ISSUE THREAD

**Issue by ByJacob** [rancher/rancher#24230]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create helm chart with a lot dependency/values in yaml file. My filewith content from `helm install --debug --dry-run` have 63K
Edit:
I am stupid... I pack previous helm packages to new, so I have helm chart who have 950 KB :C

**Result:**
Failed to install app app_name. Error: UPGRADE FAILED: ConfigMap "app_name.v9" is invalid: []: Too long: must have at most 1048576 characters

**Other details that may be helpful:**

**Environment information**
- Rancher | v2.3.2
- User Interface | v2.3.22
- Helm | v2.14.3-rancher1
- Machine | v0.15.0-rancher12-1
- Installation option single install

**Comment by georgecookeIW** [comment]
@ByJacob confirmed; I ran into the same issue.

Added the following to **.helmignore**
`*.tgz`

Re-package and it works fine.
