### ISSUE TITLE
Google SSO: Rancher fails to detect the correct redirect URL if more than one is present  

### ISSUE THREAD

**Issue by sebikul** [rancher/rancher#24257]
When configuring SSO with Google, and the OAuth credentials JSON has the following format:

```json
{
  "web": {
    "client_id": "[redacted]",
    "project_id": "[redacted]",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "[redacted]",
    "redirect_uris": [
      "https://example1.com/verify-auth",
      "https://example2.com/verify-auth"
    ],
    "javascript_origins": [
      "https://example1.com",
      "https://example2.com"
    ]
  }
}
```
Asume that both `example1.com` and `example2.com` refer to Rancher installations, where we want to share the same credentials file. When configuring SSO on domain `example1.com`, the authentication finishes successfully. However, when trying to finish the configuration on domain `example2.com`, the authentication fails with a `Bad Request` error, as the redirect URL does not match the current domain. We believe the issue is that Rancher automatically chooses the first URL out of the arrays available in the JSON file. While not wrong, it would be better to choose based on the configured `base_url`.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.2` UI: `v2.3.22` |
|Route|`global-admin.accounts.index`|

**Comment by gvilarino** [comment]
Facing this same issue

**Comment by sebikul** [comment]
This is still happening in Rancher 2.5.1. Any news here?

**Comment by bluemalkin** [comment]
I am facing the same issue in `v2.12.1`, is there a way to make it work ?
