### ISSUE TITLE
Failed to provision volume with StorageClass ** folder not found

### ISSUE THREAD

**Issue by Dante3004** [rancher/rancher#24258]
**What kind of request is this :** Question

**Steps to reproduce (least amount of steps as possible):**

Provision vsphere storage class using vsphere plugin on esxi standalone with rancher ui

**Result:**

Failed to provision volume with StorageClass "ec-stc": folder ' kubernetes' not found

--

**Environment information**
- Rancher version : 2.3.2
- Installation option : HA

**Cluster information**
- Cluster type : Vsphere
- Machine type : Metal 4 Vcpu 16 Go RAM
- Kubernetes version : 1.15

**Questions**

Cloud_provider configuration used for the cluster deployment : 

  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      global:
        insecure-flag: true
        port: '443'
        soap-roundtrip-count: 0
        user: root
        password: **********
      virtual_center:
        standalone-esxi:
      workspace:
        server: standalone-esxi
        default-datastore: datastore1
        folder: ?????
        datacenter: ha-datacenter

Unlike the vcenter we don't have any notion of a folder on a standalone esxi, being that the argument is required what should we put in this place?

Thanks in advance :)

**Comment by luthermonson** [comment]
folder is not required in the vsphere driver, just leave it blank and the default is "/": https://github.com/rancher/machine/blob/v0.15.0-rancher12/drivers/vmwarevsphere/vsphere.go#L243

@Dante3004 can you try leaving it blank? pretty sure govmomi accounts for it if it's an esxi api and not vsphere

**Comment by Dante3004** [comment]
Hello,

When I leave the field blank, the cluster provisioning fails. 
But by specifying a "/" in the folder field, it works. The correct configuration in my case is therefore:

cloud_provider:
name: vsphere
vsphereCloudProvider:
global:
insecure-flag: true
port:'443''.
soap-roundtrip-count: 0
user: root
password: **************
virtual_center:
standalone-esxi:
workspace:
server: standalone-esxi
default-datastore: datastore1
folder: **/**
datacenter: ha-datacenter

Thanks again for your help.
