### ISSUE TITLE
Pipeline clone from bitbucket SSL error

### ISSUE THREAD

**Issue by benhosmer** [rancher/rancher#24253]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

I've configured a pipeline with bitbucket. Rancher sees my repositories. When I run the pipeline though, I get the following error:
```
hudson.plugins.git.GitException: Command "git fetch --tags --progress https://bitbucket.org/myorg/myrepo.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://bitbucket.org/myorg/myrepo.git/': SSL: certificate subject name (www.myrancher.com) does not match target host name 'bitbucket.org'
```
I've changed the names for security purposes. This is a private bitbucket repository, but it's hosted with bitbucket.org, not my own server or domain.

I'm using a publicly resolveable hostname for my rancher with letsencrypt as the authority. The certificates are fine.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.2
- Installation option (single install/HA):
Single

**Comment by gitlawr** [comment]
The SSL verification is failing, can you use a hostname matching the certificate to access Bitbucket?

**Comment by benhosmer** [comment]
I edited my original, the repo is private, but it's hosted at bitbucket.org, not a private server. I don't have a certificate that matches bitbucket.org because I don't own that domain.
