### ISSUE TITLE
VPC which is part of the cloud formation stacks does not get deleted in AWS after deleting EKS clusters

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#24256]
Version: v2.3.3

Steps:
1. Create a EKS cluster in Rancher. VPC and Cloud formation stacks get created as part of the cluster 
2. Delete the EKS cluster. 
VPC which is part of the Cloud formation stacks does not get deleted in AWS after deletion. We have to manually delete the VPC.

**Comment by soumyalj** [comment]
The same issue was observed in v2.3.2

**Comment by ebauman** [comment]
I am seeing similar behavior, as well as the clusters and other resources sticking around (not just limited to VPCs). Experienced on 2.3.3

**Comment by deniseschannon** [comment]
Duplicate https://github.com/rancher/rancher/issues/17920
