### ISSUE TITLE
Constantly switching leader

### ISSUE THREAD

**Issue by joesonw** [rancher/rancher#24254]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**

Whenever Gitlab runner spawns a job pod

**Result:**

  |   |   |   |   |  
-- | -- | -- | -- | -- | --
gitlab | Normal | Killing | runner-bsvqy-1-project-1-concurrent-0dhpxn | Stopping container build | 2 minutes ago
gitlab | Normal | Killing | runner-bsvqy-1-project-1-concurrent-0dhpxn | Stopping container helper | 2 minutes ago
  | Normal | RegisteredNode | k8s-1 | Node k8s-1 event: Registered Node k8s-1 in Controller | 7 minutes ago
  | Normal | RegisteredNode | k8s-2 | Node k8s-2 event: Registered Node k8s-2 in Controller | 7 minutes ago
  | Normal | RegisteredNode | k8s-3 | Node k8s-3 event: Registered Node k8s-3 in Controller | 7 minutes ago
kube-system | Normal | LeaderElection | kube-controller-manager | k8s-1_324cf17a-8ba1-4f45-9573-c3d730dbc46f became leader | 7 minutes ago
kube-system | Normal | LeaderElection | kube-scheduler | k8s-1_d164a513-ebcb-4776-bc33-1552f8586d13 became leader | 7 minutes ago
kube-system | Normal | LeaderElection | kube-controller-manager | k8s-1_78aa6261-9053-4ae8-bf22-3e9e8c781f3b stopped leading | 8 minutes ago
gitlab | Normal | Started | runner-bsvqy-1-project-1-concurrent-0dhpxn | Started container helper | 9 minutes ago
gitlab | Normal | Created | runner-bsvqy-1-project-1-concurrent-0dhpxn | Created container build | 9 minutes ago
gitlab | Normal | Started | runner-bsvqy-1-project-1-concurrent-0dhpxn | Started container build | 9 minutes ago
gitlab | Normal | Pulled | runner-bsvqy-1-project-1-concurrent-0dhpxn | Container image "gitlab/gitlab-runner-helper:x86_64-577f813d" already present on machine | 9 minutes ago
gitlab | Normal | Created | runner-bsvqy-1-project-1-concurrent-0dhpxn | Created container helper | 9 minutes ago
gitlab | Normal | Pulled | runner-bsvqy-1-project-1-concurrent-0dhpxn | Container image "l.gcr.io/google/bazel:1.1.0" already present on machine | 9 minutes ago

**rancher/rancher goes down.**

**k8s-scheduler goes down.**

**k8s-controller-manager goes down.**

The job ran smoothly.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.2
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
k8s-1: [etcd] [Control Panel] 4C8G
k8s-2: [Worker] 4C16G
k8s-3: [Worker] 4C16G

- Kubernetes version (use `kubectl version`):

```

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by mdesarulhaque51261-svg** [comment]
JUNAEID
