### ISSUE TITLE
When I try to launch a stack from catalog, it always says "Upgrade ..."

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#2425]
I'm using v0.43.0-rc2.

When I try to launch ElasticSearch, for example, it says Upgrade Elasticsearch Stack

**Comment by sheng-liang** [comment]
I ran into this problem after I created one ElasticSearch stack, upgraded it, and deleted it. Now every launch becomes an upgrade.

**Comment by deniseschannon** [comment]
Verified with v0.43.0-rc3
