### ISSUE TITLE
About rancher cli login

### ISSUE THREAD

**Issue by xytnba** [rancher/rancher#24264]
**What kind of request is this (question/bug/enhancement/feature request):**
bug?

**Steps to reproduce (least amount of steps as possible):**
![image](https://user-images.githubusercontent.com/49108263/69701394-d4371d80-1127-11ea-8556-c5bcd68a3f95.png)
I run in node by following the commands:
1. `rancher login https://myip:v3 -t token:secret`
2. return 
```
FATA[0002] Bad response statusCode [401]. Status [401 Unauthorized]. Body: [message=clusterID does not match] from [https://my_ip/v3] 
```
But if I set this (look at pic)
![image](https://user-images.githubusercontent.com/49108263/69701592-3e4fc280-1128-11ea-8746-d2a5f254fca1.png)
It was successful 
```
Do you want to continue connecting (yes/no)? yes
NUMBER    CLUSTER NAME   PROJECT ID        PROJECT NAME   PROJECT DESCRIPTION
1         test2          c-7xqz2:p-2c279   System         System project created for the cluster
2         test2          c-7xqz2:p-vgb5t   Default        Default project created for the cluster
3         test1          c-cplvw:p-gjx7h   Default        Default project created for the cluster
4         test1          c-cplvw:p-rvhnl   System         System project created for the cluster
5         mycluster      c-lmvsp:p-49h7g   Default        Default project created for the cluster
6         mycluster      c-lmvsp:p-gc7hp   System         System project created for the cluster
Select a Project:4
INFO[0009] Saving config to /home/xieyt/.rancher/cli2.json 
root@debian106:~$ rancher nodes
ID                       NAME        STATE     POOL      DESCRIPTION
c-cplvw:m-414529b01416   debian106   active              
```
I dont know how to fix it.
Does anyone has the same problem when use rancher cli?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
```
v2.3.2
```
- Installation option (single install/HA):
```
single install
```

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
```
Custom
```
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
```
VM
```
- Kubernetes version (use `kubectl version`): 

```
v1.16.2
```

- Docker version (use `docker version`):
```
19.03.5
```

**Comment by superseb** [comment]
Sounds the same as https://github.com/rancher/rancher/issues/18639
