### ISSUE TITLE
Support self-signed certificates for notification targets

### ISSUE THREAD

**Issue by briankintz** [rancher/rancher#24263]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Steps to reproduce (least amount of steps as possible):**

1. Add a Slack notifier (type not important)
1. Enter a URL that uses a self signed certificate
1. Test
1. Save

**Result:**

1. Test works (→ Rancher itself trusts the CAs)
1. Actual alert results in an x509 certificate error in the alertmanager pod

**Other details that may be helpful:**

Very similar to #17885 (more details about the relevant alertmanager config can be found there).

**Environment information**

- Rancher version: 2.3.2
- Single and HA installation

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24272
