### ISSUE TITLE
Apps stuck deploying

### ISSUE THREAD

**Issue by amagura** [rancher/rancher#24260]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. Activate project monitoring.
2. Wait for the availability bar to go completely green
3. Try both endpoints (grafana and prometheus)
4. Click on the app and ensure that everything is marked as active.  

**Result:**
The app (project-monitoring) seems fully functional, everything belonging to the app is marked active, but the app itself is still marked as deploying.  

**Other details that may be helpful:**
The app can be brought out of a deploying state by upgrading it.  Reinstalling it by deactivating monitoring and then re-enabling it does not bring the app out of a deploying state.  This is also happening with my cluster's nginx-ingress app. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0/v.0.15.0-rancher12-1 (machine)
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud, 8 vcpus and 16 GB.
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:57:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by amagura** [comment]
This seems to no longer be an issue after upgrading to Rancher v2.3.2

**Comment by erSitzt** [comment]
I have this issue in 2.4.7

![image](https://user-images.githubusercontent.com/1625376/92216085-1c912200-ee96-11ea-96ca-706b11654c0f.png)
