### ISSUE TITLE
"Unknown question type: service" when launch Logspout from catalog

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#2426]
See screenshot:

![logspout catalog](https://cloud.githubusercontent.com/assets/9485278/10712941/4e23b5e6-7a5e-11e5-875a-ea0d4c329a76.png)

**Comment by sangeethah** [comment]
Same issue is seen when adding "Kibana" and "log stash" templates as well.

**Comment by vincent99** [comment]
These require a UI change that isn't merged yet, https://github.com/rancher/ui/pull/286 .

**Comment by sangeethah** [comment]
Tested with server version - V0.43.0-rc3

When creating a stack from logspout , we are presented with a list of services to choose from for - LOGGING TARGET LINK field. When we choose an existing logstash-collector service , we are allowed to create the stack and start the services successfully.
