### ISSUE TITLE
APIVersions definition error in system-chart

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#24262]
Mismatched APIVersions are defined in the _helpers.tpl file. Mainly in all versions of rancher-monitoring and rancher-logging. 
**Such as：**

https://github.com/rancher/system-charts/blob/52e022b1f558fa07ca6867973f2da7a8f286e26f/charts/rancher-logging/0.1.1/templates/_helpers.tpl#L6

https://github.com/rancher/system-charts/blob/52e022b1f558fa07ca6867973f2da7a8f286e26f/charts/rancher-monitoring/v0.0.3/templates/_helpers.tpl#L79

**Comment by xiaoluhong** [comment]
@aiwantaozi  @thxCode

**Comment by loganhz** [comment]
Monitoring one has been fixed in 0.0.7

**Comment by loganhz** [comment]
logging will be fixed in https://github.com/rancher/system-charts/pull/141
