### ISSUE TITLE
BugFix - EKS - eks.%.amazonaws.com/eks.%.amazonaws.com.cn added to domain whitelist

### ISSUE THREAD

**Issue by dstockton** [rancher/rancher#24277]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug (when using new AWS SDK)

**Steps to reproduce (least amount of steps as possible):**
Attempt to create and update an EKS cluster

**Result:**
FAIL: Cluster fails with an error
SUCCESS: Cluster succeeds

**Other details that may be helpful:**
https://github.com/rancher/rancher/pull/24158/files#diff-3dda985564938bb62acd5b2d96e45aa0R69

**Comment by deniseschannon** [comment]
@dstockton This change doesn't make sense to me. The place that you have added whitelisting EKS domains is where our node templates (i.e. EC2) looks for stuff. The code that calls this section would never and shouldn't have access to EKS. Can you remove the related code out of the PR ?

**Comment by dstockton** [comment]
Fair point, where do you whitelist domains for kontainer-engine traffic?
