### ISSUE TITLE
Improvement - EKS - SessionToken marked as private credential

### ISSUE THREAD

**Issue by dstockton** [rancher/rancher#24276]
**What kind of request is this (question/bug/enhancement/feature request):**
New Feature (PRd already)

**Steps to reproduce (least amount of steps as possible):**
Create a new EKS cluster using a session token
View the cluster object in the API

**Result:**
FAIL: Session token is visible
SUCCESS: Session token is hidden

**Other details that may be helpful:**
https://github.com/rancher/rancher/pull/24158/files#diff-3dda985564938bb62acd5b2d96e45aa0R30

**Comment by kinarashah** [comment]
Thanks for the PR! 

https://github.com/rancher/rancher/pull/24158#discussion_r357491003
