### ISSUE TITLE
Flaky test: test_app_namespace_annotation

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#24273]
=================================== FAILURES ===================================
--
793 | ________________________ test_app_namespace_annotation _________________________
794 | [gw3] linux -- Python 3.7.5 /go/src/github.com/rancher/rancher/tests/integration/.tox/py37/bin/python3.7
795 |  
796 | admin_pc = <suite.conftest.ProjectContext object at 0x7fd167566c90>
797 | admin_mc = <suite.conftest.ManagementContext object at 0x7fd167b7ced0>
798 |  
799 | def test_app_namespace_annotation(admin_pc, admin_mc):
800 | client = admin_pc.client
801 | ns = admin_pc.cluster.client.create_namespace(name=random_str(),
802 | projectId=admin_pc.
803 | project.id)
804 | wait_for_template_to_be_created(admin_mc.client, "library")
805 | app1 = client.create_app(
806 | name=random_str(),
807 | externalId="catalog://?catalog=library&template=mysql&version=0.3.7"
808 | "&namespace=cattle-global-data",
809 | targetNamespace=ns.name,
810 | projectId=admin_pc.project.id,
811 | )
812 | wait_for_workload(client, ns.name, count=1)
813 |  
814 | external_id = "catalog://?catalog=library&template=wordpress" \
815 | "&version=1.0.5&namespace=cattle-global-data"
816 | app2 = client.create_app(
817 | name=random_str(),
818 | externalId=external_id,
819 | targetNamespace=ns.name,
820 | projectId=admin_pc.project.id,
821 | )
822 | wait_for_workload(client, ns.name, count=3)
823 | ns = admin_pc.cluster.client.reload(ns)
824 | ns = wait_for_app_annotation(admin_pc, ns, app1.name)
825 | ns = wait_for_app_annotation(admin_pc, ns, app2.name)
826 | client.delete(app1)
827 | wait_for_app_to_be_deleted(client, app1)
828 |  
829 | ns = admin_pc.cluster.client.reload(ns)
830 | assert app1.name not in ns.annotations['cattle.io/appIds']
831 | assert app2.name in ns.annotations['cattle.io/appIds']
832 |  
833 | client.delete(app2)
834 | wait_for_app_to_be_deleted(client, app2)
835 | ns = admin_pc.cluster.client.reload(ns)
836 | > assert 'cattle.io/appIds' not in ns.annotations
837 | E assert 'cattle.io/appIds' not in {'cattle.io/appIds': '', 'cattle.io/status': '{"Conditions":[{"Type":"InitialRolesPopulated","Status":"True","Message"...":"True","Message":"","LastUpdateTime":"2019-11-27T15:46:41Z"}]}', 'lifecycle.cattle.io/create.namespace-auth': 'true'}
838 | E + where {'cattle.io/appIds': '', 'cattle.io/status': '{"Conditions":[{"Type":"InitialRolesPopulated","Status":"True","Message"...":"True","Message":"","LastUpdateTime":"2019-11-27T15:46:41Z"}]}', 'lifecycle.cattle.io/create.namespace-auth': 'true'} = {'actions': {'move': 'https://172.17.0.7:8443/v3/cluster/local/namespaces/random-37256-1574869600?action=move'}, 'anno...'transitioning': 'no', 'transitioningMessage': '', 'type': 'namespace', 'uuid': '1aa69f01-112d-11ea-8500-0242ac110007'}.annotations
839 |  
840 | test_app.py:223: AssertionError

https://drone-publish.rancher.io/rancher/rancher/1787/2/2
https://drone-publish.rancher.io/rancher/rancher/1785/2/2
https://drone-pr.rancher.io/rancher/rancher/5567/1/2

**Comment by dramich** [comment]
https://drone-pr.rancher.io/rancher/rancher/5636/2/2

**Comment by brendarearden** [comment]
https://drone-pr.rancher.io/rancher/rancher/5828/2/2
https://drone-pr.rancher.io/rancher/rancher/5826/2/2

**Comment by dramich** [comment]
Appears to be fixed.
