### ISSUE TITLE
Feature - AKS - Auto-Scaling

### ISSUE THREAD

**Issue by dstockton** [rancher/rancher#24278]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement
New Feature (PR ready)

**Steps to reproduce (least amount of steps as possible):**
Using the terraform provider, you can now create an AKS cluster that supports auto-scaling.

**Result:**
Azure Cluster can auto-scale.

**Other details that may be helpful:**
https://github.com/rancher/kontainer-engine/pull/200/files#diff-fdee2f189d794fc3e135129d93b4d373
https://github.com/terraform-providers/terraform-provider-rancher2/pull/185/files#diff-517d7d105ec5181bb804b1f010bdfff2

**Comment by deniseschannon** [comment]
@dstockton Can you confirm that this is an optional field and by default, it's false?

**Comment by dstockton** [comment]
I can; it’s line 327
