### ISSUE TITLE
service upgrade API does not allow to adding new sidekick services / removing existing ones.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2428]
Server version - v0.43.0-rc2

Currently Service upgrade API does not allow to adding new sidekick services / removing existing ones.

It would be good to provide support for being able to add new sidekick services / removing existing ones from a service.

**Comment by alena1108** [comment]
@sangeethah lets chat about the use cases to test once in the office. Only API support for now :)

**Comment by sangeethah** [comment]
Tested with rancher server version - v1.2.0-pre4-rc4 using rancher-compose:

All the below use cases work as expected, except 4:

1. Start a service with 2 sidekicks.Add another sidekick as part of upgrade. Confirm upgrade.
2. Start a service with 2 sidekicks.Add another sidekick as part of upgrade.Roll back.
3. Start a service with 2 sidekicks.Remove one of the existing sidekick as part of upgrade. Confirm upgrade.
4. Start a service with 2 sidekicks.Remove one of the existing sidekick as part of upgrade. Rollback -https://github.com/rancher/rancher/issues/6380

**Comment by sangeethah** [comment]
UI support for this feature is tracked in - https://github.com/rancher/rancher/issues/6381
