### ISSUE TITLE
Bug-Service Discovery is not accepting dot characters

### ISSUE THREAD

**Issue by santhakumarrajasekar** [rancher/rancher#24283]
*Bug-Service Discovery is not accepting dot characters

Steps to Reproduce 
Click on Service Discovery -> Add Record
enter dev.api.internal.test.net
dev. . sit. prod.<api-name>.<internal-dns>
Click on Create

Add Record is not accepting . ( dot ) characters

Expected to add the DNS names as part of service discovery for aliases and for apis dns.

Result:

"Name" contains an invalid character: .

|Versions|Rancher `v2.1.6` UI: `v2.1.19` |
|Route|`authenticated.project.dns.index`|

**Comment by loganhz** [comment]
Can you try to create what you want in k8s YAML and post it here, please?

**Comment by vincent99** [comment]
Services create new DNS entries of the form `<name>.<namespace>.svc.<cluster-domain>`.  Names cannot create dots.  Services are not a mechanism for mapping arbitrary FQDNs to a value.  You can do that for a workload with additional hostfile entries (`hostAliases`).
