### ISSUE TITLE
Feature - EKS - Separate ASGs per subnet (for AZ aware auto-scaling)

### ISSUE THREAD

**Issue by dstockton** [rancher/rancher#24286]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature - EKS - Separate ASGs per subnet (for AZ aware auto-scaling)

**Steps to reproduce (least amount of steps as possible):**
Create an EKS cluster using multiple worker subnets

**Result:**
SUCCESS: Cluster is created and the CloudFormation stack uses separate ASGs (one per subnet) - this allows you to use the auto-scaling feature and be aware of multiple AZs when scaling (the previous behaviour is one single ASG which means you have no control over the AZ that's expanded)
FAIL: Cluster does not work

**Other details that may be helpful:**
https://github.com/rancher/kontainer-engine/pull/200/files#diff-c18744328cdc32c74aa39b295238b3fcR517

**Comment by deniseschannon** [comment]
@dstockton Can you confirm that this is optional and doesn't change the default behavior today? 

Should there be a related terraform provider change along with this?

**Comment by dstockton** [comment]
Yes and yes there is https://github.com/terraform-providers/terraform-provider-rancher2/pull/185#discussion_r349024936
