### ISSUE TITLE
Feature - GKE - Multi-zone (aka regional) cluster support

### ISSUE THREAD

**Issue by dstockton** [rancher/rancher#24288]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature - GKE - Multi-zone (aka regional) cluster support

**Steps to reproduce (least amount of steps as possible):**
Create a GKE cluster that spans multiple zones (aka regional cluster)

**Result:**
SUCCESS: Cluster starts
FAIL: Cluster does not start

**Other details that may be helpful:**
https://github.com/rancher/kontainer-engine/pull/200/files#diff-1b1773a05de2c19958b9d2ac7d885b4cR1016

**Comment by deniseschannon** [comment]
@dstockton Can you confirm this is optional and doesn't change default behavior?

**Comment by dstockton** [comment]
Yes
