### ISSUE TITLE
Bug - kubecfg only works when rancher is available on https://localhost

### ISSUE THREAD

**Issue by dstockton** [rancher/rancher#24280]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug - kubecfg only works when rancher is available on https://localhost
PR ready

**Steps to reproduce (least amount of steps as possible):**
Run rancher where it's unavailable on https://localhost
Attempt to get the kubecfg file

**Result:**
FAIL: Can't get file
SUCCESS: You can get the file!

**Other details that may be helpful:**
https://github.com/rancher/rancher/pull/24158/files#diff-edacc51169cc137382b7767f83773411R457

**Comment by deniseschannon** [comment]
@dstockton How/when are you hitting this use case? We would want more details on how to reproduce.

**Comment by dstockton** [comment]
If you deploy rancher in a way that means it’s not available on https://localhost:443 then you will hit this bug. For testing purposes, you could run rancher in it’s docker container format then remove the localhost entry from /etc/hosts.

You will see an error like the one below on failure during provisioning a cluster and attempting to deploy a helm chart...
FYI if you provision via Rancher you may notice in the web UI a message like:
```
Exit status 1, unable to recognize "management-statefile_path_redacted": Get https://localhost:443/k8s/clusters/c-lh9bm/api?timeout=32s: remote error: tls: internal error
```
