### ISSUE TITLE
Feature - EKS - Option to manage security groups outside of Rancher (e.g. when wrapped with Terraform)

### ISSUE THREAD

**Issue by dstockton** [rancher/rancher#24285]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature - EKS - Option to manage security groups outside of Rancher (e.g. when wrapped with Terraform)

**Steps to reproduce (least amount of steps as possible):**
Create appropriate SGs outside of Rancher

**Result:**
SUCCESS: Cluster succeeds in using externally managed SGs
FAIL: Cluster does not provision

**Other details that may be helpful:**
https://github.com/terraform-providers/terraform-provider-rancher2/pull/185/files#diff-8ff886122dea219642c3089e474409a0R23
https://github.com/terraform-providers/terraform-provider-rancher2/pull/185/files#diff-8ff886122dea219642c3089e474409a0R26
https://github.com/rancher/kontainer-engine/pull/200/files#diff-193f5e744cfdca5a8b1c37da968623f3R161

**Comment by deniseschannon** [comment]
@dstockton Can you give more details on what this means? How are these security groups managed outside of Rancher? or where are they being created?

**Comment by dstockton** [comment]
If your organisation wants to manage their own security groups - through any method other than hidden away in rancher- then you can set this flag and rancher will not create or alter the SGs, it will only attach the SGs passed in.

**Comment by dstockton** [comment]
The “where are they being managed” answer is up to the user. In our organisations case, it’s via terraform code

**Comment by cloudnautique** [comment]
OK, cool, so if I have my SGs created outside of Rancher through some other process, these security groups will be applied unmodified to the cluster? 

Would it address: #22910

**Comment by dstockton** [comment]
Yes - sorry, I’ve opened a duplicate issue (but the PR/code resolves it)
