### ISSUE TITLE
Bug - EKS - STS token handling (e.g. update creds after expired tokens)

### ISSUE THREAD

**Issue by dstockton** [rancher/rancher#24290]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug - EKS - STS token handling (e.g. update creds after expired tokens)

**Steps to reproduce (least amount of steps as possible):**
Use the API to update EKS cluster ACCESS/SECRET/TOKEN

**Result:**
Stored AWS creds are updated

**Other details that may be helpful:**
https://github.com/rancher/kontainer-engine/pull/200/files#diff-193f5e744cfdca5a8b1c37da968623f3R1054

**Comment by deniseschannon** [comment]
@dstockton We would like to move towards using cloud credentials for hosted k8s providers (like we changed for our node templates). Would it be possible to take the changes related to this out of the PR?

**Comment by dstockton** [comment]
I could but it would mean rancher can’t use tokens effectively for EKS until you merge another PR implementing the move to cloud credentials?
Unless you have that PR ready to merge it feels a little counter-productive to want to avoid this fix?
