### ISSUE TITLE
EKS support for ca-central-1

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#24299]
Add support for new zone ca-central-1 

UI also needs to be updated [here](https://github.com/rancher/ui/blob/master/lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js). sa-east-1 is also missing from that list.

**Comment by dramich** [comment]
And update all the AMIs

**Comment by soumyalj** [comment]
Tested with Rancher server v2.3.4-rc3. 
Created a EKS cluster using UI in Ca-Central region. Cluster creation was successful. It was verified that the Cluster landed in the Ca-Central region. 
<img width="1685" alt="Screen Shot 2019-12-13 at 2 40 53 PM" src="https://user-images.githubusercontent.com/18536626/70837207-a7396a80-1db7-11ea-8d4e-b95dc7090e81.png">

API snippet:
```
"amazonElasticContainerServiceConfig": {
"accessKey": "abcdef",
"ami": "",
"associateWorkerNodePublicIp": true,
"desiredNodes": 1,
"displayName": "",
"driverName": "amazonelasticcontainerservice",
"instanceType": "m5.large",
"keyPairName": "",
"kubernetesVersion": "1.14",
"maximumNodes": 1,
"minimumNodes": 1,
"nodeVolumeSize": 20,
"region": "ca-central-1",
"serviceRole": "",
"sessionToken": "",
"subnets": null,
"userData": "#!/bin/bash\nset -o xtrace\n/etc/eks/bootstrap.sh ${ClusterName} ${BootstrapArguments}/opt/aws/bin/cfn-signal --exit-code $? --stack  ${AWS::StackName} --resource NodeGroup --region ${AWS::Region}",
"virtualNetwork": ""
},


```
Creation of workloads was fine and the cluster was active and functional .
