### ISSUE TITLE
Missing icons for Jenkins catalog.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2429]
Server versin v0.43.0-rc2

<img width="299" alt="screen shot 2015-10-24 at 3 32 37 pm" src="https://cloud.githubusercontent.com/assets/4266958/10713108/12cae544-7a65-11e5-9143-8df71d20f6ae.png">

**Comment by cloudnautique** [comment]
It's been pulled from catalog... Will go back shortly...

**Comment by sangeethah** [comment]
Able to see the jenkins icons with latest rancher/rancher-catalog.
