### ISSUE TITLE
SAML/Keycloak - An unknown error occured while attempting to login

### ISSUE THREAD

**Issue by chuegel** [rancher/rancher#24297]
**What kind of request is this (question/bug/enhancement/feature request):**
unclear yet

**Steps to reproduce (least amount of steps as possible):**
Configure Keycloak as described in the docs here https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/keycloak/
Also User Federation (LDAP) is configured and groups are mapped correctly  into KC.

KC config:
<img width="805" alt="Screenshot 2019-11-27 at 19 00 16" src="https://user-images.githubusercontent.com/6955465/69751137-baf59780-114e-11ea-9e46-9c68f3386275.png">

Mappers:
<img width="966" alt="Screenshot 2019-11-27 at 19 02 44" src="https://user-images.githubusercontent.com/6955465/69751150-c5179600-114e-11ea-9087-c8fde532be08.png">

Rancher:
<img width="1246" alt="Screenshot 2019-11-27 at 19 48 08" src="https://user-images.githubusercontent.com/6955465/69751217-ed06f980-114e-11ea-8c5f-d172c2ed2ddd.png">

**Result:**
I can authenticate against Keycloak but get an 403 error when redirecting back to rancher:

`An unknown error occured while attempting to login. Please contact your system administrator.`

I've enable debugging like described here: https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-enable-debug-logging and found this line:

`[ERROR] SAML: User does not have access <nil>`

**Other details that may be helpful:**
To exclude some misconfiguration on KC side, I've started a new rancher container via:

`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:v2.3.2`

and configured the same values as described above and it works as expected.
So the question is, what went wrong in the HA rancher installation? 

I must mention that rancher was deployed with helm and constantly updated from 2.2.x

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.3.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`): v1.14.1

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:26:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by ApolloDS** [comment]
Exactly same problem here.
One configured keycloak will not configure again even when the settings are correct.
I also get

> [ERROR] SAML: User does not have access <nil>

**Comment by ApolloDS** [comment]
Figured it out!
Go to Rancher API: https://<rancher-host>/v3/keyCloakConfigs/keycloak
and change with accessMode with "edit" from "required" to "unrestricted"
Then you can again setup SAML and it works.

**Comment by huegelc** [comment]
@ApolloDS thanks for the workaround but it still remains a bug though
