### ISSUE TITLE
[ERROR] watcher error unable to decode an event from the watch stream

### ISSUE THREAD

**Issue by guocaifeng** [rancher/rancher#24309]
rancher/rancher:stable   2.3.2

cluster create successful

but  Errors have been reported in the log

2019/11/28 16:12:35 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/28 16:12:35 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/11/28 16:12:35 [ERROR] watcher error unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)

Why the above problems ？？？？

**Comment by superseb** [comment]
Fixed in https://github.com/rancher/rancher/issues/23957
