### ISSUE TITLE
Not able to launch stack with Jenkins template.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2430]
Server version - v0.43.0-rc2

Try to create a stack using jenkins template.
Clicking on "Create" button does nothing.
<img width="922" alt="screen shot 2015-10-24 at 3 35 21 pm" src="https://cloud.githubusercontent.com/assets/4266958/10713116/7855953a-7a65-11e5-9bf1-8b42a2bcdf62.png">

**Comment by rancherdev** [comment]
Able to launch stack with Jenkins template with the latest rancher/rancher-catalog.
