### ISSUE TITLE
Feature - Openstack Node Template - Block device mapping

### ISSUE THREAD

**Issue by Jabbl** [rancher/rancher#24319]
Nodes created through rancher always use default OpenStack block-storage, as the template lacks any parameters to configure what type of storage you want to use.\
Openstack has a parameter when creating nodes called `block-device-mapping` which allows the block-storage to be configured before the node is started, but configuration of this parameter is missing in the node template.

[Link to OpenStack docs on node creation](https://docs.openstack.org/python-openstackclient/pike/cli/command-objects/server.html#server-create)

This is especially problematic when configuring etcd-nodes, as they would benefit greatly from SSD-storage, but the cloud provider defaults to hdd which thereby severely reduces the performance of the etcd-cluster.

gz#10110

**Comment by Pure-AdamuKaapan** [comment]
+1 on this, this is currently blocking us from using the OpenStack node templates as our OpenStack admins really really don't want us using the default/on-host storage. I would be willing to add this option as a side project, I just don't know where to begin.

**Comment by Pure-AdamuKaapan** [comment]
After some digging, I finally figured out the order that things will have to happen in:
* All of the parameters in the UI are defined in the main rancher project(s), haven't dug into that too far yet
* All of the actual node provisioning is handled at https://github.com/rancher/machine/tree/master/drivers/openstack, where we can add some flags to select the volume type. However, this file passes create flags into...
* https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/requests.go, but this file currently doesn't have the volume type flag.

Essentially, there will first have to be a PR into GopherCloud, and then this will have to be updated in the rancher machine driver, and then there will need to be updates into the main rancher code.

**Comment by Pure-AdamuKaapan** [comment]
I stand somewhat corrected: looks like the volume type functionality is already implemented in GopherCloud by https://github.com/gophercloud/gophercloud/pull/1690. Poking around to see how hard it would be to implement...

**Comment by qkrtjddlsgh** [comment]
Is there a way to use Openstack Block device mapping and BootFromVolume in Rancher 2.X?

I'm using rancher/rancher:latest docker image.

Thank you.

**Comment by davidburge1** [comment]
@qkrtjddlsgh The short answer has been no, not right now with nodetemplates.  The suggestion given to me was to use Terraform to provision nodes using the openstack provider and then use those nodes to create a custom cluster using the rancher2 Terraform provider.  I hope this helps.

**Comment by Pure-AdamuKaapan** [comment]
@Jabbl FYI, this is being addressed in rancher/machine#93. Not sure when it'll make it into a Rancher release.

**Comment by davidburge1** [comment]
Thank you
