### ISSUE TITLE
Fluentd missing first entries

### ISSUE THREAD

**Issue by jaccoh** [rancher/rancher#24318]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Start a new deployment and you'll see the fluentd tail will pick up the file within 60 seconds and start monitoring the file from that point. However Rancher doesn't set 'read_from_head' 'true'. Default upstream is 'false'.

**Result:**
Log entries in new files, before they got detected by fluentd in /var/log/containers/*.log, are skipped.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.15.5

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:50:54 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by jaccoh** [comment]
It was assigned? any reason its now not assigned again? :D

**Comment by panlith** [comment]
Worth to mention here based on [docs](https://docs.fluentd.org/input/tail#read_from_head):

`When this is true, in_tail tries to read a file during start up phase. If target file is large, it takes long time and starting other plugins isn't executed until reading file is finished.`

That would be something to take into account for cases when large files are read and potential impact especially on systems under high utilization.

**Comment by taka-yamamoto** [comment]
I understand the concern, but since we are running a relatively short-running batch job on Rancher, it is problematic that we may not be able to get the Logs up to 60 seconds after the container starts.
Also, up to Rancher 2.2.x could be used without any problem, but fluentd at that time does not match Elasticsearch 7.x, so it can not be said that it is not necessary to upgrade the version.

Ideally, I want a switch to switch read_from_head between true and false, or at least a UI that can be added to Config.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/25048

**Comment by izaac** [comment]
Testing was done around #25048 including an scenario to cover the `read_from_head: true` configuration:

https://github.com/rancher/rancher/issues/25048#issuecomment-593505436
