### ISSUE TITLE
cattle-cluster-agent pod CrashLoopBackOff

### ISSUE THREAD

**Issue by mariusstaicu** [rancher/rancher#24311]
**What kind of request is this (question/bug/enhancement/feature request):**
Question / Bug

**Steps to reproduce (least amount of steps as possible):**
I'm trying to setup a k8s cluster with rancher 2.3.3 (2.3.0, 2.3.2 all the same).
3 cp / etcd nodes
4 worker nodes 
all running ubuntu 18.04 in VMs / docker 19.03.5.

I create the k8s cluster, register the custom nodes described above, network plugin - canal with no isolation (same issues with flannel and calico), k8s version: 1.16.3-rancher-1 (same issues with older k8s versions).

**Result:**

everything in System project is green except cattle-cluster-agent

logs:
```bash
INFO: Environment: CATTLE_ADDRESS=10.42.2.2 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-7c6fcf58d5-qvl5w CATTLE_SERVER=https://rancher.mydomain.org
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local esol-prime options ndots:5
ERROR: https://rancher.mydomain.org/ping is not accessible (Could not resolve host: rancher.mydomain.org)
```
**Other details that may be helpful:**
https://rancher.mydomain.org is publicly accessible over internet
Tried to search similar issues with cattle-cluster-agent not starting for this reason in the past, suggested fixes to change URL to https://rancher did not work.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.3
- Installation option (single install/HA):
singleinstall

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by dan-evolvere** [comment]
can you see the core-dns and rke-coredns-addon-deploy-job running/ran successfully? Can you curl the url from the node?

Is there some kind of security group or proxy config on the web end?

**Comment by mariusstaicu** [comment]
core-dns running successful on two instances
```bash
.:53
2019-11-28T12:09:44.258Z [INFO] plugin/reload: Running configuration MD5 = 68ad62e82bb7a01ce4a04dd06bd0bf2c
2019-11-28T12:09:44.258Z [INFO] CoreDNS-1.6.2
2019-11-28T12:09:44.258Z [INFO] linux/amd64, go1.12.8, 795a3eb
CoreDNS-1.6.2
linux/amd64, go1.12.8, 795a3eb
```

rke-coredns-addon-deploy-job is also running successfully

```bash
serviceaccount/coredns created
clusterrole.rbac.authorization.k8s.io/system:coredns created
clusterrolebinding.rbac.authorization.k8s.io/system:coredns created
configmap/coredns created
deployment.apps/coredns created
service/kube-dns created
deployment.apps/coredns-autoscaler created
serviceaccount/coredns-autoscaler created
clusterrole.rbac.authorization.k8s.io/system:coredns-autoscaler created
clusterrolebinding.rbac.authorization.k8s.io/system:coredns-autoscaler created
```

curl to that address works from each of the controller and worker nodes, so there's no problem there. 
No security group or proxy on the rancher machine afaik, websocket connection seems to be working properly if that info helps.
Also, each of worker k8s nodes have both public and private ips, public interface is firewalled and allows only 443,80, and some 30000+ ports for node ports. Each controller + etcd node has only private ip. Traffic is unrestricted on private ip, I expect nodes to communicate between each other using internal ip.

**Comment by mariusstaicu** [comment]
walking through the rancher DNS troubleshooting document, I can see another thing that is not working properly:

```bash
export DOMAIN=www.google.com; echo "=> Start DNS resolve test"; kubectl get pods -l name=dnstest --no-headers -o custom-columns=NAME:.metadata.name,HOSTIP:.status.hostIP | while read pod host; do kubectl exec $pod -- /bin/sh -c "nslookup $DOMAIN > /dev/null 2>&1"; RC=$?; if [ $RC -ne 0 ]; then echo $host cannot resolve $DOMAIN; fi; done; echo "=> End DNS resolve test"
=> Start DNS resolve test

command terminated with exit code 1
192.168.40.31 cannot resolve www.google.com
command terminated with exit code 1
192.168.40.35 cannot resolve www.google.com
=> End DNS resolve test

```

**Comment by mariusstaicu** [comment]
cattle-cluster-agent resolv.conf does not look right, it is as if cluster provisioning is not considering that ubuntu is working with systemd-resolved. 

resolv.conf from a pod that has external access to interned:
```bash
cat /etc/resolv.conf 
nameserver 192.168.40.10
nameserver 192.168.40.11
search prime
```
resolv.conf from cattle-cluster-agent:
```bash
cat /etc/resolv.conf
nameserver 10.43.0.10
search cattle-system.svc.cluster.local svc.cluster.local cluster.local prime
options ndots:5
```
Is this normal ?

**Comment by mariusstaicu** [comment]
I used all the combinations possible: different rancher versions, different k8s versions, different network plugins, different configuration for nodes (w/wo external ips) different firewall configurations (even dropped entirely the firewall). The problem is persistent. The original rancher setup on the same servers worked without problems. Started having this problem after upgrading rancher to versions > 2.2.8 (because of acme API incompatibility as of nov 1st).

**Comment by mariusstaicu** [comment]
solved using suggestion here: https://github.com/rancher/rancher/issues/16454#issuecomment-542674961, however this is a workaround and the issue remains: rancher should provision cluster correctly

**Comment by mariusstaicu** [comment]
Closing in favor of #16454

**Comment by korenlev** [comment]
i see the same issue in 2.5.7 and 2.5.8, simply can not deploy cluster cattle agent, needs resolution guys
