### ISSUE TITLE
racnher2 x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by bao2314483** [rancher/rancher#24324]
Failed to communicate with API server: Get https://172.16.0.15:6443/api/v1/componentstatuses?timeout=30s: x509: certificate has expired or is not yet valid	

my rancher ver:2.1.6

How to manually update a certificate

**Comment by xiaoluhong** [comment]
https://docs.rancher.cn/rancher2x/admin-manual/rotate-cert.html    
Please refer to the above documents.
