### ISSUE TITLE
Rancher 2.3.3: kube-apiserver in loop while searching for /etc/kubernetes/cloud-config

### ISSUE THREAD

**Issue by alexchiri** [rancher/rancher#24329]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a new cluster with cloud provider aws using the following terraform templates: https://github.com/alexchiri/rancher-cluster-tf2/tree/rancher-issue

It basically creates one node for the rancher-server and then using the rancher2 provider it bootstraps the rancher server and creates a cluster with 3 nodes: one for controlplane +  etcd and 2 as workers. It creates all the needed resources for AWS using the aws provider. Docker is installed on the rancher-server using a custom script included in the repo.

**Result:**
kube-apiserver cannot start because it doesn't find /etc/kubernetes/cloud-config

**Other details that may be helpful:**
By doing a `touch /etc/kubernetes/cloud-config` on the controlplane node, the cluster becomes healthy

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud, t3a.medium on AWS
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:50:12 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
I have uploaded the kube-apiserver logs [here](https://gist.github.com/alexchiri/8aae6cb84fdf99d914d023c2add245d5/raw/2e1b6292794c0a772faead4e1ff0cd3e2a6056ac/kube-apiserver.log) and the rancher-server logs [here](https://gist.github.com/alexchiri/8aae6cb84fdf99d914d023c2add245d5/raw/2e1b6292794c0a772faead4e1ff0cd3e2a6056ac/rancher-server.log).

This issue looks similar in behaviour with #19438.

**Comment by ptrunk** [comment]
Same problem here.

**Rancher Version**: v2.3.3
**Environment**: Openstack (Custom Nodes) + External Cloud Provider (deployed manually)

I have updated Rancher from v2.3.2 to v2.3.3 and triggered an update from k8s 1.15.5 to 1.16.3. Upgrade failed with the "Error reading cloud configuration file" message.

Workaround 1: `touch /etc/kubernetes/cloud-config` on all Control Plane Nodes
Workaround 2: Downgrade Rancher Server to v2.3.2

Because Rancher v2.3.2 is working fine i think it is a Bug introduced in Rancher v2.3.3

**Comment by drpebcak** [comment]
I've hit this as well - I can't bring up a cluster in 2.3.3

**Comment by superseb** [comment]
This seems to be related to https://github.com/rancher/rke/issues/1805. We are working on a fix, regarding Terraform, this should be fixable by using the following snippet:

```
  rke_config {
    cloud_provider {
      name = "aws"
      aws_cloud_provider {
      }
    }
```

**Comment by sowmyav27** [comment]
On 2.3.3 rancher:

**Steps:**

- Bring up a custom cluster - 1 nodes on rancher, with AWS cloud config enabled on the UI.
- While registering the nodes, enter the private and public ip address and the node name of the node.
- The cluster fails to come up with the following error.

**Error:**
`[controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [3.136.25.39]: Get https://localhost:6443/healthz: dial tcp 127.0.0.1:6443: connect: connection refused, log: F1206 17:43:41.759852 1 config.go:56] Error reading from cloud configuration file /etc/kubernetes/cloud-config: &os.PathError{Op:"open", Path:"/etc/kubernetes/cloud-config", Err:0x2}]`

**Comment by deniseschannon** [comment]
Should be available in latest v2.3-head based on this commit:https://github.com/rancher/rancher/commit/cb00371201751de2feee347cd15b3369ebcb5c24

**Comment by kinarashah** [comment]
Note on why it's not happening "always" on Custom cluster created from Rancher:

It's related to `awsCloudProvider` being present or not, and it comes from UI. No changes in backend. 

- when it doesn't work, cluster has: 
```
"cloudProvider":{"name":"aws"}
```

- this works: 
```
"cloudProvider":{"awsCloudProvider":{},"name":"aws"}
```

**Comment by sowmyav27** [comment]
As per @kinarashah 's comments - https://github.com/rancher/rancher/issues/24329#issuecomment-564167817

Issue seen on `2.3.3` is
- on a Custom cluster, in some cases, on configuring a aws cloud provider custom cluster, the cloud provider is set as (cluster.yml)
```
  cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
        disable-strict-zone-check: false
    name: aws
```
- In other cases
```
  cloud_provider:
    name: aws
```
Logging an issue -- to track this.

- On `rancher:v2.3.3`, whenever the cloud config from Rancher is set as in cluster.yml
```
  cloud_provider:
    name: aws
```
The cluster fails to come up as file: `/etc/kubernetes/cloud-config` is NOT created.  error seen:
`[controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [ip]: Get https://localhost:6443/healthz: dial tcp 127.0.0.1:6443: connect: connection refused, log: F1210 20:40:25.006945 1 config.go:56] Error reading from cloud configuration file /etc/kubernetes/cloud-config: &os.PathError{Op:"open", Path:"/etc/kubernetes/cloud-config", Err:0x2}]`

Verified on latest 2.3-head - commit id: `0da334b28`
- Create a custom cluster, with AWS cloud provider enabled.

**Scenario#1**
- In case of the cloud provider set on cluster.yml file like:
```
  cloud_provider:
    name: aws
```
- The cluster comes up successfully.
- On the node, `cat /etc/kubernetes/cloud-config`, the file is available, on the node, and is empty.

**Scenario#2**
- In the case where cloud provider is set as the following in the cluster.yml
```
  cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
        disable-strict-zone-check: false
    name: aws
```
- The cluster comes up successfully.
- On the node, `cat /etc/kubernetes/cloud-config`, the file is available, on the node, and has contents:
```
$cat /etc/kubernetes/cloud-config 
[Global]

```

**Comment by sowmyav27** [comment]
Reopening this issue for a fix/PR in master-head

**Comment by superseb** [comment]
Based on https://github.com/rancher/rancher/commit/c9e674f7af3619a938feaf5be6024442bccee645, this should be in master

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `6717e73d1`**

- On an rke cluster with the cloud provider set as in the cluster.yml

```
cloud_provider:
    name: aws
```

- The cluster comes up successfully.
- On the node, cat /etc/kubernetes/cloud-config, the file is available, on the node, and is empty.
- LB works fine on the setup - rke - 1 node, cloud provider set.
