### ISSUE TITLE
the default value of question.yaml doesn't show correctly on udpate app page 

### ISSUE THREAD

**Issue by fangwei18** [rancher/rancher#24331]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1.  update the chart version
2.  go to `Apps`, select the app and click update
3. the default value of question.yaml doesn't show correctly
![image](https://user-images.githubusercontent.com/45305818/69932782-6152eb80-1507-11ea-9a21-b7a57c154ff0.png)
then remove this app and launch a new one, the default value showes correctly 
![image](https://user-images.githubusercontent.com/45305818/69932804-7c256000-1507-11ea-9d73-55c14c88d7c1.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.3
- Installation option (single install/HA): install using docker

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by sowmyav27** [comment]
Verified on rancher:2.3.3, not able to reproduce the issue.
**Steps:**

- Go to Cluster--> Project --> Apps --> Launch
- Select app - Mysql/MongoDB.
- Deploy the app.
- Select App, click on `Upgrade`. 
- The default value of question.yaml are seen on the UI as expected.

@zhkou Can you give more information on what app was deployed?

**Comment by zhkou** [comment]
here is my `questions.yml`
```yaml
questions:
  - name: image.repository
    label: docker image repository
    type: string
    default: 120.26.62.10:30000/common-idgen-be
    required: true

  - name: image.tag
    label: image tag
    type: string
    default: latest
    required: true
```
When launching a new app:
![image](https://user-images.githubusercontent.com/45305818/70002461-0ff43c00-159b-11ea-94b2-360e12bcb7bc.png)
When updating an existing app:
![image](https://user-images.githubusercontent.com/45305818/70002493-239fa280-159b-11ea-8141-a41318132eb2.png)

**Comment by loganhz** [comment]
I guess the answer `image.repository` is already `dev` when you deploy the app. As the answer has been set already, the default value will not be used when you do the update. Please provide the view api result for the app which you hit this issue.
