### ISSUE TITLE
Always show certificates are about to expire if there are removed etcd hosts

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#24333]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
![image](https://user-images.githubusercontent.com/20707603/69933605-3d44d980-150a-11ea-8937-76cb96e07875.png)

1. switch to global, click the ellipsis menu to the right of the cluster list, and then click Rotate Certificates > Rotate all service certificates.

  **Result:**  The UI still shows that the certificate is about to expire

2. View the cluster API certificatesExpiration field ，contains the master node that has changed, such as ip 192.168.0.68.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/20707603/69932765-539d6600-1507-11ea-973f-5b495cdc0807.png">

3. Check the kube-system namespace under the business cluster system project. There is no etcd secrets corresponding to the 192.168.0.68 node. However, I only have three ETCD nodes

**Cause analysis**
Switch to the local cluster >system project >cattle-system namespace and enter the resource > secrets page，Export the secrets corresponding to the business cluster id. 

Analyzing the metadata.certs field, it was found that the certificate information of the master node that had been replaced was retained, so it was possible that the UI misjudged because of the residual certificate

**Other details that may be helpful:**

**Environment information**
- Rancher version :
`rancher/rancher:v2.3.2`
- Installation option (single install/HA):
HA
- Docker version 
18.09
- Kubernetes version 
v1.15.4

**Comment by loganhz** [comment]
Reproduced in 2.3.3

Steps to reproduce:

1. Add a cluster with 3 etcd nodes
2. Remove one etcd node and add a new one 
3. Rotate certs
4. Click View API for the cluster. The cert for removed ectd node is still in API and the expirationDate not changed.

**Comment by XianglongLuo** [comment]
We can find the same problem when we create  k8s cluster by rke:
Steps to reproduce:
1、Add three ALL(etcd,worker and controlplane) node and rke up,we can see three etcd cert in cluster.rkestate,one is:
![image](https://user-images.githubusercontent.com/37337250/71071588-dedd5380-21b7-11ea-9a85-b9e137ee23f1.png)
And no kubelet cert(generate serving certificate is disabled)(ref:https://rancher.com/docs/rke/latest/en/config-options/services/#kubelet):
![image](https://user-images.githubusercontent.com/37337250/71071698-08967a80-21b8-11ea-90e5-c5460ce957ba.png)
If we   enable  generate serving certificate and rke up again,it will generate kubelet certs,we can see them in cluster.rkestate:
![image](https://user-images.githubusercontent.com/37337250/71071895-69be4e00-21b8-11ea-8a19-1c8e20195da7.png)
2、Remove the node '13-250-121-197' from cluster.yml and rke up again,we can see:
￼￼ The unused etcd and kubelet certs  not be deleted:
![image](https://user-images.githubusercontent.com/37337250/71072190-ea7d4a00-21b8-11ea-950f-888502931b43.png)
![image](https://user-images.githubusercontent.com/37337250/71072206-f23cee80-21b8-11ea-8a31-ba5ffe3fcbd0.png)
And if we disable generate serving certificate and rke up,we can see:
 ￼￼All kubelet certs be  unused ,but  not be deleted:
![image](https://user-images.githubusercontent.com/37337250/71072615-d7b74500-21b9-11ea-94c5-f7ca0d05d440.png)
![image](https://user-images.githubusercontent.com/37337250/71072645-e7368e00-21b9-11ea-9c39-dcd123973aa3.png)

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.3.5**

**Steps:**

- Add a cluster with 3 etcd nodes, 1 control plane and 1 worker nodes
- Delete one etcd node and wait for another one to be provisioned.
- After the cluster has come up Active, Rotate certs
- Click View API for the cluster. The cert for removed ectd node is still in API and the expirationDate not changed.

<img width="385" alt="Screen Shot 2020-02-25 at 1 20 10 PM" src="https://user-images.githubusercontent.com/26032343/75288774-de71c200-57d1-11ea-86a6-cc180fad1328.png">
