### ISSUE TITLE
Nested groups info sometimes lost with Google OAuth

### ISSUE THREAD

**Issue by yannrouillard** [rancher/rancher#24334]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

 * Configure Google Oauth with nested groups,
 * Create a user `UserA` and two groups  `GroupParent` and `GroupChild` in Google,
 * Add `UserA` as member of `GroupChild`, and add `GroupChild` as member of `GroupParent`
 * Authorize only `groupParent` to access a cluster (or a project)  
 * Log in with `UserA`

**Result:**

`User` can't access the cluster or project although he should because he belongs indirectly to `GroupParent`
If he log-out and re-log, he will then be able to properly see the cluster and the project.

The issue will happen at a subsequent login if there is enough delay with the previous login.

**Other details that may be helpful:**

I will post more details about the logs but basically I can clearly see that only the direct groups (`groupChild` in the example) is detected at first login and then the parent groups are detected by Rancher at the next logout/login.

**Environment information**
- Rancher version: 2.3.2
- Installation option: single install

**Comment by yannrouillard** [comment]
Here is an excerpt of the logs when the problem happens with some info masked.
There was a log of logs so I chose to select the one that seemed relevant:

```
2019/12/02 05:15:38 [DEBUG] [Google OAuth] loginuser: Using code to get oauth token
2019/12/02 05:15:38 [DEBUG] [Google OAuth] loginuser: Exchanged code for oauth token
2019/12/02 05:15:38 [DEBUG] [Google OAuth] loginuser: Obtained userinfo using oauth access token
[...]
2019/12/02 05:15:40 [DEBUG] [Google OAuth] loginuser: Retrieved user's groups using admin directory
2019/12/02 05:15:40 [DEBUG] [Google OAuth] loginuser: Checking user's access to Rancher
2019/12/02 05:15:40 [DEBUG] [Google OAuth] loginuser: Returning principals and marshaled oauth token
[...]
2019/12/02 05:15:40 [DEBUG] Requesting user: u-fakeuserid, Requesting groups: [system:authenticated] Impersonate user:  Impersonate group: []
2019/12/02 05:15:40 [DEBUG] Triggering auth refresh on u-fakeuserid
[...]
2019/12/02 05:15:40 [DEBUG] Starting refresh process for u-fakeuserid
2019/12/02 05:15:40 [DEBUG] [Google OAuth] RefetchGroupPrincipals: Initialized dir svc with stored oauth token
2019/12/02 05:15:40 [DEBUG] [Google OAuth] GetPrincipal: Parsed principalID
[...]
2019/12/02 05:15:41 [DEBUG] Requesting user: u-fakeuserid, Requesting groups: [googleoauth_group://group_child_id system:authenticated] Impersonate user:  Impersonate group: []


2019/12/02 05:20:18 [DEBUG] [Google OAuth] loginuser: Using code to get oauth token
2019/12/02 05:20:19 [DEBUG] [Google OAuth] loginuser: Exchanged code for oauth token
2019/12/02 05:20:19 [DEBUG] [Google OAuth] loginuser: Obtained userinfo using oauth access token
[...]
2019/12/02 05:20:22 [DEBUG] [Google OAuth] loginuser: Retrieved user's groups using admin directory
2019/12/02 05:20:22 [DEBUG] [Google OAuth] loginuser: Checking user's access to Rancher
2019/12/02 05:20:22 [DEBUG] [Google OAuth] loginuser: Returning principals and marshaled oauth token
[...]
2019/12/02 05:20:22 [DEBUG] Requesting user: u-fakeuserid, Requesting groups: [googleoauth_group://group_child_id googleoauth_group://group_parent_id system:authenticated] Impersonate user:  Impersonate group: []
[...]
2019/12/02 05:20:22 [DEBUG] Triggering auth refresh on u-fakeuserid
2019/12/02 05:20:22 [DEBUG] Skipping refresh for u-fakeuserid due to max-age
```

**Comment by yannrouillard** [comment]
For now our supposition about the issue is that there are 2 ways to retrieve the group informations: * one triggered by the refresh code (`[Google OAuth] RefetchGroupPrincipals`) which doesn't properly handle nested groups
* one triggered by the login code (`[Google OAuth] loginuser: Retrieved user's groups using admin directory`) which properly handle nested groups

At first login, the groups are retrieved at login time then the refresh code is triggered and update the groups info without including `groupParent`.

So at first login, th user is not seen as member of  `groupParent`and doesn't see the cluster.
On the second login, the groups are again retrieved at login time but this time they are not updated after by the refresh code which is not triggered since maxAge duration has not yet passed.

After maxAge passed, if the user re-log, the refresh code is triggered again which remove again the `groupParent`. `UserA` will again loses access until he re-logs.

**Comment by yannrouillard** [comment]
Looking at the source code we see than:

* `RefetchGroupPrincipals` doesn't seem to handle nested configuration, it directly returns the result of `getGroupsUserBelongsTo` -> https://github.com/rancher/rancher/blob/master/pkg/auth/providers/googleoauth/goauth_provider.go#L257

* `getUserInfoAndGroups` do take into account nested groups configuration -> https://github.com/rancher/rancher/blob/master/pkg/auth/providers/googleoauth/goauth_helper.go

We didn't follow the exact code path so not sure this is the cause of the issue.

**Comment by sowmyav27** [comment]
Verified on `rancher:v2.3.3` and not able to reproduce the issue.

**Steps:**

- Configure Google Oauth using nested groups
- Create a user UserA and two groups GroupParent and GroupChild in Google
- Add UserA as member of GroupChild, and add GroupChild as member of GroupParent
- Authorize only groupParent to access a cluster as cluster member.
- Log in with UserA. User is able to see the cluster on the first login.

**Comment by sowmyav27** [comment]
On `rancher:v2.3.3`, Refresh group Memberships has an issue

**Steps:**

- Configure Google Oauth using nested groups
- Create a user UserA and two groups GroupParent and GroupChild in Google
- Add UserA as member of GroupChild, and add GroupChild as member of GroupParent
- Authorize only groupParent to access a cluster as cluster member.
- Log in with UserA. User is able to see the cluster on the first login.
- Go to `https://<rancher-server>/v3/principals` and check the number of principals. There should be 3 (GroupParent, GroupChild and User A)
- As an admin on another browser, Go to Global --> users -->Click on `Refresh Group Memberships`
- On the browser where userA is logged in, click on refresh of the browser on URL `https://<rancher-server>/v3/principals`.
- The `GroupParent`'s principal is missing.

**Comment by jiaqiluo** [comment]
Met the same bug in mater-head e74c23940

After refreshing,  the user loses permissions inherited from the grandparents' group

**Comment by dramich** [comment]
https://github.com/rancher/rancher/pull/24634

**Comment by sowmyav27** [comment]
Verified on master-head - latest - commit id: `a106f2aa4` and 2.3-head - commit id: `9c1ee616e`

**Steps:**

- Configure Google Oauth using nested groups
- Create a user UserA and two groups GroupParent and GroupChild in Google
- Add UserA as member of GroupChild, and add GroupChild as member of GroupParent
- Authorize only groupParent to access a cluster as cluster member.
- Log in with UserA. User is able to see the cluster on the first login.
- Go to https://<rancher-server>/v3/principals and check the number of principals. There should be 3 (GroupParent, GroupChild and User A)
- As an admin on another browser, Go to Global --> users -->Click on Refresh Group Memberships
- On the browser where userA is logged in, click on refresh of the browser on URL https://<rancher-server>/v3/principals.
- The GroupParent's principal are available.
