### ISSUE TITLE
AWS EC2 provisioner opening port 2376 on existing security group open to 0.0.0.0/0

### ISSUE THREAD

**Issue by kamileon** [rancher/rancher#24337]
Hi!

**Steps**
Create cluster using the AWS EC2 provisioner, select an existing security group.

**Result**
Existing security group is modified - an inbound rule for the TCP 2376, TCP 22 source 0.0.0.0/0 are added!

**Expected**
Existing security group is not modified.

****
Using the Rancher 2.3.3.

gz#12865
gz#15820

SURE-2505, SURE-2860, SURE-3771

**Comment by sowmyav27** [comment]
Able to reproduce this on `rancher:v2.3.3` and `rancher:v2.2.9`
**Steps:**
- Create cluster using the AWS EC2 provisioner, select an existing security group while creating the node template.

**Result:**
- Existing security group is modified - an inbound rule for the TCP 2376, TCP 22 source 0.0.0.0/0 are added

**Comment by sowmyav27** [comment]
@kamileon 

2376 is docker port, and is required for Rancher to work to be able to talk to the host.

**Comment by kamileon** [comment]
@sowmyav27 I am aware of the requirements.

I believe when a custom/existing group is used, it should not be modified in any way. The owner takes the responsibility at this point to ensure all the setup is done right as per https://rancher.com/docs/rancher/v2.x/en/installation/references/.

As it stands right now, EC2 provisioner is compromising the security of my setup.

On the side, opening the docker port 2376 to the whole world raises a red flag in my head.

I am looking forward to hear back. Thanks!

**Comment by gochist** [comment]
Currently docker machine provides an option not to modify the security group(https://github.com/docker/machine/pull/4490). It would be great if rancher provide the option also.

**Comment by iamkye** [comment]
Having the same issues on our RKE / EC2 clusters.  How do we make it stop modifying custom groups on changes?

**Comment by Israphel** [comment]
This issue still exists. When working with Terraform + Rancher  it would be ideal if Rancher doesn't mess up the security groups. I tried removing Rancher's permission to add Rules but then everything fails; it won't add machines if it can't add rules, even tho they already exist.

Also, if you assign more than one SG, it will add the same rules everywhere.

**Comment by luthermonson** [comment]
https://github.com/rancher/machine/blob/master/drivers/amazonec2/amazonec2.go#L1297-L1304 this code probably

**Comment by maggieliu** [comment]
Can leverage this flag: https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go#L167.

**Comment by Ellenqs** [comment]
I was able to reproduce this on rancher:v2.3.3 and rancher:v2.5.4
Steps:

Create cluster using the AWS EC2 provisioner, select an existing security group while creating the node template. (all open) check if TCP 2376, TCP 22 source 0.0.0.0/0 already exist in the inbound rule, remove them. Then provision the cluster.
 
Result:

inbound rule for the TCP 2376, TCP 22 source 0.0.0.0/0 are added

**Comment by ryansann** [comment]
Inbound rules that are added to an existing security group:

| Type       | Protocol | Port Range | Source    |
|------------|----------|------------|-----------|
| SSH        | TCP      | 22         | 0.0.0.0/0 |
| Custom TCP | TCP      | 2376       | 0.0.0.0/0 |

Both of these rules are created for Node management purposes.

If we made changes to prevent these rules from being added to security groups, it would result in node provisioning operations failing, unless the existing security group already specified these required rules.

For this reason, instead of removing the logic to add these, we should instead warn users they will be added to their existing security group via the UI.

For EC2 Node Templates, under section `3. Security Groups`, when a user specifies `Choose one or more existing groups` we should show an info/warning box to the user that the aforementioned inbound rules will be added to their selected SG(s). This way, we ensure we are communicating the changes that will be made to the user.

**Comment by tulanian** [comment]
@ryansann I disagree. If you give the user the option to select an existing SG then the tool should not mess with the SG at all. Pop up a warning that says port 22 and 2376 should be accessible from the rancher servers, but do not make any changes. Our network configs are locked down with SCPs and we don't want anyone other than network admins messing with the VPCs or SGs.

**Comment by panho66** [comment]
Running into this problem with Rancher 2.4.15. Port 22 and 2376 0.0.0.0/0 pop up in one of two security groups which do not has inbound rule for port 22 and 2376 the second security do have rules for port 22 and 2376. @ryansann I disagree Rancher adding inbound rule automatically. If user select pre-defined security group without port 22 and 2376, Rancher providing warning is good enough. With two security groups in one EC2, Rancher seems only check one security group but not both.

1) cidr 0.0.0.0/0 is NO NO in our company
2) Least privilege principle, Rancher's cloud credential do not have permission to add or remove security group ingress/egress rule. If Rancher automatic add ingress rule, EC2 provision will fail.

**Comment by RP-TSB** [comment]
Hello Rancher Dev Team, I would appreciate it if this issue was prioritised instead of removed from every milestone since it affected our security score. Having security groups allowing ports from anywhere is not the best practice.

**Comment by Jono-SUSE-Rancher** [comment]
Hey @cloudnautique do you want to have a design meeting regarding this specific issue? I know that @ryansann  did some research and determined that it was designed to be setup this way, so we don't necessarily want to make any changes without consulting the original intent.

**Comment by snasovich** [comment]
Design discussion about this issue happened and we are going to stop Rancher from opening ports 22/2376 on user-provided security groups. The fix is likely to move this code under the `if`-statement below: https://github.com/rancher/machine/blob/168391d2b8861d12cb1df5322e40dafd4cb6b5c4/drivers/amazonec2/amazonec2.go#L1288-L1304

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Validation**
Rancher: v2-6-head(1d2b746)
Install: Helm
Local k8s: v1.21.10

** Validation steps**

**Test Case 1: **

1. Used `default` security group within ec2. 
2. Removed any inbound rules the relate to the ones mentioned in the original issue (22, 2376)
3. In rancher setup provision a cluster. 
4. using the above security group when creating the node template.
5. Return to ec2 when provisioning is finished and check the security group to verify no inbound rules were added. 

**Test Case 2:**
1. Create a node template from RKE1 Node template section
2. Go ahead and use the same SG(default) as above, while preemptively checking to make sure no inbound rules  that match the original are present. (That will be contained within ec2)
3. Now provision the rke1 cluster with the now created RKE1 Node Template
4. Post the successful provision, return to ec2 and check the inbound rules. 

**Results**
The above test cases passed. The inbound rules were set to the default for kubernetes, but the above rules did not exist. 

**Setup For Reproduction**
Rancher: v2-6-3
Install: Helm
Local k8s: v1.21.8

**Steps For Reproduction**
1. Provision cluster on any SG
2. Witness within ec2 that the rules have been changed.
