### ISSUE TITLE
RKE Templates not visible in UI

### ISSUE THREAD

**Issue by chuegel** [rancher/rancher#24339]
I created some RKE templates but these are not visible:

<img width="1264" alt="grafik" src="https://user-images.githubusercontent.com/6955465/69975052-bd793800-1526-11ea-9873-ee02079e4d53.png">

However, when creating a cluster I can select the template from the drop down menu:

<img width="907" alt="grafik" src="https://user-images.githubusercontent.com/6955465/69975287-36788f80-1527-11ea-95c0-22ef2b45f2a3.png">

<img width="700" alt="Screenshot 2019-12-02 at 17 30 27" src="https://user-images.githubusercontent.com/6955465/69976611-8fe1be00-1529-11ea-932b-db4afe953078.png">

In FF Console there is this error: `TypeError: this.clusterTemplate is null`

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`global-admin.cluster-templates.new`|
|k8s Version| `1.16.3`
|Browser|Firefox `70.0.1`on macOS

**Comment by sowmyav27** [comment]
Verified on Rancher v: `2.3.3`, UI: `v2.3.25` and Firefox v : `70.0.1`. Not able to reproduce the issue.
**Steps:**

- Create rke templates on the UI
- User - Admin can see the available rke templates.
- Create a cluster - DO, select ` Use an existing RKE Template and revision`. 
- User is able to select from created rke templates.
- From Firefox browser, user is able to see the available rke templates.
- Create a cluster - DO, select ` Use an existing RKE Template and revision`.  User is able to select from created rke templates.

**Comment by michaelandrepearce** [comment]
Try creating a number of templates some being default and delete one. We also hit the same issue.

**Comment by michaelandrepearce** [comment]
Some further info, that we've figured out, how this can get into this state, it seems somehow when deleting a clusterTemplate, clusterTemplateRevisions can be left behind, that then link to a not existent clusterTemplate. Annoyingly once you've found the offending clusterTemplateRevisions that cause the FE npe, you cannot even delete them by api, because it fails with 404 due to the link to the non existent clusterTemplate


cURL command line:
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X DELETE \
-H 'Accept: application/json' \
'https://REDACTED/v3/clusterTemplateRevisions/cattle-global-data:ctr-4q2jk'

HTTP Request:
HTTP/1.1 DELETE /v3/clusterTemplateRevisions/cattle-global-data:ctr-4q2jk
Host: REDACTED
Accept: application/json

HTTP Response:
HTTP/1.1 404
content-encoding: gzip
content-length: 138
content-type: application/json
date: Tue, 03 Dec 2019 15:47:01 GMT
expires: Wed 24 Feb 1982 18:42:00 GMT
server: openresty/1.15.8.1
status: 404
strict-transport-security: max-age=15724800; includeSubDomains
x-api-schemas: https://REDACTED/v3/schemas
x-content-type-options: nosniff

{
"baseType": "error",
"code": "NotFound",
"message": "clustertemplates.management.cattle.io \"ct-82tnz\" not found",
"status": 404,
"type": "error"
}

**Comment by michaelandrepearce** [comment]
As such it seems even by API its not possible to workaround this, and fix.

**Comment by westlywright** [comment]
@michaelandrepearce Can you provide more information on how you are removing a cluster template? 
From the issue I was able to pinpoint where the UI blows up and will resolve this, but there are mechanisms in place on the back-end that should clean up any cluster template revisions associated with a cluster template and I have not been able to reproduce the scenario you are describing.

**Comment by michaelandrepearce** [comment]
If you wanted we could organise a screen share to show you the problem privately i cannot obviously share publically cluster details.

**Comment by michaelpearce-gain** [comment]
Re how we are removing it, it is via the UI.

it seems if you clean the revisions manually first (via api), before deleting the clustertemplate the issue can be avoided.

And a downgrade and upgrade of rancher (e.g. -> downgrade to 2.3.2 and re-upgrade to 2.3.3) clears the corrupt data in the server.

**Comment by westlywright** [comment]
@michaelandrepearce I'm not sure I would be the right one to get on the share as the bug does seem to lie in the back-end cleanup mechanism. let me reach out to some other people and I'll circle back here when I have more info.

**Comment by prachidamle** [comment]
@michaelandrepearce @michaelpearce-gain Do you see this issue happen if you delete the clustertemplate (not revision) from the API?

Also for the clustertemplaterevisions that linger behind, do you see any finalizers present when you try to get the crd via kubectl? Also do you see ownerreferences set on those revisions?

**Comment by davidweizheng** [comment]
Any news? I'm having the exact same issue. Deleted an old RKE Template, now UI is unable to display any templates. Error in Chrome console says -
```
clustertemplaterevision.js:25 Uncaught TypeError: Cannot read property 'defaultRevisionId' of null
    at n.<anonymous> (clustertemplaterevision.js:25)
    at n.a.get (metal.js:2984)
    at n.Object.defineProperty.get [as canMakeDefault] (metal.js:997)
    at n.<anonymous> (clustertemplaterevision.js:47)
    at n.a.get (metal.js:2984)
    at Object.ie [as get] (metal.js:1592)
    at n.<anonymous> (cattle-transitioning-resource.js:275)
    at n.a.get (metal.js:2984)
    at Object.ie [as get] (metal.js:1592)
    at component.js:221
```

Rancher version is v2.3.3.

**Comment by prachidamle** [comment]
@westlywright looks like there is another NPE in the UI from the logs that @davidweizheng posted above

**Comment by prachidamle** [comment]
@davidweizheng do you  think you can give the above UI fix a test by changing a global setting called `ui-index` for your rancher setup? You can find it via API at https://<your setup ip>/v3/settings/ui-index

**Comment by davidweizheng** [comment]
@prachidamle Awesome, thanks! The fix works. Quick question - should I keep the same setting if I upgrade Rancher to newer version? (v2.3.4 was just released.)

**Comment by davidweizheng** [comment]
> @prachidamle Awesome, thanks! The fix works. Quick question - should I keep the same setting if I upgrade Rancher to newer version? (v2.3.4 was just released.)

Found the answer myself. Upgrading from v2.3.3 to v2.3.4 cleaned up the orphaned template revisions. I reset ui-index to default value. Everything looks good now.

**Comment by prachidamle** [comment]
@huegelc do you think you can give this a test again with the latest UI fixes as mentioned in above comment https://github.com/rancher/rancher/issues/24339#issuecomment-574407430

**Comment by huegelc** [comment]
@michaelandrepearce works again in 2.3.4. Thanks

**Comment by jcwimer** [comment]
I ran into this issue when deleting a RKE Template on v2.3.5. It seems that deleting the template left behind the revision.

I fixed it by cleaning up etcd on Rancher itself. 

1. I looked at /v3/clustertemplaterevisions on my browser to get the  name of the revision that was left behind. In this example ctr-d5s26 was the name of the revision left behind.
2. Ran `etcdctl get --from-key '' | grep clustertemplaterevision | grep "ctr-d5s26"` to find the key to delete.
3. Ran `etcdctl del /registry/management.cattle.io/clustertemplaterevisions/cattle-global-data/ctr-d5s26` to delete the key in etcd.

**Comment by maggieliu** [comment]
Related to : https://github.com/rancher/rancher/issues/26861

**Comment by soumyalj** [comment]
Reproduced the issue in v2.3.3

1. Create 100 templates with 50 revisions in each . 
2. Delete the templates

Some of the revisions are orphaned :
```
> kubectl get clustertemplaterevisions -n cattle-global-data
NAME        AGE
ctr-272cd   23m
ctr-2n9r7   21m
ctr-2zzjg   24m
ctr-4gpdq   20m
ctr-4gtmr   21m
ctr-5fvmj   25m
ctr-5h5sq   21m
ctr-5x2ds   24m
ctr-669xb   24m
ctr-66nqg   22m
ctr-68pvv   21m
ctr-6rwqc   24m
ctr-79r5b   24m
ctr-7h86w   23m
ctr-7pgvm   21m
ctr-85vqj   20m
ctr-9b4vw   22m
ctr-9nhwz   6m33s
ctr-bd7f7   24m
ctr-bjzcq   24m
ctr-bqmrw   23m
ctr-br94n   22m
ctr-c9bs4   24m
ctr-dbrxh   20m
ctr-f758k   23m
ctr-ftwmw   23m
ctr-gj5tn   23m
ctr-gljwd   23m
ctr-hll6h   21m

```
3. Create another rke template.
4. Navigate to the RKE templates page. The RKE templates page is empty 

![Screen Shot 2020-06-23 at 6 35 20 PM](https://user-images.githubusercontent.com/18536626/85486888-626d6800-b580-11ea-8614-8f5c612bcd91.png)
5. When we create a new cluster, the template is available to be selected

![Screen Shot 2020-06-23 at 6 37 31 PM](https://user-images.githubusercontent.com/18536626/85487030-9fd1f580-b580-11ea-8728-3ab089ef2d9c.png)

**Comment by soumyalj** [comment]
Tried the same steps as above in v2.4.4 and the issue is not observed. When there are revisions orphaned, the RKE templates are loaded in the UI as below. There was no error observed in the console.

![Screen Shot 2020-06-24 at 10 15 01 AM](https://user-images.githubusercontent.com/18536626/85601989-c38a4f80-b603-11ea-8d1a-e4a3fc73e40b.png)

**Comment by soumyalj** [comment]
Validated on v2.4-head. 
Steps:
1. Create 200 templates with 50 revisions in each .
2. Delete the templates

There are no RKE revisions orphaned in the setup and the RKE templates are displayed correctly.
