### ISSUE TITLE
Notifier email configure return plaintext password

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#24335]
Notifier return plaintext password in API request

![image](https://user-images.githubusercontent.com/5936271/69937677-56538780-1516-11ea-9e1c-b8d2cc35962f.png)

@loganhz could you help add milestone

**Comment by alena1108** [comment]
@aiwantaozi we have to make sure to:

1) add a test
2) validate that the subsequent update use case will work, from both the test + API. There were issues in the past when the password was reset on the crd when the UI was setting an empty value. Steps to take:
* Setup notifier with the password. Make sure the password is set on crd, and not shown in api
* Edit notifier. Change something non-password related, hit save. Make sure that the password in crd remains the same

**Comment by bmdepesa** [comment]
rancher/rancher:master-head a70698d25

* Reproduced in v2.3.5
* Deploy`rancher/rancher:master-head`
* Create a cluster
* Create an email notifier w/ password set
* View notifier in API and no password field is present
* Check CRD on server and see that password is set correctly
* Update password in notifier and see it reflected in CRD
* Update some non-password field (username in this case) and see the field updated, and password is not changed
