### ISSUE TITLE
Rancher UI bug：edit port mapping option for workload not working

### ISSUE THREAD

**Issue by zhongguanqun** [rancher/rancher#24332]
*Describe your issue here*
![image](https://user-images.githubusercontent.com/4767546/69932564-90b52880-1506-11ea-951a-6990e7ad0d02.png)

端口映射配置修改前状态。

![image](https://user-images.githubusercontent.com/4767546/69932643-d671f100-1506-11ea-866b-503e5bb26514.png)

映射映射配置，将暴露端口改为8000，点击保存。

![image](https://user-images.githubusercontent.com/4767546/69932650-e4277680-1506-11ea-8f67-70b5cd60218b.png)

保存后，再查看端口映射选项，发现没有修改成功。

![image](https://user-images.githubusercontent.com/4767546/69932764-526c3900-1507-11ea-87fb-06da4f3b2d0d.png)

查看yaml文件，进一步确认没有修改成功。

是从2.2.5升级到2.3.3的，2.2.5没这个问题，其他版本不清楚。对应已经正常运行的并且暴露端口和容器端口不一致的workload，一旦redeploy就直接改变暴露端口，导致依赖此服务的其他服务不能正常通信，引入服务不可用，致命问题，需要加急处理!

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`workload`|

**Comment by loganhz** [comment]
Cannot reproduce in 2.3.3. Please check the status of cluster-agent in System project. The controller for updating the Rancher auto generated svc is running inside cluster-agent pod. If cluster-agent is unhealthy, it will not be updated. Please add `rancher2` via WeChat to join Rancher WeChat group if you would like to ask question in Chinese.
