### ISSUE TITLE
Coredns container not available for rancher/coredns on arm64 (Rpi4)

### ISSUE THREAD

**Issue by anoonan-zz** [rancher/rancher#24344]
**What kind of request is this (question/bug/enhancement/feature request):**
question/bug

**Steps to reproduce (least amount of steps as possible):**
"rke up" on an arm64 cluster configured to use the default DNS (coredns)

**Result:**
rancher/coredns-coredns containers unabled to start with an "ImagePullBackOff" state

**Other details that may be helpful:**
Looking at the docker registry, there doesn't seem to be an arm64 container for coredns available)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): -NA-, just RKE at this point.  Latest version of RKE (1.0.0)
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Raspberry Pi 4b
- Kubernetes version (use `kubectl version`):

```
I can add this later, probably doesn't matter, as this is likely to just be a missing arch to be built.
```

- Docker version (use `docker version`):

```
I can add this later, probably doesn't matter, as this is likely to just be a missing arch to be built.
```

**Comment by anoonan-zz** [comment]
If the desired workaround is to not use coredns, that's fine, I just need to change that up in the configs since the default for RKE at this point is coredns.

**Comment by chA0s-Chris** [comment]
I ran into the same problem after creating a cluster (using the Rancher UI) on an x64 machine and adding a Raspberry Pi 4b as node. Everything seemed fine until I tried to deploy an arm64 workload and saw in the logs that there is no arm64 image for rancher/coredns-coredns.

Is there an arm64 image already in the works?

**Comment by Confusingboat** [comment]
If you have x86 nodes in the cluster you can work around this by setting coredns to only schedule on `amd64` nodes.
