### ISSUE TITLE
[UI] Load-balancer doesn't updates html content when choosing [Create New Existing Cookie]

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2434]
VERSION: `v0.43.0-rc2`

<img width="1056" alt="captura de ecra 2015-10-25 as 00 29 53" src="https://cloud.githubusercontent.com/assets/3604053/10713313/97ebae62-7aaf-11e5-9617-7ae55b5b3e13.png">

**Comment by deniseschannon** [comment]
Verified with UI v0.59.0.

**Comment by cusspvz** [comment]
That was fast! Thanks! :smile:
