### ISSUE TITLE
cannot access Jeager or Kiali UI's

### ISSUE THREAD

**Issue by dbones** [rancher/rancher#24355]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

enable Istio, with all the default settings apart from that all authenticated users can access Kiali and Jaeger UI

then try to access either Kiali or Jaeger

**Result:**

Error: 'dial tcp 10.0.20.110:80: i/o timeout'
Trying to reach: 'http://10.0.20.110:80/jaeger/search'

its similar for Kiali

**Other details that may be helpful:**

Prometheus and Graphana work and can be accessed.

we force-able moved the pods to another node, and this did not work either.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.2
- Installation option (single install/HA): HA

Istio: 0.1.1 App package (also tried 0.1.0)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS

**Comment by saiyam1814** [comment]
Is the Kiali pod running ? what are the logs for that ?

**Comment by dbones** [comment]
it looks like we needed to have port 80 open (this resolved this issue)

**Comment by cyliu0204** [comment]
> it looks like we needed to have port 80 open (this resolved this issue)
hi dbones ,
can u describe the resolution more specific? i have met exactly the same problem, du you mean the port 80 on local server?

**Comment by glentakahashi** [comment]
You have to edit your node security group in EC2 to allow port 80 communication from control plane: https://github.com/rancher/rancher/issues/19740#issuecomment-486657688
