### ISSUE TITLE
Listening port for Load Balancer is overwritten in UI and in API

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#24358]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create an EC2 Cluster with Amazon cloud provider.
Deploy a workload.
Add port as a load balancer.
Set listening port to anything but 0.
![Screen Shot 2019-12-03 at 8 47 14 AM](https://user-images.githubusercontent.com/57409052/70066887-ac720a80-15aa-11ea-9fad-b3c88768c0a9.png)
Launch.
Edit the workload.

**Result:**
Listening port has been set to 0.
![Screen Shot 2019-12-03 at 8 52 49 AM](https://user-images.githubusercontent.com/57409052/70066901-af6cfb00-15aa-11ea-8212-c5fc985252a0.png)
Examining in API yields:
```
ports": [
{
"containerPort": 80,
"dnsName": "test-loadbalancer",
"kind": "LoadBalancer",
"name": "testport",
"protocol": "TCP",
"sourcePort": 0,
"type": "/v3/project/schemas/containerPort"
}
],
```

**Other details that may be helpful:**
May be related to the following: https://github.com/rancher/rancher/issues/23375

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher v.2.3.3
Seen in master-head
- Installation option (single install/HA): single install

**Comment by aaronRancher** [comment]
Bug is not seen in `v2.3.2`
![Screen Shot 2019-12-03 at 9 37 04 AM](https://user-images.githubusercontent.com/57409052/70070607-25746080-15b1-11ea-8517-69800e0b95a9.png)
![Screen Shot 2019-12-03 at 9 37 11 AM](https://user-images.githubusercontent.com/57409052/70070613-2907e780-15b1-11ea-97f7-a86ce7720abf.png)

**Comment by sowmyav27** [comment]
Notice a similar issue verifying nodeport on master-head - latest

**Steps:**

- Create a workload and add Node port with `On listening port` say 30300
- Click on create.
- The request sends the value as 30300.
- But a View in API of the workload, gives: `"port": 30330`

```
publicEndpoints": [
{
"addresses": [
"<ip>"
],
"allNodes": true,
"ingressId": null,
"nodeId": null,
"podId": null,
"port": 30330,
...
```
- Edit on the workload, `On listening port` field is set as "Random"

**Comment by alena1108** [comment]
A regression caused by https://github.com/rancher/types/pull/1026

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 61b78ddf7`

Steps:
Create an EC2 Cluster with Amazon cloud provider.
Deploy a workload.
Add port as a load balancer.
Set listening port to anything but 0.
![Screen Shot 2019-12-16 at 9 03 36 AM](https://user-images.githubusercontent.com/57409052/70922461-61f98080-1fe3-11ea-9ac9-12295dec293c.png)
Launch.
Edit the workload.

Upon edit, listening port is unchanged.
![Screen Shot 2019-12-16 at 9 05 27 AM](https://user-images.githubusercontent.com/57409052/70922536-82293f80-1fe3-11ea-8d46-533c80418a01.png)

Port is defined in API:
```
"ports": [
    {
        "containerPort": 80,
        "dnsName": "test-loadbalancer",
        "hostPort": 0,
        "kind": "LoadBalancer",
        "name": "testport",
        "protocol": "TCP",
        "sourcePort": 8081,
        "type": "/v3/project/schemas/containerPort"
    }
],
```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.3-head` `version 78ed261c6`

Steps:
Create an EC2 Cluster with Amazon cloud provider.
Deploy a workload.
Add port as a load balancer.
Set listening port to anything but 0.
![Screen Shot 2019-12-16 at 10 50 14 AM](https://user-images.githubusercontent.com/57409052/70930281-0e426380-1ff2-11ea-8f6e-6ca971eee889.png)
Launch.
Edit the workload.

Upon edit, listening port is unchanged.
![Screen Shot 2019-12-16 at 10 51 08 AM](https://user-images.githubusercontent.com/57409052/70930286-13071780-1ff2-11ea-8510-c9ad74f0080b.png)

Port is defined in API:
```
ports": [
    {
        "containerPort": 80,
        "dnsName": "test2-loadbalancer",
        "hostPort": 0,
        "kind": "LoadBalancer",
        "name": "testport2",
        "protocol": "TCP",
        "sourcePort": 8088,
        "type": "/v3/project/schemas/containerPort"
    }
],
```
