### ISSUE TITLE
Unable to redeploy a vSphere deployed node.

### ISSUE THREAD

**Issue by manubalasree** [rancher/rancher#24351]
*Describe your issue here*

Unable to redeploy a vSphere deployed node. Its not deleted by Rancher from vsphere. Needs manual deletion before creating again

https://www.dropbox.com/s/j0kly3e0seoul99/Screenshot%202019-12-03%2014.41.53.png?dl=0
![Screenshot 2019-12-03 14 41 53](https://user-images.githubusercontent.com/10396579/70036602-17d3d080-15db-11ea-91a2-ed89be8138f8.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`authenticated.cluster.nodes.index`|

**Comment by bdobsonca** [comment]
This issue happens when creating a new node from scratch, I installed 2.3.3 and the first error is that it cannot find the nodes (even though they exist in vSphere) and then this error message. As I require a Rancher installation soon I'll need to install 2.3.2 to get rolling.

**Comment by mcmcghee** [comment]
Experiencing the same exact issue here.

**Comment by char-iot** [comment]
VM is created but not booted. When manually booted, it would say VM already existed.

**Comment by char-iot** [comment]
BUG noted and solved. Workaround for now: https://github.com/rancher/rancher/issues/24315#issuecomment-564173340

**Comment by ikogan** [comment]
This is also happening on 2.4.3 when you re-deploy a node by deleting the node in the node list. If you scale up the number of nodes, new nodes get created fine. If you delete a node in the list, it doesn't delete the VM.
