### ISSUE TITLE
New instances that get created when upgrade is in progress does not show up in the UI , until the upgrade process is fully done.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2436]
Server version - V0.43.0-rc2

Had a service test1 with scale 10.
Using rancher compose CLI , upgrade this service using -batch-size 5  and interval 30000.

./rancher-compose -p testme -f dcu.yml -r rcu.yml up  test1 --force-upgrade --batch-size 5 --interval 30000

I see that after 5 instances of the services are stopped , 5 more instances get created. But the new instances that get created does not show up in the UI even though I see 5 instances being stopped. The newly created instances show up in the UI , only after the upgrade is done and the service state gets changed fro "Upgrading" to "Upgraded".

**Comment by vincent99** [comment]
I haven't looked into this yet but suspect there aren't map entries set in the API until the upgrade is done so there's no way for the UI to know about them.
