### ISSUE TITLE
app update/edit via api should not expect projectID

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#24371]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
updating an app via the api has changed between 2.2.x and 2.3.x. previously passing in a projectID was not required, and probably still shouldnt be required since the app already has the projectID within the object.

**Comment by aemneina** [comment]
One could argue that projectID should not be required on a create as the information is available via the URL. Does create in the web ui hiding adding the projectID info? It is not requested/available as an input.

**Comment by cbron** [comment]
Couldn't reproduce. My steps: 
```
* Edit
  * Create project via UI
  * Edit project via API with empty projectId field and have changes go through succesfully
---
* Create
  * Attempt to create project via curl with projectID missing (example below) and it works. 
```

body:
```
curl --request POST \
  --url CLUSTER_URL/v3/project/local:p-d6gkk/apps \
  --header 'authorization: Bearer token-TOKEN \
  --header 'content-type: application/json' \
  --data '{
"answers": {
"AntiAffinity": "hard",
"defaultImage": "true",
"metrics.enabled": "false",
"replicaCount": "2",
"showMemcachedOptions": "false"
},
"description": "asdf",
"externalId": "catalog://?catalog=library&template=memcached&version=2.9.0",
"multiClusterAppId": "",
"name": "memcached-asdf",
"targetNamespace": "memcached-sqsjn",
"timeout": 300,
"wait": false
}'

Response: 201 created
```

**Comment by aemneina** [comment]
tested this out myself on 2.3.5, seems to be working as expected.

**Comment by jiaqiluo** [comment]
tested in master-head 2e6041d75 and I can deploy an app without passing a project id via the API

**Comment by mrajashree** [comment]
This doesn't happen for global catalogs, happens for project scoped catalogs

**Comment by jiaqiluo** [comment]
The following is observed on v2.3.5:

**Using cluster/project level catalog**
- If the app is deployed using a project level catalog, editing it via API with `projectId = ""` will fails with the following error message
<img width="738" alt="Screen Shot 2020-03-26 at 10 09 38 AM" src="https://user-images.githubusercontent.com/6218999/77678694-c74bfe80-6f4e-11ea-988e-8e2108d38b66.png">

**Using a global level catalog**
- if the app is deployed using a global level catalog, editing it via API without setting the `projectId`, the response of the api call contains no data
<img width="742" alt="Screen Shot 2020-03-26 at 10 17 54 AM" src="https://user-images.githubusercontent.com/6218999/77678825-f8c4ca00-6f4e-11ea-82e2-c9906b1d3ac7.png">

- and the app is gone from the UI although its workloads still exist
- a further investigation indicates that the field `spec.projectName` is empty on the App (project.cattle.io/v3) object in Rancher. Reset it to the proper project id will bring the app back in UI

**Comment by mrajashree** [comment]
The bug was reproduced when:
1. An app is launched using a project-level catalog
2. And a curl command is used to update it without passing the `projectId` key
Something like
```
curl -u "token-xxxx" \
-X PUT \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"annotations":{"lifecycle.cattle.io/create.helm-controller_local":"true"}, 
"answers":{
"cluster.enabled":"true", "cluster.slaveCount":"7", 
....}, 
"appRevisionId":"apprevision-lfj5k", 
"externalId":"catalog://?catalog=p-fhk77/p1&type=projectCatalog&template=redis&version=3.0.2", 
"name":"redis", 
"namespaceId":null, 
"targetNamespace":"redis", 
"timeout":300}' \
'https://rancher/v3/project/local:p-fhk77/apps/p-fhk77:redis'
```

**Comment by jiaqiluo** [comment]
The bug is validated on rancher:v2.4-head ba190e961

Now we can deploy/edit an app using either project or cluster catalog via command line without passing the `projectId` key 

`via command line` means first getting the curl command by tracking the network in Rancher UI then running the command with modified value in a terminal

`without passing the projectId key` means removing the `projectId` item from the request's data section
