### ISSUE TITLE
Can't create EKS cluster in 2.4

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#24372]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

I've tested this in rancher `2.4 master-head (11/21/2019)`276702446

**Scenario 1**: Using all automatic options in the UI.

`This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.
Error creating stack with VPC template: stack failed to create: reason unknown`

**Scenario 2**: using a custom VPC a different VPC is selected in security groups step.

1. Enter Keys and select region us-east-2. Next
2. Select Rancher Service role and left k8s 1.14 selected. Next
3. VPC & Subnet choose custom and select the last vpc-* in the dropdown. Next
4. Make sure to choose custom (The previously selected VPC is not chosen).
5. Select the vpc-* selected previously and all its subnets. Next
6. Notice a different VPC and subnets are selected

**Result:**

Can't provision an EKS cluster.
This is currently blocking other issues for validation: https://github.com/rancher/rancher/issues/23879

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):`2.4 master-head (11/21/2019)`276702446
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud

**Comment by daxmc99** [comment]
Available in master

**Comment by izaac** [comment]
It seems Scenario 1 and 2 are not related to each other so I've opened a separate issue for Scenario 2. https://github.com/rancher/rancher/issues/24481

**Comment by izaac** [comment]
I've tested Scenario 1 in Rancher version: `2.4 master-head (12/09/2019)` 09cbde680

- `us-west-2` worked with default options ✅ 
- `us-east-1` worked with default options ✅ 
- `us-east-2` didn't work with default options. ❌ 

Error: 
`[ERROR] ClusterController c-xxxxx [cluster-provisioner-controller] failed with : error creating stack with VPC template: stack failed to create: Resource creation cancelled`

@daxmc99

**Comment by izaac** [comment]
`us-east-2` worked with default options ✅  I had an issue with VPC limits in the zone but it's working correctly.
