### ISSUE TITLE
[Forwardport] Invalid podSecurityPolicyTemplate poisons Rancher's log

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#24391]
https://github.com/rancher/rancher/issues/23931

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version b189050eb`

Run steps as mentioned here - [#23931](https://github.com/rancher/rancher/issues/23931#issue-518184091)
Error in the terminal -`{"baseType":"error","code":"InvalidBodyContent","message":"podSecurityPolicyTemplate [doesnotexist] not found","status":422,"type":"error"}`
No error is seen in the rancher logs.
