### ISSUE TITLE
[Enhancement] Support Enabling Istio Project UI without installing Rancher Istio

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#24395]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

We currently install and manage Istio manually and do not want to enable the rancher bundled Istio. We do want to give user access to the virtual service and destination rule UI in their projects but that can only be done if we install the Rancher istio. I am proposing that the istio UI for projects be allowed to be enabled even without installing the Rancher Istio since our projects would include these objects that users are managing.

**Comment by munjal-patel** [comment]
We also have similar requirements. We already have a few clusters with Istio already deployed. Unfortunately, we are not able to take advantage of the great management features available in Rancher UI.

**Comment by JoshDaone** [comment]
Just work through the docs and found no option to add an existing istio deployment, except a simple page in rancher to enable istio, little bit confusing from docs and Rancher page.

**Comment by munjalpatel** [comment]
Any updates here? Is this in a roadmap?

**Comment by Feelas** [comment]
Bumping. Is this planned in any near future?
