### ISSUE TITLE
Add South America (São Paulo) to EKS regions (sa-east-1)

### ISSUE THREAD

**Issue by jugleni** [rancher/rancher#24400]
Amazon Elastic Kubernetes Service (EKS) is now available in the AWS São Paulo region (sa-east-1). 

https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-eks-generally-available-in-sao-paulo-region/?nc1=h_ls

https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

EKS not supported on sa-east-1 rancher/rancher#23895

**Comment by jugleni** [comment]
Hello @deniseschannon
EKS is available for the South America (Sa-East-1) region

this is your comment on another region, could you check the sa-east-1 region?

Thank you

**Comment by jugleni** [comment]
https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-eks-generally-available-in-sao-paulo-region/?nc1=h_ls

https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

**Comment by soumyalj** [comment]
Tested with Rancher server v2.3.4-rc3.

Created a EKS cluster using UI in South America  sa-east-1 region. Cluster creation was successful. It was verified that the Cluster landed in the South America sa-east-1 region.
<img width="1659" alt="Screen Shot 2019-12-13 at 2 55 07 PM" src="https://user-images.githubusercontent.com/18536626/70837457-99d0b000-1db8-11ea-87fa-40dc8c64e2f6.png">

API Snippet

```
"amazonElasticContainerServiceConfig": {
"accessKey": "abcdef",
"ami": "",
"associateWorkerNodePublicIp": true,
"desiredNodes": 3,
"displayName": "",
"driverName": "amazonelasticcontainerservice",
"instanceType": "m5.large",
"keyPairName": "",
"kubernetesVersion": "1.14",
"maximumNodes": 3,
"minimumNodes": 3,
"nodeVolumeSize": 20,
"region": "sa-east-1",
"serviceRole": "",
"sessionToken": "",
"subnets": null,
"userData": "#!/bin/bash\nset -o xtrace\n/etc/eks/bootstrap.sh ${ClusterName} ${BootstrapArguments}/opt/aws/bin/cfn-signal --exit-code $? --stack  ${AWS::StackName} --resource NodeGroup --region ${AWS::Region}",
"virtualNetwork": ""
}
```
