### ISSUE TITLE
Choosing "upgrade" option for a DNS service results in an empty page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2440]
Server version - V0.43.0-rc2

Create a "Service Alias".
Choose "upgrade" option on this service.
User is presented with empty page.

User should have the ability to change labels for DNS service as part of upgrading service.

**Comment by vincent99** [comment]
Upgrade removed for everything but 'regular' services.

**Comment by sangeethah** [comment]
Tested with Server Version - V0.43.0-rc3
"Upgrade" option is not presented in the UI for "DNS services" any more.
