### ISSUE TITLE
Openstack cloud provider: "instance name" not found

### ISSUE THREAD

**Issue by Born2Bake** [rancher/rancher#24403]
**What kind of request is this (question/bug/enhancement/feature request):**

Openstack cloud provider is added and cant find an instance

**Steps to reproduce (least amount of steps as possible):**

The main purpose - to integrate rancher into openstack and use cinder as a persistent storage for rancher.

Following this guide - https://www.vkhitrin.com/blog/deploying-rancher-on-openstack/ [Everything is deployed and working fine]
Following this guide - https://www.vkhitrin.com/blog/adding-openstack-cloud-provider-to-rancher-cluster/ [Added cloud provider details in yaml file, added rancher agent on machine and provisioning is proceeded. However, after etcd and worker provisioning, deployment is stuck with an error and cannot find "instance name", in my case instance name is "agent".

After that, the plan is to use cinder as a storage class https://www.vkhitrin.com/blog/openstack-cinder-as-a-persistent-storage/

**Result:**

http://prntscr.com/q69twh - log file with an error.

**Other details that may be helpful:**

In case if the issue cannot be fixed via configuration changes, is there any way how I can add instance id instead of using instance name? http://prntscr.com/q69v1o

Is there any way how I can add cinder as a persistent storage just using openstack driver? Cause even though openstack driver is deployed and rancher can create, start and provision instances for k8s cluster in openstack, I still dont have an option to deploy cinder volume in Storage -> Storage class form.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

Single node 2.3.3
rancher/rancher:latest

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 

Custom/Openstack

- Machine type (cloud/VM/metal) and specifications (CPU/memory): 

cloud-vm

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

Thank you very much

**Comment by Born2Bake** [comment]
any help on that?

**Comment by CiaraCode** [comment]
Did you ever find this out?
