### ISSUE TITLE
[UI] Show System project first when selecting a project

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#24401]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Description**
For large Rancher installations, such as 20+ clusters with 50+ projects, it's difficult for the administrator to navigate to the System project, which is done often for administrators. The Search field cannot be leveraged, because searching on "System" returns the System project for every cluster.

A possible recommendation to make this easier is to always list the System project first in the UI.

Specifically referring to this UI:
<img width="402" alt="image" src="https://user-images.githubusercontent.com/468462/70173912-b9652b80-1688-11ea-8c14-6d09a064a265.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.3

gz#7393

**Comment by leodotcloud** [comment]
Not relevant with the new UI.
