### ISSUE TITLE
Vsphere Node Template change issue

### ISSUE THREAD

**Issue by ibrokethecloud** [rancher/rancher#24416]
**What kind of request is this (question/bug/enhancement/feature request):** BUG

**Steps to reproduce (least amount of steps as possible):**

1. Create a Vsphere Node Template in Rancher 2.3.3
2. Specify Creation Method as Content Library, chose an image and save the node template.
3. Edit the node template and change Creation Method to Deploy from Template and save node template.
4. Inspect API for this node template, and the contentLibrary key is not cleared.

**Result:**
Provisioning breaks the driver is unable to find the template in the Content Library.

rancher-67bfcf9977-ntrgw rancher 2019/12/04 22:47:36 [ERROR] NodeController c-xd5zl/m-ktnxk [node-controller] failed with : Error creating machine: Error in driver during machine creation: POST https://myvmware:443/rest/com/vmware/content/library/item/file/id:c983c5a3-89b5-43ba-aa1d-220f1e7868cf?~action=get: 404 Not Found

**Other details that may be helpful:**
When the template source is changed the contentLibrary key should be cleared.

This causes the code execution to go down the wrong code execution branch:

https://github.com/rancher/machine/blob/master/drivers/vmwarevsphere/vsphere.go#L343

This causes cluster provisioning to fail.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): VMWARE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.16

```
(paste the output here)
```

- Docker version (use `docker version`): Docker CE 19.03

```
(paste the output here)
```

**Comment by luthermonson** [comment]
this will probably need both a UI change to unset this field and i should be able to add logic in rancher machine to short circuit the template library code.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 9c1ee616e

* Needs UI fix

* Created node template to deploy from content library
* Edited node template to deploy from datacenter
* `contentLibrary": "wrangler-cl01",` is still set in the node template

**Comment by luthermonson** [comment]
@bmdepesa UI fixes coming here: https://github.com/rancher/rancher/issues/24314

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 565ef1a85

Backend is functional, so closing this issue and will validate UI separately. 

* Create a node template which deploys from content library
* Edit to deploy from datacenter
* Node template still shows contentLIbrary field with data: #24747
* Create a cluster from the edited node template
* Cluster is created from correct data source (content library is ignored)
