### ISSUE TITLE
Choosing "upgrade" for "External Services"/ "LB services" shows a page with all fields of a regular service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2441]
Server Version - V0.43.0-rc2

Create an external service.
Choosing "upgrade" for "External Services" shows a page with all fields of a regular service which are editable.

The only supported field that should be allowed to change as part of upgrade should be labels?

The same behavior is also seen for LB service.

**Comment by vincent99** [comment]
Upgrade removed for everything but 'regular' services.

**Comment by sangeethah** [comment]
Tested with Server Version - V0.43.0-rc3
"Upgrade" option is not presented in the UI for "External Services"/ "LB services" any more.
