### ISSUE TITLE
Manage Cluster Scans role is available at both Global and Cluster level

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24420]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Navigate to Global --> Security --> Roles

**Expected Result:**
Manage Cluster Scans role is at only one level.

**Actual Result:**
Manage Cluster Scans role is available at both Global and Cluster level

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - latest
- Installation option (single install/HA): single

**Comment by leodotcloud** [comment]
We have now removed "Manage Cluster Scans" role. Can we close this issue?

**Comment by sowmyav27** [comment]
**Verified on UI on master-head latest commit id: `48a2c4ffc`**

go to Global --> Security --> Roles
Under Global and Cluster, "Manage Cluster Scans" is not listed anymore
Under v3/globalroles and v3/roleTemplates/, "Manage Cluster Scans" is not listed.
