### ISSUE TITLE
InvalidBodyContent 422: failed to parse key error seen in rancher logs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24423]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Run Security Scans on a cluster

Rancher logs show error `2019/12/04 19:29:17 [ERROR] Error certs=InvalidBodyContent 422: failed to parse key: key must be PEM encoded PKCS1 or PKCS8: x509: failed to parse private key (use ParseECPrivateKey instead for this key format) parsing cert sonobuoy-plugin-rancher-kube-bench-685a331719c74e80.` when the Security scans are run on the cluster.

**Note:**
This does NOT happen with every run of security scan.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by leodotcloud** [comment]
The error message is coming from here: https://github.com/rancher/rancher/blob/v2.3.5/pkg/cert/cert.go#L41

When the security-scan is scheduled, a self signed certificate is generated by the backend tool and it happens to be in a format that the code doesn't recognize. Need to add handling of this other kinds of cert formats or ignore this check for "security-scan" namespace.

**Comment by izaac** [comment]
I also reproduced this by doing a `2.4 master-head (06/02/2020)` **HA** install. commit id 1a03ecea3

Chart Name: `2.4.0-alpha1`
Helm Repo: `alpha`
Image Tag: `master-head`


After installation login (or using kubectl) and look at the logs of the Rancher pods. It will show logs like these:

```
2020/02/06 21:09:12 [ERROR] Error certs=InvalidBodyContent 422: failed to parse key: key must be PEM encoded PKCS1 or PKCS8: x509: failed to parse private key (use ParseECPrivateKey instead for this key format) parsing cert tls-rancher. Will not display correctly in UI
2020/02/06 21:09:12 [ERROR] Error certs=InvalidBodyContent 422: failed to parse key: key must be PEM encoded PKCS1 or PKCS8: x509: failed to parse private key (use ParseECPrivateKey instead for this key format) parsing cert serving-cert. Will not display correctly in UI
```

**Comment by izaac** [comment]
I no longer see these errors `InvalidBodyContent 422` in Rancher `2.4 master-head (02/07/2020)` commit id:  f5482571a

I've checked the three Rancher pods logs.

Same setup as my previous comment: 
Chart Name: `2.4.0-alpha1`
Helm Repo: `alpha`
Image Tag: `master-head`
Rancher generated self-signed certificates.

@sowmyav27 @deniseschannon

**Comment by sowmyav27** [comment]
verified on master-head - commit id: `3fc6715ca`

Run Security Scans on a cluster deployed.

Error `Error certs=InvalidBodyContent 422:...` is NOT seen in the Rancher logs.
