### ISSUE TITLE
Support for different version of scan tool

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24422]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Rancher must support different versions of scan tool

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Comment by leodotcloud** [comment]
Using the API, it's possible to override the benchmark version used. By default we use `rke-cis-1.4` and we don't have any other version for RKE available yet. But for testing purposes, we can pass `cis-1.4` which will run the upstream tests directly (which will result in lot of failures for RKE)

**Comment by sowmyav27** [comment]
**Reopening this issue**

**verified on latest master-head**

**Scenario#1**

- On entering overrideBenchmarkVersion : "cis-1.4" in the `runSecurityScan` API, the default `rke-cis-1.4` is run. 
- No additional failures are seen on the cluster scan as compared to Scan run from `rke-cis-1.4` .

**Expected:**
"cis-1.4" related Scan should be run on the cluster, which should have resulted in a lot more failures as mentioned in https://github.com/rancher/rancher/issues/24422#issuecomment-565579117


**Scenario#2**
- On entering invalid value for overrideBenchmarkVersion, the default `rke-cis-1.4` is run. 

**Expected:**
Users should be presented with an error, stating the value is invalid. 


**Scenario#3**
- overrideBenchmarkVersion should show the AVAILABLE values in the dropdown in the API UI for runSecurityScans.
- This can be achieved only when there is support for overrideBenchmarkVersion as a first class object.

**Comment by sowmyav27** [comment]
Scenario#3 -- As per discussions, was decided to be as is.

Scenario#1 and Scenario#2 -- need to be addressed for alpha release.

**Comment by sowmyav27** [comment]
**Verified on master head - commit id: `656781c34`**

**Scenario#1**
Verified the fix

- On entering overrideBenchmarkVersion : "cis-1.4" in the `runSecurityScan` API, the default `rke-cis-1.4` is run. 
- Additional failures are seen
- Download report.
- The report shows the scan tool version run is `Version: cis-1.4`


**Scenario#2**
- On entering invalid value for overrideBenchmarkVersion, say "1.1.1.1", the scan errors out. with status: `Error`
<img width="1310" alt="Screen Shot 2019-12-20 at 3 15 19 PM" src="https://user-images.githubusercontent.com/26032343/71298186-c72ed800-233b-11ea-9610-434cc8cb978e.png">
- Download report - gives no data in the csv
- Scan details page - has no details
- On accessing the report in api - `v3/clusterScans/<cluster-id>:<scan-id>/report` - gives

```
{
"baseType": "error",
"code": "ServerError",
"message": "configmaps \"cis-1576883698793714610\" not found",
"status": 500,
"type": "error"
}
```

**Comment by sowmyav27** [comment]
**Verified on master-head - latest - commit id: ``48783530d**

**Steps:**

- On entering overrideBenchmarkVersion : "1.1.1.1" in the runSecurityScan API, (invalid benchmark value)
- The following error is seen on the API UI

```
{

    "baseType": "error",
    "code": "InvalidOption",
    "message": "invalid override benchmark version specified",
    "status": 422,
    "type": "error"

}
```

- On entering overrideBenchmarkVersion : "cis-1.4" in the runSecurityScan API, the cis-1.4 scan tool version is run.
- Additional failures are seen
- Download report.
- The report shows the scan tool version run is Version: cis-1.4
