### ISSUE TITLE
[UI] - Cannot create global role binding 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#24438]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- as admin, enable Auth with your choice, Activity Directory in my case
- go to Global → Security → Groups → Assign Global Role
- Search and select group, testgroup2 in my case,  from the dropdown list 
- select the custom global role a-catalog
- select the builtin global role manage settings
- Click Create 

**Result:**
- the UI is stuck in the saving state 
<img width="1505" alt="Screen Shot 2019-12-05 at 11 40 24 AM" src="https://user-images.githubusercontent.com/6218999/70263636-11b52f80-1754-11ea-9ac3-c490576894fe.png">

- the browser's console shows errors

in Chrome
<img width="1465" alt="Screen Shot 2019-12-05 at 11 34 42 AM" src="https://user-images.githubusercontent.com/6218999/70263502-c00ca500-1753-11ea-96f2-08b2fb9f9868.png">

in Firefox 
<img width="1460" alt="Screen Shot 2019-12-05 at 10 48 49 AM" src="https://user-images.githubusercontent.com/6218999/70263513-c569ef80-1753-11ea-9e59-5c5857426572.png">

 
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
master-head e74c23940
- Installation option (single install/HA):
single install

**Comment by westlywright** [comment]
The key to this issue is that you have a global role with NO rules.

**Comment by jiaqiluo** [comment]
the bug fix is validated in master-head c08cedf

Steps:
- create a global role `a-empty-role` with no rules selected in it

<img width="1491" alt="Screen Shot 2019-12-06 at 11 45 08 AM" src="https://user-images.githubusercontent.com/6218999/70347502-e72fa900-181d-11ea-978f-ba19416bfc49.png">

- assign the role to a group 

Results:
- the error mentioned in the issue does not show up anymore
<img width="1455" alt="Screen Shot 2019-12-06 at 11 45 16 AM" src="https://user-images.githubusercontent.com/6218999/70347510-ebf45d00-181d-11ea-998f-f3c09aa7632a.png">
