### ISSUE TITLE
Failures in the report for mixed nodes are reported incorrectly

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24431]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On a cluster(3 etcd, 2 control plane and 3 worker nodes), run scans
- Failure is reported for a benchmark for the etcd nodes when checked in the report generated in the API.

```
"n": [
          "etcd1-ip-addr",
          "etcd2-ip-addr",
          "etcd3-ip-addr"
         ]
```
The benchmark test is applicable for master and etcd nodes.

**Expected Result:**
Only etcd nodes should be reported as failure on the UI

**Actual Result:**

- All nodes, master and etcd are reported as failure in the report on the UI.
- 5 nodes - 3 etcd and 2 control plane nodes are shown failed for this benchmark test

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest commit id-`df31802ac`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by deniseschannon** [comment]
Per convo between @codyrancher and @leodotcloud, this is a backend issue.

**Comment by deniseschannon** [comment]
@leodotcloud when it's fixed, let's move this to `team/ui` for @codyrancher to pick it up.

**Comment by sowmyav27** [comment]
When the status of the test is "M", the API does not return the set of failed nodes.

**Comment by leodotcloud** [comment]
This issue is seen when both master and etcd roles are on the same node. Will fix it. @codyrancher you can continue to fix the UI code without waiting for the backend fix by creating a split role cluster.

**Comment by sowmyav27** [comment]
@leodotcloud Logged a separate issue - https://github.com/rancher/rancher/issues/24540 to track the one mentioned here https://github.com/rancher/rancher/issues/24431#issuecomment-564756298

**Comment by leodotcloud** [comment]
This was a problem with a single node having multiple roles. Fixed.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `61b78ddf7`**

**On a cluster - 8 nodes, 3 etcd, 3 worker and 2 control planes.**

- Run CIS Scan.
- Expected one test - test1 to fail.
- The state of test1: Mixed (expected)
- The list of nodes shows both - list of nodes where the test failed (status: Fail) and list of nodes where the test passed (status: Pass)
