### ISSUE TITLE
Rancher catalog refresh fails if Helm chart versions are using SemVer with build numbers

### ISSUE THREAD

**Issue by al45tair** [rancher/rancher#24430]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Publish a Helm chart with a version number like 1.2.3+5678. (This will make a file in the repository called something like my-chart-1.2.3+5678.tgz). Now refresh the catalog in Rancher.

**Result:**
The catalog refresh seems to stall somehow.

**Other details that may be helpful:**
Charts are supposed to support SemVer 2, so build numbers are theoretically permitted.

**Environment information**
- Rancher version: v2.3.0
- Installation option (single install/HA): single install

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24863
