### ISSUE TITLE
LB does not write cookie settings for https to haproxy.cfg

### ISSUE THREAD

**Issue by flantel** [rancher/rancher#2443]
Hi

Using the latest releases:
Rancher 	v0.42.0
Cattle 	v0.102.0
User Interface 	v0.57.0
Rancher Compose 	v0.4.3

If I create a load balancer service for SSL (either directly or by uploading compose files) and set cookies (in my case "insert indirect nocache", but I have tried all combinations) the cookie settings do not get written to the SSL backend in haproxy. If I use the same settings but for a plain http port, the cookie line is written.

Additionally, if I create a load balancer for both https and http, the cookie line is written for the http backend but not for the https.

**Comment by cusspvz** [comment]
Same here also.

**Comment by alena1108** [comment]
@flantel @cusspvz bug on our side; cookie policies are not being set in haproxy.cfg for https

**Comment by sangeethah** [comment]
Tested with build from master - Oct 30

 cookie settings for https are now saved to  haproxy.cfg

<img width="669" alt="screen shot 2015-10-30 at 2 45 30 pm" src="https://cloud.githubusercontent.com/assets/4266958/10858805/fe9e709a-7f14-11e5-93eb-a05bc60c3443.png">

![Uploading Screen Shot 2015-10-30 at 2.45.00 PM.png…]()
