### ISSUE TITLE
UI - Cannot fetch groups/teams/organizations when configuring external Authentication

### ISSUE THREAD

**Issue by abryko** [rancher/rancher#24437]
**What kind of request is this (question/bug/enhancement/feature request):** BUG

**Steps to reproduce (least amount of steps as possible):**

* Brand new Rancher 2.3.3 cluster
* Configure an external authentication service from Rancher UI (eg. github)
* Once done, under *Site Access*, try to fetch groups/organizations

**Result:**
Groups cannot be fetch from the UI when using Rancher 2.3.3 onward.

**Other details that may be helpful:**
javascript error during the procedure:
```
TypeError: t.findTranslationByKey is not a function
TypeError: Cannot read property 'parentElement' of undefined
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |

**Comment by ludopaquet** [comment]
Same here, this is pretty annoying, anyone knows a workaround maybe with the api ?

**Comment by sowmyav27** [comment]
**On `rancher:v2.3.3`** - Reproduced the issue.

**Steps:**

- Enable Github Auth on the UI.
- Under Site Access Type in user/organization name in "Authorized Users and Organizations" Input field. 
- User is able to select the user/organization. NO error is seen on the UI/console.
- But on clicking the dropdown arrow in the "Authorized Users and Organizations" Input field, Error is seen in the Console

**Error:** 
```
component.js:142 Uncaught (in promise) TypeError: t.findTranslationByKey is not a function
    at n.<anonymous> (component.js:142)
    at n.a.get (metal.js:2984)
    at ie (metal.js:1592)
    at t.r.compute (glimmer.js:535)
    at t.value (glimmer.js:384)
    at e.value (runtime.js:552)
    at e.t.initialize (reference.js:454)
    at e.t.peek (reference.js:429)
    at Function.n.initialize (runtime.js:901)
    at Object.evaluate (runtime.js:873)
```

**Comment by westlywright** [comment]
Available in `latest-2.3`. No master fix as the issue was not present in that branch.

**Comment by sowmyav27** [comment]
**Verified on 2.3-head with ui tag: latest-2.3**

Steps:

- Enable Github Auth on the UI.
- Under Site Access Type in user/organization name in "Authorized Users and Organizations" Input field.
- User is able to select the user/organization. NO error is seen on the UI/console.
- On clicking the dropdown arrow in the "Authorized Users and Organizations" Input field, NO Error is seen in the Console
<img width="609" alt="Screen Shot 2019-12-10 at 4 26 43 PM" src="https://user-images.githubusercontent.com/26032343/70580820-f7bb8880-1b69-11ea-9a65-5a58e35bd3c8.png">

**Comment by ludopaquet** [comment]
Thx, a workaround for the 2.3.3 with a proper api-key :
POST https://yourrancher/v3/projectroletemplatebinding
{"type":"projectRoleTemplateBinding","projectId":"your projectid","groupPrincipalId":"keycloak_group://your_group","roleTemplateId":"project-owner"}

**Comment by Oats87** [comment]
My `2.3.4` environment is still exhibiting these problems with Rancher UI version `2.3.25`
