### ISSUE TITLE
Rancher Azure Creates Network Security Groups for every VM

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/rancher#24449]
When using the Azure provisioner to create Kubernetes clusters, we ran into a problem where the provisioner creates a Network Security Group for every VM. Our Azure network team limits our ability for SPN's to bind directly to a network security group, so we are not able to proceed with creating the cluster in Azure.

We should be able to provide an existing Network Security Group to the azure config in the node template.

**What kind of request is this (question/bug/enhancement/feature request):**
bug and feature request

**Steps to reproduce (least amount of steps as possible):**

**Result:**
```
Error creating machine: Error in driver during machine creation: 
network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- 
Original Error: autorest/azure: Service returned an error. Status=403 
Code="LinkedAuthorizationFailed" Message="The client 'f5672b5b-<snip>' with object id 'f5672b5b-<snip>' has permission to perform action 
'Microsoft.Network/networkInterfaces/write' on scope '/subscriptions/<snip>/resourceGroups/shipyard-test/providers/Microsoft.Network/networkInterfaces/test-cluster-master1-nic'; 
however, it does not have permission to perform action 
'Microsoft.Network/networkSecurityGroups/join/action' on the linked scope(s) 
'/subscriptions/<snip>/resourceGroups/shipyard-test/providers/Microsoft.Network/networkSecurityGroups/test-cluster-master1-firewall' or the linked scope(s) are invalid.";
Timeout waiting for ssh key
```

**Other details that may be helpful:**
There is an open PR in rancher/machine#43         that may help address the issue, but that PR might be missing the required resource group where the existing NSG resides. (similar to how the vnet is defined: `[resourcegroup:]vnet`)

**Environment information**
- Rancher version 2.3.3

**Comment by aiyengar2** [comment]
Providing an existing security group to the Azure Config of the node template should be supported after https://github.com/rancher/rancher/issues/25342 is resolved. https://github.com/rancher/machine/pull/77 should address the changes proposed in https://github.com/rancher/machine/pull/43 as well. The PR allows you to supply the existing NSG's ARM resource identifier (which contains information on the resource group where the existing NSG resides).

**Comment by aiyengar2** [comment]
However, based on your error statement and the [Azure docs](https://docs.microsoft.com/en-us/azure/virtual-network/manage-network-security-group), it seems like the error you're encountering is due to missing `Microsoft.Network/networkSecurityGroups/join/action` permissions, which allows you to `Associate a network security group to a subnet or network interface`. This will not be resolved with the above PR as we still require the ability to join your existing NSG with the network interface created for each machine.

**Comment by aiyengar2** [comment]
Closing this out in favor of https://github.com/rancher/rancher/issues/25342.

**Comment by HighwayofLife** [comment]
@aiyengar2 checking on this. VMs created in Azure can either have an assigned NSG, or they can use a Subnet which can have its own NSG, so no NSGs would need to be created at all in the second case. Is this what the change does?

**Comment by aiyengar2** [comment]
@HighwayofLife no, this change allows you to use an existing NSG for all nodes in your cluster; however, this is done by attaching the provided NSG to each node's network interface.

Using an NSG that is already attached to the subnet is not supported.
