### ISSUE TITLE
[CIS] - Clusterscan 'Activating' is the wrong color

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#24440]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Run a cluster scan and view the state badge.

**Result:**
The state badge is the color red instead of blue.
![Screen Shot 2019-12-05 at 12 01 30 PM](https://user-images.githubusercontent.com/55104481/70265178-15968100-1757-11ea-82ff-638536f60358.png)

**Other details that may be helpful:**
Here's the relevant part of the clusterScan response:
```       
{
    "state": "activating",
    "status": {
        "conditions": [
            {
                "lastUpdateTime": "2019-12-05T18:48:00Z",
                "status": "True",
                "type": "Created"
            },
            {
                "status": "Unknown",
                "type": "Completed"
            }
        ],
        "type": "/v3/schemas/clusterScanStatus"
    },
    "transitioning": "error",
    "transitioningMessage": "",
    "type": "clusterScan",
    "uuid": "c2d2f5c2-178f-11ea-b545-0242ac110003"
}
```

```"transitioning": "error"``` is making the state badge enter an error state.

The color is getting set in the code [here](https://github.com/rancher/ui/blob/master/lib/shared/addon/mixins/cattle-transitioning-resource.js#L540).

And we can see _isError_ is linked to _transitioning_ [here](https://github.com/rancher/ui/blob/master/lib/shared/addon/mixins/cattle-transitioning-resource.js#L459).

**Comment by leodotcloud** [comment]
I have introduced a new state "Running" for the transition. This needs to be shown in Blue color.

**Comment by sowmyav27** [comment]
Verified on latest master-head. - commit id: `a106f2aa4`
The State is `Running` when the scan is being run and is `Active` when the report has been generated.
<img width="1312" alt="Screen Shot 2019-12-20 at 8 17 55 AM" src="https://user-images.githubusercontent.com/26032343/71268203-4357fa00-2301-11ea-816f-b9e53e4b2e61.png">
