### ISSUE TITLE
User is not able to override skip from API on entering a blank value in skip

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24444]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. On a cluster, Run Scans
2. When the report generates, on any failed test, click on Skip. (when you go to the report details page)
3. Now run the Scan again. 
4. Verify the report. The test marked as skip, will be skipped.
5. From the API UI, click on runSecurityScan.
6. Leave the skip input textbox as blank. Click on Send request. 

Request sent:
```
{
"debugMaster": false,
"debugWorker": false,
"skip": [ ]
}
```

**Expected Result:**
No tests should be skipped, as the skip value is blank.

**Actual Result:**
The test marked as Skip in Step 2, will be skipped. User is NOT able to override from the API.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by leodotcloud** [comment]
The new skip value is no more an array of string. Here is a sample: `{"skip": { "rke-cis-1.4": [ "1.1.1", "1.2.2"] }}`

**Comment by sowmyav27** [comment]
As per discussions, skip will continue to be an input of array of strings. Reopening this issue for the original issue to be fixed.

**Comment by sowmyav27** [comment]
**Verified on master head - commit id: `48a2c4ffc`**

- On passing empty array in the API UI - 
```
{
"debugMaster": false,
"debugWorker": false,
"overrideBenchmarkVersion": null,
"overrideSkip": [ ]
}
```
- Security Scan runs fine from API UI.

- **From API**
```
curl -u "<token>" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
--data-binary '{"debugMaster":false,"debugWorker":false,"overrideBenchmarkVersion":null,"overrideSkip":[]}' \
'https://<rancher-server>/v3/clusters/c-xvwp2?action=runSecurityScan' --insecure
```
- Security Scan runs fine from API.
- Skips in the config map are overriden. 
- No skips happen in this particular run
