### ISSUE TITLE
rancher 2.3.3 resize vsphere vm disk

### ISSUE THREAD

**Issue by nickvth** [rancher/rancher#24453]
**What kind of request is this feature request:**

When provisioning from template, rancher is not setting the correct disk size for the vm in vmware.

**Steps to reproduce (least amount of steps as possible):**

Create cluster vsphere with a vm template
Set node template 30GB and template has default 20GB disk

**Result:**

root os will say 30GB and LVM and disk in vmware is still 20GB from template

**Other details that may be helpful:**

Rancher 2.3.3

**Comment by eliaoggian** [comment]
Same Here. 

I think that the correct behavior should be not allowing a smaller disk than template disk size, and allow for bigger values. 
Then the resizing of the partitions and fs would happen with cloud-config.

**Comment by luthermonson** [comment]
https://github.com/rancher/machine/pull/60

**Comment by luthermonson** [comment]
to reproduce this functionality working. using the disco dingo ubuntu ova you can change the disk size in the node template to anything great than 10gb and you will have the primary drive resized. do lsblk to see the resize.

e.g.
```root@atatat1:~# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0       2:0    1    4K  0 disk
loop0     7:0    0   89M  1 loop /snap/core/7713
loop1     7:1    0 54.7M  1 loop /snap/lxd/12100
sda       8:0    0 19.5G  0 disk
├─sda1    8:1    0 19.4G  0 part /
├─sda14   8:14   0    4M  0 part
└─sda15   8:15   0  106M  0 part /boot/efi
sr0      11:0    1   48K  0 rom
sr1      11:1    1   44K  0 rom```

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 5dcdd79bc
rancher/rancher:master-head 7578b3c76

* Reproduced in v2.3.3, node created with 10gb regardless of size
* Created node template using ubuntu OVA & changed disk size to 40gb
* Node was provisioned with the correct disk size
