### ISSUE TITLE
Scale of no containers in UI should have the same "scale up" size that spans the entire box

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2445]
UI v0.59.0

Steps to Reproduce:
1. Create service with scale of 0.

Result: Scale up box looks weird as it doesn't span the whole box. 

Expected Result: It should match the size of the ubuntu2 service in the photo. 

![screen shot 2015-10-26 at 9 57 03 am](https://cloud.githubusercontent.com/assets/11410997/10736009/0a7600a4-7bc8-11e5-838f-ba339cb2571e.png)

**Comment by vincent99** [comment]
No longer applies, there are no boxes for services..
