### ISSUE TITLE
feat: Allow patching/adding to the yaml deployment descriptors from the UI

### ISSUE THREAD

**Issue by ichtestemalwieder** [rancher/rancher#24451]
Feature Request: 
The Rancher UI is very limited in terms of what "entries" of the deployment descriptor can be specified. As soon as you require further changes to deployment descriptor (what is almost every time necesseary), it gets very ugly and timeconsuming. 
However there would be an easy solution by adding a generic "patch" Section, that allows to specify custom yaml patch statements to change or augment the deployment descriptors. (Its like using kubectl patch" from the UI. )

Please see the mockup, it makes it quite obviours what is required. 

![image](https://user-images.githubusercontent.com/54768881/70301996-3533b500-17fc-11ea-913e-06f75928211a.png)

Important note: Rancher should (with new deployments) first create in memory the final descriptor and then apply the patch in memory before, then deploying this final deployment descriptor. So this should not retriger a deployment but rather create one final descriptor and deploy this final result.

**Comment by vincent99** [comment]
This would be very obtuse to use, and easy to get wrong.  It is also not at all straightforward to implement, you're basically calling for knowing the merge criteria for all the involved types and then implementing strategic-merge-patch in the client.

What are you looking to edit that is missing?  The UI has controls for very close to everything (including what you're showing) except editing multiple containers at a time (which you can do with multiple saves adding a sidecar at a time).

If you want to define workloads (or anything else) with YAML, the import screen or in-browsers kubectl will do that..

**Comment by ichtestemalwieder** [comment]
Thanks very much vincent99! With your comment I realized: 

Feedback: 
On my monitor the "Show advanced options" link is not very good to see as its cutted by my tasklist, so it is not really "above the fold" and furthermore very much shiftet to the right, which makes it even harder to notice on very wide screens.  A usability improvement might be to show this "link" more prominently (=on the left), or even get rid of it at all and show these sections directly. As the hidden sections are all very important, for example as the resource limit section, that everyone should use all the time. 

This was my main use-case for patches but there are further like setting a "secretName" for TLS Certs to be stored (with Cert-Manager), that is also not possible at the UI... But I am closing this ticket, as the main use-case(s) are indeed possible via the UI. Sorry for the inconvenience.
