### ISSUE TITLE
UI - Ability to set MTU in cluster yaml/config

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#24460]
UI for https://github.com/rancher/rancher/issues/24096

**Comment by westlywright** [comment]
Is there a reason the MTU value is a string? Wouldn't it make more sense for this value to be an int? Should there be a default value in the schema? Seems like 1500 should be the default.

**Comment by superseb** [comment]
Hmm, I took it from other types like https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/rke_types.go#L165 but it seems inconsistent in types as I also see some int types. This can be easily changed (besides some vendoring). As this is an override from default behavior, we don't set a default.

**Comment by westlywright** [comment]
@superseb I think we should change the type if there are no objections. There won't be anything for me to change on the frontend for this so it won't hold up my PRs. But this could prevent any issues from users using the api and sending a number rather than string.

**Comment by jiaqiluo** [comment]
The enhancement is validated in  Rancher v2.3-head baa64d48a with UI v2.3-dev

Check 1: there is a field for `network MTU` in the cluster creation page 
<img width="838" alt="Screen Shot 2019-12-17 at 3 27 07 PM" src="https://user-images.githubusercontent.com/6218999/71039730-15e13580-20e2-11ea-8b64-d35612e9202e.png">

Check 2: create RKE-provisioned clusters with different CNI (Canal, Calico, Weave) and  `Network MTU: 4500`

Result: 
- For the cluster with Canal, go to project `System` to check the Config Map `canal-config` to see the value for `mtu`
 
<img width="1423" alt="Screen Shot 2019-12-13 at 1 24 01 PM" src="https://user-images.githubusercontent.com/6218999/70831008-b962db00-1dae-11ea-8736-dee2d834dc14.png">


- For the cluster with Calico, go to project `System` to check the Config Map `calico-config` to see the value for `veth_mtu`
<img width="1463" alt="Screen Shot 2019-12-13 at 1 45 19 PM" src="https://user-images.githubusercontent.com/6218999/70831063-d39cb900-1dae-11ea-883b-0ad750ea6d6e.png">

- For the cluster with Weave, exec into the workload `weave-net` under the project `System`  to check environment variables 
```
/home/weave # env | grep  MTU
WEAVE_MTU=4500
```

Check 3: leave the field blank while creating the cluster with Canal

Results:
- the MTU value is not set in the config map, which is the expected default behavior

**Comment by jiaqiluo** [comment]
blocked by https://github.com/rancher/rancher/issues/24647 in master-head

**Comment by jiaqiluo** [comment]
the validation is done and passed in `Rancher:mater-head` 48a2c4ffc UI `vmaster-dev` with the same tests in 2.3-head https://github.com/rancher/rancher/issues/24460#issuecomment-566784205
