### ISSUE TITLE
Pipeline - multiple clusters on same git repo

### ISSUE THREAD

**Issue by Quark-Fusion** [rancher/rancher#24478]
question/enhancement

Is it possible to limit pipeline execution by cluster name (or branch name, but store it in project rather that in ".rancher-pipeline.yml")?

For example, we have separate production and development clusters.

**Comment by juanludlf** [comment]
there is an open feature request: https://github.com/rancher/rancher/issues/17474

**Comment by danilotorrisi** [comment]
I would love to have the same features, we use seperate cluster for dev, staging and production running the same pipeline. The issue is that we cannot limit the pipeline execution on specific branches ( for example only run the dev pipeline on dev branch ect )
