### ISSUE TITLE
feat: Rancher UI - Node Detail Screen = Show the workloads/pods per Node 

### ISSUE THREAD

**Issue by ichtestemalwieder** [rancher/rancher#24471]
Feature Request: 
Problem: 
what I a desperately missing on the node scree (in the Rancher UI) is to drill down to the workloads/pods that are scheduled on the node. In smaller clusters you do quite a lot of "rebalancing and manual scheduling" of workloads base on performance metrics and it would be very helpfull to see directly what is currently running on a specific node. 
(Furthermore a Performance Metric Dashboard (as currently shown on the Node Screen) is useless, without knowing what is running on the node...)

Solution: 
So I would suggest having a box that shows the current pods/workloads as a list. These pods/workloads should be hyperlinks, so you can get to the respective pod/workload detail-page if clicking them. Thanks. 

![image](https://user-images.githubusercontent.com/54768881/70380206-acba2f00-1937-11ea-9d29-72d7459b003f.png)

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/11024
