### ISSUE TITLE
import RKE cluster and be editable

### ISSUE THREAD

**Issue by robinbraemer** [rancher/rancher#24472]
It would be nice to be able to import an existing RKE cluster and be able to fully manage and edit the cluster using rancher as it would have been created by rancher.

This makes it more attractive to migrate to rancher if you already have an RKE cluster and now want to have all the additional features that rancher provides such as node pools and adding nodes by a single command on the host.

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/22763
