### ISSUE TITLE
vSphere: Deploy from content library template fails

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#24480]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a vSphere node template: Select Creation Method -> `Deploy From Template: Content Library` and choose an existing Linux VM template from the library
2. Create cluster using the node template

**Result:**
1. Cluster creation fails.
2. Node status initially shows `Waiting for machine to be running` then throws error `Timed out waiting for machine to be running` 

**Other details that may be helpful:**

Logs show the following error masked as `INFO`:

> [INFO] [node-controller-docker-machine] (jan-mstr1) Unable to perform any actions, change flags and try again

Debug logs:
[vsphere-deploy.log](https://github.com/rancher/rancher/files/3940522/vsphere-deploy.log)

Root cause:
https://github.com/rancher/machine/blob/master/drivers/vmwarevsphere/vsphere.go#L342

**Environment information**
Rancher 2.3.3
vSphere 6.7

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head

Reproduced this in our 6.7 vSphere environment.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head `565ef1a85`

* Create node template to deploy from Content Library
* `ubuntu-19.0.4-server-cloudimg` template
* Template is copied from content library and cluster is created successfully

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 17045525a

* Create node template to deploy from Content Library
* `ubuntu-19.0.4-server-cloudimg` template
* Template is copied from content library and cluster is created successfully
