### ISSUE TITLE
[ui] Custom Registry UI Bug

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#24489]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a Registry Credential in 2.3.3
2. Select Custom
3. Populate form fields
4. Save

**Result:**

UI bug showing the address as `*%FQDN%*`.

**Other details that may be helpful:**

It appears to *ONLY* be a UI bug. The credential appear to work appropriately in the cluster.

![Screen Shot 2019-12-09 at 2 11 21 PM](https://user-images.githubusercontent.com/48329/70473302-fb79dd00-1a8d-11ea-9ca5-69ef52162bcd.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Comment by ekristen** [comment]
@vincent99

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/24659
