### ISSUE TITLE
SSL enabled ports behind the load balancer

### ISSUE THREAD

**Issue by ammmze** [rancher/rancher#2448]
**Feature Request**
Can we add support for being able to talk to SSL ports behind the load balancer?

So it would be something like this:

`request --ssl--> balancer --ssl--> container`

I understand that it requires additional decryption and encryption in the balancer, but sometimes it is out of our hands to support SSL termination and do plain text internal. For example:

I am working on using a suite of products from [WSO2](http://wso2.com/), which require even when fronted by an SSL terminating load balancer, to have the traffic hitting the product be coming in through SSL. I have attempted to to route it to the HTTP port (9763), but it always tries to redirect back to the SSL port (which then puts us in a redirect loop). For some parts of it, it would probably be okay to just do SSL pass through, but other parts do require session stickiness, which cannot be done with SSL pass through.

**Comment by cusspvz** [comment]
Sorry for relating the issue above, misunderstood the problem.

**Comment by ammmze** [comment]
For reference...I opened this issue/request based on discussion on the forums [here](http://forums.rancher.com/t/ssl-enabled-ports-behind-the-load-balancer/730/4).

**Comment by c0deaddict** [comment]
+1

**Comment by enr1c091** [comment]
I am sorry, but is there a solution for this issue at the time being? We are facing the very same issue. I cannot find a way to redirect my requests to the HTTPS port of my WSO2 container without getting a 502 Bad Gateway.

All my other containers which have it's traffic redirected to a HTTP port works just fine.

I appreciate any help.

Best regards,
Enrico

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
