### ISSUE TITLE
UI - Update EKS regions to include ca-central-1 (Canada Central) and sa-east-1 (Sao Paulo)

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#24484]
UI for https://github.com/rancher/rancher/issues/24299 and https://github.com/rancher/rancher/issues/24400

**Comment by soumyalj** [comment]
Tested with Rancher v2.3.4-rc3 
Created EKS cluster using UI in regions Ca-central-1 and Sa-east-1 regions. 
UI displays these two regions for selection during EKS cluster creation as shown below:
<img width="1080" alt="Screen Shot 2019-12-13 at 2 58 39 PM" src="https://user-images.githubusercontent.com/18536626/70837572-1c596f80-1db9-11ea-92d9-8c291e30fc11.png">

EKS cluster creation in these two regions was successful. Cluster was active and functional.
