### ISSUE TITLE
Validate importing k3s cluster

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#24485]

**Comment by aaronRancher** [comment]
Validated with Rancher server `rancher\rancher:master-head` `version 09cbde680`
k3s version `v1.16.3-k3s.2`

![Screen Shot 2019-12-09 at 2 37 29 PM](https://user-images.githubusercontent.com/57409052/70475275-75f82c00-1a91-11ea-8284-d8963d38bb78.png)
