### ISSUE TITLE
Monitoring integration with existing prometheus-stack

### ISSUE THREAD

**Issue by rjshrjndrn** [rancher/rancher#24499]
**enhancement:**

Monitoring inbuilt in rancher is really, awesome. But what if we are maintining our own monitoring stack? In that case, can I integrate rancher UI with current `prometheus-operator`

**Comment by rjshrjndrn** [comment]
Hi, Any comments on this ?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/17370
