### ISSUE TITLE
Cannot remove node labels that are added by the agent during registration

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#24498]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Add a node to a Custom Cluster using the command provided by rancher, add any label with `--label`
2. Attempt to remove the label later on, it was always be added back instantly.

**Result:**

Unable to remove labels that were added by the agent upon registration.

**Other details that may be helpful:**

I think this is a bug? Documentation doesn't call out this behavior and I don't think this is wanted behavior. 

Being able to add labels upon registering a node into a custom cluster is awesome, but in my case I changed what default labels I wanted but now I can't remove the old, they just get immediately added back.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Comment by jeroenhartgers** [comment]
The problem is also the other way around:
One cannot add a label using the Rancher GUI: The label immediately disappears after you press "Save".

**Comment by ekristen** [comment]
@jeroenhartgers i haven’t found that to be the case? Could you elaborate? It might be best as a separate issue with all the detailed filled out. 

I add labels all the time to my nodes without issue.

**Comment by jeroenhartgers** [comment]
@ekristen It just assumed it was the same problem. I will elaborate. 

- I open my Rancher GUI
- I choose a cluster on cluster level
- I click on Nodes
- I click on Edit at one of the three nodes in my cluster
- I explode Labels & Annotations
- I click Add label
- I type foo = bar
- I click on Save

**Result**: NO label

I have eleven clusters, spread over three Rancher managers. They all act the same,

**Environment information**

- Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA
- Docker 18.6.2
- Kubernetes 1.16.3

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/15825
