### ISSUE TITLE
detach a cluster from a rke template

### ISSUE THREAD

**Issue by wtayyeb** [rancher/rancher#24505]
Hi. I create a RKE Template from one of my clusters, but dont intent to use it for that cluster. but it is stick to it and I cant figure how to detach it from that template. i want to edit cluster settings but everything is locked to template and UI stuck when changing the revision!!!

**Comment by wtayyeb** [comment]
In console there is a JS error, i could only replace the revision and then hit `F5` to refresh the page with new selected revision.
![image](https://user-images.githubusercontent.com/1420290/70520562-fdf23a80-1b52-11ea-842d-3d74f067367f.png)


BTW: I want to completely detach the cluster form the template, how to do it?

**Comment by NaPs** [comment]
I have the exact same problem. There is no confirmation when clicking the "Convert to RKE template" button. And like @wtayyeb, I'm stuck upgrading my cluster because of js errors...

Please help!
