### ISSUE TITLE
Unable to select child resource groups in vSphere node template dropdown by fullpath

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#24507]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Rancher v2.3.3 instance with cloud credentials for a vsphere cluster
2. Add a nested child resource group within vSphere under a top-level resource group
3. Attempt to add a vSphere node template in the Rancher v2.3.3 UI, and observe you cannot select the nested child resource group by full path, only the name of the resource group is shown. As a result you cannot differentiate multiple resource groups with the same name.

**Other details that may be helpful:**

In Rancher < v2.3.3 the resource group was a free text field, so a user could configure a nested resource group via the UI with the full path, this is no longer possible in v2.3.3. In v2.3.3, the workaround is to first create the Node Template via the UI, then edit via the API to add the nested child to the resource group path.

**Environment information**
- Rancher v2.3.3

gzrancher/rancher#8920

gzrancher/rancher#7460

**Comment by luthermonson** [comment]
@axeal some renewed interest in this lately, my test shows a sub resource pool shows up in the drop down just only lists the name and not that it's a sub, see the screen shot of the options in the select where i have luther and luther/testerrrr

https://gyazo.com/43b7e0a12195f99f4976f5e9cdb437ac

Check again if this is an issue or perhaps we can fix UI to show it's a sub or the parent resource pool

**Comment by axeal** [comment]
@luthermonson Agreed, looks like just a UI fix to indicate it is a sub-pool of the parent

**Comment by bmdepesa** [comment]
Reproduced in v2.4.5

As @luthermonson stated, the subpools are listed, but the UI does not show the full path. 

![Screen Shot 2020-07-13 at 2 35 45 PM](https://user-images.githubusercontent.com/21316915/87356070-48d39680-c516-11ea-83ff-51206cc42df8.png)
![Screen Shot 2020-07-13 at 2 35 51 PM](https://user-images.githubusercontent.com/21316915/87356073-496c2d00-c516-11ea-90bc-5eb9482b0e40.png)

**Comment by westlywright** [comment]
Available in `latest-2.4`. `latest-2.5` and `master` incoming.

**Comment by bmdepesa** [comment]
`rancher/rancher:v2.4-3974-head`

* Create a vsphere node template
* Subpools have the full path listed in the dropdown

![Screen Shot 2020-10-16 at 5 01 13 PM](https://user-images.githubusercontent.com/21316915/96347411-79b3f200-1056-11eb-8faa-f4aa4b969968.png)


Leaving open until tested on v2.5/master lines

**Comment by bmdepesa** [comment]
`master-head 68042fa`
`v2.5-head 9d38821`

* Create a vsphere node template
* Subpools have the full path listed in the dropdown
