### ISSUE TITLE
ResourceQuota sync controller deepEqual bug

### ISSUE THREAD

**Issue by Jason-ZW** [rancher/rancher#24502]
## Description
Using `reflect.DeepEqual` to compare `resource.Quantity` can lead to the compare results are not expected. This problem is particularly acute when setting CPU related quotas. [Code Line 1](https://github.com/rancher/rancher/blob/master/pkg/controllers/user/resourcequota/resource_quota_sync.go#L103-L109) [Code Line 2](
https://github.com/rancher/rancher/blob/master/pkg/controllers/user/resourcequota/resource_quota_sync.go#L145)

## Steps to reproduce
1. add `logrus` log to the code place
2. create project with cpu limit & cpu request quota
3. update project without change anything

## Debug Log:
```
requests.cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI}
requests.cpu:{i:{value:1000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI}
```

```
2019/12/10 16:50:31 [INFO] src quota hard: map[limits.cpu:{i:{value:1500 scale:-3} d:{Dec:<nil>} s:1500m Format:DecimalSI} requests.cpu:{i:{value:1 scale:0} d:{Dec:<nil>} s:1 Format:DecimalSI} secrets:{i:{value:50 scale:0} d:{Dec:<nil>} s:50 Format:DecimalSI}]
2019/12/10 16:50:31 [INFO] dst quota hard: map[limits.cpu:{i:{value:1500 scale:-3} d:{Dec:<nil>} s:1500m Format:DecimalSI} requests.cpu:{i:{value:1000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} secrets:{i:{value:50 scale:0} d:{Dec:<nil>} s:50 Format:DecimalSI}]
```

**Comment by gitlawr** [comment]
Do you have steps to expose this bug from an end user's view? It can also help QA to validate the issue.

**Comment by Jason-ZW** [comment]
## How to test
1. create a project with `limitCPU=1000` and `requestCPU=1000` milli  
2. watch the rancher logs (level: info)
3. update project without change anything

This log is incorrect if it appears: 
```
Updating default resource quota for namespace xxx
```

**Comment by soumyalj** [comment]
Reproduced the issue with Rancher v2.3.3.
1. Created a Rancher server with CATTLE_DEV_MODE=true as below:
```
docker run -itd --privileged -p 80:80 -p 443:443 -e CATTLE_DEV_MODE=true --name rancher-server rancher/rancher:v2.3.3
```
2. Create a DO cluster
3. Create a project "testproj1"  with Project  Resource Quota and a namespace "newns1"
<img width="1254" alt="Screen Shot 2020-02-05 at 9 17 08 PM" src="https://user-images.githubusercontent.com/18536626/73907929-ea1a3a80-485c-11ea-9aa7-c261062ea705.png">

4. Edit the project and click on Save without changing any values.    

5. Observe the rancher server logs:
Logs with " Updating default resource quota for namespace newns1" are observed as below
```
2020/02/06 05:12:48 [INFO] Updating role project-member in p-ksbsv because of rules difference with roleTemplate Project Member (project-member).
2020/02/06 05:13:01 [INFO] Creating default resource quota for namespace newns1
2020/02/06 05:13:01 [INFO] Creating roleBinding User u-skezpftamu Role project-member
2020/02/06 05:13:01 [INFO] Creating roleBinding User u-skezpftamu Role edit
2020/02/06 05:13:01 [INFO] Creating roleBinding User user-t9ksm Role project-owner
2020/02/06 05:13:01 [INFO] Creating roleBinding User user-t9ksm Role admin
2020/02/06 05:13:02 [INFO] Updating default resource quota for namespace newns1
2020/02/06 05:13:02 [INFO] Updating default resource quota for namespace newns1
2020/02/06 05:13:03 [INFO] Updating default resource quota for namespace newns1
2020/02/06 05:13:36 [INFO] Updating default resource quota for namespace newns1
2020/02/06 05:13:47 [INFO] Updating default resource quota for namespace newns1


```
