### ISSUE TITLE
Updating the vSphere node template via API errors with "vappProperty=NotNullable 422: "

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#24510]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
With a vSphere cluster with node templates configured in Rancher v2.3.3:
1. We started with a tested working template in which we had  already replaced all occurrences of `null` with `""` before saving and testing (successfully) 
1. View a Node Template in API 
2. Select `Edit`
3. Select `Show Request` without making any changes
4. Select `Send Request`

**Result:**
![image](https://user-images.githubusercontent.com/8906089/70577810-e42d1380-1ba3-11ea-9330-83f347beb904.png)

**Other details that may be helpful:**
Work-around is to replace `null` with `""`

**Environment information**
- Rancher version 2.3.3

**Cluster information**
- Cluster type: vSphere VMs

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/25646

**Comment by bmdepesa** [comment]
rancher/rancher:master-head d8e28c62d

* Reproduce in v2.3.5
* Created vSphere node template
* Edit node template in API w/out making changes
* Node template is updated without any errors.
