### ISSUE TITLE
RFE: Announcement Banner Capability

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#24514]
It can be useful to have an announcement banner functionality that could be used to make announcements about the cluster by operations teams.

**Comment by mattmattox** [comment]
Could we just add a custom label like cattle.io/banner: "Text Goes Here" to the cluster object. At which point then the API already lists all labels under /v3/clusters/<cluster_name>. So the UI would just need to looks if that label is set and/or not NULL. Then just display a simple text box on the cluster dashboard page

**Comment by bgulla** [comment]
Adding https://github.com/rancher/rancher/issues/25694 with more info.

**Comment by Oats87** [comment]
Closing, as this was resolved in #25694
