### ISSUE TITLE
Security: is it safe to use Rancher?

### ISSUE THREAD

**Issue by adampl** [rancher/rancher#24511]
Is it safe to use Rancher?
Does the Rancher software undergo any third-party security audits?

I mean something like Kubernetes does:
https://github.com/kubernetes/community/tree/master/wg-security-audit

**Comment by superseb** [comment]
Please see https://rancher.com/docs/rancher/v2.x/en/security/ and let us know if you have any concern. Please remember to file any potential security issue through `security@rancher.com` and not publicly.
