### ISSUE TITLE
Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s)

### ISSUE THREAD

**Issue by rshiva777** [rancher/rancher#24526]
I am trying to deploy rancher cluster in AWS Enviroment. I have created the pre-requisites for AWS Cluster

Env: Rancher v2.2.0 (AWS Cluster Creation)
Issue: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s)
Logs: I am facing the below error logs:

2019/12/11 13:48:38 [INFO] stdout: Checking connection to Docker...
2019/12/11 13:48:38 [INFO] Checking connection to Docker...
2019/12/11 13:48:39 [INFO] stdout: Docker is up and running!
2019/12/11 13:48:39 [INFO] Docker is up and running!
2019/12/11 13:48:52 [INFO] Provisioning node awstest21 done
2019/12/11 13:48:52 [INFO] Generating and uploading node config awstest21
2019/12/11 13:48:52 [INFO] Provisioning cluster [c-bbqrd]
2019/12/11 13:48:52 [INFO] Creating cluster [c-bbqrd]
2019/12/11 13:48:57 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10580
2019/12/11 13:48:57 [INFO] cluster [c-bbqrd] provisioning: Initiating Kubernetes cluster
2019/12/11 13:48:57 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating CA kubernetes certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kubernetes API server certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Service account token key
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kube Controller certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kube Scheduler certificates
2019/12/11 13:48:58 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kube Proxy certificates
2019/12/11 13:48:59 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Node certificate
2019/12/11 13:48:59 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating admin certificates and kubeconfig
2019/12/11 13:48:59 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating Kubernetes API server proxy client certificates
2019/12/11 13:48:59 [INFO] cluster [c-bbqrd] provisioning: [certificates] Generating etcd-172.31.30.0 certificate and key
2019/12/11 13:49:00 [INFO] cluster [c-bbqrd] provisioning: Successfully Deployed state file at [management-state/rke/rke-395003924/cluster.rkestate]
2019/12/11 13:49:00 [INFO] cluster [c-bbqrd] provisioning: Building Kubernetes cluster
2019/12/11 13:49:00 [INFO] cluster [c-bbqrd] provisioning: [dialer] Setup tunnel for host [13.234.110.198]
2019/12/11 13:49:00 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/12/11 13:49:00 [ERROR] cluster [c-bbqrd] provisioning: Failed to set up SSH tunneling for host [13.234.110.118]: Can't establish dialer connection: can not build dialer to c-bbqrd:m-7kbsp
2019/12/11 13:49:00 [ERROR] cluster [c-bbqrd] provisioning: Removing host [13.234.110.198] from node lists
2019/12/11 13:49:00 [ERROR] cluster [c-bbqrd] provisioning: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [13.234.110.198]
2019/12/11 13:49:00 [ERROR] ClusterController c-bbqrd [cluster-provisioner-controller] failed with : Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [13.234.110.118]

Can anyone please help how to solve the issue

**Comment by superseb** [comment]
Log in to `13.234.110.198` following the steps described in  https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-access-nodes-created-by-rancher and check the logs of the created `rancher/rancher-agent` container (`docker ps -a`, `docker logs`), this should reveal why it cannot connect back to the configured `server-url` in Rancher.

**Comment by superseb** [comment]
Let me know if this needs a follow up.
