### ISSUE TITLE
Alertmanager does not honor node selector

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#24524]
**What kind of request is this (question/bug/enhancement/feature request):** bug
[Bug]

**Steps to reproduce (least amount of steps as possible):**

1. Enable Cluster Monitoring with a selector unique to one node. 
2. Configure and assign a Notifier to alerts so that alertmanager is deployed.
3. Delete the node with this node selector

**Result:**

All monitoring workloads except for alertmanager and prometheus-cluster-monitoring will become unavailable.  
![image](https://user-images.githubusercontent.com/8906089/70615669-bd52f980-1c04-11ea-95e0-268b9e1aaeb0.png)
![image](https://user-images.githubusercontent.com/8906089/70614949-64cf2c80-1c03-11ea-9d89-e8d27d045595.png)

When I look at each individually, I see that most workloads are correctly saying nothing matches the node selector.  prometheus-cluster-monitoring actually shows as unavailable (I believe this is Bug rancher/rancher#24128 and have updated accordingly) and alertmanager redeploys to another worker.
![image](https://user-images.githubusercontent.com/8906089/70615620-a7ddcf80-1c04-11ea-85bb-cb6dc7af385c.png)

Since alertmanager is a part of monitoring/Prometheus it should honor the NodeSelector assigned when enabling Monitoring.  I've tried editing the workload for alertmanager directly and setting a label requirement but it removes the node selector when the workload redeploys.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
Tested on: 
v2.3.2: Monitoring v0.0.5
v2.3.3: Monitoring v0.0.5 and v0.0.6

**Comment by cloudnautique** [comment]
The AlertManager is operating as designed within Rancher. AlertManager is deployed independent of the monitoring functionality built into the product. Rancher has written integrations that leverage the AlertManager for sending alerts outside of the Prometheus monitoring capability.

**Comment by Tejeev** [comment]
Do we have a recommended method for allocating the alertmanager?  
Editing the workload directly does not work: https://github.com/rancher/rancher/issues/24525

**Comment by splattner** [comment]
So, should we directly edit the cluster-alerting app in the System Project and set `alertmanager.nodeSelectors[0]=...` ? This seems to work for me, but how long? are you going to overwrite this on updates?
Or what is the preferred way?
