### ISSUE TITLE
rancher Stuck on "Waiting to register with Kubernetes

### ISSUE THREAD

**Issue by kundeng** [rancher/rancher#24521]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
adding a 2nd node (a first worker node) 

**Result:**
Waiting to register with Kubernetes

**Other details that may be helpful:**
command run is 

sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.3.2 --server https://172.22.101.101 --token 7cswv6bx5x2g88ht259zfzm4vxvw5ndfdf54thbkl5qhbmrdp5jc4b --ca-checksum ebf12f4751d177781ca39129bf09f012715bb8e1f51eb0bae7138ec2e299dd6f --worker

docker ps log shows:
....
3.005MB/3.772MB\",\"id\":\"11153ed737ac\"}"
time="2019-12-10T23:11:35Z" level=info msg="{\"status\":\"Verifying Checksum\",\"progressDetail\":{},\"id\":\"11153ed737ac\"}"
time="2019-12-10T23:11:35Z" level=info msg="{\"status\":\"Download complete\",\"progressDetail\":{},\"id\":\"11153ed737ac\"}"

no more logs after that. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Running locally using vagrant 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
Is Docker still responsive on that host? (`docker ps -a`) What are the specs of that machine, what are the load/memory/disk metrics on that time? Does it reproduce every time when creating the setup from scratch?

**Comment by kundeng** [comment]
Only the agent container is runing,  it preproduces every time I tried. 
This is by using the rancher quickstart vagrant recipe.  Whatever it is defined in there, that's the specs of the docker machine. 
Please try it yourself. 

The following is not entirely related to this bug but can be generally useful for whoever is trying to setup rancher k8s locally with multiple-nodes. 

I then tried to create my own vagrant machines based of Ubuntu instead of rancheros and I'm able to get around the above issue. However, I encountered other issues which really suggests the following: 
setting up a rancher k8s with vagrant/virtualbox is tricky.  

 It has a lot of to do with eth0 being the default nat interface of every node in virtualbox.  And virtualbox assigns (stupidly) the same ip  to all the nodes on this interface.   You can agent to use eth1 and you can  force flannel to use eth1 for networking, but it doesn't seem to work as expected.  There are workarounds  on adding clusterip to routing table etc.   What I ultimately experienced is  still intermittent hang with multiple-nodes, when say,   pinging clusterip/port of a service.  The overall experience is very poor.

**Comment by superseb** [comment]
Quickstart has been revamped using a different install method.
