### ISSUE TITLE
A StatefulSet with 10+ replicas cannot be properly sorted ascending/descending in the UI

### ISSUE THREAD

**Issue by itslukej** [rancher/rancher#24528]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Go to a workload page for a statefulset (with 10+ replicas)
2) Open "Pods in this workload"
3) Press the arrows next to Name to attempt to sort Ascending or Descending

**Result:**
![image](https://user-images.githubusercontent.com/8759737/70641239-39653580-1c35-11ea-8d66-35b7ff5b1ca9.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.7
- Installation option (single install/HA): Single

**Comment by sowmyav27** [comment]
**verified on 2.3.4-rc6**

**Steps:**

- deploy a cluster(rke DO 1.17 k8s)
- Go to a workload page for a statefulset (with 10+ replicas)
- Click on the workload, go to Pods view.
- User is able to sort the pods in the Name column in ascending/descending order
