### ISSUE TITLE
CIS Scans fail on passing junk/invalid values in the config map from the UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24539]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Go to Cluster --> System Project --> Config --> Config map --> Edit
2. Currently we are allowed to input invalid values. Enter invalid values and click on save.
3. Run Scans again on the cluster.
4. Scan fails to generate report

**Actual Result:**
Scan fails to generate report

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - latest
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.16.3
```

**Comment by leodotcloud** [comment]
Passing malformed or invalid skip information used to cause an exception resulting in a scan failure. With the fix, the invalid information is ignored and the scan proceeds.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `61b78ddf7`**

- Go to Cluster --> System Project --> Config --> Config map --> Edit
- Currently we are allowed to input invalid values. Enter invalid values and click on save.
- Run Scans again on the cluster.
- Scan is run on the cluster successfully and the invalid value is ignored.
- Go to Cluster --> System Project --> Config --> Config map --> Edit
- Enter valid skip avlues.
- Run Scans again on the cluster.
- Scan is run on the cluster successfully and the expected test is skipped.
