### ISSUE TITLE
When rancher-compose is used to upgrade services that was created from UI , upgrade will be triggered even when no changes have been made.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2453]
Server version - v0.43.0-rc3
Rancher compose version - v0.5.0-rc2

Steps to reproduce the problem:
Create a service from UI.
Note that "io.rancher.service.hash" is not created for the service.

Try to use rancher-compose to upgrade the service without making any changes to the service configuration.

Upgrade will be triggered.

Expected Behavior is for upgrade to be not triggered in this case , since there has been no changes made to any configuration of the service.

**Comment by deniseschannon** [comment]
Closing as there are users who want upgrades to be able to be triggered with no compose files. 

https://github.com/rancher/rancher/issues/3571
