### ISSUE TITLE
Canal pods crash after Kubernetes v1.13.5 to v1.15.6 upgrade on nodes with workload exposed with nodeport service

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#24543]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Set up NIS server and run ypbind on the hosts in your Kubernetes cluster. Make sure NIS will accept requests for protocols, but does not return a mapping for `tcp`.
2. Install a v1.13.5 cluster.
3. Create a workload and a service that maps to that workload that uses a NodePort
4. Upgrade cluster to v1.15.6

**Result:**
Calico node pods are crashing on the nodes that have the workloads that use NodePort services. Will errors in the pod logs such as:
```
processErr=exit status 1 stderr="ipset v6.30: Error in line 102: Syntax error: cannot parse 'tcp' as a protocol\n" stdout="" writeErr=<nil>
2019-12-03 17:11:27.210 [WARNING][21964] ipsets.go 330: Failed to update IP sets. Marking dataplane for resync. error=exit status 1 family="inet"
2019-12-03 17:11:27.736 [PANIC][21964] ipsets.go 342: Failed to update IP sets after multiple retries. family="inet"
panic: (*logrus.Entry) (0x19653e0,0xc0003b0af0)
goroutine 108 [running]:
github.com/projectcalico/node/vendor/github.com/sirupsen/logrus.Entry.log(0xc0000d40a0, 0xc00060ea80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/projectcalico/node/vendor/github.com/sirupsen/logrus/entry.go:128 +0x5a8
github.com/projectcalico/node/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc000189d10, 0xc0006f5f20, 0x1, 0x1)
/go/src/github.com/projectcalico/node/vendor/github.com/sirupsen/logrus/entry.go:173 +0xb2
github.com/projectcalico/node/vendor/github.com/projectcalico/felix/ipsets.(*IPSets).ApplyUpdates(0xc00069e1e0)
/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/ipsets/ipsets.go:342 +0x255
github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply.func1(0xc0008aa754, 0xc00069e1e0)
/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux/int_dataplane.go:1080 +0x2b
created by github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply
/go/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux/int_dataplane.go:1079 +0x29b
```

**Other details that may be helpful:**
This issue was introduced in the move from image rancher/calico-node:v3.4.0 to rancher/calico-node:v3.7.4. In v3.4.0, alpine was used as the base image and had no `/lib/x86_64-linux-gnu/libnss_nis*` libraries. In v3.7.4, base image is debian, which has these libraries present. Calico uses ipset, which in turn needs to resolve protocol names, such as `tcp` to a protocol number. Since /etc/nsswitch.conf in the calico-node container does not specify how to resolve protocols, it is defaulting to NIS instead of using /etc/protocols.

Possible ways to fix or workaround this issue is to map /etc/nsswitch.conf from the host or use a configmap that has `protocols: files`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.3
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
NA
- Kubernetes version (use `kubectl version`):
v1.13.5 to v1.15.6 upgrade

- Docker version (use `docker version`):
NA

**Comment by leodotcloud** [comment]
>We generally release patch releases only as needed, depending on the severity of bugs found and patched. This change will go into v3.13.0, which we're targeting in mid-to-late Feb.

We will be able to update our templates once we get a release from the upstream.

**Comment by deniseschannon** [comment]
It looks as if calico v3.13.0 was released 3 days ago. We need to update these the latest k8s 1.15, 1.16 and 1.17 templates

**Comment by jiaqiluo** [comment]
Rancher:master-head c34bdc2bb

The new image `rancher/calico-cni:v3.13.0`  and `rancher/calico-node:v3.13.0` are used for clusters with `calico` as the Network Provider, but not for the clusters with `canal` as the Network Provider.

**Comment by superseb** [comment]
Available in`master-head` (2426/d47b0ec4c)

**Comment by superseb** [comment]
Available in `master-head` (2427/`5e47dabd`)

**Comment by rancher-max** [comment]
#### Validated on master-2427-head `Rancher version 5e47dabd3`

- Calico K8s version 1.17:
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/55997940/76575527-a8446b80-647c-11ea-857c-ad678c39c887.png">

- Calico k8s 1.16
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/55997940/76575559-c0b48600-647c-11ea-90cf-1e9d68527f7a.png">

- Calico k8s 1.15
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/55997940/76576017-1ccbda00-647e-11ea-83b7-1d41d3500823.png">

- Canal k8s 1.17
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/55997940/76577752-8dc1c080-6483-11ea-8f74-7d2a3a1b6f5b.png">

- Canal k8s 1.16
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/55997940/76578298-6ec42e00-6485-11ea-8cf8-0aa72d8a7ad3.png">

- Canal k8s 1.15
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/55997940/76578451-e5f9c200-6485-11ea-905f-4b944cf4f135.png">

- KDM Jenkins job full passed as well

Still need to verify upgrade scenarios. Will do that tomorrow.

**Comment by rancher-max** [comment]
#### Tested Upgrade from v2.3.6-rc5 to master-head
6 Clusters with the same configurations as above. All below steps run on all clusters.

- Ran pre-upgrade jobs before upgrading rancher server version
- Upgraded rancher server version
- Upgraded each cluster k8s version to use rancher-2 instead of the rancher-1 version it was on previously
    - canal with k8s version 1.15 FAILED to upgrade rancher server version with error: `Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system`. Reopening due to this. However, even though the upgrade failed, the images from this issue were upgraded correctly in this cluster.
- Validated calico images were correct for all clusters (using v3.13.0)
- Ran post-upgrade jobs on clusters that succeeded. All passed.


**Additional Info Regarding Reopening:**
- Also fails when upgrading from v1.15 to v1.17
- Succeeds in a v2.3.5 setup without doing a Rancher server upgrade when upgrading k8s version on a cluster from v1.15 to v1.17
- Also succeeds in a setup when upgrading from v2.3.4 k8s v1.15 to v2.3.5 k8s v1.17

**Comment by rancher-max** [comment]
#### Validated in an upgrade from v2.3.5 to master-2450-head and v2.3.6-rc5 to master-2450-head

All scenarios commented above are successful now. Issue previously mentioned has been resolved. All images are correct after upgrading, upgrading was successful for all clusters (3 node all roles) and pre and post upgrade jobs succeed.
