### ISSUE TITLE
When changes are made to only sidekick services and upgrade is attempted,  all the services (primary and sidekick) get upgraded.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2454]
Server version - v0.43.0-rc3
Rancher compose version - v0.5.0-rc2

Steps to reproduce the problem:
Create a service - test1 from UI with 2 side kicks say "sk1" and "sk2".

Use the config generated from this service  and change the image name from "sk1" service alone.

Used the following upgrade command to upgrade only "sk1":
rancher-compose  -p Default -f dc-sk.yml up --upgrade test1

We see that all the services - test1 , sk1 and sk2 being upgraded.

**Comment by radius314** [comment]
Is there a workaround for this?  I'm having the same issue.  I want to be able to just be able to update a specific sidekick service and not everything in the Stack.

**Comment by deniseschannon** [comment]
@radius314 There is no current workaround. The original intent of sidekicks was to solve the use case where you would need `volumes_from` a specific container and therefore the containers would need to be scheduled together. If you update a sidekick, then you would also need to update the primary container as your volumes would have changed.

If you are using sidekicks to schedule containers together, then I'd recommend using scheduling rules for that. http://docs.rancher.com/rancher/v1.2/en/cattle/scheduling/

**Comment by will-chan** [comment]
This is not something we plan to address.
