### ISSUE TITLE
CIS Scan - Failed nodes not reported in the API when the status of test is "mixed"

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24540]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On a custom cluster - all roles - 1 node, run CIS Scans.
- For a test which has the state as "mixed", API report does not list the nodes it has failed on

**Expected Result:**
The report in API should report the nodes which have failed when the state of the test is "mixed"

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master - head
- Installation option (single install/HA): single 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.16.3
```

**Comment by leodotcloud** [comment]
Fixed the logic in the code to handle this use case.

**Comment by sowmyav27** [comment]
Verified on master-head - commit id: `61b78ddf7`

**On a cluster - 8 nodes, 3 etcd, 3 worker and 2 control planes.**

- Run CIS Scan.
- Expected one test - test1 to fail. 
- The state of test1: Mixed (expected)
- Failed nodes are listed.

**On a cluster - 1 node all roles.**

- Run CIS Scan.
- Expected one test - test1 to fail. 
- The state of test1: Fail (expected)
- All the nodes in this case fail (as it is all-roles scenario), so we do not expect the list of failed nodes.

Closing the issue.
