### ISSUE TITLE
When clicking on "Add sidekick" , the newly added stack does not launch automatically.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2455]
Server version - V0.43.0-rc4

When clicking on "Add sidekick" , the newly added stack does not launch automatically.

<img width="1168" alt="screen shot 2015-10-26 at 6 03 09 pm" src="https://cloud.githubusercontent.com/assets/4266958/10746840/e6f55f6e-7c0b-11e5-80e6-8df3f1a42d4e.png">

**Comment by sangeethah** [comment]
Tested with build from master - Oct 30

When we click on  "Add sidekick" , the newly added stack launches automatically now.

Can the default cursor be placed in the "Name" field of newly launched stack ?

**Comment by vincent99** [comment]
ok..

**Comment by sangeethah** [comment]
Tested with latest build from master - Oct 30.
When we click on "Add sidekick" , the newly added stack launches automatically now and the  cursor gets placed in the "Name" field of newly launched stack.
