### ISSUE TITLE
v2.3.3 can not set port mapping for workload

### ISSUE THREAD

**Issue by sunnycamel** [rancher/rancher#24551]
**What kind of request is this (question/bug/enhancement/feature request):**
I upgrade my rancher from v2.2.3 to v2.3.3, port mapping for workload lost. 
I try to re-set the port mapping, for example  map container port 8080 to cluser Ip 80, but rancher does not save it in the yaml file. So I can not set port mapping.

**Steps to reproduce (least amount of steps as possible):**
choose a workload set up the port mapping
fill in the mapping name,  container port 8080 , cluster ip , on listening port fill in with 80
save the configuration 
**Result:**
hope can access the workload at port 80, but it is run at port 8080, port mapping does not set succesfully

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher v2.3.3
- Installation option (single install/HA): single install

**Comment by NullIsNot0** [comment]
Today I also noticed this issue which definitaly needs to be fixed. As a workaround you can set port by editing YAML. Click on `View/Edit YAML`

Find 
```
spec:
...
	template:
		metadata:
			annotations:
				field.cattle.io/ports: '[[{"containerPort":8443,"dnsName":"SOMETHING","kind":"NodePort","name":"8080tcp318081","protocol":"TCP""}]]'
```

Change to
```'[[{"containerPort":8443,"dnsName":"SOMETHING","kind":"NodePort","name":"8080tcp318081","protocol":"TCP",sourcePort":31808"}]]'```

Notice `sourcePort":31808` at the end of line.

If you later chang Deployment through Web GUI, then you will loose Port Mapping setting. That's why I downgraded to 2.3.2 where editing Deployment works as expected.

![rancher_bug](https://user-images.githubusercontent.com/12268397/70709131-d6cb7280-1ce4-11ea-8457-72af9541d9ea.png)

**Comment by sangeethah** [comment]
This issue is similar to issue tracked in - https://github.com/rancher/rancher/issues/24358

**Comment by sowmyav27** [comment]
### Was able to reproduce the issue

**Steps:**

- Deploy a cluster on rancher:v2.2.3
- Deploy nodeport, clusterip and hostport.
- Upgraded rancher server to 2.3.3
- The nodeport had the same source port as in 2.2.3
- Edit the workload.
- update Source port to some other port. And save the changes made.
- After the workload gets to Active state, the source port mapping is lost (View in API of the workload)

```
"ports": [
{
"containerPort": 80,
"dnsName": "wk01-nodeport",
"kind": "NodePort",
"name": "80tcp312351",
"protocol": "TCP",
"sourcePort": 0,
"type": "/v3/project/schemas/containerPort"
}
```
- `publicEndpoints` still is tagged to the previous source port.
- Same is the behavior with a clusterip workload.
- Upgraded rancher server to 2.3-head latest
- Edit the workload.
- update Source port to some other port. And save the changes made.
- After the workload gets to Active state, the source port mapping is set to the one mentioned while editing the workload.
- Node port, hostport, and clusterip work as expected.

- Also verified on an upgrade from 2.3.3 to master-head, edit on workload, change the source port of nodeport/hostport/clusterip, the source port get saved on the workload.
- Node port, hostport, and clusterip work as expected.


### Verified on 2.3-head - commit id: `78ed261c6` and master-head - commit id: `564507959`

**Steps:**
1. Deploy an rke cluster.
2. Deploy nodeport/clusterip/hostport workload and specify the source port.
3. After the workload is deployed, verified the source port is the same as the port while deploying the workload.
4. `publicEndpoints` have the port configured, same as the sourceport. in case of nodeport and host port.
5. Node port, hostport, and clusterip work as expected.

Closing the issue.

**Comment by eltonk** [comment]
Same behavior on Rancher v2.5.5

**Comment by eramosr16** [comment]
I found this very same issue on Rancher v2.5.5, there is a bug parsing the form and saving as a yml, ports info updated after adding the workload aren't being saved
