### ISSUE TITLE
Ability to override the benchmark version used for a scan

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#24563]
Currently, the version of benchmark for a scan is determined by the backend. Need an override option in the API for a particular scan to use a different version.

**Comment by sowmyav27** [comment]
**Verified on master head - commit id: `656781c34`**


- On entering overrideBenchmarkVersion : "cis-1.4" in the `runSecurityScan` API, the `cis-1.4` scan tool version is run. 
- Additional failures are seen
- Download report.
- The report shows the scan tool version run is `Version: cis-1.4`

**Comment by sowmyav27** [comment]
PR: https://github.com/rancher/rancher/pull/24698
