### ISSUE TITLE
Unable to delete containers

### ISSUE THREAD

**Issue by summerQLin** [rancher/rancher#2456]
There is a container that I can't delete, rancher will always start new one, even the whole stack is removed.

My rancher version is old:
Rancher v0.37.1
Cattle v0.91.1
User Interface v0.47.0
Rancher Compose beta/latest

I don't want to go update, so what else can I do to just remove the container. I think somewhere rancher kept the metadata about that service, and how can I delete the meta info.

Thanks

**Comment by deniseschannon** [comment]
If you navigate to the API of the container, you should be able to find the associated service. Go to the API for that service and update the state to make it "Removed". It is most likely in "Active" state, which is why it keeps re-spawning.

**Comment by summerQLin** [comment]
@deniseschannon I couldn't find the API to update the service state, could you please point it out? Thanks for your help.

**Comment by summerQLin** [comment]
The url '…/v1/projects/1a32/services/1s454/?action=remove', I suppose it should be called to remove service 1s454, but clicking that link in browser doesn't remove the service at all.

**Comment by alena1108** [comment]
@summerQLin what is the state of the service you are trying to remove (1s454)? 

This issue is very similar to https://github.com/rancher/rancher/issues/2334

**Comment by deniseschannon** [comment]
@summerQLin If you are still having this issue, please re-open.
