### ISSUE TITLE
Specify Benchmark version in the report

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#24562]
Currently, the API doesn't return the version of benchmark in the report.

Need to provide this so that UI can display it and also use it to generate the skip configmap.

**Comment by sowmyav27** [comment]
@leodotcloud We see `"version":"rke-cis-1.4"` in the report generated. Is there any other fix required for this issue?

**Comment by sowmyav27** [comment]
Closing this issue as `version":"rke-cis-1.4` is seen in the scan reports generated in the API.
