### ISSUE TITLE
where is  the data of rancher cluster being saved

### ISSUE THREAD

**Issue by bingo3d2y** [rancher/rancher#24576]
I have deployed a rancher cluster with helm. But i can not find any pods’ data.
how will all the data sync between the rancher pods？

**deployment**
helm install rancher rancher-stable/rancher   --namespace cattle-system   --set hostname=rancher.my.org
NAME: rancher
LAST DEPLOYED: Fri Dec 13 07:53:06 2019
NAMESPACE: cattle-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Rancher Server has been installed.

NOTE: Rancher may take several minutes to fully initialize. Please standby while Certificates are being issued and Ingress comes up.

**Cluster information**
$ helm list -n cattle-system
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
rancher cattle-system   1               2019-12-13 07:53:06.618938401 +0000 UTC deployed        rancher-2.3.3   v2.3.3

$ k get pod -n cattle-system
NAME                                    READY   STATUS    RESTARTS   AGE
cattle-cluster-agent-5cb6cbff64-mjmzm   1/1     Running   0          32m
cattle-node-agent-qd854                 1/1     Running   0          32m
cattle-node-agent-s84qs                 1/1     Running   0          32m
cattle-node-agent-zp49f                 1/1     Running   0          32m
rancher-6599f7b45b-ddxdn                1/1     Running   0          34m
rancher-6599f7b45b-hbcjt                1/1     Running   0          35m
rancher-6599f7b45b-mxqm7                1/1     Running   0          34m

**Comment by JerryCurl** [comment]
etcd database, which runs in containers

**Comment by superseb** [comment]
This is described on https://rancher.com/docs/rancher/v2.x/en/installation/how-ha-works/
