### ISSUE TITLE
Unable to Import Existing cluster into Rancher 443 connection time out error

### ISSUE THREAD

**Issue by dbghub** [rancher/rancher#24571]
**What kind of request is this (question/bug/enhancement/feature request):**
Question
**Steps to reproduce (least amount of steps as possible):**
Have an existing two node cluster running on openstack vm.
**Here are the steps to make the cluster.**
`` sudo vi /etc/hosts
    3  free -g
    4  sudo vi /etc/fstab
    5  sudo vi /etc/yum.repos.d/kubernetes.repo
    6  sudo yum listrepo
    7  sudo yum repolist
    8  sudo yum install docker
    9  sudo docker version
   10  sudo yum install kubeadm
   11  sudo vi /etc/yum.repos.d/kubernetes.repo
   12  systemctl start docker && systemctl enable docker
   13  sudo systemctl start docker && systemctl enable docker
   14  sudo systemctl start docker && sudo systemctl enable docker
   15  sudo systemctl enable docker
   16  sudo systemctl start docker
   17  sudo systemctl start docker.service
   18  sudo systemctl status docker.service
   19  sudo yum remove docker docker-common docker-selinux docker-engine
   20  sudo yum install docker-ce
   21  sudo yum install -y yum-utils
   22  sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
   23  sudo yum makecache fast
   24  sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.33-1.git86f33cd.el7.noarch.rpm
   25  sudo yum install -y docker-ce
   26  sudo docker version
   27  sudo systemctl enable docker.service
   28  sudo systemctl start docker.service
   29  sudo systemctl status docker.service
   30  sudo docker ps -a
   31  sudo systemctl enable kubelet
   32  sudo systemctl start kubelet
   33  sudo systemctl status kubelet
   34  sudo systemctl status firewalld
   35  sudo yum install firewalld
   36  sudo systemctl enable firewalld
   37  sudo systemcl start firewalld
   38  sudo systemctl start firewalld
   39  sudo systemctl status firewalld
   40  sudo systemctl stop firewalld
   41  sudo systemctl status firewalld
   42  sudo kubeadm init --apiserver-advertise-address 172.24.172.63 --pod-network-cidr=172.16.0.0/16
   43  sudo mkdir -p $HOME/.kube
   44  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
   45  sudo chown $(id -u):$(id -g)$HOME/.kube/config
   46  sudo chown $(id -u):$(id -g) $HOME/.kube/config
   47  kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

**Result:**
``NAME                     STATUS   ROLES    AGE    VERSION
db-master-k1.novalocal   Ready    master   6d1h   v1.16.3
db-worker-k1.novalocal   Ready    <none>   6d1h   v1.16.3

**Rancher installation on Openstack Details Below**

CentOS-7x64-1708
Flavor Name
m1.medium
Flavor ID
3
RAM
4GB
VCPUs
2 VCPU
Disk
40GB

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

Rancher | v2.3.3
-- | --
User Interface | v2.3.25
Helm | v2.14.3-rancher1
Machine | v0.15.0-rancher20-1

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
```
Flavor Name
m1.medium
Flavor ID
3
RAM
4GB
```
VCPUs
2 VCPU
Disk
40GB
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```
(paste the output here)
```

- Docker version (use `docker version`):
Client: Docker Engine - Community
 Version:           19.03.5

```
(paste the output here)
When I add the cluster with rancher UI. It is in pending state forever. 
`kubectl -n cattle-system logs -l app=cattle-cluster-agent
`
**Result**
INFO: Environment: CATTLE_ADDRESS=172.16.1.2 CATTLE_CA_CHECKSUM=ab87d61737c998aaf5be40a3f1e574c110c6184063e1edf5bdd95add5aecfb6e CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-6d6f9bdb6d-wkl5f CATTLE_SERVER=https://172.24.172.55
INFO: Using resolv.conf: nameserver 10.96.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local openstacklocal novalocal options ndots:5
ERROR: https://172.24.172.55/ping is not accessible (Failed to connect to 172.24.172.55 port 443: Connection timed out)

**Problem**
 curl --insecure https://172.24.172.55/ping from the vm where master of kubernetes cluster is running is returning pong. 
Not sure how to fix this is issue. 

Running this command on master node ` kubectl -n cattle-system get pods`

Returns this 
`NAME                                    READY   STATUS    RESTARTS   AGE
cattle-cluster-agent-6d6f9bdb6d-wkl5f   1/1     Running   603        3d
cattle-node-agent-5dcr9                 1/1     Running   0          3d
cattle-node-agent-62ld9                 1/1     Running   0          3d
`

**Comment by superseb** [comment]
What does kube-flannel log? Do the nodes have iptables rules programmed? If you run a pod on your own, does it have connectivity?

**Comment by superseb** [comment]
Please let us know when you can provide the requested information.
