### ISSUE TITLE
Istio 1.4 support

### ISSUE THREAD

**Issue by phamhi** [rancher/rancher#24583]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request: istio 1.4 (https://istio.io/news/releases/1.4.x/announcing-1.4/)

Any idea when istio 1.4 will be available on Rancher?

**Steps to reproduce (least amount of steps as possible):**
<not applicable>

**Result:**

**Other details that may be helpful:**
<not applicable>

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): <not applicable>
- Installation option (single install/HA): <not applicable>

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
<not applicable>
```

- Docker version (use `docker version`):

```
<not applicable>
```

**Comment by superseb** [comment]
Covered in https://github.com/rancher/rancher/issues/24700
