### ISSUE TITLE
Keycloak LDAP groups not mapped to rancher

### ISSUE THREAD

**Issue by huegelc** [rancher/rancher#24590]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a SAML client in Keaycloak and set following mappings:

<img width="773" alt="Screenshot 2019-12-13 at 22 44 50" src="https://user-images.githubusercontent.com/6955465/70834289-38c9cc00-1dfa-11ea-8213-cee243f949aa.png">

<img width="777" alt="Screenshot 2019-12-13 at 22 48 31" src="https://user-images.githubusercontent.com/6955465/70834449-b7266e00-1dfa-11ea-8f02-5cb5c05016a8.png">

Rancher settings:

<img width="484" alt="Screenshot 2019-12-13 at 22 46 16" src="https://user-images.githubusercontent.com/6955465/70834371-76c6f000-1dfa-11ea-90d8-f8434e999ae0.png">

I can login and the username gets mapped to displayName but there are no groups available (dropdown is empty)

**Result:**
dropdown empty

**Other details that may be helpful:**
Keycloak 8.0.1
LDAP Group Mapper:

<img width="837" alt="Screenshot 2019-12-13 at 22 52 47" src="https://user-images.githubusercontent.com/6955465/70834750-724f0700-1dfb-11ea-9684-8b15d0fd4c49.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.16.3

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:22:32 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by huegelc** [comment]
I've enabled debugging with:

```
kubectl  -n cattle-system get pods -l app=rancher | grep '1/1' | awk '{ print $1 }' | xargs -I{} kubectl --kubeconfig $KUBECONFIG -n cattle-system exec {} -- loglevel --set debug
```
and this is what I get:

```
[DEBUG] Requesting user: user-xspsl, Requesting groups: [keycloak_group:///g-XXXX-Admin keycloak_group:///g-XXX_AWX_Network system:authenticated] Impersonate user:  Impersonate group: []
```

Apparently the groups are received by rancher but not displayed in the UI dropdown list

**Comment by donatasnicequestion** [comment]
Just to confirm - the same Issue (after migration from Rancher 2.3.2 to 2.3.3).

**Comment by donatasnicequestion** [comment]
Tested keycloak security with v2.3.4-rc4: groups are displayed in a dropdown.
Therefore it looks that this functionality ist broken in a version v2.3.3:
in 2.3.2 and 2.3.4 RC4 it works.

**Comment by huegelc** [comment]
@donatasnicequestion thanks for confirmation

**Comment by huegelc** [comment]
works after upgraded to rancher 2.3.4
