### ISSUE TITLE
unable to access 'https://git.rancher.io/charts/': Could not resolve host: git.rancher.io

### ISSUE THREAD

**Issue by robinbraemer** [rancher/rancher#24600]
The tutorial at https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/ does not work.
I tried it with let's encrypt.

Rancher pod logs:
```
019/12/14 16:28:25 [ERROR] ProjectController local/p-bklk7 [system-image-upgrade-controller] failed with : upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found
2019/12/14 16:28:33 [ERROR] CatalogController library [catalog] failed with : Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
fatal: unable to access 'https://git.rancher.io/charts/': Could not resolve host: git.rancher.io
: exit status 128
```

complete log: https://pastebin.com/raw/RWSxfpfH

**Comment by robinbraemer** [comment]
My fault, i did install an incompatible docker version on my centos instance where networking does not work.

**Comment by lerit** [comment]
@robinbraemer  i face same problem in centos8 after install docker,would you please tell me what is the docker version problem?

**Comment by robinbraemer** [comment]
@lerit I've installed an incompatible docker version on centos manually where the docker networking was not functioning, so kubernetes networking neither.

I simply recommend the https://get.docker.com/ script for docker installation.
`curl -fsSL https://get.docker.com | sh` As simple as running one command.

**Comment by tnlp** [comment]
hi how do you fix this errors?

**Comment by robinbraemer** [comment]
I installed a compatible docker version

**Comment by tnlp** [comment]
```
CentOS Linux release 7.7.1908 (Core)
docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:26:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:28:17 2019
  OS/Arch:          linux/amd64

```
i cannot

**Comment by sunkai-XDD** [comment]
@robinbraemer  hi ,by the way, what's your docker version?
