### ISSUE TITLE
Feature request: Enforce password policy for local authentication - Rancher 2.x

### ISSUE THREAD

**Issue by nickngch** [rancher/rancher#24609]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

Description
Be able to enforce password policies (length/characters/re-use times) for the local users.

gz#7692

gz#14100

**Comment by ChrML** [comment]
I support this request and tbh it's a very important security issue. We have a few users that deploy apps in Rancher, and we have no way to enforce them to create strong passwords.

The worst password accepted by Rancher is a single "a" or "Password123" and we have no way to check if they do. Which is a real security concern!

**Comment by ChrML** [comment]
Even if re-use times is not specified, just a simple regex config parameter that defaults to a reasonable password-strength would be a huge security improvement.

**Comment by travis-sobeck** [comment]
I thought it was only me confused at being un-able to find settings for this or even docs.

**Comment by cbron** [comment]
Hadn't seen this issue before. A min-length setting for local auth was introduced in 2.6.3: https://github.com/rancher/rancher/blob/0a448404276a890ed6cd9a383ee5a8d516b6c75f/pkg/settings/setting.go#L64

We looked into using block-lists to avoid weak passwords, but hit problems around making it work in air-gap. High storage volume, and updating over time etc... We still recommend using an external auth provider for the best security in production environments.
