### ISSUE TITLE
delete a node,then add it ,stuck Waiting to register with Kubernetes

### ISSUE THREAD

**Issue by 13567436138** [rancher/rancher#24604]
**What kind of request is this (question):**

**Steps to reproduce (least amount of steps as possible):**
delete a node
then run 
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.3.3 --server https://192.168.198.154:8443 --token p6xpsfdjlxvwkm74d9qfhckqj4xqqmz7n6rkppw6bnlwtrm9rpcxdk --ca-checksum f71cda0c532a39c8cf506334dc2241bc510020ed936eea95f9266379832a20d7 --worker

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
Can you provide more info on the steps to reproduce? When deleting a node, it needs to be cleaned before it can be re-added again as described on https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/.
