### ISSUE TITLE
Secret is mounted as a directory removing existing files in that directory - No option to mount as files?

### ISSUE THREAD

**Issue by y2krelic** [rancher/rancher#24602]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
- create a secret
- mount as a secret and choose an existing path in the container path
- container/pod starts and secret exists, but previously existing files in the path are overwritten by the mount

**Result:**
- container/pod starts and secret exists, but previously existing files in the path are overwritten by the mount

**Other details that may be helpful:**
Rancher V2.3.2

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Rancher V2.3.2

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by vincent99** [comment]
That's how mounts in general work and how Kubernetes works.  If you want a single file you can select a single key out of the secret and mount it at a path with a particular filename.
