### ISSUE TITLE
Remove "Manage Cluster Scans" role

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24613]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. As an Admin deploy a custom cluster.
2. Add a Standard User- User1 as a member of the cluster with custom role - `Manage Cluster Scans`
3. Login as User1, and navigate to Cluster --> Tools --> CIS Scans 
Error is seen on the UI

**Chrom browser:**
<img width="405" alt="Screen Shot 2019-12-16 at 9 35 57 AM" src="https://user-images.githubusercontent.com/26032343/70930490-2e6e2480-1fea-11ea-8c32-072a6d336f23.png">

**FF browser:**
<img width="315" alt="Screen Shot 2019-12-16 at 9 35 51 AM" src="https://user-images.githubusercontent.com/26032343/70930493-2f9f5180-1fea-11ea-86d9-1f10ca19f4c2.png">

**Expected Result:**
User should be able to launch the page

**Note:**
User is able to run CIS SCans via API UI.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.15
```

**Comment by codyrancher** [comment]
@leodotcloud @deniseschannon Murali was right. I was able to confirm that this is happening when we attempt to access the system project to get the configMaps.

**Comment by deniseschannon** [comment]
With further discussion with @cloudnautique , it doesn't make sense to have a separate "Manage Cluster Scans" role due to the nature of how to run a cluster scan. Keeping this issue open to track removing the role.

**Comment by sowmyav27** [comment]
Verified on UI on `master-head` latest

- go to Global --> Security --> Roles 
- Under Global and Cluster, "Manage Cluster Scans" is not listed anymore
- Under `v3/globalroles` and `v3/roleTemplates/`, "Manage Cluster Scans" is not listed.
