### ISSUE TITLE
Service upgrade failure

### ISSUE THREAD

**Issue by lielran** [rancher/rancher#2461]
rancher-compose Version: v0.5.0-rc2 
Rancher	v0.42.0 (tested also with V0.41.0 - same result)
Cattle	v0.102.0
User Interface	v0.57.0
Rancher Compose	v0.4.3
```
rancher-compose upgrade oldService newService --cleanup --update-links  
```
end up with this:
```
INFO[0001] Creating service newService
INFO[0004] Upgrading oldService to newService, scale=1
FATA[0004] Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=Either toServiceId or launchConfig/secondaryLaunchConfigs params need to be specified, code=InvalidOption] from [http://rancher.xxxxxxx.com:8080/v1/services/1s213/?action=upgrade]
```

the final result that the old service is still exist + a new one was created but with scale of 0 ('no container' state ). 

i'm thinking it's because the new rancher compose version was the only thing change lately (

**Comment by lielran** [comment]
re-test it with Rancher Compose Version: v0.4.2 

and it's working again !

**Comment by MarcusSjolin** [comment]
I get the same error using rancher-compose version v0.5.1

FATA[0000] Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidOption, fieldName=Either toServiceId or launchConfig/secondaryLaunchConfigs params need to be specified] from [http://rancher:8080/v1/services/1s11/?action=upgrade]

**Comment by deniseschannon** [comment]
We've started specifying versions of Rancher-compose that are compatible with Rancher. In these cases, you need to upgrade your version of Rancher to use the updated rancher-compose. 

Rancher: v0.41.0 uses Rancher-compose v0.4.1
Rancher: v0.42.0 uses Rancher-compose v0.4.3
Rancher: v0.43.1 uses Rancher-compose v0.5.0

When you align the release versions for Rancher and rancher-compose, the upgrade will work with no issues.
