### ISSUE TITLE
cannot start EC2 cluster - docker: Error response from daemon

### ISSUE THREAD

**Issue by gilko1981** [rancher/rancher#24612]
I am using the rancher AMI (us-east-1 | HVM | ami-03383c16defb1ed02).

2019/12/16 14:09:17 [INFO] [node-controller-docker-machine] Creating CA: /management-state/node/nodes/rancher1/certs/ca.pem
2019/12/16 14:09:18 [INFO] [node-controller-docker-machine] Creating client certificate: /management-state/node/nodes/rancher1/certs/cert.pem
2019/12/16 14:09:18 [INFO] [node-controller-docker-machine] Running pre-create checks...
2019/12/16 14:09:18 [INFO] [node-controller-docker-machine] Creating machine...
2019/12/16 14:09:18 [INFO] [node-controller-docker-machine] (rancher1) Launching instance...
2019/12/16 14:09:56 [INFO] [node-controller-docker-machine] Waiting for machine to be running, this may take a few minutes...
2019/12/16 14:09:57 [INFO] [node-controller-docker-machine] Detecting operating system of created instance...
2019/12/16 14:09:57 [INFO] [node-controller-docker-machine] Waiting for SSH to be available...
2019/12/16 14:10:44 [INFO] [node-controller-docker-machine] Detecting the provisioner...
2019/12/16 14:10:44 [INFO] [node-controller-docker-machine] Provisioning with rancheros...
2019/12/16 14:12:57 [INFO] [node-controller-docker-machine] Copying certs to the local machine directory...
2019/12/16 14:12:59 [INFO] [node-controller-docker-machine] Copying certs to the remote machine...
2019/12/16 14:13:01 [INFO] [node-controller-docker-machine] Setting Docker configuration on the remote daemon...
2019/12/16 14:13:06 [INFO] [node-controller-docker-machine] Checking connection to Docker...
2019/12/16 14:13:06 [INFO] [node-controller-docker-machine] Docker is up and running!
2019/12/16 14:13:21 [INFO] Generating and uploading node config rancher1
**2019/12/16 14:13:21 [ERROR] NodeController c-g2c48/m-k82c4 [node-controller] failed with : Unable to find image 'rancher/rancher-agent:v2.3.3' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
Process exited with status 125
: exit status 1**

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`global-admin.clusters.index`|
|rancher server|`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:latest` |

**Comment by superseb** [comment]
Sounds like a network related error, probably a (host) firewall. Can you manually run `docker pull rancher/rancher-agent:v2.3.3`? The timeout suggest it can't reach the Docker Hub to retrieve the image.

**Comment by gilko1981** [comment]
@superseb I cannot ssh the machine, a password is required

**Comment by superseb** [comment]
How to access the machine is described at https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-access-nodes-created-by-rancher

**Comment by gilko1981** [comment]
@superseb thanks but that's not possible. Since Docker fails to retrieve the required image, the machine is being destroyed and created over and over again. At no point, the "Nodes view" is available in Rancher portal.

**Comment by superseb** [comment]
Probably the best way to investigate this is to look in the AWS console, look up the created instance and see what VPC and Security Groups it gets assigned, and what IP address the machine gets.

Compare that to the values you get when you manually create an EC2 instance and install Docker and run `docker pull` to reach out to Docker Hub to retrieve images to see where the differences are.

**Comment by superseb** [comment]
Let me know if this needs help
