### ISSUE TITLE
Import yaml in storage classes and Persistent Volumes page

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#24611]
Users should be able to create PV and SC via yaml in storage classes and Persistent Volumes page

![image](https://user-images.githubusercontent.com/21168270/70891696-bbcd6b00-2022-11ea-932d-3dd43c636ec2.png)

![image](https://user-images.githubusercontent.com/21168270/70891772-e7e8ec00-2022-11ea-8f6e-e70e6abe0658.png)

**Comment by aaronRancher** [comment]
The feature is verified with Rancher server `rancher\rancher:master-head` `version 552eb2896`

Before, using `rancher\rancher:v2.3.3`:
![Screen Shot 2020-01-06 at 12 00 16 PM](https://user-images.githubusercontent.com/57409052/71841434-a32dff00-307c-11ea-8471-04ac48b5287c.png)

Using `rancher\rancher:master-head` `version 552eb2896`:
![Screen Shot 2020-01-06 at 12 02 08 PM](https://user-images.githubusercontent.com/57409052/71841442-a88b4980-307c-11ea-96bd-f893d18bb3dc.png)
![Screen Shot 2020-01-06 at 12 02 15 PM](https://user-images.githubusercontent.com/57409052/71841449-aaeda380-307c-11ea-8d4c-e4f293718a91.png)
