### ISSUE TITLE
unable to delete stack/containers 

### ISSUE THREAD

**Issue by lielran** [rancher/rancher#2462]
Rancher v0.42.0 (tested also with V0.41.0 - same result)
Cattle v0.102.0
User Interface v0.57.0
Rancher Compose v0.4.3

I created a LB stack ("load-balancer") and delete it. 
the LB containers is still exist and running even that there is no stack name "load-balancer" in the application view. 

even when i deleted the containers via the UI/docker rm it's they are recreated by rancher. 
upgrade/restart rancher master didn't solve the problem.

please let me know if you need logs or anything else in order to solve this issue.

**Comment by alena1108** [comment]
@lielran looks like Lb service wasn't cleaned up when stack was removed. Could you check the state of the load balancer service under the removed stack? 

Removing individual containers won't make any affect if they belong to non-removed service. Service reconcile process will trigger their recreation. So we have to cleanup the service itself.

**Comment by deniseschannon** [comment]
@lielran. If you are still having this issue, please re-open.
