### ISSUE TITLE
[CIS] - When a cluster scan fails to generate report, the scan is seen Active

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24626]
**What kind of request is this (question/bug/enhancement/feature request):** 

**Steps to reproduce (least amount of steps as possible):**

- Run scan on a cluster deployed with k8s v 1.17
- The scan is seen Active

<img width="1303" alt="Screen Shot 2019-12-16 at 4 51 51 PM" src="https://user-images.githubusercontent.com/26032343/70955074-63976880-2024-11ea-8bf3-ed1dffb5832f.png">

**Expected Result**
The status of the scan should show Error.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`): 

```
1.17
```

**Comment by leodotcloud** [comment]
Earlier, the report was not generated as there was an exception in the summarizer. That part has been taken care of now. Outcome of the offline discussion with Sowmya was to add a timeout on top of that. The test case would be to delete the pod in the middle of the scan.

**Comment by leodotcloud** [comment]
There could be other failure scenarios too. For example, the pod could get stuck for some reason. We need a comprehensive healthcheck to figure out the actual state of the health. That's a bigger enhancement.

**Comment by leodotcloud** [comment]
As part of improving the error handling, this issue needed to be addressed: https://github.com/aquasecurity/kube-bench/issues/546. This got fixed in https://github.com/aquasecurity/kube-bench/releases/tag/v0.2.3 by PR: https://github.com/aquasecurity/kube-bench/pull/548

**Comment by leodotcloud** [comment]
@codyrancher @maggieliu once this issue gets resolved, the UI needs to be able to show the error message (if present) from the condition.

Example from the API ClusterScan object:

```
{
"lastUpdateTime": "2020-02-06T17:01:54-08:00",
"message": "error running sonobuoy",
"status": "True",
"type": "Failed"
},
```

**Comment by sowmyav27** [comment]
**Verified on rancher - master-head - commit id: `0f1c4b17d`**

- If a report fails to generate, CIS Scan is seen with `Error` status on the Rancher UI
- As per offline discussion with @leodotcloud wait time has bee removed - (https://github.com/rancher/system-charts/commit/b62c7cee32bd0cc2ca4be46e5099b0ddd3a7ca9f#diff-034d4bcb31f271b5aef68335ed19b67b)
- Subsequent scan can be run, only when the pods/daemonset of the previous run have been deleted/removed.
- Currently, there is no issue seen with the CIS scan pods getting stuck during/after a cis scan run
- Closing the issue - will reopen if issue is seen
