### ISSUE TITLE
vsphere node template resource lookup fails if there are multiple cloud credentials configured

### ISSUE THREAD

**Issue by ibrokethecloud** [rancher/rancher#24620]
**What kind of request is this (question/bug/enhancement/feature request):** BUG

**Steps to reproduce (least amount of steps as possible):** 
- Setup AWS cloud credentials in Rancher
- Setup VMware cloud credentials in Rancher
- Try and add a node template for VMware
- Look at the network trace, the first call to VMware endpoint is made using the AWS cloud provider ( because that is the first one chosen in the nodeTemplate UI)
- This call fails with response code 422.
- Then rancher tries the same call with Vmware credentials, the vcenter returns the response
- However the UI  no longer processes the response
- If you have any other cloud credential configured, then select that node driver before you select Vsphere. 
- Rancher UI makes calls to vsphere UI using the last selected cloud providers credentials

**Result:**
- The node template functionality may appear broken

**Other details that may be helpful:**
-  Work around is to select a cloud provider for which cloud credentials are not configured before you select Vsphere provider.
- Now vsphere loads the resources just fine.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.16

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by codyrancher** [comment]
@deniseschannon do we want to backport this issue?

**Comment by deniseschannon** [comment]
@codyrancher yes please!

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 7578b3c76
rancher/rancher:v2.3.4-rc7

* Reproduced in Rancher v2.3.3
  * Create vSphere cloud credentials with valid credentials and create a node template
  * Edit the cloud credentials to have an invalid password
  * Create a new node template
  * Create a new cloud credential with valid credentials from within the node template creation screen
  * UI remains locked in some fields even after changing cloud credentials

* Follow same steps above in `v2.3.4-rc7`, and `master-head`
* After selecting the correct cloud credential, all fields are functional in the UI.
