### ISSUE TITLE
RKE v1.0.0 unable to restore from etcd snapshot

### ISSUE THREAD

**Issue by aliabbasjaffri** [rancher/rancher#24632]
**What kind of request is this (question/bug/enhancement/feature request):**
- Bug

**Steps to reproduce (least amount of steps as possible):**
1. I restored the snapshot on a running Rancher HA server and downloaded it locally
2. scp '-ed' it to the target restore server in the folder /opt/rke/etcd-snapshots
3. Ran the rke restore command,
`rke_v1.0.0 etcd snapshot-restore --name 16.12.2019_backup --config rancher-cluster-restore.yaml`

**rancher-cluster-restore.yaml**
```
nodes:
  - address: xx.xx.xx.xx
    user: root
    role: [controlplane,worker,etcd]
    ssh_key_path: ~/.ssh/id_rsa
```

The following output is observed:

**Result:**
```

INFO[0000] Running RKE version: v1.0.0
INFO[0000] Restoring etcd snapshot /opt/rke/etcd-snapshots/16.12.2019_backup
INFO[0000] Successfully Deployed state file at [./rancher-cluster-restore.rkestate]
INFO[0000] [dialer] Setup tunnel for host [xx.xx.xx.xx]
INFO[0001] Checking if container [cert-deployer] is running on host [xx.xx.xx.xx], try #1
INFO[0001] Image [rancher/rke-tools:v0.1.51] exists on host [xx.xx.xx.xx]
INFO[0001] Starting container [cert-deployer] on host [xx.xx.xx.xx], try #1
INFO[0001] Checking if container [cert-deployer] is running on host [xx.xx.xx.xx], try #1
INFO[0006] Checking if container [cert-deployer] is running on host [xx.xx.xx.xx], try #1
INFO[0006] Removing container [cert-deployer] on host [xx.xx.xx.xx], try #1
INFO[0006] Stopping container [etcd] on host [xx.xx.xx.xx] with stopTimeoutDuration [5s], try #1
WARN[0006] Can't stop Docker container [etcd] for host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
INFO[0006] Stopping container [etcd] on host [xx.xx.xx.xx] with stopTimeoutDuration [5s], try #2
WARN[0006] Can't stop Docker container [etcd] for host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
INFO[0006] Stopping container [etcd] on host [xx.xx.xx.xx] with stopTimeoutDuration [5s], try #3
WARN[0006] Can't stop Docker container [etcd] for host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
INFO[0006] [etcd] starting backup server on host [xx.xx.xx.xx]
INFO[0006] Image [rancher/rke-tools:v0.1.51] exists on host [xx.xx.xx.xx]
INFO[0007] Starting container [etcd-Serve-backup] on host [xx.xx.xx.xx], try #1
INFO[0007] [etcd] Successfully started [etcd-Serve-backup] container on host [xx.xx.xx.xx]
INFO[0013] Removing container [etcd-Serve-backup] on host [xx.xx.xx.xx], try #1
WARN[0013] failed to start backup server on host [xx.xx.xx.xx]: Failed to run backup server container, container logs: time="2019-12-16T15:50:44Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory"
INFO[0013] Starting container [etcd] on host [xx.xx.xx.xx], try #1
WARN[0013] Can't start Docker container [etcd] on host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
INFO[0013] Starting container [etcd] on host [xx.xx.xx.xx], try #2
WARN[0013] Can't start Docker container [etcd] on host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
INFO[0013] Starting container [etcd] on host [xx.xx.xx.xx], try #3
WARN[0013] Can't start Docker container [etcd] on host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
WARN[0013] failed to start etcd container on host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd
FATA[0013] failed to start backup server on all etcd nodes: [Failed to run backup server container, container logs: time="2019-12-16T15:50:44Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory"
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher v2.3.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): v1.16.3
- Docker version (use `docker version`): 19.03.5

**Comment by Oats87** [comment]
Are you trying to restore the snapshot onto a new server? This looks like the `cert-deployer` was unable to populate the `/etc/kubernetes/ssl` directory with the necessary certificates to allow the cluster to function.

**Comment by aliabbasjaffri** [comment]
Yes, that was exactly what the case was. Because RKE didn't have access to the `.rkestate` file, it couldn't restore the contents either. I thought the backup is comprised of everything, including the certificates themselves so this should happen seamlessly. But actually the `restore` function needs the `.rkestate` file from the old cluster in order to proceed with the functionality. I didn't find this anywhere in the documentation and had me wondering for a while and then eventually using the `.rkestate` file from the old cluster to successfully restored.

**Comment by superseb** [comment]
This is now in the docs
