### ISSUE TITLE
Node template with RancherOS uses docker 18 instead of 19

### ISSUE THREAD

**Issue by AntonSmolkov** [rancher/rancher#24630]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create Vsphere node template, use default engine option -  
Docker Install URL = https://releases.rancher.com/install-docker/19.03.sh

**Result:**
Nodes created from tempate use Docker version  - **18.9.8**

**Reason?**
I guess that is because 19.03.sh expects version **19.03.5**:

```	
...
docker_version=19.03.5
...
$sh_c "sleep 3;ros engine list --update"
engine_version="$(sudo ros engine list | awk '{print $2}' | grep ${docker_version} | tail -n 1)"
if [ "$engine_version" != "" ]; then
	$sh_c "ros engine switch -f $engine_version"
fi
```

But latest available inside RancherOS at the moment is -**19.03.4**

```
root@com-tcdocker-01:~# ros engine list --update
...
disabled docker-18.09.7
current  docker-18.09.8
disabled docker-18.09.9
disabled docker-19.03.0
disabled docker-19.03.1
disabled docker-19.03.2
disabled docker-19.03.3
disabled docker-19.03.4
```

**Envinronment**
Rancher 2.3.3
RancherOS 1.5.4
VMware VSphere 6.5

**Comment by superseb** [comment]
Docker 19.03.5 was added but not backported, I created this issue for it https://github.com/rancher/os/issues/2939
