### ISSUE TITLE
Node labels and taints UI Issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#24640]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1.  Go to create custom cluster
2.  Give it a name and click on Next
3.  Click on Show Advanced options

**Result:**
- [ ] Buttons for Add label and Add Taint are too close to the text above it.
![image](https://user-images.githubusercontent.com/11514927/71031084-f2ad8a80-20cf-11ea-84bf-036697452831.png)

- [ ] Inconsistent spacing when you add a label & taint between first addition and text
![image](https://user-images.githubusercontent.com/11514927/71031169-17a1fd80-20d0-11ea-93a4-be04f9b8fcd6.png)

- [ ] Help text is not helpful.  Either add text that tell what these things do or remove it.
![image](https://user-images.githubusercontent.com/11514927/71031230-330d0880-20d0-11ea-8e51-2a20cd6e0789.png)
![image](https://user-images.githubusercontent.com/11514927/71031251-3d2f0700-20d0-11ea-8462-ae705f5dfac0.png)

**Comment by sowmyav27** [comment]
**On `2.3.4-rc6`**

<img width="1170" alt="Screen Shot 2020-01-03 at 8 33 08 AM" src="https://user-images.githubusercontent.com/26032343/71735637-cdc15300-2e03-11ea-8a9a-b54fb5a5e84f.png">

Verified the issues mentioned here - `https://github.com/rancher/rancher/issues/24640#issue-539291027`


**Verified on latest master-head - commit id: `8bd9f3be2`, ui tag: `latest2`**

- Helpful text for Node Labels have been removed
- Spacing is consistent when you add a label & taint between first addition and text
<img width="1329" alt="Screen Shot 2020-01-03 at 8 33 03 AM" src="https://user-images.githubusercontent.com/26032343/71735731-07925980-2e04-11ea-8136-8a8593c89b99.png">
