### ISSUE TITLE
Google Auth - "Read from file" for "Service Account Credentials" inserts text into incorrect input field

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24649]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On latest master, go to Security --> Authentication --> Google Auth
- Click on "Read from file" for "Service Account Credentials"

**Expected Result:**
"Read from file" for "Service Account Credentials" should insert the file contents into "Service Account Credentials" input field.

**Actual Result:**
"Read from file" for "Service Account Credentials" inserts the file contents into "OAuth Credentials" input field.

<img width="1327" alt="Screen Shot 2019-12-17 at 2 43 16 PM" src="https://user-images.githubusercontent.com/26032343/71042958-1083eb00-20e2-11ea-9895-694ae3b253b6.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master head - latest - commit id: `e8fbc0c84`
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
A fix was made in this PR already.

https://github.com/rancher/ui/pull/3732

**Comment by sowmyav27** [comment]
**Verified on latest master-head - commit id: `f01cca783` ui tag: `latest2`**

- Navigate to Security --> Authentication --> Google Auth
- Click on "Read from file" for "Service Account Credentials"
- "Read from file" for "Service Account Credentials" inserts the file contents into "Service Account Credentials" input field.
