### ISSUE TITLE
Unable to deploy a cluster on latest master

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24647]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy an AWS/DO rke cluster.

**Expected Result:**
The cluster should come up successful and be Active

**Actual Result:**
The cluster fails to come up with error
`Error setting machine configuration from flags provided: gob: type not registered for interface: cli.StringSlice; Timeout waiting for ssh key`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master - head - commit id: `e8fbc0c84`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by luthermonson** [comment]
@sowmyav27 merged new rancher-machine into master please give it a try. we were making clusters locally with no issues so assume this vendor rollback will work for you too.

**Comment by sowmyav27** [comment]
Verified on master-head latest- commit id: `fa26eccdb`

Deployed an rke cluster successfully.
