### ISSUE TITLE
About kubectl from rancher v2.2.2

### ISSUE THREAD

**Issue by yangjia517** [rancher/rancher#24656]
# resources:
rancher version：V2.2.2
docker version：18.06
Linux：ubuntu16.04

# Problem Description:
Use the RKE cluster installed by helm, and add the subgroups of other hosts:
![image](https://user-images.githubusercontent.com/33953118/71048588-a66b5480-217a-11ea-9202-0085b235662b.png)
When I use kubectl to access the cluster, there is an error message. I try to use kubectl on both the web page and the host. The results are the same when I use kubectl。
![image](https://user-images.githubusercontent.com/33953118/71048775-4e811d80-217b-11ea-8472-d6255a3f069f.png)
I'm not sure what's the cause of the problem. Please help to find out. Thank you！

**Comment by yangjia517** [comment]
@superseb

**Comment by superseb** [comment]
What RKE version did you use to setup the HA cluster for Rancher? What is the `server:` value pointing to? Your own load balancer, if so what one, if not, is it a DNS name to one of the nodes? Did this work before? Since when doesn't it work or has it not worked at all?

**Comment by yangjia517** [comment]
@superseb
Thanks for helping

RKE version: RKE version v0.2.6

I have multiple clusters, only the kubectl of this cluster fails. I execute the command on the page of rancher:
![image](https://user-images.githubusercontent.com/33953118/71456446-61779b80-27d4-11ea-8de9-7ffac8f701f7.png)
The server that this cluster configuration file points to:：
![image](https://user-images.githubusercontent.com/33953118/71456533-cfbc5e00-27d4-11ea-83c7-fe288aa1b54c.png)
DNS resolution of the server is normal. It was used normally before. I didn't have any operation to fail suddenly.

**Comment by superseb** [comment]
Only on one cluster? All the kubeconfigs point to the same hostname for Rancher I assume? Can you share whats different between a working and non working cluster? And did it ever work or never for this cluster?

**Comment by superseb** [comment]
Let me know if this needs help.
