### ISSUE TITLE
API has editable fields for fields that are not-editable for EKS clusters

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#24652]
EKS edit, I can change the subnets and I see the changes applied from Rancher but if I inspect the AWS EKS web console I do not see the Subnets edited.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

Rancher version 2.4 master-head (12/17/2019) e8fbc0c

1. I create a cluster with a VPC which has **4 subnets**.
2. Cluster gets created.
3. I am able to edit the cluster and the VPC can be selected now.
4. After selecting the VPC, I **remove** one of the subnets.
5. After saving I see the subnet I unselected in the previous step is no longer listed in the UI.
6. Save the security group.
7. Finally save settings.

After all that I now edit the cluster again and I see the cluster Rancher is listing **3 subnets**. But in AWS EKS web console I see the **original 4 subnets** from step 1. So this not seems to be applying the settings in the EKS cluster.

**Result:**

Changes made in the EKS cluster from Rancher are actually applied in the EKS cluster.

**Other details that may be helpful:**

https://github.com/rancher/rancher/issues/23879

**Environment information**
- Rancher version: `2.4 master-head (12/17/2019)` e8fbc0c
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS 
- Machine type (cloud/VM/metal) and specifications (CPU/memory):  cloud
- Kubernetes version (use `kubectl version`):

```
1.14 (AWS)
```

**Comment by daxmc99** [comment]
This is part of a larger issue with EKS in general. The current way we provision EKS clusters uses cloud formation and doesn't always clean up nicely. 

Per https://github.com/rancher/rancher/issues/23879#issuecomment-566785911
>
>The backend should change the schemas to not be updatable if they are not available to >update.

This is my planned course of action with this issue. These fields will no longer be editable on the backend

**Comment by deniseschannon** [comment]
Overall, the issue is that the schema makes it seem like you can edit fields that you can't. 

We've updated the UI in 2.4 to make these fields read only, but since the subnet is being saved as `null` and being returned from AWS as `null`, there is a UI fix to just send an empty array instead of properly fixing the backend. 

When we fix the API schema to make these fields not editable we should also investigate why the API is returning a null value for when an empty array is sent. Also the field is non-nullable, which makes it extra weird.

**Comment by rancher-max** [comment]
Subnet is only being saved as null when using the default value of `VPC and Subnet are automatically created` during eks cluster creation.

**Comment by rancher-max** [comment]
UI issue mentioned above is fixed for Rancher v2.4.0 https://github.com/rancher/rancher/issues/26231#event-3169853091

**Comment by izaac** [comment]
Rancher version `2.4-head (04/21/2020)` commit id: 4fae0c687
Rancher version `master-head (04/21/2020)` commit id: bfef84c27

I was able to edit Cluster Name, Members Roles, Kubernetes Version.
Labels and Annotations appear as editable too. Everything else is shown as uneditable including Service Role, VPC and subnets, SGs, Node Options and User Data.
