### ISSUE TITLE
Feature request: filter/search on containers

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#2465]
We have rather many containers that are not yet managed by rancher. But rancher has proven to be a nice gui even for these, but it gets more difficult to navigate the containers list when there are a lot of similarly named containers in various states (running/stopped).

Search/filter on any of the available columns would be nice, as well as to be able to hide stopped containers.

Related FR: #1824

**Comment by vincent99** [comment]
Consolidating with #1533
