### ISSUE TITLE
Cannot edit PV created by CSI plugin storageclass through Rancher UI

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#24665]
*Describe your issue here*
1. Create a PVC and using csi plugin storageclass such as longhorn.
2. Check the PV at cluster level, click edit.
3. The volume plugin field shows n/a and plugin configuration field doesn't show any information. 
4. Try to change the PV size (if it's supported)  and click save.
5. You will get an error message ”volume plugin is required"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`volumes.new`|

**Comment by sowmyav27** [comment]
**Reproduced the issue on `rancher:v2.3.3`**

**Steps:**

- Install Longhorn in a cluster; go to cluster --> Project --> Apps --> LogHorn --> launch.
- Wait for the workloads to be Active
- Go to cluster level --> Storage --> Storage class Longhorn will be added.
- Deploy a workload using Storage Class Longhorn.
- Check PV in the cluster page.
- Volume Plugin* : n/a is seen
- Change `Capacity` and click on Save.
- `"Volume Plugin" is required` error is seen.

<img width="1474" alt="Screen Shot 2020-01-03 at 9 21 06 AM" src="https://user-images.githubusercontent.com/26032343/71738197-ca7d9580-2e0a-11ea-8492-41d052d5aaf8.png">

**On `master-head` commit id: `8bd9f3be2` and ui tag: latest2**

- Install Longhorn in a cluster; go to cluster --> Project --> Apps --> LogHorn --> launch.
- Wait for the workloads to be Active
- Go to cluster level --> Storage --> Storage class Longhorn will be added.
- Deploy a workload using Storage Class Longhorn.
- Check PV in the cluster page.
- `Volume Plugin* : CSI` is seen
<img width="1455" alt="Screen Shot 2020-01-03 at 9 27 11 AM" src="https://user-images.githubusercontent.com/26032343/71738384-51327280-2e0b-11ea-8b82-ac26a796db63.png">

- Change `Capacity` and click on Save. No error is seen on the UI

**Comment by loganhz** [comment]
yes, it’s expected.

**Comment by sowmyav27** [comment]
Closing this issue as the fix works as expected.
