### ISSUE TITLE
Login page 【Network request failed】

### ISSUE THREAD

**Issue by NICK-DUAN** [rancher/rancher#24660]
#### Login Failed

my rancher server run well, and i can send some requests to server with api key,
but when i use rancher web, it‘s notice me like as shown below:

![image](https://user-images.githubusercontent.com/22417013/71053858-d9b5df80-218a-11ea-9a5b-3e9a5ad5f3bd.png)

**when I turn on incognito mode in chrome brower, i won't get this problem**

To solve this problem:
- delete all cookies in my chrome brower
- click 'Reload'
 all doesn't work

**Comment by loganhz** [comment]
It should be some browser issue. Please check the error in Chrome network tab. https://cheapsslsecurity.com/blog/google-chrome-ssl-certificate-errors-troubleshoot-guide/

**Comment by NICK-DUAN** [comment]
Yes, with this link, I check my chrome version, and found that it needed to be updated，but update error, then i unintall and install agin. it fixed.
