### ISSUE TITLE
[Forwardport] 2.4: GenerateKubeconfigActionHandler panics if LocalClusterAuthEndpoint is nil

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#24668]
Forwardport: https://github.com/rancher/rancher/issues/23783

**Comment by jiaqiluo** [comment]
The bug fix is validated in master-head a106f2a

- create import cluster
- select "Kubeconfig File" or use generateKubeConfig action in API UI ==> The kubeconfig is generated and no errors in the log
- edit imported cluster, change the description, save
- select "Kubeconfig File" or use generateKubeConfig action in API UI ==> The kubeconfig is generated and no errors in the log
