### ISSUE TITLE
Option to force update ResourceQuotas on existing Namespaces, when updating the Namespace Default Limit of a resource on a Project

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#24664]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Steps to reproduce (least amount of steps as possible):**

The ResourceQuota configuration on Projects currently defines a `Namespace Default Limit`, which will apply to new namespaces (or those without a limit for the particular resource). The user would like an option to update the limit on existing namespaces when updating the `Namespace Default Limit` for a resource on a Project, perhaps via an option such as an "Apply to existing namespaces" checkbox.

**Environment information**
- Rancher v2.2.8

gz#7482

**Comment by cbron** [comment]
This doc says workaround exists: https://rancher.com/docs/rancher/v2.5/en/project-admin/resource-quotas/quotas-for-projects/

> To update a namespace default limit for existing namespaces you can delete and subsequently recreate the quota at the project level with the new default value. This will result in the new default value being applied to all existing namespaces in the project.

Would that work ? I get that a "force" button would be easier.

**Comment by axeal** [comment]
@cbron That would work and the request was closed out by the customer, so I think this issue could be closed.
