### ISSUE TITLE
Forward port: Permissions are not updated in cluster when a cluster role is modified

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#24670]
Forward port of: https://github.com/rancher/rancher/issues/23292

Addressed by https://github.com/rancher/rancher/pull/24661/commits/6dee0d8cae16a5020f752e7de5526614e520850c

**Comment by sowmyav27** [comment]
Reproduced the issue on rancher:v2.3.0

**Steps:**

- Create a cluster and a local user
- Create a Custom Node cluster role with all permissions to Node resource
- Edit the cluster, add the user as a member to the cluster with "Custom Node" role.
- In another browser, log in as local user, verify that user can "drain" a node in the cluster.
- Go back to original browser (admin), edit the Custom Node cluster role and change permissions to Read, List, Watch for Node resource.
- Go to 2nd browser (user) and attempt to "drain" node in the cluster. Allows you to do this, even though should no longer have permissions.
- Log out as user and log back in. User can still drain nodes.
- If admin removes the member and adds them again, then the ability to drain nodes is revoked.
