### ISSUE TITLE
Cannot select StatefulSet as HPA target in Rancher UI

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#24677]
Users should be able to select StatefulSet as HPA target in Rancher UI

**Comment by soumyalj** [comment]
Observed in v2.3.3 that statefulset cannot be selected as a HPA target. The dropdown does not show the statefulset created .

Tested with master-head build (b3bc13a88).
1. Created stateful set
2. Created HPA with statefulset as a target. The dropdown for workload selection does show the stateful set.

<img width="258" alt="Screen Shot 2020-01-22 at 3 10 40 PM" src="https://user-images.githubusercontent.com/18536626/72942855-607d4f80-3d29-11ea-8e15-0e47788bb7af.png">

HPA with statefulset as target is functional.
