### ISSUE TITLE
Error seen when config.json has an invalid numeric value

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24678]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- In the config.json of a cluster (System project --> Configs ), enter the value of config.json to be 100 or any numeric value.
- Go to Cluster --> tools --> CIS scans page. Refresh the page.
- Click on any one of the reports available.
- The details page of the report loads successfully.
- Click on Skip on one of the tests failed, error is seen in console

**Expected result:**
Error to be similar to one where non numeric invalid value is entered - `Unexpected token a in JSON at position 0`

**Actual Result:**
- when the config.json value : `100` (any invalid numeric value)

**Error seen in UI:**
<img width="341" alt="Screen Shot 2019-12-18 at 9 34 28 PM" src="https://user-images.githubusercontent.com/26032343/71147991-4f4b9b00-21df-11ea-8eb2-c163e6065d49.png">

**Error in console:**
```
service.js:79 Uncaught TypeError: Cannot read property 'rke-cis-1.4' of undefined
    at n.validateSecurityScanConfig (service.js:79)
    at n.toggleSkip (controller.js:189)
    at toggleSkip (controller.js:163)
    at n.toggleSkip (component.js:19)
    at n.send (action_support.js:19)
    at n [as send] (utils.js:365)
    at glimmer.js:8706
    at o (index.js:143)
    at glimmer.js:8705
    at e.n._run (backburner.js:1066)
```

- when the config.json value : `abc` (any invalid value other than numeric value)

**Error seen in UI:**
<img width="333" alt="Screen Shot 2019-12-18 at 9 36 05 PM" src="https://user-images.githubusercontent.com/26032343/71147958-3347f980-21df-11ea-8857-03916810d380.png">

**Error in console:**
```
service.js:72 Uncaught SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at n.validateSecurityScanConfig (service.js:72)
    at n.toggleSkip (controller.js:189)
    at toggleSkip (controller.js:163)
    at n.toggleSkip (component.js:19)
    at n.send (action_support.js:19)
    at n [as send] (utils.js:365)
    at glimmer.js:8706
    at o (index.js:143)
    at glimmer.js:8705
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `48a2c4ffc`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by codyrancher** [comment]
@sowmyav27 @maggieliu I don't consider this a bug. The reason the message is different is because we encountered a different parsing error. 

In this case when looking for 'rke-cis-1.4' we failed to find it because a number was specified instead of an object with a skip property. When attempting to lookup skip['rke-cis-1.4'] skip was 'undefined'.

I can remove the details from the notification if that's desired but I put them in there to help the people that are defining the config map by hand.

**Comment by sowmyav27** [comment]
@codyrancher Users would expect same message for any invalid input given - either numeric/alpha characters. I am not sure I understand why the message/validation has to be different for different types of input.

**Comment by sowmyav27** [comment]
Json parses abc and gives error - SyntaxError: Unexpected token a in JSON at position 0
where json parses 100 and results in no error. 
This field corresponds to the value in a config.json , ex: {"skip":{"rke-cis-1.4":["1.1.9"]}}.

The two different errors in the detail section of error message are expected. (for better debug purpose)
