### ISSUE TITLE
`rancher-compose rm` doesn't block until deletion is complete

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2467]
When deleting services using `rancher-compose rm`, the command returns immediately without waiting for the actual deletion to complete. This makes it difficult to script the deletion and recreation of services.

**Comment by deniseschannon** [comment]
Instead of adding this into Rancher Compose, we recommend using the new [Rancher CLI](http://docs.rancher.com/rancher/cli/) which supports `rancher -w rm`. The `-w` would wait until the resources are in resting state.
