### ISSUE TITLE
BUG Release 2.3.3 breaks vSphere driver : vm retry / recreation

### ISSUE THREAD

**Issue by Heiko-san** [rancher/rancher#24686]
![rancher-2 3 3-retry-bug](https://user-images.githubusercontent.com/10023733/71179739-0f34f880-2271-11ea-9891-51c8c63d90ec.png)
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

* create a new node-template using the GUI an provide a cloud init file (or do anything else that will cause the VM launch to fail)
* create a new cluster / node pool from template

**Result:**

* see creation of VM fail 
* see retry fail with error: "Error in driver during machine creation: The name 'my-vm1' already exists."

**Other details that may be helpful:**

* the old VM is not deleted before retrying to create it (which definitly worked before / in version 2.2.9)
* in most of the cases rancher seems to think it is cleaning up the old VM, but in some rare cases it seems even this isn't done -> see screenshot

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Comment by hsartoris-bard** [comment]
This is really the same issue as https://github.com/rancher/rancher/issues/24685, which again has been discussed. If you follow the steps listed [here](https://github.com/rancher/rancher/issues/24315#issuecomment-564173340) (comment on the issue I linked to on your other issue), I think you'll find that VMs can be both created and deleted.

**Comment by Heiko-san** [comment]
No this is not the same, I have experienced this with many different initial errors, not only the folder problem (which you are right is shown on the screenshot).

What I actually want to say here is:

If **for any reason** VM creation fails, then rancher used to delete the VM and try again (= create and start a new VM).  
But now with 2.3.3 it tries to do so aswell, but then fails with an "ups this VM is already there" error because it didn't actually delete the VM (in vCenter).  
= the VM is shutdown and lies there but in rancher it vanishes from node pool, then it is shown up in node pool as a new VM, but this time it fails because it already exists in vCenter  
(I'm not sure how to express better, I hope you understand what I'm trying to say)

**Comment by char-iot** [comment]
BUG noted and solved. Workaround for now: https://github.com/rancher/rancher/issues/24315#issuecomment-564173340
