### ISSUE TITLE
BUG Release 2.3.3 breaks vSphere driver : folders

### ISSUE THREAD

**Issue by Heiko-san** [rancher/rancher#24685]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

* create a new node-template using the GUI an provide a folder
* create a new cluster / node pool from template

**Result:**

* see creation of VM fail with error: "Error creating machine: Error in driver during machine creation: vm 'my-datacenter/vm/my-folder/my-vm1' not found"

**Other details that may be helpful:**

* before 2.3.3 we used "/my-folder" which worked perfectly (and actual still does, tried with the terraform provider)
* with new dropdown menu this folder now became "/my-datacenter/vm/my-folder"
* this actually works partly, VMs is created and it is located inside the folder
* however the start will fail with the error from above

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Comment by hsartoris-bard** [comment]
This has been discussed and patched: https://github.com/rancher/rancher/issues/24315

**Comment by Heiko-san** [comment]
ok, as far as I understand, this fix should work, so closing this issue is fine for me
