### ISSUE TITLE
compute node performing registration through proxy: i/o timeout | wss:// seems to ignore proxy settings

### ISSUE THREAD

**Issue by rmalchow** [rancher/rancher#24681]
**What kind of request is this (question/bug/enhancement/feature request):**
might be my mistake - otherwise, it could be a bug

**Steps to reproduce (least amount of steps as possible):**

- set up management/ui cluster with a TLS offloader (we're using apache here, with h2 support)
- set up a forward proxy in the target environment (we tried squid and tinyporxy)
- run the agent registration: 

`docker run --privileged --restart=unless-stopped --net=host -e HTTP_PROXY=${http_proxy} -e HTTPS_PROXY=${http_proxy} -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.3.3 --server https://rancher.foobar.com --token XXXXXXX --etcd --controlplane --worker`

**Result:**
we see the CONNECT method on the proxy, we also see the TLS handshake go through both the proxy and arrive at the apache. we also see this:

> https://rancher.foobar.com/ping is accessible

after that, no more packets go through. output of the rancher agent is:

time="2019-12-19T09:39:08Z" level=info msg="Connecting to wss://rancher.foobar.com with token $token"
time="2019-12-19T09:39:08Z" level=info msg="Connecting to proxy" url="wss://rancher.foobar.com/v3/connect/register"
time="2019-12-19T09:39:18Z" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp :443: i/o timeout"
time="2019-12-19T09:39:18Z" level=error msg="Remotedialer proxy error" error="dial tcp $IP_OF_APACHE:443: i/o timeout"

... and this keeps going, surprisingly without any further packets going back and forth between the machine the agent is started on and the proxy server. 

**also, suprisingly, i saw some packets being sent straight out to, circumventing the proxy:**

> 11:20:02.212982 IP ip-[..........].compute.internal.36646 > ec2-[external ip for rancher.foobar.com].compute.amazonaws.com.https:  ..... 

this seems to coincide with the wss:// connection attempts. does this not honor the proxy settings? i find it rather hard to believe that i'm the first one running into this, so i am assuming this is a mistake on my side. i'm just not clear how where and why.

**Comment by chrisbulgaria** [comment]
We have the same ...   did you manage to further troubleshoot this ? 
Thanks,
Chris

**Comment by rmalchow** [comment]
@chrisbulgaria nope, after realizing that this is probably something inside agent, we simply made the proxy transparent. this gives us the same level of control over outgoing traffic with none of the "will my client behave?" uncertainties

**Comment by chrisbulgaria** [comment]
Ok , thanks a lot , can’t unfortunately do that in my situation . Will further look into it .
Btw here is another one having the same issue :  #22750

**Comment by chrisbulgaria** [comment]
Yes , it’s this change https://github.com/rancher/remotedialer/commit/e82d4eeef0672d6e2923433e4ddc9cd6dc3a8fd1#commitcomment-36601573

Hope it can be fixed soon

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/24876
