### ISSUE TITLE
istio中流量控制问题

### ISSUE THREAD

**Issue by yuenwah** [rancher/rancher#24680]
*Describe your issue here*
用rancher部署了istio，配置了istio(gateway,vs,dr),但目前只有从网关进来的流量会遵循虚拟服务设定的权重，其它pod或者nginx-ingress对这个虚拟服务配置的规则无感，nginx-ingress绑定的k8s-svc,有个问题需要了解一下，因为没在网上找到，是只有istio网关进来的流量会匹配虚拟服务的规则吗

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`authenticated.project.dns.index`|

**Comment by loganhz** [comment]
It's vanilla Istio. You can check Istio docs. Please add `rancher2` to join Rancher WeChat group if you would like to ask question in Chinese.
