### ISSUE TITLE
BUG Release 2.3.3 makes vSphere driver hard to use : resource pools

### ISSUE THREAD

**Issue by Heiko-san** [rancher/rancher#24687]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

* create a new node-template using the GUI 
* have a look at the values provided in the dropdown

**Result:**

* depending on your vCenter setup you may not know what to choose, because you may get entries like ["Resources","Resources","Resources"]

**Other details that may be helpful:**

* in vSphere you actually don't have just a name for resource pools, but it is more something like a path :  /my-datacenter/host/my-cluster/Resources/my-resourcepool
* this leads to the "Resources" entry for each cluster you have
* for resource pools itself a more or less correct value is shown : "my-resourcepool"
* but even then consider you have many datacenters and/or clusters which may have resource pools of the same name 
* -> best thing would be to show the full path (I think maybe cleaning the static parts "host" & "Resources" may be safe)
* otherwise you will have to use browser's developer tools to see which entry you actually want to select

**hint for the actual "Resources" entries**

* they should stay but also get a useful entry (e.g. "/my-datacenter/host/my-cluster"), since using a cluster itself for resource pool is perfectly valid (and actually in use by us)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Comment by hsartoris-bard** [comment]
The same issue, already acknowledged: https://github.com/rancher/rancher/issues/24507
Related acknowledged issue: https://github.com/rancher/rancher/issues/24507

**Comment by Heiko-san** [comment]
ok, if the details I provided are taken care of (eg related to the cluster entries itself), then it is fine for me to track the issue in the other ticket and close this one
