### ISSUE TITLE
Specify Benchmark version on the UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24697]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Steps to reproduce (least amount of steps as possible):**
UI for https://github.com/rancher/rancher/issues/24562

**Comment by codyrancher** [comment]
@sowmyav27 @maggieliu 
What's the ask for this one? The API doesn't provide a list of valid versions so providing a dropdown with a default value isn't really reasonable and I don't think we should expose a required text field for this.

**Comment by sowmyav27** [comment]
As per discussion, API enhancement will be discussed next week 
cc: @leodotcloud @codyrancher

**Comment by sowmyav27** [comment]
**On master-head latest - ui tag: `latest2`**

- Navigate to cluster --> Tools --> CIS Scan --> Run Scan
<img width="1289" alt="Screen Shot 2020-03-06 at 9 37 09 PM" src="https://user-images.githubusercontent.com/26032343/76137753-39d35980-5ff5-11ea-9014-189d5aa595f4.png">

- Report also shows the benchmark version along with the profile
<img width="1311" alt="Screen Shot 2020-03-06 at 9 56 33 PM" src="https://user-images.githubusercontent.com/26032343/76137764-65564400-5ff5-11ea-87ab-71909a92f41d.png">
