### ISSUE TITLE
Vmware driver removes (!) attached PersistentVolumes while recreating worker nodes

### ISSUE THREAD

**Issue by AntonSmolkov** [rancher/rancher#24690]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Click  worker pool -> worker node -> chose options[...] -> Delete.

**Result:**
Rancher removes worker node and **ALL ATTACHED vmdks** with it, then rancher recreates worker node.
Persistent volumes still appear in Rancher UI, but deleted in Vmware. 
Vmware produces lot of error logs like - "Can't attach volume dows not exist. PATH"

**Other details that may be helpful:**
Expect Rancher to drain node before delete it, or at least, show warning.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher 2.3.3
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Infrastructure Provider - VMware Vspere 6.5, VSAN.
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM
- Kubernetes version (use `kubectl version`):
v1.16.3

- Docker version (use `docker version`):
19.3.4

gzrancher/rancher#8983

gzrancher/rancher#11020

gzrancher/rancher#12087

**Comment by stefanvangastel** [comment]
Experiencing same issue, this is highly unwanted!

**Comment by fredbeltrao** [comment]
To avoid that, node should be Drained with agressive mode before delete. From a dozen tests, I realize that when Rancher drains a node in agressive mode, the following events occurs (pehaps in a different order):
- volumes are carefully deattached from pods
- pods are excluded from the node
- pods are recreated on another node
- volumes are mounted in the new pods
- vmdks are preserved in vSphere

Scenario exaustively tested on Rancher 2.3.5 + vSphere 6.5

**Comment by stefanvangastel** [comment]
This however is still not the (desired) behaviour of the scale up/down nodes in nodepool functionality. 

If you scale nodes from a worker nodepool down, the behaviour @fredbeltrao describes should be triggerd **before** actually deleting the node.

**Comment by fredbeltrao** [comment]
@stefanvangastel Not only when scale down nodes in a nodepool, but also when deleting a specific node pro dropdown menu:
![](http://i.imgur.com/XH6sjqt.png)

**Comment by daneb255** [comment]
bump ... very critical bug !

**Comment by luthermonson** [comment]
Since https://github.com/rancher/rancher/issues/18221 was created first I'm going to track everything over there and close this as a duplicate.

**Comment by AntonSmolkov** [comment]
Issue is not reproducible with vSphere 6.7U3 + [out-of-tree cloud provider](https://rancher.com/blog/2020/stateful-kubernetes-workloads)

**Comment by luthermonson** [comment]
@AntonSmolkov correcft, also noted by Jan in the previous issue the out of tree provider has this https://github.com/vmware/vsphere-storage-for-kubernetes/issues/55#issuecomment-536084195
