### ISSUE TITLE
rancher istio 1.4.2 UI changes

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#24701]
To make istio 1.4.2 work in rancher, we need the follwing UI changes:

1. Change kiali link to be not hard-coded. This is due to the change that in istio 1.4.2 they changed kiali service name and port.
2. Change default answer pair to disable PodDisruptionBudget. This is to work around node draining issue for istio control plane. https://github.com/istio/istio/issues/12602. We should also add documentation so that if user is going to enable PodDisruptionBudget then they have to increase replicas numbers of istio control plane.

**Comment by StrongMonkey** [comment]
Noticed a kiali issue in UI:
We are trying to move nginx sidecar deployment for kiali, which causes some issue in UI.

> Go to Project -> Istio -> Traffic Gragh, The graph takes forever to load and under network tab it is giving 404.

I think accessing any subpath in kiali needs extra care as it tries to access subpath in kiali to get js files in order to serve those under rancher UI.  @westlywright

**Comment by rancher-max** [comment]
Looks good pending #24831

**Comment by rancher-max** [comment]
Working in 2.3-head and master-head commit ID: 3ae5ad9bd652. Changes here were available in latest-2.3 and latest2 ui-index.

Verified both previous istio versions and upgrade to new istio, as well as a fresh install using the new version on kubernetes v1.17
