### ISSUE TITLE
Health Check - Not able to start new containers when unhealthy instances are detected when service has exposed ports/scehduled with anti-affinity rules.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2470]
Server version - V0.43.1

Steps to reproduce the problem:
scenario 1:
Set up has 3 hosts.
Create a service with health check enabled and having 1 exposed port with scale 3.
Make one of the instances of the service unhealthy .
Service gets marked as "unhealthy".
There is an attempt made to start another instance , but it fails to find a placement.

scenario 2:
Set up has 3 hosts.
Create a service with health check enabled and having scheduling rules set to anti-affinty service to itself.
Make one of the instances of the service unhealthy .
Service gets marked as "unhealthy".
There is an attempt made to start another instance , but it fails to find a placement.

<img width="402" alt="screen shot 2015-10-28 at 2 50 45 pm" src="https://cloud.githubusercontent.com/assets/4266958/10808123/bf6ca7be-7da4-11e5-93f3-9fee3beb7085.png">

**Comment by alena1108** [comment]
thats a good one. We should relax port constraint for containers in unhealthy state.

**Comment by alena1108** [comment]
Shouldn't be an issue anymore as we delete unhealthy instances prior to creating their replicas now.

**Comment by sangeethah** [comment]
Tested with latest build from master.

Both the scenarios mentioned in the issues works as expected.
