### ISSUE TITLE
Upgrading rancher istio system chart to 1.4.2

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#24700]
Upgrading system-chart of istio to 1.4.2. 
Todo:

1. Adding 1.4.2 chart into system-chart.
2. Adding mirror images into rancher/rancher
3. Disable PodDisruptionBudget by default to get around with node draining issue.

QA:
1. Test if 1.4.2 is functional on fresh install
2. Test if user is able to upgrade from istio 1.3.3 to 1.4.2.

Current issue on UI:
1. Kiali link is hard-coded to use proxy link for certain service and port. We have to change UI to make link version diagnostic so it knows which service link to use according which istio version.
2. Custom questions and answers are hardcoded in UI. We have to change code in UI if we want to change default answer pairs.

**Comment by StrongMonkey** [comment]
UI issue https://github.com/rancher/rancher/issues/24701

**Comment by rancher-max** [comment]
Current Issues from QA:
1. Upgrade without force (delete/recreate resources).. This means that upgrading via Tools --> Istio won't work.
2. Kiali link not working means Traffic Graph does not work as well
3. There are no public endpoints now when enabling Istio v1.4.2 (with/without gateway enabled). We can hack this (at least for testing Gateway in current state) by setting a custom answer: `"gateways.istio-ingressgateway.labels.release": "cluster-istio"` which gives one public endpoint that works properly.

**Comment by rancher-max** [comment]
Current status using chart: https://github.com/StrongMonkey/system-charts.git and branch: istio-1.4.2 with ui-index: https://releases.rancher.com/ui/istio-upgrade-dev-v3/index.html
All 3 issues in the previous comment have been fixed.

Upgrade testing had one issue: Kiali and Jaeger links not showing up when enabling istio with all authenticated user and giving users Read Only access to System Project.

**Comment by rancher-max** [comment]
Above issue fixed now. First pass of the following all succeeded:

- fresh install
    - Execute P1 Workflow using Istio v1.4.2
- upgrade from v2.2.7
    - in v2.3.3, execute p1 workflow using Istio v1.3.3,
    - upgrade to v2.3.4
    - make sure existing istio workloads work (refer to p1 workflow)
    - Upgrade istio to v1.4.2
    - make sure existing istio workloads work (refer to p1 workflow)
    - Execute p1 workflow again in a new project/namespace
    - Execute p1 workflow in brand new cluster
- Drain Nodes with Istio v1.4.2

P1 workflow involves creating a versioned workload that is accessible using Gateway, Virtual Service, and Destination Rules. We also validate pods contain sidecars and metric tools are available.

@deniseschannon @sangeethah @StrongMonkey I believe the changes can be merged into the RC. Currently requires both System Charts from StrongMonkey/system-charts branch istio-1.4.2 and ui-index from istio-upgrade-dev-v3

**Comment by rancher-max** [comment]
Working in 2.3-head and master-head commit ID: 3ae5ad9bd652. Changes from here were available in system-charts dev branch.

Verified both previous istio versions and upgrade to new istio, as well as a fresh install using the new version on kubernetes v1.17
