### ISSUE TITLE
rancher local cluster updgrade failing 

### ISSUE THREAD

**Issue by richyta** [rancher/rancher#24717]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):***Result:***
rke up --config rancher-cluster.yml

**Other details that may be helpful:**
Trying to upgrade k8s on local rancher cluster node but getting warning error and k8s are not updated to the latest stable version provided by rke verison.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud/AWS, 4cores/15GB
- Kubernetes version (use `kubectl version`):

➜```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
18.9.4
```

```
<img width="1273" alt="Screen Shot 2019-12-17 at 10 52 08 AM" src="https://user-images.githubusercontent.com/39923752/71290042-a78bb580-2323-11ea-8ede-c1d650b0e769.png">
<img width="1273" alt="Screen Shot 2019-12-17 at 10 52 08 AM" src="https://user-images.githubusercontent.com/39923752/71290067-ba05ef00-2323-11ea-96fc-f960ee456720.png">
<img width="1232" alt="Screen Shot 2019-12-17 at 10 54 26 AM" src="https://user-images.githubusercontent.com/39923752/71290083-c722de00-2323-11ea-8f1f-4a496feed5fe.png">

**Comment by superseb** [comment]
Please reply to https://github.com/rancher/rke/issues/1836#issuecomment-567102236 with the actual error where the provisioning stops, there is no need to create a duplicate issue on the same subject.
