### ISSUE TITLE
helm install command for cert-manager is missing name parameter for helm2

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#24719]
Following the instructions here for upgrading cert-manager
https://staging.rancher.com/docs/rancher/v2.x/en/installation/options/upgrading-cert-manager/

 I tried copy/pasting the following command (Step 4 install the new version of cert-manager):

```bash
$ helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v0.12.0 
```

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Follow the steps in the documentation using helm version 2

**Result:**

```bash
$ helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v0.12.0
Error: This command needs 1 argument: chart name
```

**Other details that may be helpful:**

I was able to do the install with the following command parameters:

```bash
$ helm install \
  --name cert-manager \
  --namespace cert-manager \
  --version v0.12.0 \
  jetstack/cert-manager
```

```
helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.9
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):  HA in AWS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`):

```
 v1.15.5
```

**Comment by izaac** [comment]
I've opened an issue in rancher/docs instead: https://github.com/rancher/docs/issues/2116

**Comment by evalizhangli** [comment]
my helm version is 2.14.3, kubectl version is 1.15.5,   when i follow the doc guide run 
```
helm install \
  --name cert-manager \
  --namespace cert-manager \
  --version v0.13.1 \
  jetstack/cert-manager
```
It break for `Error: This command needs 1 argument: chart name
`
But I don't know why it's wrong?
