### ISSUE TITLE
Empty Amazone EC2 Config in Node Templates

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#24712]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
launch new rancher from master
create cloud credential for DO/vsphere
create node template with the credential
inspect node template in the api

**Result:**
the api will show have this `"amazonec2Config": null,` at the top of the template even though the template was for another cloud. some how the machine config code is adding a nil config for amazon ec2.

**Other details that may be helpful:**
this matters when you try and make changes to the node template via kubectl or api, it complains you can't have a nil amaconeec2Config and it's annoying to have to clear it all the time.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
master

- Installation option (single install/HA):
both

**Comment by pgdagenais** [comment]
I also hit this issue.

How to reproduce:

1. Create a nodetemplate using the interface.
2. Open the newly created nodetemplate in the `View in API`
3. See this at the top of the node template:
    ```
    {
    "amazonec2Config": null,
    ...
    ```


It also makes any editing of the node template breaks using the Kubernetes object themselves:
1. Edit a new nodetemplate: `kubectl edit nodetemplates.management.cattle.io -n cattle-global-nt nt-blhgc`
2. The file is open with this at the top:
    ```
    amazonec2Config: null
    ```

It is not possible to save the file itself if you do not remove the value, for example:
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# nodetemplates.management.cattle.io "nt-blhgc" was not valid:
# * : Invalid value: "The edited file failed validation": unknown object type "nil" in NodeTemplate.amazonec2Config
#
amazonec2Config: null
```

Once I remove `amazonec2Config: null` it is now possible to save the file.
