### ISSUE TITLE
CNI never "populated"(?): /etc/cni and /opt/cni empty, kubelet crashes

### ISSUE THREAD

**Issue by OrionsCore2** [rancher/rancher#24716]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1. Try to provision new 1.16 kubernetes cluster

**Result:**

Fails, CNI is never populated, kubelet crashes or something

**Other details that may be helpful:**

```
I1220 20:04:22.524588    7214 clientconn.go:577] ClientConn switching balancer to "pick_first"
I1220 20:04:22.524689    7214 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00028c2f0, CONNECTING
I1220 20:04:22.524718    7214 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc000433640, CONNECTING
I1220 20:04:22.525034    7214 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00028c2f0, READY
I1220 20:04:22.525177    7214 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc000433640, READY
W1220 20:04:27.498206    7214 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
W1220 20:04:32.498500    7214 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
W1220 20:04:37.498712    7214 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
W1220 20:04:42.499248    7214 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
```

Both /opt/cni and /etc/cni inside the kubelet container are completely empty.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.3
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`): cannot run

**Comment by lindhe** [comment]
@OrionsCore2 I'm battling the same problem. Did you find a solution?
