### ISSUE TITLE
how to get image-list from rancher

### ISSUE THREAD

**Issue by kakablue2019** [rancher/rancher#24711]
Is there any API or function to get image-list from Rancher's local registry?

**Comment by huangwei2013** [comment]
same question.
Expecting answer, pls

**Comment by superseb** [comment]
Are you looking for the info from https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/populate-private-registry/ or that info from the API? What do you mean by `from Rancher's local registry?`

**Comment by huangwei2013** [comment]
@superseb   thx for reply.  I mean do this by API.

PS： 
 - I check code of "rancher/rancher" but found nothing useful
 - I run rancher and fiddler, but found that Rancher get image-list from "workload", it looks strange...

**Comment by superseb** [comment]
I think you are looking for `https://localhost/v3/kontainerdrivers/rancher-images` but I am not sure, please let us know what you expect as output so there is a better idea on the use-case.
