### ISSUE TITLE
Cannot change NodePort values in UI

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#24724]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Flow 1:
1. Tools --> Istio or 
2. Expand "Ingress Gateway" and try to change the http2 and https ports.
Flow 2:
1. Workloads --> Deploy
2. Add Port, as a NodePort
3. Click "Random" and type any value

**Result:**
It uses the min/max values of the input field no matter what is typed (30000 or 32767) and cannot clear the field.

**Other details that may be helpful:**
Potential Workaround: should be able to enable w/ some value and then edit the istio app via api to change the port in the answers
Note that with UI Index https://releases.rancher.com/ui/2.3.26/index.html it allows clearing the field.

Example from deploying workload:
![image](https://user-images.githubusercontent.com/55997940/71297259-fc3d2980-233f-11ea-925b-79a0b058234d.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
master-head
UI Index: https://releases.rancher.com/ui/latest2/index.html
- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 
rke ec2: 1 t2.medium etcd + cp and 3 t2.xlarge workers
- Kubernetes version (use `kubectl version`):

```
1.16.3
```

- Docker version (use `docker version`):

```
1.10.3
```

**Comment by Noctalin** [comment]
Does it affect only "Edit Workload" or also Services from "Service Discovery" menu?

**Comment by rancher-max** [comment]
Good call out, it does **not** happen in the Service Discovery menu. It also looks like the min value of the field there is 1 instead of 30000.

**Comment by rancher-max** [comment]
#### Fixed in master-head commit id: `8bd9f3be2` using ui-index `https://releases.rancher.com/ui/latest2/index.html`

Can edit NodePort values on both Workload creation and Tools > Istio.
