### ISSUE TITLE
Skipped test in downloaded report is missing list of nodes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24725]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Download a CIS Scan report (make sure a test is skipped in the scan report)

**Expected Result:**
The skipped test should have the nodes column populated with apt nodes.

**Actual Result:**
The skipped test is missing the list of applicable "nodes" column

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master head - commit id: `656781c34`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.15
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by codyrancher** [comment]
This isn't a bug. The test wasn't run on the nodes.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `b3bc13a88` ui tag: `latest2`**

**Steps:**

- Download a CIS Scan report (make sure a test is skipped in the scan report)
- The skipped test has the nodes column populated with apt nodes.
