### ISSUE TITLE
Add Host AWS EC2 Account Access XMLParserError

### ISSUE THREAD

**Issue by stemau98** [rancher/rancher#2472]
When entering the Account Access keys following error occures:
XMLParserError: s.getElementsByTagName(...)[0] is undefined

Component 	Version
Rancher 	v0.42.0
Cattle 	v0.102.0
User Interface 	v0.57.0
Rancher Compose 	v0.4.3

**Comment by deniseschannon** [comment]
I have been unable to reproduce this issue. I tried with a v0.42.0 build. 

Are you still getting this issue?

**Comment by stemau98** [comment]
I have tried a second time with the latest image of the rancher server but I still get the same error:
XMLParserError: s.getElementsByTagName(...)[0] is undefined

Im running rancher in a vm with centos 7.1 and tested a local running server and agent on this machine. This worked fine for me but with AWS i'm getting the errot above.

**Comment by vincent99** [comment]
That probably means the response the AWS client is getting is JSON or other text instead of the XML it's expecting.. can you open up the browser developer tools' network tab and see what the request and response are that are failing?

**Comment by stemau98** [comment]
I think that something was wrong with my Access Key. After creating a new one there was no error. 
Thanks for help!
