### ISSUE TITLE
Ingress Status is always showing initializing

### ISSUE THREAD

**Issue by travisgu** [rancher/rancher#24737]
Rancher version: 2.2.8
All the Ingress load balancer status are **Initializing**. But there is no error in the log of ingress controller and the entries are correctly configured in the nginx.conf in the ingress controller pod. The entries are also functioning well. 
Can anyone advise why it is still in the **Initializing** State?

![image](https://user-images.githubusercontent.com/10804665/71340990-7e715c00-2593-11ea-81e7-44917545b079.png)

**Comment by dbrw** [comment]
Is there no update for this?

**Comment by travisgu** [comment]
> Is there no update for this?

no update

**Comment by dbrw** [comment]
I tried to disable and re-enable the nginx but still no luck.

**Comment by jinzishuai** [comment]
having the same problem with v2.4.7
