### ISSUE TITLE
Security Scan reports have a node's name to identify the nodes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24734]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Create an rke cluster with 1 node pool - etcd and control plane, 1 nodepool - worker node (2 nodes cluster)
2. In an RKE cluster, run scans. 
3. Report is generated. Go to the scan details page by clicking on the report.
4. The tests are linked to the nodes by the node name
5. Go to cluster --> Nodes --> Delete the worker node.
6. A worker node will get re provisioned. 
7. Go to the report in Step 3. And click on a test run on all nodes.
8. The test reports the new worker node as Pass/fail. 
9. On clicking on the node, it takes the user to the new worker node.

**Expected Result:**
The old reports should not link to the new nodes.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke
- Kubernetes version (use `kubectl version`):

```
1.15
```

**Comment by deniseschannon** [comment]
@codyrancher After re-reading this and with how Rancher handles adding new nodes in a node pool, can we remove the link to the node name and maybe add in parenthesis, what the node ID is?

**Comment by codyrancher** [comment]
I'll be removing the link and leaving the name. The node id isn't stored in the report so I can't display that.

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/09/2020)` commit id: 17bd84f8d

The node name text is persisting in the CIS Scan reports details, but there's no longer a link that would redirect to the node. This prevents linking to new nodes

**Comment by codyrancher** [comment]
@izaac  That's intentional per my earlier comment.

> I'll be removing the link and leaving the name. The node id isn't stored in the report so I can't display that.
