### ISSUE TITLE
PVC resize not possible in rancher 2.x

### ISSUE THREAD

**Issue by pirminjanka** [rancher/rancher#24741]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancment / bug

**Steps to reproduce (least amount of steps as possible):**

- Click on persistent volume claim on rancher 2.3.x
- There is no possibility to edit the pvc (instead the volume can be edited and resized but this has no effect on f.e. a netapp trident storage class)

The same works with kubectl:

```
kubectl edit pvc <pvc> -n <namespace>
persistentvolumeclaim/<pvc> edited
```

```
kubectl get pvc <pvc> -n <namespace>
NAME           STATUS   VOLUME                   CAPACITY   ACCESS MODES   STORAGECLASS         AGE
<pcc>   Bound    <volume>   <new size>       RWX            netapp-filestorage   <age>
```

**Result:**
Edit Button missing on PVC Settings Page

**Other details that may be helpful:**

**Environment information**
- Rancher v2.3.2
- Installation option Single HA
- Storage Class NetApp Trident

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): OnPrem Installation
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):

```
1.15.5
```

- Docker version (use `docker version`):

```
18.9.7
```

**Comment by gittygoo** [comment]
Having this exact same problem, how was this issue closed without anyone even looking at it ?
