### ISSUE TITLE
Container details page should show container ID

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2474]
It would be really useful to be able to see the container's ID (e.g. 2db5c9d3a544) on its details page. This would make it easier to work with Rancher-created containers on the command-line.

**Comment by deniseschannon** [comment]
@vincent99 Is this currently supported in the API? Or would we need to add it there first?

**Comment by vincent99** [comment]
@deniseschannon it should be the `externalId` field on container resources.

**Comment by cjellick** [comment]
+1
Also, put it on the container lists page

**Comment by vincent99** [comment]
(not on the lists)

**Comment by tfiduccia** [comment]
version - master UI 3/3
Verified added

**Comment by cjellick** [comment]
:sunglasses:
