### ISSUE TITLE
allow building rancher image with a custom metadata branch 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#24743]
Currently, the branch for `kontainer-driver-metadata` on startup gets decided dynamically based on rancher server image tag. For certain purposes (like preview, test, etc), we need a way to pass a custom branch while building the image. 

For test, 
- change ARG `RANCHER_METADATA_BRANCH` in Dockerfile and build the image 
- run the image and ensure `v3/settings/rke-metadata-config` reflects the correct branch

**Comment by jiaqiluo** [comment]
Validated with the lastest Rancher master branch c1c0f7f1d0d8f122d66c1951abfc53bc7cce5dfc, clone the repo and build the image locally.

Validation 1: build without changing the ARG RANCHER_METADATA_BRANCH 
Result: run the rancher images locally and notice the `v3/settings/rke-metadata-config` uses the default `dev` branch 

Validation 2: build without changing the value of ARG RANCHER_METADATA_BRANCH to `test-branch` 
Result: run the rancher images locally and notice the `v3/settings/rke-metadata-config` uses the `test-branch` branch 

<img width="1453" alt="Screen Shot 2020-01-20 at 3 18 41 PM" src="https://user-images.githubusercontent.com/6218999/72761794-5d078e00-3b9a-11ea-8580-b308f5744cab.png">
