### ISSUE TITLE
Search field on CIS Scan details page is missing a clear icon

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24750]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster
- Navigate to Tools --> CIS Scans
- Run Scans.
- CLick on the scans to go to the scan details page

**Expected Result:**
Search field should have the "clear" --> "X" icon to clear the text in the search box.
As in the case of the search field on the CIS Scans page

**Actual Result:**
Search field on CIS Scan details page is missing a clear icon

**CIS Scans page:**
<img width="1447" alt="Screen Shot 2019-12-23 at 1 50 09 PM" src="https://user-images.githubusercontent.com/26032343/71382184-ac52a280-258b-11ea-9898-cf503b1b2a16.png">

**Scan Details page:**
<img width="1451" alt="Screen Shot 2019-12-23 at 1 50 22 PM" src="https://user-images.githubusercontent.com/26032343/71382192-b2488380-258b-11ea-840e-f152374bc283.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest commit id: `d9ca7c7b6`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom/rke DO
- Kubernetes version (use `kubectl version`):

```
1.15
```

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `b3bc13a88` ui tag: latest2**

**Steps:**

- Deploy a cluster
- Navigate to Tools --> CIS Scans
- Run Scans.
- Click on the scans to go to the scan details page
- Search field has the "clear" --> "X" icon to clear the text in the search box.
<img width="1140" alt="Screen Shot 2020-01-20 at 11 12 39 PM" src="https://user-images.githubusercontent.com/26032343/72783108-792b1f80-3bda-11ea-8c65-84a937f42c83.png">

**Comment by binarymist** [comment]
How do you see the CIS Scans option

![Capture](https://user-images.githubusercontent.com/2862029/73625227-ca421580-46a8-11ea-8ef6-b6c1de9bb14e.PNG)

**Comment by sowmyav27** [comment]
@binarymist The CIS scan is available on the UI only in `rancher:v2.4.0-alpha1`
