### ISSUE TITLE
Error seen while navigating to CIS Scans page when the cluster is in Provisioning state

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24755]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy a cluster.
2. While the cluster is in Provisioning state, Navigate to Cluster --> Tools --> CIS Scans

**Error seen on the UI:**

<img width="641" alt="Screen Shot 2019-12-23 at 9 16 32 PM" src="https://user-images.githubusercontent.com/26032343/71395542-3ec66680-25cb-11ea-874e-c7f0ce893b6d.png">

From the API, when the cluster is Provisioning, when a User performs action "runSecurityScan", error seen:
```
{
"baseType": "error",
"code": "ClusterUnavailable",
"message": "cluster not ready",
"status": 503,
"type": "error"
}
```

**Expected Result:**
From the API, the action "runSecurityScan" be disabled until the cluster is Active.

UI be able to handle the navigation to CIS Scans page like other page navigations while the cluster is in provisioning state

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.0-alpha1
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke/custom
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by sowmyav27** [comment]
**Verified on latest master-head - commit id: `47bf996c2`.**

- When a cluster is in provisioning state, the action "runSecurityScan" is seen disabled.

- But when the user navigates to Cluster --> Global --> Tools --> CIS Scans , User is presented with this error on the UI

<img width="594" alt="Screen Shot 2020-01-23 at 12 55 18 PM" src="https://user-images.githubusercontent.com/26032343/73024260-17d59d00-3de2-11ea-857f-fca173ea54d1.png">

**Comment by leodotcloud** [comment]
@codyrancher I have disabled the action from the backend. Can you please look into the UI aspect of this?

**Comment by codyrancher** [comment]
@sowmyav27 is this still an issue that you see? If so, what type of cluster are you creating and with what settings? Do you have to wait for the cluster to be in a specific stage?

This is what I see when I have a cluster provisioning in the latest.
![Screen Shot 2020-03-06 at 4 56 44 PM](https://user-images.githubusercontent.com/55104481/76131429-a33e7280-5fcb-11ea-8293-c42ab8633122.png)

**Comment by sowmyav27** [comment]
**On master-head ui tag: `latest2`**

While a cluster is in provisioning state, User can access CIS Scan page from Tools.
<img width="1225" alt="Screen Shot 2020-03-06 at 9 45 31 PM" src="https://user-images.githubusercontent.com/26032343/76137728-f4af2780-5ff4-11ea-8510-5c6c3b7b3ce4.png">
