### ISSUE TITLE
boot2docker.iso file persists in vSphere datastore after deletion of node in Rancher v2.3.3

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#24758]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a simple all-role single-node vSphere provider cluster in Rancher v2.3.3.
2. After provisioning is complete, delete the cluster in Rancher.
3. Observe after the VM has been successfully deleted in vSphere that the boot2docker.iso file persists in the directory for the VM within the datastore.

**Result:**

The boot2docker.iso file is not deleted for vSphere nodes in Rancher v2.3.3, where this was previously cleaned-up on node deletion testing in Rancher v2.2.9 and v2.3.2.

**Other details that may be helpful:**
- Reproduced testing v2.3.3 versus correct deletion in v2.2.9 and v2.3.2.

**Environment information**
- Rancher v2.3.3

**Comment by char-iot** [comment]
BUG noted and solved. Workaround for now: https://github.com/rancher/rancher/issues/24315#issuecomment-564173340

**Comment by janeczku** [comment]
Bug was reproduced in v2.3.4. The following additional related bugs were observed:

1) When using the clone from VM/template method while not specifying a custom cloud-config then the user-data.iso is never deleted from datastore upon deletion of nodes.
2) When using the boot2docker legacy method while not specifying a custom Cloud Init URL a user-data.iso is uploaded and attached to the VM and not removed upon deletion of nodes.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head dad58367e

* Reproduced in v2.3.4
* `boot2docker.iso` and `userdata.iso` left remaining when creating a cluster from legacy b2d and cloning from an existing machine without a custom cloud-config
* Deployed `rancher/rancher:master-head`
* Created 2 clusters (b2d & clone from existing)
* Clusters provisioned
* Deleted clusters and all files were removed
