### ISSUE TITLE
Has been pending since import

### ISSUE THREAD

**Issue by huyifanstar** [rancher/rancher#24757]
*Describe your issue here*
Kubernetes initialized by rke 
Docker Version: 18.09.2
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.7` UI: `v2.2.93` |
|Route|`authenticated.cluster.monitoring.index`|
![image](https://user-images.githubusercontent.com/15685376/71408311-aedef600-2678-11ea-8e5d-ed2736792291.png)
![image](https://user-images.githubusercontent.com/15685376/71408421-1f861280-2679-11ea-9840-872e64606076.png)
![image](https://user-images.githubusercontent.com/15685376/71408429-290f7a80-2679-11ea-9904-825419e749d6.png)

**Comment by superseb** [comment]
Please use https://rancher.com/docs/rancher/v2.x/en/troubleshooting/imported-clusters/ and provide the logs. Also, which versions you used of RKE and what k8s version.

**Comment by huyifanstar** [comment]
![image](https://user-images.githubusercontent.com/15685376/71530569-49636180-2925-11ea-8d10-38126c2df349.png)

**Comment by huyifanstar** [comment]
The rancher https certificate and the cluster certificate are not the same, the cluster is initialized by rke

**Comment by huyifanstar** [comment]
rke Version: 0.28
docker version: 18.09.2
kubernetes version: v1.14.6-rancher1-1
ubuntu version: 18.04

**Comment by superseb** [comment]
We need to know how you installed Rancher (single install or HA) and what command(s) you used to install Rancher. The configured certificates for Rancher are not correct it seems.

**Comment by huyifanstar** [comment]
docker run -d --restart=unless-stopped   -p 80:80 -p 443:443   -v /etc/rancher/ssl/rancher.crt.pem:/etc/rancher/ssl/cert.pem   -v /etc/rancher/ssl/rancher.key.pem:/etc/rancher/ssl/key.pem   -v /data/rancher:/var/lib/rancher  rancher/rancher:v2.2.8  --no-cacerts

https is free to apply (1 year)，I don't know what will happen

**Comment by superseb** [comment]
`--no-cacerts` means that the CA is recognized and does not need any intermediate certificates in the chain. What CA is used in this case?

**Comment by huyifanstar** [comment]
Configure Rancher to https，Why do I get an error？

**Comment by superseb** [comment]
You need to provide the CA by mounting `cacerts.pem` into the container or by providing `--no-cacerts`, this depends on what CA you are using (recognized or self signed), see option B and option C on https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node/.

Having a recognized CA means that you can use `--no-cacerts` but doesn't necessarily mean that you only have to provide one certificate for the server certificate (`/etc/rancher/ssl/cert.pem`). Most recognized CA's use intermediate certificates which need to be provided in the server certificate, you can check this by searching for `YOUR_CA_NAME intermediates` and make sure they are included in the server certificate.

In v2.3.2, we added additional logging in the agent to help you diagnose SSL issues.

**Comment by huyifanstar** [comment]
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -v /etc/rancher/ssl/rancher.crt.pem:/etc/rancher/ssl/cert.pem -v /etc/rancher/ssl/rancher.key.pem:/etc/rancher/ssl/key.pem -v /data/rancher:/var/lib/rancher rancher/rancher:v2.3.2 --no-cacerts

![image](https://user-images.githubusercontent.com/15685376/71580353-3924cf80-2b3b-11ea-9b29-23d3781d4e8a.png)

**Comment by superseb** [comment]
Please share the output of:

```
openssl x509 -in /etc/rancher/ssl/rancher.crt.pem -noout -issuer
cat /etc/rancher/ssl/rancher.crt.pem | grep BEGIN | wc -l
```

**Comment by huyifanstar** [comment]
root@k8s-Master:/etc/rancher/ssl# openssl x509 -in /etc/rancher/ssl/rancher_crt.pem  -noout -issuer 
issuer=C = CN, O = "TrustAsia Technologies, Inc.", OU = Domain Validated SSL, CN = TrustAsia TLS RSA CA




root@k8s-Master:/etc/rancher/ssl# cat /etc/rancher/ssl/rancher_crt.pem | grep BEGIN | wc -l
1

**Comment by huyifanstar** [comment]
What should I do now?

**Comment by superseb** [comment]
The certificate related error is due to an incomplete certificate chain, I tested it using freessl.cn and it only works when you use the provided `full_chain.pem` as `/etc/rancher/ssl/cert.pem`. There should be 2 certificates in that file.

The error you reference in the last post, is moved to a different log level, see for more info: https://github.com/rancher/rancher/issues/23957

Let me know if using the correct certificate file does not solve your issue.

**Comment by huyifanstar** [comment]
key，crtConvert to pem
What will happen?
Don't support non-pem certificates

**Comment by superseb** [comment]
The bundle that I received from `freessl.cn` (TrustAsia) contains:

`full_chain.pem` and `private.key`, `full_chain.pem` can be used as `/etc/rancher/ssl/cert.pem` and `private.key` goes to `/etc/rancher/ssl/key.pem`. As its a recognized CA, you can use `--no-cacerts` at the end of the command.

**Comment by huyifanstar** [comment]
How about not using https and using only http？Is there any problem？

**Comment by superseb** [comment]
You will need https, why is it not possible to use the certificates you have? As I don't think there is a bug here, I will close this issue.

If you need help with the certificates, please ping me on Slack (https://slack.rancher.io) and I can help you set it up.

**Comment by huyifanstar** [comment]
@superseb    But it is still pending
