### ISSUE TITLE
Host disk space monitoring

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2476]
I just ran into a situation where some of my Docker hosts ran out of disk space. This broke Rancher's ability to manage the host pretty thoroughly: containers were getting stuck in various stopping/starting states, even after I managed to recover some disk space. I think the Rancher agent's volume was somehow remounted as read-only -- some very weird stuff was going on.

I had to use some pretty drastic measures to recover the host:

1. Manually remove all containers and their volumes using the command-line.
1. Remove and Purge the host in Rancher.
1. Stop Docker.
1. `rm -rf /var/lib/docker` (to free up disk space because Docker's volume management sucks)
1. `rm -rf /var/lib/rancher` (to remove the old rancher agent data)
1. Start Docker
1. Re-create the Rancher Agent to register the host.
1. Redeploy my images and containers.

it would be useful if Rancher monitored the free disk space on hosts and provided warning when it drops below a threshold.

**Comment by Rucknar** [comment]
You could indeed ask rancher to monitor the hosts, however i feel this would only cover one such possible event you might want monitoring. 

In my opinion, you should monitor the container hosts as you would any normal server and feed them into either your monitoring solution, that way you can handle trending and alerting without rancher having to try be all things so early on.

**Comment by gordontyler** [comment]
Rancher claims to "monitor host metrics" and I would argue that free disk space is one of those metrics that should be monitored since it has such a significant impact on the ability of the host to operate.

**Comment by Rucknar** [comment]
True, but monitoring isn't the same as alerting. I can view CPU metrics for the host, unless i look into that data there isn't a threshold mechanism or alerting mechanism for when this value changes. 

Check out https://github.com/chadoe/docker-cleanup-volumes - should handle some of those steps you ran into with the disk filling. We've had to run this on our hosts a few times, although i've not seen docker its-self lock up.

**Comment by gordontyler** [comment]
You make a valid point. Rancher has no alerting or thresholding mechanism currently.

I've started using https://github.com/cloudnautique/vol-cleanup. The problem wasn't with Docker itself, but Rancher couldn't stay in sync with the containers on that host.

**Comment by cusspvz** [comment]
+1

**Comment by helvalius** [comment]
+1, it would be really helpful to have Rancher clean up unused docker images periodically.

**Comment by sshipway** [comment]
@helvalius  I have a catalog item 'janitor' at https://github.com/sshipway/rancher-catalogue.git that can do the periodic cleanup, based on meltwater/docker-cleanup

**Comment by deniseschannon** [comment]
Closing in favor of #1542
