### ISSUE TITLE
UX: On narrow screens error notifications after pressing buttons cannot be seen

### ISSUE THREAD

**Issue by dopry** [rancher/rancher#2477]
Working on the Add Host screen on a narrow screen when I press the create button. I don't see anything happen. I scrolled up an saw the notice. I would be nice if notices were always visible when the user is interacting with the screen.

http://screencast.com/t/ZPuSdxKkjXq7

**Comment by vincent99** [comment]
These are mostly moved next to the save/create/add buttons now.
