### ISSUE TITLE
Incorrect image in rancher-images.txt for the 2.4.0-alpha1 release

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24774]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
in the rancher-images.txt file in v2.4.0-alpha1
`https://github.com/rancher/rancher/releases/tag/v2.4.0-alpha1` incorrect image.

**Actual:**
`rancher/nginx-ingress-controller-:1.5-rancher1`

**Expected:**
`rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  v2.4.0-alpha1

**Comment by superseb** [comment]
Fix for this is in https://github.com/rancher/types/pull/1068/commits/c9a50144a27e03b2f45bd34c6a9e69e2af017d72

**Comment by rancher-max** [comment]
Validated using the correct image in v2.4.0-rc1 airgap setup:

![image](https://user-images.githubusercontent.com/55997940/75467302-ae006400-5948-11ea-8227-09ff9e81dce2.png)

Imported a custom large single node cluster that has all 3 roles and left other options default to retrieve nginx-ingress. Also validated when pulling images.txt and saving the images that it was using this correct image: `rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1`
