### ISSUE TITLE
[question] How do rancher distribute service instances across hosts?

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2478]
How do rancher distribute service instances across hosts? How can i configure my rancher to keep by 2 instances of some-service on 3 hosts with total scale=6? What happens in Cattle if one of hosts goes down and i bring new host with rancher agent after? Cannot find this details in rancher docs... I used AWS ECS and know it handles this situations pretty well, what about Rancher?

**Comment by Rucknar** [comment]
@ndelitski try adding the following label:
```
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=stack_name/service_name
```

**Comment by mishak87** [comment]
You can use variables which will be replaced when scheduling the container:
```yaml
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    # $${var} -> libcompose -> ${var} -> rancher cattle -> value
```

**Comment by ndelitski** [comment]
@Rucknar @mishak87 thx! It works but what do you think about fail scenario when hosts are terminated by any reason and i have to launch new ones(think of it as an autoscaling group). That time I have no healthy services(or < than it should be) but Rancher refuse deploying to a new healthy host, until i rescale service manually. Why Rancher still counting service instances on unhealthy hosts? I expect that scheduler should have top priority to keep services in running state(also in a given scale) whenever possible like ECS does... From my point, it should deploy service to a new host, and when old host goes up - stop extra instances, not the opposite.

**Comment by deniseschannon** [comment]
@ndelitski In order for a service to maintain, it's scale, you'll need to enable a health check on the service. Without a health check, if a host goes down, then nothing gets re-scheduled until the host is removed from Rancher. At that point, the service would be re-scheduled.
