### ISSUE TITLE
invalid configuration: cgroup-root [] doesn't exist]

### ISSUE THREAD

**Issue by djq8888** [rancher/rancher#24788]
*Describe your issue here*

[workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [172.21.0.16]: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused, log: F1229 05:00:59.545168 13885 server.go:271] failed to run Kubelet: invalid configuration: cgroup-root [] doesn't exist]

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`authenticated.cluster.nodes.index`|

**Comment by TechnusOK** [comment]
+1, did you managed to fix the issue?

**Comment by liyanone** [comment]
any update on this issue?

**Comment by xingxing122** [comment]
Has this problem been solved, I also encountered this problem, it is in ubuntu 16.04

**Comment by wongchao** [comment]
apt upgrade
