### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by OPSTime** [rancher/rancher#24798]
**version:**
```
kubernetes: 1.16.4
rancher：2.3.3
```

 **kubectl logs  cattle-cluster-agent-7584b65485-rh7h2 -n cattle-system**
**kubectl logs  cattle-node-agent-2wd7w -n cattle-system**
```
INFO: https://rancher.bayuegua.com:31313/ping is accessible
INFO: rancher.bayuegua.com resolves to 192.168.1.211
INFO: Value from https://rancher.bayuegua.com:31313/v3/settings/cacerts is an x509 certificate
time="2019-12-31T12:58:24Z" level=info msg="Rancher agent version v2.3.3 is starting"
time="2019-12-31T12:58:24Z" level=info msg="Listening on /tmp/log.sock"
time="2019-12-31T12:58:24Z" level=info msg="Certificate details from https://rancher.bayuegua.com:31313"
time="2019-12-31T12:58:24Z" level=info msg="Certificate #0 (https://rancher.bayuegua.com:31313)"
time="2019-12-31T12:58:24Z" level=info msg="Subject: CN=rancher.bayuegua.com,O=the-ranch"
time="2019-12-31T12:58:24Z" level=info msg="Issuer: CN=cattle-ca,O=the-ranch"
time="2019-12-31T12:58:24Z" level=info msg="IsCA: false"
time="2019-12-31T12:58:24Z" level=info msg="DNS Names: [rancher.bayuegua.com]"
time="2019-12-31T12:58:24Z" level=info msg="IPAddresses: <none>"
time="2019-12-31T12:58:24Z" level=info msg="NotBefore: 2019-12-31 12:27:59 +0000 UTC"
time="2019-12-31T12:58:24Z" level=info msg="NotAfter: 2020-12-30 12:49:20 +0000 UTC"
time="2019-12-31T12:58:24Z" level=info msg="SignatureAlgorithm: SHA256-RSA"
time="2019-12-31T12:58:24Z" level=info msg="PublicKeyAlgorithm: RSA"
time="2019-12-31T12:58:24Z" level=info msg="Certificate details for /etc/kubernetes/ssl/certs/serverca"
time="2019-12-31T12:58:24Z" level=info msg="Certificate #0 (/etc/kubernetes/ssl/certs/serverca)"
time="2019-12-31T12:58:24Z" level=info msg="Subject: CN=cattle-ca,C=CN"
time="2019-12-31T12:58:24Z" level=info msg="Issuer: CN=cattle-ca,C=CN"
time="2019-12-31T12:58:24Z" level=info msg="IsCA: true"
time="2019-12-31T12:58:24Z" level=info msg="DNS Names: <none>"
time="2019-12-31T12:58:24Z" level=info msg="IPAddresses: <none>"
time="2019-12-31T12:58:24Z" level=info msg="NotBefore: 2019-12-30 08:46:56 +0000 UTC"
time="2019-12-31T12:58:24Z" level=info msg="NotAfter: 2029-12-27 08:46:56 +0000 UTC"
time="2019-12-31T12:58:24Z" level=info msg="SignatureAlgorithm: SHA256-RSA"
time="2019-12-31T12:58:24Z" level=info msg="PublicKeyAlgorithm: RSA"
time="2019-12-31T12:58:24Z" level=error msg="Issuer of last certificate found in chain (CN=cattle-ca,O=the-ranch) does not match with CA certificate Issuer (CN=cattle-ca,C=CN). Please check if the configured server certificate contains all needed intermediate certificates and make sure they are in the correct order (server certificate first, intermediates after)"
time="2019-12-31T12:58:24Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get https://rancher.bayuegua.com:31313: x509: certificate signed by unknown authority"
```

**kubectl get pods -n cattle-system**                     
```
NAME                                    READY   STATUS             RESTARTS   AGE
cattle-cluster-agent-7584b65485-rh7h2   0/1     CrashLoopBackOff   7          15m
cattle-node-agent-2wd7w                 0/1     CrashLoopBackOff   7          15m
cattle-node-agent-9pc9x                 0/1     CrashLoopBackOff   7          15m
cattle-node-agent-hgzxz                 0/1     CrashLoopBackOff   7          15m
rancher-64994bf7bd-vggxb                1/1     Running            3          20m

```

**Comment by 2vcps** [comment]
I was getting the same error and noticed the issuer-letsEncrypt.yaml or issuer-rancher.yaml for both the stable and latest helm charts are using apiVersion that do not work (at least on 1.16.3)

helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
I can't find where to try to do a pull request on the official chart, but I found in the path everything looks fixed here:
https://github.com/rancher/rancher/tree/master/chart
But that doesn't look to be linked to the chart repo used by the Rancher HA instructions.
https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/

Not sure if my error is exactly the same but changing to this ingress and issuers fixed the "CrashLoopBackOff" for the cluster-agent and node-agent for me.

**Comment by godliness** [comment]
I meet the same issue:

INFO: Environment: CATTLE_ADDRESS=172.16.32.3 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=k8s-node-vm6fqz-77jtilv0tc CATTLE_SERVER=https://rancher.jd.local:1443
INFO: Using resolv.conf: nameserver 172.16.56.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5
INFO: https://rancher.jd.local:1443/ping is accessible
INFO: rancher.jd.local resolves to 172.16.48.17
time="2020-03-31T07:50:05Z" level=info msg="Rancher agent version v2.3.5 is starting"
time="2020-03-31T07:50:05Z" level=info msg="Option etcd=false"
time="2020-03-31T07:50:05Z" level=info msg="Option controlPlane=false"
time="2020-03-31T07:50:05Z" level=info msg="Option worker=false"
time="2020-03-31T07:50:05Z" level=info msg="Option requestedHostname=k8s-node-vm6fqz-77jtilv0tc"
time="2020-03-31T07:50:05Z" level=info msg="Option customConfig=map[address:172.16.32.3 internalAddress: label:map[] roles:[] taints:[]]"
time="2020-03-31T07:50:05Z" level=info msg="Listening on /tmp/log.sock"
time="2020-03-31T07:50:05Z" level=info msg="Certificate details from https://rancher.jd.local:1443"
time="2020-03-31T07:50:05Z" level=info msg="Certificate #0 (https://rancher.jd.local:1443)"
time="2020-03-31T07:50:05Z" level=info msg="Subject: O=cert-manager"
time="2020-03-31T07:50:05Z" level=info msg="Issuer: CN=cattle-ca,O=the-ranch"
time="2020-03-31T07:50:05Z" level=info msg="IsCA: false"
time="2020-03-31T07:50:05Z" level=info msg="DNS Names: [rancher.jd.local]"
time="2020-03-31T07:50:05Z" level=info msg="IPAddresses: <none>"
time="2020-03-31T07:50:05Z" level=info msg="NotBefore: 2020-03-30 11:28:14 +0000 UTC"
time="2020-03-31T07:50:05Z" level=info msg="NotAfter: 2020-06-28 11:28:14 +0000 UTC"
time="2020-03-31T07:50:05Z" level=info msg="SignatureAlgorithm: SHA256-RSA"
time="2020-03-31T07:50:05Z" level=info msg="PublicKeyAlgorithm: RSA"
time="2020-03-31T07:50:05Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get https://rancher.jd.local:1443: x509: certificate signed by unknown authority"

**Comment by harikrishnamopuri** [comment]
I am facing same issue
time="2020-04-28T11:18:19Z" level=info msg="Option controlPlane=false"
time="2020-04-28T11:18:19Z" level=info msg="Option worker=false"
time="2020-04-28T11:18:19Z" level=info msg="Option requestedHostname=gke-hari-atom-dev-us-eas-default-pool-eee3ef4a-kmrg"
time="2020-04-28T11:18:19Z" level=info msg="Listening on /tmp/log.sock"
time="2020-04-28T11:18:19Z" level=info msg="Certificate details from https://rancher.texttospeech.xyz"
time="2020-04-28T11:18:19Z" level=info msg="Certificate #0 (https://rancher.texttospeech.xyz)"
time="2020-04-28T11:18:19Z" level=info msg="Subject: O=cert-manager"
time="2020-04-28T11:18:19Z" level=info msg="Issuer: CN=cattle-ca,O=the-ranch"
time="2020-04-28T11:18:19Z" level=info msg="IsCA: false"
time="2020-04-28T11:18:19Z" level=info msg="DNS Names: [rancher.texttospeech.xyz]"
time="2020-04-28T11:18:19Z" level=info msg="IPAddresses: <none>"
time="2020-04-28T11:18:19Z" level=info msg="NotBefore: 2020-04-28 07:56:04 +0000 UTC"
time="2020-04-28T11:18:19Z" level=info msg="NotAfter: 2020-07-27 07:56:04 +0000 UTC"
time="2020-04-28T11:18:19Z" level=info msg="SignatureAlgorithm: SHA256-RSA"
time="2020-04-28T11:18:19Z" level=info msg="PublicKeyAlgorithm: RSA"
time="2020-04-28T11:18:19Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get https://rancher.texttospeech.xyz: x509: certificate signed by unknown authority"

what is the solution for this

**Comment by sosoriov** [comment]
same here!

```
kubernetes: 1.16.4
rancher：2.3.5
```

**Comment by Sean-Snow** [comment]
same issue:

kubernetes: k3s + mysql
helm: 3
rancher: 2.4.3

``
time="2020-05-27T13:05:42Z" level=fatal msg="Server certificate is not valid, please check if the host has the correct time configured and if the server certificate has a notAfter date and time in the future. Certificate information is displayed above. error: Get https://rancher.xxx.com: x509: certificate has expired or is not yet valid"

``

<img width="990" alt="WX20200527-211008@2x" src="https://user-images.githubusercontent.com/4498796/83022730-8bbcd600-a05e-11ea-988b-e729d9301a1e.png">

**Comment by onkar-dhuri** [comment]
Same here....would like to know how we can rectify this ?
Especially after we have installed the rancher w/o specifying privateCA=true flag during installation.


My experience with rancher reinstallation hasn't been great and would want to know if this setting can be set somehow to read the CA certificate which would be passed down later using generic secret

**Comment by Sean-Snow** [comment]
Because my rancher was installed with --set tls = external. Externally use layer 7 load balancing, so when installing rancher in the cluster in k3s, the domain name rancher.xxx.com points to 192.168.1.3 and 192.168.1.4, causing `cattle-node-agent` to fail to recognize the certificate because 192.168.1.3 and 192.168 .1.4 ssl is not configured. Now set up `/etc/hosts`: 192.168.1.2 rancher.xxx.com on 192.168.1.3 and 192.168.1.4

nginxserver: 192.168.1.2 (https://rancher.xxx.com)

rancherserver001: 192.168.1.3 (http://rancher.xxx.com)
rancherserver002: 192.168.1.4 (http://rancher.xxx.com)
