### ISSUE TITLE
rancher/rancher:stable 在node上加入k8s后连接不上

### ISSUE THREAD

**Issue by Blanchefree** [rancher/rancher#24790]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`authenticated.cluster.monitoring.node-detail`|
	
当前集群Provisioning中...，在API准备就绪之前，直接与API交互的功能将不可用。

Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [172.16.133.209]

**Comment by loganhz** [comment]
Please find rancher2 to join Rancher WeChat group if you would like to ask questions in Chinese
