### ISSUE TITLE
Host Details icons/images not displayed for one of my newly created hosts.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#248]
Version: v0.12.0

After I created a new host, the display of the host was not consistent with other hosts. Two of the 3 properties of the machine were not being shown. This has only occurred 

When I refreshed my page, it loaded the images.

Before my refresh:

![screen shot 2015-03-18 at 1 24 20 pm](https://cloud.githubusercontent.com/assets/11410997/6718939/98ee5118-cd74-11e4-85d0-5aacf7cba15a.png)

After my refresh:

![screen shot 2015-03-18 at 1 49 46 pm](https://cloud.githubusercontent.com/assets/11410997/6719099/a7bd2cc2-cd75-11e4-86f9-10c0d6b06a6e.png)

**Comment by vincent99** [comment]
CPU and Storage come from cAdvisor, which probably wasn't up at the instant the host became active.. And I don't think there is a `resource.change` event sent when the `info` property on a host changes, so I wouldn't know to re-pull it until you refresh.  @ibuildthecloud ?

**Comment by deniseschannon** [comment]
I haven't seen this happen in awhile. Will re-open if I still see this issue.
