### ISSUE TITLE
ETCD access

### ISSUE THREAD

**Issue by DanielCambray** [rancher/rancher#24801]
Hi,

I have 3 nodes with a 'etcd' role in my cluster. Is it possible to use this ectd cluster from within my cluster ? When I try to do : 

`curl http://10.0.2.8:2379/v2/members -k --output -`

There's no output.

Thanks.

**Comment by superseb** [comment]
It uses client certificates to connect, you can try running this on an etcd node:

```
curl -s --cacert $(docker exec etcd printenv ETCDCTL_CACERT) --cert $(docker exec etcd printenv ETCDCTL_CERT) --key $(docker exec etcd printenv ETCDCTL_KEY) https://localhost:2379/metrics
```

There are some more examples on https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/etcd/.

It is not recommended to use a cluster's etcd for anything else than the cluster.
