### ISSUE TITLE
填入端口号以后，还是按照随机来分配的

### ISSUE THREAD

**Issue by liufuxi** [rancher/rancher#24809]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`containers.index`|

**Comment by loganhz** [comment]
It will be fixed in 2.3.4 with https://github.com/rancher/rancher/issues/24551
Please find `rancher2` to join Rancher WeChat group if you would like to ask questions in Chinese
