### ISSUE TITLE
Do not have access to Kiali and Jaeger after enabling in Istio

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#24806]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Enable Istio in Cluster and give access to either All authenticated members or specify a group
2. Login with a user who is NOT a cluster owner but IS a project owner

**Result:**
That user should have access to see Kiali and Jaeger links in the project, but does not. Also, trying to access a link directly given the URL gives an error:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
  },
  "status": "Failure",
  "message": "services \"http:tracing:80\" is forbidden: User \"u-7kci7j4kzt\" cannot get resource \"services/proxy\" in API group \"\" in the namespace \"istio-system\"",
  "reason": "Forbidden",
  "details": {
    "name": "http:tracing:80",
    "kind": "services"
  },
  "code": 403
}
```

**Other details that may be helpful:**
As a workaround, can set any member who should have access to Read Only in the System Project.

**Environment information**
rancher v2.3.3 Single node install

**Comment by loganhz** [comment]
Cannot reproduce it in 2.3.3

Steps: 

- Create a cluster
- Enable Istio with `Allow all authenticated members to access Kiali and Jaeger UI` selected
- Create a standard user `user1`
- Assign it to Default project as project owner
- Login as `user1`
- Try to access kiali and jaeger UI

When we enable Istio, the following role and rolebinding will be deployed. Can you use the following command to check if it is deployed?

`kubectl get RoleBinding read-istio-service -n istio-system -o yaml`
`kubectl get role istio-service-reader -n istio-system -o yaml`

**Comment by rancher-max** [comment]
Hmm that worked in a fresh install of 2.3.3 for me. I probably messed something up as I was going between versions. Thank you for double checking!

**Comment by amyounis** [comment]
i am using rancher-istio chart 104.4.0+up1.22.1 and no role or rolebinding 

> Cannot reproduce it in 2.3.3
> 
> Steps:
> 
>     * Create a cluster
> 
>     * Enable Istio with `Allow all authenticated members to access Kiali and Jaeger UI` selected
> 
>     * Create a standard user `user1`
> 
>     * Assign it to Default project as project owner
> 
>     * Login as `user1`
> 
>     * Try to access kiali and jaeger UI
> 
> 
> When we enable Istio, the following role and rolebinding will be deployed. Can you use the following command to check if it is deployed?
> 
> `kubectl get RoleBinding read-istio-service -n istio-system -o yaml` `kubectl get role istio-service-reader -n istio-system -o yaml`

i am using rancher-istio chart 104.4.0+up1.22.1 and no role or rolebinding whit the names you mentioned !
