### ISSUE TITLE
Openstack (Train version) Node Driver

### ISSUE THREAD

**Issue by Born2Bake** [rancher/rancher#24813]
**What kind of request is this (question/bug/enhancement/feature request):**

Rancher-Openstack Node driver is not compatible for latest version of Openstack: Train.

It does support Stein api's, however, using train version it cannot connect to compute API's.

ERRORS:

Error creating machine: Error in driver  during machine creation: Expected HTTP response code [200] when  accessing [POST http://10.0.225.254:8774/v2.1/os-keypairs], but got 403  instead

Error creating machine: Error in driver  during machine creation: Expected HTTP response code [200] when  accessing [POST http://10.0.225.254:8774/v2.1/servers], but got 400  instead

**Steps to reproduce (least amount of steps as possible):**

Deploy Openstack Train version and use rancher ostack node driver for nodes provisioning.

**Result:**

Docker machine will not be able to use nova compute API's and errors will come up.

**Other details that may be helpful:**

I assume, it can be fixed if API's support new version of Openstack:Train.

If I run - openstack:8774/v2.1/servers - unauthorized error / non-existent API.
If I run - openstack:8774/**compute**/v2.1/servers - it works. [ https://docs.openstack.org/api-ref/compute/ ]

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:latest
- Installation option (single install/HA): Single

- Docker version (use `docker version`):

```
19.x [latest]
```

**Comment by Born2Bake** [comment]
Hi,

I am wondering, is there a complete log file where I can see all info related to node driver provisioning and to see all errors in there?

**Comment by dhrp** [comment]
It works for me on OpenStack Train FYI

**Comment by canori01** [comment]
It works for me on Train as well.  However, I am also curious if there is a way to see logs for the node driver provisioning.
