### ISSUE TITLE
[Feature Request] Stack integration with GitHub

### ISSUE THREAD

**Issue by shakefu** [rancher/rancher#2481]
It would be great to see the following:
- Use the existing GitHub auth integration, possibly asking for more permissions as needed
- When creating a new stack, you can specify a GitHub repo to pull the rancher-compose.yml and docker-compose.yml from
- When making changes in the UI, you can (optionally) have Rancher keep the GitHub repo in sync by committing and pushing changes to the files
- When a commit is pushed to a repo from elsewhere, it would use a GitHub web hook to push the changes back to Rancher, keeping the config synchronized (though this could still be done with checking out the repo and the rancher-cli, this would allow this step to be skipped)

Benefits:
- Easily spin up new Stacks in different Rancher environments/servers with just a GitHub URL
- Avoid the pitfall of using an out-of-sync rancher-compose.yml/docker-compose.yml with the rancher-cli
- Add the benefits of versioning/being able to roll back an entire Stack config
- Allow a single commit (push) to use multiple web hooks to simultaneously update multiple Rancher environments and servers
- Allow a single Rancher UI to keep a Stack sync'd via multiple web hooks by keeping the repo up to date

**Comment by cusspvz** [comment]
-1

@shakefu, I would like to express only my opinion relating to this request, I am **NOT** part of the rancher team.

On a consistent deployment workflow system based on containers you usually have those stages:
- Development (where you transform pizza and coffee, and also maybe nicotine, into code)
- CI (where you test your code against problems)
- Image build system (some of us are putting this before the CI or in the CI process, if your app is with a nice architecture, probably this will be after CI) you can compare this with Docker Hub or quay.io
- Container provisioning system (where it deploys previously built images into different environments based on its stage) and this is where **rancher** fits!

When you're project isn't too large, or it is basic enough for don't include tests on it, you could skip **CI** and rely on the Image build system (thats why Docker Hub has directly integration with GitHub).
But I don't see advantages on skipping those all and jump directly from *Development* into *Container provisioning system*.

Thats a huge refactoring for **rancher**, not only on **code** but also on their **concept**.
Rancher had to be at least an **Image build system** (actually `rancher-compose` supports building into S3, but you don't have control about tags and stuff and thats only an advantage for rapid testing deployments, not for production), and have its own repos and build workers.

If you really need that now, you can put **git hooks** such as **after commit** on your repo to build and launch your stack calling `rancher-compose` on them.

**Comment by shakefu** [comment]
@cusspvz I think maybe you misunderstood? I was only proposing GitHub integration for the two .yml files. We have a full CI, which handles testing/image builds, and are piloting Rancher as part our Staging container provisioning.

I was thinking of this mostly as a way to handle doing "private" Stack catalogues, but with a more fluid workflow.

**Comment by jmreicha** [comment]
+1

**Comment by cusspvz** [comment]
@shakefu sorry for misunderstanding, though you was proposing integration for building and deploying directly from a GH repo. :confounded: 

We are also using a private GitHub repo for storing all our stacks, but since we are migrating repo by repo to GitLab, if this goes through, it would be nice to have GitLab as well.

**Comment by v01t** [comment]
+1

as I can see, rancher catalog so far have a next structure:

templates/
    app/
        0/
            docker-compose.xml
            rancher-compose.xml
        config.yml
        catalogIcon-app.png

so to "release" a new (existing in rancher) version to rancher-catalog you just need to add current (docker-compose.xml and rancher-compose.xml) files to the repo in folder with next version number "1" (0+1) then all other rancher servers that also use same catalog will see this stack with option "Update available".

One only problem that templates in rancher no more contains parameters (i.e. parameters names are replaced by values), so somehow they need to be merged with templates from "0" to parametrize everything back or other approach.

**Comment by vincent99** [comment]
There's no sync-ing/upgradeability and it's sort of an easter egg we don't ever talk about, but the Add Stack page in the UI accepts a few query parameters..  If you go to `https://your-rancher:8080/env/1a5/apps/stacks/add?githubRepo=your/repo`it will read docker/rancher-compose.yml from that repo and fill in the textarea.  `githubBranch=somebranch` for a branch other than master.  Or `composeFiles=http://some/base/url` to get the files from an arbitrary HTTP server instead of github.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
