### ISSUE TITLE
system-library-rancher-monitoring-0.0.3 not found

### ISSUE THREAD

**Issue by sewenc** [rancher/rancher#24812]
when install project monitor find red error msg: 
```
Catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.3" not found
```
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.8` UI: `v2.2.94` |
|path|`/p/c-h6k59:p-zqw6m/apps/p-zqw6m:project-monitoring`|

**Comment by loganhz** [comment]
Please check `system-library` in Global -> Tools -> Catalog page

**Comment by sewenc** [comment]
> Please check `system-library` in Global -> Tools -> Catalog page

thanks , Problem solved
