### ISSUE TITLE
Unable to add node to cluster

### ISSUE THREAD

**Issue by swedesoft** [rancher/rancher#24821]
I have a cluster with 6 nodes. One of them is master. All of my nodes are running RancherOS (latest version 1.5.5. When I try to add a seventh node (worker) the Rancher UI reports the following error: 

Delete https://<master-ip>:6443/api/v1/namespaces/default/serviceaccounts/netes-default: can not build dialer to [c-txsgb:m-250ea574bd93]

When I look in the Docker log files on the offending node I found: 

Error while getting agent config: invalid response 500: Failed to construct node config. Error: failed to find plan for <node.ip>

I followed the exact same process for all of my nodes so I am a bit lost to how to resolve this.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`authenticated.cluster.edit`|

**Comment by superseb** [comment]
Please check the two issues shown in https://github.com/rancher/rancher/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22failed+to+find+plan+for%22

Also, please provide logging from the `rancher/rancher` container. The error regarding `can not build dialer` shows `c-txsgb:m-250ea574bd93`, can you check the nodes view and hover the nodes to see what ID it is referring to (is `m-250ea574bd93` the new node or an existing node), and what is in the `rancher/rancher-agent` container log for that and the newly added node (if they are not the same)

**Comment by swedesoft** [comment]
Thank you for your quick reply. 

It looks like it is referring to the master node (c-txsgb:m-250ea574bd93 is the master node)

Here is some of the output of the rancher/rancher log on the VM that is running Rancher:

2020/01/02 18:33:04 [INFO] Handling backend connection request [c-txsgb:m-9c41dae30ac6]
2020/01/02 18:33:04 [INFO] Handling backend connection request [c-txsgb:m-9c41dae30ac6]
E0102 18:33:04.938564       7 reflector.go:280] github.com/rancher/norman/controller/generic_controller.go:193: Failed to watch *v1.LimitRange: Get https://10.0.4.138:6443/api/v1/watch/limitranges?allowWatchBookmarks=true&resourceVersion=1&timeout=30m0s&timeoutSeconds=561: dial tcp 127.0.0.1:6443: connect: connection refused
2020/01/02 18:33:04 [INFO] Handling backend connection request [c-txsgb:m-9c41dae30ac6]
2020-01-02 18:33:05.609158 W | etcdserver: read-only range request "key:\"/registry/replicasets\" range_end:\"/registry/replicasett\" count_only:true " with result "range_response_count:0 size:6" took too long (139.075894ms) to execute
E0102 18:33:05.942031       7 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:193: Failed to list *v1.LimitRange: Get https://10.0.4.138:6443/api/v1/limitranges?limit=500&resourceVersion=0&timeout=30s: dial tcp 127.0.0.1:6443: connect: connection refused

**Comment by swedesoft** [comment]
For some reason, the Docker service had gone down on my nodes. I believe it happened when I switch the console to the Ubuntu console (trying to install Longhorn). I killed my cluster and started over so I can no longer troubleshoot this one. Closing the issue.
