### ISSUE TITLE
Add helper text to review k8s release notes

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#24829]
When editing clusters or RKE templates for k8s versions, we should add in helper text to request the end user to review the k8s release docs before upgrading their k8s version.

```
When upgrading Kubernetes versions, please review the Kubernetes release notes for any breaking changes.
```

**Comment by sowmyav27** [comment]
**Verified on latest master-head, commit id: `552eb2896` and 2.3-head commit id: `12f8338c4`**

- Helper text is available on an Edit cluster
<img width="700" alt="Screen Shot 2020-01-06 at 9 09 58 AM" src="https://user-images.githubusercontent.com/26032343/71835326-0fe9cf00-3066-11ea-82df-725afa0463e7.png">

**Comment by sowmyav27** [comment]
@deniseschannon @westlywright Have a question about how we want it in case of rke templates edit cluster case - 

In edit cluster and change/switch templates/template revisions, will the helper text be available only when there is a k8s version change between the templates/template revisions OR will the helper text be available on the UI irrespective of the k8s version check?

**Comment by westlywright** [comment]
An update has been pushed to `latest2` and `latest-2.3`

**Comment by sowmyav27** [comment]
verified on 2.3-head latest , ui tag: latest-2.3

- CNI plugin text is available while creating an rke template and while creating a cluster
<img width="1450" alt="Screen Shot 2020-01-13 at 4 15 28 PM" src="https://user-images.githubusercontent.com/26032343/72302882-47d1b300-3620-11ea-85f9-a7dda755925f.png">
<img width="1452" alt="Screen Shot 2020-01-13 at 4 15 18 PM" src="https://user-images.githubusercontent.com/26032343/72302885-4902e000-3620-11ea-829c-23da845a2744.png">

**Cluster from RKE template**

Create an rke template with k8s v 1.16 - t1 (kubernetes version: Allow user override: No)
Clone this rke template - save with k8s 1.17 - t2 (kubernetes version: Allow user override: No)
Create a cluster using template - t1
edit cluster, change template to t2 (k8s version changes to 1.17)
Helper text- is available on the UI.
<img width="1510" alt="Screen Shot 2020-01-13 at 4 17 14 PM" src="https://user-images.githubusercontent.com/26032343/72302911-58822900-3620-11ea-8d85-6b1625822251.png">

**Comment by sowmyav27** [comment]
PR for master - https://github.com/rancher/ui/pull/3712
