### ISSUE TITLE
cannot create resource "clusterroles" while installing "ELK" via rancher

### ISSUE THREAD

**Issue by ahoehma** [rancher/rancher#24822]
Failed to install app mca-phdzs-p-rpkn6. Error: release mca-phdzs-p-rpkn6 failed: clusterroles.rbac.authorization.k8s.io is forbidden: User "u-zwzqejpnll" cannot create resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope

I'm really a noob right now :) So I have no idea what user "u-zwzqejpnll"  is.  I logged into rancher via "admin". So I guess I can do anything. 

I tried the quicksetup quide ... cluster is running as far as I see.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`apps-tab.detail`|

**Comment by ahoehma** [comment]
Ähmm ... I think I got it :D 
I changed "Available Roles" from "Project" to "Cluster" and now it works.
Sorry!

**Comment by ballahverdiyev-pshb** [comment]
hello the same problem for me, how you solved this? can you explain clearly?
