### ISSUE TITLE
Kiali port pointing to 20001 when upgrading from 2.3.3 to 2.3.4

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#24831]
Using Rancher version `2.3.3`, create a cluster with istio enabled. Accessing the kiali link should be a proxy with `kiali-http:80`.

Upgrade Rancher version to `2.3-head` or `2.3.4-rc6`, which should introduce an upgraded istio version. The cluster that had the older istio version enabled should still be working, but the links to kiali and jaeger do not show up. This is because the UI is hard coded to use `kiali:20001` for the new istio version, but should change based on the enabled version.

**Comment by westlywright** [comment]
related UI PR's:

https://github.com/rancher/ui/pull/3697
https://github.com/rancher/ui/pull/3698

**Comment by rancher-max** [comment]
Validated fix in 2.3-head and master-head commit 8bd9f3be2
