### ISSUE TITLE
Rancher cannot monitor the ETCD that imported cluster

### ISSUE THREAD

**Issue by F-liuhui** [rancher/rancher#24839]
**What kind of request is this (question/bug/enhancement/feature request):**
Rancher cannot monitor the ETCD that imported cluster

**Steps to reproduce (least amount of steps as possible):**
 Currently, rancher's own monitoring system cannot monitor the ETCD imported into the cluster. Are there any plans to support this requirement in later versions? What are the current solutions for this situation

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by vincent99** [comment]
Importing a cluster gives us access to only "inside" the k8s API exposed by that cluster.  We can't monitor etcd or manipulate the configuration of the "outside" of the cluster from that.

Also Rancher didn't deploy it, has no idea where it is, and has no credentials to talk to it.  And for any given cluster there may not even exist an etcd at all (e.g. k3s is backed by SQL by default).  Or it may be provided as a managed service that  there is no external access to (e.g. most hosted Kubernetes-as-a-service providers).

**Comment by F-liuhui** [comment]
I see, thank you. Can the monitoring system provided by rancher monitor the ETCD of the imported cluster by changing the default configuration? I don't seem to find it possible to modify

**Comment by mohjam2004** [comment]
Hi,
Is there any solution by which we can solve this issue?
Regards.

**Comment by mohjam2004** [comment]
Hi,
Enterprise PKS had the same problem and resolved it:
https://kb.vmware.com/s/article/71049
Is there any solution in Rancher?
Regards

**Comment by aiyengar2** [comment]
Monitoring V2 supports this

**Comment by aiyengar2** [comment]
FYI the solution employed by Monitoring V2 uses [rancher-pushprox](https://github.com/rancher/charts/tree/release-v2.5/charts/rancher-pushprox/rancher-pushprox/0.1.201), a Helm chart based solution designed to scrape etcd metrics in hardened cluster setups.

Monitoring V2 has configurations for rancher-pushprox for different cluster types [here](https://github.com/rancher/charts/blob/aae93d0125fad561024b25ac1a15580ea612e158/charts/rancher-monitoring/rancher-monitoring/9.4.203/values.yaml#L24-L233) but there is currently no plan to extend rancher-pushprox support for Monitoring V1.

Please upgrade to V2!
