### ISSUE TITLE
Monitoring Prometheus PVC doesn't work with OpenEBS (again)

### ISSUE THREAD

**Issue by tardich** [rancher/rancher#24837]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Enable monitoring with
  - PersistentStorage for Prometheus (storageClass: openebs)
  - PersistentStorage for Graphana (storageClass: openebs)
  - Adding prometheus.persistence.name option with "blahblah" as value *
  - Adding prometheus.persistent.useReleaseName with "true" as value  *
    * these options comes from issue 19410 (https://github.com/rancher/rancher/issues/19410)

**Result:**
PVC with this name "prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0" stays in a Pending state forever

**Environment information**
- Rancher 2.3.3
- OpenEBS 1.5.0 (latest at time of writing)
- Monitoring Version 0.0.6

**Comment by loganhz** [comment]
Please try to disable monitoring and go to System project, make sure the pvc `prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0` has been removed.

Then enable monitoring with `prometheus.persistence.name=blah` again

**Comment by alexandrujieanu** [comment]
Hi,

This is still happening on Rancher v2.3.2.

The Prometheus PV isn't created because its name exceeds 63 characters.
The Grafana PV is created because it has a much shorter name.

```
storageclass: openebs-cstor-retain-1-replica }: failed to create service: Service "pvc-22ff3423-4be9-11ea-a93f-0694661bc4ca" is invalid: metadata.labels: Invalid value: "prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0": must be no more than 63 characters
```

```
kubectl get pvc -n cattle-prometheus
NAME                                                               STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                      AGE
grafana-cluster-monitoring                                         Bound     pvc-2277c799-4be9-11ea-9db2-024fe39b56b4   3Gi        RWO            openebs-cstor-retain-3-replicas   50s
prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0   Pending                                                                        openebs-cstor-retain-3-replicas   49s
```

I added this entry in the Advanced section to get it working. 
`prometheus.persistence.name=prometheus-cluster-monitoring`

```
kubectl get pvc -n cattle-prometheus
NAME                                                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                      AGE
grafana-cluster-monitoring                                      Bound    pvc-279b14e3-4bec-11ea-9db2-024fe39b56b4   3Gi        RWO            openebs-cstor-retain-3-replicas   48s
prometheus-cluster-monitoring-prometheus-cluster-monitoring-0   Bound    pvc-281407a8-4bec-11ea-a93f-0694661bc4ca   50Gi       RWO            openebs-cstor-retain-1-replica    47s
```

To be honest I expected a much shorter name, the one I entered.

Please notice the difference between these three:
```
prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0 = 64 chars
prometheus-cluster-monitoring-prometheus-cluster-monitoring-0 = 61 chars
grafana-cluster-monitoring = 26 chars
```

Prometheus still has a much longer PV name than Grafana.
