### ISSUE TITLE
vSphere Node Template FolderList does not show sub dirs

### ISSUE THREAD

**Issue by fichterto** [rancher/rancher#24840]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create vSphere Node Template in e.g. Rancher v2.3.3
2. See Folder Dropdown in "2. Scheduling"

**Result:**
Subdirectories are not listet in Dropdown

**Slack with @luthermonson :**
https://rancher-users.slack.com/archives/CBEB5A0H1/p1577967463055900

![2020-01-03 08_26_12-vsphere](https://user-images.githubusercontent.com/22402578/71712744-ebdc8280-2e06-11ea-8303-85652f1b6b29.png)

![2020-01-03 08_27_33-dropdown](https://user-images.githubusercontent.com/22402578/71712745-ebdc8280-2e06-11ea-8170-0a5b7bd37102.png)

**Environment information**
- rancher/rancher:v2.3.3
- vSphere Cluster v6.7

**Comment by luthermonson** [comment]
govmomi logic for a vm/* is only pulling one layer deep of folders. will pull all folders and string match to make sure they're a vm folder.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
rancher/rancher:master-head

* Folder dropdown shows the full path and all subdirectories. 
* The node is created in the correct folder.

![Screen Shot 2020-01-06 at 2 54 40 PM](https://user-images.githubusercontent.com/21316915/71852298-9cf84c80-3095-11ea-8641-b600f8bb76cf.png)
