### ISSUE TITLE
vSpehere Nodetemplate Folder Selector Update

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#24853]
When using folders in vSphere we have the ability to do full folder paths and the last element of the path is not enough to be specific enough when using this feature. If someone has `/dc/vm/dev/k8s` and `/dc/vm/prd/k8s` they'll see only `k8s` twice on the drop down. Will need to either grab more from the path or something more interesting.

![Screen Shot 2020-01-03 at 2 54 49 PM](https://user-images.githubusercontent.com/1616909/71751623-66be9100-2e39-11ea-9e3c-d4a4879dacb2.png)

![Screen Shot 2020-01-03 at 1 43 18 PM](https://user-images.githubusercontent.com/1616909/71751628-6a521800-2e39-11ea-82d6-438a55d69daf.png)

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head
rancher/rancher:master-head

* Folder dropdown shows the full path and all subdirectories. 
* The node is created in the correct folder.

![Screen Shot 2020-01-06 at 2 54 40 PM](https://user-images.githubusercontent.com/21316915/71852250-881bb900-3095-11ea-82e9-c7db688f76e9.png)
