### ISSUE TITLE
[backport] Latest Server Chart to Support cert-manager 0.12.0 is broken

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#24855]
Backport for https://github.com/rancher/rancher/issues/24770

**Comment by sangeethah** [comment]
https://github.com/rancher/rancher/pull/24835

**Comment by soumyalj** [comment]
Created a HA setup using the Cert Manager v0.12. 
Used the below steps to install Cert-manager:
https://cert-manager.io/docs/installation/kubernetes/#installing-with-helm
Rancher server HA setup got created fine. 
kubectl displays the tls-rancher-ingress as expected
```
> kubectl get certificate -n cattle-system
NAME                  READY   SECRET                AGE
tls-rancher-ingress   True    tls-rancher-ingress   54m
```
Verified that new cluster can be created in the rancher server setup and it is functional.

The only issue observed is that the tls-rancher-ingress displayed in UI has domain name as "none" and the expiration date is "Invalid"
<img width="1289" alt="Screen Shot 2020-01-03 at 4 38 00 PM" src="https://user-images.githubusercontent.com/18536626/71757013-ac825600-2e47-11ea-8f5d-61c5d0c0b4e5.png">

**Comment by jiaqiluo** [comment]
Upgrading Rancher from v2.2.9 to v2.2.10-rc3 succeeds. 

Steps:
- install Rancher v2.2.9 in HA mode with letsEncrypt
- when opening Rancher UI in chrome, there is no warning for insecure connection & unknown certs 
- check certifications are created properly 
- add a cluster (DO in my case)
- check the cluster working properly (launching kubectl from UI, check pods' logs)
- upgrade cert-manager to v0.12 and Rancher to v2.2.10-rc3 (still with LetsEncrypt enabled). Here is the instruction: https://github.com/rancher/rancher/issues/23424#issuecomment-570691732

after upgrading
- there is only one issuer in the cluster where Rancher runs
```
➜  kubectl get issuers.cert-manager.io -A
NAMESPACE       NAME      READY   AGE
cattle-system   rancher   True    38m
```
- when opening Rancher UI in chrome, there is no warning for insecure connection & unknown certs 
- check certifications are created properly 
- check the existing cluster working properly (launching kubectl from UI, check pods' logs)
- add a new cluster
- check the new cluster working properly (launching kubectl from UI, check pods' logs)

**Comment by jiaqiluo** [comment]
The issue about the invalid domain name and the expiration date is tracked by this issue:
https://github.com/rancher/rancher/issues/24940
