### ISSUE TITLE
[forwardport]Cattle-cluster-agent and cattle-node-agent do not rollback to the previous version 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#24859]
Forward port of https://github.com/rancher/rancher/issues/21386

**Comment by sangeethah** [comment]
master
types: https://github.com/rancher/types/pull/1064
master: https://github.com/rancher/rancher/pull/24598

**Comment by soumyalj** [comment]
Verified on a upgrade/rollback from v2.3.5 to master-head(f21253e15) and back.

1. Created a rancher setup with v2.3.5 .
2. Upgrade rancher server from v2.3.5 to master-head
3. Rolled back rancher from master-head to v2.3.5.

Cluster-agent and node-agent rolled back to v2.3.5 version as expected.
<img width="1283" alt="Screen Shot 2020-03-02 at 10 06 25 PM" src="https://user-images.githubusercontent.com/18536626/75747708-84da2d80-5cd2-11ea-9f02-b0abade522e2.png">
