### ISSUE TITLE
Create a delete all stopped containers button on the host. 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2485]
Based on http://forums.rancher.com/t/delete-containers-after-stopping/822/3

It would be nice if the host had a button that would delete all stopped containers on the host. 

The button would perform `docker rm $(docker ps -a -q)` on the host. 

Note: This would need to be added in API first.

**Comment by astanciu** [comment]
Awesome, thank you

**Comment by vincent99** [comment]
@westlywright Not for today but this should be fairly straightforward to loop over them in the UI without specific API support.

**Comment by balzaczyy** [comment]
I'm using 1.1.3 and want to re-raise the attention of this feature request. I have now seen almost 50 pages of stopped containers in Infrastructure/Containers page. It's impossible to clear them all. (I tried but they just keep growing themselves). The host shows unknown so I think they could be dirty data.

Please re-consider this feature request or provide a workaround to cleanup those annoying entries.

**Comment by MichaelErmer** [comment]
+1 stopped containers all over the place

**Comment by olafmol** [comment]
+1

**Comment by ccamp46** [comment]
+1

**Comment by vincent99** [comment]
1.3 adds bulk-actions to the Containers list (and future releases will spread that elsewhere), so I don't think this is necessary anymore (or necessarily a good idea to just delete a bunch of containers without knowing what they are...)

![image](https://cloud.githubusercontent.com/assets/753917/22045851/245a1f54-dcda-11e6-9dec-8891a280a3fa.png)

**Comment by airdata** [comment]
I feel the same .... :(

**Comment by devarti** [comment]
One of the issue i am seeing on Rancher UI is that, even though you delete the containers that are marked as "Stopped" are keep coming up on the same host. Does it have to be deleted from MySQL database as well? 
Note: I am running Rancher with mounted filesystem and backed is MySQL.

**Comment by devarti** [comment]
So it would be something like this. 


mysql> delete from instance where name like '%tiller%' and state='stopped';
Query OK, 3 rows affected (0.01 sec)

mysql> delete from instance where name like '%dns%' and state='stopped';
Query OK, 4 rows affected (0.01 sec)

mysql> delete from instance where name like '%influxdb%' and state='stopped';
Query OK, 2 rows affected (0.01 sec)

mysql> delete from instance where name like '%sidecar%' and state='stopped';
Query OK, 2 rows affected (0.01 sec)

mysql> delete from instance where name like '%heapster%' and state='stopped';
Query OK, 1 row affected (0.00 sec)

mysql> delete from instance where name like '%grafana%' and state='stopped';
Query OK, 2 rows affected (0.01 sec)

**Comment by vincent99** [comment]
If the containers are from a service, then deleting them is host going to cause rescheduling a new one to maintain the specified scale.

You should not be randomly deleting things from the databaseI.

This issue was for a "delete all stopped containers" action, and is closed because we felt it would be unnecessarily dangerous.  You can sort by State, click one checkbox and shift-click another to select a range.

If an endless stream of random standalone container names is being created, you probably have something running on the host like a CI system that does `docker run` without `--rm`and doesn't clean up after itself.  So you should address that, not try and find a bigger broom to clean up after it with.

**Comment by devarti** [comment]
Is there a clean way of deleting nodes, pods, services from Rancher built-in MySQL database then?
