### ISSUE TITLE
[backport] Latest Server Chart to Support cert-manager 0.12.0 is broken

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#24856]
Backport of https://github.com/rancher/rancher/issues/24770

**Comment by sangeethah** [comment]
https://github.com/rancher/rancher/pull/24836

**Comment by jiaqiluo** [comment]
Upgrading Rancher from v2.1.13 to v2.1.14-rc2 succeeds. 

Steps:
- install Rancher v2.1.13 in HA mode with letsEncrypt
- when opening Rancher UI in chrome, there is no warning for insecure connection & unknown certs 
- check certifications are created properly 
- add a cluster (DO in my case)
- check the cluster working properly (launching kubectl from UI, check pods' logs)
- upgrade cert-manager to v0.12 and Rancher to v2.1.14-rc2 (still with LetsEncrypt enabled). Here is the instruction: https://github.com/rancher/rancher/issues/23424#issuecomment-570691732

after upgrading
- there is only one issuer in the cluster where Rancher runs
```
➜  kubectl get certificates.cert-manager.io  -A
NAMESPACE       NAME                  READY   SECRET                AGE
cattle-system   tls-rancher-ingress   True    tls-rancher-ingress   70s
```
- when opening Rancher UI in chrome, there is no warning for insecure connection & unknown certs 
- check certifications are created properly 
- check the existing cluster working properly (launching kubectl from UI, check pods' logs)
- add a new cluster
- check the new cluster working properly (launching kubectl from UI, check pods' logs)

**Comment by aaronRancher** [comment]
Created a HA setup using the Cert Manager v0.12.
Used the below steps to install Cert-manager:
https://cert-manager.io/docs/installation/kubernetes/#installing-with-helm
Installed Rancher:
```
helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=<hostname>--set ingress.tls.source=letsEncrypt --set letsEncrypt.email=<email> --version=v2.1.14-rc2
```
kubectl displays the tls-rancher-ingress as expected:
```
>kubectl get certificate -n cattle-system
NAME                  READY   SECRET                AGE
tls-rancher-ingress   True    tls-rancher-ingress   17m
```
Verified that a new cluster can be created and that it was working properly (launching kubectl from UI, check pods' logs)

The only issue observed is that the "tls-rancher-ingress" displayed in UI has domain name as "none" and the expiration date is "Invalid"

**Comment by tryhardest** [comment]
@jiaqiluo have you succeeded with v2.3.4-rc7? Will try tmr and report back. I see you have latest there @aaronRancher so fingers crossed.  The "tls-rancher-ingress" displayed in UI has domain name as "none" and the expiration date is "Invalid" I'll report if we also see.

**Comment by jiaqiluo** [comment]
The issue about the invalid domain name and the expiration date is tracked by this issue:
https://github.com/rancher/rancher/issues/24940
