### ISSUE TITLE
K8s 1.17 - Coredns stuck in "Updating" state in cluster with windows node.

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#24854]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a custom cluster with AWS with:
1 Linux etcd/control node
1 linux worker
3 windows worker nodes

**AMI**
AMI ID: ami-0bce54f2d5686d6c3
Name: windows-1903-docker-1903-ssh
Region: us-west-1

Provision the linux nodes first.
Wait for the cluster to become available before provisioning the windows node.

**Result:**
coredns is stuck upgrading:
![Screen Shot 2020-01-03 at 2 49 43 PM](https://user-images.githubusercontent.com/57409052/71751469-e566fe80-2e38-11ea-9f3d-cfb862d95704.png)
coredns view:
![Screen Shot 2020-01-03 at 3 01 31 PM](https://user-images.githubusercontent.com/57409052/71751797-f9f7c680-2e39-11ea-8ee6-cbd49a895dd8.png)
Error seen in pod:
![Screen Shot 2020-01-03 at 2 55 47 PM](https://user-images.githubusercontent.com/57409052/71751557-324ad500-2e39-11ea-9f97-c094a69223ba.png)

Node count appears to be off:
![Screen Shot 2020-01-03 at 2 56 52 PM](https://user-images.githubusercontent.com/57409052/71751605-55758480-2e39-11ea-87b2-b8f9d53f34bd.png)
![Screen Shot 2020-01-03 at 2 59 01 PM](https://user-images.githubusercontent.com/57409052/71751690-98375c80-2e39-11ea-87be-7e8bb2ef215b.png)

Each windows worker is correctly labeled as a worker:
![Screen Shot 2020-01-03 at 2 59 57 PM](https://user-images.githubusercontent.com/57409052/71751751-d5035380-2e39-11ea-8c02-9c7d6f77b76a.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
`v2.3-head` commit `a21dd0bab`
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Kubernetes version (use `kubectl version`): `v1.17.0-rancher1-2`
- Network Provider: `flannel`
- Windows Support: Enabled
- Cloud Provider: Amazon

**Comment by deniseschannon** [comment]
Could your fix related to coredns in RKE be applied to this use case? @superseb

**Comment by superseb** [comment]
@kinarashah Think the autoscaler labels should inclue `beta.kubernetes.io/os=linux` as well so it doesn't count Windows nodes as schedulable nodes?

**Comment by kinarashah** [comment]
> @kinarashah Think the autoscaler labels should include `beta.kubernetes.io/os=linux` as well so it doesn't count Windows nodes as schedulable nodes?

yeah, we need linux label as well

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.3-head` `version 9243de496`

Core DNS is functional.
![Screen Shot 2020-01-13 at 3 51 50 PM](https://user-images.githubusercontent.com/57409052/72298947-c0cf0b80-361c-11ea-87c2-72e8c346dfd1.png)

Tags in the windows worker node:
```
beta.kubernetes.io/os = windows
kubernetes.io/os = windows
```
Tags in the linux worker node:
```
beta.kubernetes.io/os = linux
kubernetes.io/os = linux
```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 88fcc20ad`

Core DNS is functional.
![Screen Shot 2020-01-13 at 4 35 41 PM](https://user-images.githubusercontent.com/57409052/72301146-1f978380-3623-11ea-996b-9c39b4dc8373.png)

Tags in the windows worker node:
```
beta.kubernetes.io/os = windows
kubernetes.io/os = windows
```
Tags in the linux worker node:
```
beta.kubernetes.io/os = linux
kubernetes.io/os = linux
```
