### ISSUE TITLE
Rancher SSL 

### ISSUE THREAD

**Issue by Derga127** [rancher/rancher#24861]
Hello,

I hope you can help me.

I have a Rancher v1.6.29 server with 3 client hosts (Docker version 18.06.1-ce),

The hosts appear disconnected on the server rancher. On Rancher when I want to add a host the following message is displayed on the 3 client servers: "https://rancher.example.fr/v1 is not accessible (server certificate verification failed. CAfile: / etc / ssl / certs / ca-certificates.crt CRLfile: none) "

FYI I looked for this error, they say to add the certificate of Rancher /etc/ssl/certs/ca-certificates.crt

On chrome the certificate is valid

I thank you in advance

**Comment by tryhardest** [comment]
Can you update Rancher to 2.3.x or is that out of the question? What version cert-manager are you using? Not .12?
