### ISSUE TITLE
Not all pod resource usage shows up in Rancher UI - Ex KubeVirt

### ISSUE THREAD

**Issue by mjschmidt** [rancher/rancher#24865]
**What kind of request is this (question/bug/enhancement/feature request):**
/bug
Rancher does not get resource usage from all running pods

**Steps to reproduce (least amount of steps as possible):**
Launch a rancher cluster
Launch KubeVirt using the following [directions here](https://kubevirt.io/quickstart_minikube/) I reccomend using v0.24.0
Launch the example fedora virtual machine using the directions with the following commands:
```
kubectl apply -f https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml
virtualmachine.kubevirt.io "testvm" created
```

Notice that the pod resource usage does not show up in rancher UI cluster overview, even when pod is launched in default namespace.

**Result:**
Pod Resource usage does not show up in UI overview tab

**Other details that may be helpful:**
If you have follow up questions ask, but I think this is a pretty straight forward bug, or design decison I am not aware of.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Shouldn't matter, you all can test on aws by setting the config map for software virtualization set to true
- Machine type (cloud/VM/metal) and specifications (CPU/memory): I'd get at least a few cpu and ram
- Kubernetes version (use `kubectl version`):

```
1.16.0+ is what I used
```

- Docker version (use `docker version`):Docker 1.19 I believe? Everything else is working fine so I don't think its docker version related? 
```
19.06+
```

**Comment by loganhz** [comment]
Could you provide some screenshots, please?

**Comment by mjschmidt** [comment]
We can actually close this issue, this was user error. Thanks for responding I was having a hard time finding the issue. Sorry for the inconvenience.
