### ISSUE TITLE
自动拉起aws EC2 失败后，不能删除该节点，手动删除EC2实例后,集群监控，项目监控工作不正常

### ISSUE THREAD

**Issue by yangyang198599** [rancher/rancher#24862]
自动拉起aws EC2 失败后，不能删除该节点，手动删除EC2实例后,集群监控，项目监控工作不正常
---

 
![截屏2020-01-06下午5 16 06](https://user-images.githubusercontent.com/43692461/71808262-3d824880-3065-11ea-8a1b-c51e0883f41f.png)
Versions Rancher `v2.3.3` UI: `v2.3.3` |

**Comment by loganhz** [comment]
Please add `rancher2` to join Rancher WeChat group if you would like to ask questions in Chinese.
