### ISSUE TITLE
System chart should pull images from the cluster-level registry

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#24889]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.3.4-rc8 single installed in an air-gapped env or upgrade from v2.3.3
- add a global registry 
- add a custom cluster with a cluster-level registry
- enable the cluster monitoring / project monitoring / external DNS / logging / alerting / Istio in the cluster 

**Result:**
- the images of system charts are pulled from the global registry 

**Other details that may be helpful:**
- we expect to see the images  are pulled from the cluster-level registry 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.4-rc8
- Installation option (single install/HA): single install

**Comment by loganhz** [comment]
@jiaqiluo  Does it work in 2.3.3? there is no changes in 2.3.3 for monitoring.

**Comment by jiaqiluo** [comment]
@loganhz the `global registry` is the `system-default-registry`. in v2.3.3 it also pulls images from the `system-default-registry`

what is the behavior if only the cluster-level registry is set, will it pull images from the cluster-level one?

**Comment by maggieliu** [comment]
Pushing out to 2.4. Need discussion with @cloudnautique on global registry vs. cluster registry

**Comment by deniseschannon** [comment]
@jiaqiluo This is by design where the cluster level registry is only used for provisioning clusters and the images used for provisioning them. 

 @catherineluse We should clarify in this page that this registry is only used for provisioning cluster: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#private-registries

**Comment by catherineluse** [comment]
Our global configuration docs say this:


> There are multiple ways to configure private registries in Rancher, depending on whether your private registry requires credentials:
> 
>     - If your private registry requires credentials, you need to pass the credentials to Rancher by editing the cluster options for each cluster that needs to pull images from the registry.
>     - If the private registry doesn’t require credentials, you can configure it as a default registry through the Settings tab in the global view.
> 
> If your private registry requires credentials, it cannot be used as the default registry. There is no global way to set up a private registry with authorization for every Rancher-provisioned cluster. Therefore, if you want a Rancher-provisioned cluster to pull images from a private registry with credentials, you will have to pass in the registry credentials through the advanced cluster options every time you create a new cluster.

Is the cluster-level registry just for installing the system charts? Should we make it clear that a use case of the cluster-level registry is to set up authorization for private registries that require credentials?

**Comment by jiaqiluo** [comment]
> Is the cluster-level registry just for installing the system charts? 

As I understand the cluster-level registry can be used for the user's own images, the same does the global registry.

**Comment by catherineluse** [comment]
I have updated the docs to clarify that the cluster-level private registry is only for provisioning clusters.

I also clarified that the global registry is only for air gapped setups, whereas the cluster-level registry is only for setups with credentials.

https://github.com/rancher/docs/pull/2203

**Comment by deniseschannon** [comment]
@jiaqiluo can you review the docs changes and close this issue?

**Comment by jiaqiluo** [comment]
The PR https://github.com/rancher/docs/pull/2203 LGTM.
this issue is closed.
