### ISSUE TITLE
Fix resource definitions graphs

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#2488]
It appears the graphing javascript library is no longer hosted. Used to be hosted here:
https://mdaines.github.io/viz.js/viz.js

So, pages like http://localhost:8080/v1/resourcedefinitions/1rd!service/resourcedot no longer load.

**Comment by will-chan** [comment]
@vincent99 this still happening?

**Comment by vincent99** [comment]
I think @cjellick just fixed it for this release, since he had me put up a new copy of the js onto the CDN..

**Comment by sangeethah** [comment]
Tested with rancher-server version -v0.52.0-rc4 . Able to load http://<ip>:8080/v1/resourcedefinitions/1rd!service/resourcedot
