### ISSUE TITLE
Command to add nodes to custom cluster should not use cluster-level private registry 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#24888]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/question 

The bug is found when testing Rancher v2.3.4-rc8 in an air-gapped environment, then it turns out the bug exists in the regular single-install setup, too. 

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:v2.3.4-rc8  single-install 
- add a global registry `global.com`
<img width="1422" alt="Screen Shot 2020-01-07 at 4 22 59 PM" src="https://user-images.githubusercontent.com/6218999/71937777-9b4c8880-316a-11ea-9671-b9b9379e74bd.png">

- add a custom clsuter with a private registry `cluster.com`
- click `next`

**Result:**

It is expected to see that the command to add nodes uses the global registry, but it uses the cluster-level registry actually.
<img width="1308" alt="Screen Shot 2020-01-07 at 4 22 51 PM" src="https://user-images.githubusercontent.com/6218999/71937953-27f74680-316b-11ea-84f4-f4de21e62b1e.png">

But it turns that nodes can be added to the cluster successfully by running the command showing in the UI, and it will fail if I change the registry to the global cluster.

when using the global registry, in the node only the rancher-agent runs up, but no other containers are pulled and start, so in the UI the node is stuck in registering state and  the cluster is stuck in provisioning state

Is using the cluster-level registry expected? 
 
Related issue: https://github.com/rancher/rancher/issues/20029

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.4-rc8
- Installation option (single install/HA):
single install

**Comment by sangeethah** [comment]
When there is only global registry set (and no cluster level registry) , Command to add nodes to custom cluster includes the global registry as expected.

**Comment by maggieliu** [comment]
Pushing out to 2.4. Need discussion with @cloudnautique on global registry vs. cluster registry

**Comment by deniseschannon** [comment]
This is by design. 

If a cluster level registry is defined, all cluster creation components will use the cluster level registry including obtaining the rancher/agent nodes.

**Comment by jiaqiluo** [comment]
This is closed since it is not a bug.
