### ISSUE TITLE
in 2 level nginx,the rancher's websocket cann't work

### ISSUE THREAD

**Issue by chengzn** [rancher/rancher#24880]
in rancher 2.3.3

my rancher was proxy by 2 nginx

like this
https-----nginx---http---nginx---rancher:80

but it's a problem,  the rancher's websocket cann't work.

both 2 nginx  deploy were like this
![image](https://user-images.githubusercontent.com/42170032/71895734-d52e8680-318c-11ea-9c3e-25465ae33855.png)

**Comment by vincent99** [comment]
There may be more wrong but at least the x-forwarded headers need to be "add" instead of "set" on the "inner " server, or not modified at all.  The values from the outer one nginx are getting overwritten Andy rancher needs the original protocol/host/port.

**Comment by chengzn** [comment]
@vincent99 Can you give me a more specific way? Thank you
