### ISSUE TITLE
All clusters became "Unavailable"

### ISSUE THREAD

**Issue by troy256** [rancher/rancher#24883]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Unknown

**Result:**
On-prem Rancher v2.3.3 server with 9 clusters showed that all were "Unavailable" in the State column.

**Other details that may be helpful:**
 If you clicked on the Nodes tab for each cluster you could see all nodes were active.  Logs from the Rancher server did not show any errors.  Logs from the kubelet on nodes did not show any errors.  Waiting did not change anything, restarting the Rancher Server had no effect.  I spot checked that I was able to get to various API endpoints running on different master/worker nodes.  In short, everything appeared to be normal except that all clusters were unavailable.

I then restarted the CP node on 1 of the clusters.  When it came back up, I restarted the etcd node on the same cluster.  Within a few seconds all clusters became green with status of Active.  Note that I only did this to a single cluster, yet all clusters were fixed.

**Environment information**
- Rancher v2.3.3 on-prem VM running Ubuntu 18.04, 8C/32G
- Single node
- 9 clusters, mix of on-prem and Azure clusters, various Kubernetes versions

**Comment by tryhardest** [comment]
Gosh this really scares me. Wish I could help here. Maybe if no errors it was a UI thing? Seems from that description they were alway active but displayed as unavailable, so were they down at any point?

**Comment by troy256** [comment]
All the nodes and the clusters themselves did seem to continue to run, so at least your existing workloads would not be affected.  But you couldn't view or manage any of the clusters.  Kubectl wouldn't return anything either.
