### ISSUE TITLE
Pods with ownerReference Set, Missing from Workloads View, Group By Namespace/Workload

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#24887]
This is more of a question of expected/undocumented behavior. I couldn't find in the docs where this is expected behavior, perhaps it is? If so, why does ownerReference make it hidden in these views?

**What kind of request is this (question/bug/enhancement/feature request):** question (maybe bug)

**Steps to reproduce (least amount of steps as possible):**

Deploy a Pod with ownerReference set.

**Result:**

If a pod is created by a controller and has the ownerReference set, it is hidden from the Group by Workload and Group By Namespace/Workload views.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.4-rc8
- Installation option (single install/HA): HA

**Comment by superseb** [comment]
This should be fixed in https://github.com/rancher/rancher/issues/22106, if not, please share exact YAML which can be used to reproduce.

**Comment by ekristen** [comment]
I will test 2.4 as soon as I can. Thanks.

**Comment by renperez** [comment]
@ekristen did you have any luck using 2.4? I am having the same issue in version 2.3.8
