### ISSUE TITLE
Custom listening port value not sticking

### ISSUE THREAD

**Issue by rockoo** [rancher/rancher#24885]
When setting a custom listening port in *mapping a port* section of a workload editor, the UI does not retain a set value on additional workload editing.

**Steps to replicate**
1. Edit workload
2. Under *port mapping* expose a container port and map it to any listening port
3. Click save
4. Edit the same workload again
5. Under *port mapping* custom set listening port states **random**

**Expected**
Listening port should be displayed to a value set

![1st edit](https://i.imgur.com/feuHRPY.png)

**Actual**
The set listening port is never shown (Even when clicking the pencil the port is always set to 0)

![2nd edit](https://i.imgur.com/SNVG5kh.png)
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`containers.index`|

**Comment by loganhz** [comment]
Fixed in 2.3.4 
Close in favor of https://github.com/rancher/rancher/issues/24551
