### ISSUE TITLE
Updating rancher url in settings does not update cluster kubeconfig file

### ISSUE THREAD

**Issue by rockoo** [rancher/rancher#24891]
When updating the rancher **server-url** in advanced settings it does not properly update actual kubeconfig for a cluster when trying to access through rancher kubectl.

**Steps to reproduce**
1. Go to settings -> advanced
2. Update server-url
3. Save settings
4. Launch kubectl and try running a command

**Expected**
Kubectl actual kubeconfig file should have an updated url (like it does when clicking Kubectl Config File button) and commands should work.

**Actual**
Kubeconfig file still retains the old URL.

**Additional**
If we change kubeconfig file manually from the UI kubectl the commands will work properly, however only for that active session. When the UI kubectl is closed and re-opened the file gets reset to an old URL value.

**KUBECONFIG**
![Kubeconfig](https://i.imgur.com/ihT1gae.png)

**KUBECTL CONFIG**
![Kubectl](https://i.imgur.com/Am7YGvR.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
This is part of https://github.com/rancher/rancher/issues/14731, the value is coming from non updated values. If you need to change it, there is a workaround that you can use in the issue but its not officially supported.
