### ISSUE TITLE
Can't assign mapped port to a specific port #

### ISSUE THREAD

**Issue by rockoo** [rancher/rancher#24895]
When trying to assign a mapped port on a workload the port assigned seems to be a random number.

**Steps to reproduce**
1. Open workload
2. On port map assing i.e. Container port 22 maps to NodePort i.e. 30947
3. Save workload
4. Check assigned port

**Expected**
Port inputted should be port assigned to a map.

**Actual**
Random port gets assigned to the workload.

![1](https://i.imgur.com/r8iUDd9.png)
![2](https://i.imgur.com/b7JCb65.png)
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`containers.run`|

**Comment by CodingWasaby** [comment]
rancher team said this bug is fixed in v2.3.4,
and u can change port by edit yaml in v2.3.3 #24551

**Comment by loganhz** [comment]
Sorry about that. It will be fixed in 2.3.4. Close in favor of https://github.com/rancher/rancher/issues/24551
