### ISSUE TITLE
Support for minimum rancher version

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2489]
We should be able to present only the catalog entries that the current rancher-server version supports.

As new rancher versions bring in new features, the templates using those features can get added under the catalog. These templates will work only on and after that specific rancher version.

So the catalog should list templates based on the rancher version provided to it, API should accept a filter to filter out the templates that are not compatible to the provided rancher version

**Comment by prachidamle** [comment]
@vincent99 UI needs to pass the filter /v1-catalog/templates?minimumRancherVersion_lte=
to use this property

**Comment by vincent99** [comment]
yes, next build (and when using a real release, there is no rancher version for build-master)

**Comment by vincent99** [comment]
This is in the `reskin` UI, but you need to run it against an actual release build for there to be a Rancher version available for me to send.
