### ISSUE TITLE
Do not enable create button for services/containers until a host is added

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#249]
Version: v0.12.0

If I try to add a container before deploying any hosts, the "Add Container" invalid message is "Invalid Source Image Name".  I had used the default image that loads with the page, so there should be no issue with the image name. 

The error message should indicate that a host needs to be created before attempting to add Containers.

![screen shot 2015-03-18 at 1 45 58 pm](https://cloud.githubusercontent.com/assets/11410997/6719123/c81cbeba-cd75-11e4-9f89-24b5b810c31c.png)

**Comment by vincent99** [comment]
The Add Container button just shouldn't be enabled if there aren't any active hosts, there's no point letting the user try to fill the form out.

**Comment by vincent99** [comment]
But it is also a bug that this is the error sent back from the API if you have no hosts to schedule...

**Comment by tfiduccia** [comment]
v0.18.2
No error message in create.  It creates now and if you go to that container's detail page it gives you a Removed - Failed to find a placement

Still need to disable the Add Container button if no hosts

**Comment by vincent99** [comment]
While still possible if you go looking for it, I think this is obsolete now with the splash screens telling you to add a host and it actually attempting to create and going to error instead of blowing up with a weird error...
