### ISSUE TITLE
[2.3.3] Cannot Delete monitoring-operator app after disabling all monitoring

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#24904]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Enable cluster monitoring, enable a project monitoring, disable the project monitoring, then disable cluster monitoring. 

**Result:**
The monitoring-operator still exists and cannot be removed. If I remove it, it will just be recreated.

We were testing the monitoring capabilities and are trying to switch back to the OOTB prometheus operator chart for the time being. If we cannot stop this operator from being re-deployed then we might have to just delete the cluster and re-import it.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.15.5

**Comment by loganhz** [comment]
`enableClusterMonitoring` field of the cluster   and `enableProjectMonitoring` filed of all projects inside the cluster should be `false`. Is that possible there is still one project with project level monitoring enabled?

**Comment by mitchellmaler** [comment]
Those two fields were all false. I checked /v3/cluster/c-m29gg and /v3/clusters/c-m29gg/projects but one thing I did notice was enableClusterAlerting on the cluster was still set the true. I am guessing this is used to manage the alert manager that is deployed and with it still enabled it kept the operator around even though monitoring was disabled. I updated the cluster spec by changing that to false the manually deleted the monitoring-operator app in the system project and now it isn't being recreated. Not sure why the enableClusterAlerting was left enable after I disabled the project and cluster monitoring.

**Comment by mitchellmaler** [comment]
nvm that was premature celebration where the monitoring-operator was re-deployed. The cluster has enableClusterAlerting and enableClusterMonitoring set to false and all project under /v3/clusters/c-m29gg/projects have enableProjectMonitoring set to false as well. I am not sure what else I can do to stop that app from starting up.

My steps are to disable all cluster and project monitoring, make sure the apps are deleted, delete all the coreos crds since the prom operator i am deploying will deploy them.

**Comment by mitchellmaler** [comment]
@loganhz I figured out the issue. So if you keep around alert group with prom notifier and or rules that use alert manager (not sure on this situation, need test again) then it will keep redeploying the operator and alert manager even after monitoring is completely disabled.  

I would categorize this as a bug since Prometheus is removed, alert manager should also be removed even if there are notifiers and alert groups with prom notifiers left over.

**Comment by nickvth** [comment]
When disabling project monitoring and cluster monitoring, pvc's are not removed. Also a bug.
