### ISSUE TITLE
[Pipeline] create failed. jnlp connect timeout

### ISSUE THREAD

**Issue by Qquanwei** [rancher/rancher#24908]
![image](https://user-images.githubusercontent.com/9263655/72139301-828dde00-33c9-11ea-8aa0-1435c4c242d8.png)

** jnlp logs

![image](https://user-images.githubusercontent.com/9263655/72139442-dac4e000-33c9-11ea-80c6-df36d7190d75.png)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

rancher 2.2.8

**Comment by Qquanwei** [comment]
Anyone can help me

**Comment by Qquanwei** [comment]
@superseb I need help

**Comment by superseb** [comment]
It tries to connect to the jenkins server. Can you confirm that it is running and it responds on that port? Does the overlay network work in general?

**Comment by Qquanwei** [comment]
@superseb Yes . The ip and port can connected in other pods ,  it works in almost time. only a few times it will be failure and continue a long times. 

the cluster network is correct in general. only jenkins slave can't connect network.

**Comment by superseb** [comment]
If networking is good between hosts, but it only can't connect to Jenkins at some point in time, what is the status of Jenkins at that point? Does it only not respond from the pod on that host or also from other pods? Does Jenkins log anything when a connection is refused? Is the host where Jenkins is running under load at that point when it happens?

**Comment by Qquanwei** [comment]
Jenkins pod is working . other pod can establish connect with `ip:port`. 
the Jnlp pod can't connect any ip during this time. `ping 8.8.8.8` or `ping 114.114.114.114` also timeout.

The Jenkins pod logs output like this. (I not save snapshot.)
```
 [1/100]
 [2/100]
...
...
...
 [100/100]
```

Then throw an error.

**Comment by Qquanwei** [comment]
![image](https://user-images.githubusercontent.com/9263655/72679920-2e80a900-3aef-11ea-9f5c-cca08fdb7c7d.png)

**Comment by Qquanwei** [comment]
![image](https://user-images.githubusercontent.com/9263655/72679940-64be2880-3aef-11ea-8673-e2293c61e92e.png)

**Comment by zhoutaoo** [comment]
I have the same problem
rancher 2.2.5

**Comment by Qquanwei** [comment]
@zhoutaoo check Network Plugin

**Comment by superseb** [comment]
Let us know if this still needs to be investigated.
