### ISSUE TITLE
Logging over Kafka -> doesn't support self-signed certificate when client authentication is enabled

### ISSUE THREAD

**Issue by bramamad** [rancher/rancher#24901]
After the Rancher V2.3 Upgrade we always get the message "Certificate verification failed, Kafka doesn't support self-signed certificate when client authentication is enabled" in the GUI if we select the cluster and the goto "Tools" / "Logging". If we press the "TEST" or "SAVE" button it's the same.

We activated the logging over Kafka under V2.2 without problems. And it still works fine. It's a GUI problem (kafka connection check ?). So, we cannot activate the logging over Kafka under V2.3 for new Kubernetes Cluster (Azure AKS).

Kafka is running under Docker but not inside Kubernetes.

What does that message mean. We don't use self signed certificates. Of course the root CA certificate (QuoVadis) is selfsigned !

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.4-rc8` UI: `v2.3.30` |
|Route|`global-admin.clusters.index`|

**Comment by bramamad** [comment]
I checked this problem once more with an older rancher V2.2 installation. Yes, that still works. It must be a new problem with V2.3. But what has changed there ?

**Comment by a-yiorgos** [comment]
Hey I stumbled on the very same problem today. However, the [Rancher2 documentation](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/logging/kafka/) clearly states that `Kafka does not support self-signed certificates when client authentication is enabled.`

So I am currently testing with a LetsEncrypt certificate on the Kafka server.
