### ISSUE TITLE
Add Ability To Create Projects via YAML Configs

### ISSUE THREAD

**Issue by cartyc** [rancher/rancher#24915]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature Request

**Steps to reproduce (least amount of steps as possible):**

Currently in order to create a Project in Rancher you need to go through either the UI or the Rancher CLI tool to create one. I think it would be great to be able to define a Project via configs files like namespace, ie

```
apiVersion: rancher.com/v1Projects
kind: Project
metadata:
  name: myproject
spec:
  resources: ...
```

We have been moving to embrace a more GitOps focused workflow and this is a big missing piece of the picture. All of our configs are stored in git and deploy seemlessly but we still need to have a separate workflow for project creation. This feature would be hugely beneficial to being able to keep the cluster state in sync with what is in source control.

**Other details that may be helpful:**

An end state would be the ability to define a Project object in a configuration file and deploy it like a normal Kubernetes Object ie `kubectl apply -f myrancherproject.yaml`

Thanks!

```
(paste the output here)
```

```
(paste the output here)
```

**Comment by manuschillerdev** [comment]
would love that as well!
@cartyc maybe a stupid question, but I could not find the docs to create a project from `rancher-cli`.
Would you mind pointing me in the right direction? :) 

Thanks!

**Comment by stecky** [comment]
+1 for this. I would love the ability to control the creation of projects using a flux monitored git repo
