### ISSUE TITLE
[helm]: Reject repos with local:// URLs in index.yaml

### ISSUE THREAD

**Issue by daenney** [rancher/rancher#24914]
When using Artifactory with Helm it has 2 types of repositories, local, and virtual. Virtual are the ones you have to use with Rancher, and will generate the `index.yaml` with full URLs that can then be used to fetch the charts.

If you add a Artifactory local Helm Chart by accident Rancher doesn't catch this but errors out when trying to deploy an app, with an "unsupported protocol local://". Now you have a broken app in installing state that you can't even delete (that's really 2 bugs).

When adding a catalog to Rancher it would be helpful to sanity check the URLs in the `index.yaml` that gets retrieved and error out, or warn the user, that this won't work.

**Comment by jef** [comment]
This also doesn't work with `file://`. I'm getting a stalled page like mentioned in https://github.com/rancher/rancher/issues/24927.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.5

**First pass**
I didn't reproduce this exactly, but added 2 catalogs containing an index.yaml with `file://` and `local://` urls. Using these catalogs, the UI goes into an indefinite loading state (spinner spinning and UI grayed out).

**Comment by brendarearden** [comment]
https://github.com/rancher/rancher/issues/24863. << this is likely fixed by the PR related to this issue

**Comment by daenney** [comment]
@brendarearden How do you mean? It's a fairly different issue, and there doesn't seem to be a PR associated with it?

**Comment by brendarearden** [comment]
My bad - I linked them the wrong way around - the refactoring completed to address this issue may have fixed a few other catalog issues we have been facing. I am going to remove my initial comment on this one link it the correct way.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head

* Add a catalog with a chart containing a `local://` and `file://` urls
* The chart does not sync and an error message is shown in the UI

**Comment by daenney** [comment]
For those looking for the code, #25920.
