### ISSUE TITLE
Monitoring - some graphs are missing in k8s 1.17 cluster

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#24916]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.3-4-rc8
- add a rancher launched k8s cluster with k8s version 1.17
- enable the cluster monitoring with chart version 0.0.7
- go to the cluster page to check graphs

**Result:**
The following 3 graphs are missing under the section Kubernetes Component Metrics:
- API Server Request Latency
- API Server Request Rate
- Scheduler E2E Scheduling Latency

**Other details that may be helpful:**
Those graphs show in a k8s 1.16 cluster with the same monitoring version (v0.0.7)

**Comment by maggieliu** [comment]
Pushing out to 2.4. Need discussion with @cloudnautique / @deniseschannon.

**Comment by deniseschannon** [comment]
Per @loganhz some metrics which we used are removed in 1.17. So we cannot collect them any more. We need to add some relabel rules in our monitoring chart. We fixed a similar issue in 1.16.
https://github.com/rancher/system-charts/pull/120

**Comment by jiaqiluo** [comment]
this issue is closed as https://github.com/rancher/rancher/issues/25201 is the latest version of the same problem.
