### ISSUE TITLE
Minor UI bug, information about Amazon, during Azure cluster creation step

### ISSUE THREAD

**Issue by Dmitry1987** [rancher/rancher#24922]
**What kind of request is this (question/bug/enhancement/feature request):**
UI bug report

**Steps to reproduce (least amount of steps as possible):**
Latest Rancher on Ubuntu on Azure cloud. But will be seen in any latest Rancher version probably, no matter where it runs.

**Result:**
Info box about Amazon when creating Azure cluster

![image](https://user-images.githubusercontent.com/9369080/72225313-0fa37500-3539-11ea-84f5-c9a0ab3ab293.png)

Very minor bug - but a user doesn't want to be confused about a message with Amazon information when creating Azure cluster (some might be exclusively hosted on Azure and it will confuse them "oh wait, did I press the right button, why does it say about Amazon".

**Comment by loganhz** [comment]
Thanks for the report. fixed in master branch

**Comment by izaac** [comment]
Rancher version `2.4 head (01/13/2020)` commit id: 6c488064c

Validated.
