### ISSUE TITLE
Loss of default gateway on all nodes

### ISSUE THREAD

**Issue by jhughes2112** [rancher/rancher#24921]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Installed RancherOS then rancher-agent on 3 nodes.
2) Installed MetalLB, Nginx-ingress following Adrian Goins' video, added hello-world workload.  
3) At this point, all nodes could communicate to the internet and each other.  Walk away for 10 hours.

**Result:**
All kubectl connection attempts fail to trust the SSL cert, and Rancher UI shows failures to contact the cluster, and curl https://node-ip:6443/ fails because local cert cannot be verified.  Upon ssh'ing to a node, cannot ping the internet at large because default gateway is missing.  I didn't remove it, so some interaction between MetalLB, ingress installation, flannel, or Rancher removed it from every node, but did so after some time.  Reboot of a node brought back default gateway

**Other details that may be helpful:**
Broken state:
```
rancher@hermes:~$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.0.0.0        0.0.0.0         255.0.0.0       U     202    0        0 eth0
10.42.0.0       10.42.0.0       255.255.255.0   UG    0      0        0 flannel.1
10.42.1.0       10.42.1.0       255.255.255.0   UG    0      0        0 flannel.1
10.42.2.0       0.0.0.0         255.255.255.0   U     0      0        0 cni0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker-sys
rancher@hermes:~$ ping 8.8.8.8
connect: Network is unreachable
rancher@hermes:~$ ping 10.0.0.199
PING 10.0.0.199 (10.0.0.199) 56(84) bytes of data.
64 bytes from 10.0.0.199: icmp_seq=1 ttl=64 time=7.26 ms
```
After a reboot:
```
rancher@hermes:~$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         USG             0.0.0.0         UG    202    0        0 eth0
10.0.0.0        0.0.0.0         255.0.0.0       U     202    0        0 eth0
10.42.0.0       10.42.0.0       255.255.255.0   UG    0      0        0 flannel.1
10.42.1.0       10.42.1.0       255.255.255.0   UG    0      0        0 flannel.1
10.42.2.0       0.0.0.0         255.255.255.0   U     0      0        0 cni0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker-sys
```
**Environment information**
- Rancher version: 2.3.2
- Installation option: single install

**Cluster information**
- Cluster type: None
- Machine type: Bare metal
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:38:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd87f
  Built:            Wed Jul 17 17:48:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Any idea what would cause all three nodes to drop their gateways?  The workloads kept working, and everything seemed up (it's just a load-balanced hello world), but I couldn't control the cluster anymore until I added gateways back to my nodes.  Very strange.

**Comment by superseb** [comment]
Can you provide any logging in the period it happened? Without any lead this will be pretty hard to debug.   Is this a custom cluster with manually added nodes or using node templates? What operating system? Does it consistently happen around 10 hours? Does it happen without MetalLB? Does it happen with MetalLB and a different CNI?

If all kubectl connections failed due to SSL error, what node is being used for running Rancher itself? And what certificate was presented?

**Comment by jhughes2112** [comment]
I don't have any logs from that period.  Those machines were rebuilt since then, and have not had the same packages (MetalLB, nginx ingress, hello world workload) added yet.  I don't recall the SSL issue going away after fixing the route, so I suspect the SSL error is a separate issue.

For pattern matching in the future:  
- bare metal with RancherOS installed to hdd
- bnx2x network drivers (one node had to be downgraded to the old .2.1.fw driver manually, the other two did not)
- Rancher UI running on a non-k8s machine running docker in the same subnet (10.0.0.x) as the nodes, but exposed via a public IP and DNS entry which the rancher-agents are looking for.  So the route being down makes them unable to call home to Rancher.

What logging would you like to see, assuming I can reproduce the issue?  The issue happened on all 3 nodes, which is incredibly suspicious.

**Comment by superseb** [comment]
Kubernetes components Docker container logging and system logging is probably a good start. Also, ruling out certain parts of the setup (does it happen on default 3 node custom cluster) can help here.

**Comment by superseb** [comment]
Let me know if this still needs help.
