### ISSUE TITLE
Rancher 2.3.3 private Helm repo from Jfrog Artifactory

### ISSUE THREAD

**Issue by martinounap** [rancher/rancher#24927]
Hi, could you please help?

We have created private helm chart. At first we connected Rancher to git helm chart repository, everything worked, but it was hard to version helm charts in git repository. So we started to create helm  package and pushed it to Artifactory private helm chart.

Now when we connect our Rancher 2.3.3 to Artifactory, it sees chart, but when we try to click on it, to start installation process, it keeps only loading chart. From Chrome console I see error:

`component.js:250 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at n.initPreviewTab (component.js:250)
    at n.initTemplateModel (component.js:245)
    at component.js:66
    at t.invoke (backburner.js:341)
    at e.t.flush (backburner.js:233)
    at e.t.flush (backburner.js:437)
    at e.n._end (backburner.js:1013)
    at _boundAutorunEnd (backburner.js:653)`

When I add same Artifactory helm repository to Rancher 2.2.9, it works.

Rancher 2.3.3 UI:
![image](https://user-images.githubusercontent.com/9929895/72241532-ba766a80-35ef-11ea-8177-b705c8b3f8a7.png)

Rancher 2.2.9 UI:
![image](https://user-images.githubusercontent.com/9929895/72241604-e5f95500-35ef-11ea-8053-9cd757fbdc3a.png)

**Comment by superseb** [comment]
A similar error was reported (https://github.com/rancher/rancher/issues/24912) and merged into https://github.com/rancher/rancher/issues/24914, can you share what Helm repository type in Artifactory you are adding?

**Comment by martinounap** [comment]
We are adding local repo Helm type with simple-default layout.

![image](https://user-images.githubusercontent.com/9929895/72243504-cb75aa80-35f4-11ea-9f3d-b6797f8130ab.png)

**Comment by martinounap** [comment]
Now I created also virtual repo where I added local repo. 
I checked that urls inside index.yaml are correct, but still Rancher UI hangs.

**Comment by martinounap** [comment]
Ok , my mistake. With virtual repo I do not see any charts.
When I click refresh in catalogs menu, it keeps refreshed nex to chart repo, and it does not change.

![image](https://user-images.githubusercontent.com/9929895/72245589-96b82200-35f9-11ea-8cb4-bc1359cc45be.png)

But from Apps menu I do not see apps from Artifactory virtual Helm repository.

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/24914
