### ISSUE TITLE
rancher cli move ns to project, rancher server logs panic serviing api request

### ISSUE THREAD

**Issue by zhongguanqun** [rancher/rancher#24928]
*Describe your issue here*
通过rancher cli进行操作：迁移ns到项目下
![image](https://user-images.githubusercontent.com/4767546/72245465-99cc0600-362b-11ea-8b70-07f0f8875402.png)

rancher server log 报错
![image](https://user-images.githubusercontent.com/4767546/72245516-b2d4b700-362b-11ea-813a-601985aeee6e.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.2` UI: `v2.3.22` |
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
What Rancher CLI version is this on? Any other steps to reproduce?

**Comment by zhongguanqun** [comment]
# rancher cli operatation list
./rancher namespace move test20200117-2 c-wjzlt:p-v67nr
FATA[0000] Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [] from [https://rancher.xxx.com/v3/cluster/c-wjzlt/namespaces/test20200117-2?action=move]

# rancher server audit-level=3 info
{"auditID":"6fea217a-d34f-4a71-a63c-a424aabb99d3","requestURI":"/v3/cluster/c-wjzlt/namespaces/test20200117-2","user":{"name":"user-fntfv","group":["system:authenticated"]},"method":"GET","remoteAddr":"10.108.161.31:23341","requestTimestamp":"2020-01-17T09:01:16Z","responseTimestamp":"2020-01-17T09:01:16Z","responseCode":200,"requestHeader":{"Accept-Encoding":["gzip"],"Connection":["close"],"Impersonate-Group":["system:authenticated"],"Impersonate-User":["user-fntfv"],"User-Agent":["Go-http-client/2.0"]},"responseHeader":{"Content-Encoding":["gzip"],"Content-Type":["application/json"],"Expires":["Wed 24 Feb 1982 18:42:00 GMT"],"X-Api-Schemas":["https://rancher.xxx.com/v3/cluster/c-wjzlt/schemas"]},"responseBody":{"actions":{"move":"https://rancher.xxx.com/v3/cluster/c-wjzlt/namespaces/test20200117-2?action=move"},"baseType":"namespace","created":"2020-01-17T08:39:01Z","createdTS":1579250341000,"creatorId":null,"id":"test20200117-2","links":{"remove":"https://rancher.xxx.com/v3/cluster/c-wjzlt/namespaces/test20200117-2","self":"https://rancher.xxx.com/v3/cluster/c-wjzlt/namespaces/test20200117-2","update":"https://rancher.xxx.com/v3/cluster/c-wjzlt/namespaces/test20200117-2","yaml":"https://rancher.xxx.com/v3/cluster/c-wjzlt/namespaces/test20200117-2/yaml"},"name":"test20200117-2","projectId":null,"state":"active","transitioning":"no","transitioningMessage":"","type":"namespace","uuid":"fb2e66ab-3906-4133-86cb-881b14d8f634"}}
{"auditID":"a40e6c33-2bdd-4872-948c-235ff338c863","requestURI":"/v3/cluster/c-wjzlt/namespaces/test20200117-2?action=move","user":{"name":"user-fntfv","group":["system:authenticated"]},"method":"POST","remoteAddr":"10.108.161.30:23347","requestTimestamp":"2020-01-17T09:01:16Z","responseTimestamp":"2020-01-17T09:01:16Z","responseCode":500,"requestHeader":{"Accept-Encoding":["gzip"],"Connection":["close"],"Content-Length":["31"],"Content-Type":["application/json"],"Impersonate-Group":["system:authenticated"],"Impersonate-User":["user-fntfv"],"User-Agent":["Go-http-client/2.0"]},"responseHeader":{"Content-Encoding":["gzip"]},"requestBody":{"projectId":"c-wjzlt:p-v67nr”}}

# rancher server error log
2020/01/17 09:01:15 [INFO] Registering monitoring for cluster "c-wjzlt"
2020/1/17 下午5:01:15 2020/01/17 09:01:15 [INFO] Registering istio for cluster "c-wjzlt"
2020/1/17 下午5:01:15 2020/01/17 09:01:15 [INFO] Starting cluster controllers for c-wjzlt
2020/1/17 下午5:01:16 2020/01/17 09:01:16 [ERROR] Panic serving api request:
2020/1/17 下午5:01:16 goroutine 84266 [running]:
2020/1/17 下午5:01:16 runtime/debug.Stack(0xc0164311c0, 0x2d33080, 0x3952110)
2020/1/17 下午5:01:16 /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
2020/1/17 下午5:01:16 github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x39f4b40, 0xc06309b220)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:175 +0x7a
2020/1/17 下午5:01:16 panic(0x2d33080, 0x3952110)
2020/1/17 下午5:01:16 /usr/local/go/src/runtime/panic.go:522 +0x1b5
2020/1/17 下午5:01:16 github.com/rancher/rancher/pkg/api/customization/namespace.ActionWrapper.ActionHandler(0xc000e9e880, 0xc14562635a, 0x4, 0xc0ecf51300, 0xc0c74b47e0, 0xc001da23c0, 0xc051af61e0)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/pkg/api/customization/namespace/namespace.go:101 +0x602
2020/1/17 下午5:01:16 github.com/rancher/rancher/vendor/github.com/rancher/norman/api.handleAction(0xc0ecf51300, 0xc0c74b47e0, 0x0, 0x0)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:263 +0x62
2020/1/17 下午5:01:16 github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).handle(0xc00075c000, 0x39f4b40, 0xc06309b220, 0xc0e88abe00, 0xc0e88abe00, 0xc09ad1a000, 0xc0508da180)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:251 +0xd2
2020/1/17 下午5:01:16 github.com/rancher/rancher/vendor/github.com/rancher/norman/api.(*Server).ServeHTTP(0xc00075c000, 0x39f4b40, 0xc06309b220, 0xc0e88abe00)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/api/server.go:180 +0x7d
2020/1/17 下午5:01:16 github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000dbcb40, 0x39f4b40, 0xc06309b220, 0xc0e88abc00)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe3
2020/1/17 下午5:01:16 github.com/rancher/rancher/pkg/auth/requests.authHeaderHandler.ServeHTTP(0x39d7100, 0xc0000c1b60, 0x39afa80, 0xc000dbcb40, 0x39e6cc0, 0xc000e9e880, 0x39d70c0, 0xc000dd3290, 0x39f4b40, 0xc06309b220, ...)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/pkg/auth/requests/filter.go:110 +0x72b
2020/1/17 下午5:01:16 github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP(0x39aecc0, 0xc000df0cc0, 0x39f4b40, 0xc06309b220, 0xc0e88abc00)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa1
2020/1/17 下午5:01:16 github.com/rancher/rancher/pkg/audit.auditHandler.ServeHTTP(0x39aee80, 0xc0000df130, 0xc000472c10, 0x3a07c80, 0xc0bd5d2160, 0xc0e88abb00)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/pkg/audit/filter.go:47 +0x2d4
2020/1/17 下午5:01:16 github.com/rancher/rancher/server/responsewriter.ContentType.func1(0x39f5600, 0xc0508da030, 0xc0e88abb00)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/server/responsewriter/content.go:33 +0x93
2020/1/17 下午5:01:16 net/http.HandlerFunc.ServeHTTP(0xc0005626a0, 0x39f5600, 0xc0508da030, 0xc0e88abb00)
2020/1/17 下午5:01:16 /usr/local/go/src/net/http/server.go:1995 +0x44
2020/1/17 下午5:01:16 github.com/rancher/rancher/server/responsewriter.Gzip.func1(0x3a07a40, 0xc0dca62b60, 0xc0e88abb00)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/server/responsewriter/gzip.go:60 +0x1b6
2020/1/17 下午5:01:16 net/http.HandlerFunc.ServeHTTP(0xc0005626c0, 0x3a07a40, 0xc0dca62b60, 0xc0e88abb00)
2020/1/17 下午5:01:16 /usr/local/go/src/net/http/server.go:1995 +0x44
2020/1/17 下午5:01:16 github.com/rancher/rancher/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000dbc9c0, 0x3a07a40, 0xc0dca62b60, 0xc0e88ab900)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/mux/mux.go:212 +0xe3
2020/1/17 下午5:01:16 github.com/rancher/rancher/pkg/dynamiclistener.(*Server).cacheIPHandler.func1(0x3a07a40, 0xc0dca62b60, 0xc0e88ab900)
2020/1/17 下午5:01:16 /go/src/github.com/rancher/rancher/pkg/dynamiclistener/server.go:436 +0x101
2020/1/17 下午5:01:16 net/http.HandlerFunc.ServeHTTP(0xc0036457e0, 0x3a07a40, 0xc0dca62b60, 0xc0e88ab900)
2020/1/17 下午5:01:16 /usr/local/go/src/net/http/server.go:1995 +0x44
