### ISSUE TITLE
[feature request] extend rancher `affinity:container_label` with count option

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2492]
My use case is described in #2478
Currently `container_label_soft_ne` matches hosts where <N=1 containers are running, but why not to configure this N parameter if i would like, for example, to deploy 6 instances on 3 hosts by 2(N=2)? Or round robin algorithm when rancher pick host with minimum number of specified containers running?

**Comment by stratosgear** [comment]
I also have a similar use case.  Deploy 3 instances of a service in each host, for example...

Extra points if 3 more instances are added automatically when I bring up another host.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
