### ISSUE TITLE
[CIS] Move benchmark version info to k-d-m

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#24935]
Currently, the benchmark version is in security-scan repo. Need to move this to https://github.com/rancher/kontainer-driver-metadata

**Comment by leodotcloud** [comment]
@sowmyav27 with this change, all the existing automation tests should pass as before.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `92117c9bd`**

on the rancher server management plane
```
kubectl get cisconfigs.management.cattle.io --all-namespaces
NAMESPACE            NAME      AGE
cattle-global-data   default   27m
cattle-global-data   v1.15     27m
root@64571c9b4e53:/var/lib/rancher# kubectl get cisconfigs.management.cattle.io --all-namespaces
NAMESPACE            NAME      AGE
cattle-global-data   default   27m
cattle-global-data   v1.15     27m
```

**Comment by sowmyav27** [comment]
Verified on latest master-head commit id - `7912bfdfa`

- Made changes to this file -- https://github.com/rancher/kontainer-driver-metadata/blob/dev/rke/cis_config.go (forked it to my repo)
- Added the following to `loadCisConfigParams`

```
"v1.16": {
			BenchmarkVersion: "cis-1.4",
		},
```

- And on master head, pointed the KDM to my repo/branch
- Refreshed the KDM
- Deployed cluster 1.16 k8s
- Run CIS scan
- The version reported in the Scan report was `cis-1.4` 
- For a k8s v1.17 and v1.15, rke-cis-1.4 version of scan was run.
