### ISSUE TITLE
[Feature Request] Ability to backup etcd snapshots to local s3 minio bucket

### ISSUE THREAD

**Issue by laxmanpradhan** [rancher/rancher#24938]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
- I have a local minio instance running, it has a node port IP (192.168.1.201:31456), and internal cluster IP (http://10.42.0.6) and an internal URL (minio.minio.svc.cluster.local)
- try to add this as a storage target for etcd backups in the cluster settings, use minio as the region and one of the above addresses as the end point along with the appropriate access and secret keys

**Result:**
It will give one of these errors depending on endpoint:

192.168.1.201:31456:
 'Unable to validate S3 backup target configration: Head https://192.168.1.201:31456/rancher-etcd/: dial tcp 192.168.1.201:31456: connect: connection refused'
(since I run locally I don't have an https certificate on it)

There should be an option to at disable HTTPS checking so that I can connect to a local S3 storage. 

**Other details that may be helpful:**
Right now I collect all my cluster backups on the minio instance (I use velero for the workloads), then I use rsync to copy the minio storage to offsite backups. This allows be to be completely vendor agnostic so I can easily use any type of storage for my backups. It also makes it easy to create local offline backups. 

Note that the minio instance is not accessible over the internet so it doesn't make sense to put it behind my reverse proxy so that it can get a certificate to enable HTTPS. 

**Environment information**
- Rancher 2.3.3
- Kubernetes 1.16
- 3 nodes running RancherOS VMs in Proxmox
- Using
-  a minio docker installed locally as a workload (single pod)

Rancher is installed on one of the kubernetes node nut not part of the internal kubernetes network (single instance installation), so it makes sense that it can't access the internal cluster IPs, but it should be able to connect via the nodeIP:nodeport.

**Comment by superseb** [comment]
The request for non HTTPS S3 endpoint is covered in https://github.com/rancher/rke/issues/1359. Even when configuring it, it should respond as a HTTPS request to a non HTTPS endpoint, not with connection refused. 

To troubleshoot that part, can you curl the endpoint from the host and from inside the container to see if it works?

**Comment by laxmanpradhan** [comment]
So my setup is as follows:
I have 3 VMs running as kubernetes workers: cube1, cube2, cube3. On the cube1 VM (192.168.1.201), I also have rancher installed as a single node install. So the rancher container is installed there. The minio instance is also exposed via node port on that same node (192.168.1.201:31012)

The base OS on each node is RancherOS which unfortunately does not come with the curl command. That being said, since that host node is 192.168.1.201 and the minio server is running on 192.168.1.201:31012 it is likely to work (I can access the webUI with no issues at http://192.168.1.201:31012 and my other applications on the cluster itself such as velero have no issues accessing minio at that IP:port).

For the error above, I copied the wrong error, these are the errors I get based on the endpoint I use: 


If I try to curl from within the rancher docker itself, I get the following:
```
56ed6ab720e6        rancher/rancher:latest                        "entrypoint.sh"          3 weeks ago         Up 18 hours         0.0.0.0:9005->80/tcp, 0.0.0.0:9006->443/tcp   musing_dubinsky
[rancher@cube1 ~]$ docker exec -it 56ed6ab720e6 bash
root@56ed6ab720e6:/var/lib/rancher#
----------------------------
root@56ed6ab720e6:/var/lib/rancher# curl http://192.168.1.201:31012
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>15E98F3793BB93BE</RequestId><HostId>9ba56df8-6cfa-4586-88ed-8d4834620a46</HostId></Error>
```

**Comment by superseb** [comment]
Ok, that error makes sense as it requires HTTPS and it doesn't serve as HTTPS. This can be merged into https://github.com/rancher/rke/issues/1359 and be tracked there.
