### ISSUE TITLE
Issue with helper text for CNI Plugin MTU config

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24949]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create an rke cluster/rke template
- The helper text for CNI Plugin MTU config is different from that on 2.3-head. the lines seem closer

**Master-head**
<img width="1502" alt="Screen Shot 2020-01-13 at 4 26 40 PM" src="https://user-images.githubusercontent.com/26032343/72303567-89635d80-3622-11ea-91da-0e7a623ae863.png">

**2.3-head**
<img width="1452" alt="Screen Shot 2020-01-13 at 4 15 18 PM" src="https://user-images.githubusercontent.com/26032343/72303555-81a3b900-3622-11ea-81e0-75ef9b9739e2.png">

**Expected Result:**
Text be placed on master-head UI as it is for 2.3-head

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - ui tag: latest2
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
This is to be expected. This area underwent some markup changes that did not occur in 2.3 as a result of another change. I think we can close this.

**Comment by sowmyav27** [comment]
Closing issue based on this comment https://github.com/rancher/rancher/issues/24949#issuecomment-574242295
