### ISSUE TITLE
Wrong certs info under system project in 2.1.x HA Let's Encrypt

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#24945]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug 

**Steps to reproduce (least amount of steps as possible):**
- Install either Rancher v2.1.x in HA mode with the LetsEncrypt option
- go to `local` cluster -> `system` project -> `Resources` -> `Certificates` 
<img width="953" alt="Screen Shot 2020-01-13 at 2 08 12 PM" src="https://user-images.githubusercontent.com/6218999/72292221-2a93e900-360e-11ea-90c8-91e92b4fc9b9.png">

**Result:**
- the `Domain Names` and `Expires` info are missing for `tls-rancher` and `tls-rancher-ingress`
- Viewing  `tls-rancher` and `tls-rancher-ingress` in API shows that they are not actually certificates but Rancher's own type `namespacedCertificate` 
- Checking in Kubectl shows that their type is `kubernetes.io/tls`, and there is no domain and expire info in them 
```
➜ k get secrets -n cattle-system
NAME                            TYPE                                  DATA   AGE
tls-rancher                     kubernetes.io/tls                     2      20m
tls-rancher-ingress             kubernetes.io/tls                     3      20m
```

-  the real certificates issued by Let's Encrypt is the type of `certificates.certmanager.k8s.io`
```
➜ k get certificates.certmanager.k8s.io -n cattle-system
NAME                  READY   SECRET                AGE
tls-rancher-ingress   True    tls-rancher-ingress   26m
```

**Comment by deniseschannon** [comment]
2.1 is EOL and therefore this won't be fixed. https://rancher.com/support-maintenance-terms/
