### ISSUE TITLE
Retain container IP address & create_index on service upgrade

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#2494]
As discussed in https://github.com/rancher/compose-templates/issues/19, we came to the conclusion that a service upgrade should give the ability to optionally retain the previous container IP address as well as the create_index.

A typical scenario that requires the above is a Zookeeper cluster.

In fact, a Zookeeper cluster requires the nodes IDs not to change as well as the their IP addresses.

Also, components that heavily rely on Zookeeper (e.g. Kafka) would need to be restarted if the Zookeeper nodes have new IP addresses, which is quite a big thing.

**Comment by ndelitski** [comment]
+1 usefull for scenario when you have stack with webapp+nginx, updating webapp service separately causes nginx pointing to previous app ip

**Comment by sangeethah** [comment]
Tested with server version - V0.57.0-rc4

We have the option to enable "Retain Ip" under "Networking" tab when creating services.
A new metadata field - service_index is introduced for containers.

When services are created with the retainIp flag enabled , IP address & service_index of the containers of the service remain the same even after the following actions are performed on the service:

1. Delete one of the container of the service. When service reconcile is triggered, the new container created will have the same container name  and same ip address.

2. Containers get "unhealthy" and get marked for deletion. When service reconcile is triggered, the new container created will have the same container name  and same ip address.

3. When service gets upgraded/ rolled back , the  IP address & service_index of the containers are preserved.

@m4ce , this feature will be available in the next rancher server release.

**Comment by m4ce** [comment]
@sangeethah,
I tested the feature and it works as expected. A few cosmetic issues:

- ipRetain is not present in the UI when viewing the compose config
- ipRetain is always set to null in the API when creating a service with rancher-compose. Instead, it's set to true when doing it from the UI.

Cheers,
Matteo

**Comment by deniseschannon** [comment]
Compose Config:
https://github.com/rancher/rancher/issues/3486

Rancher-compose Support:
https://github.com/rancher/rancher/issues/3498

**Comment by nunofgs** [comment]
@sangeethah: was service_index added to the main rancher api by any chance?

**Comment by deniseschannon** [comment]
@nunofgs No, service_index is not part of the main rancher API.
