### ISSUE TITLE
Vsphere cluster not provisioning

### ISSUE THREAD

**Issue by skbki** [rancher/rancher#24950]
**What kind of request is this (question/bug/enhancement/feature request):bug

**Steps to reproduce (least amount of steps as possible):
1. Configure vsphere credentials and template
2. Create vshpere provisioned cluster

**Result:**
Machine is being created and configured correctly is not being powered on

NodeController c-hsrrk/m-gr7kv [node-controller] failed with : Error creating machine: Error in driver during machine creation: vm 'DC/vm/K8S/prod-k8s-1-master-1' not found

2020/01/14 01:25:52 [INFO] [node-controller-docker-machine] About to remove prod-k8s-1-master-1
2020/01/14 01:25:52 [INFO] [node-controller-docker-machine] WARNING: This action will delete both local reference and remote instance.
2020/01/14 01:25:52 [INFO] [node-controller-docker-machine] Successfully removed prod-k8s-1-master-1
2020/01/14 01:25:52 [INFO] Removing node prod-k8s-1-master-1 done

vm is not being deleted, after that rancher starts creating new vm with same name

2020/01/14 01:26:08 [ERROR] NodeController c-hsrrk/m-7f7cs [node-controller] failed with : Error creating machine: Error in driver during machine creation: The name 'prod-k8s-1-master-1' already exists.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

Rancher Server | v2.3.3
User Interface | v2.3.25
Machine | v0.15.0-rancher20-1
vcenter 6.5u2 6.7u3

- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vmware
- Machine type (cloud/VM/metal) and specifications (CPU/memory):vm 4cores 16g memory
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by Oats87** [comment]
Can you show your node template configuration?

**Comment by skbki** [comment]
After update to 2.3.3 I recreated my templates to use dropdown menus.

![K8S](https://user-images.githubusercontent.com/50640643/72331693-e7db1b00-36b8-11ea-8467-9406c3dd8fc4.png)

**Comment by Oats87** [comment]
@skbki Can you update to Rancher `v2.3.4` and re-try provisioning? There were a lot of vSphere bug fixes that went into this release.
