### ISSUE TITLE
UI for Shibboleth with OpenLDAP Search

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#24957]
Original Issue: https://github.com/rancher/rancher/issues/24235

The UI would be to recreate the openldap configurations in a sub section of the ping saml provider. ping today has:

1. Configure Shibboleth
2. Test and Enable

And will probably need to be"
1. Configure Shibboleth
2. LDAP (closed and optional)
3. Test and Enable.

**Comment by deniseschannon** [comment]
Note: We are adding in Shibboleth as a new auth provider as well as adding the additional ability to use openLDAP search

**Comment by izaac** [comment]
This feature is available from 2.4 master-head commit id: e11d47814 

Bugs found when testing this feature are being tracked as separate issues.
