### ISSUE TITLE
Rancher Logging creates extreme amount of data/loglines

### ISSUE THREAD

**Issue by Michaellaneous** [rancher/rancher#24954]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Install Rancher
Create new Cluster and install an ELK Stack
Enable Cluster or System Logging on any cluster

**Result:**
Rancher sends an enourmous amount of data to the ELK stack - millions of docs in a matter of minutes.

**Other details that may be helpful:**

**Environment information**
- Rancher version: 2.2.8
- Installation option: HA

**Cluster information**
- Cluster type: vSphere Cluster
- Machine type: VM with RancherOS
- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GitCommit:"3e4f6a92de5f259ef313ad876bb008897f6a98f0", GitTreeState:"clean", BuildDate:"2019-08-05T09:22:00Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version:

```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:24:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:25:33 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by nanorobocop** [comment]
When you enable logging first time, fluentd will flush all existing logs to Elastic. It could be really big amount of data.
After existing logs flushed, further amount of logs will depend on workload inside your cluster.
For that case, do you know all applications running on that cluster? Maybe some of them has debug enabled or scaled out to hundreds of replicas.

**Comment by Michaellaneous** [comment]
As mentioned, I have tried this with a new cluster that barely has anything running in it.
Furthermore, the logs are split into days, and only the latest will grow massively.

**Comment by nanorobocop** [comment]
Can you distinguish those logs by container/image/filename.
For example, in Kibana it's possible to create visual distribution by one of parameter.

**Comment by Michaellaneous** [comment]
@nanorobocop Very good suggestion. I played around with visualization and the spam comes from:
`kubernetes.pod_name:rancher-logging-fluentd-7h88l`

with the line
`#0 Detected ES 7.x or above: `_doc` will be used as the document `_type`.`

I will try to figure out what causes this; do you have any pointers?

**Comment by nanorobocop** [comment]
Seems to be related to this issue https://github.com/uken/fluent-plugin-elasticsearch/issues/589
Do you have ability to change Rancher version (or rebuild existing version) or Elastic endpoint with 6.x version?

**Comment by Michaellaneous** [comment]
@nanorobocop I'll install my own fluentd version, since an Rancher upgrade is not acceptable on our productive enviornment for now.

I'll close this since it's just the issue you linked anyway. I wasn't sure what to look for, so thanks for pointing it ou.
