### ISSUE TITLE
When upgrading Istio to 1.4.3 the API returns a 422 error

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#24956]
Version: v2.3.3 -> upgrade to v2.3.4-rc8

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Launch Rancher v2.3.3, create a cluster and deploy the default istio version
- Upgrade to Rancher v2.3.4-rc8 and upgrade montioring - notice this occurrs without any issues
- Upgrade istio to 1.4.3 via the Istio config page -- notice it does complain with an issue in the UI

**Result:**
When upgrading istio to v1.4.3 the second you click that version from the dropdown the API returns the following and we see the following error bubble in the UI:
`{"baseType":"error","code":"InvalidBodyContent","message":"rancher max version exceeded","status":422,"type":"error"}`
![image](https://user-images.githubusercontent.com/45179589/72370526-b154ce80-36bf-11ea-8e90-ad5387a34586.png)

**Other details that may be helpful:**
Endpoint: v3/project/c-CLUSTERID:p-PROJECTID/apps/p-dllrc:cluster-istio?action=upgrade
We POST to this endpoint and get an HTTP 422 with the response above.
The request payload looked normal to me; relevant snippet from answers:

`externalId: "catalog://?catalog=system-library&template=rancher-istio&version=0.1.1"`

**Environment information**
single-node rancher install and upgrade

**Other information**
This issue did not happen before the following change: https://github.com/rancher/system-charts/pull/148
However, I'm not convinced the change is necessarily responsible.

**Comment by davidnuzik** [comment]
Based on QA discussion we're going to use this issue to track the fixing of this issue and our testing of upgrade testing.

Other PRs:
https://github.com/rancher/system-charts/pull/147
https://github.com/rancher/system-charts/pull/148

To check: ensure again with upgrade check that issue is resolved. Both project and cluster-level monitoring should upgrade successfully. Istio should upgrade successfully.

**Comment by westlywright** [comment]
A fix is available in `latest2` and `latest-2.3`

**Comment by davidnuzik** [comment]
Version: v2.3.3 -> v2.3.4-rc9 upgrade (single-node)

The reported bug is fixed. We no longer observe both the HTTP 422 error on the POST to upgrade istio and we do not observe the UI red error bubble as well of course.

I executed checks on both cluster monitoring and istio both pre and post upgrade:
v2.3.3 (pre-upgrade)
- Ensure I can install v0.0.6 cluster monitoring, all workloads deploy correctly, smoke test cluster charts and ensure they all work, smoke test grafana and ensure links work on cluster page.
- Ensure I can install v0.1.1 istio (1.3.3), all workloads deploy correctly, smoke test istio via test app and ensure all the charts and kiali graph work, smoke test the other links (kialia, jaeger, graphana, prometheus).

v2.3.4-rc9 (post-uprade)
- Ensure monitoring can be upgraded to v0.0.7 without any issues, same checks (check workloads, smoke test, etc)
- Ensure istio can be upgraded to v1.4.3 without any issues, ENSURE BUG NO LONGER OCCURS, and execute the other checks like before (check workloads upgraded, smoke tests, etc)

I didn't identify any issues with my checks against cluster monitoring and Istio.

**Comment by jiaqiluo** [comment]
The validated for monitoring template version is done in the path from v2.3.3 to v2.3.4-rc9

Steps:
- in v2.3.3, check the monitoring versions in the dropdown list are 0.0.4, 0.0.5, 0.0.6
<img width="717" alt="Screen Shot 2020-01-14 at 4 57 42 PM" src="https://user-images.githubusercontent.com/6218999/72397486-432efc80-36fd-11ea-8281-6cbc4777f22a.png">

- enable cluster monitoring  0.0.6 and confirm everything works 
- enable project monitoring  0.0.6 and confirm everything works 
- upgrade Rancher to v2.3.4-rc9
- check cluster and project monitoring continue working 
- add a new cluster, check the monitoring versions in the dropdown list is 0.0.7 only 
<img width="770" alt="Screen Shot 2020-01-14 at 6 34 34 PM" src="https://user-images.githubusercontent.com/6218999/72397555-78d3e580-36fd-11ea-98a9-3e2466fd411f.png">

- upgrade cluster monitoring to 0.0.7 and confirm everything works 
- upgrade proejct monitoring to 0.0.7 and confirm everything works
