### ISSUE TITLE
Monitoring & Istio system charts do not have min/max versions set

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#24959]
rancher/rancher:v2.3.4-rc8

Monitoring & Istio system charts should have min/max version set in the charts to only show the latest version. 

When validating, check both fresh install & upgrade scenarios

**Comment by bmdepesa** [comment]
https://github.com/rancher/system-charts/pull/147
https://github.com/rancher/system-charts/pull/148

**Comment by davidnuzik** [comment]
We decided to close in favor of https://github.com/rancher/rancher/issues/24956 where we will track not just that fix but our testing efforts.
