### ISSUE TITLE
CIS Scans report fails to load

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24952]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluser
- Go to Cluster --> Tools --> CIS Scans
- Run Scan
- Click on the generated scan report

**Actual Result**
The page is stuck loading
Error seen in console:
```
Uncaught (in promise) TypeError: (0 , l.extractUniqueStrings) is not a function
    at n.getNodeNamesFromNodeType (clusterscan.js:179)
    at controller.js:138
    at Array.map (<anonymous>)
    at n.<anonymous> (controller.js:135)
    at n.i.get (metal.js:3614)
    at $e (metal.js:2720)
    at t.r.compute (glimmer.js:565)
    at t.value (glimmer.js:388)
    at e.r.value (runtime.js:5115)
    at Pt (glimmer.js:5284)
```
<img width="1668" alt="Screen Shot 2020-01-13 at 9 35 56 PM" src="https://user-images.githubusercontent.com/26032343/72316985-b62c6a80-364c-11ea-91dd-ba45a9279944.png">

**Expected Result:**
Report should be displayed successfully

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `88fcc20ad`, ui tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by sowmyav27** [comment]
**Verified on master-head - ui tag: latest2**

**Steps:**

- Deploy a cluser
- Go to Cluster --> Tools --> CIS Scans
- Run Scan
- Click on the generated scan report
- Detailed scan report is open/available. No error is seen in console/UI
