### ISSUE TITLE
[rancher-dns] Figuring out Rancher DNS

### ISSUE THREAD

**Issue by faddat** [rancher/rancher#2495]
The external DNS, that is..

So I've rather evolved our rancher deployment-- at least, I'd like to have rather evolved it; it's not quite there yet.  This is actually one of the final pieces.  About half of our nodes are NAT'd / Firewalled, though.  How can we still get our services published using this code?  Is it capable of serving as an "omni-endpoint," where all of our services could exit the Rancher network through it?

**Comment by deniseschannon** [comment]
I'm not exactly sure what you're trying to do, but in our latest release, we announced what the rancher-dns repo is doing. https://github.com/rancher/rancher/issues/1675

The docs of how to use it is: http://docs.rancher.com/rancher/rancher-services/dns-service/
