### ISSUE TITLE
CIS scan: Skip file ownership checks for etcd cert and key file, when etcd process is run as a custom user

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#24964]
The test 1.4.19 checks `Ensure that the Kubernetes PKI directory and file ownership is set to root:root (Scored)`

But other CIS tests (1.4.11 and 1.4.12) need etcd process to be run by a etcd:etcd user - due to this 
when etcd process is run by etcd:etcd user, the cert and key file that etcd needs, needs to be owned by etcd user .

Thus this will break the 1.4.19 test - these two tests contradict each other. We should skip the 1.4.19 ownership check for the etcd specific cert/key files and only apply the check to rest of the certs.

Also logged this issue under the cis charts:
https://github.com/rancher/security-scan/issues/10

**Comment by sowmyav27** [comment]
Will verify when this issue -- https://github.com/rancher/rancher/issues/25642 is fixed

**Comment by sowmyav27** [comment]
**On master-head - commit id: `bfa3e1c8a`**

- On a 1.17 cluster - RKE-CIS-1.4 Hardened run, 1.4.19 is seen as "Pass"

- But `1.4.19` is NOT available in this list
<img width="1284" alt="Screen Shot 2020-03-08 at 3 07 17 PM" src="https://user-images.githubusercontent.com/26032343/76172020-9bf3a200-614e-11ea-9283-45048fcb392f.png">

@leodotcloud Could you confirm how are we skipping this test?

**Comment by leodotcloud** [comment]
@sowmyav27 The test script has been updated to get this test to pass. See changes here: https://github.com/rancher/security-scan/pull/11/commits/ec0ff6be969f85fb3479adb985745408cbda9e13

**Comment by sowmyav27** [comment]
Closing the issue
