### ISSUE TITLE
[go-rancher] what exactly is this?

### ISSUE THREAD

**Issue by faddat** [rancher/rancher#2496]
we have a golang web applciation.  Is this something we'd import into it?  It looks more like something that makes an independent binary...?

Basically:  Is this what it looks like-- the necessary golang stuff to interface with Rancher, or is it something else?

**Comment by cloudnautique** [comment]
This is the golang Rancher client library. The binary, generates the fixtures from the Rancher API schemas to populate the client directory.

 You can  `go get github.com/rancher/go-rancher` then use github.com/rancher/go-rancher/client to get a client to interface with Rancher. 

You can take  a look at rancher/rancher-compose repo for examples on how to use.
