### ISSUE TITLE
私有镜像仓库配置完成，拉取镜像提示需要登陆

### ISSUE THREAD

**Issue by zxing2004** [rancher/rancher#24969]
*Describe your issue here*

  | ErrImagePull: rpc  error: code = Unknown desc = Error response from daemon: pull access  denied for jaffezhou/zfkj, repository does not exist or may require  'docker login'
-- | --
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`authenticated.cluster.edit`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

If you would like to ask questions in Chinese, please add `rancher2` to join Rancher WeChat group. Thanks
