### ISSUE TITLE
[Rancher	v2.3.4-rc8] 工作负载添加端口映射后，服务名无法ping通

### ISSUE THREAD

**Issue by caojin223** [rancher/rancher#24974]
**操作步骤**
1. 按默认配置建立了集群，节点都为CentOS7虚拟机。
2. 建立若干工作负载。
3. 新建工作负载，如服务名为nginx-test，镜像为nginx。
4. 服务nginx-test添加了端口映射，HostPort或者NodePort

**预期结果**
  服务nginx-test可以被其他服务ping通

**实际结果**
1. 所有服务都无法ping通nginx-test，包括nginx-test自己也无法ping通自己
2. nginx-ingress服务，可以正常向外暴露nginx-test的端口
3. 删除服务nginx-test的端口映射后，所有服务都可以正常ping通nginx-test
4. 再次添加端口映射，nginx-test又变得无法ping通

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.4-rc8` UI: `v2.3.30` |
|Route|`containers.index`|

**Comment by loganhz** [comment]
You can try if you can curl it via pod ip and check if CoreDNS in System project is working well

If you would like to ask questions in Chinese, please add `rancher2` to join Rancher WeChat group. Thanks
