### ISSUE TITLE
Download the SSH keys via API?

### ISSUE THREAD

**Issue by vitobotta** [rancher/rancher#24978]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Other details that may be helpful:**
I am trying to use a node driver for Hetzner Cloud, which works great apart from the fact that no firewall is configured when Rancher creates the nodes. Because of this, I want to use Ansible to set up at least a firewall soon after the nodes are created, so to prevent etcd/etc ports from being exposed to the public. I can fetch the list of the servers automatically from Hetzner Cloud using the Ansible plugin for HC, but I also need to fetch the SSH keys that Rancher creates for the nodes. I know I can download the keys from the UI, but is it possible to download them using the Rancher API so I can automate this?

Thanks!

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2.3
- Installation option (single install/HA):
HA

**Comment by vitobotta** [comment]
I think I found it... the nodeConfig property is a link to the zip file it seems. Will try that...

**Comment by superseb** [comment]
Every action is in the API, UI calls the API. So basically any action can be automated. See also https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-automate-task-x-in-rancher

For most tasks, the CLI also provides a command and you can find out how that uses the API, for example: https://github.com/rancher/cli/blob/master/cmd/ssh.go#L137

**Comment by vitobotta** [comment]
Hi @superseb , I managed to do it via API but will check out the CLI. Thanks!
