### ISSUE TITLE
flaky test test_catalog_refresh

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#24983]
flaky test: test_catalog.py::test_catalog_refresh

failed build: https://drone-publish.rancher.io/rancher/rancher/2057/2/2

**Comment by rmweir** [comment]
https://drone-pr.rancher.io/rancher/rancher/7108/1/2

**Comment by kinarashah** [comment]
https://drone-pr.rancher.io/rancher/rancher/7930/1/2

**Comment by kinarashah** [comment]
https://drone-pr.rancher.io/rancher/rancher/7929/2/1

**Comment by maggieliu** [comment]
https://github.com/rancher/rancher/issues/26214

**Comment by dramich** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/26451
