### ISSUE TITLE
How to run multiple rancher server clusters in one k8s cluster?

### ISSUE THREAD

**Issue by nickvth** [rancher/rancher#24989]
I like to run mulitple rancher server clusters in one k8s cluster.

The problem is that they share the same etcd database, is it possible to make this multi-tenant or to use an external etcd database for each rancher server cluster? 

Thanks!

**Comment by superseb** [comment]
This should still be valid: https://github.com/rancher/rancher/issues/16102#issuecomment-429306953

**Comment by nickvth** [comment]
@superseb  this is not working for rancher server HA clusters in one cluster right?
