### ISSUE TITLE
Timeout in HTTP GET to [https://git.rancher.io/system-charts/index.yaml]

### ISSUE THREAD

**Issue by adesito** [rancher/rancher#24980]
Hi 

I receive this error in the catalog section and I cant install the monitoring system.

Timeout in HTTP GET to [https://git.rancher.io/system-charts/index.yaml], did not respond in 30s
--

Error in HTTP GET to [https://git.rancher.io/system-charts/index.yaml], error: Get https://git.rancher.io/system-charts/index.yaml: dial tcp: lookup git.rancher.io on 169.254.169.254:53: read udp 172.17.0.2:37912->169.254.169.254:53: read: no route to host
--
Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'... fatal: unable to access 'https://git.rancher.io/charts/': Could not resolve host: git.rancher.io : exit status 128
---
Single node version with docker 18.09/19.03 Oracle Linux 7.7 and 8.1 (tested in both SO).

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Rancher | v2.3.3
-- | --
User Interface | v2.3.25
Helm | v2.14.3-rancher1
Machine | v0.15.0-rancher20-1

**Comment by baturorkun** [comment]
Did you solve it? Installed Rancher and got similar errors.

```
E1213 11:49:56.202912      33 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
2021/12/13 11:50:00 [ERROR] Failed to read API for groups map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]
W1213 11:50:01.240332      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
2021/12/13 11:50:02 [ERROR] Failed to connect to peer wss://10.42.0.26/v3/connect [local ID=10.42.2.29]: dial tcp 10.42.0.26:443: i/o timeout
2021/12/13 11:50:02 [ERROR] Failed to connect to peer wss://10.42.1.22/v3/connect [local ID=10.42.2.29]: dial tcp 10.42.1.22:443: i/o timeout
E1213 11:50:06.242038      33 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
2021/12/13 11:50:11 [ERROR] Failed to read API for groups map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]
W1213 11:50:12.597576      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
2021/12/13 11:50:12 [ERROR] error syncing 'rancher-partner-charts': handler helm-clusterrepo-ensure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974 fetch origin ab9de8171a87525459dd98a83cd65ac24961da6c error: exit status 128, detail: fatal: unable to access 'https://git.rancher.io/partner-charts/': Could not resolve host: git.rancher.io
, requeuing
2021/12/13 11:50:14 [ERROR] error syncing 'rancher-charts': handler helm-clusterrepo-ensure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-charts/4b40cac650031b74776e87c1a726b0484d0877c3ec137da0872547ff9b73a721 fetch origin dd20f254d5dd6688dcc4ea480107d02e03420796 error: exit status 128, detail: fatal: unable to access 'https://git.rancher.io/charts/': Could not resolve host: git.rancher.io
, requeuing
```
