### ISSUE TITLE
Vsphere provider is trying to delete a non-existing PV

### ISSUE THREAD

**Issue by santascsi** [rancher/rancher#24991]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy persistent volumes with the Vsphere Cloud Provider
- Attach the volume to a deployment.
- force some pod movements (node drain etc).
- delete deployment.

**Result:**
We're seeing repeating errors on "delete virtual disk" tasks, initiated by the kubernetes user for vmdk's of a PV that no longer exist. the vmdk does not exist on the datastore and the corresponding PV does not exist in the kubernetes cluster.

![image](https://user-images.githubusercontent.com/39088744/72622083-ce4d0400-3942-11ea-9d91-3609d94351a2.png)

We've seen this behaviour before in a small test cluster and it stopped once the cluster was removed. This is obviously not workable for clusters with running workloads.

**Other details that may be helpful:**
- ESXi: 6.5.0 build 8294253
- Vcenter: 6.5.0 build 8307201

**Environment information**
- Rancher version: v2.3.4
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Centos VM's 4C/8G
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Debug Mode: false

Server:
 Containers: 32
  Running: 20
  Paused: 0
  Stopped: 12
 Images: 14
 Server Version: 19.03.5
 Storage Driver: devicemapper
  Pool Name: docker-253:3-98566272-pool
  Pool Blocksize: 65.54kB
  Base Device Size: 10.74GB
  Backing Filesystem: xfs
  Udev Sync Supported: true
  Data file: /dev/loop0
  Metadata file: /dev/loop1
  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
  Data Space Used: 5.114GB
  Data Space Total: 107.4GB
  Data Space Available: 24.33GB
  Metadata Space Used: 24.3MB
  Metadata Space Total: 2.147GB
  Metadata Space Available: 2.123GB
  Thin Pool Minimum Free Space: 10.74GB
  Deferred Removal Enabled: true
  Deferred Deletion Enabled: true
  Deferred Deleted Device Count: 1
  Library Version: 1.02.158-RHEL7 (2019-05-13)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.5.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.62GiB
 Name: nxtrancher1.sofico.be
 ID: SA44:GW7C:ET56:TWGQ:S2FF:7SSB:J3TA:4NVA:XGXJ:RSR7:VGDY:VYXI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: the devicemapper storage-driver is deprecated, and will be removed in a future release.
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

**Comment by Quantas** [comment]
I am seeing the exact same issue, on vSphere 6.5u3, rancher 2.3.4, using Ubuntu 18.04.3 nodes provisioned by Rancher.

**Comment by LinAnt** [comment]
https://github.com/kubernetes/cloud-provider-vsphere/issues/180
https://github.com/rancher/rancher/issues/15065
https://github.com/rancher/rancher/issues/18221

This is known issue with the deprecated provider. It is not a rancher issue, and VMWare won't fix.

Best bet is to update to 6.7u3p1 and go with the new actively developed CSI provider.

**Comment by Quantas** [comment]
@LinAnt Is there any documentation on how to setup an RKE template in Rancher UI to use the CSI provider for vSphere? Do you know if there is a way to switch but not lose any existing data/VMDKs?

**Comment by LinAnt** [comment]
I would probably start here:

https://github.com/kubernetes/cloud-provider-vsphere/blob/c40e188bea370ab7e6c76aac9d1eec67e10d8817/docs/book/tutorials/enabling-vsphere-csi-on-an-existing-cluster.md

**Comment by LinAnt** [comment]
I have not tested the new CSI or CCM providers, but knowing VMWare I would do a lot of testing before rolling out to production.

**Comment by santascsi** [comment]
I'll test it in the coming weeks once I have my setup on 6.7U3p1.
