### ISSUE TITLE
Rancher Glusterfs version compatibility

### ISSUE THREAD

**Issue by MingJunDuan** [rancher/rancher#24990]
Rancher version is 2.2.8 and Glusterfs version is 6. There is some problem if I don't set glusterfs volume ctime off, I wonder if compatibility cause the problem.  
I can't find related info in [Rancher docs](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/volumes-and-storage/). Is there any documents about Rancher version and Glusterfs version compatibility?

**Comment by slash1387** [comment]
see https://github.com/rancher/rancher/issues/27472
