### ISSUE TITLE
Validate kubernetes upgrades

### ISSUE THREAD

**Issue by spencergilbert** [rancher/rancher#24997]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

As a kubernetes cluster management layer it would be valuable for Rancher to provide the capability of validating a kubernetes version upgrade prior to applying the change.

For example with the breaking changes in the api between 1.15 and 1.16, it would be great as a user to be aware of what existing workloads would be considered deprecated and/or non-functional due to the version changes.

A inspiration reference could be elasticsearch's upgrade assistant: https://www.elastic.co/guide/en/kibana/7.x/upgrade-assistant.html

**Comment by superseb** [comment]
This was recently added to make people aware of changes between releases: https://github.com/rancher/rancher/issues/24829

The biggest problem with such a feature is that you will never cover 100% of the usecases of people and they will expect a 100% success rate as the advisor said everything was OK before upgrading. With all the components and code changes, I don't think having an advisor for Kubernetes in Rancher is feasible based on the expectations of it. Even if we would document everything that breaks when upgrading Kubernetes for Rancher itself (where we already call out the deprecations in our release notes), this will not cover everything that users use in Kubernetes.

If you have other thoughts, let me know.

**Comment by spencergilbert** [comment]
I'll try and dig up a suggestion I found which involved starting a kube-apiserver with i believe "--runtime-config" configured to not have the "to be" deprecated groups/versions
