### ISSUE TITLE
Add TRACE loglevel

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#24994]
After adding a significant amount of debug logging, we could move our very verbose debug lines to a TRACE level to make sure the debug logging is still readable. Debug would then include printing single line variables/singe line diffs between larger objects/certain behavior being executed, and TRACE would include dumping the structs/objects. This would also help in leaving debug on for a longer time for a certain issue (else it would either fill the disk or app could become sluggish)

**Comment by superseb** [comment]
To test Rancher:

- Executing `loglevel --set trace` in `rancher/rancher` container (PASS)
- Executing `loglevel --set invalid` in `rancher/rancher` container (FAIL)
- Executing `loglevel --set debug` in `rancher/rancher` container (PASS)
- Executing `loglevel --set info` in `rancher/rancher` container (PASS)

To test RKE:

- Executing `rke help` should show `--trace` as flag
- Executing `rke --trace up` should show `TRAC[0000] Loglevel set to [trace]`
- Executing `rke --debug up` should still work and show `DEBU[0000] Loglevel set to [debug]`

**Comment by aaronRancher** [comment]
This enhancement is verified with Rancher server `rancher\rancher:master-head` `version beba5247e`

Executing `loglevel --set trace` in `rancher/rancher` container (PASS)
```
root@cf0e798bffa9:/var/lib/rancher# loglevel --set trace
OK
```

Executing `loglevel --set invalid` in `rancher/rancher` container (FAIL)
```
root@cf0e798bffa9:/var/lib/rancher# loglevel --set invalid
Error when setting loglevel: Failed to parse loglevel: not a valid logrus Level: "invalid"
```

Executing `loglevel --set debug` in `rancher/rancher` container (PASS)
```
root@cf0e798bffa9:/var/lib/rancher# loglevel --set debug
OK
```

Executing `loglevel --set info` in `rancher/rancher` container (PASS)
```
root@cf0e798bffa9:/var/lib/rancher# loglevel --set info
OK
```

This enhancement is verified with RKE version `v1.1.0-rc11`
`rke help` shows `--trace` as a flag
```
GLOBAL OPTIONS:
   --debug, -d    Debug logging
   --quiet, -q    Quiet mode, disables logging and only critical output will be printed
   --trace        Trace logging
   --help, -h     show help
   --version, -v  print the version
```
Executing `rke --trace` up shows:
```
Aarons-MBP:documents aaronyee$ ./rke --trace up
TRAC[0000] Loglevel set to [trace]
```
Example of `--trace` logs:
```
DEBU[0000] audit log policy found in cluster.yml
INFO[0000] Initiating Kubernetes cluster
DEBU[0000] Logging data.json from local source, timestamp: 06 Mar 20 08:58 MST
DEBU[0000] data.json content: {
 "K8sVersionServiceOptions": {
  "v1.10": {
   "etcd": null,
   "kubeapi": {
    "allow-privileged": "true",
    "anonymous-auth": "false",
    "bind-address": "0.0.0.0",
    "enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction",
    "insecure-port": "0",
    "kubelet-preferred-address-types": "InternalIP,ExternalIP,Hostname",
    "profiling": "false",
```
Executing `rke --debug up`:
```
Aarons-MBP:documents aaronyee$ ./rke --debug up
DEBU[0000] Loglevel set to [debug]
WARN[0000] This is not an officially supported version (v1.1.0-rc11) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest
INFO[0000] Running RKE version: v1.1.0-rc11
DEBU[0000] Parsing cluster file [nodes:
```
