### ISSUE TITLE
Feature: Ability to enforce default resource requests/limits at cluster level.

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#25002]
Currently, we provide the ability to do this at the project level, but a customer would like to be able to do this at the cluster level or even global across all clusters managed by Rancher.

This should just involve adding another layer at the cluster level the propagates to projects and then to namespaces, much like how it's already done.

**Comment by skaven81** [comment]
We should reference https://github.com/kubernetes/kubernetes/issues/80537 as ultimately, having this functionality (cluster-wide resource requests/limits) in upstream K8s would be preferred over having it be a feature unique to Rancher.

Perhaps Rancher can put some pressure on the scheduling SIG to make this happen?

**Comment by skaven81** [comment]
Seems the upstream request kubernetes/kubernetes#80537 ended up getting closed as stale.

Perhaps we should close this one too.  It looks like the industry is moving toward admission control as being the de facto way to implement this sort of thing.  Whether it's Kyverno, Gatekeeper, or something else.
