### ISSUE TITLE
[UI] Add Switzerland locations to Azure as new region

### ISSUE THREAD

**Issue by hypnotortoise** [rancher/rancher#25019]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
N/A

**Result:**
N/A

**Other details that may be helpful:**
Switzerland region in Azure must be explicitly activated in subscribers quota profile and is only available to paying subscribers. Therefore adding it as another cloud region, same as Germany/China/USGov, and not in PublicCloud is recommended. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher Version  `v2.3.4` - `rancher/rancher:latest`
- Installation option (single install/HA):
`HA`

**Comment by hypnotortoise** [comment]
Just realized that all those regions links to [docker-machine environments](https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go) with different service endpoints. As this is not the case for swiss regions, I will update the PR to add both Swiss locations (switzerlandnorth & switzerlandwest) into `PublicCloud` environment.

**Comment by meyerf99** [comment]
@superseb & @bashofmann Are there any updates to this feature request?

**Comment by miraculixx** [comment]
@superseb  @bashofmann  @meyerf99 is there some way this can be custom-added to an existing rancher deployment?

**Comment by hypnotortoise** [comment]
I rebased this PR to current master to resolve conflict with UAE AZ cluster provider.
For folks who want to add this to their existing rancher deployment: I'm afraid you have to build your own Docker images of rancher ui with my patched `lib/shared/addon/utils/azure-choices.js` until someone from the rancher devs authorizes this PR.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version a1acca856`

Switzerland North and Switzerland West are available in Azure node template.
![Screen Shot 2020-08-26 at 2 50 04 PM](https://user-images.githubusercontent.com/57409052/91360592-96951d00-e7ab-11ea-8073-61e58e628449.png)

Also observed azure config set to correct locations:
Switzerland North:
```
"azureConfig": {
"availabilitySet": "docker-machine",
"clientId": "",
"customData": "",
"diskSize": "30",
"dns": "",
"dockerPort": "2376",
"environment": "AzurePublicCloud",
"faultDomainCount": "3",
"image": "canonical:UbuntuServer:18.04-LTS:latest",
"location": "switzerlandnorth",
"managedDisks": false,
"noPublicIp": false,
"nsg": "rancher-managed-hmH9AoOJ",
```
Switzerland West:
```
"azureConfig": {
"availabilitySet": "docker-machine",
"clientId": "",
"customData": "",
"diskSize": "30",
"dns": "",
"dockerPort": "2376",
"environment": "AzurePublicCloud",
"faultDomainCount": "3",
"image": "canonical:UbuntuServer:18.04-LTS:latest",
"location": "switzerlandwest",
"managedDisks": false,
"noPublicIp": false,
"nsg": "rancher-managed-hmH9AoOJ",
```
