### ISSUE TITLE
CIS Scan - UI - config.json does not accept single quotes for its value

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25010]
**What kind of request is this (question/bug/enhancement/feature request):** bug 

**Steps to reproduce (least amount of steps as possible):**
- Deploy a cluster
- Through the API run CIS Scan on the cluster with the config map value set as 
`{"config.json": "{'skip':{'rke-cis-1.4':['1.1.2']}}"}`

**Actual Result:**
The scan does NOT skip the test.

**Expected Result:**
The Scan should skip the test - 1.1.2

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Comment by codyrancher** [comment]
@maggieliu this is a backend issue because it's being run through the API and not the UI.

> Through the API run CIS Scan on the cluster with the config map value set as
{"config.json": "{'skip':{'rke-cis-1.4':['1.1.2']}}"}

As a side note. I don't think the expected result is correct. I think the api should respond with an error because the supplied configuration is not valid json. Valid json requires the use of double quotes.

**Comment by vincent99** [comment]
Yes that is not JSON.  The test could be changed to (in the backend) if the config is unparseable instead of (apparently) proceeding with no custom config, so that you know something is wrong.

**Comment by leodotcloud** [comment]
With the latest changes around using scan profiles, not applicable/skip checks from k-d-m, this issue is not relevant anymore.

**Comment by sowmyav27** [comment]
**On latest master-head - commit id:`63306835a`**

- From the UI, pass config.json like this
<img width="1184" alt="Screen Shot 2020-03-06 at 10 09 04 PM" src="https://user-images.githubusercontent.com/26032343/76137962-71db9c00-5ff7-11ea-909e-0e3d1c6d8c4c.png">
- On running a Scan for cis 1.4 Hardened profile, the report generated is erred out
<img width="1283" alt="Screen Shot 2020-03-06 at 10 12 34 PM" src="https://user-images.githubusercontent.com/26032343/76137990-d139ac00-5ff7-11ea-8535-e687f83cf48d.png">

- Rancher logs:
```
2020/03/07 06:07:20 [INFO] Marking CIS scan complete: cis-1583561232635481655
2020/03/07 06:07:20 [ERROR] ClusterScanController c-ll57f/cis-1583561232635481655 [cisScanHandler] failed with : cisScanHandler: Updated: runner pod not yet deleted, will retry
2020/03/07 06:07:21 [INFO] Deleting chart using helm version: rancher-helm
[main] 2020/03/07 06:07:21 Starting Tiller v2.16.3-rancher1 (tls=false)
[main] 2020/03/07 06:07:21 GRPC listening on :54422
[main] 2020/03/07 06:07:21 Probes listening on :55222
[main] 2020/03/07 06:07:21 Storage driver is ConfigMap
[main] 2020/03/07 06:07:21 Max history per release is 10
2020/03/07 06:07:21 [ERROR] ClusterScanController c-ll57f/cis-1583561232635481655 [cisScanHandler] failed with : cisScanHandler: Updated: runner pod not yet deleted, will retry
[storage] 2020/03/07 06:07:22 getting release history for "cis-1583561232635481655"
[tiller] 2020/03/07 06:07:22 uninstall: Deleting cis-1583561232635481655
[tiller] 2020/03/07 06:07:22 executing 0 pre-delete hooks for cis-1583561232635481655
[tiller] 2020/03/07 06:07:22 hooks complete for pre-delete cis-1583561232635481655
[storage] 2020/03/07 06:07:22 updating release "cis-1583561232635481655.v1"
2020/03/07 06:07:22 [ERROR] ClusterScanController c-ll57f/cis-1583561232635481655 [cisScanHandler] failed with : cisScanHandler: Updated: runner pod not yet deleted, will retry
[kube] 2020/03/07 06:07:22 Starting delete for "cis-1583561232635481655-rancher-cis-benchmark" Service
[kube] 2020/03/07 06:07:23 Starting delete for "security-scan-runner-cis-1583561232635481655" Pod
[kube] 2020/03/07 06:07:23 Starting delete for "s-sa-cis-1583561232635481655" ClusterRoleBinding
[kube] 2020/03/07 06:07:23 Starting delete for "s-sa-cis-1583561232635481655" ClusterRole
[kube] 2020/03/07 06:07:23 Starting delete for "s-sa-cis-1583561232635481655" ServiceAccount
[kube] 2020/03/07 06:07:23 Starting delete for "s-config-cm-cis-1583561232635481655" ConfigMap
[kube] 2020/03/07 06:07:23 Starting delete for "s-plugins-cm-cis-1583561232635481655" ConfigMap
[tiller] 2020/03/07 06:07:23 executing 0 post-delete hooks for cis-1583561232635481655
[tiller] 2020/03/07 06:07:23 hooks complete for post-delete cis-1583561232635481655
[tiller] 2020/03/07 06:07:23 purge requested for cis-1583561232635481655
[storage] 2020/03/07 06:07:23 deleting release "cis-1583561232635481655.v1"
2020/03/07 06:07:23 [WARNING] release "cis-1583561232635481655" deleted

2020/03/07 06:07:24 [ERROR] ClusterScanController c-ll57f/cis-1583561232635481655 [cisScanHandler] failed with : cisScanHandler: Updated: error fetching configmap cis-1583561232635481655: configmaps "cis-1583561232635481655" not found
2020/03/07 06:07:24 [INFO] Deleting chart using helm version: rancher-helm
[main] 2020/03/07 06:07:24 Starting Tiller v2.16.3-rancher1 (tls=false)
[main] 2020/03/07 06:07:24 GRPC listening on :49378
[main] 2020/03/07 06:07:24 Probes listening on :46276
[main] 2020/03/07 06:07:24 Storage driver is ConfigMap
[main] 2020/03/07 06:07:24 Max history per release is 10
[storage] 2020/03/07 06:07:24 getting release history for "cis-1583561232635481655"
[tiller] 2020/03/07 06:07:24 uninstall: Release not loaded: cis-1583561232635481655
2020/03/07 06:07:28 [ERROR] ClusterScanController c-ll57f/cis-1583561232635481655 [cisScanHandler] failed with : cisScanHandler: Updated: error fetching configmap cis-1583561232635481655: configmaps "cis-1583561232635481655" not found
2020/03/07 06:07:37 [ERROR] ClusterScanController c-ll57f/cis-1583561232635481655 [cisScanHandler] failed with : cisScanHandler: Updated: error fetching configmap cis-1583561232635481655: configmaps "cis-1583561232635481655" not found
2020/03/07 06:07:53 [ERROR] ClusterScanController c-ll57f/cis-1583561232635481655 [cisScanHandler] failed with : cisScanHandler: Updated: error fetching configmap cis-1583561232635481655: configmaps "cis-1583561232635481655" not found
root@localhost:~# dock


```

**Expected result:**
The Action should fail and the API should throw an error stating the config.json value is invalid.

**Comment by cjellick** [comment]
I dont think the action needs to fail. Just the test needs to fail and convey that status properly. Ran it by @vincent99 and he suggested "the test runs and gets into the following state:
`transition=error transitionMessage="Failed to run scan, malformed configmap"`

**Comment by leodotcloud** [comment]
@cjellick I agree with this conclusion. Before I made the changes, I contemplated on if we should have the action fail, because with the existing behavior, the scan will error out with the message pointing out that there is a problem with the config map.

**Comment by leodotcloud** [comment]
@sowmyav27 can you check the latest behavior (now that https://github.com/rancher/rancher/issues/24626 is fixed) and see if that addresses this issue?

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `570461823`**

- Config.json = `{'skip':{'rke-cis-1.4':['1.1.2']}}}`
- Run scan.
- Scan is run and reports an error

<img width="1163" alt="Screen Shot 2020-03-11 at 4 41 42 PM" src="https://user-images.githubusercontent.com/26032343/76474017-82a15e80-63b7-11ea-8239-25d37f2be0f2.png">
<img width="1272" alt="Screen Shot 2020-03-11 at 4 41 54 PM" src="https://user-images.githubusercontent.com/26032343/76474018-83d28b80-63b7-11ea-94e7-d1bb61b791bd.png">
