### ISSUE TITLE
Can't add etcd node if another etcd node is down

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#25013]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a new custom cluster with 2 control plane, 3 etcd, and 2 worker nodes.
2. Shut down one of the etcd nodes. To accomplish this, I stopped docker on the VM.
3. Attempt to add a new etcd node by running the docker run... on a new host.

**Result:**
The UI reports:
```
Failed to reconcile etcd plane: Failed to add etcd member [etcd-ip-10-0-2-19] to etcd cluster
```
Rancher logs show:
```
2020/01/17 22:47:12 [INFO] cluster [c-jpzp5] provisioning: [add/etcd] Adding member [etcd-ip-10-0-2-19] to etcd cluster
2020/01/17 22:47:12 [ERROR] ClusterController c-jpzp5 [cluster-provisioner-controller] failed with : Failed to reconcile etcd plane: Failed to add etcd member [etcd-ip-10-0-2-19] to etcd cluster
```
Every 5 minutes it attempts to add the etcd member but fails with the same error.

**Other details that may be helpful:**
If the unhealthy etcd node is deleted in the UI, the new etcd does get added successfully.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.4
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
t3a.medium on AWS
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by Oats87** [comment]
This behavior sounds okay, given the fact that adding a node in this state can be dangerous (if you add a node to make this a 4 node cluster for example, you still have a fault tolerance of 1, which you already have faulty node for -- this means that if your new node fails to add completely for any reason, your etcd cluster will have lost quorum)

**Comment by dnoland1** [comment]
Maybe we can consider having this behavior described in the docs and changing the error message to more clearly state that a new etcd node cannot be added unless the failed etcd node is removed first.

**Comment by sangeethah** [comment]
Similar to issue reported -https://github.com/rancher/rancher/issues/20956

**Comment by dnoland1** [comment]
Looks like we do already document this behavior (see https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/etcd/#replacing-unhealthy-etcd-nodes ). Perhaps we can also improve the error message.
