### ISSUE TITLE
Unable to add label to node 

### ISSUE THREAD

**Issue by wwyhy** [rancher/rancher#25017]
Hi,

I have imported a k8s cluster (v1.13.12). 

I tried to add label to a node by Rancher UI, but do nothing after type and save. what is the issue?

Besides,  is there any way to record operate history of each user by UI? 
Thanks!

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`authenticated.cluster.monitoring.index`|

**Comment by loganhz** [comment]
Fixed in 2.3.4
Close in favor of https://github.com/rancher/rancher/issues/24123
