### ISSUE TITLE
Add scaling test framework to Jenkins job

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#25011]
Automate scaling tests using Jenkins

**Requirements**: 
* Test framework should have pass or fail results.
* Write necessary jenkins code
* Write as validation test
* Create and provide ssh key just in case
* Delete all ec2 VMs to destroy cluster, instead of using terraform destroy

**Comment by cbron** [comment]
@bmdepesa is this handled by your stuff ? We can close out if so.

**Comment by bmdepesa** [comment]
Yes. We can close this.
