### ISSUE TITLE
[UI] App templates load clusters and projects repeatedly 

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#25026]
When doing the flow `global > apps > launch > any template` projects and clusters are retrieved every time a template is clicked on. In a system with a lot of projects and clusters this makes it seem like the app page takes a long time to load.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 2/4

* Reproduced in v2.3.3
* `global > apps > launch > template` results in calls to projects/clusters being made
* Deploy `master-head`
* `global > apps > launch > template` does not result in the calls to projects/clusters
