### ISSUE TITLE
limit resources for server

### ISSUE THREAD

**Issue by wormen** [rancher/rancher#25022]
Tell me, how can I set resource limits for specific servers in a cluster?

eg:
I have 3 servers in the cluster, for each of them, I want to set so that 4 GB of free RAM remains on it

How can I do this at the rancher level?

**Comment by loganhz** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/

**Comment by wormen** [comment]
@loganhz 
it is not described here that I asked
the question was how to do it through Rancher UI

**Comment by loganhz** [comment]
I guess `--system-reserved` arg of kubelet will help. You can add custom args when you create a RKE cluster by using `Edit as YAML`

![image](https://user-images.githubusercontent.com/21168270/72771710-baecb200-3c3c-11ea-958d-74d96f6f846b.png)

![image](https://user-images.githubusercontent.com/21168270/72771621-74975300-3c3c-11ea-82cc-60eec3433ac9.png)

More info:

https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#config-file
https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by loganhz** [comment]
Similar question https://github.com/rancher/rancher/issues/17177

**Comment by wormen** [comment]
ok thanks
