### ISSUE TITLE
Whitespace in front of CA bundle

### ISSUE THREAD

**Issue by DamonGant** [rancher/rancher#2502]
Rancher 	v0.43.1
Cattle 	v0.106.0
User Interface 	v0.63.0
Rancher Compose 	v0.5.0

Tried to use a Comodo DV cert with a HTTPS load balancer. I couldn't figure out why a cerificate from our chain was missing, but then I checked the HAproxy container. The intermediate was prefixed with a space so the entire first intermediate was discarded.

API shows no whitespace in the bundle.

Bundle https://u.pomf.io/weuwpa.txt
Cert https://u.pomf.io/bpyswm.txt

**Comment by vincentriemer** [comment]
+1 I've encountered this same issue

**Comment by sangeethah** [comment]
Tested with build from master:

Still see white space in the intermediate cert in server1.pem and sever2.pem files in haproxy of LB instances created with default and alternate certs.

**Comment by sangeethah** [comment]
Tested with rancher-server version - V0.47.0-rc1

No white spaces  seen  in the intermediate cert in default , server1.pem and sever2.pem files in haproxy of LB instances created with a default and 1 alternate cert.
