### ISSUE TITLE
[UI] prevent /g/clusters from making redundant requests

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#25024]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. open networking tab
2. load /g/clusters

**Result:**
Clusters request is made twice. It appears that both requests need to be returned before UI is load. If this is the case, the second request extends the time to load by a non trivial amount.

![image](https://user-images.githubusercontent.com/19376037/72754651-a9949e80-3b85-11ea-8115-715228a8cb9d.png)

**Comment by rmweir** [comment]
@deniseschannon @tfiduccia redundant project calls are made under `/projects-namespaces`, and I believe there are some others. Not sure if you want separate issues or not.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 2/4

* Reproduced in v2.3.3
* visit `/g/clusters` and see the redundant requests
* Deploy `master-head`
* visit `/g/clusters` and the redundant requests are no longer made
