### ISSUE TITLE
2.3.4 - Local cluster stuck in provisioning with: Waiting for server-url setting to be set

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#25041]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
Install Rancher in HA with a self-signed cert (specifically on HobbyFarm Scenario)

**Result:**
Access Rancher. set admin password. set server-url. Observe that the cluster never actually finishes "provisioning".

**Other details that may be helpful:**
A workaround for this is to edit the local cluster then save it. I am assuming this informs the clusterdeploy controller which then finishes agent deployment

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.4
- Installation option (single install/HA): HA

The relevant logs seem to be:
```
2020/01/22 00:19:02 [INFO] Redeploy Rancher Agents is needed for local: forceDeploy=false, agent/auth image changed=true, private repo changed=false
2020/01/22 00:19:02 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
```
and Rancher just sits here forever.

**Comment by sangeethah** [comment]
Similar to the issue - https://github.com/rancher/rancher/issues/16213

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/16213
