### ISSUE TITLE
Host entries are being duplicated in vSphere Node Templates in 2.3.4

### ISSUE THREAD

**Issue by smart-nickname** [rancher/rancher#25047]
What kind of request is this:
bug

Steps to reproduce:

- Create a new or edit an existing vSphere Node Template. 
- Pick a host from the host drop-down list, in this case xxx-xxx01.xxx.xxx-xxx.xx

Result:

Rancher duplicates hostnames in "hostsystem" var (seen in "View in API"):
` "hostsystem": "/dc1-4/host/xxx-xxx01.xxx.xxx-xxx.xx/xxx-xxx01.xxx.xxx-xxx.xx"`
This leads to Rancher not able to provision a node.

Other details that may be helpful:

vCenter v6.7.0.42000 Build number 15132721
Rancher v2.3.4, UI v2.3.32

**Comment by smart-nickname** [comment]
Also, this https://github.com/rancher/rancher/issues/24510 issue is still in place in 2.3.4 and both issues together make workaround (fixing the node template via API) tedious.

**Comment by bmdepesa** [comment]
I'm not able to reproduce this in vSphere 6.7 w/ Rancher 2.3.4 & UI v2.3.32

* Edited & created new node templates with a host selected. 
* `hostsystem": "/xx/host/xx/172.16.2.14"`is set in the node template correctly.

**Comment by smart-nickname** [comment]
Maybe this is some kind of artifact after upgrading Rancher from 2.3.2 to 2.3.4 which we did.

We have another Rancher instance v2.3.2 talking to exactly the same vCenter, and creating node templates there works fine.

**Comment by smart-nickname** [comment]
I'm still able to reproduce this in Rancher 2.3.6 by creating a brand new vSphere node template and changing Host only. The result is the hostname being duplicated, see the screenshot

![host](https://user-images.githubusercontent.com/42069307/80107153-06d02f80-857b-11ea-8769-7e82f9c37344.PNG)

**Comment by bashofmann** [comment]
From what I can see, Rancher is just getting a list of hostnames, displaying them in a select field and passing the received values 1:1 on, without modifications, when saving.
In your setup, I can see the difference that the host system name is not containing any vSphere cluster in its path.
It could be, that because of a bug in the vSphere Go library that Rancher uses (https://github.com/vmware/govmomi/) or a configuration issue in your vSphere setup, this path is assembled incorrectly.

**Comment by bashofmann** [comment]
@smart-nickname Could you check if the XHR Request from the Rancher UI to `https://rancher-url/meta/vsphere/hosts?...` returns a list of correct host system identifiers, or if they are already wrong there?

**Comment by smart-nickname** [comment]
@bashofmann 
The hostnames are never duplicated in the UI by the way, even if they are duplicated in "View in API".

When I try `https://rancher-url/meta/vsphere/hosts?...` , I get a 422 error 
`InvalidBodyContent: cloudCredentialId required` . Can you please share more details on how to compile the test request?

**Comment by bashofmann** [comment]
@smart-nickname I meant to check the XHR request that the UI does on the "Edit Node Template" form with the browser developer tools:

<img width="1319" alt="Bildschirmfoto 2020-04-28 um 15 38 48" src="https://user-images.githubusercontent.com/243056/80494074-88063880-8966-11ea-80a9-b0cb125eaab4.png">

**Comment by smart-nickname** [comment]
@bashofmann Got it. I can confirm that the response from vCenter contains duplicated hostnames.

**Comment by bashofmann** [comment]
Then this looks to be a problem in vSphere, the vSphere configuration or the go library from vmware. From what I can see is, that all Rancher does is query the available hosts and return a list of the full paths to them.
For readability the UI then just shows the last part of the path in the select option's label. The option's value contains the full path to the host as it was returned from vSphere.

**Comment by smart-nickname** [comment]
Also tested with another instances of vCenter and Rancher.

Thanks @bashofmann, I'm closing this ticket.
