### ISSUE TITLE
get nodes -o wide returns same address on rancher cluster made from vagrant vms

### ISSUE THREAD

**Issue by jascase901** [rancher/rancher#25042]
I think there is a bug when using rancher/rancher in vagrant. 
 
I am using this to build my rancher server
> docker run -d --name $container_name --restart=unless-stopped -p 80:80 -p 443:443 -v /opt/rancher:/var/lib/rancher rancher/rancher:latest

In order to add nodes to my cluster I need to pass parameters to tell the nodes to use the ips
on eth1 instread of eth0. Heres an example

`sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.3.3 --server https://192.168.33.11 --token cr6cvjv949wrgf4jgxf5mdw5f9f44p72fbctgn9pjxlk7n9d4ddtzg --ca-checksum de16aef511787012e4ecce624a3b5bec2c312c895d14467dd3529dc35341dcfa --address 192.168.1.33 --internal-address 192.168.1.33 --etcd --controlplane --worker
`
This lets me add nodes to my cluster.

Unfortunately, these parameters aren't 100% honored because the internal ip from 
`get nodes -o wide` for all my
nodes is always the same one on eth0 (10.0.2.15). 

When building a kubelet there should be an argument passed called "node-ip" that
changes the internal ip address. However using docker inspect I can tell that this
argument wasn't passed.

I am guessing that this line is the issue
```

#rancher/vendor/github.com/rancher/rke/cluster/plan.go
if host.Address != host.InternalAddress {
		CommandArgs["node-ip"] = host.InternalAddress
	}

```

My hypotheses is the --address 192.168.33.33 changes the host.address, and the
--internal-address 192.168.33.33  changes the host.internal address. And because I am setting
them both to the same value.  The node-ip arg never gets added to the build kubelet cmd.

I tried building rancher from source to test this out, by typing make. But I don't know how to test my changes.

**Comment by westonmyers** [comment]
Have you tried setting address to your interface name? Looking at the entrypoint for `rancher/rancher-agent`, it looks like you can just set `--address eth1`. (Looks like that's reinforced in [Rancher docs](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/custom-nodes/agent-options/) too.)

I'm not saying it'll fix your issue, I'm just curious.

**Comment by jascase901** [comment]
@westonmyers No luck. But it does make me less confident in my guess as host.InternalAddress has a different value then Host.address.

I think I figured out how to build the rancher-agent and rancher server image so ill be more useful soon.

**Comment by jascase901** [comment]
if you change this line of code
rancher/vendor/github.com/rancher/rke/cluster/plan.go

if host.Address != host.InternalAddress {
		CommandArgs["node-ip"] = host.InternalAddress
	}

to

CommandArgs["node-ip"] = host.InternalAddress

the bug is fixed.


```
**vagrant@vagrant:~$ k get nodes -o wide
NAME                  STATUS   ROLES               AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
etcd-controlplane-1   Ready    controlplane,etcd   18m   v1.17.0   192.168.33.21   <none>        Ubuntu 18.04.3 LTS   4.15.0-58-generic   docker://19.3.5
worker-1              Ready    worker              16m   v1.17.0   192.168.33.31   <none>        Ubuntu 18.04.3 LTS   4.15.0-58-generic   docker://19.3.5
**
```

**Comment by jascase901** [comment]
I don't think my patch will make it in. Apparently, something similar to it has been considered but it breaks some systems. And I don't have the time or skills to figure out the proper way to do it. 

But for anyone  who is using vagrant and sees this in the future. 
Another way of triggering the node-ip parameter logic is to tell vagrant to create two  new interfaces (eth1 and eth2), and then pass  one of them as the internal-address and the other as the address. 
heres an example.
  config.vm.define "worker_1" do |worker_1|
        # Create a private network, which allows host-only access to the machine
        # using a specific IP.


        worker_1.vm.hostname = "worker-1"
        worker_1.vm.network "private_network", ip: "192.168.33.31"
        worker_1.vm.network "private_network", ip: "192.168.34.51"

        worker_1.vm.provider "virtualbox" do |vb_1|

          vb_1.cpus = 8

          # Customize the amount of memory on the VM:
          vb_1.memory = "12288"
        end
      end
#
Then you can pass the --addresses eth1 and --internal-address eth2 which will trick the plan.go logic into passing node-ip to the kublet.

`
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.3.3 --server https://192.168.33.11 --token cr6cvjv949wrgf4jgxf5mdw5f9f44p72fbctgn9pjxlk7n9d4ddtzg --ca-checksum de16aef511787012e4ecce624a3b5bec2c312c895d14467dd3529dc35341dcfa --address 192.168.33.31 --internal-address 192.168.34.51 --etcd --controlplane --worker`

Note this is unrelated. But I also noticed that you need to tell canal to use the 192.168.0.0/16 addresses or some services like the Prometheus monitoring, and the kubernetes dashboard will not let you into their web interfaces.

I did that with 
`k edit ds canal -n kube-system
`
and making sure your command looks like this
```

      - command:
        - /opt/bin/flanneld
        - --ip-masq
        - --kube-subnet-mgr
        - --iface-regex=192\.

```

**Comment by superseb** [comment]
Without the flag, it will auto determine IP and this goes wrong when `/etc/hosts` does not contain a proper entry (https://github.com/rancher/rancher/issues/26033#issuecomment-599215353).

**Comment by boyfoo** [comment]
Run into the same problem，eth0 and eth1，What's the best solution？
