### ISSUE TITLE
vSphere nodes aren't created on correct host

### ISSUE THREAD

**Issue by joshuaganger** [rancher/rancher#25052]
In the vsphere node template configuration, you can select a host for the node to be created on.  This setting doesn't seem to work.  I deployed a cluster from a datastore template several times, and each time the nodes were deployed to a different host in the selected datacenter.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.4` UI: `v2.3.32` |
|Route|`authenticated.cluster.cluster-catalogs`|

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.4

* Reproduced in vSphere 6.7
* Set host to `172.16.2.11` in node template
* Node is actually created on `172.16.2.12`

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/25698
https://github.com/rancher/rancher/pull/25699

**Comment by bmdepesa** [comment]
rancher/rancher:master-head d8e28c62d
rancher/rancher:v2.3-head 877090196

* Reproduced in v2.3.4
* Created vsphere node template, selecting a specific host 
* Create a cluster using the node template
* The node is created on the correct host initially but then gets set to a different host after restarting during the provisioning process

This occurs in both `master-head` and `v2.3-head`

**Comment by luthermonson** [comment]
@bmdepesa can we close this? We decided that our vsphere cluster was moving the node after deployment right?

**Comment by joshuaganger** [comment]
In my case, vSphere isn't moving the VMs.  They are created and stay on the wrong host, but in the correct vSphere Datacenter.

**Comment by luthermonson** [comment]
@joshuaganger yes there was a bug with placing the nodes on the correct host which will be fixed in 2.3.6 and 2.4 and you can see the linked closed PR which fixed that. our test environment was making it look like it wasn't fixed as vsphere was moving the nodes after boot which brandon and I talked about in person, I'm trying to get him to validate the fix and close the ticket so we can consider the issue solved.

**Comment by bmdepesa** [comment]
@joshuaganger can you try with `rancher/rancher:v2.3.6-rc6`? 

Our test environment makes it seem as if this is not resolved, but I will update with my final results once they are completed.

**Comment by joshuaganger** [comment]
Just gave it a try.  The Clone virtual machine step fails with error "A specified parameter was not correct: spec.pool".  Could be something with my VMWare configuration, but nothing's changed since the last test, as far as I'm aware.

**Comment by deniseschannon** [comment]
@luthermonson can you take a look again and work with @joshuaganger cause it seems that the RC for v2.3.6 didn't fix it for him. 

@joshuaganger can you confirm it's not working in v2.3.6 or in v2.4.2?

**Comment by joshuaganger** [comment]
I solved the issue I was having.  In the node template configuration there is a selection for "Resource Pool".  In this particular vsphere implementation I have no explicitly defined Resource Pools, so only the default resource pools exist.  The default resource pools are called "Resources".  Because there are two hosts in the selected datacenter, the Rancher interface shows the two default resource pools but no indication which belongs to which host.  They both just show up as "Resources".  If one of the identically named selections is chosen, and happens to be the one associated with the OTHER host, then I get the aforementioned error.  If I had more than two hosts, this would be a frustrating game of trial and error trying to determine which identically named option is correct.

I think a possible good solution to this would be to prepend the default "Resources" name with the host that it's associated with.

**Comment by luthermonson** [comment]
@joshuaganger updated the UI to include the host/cluster for the `Resources` option in the drop down. UI will be updated and released with 2.4.3 and should be back ported to 2.3.x

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:v2.4-head` `version 7f7d6bfc9`
UI is updated to prepend the host/cluster:
![Screen Shot 2020-04-20 at 5 39 37 PM](https://user-images.githubusercontent.com/57409052/79813255-f7a97180-832f-11ea-993c-2d8ff9ad800c.png)
Previous UI in v2.4.2:
![Screen Shot 2020-04-20 at 5 55 07 PM](https://user-images.githubusercontent.com/57409052/79813606-f3318880-8330-11ea-8bb0-b432df11fae3.png)

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 6a60f3386`
UI is updated to prepend the host/cluster:
![Screen Shot 2020-04-21 at 4 25 37 PM](https://user-images.githubusercontent.com/57409052/79924516-ccd12300-83ec-11ea-98a1-b48dd27fb255.png)

When node is provisioned with host that is not in the same resource pool, provisioning fails with:
```
Error creating machine: Error in driver during machine creation: 400 Bad Request: {"type":"com.vmware.vapi.std.errors.invalid_argument","value":{"messages":[{"args":["No future registered with name: crGetEnvBrowser"],"default_message":"An error occurred: No future registered with name: crGetEnvBrowser","id":"com.vmware.vdcs.util.unhandled_error"}]}}
```
