### ISSUE TITLE
Enabling SDS Gateway in Istio fails 

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#25051]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create cluster in a v2.3.4 Rancher server that is large enough to enable monitoring and Istio. I use 3 nodes with all roles at 8GB 4vCPU.
2. As cluster owner, navigate to Tools --> Istio
3. Enable Ingress Gateway
4. Set Custom Answer: `gateways.istio-ingressgateway.sds.enabled=true`
5. Click Save

**Result:**
The `istio-ingressgateway` workload in `istio-system` namespace tries to pull image: `rancher/node-agent-k8s:1.4.3`. It should instead be pulling `rancher/istio-node-agent-k8s:1.4.3` (with "istio" prepended). It fails to pull and results in the pod never coming up, with ImagePullBackOff error.

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/55997940/72912942-9efb1600-3cf9-11ea-8de9-9cb4f4ac33a4.png">

**Other details that may be helpful:**

**Environment information**
- Rancher v2.3.4 Single node install

**Cluster information**
- Used Linode, 3 nodes all with all 3 roles at 8GB, 4vCPUs
- kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by deniseschannon** [comment]
Available in the `dev` branch of system-charts

**Comment by rancher-max** [comment]
### Tests passed using Rancher v2.3.5-rc2 and the default chart included with that ( https://git.rancher.io/system-charts  Branch: dev)

Tried with both a fresh cluster and upgrade from 2.3.3. Set custom answers when enabling istio:
```
certmanager.enabled=true
gateways.istio-ingressgateway.sds.enabled=true
istiocoredns.enabled=true
prometheus.enabled=true
grafana.enabled=true
kiali.dashboard.grafanaURL=""
kiali.prometheusAddr=http://prometheus:9090
```

This now uses the correct images (not prepended with `docker.io`) and succeeds in enabling istio. See below screenshot of all successfully deployed workloads:

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/55997940/73019065-1b682480-3de0-11ea-9668-fdd35fe08586.png">
