### ISSUE TITLE
Registry address value shows extra characters in UI

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#25069]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug in both v2.3-head and v2.3.5-rc2, but not in master-head

**Steps to reproduce (least amount of steps as possible):**
- run rancher server single install in either regular or air-gap env
- add a cluster 
- go to a project -> Resources -> Registry Credentials 
- add a custom registry 

**Result:**
The address value in the UI show `*%` at the beginning and "%*" at  the end of the actual value 

<img width="1305" alt="Screen Shot 2020-01-23 at 11 35 11 AM" src="https://user-images.githubusercontent.com/6218999/73012933-8c094400-3dd4-11ea-87c4-f42abb7d149f.png">

**Comment by westlywright** [comment]
Available in `latest-2.3`

**Comment by jiaqiluo** [comment]
The bug fix is validated on v2.3-head 6eecc2c8b with UI index latest-2.3

The steps are the same, the extra punctuations are gone

<img width="1457" alt="Screen Shot 2020-02-04 at 4 34 18 PM" src="https://user-images.githubusercontent.com/6218999/73797135-67b24d80-476c-11ea-89bf-7f4ee377c2f2.png">
