### ISSUE TITLE
Accept wss in addition to https for x-forwarded-proto

### ISSUE THREAD

**Issue by bradjones1** [rancher/rancher#25061]
**What kind of request is this (question/bug/enhancement/feature request):**

Bugfix

**Steps to reproduce (least amount of steps as possible):**

Access Rancher behind a reverse proxy that sets the `x-forwarded-proto` header to `wss` when a websocket request is made to it over HTTPS.

**Result:**

Rancher looks for a value of `https` in the `x-forwarded-proto` header at

https://github.com/rancher/rancher/blob/7a898ff87276951d95310b4dacb87020aa9e0de9/pkg/dynamiclistener/server.go#L505-L507

to determine whether to serve the request; otherwise it falls through to a redirect on error condition. Rancher should also accept `wss` as a valid forwarded protocol. For reference, Traefik sets its value for this header at https://github.com/containous/traefik/blob/a20a6636b4582e4e7b562fc01f64567775fc8a9a/pkg/middlewares/forwardedheaders/forwarded_header.go#L143-L149

**Other details that may be helpful:**

This is a continuation of the self-closed ticket at https://github.com/rancher/rancher/issues/24202, and a much more in-depth background is offered by that user on Traefik's issue queue at https://github.com/containous/traefik/issues/5533#issuecomment-553823512.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `2.3.3`
- Installation option (single install/HA): HA, behind Traefik 2.0 (as noted above)

**Comment by bradjones1** [comment]
Updated - this code is now at https://github.com/rancher/rancher/blob/4ff98cc603ea47528062ee6994d2a5e58a29ed5a/pkg/clusterrouter/proxy/proxy_server.go#L214-L221

**Comment by bradjones1** [comment]
Not stale.

**Comment by bradjones1** [comment]
Not stale.

**Comment by bradjones1** [comment]
Not stale

**Comment by radiantwave** [comment]
This was never changed?

**Comment by bradjones1** [comment]
As you'll see above, this was closed by their stale bot (I have opinions about this model but it's what the project wants to do.)

Non-maintainers can't re-open this issue so if you still need this, you'll have to open a new issue and link to this one for history.
