### ISSUE TITLE
SUSE custom cluster not provisioned with private IP provided

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#25067]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a custom cluster, with one node all roles, with the following AMI:
Suse Enterprise Linux 12 SP5
`suse-sles-12-sp5-v20191209-hvm-ssd-x86_64 - ami-0d808701ac55e8ef7`
Install docker on instances:
`sudo zypper in -f docker-19.03.5_ce-98.51.1`
Start docker on instances:
`sudo service docker start`
Provide the public IP and private IP in Rancher:
![Screen Shot 2020-01-23 at 9 29 53 AM](https://user-images.githubusercontent.com/57409052/73005895-f915dd00-3dc6-11ea-8544-183e6dc8a785.png)
Run install command

**Result:**
![Screen Shot 2020-01-23 at 9 33 05 AM](https://user-images.githubusercontent.com/57409052/73004569-d1257a00-3dc4-11ea-85fa-caab14631de4.png)
When trying to connect to the docker port from the instance:
```
ip-172-31-23-226:/home/ec2-user # telnet 172.31.23.226 2379
Trying 172.31.23.226...
telnet: connect to address 172.31.23.226: Connection timed out
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
`rancher\rancher:master-head` `version 47bf996c2`
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Kubernetes version (use `kubectl version`): 
```
v1.17.2-rancher1-1
```

- Docker version (use `docker version`):
```
docker-19.03.5_ce-98.51.1
```

**Notes:**
This bug is also seen in a 3 node setup, one role per node. As long as the private IP is passed in, the node will fail to come up.
Providing the private IP in an `ubuntu1804docker1809` custom cluster does not result in this error.

**Comment by aaronRancher** [comment]
Works when SuSEfirewall2 is disabled in the OS.

Steps followed in the OS:
`zypper update`
`SuSEfirewall2 stop`
`service docker start`
run agent installation command

The core DNS fails when the private IP is given in the installation command. Tracked here #25072

**Comment by aaronRancher** [comment]
The issue is not seen when restarting the OS after updating. CoreDNS is also functional.:

Steps followed in the OS:
`zypper update`
reboot instance
`SuSEfirewall2 stop`
service docker start
Run installation command with private IP and Public IP

**Comment by aaronRancher** [comment]
Running `docker info` yields:
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: oci runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.12.14-122.7-default
 Operating System: SUSE Linux Enterprise Server 12 SP5
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.843GiB
 Name: ip-172-31-22-209
 ID: JQMW:COA2:HV4G:BNOV:HY3O:TPL2:FIFP:L3TR:2IBR:55DN:VBSX:KQEI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by aaronRancher** [comment]
Using this ami, `suse-sles-12-sp5-v20191209-hvm-ssd-x86_64 - ami-0d808701ac55e8ef7`
We see the firewall blocking all ports by default. The following steps need to be done in order to open up the ports needed for adding host to custom cluster.

Update zypper - `zypper update`
reboot instance
edit /etc/sysconfig/SuSEfirewall2 and set the following ports
```
FW_SERVICES_EXT_TCP="22 80 443 2376 2379 2380 6443 9099 10250 10254 30000:32767"
FW_SERVICES_EXT_UDP="8472 30000:32767"
FW_ROUTE=yes
```
Restart firewall with new ports - `SuSEfirewall2`
Start docker - `service docker start`

**Comment by aaronRancher** [comment]
Reopened issue to add documentation.

**Comment by catherineluse** [comment]
The steps to open the SUSE ports have been documented here: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/node-requirements/#opening-suse-linux-ports
