### ISSUE TITLE
Namespace with -1 limit stuck in Activating

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#25076]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster with a new project. Note the cluster id and project id.
2. Run the following script to create two new namespaces. (substitute the variables at the top):
```bash
export CATTLE_ACCESS_KEY=token-xxxxx
export CATTLE_SECRET_KEY=xxxxxxxxxxxxxxxxx
export CLUSTER_ID=c-xxxxx
export PROJECT_ID=p-xxxxx
export HOST=xxx.xxx.rancher.space

JSON="{\"type\":\"namespace\",
       \"name\":\"namespace-with0\",
       \"clusterId\":\"${CLUSTER_ID}\",
       \"projectId\":\"${CLUSTER_ID}:${PROJECT_ID}\",
       \"resourceQuota\":{
         \"limit\":{
           \"limitsCpu\":\"0\",
           \"limitsMemory\":\"0\"
         }
       },
       \"labels\":{}}"

echo json is $JSON

curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-H 'content-type: application/json' \
-H 'Accept: application/json'  \
-X POST \
-d "${JSON}" \
https://${HOST}/v3/clusters/${CLUSTER_ID}/namespace

JSON="{\"type\":\"namespace\",
       \"name\":\"namespace-with-1\",
       \"clusterId\":\"${CLUSTER_ID}\",
       \"projectId\":\"${CLUSTER_ID}:${PROJECT_ID}\",
       \"resourceQuota\":{
         \"limit\":{
           \"limitsCpu\":\"-1\",
           \"limitsMemory\":\"-1\"
         }
       },
       \"labels\":{}}"

echo json is $JSON

curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-H 'content-type: application/json' \
-H 'Accept: application/json'  \
-X POST \
-d "${JSON}" \
https://${HOST}/v3/clusters/${CLUSTER_ID}/namespace
```

**Result:**
The namespace with -1 limit is stuck in Activating state. 
![image](https://user-images.githubusercontent.com/468462/73024856-47d17000-3de3-11ea-948f-1a1865a9c327.png)

**Other details that may be helpful:**
Note, the UI does not allow you to create a namespace with a -1 limit. This should be blocked by API if it's not a valid option.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.4
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
t3a.medium on aws
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

gz#8092
SURE-1685

**Comment by innobead** [comment]
@cclhsu please help with this.

**Comment by cclhsu** [comment]
Unable to reproduce the issue:

# Test Environment:
Rancher Version: v2.3.4
Cluster 1: v1.18.13+rke2r1
Cluster 2: v1.19.5+k3s2
Cluster 3: v1.2.3+rke
Cluster 4: v.1.17.4+rancher1-2
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

![Screenshot from 2020-12-25 21-03-30](https://user-images.githubusercontent.com/379755/103137533-99296400-4704-11eb-9aab-00b4389b014a.png)
![Screenshot from 2020-12-25 21-03-52](https://user-images.githubusercontent.com/379755/103137542-a1819f00-4704-11eb-9863-e6cf951a6242.png)
![Screenshot from 2020-12-25 21-54-06](https://user-images.githubusercontent.com/379755/103137545-a9414380-4704-11eb-9321-c21f3af1a82e.png)
![Screenshot from 2020-12-25 22-38-05](https://user-images.githubusercontent.com/379755/103137546-ac3c3400-4704-11eb-84b3-0e38dd873908.png)

**Comment by cclhsu** [comment]
Testing with following testing parameters to check if it is older Kubernetes or kubectl issue.

``` 
Rancher Version: v2.3.4

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: v1.15.11, v1.16.8, v.1.17.4 (3 customerize versions in the Rancher 2.3.4)
```

Still cannot reproduce the issue.  Not sure if the issue is related to I currently cannot gain AWS access using Openbare since the web has 500 error.  I will try to reproduce the issue once I have aws access.

**Comment by cclhsu** [comment]
Able to reproduce the issue. When we created the project, we also need to set "Resource Quota" in order to encounter the issue.  I have created a manifest below to test negative value when we set limited range.

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: test
spec:
  limits:
  - default:
      memory: -1Mi
    defaultRequest:
      memory: -1Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: test
spec:
  limits:
  - default:
      cpu: -1
    defaultRequest:
      cpu: -1
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: default-demo
  namespace: test
spec:
  containers:
  - name: default-demo-ctr
    image: nginx
```

And encounter message as following:

```
the Pod "default-demo" is invalid: 
* spec.containers[0].resources.limits[cpu]: Invalid value: "-1": must be greater than or equal to 0
* spec.containers[0].resources.limits[memory]: Invalid value: "-1Mi": must be greater than or equal to 0
* spec.containers[0].resources.requests[memory]: Invalid value: "-1Mi": must be greater than or equal to 0
* spec.containers[0].resources.requests[cpu]: Invalid value: "-1": must be greater than or equal to 0
```

We should add some condition to rancher/pkg/controllers/managementuser/resourcequota/resource_quota_sync.go => validateAndSetNamespaceQuota

**Comment by Ellenqs** [comment]
I tested this on Rancher V2.3.4, to reproduce the issue, when creating project, set the resource quota, also using the script provided which set the limit to "-1". If set the namespace quota limit to some resonable value such as 0.1, it works fine.

**Comment by cclhsu** [comment]
I am able to reproduce the issue using v2.5.3 also.  While building Rancher, which working earlier today, we now encountered

```
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
The command '/bin/sh -c curl -sLf ${!HELM_URL_V2} > /usr/bin/rancher-helm &&     curl -sLf ${!TILLER_URL} > /usr/bin/rancher-tiller &&     chmod +x /usr/bin/rancher-helm /usr/bin/rancher-tiller &&     ln -s /usr/bin/rancher-helm /usr/bin/helm &&     ln -s /usr/bin/rancher-tiller /usr/bin/tiller &&     helm init -c &&     helm plugin install https://github.com/rancher/helm-unittest' returned a non-zero code: 1
FATA[0034] exit status 1                                
make: *** [Makefile:11: ci] Error 1
```

It is due to [New Location For Stable and Incubator Charts](https://helm.sh/blog/new-location-stable-incubator-charts/).  Need to resolved this issue first.

**Comment by cclhsu** [comment]
@Ellenqs Can you provide more information on what you see on `v2.5.4`?  Is `namespace-with-1` in the UI stuck at `Activating` state?

**Comment by Ellenqs** [comment]
@cclhsu 

I redo the tests on both 2.5.3 and 2.5.4-rc6, below is the updated result:

On the rancher UI, this time there is no stuck on activating.

<img width="994" alt="Screen Shot 2021-01-04 at 1 46 25 PM" src="https://user-images.githubusercontent.com/75277058/103583694-0ec7c980-4e95-11eb-83e7-1b678474f5b7.png">

When view in API, we can see the limits set:

<img width="767" alt="Screen Shot 2021-01-04 at 1 47 10 PM" src="https://user-images.githubusercontent.com/75277058/103583724-1edfa900-4e95-11eb-8bbf-4ad13eff59a9.png">

<img width="757" alt="Screen Shot 2021-01-04 at 1 46 45 PM" src="https://user-images.githubusercontent.com/75277058/103583734-22733000-4e95-11eb-8914-fc687fa3429f.png">


On rancher logs, there is error message said "invalid value...":

<img width="799" alt="Screen Shot 2021-01-04 at 1 54 38 PM" src="https://user-images.githubusercontent.com/75277058/103583779-374fc380-4e95-11eb-8b2c-2ba994da7713.png">

**Comment by annablender** [comment]
No longer an issue on Rancher 2.5.9. I reproduced this on Rancher 2.6 with the new UI because the new UI uses the k8s native API which has no validation code for namespace creation. The validation code is in the non-native API, which is called from the old UI. Sent to UI team to work.
