### ISSUE TITLE
Windows enabled cluster stuck in "Provisioning" state on latest master

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25081]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a custom cluster with Flannel Network Provider and Windows enabled cluster
- Register a Linux Ubuntu 18.04 node.
- The node comes up Active.

**Expected Result:**
The cluster should come up Active

**Actual Result:**
Cluster is stuck in provisioning state
Error
```
This cluster is currently Provisioning.
```
`Exit status 1, clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver unchanged clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master unchanged namespace/cattle-system unchanged serviceaccount/cattle unchanged clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged secret/cattle-credentials-6ed72cc unchanged clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged deployment.apps/cattle-cluster-agent unchanged daemonset.apps/cattle-node-agent unchanged error: error parsing management-statefile_path_redacted: error converting YAML to JSON: yaml: line 92: found character that cannot start any token`

**Note:**
This works on 2.3.5-rc2 and 2.3.4

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `47bf996c2`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Kubernetes version (use `kubectl version`):

```
1.17.2, 1.16.6 and 1.15.9
```

- Docker version (use `docker version`):

```
19.03
```

**Comment by superseb** [comment]
Based on what I found, the tab in this PR is the reason of this error:

https://github.com/rancher/rancher/pull/24363/files#r372560544

**Comment by sowmyav27** [comment]
**verified on latest master-head - commit id : `4f1aff9b7`**

- k8s - 1.17.2
- Deploy a windows custom cluster - 1 linux all roles node, 1 windows worker node - AWS
- Deployed a workload.
- No issues seen
