### ISSUE TITLE
Not able to edit stack.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2509]
Server version - Build from master - Oct 30

From UI , Edit an existing stack and change the name of the stack.
Editing the stack fails with following exception - "Validation failed in API: previousExternalId"

**Comment by ebr** [comment]
I've seen this, but the error I got was "HostPort....something" - I'll update this if I get it again. I got around by simply clicking on the forwarded port field (not even editing anything), and clicking "Save" again.

**Comment by sshipway** [comment]
I get this as well - changing the name or description of a stack results in:

Validation failed in API: previousExternalId

... which means nothing to me!

**Comment by ibuildthecloud** [comment]
argh.... my fault.  I'll fix.

**Comment by deniseschannon** [comment]
Verified with build master
Able to edit stack name with no issues.
