### ISSUE TITLE
CRDs are missing from role_data for istio for project owner, project member, and read only

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#25096]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Enable Istio in cluster with custom answer: `certmanager.enabled=true`
2. Add 3 users with different roles to default namespace: project owner, project member, and read only
3. With any of the users, attempt to run `kubectl get` for these resources:
```
adapters.config.istio.io
attributemanifests.config.istio.io
httpapispecbindings.config.istio.io
httpapispecs.config.istio.io
instances.config.istio.io
templates.config.istio.io
certificates.certmanager.k8s.io 
challenges.certmanager.k8s.io    
issuers.certmanager.k8s.io  
orders.certmanager.k8s.io  
```

**Result:**
Project Owner and Member should be able to read and write to these resources but are forbidden since these are not present in the role_data file. Read Only user should be able to read but is also forbidden.

**Other details that may be helpful:**
This is failing in multiple releases. Tested in v2.3.3 with Istio v0.1.1 and in v2.3.5-rc2 with istio v1.4.300. Will be failing in released v2.3.5 as well.
Related to Issue: rancher/rancher#25077 

**Environment information**
- Multiple versions: v2.3.5-rc2, v2.3.3
- Single node install

**Cluster information**
- Linode k8s v1.16 or 1.17 depending on Rancher version. 
- 3 nodes, all roles, each at 4vCPU 8GB.

**Comment by davidnuzik** [comment]
Applied v2.4 milestone based on meeting we had with Denise today. Possible could slip, but ideal in v2.4.0 :)

**Comment by davidnuzik** [comment]
Note, we should also consider fixing https://github.com/rancher/rancher/issues/25275 which has a low LOE to resolve.

**Comment by cbron** [comment]
Istio v1 is deprecated and Istio v2 uses dynamic ClusterRole RBAC which includes these CRDs, so this ticket isn't relevant anymore, closing out.
