### ISSUE TITLE
Add Istio 1.5.X

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#25098]
~Istio 1.5.0 is planned to be released 2/18 at the time of this writing (see https://github.com/istio/istio/wiki/Istio-Release-1.5). We need to start working on bumping to this version.~

Rancher's 1.5 will use the original helm chart and not support istioD. We will support a migration path from the original helm chart to the operator helm chart with 1.5->1.6, which will come at a later date.

**Comment by davidnuzik** [comment]
Based on our current roadmap/timelines I'm guessing this should be for v2.4.0 release so have tagged that milestone for now.

**Comment by cbron** [comment]
This may require large updates to UI with istioD replacing Pilot, Citadel, Galley. Also, depending on how helm vs istioctl treat istiod install, it also may necessitate we handle [helm deprecation](https://github.com/rancher/rancher/issues/24976) at same time.

**Comment by LinAnt** [comment]
I tested out istio 1.5.0 default install on one of our test clusters, it seems these feature gates are not turned on in rancher although default should be `true`

![image](https://user-images.githubusercontent.com/11833599/77077804-66786f80-69fe-11ea-9f35-df754fbfc1b7.png)

I need to do some further research. Currently istiod fails with 
```MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled```

**Comment by cbron** [comment]
Possible we need to skip 1.5 and go with 1.6, as there is not a clear or clean upgrade path from current helm install, but there will be in 1.6. Still tbd at this point.

**Comment by robinbraemer** [comment]
@LinAnt could you please tell us what you did in your workaround?

**Comment by LinAnt** [comment]
> @LinAnt could you please tell us what you did in your workaround?

You just need to confitgure the API server to enable the endpoints:

```
extra_args:
        service-account-issuer: <example-name>
        service-account-signing-key-file: /etc/kubernetes/ssl/kube-service-account-token-key.pem
```

**Comment by FrimIdan** [comment]
> > @LinAnt could you please tell us what you did in your workaround?
> 
> You just need to confitgure the API server to enable the endpoints:
> 
> ```
> extra_args:
>         service-account-issuer: <example-name>
>         service-account-signing-key-file: /etc/kubernetes/ssl/kube-service-account-token-key.pem
> ```

Is there a way to add this extra_args with a `rancher/rancher-agent:v2.4.2 --server` command?

**Comment by DavidSpek** [comment]
I'm also having this issue while trying to install kubeflow with dex authentication. It seems service-account-signing-key-file is already set in the config. I tried adding service-account-issuer with and without service-account-signing-key-file under services.kube-api.extra_args and I get the following error. 

```
Error: --service-account-signing-key-file, --service-account-issuer, and --api-audiences should be specified together
```
I am using a custom cluster so I am unsure where in Rancher I can change the required setting to deploy the cluster successfully.

**Comment by lomori** [comment]
I'm having the same problem as @DavidSpek.
