### ISSUE TITLE
Kubernetes Namespaces & Workdload Not visible

### ISSUE THREAD

**Issue by Goeldeepesh** [rancher/rancher#25109]
*Describe your issue here*

I'm facing a very skeptical issue. I have kubernetes HA cluster on bare metal - 3 master, 4 data nodes and 3 external etcd. Issue is - when i installed the Rancher 2.3.4 first time and imported the kubernetes cluster, it showed all the namespaces( kube-system, cattle-system, ...) under system project with the number of pod running on each node. But when i stopped and restarted the Rancher container and again imported the kubernetes cluster, Rancher did not show any namespaces which it showed at the first time. I even tried removing the Rancher's namespace cattle-system and re-deploying it, but nothing worked.

**Rancher version 2.3.4
Kubelet 1.17
Docker 19.03

Rancher Container Logs:**

2020/01/25 13:26:25 [INFO] Handling backend connection request [c-2k2ps:machine-2gkm9]
2020/01/25 13:26:25 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2020/01/25 13:26:29 [INFO] Handling backend connection request [c-2k2ps:machine-pm92w]
2020/01/25 13:26:30 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2020/01/25 13:26:31 [ERROR] CatalogController system-library [system-image-upgrade-catalog-controller] failed with : upgrade cluster c-2k2ps system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found
2020/01/25 13:26:33 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2020/01/25 13:26:33 [INFO] Handling backend connection request [c-2k2ps:machine-rkz7j]
2020/01/25 13:26:46 [INFO] Handling backend connection request [c-2k2ps:machine-mz86g]
2020/01/25 13:26:55 [ERROR] NamespaceController default [resourceQuotaSyncController] failed with : project.management.cattle.io "c-nngxv/p-k7q4x" not found, [resourceQuotaUsedLimitController] failed with : project.management.cattle.io "c-nngxv/p-k7q4x" not found
2020/01/25 13:26:55 [ERROR] NamespaceController kube-public [resourceQuotaSyncController] failed with : project.management.cattle.io "c-nngxv/p-6hxjx" not found, [resourceQuotaUsedLimitController] failed with : project.management.cattle.io "c-nngxv/p-6hxjx" not found
2020/01/25 13:26:55 [ERROR] NamespaceController kube-system [resourceQuotaSyncController] failed with : project.management.cattle.io "c-nngxv/p-6hxjx" not found, [resourceQuotaUsedLimitController] failed with : project.management.cattle.io "c-nngxv/p-6hxjx" not found
2020/01/25 13:26:55 [ERROR] NamespaceController kube-node-lease [resourceQuotaSyncController] failed with : project.management.cattle.io "c-nngxv/p-6hxjx" not found, [resourceQuotaUsedLimitController] failed with : project.management.cattle.io "c-nngxv/p-6hxjx" not found

**Comment by simonhou** [comment]
I met the similar error, which can be found in the local cluster ui:
`CatalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found`.
