### ISSUE TITLE
Detail CIS scan results are not displayed

### ISSUE THREAD

**Issue by paraglade** [rancher/rancher#25102]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
After doing a clean install of a rancher server and importing a cluster I run a CIS scan on that imported cluster. That scan finishes and becomes `active` with a summary of the results. When I click on the report to view the details the opening box animation is displayed and report results are never shown.

**Result:**
Detailed CIS scan results are not displayed

**Other details that may be helpful:**
In the browser console I am seeing this error:
```
clusterscan.js:11 Uncaught (in promise) TypeError: Invalid attempt to spread non-iterable instance
    at clusterscan.js:11
    at s (clusterscan.js:9)
    at clusterscan.js:177
    at Array.reduce (<anonymous>)
    at n.getNodeNamesFromNodeType (clusterscan.js:176)
    at controller.js:141
    at Array.map (<anonymous>)
    at n.<anonymous> (controller.js:138)
    at n.i.get (metal.js:3614)
    at $e (metal.js:2720)
```

**Environment information**
- Rancher version `rancher-head` and ` v2.4.0-alpha1`
- Installation option single install
- CIS hardened RKE cluster

**Cluster information**
- Cluster type: `Imported`
- Machine type: `VM` 4 vCPU 3GB memory
- Kbernetes version:`v1.15.6`
- Docker version: `18.9.9`

**Comment by sowmyav27** [comment]
On an imported RKE cluster in rancher:v2.4.0-alpha1, CIS scans cannot be run
<img width="1330" alt="Screen Shot 2020-01-26 at 2 27 13 PM" src="https://user-images.githubusercontent.com/26032343/73142823-0beb1480-4048-11ea-8439-636115a74b8d.png">

Also from the API UI, the option is disabled.

@paraglade Can you please provide more information about the cluster/setup?

**Comment by paraglade** [comment]
my mistake on this the Cluster type is: `Custom`

![image](https://user-images.githubusercontent.com/2743595/73304113-dd4e7480-41d4-11ea-8374-32314d505199.png)
