### ISSUE TITLE
level=error msg="Remotedialer proxy error" error="websocket: bad handshake"

### ISSUE THREAD

**Issue by phaneesh11** [rancher/rancher#25113]
*Describe your issue here*

I am getting below error when importing a cluster to rancher
level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.0` UI: `v2.3.15` |
|Route|`global-admin.clusters.index`|

**Comment by phaneesh11** [comment]
ailed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-dqv25/m-1b0bdf35d558\" not found" error="websocket: bad handshake

**Comment by superseb** [comment]
This is identical to https://github.com/rancher/rancher/issues/25111
