### ISSUE TITLE
[feature request] Auto Deploy services via Docker Hub Web Hooks 

### ISSUE THREAD

**Issue by mih-tricom** [rancher/rancher#2511]
It would be great if Rancher could auto deploy services when the image is updated on Docker Hub.
This should be possible via the Docker Hub Web Hooks and would enable Rancher users to use Rancher for CD.

**Comment by jifeon** [comment]
Are there some workarounds for it?

**Comment by spalladino** [comment]
We've built https://github.com/manastech/rancher-autoredeploy/, which sets up a small http server for listening requests from docker hub, and upgrades the matching services in the rancher environment using the API. Hope it helps!

**Comment by deniseschannon** [comment]
This is now implemented in Rancher with our webhooks that allow you to upgrade a service based on a docker hub webhooks. . 

http://rancher.com/docs/rancher/v1.6/en/cattle/webhook-service/#upgrading-a-service-based-on-docker-hub-webhooks
