### ISSUE TITLE
Fail to apply any changes to deployed Istio configuration

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#25114]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Launch Rancher v2.3.4, create a cluster and deploy the default istio version
- Once Istio is deployed open Istio config page
- Change any configuration, e.g. Ingress Gateway -> Enable
- Hit Save

**Actual Result:**
None. Save button without function.

Expected Result:
Configuration change is applied.

Rancher 2.3.4 HA

**Comment by westlywright** [comment]
Available in `latest2` and `latest-2.3`

**Comment by rancher-max** [comment]
#### Validated with ui-index as both `https://releases.rancher.com/ui/latest2/index.html` and `https://releases.rancher.com/ui/latest-2.3/index.html` using Rancher v2.3.5-rc5 and system-chart `dev` branch

Upgrade Scenario:
1. Have istio enabled in rancher v2.3.3 server with `local` ui-index
2. Upgrade rancher to v2.3.5-rc5
3. Change ui-index to `latest-2.3` and system-chart to `dev`
4. Upgrade istio to v1.3.400
5. After istio comes up, go to Tools > Istio and change a value
6. Click Save
Validated that network sent POST request. Going to Apps > cluster-istio showed Installing and had the change present in the `Answers` section. Going back to Tools > Istio and refreshing the page had the updated values.

Fresh Install Scenario:
1. Use rancher v2.3.5-rc5
2. Change ui-index to `latest2` and system-chart to `dev`
3. Enable istio v1.3.400 with default values.
4. After istio comes up, go to Tools > Istio and change a value (I enabled gateway)
5. Click Save
Validated that network sent POST request. Going to Apps > cluster-istio showed Installing and had the change present in the `Answers` section. Going back to Tools > Istio and refreshing the page had the updated values.


![image](https://user-images.githubusercontent.com/55997940/73201394-2a0f4e00-40f6-11ea-84e1-39fac97fa7e6.png)

**Comment by rancher-max** [comment]
Validated above with `Rancher master-head version d84c489f4` and Rancher v2.3.5-rc6 (left system-charts and ui-index as defaults). Basic regression worked fine as well on rc6.
