### ISSUE TITLE
Remove pspt lifecycle and move to user sync

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#25122]
Cluster scoped lifecycles cause a lot of additional work for controllers and also make the object very hard to view when rancher is managing high numbers of clusters. For example, roleTemplates in a 2k cluster rancher setup will have 2k finalizers and 2k annotations. 

The below controllers should be investigated to determine if it's possible to rewrite them as non-cluster scoped lifecycles. 

Some options would be to split it into two controllers, a sync and a management lifecycle
An owners reference if an object need to be deleted.

```
grep -ir 'New.*LifecycleAdapter' pkg/controllers
pkg/controllers/user/rbac/podsecuritypolicy/template.go:	psptSync := v3.NewPodSecurityPolicyTemplateLifecycleAdapter("cluster-pspt-sync_"+context.ClusterName, true, pspti, lfc)
pkg/controllers/user/secret/secret.go:	sync := v1.NewSecretLifecycleAdapter(fmt.Sprintf("secretsController_%s", cluster.ClusterName), true,
```

EDIT: This issue is specifically for PodSecurityPolicyTemplate lifecycle getting moved out of being a cluster scoped lifecycle.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4.0-rc7

* Ran long and short-running automation for regression validation
