### ISSUE TITLE
Duplicated hosted zones get created with trying to create a stack with "ROOT DOMAIN NAME" that does not end with ".".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2512]
Server version - Build from master - oct 30

Create a stack from "External DNS" catalog by providing a stack with  "ROOT DOMAIN NAME" that does not end with "." like "test.com".

2 hosted zone entries get created with "test.com."  out of which one of them gets updated with all the dns entries.

Even in the case where there is already a hosted zone with "test.com." was already present , 2 more hosted zone entries get created with "test.com."  and all the dns entries get programed in one of the newly created hosted zone.

**Comment by alena1108** [comment]
Hosted name has to be pre-created

**Comment by sangeethah** [comment]
Tested with latest version of the template for "External DNS". 

When creating a stack from "External DNS" catalog by providing a stack with "HOSTED ZONE" that does not end with "." like "test.com" and "test.com" already is pre created , existing hosted  zone entry is used by rancher-server and dns entries get programmed here.

When creating a stack from "External DNS" catalog by providing a stack with "HOSTED ZONE" that does not exist , the service does not start successfully. They keep restarting.
