### ISSUE TITLE
Docker engine options does not allow duplicate keys

### ISSUE THREAD

**Issue by qtzar** [rancher/rancher#25132]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**

Create a Node Template
In the Engine Options add keys/values for
  log-opt max-file=3
  log-opt max-size=10m
save node template

**Result:**

Opening the node template and inspecting the engine options only shows one record for log-opt

**Environment information**
- Rancher version : V2.3.4
- Installation option (single install/HA): Single

- Docker version:

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by ldealmei** [comment]
@qtzar Did you find a way around this issue?
I am facing the same problem.

**Comment by ldealmei** [comment]
I went with simply setting `log-opt max-size=10m`. It does the job.
