### ISSUE TITLE
No longer able to create emptyDir volumes from the GUI

### ISSUE THREAD

**Issue by kidhasmoxy** [rancher/rancher#25131]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a new deployment, add an Ephemeral Volume from the GUI, 

**Result:**
option for EmptyDir is not available.

**Other details that may be helpful:**
This option was present in earlier versions (prior to 2.3.1) and if I deploy via yaml, I can see my volume when I edit the deployment via the GUI. I can also change options when I hit "Edit", but the Source dropdown is blank because it isn't available any more:
![image](https://user-images.githubusercontent.com/37122/73282407-973ae600-41bf-11ea-9321-18195bf87009.png)
![image](https://user-images.githubusercontent.com/37122/73282486-b8033b80-41bf-11ea-98fa-62f8ede07a66.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.3.5
- Installation option (single install/HA):
Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`): 1.17.2

**Comment by sowmyav27** [comment]
@kidhasmoxy This flag - `unsupported-storage-drivers` in the cluster level is set to `false` in rancher:v2.3.5, which Hides 'unsupported' storage providers and provisioners.

For the upsupported list of storage providers to be available, `unsupported-storage-drivers` should be set to true.

More info: https://github.com/rancher/rancher/issues/22895
