### ISSUE TITLE
secret username and password

### ISSUE THREAD

**Issue by harshsharma22** [rancher/rancher#25146]
*i have added secret via ui 
name of secret :-> htpasswd
key -> auth 
value :-> $apr1$ivdHx6Yv$3ueMuYIF0ee1D/N7Jz/Ha/ (hello)

and in my ingress i have define these 4 variable
nginx.ingress.kubernetes.io/auth-realm :-> authrequired
nginx.ingress.kubernetes.io/auth-secret -> htpasswd
nginx.ingress.kubernetes.io/auth-secret-type -> auth-map
nginx.ingress.kubernetes.io/auth-type -> basic

and i am unale to login using  auth and hello
*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.4` UI: `v2.3.32` |
|Route|`ingresses.run`|

**Comment by vincent99** [comment]
`...auth-secret-type: auth-map`  was [added](https://github.com/kubernetes/ingress-nginx/pull/4560) in ingress-nginx 0.26, which is (one) newer than we currently package.  Use the `auth-file` format for the secret (which was the only format at that time).
