### ISSUE TITLE
custom cluster creation fail - AWS cloud failed to find ClusterID

### ISSUE THREAD

**Issue by heiqs** [rancher/rancher#25148]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create AWS resources manually
2. Create a custom cluster via Rancher 2.3.2 UI
3. Tag the resources and use the docker run command

**Result:**
kubelet docker is restarting with the error: 

E0129 14:11:32.191512   21737 tags.go:97] Tag "KubernetesCluster" nor "kubernetes.io/cluster/..." not found; Kubernetes may behave unexpectedly.
F0129 14:11:32.191577   21737 server.go:271] failed to run Kubelet: could not init cloud provider "aws": AWS cloud failed to find ClusterID

**Other details that may be helpful:**

**Environment information**
- Rancher version: 2.3.2
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom on AWS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Amazon linux 2
- Kubernetes version (use `kubectl version`): Kubernetes v1.16.6-rancher1-2
```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by heiqs** [comment]
For future readers, the tag of clusterid should also be applied to VPC in AWS.

**Comment by oxr463** [comment]
> For future readers, the tag of clusterid should also be applied to VPC in AWS.

See: https://rancher.com/docs/rancher/v2.5/en/cluster-provisioning/rke-clusters/custom-nodes/#3-amazon-only-tag-resources
