### ISSUE TITLE
K3s Integration Design

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#25141]
**What kind of request is this:**
Design

**Description:**
K3s will be integrating into Rancher 2.4.0 with at least these minimum requirements for the Rancher UI:

- Import K3s clusters using normal import flow
- View details of nodes revealing the k3s config for each node (planned to be an annotation on each node)
- Edit the cluster and show at least master configuration (includes k3s version) and provide means to upgrade the K3s cluster to a newer version via drop-down (depends on k3s backend which needs to supply a means to query if there is a newer update available, see https://github.com/rancher/k3s/issues/1359). Picking a newer version will tell K3s to start upgrading nodes.
- May need to support Max Unavailable (rolling upgrades).

**Additional Information:**
Later we plan to manage nodes via nodePools and to add K3s clusters with a custom-like flow instead of import.

**About K3s:**
Note: It may make sense to sync with Dave on K3s to briefly demo it.
Resources: K3s args/flags https://rancher.com/docs/k3s/latest/en/installation/install-options/

**UI Rough Concept:**
As mentioned above, we plan to create an annotation on each K3s node that will contain it's config. The UI would need to parse the annotation to display in the Rancher UI. Otherwise, we treat mostly as a normal imported cluster in 2.4.0. We will need to tweak what we see when we edit our K3s cluster, I imagine it would look similar and we add a section for showing basic info about the cluster (how/what/where? obtain from k3s master nodes annotation?) it should at least show the current K3s version in the UI and on the edit page. Editing the cluster will allow us to see a drop-down option for upgrading the K3s cluster. K3s backend will need to have an endpoint to query to see if updates are available.
We may have to support max unavailable (rolling upgrades).

**Comment by davidnuzik** [comment]
Just adding this as a note: This is to go in the existing (ember) UI based on our discussion Tuesday. This does NOT go in the new rancher/dashboard (new UI) for Rancher 2.4.0.

**Comment by deniseschannon** [comment]
As there are 2 specific issues that have rough concepts of the UI changes, I'm going to close this issue. @davidnuzik @maggieliu let's use the other 2 issues to track progress.
