### ISSUE TITLE
CIS Scan UI/UX review

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#25159]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Result:**
1.  Newest scan should be on top
2.  State should reflect Running/Pass/Fail info
3.  Details should have Fail/Skipped/Info/Pass first sort, secondary is number
4.  Add CIS Scan to cluster menu on dashboard

**Comment by codyrancher** [comment]
2 is actually a backend issue. I've opened a separate issue to track https://github.com/rancher/rancher/issues/25214.

**Comment by sowmyav27** [comment]
**Verified on latest master-head**

- In Cluster --> Tools --> CIS Scans, click on run scans (wait until scan is active and run it again, multiple times). Newest scan is on top.
- In the Details page of the scan, tests are sorted by status - fail/skip/pass and then by the number.
- Add CIS Scan to cluster menu on dashboard: Action can be performed from Cluster page --> Click on the cluster --> Click on more options in the cluster dashboard page, and run cis scan. But issue exists when action is done from the Cluster page - Issue logged - https://github.com/rancher/rancher/issues/25241

@codyrancher @tfiduccia When a user navigates to Cluster page --> Click on the cluster --> Click on more options in the cluster dashboard page, and run cis scan, user is directed automatically to the CIS Scans page, where a scan is seen in `Running` or `Creating` status. Is that how we want it to be? As `Snapshot Now` action on the cluster does not have this behavior.

**Comment by sowmyav27** [comment]
After discussion with @tfiduccia @codyrancher decided to have a growl notification when the following action is performed
Cluster menu/Cluster page --> Run CIS Scan --> Users should see a notification that the scan is running

**Comment by sowmyav27** [comment]
**verified on latest master-head - commit id: `f01cca783`, ui tag: `latest2`**

- Click on the cluster --> Click on more options in the cluster dashboard page, and run cis scan. 
- A notification is seen that the CIS scan is running on the cluster

- Cluster Page --> More options on the cluster --> Run CIS Scan --> A notification is seen that the CIS scan is running on the cluster

- On going to Tools --> CIS Scans --> The latest reports are generated.
