### ISSUE TITLE
CIS compliant cluster fails to come up on master

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25153]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
deploy a CIS compliant cluster (after taking additional manual steps on the nodes)
The cluster fails to come up.

Error on UI: `[controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [ip]: Get https://localhost:6443/healthz: dial tcp 127.0.0.1:6443: connect: connection refused, log: ]`

Error in kube-apiserver:
```
W0129 17:12:08.033343       1 admission.go:47] the DenyEscalatingExec admission plugin is deprecated and will be removed in v1.18
W0129 17:12:08.033365       1 admission.go:48] use of PodSecurityPolicy or a custom admission plugin to limit creation of pods is recommended instead
Error: failed to initialize admission: couldn't init admission plugin "EventRateLimit": no kind "Configuration" is registered for version "management.cattle.io/v3" in scheme "k8s.io/kubernetes/plugin/pkg/admission/eventratelimit/config.go:32"
Usage:
```

**Note:**

- On removing `EventRateLimit` from admission plugin in cluster.yml, the cluster comes up successfully.
- But on running a CIS Scan on the cluster, the `1.1.36` test fails 

**Expected Result:**
Cluster should come up successfully when  `EventRateLimit` is passed in admission plugin list in cluster.yml file

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master - head commit id: `ff4dfd753`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom cluster
- Kubernetes version (use `kubectl version`):

```
1.17.2 and 1.16.6
```

**Comment by leodotcloud** [comment]
Since this change: https://github.com/rancher/rke/commit/25e7f987775dbd0e71dac82d63c0df62f65ca053#diff-ee322344e47d033c1509dc709149f86eR314

the apiVersion is generated as `management.cattle.io/v3` instead of `eventratelimit.admission.k8s.io/v1alpha1`, hence kube-apiserver is crashing.

**Comment by sowmyav27** [comment]
verified on latest master-head - commit id: `ca01ddff2`

Deploy a cluster - CIS compliant.
The cluster fails to come up
Error: `[controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [ip]: Get https://localhost:6443/healthz: dial tcp 127.0.0.1:6443: connect: connection refused, log: ]`
Logs:
`Error: failed to initialize admission: couldn't init admission plugin "EventRateLimit": no kind "Configuration" is registered for version "management.cattle.io/v3" in scheme "k8s.io/kubernetes/plugin/pkg/admission/eventratelimit/config.go:32"`

**Comment by leodotcloud** [comment]
@sowmyav27 this issue was not yet ready to test, as the rke changes were not pulled into rancher yet. I will get another PR out for that.

**Comment by sowmyav27** [comment]
**verified on latest master-head - commit id: `f01cca783`**

- Deployed a cluster which is CIS compliant. 
- Cluster comes up successfully.
- Go to tool --> CIS Scans --> Run Scan 
- Security scan is run on the cluster and report is generated.
- Expected failures/passes seen
