### ISSUE TITLE
Services with health checks sometimes get stuck in degraded/initializing

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#2516]
In building my kubernetes stack, when I added health checks, about half the time, the services/containers never got passed the degraded/initializing phase.

**Comment by cusspvz** [comment]
This happens to me with hosts that are going to be or are in "Reconnecting" state.

**Comment by alena1108** [comment]
@cusspvz we've put a bunch of fixes related to healthchecks + hosts in reconnecting state combination - all will be available in next rancher release. The problem @cjellick is facing, is different. Today we don't support health checks for instances having Host networking. So if the health check is specified for such instance, the instance will be in initializing state forever.

**Comment by janeczku** [comment]
This just happened to me with Rancher DNS service on a new DigitalOcean host and i can't get it working. Can you advise how to troubleshoot/debug the stuck in initializing sate @alena1108?

**Comment by will-chan** [comment]
not enough information here so closing issue.

**Comment by raphink** [comment]
I'm using rancher 0.56.1 and seeing this behavior:

Services I've set health checks for start fine, work fine (they're even behind a LB and working good). I see the health checks in the container logs passing (and returning a 200 code), but both services are marked as "Initializing".

**Comment by raphink** [comment]
Also, the load-balancer itself (using rancher/load-balancer-service, with a health-check) is marked as "Initializing" as well, even though it is working fine.

**Comment by raphink** [comment]
![screenshot from 2016-02-02 21 06 36](https://cloud.githubusercontent.com/assets/650430/12762736/e5407144-c9f0-11e5-82fd-661ae7971e66.png)


and the bottom of the load-balancer logs (one of the containers):

![screenshot from 2016-02-02 21 07 13](https://cloud.githubusercontent.com/assets/650430/12762756/02b682ea-c9f1-11e5-81d4-2a0267c8d9a9.png)

**Comment by raphink** [comment]
Edit: after a while, the mapserver service was not load-balanced anymore. Stop and restarting it put it behind the LB again. That container an standard Apache container. Here's an excerpt of its logs, showing the health check pings passing:

![screenshot from 2016-02-02 21 10 15](https://cloud.githubusercontent.com/assets/650430/12762832/73138fa6-c9f1-11e5-9a8b-33583c8b1e13.png)

**Comment by raphink** [comment]
I removed switched a TCP check instead of an HTTP check (removed the `request_line:` parameter) and I'm still seeing the same behavior (services marked as "Initializing")

**Comment by raphink** [comment]
Upgrading services to remove the health checks completely sets them to the "Active" state. The load-balancer however is still marked as "Initializing", even after a restart.

**Comment by raphink** [comment]
OK, that turned out to be a firewall issue. When I added a rule to my security group to allow all traffic on all protocols from all sources, the health checks passed. However, allowing them from within the security group of the nodes or from the rancher server did not need to suffice.

Which firewall rules are actually necessary for health checks to work properly?

**Comment by deniseschannon** [comment]
Health check ports for load balancers are port 42.
