### ISSUE TITLE
Rancher/Jumpcloud ldap authentication fails when "Enable as LDAP Bind DN" is not set on user

### ISSUE THREAD

**Issue by jgournet** [rancher/rancher#25165]
**What kind of request is this (question/bug/enhancement/feature request):**
- bug

**Steps to reproduce (least amount of steps as possible):**
- setup Jumpcloud as an openldap provider
- when testing the connection:
1) try with a user without "Enable as LDAP Bind DN" (ie: normal user) => fail
2) try with a user with "Enable as LDAP Bind DN" => success

**Result:**
When trying, I get this
https://MY_RANCHER_HOST/login?errorMsg=authFailedCreds
```
2020/01/29 23:44:11 [DEBUG] Now generating Ldap token
2020/01/29 23:44:11 [DEBUG] Now creating Ldap connection
2020/01/29 23:44:11 [DEBUG] Binding service account username password
2020/01/29 23:44:11 [DEBUG] Binding username password
```

**Environment information**
- Rancher version: 2.3.4
- Installation option: single install

**Comment by jgournet** [comment]
Update:
This is happening because of those lines:
https://github.com/rancher/rancher/blob/master/pkg/auth/providers/ldap/ldap_client.go#L61-L68
Here, we bind our user to ldap, with their credentials.
The subsequent call to ":searchOpRequest := ldapv2.NewSearchRequest" is then done with user credentials, which fails when that user does not have "LDAP bind DN".

An easy workaround is to:
- either create a new ldap connection and bind to it with our user DN, by adding those lines:
`
        lConnNew, err := ldap.Connect(config, caPool)
        if err != nil {
                return v3.Principal{}, nil, err
        }
        defer lConnNew.Close()


`
(and then changing the "user bind" to use "lConnNew")
- or: rebind with the service account right after binding the user:
`        
        err = lConn.Bind(serviceAccountUserName, serviceAccountPassword)
        if err != nil {
                return v3.Principal{}, nil, err
        }
`

or someone who knows more about this can come up with a proper solution, rather than a workaround

**Comment by jgournet** [comment]
Hi
This issue is still happening
Is it possible to get it fixed ?

**Comment by sra** [comment]
Yes, please consider fixing this - rancher is the only LDAP integration out of dozens that requires this and the security people hate it.

**Comment by hshimizu** [comment]
We would also like this resolved as we use Jumpcloud.
