### ISSUE TITLE
failed to mount volume backed by NFS in imported K3s cluster 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#25169]
**What kind of request is this (question/bug/enhancement/feature request):**
bug 

**Steps to reproduce (least amount of steps as possible):**
- run Rancher master-head
- imported a k3s cluster (version v1.17.2+k3s1)
- add a PV using the `NFS Sharing` volume plugin 
- add a pvc using the pv
- deploy a workload using the pvc as volume

**Result:**
- the workload is not active because the container cannot mount the volume.

error at the container level:
`
	MountVolume.SetUp failed for volume "a2" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/aa050e9c-178a-4e58-891f-a2e68b8b409c/volumes/kubernetes.io~nfs/a2 --scope -- mount -t nfs 3.133.142.220:/nfs /var/lib/kubelet/pods/aa050e9c-178a-4e58-891f-a2e68b8b409c/volumes/kubernetes.io~nfs/a2 Output: Running scope as unit: run-rc1d14fd53a61425995b3d54f58b33d43.scope mount: /var/lib/kubelet/pods/aa050e9c-178a-4e58-891f-a2e68b8b409c/volumes/kubernetes.io~nfs/a2: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
`

<img width="1403" alt="Screen Shot 2020-01-29 at 5 45 41 PM" src="https://user-images.githubusercontent.com/6218999/73411607-34327780-42c3-11ea-87bb-2e21d68f0172.png">
 

**Other details that may be helpful:**
Not see the problem in another RKE cluster in the same setup. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
master-head 

- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
imported k3s cluster, 1 control plan, 2 workers. 
 
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Ubuntu 18.04.3 LTS

- Kubernetes version (use `kubectl version`):
v1.17.2+k3s1

**Comment by jiaqiluo** [comment]
It turns out this is not a bug in neither Rancher nor k3s.

We see this error because the package `nfs-common` needs to be installed in the OS.

Install the package in the instance solves the problem.
```
sudo apt install nfs-common
```

**Comment by jiaqiluo** [comment]
The issue is reopened because we think k3s should install the nfs-common when provisioning the cluster if RKE installs it.

cc @galal-hussein

**Comment by galal-hussein** [comment]
@jiaqiluo rke doesn't install it to my knowledge

**Comment by deniseschannon** [comment]
@jiaqiluo for an imported RKE cluster, does this work?

**Comment by jiaqiluo** [comment]
@deniseschannon  it works for imported RKE cluster.

**Comment by davidnuzik** [comment]
Based on discussion with the team, we don't believe K3s should be installing OS packages on nodes. This is something we can document, however, so that users are aware of the requirement to have the nfs-common package on any/all nodes in a k3s cluster in this scenario.
I have created an issue to add this in to the docs here: https://github.com/rancher/k3s/issues/1449

As such, I will close this issue. If there are any questions please let me know.
