### ISSUE TITLE
Enable vue UI page in Ember for 2.4

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25168]

**Comment by sowmyav27** [comment]
**On latest master-head, ui tag: latest2**

- Enable "Steve" in "features"
- Navigate to cluster page 
- `Dashboard` is seen

<img width="1116" alt="Screen Shot 2020-02-24 at 10 07 18 AM" src="https://user-images.githubusercontent.com/26032343/75178857-bf016900-56ed-11ea-922b-18e94223c59b.png">

- Clicking on `Dashboard` navigates to `https://<rancher-server>/dashboard/c/c-gdxvw`, but throws the below error.
<img width="478" alt="Screen Shot 2020-02-24 at 10 07 24 AM" src="https://user-images.githubusercontent.com/26032343/75178861-c163c300-56ed-11ea-9fea-2c19e54b1521.png">

**Comment by sowmyav27** [comment]
**Verified on ui tag :latest2 on master-head.**

- Clicking on Dashboard navigates to https://<rancher-server>/dashboard/c/c-gdxvw
<img width="1282" alt="Screen Shot 2020-02-24 at 3 37 13 PM" src="https://user-images.githubusercontent.com/26032343/75200803-8ed0bf00-571b-11ea-95c7-8ee08cf8f63c.png">
