### ISSUE TITLE
changes for kontainer-driver-metadata 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#25162]
Because we currently have both code and data in rancher/kontainer-driver-metadata, vendoring it in different release branches for rancher and rke causes issues. 

- Introduce changes to our build process for rke and rancher so that they stop vendoring kdm and have access to local bin data file
- Update rke and rancher to load data from this local file

**Comment by Oats87** [comment]
Having the RKE CLI be able to consume a `data.json` would be amazing

**Comment by StrongMonkey** [comment]
Discussed with @kinarashah, the current logic for syncing kdm is use catalog url to fetch `data.json` first, then fallback to vendor file.(Assuming fallback method is needed in case catalog sync failed or air-gap installation). The goal is to move away from vendor file and only use `data.json` as source of truth. Same applies to RKE.

**Comment by kinarashah** [comment]
@StrongMonkey sounds good, just to clarify, we don't currently have any vendor file, as in we don't have vendored data.json but it's just structs

**Comment by StrongMonkey** [comment]
Related PRs: 
https://github.com/rancher/types/pull/1088
https://github.com/rancher/rke/pull/1910 
https://github.com/rancher/kontainer-driver-metadata/pull/136
https://github.com/rancher/types/pull/1088

**Comment by StrongMonkey** [comment]
This issue is available to test. This actually introduce no functionality change, but we need to verify there is no regression.

To verify this, try to provision RKE cluster in a normal or airgap setup. All the image should still be download and components should be brought up.

**Comment by jiaqiluo** [comment]
do the following preparation before doing validations
- Run Rancher:master-head 7640e89b0 and check the builtin k8s versions as the following:
```
- 1.17.3-rancher1-1 (default)
- 1.16.7-rancher1-1
- 1.15.10-rancher1-1
```
<img width="705" alt="Screen Shot 2020-02-26 at 3 43 35 PM" src="https://user-images.githubusercontent.com/6218999/75396997-0e44c680-58b3-11ea-92d2-32b410e91155.png">

- Copy the builtin `data.json` file and host it at a server so Rancher can download from an URL

**Validation 1:**
- edit the copy to add a new k8s version, saying `1.17.4-rancher1-1`
- go to Settings -> rke-metadata-config to change the URL to point to the copy

Results:
- Rancher logs show the following message which indicates a refresh is trigged
```
2020/02/27 00:38:53 [INFO] Refreshing driverMetadata in 1440 minutes
2020/02/27 00:38:53 [INFO] driverMetadata: refreshing data from upstream https://raw.githubusercontent.com/jiaqiluo/kontainer-driver-metadata/issue-25162/data/data.json
```

- In Rancher UI, go to the cluster provision page, see the new k8s version is showing in the list
![image](https://user-images.githubusercontent.com/6218999/75397574-72b45580-58b4-11ea-8fab-2535dded3ae6.png)


**Validation 2:**
- change the default to be `1.16.x` in the data.json file
```
  "RancherDefaultK8sVersions": {
    "2.3": "v1.17.x",
    "2.3.0": "v1.15.x",
    "2.3.1": "v1.15.x",
    "2.3.2": "v1.15.x",
    "2.3.3": "v1.16.x",
    "default": "v1.16.x" <--- this line
  },
```
- go to tools -> drivers and click `refresh kubernetes metadata`

Results:
- Rancher logs indicate a refresh is triggered
```
2020/02/27 00:46:30 [INFO] driverMetadata: refreshing data from upstream https://raw.githubusercontent.com/jiaqiluo/kontainer-driver-metadata/issue-25162/data/data.json
```

- in Rancher UI, the default version showing in the cluster provision page is `v1.16.7-rancher1-1`
- also in the api:
```
"default": "v1.16.7-rancher1-1",
"id": "k8s-version",
```

**Validation 3:**
-  go to Settings -> rke-metadata-config to change the refreshing interval to 1
```
"refresh-interval-minutes": "1",
```
- edit the data.json file to add a new k8s version `v1.18.1-rancher1-1`, and change the default to `v1.18.x`

Results:
- in Rancher's log, the following shows every minute which indicates the refresh is triggered automatically 
```
2020/02/27 01:07:08 [INFO] Refreshing driverMetadata in 1 minutes
2020/02/27 01:07:08 [INFO] driverMetadata: refreshing data from upstream https://raw.githubusercontent.com/jiaqiluo/kontainer-driver-metadata/issue-25162/data/data.json
2020/02/27 01:08:08 [INFO] Refreshing driverMetadata in 1 minutes
2020/02/27 01:08:08 [INFO] driverMetadata: refreshing data from upstream https://raw.githubusercontent.com/jiaqiluo/kontainer-driver-metadata/issue-25162/data/data.json
2020/02/27 01:09:08 [INFO] Refreshing driverMetadata in 1 minutes
2020/02/27 01:09:08 [INFO] driverMetadata: refreshing data from upstream https://raw.githubusercontent.com/jiaqiluo/kontainer-driver-metadata/issue-25162/data/data.json
```

- in Rancher UI, the new version shows up as the default value
![image](https://user-images.githubusercontent.com/6218999/75403000-93d07280-58c3-11ea-90b5-a2beecbc2644.png)
- the values under v3/settings also reflect the changes

**Comment by jiaqiluo** [comment]
The following validations are done on an air-gapped setup Rancher:v2.4.0-rc1, single install

Validation 1:
- provision a cluster for each supported k8s version with the embedded metadata 
- confirm that clusters are active and use the same set of images as the clusters provisioned in a non-air-gapped setup with the same k8s version


Validation 2:
- host the data.json file and change the url in settings to point to that file
- add a new k8s version to the data.json file, and trigger a refresh in Rancher
- confirm that the new k8s version shows up in Rancher
