### ISSUE TITLE
Change default VM hardware version of RancherOS

### ISSUE THREAD

**Issue by smart-nickname** [rancher/rancher#25174]
What kind of request is this:
New feature

Steps to reproduce:
1. Add a new cluster with vSphere provider. Use node templates with Creation method - Install from boot2docker ISO.
2. Look for provisioned VM's properties in vCenter: select a VM, on Summary tab navigate to VM Hardware, Compatibility.

Result:
Node VMs have VM version 14.

Desired result:
Node VMs have VM version 15.

Reason:
VM hardware version 15 is a requirement for VMware CSI.

Other details that may be helpful:
vCenter v6.7.0.42000 Build number 15132721
Rancher v2.3.4, UI v2.3.32, RancherOS 1.5.5

**Comment by krise86** [comment]
I added a configuration paramter to the node template, seems to work.
virtualHW.version=15

**Comment by smart-nickname** [comment]
Thanks krise86, but this didn't work for me. VM version of provisioned VMs remains the same.

**Comment by bofh666** [comment]
> I added a configuration paramter to the node template, seems to work.
> virtualHW.version=15

Didn't work for me either.

**Comment by ThunderRush** [comment]
We have the same issue with 2.3.5

**Comment by janeczku** [comment]
@smart-nickname Could you provide your vSphere and ESXi Versions? By default the VMs should have the latest HW version supported by the ESXi version running on the hypervisor: https://kb.vmware.com/s/article/1003746

**Comment by smart-nickname** [comment]
@janeczku 
vCenter version 6.7.0.43000, build 15976714 (latest)
ESXi version 6.7 Update 3, build 15160138

Both Host level and Datacenter level Default VM Compatibility are set to ESXi 6.7 Update 2 (hardware version 15)

**Comment by AcidAngel21** [comment]
We have the same issue with 2.4.3

**Comment by betworks** [comment]
Bump.. Same issue with 2.4.10.. 
Host, Cluster and Datacenter default VM Compat are all set to 15 but RancherOS (docker-machine?) still creates new VM's with 14.

15 is required for out of tree provider :(

**Comment by skyscooby** [comment]
Same issue with 2.4.10..

rancherOS docker-machine created VM's are created with V 14 compatibility even when datacenter, cluster and host default Compatibility is set to V 15

**Comment by epacke** [comment]
I ran into this too when writing up an article on how to install and use the Vpshere out-of-tree provider.  The solution is at the bottom of this section of the article:

https://loadbalancing.se/2021/04/04/rancher-vsphere-out-of-tree-provider/#VM_Machine_version

Hope it helps someone else.
