### ISSUE TITLE
Rancher redirects to https although 'tls' is set to 'external'

### ISSUE THREAD

**Issue by llech** [rancher/rancher#25176]
I've set up rancher following the installation instructions https://rancher.com/docs/rancher/v2.x/en/installation/options/helm2/helm-rancher/. The installed version is 2.3.5

I need rancher intern, so I've used 'tls'='external'

My values.yaml are as follow:

tls: external
hostname: rancher.k8s.mydomain 
replicas:1

However, curling rancher.k8s.mydomain has given me 302 to https. I've logged into rancher pod and executed: 

sh-4.4# curl -i localhost:80
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: https://localhost/
Date: Thu, 30 Jan 2020 15:03:23 GMT
Content-Length: 41

<a href="https://localhost/">Found</a>.

Which results with 'not found' when called externally, because Ingress specifies (correctly) only http endpoint...

There are errors in log:
2020/01/30 13:24:46 [INFO] Redeploy Rancher Agents is needed for local: forceDeploy=false, agent/auth image changed=true, private repo changed=false
2020/01/30 13:24:46 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set

Environment information:

kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", Build
Date:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", Build
Date:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd

helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

 docker version

Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by superseb** [comment]
The redirect in the ingress controller is controlled by the value external as seen here: https://github.com/rancher/rancher/blob/v2.4.3/chart/templates/ingress.yaml#L15

Rancher itself will not redirect based on the required headers being set, as described on https://rancher.com/docs/rancher/v2.x/en/installation/options/helm2/helm-rancher/chart-options/#required-headers

**Comment by imriss** [comment]
@llech, sorry to comment in a closed ticket. Have you been able to find a workaround? Thanks

**Comment by llech** [comment]
> @llech, sorry to comment in a closed ticket. Have you been able to find a workaround? Thanks

No, sorry. I was hoping it will work out-of-the-box, without scrolling through sources. I didn't have time for biting through the internals.

**Comment by ToniIltanen** [comment]
the nginx header forwarding option does not fix this issue, still the forwarding is to 443 instead 80. i also couldn't get the ingress to work with external tls using the default ingress controller instead nginx.

**Comment by d02540315** [comment]
I have same issue today even though set tls=external. 

![image](https://user-images.githubusercontent.com/5162421/158806293-5c3c7c3a-43db-401c-8ca7-d1f192fed9ca.png)

**Comment by zhaque44** [comment]
@d02540315 @ToniIltanen any luck with this?

**Comment by ToniIltanen** [comment]
@zhaque44 Nope, we changed to openshift
