### ISSUE TITLE
Allowed to have same name for sidekick services that are part of different primary launch config with in the same stack.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2517]
Server version - Build from master

Create a stack.
Create service S1- with side kick service name - "sk1"
Create another service S2 in the same stack  with side kick service name - "sk1"

Generated config for this stack , has only 1 service name - "sk1" defined in it.

if "sk1" service from both the services have exposed ports , only 1 DNS entry gets created which represents either one of these services.

We should either prevent the creation of sidekick services with same names within a stack , or we should be able to uniquely identify them by probably appending the primary service name to it ?

**Comment by alena1108** [comment]
@sangeethah same name for the sidekick cross services should be allowed. But when build fqdn, the name should be generated this way:

sidekickname.servicename.stackname.environmentname.rootdomain

**Comment by alena1108** [comment]
Sidekick name should respect the same limitation as a service name - it should be unique per stack

**Comment by sangeethah** [comment]
Tested with server version - v0.50.0-rc1

We are not allowed to create services which have primary service name /sidekick names set to an existing primary service name /sidekick name from the same stack.
