### ISSUE TITLE
Monitoring - some graphs are missing in the imported K3s clusters

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#25180]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher master-head
- imported a k3s cluster (version v1.17.2+k3s1)
- enable the cluster monitoring (0.0.7)

**Result:**
- on the cluster page, the following graphs are missing in the `Kubernetes components Metrics` section
```
    "ingresscontroller-nginx-connection",
    "apiserver-request-count",
    "controllermanager-queue-depth",
    "scheduler-e-2-e-scheduling-latency-seconds-quantile",
    "apiserver-request-latency",
```

- go to the detail page of any workload, the following graphs are missing in the `Workload Metrics` section
```
    "workload-network-packet",  
    "workload-network-io", 
```

**Comment by dnoland1** [comment]
@jiaqiluo @mrajashree  - I've also noticed when I import a two node k3s cluster, I'm only seeing metrics for one of the two nodes:
![image](https://user-images.githubusercontent.com/468462/75616196-2874e380-5b03-11ea-9e3f-3c34fa1faa58.png)

Node exporter is running on both nodes:
```
> kubectl get pods -n cattle-prometheus -o wide | grep exporter-node
exporter-node-cluster-monitoring-8d6ls                     1/1     Running   0          69m   10.100.104.57    ip-10-100-104-57    <none>           <none>
exporter-node-cluster-monitoring-rhjcb                     1/1     Running   0          69m   10.100.105.169   ip-10-100-105-169   <none>           <none>
```
I can curl metrics port on both:
```
root@ip-10-100-105-169:~# curl localhost:9100
<html>
                        <head><title>Node Exporter</title></head>
                        <body>
                        <h1>Node Exporter</h1>
                        <p><a href="/metrics">Metrics</a></p>
                        </body>
                        </html>root@ip-10-100-105-169:~#

root@ip-10-100-104-57:~# curl localhost:9100
```
```
<html>
                        <head><title>Node Exporter</title></head>
                        <body>
                        <h1>Node Exporter</h1>
                        <p><a href="/metrics">Metrics</a></p>
                        </body>
                        </html>root@ip-10-100-104-57:~#
```
This same or similar issue to what you observed above with some graphs being missing? Let me know if I should open a separate bug. FYI - this was observed on Rancher v2.3.5 with k3s 1.17.3 imported cluster.

**Comment by dnoland1** [comment]
Disregard my comment above. I wasn't getting metrics on the other node due to firewall settings.

**Comment by deniseschannon** [comment]
Based on comments in this issue: https://github.com/rancher/rancher/issues/25201

If the only comment about the fact that these graphs are missing from k8s 1.16 to k8s 1.17, I'm not sure how much we need to investigate. 

We know that these 2 were dropped from the k8s 1.17 API
``` 
 "apiserver-request-count", 
    "apiserver-request-latency",
```

This graph `"scheduler-e-2-e-scheduling-latency-seconds-quantile", ` was intentionally dropped from the latest monitoring chart.

The other missing charts could easily be from dropping from the API or chart. I think it's safe to close this issue and if there is a need to investigate further, we can do so at a user's request. 
```
"ingresscontroller-nginx-connection",
    "controllermanager-queue-depth",
```
