### ISSUE TITLE
Rancher Compose variable substitution eats '=' sign

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#2518]
The variable substitution of Rancher Compose Executor is causing logstash configurations to get corrupted.

Godeps for libcompose is out of sync between v0.4.3 and v0.5.0. Looking at this [Comparison](https://github.com/rancher/rancher-compose/commit/97f492e5486a76b86ab47f4efb18b9ca49e7b842) you can see the libcompose fix was removed from the v0.5.0 version in the file project/interpolation.go

You can reproduce this issue in v0.43.1 by:
1. create elasticsearch cluster
2. create logstash stack.
3. View config and the logstash-collector-config will have  `outputs: "elasticsearch {\n  host \n"` which does not match what was sent in.

**Comment by sangeethah** [comment]
Tested with rancher-compose version - v0.5.2-rc2

When using exported variables that have "=" , variable substitution happens as expected.

**Comment by sangeethah** [comment]
Will wait for  v0.5.2-rc2 version of rancher-compose to be packaged with a cattle release to test for variable substitution to happen correctly for logstash stack.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v0.46.0-rc2 . 
Able to start logstash stack successfully.

Following is the substituted value for - indexer_outputs:
      outputs: |+
        elasticsearch {
          host => "elasticsearch"
          protocol => "http"
          index => "logstash-%{+YYYY.MM.dd}"
        }

and for collector_inputs:

        udp {
          port => 5000
          codec => "json"
        }
