### ISSUE TITLE
[feature request] Graphite adapter for rancher container metrics

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2519]
Currently it seems that rancher show metrics in realtime, please make ability to connect graphite to Rancher for long-term storing metrics, then we, users, by our own efforts can analyze whats going on  hosts. btw you may provide some common metric reports/alarms in UI and even make this payable, one of many ways of monetization :P

**Comment by pboos** [comment]
This would be great for monitoring!

**Comment by fernandoneto** [comment]
+1

**Comment by lesaux** [comment]
+1

**Comment by Robbie1977** [comment]
+1

**Comment by vincent99** [comment]
Admin -> Settings -> Advanced:

![image](https://user-images.githubusercontent.com/753917/39334157-656cb5f6-4962-11e8-8876-735b8f62423f.png)
