### ISSUE TITLE
Cluster goes to unavailable because failed to communicate with API server: Unauthorized 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#25194]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:master-head ff4dfd753
- add a DO cluster 
We had run few automation runs on this setup. 
Dont know specific steps that lead to this problem.

**Result:**
- as admin, I can not go the cluster page for the cluster `santest1`. I see this error in the network track.
<img width="709" alt="Screen Shot 2020-01-31 at 12 10 06 PM" src="https://user-images.githubusercontent.com/6218999/73568701-3234f980-4426-11ea-9f1a-aba5ebdc99b8.png">
<img width="639" alt="Screen Shot 2020-01-31 at 12 40 38 PM" src="https://user-images.githubusercontent.com/6218999/73569188-2564d580-4427-11ea-944f-c716eb34bb67.png">
<img width="630" alt="Screen Shot 2020-01-31 at 12 41 59 PM" src="https://user-images.githubusercontent.com/6218999/73569189-25fd6c00-4427-11ea-96aa-5cb1f4f39d46.png">

and UI shows this sometimes:
<img width="351" alt="Screen Shot 2020-01-31 at 12 09 26 PM" src="https://user-images.githubusercontent.com/6218999/73568769-51338b80-4426-11ea-8141-4c8b06cb0888.png">

in Rancher's log:
```
2020/01/31 19:25:38 [ERROR] [updateClusterHealth] Failed to update cluster [c-dg9h8]: Operation cannot be fulfilled on clusters.management.cattle.io "c-dg9h8": the object has been modified; please apply your changes to the latest version and try again
2020/01/31 19:25:41 [ERROR] ClusterController _all_ [user-controllers-controller] failed with : failed to start user controllers for cluster c-dg9h8: failed to contact server: Unauthorized
2020/01/31 19:26:11 [INFO] deploy istio metric expression into CLuster c-dg9h8 successfully
2020/01/31 19:26:11 [INFO] deploy istio metric expression into CLuster c-dg9h8 successfully
2020/01/31 19:26:13 [ERROR] ClusterController _all_ [user-controllers-controller] failed with : failed to start user controllers for cluster c-dg9h8: failed to contact server: Unauthorized
2020/01/31 19:26:45 [INFO] deploy istio metric expression into CLuster c-dg9h8 successfully
2020/01/31 19:26:45 [INFO] deploy istio metric expression into CLuster c-dg9h8 successfully
2020/01/31 19:27:17 [ERROR] ClusterController _all_ [user-controllers-controller] failed with : failed to start user controllers for cluster c-dg9h8: failed to contact server: Unauthorized
```

- the cluster goes to the unavailable state with the error message: 
```
 failed to communicate with API server: Unauthorized 
```
<img width="1474" alt="Screen Shot 2020-01-31 at 12 25 28 PM" src="https://user-images.githubusercontent.com/6218999/73568567-e97d4080-4425-11ea-9e05-4be56368b48e.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher:master-head ff4dfd753

- Installation option (single install/HA):
single install 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Infrastructure Provider, DO

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
Rancher Server 
```
(Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by deniseschannon** [comment]
@jiaqiluo when you have aother setup that gets to this state, can you share with @ibuildthecloud

**Comment by deniseschannon** [comment]
@jiaqiluo it looks like we have fixed some of the websocket issues with https://github.com/rancher/rancher/pull/25255. Can you re-open if you see it again?

**Comment by jiaqiluo** [comment]
This bug is not seen in the latest master-head when running automation on it.
The issue will be reponed if needed.
