### ISSUE TITLE
Support for Oracle Linux 7.7

### ISSUE THREAD

**Issue by flrichar** [rancher/rancher#25192]
Validation for Oracle Linux 7.7 with varying kernels, UEKr4, UEKr5, UEKr6.  Docker 19.03.

**Comment by aaronRancher** [comment]
Oracle Linux 7.7 `UEKr5` with Docker 19.03 is validated using existing automation.

**Comment by sangeethah** [comment]
After discussing with @cloudnautique  , `UEKr6` is not scoped for 2.4.0 release . We will take up the certification of  `UEKr4`  if there is a customer request targeted to this specific kerner version.

**Comment by aaronRancher** [comment]
Oracle Linux 7.7 UEKr5 with Docker 19.03 is validated for Rancher HA install.
ami: `ami-000827bde0b52a728`
Kernel: `4.14.35-1902.8.4.el7uek.x86_64`

**Comment by cloudnautique** [comment]
@sangeethah , yes we can use certify the newer Kernel post 2.4.0.
