### ISSUE TITLE
Conflicts with name generation

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#25196]
With many of the same thing and relying on name generation there can be name conflicts. When this happens the call fails which causes issues with things like terraform. 

Rancher should rely on k8s to gen a name instead of doing it internally.

**Comment by bmdepesa** [comment]
rancher/rancher:master 636311443

There's not really a good way to test this one at scale from the QA side, so tests focused around ensuring resource names continue to be generated correctly. This was originally only reproduced a few times w/ cluster names when the number of clusters was high (~2000).

* Created several clusters
* Cluster names continue to be randomly generated and in the correct format `c-hkm48` 
* Other resource names are in correct formats: `user-xhqb6`, `p-jv2cm`
* Automation passes without unusual failures
