### ISSUE TITLE
Cluster creation stuck at "Pre-pulling kubernetes images" on ubuntu node

### ISSUE THREAD

**Issue by georgr** [rancher/rancher#25209]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Install rancher server
Add cluster
From existing nodes
Enter cluster name: home
Next
Add node roles: etcd, control plane worker
Copy docker command

Ubuntu LTS 18.04 node with docker 18.09 installed
Paste docker command from rancher sever

**Result:**
Rancher server:
Pre-pulling kubernetes images

Ubuntu node:
```
docker ps -a
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                      PORTS               NAMES
aa3591384e24        rancher/coreos-etcd:v3.4.3-rancher1   "/usr/local/bin/etcd…"   10 minutes ago      Up 10 minutes                                   etcd
7f4d1fb20132        rancher/rke-tools:v0.1.52             "/bin/bash"              16 minutes ago      Exited (0) 16 minutes ago                       cluster-state-deployer
74785ac2857a        rancher/rancher-agent:v2.3.5          "run.sh --server htt…"   16 minutes ago      Up 16 minutes                                   agitated_jones
5226aecb9fe8        rancher/rancher-agent:v2.3.5          "run.sh -- share-roo…"   16 minutes ago      Up 16 minutes                                   share-mnt
c7cc63fd77da        rancher/rancher-agent:v2.3.5          "run.sh --server htt…"   16 minutes ago      Up 16 minutes                                   modest_diffie
```

Log extract of container 5226aecb9fe8:

```
+ docker run --privileged --net host --pid host -v /:/host --rm --entrypoint /usr/bin/share-mnt rancher/rancher-agent:v2.3.5 --node-name rancher-worker04 /var/lib/kubelet /var/lib/rancher -- norun
Incorrect Usage.

NAME:
   /usr/bin/share-mnt - A new cli application

USAGE:
   /usr/bin/share-mnt [global options] command [command options] [arguments...]

VERSION:
   1d97ce9

COMMANDS:
   help, h	Shows a list of commands or help for one command
   
GLOBAL OPTIONS:
   --stage2		
   --help, -h		show help
   --version, -v	print the version
   

time="2020-02-02T19:44:05Z" level=fatal msg="flag provided but not defined: -node-name" 
+ docker start kubelet
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.3.5
- Installation option (single install/HA):
single install

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Also tried with docker 19.03.5 with the same share-mnt error in the container

**Comment by superseb** [comment]
This should only break provisioning if the OS actually needs share-root to be run, which is not Ubuntu 18.04. I created https://github.com/rancher/rancher/issues/25244 for the error seen in `share-mnt`.

As Kubernetes components are already running, this confirms cluster provisioning works. Being stuck on `Pre-pulling` is either a full disk, slow connection to Docker Hub (assuming its pulling from Docker Hub) or a Docker daemon stuck in pulling (which is mostly on older Docker versions).

What are in the Docker daemon logs when this happens? What happens when you manually pull the image on that node?

**Comment by georgr** [comment]
Thanks for the hint, the disks are full.
