### ISSUE TITLE
RKE cluster fails to deploy

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25204]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy an rke cluster - DO/AWS - 5 nodes - 1 etcd, 1 control plane, 3 worker nodes (tried with a custom - 1 node - all roles also)
- The cluster fails to come up.
- Cluster is stuck in provisioning state, error: `Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) []` on the UI
- On checking rancher logs - `rancher/rancher-agent:master-head` keep restarting
- logs of the agent container:

```
ERROR: Please check if the correct certificate is configured at https://rancher-server/v3/settings/cacerts
INFO: Arguments: --server https://rancher-server --token REDACTED --ca-checksum 48a041033e42d49f56b748b579f3aa6172a787523f673c94224dcb9c131256f5 -r -n m-g95gr
INFO: Environment: CATTLE_ADDRESS=ip CATTLE_AGENT_CONNECT=true CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=m-g95gr CATTLE_SERVER=https://rancher-server CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 67.207.67.3 nameserver 67.207.67.2
INFO: https://rancher-server/ping is accessible
INFO: Value from https://rancher-server/v3/settings/cacerts is an x509 certificate
ERROR: Configured cacerts checksum (fb5552604ef8b0b0ad24f98afb37712f77ad5bb836e8a36dcfc4be410d9cdbee) does not match given --ca-checksum (48a041033e42d49f56b748b579f3aa6172a787523f673c94224dcb9c131256f5)
ERROR: Please check if the correct certificate is configured at https://rancher-server/v3/settings/cacerts
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `537896429`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO/ AWS
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
1.17.2
```

**Comment by sangeethah** [comment]
Tested with latest build from master - Rancher version `e9b7af681`.

The issue is still reproducible .
Not able to bring up any RKE cluster.
rancher/rancher-agent:master-head keep restarting
logs of the agent container:

```
INFO: Using resolv.conf: nameserver 67.207.67.2 nameserver 67.207.67.3
INFO: https://<rancher-server ip>/ping is accessible
INFO: Value from https://<rancher-server ip>/v3/settings/cacerts is an x509 certificate
ERROR: Configured cacerts checksum (48d5c3abd34aba1709c309490b8a602e38c50c3f0f64d720925f4c7f41e6d1e9) does not match given --ca-checksum (3dd229922de70a8574ebdcb7b35660a89bf406a472b3963611fcd98d7032517e)
ERROR: Please check if the correct certificate is configured at https://<rancher-server ip>/v3/settings/cacerts
```

**Comment by sowmyav27** [comment]
**verified on master-head latest - commit id `92117c9bd`**

- RKE cluster comes up fine. No error seen.
- RKE custom cluster also is deployed successfully.
