### ISSUE TITLE
Monitoring - some graphs are missing in the custom RKE cluster using SUSE 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#25200]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.3.5 or master-head
- add a custom cluster
```
k8s: v1.17.2 
OS: SUSE Linux Enterprise Server 12 SP5
```
- enable the cluster monitoring (0.0.7)
- check requests sent to Rancher server for metrics data

**Result:**
- 1 new graph is added to the section `etcd metrics` 
```
etcd-peer-traffic
```

- the following 1 new graphs are added to the section `Kubernetes component metrics`
```
 ingresscontroller-request-process-time 
```

- but the following 3 metrics are missing in the section `Kubernetes component metrics`
```
 "apiserver-request-count"
 "scheduler-e-2-e-scheduling-latency-seconds-quantile"
 "apiserver-request-latency"
```

- there are no metrics for nodes
<img width="1463" alt="Screen Shot 2020-01-31 at 5 47 44 PM" src="https://user-images.githubusercontent.com/6218999/73583904-f9127e80-4451-11ea-83ab-76a05592ac74.png">

**Comment by sangeethah** [comment]
Are there any specific nodes that needs to be opened for monitoring graphs relating to node metrics to show up? The ports that are currently open on the nodes are - 
```
FW_SERVICES_EXT_TCP="22 80 443 2376 2379 2380 6443 9099 10250 10254 30000:32767"
FW_SERVICES_EXT_UDP="8472 30000:32767"
```

**Comment by jiaqiluo** [comment]
It turns out 
- the problem of missing some graphs are seen in other Rancher provisioned clusters
- the metrics on the node page show up after opening the port 9796 which is used by the node exporter to expose the metrics from nodes.
see https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/prometheus/#node-exporter

Since there is no specific issue for the custom RKE cluster using SUSE, this is closed.
The issue of missing graphs is tracked here: https://github.com/rancher/rancher/issues/25201#issuecomment-581599409
