### ISSUE TITLE
cluster-trigger-logging-deployer-updator always calls delete

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#25215]
cluster-trigger-logging-deployer-updator syncs on multiple objects and for every sync if monitoring is not enabled for that cluster/project it calls a cleanup that always calls the API to delete an app. 

This controller should check the cache before attempting the delete call.

**Comment by dramich** [comment]
Addressed in https://github.com/rancher/rancher/pull/25324

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 9adb67c4f

* No way to easily test this so preformed regression testing through automation
* No unexpected failures
