### ISSUE TITLE
Add dynamic field to features flags

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#25213]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Desired:**
Add dynamic field to feature flags. If dynamic is false, then Rancher will shutdown if the feature flags value is changed. This is ideal for features that need to be setup prior to runtime. If installed with kubernetes, rancher will reboot automatically.

**Comment by ibuildthecloud** [comment]
This flag should be visible to the UI to indicate that if the user enables it the UI may become on responsive for a short period while the feature is updating.

**Comment by sowmyav27** [comment]
Verified on rancher:master-head latest - commit id: `cc12e1d1d`

- Run docker command - fresh install to bring up server - `docker run -d -p 8080:80 -p 443:443 rancher/rancher:master-head`
- Go to /v3/features
- For `steve` feature flag , `dynamic: false` , change the value to True. 
- Rancher is shut off. 
- The container is in exited state.
- On starting the docker container aggain, UI shows `Steve` as enabled feature flag.
- <rancher-server>/dashboard, shows this
<img width="958" alt="Screen Shot 2020-02-14 at 1 03 28 PM" src="https://user-images.githubusercontent.com/26032343/74567615-0c7e1900-4f2b-11ea-88d2-cf85a1aadc42.png">

- <rancher-server>/v1 shows a bunch of this stuff
<img width="644" alt="Screen Shot 2020-02-14 at 1 05 12 PM" src="https://user-images.githubusercontent.com/26032343/74567621-0e47dc80-4f2b-11ea-8487-8c0f769831b5.png">

**Comment by sowmyav27** [comment]
**Verified on a HA setup - 3 nodes**

- When the value for feature flag "steve" is changed, only the leader rancher server gets restarted.
- Logs in the rancher server:

```
2020/02/15 01:50:52 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2020/02/15 01:50:52 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
2020/02/15 02:49:38 [FATAL] feature flag [steve] value has changed, rancher must be restarted
```

**Comment by rmweir** [comment]
@sowmyav27 no it is not. Great catch.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `7d221af9c`**

- HA setup - 3 nodes.

- When the value for feature flag "steve" is changed, all three rancher servers are shut off and restarted
- logs in all the three rancher server show:

```
2020/02/24 16:29:08 [FATAL] feature flag [steve] value has changed, rancher must be restarted
```
