### ISSUE TITLE
DNS resolution fails in a GKE and an AKS cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25210]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy . a GKE cluster - 3 nodes
- Deploy two workloads 

- - 1 workload - wk01 - 1 pod
- - 1 workload - wk02 - daemonset

- Ping wk02 from wk01
```
ping wk02
ping: wk02: Name or service not known
```
- Curl on wk02
```
curl wk02
curl: (6) Could not resolve host: wk02
```

**Note:**
Issue is seen on an AKS cluster also

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `e9b7af681`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): GKE
- Kubernetes version (use `kubectl version`):

```
v1.15.8-gke.2
```

**Comment by daxmc99** [comment]
This doesn't appear to be occurring on GKE and we may be hitting this issue on AKS https://github.com/Azure/AKS/issues/1320#issuecomment-573625107

**Comment by sowmyav27** [comment]
On the latest master, DNS resolution works for an AKS and GKE cluster. (last verified 02/12/2020)
