### ISSUE TITLE
Inconsistent state on startup

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#25216]
When controllers start they can potentially have inconsistent state based on the other controllers they rely on for their data. 

This affects at least Wrangler and Norman. 

- [ ] Wrangler PR

- [ ] Norman PR

**Comment by ibuildthecloud** [comment]
Norman: https://github.com/rancher/norman/pull/340
Wrangler: https://github.com/rancher/wrangler/pull/61

**Comment by bmdepesa** [comment]
rancher/rancher:master-head ad9c7118

Regression test via automation
* Automation for provisioning all cluster types
* Smoke & long running tests
* No unexpected results
