### ISSUE TITLE
CIS Scan - State should reflect Running/Pass/Fail info

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#25214]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Result:**
CIS Scan state should reflect the results of the tests that were run.
We don't want to see `Active` etc. We want to see `Running/Pass/Fail`.

**Notes:**
Referring to the state displayed here.
![Screen Shot 2020-02-03 at 10 37 07 AM](https://user-images.githubusercontent.com/55104481/73676205-3739b900-4671-11ea-98b6-abafcb077e5d.png)

This was originally reported at rancher/rancher#25159 but this is a backend issue so I'm splitting it into a separate issue.

**Comment by sowmyav27** [comment]
**Verified on latest master-head - commit id: `bfa3e1c8a` ui tag: latest2.**

Fail is seen in Red and Pass in Green on UI.
<img width="1333" alt="Screen Shot 2020-03-08 at 9 42 34 AM" src="https://user-images.githubusercontent.com/26032343/76167078-3ccb6880-6121-11ea-9fe9-7f983c8bc5ac.png">

State Transitions currently happening -- Creating --> Running --> Active --> Fail/Pass/Error

For Active state showing, logged bug -- https://github.com/rancher/rancher/issues/25856
