### ISSUE TITLE
[cli] Listing a lot of clusters takes a long time

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#25227]
When listing clusters, there is a secondary call for every cluster to get a node count for that cluster, this is obviously bad in a setup running a high number of clusters. 

This should be moved into a formatter for the cluster so the CLI can stop doing the extra calls.

**Comment by dramich** [comment]
This is available in cli v2.4.3-rc1 2.4 master

**Comment by dramich** [comment]
Testing should include the CLI to validate node counts, and the API by looking at the cluster object which now has a node count. 

Without running a lot of clusters the slowness won't be visible.

**Comment by rancher-max** [comment]
#### Ran Benchmarks on a Rancher v2.4-head server with 25 clusters
Previously, using cli v2.4.0:
```
Time (mean ± σ):      6.902 s ±  0.379 s   [User: 135.6 ms, System: 33.3 ms]
Range (min … max):    6.405 s …  7.325 s   
```

With v2.4.3-rc1:
```
Time (mean ± σ):      4.734 s ±  0.583 s    [User: 75.0 ms, System: 14.6 ms]
Range (min … max):    3.697 s …  5.044 s
```

- Time has been reduced by approx. 31%
- Correct node counts are still returned in the `rancher cluster ls` call.
- Also validated in cluster API there is a field called `nodeCount` which lists the correct number of nodes

**Comment by rancher-max** [comment]
#### Ran Benchmarks on a Rancher v2.4-head server with 120 clusters

Previously, using cli v2.4.0:
```
Benchmark #1: rancher cluster ls
  Time (mean ± σ):     41.345 s ±  0.610 s    [User: 281.0 ms, System: 81.3 ms]
  Range (min … max):   40.322 s … 41.882 s    5 runs
```

With v2.4.3-rc1:
```
Benchmark #1: rancher cluster ls
  Time (mean ± σ):     24.802 s ±  0.662 s    [User: 110.8 ms, System: 20.9 ms]
  Range (min … max):   23.670 s … 25.421 s    5 runs
```

- Time reduction is more significant as we increase cluster size. 
This has been fixed
