### ISSUE TITLE
UI for OPA gatekeeper

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25232]
Main Epic: rancher/rancher#23753
UI Need:
* UI to deploy/enable OPA similar to Monitoring
* UI to edit/import contraints template
* UI to indicate violation on existing resources based on enabled constraints

**Comment by tfiduccia** [comment]
Notes from meeting:

Similar to Istio
How to:
1.  Deploy OPA - wireframe for ember UI  (need fields from backend).
2.  Provide a constraints template
3.  Provide list of already deployed resources that are in violation

Stretch - constraints template library.

**Comment by maggieliu** [comment]
Moved issue to Dashboard repo
