### ISSUE TITLE
Warn if rancher compose has been upgraded but not rancher server

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2524]
There have been issues where people have upgraded rancher compose, but haven't upgraded rancher server. 

Since rancher-server and rancher-compose are pinned to each other in terms of compatibility, we should warn users if their version of rancher-compose doesn't work with their older rancher-server version. 

Note: If you upgrade rancher-server, but forget to upgrade rancher-compose, we already have a warning that a newer version of rancher-compose is available.

**Comment by kaos** [comment]
Isn't this covered by #1725 ?

**Comment by ibuildthecloud** [comment]
In this situation we can probably error out.  For example, with Docker if I use a 1.9 client against a 1.8 server it just displays an error.

**Comment by deniseschannon** [comment]
@kaos The note that I covered is what was fixed for #1725.
