### ISSUE TITLE
"Error connecting to WebSocket" error seen often

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25256]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Login to rancher - master-head latest
- Keep seeing this issue - "Error connecting to WebSocket"
<img width="1649" alt="Screen Shot 2020-02-04 at 11 57 44 AM" src="https://user-images.githubusercontent.com/26032343/73781891-ee9fff80-4745-11ea-9c3a-a02b749b6747.png">

**Note:**

- It is not specific to adding a cluster.
- It happens almost always now.
- Logout/refresh/clearing cache  - does not seem to help
- Not able to do a kubectl, view logs, exec shell into workloads because of this.
- Not able to create clusters - rke
error seen:
`Failed while: Wait for Condition: InitialRolesPopulated: True`

**Expected Result:**
"Error connecting to WebSocket" error should NOT be seen

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - ui tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by westlywright** [comment]
Per offline discussion this was unrelated to UI.

**Comment by sowmyav27** [comment]
on the latest master-head - commit id: `ca01ddff2`, this issue is not seen anymore.

**Comment by davidnuzik** [comment]
Appears to be fixed via https://github.com/rancher/rancher/pull/25255 I believe. I can no longer reproduce the issue on the same verison of master-head (latest as of 2/5/20, version `ca01ddff2`)

**Comment by deniseschannon** [comment]
@ibuildthecloud put some fixes in that may have fixed this. Can you monitor this and re-open if you see it.

**Comment by sowmyav27** [comment]
Reopening the issue as Websocket issue is seen on an upgrade setup from 2.3-head to master-head latest - commit id: `394aa88d6`

**Comment by sowmyav27** [comment]
verified on an upgrade from 2.3-head latest to master-head latest - commit id: `ff24cb9e3`, no websocket issue seen.
No error seen in the Network tab (dev tools) under subscribe>sockId
