### ISSUE TITLE
Which Rancher version works on 1.16.4 kubernetes version ?

### ISSUE THREAD

**Issue by sd2302** [rancher/rancher#25258]
**What kind of request is this (question/bug/enhancement/feature request):**

Question

Which version of Rancher supports kubernetes 1.16.4 ?

we have a 2.2.1 and we tried to import a 1.16.4 cluster and it went to 'Waiting' stage forever 

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
Supported k8s versions are listed in each release under https://github.com/rancher/rancher/releases/, and 1.16 was made default in 2.3.2 (see https://github.com/rancher/rancher/issues/22965). As 1.16 deprecated API versions (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) it will probably not work until the later versions.

With v2.2.1 being close to a year old, it is recommended to update aside from the 1.16 support.
