### ISSUE TITLE
Fresh install error: unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by adrianovieira** [rancher/rancher#25250]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

- fresh install (rke version v1.0.4)
- following: https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/helm-rancher/
`$ kubectl get pods --namespace cert-manager`
```
cert-manager-754d9b75d9-27gp6             1/1     Running   0          11m
cert-manager-cainjector-85fbdf788-s959n   1/1     Running   0          11m
cert-manager-webhook-76f9b64b45-zbgrm     1/1     Running   0          11m
```

`$ helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher.local --version 2.2.9`

**Result:**

`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): **HA**

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"
```

- Docker version (use `docker version`): 18.09.9

```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:51:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:22:32 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by adrianovieira** [comment]
My bad!

Due to cert-manager 0.12 I needed to install at least 2.2.10

**Comment by amir-khalili** [comment]
so why rancher didnt update documents! 
I just copy the command from the rancher site!
