### ISSUE TITLE
Rancher master-head throws error on first access

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#25252]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Provision a Ubuntu instance.
Install Docker/ confirm docker is installed.
Install the latest `master-head`
```
docker run -d --restart=unless-stopped \
-p 80:80 -p 443:443 \
rancher/rancher:master-head
```

**Result:**
The password page cannot be accessed.
![image](https://user-images.githubusercontent.com/57409052/73764886-ef7a6680-4730-11ea-97f2-03d8614ba1e9.png)

Hitting `log out` will bring the user to the password page.

**Other details that may be helpful:**
Seen in both Chrome and Firefox.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): Single

**Comment by aaronRancher** [comment]
Hitting `log out` will bring the user to the password page.

**Comment by westlywright** [comment]
Was related to https://github.com/rancher/rancher/issues/25198 and the fix being a bit too aggressive. The original fix has been reverted.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 1ac0ae3ff`
Steps:
Provision a Ubuntu instance.
Install Docker/ confirm docker is installed.
Install the latest `master-head`

User is met with password page upon first access.
