### ISSUE TITLE
[UI] AWS EC2 node template: Expose ebs volume fields

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#25266]
Expose field for encrypting EBS volume along with other existing fields for volumes in UI

Needs API changes from: https://github.com/rancher/rancher/issues/22691

**Comment by khushboo-rancher** [comment]
Field ```Encrypt EBS Volume``` appears on node template create/edit form in rancher version v2.3-head ```b5175db3f``` and master-head ```981263b53``` and in upgraded rancher set up from v2.3.5 to v2.3-head. On enabling it ```encryptEbsVolume": true,``` gets added in amazonec2config object in request.
