### ISSUE TITLE
Add app deployment with Helm 3 and continue supporting existing apps with Helm 2

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#25260]
Add in being able to deploy helm 3 while continue being able to support deploying existing apps using helm 2

Epic:  rancher/rancher#20596

**Comment by deniseschannon** [comment]
Since we're changing the design to add catalogs as either a Helm 2 or Helm 3 catalog, this issue should test that Helm 2 apps that get upgraded still are marked as Helm 2.

**Comment by jiaqiluo** [comment]
the feature is validated on master-head 6330683

- new catalog can be added as either helm 2 or helm 3 catalog
- the designated helm version is used to deploy, upgrade, rollback, delete apps 
- helm 2 is used for existing apps and catalogs when upgrading from v2.3.5 to master-head

Detailed tests and results are tacked in the test plan.
