### ISSUE TITLE
Support for multi-cluster app Helm 3 

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#25261]
Add being able to deploy multi-cluster apps with helm 3 while continue being able to support existing released multi-cluster apps using helm 2 

Epic: rancher/rancher#20596

**Comment by jiaqiluo** [comment]
the feature is validated on master-head 63306835a

- helm 3 catalog can be added and used to install multi-cluster apps
- existing released multi-cluster apps still use helm 2

Detailed tests and results are tacked in the test plan.
