### ISSUE TITLE
Helm 3 CLI Support

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#25262]
Add support for Helm 3 in the CLI 

Epic: rancher/rancher#20596

**Comment by deniseschannon** [comment]
Needs to add ability to add catalogs so set what version of helm it is.

**Comment by brendarearden** [comment]
available for testing in rancher/cli v2.4.3-rc1

**Comment by rancher-max** [comment]
This option is available in the CLI, but is not fully working downstream.

Steps:
1. `rancher catalog add --helm-version v3 foo https://git.rancher.io/system-charts`
produces:
```
ID               NAME             URL                                    BRANCH    KIND       HELMVERSION
foo              foo              https://git.rancher.io/system-charts   master    helm       v3
```
But in the UI:
![image](https://user-images.githubusercontent.com/55997940/78943587-0448e280-7a71-11ea-86bf-3af64034e9f4.png)

Also `v3` is not currently a valid helmversion as it requires helm_v3 at the time of this testing. 


**Dependencies: https://github.com/rancher/rancher/issues/26560 and https://github.com/rancher/rancher/pull/26531**

**Comment by rancher-max** [comment]
#### Validated above using `v2.4-2748-head` and `master-2751-head`

Working as expected and using `v3` uses helm_v3 when enabling the apps.
