### ISSUE TITLE
[feature] would be great if Load Balancer worked with services using "bridge" networking mode

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#2526]
(rancher/agent-instance:v0.5.0) / rancher 0.43.1
- create service that uses `bridge` networking mode (any scale)
- create a load balancer, point to the service
- try to connect to the LB on the specified port - it will refuse connection.
- open shell to LB, `cat /etc/haproxy/haproxy.cfg`:
  
  ```
  global                                                                          
      log 127.0.0.1 local0                                                    
      log 127.0.0.1 local1 notice                                             
      maxconn 4096                                                            
      maxpipes 1024                                                           
      chroot /var/lib/haproxy                                                 
      user haproxy
      group haproxy                                                           
      daemon                                                                  
  
  defaults                                                                        
      log     global                                                          
      mode    tcp                                                             
      option  tcplog                                                          
      option  dontlognull                                                     
      option  redispatch                                                      
      option forwardfor                                                       
      retries 3                                                               
      timeout connect 5000                                                    
      timeout client 50000                                                    
      timeout server 50000                                                    
      errorfile 400 /etc/haproxy/errors/400.http                              
      errorfile 403 /etc/haproxy/errors/403.http                              
      errorfile 408 /etc/haproxy/errors/408.http                              
      errorfile 500 /etc/haproxy/errors/500.http                              
      errorfile 502 /etc/haproxy/errors/502.http                              
      errorfile 503 /etc/haproxy/errors/503.http                              
      errorfile 504 /etc/haproxy/errors/504.http                              
  
  listen web 0.0.0.0:9
  ```

The contents are always the same regardless of the LB service config.

Examining `/etc/hosts`: backends (with their Docker bridge IPs) are correctly added to the hosts file. Only backends from the same Docker host as the LB itself are present in `hosts` for each respective LB, which is expected and desired.

Creating a LB that points to a service which uses `managed` networking, works as expected. Even cloning the above LB service and pointing it to a `managed` network backend works as expected as well.

**Comment by deniseschannon** [comment]
Load balancers only support services with managed networking.

**Comment by ebr** [comment]
Ok, thanks. This is not evident from reading the documentation.

**Comment by ebr** [comment]
I updated this to be a feature request.

My current (and probably not the only) use case for this: I'd like to run some a/b tests, and launched several copies of the same service on a single host in my farm. I'd like to direct all traffic to the "b" version of the service to the load balancer on that host, and need this traffic to stay within this host and not cross over to others, to eliminate network conditions from my test cases.

this is not a common requirement, so completely understandable if this doesn't make it into release for a while (a really long while, even). but just leaving this here in case anyone else has the same use case.

**Comment by deniseschannon** [comment]
@ebr Added notes on load balancers and managed network. https://github.com/rancher/rancher.github.io/pull/112 Is there another place that you were looking at that I might have missed?

**Comment by Kelindar** [comment]
+1

**Comment by will-chan** [comment]
This is not something we plan to address.  it would require major refactoring work.
