### ISSUE TITLE
NGINX-INGRESS rewrite-target

### ISSUE THREAD

**Issue by it-forever** [rancher/rancher#25272]
Hey. There is a problem with the new nginx openresty version rancher / nginx-ingress-controller: nginx-0.25.1-rancher1
when using "nginx.ingress.kubernetes.io/rewrite-target = /"

The final config nginx.conf looks like this:
<code>
location ~* "^/custompath"
</code>

doesn’t work as intended

In the old version of rancher / nginx-ingress-controller: 0.21.0-rancher3
  It works as intended and looks like:
<code>
location ~* "^/custompath\/?(?<base_uri>.*)"
</code>

**Comment by superseb** [comment]
See https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target / https://github.com/kubernetes/ingress-nginx/pull/3174#issuecomment-455665710

**Comment by adrianovieira** [comment]
In my case when I use `rewrite-target` annotation, Rancher UI is showing and generating the target path with that regex, too.

from that comment @superseb ... e.g: `path: /old/?(.*)`

Although it works, at rancher-ui shows workload's/loadbalancing target link like: `http://server.example.com//old/?(.*)`

What I need to do to fix the "rancher-ui target link"?

**Comment by lonelyleaf** [comment]
Waht a stupid change they made!Even I rewrite my ingress config , my service wouldn't work fine.

Are rancher going to support traefik?

**Comment by vincent99** [comment]
You can disable nginx and deploy traefik, but we have no immediate plans for Rancher/RKE to deploy it for you.

K3s uses traefik by default.

**Comment by lonelyleaf** [comment]
@vincent99  Thank you. If I use traefik and nginx as ingress at same time, will there be any confilct?
