### ISSUE TITLE
Native Private Links AKS Cluster Mgmt

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#25273]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request/Enhancement

**Request**
Rancher Support for Azure Private Links at GA (feature is in Public Preview)

Can Rancher include creating/managing AKS Private Link clusters in a future version when the feature becomes GA in Azure, it is understood it is out of scope until then.

It is highly beneficial and increasingly standardised for secure networking environments that customers be allowed to use Private Links Networks for provisioning and managing their data and infrastructure when using the cloud.

Rancher supporting this natively would enable customers who have these concerns to operate with confidence while expanding the customer base who need this complexity to meet stringent audit requirements.

gz#11713
gz#8164

**Comment by janeczku** [comment]
Azure Private Link for AKS is now GA.
https://azure.microsoft.com/en-us/updates/azure-private-link-for-aks-is-now-generally-available/

**Comment by prabalsharma** [comment]
Tested private cluster on master-7a2fc74, operator rc 11
