### ISSUE TITLE
Unable to provision Kubernetes 1.14 with Calico as chosen network provider

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25278]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Provision a 1.14.9-rancher1-2 cluster - DO RKE cluster - 1 node - all roles.
- The cluster is stuck in provisioning
- Error: `Can not find RKE state file: open /var/lib/rancher/management-state/rke/rke-748315723/cluster.rkestate: no such file or directory`
- Rancher logs: `2020/02/05 18:17:50 [ERROR] cluster [c-zlbdd] provisioning: Failed to validate cluster: v1.14.9-rancher1-2 is an unsupported Kubernetes version and system images are not populated: calico controllers image is not populated`
- 

**Expected Result:**
The cluster should be provisioned successfully.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE DO
- Kubernetes version (use `kubectl version`):

```
1.14.9
```

**Comment by Oats87** [comment]
@sowmyav27 This is happening on `v2.3.2`?

**Comment by Oats87** [comment]
OK. This looks to be happening because of our validation logic in RKE. We should maybe cut a `rancher1-3` of `v1.14.9` that populates `CalicoControllers` (with a null value)

/cc @deniseschannon I'll open a proposed PR for this

**Comment by StrongMonkey** [comment]
It also fails on rancher `v2.3-head` with kubernetes 1.17.2. 
> v1.17.2-rancher1-1 is an unsupported Kubernetes version and system images are not populated: calico ctl image is not populated

**Comment by Oats87** [comment]
> It also fails on rancher `v2.3-head` with kubernetes 1.17.2.
> 
> > v1.17.2-rancher1-1 is an unsupported Kubernetes version and system images are not populated: calico ctl image is not populated

Where are you seeing `v1.17.2-rancher1-1`? We cut a `v1.17.2-rancher1-2` as well as a `v1.17.3-rancher1-1` that has `CalicoCtl` populated

**Comment by deniseschannon** [comment]
@sowmyav27 This is available in 2.3.3 (last 2.3 version that has k8s 1.14 available) and should be validated with that version. 

It's available in the `dev-2.3` branch of k-d-m.

**Comment by sangeethah** [comment]
Validations done for rancher server version - `v2.3-5` pointing to  `dev-v2.3` branch of k-d-m

1. Expected applicable k8s versions are seen in the dropdown while creating clusters (RKE)

<img width="816" alt="Screen Shot 2020-02-23 at 2 20 40 PM" src="https://user-images.githubusercontent.com/4266958/75121313-c110ec80-5647-11ea-8191-a49538f7ed88.png">

2. User is able to provision clusters with all applicable k8s versions(from drop down list) using all 4 network providers ( test_clusters_for_kdm)

3.. All onTag automation runs for Cluster with each supported K8s version with “Canal” succeded.

**Comment by sowmyav27** [comment]
**Verified on rancher:v2.3.3**

- Rancher shows the following k8s versions:
<img width="873" alt="Screen Shot 2020-02-24 at 8 45 57 AM" src="https://user-images.githubusercontent.com/26032343/75175204-c07b6300-56e6-11ea-880c-efa3f5a9a545.png">

- Cluster with all 4 k8s versions ^^^ with all applicable network provider - canal, calico, weave and flannel, deployed successfully. (using test_clusters_for_kdm)
- Automation run for 4 k8s versions, with network provider: `Canal` succeeded. 

**Verified on rancher:v2.3.2**

- Rancher shows the following k8s versions:
<img width="873" alt="Screen Shot 2020-02-24 at 8 45 57 AM" src="https://user-images.githubusercontent.com/26032343/75175204-c07b6300-56e6-11ea-880c-efa3f5a9a545.png">

- Cluster with all 4 k8s versions ^^^ with all applicable network provider - canal, calico, weave and flannel, deployed successfully. (using test_clusters_for_kdm)
