### ISSUE TITLE
Not selecting the node roles checkboxes during cluster creation allows the user to click create and start provisioning

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25276]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Go to create an Infrastructure Provider cluster like Digital Ocean.
2. Set the cluster name and the node name, but do not check any of the roles boxes.
3. Click create

**Result:**

An error will appear about that the required boxes were not selected, but the UI will redirect the user to the Clusters page, and the cluster will start provisioning with one Node and the node will only have the Worker role.

**Other details that may be helpful:**

**Environment information**
- Rancher version: `2.4 master-head` commit id: ca01ddff2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud

**Comment by deniseschannon** [comment]
is this a regression? @izaac

**Comment by izaac** [comment]
@deniseschannon this is not happening in 2.3.5 so I think it is a regression.

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (02/19/2020)` commit id: e11d47814

Closing, I was not able to reproduce this issue anymore in a recent build.
