### ISSUE TITLE
Failed to pull catalog with exit status 128

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2527]
Server version - v0.44.0-rc1

I had the catalog.url set to https://github.com//alena1108/rancher-catalog.git.

Cloning of catalog was successful and I was able to create stack with template from catalog.
There was a change in version for "Route53 DNS" template from v0.1.2 ->  v0.1.3.
I was not able to get the latest version of "Route53 DNS" template to show up in my catalog even after I refreshed the UI few times.

git pull encountered error - exit status 128.

When I forced the clone of catalog again (by changing the catalog.url ) , I was able to see the new version of  "Route53 DNS" template.

```
time="2015-11-03T00:21:36Z" level=info msg="Cloning the catalog from github url https://github.com/rancher/rancher-catalog.git" 
time="2015-11-03T01:18:17Z" level=info msg="Cloning the catalog from github url https://github.com/alena1108/rancher-catalog.git" 
time="2015-11-03T18:38:18Z" level=error msg="Failed to pull the catalog from github repo https://github.com/alena1108/rancher-catalog.git, error: exit status 128" 
time="2015-11-03T18:43:18Z" level=error msg="Failed to pull the catalog from github repo https://github.com/alena1108/rancher-catalog.git, error: exit status 128" 
time="2015-11-03T18:48:18Z" level=error msg="Failed to pull the catalog from github repo https://github.com/alena1108/rancher-catalog.git, error: exit status 128" 
time="2015-11-03T18:49:10Z" level=info msg="Cloning the catalog from github url https://github.com/rancher/rancher-catalog.git" 
time="2015-11-03T18:50:42Z" level=info msg="Cloning the catalog from github url https://github.com/alena1108/rancher-catalog.git" 
```

**Comment by prachidamle** [comment]
This issue was caused because the catalog owner @alena1108 used git push -f to forcefully rewrite the git branch. So git pull against the original branch started erroring out due to the re-write.

This error will not happen in case of updates on an existing branch.

**Comment by onatm** [comment]
so, how are we gonna fix this?
