### ISSUE TITLE
Updating Istio to enable certmanager fails

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#25275]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Enable Istio in a cluster
2. After it has been deployed successfully, navigate back to Tools > Istio and add Custom Answer: `certmanager.enabled=true`, then click Save.

**Result:**
Istio appears to be installing forever. Going to System project > Apps > cluster-istio shows this error at the top: `failed to install app cluster-istio. Error: UPGRADE FAILED: unable to recognize "": no matches for kind "ClusterIssuer" in version "certmanager.k8s.io/v1alpha1"`

![image](https://user-images.githubusercontent.com/55997940/73862415-c5da4180-47fb-11ea-8a4c-935ea8c19e8a.png)

**Other details that may be helpful:**
Enabling that custom answer upon initial install of Istio in the cluster works properly. Also, as a workaround, user can apply the CRDs to the cluster first with: `kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.6/deploy/manifests/00-crds.yaml`

I believe this can be fixed by adding a `pre-upgrade` hook to the istio certmanager chart, similar to the fix that was done here: https://github.com/rancher/system-charts/pull/154.

Also, I suspect there could be other system-charts that have a similar error to this. It looks like we need that hook for net new CRDs to be added during an update scenario. This would affect upgrading versions as well if there are new CRDs in an upgrade (see previous fix for https://github.com/rancher/rancher/issues/25077#issuecomment-578212132).

**Environment information**
Rancher v2.3.5 single node install

**Cluster information**
- 3 nodes, all roles, each 4vCPU 8GB.
- kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jiaqiluo** [comment]
The bug still exists on `master-5e1b21b931ac58ba0aa3f89c827a0f65dd42051b-head`

- cluster k8s `v1.18.6-rancher1-2`
- Istio chart version `1.5.900(istio 1.5.9)`

**Comment by cbron** [comment]
For context, master (Rancher 2.5) will ship with Istio 1.7 which no longer ships with cert-manager, it has been removed along with many other integrations. If there is wide community request for backporting this to 1.5.x we can look into it.

**Comment by cbron** [comment]
Closing as v1 is now deprecated.
