### ISSUE TITLE
View logs not functional, stuck in "Connecting" state

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#25297]
Version: master-head (fe3163fc2)

Steps:

1. Create a single node Rancher Server with using your own self signed certificate or using certs from a recognized CA
```
docker run -d --restart=unless-stopped \
	-p 80:80 -p 443:443 \
	-v /<CERT_DIRECTORY>/<FULL_CHAIN.pem>:/etc/rancher/ssl/cert.pem \
	-v /<CERT_DIRECTORY>/<PRIVATE_KEY.pem>:/etc/rancher/ssl/key.pem \
	-v /<CERT_DIRECTORY>/<CA_CERTS.pem>:/etc/rancher/ssl/cacerts.pem \
	rancher/rancher:latest

OR

docker run -d --restart=unless-stopped \
	-p 80:80 -p 443:443 \
	-v /<CERT_DIRECTORY>/<FULL_CHAIN.pem>:/etc/rancher/ssl/cert.pem \
	-v /<CERT_DIRECTORY>/<PRIVATE_KEY.pem>:/etc/rancher/ssl/key.pem \
	rancher/rancher:latest \
	--no-cacerts

```
2. Create a DO user cluster
3. Create workloads in a  project and view logs for the containers or view logs for the workloads in system project
Logs are not displayed. The window is in "Connecting" state
<img width="2005" alt="Screen Shot 2020-02-06 at 2 02 51 PM" src="https://user-images.githubusercontent.com/18536626/73982654-84c05b00-48e9-11ea-8549-bd51258401e2.png">

Work around:
 Check and uncheck previous container check box in the bottom left corner of the logs window, fixes the problem

**Comment by westlywright** [comment]
This is unrelated to certs. Was a bug in the UI code.

**Comment by soumyalj** [comment]
Tested with master-head (5ced4dc03)
1. Create  single node Rancher Servers with using your own self signed certificate or using certs from a recognized CA
docker run -d --restart=unless-stopped \
	-p 80:80 -p 443:443 \
	-v /<CERT_DIRECTORY>/<FULL_CHAIN.pem>:/etc/rancher/ssl/cert.pem \
	-v /<CERT_DIRECTORY>/<PRIVATE_KEY.pem>:/etc/rancher/ssl/key.pem \
	-v /<CERT_DIRECTORY>/<CA_CERTS.pem>:/etc/rancher/ssl/cacerts.pem \
	rancher/rancher:latest

and

docker run -d --restart=unless-stopped \
	-p 80:80 -p 443:443 \
	-v /<CERT_DIRECTORY>/<FULL_CHAIN.pem>:/etc/rancher/ssl/cert.pem \
	-v /<CERT_DIRECTORY>/<PRIVATE_KEY.pem>:/etc/rancher/ssl/key.pem \
	rancher/rancher:latest \
	--no-cacerts
2. Create DO cluster.
3. Create workloads in a project and view logs for the workload pods or view logs for the workload pods in system project

View logs are functional
<img width="2016" alt="Screen Shot 2020-02-13 at 4 43 20 PM" src="https://user-images.githubusercontent.com/18536626/74491276-fbc49900-4e7f-11ea-9b02-cd03010dd07e.png">


<img width="2016" alt="Screen Shot 2020-02-13 at 4 42 53 PM" src="https://user-images.githubusercontent.com/18536626/74491294-05e69780-4e80-11ea-8065-e8c8fb172dfe.png">
