### ISSUE TITLE
Support K8s 1.15.10, 1.16.7, 1.17.3

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#25293]
Kubernetes v1.15.10, v1.16.7, and v1.17.3 are planned to be released on February 11, 2020.

**Comment by Oats87** [comment]
https://github.com/rancher/hyperkube/pull/97
https://github.com/rancher/hyperkube/pull/98
https://github.com/rancher/hyperkube/pull/99

https://github.com/rancher/kontainer-driver-metadata/pull/134

in flight

**Comment by sangeethah** [comment]
Validations done for rancher server version - v2.3-5 pointing to dev-v2.3 branch of k-d-m

Expected applicable k8s versions are seen in the dropdown while creating clusters (RKE)
<img width="816" alt="Screen Shot 2020-02-23 at 2 20 40 PM" src="https://user-images.githubusercontent.com/4266958/75166831-55775f80-56d9-11ea-9d85-d263ce34e556.png">

User is able to provision clusters with all applicable k8s versions(from drop down list) using all 4 network providers ( test_clusters_for_kdm)
3.. All onTag automation runs for Cluster with each supported K8s version with “Canal” succeded.
