### ISSUE TITLE
How to make Rancher use Kubernetes of Docker

### ISSUE THREAD

**Issue by nicoclau** [rancher/rancher#25292]
Hello all, I use Kubernetes with Docker.
I added the dashboard and it s pretty neat.

Now I need the rancher to reach for the cluster.

How to do that please?

Thanks :)

**Comment by nicoclau** [comment]
I managed, I import an existing cluster.

But I got the error in the pod  cattle-cluster-agent 

INFO: Environment: CATTLE_ADDRESS=10.1.0.76 CATTLE_CA_CHECKSUM=368d86f4ae9b4e23245ffc129f25457b4f5edafa23ecb58db3eb3218a8606f7e CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-6bf4c64948-nftdz CATTLE_SERVER=https://localhost
INFO: Using resolv.conf: nameserver 10.96.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5
ERROR: https://localhost/ping is not accessible (Failed to connect to localhost port 443: Connection refused)

**Comment by superseb** [comment]
The configured `server-url` has to be reachable by all nodes via DNS, the pod is now trying to connect to itself where there is nothing running. If you configure the `server-url` to resolvable FQDN, and then import a cluster, the agent should be able to run.

If not, please supply output from the troubleshooting commands listed here: https://rancher.com/docs/rancher/v2.x/en/troubleshooting/
