### ISSUE TITLE
SourceCodeProvider and PipelineSettings always call create

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#25295]
In the pipeline-controller sync the same create call happens without checking a cache to see if an object exists first. In large clusters this can be seen as doing 24k calls to the api over the course of 1 minute with a return code of 409.

**Comment by dramich** [comment]
This ended up being larger than the initial issue, there was a general problem in using the API instead of listers in multiple places.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head ad9c7118

Regression test via automation
* Automation for provisioning all cluster types
* Smoke & long running tests
* No unexpected results

Manual checks for P1 pipeline cases on RKE cluster and k3s cluster (@aaronRancher)
