### ISSUE TITLE
changing refresh interval in rke-metadata-config doesn't take effect immediately

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#25308]
- Bring up a rancher setup with a downstream cluster
- Navigate to `/v3/settings/rke-metadata-config`
- Change the URL to a different repo (with some new CRDs preferably) and set the time to `1` (1 minute) and save.

Expected: refresh to happen and start showing the following log line every minute.
`[INFO] driverMetadata: checking rke-metadata-url every 1m0s`

But the refresh doesn't happen. Looks like the previous timers are not reset when there is a config change. 

Workaround: Either a manual refresh (Tools -> Drivers -> Refresh Kubernetes Metadata) or a restart of the rancher pod fixes the issue.

**Comment by StrongMonkey** [comment]
Available to test. Since it is hard to notice any real change in data.json, QA can verify this according to rancher logs. There are logs that indicates when driverMetadata is updated.

**Comment by jiaqiluo** [comment]
the validation for this bug fix is covered in the validation for this issue: https://github.com/rancher/rancher/issues/25162#issuecomment-591726838


-  go to Settings -> rke-metadata-config to change the refreshing interval to 1
```
"refresh-interval-minutes": "1",
```
- edit the data.json file to add a new k8s version `v1.18.1-rancher1-1`, and change the default to `v1.18.x`

Results:
- in Rancher's log, the following shows every minute which indicates the refresh is triggered automatically 
```
2020/02/27 01:07:08 [INFO] Refreshing driverMetadata in 1 minutes
2020/02/27 01:07:08 [INFO] driverMetadata: refreshing data from upstream https://raw.githubusercontent.com/jiaqiluo/kontainer-driver-metadata/issue-25162/data/data.json
2020/02/27 01:08:08 [INFO] Refreshing driverMetadata in 1 minutes
2020/02/27 01:08:08 [INFO] driverMetadata: refreshing data from upstream https://raw.githubusercontent.com/jiaqiluo/kontainer-driver-metadata/issue-25162/data/data.json
2020/02/27 01:09:08 [INFO] Refreshing driverMetadata in 1 minutes
2020/02/27 01:09:08 [INFO] driverMetadata: refreshing data from upstream https://raw.githubusercontent.com/jiaqiluo/kontainer-driver-metadata/issue-25162/data/data.json
```

- in Rancher UI, the new version shows up as the default value
![image](https://user-images.githubusercontent.com/6218999/75403000-93d07280-58c3-11ea-90b5-a2beecbc2644.png)
- the values under v3/settings also reflect the changes
