### ISSUE TITLE
"Upgrade Available" flag is still present when the service is already upgraded to the latest version and is in "upgraded"/"active" state until the page is refreshed manually.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2530]
Server version - v0.44.0-rc2

Created a stack from catalog using the older version of "Elastic Search" template.
"Upgrade Available" option is presented to user.
Upgrade this service.
When service is in "Upgraded" state , "Upgrade Available" option is still presented to user.

<img width="1276" alt="screen shot 2015-11-03 at 1 48 32 pm" src="https://cloud.githubusercontent.com/assets/4266958/10924451/9b91d0bc-823b-11e5-8d0d-c6727e913f4b.png">

"Finish Upgrade" and wait for service state to get to "Active" state. "Upgrade Available" option is still presented to user.

<img width="1516" alt="screen shot 2015-11-03 at 1 49 58 pm" src="https://cloud.githubusercontent.com/assets/4266958/10924455/a0c1076a-823b-11e5-98ab-bcb844dcbb3e.png">

Once refresh , the "Upgrade Available" option is not present anymore.

**Comment by vincent99** [comment]
Changed to show 'Upgrade in progress' during upgrade.

**Comment by tfiduccia** [comment]
Version - Master with latest reskin UI
Verified fixed
