### ISSUE TITLE
Waiting for server to become available: Get https://localhost:6443/version?timeout=30s: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by linbingdouzhe** [rancher/rancher#25311]
**What kind of request is this (question/bug/enhancement/feature request):**
rancher disaster restoration

**Steps to reproduce (least amount of steps as possible):**
according to https://rancher.com/docs/rancher/v2.x/en/backups/restorations/single-node-restoration/ and https://rancher.com/docs/rancher/v2.x/en/backups/backups/single-node-backups/
this two step 

**Result:**
2020/02/07 09:25:53 [INFO] Waiting for server to become available: Get https://localhost:6443/version?timeout=30s: x509: certificate signed by unknown authority
2020/02/07 09:25:55 [INFO] Waiting for server to become available: Get https://localhost:6443/version?timeout=30s: x509: certificate signed by unknown authority

**Other details that may be helpful:**
I restoration to a new ec2 instance

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
single docker install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-108.git4ef4b30.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      4ef4b30/1.13.1
 Built:           Tue Jan 21 17:16:25 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-108.git4ef4b30.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      4ef4b30/1.13.1
 Built:           Tue Jan 21 17:16:25 2020
 OS/Arch:         linux/amd64
 Experimental:    false
```
(paste the output here)
```

**Comment by linbingdouzhe** [comment]
my rancher version is stable now

**Comment by kebyn** [comment]
After deleting, restarting does not generate the localhost certificate, so I manually generated the certificate.
```
openssl genrsa -out  localhost.key 4096
openssl req -new -key localhost.key -out localhost.csr -subj "/CN=localhost"
openssl x509 -req -in localhost.csr -CA client-ca.crt -CAkey client-ca.key -CAcreateserial -out localhost.crt -days 36500
```
