### ISSUE TITLE
sort node templates dropdown

### ISSUE THREAD

**Issue by stephen-dahl** [rancher/rancher#25316]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

please sort this dropdown alphabetically so that it is easier to find the template I want.
![image](https://user-images.githubusercontent.com/6061073/74053723-3fefff00-4991-11ea-94c1-baf4a7eccc2c.png)

**Comment by aaronRancher** [comment]
The enhancement is verified with Rancher server `rancher\rancher:master-head` `version 3623201ad`
Before, templates would be listed in the order they were created. From `Rancher v2.3.5`:
![Screen Shot 2020-03-03 at 1 12 41 PM](https://user-images.githubusercontent.com/57409052/75815643-0375b000-5d51-11ea-9e70-fc11e28de3de.png)

Templates are now sorted alphabetically. From `Rancher master-head`:
![Screen Shot 2020-03-03 at 1 08 48 PM](https://user-images.githubusercontent.com/57409052/75815654-0670a080-5d51-11ea-9560-f514eb6d4ffe.png)
