### ISSUE TITLE
JSON logs shipped with 1970-01-01T00:33:40.000Z timestamp

### ISSUE THREAD

**Issue by bob-gray** [rancher/rancher#25318]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Enable Elasticsearch logging in project - Check Enable JSON Parsing (#23646)
Write to container logs using Node.js Bunyan

**Result:**
@timestamp sent to Elasticsearch is "1970-01-01T00:33:40.000Z"

Container log file:
```
{"log":"{\"name\":\"time-off\",\"hostname\":\"time-off-6c7584cf75-qf7h2\",\"pid\":1,\"id\":\"5ad7e9744bb3aae8\",\"level\":30,\"elapsed\":56.662333,\"status\":{\"code\":304,\"text\":\"Not Modified\"},\"headers\":{\"Cache-Control\":\"no-cache, must-revalidate\"},\"msg\":\"response\",\"time\":\"2020-02-07T17:20:40.515Z\",\"v\":0}\n","stream":"stdout","time":"2020-02-07T17:20:40.515667046Z"}
```

Log in Elasticsearch:
```
{
  "_index": "development_http_services-1970-01-01",
  "_type": "_doc",
  "_id": "kTSrIHABju6QEerI5MJ5",
  "_version": 1,
  "_score": null,
  "_source": {
    "log": "{\"name\":\"time-off\",\"hostname\":\"time-off-6c7584cf75-qf7h2\",\"pid\":1,\"id\":\"5ad7e9744bb3aae8\",\"level\":30,\"elapsed\":56.662333,\"status\":{\"code\":304,\"text\":\"Not Modified\"},\"headers\":{\"Cache-Control\":\"no-cache, must-revalidate\"},\"msg\":\"response\",\"time\":\"2020-02-07T17:20:40.515Z\",\"v\":0}\n",
    "stream": "stdout",
    "docker": {
      "container_id": "2ca54d5eb09915964ae8af5251d8608be21a76bc2fde002fac7524f8786e31ed"
    },
    "kubernetes": {
      "container_name": "time-off",
      "namespace_name": "http-services",
      "pod_name": "time-off-6c7584cf75-qf7h2",
      "container_image": "containers/http.services/time-off:63e6b34692d304cee165d211dd8957dbc89c14c3",
      "container_image_id": "docker-pullable://containers/http.services/time-off@sha256:259abd81b52fbe30552ef28e9bcca2c44ccd94d8d0df39ab209af96c084df42f",
      "pod_id": "f4f6fa34-19dd-4ad4-bfd6-f3074855378e",
      "host": "kubedevworkernwjjm",
      "labels": {
        "httpService": "time-off",
        "pod-template-hash": "6c7584cf75"
      },
      "master_url": "https://10.43.0.1:443/api",
      "namespace_id": "ee663833-e490-4c86-a232-61aced08314d",
      "namespace_labels": {
        "field_cattle_io/projectId": "p-clc89"
      }
    },
    "tag": "c-nkf8q:p-clc89.var.log.containers.time-off-6c7584cf75-qf7h2_http-services_time-off-2ca54d5eb09915964ae8af5251d8608be21a76bc2fde002fac7524f8786e31ed.log",
    "log_type": "k8s_normal_container",
    "projectID": "c-nkf8q:p-clc89",
    "name": "time-off",
    "hostname": "time-off-6c7584cf75-qf7h2",
    "pid": 1,
    "id": "5ad7e9744bb3aae8",
    "level": 30,
    "elapsed": 56.662333,
    "status": {
      "code": 304,
      "text": "Not Modified"
    },
    "headers": {
      "Cache-Control": "no-cache, must-revalidate"
    },
    "msg": "response",
    "v": 0,
    "@timestamp": "1970-01-01T00:33:40.000000515+00:00"
  },
  "fields": {
    "@timestamp": [
      "1970-01-01T00:33:40.000Z"
    ]
  }
}
```

**Other details that may be helpful:**
Logging with Bunyan was working as desired prior to Rancher 2.3.3.

Bunyan writes a "time" field to the log JSON. I have a feeling this maybe causing a conflict and causing fluentd time parsing to fail.

How can I configure fluentd to parse the JSON but not merge it? Is it possible to have the parsed JSON sent as the value for "log" instead of the JSON string? It seems wasteful to send the same data twice in each log document and because it's merged there is an opportunity for field collisions.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5
- Installation option (single install/HA): single node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by MaxDiOrio** [comment]
I'm seeing this same issue on 2.3.5 with my Vault containers that log to JSON format.

**Comment by Jordilg13** [comment]
I had the same problem, the date isn't in the correct format, then elasticsearch can't parse it and thats why it uses the first date available. I disabled the JSON parsing, I supose that u have to set the date format.

**Comment by MaxDiOrio** [comment]
I have a config block to set the date format, although the format is ISO standard for Vault.

**Comment by bob-gray** [comment]
@MaxDiOrio is the config block for Vault (writing the date) or fluentd (parsing the date)? If in fluentd, will you share it and share how you applied it in Rancher? I've tried and failed to change the fluentd date format in Rancher. Thanks

**Comment by MaxDiOrio** [comment]
@bob-gray - it is a fluentd config that I’ve seen recommended, however it does not work as expected. It does let fluentd parse fields and lets them show up in Elastic, but the date issue remains.

Stderr logs that are plain text work fine for the timestamp.  The issue is in the stdout logs that are json based.

**Comment by bob-gray** [comment]
@MaxDiOrio I've see the same behavior. Without JSON parsing and merging - the date is fine. Unfortunately plain text unstructured log messages are far less valuable to us. Especially when shipping the logs to Elasticsearch. It would be great if we could parse the JSON and not merge the fields - avoiding the date issue or any other collisions.

**Comment by MaxDiOrio** [comment]
@bob-gray Absolutely agree.  You can also see from this capture that the contents are coming in the log field, and not the message field for some reason.   

This is becoming a critical issue for our logging.  We can't use this, as the fields logged with 1969 dates also have a random order as they all contain the exact same timestamp.

![image](https://user-images.githubusercontent.com/25855524/76233830-2d225180-61ff-11ea-876f-8aa2aad1fc9c.png)

**Comment by MaxDiOrio** [comment]
So went to the Rancher config for my cluster logging and unchecked the box for Enable JSON Parsing, and now the date is showing up correctly, however the fields in the json log that were being parsed before, are not now.

I'd rather have correct dates for now I guess.

**Comment by bob-gray** [comment]
@Jordilg13 have you had any luck getting this to work? I've been successful altering the date format of the log output but not matter how I format the date it fails. If the stdout is JSON and has a property named "time" it doesn't work regardless of the format.

**Comment by Jordilg13** [comment]
> @Jordilg13 have you had any luck getting this to work? I've been successful altering the date format of the log output but not matter how I format the date it fails. If the stdout is JSON and has a property named "time" it doesn't work regardless of the format.

No sry, I just disabled the JSON parsing and didn't tried anything else, sry😢.

**Comment by MaxDiOrio** [comment]
Same here. Disabled the json passing and haven’t had time to go back.

**Comment by abola** [comment]
Same issue. I'm trying to edit  secret `rancher-logging-fluentd`, file: `project.conf` find the like below 

```
<filter local:p-jmkv4.**>
  @type parser
  <parse>
    @type multi_format
    <pattern>
      format json
    </pattern>
    <pattern>
      format none
    </pattern>
  </parse>
  key_name log
  reserve_data true
  reserve_time true
</filter>
```

Add `reserve_time true` for the project filter. It will be work, but shortly getting wrong again. 
Cause rancher-logging overwrite the settings.
