### ISSUE TITLE
Zero Down: Add label to ignore nodes

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25329]

**Comment by sowmyav27** [comment]
**verified on master-head - commit id - `926997017`**

**Steps:**

- Mark one worker node with label - `user.cattle.io/upgrade-policy=prevent`.
- Upgrade cluster by changing value

```
kubelet:
      extra_args:
        max-pods: '123'
```
- Cluster will go into `Updating` state.
- Worker node marked with label, does NOT get upgraded.
- Cluster comes back to `Active` state.
