### ISSUE TITLE
CIS Scan - Ability to run Permissive & Hardened Profiles

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25325]
CIS Scan design summary:
* Types of CIS tests: Not Applicable, Skipped (Rancher), Skipped (User), Active
* There should be two profiles for CIS scan "Permissive" vs "Hardened"
        * By default, "Permissive" run contains Rancher recommended skip tests and it cannot be unskipped.
        * By default, "Hardened" run contains no skipped tests
* User can select either profile to run a CIS scan
         * If there are user skipped tests it will be applied on top of the profile selected.

 (i.e: if there are 5 user skipped tests and 10 Rancher skipped tests, when user picks "Permissive" to run, the run will contain 15 skipped test. If user selected "Hardened" to run, the run will contain 5 skipped tests)

* User skipped tests will be saved in a config-map file
* User can predefine skipped tests by calling the API and passing in the config map
* Terraform should be able to schedule CIS scan run with an option of which profile to run it with

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `63306835a`**

- User is able to run cis scans using Permissive & Hardened Profiles from the API and the UI.
<img width="853" alt="Screen Shot 2020-03-06 at 9 37 19 PM" src="https://user-images.githubusercontent.com/26032343/76137509-cd575b00-5ff2-11ea-9f0f-832702ccc6a7.png">
<img width="1289" alt="Screen Shot 2020-03-06 at 9 37 09 PM" src="https://user-images.githubusercontent.com/26032343/76137510-ce888800-5ff2-11ea-8526-24a7758437a2.png">
