### ISSUE TITLE
links are only updating for in-stack services?

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2532]
Stack 1
ServiceA <- Service B(external service)
Stack 2
Service C <- Service 1/B

Remove Service B, then create service B. Link in service A will be updated, in service C - will not.

**Comment by deniseschannon** [comment]
I don't completely follow what you're trying to do.

What I thought you were trying to achieve:

Stack 1
Service A linked to Service B (in A, service links to service B)
Stack 2
Service C linked to Stack 1/ServiceB (in service C, service links to stack1/service B)

When I remove ServiceB, links are removed on both Service A and service C. When I create serviceB again, there shouldn't be any links (unless you have a selector link).

**Comment by ndelitski** [comment]
@deniseschannon Here i didn't event try to use service links, just experimenting with `links` and `external_links` and have noticed an inconsistent behavior: local links are recoverable, external_links - not, for them i have to upgrade/relaunch main service with `external_links` definition.
btw upgrading is also buggy(and not working with sidekicks yet? all my services have sidekicks :D).
When i click upgrade, add new link, service have changed state to "upgraded" but link did not appear neither in UI nor in DNS.
FYI I a have a common service in one stack and it is linked to almost every service in other stacks. If i recreate this common service all links to it will be dropped, it is an external service and service links are not properly working yet... editing too

**Comment by deniseschannon** [comment]
Can you provide how you're starting services? Are you only using rancher-compose? How are you removing stacks? 

I had assumed you were using the UI based on your descriptions, but your most recent comment makes it seem like you are using rancher-compose. 

If using rancher-compose, it's best to provide a docker-compose.yml and rancher-compose.yml files as well as the exact commands that you did.

**Comment by ndelitski** [comment]
super simple example of what i was saying. Yes, i was using `rancher-compose -p {stack} -f {docker-compose-file} -r {rancher-compose-file which was empty for this case} up -d` for launching stack, but removing services i was doing from UI.
```yml
service-A:
  image: nginx:1.9.4
service-B:
  image: nginx:1.9.4
  links:
    - service-A:sv
    - temp/service-EXT:sve
```
stack: temp
```yml
service-EXT:
  image: nginx:1.9.4
  labels:
    foo: bar
```
Link to service-A will recover if i recreate service-A(from UI), link to service-EXT will not. Under "recover" i mean that link will be recreated, and corresponding dns answer will appear in hosts network agent WITHOUT touching service-B 
```
Rancher	v0.44.0
Cattle	v0.107.0
User Interface	v0.65.0
Rancher Compose	v0.5.1
```

**Comment by deniseschannon** [comment]
Links need to be under `external_links` when it's outside the stack.

http://docs.rancher.com/rancher/rancher-compose/#cross-stack-linking
