### ISSUE TITLE
[ui] Service links disappear when switching environment

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2533]
Open environment A in new tab(links are shown), switch to B(no links). Reload page. There are links in B, switch to A(no links again)
```
Rancher	v0.43.1
Cattle	v0.106.0
User Interface	v0.63.0
Rancher Compose	v0.5.0
```

**Comment by deniseschannon** [comment]
This is a duplicate of this. https://github.com/rancher/rancher/issues/1389

Sometimes links aren't showing up when there are multiple environments.
