### ISSUE TITLE
Node controller panic

### ISSUE THREAD

**Issue by robinbraemer** [rancher/rancher#25332]
Rancher v2.3.5
ˋˋˋ
2020/02/08 20:49:49 [ERROR] NodeController ubuntu-4gb-fsn1-4 recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
8.2.2020 21:49:49 goroutine 33896 [running]:
8.2.2020 21:49:49 github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc0021e7d30)
8.2.2020 21:49:49 /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5
8.2.2020 21:49:49 panic(0x3210c60, 0x62d2810)
8.2.2020 21:49:49 /usr/local/go/src/runtime/panic.go:679 +0x1b2
8.2.2020 21:49:49 github.com/rancher/rancher/pkg/controllers/user/monitoring.(*clusterMonitoringEnabledHandler).syncWindowsNode(0xc004445f00, 0xc009d364e0, 0x11, 0x0, 0xc000076700, 0x7f06de15d6d0, 0x0, 0x0)
8.2.2020 21:49:49 /go/src/github.com/rancher/rancher/pkg/controllers/user/monitoring/cluster_monitoring_enabled_handler.go:58 +0xe6
8.2.2020 21:49:49 github.com/rancher/rancher/vendor/github.com/rancher/types/apis/core/v1.(*nodeController).AddHandler.func1(0xc009d364e0, 0x11, 0x0, 0x0, 0xc0021e7cd8, 0x3, 0x3, 0x0)
8.2.2020 21:49:49 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/core/v1/zz_generated_node_controller.go:149 +0xe0
8.2.2020 21:49:49 github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc00bff0b00, 0x2f9a320, 0xc00e9056a0, 0x0, 0x0)
8.2.2020 21:49:49 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:367 +0x371
8.2.2020 21:49:49 github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc00bff0b00, 0x0)
8.2.2020 21:49:49 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xef
8.2.2020 21:49:49 github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc00bff0b00)
8.2.2020 21:49:49 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:264 +0x2b
8.2.2020 21:49:49 github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00a414210)
8.2.2020 21:49:49 /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
8.2.2020 21:49:49 github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00a414210, 0x3b9aca00, 0x0, 0x1, 0xc004dea360)
8.2.2020 21:49:49 /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
8.2.2020 21:49:49 github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00a414210, 0x3b9aca00, 0xc004dea360)
8.2.2020 21:49:49 /go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
8.2.2020 21:49:49 created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run
8.2.2020 21:49:49 /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:256 +0xe8
8.2.2020 21:49:49

xxx

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/25203
