### ISSUE TITLE
RancherOS v1.5.5 requests a new IP from DHCP 

### ISSUE THREAD

**Issue by smart-nickname** [rancher/rancher#25339]
*What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Use Rancher to provision a cluster with RancherOS v1.5.5 (currently latest) using VMware node templates.
Creation method - Install from boot2docker ISO
Have a working DHCP server.

2. Wait for nodes to become online

3. Reboot or poweroff the nodes.

**Result:**

After their first reboot, the nodes ask for a new IP address and after they receive it, Rancher is no longer able to communicate to cluster's API (it tries to connect to old IPs).
The error is `Failed to communicate with API server`

**Other details that may be helpful:**
There was no such a behavior with RancherOS prior to v.1.5.5

**Environment information**
- Rancher version: v2.3.5
- Installation option (single install/HA): HA
- vCenter v6.7.0.42000 Build number 15132721

DHCP server log:

```
13:19:04 dhcp01 dhcpd[789]: DHCPDISCOVER from **00:50:56:90:a5:75** via ens192
13:19:05 dhcp01 dhcpd[789]: DHCPOFFER on xxx.xxx.141.242 to 00:50:56:90:a5:75 (rancher) via ens192
13:19:05 dhcp01 dhcpd[789]: DHCPREQUEST for xxx.xxx.141.242 (xxx.xxx.141.10) from 00:50:56:90:a5:75 (rancher) via ens192
13:19:05 dhcp01 dhcpd[789]: DHCPACK on xxx.xxx.141.242 to 00:50:56:90:a5:75 (rancher) via ens192
###**reboot**###
14:27:19 dhcp01 dhcpd[789]: DHCPDISCOVER from **00:50:56:90:a5:75** via ens192
14:27:20 dhcp01 dhcpd[789]: DHCPOFFER on xxx.xxx.141.136 to 00:50:56:90:a5:75 (rancher) via ens192
14:27:20 dhcp01 dhcpd[789]: DHCPREQUEST for xxx.xxx.141.136 (xxx.xxx.141.10) from 00:50:56:90:a5:75 (rancher) via ens192
14:27:20 dhcp01 dhcpd[789]: DHCPACK on xxx.xxx.141.136 to 00:50:56:90:a5:75 (rancher) via ens192

```

**Comment by janeczku** [comment]
@smart-nickname i have moved this over to the RancherOS repository: https://github.com/rancher/os/issues/2992
