### ISSUE TITLE
CIS Scan - UI/UX for the Scheduling

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25347]
CIS Scheduling: rancher/rancher#25326 
* Need to be able to schedule the CIS scan when creating a cluster
* There should be away to schedule the CIS scan from the tools -> CIS scan also (which is just a button to the cluster edit page)
* User will be able to select which CIS version to run
* User can select which "Profile" to run 
* User can enter a timing for the run
* User can enter a value for retention period of the report

**Comment by codyrancher** [comment]
Here's the look and feel:
![Screen Shot 2020-02-11 at 3 38 06 PM](https://user-images.githubusercontent.com/55104481/74286578-46f67480-4ce5-11ea-8310-a910b5820ceb.png)

@leodotcloud here are the fields and values I'm currently using in case you want to use them for the backend to reduce integration effort. I'm not sure if cisScan should be under services so let me know.

1. rancherKubernetesEngineConfig.services.cisScan.scheduled.enabled === true | false
1. rancherKubernetesEngineConfig.services.cisScan.scheduled.profile === 'rke-cis-1.4-permissive' | 'rke-cis-1.4-hardened' 
1. rancherKubernetesEngineConfig.services.cisScan.scheduled.intervalHours === number
1. rancherKubernetesEngineConfig.services.cisScan.scheduled.retention === number

**Comment by codyrancher** [comment]
I updated the interval to be a cron.

**Comment by sowmyav27** [comment]
Verified on master-head

User is able to schedule a scan for the cluster 
<img width="1213" alt="Screen Shot 2020-03-20 at 2 59 45 PM" src="https://user-images.githubusercontent.com/26032343/77209452-8457da00-6abb-11ea-92e5-bb1c7d33a6da.png">


Other issues related to schedule scan are being tracked separately

Closing this issue.
