### ISSUE TITLE
Azure node driver fixes

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#25342]
Azure Node Driver needs to support:

1. Update to the latest client of Azure and relevant Docker scripts

1. Use a pre-baked image that may or may not include Docker already. https://github.com/rancher/rancher/issues/23010

1. SLES Docker installs. https://github.com/rancher/rancher/issues/25071

1. https://github.com/rancher/rancher/issues/11674 <- Crux of the following issues problems
The user needs to be able to pass an existing network security group(NSG).
Nodepools will need to use 1 NSG per pool instead of one per node.
Existing node templates need to continue to function.
New node templates will default to the NSG per node pool.
NSG name is updatable and new nodes in node pool would be placed in new NSG, while old nodes stay in old NSG. 
   1. https://github.com/rancher/rancher/issues/17181
   1. https://github.com/rancher/rancher/issues/22147

Secondary goals:
1. Use cloud init similar to the vsphere provider.

Docker machine has an upstream attempt at resolution for issue 11674. 
https://github.com/docker/machine/pull/4486

**Comment by aiyengar2** [comment]
https://github.com/rancher/machine/pull/72 addresses #1 and #2

**Comment by aiyengar2** [comment]
https://github.com/rancher/install-docker/pull/45 addresses milestone 3

**Comment by aiyengar2** [comment]
https://github.com/rancher/machine/pull/77 addresses milestone 4

**Comment by deniseschannon** [comment]
Moved this to v2.4.4 as half the issues will be in v2.4.3 and the other will be with v2.4.4

**Comment by cloudnautique** [comment]
Requirement 4 Updates:
1. We are going to leave the default existing behavior of the node template for Azure. It will continue to create 1 NSG per node.
1. A user can create an NSG out-of-band and pass that into a node template. All node templates in a cluster can be passed the same NSG.
1. A user can create an NSG out-of-band and edit an existing clusters node templates and replace all nodes to migrate to this new model.

Rancher will not create a single NSG for the cluster, that will be left to the user.

**Comment by soumyalj** [comment]
Tested with master-head(1afaa4768)
1. Create azure template with NSG field empty. 
   Create azure cluster with the template. 
   One NSG per VM was created and cluster was active and functional
2. Created azure template with NSG field with a NSG name(non existent)
    Create azure cluster with the template. 
    Only one NSG was created per node pool using  the template
    Multiple clusters created using the same template will use the same NSG

**Comment by aiyengar2** [comment]
Quick note about existing NSGs:

Based on the discussion documented in https://github.com/rancher/machine/pull/77#issuecomment-625564555, it will be the user's responsibility to set up an existing NSG with the expected security rules before providing it on a node template.

The rules that Rancher will expect from existing NSGs during provisioning are detailed in the `Port Requirements` section of the [Rancher docs](https://rancher.com/docs/rancher/v2.x/en/installation/requirements/ports/).
