### ISSUE TITLE
UI for RHEL 8 Support with Docker CE

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#25346]
UI for https://github.com/rancher/rancher/issues/23045

To test:

* Add Red Hat 7 and Red Hat 8 to a custom cluster
* Open node detail page for each node
* OS name (before kernel version in gray) should be shortened to RHEL

**Comment by Ellenqs** [comment]
Validated on Rancher `v2.5-head (b152ce8)` and `master-head`.

**Steps:**

- Deploy rancher.
- Create two custom clusters on aws,
  one with Red Hat7 ami-0057f60d0abc2fcc7
  one with Red Hat8 ami-0ea9f93373eadced4.
- Open node detail page for each node. 

**Results:**
OS name is shortened to "RHEL"
![Screen Shot 2021-02-01 at 5 37 54 PM](https://user-images.githubusercontent.com/75277058/106543535-c6fb8880-64ba-11eb-8641-e5a83f140d1c.png)
![Screen Shot 2021-02-01 at 5 43 55 PM](https://user-images.githubusercontent.com/75277058/106543544-c9f67900-64ba-11eb-9cf0-8ab632a16c59.png)
