### ISSUE TITLE
[ui] client-side error when editing external service

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2534]
<img width="1391" alt="screenshot 2015-11-04 03 28 12" src="https://cloud.githubusercontent.com/assets/3070298/10926012/3502543e-82a4-11e5-845f-c1760722919a.png">
```
Rancher	v0.43.1
Cattle	v0.106.0
User Interface	v0.63.0
Rancher Compose	v0.5.0
```

**Comment by deniseschannon** [comment]
FYI, it kind of breaks the "Edit" for other services for a little bit. We did a major UI refactoring and just missed editing external services.

**Comment by tfiduccia** [comment]
Version - Master with latest reskin UI
Verified fixed
