### ISSUE TITLE
CIS Scan - UI/UX for Alerting

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25349]
Alert: rancher/rancher#25326
* Add a new option to the alert page "Security Scan"
* The bottom section will have the option for "Completed Scan" or "Has Failure"
* Send for "Critical" or "Info"

**Comment by codyrancher** [comment]
Here's the look and feel.
![Screen Shot 2020-02-11 at 1 25 02 PM](https://user-images.githubusercontent.com/55104481/74275965-1527e280-4cd2-11ea-9f2c-2aca130eb2c8.png)

@leodotcloud here are the values I'm currently using in case you want to use them for the backend to reduce integration effort.
1. _targetType === "cisScan"
1. nodeRule.condition === "completedScan"
1. nodeRule.condition === "hasFailure"

**Comment by sowmyav27** [comment]
Currently on master-head - ui tag: `latest2`

Go to Cluster --> Tools --> CISscans --> "Set Alert"

Expected:

**Comment by codyrancher** [comment]
@sowmyav27 @deniseschannon 

There's actually nothing in the description of this issue which mentions the Set Alert button. 

What has been reported actually sounds like a new feature request or a request to change the existing feature. Can we either update the description or create a new issue and have Tani approve either?

**Comment by sowmyav27** [comment]
Closing this issue as there are separate bugs logged for issues
- https://github.com/rancher/rancher/issues/25853
- https://github.com/rancher/rancher/issues/25852
