### ISSUE TITLE
Issue creating vSphere node templates v2.3.5

### ISSUE THREAD

**Issue by bananflugan** [rancher/rancher#25354]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Select node templates, choose to add a template and try select a data store.

**Result:**
Error: "Please select a new value. The following is no longer valid:
"PATH to data store""

**Other details that may be helpful:**
Templates that were created with v2.3.2 are still working. Editing existing templates will produce this issue and creating new templates is almost impossible. The cloud credential is correct and the data store paths are also correct, they are even detected by Rancher.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM(U18.04) 2 cores 8GB ram
- Kubernetes version (use `kubectl version`): 1.15.5

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by bananflugan** [comment]
Update:

It is possible that this bug occurs if you hav more than one data center in vSphere. If i create a new template, which is sometimes doable by enabling and disabling the toggle for Data Store cluster, i can then create the template. 

However, no nodes can be created with this new template, "Error creating machine: Error in driver during machine creation: The input arguments had entities that did not belong to the same datacenter".

Going back and editing the template i see that Rancher complains that the recourse pool and data store is all of a sudden not valid and on top of that belongs to a different data center...

**Comment by dannietjoh** [comment]
I beleeve Rancher is trying to be too smart about prepending paths to vsphere resources.
I'm running a lab on a few non vpshere (ESXi only) nodes and experience the same issue.

A workaround is to create a node template via the API or edit it in the API after creating it in the UI.
Please not that this too has a bug where it adds non-nullable attributes in the json, to work around just remove any key which has a value of null in the vmwarevsphereConfig section.

**Comment by luthermonson** [comment]
@dannietjoh https://github.com/rancher/rancher/issues/24510

**Comment by Turb0Fly** [comment]
Having this issue for the resource field. I have 2 vCenter server and Rancher will always input values from the 1st vCenter even though we select the correct ones from the drop down menus.  @dannietjoh suggestion worked. When we go to edit the node template in the API , in the **vmwarevsphereConfig** field, we can see that the resource pool value is from the 1st vCenter.  We update it through the API and it worked. We are able to use that node template to launch nodes in our 2nd vCenter server.

**Comment by ansilh** [comment]
Hi @Turb0Fly - Could you please check the issue https://github.com/rancher/rancher/issues/26997 since your description matches the symptoms I've observed in that bug?

**Comment by Turb0Fly** [comment]
Hi @ansilh . It does in fact exhibits exactly the same symptoms.
