### ISSUE TITLE
rancher remove instances from active hosts when it could remove from inactive

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2536]
Service is running on both hosts. Make one host inactive, scale down. In my case rancher removed container from active host and keep one on inactive lol.
I think containers on inactive hosts should not be considered as green.

**Comment by deniseschannon** [comment]
When a host is in inactive state, the only change is that no new containers will be deployed onto it, so I don't believe your title is accurate. 

The service has no knowledge of which hosts are active or inactive so it could have removed containers on either the active or inactive hosts. If you want the containers to be redeployed, you'd have to remove it.

**Comment by ndelitski** [comment]
Maybe the service didn't know which host it is running on, but the scheduler which i think responsible for scaling and deploying operations should have knowledge where to shutdown instances - from active host or inactive, what do you think? But it turns out i have 2 hosts and 2 instances, i make decision to down host, or it was terminated by itself, pressed scaledown button on the service and i have ZERO healthy instances because rancher kill instance on a single healthy host, where is the logic from a user point of view?

**Comment by vincent99** [comment]
The logic is as Denise said, `inactive` only means new containers are not scheduled to that host.  The health of the host is determined by the responsiveness of the `rancher/agent`, and the healthchecks for the individual containers. 

If `inactive` meant anything stronger than that, the only sensible thing to do would be to immediately stop and reschedule every container on that host when it is deactivated... Why wait for the user to go clicking things?

**Comment by ndelitski** [comment]
@vincent99 Does rancher reschedule every container on inactive host? it even continues to show that containers are "green", so confusing. Sorry, but I am not getting what you was trying to say. In my opinion, first rancher should have a timeout window on which agent could reconnect, otherwise it should mark all deployed to this host containers with some more clear sign that "green" label, then redeploy if it can(i was saying this in an another issue). If agent reconnect time was over, then crushed host should not be counted anymore(until agent connect but it is unlikely if it already was not able connect in an adequate time), rancher began redeploying and if i consider necessary to scale down at that moment, rancher should not consider instances that was running long ago on a crushed host(even if i didn't disable it in UI), so in my case described in a first post i expect that rescale from 2 to 1 will do nothing because of actual scale was already 1.

**Comment by deniseschannon** [comment]
@ndelitski Rancher would never schedule containers on an inactive host. An inactive host means that containers will not be deployed, but as long as the containers are running on the host, there is nothing wrong with the service. 

Note: There is a difference between an inactive host and a reconnecting host. 

If your host is in reconnecting, the last known state of the containers are displayed in Rancher. If you had a service with a health check enabled on it, then it would be re-scheduled.

**Comment by bitninjaio** [comment]
Any update on it? I also think the scheduler should prefer to destroy the containers on an inactive node upon scaling down. This way we could control which node we want to be destroyed.
