### ISSUE TITLE
Cannot import clusters if Rancher is behind a proxy

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#25372]
Version: v2.3-head `6eecc2c8b`

This appears to be related to https://github.com/rancher/rancher/issues/24876 however, I didn't reopen that issue because the errors in logs appear to be different. I am not entirely sure this is the exact same issue.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug, possibly regression of #24876 which was last known to be working as of Feb 3rd, 2020

**Steps to reproduce (least amount of steps as possible):**
- Create a web proxy such as with squid. Ensure you have properly configured the squid.conf
```
acl localnet src 10.0.0.0/8     # RFC1918 possible internal network
acl localnet src 172.16.0.0/12  # RFC1918 possible internal network
acl localnet src 192.168.0.0/16 # RFC1918 possible internal network
acl SSL_ports port 443
acl SSL_ports port 6443         # k8s api ssl_ports
acl Safe_ports port 80          # http
acl Safe_ports port 21          # ftp
acl Safe_ports port 443         # https
acl Safe_ports port 70          # gopher
acl Safe_ports port 210         # wais
acl Safe_ports port 1025-65535  # unregistered ports
acl Safe_ports port 280         # http-mgmt
acl Safe_ports port 488         # gss-http
acl Safe_ports port 591         # filemaker
acl Safe_ports port 777         # multiling http
acl Safe_ports port 6443        # k8s api safe_ports
acl CONNECT method CONNECT
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow localhost manager
http_access deny manager
http_access allow localnet
http_access allow localhost
http_access allow all
http_port 3128
coredump_dir /var/spool/squid
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern (Release|Packages(.gz)*)$      0       20%     2880
refresh_pattern .               0       20%     4320
```
- Create a machine to act as the Rancher server. For the host, append your `/etc/environment` so the machine will leverage the squid proxy. An example is below.
```
# Example only, fill in public IP/DNS of your squid machine
# Proxy vars
HTTP_PROXY="http://proxy_url:port"
http_proxy="http://proxy_url:port"
HTTPS_PROXY="http://proxy_url:port"
https_proxy="http://proxy_url:port"
NO_PROXY="localhost,127.0.0.1,0.0.0.0"
```
Set up docker on the rancher host to leverage the proxy:
`sudo mkdir -p /etc/systemd/system/docker.service.d`
`sudo vi /etc/systemd/system/docker.service.d/http-proxy.conf`
Add content to http-proxy.conf:
```
# Example only, fill in public IP/DNS of your squid machine
[Service]
Environment="HTTP_PROXY=http://proxy_url:port/" "HTTPS_PROXY=http://proxy_url:port/" "http_proxy=http://proxy_url:port/" "https_proxy=http://proxy_url:port/" "NO_PROXY=localhost,127.0.0.1,0.0.0.0"
```
Restart docker:
`sudo systemctl daemon-reload && sudo systemctl restart docker`
You may need to reboot the machine or manually export the necessary proxy env vars as well so the host is also utilizing the proxy.
- Run single-node rancher:
```
# Example only, fill in public IP/DNS of your squid machine
docker run -d --restart=unless-stopped \
  -v /home/ubuntu/state:/var/lib/rancher \
  -p 80:80 -p 443:443 \
  -e HTTP_PROXY="http://proxy_url:port" \
  -e HTTPS_PROXY="http://proxy_url:port" \
  -e NO_PROXY="localhost,127.0.0.1,0.0.0.0" \
  rancher/rancher:v2.3-head
```
- Create a k3s cluster or rke cluster and attempt to import the cluster. This will never succeed. Rancher will constantly show "Waiting for API to be available" in the UI. And if you look at the Rancher server logs you'll see:
`2020/02/12 01:26:07 [ERROR] ClusterController _all_ [user-controllers-controller] failed with : failed to start user controllers for cluster c-xhdrz: failed to contact server: Get https://10.43.0.1:443/api/v1/namespaces/kube-system?timeout=30s: proxyconnect tcp: waiting for cluster agent to connect`

**Result:**
Rancher cannot import any clusters if Rancher is running with a proxy. The cattle-node-agent and cattle-cluster-agent come up and are in a Running state. cattle-cluster-agent logs show no issues. cattle-node-agent logs show the following, repeating infinitely:
```
time="2020-02-12T01:39:50Z" level=info msg="Connecting to wss://REDACTED_RANCHER_HOST_IP/v3/connect with token t8rmfll9rx4brhdmn6j8shm6z79t57nmnmpkmngkngl5q7ql45k7cf"
time="2020-02-12T01:39:50Z" level=info msg="Connecting to proxy" url="wss://REDACTED_RANCHER_HOST_IP/v3/connect"
time="2020-02-12T01:39:50Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-8nwhk/m-f263be449487\" not found" error="websocket: bad handshake"
time="2020-02-12T01:39:50Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
```

It looks like this m-f263be449487 object does not exist. And I have reproduced this several times.

**Expected Result:**
Rancher should import the clusters without any issues.

**Comment by davidnuzik** [comment]
Note, while testing today I tested with rke/k3s clusters behind a proxy or not. It doesn't seem to matter if the cluster itself is behind a proxy or not, only when Rancher itself is behind a proxy do we run into this issue.

**Comment by chrisbulgaria** [comment]
I had seen this before, #22474 . The title is misleading but how I worked around is by actually including the 10.x in the NO_PROXY , see closing comment . Never investigated further why this is needed . Somit this is the same it’s not related to #24876 as this was long before.

**Comment by davidnuzik** [comment]
Thanks. I think we should re-test with specifying the 10.x network in NO_PROXY env var.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head  6eecc2c8b

* After adding `10.43.0.1` to NO_PROXY, the cluster is able to provision.

**Comment by imlight** [comment]
Run below command in the cluster which you are implementing 

kubectl get svc 

Use  the IP address from above command , and add that in noProxy 


kubectl -n cattle-system create secret generic tls-ca-additional --from-file=ca-additional.pem=/ProxyRootCA.crt

helm upgrade rancher rancher-stable/rancher  --set hostname=np-rancher --set ingress.tls.source=secret  --set privateCA=true --set proxy="http://example.com" --set noProxy="127.0.0.1\,*.external.com\,.svc\,.cluster.local\,<IP from first command"" --set additionalTrustedCAs=true

**Comment by Huixxi** [comment]
> Run below command in the cluster which you are implementing
> 
> kubectl get svc
> 
> Use the IP address from above command , and add that in noProxy
> 
> kubectl -n cattle-system create secret generic tls-ca-additional --from-file=ca-additional.pem=/ProxyRootCA.crt
> 
> helm upgrade rancher rancher-stable/rancher --set hostname=np-rancher --set ingress.tls.source=secret --set privateCA=true --set proxy="http://example.com" --set noProxy="127.0.0.1,*.external.com,.svc,.cluster.local,<IP from first command"" --set additionalTrustedCAs=true

I met those problems and some questions:
1. what will get after `kubectl get svc`, do you mean the kubernetes's cluster ip?
2. the second command, I got error: error reading /ProxyRootCA.crt: no such file or directory
