### ISSUE TITLE
[RFE] Support adding extra link in Rancher UI footer 

### ISSUE THREAD

**Issue by liulipengju** [rancher/rancher#25389]
Support adding extra link in Rancher UI footer

In China, you need to apply a record number from government if the website is accessible from internet.
And users need to put this number and link in the UI footer.

**Comment by loganhz** [comment]
https://github.com/rancher/rancher/compare/master...loganhz:rancher-footer
https://github.com/rancher/ui/compare/master...loganhz:rancher-footer

**Comment by loganhz** [comment]
close in favor of https://github.com/rancher/rancher/issues/16474
