### ISSUE TITLE
Deploying applications through local disk to Rancher yields installation unusable

### ISSUE THREAD

**Issue by patrickdappollonio** [rancher/rancher#25383]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug (on Rancher 2.2.9, haven't tried 2.3.x)

**Steps to reproduce (least amount of steps as possible):**

* Create a cluster through Rancher
* Clone to a local directory any helm chart that requires dependencies, in our
    testing, the Helm Chart for Kong
    [at this specific commit](https://github.com/helm/charts/commit/0580e453e)
    was tested, but the situation can also be replicated by using a helm chart
    that's broken (for example, a template syntax error) or that has
    dependencies, and then `cd` into the folder `charts/stable/kong`.

 ```bash
# Clone helm chart
cd $(mktemp -d) && git clone git@github.com:helm/charts.git

# Reset to specific commit (YMMV testing with others, see below)
cd charts && git reset --hard 0580e453e

# cd into the specific chart
cd charts/stable/kong

# Install it as an app
rancher app install . kong
```

* With a `rancher` CLI properly configured pointing at the cluster created with
    the first step, install the app by executing `rancher apps install . kong`.
    To accelerate the process, you can create a few other copies, like `kong2`,
    `kong3`, and so on.

**Expected Result:**
* Rancher will display the fact that the installation failed because the
    Helm Chart dependencies weren't installed (`helm dep update`) before
    sending the app to install.

**Actual Result:**

* This is a chain reaction of events:
  * The application shows correctly as broken in the UI
  * After a couple of minutes, the Rancher UI becomes unresponsive with the
      error: `etcdserver: mvcc: database space exceeded`
  * Rancher can't be used anymore from the UI, the CLI or directly using
      `kubectl`.

The reason behind the issue is that each helm install failure seems to cause
Rancher to attach the payload of the repository cloned in the CRD
`apps.project.cattle.io` (since it's the way to be able to store it due to being
installed from a local directory). In an etcd using multi-version concurrency
control, etcd ends up holding to several large etcd document revisions (which
include each file from the folder, base64-encoded in the list of files) which
causes a massive increase in the etcd database size, preventing it from running
compaction and defragment tasks in-time resulting in the cluster hitting the
maximum database size and then switching to read-only mode.

https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#what-does-mvcc-database-space-exceeded-mean-and-how-do-i-fix-it

**Other details that may be helpful:**

As stated above, we've seen this issue with both Helm charts with dependencies
or broken templates, although we suspect anything that can make the helm
installation crash would do it. An example error from when the template is
broken:

```
"message": "wait helm template failed. Error: parse error in \"kong/templates/_helpers.tpl\": template: kong/templates/_helpers.tpl:255: unexpected \"=\" in operand\n: exit status 1",
```

And this is an example error from when there's a requirement not previously
installed:

```
"message":"wait helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: postgresql\n: exit status 1",
```

The CRD which holds the information about the deployed application contains a
`.spec.files` value in the JSON content which holds all the files base64'd
(which can become quite big if there's several files in it):

* Example application JSON output:
    https://gist.github.com/patrickdappollonio/4acb3fee1d4cca245c40ccc0bfcafb1a
* Example etcd write-ahead log content:
    https://gist.github.com/patrickdappollonio/067ae77a9d8baa264429c241323d2a26

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom
    left in the UI):
```
Rancher: v2.2.9
User Interface: v2.2.98
Helm: v2.10.0-rancher11
Machine: v0.15.0-rancher8-1
```

- Installation option (single install/HA): HA deployment with 2 replicas on K8s.

**Cluster information**
- Cluster type: Hosted
- Machine type and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.13.5
- Docker version (use `docker version`):

```
$ docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.8
 Git commit:        d7080c1
 Built:             Tue Feb 19 23:07:53 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d7080c1
  Built:            Tue Feb 19 23:07:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

gzrancher/rancher#8427

**Comment by rancher-max** [comment]
I am able to recreate this following the steps exactly as given. Thank you for all the detail! This is a great issue write-up.

The only note I would like to add is that I did this on a single node, non-HA install. 
In my case, first the cluster went to `Unavailable` status in the UI, then shortly after rancher became unresponsive and would no longer work through UI or CLI. 

Following the logs with `docker logs -f <image_name>` I saw repetitive:
```
2020/06/19 21:20:50 [ERROR] AppController p-n7p28/kong [helm-controller] failed with : wait helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: postgresql
: exit status 1
2020/06/19 21:20:51 [ERROR] AppController p-n7p28/kong [helm-controller] failed with : wait helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: postgresql
: exit status 1
```
Then, after Rancher crashed, the logs started showing:
```
I0619 21:22:07.212421       6 controllermanager.go:455] Started "replicationcontroller"
I0619 21:22:07.245672       6 replica_set.go:182] Starting replicationcontroller controller
I0619 21:22:07.609660       6 controller_utils.go:1027] Waiting for caches to sync for ReplicationController controller
I0619 21:22:07.948847       6 trace.go:76] Trace[1585541045]: "GuaranteedUpdate etcd3: *core.Endpoints" (started: 2020-06-19 21:22:02.139014847 +0000 UTC m=+48.120426948) (total time: 5.508880544s):
Trace[1585541045]: [2.337142577s] [2.337142577s] initial value restored
Trace[1585541045]: [3.532608874s] [1.195466297s] Transaction prepared
Trace[1585541045]: [5.150661486s] [1.618052612s] Transaction committed
Trace[1585541045]: [5.508880544s] [358.219058ms] END
2020-06-19 21:22:09.591490 W | etcdserver: apply entries took too long [401.327704ms for 1 entries]
2020-06-19 21:22:09.595467 W | etcdserver: avoid queries with large range/delete range!
```

This happens with many types. i.e `Started "daemonset"`, `Started "nodeipam"`, `Started "attachdetach"`, etc.

**Comment by rancher-max** [comment]
Note this also applies for rancher v2.4.2, and cli version does not seem to have an effect.

**Comment by rancher-max** [comment]
#### Validated in both `master-3301-head` and `v2.4-3302-head` using CLI version v2.4.5

- App does not deploy, but rancher server does not crash
- Cluster also remains accessible
- The errors do not repeat constantly in the logs and server health is maintained correctly
