### ISSUE TITLE
Catalog service doesn't handle folder rename

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2538]
Steps to reproduce:

1) Had folder under "templates" named "externaldns". 
2) Renamed the folder to "route53" using "git mv" command. 

People who were using catalog-service prior to 2), now started seeing 2 catalog items: externaldns and route53

@vincent99 @sangeethah

**Comment by prachidamle** [comment]
Fix has ben submitted

**Comment by sangeethah** [comment]
The latest version of rancher-catalog service is not getting released with v0.47.0 release. So moving it to next milestone.

**Comment by sangeethah** [comment]
Tested with latest build from master - dec 4 and rancher-catalog service version - v0.4.0 .

When folder under "templates" get renamed using git mv command , there is only 1 catalog entry with the new version in catalog list view. It could take up to 5 mts for the changes to get propagated to the UI.
