### ISSUE TITLE
rancher2.3.5，各项目之间切换还是出现了点击无反应的情况

### ISSUE THREAD

**Issue by yizhishang** [rancher/rancher#25393]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.5` UI: `v2.3.36` |
|Route|`workload`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

If you would like to ask questions in Chinese, please add `rancher2` to join Rancher WeChat group. Thanks
