### ISSUE TITLE
vSphere :  Adding node to cluster fails with write tcp: use of closed network connection

### ISSUE THREAD

**Issue by gillarda** [rancher/rancher#25392]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Create vSphere Credential and Node Template
- Create a cluster with the vSphere Provider
- Node creation may fail
- If node creation works, add another node to the node pool

**Result:**
```
2020/02/13 11:12:49 [ERROR] NodeController c-ggm28/m-b9gfv [node-controller] failed with : Error creating machine: Error in driver during machine creation: Put https://vcenter.local.net:443/folder/EQL/boot2docker.iso?dcPath=%!F(MISSING)VSPHERE-CLUSTER&dsName=Datastore+04: write tcp 172.17.0.2:43242->10.8.73.10:443: use of closed network connection
```
or
` write: broken pipe` instead of `use of closed network connection`
or
` 500 Internal Server Error` instead of `use of closed network connection`

**Other details that may be helpful:**
More logs : 
```
2020/02/13 11:12:42 [DEBUG] stdout: (k8s-agd5m2) Uploading Boot2docker ISO ...
2020/02/13 11:12:42 [INFO] [node-controller-rancher-machine] (k8s-agd5m2) Uploading Boot2docker ISO ...
2020/02/13 11:12:42 [DEBUG] REST UPDATE apis/management.cattle.io/v3/c-ggm28/nodes/m-b9gfv
2020/02/13 11:12:42 [DEBUG] NodeController calling handler nodeHandler c-ggm28/m-b9gfv
2020/02/13 11:12:42 [DEBUG] NodeController calling handler user-node-remove c-ggm28/m-b9gfv
2020/02/13 11:12:42 [DEBUG] NodeController calling handler machinesSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:42 [DEBUG] NodeController calling handler machinesLabelSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:42 [DEBUG] NodeController calling handler cordonFieldsSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:42 [DEBUG] NodeController calling handler drainNodeSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:42 [DEBUG] NodeController calling handler machineTaintSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:44 [DEBUG] REST GET api//v1//namespaces/kube-system
2020/02/13 11:12:44 [DEBUG] REST LIST api//v1//componentstatuses
2020/02/13 11:12:45 [DEBUG] REST GET api//v1//namespaces/kube-system
2020/02/13 11:12:45 [DEBUG] REST LIST api//v1//componentstatuses
2020/02/13 11:12:46 [DEBUG] REST UPDATE api//v1/cattle-system/secrets/mc-m-b9gfv
2020/02/13 11:12:46 [DEBUG] SecretController calling handler secretsController cattle-system/mc-m-b9gfv
2020/02/13 11:12:46 [DEBUG] SecretController calling handler management-cloudcredential-controller cattle-system/mc-m-b9gfv
2020/02/13 11:12:46 [DEBUG] SecretController calling handler mgmt-global-dns-provider-secret-syncer cattle-system/mc-m-b9gfv
2020/02/13 11:12:46 [DEBUG] SecretController calling handler secretsController cattle-system/mc-m-b9gfv
2020/02/13 11:12:49 [DEBUG] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2020/02/13 11:12:49 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2020/02/13 11:12:49 [DEBUG] REST UPDATE apis/management.cattle.io/v3/c-ggm28/nodes/m-b9gfv
2020/02/13 11:12:49 [DEBUG] stdout: 
2020/02/13 11:12:49 [INFO] [node-controller-rancher-machine] 
2020/02/13 11:12:49 [DEBUG] REST UPDATE apis/management.cattle.io/v3/c-ggm28/nodes/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler nodeHandler c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler user-node-remove c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler machinesSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler machinesLabelSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler cordonFieldsSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler drainNodeSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler machineTaintSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler nodeHandler c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler user-node-remove c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler machinesSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler machinesLabelSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler cordonFieldsSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler drainNodeSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler machineTaintSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [INFO] Generating and uploading node config k8s-agd5m2
2020/02/13 11:12:49 [DEBUG] getNodeTemplate parsed [cattle-global-nt:nt-wvt8j] to ns: [cattle-global-nt] and n: [nt-wvt8j]
2020/02/13 11:12:49 [DEBUG] REST GET apis/management.cattle.io/v3/cattle-global-nt/nodetemplates/nt-wvt8j
2020/02/13 11:12:49 [DEBUG] Cleaning up [/opt/jail/c-ggm28/management-state/node/nodes/k8s-agd5m2]
2020/02/13 11:12:49 [DEBUG] REST UPDATE apis/management.cattle.io/v3/c-ggm28/nodes/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler nodeHandler c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler user-node-remove c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler machinesSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler machinesLabelSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler cordonFieldsSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler drainNodeSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler machineTaintSyncer c-ggm28/m-b9gfv
2020/02/13 11:12:49 [ERROR] NodeController c-ggm28/m-b9gfv [node-controller] failed with : Error creating machine: Error in driver during machine creation: Put https://vcenter.local.net:443/folder/EQL/boot2docker.iso?dcPath=%!F(MISSING)VSPHERE-CLUSTER&dsName=Datastore+04: write tcp 172.17.0.2:43242->10.8.73.10:443: use of closed network connection
2020/02/13 11:12:49 [DEBUG] NodeController calling handler cluster-provisioner-controller c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler cluster-stats c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler nodepool-provisioner c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController calling handler node-controller c-ggm28/m-b9gfv
2020/02/13 11:12:49 [DEBUG] NodeController c-ggm28/m-b9gfv completed with dropped err: [node-controller] failed with : Error
```

First node creation generally works. Adding more nodes fails.

**Environment information**
- Rancher version : 2.3.5 and 2.3-head
- Installation option (single install/HA): single install
- Rancher host : Centos 7.7 and docker 19.03.5
- Rancher K8S Nodes : RancherOS 1.5.5 (so using boot2docker as per https://github.com/rancher/rancher/issues/24948#issuecomment-577453323)

I have seen issues #24686, #24351, #24315
I have tried the (not-so related) workaround in https://github.com/rancher/rancher/issues/24315#issuecomment-564173340 without success.

**Comment by gillarda** [comment]
I tried with a Rancher instance deployed on a RKE Kubernetes cluster, but the results are still the same.

**Comment by Charlio99** [comment]
Same problem here

**Comment by Charlio99** [comment]
Any news on this? @gillarda did you managed to solve it?

**Comment by gillarda** [comment]
Nope, I am waiting on 2.3.6 to see if there are new developments regarding the vsphere provider.
I'll have to try and dig deeper then because we cannot upgrade to 2.3  at the moment and benefit from a couple of nice new features and bug corrections.

**Comment by Charlio99** [comment]
> Nope, I am waiting on 2.3.6 to see if there are new developments regarding the vsphere provider.
> I'll have to try and dig deeper then because we cannot upgrade to 2.3 at the moment and benefit from a couple of nice new features and bug corrections.

Does it works in any version prior to 2.3?

**Comment by gillarda** [comment]
> 
> 
> > Nope, I am waiting on 2.3.6 to see if there are new developments regarding the vsphere provider.
> > I'll have to try and dig deeper then because we cannot upgrade to 2.3 at the moment and benefit from a couple of nice new features and bug corrections.
> 
> Does it work in any version prior to 2.3?

We did not have any issue of this type in 2.0, 2.1 or 2.2, so I assumed it came along the big update in the vsphere provider in 2.3.

**Comment by gillarda** [comment]
I upgraded to 2.3.6, behavior is still the same.
I dug a bit and it appears to have something to do with spaces in the datastores names ?
If the datastores in the datastore cluster do not have spaces in their names, the node is deployed without issue, if there are spaces, I get the error above (the datastore cluster name can contain spaces).

I used to be able to deploy to single datastores with spaces in them (I could do this in 2.2, 2.3.5, 2.3.6), but after a bunch of test iterations in 2.3.6, all of a sudden it appears I can no longer deploy nodes to single datastores with spaces in them...

**Comment by Daniel-Vaz** [comment]
Same issue here. 
Rancher Version: 2.4.6
vSphere version: vSphere Client version 6.7.0.20000

I am provisioning a cluster with rancherOS Nodes and most of them fail with the same error (the datastore that I am using has spaces in the name also).

Node template that I am using:
`resource "rancher2_node_template" "vSphereUPITemplateCP" {
   depends_on = [null_resource.ansible-deploy-rancher]
   name = var.upiTemplateNameCP
   description = "Terraform - UPI Downstream Cluster CP Template"
   cloud_credential_id = rancher2_cloud_credential.vsphere-terraform.id
   engine_insecure_registry = [var.PRurl]
   vsphere_config {
     cfgparam = ["disk.enableUUID=TRUE"]
     cpu_count = var.upiCPcpu
     creation_type = "legacy"
     disk_size = var.upiCPdiskMB
     memory_size = var.upiCPramMB
     datastore = var.datastore
     datacenter = var.datacenter
     hostsystem = var.esxiHost
     folder = var.folder
     pool = var.rscPool
     network = [var.nic]
   }
}
`

**Comment by efe136** [comment]
Same here with version 2.4.6. I just realized it creates only 2 nodes not else. then fail
