### ISSUE TITLE
rancher  exit unexpect

### ISSUE THREAD

**Issue by maoyangcao** [rancher/rancher#25390]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**

![F3875219-2AB0-4dc8-AA83-9974CF006791](https://user-images.githubusercontent.com/13943027/74418690-b904c000-4e83-11ea-8bae-a8bf10c06b38.png)

**Result:**
rancher  exit unexpect and container can not restart.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.3
- Installation option (single install/HA):
single 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
two Cluster 
create rke ,Imported ack
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
cloud
cpu:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
Stepping:              2
CPU MHz:               2494.224
BogoMIPS:              4988.44
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0,1

memory: 4G
- Kubernetes version (use `kubectl version`):

```
create rke : v1.13.5
import ack: v1.12.6-aliyun.1
``` 

- Docker version (use `docker version`):

```
1.13.1
```

**Comment by superseb** [comment]
Please fill in all the requested information in the issue template (especially specifications), can you also share what operating system you are using and how many clusters/node per cluster/projects etc you are using?

**Comment by maoyangcao** [comment]
> Please fill in all the requested information in the issue template (especially specifications), can you also share what operating system you are using and how many clusters/node per cluster/projects etc you are using?

two clusters 
create rke 
version : v1.13.5
node: 12
project:45
import ack
node:11
project:26
version: v1.12.6-aliyun.1

**Comment by superseb** [comment]
Whats the disk performance on the node running Rancher? Are you mounting `/var/lib/rancher` from a location on the host or just embedded?

**Comment by superseb** [comment]
Let me know if this still needs help
