### ISSUE TITLE
In hosts, the rancher/agent and rancher/agent-instance naming is too confusing.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#254]
The naming convention for rancher/agent container and the ranger/agent-instance container are too similarly named.

Can we update the agent-instance to something more distinctive?

Customers will get confused on which one is needed for what.

**Comment by blaggacao** [comment]
:+1: I'm confused :smile:

**Comment by meAmidos** [comment]
+1

**Comment by vincent99** [comment]
`rancher/agent` and `rancher/network-agent-or-load-balancer-or-something-like-that`?

**Comment by blaggacao** [comment]
how about

`rancher/client`  or `rancher/host-client` hinting at the server/client model

and then

`rancher/network-agent`

**Comment by deniseschannon** [comment]
In 1.2, we have moved away from using the `rancher/agent-instance`, so no longer valid.
