### ISSUE TITLE
K3s Integration - Cluster Update capability

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#25401]
To support the k3s integration in to the ember UI, work needs to be done to allow users to upgrade k3s from the UI. Based on some past discussion, it sounded like we might tweak the edit page so that we add in a section for upgrading k3s.

**Description:**
K3s will be integrating into Rancher 2.4.0 with at least these minimum requirements for the Rancher UI:

- Import K3s clusters using normal import flow
- Edit the cluster and show at least master configuration (includes k3s version) and provide means to upgrade the K3s cluster to a newer version via drop-down (depends on k3s backend which needs to supply a means to query if there is a newer update available, see https://github.com/rancher/k3s/issues/1359). Picking a newer version will tell K3s to start upgrading nodes.

**About K3s:**
Note: It may make sense to sync with Dave on K3s to briefly demo it.
Resources: K3s args/flags https://rancher.com/docs/k3s/latest/en/installation/install-options/

**UI Rough Concept:**
We will need to tweak what we see when we edit our K3s cluster, I imagine it would look similar and we add a section for showing basic info about the cluster (how/what/where? obtain from k3s master nodes annotation?) it should at least show the current K3s version in the UI and on the edit page. Editing the cluster will allow us to see a drop-down option for upgrading the K3s cluster. K3s backend will need to have an endpoint to query to see if updates are available.

**Comment by deniseschannon** [comment]
@davidnuzik Who is an engineer that UI team could work with if they have questions about the annotations on nodes or getting an imported k3s cluster in a setup to look at it to see how it would be?

**Comment by davidnuzik** [comment]
@deniseschannon @galal-hussein would be a good contact here.

**Comment by westlywright** [comment]
Upgrade controller and annotations currently do not exist on imported k3s clusters.

**Comment by davidnuzik** [comment]
Update: We're going to touch base Monday 2/24 to sync and ensure we're on the same page.
By 2/28 we should be ready for UI to start on this issue.

**Comment by davidnuzik** [comment]
Backend: https://github.com/rancher/rancher/issues/25543

**Comment by westlywright** [comment]
@davidnuzik @cjellick this is available in master (latest2) with the caveate that I dont have the versions api from Darren yet so the version input is just a plain-text input that you'll have to put the correct version into. Also I've been using k3s with a commit, I am not sure that the new changes have been pushed into an actual release yet?

**Comment by davidnuzik** [comment]
Waiting on https://github.com/rancher/rancher/issues/25543 and other backend work. My bad I thought everything was in and this is why it when To Test earlier.

**Comment by sangeethah** [comment]
Tested with latest build from master - 25f16c370

When editing an imported k3 cluster , drain options and Concurrency options from server and worker nodes are presented in the UI.

Able to upgrade the k3 version successfully with these 2 drain options enabled /disabled and by providing different values for "Server Concurrency" and "Worker Concurrency".

Drain option gets set correctly when enabled /disabled. in the k3Config object as expected.

<img width="493" alt="Screen Shot 2020-03-07 at 7 53 10 PM" src="https://user-images.githubusercontent.com/4266958/76156307-7b274000-60ad-11ea-8981-c85e87c6ece3.png">

<img width="998" alt="Screen Shot 2020-03-07 at 7 53 03 PM" src="https://user-images.githubusercontent.com/4266958/76156308-7e223080-60ad-11ea-8da2-e9fe3c7ebdf4.png">
