### ISSUE TITLE
"Error checking upgrade" status for stack.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2540]
Server version - v0.44.0-rc2

I had created a stack with older template version - v0.1.3 of "Route53 DNS" 
I have deleted this service now.

UI  shows "Error checking upgrade" status for stack.

<img width="1346" alt="screen shot 2015-11-03 at 5 58 08 pm" src="https://cloud.githubusercontent.com/assets/4266958/10927494/fa0f329c-8254-11e5-8722-104570d740bd.png">

**Comment by vincent99** [comment]
That message just means the API returned an error when the UI asked for the upgrade info.. in this case probably because we renamed the template
