### ISSUE TITLE
K3s Integration - Node Details

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#25400]
To support the k3s integration in to the ember UI, work needs to be done to show the k3s node details from the annotation which should be a json blob.

**Description:**
K3s will be integrating into Rancher 2.4.0 with at least these minimum requirements for the Rancher UI:

- Import K3s clusters using normal import flow
- View details of nodes revealing the k3s config for each node (planned to be an annotation on each node)

**About K3s:**
Note: It may make sense to sync with Dave on K3s to briefly demo it.
Resources: K3s args/flags https://rancher.com/docs/k3s/latest/en/installation/install-options/

**UI Rough Concept:**
As mentioned above, we plan to create an annotation on each K3s node that will contain it's config. The UI would need to parse the annotation to display in the Rancher UI. Otherwise, we treat mostly as a normal imported cluster in 2.4.0.

**Comment by deniseschannon** [comment]
@davidnuzik Who is an engineer that UI team could work with if they have questions about the annotations on nodes or getting an imported k3s cluster in a setup to look at it to see how it would be?

**Comment by davidnuzik** [comment]
@deniseschannon @galal-hussein would be a good contact here.

**Comment by westlywright** [comment]
@tfiduccia @deniseschannon do we have better requirements about what info should be displayed? Currently I have the following info on imported k3s cluster nodes and because we already display annotations on a node detail page it gets displayed in that section. Do we need to create a new section for this? 

```
    "flannel.alpha.coreos.com/backend-data": "{\"VtepMAC\":\"redacted\"}",
    "flannel.alpha.coreos.com/backend-type": "vxlan",
    "flannel.alpha.coreos.com/kube-subnet-manager": "true",
    "flannel.alpha.coreos.com/public-ip": "redacted",
    "node.alpha.kubernetes.io/ttl": "0",
    "volumes.kubernetes.io/controller-managed-attach-detach": "true"
```

**Comment by tfiduccia** [comment]
@westlywright - @davidnuzik will have to tell you what he wants here.  This is a k3s specific page and I'm not involved with getting requirements.

**Comment by davidnuzik** [comment]
In this case, we'll leave things as they are today. The node config info can be seen by looking at the annotations in the node. This should be sufficient.

**Comment by davidnuzik** [comment]
For this issue, ensure we see these labels: https://github.com/rancher/k3s/blob/master/pkg/agent/run.go#L37-L39
and these annotations:
https://github.com/rancher/k3s/blob/master/pkg/nodeconfig/nodeconfig.go#L16-L18

Might require additional environmental config. If have questions let me know.

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 32f6f659c`
Added labels:
```
	InternalIPLabel = "k3s.io/internal-ip"
	ExternalIPLabel = "k3s.io/external-ip"
	HostnameLabel   = "k3s.io/hostname"
```
Added annotations:
```
	NodeArgsAnnotation       = "k3s.io/node-args"
	NodeEnvAnnotation        = "k3s.io/node-env"
	NodeConfigHashAnnotation = "k3s.io/node-config-hash"
```
These are not found in a k3s imported node:
![Screen Shot 2020-02-27 at 4 56 31 PM](https://user-images.githubusercontent.com/57409052/75497658-2f281d00-5982-11ea-8f5f-c5f84124cc78.png)

**Comment by galal-hussein** [comment]
@aaronRancher what is the version of k3s cluster that you imported to rancher?

**Comment by aaronRancher** [comment]
@galal-hussein `k3s version v1.17.3+k3s1 (5b17a175)`

**Comment by davidnuzik** [comment]
Need more info; assigned to @galal-hussein

**Comment by galal-hussein** [comment]
@davidnuzik `v1.17.3+k3s1` didn't include the node config PR, the feature will be backported to 1.17 release branch

**Comment by davidnuzik** [comment]
Thanks. Will move this out of to-test for now

**Comment by davidnuzik** [comment]
Waiting on RC which Hussein is working on getting out. I tested from master so far and appears to be working in the UI. My node args show up and the start up args as well.

**Comment by aaronRancher** [comment]
The feature is verified with Rancher server `rancher\rancher:master-2411-head` `version 570461823`
k3s version `v1.17.3-alpha1+k3s1`

Steps:
Provision k3s cluster with:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.17.3-alpha1+k3s1 sh -s - server --node-external-ip=<IP>
```

New labels and annotations are seen:
![Screen Shot 2020-03-11 at 9 44 22 AM](https://user-images.githubusercontent.com/57409052/76442487-43a2e700-637e-11ea-90d9-5e2f915695a1.png)
