### ISSUE TITLE
vsphere 6.9 support

### ISSUE THREAD

**Issue by claflico** [rancher/rancher#25404]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

- Try to launch vsphere cluster using "install from boot2docker" as the creation method. 
- Specify 2cpu, 2gb ram, 20gb hdd in template

**Result:**
Vms get created in vsphere but get an error message in vsphere recent task window: "A specified parameter was not correct: deviceChange[1].device.key Cannot add multiple devices using the same device key." Created VMs do not get an HDD or ISO device attached. Deleting the cluster does not delete the VMs.

**Other details that may be helpful:**
Brand new install of Rancher 2.3.5. VMC hosted version of vsphere 6.9.1, hosts show to be esxi 6.9.1. Node templates are basic with very little changed from default.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher 2.3.5
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): VMC Vsphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 2CPU, 2GB ram, 20GB HDD
- Kubernetes version (use `kubectl version`): v1.17.2-rancher1-2

```
2020-02-13 13:58:27.218118 W | etcdserver: read-only range request "key:\"/registry/services/endpoints/kube-system/kube-controller-manager\" " with result "range_response_count:1 size:557" took too long (603.883094ms) to execute
2020/02/13 13:58:28 [INFO] [node-controller-rancher-machine] (dc1-dev-etcd1) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2020/02/13 13:58:28 [INFO] [node-controller-rancher-machine] (dc1-dev-etcd1) Finding datastore /SDDC-Datacenter/datastore/WorkloadDatastore
2020/02/13 13:58:28 [INFO] [node-controller-rancher-machine] (dc1-dev-etcd2) Uploading Boot2docker ISO ...
2020/02/13 13:58:30 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2020/02/13 13:58:30 [INFO] [node-controller-rancher-machine]
2020/02/13 13:58:30 [INFO] [node-controller-rancher-machine] (dc1-dev-etcd1) Uploading Boot2docker ISO ...
2020/02/13 13:58:30 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2020/02/13 13:58:30 [INFO] [node-controller-rancher-machine]
2020/02/13 13:58:31 [INFO] Generating and uploading node config dc1-dev-wrkr1
2020/02/13 13:58:31 [ERROR] NodeController c-98zbd/m-cm78h [node-controller] failed with : Error creating machine: Error in driver during machine creation: A specified parameter was not correct: deviceChange[1].device.key
2020/02/13 13:58:31 [INFO] [node-controller-rancher-machine] (dc1-dev-wrkr2) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2020/02/13 13:58:31 [INFO] [node-controller-rancher-machine] (dc1-dev-ctlpln3) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2020/02/13 13:58:31 [INFO] [node-controller-rancher-machine] (dc1-dev-wrkr3) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2020/02/13 13:58:31 [INFO] Generating and uploading node config dc1-dev-etcd3
2020/02/13 13:58:32 [INFO] [node-controller-rancher-machine] (dc1-dev-wrkr2) Finding datastore /SDDC-Datacenter/datastore/WorkloadDatastore
2020/02/13 13:58:32 [INFO] [node-controller-rancher-machine] (dc1-dev-ctlpln3) Finding datastore /SDDC-Datacenter/datastore/WorkloadDatastore
2020/02/13 13:58:32 [INFO] [node-controller-rancher-machine] (dc1-dev-wrkr3) Finding datastore /SDDC-Datacenter/datastore/WorkloadDatastore
2020/02/13 13:58:32 [ERROR] NodeController c-98zbd/m-hvhwb [node-controller] failed with : Error creating machine: Error in driver during machine creation: A specified parameter was not correct: deviceChange[1].device.key
2020/02/13 13:58:32 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2020/02/13 13:58:32 [INFO] [node-controller-rancher-machine]
2020/02/13 13:58:34 [INFO] Generating and uploading node config dc1-dev-ctlpln1
2020/02/13 13:58:34 [ERROR] NodeController c-98zbd/m-qvm7z [node-controller] failed with : Error creating machine: Error in driver during machine creation: A specified parameter was not correct: deviceChange[1].device.key
2020/02/13 13:58:34 [INFO] [node-controller-rancher-machine] (dc1-dev-wrkr3) Uploading Boot2docker ISO ...
2020/02/13 13:58:35 [INFO] [node-controller-rancher-machine] (dc1-dev-wrkr2) Uploading Boot2docker ISO ...
2020/02/13 13:58:35 [INFO] [node-controller-rancher-machine] (dc1-dev-ctlpln3) Uploading Boot2docker ISO ...
2020/02/13 13:58:37 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2020/02/13 13:58:37 [INFO] [node-controller-rancher-machine]
2020/02/13 13:58:37 [INFO] Generating and uploading node config dc1-dev-etcd2
2020/02/13 13:58:37 [ERROR] NodeController c-98zbd/m-4bs6h [node-controller] failed with : Error creating machine: Error in driver during machine creation: A specified parameter was not correct: deviceChange[1].device.key
2020/02/13 13:58:38 [INFO] [node-controller-rancher-machine] (dc1-dev-ctlpln2) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2020/02/13 13:58:38 [INFO] [node-controller-rancher-machine] (dc1-dev-ctlpln2) Finding datastore /SDDC-Datacenter/datastore/WorkloadDatastore
2020/02/13 13:58:40 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2020/02/13 13:58:40 [INFO] [node-controller-rancher-machine]
2020/02/13 13:58:41 [INFO] Generating and uploading node config dc1-dev-etcd1
2020/02/13 13:58:41 [ERROR] NodeController c-98zbd/m-f76p2 [node-controller] failed with : Error creating machine: Error in driver during machine creation: A specified parameter was not correct: deviceChange[1].device.key
2020/02/13 13:58:41 [INFO] Creating jail for c-98zbd
2020/02/13 13:58:41 [INFO] Generating and uploading node config
2020/02/13 13:58:42 http: TLS handshake error from 127.0.0.1:51544: EOF
2020/02/13 13:58:42 [INFO] [node-controller-rancher-machine] (dc1-dev-ctlpln2) Uploading Boot2docker ISO ...
2020/02/13 13:58:43 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2020/02/13 13:58:43 [INFO] [node-controller-rancher-machine]
2020/02/13 13:58:43 [INFO] Generating and uploading node config dc1-dev-wrkr3
2020/02/13 13:58:43 [ERROR] NodeController c-98zbd/m-rjlkk [node-controller] failed with : Error creating machine: Error in driver during machine creation: A specified parameter was not correct: deviceChange[1].device.key
2020/02/13 13:58:43 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2020/02/13 13:58:43 [INFO] [node-controller-rancher-machine]
2020/02/13 13:58:44 [INFO] Generating and uploading node config dc1-dev-wrkr2
2020/02/13 13:58:44 [ERROR] NodeController c-98zbd/m-4qb8m [node-controller] failed with : Error creating machine: Error in driver during machine creation: A specified parameter was not correct: deviceChange[1].device.key
2020/02/13 13:58:44 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2020/02/13 13:58:45 [INFO] [node-controller-rancher-machine]
2020/02/13 13:58:45 [INFO] Generating and uploading node config dc1-dev-ctlpln3
2020/02/13 13:58:45 [ERROR] NodeController c-98zbd/m-dhl7w [node-controller] failed with : Error creating machine: Error in driver during machine creation: A specified parameter was not correct: deviceChange[1].device.key
2020/02/13 13:58:51 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2020/02/13 13:58:51 [INFO] [node-controller-rancher-machine]
2020/02/13 13:58:52 [INFO] Generating and uploading node config dc1-dev-ctlpln2
```

**Comment by claflico** [comment]
Changing the vsphere node template to "Deploy from template: DataCenter" results in a VM being created and booting (didn't fully test provisioning because we don't have docker template created yet". Deleting the cluster did NOT delete the running VM.

**Comment by mchineboy** [comment]
Issue persists on 2.4.3.

**Comment by lynic** [comment]
Same issues saw in vsphere 7.0, any plan to fix it?

I'm using rancheros.iso 1.5.6 to setup k8s on vsphere 7.0

 Reconfigure virtual machine
Status:
A specified parameter was not correct: deviceChange[1].device.key
Initiator: VSPHERE.LOCAL\Administrator
Target:
kube-vpn-node1
Server: vcsa
Error stack:
Cannot add multiple devices using the same device key..

**Comment by DH-Rancher** [comment]
@claflico - Can you confirm if this is ESXi 6.7 or 7, please? 6.9 doesn't seem to be an official release

**Comment by claflico** [comment]
@DH-Rancher It's a hosted instance of vcenter, they call it VMC. When I go to vcenter summary the Version Information shows:

Version 6.9.1
Build 14621801

When I go to the "About VMware vSphere" it says "vSphere Client version 6.9.1.10000"

**Comment by lynic** [comment]
It's a beta version of vsphere 7.0, so let's take it as vsphere 7.0 .

> @DH-Rancher It's a hosted instance of vcenter, they call it VMC. When I go to vcenter summary the Version Information shows:
> 
> Version 6.9.1
> Build 14621801
> 
> When I go to the "About VMware vSphere" it says "vSphere Client version 6.9.1.10000"

**Comment by carterminearIMT** [comment]
I am also getting this error on vsphere 7.0

**Comment by agepi477** [comment]
Same issue here.

**Versions:**
* Rancher v2.4.5
* VMware vCenter 7 
* VMware ESXi 6.7 (Build 16316930)

vSphere creates the VM and finally fails to add NIC and CDROM to the VM. Instead it posts error message:

A specified parameter was not correct: deviceChange[1].device.key

**Comment by Galphaa** [comment]
Same issue here 



-  Rancher v2.4.6

- VMware vCenter 7

- VMware ESXi  7.0.0 15843807

**Comment by Hitman247m** [comment]
> I'm having the issue as well.
> 
> **Versions:**
> 
> * Tried with Rancher 2.4.5 and 2.4.6-rc9
> * VMware vCenter 7.0.0 (Build 16620013)
> * VMware ESXi, 7.0.0 (Build 16324942)
> 
> **vCenter Tasks:**
> 
> 1. Create virtual machine --> Success
> 2. Reconfigure virtual machine --> Failed
> 
> ```
> Reconfigure virtual machine
> Details: Executing prechecks
> Status: A specified parameter was not correct: deviceChange[1].device.key
> Error Stack: Cannot add multiple devices using the same device key..
> ```
> 
> After that, it keeps trying to create those same VMs again, while complaining that the name is already in-use.

Just to add-on to this, I've now tested with the following and the issue persists:

- Rancher 2.4.8
- VMware vCenter 7.0.0 (Build 16749670)
- VMware ESXi, 7.0.0 (Build 16324942)

**Comment by robotica72** [comment]
Not sure its helpful, but Ill add to this thread - Same issue here with Newest Rancher and vSphere 7.0.

**Comment by SimonyanG** [comment]
Any news on this ?

**Comment by Hitman247m** [comment]
As of the latest RC, it's still broken for me. Guess I'll stick with Kubespray.

**Comment by starkca90** [comment]
Add me to the list:

- Rancher: v2.5.1
- vCenter: 7.0.1 (Build 16858589)
- ESXi: 7.0.1, 16850804

**Comment by AkideLiu** [comment]
Confirm not working as same as above 

Rancher: v2.5.1
vCenter: 7.0.1 (Build 16858589)
ESXi: 7.0.1, 16850804

**Comment by DH-Rancher** [comment]
We're working on it, but unfortunately we cannot share an ETA at this time

As a workaround (admittedly, not ideal:)

Try to configure your template to mimic the desired end configuration state in terms of attached port groups. Currently, I can get it to work cloning a VM template with the desired port group already attached.

**Comment by bmdepesa** [comment]
v2.4-head, v2.5-head, master-head tested in this issue: https://github.com/rancher/rancher/issues/29519#issuecomment-712872322

**Comment by aledr** [comment]
Tested on 2.5.2 with vApp properties and It fails to add IP address.
