### ISSUE TITLE
Failed to install app

### ISSUE THREAD

**Issue by excme** [rancher/rancher#25417]
`Failed to install app postgres-operator. Error: unable to convert to CRD type: unable to convert unstructured object to apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition: cannot convert int64 to float64`
Git Url in Catalog - https://github.com/zalando/postgres-operator.git

Maybe Version incompatibility of helm?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.5` UI: `v2.3.36` Helm `v2.14.3-rancher1` |
|Route|`apps-tab.detail`|

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/25036
