### ISSUE TITLE
[UI] warn users when that non-dynamic features require rancher to be restarted

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#25421]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Explanation:**
Features will now either be dynamic or non-dynamic. If a feature is non-dynamic then it requires rancher to be restarted and will cause rancher to turn off when they are toggled.

**Desired:**
Warn users about this behavior.

**Notes:**
The schema now uses spec and status, where spec contains value and status contains default and dynamic fields. The ui seems to magically be handling this already but worth looking at.

**Backend Issue:**
https://github.com/rancher/rancher/issues/25213

**Comment by rmweir** [comment]
**Design suggestions:**
@ibuildthecloud : there should be a modal that warns the user that upon toggling the value the server will restart and be unavailable. If the user select okay, then the dialog should show a sleep while pinging the server until it's alive again, then closes the modal and refreshes.

**Comment by codyrancher** [comment]
@deniseschannon is this supposed to go in ember or vue? I noticed screenshots of vue in the backend issue.

**Comment by deniseschannon** [comment]
This should be in ember when you enable dynamic features.

@rmweir Is there a way to know which is a dynamic feature or not? 

<img width="1163" alt="Screen Shot 2020-03-04 at 2 40 40 PM" src="https://user-images.githubusercontent.com/11410997/75929778-2756f580-5e26-11ea-9714-fc8390200d15.png">

**Comment by rmweir** [comment]
@deniseschannon yes, there is a "dynamic" field under status

**Comment by rmweir** [comment]
@codyrancher the vue screenshots were from validating if the feature flag worked since it gates rio. This is just regular rancher's feature ui.

**Comment by sowmyav27** [comment]
**Verified on latest master - ui Tag: latest2**

- Go to Global --> Settings --> Feature Flags 
- Warning is displayed - `Feature flags allow Rancher to gate certain features behind flags. You should enable these features with caution, and they should be considered beta functionality, which could cause problems for your system. Additionally, some features require a restart of the Rancher server to be enabled.`

<img width="1081" alt="Screen Shot 2020-03-13 at 2 44 31 PM" src="https://user-images.githubusercontent.com/26032343/76661645-34b46400-6539-11ea-8722-f34bf2462620.png">
