### ISSUE TITLE
2.4 SAML UI error when clicking on SAML auth providers in the UI

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25426]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Install Rancher 2.4 master-head commit id: ad9c71186
Navigate with Security -> Authentication and navigate through the different SAML providers. You get an error

**Result:**

Cannot read property 'rancherApiHost' of undefined.

<img width="750" alt="Screen Shot 2020-02-14 at 1 29 07 PM" src="https://user-images.githubusercontent.com/27659/74565598-ca56d680-4f2e-11ea-9bb5-297fb28727a1.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version: 2.4 master-head commit id: ad9c71186
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (02/15/2020)` commit id: 580ab5bb4

I validated this error is no longer happening in the UI, I was able to navigate through all the auth providers not only SAML.

I've used latest Firefox and Chrome in OS X.
