### ISSUE TITLE
rancher reinstall with new domain name,but import cluster script is old one

### ISSUE THREAD

**Issue by 4admin2root** [rancher/rancher#25434]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1.helm uninstall rancher -n cattle-system
2.helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=rancher.new.com \
  --set ingress.tls.source=secret
3. menu: globao->add cluster->add an existing cluster
```
curl --insecure -sfL https://rancher.old.com/v3/import/ps9knz89vjw2vjz7f7gbrj9cpvl455gvkksltmxthbj5w56zwstvx2.yaml | kubectl apply -f -
```

**Result:**
the domain name is old one

**Other details that may be helpful:**
nothing

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.3.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):vm 
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```

$ docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:26:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:28:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by jonashartwig** [comment]
Hi, I just wanted to report something familiar. Might be related:
we also made a HA installation of rancher setting hostname flag in Helm (version 3.0.3) to loadbalancer.company.com. Afterwards we got a DNS entry and made helm upgrade with hostname: dnsentry.company.com.

Afterwards we got this behaviour in the kubectl shell launched form the web:

```bash
# Run kubectl commands inside here
# e.g. kubectl get all
> kubectl get nodes
error: the server doesn't have a resource type "nodes"
> kubectl get pods
error: the server doesn't have a resource type "pods"
> cat .kube/config 
apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    server: "https://loadbalancer.company.com/k8s/clusters/local"
    certificate-authority: /nonexistent/.kube/certs/ca.crt
  name: "Default"
contexts:
- context:
    cluster: "Default"
    user: "Default"
  name: "Default"
current-context: "Default"
users:
- name: "Default"
  user:
    token: "kubectl-shell-user-94kjw:wtnkgm7bvdlr6txms2hvvgl4plv9bkjjmlkqthz2rnh597j8b7m7gh"
> vi .kube/config # set server to dnsentry.company.com
> kubectl get pods
No resources found in default namespace.
> kubectl get nodes
NAME                                  STATUS   ROLES                      AGE     VERSION
ra001-k8s-cdl-d.ddc.teliasonera.net   Ready    controlplane,etcd,worker   4h49m   v1.17.2
ra002-k8s-cdl-d.ddc.teliasonera.net   Ready    controlplane,etcd,worker   4h49m   v1.17.2
ra003-k8s-cdl-d.ddc.teliasonera.net   Ready    controlplane,etcd,worker   4h49m   v1.17.2
```
Manually updating the kube/config file solved that problem. Resolution right now: re-install rancher. However according to above that might not work either.
rancher: 2.2.5, docker 19.03.5.

regards

**Comment by 4admin2root** [comment]
And the ENV CATTLE_SERVER is old one in cattle-cluster-agent and  cattle-node-agent

**Comment by 4admin2root** [comment]
fixed by following this :
https://docs.rancher.cn/rancher2x/admin-manual/replace-ip-domain.html#_1-%E5%87%86%E5%A4%87%E6%89%80%E6%9C%89%E9%9B%86%E7%BE%A4%E7%9A%84%E7%9B%B4%E8%BF%9Ekubeconfig%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
