### ISSUE TITLE
v2.3.5 - Glusterfs removed from UI

### ISSUE THREAD

**Issue by ainiml** [rancher/rancher#25442]
Glusterfs is no longer listed as a Storage Class or Persistent Volume

**What kind of request is this (question/bug/enhancement/feature request):**
regression
 

**Result:**
![image](https://user-images.githubusercontent.com/28725423/74633729-49672d00-5130-11ea-897c-282ed534ef43.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

Rancher | v2.3.5
-- | --
User Interface | v2.3.36
Helm | v2.14.3-rancher1
Machine | v0.15.0-rancher29

- Installation option (single install/HA):

single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
 

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.12
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by sowmyav27** [comment]
@ainiml  This flag - `unsupported-storage-drivers` in the cluster level is set to `false`in rancher:v2.3.x , which Hides 'unsupported' storage providers and provisioners.

For the upsupported list of storage providers to be available, `unsupported-storage-drivers` should be set to true.

More info: https://github.com/rancher/rancher/issues/22895

**Comment by ainiml** [comment]
> @ainiml This flag - `unsupported-storage-drivers` in the cluster level is set to `false`in rancher:v2.3.x , which Hides 'unsupported' storage providers and provisioners.
> 
> For the upsupported list of storage providers to be available, `unsupported-storage-drivers` should be set to true.
> 
> More info: #22895

Thanks

This was impossible to find in the docs related to Glusterfs

I also wonder why the UI toggle wasn't made before merging the PR to hide them all
