### ISSUE TITLE
new rancher server has no kubernetes versions for install until metadata is refreshed

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#25444]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. install Rancher into RKE
2. immediately try to deploy a new custom cluster

**Result:**

- the kubernetes versions dropdown is empty

**Other details that may be helpful:**

- if i manually refresh the metadata, the dropdown is populated. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

v2.3.5 / HA

**Comment by superseb** [comment]
This is the same as https://github.com/rancher/rancher/issues/24091

**Comment by oskapt** [comment]
whoops! i searched through issues but didn't look back into the previous decade.. 😛
