### ISSUE TITLE
[cli] RFE: rancher cli should allow command-line or environment-variable access token settings

### ISSUE THREAD

**Issue by Rancheroo** [rancher/rancher#25441]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
The rancher 1.x CLI used the --url, --access-key, and --secret-key (along with corresponding environment variables) to direct the CLI to communicate with a particular API endpoint.

The rancher 2.x CLI appears to have dropped this model in favor of a $HOME/.rancher/cli2.json file that must be present, and cannot even be overridden by a command line option.

When creating CI/CD pipelines and other types of automation that require communication with the Rancher CLI (e.g. to create a Namespace in a particular Project, or to deploy a Rancher Chart, or to run kubectl commands using Rancher access tokens instead of a Kubeconfig file), it is important that the authentication tokens and API information be stored in a consistent and secure location.

**Result:**
Please restore the ability to specify the API URL, auth token, cluster, and project (e.g. the entirety of the context) as command-line options and environment variables. This would make incorporating the rancher CLI utility into automated processes much easier.

**Other details that may be helpful:**
The Rancher 1.6 CLI utility allowed you to provide the RANCHER_URL, RANCHER_SECRET_KEY and RANCHER_ACCESS_KEY environment variables, making it well suited for automation in, say, Jenkins. But since the rancher 2.x CLI insists on doing an interactive login process to create a cli2.json file, there's no straightforward way to inject a rancher CLI command into a Jenkins pipeline without resorting to hacks like manually creating the cli2.json file as part of the pipeline, and then mangling $HOME to trick the CLI into reading it.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

gz#8402

**Comment by laurie-kepford** [comment]
So this was asked a year ago with no response.  I have a similar issue.
I would at lease like the ability to keep multiple cli.json files.  ie. cli2-prod.json and cli2-test.json and pass in my command which file to use:  ie. `rancher --config /path/cli2-prod.json get namespaces`.  This was possible in rancher 1.6.
