### ISSUE TITLE
Unable to create Amazon Credentials

### ISSUE THREAD

**Issue by ms-dennis** [rancher/rancher#25448]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Open Cloud Credentials (https://rancher.ops.ps.m953.net/g/security/cloud-credentials)
* Try to add a new Amazon Credential
* Fill out any required filed

![image](https://user-images.githubusercontent.com/57993182/74738609-90037700-5257-11ea-98cd-e011982f308b.png)

**Result:**
Validation failed in API: a Config field must be set is required

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
* 2.3.5
- Installation option (single install/HA):
HA

**Comment by ms-dennis** [comment]
I found the problem.
This error message is kinda misleading. Please update it.

Problem was, that i disabled any Node Drivers but vsphere Drivers.
Re-enabling the Amazon EC2 Driver solved the problem.

**Comment by DawnBreather** [comment]
Faced same issue on a branch new installation of Rancher v2.5 (v2.5-07131035f51f3e264c114e9d9dde65aae37bdf4f-linux-arm64).
Guys, any ideas what can be wrong ?

**Comment by DawnBreather** [comment]
> Faced same issue on a branch new installation of Rancher v2.5 (v2.5-07131035f51f3e264c114e9d9dde65aae37bdf4f-linux-arm64).
> Guys, any ideas what can be wrong ?

Identified the issue:
As you may see i am using ARM version, but seems like some drivers are not working there. So, please beware of ARM architecture for rancher setup.
