### ISSUE TITLE
Shibboleth auth UI Rancher API Host field is disabled and certs textboxes missing when trying to configure it.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25449]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

- Install Rancher 2.4 
- Navigate to Security -> Authentication -> Shibboleth

**Result:**
The UI is displayed to the user but the Rancher API host field is disabled. 
<img width="1561" alt="Screen Shot 2020-02-18 at 9 53 13 AM" src="https://user-images.githubusercontent.com/27659/74758461-9af8e000-5234-11ea-9e6b-2c26d5e46c87.png">

It seems that the Certificates IDs textboxes are also missing, because clicking Authenticate with Shibboleth those fields are required but are not visible:

<img width="742" alt="Screen Shot 2020-02-18 at 10 01 30 AM" src="https://user-images.githubusercontent.com/27659/74759214-abf62100-5235-11ea-9ee0-690b9956306c.png">

**Other details that may be helpful:**

This was previously working before this other issue was fixed: https://github.com/rancher/rancher/issues/25426

**Environment information**
- Rancher version: `2.4 master-head (02/18/2020)` commit id: 580ab5bb4
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
Available in `latest2`

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (02/18/2020)` commit id: 580ab5bb4

I'm able to configure Shibboleth auth now (with and without OpenLDAP), the fields are visible and editable in the UI. Also navigating to other SAML auth providers didn't reproduce #25426 either.
