### ISSUE TITLE
[feature] More comparison options in UI schedule definition

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2545]
When defining scheduler rules in the UI, you can currently only specify TAG=VALUE (though this can be negated).

It would be useful to also be able to specify such rules as --

-- TAG exists
-- TAG < VALUE (for numeric tag values)
-- TAG > VALUE (for numeric tag values)

As an example use case, we have 2 hosts that hold load balancer instances.  Load balancers are started with 'global' and 'require LB=1'.  When starting services, we use 'prefer LB=0' but this means we need to have the LB=0 tag on all worker hosts.  It would be better to be able to say 'prefer !exists LB'

If you're really feeling adventurous, it might even be possible to use a function to define preference weighting using numerical tags...

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
