### ISSUE TITLE
The Shibboleth OpenLDAP search config schema fields are not pre-filled with default values

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25458]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Install Rancher 2.4 commit id used: 580ab5bb4
- Navigate to Security -> Authentication -> Shibboleth
- Then expanding the **-2 OpenLDAP Search Configuration** section, there are a few Users and Groups schema fields that can be set as needed, these values are usually pre-filled in other LDAP auth providers (OpenLDAP, FreeIPA)

**Result:**

The OpenLDAP schema fields in the Shibboleth auth config are note pre-filled con sample values. Here is a sample screenshot on a new Rancher 2.4 installation:

<img width="1256" alt="Screen Shot 2020-02-18 at 2 20 01 PM" src="https://user-images.githubusercontent.com/27659/74779243-54b67780-525a-11ea-9c7c-cccc2cea8fe5.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version: `2.4 master-head (02/18/2020)` commit id: 580ab5bb4
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
I believe this was addressed in rancher/ui#3757

**Comment by izaac** [comment]
I was able to see the fields pre-filled now.

I'm no longer able to reproduce with newer Rancher 2.4 build 2.4 master-head (02/19/2020) commit id: e11d478
