### ISSUE TITLE
Shibboleth user and groups self link are returning 500 in v3/principals

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25466]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Enable Shibboleth with OpenLDAP search

- self link for user and group in v3/principals returning 500 *No identities can be retrieved *
 
**Result:**

```json
{

    "baseType": "error",
    "code": "ServerError",
    "message": "No identities can be retrieved",
    "status": 500,
    "type": "error"

}
```

**Other details that may be helpful:**

**Environment information**
- Rancher version: `2.4 master-head (02/18/2020)` commit id: 580ab5bb4
- Installation option (single install/HA): single

**Comment by sangeethah** [comment]
The call to groups link is also done when clicking on "Edit Cluster" from UI.

![imageedit__4061766606](https://user-images.githubusercontent.com/4266958/74802196-f4412d80-528d-11ea-8cef-170d012e773f.png)

**Comment by izaac** [comment]
I'm no longer able to reproduce after a second check on the OpenLDAP settings and a newer Rancher 2.4 build 2.4 master-head (02/19/2020) commit id: e11d478

I was able to click in the self-links and get the proper response in the v3/principals.
