### ISSUE TITLE
Istio traffic routing tabs disappeared from UI in master

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#25462]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Enable Istio in Rancher master
2. Navigate to Resources > Istio

**Result:**
There should be 5 tabs across the top of that page. It SHOULD look like:
![image](https://user-images.githubusercontent.com/55997940/74782966-ce059880-5261-11ea-82b1-2eea80be6217.png)

But what we actually see is:
![image](https://user-images.githubusercontent.com/55997940/74783128-3eacb500-5262-11ea-9b67-2e6b23e3c8e1.png)

In master, I do not see "Gateways", "Destination Rules", or "Virtual Services"

**Other details that may be helpful:**
First screenshot above is the correct view from Rancher v2.3.5. Changing ui-index in Rancher v2.3.5 to be the same as master (https://releases.rancher.com/ui/latest2/index.html) does NOT reproduce this issue.

**Environment information**
Single node install, master Rancher version `580ab5bb4`

**Cluster information**
3 nodes, all roles, 8gb 4vcpu each. Hosted on Linode.
 Kubernetes Version: v1.17.2

**Comment by rancher-max** [comment]
**Interesting to note: using the URLs directly takes me to the appropriate pages:**
https://${RANCHER_SERVER_URL}/p/${CLUSTER:PROJECT IDs}/istio/project-istio/gateways
https://${RANCHER_SERVER_URL}/p/${CLUSTER:PROJECT IDs}/istio/project-istio/destination-rules
https://${RANCHER_SERVER_URL}/p/${CLUSTER:PROJECT IDs}/istio/project-istio/virtual-services

**Comment by codyrancher** [comment]
The display of those tabs are now behind a feature flag
<img width="1272" alt="Screen Shot 2020-02-20 at 8 17 45 AM" src="https://user-images.githubusercontent.com/55104481/74948567-b7725500-53b9-11ea-95f1-e539d913b59e.png">

The code was committed in october https://github.com/rancher/ui/commit/5562d5f65d12ee2c65b944bc34ea5b3109179410

I don't think this is in error.

**Comment by rancher-max** [comment]
Enabling that feature flag does resolve this issue. Has this specific flag been changed in master to be disabled by default now? I see it disabled even on current master (`Rancher version e11d47814`), but it is enabled by default using `v2.3.6-rc1`. I think proper behavior this one is to be enabled by default.

**Comment by codyrancher** [comment]
I don't really have an opinion on whether or not it should be enabled by default. If we want to change the default value this is going to be a backend change. The front end only checks to see if the feature is enabled, it doesn't set the default.

@maggieliu if we want to change the default the backend should change it.

**Comment by davidnuzik** [comment]
If we need the flag enabled to show the UI tabs correctly then I think we should just enable the flag by default. It doesn't make sense to me to keep it disabled unless there is a very very good reason and the UI can help the user enable it themselves (would need a use case as to not enable it by default)

**Comment by rmweir** [comment]
investigating rn, as the default should be true

**Comment by rancher-max** [comment]
#### Validated on `Rancher version dad58367e (dad58367e)`

Left ui-index and system-charts as the defaults.

The routing tabs are back! The feature flags now have the correct default values (True for `istio-virtual-service-ui` and False for `steve` and `unsupported-storage-drivers`. None are null anymore). 

**Feature defaults:**
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/55997940/75057815-0b9f3700-5497-11ea-8cf4-7332b11f32d9.png">

**Istio traffic routing screens:**
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/55997940/75057833-18238f80-5497-11ea-9808-6d4b0c6880d0.png">
