### ISSUE TITLE
Ability to allow TTL for the record set created by "Route 53" to be configurable. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2546]

**Comment by sangeethah** [comment]
Currently TTL for the record sets created by "Route 53" service is set to 300 seconds by default which means it could take up to 5 minutes for the changes done to the record set to get propagated to the client.
We should allow for  TTL for the record set created by "Route 53" to be configurable

**Comment by alena1108** [comment]
Rancher-catalog is updated with the new version of the template allowing to specify custom TTL

**Comment by sangeethah** [comment]
Tested with v0.1.6 version of "Route53 DNS" catalog.

We have the ability to set  TTL value when creating this service. This is used to program Route53 record set entries.
