### ISSUE TITLE
Shibboleth - users of nested group added to cluster as owner are not given access to cluster

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25471]
What kind of request is this (question/bug/enhancement/feature request):
Bug

Steps to reproduce (least amount of steps as possible):

`testuser1` is part of `group3`
`testuser6` is part of `group2` (which is nested under group3)

<img width="329" alt="Screen Shot 2020-02-18 at 5 53 29 PM" src="https://user-images.githubusercontent.com/27659/74792216-03b67b80-527a-11ea-81a3-678eee7929c8.png">

- Enable Shibboleth with OpenLDAP
- Search for the `group3` and add it as a Cluster Owner
- Then logout and login as `testuser6`.

Result:

The cluster is not listed.

Other details that may be helpful:

Environment information

Rancher version: 2.4 master-head (02/18/2020) commit id: 580ab5b
Installation option (single install/HA): single

**Comment by cjellick** [comment]
Do you have shibboleth configured to return nested group memberships as part of the saml assertions. If not (and I’d bet that you don’t) then this is behaving as expected.

Rancher will only reflect the group memberships that the saml provider presents in the assertions. The source of truth is saml. It is not in Rancher’s scope to make any inferences from those assertions, such as walking nested group structures. (Yes this is different from ldap auth providers like AD or OpenLdap, but that is intentional).

**Comment by izaac** [comment]
@cjellick no I don't think I have the Shibboleth instance I'm using for testing with that configuration. But in Shibboleth's OpenLDAP Search Configuration in Rancher what's the purpose of these options then?

<img width="354" alt="Screen Shot 2020-02-19 at 9 33 43 AM" src="https://user-images.githubusercontent.com/27659/74853498-3e142d00-52fb-11ea-977c-059d5d758678.png">

**Comment by izaac** [comment]
This is the data coming from a user in a nested group who belongs to the direct `group2` which is as member (child) of `group3`.

```json
data": [ 2 items

    {
        "baseType": "principal",
        "created": null,
        "creatorId": null,
        "id": "shibboleth_user://testuser6",
        "links": {
            "self": "…/v3/principals/shibboleth_user:%2F%2Ftestuser6"
        },
        "loginName": "testuser6",
        "me": true,
        "memberOf": false,
        "name": "testuser6",
        "principalType": "user",
        "provider": "shibboleth",
        "type": "principal"
    },
    {
        "baseType": "principal",
        "created": null,
        "creatorId": null,
        "id": "shibboleth_group://cn=group2,cn=group3,ou=groups,dc=example,dc=org",
        "links": {
            "self": "…/v3/principals/shibboleth_group:%2F%2Fcn=group2%2Ccn=group3%2Cou=groups%2Cdc=example%2Cdc=org"
        },
        "me": false,
        "memberOf": true,
        "name": "cn=group2,cn=group3,ou=groups,dc=example,dc=org",
        "principalType": "group",
        "provider": "shibboleth",
        "type": "principal"
    }

]
```

**Comment by luthermonson** [comment]
@deniseschannon @maggieliu the source of truth is SAML and we'll never get back anything more than strings for groups from an assertion and we shouldn't know the nested structure. Craig thinks  we should talk about getting rid of the radios and we should not get nested groups working.

**Comment by deniseschannon** [comment]
I agree that SAML is the source of truth so let's remove the nested group membership from the UI.

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/03/2020)` commit id: c921ba250

I validated these radio buttons are not in the UI anymore. I was able to enable both Shibboleth only and Shibboleth+OpenLDAP

**Comment by izaac** [comment]
Search for groups, adding and removing users and groups worked as expected after enabling.
