### ISSUE TITLE
Rancher K8s Auth Proxy does not utilize forward proxy (if defined) to proxy communication

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#25488]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
Spin up Rancher HA in semi-airgapped environment (with HTTP/HTTPS forward proxies and no ability for Rancher to directly access the internet without utilizing these forward proxies)
Attempt to provision a ClusterDriver cluster (GKE, EKS, AKS for example)
Observe that while the cluster is in fact able to provision (kontainer-engine is able to use the proxies when provisioning as they are passed in via environment variables), the `cattle-node-agent` and `cattle-cluster-agent` are unable to deploy into the cluster and the cluster never finishes provisioning. Eventually you will see an error message similar to: 
```
unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request unable to recognize "management-statefile_path_redacted": the server is currently unable to handle the request
``` 

in the Rancher UI for this cluster.

**Result:**
Rancher is unable to communicate with the underlying cluster when it attempts to deploy its agents to the cluster, because the K8s auth proxy does not forward traffic properly through a defined forward proxy for clusters that are cluster driver clusters.

Tracing this down, it is seen that these agents are deployed using the clusterdeploy controller here: https://github.com/rancher/rancher/blob/v2.3.5/pkg/controllers/management/clusterdeploy/clusterdeploy.go#L212 

When looking at the `kubectl` package, it can be seen that the kube config context that is passed to the `kubectl` command contains the server as `https://localhost:443/k8s/clusters/<cluster-id>/`, which means it will proxy through the K8s authentication proxy. Due to the fact that the authentication proxy is not properly utilizing the underlying proxy (and this is a cluster driver cluster which does not utilize the underlying agent tunnels for communication), this breaks down and the agents are never properly deployed.

**Other details that may be helpful:**

This is being caused due to the fact that the K8s auth proxy does not utilize a proxy in its HTTPTransport.

Conventionally you would have a line to specify something similar to:
```
transport.Proxy = http.ProxyFromEnvironment
```
here: https://github.com/rancher/rancher/blob/v2.3.5/pkg/clusterrouter/proxy/proxy_server.go#L169

Note that this is not the full solution to this, as the `ClusterDialer` may not actually need to utilize a proxy when talking to RKE/Imported clusters, but will attempt to do. 

Even if the `transport.Proxy` is put into place, the Norman-powered user controllers are still unable to start, with errors similar to:
```
E0219 22:22:06.992485       6 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:193: Failed to list *v1.Event: Get https://<GKE-MASTER-IP>/api/v1/events?limit=500&resourceVersion=0&timeout=30s: Service Unavailable
E0219 22:22:07.014356       6 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:193: Failed to list *v1.Node: Get https://<GKE-MASTER-IP>/api/v1/nodes?limit=500&resourceVersion=0&timeout=30s: Service Unavailable
```

gzrancher/rancher#10911

**Comment by Oats87** [comment]
This issue is similar to: https://github.com/rancher/rancher/issues/22006 (in fact this issue solves half the problem, which is the clusterdriver comparison). It does not completely solve the issue because of the auth proxy issue

**Comment by kinarashah** [comment]
Even if proxy passed in transport and cluster comes up active, kubectl access and view logs from UI don't work and exit with closed code because they don't utilize proxy.

**Comment by bmdepesa** [comment]
Reproduced in v2.3.8, v2.4.5

* Semi-airgapped environment with proxy for outbound connections
* Provision a GKE clsuter, the nodes are provisioned but the agents are never deployed

**Comment by kinarashah** [comment]
we should also confirm this doesn't affect normal (no proxy) setups and normal setup with proxy. Also if we can test this fix out for a custom cluster, that'd give us an idea of what could break in RKE clusters.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.9-rc2

* Deploy Rancher in a semi-airgapped environment, with a proxy
  * Rancher installed a node with no public IP / direct access to the internet
  * Internet-facing load balancer points to Rancher so it is externally accessible
  * Docker settings and Rancher both use proxy
  * No private registry
* Create a GKE cluster
* Cluster provisions
* Cluster and node agents deploy on GKE cluster
* Cluster is active and accessible
* View logs, exec shell, kubectl all function
--
* Regression tested:
  * Deploy custom cluster in same environment as above, in the same EC2 network
  * Deploy custom cluster in same environment as above, from DO nodes
  * Normal non-airgapped/proxy single node Rancher cluster provisioning succeeds through automation
  * Normal non-airgapped/proxy HA Rancher install succeeds in provisioning all cluster types
    * Letsencrypt certs
    * BYO valid certs
    * Rancher-generated
    * k3s-backed install w/ Letsencrypt 
  * View logs, exec shell, kubectl all function in all clusters

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.9-rc3

* Deploy Rancher in a semi-airgapped environment, with a proxy
  * Rancher installed a node with no public IP / direct access to the internet in EC2
  * Internet-facing load balancer points to Rancher so it is externally accessible
  * Docker settings and Rancher both use proxy
  * No private registry
* Create each of GKE, EKS, AKS, Custom clusters (custom cluster created from DO node)
* Clusters provision
* Cluster and node agents deploy on all clusters
* Clusters are active and accessible
* View logs, exec shell, kubectl all function in all clusters

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.9-rc3

* Additionally performed an upgrade from v2.3.8 -> v2.3.9-rc3
* Deploy Rancher in a semi-airgapped environment, with a proxy
  * Rancher installed a node with no public IP / direct access to the internet in EC2
  * Internet-facing load balancer points to Rancher so it is externally accessible
  * Docker settings and Rancher both use proxy
  * No private registry
* Custom cluster on-prem
* Upgrade to v2.3.9-rc3
* Custom cluster agents upgrade
* Scale up custom cluster to add additional worker nodes succeeds without issue
