### ISSUE TITLE
[feature] Support VMWare as a provider for new hosts

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2548]
The VMWare API could be added as another built-in method for autoprovisioning new Hosts, in the same way as you already do for AWS, Rackspace etc.

This would allow VMWare users to automatically spin up new hosts very quickly without the current steps of clone template, log in, run Rancher agent.

The API would only need to be given credentials, VirtualCentre URL, destination container and a template... though this may be dependent on creating an ovf VMWare template for RancherOS in order to achieve it.  CloudFoundry is a good example of something that can do this.

**Comment by cloudnautique** [comment]
In the "other" machine drivers, vmwarevsphere and vmwarevcloudair is available driver types. We are just using Docker machine under the hood.

**Comment by sshipway** [comment]
I've spotted the VSphere one, but it is not clear what should go into the many settings.  The AWS one is far simpler.  Can this be simplified?

**Comment by vincent99** [comment]
The "other" ones are "other" because they are just generically exposing all the options in docker-machine driver.  The ones that have nicer screens are mostly either huge public clouds everybody wants or were contributed by the hosting company themselves.  AWS's raw options are particularly unusable, so the UI talks to their API to pull information.

The [docker docs](https://docs.docker.com/machine/drivers/vsphere/) may help.

**Comment by sshipway** [comment]
The VMWare API params are not exactly helpful, either.   I guess what I'd like is a more user-friendly interface to the VMWare provisioning system... 

It seems that any data entered into these forms is not kept in the database to pre-populate later calls, which is inconvenient.  This would seem a good idea, particularly with the more complex forms.

 While a lot of people use the cloud-based systems, any organisation that uses a large in-house cloud (either for performance or security reasons) is likely to be using VMWare.  

I've not yet managed to make this work.  Part of the problem seems to be that it relies on a package called 'govc' which is not installed; also I'm not sure of what URL to be using for the vmware template image.

**Comment by deniseschannon** [comment]
Have you been able to install a VM using docker-machine? Since we're just calling a docker-machine command, it might be easier to figure it out with docker-machine before translating to Rancher?

**Comment by sshipway** [comment]
So far, I've only installed docker hosts on VMware by building from the CoreOS VMware template with a cloud_config.yaml file.  I'm not aware of the docker-machine command, I'd need to look into this.

**Comment by deniseschannon** [comment]
The UI in Rancher is only calling docker-machine command, so looking to the docker-machine docs for vmware might be helpful.

https://docs.docker.com/machine/drivers/vsphere/

**Comment by vincent99** [comment]
@sshipway Are you using Rancher v0.44?  `govc` was missing but [added](https://github.com/rancher/cattle/commit/7fa4d0b00d095967d68c6ba8842f2267ff1e76f3) a couple weeks ago.

Cloning an existing host created through machine will pre-populate the form with the previous values (except #2226 may foil that).

Talking to the vSphere API and adding custom UI for it is certainly possible, but not trivial; depends largely on what their API looks like and it can be talked to, and I'm not familiar with it.

The only option the driver provides to choose the OS/image that's deployed is the "boot2docker url", which appears to just mean where to find an ISO to download (e.g. https://releases.rancher.com/os/v0.4.0/rancheros.iso or https://github.com/boot2docker/boot2docker/releases/download/v1.9.0/boot2docker.iso).  There is not an option to choose an existing template from vSphere.

Do all your users have direct access to the vSphere GUI/API to go deploying VMs?  Many big companies may *run* VMWare, but can Joe developer login to vSphere and spin up things directly (which they would need to use this machine driver)?  e.g. The last big company I worked at had their own provisioning system.. you may get a VMWare VM out the back of it, but you never interacted with it directly and the operations team would never let a normal user anywhere near it.

**Comment by sshipway** [comment]
We're using Rancher-Server 0.43.1.  I'll be looking to upgrade to 0.44 shortly.

The VMWare API is not the most efficient, but it can achieve everything required.  I've coded a few Nagios integrations that use it, via the Perl library.   There may be a fair amount of work involved for you to properly support it, though.  Since the current implementation uses an ISO it will configure a VM effectively from nothing, which will be why it needs all the additional parameters - a VMWare template will set all of these up in advance, which works better for us as we can configure for DHCP and so on.  The docker-machine command seems to be pretty limited and unfriendly in the way it integrates with VMWare.

Currently, only the VM admins here can spin up new VMs via our provisioning syste,.  However, for Docker Hosts, eventually we would like to allow users to spin up their own Hosts in a predefined resource pool via an automated interface such as this.  Being a University, we have different use cases to most companies, and so we have researchers and lecturers who would want to spin up a dedicated Host in their personal Environment for a short period of time before destroying it, and other similar cases.  We might get a large number of short-lived personal environments rather than one large Prod and one large Dev.

If we can have a setup whereby a research group have their own VMWare API credentials and can spin up new Docker Hosts on demand (within a predefined resource pool of course) it would greatly streamline our procedure.

**Comment by deniseschannon** [comment]
With the release of v1.1, we've addese support for:

Custom UI for Machine Drivers [#4589] - In addition to being able to add your own Docker Machine drivers into Rancher, this feature will allow users to also add their own custom UI elements for the driver. Please see https://github.com/rancher/ui-driver-skel for more details.

If a custom UI is requested for vmware, we'd advise to create your own at this time. 

Vmware is already a provider for new hosts through our existing drivers and "Other" machine driver UI page.
