### ISSUE TITLE
Control plan and etcd nodes are drained two times during an upgrade 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25480]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Bring up a cluster - 3 etcd, 2 control planes and 2 worker nodes - k8s v 1.15
- Upgrade k8s version to k8s v 1.16

**Expected Result:**
Control planes and etcd nodes should get drained and cordoned only once during the upgrade process

**Actual Result:**
Control planes get drained two times during the process. One time while upgrading the kube-apiserver component, and once while upgrading the kubelet, kube-proxy components.

Same is the case with etcd nodes. Once when the etcd component is upgraded and the second time when the kubelet, kube-proxy components are upgraded.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - latest - commit id: `e11d47814`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.15
```

**Comment by mrajashree** [comment]
Etcd nodes aren't getting drained twice, only controlplane nodes are

**Comment by sowmyav27** [comment]
**verified on `rancher:2.4.0-rc1`**

Cluster spec tested:
- 7 nodes cluster - 3 etcd, 2 control plane and 2 worker nodes
- 3 nodes - all roles cluster
On an Upgrade from k8s 1.15 to 1.16, verified that the control planes are drained only once during the upgrade process. Control plane and worker components are upgraded together.
