### ISSUE TITLE
Shibboleth - user input for cluster roles gets cleared, not allowing to add users manually

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25484]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Install Rancher 2.4 `master-head (02/19/2020)` commit id: e11d47814
2. Enable Shibboleth with OpenLDAP
3. Add a user and a group as cluster owners
4. Disable Shibboleth
5. Re-enable Shibboleth **without** OpenLDAP (OpenLDAP search will be disabled)
6. Login as a user in step 3.
7. Try to add a user search to LDAP won't work but we should be able to add an arbitrary username.

**Result:**

The dropdown input field for User/Group gets cleared out when trying to select the Cluster Role.
This doesn't happen with others SAML providers like Keycloak which allows us to add usernames manually (not selected from dropdown).

**Other details that may be helpful:**

Errors/warnings in Rancher logs

```
2020/02/19 21:30:52 [ERROR] Unknown error: invalid server config. only exactly 1 server is currently supported
2020/02/19 21:31:54 [WARNING] ldap search principals failed to connect to ldap: invalid server config. only exactly 1 server is currently supported
```

**Environment information**
- Rancher version: `2.4 master-head (02/19/2020)` commit id: e11d47814
- Installation option (single install/HA): single

**Comment by izaac** [comment]
After further testing this also happens if we setup Shibboleth **without** OpenLDAP. There's no need to disable and re-enable to reproduce.

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/25489

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/25489

**Comment by izaac** [comment]
This is no longer reproducible in Rancher version `2.4 master-head (02/21/2020)` commit id: 264d9235b

I was able to add users and groups when the Shibboleth is not configured with OpenLDAP search now.
