### ISSUE TITLE
Containers in the default-http-backend Pod are OOM killed

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#25490]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Steps to reproduce (least amount of steps as possible):** Exact steps are unknown, although the issue is known to manifest on large clusters

**Result:** Deployment restarts Pods as the containers exit (code: 137), with OS logs confirming a related OOM kill 

**Other details that may be helpful:** Increasing the memory limit from the default (`20Mi`) stabilises the container. The small headroom of memory can result in an OOM kill on some clusters.
 
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): v1.16.3

gz#8557

**Comment by Oats87** [comment]
I've always had a theory that the default backend server OOM's due to large numbers of requests against it, considering it keeps Prometheus data within it: https://github.com/kubernetes/ingress-nginx/blob/debf0249215aebda7f2927d2e4e2f34b38e91af6/images/404-server/metrics.go#L31

**Comment by dkeightley** [comment]
That could make sense here, as I do believe there are F5 health checks being performed. I can request more data to understand the request behaviour if needed.

**Comment by Oats87** [comment]
If you grab the pod IP of the `default-http-backend` you can `curl http://<pod-ip>:10254/metrics` and grab the current info.

**Comment by dkeightley** [comment]
Closing as this can be mitigated by [disabling the default backend](https://github.com/rancher/rancher/issues/25590) and using the global nginx backend
