### ISSUE TITLE
Multivalue A record has changed to a single record

### ISSUE THREAD

**Issue by olefemmy** [rancher/rancher#25492]
*My cluster has 5 worker nodes and everything has been fine until yesterday early evening. Before then, all DNS entries has the 5 IP addresses of the worker nodes and all of the nodes were receiving traffic. However, without any deployment or any work in Rancher, all entries in Route53 now has a single IP address of a worker node and this is the only worker node that is now receiving traffic. Please can you help*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`workload`|

**Comment by olefemmy** [comment]
I changed the record in Route 53 to contain all the 5 IP addresses of the worker nodes, the next minute, it was updated back to 1 IP address!

**Comment by olefemmy** [comment]
Once I restart the ingress controllers, it seems the last one that gets restarted is the IP address that is updated in Route53. In other words, it's almost like a race condition and the last one that gets started takes control in informing DNS what information to send to Route53.

**Comment by olefemmy** [comment]
Another observation is that there is only a single IP address that is associated with the LB in a project space. So, for example, `apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    field.cattle.io/publicEndpoints: '[{"addresses":["3.10.223.48"],"port":443,"protocol":"HTTPS","serviceName":"p-j4lfz-pipeline:auth-master-service","ingressName":"p-j4lfz-pipeline:auth-master-ingress","hostname":"auth.master.apps.wsp-lattice.io","path":"/","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"certmanager.k8s.io/cluster-issuer":"letsencrypt-prod","kubernetes.io/ingress.class":"nginx","kubernetes.io/tls-acme":"true","nginx.ingress.kubernetes.io/secure-backends":"true","rancher.io/globalDNS.hostname":"auth.master.apps.wsp-lattice.io"},"name":"auth-master-ingress","namespace":"p-j4lfz-pipeline"},"spec":{"rules":[{"host":"auth.master.apps.wsp-lattice.io","http":{"paths":[{"backend":{"serviceName":"auth-master-service","servicePort":80},"path":"/"}]}}],"tls":[{"hosts":["auth.master.apps.wsp-lattice.io"],"secretName":"auth-master-cert"}]}}
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    rancher.io/globalDNS.hostname: auth.master.apps.wsp-lattice.io
  creationTimestamp: "2020-02-04T14:22:36Z"
  generation: 1
  name: auth-master-ingress
  namespace: p-j4lfz-pipeline
  resourceVersion: "12329978"
  selfLink: /apis/extensions/v1beta1/namespaces/p-j4lfz-pipeline/ingresses/auth-master-ingress
  uid: b970c97c-c788-4ba6-907c-d4f72c5d99e2
spec:
  rules:
  - host: auth.master.apps.wsp-lattice.io
    http:
      paths:
      - backend:
          serviceName: auth-master-service
          servicePort: 80
        path: /
  tls:
  - hosts:
    - auth.master.apps.wsp-lattice.io
    secretName: auth-master-cert
status:
  loadBalancer:
    ingress:
    - ip: 3.10.223.48
`
I expect the IP addresses of all the nodes to be listed here.

**Comment by olefemmy** [comment]
The log on reprovisioning a node is the following:

W0221 17:17:27.481950 6 flags.go:221] SSL certificate chain completion is disabled (--enable-ssl-chain-completion=false)
nginx version: openresty/1.15.8.1
W0221 17:17:27.485215 6 client_config.go:541] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.
I0221 17:17:27.485422 6 main.go:183] Creating API client for https://10.43.0.1:443
I0221 17:17:27.491689 6 main.go:227] Running in Kubernetes cluster version v1.16 (v1.16.3) - git (clean) commit b3cbbae08ec52a7fc73d334838e18d17e8512749 - platform linux/amd64
I0221 17:17:27.495494 6 main.go:91] Validated ingress-nginx/default-http-backend as the default backend.
I0221 17:17:27.663487 6 main.go:102] Created fake certificate with PemFileName: /etc/ingress-controller/ssl/default-fake-certificate.pem
I0221 17:17:27.690878 6 nginx.go:274] Starting NGINX Ingress controller
I0221 17:17:28.033142 6 event.go:258] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"ingress-nginx", Name:"nginx-configuration", UID:"e92b384e-cd3c-452f-b183-74a18cde28ff", APIVersion:"v1", ResourceVersion:"592", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap ingress-nginx/nginx-configuration
I0221 17:17:28.033361 6 event.go:258] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"ingress-nginx", Name:"udp-services", UID:"d48b28df-00dc-4e0a-bc5a-acd55da0a272", APIVersion:"v1", ResourceVersion:"597", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap ingress-nginx/udp-services
I0221 17:17:28.044994 6 event.go:258] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"ingress-nginx", Name:"tcp-services", UID:"f4e6d726-5a26-499f-8d64-274a9ff312f1", APIVersion:"v1", ResourceVersion:"596", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap ingress-nginx/tcp-services
I0221 17:17:29.165791 6 backend_ssl.go:66] Adding Secret "p-j4lfz-pipeline/auth-master-cert" to the local store
I0221 17:17:29.166671 6 backend_ssl.go:66] Adding Secret "p-jvztj-pipeline/corgis-review-auth-service-cert" to the local store
I0221 17:17:29.167972 6 backend_ssl.go:66] Adding Secret "p-fvvtq-pipeline/wits-stag-cert" to the local store
I0221 17:17:29.168097 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-j4lfz-pipeline", Name:"auth-master-ingress", UID:"b970c97c-c788-4ba6-907c-d4f72c5d99e2", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345219", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-j4lfz-pipeline/auth-master-ingress
I0221 17:17:29.168135 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-jvztj-pipeline", Name:"corgis-review-auth-service-ingress", UID:"4f6e5aa4-c900-4968-a45a-cda789a4d423", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345224", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-jvztj-pipeline/corgis-review-auth-service-ingress
I0221 17:17:29.168183 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-fvvtq-pipeline", Name:"wits-stag-ingress", UID:"0134fa0c-ddfb-4f8d-bb56-5e848c2d6bdc", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345147", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-fvvtq-pipeline/wits-stag-ingress
I0221 17:17:29.168366 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-jvztj-pipeline", Name:"corgis-master-ingress", UID:"3f7ee5e4-a824-42a7-99d2-209eeccee31e", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345181", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-jvztj-pipeline/corgis-master-ingress
I0221 17:17:29.170037 6 backend_ssl.go:66] Adding Secret "p-jvztj-pipeline/corgis-master-cert" to the local store
I0221 17:17:29.170357 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-px2w9-pipeline", Name:"geoservice-test-ingress", UID:"88bbaa20-e151-4348-a139-0c6ac31e2e92", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345207", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-px2w9-pipeline/geoservice-test-ingress
I0221 17:17:29.170860 6 backend_ssl.go:66] Adding Secret "p-px2w9-pipeline/geoservice-test-cert" to the local store
I0221 17:17:29.171086 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-jvztj-pipeline", Name:"corgis-review-fix-sidebar-indent-ingress", UID:"ad1d78e2-a5b2-4f39-8d7b-a9060b0a91f9", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345239", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-jvztj-pipeline/corgis-review-fix-sidebar-indent-ingress
I0221 17:17:29.171699 6 backend_ssl.go:66] Adding Secret "p-jvztj-pipeline/corgis-review-fix-sidebar-indent-cert" to the local store
I0221 17:17:29.172432 6 backend_ssl.go:66] Adding Secret "p-7p5bc-pipeline/fpt-test-cert" to the local store
I0221 17:17:29.174169 6 backend_ssl.go:66] Adding Secret "p-82cnf-pipeline/imannotate-test-cert" to the local store
I0221 17:17:29.174781 6 backend_ssl.go:66] Adding Secret "p-fvvtq-pipeline/wits-prod-cert" to the local store
I0221 17:17:29.174824 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-7p5bc-pipeline", Name:"fpt-test-ingress", UID:"15fbc195-e2a5-4251-b87f-7cc0e750d402", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345124", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-7p5bc-pipeline/fpt-test-ingress
I0221 17:17:29.174847 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-82cnf-pipeline", Name:"imannotate-test-ingress", UID:"a1e51a30-9a6d-4830-87a9-150587b92f09", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345174", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-82cnf-pipeline/imannotate-test-ingress
I0221 17:17:29.175651 6 backend_ssl.go:66] Adding Secret "p-fvvtq-pipeline/wits-test-cert" to the local store
I0221 17:17:29.176314 6 backend_ssl.go:66] Adding Secret "p-jvztj-pipeline/corgis-prod-cert" to the local store
I0221 17:17:29.176343 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-fvvtq-pipeline", Name:"wits-prod-ingress", UID:"7da4f365-9ff3-42f3-be12-a8a4453f9846", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345093", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-fvvtq-pipeline/wits-prod-ingress
I0221 17:17:29.176362 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-fvvtq-pipeline", Name:"wits-test-ingress", UID:"18c930a3-e8f4-4f6c-9334-bfc632f1d85b", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345115", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-fvvtq-pipeline/wits-test-ingress
I0221 17:17:29.178064 6 backend_ssl.go:66] Adding Secret "p-jvztj-pipeline/corgis-stag-cert" to the local store
I0221 17:17:29.178910 6 backend_ssl.go:66] Adding Secret "p-jvztj-pipeline/corgis-demo-cert" to the local store
I0221 17:17:29.184690 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-jvztj-pipeline", Name:"corgis-prod-ingress", UID:"7055edcb-ba2c-4da5-b89f-cfad04624ba4", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345157", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-jvztj-pipeline/corgis-prod-ingress
I0221 17:17:29.184941 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-jvztj-pipeline", Name:"corgis-stag-ingress", UID:"87b20ef5-e6ec-4e59-b96a-73395bedf1cc", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345165", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-jvztj-pipeline/corgis-stag-ingress
I0221 17:17:29.185831 6 backend_ssl.go:66] Adding Secret "p-jvztj-pipeline/corgis-review-geolocation-cert" to the local store
I0221 17:17:29.189906 6 backend_ssl.go:66] Adding Secret "p-jvztj-pipeline/corgis-review-modularization-cert" to the local store
I0221 17:17:29.195167 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-jvztj-pipeline", Name:"corgis-demo-ingress", UID:"9e0cd88e-17cf-4de9-85f7-80ef3cad1148", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345104", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-jvztj-pipeline/corgis-demo-ingress
I0221 17:17:29.195332 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-jvztj-pipeline", Name:"corgis-review-geolocation-ingress", UID:"72953841-3d15-4c37-9292-497a7d7ddd32", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345230", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-jvztj-pipeline/corgis-review-geolocation-ingress
I0221 17:17:29.196653 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-jvztj-pipeline", Name:"corgis-review-modularization-ingress", UID:"2a8ca5d5-470a-4afe-9a6f-82209f5aa90b", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345213", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-jvztj-pipeline/corgis-review-modularization-ingress
I0221 17:17:29.199538 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-jvztj-pipeline", Name:"corgis-review-geoservice-ingress", UID:"41e3c900-f59f-402d-b123-de2aa4e150c0", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345236", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-jvztj-pipeline/corgis-review-geoservice-ingress
I0221 17:17:29.199712 6 backend_ssl.go:66] Adding Secret "p-jvztj-pipeline/corgis-review-geoservice-cert" to the local store
I0221 17:17:29.200569 6 backend_ssl.go:66] Adding Secret "p-jvztj-pipeline/corgis-review-style-updates-cert" to the local store
I0221 17:17:29.203720 6 event.go:258] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"p-jvztj-pipeline", Name:"corgis-review-style-updates-ingress", UID:"5a2b6158-5ff8-440e-bf8c-df4bb382c271", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"12345141", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress p-jvztj-pipeline/corgis-review-style-updates-ingress
I0221 17:17:29.224297 6 nginx.go:318] Starting NGINX process
I0221 17:17:29.224516 6 leaderelection.go:235] attempting to acquire leader lease ingress-nginx/ingress-controller-leader-nginx...
I0221 17:17:29.226090 6 controller.go:133] Configuration changes detected, backend reload required.
I0221 17:17:29.227312 6 status.go:86] new leader elected: nginx-ingress-controller-qbtzq
I0221 17:17:29.380766 6 controller.go:149] Backend successfully reloaded.
I0221 17:17:29.380973 6 controller.go:158] Initial sync, sleeping for 1 second.
I0221 17:17:5

**Comment by szuecs** [comment]
Sidenote from external-dns point of view:

If the `ingress.status` has only one IP/hostname, external-dns can only assign all mentioned `spec.rules[].host` to the given one. 
To fix the issue the ingress controller configuration or the controller needs to be fixed.

**Comment by olefemmy** [comment]
I can confirm that the problem is with the latest image (rancher/nginx-ingress-controller:nginx-0.25.1-rancher1)

I have reverted to the previous image (rancher/nginx-ingress-controller:0.21.0-rancher3) and everything seems to be working fine.

**Comment by al45tair** [comment]
The actual problem that caused this is described in #26677. I filed it separately because that let me put the right title on the issue as a bug report. (This Issue instead describes a symptom of the bug.)
