### ISSUE TITLE
[question] proper way to implement rabbitmq agent coupled with rancher network agent

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2549]
When i was going to deploy RabbitMQ HA cluster in Rancher i have encountered this challenge: each node(container) in a cluster should see others and be reachable by its hostname. I certainly could define rabbit-1, rabbit-2, rabbit-3 in compose file and link them together like `links: - rabbit-2:rabbit_rabbit-2_1 - rabbit-3:rabbit_rabbit-3_1` and etc, but i want to build an elastic cluster.
<img width="513" alt="screenshot 2015-11-05 00 03 44" src="https://cloud.githubusercontent.com/assets/817946/6499344/6c071426-c2c7-11e4-923c-71ac84ad3620.png">

[more](https://github.com/jjasghar/rabbitmq/issues/125#issuecomment-77307847)
With `io.rancher.container.hostname_override: container_name` container hostnames are looking like `$${stack_name}_$${service-name}_$${create_index}`, so when starting a new container in a cluster i have to insert corresponding DNS entry for each node ip in `anwsers.json` file on a local rancher network agent.
The most straight-forward way is to implement agent listening for a metadata-service for a list of containers in a rabbit stack, pair it with a network agent, and apply changes to an `anwers.json` file directly.
@cloudnautique @cjellick greetings guys! Could you help me? maybe you suggest a better solution?:D Didn't find how to link on containers-level in a rancher api... Or maybe i could do some dirty inserts in a cattle DB and `answers.json` will be magically updated lol

**Comment by ndelitski** [comment]
Come up with more elegant solution :D implement custom dns server which will filling dns entries by polling  `rancher-metadata/latest/containers/rabbit_*`. This dns server will be deployed in a pair with every rabbit node and linked with a combination of `dns` and `links` configuration options, so every rabbit container will resolve each other by hostname, independently of running instances!
@cloudnautique what do you think about adding this RabbitMQ cluster implementation to official rancher-catalog? If this will work i could make a pull request

**Comment by ndelitski** [comment]
@imikushin just saw you will show how to deploy RabbitMQ cluster in upcoming meetup, what do you think about my implementation?

**Comment by cloudnautique** [comment]
Been noodling this one... I kind of came to the same place.. maybe abuse metadata/confd to create dnsmasq responses and forward everything else to our default DNS...

You can't really write to the answers.json file because Rancher will clobber it. 
Also, one thing to note, though is we do not guarantee hostnames will be the same. If you have 3 nodes, and the second one dies.. it might comeback as  4. It sounds like this is problematic for Rabbit? We are working on a feature to keep the IP addresses consistent between restart/upgrade. Not sure if that would help.

**Comment by cloudnautique** [comment]
Oh, and yeah, if RabbitMQ is working well we should offer it in the catalog.

**Comment by ndelitski** [comment]
Didn't know about `dnsmasq`, it is exactly better suited in a combination with `confd-rancher`, i'll give it a try though. Changing ip is such pain...
An alternative approach might be used if rancher would have a `hostname_override: container_ip` option(hostname will be `ip-10-42-xxx-xxx`), then when ip change, hostname will change too and node will rejoin cluster with new name. But here we have another sort of a problem - if there are a lot of inactive hostnames in a cluster we have to periodically do a cleanup with `rabbitmqctl forget_cluster_node ` command.

**Comment by deniseschannon** [comment]
@ndelitski Please re-open if you still have questions about this.
