### ISSUE TITLE
[ui] Light and dark theme have different spacing around clusters

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#25498]
Running master head the clusters have less spacing per row vs the light theme, which I think is better anyways

![Screen Shot 2020-02-20 at 1 41 08 PM](https://user-images.githubusercontent.com/13897607/74976835-bc99c900-53e6-11ea-9e6e-7d1a29f8eb18.png)
![Screen Shot 2020-02-20 at 1 41 27 PM](https://user-images.githubusercontent.com/13897607/74976837-bd325f80-53e6-11ea-95a0-a12a08e547c4.png)

**Comment by sowmyav27** [comment]
**Reproduced the issue in 2.3.5**
<img width="1276" alt="Screen Shot 2020-03-09 at 4 43 19 PM" src="https://user-images.githubusercontent.com/26032343/76277262-7e553400-6245-11ea-99f2-52b8bf55ab22.png">
<img width="1259" alt="Screen Shot 2020-03-09 at 4 43 31 PM" src="https://user-images.githubusercontent.com/26032343/76277264-7eedca80-6245-11ea-9d1a-4525b46fde7d.png">

**Validated the fix on master-head - latest2**
<img width="1282" alt="Screen Shot 2020-03-09 at 8 36 35 PM" src="https://user-images.githubusercontent.com/26032343/76277454-02a7b700-6246-11ea-8b28-70d2a4874a3b.png">
<img width="1262" alt="Screen Shot 2020-03-09 at 8 36 02 PM" src="https://user-images.githubusercontent.com/26032343/76277455-03d8e400-6246-11ea-97f3-38eb2580ed59.png">
