### ISSUE TITLE
service could not be resolved when execute "docker stop and docker start"

### ISSUE THREAD

**Issue by linbingdouzhe** [rancher/rancher#25491]
**What kind of request is this (question/bug/enhancement/feature request):BUG

**Steps to reproduce (least amount of steps as possible):
My rancher installed by single docker node , I need to do disaster recovery action, so I have stoped rancher container then backup the container "/var/lib/rancher" directory . When i done , I start the old rancher container . Then everything seem normal

**Result:**
My deployments has appeared error : server could not be resolved , sometimes
 it will report that network can not be reached.

**Other details that may be helpful:**
When i face this problem , i usually restart all calico node or core-dns node , that will be recovery.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA):single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EC2
- Machine type (cloud/VM/metal) and specifications (CPU/memory): rancher-os
- Kubernetes version (use `kubectl version`): 1.15.4

- [ ] 

```
(paste the output here)
```

- Docker version (use `docker version`):
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
(paste the output here)
```

**Comment by linbingdouzhe** [comment]
there is no error info on calico logs or coredns logs 
could somebody help me ?
@loganhz

**Comment by superseb** [comment]
If you are talking about stopping and starting the `rancher/rancher` container, please check what IPs are assigned to the pods as described in https://github.com/rancher/rancher/issues/23284

**Comment by superseb** [comment]
Please let us know if we need to investigate this.

**Comment by linbingdouzhe** [comment]
i found that reason , because there has some wrong hpa setting , when i restart that rancher/rancher container , cluster will be abnormal status . And i try to move it , that problem has been resolved. thanks
