### ISSUE TITLE
Validate Rancher HA installs on k3s clusters.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#25495]

**Comment by aaronRancher** [comment]
According to our staging documentation, https://staging.rancher.com/docs/rancher/v2.x/en/installation/k8s-install/kubernetes-rke/, we start K3s without deploying `traefik`. This results in no ingress being deployed and Rancher unaccessible through the UI.
Deploying k3s with traefik by default allows Rancher to be accessed through the UI in an HA install.
```
curl -sfL https://get.k3s.io | sh -s - server \
--datastore-endpoint="mysql://<username>:<Password>@tcp(<hostname>:3306)/<data-store name>" \
```

**Comment by aaronRancher** [comment]
Verified with Rancher server `rancher\rancher:master-head` `version 1ce03e7`
Steps:
Create a mysql datastore in aws.
Install k3s on 2 linux instances:
```
curl -sfL https://get.k3s.io | sh -s - server \
--datastore-endpoint="mysql://<username>:<Password>@tcp(<hostname>:3306)/<data-store name>" \
```
Set LB and route 53
Set kubectl
Install Rancher:
```
helm install rancher rancher-alpha/rancher --namespace cattle-system --set hostname=<hostname> --version 2.4.0-alpha1  --set rancherImageTag=master-head
```

Existing automation passes on a 3 node custom cluster, all roles.

**Comment by aaronRancher** [comment]
k3s HA install has been validated using mysqkl and postgresql for AWS datastores.

**Comment by aaronRancher** [comment]
HA install validated for k3s version `1.17.2+k3s1`
Traefik version: `1.7.19`

kubectl and exec shell work in the following browsers:
Chrome version `80.0.3987.122`
Firefox version `73.0.1`
Safari version `13.0.5 (15608.5.11)`

Previous issues prevent Traefik from being the recommended ingress controller over nginx:
https://github.com/rancher/rancher/issues/7425#issuecomment-272999869

**Comment by jiaqiluo** [comment]
on the setup K3s `v1.17.3+k3s1` (HA mode)+ external etcd `v3.3` + Rancher `v2.4.0-rc1`, I can exec shell and view logs of workloads deployed in local and user clusters(cluster provisioned by Rancher).

**Comment by sangeethah** [comment]
Waiting on new K3s release with nginx as default provider for Ingress.
Need to re test using this K3s version with Mysql 5.7 and MariaDB.

**Comment by aaronRancher** [comment]
HA install validated for k3s version `v1.17.3-alpha1+k3s1`
MariaDB version: `10.3.20`

kubectl and exec shell work in the following browsers:
Chrome version `80.0.3987.132`
Firefox version `73.0.1` 
Safari version `13.0.5 (15608.5.11)`

We will use Traefik as the default provider for ingress. Testing was done using `traefik:1.7.19`

**Comment by jiaqiluo** [comment]
hold for validating Rancher in k3s HA in an air-gapped environment.
