### ISSUE TITLE
Add timer to automatically logout 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#255]
Github auth is good for days, but the JWT (JSON Web Token) that authenticates the UI to the backend is good for 16 hours. Once that's up you should get sent automatically back to the the login page to login again.

**Comment by deniseschannon** [comment]
@vincent99 Is this already in?

**Comment by vincent99** [comment]
Nope

**Comment by westlywright** [comment]
@deniseschannon is the use case for this that the user has had there single tab open for more then 16hours and then api calls start to fail because auth expired?

**Comment by deniseschannon** [comment]
I have no idea. I had copied it over from the UI repo many months ago when I was closing up issue filing in other repos. :) Ask @vincent99

**Comment by vincent99** [comment]
Yes.. You login Monday morning, use it all day and Tuesday it looks still good but fails the first time you click something.

**Comment by tfiduccia** [comment]
Version - master 3/17
Verified fixed
