### ISSUE TITLE
Cluster agent and Node agent pods stuck in removing state on a rancher server upgrade and fails to get upgraded

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25506]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster - 3 nodes - 1 etcd, 1 control plane and 1 worker node in 2.3.5
- Deploy a workload on the cluster
- Upgrade rancher to latest master-head - commit id: `1ce03e735`
- The Cluster agent and Node agent pods stuck in removing state on the control plane node.
- cattle node agent is seen upgraded on the worker node

**Expected Result:**
Cluster agent and Node agent pods should get upgraded successfully

**Note:**

- CLuster with all roles - 1 node. Upgrade was successful from 2.3.5 to master head.
- Cluster agent and Node agent pods are upgraded successfully
- System Project --> Pods are all active and up.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `1ce03e735`
- Installation option (single install/HA): single node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
v1.15.9
```

**Comment by soumyalj** [comment]
Reproduced the issue above:
1. Create a 3 node cluster with K8s version : v1.15.9
N1 : control 
N2: etcd
N3 : worker
2. Deploy few workloads
3. Upgrade Rancher to master-head(Rancher version dad58367e (dad58367e))
After upgrading rancher, the node-agent on worker node was stuck in "Removing" state and failed to get upgraded.
node-agent on contolplane node got upgraded. 
<img width="911" alt="Screen Shot 2020-02-21 at 11 23 48 AM" src="https://user-images.githubusercontent.com/18536626/75065276-5fad1a00-549d-11ea-8505-cc74206c271a.png">

The cluster agent got upgraded successfully.
<img width="923" alt="Screen Shot 2020-02-21 at 11 30 50 AM" src="https://user-images.githubusercontent.com/18536626/75065394-a3a01f00-549d-11ea-943f-154643dc62f5.png">

**Comment by sowmyav27** [comment]
Even "kube-api-auth" workload pods are stuck in `Removing` state. Pods on the control plane nodes are stuck in removing state
<img width="1276" alt="Screen Shot 2020-02-25 at 10 09 24 AM" src="https://user-images.githubusercontent.com/26032343/75274078-07388e00-57b7-11ea-8cba-e1491e9fa626.png">

**Comment by StrongMonkey** [comment]
Looks like restarting kubelet fixes everything. Pod was stuck at terminating due to volumeMount failed to be removed.

**Comment by deniseschannon** [comment]
But why is the pod stuck at terminating? It seems to be stuck for the last couple of upgrades.

**Comment by mrajashree** [comment]
https://github.com/rancher/rancher/issues/16722#issuecomment-442176111
Looks like we have faced this issue earlier

**Comment by StrongMonkey** [comment]
During initial investigation, this might be the one that is causing the problem: https://github.com/rancher/rancher/pull/25245.

Seb corrected the node registration command so that share-mnt can be successfully run. Share-mnt changes the mounting directory so that /var/lib/kubelet will be mounted as shared(in order for mounts to be propagated from container to host. This change caused pods fail to be removed since it uses secret volume which fail to be unmounted. I think to solve this issue we have to restart kubelet after share-mnt is run.

**Comment by StrongMonkey** [comment]
Also to reproduce that problem, start rancher v2.3.5 and provision the cluster. Run the following command on one of the nodes:
```
mount --bind -o rw /var/lib/kubelet /var/lib/kubelet 
mount --make-shared  /var/lib/kubelet
``` 
which is the exact command that share-mnt will run.

Also tried with a custom build without that commit, it appears to be working.

**Comment by sowmyav27** [comment]
**Verified on upgrade from 2.3.5 to latest - master-head - commit id: `f21253e15`**

**Steps:**

- Deploy a cluster - 3 nodes - 3 etcd, 2 control plane and 3 worker node in 2.3.5
- Deploy a workload on the cluster
- Upgrade rancher to latest master-head - commit id: `f21253e15`
- All the workloads in System Project are Active.
