### ISSUE TITLE
Add in places in UI for the new system labels that have been introduced

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2550]
Based on the labels docs, some of these need to be incorporated into the UI so that if you clone a service, it will clone the behavior. Due to the fact system labels are not copied (https://github.com/rancher/rancher/issues/2342), it needs to be added in the UI so that clone would work. 

http://docs.rancher.com/rancher/labels/

Labels to add into the UI include:
io.rancher.container.dns
io.rancher.container.hostname_override
io.rancher.container.start_once
io.rancher.container.pull_image
io.rancher.container.requested_ip

**Comment by sshipway** [comment]
+1 for at least start_once to be a UI checkbox.

**Comment by jippi** [comment]
:+1:

**Comment by vincent99** [comment]
DNS is on by default and doesn't have a false value so it doesn't make sense to show.  The others are fine.

**Comment by vincent99** [comment]
DNS: Available only if managed network, off by default
Hostname: Available only on service, radio to select "container name" or custom string
Start once: Available only on service
Requested IP: Available only if managed network
Pull: Enabled by default because it seems like what people want

**Comment by deniseschannon** [comment]
DNS: This only works for Host networking so should hide for bridge/none. @vincent99 
Pull: It's not enabled by default. Did we want to?

I have not tested on containers, just services.

**Comment by vincent99** [comment]
(in master/after rc3)

- DNS Changed to only networkMode=host
- DNS changed to actually work when set
- Pull on by default

**Comment by tfiduccia** [comment]
Tested and entered separate bugs against issues.
