### ISSUE TITLE
Add Custom Cluster, no data in the kubernetes drop down

### ISSUE THREAD

**Issue by Rancheroo** [rancher/rancher#25509]
**What kind of request is this (question/bug/enhancement/feature request):**
Raising this issue for visibility as it seems to be solved in 2.3.5
Missing info on kubernetes tab when adding Custom cluster

**Steps to reproduce (least amount of steps as possible):**
1. new 3 node cluster (RKE 1.04)
2. install Rancher 2.3.3
3. Access UI and click add cluster
4. Under the kubernetes menu it has no kubernetes version listed

**Result:**
![image](https://user-images.githubusercontent.com/56899019/75012086-5a6bc180-54d5-11ea-9814-9326d2aa1cdc.png)

**Other details that may be helpful:**
Upgrading to Rancher to 2.3.5 corrects the issue
(Also a workaround removing 2.3.5 and installing 2.3.3 is a hacky workaround for this issue also)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA rke 1.04

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
https://github.com/rancher/rancher/issues/24091
