### ISSUE TITLE
Rancher alerting can not be enabled in master-head

### ISSUE THREAD

**Issue by GGGitBoy** [rancher/rancher#25507]
**What kind of request is this (question/bug/enhancement/feature request):**

- bug

**Steps to reproduce (least amount of steps as possible):**

- Start rancher master-head version(2020-02-20)

- Add notifier

- Add alert group

**Result:**

 The App Cluster-alerting is not running. Only monitoring-operator has been deploy, but alert-manager not.

![捕获1](https://user-images.githubusercontent.com/51182588/75005730-42cb1380-54aa-11ea-8dce-ab31c11a3864.PNG)

**Expected:**

cluster-alerting app should be deployed in system project

**Other details that may be helpful:**

![捕获](https://user-images.githubusercontent.com/51182588/74967930-e5f13e00-5454-11ea-83bb-80a0769dd0d2.PNG)

- If change to "app, err := d.appsGetter.Apps(systemProjectName).Get(appName, metav1.GetOptions{})" here. The Cluster-alerting will work
https://github.com/rancher/rancher/blob/master/pkg/controllers/user/alert/deployer/deployer.go#L288

- The problem maybe is here
https://github.com/rancher/types/blob/master/apis/project.cattle.io/v3/zz_generated_app_controller.go#L127

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):rancher master-head version(2020-02-20)

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (02/24/2020)` commit id: f84c1e8f7

This is working for me in a new single install. I was able to setup alerting with an Slack notifier.


Both cluster alerting and the monitoring-operator system workloads green:
<img width="1269" alt="Screen Shot 2020-02-24 at 1 48 03 PM" src="https://user-images.githubusercontent.com/27659/75189849-54abf100-570c-11ea-8d40-9a1519eeca26.png">

And I was able to receive the notification over Slack: 

<img width="552" alt="Screen Shot 2020-02-24 at 1 48 45 PM" src="https://user-images.githubusercontent.com/27659/75189887-68efee00-570c-11ea-8491-2821b55e5cd0.png">
