### ISSUE TITLE
Missing labels added during service upgrade

### ISSUE THREAD

**Issue by alex88** [rancher/rancher#2551]
From the UI, if I add a label during a service in-place upgrade, the next time time I try to upgrade the service, the newly created label is missing

**Comment by sangeethah** [comment]
@alex88 , Did you add a system label - http://docs.rancher.com/rancher/labels/ as part of upgrade ? If that is the case , UI will not display this  label  when you attempt to upgrade again in "Advanced option-> labels" section. But you will be able to see it in service detail page (clicking on service).

**Comment by alex88** [comment]
@sangeethah I did, but when I upgrade again 'Advanced option -> labels' doesn't display the `io.rancher.container.pull_image` and in fact the image doesn't get pulled, the new container just starts.

After I confirm the upgrade, the service page doesn't show any labels anymore

**Comment by alex88** [comment]
So actually:
 - service doesn't have any labels
 - upgrade service and add the `io.rancher.container.pull_image` label
 - image gets pulled and new container started
 - confirm upgrade
 - service has `io.rancher.container.pull_image ` label
 - upgrade service and `io.rancher.container.pull_image` label isn't there anymore
 - image doesn't get pulled an new container is started right after
 - confirm upgrade
 - service doesn't have any labels

**Comment by sangeethah** [comment]
@alex88 , when upgrade is done the second time (with io.rancher.container.pull_image label set) , since UI currently does not have the ability to show system labels it does not get set when the upgrade request is done resulting in the upgraded service not having io.rancher.container.pull_image label set. This issue should be fixed when #2550 gets addressed.

**Comment by alex88** [comment]
Oh sorry

**Comment by sangeethah** [comment]
@alex88 , will make sure that we verify this use cases specifically when #2550 get addressed.
