### ISSUE TITLE
Not able to add group at project level

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25526]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Install Rancher 2.4 `master-head (02/21/2020)` commit id: 264d9235b
- Create a cluster
- Add a new user as Cluster Member for this cluster. (A user with a group)
- Login a the Cluster Member created
- Create a Project
- Edit the Project and add Member, click in the dropdown to list the group(s) the user belongs to.
- Select the Role
- Save

**Result:**

```
Validation failed in API: must target a user [userId]/[userPrincipalId] OR a group [groupId]/[groupPrincipalId]
```

<img width="1710" alt="Screen Shot 2020-02-21 at 6 03 15 PM" src="https://user-images.githubusercontent.com/27659/75093569-0a761480-5540-11ea-9c5c-0fc0e2797898.png">

Happens with Shibboleth without LDAP where I pick the group from the arrow button.
Also this happens when selecting a group from the new Shibboleth OpenLDAP search dropdown.

**Other details that may be helpful:**

Adding group to cluster level works.

Headers
```
POST /v3/projectroletemplatebinding HTTP/1.1
Host: x.x.x.x
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:73.0) Gecko/20100101 Firefox/73.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
content-type: application/json
x-api-action-links: actionLinks
x-api-no-challenge: true
x-api-csrf: a19f3bbbc0
Content-Length: 244
Origin: https://x.x.x.x
DNT: 1
Connection: keep-alive
Referer: https://96.126.101.112/c/c-sxcml/projects-namespaces/project/c-sxcml:p-4ffj4
Cookie: CSRF=a19f3bbbc0; R_SESS=token-7w7sm:wltsfm7pgnrnsghx449k8sz6txxftpcm58qh5fjw5hvshq85xm4rx2
```
POST

```json
{"type":"projectRoleTemplateBinding","subjectKind":"Group","userId":"","projectRoleTemplateId":"","projectId":"c-sxcml:p-4ffj4","groupPrincipalId":"shibboleth_group://cn=testgroup2,ou=groups,dc=example,dc=org","roleTemplateId":"project-member"}
```

Response:

```json
{"baseType":"error","code":"InvalidBodyContent","message":"must target a user [userId]/[userPrincipalId] OR a group [groupId]/[groupPrincipalId]","status":422,"type":"error"}
```

**Environment information**
- Rancher version: `2.4 master-head (02/21/2020)` commit id: 264d9235b
- Installation option (single install/HA): single

**Comment by sangeethah** [comment]
Possible regression from this fix - https://github.com/rancher/rancher/issues/24036

**Comment by sangeethah** [comment]
This issue is also seen when testing with AD authentictaion.

**Comment by soumyalj** [comment]
Version: master-head
1. Create a cluster with AD authentication .
2. Create a project and add a group as a member to the project(while creating the project). This operation fails with the error below:
```
Validation failed in API: must target a user [userId]/[userPrincipalId] OR a group [groupId]/[groupPrincipalId]

```
<img width="867" alt="Screen Shot 2020-02-21 at 9 04 44 PM" src="https://user-images.githubusercontent.com/18536626/75086863-cfe38c00-54ed-11ea-9cab-d8170e07d3b1.png">

Note: Adding a group as a member to the cluster is successful

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (02/24/2020)` commit id: f84c1e8f7

I've validated this issue using Shibboleth Auth.

Using Shibboleth+OpenLDAP

- Adding project level groups worked as expected using the OpenLDAP autocomplete dropdown.
- Adding project level **users**  worked as expected. 
- Editing a Project adding a group using the Arrow Down dropdown worked as expected

Using Shibboleth only

- Adding project level **users**  worked as expected. 
- Editing a Project adding a group using the Arrow Down dropdown worked as expected


I hit issue https://github.com/rancher/rancher/issues/25479 a couple of times with groups memberships but workaround was to logout and login again with first login users.

**Comment by soumyalj** [comment]
Tested on 2.4 master-head(Rancher version a70698d25 (a70698d25))
1. Enable AD auth in the setup and create a DO cluster .
2. Create a project and add a group as a member to the project(while creating the project). 
Adding groups at the project level is successful. 
The issue is fixed.
