### ISSUE TITLE
Sometimes custom cluster provisioning stuck in "Updating" state with "401" unauthorized error 

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#25524]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Install Rancher master-head in HA using k3s nodes.
https://staging.rancher.com/docs/rancher/v2.x/en/installation/k8s-install/create-nodes-lb/
Rancher install command:
```
helm install rancher rancher-alpha/rancher --namespace cattle-system --set hostname=<hostname> --version 2.4.0-alpha1  --set rancherImageTag=master-head
```
In master-head, provision a custom 3 node cluster using Linux instances (3 nodes, all roles each)

**Result:**
Cluster fails to be provisioned and user cannot access.
Fails with:
```
	[etcd] Failed to bring up Etcd Plane: Container [etcd-fix-perm] did not complete in time on host [18.222.106.119]; [etcd] Failed to bring up Etcd Plane: Container [etcd-fix-perm] did not complete in time on host [18.222.106.119]; [controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host [18.222.106.119]. Response code: [401], response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401} , log: W0221 23:15:04.288799 1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://172.31.13.3:2379 0 <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kube-ca\")". Reconnecting...]
```
![Screen Shot 2020-02-21 at 4 15 11 PM](https://user-images.githubusercontent.com/57409052/75079570-64d28f00-54c6-11ea-943c-cd690693132c.png)

User cannot access cluster and is blocked by 503 error:
![Screen Shot 2020-02-21 at 4 15 33 PM](https://user-images.githubusercontent.com/57409052/75079551-55ebdc80-54c6-11ea-975d-87242137e87c.png)
Dev console:
![Screen Shot 2020-02-21 at 4 15 23 PM](https://user-images.githubusercontent.com/57409052/75079565-62703500-54c6-11ea-892b-9461949584c3.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
`rancher\rancher:master-head` `version 1ce03e7`
- Installation option (single install/HA): `HA` 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
v1.17.3-rancher1-1
```

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:master-head` `version ca71db485`

Steps:
Install Rancher master-head in HA using k3s nodes.
https://staging.rancher.com/docs/rancher/v2.x/en/installation/k8s-install/create-nodes-lb/
Testing setup used mysql for AWS datastore.
In master-head, provision a custom 3 node cluster using Linux instances (3 nodes, all roles each)

Results:
Cluster fails to come up
![image](https://user-images.githubusercontent.com/57409052/75469255-eeadac80-594b-11ea-8862-ccfe90f7d10b.png)
```
[controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host [18.189.171.102]. Response code: [401], response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401} , log: W0227 17:50:42.459929 1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://172.31.1.205:2379 0 <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kube-ca\")". Reconnecting...]; [controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host [18.189.171.102]. Response code: [401], response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401} , log: W0227 17:50:42.459929 1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://172.31.1.205:2379 0 <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kube-ca\")". Reconnecting...]
--
```
Behavior is inconsistent. The same cluster setup will work sometimes. Indicative of a timing issue.

**Comment by deniseschannon** [comment]
@aaronRancher @sangeethah Is this an issue with RKE HA install or only k3s HA install. I'm trying to pinpoint if the issue is something in k3s as the local cluster or a general Rancher issue.

**Comment by sangeethah** [comment]
@deniseschannon This issue is not specific to  RKE HA install or  k3s HA install.  But we see it happen more on this  k3s HA install.

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:master-head` `version 3045289`
Steps:
Install Rancher master-head in HA using k3s nodes
Provision several custom clusters. (3 nodes, all roles)

This bug will not appear consistently. It has appeared when more than 1 cluster is being provisioned at a time.

**Comment by aaronRancher** [comment]
This bug has not been observed with Rancher server `rancher\rancher:master-head` `version 5ee70d014`
k3s version `v1.17.3-alpha1+k3s1`
Tested manually and with automation.

Can reopen the issue if observed again.
