### ISSUE TITLE
UI update for restoring etcd snapshot

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25525]
Issue: https://github.com/rancher/rancher/issues/22232

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/25540
This PR adds the new `restoreRkeConfig` which can now be passed `all` or `kubernetesVersion` as options. UI Should pull `kubernetesVersion` from the etcdsnapshot and only let these options be set if that is there. This field will only be on a backup that contains the cluster and can be restored properly with the extra options passed.

If you try and pass in `restoreRkeConfig` and the backup does not contain the clusterObject it will also error.

**Comment by sangeethah** [comment]
Reopening this issue to fix the text that appears for different option of `restoreRkeConfig` that gets set.

Currently we show this:

<img width="929" alt="Screen Shot 2020-02-26 at 9 11 50 PM" src="https://user-images.githubusercontent.com/4266958/75414704-50cfc880-58de-11ea-8cfe-56a479843e7b.png">

"Kubernetes Version - v1.16.7-rancher1-1"  option restores "ETCD and Kubernetes Version"
"ETCD and Kubernetes Version - v1.16.7-rancher1-1" options restore "ETCD , Kubernetes Version and cluster config"

**Comment by Oats87** [comment]
This might be a small nit, but it's stylized `etcd` not `ETCD`

**Comment by vincent99** [comment]
Came here to say the same... etcd is always lowercase.

**Comment by sangeethah** [comment]
With latest build , we see "etcd" case being fixed to lower case.

<img width="906" alt="Screen Shot 2020-02-27 at 2 41 59 PM" src="https://user-images.githubusercontent.com/4266958/75493732-71942e80-596f-11ea-9585-b82d6862145d.png">

Need to change the text for option 2 and option 3 to reflect the actual behavior that is done:

`Restore Kubernetes Version`  - >  `Restore etcd and Kubernetes Version`
`Restore etcd and Kubernetes Version` -> `Restore etcd , Kubernetes Version and cluster config`

**Comment by sangeethah** [comment]
With latest build from master:

<img width="975" alt="Screen Shot 2020-02-28 at 11 50 13 AM" src="https://user-images.githubusercontent.com/4266958/75582472-8086e980-5a20-11ea-96f3-6d9010875b8b.png">
