### ISSUE TITLE
Can't restore backup on rancher single node setup

### ISSUE THREAD

**Issue by rpelissi** [rancher/rancher#25533]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG: After a disaster recovery (working setup > backup> os resintall> restore) I can't have a working rancher setup by following the official documentation

**Steps to reproduce (least amount of steps as possible):**
- Install a single node rancher (v2.3.4) with etcd, control plane, worker
- bonus: install one additional worker node
- have some workload working
- make a backup using official documentation
- Recreate the OS from scratch, same setup, same docker version using official documentation
- Restore using official documentation

**Result:**
See #25311, similar error message
After the last step (docker start <rancher id>) the ui does not come backup up and the logs show something like this:
2020/02/23 17:08:36 [INFO] Waiting for server to become available: Get https://localhost:6443/version?timeout=30s: x509: certificate signed by unknown authority

**Other details that may be helpful:**
I tried on ubuntu 18.04 and Centos 7, same result

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.4
- Installation option (single install/HA):
Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Single node, Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM: 6G RAM, 4 CPU
- Kubernetes version (use `kubectl version`):
17.02

```
(paste the output here)
```

- Docker version (use `docker version`):
18.09 CE (using the curl https://releases.rancher.com/install-docker/18.09.sh | sh script)

```
(paste the output here)
```

**Comment by rpelissi** [comment]
I have disabled the swap and rebooted the system, now the rancher-agent logs output this:

```
INFO: Arguments: --server https://192.168.2.9:8443 --token REDACTED --ca-checksum 5d0b6cfc154eb8cbd39f32d56a883d8a70df35c6a5057926cbba2f573db0e897 --no-register --only-write-certs
INFO: Environment: CATTLE_ADDRESS=192.168.2.9 CATTLE_AGENT_CONNECT=true CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=pdrrancher01 CATTLE_SERVER=https://192.168.2.9:8443 CATTLE_TOKEN=REDACTED CATTLE_WRITE_CERT_ONLY=true
INFO: Using resolv.conf: search digitalrat.lan nameserver 192.168.2.1
INFO: https://192.168.2.9:8443/ping is accessible
INFO: Value from https://192.168.2.9:8443/v3/settings/cacerts is an x509 certificate
ERROR: Configured cacerts checksum (a6890287d243821c58a5f536882eb6f22d4e3d97989c23c8ea9aba50a9930a2c) does not match given --ca-checksum (5d0b6cfc154eb8cbd39f32d56a883d8a70df35c6a5057926cbba2f573db0e897)
ERROR: Please check if the correct certificate is configured at https://192.168.2.9:8443/v3/settings/cacerts
```

UI is available now but display:

`This cluster is currently Unavailable; areas that interact directly with it will not be available until the API is ready.`

I can see the snapshots from the backup in the snapshot list. I can try to rotate the certificate but the last time I did this, etc became completely dead/lost. I prefer to wait for any comment suggestion from you guys before doing stupid stuff ;)

**Comment by rpelissi** [comment]
Could it be related to #13831 or #13615?

**Comment by davemcdonnell** [comment]
Following the backup/restore instructions for Rancher on docker, I had this same issue. (Image ID 83fe4871cf67)

After taking a backup as per the instructions, I completely destroyed my container (docker rm) and then started a fresh rancher container. After restoring the content with tar to the new container (ie full DR restore), this is logged:
2020/02/25 01:18:11 [INFO] Waiting for server to become available: Get https://localhost:6443/version?timeout=30s: x509: certificate signed by unknown authority

Restarting the container fixes the issue though. I'm not sure if this needs to be documented in the DR documentation (or maybe fixed?).

**Comment by rpelissi** [comment]
Hi,
I have check the certificate in /v3/cacert and put that in a file. I have removed all \n to have a nice file and did a sha256sum on it. The value is the one expect in the error message. But there is no way to fix the certificate in the API, so I do not know what to do at that point.

**Comment by rpelissi** [comment]
I have checked in the backup file and can't find this certificate so I am not sure how I can fix this manually..

**Comment by rpelissi** [comment]
The certificate is in the etcd backup (a db file in the backup archive), I do not see any evidence that the certificate got extra characters in the db so I guess that it's during the import that something goes wrong.

**Comment by drbugfinder** [comment]
> Restarting the container fixes the issue though. I'm not sure if this needs to be documented in the DR documentation (or maybe fixed?).

Thanks! Restarting the container AGAIN (!) did the trick. 
I moved an installation from one Docker node to another Docker node. The Rancher recovery guide only describes how to restore a container on the same node when the old container is still existing. 

My steps of getting the backup run on the new node were:

- Start a FRESH Rancher container: docker run -d --restart=unless-stopped   -p 80:80 -p 443:443   rancher/rancher:{SAME VERSION, MAYBE NEWER VERSION?}
- Get {container name} via docker ps
- Stop the container docker ps {container name}
- Restore the backup docker run --volumes-from {container name} -v $PWD:/backup busybox sh -c "rm /var/lib/rancher/* -rf  && tar pzxvf /backup/{backup file name}" (The file has to be in the 
current working directory and gets mounted to /backup/ folder inside the container)
- Stop the container docker stop {container name}
- Start the container docker start {container name}
- Wait some minutes (In my case I see certificate errors when executing docker logs -f {container name})
- Then stop the container AGAIN docker stop {container name}
- And finally start the container docker start {container name}

The last restart seems to be essential that the newly generated certificates take effect (I assume).

**Comment by linbingdouzhe** [comment]
facing same problem, maybe rancher itself has some certificate problem .
In my case,  i build a rancher HA cluster to avoid single node problem ....
