### ISSUE TITLE
Pod metrics / Memory Utilization graph showing twice as large as actual

### ISSUE THREAD

**Issue by bjornmagnusson** [rancher/rancher#25536]
Memory utilization in Pod Metrics graph (both in Rancher and in Grafana) show usage roughly twice as large as the actual usage.
Example pod is limited to 1G and still the graph is show around 1.6G.
Execing into the pod show Java is using around 800M.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Launch a pod
2. Check Pod Metrics

**Result:**
Memory utilization graph showing a memory usage of around twice as large as expected, and above memory limits for the given pod

**Other details that may be helpful:**
![image](https://user-images.githubusercontent.com/6065120/75149498-7011fe80-5702-11ea-8797-8f563af488d5.png)

**Environment information**
- Rancher version: 2.3.3
- Installation option: HA

**Cluster information**
- Cluster type: RKE "local" cluster
- Machine type: on premise using CentOS 7
- Kubernetes version (use `kubectl version`): 1.16.3

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      19.03.5
 API version:  1.40
 Go version:   go1.12.12
 Git commit:   633a0ea
 Built:        Wed Nov 13 07:24:18 2019
 OS/Arch:      linux/amd64
```

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/25539
