### ISSUE TITLE
how migrate rancher server to another computer

### ISSUE THREAD

**Issue by lerit** [rancher/rancher#25531]
**What kind of request is this (question/bug/enhancement/feature request):**
question
**Steps to reproduce (least amount of steps as possible):**
1.rancher server deploy in computer A
2.use rancher to create RKE cluster in computerB,computerC and computerD(1 master and 2 work).
it work well.
3.now,for some reason,computerA will not work
4.i want to install new rancher in another computer(with different ip address)
5.what to do so that the cluster work again,or some suggest with minimum change? 

**Result:**
migrate rancher server to another computer ,and cluster will still work 

**Other details that may be helpful:**
no

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.2
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by chris-str-cst** [comment]
I actually did it today
## Backup
```bash
https://rancher.com/docs/rancher/v2.x/en/backups/backups/single-node-backups/
docker ps | grep rancher/rancher # get container ID or name
RANCHER_CONTAINER_NAME=<fromAboveCommand>
docker stop $RANCHER_CONTAINER_NAME
docker create --volumes-from $RANCHER_CONTAINER_NAME --name rancher-data rancher/rancher:latest
docker run  --volumes-from rancher-data -v $PWD:/backup:z busybox tar pzcvf /backup/rancher-data-backup.tar.gz /var/lib/rancher
docker start $RANCHER_CONTAINER_NAME
```

Move files to new host

## Restore
Create new Rancher Container from Rancher install Docs!

https://rancher.com/docs/rancher/v2.x/en/backups/restorations/single-node-restoration/
```bash
docker ps | grep rancher/rancher # get container ID or name
RANCHER_CONTAINER_NAME=<fromAboveCommand>
docker stop $RANCHER_CONTAINER_NAME
docker run  --volumes-from $RANCHER_CONTAINER_NAME -v $PWD:/backup \
    busybox sh -c "rm /var/lib/rancher/* -rf  && \
    tar pzxvf /backup/rancher-data-backup.tar.gz"
docker start $RANCHER_CONTAINER_NAME
docker restart $RANCHER_CONTAINER_NAME
```
Login to UI -> Settings and update IP and run the custom init commands on all clusters to make them available in the new rancher instance

Done

**Comment by SimonHeimberg** [comment]
Could this please be included in the doc? What do to when the rancher IP changed is included in [FAQ for 1.6](https://rancher.com/docs/rancher/v1.6/en/faqs/server/#what-happens-if-the-ip-of-rancher-server-has-changed), but nowehere for 2.

**Comment by SimonHeimberg** [comment]
@chris-str-cst what command do you relate to with "run the custom init commands on all clusters"?
I followed your instructions until this point. One of two nodes was connected automatically. But it is a worker only. How can I connect the other node?

**Comment by chris-str-cst** [comment]
@SimonHeimberg  `sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:...`
Keep in mind I provisioned custom cluster like described here: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/custom-nodes/#2-create-the-custom-cluster

**Comment by SimonHeimberg** [comment]
And what did you do with the old container running `rancher-agent`? Do you have two running? Did you stop the old one before?
My guess is there should not be running two. But they do not complain.
After having moved the rancher server, I wanted to reconfigure the nodes and had this question again: Which ranger-agent should run? https://forums.rancher.com/t/change-role-of-node/17017/2

**Comment by chris-str-cst** [comment]
I stopped the old one but only after a week or so ;)
