### ISSUE TITLE
Unable to create Registry Credentials in the correct namespace

### ISSUE THREAD

**Issue by iohenkies** [rancher/rancher#25535]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug.

**Steps to reproduce (least amount of steps as possible):**
- Go to cluster - Projects - Resources - Secrets - Registry Credentials
- Add a registry in a single namespace
- We're using a private registry so fill in the details

**Result:**
Doesn't matter which namespace we select at step 2, it always reverts to the same one (the top of our list) after saving

**Environment information**
- Rancher version: 2.3.4
- Installation option: HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): On-prem, created with Rancher
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3 x VM with 4 x CPU/8GB RAM each
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by ncareau** [comment]
I have the same exact issue.

Environment information

    Rancher version: 2.3.4
    Installation option: HA

Kubernetes version :
`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`

Docker Version :
```
Client:
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Comment by iohenkies** [comment]
Howdy Rancher folks. Since we for security compliance need every app to have its own registry credentials (and every app has its own namespace), this is pretty important for us. Is this issue being addressed in the near future?
