### ISSUE TITLE
[feature] Display exposed port number of objects in UI along with IP address

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2554]
The Rancher web interface, when viewing Stacks, Hosts or Containers, should display any public-exposed port numbers next to the Service/Container in question, for reference.  It already displays the IP address nect to containers; I think the port number on containers (and the public port number on a Service/Load Balancer) is even more useful.

This will be particularly useful when randomly-assigned service ports becomes an option, as it makes the information immediately visible without having to click down into the object view to see it.

This could be displayed in the same section as the linked Service name on Load Balancers, for example.

**Comment by vincent99** [comment]
In next release:

![image](https://cloud.githubusercontent.com/assets/753917/11381455/72b6876c-92b9-11e5-96ed-c83e2e4c1082.png)

![image](https://cloud.githubusercontent.com/assets/753917/11381466/7e24c654-92b9-11e5-9d35-aa763f99cdca.png)
