### ISSUE TITLE
'Encrypt EBS Volume' in EC2 node template doesn't work on upgraded rancher set up

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/rancher#25546]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create rancher server version v2.3.5 and upgrade to v2.3-head
2. Add a node template for EC2 with encrypt EBS enabled.
3. Go to edit template or view in API

**Result:**
v3/schema doesn't have ```encryptEbsVolume": true``` object under ```amazonec2``` object.
UI in edit node template doesn't show encrypt EBS volume enabled.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):rancher-v2.3-head
- Installation option (single install/HA): Single

**Comment by dramich** [comment]
This is an issue with the version rancher-machine is outputting through `rancher-machine --version` and is not related to the new field.

**Comment by luthermonson** [comment]
https://github.com/rancher/machine/pull/69

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/25585
https://github.com/rancher/rancher/pull/25584

**Comment by khushboo-rancher** [comment]
Tested the fix, now It works fine in rancher version v2.3-head ```b5175db3f``` and master-head ```981263b53```
