### ISSUE TITLE
Multiple AD Hosts

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#25557]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Steps to reproduce (least amount of steps as possible):**

Similar to the request https://github.com/rancher/rancher/issues/21382 for LDAP, the user would like to be able to configure a list of multiple AD servers for authentication, such that auth requests failover in the event of an AD server being unavailable.

**Environment information**
- Rancher v2.3

**Comment by bemeyert** [comment]
We could use this feature too.

**Comment by ZeusThaBomb** [comment]
We could use this feature too.

**Comment by sevenval-admins** [comment]
We would be very interested to this feature too.
Can anyone please give us some feedback?

**Comment by dbrekau** [comment]
Are there any plans on this?

**Comment by mayrstefan** [comment]
From reading the code I would say internally this is already supported. I can see the config object has an attribute "servers" which is an array of strings. Also an API test case use a list of servers - with just one element. So this currently just might be a UI limitation.

**Comment by mayrstefan** [comment]
Reading more UI code my guess would be that hostname could already be a comma separated list of servers. Maybe just the documentation is missing

**Comment by mayrstefan** [comment]
I tried to intercept the request and made a list of multiple servers which gave me this result
`{"baseType":"error","code":"InvalidBodyContent","message":"multiple servers not yet supported","status":422,"type":"error"}`

Looking for this message I found https://github.com/rancher/rancher/blob/2708725597f29f23bea92828e34a1355085ad746/pkg/auth/providers/activedirectory/activedirectory_actions.go#L77-L79

This matches the TODO in https://github.com/rancher/rancher/blob/2708725597f29f23bea92828e34a1355085ad746/pkg/auth/providers/common/ldap/ldap_util.go#L42-L46

**Comment by mayrstefan** [comment]
I don't understand how the UI works. My guess would have been, that the UI should already split a comma separated list of hostnames into an array of servers. But it does not. It keeps the string as entered into the hostname field (e.g. "server1,server2,server3")

**Comment by mayrstefan** [comment]
My fault: rancher/ui already supported this by using a comma-separated list in the hostname field. But the current web ui is rancher/dashboard which does not. I also provided a pull request to restore this feature in the new ui.

**Comment by 24367dfa** [comment]
This might be solved by https://github.com/rancher/rancher/pull/37215
