### ISSUE TITLE
Support for launching Dashboard in airgap setups.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#25550]
Vue UI doesn't have the ability to be used in  airgap setups currently since we have it rendered from `https://releases.rancher.com/dashboard/latest/`. 
There is no option to bundle UI resources into the server container for a specific UI tag.

**Comment by vincent99** [comment]
It is intentionally setup this way, so that it can be updated as a an experimental feature outside of the normal long rancher release cycle.

**Comment by jiaqiluo** [comment]
Rancher `v2.4.0-rc3` air-gap HA on a k3s (`v1.17.3-alpha1+k3s1`) cluster.

Steps:
- add a custom cluster 
- go to the cluster page
- Click "Try Dashboard"

Results:
- two socket connections are created, but there is no data back from the server 

![image](https://user-images.githubusercontent.com/6218999/76712281-6dd50b80-66d4-11ea-89ba-ac4926dde818.png)

**Comment by UberKuber** [comment]
Is there any way to redirect this to something running in the air-gapped environment?

**Comment by sowmyav27** [comment]
Closing this issue as Dashboard is experimental in 2.4 and this is not an issue in 2.5.x
