### ISSUE TITLE
Validate 2.2 -> 2.4 upgrade

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25565]
Need to test the upgrade path from 2.2 to 2.4:

Scenario 1: 

Steps:
1) Install Rancher 2.2.10
2) Provision 3 RKE clusters with 3 different supported k8s versions in 2.2.10
   * 1.13.12, 1.14.8, 1.15.5
   * Add some pre-upgrade workloads
3) Upgrade to Rancher v2.4
4) Update all RKE clusters to latest k8s 1.15 
Scenario 2: 

Steps:
1) Install Rancher 2.2.10
2) Provision 3 RKE clusters with 3 different supported k8s versions in 2.2.10
   * 1.13.12, 1.14.8, 1.15.5
   * Add some pre-upgrade workloads
3) Upgrade to Rancher v2.4
4) Update all RKE clusters to latest k8s 1.17

**Comment by aaronRancher** [comment]
Scenario 1 passes with our existing automation and manual testing.

Steps:
Install Rancher 2.2.10
Provision 3 RKE clusters with 3 different supported k8s versions in 2.2.10
1.13.12, 1.14.8, 1.15.5
Add some pre-upgrade workloads. Run pre-upgrade automation.
Upgrade to Rancher `v2.4.0-rc2`
Update all RKE clusters to latest k8s 1.15
Run post-upgrade automation.

Scenario 2 upgrades are blocked by error:
![Screen Shot 2020-03-04 at 4 44 09 PM](https://user-images.githubusercontent.com/57409052/75933500-693c6780-5e37-11ea-9d11-c8616de35cee.png)
```
[controlPlane] Failed to upgrade Control Plane: [error during connect: Delete http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/rke-log-linker?force=1&v=1: failed to find Session for client c-fgnvb:m-d055a60deaf0]
```
This error appears when trying to update clusters to k8s `1.17.3-rancher1-2`

**Comment by aaronRancher** [comment]
Scenario 2 passes with our existing automation and manual testing.

Steps:
Install Rancher 2.2.10
Provision 3 RKE clusters with 3 different supported k8s versions in 2.2.10
1.13.12, 1.14.8, 1.15.5
Add some pre-upgrade workloads. Run pre-upgrade automation.
Upgrade to Rancher `v2.4.0-rc2`
Update all RKE clusters to latest k8s 1.17
Run post-upgrade automation.

Additional notes:
During k8s update, the cluster will be stuck updating for a few minutes with the following error:
![Screen Shot 2020-03-04 at 4 44 09 PM](https://user-images.githubusercontent.com/57409052/76014289-9429c880-5ed6-11ea-905d-fe33788f49bb.png)
The cluster eventually recovers and is accessable.

The `kre-kube-dns-addon-delete-job` workload in the cluster upgraded from 1.13.12 to 1.17 was not available after updating.
![Screen Shot 2020-03-04 at 5 07 10 PM](https://user-images.githubusercontent.com/57409052/76014325-a60b6b80-5ed6-11ea-96ae-0aea7e4965c6.png)
Error from pods:
![Screen Shot 2020-03-04 at 5 07 19 PM](https://user-images.githubusercontent.com/57409052/76014339-ae63a680-5ed6-11ea-9a92-f186fd96b137.png)

This workload does not recover.

**Comment by deniseschannon** [comment]
@aaronRancher @sangeethah I think we should review this upgrade path after the zero downtime cluster maintenance feature has been stabilized more. Just to ensure that the changes don't affect this upgrade path.

**Comment by aaronRancher** [comment]
Scenario 1 passes with our existing automation and manual testing.

Steps:
Install Rancher `2.2.10`
Provision 3 RKE clusters with 3 different supported k8s versions in `2.2.10`
`1.13.12`, `1.14.8`, `1.15.5`
Add some pre-upgrade workloads. Run pre-upgrade automation.
Upgrade to Rancher `v2.4.0-rc6`
Update all RKE clusters to latest k8s `1.15` (Used `v1.15.11-rancher1-2`)
Run post-upgrade automation.

Scenario 2 passes with our existing automation and manual testing.

Steps:
Install Rancher `2.2.10`
Provision 3 RKE clusters with 3 different supported k8s versions in `2.2.10`
`1.13.12`, `1.14.8`, `1.15.5`
Add some pre-upgrade workloads. Run pre-upgrade automation.
Upgrade to Rancher `v2.4.0-rc6`
Update all RKE clusters to latest k8s `1.17` (Used `v1.17.4-rancher1-2`)
Run post-upgrade automation.

Additional notes:
During k8s `1.17` update, the cluster will be stuck updating for a few minutes with the following error:
![image](https://user-images.githubusercontent.com/57409052/77110790-5e5f0680-69e3-11ea-8126-b6f291709708.png)
The cluster eventually recovers and is accessible.
