### ISSUE TITLE
Test new pipeline images

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#25577]
From rancher 2.4 we bumped rancher pipeline to use the latest images. 

Here are the images that need to be verified:
```
rancher/pipeline-jenkins-server: v0.1.4 -> v0.1.5
rancher/jenkins-jnlp-slave: 3.35-4 -> 3.40-1
rancher/minio-minio: RELEASE.2019-09-25T18-25-51Z -> RELEASE.2020-02-07T23-28-16Z
```

The rest of pipeline function should not be impacted.

Related docs: https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/pipelines/

**Comment by StrongMonkey** [comment]
Should be available to test in rancher master now.

**Comment by aaronRancher** [comment]
Tested in Rancher server `rancher\rancher:master-head` `version 7da8c22f9`
Running `pipeline-example-go` results in error 403.
![Screen Shot 2020-02-25 at 2 56 25 PM](https://user-images.githubusercontent.com/57409052/75293425-5e545800-57e3-11ea-855a-b6780b8bd446.png)
```
Create job got 403 403: <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 403 No valid crumb was included in the request</title> </head> <body><h2>HTTP ERROR 403</h2> <p>Problem accessing /createItem. Reason: <pre> No valid crumb was included in the request</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/> </body> </html>; ; create job got 403 403: <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 403 No valid crumb was included in the request</title> </head> <body><h2>HTTP ERROR 403</h2> <p>Problem accessing /createItem. Reason: <pre> No valid crumb was included in the request</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/> </body> </html>
```

**Comment by aaronRancher** [comment]
Verified images being used in `master-head` `version 7da8c22f9`
Minio
`"image": "rancher/minio-minio:RELEASE.2020-02-07T23-28-16Z"`
Jenkins
`"image": "rancher/pipeline-jenkins-server:v0.1.5"`

**Comment by aaronRancher** [comment]
Logs from the Jenkins container:
```
SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Declarative Extension Points API v1.5.1 (pipeline-model-extensions)
java.io.IOException: Pipeline: Declarative Extension Points API version 1.5.1 failed to load.
```

**Comment by StrongMonkey** [comment]
Caused by https://jenkins.io/doc/upgrade-guide/2.176/#SECURITY-626. Need to disable the setting or change our client to attach session cookies.

**Comment by deniseschannon** [comment]
Reverted the image changes for pipeline, so need to re-test that pipeline is still working.

**Comment by aaronRancher** [comment]
Tested on `rancher\rancher:master-head` `version 3623201ad`
Images used:
`rancher/pipeline-jenkins-server:v0.1.4`
`rancher/jenkins-jnlp-slave:3.35-4`
`rancher/minio-minio:RELEASE.2019-09-25T18-25-51Z`

Running example pipeline, `pipeline-example-go`, succeeds.
