### ISSUE TITLE
[feature request] Make "stack: {name}" clickable in a host-view

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2557]
Please do it!
<img width="325" alt="screenshot 2015-11-05 17 29 43" src="https://cloud.githubusercontent.com/assets/3070298/10971000/fd890c1a-83e2-11e5-9fa4-4d1d4824b0cc.png">

**Comment by vincent99** [comment]
For this (and #4328) you'll need to verify that the host screen is displayed correctly in general, the logic for how containers are grouped into stacks, their sidekicks or upgraded primary container, etc is all different.

**Comment by tfiduccia** [comment]
Version - master 12/30
Verified fixed
