### ISSUE TITLE
Modifying the Service port will cause Ingress to return 503 unavailable

### ISSUE THREAD

**Issue by MrYuanZhen** [rancher/rancher#25587]
### What kind of request is this
  * enhancement
### Environment information
 * Rancher 2.3.5 

### Steps to reproduce

    1.Create a workload；

    2.Create an ingress with the backend specified as the default generated service. At this time, the container port should default to 42.

    3.At this point, accessing the ingress should return a 502 error, then upgrade the workload and add a port of type ClusterIP, assuming 80.

    4.Then you can see that the default generated service type has been changed to ClusterIP and the port has also been changed to 80.

    5.By editing the ingress, you can see that the port of the back-end service has changed to 80. At this time, no changes are made to the ingress and saved directly. Theoretically it should be possible to access the service through ingress, but in fact it cannot be accessed.

    6.Through inspection, it was found that the backend port of the Ingress in the UI has changed, but in fact the content in the ingress yaml has not changed, and the container port is still 42.

This is very unfriendly. After modifying the port rules, the existing ingress cannot be used. If the user forgets to manually change and save it, the ingress will never be accessible.

---
* Ingress backend port in UI has changed
![image](https://user-images.githubusercontent.com/37647017/75309213-59e37a00-588b-11ea-9a75-21cd81d319fc.png)

* The actual ingress yaml file has not changed
![image](https://user-images.githubusercontent.com/37647017/75309263-84353780-588b-11ea-9958-549a1d303894.png)

**Comment by loganhz** [comment]
Fixed in 2.4 https://github.com/rancher/rancher/issues/23461
