### ISSUE TITLE
Test new kube-auth-api image

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#25581]
From rancher 2.4 kube-auth-api is updated to v0.1.4. This update only contains contains base image update and should not have real impact. 

Verify image changes:
rancher/kube-api-auth: v0.1.3 -> v0.1.4

Related docs: https://rancher.com/docs/rancher/v2.x/en/overview/architecture/#4-authorized-cluster-endpoint

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 981263b5

Fresh install:
* Deployed cluster
* `kube-api-auth` image is `rancher/kube-api-auth:v0.1.4`
* Cluster is functioning

Upgrade testing still needs to be performed.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 17a40f50

Fresh install of 2.2.8 in HA
* Deployed cluster
* `kube-api-auth` image is `rancher/kube-api-auth:v0.1.3`
* Cluster is functioning
* Upgrade to master-head
* kube-api-auth image is rancher/kube-api-auth:v0.1.4
* Cluster is functioning
