### ISSUE TITLE
Error: release: "rancher" not found

### ISSUE THREAD

**Issue by naveen230** [rancher/rancher#25580]
still having the issue when trying to upgrade rancher with new ssl certificates
"helm get values rancher" returns
Error: release: "rancher" not found

helm repo list returns
NAME URL
stable https://kubernetes-charts.storage.googleapis.com
local http://127.0.0.1:8879/charts
rancher-stable https://releases.rancher.com/server-charts/stable
jetstack https://charts.jetstack.io

helm version
Client: &version.Version{SemVer:"v2.16.2", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.2", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

**Comment by Cobra1978** [comment]
Same problem on a hosted cluster.

**Comment by Napsty** [comment]
Same problem here

```
$ helm repo list
NAME            URL                                              
stable          https://kubernetes-charts.storage.googleapis.com 
local           http://127.0.0.1:8879/charts                     
rancher-stable  https://releases.rancher.com/server-charts/stable

$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

$ helm get values rancher
Error: release: "rancher" not found
```
