### ISSUE TITLE
Better errors for cluster monitoring

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#25594]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

When calls regarding monitoring fail (for instance, https://github.com/rancher/rancher/blob/master/pkg/api/customization/monitor/prometheus_manager.go#L40), the popup with the error seen in Rancher shows:

```
failed to pick endpoint address
undefined
```

Which has no context on what is actually going on, we should improve the errors to give a better indication what it is related to and what is or could be the cause.

**Comment by saholman** [comment]
@superseb Any idea what this particular error means? I've been struggling to get monitoring setup, and I usually get 
> Failed to obtain metrics. The metrics service may not be available.
> undefined

But now I'm also getting 

> failed to pick endpoint address
> undefined

**Comment by miraculixx** [comment]
Observe the same as follows, this is 100% reproducible. Monitoring works fine otherwise.

Steps to reproduce:

1. select cluster & project
2. tools => alters
3. add alert rule or edit existing

The exact message appears:
![image](https://user-images.githubusercontent.com/859611/96332630-8724a880-1065-11eb-99a3-c8346bf61524.png)

The source is this request (hostname, cluster/project ids edited)

```
POST https://rancherhost/v3/monitormetrics?action=listprojectmetricname&limit=-1' 
{"projectId":"c-abcd5:p-wxyz5"}
=>
Status: 500
{"baseType":"error","code":"ServerError","message":"failed to pick endpoint address","status":500,"type":"error"}
```

**Comment by amagura** [comment]
I'm getting this, but I'm also getting when I try to deactivate a new alert.  
![image](https://user-images.githubusercontent.com/5353903/103564576-fdbe8e80-4e7b-11eb-87e6-c2e20f6056f1.png)

And if I deactivate an existing alert and try to reactive it, then I get this:  

![image](https://user-images.githubusercontent.com/5353903/103564656-247cc500-4e7c-11eb-919d-f6da60f8096f.png)
