### ISSUE TITLE
Specify another catalog to upgrade app to - helm chart repo deprecation

### ISSUE THREAD

**Issue by lwj5** [rancher/rancher#25592]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Launch an app from the catalog from helm-stable. Upgrade it. No option to upgrade to another chart in UI and CLI.

For example:
cattle-global-data:helm-redis -> cattle-global-data:bitnami-redis

Helm allows upgrading to another chart in another repository, rancher should allow it too.
helm install -n xx stable/xx
helm upgrade xx -n xx bitnami/xx

**Other details that may be helpful:**
With the deprecation of helm charts https://github.com/helm/charts#deprecation-timeline and delisting in May. The charts are moved to different repositories. There is no way to upgrade these current apps to the ones in the new repo in Rancher.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.3

- Installation option (single install/HA):
HA

**Comment by lwj5** [comment]
I found a workaround. 

If you are in rancher UI go to:
App > Options of the App you want to migrate > View in API > Upgrade

Put the replacement externalId.
For example, if the current externalId shown in the API is:

> catalog://?catalog=stable&template=redis&version=10.5.5

the replacement externalId will be:

> catalog://?catalog=bitnami&template=redis&version=10.5.5

**Comment by voarsh2** [comment]
Since Rancher 2.5, the Helm Apps is depreciated in 2.7 and can't manage them, so view in API is not available in 2.7... this is a valid issue still and should maybe be addressed?

**Comment by kyashwanth** [comment]
any update on how to achieve this?
