### ISSUE TITLE
Validate oldest and latest versions supported for GKE , EKS and AKS

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#25595]
Validate oldest and latest versions supported for GKE , EKS and AKS.

As part of validation , deploy each of the supported version and run automated validation runs.

**Comment by aaronRancher** [comment]
Validated the following k8s versions:
GKE `v1.15.7-gke.23` and `v1.15.9-gke.9`
AKS `v1.15.5` and `v1.15.7`
EKS `v1.14`
