### ISSUE TITLE
Kubectl access is not available when a cluster is upgrading

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25591]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster - 3 etcd, 2 control planes and 2 worker nodes. with k8s 1.15
- Copy the kubeconfig of the cluster for remote kubectl access.
- Run this command - ` while true; do sleep .1; kubectl get nodes ; done`
- upgrade k8s to 1.16 version
- While upgrade is in process, kubectl access is not available for few seconds during the upgrade of control plane

```
NAME            STATUS                     ROLES          AGE    VERSION
sowmya-ctrl-1   Ready                      controlplane   111m   v1.15.10
sowmya-ctrl-2   Ready,SchedulingDisabled   controlplane   111m   v1.15.10
sowmya-etcd-1   Ready                      etcd           62m    v1.15.10
sowmya-etcd-2   Ready                      etcd           111m   v1.15.10
sowmya-etcd-3   Ready                      etcd           111m   v1.15.10
sowmya-work-1   Ready                      worker         109m   v1.15.10
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes)
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes)
```

**Expected Result:**
kubectl access should be always available.

**Actual Result**
It is not available for a few seconds during the upgrade of control plane during cluster upgrade.

**Note:**
Kubectl access on the cluster in Rancher UI --> Also is disconnected during an upgrade

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest commit id: `c65f8705a`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.15 to 1.16
```

**Comment by mrajashree** [comment]
@sowmyav27 This was with a sleep of 0.1 seconds between the kubectl get command, can you also check with the sleep of 1 second? If it doesn't show those errors for a sleep of 1 second then we can't say it's not available for a few seconds

**Comment by sowmyav27** [comment]
Sleep of one second, there is one interrupt while doing a kubectl get nodes, but it recovers after

command - `while true; do sleep 1; kubectl get nodes ; done`
```
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes)
Error from server (Forbidden): users "user-drgx9" is forbidden: User "system:serviceaccount:cattle-system:kontainer-engine" cannot impersonate resource "users" in API group "" at the cluster scope
NAME            STATUS                     ROLES          AGE   VERSION
sowmya-ctrl-1   Ready                      controlplane   16h   v1.16.7
sowmya-ctrl-2   Ready,SchedulingDisabled   controlplane   16h   v1.16.7
sowmya-etcd-1   Ready                      etcd           15h   v1.16.7
sowmya-etcd-2   Ready                      etcd           16h   v1.16.7
sowmya-etcd-3   Ready                      etcd           16h   v1.16.7
sowmya-work-1   Ready                      worker         16h   v1.16.7
```

**Comment by maggieliu** [comment]
Talked to @cloudnautique and decided that this is acceptable.
