### ISSUE TITLE
Label - rke.cattle.io/ignore-during-upgrade added on the node is not editable

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25606]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Bring up a cluster - 3 etcd, 2 control plane and 2 worker nodes
- Add label `rke.cattle.io/ignore-during-upgrade=true` on the control plane node.
- The label on the node cannot be edited from the UI.
- It is currently editable only through the API

**Expected Result:**
The label should be editable on the UI.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - latest commit id: `1d21c437c`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.15
```

**Comment by mrajashree** [comment]
This can be edited through API, I don't know how to make it editable via UI

**Comment by Oats87** [comment]
@mrajashree What are you going to change the label name to?

**Comment by mrajashree** [comment]
The label is renamed to `user.cattle.io/upgrade-policy` and expected value of this label on node you want to ignore upgrade is `prevent`

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `f6872eb2c`**

**Steps:**

- Bring up a cluster - 1 etcd, 2 control plane and 2 worker nodes in k8s version 1.15 
- Power down one of the control plane nodes
- Modify the k8s version - to 1.16
- The cluster is stuck in Updating state with error: `ClusterController c-gljp6 [cluster-provisioner-controller] failed with : [controlPlane] Failed to upgrade Control Plane: cannot proceed with upgrade of controlplane since 1 host(s) cannot be reached prior to upgrade`
- Label the powered down control plane node as `user.cattle.io/upgrade-policy=prevent`.
- the reconcile on the cluster happens, but the cluster is still stuck in Updating state.
- `[controlPlane] Failed to upgrade Control Plane: cannot proceed with upgrade of controlplane since 1 host(s) cannot be reached prior to upgrade`

**Comment by sowmyav27** [comment]
Label has been renamed to `user.cattle.io/upgrade-policy=prevent` which can be edited on the UI

**Comment by sowmyav27** [comment]
**On master-head - commit id: `e74136aa5`**

**Steps:**

- Bring up a cluster - 1 etcd, 2 control plane and 2 worker nodes in k8s version 1.15
- Label one control plane C1 node as user.cattle.io/upgrade-policy=prevent
- Power down C1 node
- Modify the k8s version - to 1.16. Upgrade the cluster.
- The upgrade goes through.
- All the nodes' k8s upgrade to 1.16 except the powered down/labelled node.
