### ISSUE TITLE
Move GET calls to caches

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#25605]
Three more locations where API calls are being used and a cache is better need to be updated. 
As seen below this is thousands of calls to the API for objects. 
![Screen Shot 2020-02-26 at 4 13 22 PM](https://user-images.githubusercontent.com/13897607/75397186-7e534c80-58b3-11ea-9a35-17294070ac27.png)

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 9adb67c4f

* No way to easily test this so preformed regression testing through automation
* No unexpected failures
