### ISSUE TITLE
`service.selector.link` doesn't work with system label `io.rancher.stack_service.name`

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2560]
I have two services `backend/backend` and `frontend/frontend` in a separate stacks. Frontend is linked to the backend with `io.rancher.service.selector.link: io.rancher.stack_service.name=backend/backend`. Doesn't work.
If i define a custom label like `foo: bar` on the backend side, and add `io.rancher.service.selector.link: foo=bar` to frontend all work as expected.

**Comment by ndelitski** [comment]
To confirm that label is present:
<img width="635" alt="screenshot 2015-11-05 18 53 16" src="https://cloud.githubusercontent.com/assets/3070298/10973492/bb7073de-83ee-11e5-87b7-467d992c6f06.png">

**Comment by deniseschannon** [comment]
Service selector links only look at labels at the service level and not at the container level. 

In your use case, the system labels are only at the container level and not at the service level. If you added the `io.rancher.stack_service.name=backend/backend` when creating the service, your selector label would work.

**Comment by ndelitski** [comment]
hmm... for now i have to add custom label like `service_name: backend` and on the link side `link: service_name in (backend, rabbit)`. If I use `service_name: $${service_name}` would this work?
Is there an ability to customize dns names for auto-linked services?

**Comment by deniseschannon** [comment]
Yes, you must add a custom label. Using `service_name: $${service_name}` will not work. 

Please read through #2628 as your use case that you've been trying to handle should work.
