### ISSUE TITLE
Node which was ignored during an upgrade, has no way to upgrade automatically after cluster upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25610]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster - 7 nodes - 3 etcd, 2 control and 2 worker nodes with k8s version as 1.15
- Now Power off one  control plane node.
- upgrade k8s version to 1.16
- The cluster does not go thru upgrade as one control plane is not available. Error is seen on the cluster.
- Label the powered off control plane node as `rke.cattle.io/ignore-during-upgrade=true`
- The cluster will go through upgrade process.
- Now power on the control plane node and remove label `rke.cattle.io/ignore-during-upgrade=true`

**Expected Result:**
The powered on node should get upgraded automatically.

**Actual Result:**
The powered on node is not getting upgraded.  
**Question:** How can this be done? 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - latest commit id: 1d21c437c
- Installation option (single install/HA):single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.15 to 1.16
```

**Comment by mrajashree** [comment]
@sowmyav27 did you do another upgrade after powering on the node?

**Comment by sowmyav27** [comment]
@mrajashree verified the following steps too on latest master-head - commit id; `32f6f659c`

**Steps:**

- Deploy a cluster -  1 etcd, 3 control and 2 worker nodes with k8s version as 1.15
- Add label on one node N1 - `rke.cattle.io/ignore-during-upgrade=true`
- upgrade k8s version to 1.16
- The cluster goes through an upgrade process .
- The node N1 which had the label - `rke.cattle.io/ignore-during-upgrade=true`, k8s version does not get upgraded.
- Now remove label - `rke.cattle.io/ignore-during-upgrade=true` from the node N1.
- Do an edit of cluster, change the max_unavailable_controlplane = 2.
- The cluster goes into upgrading state.
- And the node N1 's k8s upgrade happens and changes to 1.16.
- While the other nodes remain in `Active` state.

**Comment by deniseschannon** [comment]
@mrajashree @kinarashah 

Discussed offline, that after a node label is removed, we do not expect the node to automatically get upgraded. Instead we should figure out a way to indicate that one of the nodes is in a different state than all the other nodes to indicate to the user that one of their nodes is not aligned with the rest of the nodes. 

We would expect the user to be able to then run the upgrade again to get the non-labeled node upgraded to match with the other nodes in the cluster. 

Is there something in the API that the UI can use to reflect this information?

**Comment by kinarashah** [comment]
@mrajashree @deniseschannon 

For etcd/controlplane nodes, I don't think rancher has a way of knowing this information, since it's RKE doing the upgrade. 
For worker nodes, the current behavior is removing the label would trigger would automatically ensure a cluster upgrade starts and node gets upgraded. 

We probably need to keep this behavior consistent, keeping this issue open to revisit later.

**Comment by deniseschannon** [comment]
@sowmyav27 With the design change to no longer allow ignoring control plane nodes during upgrade, I think we should close this issue. 

For the worker only node use case, let's wait until the design is completed before opening a new issue.

**Comment by sowmyav27** [comment]
Closing as per comments https://github.com/rancher/rancher/issues/25610#issuecomment-597446535
