### ISSUE TITLE
Cluster stuck in "Updating" state forever when trying to restore from Snapshot.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#25617]
Rancher server version - build from master - `776b0e457`

Steps to reproduce the problem:
Create a 3 node (all roles) cluster with K8s version - `1.15.10`
Deploy few workloads.
Take a snapshot - S1.
Upgrade K8s version of the cluster to - `1.16.7` and also set `service_node_port_range: 30000-32000` for kube-api server in `edit as yaml".
Deploy few workloads.

Restore Snapshot with "all" option. 
Cluster gets to "Updating" state and gets stuck in this state forever with following error message:
```
Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [<ip>]; Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [<ip>]
```

**Comment by deniseschannon** [comment]
@luthermonson Can you confirm that this has nothing to do with the new restore logic, but the actual "upgrade" logic for a cluster?

**Comment by deniseschannon** [comment]
This might be related: https://github.com/rancher/rancher/issues/25647

**Comment by luthermonson** [comment]
@deniseschannon all my chagnes are doing is storing information about the cluster and passing it to RKE and triggering a restore. I don't really know much about this, if you want me to look into it let me know but i'd be starting from zero.

**Comment by deniseschannon** [comment]
Thanks @luthermonson. This looks related to "upgrade" logic which would be @mrajashree and @kinarashah

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/25637 as the error message is the same.
