### ISSUE TITLE
Support EKS cn-northwest-1 and cn-north-1

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#25613]
Users should be able to create EKS clusters in cn-northwest-1 and cn-north-1 regions

**Comment by loganhz** [comment]
2.4 PRs

- https://github.com/rancher/kontainer-engine/pull/221
- https://github.com/rancher/ui/pull/3890

Master PRs

- https://github.com/rancher/kontainer-engine/pull/210
- https://github.com/rancher/ui/pull/3772

**Comment by loganhz** [comment]
https://github.com/rancher/rancher/pull/26522
https://github.com/rancher/rancher/pull/26523

**Comment by loganhz** [comment]
@kingsd041 Please validate EKS China and do some smoke test for EKS Global in `rancher/rancher:v2.3-head` and `rancher/rancher:master-head` after https://github.com/rancher/ui/pull/3890 and https://github.com/rancher/ui/pull/3772 merged.

**Comment by kingsd041** [comment]
Test Version:
- rancher/rancher:v2.4-head.   04/10     commit id: 63b2aa77b
- rancher/rancher:master-head    04/10     commit id: 419b87a70

The following EKS options were tested on `cn-northwest-1` and` cn-north-1` using `rancher/rancher:v2.4-head` and`rancher/rancher:master-head`:
- Kubernetes Version
- Service Role
- Public IP for Worker Nodes
- VPC & Subnet
- Instance Type
- Custom AMI Override
- Desired ASG Size
- Node Volume Size
- SSH Key
- EBS Encryption
- User Data
- Launch EKS cluster in `ca-central-1`

The clusters created with these options work well in my environment and pass the smoke test
