### ISSUE TITLE
Image Tag for Rancher v2.4.0-rc1 wrong in cattle-agent upgrade

### ISSUE THREAD

**Issue by pirminjanka** [rancher/rancher#25618]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Update Rancher Server to 2.4.0-rc1
2. Auto-Update of all rancher cattle-agents in k8s clusters fails because they pull image tag v2.4.0-rc1 and this does not exist... there is only the following image tag: rancher-agent:v2.4.0-rc1-linux-amd64

**Result:**
cattle-agents cannot be deployet

**Other details that may be helpful:**
You can manually edit the cattle-agent yaml and change the image tag to rancher-agent:v2.4.0-rc1-linux-amd64

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.0-rc1
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): GKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): 1.15.9-gke9

```
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.8-beta.0", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"archive", BuildDate:"2020-01-02T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.9", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T22:35:02Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
lient:
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.11.2
 Git commit:        74b1e89
 Built:             Fri Sep 27 06:20:54 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       74b1e89
  Built:            Fri Sep 27 06:19:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.8
  GitCommit:        a4bc1d432a2c33aa2eed37f338dceabb93641310
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683b971d9c3ef73f284f176672c44b448662
```

**Comment by superseb** [comment]
Thanks for the report, this was due to a build issue. Please see https://forums.rancher.com/c/announcements/ for announcements regarding new (preview) releases, RC releases are meant for internal testing.
