### ISSUE TITLE
Add helm version selection on catalog create

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#25627]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Helm Version selection**

- When adding a catalog, user needs to be able to set the helm version for that catalog
  - This should be set on create and user should be warned they cannot update it
  - This cannot be updated
- When selecting an app to deploy, user needs to see what version of helm that template is using
- When user is selecting a template version, user needs to see what version of helm that template version uses

**Comment by lvuch** [comment]
![helm-list](https://user-images.githubusercontent.com/3013118/75482563-4ce58a00-5962-11ea-9f02-c5c9030827ca.png)
![helm-launch](https://user-images.githubusercontent.com/3013118/75482566-4e16b700-5962-11ea-9291-e25032bd5748.png)

**Comment by jiaqiluo** [comment]
The enhancement is validated on Rancher master-head with latest UI 

Confirm that for both global and project catalogs:
- the helm version can be set when adding a catalog 
- the helm version can not be changed when editing the catalog 
- the helm v3 logo shows on the app deploying page

<img width="943" alt="Screen Shot 2020-03-06 at 11 43 02 AM" src="https://user-images.githubusercontent.com/6218999/76115899-34025780-5fa6-11ea-97ef-017b94b879f6.png">
<img width="1466" alt="Screen Shot 2020-03-06 at 12 29 45 PM" src="https://user-images.githubusercontent.com/6218999/76115909-3664b180-5fa6-11ea-849a-affe15c47613.png">

<img width="1505" alt="Screen Shot 2020-03-06 at 12 29 35 PM" src="https://user-images.githubusercontent.com/6218999/76115902-349aee00-5fa6-11ea-92a4-db462139cd96.png">

A bug is found during the validation 
https://github.com/rancher/rancher/issues/25832
