### ISSUE TITLE
AWS 0.4.0 AMI is not reachable through ssh

### ISSUE THREAD

**Issue by massimiliano-mantione** [rancher/rancher#2562]
I started an AWS EC2 instance using the rancheros-v0.4.0-hvm-0 (ami-175a6460) AMI (0.4.0, eu-west-1).
I can ping it but it does not allow ssh connections.

By comparison, an instance created exactly in the same way but starting from the rancheros-v0.3.3-hvm-1 (ami-e0b7f797) AMI works fine.

Any clues?

**Comment by deniseschannon** [comment]
Just to confirm, are you adding the AMI into the rancher server UI to launch an AWS EC2 instance? Or is this a general issue with launching rancheros in AWS EC2? What instance type did you use?

I tested starting all AMIs in all regions and being able to ssh into the AMI, but haven't tested it by launching it through rancher-server. 

Also, it seems like you're familiar, but just want to remind you that you need to use the `rancher` user.

**Comment by ndelitski** [comment]
Launched this AMI recently, had no problems. Also double-check your security group for opened port 22. And rancher user of course.

**Comment by massimiliano-mantione** [comment]
It was a general issue with launching rancheros in AWS EC2.
I was using the AWC web console to launch a t2.small in eu-west, with a security group that allows ssh on the public ip (and everything from our private subnet), and ssh into it with the rancher user.

I did it for both AMIs (rancher os 0.3.3 amd 0.4).
For some reason I could not ssh into the 0.4 one: it would refuse connections from everywhere (but I could ping it from the internal subnet).
I am convinced I created both instances in exactly the same way, but with hindsight I should have saved the output of "aws ec2 describe instances" of both, and compare them, to be extra sure.

I am writing in the past because right now I created another rancher 0.4 instance (a micro, but in the same way), and this time I can ssh into it.
Therefore I would close this issue.

That said, I then started rancher.io on the 3.3 instance and tried adding EC2 hosts from the web interface, but failed.
I did it in the most "just choose the defaults and specify as less as possible" way.
I don't know if it matters, but I did not even specify an AMI (I was even curious to see which AMI it would use!).

This is the log I see from the rancher container:

time="2015-11-05T22:25:06Z" level=info msg="Creating Machine" eventId="873ce174-d8c7-4406-bf64-acb9782ae625" resourceId=1ph2 
time="2015-11-05T22:25:06Z" level=info msg="Cmd slice: [create -d amazonec2 --amazonec2-access-key XXXXXXXXXXXXXXXX --amazonec2-instance-type t2.micro --amazonec2-private-address-only --amazonec2-region eu-west-1 --amazonec2-root-size 16 --amazonec2-secret-key YYYYYYYYYYYYYYYYYYYYY --amazonec2-subnet-id subnet-34346672 --amazonec2-vpc-id vpc-b88691da --amazonec2-zone a test-2]" 
time="2015-11-05T22:25:06Z" level=info msg="stdout: Creating CA: /var/lib/cattle/machine/24bd892f-7006-4b18-a73b-5ff07823efc9/certs/ca.pem" resourceId: =1ph2 
time="2015-11-05T22:25:08Z" level=info msg="stdout: Creating client certificate: /var/lib/cattle/machine/24bd892f-7006-4b18-a73b-5ff07823efc9/certs/cert.pem" resourceId: =1ph2 
time="2015-11-05T22:25:09Z" level=info msg="stdout: Launching instance..." resourceId: =1ph2 
time="2015-11-05T22:49:39Z" level=info msg="stderr: SSH cmd error!" resourceId=1ph2 
time="2015-11-05T22:49:39Z" level=info msg="stderr: command: sudo docker version" resourceId=1ph2 
time="2015-11-05T22:49:39Z" level=info msg="stderr: err    : exit status 1" resourceId=1ph2 
time="2015-11-05T22:49:39Z" level=info msg="stderr: output : sudo: docker: command not found" resourceId=1ph2 
time="2015-11-05T22:49:39Z" level=info msg="stderr: " resourceId=1ph2 
time="2015-11-05T22:49:39Z" level=info msg="starting cleanup..." machine name=test-2 
time="2015-11-05T22:49:40Z" level=info msg="cleanup successful" machine name=test-2 
time="2015-11-05T22:49:40Z" level=error msg="Error processing event" err="exit status 1" eventId="873ce174-d8c7-4406-bf64-acb9782ae625" eventName="physicalhost.create;handler=goMachineService" resourceId=1ph2 


Should we discuss this opening another issue or should we stay here?
Or are more general "I don't really understand how this is failing" questions better posted on the rancher forum?

**Comment by deniseschannon** [comment]
In Rancher server (that's what I'm assuming you mean by rancher.io), the UI defaults to whatever docker-machine defaults to. As you can see from the output from the server, we've just called a `docker-machine create` command to create the instance. The default for AWS (no AMI passed in) is an ubuntu image. 

This is definitely a separate issue and sounds more like something with the default image that docker-machine has tagged for AWS. 

https://docs.docker.com/machine/drivers/aws/

You can try to add in the RancherOS AMI and it should work. ;) Granted, I have yet to test our AMI in that region using Rancher, but I have created instances in all regions so I know they all work. 

I'm going to close this issue and if you have additional issues with getting an AWS instance in Rancher, please open a new one.
