### ISSUE TITLE
Worker node deleted and re-provisioned by Rancher after etcd/kubernetes restore

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25640]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Install Rancher 2.4 master-head used commit id: 9adb67c4f (02/27/2020)
- Configure a new cluster with S3 backups k8s version v1.15.10-rancher1-1
  - not sure if this is directly related but this was used in the test environment.
  - I used DigitalOcean to provision the nodes.
- Let Rancher create the first automatic snapshot and then trigger a new one.
- Update the cluster to Kubernetes v1.16.7-rancher1-1
- After the cluster is back to active trigger two backups.
- Update the cluster to Kubernetes v1.17.3-rancher1-1
- After the cluster is back to active trigger two backups.
- At this point there will be 6 backups in total 2 for each Kubernetes version in Rancher.
- Open `Restore Snapshot` and select the second snapshot created for Kubernetes v1.15.10-rancher1-1 from the dropdown
- Select the option `Restore etcd and Kubernetes Version - v1.15.10-rancher1-1`
- Click Restore

**Result:**

Once the restore is completed the Cluster was active but then Rancher triggered a node delete in one of the worker nodes:

```log
2020/02/27 21:04:54 [INFO] Finished restoring snapshot [c-82p5s-ms-z66s6_2020-02-27T20:55:04Z] on all etcd hosts
2020/02/27 21:04:54 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/02/27 21:04:59 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:37207
2020/02/27 21:04:59 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/02/27 21:04:59 [INFO] Provisioned cluster [c-82p5s]
2020/02/27 21:05:16 [INFO] Updating workload [ingress-nginx/nginx-ingress-controller] with public endpoints [[{"nodeName":"c-82p5s:m-rpwdg","addresses":["x.x.x.x"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-pfs6c","allNodes":false},{"nodeName":"c-82p5s:m-rpwdg","addresses":["x.x.x.x"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-pfs6c","allNodes":false}]]
2020/02/27 21:05:18 [INFO] Handling backend connection request [c-82p5s]
2020/02/27 21:05:19 [INFO] Updating workload [ingress-nginx/nginx-ingress-controller] with public endpoints [[{"nodeName":"c-82p5s:m-rpwdg","addresses":["x.x.x.x"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-pfs6c","allNodes":false},{"nodeName":"c-82p5s:m-rpwdg","addresses":["x.x.x.x"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-pfs6c","allNodes":false},{"nodeName":"c-82p5s:m-khsw6","addresses":["x.x.x.x"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-vfz92","allNodes":false},{"nodeName":"c-82p5s:m-khsw6","addresses":["x.x.x.x"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-vfz92","allNodes":false}]]
2020/02/27 21:05:27 [INFO] Deleted cluster node m-cng9k [izaac-do-test1-wrkr-1]
2020/02/27 21:05:27 [INFO] Removing node izaac-do-test1-wrkr-1
2020/02/27 21:05:27 [INFO] [node-controller-rancher-machine] About to remove izaac-do-test1-wrkr-1
2020/02/27 21:05:27 [INFO] [node-controller-rancher-machine] WARNING: This action will delete both local reference and remote instance.
2020/02/27 21:05:28 [INFO] Provisioning cluster [c-82p5s]
2020/02/27 21:05:28 [INFO] Updating cluster [c-82p5s]
2020/02/27 21:05:28 [INFO] [node-controller-rancher-machine] Successfully removed izaac-do-test1-wrkr-1
2020/02/27 21:05:28 [INFO] Removing node izaac-do-test1-wrkr-1 done
2020/02/27 21:05:28 [INFO] Creating jail for c-82p5s
2020/02/27 21:05:28 [INFO] Provisioning node izaac-do-test1-wrkr-1
```

**Other details that may be helpful:**

**Environment information**
- Rancher version: `2.4 master-head (02/27/2020)` commit id: 9adb67c4f
- Installation option (single install/HA): single

**Comment by luthermonson** [comment]
@sangeethah this is probably deep in nodesyncer and not related to the etcd restore process. i can look but should be a separate store and I don't feel it should be tied to the definition of done for etcd backup restore.

**Comment by deniseschannon** [comment]
@izaac Does this happen with every restore? Or just sometimes?

**Comment by izaac** [comment]
@deniseschannon so far  I was able to reproduce consistently with the `restoreRkeConfig='all'` scenarios

**Comment by izaac** [comment]
> @izaac Does this happen with every restore? Or just sometimes?

This happened to me once, it's not happening all the time so far hasn't happened to me again. But we decided to open the issue for tracking.

**Comment by izaac** [comment]
Closing, please open a new issue if this is still experienced on the latest Rancher release on RKE1 clusters.
