### ISSUE TITLE
Ignore zero downtime constraints during atomic rollback

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#25647]
With the introduction of zero downtime feature in 2.4, 
Upgrade on cluster will 
- consider only maxUnavailable nodes simultaneously
- do few prechecks, cordon/drain node, upgrade and uncordon the node back

We want to disable these extra steps during etcd restore action on the cluster. Restore flag is set on the rke config before restore operation (https://github.com/rancher/rancher/blob/master/pkg/api/customization/cluster/actions_etcd.go#L143) and gets reset back later (https://github.com/rancher/rancher/blob/master/pkg/controllers/management/clusterprovisioner/provisioner.go#L561) - so we should be able to rely on the same flag to check. 

https://github.com/rancher/rancher/issues/22232

**Comment by mrajashree** [comment]
It looks like RKE already handles this, because ClusterUp calls zero downtime upgrade logic based on the clusterState.CurrentState https://github.com/rancher/rke/blob/master/cmd/up.go#L148 
`RestoreEtcdSnapshot` before calling ClusterUp sets the CurrentState to nil and writes this to the statefile https://github.com/rancher/rke/blob/master/cmd/etcd.go#L136-L137
So the `reconcileCluster` flag never gets set to true and DeployControlPlane and DeployWorkerPlane don't call the functions that carry out zero downtime upgrades

**Comment by sowmyav27** [comment]
**Verified on latest master-head - comiit id: `888029fb0`**

**Steps:**

- Have a cluster - 1 etcd , 1 control plane and 5 worker nodes
- Max unavailable worker = 2, max Unavailable control = 1, drain = false
- take a snapshot
- Power down one worker plane node W1
- Upgrade k8s cluster from 1.16 to 1.17
- The cluster is stuck in upgrading state, as there is one worker node - powered down W1.
- other worker nodes get upgraded.
- restore to snapshot taken in Step 3.
- The powered down node is taken up for Upgrading, it is Cordoned. The node is then stuck in Cordoned state.
- one more node, worker node, is also stuck in cordoned state. 
- Cluster is stuck in Upgrading state 
- All worker nodes k8s version is 1.16
<img width="1281" alt="Screen Shot 2020-03-17 at 4 24 32 PM" src="https://user-images.githubusercontent.com/26032343/76910709-f934d500-686b-11ea-93f6-dd2e82efdcac.png">

**Comment by sowmyav27** [comment]
**Verified on master-head - latest - commit id: `0582d678c`**

1. Have a cluster - 1 etcd , 1 control plane and 5 worker nodes
2. Max unavailable worker = 2, max Unavailable control = 1, drain = false
3. take a snapshot
4. Power down one worker plane node W1
5. Upgrade k8s cluster from 1.16 to 1.17
6. The cluster is stuck in upgrading state, as there is one worker node - powered down W1.
7. other worker nodes get upgraded.
8. restore to snapshot taken in Step 3.
9. Cluster goes into "Updating" state. 
10. Cluster is restored to k8s 1.16 - on all the nodes.
11. W1 is seen momentarily go into Active state and then comes back to "Unavailable" state.
