### ISSUE TITLE
QUES: How do you git clone and run local?

### ISSUE THREAD

**Issue by joehoeller** [rancher/rancher#25649]
?

**Comment by joehoeller** [comment]
@gliptak @SvenDowideit @izaac @phillc

**Comment by izaac** [comment]
@joehoeller there's a wiki doc for this, let us know if this is what you are looking for.

https://github.com/rancher/rancher/wiki/Setting-Up-Rancher-2.0-Development-Environment

**Comment by joehoeller** [comment]
Does this work on Linux, or is the MacOS stuff ancillary info for “if I’m on a Mac”?

**Comment by izaac** [comment]
@joehoeller It should work, besides the OS X specific tools referenced in case you're in that platform everything else works even the IDE.

> This is primarily built on the premise of setting up in a MacOS environment, but most of it should carry over to linux as well.

**Comment by joehoeller** [comment]
Ok I’ll give it a go and follow up soon on a yay or nay or questions.

**Comment by joehoeller** [comment]
@izaac I think there is some disconnect here. I just want to git clone and run local with docker. Is that possible?
