### ISSUE TITLE
CIS scan does not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25642]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- on latest-master-head - commit id: `5e9cc17e8` and on 2.4.0-rc1
- Deploy a cluster - 1 node all roles- rke cluster or 1 etcd, 3 control and 2 worker nodes
- Go to Tools --> CIS Scan --> Run Scan
- The Scan report--> Running state and errors out

<img width="1575" alt="Screen Shot 2020-02-27 at 2 11 41 PM" src="https://user-images.githubusercontent.com/26032343/75491640-182a0080-596b-11ea-841e-7777f9de22a1.png">

**Expected Result:**
Scan should run and reports should be generated on the cluster successfully.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `5e9cc17e8` and on 2.4.0-rc1
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.15.10
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by leodotcloud** [comment]
Once this PR (https://github.com/rancher/rancher/pull/25475) gets merged, things will work.

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `f6872eb2c`**

- Run scan on a cluster.
- Pod: security-scan-runner is in `Unavailable` state with error: `ImagePullBackOff: Back-off pulling image "rancher/security-scan:v0.1.7"`
- Scan is stuck in `Running` state

**Comment by deniseschannon** [comment]
@sowmyav27 the `rancher/security-scan:v0.1.7` is now available in Dockerhub.

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `f6872eb2c`**

- Run scan on a cluster.
- Able to run CIS scan on the cluster
- Scan Report is generated is seen Active
