### ISSUE TITLE
Labels not showing up for cloned host

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2565]
Version - reskin master

Steps:
1.  Create a host/machine with a label
2.  Clone host/machine

Results:
Notice that the label is missing

Expected:
Cloned hosts should have same labels available

**Comment by ebr** [comment]
This also happens for cloned or upgraded services, as well as containers.

**Comment by deniseschannon** [comment]
@ebr What labels are you talking about? Any label prefixed with `io.rancher` isn't cloned. There is an issue to clone the ones that make sense.

https://github.com/rancher/rancher/issues/2342

**Comment by ebr** [comment]
@deniseschannon thanks for linking the existing issue - yes, i am specifically talking about `io.rancher.container.pull_image`. Wanted to report it as a bug, found this issue via search. In light of #2342, please ignore my previous comment :)

**Comment by tfiduccia** [comment]
Version - master UI 3/17
Verified fixed
