### ISSUE TITLE
exec shell and view logs for pods dont work in steve enabled setup from rancher UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25650]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On master-head commit id: `32f6f659c`, deploy cluster. 
- Enable Steve from Settings --> Feature flags --> Steve --> Enable/Activate
- deploy some workloads
- Do a View Logs and Exec shell into pods
- "Closed Code: 1006" error is seen -- on exec shell
- And View logs is Disconnected.
- Error seen in console: `failed: Error during WebSocket handshake: Unexpected response code: 500`

**Expected Result:**
View logs and exec shell should work 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `32f6f659c`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): do-rke
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by sowmyav27** [comment]
Remote kubectl - exec shell fails
``` 
kubectl exec -it wk01-54bc5f97b4-97crh bash
error: unable to upgrade connection: malformed HTTP response "\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x04\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x04\x00\x04\x00\x00"
```

**Comment by sowmyav27** [comment]
**Verified on latest master - commit id: `fd4f14d35`**

- Deploy one node cluster
- Steve is enabled by default.
- exec shell and view logs do not work
- remote kubectl also does not work
```
kubectl exec -it wk01-67f85cb965-7k4dd bash
error: unable to upgrade connection: malformed HTTP response "\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x04\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x04\x00\x04\x00\x00"
```

**Comment by jiaqiluo** [comment]
The same bug exists in the master-head 2e6041d75

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `17a40f502`**

- Exec shell and View logs work from Rancher UI
- Kubectl exec works from Rancher UI

```
kubectl exec -it wk01-78cc9b575-nk2rs bash
root@wk01-78cc9b575-nk2rs:/# cd data
```
