### ISSUE TITLE
Show AKS/EKS/GKE region info in cluster dashboard

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#25656]
Rancher 2.3

Now users can only see the EKS region info in `Edit Cluster` page. 

We should show EKS region info in cluster dashboard. Same for GKE and AKS.

![image](https://user-images.githubusercontent.com/21168270/75549960-ccab4b80-5a6b-11ea-90c6-13c1296774c0.png)
![image](https://user-images.githubusercontent.com/21168270/75549986-da60d100-5a6b-11ea-9197-067bf52018db.png)
![image](https://user-images.githubusercontent.com/21168270/75550163-43e0df80-5a6c-11ea-885d-ebe44f5998dd.png)
![image](https://user-images.githubusercontent.com/21168270/75550193-5824dc80-5a6c-11ea-9393-d4c9d810f47e.png)

**Comment by soumyalj** [comment]
Tested with master-head build (ea9700b41)
Created AKS, EKS and GKE clusters in the setup. 
The dashboard in each of the clusters hows the region information as below:

AKS cluster:

![Screen Shot 2020-04-06 at 9 08 52 PM](https://user-images.githubusercontent.com/18536626/78629240-4d1f5200-784b-11ea-8de6-cfedea973aeb.png)

GKE cluster

![Screen Shot 2020-04-06 at 9 12 45 PM](https://user-images.githubusercontent.com/18536626/78629343-97083800-784b-11ea-9daf-91fc17dc666e.png)

EKS Cluster

![Screen Shot 2020-04-06 at 9 14 07 PM](https://user-images.githubusercontent.com/18536626/78629356-a2f3fa00-784b-11ea-80cb-21accf7523f2.png)

**Comment by soumyalj** [comment]
Tested with v2.4-head build (0ebc44347)
Created AKS, EKS and GKE clusters in the setup.
The dashboard in each of the clusters hows the region information as below:
**EKS Cluster**
![Screen Shot 2020-04-07 at 10 24 34 AM](https://user-images.githubusercontent.com/18536626/78700254-0452b200-78ba-11ea-8b25-07572a81e2a0.png)

**GKE Cluster**
![Screen Shot 2020-04-07 at 10 24 27 AM](https://user-images.githubusercontent.com/18536626/78700281-0a489300-78ba-11ea-8df4-9fd26ed026b2.png)

**AKS Cluster**
![Screen Shot 2020-04-07 at 10 24 12 AM](https://user-images.githubusercontent.com/18536626/78700303-0fa5dd80-78ba-11ea-99b8-b3b4e8b64623.png)
