### ISSUE TITLE
rancher-helm: upgrade to latest helm 2

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#25663]
upgrade rancher-helm to the most recent helm 2 version

**Comment by dramich** [comment]
Helm was uplifted to 2.16.3, no changes should be noticed with this uplift

**Comment by jiaqiluo** [comment]
the following tests are passed in master-head 17a40f502
- deploy all apps from the builtin catalog 
- deploy/upgrade/rollback/delete WordPress app from the catalog

**Comment by jiaqiluo** [comment]
the following tests for Multi-Cluster Apps are passed in master-head 17a40f5

- provision two clusters  
- deploy WordPress app into two projects in those two clusters
- upgrade/rollback/delete the WordPress app
