### ISSUE TITLE
Helm-Unittest failures due to api limit

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#25660]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Run drone build
-OR-
curl https://api.github.com/repos/$PROJECT_GH/releases/latest a few times

**Result:**
See dapper step `rancher-helm plugin install https://github.com/rancher/helm-unittest` fail occasionally
-OR-
`{
  "message": "API rate limit exceeded for <ip>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}`

**Example Drone Failure** 
https://drone-pr.rancher.io/rancher/rancher/7332/2/2

**Comment by jiaqiluo** [comment]
wait for https://github.com/rancher/rancher/pull/25740 to be merged.

**Comment by brendarearden** [comment]
fix is working in master and 2.3 branches as both builds passed successfully and continue to pass.
