### ISSUE TITLE
Backing off failure, delay: 30s while restoring backup using restoreRkeConfig = all

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25664]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Install Rancher `2.4 master-head (02/28/2020)` commit id: e59944099
2. Create a cluster with K8s version V1. Create few workloads in the cluster. 
  a.  DigitalOcean used as provisioner (1 etcd, 1 controlplane, 3 worker nodes)
  b.  Kubernetes version used: `v1.15.10-rancher1-1`
  c. S3 backups enabled
3. Initiate a backup B1
4. Edit cluster and change kubelet args on the cluster . Create few workloads.
5. Restore to backup B1 with restoreRkeConfig = "all" UI: `etcd, Kubernetes Version and cluster config`

**Result:**

UI shows an error message but the restore backup eventually succeeds.

`Backing off failure, delay: 30s; backing off failure, delay: 30s`

<img width="965" alt="Screen Shot 2020-02-28 at 10 20 59 AM" src="https://user-images.githubusercontent.com/27659/75570722-fb4a0780-5a14-11ea-8c84-d5ac0c58465c.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version: `2.4 master-head (02/28/2020)` commit id: e59944099
- Installation option (single install/HA): single

**Comment by luthermonson** [comment]
@sangeethah i dont feel this is a bug related to etcd restore, ultimately the cluster comes back according to @izaac and seems like this is standard backoff. i can look more but i dont feel it should be tied to the etcd restore store

**Comment by deniseschannon** [comment]
@izaac Does the cluster eventually become green and active? Is the issue that during updating, it shows when we hit a failure and turns red?

**Comment by izaac** [comment]
@deniseschannon  It's not pretty clear to me what exactly triggers this error message in the UI as the Rancher server log doesn't show any error.

But yes this error appears and the restore eventually succeeds. The cluster turns active and no more errors are shown in the UI.
