### ISSUE TITLE
If missing required field for Services, the Create button stays dimmed and says Saving...

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2567]
Version - Master with reskin UI

Steps:
1.  Add Service
2.  Don't put in a Name and click on Create

Results:
The Create button dims and it says Saving... So I can no longer create service.

Expected:
The button should go back to active and say Create.  All other Adds work this way.

**Comment by deniseschannon** [comment]
Duplicate of #2566. Just found it in my training today. ;)
