### ISSUE TITLE
[ui] Rename field maxUnavailable for cluster upgrade strategy

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#25670]
* MaxUnavailable field has been replaced by 2 new fields: MaxUnavailableWorker and MaxUnavailableControlplane
* The current field shown in UI MaxUnavailable should be renamed to MaxUnavailableWorker
* MaxUnavailableControlplane should not be exposed in the UI
* Schema changes for this are merged in rancher master
Without this change, UI sends value for maxUnavailable in the request instead of these two fields
<img width="610" alt="Screen Shot 2020-02-28 at 12 23 10 PM" src="https://user-images.githubusercontent.com/10672776/75585453-03ab3e00-5a27-11ea-9e79-5f2b2ffe7888.png">

The request should contain `max_unavailable_worker` which corresponds to current maxUnavailable in UI, and `max_unavailable_controlplane`

**Comment by sowmyav27** [comment]
**Verified on master-head latest - ui tag: latest2**

create a cluster, with default upgrade strategy values.
Request sends the following params 
```
upgradeStrategy: {maxUnavailableWorker: "", drain: false, nodeDrainInput: null, maxUnavailableUnit: "count"}
maxUnavailableWorker: ""
drain: false
nodeDrainInput: null
maxUnavailableUnit: "count"
```

**Comment by sowmyav27** [comment]
**Verified on latest master-head commit id: `c921ba250` - UI tag: latest2**

- Default values when creating a cluster (values sent in the request):
```
maxUnavailableControlplane: "1"
maxUnavailableWorker: "10%"
drain: true
nodeDrainInput: {deleteLocalData: false, force: false, gracePeriod: -1, ignoreDaemonSets: true, timeout: 60,…}
maxUnavailableUnit: "percentage"
```
- Edit of cluster does NOT reset the maxUnavailableControlplane of the cluster.
- Drain being set to True by default -- issue being tracker here -- https://github.com/rancher/rancher/issues/25732
