### ISSUE TITLE
Refresh on API Keys page gives a path api response

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25675]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Navigate to API & Keys page on rancher UI - latest master-head
- Refresh the page.

**Expected Result:**
Refresh on the page should list the page of API &Keys.

**Actual Result:**
- Refresh on API Keys page gives a path api response
<img width="602" alt="Screen Shot 2020-02-28 at 2 07 07 PM" src="https://user-images.githubusercontent.com/26032343/75591152-db760c00-5a33-11ea-839b-f0808b2d1c87.png">
- Status code of the request - https://<rancher-server>/apikeys - GET gives 40

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Comment by vincent99** [comment]
Presumably the route for `/api` isn't checking for end-of-string or followed by `/`, so it matches any URL starting with `/api`.  This has probably been around forever..

**Comment by cbron** [comment]
I checked 2.3.5 and it doesn't happen there.

**Comment by cbron** [comment]
Found issue: https://github.com/rancher/steve/blob/6dafed731f412f2fd334acf0a870032a8ed1ffff/pkg/server/router/router.go#L37

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `3623201ad`**

- Navigate to API & Keys page on rancher UI - latest master-head
- Refresh the page.
- Refresh on the page lists the page of API &Keys.
