### ISSUE TITLE
Menu overlap on small screen

### ISSUE THREAD

**Issue by diansaji** [rancher/rancher#25686]
Every now and then i work on rancher from my phone. im having trouble on accessing  menus because it overlaping each other. From the Global menu i can only see Cluster, the project can be search but cannot be selected due to the overlap with another project and the interface below. I hope someone can fix this.
![Screenshot_2020-03-01-09-43-12-609_com android chrome](https://user-images.githubusercontent.com/39397553/75618446-1fd2ea80-5ba1-11ea-82c2-92a5a6a45c88.jpg)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.5` UI: `v2.3.36` |
|Route|`global-admin.clusters.index`|

**Comment by ChrML** [comment]
+1 on this. It's near impossible to access the cluster UI on a phone to view for example workload statuses.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/27183
