### ISSUE TITLE
DNS error when attaching a PV on vSphere

### ISSUE THREAD

**Issue by mfbrj** [rancher/rancher#25682]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- pgadmin installed through Apps was working fine and accessing a existing PV on vSphere.
- I scale down the workload to 0 to rename vmdk from ugly name `kubernetes-dynamic-pvc-266c3e63-ec40-4153-ab5e-0e0785f968c6.vmdk` to `pgadmin.vmdk`.
- Vmdk file was successfully renamed in vSphere and PV and PVC were successfully reconfigured in Rancher UI.
- When I scale up the workload to 1, UI shows the error below:

**Result:**
```
AttachVolume.Attach failed for volume "pgadmin" : Post https://vcshomolog.tre-pa.jus.br:443/sdk: dial tcp: lookup vcshomolog.tre-pa.jus.br on [::1]:53: read udp [::1]:43003->[::1]:53: read: connection refused
```

**Other details that may be helpful:**
- `vcshomolog.tre-pa.jus.br` is my vCenter
- Despite this DNS error, Rancher UI can successfully create new nodes on that vSphere
- `nslookup` from `busybox:1.28.4` in both `local` and `downstream` clusters resolves `vcshomolog.tre-pa.jus.br` fine.
- Creating new volumes from Rancher UI stucks on Pending state

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere 6.5 on premise
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-12T13:43:46Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by fredbeltrao** [comment]
What Rancher component is responsible for this message? It's not shown in the Rancher logs.

`AttachVolume.Attach failed for volume "pgadmin" : Post https://vcshomolog.tre-pa.jus.br:443/sdk: dial tcp: lookup vcshomolog.tre-pa.jus.br on [::1]:53: read udp [::1]:43003->[::1]:53: read: connection refused`

**Comment by fredbeltrao** [comment]
I don't now why or how, but problem was SOLVED when I deleted and recreate the underlying StorageClass.
