### ISSUE TITLE
Add Customizable Header/Footer/'Classification Banners' to Rancher UI

### ISSUE THREAD

**Issue by bgulla** [rancher/rancher#25694]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
Many government organizations require CSS banners be implemented on government-hosted websites indicating that the webapp is accredited for a certain environment. These header/footers are typically solid ~25px floating-horizontal boxes with centered white text surrounding the web pages. The Header/Footer combo are typically implemented via CSS and configurable at the server level only, (not per user). Ideally, Rancher server would have a new 'Advanced Option' that would either one of the following options:
 - Option 1 (more user friendly): Header/Footer Option with form fields for foreground, background and custom text. 
 - Option 2 (more customizable): Header/Footer CSS/HTML Option with single form field where users could paste in direct CSS/HTML that would be added as header/footers.

**Result:**
These header/footers would add another layer of visibility to the user indicating the classification level or even broader announcement to all rancher-server users (example: THIS SYSTEM WILL BE UPGRADED FRIDAY 1700EST). 

**Other details that may be helpful:**
Guide for implementing classification banners:
https://www.patternfly.org/v3/pattern-library/communication/classification-banner/index.html

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
rancher/rancher

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): N/A
- Machine type (cloud/VM/metal) and specifications (CPU/memory): N/A
- Kubernetes version (use `kubectl version`): N/A

```
(paste the output here)
```

- Docker version (use `docker version`):
N/A
```
(paste the output here)
```

**Comment by vincent99** [comment]
#1 is fine with options for header/footer text/color/bg/whatever. 
  - You presumably want it available on the login page so it needs to be a setting and added as one of the settings that are available without authentication.
  - There's no API call to get a list of all the public settings at once, so multiple separate settings is impractical...  Save a single setting with a JSON blob in it.
  - Text content can be markdown if you want to support links, pass it through DOMPurify after rendering.
  -Would be simpler if there's just a few standard color choices (info, warning, error/alert).  Picking color codes doesn't fit very well with multiple themes, most specific color codes won't work well in both.

#2: Noo... arbitrary CSS/JS/HTML injection and the ability to break the page are bad.

**Comment by maggieliu** [comment]
Example of the banner on other app:

<img width="999" alt="Screen Shot 2020-03-25 at 5 11 08 PM" src="https://user-images.githubusercontent.com/2137556/77597301-a71f2f80-6ebb-11ea-80aa-ddb546580234.png">

**Comment by westlywright** [comment]
@deniseschannon @maggieliu For option 1 to proceed we'll need some back end work to happen. We'll need a new public setting as per Vince's comment. Even though this is fairly small change I think there should be some discussion around the API setting and the feature. The implementation details are pretty fuzzy.

**Comment by vincent99** [comment]
While they're in the neighborhood the Dashboard could use a Steve-style way to access the public settings rather than trying to determine if the installation has Rancher or not, calling out to old /v3, and having no support for settings in standalone mode.

I'd like it to return the whole collection of them instead of making N separate calls, and for the list of settings that are public to itself be a setting so that future entries don't need to be wait on API changes.

**Comment by westlywright** [comment]
From the meeting:

A single new public api will be added and will be called `ui-banners`
The new api will accept a json blob with the following shape, all field types are strings. Its fine if param names need to change.
```
{
  header: {
    foreground,
    background,
    text
  },
  footer: {
    foreground,
    background,
    text
  },
}
```

**Comment by westlywright** [comment]
There is one bug right now where the banners are not working on the login page. This actually seems to be stemming from an ember issue but I am still investigating. I will open a separate bug to track this issue. Currently the banners should be present on all the logged in pages.

**Comment by aaronRancher** [comment]
The feature is verified with Rancher server `rancher\rancher:master-head` `version cc64610a8` and `rancher\rancher:v2.4-head` `version d27bbf11a`

Settings for ui-banner has been added:
![Screen Shot 2020-04-22 at 4 11 07 PM](https://user-images.githubusercontent.com/57409052/80042513-10429480-84b4-11ea-8a88-ff8173d6aabb.png)
Banner header is seen:
![Screen Shot 2020-04-22 at 4 11 23 PM](https://user-images.githubusercontent.com/57409052/80042536-26505500-84b4-11ea-815e-d512ae205a10.png)
Banner footer is seen:
![Screen Shot 2020-04-22 at 4 11 39 PM](https://user-images.githubusercontent.com/57409052/80042532-23556480-84b4-11ea-971b-4205ede9e765.png)

**Comment by zbialik** [comment]
FYI, running a DELETE request to /v3/settings/ui-banners not only deletes the current config for it, but it also removes everything under /v3/settings... not sure if bug or what but right after running that DELETE request, you can no longer see anything in Settings of UI (cause that section of API is gone). 

To remedy, just redeploy the rancher workload to restore the unharmed API.

**Comment by zbialik** [comment]
Is there any plan or possibility of getting a different message for the Header and Footer?
