### ISSUE TITLE
Tiny dots and Grouped view for Stacks is not functioning

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2569]
Version - Master with reskin UI

Steps:
1.  Go into a Stack details view
2.  Create multiple services inside a stack (make sure some have sidekicks)
3.  Click on Tiny Dots and Grouped sidekicks icons

Results:
Nothing happens, they all look like the container view.

**Comment by vincent99** [comment]
Fixed, these will be getting replaced with table view though.

**Comment by tfiduccia** [comment]
Verified fixed - Master with newest reskin
Tiny dot and Group view removed.
