### ISSUE TITLE
Able to start a container without passing any networkIds

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#257]
Version -V0.12.1

Using APIs , I am able to start a container without passing  networkIds param( I passed only imageUuid and name). In this case container has no ipaddress assigned to it. 
In such cases , we expect API to default to Managed network.

HTTP/1.1 POST /v1/containers
Host: <host ipaddress>
Accept: application/json
Content-Type: application/json
Content-Length: 330
{
"imageUuid": "docker:nginx",
"name": "test5",
"networkIds": [ ],
"ports": [ ],
"startOnCreate": true,
"commandArgs": [ ],
"publishAllPorts": false,
"privileged": false,
"capAdd": [ ],
"capDrop": [ ],
"dns": [ ],
"dnsSearch": [ ],
"stdinOpen": false,
"tty": false,
"entryPoint": [ ],
"restartPolicy": null,
"devices": [ ],
"dataVolumes": [ ],
"dataVolumesFrom": [ ],
}
HTTP Response:
HTTP/1.1 201
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-API-Schemas: http://<ip address>:8080/v1/schemas
Server: Jetty(8.1.11.v20130520)
X-API-Client-IP: 50.255.37.17
Content-Length: 2309
Content-Type: application/json; charset=utf-8

{
"id": "1i14",
"type": "container",
"links": {
"self": "…/v1/containers/1i14",
"account": "…/v1/containers/1i14/account",
"credentials": "…/v1/containers/1i14/credentials",
"hosts": "…/v1/containers/1i14/hosts",
"instanceLinks": "…/v1/containers/1i14/instancelinks",
"loadBalancerTargets": "…/v1/containers/1i14/loadbalancertargets",
"mounts": "…/v1/containers/1i14/mounts",
"ports": "…/v1/containers/1i14/ports",
"targetInstanceLinks": "…/v1/containers/1i14/targetinstancelinks",
"volumes": "…/v1/containers/1i14/volumes",
"stats": "…/v1/containers/1i14/stats",
},
"actions": {
"remove": "…/v1/containers/1i14/?action=remove",
"start": "…/v1/containers/1i14/?action=start",
"logs": "…/v1/containers/1i14/?action=logs",
},
"name": "test5",
"state": "creating",
"accountId": "1a1",
"agentId": null,
"allocationState": "inactive",
"capAdd": [ ],
"capDrop": [ ],
"command": null,
"commandArgs": [ ],
"cpuSet": null,
"cpuShares": null,
"created": "2015-03-18T22:39:48Z",
"createdTS": 1426718388000,
"data": {
"fields": {
"imageUuid": "docker:nginx",
"publishAllPorts": false,
"startOnCreate": true,
"dns": [ ],
"dnsSearch": [ ],
"stdinOpen": false,
"ports": [ ],
"commandArgs": [ ],
"networkIds": [ ],
"entryPoint": [ ],
"capAdd": [ ],
"dataVolumesFrom": [ ],
"tty": false,
"capDrop": [ ],
"dataVolumes": [ ],
"restartPolicy": null,
"privileged": false,
"devices": [ ],
},
},
"dataVolumes": [ ],
"dataVolumesFrom": [ ],
"description": null,
"devices": [ ],
"directory": null,
"dns": [ ],
"dnsSearch": [ ],
"domainName": null,
"entryPoint": [ ],
"environment": null,
"firstRunning": null,
"hostname": null,
"imageUuid": "docker:nginx",
"kind": "container",
"lxcConf": null,
"memory": null,
"memorySwap": null,
"networkIds": [ ],
"ports": [ ],
"primaryIpAddress": null,
"privileged": false,
"publishAllPorts": false,
"registryCredentialId": null,
"removeTime": null,
"removed": null,
"requestedHostId": null,
"restartPolicy": null,
"startOnCreate": true,
"stdinOpen": false,
"systemContainer": null,
"token": null,
"transitioning": "yes",
"transitioningMessage": "In Progress",
"transitioningProgress": null,
"tty": false,
"user": null,
"uuid": "7b023fb1-eb7b-4db2-bea8-29c1a486660c",
}

**Comment by vincent99** [comment]
This is now `networkMode` and not relevant..
