### ISSUE TITLE
Add Windows 1909 Agent Build

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#25706]
We have 1809 and 1903 agent builds, a 1909 was released and we should probably add it to our drone.yaml for continued up to date windows agent support.

**Comment by SSvilen** [comment]
Would Windows 1909 be only in version 2.4 supported? Or do you plan to build images also for older versions - like 2.3.6 for instance?

**Comment by maggieliu** [comment]
@SSvilen The issue for 2.3 line is tracked here: https://github.com/rancher/rancher/issues/27002.

**Comment by sowmyav27** [comment]
**Validated on master-head - commit id: `924e56374`**

- On running the register command on a windows 1909 node, node does NOT register
```
>docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS               NAMES
6ee9372a87ba        rancher/hyperkube:v1.17.6-rancher2       "pwsh -NoLogo -NonIn…"   8 minutes ago       Up 8 minutes                            kube-proxy
212311383b3a        rancher/hyperkube:v1.17.6-rancher2       "pwsh -NoLogo -NonIn…"   9 minutes ago       Up 9 minutes                            kubelet
ff42a4416074        rancher/rancher-agent:master-3159-head   "pwsh -NoLogo -NonIn…"   11 minutes ago      Up 11 minutes                           elastic_mclaren
```

**Comment by sowmyav27** [comment]
**Verified on 2.4-head - commit id: `4269f6124`**

- Deployed a windows 1909 cluster - 2 linux worker nodes, 2 windows worker nodes, ami - `Windows_Server-1909-English-Core-Base-2020.05.13 (ami-0258598f8dae94743)`
- Basic checks - workload deployment, ingress, nodeport, dns - works fine

**Comment by sowmyav27** [comment]
**Validated on 2.4.5-rc5**

**Scenario#1**

- Add a windows cluster - 1 node all roles, linux, add 1 windows 1909 worker node
- Cluster is good, Node agent windows is up and active
- Add another windows worker node
- Second windows node failed to register - service side kick container keeps restarting
- Existing Node agent windows has an issue on the cluster now

**Scenario#2**

- Add a windows cluster - 1 node all roles, linux, add 1 windows 1909 worker node
- Cluster is good, Node agent windows is up and active
- Add another windows worker node
- Second windows node registered
- Node agent windows - on the newly added node, does not come up. Kube-proxy keep restarting-
**Logs:**
```
INFO: Waiting for servcie-sidekick to prepare the entrypoint.ps1 ...
FATA: Could not get vxlan0 HNS network: FATA[2020-06-12T23:35:48Z] rpc error: code = InvalidArgument desc = could not get HNS network vxlan0 via v2 api: Network Id  not found
INFO: Waiting for servcie-sidekick to prepare the entrypoint.ps1 ...
FATA: Could not get vxlan0 HNS network: FATA[2020-06-12T23:36:05Z] rpc error: code = InvalidArgument desc = could not get HNS network vxlan0 via v2 api: Network Id  not found
INFO: Waiting for servcie-sidekick to prepare the entrypoint.ps1 ...
FATA: Could not get vxlan0 HNS network: FATA[2020-06-12T23:36:21Z] rpc error: code = InvalidArgument desc = could not get HNS network vxlan0 via v2 api: Network Id  not found
INFO: Waiting for servcie-sidekick to prepare the entrypoint.ps1 ...
```

**Comment by luthermonson** [comment]
hopefully fixing 1909 failures since upgrading to flannel v0.12.0 https://github.com/rancher/rke-tools/pull/96

**Comment by sowmyav27** [comment]
**Validated on `2.4.6-rc2`**

**Steps:**

- Add a windows cluster - 3 linux nodes - 1 etcd, 1 control plane, 1 worker nodes, 
- 1 windows node gets registered
- Two other windows nodes fail to register
- Existing Node agent windows has an issue on the cluster - keeps recreating

**Comment by sowmyav27** [comment]
**Tested on 2.4-head - commit id: `fb2c5fb2d`**

- Deploy a windows cluster, run register command on two windows worker nodes with NO nodename override
- docker inspect of service-sidekick on the node that is registered successfully
```
"Env": [
                "RKE_CLUSTER_CIDR=10.42.0.0/16",
                "RKE_CLUSTER_DOMAIN=cluster.local",
                "RKE_CLUSTER_DNS_SERVER=<>",
                "RKE_CLUSTER_SERVICE_CIDR=10.43.0.0/16",
                "RKE_NODE_ADDRESS=ip-1",
                "RKE_NODE_INTERNAL_ADDRESS=priv-ip-1",
                "RKE_CLOUD_PROVIDER_NAME=",
                "RKE_NODE_NAME_OVERRIDE=ec2amaz-l8hl3mp",
```
- docker inspect of service-sidekick on the node that is NOT registered successfully
```
"Env": [
                "RKE_CLUSTER_CIDR=10.42.0.0/16",
                "RKE_CLUSTER_DOMAIN=cluster.local",
                "RKE_CLUSTER_DNS_SERVER=<>",
                "RKE_CLUSTER_SERVICE_CIDR=10.43.0.0/16",
                "RKE_NODE_ADDRESS=ip-1",
                "RKE_NODE_INTERNAL_ADDRESS=priv-ip-1",
                "RKE_CLOUD_PROVIDER_NAME=",
                "RKE_NODE_NAME_OVERRIDE=ec2amaz-l8hl3mp",
```
- Same nodename override and node address is available.
- When the windows nodes were registered WITH nodename override, 2 windows 1909 nodes are registered successfully in the cluster.

**Comment by sowmyav27** [comment]
**Validated on 2.4-head - commit id: `f210f54bd`, 2.5-head commit id: `b72284720` and master-head - commit id: `e90c401815`**

- Deployed windows cluster - 1 linux all roles and 2 windows worker nodes (windows 1909 `Windows_Server-1909-English-Core-Base-2020.10.14` - AMI from AWS)
- Cluster was deployed successfully.
- All windows nodes registered.
- Validation checks on the clusters passed (automation)
