### ISSUE TITLE
Drop share-mnt process

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#25702]
Share-mnt process is the container we ran to make some directories shared in order for kubelet container to propagate mounts. Since we are starting kubelet with rshared volumes, container will fail to start if mountpoint is not rshared. Since most of OSs today mount their root dir as shared, it is not needed anymore.(It previously only applied for boot2docker, which is not supported in our matrix anymore). This issue tracks the work to drop share-mnt container.

Things to be noticed:
We still need share-mnt container to be run in order to write certs into rancherOS. Only the actual share-mnt process needs to be dropped.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head bcc8261

Fresh installs - 

* Fresh install in HA
* Create an RKE cluster
  * Cluster & node agents do not have `share-mnt` binary (exec shell into agent and `share-mnt`, and no container is running
* Create RKE ROS cluster
  * Deploys successfully
* Automation runs successfully against both clusters

**Comment by soumyalj** [comment]
Tested with upgrade from v2.4.0 to master-head(bcc8261487ecd)

Steps:

- Created RKE DO  and ROS clusters in v2.4.0
- Cluster and node agents had the share-mnt binary
- Upgraded to Rancher to master-head
- Verified that share-mnt binary does not exist in the cluster and node agents

```
root@cattle-cluster-agent-59d4c7f5fd-zggjf:/var/lib/rancher# share-mnt --help
bash: share-mnt: command not found
root@cattle-cluster-agent-59d4c7f5fd-zggjf:/var/lib/rancher# 
```

```
root@soumyarostest3:/var/lib/rancher# share-mnt --help
bash: share-mnt: command not found
root@soumyarostest3:/var/lib/rancher# 

```
- Basic automation runs succeed on the clusters
