### ISSUE TITLE
[UI] Kontainer engine schemas where 'Update':'False' should be respected

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#25708]
The Rancher UI for Kontainer-engine drivers should respect schemas with the field update set to `False`. 

For example, after this [PR](https://github.com/rancher/rancher/pull/25707) is merged, the subnets field cannot be edited on EKS clusters. The UI should not allow these fields to be edited.

Part of fixing https://github.com/rancher/rancher/issues/24652

**Comment by cbron** [comment]
@rancher-max is this issue already fixed by  https://github.com/rancher/rancher/issues/26231#event-3169853091 ? Looks like it.

**Comment by rancher-max** [comment]
This should be fixed for EKS, but I'm not sure if this issue specifically applies for all clusters. If so, then it might still need to be fixed for RKE, GKE, and AKS clusters as well.

**Comment by cbron** [comment]
This one was specifically targeted at EKS clusters, going to close as duplicate.
