### ISSUE TITLE
Cannot start any containers

### ISSUE THREAD

**Issue by amalagaura** [rancher/rancher#2571]
I am running into this same issue with the latest Rancher and a latest docker. I have two hosts which get connected to the server.

Getting these in the agent log when trying to start a container from Rancher: `Container locked. Can't run StartHandler`

> Component	Version
> Rancher	v0.44.0
> Cattle	v0.107.0
> User Interface	v0.65.0
> Rancher Compose	v0.5.1

Docker version 1.9.0, build 76d6bc9

**Comment by deniseschannon** [comment]
What OS are you using?

**Comment by deniseschannon** [comment]
Also, what is your setup? Your other comment was on a multinode setup.

**Comment by amalagaura** [comment]
Yes sorry I remembered afterwards that I forgot to mention it is running Centos 7.1

It is a multinode with two hosts. They connect fine and I can view non-Rancher containers if I try that. Other networking is fine if I do a test. The networking container also starts up.

Is 1.9 officially supported? I am thinking to use RancherOS since they will be dedicated for Rancher.

**Comment by amalagaura** [comment]
I just tried moving to 1.8 and it still failed. Are there known issues with Centos 7.1? I had installed the yum packages docker-engine (1.9) and docker (1.8).

It is running the server on one of the hosts. I add the other host to rancher but it cannot launch containers. They get stuck in the "Networking" state with docker 1.9 and docker 1.8.

Will Ubuntu work better? I would like to use RancherOS but can't since the OS needs to run some KVM containers.

**Comment by amalagaura** [comment]
Urgh, this is very frustrating. I installed on Ubuntu and am having the same problem.

On the rancher-agent log I am repeatedly getting 
```
time="2015-11-06T19:16:59Z" level="info" msg="Container locked. Can't run StartHandler. ID: []" 
```

Still running the same versions as when I tried on CentOS

Now running:  Ubuntu 14.04.3 LTS with Docker version 1.9.0, build 76d6bc9

This is starting from scratch, just trying to get Rancher working but cannot launch any containers

**Comment by amalagaura** [comment]
@deniseschannon I installed nsenter, restarted the agent and still no success

**Comment by deniseschannon** [comment]
This is strange as I am able to start up Rancher server using v0.44.0 using Ubuntu 14.04.3 (in GCE). I have a server with 2 hosts and they are all able to start containers with no issues. I am running Docker 1.9. 

I haven't tried testing with CentOS yet.

**Comment by deniseschannon** [comment]
Can you do a couple of tests for me? 

1. Are you able to launch other containers on your host using the docker command line? 
2. Have you tried with a single node setup? Single Rancher server to see if you can add your 2 hosts and are able to launch containers?
3. When you say internal IPs, what does that mean? 

Have you looked at the troubleshooting docs to see if everything is set up correctly? Just go through the list of issues to see if anything pertains to you. I'm not exactly sure what's wrong with your setup. 

http://docs.rancher.com/rancher/faqs/troubleshooting/

**Comment by amalagaura** [comment]
Thank you for trying this out. I am stumped too. I have used docker for a few months so this is really confusing why it doesn't work.

I am trying with a single host again by nuking docker and removing /var/lib/rancher/state and using the exact commands from the quickstart guide. I still get the exact same thing. 

* I am starting the rancher server with ` docker run -d --restart=always -p 8080:8080 rancher/server`
* going to the UI, copy pasting the custom host,  
* waiting for the host to appear, then doing "add container" in the UI, 
* Two containers appear, "Network Agent" goes through some steps and succeeds
* The container that I try to add gets stuck on "Networking"
* Checking the log on the host shows `msg="Container locked. Can't run StartHandler. ID:` and `nsenter: cannot open /proc/9229/ns/ipc: No such file or directory` as the only two errors

1. I can launch other containers and they have internet access and I can see them on the Rancher UI
2. I am just trying single node now. I started the server 
3. Internal IP's means these servers are behind a firewall with non-internet accessible IP's. They can go out to the internet. They have private IPs and can communicate to each other. But for the single node that doesn't matter.

I went through the FAQ but do not find anything. On Monday I am going to try on fresh Amazon EC2 instances. If needed I can screencast it but I am following the instructions exactly.

**Comment by amalagaura** [comment]
I tried one more thing. I apt-get removed apparmor from Ubuntu and rebooted. It still did not help. I thought that might have been the issue.

In the server I am getting this error:

` [nsenter: failed to execute /var/lib/cattle/events/config.update: No such file or directory`

**Comment by amalagaura** [comment]
Looking at issue #1442 I tried using only the IP and no DNS, but it did not help. The same errors

**Comment by deniseschannon** [comment]
@amalagaura I'm curious if you had time to try this out today as we haven't had any other users having issues launching containers with Docker 1.9 and Rancher.

**Comment by amalagaura** [comment]
Sorry I did not get to it today but I will do it first thing tomorrow morning and report here. My plan is to use Amazon EC2 and a standard Ubuntu instance and just a single node. If it works I will use `dpkg` and compare the installed packages on the working and non working systems. I can't understand how I tried two different systems it doesn't work.

**Comment by amalagaura** [comment]
I just tried it on EC2 and it worked.

It must be an issue with the VM I am getting from my provider. This is a list of installed packages. It is different from the EC2 packages.

Here is the list of installed packages on each: https://gist.github.com/amalagaura/00c72728774f424c4072

I am going to ask my VM provider in our company what was done special to create the VM. I don't see any xwindows graphical desktop packages. I may just have to do the testing elsewhere.

**Comment by amalagaura** [comment]
OK you can disregard the list of installed packages. I used `apt-clone` to make both systems have the exact same installed packages.

So my system has the same packages as a default ec2 system. I then restarted the system, removed the docker directory, and I have the same problem.

What else can I look at or do? The people who provided the VM to me say there is nothing special about it. 

```
uname -a
Linux staging-1.c01.infrdev.com 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by deniseschannon** [comment]
What do you mean by "removed the docker directory"?

**Comment by amalagaura** [comment]
To clear the system I uninstalled docker and then `rm -rf /var/lib/docker` . When you restart docker it recreates that directory. The point is there are no old images or containers, it downloads and creates them new.

I don't think that is relevant because this happens on a brand new system. 

The main thing that would be helpful is how to diagnose the error message: 
```
msg="Container locked. Can't run StartHandler. ID: 
```

It is from this line https://github.com/rancher/host-api/blob/master/events/start_handler.go#L82 but I don't know what is causing this on the system.

**Comment by cloudnautique** [comment]
@amalagaura, when you wipe a node clean, you also need to clean out the /var/lib/rancher/state directory. Its possible you have old state that is no longer reconcilable.

**Comment by amalagaura** [comment]
@cloudnautique I have been removing that directory too. I found that out when I was unable to readd an agent and searched the issues here.

**Comment by ibuildthecloud** [comment]
@amalagaura I'm just now looking at this thread.  "Container locked. Can't run StartHandler. ID:" unfortunately is not an error.  It is quite normal to see that message.  We can probably change it to not sound so bad.  Also "nsenter: cannot open /proc/9142/ns/ipc: No such file or directory" is not really that bad either.  That error can happen if a container starts and dies at the right time.

So on a single host, does a container forever get stuck in "Networking"?  Let not even do cross host networking, based on your past comments it sounds like a single host doesn't even come up properly (ignoring the Container locked message, which isn't really an error)

**Comment by amalagaura** [comment]
Thank you for the message. It looked like the message was waiting for a lock to clear which was not happening.

Yes I am only on a single host right now. A container started gets stuck in "Networking" (But not the Networking Agent container). I can start containers from the command line without Rancher without a problem.

I have tried it in Centos and Ubuntu and it is happening on the VMs provided by the corporate resources. I don't know how the machines are different from the one on EC2.

**Comment by amalagaura** [comment]
@ibuildthecloud @deniseschannon Any suggestions for me? I am stuck on what to do or try after I synced packages to what EC2 had. What other settings on the server might be relevant?

**Comment by andyshinn** [comment]
I think I'm running into the same issue as well. I cannot start containers after moving my Rancher server to a new Docker 1.9.0 host. The containers are stuck in *Networking*. The `rancher-compose up` is stuck at:

```
INFO[0000] Creating stack smil                          
INFO[0000] Creating service taskscheduler          
INFO[0001] Project [smil]: Starting project             
INFO[0001] [0/1] [taskscheduler]: Starting
```

`cattle-error.log` has a lot of:

```
2015-11-11 16:26:07,567 ERROR [:] [] [] [] [cutorService-10] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [nsenter: cannot open /proc/26179/ns/pid: No such file or directory
] 
2015-11-11 16:26:23,565 ERROR [:] [] [] [] [ecutorService-7] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [nsenter: cannot open /proc/26179/ns/pid: No such file or directory
]
```

Which from previous comments appear to be harmless. The `cattle-debug.log` is pretty large. Any relevant logs I can give to help troubleshoot?

**Comment by amalagaura** [comment]
@andyshinn I had the problem with 1.8 also. You should give more details of your current host. OS, etc.

**Comment by andyshinn** [comment]
I'm running:

```
Rancher: v0.44.0
Cattle: v0.107.0
User Interface: v0.65.0
Rancher Compose: v0.5.1
Docker: 1.9.0
Ubuntu: 14.04.3
```

**Comment by amalagaura** [comment]
@ibuildthecloud @deniseschannon Any update? We have another user @andyshinn reporting the same issue and we are both ready to assist to troubleshoot this.

**Comment by deniseschannon** [comment]
I think @andyshinn is having a different issue as he had upgraded an existing setup. Have you been able to resolve your issues after you moved your Rancher server? As mentioned in your other threads, I've never tried it. :)

@amalagaura It sounds as if you aren't even able to get it up and running. Let's summarize what the issue is as the thread is getting quite lengthy. 

1. Start VM using either CentOS 7.1 or Ubuntu 14.04.3
2. Run Rancher-Server `docker run -d --restart=always -p 8080:8080 rancher/server`
3. Add single node (can you confim if this is the same or separate VM)?
4. Add container through UI
5. Network Agent container succeeds
6. The added container is stuck in `Networking`

The steps above work for EC2, but not for the VM from your provider. 

What container image are you trying to run? Have you tried different ones? Do they all go into networking?

Are there any images pre-pulled on your VM? If you pre-pull the image on the host and then launch, does the container start okay?

**Comment by andyshinn** [comment]
No, it is still unresolved. Since I am only testing, I'll tear down the server and agents and start fresh and see if I can reproduce. I've already tried new agents (Docker 1.8.x) on the Rancher server (Docker 1.9.0) and they fail as well. I'll post some logs if still happening with a fresh server.

**Comment by cloudnautique** [comment]
@andyshinn if the name or IP changed in the host move.. you might need to go the host registration tab in admin to reset it.

**Comment by amalagaura** [comment]
@deniseschannon Your summary is correct. To answer your questions

>Add single node (can you confim if this is the same or separate VM)?

It is on the same VM as the server.

>What container image are you trying to run? Have you tried different ones? Do they all go into networking?

>Are there any images pre-pulled on your VM? If you pre-pull the image on the host and then launch, does the container start okay?

I tried a few different ones, but I have just been checking ubuntu:latest mainly. I did try prepulling using `sudo docker pull ubuntu:latest` but it does not change anything on the rancher ui when I try again.

**Comment by deniseschannon** [comment]
Since you're running Rancher hosts on the same VM as the Rancher server, I'm assuming the host is showing the correct IP? If not, you can read about how to set the correct IP when launching on the [same VM](http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#samehost).

So even if you pull the image on the host and then try to start a service or container using the image, it will get stuck in `Networking`? Have you tried with both standalone containers (using the `+ Container` on the host as well as the Add Service section on the Applications page)?

**Comment by amalagaura** [comment]
@deniseschannon The host was showing the internal docker bridge IP by default but I did use those instructions to correct it. It did not make a difference.

Currently the IP's displayed on the UI are:
Host: 10.42.1.21
Rancher-server container: 172.17.0.2
Network container: 10.42.101.123

Actually I think this is probably the problem. I don't think that is a correct IP for the network container.

This is the results of ifconfig
>eth0  inet addr:10.42.1.21  Bcast:10.42.255.255  Mask:255.255.0.0
>docker0  inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0 


>So even if you pull the image on the host and then try to start a service or container using the image, it will get stuck in Networking? Have you tried with both standalone containers (using the + Container on the host as well as the Add Service section on the Applications page)?

Yes, yes and yes

**Comment by deniseschannon** [comment]
Okay, now that you've shared your IP of the host, I believe that may be the cause of the issue. We use the `10.42.x.x` as part of the managed overlay network.

Can you follow the instructions to changing the subnet and then create a new environment, add a host and try to launch a container?

http://docs.rancher.com/rancher/faqs/#subnet

**Comment by amalagaura** [comment]
@deniseschannon Thank you. It was just bad luck on our part for our corporate network resources and I didn't notice that the network container was on the same subnet. I will change that on Monday and try it out. It would be nice if rancher would check it, but I guess it is a rare case.

**Comment by amalagaura** [comment]
@deniseschannon OK I followed instructions on that page to change the subnet CIDR. Then I even rebooted but it is still not working. Attached are screenshots.

<img width="379" alt="screen shot 2015-11-16 at 12 34 12" src="https://cloud.githubusercontent.com/assets/498234/11189484/583f0ce4-8c5e-11e5-8355-00b7d3ec7f01.png">

<img width="295" alt="screen shot 2015-11-16 at 12 33 12" src="https://cloud.githubusercontent.com/assets/498234/11189469/40abbc9e-8c5e-11e5-9d33-8a40fd636539.png">

**Comment by amalagaura** [comment]
@deniseschannon Hang on, I guess 10.250.0.0/16 is not a private subnet. 10.10.0.0/16 is marked as private. 10.250.0.0/16 might be internet accessible. So I am not sure what to put for the new subnet. I will play around more with it.

**Comment by deniseschannon** [comment]
@amalagaura Did you create a new environment? That is the only way it will trigger using the new subnet.

**Comment by amalagaura** [comment]
OK Sorry I did not understand environment. I thought it was referring to a stack.

**Comment by amalagaura** [comment]
@deniseschannon OK I cleared the environment and it worked! The container started up. Thank you for being patient with me and working with me on the troubleshooting. Going to start moving our docker-compose containers over to Rancher now!
