### ISSUE TITLE
Error when log out then try to log back in to Rancher UI

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#25714]
Version: master-head (3/2/2020) `d8e28c62d`

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Log in to Rancher. Log out.
- Try to log back in.

**Result:**
Error in UI:
![image](https://user-images.githubusercontent.com/45179589/75726309-54c56700-5c9f-11ea-9600-65e6656cb5c6.png)

Error in dev console:
```
Uncaught TypeError: Cannot read property 'type' of undefined
    at setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)
```

Followed by 422 error on POST to /v3-public/localProviders/local?action=login
with a response body like:
```
{baseType: "error", code: "InvalidCSRFToken", message: "Invalid CSRF token", status: 422,…}
baseType: "error"
code: "InvalidCSRFToken"
message: "Invalid CSRF token"
status: 422
type: "error"
```

**Other details that may be helpful:**
Able to log in on second attempt. A couple other QA have mentioned sometimes takes them a 3rd try until they can actually log back in.
Was careful to test in "incognito mode" so we have a clean cache, etc.

**Environment information**
- Single node rancher was tested in my case. It probably wouldn't make a difference if this was HA or single-node rancher.

**Comment by davidnuzik** [comment]
It's worth noting that this probably isn't a priority. I think we should fix it, but that it's not critical for 2.4.0.
This is because the issue will only happen if you keep your tab/window open and try to log back in. I believe that in most situations when someone logs out (if they log out at all) they will probably then close their tab/window or navigate to another URL.

As long as you do that and open a new tab/window (even in same browser session) the issue won't happen. This only happens if you follow the steps in your same browser tab/window. As soon as you close the tab and try to log in again everything is fine.

**Comment by kingsd041** [comment]
The same problem exists in `rancher/rancher:2.3.6-rc5`

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-2401-head` `version 0519da989`

Able to log out and log back in as admin, standard user, and user-base.
