### ISSUE TITLE
User is not able to access the rancher server URL in the first try after launching the server

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25716]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Bring up a rancher server - latest `master-head` command used: `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:master-head`
- Go to the URL - https://<rancher-server-ip>
- Warning: `Your connection is not private` is seen 
- Click on Advanced --> proceed ( Chrome web page)
- The server fails to load.
- Refresh the browser.
- Warning: `Your connection is not private` is seen 
- Click on Advanced --> proceed ( Chrome web page)
- Now the user will be redirected to `https://<rancher-server-ip>/update-password` page

**Note:**
This happens even after there is considerable time between docker run command of the rancher server and accessing the webpage with the URL - https://<rancher-server-ip> (approx 10 mins after)

**Expected Result:**
The user should NOT login to the rancher server the second time. User should be redirected to `https://<rancher-server-ip>/update-password` in the first try

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `d8e28c62d`
- Installation option (single install/HA): single

**Comment by davidnuzik** [comment]
I did some more tests with this today. I agree the amount of time you wait before login does not matter. I can wait for a very very long time, then attempt the first log in and see this issue. It's only upon me attempting to accept the self-signed cert in my browser that I then see these entries in the Rancher server log:

```
2020/03/03 20:14:14 [INFO] Updating TLS secret for serving-cert (count: 4): map[listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.2:172.17.0.2 listener.cattle.io/cn-REDACTED_RANCHER_IP:REDACTED_RANCHER_IP listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:715b4eedd9462e33096a92f74459f8d5467968b8f8200eb08994314480ecb5ad]
2020/03/03 20:14:14 [INFO] Active TLS secret serving-cert (ver=4068) (count 4): map[listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.2:172.17.0.2 listener.cattle.io/cn-REDACTED_RANCHER_IP:REDACTED_RANCHER_IP listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:715b4eedd9462e33096a92f74459f8d5467968b8f8200eb08994314480ecb5ad]
2020/03/03 20:14:14 [INFO] Active TLS secret serving-cert (ver=4068) (count 4): map[listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.2:172.17.0.2 listener.cattle.io/cn-REDACTED_RANCHER_IP:REDACTED_RANCHER_IP listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:715b4eedd9462e33096a92f74459f8d5467968b8f8200eb08994314480ecb5ad]
```

Only after these entries are seen in the log can we then attempt to acceess the rancher server UI (i.e. our 2nd attempt). It's as if this action needs to happen much sooner but does not until it is triggered by the user via first attempt to accept risk of self-signed cert in the browser (and thus initiate first connection with rancher server).

**Comment by sangeethah** [comment]
This issue is seen in rancher server version `v2.4.0-rc3`

```
2020/03/12 04:43:20 [INFO] Updating TLS secret for serving-cert (count: 4): map[listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.2:172.17.0.2 listener.cattle.io/cn-45.56.92.36:45.56.92.36 listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:8800ec04355f5ef0eaa1d3339434fce6797df0a7caa67d8b19023fa5aa860de9]
2020/03/12 04:43:20 [INFO] Active TLS secret serving-cert (ver=2878) (count 4): map[listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.2:172.17.0.2 listener.cattle.io/cn-45.56.92.36:45.56.92.36 listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:8800ec04355f5ef0eaa1d3339434fce6797df0a7caa67d8b19023fa5aa860de9]
2020/03/12 04:43:20 [INFO] Active TLS secret serving-cert (ver=2878) (count 4): map[listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.2:172.17.0.2 listener.cattle.io/cn-45.56.92.36:45.56.92.36 listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:8800ec04355f5ef0eaa1d3339434fce6797df0a7caa67d8b19023fa5aa860de9]
I0312 04:44:29.844648      21 controller.go:606] quota admission added evaluator for: preferences.management.cattle.io
```

**Comment by sowmyav27** [comment]
**Verified on latest master-head build. - commit id: `56d69e236`**

- Able to login to rancher in the first attempt

- Do not see this in the logs anymore
```
[INFO] Active TLS secret serving-cert (ver=1494) (count 4): map[listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.2:172.17.0.2 listener.cattle.io/cn-173.255.242.109:173.255.242.109 listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:b7b3e58c63c0c81d22e77cbf8db55283495fabfd7073f3af39f84bd9e2783ad1]
```
