### ISSUE TITLE
Folder icon in front of environment name in drop-down disappears when selected

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2572]
Version - Master with reskin UI

Steps:
1.  Create an additional environment
2.  Click on Environments drop-down on upper-right (notice the folder icon besides newly created environment)
3.  Click on Environment to select it.

Results:
The folder icon disappears.

Expected:
Since the little home icon stays when you select that particular environment, seems like the folder icon should as well.

**Comment by vincent99** [comment]
Wrong icon name when showing the not-default environment.

**Comment by tfiduccia** [comment]
Verified fixed - Master with newest reskin
