### ISSUE TITLE
[UI] Update UI to use revised API functionality for k3s upgrade

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#25720]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Explanation:**
1. A new API has been introduced to channelserver, `/v1-releases/releases`
The data looks like the following:
![image](https://user-images.githubusercontent.com/19376037/75732049-9d385100-5cae-11ea-8c61-2835504e1a8a.png)
 2. K3sConfig has been updated to make version a string instead of a struct of strings 

The list has already been filtered, so all releases shown are available. UI can ignore minChannelServerVersion and maxChannelServerVersion.

Backend PR: https://github.com/rancher/channelserver/pull/3
 
**Desired:**
1. UI should use the releases api to determine which k3s release are available.
2. The UI should use a string for the version. The UI should also not set a version on K3Config when a cluster is imported. A non-existent string on K3sConfig.Version indicates that the cluster is "unmanaged" and may be used in the future. Version should only be set _by the UI_ when a user attempts to upgrade a cluster.

**Comment by sangeethah** [comment]
Tested with latest build from master - `25f16c370`

When editing an imported cluster (in my case k3s version - v1.16.3-k3s.2) , user is presented with all the options it can updgrade to in the Kubernetes Version drop down menu as expected  from kdm data.json 
```
 "k3s": {
  "releases": [
   {
    "maxChannelServerVersion": "v2.4.0",
    "minChannelServerVersion": "v2.4.0",
    "version": "v1.17.3+k3s1"
   },
   {
    "maxChannelServerVersion": "v2.4.0",
    "minChannelServerVersion": "v2.4.0",
    "version": "v1.16.7+k3s1"
   }
  ]
 }
```

<img width="504" alt="Screen Shot 2020-03-07 at 7 44 19 PM" src="https://user-images.githubusercontent.com/4266958/76156225-0ef80c80-60ac-11ea-9d22-49b28eb75296.png">


There is 1 relayed issue with changes made to the versions published in kdm data.json not getting reflected in rancher which is tracked in https://github.com/rancher/rancher/issues/25870.
