### ISSUE TITLE
redis-master service is unreachable from windows pods in mixed clusters

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#25736]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. create rancher custom cluster with linux and windows worker nodes. (following the instructions in our docs here [Launching Kubernetes on Windows Clusters](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/)
2. deploy redis app via catalog ( Apps -> Deploy -> redis -> launch w/ default configs, verify that clusterip is used and that `Enable Master-Slave Topology` is enabled )
4. create windows pod ( using default `mcr.microsoft.com/dotnet/core/samples:aspnetapp` )
5. attempt to connect to linux redis-master service from windows pod using telnet and curl

**Result:**
Service for redis master is unreachable from windows pods.

example: 
deployed redis stable helm chart and windows pod 
kubectl exec -it win-pod powershell 

```
telnet redis-master 6379 
Connecting To redis-master...Could not open connection to the host, on port 6379: Connect failed

curl redis-master:6379
curl: (6) Could not resolve host: redis-master
```

**Other details that may be helpful:**

connecting to redis-slave service works from windows pods
Connecting by redis-master service IP does not work either
linux pod -> redis-master service works 
From windows pods it is possible to successfully connect to redis pods by pod ip, but connection to redis-master service always fails.

**Environment information**

Rancher version: 2.3.3 
Installation option: HA 

**Cluster information**

Cluster type: Custom 
Machine type: VM (on-prem, VMWare)

Kubernetes version 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749 
", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"} 
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749 
", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"} 
```
Docker version (use docker version): 

docker version 
```
Client: Docker Engine - Enterprise 
Version: 19.03.5 
API version: 1.40 
Go version: go1.12.12 
Git commit: 2ee0c57608 
Built: 11/13/2019 08:00:16 
OS/Arch: windows/amd64 
Experimental: false 

Server: Docker Engine - Enterprise 
Engine: 
Version: 19.03.5 
API version: 1.40 (minimum version 1.24) 
Go version: go1.12.12 
Git commit: 2ee0c57608 
Built: 11/13/2019 07:58:51 
OS/Arch: windows/amd64 
Experimental: false
```

**Comment by maggieliu** [comment]
No longer reproducing the issue. Confirmed with Support to close ticket.
