### ISSUE TITLE
Add Route 53 support for Rancher Services using rancher domain

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2573]
With #1675 completed, Rancher should now also support a default myrancher.com domain for services that have a published port.  

A default catalog entry should be created similar to what already exist for the custom Route53 template.  The UX to for enable this could be when a user created an environment, an option to enable Rancher Route53 is presented.  By enabling this, all future services with published ports will have a DNS entry generated and accessible via the internet.

**Comment by blaggacao** [comment]
if i understand it right, this goes under "batteries included but swappable", As for the case of Colombia, only Cloudflare is present in the city of Medellin with superior latency metrics. So I'm looking out for a way to keep cloudflares dns entries updated by api. It seems, this is probably what I was looking for. :+1:

**Comment by vincent99** [comment]
@blaggacao This particular feature would be to provide something like `service.stack.environment.blaggacao.rancher.com" FQDNs as-a-service that we own/manage that could work automatically with minimal/no setup.

The external DNS service is a container that watches for changes in Rancher metadata and makes the appropriate changes to the DNS entries with the provider's API.  So far it includes only a driver for Amazon Route53, but we would take a PR for CloudFlare support, or one of us will get to it eventually (we use them ourselves).

For example, here's one in progress contributed by a user for dnsimple: https://github.com/rancher/external-dns/pull/20

**Comment by will-chan** [comment]
Code is done.  Need to talk about hosting the rancher service that talks to Route53.
