### ISSUE TITLE
remote kubectl exec on a cluster does not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25737]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On master-head , deploy cluster.
- Steve is enabled by default
- Remote kubectl - exec shell fails

``` 
kubectl exec -it wk01-54bc5f97b4-97crh bash
error: unable to upgrade connection: malformed HTTP response "\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x04\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x04\x00\x04\x00\x00"
```

**Expected Result:**
Remote kubectl should work for a cluster

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master - head - latest
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): do rke
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by cjellick** [comment]
does the type of downstream have an impact (ie rke vs k3s vs eks)?

**Comment by sowmyav27** [comment]
@cjellick this is happening on these cluster types - import cluster, import k3s, rke, GKE clusters

**Comment by ibuildthecloud** [comment]
This seems to be an upstream issue with k8s https://github.com/kubernetes/kubernetes/issues/88782

I've patched it in https://github.com/rancher/apimachinery/commit/8ac01dfe4ad0d1f94a704b00020c35864dc1e7e4

**Comment by sowmyav27** [comment]
Verified with master-head - commit id: `17a40f502`

- kubectl - remote and via UI works

```
kubectl exec -it wk01-78cc9b575-nk2rs bash
root@wk01-78cc9b575-nk2rs:/# cd data
```
