### ISSUE TITLE
Drain is set to True by default on the UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25732]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On latest master-head, deploy a cluster.
- In the Advanced Options, Drain option is set to true

<img width="842" alt="Screen Shot 2020-03-03 at 8 33 16 AM" src="https://user-images.githubusercontent.com/26032343/75801017-5179bc00-5d2f-11ea-9781-368ed5241b06.png">

**Expected Result:**
Drain should be set to false (by default)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - ui tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): do RKE

**Comment by sowmyav27** [comment]
**Verified on latest master - ui tag: `latest2`**

Drain option is defaulted to "False"

**Comment by sowmyav27** [comment]
Reopening the issue
On master-head - commit id: `bfa3e1c8a` UI Tag: latest2,

Drain option is set to true, while creating a cluster --> Advance options
![Uploading Screen Shot 2020-03-07 at 9.51.13 PM.png…]()

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/09/2020)` commit id: 0519da989

- Validated all RKE provision clusters in the UI have this option default to false.
- Validated the Custom cluster has this option as false by default.
- Provisioning the cluster with the option set to default false succeeded, and the provisioned cluster had this option as false.
- Provisioning the cluster with the option set to default true succeeded, and the provisioned cluster had this option as true.
