### ISSUE TITLE
Istio - steve blocks istio from finishing installation

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#25742]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Run rancher:mater-head 3623201 single install
2. Enable Istio (with default options)

**Result:**
Navigating to System > Apps > cluster-istio after some time shows a failed Installing state:
![image](https://user-images.githubusercontent.com/55997940/75817361-29508400-5d54-11ea-96c4-2c79c60a2896.png)

**Other details that may be helpful:**
All pods appear to be running, and sidecar injection works properly even though cluster-istio is not shown as active. Istio Traffic Metrics page shows graphs correctly. Traffic Graphs page and links (prometheus, grafana, kiali, jaeger) all **do not work** and give 404 errors for all of their JS and CSS resources. The pages generally do not load.

Disabling Steve fixes the problems. However, the Kiali link and Traffics Graph page are still broken.

Likely related to https://github.com/rancher/rancher/issues/25741

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO 8gb 4vcpu 3 nodes all roles for each.
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by davidnuzik** [comment]
When I try this in latest master I actually get rancher server to crash. Reproduced twice. Simple enable Istio and you'll see tons of panics in rancher server logs (seems like infinite loop) then rancher server will eventually crash.

**Comment by cbron** [comment]
Unable to replicate on master-head `53e0430e1` with HA setup. Both monitoring and istio install correctly in downstream cluster. I can share my setup, but might just retry it. 
I see one error in rancher logs: `error in remotedialer server [400]: websocket: close` but it recovers fine.

**Comment by cbron** [comment]
Having trouble debugging this one, although I did confirm that turning steve off fixes it so it doesn't appear to be a helm issue. 

Primary issue seems to be this post-install job/pod not being recognized as completed: 

```
Release cluster-istio post-install rancher-istio/charts/security/templates/create-custom-resources-job.yaml could not complete: timed out waiting for the condition
rancher-855885976b-8khxl rancher [tiller] 2020/03/06 18:32:00 warning: Release "cluster-istio" failed post-install: timed out waiting for the condition
rancher-855885976b-8khxl rancher 2020/03/06 18:32:01 [ERROR] AppController p-gc45x/cluster-istio [helm-controller] failed with : failed to install app cluster-istio. Error: timed out waiting for the condition
```
But when you look at them they are fine, no errors in logs, status of succeeded: 

```
k get job -n istio-system
NAME                                COMPLETIONS   DURATION   AGE
> istio-security-post-install-1.4.6   1/1           22s        15m

k get pod -n istio-system | grep security
> istio-system        istio-security-post-install-1.4.6-wb748        0/1     Completed   0          15m  
```

One time on the pod I got this but it appears unrelated:
```
  Warning  FailedMount  2m56s      kubelet,  MountVolume.SetUp failed for volume "istio-security-post-install-account-token-6mb52" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  2m56s      kubelet,  MountVolume.SetUp failed for volume "tmp-configmap-security" : failed to sync configmap cache: timed out waiting for the condition
```
Another transient error related to configmaps is: 
```
Failed to install app monitoring-operator. Error: UPGRADE FAILED: an error on the server ("") has prevented the request from succeeding (get configmaps)
```
And no events appear in any NS, sometimes helm rbac issues pop up there.

**Comment by cbron** [comment]
Re-assigning for now because I believe this is a dupe of 25741, if not I will take back.

**Comment by rancher-max** [comment]
#### Validated with master-2414-head `Rancher version c34bdc2bb`
Followed the same steps as in the original issue:

- Istio (and therefore monitoring) installs correctly when using the default enabled rancher features
![image](https://user-images.githubusercontent.com/55997940/76446685-a6977c80-6384-11ea-8d93-bb25ef52120e.png)

- Automation runs and passes so regressions have been accounted for
