### ISSUE TITLE
Kubernetes version is empty in upgraded HA set up.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/rancher#25745]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create an HA rancher setup (3 nodes all roles) - rancher version - v2.3.5
2. Upgrade the set up to rancher master 2330 head - 3623201ad
3. Click add cluster.

**Result:**
Kubernetes version selection box is empty.
![empty-version](https://user-images.githubusercontent.com/60111667/75821010-51d77e80-5d52-11ea-8332-7b5224700880.png)

**Other details that may be helpful:**
 On refreshing 'kubernetes metadata' ```tools > drivers> refresh kubernetes metadata```, versions start appearing.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): HA

**Comment by StrongMonkey** [comment]
@khushboo-rancher @jiaqiluo Can you test rancher master right now? I assume this commit should fix it. https://github.com/rancher/rancher/commit/78ee11ab732a1d2f8d1bfa2be3f3969c73f13339. I did a single node upgrade it appears to be working. I don't think this is specifically related to HA install.

**Comment by rancher-max** [comment]
Validated @StrongMonkey's theory on latest master build: master-2355-head. (`Rancher version f6872eb2c`)

![image](https://user-images.githubusercontent.com/55997940/76007893-021cc280-5ecc-11ea-9fa4-0c01a3d080fa.png)

Tried two separate scenarios (both using HA setup): 
1. Fresh install master-head 
2. Upgrade from v2.3.5 to master-head

Kubernetes versions are available when creating cluster in both (see screenshot)
