### ISSUE TITLE
helm repo with non-absolute path for sources in index.yaml

### ISSUE THREAD

**Issue by ribx** [rancher/rancher#25759]
This issue looks alot like #14905.

**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. add https://grafana.github.io/loki/charts to rancher 2.3.5 catalog
2. try to install a package (e.g. loki-stack)

**Result:**
Page is grayed out (loading state) and gets stuck there. A Javascript error appears:
```
Unhandled promise rejection TypeError: "can't convert undefined to object"
    initPreviewTab component.js:250
    initTemplateModel component.js:245
    init component.js:66
    invoke backburner.js:341
    flush backburner.js:233
    flush backburner.js:437
    _end backburner.js:1013
    _boundAutorunEnd backburner.js:653
    s polyfill.js:4399
    O polyfill.js:4416
    u polyfill.js:1501
polyfill.js:4434
    t polyfill.js:4434
    exports polyfill.js:1849
    M polyfill.js:4428
    exports polyfill.js:1182
    <anonym> polyfill.js:2256
    v polyfill.js:2242
    y polyfill.js:2246
```

The last request to the backend (<rachner>/v3/templateVersions/cattle-global-data:loki-loki-stack-0.32.1?rancherVersion=v2.3.5) does not include any "files". They are included in other packages that work.

I see two Problems:
1. the exception in javascript is not properly handled
2. the backend does not send the nessesary files

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.3.5
- Installation option (single install/HA): single install

**Comment by sunxiang0918** [comment]
I'm having the same problem..

**Comment by stv0g** [comment]
Me too

**Comment by sra** [comment]
This happened to us today, the issue was that the private repository was down - it is a sonatype nexus repo and it was offline for maintenance. The issue went away after it came back online.
