### ISSUE TITLE
[UI] Upgrade change health check from HTTP to TCP opened doesn't work

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2575]
Whenever you try to upgrade a service, and that service has an health check over HTTP requests, and you try to choose TCP Opened check method, Health Check settings will be ignored.

EDIT:
Affected cattle version: `v0.107.0`

**Comment by deniseschannon** [comment]
This isn't just an upgrade issue. It's a UI issue where if you had text in the `HTTP REQUEST*` line, it doesn't get cleared if you have selected `TCP` health check and save.

**Comment by tfiduccia** [comment]
Version - Master with latest reskin UI
Verified fixed
