### ISSUE TITLE
Add Helm 3 chart catalog to repo

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#25754]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement/feature

**Explanation :**
Helm versions are determined at the catalog level, so new Rancher charts that are helm 3 compatible will need to be in their own catalog.  

**Result:**
New helm 3 catalog (https://github.com/rancher/helm3-charts)  needs to be added https://git.rancher.io
and needs to be added into Rancher

**Comment by paraglade** [comment]
helm chart updated to pull in helm3-charts repo and production upgraded:
 #https://github.com/rancher/eio-charts/pull/32
```
┌─[paraglade][angus][~/brain/tmp]
└─▪ git clone https://git.rancher.io/helm3-charts
Cloning into 'helm3-charts'...
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (9/9), done.
┌─[paraglade][angus][~/brain/tmp]
└─▪ ls -la helm3-charts
total 32
drwxr-xr-x 4 paraglade paraglade 4096 Mar  4 13:42 .
drwxr-xr-x 5 paraglade paraglade 4096 Mar  4 13:42 ..
-rw-r--r-- 1 paraglade paraglade  335 Mar  4 13:42 .drone.yml
drwxr-xr-x 8 paraglade paraglade 4096 Mar  4 13:42 .git
-rw-r--r-- 1 paraglade paraglade   10 Mar  4 13:42 .gitignore
-rw-r--r-- 1 paraglade paraglade 5656 Mar  4 13:42 README.md
drwxr-xr-x 2 paraglade paraglade 4096 Mar  4 13:42 test
┌─[paraglade][angus][~/brain/tmp]
```

**Comment by deniseschannon** [comment]
@brendarearden can you add helm3-library pointing to `git.rancher.io/helm3-charts` in this section?
https://github.com/rancher/rancher/blob/master/app/catalog_data.go

**Comment by brendarearden** [comment]
Yes, I will add that in and get a PR up

**Comment by jiaqiluo** [comment]
Rancher master-head 9269970

confirm that
- a new helm 3 catalog named `helm3-library` is enabled by default
- and it points to `git.rancher.io/helm3-charts`

![image](https://user-images.githubusercontent.com/6218999/76241657-8c2d9980-61f2-11ea-9411-53b7613bbb4c.png)
