### ISSUE TITLE
Can't set traefik host label in new workload

### ISSUE THREAD

**Issue by skjnldsv** [rancher/rancher#25758]
Hi!

I'm new to rancher and I currently successfully set up rancher on ubuntu 18.04 with a traefik frontend.
I'm trying to deploy my first workload, but I cannot set the necessary label for traefik ```traefik.http.routers.whoami.rule=Host(`rancher.domain.com`)```

![image](https://user-images.githubusercontent.com/14975046/75857271-345bf080-5df6-11ea-9adb-3f60fd69de86.png)

It says
> Validation failed in API: Deployment.apps "whoami" is invalid: spec.template.labels: Invalid value: "Host(`rancher.domain.com`)": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

Anyone knows how I can do that?

**Comment by vincent99** [comment]
Labels in Kubernetes are mostly used for scheduling and have very limited allowed charactersets and lengths for both the key and value.  You're probably looking at the Docker or Rancher 1.x examples for Traefik instead of Kubernetes...

For Traefik 2.x there are custom resources for configuring traefik: https://docs.traefik.io/routing/providers/kubernetes-crd/

For 1.x they use annotations (not labels): https://docs.traefik.io/v1.7/user-guide/kubernetes/

**Comment by skjnldsv** [comment]
Hey! Thanks for the help :)

> You're probably looking at the Docker or Rancher 1.x examples for Traefik instead of Kubernetes...

Well, I'm on Traefik 2.1 and rancher 2. Running manual dockers images with labels works just fine. https://docs.traefik.io/routing/routers/#rule

**Comment by skjnldsv** [comment]
I'm running rancher behind traefik, so far everything is working fine labels, domains, load balancing.... :wink: 

Only applying labels to my workloads fails, therefore traefik cannot reach it :(

**Comment by vincent99** [comment]
Labels in docker and labels in Kubernetes things are entirely unrelated things with the same name.  Setting labels on a workload does not pass them to Docker.

To configure Traefik 2.x rules in k8s you use their CRD (which there is no UI for in Rancher): https://docs.traefik.io/routing/providers/kubernetes-crd/

Or you turn on normal kubernetes ingress support and use that (which does less but works with any ingress provider and is in the Rancher UI): https://docs.traefik.io/providers/kubernetes-ingress/
