### ISSUE TITLE
[Task] prepare channelserver k3s min and max versions for release

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#25750]
**What kind of request is this (question/bug/enhancement/feature request):**
task

**Description:**
need to decide on k3s release to include in /releases for v2.4 and add them to kontainer-driver-metadata.

**Comment by cjellick** [comment]
We've left in older versions for the purposes of testing, but we'll just have 1.17.4 in the list when we go live

**Comment by deniseschannon** [comment]
@daxmc99 can we make a PR for this so that when it comes time, it's ready to merge and we can then test around it?

**Comment by daxmc99** [comment]
For reference: the root of truth repo for this is https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/data/data.json

**Comment by daxmc99** [comment]
https://github.com/rancher/kontainer-driver-metadata/compare/dev-v2.4...daxmc99:k3s_version_2.4?expand=1 
Do we want to merge into the `dev-v2.4` branch or is there going to be a release 2.4 branch I should make the PR to?

**Comment by deniseschannon** [comment]
You can make a PR to dev-v2.4, but that whole branch will eventually be moved to create a new release 2.4 branch.

**Comment by rmweir** [comment]
system-upgrade-controller should be version v0.4.0

**Comment by khushboo-rancher** [comment]
Tested on master head - e78331527 

Only 1.17.4 appears in version. 
<img width="1348" alt="Screen Shot 2020-03-25 at 2 49 08 PM" src="https://user-images.githubusercontent.com/60111667/77590290-a336e180-6eaa-11ea-8ea5-d770b99fcaa3.png">

System-upgrade-controller has the version v0.4.0
<img width="1372" alt="Screen Shot 2020-03-25 at 2 51 32 PM" src="https://user-images.githubusercontent.com/60111667/77590466-03c61e80-6eab-11ea-8529-f295db1f240f.png">

An upgrade from v1.16.3 to v1.17.4 went through smoothly.
