### ISSUE TITLE
[RFE] Group clusters into folder/tree view with RBAC support

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#25763]
#### Feature Request

When the number of clusters is growing, it is hard to manage them.

The idea is to create a tree view with some kind of "folders" to filter the cluster view.
In addition, an RBAC list of rules to control the visibility on those folders would help to restrict users visibility.

**Comment by skaven81** [comment]
To expand on this, there are two separate, but related, goals to this RFE.

The first is organizational.  As Rancher endeavors to scale up to thousands of managed clusters, there is a need for grouping and organization of the managed clusters.  The Rio-based tree view seems to be a good match for this.  I would like to see the Rancher UI allow administrators to create a tree-like structure of "folders" where managed clusters can be arranged.  For example, we might want to organize the clusters by region.  Or by development stage.  Or by security context.  Or by cloud technology.

The second is around RBAC, and rides on top of the tree-like view of the clusters.  An infrastructure operations team may provision many Rancher-managed clusters (possibly hundreds or even thousands).  But individual users (non-admins) logging into the Rancher UI don't need to see all of those clusters.  They only need to see the clusters that they actually have rights to see.  There is already the concept of cluster-level "member" roles, and I think that these are sufficient.  But the way they are managed should be folded into the tree structure noted above.  Folders in the tree structure should be able to be assigned cluster role "templates" of sorts.  So when a cluster is moved into a particular folder, the cluster roles in that folder (and its parents) are applied to the cluster automatically.  And conversely, if the cluster is moved out of the folder, those roles should be removed.

The result should look a lot like the prototype Rio UI, where when a regular (non-admin) user logs in, they only see the folders and clusters they have rights to see.  Everything else is hidden, providing a clean, tidy environment for developers to work.  It also ensures that as the infrastructure ops team works on things like experimental clusters that may be in an error or unavailable state, that they can be hidden from regular users, by virtue of placing them in a folder that regular users don't have access to.
