### ISSUE TITLE
Terraform Rancher2 node_template not using ssh_keypath from amazonec2_config block

### ISSUE THREAD

**Issue by seanmcrum** [rancher/rancher#25765]
I am trying to use Terraform + the Rancher2 provider to create a node template and cluster. I've configured the node_template to use the necessary AWS credentials but I'm stuck at the keypair_name and ssh_keypath configuration.

When I add an existing keypair_name and ssh_keypath I get an error in Rancher that says "error setting machine configuration from flags provided: using --amazonec2-keypair-name also requires --amazonec2-ssh-keypath." If I check the node template through the Rancher API the ssh_keypath key isn't even there. The ssh_keypath is present in the Terraform state file, but it looks like it can't pass into the Rancher node_template.

How do I fix this?
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.5` UI: `v2.3.36` |
|Route|`nodes.node-templates`|

**Comment by hanselke** [comment]
same problem on rancher 2.5.5 - 2.5.7

**Comment by son-la** [comment]
I guess this will never work then?

**Comment by son-la** [comment]
I still have this issue on Rancher 2.5.x/ rancher2 provider 1.21.0

**Comment by empeekdev** [comment]
Why it was closed? Is there any update? We have the same issue on Rancher 2.6.3. node_template API definition just don’t have ssh_keypath parameter.
 
@seanmcrum @hanselke @son-la was you able to solve this problem?

**Comment by palmeXx** [comment]
THis is not a problem of the provider... it's a Problem in the docs... 

When u set _kepair_name_ u need to set _ssh_key_contents_ with the private_key of your key_pair 

Why?
The key_pair in aws holds only the publickey, so rancher need the private key to establish a connection.
