### ISSUE TITLE
Shibboleth OpenLDAP TLS Setting Not Set from API

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#25775]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
add shibboleth config
check tls setting (located in OpenLDAP near Port and Servers)
save shibboleth config
edit shibboleth and see tls will not be checked
check /v3/authconfig/shibboleth API and you will see value is true

Expect behavior would be to see the TLS box checked, this can break your openldap connection config completely if the user does not notice this

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/05/2020)` commit id: f6872eb2c

I was able to validate that saving or configuring OpenLDAP in Shibboleth enabling the TLS checkbox in the UI now sends the `tls: true` configuration to the BE.

The configuration response also had this `tls: true` value in the config.

Validated that the TLS communication was stablished with the OpenLDAP server by monitoring the OpenLDAP server logs:

```
5e610a38 conn=1020 fd=30 ACCEPT from IP=x.x.x.x:51672 (IP=0.0.0.0:636)
5e610a38 conn=1020 fd=30 TLS established tls_ssf=128 ssf=128
5e610a38 conn=1020 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
5e610a38 conn=1020 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
5e610a38 conn=1020 op=0 RESULT tag=97 err=0 text=
5e610a38 conn=1020 op=1 SRCH base="ou=people,dc=example,dc=org" scope=2 deref=0 filter="(&(objectClass=inetOrgPerson)(|(cn=test*)(givenName=test*)))"
5e610a38 conn=1020 op=1 SRCH attr=dn memberOf objectClass inetOrgPerson cn cn 1.1
```

Searching for users and groups and assigning roles for site access, cluster and project worked.

**Comment by izaac** [comment]
Opened https://github.com/rancher/rancher/issues/25799 for an UI enhancement.
