### ISSUE TITLE
Unable to add Environment group permission for a group I am not a member of

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2577]
We have integrated Rancher with our AD LDAP for authentication and groups.

When configuring Environment permissions by group, the Group selection dropdown only contains a list of groups of which I am already a member.  This is probably a good thing, since we have literally thousands of groups in our domain and retrieving all of them would take too long (and make an unuseable dropdown), but it means I am unable to select a group of which I am not a member.

Although I can type a group name into the selector box for a group I know to exist, this is rejected with "Identity not found".  I would guess that this is because the group exists in some sub-OU in the LDAP structure, and the validity check for groups is only being done against the known groups list which contains only the groups of which I am personally a member.

When using LDAP as the authenitcation mechanism, the system needs to do an LDAP search for the requested group to determine its validity.

**Comment by sshipway** [comment]
A bit more testing shows that usernames are verified against an LDAP lookup, but groups are not.  

This also raises the question of what will happen if there exists a user with the same base name as a valid group - how can you know which will be added?  Should there be a '+User' and '+Group' button rather than just a '+' ?  

Fortunately, we have a naming scheme that means we are not vulnerable to this potential issue, but it may well arise elsewhere.

**Comment by hibooboo2** [comment]
@sshipway Can you try logging into rancher(the one you have setup with ldap.) Then goto ${RANCHER_URL}/v1/identity?all=${GROUP_NAME_YOU_ARE_LOOKING_FOR} and let me know if that finds your group or a list of the groups you are after. As this is a supported feature to look for groups using the ldap filter: 
```
query = "(&(" + LdapConstants.GROUP_SEARCH_FIELD.get() + "=*" + name + "*)(" + LdapConstants.OBJECT_CLASS + '='
                    + LdapConstants.GROUP_OBJECT_CLASS.get() + "))";
```
Which might translate to say 
```
query= "(&(sAMAccountName=*developers*)(objectClass=group))"

**Comment by hibooboo2** [comment]
As far as which attribute to assign to the group search field I am not sure with you would need, without looking at your setup. I would try setting it to CN or cn and see it that works.

**Comment by sshipway** [comment]
Tested this again under 0.47.0, and the problem is still there;  I can only add a group to the permissions list for which I am already a member.  The API call still produces the 404.

I can select a group for which I am a member from the dropdown; but I can only enter a username into the text box, not a group name.

The login time is vastly improved, though, under 0.47.0

**Comment by sshipway** [comment]
This *may* be due to overzealous security restrictions at the AD LDAP end on the service account being used to bind to AD, which might be restricting the ability to search for groups.  I am investigating, will post here if it solves the issue.

**Comment by sshipway** [comment]
Yes, this was indded the case.  Rancher is correctly searching for groups, but our AD was hiding them.  Rights have been updated, and the group search is now working as expected.

Not a bug in Rancher after all
