### ISSUE TITLE
Fix flakey/slow app integration tests in ARM

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#25774]
There has been a dramatic increase in app test failures in ARM. In the past there has been sporadic failures, but now they are consistent over multiple tests. Specifically: 

```
=========================== short test summary info ============================
--
1199 | FAILED test_app.py::test_app_mysql
1200 | FAILED test_app.py::test_helm_timeout
1201 | FAILED test_app.py::test_prehook_chart
1202 | FAILED test_app.py::test_app_namespace_annotation
1203 | FAILED test_app.py::test_app_wordpress
1204 | FAILED test_app.py::test_app_custom_values_file
```

This may be related to the following: 

  * Heavy drone usage
  * Steve
  * Token hashing
  * Helm upgrade

First case of it being very bad: 
  * https://drone-pr.rancher.io/rancher/rancher/7543

Other Examples:
  * https://drone-pr.rancher.io/rancher/rancher/7572
  * https://drone-pr.rancher.io/rancher/rancher/7570
  * https://drone-pr.rancher.io/rancher/rancher/7552

Hacky fix: 
  * https://github.com/rancher/rancher/pull/25767

Tip:
  * Use this to scroll back in drone: `var x = 0; btn = $(".output-button"); while (btn != null && x < 500) {btn.click(); btn = $(".output-button"); x++}` and then search for "short test".

**Comment by cjellick** [comment]
https://drone-pr.rancher.io/rancher/rancher/7633/1/2
