### ISSUE TITLE
Reflect scan state with the right color in the UI

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#25789]
UI counterpart for https://github.com/rancher/rancher/issues/25214

UI needs to show "Fail" in Red and "Pass" in Green

**Comment by sowmyav27** [comment]
Verified on latest master-head - commit id: `bfa3e1c8a` ui tag: latest2.

Fail is seen in Red and Pass in Green on UI.
<img width="1333" alt="Screen Shot 2020-03-08 at 9 42 34 AM" src="https://user-images.githubusercontent.com/26032343/76167078-3ccb6880-6121-11ea-9fe9-7f983c8bc5ac.png">

State Transitions currently happening -- Creating --> Running --> Active --> Fail/Pass/Error

For Active state showing, logged bug -- https://github.com/rancher/rancher/issues/25856
