### ISSUE TITLE
Creating service with health check enabled should not be allowed for any network other than managed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2578]
Currently , we are allowed to create services with health check enabled when services have any network - like host/container/bridge. Since we support of  health check only for services in managed network , API should error out when Creating service with health check enabled on  any network other than managed.

**Comment by ebr** [comment]
Thanks for this note, this explains a lot. It would be great to make this *very* clear in the documentation - I've been wondering why some of my healthchecks simply never work, and ostensibly this is the reason.

**Comment by deniseschannon** [comment]
@ebr I've added the docs in this PR https://github.com/rancher/rancher.github.io/pull/111. Is there anywhere else in the docs site that I could add it to that I might have missed?

**Comment by alena1108** [comment]
Closing this bug in favor of https://github.com/rancher/rancher/issues/2432 enhancement request.
