### ISSUE TITLE
where is the detail rancher-cluster.yaml

### ISSUE THREAD

**Issue by denwork** [rancher/rancher#25798]
I want konew about more for rancher-cluster.yaml.
Where can I find the detailed rancher-cluster.yaml?

**Comment by superseb** [comment]
Not really sure what you are asking exactly, but in the docs (https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/kubernetes-rke/#advanced-configurations) we link to the RKE documentation which uses this file to create the cluster.

Let me know if there are remaining questions.

**Comment by denwork** [comment]
@superseb  The docs so simple. Do you have a more detailed docs for the config yaml?
For example:
about kube-api kube-controller kubelet and kube-proxy etc in the rancher-cluster.yaml.
thanks!!

**Comment by superseb** [comment]
If you follow the link on that page to the RKE docs, you end up on https://rancher.com/docs/rke/latest/en/config-options/ which includes those services here https://rancher.com/docs/rke/latest/en/config-options/services/
