### ISSUE TITLE
Should be able to restrict certain operations in Environments to Owners

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2580]
Within each Environment, it is possible to grant Owner or User roles.

The only current difference seems to be that Owners can grant permissions to an Environment whereas Users cannot.

I would like to also be able to restrict other configuration options to Owners only -
- Configuration of Registries (so that normal users cannot install from an unapproved Registry)
- to mark Stacks as 'protected' to restrict their maintenance to Owners only.
- Add/Delete a Host in the Environment (so that normal users cannot extend the cluster to their desktop when they need more capacity, or worse delete hosts)
- Define an API key

In addition, I would like to be able to restrict actions such as 'Create Environment' to Admins only, in order to prevent users from creating an untold number of Environments without control - as there seems to be no way to delete an Environment.

**Comment by hibooboo2** [comment]
@sshipway Is the new role made from rancher/cattle#1069 meeting your needs?

**Comment by sshipway** [comment]
Will need to check this when I get back to the office after the xmas hols.  Looks good though.

**Comment by will-chan** [comment]
This will be part of the larger RBAC feature we add.
