### ISSUE TITLE
Color changes in UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25800]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Navigate to Settings page from Rancher UI
- Ui is seen as:

<img width="1283" alt="Screen Shot 2020-03-05 at 7 36 50 AM" src="https://user-images.githubusercontent.com/26032343/75997787-b6aaea00-5eb4-11ea-86ec-34f637b28dd6.png">

**Expected Result:**
- Black color should NOT be seen here

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest
- Installation option (single install/HA): single

**Comment by rancher-max** [comment]
Also the white text makes it a bit hard to read in the "Differences" section when performing a rollback:
![image](https://user-images.githubusercontent.com/55997940/76001171-ec0a0480-5ec1-11ea-8122-52c76544b68b.png)

![image](https://user-images.githubusercontent.com/55997940/76001227-0643e280-5ec2-11ea-8dd3-a534221a9e96.png)

**Comment by sowmyav27** [comment]
**Verified on latest master- ui Tag: `latest2`**
This issue - https://github.com/rancher/rancher/issues/25800#issue-576346467 is seen fixed.
<img width="1329" alt="Screen Shot 2020-03-05 at 9 42 52 AM" src="https://user-images.githubusercontent.com/26032343/76009214-b36c2a00-5ec5-11ea-8c87-758b3c99adf0.png">

**Comment by rancher-max** [comment]
The other part of this issue - https://github.com/rancher/rancher/issues/25800#issuecomment-595314320 is also fixed on latest master ui tag (`latest2`)

![image](https://user-images.githubusercontent.com/55997940/76011541-0055fd80-5ed2-11ea-9ae6-18f6de531baf.png)

**Comment by rancher-max** [comment]
Something changed with this. Now cannot see the field names that are changing without highlighting. See below screenshots from App Revision Differences during a rollback. First is without highlighting:

![image](https://user-images.githubusercontent.com/55997940/76238880-c21c4f00-61ed-11ea-90b3-649c27e2748e.png)


![image](https://user-images.githubusercontent.com/55997940/76238718-83869480-61ed-11ea-911f-b202088018d3.png)

**Comment by rancher-max** [comment]
![image](https://user-images.githubusercontent.com/55997940/76257959-e5f08c80-620f-11ea-9633-3954a10fc78e.png)
Validated this is fixed again in `latest2`
