### ISSUE TITLE
Checking and deleting unused kube-kubelet certificates are seen in the rancher logs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25814]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster on master-head
- Cluster spec - 8 nodes, 3 etcd, 2 control plane and 3 worker nodes
- Run CIS scan on the cluster.
- Rancher logs keep showing this message:

```
2020/03/05 23:23:42 [INFO] [certificates] Checking and deleting unused kube-kubelet certificates
2020/03/05 23:23:42 [INFO] [certificates] Deleting unused certificate: kube-kubelet-<ip>
2020/03/05 23:23:42 [INFO] [certificates] Deleting unused certificate: kube-kubelet-<ip>
2020/03/05 23:23:43 [INFO] [certificates] Checking and deleting unused kube-kubelet certificates
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `f6872eb2c`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom cluster
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by leodotcloud** [comment]
This doesn't seem to be a CIS related issue.

**Comment by sowmyav27** [comment]
**verified on master-head - commit id: `570461823`**

- Verified the logs are available in Trace. `docker exec 3b470f739931 loglevel --set trace`

```
2020/03/11 15:46:00 [TRACE] Checking and deleting unused certificates with prefix [kube-etcd] for the following [1] node(s): <ip>
```
