### ISSUE TITLE
Add nodelocal DNS option as option in yaml

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#25811]
Enhancement

RKE issue: https://github.com/rancher/rke/issues/1050

**Comment by jiaqiluo** [comment]
The UI enhancement is validated in Rancher:master-head 8ede17d10
the following section shows when add/edit a cluster in YAML 

![image](https://user-images.githubusercontent.com/6218999/76350788-9bcbe180-62c9-11ea-83af-087e458296f5.png)

**Comment by jiaqiluo** [comment]
The node-local DNS does not take effect in Rancher:master-head 8ede17d


- add a new cluster in Rancher, edit it as YAML and fill the `ip_address` with `169.254.20.10`
- the cluster is active, but there is NO `node-local-dns` DaemonSet
- edit the cluster as YAML to add the following line to the dns section
```provider: coredns```
- the cluster is active again, but the `rke-nodelocal-addon-deploy-job` is stuck in deploying, its pods shows the error:
`
The DaemonSet "node-local-dns" is invalid: spec.updateStrategy: Unsupported value: apps.DaemonSetUpdateStrategy{Type:"/v3/schemas/daemonSetUpdateStrategy", RollingUpdate:(*apps.RollingUpdateDaemonSet)(0xc00e4a5640)}: supported values: "RollingUpdate", "OnDelete"
`
![image](https://user-images.githubusercontent.com/6218999/76351569-e6019280-62ca-11ea-96cd-f8caf1cb58e1.png)

![image](https://user-images.githubusercontent.com/6218999/76351545-daae6700-62ca-11ea-801e-50d658c7012a.png)


Note:
- If I added both the provider and the ip address when createing the cluster, the node-local DNS will work.

**Comment by superseb** [comment]
@jiaqiluo Can you retest this on current master-head (build 2444)

**Comment by sangeethah** [comment]
@superseb Can you add the PR that addresses this issue ?

**Comment by superseb** [comment]
https://github.com/rancher/rke/pull/1962

**Comment by jiaqiluo** [comment]
the enhancement is validated on master-2447-head 56d69e236

Steps:
- add a new cluster(1 etcd+contrlplane, 3 workers) in Rancher, edit it as YAML and fill the `ip_address` with `169.254.20.10`

Results:
- the cluster is active and all workloads are deployed successfully 
- confirm the `--cluster-dns` on the `kubelet` container should be set to designated address (need to ssh into nodes)
```
ubuntu@jiaqi-ec2-w1:~$ sudo docker inspect kubelet | grep -e  'cluster-dns'
            "--cluster-dns=169.254.20.10",
                "--cluster-dns=169.254.20.10",
```
- confirm that the internal and external dns resolution works following the checsk on https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/
