### ISSUE TITLE
Accounts should pull and display displayName when creating from an LDAP login

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2581]
When an LDAP user logs in for the first time, a Rancher account by that name is created in the database and linked to that Identiy.

However, the Account name is not populated with the displayName attribute from the LDAP identity, and the Identity and Account are always displayed with the identity name.

The Environment access configuration screen would be easier to read if the user displayName (and possibly the equivalent for groups) were displayed; User objects should probably display the Account object Name with the Identity underneath, and an Account should default to using the Identity displayName as the Name.

Whilest this does not add any functionality, it makes it much easier to manage large numbers of users when you can see both the display name ('Steve Shipway') and the identiy ('sshi052')

**Comment by RoryHunter** [comment]
Is this still an issue? I created an LDAP-backed Rancher server today, and it shows me the uid and display name just fine.

**Comment by sshipway** [comment]
@RoryHunter -- This is all fixed now.  I don't know at which version it was corrected but I definitely have all the displayNames visible in our system.

This ticket can be closed.
