### ISSUE TITLE
Can't get any catalogs: Cert valid for load balancer/proxy, not catalog domain

### ISSUE THREAD

**Issue by Vacant0mens** [rancher/rancher#25836]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1 - Fresh install/setup of Rancher in Kubernetes with an external load balancer (nginx) with self-signed certs on Rancher and LetsEncrypt certs on the load balancer.
2 - add custom Catalog (in this case, the main k8s helm catalog (https://kubernetes-charts.storage.googleapis.com/stable)
**Result:**
`Error in HTTP GET to [https://kubernetes-charts.storage.googleapis.com/index.yaml], error: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: certificate is valid for rancher.mydomain.com, other.mydomain.com, foo.mydomain.com, bar.mydomain.com, not kubernetes-charts.storage.googleapis.com`
built-in catalogs have a similar, but different error:
`fatal: unable to access 'https://git.rancher.io/system-charts/': SSL: certificate subject name (mydomain.com) does not match target host name 'git.rancher.io' : exit status 128`
**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5
- Installation option (single install/HA): HA on a 3-node kubernetes cluster (built using rke)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): self-hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3 VM's
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by superseb** [comment]
This sounds identical to https://github.com/rancher/rancher/issues/16697, can you check if that applies to your situation?

**Comment by Vacant0mens** [comment]
looks like it is (weird that it didn't come up in my search, nor as part of the "these issues are similar" suggestions). However, that last comment doesn't say where they changed `dns-search`, I assume that'd be in the `/etc/resolv.conf` ?

**Comment by Vacant0mens** [comment]
I commented out the `search mydomain.com` line in the `/etc/resolv.conf` file on each of my nodes and rebooted, but it doesn't seem to have helped.

**Comment by Vacant0mens** [comment]
oh. it looks like systemd overwrote my comment in the resolve.conf. let me try something else.

**Comment by Vacant0mens** [comment]
@superseb I can't seem to find where the host nodes would be getting the search domain from. Do you happen to have any ideas?

**Comment by superseb** [comment]
`docker inspect kubelet | grep resolv-conf` will show what kubelet is using as a file. If you are using systemd-resolved, you can't edit the file in place, you will need to do it via systemd-resolved configuration file and refresh to apply.

**Comment by superseb** [comment]
Let us know if this still needs more investigation.
