### ISSUE TITLE
Config maps left behind after a failed CIS Scan run has been deleted

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25837]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Run a CIS scan on a cluster.
- Scan gets stuck in "Creating" state, because of a known issue.
- Delete the CIS scan.
- The config maps related to this scan are NOT deleted.

**Expected Result:**
Config maps related the deleted failed CIS scan must get cleaned up

<img width="1441" alt="Screen Shot 2020-03-06 at 1 45 20 PM" src="https://user-images.githubusercontent.com/26032343/76125867-95c8be80-5fb2-11ea-998e-e6f77b664d41.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - latest - commit id: `beba5247e`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom cluster
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/10/2020)` commit id: e78e43fea

I was able to get the scan stuck in a "Running" state then after a minute I've just deleted the scan, all its related config maps were removed after doing this.
