### ISSUE TITLE
Catalog - UI TypeError for project or cluster catalog

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#25832]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- go to a project
- add a catalog with the scope of either `project` or `cluster`
- go to launch an app 
<img width="943" alt="Screen Shot 2020-03-06 at 11 43 02 AM" src="https://user-images.githubusercontent.com/6218999/76112846-45486580-5fa0-11ea-9aab-78615a50960e.png">

**Result:**
- UI is stuck in loading apps, and the following error is caught in console
`TypeError: Cannot read property 'isHelm3' of null`
<img width="997" alt="Screen Shot 2020-03-06 at 11 19 04 AM" src="https://user-images.githubusercontent.com/6218999/76112843-4083b180-5fa0-11ea-82c8-f11c0f3c5293.png">

**Other details that may be helpful:**
- not happen for catalog with the scope of `global`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
master-head 
- Installation option (single install/HA):
single install

**Comment by westlywright** [comment]
https://github.com/rancher/ui/pull/3797

**Comment by jiaqiluo** [comment]
validated in the master-head with the builtin UI index `https://releases.rancher.com/ui/latest2/index.html`

Following the same steps, we can now load the page and deploy apps successfully.
