### ISSUE TITLE
Cannot fully rotate AWS credentials for EKS clusters

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#25835]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. create eks cluster
2. let it provision
3. change access keys and secret key via the UI or kubectl
4. in the API/UI it will appear the access key is change
5. delete the old key from AWS, and attempt to update EKS version or delete the cluster

**Result:**
will not work due to invalid credentials

**Other details that may be helpful:**
I believe this is happening because the driver store the state for the cluster in a secret. Since the only thing that can be changed in actual AWS for the EKS cluster is the version, the driver will only update version in the secret it maintains for the clusters current state. If you decode the secret you will see the key has not changed.

**Comment by rmweir** [comment]
Created backport issue, this will be used to track master, the other will be for 2.4. There is no milestone for 2.5 yet, so it will stay as 2.4.

**Comment by rancher-max** [comment]
#### Validated in both master-2689-head (`d18a0b6b4`) and v2.4-2696-head (`04159d027`)

Followed the same steps as noted above: 

- Keys can be rotated and the cluster continues to work. It allows updating, continues to function properly, and deletion. 

- The secret that Rancher stores (mentioned in the original issue comment) is not updated. Leaving this open for @rmweir to investigate further.

**Comment by rancher-max** [comment]
The secret is updated correctly. The correct secret to verify is in namespace `cattle-system` and is like `c-c-*****`. Above was a user-error and this is fully functional.
