### ISSUE TITLE
[question] How do new Docker 1.9.0 features (Swarm, Multi-Host networking) affect Rancher?

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#2583]
Should they play nicely (e.g. Rancher managed network and Docker multi-host network across the same set of hosts)?

Are there plans to use Docker's multi-host network feature to replace Rancher's implementation?

Are there any advantages of one over the other?

Are there any conflicts to be expected with Swarm?

Thx!!!

**Comment by deniseschannon** [comment]
Here's some forum posts on this topic: 

http://forums.rancher.com/t/rancher-networking-architecture-vs-libnetzwork-docker-1-9/685/3
http://forums.rancher.com/t/docker-1-9-multi-host-networking-swarm-etc/869

**Comment by ebr** [comment]
:heart_eyes_cat: AWESOME. Thank you for all of this!
