### ISSUE TITLE
If unauthenticated, a big black dot appears in the Accounts Screen

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2584]
Version - Master with reskin

Steps:
1.  Authenticate through Github
2.  Turn Off authentication
3.  Go to the Accounts screen

Results:
There is now a big black dot under Identity
![image](https://cloud.githubusercontent.com/assets/11514927/11003536/55d12582-8470-11e5-9b27-22651c2a8ba5.png)

Expected:
Probably should not be there.

**Comment by vincent99** [comment]
This is only if you turn auth on and off again, because we've saved that that account was tied to (in this case) GitHub, but can't hit them anymore to get info about that user.
