### ISSUE TITLE
Endless loop rancher server logs on helm3 install failure

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#25842]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Add catalog:  	https://argoproj.github.io/argo-helm specify helm2 name it helm2
2. Add catalog  	https://argoproj.github.io/argo-helm specify helm3 name it helm3
3. Using helm2, install app argo-cd and name it foo
4. Delete foo
5. Using helm3, install app argo-cd and name it foo

**Result:**
This fails as expected due to helm3 not having the `crd-install` hook option. However, there are endless logs on the rancher server every 1 second:
```
2020/03/06 22:28:37 [ERROR] AppController p-kctnb/foo [helm-controller] failed with : wait helm template rendering notes failed. manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: foo-argocd-application-controller, existing_kind: rbac.authorization.k8s.io/v1, Kind=ClusterRole, new_kind: rbac.authorization.k8s.io/v1, Kind=ClusterRole
: exit status 1
```

**Other details that may be helpful:**
This happened for me in an upgraded setup. I previously had deployed a few apps in the setup before upgrading (using helm2) and used the same chart URL on my new catalog after upgrading, but had that one use helm3. 

Can workaround this by deleting the clusterroles and clusterrolebindings that were created in this case: `kubectl delete clusterroles foo-argocd-application-controller foo-argocd-server`
`kubectl delete clusterrolebindings foo-argocd-application-controller foo-argocd-server`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `Rancher version 63306835a` (`master-2375-head`)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 3 Linode nodes all roles
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 2cpu 4gb each node
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by brendarearden** [comment]
When I am running with the most recent code in head I am seeing this upon initial delete
```W0307 17:19:45.904432   49630 reflector.go:326] github.com/rancher/steve/pkg/clustercache/controller.go:184: watch of *v1.PartialObjectMetadata ended with: an error on the server ("unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)") has prevented the request from succeeding
W0307 17:19:45.915485   49630 reflector.go:326] github.com/rancher/steve/pkg/clustercache/controller.go:184: watch of *v1.PartialObjectMetadata ended with: an error on the server ("unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)") has prevented the request from succeeding
W0307 17:19:45.923993   49630 reflector.go:326] github.com/rancher/steve/pkg/clustercache/controller.go:184: watch of *v1.PartialObjectMetadata ended with: an error on the server ("unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)") has prevented the request from succeeding
```
And then when I try to install again I see:
```2020/03/07 17:38:11 [INFO] APIVersion metrics.k8s.io/v1beta1 Kind PodMetrics
E0307 17:38:12.342875   49630 reflector.go:307] github.com/rancher/steve/pkg/clustercache/controller.go:184: Failed to watch *v1.PartialObjectMetadata: the server could not find the requested resource
2020/03/07 17:38:12 [INFO] Stopping metadata watch on argoproj.io/v1alpha1, Resource=applications
2020/03/07 17:38:12 [INFO] Shutting down argoproj.io/v1alpha1, Kind=Application workers
```
**Steps to reproduce (least amount of steps as possible):**
Add catalog: https://argoproj.github.io/argo-helm specify helm2 name it helm2
Using helm2, install app argo-cd
Delete foo
Using helm2, install app argo-cd again

I turned off steve and it seemed to fix the issue and I do not see the endless rancher server logs even when following the original steps you submitted

**Comment by brendarearden** [comment]
Current master has proxy turned off by default - this seems to have fixed the issue of fresh install having helm 2 and helm 3 crd install issues

**Comment by rancher-max** [comment]
#### Validated in master-2417-head `Rancher version 01c482d5f`

This issue has been resolved. The same steps do not generate any endless logs, and the apps install correctly with no issues with both helm2 and helm3.
