### ISSUE TITLE
Don't pass restartAlways to docker for containers that are part of the service

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2585]
Today service reconcile logic controls container's lifecycle, and restarts it if it dies. So if restart=Always set on the container is redundant. Plus it can unnecessary interfere with service reconcile when restart is performed by Docker and by Rancher at the same time.

**Comment by sangeethah** [comment]
Tested with build from master - Nov 11

restartPolicy is not accepted as a parameter when creating services and all containers of the service have the restartPolicy set as follows:

        "RestartPolicy": {
            "Name": "",
            "MaximumRetryCount": 0
        },
