### ISSUE TITLE
[UI] Uplift Azure node template + custom images changes

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#25859]
1. We need support / validation for custom image input which needs to be provided to Rancher in one of the following formats:
- `<publisher>:<offer>:<sku>:<version>` for any image
- `resourceGroups/<resourceGroupOfImage>/providers/Microsoft.Compute/images/<imageName>` for an Azure Custom Image
- `resourceGroups/<resourceGroupOfImage>/providers/Microsoft.Compute/galleries/<galleryName>/images/<imageName>/versions/<versionNumber>` for an Azure Gallery Image

Can we add a way for users to input these values individually such that they are aggregated and sent to Rancher according the the type of input inserted?

i.e. something like a single box with tabs for Azure Image / Azure Custom Image / Azure Gallery Image that changes the fields received based on those required and sends them in the above format to the Rancher server when the user submits the form.

Currently the UI has a single text box for `Image`:
 ![screen_shot_2020-03-04_at_3 29 43_pm](https://user-images.githubusercontent.com/13127443/76134292-fb787300-5fd1-11ea-9e04-a3d3a6bd9ffb.png)

2. Would be nice if we could validate the Fault Domain Count provided against the maximum for the location requested (found here https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/managed-disks-common-fault-domain-region-list.md or accessible via the Azure API, as demonstrated in `drivers/azure/azureutil/sku.go` of the PR below):
![Screen Shot 2020-03-06 at 6 08 06 PM](https://user-images.githubusercontent.com/13127443/76134736-70997780-5fd5-11ea-9f5d-779aecf39324.png)

3. Would be nice if we can resolve https://github.com/rancher/rancher/issues/18291 as part of this task

Needs API changes from: https://github.com/rancher/machine/pull/72

**Comment by westlywright** [comment]
@deniseschannon I had an offline discussion with @aiyengar2 and this doesn't introduce any new parameters. The change only expands on what the image input calls valid so as we discussed no new UI changes are required for this.

**Comment by deniseschannon** [comment]
Closing as QA can use the main ticket and the existing `image` field in the node template to test out the custom azure image.
