### ISSUE TITLE
Security scan Alerts showing up as "Not Configured"

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25853]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Go to Cluster --> Tools --> Alerts
- When the Security Scan alerts have been configured with a Notifier, `Condition` of the alerts are seen as "Not Configured"

<img width="1278" alt="Screen Shot 2020-03-06 at 3 11 41 PM" src="https://user-images.githubusercontent.com/26032343/76132075-f1507780-5fc5-11ea-871d-ec57f15fbdac.png">

- Edit on one of the Active Alerts, shows that the alert is configured
<img width="1331" alt="Screen Shot 2020-03-06 at 4 15 39 PM" src="https://user-images.githubusercontent.com/26032343/76132086-ff05fd00-5fc5-11ea-8076-57d0f21e6f3c.png">

**Expected Result:**
Alerts should not be shown as "Not Configured"

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest - ui tag: latest2
- Installation option (single install/HA): single

**Comment by codyrancher** [comment]
I went ahead and updated the condition field for security scan. If it's failures only the condition will be "Failure" if not it will be "Happens".

It appears the default group is setting up a notifier and that's why that one isn't configured. So that will be a backend issue. Here's a security security scan group i created with a notifier configured properly.

![Screen Shot 2020-03-09 at 9.32.54 AM.png](https://zube.io/files/rancher/2b19a95ef7064305e5344e1c2b09d9bf-screen-shot-2020-03-09-at-9-32-54-am.png)

**Comment by izaac** [comment]
@codyrancher I thought https://github.com/rancher/rancher/issues/25904 was a dupe of this issue.

The first Alert Rule is working but after adding a second rule to an Alert group the Security Scan Condition is not getting saved. 

In the second rule added I try selecting the Security Scan -> Has Failure  And both "Completed Scan" and "Has Failure" end up selected, clicking Create gets the alert in Not Configured state:

<img width="1031" alt="Screen Shot 2020-03-09 at 11 38 47 AM" src="https://user-images.githubusercontent.com/27659/76246330-b97e4580-61fa-11ea-928b-b48f13192199.png">

<img width="1025" alt="Screen Shot 2020-03-09 at 11 39 32 AM" src="https://user-images.githubusercontent.com/27659/76246340-c0a55380-61fa-11ea-9a2c-18168e92d1fd.png">

**Comment by codyrancher** [comment]
I actually don't think that's a dupe. It's a separate issue. If you look at the screenshot you posted the test alert isn't considered a security scan. I'm going to close this issue and reopen the other.
