### ISSUE TITLE
New rancher library catalog in UI

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#25850]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Explanation:**
We have added a new Rancher library for helm3 charts only.  

**Result:**
New `helm3-library` needs to be be given the same UI rules as `library`

**Related Issue:**
rancher/rancher#25754

**Comment by deniseschannon** [comment]
With the backend in, I don't think we need to add anything in the UI. 

<img width="1297" alt="Screen Shot 2020-03-07 at 10 09 01 AM" src="https://user-images.githubusercontent.com/11410997/76150123-b1d46a80-605b-11ea-9cd3-d7ac6767ab38.png">

**Comment by deniseschannon** [comment]
Actually, looking into this a bit more. 

I don't know if it's front end or backend that is determining if you can or can't clone a catalog. 

It seems we allowing cloning the system-library and helm3-library. We should disable ability to clone both of those to keep consistency.

**Comment by vincent99** [comment]
That giant icon is...supposed to be there?  cc @tfiduccia

**Comment by loganhz** [comment]
Hi @brendarearden , if we deploy a new app from the old `library` in 2.4.0,  which helm version will be used in rancher server for it ?

**Comment by loganhz** [comment]
Oh, just found the answer here https://github.com/rancher/rancher/issues/20596#issuecomment-596022744.

**Comment by jiaqiluo** [comment]
Rancher master-head 9269970

confirm that
- a new helm 3 catalog named `helm3-library` is enabled by default
- there is no clone option for `helm3-library` and `system-library` 

This issue keeps opening to wait for new charts added to `system-library`

**Comment by tfiduccia** [comment]
I upgraded my master and I didn't see the helm 3 chart?
![image](https://user-images.githubusercontent.com/11514927/76255386-547f1b80-620b-11ea-9dbf-6c1a9d03069e.png)

**Comment by tfiduccia** [comment]
@westlywright @lvuch  
- [ ] Can we move the icon to the right  side of the helm text and make it smaller?

![image](https://user-images.githubusercontent.com/11514927/76255502-82646000-620b-11ea-82f1-30cb041ec139.png)

**Comment by lvuch** [comment]
Agreed @tfiduccia, @westlywright  the icon be smaller and moved to the right

**Comment by westlywright** [comment]
@tfiduccia @lvuch I'm on it

**Comment by jiaqiluo** [comment]
This is validated on master-head with the built-in UI-index `https://releases.rancher.com/ui/latest2/index.html`

Before the fix:
<img width="1426" alt="Screen Shot 2020-03-09 at 6 00 16 PM" src="https://user-images.githubusercontent.com/6218999/76269695-e7ca4800-622f-11ea-8700-5fa868295998.png">

After the fix:
<img width="1380" alt="Screen Shot 2020-03-09 at 6 00 07 PM" src="https://user-images.githubusercontent.com/6218999/76269698-ebf66580-622f-11ea-8d15-800bd3c265c2.png">
