### ISSUE TITLE
cronSchedule does not have a default value

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25855]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- From the UI, Give the `Recurring Security Scan Interval (cron)` = <blank> while creating the cluster.
- The cron value is NOT set for the cluster.

**Expected Result:**

- When no value is sent for the `Recurring Security Scan Interval (cron)`, API should have the default value in place for the `cronSchedule` param
- UI should send the default value for the field when the cluster is being created.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest - commit id: `63306835a`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom rke
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by izaac** [comment]
#25933

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/10/2020)` commit id: 8ede17d10

Default value from API configuration is now `0 0 0 * *`  Validated this is getting set properly.
