### ISSUE TITLE
Schedule scan options should be disabled for a Windows cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25864]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a custom cluster.
- Select Network provider Flannel and Enable WIndows, 

**Expected Result:**
Schedule scan options should be disabled or hidden from the User for a Windows cluster

**Actual Result:**
Schedule scan options are enabled and available for the user for a windows cluster

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head ui tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/09/2020)` commit id: 926997017

The option is disabled in the UI and can't be selected if Windows Support is enabled in the Flannel Network provider.
