### ISSUE TITLE
Tests that are skipped in the Permissive CIS scan run, have action "Skip" enabled on the UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25863]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Run Scan - 1.4 - Permissive on a cluster
- When the scan report is ready, click on the Scan report.
- The Skipped tests have action "Skip" available on the UI and the tests can be skipped

<img width="1343" alt="Screen Shot 2020-03-06 at 9 09 55 PM" src="https://user-images.githubusercontent.com/26032343/76137198-d9411e00-5fee-11ea-9eb7-d3019d56e504.png">

**Expected Result:**
Skipped tests from a Permissive cluster scan, should NOT have Skip action.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest  commit id: `63306835a`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): do rke
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by codyrancher** [comment]
@leodotcloud 
Unless there's something I missed I believe this is a backend issue. The report says skip state even though I don't have anything configured to be skipped in the config map. Should these be marked as not applicable instead?

**Comment by izaac** [comment]
N/A state results have the skip button enabled but those also shouldn't have it. According to https://github.com/rancher/rancher/issues/25857

Should we follow up the N/A skip button in this issue instead? 

@sowmyav27 @leodotcloud

**Comment by codyrancher** [comment]
1. The skipped tests here are actually rancher default skips
2. I disagree that the skip button shouldn't be present here. We don't differentiate between profiles in the skip config map we only differentiate between benchmarks. I think we should respect whatever is in the config map for these. We've also always showed the skip button for skipped tests.

**Comment by sowmyav27** [comment]
Reopening this to keep a track of the changes we discussed during an offline demo session.

**Comment by codyrancher** [comment]
Just for the context.

We're removing the CIS skip button because we decided the current UX is poor and we don't want to spend a tremendous amount of effort making a marginally better UX in the short time we have left. We intend to  redesign skipping in 4.x likely using something such as "Custom Profiles".

**Comment by sowmyav27** [comment]
For a permissive profile, on latest master-head commit id: `570461823`, ui tag: latest2 - skip buttons are NOT available in the report.
Closing the issue
<img width="1443" alt="Screen Shot 2020-03-11 at 9 42 32 AM" src="https://user-images.githubusercontent.com/26032343/76441811-418c5880-637d-11ea-944e-b3b3d78a51eb.png">
