### ISSUE TITLE
Can't delete Device Binding

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2586]
Version - Master with reskin UI

Steps:
1.  On Add Service screen go to Advance Options
2.  Click on Security/Host tab
3.  Click on + to add a Device Binding
4.  Click on X to try to delete Device Binding

Results:
Nothing happens (same with Add Container)

Expected:
Should be able to delete that

**Comment by deniseschannon** [comment]
Verified with latest UI (evening 11/24)
