### ISSUE TITLE
K3s master node/arg details are not shown in cluster edit view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#25860]
Rancher server version - 3e9ab849f

Import a K3s cluster ( 3 control nodes and 4 worker nodes)
In "Edit Cluster" page , "K3S Node Information" section, select one if the nodes from "Master Node".
No information is displayed.

Errors seen in console:

<img width="1389" alt="Screen Shot 2020-03-06 at 7 12 14 PM" src="https://user-images.githubusercontent.com/4266958/76135785-2cab7000-5fdf-11ea-9942-a120d5fe700e.png">

**Comment by cjellick** [comment]
fyi, for clusters older than 1.17.4, you will not have this information available. So, UI should gracefully degrade

**Comment by sangeethah** [comment]
Tested with latest UI changes from master-head.

This issue is not reproducible anymore using imported k3 cluster version `1.16.3`
