### ISSUE TITLE
Failed to enable project monitoring.

### ISSUE THREAD

**Issue by cocotyty** [rancher/rancher#25867]
**What kind of request is this (question/bug/enhancement/feature request):**

bug
**Steps to reproduce (least amount of steps as possible):**

Enable project monitoring
**Result:**

Failed to install app project-monitoring. Error: release project-monitoring failed: secrets "prometheus-project-monitoring-additional-alertmanager-configs" is forbidden: exceeded quota: default-89tfn, requested: secrets=1, used: secrets=1, limited: secrets=0
<img width="1352" alt="WX20200307-212212@2x" src="https://user-images.githubusercontent.com/2241753/76144296-bfb8d880-60b9-11ea-8394-76bb2d96a08f.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

v2.3.5
- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
metal
- Kubernetes version (use `kubectl version`):

```
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false```

**Comment by loganhz** [comment]
It looks like your project doesn't have enough quota for creating new secrets for project monitoring.

Please go to `Edit Project` page and check your project resource quota and default namespace resource quota in that page.

When you enable monitoring in a resource quota configured project, Rancher will create a new namespace in that project with the default namespace resource quota.

**Comment by MKlimuszka** [comment]
Closing this ticket as the last comment explains the issue, and monitoring v1 is end of life.
