### ISSUE TITLE
K3s import - Support for Node args/env details to be shown in k3 import clusters. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#25868]
Rancher server version - Build form master - `3e9ab84`

When importing k3 cluster with version - `1.17.3` , we do not see  Node args/env details to be shown in Node detail or cluster edit pages.

<img width="1138" alt="Screen Shot 2020-03-06 at 8 44 08 PM" src="https://user-images.githubusercontent.com/4266958/76145717-da02a000-6040-11ea-8f65-8f2ee6d72613.png">

We need the support for showing Node args/env details  in K3s  `1.17.x`  releases.

**Comment by cjellick** [comment]
Will only be in 1.17.4

**Comment by aaronRancher** [comment]
Node args/env details are seen in k3s version `v1.17.3-alpha1+k3s1`
Tested on Rancher server `rancher\rancher:master-head` `version 570461823 `

![Screen Shot 2020-03-11 at 9 14 26 AM](https://user-images.githubusercontent.com/57409052/76443378-8d400180-637f-11ea-850f-e734948c6d64.png)

**Comment by aaronRancher** [comment]
k3s information from a worker node:
![Screen Shot 2020-03-11 at 11 32 47 AM](https://user-images.githubusercontent.com/57409052/76452543-8a98d880-638e-11ea-9578-e630e6322959.png)
As `K3S_TOKEN` is a secret, the field is hidden.
