### ISSUE TITLE
K3S Import : Should not be allowed to save invalid values (0/negative values ) for control and master concurrency.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#25874]
Rancher server version - `25f16c370`

Currently we are allowed to enter invalid values (0/negative values ) for control and master concurrency and these incorrect values gets saved in the  cluster's  "k3supgradeStrategy".

Expected behavior:
API should error out in this case.

Also editing cluster version after this does not result in upgrade to be triggered .

**Comment by sangeethah** [comment]
Will test once the types changes to  be included  in rancher repo.

**Comment by cjellick** [comment]
looks like types got updated. moving over

**Comment by sangeethah** [comment]
Tested with latest build from master - `e78e43fea`

API fails with following error message - "Validation failed in API: k3sConfig `k3supgradeStrategy=InvalidFormat 422: serverConcurrency=MinLimitExceeded 422:`
