### ISSUE TITLE
ignored worker node during cluster upgrade never comes up active later 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#25872]
rancher/rancher:master-head `fec37fb7e3a4`

Steps:
- power off a worker node before upgrade, shows up `Unavailable` in UI 
- trigger cluster upgrade 
- upgrade logic marks the node for upgrading - `reconciling` 
- add an ignore label to the node 
- cluster upgrade gets completed, cluster becomes active 
- power on the node 

Expected: 
- node becomes active 

Result: 
- node stays in the upgrading reconciling state 

Note: 
- node actually gets upgraded correctly, just the conditions don't get set correctly 
- if the node is not labeled, but instead maxUnavailableWorker is adjusted, everything works as expected

<img width="1325" alt="Screen Shot 2020-03-07 at 1 30 34 PM" src="https://user-images.githubusercontent.com/16870565/76152727-e81fe300-6077-11ea-8dae-585fce9cb95c.png">

**Comment by soumyalj** [comment]
rancher/rancher:master-head 926997017

Steps:

1. Power off a worker node W1 before upgrade, shows up Unavailable in UI
2. Trigger cluster upgrade
3. Upgrade logic marks the node W1 for upgrading - reconciling
4. Add an ignore label to the node
5. Cluster upgrade gets completed, cluster becomes active
6. Power on the node and remove the label
The node is not upgraded and does not come to active state


 




node becomes active

**Comment by kinarashah** [comment]
@soumyalj Tested this thrice, not able to reproduce it on upstream master, could you give it a try again?

**Comment by soumyalj** [comment]
@kinarashah : Tested with latest master(0519da989) . The issue did not reproduce so far.

**Comment by soumyalj** [comment]
Tested with latest master with the above steps. The issue is fixed. 
But in Step 6 above, if the label is not removed, the node still gets upgraded. 
This issue is tracked here :
https://github.com/rancher/rancher/issues/25935
