### ISSUE TITLE
K3s Imports: When upgrade is not attempted on a k3s version , UI still reports this version as cluster's version.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#25876]
Rancher server version - 25f16c370

Import k3s cluster (`1.16.3` in mycase)
Enter invalid values (0/negative values ) for control and master concurrency and these incorrect values gets saved in the cluster's "k3supgradeStrategy" . This should not be allowed at the API level - Issue tracked in https://github.com/rancher/rancher/issues/25874

Edit cluster k3 version and upgrade it to `1.16.7`.
This does not trigger any upgrades. 

But UI reports the k3s cluster version to be `1.16.7` in cluster list view.

<img width="971" alt="Screen Shot 2020-03-07 at 9 05 40 PM" src="https://user-images.githubusercontent.com/4266958/76156989-6d76b800-60b7-11ea-9426-681f6f54dee3.png">

Expected behavior:
UI should  report the actual version of the cluster which is `1.16.3` which is present in  `"verson":"gitVersion": "v1.16.3-k3s.2"` and not the from `"k3sConfig":"kubernetesVersion"`

**Comment by westlywright** [comment]
@sangeethah I am confused here

> UI should NOT report the actual version of the cluster which is 1.16.3 which is present in "verson":"gitVersion": "v1.16.3-k3s.2" and not the from "k3sConfig":"kubernetesVersion"

It is reporting the version from the `k3sConfig` which is what it should do. You edited the version (`1.16.7`) and saved it. The fact that the backend didn't trigger an upgrade has nothing to do with the UI. The only reason we fallback to the `gitVerson` is if we dont have the k3sConfig. If the config was invalid the backend should not have saved it and responded with an error. In that case the UI should not show the new version because it should not have been saved in the config.

**Comment by sangeethah** [comment]
@westlywright That was a typo , corrected it . Its should be 
```
UI should report the actual version of the cluster which is 1.16.3 which is present in "verson":"gitVersion": "v1.16.3-k3s.2" and not the from "k3sConfig":"kubernetesVersion"
```

**Comment by sangeethah** [comment]
@cjellick @westlywright  , When Upgrade does not get attempted at all , k8s version will NOT be the one from "k3sConfig":"kubernetesVersion" . This is the version user intends to upgrade to . 

"k3sConfig":"kubernetesVersion" will always report the current version of k3s right ?

**Comment by westlywright** [comment]
IMO if the k3sConfig has a version that is the one that should be reported. How is the UI supposed to know which version is the source of truth if in some random cases the k3sConfig version isn't the correct one?

**Comment by cjellick** [comment]
How does RKE clusters behave in this scenario? Do we immediately show the desired version or do we show the actual reported version?

**Comment by cjellick** [comment]
@westlywright - Sangeetha's team compared the functionality to RKE in the scenario where an RKE upgrade failure occurs. RKE displays the actual current version, not the desired version. I'd like to see the same behavior with k3s. 

>  How is the UI supposed to know which version is the source of truth if in some random cases the k3sConfig version isn't the correct one?

In kubernetes, you have desired state and actual state. The k3sConfig is the desired state. The version field is the actual state. It is always the source of truth for the actual version of the cluster.

Note: the invalid value issue that lead to uncovering this behavior has been addressed in a separate PR.

**Comment by khushboo-rancher** [comment]
Tested on master-2417-head- 01c482d . Issue is resolved.

1. Imported a k3s cluster(1 control, 1 worker).
2. Concurrency 0/negative is not allowed to enter now from UI/API.
2. Tried upgrading it from v1.16.3 to wrong kubernetes version -v1.17.3+k3s2.
3. Cluster didn't get upgrade.
4. Cluster list view showed v1.16.3
