### ISSUE TITLE
CIS scan with Profile=NULL runs RKE-CIS-1.5 Permissive scan but the results are incorrect

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25877]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- From the API run scan with default values for all input values except `Profile=NULL`
- The scan run on the Rancher UI shows it is RKE-CIS-1.5 Permissive scan run.

<img width="1271" alt="Screen Shot 2020-03-07 at 9 31 47 PM" src="https://user-images.githubusercontent.com/26032343/76157299-b2045280-60bb-11ea-9009-cf2fe7e65761.png">

**Scan run with Profile=NULL**
<img width="1323" alt="Screen Shot 2020-03-07 at 9 35 53 PM" src="https://user-images.githubusercontent.com/26032343/76157302-c0526e80-60bb-11ea-94fd-6fca57af4de1.png">

**Actual RKE-CIS-1.5 Permissive run on the cluster**
<img width="1312" alt="Screen Shot 2020-03-07 at 9 36 03 PM" src="https://user-images.githubusercontent.com/26032343/76157307-cb0d0380-60bb-11ea-8d2c-626192e9af27.png">

**Expected Result:**
@leodotcloud Question:
When Profile=NULL, what should be the expected CIS scan run? Is it RKE-CIS-1.5 Permissive scan by default? 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `63306835a`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO 
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by leodotcloud** [comment]
@sowmyav27 yes, if no profile is specified, permissive is used. Will fix the issue.

**Comment by sowmyav27** [comment]
@leodotcloud @deniseschannon @cloudnautique At the API level, when no profile is specified, should Permissive be the default profile to be used for the scan?

**Comment by maggieliu** [comment]
Permissive should be the default.

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/10/2020)` commit id: e78e43fea

Using NULL in the API now triggers the`Permissive` profile by default and benchmark version 1.5. 
Triggering with null matches the results of running the `rke-cis-1.5` Permissive test results.
