### ISSUE TITLE
If label has a uppercase letter, it doesn't show up in the Value drop-down

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2587]
Version - Master with reskin UI

Steps;
1.  Add a label to a host that where Key = Abc and Value is Abc
2.  Add another label where Key is bCd and Value is bCd
3.  Go to Add Service or Add Container
4   Under Advanced Options go to Scheduling
5.  Add a Scheduling Rule

Results:
Notice in the Key drop-down that the Abc and bCd have been changed to lower case, and if you select them, the Value field does not change to a drop-down.

Expected:
Value field should have drop-down with abc for key abc and bcd for key bcd.

Comments:
I noticed that this only happens when the Key field actually has a uppercase letter in it.  So it seems when we change the key to lowercase it no longer associates it to it's Value.  So:

**Comment by ebr** [comment]
@tfiduccia might be related? https://github.com/rancher/rancher/issues/1844

**Comment by vincent99** [comment]
yes
