### ISSUE TITLE
K3S Import - Cluster stuck in "Upgrading" state when upgrade was attempted when 1 worker node was powered off and then powered on.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#25882]
Rancher Server Version - `25f16c370`

Steps to reproduce the problem;
1. Import k3 cluster with k3s version -“1.16.3” having 1 control and 2 workers.
2. Power down 1 worker node  ("Unavailable" state in UI)
3. Upgrade k3s version to “1.16.7” with control and master concurrency set to 1.
4. Control node got upgraded to new k3s version.
5. Cluster was stuck in “upgrading” state - Message said “Upgrading control node” even though it has upgraded control node.
6. Power on worker node.
7. Node gets to “active” state.

I see this message - “Worker node being upgraded” , but don’t see worker node being upgraded ( It is not getting to cordoned state)

![imageedit_2_4946362863](https://user-images.githubusercontent.com/4266958/76169288-e582c380-6133-11ea-8cfc-a129abd8c9a3.png)
![imageedit_1_9874817193](https://user-images.githubusercontent.com/4266958/76169290-e74c8700-6133-11ea-815c-713925f5b386.png)

**Comment by dweomer** [comment]
I think the root cause here is the low (default) backoff limit that the SUC configures jobs with. This can be modified in the system chart. I will submit a PR for that to adjust.

**Comment by cjellick** [comment]
@daxmc99  your earlier pr addresses the status sticking I. “...control plane”?

**Comment by cjellick** [comment]
Never mind. Looks like it was separated

**Comment by daxmc99** [comment]
Doesn't appear to be any work in Rancher needed here. @dweomer is going to bump the system-chart and make some changes to SUC.

**Comment by dweomer** [comment]
Additional mitigation from rancher/system-upgrade-controller#48

**Comment by cjellick** [comment]
I'm removing Dax as this has been addressed at the system-upgrade-controller level.

**Comment by khushboo-rancher** [comment]
Tested in master-23409-head 8ede17d10
Worked as expected.
Steps:
1. Imported k3 cluster with k3s version -“1.16.3” having 1 control and 2 workers.
2. Powered down 1 worker node ("Unavailable" state in UI)
3. Upgraded k3s version to “1.16.7” with control and master concurrency set to 1.
4. Control node got upgraded to new k3s version.
5. Cluster was stuck in “upgrading” state - Message said “Upgrading worker node which was powered down"
6. Powered on worker node.
7. Node became “active”.
8. Cluster upgraded t0 16.7 successfully.

Above was tested with concurrency of worker as 2, Upgrade started for both the worker node at same time and stuck for powered off node only. On making the node power on upgrade worked fine.
