### ISSUE TITLE
Let user specify public IP address of the host during agent registration

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2588]
As host can have multiple interfaces, we should let user specify public ip address of the host so it can be used by services like Route53

**Comment by mishak87** [comment]
I think this is already implemented via `CATTLE_HOST_IP` in UI (checked on v1.0.1) and in [docs](http://docs.rancher.com/rancher/faqs/agents/#how-does-the-host-determine-ip-address-and-how-can-i-change-it-what-do-i-do-if-the-ip-of-my-host-has-changed-due-to-reboot).
