### ISSUE TITLE
[Feature request]Ability to trigger alert for scheduled Etcd snapshot backup

### ISSUE THREAD

**Issue by nickngch** [rancher/rancher#25887]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Description:**
It would be nice to have the ability to trigger the alert when the schedule Etcd backup is failed

gz#8824
gz#10830

**Comment by Tejeev** [comment]
Frequently in support calls, I find the backup infrastructure has a previously unknown and unresolved issue as the user had no indication of if backups were still working or not.  It's also not clear when backups may have started failing unless we are lucky and an S3 bucket has not been cleared out.  

It would be _very_ helpful if there was a way to alert a user when backups have failed or failed to be uploaded to the bucket.  For a good production-grade solution, this should actually check a md5sum or in some other way confirm that the backup is in the bucket, can be downloaded, and is not an empty or corrupted file.

**Comment by panho66** [comment]
+1

**Comment by Martin-Weiss** [comment]
We need this, too!
