### ISSUE TITLE
how to custom notification and alertmanager?

### ISSUE THREAD

**Issue by kaybinwong** [rancher/rancher#25891]
the alertmanager was overwrite after config.

how to custom notification and alertmanager?

https://github.com/rancher/rancher/blob/87d8349119a0574718ca95170221f7adbe3e141f/pkg/controllers/user/alert/configsyncer/configsyncer.go#L221

**Comment by bentastic27** [comment]
@kaybinwong right now custom edits are not supported.

https://github.com/rancher/rancher/issues/22389
