### ISSUE TITLE
UI - CIS Scan page should include profile details

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25890]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Navigate to Cluster --> Tools --> CIS scans
- The UI should display profile details along with the scan run.

<img width="1334" alt="Screen Shot 2020-03-08 at 10 01 05 PM" src="https://user-images.githubusercontent.com/26032343/76184601-c9aa0c80-6189-11ea-879b-724065bbba20.png">

**Expected Result:**
The UI should display profile details along with the scan run.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head UI tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom 
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/10/2020)` commit id: 8ede17d10

Validated this information appears now in the CIS scans page.
