### ISSUE TITLE
Ingress with multiple path is not working, working only with default path

### ISSUE THREAD

**Issue by shash81** [rancher/rancher#25903]
I have create a ingress, one service with multiple port, one pod has multiple container port,
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /   

spec:
  tls:
      - secretName: abc-test
        hosts:
        - host.servicenode.com
  rules:
  - host: host.servicenode.com
    http:
      paths:
      - path: /
        backend:
          serviceName: myservice
          servicePort: 2222
      - path: /test
        backend:
          serviceName: myservice
          servicePort: 8778
when i deployed it on cluster only default path is working while /test is not working
both port are also part of same pod and same service i.e myservice
any way to solve this issue

**Comment by JerryCurl** [comment]
you have a rewrite annotation that is sending all to "/"

**Comment by shash81** [comment]
how should I correct this

**Comment by shash81** [comment]
@JerryCurl  any pointer to fix this issue?

**Comment by shash81** [comment]
seems to be working fine
