### ISSUE TITLE
CIS Scan Alert UI when a second rule is added to the alert group the settings are not saved

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25904]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Add a new alert group and alert using the Security Scan target
2. Validate this new alert is working fine (you're receiving alerts to the notifier)
3. Add a new Alert Rule to this Alert Group (created in step 1)
4. Select Security Scan as Target and then try to select _Completed Scan_ or _Has Failures_.

**Result:**

At this point I've seen two different behaviors:

1. The Radio buttons are both selected in the UI and then can't be deselected, but Create can be clicked.
2. You can select one of the options and click Create

And the alerts won't get delivered.

Both ends in the rule not having a Target and its condition as "Not Configured"

<img width="870" alt="Screen Shot 2020-03-09 at 11 04 42 AM" src="https://user-images.githubusercontent.com/27659/76243640-d9f7d100-61f5-11ea-9ad5-74e1114fd8a0.png">

**Environment information**
- Rancher version: `2.4 master-head (03/09/2020)` commit id: 926997017
- Installation option (single install/HA): single

**Comment by izaac** [comment]
Dupe of https://github.com/rancher/rancher/issues/25853 closing.

**Comment by codyrancher** [comment]
Reopening as this appears to be a separate issue. It looks like subsequent alerts aren't being saved as security scans.

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/09/2020)` commit id: 17bd84f8d

First added Alert Rule works, and subsequent Rules added to group works as expected now.
