### ISSUE TITLE
UI for updating the description for all feature flag

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25909]
The description for all feature flags should come from the API.

Note for QA: Need to test the upgrade also.

Backend Issue: rancher/rancher#25817

**Comment by rancher-max** [comment]
#### Fresh install of master-2408-head `Rancher version e78e43fea` Validation:
![image](https://user-images.githubusercontent.com/55997940/76335202-674c2b80-62b1-11ea-9455-312865e4c445.png)
- Checked that these descriptions match with what shows in the API `.status.description` field
- Deactivated dashboard and see the same results as well.


#### Upgrade from v2.3.5 to master-2408-head `Rancher version e78e43fea` Validation:
Before Upgrade:
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/55997940/76336275-fdcd1c80-62b2-11ea-8977-9070565eec0f.png">
- Also checked API and saw no description field

After Upgrade:
![image](https://user-images.githubusercontent.com/55997940/76337565-c65f6f80-62b4-11ea-89af-cfa72c838f6c.png)
- Checked that these descriptions match with what shows in the API `.status.description` field
