### ISSUE TITLE
[k3s-upgrade] Workload-apply-k3s-worker-plan stuck while upgrading cluster from v1.16.3 to v1.16.7.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/rancher#25907]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Import a k3s cluster with version v1.16.3 (1 master node, 2 worker nodes)
2. Upgrade the cluster to v1.16.7 (Drain server/worker node being false and concurrency being 1)

**Result:**
Cluster -> system -> Workload -> apply-k3s-worker-plan one of the pods is stuck in initialization state.
<img width="924" alt="Screen Shot 2020-03-09 at 11 01 58 AM" src="https://user-images.githubusercontent.com/60111667/76247417-c1d78000-61fc-11ea-9ad8-e566fec43647.png">
<img width="1023" alt="Screen Shot 2020-03-09 at 11 10 05 AM" src="https://user-images.githubusercontent.com/60111667/76247773-504c0180-61fd-11ea-8b53-bc5fae38441c.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2399-head - 926997017
- Installation option (single install/HA): Single

**Comment by cjellick** [comment]
@galal-hussein the prepare container should be more fault tolerant in this case and treat the absence of the master plan the same as the plan not being completed

**Comment by cjellick** [comment]
i've co-assigned @galal-hussein. He will be making changes to the prepare container and this should be included in those changes.
But @daxmc99 we should investigate a little bit to see if the master plan really was not created and if not, why

**Comment by daxmc99** [comment]
[container.log](https://github.com/rancher/rancher/files/4308827/container.log)
Included log of a successful prepare pod

**Comment by cjellick** [comment]
I've removed Dax from the assignee list. This will be addressed in two ways:
1. By making the framework more resilient (this is the same fix as https://github.com/rancher/rancher/issues/25882)
2. Making the `prepare` step more resilient such that it does not fail if it cannot find the master plan.

**Comment by cjellick** [comment]
Note: @daxmc99 will have to update the rancher logic to not hardcode the prepare image in order for this to work properly.

**Comment by daxmc99** [comment]
All PRs have been merged, moving to test

**Comment by cjellick** [comment]
There was one remaining bit that just got merged: https://github.com/rancher/k3s-upgrade/pull/15
This addressed the concern:
> Making the prepare step more resilient such that it does not fail if it cannot find the master plan.

**Comment by cjellick** [comment]
Actually, can you just double check with @galal-hussein before going testing? He had some trouble getting artifacts to push properly, so just check with hi before testing.

**Comment by khushboo-rancher** [comment]
Tested on master-2417-head- 01c482d5f . Issue is resolved.

Imported a cluster(1 control plane and 2 workers). Upgraded the k3s version from v1.16.3 to v1.16.7.

On getting empty master plan, it retried finding plan after sleep of 5 sec and didn't exit.
<img width="1079" alt="Screen Shot 2020-03-11 at 3 43 36 PM" src="https://user-images.githubusercontent.com/60111667/76471456-eb84d880-63af-11ea-8182-e6eb0a694e87.png">
