### ISSUE TITLE
Worker nodes stuck in "draining" state during K8s upgrade when one control node is OFF and ignore label is added

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#25906]
Version: master-head

Steps:

1. Create a rancher setup with k8s version v1.15.10-rancher
Configuration: 1 etcd, 3 control(C1, C2, C3) and 3 workers (N1, N2, N3)
2. Power OFF one worker node C1
3. Upgrade cluster to K8s v1.16.7 set 
```
max_unavailable_control=1
max_unavailable_worker=70%
```
Upgrade does not proceed as one control node is off
4. Add a label to the control node "user.cattle.io/upgrade-policy=prevent"
Upgrade proceeds for the control nodes.
5. The worker nodes are stuck in draining state as below:

Logs below:
```
grace-period=0 --ignore-daemonsets=true --timeout=60s
2020/03/09 18:12:00 http: proxy error: failed to find Session for client c-kwkt9
2020/03/09 18:12:00 http: proxy error: failed to find Session for client c-kwkt9
2020/03/09 18:12:00 http: proxy error: failed to find Session for client c-kwkt9
2020/03/09 18:12:00 http: proxy error: failed to find Session for client c-kwkt9
2020/03/09 18:12:00 [ERROR] nodeDrain: kubectl error draining node [soumyaregworker1] in cluster [c-kwkt9]: 
2020/03/09 18:12:00 [INFO] Draining node soumyaregworker1 in c-kwkt9 with flags --delete-local-data=false --force=false --grace-period=0 --ignore-daemonsets=true --timeout=60s
2020/03/09 18:12:00 [INFO] Draining node soumyaregworker2 in c-kwkt9 with flags --delete-local-data=false --force=false --grace-period=0 --ignore-daemonsets=true --timeout=60s
2020/03/09 18:12:00 http: proxy error: failed to find Session for client c-kwkt9
2020/03/09 18:12:00 http: proxy error: failed to find Session for client c-kwkt9
2020/03/09 18:12:00 http: proxy error: failed to find Session for client c-kwkt9
2020/03/09 18:12:00 http: proxy error: failed to find Session for client c-kwkt9
2020/03/09 18:12:00 [ERROR] nodeDrain: kubectl error draining node [soumyaregworker1] in cluster [c-kwkt9]: 
```

<img width="1533" alt="Screen Shot 2020-03-09 at 11 14 56 AM" src="https://user-images.githubusercontent.com/18536626/76245896-f72e9e80-61f9-11ea-9573-f8e5f2ba6276.png">

**Comment by kinarashah** [comment]
@deniseschannon 
This is happening because the control plane node is powered off and had an ignored label. Rancher's code around dialer and session management doesn't respect this label, and I don't know if it's within the scope to now go and change it. 

Before zero downtime feature, if you powered off a control plane node and tried to drain a worker node, you'd see the same exact behavior.

**Comment by deniseschannon** [comment]
With the design change of removing the ability to "ignore" control plane nodes, this use case is no longer relevant.

**Comment by soumyalj** [comment]
Closing the issue as the use case is not relevant.
