### ISSUE TITLE
Rancher app does not respect Helm v3 dependencies settings

### ISSUE THREAD

**Issue by jaczie** [rancher/rancher#25900]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1) Create Helm Chart.yaml and set:
apiVersion: v2
add dependencies section with conditon as described in HELM v3 documentation
2) Evaluate condition to be false (e.g. set it to false in values.yaml)
3) Make helm package e.g. helm package -u <helm_dir>
4) Push package to the Helm repository
5) Add helm repository to the catalog in rancher (cluster scope)
6) In Rancher UI deploy application from the catalog

**Result:**
App will not respect condition (sub chart will be always deployed) 

**Other details that may be helpful:**
This does not happen when we use Helm v2 and add dependency inside requirements.yaml file.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.1

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported from AWS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud
- Kubernetes version (use `kubectl version`): 1.14

**Comment by deniseschannon** [comment]
Helm 3 isn't supported in Rancher for deploying catalog apps and will be added as part of v2.4 (https://github.com/rancher/rancher/issues/20596)

**Comment by jaczie** [comment]
@deniseschannon thank you for the information, I think this issue may be closed in such case
