### ISSUE TITLE
Cannot deploy a helm3/helm2 compatible chart through Pipeline using helm3

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#25910]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Enable Github Auth
2. Add a catalog and have it use helm3. I chose https://argoproj.github.io/argo-helm
3. Setup a Pipeline to use the Deploy Catalog App step, and have it use a chart from the catalog that you added:
![image](https://user-images.githubusercontent.com/55997940/76254675-20572b00-620a-11ea-8c53-b316d9d37834.png)
4. Save and run the pipeline

**Result:**
The app fails to install. Below screenshots are from the pipeline and app page in the UI. 

![image](https://user-images.githubusercontent.com/55997940/76254795-4e3c6f80-620a-11ea-8dbf-29dd0737eb91.png)

![image](https://user-images.githubusercontent.com/55997940/76257342-bdb45e00-620e-11ea-9918-bc7b8eb274c8.png)

Rancher server logs show both:
```
2020/03/09 21:02:05 [ERROR] AppController p-j5rl7/pipeline-argo [helm-controller] failed with : wait helm template rendering notes failed. manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: clusterroles.rbac.authorization.k8s.io "pipeline-argo-server-cluster-role" is forbidden: User "u-ncndi22mpn" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
: exit status 1
```

**Other details that may be helpful:**
- This happens whether steve is enabled or disabled.
- This chart also fails with this error when helm2 is specified instead of helm3 for the catalog

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2399-head (`Rancher version 926997017`)
- Installation option (single install/HA): single

**Comment by rancher-max** [comment]
This may be chart specific..
I was able to deploy chartmuseum using rancher's version and the default helm version from here https://kubernetes-charts.storage.googleapis.com/ using both helm2 and helm3

**Comment by brendarearden** [comment]
When looking into this issue, it seems like this original issue was chart specific and this error was also part of the initial steve errors. With the proxy being turned off by default now, we are seeing a user permission issues when the pipeline tries to deploy the chart which creates crds - this doesn't seem to be helm related so I am not sure if that an additional issue with the steve changes or something else.

**Comment by rancher-max** [comment]
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/55997940/76661036-a55a8100-6537-11ea-97e4-f8f01c6e3a8d.png">

```
Wait helm template rendering notes failed. manifest_sorter.go:192: info: skipping unknown hook: "crd-install" manifest_sorter.go:192: info: skipping unknown hook: "crd-install" manifest_sorter.go:192: info: skipping unknown hook: "crd-install" Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: clusterroles.rbac.authorization.k8s.io "pipeline-argo-test-helm3-server-cluster-role" is forbidden: User "u-lw3zi2qgyc" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope : exit status 1
```
^^ Error message for copy pasting

**Comment by deniseschannon** [comment]
@brendarearden Based on the comment, does pipeline have the ability to deploy helm3 charts? I'm not sure how pipeline triggers app deployment.

**Comment by brendarearden** [comment]
The pipeline successfully deploys chartmuseum from our library as both helm 2 and helm 3. It appears the permission issue we are seeing is specific to that chart/catalog and it does not work for helm 2 or helm 3. I verified that the same permission issue was happening in pipelines with https://argoproj.github.io/argo-helm argo in rancher v2.3.5. This does bring up a potential gap in which user we are using for the pipeline, but its unrelated to the helm2/3 changes

**Comment by rancher-max** [comment]
I validated @brendarearden's comment above and also other charts using helm3 through pipeline. I agree this is chart specific.
