### ISSUE TITLE
Upgrading state on cluster when worker nodes are upgrading should be shown in yellow 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25917]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster
- Upgrade k8s version
- when the control and etcd nodes are getting upgraded, the status of the cluster is "Updating" and the color of the state shown is "Yellow"

<img width="1442" alt="Screen Shot 2020-03-09 at 11 18 51 AM" src="https://user-images.githubusercontent.com/26032343/76267357-b8afd880-6227-11ea-8281-8d48f3836650.png">

- When the worker nodes are upgrading, color of the status "Upgrading" is Blue.
<img width="1432" alt="Screen Shot 2020-03-09 at 11 18 58 AM" src="https://user-images.githubusercontent.com/26032343/76267383-c9604e80-6227-11ea-82d6-77a6eccc22d9.png">

**Expected Result:**
Upgrading state on cluster when worker nodes are upgrading should be shown in yellow 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - latest - commit id: 926997017
- Installation option (single install/HA):single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.15 to 1.16
```

**Comment by deniseschannon** [comment]
This is a UI issue when introducing a new state.

**Comment by kinarashah** [comment]
The new state for cluster is "upgrading", and it's set when worker nodes get upgraded for RKE clusters.

**Comment by westlywright** [comment]
@kinarashah @deniseschannon why are we not using the same verbiage for worker nodes vs other control plane and etcd nodes? I can add the state to the UI easily enough but the question still stands.

**Comment by sowmyav27** [comment]
**Verified on latest master-head - ui tag: latest2**

- When the worker nodes are upgraded, it is seen in "Yellow"  
<img width="1308" alt="Screen Shot 2020-03-25 at 10 08 10 AM" src="https://user-images.githubusercontent.com/26032343/77565244-2d6a5000-6e81-11ea-949a-54e47f09a98a.png">
