### ISSUE TITLE
Upgrading rancher causes cluster-alerting app to upgrade and subsequently fail

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#25914]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Add a notifier (can use dummy values)
2. Add an alert group in a project (see screenshot at end for my configuration in System project)
3. Verify the cluster-alerting and monitoring-operator apps are fully deployed and are on version 0.0.7
4. Upgrade to master-head
5. Navigate to the System > Apps page. 

**Result:**
cluster-alerting has been upgraded to 0.0.8 and failed upgrade.
monitoring-operator is still 0.0.7 and is running successfully.

**Other details that may be helpful:**
cluster-alerting should upgrade by default, and that upgrade should pass. I see this in the server logs:
```
2020/03/09 22:13:49 [INFO] Installing chart using helm version: rancher-helm
[main] 2020/03/09 22:13:49 Starting Tiller v2.16.3-rancher1 (tls=false)
[main] 2020/03/09 22:13:49 GRPC listening on :50852
[main] 2020/03/09 22:13:49 Probes listening on :43292
[main] 2020/03/09 22:13:49 Storage driver is ConfigMap
[main] 2020/03/09 22:13:49 Max history per release is 10
[tiller] 2020/03/09 22:13:49 getting history for release cluster-alerting
[storage] 2020/03/09 22:13:49 getting release history for "cluster-alerting"
2020/03/09 22:13:49 http: proxy error: dial tcp 127.0.0.1:6443: connect: connection refused
[storage/driver] 2020/03/09 22:13:49 query: failed to query with labels: an error on the server ("") has prevented the request from succeeding (get configmaps)
[tiller] 2020/03/09 22:13:49 preparing update for cluster-alerting
[storage] 2020/03/09 22:13:49 getting deployed releases from "cluster-alerting" history
2020/03/09 22:13:49 http: proxy error: dial tcp 127.0.0.1:6443: connect: connection refused
[storage/driver] 2020/03/09 22:13:49 query: failed to query with labels: an error on the server ("") has prevented the request from succeeding (get configmaps)
[tiller] 2020/03/09 22:13:49 failed to prepare update: an error on the server ("") has prevented the request from succeeding (get configmaps)
[tiller] 2020/03/09 22:13:49 performing force update for cluster-alerting
[storage] 2020/03/09 22:13:49 getting last revision of "cluster-alerting"
[storage] 2020/03/09 22:13:49 getting release history for "cluster-alerting"
2020/03/09 22:13:49 http: proxy error: dial tcp 127.0.0.1:6443: connect: connection refused
[storage/driver] 2020/03/09 22:13:49 query: failed to query with labels: an error on the server ("") has prevented the request from succeeding (get configmaps)
UPGRADE FAILED
Error: an error on the server ("") has prevented the request from succeeding (get configmaps)
2020/03/09 22:13:49 [ERROR] AppController p-9whmn/cluster-alerting [helm-controller] failed with : failed to install app cluster-alerting. Error: UPGRADE FAILED: an error on the server ("") has prevented the request from succeeding (get configmaps)
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2401-head `Rancher version 0519da989`
- Installation option (single install/HA): single

![image](https://user-images.githubusercontent.com/55997940/76262810-982d5180-621a-11ea-948d-ed952722ef42.png)

**Comment by deniseschannon** [comment]
I think this is related to your changes or related to steve is having issues with deploying apps (see https://github.com/rancher/rancher/issues/25742)

**Comment by rancher-max** [comment]
#### Validated Upgrade from Rancher v2.3.5 to Rancher v2.4.0-rc3

Followed same steps as in this issue:
- Initial version of cluster-alerting was 0.0.7, and after upgrading it successfully upgrades to 0.0.8
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/55997940/76557647-3149ab80-6459-11ea-88b1-c7b455536086.png">

- As a side note, Monitoring and Istio also are still operating and functional after rancher server upgrade
