### ISSUE TITLE
Reconcile is not happening on the powered off worker node

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25913]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Have a custom rke cluster - 1 etcd, 1 control plane and 10 worker nodes.
2. Max Unavailable Worker = 1
3. Power down 2 worker nodes - W1 and W2
4. The nodes W1 and W2, will be seen in `Unavailable` state on the UI
5. Upgrade k8s version to 1.16 from 1.15
6. The control and etcd nodes go through upgrade process. 
7. Cluster is seen in `Upgrading` state.
8. The state of the nodes W1 and W2 is `Unavailable`

**Expected Result:**
The nodes W1 and W2 should be in `Upgrading` (reconciling) state (one of the these)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `17bd84f8d`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom RKE 
- Kubernetes version (use `kubectl version`):

```
(paste the output here)1.15 to 1.16
```

**Comment by deniseschannon** [comment]
@kinarashah If the node is powered off, would we ever expect this node status change to `Upgrading`?

**Comment by kinarashah** [comment]
Earlier, the unavailable nodes did go to upgrading/reconciling, but now only active nodes will go through upgrading process. We'd still update unavailable nodes with latest node plan so they come up active with new config, but they won't be shown as upgrading and would count towards maxUnavailable nodes.

**Comment by sowmyav27** [comment]
**On master-head - latest - commit id: `8b8ed06d3`**

**Scenario:**

- maxUnavailable worker = 1
- number of worker nodes in cluster - 4, power down one worker node
- Upgrade cluster changing max-pods
- Control and etcd nodes are upgraded. Worker nodes do not get upgraded
- unavailable node - remains in Unavailable state. The cluster goes into `Upgrading` state.
