### ISSUE TITLE
Cluster stuck in upgrading when a worker node is powered off

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25912]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Have a cluster deployed - 1 etcd, 1 control plane and 5 worker nodes - k8s 1.15
2. Add label - `user.cattle.io/upgrade-policy=prevent` to node W1
3. Upgrade max-pods to '101'
```
kubelet:
      extra_args:
        max-pods: '123'
```
4. Node W1's max-pods will not upgraded. But the upgrade of cluster goes through. And cluster comes up `Active`
5. Power off a worker node W2.
6. The node will be in "Unavailable" state in UI.
7. After sometime the cluster is seen in `Upgrading` state

**Actual Result:**
Cluster is stuck in Upgrading state

**Expected Result:**
The cluster should NOT go in `Upgrading` state.

**Other details that may be helpful:**
No edit was performed on the cluster after the node was powered down.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id:  `926997017`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by deniseschannon** [comment]
Since the label no longer exists, I don't think this use case is relevant.

**Comment by sowmyav27** [comment]
**Verified on master head - commit id: `8b8ed06d3`**

- Adding label `user.cattle.io/upgrade-policy=prevent` on a worker node, does not prevent it from being upgraded.
