### ISSUE TITLE
Delete k3s upgrade jobs after 15 minutes

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#25929]
The jobs that are created to handle a k3s upgrade should be deleted 15 minutes after they reach a terminal state. The terminal state can either be success or a failure but either way, they should be cleaned up after 15 minutes.

Note that deleting a failed job after 15 minutes would also cause the system upgrade controller to schedule a new job on the node where that job was. So, if the node was stuck in upgrading for some reason, this would cause it to retry.

A user should also be able to edit a job and delete/clear out the TTL so that the job is never cleaned up. This would be useful for debugging purposes, to ensure a failed job doesn't get removed.

**Comment by cjellick** [comment]
The system-upgrade-controller repo has a corresponding issue:
https://github.com/rancher/rancher/issues/25929

When you test and close this, can you also test and close the issue in sys-up-controller?

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 570461823

Upgrade jobs are not getting deleted after 15-30 minutes post-upgrade. 

Job config appears correct:
```
jobConfig": {
"activeDeadlineSeconds": 900,
"backoffLimit": 99,
"completions": 1,
"parallelism": 1
},
"jobStatus": {
"active": 0,
"completionTime": "2020-03-11T23:27:15Z",
"completionTimeTS": 1583969235000,
```

The upgrader app is `0.4.0-rc1`

**Comment by dweomer** [comment]
so, the jobs that are hanging around are completed and look to be missing `.spec.ttlSecondsAfterFinished`. If I `kubectl` edit these in-place to add `ttlSecondsAfterFinished` the edit works but the value disappears. I suspect that either the job controller is overriding edits to completed jobs or that the TTL Controller for Finished Resources which is off by default (behind a feature gate) is seeing that field and removing it before the SUC can delete the job.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4.0-rc3

Upgrade jobs now have the correct `ttlSecondsAfterFinished` and the jobs are deleted 15 minutes after the upgrade has completed.
