### ISSUE TITLE
Feature Request: Auth0 Integration

### ISSUE THREAD

**Issue by jlambright** [rancher/rancher#2592]
It seems like using a system like [Auth0](https://auth0.com/) would be very beneficial for the Rancher console.

**Comment by jlambright** [comment]
I'm willing to work on this. But I

**Comment by jlambright** [comment]
[Sorry about accidental close.]

I'd lie to propose a version of rancher, that has Auth0 burned in as the authentication/authorization platform. So fare I thought of two scenarios.

Scenario 1) All the user would have to do, is provide the following new parameters.

AUTH0_CLIENT_ID (This is generated as part of creating an Auth0 app/api auth application.)
AUTH0_DOMAIN (This is created when a user initially creates their Auth0 account <UNIQUE_DOMAIN>.auth0.com.)

This would get passed along, as environment variables, to EmberJS and therefore Auth0 would be preconfigured on launching Rancher.

Scenario 2) Much like what is currently done, the user would have to configure the Auth0 authentication on first boot.

Any thoughts?

**Comment by vincent99** [comment]
All the auth configs are exposed as `{provider}Config` resources so it can be setup by the UI.  I don't expect we would accept any PR that added a new auth provider but did not expose it the same way.  The config is ultimately all `settings` though, which can all be set at startup with environment variables.  

Really the bulk of the work would be integrating (in Java, the [cattle](https://github.com/rancher/cattle) repo) with their API to authenticate requests and provide user & group identities for mapping authorization to environments.

**Comment by jlambright** [comment]
I reached out to the support at Auth0, and agreed that this shouldn't be a problem. There is even a possibility of presenting the user an option with connecting to an existing Auth0 account/app, or making a new one, at first launch. Once I get more of the nuts and bolts worked out, we should be able to get something going.

**Comment by jlambright** [comment]
So I've been going over this, and I'm a bit curious about why Spring's security module apparently isn't being used (maybe I missed it, but I couldn't find it being imported)? Is there a specific reason behind this?

The reason I bring it up, is because Auth0 has existing Spring Security integration. If that Spring module is of the table, we can find another way. Just thought I'd check.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by ricricucit** [comment]
wouldn't be a bad idea to reconsider opening this, maybe?
