### ISSUE TITLE
test_host_api_hoststats fails when admin client tries to list projects.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2593]
Server version - Build from master - Nov 6
```
___________________________ test_host_api_hoststats ____________________________

client = <cattle.Client object at 0x7f9c27356710>
admin_client = <cattle.Client object at 0x7f9c27323bd0>

    def test_host_api_hoststats(client, admin_client):
        hosts = client.list_host(kind='docker', removed_null=True)
        assert len(hosts) > 0

        stats = hosts[0].hostStats()
        conn = ws.create_connection(stats.url + '?token=' + stats.token)
        result = conn.recv()
        conn.close()
        assert result is not None
        assert result.startswith('[')

>       project = admin_client.list_project()[0]
E       IndexError: list index out of range
```

**Comment by hibooboo2** [comment]
Interesting. Not sure how that is failing. Do you have any logs from the server?

**Comment by ibuildthecloud** [comment]
@hibooboo2. Can you just run this one validation test locally?  This doesn't look like a random issue.

**Comment by sangeethah** [comment]
This test case had failed last 3 times when validation tests are executed against latest server ( from master). This set up is git hub auth enabled setup.

**Comment by hibooboo2** [comment]
Looking at it, when github auth is enabled validation tests cannot run currently because when the admin client fixture lists projects to get the hosts it has none because it is not a member of the default project where the hosts are. In order to fix this we have to change the way the test pick the project to act as.

**Comment by sangeethah** [comment]
test_host_api_hoststats test cases are now executing fine and reporting success.
