### ISSUE TITLE
worker nodes are upgraded when they have label "user.cattle.io/upgrade-policy=prevent"

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25935]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Bring up a cluster - 1 etcd, 1 control plane and 5 worker nodes.
- Max Unavailable worker = 1
- Power down one of the worker nodes.
- Update the following in cluster.yml

```
    kubelet:
      extra_args:
        max-pods: '124'
```

- The cluster goes into Updating state.
- The control and etcd nodes get upgraded.
- The worker node which was powered down is stuck in upgrading.
- Cluster state is stuck in Upgrading status.
- Now label the powered down worker node with "user.cattle.io/upgrade-policy=prevent"
- The upgrade automatically goes through.
- The other worker nodes get upgraded. The cluster comes to Active state.
- Now power on the Powered down worker node (N1).

**Expected Result:**
The worker node N1 should NOT get upgraded with max-pods = 124

**Actual Result:**
The worker node N1 gets upgraded with max-pods = 124

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master- head - commit id: `e78e43fea`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.15
```

**Comment by deniseschannon** [comment]
With the new changes for labels, once a worker only node is attempted to be upgraded and fails in any way, it will be part of the maxunavailable set unless it's fixed or removed. Applying the label will not prevent it to be upgraded.

**Comment by sowmyav27** [comment]
**Verified on master head - commit id: `8b8ed06d3`**

- Adding Label `user.cattle.io/upgrade-policy=prevent` on a node does not prevent it from being upgraded.
