### ISSUE TITLE
CIS Scan - scheduled scans shouldn't remove manual scans

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25944]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Enable scheduled scans set the retention count to 1
- Execute 1 CIS scan manually
- Wait for the scheduled scan to get triggered.

**Result:**

The user will end up with one scheduled scan listed in the CIS Scan list page. The manually generated CIS scan gets deleted.

Manually executed CIS Scans shouldn't get touched by the scheduled scans.

**Other details that may be helpful:**

**Environment information**
- Rancher version: `2.4 master-head (03/10/2020)` commit id: 8ede17d10
- Installation option (single install/HA): single

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `330a4bed0`**

1. Deploy a cluster - 1 etcd, 1 control and 1 worker.
2. Enable CIS schedule scans and give cron time = 10 * * * *. (for example) and retention count = 2
3. Scheduled scan will run on the 10th minute that hour. 
4. Run few manual scans
5. Edit cluster change cron time = 12 * * * *. 
6. Scheduled scan will run on the 12th minute that hour. 
7. Edit cluster change cron time = 13 * * * *. 
8. Scan run in Step 3 will be deleted. And a new Scheduled scan will be generated for the cluster.
9. Manual scans do not get deleted.
