### ISSUE TITLE
Allow ignoring unhealthy controller-manager, scheduler.

### ISSUE THREAD

**Issue by Vad1mo** [rancher/rancher#25942]
Make it configurable to ignore unhealthy controller-manager, scheduler as some managed K8s provider restrict accessing the hardcoded port on localhost.

```sh
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused   
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused   
```

A fix was implemented some time ago in the UI, but only for azure. 
I think it would make sense to provide a more general purpose solution, as more and more k8s provider disable it. Also it is a [deprecated](https://github.com/kubernetes/enhancements/issues/553) and will be removed one day.  

Here is the link to the pull request the brought in the fix for Azure AKS.
https://github.com/rancher/ui/pull/2976/files

**Comment by deniseschannon** [comment]
I'm closing this in favor of https://github.com/rancher/rancher/issues/11496#issuecomment-727641496
