### ISSUE TITLE
CIS Scan - scheduled scan keeps trying to execute after the cluster is deleted

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25943]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Create a cluster and enable scheduled CIS Scans
- Delete the cluster

**Result:**

After some time the Scheduled scan tries to get executed in the deleted cluster:

```
2020/03/10 23:23:03 [ERROR] ClusterScanController scheduledscan/c-vk7cw:23 * * * * [scheduledScanHandler:sync] failed with : scheduledScanHandler: sync: error fetching cluster c-vk7cw: cluster.management.cattle.io "c-vk7cw" not found
```

**Other details that may be helpful:**

**Environment information**
- Rancher version: `2.4 master-head (03/10/2020)` commit id: 8ede17d10
- Installation option (single install/HA): single

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `330a4bed0`**

- Deploy a cluster.
- Enable Scheduled CIS scan on the cluster. 
- Deleted the cluster
- Scheduled scan does not run on a deleted cluster.
