### ISSUE TITLE
cluster agent and node agent start failed

### ISSUE THREAD

**Issue by zffocussss** [rancher/rancher#25949]
**Error messages in the pod**

```
ERROR: https://localhost/ping is not accessible (Failed to connect to localhost port 443: Connection refused)
```

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
I follow the suggestion of rancher

**Result:**
NAME                                   READY   STATUS             RESTARTS   AGE
cattle-cluster-agent-8668888d5-zt7fb   0/1     CrashLoopBackOff   7          12m
cattle-node-agent-4cgmm                0/1     CrashLoopBackOff   17         67m
cattle-node-agent-vjtnm                0/1     CrashLoopBackOff   17         67m

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.3.5

- Installation option (single install/HA): single running with docker locally

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AKS/2C/4G
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
17.09.1-ce
```

**Comment by tcouper** [comment]
I have the same problem following an upgrade to latest stable from v2.2.3
