### ISSUE TITLE
Rancher pull failing with Docker 1.9.0 and legacy docker registries

### ISSUE THREAD

**Issue by mohan08p** [rancher/rancher#2594]
When trying to pull images from a legacy docker registry (quay.io), I get this warning:

Status: Downloaded newer image for rancher/server:latest
docker.io/rancher/server: this image was pulled from a legacy registry.  
Important: This registry version will not be supported in future versions of docker.
2b776c2771357874cb7071b21bbdd745545a2f40a65ece648fce06b759f42105

So, basically I got the image but, this might be some warning that the images are to be put into /v2/ registry endpoint instead of remaining in the old /v1/ registry.

**Comment by deniseschannon** [comment]
@cloudnautique Can you take a look to see if this affects us?

**Comment by cloudnautique** [comment]
I believe this was caused by the migration to registry V2 by Docker. They dropped support for clients <1.5.

**Comment by deniseschannon** [comment]
rancher/server is in dockerhub and already v2 registry. 

If you are downloading from quay.io, then you might have copied the rancher/server image into it?
