### ISSUE TITLE
--force-upgrade on a service creates new datavolumes

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#2595]
When upgrading the Jenkins or Hadoop stacks that have data volumes by running:

`rancher-compose -p jenkins up --force-upgrade jenkins-ci` 

The new containers end up with new data-volumes, and possibly on new hosts. In the case of Jenkins and Hadoop, we want the original datavolume to be retained and used by the new containers.

When running the Jenkins upgrade, I have just changed the metadata in rancher-compose.yml.

**Comment by ibuildthecloud** [comment]
I believe this is a rancher compose issue.  I'll investigate more.

**Comment by deniseschannon** [comment]
Verified datavolume fix with v0.5.3-rc1 and v0.47.0-rc1

Steps I took:
1. Launch Jenkins using catalog service
2. Copy docker-compose.yml and rancher-compose.yml to rancher-compose CLI
3. Make some changes to the jenkins plugins (remove some plugins)
4. Run `rancher-compose up --force-upgrade jenkins-primary`

The datavolume is maintained.
