### ISSUE TITLE
Upgraded cluster from 2.3.5 does not have the default values for maxUnavailable worker and control

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25951]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy a cluster in 2.3.5
- Upgrade to master 
- Edit on the cluster.
- The default values for maxUnavailable_worker and Drain is not seen

<img width="1285" alt="Screen Shot 2020-03-11 at 12 12 11 AM" src="https://user-images.githubusercontent.com/26032343/76431743-4518e300-636f-11ea-94e0-d69e08f7db98.png">

- maxUnavailable_control is not available in Edit as YAML.

**Expected Result:**
Default values for the maxUnavailable_worker and Drain should be seen. maxUnavailable_control should be available in Edit as YAML

**Note:**
View in API of the cluster --> does NOT show the maxUnavailable_worker/control/drain params

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `570461823`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.15
```

**Comment by mrajashree** [comment]
I don't see how we can set these values without user doing a cluster edit action. But it must be operating and doing cluster upgrades with the expected default values right? @sowmyav27

**Comment by deniseschannon** [comment]
@mrajashree How is this a UI only issue? We have had plenty of other enhancements where we've added in new fields and the default is set during upgrade.

**Comment by mrajashree** [comment]
@deniseschannon From offline discussion with @codyrancher since the default values for these fields are present in `/v3/schemas/nodeUpgradeStrategy` on the upgraded setup, they should be populated from that in the UI

**Comment by rancher-max** [comment]
Giving a value for "Maximum Worker Nodes Unavailable" now in UI on `master-2450-head` (`Rancher version 73f603f9f`) gives error: `invalid value for IntOrString: invalid value "": strconv.Atoi: parsing "": invalid syntax`. This worked last week.

There is no workaround that I can tell right now so it blocks us from upgrading kubernetes versions on a cluster.

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/17/2020)` commit id: ddda7cb8d

Validated the default value after upgrading from `v2.3.5` is **10** percentage:

<img width="366" alt="Screen Shot 2020-03-17 at 10 51 34 AM" src="https://user-images.githubusercontent.com/27659/76886097-801e8900-683d-11ea-8e52-9e725ed72de1.png">

maxUnavailable in the API shows 10 too.

Drain default value in UI is **No**.
Drain default value in the API is **false**.

Editing the cluster and saving the settings also works.
