### ISSUE TITLE
Please allow setting of pod-max-pids via UI

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#25950]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Request:**
The Rancher UI currently provides UI support for project- and workload-level resource limits for CPU and memory. But it's not possible through the Rancher UI (except by editing cluster.yaml directly) to set the --pod-max-pids option for the kubelet, which limits the number of PIDs that each pod can utilize concurrently. 

As this is an important limit to set in multi-tenant clusters, to prevent fork-bomb pods from wreaking havoc in the cluster, we propose that the flag be promoted to a first-class UI widget in the cluster creation and templating system.

**Comment by skaven81** [comment]
Note that if Rancher makes this a first-class configuration option, that this will also require some additional configuration updates in the nginx ingress controller.  By default, the nginx ingress controller creates 64 threads per worker, and one worker per core.  Every thread consumes one PID.  So even for very generous values of --pod-max-pids (e.g. 1000), it does not take many CPUs before nginx consumes all available PIDs.  For example, on a system with 40 cores, nginx requires over 2,500 PIDs.  Setting the nginx `worker-processes` option in the ConfigMap to some reasonable value (such as 4 or 8) by default will ensure that the ingress controller won't fail to start.
