### ISSUE TITLE
CIS Scan - Improve UX of Run Scan Modal

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#25961]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement/design

**Other details that may be helpful:**
We are going to add a section beneath the profile selector of the run scan modal. This section is responsible for informing the user of which tests will not be run and why. 

There will be two subsections Not Applicable and Skipped tests. Skipped tests will only be shown for permissive profiles since hardened tests shouldn't skip anything.

**Comment by codyrancher** [comment]
Here are screenshots of what we intend to create.
![Screen Shot 2020-03-11 at 12 44 37 PM](https://user-images.githubusercontent.com/55104481/76460454-4233e780-639b-11ea-9c35-2e13b7a1d60f.png)

![Screen Shot 2020-03-11 at 12 44 47 PM](https://user-images.githubusercontent.com/55104481/76460450-419b5100-639b-11ea-95ae-24fe26157346.png)

![Screen Shot 2020-03-11 at 12 45 01 PM](https://user-images.githubusercontent.com/55104481/76460444-406a2400-639b-11ea-81a0-8e92a7fdc455.png)

**Comment by sowmyav27** [comment]
**Verified on latest master-head commit id: `` , ui tag: latest2**

- The UI after Run Scan is clicked is 

<img width="1163" alt="Screen Shot 2020-03-16 at 1 56 31 PM" src="https://user-images.githubusercontent.com/26032343/76799009-f663b280-678d-11ea-9e01-9fad9ad8d3e9.png">

<img width="1243" alt="Screen Shot 2020-03-16 at 1 56 36 PM" src="https://user-images.githubusercontent.com/26032343/76799018-f82d7600-678d-11ea-87d5-0a9ede02c73c.png">


**Logged issues:** 
- https://github.com/rancher/rancher/issues/26065

**Comment by izaac** [comment]
I've closed #26056 in the latest `2.4 master-head` build commit: 148b3e000
From @sowmyav27 I also think #26066 will make easier to differentiate between Rancher Skips and user Skips.

Besides that I think we're good to close.
