### ISSUE TITLE
Gitlab integration for pipeline fails

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#25975]
**Rancher Version:**
v2.3.5, or v2.2.x/v2.3.x

**Steps to reproduce (least amount of steps as possible):**
1. Add a cluster
2. Go to the default project - tools - pipeline
3. Configure Gitlab authentication

**Result:**
Got an error showing:
```
Fail to get accesstoken with oauth config
```

**Other details that may be helpful:**
1. It breaks using public Gitlab service, and recent Gitlab versions.
1. It works for private Gitlab in previous versions including `11.11.8-ce.0/12.1.17-ce.0/12.4.7-ce.0`(haven't tested the rest)

**Cause**
In recent Gitlab version, the Oauth API returns `Bearer` token type instead of `bearer` as shown in the [docs](https://docs.gitlab.com/ee/api/oauth2.html), making the condition check [here](https://github.com/rancher/rancher/blob/5ee70d01459132fa3cd575abecfc501cc864d70a/pkg/pipeline/remote/gitlab/gitlab.go#L94) fails.

**Workaround**
For private Gitlab setup, use a previous Gitlab version as the workaround.
For public Gitlab users, wait for the fix.

**Comment by DoNotSayYes** [comment]
**Reproduced the issue on 2.3.5**
- Deploy a cluster.
- Go to the default project - tools - pipeline
- Configure Gitlab authentication

**Result:**
- Got an error which is saying:
```
   Fail to get accesstoken with oauth config
```
**See a screenshot here:** 
![Fail to get accesstoken with oauth config](https://user-images.githubusercontent.com/57614736/77034159-37ed9b00-69e4-11ea-8cf8-7f4909cfeb28.png)



-------------
**Verified with master-head - commit id: ```2709ab2``` and on 2.3-head commit id: ```48bf013```**

**Test Steps:**
- Deploy a cluster.
- Go to the default project - tools - pipeline
- Configure Gitlab authentication

**Result:**
```
Gitlab authenticated.
```

**See screenshots here:**
![image](https://user-images.githubusercontent.com/57614736/77034249-72573800-69e4-11ea-8ae7-2fe39d6a717a.png)
![image](https://user-images.githubusercontent.com/57614736/77034265-784d1900-69e4-11ea-871d-3b85e19d84be.png)

**Comment by sunliusi** [comment]
any solution for rancher v2.3.5?
