### ISSUE TITLE
UI - CIS Scan Issues

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25970]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Issue#1**

- The Total count of tests is missing.
- We need this, because the CIS 1.4 and CIS 1.5 scan tools, run different sets of tests on the cluster. The user does not have an idea, how many tests are available in total in CIS 1.4 vs CIS 1.5 runs, and why is he seeing different counts
<img width="1271" alt="Screen Shot 2020-03-11 at 6 31 50 PM" src="https://user-images.githubusercontent.com/26032343/76478647-9accaa00-63c6-11ea-8e33-9ee729ed9ac2.png">

**Issue#2**

- The tests in the report details page is sorted by test "State"
- Currently tests are sorted by state:

- - Fail
- - Skipped
- - Passed
- - N/A

<img width="1337" alt="Screen Shot 2020-03-11 at 6 37 17 PM" src="https://user-images.githubusercontent.com/26032343/76478918-5db4e780-63c7-11ea-81b5-452900b8c5e0.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown  - rancher - master- head - UI tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by codyrancher** [comment]
This is intended. We decided to remove the total for two reasons.
1. Having a scan pass and then have the passed column read "40 of 70" was misleading.
2. We didn't add it as a separate column because we couldn't think of a way that the information would be actionable.

The email @maggieliu sent out regarding the summary and action items of the demo included:

> Removed the total count from the "pass/skipped/failed/not applicable

**Comment by sowmyav27** [comment]
Closing the issue based on Cody's comments.

They are as per requirement
