### ISSUE TITLE
UI issues while deploying workload

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25974]
**What kind of request is this (question/bug/enhancement/feature request):** bug 

**Steps to reproduce (least amount of steps as possible):**
Go to a cluster --> Default Project --> Workload --> Deploy

**Issue#1**
- In `Workload Type` section, "Delete" from keyboard the contents of `Scalable deployment of _ Pods` field.
- The contents change to 0
<img width="1270" alt="Screen Shot 2020-03-11 at 8 56 53 PM" src="https://user-images.githubusercontent.com/26032343/76485903-091b6780-63db-11ea-8b83-9ca01e4645c3.png">

**Issue#2**
- Click on Add port in the same window from above ^^^
- In the `Publish the container port` field, hit "Delete" from keyboard
- The contents change to 1
<img width="1293" alt="Screen Shot 2020-03-11 at 8 58 51 PM" src="https://user-images.githubusercontent.com/26032343/76485972-3ff17d80-63db-11ea-9a87-12d454965377.png">

**Issue#3**
- From above step, in the same window, In the field `On listening port` , the value is always defaulted to 30000, when you hit "Delete" from keyboard or enter a number say 3000 and click on another field.
<img width="1277" alt="Screen Shot 2020-03-11 at 9 01 10 PM" src="https://user-images.githubusercontent.com/26032343/76486054-74653980-63db-11ea-8622-e80b8860cee1.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest - commit id: `570461823` ui tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO rke
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by sowmyav27** [comment]
Verified on latest master-head - ui tag: latest2 

**Issue#1** -- seen fixed
- In Workload Type section, "Delete" from keyboard the contents of Scalable deployment of _ Pods field.
- The contents get deleted
<img width="1315" alt="Screen Shot 2020-03-13 at 2 21 21 PM" src="https://user-images.githubusercontent.com/26032343/76660391-126d1700-6536-11ea-9f61-8cbeee834fb8.png">


**Issue#2** -- seen fixed

- Click on Add port in the same window from above ^^^
- In the Publish the container port field, hit "Delete" from keyboard
- The contents get deleted

**Comment by westlywright** [comment]
@sowmyav27 I do not think that #3 should halt this ticket being closed. We already talked about this. The cluster you are using has `kubeApi.serviceNodePortRange` set in the config, in this case the min value of 30000 is valid. If you enter anything between 30000-32767, the valid node port range on the `kubeApi` service, it will stay what you enter. If it lacks that range in the config on then any range between 1-65535 is valid. A decent test for this is an import cluster without that set and a DO cluster does have it set by default. The I think we should be able to close this and open another issue to discuss how we can make this clearer for end users.

**Comment by sowmyav27** [comment]
Logged issue - https://github.com/rancher/rancher/issues/26070 as per comments:  https://github.com/rancher/rancher/issues/25974#issuecomment-599632044

Closing this issue
