### ISSUE TITLE
CIS Scan - with multiple cluster clicking Run CIS Scan works the first time, but not for the next cluster 

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#25983]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Create two RKE clusters
- Wait for them to get into Active state
- In Global where the clusters are listed click `Run CIS Scan` in the first cluster
- Select the CIS Profile and click Run
- Wait for the Scan to finish or immediately `Run CIS Scan` in the second cluster
- Select the CIS Profile and click Run

**Result:**

Nothing happens. Checking the Browser Console I notice an error.

```
Uncaught TypeError: Cannot read property 'profile' of undefined
    at n.run (component.js:31)
    at n.send (action_support.js:19)
    at n [as send] (utils.js:365)
    at glimmer.js:8706
    at s (index.js:143)
    at glimmer.js:8705
    at e.n._run (backburner.js:1066)
    at e.n._join (backburner.js:1042)
    at e.n.join (backburner.js:759)
    at p (index.js:176)
```

**Other details that may be helpful:**

Refreshing the browser allows me to run the scan in the second cluster.

**Environment information**
- Rancher version: `2.4 master-head (03/12/2020)` commit id: 881b3e40d
- Installation option (single install/HA): single

**Comment by sowmyav27** [comment]
**Was able to see this issue on latest master-head** 

**Steps:**

- Run a scan on a cluster - select a profile
- When the scan is generated - Pass/Fail , run another scan again, click on Run. (default one in the dropdown)

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/16/2020)` commit id: 73f603f9f

Validated I no longer see this error anymore and I'm able to run multiple CIS scans from the Global cluster view. Both hardened and permissive.
