### ISSUE TITLE
[UI] Canont click on "K3s" hyperlink in cluster import description

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#25981]
master-2424-head

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Launch Rancher UI, click on the Add Cluster button
- Click on the "K3s" hyperlink in the description for the cluster import (See image below)

**Result:**
![image](https://user-images.githubusercontent.com/45179589/76547492-7c0ff700-644a-11ea-9f6b-edabfc6e0b53.png)
If you click on the "K3s" hyperlink, a new tab will not be opened bringing you to https://k3s.io, instead, you will be navigated to the import cluster page. We should either fix this or just not provide a hyperlink here.

Notice the 'S' is capitalized as well; it should not be unless used at the start of a sentence.

**Comment by davidnuzik** [comment]
Minor, nice-to-have.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-2425-head` `version 881b3e40d`

k3s hyperlink can now be clicked and a new tab will be opened to https://k3s.io
![Screen Shot 2020-03-12 at 4 21 21 PM](https://user-images.githubusercontent.com/57409052/76576020-1d647080-647e-11ea-9e33-dbd3256a5770.png)
