### ISSUE TITLE
[UI] Tweaks to K3s Information section on Node Details page (en-us translations)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#25993]
Master-head

**What kind of request is this (question/bug/enhancement/feature request):**
Task

**Steps to reproduce (least amount of steps as possible):**
We'd like to make some tweaks to two translation keys based on a UX design meeting around the K3s integration. The intent is to make it more clear to the user, that when viewing the K3s node args on the node details pages that these are the args supplied for startup.

**I'm requesting that we change the following:**
_%clusterDashboard.k3sInfo.nodeArgs.detail%_ becomes:
`Read only list of the K3s startup arguments for this node.`

_%k3sNodeEnvVarSection.detail%_ becomes:
`Read only list of the K3s startup environment variables for this node.`

**Note:**
I played around with the idea of the descriptions going in more detail like "Read only list of the K3s startup arguments supplied at run time or install time for this node." but this was rather long. I think most people should already understand these are the k3s args supplied when the user either ran them manually via the binary (or some other method) or via the install.sh script (curl install script).

**Additional Information:**
Screenshot of the area we are changing:
![image](https://user-images.githubusercontent.com/45179589/76569604-bb513e80-6470-11ea-97c6-5397516ea8e9.png)

**Comment by khushboo-rancher** [comment]
Tested on v1.17.3-alpha1+k3s1. Text appears as expected on node detail page.

<img width="1449" alt="Screen Shot 2020-03-15 at 11 50 08 AM" src="https://user-images.githubusercontent.com/60111667/76708368-72d59300-66b3-11ea-8cd5-439c4fe6a157.png">
<img width="1372" alt="Screen Shot 2020-03-15 at 11 50 30 AM" src="https://user-images.githubusercontent.com/60111667/76708370-749f5680-66b3-11ea-84b6-e4bf757c512d.png">
