### ISSUE TITLE
Upgrade process on a windows vs linux cluster is different

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25998]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On a windows cluster - 3 linux nodes - 1 etcd, 1 control and 1 worker node and 3 windows worker nodes, upgrade max-pods value to 124
- Max unavailable worker = 2

```
kubelet:
      extra_args:
        max-pods: '124'
```
- The cluster goes into **`Updating`** state.
- Etcd and control plane nodes get upgraded. 
- The cluster is still in **`Updating`** state. The add ons get upgraded now. 
- The worker nodes also start upgrading.
<img width="1323" alt="Screen Shot 2020-03-12 at 5 10 14 PM" src="https://user-images.githubusercontent.com/26032343/76587985-fd937380-64a2-11ea-8659-ca2a2670210e.png">

**The upgrade process seen in a linux cluster is:**

- Etcd and control plane nodes get upgraded. 
- The cluster is still in **`Updating`** state. The add ons get upgraded now. 
The cluster comes to `Active`, momentarily before the status changes to `Upgrading` - worker nodes upgrading
- And the worker nodes get upgraded one by one.

**Question:**
Why is there this difference during the upgrade process? Is this expected? 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head- commit id: `5ee70d014`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): linux cluster and windows cluster

**Comment by kinarashah** [comment]
@sowmyav27 Do you have the logs for this?

**Comment by sowmyav27** [comment]
Not able to reproduce the issue on master-head  commit id: `8b8ed06d3`

The windows cluster's upgrade process is similar to the linux cluster's upgrade

**Comment by sowmyav27** [comment]
Closing the issue

Will reopen if this is seen again.
