### ISSUE TITLE
rancher2.3.5与gitlab认证

### ISSUE THREAD

**Issue by zhangq123456** [rancher/rancher#26002]
使用离线部署的rancher2.3.5版本
在流水线进行gitlab认证的时候，提示超时
在集群中的其他容器上是可以正常访问gitlab

**Comment by loganhz** [comment]
If you would like to ask questions in Chinese, please add `rancher2` to join 
Rancher WeChat group. Thanks

Close in favor of https://github.com/rancher/rancher/issues/25975
