### ISSUE TITLE
gitee.com pipline

### ISSUE THREAD

**Issue by helloworldyuhaiyang** [rancher/rancher#26003]
**What kind of request is this (question/bug/enhancement/feature request):**

![30331584096703_ pic_hd](https://user-images.githubusercontent.com/10350492/76614809-c03eec80-655b-11ea-8fee-3d9fe764db99.jpg)

**Steps to reproduce (least amount of steps as possible):**
1.create pipeline (创建流水线)
2.choose gitlab (选则 gitlab)
3.choose private gitlab (使用私有gitlab企业版部署)

oatuth seems to be good。gitee.com has authorization rancher ok。but rancher 2.3.5 return error.(oauth 貌似都成功了.gitee 已经成功授权了 rancher。但是 rancher 返回了错误)

**Result:**

TestAndApply Error
{"status":"404","error":"Not Found"}: undefined 

**Other details that may be helpful:**

**Environment information**
rancher 2.3.5

**Cluster information**
```
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
If you would like to ask questions in Chinese, please add `rancher2` to join 
Rancher WeChat group. Thanks

Close in favor of https://github.com/rancher/rancher/issues/25975

**Comment by Leixiaodong** [comment]
me too

TestAndApply Error
{"status":"404","error":"Not Found"}: undefined
