### ISSUE TITLE
Namespace cattle-global-nt not assigned to System project

### ISSUE THREAD

**Issue by fmunteanu** [rancher/rancher#26001]
Running a HA cluster of 3 nodes, fresh install of Rancher 2.3.5.

For some reason namespace `cattle-global-nt` is not assigned to System project:

![Screen Shot 2020-03-13 at 2 51 12 AM](https://user-images.githubusercontent.com/19806136/76597033-f89be780-64d5-11ea-8f26-c997e4b4421c.png)

**Comment by ainiml** [comment]
Same on Rancher helm v2.4.3

![image](https://user-images.githubusercontent.com/28725423/81467466-be358a80-91a6-11ea-9f85-8fbd491769f0.png)


Component | Version
-- | --
Rancher | v2.4.3
User Interface | v2.4.22
Helm | v2.16.5-rancher1
Machine | v0.15.0-rancher36

**Comment by corentin59** [comment]
Same in Rancher v2.4.4

![image](https://user-images.githubusercontent.com/2035983/85005409-0ad29500-b159-11ea-8d36-7e0272096aba.png)

**Comment by wpwoodjr** [comment]
Seems to be fixed, in v2.4.8 `cattle-global-nt` is assigned to the `System` project

**Comment by superseb** [comment]
This was added via https://github.com/rancher/rancher/pull/27056, let us know if this happens in recent versions.
