### ISSUE TITLE
Agent on imported k3s cluster spamming for plans

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#26015]
The agent is getting a wait time of zero so it's hammering the rancher server for plans. 

image: rancher/rancher-agent:master-2433-head

**Comment by sowmyav27** [comment]
**Verified with latest master-head - commit id: `547c8dd3d`**

- On a k3s imported cluster
```
kubectl logs cattle-node-agent-w9smr  -n cattle-system | grep "plan monitor"
time="2020-03-14T03:07:45Z" level=info msg="Starting plan monitor, checking every 120 seconds"
```
