### ISSUE TITLE
KDM for k3s "minChannelServerVersion" does not work as expected

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#26011]
rancher/rancher:v2.4.0-rc3

* Import a k3s cluster
* Edit the cluster
* The user is unable to edit the k3s cluster version

https://releases.rancher.com/kontainer-driver-metadata/dev-v2.4/data.json shows 
```
"k3s": {
  "releases": [
   {
    "maxChannelServerVersion": "v2.4.0",
    "minChannelServerVersion": "v2.4.0",
    "version": "v1.17.3+k3s1"
   },
   {
    "maxChannelServerVersion": "v2.4.0",
    "minChannelServerVersion": "v2.4.0",
    "version": "v1.16.7+k3s1"
   }
  ]
 }
```

The releases API is empty
```
{"type":"collection","links":{"self":"http://url/v1-release/release"},"actions":{},"resourceType":"release","data":[]}
```

When updating `data.json` to include the following, the versions show as expected in UI and releases API:
```
min / max
2.5.0 / 2.6.0 - does not show as expected
2.3.0 / 2.5.0 - shows as expected
2.3.0 / 2.4.0 - shows as expected
```

**Comment by rmweir** [comment]
If you're on a version that is technically before 2.4.0, this includes 2.4.0-*, then anything with 2.4.0 or higher as a min won't show up. This is expected.

**Comment by sangeethah** [comment]
@rmweir Can we have the `minChannelServerVersion`  set to `v2.4.0-rc1`? This will be in line with how min rancher server versions are set for system charts- https://github.com/rancher/system-charts/blob/dev/charts/rancher-monitoring/v0.0.8/questions.yml.

Also this will be help with airgap testing of rc builds were it does not work out of the box and we did have to host a modified data.json to see the versions for upgrade testing.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-2469-head` `version 888029fb0`

Steps:
Create a k3s cluster. Installed with:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.0.1 sh -s - server
```
Import cluster
Edit the cluster

Result:
Kubernetes Version can be edited
![Screen Shot 2020-03-17 at 4 36 00 PM](https://user-images.githubusercontent.com/57409052/76911327-d73c5200-686d-11ea-8afa-9b281f259d2d.png)


https://releases.rancher.com/kontainer-driver-metadata/dev-v2.4/data.json shows
```
 },
 "k3s": {
  "releases": [
   {
    "maxChannelServerVersion": "v2.4.0",
    "minChannelServerVersion": "v2.4.0-rc1",
    "version": "v1.17.3+k3s1"
   },
   {
    "maxChannelServerVersion": "v2.4.0",
    "minChannelServerVersion": "v2.4.0-rc1",
    "version": "v1.16.7+k3s1"
   }
  ]
 }
}
```
