### ISSUE TITLE
When display k3s node args and environment variables, use ******** for omitted values

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#26025]
See: https://github.com/rancher/k3s/issues/1524

This issue is just to make sure we check this out in the Rancher UI and it looks good

This is waiting for a *K3s RC* of 1.17.4

**Comment by cjellick** [comment]
Available in:
v1.17.4-alpha1+k3s1

**Comment by aaronRancher** [comment]
The feature is verified with Rancher server `rancher\rancher:master-2469-head` `version 888029fb0`

Steps:
Provision a k3s multinode cluster (2 control, 2 worker)
Edit a node

Control plane:
k3s Information
<img width="1166" alt="Screen Shot 2020-03-18 at 10 11 00 AM" src="https://user-images.githubusercontent.com/57409052/76988666-4c596700-6902-11ea-8bde-f6cc1ea6f653.png">
Annotations
<img width="1146" alt="Screen Shot 2020-03-18 at 10 11 13 AM" src="https://user-images.githubusercontent.com/57409052/76988698-5bd8b000-6902-11ea-90ff-cff8f6936ea4.png">

Worker:
k3s information
<img width="1167" alt="Screen Shot 2020-03-18 at 10 19 14 AM" src="https://user-images.githubusercontent.com/57409052/76988714-61ce9100-6902-11ea-88df-8a4936d3ea39.png">
