### ISSUE TITLE
UI Color Issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2602]
List of Color Issues:

Main Stack screen
- [x] Sidekick grey background color same as grey part of grid color
- [x] the Blue line that underlines Applications on main menu and the highlight for Stack/Catalog sub-menu, makes it seem like there is a highlight bug.  This would be true for the other main menu titles and submenus. (added up arrows instead lv)
- [x] The color for a degraded Stack is the same "peachy" color that we are using to show the number of Containers.  Maybe degraded stack symbol should be red?

Stack Details Screen
- [x] Degraded text is kinda hard to see because it's a light peach color.
- [x] Can barely see the line between the Stack Name and the view icons.
- [x] The view icons (tiny dots, containers, etc...) are all light grey and look like they are disabled
- [x] + Scale up text is too light (can barely see it and it look like it's disabled)
- [x] The little green outline circle that says a service is running, it's hard to tell it's green and running because it's not solid green circle.

Main Host Screen & Host Details screen
- [x] Main - The little green outline circle that says a service is running, it's hard to tell it's green and running because it's not solid green circle.  
- [x] Main - Hard to see circle that tells you how many sidekicks you have.  I think it might be a light green outline circle here as well.  But hard to tell and see because of grey background.
- [x] Main - + Add Container text is too light and hard to see.
- [x] Details - Container & Storage tabs when unselected is almost same color grey as background.

Other Screens
- [x] All Screens - the light grey Title text for input fields make it look like this fields are unavailable?  This is especially noticeable on LDAP access control screen.  I'm not sure you would want to change this as it would have to be changed on every single screen, but thought I would bring it up.
- [x] All screens - Can barely see the grey line between the screen name and options.  Example: On the main stack screen, the line between the "Stacks" and the "Add Stack" button.
- [x] Environments & Setting dropdown from Main menu - The grey title text (All Environments, Your Accounts, This Environment) are too light.  Can barely see them.
- [x] Grids - Grey outline colors for grids is also very faint.
- [x] Alerts - The color on Alerts is orange, maybe it should red

**Comment by vincent99** [comment]
State colors should be some form of

Active/Running: green
Degraded: orange/yellow
Inactive/Stopped: red
Transitioning: something else (currently blue, which I like because not red or green)

**Comment by vincent99** [comment]
Running is a hollow circle vs solid to provide an alternate way to tell which is which for color-blind people.

**Comment by tfiduccia** [comment]
Version - Master with latest reskin UI
Verified fixed
