### ISSUE TITLE
CIS Scan does not run on a cluster with powered off nodes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26028]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster - 3 etcd, 2 control and 4 worker nodes
- Power off one worker node.
- Worker node status - `Unavailable` in the cluster
- Go to cluster --> Tools --> CIS scan --> Run scan --> Select profile
- The Scan is seen running.
- Report is not generated
- `security-scan-runner` Pod is seen running in System project

**Expected Result:**
The report should be generated for the cluster

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest - commit id: `547c8dd3d`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
v1.16.8
```

**Comment by sowmyav27** [comment]
Was able to reproduce this issue when a control node was powered down.
Scheduled scan - failed to run on the cluster.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `546b039e4`**

- Deploy a cluster - 2 control, 3 etcd, 3 worker nodes.
- Power off worker node W1
- Run CIS scan. Verified the scan report does not report W1 in the list of nodes.
- Power on worker node W1
- Run CIS scan. Verified the scan reports  W1 in the list of nodes.

Similar tests wrt to powering off/on control plane and etcd were verified. 
Verified the same for schedule scan also

**Comment by StrongMonkey** [comment]
CIS can't be run if the following is broken:
1. Metric server is not running. There is a known issue that helm will not work if metric api is not available. CIS app will fail to deploy. https://github.com/helm/helm/issues/6361
2. Coredns is not running. CIS relies on DNS internally so if dns is broken CIS run can't be finished.

**Comment by sowmyav27** [comment]
**Verified on latest master-head - commit id: `371ec137f`**

- Cluster spec - 1 etcd, 1 control plane and 5 worker nodes.
- Power off W5, cre dns and metrics server are NOT deployed on this worker node.
- Run CIS scan on the cluster
- The scan runs successfully. Report is generated.
- Report does not have the powered off node in its list of nodes.

```
"nodes":{
   "etcd":[
      "sowmya-etcd-cis-1"
   ],
   "master":[
      "sowmya-ctrl-cis-1"
   ],
   "node":[
      "sowmya-ctrl-cis-1",
      "sowmya-etcd-cis-1",
      "sowmya-wrk-cis-1",
      "sowmya-wrk-cis-2",
      "sowmya-wrk-cis-3",
      "sowmya-wrk-cis-4"
   ]
}
```
