### ISSUE TITLE
Validate new k8s versions - 1.17.4, 1.16.8 and 1.15.11

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#26026]

**Comment by sangeethah** [comment]
On latest `2.3-head` , we are presented with k8s versions `1.17.4`, `1.16.8` and `1.15.11`.

Automated run on k8s clusters created with the all the 3 k8s versions with 2 control , 3 etcd and 3 worker nodes succeeded. No new issues reported.

Also able to bring up clusters with following 4 network providers on all the above 3 k8s versions successfully using `v2.3.6-rc5` version :
1. Canal
2. Weave
3. Flannel
4. Calico

**Comment by sangeethah** [comment]
We will be getting new versions of `1.17.4`, `1.16.8` and `1.15.11` which includes the updated CNI (`calico-node:v3.13.0`) for addressing -  https://github.com/rancher/rancher/issues/23662

**Comment by superseb** [comment]
Available in `rancher/rancher:v2.3.6-rc6`

**Comment by rancher-max** [comment]
#### Fresh Install of v2.3.6-rc6 Validation

- Versions `1.17.4`, `1.16.8`, and `1.15.11` are available and install successful using all four network providers (`Canal`, `Weave`, `Flannel`, `Calico`).
- Installs with `Canal` and `Calico` both have the correct CNI image tags (`v3.13.0`)

#### Upgrade from v2.3.5 to v2.3.6-rc6
- In v2.3.5, installed k8s versions 1.17.3, 1.16.7, and 1.15.10 and ran pre-upgrade jobs on all 3 versions with `canal` and all 3 versions with `calico` (6 clusters total)
- Upgraded rancher server to v2.3.6-rc6
- Ran post-upgrade jobs successfully
- Upgraded k8s versions in all 6 clusters to be 1.17.4, 1.16.8, and 1.15.11. Validated cni images were upgraded successfully
- Ran post-upgrade jobs again successfully

**Comment by rancher-max** [comment]
Automated runs succeed on the clusters using the new calico versions.
