### ISSUE TITLE
UI - CIS Scan - Issue in Scan details page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26021]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Run scan on a cluster.
- Go to Cluster --> Tools --> CIS scans
- Click on the scan report
- Scan details page is open

<img width="1314" alt="Screen Shot 2020-03-13 at 3 06 00 PM" src="https://user-images.githubusercontent.com/26032343/76669244-173ac680-6548-11ea-85bf-cf057b125647.png">

- Expand the test result for a test to see the nodes on which the test was run.
<img width="1373" alt="Screen Shot 2020-03-13 at 3 05 51 PM" src="https://user-images.githubusercontent.com/26032343/76669248-199d2080-6548-11ea-99e3-b56085241d03.png">

**Expected Result:**
The row lines - are missing - and that should not be the case.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): latest2 - ui tag on latest master-head
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by codyrancher** [comment]
@sowmyav27 can you describe what row line is? Your screenshots look correct to me.

**Comment by codyrancher** [comment]
Nevermind. You're talking about the blue line at the top.

**Comment by sowmyav27** [comment]
@codyrancher the line on the top, the blue one, and also the lines below the pop up window.

**Comment by sowmyav27** [comment]
**verified on latest master-head commit id: `148b3e000` ui tag: latest2**

Issue is not seen anymore on expanding a test result in a CIS scan report details page
<img width="1272" alt="Screen Shot 2020-03-16 at 11 54 12 AM" src="https://user-images.githubusercontent.com/26032343/76790915-ff985380-677c-11ea-9658-a8a7a206b258.png">
