### ISSUE TITLE
Cluster stuck in upgrading as one worker node is powered down and CIS scan action cannot be performed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26020]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Have a cluster - 1 etcd, 1 control and 4 worker nodes.
- Max unavailable worker = 2
- Power down one worker node
- Do an upgrade on the cluster, change the max-pods to `124`.
- The cluster will go into `Updating state.
- The control and etcd nodes get upgraded.
- Other worker nodes get upgraded.
- The powered down worker node will be in `Unavailable` state and the cluster will be stuck in `Upgrading` state.
- CIS scan cannot be run on this cluster now.

**Question:**

- Do we want the cluster to be stuck in Upgrading state when one worker node is `Unavailable` ? 
- This is not the case during the cluster provisioning - where even when the worker nodes are in Registering/Unavailable status, the cluster is seen `Active`
- This might break any actions which can be taken on the cluster.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - latest - `2532ff801`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): do rke
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by kinarashah** [comment]
I don't know if this is a bug. @deniseschannon It was decided that cluster's going to be stuck in Upgrading if there are unavailable nodes. And there should be no state transition for unavailable nodes.

**Comment by deniseschannon** [comment]
Yes, this is as expected. Cluster should be stuck in Upgrading state until the node is fixed or removed from the cluster.
