### ISSUE TITLE
Cluster stuck in upgrading during a snapshot restore

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26031]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Have a cluster - 1 etcd , 1 control plane and 5 worker nodes
2. Max unavailable worker = 3, max Unavailable control = 1, drain = false
3. take a snapshot
4. Power down one contorl plane node
5. Upgrade k8s cluster from 1.16 to 1.17
6. The cluster is stuck in upgrading state, as there is one worker node - powered down.
7. other worker nodes get upgrade.
8. restore to snapshot taken in Step 3.
9. 4 worker nodes were considered for upgrade and the upgrade/restore failed
10. k8s on the 3 worker nodes, are upgraded to previous version - 1.16

```
2020/03/14 05:23:32 [DEBUG] cluster [c-h2qjf] worker-upgrade: workerNodeInfo: nodes 5 maxAllowed 3 upgrading 3 notReady 1 toProcess [] toPrepare [m-59rcs] done [m-9hntt m-69c8k m-tqlgt]
2020/03/14 05:23:32 [ERROR] NodeController c-h2qjf/m-69c8k [rke-worker-upgrader] failed with : cluster [c-h2qjf] worker-upgrade: more than allowed nodes upgrading for cluster: unavailable 4 maxUnavailable 3
```

**Expected Result:**
Restore snapshot should be successful

**Other details that may be helpful:**
Related to: https://github.com/rancher/rancher/issues/25861

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest - commit id: `547c8dd3d`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.16 to 1.17
```

**Comment by kinarashah** [comment]
Should be fixed after https://github.com/rancher/rancher/issues/25647

**Comment by mrajashree** [comment]
The restore PR for worker nodes isn't merged yet. And the issue #25647 is tracking it. Maybe we can close this then?

**Comment by maggieliu** [comment]
Closing this. Fix will be part of: #25647

**Comment by sowmyav27** [comment]
Verified on latest master-head - comiit id: ``

Steps:

- Have a cluster - 1 etcd , 1 control plane and 5 worker nodes
- Max unavailable worker = 2, max Unavailable control = 1, drain = false
- take a snapshot
- Power down one worker plane node W1
- Upgrade k8s cluster from 1.16 to 1.17
- The cluster is stuck in upgrading state, as there is one worker node - powered down W1.
- other worker nodes get upgraded.
- restore to snapshot taken in Step 3.
- The powered down node is taken up for Upgrading, it is Cordoned. The node is then stuck in Cordoned state.
- one more node, worker node, is also stuck in cordoned state. 
- Cluster is stuck in Upgrading state 
- All worker nodes k8s version is 1.16
<img width="1281" alt="Screen Shot 2020-03-17 at 4 24 32 PM" src="https://user-images.githubusercontent.com/26032343/76910709-f934d500-686b-11ea-93f6-dd2e82efdcac.png">

**Comment by sowmyav27** [comment]
Closing this issue as its being tracked here -- https://github.com/rancher/rancher/issues/25647
