### ISSUE TITLE
Problem with self-signed cert and single node cluster 

### ISSUE THREAD

**Issue by PeterTalen** [rancher/rancher#26039]
Hello,

I am using an Openssl self signed cert in an HAProxy lb and I do have the default gerenerated certs in an HA 3 server rancher setup.

I am using this command (removed servername): sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.3.5 --server https://xxxxxxxxx --token wxqss7cgwrvcgzkt2mtnjmgnrmxfth8fqzsm8vcvx559lww9cz8ljq --ca-checksum 198b87cd1f5b1804d157a7bc7ac20db8eeff1fa8710e79303bf52724af766975 --etcd --controlplane --worker

I do get this error: Issuer of last certificate found in chain (CN=xxx,OU=K8s,O=TEST,L=xxxx,ST=xx,C=xx) does not match with CA certificate Issuer (CN=cattle-ca,O=the-ranch). Please check if the configured server certificate contains all needed intermediate certificates and make sure they are in the correct order (server certificate first, intermediates after)"
time="2020-03-15T14:31:46Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get https://xxxxxxx: x509: certificate signed by unknown authority"

This is probably my mistake, but I do not know how to resolve this. Can I get some help? Thanks.

Kind regards,
Peter
---
Rancher `v2.3.5`

**Comment by xunchangguo** [comment]
怎么解决的？
