### ISSUE TITLE
kubectl logs/exec command failed

### ISSUE THREAD

**Issue by Mel-Github** [rancher/rancher#26033]
*Describe your issue here*

I have just managed to setup a k8s cluster using 3 VM. All the kubectl commands are working perfectly except the kubectl log <pod> command. Attached 

$ kubectl logs deploy/nginx
Error from server (NotFound): the server could not find the requested resource ( pods/log nginx-
6db489d4b7-qjvgh)

$ k get pods
NAME                     READY   STATUS    RESTARTS   AGE
nginx-6db489d4b7-qjvgh   1/1     Running   0          106m

$ k exec -it nginx-6db489d4b7-qjvgh -- /bin/sh
error: unable to upgrade connection: pod does not exist

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

Any advice?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.5` UI: `v2.3.36` |
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment]
Are you running this in the`Launch kubectl` window in the UI? Is this single node install and is the configured `server-url` directly pointing to the `rancher/rancher` container?

Some more info on node used helps as well, what are you using for launching the VMs? Do they have one or more than one network interface? For VirtualBox you can check https://github.com/rancher/quickstart/blob/master/vagrant/scripts/configure_rancher_node.sh#L78 how to configure the correct address(es)

**Comment by Mel-Github** [comment]
yes am running from the UI kubectl .... i setup with 3 VM on virtualbox... running ubuntu ...the first VM is started with the rancher/rancher image and subsequently loaded with the cluster etcd & control plane node option. i managed to registered the 2 worker nodes had the --address and --internal-address command provided in the UI.

**Comment by Mel-Github** [comment]
suspect same as this [issue](https://github.com/rancher/rancher/issues/11365) 

i have started the -worker node with the --address and  --internal-address option. However the 

$ kubectl get nodes devops-continens-k8s-worker-node1 -o yaml
spec:
  podCIDR: 10.42.2.0/24
  podCIDRs:
  - 10.42.2.0/24
status:
  addresses:
  - address: 10.0.2.15
    type: InternalIP

$ kubectl get nodes -o wide
NAME                                STATUS   ROLES               AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
devops-continens-k8s-master-node    Ready    controlplane,etcd   110m   v1.17.3   10.0.2.15     <none>        Ubuntu 18.04.4 LTS   4.15.0-76-generic   docker://19.3.8
devops-continens-k8s-worker-node1   Ready    worker              108m   v1.17.3   10.0.2.15     <none>        Ubuntu 18.04.4 LTS   4.15.0-76-generic   docker://19.3.8
devops-continens-k8s-worker-node2   Ready    worker              108m   v1.17.3   10.0.2.15     <none>        Ubuntu 18.04.4 LTS   4.15.0-76-generic   docker://19.3.8

**Comment by superseb** [comment]
What is the exact `docker run` command you used to register the host?

**Comment by Mel-Github** [comment]
For etcd and control plane

sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.3.5 --server https://192.168.1.102 --token dlgx6vwgq2zj9sc5hwbk6vxh8lc4mh6phzrgqsvhtx6zxnzgrsxn4x --ca-checksum 2e1ca5566206e5a6bdb979c8f6e258a8a4465f48b7f0c448b1749864aacd26fd --address 192.168.1.102 --internal-address 192.168.1.102 --etcd --controlplane

For worker

 sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.3.5 --server https://192.168.1.102 --token dlgx6vwgq2zj9sc5hwbk6vxh8lc4mh6phzrgqsvhtx6zxnzgrsxn4x --ca-checksum 2e1ca5566206e5a6bdb979c8f6e258a8a4465f48b7f0c448b1749864aacd26fd --address 192.168.1.21 --internal-address 192.168.1.21 --worker

**Comment by superseb** [comment]
That should be good. The kubelet auto-detects the wrong address, can you check if you `/etc/hosts` is correctly setup? The hostname of the machine should be pointing to the right IP so that auto detection doesn't kick in and gets the wrong IP.

**Comment by Mel-Github** [comment]
thanks superseb... i managed to workabout the issue. Instead of using vagrant to spin up the instance which resulted in the eth0 = NAT, i just went ahead and use virtualbox GUI to perform a "detachable start" which had eth0 = "bridge address".
