### ISSUE TITLE
Imported K3s cluster - not use private registry in air-gap env for upgrading

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#26042]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher HA in airgap env
- provision a 1-node k3s (`v1.0.1`) cluster in airgap env 
- import the k3s cluster into Rancher
- In Rancher, edit the cluster to upgrade to a newer version `v1.16.7-k3s1 `

<img width="851" alt="Screen Shot 2020-03-15 at 5 11 26 PM" src="https://user-images.githubusercontent.com/6218999/76714315-944e7300-66e3-11ea-9d4e-fb2138c303b1.png">

**Result:**
- under the system project, the deployment `system-upgrade-controller` and job `apply-k3s-master-plan-on-ip-172-31-22-101-with-b5c244a878-64bad` is created
![image](https://user-images.githubusercontent.com/6218999/76714488-70d7f800-66e4-11ea-883b-cf038e1b8361.png)

- the job `apply-k3s-master-plan-on-ip-172-31-22-101-with-b5c244a878-64bad` failes to pull images because it does not use the private registy 
<img width="1414" alt="Screen Shot 2020-03-15 at 5 19 21 PM" src="https://user-images.githubusercontent.com/6218999/76714423-1b9be680-66e4-11ea-9cbf-53d72cfbff75.png">

**Other details that may be helpful:**
- the image `rancher/k3s-upgrade:v1.16.7-k3s1` is not in the rancher-images.txt file

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.0-rc3
- Installation option (single install/HA):
HA

**Comment by dweomer** [comment]
This is almost certainly because both of these images are missing from the airgap images tarball:
- `rancher/k3s-upgrade:v1.16.7-k3s1`
- `rancher/kubectl:v1.17.0`

**Comment by davidnuzik** [comment]
Related K3s documentation issue https://github.com/rancher/k3s/issues/1547

**Comment by jiaqiluo** [comment]
on Rancher v2.4.0-rc3 airgap env 

- add the missing images to the `image-list.txt` https://github.com/rancher/k3s/blob/master/scripts/airgap/image-list.txt
- push those images to the private registry
- upgrade imported k3s cluster from  k3s v1.0.1 (k8s 1.16.3) to  k3s version v1.16.7+k3s1

result:
- the k3s cluster is upgraded successfully


Stil waiting for a new RC to validate the fix

**Comment by rmweir** [comment]
@jiaqiluo v2.4.0-rc6

**Comment by rancher-max** [comment]
#### Validated in v2.4.0-rc8
Steps:
- Add the proper images, including the missing ones, to a txt file in bastion server:
```
docker.io/coredns/coredns:1.6.3
docker.io/library/traefik:1.7.19
docker.io/rancher/klipper-helm:v0.2.3
docker.io/rancher/klipper-lb:v0.1.2
docker.io/rancher/local-path-provisioner:v0.0.11
docker.io/rancher/metrics-server:v0.3.6
docker.io/rancher/pause:3.1
rancher/k3s-upgrade:v1.16.7-k3s1
rancher/kubectl:v1.17.0
rancher/k3s-upgrade:v1.17.3-k3s1
```
- Push those images to the private registry
- Upgrade imported k3s from k3s v1.0.1 (k8s 1.16.3) to k3s version 1.16.7+k3s1 (success!)
- Upgrade again to k3s version 1.17.3+k3s1 (success again!)
