### ISSUE TITLE
手动创建的namespaces 的deployment  ui界面上看不到服务

### ISSUE THREAD

**Issue by alexshenyuefei** [rancher/rancher#26045]
手动创建的namespaces 的deployment  ui界面上看不到服务

**Comment by alexshenyuefei** [comment]
![image](https://user-images.githubusercontent.com/16495430/76729746-d388cc80-6794-11ea-84dd-2ae64c2db4f4.png)
ui 界面上是没有的

**Comment by loganhz** [comment]
You need to move the namespace into a project. For instance, you need to move your `skywalking` namespace into `Default` project in Rancher UI. Then you can go to project -> resources -> workloads -> Service Discovery to see your svc

**Comment by loganhz** [comment]
If you would like to ask questions in Chinese, please add `rancher2` to join 
Rancher WeChat group. Thanks

**Comment by alexshenyuefei** [comment]
wechat   没人理啊    谢谢解答
