### ISSUE TITLE
Add nginx-dav-ext-module to ingress-nginx controller

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#26047]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature request

**Steps to reproduce (least amount of steps as possible):**

The rancher/nginx-ingress-controller:nginx-0.25.1-rancher1 nginx was compiled with the ngx_http_dav_module (per "nginx -V" in the container), which supports WebDAV methods PUT, DELETE, MKCOL, COPY, and MOVE (per http://nginx.org/en/docs/http/ngx_http_dav_module.html). However, many modern WebDAV clients (at least as macOS Finder / mount_webdav command, and the Linux davfs2 client) require additional WebDAV-specific HTTP methods not supported by ngx_http_dav_module; (e.g., PROPFIND for macOS, and LOCK for davfs2), and nginx-ingress appears to not forward HTTP requests with unsupported HTTP methods.

These methods are added by nginx-dav-ext-module (https://github.com/arut/nginx-dav-ext-module) and the user's request is that future releases of the nginx-ingress-controller ship with this module compiled.

**Environment information**
- Rancher v2.3.4
- K8s v1.16.3

gz#8980

**Comment by leodotcloud** [comment]
The requested module is not from official upstream sources. Hence, closing.
