### ISSUE TITLE
Security-scan does not pull images from the private registry

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#26041]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- install Rancher `v2.4.0-rc3` HA in airgap env
- add a cluster cluster
- run CIS scan (Tools -> CIS Scans)

**Result:**
- the scan is triggered, and a pod is created under the system project
- but the pod does not pull the image from the private registry, thus fails to deploy 

<img width="1030" alt="Screen Shot 2020-03-15 at 4 01 08 PM" src="https://user-images.githubusercontent.com/6218999/76712500-e8068f80-66d6-11ea-8317-f1fa9d10bb23.png">

- the image `rancher/security-scan:v0.1.9` is included in the `rancher-images.txt` file and is in the private registry

**Comment by jiaqiluo** [comment]
on v2.4.0-rc6

It is good that the deployment `security-scan-runner-cis` pulls the image from the private registry properly, but the daemonSet `sonobuoy-rancher-kube-bench-daemon-set` does not. 

We did not find it because the daemonSet was not deployed until the first deployment was active. 

<img width="1096" alt="Screen Shot 2020-03-18 at 1 24 50 PM" src="https://user-images.githubusercontent.com/6218999/77005671-6f920f80-691e-11ea-92fa-3f8b1f423162.png">
<img width="1045" alt="Screen Shot 2020-03-18 at 1 24 45 PM" src="https://user-images.githubusercontent.com/6218999/77005688-7587f080-691e-11ea-918a-bc75dc24caf7.png">
<img width="1222" alt="Screen Shot 2020-03-18 at 1 22 40 PM" src="https://user-images.githubusercontent.com/6218999/77005729-88022a00-691e-11ea-8fa4-ac774494a005.png">

**Comment by rancher-max** [comment]
#### Validated these both show up in an airgap setup that has been upgraded from v2.3.5 to v2.4.0-rc8

![image](https://user-images.githubusercontent.com/55997940/77198767-e0633400-6aa4-11ea-8fa1-54cbcb86a18b.png)
