### ISSUE TITLE
"Show advanced..." text in Add/Edit Load Balancer service is not aligned properly

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2605]
Version - Master with reskin UI

Steps:
1.  Create a Load Balancer Service
2.  Edit LB Service

Results:
"Show advanced routing options:...." link and text is not left aligned properly

![image](https://cloud.githubusercontent.com/assets/11514927/11022033/94c5cff2-8611-11e5-989e-76ab395a41b4.png)

![image](https://cloud.githubusercontent.com/assets/11514927/11022035/a88e2caa-8611-11e5-8b22-fd7348ea37e3.png)

Expected:
Should be aligned properly

**Comment by deniseschannon** [comment]
Here's the current view in latest UI (11/24 evening) Not sure if thats what @tfiduccia was expecting. 

<img width="470" alt="screen shot 2015-11-24 at 10 04 09 pm" src="https://cloud.githubusercontent.com/assets/11410997/11389618/54f2cd6a-92f7-11e5-9a4b-db06e4218a03.png">

**Comment by tfiduccia** [comment]
Looks good :)
