### ISSUE TITLE
UI - CIS Scan shouldn't show Rancher skipped tests for hardened profile

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#26056]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Create RKE Cluster
- Go to Tools -> CIS Scans
- Click Run Scans
- Choose 1.4 Hardened

**Result:**

There are Rancher skipped tests listed when selecting Hardened. Hardened doesn't skip any tests.

<img width="590" alt="Screen Shot 2020-03-16 at 10 34 26 AM" src="https://user-images.githubusercontent.com/27659/76785338-7ed45a00-6772-11ea-9911-3c1586c0c730.png">

**Other details that may be helpful:**

Running the scan with this profile doesn't show any skipped tests in the result:

<img width="977" alt="Screen Shot 2020-03-16 at 10 42 29 AM" src="https://user-images.githubusercontent.com/27659/76785534-dd013d00-6772-11ea-895a-47aa94cfab5a.png">

**Environment information**
- Rancher version: `2.4 master-head (03/16/2020)` commit id: 73f603f9f
- Installation option (single install/HA): single

**Comment by izaac** [comment]
25961

**Comment by codyrancher** [comment]
@izaac can you try this again with the latest? There's a change in https://github.com/rancher/ui/pull/3842 which should resolve this issue.

**Comment by izaac** [comment]
@codyrancher sure I will try in a newer build.

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/16/2020)` commit id: 148b3e000

This is working as expected for Rancher skipped tests which counts are properly reflected when switching from/to Permissive and Hardened profiles.
