### ISSUE TITLE
Verify how zero downtime works with dummy nodes (can be ignored using label cattle.rancher.io/node-status: ignore and added via v3/settings/ignore-node-name)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#26052]
Due to the following issue, we need to make sure that this label `cattle.rancher.io/node-status: ignore` allows worker nodes to be upgraded. 

https://github.com/rancher/rancher/issues/23394

**Comment by kinarashah** [comment]
Looks like the nodes added with this label or added via `v3/settings/ignore-node-name` don't register as `v3/nodes`. So rancher won't list them at all, and so other nodes get upgraded as usual.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `e651c7a81`**

**The following two use-cases work**

**Scenario#1**

- Node-name - add node name
- Register node (dummy one) through kubectl
- Node will not get added to Rancher UI
- Kubectl lists the node in NotReady status 
- edit cluster, change kubelet - max-pods value
- Upgrade of cluster went through.

**Scenario#2**

- Register node
- Add label through kubectl 
- Kubectl lists the node in NotReady status 
- Node will not get added to Rancher UI
- edit cluster, change kubelet - max-pods value
- Upgrade of cluster went through.

**Comment by kinarashah** [comment]
This is happening because `node.Status.NodeConfig` of this dummy node is nil. We infer role of the node after nodeConfig gets populated. I see everywhere we rely on this nodeConfig so I don't feel comfortable changing the logic just for this dummy node. https://github.com/rancher/rancher/blob/master/pkg/api/store/cluster/cluster_store.go#L1011 

There's no harm to put this dummy node as upgrading, we can always recommend users to add the ignore label to this node (which was the original purpose of this feature anyway)

**Comment by kinarashah** [comment]
cc @deniseschannon don't think this needs to be fixed, or can be moved to 2.4.x

**Comment by deniseschannon** [comment]
I added the `status/wontfix` label for the one use case that upgrading doesn't check the bad node added through kubectl. But the overall issue is fixed. @sowmyav27 up to you how you want to close it. :)

**Comment by sowmyav27** [comment]
@kinarashah The dummy node, does NOT go into "Upgrading" state. It remains in "Unavailable" State. Concern was, rancher zerodowntime validation was not happening in this case.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `330a4bed0`**

**Steps:**

- Register node(dummy) through kubectl - no label added or node registered in the /v3/settings/ignore-node-name
- Wait until node is in Unavailable in the Rancher UI
- Upgrade cluster k8s version from 1.16 to 1.17
- The upgrade goes through.
- Dummy node is still seen in "Unavailable" state


Closing the issue as per comments https://github.com/rancher/rancher/issues/26052#issuecomment-600411877
