### ISSUE TITLE
Unable to edit cluster after upgrade from rancher v2.3.5 to master

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#26053]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy a cluster in Rancher v2.3.5 or v2.3.6-rc5
2. Upgrade rancher to master-head
3. Edit on the cluster
4. Fill in a value for max unavailable workers
5. Save 

**Result:**
Unable to upgrade with error: `invalid value for IntOrString: invalid value "": strconv.Atoi: parsing "": invalid syntax`. 

**Other details that may be helpful:**
- Potentially related to https://github.com/rancher/rancher/issues/25951. 
- Cannot find any workaround at this time.
- Attempted edit a cluster on a non-upgraded master-head setup and it was successful. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `Rancher version 73f603f9f` `master-2450-head`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke Linode 3 nodes all roles
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): Attempted with 6 options: k8s 1.15, 1.16, and 1.17. One calico one canal for each.

**Comment by mrajashree** [comment]
@rancher-max Can you share what value you filled max unavailable workers?

**Comment by rancher-max** [comment]
@mrajashree I tried it with the following:
- Count: 3
- Count: 1
- Count: 0
- Percentage: 10
- Percentage: 100
- Percentage: 0

**Comment by mrajashree** [comment]
No value is being passed for maxUnavailableControlplane in the cluster edit call.
For now a workaround is to Edit cluster through API, no need to change any values, this puts in the  default for maxUnavailableControlplane, after which editing cluster through UI should work

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/17/2020)` commit id: ddda7cb8d

Validated the default value after upgrading from `v2.3.5` is **10** percentage:

<img width="366" alt="Screen Shot 2020-03-17 at 10 51 34 AM" src="https://user-images.githubusercontent.com/27659/76886097-801e8900-683d-11ea-8e52-9e725ed72de1.png">

maxUnavailable in the API shows 10 too.

Drain default value in UI is **No**.
Drain default value in the API is **false**.

Editing the cluster and saving the settings also works.

Tested upgrading the Kubernetes version after the Rancher Upgrade. Passed.

Related issue: 25951
