### ISSUE TITLE
CIS Scan - UI - Issues with Improved UX of Run Scan Modal

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26065]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Issue#1**

- Run Scan on a cluster
- The hyperlinks mentioned in the modal navigate user to rancher docs.

<img width="761" alt="Screen Shot 2020-03-16 at 1 47 16 PM" src="https://user-images.githubusercontent.com/26032343/76798559-0d55d500-678d-11ea-9a4f-b9d9221f437a.png">

**Expected Result:**
The hyperlink should navigate user to the for "profiles" and "skipped rancher tests"

**Issue#2**
- Could we have better wording for these two Info texts ?

<img width="1333" alt="Screen Shot 2020-03-16 at 1 50 33 PM" src="https://user-images.githubusercontent.com/26032343/76798653-3b3b1980-678d-11ea-98d2-6761b6efbd1e.png">

**Issue#3**
- Go to System Project --> Config --> Add new config in security-scan namespace (to skip tests)
- Run Scan - choose permissive/hardened
- User defined skip tests do not show up.

**Note:**
On a refresh of the page, the skipped tests from the config (user skipped tests) show up.

**Expected Result:**
The skipped tests from config map, should show up in the user skipped tests when Run scan is clicked, without doing a refresh on the webpage.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - `148b3e000` ui tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.17
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by codyrancher** [comment]
That's intended until we have the docs to link to. Might as well keep this open for tracking though.

**Comment by codyrancher** [comment]
@deniseschannon For issue 2 isn't this the wording we agreed to?

**Comment by deniseschannon** [comment]
Correct, #2 is the wording agreed upon, but we should keep this open to track the two URL changes.

**Comment by deniseschannon** [comment]
Profiles Link: https://rancher.com/docs/rancher/v2.x/en/security/security-scan/#profiles

Tests Link:  https://rancher.com/docs/rancher/v2.x/en/security/security-scan/#skipped-and-not-applicable-tests

**Comment by deniseschannon** [comment]
Moved Issue #3 into:  https://github.com/rancher/rancher/issues/26161

This issue is only to track Issue #1, but since the docs aren't posted they will not go to a direct page. If you take the link that is tracked and add `staging` into the URL so that it's `staging.rancher.com/docs`, it should take you to the correct place.

side note on docs: Whenever we use a heading as a link, it ends up hiding partially behind the header of the docs page.

**Comment by sowmyav27** [comment]
**verified on latest master-head - ui tag: latest2**

**Issue#1 is seen fixed**

- Run Scan on a cluster
- The hyperlinks mentioned in the modal navigate user to rancher docs are as mentioned https://github.com/rancher/rancher/issues/26065#issuecomment-600865369

Closing the issue.
