### ISSUE TITLE
UI - CIS Scan - Skipped tests can have 2 sections - rancher skipped and user skipped tests

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26066]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Steps to reproduce (least amount of steps as possible):**

- The Skipped tests shown, can have two separate blocks - Rancher skipped tests and User skipped tests.
<img width="1187" alt="Screen Shot 2020-03-16 at 1 58 00 PM" src="https://user-images.githubusercontent.com/26032343/76799495-df719000-678e-11ea-9a59-7bc81440f0a6.png">

- Currently when a user skips a Rancher skipped test - it shows up as a duplicate entry with different `Explanation`.
- But if we have two sections, we can list them separately

<img width="1284" alt="Screen Shot 2020-03-16 at 2 02 01 PM" src="https://user-images.githubusercontent.com/26032343/76799488-db457280-678e-11ea-8724-56308bb09c76.png">

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - ui tag" `latest2`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by codyrancher** [comment]
I was asked to put them in one section. @deniseschannon do we want to change that now?

**Comment by deniseschannon** [comment]
I would prefer 2 lists but could see it either way. @tfiduccia do you have a strong preference?

**Comment by tfiduccia** [comment]
@deniseschannon - I thought we agreed skipped was skipped? And go into the same list.  The details will say who/why.

**Comment by deniseschannon** [comment]
Seeing as the request has come in more than 1 place, I'm thinking we should separate them as it'd be clearer to users.

What does the reason say when it's a user skipped test @sowmyav27 @codyrancher ?

**Comment by codyrancher** [comment]
@deniseschannon it's in the screenshot. 

> Skipped by user

**Comment by deniseschannon** [comment]
Can we update it to this: 

* The current N/A and skipped tests from the profile to be laid out in its own section (like it is now), but update the text to something like "These tests won't run due to the selected profile" 

And then a separate section below it that has text that says "These tests won't run as they have been skipped for the cluster" and then underneath that show a comma delimited list of test IDs

.

**Comment by Oats87** [comment]
I am for separating the sections to distinguish between what we (Rancher) have deemed to skip vs. what the user has skipped. I can easily see users being confused due to duplication in the same table.

**Comment by sowmyav27** [comment]
**verified on latest master-head - ui tag: latest2**

- When there is no config map for the cluster (security-scan-cfg in System Project), the run Scan pop up windows is like
<img width="938" alt="Screen Shot 2020-03-18 at 4 44 00 PM" src="https://user-images.githubusercontent.com/26032343/77017500-e7b8ff00-6937-11ea-9f36-c1c1b8bc31c4.png">

- When the config map has tests to be skipped - added by the user, the run scan pop up shows like
<img width="987" alt="Screen Shot 2020-03-18 at 4 41 18 PM" src="https://user-images.githubusercontent.com/26032343/77017529-f7384800-6937-11ea-92b2-3ae5e2bace82.png">
