### ISSUE TITLE
Line separators in Add environment are not aligned properly

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2607]
Version - Master with reskin UI

Steps:
1.  Authenticate using GitHub
2.  Go to Add Environment

Results:  The grey lines that are separating member information is right up against the fields.  And they are also too light of a color.
![image](https://cloud.githubusercontent.com/assets/11514927/11022241/0b2c4bf8-8617-11e5-94a3-f7e36fa9368a.png)

Expected:
Separator lines should not touch the field name and info.

**Comment by vincent99** [comment]
This style got added to all tables, fixed..

**Comment by tfiduccia** [comment]
Verified fixed - Version Master with updated reskined UI
