### ISSUE TITLE
[OPA Gateway] Unable to create constraint template

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/rancher#26074]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster, go to dashboard.
2. Enable OPA gatekeeper
3. Go to template.
4. Write/paste the yaml into the editor.
5. Click save

**Result:**
UI shows error ```{ "data": "" }```
The response of the post request to https://rancher.server/k8s/clusters/c-aaaa/v1/templates.gatekeeper.sh.constrainttemplates API is 502.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2463-head- e651c7a81
- Installation option (single install/HA): Single

**Comment by prachidamle** [comment]
I can create constrainttemplate on current master-head (ddda7cb8d)

I just copied over the yaml from here https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/library/general/httpsonly/template.yaml

**Comment by prachidamle** [comment]
The yaml one uses to create the constrainttemplate, should not have `resourceversion` metadata as this is a Create request for a new resource.
