### ISSUE TITLE
modifying altermanager.yaml injects empty proxy_url option

### ISSUE THREAD

**Issue by flrichar** [rancher/rancher#26089]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- enable monitoring
- modify secrets for alertmanager.yaml
- remove proxy_url line

**Result:**
- proxy_url comes back with null value "" and is parsed incorrectly

**Other details that may be helpful:**
user does have a proxy but does not need it for internal custom webhook.  the monitoring will work for a while before the controller replaces the proxy_url line, breaking the monitoring.

**Environment information**
- Rancher version v2.3.5
- Installation option Single

**Cluster information**
- Cluster type: Custom
- Machine type: VM
- Kubernetes version 1.15
- Docker version 18.09.3

**Comment by loganhz** [comment]
Workaround 1 : 

- Remove the webhook and add it again without proxy url input

Workaround 2: 

- Click View API for the broken notifier. 
- Click "Edit" and remove the proxyurl part in webhookConfig. 
- Click "Show request". 
- Copy the `curl` command.
- Append `?_replace=true` in the curl command
- Send the command via curl

![image](https://user-images.githubusercontent.com/21168270/76917576-cee02780-68fe-11ea-8586-4759e225c5cf.png)
![image](https://user-images.githubusercontent.com/21168270/76917722-41510780-68ff-11ea-8b69-b3ed5f54e5ce.png)

**Comment by gmolkvk** [comment]
I have also found that activating the Proxy URL field will insert an empty string into the webhookConfig.proxy_url, which will end up in the AlertManager. 

By extension, this will cause "connection refused" errors in the AlertManager on triggered Webhook alerts, because "" (empty string) is not a valid hostname for a proxy.

**Comment by jiaqiluo** [comment]
Some observations on around notifiers in v2.3.5
- we can edit an existing notifier to change the value of the proxy URL to another valid value or an empty string, but cannot remove the proxy URL once it was set
- if we enter spaces on the proxy URL filed when creating a notifier, the value will be set to an empty string which can be seen when viewing the notifier in API.

<img width="675" alt="Screen Shot 2020-04-06 at 4 08 58 PM" src="https://user-images.githubusercontent.com/6218999/78613552-0157b300-7821-11ea-93e0-a17cfd435370.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated in Rancher:v2.4-master 0865a2cc9 

- We cannot remove the `proxyURL` fully (you can see it when viewing the notifier in API) once its value is set, but we can change its value to an empty string (by typing spaces in the filed) and Rancher will ignore it and alters using the notifier will continue working. 
- if the value of `proxy_url` is either an empty string `""` or `null`, the `http_config` section will be omitted in the `Alertmanager.yaml` file
