### ISSUE TITLE
CATTLE_HOST_LABELS after first startup of rancher/agent

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#2608]
Hey there,
I noticed that if host already was added to `rancher/server` new `CATTLE_HOST_LABELS` will be not recognized. Reason? It would be nice if this was not fixed after second `rancher/agent` startup.

**Comment by deniseschannon** [comment]
I was unable to reproduce.

Steps I did:

1. Add a host to Rancher (no host labels)
2. Remove the host from Rancher.
3. Add the same host using a command that includes a new host label (foo=bar)

Result: When the host is added, the host has a host label of `foo=bar`. 

Did you remove the host or were you just trying to add in new host labels? I guess why the reasoning of running the "add host" command if it's already up and running?

**Comment by fentas** [comment]
Yeah. I guess I got a little confused. I moved my infrastructure from gce to static servers.
I got used to that `rancher/agent` wasn't there after a restart. Now it is.
Sorry and Thanks for your time. :+1:
