### ISSUE TITLE
Possible to create node pools without a role

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#26080]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a vSphere cluster with two node pools of one node, one node pool with the etcd and controlplane nodes, and the second node pool with the worker role.
2. Observe the cluster provisioned successfully and the worker pool node labelled with node-role.kubernetes.io/worker=true
3. Add a third node pool with one node, but do not select a role for this node pool.
4. Observe the node is successfully provisioned, but does not receive the node-role.kubernetes.io/worker=true label. As a result whilst workloads can be deployed to this node, an nginx-ingress controller will not schedule on it, due to the label selector.

Seems there is a bug here, in enabling the creation of node pools without a role selected.

**Environment information**
- Rancher v2.3.4

gz#8965

**Comment by deniseschannon** [comment]
This has been updated and corrected within 2.5 based on this issue: https://github.com/rancher/rancher/issues/28758

**Comment by sowmyav27** [comment]
Can be validated on 2.5.2 and master-head.

**Comment by axeal** [comment]
@deniseschannon Whilst the milestone here is v2.5.3, it looks like the fix was merged into the UI for v2.5.2 and in addition to @sowmyav27 's comment, I have also validated it is now fixed in v2.5.2, so looks like this could be closed out.

**Comment by deniseschannon** [comment]
@axeal Correct, the milestone for v2.5.2 is now closed so it's the easiest way to get it to QA attention is to put it in the upcoming milestone. 

But if you've already validated it, I'll close it now.
