### ISSUE TITLE
Unable to set helm value/answer to YAML string "true" in editMonitoring

### ISSUE THREAD

**Issue by nikkelma** [rancher/rancher#26088]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Enable monitoring on a cluster
2. Call cluster's `editMonitoring` action with all default answers and two extra answers:
  - ~JSON: `"grafana.extraEnv[0].name": "TEST_VAR"`~
  - ~JSON: `"grafana.extraEnv[0].value": "<value>"` where `<value>` is `true` or `\"true\"` or `'true'`~
 - 2020-11-09: JSON: `"grafana.extraVars[0].name": "TEST_VAR"`
 - 2020-11-09: JSON: `"grafana.extraVars[0].value": "<value>"` where `<value>` is `true` or `\"true\"` or `'true'`

**Result:**
- Scenario A, where `<value>` is `true`: grafana-cluster-monitoring is not deployed, as `env.value` expects a string but gets a bool
- Scenario B, where `<value>` is `\"true\"` or `'true'`: grafana-cluster-monitoring is deployed but `env.value` for `env.name: TEST_VAR` is wrapped in single quotes - YAML `'"true"'` or `'''true'''`, respectively

**Other details that may be helpful:**
- rancher/rancher#17346 is similar, a potential workaround (providing `values.yaml` instead of an `answers` map) is not possible as the `monitoringInput` API object does not have this field
- rancher/rancher#17346, https://github.com/rancher/rancher/issues/13158#issuecomment-418910405, rancher/rancher#13158's fix, and rancher/rancher#15043 indicates that some stability may be needed for helm answers in general

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): **v2.3.5**
- Installation option (single install/HA): **HA**

gz#14692

**Comment by nikkelma** [comment]
Potential fixes:
1. Add ValuesYaml from [`App.Spec`](https://github.com/rancher/types/blob/e8e610dd9e0169e93090b9f881f47043738ee3ec/apis/project.cattle.io/v3/app_types.go#L37) to [`MonitoringInput`](https://github.com/rancher/types/blob/37f04dbaa0a5358e6fc4e99d28c220d953bd98ad/apis/management.cattle.io/v3/cluster_types.go#L286-L289) (UI support would be nice, too)
2. Solve issue in https://github.com/rancher/rancher/issues/13158#issuecomment-418910405 (_Somehow provide a (per answer) choice of set vs set-string for vanilla helm templates_) and use solution in [`MonitoringInput`](https://github.com/rancher/types/blob/37f04dbaa0a5358e6fc4e99d28c220d953bd98ad/apis/management.cattle.io/v3/cluster_types.go#L286-L289)

`1.` would allow API calls to achieve the desired behavior but would only allow intended behavior by providing `values.yaml` directly, while `2.` would allow answers (in the API and UI) to also achieve this behavior.

A possible approach for `2.` would be to add a new field `AnswersForceString` (type `map[string]bool` or `[]string`) to [`App.Spec`](https://github.com/rancher/types/blob/e8e610dd9e0169e93090b9f881f47043738ee3ec/apis/project.cattle.io/v3/app_types.go#L37) and, for each key in `Answers`, check if `--set-string` should be used instead of `--set` by inspecting `AnswersForceString` for existence of the key in question.

**Comment by nikkelma** [comment]
Edited to reflect @jiaqiluo's findings that `extraEnv` was incorrect, instead should be `extraVars`.

**Comment by nikkelma** [comment]
Some additional info:

- Original issue was filed against Rancher v2.3.5
- Successfully reproduced in Rancher v2.4.8
- Linked issue above (#29325) reproduces in v2.5.2-rc4

### Scenario A (value = `true`) screenshots:

#### UI

![Screen Shot 2020-11-09 at 16 47 19](https://user-images.githubusercontent.com/16194510/98600231-3e9a8c80-22ab-11eb-8af9-9ffc49cab4d0.png)

#### API call

![Screen Shot 2020-11-09 at 16 49 16](https://user-images.githubusercontent.com/16194510/98600414-85888200-22ab-11eb-8ff4-7036dfd760ab.png)

#### Error
Due to `env.value` being `true` instead of `"true"` (expected type is string, not bool)

![Screen Shot 2020-11-09 at 16 54 37](https://user-images.githubusercontent.com/16194510/98600901-427ade80-22ac-11eb-9af0-c089ca687c06.png)

### Scenario B (value = `"true"`) screenshots:

#### UI

![Screen Shot 2020-11-09 at 16 59 47](https://user-images.githubusercontent.com/16194510/98601394-fbd9b400-22ac-11eb-9ad1-69795402c3e9.png)

#### API

![Screen Shot 2020-11-09 at 17 00 36](https://user-images.githubusercontent.com/16194510/98601470-17dd5580-22ad-11eb-8b74-7029f8b4ca06.png)

#### Unexpected configuration

Note that `GF_AUTH_BASIC_ENABLED` and `GF_AUTH_ANONYMOUS_ENABLED` are hard-coded in the helm chart, not set by any answers.

![Screen Shot 2020-11-09 at 17 01 51](https://user-images.githubusercontent.com/16194510/98601587-44916d00-22ad-11eb-900c-b444e706f343.png)

**Comment by jiaqiluo** [comment]
the bug is reproduced in `v2.5.2-rc7` single install 

### when value = `true`

<img width="1467" alt="Screen Shot 2020-11-09 at 2 58 12 PM" src="https://user-images.githubusercontent.com/6218999/98604113-59b3cf00-22a0-11eb-9442-b1d297bf72c9.png">

<img width="1466" alt="Screen Shot 2020-11-09 at 2 59 01 PM" src="https://user-images.githubusercontent.com/6218999/98604011-3e48c400-22a0-11eb-91dc-3bb3afa75c8b.png">


 
### when value = `"true"`
![image](https://user-images.githubusercontent.com/6218999/98603868-0f325280-22a0-11eb-9dbb-548ba86ac482.png)

<img width="538" alt="Screen Shot 2020-11-09 at 3 25 44 PM" src="https://user-images.githubusercontent.com/6218999/98603883-148f9d00-22a0-11eb-978a-11b6bdcf3105.png">

**Comment by slickwarren** [comment]
on rancher version v2.5.3, monitor version 0.1.4 the issue is reproduced.  
a small caveat was found: 
* change the `grafana.extraVars[0].value` to boolean true after setting it to one of the string values ("true" or 'true')
* the value will keep the string value due to an issue in the app upgrade process

Yaml output when updated to 'true'

<img width="353" alt="Screen Shot 2020-12-23 at 2 40 16 PM" src="https://user-images.githubusercontent.com/16691014/103044648-34b8aa00-4536-11eb-89fd-e00f9de037b2.png">

yaml output when updated to "true"

<img width="343" alt="Screen Shot 2020-12-23 at 2 37 35 PM" src="https://user-images.githubusercontent.com/16691014/103044665-3e421200-4536-11eb-8e4c-4da2c5eaebdf.png">

app status when updating to boolean true (truncated): 
```
23T23:46:00Z\",\"lastTransitionTime\":\"2020-12-23T21:29:45Z\",\"reason\":\"NewReplicaSetAvailable\",\"message\":\"ReplicaSet \\\"grafana-cluster-monitoring-596cbd8b55\\\" has successfully progressed.\"}]}}": v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true}],"ima|..., bigger context ...|ENABLED","value":"true"},{"name":"test1","value":true}],"image":"rancher/grafana-grafana:7.1.5","nam|...
```

**Comment by PennyScissors** [comment]
What needs to be tested as part of this issue:

1. Apps
The API now has a new field "answersSetString" for all the variables the user wants to force their value to be string typed. Once this UI issue is completed, the user should have the option to force set the value of each individual variable to be a string as following (or similarly, depends on how it gets implemented).

User input in UI  (setString could be something set by the user using a checkbox, etc)
```
"A"="1"  setString=false
"B"="2"  setString=false
"C"="3"  setString=true
"D"="4"  setString=false
"E"="5"  setString=true
```

Expected JSON in the API:
```
{
  "answers": {
    "A":"1",
    "B":"2",
    "D":"4"
  },
  "answersSetString": {
    "C":"3",
    "E":"5"
  },
  ...
}
```

What needs to be tested once the UI and CLI has been updated (UI issue, CLI issue):
Apps and Multicluster Apps - Set env variables for the app through the text fields and validate the values are added to the right API field and the variable in the app has the expected type (String if the user chose to force it).
Multicluster Apps - 
Monitoring -
CLI -

**Comment by PennyScissors** [comment]
What needs to be tested as part of this issue:

1. Apps
The API now has a new field `answersSetString` for all the variables the user wants to force their value to be string typed. Once this UI issue is completed, the user should have the option to force set the value of each individual variable to be a string as following (or similarly, depends on how it gets implemented).

    User input in UI  (`setString` could be something set by the user through a checkbox, etc)
    ```
    "A" = "1"  setString=false
    "B" = "2"  setString=false
    "C" = "3"  setString=true
    ```
    
    Expected JSON in the API:
    ```
    {
      "answers": {
        "A": "1",
        "B": "2",
      },
      "answersSetString": {
        "C": "3",
      },
      ...
    }
    What needs to be validated:
    * Variables with setString == true should go in answersSetString, and the value should resolve to a string type in the app it's been deployed.
    * Variables with setString == false should go in answers, and the behavior is the same as the current behavior.

2. Multicluster Apps
Same as Apps, but the structure in the API is different due to being multicluster and each app having their own answers.
    
    User input in UI
    ```
    "A" = "1"  setString=false
    "B" = "2"  setString=false
    "C" = "3"  setString=true
    ```
    Expected JSON in the API:
    ```
    "answers": [
        {
          "type": "answer",
          "clusterId": null,
          "projectId": null,
          "values": {
            "A": "1",
            "B": "2"
          },
          valuesSetString: {
            "C": "3"
          }
        }
      ],
    ```
    What needs to be validated:
    * Variables with setString == true should go in answersSetString, and the value should resolve to a string type in the app it's been deployed.
    * Variables with setString == false should go in answers, and the behavior is the same as the current behavior.
 to the right map map based on the selection (E.g. answers when setString is false, answersSetString when setString is true).
 validate the values are added to the right API field and the variable in the app has the expected type (String if the user chose to force it).
Multicluster Apps - 
Monitoring -
CLI -

**Comment by anupama2501** [comment]
Reproduced on v2.5.8:
1. Created an rke1 node driver 3 worker, 1 cp and 1 etcd
2. Install monitoring v1 by adding the ```grafana.extraVars[0].name=TEST_VAR and grafana.extraVars[0].value=`true` ```
3. From the cluster --> System project --> apps monitoring installation fails with the error: 
``` Failed to install app cluster-monitoring. Error: UPGRADE FAILED: failed to create resource: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true}],"ima|..., bigger context ...|BLED","value":"true"},{"name":"TEST_VAR","value":true}],"image":"rancher/mirrored-grafana-grafana:7.|... ```
4. Set ```grafana.extraVars[0].value='true' ``` and see the yaml has:
``` spec:
  containers:
  - env:
    - name: GF_AUTH_BASIC_ENABLED
      value: "true"
    - name: GF_AUTH_ANONYMOUS_ENABLED
      value: "true"
    - name: TEST_VAR
      value: '''true''' 
```
5. Set ```grafana.extraVars[0].value="true" ```
spec:
  containers:
  - env:
    - name: GF_AUTH_BASIC_ENABLED
      value: "true"
    - name: GF_AUTH_ANONYMOUS_ENABLED
      value: "true"
    - name: TEST_VAR
      value: '"true"'
```

**Comment by anupama2501** [comment]
Verified on fresh install of master-head 44bb5b4
Created an rke1 node driver cluster with 3 worker, 1 cp and 1 etcd

**Test1 Install monitoring**
1. From v3 API, `https://ip/v3/clusters/c-sl88n?action=enableMonitoring`, add the values in `answersSetString` as follows:
<img width="300" alt="Screen Shot 2021-07-15 at 10 52 27 AM" src="https://user-images.githubusercontent.com/38144301/125834376-433ca6b0-183a-46c3-96a6-16ebacb5f996.png">
2. Verified the monitoring is successfully installed in the cluster.
**Test2 Edit monitoring**
3. Install monitoring without adding custom set strings from v3 API 
4. Edit monitoring by `https://ip/v3/clusters/c-sl88n?action=editMonitoring` and set the values 

``` 
grafana.extraVars[0].name=TEST_VAR
grafana.extraVars[0].value=true
```
Grafana is enabled in the monitoring app and the yaml shows correct values :
```
spec:
  containers:
  - env:
    - name: GF_AUTH_BASIC_ENABLED
      value: "true"
    - name: GF_AUTH_ANONYMOUS_ENABLED
      value: "true"
    - name: TEST_VAR
      value: "true"
```

#### Note: The values are to be sent without any quotes as the answerSetString is a string and quotes single or double are not needed.

**Comment by anupama2501** [comment]
Verified the same on multi cluster apps and apps:
Created a cluster with 3 nodes 1 role each

multicluster app test:

- From v3 api, installed docker registry app by passing the following values in answers:

```
 "answers":[
      {
         "type":"answer",
         "clusterId":null,
         "projectId":null,
         "**values**":{
            "secrets.htpasswd":"",
            "storage":"filesystem",
            "persistence.enabled":"false",
            "ingress.enabled":"false",
            "service.type":"NodePort",
            "service.nodePort":""
         },
        "**valuesSetString**":{
        "test":true,
        "test2":"true",
        "test3":'true'
}]
```

- Verified from the target cluster --> project --> app is installed and has the values highlighted above set as answer and valuesSetString highlighted above set as answerSetString

<img width="318" alt="Screen Shot 2021-07-16 at 4 34 43 PM" src="https://user-images.githubusercontent.com/38144301/126017905-26da59c2-8cd3-4a24-ac34-580d77d00942.png">


*Single app*:
- Verified by sending requests via v3 API, set the answer and answerSetString values as follows: 
<img width="731" alt="Screen Shot 2021-07-16 at 4 37 14 PM" src="https://user-images.githubusercontent.com/38144301/126017969-cf59df60-e3b5-4b53-978a-d93c53a05347.png">

**Comment by anupama2501** [comment]
Upgrade test case:
Before upgrade v2.5.8 
After upgrade: master-head f33188d

1. On v2.5.8, create an rke1 cluster node driver with 3 worker, 1 cp, 1 etcd
2. Enable monitoring in the cluster with answer `grafana.extraVars[0].name=TEST_VAR` and `grafana.extraVars[0].value=true`
3. Monitoring is stuck as mentioned in the above error
4. From global, apps --> install docker registry with target set to cluster - default and local - default project. 
5. App installs in the both projects
6. Install mysql in the default project
7. Upgrade the rancher server to the master-head version
8. Edit the monitoring via v3 API and set the `grafana.extraVars[0].name=TEST_VAR` and `grafana.extraVars[0].value=true` in answerSetString.
9. Monitoring installs successfully
10. edit the multi-cluster app via v3 API and add `"valuesSetString": {"key":"value1"}`
11. Verified the string values are set in both projects 
12. Edit the mysql app, add the `answerSetString` with `key:value` 
13. verified the app reflects the new values added.
