### ISSUE TITLE
In Add Catalog, the preview yml is below the Create/Cancel buttons

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2609]
Version - Master with reskin

Steps:
1.  Go to Catalog and click on any catalog
2.  In Add Catalog screen scroll to bottom

Result:
The Preview for yml is below the Create/Cancel buttons.  This seems really strange.

Expected:
They should probably be above the buttons, but maybe minimized (have a way to open/close the preview).

**Comment by vincent99** [comment]
Minimized by default and in tabs now.

**Comment by tfiduccia** [comment]
Verified fixed - Version Master with updated reskined UI
