### ISSUE TITLE
Add Node Drivers,Aliyun ECS does not have uiUrl,I want to get it

### ISSUE THREAD

**Issue by weavepub** [rancher/rancher#26097]
**What kind of request is this: question**
**Version: Rancher v2.3.5**

**Steps:**

When I add Node Drivers，found that Aliyun ECS does not have uiUrl。
I want to modify some default values，Can you provide uiUrl js file？

`data": [ 15 items
{
"actions": { … },
"active": true,
"annotations": { … },
"baseType": "nodeDriver",
"builtin": false,
"checksum": "c31b9da2c977e70c2eeee5279123a95d",
"created": "2019-06-14T08:58:05Z",
"createdTS": 1560502685000,
"creatorId": null,
"description": "",
"externalId": "",
"id": "aliyunecs",
"labels": { … },
"links": { … },
"name": "aliyunecs",
"state": "active",
"status": { … },
"transitioning": "no",
"transitioningMessage": "",
"type": "nodeDriver",
"uiUrl": "",
"url": "http://machine-driver.oss-cn-shanghai.aliyuncs.com/aliyun/1.0.2/linux/amd64/docker-machine-driver-aliyunecs.tgz",
"uuid": "8627f7a5-8e82-11e9-92de-00163e053465",
"whitelistDomains": [
"ecs.aliyuncs.com"
]
}
}`

**Comment by loganhz** [comment]
You can just enable it instead of adding a new one. Also it's a build-in driver https://github.com/rancher/ui/tree/master/lib/nodes/addon/components/driver-aliyunecs. So there is no external UI for it.
