### ISSUE TITLE
Debugging s3 backup issues 

### ISSUE THREAD

**Issue by ilhaan** [rancher/rancher#26092]
**What kind of request is this (question/bug/enhancement/feature request):**
question 

**Steps to reproduce (least amount of steps as possible):**
1. Initiate rke one-time snapshot as per [this](https://rancher.com/docs/rke/latest/en/etcd-snapshots/one-time-snapshots/): 
```
rke etcd snapshot-save \
--config cluster.yml \
--name s3snapshot-03-17-2020 \
--s3 \
--access-key <access-key> \
--secret-key <secret-key> \
--region us-west-2 \
--bucket-name <bucket-name> \
--s3-endpoint s3.amazonaws.com
```
2. Login to cluster node and run `docker logs -f etcd-snapshot-once`
```
user@server:~# docker logs -f etcd-snapshot-once 
time="2020-03-18T01:45:57Z" level=info msg="invoking set s3 service client" 
time="2020-03-18T01:45:58Z" level=info msg="Initializing Onetime Backup" name=s3snapshot-03-17-2020 
time="2020-03-18T01:46:07Z" level=info msg="Created backup" name=s3snapshot-03-17-2020 runtime=5.429355406s 
time="2020-03-18T01:46:07Z" level=info msg="invoking uploading backup file s3snapshot-03-17-2020.zip to s3" 
```

**Result:**
The process just hangs there.  I have tested the access credentials to upload and list files in the same bucket and have ruled out all access credentials related issues. I tested access by using `s3cmd` on the node and this works fine. 

**Other details that may be helpful:**
In order to debug this further, I attempted to get debug logs doing the following: 
1. Log in to `etcd-snapshot-once` container: 
```
user@server:~# docker exec -it etcd-snapshot-once bash
```
2. Run rke backup command with `--debug`: 
```
bash-4.4# /opt/rke-tools/rke-etcd-backup etcd-backup save --debug --cacert /etc/kubernetes/ssl/kube-ca.pem --cert /etc/kubernetes/ssl/kube-node.pem --key /etc/kubernetes/ssl/kube-node-key.pem --name s3snapshot-03-17-2020 --endpoints=10.192.0.73:2379 --once --creation=12h --retention=72h --s3-backup=true --s3-endpoint=s3.amazonaws.com --s3-accessKey=<access-keu> --s3-secretKey=<secret-key> --s3-bucketName=<bucket-name> --s3-region=us-west-2
INFO[0000] invoking set s3 service client               
INFO[0000] Initializing Onetime Backup                   name=s3snapshot-03-17-2020
INFO[0008] Created backup                                name=s3snapshot-03-17-2020 runtime=4.815617427s
INFO[0008] invoking uploading backup file s3snapshot-03-17-2020.zip to s3 
```

This does not seem to enable debug logs.  Is there something I am doing wrong here or do I have to access these debug logs some other way? 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal 
- Kubernetes version (use `kubectl version`): v1.14.6

- Docker version (use `docker version`):

```
Docker version 19.03.3, build a872fc2f86
```

**Comment by superseb** [comment]
This is sending a snapshot to actual Amazon S3 or a clone? We already have retry functionality and print the error if there is one. If it actually hangs, it would be a bug in upstream libraries or the backend if its not default S3 (as that is what is tested). `kill -3` of the process will dump more info to retrieve why its stuck.

**Comment by ilhaan** [comment]
Using actual Amazon S3. Been a while since I last attempted this. Will give `kill -3` a shot and post here with an update.

**Comment by ilhaan** [comment]
Ok, finally got a chance to revisit this. Turns out the endpoint I used was wrong and had to specify region as shown below: 
```
--s3-endpoint s3.us-west-2.amazonaws.com
```
