### ISSUE TITLE
Document required IAM policy for creating and managing EKS cluster

### ISSUE THREAD

**Issue by azelezni** [rancher/rancher#26098]
There is currently no documentation (that I can find) that describe the required IAM policy for Rancher to create and manage an EKS cluster, I ended up giving rancher admin access after spending hours trying to figure out the required permissions.

Can we please get a minimal required policy for EKS cluster?

**Comment by Caldas** [comment]
I'm also facing this problem ... I had to set full admin access to bypass this IAM issue and that's not cool
