### ISSUE TITLE
CIS Scan - Scans not running on a cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26108]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Deploy a cluster - 1 etcd, 1 control and 1 worker.
2. Enable CIS schedule scans and give cron time = 10 * * * *. (for example) and retention count = 2
3. Scheduled scan will run on the 10th minute that hour. 
4. Run few manual scans
5. Edit cluster change cron time = 12 * * * *. 
6. Scheduled scan will run on the 12th minute that hour. 
7. Edit cluster change cron time = 13 * * * *. 
8. Scan run in Step 3 will be deleted. And a new Scheduled scan will be generated for the cluster.
9. Manual scans do not get deleted
10. Do Step 4, 5 and 6 a couple of times.

**Expected Result:**
Scheduled scan and run scan should be run on the cluster

**Actual Result:**

- Scheduled scan and run scan are not on the cluster. Error seen while Run scan is clicked from UI - `CIS scan already running on cluster` 
- No workloads/pods related to scan running in System project -- Security scan namespace
- Logs:

```
2020/03/18 17:41:37 [INFO] scheduledScanHandler: clusterSync: cron schedule modified for cluster c-8q8rv: 42 * * * *
2020/03/18 17:41:37 [DEBUG] scheduledScanHandler: scheduleScan: cluster c-8q8rv now: 2020-03-18 17:41:37.201276888 +0000 UTC m=+7113.246273901 setting nextScanAt: 2020-03-18 17:42:00 +0000 UTC
2020/03/18 17:41:37 [DEBUG] Checking and deleting unused certificates for cluster c-8q8rv
2020/03/18 17:41:53 [DEBUG] machineName: returning [m-031e08b51fd9] for node with RequestedHostname [ip-172-31-8-218]
2020/03/18 17:41:53 [DEBUG] getMachine: looking up machine [m-031e08b51fd9] in cluster [c-dxlgg]
2020/03/18 17:42:00 [ERROR] ClusterScanController scheduledscan/c-8q8rv:42 * * * * [scheduledScanHandler:sync] failed with : CIS scan already running on cluster
2020/03/18 17:42:00 [ERROR] ClusterScanController scheduledscan/c-8q8rv:42 * * * * [scheduledScanHandler:sync] failed with : CIS scan already running on cluster
2020/03/18 17:42:01 [ERROR] ClusterScanController scheduledscan/c-8q8rv:42 * * * * [scheduledScanHandler:sync] failed with : CIS scan already running on cluster
E0318 17:42:03.362883      28 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
2020/03/18 17:42:03 [ERROR] ClusterScanController scheduledscan/c-8q8rv:42 * * * * [scheduledScanHandler:sync] failed with : CIS scan already running on cluster
2020/03/18 17:42:06 [DEBUG] Triggering auth refresh on user-ss4bl
2020/03/18 17:42:06 [DEBUG] Skipping refresh for user-ss4bl due to max-age
2020/03/18 17:42:07 [ERROR] ClusterScanController scheduledscan/c-8q8rv:42 * * * * [scheduledScanHandler:sync] failed with : CIS scan already running on cluster
2020/03/18 17:42:07 [ERROR] ClusterScanController scheduledscan/c-8q8rv:40 * * * * [scheduledScanHandler:sync] failed with : CIS scan already running on cluster
```

**Other details that may be helpful:**
**Note:**
Able to consistently reproduce the issue when the cron time for the Scheduled CIS scan is changed (cluster edit) when a scan is running on the cluster

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `330a4bed0 `
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom/rke do
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by StrongMonkey** [comment]
This is a composite of a UI bug. We use annotation on cluster to control whether CIS has been running in the cluster. So When CIS is running, cluster will have the annotation(something like `field.cattle.io/runCisScan: cis-1584590230024166817`). And after CIS is done, controller will automatically remove the annotation. But If user is editing the schedule-run at this time, UI will have the old annotation data and sending the wrong payload to update cluster, appending the CIS annotation again. To fix this, I suggest to move annotation into cluster.status so that it will not be changed accidentally during a regular PUT request.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `500bc21f1`**

**Steps:**

- Run a manual scan or when a scheduled scan is in "running" state  go to edit cluster
- change the cron time of CIS schedule 
- click on save. 
- Click on Run Scan after the previous scan is finished. And report is generated.
- No error seen on the cluster.
- User is able to perform Run Scan action
