### ISSUE TITLE
Missing arm64 for rancher/coreos-flannel:v0.11.0-rancher1

### ISSUE THREAD

**Issue by pvizeli** [rancher/rancher#26106]
I have many issues with running Rancher on a ARM64 cluster. I found now out, that the arm64 version for v0.11.0 is missing -> https://hub.docker.com/r/rancher/coreos-flannel/tags

**Comment by BarthV** [comment]
+1 here !

Why not releasing it like you already did for v0.10.0 ?

**Comment by BarthV** [comment]
dups https://github.com/rancher/rancher/issues/25375
