### ISSUE TITLE
better display of scaled-down GKE/EKS/AKS clusters

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#26117]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Details:**

It is a fairly common cost-cutting maneuver when using cloud-managed clusters (GKE, EKS, AKS, etc.) to scale them down to zero to save money when not in use. Especially in GKE, where the master nodes are free, scaling a cluster to zero workers means the cluster is literally costing nothing while scaled down.

Unfortunately, since Rancher depends on the presence of the cattle agents to determine cluster liveness and health, scaling an imported GKE cluster to zero workers means the cluster appears as "unavailable" when in this state.

It would be nice if Rancher was more aware of this specific type of "unavailable" and can display it properly in the UI. Instead of showing the cluster as "unavailable", it could instead show it as "Shutdown".

gz#8766

**Comment by vincent99** [comment]
There's bad news headed your way on GKE pricing... https://cloud.google.com/kubernetes-engine/pricing

What is the difference you're really looking for between "unavailable" and "shut down"?  Displaying the state as not-red, because it's desired?

**Comment by leodotcloud** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/27676
