### ISSUE TITLE
External cloud provider option for RKE/node-driver clusters not working as expected

### ISSUE THREAD

**Issue by jlamillan** [rancher/rancher#26118]
The "External" Cloud Provider cluster option for the Infrastructure Provider based RKE cluster is not working how I would expect. 

When I select "External", I expected that both the `kubelet` and `kube-controller-manager` containers would be started with the `--cloud-provider=external` flag set.   Instead, they appear to use/default to `--cloud-provider=aws`

![external CCM](https://user-images.githubusercontent.com/13613687/77018888-4d0eef00-693c-11ea-8c30-0f9bad4097f2.png)

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Add a cluster using a infrastructure provider driver (I'm using the OCI driver, which is in-development)
2. In the Cluster Configuration, choose "External" as the Cloud Provider
3. Optionally, view the config by clicking "Edit as YAML", which does show the cloud_provider _name_ as external:
 
```
rancher_kubernetes_engine_config:
  cloud_provider:
    name: external
```

**Result:**

Instead of `kubelet` and `kube-controller-manager` containers being started with the `--cloud-provider=external` flags set.   Instead, they appear to use/default to `--cloud-provider=aws`:

kubelet for example fails to start:

```
I0318 23:26:06.404510    1863 flags.go:33] FLAG: --cloud-provider="aws"
...
...
I0318 23:26:22.333034    3077 aws.go:1183] Building AWS cloudprovider
I0318 23:26:22.334363    3077 aws.go:1149] Zone not specified in configuration file; querying AWS metadata service
F0318 23:26:22.345484    3077 server.go:273] failed to run Kubelet: could not init cloud provider "aws": unable to determine AWS zone from cloud provider config or EC2 instance metadata: EC2MetadataError: failed to make EC2Metadata request
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: 374b38cb28316125ca6d42bbc70d267685102735
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): OCI Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): v1.15.11

```
jemillan$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:25:00Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
[root@master1 opc]# docker version 
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Comment by westlywright** [comment]
@deniseschannon Per our discussion the UI is sending external correctly so I think we'll need to add a back end resource here to investigate.

**Comment by jlamillan** [comment]
Actually, unless anyone here objects, I am going to close this issue since our CCM no longer requires `--cloud-provider=external`.  So, leaving the Cloud Provider to 'None' and applying our manifests is enough.

**Comment by deniseschannon** [comment]
@jlamillan I'd like to keep it open to see what's going on for supporting external cloud providers in RKE, but I'll move the milestone

**Comment by kinarashah** [comment]
@westlywright When users select `External` Cloud Provider from UI, we expect only the name: `external` to be sent but no other fields. Right now I see that UI passes empty `awsCloudProvider` along with name so backend populates default values for it and if this is not empty, RKE configures AWS cloud provider.  

```
cloudProvider: {type: "cloudProvider", name: "external", awsCloudProvider: {}, cloudConfig: {}}
awsCloudProvider: {}
cloudConfig: {}
name: "external"
type: "cloudProvider"
```

**Comment by kinarashah** [comment]
My steps to reproduce: 

1) Rancher v2.4.5, single node install 
2) Provision an ec2 cluster, and select External cloud provider in UI.

**Comment by izaac** [comment]
Rancher version: `master-head (09/26/2020)` _27000be_

Selecting External in cloud providers is now sending only the required payload, without awsCloudProvider. 

```javascript
"rancherKubernetesEngineConfig": {
   "cloudProvider": {
            "type": "cloudProvider",
            "name": "external"
        }
}
```

Amazon provider with EC2 cluster

```javascript
...
"cloudProvider": {
            "type": "cloudProvider",
            "name": "aws",
            "awsCloudProvider": {
                "type": "awsCloudProvider"
            }
        }
...
```

External provider with EC2 cluster

```javascript
...
"cloudProvider": {
            "type": "cloudProvider",
            "name": "external"
        }
...
```


**Custom** provider works too I checked this with a Linode cluster
