### ISSUE TITLE
Run CIS Scan - User Skipped tests font can be modified to make it more noticeable 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26122]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Go to System Project --> Config
- Create a config map
- name: "security-scan-cfg"
- key: "config.json"
- value: {"skip":{"rke-cis-1.4":["1.1.11","1.1.15"]}}
- Refresh CIS scans page (as there is an issue currently)
- Click on Run Scan
- The pop up window is like

<img width="987" alt="Screen Shot 2020-03-18 at 4 41 18 PM" src="https://user-images.githubusercontent.com/26032343/77025863-75ecaf80-694f-11ea-93b5-a517dba899c7.png">

**Expected Result:**
The skipped tests' font can be modified to make it noticeable

**Other details that may be helpful:**
Related to : https://github.com/rancher/rancher/issues/26066

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - ui tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by lvuch** [comment]
I can't reproduce this but paired with @codyrancher and came up with this option 
![image](https://user-images.githubusercontent.com/3013118/77108573-ae3bce80-69df-11ea-8ef7-82f670896f50.png)

Let us know if this works. Another alternative would be to list the config skips in an additional accoridon.

**Comment by deniseschannon** [comment]
@codyrancher @lvuch This looks good to me.

**Comment by sowmyav27** [comment]
**verified on latest master-head - commit id: `ae4a76a7e` ui tag: latest2**

On a run scan, with user added skips in the config map, the UI is seen as
<img width="1323" alt="Screen Shot 2020-03-20 at 9 55 42 AM" src="https://user-images.githubusercontent.com/26032343/77187785-3d092380-6a92-11ea-89bf-abc139674415.png">
