### ISSUE TITLE
User can change rancher-url without necessary permissions and lock up rancher. 

### ISSUE THREAD

**Issue by JSchuchman** [rancher/rancher#26126]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
- Log into rancher as admin, create a new user with only the global Role "User Base", which is read only in regards to settings. 
- Log out, and log back in as the new user.
- Go to settings, server-url, and select "View in API"
- In the Api view, select the delete operations, then click send request
- Refresh the page

**Result:**
An error appears saying that the server-url cannot be found. The user is then redirected back to login, and no one can log back in. On log in attempts, /v3/settings/server-url?sort=name returns a 404, and prevents further access. 

** Expected Results **
User without write access to settings should not be able to update or delete settings.

**Other details that may be helpful:**
The user can also change the rancher server url.

**Environment information**
- Rancher version: rancher/rancher:v2.3.5
- Installation option (single install/HA): offline HA, on both kops and RKE

**Comment by sangeethah** [comment]
Not able to reproduce this issue when testing on single node install and HA installs - v2.3.5  
Created a user with only the global Role "User Base"

<img width="1189" alt="Screen Shot 2020-03-18 at 10 09 29 PM" src="https://user-images.githubusercontent.com/4266958/77033771-6a0be800-6965-11ea-8c65-91e6f8f9414f.png">

Logged in as this user and tried to delete `server-url` settings using  delete option in "View in API".
Presented with following error message:

```
HTTP/1.1 403
content-encoding: gzip
content-length: 196
content-type: application/json
date: Thu, 19 Mar 2020 05:40:37 GMT
expires: Wed 24 Feb 1982 18:42:00 GMT
server: openresty/1.15.8.1
status: 403
strict-transport-security: max-age=15724800; includeSubDomains
x-api-schemas: https://sangeeha.qa.rancher.space/v3/schemas
x-content-type-options: nosniff

{
"baseType": "error",
"code": "Forbidden",
"message": "settings.management.cattle.io \"server-url\" is forbidden: User \"u-w55ft\" cannot delete resource \"settings\" in API group \"management.cattle.io\" at the cluster scope",
"status": 403,
"type": "error"
}
```

**Comment by JSchuchman** [comment]
Not sure if this changes anything, but it is an offline HA install. I will update the ticket. Besides that there isn’t any other special configuration, I just follow the documentation.

**Comment by huninmunin** [comment]
I tried this with k3s and `rancher.localdev/v3/settings/server-url`
The delete button was there in the api, but a permissions did deny deletion.

**Comment by JSchuchman** [comment]
Ended up being a user error. Cluster had RBAC disabled. When RBAC was enabled our issues went away.
