### ISSUE TITLE
Active Directory Users do not show up in Rancher UI

### ISSUE THREAD

**Issue by mkostersitz** [rancher/rancher#26132]
I deployed Rancher 2.3.5 clean and built a new cluster. 
Setup AD authentication.
I can log in successfully with AD authentication but the users that logged in using AD are not listed under Global/Users so a Role can be assigned or when assigning Members to a cluster resource. That only lists the domain admins group and not all users and groups under the LDAP search root. 

---

Rancher | v2.3.5
-- | --
User Interface | v2.3.36
Helm | v2.14.3-rancher1
Machine | v0.15.0-rancher29

**Comment by uluzox** [comment]
Users are added to the list, after they logged in to Rancher for the first time. At least this is how it looks like for me.
The user you tested the AD authentification with during setup, is automatically assigned the administrator role c.f. https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/ad/#test-authentication

**Comment by mkostersitz** [comment]
Thanks this is resolved
