### ISSUE TITLE
Helm Chart README.md is not displaying in the Detailed Description Area

### ISSUE THREAD

**Issue by Cagrosso** [rancher/rancher#26136]
My helm chart has a README.md file located in the root of the helm chart ($APPNAME/README.md).  When trying to deploy the chart via the App Catalogue, the detailed Description only contains the text located in the Chart.yaml Description field.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.5` UI: `v2.3.36` |
|Route|`catalog-tab.launch`|

**Comment by deniseschannon** [comment]
You need to create an `app-readme.md` for that to show up in Rancher:

https://rancher.com/docs/rancher/v2.x/en/catalog/custom/creating/#rancher-chart-additional-files

**Comment by Cagrosso** [comment]
@deniseschannon That didn't do it.  That added the description to the brief summary to the right of the App logo.  I'm looking to have my README.md display in the Detailed Description field.  Adding the app-readme.md did not solve that issue.
