### ISSUE TITLE
Empty host label not recognized from service scheduler

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#2613]
Hey there,
it is possible to set an empty host label (no value) but if I want to use it like this
```yml
[...]
  labels:
    io.rancher.scheduler.affinity:host_label:  "mongo-replset"
```
.. it fails directly. Saying that no host could be found.
```yml
[...]
  labels:
    io.rancher.scheduler.affinity:host_label:  "mongo-replset="
```
.. it stays in "Scheduling" forever.

**Comment by deniseschannon** [comment]
This is a similar request to https://github.com/rancher/rancher/issues/2601 where you are trying to use the same syntax that selector labels support for scheduling labels. This is not supported and I'll close this one in favor of the other one.
