### ISSUE TITLE
Bug: etcd storage size alert set too small by default

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#26145]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Deploy cluster and enabled alerts

**Result:**
etcd alert for "Database is close to quota" is set to low by default.  Our default maximum size is 2GB so this alert ends up notifying users prematurely that they are over the limit.

**Other details that may be helpful:**
Screenshot:
![image](https://user-images.githubusercontent.com/44879867/77120865-3b971700-6a10-11ea-86c2-5d7ea941495a.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v21.3.5
- Installation option (single install/HA): HA/Siingle

gz#9093

**Comment by deniseschannon** [comment]
At this time, we will not be updating the default size for the alert, but this can be corrected by the end user to update the alert to a higher number.
