### ISSUE TITLE
CIS rke 1.5 config maps should not be available in Rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26147]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster.
- Go to System Project --> Config
- na-rke-cis-1.5 and ds-rke-cis-1.5 should be removed as CIS 1.5 is not available anymore.
<img width="1316" alt="Screen Shot 2020-03-19 at 3 41 00 PM" src="https://user-images.githubusercontent.com/26032343/77121576-b94f2880-69f8-11ea-80be-6ef8e20bab90.png">

**Expected Result:**
- na-rke-cis-1.5 and ds-rke-cis-1.5 should be removed as CIS 1.5 is not available anymore.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `500bc21f1`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke/custom
- Kubernetes version (use `kubectl version`):

```
1.17.4
```

**Comment by deniseschannon** [comment]
There's no harm in having hte config maps of being able to run the scans even though it's not supported yet.

**Comment by sowmyav27** [comment]
Closing the issue as per comments - https://github.com/rancher/rancher/issues/26147#issuecomment-601475439
