### ISSUE TITLE
Add support for SLES 15 SP1

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#26143]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

I am able to run nodes on SLES 12.5 per this:
https://github.com/rancher/rancher/issues/25067#issuecomment-580875741

And, would like to run on [SLES 15.1](https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP1/).  Is this supported?

**Comment by aaronRancher** [comment]
Validated with Rancher `version 2.4.1`

Steps:
Launch instances with the following AMI: `ami-05c7da163cde739d0`
Start docker service
```
sudo service docker start
sudo usermod -aG docker ec2-user
```

Custom cluster validated with existing automation.
HA install validated with 7 nodes (3 etcd, 1 control, 3 worker)
