### ISSUE TITLE
ingress pods not on the newest supported version after upgrade process

### ISSUE THREAD

**Issue by pirminjanka** [rancher/rancher#26155]
**What kind of request is this (question/bug/enhancement/feature request):**
question/bug

**Steps to reproduce (least amount of steps as possible):**
Update RKE k8s Cluster to a newer version

**Result:**
After the Upgrade, the ingress pods are not always on the newest version, sometimes it works sometimes not, sometimes only certain pods are in version 0.25 other ones remains in version 0.21. So we often have ingress pods with version 0.21 instead of 0.25

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.3.5
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM
- Kubernetes version (use `kubectl version`):1.16.6

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:19:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Comment by superseb** [comment]
Is this at all related to https://rancher.com/docs/rancher/v2.x/en/cluster-admin/editing-clusters/#updating-ingress-nginx? Or do you see random versions pop up in your cluster at random times?

**Comment by pirminjanka** [comment]
yes it seems related to this, we started with kubernetes < 1.16, so the update policy is OnDelete. One more question will the deleted/upgraded ingresses automatically get the RollingUpdate updateStrategie?

**Comment by superseb** [comment]
Might be good to double check this after you upgraded. Let me know if this is still happening randomly.
