### ISSUE TITLE
告警通知里面的webhook如何使用？或者提供数据格式如何接入自己开发的webhook接口

### ISSUE THREAD

**Issue by LeoShi02** [rancher/rancher#26152]
*Describe your issue here*

Hi，
 我们现在使用rancher作为我们k8s集群(aws的eks)的控制台，我们使用告警通知时发现只能发送邮件，我们需要最好能接入webook 实现电话短信或者钉钉告警；能否提供下方法；若我们自己开发webook，可能需要你们的告警数据结构，然后触发我们的webhook接口；该怎么办

--
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.3` UI: `v2.3.25` |
|Route|`workload`|

**Comment by loganhz** [comment]
Dingtalk will be supported in 2.4.x: https://github.com/rancher/rancher/issues/19537

If you would like to ask questions in Chinese, please add `rancher2` to join 
Rancher WeChat group. Thanks

**Comment by Zhang21** [comment]
Same demand.

Can I write a application to support rancher monitor webhook, or can add support to enterprise webchat robot  webhook.
