### ISSUE TITLE
UI - CIS Scan - Add schedule should not be enabled for a cluster created using rke template and schedule scan not allowed for user override

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26150]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create an rke template with Schedule CIS scan disabled. (allow user override - No)
- Deploy a cluster using this RKE template.
- When the cluster is up and Active, Navigate to Cluster --> Tools --> CIS scans --> Click on "Add Schedule"
- The user is navigated to the cluster edit page - Advanced options section  - Schedule CIS scan option.
- User will not be able to make any changes to this section now.

**Expected Result:**
Add schedule should not be enabled for a cluster created using rke template and schedule scan not allowed for user override

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `500bc21f1` ui tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke
- Kubernetes version (use `kubectl version`):

```
1.17.4
```

**Comment by codyrancher** [comment]
I went ahead and created a PR for this but I wanted to note that I think it's really strange that rancher frequently seems to disable behavior without providing explanations as to why things are disabled.

**Comment by sowmyav27** [comment]
**Verified on master-head - `546b039e4` ui tag: `latest2`**

- Create an rke template with Schedule CIS scan disabled. (allow user override - No)
- Deploy a cluster using this RKE template.
- When the cluster is up and Active, Navigate to Cluster --> Tools --> CIS scans 
- "Add Schedule" is NOT enabled.
