### ISSUE TITLE
Upgrade not triggered on control nodes that was stuck in "cordoned" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#26154]
Rancher server on master-head - commit id: `0582d678c`

Steps to reproduce the problem:

Deploy a cluster 1 control, 3 etcd and 2 worker nodes - maxUnavailable_control = 1
Upgrade cluster by giving incorrect param - max=pods
```
kubelet:
  extra_args:
    max=pods: 123
```

Save changes made.
The control plane node fails to upgrade and is stuck in Cordoned state.
Edit cluster.yml and give modify param - `max=pods` to `max_pods`
Save changes made.
User is not allowed to update as not enough control plane nodes ready to upgrade, maxUnavailable: 1, notReady: 1, ready: 0
maxUnavailable_control = 2 is changed. and save changes made
this does NOT trigger an update on the cluster.
Control plane node is seen in "Cordoned" state.

Relating to this https://github.com/rancher/rancher/issues/26076#issuecomment-600946668

**Comment by sowmyav27** [comment]
As per offline discussion, this fix is going to fix the following issue also.

- After steps from here
- delete the control plane node stuck in Cordoned state.
- New control plane Node is still in "Registering" state ( as this is a node driver cluster, node will be re provisioned on deletion from node pool)
- Cluster is in

```
This cluster is currently Updating.
[controlPlane] Failed to upgrade Control Plane: [[[controlplane] Error getting node sowmya-zerodt-ctrl-1: "sowmya-zerodt-ctrl-1" not found]]
```

**Issue:**
The control plane - did not register.

**Comment by sowmyav27** [comment]
**Verified on latest master-head - commit id: `3e6e9ddee`**

**Steps:**

- Deploy a cluster 1 control, 3 etcd and 2 worker nodes - maxUnavailable_control = 1
- Upgrade cluster by giving incorrect param - max=pods

```
kubelet:
  extra_args:
    max=pods: 123
```

- Save changes made.
- The control plane node fails to upgrade and is stuck in Cordoned state.
- Edit cluster.yml and give modify param - `max=pods` to `max_pods`
- Save changes made.
- The control node, which is stuck, gets upgraded.
- Cluster comes up Active.

**Comment by menih** [comment]
I am hitting the same issue... is this fixed?
