### ISSUE TITLE
Upgrade service, start behavior default

### ISSUE THREAD

**Issue by etlweather** [rancher/rancher#2615]
In 0.43.1, when doing a service upgrade through the UI, the page has a checkbox for "Start behavior". The default is unchecked which means "stop before start". Checked starts the new container and then stops the old one.

Seems to me that the default should be checked so that a new container is started before stopping the old one so as to maintain the service up.

**Comment by vincent99** [comment]
No; start-before stop doesn't necessarily play well with containers with data volumes (e.g. databases), and public ports can only be bound to one container at a time.
