### ISSUE TITLE
[feature] show free disk space or disk usage in % in a host view

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2616]
I have constantly to check out free disk space, because of devicemapper leak problem, so would be nice to see it on a single page. When something goes wrong on the host the most common problem is 100% disk usage...
Actually you can show only indicator when disk usage is more 80%.

**Comment by sshipway** [comment]
+1 for this.  It would be very helpful to have a small bar/pie in the Host screen to show the space used in the /var/lib/docker filesystem.  However this might need to be configurable if people are using different filesystem locations, or multiple filesystems (such as to hold persistent data)

**Comment by gordontyler** [comment]
Related: #2476

**Comment by cusspvz** [comment]
+1

**Comment by deniseschannon** [comment]
Duplicate of #1542
