### ISSUE TITLE
CIS Scan UI - Modal does not update with User Skipped Tests from Config Map until after page refresh

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#26161]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Go to System Project --> Config --> Add new config in security-scan namespace (to skip tests)
- Run Scan - choose permissive/hardened
- User defined skip tests do not show up.

**Note:**
On a refresh of the page, the skipped tests from the config (user skipped tests) show up.

**Expected Result:**
The skipped tests from config map, should show up in the user skipped tests when Run scan is clicked, without doing a refresh on the webpage.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - `148b3e000` ui tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by codyrancher** [comment]
@sowmyav27 @deniseschannon I was able to get the skip list to update anytime you open the modal. Unfortunately I don't think it's possible to have the modal update without reopening the modal. 

It doesn't appear the backend is sending an update message when just data field of the config map is updated. You can demonstrate this for yourself by: 
1. Opening a config map view page and a config map edit page
2. On the edit page edit the config map data and save
3. Go to the view page and notice that the data doesn't update.

**Comment by deniseschannon** [comment]
@codyrancher I think that's fine. I wouldn't expect it to refresh while the modal is open. As long as it refreshes when the modal is opened.

**Comment by sowmyav27** [comment]
**Verified on latest master-head - commit id: `371ec137f` UI tag: latest2** 

**Steps:**

- Go to System Project --> Config --> Add new config in security-scan namespace (to skip tests)
- Click on Run Scan from Cluster --> more options OR Cluster --> Tools --> CIS Scans --> Run Scan - choose permissive/hardened
- User defined skip tests shows up under "In addition, the following tests have been configured to be skipped as part of the scan"
- No refresh is required.
