### ISSUE TITLE
Standard user can't deploy the gatekeeper app.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/rancher#26163]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster.
2. Create one standard user and make it cluster owner for the cluster created.
3. Through API ``` https://rancher-server/v1/management.cattle.io.clusters/c-xxxx/apps``` try to deploy the gatekeeper app

**Result:**
API returns 404.

When API request is made with admin token, it returns 201 and deploys the app.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2486-head- cf6d0c979
- Installation option (single install/HA): Single

**Comment by sangeethah** [comment]
Related issue for admin user - https://github.com/rancher/rancher/issues/26186

The same issue is also encountered for standard user when trying to enable OPA gatekeeper app.

```
Request URL: https://<ip>/v1/management.cattle.io.clusters/c-xfzxp/apps/p-tgvm6
Request Method: POST
Status Code: 405 Method Not Allowed
```

**Comment by sangeethah** [comment]
Tested with Rancher Server version `371ec137f``

As standard user , deploy a cluster.
Launch Dashboard.
Enable "OPA Gatekeeper".
Able to enable "OPA Gatekeeper" successfully.

**Comment by khushboo-rancher** [comment]
Verified on Rancher server master-2523-head- 371ec137f

API:
1. Enable OPA Gatekeeper with standard user.
2. Enable OPA Gatekeeper with admin user. 

Dashboard
1. As a standard user deployed a cluster.
2.  Launched Dashboard - Encountered https://github.com/rancher/dashboard/issues/393
3. Enable 'OPA Gatekeeper'
4. Create a constraint for repo whitelisting.
5. Verified the violation.
6. Verified all of the above with admin user too.

Encountered the refresh issues while verifying above functionality https://github.com/rancher/dashboard/issues/371
