### ISSUE TITLE
Worker nodes getting upgraded again when a deletion of a powered down worker node happens when the cluster is in Upgrading state

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26164]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Scenario#1**

- Cluster - spec - 1 etcd, 2 control, 3 worker - RKE DO 
- power down one node N1 (worker node)
- max Unavailable worker = 2
- upgrade cluster k8s version from 1.15 to 1.16
- cluster will be stuck in upgrading,.
- All other nodes - k8s version is upgraded except N1.
- delete the worker node N1 - will get re provisioned as its node driver cluster 

**Expected result:**
N1 will get re provisioned, and the cluster will come to active. N1 will have k8s version - 1.16

**Actual Result:**
Other worker nodes, go "Cordoned" Upgrading state again, when N1 is getting re provisioned.

**Scenario#2**
- Cluster - spec - 1 etcd, 2 control, 3 worker - Custom cluster
- power down one node N1 - worker node
- max Unavailable worker = 99%
- upgrade cluster k8s version from 1.15 to 1.16
- cluster will be stuck in upgrading,.
- All other nodes - k8s version is upgraded.
- Delete N1
- N1 is deleted from cluster in Rancher UI

**Expected Result:**
Cluster goes to Updating State and becomes Active

**Actual Result:**

- Cluster goes to "Updating".
- Cluster goes to "Upgrading" and Other worker nodes - 2 others - go into Cordoned and Upgrading state again, before the cluster becomes Active

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `ae4a76a7e`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom and rke
- Kubernetes version (use `kubectl version`):

```
1.15 to 1.16
```

**Comment by deniseschannon** [comment]
Per @kinarashah, the changes are not related to actual upgrade on which nodes get picked, but when/how the upgrade gets called/triggered.

**Comment by sowmyav27** [comment]
Verified with latest - master-head commit id: ``

- Cluster - spec - 1 etcd, 2 control, 3 worker - RKE DO
- power down one node N1 (worker node)
- max Unavailable worker = 2
- upgrade cluster k8s version from 1.15 to 1.16
- cluster will be stuck in upgrading,.
- All other nodes - k8s version is upgraded except N1.
- delete the worker node N1 - will get re provisioned as its node driver cluster
- N1 will get re provisioned, and the cluster comes to active. N1 has the upgraded k8s version - 1.16
- logs when N1 is getting re provisioned:
```
2020/03/24 18:50:27 [INFO] cluster [c-g4g7z] worker-upgrade: finished upgrade
2020/03/24 18:50:27 [DEBUG] cluster [c-g4g7z] upgrading condition: [true] plan changed: [false]
2020/03/24 18:50:27 [DEBUG] cluster [c-g4g7z] worker-upgrade cluster status node version [2]
2020/03/24 18:50:27 [DEBUG] cluster [c-g4g7z] worker-upgrade: node [m-xhg54] is not a workerOnly node
2020/03/24 18:50:27 [DEBUG] cluster [c-g4g7z] worker-upgrade: node [m-54gxx] nodeConfig is empty
2020/03/24 18:50:27 [DEBUG] cluster [c-g4g7z] worker-upgrade: node [m-vg8tc] is not a workerOnly node
2020/03/24 18:50:27 [DEBUG] cluster [c-g4g7z] worker-upgrade: node [m-frpf7] is done
2020/03/24 18:50:27 [DEBUG] cluster [c-g4g7z] worker-upgrade: node [m-drqk6] is not a workerOnly node
2020/03/24 18:50:27 [DEBUG] cluster [c-g4g7z] worker-upgrade: node [m-x2xtp] is done
2020/03/24 18:50:27 [DEBUG] cluster [c-g4g7z] worker-upgrade: workerNodeInfo: nodes 2 maxAllowed 2 upgrading 0 notReady [] toProcess [] toPrepare [] done []
2020/03/24 18:50:27 [DEBUG] cluster [c-g4g7z] worker-upgrade: cluster is done upgrading, done 2 len(nodes) 2
2020/03/24 18:50:27 [DEBUG] isActiveCluster: true isWindowsCluster: false user: user-zm7x7, canUpdateCluster: true
```
