### ISSUE TITLE
Set default value of node drain input to 120

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26170]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Enable Drain**
- Create a cluster - rke/custom
- Enabled Drain for Upgrade strategy
- The default value for drain timeout is 60 seconds.
- Click on Save. The drain timeout is 60 seconds.

**Disable Drain**
- Create a cluster - rke/custom
- Disabled drain option
- Click on save. 
- In the response from the request -- "Network" tab of dev tools, "timeout" is set to 120 seconds
```
"nodeDrainInput": {
        "deleteLocalData": false,
        "force": false,
        "gracePeriod": -1,
        "ignoreDaemonSets": true,
        "timeout": 120,
        "type": "/v3/schemas/nodeDrainInput"
      },
```
**Expected Result:**
When drain is disabled, the default value should be set as 60

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `ae4a76a7e`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke/custom
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by mrajashree** [comment]
@sowmyav27 The default for drain timeout has always been 120.
When enabling drain:
<img width="1331" alt="Screen Shot 2020-03-20 at 5 09 20 PM" src="https://user-images.githubusercontent.com/10672776/77214782-e15c8b80-6acd-11ea-8cbc-421b959f2704.png">
And the corresponding request
<img width="810" alt="Screen Shot 2020-03-20 at 5 10 17 PM" src="https://user-images.githubusercontent.com/10672776/77214799-f2a59800-6acd-11ea-9a43-1906893fed2d.png">

And the same while disabling, where exactly do you see it being set to 60?

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `546b039e4`**

- `/v3/schemas/nodeDrainInput` -- has:
```
"timeout": {
"create": true,
"default": 120,
"max": 10800,
"min": 1,
"type": "int",
"update": true
}
```
