### ISSUE TITLE
Adding Brightbox Cloud to the Docker Machine provider screen in Rancher

### ISSUE THREAD

**Issue by NeilW** [rancher/rancher#2619]
Hi,

Thanks to the Docker-Machine 0.5.0 driver plugin system I've been able to create a docker-machine plugin that drives the Brightbox Cloud (https://github.com/brightbox/docker-machine-driver-brightbox)

I was wondering what would be needed to get that working with the Rancher Docker Machine integration so that I can use it directly from the UI.

**Comment by deniseschannon** [comment]
We haven't upgraded docker-machine to run 0.5.0 in Rancher yet, but when we look into it, we can take a look at how to use the driver plugin system that's been added. 

This will be a feature request because even when we move to v0.5.0, we might not be able to immediately support the new driver plugin system.

**Comment by NeilW** [comment]
Hopefully it'll get considered by #2576 when they're reconfiguring the generator part of go-machine-service.

Obviously I'm happy to help if I can.

**Comment by deniseschannon** [comment]
With the release of v1.1, we've add in support for custom machine drivers: http://docs.rancher.com/rancher/latest/en/configuration/machine-drivers/#adding-machine-drivers as well as custom UI for Machine Drivers: In addition to being able to add your own Docker Machine drivers into Rancher, this feature will allow users to also add their own custom UI elements for the driver. Please see https://github.com/rancher/ui-driver-skel for more details.

If a custom UI is requested for brightbox cloud, we'd advise to create your own at this time.
