### ISSUE TITLE
Plz add to docs instructions for installing RC versions via helm

### ISSUE THREAD

**Issue by trauts2** [rancher/rancher#26196]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**
Looking at docs at https://staging.rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/ha/

There are instructions for the helm repo for latest and stable versions.  But it does not explain how to install v2.4-rc8 or other RC versions via helm.  This would be a small doc addition which I think would benefit users.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
RCs are made for internal testing so this won't be added to the official documentation where people are looking to install official releases of Rancher. If people want to take the risk to use RCs, they can read the Helm chart and find what to use: https://github.com/rancher/rancher/blob/master/chart/values.yaml#L82
