### ISSUE TITLE
Coredns/metrics server pods are not getting evicted when a worker node is powered off

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26190]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy cluster - Cluster spec - 1 etcd, 2 control, 3 worker nodes
- Power off W1 and W2 - worker nodes
- Go to System Project --> Core dns workload - the pods are deployed in nodes W1 and W2, and are not evicted, status of the pods are "Unknown"

**Expected Result:**
The coredns pods should be evicted from W1 and W2 and should deploy on W3

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `546b039e4` 
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by sangeethah** [comment]
This behavior is also seen when testing with rancher server version - v2.3.5

**Comment by StrongMonkey** [comment]
The workaround is to delete the pod until the pod gets schedule into healthy nodes.

**Comment by sowmyav27** [comment]
Verified on master-head - commit id -  

**Steps:**

- Deploy cluster - Cluster spec - 1 etcd, 2 control, 5 worker nodes
- Power off W1 and W2 - worker nodes
- Go to System Project --> Core dns workload - the pods are deployed in nodes W1 and W2, and are not evicted, status of the pods are "Unknown"
- Delete the pods deployed on W1 and W2. They will get deployed on other active worker 
- CIS scan run is successful on this cluster.

**Comment by adampl** [comment]
Doesn't it require the [Taint-based Evictions](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#taint-based-evictions) feature, which is GA since Kubernetes 1.18?

**Comment by Jono-SUSE-Rancher** [comment]
Would the changes made for taints and tolerations have corrected this? @superseb CC:@deniseschannon

**Comment by superseb** [comment]
Yes this was fixed as part of https://github.com/rancher/rancher/issues/27734

**Comment by anupama2501** [comment]
Verified on 
Rancher | v2.5-a420b5195dd1d0a23411b0aeb17713f291e90e10-head 
and 
Rancher | master-eda2a07c98fb3441260308ab9253c58e1fca7761-head

k8s : v1.19.8, v1.18.16, v1.20.4

Steps:
- Create a cluster with 4 worker, 1 etcd, 1 cp and add the tolerations to DNS as follows:
```
provider: coredns
tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        toleration_seconds: 15
```

- From the system project, in the coredns workload, verify the nodes on which it was deployed and power off the nodes
- Wait for the status to change from "Running" to "Unknown"
- In some time [toleration set above as 15 sec therefore nodes started deploying in 15-20], we see pods are evicted and are deployed one new nodes
