### ISSUE TITLE
rancher-images.txt does not contain all k3s images needed for upgrade in airgap

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#26200]
When you follow airgap instructions, you have to mirror images in rancher-images.txt to your private registry.

With the new ability to upgrade a k3s cluster from Rancher, we want to make sure that that image list includes all necessary k3s images. We already handle the images that actually perform the upgrade (rancher/system-upgrade-controller and rancher/k3s-upgrade), but we are not handling the images that k3s will deploy once an upgrade takes. These images like coredns and traefik.

As of `v1.17.4-alpha1+k3s1`, we've started to publish that list of images as a release artifact in k3s. See:
https://github.com/rancher/k3s/releases/download/v1.17.4-alpha1%2Bk3s1/k3s-images.txt
https://github.com/rancher/k3s/releases/download/v1.17.4-rc1%2Bk3s1/k3s-images.txt

Additionally, some of the images in that list (specifically coredns and traefik) do not come from the rancher docker hub organization.

*Two things should be fixed/changed*:
1. rancher-images.txt should contain the k3s images for any releases of k3s that are bundled into the rancher release as part of kontainer-driver-metadata (see: https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/data/data.json#L4650-L4661)
2. k3s should only use images from the rancher docker hub org. So, specificaly, traefik and coredns should be fixed to reference images from rancher.

**Note:** This would not have surfaced in the airgap testing we already did for rancher + k3s because to standup the k3s cluster in the first place you had to make the images available to the k3s cluster when you stood it up initially. So, the images didn't change on upgrade and thus no problems were noticed.

**Comment by cjellick** [comment]
Note that as part of this change, we've also updated KDM to only have `v1.17.4-rc2+k3s1` as the available k3s version. We dropped the 1.16 release that was in there as that was only in there for the purposes of testing that upgrades show up when appropriate.

**Comment by deniseschannon** [comment]
Available to test with v2.4.0-rc10

**Comment by jiaqiluo** [comment]
There is no k3s-related images in the `rancher-images.txt` file in v2.4.0-rc10 release https://github.com/rancher/rancher/releases/tag/v2.4.0-rc10

**Comment by jiaqiluo** [comment]
This is validated in Rancher: `v2.4.0-rc11` release that the `rancher-images.txt` file contains all images need for upgrading imported k3s cluster 

Steps:
- provision a k3s cluster in airgap env (2 servers, 1 agent, external mysql database, k3s version v1.0.1)
- install Rancher:v2.4.0-rc11 in airgap env 
- import the k3s cluster into Rancher
- check that the k3s cluster is functional properly
- edit and upgrade the k3s cluster 
<img width="653" alt="Screen Shot 2020-03-24 at 5 43 09 PM" src="https://user-images.githubusercontent.com/6218999/77490492-3bc05980-6df8-11ea-8b11-1d59db11f31f.png">

Results:
- the k3s cluster is upgraded to `v1.17.4-rc2+k3s1` successfully
- check that the k3s cluster is functional properly

**Comment by cjellick** [comment]
Reopened this because https://github.com/rancher/rancher/pull/26223 had not been merged. Now that taht is merged, you need to do one more pass to ensure that the rancher-images.txt file that is produced in the next RC has all the proper images.

**Comment by jiaqiluo** [comment]
It is validated that the release `Rancher:v2.4.0-rc12` contains all images need for upgrading the imported k3s cluster. 

This is done along with testing upgrading Rancher (HA installation) from `v2.3.5` to `v2.4.0-rc12` in an air-gapped environment.

k3s cluster `v1.0.1` is provisioned with 1 server + 1 agent in an air-gapped environment, then is upgraded via Rancher UI to `v1.17.4+k3s1`

before upgradtion 
![Screenshot_2020-03-27 Rancher](https://user-images.githubusercontent.com/6218999/77804330-7e727380-703c-11ea-9b0d-61f3f6483bd9.png)

after upgradtion 
![Screenshot_2020-03-27 Rancher(1)](https://user-images.githubusercontent.com/6218999/77804373-94803400-703c-11ea-81d7-5696a332cb91.png)
