### ISSUE TITLE
EKS Cluster CredentialsError: Missing credentials in config UI error 

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#26208]
**What kind of request is this:**
Bug

**Steps to reproduce:**

- Create an EKS cluster I used the following options (see screenshot)

![screencapture-96-126-103-245-g-clusters-add-launch-amazoneks-2020-03-23-12_05_54](https://user-images.githubusercontent.com/27659/77354702-8068c980-6d00-11ea-9485-f57b4c288540.png)

**Result:**

Results in **CredentialsError: Missing credentials in config** shown in the UI very quick with no Errors in Network or Console tabs in the Browser Dev Tools.

<img width="1241" alt="Screen Shot 2020-03-23 at 12 14 27 PM" src="https://user-images.githubusercontent.com/27659/77354781-9b3b3e00-6d00-11ea-9b23-8f402f55a69b.png">

**Other details that may be helpful:**

Creation of the Cluster continues with no apparent issues. 

**Environment information**
- Rancher version: `2.4 master-head (03/23/2020)` commit id: 371ec137f
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
The key to testing this issue is the VPCs, ensure that when you are setting up the cluster you make non-default VPC/Subnet selections.

**Comment by izaac** [comment]
Blocker for validation: https://github.com/rancher/rancher/issues/26237

**Comment by izaac** [comment]
Rancher version: `v2.4.0-rc11`

Validated I was no longer able to reproduce the reported issue. I tried combinations of setting VPCs and using default values.
