### ISSUE TITLE
Request to /v3/users at logout is seen in chrome dev tools

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#26201]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Install Rancher (`2.4 master-head (03/23/20)` commit id: 371ec137f)
2. Create password for default admin user.
3. Once logged in, open the Chrome DevTools Network tab.
4. Logout

**Result:**

Request to `/v3/users?me=true` is made with `401 Unauthorized`

`{"type":"error","status":"401","message":"must authenticate"}`

**Other details that may be helpful:**

This can't be noticed using Rancher `v2.3.4`
This is also not affecting functionality.

**Environment information**
- Rancher version: `2.4 master-head (03/23/20)` commit id: 371ec137f
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
This is not a bug. Its part the detection process to see if we're logged in. The failed response is caught by the front end and handled. You see it on log out because we refresh the page to clear any stale data.

**Comment by izaac** [comment]
Closing as this is by design.
