### ISSUE TITLE
Additional OPA Gatekeeper enhancements

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#26210]
This ticket is to track the GA support of OPA Gatekeeper  that includes the nice to have and future design considerations .

Design considerations/Nice to have:
- Rancher should have some pre-canned policies for  PSP functionality.
- Nice to have: Simple enable toggle during RKE provisioning similar functionality as monitoring.
- Users should be able to setup global policies and apply to one or many clusters.
- If rancher has a predefined policy, it should be editable by the user. If the user would like to “reset” and go back to the default setting that should be an option to them.
- Global level policy manager.
Policies: Will reside at the cluster level initially, with plans to be able to apply from a global catalog.

- Users should be able to enable this through the Terraform provider / cluster provisioning process.

Out of the box policies that could be included:

- Policy for whitelisting registries in a namespace, cluster (Included in v2.4), and globally.
  - A user should be able to add Registries easily from the UI/API at each scope.
- Policy for enforcing a specific registry.
  - At a project, cluster and global level, an admin should be able to rewrite the images to use a specific registry.
- Policy to enforce cluster level unique ingress names.
- Users should be able to leverage Gatekeeper's ability to mutate deployments.

**Comment by rayandas** [comment]
Here are the findings:
**Design considerations/Nice to have:**
1. Rancher should have some pre-canned policies for PSP functionality: PSP is removed from K8s 1.25.
2. Nice to have: Simple enable toggle during RKE provisioning similar functionality as monitoring: This is a V1 feature and doesn't apply for V2 charts.
3. Users should be able to setup global policies and apply to one or many clusters: Not implemented in Rancher. Gatekeeper upstream doesn't have multicluster support. 
4. If rancher has a predefined policy, it should be editable by the user. If the user would like to “reset” and go back to the default setting that should be an option to them: Currently users can create, delete and modify the templates. The "reset" cannot be implemented as rancher doesn't store any timestamp about the templates that's been created or modified.
5. Global level policy manager.
    * Policies: Will reside at the cluster level initially, with plans to be able to apply from a global catalog.
    * Users should be able to enable this through the Terraform provider / cluster provisioning process: Not implemented. But might be implemented. One way could be to ship OPA Gatekeeper with the installation of Rancher and add another scope as global along with namespace and cluster (these two are already deployed). But https://github.com/open-policy-agent/gatekeeper/issues/2027 according to this issue OPA Gatekeeper doesn't have multi cluster support. https://open-cluster-management.io/ is an alternative.

**Out of the box policies that could be included:**
1. Policy for whitelisting registries in a namespace, cluster (Included in v2.4), and globally.
    * An user should be able to add Registries easily from the UI/API at each scope: Policy for whitelisting registries in a namespace, cluster is already implemented. A user should be able to add Registries...
2. Policy for enforcing a specific registry.
    * At a project, cluster and global level, an admin should be able to rewrite the images to use a specific registry: Policy for enforcing a registry is already implemented for namespace and cluster. But an admin should be able to rewrite the images to use a specific registry.
3. Policy to enforce cluster level unique ingress names: Not implemented but can be implemented. We just have to add a template for this.
4. Users should be able to leverage Gatekeeper's ability to mutate deployments: Not implemented on UI but everything can be done via kubectl. Can be implemented on UI based on need. Mutation means that policy can change Kubernetes resources based on different criteria using Mutation policies. I have tried all the three type of mutation policies on Rancher RKE2 cluster view kubectl shell. It can be implementen on UI like we have Constraint Templates (default policies in OPA Gatekeeper app). More on https://open-policy-agent.github.io/gatekeeper/website/docs/mutation

@MKlimuszka @prachidamle @mitulshah-suse
