### ISSUE TITLE
flaky test: test_catalog_refresh

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#26214]
Investigate test for flakiness, resolve if needed

**Failed tests:**
https://drone-pr.rancher.io/rancher/rancher/8147
https://drone-pr.rancher.io/rancher/rancher/8139
https://drone-pr.rancher.io/rancher/rancher/8134
https://drone-pr.rancher.io/rancher/rancher/8125
https://drone-pr.rancher.io/rancher/rancher/8124
https://drone-pr.rancher.io/rancher/rancher/8122

**Comment by dramich** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/26451
