### ISSUE TITLE
Tests failing in drone runs with error "Failed to establish a new connection: [Errno 111] Connection refused"

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#26215]
Investigate test for flakiness, resolve if needed

**Failed tests:**
https://drone-pr.rancher.io/rancher/rancher/8143
https://drone-pr.rancher.io/rancher/rancher/8133
https://drone-pr.rancher.io/rancher/rancher/8107
https://drone-pr.rancher.io/rancher/rancher/8071
https://drone-pr.rancher.io/rancher/rancher/8009
https://drone-pr.rancher.io/rancher/rancher/7992

**Comment by mrajashree** [comment]
This test isn't flaky, it was last year but I'd put a pr to fix that https://github.com/rancher/rancher/pull/18485

It failed in these builds along with many other tests with a connection refused error
```
>           raise ConnectionError(e, request=request)
E           requests.exceptions.ConnectionError: HTTPSConnectionPool(host='172.17.0.3', port=8443): Max retries exceeded with url: /v3/roletemplates (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xffffa72b9fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by rmweir** [comment]
does not appear to be a flaky test, closed in favor of: https://github.com/rancher/rancher/issues/26427
