### ISSUE TITLE
Route53 fails to start due to "dial tcp: lookup route53.amazonaws.com on 169.254.169.250:53: no such host"

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2621]
http://forums.rancher.com/t/trouble-connecting-to-route53/915

Its possible for the Route53 connection to be done too soon, before rancher network is fully set. It can cause DNS resolution issues, so Route53 container does.

**Comment by alena1108** [comment]
@sangeethah could you run your regular set of test cases for Route53? I did a little bit of refactoring to route53 to incorporate network connectivity check.

**Comment by sangeethah** [comment]
Tested with Route53 DNS version - v0.1.7-rancher1.

Tested the regular set of test cases for Route53 , involving programming of route53 for following use cases:
1. Creating LB service / service with ports
2. scale up LB service / service with ports multiple times
3. scale down LB service / service with ports multiple times - #2698
4. Delete route53 entries for existing LB service / service with ports from AWS . Wait for them to get reprogrammed.
5. Started  route53 service , after Creating  LB service / service with ports.

Health check for Route 53 services:
1. Bring up Route 53 instance in a  new host , so both network agent and  Route53  instance is starting at the same time.
2. Bring down host where Route 53 instance is running. Make sure Route53  instance  gets created in a new host.
3. Delete the existing Route 53 instance. Make sure it gets recreated by service reconcile.
3. Stop the existing Route 53 instance. Make sure it gets started by service reconcile.

In all the above cases , make sure that the Route 53 service that was started functions as expected.

**Comment by eebjr** [comment]
I noticed this is closed. Does that mean I can now get the fix? If not, when?

**Comment by deniseschannon** [comment]
Yes, v0.1.7 of the Route 53 Service has been released and shoudl be available in the Catalog.

**Comment by janeczku** [comment]
I just tested both `rancher/external-dns:v0.1.7` and `rancher/external-dns:v0.1.`9. This still seems to be an issue in some environments.

```TEXT
time="2015-12-04T16:52:13Z" level=fatal msg="Failed to list hosted zones:
Get https://route53.amazonaws.com/2013-04-01/hostedzone/?maxItems=9223372036854775807:
dial tcp: lookup route53.amazonaws.com on 169.254.169.250:53: no such host"
```

**Comment by janeczku** [comment]
Actually the Rancher DNS server is the culprit here: https://github.com/rancher/rancher/issues/2928

**Comment by vincent99** [comment]
@janeczku: `route53.amazonaws.com` is a single A record and under 100 bytes, so even if there are size-related issues they wouldn't apply here.  This issue was that the container can start up and make a request before the resolv.conf and rancher-dns answers are in place.

**Comment by janeczku** [comment]
@vincent99 
The size of the message returned by Rancher DNS for that query is actually around the 512 bytes limit. Depending on what records that domain contains at the time of the query it may return an oversize UDP reply resulting in Route53 container to fail (see https://github.com/rancher/rancher/issues/2928#issuecomment-162212607 for steps to reproduce)

Actual query within a container configured with managed network and whose host's resolv.conf has `nameserver 194.120.55.3`:

```TEXT
; <<>> DiG 9.10.2-P4 <<>> route53.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55848
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 6, ADDITIONAL: 2

;; QUESTION SECTION:
;route53.amazonaws.com.		IN	A

;; ANSWER SECTION:
route53.amazonaws.com.	18	IN	A	54.239.19.226

;; AUTHORITY SECTION:
route53.amazonaws.com.	865	IN	NS	ns-932.amazon.com.
route53.amazonaws.com.	865	IN	NS	ns-923.amazon.com.
route53.amazonaws.com.	865	IN	NS	ns-921.amazon.com.
route53.amazonaws.com.	865	IN	NS	ns-911.amazon.com.
route53.amazonaws.com.	865	IN	NS	ns-931.amazon.com.
route53.amazonaws.com.	865	IN	NS	ns-912.amazon.com.

;; ADDITIONAL SECTION:
ns-911.amazon.com.	35	IN	A	207.171.178.6
ns-923.amazon.com.	35	IN	A	72.21.208.215

;; Query time: 12 msec
;; SERVER: 169.254.169.250#53(169.254.169.250)
;; WHEN: Sat Dec 05 16:37:40 UTC 2015
;; MSG SIZE  rcvd: 454
```

**Comment by janeczku** [comment]
fixed in https://github.com/rancher/rancher-dns/commit/cfb851c7b4f70a3d617d4d694053767cd8df83c9

**Comment by eebjr** [comment]
I just fired up a route53 container, on Rancher v50, and it worked! It removed an entry that I didn't expect it to remove, but that's on me... Looks like this is working for me now. Thanks.

**Comment by alena1108** [comment]
@janeczku thanks for debugging and fix it!
