### ISSUE TITLE
Cannot use Aliyun virtual kubelet feature

### ISSUE THREAD

**Issue by chenchi2038** [rancher/rancher#26226]
* Follow Aliyun virtual kubelet docs, the node doesn't show up correctly in Rancher UI.
* Users can only use `nodeName` to schedule pod to the virtual kubelet . `nodeSelector` doesn't work for virtual kubelet .
*  After specifying the `nodeName` via YAML, users can not update it via Rancher UI as  `nodeName` will be removed if we update it via workload edit page

Aliyun virtual kubelet docs:

https://help.aliyun.com/document_detail/118970.html

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.5` UI: `v2.3.36` |
|Route|`containers.index`|

**Comment by loganhz** [comment]
If you would like to ask questions in Chinese, please add `rancher2` to join 
Rancher WeChat group. Thanks

**Comment by maggieliu** [comment]
@guangbochen Please update the PRs since "Types" is got merged into Rancher in master

**Comment by GGGitBoy** [comment]
@maggieliu PR has been updated

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/rancher/pull/27523

**Comment by DoNotSayYes** [comment]
**Version:** `rancher/rancher: master-head` 
**Commit:** [3ff065f](https://github.com/rancher/rancher/commit/3ff065fb6d1c448a5bd9343460d80a44e7d6cfaf)

**Steps to verify:**
1. Add an Aliyun ack cluster on Rancher UI
2. After the cluster is ready, add a virtual node on the Aliyun dashboard
3. Check on Rancher UI

**Result:**
The virtual node can be displayed correctly and users can schedule pods to it
![image](https://user-images.githubusercontent.com/57614736/93187589-881a9f80-f772-11ea-9cc5-cb5e485e4a9f.png)
