### ISSUE TITLE
Move kdm download from dapper to package script

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#26222]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Description:**
data.json file from kdm is being cached, which can result in an outdated images text in rancher releases.

**Notes:**
Can be resolved by moving data.json download from dapper to package script.

**Comment by cjellick** [comment]
I'm closing this issue. We just need to track against the issue can test against: https://github.com/rancher/rancher/issues/26200

They cant really test this one
