### ISSUE TITLE
EKS Error parsing state: default ami of region xx for kubernetes version 1.15 is not set

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#26237]
**What kind of request is this:**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Start provisioning an Amazon EKS cluster
- Notice default version in latest `master-head`  (a9d7ce3da) is now 1.15

**Result:**

Error parsing state: default ami of region xx for kubernetes version 1.15 is not set

** Other information: **

2.4.0-rc10 had 1.14 as supported and latest kubernetes version for EKS.

**Environment information**
- Rancher version: `2.4 master-head (03/24/2020)` commit id: a9d7ce3da
- Installation option (single install/HA): single

**Comment by deniseschannon** [comment]
@westlywright I don't think EKS has support for k8s 1.15 at this time.

**Comment by westlywright** [comment]
1.15 looks to be available but I am guessing we'll need to update kontainer driver to handle the changes. I'll remove 1.15 from the versions list.

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/25/2020)` commit id: ae28b67cc

Validated that rancher is now able to find the default AMI and the cluster is created successfully. I tested with regions `us-east-2` and `us-west-2`.
