### ISSUE TITLE
Edit page of EKS shows options as if they are editable when they are not updatable

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#26231]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Provision an EKS cluster
2. Edit the EKS cluster
3. Input AWS credentials 

**Result:**
After the AWS credentials, the UI guides you through a step by step of picking VPC, subnet, etc, but none of those are updatable. The only option that can be updated is the k8s version. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): any version
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): N/A
- Kubernetes version (use `kubectl version`): doesn't matter

**Comment by rancher-max** [comment]
#### Tested with master-head commit id `ae28b67cc`

- Edit page only allows editing k8s cluster, which is correct.
- REOPENING because the subnet goes to null and cannot save an edit due to this error: `Validation failed in API: amazonElasticContainerServiceConfig subnets=NotNullable 422:`

**Comment by rancher-max** [comment]
#### Findings from testing EKS with Rancher v2.3.5 

- If using default options for VPC/Subnet (`Standard: VPC and Subnet are automatically created`), then we initially send subnet as an empty array. This correctly creates a new vpc and subnets, but the backend stores `subnet` as `null`. Then, going back in and editing the cluster, we must select a subnet to be able to save the edits correctly.
- If selecting a VPC/Subnet during initial cluster creation, then that information is stored in an array in the backend (`subnet=[sub1,sub2,sub3]`), which is then retrieved during edit and a value does not need to be re-selected.

**Comment by rancher-max** [comment]
#### Validated in master-2564-head with default ui-index (`latest2`)

- Need to input secret key in order to be able to edit. This is expected behavior
- After inputting secret key, the only editable field is Kubernetes Version. Downgrading is correctly not allowed, and upgrading successfully upgrades the cluster kubernetes version. 
- If a subnet was selected upon initial creation, then the initial values that were selected are sent on edit as well.
