### ISSUE TITLE
Run scan freezes UI when using invalid security-scan-cfg

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#26248]
master-head

Steps:

1. Create a `security-scan-cfg` with invalid value.  (copied it from docs by mistake)

![image](https://user-images.githubusercontent.com/21168270/77532694-57972e80-6ed0-11ea-98ad-c3c0aa347f34.png)
![image](https://user-images.githubusercontent.com/21168270/77532798-9200cb80-6ed0-11ea-9ed4-f3c0f14a5bcd.png)

2. Try to Run Scan

Results:

UI freezes

![image](https://user-images.githubusercontent.com/21168270/77532939-db511b00-6ed0-11ea-9aed-d38d06d6a419.png)

Expected:

UI should be able to tolerate invalid value of `security-scan-cfg`

**Comment by sowmyav27** [comment]
**verified on master-head - ui tag: latest2**

- Deploy a cluster.
- Go to System project --> Config.
- Create a config - security-scan-cfg. Give value for key: config.json - Copied from docs:

<img width="1289" alt="Screen Shot 2020-03-25 at 11 41 22 AM" src="https://user-images.githubusercontent.com/26032343/77575683-264b3e00-6e91-11ea-9d99-f7771336fdcd.png">

- No error seen on UI
- Gave in invalid value :

```
{
"config.json": {
"skip": {
"rke-cis-1.4": [ "1.1.1", "1.2.2"]
}
}
```
Error seen after the scan is run
<img width="1282" alt="Screen Shot 2020-03-25 at 11 53 23 AM" src="https://user-images.githubusercontent.com/26032343/77575711-306d3c80-6e91-11ea-9ed8-acbc0fcc1c3d.png">
