### ISSUE TITLE
Schedule CIS Scan Enable value is not set on the UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26245]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

- Enable Schedule CIS scan on a cluster.
- Save the changes made.
- Schedule scan will run in the time specified in the cron time.
- Go to Edit Cluster --> Advanced Options --> Scheduled CIS scan --> The values "Yes" is not saved.

**Expected Result:**
Yes/No for Scheduled CIS scan should be saved for a cluster

**Other details that may be helpful:**
Related to: https://github.com/rancher/rancher/issues/26202#issuecomment-602879342

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - ui tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by codyrancher** [comment]
I also added a spelling fix to this issue that @sowmyav27 found. 

I corrected `Maxiumum Worker Nodes Unavailable`

**Comment by sowmyav27** [comment]
**Verified on latest master-head commit id: `29e223653` - ui tag: `latest2`**

- Reopening the issue as when the user selects Schedule CIS scan enabled: Yes, the fields - Profile, retention count and Cron time, are NOT enabled on the UI
<img width="1284" alt="Screen Shot 2020-03-25 at 2 12 53 PM" src="https://user-images.githubusercontent.com/26032343/77586428-6a473e80-6ea3-11ea-8b0e-e803582af3fd.png">

**Comment by sowmyav27** [comment]
**Verified on latest master- ui tag: `latest2`**

- Enabled Schedule scan - Yes, Given in a cron time: 6 * * * *, default value for retention: 24 and Profile: Permissive CIS 1.4
- Error is seen on clicking on Save cluster.

<img width="1096" alt="Screen Shot 2020-03-25 at 5 07 26 PM" src="https://user-images.githubusercontent.com/26032343/77597192-4db70080-6ebb-11ea-90c6-f9c47b271d5e.png">

- `scheduledClusterScan` is sent as null
- In the network tab dev tools:

```
scheduledClusterScan: {enabled: true, scanConfig: null, scheduleConfig: null, type: "/v3/schemas/scheduledClusterScan"}
enabled: true
scanConfig: null
scheduleConfig: null
type: "/v3/schemas/scheduledClusterScan"
```

**Comment by sowmyav27** [comment]
**Verified on latest master-head - commit id: `44f73ad06` ui tag: `latest2`**

- User is able to enable Schedule CIS scan on the UI.
- Values set for the params is saved in the cluster
- Schedule scan is successfully run on the cluster. and report is generated
