### ISSUE TITLE
Remove restriction on minimum supported versions for hosted k8s providers

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#26255]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Launch a hosted k8s provider
2. the UI will restrict what versions can be launched even though the hosted provider has the ability to launch them.

**Result:**

Since Rancher isn't managing the k8s version, Rancher shouldn't care what version it's on.

Note: We should restrict the maximum k8s version supported based on max version that RKE clusters have been launched on, but usually not an issue as the hosted k8s providers are usually behind RKE in allowing support

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5
- Installation option (single install/HA): doesn't matter

**Comment by westlywright** [comment]
This only affects AKS, EKS, and GKE cloud provider clusters.

**Comment by izaac** [comment]
Rancher version: `v2.4 master-head (03/26/2020)` commit id: 44f73ad06
Rancher version: `v2.3-head (03/26/2020)` commit id: 991832341

Validated that the versions on each cloud provider are not restricted now.
Validated I am able to deploy/provision a cluster properly. I tested the boundary version, oldest and newest versions and ran Rancher automation on them as listed below.

**master-head**

GKE `v1.14.10-gke.17`
GKE `v1.15.9-gke.26`

AKS `v1.14.7`
AKS `v1.16.7`

EKS `v1.15.10-eks-bac369` (1.15)
EKS `v1.13.12-eks-879c36` (1.13)


**v2.3-head**

GKE `v1.14.10-gke.17`
GKE `v1.15.9-gke.26`

AKS `v1.14.7`
AKS `v1.16.7`

EKS `v1.15.10-eks-bac369` (1.15)
EKS `v1.13.12-eks-879c36` (1.13)
