### ISSUE TITLE
Manual Quickstart on CentOS 8 fails bringing up rke-network-plugin-deploy-job

### ISSUE THREAD

**Issue by azrdev** [rancher/rancher#26265]
I'm following https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/ on a single CentOS 8 host to bring up a cluster on that single node.

**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- `curl https://download.docker.com/linux/centos/docker-ce.repo > /etc/yum.repos.d/docker-ce.repo`
- `yum install --nobest docker-ce` (docker repo has a broken dependency in the latest version, maybe https://github.com/docker/for-linux/issues/901 )
- `sudo docker run -d --restart=unless-stopped -p 3380:80 -p 33443:443 rancher/rancher` (use different ports for management, in case the cluster needs those)
- get up the webinterface, create a custom cluster with default settings, add all three roles to the new node config, copy that command:
- `sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.3.5 --server https://myhost.myfqdn:33443 --token TOKEN --ca-checksum CACHCK --etcd --controlplane --worker`

**Result:**
After some minutes of setup, the GUI stops changing with the error message:
> This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.
> Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 2vCPU,2GB RAM
- Kubernetes version (use `kubectl version`):

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
Maybe relevant are the following snippets from `docker logs kubelet`:
~~~
W0325 22:09:42.954132   19390 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
W0325 22:09:42.960215   19390 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
I0325 22:09:42.960281   19390 plugins.go:166] Loaded network plugin "cni"
I0325 22:09:42.960357   19390 docker_service.go:255] Docker cri networking managed by cni
W0325 22:09:42.960411   19390 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
...
I0325 22:09:45.067543   19390 kubelet_network.go:77] Setting Pod CIDR:  -> 10.42.0.0/24
E0325 22:09:45.068784   19390 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
W0325 22:09:47.960619   19390 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
E0325 22:09:48.317091   19390 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
W0325 22:09:52.960787   19390 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
I0325 22:09:53.298229   19390 kubelet.go:1906] SyncLoop (ADD, "api"): "rke-network-plugin-deploy-job-25gqq_kube-system(15571da1-b83c-4619-a186-692d03551fb6)"
~~~

I can of course provide more logs if you tell me which ones.

Probably related: #19713

**Comment by azrdev** [comment]
Maybe also related: https://github.com/rancher/rancher/issues/23045

**Comment by superseb** [comment]
This has not been tested, the mentioned ticket (https://github.com/rancher/rancher/issues/23045) is to make sure this is going to work. The steps in this comment were used to have a working setup (https://github.com/rancher/rancher/issues/23045#issuecomment-584755309) but still, that issue will be closed as soon as the OS is validated in the way that we want.
