### ISSUE TITLE
CoreDNS not updating resolv.conf after being re-created

### ISSUE THREAD

**Issue by kristapsm** [rancher/rancher#26272]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Change nameservers in /etc/resolv.conf file on node
2. Delete existing coredns pod for a new one to be created and supposedly have the new resolv.conf file

**Result:**
Cluster still uses old resolv.conf file

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): **v2.3.2**
- Installation option (single install/HA): **HA**

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): **Custom using rke**
- Machine type (cloud/VM/metal) and specifications (CPU/memory): **VM 4 CPUs 16GB RAM**
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:58:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:56:46 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

So basically the issue happened when my nameservers IP got changed and Rancher nodes were not able to ping anything outside like google.com etc, when I changed nameservers in /etc/resolv.conf, nodes were able to ping google.com, but containers running on Rancher were still not able to ping anything externally.
Using the 
```
$ kubectl get pods -o wide -n kube-system | grep coredns
```
I have such pods running (showing as 14h old because I tried this already)
```
coredns-799dffd9c4-2bl72                  1/1     Running     0          14h    10.42.1.7    10.65.5.26   <none>           <none>
coredns-autoscaler-84766fbb4-xw8bp        1/1     Running     0          166d   10.42.2.2    10.65.5.27   <none>           <none>
rke-coredns-addon-deploy-job-fsb2l        0/1     Completed   0          166d   10.65.5.25   10.65.5.25   <none>           <none>
```
And when I try to $ kubectl delete pods -n kube-system coredns-799dffd9c4-2bl72, it re-creates a new one, but still has the same old resolv.conf config as per 
```
$ kubectl run -i --restart=Never --rm test-${RANDOM} --image=ubuntu --overrides='{"kind":"Pod", "apiVersion":"v1", "spec": {"dnsPolicy":"Default"}}' -- sh -c 'cat /etc/resolv.conf'
```
 I get 
```
nameserver 192.169.255.69
nameserver 192.169.255.70
```
which are my old nameservers, as my current /etc/resolv.conf looks like this on all my nodes
```
#nameserver 192.169.255.69
#nameserver 192.169.255.70

nameserver 8.8.8.8
```

**Comment by superseb** [comment]
Please share what OS you are using and what the kubelet has configured as `--resolv-conf` using `ps -ef | grep resolv-conf`. Can you also check what the file contents are in the `kubelet` container for the configured `resolv-conf` file?

**Comment by kristapsm** [comment]
@superseb thanks for helping on this.

My OS is -

```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

This is the result of grep -
```
ps -ef | grep resolv-conf
root      4204  4187  1  2019 ?        2-09:49:13 kubelet --resolv-conf=/etc/resolv.conf --make-iptables-util-chains=true --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --cgroups-per-qos=True --v=2 --authorization-mode=Webhook --event-qps=0 --cluster-dns=10.43.0.10 --fail-swap-on=false --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-node.yaml --root-dir=/var/lib/kubelet --anonymous-auth=false --streaming-connection-idle-timeout=30m --read-only-port=0 --address=0.0.0.0 --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --hostname-override=10.65.5.26 --pod-infra-container-image=rancher/pause:3.1 --network-plugin=cni --volume-plugin-dir=/var/lib/kubelet/volumeplugins --cni-conf-dir=/etc/cni/net.d --authentication-token-webhook=true --cloud-provider= --cluster-domain=cluster.local --cni-bin-dir=/opt/cni/bin --cgroup-driver=cgroupfs
```

And this is the /etc/resolv.conf file on kubelet container -
```
cat /etc/resolv.conf
nameserver 192.168.254.69
nameserver 192.168.254.70
```

And (once again, sorry) this is the actual resolv.conf file on the same node
```
cat /etc/resolv.conf
#nameserver 192.168.254.69
#nameserver 192.168.254.70

nameserver 8.8.8.8
```

**Comment by superseb** [comment]
It depends on how you edited the file, the changes in the file are only going to be reflected in the container if you are editing it in-place (e.g. `nano`) but not by default via `vi` for instance. Now you will need to restart the `kubelet` container to reflect the changes. I

**Comment by kristapsm** [comment]
So if I understand you correctly, for changes on /etc/resolv.conf to take an effect in kubelet container, I need to edit the /etc/resolv.conf file on the node(host) using ```nano``` which would reflect changes in the container automatically and NOT using ```vi``` (which I did use indeed)? Is that correct? And if I do edit the resolv.conf on the node again using ```nano``` right now, would it work now? Or is a restart of ```kubelet``` container necessary anyway? And do I need to restart the container on this one specific node or on all of the nodes?

Sorry for a lot of questions, just want to make sure I do everything correct and not mess up my cluster

**Comment by kristapsm** [comment]
@superseb sorry for pinging you but if you could just clarify my last few questions above, I would be really thankful

**Comment by superseb** [comment]
If the change didn't reflect in the container, you will need to restart the container. If you think there will be issues restarting the container, you can also add new hosts with the correct `/etc/resolv.conf` and after they are added, remove the old hosts.

**Comment by kristapsm** [comment]
Thank you very much for help @superseb. I have restarted all ```kubelet``` containers and everything seems fine for now. Also editing with ```nano``` does reflect changes on container right away. I believe this can be closed then.
