### ISSUE TITLE
Workload not visible in Rancher GUI after importing existing EKS cluster

### ISSUE THREAD

**Issue by fdellutri** [rancher/rancher#26278]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1. In Rancher we imported an existing EKS cluster and deployed some workload
2. We delete the cluster into the Rancher GUI (but the cluster still exists in EKS)
3. We reconnected the cluster through the rancher GUI that provided the kubectl command

**Result:**
The cluster reconnection was successful, but the cluster appears clean without any projects/workload running. We can't see any of the existing workload through the Rancher GUI. The workloads are still alive and visible through kubectl command

**Environment information**
- Rancher version (`rancher/rancher' image tag or shown bottom left in the UI): rancher/rancher 2.3.5
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported AWS EKS
- Kubernetes version (use `kubectl version`): 1.15

**Comment by fdellutri** [comment]
Solved: after the re-importing the association project/namespace was lost. Simply reassign projects to namespaces through "Projects/Namespaces".

**Comment by viswachalla** [comment]
hi

   I request for help for rancher. I lost the rancher management vm. I rebuild, i tried to import the previous cluster to new rancher. I imported the rancher cluster but i am not able to view all workloads/project and pipeline and environment variables. I request for help to retrieve the data.

**Comment by fearlesssssssssss** [comment]
> Solved: after the re-importing the association project/namespace was lost. Simply reassign projects to namespaces through "Projects/Namespaces".


but i could not find the "reassign" to choose. when i click namespace having the same name with eks's, it just showed error: namespaces "cert-manager" already exists, which makes me confused for long time
