### ISSUE TITLE
UI shows Upgrading even after the cluster is already upgraded in a single node k3s cluster

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rancher#26286]
**Steps to reproduce (least amount of steps as possible):**
Import a single node k3s cluster with v1.0.1
Upgrade to the cluster to v1.17.4+k3s1

**Result:**
Cluster is upgraded to the selected version. UI shows still Upgrading

**Other details that may be helpful:**
This issue os not seen in multinode setup.

**Environment information**
- Rancher version: master-head (ImageID: ecd553b460c9)

Screenshot attached:  
![image](https://user-images.githubusercontent.com/56045581/77683871-54df1c80-6f56-11ea-91d6-7803de52033e.png)

**Comment by daxmc99** [comment]
Unable to replicate this bug on master-head (image id: eb09dcb7680b)

**Comment by daxmc99** [comment]
Upgraded to latest-master head, again, unable to replicate.

**Comment by sangeethah** [comment]
@daxmc99 Can you have this merged for 2.4 release as well ?

**Comment by deniseschannon** [comment]
@ShylajaDevadiga @sangeethah this is ready to test in v2.4 now.

**Comment by ShylajaDevadiga** [comment]
Issue mentioned above is resolved. Verified using 2.4-head as well as master-head(Image ID:b0e67872d010), Single control and multi control node. With Drain checked/unchecked.
2.4-head
![image](https://user-images.githubusercontent.com/56045581/78399503-d9124f00-75a9-11ea-92af-aab16df1a3ac.png)

master-head
![image](https://user-images.githubusercontent.com/56045581/78399648-27275280-75aa-11ea-99db-8bc6dfeb6dca.png)

**Comment by khushboo-rancher** [comment]
K3s upgrade verified on rancher server ```master-2689-head - d18a0b6b4``` and ```v2.4-2686-head-00827641e``` worked fine.

Scenarios tested:
1. Single node
2. Multi nodes - combination of single/multiple control plane and workers.
3. Drain option enabled and disabled.
4. Concurrency for control/worker nodes as 1 and 2
