### ISSUE TITLE
[Backport] k8s 1.12 is shown in EKS create cluster but that's not listed in AWS EKS console

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#26285]
**Backport:**
https://github.com/rancher/rancher/issues/26281

**Comment by deniseschannon** [comment]
This is both UI and Backend changes.

**Comment by westlywright** [comment]
UI is in latest2-3

**Comment by izaac** [comment]
Rancher version: v2.3-head  (03/26/2020) commit id: e714692fc

I was able to validate this by deploying clusters with k8s versions 1.13, 1.14 and 1.15 which are the only options shown now in the EKS Kubernetes Version dropdown. Regions checked us-east-2, us-west-2

There's a small UI issue after adding the first cluster. If I go to EKS Create cluster again the Kubernetes Version dropdown defaults to the lowest version (1.13 in this case) with the same browser session. If I open a new browser, or clean up browser history and cookies I see 1.15

**Comment by izaac** [comment]
Closing, I've opened https://github.com/rancher/rancher/issues/26296 for the dropdown issue mentioned above.
