### ISSUE TITLE
k8s 1.12 is shown in EKS create cluster but that's not listed in AWS EKS console

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#26281]
**What kind of request is this:**
Bug

**Steps to reproduce:**

- Create an EKS cluster
- In the Kubernetes version dropdown 1.12 is listed and selectable and 1.15 is default
- EKS lists 1.14 as default (shown in the screenshot) should this be 1.14 in Rancher too?
- Deploying this cluster works

**Result:**

1.12 is listed as a k8s version but EKS doesn't have it as an option anymore.

![Screen Shot 2020-03-26 at 9 56 57 AM](https://user-images.githubusercontent.com/27659/77673999-29edcc00-6f48-11ea-9bf6-cb646386d9a9.png)

**Environment information**
- Rancher version:  `2.4 master-head (03/26/2020)` commit id: 02956b782
- Installation option (single install/HA): single

**Comment by deniseschannon** [comment]
This is both UI and Backend changes.

**Comment by westlywright** [comment]
The UI is in latest2

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/26/2020)` commit id: 98e2ce06d

I was able to validate this by deploying clusters with k8s versions 1.13, 1.14 and 1.15 which are the only options shown now in the EKS Kubernetes Version dropdown. Regions checked `us-east-2`, `us-west-2`

There's a small UI issue after adding the first cluster. If I go to EKS Create cluster again the Kubernetes Version dropdown defaults to the lowest version (1.13 in this case) with the same browser session. If I open a new browser, or clean up browser history and cookies I see 1.15

**Comment by izaac** [comment]
Closing, I've opened https://github.com/rancher/rancher/issues/26296 for the dropdown issue mentioned above.
