### ISSUE TITLE
Rolling back to a snapshot does not upgrade the worker nodes to the previous k8s version

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26289]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy a cluster - 1 etcd, 1 control, 2 worker nodes 1.15
- Take a snapshot S1
- Upgrade k8s version to 1.16
- When the cluster comes up "Active" restore to snapshot S1
- The cluster goes to "Updating" state. And comes back Active
- control plane and etcd node go into "Unavailable" state and the k8s version changes to 1.15
- Worker nodes' k8s version does NOT change to 1.15. 

**Actual Result:**
Worker nodes' k8s version is 1.16 and does NOT upgrade to previous version

**Expected Result:**
Worker nodes' k8s version should have changed to 1.15

**Other details that may be helpful:**
This was tested here https://github.com/rancher/rancher/issues/25647#issuecomment-600885076 Scenariorancher/rancher#2

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id `02956b782`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.15 to 1.16
```

**Comment by sangeethah** [comment]
Other issues that were seen when testing with the same rancher server version:

Scenario 1:
Take a snapshot
upgrade k8s
power down one worker node
cluster stuck in upgrade
restore to snapshot
the cluster is stuck in upgrade, powered down node, is stuck in “Upgrading”.

Scenario 2:
CLuster spec - 1 etcd, 2 control, 3 worker node, max Unavailable worker - 2
take a snapshot
power down one worker
Upgrade k8s value
except Powered down worker, all nodes get upgraded, cluster is stuck in upgrading state.
Restore to snapshot.
The cluster is stuck in upgrading. Worker nodes are not upgraded to the previous k8s version. Control and etcd can be seen in 1.15 k8s version.

**Comment by sowmyav27** [comment]
**Verified all the scenarios on laster-head - commit id: `44f73ad06`**

**Scenario#1**

- Deploy a cluster - 1 etcd, 1 control, 2 worker nodes 1.15
- Take a snapshot S1
- Upgrade k8s version to 1.16
- When the cluster comes up "Active" restore to snapshot S1
- The cluster goes to "Updating" state. And comes back Active
- Control and etcd nodes' k8s changes. 
- Worker nodes' k8s version changes to 1.15 (after sometime after cluster becomes active)

**Scenario#2**

- Deploy a cluster - 1 etcd, 1 control, 2 worker nodes 1.15.
- Take a snapshot
- upgrade max-pods value
- power down one worker node during the upgrade process.
- cluster stuck in upgrade as the max unavailable worker is hit
- restore to snapshot (etcd,k8s+config)
- Cluster comes back to Active state.
- Powered down node will be in "Unavailable" state

**Scenario#3**

- CLuster spec - 1 etcd, 2 control, 3 worker node, max Unavailable worker - 2
- take a snapshot
- power down one worker
- Upgrade k8s value
- except Powered down worker, all nodes get upgraded, cluster is stuck in upgrading state.
- Restore to snapshot.
- The cluster comes to Active state. Powered down node is stuck in "Unavailable" state.
