### ISSUE TITLE
Validate SUSE Enterprise Linux 12 SP5 with kernel version 4.12.14-122.17

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#26287]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Description:**
Validate SUSE Enterprise Linux 12 SP5 with kernel version 4.12.14-122.17

**Other details that may be helpful:**
Per this comment, https://github.com/rancher/rancher/issues/25067#issuecomment-580875741 it is only `.12` that seems to be validated with SLES 12.5

**Environment information**
- Rancher v2.3.5

**Comment by aaronRancher** [comment]
Validated with Rancher version `2.4.1`

Steps:
Launch instances with the following AMI: `ami-0d808701ac55e8ef7`
Install docker and start service
```
sudo zypper in -f docker-19.03.5_ce-98.51.1
sudo service docker start
```
Get `kernel version 4.12.14-122.17`
```
zypper in kernel-default-devel-4.12.14-122.17.1
zypper se -s Kernel-default-devel
```

Custom cluster validated with existing automation.
HA install validated with 7 nodes (3 etcd, 1 control, 3 worker)

**Comment by maggieliu** [comment]
Need to perform validation on 2.3.x

**Comment by aaronRancher** [comment]
Validated with Rancher `version 2.3.5`

Custom cluster validated with existing automation.
HA install validated with existing automation
