### ISSUE TITLE
Enable use of Azure VM Scaled Sets (vmss) for all cluster types

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#26293]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
- Create new cluster using Azure cloud provider and set cloud type to vmss

**Result:**
vmss are currently not a supported configuration option and the vmss won't be created

**Environment information**
- Rancher version: v2.3.3
- RKE version: local v1.0.0
- k8s version: local v1.16.3 ; cluster v1.15.7
- HA is enabled

**Comment by deniseschannon** [comment]
Working with rke-tools:v0.1.55
