### ISSUE TITLE
EKS lowest kubernetes version pre-selected in dropdown after creating one cluster

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#26296]
**What kind of request is this:**

**Steps to reproduce:**

1. Create a EKS cluster (select Kubernetes version 1.15)
2. After it's created go to Create EKS Cluster again
3. Check the Kubernetes version dropdown 

**Result:**

The lowest version pre-selected will be 1.13 but it will show the lowest version available in the dropdown.

If I logout and log in again and I go to EKS Create Cluster I see 1.15
If I open a new browser I see 1.15.

**Environment information**
- Rancher version: `2.4 master-head (03/26/2020)` commit id 98e2ce06d
- Installation option: single

This is also happening in `v2.3-head (03/26/2020)` commit id: e714692fc

Related issues:

https://github.com/rancher/rancher/issues/26281
https://github.com/rancher/rancher/issues/26285

**Comment by deniseschannon** [comment]
@izaac I've moved this to 2.3.6 so it's tested with both 2.3 and "master"

**Comment by izaac** [comment]
Rancher version: `v2.3-head (03/26/2020)` commit id: 991832341
Rancher version: `v2.4 master-head (03/26/2020)` commit id: 44f73ad06

Rancher is now showing the latest version in the EKS kubernetes version dropdown while in Create Cluster. Checked this and I always seen 1.15 after creating a cluster and start creating a new one for both `v2.3-head` and `master-head`
