### ISSUE TITLE
k8s version is not available sometimes in the dropdown while creating a cluster in a HA setup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26304]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Bring up a HA cluster on master-head
- Deploy a DO cluster.
- k8s version dropdown is empty
<img width="910" alt="Screen Shot 2020-03-26 at 5 36 05 PM" src="https://user-images.githubusercontent.com/26032343/77710056-3f83e580-6f8a-11ea-9989-72badcee1223.png">

- On a refresh of kubernetes metadata, the k8s version were available in the dropdown during cluster creation

**Expected Result:**
k8s version should be available in the dropdown

**Other details that may be helpful:**
Note: Not always reproducible (hit this issue 1 out of 3 ha setups on master-head)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `a195fe7c6`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by deniseschannon** [comment]
@sowmyav27 How quickly are you going to start creating clusters? I wonder if it's a timing thing?

**Comment by StrongMonkey** [comment]
@sowmyav27  if you reproduced it next time, can you share the setup? I'd like to know if version never shows up until you refresh or it is just a timing thing.

**Comment by sowmyav27** [comment]
@deniseschannon @StrongMonkey 
Logs:
```
2020/03/27 00:25:44 [INFO] Refreshing driverMetadata in 1440 minutes
2020/03/27 00:25:44 [INFO] driverMetadata: refreshing data from upstream https://releases.rancher.com/kontainer-driver-metadata/dev-v2.4/data.json
2020/03/27 00:25:45 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:42833
2020/03/27 00:25:45 [INFO] kontainerdriver googlekubernetesengine stopped
2020/03/27 00:25:45 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:44585
2020/03/27 00:25:45 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2020/03/27 00:25:45 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:42295
2020/03/27 00:25:45 [INFO] kontainerdriver azurekubernetesservice stopped
2020/03/27 00:25:45 [INFO] update kontainerdriver googlekubernetesengine
..
```
^^^ was initially when the rancher server was up
And when I manually refreshed
```
2020/03/27 00:36:13 [INFO] failed to run channelserver: signal: killed
2020/03/27 00:36:14 [INFO] driverMetadata: refreshing data from upstream https://releases.rancher.com/kontainer-driver-metadata/dev-v2.4/data.json
2020/03/27 00:37:21 [INFO] [mgmt-cluster-rbac-delete] Creating namespace c-8qb5n
2020/03/27 00:37:22 [INFO] [mgmt-cluster-rbac-delete] Creating Default project for cluster c-8qb5n
2020/03/27 00:37:22 [INFO] [mgmt-project-rbac-create] Creating namespace p-f58gh
2020/03/27 00:37:22 [INFO] [mgmt-cluster-rbac-delete] Creating System project for cluster c-8qb5n
```

**Comment by StrongMonkey** [comment]
@sowmyav27 I think this should be fixed but I couldn't reproduce it locally. If you see this again, keep the setup and let me know.

**Comment by sowmyav27** [comment]
**Verified on an upgrade from v2.2.11-rc2  to 2.4.0-rc14**
On an upgrade, the k8s version in the dropdown were available after about a minute after upgrade.

**Comment by sowmyav27** [comment]
On an upgrade to 2.4.x, the k8s version in the dropdown were available after about a minute after upgrade. This was observed in several upgrades. 
As per @StrongMonkey 's confirmation, that this slight delay is acceptable, closing the issue
