### ISSUE TITLE
Rancher restart loggers and change config back on fluentd (containerd)

### ISSUE THREAD

**Issue by hschu12** [rancher/rancher#26307]
**What kind of request is this (question/bug/enhancement/feature request):**
Question/bug:
Why does Rancher reset my fluentd config and restart loggers after 1 hour?
I am trying to get around the problem of fluentd loggers not being able to parse containerd logs due to not being in json (pattern dont match) and therefore not sending logs to Elasticsearch. Found solution but Rancher resets config and restart logs after 1 hour.

**Steps to reproduce (least amount of steps as possible):**
Rancher 2.3.5 running containerd
Enable cluster logging
Logs does not match pattern since it is not json
Change fluentd config in system/secrets source to:
` 
\<source>  
  @type  tail  
 path  /var/log/containers/*.log  
  exclude_path ["/var/log/containers/rancher-logging-fluentd*.log"]   
  pos_file  /fluentd/log/fluentd-cluster-logging.pos  
  time_format  %Y-%m-%dT%H:%M:%S.%N  
  tag  cluster.*  
  \<parse>  
    @type regexp  
    expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/  
    time_format %Y-%m-%dT%H:%M:%S.%L%z  
  \</parse>  
\</source>
</source> 
`  
(potentially change elastic document type to _doc)

Restart logs.
Logs work. After one hour Rancher resets the config and restarts the loggers. Logs dont work anymore.

**Result:**
Logs send for one hour and returns to faulty state

**Other details that may be helpful:**

**Environment information**
- Rancher version 2.3.5:
- Installation option (single install/HA): Both (test env: single, prod HA) happens on both systems

**Comment by warthur1214** [comment]
I have a same issure

**Comment by Cobra1978** [comment]
Same issue here!

**Comment by huangzixun123** [comment]
Same issue!

**Comment by KornKalle** [comment]
Got the same Problem on 2 indenpendent rancher 2.6.3-patch2 Instances.
First I ran into the problem, that the resource limits were hilariously low, which I fixed by editing the yml.

Now I have the problem that i could not figure out how to edit the rancher-logging-fluentd-app secret so that it persists.
On 1 of these instances i managed to achieve this, but I can't reproduce what I did.

**Comment by amyounis** [comment]
same here , i only want to add that i checked the Kubernetes API server audit log and i found out that the "cluster agent" is the one updating the secret back, i am not sure what triggers it though ! 
the kubelet is watching (sending watch requests) the secret too (not sure if this is normal )
