### ISSUE TITLE
Catalog Template API[Steve] - No Way To Fetch Catalog Template Data

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#26313]
Currently we have no way to fetch the catalog template default data as we do in Norman. This means we can't get the defaults for the catalog item.

**Comment by westlywright** [comment]
Norman Catalog Template Version `templateVersion` include a files collection containing the charts files base64 encoded. The UI specifically uses the `values.yaml` to get the default chart data. But we also use the other files as in the preview at the bottom of the page when launching an app.

Steve Catalog Template Version `management.cattle.io.catalogtemplateversions` does not include this data. Values is currently hard coded into the UI.

**Comment by deniseschannon** [comment]
This is no longer valid with the new catalog service in the dashboard.
