### ISSUE TITLE
Spike: Kontainer Engine V2

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#26321]
See research doc.

**Comment by rmweir** [comment]
just a note: some ke issues are due to not syncing with provider's state when update happen off of rancher. For EKS at least, this info should be easily obtained by us.

**Comment by rmweir** [comment]
https://github.com/rancher/rancher/issues/26536 
https://github.com/rancher/rancher/issues/26538
https://github.com/rancher/rancher/issues/26540

**Comment by rmweir** [comment]
https://github.com/rancher/rancher/issues/26548

**Comment by cbron** [comment]
Research phase done, splitting up into various tickets.
