### ISSUE TITLE
Rancher UI gives 404 backend when using helm chart 

### ISSUE THREAD

**Issue by MrAmbiG** [rancher/rancher#26323]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
any one of 3
`helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=rancher.amd.com \
  --set ingress.tls.source=secret

helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=rancher.amd.com
  
  
helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=rancher.amd.com \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=myemail@amd.com `

**Result:**
default backend - 404

**Other details that may be helpful:**
`kubectl get ingress -n cattle-system`    
NAME      HOSTS                  ADDRESS                       PORTS     AGE    
rancher   rancher.amd.com   ip_addr1,ip_addr2                  80, 443   48m    

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher server with helm/stable
- Installation option (single install/HA): 2 node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):metal
- Kubernetes version (use `kubectl version`):

```
1.18
```

- Docker version (use `docker version`): 

```
19.03.5
```

**Comment by superseb** [comment]
1.18 is not yet validated in either Rancher or RKE, on what kind of cluster are you installing Rancher on? Also, please include output from the troubleshooting docs here: https://rancher.com/docs/rancher/v2.x/en/troubleshooting/

**Comment by MrAmbiG** [comment]
@superseb 
k8s cluster --> RKE cluster. 
- I followed rancher's tutorial on how to install k8s using rke. The version of k8s was an automatic decision from rke. I did not specify or have not rigid requirement of any version.
- I wanted rancher server on rke cluster. So i followed rancher website's installation guide. `helm install rancher rancher-stable/rancher` as per their site. Here too the choice of version was left to helm ( latest).
Goal = Deploy 2 node rke cluster + deploy rancher server on rke cluster.

**Comment by superseb** [comment]
Please include the output of `kubectl version` and the outputs from the commands on https://rancher.com/docs/rancher/v2.x/en/troubleshooting/rancherha/

**Comment by mkay-sh** [comment]
I have the same problem with rancher 2.4 on a k3s cluster using letsencrypt and cert manager. I followed the instructions from the [current docs](https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/helm-rancher/) but used only one k3s node for testing purposes.

kubectl version:
> Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+k3s1", GitCommit:"3eee8ac3a1cf0a216c8a660571329d4bda3bdf77", GitTreeState:"clean", BuildDate:"2020-03-25T16:13:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Outputs from the troubleshooting docs:
`kubectl -n cattle-system get pods -l app=rancher -o wide`
All rancher pods are running and ready.

Rancher logs `kubectl -n cattle-system logs -l app=rancher`
```
2020/04/17 09:22:28 [INFO] APIVersion metrics.k8s.io/v1beta1 Kind NodeMetrics
2020/04/17 09:22:28 [INFO] APIVersion metrics.k8s.io/v1beta1 Kind PodMetrics
2020/04/17 09:22:30 [INFO] Handling backend connection request [10.42.0.13]
2020/04/17 09:22:31 [INFO] Watching metadata for monitoring.coreos.com/v1, Kind=Alertmanager
2020/04/17 09:22:31 [INFO] Watching metadata for monitoring.coreos.com/v1, Kind=PrometheusRule
2020/04/17 09:22:31 [INFO] Watching metadata for monitoring.coreos.com/v1, Kind=Prometheus
2020/04/17 09:22:31 [INFO] Watching metadata for monitoring.coreos.com/v1, Kind=ServiceMonitor
2020/04/17 09:22:32 [INFO] Adding peer wss://10.42.0.14/v3/connect, 10.42.0.14
2020/04/17 09:22:33 [INFO] Active TLS secret serving-cert (ver=238982) (count 6): map[field.cattle.io/projectId:local:p-qw2c7 listener.cattle.io/cn-10.42.0.12:10.42.0.12 listener.cattle.io/cn-10.42.0.13:10.42.0.13 listener.cattle.io/cn-10.42.0.14:10.42.0.14 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:f3f1a8ef843fab391f5f96e5c1158cbdd82e78a6ed9a9795a246711c31cfc1e4]
2020/04/17 09:22:35 [INFO] Handling backend connection request [10.42.0.14]
2020/04/17 09:22:32 [INFO] Creating roleBinding User u-q2e6n52uf2 Role project-member
2020/04/17 09:22:32 [INFO] Creating clusterRoleBinding for project access to global resource for subject u-q2e6n52uf2 role project-member-promoted.
2020/04/17 09:22:32 [INFO] Creating clusterRoleBinding for project access to global resource for subject u-q2e6n52uf2 role create-ns.
2020/04/17 09:22:32 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-qw2c7 to namespace=cattle-system
2020/04/17 09:22:32 [ERROR] ProjectController local/p-skfjt [system-image-upgrade-controller] failed with : upgrade cluster local system service logging failed: cluster local not ready
2020/04/17 09:22:33 [INFO] Active TLS secret serving-cert (ver=238982) (count 6): map[field.cattle.io/projectId:local:p-qw2c7 listener.cattle.io/cn-10.42.0.12:10.42.0.12 listener.cattle.io/cn-10.42.0.13:10.42.0.13 listener.cattle.io/cn-10.42.0.14:10.42.0.14 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:f3f1a8ef843fab391f5f96e5c1158cbdd82e78a6ed9a9795a246711c31cfc1e4]
2020/04/17 09:22:33 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-qw2c7 to namespace=cert-manager
2020/04/17 09:22:33 [ERROR] ProjectController local/p-qw2c7 [system-image-upgrade-controller] failed with : upgrade cluster local system service logging failed: cluster local not ready
2020/04/17 09:22:33 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-qw2c7 to namespace=kube-system
2020/04/17 09:22:33 [ERROR] NamespaceController kube-system [namespace-auth] failed with : clusterroles.rbac.authorization.k8s.io "p-qw2c7-namespaces-readonly" already exists
2020/04/17 11:56:16 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/04/17 11:56:17 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/04/17 11:56:18 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/04/17 11:56:19 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/04/17 11:56:20 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/04/17 11:56:21 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/04/17 11:56:23 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/04/17 11:56:24 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/04/17 11:56:25 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/04/17 11:56:26 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
```

Namespace events`kubectl -n cattle-system get events`
`No resources found in cattle-system namespace.`

Ingress `kubectl -n cattle-system get ingress`
```
NAME                                          HOSTS                         ADDRESS   PORTS     AGE
rancher                                       rancher.example.com  80, 443   158m
cm-acme-http-solver-vmmbk   rancher.example.com  80           158m

The ingress logs are empty. When I call the ACME validation path (rancher.example.com/.well-known/acme-challenge/REDACTED I get a 404  page not found.

**Comment by jwrascoe** [comment]
I am having the same issue on both rancher-latest/rancher & rancher-stable/rancher when trying to generate the lets encrypt cert

 **404 page rendered on at the acme challenge**

Is there any work-around?

Rancher Deployed on Ubuntu 18.04/k3s/master hosts as VM's running on vSphere 6.7

Running self signed of course works.

**Comment by ppihus** [comment]
I'm having the same issue when using `--set tls=external`

**Comment by dirkdevriendt** [comment]
Same here (I think) with Hetzner machines and k3s, dqlite, cert-manager, letsencrypt, rancher 2.4.2, all following standard documentation.
Everything comes up, but I end up with two ingresses (one for rancher on 80/443, one for the cert-manager http01 verification on 80 only).
My impression is that k3s uses traefik, cert-manager just sits next to it, doing its own ingress stuff (with a NodePort service) and rancher remains blissfully unaware of everything by assuming an nginx ingress.
Tried different ways of fixing it (e.g. with annotations like kubernetes.io/ingress.class and acme.cert-manager.io/http01-edit-in-place), but it's a bit of a rabbit hole and I haven't found my way through yet.
In the end, AFAICT, traefik just keeps showing its 404 instead of finding out about / pointing to the http01 verification.

**Comment by jwrascoe** [comment]
dirkdevriendt, would be nice if it just supported the DNS verification rather than the HTTP

I gave up and went back to a self signed for now.

**Comment by jiaqiluo** [comment]
the bug is reproduced by installing Rancher v2.4.2 in a k3s cluster (`v1.17.4+k3s1`) with using `letsEncrypt`

- following the k3s documentation to get a k3s cluster with 1 server + 1 worker
- following the Rancher documentation to install Rancher with letsEncrypt

Results:
- 404 shows when opening Rancher URL
- the following error in `cert-manager`'s pod 
```
I0427 18:01:11.825450       1 controller.go:129] cert-manager/controller/challenges "level"=0 "msg"="syncing item" "key"="cattle-system/tls-rancher-ingress-3417164082-552234085-1106219191"
I0427 18:01:11.825827       1 pod.go:58] cert-manager/controller/challenges/http01/selfCheck/http01/ensurePod "level"=0 "msg"="found one existing HTTP01 solver pod" "dnsName"="jack-ha.qa.rancher.space" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-45jlx" "related_resource_namespace"="cattle-system" "resource_kind"="Challenge" "resource_name"="tls-rancher-ingress-3417164082-552234085-1106219191" "resource_namespace"="cattle-system" "type"="http-01"
I0427 18:01:11.825892       1 service.go:43] cert-manager/controller/challenges/http01/selfCheck/http01/ensureService "level"=0 "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="jack-ha.qa.rancher.space" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-9vm7k" "related_resource_namespace"="cattle-system" "resource_kind"="Challenge" "resource_name"="tls-rancher-ingress-3417164082-552234085-1106219191" "resource_namespace"="cattle-system" "type"="http-01"
I0427 18:01:11.825950       1 ingress.go:91] cert-manager/controller/challenges/http01/selfCheck/http01/ensureIngress "level"=0 "msg"="found one existing HTTP01 solver ingress" "dnsName"="jack-ha.qa.rancher.space" "related_resource_kind"="Ingress" "related_resource_name"="cm-acme-http-solver-8dvgq" "related_resource_namespace"="cattle-system" "resource_kind"="Challenge" "resource_name"="tls-rancher-ingress-3417164082-552234085-1106219191" "resource_namespace"="cattle-system" "type"="http-01"
```

- the following error shows in the `traefik`'s pod 
```
{"level":"error","msg":"Error configuring TLS for ingress cattle-system/rancher: secret cattle-system/tls-rancher-ingress contains the following empty TLS data entries: tls.crt","time":"2020-04-27T18:09:54Z"}
```

**Comment by cjellick** [comment]
related? https://github.com/rancher/k3s/issues/1009

**Comment by cjellick** [comment]
Maybe this is causing it? https://github.com/rancher/rancher/blob/master/chart/templates/issuer-letsEncrypt.yaml#L28-L33

based on @galal-hussein comment:
okay I think i figured out the or a problem, rancher creates http solver ingress for the cert manager, however it set that into the ingress:
```
annotations:                                                        
  kubernetes.io/ingress.class: nginx                                
  nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0,::/0
```
that prevents the ingress:
```
cattle-system   cm-acme-http-solver-2mk7j 
```
to be ignored by traefik

**Comment by sangeethah** [comment]
Fix is available in `v2.4.3-rc4`

**Comment by jiaqiluo** [comment]
the fix is validated in `v2.4.3-rc4` 

Steps:
- create a k3s cluster `v1.16.3-k3s.2` with 2 server nodes
- install Rancher `v2.4.3-rc4` with letsEncryt 

```
helm install rancher rancher-latest/rancher  --version 2.4.3-rc4\
  --namespace cattle-system \
  --set hostname=my-hostname \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=my-email
```
Results: I can open Rancher in UI, the cert is issued by letsEncryt


The following Certificate Options are also validated with the same steps:
- Rancher generated
- certificates from file issued by public CA
- certificates from file issued by private CA

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.4.3-rc4`
Steps:
Create a k8s `v1.17.5` HA setup. 1 node all roles, 1 worker node.
```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=<hostname> \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=<email> --version 2.4.3-rc4
```
Results: Rancher UI is available with valid cert from Let's Encrypt

**Comment by jiaqiluo** [comment]
The fix is validated in Rancher `v2.4.3-rc4` installing in k3s `v1.17.4+k3s1`
with certs from letsEncrypt

**Comment by jmgilman** [comment]
I can confirm the above and have filed a separate bug: #27297.

**Comment by lucj** [comment]
I have the same error when running latest rancher version (2.4.8) on k3s v1.18.6+k3s1

**Comment by DeyvsonL** [comment]
Still facing this issue with Rancher 2.5

**Comment by jiaqiluo** [comment]
Hi @lucj  I cannot reproduce your error. My k3s version is newer than yours. Here is what I did:

Rancher `v2.4.8` is installed successfully on k3s `v1.18.9+k3s1` cluster( 2 master + 3 worker)

```
> k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T11:09:22Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

The command to install cert-manager
```
 helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.0.2 \
  --set installCRDs=true
```
The command to install Rancher
```
helm install rancher rancher-latest/rancher  --version 2.4.8\
  --namespace cattle-system \
  --set hostname=myhostname \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=myemail
```


```
> helm list -A
NAME        	NAMESPACE    	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
cert-manager	cert-manager 	1       	2020-10-13 14:59:43.941774 -0700 MST   	deployed	cert-manager-v1.0.2	v1.0.2
rancher     	cattle-system	1       	2020-10-13 15:02:51.694241 -0700 MST   	deployed	rancher-2.4.8      	v2.4.8
traefik     	kube-system  	1       	2020-10-13 21:53:13.584907587 +0000 UTC	deployed	traefik-1.81.0     	1.7.19
```



![screencapture-jq301-qa-rancher-space-g-clusters-2020-10-13-15_11_12](https://user-images.githubusercontent.com/6218999/95921567-5d6a3980-0d66-11eb-88e8-7fa941495d46.png)

**Comment by aaronRancher** [comment]
Was unable to reproduce this behavior with Rancher server `rancher\rancher:v2.5.0`

Steps:
Create a k8s v1.18.9 HA setup. 1 node all roles, 1 worker node. Used RKE `v1.1.9`
Installed Rancher with:
```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname= <hostname>\
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=<email> --version 2.5.0
```
Result:
Rancher UI is available
![Screen Shot 2020-10-13 at 4 01 22 PM](https://user-images.githubusercontent.com/57409052/95924932-690d2e80-0d6d-11eb-8a04-a72cca3bcf2c.png)

**Comment by lucj** [comment]
@jiaqiluo @aaronRancher Thanks a lot for the tests.
Regarding my setup I was missing the namespace in the IngressRoute (.spec.routes.services) definition. That was the reason of my 404 :(
````
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rancher
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`rancher.domain.tld`)
    kind: Rule
    services:
    - name: rancher
      namespace: cattle-system
      port: 80
  tls:
    passthrough: true
````
Everything is working fine now

**Comment by taromurao** [comment]
I installed Kubernetes cluster with RKE on RHEL VMs and followed the installation guide on https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/ with the "Rancher Generated Certificates" option. I tried a couple of things, like deleting cert-manager-webhook-ca, trying out rancher latest stream and redeploying cert-manager, but still facing probably similar problem you have. When I look into the log of cert-manager pod, I find 

```
controller.go:158] cert-manager/controller/ingress-shim "msg"="re-queuing item due to error processing" "error"="Internal error occurred: failed calling webhook \"webhook.cert-manager.io\": Post \"https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s\": context deadline exceeded" "key"="cattle-system/rancher"
```

From `kubectl -n cattle-system describe certificate` and `kubectl -n cattle-system describe issuer`, I get `No resources found in cattle-system namespace.`. Though I followed the steps and installed cert-manager.

When I was to install Rancher with Helm, I also immediately got the error

```
Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.43.45.211:443: i/o timeout
```

Any clue?
