### ISSUE TITLE
Is this image open source? rancher/plugins-docker

### ISSUE THREAD

**Issue by easonjim** [rancher/rancher#26329]
When I was using rancher pipeline, I found that this mirror could not be found in github. Is this mirror open source?
rancher/plugins-docker:18.09

**Comment by StrongMonkey** [comment]
Hi, @easonjim  I believe it is mirrored from `plugins/docker:18.09`

**Comment by easonjim** [comment]
@StrongMonkey thanks，i find it: 
https://github.com/drone-plugins/drone-docker
