### ISSUE TITLE
Master branch is missing metadata

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#2633]
When deploying a three node cluster, we are seeing that some of the containers only see /self/service/containers for two of the containers while others see three.

Reproduce:
run rancher/build-master:v0.19.2
run gluster stack from catalog.
container $${stack_name}_volume-create_2 ends up hanging waiting for all containers to come up. looking at the returned metadata it only sees 2 containers when all three containers in the service are up.

**Comment by sangeethah** [comment]
I see the same problem in my case:

I had a service with scale 1 to begin with with exposed port.
Scale up service by 1.
New host ip address was programmed in Route53.
Scaled down service.
This change was never propagated to  Route53.

The reason for this is the container_list in the metadata for this service still has 2 entries (including the container that was delete as part of scale down)

**Comment by alena1108** [comment]
Ok, went above and beyond debugging it. Definitely discovered some bugs in the way we trigger metadata/dns for service's instances, applied the fixes (PR is coming soon). But looks like there is some bug in config update framework causing items to not increment/apply under certain conditions in the following method:

```
 AbstractApplyItems.assignItems
```

When config update is triggered for more than 1 agent by the same process, ConfigUpdateRequest mixes up agent contexts, and it results in some agents not being updated.

 In my case, I have 3 hosts, and service deployed cross these hosts. Any service instance update triggers "hosts" config item update for all 3 host's agents (verified by debugging, AbstractApplyItems.assignItems is called for all agents). But only 2 of them get updated in the DB:

```
mysql> select id, name, requested_version, applied_version, agent_id from config_item_status where name='hosts';
+----+-------+-------------------+-----------------+----------+
| id | name  | requested_version | applied_version | agent_id |
+----+-------+-------------------+-----------------+----------+
| 13 | hosts |               222 |             222 |        4 |
| 35 | hosts |                27 |              27 |        5 |
| 39 | hosts |               195 |             195 |        6 |
+----+-------+-------------------+-----------------+----------+
```

agent id=5 doesn't get updates. With attached debugger, I found out that ConfigUpdateRequest for agent id=5 gets set with the request having context of agent id=6. And as agent id=6 is already updated at this point, update for agent id=5 gets skipped.

@ibuildthecloud need your help to figure out what would be the right way to fix it. This looks like a regression bug introduced some time in Nov.

**Comment by ibuildthecloud** [comment]
I most likely caused this... one sec...

**Comment by ibuildthecloud** [comment]
@alena1108 Can you try reverting https://github.com/rancher/cattle/pull/1016 and see if things are fix in the item framework.  If so, I'll find a better approach that break less things.

**Comment by alena1108** [comment]
@ibuildthecloud after reverting the commit, all started working :)

**Comment by sangeethah** [comment]
@ibuildthecloud @alena1108 , I am testing with latest build from master , I am still seeing the issue where the  container_list in the metadata for the service has the container that was removed as part of scaling down service.
