### ISSUE TITLE
External DNS (Route 53) - Allow additional option of taking a Hosted Zone ID when there are multiple hosted zone names

### ISSUE THREAD

**Issue by johnrengelman** [rancher/rancher#2635]
The configuration screen from the External DNS asks for `Hosted Zone`. But what it actually wants here is the hosted zone's name (i.e. domain name), not the Hosted Zone Id.

This is non-intuitive. The page text could be more reflective.

However, this is problematic if using the external DNS service to create entries in a Route 53 Private Zone since multiple zones can have same the domain name in this scenario.

Instead, the configuration should take the HostedZoneId, then discover the corresponding domain name from the HostedZoneRecord.

**Comment by vincent99** [comment]
This is fine as an *additional* option for the minority that have ambiguously named zones and need it..  But taking an ID *instead of* Name is awful for usability.

**Comment by alena1108** [comment]
I updated catalog item description to reflect that its hosted zone Name that has to be provided, as a part of PR: 
https://github.com/rancher/rancher-catalog/pull/34/files

**Comment by johnrengelman** [comment]
@vincent99 I'm cool with it being an additional option

**Comment by johnrengelman** [comment]
In this particular scenario it would be nice to be able to configure the naming pattern as well. Since with a private zone the Rancher environment would likely be redundant.

**Comment by cllunsford** [comment]
I ran into this today with AWS Private Hosted Zones and v0.2.1.  The External DNS service is putting the records in the Public zone, since it appears before the Private zone in the hosted zones list.  I would also be fine with an additional option to override or complement the existing zone name.

**Comment by alena1108** [comment]
Should be fixed by @janeczku

**Comment by sangeethah** [comment]
With Route53 catalog version - rancher/external-dns:v0.4.0 , we are allowed to enter values for "HostedZoneId" in additoin to "Hosted zone name" .

So we are able to program entries to a specific "Hosted zone" when there are multiple hosted zones with the same name by using the "HostedZoneId".
