### ISSUE TITLE
How do I enable CSR signing

### ISSUE THREAD

**Issue by F-liuhui** [rancher/rancher#26359]
**What kind of request is this (question/bug/enhancement/feature request):**
I created a custom (RKE)k8s cluster through rancher UI. How do I enable CSR signing

**Steps to reproduce (least amount of steps as possible):**
How do I enable CSR signing

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by jdambly-ns** [comment]
did you find a solution for this, I'm having the same issue. I can create the CSR but seems the kube controller manager is not configured to use a CA wondering how to get this working with rancher built clusters.

**Comment by missnebun** [comment]
Edit Cluster.  
Under Cluster Options select Edit as YAML
and change kube-controller: {} 
TO
   kube-controller:
      extra_args:
        cluster-signing-cert-file: /etc/kubernetes/ssl/kube-ca.pem
        cluster-signing-key-file: /etc/kubernetes/ssl/kube-ca-key.pem
