### ISSUE TITLE
Update `ingress-nginx-controller` to latest version.

### ISSUE THREAD

**Issue by twitchax** [rancher/rancher#26377]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request.

**Steps to reproduce (least amount of steps as possible):**
N/A.

**Result:**
N/A.

**Other details that may be helpful:**
The latest version on ingress-nginx, `0.30.x`, has some useful features, such as `gRPC` support.  It would be nice if you could cut a new system image for the ingress controller.  I don't mind helping, either, but the Rancher fork doesn't have a lot of information about how to update and test a new version.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5
- Installation option (single install/HA): HA

**Comment by stefanlasiewski** [comment]
We also could use a newer version.

However, I wonder if it's worthwhile sticking with the internal version within Rancher or if we should instead be using a different one from one of the Helm catalogs.

**Comment by twitchax** [comment]
@stefanlasiewski, I had some issues when using the `0.30.0` image, so it might need some of the magic sauce that the Rancher team builds into it.

**Comment by stefanlasiewski** [comment]
@twitchax Do you remember what those issues were?

**Comment by twitchax** [comment]
The issue for me was around the service accounts not working properly.

**Comment by rancher-max** [comment]
#### Validated in master-head and v2.4-head

- nginx image is deployed successfully as: rancher/nginx-ingress-controller:nginx-0.32.0-rancher1
- Ingress and standard functionality is working
- Validated in k8s 1.15.12, 1.16.10, 1.17.6, and 1.18.3
- Regular automation runs on the scaled clusters are successful
