### ISSUE TITLE
CIS Scan Does Not Work

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#26371]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1. Launch CIS Scan Level 1

**Result:**

The docker image errors out over and over again.

**Other details that may be helpful:**

```
time="2020-03-30T20:09:19Z" level=info msg="Starting server Expected Results: [{control1 rancher-kube-bench} {xxx1 rancher-kube-bench} {xxx2 rancher-kube-bench} {xxx3 rancher-kube-bench} {xxx4 rancher-kube-bench} {xxx5 rancher-kube-bench} {xxx6 rancher-kube-bench}]"

time="2020-03-30T20:09:19Z" level=info msg="Starting annotation update routine"

time="2020-03-30T20:09:19Z" level=info msg="Starting aggregation server" address=0.0.0.0 port=443

time="2020-03-30T20:09:19Z" level=info msg="Running plugin" plugin=rancher-kube-bench

time="2020-03-30T20:09:19Z" level=info msg="couldn't annotate sonobuoy pod" error="couldn't patch pod annotation: pods \"sonobuoy\" not found"

time="2020-03-30T20:09:19Z" level=info msg="Last update to annotations on exit"

time="2020-03-30T20:09:19Z" level=info msg="couldn't annotate sonobuoy pod" error="couldn't patch pod annotation: pods \"sonobuoy\" not found"

time="2020-03-30T20:09:19Z" level=error msg="error running plugins: error running plugin rancher-kube-bench: couldn't create TLS secret for daemonset plugin rancher-kube-bench: namespaces \"heptio-sonobuoy\" not found"

time="2020-03-30T20:09:20Z" level=info msg="Resources is not set explicitly implying query all resources, but skipping secrets for safety. Specify the value explicitly in Resources to gather this data."

time="2020-03-30T20:09:20Z" level=info msg="Collecting Node Configuration and Health..."

time="2020-03-30T20:09:20Z" level=info msg="Creating host results for control1 under /tmp/sonobuoy/84246d2b-d324-4a81-a2a4-2d6d7273332b/hosts/control1\n"

time="2020-03-30T20:09:20Z" level=info msg="Creating host results for xxx1 under /tmp/sonobuoy/84246d2b-d324-4a81-a2a4-2d6d7273332b/hosts/xxx1\n"

time="2020-03-30T20:09:20Z" level=info msg="Creating host results for xxx2 under /tmp/sonobuoy/84246d2b-d324-4a81-a2a4-2d6d7273332b/hosts/xxx2\n"

time="2020-03-30T20:09:20Z" level=info msg="Creating host results for xxx3 under /tmp/sonobuoy/84246d2b-d324-4a81-a2a4-2d6d7273332b/hosts/xxx3\n"

time="2020-03-30T20:09:20Z" level=info msg="Creating host results for xxx4 under /tmp/sonobuoy/84246d2b-d324-4a81-a2a4-2d6d7273332b/hosts/xxx4\n"

time="2020-03-30T20:09:20Z" level=info msg="Creating host results for xxx5 under /tmp/sonobuoy/84246d2b-d324-4a81-a2a4-2d6d7273332b/hosts/xxx5\n"

time="2020-03-30T20:09:20Z" level=info msg="Creating host results for xxx6 under /tmp/sonobuoy/84246d2b-d324-4a81-a2a4-2d6d7273332b/hosts/xxx6\n"

time="2020-03-30T20:09:20Z" level=info msg="Running cluster queries"

time="2020-03-30T20:09:21Z" level=error msg="error updating pod status: failed to get the existing status: sonobuoy namespace does not exist: namespaces \"heptio-sonobuoy\" not found"

time="2020-03-30T20:09:21Z" level=info msg="Results available at /tmp/sonobuoy/202003302009_sonobuoy_84246d2b-d324-4a81-a2a4-2d6d7273332b.tar.gz"
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.0-rc16
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ekristen** [comment]
I upgraded to 2.4.0-rc16, went to my imported cluster and which is 1.15.5 and clicked run scan. The above was the result.

**Comment by cjellick** [comment]
@ekristen can you clarify was it an imported or a custom cluster? CIS is only expected to work on RKE (custom) clusters, not imported, but if your cluster is imported, we should not have allowed it

**Comment by ekristen** [comment]
The cluster is custom. It was created with Rancher 2 and RKE. This cluster is old, it was a 1.14 at some point originally, recently upgraded to 1.15.5.

**Comment by ekristen** [comment]
If imported is not allowed does that mean Rancher 2 HA local cluster won't allow CIS to run since it's "imported" vs "custom" even though it was created with RKE?

**Comment by sowmyav27** [comment]
@ekristen Was CIS scan attempted to run on this cluster anytime before the cluster/rancher was upgraded? In rancher:2.3.x ?(through the API)

**Comment by ekristen** [comment]
No it was not.

**Comment by sowmyav27** [comment]
**Verified on an upgrade from 2.2.10 to 2.4.0-rc16**

- 2 clusters - Custom 3 node - 1 etcd, 1 control plane and 1 worker node and 1 do rke cluster - 3 node - 1 etcd, 1 control plane and 1 worker node in `rancher:v2.2.10`
- k8s version - v1.15.5
- upgrade rancher to `2.4.0-rc16`
- Run CIS scans on these cluster
- Scan is run successfully.
- No error seen

Not able to reproduce the issue

**Comment by ekristen** [comment]
I was on 2.3.x before upgrading to 2.4.0-rc16. 

The scan container gets launched into `security-scan` namespace but the logs reference `heptio-sonobuoy`

```
error updating pod status: failed to get the existing status: sonobuoy namespace does not exist: namespaces \"heptio-sonobuoy\" not found
```

**Comment by StrongMonkey** [comment]
@ekristen Not sure If the answer is clear, but is your cluster imported or custom? By custom RKE cluster I mean even if you create a cluster using rke CLI and import it into rancher, it is called imported(not custom RKE). Also does cis scan run on your other cluster?

**Comment by ekristen** [comment]
This is a custom rke created cluster NOT imported.

My other cluster is my HA rancher 2 built with rke and the UI refuses to let me run it there.

**Comment by StrongMonkey** [comment]
@ekristen I think you might be running a old version of security-scan which is causing the issue. Can you do the following:
1. Go to `global` -> `tools` -> `drivers`. Manually click on `refreshing metadata`.
2. Go to `global` -> `catalogs`. Select system-library and manually refresh. 

Or if you are running air-gapped installation, you might need to look at docs to bump those data.

**Comment by ekristen** [comment]
Oh. That’s probably it! I had forked then system charts to fix something let me reset that.

**Comment by ekristen** [comment]
What branch of system charts should it be on?

**Comment by sowmyav27** [comment]
@ekristen The branch should be `release-v2.4`.
