### ISSUE TITLE
Hardcoded values for default catalog ids for external dns and cis scan.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#26388]
Currently we have hardcoded values for  settings - `system-externaldns-catalog-id` and `system-cis-benchmark-catalog-id` which gets used when deploying GDNS provider and when running scans.

We should be able to default to the latest available system chart.

**Comment by sowmyav27** [comment]
**Verified on 2.4-head - commit id: `65b520517` and master-head - commit id: `84d937acf`**

- CIS scan runs successfully on a custom cluster
- The version of security-scan run is which is the latest in `dev-v2.4` and `dev-v2.5` branches of system charts

<img width="1295" alt="Screen Shot 2020-05-11 at 1 31 43 PM" src="https://user-images.githubusercontent.com/26032343/81608993-f9dd7980-938b-11ea-92e4-b3072fac7b0c.png">

- The global DNS - P1 use -case worked fine. And the `systemapp-test-rancher-external-dns` version is `rancher/kubernetes-external-dns:v0.6.0` which is the latest `dev-v2.4` and `dev-v2.5` branches of system charts

- `system-externaldns-catalog-id` and `system-cis-benchmark-catalog-id` are not available under `v3/settings`.
