### ISSUE TITLE
Containers disappearing from scaled service

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2639]
I have a service with a scale of 35, but only instances 15-35 are showing up in the various Rancher UI views for that service and the service is marked as "Degraded". But, if I look at the list of all containers on all hosts, I can see instances 1-14 running. The service configuration in the UI still shows a scale of 35.

If I run `rancher-compose up -d <badservice>` with a rancher-compose.xml file setting the scale to 35, the 1-14 containers suddenly reappear in the service views in the UI and the service is marked as "Active". However, some time later they disappear again.

I destroyed and recreated the service and the problem went away for a bit, but then started happening for another similarly scaled service some time later.

**Comment by vincent99** [comment]
Do you have a few hundred or more containers total?  There are weird pagination issues in the UI as you cross ~200-1000 resources, depending on the resource and what else is included with it, https://github.com/rancher/rancher/issues/1606.  I should have time to look at that after DockerCon.

**Comment by gordontyler** [comment]
I have over 1500 containers in total. Although I've seen the issue in the individual service pages as well, where there should be 35 containers displayed, but it's missing 15 containers.

**Comment by deniseschannon** [comment]
@gordontyler We've rolled out a new UI with new service views. I believe this issue was opened before the new UI. 

Are you still facing this issue in the service page?

**Comment by gordontyler** [comment]
I have not recreated a similarly sized environment since I upgraded to the new Rancher UI. I'll see if I can reproduce it.

**Comment by gordontyler** [comment]
Using Rancher v0.50.1 I've been able to create 10 services with 50 containers each and all the containers are displayed in the services' containers pages. I'll leave it running to see if the problem reoccurs.

**Comment by gordontyler** [comment]
Everything still looks good.

**Comment by gordontyler** [comment]
Still working. I'd say this is fixed.
