### ISSUE TITLE
Secret/Config mounting issues in 2.4.0

### ISSUE THREAD

**Issue by andrew-landsverk-win** [rancher/rancher#26398]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Started with Rancher HA on kubernetes (2.3.5).
2. Upgrade rancher install via Helm 3 to 2.4.0
3. "local" cluster appears to upgrade successfully, but all managed clusters start having errors mounting secrets and config maps.

**Result:**

Tons of errors, relating to all pods that mount secrets or config maps:

`MountVolume.SetUp failed for volume "cattle-credentials" : failed to sync secret cache: timed out waiting for the condition`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.0
- Installation option (single install/HA): HA

**Comment by andrew-landsverk-win** [comment]
Looks like 2.3.6 is working as intended.

**Comment by andrew-landsverk-win** [comment]
I should also note, I rolled back the 2.4.0 cluster and the issues went away, I subsequently upgraded it to 2.3.6 and everything was also fine.

**Comment by jiaqiluo** [comment]
Hi @andrew-landsverk-win, can you provide more information about the managed cluster? For example, which k8s version is it? How many etcd/control plane/worker nodes it has?

**Comment by andrew-landsverk-win** [comment]
Sure can:

It was 2 clusters, both are using the vSphere driver, both with in-tree storage. The nodes were created with 2.3.5 using Ubuntu cloud-init img. All clusters, including local, are on k8s 1.17.4.

Cluster 1:
1 - etcd+cp
4 - worker

Cluster 2:
1 - etcd+cp
3 - worker

**Comment by Oats87** [comment]
@andrew-landsverk-win were you able to excerpt full logs from the kubelets running on your nodes?

**Comment by andrew-landsverk-win** [comment]
@Oats87 I can try updating from 2.3.6 again this afternoon and grab kutelet logs. They are in the container, right?

**Comment by Oats87** [comment]
<img width="3008" alt="Screen Shot 2020-03-31 at 10 54 55 AM" src="https://user-images.githubusercontent.com/30601846/78059063-170b3b00-733e-11ea-8603-3023b5d5c2f1.png">

This may be related to: https://github.com/rancher/rancher/issues/26399

**Comment by Oats87** [comment]
Looks to be happening every 3 minutes, coincidentally, the restart loop of the Kubelet is happening every 175 seconds which is basically 3 minutes

**Comment by andrew-landsverk-win** [comment]
That's very likely, I was also seeing kublet restarts in my "events" tab.

**Comment by andrew-landsverk-win** [comment]
You don't need me to try 2.4.0 again then?

**Comment by Oats87** [comment]
You could, then if you go into the System project of each of your clusters and delete/redeploy the cattle-node-agent pods (make sure you delete the pods and not the daemonset) the problem will be resolved

**Comment by jiaqiluo** [comment]
On a Rancher single-install setup (v2.3.5 -> 2.4.0) with a Rancher-provisioned ec2 cluster (k8s 1.17, 1 etcd+control plane, 3 workers), I did not reproduce the issue about mounting secrets and config maps. 
But the cluster ran into the issue that kubelet restarts every 3 minutes, and deleting the pods under `cattle-node-agent` solves it.

**Comment by andrew-landsverk-win** [comment]
The workaround seems to have resolved the issues on 2.4.0 (kubelet restarting and secrets/configs not mounting). Thanks!

**Comment by andrew-landsverk-win** [comment]
It's also worth noting, on a brand new cluster provisioned by Rancher, you have to delete the node agents to get kubelet to stop crashing.

**Comment by andrew-landsverk-win** [comment]
This looks like it's resolved in 2.4.1! Thanks!
