### ISSUE TITLE
Dashboard returns 500 error

### ISSUE THREAD

**Issue by gregsidelinger** [rancher/rancher#26397]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Enable the Dashboard feature under RANCHER_URL/g/settings/feature-flags
* Access the Dashboard for a cluster RANCHER_URL/dashboard/c/CLUSTER_NAME

**Result:**
If something is blocking access to https://releases.rancher.com/dashboard/release-2.4/index.html you will get a 500 error.

**Other details that may be helpful:**
This is in the rancher pod logs.
2020/03/31 14:32:31 [ERROR] failed to serve UI: Get https://releases.rancher.com/dashboard/release-2.4/index.html: read tcp 10.42.5.36:38966->104.26.4.146:443: read: connection reset by peer

The connection is being reset is causes from our firewall not allowing access to https://releases.rancher.com/dashboard/release-2.4/index.html.  I will get the access opened up however the rancher UI should deal with this and not return a 500 error.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.0
- Installation option (single install/HA): HA

**Comment by superseb** [comment]
It can't be used in air gap as described in the release notes, https://github.com/rancher/rancher/issues/25550 is used to track support.

**Comment by gregsidelinger** [comment]
@superseb  Air gap not being supported is fine.  I'm working on getting the firewall rules opened up on my end to access the pages.  However I consider any time an application returns a 500 error to be bad.  Rancher should handle the case that the URL is not accessible and return something better than a 500.
