### ISSUE TITLE
The Stop/Start hint text in Service Detail Popup is not showing up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2640]
Version - Master with reskin UI

Steps:
1.  Create a stack and add a service
2.  Go to Stack detail page and select Graph view
3.  Click on Service to bring up popup
4.  Move mouse over the stop/start icon

Results:
The black hint text does not show up. Since it's on the left, you can see a little of the black > but the rest is cut off.
![image](https://cloud.githubusercontent.com/assets/11514927/11104516/704fe672-8886-11e5-9999-a3367435911a.png)

Expected:
Text should not be cut off

**Comment by vincent99** [comment]
This seems ok with the current layout

**Comment by tfiduccia** [comment]
Version - Master with latest reskin UI
Verified fixed
