### ISSUE TITLE
Zero-Downtime Upgrade process moving to drain next node without waiting for current node to be upgraded

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#26401]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

Perform zero-downtime rolling upgrade of K8s cluster (preferably with max unavailable node count of 1)

**Result:**
Observe that the process will drain and move onto draining the next node without seeing the "current" node as upgraded to the latest version of K8s

**Other details that may be helpful:**
This is bad and causes downtime, as it's possible that the workloads that are drained off the new node are going to be drained onto the old ("upgraded") node because it is the most empty in the cluster, then when the kubelet restarts it will restart all of the pods on that node which is bad.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.0
- Installation option (single install/HA): HA

Upgraded from 1.15.6 -> 1.17.4

**Comment by kinarashah** [comment]
Didn't see anything in @Oats87's setup that'd help me root cause the problem... 
I'm unable to reproduce this, will continue looking into the issue but if anyone else sees something similar, logs would be helpful!

**Comment by sowmyav27** [comment]
Saw this issue on an upgrade from 2.3.4 to 2.4.0

**Steps:**

- Bring up a cluster with k8s 1.15.11-rancher1-1 in rancher:v2.3.4
- Cluster spec: 1 etcd, 1 control and 3 worker nodes
- Upgrade rancher to v2.4.0
- Upgrade k8s version to 1.17.4-rancher1-3 (drain is disabled)
- The control and etcd nodes get upgraded
- The worker nodes are picked one by one for upgrade.
- After finishing upgrade, the k8s version for them do not change (on the UI)
- The change is slowly seen for the worker nodes, after all the nodes are upgraded, and the cluster comes to Active - one by one the k8s version upgrade to 1.17.4

**Comment by sowmyav27** [comment]
@kinarashah Reopened. Awaiting fix in master.

**Comment by sowmyav27** [comment]
**Validated on an upgrade from 2.3.5 to 2.4-head - commit id: `04159d027`**

- Deploy a cluster - 1 etcd, 1 control and 3 worker nodes - 1.15 k8s version
- Upgrade to 2.4-head.
- unmanaged agent was seen on `docker ps | grep agent`  on a worker node. This container has been started with `--only-write-certs` (seen on doing docker inspect and "cmd")
- set debug on the `k8s_agent_cattle-node-agent`
- upgrade k8s version to 1.17.3
- From the k8s agent logs and the server logs (as below), the node was marked upgraded only when the kubelet images has been changed.

**Agent logs:**
```
time="2020-04-04T17:53:49Z" level=info msg="{\"status\":\"Pull complete\",\"progressDetail\":{},\"id\":\"3559fd7e327a\"}"
time="2020-04-04T17:53:49Z" level=info msg="{\"status\":\"Digest: sha256:70487c2f23337c5fa1c0e4bba06600cae3ce2bfc998adc2e17100862fad4e6c3\"}"
time="2020-04-04T17:53:49Z" level=info msg="{\"status\":\"Status: Downloaded newer image for rancher/hyperkube:v1.17.4-rancher1\"}"
time="2020-04-04T17:53:50Z" level=info msg="For process kubelet, Image has changed from rancher/hyperkube:v1.15.11-rancher1 to rancher/hyperkube:v1.17.4-rancher1"
```

**Server logs:** - node: `m-l2bhf`
```
2020/04/04 17:53:47 [INFO] cluster [c-ztsq4] worker-upgrade: sending node-version for node [sowmya-test1-wrk-2] version 2
2020/04/04 17:53:52 [INFO] cluster [c-ztsq4] worker-upgrade: updating node [m-l2bhf] with node-version 2
2020/04/04 17:53:52 [INFO] cluster [c-ztsq4] worker-upgrade: call upgrade to reconcile for node [m-l2bhf]
2020/04/04 17:53:52 [INFO] cluster [c-ztsq4] worker-upgrade: sending node-version for node [sowmya-test1-wrk-2] version 2
2020/04/04 17:53:52 [INFO] cluster [c-ztsq4] worker-upgrade: updated node [m-l2bhf] to uncordon
```
- A slight delay in upgraded k8s version can be seen on the node, while the second worker nodes get picked for upgrade.


**Verified on an upgrade from 2.3.5 to  master-head - commit id: `e3d66b9e7`**

- Deploy a cluster - 1 etcd, 1 control and 3 worker nodes - 1.15 k8s version
- Upgrade to master-head.
- unmanaged agent was seen on `docker ps | grep agent`  on a worker node. 
- set debug on the `k8s_agent_cattle-node-agent`
- upgrade k8s version to 1.17.3
- From the k8s agent logs and the server logs (as below), the node was marked upgraded only when the kubelet images has been changed.

**Agent logs:**
```
time="2020-04-04T18:40:48Z" level=info msg="{\"status\":\"Pull complete\",\"progressDetail\":{},\"id\":\"3559fd7e327a\"}"
time="2020-04-04T18:40:48Z" level=info msg="{\"status\":\"Digest: sha256:70487c2f23337c5fa1c0e4bba06600cae3ce2bfc998adc2e17100862fad4e6c3\"}"
time="2020-04-04T18:40:48Z" level=info msg="{\"status\":\"Status: Downloaded newer image for rancher/hyperkube:v1.17.4-rancher1\"}"
time="2020-04-04T18:40:48Z" level=debug msg="Wrote ping"
time="2020-04-04T18:40:48Z" level=info msg="For process kube-proxy, Image has changed from rancher/hyperkube:v1.15.11-rancher1 to rancher/hyperkube:v1.17.4-rancher1"
```

**Server logs: (node: `m-dtm9m`)**
```
2020/04/04 18:40:26 [INFO] cluster [c-qm259] worker-upgrade: sending node-version for node [sowmya-test3-wrk-1] version 2
2020/04/04 18:40:28 [INFO] cluster [c-qm259] worker-upgrade: sending node-version for node [sowmya-test3-wrk-1] version 2
2020/04/04 18:40:32 [INFO] cluster [c-qm259] worker-upgrade: updating [sowmya-test3-wrk-3] with agent-interval [35]
2020/04/04 18:40:32 [INFO] cluster [c-qm259] worker-upgrade: call upgrade to reconcile for node [m-j5zc2]
2020/04/04 18:40:38 [INFO] cluster [c-qm259] worker-upgrade: call upgrade to reconcile for node [m-vqkkh]
2020/04/04 18:40:38 [INFO] cluster [c-qm259] worker-upgrade: updating [sowmya-test3-wrk-2] with agent-interval [35]
2020/04/04 18:40:49 [INFO] cluster [c-qm259] worker-upgrade: updating node [m-dtm9m] with node-version 2
2020/04/04 18:40:49 [INFO] cluster [c-qm259] worker-upgrade: call upgrade to reconcile for node [m-dtm9m]
2020/04/04 18:40:49 [INFO] cluster [c-qm259] worker-upgrade: sending node-version for node [sowmya-test3-wrk-1] version 2
2020/04/04 18:40:49 [INFO] cluster [c-qm259] worker-upgrade: updated node [m-dtm9m] to uncordon
```
