### ISSUE TITLE
KeyCloak Auth Provider fails handling group memberships - SAML: User does not have access

### ISSUE THREAD

**Issue by PhilipSchmid** [rancher/rancher#26404]
**What kind of request is this (question/bug/enhancement/feature request):**
question / (maybe bug)

**Steps to reproduce (least amount of steps as possible):**
Configure Rancher authentication with KeyCloak as IdP: https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/keycloak

Ensure to use the right IDP metadata as instructed here: https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/keycloak/#keycloak-6-0-0-idpssodescriptor-missing-from-options

Set up KeyCloak SAML client:
![keycloak-rancher-client](https://user-images.githubusercontent.com/5549063/78062738-69c11300-738f-11ea-86c7-b436d84f583d.png)

Adjust required KeyCloak mappers:
![keycloak-rancher-client-mappers](https://user-images.githubusercontent.com/5549063/78062814-86f5e180-738f-11ea-9284-4d260a1a8cb1.png)

Especially the `group` mapping configuration:
![keycloak-rancher-client-mappers-groups](https://user-images.githubusercontent.com/5549063/78062856-94ab6700-738f-11ea-9cc6-40215f5885d2.png)
 
and the `username` mapping:
![keycloak-rancher-client-mappers-username](https://user-images.githubusercontent.com/5549063/78062876-9d03a200-738f-11ea-850b-13836d184a05.png)

Setup KeyCloak user & group which are going to be used by Rancher:
![keycloak-rancher-groups](https://user-images.githubusercontent.com/5549063/78062962-b99fda00-738f-11ea-805d-68979014b447.png)
![keycloak-rancher-admins-members](https://user-images.githubusercontent.com/5549063/78062970-bc9aca80-738f-11ea-8ec2-b39c5c2d91ef.png)

Next, switch to the Rancher UI and set up the KeyCloak IdP connection:
![rancher-keycloak-configuration](https://user-images.githubusercontent.com/5549063/78063050-dfc57a00-738f-11ea-8ac2-0023dc7a7312.png)

Test the authentication and permit the `rancher-admins` group to login to Rancher:
![rancher-allowed-groups](https://user-images.githubusercontent.com/5549063/78063115-f370e080-738f-11ea-87bd-525282a46ed4.png)

Finally, test the login.

**Result:**
The login for the test user `pschmid` (which is member of the `rancher-admins` group) fails:
![failed-keycloak-login](https://user-images.githubusercontent.com/5549063/78063132-fe2b7580-738f-11ea-94c2-2af1f58cd893.png)

The Rancher log prints:
```bash
rancher_1  | 2020/03/31 18:09:33 [ERROR] SAML: User does not have access <nil>
```

... even though Rancher should have received the correct group membership during the login (trace output from KeyCloak):
```bash
<saml:Attribute FriendlyName="givenName" Name="urn:oid:2.5.4.42" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
    <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">Philip</saml:AttributeValue>
</saml:Attribute>
<saml:Attribute FriendlyName="surname" Name="urn:oid:2.5.4.4" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
    <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">Schmid</saml:AttributeValue>
</saml:Attribute>
<saml:Attribute Name="member" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
    <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">rancher-admins</saml:AttributeValue>
</saml:Attribute>
<saml:Attribute FriendlyName="email" Name="urn:oid:1.2.840.113549.1.9.1" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
    <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">pschmid@example.com</saml:AttributeValue>
</saml:Attribute>
<saml:Attribute Name="uid" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
    <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">pschmid</saml:AttributeValue>
</saml:Attribute>
```

The Rancher login for the KeyCloak `admin` user works - but this user is also separately listed as "Authorized User". Is it not possible to directly use KeyCloak groups as "Site Access Authorized Group/Organization"? Unfortunately I can't find any documentation about how to grant Rancher access to a all members of a KeyCloak group.

**Other details that may be helpful:**
KeyCloak version: jboss/keycloak:9.0.0

https://github.com/rancher/rancher/issues/16539 helped me to set up the group mappers but it's still not working...

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.4.0
- Installation option (single install/HA): Single install

**Comment by izaac** [comment]
Hi @PhilipSchmid  I see by checking the screenshots that the `rancher-admins` was added as user (notice the `User` type below the `rancher-admins` in the Site Access screen), was it added from the text field or from the dropdown ?

There's a note in the docs that state:

> When adding groups, you must select the group from the drop-down that is next to the text box. Rancher assumes that any input from the text box is a user.

> The group drop-down shows only the groups that you are a member of. You will not be able to add groups that you are not a member of.

In the SAML Provider Caveats note here: https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/keycloak/

Could you try using the dropdown arrow to the right of that input field? The user adding the group must be part of the group you're adding.

**Comment by PhilipSchmid** [comment]
Hi @izaac 
Oh wow.. nice one. That fixed the problem. Now it works:

![rancher-allowed-groups-fixed](https://user-images.githubusercontent.com/5549063/78068690-1eabfd80-7399-11ea-8d6c-ff7afbdadfbe.png)

Thanks!

Regards,
Philip

**Comment by PhilipSchmid** [comment]
If someone is interested in a step-by-step guide about how to set up the whole Rancher v2.x KeyCloak IdP authentication: https://gist.github.com/PhilipSchmid/506b33cd74ddef4064d30fba50635c5b

**Comment by Rafisto** [comment]
Hello, I recently came across this issue and realised that @izaac's response does not fully express what Rancher can in fact do. Let's tackle this statement:

> The group drop-down shows only the groups that you are a member of. You will not be able to add groups that you are not a member of.

This is true, there is no way to do it in the UI. However, you can in fact add groups that you are not a member of via the API.

The easiest way is to run the following manifest (`kubectl apply -f`) in rancher local cluster:

```yaml
apiVersion: management.cattle.io/v3
kind: GlobalRoleBinding
metadata:
  name: grb-forged-group
globalRoleName: admin
groupPrincipalName: keycloak_group://<your-saml-mapped-group>
```

It can also be created for KeyCloak OIDC provider - change `keycloak_group` to `keycloakoidc_group`:

```yaml
apiVersion: management.cattle.io/v3
kind: GlobalRoleBinding
metadata:
  name: grb-forged-group
globalRoleName: admin
groupPrincipalName: keycloakoidc_group://<your-oidc-mapped-group>
```

This is in fact what the UI does when adding a group you're a member of.
**There is a caveat though** - you may not be able to see the group in the UI, and that happens when:
- Querying a group you're a member of - yields HTTP 200 in Users & Authentication > Groups
- Querying a group you're not a member of - yields HTTP 403 in Users & Authentication > Groups

We have confirmed that adding `admin` role to the specific group allows its member to query the UI normally and actually see the created group, whereas local administrator is unable to do so.

This ends the issue for my use case.
If someone is willing to further investigate why HTTP 403 occurs I have also checked and verified that the manifest above creates two another records in the form of: 

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: forged-group-binding
  labels:
    authz.management.cattle.io/globalrolebinding: 'true'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cattle-globalrole-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: keycloak_group://<your-saml-mapped-group>
```

Which singularly work as well, but this approach under no circumstance is to be seen in the UI.
