### ISSUE TITLE
[UI] K3s clusters show etcd specifics labels when not applicable

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#26402]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. import k3s cluster
2. go to cluster view page

**Result:**
shows "Etcd" in green box to indicate it is healthy

**Desired:**
don't show it for k3s clusters

**Comment by rmweir** [comment]
It looks like if no component matching the label is found (in this case "etcd") we display it as healthy.

Support suggested we just make the label more general.

**Comment by deniseschannon** [comment]
@westlywright Not sure how easy this is to update this. Let me know if there is a way to make this grey or disabled.

**Comment by westlywright** [comment]
@deniseschannon I am just going to hide the status box and extend the other boxes to fill the space if we don't have an etcd status and its a k3s imported cluster. Are you okay with that?

**Comment by deniseschannon** [comment]
@westlywright that's fine, but it's weird why we don't do something like that for AKS, which has 2 of the 4 boxes that aren't valid.

**Comment by westlywright** [comment]
@deniseschannon Do we want to add it while I am in here? Is there good reason to show them as greyed out rather then hide them all together?

**Comment by deniseschannon** [comment]
I have no good reason to grey them out (aka disable them) if it's not valid. I'd only worry about when you switch between clusters and how that looks. Someone might ask, why those don't show up, but maybe not.

**Comment by aaronRancher** [comment]
This is reproduced with Rancher server `rancher\rancher:v2.4.2`
Steps:
Import a k3s cluster
View cluster
Result:
![Screen Shot 2020-04-09 at 5 44 13 PM](https://user-images.githubusercontent.com/57409052/78952509-ac1eda00-7a8a-11ea-8d1d-7ac8b856ccf9.png)

The feature is verified with Rancher server `rancher\rancher:master-head` `version 03947c351` and `rancher\rancher:v2.4-head` `version 03947c351`
Etcd is greyed out:
![Screen Shot 2020-04-09 at 5 44 32 PM](https://user-images.githubusercontent.com/57409052/78952634-1e8fba00-7a8b-11ea-9968-c18a7b0775c3.png)
