### ISSUE TITLE
Support for k8s 1.15.11, 1.14.10  in v2.2.x

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#26410]

**Comment by sangeethah** [comment]
Deployed cluster with k8s version - 1.15.11 and 1.14.10 with following configurations:
2 control
3 etcd
3 workers

Existing automation runs succeeded.

**Comment by deniseschannon** [comment]
All networking providers need to be validated in 2.2.x. The current template doesn't work for Calico.

**Comment by sangeethah** [comment]
Tested with rancher server version - 2.2.11-rc4
Deployed cluster with k8s version - 1.15.11 and 1.14.10 with following configurations:
2 control
3 etcd
3 workers
Existing automation runs succeeded for Canal network.

Able to deploy clusters (1 control , 1 etcd , 2 workers) successfully using all the following networks on k8s versions -1.15.11,14.10 and 1.13.12:
Canal
Flannel
Weave
 Calico

Basic checks for workload deployment , ingress and fqdn checks succeed.
