### ISSUE TITLE
share_mnt not upgraded when upgrading rancher server from v2.4.0

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#26417]
Rancher server version - v2.4.0

Steps to reproduce the problem:

Fresh install of v2.4.0 ( or upgraded from any 2.3.x)
Create a RKE cluster ( or it can be an existing cluster from previous rancher server version).
Upgrade to 2.4.2-rc2.

After rancher server gets upgraded , notice that the `cattle-cluster-agent` and `cattle-node-agent` get upgraded successfully to `rancher/rancher-agent:v2.4.1-rc2` but `share-mnt` fails to upgrade.

```
docker ps -a | grep agent
7731efa05499        rancher/rancher-agent                             "run.sh"                 16 minutes ago      Up 16 minutes                                   k8s_agent_cattle-node-agent-bxsn5_cattle-system_58726ef0-470b-4c80-8783-c19734eb6fdf_0
bcdf88d20f22        rancher/pause:3.1                                 "/pause"                 17 minutes ago      Up 17 minutes                                   k8s_POD_cattle-node-agent-bxsn5_cattle-system_58726ef0-470b-4c80-8783-c19734eb6fdf_0
f41d19c329ab        rancher/rancher-agent:v2.4.0                      "run.sh -- share-roo…"   26 minutes ago      Exited (0) 26 minutes ago                       share-mnt
```

**Comment by deniseschannon** [comment]
Will be addressed by dropping share-mnt and update the logic to no longer rely on it: https://github.com/rancher/rancher/issues/25702

**Comment by deniseschannon** [comment]
This only affects clusters that are being upgraded from v2.4.0 and will get upgraded when the cluster upgrades to a new k8s version

**Comment by bmdepesa** [comment]
rancher/rancher:master-head bcc8261

* We are not doing any cleanup on this container
* Tested via resolution of #25702
