### ISSUE TITLE
Helm chart repos 404- can't install rancher

### ISSUE THREAD

**Issue by mrteenageparker** [rancher/rancher#26414]
When I try to install using any of the repos - it fails to download, and when visiting them directly - it's because they don't exist:

https://releases.rancher.com/server-charts/latest
https://releases.rancher.com/server-charts/stable
https://releases.rancher.com/server-charts/alpha

**Comment by superseb** [comment]
It will look for `index.yaml` at the given locations, please supply the output of `curl -v https://releases.rancher.com/server-charts/stable/index.yaml` and the actual error from Helm.

**Comment by mrteenageparker** [comment]
It definitely seems like the file exists - apologies not very familiar with Helm.

However, the error from helm is:

    username@machine project % helm install rancher rancher-stable/rancher --namespace default --kubeconfig --set hostname=rancher.machine  --kubeconfig $HOME/multipass-mount/k3s.yaml --generate-name
    Error: failed to download "rancher" (hint: running `helm repo update` may help)

**Comment by mrteenageparker** [comment]
I also just realized maybe I shouldn't do this stuff late at night - it seems like it was my fault. Apologies for potentially causing any disruptions.

Helm potentially could be clearer on the error messages, as the mistake was i had two --kubeconfig arguments.
