### ISSUE TITLE
No host was added for health monitoring for some instances of a service resulting in health_state not reflecting unhealthy state of the instance.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2642]
Server version - Build from master

Set up - 2 hosts - host1 and host2

Have all instances of health check enabled service with scale- 24 running on host1.
Bring down host1 , so that all instances get migrated to host2.

When host1 is still in "reconnecting" state , bring down host2.
Once host2 gets to "reconnecting" state , bring up host1.

Only 12 instances (out of 24) get migrated to host1. The rest of the instances continue to be shown as being in "healthy" state since there is no host being added to monitor their health.  

```
mysql> select id, state ,health_state, name, created from instance where state="running" and name like "%yello123%";
+-----+---------+--------------+---------------------+---------------------+
| id  | state   | health_state | name                | created             |
+-----+---------+--------------+---------------------+---------------------+
| 490 | running | healthy      | Default_yello123_10 | 2015-11-12 00:30:31 |
| 491 | running | healthy      | Default_yello123_11 | 2015-11-12 00:30:31 |
| 492 | running | healthy      | Default_yello123_5  | 2015-11-12 00:30:38 |
| 493 | running | healthy      | Default_yello123_6  | 2015-11-12 00:30:38 |
| 494 | running | healthy      | Default_yello123_14 | 2015-11-12 00:30:38 |
| 495 | running | healthy      | Default_yello123_20 | 2015-11-12 00:30:38 |
| 496 | running | healthy      | Default_yello123_23 | 2015-11-12 00:30:38 |
| 497 | running | healthy      | Default_yello123_24 | 2015-11-12 00:30:39 |
| 498 | running | healthy      | Default_yello123_25 | 2015-11-12 00:30:39 |
| 499 | running | healthy      | Default_yello123_26 | 2015-11-12 00:30:39 |
| 500 | running | healthy      | Default_yello123_27 | 2015-11-12 00:30:40 |
| 501 | running | healthy      | Default_yello123_1  | 2015-11-12 00:31:10 |
| 511 | running | healthy      | Default_yello123_7  | 2015-11-12 00:35:23 |
| 512 | running | healthy      | Default_yello123_9  | 2015-11-12 00:35:35 |
| 513 | running | healthy      | Default_yello123_16 | 2015-11-12 00:35:35 |
| 514 | running | healthy      | Default_yello123_17 | 2015-11-12 00:35:35 |
| 515 | running | healthy      | Default_yello123_18 | 2015-11-12 00:35:35 |
| 516 | running | healthy      | Default_yello123_19 | 2015-11-12 00:35:35 |
| 517 | running | healthy      | Default_yello123_28 | 2015-11-12 00:35:35 |
| 518 | running | healthy      | Default_yello123_29 | 2015-11-12 00:35:36 |
| 519 | running | healthy      | Default_yello123_30 | 2015-11-12 00:35:36 |
| 520 | running | healthy      | Default_yello123_31 | 2015-11-12 00:35:36 |
| 521 | running | healthy      | Default_yello123_32 | 2015-11-12 00:35:37 |
| 522 | running | healthy      | Default_yello123_33 | 2015-11-12 00:35:37 |
+-----+---------+--------------+---------------------+---------------------+
24 rows in set (0.00 sec)


mysql> select health_state, host_id,state from healthcheck_instance_host_map where healthcheck_instance_id in (select id from healthcheck_instance where instance_id=490);
+--------------+---------+---------+
| health_state | host_id | state   |
+--------------+---------+---------+
| healthy      |       7 | removed |
+--------------+---------+---------+
1 row in set (0.00 sec)

mysql> select health_state, host_id,state from healthcheck_instance_host_map where healthcheck_instance_id in (select id from healthcheck_instance where instance_id=491);
+--------------+---------+---------+
| health_state | host_id | state   |
+--------------+---------+---------+
| healthy      |       7 | removed |
+--------------+---------+---------+
1 row in set (0.00 sec)

```

**Comment by sangeethah** [comment]
This issue is also reproducible with services using smaller scale like 5. 3 of the 5 instances get migrated to the host that is up . But 2 of them continue to be in the host that is down since they do not have any host monitoring them.

**Comment by alena1108** [comment]
@sangeethah its possible that even with the fix, there would be a race condition when healtcheck map gets removed from host1 going down, while host2 is coming up, but not fully up yet, and there are no other hosts in the system. Unfortunately, the fix won't be trivial, have to think about it.

**Comment by sangeethah** [comment]
yes , I am able to reproduce this issue with the latest build from master. Reopening this issue for now.

**Comment by alena1108** [comment]
Race condition bug, moving the target to the future.

**Comment by soumyalj** [comment]
Created a Kubernetes setup with 3 hosts. Turned off all 3 hosts and brought back one host after around 5 mins. The etcds on hosts in reconnecting state are still running. They are not marked un-healthy.

**Comment by alena1108** [comment]
Should be fixed with:

```
commit 5901fe787de9d4d3d10ec8658e3502dfafee38a9
Author: Alena Prokharchyk <alena@rancher.com>
Date:   Tue Oct 18 14:46:14 2016 -0700

    new state transition between agent.reconnecting and agent.active
```

**Comment by deniseschannon** [comment]
Note: This is in 1.2 and can be tested with 1.2.

**Comment by sangeethah** [comment]
Tested with racher-server version - v1.2.0

I am still able to reproduce this issue where instances in a host that is in "Disconnected" state continues to be in "healthy" state and so it does not get migrated to "Active" hosts.

Following are steps I have done:

Set up with 3 hosts.
Had 5 health check enabled instances running on them.
Brought down 2 hosts( h1 and h3) , so that all the instances now got migrated to 1 remaining healthy host - h2.

Power on h1 and h2. While they are still in the process of getting powered on , power down h3 where all the 5 instances are running.

These 5 instance now continue to be in "healthy" state in the host even after it went from "Active"->"Reconnecting"->"Disconnected" state.

<img width="1026" alt="screen shot 2016-12-09 at 5 42 28 pm" src="https://cloud.githubusercontent.com/assets/4266958/21070220/e016ced0-be36-11e6-91db-c3256f3ca3c5.png">

Containers are still in "healthy" state

```
"healthState": "healthy",
```
```
"healthcheckStates": [ 2 items
{
"hostId": "1h1",
"healthState": "initializing"
},
{
"hostId": "1h3",
"healthState": "initializing"
}
]
}
```

**Comment by sangeethah** [comment]
In this case , even scheduler container which is in the "Disconnected" host is marked healthy.
Any contianer deployment is now stuck in "starting" state with error -  ```Activating (Waiting: allocated [container:1i42])```

**Comment by alena1108** [comment]
@sangeethah in that setup, disconnected host was removed from the list of health checkers. And the new hosts were added - which is correct. But by some reason, the health check containers weren't started on the reconnected hosts, so they can't report the "unhealthy" health check. 

So this original issue is resolved. But we have to figure out why health check containers failed to start

**Comment by alena1108** [comment]
@cjellick running into an interesting issue here:

1) all hosts in the system are going down 
2) "scheduler" container is left on disconnected host as all its health checkers are also on disconnected hosts, so there is noone to report the health is left around.
3) bring new host to the system, or bring one of the old hosts back up (not the one where scheduler is running).
4) Healthcheck system container fails to allocate on this host - and any new container fails to start too - as scheduler is in still on disconnected host, and there is noone to report it as unhealthy.

Thinking about the fix, couple of solutions come to mind, let me know what you think.

1) Skip system containers (with isSystem=true) from being processed by scheduler
2) In the place where we try to reach the scheduler during the container.allocate, check the state of the host where scheduler container resides. If host is in disconnected state, skip the call.

Honestly, I'm not a big fun of either solution, so really need your input on this one

**Comment by cjellick** [comment]
@ibuildthecloud has observed something similar. he wanted to build a priority event queue for important containers.

I'll think on this for a bit
