### ISSUE TITLE
Wrong PODs count in dashboard (KOPS imported cluster)

### ISSUE THREAD

**Issue by cecampossilva** [rancher/rancher#26420]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
Import any kops created cluster into rancher

**Result:**
In the initial dashboard, rancher UI counts all available pods, including the master nodes pods (with noschedule)

**Environment information**
Rancher 2.3.5 single install

**Comment by ibuildthecloud** [comment]
The dashboard defaults to all "User Namespaces" which excludes system namespaces (kube-system, etc).  If you click the namespace filter in top of the UI you can choose "All namespaces" to see everything.  Is this the issue are you seeing?

**Comment by cecampossilva** [comment]
My problem is with the dashboard counter graph at right side of the screen. All the PODs (including the master nodes) are counted.
