### ISSUE TITLE
Additional fields needed for catalog templates

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#2643]
Templates in the Catalog could contain following additional entries in config.yml file:
Changes to support:
1) Support these additional fields in config.yml [maintainer, license, projectURL] 
2) readme.md file under each template, a link will be provided in the response
3) output section in .catalog section of templates:
.catalog:
  output:
     url:

**Comment by prachidamle** [comment]
Submitted PR to fix this. https://github.com/rancher/rancher-catalog-service/pull/16

**Comment by prachidamle** [comment]
PR merged, resolving

**Comment by prachidamle** [comment]
@cloudnautique Catalog templates can contain these additional fields now. When we need them, please add to the rancher Catalog.

**Comment by deniseschannon** [comment]
projectURL is in the backend but missing from the UI: https://github.com/rancher/rancher/issues/3897

Output is yet to be implemented into Rancher, but available in the catalog-service. https://github.com/rancher/rancher/issues/3898
