### ISSUE TITLE
Unable to add any alert rules to System Project with misleading "if you want to use metric alert, need to enable monitoring for project" error

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#26446]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

If you attempt to add any alert rule to the System Project and click 'Save' you receive the error "if you want to use metric alert, need to enable monitoring for project c-mwmjd:p-mhmv8" due to the pre-existing "Memory usage close to the quota" expression configured. This error is misleading as you cannot enable Project monitoring for the System project, and also prevents you from adding any other alert rules. The message should be updated to clarify how a user can add alerts for System project.

Related to https://github.com/rancher/rancher/issues/26249

**Environment information**
- Rancher v2.4.2
```


gz#9106

**Comment by izaac** [comment]
I was able to reproduce with the following steps in v2.4.2:

1. Create Cluster
2. Go to System Project in Cluster and navigate to Tools -> Alerts
3. Clone the `Memory usage close to the quota` existing alert.
4. Put a name and click Save

![screencapture-96-126-103-245-p-c-zcf2q-p-lhtp8-alerts-p-lhtp8-projectalert-workload-alert-rule-add-2020-04-02-10_22_12](https://user-images.githubusercontent.com/27659/78279092-e0632b00-74cb-11ea-903f-1a3a8372e5af.png)

This screenshot also shows the #26249 issue.

But I can add other Alerts not using expressions as targets, like Pod and Workload targets.

**Comment by anouarchattouna** [comment]
Reproduced when creating an alert rule of type **metricRule** 
Rancher **v2.3.2**
* Request
```
curl -X POST '${RANCHER_URL}/v3/clusterAlertRules' \
-H 'Authorization: Bearer ${RANCHER_TOKEN}' \
-H 'Content-Type: application/json' \
--data-raw '{
  "clusterId": "c-qr45q",
  "groupId": "c-qr45q:cag-c26qw",
  "metricRule": {
    "comparison": "greater-than",
    "description": "The cpu load is higher than 70",
    "duration": "3m",
    "expression": "sum(node_load1) by (node) / sum(machine_cpu_cores) by (node) * 100",
    "threshold_value": 70
  },
  "name": "test-metric-rule",
  "severity": "critical"
}'
```
* Response : 500 Internal Server Error
```json
{
    "baseType": "error",
    "code": "ServerError",
    "message": "if you want to use metric alert, need to enable monitoring for cluster c-qr45q",
    "status": 500,
    "type": "error"
}
```

**Comment by izaac** [comment]
Alert Manager v1 is no longer supported
