### ISSUE TITLE
Upgrade K3OS cluster fails

### ISSUE THREAD

**Issue by DarrenRatcliffe** [rancher/rancher#26448]
**What kind of request is this (question/bug/enhancement/feature request):**
Question / Bug?

**Steps to reproduce (least amount of steps as possible):**
In Rancher 2.4.2 edit imported K3OS cluster (K3OS v0.9.1) pick latest release and save

**Result:**
system upgrade controller deploys but fails

Rancher server stuck in 'Cluster is being upgraded'

controller container log output:

`W0402 15:40:10.608696       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-04-02T15:40:10Z" level=fatal msg="Error starting: namespaces \"kube-system\" is forbidden: User \"system:serviceaccount:cattle-system:system-upgrade\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"kube-system\""`

**Other details that may be helpful:**

**Environment information**
- Rancher version: v2.4.2
- Installation option: single install
- K3OS: v0.9.1
- K3S: v1.17.2+k3s1

**Comment by sangeethah** [comment]
Able to upgrade a imported K3s cluster on version `v1.0.1` to `v1.17.4+k3s1` successfully using rancher server version - `v2.4.2`.

**Comment by cjellick** [comment]
We'll have to clarify this in our docs and possibly prevent it at the API level, but the integrated upgrades are not intended for k3os, just k3s installed into vanilla linux os like ubuntu (currently the only officially supported os for k3s).

We haven't focused on a k3os integration because that is still very much a non-produciotn/non-GA project.

**Comment by DarrenRatcliffe** [comment]
> We'll have to clarify this in our docs and possibly prevent it at the API level, but the integrated upgrades are not intended for k3os, just k3s installed into vanilla linux os like ubuntu (currently the only officially supported os for k3s).
> 
> We haven't focused on a k3os integration because that is still very much a non-produciotn/non-GA project.

Ah OK, I figured if it worked for K3S then by default it should work for K3OS

**Comment by DarrenRatcliffe** [comment]
I just went back and checked the K3OS github docs and in the automatic upgrade section it specifically states using the Rancher/system-upgrade-controller https://github.com/rancher/k3os to upgrade K3OS?

**Comment by cjellick** [comment]
Right. So system-upgrade-controller is a generic framework. It doesn't contain the upgrade media or the specific upgrade logic. That is handled by specific implementations. For what we've integrated into rancher, we just have the normal (non-k3os) upgrade media: https://github.com/rancher/k3s-upgrade

You can definitely use system-upgrade-controller to upgrade k3os, but its not integrated into Rancher. I'll let @dweomer give you the details on how to use it in k3os.

@dweomer can you point him in the right direction?

**Comment by dweomer** [comment]
Hi @DarrenRatcliffe,

The system-upgrade-controller is deployed with k3OS with an upgrade plan called `k3os-latest` which, by default, polls https://github.com/rancher/k3os/releases/latest every 15 minutes for the latest release tag (which excludes pre-releases) and use that tag as the "latest version" for driving application(s) of the plan. This plan will only be applied to k3OS nodes that have the `plan.upgrade.cattle.io/k3os-latest` label with any value other than `disabled`. If you need more control over when and what gets upgraded I encourage you to create your own plan using `k3os-latest` as a template.

Upgrading k3OS is monolithic in that the user-space, k3s, and (depending on arch) the kernel are bundled together in a single image, e.g. [rancher/k3os:v0.9.1](https://hub.docker.com/layers/rancher/k3os/v0.9.1/images/sha256-d90df3661f1f74b909be270aae79f3a3baa02f8df387b3528436e664454d016d) used as installation media by the `k3os-latest` upgrade **Plan**. The rancher/rancher orchestrated upgrades of k3s are currently hard-coded to use `rancher/k3s-upgrade` images for upgrade media and logic which are not aware of the unique nature of the k3s installation in k3OS.

So, you can still upgrade your k3OS nodes but you will have to do it outside of the Rancher UX.

**Comment by DarrenRatcliffe** [comment]
Thanks, does anyone have any tips on how to take the K3OS cluster UI in Rancher out of reporting that an upgrade is in progress when it will never complete?

**Comment by cjellick** [comment]
We should disable upgrade functionality for imported K3OS clusters. @deniseschannon @maggieliu i put this into v2.4.3, but that's negotiable. It's not a complete blocker, but i would like to prevent other users from running into this in the future.

**Comment by daxmc99** [comment]
@DarrenRatcliffe You will need to edit the cluster object directly to set the value of the Kubernetes version inside k3s config. `kubectl get cluster $yourK3sCluster -o=jsonpath="{.spec.k3sConfig.kubernetesVersion}"`

**Comment by daxmc99** [comment]
To test this, ensure the k3os cluster comes as k3os ( a cluster with as much as one node is considered a k3os cluster). This cluster should have feature parity with an imported cluster.

This fix _does not_ provide for the ability to upgrade k3os clusters.

**Comment by ShylajaDevadiga** [comment]
Issue was reproducible on Environment. Provider was k3s with option to upgrade cluster.
Rancher version: v2.4.2
Installation option: single install
K3OS: v0.9.1
K3S: v1.17.2+k3s1
![image](https://user-images.githubusercontent.com/56045581/79292195-6052a300-7e85-11ea-87fc-71a9b8d701c7.png)

Verified issue is fixed using Rancher 2.4-head as well as master-2751-head, Provider was k3os and no upgrade option was available.
Installation option: single install
K3OS: v0.9.1
K3S: v1.17.2+k3s1

![image](https://user-images.githubusercontent.com/56045581/79292406-ea027080-7e85-11ea-8a89-16205857650a.png)

![image](https://user-images.githubusercontent.com/56045581/79292428-f4246f00-7e85-11ea-9502-0bc65202da8a.png)

![image](https://user-images.githubusercontent.com/56045581/79292448-fe466d80-7e85-11ea-93f7-ff9907b25170.png)

![image](https://user-images.githubusercontent.com/56045581/79292461-069ea880-7e86-11ea-9ec9-14a7040e53b8.png)
