### ISSUE TITLE
No CIS Scan profiles available

### ISSUE THREAD

**Issue by nicolasmaier** [rancher/rancher#26445]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
case 1: on cluster level -> tools -> CIS Scan -> Run Scan -> Choose a profile
case 2: Edit Cluster -> Scheduled CIS Scan -> Scheduled CIS Scan Profile

**Result:**
--> the Dropdown is empty in both cases

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): vm
- Kubernetes version (use `kubectl version`): 1.16.8

- Docker version (use `docker version`): 18.9.2

**Comment by sowmyav27** [comment]
On a fresh install of `rancher:2.4.2` verified "Profiles" for CIS scan were available for a custom RKE cluster.

- Cluster --> Tools --> CIS scans --> Run scans
<img width="1293" alt="Screen Shot 2020-04-02 at 9 23 09 AM" src="https://user-images.githubusercontent.com/26032343/78273463-b4dc4280-74c3-11ea-9abc-57def713b161.png">

- Cluster --> Options --> Run CIS scan
<img width="1276" alt="Screen Shot 2020-04-02 at 9 22 35 AM" src="https://user-images.githubusercontent.com/26032343/78273467-b60d6f80-74c3-11ea-85a8-57f1bc1454df.png">

**Comment by sowmyav27** [comment]
@nicolasmaier Could you give us more details - What role do you have on the cluster?

**Comment by nicolasmaier** [comment]
@sowmyav27 I have the role "Cluster Owner", the installation was upgraded from version 2.3.5.

**Comment by sowmyav27** [comment]
@nicolasmaier I think it might be related to this -- https://github.com/rancher/rancher/issues/26441#issuecomment-607976048
Was a "CIS Scan run" performed after some time (not right after your upgrade) on the cluster?

**Comment by nicolasmaier** [comment]
@sowmyav27 
Not sure if I'm understanding you correct, but I never ran a CIS scan.
I'm not able to do that, since I don't see any profiles in the dropdown (which is this issue about).

**Comment by sowmyav27** [comment]
@nicolasmaier There might be a slight delay in upgraded rancher server getting the CIS Scan "Profile" info from KDM. If you attempted to run the scan after about 5 minutes post rancher server upgrade on the SAME cluster, do you happen to see the "Profiles" in the dropdown? If you still do not see it, could you manually refresh the KDM by navigating to Global --> Tools --> Drivers --> Refresh Kubernetes Metadata ?

**Comment by nicolasmaier** [comment]
@sowmyav27 
I see no profiles after waiting 5min.
I also tried to refresh the kdm manually, still no profiles available.

**Comment by loganhz** [comment]
Same issue here.

`/v3/cisconfigs`  returns empty array.

The data is from `rke-metadata-config` in your settings.

In 2.4, the download url for metadata is `https://releases.rancher.com/kontainer-driver-metadata/release-v2.4/data.json`. You can find more info via `https://rancher.com/docs/rancher/v2.x/en/admin-settings/k8s-metadata/`

You can try to click `Global -> Tools -> Driver -> Refresh Kubernetes Metadata` to force update the metadata.

But I hit another issue when I try to refresh the metadata via UI. The error message is following:

```
failed to refresh failed to create or update driverMetadata: driverMetadata: unable to find default k8s version in current k8s v1.17.x [v1.14.9-rancher1-1 v1.15.6-rancher1-2 v1.16.3-rancher1-1]
```

![image](https://user-images.githubusercontent.com/21168270/79180851-8d7b6300-7e3d-11ea-9e45-c84d7e8fbd92.png)

I found we have configured `/v3/settings/k8s-versions-current` before for some reason. So we need to revert it to default value manually by removing the value input.

![image](https://user-images.githubusercontent.com/21168270/79180967-dfbc8400-7e3d-11ea-9a7e-9760a892b1e5.png)

Now you can try to `Refresh Kubernetes Metadata` again. Profile shows up.

**Comment by loganhz** [comment]
@nicolasmaier please make sure metadata can be downloaded in your setup.

**Comment by nicolasmaier** [comment]
/v3/cisconfigs looks like this:
![image](https://user-images.githubusercontent.com/55988296/79193031-1c7e8000-7e2a-11ea-85b7-d3cea46bf658.png)

Don't see the issue with the k8s versions in /v3/settings/k8s-versions-current:
![image](https://user-images.githubusercontent.com/55988296/79193281-99a9f500-7e2a-11ea-9919-24fc8afe9217.png)

I'm able to get to access the metadata url manually from the rancher pods with curl.

But nothing changes when I run the "Refresh Kubernetes Metadata". Still no profiles available..

**Comment by nicolasmaier** [comment]
I've changed the rke-metadata-config from:
![image](https://user-images.githubusercontent.com/55988296/79198524-e80fc180-7e33-11ea-8907-ba5b843bac12.png)

to:
![image](https://user-images.githubusercontent.com/55988296/79198695-31f8a780-7e34-11ea-840b-37b568be4f1c.png)


After changing this and another manual refresh of the metadata, the cis profiles are available.
