### ISSUE TITLE
[RFE] Replace/Add Flatcar docker machine OS

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#26444]
This issue is a reference to the PR submitted here:
https://github.com/rancher/machine/pull/74

The idea is to replace the CoreOS implementation that is going to be EOL soon.
Even if it is not supported as a Rancher OS, it gives an alternative to CoreOS users.

gz#9269

**Comment by dabeck** [comment]
Any chance to get this merged?

**Comment by ibuildthecloud** [comment]
I see no issue adding this support.

**Comment by ibuildthecloud** [comment]
I see no issue adding this support in.

**Comment by superseb** [comment]
This is done in https://github.com/rancher/machine/pull/81
