### ISSUE TITLE
Self signed TLS fails to generate after v2.4.2 upgrade, UI won't load

### ISSUE THREAD

**Issue by andruwa13** [rancher/rancher#26457]
[ERROR] MultiClusterAppRevisionController cattle-global-data/mcapprevision-t7zmd [management-multiclusterapp-revisions-rbac] failed with : multiClusterApp.management.cattle.io "cattle-global-data/cert-manager" not found

[INFO] failed to create TLS cert for: 172.17.0.2

run command:

docker run -d -v /home/rancher/data:/var/lib/rancher --restart=unless-stopped -p 8080:80 -p 8443:443  --name rancher-server rancher/rancher

os Ubuntu 18.04.4
Docker version 19.03.8, build afacb8b7f0

**Comment by mshade** [comment]
I had the same issue. I switched to [providing my own self-signed cert to get going](https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/#option-b-bring-your-own-certificate-self-signed)

If I restart rancher server without the provided self-signed cert, the problem returns. Logs look like this:

```
rancher_1  | 2020/04/03 00:01:46 [INFO] Creating new TLS secret for serving-cert (count: 16): map[listener.cattle.io/redacted listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/redacted listener.cattle.io/redacted:8443 listener.cattle.io/cn-172.22.0.2:172.22.0.2 listener.cattle.io/cn-redacted listener.cattle.io/cn-hidden listener.cattle.io/redacted listener.cattle.io/redacted listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-redacted listener.cattle.io/redacted listener.cattle.io/redacted listener.cattle.io/redacted listener.cattle.io/cn-redacted listener.cattle.io/redacted listener.cattle.io/hash:0cd54ff8cbe4580f42c47283d84c3803465313dee49c616668ff4cd1c0aca82f]
rancher_1  | 2020/04/03 00:01:46 [INFO] failed to create TLS cert for: 172.22.0.2
```

How is it auto-detecting these hostnames? Some of the `redacted` names are unknown to me...

**Comment by ibuildthecloud** [comment]
If anyone hits this issue you can run the below in the kubernetes cluster run Rancher.  If this is a single node setup just `docker exec -it CONTAINER bash` first and then run the below.

```
kubectl -n cattle-system delete secret serving-cert
kubectl delete listenconfigs cli-config
```
Then restart Rancher

**Comment by andruwa13** [comment]
@ibuildthecloud  thanks work

**Comment by deniseschannon** [comment]
@andruwa13 I'd like to keep this open until we have a proper fix in the product.

**Comment by stanzhai** [comment]
I had the same issue after upgrade rancher from 2.3.5 to 2.4.0.

```
2020/04/01 15:48:40 [INFO] failed to create TLS cert for: 172.17.0.4
2020/04/01 15:48:40 [INFO] Creating new TLS secret for serving-cert (count: 7): map[...]
```

and 

```
kubectl -n cattle-system delete secret serving-cert
kubectl delete listenconfigs cli-config
```

met another problem: `This cluster is currently Unavailable; areas that interact directly with it will not be available until the API is ready`, it does not work for me.

**Comment by sowmyav27** [comment]
**Hit this issue on an upgrade from 2.3.5 to 2.4-head - commit : `04159d027`** 

Steps:
Deploy 2 DO clusters (1.15 k8s)
upgrade rancher to 2.4-head
rancher fails to launch
Logs:
```
2020/04/06 17:57:09 [INFO] failed to create TLS cert for: 172.17.0.2
2020/04/06 17:57:09 [INFO] Creating new TLS secret for serving-cert (count: 5): map[listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.2:172.17.0.2 listener.cattle.io/cn-<rancher-server-ip>:<rancher-server-ip> listener.cattle.io/cn-<rancher-server-ip>:443:<rancher-server-ip>:443 listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:3d9724530379cd5f60f01e5670b9fc533e116a7a8d7f5fbfd5a066d345edbc43]
2020/04/06 17:57:09 [INFO] failed to create TLS cert for: 172.17.0.2
2020/04/06 17:57:10 [INFO] Creating new TLS secret for serving-cert (count: 5): map[listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.2:172.17.0.2 listener.cattle.io/cn-<rancher-server-ip>:<rancher-server-ip> listener.cattle.io/cn-<rancher-server-ip>:443:<rancher-server-ip>:443 listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:3d9724530379cd5f60f01e5670b9fc533e116a7a8d7f5fbfd5a066d345edbc43]
2020/04/06 17:57:10 [INFO] failed to create TLS cert for: 172.17.0.2
```

**Comment by sowmyav27** [comment]
Verified a couple of times upgrade from 2.3.5 to 2.4-head - latest - commit id: `3f7fe7098`
and upgrade from 2.3.5 to master-head - commit id: `64e257376`

- Deploy 2 do clusters - 1 node all roles - 1.15 k8s version
- Upgrade to 2.4-head  and master-head
- User is able to access the Rancher UI post upgrade.
-

**Comment by aaronRancher** [comment]
Verified upgrade from v2.3.6 to 2.4-head version `cf5ab1dcb`
- Deploy 2 do clusters - 1 node all roles - 1.15 k8s version
- Upgrade to 2.4-head
- User is able to access the Rancher UI post upgrade.

**Comment by soumyalj** [comment]
Tested with upgrade from v2.0.10 -> v2.2.9->v2.2.11->v2.4-head
Created Rancher server v2.0.10 using Rancher generated certs
**Steps:**
1. Deploy a cluster in v2.0.10 with k8s 1.11.6-rancher1-1
Cluster config used: 1 control node, 3 etcd nodes and 3 worker nodes
2. Upgrade from rancher v2.0.10 to rancher v2.2.9
3. Upgrade from v2.2.11 to v2.4-head
Upgrade was successful and UI loaded fine. We can access the UI after upgrade to v2.4-head

**Comment by GameScripting** [comment]
I tried to overcome this issue by providing the `--acme-domain [DOMAIN]` flag.

It DOES NOT help to overcome the issue.

**Comment by GameScripting** [comment]
Tested with upgrade from v2.3.3 -> v2.3.7-rc2->v2.4 (`:latest`): FAILED
Tested with upgrade from v2.3.3 -> >v2.4-2809-head : SUCCESS

**Comment by dutangp** [comment]
I had this issue during the migration from v2.3.8 to v2.4.0. I tried the workaround suggested by @mshade, the UI worked but I got cluster Unavailable. I figured out a way to fix that and it's all good now. I even updated to v2.4.3.

My concern now is that I am running with my own self signed certificates and I would like to come back on Default Rancher-generated Self-signed Certificate. When I try to switch back to this mode, I still get the following error

```
2020/06/22 09:16:06 [INFO] Creating new TLS secret for serving-cert (count: 7): map[listener.cattle.io/cn-10.78.14.79:10.78.14.79 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.3:172.17.0.3 listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-localhost.localdomain:localhost.localdomain listener.cattle.io/cn-localhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainloca:localhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainloca listener.cattle.io/cn-myserver.rancher.env1.test.io :myserver.rancher.env1.test.io listener.cattle.io/hash:943998f2c07a2305e507623d494221d94ce1746115ad30040dfa3ecc8790d0dc]
2020/06/22 09:16:06 [INFO] failed to create TLS cert for: 172.17.0.3, Secret "serving-cert" is invalid: metadata.annotations: Invalid value: "listener.cattle.io/cn-localhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainloca": name part must be no more than 63 characters
```

**Comment by diogoserrano** [comment]
> 
> 
> I had this issue during the migration from v2.3.8 to v2.4.0. I tried the workaround suggested by @mshade, the UI worked but I got cluster Unavailable. I figured out a way to fix that and it's all good now. I even updated to v2.4.3.
> 
> My concern now is that I am running with my own self signed certificates and I would like to come back on Default Rancher-generated Self-signed Certificate. When I try to switch back to this mode, I still get the following error
> 
> ```
> 2020/06/22 09:16:06 [INFO] Creating new TLS secret for serving-cert (count: 7): map[listener.cattle.io/cn-10.78.14.79:10.78.14.79 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.3:172.17.0.3 listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-localhost.localdomain:localhost.localdomain listener.cattle.io/cn-localhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainloca:localhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainloca listener.cattle.io/cn-myserver.rancher.env1.test.io :myserver.rancher.env1.test.io listener.cattle.io/hash:943998f2c07a2305e507623d494221d94ce1746115ad30040dfa3ecc8790d0dc]
> 2020/06/22 09:16:06 [INFO] failed to create TLS cert for: 172.17.0.3, Secret "serving-cert" is invalid: metadata.annotations: Invalid value: "listener.cattle.io/cn-localhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainlocalhost.localdomainloca": name part must be no more than 63 characters
> ```
Hi @dutangp, 

We faced the same problem and thanks to our teammate @suvl for figured that out.

rancher have a k3s inside its container with a CRD called listenconfigs where is stored all the self-signed certificates generated by rancher.

All you have to do is delete that old certificate with more than 63 characters to overcome that error.

1. enter rancher container ( in our case we have a single node instance)
`docker exec -ti <rancher-container-id> /bin/bash`

2. edit the listenconfigs
`kubectl edit listenconfigs `

3. search for the line on the error and certificate and delete that line and you're ready to go with rancher upgrade with their self-signed etc :)

**Comment by dutangp** [comment]
hey @diogoserrano thanks a lot, I will try that on the next release as we had to use a homemade cert. This is awesome, thanks a lot.

I ll keep you updated

**Comment by troy256** [comment]
We see this issue on an upgrade of the single container install 2.3.3 to 2.4.5 with default self-signed cert.  

Using "kubectl edit listenconfigs" and pruning out the problematic lines did not help, Rancher still not listening on 443.

**Comment by troy256** [comment]
The only thing that worked for us was to first upgrade to 2.4.8 then use etcdctl inside the Rancher container to get the /registry/management.cattle.io/listenconfigs/cli-config key, edit out the bad certificate entry, and etcdctl put it back.  At that point we restarted the container and the UI came back up.
