### ISSUE TITLE
Helm version checks are too strict

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#26450]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
use a random value for helm version
or
use a shortened version of helm version (example: "v2", "v3")

**Result:**
* isHelm2 check is too strict so tiller wont start. 
* isHelm3 check  is too strict so shortened values are not accepted

**Solution**
Tiller always checks to see if it is helm v2 before starting by checking param version against the v2 string, but users are not aware of the exact v2 string or might throw in something more generic like the shortened version (or just garbage). In this case we need to default to helm 2. 

Similarly, users specifying another version of v3 should end up using helm v3.

**Comment by rancher-max** [comment]
Need a merge in 2.4 branch as well

**Comment by cbron** [comment]
@rancher-max fixed, let me know if you need anything else.

**Comment by rancher-max** [comment]
This is needed for the cli to allow passing `v2` or `v3` when adding a catalog and specifying helm version. Valid values are now `helm_v2`, `helm_v3`, `v2`, or `v3`. This has been validated in both `master-2750-head` and `v2.4-2745-head` Rancher.


Passing in garbage works in some cases. See two scenarios below:
- Pass in garbage v3 value
```
$ rancher catalog add --helm-version myv3 badversion-test https://github.com/rancher-max/helm-foo
FATA[0000] Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [baseType=error, code=InvalidBodyContent, message=Invalid helm 3 version] from [https://173.230.145.148/v3/catalogs]
```
- Pass in garbage v2 value
```
$ rancher catalog add --helm-version myv2though badversion-test https://github.com/rancher-max/helm-foo
# Success!
```

I believe the error case is okay as it gives a descriptive error, and using `rancher catalog add --help` specifies to use `v2` or `v3` explicitly. @brendarearden and @cbron If you feel differently let me know. I'll leave this open pending your judgement, but if you agree we can close.

**Comment by cbron** [comment]
@rancher-max yes thats by design. We wanted to give users who try to pass something v3-like to be warned that it failed. If the mangle v2 then we just use v2 anyway so we don't error out. If thats all then good to close.
