### ISSUE TITLE
Wait and intervalMillis not configurable RancherUI

### ISSUE THREAD

**Issue by jacktuck** [rancher/rancher#2645]
When performing an upgrade in Rancher's UI, you can only specify the `startStop` ('Start before Stop' checkbox) behaviour but not the wait or interval.

**Comment by vincent99** [comment]
Interval is the middle box:

![image](https://cloud.githubusercontent.com/assets/753917/11128743/f3c76770-8938-11e5-86ec-113f7cc2fe0c.png)

and I'm not sure what you mean by "wait" @jacktuck because that is not a thing in the API.

**Comment by jacktuck** [comment]
@vincent99 Oh i missed that. 

Oh i thought `-wait` was an option? http://docs.rancher.com/rancher/rancher-compose/upgrading/

**Comment by deniseschannon** [comment]
That is for rolling upgrade, where as the UI is performing an in-service upgrade.

Rolling Upgrade: Creates new service with new containers before removing old containers/service.
In-Service Upgrade: Create new containers while deleting old containers in same service.

**Comment by jacktuck** [comment]
I have an image which uses NGINX as the base image and even with startStop:true it seems like the new container is not fully started before the old container downgrades itself. Should i play with the batch interval option - or is there a better way?

**Comment by vincent99** [comment]
The field is called `startFirst: true`, not `startStop`.  `intervalMillis` is the interval between scheduling new containers (`batchSize` at a time).. So you can use that to provide some time for the service to startup before upgrading more.

But there is not currently an interval for how long to wait for the new container to start before stopping the old one and we have no way to know when the new container is actually "up" (well, healthchecks, but I don't think it does that, @alena1108 ?)
