### ISSUE TITLE
OPA Gatekeeper: update system chart to latest beta version v3.1.0-beta8 released

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#26453]
OPA Gatekeeper has released new beta version - v3.1.0-beta.8 
https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.1.0-beta.8

We need to update the system chart that deploys gatekeeper in Rancher and test out the updates.

**Comment by izaac** [comment]
Core functionality was validated following the test plan. But this is not yet fully integrated with the UI, UI test cases are pending for validation. 

For example I had to follow extra manual steps to install OPA gateway and be able to check constraints and templates.

@prachidamle @codyrancher

**Comment by izaac** [comment]
Closing UI testing will be performed as part of different issue in the dashboard repository as well as upgrade.
