### ISSUE TITLE
Upgrade path verification: k8s 1.11.6 -> 1.14.10 & Rancher 2.0.3 => 2.3.6

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#26458]
**The assumptions are we are trying to upgrade:**
1. k8s versions from 1.11.6 to 1.14.10 (since this will be latest in the 1.14.x series). 
2. rancher version from 2.0.3 to 2.3.6 (eventually client will upgrade to 2.4 but not needed for the verification test)

**The Upgrade path/steps are:**

1. Start a setup with 2.0.3, create a k8s cluster with version 1.11.6
2. Have pre-upgrade deployments in the k8s cluster
3. First upgrade Rancher to 2.1.4
4. Upgrade Rancher to 2.2.11
5. Upgrade the k8s cluster to 1.14.10
6. Upgrade to Rancher to 2.3.6
7. Run validation tests on this upgraded cluster

**Comment by ohauer** [comment]
Perhaps do some additional steps like enable monitoring and istio if available.
In my experience upgrade works most the time w.o., but sometimes fails if one of them are enabled.

**Comment by sowmyav27** [comment]
Plan of action:

**Scenario#1**

- Deploy a cluster in 2.0.10 with k8s 1.11.6
- Run pre upgrade checks
- Upgrade from rancher:2.0.10 to rancher:2.2.9 
- Run post upgrade checks
- Upgrade to 2.2.11 and Run post upgrade checks
- Upgrade k8s to 1.14.10 and Run post upgrade checks
- Upgrade to 2.4.2 and Run post upgrade checks - no k8s upgrade

**Scenario#2**

- Deploy a cluster in 2.2.9 with k8s 1.14.8
- Run pre upgrade checks
- Upgrade from rancher:2.2.9 to rancher:2.2.11
- Run post upgrade checks
- Upgrade k8s to 1.14.10 and Run post upgrade checks
- Upgrade to 2.4.2 and Run post upgrade checks - no k8s upgrade

**Comment by soumyalj** [comment]
Tested the below Scenarios and they succeeded
Scenario#1
1. Deploy a cluster in 2.0.10 with k8s 1.11.6 and run pre upgrade checks
2. Upgrade from rancher v2.0.10 to rancher v2.2.9 and run post upgrade checks
3. Upgrade to 2.2.11 and run post upgrade checks
4. Upgrade k8s to 1.14.10 and run post upgrade checks and also add a node
5. Upgrade to 2.4.2 and run post upgrade checks  and also add a node
After upgrading to v2.4.2, logged into each of the nodes and verified that kubelet was running with no restarts. Verified through docker inspect that Restart count = 0
```
      "Name": "/kubelet",
        "RestartCount": 0,

```
Also, verified that all pods in the system project are active.

Scenario#2

1. Deploy a cluster in 2.2.9 with k8s 1.14.8 and run pre upgrade checks
2. Upgrade from rancher v2.2.9 to rancher v2.2.11 and run post upgrade checks
3. Upgrade k8s to 1.14.10 and run post upgrade checks. Also, add a new node
4. Upgrade to 2.4.2 and run post upgrade checks . Add a new node. 
After upgrading to v2.4.2, logged into each of the nodes and verified that kubelet was running with no restarts. Verified through docker inspect that Restart count = 0
```
      "Name": "/kubelet",
        "RestartCount": 0,

```
Also, verified that all pods in the system project are active.

**Comment by leodotcloud** [comment]
Thanks @soumyalj for the update.

**Comment by sangeethah** [comment]
@soumyalj We will be having a new RC to address upgrade issues we are seeing with clusters using calico network - https://github.com/rancher/rancher/issues/26551

**Comment by soumyalj** [comment]
Retested the scenarios above with upgrade to the released version v2.2.11. 
Network Plugin for the clusters: Canal

**Scenario#1**

1. Deploy a cluster in 2.0.10 with k8s 1.11.6-rancher1-1 and run pre upgrade checks
2. Upgrade from rancher v2.0.10 to rancher v2.2.9 and run post upgrade checks
3. Upgrade to  rancher v2.2.11 and run post upgrade checks
4. Upgrade k8s to 1.14.10 and run post upgrade checks and also add a node
5. Upgrade to 2.4.2 and run post upgrade checks  and also add a node
After upgrading to v2.4.2, logged into each of the nodes and verified that kubelet was running with no restarts. Verified through docker inspect that Restart count = 0
```
      "Name": "/kubelet",
        "RestartCount": 0,

```
Also, verified that all pods in the system project are active.

**Scenario#2**

1. Deploy a cluster in 2.2.9 with k8s 1.14.8 and run pre upgrade checks
2. Upgrade from rancher v2.2.9 to rancher v2.2.11 and run post upgrade checks
3. Upgrade k8s to 1.14.10 and run post upgrade checks. Also, add a new node
4. Upgrade to rancher v2.4.2 and run post upgrade checks . Add a new node. 
After upgrading to v2.4.2, logged into each of the nodes and verified that kubelet was running with no restarts. Verified through docker inspect that Restart count = 0
```
      "Name": "/kubelet",
        "RestartCount": 0,

```
Also, verified that all pods in the system project are active.

**Comment by soumyalj** [comment]
Other issues found during testing this issue:
https://github.com/rancher/rancher/issues/26586
https://github.com/rancher/rancher/issues/26588

**Comment by mrajashree** [comment]
Are we testing upgrade only from 2.2.11 to 2.4.2 directly? why not also 2.3.6 first, so 
2.2.11->2.3.6->2.4.2? 
if any of the above two issues are found in 2.2.11 -> 2.3.6 that'll make things easier to debug
