### ISSUE TITLE
[RFE] Allow project admin to disallow namespace delete

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#26472]
Rancher 2.3.5
Kubernetes 1.16

It is not possible to remove the delete permission on namespace for project members.
Would it be possible to allow project owner to remove the delete permission on namespaces ?

gz#8782

**Comment by manicole** [comment]
Would need that too.

Btw, I can't understand why in the Role "project-member" the only action allowed on namespace is "Create" :
![image](https://user-images.githubusercontent.com/55095426/104185605-793cb480-5415-11eb-927e-7ec4ee4ffea7.png)

In practice, as @zaggash said, any project member can delete a namespace in his project ... Any clue ?

**Comment by manicole** [comment]
Still interested by the feature. Thanks
