### ISSUE TITLE
404 default backend

### ISSUE THREAD

**Issue by jehutyy** [rancher/rancher#26470]
**Bug**
creating a new cluster on a single node rancher server results in a `404 default backend` error

**Steps to reproduce**

1. `docker run -dit --name rancher --rm -p 80:80 -p 443:443 rancher/rancher
2. log in
3. create a cluster
4. waiting cluster creation completion
5. trying get back to web interface and see a `404 default backend` in place of rancher gui

**Result:**
Rancher gui pops-up normally until new cluster creation.

**Other details that may be helpful:**
I installed rancher server on a publicly accessible cloud instance with a resolvable FQDN.

**Environment information**
- rancher/rancher:latest
- cloud instance vps debian buster
- Docker version 18.09.1, build 4c52b90

**Comment by hjacobs** [comment]
I have the same problem and can't figure out the problem from Docker logs.

**Comment by superseb** [comment]
This should be addressed by https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/advanced/#running-rancher-rancher-and-rancher-rancher-agent-on-the-same-node, if not, please file a new issue and describe the steps and commands executed to reproduce the behavior so we can investigate.
