### ISSUE TITLE
Cannot remove some hosts which no longer exist

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2647]
I'm recreating my Docker environment from scratch, but I am having some trouble removing the last two hosts registered in Rancher. The actual hosts themselves no longer exist -- the VMs have been deleted in vSphere. But two of the 20 hosts that I removed remain visible in Rancher in a "removing" state. They've been like this for at least 10 minutes.

I see quite a few of the following errors in the Rancher log:

```
2015-11-12 18:32:58,131 ERROR [:] [] [] [] [utorService-937] [c.p.e.p.i.DefaultProcessInstanceImpl] final ExitReason is null, should not be
2015-11-12 18:32:58,133 ERROR [:] [] [] [] [utorService-937] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [instance.purge:122796] on [2800] java.lang.IllegalStateException: Attempt to cancel when process is still transitioning
```

I'm going to try restarting the Rancher Server next. If that doesn't work, I guess I'll have to recreate the Rancher Server (and its data container).

**Comment by gordontyler** [comment]
Wrong button, dangit.

**Comment by gordontyler** [comment]
Restarting the Rancher Server allowed to get past the "removing" state and purge the hosts.

**Comment by gordontyler** [comment]
The /infra/containers page still shows a ton of containers stopping/stopped/removed/purging.

**Comment by gordontyler** [comment]
Some hosts which I had thought were removed and purged have magically shown up again as "purging".

**Comment by gordontyler** [comment]
And now they're gone again.

**Comment by gordontyler** [comment]
Eventually everything seems to have calmed down. There's a lot of *.purge processes executing (as seen on the /admin/processes page) but otherwise it seems to be happy.

**Comment by deniseschannon** [comment]
@gordontyler Let me know if you see this happening again. Since it eventually resolved, it might have just been due to the scale of your setup. 

Please re-open if you still have issues wit this one.
