### ISSUE TITLE
[Backport to 2.3] Add nodelocal DNS option as option in yaml

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#26480]
Backport to 2.3: https://github.com/rancher/rancher/issues/25811

**Comment by superseb** [comment]
Only change here is that it doesn't need the zero downtime addon option `updateStrategy`.

**Comment by superseb** [comment]
Backend is in

**Comment by westlywright** [comment]
UI is in https://github.com/rancher/ui/pull/3923

**Comment by jiaqiluo** [comment]
the corresponding RKE issue https://github.com/rancher/rke/issues/2014

**Comment by jiaqiluo** [comment]
confirmed that in `v2.3.7-rc2`, we see the following options for nodelocal DNS when provisioning a cluster and edit it as YAML 

![image](https://user-images.githubusercontent.com/6218999/80046999-1ab75b00-84c1-11ea-8c20-6aae2a94c906.png)
