### ISSUE TITLE
[Backport] 2.3: Cannot fully rotate AWS credentials for EKS clusters

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#26487]
**Backport:**
https://github.com/rancher/rancher/issues/25835

**Comment by rancher-max** [comment]
#### Validated in v2.3-head (commit id `8d057f70a`)

Performed same scenarios as noted in https://github.com/rancher/rancher/issues/25835#issuecomment-610081323 and saw the same results. Leaving this open for further investigation as well.

**Comment by rancher-max** [comment]
Closing due to https://github.com/rancher/rancher/issues/25835#issuecomment-610123017
