### ISSUE TITLE
[Backport] 2.3: Cluster Upgrade stuck if EKS Cluster was updated manually

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#26486]
**Backport:**
https://github.com/rancher/rancher/issues/24171

**Comment by cbron** [comment]
Should be milestone 2.3.7 right ?

**Comment by rancher-max** [comment]
#### Validated in v2.3-head (commit id `8d057f70a`)

Performed same scenarios as noted in https://github.com/rancher/rancher/issues/24171#issuecomment-608712606 and saw the same successful results.
