### ISSUE TITLE
CPU, RAM missing for k3s cluster in cluster view

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#26488]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Import a k3s cluster, go to cluster view

**Result:**
The RAM and CPU are missing, however if you click into the cluster, you can see the RAM and CPU for the cluster:
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/468462/78411716-7929a180-75c5-11ea-900b-97244edfc4ef.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.2
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
k3s imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):
v1.17.4+k3s1

- Docker version (use `docker version`):
None, using containerd:
1.3.3-k3s2

gzrancher/rancher#9733

**Comment by TReZ42** [comment]
Hi,

Apparently K3s server nodes are labelled as Control Plane nodes only (node-role.kubernetes.io/master=true). So rancher thinks there is no resources allocatable...

You can add the worker role to your server+agent nodes : `kubectl label node/your-node node-role.kubernetes.io/worker=true`.

Don't know if it's a K3s issue or not...

Regards,

Ben.

**Comment by cbron** [comment]
Confirmed this is still happening, and its API not UI issue.

**Comment by deniseschannon** [comment]
This looks as if it's already fixed in v2.5.2. 

@dnoland1 Can you confirm?

**Comment by sowmyav27** [comment]
**On `2.5.2`** 

- Import a K3s cluster into 2.5.2
- CPU and RAM are available
<img width="1408" alt="Screen Shot 2020-11-11 at 11 14 52 AM" src="https://user-images.githubusercontent.com/26032343/98854482-74588600-240f-11eb-97f7-c8f2e71ccb7c.png">

**Comment by dnoland1** [comment]
Works for me in v2.5.2:
![image](https://user-images.githubusercontent.com/468462/98902883-5f114500-246b-11eb-8560-f5b51e81080f.png)

**Comment by hinstw** [comment]
The CPU usage refuses to show up for me even after I label my node as worker

```
orangepi@orangepizero2w:~$ kubectl label node/orangepizero2w node-role.kubernetes.io/worker=true
node/orangepizero2w labeled
```

![screenshot](https://github.com/rancher/rancher/assets/43474314/f399bbc6-0666-47a3-aa88-280d6f521843)
