### ISSUE TITLE
Kubernetes version drop-down menu in cluster edit is broken

### ISSUE THREAD

**Issue by sdanieru** [rancher/rancher#26483]
**What kind of request is this**
BUG

**Steps to reproduce (least amount of steps as possible):**
1. In the Rancher UI, Global, click 'Add Cluster'
2. Under 'Cluster Options' observe and attempt to interact with the 'Kubernetes Version' drop-down menu.

**Result:**
The Drop down menu is empty; clicking on it has no effect other than to highlight it.

**Other details that may be helpful:**

This seems to be a general problem across clusters as I see this behavior for both existing and new clusters.

I'm observing this in both:
*Chromium Version 80.0.3987.162 (Official Build) snap (64-bit)
*Firefox 74.0 (64-bit)

**Environment information**
- Rancher version: 2.3.5
- Installation: HA

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.7
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        7141c199a2
 Built:             Wed Mar  4 01:22:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.7
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       7141c199a2
  Built:            Wed Mar  4 01:21:08 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by sdanieru** [comment]
![Screenshot from 2020-04-03 13-52-27](https://user-images.githubusercontent.com/18471926/78399615-75405400-75b2-11ea-9b98-fd110a674430.png)

**Comment by adrianovieira** [comment]
The same happening here, but we have a different situation...

It was just after upgrading rancher from v2.3.5 to v2.3.6 to v2.3.7 and finally to v2.3.8.

After all, that selection field became empty - as you can see on this image:


![image](https://user-images.githubusercontent.com/5561794/83931071-1d1ffc80-a771-11ea-83a3-66e42873fb3c.png)

As you notice, we can't upgrade kubernetes version for our downstream cluster.
 
Please!
What we can do to fix this?

**Comment by adrianovieira** [comment]
From this issue #25745...

At the "*Global*" menu goes to `tools > drivers>`  and execute **`refresh kubernetes metadata`**

Now it is working on our HA environments and I can upgrade all downstream clusters.
