### ISSUE TITLE
Cancel button doesn't work if I try to clone from summary view

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2648]
Version - Master with newest reskin

Steps:
1.  Add a Stack
2.  Add a Service to Stack
3.  From main Service screen click on a service
4.  From summary view go to menu and select Clone
4.  Click on Cancel in Add Service screen

Results:
Nothing happens.  Saw error in dev tools - Uncaught Error: More context objects were passed than there are dynamic segments for the route: environments.index

Expected:
Cancel out of Add Service

**Comment by tfiduccia** [comment]
Noticed that Add Service's cancel button doesn't work after opening summary view from anywhere until I reload screen.

**Comment by vincent99** [comment]
I think this was fixed earlier..

**Comment by tfiduccia** [comment]
Version - Master with latest reskin UI
Verified fixed
