### ISSUE TITLE
Cannot generate kubeconfig with cluster-scoped API tokens

### ISSUE THREAD

**Issue by danielmittelman** [rancher/rancher#26482]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug report

**Steps to reproduce (least amount of steps as possible):**
1. Create an API key that is scoped to a specific cluster
2. Use the access and secret key to perform the following call:
`POST https://<rancherhost>/v3/clusters/<cluster_id>?action=generateKubeconfig`
(use the same `cluster_id` and pass the access/secret keys as a bearer token)

**Result:**
The following HTTP response is returned:
`{"type":"error","status":"401","message":"clusterID does not match"}`

**Other details that may be helpful:**
We used this API call many times with v2.3.2 and it worked perfectly. This ability broke right after upgrading to v2.4.2.

Using API tokens without a scope is working.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.2
- Installation option (single install/HA): Single install

**Comment by PU-101** [comment]
release/v2.3
```
func GetClusterID(req *http.Request) string {
	clusterID := req.Header.Get("X-API-Cluster-Id")
	if clusterID != "" {
		return clusterID
	}

	parts := strings.Split(req.URL.Path, "/")
	if len(parts) > 3 && strings.HasPrefix(parts[2], "cluster") {
		return parts[3]
	}

	return ""
}
```

release/v2.4
```
func GetClusterID(req *http.Request) string {
	parts := strings.Split(req.URL.Path, "/")
	if len(parts) > 3 &&
		parts[0] == "" &&
		parts[1] == "k8s" &&
		(parts[2] == "clusters" || parts[2] == "cluster") {
		return parts[3]
	}

	return ""
}
```

when you call v3 api, the cluster id will always be empty string.

**Comment by jiaqiluo** [comment]
The bug is reproduced in rancher:`v2.4-3045-head`

Steps:
- add a cluster 
- add a key with the cluster scope 
- get and run the curl command for getting the kubeconfig with the cluster-scoped token in command line

<img width="788" alt="Screen Shot 2020-05-28 at 4 08 22 PM" src="https://user-images.githubusercontent.com/6218999/83203114-924e5a80-a0fd-11ea-8bc1-52827dbafe83.png">

Result:
error is returned:
```
{"type":"error","status":"401","message":"clusterID does not match"}
```

**Comment by hubert-he** [comment]
> The bug is reproduced in rancher:`v2.4-3045-head` and `master-3061-head`
> 
> Steps:
> 
> * add a cluster
> * add a key with the cluster scope
> * get and run the curl command for getting the kubeconfig with the cluster-scoped token in command line
> 
> <img alt="Screen Shot 2020-05-28 at 4 08 22 PM" width="788" src="https://user-images.githubusercontent.com/6218999/83203114-924e5a80-a0fd-11ea-8bc1-52827dbafe83.png">
> 
> Result:
> error is returned:
> 
> ```
> {"type":"error","status":"401","message":"clusterID does not match"}
> ```

yeah that's right。 
I hope rancher still keep compatible with old version

**Comment by jiaqiluo** [comment]
The bugfix is validated in both `master-3187-head` and `v2.4-3186-head`

The steps are the same as my previous comment describes. https://github.com/rancher/rancher/issues/26482#issuecomment-635664078

Now the kubeconfig file is returned.
