### ISSUE TITLE
View Details button not working in Summary View on main stack page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2649]
Version - Master with newest reskin UI

Steps:
1.  Add a stack
2.  Add a Service
3.  From main stack page, click on service name to bring up summary view
4.  In summary view click on View Details

Results:  nothing happens - Error (sition #56: TRANSITION COMPLETE.
container-spark-stats.js:68 Uncaught TypeError: Cannot read property 'forEach' of undefined)

Expected: Details for service comes up.

**Comment by vincent99** [comment]
I think this is fixed..

**Comment by tfiduccia** [comment]
Version - master with latest reskin UI
Verified fixed
