### ISSUE TITLE
UI hangs when a standard user edits a cluster in a setup with cluster-template-enforcement ON

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#26491]
Rancher version: v2.4.2

Steps:
1. Set Cluster-template-enforcement = True through the Settings tab
2. Create a standard user "newuser" 
3. As an admin, create a DO cluster "C1"
4. Add "newuser" as a cluster owner to the cluster "C1"
5. Login as "newuser" and edit the cluster "C1"

UI hangs as below:

![Screen Shot 2020-04-03 at 5 13 27 PM](https://user-images.githubusercontent.com/18536626/78413918-7f704b80-75ce-11ea-8aee-15ca58d45c5c.png)

Errors from the console:
![Screen Shot 2020-04-03 at 5 16 13 PM](https://user-images.githubusercontent.com/18536626/78413998-e68e0000-75ce-11ea-9932-82184659cdfd.png)

UI should not allow standard user to edit the cluster which is not created using a RKE template[Cluster-template-enforcement is set to True]

Note: When cluster is edited through API, it errors out as expected:
```

{
"baseType": "error",
"code": "MissingRequired",
"message": "A clusterTemplateRevision to create a cluster",
"status": 422,
"type": "error"
}

```

**Comment by soumyalj** [comment]
The same issue is observed in Rancher v2.3.6

**Comment by westlywright** [comment]
As the UI and API function currently this user is not allowed to edit the cluster because it doesn't have a cluster template associated with it. As such I've also added a warning for the user and added the cancel button so they can go back to the previous page.

**Comment by soumyalj** [comment]
Tested with v2.4-head with the steps mentioned above. 
UI does not hang when a standard user edits the cluster, but there is a "Done" button instead of "Cancel" button.
![Screen Shot 2020-04-15 at 11 25 45 AM](https://user-images.githubusercontent.com/18536626/79374439-2ed0ea80-7f0c-11ea-87c8-9a985cc43919.png)

**Comment by soumyalj** [comment]
Tested with latest v2.4 -head with steps mentioned above.
On a setup with cluster-template-enforcement ON, UI does not hang when a standard user edits the cluster.  "Cancel" button is displayed as expected.
![Screen Shot 2020-04-15 at 2 11 50 PM](https://user-images.githubusercontent.com/18536626/79389733-7adb5980-7f23-11ea-9212-1d6ec8b8728c.png)
