### ISSUE TITLE
upgrade rancher from 2.3.6 to 2.4.2

### ISSUE THREAD

**Issue by chengzn** [rancher/rancher#26495]
when i upgrade rancher server from 2.3.6 to 2.4.2

it failure！

the rancher log was

2020/04/04 20:01:45 [INFO] Refreshing driverMetadata in 1440 minutes
2020/04/04 20:01:45 [INFO] update kontainerdriver azurekubernetesservice
2020/04/04 20:01:45 [INFO] update kontainerdriver googlekubernetesengine
2020/04/04 20:01:45 [INFO] update kontainerdriver tencentkubernetesengine
2020/04/04 20:01:45 [INFO] update kontainerdriver aliyunkubernetescontainerservice
2020/04/04 20:01:45 [INFO] update kontainerdriver amazonelasticcontainerservice
2020/04/04 20:01:45 [INFO] update kontainerdriver baiducloudcontainerengine
2020/04/04 20:01:45 [INFO] update kontainerdriver rancherkubernetesengine
2020/04/04 20:01:45 [INFO] update kontainerdriver huaweicontainercloudengine
2020/04/04 20:01:45 [INFO] driverMetadata: refreshing data from upstream https://releases.rancher.com/kontainer-driver-metadata/release-v2.4/data.json
2020/04/04 20:01:50 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:42649
2020/04/04 20:01:50 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:44155
2020/04/04 20:01:50 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:44554
2020/04/04 20:01:50 [INFO] kontainerdriver googlekubernetesengine stopped
2020/04/04 20:01:50 [INFO] dynamic schema for kontainerdriver googlekubernetesengine updating
2020/04/04 20:01:50 [INFO] kontainerdriver azurekubernetesservice stopped
2020/04/04 20:01:50 [INFO] dynamic schema for kontainerdriver azurekubernetesservice updating
2020/04/04 20:01:50 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2020/04/04 20:01:50 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
time="2020-04-04 20:01:58" level=info msg="Collecting anonymous data from https://localhost:443/v3"
2020/04/04 20:02:29 [ERROR] Unknown error: Get https://10.0.204.188:6443/api/v1/namespaces?timeout=30s: waiting for cluster [c-8stcj] agent to connect
time="2020-04-04 20:02:29" level=error msg="Failed to get Namespaces err=Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=Get https://10.0.204.188:6443/api/v1/namespaces?timeout=30s: waiting for cluster [c-8stcj] agent to connect, baseType=error, code=ServerError] from [https://localhost:443/v3/cluster/c-8stcj/namespaces]"
2020/04/04 20:02:30 [ERROR] ClusterController c-8stcj [cluster-deploy] failed with : Get https://10.0.204.188:6443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent?timeout=30s: context deadline exceeded
2020/04/04 20:02:51 [INFO] Stopping cluster agent for c-8stcj
2020/04/04 20:02:57 [ERROR] Unknown error: Get https://10.0.204.188:6443/api/v1/namespaces?timeout=30s: waiting for cluster [c-8stcj] agent to connect
time="2020-04-04 20:02:57" level=error msg="Failed to get Namespaces for project c-8stcj:p-47cdm err=Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=Get https://10.0.204.188:6443/api/v1/namespaces?timeout=30s: waiting for cluster [c-8stcj] agent to connect] from [https://localhost:443/v3/cluster/c-8stcj/namespaces?limit=-1&projectId=c-8stcj%3Ap-47cdm&state_ne=removed]"
2020/04/04 20:03:27 [INFO] Error on LIST namespaces: Get https://10.0.204.188:6443/api/v1/namespaces?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers). Attempt: 1. Retrying
2020/04/04 20:03:57 [ERROR] Unknown error: Get https://10.0.204.188:6443/api/v1/namespaces?timeout=30s: waiting for cluster [c-8stcj] agent to connect
time="2020-04-04 20:03:57" level=error msg="Failed to get Namespaces for project c-8stcj:p-68ltv err=Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=Get https://10.0.204.188:6443/api/v1/namespaces?timeout=30s: waiting for cluster [c-8stcj] agent to connect] from [https://localhost:443/v3/cluster/c-8stcj/namespaces?limit=-1&projectId=c-8stcj%3Ap-68ltv&state_ne=removed]"
2020/04/04 20:04:27 [INFO] Error on LIST namespaces: Get https://10.0.204.188:6443/api/v1/namespaces?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers). Attempt: 1. Retrying
2020/04/04 20:04:52 [INFO] Stopping cluster agent for c-8stcj
time="2020-04-04 20:04:57" level=error msg="Failed to get Namespaces for project c-8stcj:p-74rh7 err=Get https://localhost:443/v3/cluster/c-8stcj/namespaces?limit=-1&projectId=c-8stcj%3Ap-74rh7&state_ne=removed: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
2020/04/04 20:04:57 [INFO] Error on LIST namespaces: Get https://10.0.204.188:6443/api/v1/namespaces?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Attempt: 2. Retrying
2020/04/04 20:05:27 [ERROR] Unknown error: Get https://10.0.204.188:6443/api/v1/namespaces?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2020/04/04 20:05:27 [INFO] Error on LIST namespaces: Get https://10.0.204.188:6443/api/v1/namespaces?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers). Attempt: 1. Retrying

what the problem?

**Comment by gameiro83** [comment]
Hi had the same issues with imported k8s cluster, mainly with oke ones Oracle kubernetes engine. Had to revert back to 2.3.5.
