### ISSUE TITLE
Ability to upgrade stopped stack for catalog

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2650]
v0.44.0

Steps to Reproduce:

1. Create an older version of a catalog entry.
2. Click on upgrade button in UI

Result: Unable to upgrade the services.

**Comment by alena1108** [comment]
We should also support upgrade for stack having mix of active/inactive services

**Comment by deniseschannon** [comment]
Some better steps written by @tfiduccia 

Steps;
1. Add Elasticsearch Stack with older version of rancher
2. Click on upgrade before you start any services
3. Try to finish upgrade

Results:
It gets stuck trying to upgrade.

Expected:
Should not get stuck.

**Comment by alena1108** [comment]
@sangeethah you can test this fix using the UI only. Could you file a separate bug to enable rancher-compose support?

**Comment by sangeethah** [comment]
Tested with build from master - dec 3

1. Add Elasticsearch Stack with older version of rancher. Choose not to start the service.
2. Click on upgrade before you start any services


kpof service tries to get upgraded but gets stuck in "activating" state since the containers get constantly restarted . All other services in the stack continue to remain in "Inactive" state.

Following exception seen in kpof container logs:


```
12/3/2015 7:29:51 PM2015/12/04 03:29:51 [emerg] 1#1: host not found in upstream "es-clients:9200" in /etc/nginx/nginx.conf:25
12/3/2015 7:29:51 PMnginx: [emerg] host not found in upstream "es-clients:9200" in /etc/nginx/nginx.conf:25
12/3/2015 7:30:19 PM2015/12/04 03:30:19 [emerg] 1#1: host not found in upstream "es-clients:9200" in /etc/nginx/nginx.conf:25
12/3/2015 7:30:19 PMnginx: [emerg] host not found in upstream "es-clients:9200" in /etc/nginx/nginx.conf:25
```

<img width="1241" alt="screen shot 2015-12-03 at 7 39 59 pm" src="https://cloud.githubusercontent.com/assets/4266958/11581381/fb24c58a-99f5-11e5-844d-0d03b7e60f9c.png">

**Comment by alena1108** [comment]
hm, looks like a compose bug. When upgrade stack, we should call upgrade for every service in order defined by links (similar how we start the services when stack.activate is called). Otherwise master service can get upgraded before service we depend on, even created. @ibuildthecloud ^^

**Comment by ibuildthecloud** [comment]
@alena1108 I believe that is how it works today.

**Comment by deniseschannon** [comment]
Verified with v0.51.0 that this is still a bug in rancher-compose v0.7.0. 

Steps to Reproduce:
1. Start ElasticSearch catalog item using old version (uncheck start services after creation)
2. After creation, click on upgrade available and select new one. 

kopf service gets stuck in activating as per @sangeethah's comments.

**Comment by asciifaceman** [comment]
Would it be related if I am unable to stop a "Finish upgrade" when there is a port conflict that can only be stopped by deleting the service in the stack

**Comment by deniseschannon** [comment]
@asciifaceman What state is your service in? Is it still trying to Uprgrade? This issue is specifically about having inactive stack and trying to upgrade the stack.

**Comment by asciifaceman** [comment]
Ah, it's not a match then. My situation was clicking "Finish upgrade" on an
active service with a port conflict puts it in an infinite loop that can
only be stopped by deleting it entirely.

On Tue, Mar 22, 2016 at 3:38 PM, Denise <notifications@github.com> wrote:

> @asciifaceman <https://github.com/asciifaceman> What state is your
> service in? Is it still trying to Uprgrade? This issue is specifically
> about having inactive stack and trying to upgrade the stack.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rancher/rancher/issues/2650#issuecomment-200063862>
>



-- 
Charles P. Corbett

**Comment by ibuildthecloud** [comment]
Tested on 1.0.0-rc5 and can't reproduce.

**Comment by deniseschannon** [comment]
Verified with v1.0.0-rc6.
