### ISSUE TITLE
[Backport 2.3.7] API has editable fields for fields that are not-editable for EKS clusters 

### ISSUE THREAD

**Issue by daxmc99** [rancher/rancher#26518]
Back for  https://github.com/rancher/rancher/issues/24652#issue-539369928

**Comment by daxmc99** [comment]
This may also require a UI change to mark these fields as read-only as well

**Comment by izaac** [comment]
I still see the subnet fields editable in the UI in latest `v2.3-head` commit id: 55b912553

**Comment by izaac** [comment]
Response from the API when trying to edit an existing EKS cluster:

```
{"baseType":"error","code":"InvalidBodyContent","message":"cannot modify EKS subnets after creation","status":422,"type":"error"}
```

UI shows

**Validation failed in API: cannot modify EKS subnets after creation**

**Comment by westlywright** [comment]
Available in latest-2.3 and 2.3.43

**Comment by izaac** [comment]
@deniseschannon are we planning to backport #22633 too along with this change? These EBS encrypt labels and the checkbox are now displayed in the EKS create and labels in EKS Edit

Create:

![Screen Shot 2020-04-21 at 6 22 45 PM](https://user-images.githubusercontent.com/27659/79930617-d747e880-83fd-11ea-9409-0441b777aa2e.png)

On Edit:
![Screen Shot 2020-04-21 at 6 21 46 PM](https://user-images.githubusercontent.com/27659/79930625-dd3dc980-83fd-11ea-9430-25c31c5dffc3.png)

This change could potentially increase the backend dev and testing scope of this issue. As of v2.3.6 this option is not available cc @sangeethah

**Comment by deniseschannon** [comment]
No, we aren't planning on backporting that specific feature. @westlywright Can we fix to remove that UI field? It must have been added as part of another commit.

**Comment by izaac** [comment]
Validated this in Rancher version: `v2.3.7-rc3`. Subnets are not appearing as editable in the UI when editing an EKS cluster.
