### ISSUE TITLE
Unlimited kube-audit log on node with RKE

### ISSUE THREAD

**Issue by scndel** [rancher/rancher#26515]
RKE node became unstable because log files grew very fast in `/var/log/kube-audit`

<img width="900" alt="Screenshot 2020-04-06 at 22 59 56" src="https://user-images.githubusercontent.com/17161227/78604633-68de2480-785a-11ea-916f-bc05d7e71874.png">

**kube-audit** is required by CIS but shouldn't be so verbose by default.
Or could we define the log path & level in the docker command while creating RKE node ?
That full directory prevented me from reimporting my node because it wasn't listed here:
https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/
It'd be nice to add it.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.2` UI: `v2.4.14` |
|Route|`undefined`|

**Comment by scndel** [comment]
I guess workaround lies here : 
https://rancher.com/docs/rke/latest/en/config-options/audit-log/
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy

On my host, I see a file _audit-policy.yaml_ in `/etc/kubernetes` whith pretty empty content :
```
apiVersion: audit.k8s.io/v1
kind: Policy
metadata:
  creationTimestamp: null
rules:
- level: Metadata
```

**Comment by superseb** [comment]
The defaults changed in v1.1.0 and higher, I updated the docs in https://github.com/rancher/docs/pull/2450. If you don't want to use the defaults, you can change them as shown in the docs link you added.

Cleaning the directory is added here: https://github.com/rancher/docs/pull/2451

**Comment by scndel** [comment]
Thanks @superseb for this accurate update. I didn't realise that editing cluster through UI was the proper way to interact with `cluster.yml` for RKE cluster made in Rancher. 
In fact I was vainly looking there for key `kube-audit` which is not present because it's a default config in `cluster/defaults.go` from RKE. 
But editing cluster through UI do indeed override those values.
![Rancher UI edit cluster kube-audit](https://user-images.githubusercontent.com/17161227/79336959-eeca3180-7f24-11ea-9cec-87bbcbf75a2f.png)
