### ISSUE TITLE
[Backport 2.3] Creating new cluster using Aliyun generates API error 400 while allocating EIP

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#26526]
https://github.com/rancher/rancher/issues/15847

**Comment by kingsd041** [comment]
Version:
rancher/rancher:master-head  04/13  commit id: 419b87a70

Create two Aliyun ECS clusters with different `EIP Charge Type (Pay By Bandwidth or Pay By Traffic)`. The cluster can be created successfully, and all containers and pods under the system project are healthy and some workloads can be successfully created in the default project
Test passed, Close it.
