### ISSUE TITLE
API is forcing users to provide access key/secret key (new UI) instead of login screen

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2652]
On the new UI, the API is popping up the access key/secret key screen in front of the login page of `http://ip:8080`

Also, if you use the `http://ip:8080/apps/welcome`, the API access key/secret key is the only thing shown. No login screen.

**Comment by vincent99** [comment]
This has nothing to do with new vs old UI... the initial HTML request is getting back `www-authenticate` from the API.

**Comment by will-chan** [comment]
Is this still happening?

**Comment by deniseschannon** [comment]
Unable to reproduce with v0.61.0-rc3
