### ISSUE TITLE
Monitoring v2

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#26549]
Create a new chart for Rancher Monitoring that patches the [upstream Prometheus Operator chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator). The default configuration of this chart will provide:
- Support for existing cluster-scoped metrics (CPU, Memory, etc.)
- Support for custom metrics configuration via creating / modifying ServiceMonitor and PodMonitor CRs (https://github.com/rancher/rancher/issues/22847)
- Support for setting customizable configuration of alerting / recording rules via creating / modifying PrometheusRules CRs
- Support for persisting custom Grafana dashboards or configuring custom Grafana Datasources via [creating ConfigMaps](https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-dashboards) (https://github.com/rancher/rancher/issues/24213, https://github.com/rancher/rancher/issues/20327)
- Implementation of the k8s Custom Metrics and Resource Metrics API through [Prometheus Adapter](https://github.com/helm/charts/tree/master/stable/prometheus-adapter) that allows users to expose custom metrics
- Integration with Alerting V2 with support for any other valid [AlertManager configurations](https://prometheus.io/docs/alerting/latest/configuration/)
- Support for Prometheus monitoring kube-controller-manager, kube-scheduler, and etcd nodes in an RKE cluster (https://github.com/rancher/rancher/issues/18619) 
    - Can be scraped in a hardened cluster using [PushProx](https://github.com/prometheus-community/PushProx) clients and proxies (https://github.com/rancher/rancher/issues/18044)

Since this chart will be a patch on the upstream Prometheus Operator chart, users will have full control over the deployment and should be able to customize their configuration in any way that the upstream Prometheus Operator currently supports, including using experimental features such as specifying remote read/write configurations to Prometheus and providing Thanos configuration.

Note: For integration with Prometheus Adapter for publishing custom metrics via the k8s Custom Metrics and Resource Metrics API, using [multiple Prometheus instances](https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/45) is currently an open issue.

Note: This new chart will only support cluster monitoring; project monitoring is no longer supported.

Parent PR: https://github.com/rancher/rancher/issues/23239

gzrancher/rancher#6800

gzrancher/rancher#11241

**Comment by jiaqiluo** [comment]
Monitoring v2 is being developed and validated on `rancher:master-head`

New issues will be made for each specific bug/issue. 

This can be closed.
