### ISSUE TITLE
[BUG] in Rancher Logging, Tests are not indicative of whether the config will work or not

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#26543]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Select ES as target for cluster logging
1. Use `Edit as File` mode and input the correct config
2. Click `Dry Run`

**Result:**
Dry run fails.  Even the config is correct.

**Environment information**
- Rancher: v2.3.5

**Tested on:**
Rancher Launched (Provider) EC2 cluster
- Kubernetes: v1.17.2
- Elasticsearch: standalone docker container elasticsearch:7.6.0
- Logging: v0.1.4

Rancher Launched (Provider) Google GKE cluster
- Kubernetes: v1.15.9-gke.24
- Elasticsearch: standalone docker container elasticsearch:7.6.0
- Logging: v0.1.4

**Comment by Tejeev** [comment]
This is a result of #26559 so I am closing this issue as a duplicate

**Comment by aiwantaozi** [comment]
@Tejeev could you paste the configure you just input in UI here?

**Comment by loganhz** [comment]
I cannot reproduce it locally. But it did happen in the user's env. The config looks good.

**Comment by aiwantaozi** [comment]
Not sure what tj got, but after I try it, and find we need to update some code base on the lastest rancher code and new fluentd version.

I got this error after click dry-run
![image](https://user-images.githubusercontent.com/5936271/85124710-efe94900-b25c-11ea-9a66-8154d49690ad.png)

configure
```
        @type elasticsearch
	include_tag_key  true
	hosts http://18.163.101.228:9200    
	logstash_prefix "ec2-2"
	logstash_format true
	logstash_dateformat  %Y-%m-%d
	type_name  "container_log"
```

and got fluentd warning [Deprecate top-level match](https://docs.fluentd.org/deployment/logging#deprecate-top-level-match)

**Comment by izaac** [comment]
Rancher version `v2.4-head (07/24/2020)` _29be104e6_
Rancher version `master-head (07/24/2020)` _80542c31b_

This is now showing an error in the UI if the dry run failed. 

This was previously reproduced in `v2.4.5` https://github.com/rancher/rancher/issues/27695#issuecomment-648973825

**Comment by cbron** [comment]
@aiwantaozi fluentD v0.1.20 has been tagged, can you PR that in. Afterwards @izaac we should re-test with those changes.

**Comment by izaac** [comment]
Re-opening for https://github.com/rancher/rancher/issues/26543#issuecomment-664036410

**Comment by izaac** [comment]
Current fluentd version in Rancher `v2.4-head (07/27/2020)` 3e543f7c4 is `rancher/fluentd:v0.1.19 `

**Comment by aiwantaozi** [comment]
@cbron create PRs, thanks.
[PR for v2.4](https://github.com/rancher/system-charts/pull/299)
[PR for v2.5](https://github.com/rancher/system-charts/pull/300)

**Comment by izaac** [comment]
Rancher version `master-head (07/28/2020)` _e20f472d4_
Rancher version `v2.4-head (07/28/2020)` _3e543f7c4_

I am trying to get a valid configuration when using the `Edit as File` with this configuration:

```
<match *>
  @type elasticsearch
  host <IP address>
  port 9200
  index_name fluentd1
  type_name fluentd
</match>
```

But this is the error I'm getting, as if the generated configuration file has a duplicated configuration section:

`stdout: 2020-07-28 17:32:55 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Section <label @FLUENT_LOG> appears twice" : stream error: command terminated with exit code 1`


This is the `fluent.conf` file in the `dry-run` container:

`root@rancher-logging-tester-fluentd-tester-5bf9b4889c-gwktz:/etc/fluent# cat fluent.conf `

```conf
# This is the root config file, which only includes components of the actual configuration

# Do not collect fluentd's own logs to avoid infinite loops.
<label @FLUENT_LOG>
  <match fluent.*>
    @type null
  </match>
</label>

@include /etc/fluent/config.d/*.conf
```

**Comment by cbron** [comment]
@aiwantaozi if we do need to remove one, should we remove it from fluentD then ? If so we can revert chart and fluentD PR, then publish new image that is same as 0.1.19.

**Comment by aiwantaozi** [comment]
@cbron we can revert the charts PR to quick fix the duplicated configuration,  fix in rancher is enough to fix the current problem, update fluentd configure isn't necessary. I will update the fluentd configure, then we can release a new fluentd, then update the chart with next fluentd version.

**Comment by cbron** [comment]
@izaac we reverted the chart update and image, so if you could just do a quick sanity check back on 0.2.1 which has fluentd image 0.1.19, then we should be good to go.

**Comment by izaac** [comment]
Validated this is working in `v2.4-head (07/30/2020)` _fdbd0245a_

Invalid config used to trigger an error during Dry Run:

```
<match *>
       @type elasticsearch
  	include_tag_key true
  	hosts http://host:9200
  	logstash_prefix "ec2-2"
  	logstash_format true
  	logstash_dateformat %Y-%m-%d
  	type_name "container_log"
</match>
```

Valid config used to get a valid response from Elasticsearch and check the logs reached the log server.

```
<match *>
  @type elasticsearch
	include_tag_key  true
	reload_connections false
	reconnect_on_error true
	reload_on_failure true
	hosts http://host:9200    
	logstash_prefix "izaac-do-test2"
	logstash_format true
	logstash_dateformat  %Y-%m-%d
	type_name  "container_log"
</match>
```

Will check on `master-head` next.

**Comment by izaac** [comment]
Rancher version `master-head (07/30/2020)` _c53a66e22_
`rancher/fluentd:v0.1.19`

The Dry run fails using the same valid file I used in `v2.4-head` 

```
<match *>
  @type elasticsearch
	include_tag_key  true
	reload_connections false
	reconnect_on_error true
	reload_on_failure true
	hosts http://host:9200    
	logstash_prefix "izaac-do-log1"
	logstash_format true
	logstash_dateformat  %Y-%m-%d
	type_name  "container_log"
</match>
```

```json
{
    "baseType": "error",
    "code": "ServerError",
    "message": "dry run fluentd failed, stdout: 2020-07-30 22:51:13 +0000 [warn]: parameter 'time_format' in \u003csource\u003e\n  @type tail\n  path \"/var/log/containers/*.log\"\n  pos_file \"/fluentd/log/fluentd-cluster-logging.pos\"\n  time_format %Y-%m-%dT%H:%M:%S.%N\n  tag \"cluster.*\"\n  format json\n  skip_refresh_on_startup true\n  read_from_head true\n  \u003cparse\u003e\n    @type \"multi_format\"\n    \u003cpattern\u003e\n      format json\n      time_format \"%Y-%m-%dT%H:%M:%S.%NZ\"\n      time_type string\n    \u003c/pattern\u003e\n    \u003cpattern\u003e\n      format regexp\n      time_format \"%Y-%m-%dT%H:%M:%S.%N%:z\"\n      expression /^(?\u003ctime\u003e.+)\\b(?\u003cstream\u003estdout|stderr)\\b(?\u003clog\u003e.*)$/\n    \u003c/pattern\u003e\n  \u003c/parse\u003e\n\u003c/source\u003e is not used.\n2020-07-30 22:51:13 +0000 [warn]: parameter 'format' in \u003csource\u003e\n  @type tail\n  path \"/var/log/containers/*.log\"\n  pos_file \"/fluentd/log/fluentd-cluster-logging.pos\"\n  time_format %Y-%m-%dT%H:%M:%S.%N\n  tag \"cluster.*\"\n  format json\n  skip_refresh_on_startup true\n  read_from_head true\n  \u003cparse\u003e\n    @type \"multi_format\"\n    \u003cpattern\u003e\n      format json\n      time_format \"%Y-%m-%dT%H:%M:%S.%NZ\"\n      time_type string\n    \u003c/pattern\u003e\n    \u003cpattern\u003e\n      format regexp\n      time_format \"%Y-%m-%dT%H:%M:%S.%N%:z\"\n      expression /^(?\u003ctime\u003e.+)\\b(?\u003cstream\u003estdout|stderr)\\b(?\u003clog\u003e.*)$/\n    \u003c/pattern\u003e\n  \u003c/parse\u003e\n\u003c/source\u003e is not used.\n",
    "status": 500,
    "type": "error"
}
```

**Comment by aiwantaozi** [comment]
I tested it project logging, no warning here. I found this warning show in cluster logging. Because this commit added duplicated configure to cluster logging, so one of the duplicated configure is not used.

these two lines [line1](https://github.com/rancher/rancher/commit/67748d6c4adec8a00cce9e02c9e4cbc153184ca0),  [line2](https://github.com/rancher/rancher/commit/67748d6c4adec8a00cce9e02c9e4cbc153184ca0#diff-5fc54d8d08cb96bfe5d6efc5f5602454L20) are duplicated to  [duplicated configure](https://github.com/rancher/rancher/commit/67748d6c4adec8a00cce9e02c9e4cbc153184ca0#diff-5fc54d8d08cb96bfe5d6efc5f5602454R29-R30) .

**Comment by cbron** [comment]
2.4 and master fixes in, ready for test again

**Comment by izaac** [comment]
This is working as expected in:

Rancher version `v2.4-head (08/05/2020)` _66c7e285e_
Rancher version `master-head (08/05/2020)` _65a2b808c_ HA k8s

- Cluster and Project level logging checked.
- Cluster types: RKE DO and K3s imported 
- `Dry run` in `Edit as File` tested and checked the logs flow to the server for valid configuration.
- `Test` button in `Edit as Form` tested too.


No backslashes issue observed in either RKE or K3s clusters tests.


Opened an issue while testing Dry Run on imported K3s cluster but opened as a separate issue:
#28250
