### ISSUE TITLE
Removed nodes not correctly cleaned up

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#26545]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy a 3 node custom cluster with roles `all` and wait for the cluster to stabilize
2. Delete one of the nodes

**Result:**
- Docker and k8s containers continue to run on the deleted node.
- etcd is still trying to reconnect to its peers, and in one test even able to do so and continued on as the master (though we've not reproduced this since). 
- `/etc/kubernetes/ssl` has not been cleared.
- When I restarted the node it rejoined the cluster as a worker

```
root@ip-10-0-4-253:/home/ubuntu# docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                          PORTS               NAMES
3d658f8790c4        70f311871ae1                          "/coredns -conf /etc…"   45 seconds ago      Up 44 seconds                                       k8s_coredns_coredns-7c5566588d-m585c_kube-system_bd1af8ea-f647-43ca-8c80-57020d261e1e_3
887b4fdf0ccb        rancher/kube-api-auth                 "/bin/sh -c 'kube-ap…"   29 hours ago        Up 29 hours                                         k8s_kube-api-auth_kube-api-auth-6l5ms_cattle-system_25c77d6e-59ef-40a6-9b52-4527bb14a53f_0
87d115b009f9        069831ff8196                          "run.sh"                 29 hours ago        Up 29 hours                                         k8s_agent_cattle-node-agent-r4lp7_cattle-system_93160240-7dac-4bf5-ae1a-51b1d4b349c4_0
e52cd9e1081c        rancher/pause:3.1                     "/pause"                 29 hours ago        Up 29 hours                                         k8s_POD_kube-api-auth-6l5ms_cattle-system_25c77d6e-59ef-40a6-9b52-4527bb14a53f_0
e859429fd2cf        rancher/pause:3.1                     "/pause"                 29 hours ago        Up 29 hours                                         k8s_POD_cattle-node-agent-r4lp7_cattle-system_93160240-7dac-4bf5-ae1a-51b1d4b349c4_0
09a50ab9643f        rancher/nginx-ingress-controller      "/usr/bin/dumb-init …"   29 hours ago        Up 29 hours                                         k8s_nginx-ingress-controller_nginx-ingress-controller-nnjrv_ingress-nginx_c02dbebc-230d-45d0-864d-11e2e9229f6c_0
2e030f5a770f        rancher/pause:3.1                     "/pause"                 29 hours ago        Up 29 hours                                         k8s_POD_nginx-ingress-controller-nnjrv_ingress-nginx_c02dbebc-230d-45d0-864d-11e2e9229f6c_0
af9bbea7e426        rancher/coreos-flannel                "/opt/bin/flanneld -…"   29 hours ago        Up 29 hours                                         k8s_kube-flannel_canal-5fh2c_kube-system_c5497df7-ead8-4680-8e42-9cda428f92b7_0
47fab53b94be        rancher/pause:3.1                     "/pause"                 29 hours ago        Up 29 hours                                         k8s_POD_coredns-7c5566588d-m585c_kube-system_bd1af8ea-f647-43ca-8c80-57020d261e1e_3
2d0bb687dfc0        rancher/calico-node                   "start_runit"            29 hours ago        Up 29 hours                                         k8s_calico-node_canal-5fh2c_kube-system_c5497df7-ead8-4680-8e42-9cda428f92b7_0
7a37f606e86b        rancher/pause:3.1                     "/pause"                 29 hours ago        Up 29 hours                                         k8s_POD_canal-5fh2c_kube-system_c5497df7-ead8-4680-8e42-9cda428f92b7_0
fe55b79e5404        rancher/hyperkube:v1.17.4-rancher1    "/opt/rke-tools/entr…"   29 hours ago        Up 29 hours                                         kube-proxy
728d643f7880        rancher/hyperkube:v1.17.4-rancher1    "/opt/rke-tools/entr…"   29 hours ago        Up 29 hours                                         kubelet
16adc313d1bc        rancher/hyperkube:v1.17.4-rancher1    "/opt/rke-tools/entr…"   29 hours ago        Up 16 hours                                         kube-scheduler
819a18e106fc        rancher/hyperkube:v1.17.4-rancher1    "/opt/rke-tools/entr…"   29 hours ago        Up 5 minutes                                        kube-controller-manager
41c2555b9ac5        rancher/hyperkube:v1.17.4-rancher1    "/opt/rke-tools/entr…"   29 hours ago        Up 29 hours                                         kube-apiserver
c8c25f103d58        rancher/coreos-etcd:v3.4.3-rancher1   "/usr/local/bin/etcd…"   29 hours ago        Restarting (0) 22 seconds ago                       etcd
root@ip-10-0-4-253:/home/ubuntu# ls /etc/kubernetes/ssl
certs                                    kube-apiserver-requestheader-ca.pem  kube-controller-manager.pem   kube-etcd-10-0-4-36-key.pem  kube-proxy.pem                      kubecfg-kube-apiserver-proxy-client.yaml      kubecfg-kube-scheduler.yaml
kube-apiserver-key.pem                   kube-apiserver.pem                   kube-etcd-10-0-4-196-key.pem  kube-etcd-10-0-4-36.pem      kube-scheduler-key.pem              kubecfg-kube-apiserver-requestheader-ca.yaml
kube-apiserver-proxy-client-key.pem      kube-ca-key.pem                      kube-etcd-10-0-4-196.pem      kube-node-key.pem            kube-scheduler.pem                  kubecfg-kube-controller-manager.yaml
kube-apiserver-proxy-client.pem          kube-ca.pem                          kube-etcd-10-0-4-253-key.pem  kube-node.pem                kube-service-account-token-key.pem  kubecfg-kube-node.yaml
kube-apiserver-requestheader-ca-key.pem  kube-controller-manager-key.pem      kube-etcd-10-0-4-253.pem      kube-proxy-key.pem           kube-service-account-token.pem      kubecfg-kube-proxy.yaml
```
![image](https://user-images.githubusercontent.com/8906089/78723478-64317300-7923-11ea-9274-62c69f709786.png)
```
ubuntu@ip-10-0-4-253:~$ sudo su
root@ip-10-0-4-253:/home/ubuntu# docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                         PORTS               NAMES
84c1d3e7c322        ff281650a721                          "/opt/bin/flanneld -…"   16 seconds ago      Up 15 seconds                                      k8s_kube-flannel_canal-9vhpj_kube-system_65faa90a-e36d-4b7e-bba3-0872b98d5e30_0
00518ce87b49        d6abb567faf1                          "start_runit"            16 seconds ago      Up 16 seconds                                      k8s_calico-node_canal-9vhpj_kube-system_65faa90a-e36d-4b7e-bba3-0872b98d5e30_0
ae97fcc7a59c        069831ff8196                          "run.sh"                 19 seconds ago      Up 18 seconds                                      k8s_agent_cattle-node-agent-hlvlb_cattle-system_c6f00bbf-a1ad-4b63-8ad8-d9feb36b21e6_0
f987b9b339c8        rancher/pause:3.1                     "/pause"                 19 seconds ago      Up 19 seconds                                      k8s_POD_cattle-node-agent-hlvlb_cattle-system_c6f00bbf-a1ad-4b63-8ad8-d9feb36b21e6_0
d14008227485        rancher/pause:3.1                     "/pause"                 19 seconds ago      Up 19 seconds                                      k8s_POD_canal-9vhpj_kube-system_65faa90a-e36d-4b7e-bba3-0872b98d5e30_0
4bbf35e946e9        rancher/rancher-agent:v2.3.4          "run.sh --server htt…"   29 seconds ago      Up 27 seconds                                      mystifying_gould
fe55b79e5404        rancher/hyperkube:v1.17.4-rancher1    "/opt/rke-tools/entr…"   29 hours ago        Up 31 seconds                                      kube-proxy
728d643f7880        rancher/hyperkube:v1.17.4-rancher1    "/opt/rke-tools/entr…"   29 hours ago        Up 31 seconds                                      kubelet
16adc313d1bc        rancher/hyperkube:v1.17.4-rancher1    "/opt/rke-tools/entr…"   29 hours ago        Up 31 seconds                                      kube-scheduler
819a18e106fc        rancher/hyperkube:v1.17.4-rancher1    "/opt/rke-tools/entr…"   29 hours ago        Up 31 seconds                                      kube-controller-manager
41c2555b9ac5        rancher/hyperkube:v1.17.4-rancher1    "/opt/rke-tools/entr…"   29 hours ago        Up 31 seconds                                      kube-apiserver
c8c25f103d58        rancher/coreos-etcd:v3.4.3-rancher1   "/usr/local/bin/etcd…"   29 hours ago        Restarting (0) 4 seconds ago                       etcd
root@ip-10-0-4-253:/home/ubuntu# ls /etc/kubernetes/ssl
certs                                    kube-apiserver-requestheader-ca.pem  kube-controller-manager.pem   kube-etcd-10-0-4-36-key.pem  kube-proxy.pem                      kubecfg-kube-apiserver-proxy-client.yaml      kubecfg-kube-scheduler.yaml
kube-apiserver-key.pem                   kube-apiserver.pem                   kube-etcd-10-0-4-196-key.pem  kube-etcd-10-0-4-36.pem      kube-scheduler-key.pem              kubecfg-kube-apiserver-requestheader-ca.yaml
kube-apiserver-proxy-client-key.pem      kube-ca-key.pem                      kube-etcd-10-0-4-196.pem      kube-node-key.pem            kube-scheduler.pem                  kubecfg-kube-controller-manager.yaml
kube-apiserver-proxy-client.pem          kube-ca.pem                          kube-etcd-10-0-4-253-key.pem  kube-node.pem                kube-service-account-token-key.pem  kubecfg-kube-node.yaml
kube-apiserver-requestheader-ca-key.pem  kube-controller-manager-key.pem      kube-etcd-10-0-4-253.pem      kube-proxy-key.pem           kube-service-account-token.pem      kubecfg-kube-proxy.yaml
```

**Expected Behavior**
- All containers on the host to be stopped
- All secure information (including `/etc/kubernetes/ssl`) should be removed
- The node should not rejoin the cluster when restarted

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.4

**Cluster information**
- Cluster type: Custom cluster hosted on EC2 nodes
- Kubernetes version: v1.17.4

gz#9282

gz#10636

gz#11132

gz#12206

gz#14041

**Comment by Tejeev** [comment]
I re-ran the delete and reboot on a second node to capture screenshots before and after the reboot.

Before:
![image](https://user-images.githubusercontent.com/8906089/78723945-4b758d00-7924-11ea-941e-f7957f3b103d.png)


After:
![image](https://user-images.githubusercontent.com/8906089/78724129-b0c97e00-7924-11ea-8e6f-5095ba650e4a.png)

**Comment by mattmattox** [comment]
This bug caused a production outage because kube-scheduler and kube-controller-manager were left behind. Due to the "zombie" scheduler grabbing the leader election but being unable to schedule anything due to overlay not being available on the deleted node.

Error:
`Internal error occurred: failed calling webhook "admission-webhook.windows-gmsa.sigs.k8s.io": Post https://gmsa-webhook.gmsa-webhook.svc:443/mutate?timeout=30s: context deadline exceeded; Deployment does not have minimum availability.`

Workaround:
```
docker rm -f kube-scheduler
docker rm -f kube-controller-manager
```

**Comment by mattmattox** [comment]
Containers that are being left behind.
![image](https://user-images.githubusercontent.com/17145893/85743518-b6379880-b6c9-11ea-9ad5-42e4ffa49b97.png)

**Comment by mattmattox** [comment]
Here are all the containers that are being left behind on a deleted node.
![image](https://user-images.githubusercontent.com/17145893/85743721-e7b06400-b6c9-11ea-9188-b9bb6fb989fd.png)

**Comment by Tejeev** [comment]
I believe we are seeing this when people destroy clusters using Terraform.

**Comment by Tejeev** [comment]
@maggieliu I think this might be an RKE issue instead of Rancher.  Could we get a review to be sure?

**Comment by sangeethah** [comment]
Related issue https://github.com/rancher/rancher/issues/21299

**Comment by maggieliu** [comment]
related to this: https://github.com/rancher/rancher/issues/17893

**Comment by maggieliu** [comment]
related to: https://github.com/rancher/rancher/issues/17893#issuecomment-466129353

**Comment by sadiapoddar** [comment]
I was able to reproduce this issue with v2.5.1 released

**Comment by sadiapoddar** [comment]
Steps to reproduce
1. At Rancher UI, bring custom clusters k8s with roles( etcd, control plane, worker) enable in each node
2. Once the cluster is running and stable, 
3. delete one of these k8s nodes
4. The "delete" didn't completely delete the rancher configuration on the deleted node
5. Reboot the k8s node which was deleted from the cluster, the node joined as a worker node in the cluster again. 
 
Expected behaviors, delete operations should completely prune all config information from the deleted node to avoid this behavior. Reboot/restart operation on the node shouldn't automatically join the deleted node in the cluster.


Execute the following command on the terminal of the deleted nodes, 

buntu@ip-172-31-0-248:~$ sudo docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                          PORTS               NAMES
cf972c9b3ffc        rancher/hyperkube:v1.19.3-rancher1     "/opt/rke-tools/entr…"   5 minutes ago       Up 5 minutes                                        kube-apiserver
91d4d65ae2d1        rancher/coreos-etcd:v3.4.13-rancher1   "/usr/local/bin/etcd…"   6 minutes ago       Restarting (0) 18 seconds ago                       etcd
d7224ffdf9eb        rancher/hyperkube:v1.19.3-rancher1     "/opt/rke-tools/entr…"   11 minutes ago      Up 11 minutes                                       kube-proxy
cd8b50cdb415        rancher/hyperkube:v1.19.3-rancher1     "/opt/rke-tools/entr…"   12 minutes ago      Up 12 minutes                                       kubelet
1ef0e245d961        rancher/hyperkube:v1.19.3-rancher1     "/opt/rke-tools/entr…"   12 minutes ago      Up 7 minutes                                        kube-scheduler
4591ffb78d83        rancher/hyperkube:v1.19.3-rancher1     "/opt/rke-tools/entr…"   12 minutes ago      Up 7 minutes                                        kube-controller-manager

**A few minutes later**
ubuntu@ip-172-31-0-248:~$ sudo docker ps
buntu@ip-172-31-0-248:~$ sudo docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                          PORTS               NAMES
cf972c9b3ffc        rancher/hyperkube:v1.19.3-rancher1     "/opt/rke-tools/entr…"   5 minutes ago       Up 5 minutes                                        kube-apiserver
91d4d65ae2d1        rancher/coreos-etcd:v3.4.13-rancher1   "/usr/local/bin/etcd…"   6 minutes ago       Restarting (0) 18 seconds ago                       etcd
d7224ffdf9eb        rancher/hyperkube:v1.19.3-rancher1     "/opt/rke-tools/entr…"   11 minutes ago      Up 11 minutes                                       kube-proxy
cd8b50cdb415        rancher/hyperkube:v1.19.3-rancher1     "/opt/rke-tools/entr…"   12 minutes ago      Up 12 minutes                                       kubelet
1ef0e245d961        rancher/hyperkube:v1.19.3-rancher1     "/opt/rke-tools/entr…"   12 minutes ago      Up 7 minutes                                        kube-scheduler
4591ffb78d83        rancher/hyperkube:v1.19.3-rancher1     "/opt/rke-tools/entr…"   12 minutes ago      Up 7 minutes                                        kube-controller-manager

SSL dir has the pem.keys
ubuntu@ip-172-31-0-248:~$ 
<img width="1644" alt="Screen Shot 2020-10-30 at 12 35 07 PM" src="https://user-images.githubusercontent.com/72409237/97749497-63715180-1aac-11eb-844f-4ad3d0b77437.png">

**Comment by bananflugan** [comment]
I have the same issues on my 2.5.5 clusters.

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.5.6**

- Deploy a cluster - 3 nodes all roles
- Delete a node. Cluster goes into Updating state.
- Docker ps on the deleted node shows:

```
docker ps
CONTAINER ID   IMAGE                                  COMMAND                  CREATED          STATUS                          PORTS     NAMES
082d505d886a   rancher/hyperkube:v1.20.4-rancher1     "/opt/rke-tools/entr…"   15 minutes ago   Up 15 minutes                             kube-proxy
57efa4ee9441   rancher/hyperkube:v1.20.4-rancher1     "/opt/rke-tools/entr…"   15 minutes ago   Up 15 minutes                             kubelet
a8cd9c208dd3   rancher/hyperkube:v1.20.4-rancher1     "/opt/rke-tools/entr…"   15 minutes ago   Up About a minute                         kube-scheduler
ec6e4be2e175   rancher/hyperkube:v1.20.4-rancher1     "/opt/rke-tools/entr…"   15 minutes ago   Up About a minute                         kube-controller-manager
f59565155eb5   rancher/hyperkube:v1.20.4-rancher1     "/opt/rke-tools/entr…"   15 minutes ago   Up 15 minutes                             kube-apiserver
d8c96cb0fac8   rancher/coreos-etcd:v3.4.14-rancher1   "/usr/local/bin/etcd…"   17 minutes ago   Restarting (0) 23 seconds ago             etcd
```
- kubectl get nodes on the cluster does not list the deleted node. 
- Reboot the deleted node 
- Node joined bacck to the cluster as worker nodes
- docker ps on the node shows
```
docker ps
CONTAINER ID   IMAGE                                  COMMAND                  CREATED          STATUS                          PORTS     NAMES
ee52e9d038b0   0bfefe9f649b                           "/opt/bin/flanneld -…"   28 seconds ago   Up 27 seconds                             k8s_kube-flannel_canal-p6l4s_kube-system_81c92878-f838-4eba-8434-4b57176630a6_0
d58d15e9b372   5a3c598c81d5                           "start_runit"            28 seconds ago   Up 27 seconds                             k8s_calico-node_canal-p6l4s_kube-system_81c92878-f838-4eba-8434-4b57176630a6_0
09c468c4bf2a   4cd72bf2d36b                           "run.sh"                 31 seconds ago   Up 30 seconds                             k8s_agent_cattle-node-agent-fwpk6_cattle-system_00446b79-d0ad-421a-b888-187845ac58fc_0
72edaeb8cb89   rancher/pause:3.2                      "/pause"                 32 seconds ago   Up 31 seconds                             k8s_POD_cattle-node-agent-fwpk6_cattle-system_00446b79-d0ad-421a-b888-187845ac58fc_0
150470fa6018   rancher/pause:3.2                      "/pause"                 32 seconds ago   Up 31 seconds                             k8s_POD_canal-p6l4s_kube-system_81c92878-f838-4eba-8434-4b57176630a6_0
6527f9e70129   rancher/rancher-agent:v2.5.6           "run.sh --server htt…"   50 seconds ago   Up 49 seconds                             silly_elbakyan
082d505d886a   rancher/hyperkube:v1.20.4-rancher1     "/opt/rke-tools/entr…"   18 minutes ago   Up 51 seconds                             kube-proxy
57efa4ee9441   rancher/hyperkube:v1.20.4-rancher1     "/opt/rke-tools/entr…"   18 minutes ago   Up 51 seconds                             kubelet
a8cd9c208dd3   rancher/hyperkube:v1.20.4-rancher1     "/opt/rke-tools/entr…"   18 minutes ago   Up 50 seconds                             kube-scheduler
ec6e4be2e175   rancher/hyperkube:v1.20.4-rancher1     "/opt/rke-tools/entr…"   18 minutes ago   Up 50 seconds                             kube-controller-manager
f59565155eb5   rancher/hyperkube:v1.20.4-rancher1     "/opt/rke-tools/entr…"   18 minutes ago   Up 50 seconds                             kube-apiserver
d8c96cb0fac8   rancher/coreos-etcd:v3.4.14-rancher1   "/usr/local/bin/etcd…"   20 minutes ago   Restarting (0) 12 seconds ago             etcd
```

**Comment by anupama2501** [comment]
`Reproduced` the issue on v2.5.6:

- Created a custom cluster with 3 nodes all roles on ember UI
- Once the node is up and active, deleted one of the nodes
- On the removed node, for docker ps

<img width="400" alt="Screen Shot 2021-06-07 at 8 02 44 AM" src="https://user-images.githubusercontent.com/38144301/121058329-14dc1200-c775-11eb-84aa-dda336c39978.png">

- On kubectl get nodes:

<img width="400" alt="Screen Shot 2021-06-07 at 8 03 41 AM" src="https://user-images.githubusercontent.com/38144301/121058386-20c7d400-c775-11eb-866a-d59ae54d241a.png">

- Once the node is rebooted and has come active, it joined the cluster back as a worker node:


<img width="1335" alt="Screen Shot 2021-06-07 at 8 08 23 AM" src="https://user-images.githubusercontent.com/38144301/121058543-4c4abe80-c775-11eb-83c5-125bec3449d1.png">



`Verified` on the rancher version: b2f8824

Scenario1:
1. Created an rke1 custom cluster from ember UI - 3 nodes all roles enabled on all 3 nodes.
2. Once the cluster is active, delete one of the nodes
3. On the deleted node, **docker ps**:
 all containers were removed
<img width="878" alt="Screen Shot 2021-06-07 at 10 03 05 AM" src="https://user-images.githubusercontent.com/38144301/121060513-99c82b00-c777-11eb-8975-7efcddc25692.png">

Restarted the node that was deleted from ember UI and verified that it was not added as a worker node

Scenario2: 
1. Created an rke1 custom cluster from explorer - 3 nodes all roles.
2. Once the cluster is active, deleted one of the nodes and the docker ps has no containers running except for the following. Rebooted the node and see that the node is not added back as a worker node.

```
CONTAINER ID        IMAGE                                                                        COMMAND                  CREATED             STATUS                          PORTS               NAMES
959e737abcb2        rancher/rancher-agent:master-b2f88241d8a5194b5a3a39cc84de0b0a046f8b7e-head   "run.sh --no-registe…"   2 hours ago         Restarting (1) 20 seconds ago                       share-mnt
```

**Comment by anupama2501** [comment]
Re-opening the tickte for the issue seen:
Scenario3:
1. Create an rke1 custom cluster from the dashboard UI with 3 nodes all roles.
2. Once the cluster is up and active, remove two nodes and verify the docker ps has no containers but the following and when we reboot the nodes they are not added back to the cluster.
3. Now remove the remaining 1 node as well with all roles as well. Following are the docker ps cotainers:
```
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS               NAMES
8e49757d47cc        rancher/hyperkube:v1.20.7-rancher1              "/opt/rke-tools/entr…"   8 minutes ago       Up 8 minutes                            kube-apiserver
14b5d7655cc9        rancher/mirrored-coreos-etcd:v3.4.15-rancher1   "/usr/local/bin/etcd…"   9 minutes ago       Up 9 minutes                            etcd
5edb7d6782f0        rancher/hyperkube:v1.20.7-rancher1              "/opt/rke-tools/entr…"   2 hours ago         Up 2 hours                              kube-proxy
1406aea831a2        rancher/hyperkube:v1.20.7-rancher1              "/opt/rke-tools/entr…"   2 hours ago         Up 2 hours                              kubelet
d1083e0c9ef1        rancher/hyperkube:v1.20.7-rancher1              "/opt/rke-tools/entr…"   2 hours ago         Up About an hour                        kube-scheduler
ba51a771e4dd        rancher/hyperkube:v1.20.7-rancher1              "/opt/rke-tools/entr…"   2 hours ago         Up 9 minutes                            kube-controller-manager
```

If we reboot the node, once it comes up, it is added back in the cluster as a worker node.
docker ps:
```
CONTAINER ID        IMAGE                        COMMAND             CREATED             STATUS              PORTS               NAMES
e18140a0a853        rancher/mirrored-pause:3.2   "/pause"            11 minutes ago      Up 11 minutes
         k8s_POD_canal-45hnb_kube-system_895cfacd-d9f4-4e27-ab16-c04e81bbd732_1
```

After sometime, the cluster goes into error state with the following logs in rancher server:
```
2021/06/07 17:31:12 [ERROR] error syncing 'c-bx4cm/machine-285t6': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
```

**Comment by anupama2501** [comment]
Verified on master-6b430f31afb9cfc5493f686279a97dd79c54ad88-head

**Scenario2 from above comments:**

1. Created an rke1 custom cluster from explorer - 3 nodes all roles.
2. Once the cluster is active, deleted one of the nodes and the docker ps has no containers running . 
3. Rebooted the node and see that the node is not added back as a worker node.

**Scenario3 from above comments:**

1. Create an rke1 custom cluster from the dashboard UI with 3 nodes all roles.
2. Once the cluster is up and active, removed two nodes and verified the docker ps has no containers running and when we reboot the nodes they are not added back to the cluster.
3. Now removed the remaining 1 node as well with all roles. All the docker running containers were removed. 
4. Rebooted the node and it was not added back as worker node

**Scenario4 - new**

1. Created an rke1 custom cluster from ember UI with 3 etcd nodes, 2 cp nodes, 3 worker nodes
2. Removed 1 etcd node and verified all the containers from the node were removed and once we reboot, it is not added back as worker node
3. Removed 1 worker node and verified all the containers from the node were removed and on rebooting it was not added back
4. Verified the same step as above with 1 control plane node.
