### ISSUE TITLE
When upgrading Service, link and description are not saving

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2655]
Version - master with newest reskin UI

Steps:
1.  Create a Stack
2.  Add a service
3.  Upgrade service and add a link, change the description, add a label.
4.  Finish upgrade
5.  View summary or detail information for Service

Results:
Label saved, but the link and description did not.

Expected:
Link and Description information to save.

**Comment by vincent99** [comment]
Removed name/description on upgrade because they're not part of what's sent for an upgrade, and fixed servicelinks.

**Comment by tfiduccia** [comment]
Version - Master with reskin UI
Verified fixed
