### ISSUE TITLE
"rke-network-plugin-deploy-job" fails to deploy successfully for a 1.15.11-rancher1-0 cluster with calico on rancher server upgrade or fresh install.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#26551]
Steps to reproduce the problem:

Scenario 1:
Rancher server version - `v2.2.11-rc3`
Deploy `1.15.11-rancher1-0` cluster  with calico network.

Upgrade to Rancher server version - `v2.3.3`

Cluster stuck in "updating" state which is expected since we dont have the updated KDM.

Update KDM to point to `dev-v2.3` branch.

Cluster gets to "active" state but "rke-network-plugin-deploy-job" fails to deploy successfully

<img width="523" alt="Screen Shot 2020-04-07 at 9 53 45 PM" src="https://user-images.githubusercontent.com/4266958/78745892-50cdda00-791a-11ea-86e4-6286d3707972.png">

Pods are in terminated state.
```
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrole.rbac.authorization.k8s.io/calico-node unchanged
clusterrolebinding.rbac.authorization.k8s.io/calico-node unchanged
configmap/calico-config unchanged
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org unchanged
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org unchanged
serviceaccount/calico-kube-controllers unchanged
serviceaccount/calico-node unchanged
deployment.apps/calico-kube-controllers unchanged
The DaemonSet "calico-node" is invalid: spec.template.spec.initContainers[2].image: Required value
```

Scenario 2:
Deploy `1.15.11-rancher1-0` cluster  with calico network.( Set this version of k8s by editing the cluster using "Edit as Yaml".

Cluster is stuck in "provisioning" state.

<img width="952" alt="Screen Shot 2020-04-07 at 9 58 15 PM" src="https://user-images.githubusercontent.com/4266958/78746131-e79a9680-791a-11ea-93fb-f14eb447bec3.png">

```
2020/04/08 04:45:28 [INFO] cluster [c-xnwdh] provisioning: [sync] Syncing nodes Labels and Taints
2020/04/08 04:45:28 [INFO] cluster [c-xnwdh] provisioning: [sync] Successfully synced nodes Labels and Taints
2020/04/08 04:45:28 [INFO] cluster [c-xnwdh] provisioning: [network] Setting up network plugin: calico
2020/04/08 04:45:28 [INFO] cluster [c-xnwdh] provisioning: [addons] Saving ConfigMap for addon rke-network-plugin to Kubernetes
2020/04/08 04:45:28 [INFO] cluster [c-xnwdh] provisioning: [addons] Successfully saved ConfigMap for addon rke-network-plugin to Kubernetes
2020/04/08 04:45:28 [INFO] cluster [c-xnwdh] provisioning: [addons] Executing deploy job rke-network-plugin
2020/04/08 04:46:04 [ERROR] cluster [c-xnwdh] provisioning: Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system
2020/04/08 04:46:04 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/04/08 04:46:04 [ERROR] ClusterController c-xnwdh [cluster-provisioner-controller] failed with : Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system
```

**Comment by jiaqiluo** [comment]
The following checks are done:

- run rancher v2.2.11-rc3
- add the following clusters
	- k8s 1.15.11-rancher1-0 with Calico, 1 control 1 etcd, 2 workers 
	- k8s 1.15.11-rancher1-0 with Canal, 1 control 1 etcd, 2 workers 
	- k8s 1.14.10-rancher1-0 with Calico, 1 control 1 etcd, 2 workers 
	- k8s 1.14.10-rancher1-0 with Canal, 1 control 1 etcd, 2 workers 
- run pre-upgrade tests 
- log in any node to get the image of rke-tools -> `rancher/rke-tools:v0.1.50` for all clusters 
- check the cni versions:
	- k8s 1.14.10-rancher1-0: `rancher/calico-cni:v3.4.0` `rancher/calico-node:v3.4.0`
	- k8s 1.15.11-rancher1-0: `rancher/calico-cni:v3.7.4` `rancher/calico-node:v3.7.4`
- Upgrade Rancher to v2.3.3 with custom KDM pointing to `dev-v2.3`
- no existing clusters go to the upgrade state 
- run post-upgrade tests
- log in any node to get the image of rke-tools -> the same as before `rancher/rke-tools:v0.1.50` 
- upgrade k8s version to `rancher1-1`
- run post-upgrade tests
- check the cni versions:
	- k8s 1.14.10-rancher1-0: `rancher/calico-cni:v3.4.0` `rancher/calico-node:v3.4.0`
	- k8s 1.15.11-rancher1-0: **New images** `rancher/calico-cni:v3.13.0` `rancher/calico-node:v3.13.0`
- log in any node to get the image of rke-tools -> **new image** `rancher/rke-tools:v0.1.52`
