### ISSUE TITLE
Cannot connect to clusters deployed by 2.4.0 directly but only through Rancher

### ISSUE THREAD

**Issue by vitobotta** [rancher/rancher#26555]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug?

**Steps to reproduce (least amount of steps as possible):**
I have tested this with several throaway clusters. Since I upgraded to 2.4.0, when I create a cluster and download the kubeconfig, I can connect to the cluster only with the context that proxies the connection through Rancher, but none of the contexts in the kubeconfig for the masters work. 

**Result:**
Whenever I try to connect to the cluster directly, I get this:

```
error: You must be logged in to the server (Unauthorized)
```

**Other details that may be helpful:**
I can connect to the clusters via Rancher just fine.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.4.0
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Deployed with a node driver for Hetzner Cloud
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Cloud, no difference regardless of the model/size
- Kubernetes version (use `kubectl version`):
1.17.4

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```

Thanks in advance for any help.

**Comment by vitobotta** [comment]
In the logs for the kube-apiserver container on a master I see these:

```
E0408 17:34:35.196992       1 webhook.go:109] Failed to make webhook authenticator request: the server has asked for the client to provide credentials
E0408 17:34:35.197062       1 authentication.go:104] Unable to authenticate the request due to an error: [invalid bearer token, the server has asked for the client to provide credentials]
```

**Comment by jiaqiluo** [comment]
The bug is reproduced in Rancher v2.4.2, single install 

Steps:
- add a cluster 
- get the kubeconfig file from Rancher UI
- confirm that we can use the config file to access to the cluster via command line, by default it connects to Rancher first then the cluster 
- edit the kubeconfig file to  switch to use another context which connects to the cluster directly 
```
➜ kubectl config get-contexts
CURRENT   NAME                             CLUSTER                          AUTHINFO     NAMESPACE
          1-15-canal                       1-15-canal                       user-kb87w
*         1-15-canal-jiaqi-1-15-canal-c1   1-15-canal-jiaqi-1-15-canal-c1   user-kb87w
```
- see the following error 
```
➜ export KUBECONFIG=./kube_config_rancher-cluster.yml
➜ kubectl get nodes
error: You must be logged in to the server (Unauthorized)
```

**Comment by vitobotta** [comment]
Thanks @jiaqiluo ! I thought it was just me even though I tried with several clusters. :)

**Comment by dramich** [comment]
@vitobotta how is rancher deployed? Are you using a self-signed cert or something like letsencrypt? Can you provide rancher logs?

**Comment by dramich** [comment]
QA: To reproduce this run rancher 2.4.2 and create three clusters. The first cluster created should not have any issues. The fastest way to check is to first push the `get kubeconfig` in the UI then run kubectl from the UI and run `kubectl get clusterauthtokens.cluster.cattle.io -A`.  In a working cluster there will be a token, in the other clusters there will not be one when this process is repeated for all clusters.

**Comment by jiaqiluo** [comment]
@dramich Can you backport it to the master branch? The same issue exists in master-head, too

**Comment by jiaqiluo** [comment]
the bug fix is validated in master-head 419b87a70 and v2.4-head 9afe68b83


added 3 clusters in the setup and the following 2 checks were done on the clusters:
- `kubectl get clusterauthtokens.cluster.cattle.io -A` returns a token
- can switch the context and access to the cluster in the command line

**Comment by vitobotta** [comment]
@jiaqiluo Something weird happened.... yesterday I created a new cluster to test some stuff, and surprise... I can connect to the cluster directly. I'm still on 2.4.0 so I have not upgraded or changed anything. This is the first time this works since I upgraded to 2.4.0, after having the same authentication issue with about 10 test clusters. How is this possible?

**Comment by dramich** [comment]
The first cluster through the controllers will work, as will older clusters that already have the tokens in the downstream clusters.

**Comment by vitobotta** [comment]
Hi @dramich - I answered it on Slack but just in case.... this was the 11th test cluster in a row since I upgraded to 2.4.0. And the only one I can connect to directly. What do you mean by "the first cluster through the controllers"? Thanks!
