### ISSUE TITLE
Shortened Helm 3 Version value needs to display helm 3 icon 

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#26560]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/enhancement

**Steps to reproduce (least amount of steps as possible):**
Changes introduced in 2.4.X for helm 3 were too strict around naming (see related issue)
Helm 3 is now allowed to be "helm_v3" or "v3"

**Result:**
Helm 3 Icon is not showing up when using the shortened "v3" since we previously discussed only doing a check for "helm_v3" as the helmversion value

**Related**
https://github.com/rancher/rancher/issues/26450

**Comment by brendarearden** [comment]
https://github.com/rancher/rancher/pull/26531

**Comment by rancher-max** [comment]
#### Validated using both ui-index `latest2` and `latest-2.4` in `master-2750-head` and `v2.4-2478-head` respectively

The Icon shows up correctly:
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/55997940/79148282-16c96180-7d7a-11ea-9f22-744468a8b116.png">
```
ID               NAME             URL                                    BRANCH    KIND       HELMVERSION
foo              foo              https://git.rancher.io/helm3-charts    master    helm       v3
foo2             foo2             https://git.rancher.io/helm3-charts    master    helm       v2
helm3-library    helm3-library    https://git.rancher.io/helm3-charts    master    helm:git   helm_v3
library          library          https://git.rancher.io/charts          master    helm:git   
system-library   system-library   https://git.rancher.io/system-charts   dev       helm:git   
```
