### ISSUE TITLE
Not support OpenStack cloud provider on v2.3.6?

### ISSUE THREAD

**Issue by jaggerwang** [rancher/rancher#26573]
Not found OpenStack infrastructure provider when create cluster on version 2.3.6. I'm running rancher server by docker on a single node which is a OpenStack virtual machine.

![image](https://user-images.githubusercontent.com/1255011/78863186-8b935780-7a6b-11ea-81bc-4f30c7421cfa.png)

**Comment by longtds** [comment]
You can manually open the Openstack driver.
![image](https://user-images.githubusercontent.com/20021501/78872905-8c80b500-7a7c-11ea-9e18-3d9fde1a8be9.png)

**Comment by jaggerwang** [comment]
Thansk!
