### ISSUE TITLE
[Forwardport] - Project owner cannot see PVC in 2.4.0

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#26582]
Forward port for - https://github.com/rancher/rancher/issues/26416

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `419b87a70`**

- Project owner is able to list the following
```
- Persistent Volume
- persistenVolumeClaim
- configMap
- statefulSet
- cronJob
- daemonSet
- HPA
```
