### ISSUE TITLE
[Forwardport] - OPA gatekeeper page unable to load in HA set up with ingress pointing to 8080/8443

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#26581]
Forward-port for - https://github.com/rancher/rancher/issues/26430

**Comment by khushboo-rancher** [comment]
HA setup in master-head ```419b87a70```with ingress pointing to 8443 fails to launch properly. The login is redirected without port.

Steps:
HA set up is brought up with 8080/8443 port using helm install 
``` helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=rancher-server --version 2.4.2 --set rancherImageTag=master-head```
https://rancher-server:8443 page doesn't show set password page on launching first time.
Below requests returns 401
```https://rancher-server:8443/v3/users?me=true
https://rancher-server:8443/v3/
https://rancher-server:8443/v3/settings?limit=-1&sort=name
```

Login request is sent without port 8443 ```https://rancher-server/v3-public/localProviders/local?action=login```

**Comment by khushboo-rancher** [comment]
Verified in master-2777-head c49a121fc , OPA gatekeeper page works fine. User is able to launch dashboard and enable OPA gatekeeper .
