### ISSUE TITLE
Adding a worker node to a custom cluster triggered rke reconcile 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#26588]
OS: Ubuntu 18.04
Steps :

1. Deploy a custom cluster in 2.0.10 with k8s 1.11.6-rancher1-1 and run pre upgrade checks
2. Upgrade from rancher v2.0.10 to rancher v2.2.9 and run post upgrade checks
3. Upgrade to rancher 2.2.11 and run post upgrade checks
4. Upgrade k8s to 1.14.10 and run post upgrade checks and also add a node
5. Upgrade to 2.4.2 and run post upgrade checks and add a node

After node addition, cluster update was triggered. A bind mount change for the kubelet was observed:
Rancher server logs below:
```
2020/04/09 21:59:47 [INFO] Provisioning cluster [c-dkzqr]
2020/04/09 21:59:47 [INFO] Updating cluster [c-dkzqr]
2020/04/09 21:59:51 [INFO] Handling backend connection request [c-dkzqr:m-db790889d42b]
2020/04/09 21:59:51 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2020/04/09 21:59:52 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:44329
2020/04/09 21:59:52 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/04/09 21:59:52 [INFO] Updated cluster [c-dkzqr] with node version [1]
2020/04/09 21:59:52 [INFO] Provisioned cluster [c-dkzqr]
2020/04/09 21:59:53 [INFO] checking cluster [c-dkzqr] for worker nodes upgrade
2020/04/09 21:59:53 [INFO] binds changed for [kubelet] old: [/etc/kubernetes:/etc/kubernetes:z /etc/cni:/etc/cni:rw,z /opt/cni:/opt/cni:rw,z /var/lib/cni:/var/lib/cni:z /var/lib/calico:/var/lib/calico:z /etc/resolv.conf:/etc/resolv.conf /sys:/sys:rprivate ::rw,rslave,z /var/lib/kubelet:/var/lib/kubelet:shared,z /var/lib/rancher:/var/lib/rancher:shared,z /var/run:/var/run:rw,rprivate /run:/run:rprivate /etc/ceph:/etc/ceph /dev:/host/dev:rprivate /var/log/containers:/var/log/containers:z /var/log/pods:/var/log/pods:z /usr:/host/usr:ro /etc:/host/etc:ro] new [/etc/kubernetes:/etc/kubernetes:z /etc/cni:/etc/cni:rw,z /opt/cni:/opt/cni:rw,z /var/lib/cni:/var/lib/cni:z /var/lib/calico:/var/lib/calico:z /etc/resolv.conf:/etc/resolv.conf /sys:/sys:rprivate /var/lib/docker:/var/lib/docker:rw,rslave,z /var/lib/kubelet:/var/lib/kubelet:shared,z /var/lib/rancher:/var/lib/rancher:shared,z /var/run:/var/run:rw,rprivate /run:/run:rprivate /etc/ceph:/etc/ceph /dev:/host/dev:rprivate /var/log/containers:/var/log/containers:z /var/log/pods:/var/log/pods:z /usr:/host/usr:ro /etc:/host/etc:ro]
2020/04/09 21:59:53 [INFO] cluster [c-dkzqr] worker-upgrade: updated cluster for upgrading: [2] 

```

**Comment by mrajashree** [comment]
Can we also test upgrade from 2.2.11 to 2.3.6 first? So 2.2.11->2.3.6->2.4.2?  
If this issue is repro'd for 2.2.11 to 2.3.6 that will help with debugging

**Comment by soumyalj** [comment]
Tested with upgrade from v2.0.10 -> v2.2.9->**v2.2.11->v2.3.6-v2.4.2**

1. Deploy a cluster in v2.0.10 with k8s 1.11.6-rancher1-1 using certs from a recognized CA. 
**Cluster config used**: 1 control node, 3 etcd nodes and 3 worker nodes
2. Upgrade from rancher v2.0.10 to rancher v2.2.9 
3. Upgrade to  rancher 2.2.11-rc2 and run post upgrade checks
4. Upgrade k8s to 1.14.10 and run post upgrade checks and also add a node
5. Upgrade to 2.3.6 and run post upgrade checks  and add a node
6. Upgrade from v2.3.6 to v2.4.2 . (The cluster went to updating state for a short time).
 Run post upgrade checks and add a node
After upgrading to v2.4.2, logged into each of the nodes and verified that kubelet was running with no restarts. Verified through docker inspect that Restart count = 0
```
      "Name": "/kubelet",
        "RestartCount": 0,

```
Also, verified that all pods in the system project are active.

**Comment by soumyalj** [comment]
Tested with upgrade from v2.2.11 to v2.4.2

1. Created a DO cluster in Rancher v2.2.11 with K8s v1.14.10-rancher1-0. Run pre-upgrade tests
2. Upgrade Rancher to v2.4.2. Run post upgrade tests. 
3. Add a new worker node to the cluster and it succeeds. 
The following logs are observed :
```
2020/04/15 19:23:01 [INFO] Provisioning node soumyaworker5 done
2020/04/15 19:23:01 [INFO] Generating and uploading node config soumyaworker5
2020/04/15 19:23:01 [ERROR] NodeController c-jfbsd/m-rdr9t [rke-worker-upgrader] failed with : getNodePlan error for node [m-rdr9t]: failed to find plan for abcd
2020/04/15 19:23:01 [ERROR] NodeController c-jfbsd/m-rdr9t [rke-worker-upgrader] failed with : getNodePlan error for node [m-rdr9t]: failed to find plan for abcd
2020/04/15 19:23:02 [INFO] Handling backend connection request [c-jfbsd:m-rdr9t]

2020/04/15 19:23:02 [INFO] Provisioning cluster [c-jfbsd]
2020/04/15 19:23:02 [INFO] Updating cluster [c-jfbsd]
2020/04/15 19:23:06 [ERROR] NodeController c-jfbsd/m-rdr9t [rke-worker-upgrader] failed with : getNodePlan error for node [m-rdr9t]: failed to find plan for abcd
2020/04/15 19:23:07 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:43447
2020/04/15 19:23:07 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/04/15 19:23:07 [INFO] Updated cluster [c-jfbsd] with node version [1]
2020/04/15 19:23:07 [INFO] Provisioned cluster [c-jfbsd]
2020/04/15 19:23:07 [INFO] checking cluster [c-jfbsd] for worker nodes upgrade

```
@mrajashree : In the logs above, after a node is added, we observe that cluster is provisioned and goes to updating state. Is this expected as part of node addition ?

**Comment by kinarashah** [comment]
@soumyalj To clarify, both upgrades to 2.4.2 (from 2.2.11 and from 2.3.6) result into cluster always going to updating for a short time + adding a new worker also puts the cluster into updating?

**Comment by soumyalj** [comment]
@kinarashah : Yes, this is what I observed during my testing.

**Comment by kinarashah** [comment]
This behavior has always been present, and I don't see it as a bug. Confirmed in rancher server versions 2.2.10, 2.3.6 and 2.4.2,

On adding a worker node in custom cluster, logs would show cluster undergoing provisioning again. I think this is similar to adding a node via node pool, which also results into cluster getting provisioned and updated in the logs. 

```
2020/04/20 20:55:13 [INFO] Handling backend connection request [c-c65mb:m-7dd7e4b58630]
2020/04/20 20:55:13 [INFO] Provisioning cluster [c-c65mb]
2020/04/20 20:55:13 [INFO] Updating cluster [c-c65mb]
2020/04/20 20:55:18 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10313
2020/04/20 20:55:18 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/04/20 20:55:18 [INFO] Provisioned cluster [c-c65mb]
```

**Comment by soumyalj** [comment]
Yes, can be closed.
