### ISSUE TITLE
[Backport 2.3] Monitoring: Pod Usage (CPU/Memory) is doubled

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#26594]
https://github.com/rancher/rancher/issues/25539

**Comment by deniseschannon** [comment]
Monitoring v0.1.0 is now available in `dev-v2.3`, which is what is `v2.3-head` is pointing to.

**Comment by jiaqiluo** [comment]
The bug fix is validated in v2.3-head a0c372a82

Steps:
- run Rancher v2.3.5 single install
- add an ec2 cluster
- enable the cluster monitoring
- deploy a workload with the image `progrium/stress`, set Command to `--cpu 1` and set the CPU limit to 150
- check the pod metrics in Grafana (from the pod page)

Results:
- the values in the metrics are correct, and the current does not exceed the limit. 
<img width="1226" alt="Screen Shot 2020-04-16 at 1 32 36 PM" src="https://user-images.githubusercontent.com/6218999/79504350-a293f580-7fe7-11ea-9a72-1dc9e8dfaf30.png">

**Comment by DrZoidberg09** [comment]
I am running version 2.7.5 on arm64 and there it still exists. Cluster metrics show exactly double the memory than grafana.
