### ISSUE TITLE
[CIS] user applications with matching kubernetes binary names interfere with CIS Scans

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#26598]
Create a sample workload with a binary name `apiserver` and deploy it in the cluster. When a CIS scan is launched, the worker node is detected as a master node which causes the master checks to run on this node causing failures.

Symptoms of the problem: The CIS scan will be stuck in "Running" state.

Workaround: Rename the application binary to something else and redeploy.

gzrancher/rancher#10265

gzrancher/rancher#9444

**Comment by spencergilbert** [comment]
@leodotcloud would the easiest fix be to just grep on `kube-apiserver` ?

**Comment by leodotcloud** [comment]
It's pretty easy to fix for RKE clusters as we know the binary name is for sure `kube-apiserver`, but in long run when we want to support imported clusters, we might run into a similar problem.

**Comment by leodotcloud** [comment]
Doing this on a worker node should probably repro the issue 

```
touch /usr/local/bin/apiserver
chmod +x /usr/local/bin/apiserver
echo "/bin/bash" >> /usr/local/bin/apiserver
echo "sleep infinity" >> /usr/local/bin/apiserver
/usr/local/bin/apiserver
```

**Comment by leodotcloud** [comment]
Having similar issues in another customer setup with the `etcd` binary name.

```
# ps -ef|grep etcd
root 11758 2387 0 Feb20 ? 18:34:19 /usr/local/bin/px-etcd start --port 9011
```

**Comment by nagyclaudiu83** [comment]
I am running into a similar issue in a cluster where "CrunchyData Postgres Operator" is deployed. 

The operator is running containers with following names :
`k8s_event_postgres-operator-...`
`k8s_scheduler_postgres-operator-...`
`k8s_operator_postgres-operator-...`
`k8s_apiserver_postgres-operator-...`
`k8s_POD_postgres-operator-...`

And one of the process is:
`daemon   23272 23259  0 13:56 ?        00:00:00 /opt/cpm/bin/pgo-scheduler`

The error in the CIS Scan is:
`level=info msg="found error file"`
`level=fatal msg="error summarizing: \nfailed to get a set of executables needed for tests: unable to detect running programs for component \"scheduler\"\n"`

**Comment by sowmyav27** [comment]
On 2.4.5 - reproduced the issue

- Deploy a cluster.
- On a worker node run the following commands
```
touch /usr/local/bin/apiserver
chmod +x /usr/local/bin/apiserver
echo "#!/bin/bash" >> /usr/local/bin/apiserver
echo "sleep infinity" >> /usr/local/bin/apiserver
/usr/local/bin/apiserver
```
- Run a CIS 1.4 permissive on the cluster. The scan is stuck in `Running` state.
- The issue happens when a binary of name `etcd` is running in the node.


@prachidamle Could we NOT include the full path when checking for the process and use “ends with” full name of the process including / like “/kube-apiserver” . We would also need to fix this for all processes we query for as part of CIS Scan. (two of the three gz tickets call out `scheduler`)

**Comment by prachidamle** [comment]
@sowmyav27 thanks for reproducing. Does the current PR fixes it for kube-apiserver and etcd?

**Comment by sowmyav27** [comment]
@prachidamle Validated on 2.4-head `fdbd0245a`

- Deploy a cluster.
- On a worker node run the following commands

```
touch /usr/local/bin/apiserver
chmod +x /usr/local/bin/apiserver
echo "/bin/bash" >> /usr/local/bin/apiserver
echo "sleep infinity" >> /usr/local/bin/apiserver
/usr/local/bin/apiserver
```
- Run a CIS 1.4 permissive on the cluster. Scan runs fine and a report is generated
- when a binary of name etcd is running in the node, Run a CIS 1.4 permissive on the cluster. Scan runs fine and a report is generated

**Comment by leodotcloud** [comment]
One more thought: Check if it's possible to use Downward API to determine the role of the node to do away with these checks?

https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api

**Comment by prachidamle** [comment]
@sowmyav27 The new system-chart tag has been release for release/v2.4. For master, @maggieliu confirmed that we dont need another PR for dev-v2.5 branch as we will be dropping that branch moving forward for 2.5/master.

**Comment by sowmyav27** [comment]
**Validated on 2.4-head - commit id: `66c7e285e`**

- Deploy a cluster.
- On a worker node run the following commands

```
touch /usr/local/bin/apiserver
chmod +x /usr/local/bin/apiserver
echo "/bin/bash" >> /usr/local/bin/apiserver
echo "sleep infinity" >> /usr/local/bin/apiserver
/usr/local/bin/apiserver
```

- Run a CIS 1.4 permissive on the cluster. The scan finishes as expected and report is generated
- The above behavior is seen when a binary named `kube-apiserver` is also run 
- When binaries named `etcd` and `kube-apiserver-test` are run, the CIS scan is seen in `Running` state. No report is generated.

**Comment by prachidamle** [comment]
yes this fix as mentioned in the PR is a patch fix to address the reported customer problems; we definitely will need another way of figuring out role of a node.

**Comment by prachidamle** [comment]
@nagyclaudiu83 A separate issue has been logged for the problem you are seeing, we could not reproduce it. Will you be able to provide some more steps to reproduce?https://github.com/rancher/rancher/issues/28285

**Comment by maggieliu** [comment]
QA validation completed
