### ISSUE TITLE
Rancher_V2.3.5 Alermanager的secret配置文件alertmanager-cluster-alerting更新后被覆盖，导致自定义报警主题和报警主体模板无法生效

### ISSUE THREAD

**Issue by ruanqj** [rancher/rancher#26595]
Alermanager的secret配置文件alertmanager-cluster-alerting更新后被覆盖，导致自定义报警主题和报警主体模板无法生效

**Comment by loganhz** [comment]
thanks for the report.

Close in favor of https://github.com/rancher/rancher/issues/23140

Please add `rancher2` to join Rancher WeChat group if you would like to ask question in Chinese
