### ISSUE TITLE
Deleting a label on a node through the API does not delete the labels

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26604]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Add a label to a node template - say DO 
- Bring up a cluster - 1 node all roles using this node template
- click on `View in API` of the node
- Delete the label. Send request.
- the label is NOT deleted.

**Expected Result:**
Label should be deleted

**Other details that may be helpful:**

- When the user does a delete of the label from the API the second time, the label is deleted.
- The label gets deleted the first time, when the action is performed through the UI.
- Behavior is the same for a node with all roles/worker only node

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.17.4
```

**Comment by deniseschannon** [comment]
@sowmyav27 isn't this a duplicate of https://github.com/rancher/rancher/issues/15825?

**Comment by sowmyav27** [comment]
Duplicate issue.
Closing this one
