### ISSUE TITLE
Clusters fail to come up with k8s 1.13 in 2.3.x

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26608]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. bring up a cluster with calico network and k8s version 1.13.12-rancher2-1
2. Clusters fail to come up.

**Actual Result:**
Error seen: `Can not find RKE state file: open /var/lib/rancher/management-state/rke/rke-036930269/cluster.rkestate: no such file or directory`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.1 and 2.3.0
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.13.12-rancher2-1
```

**Comment by superseb** [comment]
Actual error for this situation is:

```
2020/04/16 12:34:05 [ERROR] cluster [c-rmn42] provisioning: Failed to validate cluster: v1.13.12-rancher2-1 is an unsupported Kubernetes version and system images are not populated: calico controllers image is not populated
```

**Comment by sowmyav27** [comment]
Change the KDM branch to `dev-v2.3`

Refresh of Kubernetes Metadata gives response
**On 2.3.1**
```
null
{"baseType":"error","code":"ServerError","message":"no template found for k8sVersion v1.12.7-rancher1-4 plugin nodelocal","status":500,"type":"error"}
```
**On 2.3.0, response:**
```
null
{"baseType":"error","code":"ServerError","message":"no template found for k8sVersion v1.12.10-rancher1-1 plugin nodelocal","status":500,"type":"error"}
```

**Comment by sowmyav27** [comment]
**Change the KDM branch to `dev-v2.3` on rancher v 2.3.0 and 2.3.1**

Clusters deployed with all applicable k8s version including `v1.13.12-rancher2-1` 

Workload and ingress are deployed successfully.
