### ISSUE TITLE
Incorrect disk space reported for centos 7.1

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2661]
Tested with build from master - Nov 12
rancher-server is running on a ubuntu VM.
Added Cent OS host with 10 GB disk space.

Disk space reported for the host in incorrect in "Hosts" page:

<img width="320" alt="screen shot 2015-11-12 at 2 49 33 pm" src="https://cloud.githubusercontent.com/assets/4266958/11133754/b9fbef8e-894c-11e5-9d29-2d2add2c01a0.png">

In "Hosts" details page , we see 2 entries for storage for pool and dev/sda1:
<img width="365" alt="screen shot 2015-11-12 at 2 43 36 pm" src="https://cloud.githubusercontent.com/assets/4266958/11133781/effc149c-894c-11e5-9799-e31c6e343c87.png">

**Comment by clemenko** [comment]
Looks to be working with v0.46-rc1
![screen shot 2015-11-12 at 6 36 29 pm](https://cloud.githubusercontent.com/assets/3177276/11134648/798f1c44-896c-11e5-88cb-0929cdbebc7a.jpg)

**Comment by cloudnautique** [comment]
On the main host page is it showing ~126gb?

**Comment by clemenko** [comment]
Nope 18gb.. like it should.

**Comment by cloudnautique** [comment]
Hmm... are you using device mapper?

**Comment by sangeethah** [comment]
@clemenko @cloudnautique my bad. I was actually testing with CentOS 1.7.
Updated the bug description accordingly.

**Comment by clemenko** [comment]
I am using the default coreos storage driver. In a few I can build another cluster to test.

**Comment by clemenko** [comment]
Yup looks good. 
![screen shot 2015-11-12 at 7 36 45 pm](https://cloud.githubusercontent.com/assets/3177276/11135612/c184322a-8974-11e5-8379-48ad9fd2d2ba.jpg)

**Comment by deniseschannon** [comment]
Still an issue in v0.51.0. Started a CentOS 7.1 box with 20GB. 

Shows only 10GB in the hosts page.

<img width="298" alt="screen shot 2015-12-29 at 10 31 30 am" src="https://cloud.githubusercontent.com/assets/11410997/12039716/8173ae6e-ae17-11e5-8f23-53df17458327.png">

**Comment by deniseschannon** [comment]
Verified with v0.51.0 that this is working correctly.
