### ISSUE TITLE
[UI] Enable NSGs shared between multiple machines changes

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#26619]
After changes from https://github.com/rancher/machine/pull/77 are merged, we need a new section within the Azure node template Network settings (shown below) for supplying an NSG.

![Screen Shot 2020-04-13 at 2 53 19 PM](https://user-images.githubusercontent.com/13127443/79164746-864d4a00-7d96-11ea-8886-357a76bacfbe.png)

Some context:
From the backend perspective, users should now be able to supply a value for a `nsg` flag for node templates that generates the following behavior:
1. If `nsg == ""`, we default to the legacy case and create one NSG per node that is provisioned
1. if `nsg == <arm_resource_identifier>`, we attach every node that is created from the node template to the NSG referenced by the provided [ARM resource identifier](https://docs.microsoft.com/en-us/rest/api/resources/resources/getbyid) (i.e. a "pooled" NSG). If the NSG does not currently exist, we create it only if the ARM resource identifier provided is within the resourceGroup defined in the node template.
1. If `nsg = <name>`, where the name is the name of a networkSecurityGroup, we assume it refers to an NSG within node template's resourceGroup and subscription and default to option 2.

The requested UI changes:
Ideally, when a user loads up a node template and scrolls down to the Network settings of the node, they should see a section that contains a radio button with three text fields below (corresponding to `Subscription`, `Resource Group`, `Name`).

The radio button should have the following three options:
1. `Create a Rancher managed NSG per node`
1. `Create or use a Rancher managed NSG for all nodes`
1. `Use an existing NSG for all nodes`

All three text fields should be disabled if option 1 is chosen.
Only `Name` should be enabled if option 2 is chosen.
All three text fields should be enabled if option 3 is chosen.

If enabled, each text field should have its user input validated on submit according to the [naming rules and restrictions for Azure resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules).

On submit, the following should happen to the created / updated node template for each option, respectively (post validation of user input):
1. The `nsg` should be set to `""`
1. The `nsg` should be set to `"{Name}"`
1. The `nsg` should be set to `"/subscriptions/{Subscription}/resourceGroups/{Resource Group}/Microsoft.Network/networkSecurityGroups/{Name}"`

On reloading a node template based on the NSG value:
1. If the `nsg` is empty or nil (legacy case), the first radio button should be selected.
1. If the `nsg` does not contain a slash, the second radio button should be selected and `Name` should be set to the nsg field's contents.
1. If the `nsg` does contain a slash, the third radio button should be selected and the field's contents should be parsed into the `Subscription`, `Resource Group`, and `Name` fields.

If we want a default value for `Name` (in the case that we want providing a name for option 2 to be optional), I would suggest defaulting to `"rancher-<node_template_id>-firewall"`.

Feel free to reach out to me with any questions!

Needs API changes from: https://github.com/rancher/machine/pull/77

**Comment by aiyengar2** [comment]
re: https://github.com/rancher/machine/pull/77#issuecomment-625564555

```
It will be the user's responsibility to set up an existing NSG with the expected security rules.
```

Existing NSGs will ignore values in the `Open Ports` field, so the field should be disabled on the UI if that option is selected.

![Screen Shot 2020-05-18 at 2 44 53 PM](https://user-images.githubusercontent.com/13127443/82262641-23f7e400-9916-11ea-9237-fa1dd411ed7a.png)

**Comment by soumyalj** [comment]
Tested with master-head(1afaa4768) and v2.4-head(aae934198)
In the UI, Azure node template supports NSG field. 

![Screen Shot 2020-05-26 at 4 27 28 PM](https://user-images.githubusercontent.com/18536626/82959926-d6aaf080-9f6d-11ea-8a97-c758b0dab462.png)

The following use cases were tested:
- NSG field empty
 1. Create azure node template with NSG field empty. 
 2. Create azure cluster with the template. 
 3.   One NSG per VM was created and cluster was active and functional

- Provide NSG name(non existing) in the NSG field
 1. Create azure node template with a NSG name(non existing) in the NSG field
 2. Create azure cluster with the template. 
 3. Only one NSG was created per node pool using  the template
 4. Create multiple clusters using the same node template. The nodes will use the same NSG.
