### ISSUE TITLE
[Bug] Creating StorageClass with Longhorn provisioner is failing

### ISSUE THREAD

**Issue by meldafrawi** [rancher/rancher#26617]
Creating a StorageClass with Longhorn provisioner is using wrong provisioner name, set `allowVolumeExpansion` to `false`, and lacks parameters is supported by Longhorn driver 

We will need also to support adding more user customized parameters to support new parameter added in the future.

**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Create a StorageClass, Using Longhorn provisioner

**Result:**
StorageClass gets created with wrong provisioner `rancher.io/longhorn`  , so createing a PVC using that StorageClass will not result in creating a volume in Longhorn

**Other details that may be helpful:**
Current Longhorn StorageClass manifest with supported parameters

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
#  diskSelector: "ssd,fast"
#  nodeSelector: "storage,fast"
#  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"*/1 * * * *", "retain":1},
#                   {"name":"backup", "task":"backup", "cron":"*/2 * * * *", "retain":1,
#                    "labels": {"interval":"2m"}}]'
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by yasker** [comment]
One more thing: we want to make sure Rancher is compatible with Longhorn in the sense of new parameters. So we also want a customizable parameter list for Longhorn (like `custom` provider in StorageClass creation), in case Longhorn was upgraded to support more parameters in StorageClass. Users can find the key(name) of the parameter in Longhorn doc, which doesn't need to be hardcoded by Rancher.

**Comment by yasker** [comment]
Realized PV's parameter input model can be used for storage class here to allow customized parameters.

Some parameters might need multi-lines textbox though, e.g. `recurringJobs` as shown above.

<img width="666" alt="Screen Shot 2020-04-14 at 11 51 20 AM" src="https://user-images.githubusercontent.com/3344618/79262532-565d7f80-7e46-11ea-89a6-031bfa69107a.png">

**Comment by khushboo-rancher** [comment]
Verified in Rancher-v2.4 -head ```ba190e961``` Creation of StorageClass with longhorn provisioner is working but editing of StorageClass doesn't work.

Steps:
1. Create a Storage Class with longhorn provisioner giving below details
```
"parameters": {
"diskSelector": "ssd,fast",
"nodeSelector": "storage,fast",
"numberOfReplicas": "5",
"recurringJobs": "[{\"name\":\"snap\", \"task\":\"snapshot\", \"cron\":\"*/1 * * * *\", \"retain\":1},\n{\"name\":\"backup\", \"task\":\"backup\", \"cron\":\"*/2 * * * *\", \"retain\":1, \"labels\": {\"interval\":\"2m\"}}]",
"staleReplicaTimeout": "2880"
},
"provisioner": "driver.longhorn.io",
```
Provisioner is ```driver.longhorn.io``` as expected.
2. Go to edit view of the Storage class, It doesn't show the details as entered in step 1 but default values.
3. Click save it shows error and doesn't get saved.
<img width="1263" alt="Screen Shot 2020-04-15 at 4 15 32 PM" src="https://user-images.githubusercontent.com/60111667/79398287-29d46100-7f35-11ea-90b6-d012f89c3b5e.png">

**Comment by yasker** [comment]
@khushboo-rancher Kubernetes doesn't allow editing StorageClass parameters. That's another reason we want users to create a new StorageClass instead of modifying the default one.

**Comment by khushboo-rancher** [comment]
@yasker Should we remove edit option from StorageClass ?

**Comment by yasker** [comment]
They do allow changing for other parameters, like allowExpansion.

**Comment by khushboo-rancher** [comment]
Okay, so the issue here is if user creates StorageClass with modified values in parameters, UI in edit mode shows the default values for all parameters which is treated as changed values and doesn't allow to save the StorageClass.

Example.
1. StorageClass is created with diskSelector and nodeSelector.
2. StorageClass in edit mode shows ```diskSelector and nodeSelector``` as blank.
3. User changes the allowExpansion and clicked save button. It throws error as ```invalid: parameters: Forbidden```. This is because API request doesn't have ```diskSelector and nodeSelector``` now.

**Comment by yasker** [comment]
@khushboo-rancher we shouldn't allow editing on the provisioned specific parameters.

**Comment by khushboo-rancher** [comment]
Verified in master-head e1e4e8500 and 2.4-head 08d166215, creation and editing work fine.
1. Provisioner is ```driver.longhorn.io```. 
2. ```allowVolumeExpansion``` is true by default.
3.  All the required parameters are present 
```
"parameters": {
"diskSelector": "ssd,fast",
"nodeSelector": "storage,fast",
"numberOfReplicas": "5",
"recurringJobs": "[{\"name\":\"snap\", \"task\":\"snapshot\", \"cron\":\"*/1 * * * *\", \"retain\":1},\n{\"name\":\"backup\", \"task\":\"backup\", \"cron\":\"*/2 * * * *\", \"retain\":1, \"labels\": {\"interval\":\"2m\"}}]",
"staleReplicaTimeout": "2880"
},
"provisioner": "driver.longhorn.io",
```
