### ISSUE TITLE
Rancher_V2.3.5 Alermanager's secret configuration file alertmanager-cluster-alerting is overwritten after update, resulting in the failure of custom alarm themes and alarm body templates

### ISSUE THREAD

**Issue by ruanqj** [rancher/rancher#26611]
Alermanager's secret configuration file alertmanager-cluster-alerting is overwritten after update, resulting in the failure of custom alarm themes and alarm body templates

**Comment by loganhz** [comment]
Not supported yet.  https://github.com/rancher/rancher/issues/23140
