### ISSUE TITLE
chart: preventing user from deploying certain apps more than once in a cluster

### ISSUE THREAD

**Issue by yasker** [rancher/rancher#26627]
For certain system applications like Longhorn, one cluster can only install one copy of the app. We want to enforce that.

If we make sure the app's name cannot be changed, e.g. `longhorn-system`, then we can ensure that one cluster can only have one Longhorn installed. Otherwise, Rancher will error out with `apps.project.cattle.io "longhorn-system" already exists`.

**Comment by yasker** [comment]
@deniseschannon

**Comment by sowmyav27** [comment]
**Verified on master- latest - commit id:  `1ccffeb09` ui tag: latest2**

- Deploy longhorn app
- Deploy another longhorn app
- Error seen on the UI

```
apps.project.cattle.io "longhorn-system" already exists
```
