### ISSUE TITLE
[2.2.11] 503 Service Temporarily Unavailable nginx-ingress

### ISSUE THREAD

**Issue by tomashapl** [rancher/rancher#26621]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

I am not able to forward traffic to container via:

![image](https://user-images.githubusercontent.com/7850592/79203477-60c64c00-7e3b-11ea-9a57-c56bb06877d3.png)

I've already created loadbalancer for my workload:

![image](https://user-images.githubusercontent.com/7850592/79203538-789dd000-7e3b-11ea-8b42-48b5a2ec7612.png)

Yaml looks:

![image](https://user-images.githubusercontent.com/7850592/79203714-b6025d80-7e3b-11ea-999e-b757a84dcf79.png)

and log from ingress-controller:

```
W0414 08:34:43.942485 8 controller.go:753] Error obtaining Endpoints for Service "default/ingress-4da44d2d84d76ba697bd9af3c8352a50": no object matching key "default/ingress-4da44d2d84d76ba697bd9af3c8352a50" in local store
```

**Result:**

![image](https://user-images.githubusercontent.com/7850592/79203896-fd88e980-7e3b-11ea-9147-44908aa3e665.png)

So the ingress-controller catch the traffic but didn't provide correct container.

Am I missing something ?

**Other details that may be helpful:**

**Environment information**
- Rancher version `rancher/rancher:2.2.11`
- Installation option `single install - docker image`

**Cluster information**
- Cluster type `Custom`
- Machine type `metal` and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by tomashapl** [comment]
I had issues with `cattle-cluster-agent` which was not deploy ingrees-xxxxxx

**Comment by Metrakit** [comment]
Hi @tomashapl I have the same issue from a fresh install of Rancher with Docker. Did you find a solution ?

**Comment by edgars** [comment]
Getting the same in CentOS 8 kind of the same versions or rancher.

**Comment by cxgreat2014** [comment]
Getting the same in Ubuntu 18.04 kind of the same versions or rancher.

**Comment by wedi** [comment]
Unfortunately, I am experiencing this as well when following the quickstart guide.
https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/

**Comment by VladimirTambovtsev** [comment]
I got this error after setting up cluster on rancher using this terraform quickstart.
https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/amazon-aws-qs/

**Comment by Gallardo994** [comment]
Same issue in our cluster. ClusterIP doesn't seem to provide any addresses whatsoever. A workaround is to create service manually and use label selector.
