### ISSUE TITLE
cattle-cluster-agent memory growing in idle Rancher v2.4.2 k3s cluster

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#26633]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Install rancher on k3s cluster with 2 server nodes.
2. Enable monitoring
3. Wait. Don't need to add clusters or deploy any workloads. Let the cluster sit idle.

**Result:**
cattle-cluster-agent appears to be leaking memory. Memory graph from Grafana:
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/468462/79297569-6485bd00-7e93-11ea-8e50-841b65d41843.png">

**Other details that may be helpful:**
Same cluster that is having rancher memory leak mentioned in https://github.com/rancher/rancher/issues/26577

Agent has been running a little over 5 days:
```
root@ip-10-100-105-33:~# kubectl get pod -n cattle-system
NAME                                   READY   STATUS    RESTARTS   AGE
cattle-cluster-agent-66fc4dbdb-dt2tg   1/1     Running   0          5d5h
cattle-node-agent-67rdd                1/1     Running   0          5d5h
cattle-node-agent-rzrjk                1/1     Running   0          5d4h
```

Memory heap:
[cattle-cluster-agent-66fc4dbdb-dt2tg-profile2.gz](https://github.com/rancher/rancher/files/4479076/cattle-cluster-agent-66fc4dbdb-dt2tg-profile2.gz)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.2
- Installation option (single install/HA):
HA w/ k3s

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
K3s
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
m5.large (8GB RAM, 2 vCPU)

- Kubernetes version (use `kubectl version`):

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+k3s1", GitCommit:"3eee8ac3a1cf0a216c8a660571329d4bda3bdf77", GitTreeState:"clean", BuildDate:"2020-03-25T16:13:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+k3s1", GitCommit:"3eee8ac3a1cf0a216c8a660571329d4bda3bdf77", GitTreeState:"clean", BuildDate:"2020-03-25T16:13:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
NA, containerd

**Comment by dnoland1** [comment]
This is a possible duplicate of https://github.com/rancher/rancher/issues/26613

Note: also seeing
```
E0411 11:00:17.863047       1 reflector.go:153] github.com/rancher/steve/pkg/clustercache/controller.go:187: Failed to list *summary.SummarizedObject: the server is currently unable to handle the request
E0411 11:00:18.063022       1 reflector.go:153] github.com/rancher/steve/pkg/clustercache/controller.go:187: Failed to list *summary.SummarizedObject: the server is currently unable to handle the request
E0411 11:00:18.262932       1 reflector.go:153] github.com/rancher/steve/pkg/clustercache/controller.go:187: Failed to list *summary.SummarizedObject: the server is currently unable to handle the request
E0411 11:00:18.462963       1 reflector.go:153] github.com/rancher/steve/pkg/clustercache/controller.go:187: Failed to list *summary.SummarizedObject: the server is currently unable to handle the request
E0411 11:00:18.662986       1 reflector.go:153] github.com/rancher/steve/pkg/clustercache/controller.go:187: Failed to list *summary.SummarizedObject: the server is currently unable to handle the request
E0411 11:00:18.863114       1 reflector.go:153] github.com/rancher/steve/pkg/clustercache/controller.go:187: Failed to list *summary.SummarizedObject: the server is currently unable to handle the request
E0411 11:00:19.063022       1 reflector.go:153] github.com/rancher/steve/pkg/clustercache/controller.go:187: Failed to list *summary.SummarizedObject: the server is currently unable to handle the request
```
repeated in the logs about 3 days ago.

**Comment by ibuildthecloud** [comment]
@dnoland1 Can you try turning off the new dashboard in the features flags and see if that stops the leak?

**Comment by dnoland1** [comment]
@ibuildthecloud Sorry, I'm not able to turn off the dashboard feature flag. See: 
[Deactivate-dashboard.mov.gz](https://github.com/rancher/rancher/files/4484440/Deactivate-dashboard.mov.gz)
There alternative methods for disabling the dashboard?

**Comment by dnoland1** [comment]
Sorry, never mind, thought I was logged in as an admin, but wasn't. I have disable the dashboard feature flag now.

**Comment by dramich** [comment]
This pr https://github.com/rancher/rancher/pull/26644 fixes this in master by pulling in latest steve.

**Comment by sangeethah** [comment]
Reopening this issue to get the fixes merged in master since it was reverted - https://github.com/rancher/rancher/pull/26663 - Revert "Refactor for lasso" #26663

**Comment by dnoland1** [comment]
FYI - after disabling dashboard, memory utilization appears to have stabilized.

**Comment by aaronRancher** [comment]
Installed Rancher v2.4-head on a two node k3s (t2.medium) cluster with MySQL backend (v5.7.22, db.t2.large)
cattle-cluster-agent memory behavior of 2.4-head version cf5ab1dcb for 6 hours.
![Screen Shot 2020-04-17 at 5 27 13 PM](https://user-images.githubusercontent.com/57409052/79623565-dfd4b200-80d1-11ea-881d-e589c16e91ec.png)

**Comment by dnoland1** [comment]
I take it back. Memory growth on the rancher pods is flat after disabling the dashboard, but the cattle-cluster-agent is still climbing:

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/468462/79680085-aaf35880-81c0-11ea-9eaf-46d0621aabf1.png">

**Comment by krishofmans** [comment]
We also have issues with this ... first the issues with the pods going to the docker network bridge, now this ... might need more QA love.

**Comment by sadoMasupilami** [comment]
i do see the same problem with a master which has 8GB and only 3 workers.
![image](https://user-images.githubusercontent.com/11665329/79720250-7971ae80-82e0-11ea-8fea-3203ef6123a6.png)

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:v2.4-head` `version 7f7d6bfc9`.
Steps:
Install rancher on k3s cluster with 2 server nodes (t2.medium) with MySQL backend (v5.7.22, db.t2.large).
Enable monitoring
Cluster was idle for 17 hours
![Screen Shot 2020-04-20 at 6 07 37 PM](https://user-images.githubusercontent.com/57409052/79814060-2cb6c380-8332-11ea-97f2-04a9a6615ebc.png)

Compared to Rancher server `rancher\rancher:v2.4.2` cattle-cluster-agent memory usage:
![Screen Shot 2020-04-20 at 6 07 32 PM](https://user-images.githubusercontent.com/57409052/79814070-32aca480-8332-11ea-8dc3-cfd4a15d2547.png)

**Comment by jiaqiluo** [comment]
Install `Rancher:v2.4.2` in an RKE 3-node cluster, and add couple clusters to the setup. Here is the CPU and memory consumption of the `cattle-cluster-agent` workload in the local cluster:

![image](https://user-images.githubusercontent.com/6218999/79897306-633a2000-83be-11ea-8a4e-27882b0fc102.png)


Make another identical setup using the image `Rancher:v2.4-2774-head` cf5ab1dcb :

![image](https://user-images.githubusercontent.com/6218999/79897681-e491b280-83be-11ea-8d00-3276dff97a9f.png)

**Comment by aaronRancher** [comment]
Tested with Rancher server rancher\rancher:v2.4.2 version 7f7d6bfc9.
Cluster was idle for 3 days:
![Screen Shot 2020-04-22 at 4 27 07 PM](https://user-images.githubusercontent.com/57409052/80043301-28b3ae80-84b6-11ea-93dc-59eaea89e3fa.png)

Tested with Rancher server rancher\rancher:master-head version 8bd924599.
Cluster was idle for 3 days:
![Screen Shot 2020-04-22 at 4 26 42 PM](https://user-images.githubusercontent.com/57409052/80043265-1174c100-84b6-11ea-874c-59516f7f7a88.png)

Tested with Rancher server rancher\rancher:v2.4-head version 7f7d6bfc9.
Cluster was idle for 3 days:
![Screen Shot 2020-04-22 at 4 29 27 PM](https://user-images.githubusercontent.com/57409052/80043415-74feee80-84b6-11ea-95c1-f274823d4954.png)

**Comment by jiaqiluo** [comment]
Run the following three setups on three identical RKE provisioned cluster (k8s v1.17.4), and provision the same number of clusters on it.
- rancher v2.4.2
- rancher v2.4-head
- rancher mater-head

<img width="1377" alt="Screen Shot 2020-04-22 at 6 04 49 PM" src="https://user-images.githubusercontent.com/6218999/80048053-f3ae5880-84c3-11ea-968c-d095b3dc41ce.png">


<img width="1384" alt="Screen Shot 2020-04-22 at 6 04 25 PM" src="https://user-images.githubusercontent.com/6218999/80048051-f01ad180-84c3-11ea-86c6-e52462c7b023.png">



<img width="1373" alt="Screen Shot 2020-04-22 at 6 05 08 PM" src="https://user-images.githubusercontent.com/6218999/80048056-f5781c00-84c3-11ea-8633-d55ba61b00f7.png">

it turns out in the past 12 hours:
- the memory consumption in v2.4.2 went up to 961 MB and is growing
- `master-head` and `v2.4-head` used about 50 - 60 MB constantly

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.4.3-rc1` on a two node k3s (t2.large) cluster with MySQL backend (v5.7.22, db.t2.large)
![Screen Shot 2020-04-23 at 5 25 54 PM](https://user-images.githubusercontent.com/57409052/80163598-7fd78300-858b-11ea-8416-77f4d5beb0f0.png)

Tested with k3s HA Rancher server rancher\rancher:`v2.4-head version` `7f7d6bf`.
![Screen Shot 2020-04-23 at 5 53 55 PM](https://user-images.githubusercontent.com/57409052/80163633-9a116100-858b-11ea-83f1-357c272efc44.png)

Memory is stable on idle.

**Comment by KeithTt** [comment]
Same problem here, I have a v2.4.0 cluster, can I upgrade the rancher server?
