### ISSUE TITLE
How to clean up old records of clusters long deleted?

### ISSUE THREAD

**Issue by sharkymcdongles** [rancher/rancher#26639]
We had some clusters where we deleted them outside of rancher because deleting within the UI would hang forever on deleting RBAC, so we deleted the object under the cluster CRD directly. This worked fine except we see tons of these in the logs from long deleted clusters:

`
2020/04/15 19:59:20 [ERROR] ProjectRoleTemplateBindingController p-jkh8n/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-zccxp" not found
2020/04/15 19:59:20 [ERROR] ProjectRoleTemplateBindingController p-djqbn/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-kjs67" not found
2020/04/15 19:59:20 [ERROR] ProjectRoleTemplateBindingController p-vjrzb/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-f4qvk" not found
2020/04/15 19:59:20 [ERROR] ProjectRoleTemplateBindingController p-qzlxx/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-5sn4l" not found
2020/04/15 19:59:20 [ERROR] ProjectRoleTemplateBindingController p-sq6d8/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-kx5xg" not found
2020/04/15 19:59:20 [ERROR] ProjectRoleTemplateBindingController p-qrb2q/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-d7kdc" not found
2020/04/15 19:59:20 [ERROR] ProjectRoleTemplateBindingController p-r866j/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-cvb7c" not found
2020/04/15 19:59:20 [ERROR] ProjectRoleTemplateBindingController p-299wx/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-w2x5p" not found
2020/04/15 19:59:20 [ERROR] ProjectRoleTemplateBindingController p-5m978/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-xvtrh" not found
2020/04/15 19:59:20 [ERROR] ProjectRoleTemplateBindingController p-9jg8c/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-448j5" not found
2020/04/15 19:59:21 [ERROR] ProjectRoleTemplateBindingController p-l6ccx/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-2g6fh" not found
2020/04/15 19:59:21 [ERROR] ProjectRoleTemplateBindingController p-bkh6f/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-wwvcm" not found
2020/04/15 19:59:21 [ERROR] ProjectRoleTemplateBindingController p-bzk95/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-f2frq" not found
2020/04/15 19:59:21 [ERROR] ProjectRoleTemplateBindingController p-dr8hg/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-lbnlc" not found
2020/04/15 19:59:21 [ERROR] ProjectRoleTemplateBindingController p-z52tl/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-5dtjf" not found
2020/04/15 19:59:21 [ERROR] ProjectRoleTemplateBindingController p-878wg/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-r4v6k" not found
2020/04/15 19:59:21 [ERROR] ProjectRoleTemplateBindingController p-bmnnt/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-rv5xm" not found
2020/04/15 19:59:21 [ERROR] ProjectRoleTemplateBindingController p-rsg6n/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-9cttf" not found
2020/04/15 19:59:21 [ERROR] ProjectRoleTemplateBindingController p-bwlj4/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-ggtb8" not found
2020/04/15 19:59:21 [ERROR] ProjectRoleTemplateBindingController p-blwdl/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-hhg87" not found
2020/04/15 19:59:22 [ERROR] ProjectRoleTemplateBindingController p-cszwg/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-h8vh8" not found
2020/04/15 19:59:22 [ERROR] ProjectRoleTemplateBindingController p-97b99/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-r8fgw" not found
2020/04/15 19:59:22 [ERROR] ProjectRoleTemplateBindingController p-x7x58/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-gzg9q" not found
2020/04/15 19:59:22 [ERROR] ProjectRoleTemplateBindingController p-h6ptz/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-t9gqj" not found
2020/04/15 19:59:22 [ERROR] ProjectRoleTemplateBindingController p-x6vb4/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-h8vh8" not found
2020/04/15 19:59:43 [ERROR] ProjectRoleTemplateBindingController p-sr8fg/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-zsjf6" not found
2020/04/15 19:59:53 [ERROR] ProjectRoleTemplateBindingController p-g8kks/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-g4fgv" not found
2020/04/15 19:59:53 [ERROR] ProjectRoleTemplateBindingController p-8ttrs/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-448j5" not found
2020/04/15 19:59:53 [ERROR] ProjectRoleTemplateBindingController p-rttp8/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-56g9x" not found
2020/04/15 19:59:53 [ERROR] ProjectRoleTemplateBindingController p-d984n/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-zsdv2" not found
2020/04/15 19:59:53 [ERROR] ProjectRoleTemplateBindingController p-mrghd/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-rsz9v" not found
2020/04/15 19:59:53 [ERROR] ProjectRoleTemplateBindingController p-8xnfq/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-w2ftk" not found
2020/04/15 19:59:54 [ERROR] ProjectRoleTemplateBindingController p-sx5tg/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-lx86m" not found
2020/04/15 19:59:54 [ERROR] ProjectRoleTemplateBindingController p-lhcn6/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-qslrq" not found
2020/04/15 19:59:54 [ERROR] ProjectRoleTemplateBindingController p-mlz4v/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-9fw7s" not found
2020/04/15 19:59:54 [ERROR] ProjectRoleTemplateBindingController p-n2rkg/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-kc7d5" not found
2020/04/15 19:59:54 [ERROR] ProjectRoleTemplateBindingController p-j6prv/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-glpqs" not found
2020/04/15 19:59:54 [ERROR] ProjectRoleTemplateBindingController p-cbcht/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-2g6fh" not found
2020/04/15 19:59:54 [ERROR] ProjectRoleTemplateBindingController p-vq9f2/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-8k9s7" not found
2020/04/15 19:59:54 [ERROR] ProjectRoleTemplateBindingController p-2tjcr/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-p69dr" not found
2020/04/15 19:59:54 [ERROR] ProjectRoleTemplateBindingController p-vtrr9/creator-project-owner [mgmt-auth-prtb-controller] failed with : cluster.management.cattle.io "c-6h5zg" not found
`

Where can I find this logic / CRD or w/e it is checking for? I have been trying to find it in the CRDs to no avail.

**Comment by sharkymcdongles** [comment]
Same issue as here, but this is GKE so no direct etcd access: https://github.com/rancher/rancher/issues/18735

**Comment by ChrisHaPunkt** [comment]
Same here. Can't tell anymore if the cluster ids logged were GKE Clusters, but log is spammed with this entries.

**Comment by vildek** [comment]
This just baffles me, how can a product this popular be this bad in garbage collection. Feels like they punish you if you want to reinstall the Rancher..
