### ISSUE TITLE
Catalog Chart version should allow uppercase characters (SemVer)

### ISSUE THREAD

**Issue by stearz** [rancher/rancher#26647]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a chart which version contains uppercase characters like "mychart-1.2.3-SNAPSHOT"), in a chart repo. Add the helm repo as a catalog in Rancher.

**Result:**
Snapshot versions are ignored and can not be used.
The rancher container logs this:

```
failed mychart template version name mytemplate-1.2.3-SNAPSHOT:
[a DNS-1123 subdomain must consist of lower case alphanumeric
characters, '-' or '.', and must start and end with an alphanumeric
character (e.g. 'example.com', regex used for validation is
'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

**Other details that may be helpful:**
Here (https://semver.org/#spec-item-9) it says that uppercase characters are ok to use:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9**A-Z**a-z-].

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.2
- Installation option (single install/HA): HA

**Comment by stearz** [comment]
I just created a pull request that should fix the problem:

https://github.com/stearz/rancher/pull/1

**Comment by brendarearden** [comment]
similar issue https://github.com/rancher/rancher/issues/19615

**Comment by stearz** [comment]
original PR was closed when I tried to squash.
Here is the new one: https://github.com/rancher/rancher/pull/26943
