### ISSUE TITLE
Project-monitoring cannot list resource \"endpoints\" in API group \"\" at the cluster scope"

### ISSUE THREAD

**Issue by skbki** [rancher/rancher#26646]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1.Enable cluster monitoring
2. Enable project level monitoring

**Result:**
Project level prometheus indefinitely printing error messages

`level=error ts=2020-04-16T09:26:36.184Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:264: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"services\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:36.185Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:263: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:36.371Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:265: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:37.186Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:263: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:37.186Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:264: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"services\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:37.372Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:265: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:38.188Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:263: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:38.188Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:264: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"services\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:38.374Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:265: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:39.190Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:263: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:39.190Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:264: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"services\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:39.376Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:265: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:40.192Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:263: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:40.192Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:264: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"services\" in API group \"\" at the cluster scope"
level=error ts=2020-04-16T09:26:40.377Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:265: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:cattle-prometheus-p-bn6gx:project-monitoring\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
 `

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.5
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM 4cpu 16gb ram
- Kubernetes version (use `kubectl version`): 1.17.3

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by jiaqiluo** [comment]
Hi @skbki  how do you get a cluster with k8s 1.17.3 in Rancher v2.3.5?  Is it an imported cluster? Or is the Rancher server upgraded from an older version?

**Comment by skbki** [comment]
Yes, rancher was upgraded.
On this rancher instance I have another cluster with version 1.16.3 with project monitoring 0.0.5 where this issue does not exist

**Comment by hrbu** [comment]
Any progress here? Facing a similar issue.

**Comment by marwanAmeen** [comment]
i am facing the same issue any .
