### ISSUE TITLE
[cadvisor-package] update in agent version. 

### ISSUE THREAD

**Issue by cicerocomp** [rancher/rancher#2665]
cAdvisor upgraded in the repository ([v0.19.3](https://github.com/rancher/cadvisor-package/releases/tag/v0.19.3)), but the latest agent version ([rancher/agent:v0.8.2](https://hub.docker.com/r/rancher/agent/tags/)) is still using the old version:

```
# ./cadvisor --version
cAdvisor version 0.16.0
```

Probably the update also solves the problem of this issues: #2241

**Comment by deniseschannon** [comment]
The cAdvisor will be updated in the next release of Rancher.

**Comment by donmimo** [comment]
Still not updated.

**Comment by deniseschannon** [comment]
The agent is updated, but it's not very clear.

On the host, `docker exec -it rancher-agent bash` to get inside the container. 

Navigate to `cd var/lib/cattle/bin/`.

Inside the folder, `./cadvisor -version`

The result will be `cAdvisor version  ()`. The result isn't very helpful, but that is the latest cadvisor version according to @cloudnautique. I've opened up https://github.com/rancher/rancher/issues/2975 to track being able to actually display the cadvisor version.
