### ISSUE TITLE
User should not be allowed to select lower version from current in Longhorn app upgrade.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/rancher#26661]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster.
2. Deploy app longhorn v0.8.0.
3. Click upgrade and select lower version v0.7.0

**Result:**
Downgrading the longhorn version should not be allowed. The lower versions should grayed out.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.4.2
- Installation option (single install/HA): Single

**Comment by yasker** [comment]
@deniseschannon If charts support prohibiting downgrade, we can do something in Longhorn chart side.

**Comment by deniseschannon** [comment]
@westlywright I thought that apps could only "downgrade" using rollback. The version dropdown shouldn't allow downgrade through the app version seleciton when upgrading.

**Comment by khushboo-rancher** [comment]
Verified in master-head c49a121fc and v2.4-head cf5ab1dcb, lower version of longhorn app is not available while upgrading the app.
<img width="1288" alt="Screen Shot 2020-04-17 at 4 21 45 PM" src="https://user-images.githubusercontent.com/60111667/79621264-8f585700-80c7-11ea-86a5-446f91855c18.png">
