### ISSUE TITLE
[BUG] Rancher breaks ingress-nginx by labelling its Pods ⚠️

### ISSUE THREAD

**Issue by al45tair** [rancher/rancher#26677]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Install Rancher.

**Result:**
At some point, Rancher adds the label "field.cattle.io/podName" to the ingress controller Pods. This is unfortunate, because ingress-nginx asks Kubernetes to find all the Pods running ingress-nginx *with the same label as the running pod* in order to find the set of IP addresses that it should use to annotate ingresses (in the loadBalancer part of the Ingress status).

The upshot is that once Rancher has done this, Ingresses are massively less robust than they should be, because they only have the IP address of a single node, rather than all the addresses of all of the nodes running ingress controller instances.

This feeds through into DNS if you're using external-dns (which lots of us are).

This is the cause of #25492; rather than add to that Issue, I filed a new one explaining the actual bug.

**Other details that may be helpful:**
The code in ingress-nginx that does this is visible in internal/ingress/status/status.go, in runningAddresses() and isRunningMultiplePods() (I was looking at revision 6e8c68d8881212 of [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx)). Adding the label breaks this code.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Azure, 2 cores, 8GB
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): I don't have host access.

**Comment by al45tair** [comment]
I've written a [short patch for ingress-nginx that should work around this problem](https://github.com/al45tair/ingress-nginx/commit/4b5017fabd2f3c604041487af0c9baf5784b0605). This isn't really ideal, because it would mean that you'd need to run a special, Rancher-specific, version of ingress-nginx, which is obviously undesirable.

**Comment by chrisfosterelli** [comment]
Thanks for digging into this @al45tair. I've been wracking my brain trying to figure out why I can't get every node in the cluster attached to a Route 53 record -- seems this is strongly in the way.

**Comment by al45tair** [comment]
@chrisfosterelli Indeed. It was quite puzzling too, because Rancher doesn't add the extra label to start with; that has only ever happened later on, and I'm not entirely certain what triggers it. So it will work to start with, with a newly created cluster, and then at some point it'll break.

I'm a little surprised Rancher hasn't even commented on this issue yet. It seems to me that this is a pretty serious bug, and I reported it on the 17th of April, which is quite some time ago now.

**Comment by kinarashah** [comment]
@al45tair Thank you very much for your detailed analysis! 

This happens when Project network isolation is enabled on the cluster. 
> Rancher doesn't add the extra label to start with; that has only ever happened later on, and I'm not entirely certain what triggers it.

**Comment by sowmyav27** [comment]
**On 2.4.8 Reproduced the issue**

- Deploy a 2 worker node cluster.
- Enabled `Project Network Isolation` 
- Ingress controller deployed has the following labels: -- **Expected with fix**: `field.cattle.io/podName: nginx-ingress-controller-qfhbt` should NOT be available

```
labels:
    app: ingress-nginx
    controller-revision-hash: 8d4d59f96
    field.cattle.io/podName: nginx-ingress-controller-qfhbt
    pod-template-generation: "1"
```

- Deploy a GDNS - provider and entry
- The A record for the GDNS provider points to only 1 worker node
- Create a workload - scale = 2 in default project
- Create an ingress pointing to this workload
- View/Edit Yaml for this ingress
```
status:
  loadBalancer:
    ingress:
    - ip: <worker nodes 1>
```
- Ip address of only 1 worker node is available. -- **Expected** - all worker node's IP addresses should be available

**In 2.5-head commit id: `9d388217`**

- Deploy a 2 worker node cluster.
- Enabled `Project Network Isolation` 
- Labels on the ingress-controller in System project -
```
labels:
    app: ingress-nginx
    controller-revision-hash: 6c464fc9d6
    pod-template-generation: "1"
```
- `podName` label is NOT available
- Deploy a GDNS - provider and entry
- The A record for the GDNS provider points to both the worker nodes
- Create a workload - scale = 2 in default project
- Create an ingress pointing to this workload
- View/Edit Yaml for this ingress

```
status:
  loadBalancer:
    ingress:
    - ip: <w1>
    - ip: <w2>
```

**Comment by maggieliu** [comment]
@sowmyav27 created separate issue to track master issue. If we can good for 2.4 and 2.5 can you please close this?

**Comment by sowmyav27** [comment]
Closing this as it works on 2.4 and 2.5 branches.

**Comment by UberKuber** [comment]
After upgrading to Rancher v2.4.10 we see that the `podName` label keeps getting applied then removed, is this expected behaviour? The ingress still only lists the leader controller IP.

**Comment by sowmyav27** [comment]
@UberKuber That is not expected, that is being tracked in this [issue](https://github.com/rancher/rancher/issues/30045)

**Comment by UberKuber** [comment]
Thanks @sowmyav27, the process I'm testing now is as per below:

1. Disable project network isolation on the cluster
2. Redeploy nginx ingress controller daemonset
3. Enable project network isolation on the cluster
