### ISSUE TITLE
Minor feature request: Link to Rancher Docs from rancher server ui

### ISSUE THREAD

**Issue by dahendel** [rancher/rancher#2667]
As I have been using rancher for a little while now, I have become very familiar with it but I still reference the docs almost daily. Is it possible to toss a link to the docs in the UI? I especially use this when writing compose files for the labels. I think it would be a great "nice-to-have".

Thanks for the great work!

**Comment by will-chan** [comment]
This should be available in our next 0.53 release.

**Comment by tfiduccia** [comment]
Version - Master Jan 07
Verified added
