### ISSUE TITLE
unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by chuegel** [rancher/rancher#26674]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
We have cert-manager 0.12 deployed via helm. Upgrading rancher from 2.3.5 to 2.3.6:
```
helm upgrade rancher rancher-stable/rancher   --namespace cattle-system   --set ingress.tls.source=secret   --set hostname=rancher.example.com
```
fails with:
**Result:**
```
UPGRADE FAILED
ROLLING BACK
Error: failed decoding reader into objects: unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"
Error: UPGRADE FAILED: failed decoding reader into objects: unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"
```

```
helm list
NAME        	REVISION	UPDATED                 	STATUS  	CHART               	APP VERSION	NAMESPACE
cert-manager	1       	Fri Apr 17 09:43:06 2020	DEPLOYED	cert-manager-v0.12.0	v0.12.0    	cert-manager
rancher     	13      	Fri Apr 17 11:11:15 2020	FAILED  	rancher-2.3.6       	v2.3.6     	cattle-system
```
**Other details that may be helpful:**
```
kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml
```
```
kubectl get clusterissuers.cert-manager.io
NAME               READY   AGE
letsencrypt-prod   True    31d
```

```
kubectl get issuers.cert-manager.io -A
NAMESPACE       NAME                            READY   AGE
cattle-system   rancher                         True    31d
cert-manager    cert-manager-webhook-ca         True    31d
cert-manager    cert-manager-webhook-selfsign   True    31d
```
*name redacted

```
kubectl get certificate -
NAMESPACE       NAME                                   READY   SECRET                                 AGE
cattle-system   rancher.example.com                      True    tls-rancher-ingress                    31d
cattle-system   tls-rancher-ingress                    False   tls-rancher-ingress                    60m
cert-manager    cert-manager-webhook-ca                True    cert-manager-webhook-ca                31d
cert-manager    cert-manager-webhook-webhook-tls       True    cert-manager-webhook-webhook-tls       31d
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
- cert-manager version:

```
NAME        	REVISION	UPDATED                 	STATUS  	CHART               	APP VERSION	NAMESPACE
cert-manager	1       	Fri Apr 17 09:43:06 2020	DEPLOYED	cert-manager-v0.12.0	v0.12.0    	cert-manager
```

Any hints how to fix this? Thanks

**Comment by fabiorauber** [comment]
See https://cert-manager.io/docs/installation/upgrading/upgrading-0.10-0.11/, about deprecation of certmanager.k8s.io/v1alpha1 in favor of cert-manager.io/v1alpha2.

**Comment by chuegel** [comment]
@fabiorauber I already did that when upgrading cert-manager. See version above.

```
kubectl get -o yaml --all-namespaces issuer,clusterissuer,certificates,certificaterequests -o yaml | grep alpha1 | wc -l
0
```

**Comment by colek42** [comment]
I have the same issue.  Rancher creates an `Issuer` in the `cattle-system` namespace names `rancher` but the annotation on the Ingress looks for a `ClusterIssuer` named `rancher`.  My workaround was to create a `clusterIssuer` named Rancher with my letsencrypt email.  I think there is a bug here, and some room for improvement in the config.  I should be able to use whatever issuer I want.  Currently, the annotations in the Helm chart do not override the declared config.  Let me know if you need anything else.

**Comment by chuegel** [comment]
I've re-installed the rancher chart. That seems to do the trick.

**Comment by Da-Teach** [comment]
We are running into the same issue. 
(image 2.4.2)

As requested per 2.3 -> 2.4 upgrade, we updated cert-manager to v0.12. This means v1alpha1 doesn't exist. I'm not entirely sure if we updated cert-manager before or after upgrading to v2.4.2. 

But end result is that we can't upgrade to 2.4.3 due to this error. We also can't uninstall v2.4.2 due to the same issue (it'll remove the helm release but leave rancher installed with various errors if we try to install once uninstall failed).

**Comment by rawmind0** [comment]
@colek42, Rancher chart is not referencing `ClusterIssuer` anymore, https://github.com/rancher/rancher/blob/v2.4.2/chart/templates/ingress.yaml#L21 . May be your issue is related to https://github.com/rancher/rancher/issues/26505 . Have you set `--default-issuer-kind=ClusterIssuer` to your cert-manager?? 

@Da-Teach , have you followed [rancher upgrade instructions](https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/ha/#c-upgrade-rancher)??  If you are upgrading cert-manager, you should follow `OPTION B: REINSTALLING RANCHER AND CERT-MANAGER`

**Comment by Da-Teach** [comment]
@rawmind0 , well v2.4.2 is installed ... Just now in a situation that I can't uninstall and can't upgrade Rancher ...

**Comment by rawmind0** [comment]
@Da-Teach, due to your explanation, i'm guessing you upgraded cert-manager after upgrading rancher to v2.4.2, but not following  [rancher upgrade instructions](https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/ha/#c-upgrade-rancher), `OPTION B: REINSTALLING RANCHER AND CERT-MANAGER`, isn't it??

Rancher chart should be uninstalled before you upgrade cert-manager due to CRDs API changes.  If you install old cert-manager CRDs, containing old API `certmanager.k8s.io/v1alpha1` you should be able to uninstall Rancher chart and install it again once new cert-manager API is available. Don't forget to backup your rancher k8s cluster before uninstall Rancher chart.

**Comment by Da-Teach** [comment]
@rawmind0 let me start by saying I appreciate that you are helping me. Even though I slightly feel like you are telling me I can't follow instructions, but it's ok. You mention option B. And the fun thing is, I followed option b step by step (and it's exactly how I got into the mess I'm in).

Step 1: Uninstall rancher (2.3.something) - Done
Step 2: Reinstall rancher - So installed 2.4.2
Step 3: Uninstall and reinstall Cert-Manager - So uninstall cert-manager 0.8.3 (I think?) and installed 0.12

I'm going to guess the *correct* order should be:
Uninstall rancher
Uninstall cert-manager
(Re)install cert-manager
(Re)install rancher

So unless I'm wrong my steps will now be:
Backup settings and uninstall cert-manager 0.12
Reinstall cert-manager 0.8
Uninstall rancher 2.4.2
Reinstall cert-manager 0.12 and restore settings
Reinstall rancher 2.4.3

**Comment by rawmind0** [comment]
@Da-Teach , i'm not telling you that you can't follow instruction. I was just asking if you follow them to figure out what is the situation of your system. Anyway, I'm sorry if you understand that from my comments, it wasn't my intention.

> You mention option B. And the fun thing is, I followed option b step by step (and it's exactly how I got into the mess I'm in).

> Step 1: Uninstall rancher (2.3.something) - Done
Step 2: Reinstall rancher - So installed 2.4.2
Step 3: Uninstall and reinstall Cert-Manager - So uninstall cert-manager 0.8.3 (I think?) and installed 0.12

Oh, you are right, the process defined in the docs is not correct. Thanks to mention and report it, i'll open a PR to fix it. 

As you mention, the process should be:
* Backup system etcd and settings
* Uninstall rancher
* Uninstall old cert-manager
* Install new cert-manager
* Install rancher (same rancher version you had)

In your case, to finish with rancher 2.4.3, your steps should be 
* Backup settings and uninstall cert-manager 0.12
* Reinstall cert-manager 0.8
* Uninstall rancher 2.4.2
* Reinstall cert-manager 0.12 and restore settings
* Reinstall rancher 2.4.2
* Upgrade to rancher 2.4.3

**Comment by Da-Teach** [comment]
@rawmind0 thanks for the help. Took a few etcd-restores to get it working. Ran into an issue with helm  trying to uninstall cert-manager. But after upgrading helm I got everything up. I didn't need to install cert-manager 0.9, only the crd's .

**Comment by superseb** [comment]
If you encounter this error after following the fixed docs, please set `export HELM_DEBUG=true` before running the Helm install to see possible errors. In Helm versions before 3.1.2 (possibly 3.1.0), I've seen the install fail silently with this error while the root cause was that not all apiservice were ready in the cluster (`kubectl get apiservice`), this was only seen when `HELM_DEBUG=true` was set. In v3.1.2, the install proceeded fine.

**Comment by rajha-korithrien** [comment]
Thanks Rancher folks for making a very useful project!
I can confirm that this issue occurs when installing Rancher from scratch, and using the latest `cert-manager`. Which I acknowledge is not a supported configuration (I think).

I have a completely "clean" Kubernetes cluster brought up with `rke` no `rancher` installed.
```
kubectl --kubeconfig ./kube_config_cluster.yml get pods --all-namespaces
NAMESPACE       NAME                                        READY   STATUS      RESTARTS   AGE
ingress-nginx   default-http-backend-5bcc9fd598-dbm4w       1/1     Running     0          21h
ingress-nginx   nginx-ingress-controller-9sc9k              1/1     Running     0          21h
ingress-nginx   nginx-ingress-controller-fr2xr              1/1     Running     0          21h
ingress-nginx   nginx-ingress-controller-r8qjl              1/1     Running     0          21h
kube-system     coredns-799dffd9c4-4qzsf                    1/1     Running     0          21h
kube-system     coredns-autoscaler-84766fbb4-9xvhp          1/1     Running     0          21h
kube-system     kube-flannel-7glvw                          2/2     Running     0          21h
kube-system     kube-flannel-rndpk                          2/2     Running     0          21h
kube-system     kube-flannel-t4jss                          2/2     Running     0          21h
kube-system     metrics-server-59c6fd6767-4qvs9             1/1     Running     0          21h
kube-system     rke-coredns-addon-deploy-job-89gbk          0/1     Completed   0          21h
kube-system     rke-ingress-controller-deploy-job-5q4ds     0/1     Completed   0          21h
kube-system     rke-metrics-addon-deploy-job-j6scd          0/1     Completed   0          21h
kube-system     rke-user-includes-addons-deploy-job-5wrzs   0/1     Completed   0          21h
```
Following the instructions given here: https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/helm-rancher/
```
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
"rancher-latest" has been added to your repositories
```
Followed by:
```
kubectl --kubeconfig ./kube_config_cluster.yml create namespace cattle-system
namespace/cattle-system created
```
Then install the `cert-manager` CRDs:
```
kubectl --kubeconfig ./kube_config_cluster.yml apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.0/cert-manager-legacy.crds.yaml
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io created
```
Now install `cert-manager` namespace:
```
kubectl --kubeconfig ./kube_config_cluster.yml create namespace cert-manager
namespace/cert-manager created
```
Now use helm to install `cert-manager` (version `1.0.0`):
```
helm repo add jetstack https://charts.jetstack.io
"jetstack" has been added to your repositories
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "rancher-latest" chart repository
Update Complete. ⎈ Happy Helming!⎈
$ helm --kubeconfig ./kube_config_cluster.yml install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.0.0
NAME: cert-manager
LAST DEPLOYED: Wed Sep  2 12:45:22 2020
...
...
cert-manager has been deployed successfully!
```
Wait for cert-manager to finish coming up:
```
kubectl --kubeconfig ./kube_config_cluster.yml get pods --namespace cert-manager
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-7689f6664-rj9x4               1/1     Running   0          2m19s
cert-manager-cainjector-84d896cfbc-qnxl6   1/1     Running   0          2m19s
cert-manager-webhook-6566df9594-nl4fw      1/1     Running   0          2m19s
```
Now install Rancher via helm:
```
helm --kubeconfig ./kube_config_cluster.yml install rancher rancher-latest/rancher --namespace cattle-system --set hostname=192.168.57.100.xip.io
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"
```

I understand that Rancher 2.4.6 doesn't support `cert-manager` > 0.16.0. If you please, when might such support be slated to occur?

Thanks again!

**Comment by bizmate** [comment]
I am also stuck while trying to install Rancher on RKE using Helm and get a very similar error

```
helm_release.rancher_helm: Creating...

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"

  on rancher.tf line 1, in resource "helm_release" "rancher_helm":
   1: resource "helm_release" "rancher_helm" {

```

Would it be caused by the same bug?

**Comment by rawmind0** [comment]
Rancher helm chart  shouldn't work properly with cert-manager up to v0.16.0 due to api version update. Support to it will be provided with PR #29017

**Comment by deniseschannon** [comment]
Cert-manager changed their APIs so our current Rancher helm chart doesn't work with different versions of cert-manager. 

With this change, cert-manager v0.16.0+ and v1.0.0 should be supported. Our docs only recommend up to v0.15.0 but it's easy for users to try out the latest chart changes. 

To test: After this helm chart change is in, test with cert-manager v0.15.0 and the latest cert manager v1.0.1, which is the latest.

**Comment by jiaqiluo** [comment]
the bugfix is validated on rancher:`master-head` e9a98a3

Rancher is installed successfully with cert-manager both v0.15.0 and v1.0.1

- all workloads in the system project in lcoasl cluster are active 
- adding a custom cluster is successful

**Comment by wzrdtales** [comment]
this bug fix doesn't work. upgrades are broken for me right now in any version. worst thing is: the api capabilities get checked before certmanager.version. So certmanager.version is completely useless right now and is not a workaround either...

So with 0.15 latest try I still get `Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"` Uninstalling rancher is not an option, I am not going to sacrifice a working production system.


```
v1alpha2.acme.cert-manager.io               Local                        True        8m41s
v1alpha2.cert-manager.io                    Local                        True        8m42s
v1alpha3.acme.cert-manager.io               Local                        True        8m41s
v1alpha3.cert-manager.io                    Local                        True        8m42s
```

**Comment by wzrdtales** [comment]
to be clear not version works, not even 0.12 anymore...

**Comment by lcotonea** [comment]
@wzrdtales You have maybe forgotten to apply custom definition related to your cert-manager version. Example:
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/**v0.15.0**/cert-manager.crds.yaml

**Comment by wzrdtales** [comment]
nope, if you would have forgotten that, the output i posted wouldn't even exist...

**Comment by lcotonea** [comment]
@wzrdtales Indeed, however your error message talks about a certmanager.k8s.io**/v1alpha1** resource that is not listed in the resource list.
Try to:
- delete your cert-manager namespace : kubectl delete namespace cert-manager
- apply the ressource for the version 0.15.0 of cert-manager : kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.15.0/cert-manager.crds.yaml
- create your namespace cert-manager : kubectl create namespace cert-manager
- deploy your cert-manager in the right version : helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v0.15.0

**Comment by wzrdtales** [comment]
did all of that way before already, no need to ask me third level support stuff, I only reach out when things are broken.

Indeed, before I updated rancher from 2.4.5 to 2.4.8 today already 0.12 was installed on that cluster. And executing on this existing working setup the update command is already in a bad status.

**Comment by rawmind0** [comment]
@wzrdtales , if you are trying to already update cert-manager with Rancher, you should follow https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/ha/#c-upgrade-rancher  - `Option B: Reinstalling Rancher and cert-manager` . Unfortunately, helm is not able to manage objects update if api version has been changed. 

> Uninstalling rancher is not an option, I am not going to sacrifice a working production system.

Uninstalling Rancher and installing it again on the same k8s cluster shouldn't sacrifice the system, due to rancher data should be there once you install it again. Anyway, previous etcd backup is more than recommended before proceed.
