### ISSUE TITLE
Validate k8s 1.16.9 and 1.17.5 versions

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#26680]

**Comment by rancher-max** [comment]
#### Validated in v2.4-2780-head (commit id `7f7d6bfc9`) and master-2782-head (commit id `ac55abc62`)
Steps:
1. Run kdm job (creates and validates all 3 k8s versions for all 4 clusters. Total of 12 clusters created.)
2. Using 3 clusters created from that job (canal with k8s v1.17.5, canal with k8s v1.16.9, and canal with k8s v1.15.11) run all other existing regression automation


#### Validated upgrade scenario from v2.4.2 to v2.4-2785-head
Steps:
1. Create 3 clusters in v2.4.2 using canal with kubernetes versions 1.15.11, 1.16.8, and 1.17.4
2. Run preupgrade jobs
3. Upgrade to v2.4-head and update kdm branch to use dev-v2.4. Refresh kdm driver as well
4. Run postupgrade jobs
5. Upgrade 1.16 and 1.17 clusters to use 1.16.9 and 1.17.5, respectively
6. Run postupgrade jobs again


Fully validated. 

**One strange behavior to note:  v2.4-head does not use kdm branch `dev-v2.4` by default and instead uses `release-v2.4`.**
