### ISSUE TITLE
Links to load balancer are being updated before new services are up 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2668]
Rancher-compose- v0.5.1

When performing `rancher-compose up`,  links to services are updated before the new service was actually running. 

Links to services on a load balancer should be updated AFTER the service is running 

http://forums.rancher.com/t/haproxy-link-updated-prior-to-container-being-available/897

**Comment by deniseschannon** [comment]
@sangeethah When testing this fix, can you please also test that circular links are still working as well.

**Comment by deniseschannon** [comment]
Verified that circular links (above issues) are still working with v0.5.2-rc2.

**Comment by sangeethah** [comment]
Tested with rancher-compose version - V0.5.2-rc2

When a new service is defined and linked to existing LB service using rancher-compose up , the new service is activated and started and only when it gets to "active" state , the Lb service is linked to it.
