### ISSUE TITLE
Error relating to "kubeclt apply failed" presented for around 5 minutes during cluster provisioning 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#26688]
Version: master-head(00ff15976)

Steps:
1. Create a DO cluster in master-head
2. Provisioning error is displayed as below for around 5 minutes. 
![Screen Shot 2020-04-17 at 11 25 00 AM](https://user-images.githubusercontent.com/18536626/79602560-8bb0da00-809f-11ea-8008-1076de8ffaca.png)

It recovers after 5 minutes

**Comment by izaac** [comment]
This happened to me today

Rancher version `master-head (08/12/2020)` _d19f179c4_

I was using DO driver to provision a cluster. Usually after deploying Rancher and provisioning a cluster shortly after I get this error *occasionally*

**Comment by soumyalj** [comment]
Tested with master-head(master-76c26fb0f9)

Deployed few node driver and custom clusters. 
The error as mentioned above was not observed during provisioning.
