### ISSUE TITLE
[backport] Validate k8s 1.16.9 and 1.17.5 versions

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#26681]
Needs to be coordinated with nodelocal backport issue (#26480)

**Comment by rancher-max** [comment]
Reopening because unable to see the expected versions.
KDM config:
```
{
  "branch": "dev-v2.3",
  "refresh-interval-minutes": "1440",
  "url": "https://github.com/rancher/kontainer-driver-metadata.git"
}
```

Versions in dropdown:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/55997940/79792202-5ad0df00-8303-11ea-9a3a-1d77ff979d1e.png">

**Comment by deniseschannon** [comment]
@mrajashree what's the minimum version set for these templates?

**Comment by mrajashree** [comment]
@rancher-max @deniseschannon This needs an RC, can be only tested on RC.

**Comment by mrajashree** [comment]
The minimum rancher server version is 2.3.7-rc1 for these new k8s versions

**Comment by rancher-max** [comment]
#### Validated in v2.3.7-rc2

- All kdm jobs and automation on k8s v1.17.5 and k8s v1.16.9 passed
- Available versions:
<img width="706" alt="image" src="https://user-images.githubusercontent.com/55997940/80038646-f0f33980-84aa-11ea-9f20-b397288266fa.png">

- In rancher v2.3.6 using kdm branch dev-v2.3 available versions:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/55997940/80038756-1c762400-84ab-11ea-9822-d1cdc87ce789.png">
