### ISSUE TITLE
HA upgrade from v2.3.5 gets clusters in Provisioning state and with tls error.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#26694]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

- Install Rancher `v2.3.5` HA (auto generated certs)
  - `helm_v3 install rancher rancher-latest/rancher --version v2.3.5 --namespace cattle-system --set hostname=hostname --set rancherImageTag=v2.3.5`
- Provision a couple of RKE/Custom clusters and upgrade to `v2.4-head` (cf5ab1dcb)
  - `helm_v3 upgrade rancher rancher-latest/rancher --version v2.4.2 --namespace cattle-system --set hostname=hostname --set rancherImageTag=v2.4-head`

**Result:**

Rancher gets updated but the clusters get stuck in `Provisioning` with the following error when rancher tries to upgrade the agents which are never upgraded they stay in `v2.3.5
```
Kubectl apply failed: exit status 1, unable to recognize "management-statefile_path_redacted": Get https://localhost:443/k8s/clusters/c-jndrb/api?timeout=32s: remote error: tls: internal error unable to recognize "management-statefile_path_redacted": Get https://localhost:443/k8s/clusters/c-jndrb/api?timeout=32s: remote error: tls: internal error unable to recognize "management-statefile_path_redacted": Get https://localhost:443/k8s/clusters/c-jndrb/api?timeout=32s:
```

**Other details that may be helpful:**

**Environment information**
- Rancher version: `v2.4-head`
- Installation option (single install/HA): HA

**Comment by sowmyav27** [comment]
Upgrade on a single node worked fine -  from 2.3.5 to 2.4-head - commit id: `cf5ab1dcb`

**Comment by izaac** [comment]
Rancher version: `v2.4-head` commit id: 7f7d6bfc9

- HA Install with self-signed certs.
- Single Install with self-signed certs.

Upgrade to `v2.4-head` from `v2.3.5` works now. I will validate in master once merged.

**Comment by izaac** [comment]
Rancher version: `master-head (04/20/2020)` commit id: 8bd924599

- HA Install with self-signed certs.
- Single Install with self-signed certs.

Upgrade to `master-head` from `v2.3.5` works now.

Opened issue #26716, related to the HA rancher nodes getting restarted more than expected due to an error.
