### ISSUE TITLE
Monitoring - Monitoring API is not ready after apps are active 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#26692]
this is found during the testing this issue: https://github.com/rancher/rancher/issues/26440

Steps:
- run `Rancher:v2.4-head` single install 
- add a cluster with cluster monitoring enabled by editing the cluster as YAML file
- add a second cluster, enable the cluster monitoring after the cluster is active

Results:

When enabling the cluster monitoring in the provisioning configuration, the UI will keep showing the `Monitoring API is not ready` message after the apps are active, and it takes **another 3 to 5 mins** to see the message disappear and metrics section shows up. --> This behavior is **not** seen on `rancher:v2.3.6` single install. 

While if the cluster monitoring is enabled after the cluster is active, the `Monitoring API is not ready` message will disappear and the metrics section shows up as soon as the apps are active. --> This behavior is the same on `rancher:v2.3.6` single install.

**Comment by lots0logs** [comment]
I'm using v2.4.2 and while I can see that the monitoring apps are running, the dashboard continues to show "Monitoring API is not ready" message. It's been over 24 hours and the message is still there. I even tried rebooting the hosts. Please let me know what data you need to identify the issue.

**Comment by jiaqiluo** [comment]
This happens in an imported multiple-node k3s cluster (v1.17.4+k3s1) in a `rancher:v2.4.3-rc2` single-install setup. 

it takes a long time for the metrics showing in the UI after the apps are active

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/26811#issuecomment-627679570

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher
- `v2.4-3036-head` and
-  `master-3034-head` 

with monitoring chart version `0.1.1`  


The cluster monitoring is tested on clusters with different k8s versions and different kinds of clusters on different scenarios while validating other monitoring-related issues. The metrics show up in Rancher UI right after the monitoring apps are active at most times. 

So I am confident to say that the bug is fixed.

**Comment by deviops-com** [comment]
Hi,
