### ISSUE TITLE
How to disable the page reload in a minute?

### ISSUE THREAD

**Issue by yuanqixun** [rancher/rancher#26707]
Just for the title, how to disable the feature?
when i edit some configure, the page will auto reload in a minute and all my config data will lost before i save the page.

**Comment by vincent99** [comment]
The only time the UI reloads itself is when the websocket connection drops for more than a minute.  Look for the underlying issue there.

**Comment by drewhemm** [comment]
@vincent99 Any chance you could provide more information about how to troubleshoot this? I am hitting the same problem - Rancher reloads every 60 seconds or so, regardless of what I am doing in the UI. This is on a fresh installation with k3s and metallb

**Comment by drewhemm** [comment]
For me, the issue was caused by my default opnsense firewall settings, see referenced metallb issue for details of the solution.
