### ISSUE TITLE
Container DNS

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#2670]
Some applications need to be able to resolve the hosts by name. (Rabbit MQ) In order for that to work we need the container names to resolve to the rancher ips in DNS.

So if a service had web1 and web2 

dig web1 +short 
returns 10.42.x.x

**Comment by alena1108** [comment]
That is already in. If web1 and web2 are the part of the service, web1 will be able to resolve both web1 and web2 by the instance name.
