### ISSUE TITLE
rancher 导入现有集群，提示xit status 1, W0419 05:24:50.936626 24544 factory_object_mapping.go:423] Failed to download OpenAPI (the server could not find the requested resource), falling back to swagger error: error validating "management-state/tmp/yaml-746003858": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false

### ISSUE THREAD

**Issue by wangtingwei1995** [rancher/rancher#26704]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by loganhz** [comment]
Can you supply more info on your setup (basically copy paste from this and fill in: https://raw.githubusercontent.com/rancher/rancher/master/.github/ISSUE_TEMPLATE.md)

If you would like to ask questions in Chinese, please add `rancher2` to join 
Rancher WeChat group. Thanks
