### ISSUE TITLE
kubernetes cluster server url points to rancher server

### ISSUE THREAD

**Issue by MrAmbiG** [rancher/rancher#26719]
I have 2 kubernetes clusters imported into rancher (older rancher crashed so moved to new rancher docker) but both the cluster's server url points to the ip address of the server on which the rancher docker is running. This is see in the kubeconfig. Does this not mean if the rancher docker crashes again or not available then my k8s clusters are inaccessible. In other words if I have a single point of failure for all my kubernetes clusters if they are managed by rancher?! I hope not.
https://<rancher server)/k8s/clusters/cluster1
https://<rancher server)/k8s/clusters/cluster2
**What kind of request is this (question/bug/enhancement/feature request):**
Rancher is a single point of failure for multiple k8s clusters.

**Steps to reproduce (least amount of steps as possible):**
import existing rancher or other k8s clusters to a rancher(docker) server.

**Result:**

Rancher is a single point of failure for multiple k8s clusters.
**Other details that may be helpful:**
Old rancher docker server crashed from  which these 2 clusters were created. So I recreated the rancher docker server and imported these 2 rancher clusters.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Latest
- Installation option (single install/HA): Single node docker image.
Baremetal/metallb

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
19.x
```

**Comment by superseb** [comment]
For production use, you should run the HA install of Rancher as described on https://rancher.com/docs/rancher/v2.x/en/best-practices/deployment-types/ and the installation instructions are on https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/.

For RKE clusters, there is an alternative way to access the cluster outside of Rancher as described on https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cluster-access/ace/. In case of an imported cluster, the kubeconfig of the cluster must have been present at the time of importing which is still valid after importing as being the fail safe option until Rancher is back up and running.

**Comment by MrAmbiG** [comment]
After importing these clusters into rancher, it was giving certifiation errors to connect with the imported clusters so we had to replace the old kubeconfig with the new kubeconfig what rancher generated. We noticed that the kubemaster is pointing only to the rancher server which is running is docker .
Background:
1. spin up new rancher docker 
2. create 2 clusters
3. rancher crashed
4. recreated rancher
5. imported both the rancher clusters into the newly recreated rancher (Same place, same server, same ip)
6. kubectl was giving x509 certification error.
7. replaced the old kubeconfig files with the new kubeconfig files from new rancher's dashboard.

When we created these 2 clusters from rancher earlier we had a context where we can point kubectl to one of the nodes and it will still work but not after importing them.

This means that when if someone imports any of their non RKE or non rancher clusters into rancher they are creating a dependency on rancher. Hypothetically if I have 10 k8s clusters managed by rancher and if rancher (even if its HA) is not reachable for some reason (network or subnet where rancher resides is down, all 3 servers down, the site where rancher is hosted is down) then all 10 k8s clusters are out of reach because they all now have a common+single point of failure.

I honestly feel that it is a predatory design where if we add a cluster to rancher then it takes over the cluster in such a way that it creates an unnecessary dependency on rancher and you can't access without it. Old kubeconfig files will give x509 certification error and won't work when we import clusters into rancher.

Please suggest a fix or solution where we can reach our k8s clusters even if the rancher is down.

We have been trying from months to get rancher HA working. We tried helm and 3 VMs but no go. We get the default backend error on both VMs and helm. So we gave up.
