### ISSUE TITLE
AKS NetworkPolicy is not supported

### ISSUE THREAD

**Issue by travis-sobeck** [rancher/rancher#26710]
Rancher v2.3.6
Unable to create AKS cluster with advanced network config with azure and calico
![image](https://user-images.githubusercontent.com/20098093/79766902-31598880-82ee-11ea-9fcd-07f4dd8f3c47.png)

The full error is as follows:
```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.
Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NetworkPolicyNotSupported" 
Message="NetworkPolicy is not supported (only azure and calico are supported)" Target="networkProfile.networkPolicy"
```

For reference this works just fine so I know its not azure
az aks create --resource-group {resGrp} --name {aks} --generate-ssh-keys --aad-server-app-id {server_app_id} --aad-server-app-secret {server_app_secret} --aad-client-app-id ${client_app_id} --aad-tenant-id ${tenantId} --network-plugin azure --dns-name-prefix "${resGrp}-dns"
–vnet-subnet-id ${subnet_id} --docker-bridge-address 172.17.0.1/16 --dns-service-ip $dns_service_ip --service-cidr $service_cidr `
–subscription $azureSubscriptionID --location eastus --kubernetes-version 1.16.7 --node-count 1 --node-vm-size Standard_D2s_v3 --network-policy calico

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.6` UI: `v2.3.40` |
|Route|`nodes.node-templates`|

**Comment by superseb** [comment]
Do you get the same error from the CLI when you use `--network-policy Calico` at the end? (to root cause this to case sensitivity of the network-policy value)

**Comment by travis-sobeck** [comment]
By CLI assume you mean AzureCli (az aks create)?  It works just fine as posted above (--network-plugin azure and --network-policy calico).  I have not tried it with upper case 'Calico', I just used lower case because that's what was in Azure Docs.

**Comment by travis-sobeck** [comment]
but I can run a test with upper case

**Comment by travis-sobeck** [comment]
It does not like upper case 'Calico'
Operation failed with status: 'Bad Request'. Details: NetworkPolicy is not supported (only azure and calico are supported)

**Comment by travis-sobeck** [comment]
It looks like this is what Rancher is trying to use (View in API) "networkPolicy": "Calico"
That will NOT work if its sending uppercase

**Comment by travis-sobeck** [comment]
I was able to hack at the config in "View in API" and force it to lower case, (and it did not like Null for Tags), then it worked

**Comment by ams0** [comment]
I have the same, I think the culprit is in this line https://github.com/rancher/ui/blob/da5ef3345dedfba9031d2f8f3fb7511df2fe4840/lib/shared/addon/components/cluster-driver/driver-azureaks/component.js#L21

I would love to submit a PR myself, but can anyone point me to a doc to build rancher for testing? thanks!

**Comment by deniseschannon** [comment]
@westlywright can we also backport this into 2.4? I left it into the 2.5 milestone due to where we are in the release.

**Comment by soumyalj** [comment]
Reproduced the issue with Rancher v2.4.8
1. Create a AKS cluster with advance settings - **Network Plugin : azure, Network Policy: Calico and selecting a Virtual network** 

![Screen Shot 2020-09-14 at 12 26 49 PM](https://user-images.githubusercontent.com/18536626/93129288-98a11c00-f685-11ea-9338-a06f6475efe5.png)

Cluster provisioning fails with the error below:
```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NetworkPolicyNotSupported" Message="NetworkPolicy is not supported (only azure and calico are supported)" Target="networkProfile.networkPolicy"

```
