### ISSUE TITLE
Feature request: Allow for specifying Catalog location thru admin UI.

### ISSUE THREAD

**Issue by srikarm** [rancher/rancher#2672]
Currently one need to update the API via a POST request to change the location of the rancher-catalog repo location. While it works fine, it would be good to have the feature enabled via UI screen. Also, it would be a great feature to set catalog per environment...for example, it our use case, we would like to create an environment for different product groups and have each product group have their own catalog. It could be a scenario like Catalog items marked as generally available to all + items limited to a product group/environment. By default all environments would inherit default catalog but admin could change that to specific repo...

**Comment by vincent99** [comment]
This is several different requests..
  - Supporting more than one catalog repo will be in the next full release (it's actually merged, https://github.com/rancher/rancher-catalog-service/pull/20)
  - Configuring the catalog URL(s) in the UI for admins will probably ship with that.  (Side note: you can go to the API and change the setting with just a browser, you don't actually need API keys and curl or similar...  User menu -> API & Keys -> click Endpoint link and then navigate to `/v1/settings/catalog.url` and click the blue Edit button)
  - Access controls for different catalog items for different people/environments is not in the immediate roadmap.  The catalog service runs as a separate API that has no information about what user or environment the request is for.

**Comment by will-chan** [comment]
Added new feature to track 3rd feature request in #3158.  Closing this issue as the 1st two items have already been released.
