### ISSUE TITLE
New line at the end of configmap

### ISSUE THREAD

**Issue by stex79** [rancher/rancher#26721]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Add a configmap using the web frontend with one or more new lines at the end of it.

**Result:**
It should keep the new lines instead the configmap is trimmed. This causes errors in some services that require a new line at the end of the file.

**Other details that may be helpful:**
If the configmap is created with kubectl the new lines are preserved.

**Environment information**
- Rancher version 2.3.5
- Installation option: HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EC2 Instances
- Machine type (cloud/VM/metal) and specifications (CPU/memory): m5a.xlarge
- Kubernetes version: 1.17.4

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- Docker version:

Client: Docker Engine - Community
 Version:           19.03.7
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        7141c199a2
 Built:             Wed Mar  4 01:22:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.7
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       7141c199a2
  Built:            Wed Mar  4 01:21:08 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by ElGranLoky** [comment]
same problem

**Comment by stex79** [comment]
I have found a workaround that does not force to use kubectl from cli, by doing "View/Edit YAML".

I still think this should be fixed.

**Comment by graham-web** [comment]
I'm seeing this too (Rancher 2.4.5)

The configmap yaml generated looks like
```
data:
  mykey: |-
    my config map data that needs to end in newline
```

Directly editing the yaml to remove the "chomping indicator" (i.e. change `|-` to `|`) works, but when I edit again via Rancher's UI this always gets changed back to `|-` .

**Comment by prashantnitt07** [comment]
soluation : 

kubectl get cm configmap_name -o yaml > cm.yaml

Now copy the contents of cm.yaml file and past it on [yamllint.com](http://www.yamllint.com/). Yamllint.com is powerful tool to check the linting of yaml files.

This will provide you with the configmap as expected with correct formatting.

Paste the output in another yaml file (for e.g - cm_ready.yaml)

 kubectl apply -f cm_ready.yaml

my side is working . when will be edit , use cm_ready.yaml file and apply

**Comment by Benly-walter** [comment]
This is still an issue in rancher v2.8.5
