### ISSUE TITLE
Monitoring - Update API metrics to fix missing kube-apiserver graphs in RKE/K8s 1.17.x

### ISSUE THREAD

**Issue by chrisreed87** [rancher/rancher#26724]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
- Provision a new RKE cluster in Rancher 2.4.2 / Kubernetes 1.17.x
- Enable cluster monitoring
- Navigate to Grafana Kubernetes Components page

**Result:**
api-server related graphs are unpopulated due to deprecated metrics in 1.17.x
    "apiserver-request-count", 
    "apiserver-request-latency",

According to - https://github.com/kubernetes/kubernetes/pull/76496 - they have been replaced with updated metrics

e.g.
```
* `apiserver_request_latencies` -> `apiserver_request_duration_seconds`
* `apiserver_dropped_requests` -> `apiserver_dropped_requests_total`
* `apiserver_storage_transformation_latencies_microseconds ` -> `apiserver_storage_transformation_duration_seconds`
* `apiserver_storage_data_key_generation_latencies_microseconds` -> `apiserver_storage_data_key_generation_duration_seconds`
* `apiserver_request_count` -> `apiserver_request_total`
```

**Other details that may be helpful:**
- https://github.com/kubernetes/kubernetes/pull/76496
- https://github.com/rancher/rancher/issues/25201

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.2
- Installation option (single install/HA): both

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
v1.17.4
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by mrajashree** [comment]
[This](https://github.com/rancher/system-charts/pull/185) PR will replace `apiserver_request_count` with `apiserver_request_total` using recording rule. But the recording rule replacement for `apiserver-request-latency` didn't work

**Comment by deniseschannon** [comment]
Brought into Monitoring v0.1.1.

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher
- `v2.4-3036-head` and
-  `master-3034-head` 

with monitoring chart version `0.1.1`  

on clusters with k8s version 
- `v1.17.6-rancher1-1` and 
- `v1.18.3-rancher1-1`

Steps:
- run Rancher server, single install
- edit the system chart to point to branch `dev-v2.5`
- provision a cluster 
- enable the cluster monitoring 

Results:

- the `Kubernetes Components Metrics` section in Rancher UI
<img width="1396" alt="Screen Shot 2020-05-26 at 11 21 14 AM" src="https://user-images.githubusercontent.com/6218999/82936211-1a3c3500-9f43-11ea-907e-28fe7e0db9fb.png">

- the `Kubernetes Components` section in Grafana UI
<img width="1808" alt="Screen Shot 2020-05-26 at 11 23 05 AM" src="https://user-images.githubusercontent.com/6218999/82936356-51aae180-9f43-11ea-8d01-2de99ead7d78.png">

**Comment by jiaqiluo** [comment]
here is why the above behavior happens:

We added a new logic in the monitoring chart `0.1.1` to use different sets of APIs for different k8s versions, which is calculated and applied at the time of enabling the cluster monitoring.

Upgrading the k8s version of a cluster does NOT cause apps to be re-deployed.

So, if we enable monitoring in the k8s 1.16 cluster and then upgrade the k8s to 1.17/1.18, the monitoring apps will still try fetching data from deprecated APIs, which of course will NOT work.


Since we support multiple k8s version in one release, for example, 1.16, 1,17, and 1.18, there should be no need to re-install the monitoring if we just upgrade the k8s version of a cluster.
