### ISSUE TITLE
Remove trash icon is missing when I delete host that has services assoicated

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2673]
Version - Masters with reskin UI

Steps:
1.  Create a new Environment
2.  Add a single host 
3.  Create a stack and add a service, start it
4.  Deactivate & delete host
5.  Go to container's page

Results:  Notice the trash icon is missing on some of the containers being removed.
![image](https://cloud.githubusercontent.com/assets/11514927/11156876/a37d2a6a-8a0b-11e5-8a39-c6dad603ba6b.png)

Expected:  the remove icon should be consistent

**Comment by deniseschannon** [comment]
It's a mix of icons of trash cans and the other icon as the service keeps trying to deploy containers.

<img width="320" alt="screen shot 2015-11-24 at 10 11 42 pm" src="https://cloud.githubusercontent.com/assets/11410997/11389746/61bff94a-92f8-11e5-8a99-853afc7b1c2b.png">
