### ISSUE TITLE
Cannot add expression alert rule while cluster is pending: "if you want to use metric alert, need to enable monitoring for cluster"

### ISSUE THREAD

**Issue by sauber** [rancher/rancher#26737]
**What kind of request is this (question/bug/enhancement/feature request): bug

**Steps to reproduce (least amount of steps as possible): 
Create cluster
Enable monitoring
Add Alert Rule
Expression: kube_daemonset_status_desired_number_scheduled
Create

**Result: if you want to use metric alert, need to enable monitoring for cluster 

**Other details that may be helpful:**
Monitoring is enabled, cluster is still in pending status

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.2 (and any older)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): No nodes created
- Kubernetes version (use `kubectl version`): Not installed

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by anouarchattouna** [comment]
Same behaviour using 
* Rancher v2.4.2
https://github.com/rancher/rancher/issues/26446#issuecomment-611406000
