### ISSUE TITLE
Rancher2.3.X can't click the "Use a custom Fluentd regex" button

### ISSUE THREAD

**Issue by zerchin** [rancher/rancher#26731]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
  1. Add a custom cluster
  2. Enable project level logging
  3. Deploy any workload, add "Read log files from a directory" volume, log format select "Use a custom Fluentd regex"
![image](https://user-images.githubusercontent.com/29743207/79821764-27a15500-83c2-11ea-8fda-a4c046448a29.png)

**Result:**  I can't click the "Use a custom Fluentd regex" button

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.x
- Installation option (single install/HA):single

**Comment by izaac** [comment]
Validated in

- Rancher `master-head (05/12/2020)` commit id: 5a2a78e73
- Rancher `v2.4-head (05/12/2020)` commit id: 65b520517

![Screen Shot 2020-05-12 at 9 40 55 AM](https://user-images.githubusercontent.com/27659/81723664-0e774b80-9438-11ea-8ce8-6f0d57513d67.png)

I was able to configure a volume using "Read log files from a directory" option. And configure a custom fluentd regex.
