### ISSUE TITLE
UI Banners Not Present On Login Page

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#26746]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug - related to rancher/rancher#25694

**Steps to reproduce (least amount of steps as possible):**
Enable the ui-banners setting with the following blob

```
{
  "banner": {
    "textColor": "#000000",
    "background": "#d71a1a",
    "text": "Classified"
  },
  "showHeader": "true",
  "showFooter": "false"
}
```
Logout

**Result:**
The ui-banners should still be present on the login page.

**Other details that may be helpful:**
Currently I've disabled fetching the setting in the `detect` method so it does not display by default. Additionally the root cause of the bug is the fact that the element for the component is null so its not being targeted correctly when we display it and none of the styles apply.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by gaby** [comment]
I'm interested in this same issue, any updates?

**Comment by gaby** [comment]
Why was this ticket closed? @jiaqiluo It's still relevant.

**Comment by gaby** [comment]
Still valid 🙃
