### ISSUE TITLE
Up to date shouldn't be selectable (and when selected, text is unreadable)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2675]
Version - Master with reskin UI

Steps:
1.  Add a catalog and make sure it's up to date
2.  Click on Up to date button

Results: Can select the button and text is unreadable
![image](https://cloud.githubusercontent.com/assets/11514927/11160158/af41d356-8a23-11e5-985a-87c8f8aafaf5.png)

Expected: Shouldn't be selectable?  Plus the light blue on white is unreadable.

**Comment by westlywright** [comment]
@tfiduccia this seems to be resolved on my latest local version of master so i assume it will be launched today.

**Comment by lvuch** [comment]
I resolved that a couple days ago

**Comment by lvuch** [comment]
<img width="162" alt="screen shot 2015-11-20 at 4 30 01 pm" src="https://cloud.githubusercontent.com/assets/3013118/11314573/087a4efa-8fa4-11e5-82d9-8a9cae2308bf.png">

cursor style changed as well

**Comment by deniseschannon** [comment]
Verified with latest in the evening of 11/24. When you hover over the button, it's disabled and has a sign to indicate you can't click on it.
