### ISSUE TITLE
Duplicated node names in node list page in some clusters

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#26760]
rancher/rancher:v2.3.6

Steps:

1. Create host in Aliyun
2. Create a custom cluster

Results:

![image](https://user-images.githubusercontent.com/21168270/79981876-fe72e880-84d7-11ea-85dc-1dcd5bf4812d.png)

Expected:

The host name format is `cn-shenzhen.i-x5xxxxxx`. In Rancher, we will take the prefix. But in this case, we need to fallback to suffix

**Comment by DoNotSayYes** [comment]
Tested on rancher: `master-head`

In this case, are we supposed to take the whole IP as a suffix? And the node names should be the IP addresses.

![image](https://user-images.githubusercontent.com/57614736/81503941-18565d00-9319-11ea-9e53-5c65d7c5c7e4.png)

![image](https://user-images.githubusercontent.com/57614736/81504365-58b6da80-931b-11ea-8cba-7bd94c3feed1.png)

**Comment by DoNotSayYes** [comment]
Verified on `rancher/rancher:master-head` off 12th May, showing the whole hostname
![image](https://user-images.githubusercontent.com/57614736/81671466-9a5e9700-947b-11ea-921c-0d011150a71d.png)

Verified on `rancher/rancher:v2.4-head` off 12th May, showing the whole hostname
![image](https://user-images.githubusercontent.com/57614736/81672070-34beda80-947c-11ea-9e9d-8cfc5ed61180.png)
