### ISSUE TITLE
Editing Ingress Snippets in cluster.yaml removes line breaks

### ISSUE THREAD

**Issue by fabiorauber** [rancher/rancher#26765]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Edit a cluster configuration in Rancher 2 as YAML
2. Configure multiline strings in ingress.options section (like http-snippet or location-snippet)
3. Click Save 

**Result:**
"nginx-configuration" ConfigMap is garbled, and nginx-ingress-controller cannot apply it. When inspecting, you can see the snippet line breaks were removed.

**Other details that may be helpful:**
Example for the ingress section:

```
ingress:
    options:
      http-snippet: >-
        # caching time for different response codes
        proxy_cache_path /var/lib/nginx/cache levels=1:2 keys_zone=cache:10m
        max_size=4g inactive=360m use_temp_path=off;
        proxy_cache_key $host$request_uri$is_args$args;
        proxy_cache_valid 200 301 302 1m;
        proxy_cache_revalidate on;
```
If you add a "\n" to each line, it works:
```
ngress:
    node_selector:
      role: ingress
    options:
      http-snippet: >-
        # caching time for different response codes\n
        proxy_cache_path /var/lib/nginx/cache levels=1:2 keys_zone=cache:10m
        max_size=4g inactive=360m use_temp_path=off;\n
        proxy_cache_key $host$request_uri$is_args$args;\n
        proxy_cache_valid 200 301 302 1m;\n
        proxy_cache_revalidate on;
```

**Environment information**
- Rancher version: v2.4.2 
- Installation option: single install

**Cluster information**
- Cluster type: XCP docker-machine driver hosted VMs
- Machine type: VMs
- Kubernetes version: v1.17.4

- Docker version: 18.6.3

**Comment by vincent99** [comment]
The yaml parser is doing what you asked for.  The `>` means to fold newlines (turn them into single spaces) and the `-` to strip the trailing newline.  You want `http-snippet: |` to preserve newlines in the middle and a single one at the end.
