### ISSUE TITLE
RKE installation k8s cluster error

### ISSUE THREAD

**Issue by kangkang1986** [rancher/rancher#26770]
Error reported when RKE installs k8s cluster
Action taken:
1. Server password free login
2. Server time synchronized
3. Docker accelerator has been added and docker service has been restarted
![image](https://user-images.githubusercontent.com/64191348/80076402-bce94880-857e-11ea-95c2-345f15215b85.png)
![image](https://user-images.githubusercontent.com/64191348/80076441-c96da100-857e-11ea-9eb8-b85465cc9983.png)

**Comment by superseb** [comment]
Are the nodes being reused for different clusters? Files that are left behind on the nodes conflict with new installations, as described on https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/. Running `rke remove` will also make sure the nodes are cleaned, so after running `rke remove`, `rke up` can be run again. This will destroy all data.

If this happened randomly on an existing cluster, please provide more info like what RKE version was used to set it up and was it upgraded later, what Kubernetes version, what is the full log of `rke --debug up`.

**Comment by superseb** [comment]
Let me know if this still needs help
