### ISSUE TITLE
In Summary view, sidekick container count keeps going up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2677]
Version - Master with reskin UI

Steps:
1.  Create a service with a couple of sidekicks (start the service)
2.  On main stack screen click on the service to bring up summary view
3.  Close summary view and open a couple of times (each time click on sidekick tab)

Results:
Notice that the container o keeps adding one each time you open and close the summary view,  This has 1 container, and now it's showing 5
![image](https://cloud.githubusercontent.com/assets/11514927/11160751/95432bfa-8a2b-11e5-9f0f-21c2b6ba3173.png)

Expected:
Count to not increase.

**Comment by vincent99** [comment]
@wes can you look at this.. there's probably an array not being cleared when the component model changes.

**Comment by tfiduccia** [comment]
Version - master with newest reskin
Verified fixed
