### ISSUE TITLE
Istio v2 Install base

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#26786]
Create a helm chart for Istio 1.6 which installs the operator, this will allow for fresh install or upgrade of Istio via Rancher, which can be managed via the UI. 

- [x] 1) Create a chart which installs istio with an IstioOperator CR. The chart must pass the users desired values into an IstioOperator resource. Then we run the [verify-install](https://istio.io/docs/reference/commands/istioctl/#istioctl-verify-install) command. 
- [x] 2) Ensure upgrade strategy to next release is valid
- [x] 3) Create a drone pipeline to build installer image.
- [x] 4) Add chart to dev charts
- [x] 5) Add cluster roles

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4.6-rc6
rancher/rancher:master-d19f179c4ff15bb782e27ed50d33d169dad79f80-head

The istio install base is working correctly: installing the `rancher-istio-installer` chart creates the IstioOperator CR and installs Istio correctly with the user-specified values and overlays. 

Fresh installs (1.6.5/6/7) and upgrades (1.6.5 -> 1.6.6/7) were checked.

Roles were checked with the RBAC automation framework.
