### ISSUE TITLE
Validate Ubuntu 20.04

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#26783]
https://ubuntu.com/blog/ubuntu-20-04-lts-arrives

Validate Ubuntu 20.04 Focal Fossa

According to Docker, packages will be created for the next Docker release (20.xx) (https://github.com/docker/docker-ce-packaging/pull/443#issuecomment-618340415)

Edit: they now backported the PR to 19.03 (https://github.com/docker/docker-ce-packaging/pull/464), so the next 19.03 should be available on Focal as well: 

gzrancher/rancher#9321

**Comment by Remigius2011** [comment]
can we please get an ETA on this?

**Comment by mxschmitt** [comment]
If the [docker-install](https://github.com/rancher/install-docker) script gets updated to 19.03.09 then it works with Ubuntu 20.

See here: https://github.com/mxschmitt/ui-driver-hetzner/issues/91#issuecomment-630628178

cc @superseb

**Comment by superseb** [comment]
Not really sure why this has not been released as previous releases, no github release and no docs. Just a packaging tag and GitHub comments, I assume this will be done soon. I created a draft PR for the install script.

**Comment by aaronRancher** [comment]
Ubuntu 20.04 has been validated with Rancher server `rancher\rancher:master-head` `version d9184e914`and Rancher server `rancher\rancher:v2.4-head` `version aae934198`

Validated single install and HA install with k8s `version 1.18`

**Comment by aaronRancher** [comment]
Ubuntu 20.04 has been validated with Rancher server `rancher\rancher:v2.4.4`
Docker version `19.03.11`
k8s version `1.17.6`
