### ISSUE TITLE
Feature flag restart for dashboard restarts all rancher pods at once

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#26787]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Disable (or activate) Dashboard feature flag

**Result:**
Appears all (2 in this case) rancher pods restart at the same time. For HA, it should do a rolling restart of rancher pods. Not all at once.

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/468462/80138695-0a06f380-855a-11ea-9796-b1ccdfb294f4.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.2
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
AWS m5.large (2vpu, 8gb ram)
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+k3s1", GitCommit:"3eee8ac3a1cf0a216c8a660571329d4bda3bdf77", GitTreeState:"clean", BuildDate:"2020-03-25T16:13:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
NA, using containerd

gzrancher/rancher#9721

**Comment by maggieliu** [comment]
No longer valid because starting 2.5 this flag will be removed
