### ISSUE TITLE
[ui] Can't remove Authorized Users

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#2679]
Hoho,
I try to remove Authorized Users within *Access Control* > *Site Access*.
When I click on the round **x** beside of any user the only thing happening is that the "save" button becomes active but the user is still there.

**Comment by deniseschannon** [comment]
Using Rancher v0.44.0, I have reproduced with GitHub authentication.

@tfiduccia Could you check to see if the new UI still has this issue?

**Comment by tfiduccia** [comment]
Version - master with latest reskin UI
User is removed when clicking on x.  But you still have to click on Save to remove them permanently.
