### ISSUE TITLE
Worker node fails to register in a custom rke cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26790]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a custom cluster in 2.3.6 k8s - 1.17.4-rancher1-2
- Upgrade rancher server to 2.4.3-rc2
- Upgrade k8s version to 1.17.5
- Add a worker node to the cluster
- the node is stuck in registering state
- Logs of `share-mnt` container on the node

```
Error: failed to start containers: kubelet
+ sleep 2
+ docker start kubelet
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
```

**Expected Result:**
Kubelet should be deployed on the node
And the worker node should get registered.

**Other details that may be helpful:**

- This was not reproducible on an addition of a worker node in a node driver AWS cluster.
- Reproduced this issue on an addition of the Second worker node in an upgraded cluster in a single node install. This was right after rancher server upgrade. No k8s upgrade was done on the cluster. K8s on this cluster - v1.17.4

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.6 to 2.4.3-rc2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom-rke
- Kubernetes version (use `kubectl version`):

```
1.17.5
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by mcmcghee** [comment]
I'm seeing this same issue on 2.4.2 and 1.17.4. It happens completely randomly on the provision of a new cluster and only on 2-3 nodes.

**Comment by izaac** [comment]
I experienced this after upgrading from `v2.4.2` to `v2.4.3-rc2` in a Custom cluster.

**Comment by zbialik** [comment]
I experienced this after upgrading from `v2.3.2` to `v2.4.2` in a Custom cluster. 

I wrote [this issue post](https://github.com/rancher/rancher/issues/26776) outlining some more specific information.

**Comment by aaronRancher** [comment]
Reproducible in a single node fresh install of v2.4.3-rc2.
Steps:
Provision 1 node custom cluster (all roles)
Add 1 worker node (succeeded)
Add 1 worker node (failed, stuck provisioning)
Error from `share-mnt`:
```
+ docker start kubelet
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
```
Upon further attempts, this seems to happen randomly.

**Comment by sowmyav27** [comment]
**Able to reproduce this issue on 2.4.2**

- 1 all roles node custom cluster
- add a worker node. It fails to register

```
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
+ docker start kubelet
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
+ docker start kubelet
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
```

**Comment by kinarashah** [comment]
@StrongMonkey seems like this is happening when DockerRootDir for the host is empty when node's plan is calculated, so kubelet fails to start up.

**Comment by StrongMonkey** [comment]
@kinarashah Thanks for putting the fix. The fix specifically addresses this issue where rancher-agent will have the following error:
```
time="2020-04-23T15:20:40Z" level=error msg="Remotedialer proxy error" error="Error response from daemon: invalid bind mount spec \"::rw,rslave,z\": invalid volume specification: '::rw,rslave,z'"
```

@sowmyav27 @izaac @aaronRancher Can we check that when you were able to reproduce this issue, the rancher-agent container will have the error above? Last time I checked with @izaac 's setup and found there is no such error on his setup, so wondering if there is another potential bug.

**Comment by StrongMonkey** [comment]
related https://github.com/rancher/rancher/issues/23254#issuecomment-612144907.

**Comment by sowmyav27** [comment]
**Hit the issue in `rancher:v2.4.2`** 

- Deploy a cluster - 1 node all roles - custom cluster.
- Add a worker node.
- The worker node is stuck in registering state
- One of the agent logs show the error

```
time="2020-04-27T16:59:11Z" level=error msg="Remotedialer proxy error" error="Error response from daemon: invalid volume specification: '::rw,rslave,z'"
```

**Comment by kinarashah** [comment]
Looks like @sowmyav27 is hitting the same issue that I saw, @izaac @aaronRancher could you guys confirm this as well?

**Comment by aaronRancher** [comment]
Reproduced the issue in `rancher:v2.4.3-rc2`
```
ubuntu@ip-####:~$ docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
76b01e3e794d        rancher/rke-tools:v0.1.56            "nginx-proxy CP_HOST…"   6 minutes ago       Up 6 minutes                            nginx-proxy
c98c1f7c62d5        rancher/rancher-agent:v2.4.3-rc2     "run.sh --server htt…"   9 minutes ago       Up 9 minutes                            upbeat_booth
b79a91d670df        rancher/hyperkube:v1.17.5-rancher1   "/opt/rke-tools/entr…"   10 minutes ago      Up 10 minutes                           kube-proxy
700f59c7a470        rancher/rancher-agent:v2.4.3-rc2     "run.sh -- share-roo…"   10 minutes ago      Up 9 minutes                            share-mnt
ad60cc5eae8f        rancher/rke-tools:v0.1.56            "/bin/bash"              10 minutes ago      Created                                 service-sidekick
6674d4a63e36        rancher/rancher-agent:v2.4.3-rc2     "run.sh --server htt…"   11 minutes ago      Up 11 minutes                           vibrant_moore
```
Logs of second rancher/rancher-agent:v2.4.3-rc2 :
```
time="2020-04-27T17:06:32Z" level=error msg="Remotedialer proxy error" error="Error response from daemon: invalid volume specification: '::rw,rslave,z'"
```
Logs of share-mnt container:
```
+ docker start kubelet
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
```

**Comment by sowmyav27** [comment]
Hit the issue on an upgrade from 2.3.6 - 2.4.3-rc2

Have a custom cluster - 1 node all roles in 2.3.6
Upgrade to 2.4.3-rc2
Add 4 worker nodes.
Add 3 worker nodes.
Hit the issue here.
the worker nodes are stuck in Registering state.
Agent logs:
```
time="2020-04-27T18:25:16Z" level=error msg="Remotedialer proxy error" error="Error response from daemon: invalid volume specification: '::rw,rslave,z'"
```
- docker ps -a
```
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
d0ea83bda9f8        rancher/rke-tools:v0.1.56            "nginx-proxy CP_HOST…"   4 minutes ago       Up 4 minutes                            nginx-proxy
3c54dc9ca75d        rancher/rancher-agent:v2.4.3-rc2     "run.sh --server htt…"   4 minutes ago       Up 4 minutes                            hopeful_hermann
3c1fcf7ec610        rancher/hyperkube:v1.17.4-rancher1   "/opt/rke-tools/entr…"   5 minutes ago       Up 5 minutes                            kube-proxy
4f47e05cbef9        rancher/rancher-agent:v2.4.3-rc2     "run.sh -- share-roo…"   5 minutes ago       Up 4 minutes                            share-mnt
74870b6a8f7f        rancher/rke-tools:v0.1.56            "/bin/bash"              5 minutes ago       Created                                 service-sidekick
95fa31f45560        rancher/rancher-agent:v2.4.3-rc2     "run.sh --server htt…"   6 minutes ago       Up 6 minutes                            interesting_driscoll
```
- `share-mnt` container logs
```
+ docker start kubelet
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
```

**Comment by izaac** [comment]
**Repro the issue on an upgrade from 2.4.2 - 2.4.3-rc2**

 Self-signed certificates Rancher 
- Have a custom cluster - 1 etcd, 1 control plane, 3 workers
- Upgrade to 2.4.3-rc2
- Add 5 worker nodes.
- Hit the issue here.
- the worker nodes are stuck in Registering state.
- Agent logs:

```
time="2020-04-27T18:41:40Z" level=error msg="Remotedialer proxy error" error="Error response from daemon: invalid volume specification: '::rw,rslave,z'"
```

- docker ps -a

```
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
a2baf1f2b5de        rancher/rke-tools:v0.1.56            "nginx-proxy CP_HOST…"   8 minutes ago       Up 8 minutes                            nginx-proxy
02f517068bee        rancher/rancher-agent:v2.4.3-rc2     "run.sh --server htt…"   9 minutes ago       Up 9 minutes                            hopeful_golick
2f5a269234c4        rancher/hyperkube:v1.17.4-rancher1   "/opt/rke-tools/entr…"   9 minutes ago       Up 9 minutes                            kube-proxy
284997cce273        rancher/rancher-agent:v2.4.3-rc2     "run.sh -- share-roo…"   10 minutes ago      Up 9 minutes                            share-mnt
2524bbea6db3        rancher/rke-tools:v0.1.56            "/bin/bash"              10 minutes ago      Created                                 service-sidekick
a988ff7b6d19        rancher/rancher-agent:v2.4.3-rc2     "run.sh --server htt…"   10 minutes ago      Up 10 minutes                           amazing_ganguly
```

- `share-mnt` container logs
```
+ docker start kubelet
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
```

**Comment by jcwimer** [comment]
Upgrade from 2.3.5 to 2.4.2

Using Openstack driver, a new cluster can be built. New workers get the below errrors. All nodes are running Ubuntu Bionic.

Old (spun up by 2.3.5) clusters cannot add a worker either. Seeing the same errors. 

All nodes share OS version and docker version.

`docker version`
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

`docker ps -a`
```
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
a0b5ecdf6532        rancher/hyperkube:v1.17.4-rancher1   "/opt/rke-tools/entr…"   4 minutes ago       Up 4 minutes                            kube-proxy
916c68e0ec5b        rancher/rancher-agent:v2.4.2         "run.sh --server htt…"   5 minutes ago       Up 5 minutes                            elated_turing
43a4ec6a39a6        rancher/rke-tools:v0.1.56            "nginx-proxy CP_HOST…"   5 minutes ago       Up 5 minutes                            nginx-proxy
f0fe23cf92d9        rancher/rancher-agent:v2.4.2         "run.sh -- share-roo…"   5 minutes ago       Up 5 minutes                            share-mnt
141a6646afc0        rancher/rke-tools:v0.1.56            "/bin/bash"              5 minutes ago       Created                                 service-sidekick
c7bbfb6d84ed        rancher/rancher-agent:v2.4.2         "run.sh --server htt…"   5 minutes ago       Up 5 minutes                            exciting_fermi
```
Agent logs:
`time="2020-04-29T15:22:59Z" level=error msg="Remotedialer proxy error" error="Error response from daemon: invalid volume specification: '::rw,rslave,z'"`

`share-mnt` logs
```
+ docker start kubelet
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
```

**Comment by sowmyav27** [comment]
**Verified the following:**

Upgraded from 2.3.5, 2.3.6, 2.4.2 to 2.4.3-rc3 (each)

- HA setup with custom cluster with 1 node all roles and 1 dedicated worker node.
- Upgrade to 2.4.3-rc3
- There were no kubelet restarts
- Add additional worker nodes.
- User is able to add additional worker nodes
- Create new  custom cluster with 1 node all roles.
- Add more worker nodes.
- User is able to add additional worker nodes
