### ISSUE TITLE
private registry functionality is broken when credentials are required

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#26795]
# Description

Yesterday with a customer we stumbled upon this problem which very likely is a bug. We configured a windows/linux cluster and started off with an unauthenticated private registry. Now when we wanted to migrate to the authenticated one to reach the compliance level of their company, it can pull with the pullsecrets provided the main image. But it fails to pull  the system images.

# Error details

```
FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "artefact-repo.de:5001/rancher/pause:3.1": Error response from daemon: Get https://artefact-repo.de:5001/v2/rancher/pause/manifests/3.1: no basic auth credentials FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "artefact-repo.de:5001/rancher/pause:3.1": Error response from daemon: Get https://artefact-repo:5001/v2/rancher/pause/manifests/3.1: no basic auth credentials
```

As you can see it complains about the pause container. It can indeed not deploy a **single** container and is ignoring the authentication (via rancher cluster settings (rke)) completely for some reason as the error states no credentials provided...
We tried a few different accounts to make sure there is no problem with special characters in the username, but whatever we set, it will fail to utilize this credentials and use them properly for pulling the system images.

# Environment

OS: Linux (CentOS)
Rancher: v2.3.6
K8s: v17.x

**Comment by janeczku** [comment]
Hi @wzrdtales, could you provide the exact steps allowing us to reproduce the issue? Thanks!

**Comment by wzrdtales** [comment]
it turned out back then, that there is a problem with special characters in the name of the user "~" in this case. But only from the private registry option side, not everywhere else

**Comment by wzrdtales** [comment]
no one looked at it again that there is problem with special chars in the username
