### ISSUE TITLE
Charts Updates - MariaDB, Wordpress, Redis, Docker Registry

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#26808]
Helm 2 Charts

This is already in `master` and available today, but we should run 1 check on it. I hadn't paid attention when merging. Apologies.

Wordpress v9.0.3
MariaDB v7.3.14
Redis v10.6.4
Docker Registry v1.9.2

Helm 3 Charts

MariaDB v7.3.14 - located in the `dev` branch of https://github.com/rancher/helm3-charts

**Comment by jiaqiluo** [comment]
It is validated in v2.4.3-rc2 that all those new versions show up and the apps can be deployed and work.
