### ISSUE TITLE
In the rancher pipeline, Jenkins slave network created by Jenkins master seems to be problematic

### ISSUE THREAD

**Issue by LivesMountain** [rancher/rancher#26816]
"""
Hello, the Jenkins slave created by Jenkins master while I was using rancher pipeline looks like there is no network.But the docker-registry network automatically created in the same namespace seems to be ok.What can I do to solve this problem？thanks 
"""
'''
This is the complete Jenkins build log and errors
‘’‘’
 
![image](https://user-images.githubusercontent.com/19382017/80297600-22c01500-87b7-11ea-88bb-2ca840223a16.png)

[jenkinslog.txt](https://github.com/rancher/rancher/files/4534589/jenkinslog.txt)
‘’‘
So these are some of the information 
‘’’
![123123](https://user-images.githubusercontent.com/19382017/80298056-45542d00-87bb-11ea-8981-1ea77b8b1285.jpg)

![image](https://user-images.githubusercontent.com/19382017/80297544-901f7600-87b6-11ea-8f8a-4e6234ec4892.png)
![image](https://user-images.githubusercontent.com/19382017/80297444-94975f00-87b5-11ea-9405-190952b79bfb.png)
![image](https://user-images.githubusercontent.com/19382017/80297718-78e18800-87b8-11ea-9ad1-31bd4d9084bb.png)
![image](https://user-images.githubusercontent.com/19382017/80297721-7d0da580-87b8-11ea-8164-6d6ef5fe2ac1.png)
![image](https://user-images.githubusercontent.com/19382017/80297771-edb4c200-87b8-11ea-8b65-fd11c8443b59.png)

 

**Environment information**
- rancher version:2.3.2

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): aliyun cloud ,4 cpu,32g mem
- Kubernetes version (use `kubectl version`):v1.15.5

- Docker version (use `docker version`):18.09.8

```
dockerfile
FROM docker.source3g.com:5000/ops/python:3.5

COPY . /app

WORKDIR /app

RUN pip install -i https://pypi.douban.com/simple -r requirements.txt

CMD ["/usr/local/bin/python","devops/manage.py","runserver","0.0.0.0:8080"]
pip install django==1.11.7 -i https://pypi.douban.com/simple
```
```
rancher pipeline
stages:
- name: compile
  steps:
  - runScriptConfig:
      image: docker.source3g.com:5000/ops/docker-dind:17.12.1-ce-dind
      shellScript: |-
        echo ${CICD_GIT_REPO_NAME}
        echo ${CICD_GIT_URL}
        echo ${CICD_GIT_COMMIT}
        echo ${CICD_GIT_BRANCH}
        echo ${CICD_GIT_REF}
        echo ${CICD_GIT_TAG}
        echo ${CICD_EVENT}
        echo ${CICD_PIPELINE_ID}
        echo ${CICD_EXECUTION_SEQUENCE}
        echo ${CICD_EXECUTION_ID}
        echo ${CICD_REGISTRY}
        echo ${CICD_IMAGE}

- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: '.'
      tag: ops/devops:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.source3g.com:5000
    env:
      PLUGIN_CUSTOM_DNS: "8.8.8.8"
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: test
  steps:
  - runScriptConfig:
      image: docker.source3g.com:5000/ops/docker-dind:17.12.1-ce-dind
      shellScript: |-
        DOCKER_REPO=docker.source3g.com:5000/ops/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}
        echo ${DOCKER_REPO}
        docker build --network host -t ${DOCKER_REPO} .
        docker push ${DOCKER_REPO}
        echo ${CICD_GIT_REPO_NAME}
        echo ${CICD_GIT_URL}
        echo ${CICD_GIT_COMMIT}
        echo ${CICD_GIT_BRANCH}
        echo ${CICD_GIT_REF}
        echo ${CICD_GIT_TAG}
        echo ${CICD_EVENT}
        echo ${CICD_PIPELINE_ID}
        echo ${CICD_EXECUTION_SEQUENCE}
        echo ${CICD_EXECUTION_ID}
        echo ${CICD_REGISTRY}
        echo ${CICD_IMAGE}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch:
  include:
  - test
notification: {}
```

**Comment by LivesMountain** [comment]
![123123](https://user-images.githubusercontent.com/19382017/80298173-0e324b80-87bc-11ea-96cb-a0ab6ea6c632.jpg)

**Comment by LivesMountain** [comment]
![123123](https://user-images.githubusercontent.com/19382017/80298281-3b332e00-87bd-11ea-9d34-a460af083c7e.jpg)

**Comment by ArgonV** [comment]
I have the same issue, in v2.4.4. Same exact errors as well with the buildpod timeout.

**Comment by ArgonV** [comment]
My co-worker has done some more digging and found some more descriptive logs we believe are related.

Calico-node pod logs:
`[WARNING][43] active_rules_calculator.go 326: Profile not known or invalid, generating dummy profile that drops all traffic. profileID="ksa.p-9pdnx-pipeline.default"[WARNING][43] active_rules_calculator.go 326: Profile not known or invalid, generating dummy profile that drops all traffic. profileID="ksa.p-9pdnx-pipeline.default"`

**Comment by wanghaiqing2015** [comment]
I have the same problem
