### ISSUE TITLE
Imported K3s cluster - Monitoring API is not ready after apps are active

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#26811]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.4.3-rc2 single install
- imported a k3s cluster `v1.17.4+k3s1`
- enable the cluster monitoring 

**Result:**
- after the apps are available, the UI still shows waiting for the API to be ready 
- and it waits a long time to show the graphs in the UI 
- this is the same behavior we saw here: https://github.com/rancher/rancher/issues/26692

**Other details that may be helpful:**
- this is not seen in an imported k3s cluster with an older version (v1.16.3-k3s.2)

**Comment by StrongMonkey** [comment]
@jiaqiluo I can't reproduce it when testing 2.4-head. Are you always able to reproduce this?

**Comment by StrongMonkey** [comment]
Also notice that there are failure scenario where the controller takes maximum 2 minutes to re-sync. So any status cloud be refreshed after 2 minutes.

**Comment by StrongMonkey** [comment]
Actually I am still struggling at reproducing this issue. But https://github.com/rancher/rancher/pull/27054 should potentically fix it. I think the general issue right here is not related to the underlying k3s version. The controller inside rancher has to fetch the download prometheus instances and update cluster status accordingly. While the controller follow the back-off algorithm to sync status, it will eventually fallback to 2 minutes(or other maximum interval). So there is a delay between the real status and the status showing on UI.

@jiaqiluo Let me know if you see that the cluster stays in `not ready` states and never returns to a normal state. My understanding is that it will recover after a certain period. This could happen a lot when cluster is not ready(for example, launched with automation scripts). 

cc @maggieliu

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher
- `v2.4-3036-head` and
-  `master-3034-head` 

with monitoring chart version `0.1.1`  

Steps:
- run Rancher server, single install
- edit the system chart to point to branch `dev-v2.5`
- import a k3s cluster into Rancher, the k3s cluster has 2 servers and 2 workers, and it version is `v1.17.4+k3s1`
- enable the cluster monitoring  `0.1.1`  

Results:
The cluster page shows up graphs right after the monitoring apps are available under system projects 

![Screenshot_2020-05-26 Rancher](https://user-images.githubusercontent.com/6218999/82948800-54afcd00-9f57-11ea-8054-7437598329be.png)
