### ISSUE TITLE
[bug] can't add registry credentials to single namespace

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#26813]
# Description

When I tried to separate the credentials per namespace and wanted to add a credential to an existing namespace, it added it to a different namespace in the same project instead.

When looking into the network request made:

```
name: "geawgwe"
namespaceId: "differentnamespace"
registries: {index.docker.io: {username: "test", password: "test"}}
type: "namespacedDockerCredential"
```

I can see, this is a UI error. For some reason it does not use the selected namespace from the ui and always adds it in our case to the **first element from the dropdown**.

rancher version is 2.3.6

**Comment by wzrdtales** [comment]
ping @superseb

**Comment by soumyalj** [comment]
Reproduced the issue with Rancher version v2.3.6
K8s version : v1.17.4

Steps:
1. Create namespaces ns1 and ns2 in "Default" project
2. Navigate to "Add Registry"  and add  add registry for a specific namespace. Choose namespace "ns1" from the namespace dropdown .

Results:
The registry always gets created for "default" namespace even though a specific namespace is chosen 
![Screen Shot 2020-04-29 at 10 55 28 AM](https://user-images.githubusercontent.com/18536626/80629627-fa7b2500-8a07-11ea-8ba1-2d83961b42ee.png)
Response:
```
{"annotations":{},"baseType":"namespacedSecret","created":"2020-04-29T17:47:45Z","createdTS":1588182465000,"creatorId":"user-fh5xd","id":"default:test2","labels":{"cattle.io/creator":"norman"},"links":{"remove":"https://173.255.242.104/v3/project/c-wlj6r:p-h4fhd/namespacedDockerCredentials/default:test2","self":"https://173.255.242.104/v3/project/c-wlj6r:p-h4fhd/namespacedDockerCredentials/default:test2","update":"https://173.255.242.104/v3/project/c-wlj6r:p-h4fhd/namespacedDockerCredentials/default:test2","yaml":"https://173.255.242.104/v3/project/c-wlj6r:p-h4fhd/namespacedDockerCredentials/default:test2/yaml"},"name":"test2","namespaceId":"default","projectId":"c-wlj6r:p-h4fhd","registries":{"index.docker.io":{"auth":"bmV3dGVzdDpuZXdwYXNz","password":"newpass","username":"newtest"}},"type":"namespacedDockerCredential","uuid":"e35b4187-5bb4-4d43-98db-fda579f1f223"}
```
![Screen Shot 2020-04-29 at 10 55 59 AM](https://user-images.githubusercontent.com/18536626/80629668-0830aa80-8a08-11ea-86ef-f67a50138cea.png)

**Comment by soumyalj** [comment]
Validated with Rancher version v2.4.3-rc3
Steps:
1. Create namespaces ns1 and ns2 in a new project or default project
2. Navigate to "Add Registry" and add add registry for a specific namespace. Choose namespace "ns1" from the namespace dropdown .
**Results:**
Registry gets created in the right name space as specified.

![Screen Shot 2020-04-30 at 2 55 44 PM](https://user-images.githubusercontent.com/18536626/80763124-ae58df00-8af2-11ea-81cf-02de7f178c83.png)

![Screen Shot 2020-04-30 at 2 58 29 PM](https://user-images.githubusercontent.com/18536626/80763299-14456680-8af3-11ea-8579-5ced0505ae96.png)



```
{type: "namespacedDockerCredential",…}
type: "namespacedDockerCredential"
registries: {index.docker.io: {username: "test", password: "pass"}}
name: "test"
namespaceId: "ns1"

```

**Comment by rex** [comment]
This may have been an overcorrection. In the most recent version of rancher (I am testing an upgrade path for my team) we are unable to add registry credentials _except_ to a single namespace. That means we are having to add a set of registry credentials for _every. single. app_ we deploy. Which is, as you can imagine, unsustainable.

**Comment by theAkito** [comment]
@rex 
https://github.com/rancher/rancher/issues/26981#issuecomment-637493461

**Comment by rex** [comment]
@theAkito OMG! Brilliant! Thank you so much for this! I will give it a whirl.
