### ISSUE TITLE
[2.4.2] High memory usage by cattle-cluster-agent pod (Possible memory leak)

### ISSUE THREAD

**Issue by niranjan94** [rancher/rancher#26818]
**What kind of request is this :** bug

**Steps to reproduce:** 
1. Import an EKS cluster
2. Keep using it for sometime (view logs, execute shell, switch projects etc)

**Result:**
Gradually increasing memory usage by the `cattle-cluster-agent` pod (similar to a memory leak ?)

Noticed memory usages ranging from 9 GB to 11 GB over a period of 7 days across 3 clusters.

**Environment information**
- Rancher version: `v2.4.2`
- UI version: `v2.4.14`
- Installation option: single install

**Cluster information**
- Cluster type: Imported
- Machine type: AWS EKS + 3 Linux Nodes + 2 Windows Nodes
- Kubernetes version: 

```
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional information**

Possible #26624 could be related to this.

**Comment by superseb** [comment]
This seems to be the same as https://github.com/rancher/rancher/issues/26633

**Comment by niranjan94** [comment]
@superseb You're right. This is a duplicate of #26633 . Apologies. Did not notice that issue. Thanks for pointing out. 😄
