### ISSUE TITLE
Wrong resource group selected in vSphere node template

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#26820]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Create a vSphere node template for a vSphere cluster with two datacenters that each just have the default Root-Resource Pool
* In the UI, choose the second datacenter or switch back and forth between the datacenters
* The resource pool dropdown correctly only has one entry in both cases, the name of the resource pool is the same, since it is the default root resource pool in each datacenter

**Result:**
When you choose the second datacenter, the resource pool of the first datacenter is added to the node template (visible for example in the API). It should add the resource pool of the chosen datacenter though.

**Other details that may be helpful:**
This could be related to #24507, since the default root resource pool has the same name in both datacenters. It seems that some UI logic then just picks the first one, that matches this name which may be from the wrong datacenter.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.2
- Installation option (single install/HA): HA

**Comment by bashofmann** [comment]
Potentially also related: #24555

**Comment by UberKuber** [comment]
Potentially also related: https://github.com/rancher/rancher/issues/26997

**Comment by luthermonson** [comment]
@bashofmann This was the fix for two defaults https://github.com/rancher/rancher/issues/25052
@UberKuber your link is referencing what looks like a UI issue with switching between datacenters, not sure it's related.

**Comment by bashofmann** [comment]
Awesome. I think we can close this issue then since it is fixed in #25052.
