### ISSUE TITLE
[BUG] Alert Expression Metrics Not Populating

### ISSUE THREAD

**Issue by js422** [rancher/rancher#26829]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Install Rancher v2.4.2
1. Enable Monitoring
1. Create `New Alert`
1. Select `Expression` radio button.
1. Attempt to drop-down the list of metrics.

**Result:**

Metrics fields are not populating in the drop-down.

**Other details that may be helpful:**

```See attached image```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): **v2.4.2**
- Installation option (single install/HA): **HA/RKE**

![Screenshot (5)](https://user-images.githubusercontent.com/13205645/80396906-5b2d2500-8883-11ea-8c4f-e16354c55f33.png)

**Comment by mrajashree** [comment]
@maggieliu from discussion with @westlywright this appears to be a UI bug

**Comment by sangeethah** [comment]
@codyrancher Can you add the PR for 2.4 release branch to this issue?

**Comment by sangeethah** [comment]
https://github.com/rancher/ui/pull/3943

**Comment by izaac** [comment]
Rancher version `master-head (04/28/2020)` `master-2821-head` commit id: 14013a8d0

I was able to select expression, the dropdown gets populated in a second and no errors in the browser devtools console and network.
Rule was successfully added and I was able to also remove it.
