### ISSUE TITLE
What the alert architecture looks like and how to implement it. Is there any documentation? Thank you

### ISSUE THREAD

**Issue by zhifei92** [rancher/rancher#26824]
I would like to know the implementation details of the alert.

**Comment by gmolkvk** [comment]
afaik

AlertRule CustomResource (CR) creates a PrometheusRule CR, which may create an Alert CR. The alertmanager in the System project watches for the Alert CR and sends it out on linked Notifier(s)

**Comment by zhifei92** [comment]
thank you
