### ISSUE TITLE
FR: Granular Access Control for Secrets in Rancher UI

### ISSUE THREAD

**Issue by Rancheroo** [rancher/rancher#26849]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Secrets access in Rancher is currently binary, 1 you have access, 0 you don't have access

**Result:**
Limited Flexibility in managing secrets

**Other details that may be helpful:**
Suggestion would be
By default, secrets would be viewable and editable in the UI. Several levels of "protection" could be enabled:
* default = create/edit/view secrets in the UI (with click/hover-to-show)
* no-view = create/edit (if user has sufficient permission). No viewing.
* create-only = Rancher 1.6 behavior. Create secrets only, no edit, no viewing.

I think that the RFE for the secrets viewing/editing/create-only configuration option, should be configurable at the Global, Cluster, and Project levels -- that way organisations with different requirements can set it as necessary. In our case, we would likely set the default for Global and Cluster, and have certain Projects use the "create-only" behavior.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

gz#9203

**Comment by vincent99** [comment]
This is not the reality of how kubernetes works.  There are no "write-only" fields in k8s; anything we do would either be superficial in the UI only, or break the API and kubectl and everything else that depends on it.

This is all ineffective anyway (as it also was in 1.x), because if you can see the secret exists you can use it in a pod spec and then just read the secret out of that container.
