### ISSUE TITLE
Provision New Host: Rackspace API Error (403)

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#2685]
All attempts to provision a new Rackspace host result in a 403 error.

**Comment by deniseschannon** [comment]
What version are you running? Are you behind a proxy? 

I was able to deploy Rackspace with no issues myself.

**Comment by bacheson** [comment]
latest stable (v0.44.0). No proxy. I am able to provision on packet.net and digital ocean without issue.

**Comment by deniseschannon** [comment]
Can you paste the rancher-server logs for when you try to add a rackspace host? It shoudl show the docker-machine command that Rancher is using.

Please hide your rackspace credentials with a `XXX`.

**Comment by bacheson** [comment]
The problem appears to be explained in this thread: https://community.rackspace.com/developers/f/7/t/5143

When certain Rackspace compute flavours are create, rancher is not defining the boot disk

Logs:
time="2015-11-18T20:07:00Z" level=info msg="Creating Machine" eventId="a36aa832-8d71-4a2c-b669-784de6cce578" resourceId=1ph5 
time="2015-11-18T20:07:00Z" level=info msg="Cmd slice: [create -d rackspace --rackspace-api-key ***************** --rackspace-flavor-id compute1-60 --rackspace-region ORD --rackspace-username ********* rancher-slave-2]" 
time="2015-11-18T20:07:00Z" level=info msg="stdout: Creating CA: /var/lib/cattle/machine/37652f72-21d8-460f-b2d9-5bb6d1e570ca/certs/ca.pem" resourceId: =1ph5 
time="2015-11-18T20:07:01Z" level=info msg="stdout: Creating client certificate: /var/lib/cattle/machine/37652f72-21d8-460f-b2d9-5bb6d1e570ca/certs/cert.pem" resourceId: =1ph5 
time="2015-11-18T20:07:03Z" level=info msg="stdout: Creating machine..." resourceId: =1ph5 
time="2015-11-18T20:07:03Z" level=info msg="stderr: Error creating machine: Expected HTTP response code [201 202] when accessing [POST https://ord.servers.api.rackspacecloud.com/v2/959462/servers], but got 403 instead" resourceId=1ph5 
time="2015-11-18T20:07:03Z" level=info msg="stderr: {\"forbidden\": {\"message\": \"Policy doesn't allow compute_flavor:create:image_backed to be performed.\", \"code\": 403}}" resourceId=1ph5

**Comment by deniseschannon** [comment]
This is an issue with docker-machine. https://github.com/docker/machine/issues/1773

Since we're just calling the docker-machine command, there isn't much that Rancher can do. I'll close it and you can comment on the docker-machine issue.
