### ISSUE TITLE
ERROR: https://localhost/ping is not accessible (Failed to connect to localhost port 443: Connection refused)

### ISSUE THREAD

**Issue by AndriyKalashnykov** [rancher/rancher#26852]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Install GKE cluster with Rancher 2.4.2 

**Result:**
cattle-cluster-agent stuck in "Updating" state with message "Deployment does not have minimum availability." with CrashLoopBackOff

cattle-node-agent stuck in "Upgrading workload" with CrashLoopBackOff

**Other details that may be helpful:**

Logs:

INFO: Environment: CATTLE_ADDRESS=10.60.6.7 CATTLE_CA_CHECKSUM=19fe270bb4288bb634806dd750943559ca0d45b8596b416f7017f407f53aa825 CATTLE_CLUSTER=true CATTLE_FEATURES=dashboard=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-754994b956-hqclv CATTLE_SERVER=https://localhost
INFO: Using resolv.conf: nameserver 10.64.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local c.kube-testing-262302.internal google.internal options ndots:5
ERROR: https://localhost/ping is not accessible (Failed to connect to localhost port 443: Connection refused)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted, GKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud, n1-standard-4 (4 vCPUs, 15 GB RAM), image type: UBUNTU
- Kubernetes version (use `kubectl version`): [1.15.11-gke.9](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.15.md#changelog-since-v11510)

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.9", GitCommit:"e1af17fd873e15a48769e2c7b9851405f89e3d0d", GitTreeState:"clean", BuildDate:"2020-04-06T20:56:54Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
lient: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by soumyalj** [comment]
Tested with Rancher version v2.4.2 
K8s version : v1.15.11-gke.9

1. Created a 3 node GKE cluster in the setup
GKE cluster came up successfully. Cluster agent and node agent were active.
Workload creation also worked fine.

**Comment by AndriyKalashnykov** [comment]
we can set up a session and i can demonstrate it

**Comment by superseb** [comment]
This is the text when configuring Rancher Server URL on first login:

```
Rancher Server URL
What URL should be used for this Rancher installation? All the nodes in your clusters will need to be able to reach this.```

It appears to be set to `localhost` which can't be used to connect to Rancher (without workarounds). If you didn't set this to `localhost`, please share exact steps taken from starting Rancher to creating the cluster to reach this situation.

**Comment by AndriyKalashnykov** [comment]
@superseb you are correct, i left it at default "localhost" didn't understand the importance. You mentioned workaround? Im running rancher docker image locally

**Comment by superseb** [comment]
This is covered in https://github.com/rancher/rancher/issues/14731, workarounds exists but for no surprises/side effects it probably best to start fresh. Let us know if there is still an issue after having the correct `server-url` configured.
