### ISSUE TITLE
v3.Node.SystemInformation should show "containerRuntimeVersion" instead of a "DockerVersion"

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#26857]
The issue exists on master build off April 29th

Steps to reproduce:

* Launch basic cluster with kind
* Import the cluster to Rancher
* Go to Cluster details -> Node -> Node details - >System Information

One of the fields is "dockerVersion": "containerd://1.3.2". It should be "containerRuntimeVersion": "containerd://1.3.2", as in native k8s v1.Node

![image](https://user-images.githubusercontent.com/1562176/80630948-dc162900-8a09-11ea-85f6-cad46995b08e.png)

**Comment by jiaqiluo** [comment]
The bug is reproduced in v2.4.4

Adding a k3s cluster, and check the node's system info

<img width="1383" alt="Screen Shot 2020-06-16 at 10 22 30 AM" src="https://user-images.githubusercontent.com/6218999/84807073-872f7180-afbb-11ea-81be-a06561774202.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated on Rancher `master-3205-head`

<img width="1386" alt="Screen Shot 2020-06-16 at 12 23 56 PM" src="https://user-images.githubusercontent.com/6218999/84819148-691e3d00-afcc-11ea-9561-929c39ea30f1.png">

**Comment by jiaqiluo** [comment]
Need the fix to be backported into the `v2.4` branch

**Comment by loganhz** [comment]
Hi @jiaqiluo as it's a "small" issue, maybe we could just fix in 2.5. Please move it to a 2.4 milestone if you would like to fix it in 2.4 as well. Thanks!

**Comment by jiaqiluo** [comment]
close this issue since the fix is already validated in master-head and no backport is needed.
