### ISSUE TITLE
[Backport] Can't add registry credentials to single namespace

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#26864]
backport of rancher/rancher#26813

**Comment by soumyalj** [comment]
Validated with Rancher version v2.3.7-rc4
Steps:
1. Create namespaces ns1 and ns2 in a new project or default project
2. Navigate to "Add Registry" and add registry for a specific namespace. Choose namespace "ns1" from the namespace dropdown .
Results:
Registry gets created in the right name space as specified.

![Screen Shot 2020-05-01 at 11 28 24 AM](https://user-images.githubusercontent.com/18536626/80831029-e74e8d80-8b9e-11ea-8d51-886f79172ca3.png)

![Screen Shot 2020-05-01 at 11 25 58 AM](https://user-images.githubusercontent.com/18536626/80831047-efa6c880-8b9e-11ea-817e-6326737c0561.png)
