### ISSUE TITLE
Deleting app launched at the global level doesn't clean up resources

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#26874]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Navigate to Global -> Apps -> Launch
2) Launch the HAProxy app
3) Choose "Cluster" for available roles
4) Delete the app
5) Deploy the app again

**Result:**

Resources not removed after step 4, which causes re-deploying at step 5 to fail with the message that there are duplicated resources.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by NickMRamirez** [comment]
In my test lab, the ClusterRole and ClusterRoleBinding that the HAProxy Helm chart deploys are not removed when the app is deleted. I can't tell if this is specific to an RKE cluster.
