### ISSUE TITLE
Cluster provisioning fails on a RHEL 7.7 setup with selinux enabled on Docker daemon

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#26871]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a RHEL 7.7 node in AWS (RHEL-7.7_HVM_GA-20190723-x86_64-1-Hourly2-GP2). SELINUX should be enabled. 
```
[root@ip-172-31-16-59 ec2-user]# getenforce
Enforcing

```
2. Install upstream docker 19.03
3. Enable selinux on docker daemon using the below commands:
```
echo '{"selinux-enabled": true}' > /etc/docker/daemon.json
systemctl restart docker

```
Verify selinux is enabled by checking docker info: 
```
 Security Options:
  seccomp
   Profile: default
  selinux
```
4. Create single node cluster using the above RHEL 7.7 node 

**Result:**

Cluster provisioning fails. Kubelet fails to come up on the node.
```
2020/04/30 17:49:52 [ERROR] Failed to upgrade worker components on NotReady hosts, error: [Failed to start [kubelet] container on host [172.31.16.59]: Error response from daemon: error setting label on mount source '/var/lib/docker': failed to set file label on /var/lib/docker/containers/1eac2deb74e4dca1b7a4dd2f6c0e380e56e31f86d05c68040e4bf08925e71c4e/mounts/shm: operation not supported]
2020/04/30 17:49:52 [INFO] [controlplane] Now checking status of node ip-172-31-16-59, try #1










2020/04/30 17:50:17 [ERROR] Host ip-172-31-16-59 failed to report Ready status with error: [controlplane] Error getting node ip-172-31-16-59:  "ip-172-31-16-59" not found
2020/04/30 17:50:17 [INFO] cluster [c-qfbhg] provisioning: [controlplane] Processing controlplane hosts for upgrade 1 at a time
2020/04/30 17:50:17 [INFO] [controlplane] Now checking status of node ip-172-31-16-59, try rancher/rancher#1
2020/04/30 17:50:18 [INFO] cluster [c-qfbhg] provisioning: Processing controlplane host ip-172-31-16-59
2020/04/30 17:50:43 [ERROR] Failed to upgrade hosts: ip-172-31-16-59 with error [[controlplane] Error getting node ip-172-31-16-59:  "ip-172-31-16-59" not found]
2020/04/30 17:50:43 [ERROR] cluster [c-qfbhg] provisioning: [controlPlane] Failed to upgrade Control Plane: [[[controlplane] Error getting node ip-172-31-16-59:  "ip-172-31-16-59" not found]]


```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4-head
- Installation option (single install/HA):
Single node cluster

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): RHEL
- Kubernetes version (use `kubectl version`): V1.17.5-rancher1-1

- Docker version (use `docker version`):
19.03

**Comment by jiaqiluo** [comment]
The bug is reproduced in an instance that runs RHEL 7.7, SeLinux ON, Docker 19.03, OverlayNetwork, and `"selinux-enabled": true` for docker

Rancher server: `v2.4.2`
k8s version: `v1.17.4-rancher1-3`

the `container-selinux` package is installed
```
[root@ip-172-31-7-147 ec2-user]# yum list installed | grep container
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
container-selinux.noarch            2:2.107-3.el7              @rhui-REGION-rhel-server-extras
containerd.io.x86_64                1.2.13-3.1.el7             @docker-ce-stable
```

**Comment by soumyalj** [comment]
Other findings:

- Rancher version: V2.4.3-rc2 , K8s version v1.17.5-rancher1-1
Deployed cluster using RHEL 7.6 nodes with selinux enabled on docker daemon. Cluster provisioning fails with the below error.
```
2020/05/01 00:26:50 [WARNING] Can't start Docker container [kubelet] on host [abcd]: Error response from daemon: error setting label on mount source '/var/lib/docker': failed to set file label on /var/lib/docker/containers/32faaeae3467deafa697eec28d8609b58fd97d71f3fcc35cd3161fa985b3cea7/mounts/shm: operation not supported
2020/05/01 00:26:50 [INFO] Starting container [kubelet] on host [abcd], try #3
2020/05/01 00:26:50 [WARNING] Can't start Docker container [kubelet] on host [abcd]: Error response from daemon: error setting label on mount source '/var/lib/docker': failed to set file label on /var/lib/docker/containers/32faaeae3467deafa697eec28d8609b58fd97d71f3fcc35cd3161fa985b3cea7/mounts/shm: operation not supported
2020/05/01 00:26:50 [ERROR] Failed to upgrade worker components on NotReady hosts, error: [Failed to start [kubelet] container on host [abcd]: Error response from daemon: error setting label on mount source '/var/lib/docker': failed to set file label on /var/lib/docker/containers/32faaeae3467deafa697eec28d8609b58fd97d71f3fcc35cd3161fa985b3cea7/mounts/shm: operation not supported]
2020/05/01 00:26:50 [INFO] [controlplane] Now checking status of node ip-abcd, try #1
2020/05/01 00:27:15 [ERROR] Host ip-abcd failed to report Ready status with error: [controlplane] Error getting node ip-abcd:  "ip-abcd" not found

```

- Rancher version: V2.3.3 , K8s version v1.15.11
Deployed cluster using RHEL 7.6 nodes with selinux enabled on docker daemon. Cluster came up successfully and workloads came up fine.

**Comment by soumyalj** [comment]
Overall summary for Cluster provisioning test with RHEL nodes having selinux enabled on docker daemon : 
- v2.4.3-rc3/v2.4-head

RHEL7.7 fails with K8s 1.17.5-rancher1-1, K8s v1.15.11-rancher1-3
RHEL 7.6 fails with K8s 1.17.5-rancher1-1
[Note: All failures are with the same error as above]
- v2.3.3

RHEL 7.6 succeeds with K8s v1.15.11-rancher1-2, v1.17.4-rancher1-2

**Comment by sangeethah** [comment]
Related RKE issue - https://github.com/rancher/rke/issues/1966

**Comment by superseb** [comment]
This can be tested using v2.4.5-rc1

**Comment by soumyalj** [comment]
Tested with v2.4.5-rc2. 

Steps:

1. Create a cluster using RHEL 7.7 nodes/RHEL 7.8  with Upstream docker 19.03 and selinux enabled on docker daemon and OS. 
Cluster configuration: 4 nodes. 
N1: etcd, control 
N2, N3, N4: Worker

Cluster is active but few workloads in system project are not active. 
Workloads in ingress-nginx, kube-system namespace are stuck in updating state for worker nodes. 

![Screen Shot 2020-06-05 at 12 12 26 PM](https://user-images.githubusercontent.com/18536626/83914301-d822a880-a725-11ea-8662-ce97055078d5.png)

Note: This issue is not observed on a single node cluster with all 3 roles. All workloads in system project are active. The issue is observed for worker only nodes

**Comment by soumyalj** [comment]
Validated with v2.4.5-rc4.
- OS: RHEL 7.7 and RHEL 7.8
- Upstream docker 19.03 and selinux enabled on docker daemon and OS.   

Steps:

1. Create clusters  cluster1 using RHEL 7.7 nodes and cluster2 using RHEL 7.8 nodes [Both with Upstream docker 19.03 and selinux enabled on docker daemon and OS]
Cluster configuration: 5 nodes.
N1: etcd
N2: control
N3, N4, N5: Worker

Cluster provisioning was successful. Workloads in the system project were active. 
Automation runs succeeded for both clusters.
