### ISSUE TITLE
Host.remove doesn't trigger metadata update

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2688]
Sometimes host.remove doesn't trigger metadata updates as per @ibuildthecloud.

**Comment by alena1108** [comment]
@sangeethah when you have a chance, could you test this use case against master? I can't reproduce it, but I'm sure there are some steps that can lead to this failure. We should also include it to our validation test cases set.

**Comment by deniseschannon** [comment]
Verified with v0.47.0-rc1

Added 6 hosts. Removed 1 host at a time (total of 3) and checked  http://rancher-metadata/latest/containers and http://rancher-metadata/latest/hosts on each host after the remove. Each time the hosts were removed.
