### ISSUE TITLE
Adding digitalocean to rancher

### ISSUE THREAD

**Issue by emalov98ffm** [rancher/rancher#26892]
I am not able to add or connect digital ocean droplets to the rancher OS I'm getting this error.

Error in driver during machine creation: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation.

**Comment by superseb** [comment]
Please describe in more detail how to reproduce, what version of Rancher are you using and what steps are you taking from logging in to getting the error.
