### ISSUE TITLE
Add support for GitLab personal access tokens in Rancher Pipeline

### ISSUE THREAD

**Issue by pirminjanka** [rancher/rancher#26893]
Up to now it's only possible to connect through app id and secret to a gitlab instance when creating a rancher pipeline. Rancher should also support the combination of username and personal access token to do the connection to a gitlab instance in rancher pipeline.

**Comment by houtianhong** [comment]
Rancher 2.4.3 has the same problem when adding the authorization of private gitlab-ce account. Click the authorization button and the error will pop up immediately:
failed to decode the config, error: 1 error(s) decoding: * 'ManagedFields[0].Time' expected a map, got 'string'

**Comment by bluceyee** [comment]
Also got this error on Rancher 2.4.5.

**Comment by sammasamadhi** [comment]
The same error on 2.4.5
failed to decode the config, error: 1 error(s) decoding: * 'ManagedFields[0].Time' expected a map, got 'string'

**Comment by richyta** [comment]
Also got the same error on my end when trying to add gitlab in rancher pipeline.
failed to decode the config, error: 1 error(s) decoding: * 'ManagedFields[0].Time' expected a map, got 'string'

**Comment by sunliusi** [comment]
Why has such a serious problem not been fixed?

**Comment by camilorossi** [comment]
Same issue with 2.4.5

**Comment by yuedefeng** [comment]
Same issue with 2.4.5

**Comment by duxie** [comment]
Same issue with 2.4.5

**Comment by CarlosPerdomo** [comment]
Also got the same error when trying to add gitlab in rancher pipeline.

> failed to decode the config, error: 1 error(s) decoding: * 'ManagedFields[0].Time' expected a map, got 'string'

**Comment by fjfo** [comment]
same error with 2.4.5

**Comment by yfilipov** [comment]
Same issue with 2.4.5
