### ISSUE TITLE
Registry credentials do not get created in the selected namespace

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#26895]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** Create a registry credential in a project with at least two namespaces, selecting one with 'Available to a single namespace'.

**Result:** The credential will always be created in one of the namespaces regardless of selecting another.

**Other details that may be helpful:** This selection of which namespace becomes the only namespace used appears to relate to it being the first namespace created in the project. Working as expected via kubectl.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.6 and v2.4.2 tested so far
- Installation option (single install/HA): HA

Even though `kube-system` was chosen, the request payload selects `cattle-global-data`:

```json
{"type":"namespacedDockerCredential","registries":{"index.docker.io":{"username":"test","password":"test"}},"name":"kube-system-cred","namespaceId":"cattle-global-data"}
```

**Comment by superseb** [comment]
Please check https://github.com/rancher/rancher/issues/26813

**Comment by dkeightley** [comment]
Closing in favour of #26813
