### ISSUE TITLE
Update Nginx Ingress Request Rate increase(nginx_ingress_controller_nginx_process_requests_total[2m])

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#26902]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

The Nginx Ingress Request Rate graph in the Kubernetes Component Dashboard of Rancher Cluster Monitoring uses the expression `increase(nginx_ingress_controller_nginx_process_requests_total[1m])`. The nginx metrics at `http://<ip>:10254/metrics` are scraped every 1 minute. As a result the Prometheus [increase query](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) selects only one data point, and cannot calculate a difference, so the graph will always show `No data points`. The expression should be `increase(nginx_ingress_controller_nginx_process_requests_total[2m])` so the increase query will select the last two available data points to calculate the value.

**Cluster information**
- Rancher v2.2.8 / Monitoring v0.0.3 (query appears to be the same in latest monitorin v0.1.0 chart https://github.com/rancher/system-charts/blob/release-v2.4/charts/rancher-monitoring/v0.1.0/charts/grafana/dashboards/c_kubernetes-components-dashboard.json)

gzrancher/rancher#9894

**Comment by jiaqiluo** [comment]
the bugfix is validated on rancehr:master-head f1a410a97e2abf8c81c62195a7b40f10007398f0

monitoring `0.1.3`

<img width="1856" alt="Screen Shot 2020-09-21 at 3 00 48 PM" src="https://user-images.githubusercontent.com/6218999/93826148-7b3af780-fc1b-11ea-91b3-8d99b82e572c.png">


![image](https://user-images.githubusercontent.com/6218999/93826170-89891380-fc1b-11ea-9531-d59d5ed0b434.png)

![image](https://user-images.githubusercontent.com/6218999/93826194-9574d580-fc1b-11ea-9ae2-f7eded36cc4d.png)
