### ISSUE TITLE
[KE] Updating AKS kubernetes version fails

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#26907]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Using Rancher v2.3.5, create an AKS cluster with k8s version v1.15.7
2. Upgrade Rancher to v2.4.3-rc6
3. Attempt to upgrade k8s version for cluster to v1.15.10

**Result:**
AKS creation errors out with: "Azure failed to provision cluster with state: Upgrading"

**Other details that may be helpful:**
Rancher (KE's aks_driver) evaluates a status field returned by AKS and interprets the response as an error if the status is not "Creating" or "Updating. In this case, the status is "Upgrading" which is _probably_ valid.

More Info:
see this in Rancher logs
```
[rancher-74fc8d9c89-5sr4b] 2020/05/04 21:15:26 [INFO] Request submitted, waiting for cluster to finish creating
[rancher-74fc8d9c89-5sr4b] 2020/05/04 21:15:26 [ERROR] Azure failed to provision cluster with state: Upgrading
[rancher-74fc8d9c89-5sr4b] 2020/05/04 21:15:26 [INFO] kontainerdriver azurekubernetesservice stopped
[rancher-74fc8d9c89-5sr4b] 2020/05/04 21:15:26 [ERROR] ClusterController c-c6574 [cluster-provisioner-controller] failed with : failed to provision Azure cluster
```

**Comment by sangeethah** [comment]
The behavior seen is very similar to https://github.com/rancher/rancher/issues/19115

**Comment by jiaqiluo** [comment]
in 2.3.6/ 2.4.3-rc6
- provision an AKS cluster
- after the cluster is active, edit and upgrade the k8s version

Results:
- the cluster goes to the upgrade state and show the following error quickly

<img width="1173" alt="Screen Shot 2020-05-04 at 12 45 12 PM" src="https://user-images.githubusercontent.com/6218999/81018470-71a22600-8e19-11ea-9f59-63982348728e.png">

in Rancher logs 
`
[rancher-74fc8d9c89-5sr4b] 2020/05/04 20:24:34 [INFO] Provisioning cluster [c-j2qxq]
[rancher-74fc8d9c89-5sr4b] 2020/05/04 20:24:34 [INFO] Updating cluster [c-j2qxq]
[rancher-74fc8d9c89-5sr4b] 2020/05/04 20:24:39 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:45013
[rancher-74fc8d9c89-5sr4b] 2020/05/04 20:24:45 [INFO] Request submitted, waiting for cluster to finish creating
[rancher-74fc8d9c89-5sr4b] 2020/05/04 20:24:45 [ERROR] Azure failed to provision cluster with state: Upgrading
[rancher-74fc8d9c89-5sr4b] 2020/05/04 20:24:45 [INFO] kontainerdriver azurekubernetesservice stopped
[rancher-74fc8d9c89-5sr4b] 2020/05/04 20:24:45 [ERROR] ClusterController c-j2qxq [cluster-provisioner-controller] failed with : failed to provision Azure cluster	
`

- after a while, the error changes to be this

<img width="925" alt="Screen Shot 2020-05-04 at 2 58 37 PM" src="https://user-images.githubusercontent.com/6218999/81018511-81ba0580-8e19-11ea-8b85-51854836ff12.png">

in Rnacher logs
`
[rancher-74fc8d9c89-5sr4b] 2020/05/04 21:19:42 [INFO] kontainerdriver azurekubernetesservice stopped
[rancher-74fc8d9c89-5sr4b] 2020/05/04 21:19:42 [ERROR] ClusterController c-c6574 [cluster-provisioner-controller] failed with : containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
`

- although Rancher UI shows errors, the cluster in Azuer console goes to upgrading state

<img width="877" alt="Screen Shot 2020-05-04 at 2 37 31 PM" src="https://user-images.githubusercontent.com/6218999/81018762-03119800-8e1a-11ea-89af-c832e9a20f89.png">


- after the upgradtion is done, the cluster goes to active in Rancher UI

**Comment by rancher-max** [comment]
#### Validated in v2.4-head (`531144a97`) and master-head (`f1cfcb225`)

- All issues mentioned with steps listed above have been resolved
- Errors in the logs that I noticed appeared to be standard: `2020/05/13 20:51:09 [ERROR] NodeController c-rxv4g/machine-lssdw [user-node-remove] failed with : nodes.management.cattle.io "machine-lssdw" not found` and `2020/05/13 21:17:56 [ERROR] failed on subscribe storageClass: Get https://c-hhsl-mastertestr-14a619-master-e5e06d63.hcp.eastus.azmk8s.io:443/apis/storage.k8s.io/v1/storageclasses?resourceVersion=0&timeout=30m0s&timeoutSeconds=1800&watch=true: dial tcp a.b.c.d:443: connect: connection refused`
- None of the errors mentioned caused any errors on the UI. It showed Updating in yellow the entire time:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/55997940/81869261-9472bf80-9528-11ea-8f27-3ae451651e75.png">
- Update takes a long time, but after it is complete, Rancher shows as active.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/55997940/81869309-ae140700-9528-11ea-8734-0a99ccca4d3d.png">

**Comment by ccadruvi** [comment]
I am experiencing a [similar issue](https://github.com/rancher/rancher/issues/26907#issuecomment-623736629) as jiaqiluo when modifying the number of nodes on an AKS Cluster created with Rancher via Terraform:
> This cluster is currently Updating.
> 
> Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

The update is performed and a few minutes later, the error in Rancher switches to this:

> This cluster is currently Error.
> 
> Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

Another few minutes later, the cluster is scaled accordingly and the cluster in Rancher returns to Active state.

I am on Rancher v.2.5.9.

**Comment by tuxicorn** [comment]
facing similar issue
