### ISSUE TITLE
[RFE] - track resource cost, per project/namespace, by group/user

### ISSUE THREAD

**Issue by flrichar** [rancher/rancher#26901]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

Ability to track cost of resources, wether on premises or in the cloud.  The on-prem resources would need to be a configurable formula.  Ability to measure the entire cost of resource(s) by a small metric, unit of measurement, or rate, then categorize by the users or groups responsible for the resource(s).

* Pull metrics for CPU, memory, storage, and network utilization for computing costs
* Customize costs for on-prem clusters; pull data from AWS/GCP/Azure for managed clusters
* Allow computing costs for resources that may trigger external events. For example, adding an Ingress may incur a charge for the DNS entry or SSL certificate.
* Allow for "fixed overhead" computations -- e.g. each cluster costs X amount in fixed costs for day-to-day management
* API access to cost data
* Run reports per-cluster, per-project, per-namespace, or using search criteria like a label.
* "show-back" functionality
* integration with projects like kubecost

**Comment by skaven81** [comment]
The last item, "integration with projects like kubecost" doesn't really make sense.  Kubecost might be a potential _solution_ to this problem -- if Rancher integrated Kubecost (or some other open source kubernetes accounting software), that would likely cover 80-90% of this RFE.
