### ISSUE TITLE
When Upgrading k83 version for an  EKS cluster fails, k8s version in the edit cluster view reflects the newer version.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#26908]
**What kind of request is this:**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy an EKS cluster selecting k8s version 1.13
- Once the Cluster is Active go to Edit cluster.
- Select k8s 1.15 from the Kubernetes Version dropdown and click Save.
- The result is shown below
- After the failure the Rancher UI stays in k8s 1.15 as if the upgrade was a success. But that isn't the case.
- Edit Cluster shows k8s 1.15 and can't change it back to 1.13 unless we use the API.

**Result:**

Cluster is stuck in Updating in Rancher.

```
InvalidParameterException: Unsupported Kubernetes minor version update from 1.13 to 1.15 status code: 400, request id: 3e33935c-9352-xxxx-xxxx-xxxxxxxxxxxx
```

![Cluster List](https://user-images.githubusercontent.com/27659/81015531-b62ac300-8e13-11ea-8df4-534ef77f02fe.png)

**Other details that may be helpful:**

- EKS Console shows upgrade to 1.15 as unsupported from 1.13
- Upgrading from 1.13 to 1.14 works.
- Upgrade path 1.13 -> 1.14 -> 1.15 works.

**Environment information**
- Rancher version: `v2.4.3-rc6`
- Installation option: HA k8s

**Comment by izaac** [comment]
This is also reproducible in `v2.3.6` with EKS k8s 1.13

![Screen Shot 2020-05-04 at 4 18 55 PM](https://user-images.githubusercontent.com/27659/81022664-0a896f00-8e23-11ea-84d0-ddc41c575fa2.png)


Trying to edit the cluster it shows 1.15 immediately:

![Screen Shot 2020-05-04 at 4 19 13 PM](https://user-images.githubusercontent.com/27659/81022701-25f47a00-8e23-11ea-972f-65c64d6561b6.png)

**Comment by rmweir** [comment]
I recommend not allowing them to update to version that are more than one minor version ahead of their current. We know EKS will not allow it.

In my opinion, we should also hold off on adding this type of validation logic in the backend as @mrajashree works on kubernetes native validation. We likely will not have the same kind of flexibility w/ API level validation going forward. We also want people to be able to remedy these types of scenarios using the raw API.

**Comment by izaac** [comment]
EKS UI is broken in latest `2.4-head`commit id: 8e20687a4 and `master-head` commit id: b85ea695f

Uncaught (in promise) Error: Could not find module `Semver` imported from `shared/components/cluster-driver/driver-amazoneks/component`

UI is just stuck here:
![Screen Shot 2020-05-18 at 4 57 16 PM](https://user-images.githubusercontent.com/27659/82270131-a8ebf900-9928-11ea-9191-32ce8744d37a.png)

**Comment by izaac** [comment]
Rancher version: `2.4-head (05/19/2020)` commit id: 8e20687a4
Rancher version: `master-head (05/19/2020)` commit id: b85ea695f

The UI is now preventing to upgrade from 2 versions behind the current k8s version in EKS.

![Screen Shot 2020-05-19 at 1 35 16 PM](https://user-images.githubusercontent.com/27659/82383826-781cca00-99e3-11ea-944d-e3b8d4847db1.png)

Upgrading K8s is possible from 1.13 -> 1.14 and then from 1.14 -> 1.15 as expected and supported by EKS.

![Screen Shot 2020-05-19 at 3 13 05 PM](https://user-images.githubusercontent.com/27659/82383898-98e51f80-99e3-11ea-9d22-b012c8e39716.png)

![Screen Shot 2020-05-19 at 3 38 32 PM](https://user-images.githubusercontent.com/27659/82385382-d6977780-99e6-11ea-8024-da332f98fee5.png)
