### ISSUE TITLE
Unable to complete Provisioning (New Install)

### ISSUE THREAD

**Issue by TheEagle13** [rancher/rancher#26903]
**What kind of request is this (question/bug/enhancement/feature request):**
Question/Bug

**Steps to reproduce (least amount of steps as possible):**
Fresh install of Fedora 31
Fresh Install of Docker 19.03.8
Setup Rancher with the command `sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher`
Install etcd, Control Plane and Worker Roles on first server with:
`sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.4.2 --server https://***.***.com --token ***************************** --ca-checksum *********************************** --etcd --controlplane --worker`

**Result:**
Stuck on:
```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

[controlPlane] Failed to upgrade Control Plane: [[host server1 not ready]]
```

**Other details that may be helpful:**

**Environment information**
- Rancher | v2.4.2
- User Interface | v2.4.14
- Helm | v2.16.3-rancher1
- Machine | v0.15.0-rancher35
- Installation option (single install/HA): Single currently

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Physical Server 64GB Ram/ Dual Xeon

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:27:05 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:25:01 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by superseb** [comment]
Please test using the config described in https://github.com/rancher/rancher/issues/25681

**Comment by TheEagle13** [comment]
I'm not so sure that the issue you referenced has any relation to my issue. That appears to be when one wants to use a flexvolume. 
Regardless I tested by adding the extra args anyway, and it had no effect.

**Comment by superseb** [comment]
What network provider was chosen when creating the cluster? What is the status of the Docker containers on `server1` both the ones for the Kubernetes components as the pod containers (and in this case specifically, the logs from the `flexvol-driver` container (which is part of the calico/canal pod(s)

**Comment by superseb** [comment]
Because thats the main issue seen with Fedora, this is not a tested OS but we do have a configuration option to make it work. If this is all there is, then we need the logs from the `rancher/rancher` container. Also, as it seems you are running Rancher on the same node as the node you are adding to a cluster, you will need to follow https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/advanced/#running-rancher-rancher-and-rancher-rancher-agent-on-the-same-node

Please also include `docker ps -a` if this is not already the command that is used.
