### ISSUE TITLE
Cannot upgrade EKS clusters if using Rancher created VPC and Subnets

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#26909]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create EKS cluster using a kubernetes version that is not the latest (1.13 or 1.14). Use all other default options. Specifically "Rancher Created VPC and Subnet"
2. Attempt to upgrade the kubernetes version on that cluster

**Result:**
Fails with error: `Validation failed in API: amazonElasticContainerServiceConfig subnets=NotNullable 422:`

**Other details that may be helpful:**
Probably due to backport of: https://github.com/rancher/rancher/issues/26231#issuecomment-604020610

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.3.7-rc4`
- Installation option (single install/HA): single and HA (validated this happens in both)

**Comment by westlywright** [comment]
Available in latest2-3 and 2.3.46

**Comment by rancher-max** [comment]
#### Validated fixed using ui-index 2.3.46 (`https://releases.rancher.com/ui/2.3.46/index.html`)

Following the same steps as above, I do not see the issue using this ui-index. This will be available in the rc5.
