### ISSUE TITLE
KEv2: EKS CRD, controller, base provisioning

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#26921]
This issue handles the base arch of EKS in KEv2

* Watches for new EKSAPIConfig
* Includes necessary IAM provisioning to create cluster
* If EKSAPIConfig does not have an owner, noop
* Create cluster in EKS
* store credentials and info needed to create service account in secret
* labels for cluster-autoscaler **EDIT: user can edit tags on eks so they are able to add cluster-autoscaler tags if they wish. Tags are as follows:
`k8s.io/cluster-autoscaler/<cluster-name>: owned`
`k8s.io/cluster-autoscaler/enabled: true`

  For more info on cluster auto-scaler: https://docs.aws.amazon.com/eks/latest/userguide/cluster- 
  autoscaler.html

* cloud credentials (may need to split this out) 

Ensure that
- [ ] Instance profiles can take the place of directly supplying aws keys

This ticket does not cover: 

* updating cluster
* creating/updating node groups
* any other eks features

**Comment by rmweir** [comment]
YAML to be applied (remove nodegroups field if desired):

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cattle-system
  name: eks-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  eks-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: eks-config
  namespace: cattle-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eksclusterconfigs.ke.cattle.io
spec:
  group: ke.cattle.io
  names:
    kind: EKSClusterConfig
    plural: eksclusterconfigs
    shortNames:
    - ekscc
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          anyOf:
          - required:
            - imported
            - cloudCredential
            - displayName
          - required:
            - publicAccess
            - privateAccess
            - cloudCredential
            - displayName
          properties:
            cloudCredential:
              type: string
            displayName:
              type: string
            imported:
              enum:
              - true
              nullable: true
              type: boolean
            kmsKey:
              type: string
            kubernetesVersion:
              type: string
            loggingTypes:
              items:
                type: string
              nullable: true
              type: array
            nodeGroups:
              items:
                properties:
                  desiredSize:
                    nullable: true
                    type: integer
                  diskSize:
                    nullable: true
                    type: integer
                  ec2SshKey:
                    nullable: true
                    type: string
                  gpu:
                    type: boolean
                  instanceType:
                    nullable: true
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    nullable: true
                    type: object
                  maxSize:
                    nullable: true
                    type: integer
                  minSize:
                    nullable: true
                    type: integer
                  nodegroupName:
                    type: string
                  sourceSecurityGroups:
                    items:
                      type: string
                    nullable: true
                    type: array
                  subnets:
                    items:
                      type: string
                    nullable: true
                    type: array
                  tags:
                    additionalProperties:
                      type: string
                    nullable: true
                    type: object
                  version:
                    nullable: true
                    type: string
                type: object
              nullable: true
              type: array
            privateAccess:
              type: boolean
            publicAccess:
              type: boolean
            publicAccessSources:
              items:
                type: string
              nullable: true
              type: array
            region:
              type: string
            secretsEncryption:
              type: boolean
            securityGroups:
              items:
                type: string
              nullable: true
              type: array
            serviceRole:
              type: string
            subnets:
              items:
                type: string
              nullable: true
              type: array
            tags:
              additionalProperties:
                type: string
              nullable: true
              type: object
            virtualNetwork:
              type: string
          type: object
        status:
          properties:
            phase:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: ke.cattle.io/v1
kind: EKSClusterConfig
metadata:
  name: rmweir-5
spec:
  kubernetesVersion: "1.15"
  privateAccess: false
  publicAccess: true
  cloudCredential: ""
  displayName: "eks-clustername"
  region: "us-east-2"
  loggingTypes: []
  nodeGroups:
  - nodegroupName: "eks-clustername-ng-1"
    instanceType: "t3.medium"
    desiredSize: 1
    maxSize: 2
    minSize: 1

**Comment by cbron** [comment]
@rmweir what was our decision on instance profiles ?
