### ISSUE TITLE
Using asterisk in command

### ISSUE THREAD

**Issue by eelcocramer** [rancher/rancher#2692]
I'm trying to add a new service to my stack. My service uses a image with an entrypoint and I want to add command line arguments via the `command` field of `advanced options`.

My command field is a series of command line arguments:

```
--upstream=http://upstream/ --http-address=0.0.0.0:4180 --redirect-url=https://example.com/oauth2/callback --email-domain=* --provider=azure --cookie-secure=true
```

When the container is created I see that the command line option `--email-domain=*` is not passed into the container and is not listed in the `View in API` output of rancher.

**Comment by deniseschannon** [comment]
Reproduced in v0.46.0-rc4.

@alena1108 I think this is a bug with the command parsing. 

@eelcocramer Do the commands work when you do a normal `docker run` command on a host? Just want to double check.

**Comment by eelcocramer** [comment]
Yes.

Also we I put the commands in a `.yml` and use the command line `rancher-compose` tool it works without a problem.

**Comment by alena1108** [comment]
Looks like a UI issue as I see the UI sends this value for the field:

```
"command":["--upstream=http://upstream/","--http-address=0.0.0.0:4180","--redirect-url
=https://example.com/oauth2/callback","glob","--provider=azure","--cookie-secure=true"]
```

@vincent99

**Comment by tfiduccia** [comment]
Verison - master UI 3/17
Verified fixed
