### ISSUE TITLE
rancher monitoring behind nginx

### ISSUE THREAD

**Issue by zhfish** [rancher/rancher#26938]
**What kind of request is this (question/bug/enhancement/feature request):**
bug or question

**Steps to reproduce (least amount of steps as possible):**

![image](https://user-images.githubusercontent.com/287033/81133879-92878a00-8f85-11ea-8c8c-d5ef4e376848.png)

**Result:**

show me the grafana

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

rancher v2.3.5
monitoring v0.0.7
openresty proxy-pass http port

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by aiyengar2** [comment]
@zhfish can you provide more information? For context, we currently place Prometheus + Grafana behind a minimal nginx proxy with the following configurations:
- Grafana: [container](https://github.com/rancher/charts/blob/73f1cd647751650190644b23d0e41221bdfed644/charts/rancher-monitoring/values.yaml#L962-L981), [config](https://github.com/rancher/charts/blob/73f1cd647751650190644b23d0e41221bdfed644/charts/rancher-monitoring/charts/grafana/templates/nginx-config.yaml#L10-L75)
- Prometheus: [container](https://github.com/rancher/charts/blob/73f1cd647751650190644b23d0e41221bdfed644/charts/rancher-monitoring/values.yaml#L2412-L2431), [config](https://github.com/rancher/charts/blob/73f1cd647751650190644b23d0e41221bdfed644/charts/rancher-monitoring/templates/prometheus/nginx-config.yaml#L15-L66)

The purpose behind these configurations is to avoid Grafana / Prometheus breaking when accessed through a URL subpath.
