### ISSUE TITLE
KEv2: EKS docs

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#26930]
Relevant validation/integration tests should be added for primary EKS functionality and feature set. Typically we would have the tests done on each ticket, but because so much functionality is split up across tickets that isn't possible. 

items 
- [ ] Docs
- [ ] KB Docs

**Comment by sowmyav27** [comment]
Tracking the documentation required for issue - https://github.com/rancher/rancher/issues/28208. 
Information on public/private access and security groups rules for private traffic should be made available in docs.

**Comment by cbron** [comment]
See: https://github.com/rancher/rancher/issues/29023

We should add a section in docs with overview and the pros/cons/gotchas involved with our syncing architecture.

**Comment by cbron** [comment]
Closing, as we will handle without issue.
