### ISSUE TITLE
[UI] Node Templates - Cloned Unusable

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#26946]
**What kind of request is this (question/bug/enhancement/feature request):** bug

Related: https://github.com/rancher/rancher/issues/26575

**Steps to reproduce (least amount of steps as possible):**

### Unable to Clone a Cloned Template

1. Clone any existing Node Template
2. Attempt to use it in any cluster.

**Result:**

Permission denied or 404 error

**Other details that may be helpful:**

It appears that with the change to make node templates global or access by multiple users some underlying logic has broken with the use of any clone template. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Comment by ekristen** [comment]
It appears that templates prior to the change that moved the templates to the cattle global data are affected. 

For example, if you had UserA (not Global Admin) that created Template1 BEFORE the global data migration for node templates, and then UserA *clones* Template1 to Template2 in 2.3.3 it Template2 will be **unavailable** to UserA period. 

New Templates created by UserA are ok.

**Comment by rmweir** [comment]
When a user goes to clone the nodetemplate it is also copying the annotations over to the new template which is what rancher uses to know whether or not it has made rolebinding for the creator.

Annotations should not be copied, just the non-meta fields of the nodetemplate.

**Comment by izaac** [comment]
Reproduced the issue in `v2.3.3` cloned templates has the annotations copied and trying to use the cloned templated returns an error as described using templates created in `v2.3.2`

Validated this is no longer the issue in `v2.3-head (05/22/2020)` commit a621912b1 

I will check `2.4-head` and `master-head` next.

**Comment by izaac** [comment]
Validated the fix also in `v2.4-head (05/22/2020)` commit d8f101974

Cloned templates after upgrading from `v2.3.2` works for creating clusters. Cloned templates with extra annotations, the annotations got removed in the cloned template.

Issue #27227 opened because the UI gets unresponsive after upgrading to `master-head`
