### ISSUE TITLE
Chart Update - OpenFaaS

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#26953]
Helm 2 Chart - OpenFaaS v5.7.2 
Located in the `dev` branch of [https://github.com/rancher/charts](https://github.com/rancher/charts)

**Comment by jiaqiluo** [comment]
the chart is validated functional on Rancher `v2.4.3-rc7`

Steps:
- run Rancher `v2.4.3-rc7` single install 
- provision a cluster with k8s `v1.17.5-rancher1-1`
- change the branch of `library` to `dev`
- deploy the app  OpenFaaS v5.7.2

Results:
- the app is deployed successfully 
- can access to the app's UI 

![image](https://user-images.githubusercontent.com/6218999/81215944-f4002680-8f8e-11ea-995e-d27ba251edeb.png)

![image](https://user-images.githubusercontent.com/6218999/81215965-febabb80-8f8e-11ea-9c19-39b397e4821b.png)
