### ISSUE TITLE
[2.3] Support k8s 1.15.12

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#26959]
Support k8s 1.15.12 for 2.3.x

**Comment by sangeethah** [comment]
Fresh install of `v2.2.13-rc4` 
Add clusters with version - `v1.15.12-rancher1-1` 
Upgrade rancher server to `v2.3.8-rc3` 
Able to upgrade the existing 1.15.12 clusters to other K8s versions successfully.
Also able to upgrade K8s version to  - `v1.15.12-rancher2-2` which is the version presented on fresh install successfully.
