### ISSUE TITLE
Azure Node Template Tags

### ISSUE THREAD

**Issue by shpwrck** [rancher/rancher#26955]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature Request

**Steps to reproduce (least amount of steps as possible):**

1. Provision Rancher >2.3
2. Create an Azure Node Template
3. Attempt to apply tags.

**Result:**

There is no option for adding tags to Azure Node Template Instances like there is for AWS (see below screenshot).

![image](https://user-images.githubusercontent.com/58433720/81221100-5fa6bb80-8fb0-11ea-81a3-7251a1c5c82e.png)

**Other details that may be helpful:**

Ideally this will make it's way into the Rancher2 terraform provider as well.

**Environment information**

Any installation of Rancher >= 2.3
The primary use case being an environment that will reject any resource created without a tag.
In said environment resources created through AKS would also need tags applied to them.

gz#14304

SURE-2700

**Comment by julienym** [comment]
Small note that through Terraform, creating an AKS cluster on Azure doesn't put the tags as it should:
rancher2_cluster.aks {
aks_config {
tag = { test = "true" }

---
Terraform v0.12.24
+ provider.rancher2 v1.8.3

**Comment by julienym** [comment]
See also ? : https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/36291130-auto-generated-tags-via-deployment-manifests

**Comment by HarrisonWAffel** [comment]
@gaktive This ticket is currently blocked by the respective UI work. rancher-machine has been updated so the required API schema changes should be present, resolving previous UI blockers.

**Comment by thaneunsoo** [comment]
The test plan can be viewed [here](https://confluence.suse.com/pages/viewpage.action?pageId=1141178915)

**Comment by thaneunsoo** [comment]
Azure Node Template Tags have been added successfully.
Test results can be found [here](https://confluence.suse.com/pages/viewpage.action?pageId=1141178915)
