### ISSUE TITLE
Add hostServiceMap API endpoint

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2695]
With following fields:

* serviceId
* hostId
* host_ip_address

The hostServiceMap object will be created when service publishes the port to the host; removed when service's instance gets removed from the host.

Object will have read only permissions

@vincent99 @will-chan

**Comment by alena1108** [comment]
@sangeethah here are the API changes that we have to test (copied from https://github.com/rancher/cattle/pull/1076):


service" and "host" objects get one extra API field called "publicEndpoints". Each endpoint has 2 fields:

port (int)
ipAddress (string)

Field gets populated for service/host on every nic.activate/nic.deactivate event for the instance having port exposed. Supported for both service and standalone instances; in standalone instance case only host object will get an update.

This model will be valid even in the future, when we add support for multiple interfaces for hosts + mapping port to a particular interface.

**Comment by sangeethah** [comment]
Tested with server version  - v0.47.0-rc1

host.publicEndpoints and service.publicEndpoints are available now which exposes all the ports that are being used by it. 

Few issues found when testing for proper generation of the ports in tracked in 
#2770,#2771 and #2773
