### ISSUE TITLE
[2.4.3] Unexpected token s in JSON at position 3

### ISSUE THREAD

**Issue by MSandro** [rancher/rancher#26970]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* update to 2.4.3
* global -> settings
* edit UI Banner
* input wrong json

**Result:**
* now UI Banner can't be edited anymore
* sometimes you will be redictd to /fail with errror Unexpected token s in JSON at position 3

**Other details that may be helpful:**
I would like to fix the JSON but don't know where I can manually edit the rancher settings

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/rancher 2.4.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 2 Cores 8 GB RAM
- Kubernetes version (use `kubectl version`): 1.17.5

- Docker version (use `docker version`):  19.3.8

**Comment by sangeethah** [comment]
@MSandro , you can got to "/v3/settings/ui-banners" and use "Edit" option to correct the value.

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/28504
