### ISSUE TITLE
Target services fails to reconcile when LB service it is associated with is not able to reconcile.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2697]
Setup: 3 hosts

Service web1 - scale 2
Service web2 - scale 2
LB service - scale 3

Bring down one of the host which has 1 Lb Agent and 1 instance of service web1 is running.

LB service is not able to reconcile , since there is no host in the setup for the new LB instance to be started.

But this also affects the web1 service which is not able to reconcile. When unhealthy instance was detected , we were reconcile service. The new instance was attempted to start in the host that was reconnecting and when there was an attempt made to "stop" it , it gets stuck in "reconnecting" state forever.

```
mysql> select id,name,state,health_state from instance where name like "%web1%";
+----+----------------+----------+--------------+
| id | name           | state    | health_state |
+----+----------------+----------+--------------+
|  1 | Default_web1_1 | running  | healthy      |
|  2 | Default_web1_2 | purged   | unhealthy    |
| 12 | Default_web1_3 | purged   | initializing |
| 14 | Default_web1_3 | purged   | unhealthy    |
| 17 | Default_web1_2 | running  | healthy      |
| 22 | Default_web1_3 | running  | unhealthy    |
| 24 | Default_web1_4 | stopping | initializing |
+----+----------------+----------+--------------+
7 rows in set (0.00 sec)
```

**Comment by sangeethah** [comment]
Tested with latest build from master.

Tested the same scenario mentioned in this issue.

I see the same issue where the target service remains degraded and the new instances that are getting created are stuck in "post-network" state forever.

**Comment by sangeethah** [comment]
@alena1108 Also noticed the following behavior , when the host that was down is brought back up:

LB service reconciles as expected with 3 "LB Agents" starting successfully.

But the taggert services takes a very long to reconcile.
I see the services the services that were attempted to start when the host was down , now getting going to "stopped" stated ( in addition to the ones that get marked in "stopped" state for the instances that were in the host that went down).  These stopped instances get removed and  after this new instance are getting created.

<img width="1158" alt="screen shot 2015-11-16 at 4 11 54 pm" src="https://cloud.githubusercontent.com/assets/4266958/11198861/385a626a-8c7d-11e5-89e3-305563865a81.png">

**Comment by alena1108** [comment]
@sangeethah for your last comment, you should probably file a new issue. Unless you can reproduce it only in conjunction with LB service?

**Comment by sangeethah** [comment]
@alena1108 I dont see this behavior when I tested the same scenario with a service that is not a target for a LB service but it have exposed port. I see the service reconciles quickly after the host is kept down and brought back up again.

**Comment by alena1108** [comment]
@sangeethah then lets see if the same fix solves both problems.

**Comment by sangeethah** [comment]
Tested with latest build from master:

Service web1 - scale 10
Service web2 - scale 10
LB service - scale 3

Bring down one of the host which has 1 Lb Agent and few instance of service web1 and web2  are running.

services web1 and web2 are able to reconcile successfully on detection of unhealthy instances even when the host is down and LB service is still degraded.

Once the host is brought up, Lb service reconciles as expected.
