### ISSUE TITLE
k3s with aws network load balancer: aws health check fails due to traefik ingress controller

### ISSUE THREAD

**Issue by spicysomtam** [rancher/rancher#26977]
k3s rancher 2.4.3.

**Steps to reproduce (least amount of steps as possible):**
Followed all the steps in the install instructions to install the k3s version of rancher on 2 x ubuntu 18.04 aws ec2 instances, and followed your instructions to setup a aws network load balancer. All installs and appears setup fine. I am building this out as a terraform automated deploy and its worked out pretty good so far.

The issue I have is the aws network load balancer health checks never become healthy, and the reason is that traefik is not getting the hostname it expects to route it through. Since they never become healthy they don't route traffic!

I can confirm traefik is working fine on one of the ubuntu vm's:

```
# curl http://127.0.0.1/healthz
404 page not found

# curl  -H Host:rancher.mydomain.com http://127.0.0.1
<a href="https://rancher.mydomain.com/">Found</a>.

# curl  -H Host:rancher.mydomain.com http://127.0.0.1/healthz
ok
```
Thus I would say the rancher k3s install looks setup correctly.

There does not seem to be any way in the aws target groups to insert a header for health checks (nlb and alb). So it looks like traefik and aws load balancers is unworkable?

Thus I am wondering if I can dispense with traefik and use something else (nginx?) as a ingress controller? Or maybe I am missing something really obvious to resolve this? Any help would be appreciated.

**Comment by jiaqiluo** [comment]
Hi @spicysomtam, is your Rancher setup accessible from the browser? Does the health check failure stop you from using Rancher?

**Comment by spicysomtam** [comment]
Yes it does as its the ingress into the cluster (load balances the two ubuntu hosts). 

[Install instructions I followed (k3s)](https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/create-nodes-lb/). Specifically load balancer setup from these [instructions](https://rancher.com/docs/rancher/v2.x/en/installation/options/nlb/). 

My debug of the treafik is in the first post.

**Comment by spicysomtam** [comment]
[This blog from Grégoire Jeanmart ](https://kauri.io/38-install-and-configure-a-kubernetes-cluster-with/418b3bc1e0544fbc955a4bbba6fff8a9/a) looks a solution to not installing treafik and using nginx instead for ingress. Will have a play and see how far I get.

**Comment by spicysomtam** [comment]
I also found this on the k3s [faq](https://rancher.com/docs/k3s/latest/en/faq/):

> How can I use my own Ingress instead of Traefik?
> Simply start K3s server with --no-deploy=traefik and deploy your ingress.

I would say the docs need a bit more on how treafik works and how this could be an issue with external load balancers that have a health check. Maybe instructions on how to replace it with nginx?

Also how about an option to install nginx as the ingress controller rather than treafik so the problem can easily be worked round?

Have not had any time today to play with k3s and changing the ingress controller.

**Comment by spicysomtam** [comment]
I managed to solve my issues. Documented it in the repo I have put up on github that deploys k3s as a dual node cluster in aws using terraform (there is also a single node deploy). Link to the [issue/fix](https://github.com/spicysomtam/rancher-k3s-aws#issue-with-an-aws-network-load-balancer-and-3ks). 

Summary: The rancher instructions for creating the Network Load Balancer are incorrect for k3s:

* The health check settings are misleading and not required. We are implementing a TCP load balancer (connect to a port) and its not concerned with any protocols such as HTTP/HTTPS. Furthermore this health check causes the targets to be shown as unhealthy, because of the use of the treafik ingress controller, and will mislead that things are not working correctly.
* The target group for HTTPS (443) should be directed to port 443 on the ec2 nodes and not port 80.

Rancher [instructions](https://rancher.com/docs/rancher/v2.x/en/installation/options/nlb/) for creating the AWS Network Load Balancer.

Feel free to try out my terraform!

**Comment by spicysomtam** [comment]
I updated my [terraform at github](https://github.com/spicysomtam/rancher-k3s-aws) to include an AWS ELB load balancer (classic) deploy, which deploys much faster than an NLB. An NLB is not needed for a simple tcp load balancer. Also a slight tweak to my terraform to ensure ec2 instances are deployed in different availability zones for max fault tolerance.

**Comment by spicysomtam** [comment]
Think this is resolved, apart from docs needing updating? Shall I close it?

**Comment by jiaqiluo** [comment]
Hi @spicysomtam Thank you so much for the feedback!

Please leave the issue open and we will deal with it.

**Comment by catherineluse** [comment]
The load balancer in this documentation isn't directing traffic differently based on whether it is HTTP or HTTPS. It is redirecting traffic from port 80 to port 443, but that's all because encryption is terminated at the Rancher instance.

I have made a doc PR to say that the health checks aren't intended to be used with the Traefik ingress controller.

**Comment by spicysomtam** [comment]
The health check should be tcp anyway since its a tcp based load balancer. http health check is misleading.

What I found testing is that if you connect to http on the lb, you are redirected to https. I am not sure what is happening; I suspect the web browser receives a ssl cert from http and then rewrites the url to https because of this. Anyhow, when it gets redirected to https, this fails as the response from port 80 (443->80) is incorrect and the browser has an issue with this. If I point the load balancer 443 service to connect to 443 on the rancher nodes, then all is fine. So the 443 being directed to port 80 is incorrect. I am not sure the exact behaviour with treafik regarding ports 80 and 443; does it provide a cert on both ports or just port 443; I suspect both ports? 

Also a NLB is not required; a simple ELB is much quicker to create in aws, and the health checks come live much quicker with an ELB. In fact the lb required is really simple; just tcp, no stickiness, etc, since the service within k3s is a clusterIP. That means you can come in on any k3s node, hit the cluster ip service, which will maintain your stickiness/session/etc, even if you subsequently come in on a different k3s node. The only thing the cloud load balancer needs to do is check the port is open on the target nodes.

Hope all of this makes sense? BTW my kubernetes experience is mainly from Openshift.

**Comment by catherineluse** [comment]
I'm having trouble with the terminology of an ELB. From what I understand, an ELB is an umbrella term that includes both the layer-4/network load balancer as well as the layer-7/application load balancer. When you say a simple ELB, is that a layer 4 or layer 7 load balancer?

**Comment by spicysomtam** [comment]
ELB is the aws classic load balancer while ALB/NLB is the newer aws load balancer (they call these lbv2 so elb is v1 so to speak). The ELB is a simpler beast, while the ALB/NLB is much more complex and takes longer to deploy (from memory it needs 8 ip's per availability zone). ELB does not need target groups while NLB/ALB does. To confuse things ELB can be layer 4 or 7; depending on your needs. With k3s since you terminate TLS in the cluster and you use a cluster IP service, thus all you need outside the cluster in the cloud is a simple layer 4 load balancer. That is why you should use an ELB and not an NLB. If you deploy my terraform in my git repo you can compare both (NLB v ELB). Note ELB deploys much quicker and comes healthy much quicker. AWS misleads in that it says NLB/ALB is `better` or `newer` than ELB, but the simple answer is there is use cases for both and there is no plans to retire ELBs since so many clients use it.

**Comment by catherineluse** [comment]
Ok @davidnuzik  Bastian explained why the health check works with the NGINX ingress but not the Traefik Ingress.

> The traefik ingress controller listens on port 80 and 443 as well. Traffic to port 80 will also automatically be redirected to port 443.
>
> So it is correct that theLB port 80 should point to ingress controller port 80 and LB port 443 should point to ingress controller port 443.
>
> The only difference to the nginx ingress controller is, that the health check in our NLB docs does not work like this. The documented health checks do a HTTP request to /healthz . Because the LB health check does not send a host header this will be routed to the default backend of the ingress controller. The default backend of the nginx ingress controller has a /healthz  endpoint, the default backend of traefik has not.
> 
> Since the NLB is working as a Layer 4 TCP loadbalancer anyways, I think it would be correct to also only do a Layer 4 TCP health check to the port of the target group and not an HTTP health check.

**Comment by spicysomtam** [comment]
The only incorrect bit is there is no nginx ingress controller and the /healthz end point is in the rancher k8s service (actually the pods behind the service). Treafik identifies the incoming hostname for rancher, identifies that the rancher service in cattle-system namespace is the target, and will redirect requests to this. Since a http/https health check will not pass a hostname through this fails. With the k3s deployment, treafik ingress controller replaces the nginx ingress controller; the rke deployment uses nginx ingress rather than treafik. All the other points I agree, and its a nice summary.

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/2548#pullrequestreview-430060252 was merged

**Comment by ReginaldoSantos** [comment]
> I managed to solve my issues. Documented it in the repo I have put up on github that deploys k3s as a dual node cluster in aws using terraform (there is also a single node deploy). Link to the [issue/fix](https://github.com/spicysomtam/rancher-k3s-aws-tf#issue-with-an-aws-network-load-balancer-and-3ks).
> 
> Summary: The rancher instructions for creating the Network Load Balancer are incorrect for k3s:
> 
> * The health check settings are misleading and not required. We are implementing a TCP load balancer (connect to a port) and its not concerned with any protocols such as HTTP/HTTPS. Furthermore this health check causes the targets to be shown as unhealthy, because of the use of the treafik ingress controller, and will mislead that things are not working correctly.
> * The target group for HTTPS (443) should be directed to port 443 on the ec2 nodes and not port 80.
> 
> Rancher [instructions](https://rancher.com/docs/rancher/v2.x/en/installation/options/nlb/) for creating the AWS Network Load Balancer.
> 
> Feel free to try out my terraform!

Thank you very much for sharing! Awesome work!
