### ISSUE TITLE
error:  only the following media types are accepted: application/json, application/yaml

### ISSUE THREAD

**Issue by chuegel** [rancher/rancher#26987]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
install rancher 2.4.3 helm3 chart
access rancher and click on "Try Dashboard"

**Result:**
Blank page with following error:
`error:  only the following media types are accepted: application/json, application/yaml`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by AcidAngel21** [comment]
We are experiencing the same issue.

**Comment by erSitzt** [comment]
Same here

**Comment by soumyalj** [comment]
- Use case 1: 
Tested on Rancher v2.4.3  HA setup 

Steps:
1. Create RKE cluster with K8s version v1.14.1-rancher1-2 [using RKE CLI]
2. Import the cluster in the HA setup. 
3. Once the cluster became active, immediately access the Dashboard. 
Result:
Observed the below error for 5s or so:
![Screen Shot 2020-05-11 at 7 31 57 PM](https://user-images.githubusercontent.com/18536626/81632398-fa433800-93be-11ea-9611-f42bf459e634.png)

Accessed the dashboard again after 10 seconds. Dashboard was launched successfully.

- Use case 2: 
Observed the same behavior as above on a single node setup upgraded from v2.3.1 to v2.4.3. 
[RKE cluster was imported in the upgraded setup]

**Comment by Jaywoods2** [comment]
Is it resolved?

**Comment by erSitzt** [comment]
Is there any news on this ? Still not working in any of my clusters.

**Comment by superseb** [comment]
Please check https://github.com/rancher/rancher/issues/26980 as well

**Comment by weavepub** [comment]
Updated the k8s version to v1.17.5 under my Rancher HA instance but this don't working

**Comment by erSitzt** [comment]
I updated my k8s running ha rancher and its working now.
