### ISSUE TITLE
When service is scaled down , metadata for service still reports the removed container in container_list .

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2698]
rancher server - Build from master

I had a service with scale 1 to begin with with exposed port.
Scale up service by 1.
New host ip address was programmed in Route53.
Scaled down service.
This change was never propagated to Route53.

The reason for this is the container_list in the metadata for this service still has 2 entries (including the container that was delete as part of scale down)

**Comment by alena1108** [comment]
@sangeethah I've put a fix excluding hosts/instances/serviceexposemaps in Removing state from being propagated to metadata.

**Comment by sangeethah** [comment]
Tested with latest build from master.

When services are scaled down , changes get propagated to Route53 promptly and ip address of the host that had the removed container is removed .
