### ISSUE TITLE
only the following media types are accepted: application/json, application/yaml when clicking "Try Dashboard" 

### ISSUE THREAD

**Issue by kleintech** [rancher/rancher#26980]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Upgrade Rancher HA to 2.4.3 from 2.3.5 using Helm
2. Log in to Rancher UI
3. Click on any k8s cluster
4. Click "Try Dashboard" in top right

**Result:**
Browser is redirected to `/dashboard/fail-whale`
```
Error
only the following media types are accepted: application/json, application/yaml
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3
- Installation option (single install/HA): HA on Kubernetes

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Both Custom and Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM. Specs vary from 2CPUx8GB RAM to 4x16
- Kubernetes version (use `kubectl version`): Varies from 1.13.5 to 1.17.3

- Docker version (use `docker version`): Varies from 19.3.3 to 19.3.6

**Comment by vincent99** [comment]
I'm pretty sure 1.13 is too old for some of the features the new dashboard uses (and also is no longer supported by the k8s community in general).  Is the first cluster alphabetically one of the older ones?

In the next update the error page will at least let you see the cluster list and switch to a different one instead of leaving you stranded.

**Comment by kleintech** [comment]
My rancher cluster is running the older version and is not alphabetically
first in my cluster list, but the newer clusters are having the same issue.
I will upgrade the rancher cluster k8s and get back thanks.

**Comment by kleintech** [comment]
Updated the k8s version under my Rancher HA instance and this started working properly, thanks!
