### ISSUE TITLE
sometimes the edited scale for a service is not saved when editing services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2699]
Server version - Build from master.

Edit a service.
Change the scale and save.
Service scale remains the same.
When i did an inspect to see the API call being made by the UI , the scale is still set to the original value before the edit scale was done.

Seems like this happens when we change the scale and click on "save" button very quickly.

**Comment by deniseschannon** [comment]
I've also seen this happen but it's literally how fast you are clicking.
