### ISSUE TITLE
Node template values not changing while switching cloud credentials for vSphere

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#26997]
### Affected versions
 Rancher 2.3.x & 2.4.x

### Steps to reproduce 

1. Add two vCenter credentials
2. Click on Manager Node Template
3. Click on vSphere

This works fine and we can see many API calls going out to fetch data 
```
https://x.x.x.x/meta/vsphere/resource-pools?cloudCredentialId=cattle-global-data:cc-bddz9&dataCenter=/DC0
https://x.x.x.x/meta/vsphere/data-stores?cloudCredentialId=cattle-global-data:cc-bddz9&dataCenter=/DC0
https://x.x.x.x/meta/vsphere/folders?cloudCredentialId=cattle-global-data:cc-bddz9&dataCenter=/DC0
https://x.x.x.x/meta/vsphere/hosts?cloudCredentialId=cattle-global-data:cc-bddz9&dataCenter=/DC0
https://x.x.x.x/meta/vsphere/templates?cloudCredentialId=cattle-global-data:cc-bddz9&dataCenter=/DC0
https://x.x.x.x/meta/vsphere/networks?cloudCredentialId=cattle-global-data:cc-bddz9&dataCenter=/DC0

```
![template-pageload](https://user-images.githubusercontent.com/11064902/81438653-bcf66480-918a-11ea-97a5-c28664e8bf0f.png)

But , when we switch the cloud credential and selects the second one, the template form don't refresh new values from the second vCenter , instead it keeps the first vCenters values.

Here we don't see the same API calls we observed while loading the form.

![template-cloud-credential-switch](https://user-images.githubusercontent.com/11064902/81438584-a819d100-918a-11ea-9d86-281f465891ad.png)

Here we don't see the "Data Store" value reflecting from second vCenter in UI

As per the configuration of second vCenter (dc2), the DS name is `gostore` but as per the testing it still shows previous vCenter's value.

```
$ govc find .
/
/godc
/godc/vm
/godc/vm/govm1
/godc/host
/godc/host/gocluster
/godc/host/gocluster/gohost1
/godc/host/gocluster/Resources
/godc/datastore
/godc/datastore/gostore <<<---------
/godc/network
/godc/network/VM Network
```

Seems like we are hitting a UI bug here.

gzrancher/rancher#9795

**Comment by aaronRancher** [comment]
Was not able to reproduce with Rancher server `rancher\rancher:v2.4.3`
Tested with a valid cert and an invalid cert to see changes in API calls. Saw valid certs populate node template. Saw new API calls when trying invalid certs:
<img width="1513" alt="Screen Shot 2020-05-11 at 11 12 53 AM" src="https://user-images.githubusercontent.com/57409052/81604286-86843980-9384-11ea-9cc2-1a7eccc7c07c.png">

**Comment by ansilh** [comment]
Hi @aaronRancher ,
Thanks for looking it to it.
If we look at the "2. Scheduling" **after switching credential**  , the only field that changes is "Data Center" , all other values shows the first credential's values.

![scheduling](https://user-images.githubusercontent.com/11064902/81682053-3be0eb00-9472-11ea-82e9-58deff8f2bee.png)

**Comment by codyrancher** [comment]
@ansilh I haven't been able to reproduce this issue but I did notice a related issue which may resolve what you're seeing.

Could you change the `ui-index` setting to `https://releases.rancher.com/ui/vsphere-credentials/index.html` of a 2.3 rancher and let me know if that resolves the issue for you?

If it doesn't resolve the issue do you have a rancher server that I can point a UI at to dig deeper?

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version ec1ea7a99`
Steps:
* Add two vCenter credentials
* Click on Manager Node Template
* Click on vSphere
* Switch between two vCenter credentials and observe `Scheduling` fields update
* Observe new API calls are being made when credentials are switched

**Comment by ansilh** [comment]
Hi @aaronRancher , @codyrancher . This issue is not completely fixed.

After switching to the second vCenter credential, we get a warning that the Data Center value is not valid even though its correct.

![image](https://user-images.githubusercontent.com/11064902/98932386-481f3100-2505-11eb-9a90-d19204001d51.png)

While saving the template, the POST call still takes values from the first vCenter.

![image](https://user-images.githubusercontent.com/11064902/98932423-4eada880-2505-11eb-8208-fd9a9dd8655a.png)

Cc: @maggieliu

**Comment by ansilh** [comment]
For the sake of easiness of testing, we can use the vCenter simulator to create this scenario 

Below are the steps I've used to create this test.

1. Download govc binary 
https://github.com/vmware/govmomi/tree/master/govc

2. Compile vcsim 
https://github.com/vmware/govmomi/tree/master/vcsim

3. Start two instances of vcsim 
```
$ mkdir /tmp/MyDS01 /tmp/MyDS02
$ chmod 777 /tmp/MyDS01 /tmp/MyDS02
$ vcsim -l :8880 -dc 0 & 
$ vcsim -l :8881 -dc 0 &
```
4. Setup vCenter invetory using govc  (Assuming simulator is running on a VM with IP 192.168.110.111)

vCenter-1
```
export GOVC_URL=https://user:pass@192.168.110.111:8880/sdk GOVC_SIM_PID=7760
export GOVC_INSECURE=true 

./govc datacenter.create MyDC01
./govc cluster.create MyCluster01
./govc cluster.add -hostname Myhost1 -username user -password pass -noverify
./govc datastore.create -type local -name MyDS01 -path /tmp/MyDS01 MyCluster01/*
./govc vm.create -ds gostore -cluster MyCluster01 MyVM1
./govc find -l # verify invetory 
```

vCenter-2
```
$ export GOVC_URL=https://user:pass@192.168.110.111:8881/sdk GOVC_SIM_PID=7760

./govc datacenter.create MyDC02
./govc cluster.create MyCluster02
./govc cluster.add -hostname Myhost2 -username user -password pass -noverify
./govc datastore.create -type local -name MyDS02 -path /tmp/MyDS02 MyCluster02/*
./govc vm.create -ds gostore -cluster MyCluster02 MyVM2
./govc find -l
```
Now we can use these two vCenter instances to test and verify the scenario.
