### ISSUE TITLE
UI is stuck on saving "custom" cluster info in 2.4.3 - Note: Clusters can still be upgraded with docker command

### ISSUE THREAD

**Issue by richyta** [rancher/rancher#26996]
After upgrading from rancher 2.3.6 to 2.4.3 kubernetes upgrade is stalling and not completing.
<img width="1220" alt="Screen Shot 2020-05-08 at 10 43 53 AM" src="https://user-images.githubusercontent.com/39923752/81433058-d232ab00-9118-11ea-81e2-5df382b34fc8.png">

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
|Route|`undefined`|

**Comment by sangeethah** [comment]
@richyta , Could you provide the exact steps that was done after rancher server was upgraded to 2.4.3 .
Were you attempting to add a worker node to an existing cluster?

**Comment by richyta** [comment]
No not adding a new node just upgrading the existing one to the lastest kubernetes version.

**Comment by sangeethah** [comment]
Can you provide the k8s versions prior to upgrade and the version you were upgrading to ? Is this a custom cluster ?

**Comment by richyta** [comment]
1.17.4

**Comment by izaac** [comment]
@sangeethah @richyta I did an upgrade in a Rancher single install.

Custom cluster in `v2.3.6` with k8s version `v1.17.4-rancher1-2`
Upgrade to `v2.4.3` wait for the agents to be upgraded.
Upgrade K8s in the cluster to `v1.17.5-rancher1-1`

![Screen Shot 2020-05-08 at 11 40 07 AM](https://user-images.githubusercontent.com/27659/81438892-5dfd0500-9122-11ea-8cd8-c70245576659.png)


Upgrade was successful and the cluster Active.

**Comment by richyta** [comment]
I am running this in a 3 node HA environment so maybe different in a single rancher instance install verses an HA environment.

**Comment by izaac** [comment]
@richyta cool thanks I will try HA, I assumed this was a single install.

**Comment by richyta** [comment]
No this was done on 3 node HA not single install.

**Comment by richyta** [comment]
Most companies that I am aware of will have an HA environment and not a single node instance install. I primarily use single node install to perform testing and not ran in production.

**Comment by richyta** [comment]
We have a replicated HA testing environment that we use to perform upgrades prior to pushing it to dev, staging and production environments.

**Comment by richyta** [comment]
Thanks for testing  izaac. Look to hearing how it goes for you.

**Comment by izaac** [comment]
What's the current state of the cluster at the moment? As I wasn't able to reproduce the issue in an HA setup either.

Would you be able to share the logs of your setup?

Thanks @richyta

**Comment by richyta** [comment]
Cluster has no issue that I can tell at the moment. As for the logs I would need to check with our team.

**Comment by richyta** [comment]
So the cluster has 3 master nodes that has all the roles on them and 3 worker nodes running. Just FYI.

**Comment by richyta** [comment]
I will try deploying another worker node with the new setup and see if that deploys or not to test.

**Comment by izaac** [comment]
@richyta I will try again the HA upgrade with the Custom cluster 3 nodes all roles. Thanks for the info.

**Comment by richyta** [comment]
Interesting so even when I go to add a new cluster I am having issues creating it.

**Comment by sangeethah** [comment]
@richyta Could you share your rancher server logs ? In case of new cluster creation , what is the exact behavior you are seeing ?

**Comment by richyta** [comment]
Can you provide info on how to grab the logs for rancher?

**Comment by sangeethah** [comment]
@richyta Could you capture the actual api call made by UI and see if there are any console errors you are seeing when this action is peformed?

**Comment by richyta** [comment]
At this point its really not usable rancher 2.4.3. So we will stay with 2.3.6 until the bugs are fixed.

**Comment by deniseschannon** [comment]
Based on the original comment, it seems as if the problem is in the UI is stuck with the button as `Saving` which is not directly associated with the stability of the downstream cluster. Since you take the Docker command and apply it to your cluster, whatever happens in the UI is not correlated to the downstream clsuter.

@izaac Did you test clicking on `Save` on the UI to see that it can go back to the clusters page? 

@richyta Did you apply the docker command to your downstream cluster? Did the cluster become active? Is the complaint that the UI is stuck in `Saving`?

**Comment by izaac** [comment]
Got this from the user this is what the UI shows in console when clicking **Save** after selecting the K8s version to upgrade.

<img width="653" alt="Screen Shot 2020-05-08 at 4 01 02 PM" src="https://user-images.githubusercontent.com/27659/81456444-23f22a00-9147-11ea-8b72-90212b9ae1b1.png">

**Comment by codyrancher** [comment]
I'm guessing that the user doesn't have the cisscanconfig schema in their current cluster and scheduledClusterScan is enabled.

To get the cluster unstuck try disabling "Scheduled CIS Scan Enabled" and saving. More than likely it has nothing to do with the upgrade and if you attempted to save anything it would fail.

**Comment by izaac** [comment]
The issue seemed to be that in Richard's setup the Scheduled CIS  Scan Enabled option was unselected.

<img width="1260" alt="Screen Shot 2020-05-08 at 5 15 27 PM" src="https://user-images.githubusercontent.com/27659/81458673-69672500-9150-11ea-8151-0f4bbcce8ef5.png">

**Comment by codyrancher** [comment]
@maggieliu So I sent out a PR which should allow the user to still save even if they run into this issue.

Unfortunately I haven't been able to reproduce this with any kind of consistency. The one time I reproduced this issue it appeared that the cisscanconfig schema wasn't present. Though my change should stop the bleeding I think the proper fix will need to be a backend change.

**Comment by rancher-max** [comment]
### Reproduced reliably with the following steps:
1. Create a custom data.json for rke-metadata-config that does not have the CIS Config Params or CIS Benchmark Version Info
2. Install Rancher with the environment variable for RKE metadata config pointing to that data.json: `sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e "CATTLE_RKE_METADATA_CONFIG={\"refresh-interval-minutes\":\"144000\",\"url\":\"https://raw.githubusercontent.com/rancher-max/rke-data/master/data.json\"}" rancher/rancher:master-head`
3. Attempt to create a cluster. It will fail with all the errors mentioned above:
    - Null selection in Advanced Options > Scheduled CIS Scan Enabled
    - After clicking "Create", it just spins for ever with "Saving"
    - Same error in console as mentioned above

### Validated in both master-head and v2.4-head using UI index `latest2` and `latest-2.4` respectively

- Default value is set to `No` for Scheduled CIS Scan Enabled
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/55997940/82580209-b6c99600-9b43-11ea-87cc-44449a4cebdd.png">

- Creating cluster does not stall. Creates successfully

- Upgrading cluster is successful

- No error occurs in console logs


**NOTE: This fixes cluster creation/upgrade, but the error of having no CIS Scan Profiles is still present. #27005 will address that.**
