### ISSUE TITLE
Chosen namespace for Registry secret is not being respected

### ISSUE THREAD

**Issue by tvollstaedt** [rancher/rancher#26991]
When adding container registry credentials using Rancher UI, the selected namespace won't be taken over.

**Expected behaviour**: Secret will be saved into selected namespace

**Actual behaviour**: Secret will be saved into namespace `default`

**Workaround**: Adding the registry secret via `kubectl`.

Screenshots:

![image](https://user-images.githubusercontent.com/1023920/81425553-172a0200-9158-11ea-969b-1fb913f84553.png)

![image](https://user-images.githubusercontent.com/1023920/81425582-28730e80-9158-11ea-84ea-bce027341e69.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.2` UI: `v2.4.14` |
|Route|`undefined`|

**Comment by soumyalj** [comment]
This has been addressed in v2.4.3
https://github.com/rancher/rancher/issues/26813

**Comment by tvollstaedt** [comment]
Thanks, closing it as Duplicate of #26813
