### ISSUE TITLE
[Backport 2.3] Logging: AWS Elasticsearch: Cannot get new connection from pool 

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27003]
2.3 backport for https://github.com/rancher/rancher/issues/21744

**Comment by izaac** [comment]
Rancher version: `v2.3-head (05/14/20)` commit id: 091316568
Same results mentioned [here](https://github.com/rancher/rancher/issues/21744#issuecomment-627913007) for versions `v2.4-head` and `master-head`.

- Deployed an AWS ES Domain. (Domain should have enough EBS disk capacity for a long run)
- Setup cluster and project logging with flush interval to 1 second. (Cluster should have enough disk space for a long run).
- In a project deploy a web workload or any other docker container to generate logs and start monitoring the logs in Kibana in the ES Domain (Kibana is deployed automatically to analyze the logs).
- Left the logging running for 8+ not able to reach the connection reload issue.


`cluster.conf` and `project.conf` keys in the `rancher-logging-fluentd` secret had the values:

```
reload_connections false
reconnect_on_error true
reload_on_failure true
```
