### ISSUE TITLE
[2.3] Add Windows 1909 Agent Build

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27002]
We have 1809 and 1903 agent builds, a 1909 was released and we should probably add it to our drone.yaml for continued up to date windows agent support.

**Comment by deniseschannon** [comment]
k8s 1.18 added support for windows 1909 and currently 2.3 does not support k8s 1.18. 

https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#supported-functionality-and-limitations
