### ISSUE TITLE
Chart Update - Cost Analyzer (Kubecost)

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#27008]
Helm 2 Chart - Cost Analyzer v1.57.2 (Kubecost)
Located in the dev branch of https://github.com/rancher/charts

**Comment by rancher-max** [comment]
#### Validated in both v2.4-head and master-head using rancher chart branch `dev`

- Using default options deploys successfully
- Deploys successfully as multicluster app
- Using non-default options deploys successfully
- Links work correctly
