### ISSUE TITLE
Cannot upgrade grafana app from helm stable catalog

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#27014]
**Version:**
Rancher v2.4.3

**Steps to reproduce (least amount of steps as possible):**
1. Enable helm stable community catalog.
2. Provision a v1.17.5 cluster using AWS node driver
3. Deploy a grafana app(default 5.0.24 version) to the default project using the default answers.
4. Wait until the app is active.
5. Click upgrade

**Result:**
See the page loading but upgrade page is not shown up in the end.

**Other details that may be helpful:**
It works for grafana from library catalog.
It works for other app(drone, envoy) from hem stable catalog.
No error is observed in web browser console.

**Comment by thlassche** [comment]
Same here
