### ISSUE TITLE
Rancher EC2 support custom KMS encryption key

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#27015]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

Rancher 2.4.x support EC2 encryption but do not have option to use custom KMS keys
In AWS multiple accounts environments, encrypted AMI can only be shared with other AWS accounts using custom KMS key. An EC2 create from encrypted AMI using custom encryped KMS key should re-encryped with custom KMS key to enforce security.

Current, Rancher 2.4.x has encryption option but do not have a parameter for custom KMS key to re-encrypt EC2 as a result default EC2 encryption key used.

![image](https://user-images.githubusercontent.com/15118220/81522225-23e36b80-938d-11ea-99ea-4b54b6624325.png)

**Comment by panho66** [comment]
Need Terraform Rancher2 provider support additional KMS key as well.

**Comment by panho66** [comment]
This fail in Cloud Conformity security report not able to use KMS custom key but AWS encryption key.

**Comment by sowmyav27** [comment]
**verified on 2.4-head commit id: `b4d72a511`**

- Create an AWS node template. Set the below values while `View in API` of the node template (A kmsKey should be created)
```
encryptEbsVolume": True,
"kmsKey": "<key-id>", 
```

- Launch an AWS cluster using this node template
- the nodes of the cluster have volume linked show in the console

```
Encryption : Encrypted
KMS Key ID: <key id> 
KMS Key Aliases: <KMS Key name>
```

**Comment by sowmyav27** [comment]
master PR: https://github.com/rancher/rancher/pull/27967
