### ISSUE TITLE
"Try Dashboard" only works for one of three clusters

### ISSUE THREAD

**Issue by StoneCut** [rancher/rancher#27020]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
setup HA rancher cluster using RKE cli
setup more some mmore cluster using RKE cli

**Result:**
Only the Rancher HA cluster can access the new dashboard.
All other clusters display an error and redirect to "fail-whale"

**Other details that may be helpful:**
All clusters utilize a proxy.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

Rancher 2.4.3
HA cluster (RKE cli)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

(Imported) RKE clusters
VMs

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Comment by soumyalj** [comment]
@StoneCut : Were you able to access the dashboard from the clusters after sometime ? 

Created a RKE cluster and imported the cluster in a HA setup (Rancher v2.4.3).
Accessed the dashboard from the imported RKE cluster. The error was seen for only a few (5) seconds. I was able to launch the dashboard when I tried retried launching again.

**Comment by StoneCut** [comment]
I've just now tried and I still can't access the other clusters. Is there any additional info I can provide? Any specific logs?

**Comment by jiaqiluo** [comment]
The bug is reproduced in a  Rancher v2.4.3 HA setup with a proxy.

The dashboard for the local cluster is accessible, but not for all other clusters 

<img width="625" alt="Screen Shot 2020-05-12 at 9 07 46 AM" src="https://user-images.githubusercontent.com/6218999/81720342-21d3e800-9433-11ea-970b-d3fabe16aecd.png">

**Comment by deniseschannon** [comment]
Is this still an issue in the v2.5.x line? With v2.4.x, it's experimental and might not work for proxy clusters.

**Comment by StoneCut** [comment]
> Is this still an issue in the v2.5.x line? With v2.4.x, it's experimental and might not work for proxy clusters.

It's working now. Thank you.
