### ISSUE TITLE
Rancher does not load 'IE Not Supported Page' on IE or Edge in 2.4

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#27021]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Spin up Rancher iand navigate using Chrome and then using IE form a Windows client

**Result:**
IE fails to load - expected to see - https://github.com/rancher/ui/pull/3554

**Other details that may be helpful:**
Seems to be stuck at a define value in js

IE View:

![IE View](https://user-images.githubusercontent.com/57944539/81571797-53e53b80-939a-11ea-95d3-c49a2c6634f7.png)

Chrome View:

![Chrome View](https://user-images.githubusercontent.com/57944539/81571811-55aeff00-939a-11ea-86e3-5fde1e8d9473.png)

Zoom in of error when I set IE to Chrome (else it just fails to load with no message):

![Zoom in of error when I set IE to Chrome (else it just fails to load with no message)](https://user-images.githubusercontent.com/57944539/81571820-5778c280-939a-11ea-96b1-17fc71a2759c.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.2/3
- Installation option (single install/HA): HA

**Comment by vincent99** [comment]
IE is not, has never been, and will not be supported.  (Including in 1.x from the very beginning)

**Comment by sangeethah** [comment]
Related issue - https://github.com/rancher/rancher/issues/24028

**Comment by izaac** [comment]
This is not reproducible in Rancher `v2.3.8` with Legacy Edge as it shows the `Sorry IE and Edge are not supported`
Although the message will be outdated as there's now Legacy Edge and the new Edge Browser based in Chrome.


This is reproducible in Rancher `v2.3.8` with IE11 (Version: 11.379.17763.0) this version is no longer redirecting to the message in the `/ie` path.

```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
<IP>
HTML1300: Navigation occurred.
<IP>
SCRIPT1002: Syntax error
vendor-b5552f80fff0826141c95c5df58c486c.js (7325,12)
SCRIPT5009: 'define' is undefined
ui-7f135d0498e3148bf30ba8afc9c0b6d2.js (2,1)
```

This error is reproducible in `v2.4.3`, `v2.4.5` in both IE11 and Legacy Edge.

Error in Legacy Edge:

```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
vendor-2d531df07709b83a209f5e946c74dd82.js (26518,44)

0: 'define' is not defined
ui-d599c23469b20d538262797ce176dc4a.js (1,1)
```

I am using the VMs provided by Microsoft with both IE11 and Legacy Edge installed: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by izaac** [comment]
Rancher version `master-head (07/02/2020)` commit _ec1ea7a99_

Operating System: Windows 10 1809 17763.379
I am using the VMs provided by Microsoft with both IE11 and Legacy Edge installed: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/


**Left: Internet Explorer 11
Right: Edge Legacy**
![Screen Shot 2020-07-02 at 12 52 21 PM](https://user-images.githubusercontent.com/27659/86403737-1fd41b80-bc63-11ea-920e-5b50c4362768.png)

New Edge browser (Version 83.0.478.58) works on Mac OS X and Windows 10

**Comment by izaac** [comment]
Validated also in Rancher version `v2.4-head (07/02/2020)` commit _efd76d86b_
