### ISSUE TITLE
When health check configs are different for targets of the same backend,one of the  health check configs is used for programming the backend. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2702]
Server version - Build from master

Service web1 has following health check configs:

"healthCheck": {
"interval": 2000,
"responseTimeout": 2000,
"healthyThreshold": 2,
"unhealthyThreshold": 3,
"requestLine": "GET /service2.html HTTP/1.0",
"port": 80,
},

Service web2 has following health check configs:

"healthCheck": {
"interval": 2000,
"responseTimeout": 2000,
"healthyThreshold": 2,
"unhealthyThreshold": 3,
"requestLine": "GET /service1.html HTTP/1.0",
"port": 80,
},

requestLine is different for both.

Created LB services for both these services. LB service uses one of the  health check config for programming the backend. 

<img width="694" alt="screen shot 2015-11-16 at 6 05 37 pm" src="https://cloud.githubusercontent.com/assets/4266958/11200828/ba7ba604-8c8d-11e5-8bc3-7b0460a110d3.png">

**Comment by alena1108** [comment]
This is known issue and always been there.

**Comment by alena1108** [comment]
Closing as we can't do anything about it. Request line for http health check gets configured on per backend on haproxy. Plus it is very unlikely that user would set 2 completely different services with different health checks behind the same backend. It would either be the same kind of service (when he does service upgrade using LB) or 2 backends, one per service.
