### ISSUE TITLE
Chart Update - Trivy v0.6.0

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#27027]
Helm 2 Chart - Trivy v0.6.0
Located in the dev branch of https://github.com/rancher/charts

Note: I couldn't figure out an endpoint to test this API directly after deployment. So I deployed the latest Harbor chart through a custom catalog (You need it to add custom scanners) and added the scanner(Trivy) using their instructions. This way you can test the scanner's health through Harbor directly. If you need more information on this, let me know.

**Comment by rancher-max** [comment]
#### Validated in v2.4-head and master-head using `dev` catalog branch

- Able to deploy multi-cluster apps with trivy using default values and non-default values
- Able to deploy normal app with trivy using default values and non-default values
- Able to deploy into different namespaces

In all cases, app workloads come up successfully and appear functional
