### ISSUE TITLE
[2.4.3] "Container Default Resource Limit" has default value and cannot be cleared

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#27038]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Add project or namespace
2. Open `Container Default Resource Limit`
3. Mouse click on the input boxes of `Memory Limit`,` CPU Limit`, `CPU Reservation`, and` Memory Reservation` without entering any parameters, and then click anywhere else

**Result:**
Different default values will appear in the input box, and cannot be cleared

![image](https://user-images.githubusercontent.com/19684717/81693402-6a6ebe00-9492-11ea-9a5d-68bf3dbbea24.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.3  UI:v2.4.22
- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom

**Comment by kingsd041** [comment]
Add  custom cluster, `CNI Plugin MTU Override` has the same problem

**Comment by soumyalj** [comment]
Reproduce the issue with v2.4.3
Validated with v2.4-head(8e20687a4)
Steps:
1. Add a new project or namespace
2. Open Container Default Resource Limit
3. Mouse click on the input boxes of Memory Limit, CPU Limit, CPU Reservation, and Memory Reservation without entering any parameters, and then click anywhere else

Results:
Mouse clicking and clicking else where does not introduce arbitrary values in the text boxes. 
Providing values in the text boxes and saving creates project/namespace with the right values as expected.
