### ISSUE TITLE
after upgrade to v2.4.3, cluster status Unavailable

### ISSUE THREAD

**Issue by lxkaka** [rancher/rancher#27035]
after upgrade to rancher/rancher:v2.4.3, some k8s cluster show error below
```
Failed to ensure monitoring project name: failed to find "cattle-prometheus" Namespace: Get https://172.21.0.1:443/api/v1/namespaces/cattle-prometheus?timeout=30s: EOF; cluster health check failed: Failed to communicate with API server: Get https://172.21.0.1:443/api/v1/namespaces/kube-system?timeout=30s: EOF
```
![image](https://user-images.githubusercontent.com/10549664/81633237-daebef80-943e-11ea-9c1f-fe55c5bde52d.png)   
when we restart rancher, this error may disappear

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
|Route|`undefined`|

**Comment by loganhz** [comment]
I think it will disappear even without restart. Once cluster agent reconnected, in the next loop Rancher will remove the error message.

**Comment by lxkaka** [comment]
I will continue to watch that.

**Comment by lxkaka** [comment]
actually, more than 30 minutes health check still failed. I will rollback to version 2.3.5

**Comment by gameiro** [comment]
I have the same issues with imported clusters. All the cluster start to be unavailable after upgrading to 2.4.3.

**Comment by jugou28** [comment]
I have the same issues.

**Comment by JunJiangWang** [comment]
The same issue.

**Comment by jls-tschanzc** [comment]
Same here.

Upgraded Rancher from 2.3.5 to 2.4.4 and mistakingly upgraded Monitoring to 0.1.0.
Monitoring did recover after a while (See here: https://github.com/rancher/rancher/issues/26969) but after a couple of days the Cluster now errors with the exact same error.

Env:

Imported EKS Cluster on k8s 1.15

Error:

```
Failed to ensure monitoring project name: failed to find "cattle-prometheus" Namespace: Get https://10.100.0.1:443/api/v1/namespaces/cattle-prometheus?timeout=30s: EOF; cluster health check failed: Failed to communicate with API server: Get https://10.100.0.1:443/api/v1/namespaces/kube-system?timeout=30s: EOF
```

We noticed that we can only see running instances of alerting-manager and prometheus-operator in the monitoring namespace, compared to 6 workloads on our healthy cluster.

Restarting the cattle-cluster-agent did not help.

**Comment by gameiro** [comment]
Hi @jls-tschanzc, I will try adding the env variable and see if it works with Oracle imported clusters as well.

**Comment by gameiro83** [comment]
I have installed last rancher version 2.4.5 and its seems to work 👍, also my Oracle Kubernetes Engine is using the latest kubernetes version for the service.

**Comment by lxkaka** [comment]
thank for the repl. I will try
