### ISSUE TITLE
New setting to manage "File an Issue" link

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27047]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
New setting(s) that can specify where the "File an Issue" will linked to. The options should be the default GH issue, or an email sent to a specific email address, which will be turned into a support ticket.

**Comment by maggieliu** [comment]
Additional requirement: Is it possible to configure the text for "File an Issue" with the same setting?

**Comment by aaronRancher** [comment]
The feature is verified with Rancher server `rancher\rancher:master-head` `version d9184e914` and Rancher server `rancher\rancher:v2.4-head` `version aae934198`

By default, "File an Issue" will link to a new GH issue:
![Screen Shot 2020-05-27 at 9 51 15 AM](https://user-images.githubusercontent.com/57409052/83052778-a2364380-a004-11ea-8a2d-bc2169ea4267.png)

This feature adds a new setting, `ui-issues`:
![Screen Shot 2020-05-27 at 9 43 27 AM](https://user-images.githubusercontent.com/57409052/83053091-0ce77f00-a005-11ea-8f32-3521371bbee3.png)

The field can be edited with a `mailto:` link:
![Screen Shot 2020-05-27 at 10 32 28 AM](https://user-images.githubusercontent.com/57409052/83053392-7f585f00-a005-11ea-8108-93a01aa6ca27.png)

"File an Issue" will point to the link in the `ui-issues` field:
![Screen Shot 2020-05-27 at 10 20 05 AM](https://user-images.githubusercontent.com/57409052/83053079-0527da80-a005-11ea-93aa-eaa198e780b0.png)

**Comment by vincent99** [comment]
It is a standard link href and you can put in whatever you like, which the user's client may or may not respect..  most will do

`mailto:foo@bar.com?cc=someone-else@bar.com&subject=blah&body=blah`

The values will need to be url-encoded.
