### ISSUE TITLE
Failing to Assign Rancher Administrator role to OpenLDAP group

### ISSUE THREAD

**Issue by vynguyenchantal** [rancher/rancher#27045]
The goal is to assign Rancher global Administrator role to an OpenLDAP group so that all users/members in that specific LDAP Group can access Rancher UI with admin privileges.

I follow the instruction from this https://rancher.com/docs/rancher/v2.x/en/admin-settings/rbac/global-permissions/#assigning-a-custom-global-permission-to-a-group - Configuring Global Permissions for Groups.

I have OpenLDAP authentication enabled in Rancher 2.4.3. I have rancher-admin OpenLDAP group that I assign the Rancher global Administrator role (in addition to Standard User role). As a user/member of the "rancher-admin" group, I should be able to login to Rancher UI with admin access. However, that's not the case. It appears I only have Standard User permission since I do not see any resources (clusters, projects, etc.).

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Login with an OpenLDAP account (with administrator role)
2. Global>Security>Groups - click Assign Global Role
3. On the Assign Global Roles To Group 
a) Select Group to Add - type in the OpenLDAP group (i.e. rancher-admin)
b) Global Permissions - click Administrator (leave Standard User checked)
4. Click Refresh Group Memberships
5. Login with an OpenLDAP account that is a member of the rancher-admin group.
The expected behavior: the account has the default user permission and also the global Administrator role. 

**Result:**
The OpenLDAP account that is a member of rancher-admin group does NOT inherit the global Administrator role.

**Other details that may be helpful:**
OpenLDAP version: 2.4

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): t2.large
- Kubernetes version (use `kubectl version`): v1.17.5

- Docker version (use `docker version`): 1.13.1

**Comment by zbialik** [comment]
I can confirm this is failing for me. We were mainly looking to upgrade Rancher to v2.4.x to leverage this new Group feature for LDAP Authentication. We are delaying upgrading because of this. Appreciate the support!

**Comment by vynguyenchantal** [comment]
I no longer have the issue after I updated the configuration for Users and Groups attributes base on these 2 links: 
1) https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/openldap/openldap-config/#user-schema-configuration
2) https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/openldap/openldap-config/#group-schema-configuration

Thank you.
