### ISSUE TITLE
[Feature Request] ability to add custom private helm catalog with user and password flags by using rancher cli

### ISSUE THREAD

**Issue by dorsany** [rancher/rancher#27044]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
`rancher catalog add --help`

```
Add a catalog

Add a new catalog to the Rancher server

Example:
  # Add a catalog
  $ rancher catalog add foo https://my.catalog

  # Add a catalog and specify the branch to use
  $ rancher catalog add --branch awesomebranch foo https://my.catalog
Usage:
  rancher catalog add [OPTIONS] [NAME, URL]
```

no mention of adding custom private catalog with username and password
I couldn't find any mention about username or password flags in the rancher cli code: https://github.com/rancher/cli/blob/master/cmd/catalog.go

**Other details that may be helpful:**
we can do this by using the web ui but unable to do this by using the `rancher cli`
This document show how to add custom private catalog with username and passowrd using the web ui:
https://rancher.com/docs/rancher/v2.x/en/catalog/catalog-config/

**Comment by dorsany** [comment]
FYI @brendarearden

**Comment by jpreese** [comment]
Related: https://github.com/rancher/rancher/issues/22254

**Comment by dorsany** [comment]
@jpreese this is definitely not related!
You are asking for rancher login
I'm asking for adding private helm catalog (like chart museum) which protected with username & password by using the rancher cli, this is possible through the UI but not through the cli
