### ISSUE TITLE
Service's labels are set in lowercase on container but displayed as typed in UI

### ISSUE THREAD

**Issue by ViBiOh** [rancher/rancher#2704]
When setting a label on a service that contains uppercase letters, they are set in lowercase in the container.

e.g.

I set label `myAwesomeLabel=true` in service and I get "myawesomelabel": "true" with `docker inspect`.

I expect to have the label as typed in container, when others services use this label.

**Comment by vincent99** [comment]
Apparently rancher-compose has a similar issue, but I believe what was intended is that only Rancher system label keys (`io.rancher.*`) are lowercased.

Changed in the UI for v0.47 (next week)

**Comment by ibuildthecloud** [comment]
@vincent99 Are you saying there is a UI issue regarding this?  There is a definitely a backend issue that @alena1108 is fixing.  On the backend the keys get lower cased when transfered from the service launch config to the container.

**Comment by ViBiOh** [comment]
I agree with @ibuildthecloud, I don't want an UI fix, I want the label that I define is the label is set in the container.

Thanks @alena1108 for referencing the PR, it seems to be fixed ;)
