### ISSUE TITLE
[Backport 2.3] Update nginx to latest version available 

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27046]
Related to: https://github.com/rancher/rancher/issues/26377
https://github.com/rancher/rancher/issues/26957

**Comment by rancher-max** [comment]
#### Validated in v2.3.8-rc3

- Validated nginx-ingress-controller image used is: `rancher/nginx-ingress-controller:nginx-0.32.0-rancher1`
- Comes up successfully using all kubernetes versions (`v1.17.6-rancher2-1`, `v1.16.10-rancher2-1`, `v1.15.12-rancher2-2`) with all different network providers (canal, calico, weave, flannel)
