### ISSUE TITLE
Ability to dynamically fetch value from OCI API

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#27051]

**Comment by sowmyav27** [comment]
**On latest master-head - commit id: `ac02f1649`**

- Validation test `test_create_oke_cluster` fails here 
```
# Get the node shape
    if OCI_NODE_SHAPE is None:
        response = get_oci_meta_response("/meta/oci/nodeShapes", oci_cred_body)
```
**Error:**
```
'type': 'error', 'status': '404', 'message': 'Service error:NotAuthorizedOrNotFound. Authorization failed or requested resource not found.. http status code: 404.
```

**Comment by sowmyav27** [comment]
**On master-head (07/16/2020)**

- Validation tests for `test_oke_cluster` works.
- Cluster is deployed successfully.

**Comment by sowmyav27** [comment]
Another PR: https://github.com/rancher/rancher/pull/27945

**Comment by westlywright** [comment]
UI changes have been merged and are available in `latest2`

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: c428bc9feb**

- Deployed an OKE cluster successfully from UI.
- Created an OCI node template.
- Notice "ssh User" field is NOT available in the template
<img width="1236" alt="Screen Shot 2020-09-01 at 1 48 22 PM" src="https://user-images.githubusercontent.com/26032343/91904690-334b3500-ec5a-11ea-8839-f1be9d8176f6.png">

<img width="1240" alt="Screen Shot 2020-09-01 at 1 48 28 PM" src="https://user-images.githubusercontent.com/26032343/91904603-0dbe2b80-ec5a-11ea-8ac5-f38ed36f637a.png">

- Node is seen with error `Error creating machine: Error running provisioning: error installing docker:`

**Comment by jlamillan** [comment]
Regarding the error above:

> Error creating machine: Error running provisioning: error installing docker:

Rancher support for RHEL-8 / OL-8 is not complete and tracked here: https://github.com/rancher/rancher/issues/23045

**Comment by jlamillan** [comment]
Maybe we should be filtering out OL-8* images until https://github.com/rancher/rancher/issues/23045 is fixed?

**Comment by aaronRancher** [comment]
The feature is verified with Rancher servers: 
`rancher\rancher:master-head` `version a3a4c87`
`rancher\rancher:v2.5-head` `version d87f58a`
`rancher\rancher:v2.4-4037-head`

- Deployed an OKE cluster successfully from UI.
- Created an OCI node template.
- Observed driver data fetched from OCI API
![Screen Shot 2020-10-23 at 9 18 00 AM](https://user-images.githubusercontent.com/57409052/97029458-51bf0580-1512-11eb-9e26-439a8c892d60.png)
![Screen Shot 2020-10-23 at 9 28 34 AM](https://user-images.githubusercontent.com/57409052/97029619-86cb5800-1512-11eb-8629-4f9d3ee12961.png)

Tracking OL-8 support separately: #23045
