### ISSUE TITLE
Unable to upgrade downstream k3s clusters often - plan does not deploy or takes a long time

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#27069]
So far, I have only noticed the issue in master-head; reproduced numerous times. I only tested a couple of times in v2.4.3 but didn't see the issue in that release. I still think we should investigate the cause of the issue in master so this doesn't pop up in v2.4.4 or v2.5 eventual release.

Version: master-2952-head `dd102af17`

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Install Rancher master-head (in my case single-node in Docker)
- On another VM, install K3s v1.17.3:
``curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.17.3+k3s1 sh -`
- Add the downstream k3s cluster to Rancher
- Edit the cluster and attempt to upgrade to v1.17.4+k3s1

**Result:**
This should fail every time. In one case this worked but took a very long time (over an hour?) to upgrade -- in this case i was upgrading from v1.17.3 directly to v1.18.2 via a fork of KDM which had this option.
Note: Not certain why, but when doing this in Rancher v2.4.3 everything seems to work just fine.

**Other details that may be helpful:**
Ricky has been supplied Rancher logs and system-upgrade-controller pod logs.

**Comment by rmweir** [comment]
I think this may have been related to an issue with lasso not re-queueing when a controller returns an error. It would also explain why the k3s cluster randomly updated after a long wait. Build failed so wasn't in latest image until about 20 minutes ago.

**Comment by davidnuzik** [comment]
Should be fixed in master-head now. Will do some more checks then we can probably close this out as resolved.

**Comment by davidnuzik** [comment]
Version: master-2962-head (`7248f0966`)

The fix is confirmed. This is now working in the latest master-head. I tested a few times to make certain.

- Import a single-node k3s (v1.17.3)
- Upgrade to v1.17.4 (custom data.json)
- Upgrade to v1.18.2 (custom data.json)

Each time this worked without fail and quickly (in normal expected timeframe).
I didn't observe any concerning errors in logs while testing.
