### ISSUE TITLE
Workload operator-init-cluster-monitoring fails

### ISSUE THREAD

**Issue by Raboo** [rancher/rancher#27077]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Enable istio, enable monitoring.

**Result:**
System project Workload operator-init-cluster-monitoring fails.

**Other details that may be helpful:**
Monitoring version: 0.1.0
This is a workloads cluster that runs on RancherOS everything seems to work. I have no idea what the `operator-init-cluster-monitoring` actually does.

The pod has 3 containers.

State | Name | Image
-- | -- | --
Terminated/Error | operator-init-crds | rancher/istio-kubectl:1.1.5
Terminated | istio-init                            Init Container | rancher/istio-proxyv2:1.4.7
Running | istio-proxy | rancher/istio-proxyv2:1.4.7

I've tried deleting the pod, but the recreated pod get same errors and operator-init-crds fails.

Logs for operator-init-crds:
```
unable to recognize "/etc/operator-init/crd-alertmanager.yaml": Get https://10.43.0.1:443/api?timeout=32s: dial tcp 10.43.0.1:443: connect: connection refused
unable to recognize "/etc/operator-init/crd-podmonitor.yaml": Get https://10.43.0.1:443/api?timeout=32s: dial tcp 10.43.0.1:443: connect: connection refused
unable to recognize "/etc/operator-init/crd-prometheus.yaml": Get https://10.43.0.1:443/api?timeout=32s: dial tcp 10.43.0.1:443: connect: connection refused
unable to recognize "/etc/operator-init/crd-prometheusrules.yaml": Get https://10.43.0.1:443/api?timeout=32s: dial tcp 10.43.0.1:443: connect: connection refused
unable to recognize "/etc/operator-init/crd-servicemonitor.yaml": Get https://10.43.0.1:443/api?timeout=32s: dial tcp 10.43.0.1:443: connect: connection refused
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 9xVM (total: 46 cores/184 GB RAM)
- Docker version (use `docker version`): ce-19.3.8
- kubernetes version: v1.17.4

gz#11186

**Comment by l0bster** [comment]
same Problem here 

+1

**Comment by ThePolarNight** [comment]
Same Problem

State | Name | Image
-- | -- | --
Terminated | istio | v1.7.3
Running | istio-proxy | rancher/istio-proxyv2:1.7.3
