### ISSUE TITLE
access to rancher ui through http-proxy

### ISSUE THREAD

**Issue by dmzaytsev** [rancher/rancher#2707]
Setup:
Rancher server and hosts deployed on google cloud's vm.
Client has internet access through http-proxy.

Client not able to view logs and to execute shell 
Would it possible to get access to logs and shell  if client is behind a http-proxy ?
thanks

**Comment by deniseschannon** [comment]
Did you make sure to set up the proxy settings in Docker? I don't have a proxy so hard for me to test out. :) And I believe there shouldn't be any issues as long as the proxy settings are set up.

http://docs.rancher.com/rancher/installing-rancher/installing-server/#launching-rancher-server-behind-a-http-proxy
http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#hosts-behind-a-proxy

**Comment by dmzaytsev** [comment]
I didn't make any proxy settings on docker. both the rancher server and the hosts have a direct access to internet.
There is no problem if I have direct internet access as well.
But if I try to use rancher ui when I'm behind proxy, I have a problem, I can't open logs or execute shell.

I have made some screenshots below I hope it will help

![image](https://cloud.githubusercontent.com/assets/9972909/11222689/bdc7e7ea-8d8d-11e5-9ffd-768085113fda.png)

the websocket request returns error code 422

![image](https://cloud.githubusercontent.com/assets/9972909/11222728/f42f8b1c-8d8d-11e5-8c75-7eaa490cf99c.png)

**Comment by mishak87** [comment]
@dmzaytsev Shell and logs require working websocket connections have allowed them in proxy?

**Comment by dmzaytsev** [comment]
@mishak87 @deniseschannon 
I did the test for the websocket connections on http://www.websocket.org/echo.html
the proxy doesn't allow ws:// connections
only wss:// allowed
so I guess if I will use https Rancher server, the issue will be resolved
Thanks!
