### ISSUE TITLE
Add support for GovCloud regions for EKS

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#27080]
https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-eks-now-available-in-the-aws-govcloud-us-regions/

```
Amazon Elastic Kubernetes Service (EKS) is now available in AWS GovCloud (US) Regions.
```

gzrancher/rancher#12101

**Comment by sowmyav27** [comment]
**On master-head - commit id - `33f755f1809`**

- Create a cloud cred with region - us-gov-west-1
- Deploy a hosted EKS cluster by giving in the creds
- Error seen in console and UI

<img width="1674" alt="Screen Shot 2020-09-16 at 8 53 21 PM" src="https://user-images.githubusercontent.com/26032343/93418764-effae400-f85f-11ea-8cbc-5eff9187d0b2.png">

**Comment by thedadams** [comment]
After some investigation with @rmweir, it seems that maybe the hostname is incorrect in the request. When we make a request manually to `iam.us-gov-west-1.amazonaws.com`, we immediately get a `401` response.

When we make a request to `iam.us-gov.amazonaws.com` (the one in the error screenshot above), the request appears to timeout.

Is this perhaps an issue with the UI making a request to the wrong hostname?

**Comment by thedadams** [comment]
According to https://docs.amazonaws.cn/en_us/general/latest/gr/iam-service.html, the above is incorrect.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `393468fd` and master-head commit id: `5aa3918`**

Deployed hosted EKS clusters in `us-gov-west-1` region.
Clusters came up Active. Validation checks works fine on the clusters

**Comment by sowmyav27** [comment]
Blocked because of issue - https://github.com/rancher/rancher/issues/29103#issuecomment-733993630

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `b2953cbc` and master-head - commit id: `278c1f988`**

- Able to import an EKS gov cloud. Edit cluster--> Add node group -->Save changes made.
- Node group is seen added and the cluster comes up Active.
