### ISSUE TITLE
Bug: ec2 draining does not work

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#27084]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Create ec2 cluster on Rancher v2.3.5 or v2.4.3 using Kubernetes v1.15, v1.16 or v1.17
2) Attempt to drain node using the UI

**Result:**
It never drains the node, confirm results using CLI

**Other details that may be helpful:**
Tested in custom clusters and it works fine.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.5-v2.4.3
- Installation option (single install/HA): HA

gzrancher/rancher#10106

**Comment by sowmyav27** [comment]
**Validated on `rancher:2.3.5`** 

- Deployed an AWS RKE cluster - 1 master, 2 worker nodes W1, W2
- Deployed daemonset and workload with 10 pods.
- `Safe` Drain a worker node W1
- Pods are seen migrating to W2

**Validated on `rancher:2.4-head` latest**

- Deployed a 5 node cluster - 3 worker nodes
- Safe drain on worker node, drain pods in workloads and migrates to other nodes.

**Comment by patrick0057** [comment]
@sowmyav27 after performing the drain, do you see the node in question set as SchedulingDisabled as shown below?  This only happens for me if I do a drain from the CLI when using the EC2 provider.

```
> kubectl get node
NAME                                          STATUS                     ROLES                      AGE   VERSION
ip-172-31-11-216.us-east-2.compute.internal   Ready                      controlplane,etcd,worker   10m   v1.17.5
ip-172-31-12-2.us-east-2.compute.internal     Ready,SchedulingDisabled   controlplane,etcd,worker   10m   v1.17.5
ip-172-31-5-33.us-east-2.compute.internal     Ready                      controlplane,etcd,worker   10m   v1.17.5
```

**Comment by sowmyav27** [comment]
On 2.4.5

**Scenario#1**
- Deploy an AWS node driver cluster - 1 etcd/control, 2 worker nodes.
- Drain a worker node (safe drain)
- Node is seen in drained state
```
> k get nodes
NAME            STATUS                     ROLES               AGE     VERSION
sowmya-aws-1    Ready                      controlplane,etcd   3m31s   v1.18.6
sowmya-aws-w1   Ready,SchedulingDisabled   worker              48s     v1.18.6
sowmya-aws-w2   Ready                      worker              110s    v1.18.6
```

**Scenario#2**
- Deploy an AWS node driver cluster - 1 etcd/control, 2 worker nodes. Enable cloud provider
- Drain a worker node (safe drain)
- Node is seen in draining state. 
```
> kubectl get nodes
NAME                                          STATUS   ROLES               AGE     VERSION
ip-<>.us-west-2.compute.internal   Ready    worker              3m27s   v1.18.6
ip-<>.us-west-2.compute.internal   Ready    controlplane,etcd   5m4s    v1.18.6
ip-<>.us-west-2.compute.internal    Ready    worker              3m27s   v1.18.6
```
- Node will not be drained in this case because of this issue -- https://github.com/rancher/rancher/issues/23333

**Comment by patrick0057** [comment]
@sowmyav27 I have checked this in my lab and can confirm that it is also the case for me.

**Comment by sowmyav27** [comment]
Closing this issue. Tracking this issue in https://github.com/rancher/rancher/issues/23333
