### ISSUE TITLE
[Backport 2.3] Add 'cert-manager.io/issuer-kind: Issuer' to ingress.yaml in Rancher chart to mitigate https://github.com/jetstack/cert-manager/issues/2533

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27085]
related to https://github.com/rancher/rancher/issues/26505

**Comment by rancher-max** [comment]
#### Validated in v2.3.8-rc1

Following same steps as in https://github.com/rancher/rancher/issues/26505#issuecomment-629467217:

- Certificate becomes valid, signed by Let's Encrypt
<img width="485" alt="image" src="https://user-images.githubusercontent.com/55997940/82472447-08f3b400-9a7d-11ea-8012-75ca8d6e33a7.png">

- `kubectl describe ingress -n cattle-system` shows the correct, newly expected annotation of `issuer-kind=Issuer`:
```
...
Annotations:
  nginx.ingress.kubernetes.io/proxy-send-timeout:     1800
  cert-manager.io/issuer:                             rancher
  cert-manager.io/issuer-kind:                        Issuer
...
```
