### ISSUE TITLE
Rancher CLI apps install/upgrade with --atomic option for automatic rollback

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#27081]
What kind of request is this (question/bug/enhancement/feature request):
feature request

Automatic rollback if the app fails to install using the --atomic flag in helm.

Steps to reproduce (least amount of steps as possible):
rancher apps upgrade --atomic ...

Result:
If the app fails to install/upgrade correctly it will be rolled back automatically.

**Comment by Jonas18175** [comment]
Any process here? Or a workaround? I use CI pipeline to update deployments - so when an update fail the deployment goes offline .. an --atomic option is very useful.
