### ISSUE TITLE
OPA dashboard cannot read the catalog template data from Steve API

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#27087]
This is the backend ticket to support reading of catalog template data from steve API.

Corresponding dashboard ticket: https://github.com/rancher/dashboard/issues/655

**Comment by maggieliu** [comment]
related to: https://github.com/rancher/dashboard/issues/837

**Comment by deniseschannon** [comment]
With updates to how we handle helm charts in Dashboard, this isn't relevant any more.
