### ISSUE TITLE
Infinite error logging loop caused by App parsing error

### ISSUE THREAD

**Issue by kevinfrommelt-wf** [rancher/rancher#27082]
When installing or upgrading an App, if there is a parsing error in the chart or it's values, Rancher infinitely logs the failure until the app is deleted or upgraded to fix the parsing error.

While this is happening we are seeing other App install/upgrades sitting in the Deploying state (rather than going to Active) for upwards of an hour. These upgrades normally finish within a couple minutes. The upgrade seems to work right away, just that the status doesn't transition to Active.

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
```bash
rancher app install docker-registry docker-registry --no-prompt --version 1.9.2 --set "value=foo\,bar"
```

**Result:**
The App should show a parsing error in the UI
![Screen Shot 2020-05-14 at 1 08 27 PM](https://user-images.githubusercontent.com/3324904/81969946-563ad600-95e4-11ea-80e6-171cbe8f2851.png)

Server logs are full of errors like these
```
2020/05/14 17:58:35 [ERROR] AppController p-qsxvn/docker-registry [helm-controller] failed with : wait helm template failed. Error: failed parsing --set data: key "bar" has no value (cannot end with ,)
: exit status 1
2020/05/14 17:58:35 [ERROR] AppController p-qsxvn/docker-registry [helm-controller] failed with : wait helm template failed. Error: failed parsing --set data: key "bar" has no value (cannot end with ,)
: exit status 1
2020/05/14 17:58:35 [ERROR] AppController p-qsxvn/docker-registry [helm-controller] failed with : wait helm template failed. Error: failed parsing --set data: key "bar" has no value (cannot end with ,)
: exit status 1
2020/05/14 17:58:35 [ERROR] AppController p-qsxvn/docker-registry [helm-controller] failed with : wait helm template failed. Error: failed parsing --set data: key "bar" has no value (cannot end with ,)
: exit status 1
```

**Other details that may be helpful:**

**Environment information**
- Rancher version: v2.4.2, v2.4.3
- Installation option: HA

**Cluster information**
- Cluster type: Imported
- Machine type: Cloud
- Kubernetes version: v1.15.11-eks-af3caf

**Comment by Ilya-Kuchaev** [comment]
How can I delete such failed installation?

**Comment by kevinfrommelt-wf** [comment]
Related to https://github.com/rancher/rancher/issues/27146
