### ISSUE TITLE
[Backport 2.3] Need af-south-1 as UI option for AWS deployment via Rancher 

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27088]
Related to rancher/rancher#27042

**Comment by rancher-max** [comment]
#### Validated in v2.3-head UI index: `latest-2.3`

- Region is available as a Node Template selection for EC2:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/55997940/82271365-6c220100-992c-11ea-9864-660784c9ee7f.png">

- Creating cluster using this region is successful and basic operations can be performed against the cluster
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/55997940/82361830-447c7880-99c0-11ea-9370-f173dbeb331c.png">
