### ISSUE TITLE
[Backport 2.2] Need af-south-1 as UI option for AWS deployment via Rancher

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27083]
Related to  https://github.com/rancher/rancher/issues/27042

gz#10023

**Comment by rancher-max** [comment]
#### Validated in v2.2.12-rc1

I see the value in the UI now available:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/55997940/82097978-dc285100-96b8-11ea-99d7-a5751a9f7b6a.png">
