### ISSUE TITLE
Kubernetes Version not updating in Cluster UI

### ISSUE THREAD

**Issue by torpinouche** [rancher/rancher#27091]
**What kind of request is this (question/bug/enhancement/feature request):**
Minor bug (cosmetic)

**Steps to reproduce (least amount of steps as possible):**
 - Install k3s with v1.17.4+k3s1
 - Upgrade to v1.18.2+k3s1 with system-upgrade-controller using a plan
 - Wait for servers and agents to update

**Result:**
In the list of nodes of the cluster, the version is correct (v1.18.2+k3s1)
But if you hit  "Edit Cluster" on this page, it shows the initial version (v1.17.4+k3s1).

**Other details that may be helpful:**
Tried to empty cache.
Tried another browser.
Tried to restart the master.

It does not update.

**Environment information**

Rancher | v2.4.3
User Interface | v2.4.22
Helm | v2.16.5-rancher1
Machine | v0.15.0-rancher36

k3s HA with external DB, 2 masters and 6 nodes.
On premises Debian 10 VMs on Proxmox 4 vCPU 32GB RAM each.
Cluster imported in Rancher.

Thanks!

**Comment by adrianovieira** [comment]
Probably related issue #26483

**Comment by adrianovieira** [comment]
From this issue #25745...

At the "*Global*" menu goes to `tools > drivers>`  and execute **`refresh kubernetes metadata`**

Now it is working on our v2.3.8 HA environments and I can upgrade all downstream clusters.

Maybe it can work for you too.

**Comment by snasovich** [comment]
This is working as expected.
> But if you hit "Edit Cluster" on this page, it shows the initial version (v1.17.4+k3s1).
"Edit Cluster" shows the version from the `spec` which is a desired state.

Upgrading k8s version outside of Rancher is not supported for Rancher managed clusters and it seems that it's what was done here: _Upgrade to v1.18.2+k3s1 with system-upgrade-controller using a plan_. In such cases versions on `spec` and `status` will diverge and it's not a bug.
