### ISSUE TITLE
Cannot open rancher new dashboard page

### ISSUE THREAD

**Issue by zengyongjie** [rancher/rancher#27092]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Upgraded Helm installed  HA Rancher  from  version 2.2.4 to version 2.4.3 . 

**Result:**
Cannot open rancher dashboard page

**Other details that may be helpful:**

![image](https://user-images.githubusercontent.com/62204644/82001853-c2721400-968e-11ea-9757-81502dea81f5.png)

**Comment by superseb** [comment]
Please check https://github.com/rancher/rancher/issues/26980
