### ISSUE TITLE
document how to enable feature gates for k8s components

### ISSUE THREAD

**Issue by SimonHeimberg** [rancher/rancher#27095]
**What kind of request is this (question/bug/enhancement/feature request):**

enhancement for documentation

**Suggestion:**

Please document how to enable [Feature Gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) for kubernetes components.

**Current Situation:**
The only hints about it are in 
https://stackoverflow.com/questions/51336595/how-do-i-enable-mount-propagation-in-rancher-kubernetes-feature-gates/61458699

**Comment by loganhz** [comment]
There is `Edit as YAML` button in create/edit cluster page. And you can config the start params for each k8s component.

https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/

https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/

BTW, you could submit issue for docs in https://github.com/rancher/docs :)

**Comment by SimonHeimberg** [comment]
> There is a `Edit as YAML` button in create/edit cluster page. And you can config the start params for each k8s component.
> 
> https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/
> 

This pages explains how to edit the yaml data. Fine. But for a newbe it is not easy to find out that extra_args belongs there.
So maybe the example on above page could be extended with some useful examples of `extra_args`. But what is such an example? Maybe `feature-gates` is an advanced option which should not be shown as simple example?

> https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/
> 
> BTW, you could submit issue for docs in https://github.com/rancher/docs :)

I would normally do this. In this case I misunderstood the statement `Though we have many repositories related to Rancher, we want the bugs filed in the Rancher repository so we won’t miss them!` from https://rancher.com/docs/rancher/v2.x/en/contributing/#bugs-issues-or-questions . Shall I close here and create an issue in doc?
