### ISSUE TITLE
Rancher Docker Container Runs as Root - Security Risk

### ISSUE THREAD

**Issue by GetchaDEAGLE** [rancher/rancher#27090]
**What kind of request is this (question/bug/enhancement/feature request):**

enhancement

**Steps to reproduce (least amount of steps as possible):**

Run Rancher as a single container in Docker.

`sudo docker run -d --restart=unless-stopped -p 443:443 --name rancher-server rancher/rancher:v2.4.3`
`sudo docker exec -it rancher-server bash`
`whoami` - outputs **root**

**Result:**

When executing into the container and running bash, it is clear the container is running as the root user which is a security risk, regardless of using a jail (e.g. chroot).

**Other details that may be helpful:**

I am running Rancher as a regular Docker container (not using Docker Swarm or Kubernetes) for testing purposes. However, security is a major concern and always is. Therefore, I am seeking the most secure and least risky way of running Rancher. It's generally not a good practice to run a Docker container as root due to breaking out and accessing the Docker host.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

2.4.3

- Installation option (single install/HA):

single install

- Docker version (use `docker version`):

```
Docker version 19.03.8, build afacb8b7f0
```

**Edit 1:** I have tried running this container as a different user but always end up with the following error: `[FATAL] error running the jail command: exit status 1`

**Edit 2:** When using the userns-remap option to mitigate the issues with running root in the container, the error changes to `[FATAL] error running the jail command: exit status 2`

**Comment by ealasgarov** [comment]
I wonder whether any development had been done on this issue since then?
