### ISSUE TITLE
Missing refresh button after editing the catalogs item

### ISSUE THREAD

**Issue by DoNotSayYes** [rancher/rancher#27094]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Navigate to Global->Tools->Catalogs
2. Edit system-library and save. (e.g., change the branch from release-v2.4 to release-v2.3)

**Result:**
After the system-charts refreshed, the refresh button is gone. Reload the page can solve this problem.

Moreover, in version 2.4.7, the clone button is no longer available, please help confirm whether it is expected.

![image](https://user-images.githubusercontent.com/57614736/82020477-bc465c80-96bb-11ea-818c-cdf8fff97b36.png)

**Environment information**
- Rancher version (`rancher/rancher:v2.3.7` and `rancher/rancher:v2.4.3`):

**Comment by loganhz** [comment]
Websocket is not sending data with actions to UI. Introduced in https://github.com/rancher/rancher/commit/44f73ad06ed7bae3fddae27a7cad3a05f5f82e20#diff-00d385bb61358de9d6da349ec8a66ac8 https://github.com/rancher/rancher/commit/843e949b2286827f8ea971243dd18215f0df297f#diff-00d385bb61358de9d6da349ec8a66ac8

**Comment by DoNotSayYes** [comment]
**Version:**` rancher/rancher:v2.4.4`


**Steps to reproduce:**
1. On the catalogs page, add a record or edit one of the existing ones
2. Click the ellipsis and check the menubar 

**Result:**
The refresh button is not showing up until refreshing the page.
![image](https://user-images.githubusercontent.com/57614736/84366008-d9137880-ac04-11ea-99fa-be424b9af26b.png)
![image](https://user-images.githubusercontent.com/57614736/84366649-b7ff5780-ac05-11ea-9536-9ce2fa58a769.png)

**Comment by DoNotSayYes** [comment]
**Validation version:** ` rancher/rancher:master-head` off June 22, 2020

**Steps:**
1. On the catalogs page, add a record or edit one of the existing ones
2. Click the ellipsis and check the menubar 

**Result:**
Users will no longer need to refresh the page to get the refresh button back.
![image](https://user-images.githubusercontent.com/57614736/84367756-432d1d00-ac07-11ea-8e5e-fd6176790c8d.png)

**Comment by cbron** [comment]
@deniseschannon / @loganhz should this and https://github.com/rancher/rancher/issues/27163 get backported to 2.4/2.3 ?
