### ISSUE TITLE
Feature Request: Ability to have containers of a specific host get scheduled to another host

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2710]
Create an action on a host that would force all containers to be re-scheduled to a different host. This would allow users to provide maintenance to the host without having to actually remove the host and re-run rancher-agent registration.

Forum Issues:
http://forums.rancher.com/t/upgrading-docker-or-other-maintenance-on-a-host-is-this-the-best-way/912

**Comment by withinboredom** [comment]
+1

**Comment by will-chan** [comment]
This is something that is part of our API ready .  No UI added though.

**Comment by vincent99** [comment]
Evacuate was added a while ago..

**Comment by paulz1** [comment]
It seems that Evacuate do "Deactivates the host and deletes all non-infrastructure containers on it." and not re-schedule to another host. So to add the ability to re-schedule may be still a good idea.

If it's already realised in API, how could we use it?
