### ISSUE TITLE
Aggressive Drain option from UI does not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#27111]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Do an Aggressive drain from the UI on one of the worker nodes
- Request sent contains  : `deleteLocalData: "true"` only.

**Expected Result:**
Correct values of "Aggressive" drain option be sent - force: `true`

**Rancher logs** 
`2020/05/15 21:01:23 [INFO] Draining node sowmya-new-worker-longhorn-2 in c-8gbxq with flags --delete-local-data=true --force=false --grace-period=-1 --ignore-daemonsets=true --timeout=120s`

**Other details that may be helpful:**

- On 2.3.6, on doing an aggressive drain on a node - Request sent ocntains - `{deleteLocalData: true, force: true, ignoreDaemonSets: true, gracePeriod: -1, timeout: 60`
- Rancher logs: `2020/05/15 20:35:15 [INFO] Draining node sowmya-longhorn-236-1 in c-jx9h4 with flags --delete-local-data=true --force=true --grace-period=-1 --ignore-daemonsets=true --timeout=60s`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.17.5
```

**Comment by codyrancher** [comment]
While verifying this please take a look at the 'Drain nodes' section of the rke driver.

**Comment by codyrancher** [comment]
@lvuch @deniseschannon per the conversation here https://github.com/rancher/ui/pull/3997 it looks like we need to make some changes to the UI. Specifically want to change the mode section to expose two separate properties rather than just conflating them into safe and aggressive. The two properties being
deleteLocalData
force

We have the options on the node drain modal and in the rke config.
Node:
![image.png](https://zube.io/files/rancher/b6f7ef99f0a43f30d6dc8c8be8ea190a-image.png)
Config:

Would something like this be okay?
![image.png](https://zube.io/files/rancher/beff134a66ee84cd44d30e7aa56383bc-image.png)

If that's not okay would you mind putting something together?

**Comment by deniseschannon** [comment]
@codyrancher This looks fine to me.

**Comment by sowmyav27** [comment]
### **Verified on 2.4-head - commit id: `c357f562f`**

- Drain a node, the options available to the user is 
<img width="895" alt="Screen Shot 2020-05-29 at 9 37 06 AM" src="https://user-images.githubusercontent.com/26032343/83283556-3e408600-a190-11ea-935e-b0e7b9d61e16.png">

- Select `Delete Local Data` = True, `Force` = True, Give some values for `Drain timeout` and `Grace period for pods to terminate themselves`.
- Click on Drain.
- Request sent consists of all the input values - `{force: true, deleteLocalData: true, gracePeriod: "30", timeout: "60"}`

But the values for Drain pop up window -`Delete Local Data` , `Force`, `Grace period for pods to terminate themselves` and `Drain timeout` persists when trying to drain other nodes - logging a bug - https://github.com/rancher/rancher/issues/27339

### **On master-head - commit id: `4ef496126`**
- Drain a node, the options available to the user is 
<img width="837" alt="Screen Shot 2020-05-29 at 11 39 43 AM" src="https://user-images.githubusercontent.com/26032343/83293803-21607e80-a1a1-11ea-8875-def499105a47.png">

- Select `Delete Local Data` = True, `Force` = True, Give some values for `Drain timeout` and `Grace period for pods to terminate themselves`.
- Click on Drain.
- Request sent consists of all the input values - `{force: true, deleteLocalData: true, gracePeriod: "30", timeout: "60"}`
- But a panic occurs on the rancher server - https://github.com/rancher/rancher/issues/27168
But the values for Drain pop up window -`Grace period for pods to terminate themselves` and `Drain timeout` persists when trying to drain other nodes - tracking the issue in this bug - https://github.com/rancher/rancher/issues/27339
