### ISSUE TITLE
Feature Request: Ability to assign Okta groups to clusters and projects using local user account or Okta user that does not belong to that group

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#27110]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Description:**
Ability to assign Okta groups to clusters and projects using local user account or Okta user that does not belong to that group  Currently you cannot do this per our documentation:
https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/okta/

In the Rancher terraform provider you can force it, but the end result is that it appears the group has been added but the permissions do not work as shown in the screenshot below.
![image](https://user-images.githubusercontent.com/44879867/82092854-df1e4400-96ae-11ea-8503-9cfc6d3a8afa.png)

gz#10140

**Comment by triceras** [comment]
Thanks for looking into this @patrick0057.
The okta group can be assigned to the rke cluster via the Rancher2 terraform provider, however the permissions from the role assigned to the okta group don't work when done via terraform. It is possible to assign the okta group with role to the rke cluster manually via the Rancher UI.

**Comment by rawmind0** [comment]
In the Rancher2 terraform provider, whatever Okta group can be assigned, due to they are not checked. As commented, this shouldn't work as this can't be done at Rancher.

Beside that, assign okta groups (user belonging to them) seems working fine from tf provider. Tested on Rancher v2.4.3

**Comment by patrick0057** [comment]
@rawmind0 thanks!  I'm closing out this issue as there was a  bit of a misunderstanding when it was originally created.
