### ISSUE TITLE
how to upgrade a service with an API?

### ISSUE THREAD

**Issue by oprogramador** [rancher/rancher#27119]
In the UI, using dev tools, I checked it calls:
- POST /v2-beta/projects/:projectId/services/:serviceId/?action=upgrade
- POST /v2-beta/projects/:projectId/services/:serviceId/?action=finishupgrade

These endpoints require a token inside the cookies but I guess such a token is very volatile.

How can I use these endpoints (or other similar endpoints if they don't support that) with an access key and a secret key?

I tried just replacing the cookies with the HTTP basic authentication but I got `"status":422,"code":"ActionNotAvailable"`.

In the docs (https://github.com/rancher/api-spec/blob/master/specification.md) I cannot find these endpoints.

**Comment by oprogramador** [comment]
I just checked that `curl -i -X GET 'https://my-domain.com/v2-beta/projects/:myProject/services/:myService/' -u '` works both with `v2-beta` and `v1`.

So how can perform `upgrade` and `finishupgrade` actions with v1 or v2-beta API?

**Comment by oprogramador** [comment]
It works, I got an error because I was trying to perform the `upgrade` action during the state of not finished upgrade.

However, it would be good to refine docs to list explicitly all the available endpoints and actions.

**Comment by vincent99** [comment]
If you go to the API in a browser you get controls that show you all the actions and which are available right now for a particular resource.  1.x has been on its way out for over 2 years and is no longer actively maintained (except for critical security issues).
