### ISSUE TITLE
Cannot create cluster using af-south region

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#27112]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
In v2.2.12-rc1:
1. Create an EC2 cluster using af-south region

**Result:**
Cluster fails to come up. Rancher logs give: `2020/05/15 20:54:54 [ERROR] NodeController c-xmrsw/m-f92dg [node-controller] failed with : Error setting machine configuration from flags provided: Invalid region specified`

From internal discussion, looks like this requires a machine bump as well as the UI fix. Need to add new region to the machine repo. Similar to: https://github.com/rancher/machine/commit/1507ebcb0da94aa73c2d1a21052aa39f30fd0d08#diff-75a8caf025ffa85507ae86f2cf9ec352

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.12-rc1
- Installation option (single install/HA): HA

**Comment by StrongMonkey** [comment]
Available to test on v2.2.12-rc2.

**Comment by rancher-max** [comment]
#### Validated in v2.2.12-rc2 

- Able to create cluster in region af-south-1
- Cluster comes up successfully and basic regression tests pass (deploy workloads, rbac, exec shell, etc.)
