### ISSUE TITLE
Chart Update - Harbor v1.3.2

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#27114]
Helm 2 Chart - Harbor v1.3.2
Located in the dev branch of https://github.com/rancher/charts

**Comment by jiaqiluo** [comment]
The new chart is validated on Rancher v2.4-head 8e20687a4




Steps:
- run Rancher single install
- provision new cluster (ec2 nodes ) with 1 etcd, 1 control plane, 3 workers
- add the chart repo 
- deploy Harbor v13.2 with all default values 
 
Results:
The app is deployed successfully and functional on clusters with all 3 supported k8s clusters 

- 1.17.5-rancher1-1
- 1.16.9-rancher1-1
- 1.15.11-rancher1-3
