### ISSUE TITLE
Helm 安装 Rancher2.4.3 无法打开rancherUI网站. 

### ISSUE THREAD

**Issue by fws20060501** [rancher/rancher#27120]
**What kind of request is this (question/bug/enhancement/feature request):**
K3S(1.17.5+k3s1)   
Helm 安装 Rancher2.4.3 无法打开rancherUI网站. 

**Steps to reproduce (least amount of steps as possible):**
cd /home
chmod +x /home/helm/helm
cp /home/helm/helm /usr/local/bin/helm
helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
kubectl create namespace cattle-system
kubectl apply -f /home/CustomResourceDefinition/00-crds.yaml
kubectl create namespace cert-manager
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install \
 cert-manager jetstack/cert-manager \
 --namespace cert-manager \
 --version v0.12.0
kubectl get pods --namespace cert-manager

helm install rancher rancher-stable/rancher \
 --namespace cattle-system \
 --set hostname=rancher.515cn.com
kubectl -n cattle-system rollout status deploy/rancher

**Result:**
![图片](https://user-images.githubusercontent.com/51530023/82143463-bcd72280-9876-11ea-850d-35c48cd9105a.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):rancher/rancher
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 8C 16G
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5+k3s1", GitCommit:"58ebdb2a2ec5318ca40649eb7bd31679cb679f71", GitTreeState:"clean", BuildDate:"2020-05-06T23:43:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5+k3s1", GitCommit:"58ebdb2a2ec5318ca40649eb7bd31679cb679f71", GitTreeState:"clean", BuildDate:"2020-05-06T23:43:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:29:29 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:28:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by loganhz** [comment]
If you would like to ask questions in Chinese, please add `rancher3` to join 
Rancher WeChat group. Thanks
