### ISSUE TITLE
Cannot create TKE in Rancher

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#27121]
Tencent Kubernetes Engine introduced a breaking change in V3 API.
And Tencent has removed V2 API from their service endpoints last month. 
However, Rancher TKE kontainer engine is using V2 API.

**Comment by DoNotSayYes** [comment]
Reproduced in version v2.4.3
![image](https://user-images.githubusercontent.com/57614736/82784418-105af900-9e93-11ea-8c64-0399ac33a254.png)

Validated in version v2.4-head off 25th May
**Steps:**
1. Create cluster, choose Tencent TKE
2. Use valid Tencent credentials to proceed

**Result:**
TKE clusters can be provisioned successfully. 
![image](https://user-images.githubusercontent.com/57614736/82784760-c3c3ed80-9e93-11ea-9a41-8673895a2eb3.png)

Validated in version master-head off 25th May
**Steps:**
1. Create cluster, choose Tencent TKE
2. Use valid Tencent credentials to proceed

**Result:**
TKE clusters can be provisioned successfully. 
![image](https://user-images.githubusercontent.com/57614736/82784956-32a14680-9e94-11ea-82a6-55df167fa512.png)
