### ISSUE TITLE
[Backport 2.3] Need af-south-1 as UI option for AWS deployment via Rancher - Backend

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27130]
Backend work Related to https://github.com/rancher/rancher/issues/27042, https://github.com/rancher/rancher/issues/27088 (UI backport)

**Comment by rancher-max** [comment]
#### Validated in v2.3-head

See https://github.com/rancher/rancher/issues/27088#issuecomment-630990269 for validation details.
