### ISSUE TITLE
Can't add a registry credential by using the same name as a secret

### ISSUE THREAD

**Issue by DoNotSayYes** [rancher/rancher#27132]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Navigate to Cluster->Project->Secretes page
2. Add a `Secrets` record, name it as `test`
2. Add a `Registry Credentials `record, name it as `test` as well

**Result:**
When adding a registry credential by using the same name as a secret, an error shows up and says: `secrets "test" already exists`
![image](https://user-images.githubusercontent.com/57614736/82241026-ff2f5b00-996d-11ea-84fc-179a1c6158a3.png)
 

**Environment information**
- Rancher version (`rancher/rancher:v2.4.3`)

**Comment by splattner** [comment]
Secrets and Registry credentials are both of `kind: Secret` and just have a different type (`Opaque` vs. `kubernetes.io/dockerconfigjson`. You cannot use the same name twice or more for a secret.

The same behavior also applies to certificates (they have type `kubernetes.io/tls`)

**Comment by DoNotSayYes** [comment]
> Secrets and Registry credentials are both of `kind: Secret` and just have a different type (`Opaque` vs. `kubernetes.io/dockerconfigjson`. You cannot use the same name twice or more for a secret.
> 
> The same behavior also applies to certificates (they have type `kubernetes.io/tls`)

Many thanks.
