### ISSUE TITLE
[Backport 2.4] Need af-south-1 as UI option for AWS deployment via Rancher - Backend

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27131]
Backend work Related to https://github.com/rancher/rancher/issues/27042 (Main  UI issue for 2.4.4 + Master)

**Comment by sangeethah** [comment]
Related UI fix - https://github.com/rancher/rancher/issues/27042

**Comment by rancher-max** [comment]
#### Validated in both master-head and v2.4-head

See https://github.com/rancher/rancher/issues/27042#issuecomment-630502207 for validations. This backend change is necessary for the clusters to come up successfully when using this region:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/55997940/82271190-f4ec6d00-992b-11ea-9ec5-c63dcbebd353.png">
