### ISSUE TITLE
If stack name is long, UI does not look good

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#2714]
```
Component 	Version
Rancher 	v0.44.0
Cattle 	v0.107.0
User Interface 	v0.65.0
Rancher Compose 	v0.5.1
```

One suggestion is to space out the host sections and use available real estate 

![image](https://cloud.githubusercontent.com/assets/7720752/11229967/94717322-8d4f-11e5-950b-7f4ea63f513e.png)

**Comment by vincent99** [comment]
These should really be limited to 63 chars in the API, but we can clip in the UI too.

**Comment by westlywright** [comment]
@vincent99 should we limit the input or just clip the titles if they are longer then 63?

**Comment by vincent99** [comment]
The API (and therefore UI) should limit to 63, but we should just add `class="clip"` for now

**Comment by sangeethah** [comment]
Tested with rancher server version - v0.52.0-rc4.

UI now clips the stack name (with trailing ..).

<img width="356" alt="screen shot 2016-01-06 at 3 45 28 pm" src="https://cloud.githubusercontent.com/assets/4266958/12158197/89e4215c-b48c-11e5-9a02-40ed91cc8397.png">
