### ISSUE TITLE
No longer able to 'upgrade' to older version, please reenable this option

### ISSUE THREAD

**Issue by mverleun** [rancher/rancher#27150]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Deploy an App using the GUI by selecting the App and the version as shown below where there is a lot of choice in versions, we start with the lowest:
![PolitieNL-Dev](https://user-images.githubusercontent.com/11242627/82339278-2594db00-99ee-11ea-9a44-dcf5b036e838.png)
Upgrade the App using the upgrade feature of the GUI to a higher version shows still all possible versions as shown below:
![PolitieNL-Dev](https://user-images.githubusercontent.com/11242627/82339516-67be1c80-99ee-11ea-8ea4-f284c09a304a.png)
When on the high version number it is not possible to 'upgrade' to a previous version any longer as it was with Rancher 2.3.5
![PolitieNL-Dev](https://user-images.githubusercontent.com/11242627/82339633-8a503580-99ee-11ea-8382-7b09309dba72.png)

The Rollback option is not useful for two reasons:
- If a version is skipped you can not roll back to it
- The overview of the Apps in de rollback list has no understandable relation with the version numbers of the Apps

**Result:**
Older versions no longer selectable. Downgrade's are difficult and can only be done by completely deleting an App (and its resources) and redeploy it...

**Other details that may be helpful:**
It worked well on the previous version of Rancher (2.3.5)

**Environment information**
- 

| Component | Version |
| -- | -- |
| Rancher | v2.4.3 |
| User Interface | v2.4.22 |
| Helm | v2.16.5-rancher1 |
| Machine | v0.15.0-rancher36 |

- Installation option (single install/HA): Single install of the App

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 3 controllers, 6 workers, all 4CPU/24Gb each
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

gzrancher/rancher#10473

**Comment by w3blogfr** [comment]
If we upgrade from 1.0.0 to 2.0.0, we don't have any possibility to re-install the previous 1.0.0.

It's a big breaking change.

**Comment by vincent99** [comment]
Introduced in 2.3.4 [here](https://github.com/rancher/ui/commit/f95c884acb6d52efead49953060aedeaf4e329c8#diff-cb9ef8bdcc338208165f7c620890a1bfR71).

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/26661

**Comment by deniseschannon** [comment]
@mverleun Please try using "Rollback" to your older versions of your application.

**Comment by mverleun** [comment]
First of all thanks to everybody explaining the reason why it can not be done and suggesting workarounds.

Let me change this into a feature request. Just like it was to enforce this behaviour.
The reason why we would like this possibility is two fold:

1. A roll back can only be done to versions that have been installed before. If a version was skipped, or if the history of installations is erased by accident it can not be used. 
Besides that, the rollback history very hard to use in the sense that you have to select something based on date since the rollback info does not show any original version numbers.

2. Our developers are used naming there versions using server numbering followed by either RELEASE or SNAPSHOT. Snapshot is coming from Maven. 
When a version is released we upgrade to the next RELEASE. But this is not at the end of the list, there are quite some new SNAPSHOT versions as well since development continues.
If by accident the upgrade went wrong and a SNAPSHOT was used we had the ability to 'downgrade' to the latest release in our test cluster (Production is a bit more secure and does not have snapshots btw)

So I would like to propose to make this feature a setting where it can be different between production and development/test clusters.

**Comment by maggieliu** [comment]
Plan is to revert the change made for Longhorn: https://github.com/rancher/rancher/issues/26661

**Comment by rancher-max** [comment]
#### Validated using ui-index: `https://releases.rancher.com/ui/latest2/index.html` and `https://releases.rancher.com/ui/latest-2.4/index.html` using Rancher v2.4.4

- I can "upgrade" to previous versions through the UI now:
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/55997940/83812060-b535bd00-a66f-11ea-96eb-2bd651185ef5.png">

**Comment by mverleun** [comment]
Thank you, this is appreciated a lot
