### ISSUE TITLE
[Backport 2.2] 1.15.12 + Nginx

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27153]
Support 1.15.12 + update Nginx

**Comment by jiaqiluo** [comment]
This is validated in  `v2.2.13-rc4`  either 
- freshly installed or 
- upgraded from `v2.2.12` as part of the release validation process.

The new image `rancher/nginx-ingress-controller:nginx-0.32.0-rancher1` are used in the `v1.15.12-rancher1-1` cluster with all 4 CNI plugins.
