### ISSUE TITLE
Not able to clone LB service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2715]
Server - Build from master

Steps to reproduce the problem:
Create a LB service with 2 other services as targets.
Start LB service.

Clone this LB service. Change the name and port of the LB service and "save".

User gets error message - "Validation failed in API: name"

API returns Status Code:422  - {"id":"5e5ed1dc-5cad-4488-bc24-3304ae44d2a4","type":"error","links":{},"actions":{},"status":422,"code":"NotNullable","message":null,"detail":null,"fieldName":"name"}

**Comment by alena1108** [comment]
Debugged, and seeing the "name" field being sent twice during clone. One has not null value, another has null value - and that causes the problems. I also see that "description" field being sent twice as well. 
@vincent99 do you have any hints why it could be happening?

**Comment by deniseschannon** [comment]
Verified in v0.57.0-rc5 that this is no longer an issue.
