### ISSUE TITLE
Cannot Unmute an Alert from GUI without refreshing the page

### ISSUE THREAD

**Issue by mscbpi** [rancher/rancher#27163]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Go to Alert Rules
Mute an Alert
Try to Unmute an alert

**Result:**

Error

**Other details that may be helpful:**

Refreshing the page works
API page works

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.4.3
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by loganhz** [comment]
Websocket is not sending data with actions to UI. Introduced in https://github.com/rancher/rancher/commit/44f73ad06ed7bae3fddae27a7cad3a05f5f82e20#diff-00d385bb61358de9d6da349ec8a66ac8 https://github.com/rancher/rancher/commit/843e949b2286827f8ea971243dd18215f0df297f#diff-00d385bb61358de9d6da349ec8a66ac8

**Comment by DoNotSayYes** [comment]
**Version:**` rancher/rancher:v2.4.4`
**Steps to reproduce:**
1. On Alerts Page, select one or more records and deactivate/mute them
2. Then choose those inactive records to re-activate/unmute them without refreshing the page

**Result:**
Error occures
![image](https://user-images.githubusercontent.com/57614736/84365609-47a40680-ac04-11ea-8590-549670341320.png)

**Comment by DoNotSayYes** [comment]
**Validation Version:**` rancher/rancher:master-head` off June 11, 2020


**Steps to reproduce:**
1. On Alerts Page, choose one or more records and deactivate them, and then re-activate them
2. Choose one or more alerting records and mute them, and then unmute them


**Result:**
All the actions are functional, no need to refresh the page anymore to proceed further actions
![image](https://user-images.githubusercontent.com/57614736/84368705-80de7580-ac08-11ea-8b29-43618eeea251.png)
![image](https://user-images.githubusercontent.com/57614736/84368765-93f14580-ac08-11ea-91d6-827eb8236c7f.png)
