### ISSUE TITLE
Pin docker-ce-cli version in https://releases.rancher.com/install-docker/<x.y.z>.sh

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#27161]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

With the release of [Docker CLI v19.03.9](https://github.com/docker/cli/releases/tag/v19.03.9) (on 2020-05-19), attempts to use https://releases.rancher.com/install-docker/<x.y.z>.sh to install Docker < 19.03, either manually or as part of node provisioning with a Rancher Node Provider, will result in failure to run docker CLI commands with an error of the format `Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39`. The workaround is to install v19.03, but where this is not an immediate option for a user (due to internal testing requirements), they are prevented from adding new nodes to existing clusters. Pinning a matching version of the docker-ce-cli package to the docker-ce package within the script install-docker script would appear like a possible mitigation of this.

**Environment information**
- Ubuntu 18.04 LTS
- https://releases.rancher.com/install-docker/18.09.6.sh

**Comment by Kamaradeivanov** [comment]
Same for me for two of my client ....
I got a shity night to fix find and fix the issue ....

**Comment by bashofmann** [comment]
The same problem also exists on centos 7 with docker 18.09.

**Comment by superseb** [comment]
This is an upstream issue, see https://github.com/docker/cli/issues/2533. We probably need to pin the versions to make around this issue.

**Comment by izaac** [comment]
Reproduced in `v2.4-head` commit 899dce29e using `https://releases.rancher.com/install-docker/18.09.sh`

```bash
2020/05/22 19:44:12 [INFO] [node-controller-rancher-machine] Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39
2020/05/22 19:44:12 [DEBUG] stdout:
2020/05/22 19:44:12 [INFO] [node-controller-rancher-machine]
2020/05/22 19:44:16 [DEBUG] stdout: Error getting SSH command to check if the daemon is up: ssh command error: command: sudo docker version err: exit status 1 output: Client: Docker Engine - Community
2020/05/22 19:44:16 [INFO] [node-controller-rancher-machine] Error getting SSH command to check if the daemon is up: ssh command error: command: sudo docker version err: exit status 1 output: Client: Docker Engine - Community
2020/05/22 19:44:16 [DEBUG] stdout:  Version:           19.03.9
2020/05/22 19:44:16 [INFO] [node-controller-rancher-machine]  Version:           19.03.9
2020/05/22 19:44:16 [DEBUG] stdout:  API version:       1.40
2020/05/22 19:44:16 [INFO] [node-controller-rancher-machine]  API version:       1.40
```

**Comment by izaac** [comment]
Reproduced in `v2.4-head` commit 899dce29e using `https://releases.rancher.com/install-docker/18.09.sh`

```bash
2020/05/22 19:44:12 [INFO] [node-controller-rancher-machine] Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39
2020/05/22 19:44:12 [DEBUG] stdout:
2020/05/22 19:44:12 [INFO] [node-controller-rancher-machine]
2020/05/22 19:44:16 [DEBUG] stdout: Error getting SSH command to check if the daemon is up: ssh command error: command: sudo docker version err: exit status 1 output: Client: Docker Engine - Community
2020/05/22 19:44:16 [INFO] [node-controller-rancher-machine] Error getting SSH command to check if the daemon is up: ssh command error: command: sudo docker version err: exit status 1 output: Client: Docker Engine - Community
2020/05/22 19:44:16 [DEBUG] stdout:  Version:           19.03.9
2020/05/22 19:44:16 [INFO] [node-controller-rancher-machine]  Version:           19.03.9
2020/05/22 19:44:16 [DEBUG] stdout:  API version:       1.40
2020/05/22 19:44:16 [INFO] [node-controller-rancher-machine]  API version:       1.40
```

**Comment by superseb** [comment]
Scripts with pinned versions are now live

**Comment by izaac** [comment]
Installations validated:

Docker install URLs used in node templates:

- 17.03: `https://releases.rancher.com/install-docker/17.03.sh`
- 18.06: `https://releases.rancher.com/install-docker/18.06.sh`
- 18.09: `https://releases.rancher.com/install-docker/18.09.sh`
- 19.03: `https://releases.rancher.com/install-docker/19.03.sh` 



- Docker 17.03 with Ubuntu 16.04
- Docker 18.06 with Ubuntu 18.04
- Docker 18.09 with Ubuntu 18.04
- Docker 19.03 with Ubuntu 18.04

- Docker 18.06 with CentOS 7
- Docker 18.09 with CentOS 7
- Docker 19.03 with CentOS 7

Clusters were provisioned and active in Rancher `v2.4-head (05/22/2020)` commit 899dce29e
Spot checked 18.06 and 18.09 using Ubuntu 18.04 in Rancher `v2.3.7`.
