### ISSUE TITLE
Log "error running the jail command: exit status 2" seen when using CRI-O with default permissions

### ISSUE THREAD

**Issue by kubealex** [rancher/rancher#27160]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Fresh k8s installation
Follow the steps on the setup documentation:
- Install cert-manager via helm chart
- Install rancher via helm chart 
- Use 'rancher' cert creation with cert-manager

**Result:**

tls-rancher secret not created.

Events in the cattle-system namespace:

99s         Warning   ErrGetKeyPair       issuer/rancher                                      Error getting keypair for CA issuer: secret "tls-rancher" not found
99s         Warning   ErrInitIssuer       issuer/rancher                                      Error initializing issuer: secret "tls-rancher" not found

Logs in rancher pods:

2020/05/20 08:38:26 [INFO] Rancher version v2.4.3 (684884c00) is starting
2020/05/20 08:38:26 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features:}
2020/05/20 08:38:26 [INFO] Listening on /tmp/log.sock
2020/05/20 08:38:26 [INFO] Starting API controllers
2020/05/20 08:38:26 [INFO] Running in clustered mode with ID 10.85.0.52, monitoring endpoint cattle-system/rancher
2020/05/20 08:38:27 [INFO] Starting API controllers
2020/05/20 08:38:27 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=Role controller
2020/05/20 08:38:27 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller
2020/05/20 08:38:28 [FATAL] error running the jail command: exit status 2

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): stable 
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```

```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by kubealex** [comment]
In addition to this, in the troubleshooting section we find:

**cert-manager pod in the kube-system namespace.**

this isn't true, as it is installed, by documentation in "kubectl create namespace cert-manager"

Documentation is inconsistent.

**Comment by kubealex** [comment]
Any tip?

**Comment by kubealex** [comment]
Up

**Comment by markc43** [comment]
It would be good to know more about your environment, can you provide: 
    Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
    Machine type (cloud/VM/metal) and specifications (CPU/memory):
    Kubernetes version (use kubectl version):
    Docker version (use docker version):

**Comment by kubealex** [comment]
Cluster type: standard k8s install on VM with 1 master/1 worker

Machine type: VM

Kubernetes version 1.18

Docker version: no docker, i use cri-o as container runtime for k8s


Il lun 25 mag 2020, 09:48 markc43 <notifications@github.com> ha scritto:

**Comment by kubealex** [comment]
Nevermind, tried another fresh install and worked.
No idea what happened!

**Comment by markc43** [comment]
Note I was able to reproduce with cri-o, I made a debug image and saw this:
```
+ cd /dev
+ tar cf - --exclude=mqueue --exclude=shm --exclude=pts .
+ cd /opt/jail/driver-jail/dev
+ tar xfp -
tar: ./urandom: Cannot mknod: Operation not permitted
tar: ./zero: Cannot mknod: Operation not permitted
tar: ./tty: Cannot mknod: Operation not permitted
tar: ./full: Cannot mknod: Operation not permitted
tar: ./random: Cannot mknod: Operation not permitted
tar: ./null: Cannot mknod: Operation not permitted
tar: Exiting with failure status due to previous errors
```

**Comment by kubealex** [comment]
I confirm, it doesn't work

**Comment by kubealex** [comment]
Adding MKNOD to capabilities in cri-o solves the problem. Opened an issue and pr on cri-o repo to fix it and increase compatibility

**Comment by markc43** [comment]
It'd be interesting to 
a) Know what the OCI runtime spec states that containers should be granted by default 
b) Know if Rancher really needs mknod, I changed the /usr/bin/jailer.sh script to be `+e` (not die on the mknod error) and the container started and I could register a cluster. Naturally this is a basic test but I had expected items to fail due to missing `urandom`/`random`.

You can quickly test with 
```
FROM docker.io/rancher/rancher:v2.4.3
RUN sed -i "s|set -e|set -x|" /usr/bin/jailer.sh
``` 
and ``--set rancherImage=myimage --set debug=true``

**Comment by kubealex** [comment]
I can provide some info on point a)

I opened an issue on cri-o and they said that MKNOD is not granted by default anymore for security reasons, because "99%" of containers have no need for that and it can be granted in securityPolicy.

**Comment by haimari** [comment]
Rancher does not specify how to handle this [issue](https://rancher.com/docs/rancher/v2.x/en/installation/options/helm2/helm-rancher/troubleshooting/)

It is not clear how to handle this.

```
kubectl -n cattle-system describe issuer
```

```
Events:
  Type     Reason           Age                From          Message
  ----     ------           ----               ----          -------
  Warning  ErrGetKeyPair    34m (x4 over 34m)  cert-manager  Error getting keypair for CA issuer: secret "tls-rancher" not found
  Warning  ErrInitIssuer    34m (x4 over 34m)  cert-manager  Error initializing issuer: secret "tls-rancher" not found
  Normal   KeyPairVerified  33m (x2 over 33m)  cert-manager  Signing CA verified
```

**Comment by pasancario** [comment]
I've faced same situation with CRI-O engine but fix above created by @kubealex was not properly working due a misconfiguration on yaml. 

Solution need to be like
```
spec:
      containers:
        - name: rancher
          securityContext:
            capabilities:
              add:
                - MKNOD
```

There was a securityContext missing just above capabilities.

**Comment by AndreasKappel** [comment]
ultimate solution for me was to add the MKNOD capability to the default capabilities in /etc/crio/crio.conf
Ansible script:
`- name: set MKNOD capability in /etc/crio/crio.conf
  lineinfile:
    path: /etc/crio/crio.conf
    insertafter: 'default_capabilities'
    line: '        "MKNOD",'
  notify:
    - restart crio`

**Comment by edikoston** [comment]
Muito obg, @pasancario 
Funcionou perfeitamente pra mim.
