### ISSUE TITLE
API don't show data array in containers

### ISSUE THREAD

**Issue by jbaojunior** [rancher/rancher#2716]
Hi Guys,

I have problem in consult a api with curl. It doesn't show data array inside data of container.

When I consult logged at UI the array data inside container is shown. I need of dockerHostIp information.

Below the data array at consultation when I am in UI:

```
{
    "id": "XXXX",
    "type": "container",
    "links": {
        ....
    },
    "actions": {
        ...
    },
    "name": "Lb Agent",
    ...
    "data": {
        "fields": {
            ...
            "networkIds": [
                5,
            ],
            "labels": {
                ...
            },
            ...
            **"dockerHostIp": "X.X.X.X",**
            ...
        },
        ...
}
```

**Comment by jbaojunior** [comment]
I'm crazy. Sorry. I used the wrong URL.

**Comment by vincent99** [comment]
The "data" field is only shown when making requests as an admin.  It is a debugging tool and should not be used/relied on for anything.
