### ISSUE TITLE
[UI Bug] CA Cert field text area is too wide.

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#27165]
**What kind of request is this (question/bug/enhancement/feature request):**

  - This is a UI Bug in the RKE template

**Steps to reproduce (least amount of steps as possible):**

  - Create a RKE Template
  - Go to the "etcd Snapshot Backup Target"
  - Select S3
  - Paste a "Custom CA Certificate" 
  - Then click "Create"
  - Now open the created template 

**Result:**
![screenshot_20-05-2020_1589980443](https://user-images.githubusercontent.com/1724149/82450846-82a39600-9aad-11ea-958e-99ba6ffb63c8.jpg)

**Environment information**
  - Rancher 2.4.3

gz#10075

**Comment by sowmyav27** [comment]
**Validated on 2.4.5**

**Steps:**

- Create an RKE Template
- Go to the "etcd Snapshot Backup Target"
- Select S3 Paste a "Custom CA Certificate"
- Then click "Create"
- Now open the created template by clicking on the rke template

<img width="1446" alt="Screen Shot 2020-06-25 at 4 24 02 PM" src="https://user-images.githubusercontent.com/26032343/85805177-73dd7e00-b700-11ea-912f-8832f818eb8f.png">

**Comment by sowmyav27** [comment]
**on 2.5-head commit id: `8201e080df` and master-head - commit id: `fbe2c30d9`**

- Create an RKE Template
- Go to the "etcd Snapshot Backup Target"
- Select S3 Paste a "Custom CA Certificate"
- Then click "Create"
- Now open the created template by clicking on the rke template

<img width="952" alt="Screen Shot 2021-02-04 at 8 36 56 PM" src="https://user-images.githubusercontent.com/26032343/106990390-00393000-6729-11eb-925f-99e6d2a1b6bd.png">
