### ISSUE TITLE
[UI] Remove github oauth scope from UI

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#27175]
UI adds the github oauth scope during login to the redirect URL that api sends https://github.com/rancher/ui/blob/master/lib/shared/addon/oauth/service.js#L7

From now on the api will send scopes along with clientID and UI won't add any scopes

For: https://github.com/rancherlabs/managed-rancher/issues/353

**Comment by izaac** [comment]
Reopening, as per @mrajashree findings detailed here https://github.com/rancher/rancher/issues/27028#issuecomment-634304117

**Comment by izaac** [comment]
Validated this using Github in new installs for

Rancher version `v2.4-head (05/28/2020)` 24c684289
Rancher version `master-head (05/28/2020)` 56a464049

I also smoke tested Google Auth  continued working (I was able to enable the auth and login afterwards.


Before in Rancher v2.4.3 installs the userattribute store shown none with the following `kubectl` command (for local and Github users):

```
kubectl get userattribute -o custom-columns='Name:UserName,Email:UserPrincipal.extraInfo.Email,Location:UserPrincipal.extraInfo.Location,Company:UserPrincipal.extraInfo.Company,Username:UserPrincipal.loginName'
Name   Email    Location   Company   Username
       <none>   <none>     <none>    <none>
       <none>   <none>     <none>    <none>
       <none>   <none>     <none>    <none>
       <none>   <none>     <none>    <none>
```

In `v2.4-head` and `master-head` the Github email and other details are stored now:

```
Name            Email          Location   Company   Username
test-39669      <none>         <none>     <none>    test-39669
test-53070      <none>         <none>     <none>    test-53070
izaacorguser1   izaacz@email.xx                        izaacorguser1
Izaac Zavaleta   jorge.izaaac@email.xx  Tempe, Arizona  Rancher Labs @rancher
 izaac
```

I've opened a separate issue found during upgrade scenario test #27321
