### ISSUE TITLE
Cloning a namespaced registry fails with an error

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#27173]
Version: v2.4-head

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a project and namespaces ns1, ns2
2.  Add a registry "testreg" providing credentials and choosing a registry(dockerhun/quay etc) available for a specific namespace
3. Clone the registry "testreg", provide a different name and other credentials. 
4. Hit "Save"

Results:
Registry creation fails with the error "No namespace specified"

![Screen Shot 2020-05-20 at 2 07 03 PM](https://user-images.githubusercontent.com/18536626/82497612-6ac71480-9aa3-11ea-90e1-c27704204d4c.png)

Namespace dropdown is missing in the clone view.

Note: As seen above, the scope changes to "Available to all namespaces in this project"
Before hitting "Save" the scope is "Available to a single namespace: newns"

**Environment information**
- Installation option (single install/HA): Single node

**Comment by codyrancher** [comment]
@soumyalj are you still able to reproduce this? If so, do you have any more specific repro steps because it appears to be working for me.

![reg](https://user-images.githubusercontent.com/55104481/82708621-8f51f680-9c33-11ea-9819-932945fda542.gif)

> Namespace dropdown is missing in the clone view.
This has been true for two years. This change disables the selection for clones. https://github.com/rancher/ui/commit/8625fe3528ebe0f00af8eaa15e2cd2a5f7f6126f

**Comment by soumyalj** [comment]
@codyrancher : I am still able to reproduce this issue in v2.4-head(aae934198)
Its the same steps I mentioned above. 
**Steps to reproduce (least amount of steps as possible):**
1. Create a project and namespaces ns1, ns2
2.  Add a registry "testreg" providing credentials and choosing a registry(dockerhun/quay etc) available for a **specific namespace**
3. Clone the registry "testreg", provide a different name and other credentials. 
4. Hit "Save"

Results:
Registry creation fails with the error "No namespace specified"

![Screen Shot 2020-05-26 at 5 43 51 PM](https://user-images.githubusercontent.com/18536626/82963789-9ac95880-9f78-11ea-9024-e7055bb2f1ee.png)

**Comment by soumyalj** [comment]
Validated with v2.4-head(b1591f04e819)
Steps:
1. Create a project and namespaces ns1, ns2
2.  Add a registry "testreg" providing credentials and choosing a registry(dockerhun/quay etc) available for a **specific namespace**
3. Clone the registry "testreg", provide a different name and other credentials. 
4. Hit "Save"

Namespace error does not show up now. The issue is fixed. 
Note: We can clone only to the namespace from where we cloned the registry .

**Comment by soumyalj** [comment]
Tested with master-head(a6da5de55)
In master, when a registry is cloned, UI with auth token is displayed instead of username and password .
![Screen Shot 2020-05-28 at 5 00 19 PM](https://user-images.githubusercontent.com/18536626/83206080-02acaa00-a105-11ea-9c99-f93205217b5f.png)

UI displayed for clone should be fixed to validate this issue. 
This is true for both registry available for all namespaces or a single namespace.

**Comment by codyrancher** [comment]
This appears to be a backend issue that was present on master-3063-head but is no longer present on the current master-head.

When we create the new registry resource the frontend sent
`{"index.docker.io": {"username": "a", "password": "a"}}`

But the backend responded with
`{"index.docker.io":{"auth":"YTph","password":"a","username":"a"}}`

That response updated the resource locally but the subsequent request after refreshing the page returns the expected resource without the "auth" property.

**Comment by soumyalj** [comment]
Validated with latest master(4ef496126)

Steps:

1. Create a project and namespaces ns1, ns2
2. Add a registry "testreg" providing credentials and choosing a registry(dockerhun/quay etc) available for a specific namespace
3. Clone the registry "testreg", provide a different name and other credentials.
4. Hit "Save"
Namespace error does not show up now. The issue is fixed.
The auth token UI error also is not seen.
