### ISSUE TITLE
[UI] Proposal of a Dashboard as default home page

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2718]
I feel that **rancher** is missing a dashboard giving major information to their users/admins. I also am in doubt if Dashboard should be apart from the environments or not, will let that as also for discussion.

In case everyone agrees, I would like to advance a couple of information that is crucial for me, supposing how they could be organized already:
- Stacks related info:
  - overall environment status (this could follow the behavior stack status has based on services)
  - number of online stacks
  - number of degraded stacks
  - number of offline stacks
  - number of online services
  - number of degraded services
  - number of offline services
- Infastructure related info:
  - overall environment status (same as stacks but based on hosts statuses)
  - number of online hosts
  - number of reconnecting hosts
  - number of offline hosts
  - cpu:
    - total power available
    - overall being spend for user (avg)
    - overall being spend for system (avg)
  - memory:
    - total power available
    - overall being spend (avg)
  - disk
    - total space available
    - total space used
    - space used by active volumes
    - space used by orphaned volumes (so we know how much we have to clean up)
    - space used by system ( available - volumes )
  - network
    - overall in (avg)
    - overall out (avg)
  - containers
    - total number of deployed containers
    - started count
    - degraded count
    - deploying count
    - stopped count
- Administration
  - Users
    - overall count
    - count of admins
    - count of users
  - Processes
    - count of all processes
    - count of running processes

EDIT Changelog:
- [20-Nov-2015 12:05 UTC] Added disk metrics

**Comment by bacheson** [comment]
+1 this would be awesome to have

**Comment by ibuildthecloud** [comment]
This would be great!  Thanks for sharing the information you'd like to see.  I love to hear more comments from users as to what information would be important for a dashboard.

**Comment by smw355** [comment]
+1
I'd also like to see:
1. Capacity and utilization data mapped against time series for each environment and stacks. Might be nice to have at a global level as well.
2. Audit feed view that showed actions/changes taken by users and system.
3. I'd add disk capacity to the above NW, Memory and CPU stats.

**Comment by cusspvz** [comment]
@smw355 

> Audit feed view that showed actions/changes taken by users and system.

There is an Event Feed request already #2200, think it could have users actions as well and it should be apart from the dashboard, but would be nice to have the most 5 recent activities on it.

> Capacity and utilization data mapped against time series for each environment and stacks. Might be nice to have at a global level as well.

My idea was to propose a global dashboard since racher is user/environment centric, but happens that it would lead to some UI rethinking, but most of users will have no more than 2 ou 3 environments, thats why I've let that to discussion.

>> I also am in doubt if Dashboard should be apart from the environments or not, will let that as also for discussion.

> I'd add disk capacity to the above NW, Memory and CPU stats.

Gosh, I forgot disk metrics! Gonna edit the post.

> This would be great! Thanks for sharing the information you'd like to see. 

@ibuildthecloud Nice to hear that from you! :)

**Comment by lavvy** [comment]
+1 for this feature. Don't forget Disk metrics please

**Comment by eebjr** [comment]
will there be an API for all of this "global" information...please...

**Comment by will-chan** [comment]
We have done some design of this and will need to implement some backend to support this.

**Comment by demarant** [comment]
+1 indeed see also #2718 and also related to #3362

**Comment by demarant** [comment]
@will-chan Please while implementing this, I would like to see the dashboard give a global summary of all the environments as user I have "read access" to and possibility for a drill-down by environment. For "Admin users" it will make possible to have a global overview and other users with access to multiple environments will have their own overviews. 
I would like to avoid to see a dashboard that only display metrics for a single environment, forcing the user to switch environment several time to get an overview.

**Comment by dkiser** [comment]
+1

**Comment by rvion** [comment]
+1

**Comment by schellkenig** [comment]
+1

**Comment by SInCE** [comment]
:+1: +1

**Comment by unki2aut** [comment]
+1

**Comment by AndreasRudich** [comment]
+1

**Comment by taketnoi** [comment]
+1

**Comment by demarant** [comment]
is there any estimate when the rancher dashboard will see the bright light over the clouds ? I really miss it :smile:

**Comment by MouhamedAymen** [comment]
+1

**Comment by digitalLumberjack** [comment]
Did not see that request yet. That would be awesome !

**Comment by vincent99** [comment]
Some parts of this will be in the 2.0 clusters page.
