### ISSUE TITLE
Cannot select cluster and project  on mobile

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#27183]
Cannot select cluster and project  on mobile

![image](https://user-images.githubusercontent.com/21168270/82530641-5b61cd00-9b70-11ea-95e9-13b2264163d3.png)

**Comment by ChrML** [comment]
This issue is also reported as #25686 (duplicate).

**Comment by DoNotSayYes** [comment]
Cannot redirect by clicking cluster or project on the left hand navigation at the very beginning of entering the page. However, the double click is OK.

**Comment by DoNotSayYes** [comment]
**Reproduced in version:**  `rancher/rancher:v2.4.3`
**Steps:**
1. Add a cluster
2. View rancher on mobile

**Result:**
Navigation functions inappropriately (Cannot select cluster and project).

------

**Verified in version**: `rancher/rancher: v2.4-head` off 29th May
Navigate is functional by selecting a cluster or project on mobile
![image](https://user-images.githubusercontent.com/57614736/83219298-9a140a80-a1a2-11ea-92b3-089aeb8dd9c7.png)

-------

**Verified in version**: `rancher/rancher: master-head` off 29th May
Navigate is functional by selecting a cluster or project on mobile
![image](https://user-images.githubusercontent.com/57614736/83219383-d0518a00-a1a2-11ea-8ddc-66a968196cb1.png)
