### ISSUE TITLE
[Backport 2.3] Fix registry credentials so that it doesn't crash

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27182]
Backport for https://github.com/rancher/rancher/issues/26981

**Comment by DoNotSayYes** [comment]
Reproduced the issue in v2.3.7
1. Create a registry selecting "Available to all namespaces" and save
UI is stuck in saving state and does not complete. 
![image](https://user-images.githubusercontent.com/57614736/82659669-a3a9e980-9c5b-11ea-9da1-cd49e000ccad.png)


Validated in  v2.3-head(`aea3cc0`)
1. Add a registry selecting the scope "Available to all namespaces".
2. Configure Dockerhub/quay/artifactory/custom registry then save
3. Registry gets created as expected without any errors. 
4. Creating a registry in a single namespace also works fine.

**Comment by deniseschannon** [comment]
This was validated with 2.3-head, but was missed in the UI release that was shipped with 2.3.8, so moved to 2.3.9.
