### ISSUE TITLE
[UI Bug] Catalog helm chart with missing field breaks search function

### ISSUE THREAD

**Issue by DH-Rancher** [rancher/rancher#27188]
If a catalog entry contains a helm chart with a missing, non-manatory field in the respective `Chart.yaml`, the search functionality breaks.

To reproduce

* Add https://github.com/janeczku/demo-charts as a Catalog entry in Rancher
* Navigate to a project within a cluster
* Click "Apps"
* Search for a specific chart, ie "Wordpress". The displayed list of charts does not filter based on the search string. Additionally, the following is displayed:

![image](https://user-images.githubusercontent.com/57356014/82576770-fca54f00-9b81-11ea-97b5-a9f280dab6d1.png)

In this example, "Description" from the `Chart.yaml` file is not present but is not a mandatory field. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
|Route|`undefined`|

**Comment by jiaqiluo** [comment]
The bug is reproduced in v2.4.3 with the steps in the issue. 

The bug fix is validated in v2.4-head and master-head with the default UI index.
