### ISSUE TITLE
Controller-manager and scheduler are intermittently 'Unhealthy'

### ISSUE THREAD

**Issue by AprilE-zz** [rancher/rancher#27190]
We are running four clusters. One of the clusters has an intermittent problem where it shows the Controller and Scheduler are 'unhealthy'. It flips back and forth between 'healthy' and 'unhealthy' every 15 minutes or so. It's a production cluster, the applications are running successfully and the individual nodes are healthy.

> kubectl get cs
NAME                 STATUS      MESSAGE                                                                                     ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused   
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused   
etcd-0               Healthy     {"health": "true"}                                                                          
etcd-1               Healthy     {"health": "true"}                                                                          
> 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.8` UI: `v2.2.8` |

**Comment by deniseschannon** [comment]
@AprilE-zz This is most likely based on the type of cluster you are running and whether or not the cluster supports component status. I'm going to close this issue in favor of this other one, which indicates how we'll handle these clusters that don't support component status for certain components. 

https://github.com/rancher/rancher/issues/11496#issuecomment-727641496
