### ISSUE TITLE
UI and API slowness in Rancher v2.4.3

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#27192]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

When using rancher as the admin user on 2.4.3, it is now taking a considerably longer time than in 2.3 due to the UI waiting on `/v3/clusters?limit=-1&sort=name` endpoint on page loads/refreshes. This call can take up to 3 minutes to complete on certain occasions.

The entire cluster list can be queried directly via CRDs in less than 2 seconds.
```
$ time kubectl get cluster -o json > /dev/null
kubectl get cluster -o json > /dev/null 1.17s user 0.08s system 94% cpu 1.315 total
```
But the API call takes more than a minute to complete.
```
$ time curl -fSso /dev/null -u “token-***:***” ‘https:/xxxx.com/v3/clusters?limit=-1&sort=name’
curl -fSso /dev/null -u 0.02s user 0.01s system 0% cpu 1:17.02 total
```

env:
rancher v2.4.3
k8s v1.17.2
3 node control plane, 5 node etcd v3.3.8

gzrancher/rancher#10245

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.4.5**

- On 2.3.8 - Deploy 200 clusters. Load the UI page. UI loads all the clusters in about 1 or 2 seconds. 
- Upgrade to 2.4.5
- Load the UI page. UI loads all the clusters in about 39 seconds.
- time curl -fSso /dev/null -u token-<token> "https://<rancher-server>/v3/clusters" --insecure -- took about `real	0m39.726s`

**Comment by sowmyav27** [comment]
**Verified on 2.4-head -commit id: `beca318de`**

- Deploy 200 empty custom clusters. Load the UI page. UI loads all the clusters in about 39 seconds.
- Upgrade to 2.4-head
- Load the UI page. UI loads all the clusters in about 1.2 seconds.
- time curl -fSso /dev/null -u token- "https:///v3/clusters" --insecure -- took about `real	0m1.272s`
