### ISSUE TITLE
Cluster stuck in provisioning state Cluster must have at least one etcd plane host

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#27198]
**What kind of request is this:**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Install rancher `v2.4-3003-head` commit id: aa7c0629a
- Start provisioning a RKE DO cluster

**Result:**

```
2020/05/21 20:57:39 [ERROR] cluster [c-ww8j9] provisioning: [state] can't fetch legacy cluster state from Kubernetes: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x]

2020/05/21 20:58:17 [ERROR] cluster [c-ww8j9] provisioning: Failed to set up SSH tunneling for host [x.x.x.x]: Can't establish dialer connection: can not build dialer to [c-ww8j9:m-d44cl]

2020/05/21 20:58:17 [ERROR] ClusterController c-ww8j9 [cluster-provisioner-controller] failed with : Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [x.x.x.x]
```

![Screen Shot 2020-05-21 at 2 03 21 PM](https://user-images.githubusercontent.com/27659/82606444-f7d5a080-9b6b-11ea-8b94-e7e961afc75a.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version: `v2.4-3003-head (05/21/2020)` commit id: aa7c0629a
- Installation option: single

**Cluster information**
- Kubernetes version: `v1.17.6-rancher1-1`

**Comment by izaac** [comment]
With the latest build commit id 0d89e64ee of `v2.4-head (05/22/2020)` I'm still experiencing this issue with all k8s versions.

This is a single Rancher install with Rancher's self-signed certificates.

![Screen Shot 2020-05-22 at 8 21 55 AM](https://user-images.githubusercontent.com/27659/82684106-eee5dd00-9c06-11ea-9c13-045095dccc76.png)

**Comment by izaac** [comment]
Self-signed certs installation method is what's having issues, I just did a letsencrypt install and got a cluster up and running in the latest `v2.4-head`

**Comment by izaac** [comment]
Validated this is now working in Rancher version `v2.4-head (05/26/2020)` aae934198
Both single and HA installs with Rancher generated certificates.

I was able to deploy RKE clusters and Custom clusters without issues.
k8s versions used for the clusters:

- v1.18.3-rancher1-1
- v1.17.6-rancher1-1
- v1.16.10-rancher1-1
- v1.15.12-rancher1-2

**Comment by sundayayandele** [comment]
@izaac what did you do to resolve the issue of "
Cluster stuck in provisioning state Cluster must have at least one etcd plane host
"

**Comment by izaac** [comment]
> @izaac what did you do to resolve the issue of "
> 
> Cluster stuck in provisioning state Cluster must have at least one etcd plane host
> 
> "

This was a symptom of invalid certs problem iirc. You can check in the cluster nodes docker container logs if this is the case. I had to reinstall rancher with valid certificates. In the specific scenario of this issue the Rancher self-signed certificates generation had a bug so it required a code change.
