### ISSUE TITLE
Cannot add "Registry Credentials"

### ISSUE THREAD

**Issue by avarabei** [rancher/rancher#27197]
Cannot add "Registry Credentials" in Rancher UI with "Available to all namespaces in this project". The `this.namespace` variable is `null`. Please see on the screenshot:

![image](https://user-images.githubusercontent.com/5284736/82606431-c38bcf80-9bbf-11ea-8e6f-2453b48fd40c.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
|Route|`/registries/add`|

**Comment by sangeethah** [comment]
Duplicate of https://github.com/rancher/rancher/issues/26981
