### ISSUE TITLE
LDAP Connection testing makes the test user admin of the whole Rancher cluster

### ISSUE THREAD

**Issue by pancochea** [rancher/rancher#27206]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug - Security issue

**Steps to reproduce (least amount of steps as possible):**
Link rancher to a LDAP for authentication. 
After validation, using the local admin user, test de authentication (step 3 when editing the LDAP authentication) whit any user in the LDAP.

**Result:**
This user is linked to the **local admin account** and can login with LDAP credentials, thus **becoming admin of that rancher cluster and it's managed clusters**, independently of the permissions that user had in the rancher or LDAP group.

**Other details that may be helpful:**
The user won't appear in the users, as it appears in default admin. Following is the api output of the admin user after reproducing these steps (some details edited and ids modified):
`{

    "actions": {
        "refreshauthprovideraccess": "…/v3/users/user-zui7h?action=refreshauthprovideraccess",
        "setpassword": "…/v3/users/user-zui7h?action=setpassword"
    },
    "annotations": {
        "lifecycle.cattle.io/create.mgmt-auth-users-controller": "true"
    },
    "baseType": "user",
    "conditions": null,
    "created": "2020-04-16T14:41:20Z",
    "createdTS": 1587048080000,
    "creatorId": null,
    "description": "",
    "enabled": true,
    "id": "user-zui7h",
    "labels": {
        "authz.management.cattle.io/bootstrapping": "admin-user",
        "cattle.io/creator": "norman"
    },
    "links": {
        "clusterRoleTemplateBindings": "…/v3/clusterRoleTemplateBindings?userId=user-zui7h",
        "globalRoleBindings": "…/v3/globalRoleBindings?userId=user-zui7h",
        "projectRoleTemplateBindings": "…/v3/projectRoleTemplateBindings?userId=user-zui7h",
        "remove": "…/v3/users/user-zui7h",
        "self": "…/v3/users/user-zui7h",
        "tokens": "…/v3/tokens?userId=user-zui7h",
        "update": "…/v3/users/user-zui7h"
    },
    "me": true,
    "mustChangePassword": false,
    "name": "Default Admin",
    "principalIds": [ 2 items
        "local://user-zui7h",
        "openldap_user://cn="*USERANEM IN LDAP",ou=EDITED,ou=People,dc=EDITED,dc=com"
    ],
    "state": "active",
    "transitioning": "no",
    "transitioningMessage": "",
    "type": "user",
    "username": "admin",
    "uuid": "EDITED-2d1b-41dc-bcc9-EDITED"

}`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Verified in Rancher 2.4.3 and 2.3.5
- Installation option (single install/HA):
HA

**Comment by splattner** [comment]
Same here, saw this multiple times and always wonder why?

is it possible to delete the default Rancher admin afterwards (obviously while having an other administrator account available) and then let the user login again (via LDAP) to create a new user inside Rancher?

**Comment by pancochea** [comment]
Never tried. As Default admin is a local user, I never wanted to remove it. What we did is to assign default admin to the manager... If you do that, and login with the previous user, the user is created as external user as expected.

**Comment by janeczku** [comment]
Closing as pre-duplicate of https://github.com/rancher/rancher/issues/27206 which contains more information on this behavior.
