### ISSUE TITLE
Package Local Copy of Catalog for companies with no internet or unproxied access to internet

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2720]
Ability to package a local copy of catalog into Rancher.

http://forums.rancher.com/t/rancher-server-high-cpu/977

**Comment by will-chan** [comment]
Shouldn't you be able to clone a copy of the Rancher catalog project and hosted it internally with your own git repo?

**Comment by deniseschannon** [comment]
This is already implemented.
