### ISSUE TITLE
[RFE] Include a tool tip reminding users to check for k8s deprications before upgrading to 1.16 and not skip K8s versions

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#27207]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
Upgrade Kubernetes for downstream clusters

**Result:**
The UI allows you to skip k8s versions when upgrading, including 1.15 and 1.16.  I've had several users do this and break workloads as they assumed Rancher was "handling" it.
Kubernetes advises upgrading one version at a time to prevent version skew between different running k8s components and allow for resource migration from one API to another in the case of deprecation.

It would be supremely useful to require users to go one step at a time, with a particular advisory for going from 1.15 to 1.16 to fix deprecated API or some automation to do it for the users.
Hopefully we can automate this? (https://github.com/rancher/rancher/issues/27215)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.6, v2.4.3

**Comment by superseb** [comment]
https://github.com/rancher/rancher/issues/24829 made a note on reviewing the k8s release notes before upgrading.

**Comment by Tejeev** [comment]
@superseb This addresses that user should review the docs, what about when they go to skip versions?
It's also not going to stand out much to the UI user that just goes and changes the version.  I almost feel like it should be red... sooo many people do not read that tooltip.
