### ISSUE TITLE
"Redeploy Rancher Agents is needed for [cluster]" log spam 

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#27218]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Upgrade Rancher from v2.3.2 to v2.3.6 

We are concerned this may relate to memory and load issues as it seems that afterwards, since the container doesn't get updated (because it already is) then somewhere that operation ends in a no-op.
Here follows the analysis from a user:
As you are aware, we went through an upgrade of Rancher from v2.3.2 to v2.3.6 just a few days ago and we've been closely monitoring the situation. One of the nuisances that we noticed is the following lines:

```
rancher-655cb6f56d-nz52k rancher 2020/04/22 19:02:30 [INFO] Redeploy Rancher Agents is needed for c-4pt7k: forceDeploy=false, agent/auth image changed=false, private repo changed=true
rancher-655cb6f56d-nz52k rancher 2020/04/22 19:02:31 [INFO] Redeploy Rancher Agents is needed for c-z5tlz: forceDeploy=false, agent/auth image changed=false, private repo changed=true
rancher-655cb6f56d-nz52k rancher 2020/04/22 19:02:31 [INFO] Redeploy Rancher Agents is needed for c-z5tlz: forceDeploy=false, agent/auth image changed=false, private repo changed=true
rancher-655cb6f56d-nz52k rancher 2020/04/22 19:02:32 [INFO] Redeploy Rancher Agents is needed for c-w9k86: forceDeploy=false, agent/auth image changed=false, private repo changed=true
rancher-655cb6f56d-nz52k rancher 2020/04/22 19:02:32 [INFO] Redeploy Rancher Agents is needed for c-wmv4d: forceDeploy=false, agent/auth image changed=false, private repo changed=true
rancher-655cb6f56d-nz52k rancher 2020/04/22 19:02:33 [INFO] Redeploy Rancher Agents is needed for c-z5tlz: forceDeploy=false, agent/auth image changed=false, private repo changed=true

```

These lines have been showing up by quite a lot (per our Kibana, around 8000 of these logs every 3 hours since the upgrade).
... we started digging through the codebase, since it seems this log line seems to think that the `private repo changed` (it's the only flag set to true). Here's what we found:

To start, we configured a private registry (using the "system-default-registry" rancher setting)

In this file: https://github.com/rancher/rancher/blob/v2.3.6/pkg/controllers/management/clusterdeploy/clusterdeploy.go#L140-L141 -- there's 2 variables created, `desiredRepo` and `appliedRepo`. 
The logic to find `desiredRepo` starts by looking at the Cluster object in the path: `cluster.Status.AppliedSpec.RancherKubernetesEngineConfig.PrivateRegistries` OR by looking at the setting `system-default-registry`.

Since there's no values nor the key itself in the JSON data for `cluster.Status.AppliedSpec.RancherKubernetesEngineConfig.PrivateRegistries`, this returns always a zero-size result back, so the second value is taken, the value of `system-default-registry`, which in our case is set to the registry URL.

`appliedRepo`, on the other hand, comes from the first `cluster.Status.AppliedSpec.RancherKubernetesEngineConfig.PrivateRegistries` item in this list (if there's one) but for the clusters from the example log above, there's none.

At this point, `desiredRepo` is set to our provided registry URL and `appliedRepo` is `nil` because there was none found as stated in the previous paragraph, since there's no values in that JSON key.

After that, there's a few `IF` statements, being the first one the one that finds `appliedRepo`, then another one in the same file in line 145, which is `false` overall so it's skipped, and then it gets to line 148, where you have something like this:

```
desiredRepo := *v3.PrivateRegistry{"$REGISTRY_URL"}
appliedRepo := *v3.PrivateRegistry(nil)

# (FALSE && FALSE) || (TRUE && TRUE)
if (desiredRepo == nil && appliedRepo != nil) || (desiredRepo != nil && appliedRepo == nil) {
repoChange = true
}

```

Since the condition is an OR and the second set evaluates to `true`, the condition is met and the `repoChange` process triggers. Most likely, afterwards, the whole thing ends in nothing because after inspecting the cluster data and the pods running, they are running rancher agents version 2.3.6, deployed at the moment of the update -- so, there's no reason to "redeploy rancher agents" as the log statement suggest.

gzrancher/rancher#9706

**Comment by sangeethah** [comment]
Reopening to get fixes merge to release branch

**Comment by sowmyav27** [comment]
**On 2.4.5**

**Steps:**

- Create a private registry with no auth
- Add the registry as `system-registry-default`
- Bring up a custom cluster in 2.4.5 - 1 node all roles.
- The logs show

```
2020/07/02 19:37:39 [INFO] Redeploy Rancher Agents is needed for c-x8c25: forceDeploy=false, agent/auth image changed=false, private repo changed=true, agent features changed=false
2020-07-02 19:37:39.906409 I | http: TLS handshake error from 127.0.0.1:56054: EOF
2020/07/02 19:37:41 [INFO] Redeploy Rancher Agents is needed for c-x8c25: forceDeploy=false, agent/auth image changed=false, private repo changed=true, agent features changed=false
```
