### ISSUE TITLE
Rancher UI gets unresponsive after upgrading from v2.3.7 to master

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#27227]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install Rancher v2.3.7, single install.
- (May be Optional) Create a node template
- Upgrade to `master-head` 2b6c150da
- Try cloning the node template.

**Result:**

UI seems fine for a minute then it keeps degrading and finally is unresponsive.

Only Error I see in the logs is:

```
E0522 23:50:00.595463       7 reflector.go:178] github.com/rancher/lasso/pkg/cache/cache.go:112: Failed to list *v3.GlobalDNSProvider: no kind "GlobalDnsProviderList" is registered for version "management.cattle.io/v3" in scheme "github.com/rancher/types/config/context.go:68
```

![Screen Shot 2020-05-22 at 4 13 00 PM](https://user-images.githubusercontent.com/27659/82716494-87528080-9c4c-11ea-9e40-8095fb75f4f1.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version: `master-head (05/22/2020)` commit 2b6c150da
- Installation option: single

`2.4-head` works after upgrade, so this is only a `master-head` issue.

**Comment by izaac** [comment]
I tried with rancher generated certificates and byo-self signed.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 8d9cedde9`

Steps:
Deploy Rancher v2.3.7, single install
Create a node template
Upgrade to master-head
Clone the node template

Result:
UI is responsive. Was able to clone node template and deploy clusters.
<img width="913" alt="Screen Shot 2020-08-31 at 10 09 50 AM" src="https://user-images.githubusercontent.com/57409052/91746946-500c3d80-eb72-11ea-83ef-1693b96295cd.png">
<img width="586" alt="Screen Shot 2020-08-31 at 10 10 02 AM" src="https://user-images.githubusercontent.com/57409052/91746942-4edb1080-eb72-11ea-9bd3-1b512dba561c.png">
