### ISSUE TITLE
Authorization with github currently bugged

### ISSUE THREAD

**Issue by hrwebasst** [rancher/rancher#2722]
Steps to reproduce. Install rancher. In my case on port my.example.com:3000

go to access controls, set up github access normally. It will bounce you back to your main welcome page and still has the access control banner at the top and when you try a second time sometimes the popup gives a 404 page other times the second time will actually enable access controls.

**Comment by deniseschannon** [comment]
What version of Rancher are you trying to install? After authenticating, there is a 2 step process (can't remember off the top of my head of what exactly is going on) before you are logged in as the authenticated user.

**Comment by hrwebasst** [comment]
I've done the process quite a few times before, it is two step. I'm running latest v0.46.0

**Comment by deniseschannon** [comment]
@vincent99 Any idea on why this would be happening?

**Comment by hrwebasst** [comment]
This is still happening with v0.47.0. Here are the steps.

1. Be logged into github
2. click the red banner and choose github
3. fill out authorization information
4. It directs you back to the root page of rancher and access control banner is still there
5. click on access control banner and get the following /fail page
![fail](https://cloud.githubusercontent.com/assets/9060082/11542007/2fca98da-98ea-11e5-829e-5ba1ee593f45.png)
6. go back to the root
7. click access banner again
8. get fail page again but after about 10 seconds it will redirect you back to root and finally work

**Comment by deniseschannon** [comment]
@hrwebasst If you are still hitting this issue with our latest versions, please re-open. I have never been able to reproduce or have this issue.
