### ISSUE TITLE
User is unable to add parameter in longhorn storage class

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/rancher#27220]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create storage class with longhorn provisioner.
2. Add a parameter by clicking add label.
<img width="669" alt="Screen Shot 2020-05-22 at 3 05 09 PM" src="https://user-images.githubusercontent.com/60111667/82712821-ce854500-9c3d-11ea-895c-13de6d201ca5.png">

**Result:**
Storage class doesn't get created with added parameter. 
The request doesn't have the added parameter. 
```{"type":"storageClass","provisioner":"driver.longhorn.io","reclaimPolicy":"Delete","allowVolumeExpansion":true,"volumeBindingMode":"Immediate","name":null,"parameters":{"numberOfReplicas":"3","staleReplicaTimeout":"2880"}}```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  rancher-master b85ea695f
- Installation option (single install/HA): Single

**Other details**
There was some fix around it in https://github.com/rancher/rancher/issues/26617

**Comment by codyrancher** [comment]
@maggieliu @khushboo-rancher  even though the parameters look like they're freeform key-values this is actually being intentionally restricted to just the parameters listed here https://github.com/rancher/ui/blob/master/lib/shared/addon/components/storage-class/provisioner-longhorn/component.js#L6-L13 .

Do we want to make the parameters freeform or do we just want to add a few more to the list

**Comment by yasker** [comment]
@codyrancher We can do it with free form while showing a list of known parameters. The reason is Longhorn can add new parameters in the future and it doesn't require the user to use the newer version of UI or Rancher to use it. So it's unnecessary to restrict the user from using only the known parameters to Rancher at this moment.

**Comment by khushboo-rancher** [comment]
Verified on ```master-3049-head``` and ```v2.4-3045-head```

Adding parameter in longhorn storage class is working. 
The request to create storage class:
```
{"type":"storageClass","provisioner":"driver.longhorn.io","reclaimPolicy":"Delete","allowVolumeExpansion":true,"volumeBindingMode":"Immediate","name":"longhorn-class2","parameters":{"numberOfReplicas":"3","staleReplicaTimeout":"2880","fsType":"xfs"}}
```
