### ISSUE TITLE
Upgrade delete service links not saving 

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#2723]
1) upgrade a service
2) delete service link
3) click upgrade

the link will still exist

**Comment by deniseschannon** [comment]
In v0.46.0, I was unable to reproduce, but I am also testing with the new UI. 

Here are some more detailed steps I performed.

Service 1 with link to Service2.
In UI, select Upgrade option to a different image (leaving link in tact). 
Finish Upgrade
Edit service 1 to delete the link to service 2. Save the edit.
In UI, select Upgrade option. Link to service 2 is NOT showing up.

**Comment by alex88** [comment]
Just tried to:

1) upgrade service
2) add link during service upgrade
3) actually upgrade

link not present

**Comment by deniseschannon** [comment]
What rancher version are you running? How are you upgrading (UI or rancher-compose)?

**Comment by alex88** [comment]
Upgrading via UI, rancher 0.46.0

**Comment by deniseschannon** [comment]
I'm on our latest rc (doing testing) and still have been unable to reproduce. 

Link is present after I added during service upgrade. 

Do you have multiple environments? I'm wondering if you are hitting https://github.com/rancher/rancher/issues/1389

**Comment by deniseschannon** [comment]
@alex88 As I have been unable to reproduce (after multiple attempts), I'm going to assume you were hitting #1389 where sometimes links aren't present if you have multiple environments. Closing in favor of that issue.
