### ISSUE TITLE
Issue Firefox+ GitHub Login

### ISSUE THREAD

**Issue by xakraz** [rancher/rancher#27245]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

:shrug: I don't really know, I need help to provide more info.

* I have setup Rancher with GitHub.com authentication
* One day, when login with FireFox I get : `Permission denied to access property "ls" on cross-origin object`

However:
* When using Chromium or Firefox in private mode it works
* I have checked the extension I am using in Firefox none of them are "blockers"
* I have deactivated Firefox built-in protection with no success

**Result:**

![Screenshot_20200525_164320](https://user-images.githubusercontent.com/1590399/82825079-dac20a00-9eaa-11ea-9180-d2a06bf3d749.png)

**Other details that may be helpful:**

**Environment information**

Rancher | v2.3.6
-- | --
User Interface | v2.3.40
Helm | v2.14.3-rancher1
Machine | v0.15.0-rancher34

Firefox: 76.0.1

**Comment by DonnaScriptTechs** [comment]
I'm having an issue with Chrome today for Github authentication. It worked yesterday morning. Version 83.0.4103.61 (Official Build) (64-bit)
I reported it to Github too, just in case. I don't know if these issues are related but figured to comment just in case they are.
![ghissue](https://user-images.githubusercontent.com/6908282/82903338-cc1d3680-9f2e-11ea-9a3b-aeff8525bb67.jpg)

**Comment by xakraz** [comment]
By the way, it is working again today .... :shrimp:

**Comment by DonnaScriptTechs** [comment]
yes, it works in firefox, I just checked. It does not work in chrome. Odd. Hopefully, there's a fix as I like Chrome better. :)

**Comment by DonnaScriptTechs** [comment]
Figured it out and not too happy about it. I have to disable anti-tracking in order for this to work in chrome. :( Why are you requiring tracking to be enabled Rancher?

**Comment by vincent99** [comment]
"We" are not doing anything to "track" you. 

Rancher redirects to GitHub with the application id you've configured.  You sign in on their site and they reflect back to the URL we tell them plus a code.  That along with the application secret configured can then be exchanged on the server-side for an API key.  This is the standard OAuth web flow.

The error page you're showing is on their site.  So whatever you have enabled is breaking GitHub, and likely has nothing to do with Rancher.

**Comment by DonnaScriptTechs** [comment]
Ok thanks for the explanation. I've used this for years without issues and have a ticket in to Github for our organization. Have a good day.
