### ISSUE TITLE
Invalid Repository Name: rocket.chat

### ISSUE THREAD

**Issue by ColtonProvias** [rancher/rancher#2724]
When attempting to set up a service that involves the [official docker distribution of rocket.chat](https://hub.docker.com/_/rocket.chat/), an invalid repository name error is returned as the name of the repository contains a period.

**Comment by deniseschannon** [comment]
Confirmed that it's a bug. I'm able to pull rocket.chat onto my host and still unable to start containers/services with the image name.

**Comment by deniseschannon** [comment]
@hibooboo2 Would you be able to look at how we validate image name for launching a container? The bug is for standalone containers and @alena1108 is just re-using the same validation.

**Comment by hibooboo2** [comment]
Ok Looking now.

**Comment by hibooboo2** [comment]
https://github.com/docker/docker-py/blob/master/docker/auth/auth.py#L46

As you can see from this function docker py is filtering out any repo that contains a `.` in its name.

**Comment by hibooboo2** [comment]
docker/docker-py#860

**Comment by sangeethah** [comment]
Tested with latest build from master:

Able to start a service using image-rocket.chat successfully.There is no error relating to invalid repository name error seen.
