### ISSUE TITLE
--cpu-shares默认值为2，导致无法进行CPU计算

### ISSUE THREAD

**Issue by inewlife** [rancher/rancher#27242]
请假一个问题，rancher上面不管是1.6还是2.X版本，都把创建的容器--cpu-shares这个值默认设置为2，导致在机器cpu有些占用为100%时，rancher创建的容器无法进行cpu计算，这是个bug吗，还是故意为之

**Comment by loganhz** [comment]
If you would like to ask questions in Chinese, please add `rancher3` to join 
Rancher WeChat group. Thanks
