### ISSUE TITLE
Hide server header in reponse

### ISSUE THREAD

**Issue by babytut** [rancher/rancher#27247]
**What kind of request is this (question/bug/enhancement/feature request):**

enhancement
**Steps to reproduce (least amount of steps as possible):**
I want to remove server header reponse: server: openresty/1.15.8.1

**Result:**
set server_tokens off; 
in _nginx-configuration_ but not success.

**Other details that may be helpful:**

**Environment information**
- Rancher version: 2.4.2
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): vm
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
As described on https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#server-tokens, `server-tokens: "false"` needs to be added in the ConfigMap. After it automatically reloads the config, the header is not present in response anymore.
