### ISSUE TITLE
Instal chart from helm catalog

### ISSUE THREAD

**Issue by quadrinho** [rancher/rancher#27255]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
We tried to install ingress chart from helm catalog:

https://kubernetes-charts.storage.googleapis.com/

**Result:**

Error: transport is closing

**Other details that may be helpful:**
We see that the pod seems ok but the status of Apps is "Installing" in red

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Rancher Version --> 2.4.3
Installation option --> both single install and HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
Docker version 19.03.9, build 9d988398e7
```

**Comment by quadrinho** [comment]
Also we see in the docker logs of single install thies error:

NAME:   nginx-ingress
[storage] 2020/05/26 14:03:36 getting last revision of "nginx-ingress"
[storage] 2020/05/26 14:03:36 getting release history for "nginx-ingress"
[kube] 2020/05/26 14:03:36 Doing get for PodDisruptionBudget: "nginx-ingress-default-backend"
[kube] 2020/05/26 14:03:36 Doing get for PodDisruptionBudget: "nginx-ingress-controller"
[kube] 2020/05/26 14:03:36 Doing get for ConfigMap: "nginx-ingress-controller"
[kube] 2020/05/26 14:03:36 Doing get for ServiceAccount: "nginx-ingress"
[kube] 2020/05/26 14:03:36 Doing get for Role: "nginx-ingress"
[kube] 2020/05/26 14:03:36 Doing get for RoleBinding: "nginx-ingress"
[kube] 2020/05/26 14:03:36 Doing get for Service: "nginx-ingress-default-backend"
[kube] 2020/05/26 14:03:36 Doing get for Service: "nginx-ingress-controller"
[kube] 2020/05/26 14:03:36 Doing get for Deployment: "nginx-ingress-default-backend"
[kube] 2020/05/26 14:03:36 Doing get for Deployment: "nginx-ingress-controller"
[kube] 2020/05/26 14:03:36 get relation pod of object: sit/PodDisruptionBudget/nginx-ingress-default-backend
[kube] 2020/05/26 14:03:36 get relation pod of object: sit/PodDisruptionBudget/nginx-ingress-controller
[kube] 2020/05/26 14:03:36 get relation pod of object: sit/ConfigMap/nginx-ingress-controller
[kube] 2020/05/26 14:03:36 get relation pod of object: sit/ServiceAccount/nginx-ingress
[kube] 2020/05/26 14:03:36 get relation pod of object: sit/Role/nginx-ingress
[kube] 2020/05/26 14:03:36 get relation pod of object: sit/RoleBinding/nginx-ingress
[kube] 2020/05/26 14:03:36 get relation pod of object: sit/Service/nginx-ingress-default-backend
[kube] 2020/05/26 14:03:36 get relation pod of object: sit/Service/nginx-ingress-controller
[kube] 2020/05/26 14:03:36 get relation pod of object: sit/Deployment/nginx-ingress-default-backend
**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x154ded3]

goroutine 531 [running]:
k8s.io/helm/pkg/kube.getSelectorFromObject(0x1c91580, 0xc00079e000, 0xc00079e000, 0x0)
        /go/src/k8s.io/helm/pkg/kube/client.go:1002 +0x253
k8s.io/helm/pkg/kube.(*Client).getSelectRelationPod(0xc0000b1ec0, 0xc0001a7490, 0xc00089ef30, 0xc0000ce4a0, 0x15, 0x800000045)
        /go/src/k8s.io/helm/pkg/kube/client.go:1191 +0x195
k8s.io/helm/pkg/kube.(*Client).Get.func2(0xc0001a7490, 0x0, 0x0)
        /go/src/k8s.io/helm/pkg/kube/client.go:430 +0xa5
k8s.io/helm/pkg/kube.batchPerform.func1(0xc00057c060, 0xc000a41e30, 0xc000999f04, 0xc0001a7490)
        /go/src/k8s.io/helm/pkg/kube/client.go:816 +0x30
created by k8s.io/helm/pkg/kube.batchPerform
        /go/src/k8s.io/helm/pkg/kube/client.go:815 +0xb8**
**2020/05/26 14:03:36 [ERROR] AppController p-f7p92/nginx-ingress [helm-controller] failed with : failed to install app nginx-ingress. Error: transport is closing**

The last error is the same that we see in the UI.

Can anyone help me?

Thanks!

Alessio

**Comment by quadrinho** [comment]
Hello,

anyone can help me?

Thanks,

Alessio

**Comment by KuroObi** [comment]
We are seeing the same issue on rancher v2.4.4 too.
