### ISSUE TITLE
[2.4.3] Error: apiVersion 'v2' is not valid. The value must be "v1" : exit status 1 on Helm 3 Catalog

### ISSUE THREAD

**Issue by Lebvanih** [rancher/rancher#27252]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
The version of helm to create the charts in the next steps is:
```
./helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```
1 - Create a new application using helm: `./helm create rancher-v3-issue`. It should directly create a Helm 3, but ensure in the Charts.yaml that apiVersion is set to v2.
2 - Create a new git repository and place that application in it. By default the version is 0.1.0 so the current layout for me was:
```
.
└── charts
    └── rancher-v3-issue
        └── 0.1.0
            ├── charts
            ├── Chart.yaml
            ├── templates
            │   ├── deployment.yaml
            │   ├── _helpers.tpl
            │   ├── hpa.yaml
            │   ├── ingress.yaml
            │   ├── NOTES.txt
            │   ├── serviceaccount.yaml
            │   ├── service.yaml
            │   └── tests
            │       └── test-connection.yaml
            └── values.yaml
```
3 - Add a new catalog in rancher using that git repository. Make sure to select Helmv3. Then deploy the application. No issue should be encountered
4 - Duplicate the 0.1.0 directory into 0.1.1 and edit the Chart.yaml file to reflect the change of value. In my case:
```
.
└── charts
    └── rancher-v3-issue
        ├── 0.1.0
        │   ├── charts
        │   ├── Chart.yaml
        │   ├── templates
        │   │   ├── deployment.yaml
        │   │   ├── _helpers.tpl
        │   │   ├── hpa.yaml
        │   │   ├── ingress.yaml
        │   │   ├── NOTES.txt
        │   │   ├── serviceaccount.yaml
        │   │   ├── service.yaml
        │   │   └── tests
        │   │       └── test-connection.yaml
        │   └── values.yaml
        └── 0.1.1
            ├── charts
            ├── Chart.yaml
            ├── templates
            │   ├── deployment.yaml
            │   ├── _helpers.tpl
            │   ├── hpa.yaml
            │   ├── ingress.yaml
            │   ├── NOTES.txt
            │   ├── serviceaccount.yaml
            │   ├── service.yaml
            │   └── tests
            │       └── test-connection.yaml
            └── values.yaml
```
And the diff:
```
Common subdirectories: 0.1.0/charts and 0.1.1/charts
diff 0.1.0/Chart.yaml 0.1.1/Chart.yaml
18c18
< version: 0.1.0
---
> version: 0.1.1
23c23
< appVersion: 1.16.0
---
> appVersion: 1.16.1
Common subdirectories: 0.1.0/templates and 0.1.1/templates
```
5 - Push the change to git and refresh the catalog
6 - Update the already deployed application to 0.1.1. This should work smoothly as the helmversion is kept during upgrade.
7 - Deploy the application again (fresh one, no upgrade) but select directly 0.1.1 as version. This will fail with the following message:
`Wait helm template failed. Error: apiVersion 'v2' is not valid. The value must be "v1" : exit status 1
`. Looking at the API view for the application, the helmVersion isn't set at all in that case, and it seems that rancher fallback to Helm 2 in that case even if the catalog is set to Helm v3.
8 - Delete the catalog and recreate it. The deployment of the 0.1.1 will work directly using Helm v3

**Other details that may be helpful:**
It can be workaround by using a version that already exist in the catalog at the time of the initial import then upgrade. But this isn't really viable in the long term. Seems similar to https://github.com/rancher/rancher/issues/26407, but we are not in a migration use case here as the catalogue was created after upgrading to 2.4.3

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.4.3
- Installation option (single install/HA): HA

gzrancher/rancher#10141

**Comment by krisko** [comment]
Same here, starting with empty chartmuseum I managed somehow to create helm chart with apiversion v2 which can be deployed. But just increasing version in Chart.yaml and uploading the same chart, results in error message as above: **2020/06/11 13:22:56 [ERROR] AppController p-kpg44/tiddlywiki-dev [helm-controller] failed with : wait helm template failed. Error: apiVersion 'v2' is not valid. The value must be "v1"**

**Comment by iWangJiaxiang** [comment]
Same issue in rancher **2.4.4**

Seems the only the initial version would work correctly

**Comment by fredleger** [comment]
Same issue in rancher 2.4.4. Deleting an re-importing the helm 3 repo seems to fix the issue for now.

This happened when i tried to deploy an app from one Project to another.

**Comment by sra** [comment]
This is happening for us every time using a private repo (Nexus v3) with our charts with v2 api - removing and adding again doesn't seem to make any difference. Rancher 2.4.5, the catalog is global, installing into a project on an EKS cluster

**Comment by jiaqiluo** [comment]
The bug is reproduced in `Rancher:v2.4.5`, the steps are the same as the issue provides. 

the existing app can be upgraded, but deploying a new app with the new chart version fails

![image](https://user-images.githubusercontent.com/6218999/87461256-04ea9b00-c5c3-11ea-82da-498946bef3df.png)

<img width="1442" alt="Screen Shot 2020-07-14 at 11 09 48 AM" src="https://user-images.githubusercontent.com/6218999/87461212-f13f3480-c5c2-11ea-84c1-d25973a41cdf.png">


the bug fix is validated in `Rancher:v2.4-3304-head` and `Rancher:master-3301-head`. Following the same steps, now the app can be deployed successfully.

![image](https://user-images.githubusercontent.com/6218999/87461437-509d4480-c5c3-11ea-97aa-2c8c46c9861d.png)

View the app in API, we can see the helmVersion is set properly 
```
helmVersion": "helm_v3",
```

**Comment by dasMulli** [comment]
@jiaqiluo will upgrading fix existing versions of the chart metadata that was synced by versions affected by this bug?

**Comment by jiaqiluo** [comment]
@dasMulli  I don't think updating will fix the existing app which is in a bad state caused by this bug. You need to redeploy the app.

**Comment by dasMulli** [comment]
thanks, so deploying a new app is enough or worst case removing and re-adding the catalog?

**Comment by jiaqiluo** [comment]
The fix is at the catalog level, so re-adding the catalog will be the ultimate workaround if other means do not work.
