### ISSUE TITLE
Control Plane component in error when importing an existing Kapsule (Scaleway K8s)

### ISSUE THREAD

**Issue by lucj** [rancher/rancher#27259]
**What kind of request is this : question**

Not a Rancher issue, as it seems to be due to upstream Kubernetes

**Steps to reproduce:**

Run Rancher 2.3 and try to import an existing Kubernetes cluster managed by Scaleway (Kapsule)

**Result:**

Control Plane components are shown in error

![EYyRFB9WkAAD5SF](https://user-images.githubusercontent.com/182406/82931911-ea635080-9f87-11ea-811a-ccb031977fa0.jpeg)

**Other details that may be helpful:**

Could this be handled the same way as the following AKS related issue (just a though) ?
https://github.com/rancher/rancher/issues/17344#issuecomment-491023419

**Environment information**

- Rancher version: 2.3.5
- Installation option: single
- Docker version: 19.03

**Comment by superseb** [comment]
This is tracked in https://github.com/rancher/rancher/issues/11496
