### ISSUE TITLE
Convoy - Service with convoy volume driver stuck in "Activating" state since some of the instances are trying to get deployed in host which do not have access to convoy volumes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2725]
Server Build - from master - Nov 18

Set up - 3 hosts
Host1 is not part of the convoy volume driver.
Host2 and Host3  are part of the convoy volume driver storage pool.

Deploy a service with scale 6 using convoy as volume driver.
4 instances of the services got deployed in host2 and host3 as expected.
But 2 other instances get deployed in host1 and are stuck in "starting" state forever.

<img width="326" alt="screen shot 2015-11-18 at 3 59 07 pm" src="https://cloud.githubusercontent.com/assets/4266958/11258367/54d9e744-8e0d-11e5-81a3-613a3d870ac0.png">

<img width="1084" alt="screen shot 2015-11-18 at 3 57 27 pm" src="https://cloud.githubusercontent.com/assets/4266958/11258356/37045f06-8e0d-11e5-9d01-76d01ee96a52.png">

**Comment by sangeethah** [comment]
Tested with latest build from master.

This issue is still reproducible. 

This scenario is specific to the following workflow:
Deploy a service setting "volume driver" field as "myconvoy" and in "volumes" as "name:/dir".
Instances of the service try to get deployed in hosts that do not have access to convoy storage pool  and remain stuck in "starting" state.

**Comment by cjellick** [comment]
Totally fixed this time, I swear.

**Comment by sangeethah** [comment]
Tested with latest build from master - Nov 20

Set up - 3 hosts
Host1 is not part of the convoy volume driver.
Host2 and Host3 are part of the convoy volume driver storage pool.

Deploy a service with scale 6 setting "volume driver" field as "myconvoy" and in "volumes" as "name:/dir" where name is a new volume.

All instances get deployed in Host2 and Host3 wich are part of the convoy volume driver storage pool.
