### ISSUE TITLE
[2.4.2] [Bug] Rancher-logging is not deployed correctly on new cluster creation

### ISSUE THREAD

**Issue by anouarchattouna** [rancher/rancher#27250]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a new cluster using the terraform provider with monitoring and logging (elasticsearch) enabled.

**Result:**
The `cluster-monitoring` & the `rancher-logging` apps do not deploy correctly

Looking in the clusters System Apps :

`rancher-logging` : 
```code
Failed to install app rancher-logging. Error: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: authentication.k8s.io/v1: the server is currently unable to handle the request, authentication.k8s.io/v1beta1: the server is currently unable to handle the request, authorization.k8s.io/v1: the server is currently unable to handle the request, autoscaling/v2beta2: the server is currently unable to handle the request, batch/v1: the server is currently unable to handle the request, certificates.k8s.io/v1beta1: the server is currently unable to handle the request, crd.projectcalico.org/v1: the server is currently unable to handle the request, metrics.k8s.io/v1beta1: the server is currently unable to handle the request, storage.k8s.io/v1: the server is currently unable to handle the request
```
`cluster-monitoring` :
```code
Failed to install app cluster-monitoring. Error: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: authorization.k8s.io/v1beta1: the server is currently unable to handle the request, metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

**Other details that may be helpful:**

**Related issue** https://github.com/rancher/rancher/issues/26440

The workaround is to force upgrade the apps

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): **v2.4.2**
- Installation option (single install/HA): `HA`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): **Custom**
- Machine type (cloud/VM/metal) and specifications (CPU/memory): **VM**
- Kubernetes version (use `kubectl version`): **v1.17.3**

![Screenshot 2020-05-26 at 9 59 15 AM](https://user-images.githubusercontent.com/9251649/82876325-e3612180-9f38-11ea-93d4-77467d03875e.png)
![Screenshot 2020-05-26 at 9 59 31 AM](https://user-images.githubusercontent.com/9251649/82876351-ed832000-9f38-11ea-926b-36d1c132dec4.png)
![Screenshot 2020-05-26 at 9 59 15 AM](https://user-images.githubusercontent.com/9251649/82876368-f2e06a80-9f38-11ea-8f89-a3cf8117810a.png)

**Comment by superseb** [comment]
The related issue is identical and should be fixed in v2.4.3, the status being updated late is handled in https://github.com/rancher/rancher/issues/26692
