### ISSUE TITLE
Additional disk on etcd nodes

### ISSUE THREAD

**Issue by jsbrain** [rancher/rancher#27251]
I'm ignoring the template as this is not a technical question/issue.

I have a rancher cluster with 3 etcd nodes of which 2 also serve as managers.

Those all have 2 CPUs, 2GB RAM and 20GB disk.

The disk somehow is now running full on all of them, that's why I added additional block storage à 10GB to all nodes. I searched on Google and in the issues here for a way to tell rancher/k8s/docker to use the second volume which is mounted at `/mnt/sda` but I cannot find anything at all.

Maybe I'm using the wrong terminology or this is not documented or even just not possible?

Any ideas on how I can achieve/fix this?

**Comment by superseb** [comment]
This is documented at https://rancher.com/docs/rancher/v2.x/en/installation/options/etcd/, but this will not move the data for you.

**Comment by jsbrain** [comment]
This looks promising. Thanks for pointing it out!
