### ISSUE TITLE
[k8s native cluster] Add OpenAPIV3schema to cluster CRD

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#27261]
- [x] Generate openapi schema for all fields on cluster spec
- [x] Generate openapi schema for fields from dynamicSchema and update cluster crd with it
- [x] Test cluster creation works
- [ ] Cluster spec fields ClusterTemplateAnswers.Values and DisplayName have the "required" norman tag, which makes them appear under "required" section on the openapi schema. Check if the required tag can be removed from these fields

Part of https://github.com/rancher/rancher/issues/27260

**Comment by maggieliu** [comment]
Not needed anymore
