### ISSUE TITLE
Update ACK cluster driver

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#27277]
Update k8s version and other options for ACK cluster driver

**Comment by DoNotSayYes** [comment]
Tested in the version of `rancher/rancher:master-head` off 1st June
![image](https://user-images.githubusercontent.com/57614736/83423462-952eaf80-a45d-11ea-9e30-13a34740b41c.png)

![image](https://user-images.githubusercontent.com/57614736/83423715-f787b000-a45d-11ea-9ab2-1892eaaa5a37.png)


Tested in the version of `rancher/rancher:v2.4-head` off 1st June
![image](https://user-images.githubusercontent.com/57614736/83423666-e0e15900-a45d-11ea-9029-899e4d140917.png)

![image](https://user-images.githubusercontent.com/57614736/83423631-d626c400-a45d-11ea-95d4-0404f9f27306.png)
