### ISSUE TITLE
[UI] Can not open Try Dashboard

### ISSUE THREAD

**Issue by hubert-he** [rancher/rancher#27274]
Version: 2.4
Problem: Can not open Try Dashboard feature
log from chrome: 
![image](https://user-images.githubusercontent.com/5668537/82995502-3cfb4600-a036-11ea-9b50-7297ed9aea04.png)

**Comment by hubert-he** [comment]
ui package must be from releases.rancher.com?

**Comment by PmcFizz** [comment]
who  can answer  this question ?
I meet same question  
and i see code
```
    if ( get(this, 'app.environment') === 'development' ) {
      link = `https://localhost:8005/c/${ escape(this.clusterId) }`;
    } else {
      link = `/dashboard/c/${ escape(this.clusterId) }`;
    }
```

who can explain localhost:8005 what mean?

**Comment by vincent99** [comment]
If you're running local rancher/ui for dev then it links to`localhost:8005`, which is where the dev rancher/dashboard would be.  But you're not, so this is not relevant.

CORS should also not be relevant for loading `<script>` tags on the page, they point to third-party domains all the time.  Do you have tweaked `about:config` settings or ad blocker plugins installed?

The new dashboard is hosted on our CDN while it is experimental so that it can be updated outside of the normal Rancher release cycle.  When it becomes a stable feature it will be bundled with the release, like the regular UI, and not require talking to the internet.

**Comment by PmcFizz** [comment]
@vincent99   hello  my leader want to I translate this dashboard page  to chinese ? can you provide a way  do this?  or this is not support it now ?  thank your reply

**Comment by hubert-he** [comment]
> If you're running local rancher/ui for dev then it links to`localhost:8005`, which is where the dev rancher/dashboard would be. But you're not, so this is not relevant.
> 
> CORS should also not be relevant for loading `<script>` tags on the page, they point to third-party domains all the time. Do you have tweaked `about:config` settings or ad blocker plugins installed?
> 
> The new dashboard is hosted on our CDN while it is experimental so that it can be updated outside of the normal Rancher release cycle. When it becomes a stable feature it will be bundled with the release, like the regular UI, and not require talking to the internet.

I git pull release tag that is v2.4.3. So I think that is a bad idea involve this unstable feature into the release package

**Comment by vincent99** [comment]
> want to I translate this dashboard page to chinese ? can you provide a way do this? or this is not support it now ?

Much of the english is still directly written into the templates and not translation keys, but there is a system (largely the same as in rancher/ui) for translations in https://github.com/rancher/dashboard/tree/master/assets/translations .

> I git pull release tag that is v2.4.3. So I think that is a bad idea involve this unstable feature into the release package

We disagree, but there's a feature flag for it and you can turn it off if you don't want it to be available.

**Comment by PmcFizz** [comment]
thank  you  very much . 
finianly  i think this code ```link = `https://localhost:8005/c/${ escape(this.clusterId) }`; ```
this **localhost:8005**  should use environment  haha
