### ISSUE TITLE
Upcoming Breaking Change to Nginx Ingress Controller: Change of UID

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#27287]
There is an upcoming breaking change to the nginx ingress controller for kubernetes.

Starting in 0.27.0 they moved to alpine so the UID changed when deploying nginx ingress. If anyone wants to upgrade nginx controller out of band you need to know this.

https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md#0270

https://github.com/kubernetes/ingress-nginx/issues/4061#issuecomment-596525816

This is likely most important to RKE.

**Comment by superseb** [comment]
Updating NGINX ingress is done in https://github.com/rancher/rancher/issues/26377 and is validated. We don't recommend updating any of the fixed set of images in a release.

**Comment by ekristen** [comment]
Thanks @superseb I needed a newer feature and ran into this, I just opened to ensure the rancher team was aware, and per usual, you were already.
