### ISSUE TITLE
[go-machine-service] Adding driver for Vultr.com

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#2729]
Just noticed that there is now a generic UI for `docker-machine`. Awesome :tada:

I'd like to see support for the **VULTR** driver in `rancher/go-machine-service` and would be more than happy to contribute the necessary code.

https://github.com/janeczku/docker-machine-vultr

The driver provisions instances with RancherOS by default which makes it a great match for the Rancher platform.

I guess the first step would be to push the driver to `rancher/machine`?

Please advise!

/cc @ibuildthecloud

**Comment by ibuildthecloud** [comment]
@janeczku we are in the process of switching to Machine 0.5.0 so I see no reason why we couldn't include this driver.  After we switch to 0.5.0 we will start working on making it possible to register driver plugins through the UI.

@wlan0

**Comment by janeczku** [comment]
@ibuildthecloud 
> After we switch to 0.5.0 we will start working on making it possible to register driver plugins through the UI.

Would this comprise uploading the driver binary through the UI?

**Comment by ibuildthecloud** [comment]
That's the idea, still working out how but on the admin screen you can upload and select which drivers are valid for your deployment

**Comment by will-chan** [comment]
Better support when we complete #2923

**Comment by deniseschannon** [comment]
With the ability for users add in your own machine drivers and customize your own UI for machine drivers, I will close this issue.
