### ISSUE TITLE
Rancher helm chart does not create self-signed certificate

### ISSUE THREAD

**Issue by jmgilman** [rancher/rancher#27297]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Install k3s to a 3-node cluster
* Deploy cert-manager helm chart
* Deploy Rancher helm chart with the default values
* Attempt to connect to Rancher and get invalid certificate errors

Note that in the above case I was following the respective guides in the official Rancher docs.

**Result:**
Traefik is returning the default certificate (*.example.com) which, as expected, causes Chrome to complain. 

**Other details that may be helpful:**
```
$> kubectl logs traefik-758cd5fc85-4rk64 -n kube-system
{"level":"error","msg":"Error configuring TLS for ingress rancher/rancher: secret rancher/tls-rancher-ingress contains the following empty TLS data entries: tls.crt","time":"2020-05-28T04:35:31Z"}
{"level":"error","msg":"Error configuring TLS for ingress rancher/rancher: secret rancher/tls-rancher-ingress contains the following empty TLS data entries: tls.crt","time":"2020-05-28T04:35:33Z"}
{"level":"error","msg":"Error configuring TLS for ingress rancher/rancher: secret rancher/tls-rancher-ingress contains the following empty TLS data entries: tls.crt","time":"2020-05-28T04:35:35Z"}
{"level":"error","msg":"Error configuring TLS for ingress rancher/rancher: secret rancher/tls-rancher-ingress contains the following empty TLS data entries: tls.crt","time":"2020-05-28T04:35:37Z"}
```

```
$> kubectl logs -l app=rancher -n rancher
2020/05/28 04:33:52 [INFO] Adding peer wss://10.42.2.9/v3/connect, 10.42.2.9
2020/05/28 04:33:52 [ERROR] Failed to connect to peer wss://10.42.2.9/v3/connect [local ID=10.42.1.9]: websocket: bad handshake
2020/05/28 04:33:57 [ERROR] Failed to connect to peer wss://10.42.2.9/v3/connect [local ID=10.42.1.9]: websocket: bad handshake
2020/05/28 04:34:00 [INFO] Adding peer wss://10.42.0.12/v3/connect, 10.42.0.12
2020/05/28 04:34:00 [ERROR] Failed to connect to peer wss://10.42.0.12/v3/connect [local ID=10.42.1.9]: websocket: bad handshake
2020/05/28 04:34:02 [ERROR] Failed to connect to peer wss://10.42.2.9/v3/connect [local ID=10.42.1.9]: websocket: bad handshake
2020/05/28 04:34:04 [INFO] Handling backend connection request [10.42.0.12]
2020/05/28 04:34:04 [INFO] Handling backend connection request [10.42.2.9]
```

```
$> kubectl describe secret tls-rancher-ingress -n rancher
Name:         tls-rancher-ingress
Namespace:    rancher
Labels:       <none>
Annotations:  cert-manager.io/certificate-name: tls-rancher-ingress
              cert-manager.io/issuer-kind: Issuer
              cert-manager.io/issuer-name: rancher

Type:  kubernetes.io/tls

Data
====
ca.crt:   0 bytes
tls.crt:  0 bytes
tls.key:  1675 bytes
```

The issue is that Rancher is generating a key but no matching certificate. This causes Traefik to complain as seen above and return the default cert instead of the one that Rancher was supposed to be created. Rancher is also complaining with failed handshakes which is expected when there's no certificate.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3-rc4
- Installation option (single install/HA): default Helm values

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): v1.18.2+k3s1
- Docker version (use `docker version`): N/A

**Comment by jmgilman** [comment]
Additional logs that may be pertinent:

```
$> kubectl logs cert-manager-57869c58f9-j5vlw -n cert-manager
E0528 04:43:02.115214       1 controller.go:131] cert-manager/controller/issuers "msg"="re-queuing item  due to error processing" "error"="secret \"tls-rancher\" not found" "key"="rancher/rancher" 
I0528 04:48:02.116353       1 controller.go:129] cert-manager/controller/issuers "level"=0 "msg"="syncing item" "key"="rancher/rancher" 
E0528 04:48:02.116590       1 pki.go:75] cert-manager/controller/issuers "msg"="failed to retrieve secret" "error"="secret \"tls-rancher\" not found" "related_resource_kind"="Secret" "related_resource_name"="tls-rancher" "related_resource_namespace"="rancher" "resource_kind"="Issuer" "resource_name"="rancher" "resource_namespace"="rancher" 
E0528 04:48:02.116683       1 setup.go:48] cert-manager/controller/issuers/setup "msg"="error getting signing CA TLS certificate" "error"="secret \"tls-rancher\" not found" "resource_kind"="Issuer" "resource_name"="rancher" "resource_namespace"="rancher" 
I0528 04:48:02.116782       1 sync.go:80] cert-manager/controller/issuers "level"=0 "msg"="Error initializing issuer: secret \"tls-rancher\" not found" "resource_kind"="Issuer" "resource_name"="rancher" "resource_namespace"="rancher" 
E0528 04:48:02.116854       1 controller.go:131] cert-manager/controller/issuers "msg"="re-queuing item  due to error processing" "error"="secret \"tls-rancher\" not found" "key"="rancher/rancher"
```

**Comment by jmgilman** [comment]
The easiest work-around this issue, until it's resolved, is to just set the Issuer to self-signed mode. An alternative would be generating your own CA and filling in the `tls-rancher` secret manually, but that seemed like a lot more work.

```bash
$> kubectl edit issuer -n rancher
...
spec:
  selfSigned: {}
...
$> kubectl delete certificate tls-rancher-ingress -n rancher
```

**Comment by kubealex** [comment]
same with nginx, but workaround doesn't work:

2020-06-09T22:46:24.182235349+00:00 stderr F I0609 22:46:24.177954       6 main.go:115] successfully validated configuration, accepting ingress rancher in namespace cattle-system
2020-06-09T22:46:24.231724201+00:00 stderr F W0609 22:46:24.231220       6 backend_ssl.go:46] Error obtaining X.509 certificate: no object matching key "cattle-system/tls-rancher-ingress" in local store
2020-06-09T22:46:24.231724201+00:00 stderr F I0609 22:46:24.231649       6 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"cattle-system", Name:"rancher", UID:"b0862c33-856c-48d9-a73d-ece5852f092a", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"2393", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress cattle-system/rancher
2020-06-09T22:46:25.080108336+00:00 stderr F I0609 22:46:25.079652       6 store.go:421] secret cattle-system/tls-rancher-ingress was added and it is used in ingress annotations. Parsing...
2020-06-09T22:46:25.080108336+00:00 stderr F W0609 22:46:25.079992       6 backend_ssl.go:46] Error obtaining X.509 certificate: unexpected error creating SSL Cert: no certificate PEM data found, make sure certificate content starts with 'BEGIN CERTIFICATE'
2020-06-09T22:46:26.713322729+00:00 stderr F I0609 22:46:26.706704       6 status.go:275] updating Ingress cattle-system/rancher status from [] to [{192.168.200.24 }]
2020-06-09T22:46:26.810323460+00:00 stderr F W0609 22:46:26.809865       6 backend_ssl.go:46] Error obtaining X.509 certificate: unexpected error creating SSL Cert: no certificate PEM data found, make sure certificate content starts with 'BEGIN CERTIFICATE'

**Comment by kubealex** [comment]
Are you using cri-o as runtime?

**Comment by panho66** [comment]
This error happens in RKE 1.1.3 Rancher 2.4.5 ( Kubernetes 1.18.3 )
Error: 
Error: Issuer.certmanager.k8s.io is invalid: metadata.managedFields.fieldsType: Invalid value: "": must be `FieldsV1`

Rollback to RKE 1.1.2 fixed the problem (Kubernete v1.17.6)

Look like related to this
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/247

**Comment by haimari** [comment]
Reinstalled cert-manager and rancher and it works

**Comment by cavepopo** [comment]
FYI : Installed on QEMU over proxmox hypervisor, I had to reboot the VM to get access to the rancher UI (got 404 previously)
