### ISSUE TITLE
Ability to pull from the interface

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2731]
I feel that is important to have a feature per service (and/or also on stack) on UI to pull docker image on targeted hosts.

**Comment by fentas** [comment]
(: I guess this is a duplicate issue for: #1872 and #1044

**Comment by deniseschannon** [comment]
Closing in favor of the image management feature issue. If you have other ideas of image management, please add comments to the issue. 

 https://github.com/rancher/rancher/issues/1277

**Comment by deniseschannon** [comment]
Whoops, please ignore my comment on using #1277, but instead you should refer to #1872.

**Comment by cusspvz** [comment]
Thank you both! :)
