### ISSUE TITLE
CrashLoopBackoff on nginx-ingress-controller

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#27317]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster using RKE and either k8s version `1.13.12-rancher1-1` or `1.14.10-rancher1-0`

**Result:**
After cluster appears active, see nginx-ingress-controller is stuck in Updating state. Logs show:
```
W0528 21:24:23.304871 6 flags.go:221] SSL certificate chain completion is disabled (--enable-ssl-chain-completion=false)

nginx version: openresty/1.15.8.1

W0528 21:24:23.313991 6 client_config.go:541] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.

I0528 21:24:23.314208 6 main.go:183] Creating API client for https://x.x.x.x:443

I0528 21:24:23.339979 6 main.go:227] Running in Kubernetes cluster version v1.13 (v1.13.12) - git (clean) commit a8b52209ee172232b6db7a6e0ce2adc77458829f - platform linux/amd64

I0528 21:24:23.342788 6 main.go:91] Validated ingress-nginx/default-http-backend as the default backend.

F0528 21:24:23.488016 6 ssl.go:379] unexpected error storing fake SSL Cert: could not create PEM certificate file /etc/ingress-controller/ssl/default-fake-certificate.pem: open /etc/ingress-controller/ssl/default-fake-certificate.pem: permission denied
```

**Other details that may be helpful:**
- These failing versions use nginx-ingress-controller tag `nginx-0.25.1-rancher1`
- Deploying a cluster using k8s version v1.15.12-rancher1-1 succeeds, which uses nginx-ingress-controller tag `nginx-0.32.0-rancher1`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.13-rc1
- Installation option (single install/HA): single

**Comment by jiaqiluo** [comment]
The bug still exists on `v2.2.13-rc2`, the same behavior in `1.13.12-rancher1-1` or` 1.14.10-rancher1-0 cluster`

**Comment by sangeethah** [comment]
Tested with v2.2.13-rc3. 
Ingress controller -`rancher/nginx-ingress-controller:nginx-0.25.1-rancher1` comes up successfully for both k8s versiona `1.13.12-rancher1-1`  and `1.14.10-rancher1`
