### ISSUE TITLE
Connection Refused using "latest" Tag for Docker Image

### ISSUE THREAD

**Issue by briandowns** [rancher/rancher#27322]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

With or without `--privileged` flag.

 `docker run --privileged -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:latest` 

**Result:**

```sh
➜  curl -XGET http://127.0.0.1
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused                                                                         
➜   curl -XGET https://127.0.0.1
curl: (7) Failed to connect to 127.0.0.1 port 443: Connection refused
```

**Other details that may be helpful:**

Works when running the above command with a specific image tag: e.g. `v2.4-head`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```

```

- Docker version (use `docker version`):

```
➜   docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by superseb** [comment]
`latest` is not a version own it's own, it's the same as the latest release which is v2.4.3. The version will be logged in the first line of the container startup. If this is indeed v2.4.3, I can't really explain why `latest` won't work and `v2.4.3`. Can you share the full log of the container? And the output of `docker info`?

**Comment by superseb** [comment]
Let me know if this still needs help.

**Comment by tophsic** [comment]
I confirm that ports are not set with `rancher/rancher` image which corresponds to this image https://hub.docker.com/layers/rancher/rancher/latest/images/sha256-09e1bef888ef4e1119eb6aa9a95413c7b0fecc7512700b8546502933a2eaa22b?context=explore. It is the same with `rancher/rancher:v2.5.2-rc5`

```
➜  docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --name rancher rancher/rancher:v2.5.2-rc5
docker pull rancher/rancher:v2.5.2-rc5

8397afd749be981a5de960ef5055c619e2e0f2728b4e3ffe5bbdf48fe94fd32c
v2.5.2-rc5: Pulling from rancher/rancher
Digest: sha256:6192cd2171d31157654d289fea217d0530c3d0f5728c6e08fce6ffae83fb4753
Status: Image is up to date for rancher/rancher:v2.5.2-rc5
docker.io/rancher/rancher:v2.5.2-rc5
➜  docker ps                                                                                           
CONTAINER ID        IMAGE                        COMMAND             CREATED             STATUS                         PORTS               NAMES
8397afd749be        rancher/rancher:v2.5.2-rc5   "entrypoint.sh"     9 seconds ago       Restarting (1) 2 seconds ago                       rancher
```

It’s working for me with `rancher/rancher:v2.4-head`

```
➜  docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --name rancher rancher/rancher:v2.4-head 
8951a963b9e696e86f539269db901147093974228463a8b7f93505b53115effb
➜  docker ps                                                                                          
CONTAINER ID        IMAGE                       COMMAND             CREATED             STATUS              PORTS                                      NAMES
8951a963b9e6        rancher/rancher:v2.4-head   "entrypoint.sh"     9 seconds ago       Up 8 seconds        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   rancher
```

Cluster information

* OSX Catalina 10.15.7
* Docker version 19.03.13, build 4484c46d9d
