### ISSUE TITLE
2020/05/28 04:52:34 [ERROR] Error parsing max age Error parsing auth refresh max age: time: invalid duration s

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#27328]
rancher 2.3.3

docker logs -f rancher 
2020/05/28 02:52:34 [ERROR] Error parsing max age Error parsing auth refresh max age: time: invalid duration s
......
2020/05/28 04:52:34 [ERROR] Error parsing max age Error parsing auth refresh max age: time: invalid duration s
......

This error message appears every 2 hours.  why is this ?

**Comment by lijilina** [comment]
Have you solved it
