### ISSUE TITLE
Can't login with existing Github users after Rancher upgrade

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#27321]
**What kind of request is this:**
Bug

**Steps to reproduce:**

- Install Rancher `v2.4.3`
- Setup Github Auth
 - check the Rancher userattribute store returns <none> for all these fields which are not retrieved yet from the GH scopes. (This is now populated in `v2.4-head`)

```
kubectl get userattribute -o custom-columns='Name:UserName,Email:UserPrincipal.extraInfo.Email,Location:UserPrincipal.extraInfo.Location,Company:UserPrincipal.extraInfo.Company,Username:UserPrincipal.loginName'
Name   Email    Location   Company   Username
       <none>   <none>     <none>    <none>
       <none>   <none>     <none>    <none>
       <none>   <none>     <none>    <none>
       <none>   <none>     <none>    <none>
```

- Add a couple of GH users, you can set the Site Access to any to add more users.
- Upgrade to `v2.4-head` or `master`

**Result:**

After the upgrade the GH user I was using was still functional, but after logging out and clicking in Login with Github returns a 500, and I can't login again with the existing github users.

![Screen Shot 2020-05-28 at 3 30 48 PM](https://user-images.githubusercontent.com/27659/83201429-4d74f480-a0fa-11ea-82a3-6563e916fd10.png)

```
2020/05/28 22:27:43 [ERROR] Github getGithubUser: GET email url https://api.github.com/user/emails received error from github, err: request failed, got status code: 404. Response: {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/users/emails/#list-email-addresses-for-a-user"
}
2020/05/28 22:27:43 [ERROR] API error response 500 for POST /v3-public/githubProviders/github?action=login. Cause: request failed, got status code: 404. Response: {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/users/emails/#list-email-addresses-for-a-user"
}
```

**Other details that may be helpful:**

The userattribute is not updated after upgrade, I think I need to login back to Rancher to get it updated but I can't log back in.

**Environment information**
- Rancher version: `v2.4-head` commit 24c684289
- Installation option: HA

rancher/rancher#27175 
rancher/rancher#27028

**Comment by mrajashree** [comment]
Login through API works immediately after upgrade, but through UI it starts working after 1-2 minutes. Might be something to do with the state param

**Comment by izaac** [comment]
Yes I was able to login after ~2 minutes, but before that I kept getting 500.

**Comment by vincent99** [comment]
`state` has nothing to do with the server-side or any error it's producing or getting back from GitHub.  It's a nonce generated by the UI to ensure on the redirect back to the UI came from a user's actual login intent instead of someone tricking you into clicking a link that would eventually cause you to get logged in.  It has nothing to do with this or any server-side message.

**Comment by westlywright** [comment]
The UI changes were reverted in this [PR](https://github.com/rancher/ui/pull/4028)

**Comment by mrajashree** [comment]
Backend changes reverted in https://github.com/rancher/rancher/pull/27342 and https://github.com/rancher/rancher/pull/27335

**Comment by mrajashree** [comment]
@izaac @sangeethah changes for this enhancement are reverted

**Comment by izaac** [comment]
This is working in Rancher `v2.4-head (06/02/2020)` commit afdea9956 after upgrade I had no issues logging in git GH auth.
