### ISSUE TITLE
[proposal] changing environment variables for service in runtime.

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#2732]
Hey there,
my workflow to change my environment vars now a days is to change my `docker-compose.yml`, which I would anyway, then (the long-winded part) delete my service, in order to recreate it with `rancher-compose` and finally update my load balancers which removed the path to this service.

For me quite an undertaking. I would like to have an easy way to update environment vars like one of these ways

* editing my environment vars within `docker-compose.yml` and run e.g. `rancher-compose update` to resolve the differences.
* updating a service via *Edit* in `rancher/server ui` like the way to connect services to each other.

Both ways should simply set the new config and use them for the next start up or restart of a running container (of the service).

**Comment by deniseschannon** [comment]
Would in-service upgrades work for your use case? 

http://docs.rancher.com/rancher/rancher-compose/upgrading/#in-service-upgrade

Basically, your first request would be to edit the env vars and run a `rancher-compose up --upgrade`. 

Your second request would be to "upgrade" a service. It would launch a new container in place of the existing one with the new config. 

This is available in our latest version v0.46.0 and was introduced in v0.43.1 (though I can't remember when it was introduced in the UI)

**Comment by fentas** [comment]
Yeah I guess this solves it mostly. :+1: 
Thanks.
