### ISSUE TITLE
support of Let's encrypt

### ISSUE THREAD

**Issue by dmzaytsev** [rancher/rancher#2734]
It would be great to add support of the Let's encrypt project https://letsencrypt.org/
as option in the load balancer ssl settings if possible 
public beta will start soon

**Comment by fentas** [comment]
Jup. Would be really nice. :+1: 
As I remember they moved it from 16.11 to 03.12. (public beta)

**Comment by Swatto** [comment]
It would be a very nice feature.

**Comment by blackjid** [comment]
:+1: wow!! It would be awesome

**Comment by blaggacao** [comment]
+1 you read my mind!! :)

**Comment by vincent99** [comment]
http://forums.rancher.com/t/letsencrypt-integration-to-rancher/923/2?u=vincent

> This seems like something that would be best as a rancher-catalog template that interacts in a standalone codebase (probably in Go) with the Let's Encrypt + Rancher APIs, rather than baking support for a very specific niche into Rancher itself (actually Cattle, and in Java).

**Comment by dmzaytsev** [comment]
@vincent99 Let's Encrypt requires access to the web server root(or it can run a standalone webserver) to verify your control over the domain
I think it possible only inside the load balancer because it listens the port

**Comment by Swatto** [comment]
If a rancher-catalog template can interact with an existing LB, it would be possible.
But if it's not the case, we need it part of rancher (since the port 80 and 443 could be already used per machine).

**Comment by blackjid** [comment]
maybe this could work also in tandem with the Route53 service that's already in the catalog. You can use that integration to validate the control of the domain.

**Comment by Swatto** [comment]
I'm not sure that a huge pourcentage of folks use Route53 (I'm not)

**Comment by blaggacao** [comment]
Letsencypt is made by a non for porfit company, so integrating it tightly would only feel like a "soft vendor lockin" - If that is part of the concern anyway...

**Comment by pavankumarkatakam** [comment]
+1

**Comment by ibuildthecloud** [comment]
It is possible to write a component that would run in the environment that would interact with both letsencrypt tool chain and the Rancher API to create and update the certificate.  Rancher would then propagate the certificate to the LB.  I would love to see this happen.

**Comment by blackjid** [comment]
I've been playing with letsencrypt within rancher...

For now I haven't hooked into the rancher API, but I was trying to figure it out the best way to run the letsecrypt client.

What I did was:
- Add the domain I want to get a certificate for to the loadbalancer with hostname routing and add a path to `.well-known`. The target for this entry in the loadbalancer is the letsencrypt service running the official letsencrypt docker image (port 80)
- Run `letsencrypt certonly` in `standalone` mode and using the `80` port with the `--standalone-supported-challenges http-01` argument.

This way the letsencrypt service is able to verify the ownership of the domain.

What I'm not sure how to do is the automation phase based on rancher events...
I will take a look at the external-dns catalog component.

**Comment by dbones** [comment]
:+1:

**Comment by zaubererty** [comment]
Cross posting from the forum:

I'd like to implement a container that runs letsencrypt (https://letsencrypt.org/) to acquire certificates for my domains and renew them automatically.
I have found the rancher API calls to add a certificate and to set a network endpoint (domain / subdomain) but I can't find a way to list all my configured endpoints.
I'm going to implement a letsencrypt plugin for rancher.

Do you have any suggestions for me?

@blackjid great manual workflow

**Comment by blaggacao** [comment]
+1 @ibuildthecloud

**Comment by Ilya-Kuchaev** [comment]
+1

**Comment by pwFoo** [comment]
I would love a Let's Encrypt integration with ssl termination / offloading into the loadbalancer. 

Certificates should be created via Let's Encrypt API or inside a temporary Let's Encrypt client container and then moved to the loadbalancer and offered to download for production use. The Let's Encrypt client shouldn't stay in production environment. 

There is also a github project offering a static website to create Let's Encrypt certificates making requests to the Let's Encrypt API.

It's a open source project:
https://github.com/diafygi/gethttpsforfree/blob/gh-pages/README.md

**Comment by petyunchik** [comment]
+1

**Comment by lavvy** [comment]
+1

**Comment by pwFoo** [comment]
Also found a nice 3MB webserver with integrated lets encryption feature.
Could be used as Webserver and also a proxy / loadbalancer.
Haven't tested it yet...

https://caddyserver.com/

**Comment by demarant** [comment]
+1

**Comment by blaggacao** [comment]
I guess this is an opportunity to earn some karma for capable ones.

@blackjid @zaubererty How is the status? Can you share some code? I'd love to have a look...

I think, as @ibuildthecloud envisioned, if it would be integrated into the environment, something as the following (optional/convenience!) workflow would be possible:
SSL terminate a port on a LB by the simple click on a checkbox, next to entering a domain.

**Comment by cusspvz** [comment]
+1 here :)

**Comment by janeczku** [comment]
Almost there... :wink: :tada: 

![rancher-letsencrypt-catalog](https://cloud.githubusercontent.com/assets/3813921/12709052/1071a95e-c8a8-11e5-99d1-cc130b2ac29c.png)

![rancher-letsencrypt-config](https://cloud.githubusercontent.com/assets/3813921/12709055/138b49f6-c8a8-11e5-94ee-acbf1dd2e95a.png)

**Comment by alena1108** [comment]
@janeczku that is so great!

**Comment by demarant** [comment]
@janeczku wow thank you so much!

**Comment by taketnoi** [comment]
+1

**Comment by CBR09** [comment]
+1 for this

**Comment by vincent99** [comment]
@janeczku https://github.com/rancher/community-catalog will be available as a first-class option in 0.57 or 0.58 if you want to put a PR in when you're done.

**Comment by janeczku** [comment]
@vincent99 Certainly! In the process i realized that the permissions for "environment" or "external-dns" agent roles are not sufficient to create certificates and upgrade load balancers. I wonder if there is something we can do, so one needn't have to manually create an API user and fill out even more credentials in the on-boarding form for the service?

I am talking about these labels:
```YAML
io.rancher.container.create_agent: "true"
io.rancher.container.agent.role: "external-dns"
```

**Comment by pwFoo** [comment]
Great! :)
Is a integration to the Rancher Loadbalancer planned / possible?

**Comment by vincent99** [comment]
@janeczku that should be doable; @alena1108?

**Comment by blaggacao** [comment]
:heart:

**Comment by cusspvz** [comment]
@janeczku AWESOME job!!

**Comment by adamgoose** [comment]
@janeczku I'm also creating a container, that's almost ready to be deployed to the Rancher Community Catalog. You can read about my WIP here: https://github.com/adamgoose/rancher-certificates

**Comment by adamgoose** [comment]
Using the following labels gives the container an API Key that has access to certificates:

```
io.rancher.container.create_agent: "true"
io.rancher.container.agent.role: "environment"
```

**Comment by janeczku** [comment]
@adamgoose Nice, that even gives permissions for updating the load balancers. :yum: :v:

**Comment by adamgoose** [comment]
I've also found that the /v1/certificates endpoint is read-only, so you need to use /v1/projects/{projectId}/certificates

**Comment by seb2411** [comment]
Waiting for this too ^^ .

**Comment by janeczku** [comment]
@seb2411 It's just a matter of https://github.com/rancher/rancher/issues/3556 getting fixed.

**Comment by fprieur** [comment]
:+1:

**Comment by mtrofimm** [comment]
+1

**Comment by digitalLumberjack** [comment]
:+1: so nice to see its on it way :)

**Comment by atonit** [comment]
+1 @janeczku
+1 @adamgoose

**Comment by silviupanaite** [comment]
+1

**Comment by mishak87** [comment]
@silviupanaite You now have reactions in right top corner of message ;-)

**Comment by janeczku** [comment]
[![Let's Encrypt for Rancher](https://raw.githubusercontent.com/janeczku/rancher-letsencrypt/master/hero.png)](https://github.com/janeczku/rancher-letsencrypt)

Let's Encrypt is now available in Rancher's community catalog! Have a nice weekend guys!

**Comment by sebastien-lemarinel** [comment]
Thx ;)

**Comment by seb2411** [comment]
Thx ;)

**Comment by vincent99** [comment]
Thanks @janeczku

**Comment by taketnoi** [comment]
thanks @janeczku

**Comment by omata-metamax** [comment]
Hello,

Just a question, How do I add new **domain names** to the **Common Name** fields after launch the Let's Encrypt Container?

Best Regards.

**Comment by willseward** [comment]
@omata-metamax Just do a stack upgrade and change the environment variables.

**Comment by keyscores** [comment]
@rancherdev I'm glad a community member included this. IMHO, let's encrypt should be included in the HA proxy implementation of rancher. I think it's very low overhead and a free service.

**Comment by omata-metamax** [comment]
@willseward If I configure the instance to generate each cert in it's own directory will be all directories renewed when is needed?

Best regards.

**Comment by willseward** [comment]
@omata-metamax I'm not sure what you mean by individual directories. Each named certificate/key pair are placed in eponymous directories---one per instance because one service can only generate one certificate with multiple SANs. 

However, by updating the SANs on the cert by means of the environment variable, the instance will pick up the difference and update it near expiry.

**Comment by omata-metamax** [comment]
@willseward When configuring the instance there is an environment variable called `CERT_NAME` that will create another directory for that cert. Then I want to know if the cert inside it  name/directory will be upgraded when it near expiry.

**Comment by willseward** [comment]
@omata-metamax Yes. The service can only update one certificate/key pair at a time. I'd clone the stack for each certificate that you need.

**Comment by omata-metamax** [comment]
Thank you very much @willseward

**Comment by willseward** [comment]
@omata-metamax No problem. I'm glad this service exists. 

And I agree with @keyscores . It would be nice to have this integrated by default.

**Comment by pwFoo** [comment]
Let's encrypt support with webroot verification instead of external dns service would be great!

**Comment by mzygmunt** [comment]
Has anyone configured LetsEncrypt with Rancher Kubernetes?

**Comment by 9teen90nine** [comment]
Hi! Is there any way to use this in Kubernetes? It seems that there's no access to community catalog in k8s environments :(
