### ISSUE TITLE
Upgrade ingress-nginx controller to 0.26 or higher

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#27349]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Description**
Current version of Rancher (v2.3.4) uses `rancher/nginx-ingress-controller:nginx-0.25.1-rancher1`.

There's a bug fix in ingress-nginx controller 0.26 for supporting extensions k8s.io/api/extensions/v1beta1 for the admission controller webhook to provide syntax validation to prevent ingress configuration from crashing the ingress controller. The specific commit:
https://github.com/kubernetes/ingress-nginx/pull/4521/commits/3dc8211c469c4313839b45497d951534db220088

**Comment by dnoland1** [comment]
Another possible fix it to use networking v1beta1 instead of extensions v1beta1 for ingress kinds.

**Comment by superseb** [comment]
Upgrade of NGINX ingress to 0.32.0 is done in https://github.com/rancher/rancher/issues/26377

**Comment by dnoland1** [comment]
Thanks @superseb, I'll close this issue since it's pretty much a duplicate of #26377.
