### ISSUE TITLE
2.4.3 (with updated KDM) - CrashLoopBackoff on nginx-ingress-controller

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#27350]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster using RKE and with any k8s version available in v2.4.3 using kdm branch dev-v2.4

**Result:**
After cluster appears active, see nginx-ingress-controller is stuck in Updating state. Logs show:
```
W0528 21:24:23.304871 6 flags.go:221] SSL certificate chain completion is disabled (--enable-ssl-chain-completion=false)

nginx version: openresty/1.15.8.1

W0528 21:24:23.313991 6 client_config.go:541] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.

I0528 21:24:23.314208 6 main.go:183] Creating API client for https://x.x.x.x:443

I0528 21:24:23.339979 6 main.go:227] Running in Kubernetes cluster version v1.17 (v1.17.6) - git (clean) commit a8b52209ee172232b6db7a6e0ce2adc77458829f - platform linux/amd64

I0528 21:24:23.342788 6 main.go:91] Validated ingress-nginx/default-http-backend as the default backend.

F0528 21:24:23.488016 6 ssl.go:379] unexpected error storing fake SSL Cert: could not create PEM certificate file /etc/ingress-controller/ssl/default-fake-certificate.pem: open /etc/ingress-controller/ssl/default-fake-certificate.pem: permission denied
```

**Other details that may be helpful:**
- This fails for nginx-ingress-controller tag `nginx-0.32.0-rancher1`
- Fails for all 3 kubernetes versions shown in rancher ui with all different network providers (flannel, weave, canal, calico)
- Seems same as rancher/rancher#27317 but with different kdm branch

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.3
- Installation option (single install/HA): single

**Comment by sangeethah** [comment]
On fresh install v2.4.4-rc2 , `nginx-ingress-controller` 
comes up successfully without any problems in following K8s clusters with "canal" networking:

1.16.10-rancher2-1
1.15.12-rancher2-2
1.17.6-rancher2-1

**Comment by sangeethah** [comment]
On fresh install v2.4.4-rc2 , `rancher/calico-node:v3.13.4` comes up successfully without any problems in following K8s clusters with "canal" networking:

1.16.10-rancher2-1
1.15.12-rancher2-2
1.17.6-rancher2-1
