### ISSUE TITLE
Rancher v2.3.7 fails to deploy nginx-ingress-controller

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#27352]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy rancher v2.3.7 and change KDM to use branch dev-v2.3
2. Create a cluster using any kubernetes version and any network provider (canal, calico, weave, flannel)

**Result:**
nginx-ingress-controller fails to deploy

**Other details that may be helpful:**
- Deploying a cluster before changing the KDM, and then upgrading it after changing KDM branch will initially deploy nginx-ingress-controller image: `rancher/nginx-ingress-controller:nginx-0.25.1-rancher1`. Upon doing the upgrade, it will not attempt to deploy the expected new image at all: `rancher/nginx-ingress-controller:nginx-0.32.0-rancher1`

Screenshot below shows all images deployed from fresh install scenario:
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/55997940/83316758-acab3580-a1dc-11ea-9c0d-80d448e0960e.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.7
- Installation option (single install/HA): single

**Comment by sangeethah** [comment]
Works with latest templates from  `dev-v2.3` branch.

Deploy rancher v2.3.7 and change KDM to use branch `dev-v2.3`.
Create clusters using all kubernetes version and all network provider (canal, calico, weave, flannel)
nginx-ingress-controller deploys successfully.

**Comment by rancher-max** [comment]
#### Validated with v2.3.8-rc3

Deploy rancher v2.3.8-rc3
Create clusters using all k8s versions and network providers
nginx-ingress-controller deploys successfully
