### ISSUE TITLE
Pods in nginx-ingress-controller do not use new image after upgrading Rancher

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#27354]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.2.12 single install 
- add a cluster with k8s `v1.15.11-rancher1-0` 
- upgrade Rancher to v2.2.13-rc2
- Upgrade k8s version from `v1.15.11-rancher1-0` to `v1.15.12-rancher1-1`

**Result:**
- the workload `nginx-ingress-controller` show image `rancher/nginx-ingress-controller:nginx-0.32.0-rancher1` is used, but none of the pods are using the new image, they all the old pods with the old image `rancher/nginx-ingress-controller:nginx-0.25.1-rancher1`

![image](https://user-images.githubusercontent.com/6218999/83317808-6eb20f80-a1e4-11ea-80b4-f970b47e312f.png)

**Other details that may be helpful:**
this happens to all k8s ``v1.15.12-rancher1-1`  cluster with all 4 CNI plugins.

**Comment by sangeethah** [comment]
This issue still exists when testing with `v2.2.13-rc3`

**Comment by jiaqiluo** [comment]
The bug fix is validated in v2.2.13-rc4 upgraded from v2.2.12

The steps are the same as the issue provides, now we see the pods are created to use the new image after upgrading the k8s version 

<img width="1322" alt="Screen Shot 2020-05-30 at 5 51 49 PM" src="https://user-images.githubusercontent.com/6218999/83341972-4a1a6e00-a29e-11ea-9f1d-78efaaf5634c.png">

**Comment by jiaqiluo** [comment]
The bug fix is validated in `v2.4.4-rc3` upgraded from `v2.2.12`

steps:

- run Rancher `v2.2.12` single install
- add a cluster with k8s `v1.15.11-rancher1-0`
- upgrade Rancher to `v2.4.4-rc3`
- Upgrade k8s version from `v1.15.11-rancher1-0` to `v1.16.10-rancher2-1`

Results:
-  the pods are created to use the new image `rancher/nginx-ingress-controller:nginx-0.32.0-rancher1`  after upgrading the k8s version
