### ISSUE TITLE
Host CPU utilization graph is wrong

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#2736]
I've spun up a 16 core system. The CPU utilization graph is showing 1600% as the ceiling which makes sense at first glance. The problem is that the actual plotted value is the system's total utilization. 

Rancher is showing 70/1600% utilization. However the machine is only 30% idle.

**Comment by gordontyler** [comment]
I just noticed something similar myself. The CPU utilization measurement that its graphing appears to be on a 0-100% range, but the graph is rendered with Nx100% as the upper bound, where N is the number of CPUs/cores.

**Comment by vincent99** [comment]
These are fixed in the next release... https://github.com/rancher/ui/commit/293683826cdb78805bcf6cec2eee4a39246b8a75

**Comment by tfiduccia** [comment]
version - master jan 07
Verified fixed
