### ISSUE TITLE
Rancher 2.4.2 - Windows Cluster using flannel host-gw not working 

### ISSUE THREAD

**Issue by AMoghrabi** [rancher/rancher#27367]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a Windows Cluster using flannel / host-gw

**Result:**
The pod `cattle-node-agent-windows` continuously crashes:

```
WARN: Default docker named pipe is not found
WARN: Please bind mount in the docker named pipe to //./pipe/docker_engine if docker errors occur
WARN: example: docker run -v //./pipe/custom_docker_named_pipe://./pipe/docker_engine ...
FATA: https://rancher.xxx.com is not accessible
```

**Other details that may be helpful:**
exec'ing into the pod prior to it crashing and trying to use `curl` results in timeouts for all addresses. `curl` from the kubelet and/or other pods works fine.

Setting up a cluster using flannel / vxlan works perfectly fine.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Bare metal, 2 CPU cores, 8 GB RAM
- Kubernetes version (use `kubectl version`):

```
(Switched to 1.15.11 to see if it'll work on that version. Have also tried 1.16.9)

lient Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
(This is on the windows node)

Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by AMoghrabi** [comment]
The pod that Kubernetes spins up for cattle-node-agent-windows has no connectivity. I've spent days trying to debug it but no luck. 

I'll often see these errors in the kubelet log but they eventually go away. I assume it's just the containers initializing:

```
E0531 20:39:43.456604   12776 reflector.go:282] object-"cattle-system"/"cattle-credentials-87e7ee1": Failed to watch *v1.Secret: Get https://127.0.0.1:6443/api/v1/namespaces/cattle-system/secrets?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dcattle-credentials-87e7ee1&resourceVersion=282036&timeout=8m17s&timeoutSeconds=497&watch=true: read tcp 127.0.0.1:62854->127.0.0.1:6443: wsarecv: An existing connection was forcibly closed by the remote host.
```

```
E0531 20:39:38.079356   12776 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to set up sandbox container "0b71dfad559d53692c702699bbb99dc6913f2cf8c43bd635f88a1c3d6b825b21" network for pod "cattle-node-agent-windows-x7qlr": networkPlugin cni failed to set up pod "cattle-node-agent-windows-x7qlr_cattle-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.
```

☝️  I have verified the subnet.env exists on the windows node.

```
E0531 20:41:04.116347   12776 eviction_manager.go:246] eviction manager: failed to get summary stats: failed to list pod stats: failed to list all container stats: rpc error: code = Unknown desc = hcsshim::OpenComputeSystem 8c49413c26ee999a4f5969c634a8b8144682b224eeb0e8df5b076464281f8bc3: A virtual machine or container with the specified identifier does not exist.
```

**Comment by AMoghrabi** [comment]
@brianharwell if you have any tips that would be greatly appreciated. We briefly spoke about this issue in your ticket: https://github.com/rancher/rancher/issues/27331

**Comment by brianharwell** [comment]
Check out https://stackoverflow.com/questions/60708270/how-can-i-use-flannel-without-disabing-firewalld-kubernetes

The fix for us was `firewall-cmd --add-masquerade --permanent`

**Comment by AMoghrabi** [comment]
Thanks Brian! Unfortunately I'm a little weak in this area, forgive me if this is obvious. 

My master nodes currently do not have firewall running so I'm not sure if that is applicable to me:

```
[ali.moghrabi@xxx ~]$ firewall-cmd --state
not running
```

I don't see Windows Defender firewall running on the windows host either but I'll give that a double check.

**Comment by brianharwell** [comment]
Ok my bad, we had that issue with the linux nodes.

Are all of your nodes on the same subnet? The downside with L2Bridge mode is that all of the nodes need to be on the same L2 network. If they are not then you need to configure custom routing rules.

**Comment by AMoghrabi** [comment]
Not a problem Brian, appreciate any advice :) 

Yep all nodes are on the same subnet. I'm wondering if this is a problem with the rancher-win service, as I see this in the logs of several components that it fails to hit port `6543` on localhost, which is odd. The problem with most of these errors that I see is they go away the longer the containers run. 

Thanks again!

**Comment by AMoghrabi** [comment]
Hey @brianharwell , whenever you have a minute, could you run `Get-HnsNetwork` on your windows node and tell me how many there are? On my host I see two, one called `nat` and the other `crb0`. I'm wondering if there is a third called `External`.

Thanks!

**Comment by brianharwell** [comment]
`Get-HnsNetwork | Select-Object -Property Name`
```
Name
----
cbr0
nat
```

**Comment by AMoghrabi** [comment]
Thanks!

**Comment by gianghn** [comment]
Hi @AMoghrabi 

Have you been able to troubleshoot this problem? I'm having a similar problem using Flannel/VXLan, my setup using Windows HOst on VMWARE.

Best,

Giang

**Comment by AMoghrabi** [comment]
Hey @gianghn , unfortunately I wasn't able to completely solve the problem. We moved back to using kubeadm because you literally cannot get very far without purchasing rancher support. Other reason is because we realized that this only gets you a windows-only cluster. Rancher sort of blocks you from running Linux workloads. 

Anyways have you tried vxlan and host-gw? It should work out of the box using vxlan. Host-gw is a different story which I can go into more detail tomorrow if vxlan isn't an option. 

For vxlan: 
- are all of your nodes on the same VLAN? It isn't required but simplifies things.
- what version of Windows are you running? What revision number? I forget the exact revision but you need to have  recent updates.

Anyways I'm heading to bed but I can help troubleshoot some more tomorrow. Good luck

**Comment by AMoghrabi** [comment]
Oh and one other thing is to check your vmware tools version. I think v10 is broken, upgrading to v11 works. We don't use VMware but I read that advice somewhere when I was troubleshooting

**Comment by brianharwell** [comment]
> Other reason is because we realized that this only gets you a windows-only cluster. Rancher sort of blocks you from running Linux workloads.

This is not true. Rancher adds taints to the Linux nodes. So in order to run Linux workloads you need to add tolerations and affinity rules.

**Comment by AMoghrabi** [comment]
@brianharwell it is stated in the documentation: 

> You can use a mix of Linux and Windows hosts as your cluster nodes. **Windows nodes can only be used for deploying workloads, while Linux nodes are required for cluster management.**

https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/


It is also stated by a rancher employee: 

https://forums.rancher.com/t/mixed-linux-windows-workers/15699/9

> The Linux machines in a Windows cluster are required to run etcd and various other system services (for which no Windows build exists). Otherwise from the user perspective we treat it as a “Windows-only” cluster.

So yes, while you can use taints to bypass it, you are not meant to do that.

**Comment by brianharwell** [comment]
> It is also stated by a rancher employee:
> 
> https://forums.rancher.com/t/mixed-linux-windows-workers/15699/9
> 
> > The Linux machines in a Windows cluster are required to run etcd and various other system services (for which no Windows build exists). Otherwise from the user perspective we treat it as a “Windows-only” cluster.
> 
> So yes, while you can use tolerstions to bypass it, you are not meant to do that.

This sounds ridiculous. There is no response as to why this is any my company is not planning on following this.

**Comment by AMoghrabi** [comment]
Yeah I'm in agreement with you. Do you have a Rancher support plan and will follow up on that, or are you going to steer in a different direction and move off of Rancher?

**Comment by brianharwell** [comment]
We are going to purchase support before we get to prod

**Comment by brianharwell** [comment]
We are going to use Rancher to manage and support our clusters

**Comment by gianghn** [comment]
It seems that we have some problem with our trunking and LACP setting with our network. When we moved to a brand new cluster of machine, newer switch and servers, we set up LACP and trunking from server to switch. Host-gw with windows start working. 

I need to inspect further to have more information.

**Comment by maxisam** [comment]
I have exactly the same issue with Rancher 2.4.8. 
I am using windows 1809. I am going to give 1903 a try tomorrow. 

It is odd that my Get-HNSNetwork returns nothing.

**Comment by brianharwell** [comment]
The issue is most likely a Windows update. That is what I found. Everything was working until the latest Windows updates were applied. Then the Windows agent started crashing. Uninstalling the Windows update fixed the issue.

Here are two that are applying the same "fix" but end up breaking connectivity...

https://support.microsoft.com/en-us/help/4571748/windows-10-update-kb4571748
https://support.microsoft.com/en-us/help/4570333/windows-10-update-kb4570333

**Comment by maxisam** [comment]
@brianharwell Thanks for the tip. Just curious, do you guys use Rancher for windows cluster now? Is everything running smoothly? 

Could you share which windows build version you use? 

Mine is 17763.1457 under vmware with vmware tool v10.1.15. 

I also heard vmware tool v10 has a weird issue that would restart a container every 15 minutes but my issue seems like nothing to do that that behavior.

**Comment by brianharwell** [comment]
@maxisam We are close. We have 3 clusters stood up and are planning to do a load test over the next week or two to prove out that Kubernetes and Windows containers can handle our load.

We are running 1809 in all our clusters. 

17763.1457 is the cluster is broken due to the Windows update.
17763.1282 is the cluster that is working.

VM Ware Tools v11.1.0

**Comment by brianharwell** [comment]
This Windows update broke docker. 

https://github.com/moby/moby/issues/40998#issuecomment-634682203

**Comment by maxisam** [comment]
finally it works. Here is the config I used 

vmware iso. 1809 build 17763.1397
VMWare Tool 11.1.0 and 
only install docker. (no hyper-v) 

```ps1
Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
Install-Package -Name docker -ProviderName DockerMsftProvider -Force
Restart-Computer –Force
```
And use flannel/host-gw for network.

Thanks guys!

**Comment by maxisam** [comment]
ah... spoke too soon. The agent pod in Windows nodes keeps restarting just like @AMoghrabi has.


```
WARN: Default docker named pipe is not found
WARN: Please bind mount in the docker named pipe to //./pipe/docker_engine if docker errors occur
WARN: example: docker run -v //./pipe/custom_docker_named_pipe://./pipe/docker_engine ...
FATA: https://rancher.xxx.com is not accessible
```

**Comment by AMoghrabi** [comment]
@maxisam what I've discovered is that it will work if your master nodes are on a different VLAN. Can't tell you why though.

**Comment by brianharwell** [comment]
> @maxisam what I've discovered is that it will work if your master nodes are on a different VLAN. Can't tell you why though.

If you are using l2bridge that should **not** work at all unless you manual set up the routes.

**Comment by brianharwell** [comment]
@maxisam and @AMoghrabi What do the logs for the cattle cluster agent show?

**Comment by maxisam** [comment]
@brianharwell  Well, I have rebuilt it with vxlan, so I don't have the log now. And vxlan does work. And i don't have firewall on my linux node.

**Comment by maxisam** [comment]
![image](https://user-images.githubusercontent.com/456807/93958439-1dda9f80-fd1c-11ea-8624-bc3c6df1a806.png)

So I install some updates.  The build number is 17763.1457 now and it is working.  Not sure why...

**Comment by nathangiuliani** [comment]
We encountered this problem too. It was confusing, because my personal lab running Hyper-V was fine, but our main VMware setup had this problem.

The fix was to upgrade VMware Tools to get around this bug https://kb.vmware.com/s/article/78550. I believe a downgrade to an earlier version without this 'feature' would also work.
