### ISSUE TITLE
UI: Enable CIS 1.5 profiles for CIS Scan tool

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#27374]
This is the UI ticket corresponding to https://github.com/rancher/rancher/issues/24987

We need to enable in the UI the CIS permissive and hardened profiles for CIS 1.5

**Comment by sowmyav27** [comment]
Shouldn't this https://github.com/rancher/rancher/issues/25888 have covered this issue already ?

**Comment by sowmyav27** [comment]
**Verified on 2.4-head commit id: `2d58a3fcd` and master-head commit id: `f7e83e3e4`**

- Default CIS scan version run on a k8s 1.18 cluster is CIS 1.5 when done through View In API --> runSecurityScan
- On the UI, default scan version available is RKE CIS 1.5 for a k8s 1.18 cluster
- Upgrade cases have been tested as part of other issues - https://github.com/rancher/rancher/issues/27867 and https://github.com/rancher/rancher/issues/27866
