### ISSUE TITLE
[BUG] CLI values ignored by Helm

### ISSUE THREAD

**Issue by marcusianlevine** [rancher/rancher#27376]
**What kind of request is this:**

**_BUG_**

After upgrading from Rancher CLI v2.2.0 to Rancher CLI v2.4.3, our apps that use a `values.yaml` file no longer deploy properly

It seems that the Rancher API is being updated properly (the values show up in the UI and API) but when Helm deploys the templated resources, they appear as if the values were not actually applied

**Steps to reproduce (least amount of steps as possible):**
Deploy an app using `--values` and Rancher CLI v2.4.3

**Result:**
Note that the default values are used. If answers were previously provided via the UI or from an older CLI version, they are not updated to the values specified.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.7
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AWS EC2
- Kubernetes version (use `kubectl version`): 1.16.9
- Docker version (use `docker version`): 19.3.4

gzrancher/rancher#10352

**Comment by Minizinger** [comment]
I just found this bug myself, seems that using `--answers` flag instead works, but it's really counter-intuitive

**Comment by crazycreak** [comment]
We have the same problem, updated from rancher 2.3 (cli 2.3.2) to rancher 2.4.4 (cli 2.4.3) and our deployment via rancher cli is not working anymore. The cli asks for an answer although the value is set in the provided valuse.yaml (with --values)

**Comment by jiaqiluo** [comment]
the `--values` option works in Rancher CLI v2.3.2
```
➜   ./rancher -v
rancher version v2.3.2

➜  ./rancher apps install --values ./wp-values.yaml wordpress --version 9.0.3 --no-prompt
run "app show-notes a-4d6wd" to view app notes once app is ready

```

but it is broken in Rancher CLI v2.4.5, you can see it still asks for values.
```
➜   ./rancher-245 -v
rancher version v2.4.5

➜   ./rancher-245 apps install --values ./wp-values.yaml wordpress --version 9.0.3 --no-prompt

Description: Use default Docker image
Name: Use Default Image
Variable Name: defaultImage
Default:[true]
Enter answer or 'return' for default:^C
```

**Comment by rancher-max** [comment]
This works in cli v2.4.5 when we pass ALL the options either before or after the template. i.e:
```
# After:
./rancher apps install wordpress --version 9.0.3 --no-prompt --values ./wp-values.yaml

# Before:
./rancher apps install --version 9.0.3 --no-prompt --values ./wp-values.yaml wordpress
```

**Comment by jiaqiluo** [comment]
The bugfix is validated in CLI `v2.4.6-rc1`

```
>  ./rancher -v
rancher version v2.4.6-rc1
```

```
> ./rancher apps install --values ./values.yaml wordpress --version 9.0.3 --no-prompt
run "app show-notes a-ddrbq" to view app notes once app is ready
```

And then we can see the deployed app in Rancher UI. 

A new bug is found during validating this issue: https://github.com/rancher/rancher/issues/27841
