### ISSUE TITLE
Convert OPA to use cloud native packaging

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27378]
For 2.5 we need to package OPA following the cloud native packaging process

**Comment by izaac** [comment]
from Prachi:

> We should validate install/uninstall and also the create constrainttemplates/constraints and that the constraints applied work.

From Steven:

> We should validate that rancher-gatekeeper installs/uninstalls rancher-gatekeeper-crd, and the CRDs are cleaned up on uninstall.

Uninstall is blocked by #28097

**Comment by izaac** [comment]
Dashboard issues:

https://github.com/rancher/dashboard/issues/1016
https://github.com/rancher/dashboard/issues/1011

**Comment by aaronRancher** [comment]
Currently blocked by:
https://github.com/rancher/dashboard/issues/1145

Additional Dashboard issues:
https://github.com/rancher/dashboard/issues/1136
https://github.com/rancher/dashboard/issues/1104
https://github.com/rancher/dashboard/issues/1100
https://github.com/rancher/dashboard/issues/1099

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 76c26fb`. OPA is functionally available.
OPA Gatekeeper Version `rancher-gatekeeper:v3.1.0-rc.1`

Logged bugs to be tracked separately:
https://github.com/rancher/dashboard/issues/1194
https://github.com/rancher/dashboard/issues/1200
