### ISSUE TITLE
Missing Azure UAE regions from node template list

### ISSUE THREAD

**Issue by IanMoroney** [rancher/rancher#27370]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement request

**Steps to reproduce (least amount of steps as possible):**
Go to: /g/clusters/add/launch/azure
Open dropdown for "Region"

**Result:**
UAE Regions missing

I am creating a PR to correct this.

**Comment by soumyalj** [comment]
Observed in v2.4.3 that UAE regions are missing in azure node template

![Screen Shot 2020-06-02 at 3 39 05 PM](https://user-images.githubusercontent.com/18536626/83576931-bfc54a80-a4e7-11ea-8ff7-0114bd2c0bf7.png)

Validated with v2.4-head(afdea9956) and master-head(0ab59f95e). UAE regions are populated in the azure node template. UAE Central and UAED North regions are added. 

![Screen Shot 2020-06-02 at 3 45 20 PM](https://user-images.githubusercontent.com/18536626/83577078-20548780-a4e8-11ea-8d2e-e03221c09d24.png)
