### ISSUE TITLE
Disable auto creation of cluster rolebinding

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#27380]
**What kind of request is this:** question/enhancement/feature request
A cluster rolebinding is created automatically when psp is enabled and a service account is created.

Can this be disabled somehow? Usually we have cluster role and cluster role binding created when a chart is deployed, so the auto creation of cluster role binding  is not required.

**Steps to reproduce (least amount of steps as possible):**
Enabled PSP and create a service account

**Result:**
A cluster rolebinding is created automatically when psp is enabled and a service account is created

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.16.6

**Comment by Purneau** [comment]
We consider this a feature on our end :)

**Comment by jessievar** [comment]
> We consider this a feature on our end :)

It is :) and useful when PSP is enabled but a cluster rolebinding is not created by the helm chart.

But would be nice if the user can choose if they want to create the default cluster rolebinding.

Also the feature kind of allows any service account to run pods with binding the service account automatically to a clusterrole that has access to "use" a default(restricted or unrestricted) PSP.

**Comment by Purneau** [comment]
I agree, also the reason why I created #27275 last week. Let's see

**Comment by jessielincatalyst** [comment]
@jessievar

**Comment by jessielincatalyst** [comment]
@jessievar

**Comment by jessielincatalyst** [comment]
@jessievar @jessievar

**Comment by jessielincatalyst** [comment]
@jessievar DOMINOS

**Comment by jessielincatalyst** [comment]
@jessievar

**Comment by jessielincatalyst** [comment]
@jessievar 

What kind of request is this: question/enhancement/feature request
A cluster rolebinding is created automatically when psp is enabled and a service account is created.

Can this be disabled somehow? Usually we have cluster role and cluster role binding created when a chart is deployed, so the auto creation of cluster role binding is not required.

Steps to reproduce (least amount of steps as possible):
Enabled PSP and create a service account

Result:
A cluster rolebinding is created automatically when psp is enabled and a service account is created

Other details that may be helpful:

Environment information

    Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): 2.3.3
    Installation option (single install/HA): HA

Cluster information

    Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
    Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
    Kubernetes version (use kubectl version): 1.16.6

**Comment by jessielincatalyst** [comment]
@jessievar

**Comment by yuconglinvar** [comment]
@jessievar

**Comment by yuconglinvar** [comment]
@jessievar Jessie Lin

**Comment by yuconglinvar** [comment]
@etc-eng Jessie Lin

**Comment by yucong-lin** [comment]
@etc-eng JESSIE LIN

**Comment by yucong-lin** [comment]
@etc-eng JESSIE LIN

**Comment by yucong-lin** [comment]
@etc-eng Jessie Lin

**Comment by yucong-lin** [comment]
@etc-eng JESSIE LIN

**Comment by yucong-lin** [comment]
@etc-eng YOU HAVE SMALL TITS
