### ISSUE TITLE
Rancher+k3s HA  traefik show logs  Endpoints not available for cattle-system/rancher

### ISSUE THREAD

**Issue by szsuyuji** [rancher/rancher#27392]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**

1、install k3s master to two nodes    k3s version :v1.18.2+k3s1

2、install rancher  version v2.4.3

my  tls is a public ca cetificate   with host rancher.szsuyuji.com 

kube-system     metrics-server-7566d596c8-pbd68          1/1     Running     0          40m
kube-system     local-path-provisioner-6d59f47c7-vzphn   1/1     Running     0          40m
kube-system     helm-install-traefik-qbwzr               0/1     Completed   0          40m
kube-system     coredns-8655855d6-7x4dd                  1/1     Running     0          40m
kube-system     svclb-traefik-dg464                      2/2     Running     0          39m
kube-system     svclb-traefik-8k2ql                      2/2     Running     0          39m
kube-system     traefik-758cd5fc85-pqdlm                 1/1     Running     0          39m
cattle-system   rancher-7dc864d7fc-l644m                 1/1     Running     0          36m
cattle-system   rancher-7dc864d7fc-fwztq                 1/1     Running     0          36m
cattle-system   rancher-7dc864d7fc-fsv4p                 1/1     Running     0          36m

evering thing is running  

**Result:**
Rancher UI 404 

**Other details that may be helpful:**

### traefik logs show 

{"level":"warning","msg":"**Endpoints not available for cattle-system/rancher**","time":"2020-06-02T05:16:30Z"}
{"level":"warning","msg":"**Endpoints not available for cattle-system/rancher**","time":"2020-06-02T05:16:31Z"}
{"level":"info","msg":"Server configuration reloaded on :443","time":"2020-06-02T05:16:54Z"}
{"level":"info","msg":"Server configuration reloaded on :9100","time":"2020-06-02T05:16:54Z"}

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
k3s version :v1.18.2+k3s1   and  rancher  version v2.4.3

HA install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by szsuyuji** [comment]
change lb7 to lb4 fix it

**Comment by samirsss** [comment]
We're seeing this on 1.18.19 build of k3s more regularly now and hence wondering if there is something thats causing it?
