### ISSUE TITLE
If long service name, can't click on sidekick tabs in Summary

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2739]
Version - Master with latest reskin UI

Steps:
1.  Create a stack
2.  Add a service with a really long name (it allows for 255 characters so i put that many in there)
3.  Add a sidekick (name can be small) to that service
4.  Click on service to bring up summary

Result:
Notice that the tab for the Primary Service is so long that the sidekick drops to the bottom and is now not clickable.
![image](https://cloud.githubusercontent.com/assets/11514927/11283780/93b18e8e-8ec3-11e5-9693-062855bf6262.png)

Expected:
We should probably have a set tab length and if name goes over we should do the ... thing.

**Comment by deniseschannon** [comment]
Verified with latest UI with evening of 11/24.
