### ISSUE TITLE
I can't delete the app: rancher-logging

### ISSUE THREAD

**Issue by oangit** [rancher/rancher#27393]
Hello.
I can't delete the app: rancher-logging.
In the UI apps, I click Delete on the rancher-logging application.
The app is deleted, but installed again. 
How to delete the app: rancher-logging ?

Thanks for help.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.3.6` UI: `v2.3.40` |
|Route|`apps-tab.index`|

**Comment by patriczek** [comment]
Hi, 

did you find a solution for how to delete the app?
