### ISSUE TITLE
Chart Update - Flux v1.3.0

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#27400]
Helm 2 Chart - Flux v1.3.0
Located in the dev branch of https://github.com/rancher/charts

**Comment by jiaqiluo** [comment]
The chart is validated in rancher `v2.4-3131-head` and `master-3127-head`

steps:
- run Rancher server 
- add a cluster 
- change the branch of the catalog `library` to `dev` 
- launch the app `flux` version `1.3.0` with all default values 

Results:
- the app is launched and running up successfully
