### ISSUE TITLE
Change Rancher Machine default storage-driver to overlay2

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#27414]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Details:**

Right now, the aufs default is coded into Rancher Machine, this should be changed to overlay2:

https://github.com/rancher/machine/blob/master/libmachine/libmachine.go#L76

```
EngineOptions: &engine.Options{
    InstallURL:    drivers.DefaultEngineInstallURL,
    StorageDriver: "aufs",
    TLSVerify:     true,
},
```

So it looks like any Rancher provisioned cluster created with machine will end up with aufs by default. 

This can be worked around by setting storage-driver to overlay2 in the node template, but that doesn't seem to be an awesome solution as that just appends the flag to the docker command to replace the first. As you can see here, it's set twice

```
ubuntu@benhealey-ec2-test-4:~$ cat /etc/systemd/system/docker.service.d/10-machine.conf 
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=amazonec2 --storage-driver=overlay2 
Environment=
```
But it does work:

```
ubuntu@benhealey-ec2-test-4:~$ sudo docker info | grep 'Storage Driver'
 Storage Driver: overlay2
```

One last point here is that it's not entirely clear what to set in the node template to achieve overlay2. The [Docker Machine Docs](https://docs.docker.com/machine/reference/create/#accessing-driver-specific-flags-in-the-help-text) indicate using `engine-storage-driver`, but since engine options just appends to the actual docker command, that's invalid and causes Docker to fail to start.

gzrancher/rancher#10426

**Comment by bentastic27** [comment]
Potential fix https://github.com/rancher/machine/pull/86

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4-head

* Reproduced in v2.3.5
* Create cluster from node templates
* ssh to node
```
$ sudo docker info | grep 'Storage Driver'
Storage Driver: aufs
```
* Install v2.4-head
* Create cluster from node templates
* ssh to node
```
$ sudo docker info | grep 'Storage Driver'
 Storage Driver: overlay2
```

**Comment by bmdepesa** [comment]
rancher/rancher:master-3326-head
rancher/rancher:v2.4-head b7ab53e95

* Create cluster from node templates
* ssh to node
```
$ sudo docker info | grep 'Storage Driver'
WARNING: No swap limit support
 Storage Driver: overlay2
```

Upgrade from v2.4.5 to v2.4-head b7ab53e95
* Create cluster
* ssh to node
* See storage driver is `aufs`
* Upgrade to master-head
* Scale up cluster
* ssh to new node and see storage driver is `overlay2`
