### ISSUE TITLE
Unable to edit fields in Multi Cluster App

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#27416]
**What kind of request is this :**
Bug

**Steps to reproduce (least amount of steps as possible):**

Deploy docker-registry as Multi-Cluster App
Upgarde App after deployment

**Result:**

Below fields were not loading/editable.

- Default Storage Class for Docker registry
- Uses existing Persistent Volume Claim
- Answer Overrides

![mc_app_ui](https://user-images.githubusercontent.com/11064902/83659767-9852a880-a5e1-11ea-984d-9683e4dd8e51.PNG)
![mc_api-1](https://user-images.githubusercontent.com/11064902/83660156-1f078580-a5e2-11ea-9f31-0ba0f5b81b47.PNG)
![mc_api-2](https://user-images.githubusercontent.com/11064902/83660180-262e9380-a5e2-11ea-87ba-ad2bf762ee23.PNG)

**Other details that may be helpful:**

A similar issue was fixed in the past 
https://github.com/rancher/rancher/issues/16941

**Environment information**
- Rancher version : 2.4.3
- Installation option : HA

gzrancher/rancher#10423

**Comment by sowmyav27** [comment]
**Verified on 2.4.5**

Not able to reproduce the issue

- Deploy a cluster. Deploy Longhorn in the cluster
- Deploy docker-regitry mcapp. 
- Upgrade the app.
- `Default Storage Class`, `Uses existing Persistent Volume Claim` and `Answer Overrides` fields are editable.
<img width="1268" alt="Screen Shot 2020-06-24 at 11 11 01 AM" src="https://user-images.githubusercontent.com/26032343/85803560-468ed100-b6fc-11ea-96c5-00e78ffebcd2.png">
<img width="1314" alt="Screen Shot 2020-06-24 at 11 10 52 AM" src="https://user-images.githubusercontent.com/26032343/85803561-47276780-b6fc-11ea-8de7-82bb0c0a7442.png">

**Comment by westlywright** [comment]
Steps I used to reproduce on 2.4-master:

Launch Docker Registry MC app with the following options set:

- At least one target project
- Project Role
- Random PW
- Storage System: filesystem
- Persistence Enabled: true (leave defaults!)
- Layer 7: false
- Service Type: NodePort
- Node Port: (empty - dont even focus it)

Provide an the following override answer: 

- Same scope as a target project
- Question: Docker Registry Service Type
- Answer: NodePort
- NodePort Http Port: 30001

**Comment by sowmyav27** [comment]
**Verified on latest 2.4-head - ui tag: `latest-2.4`**

Reproduced the issue

**Steps:**
- Launch Docker Registry MC app with the following options set:
```
At least one target project
Project Role
Storage System: filesystem
Persistence Enabled: true (leave defaults!)
Layer 7: false
Service Type: NodePort
```
- Provide an the following override answer:
```
- Same scope as a target project
- Question: Docker Registry Service Type
- Answer: NodePort
- NodePort Http Port: 30001
```
<img width="1276" alt="Screen Shot 2020-06-25 at 4 32 53 PM" src="https://user-images.githubusercontent.com/26032343/85805678-d3885900-b701-11ea-8129-d7e706d48574.png">

**Comment by sowmyav27** [comment]
**verified on 2.4-head - commit id: `cf8f4a6f5` ui tag: `latest-2.4`**

Issue is seen fixed.

**Steps:**
- Create a standard user and login as the user. Create a cluster.
- Launch Docker Registry MC app with the following options set:
```
- At least one target project
- Project Role
- Storage System: filesystem
- Persistence Enabled: true (leave defaults!)
- Layer 7: false
- Service Type: NodePort
```
- Provide an the following override answer:
```
- Same scope as a target project
- Question: Docker Registry Service Type
- Answer: NodePort
- NodePort Http Port: 30001
```
Save the changes made and deploy the app
Click on Upgrade app.
Not issue is seen while loading the Answer overrides.
<img width="1335" alt="Screen Shot 2020-06-29 at 3 17 45 PM" src="https://user-images.githubusercontent.com/26032343/86061588-ed84ad00-ba1b-11ea-9710-e99ae9a24b86.png">

Verified using another app - mysql. And having answer overrides have a question for a question - having more than 1 level of question
<img width="1281" alt="Screen Shot 2020-06-29 at 3 18 28 PM" src="https://user-images.githubusercontent.com/26032343/86061645-ff665000-ba1b-11ea-8f66-de34f7311e02.png">
