### ISSUE TITLE
Stack that was never started gets stuck in Upgrade

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2741]
Version - Master with latest reskin UI

Steps;
1.  Add Elasticsearch Stack with older version of rancher
2.  Click on upgrade before you start any services
3.  Try to finish upgrade

Results:
It gets stuck trying to upgrade.  

Expected:
Should not get stuck.

**Comment by vincent99** [comment]
The UI just works here...  @alena1108 ?

**Comment by deniseschannon** [comment]
This looks like a duplicate of https://github.com/rancher/rancher/issues/2650 but better written. :)
