### ISSUE TITLE
Update the Rancher min version on Longhorn chart

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27423]
Need a different way to handle issue: https://github.com/rancher/rancher/issues/26661. Since we will be reverting the change [here](https://github.com/rancher/rancher/issues/27150)

Should leverage min/max version instead.

This should be released at the same time the revert happens.

**Comment by maggieliu** [comment]
Currently we will update the readme file to state that user cannot downgrade for longhorn.

TBD: whether or not we need to make an exception for longhorn to manage the upgrade (step by step) and preventing user from downgrading.

**Comment by yasker** [comment]
Talked with Will. We decide to just update the chart README to indicate that downgrade is not allowed for now.

**Comment by yasker** [comment]
README fix merged.

**Comment by khushboo-rancher** [comment]
@yasker Do we want to show this warning if only v1.0.0 selected? If I select v0.8.1 or lower version I don't see the warning.

**Comment by yasker** [comment]
We only care about v1.0.0+ for now.

**Comment by khushboo-rancher** [comment]
@yasker We should add this warning https://github.com/rancher/charts/blob/master/charts/longhorn/v0.1.0/README.md too.
Currently warning is added to only latest README file https://github.com/rancher/charts/blob/master/charts/longhorn/latest/README.md which means it  only applies to latest version and in future if we release another version warning will stop appearing in v1.0.0

**Comment by yasker** [comment]
@khushboo-rancher it should still appear in v1.0.0 since we always copy the latest folder then change the version?

**Comment by khushboo-rancher** [comment]
Yes, it is appearing in the v1.0.0 and since we copy the latest folder then change version it should be good. Closing this issue.
<img width="1362" alt="Screen Shot 2020-06-04 at 3 34 00 PM" src="https://user-images.githubusercontent.com/60111667/83819812-be2e8a80-a67f-11ea-91fd-69e60d4b696e.png">
