### ISSUE TITLE
[backport 2.3] [UI] Node Templates - Cloned Unusable

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#27424]
backport https://github.com/rancher/rancher/issues/26946

This has already been merged into UI for 2.3.

**Comment by sangeethah** [comment]
@izaac Seems like you have already validated tis issue in `2.3-head` - https://github.com/rancher/rancher/issues/26946#issuecomment-632854614.
Can you confirm that the fix id already available in `v2.3.8` ?

**Comment by izaac** [comment]
This is still reproducible in `v2.3.8` @sangeethah @deniseschannon

**Comment by izaac** [comment]
This looks fixed in `v2.3-head` commit: 01db604d8
