### ISSUE TITLE
Adding Registry Credentials to a project doesn't work

### ISSUE THREAD

**Issue by andruwa13** [rancher/rancher#27435]
* Not add custom Registry Credentials *

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
|Route|`undefined`|
![Rancher 2020-06-04 10-56-36](https://user-images.githubusercontent.com/5846351/83730909-6594c880-a652-11ea-8739-0dcfd51eecf2.png)

**Comment by hingew** [comment]
I got the same issue. In the console i've got the following error :

```
component.js:79 Uncaught TypeError: Cannot read property 'id' of null
    at n.willSave (component.js:79)
    at n.save (new-or-edit.js:54)
    at e.n._join (backburner.js:1048)
    at e.n.join (backburner.js:759)
    at p (index.js:176)
    at glimmer.js:7609
    at s (index.js:143)
    at n.save (glimmer.js:7608)
    at n.save (component.js:55)
    at n.send (action_support.js:19)
```

**Comment by pehbehbeh** [comment]
There is the same problem in #27373.

**Comment by hingew** [comment]
Just tested it with a signle namespace, works perfect!  

This only happs, when the option `Available to all namespaces in this project` is selected.

**Comment by westlywright** [comment]
@rancher/qa can we re-test this? I believe the main issue was found and resolved in the attached PR. 


https://github.com/rancher/rancher/issues/26981

**Comment by soumyalj** [comment]
Reproduced the issue with v2.4.4

Validated with v2.4.5-rc6. 

1. Create a registry credential available to all namespaces choosing address Dockerhub/quay.io/artifactory/custom and provide username/password.
2. Registry gets added correctly with no errors.  

Note: Also verified that creating registry available for a single namespace is functional.
