### ISSUE TITLE
Description missing in summary view for Load Balancer, External Service and Service Alias

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2743]
Version - Master with latest reskin UI

Steps;
1.  Create a stack
2.  Add a Service, Load Balancer, External Service and Service Alias.  Make sure they all have descriptions.
3.  Click on each Service to see the summary

Results:
Description exists under the Info section for Service, but does not show up for Load Balancer, External Service and Service Alias.

Expected:
Description should show up in the summary for all Services.

**Comment by deniseschannon** [comment]
Description is now available in all cases on the summary service page.

When there is a hostname on an external service, there is no line break between the two.
