### ISSUE TITLE
No View Details link in Summary view for Service Alias or External Service

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2744]
Version - Master with latest reskin UI

Steps:
1.  Create a stack
2.  Add a Service Alias and External Service
3.  Click on the service's name to bring up summary view

Results:
In the summary view for Service Alias and External Services there is no View Details link.

Expected:
View Detail link and a details page for each service.

**Comment by deniseschannon** [comment]
Verified this in reskin that the "View Details" is showing in the summary name when looking at #2783
