### ISSUE TITLE
New Dashboard - pod logs bottom not visible

### ISSUE THREAD

**Issue by wu105** [rancher/rancher#27443]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

On Rancher web ui, select any cluster, click on the "Try Dashboard" button, select Pod from the left navigation column, select View Logs from the popup menu of any pod on the right.

**Result:**
The bottom of the log is not visible, regardless of the scroll position.

**Other details that may be helpful:**
The browser is Chrome Version 81.0.4044.113 (Official Build) (64-bit)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.4
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMWare instances
- Kubernetes version (use `kubectl version`): v1.17.6

```
(paste the output here)
```

- Docker version (use `docker version`): 18.9.1

```
(paste the output here)
```

**Comment by vincent99** [comment]
This is fixed already for the next release, logs and shell now go in a tabbed tray at the bottom so you can have more than one of them up at a time and switch between them.
