### ISSUE TITLE
Issues increasing the number of nodes in an existing Azure VM node pool

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#27447]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Upgrade Rancher from v2.4.2 to v2.4.3 or start with 2.4.3
Create a new Azure VM node pool or edit an existing one (if upgraded from 2.4.2) 
Attempt to increase the number of nodes in the node pool

**Result:**
The new nodes will fail to be added and an error will be output, like the one below:

> Error with pre-create check: "resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 
> Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" 
> Message=\"The client 'XXXX' with object id 'YYYY' does not have authorization to perform action 'Microsoft.Subscription/register/action' over scope '/subscriptions/ZZZZ' or the scope is invalid. If access was recently granted, please refresh your credentials.\""; Timeout waiting for ssh key

**Other details that may be helpful:**
Increasing the number of nodes in an existing Azure VM node pool was confirmed as working on v2.4.2 and appears to be a regression in 2.4.3

**Environment information**

- Rancher version: v2.4.3
- Kubernetes version: v1.17.4
- OS: Ubuntu 18.04.04 LTS
- HA RKE installation 
- Cloud Provider: Azure  
- Node Type: Azure VMs

gzrancher/rancher#10408

**Comment by aiyengar2** [comment]
Created a app registration with scoped down permissions here: [arvind-test-scoped-down-permissions](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Overview/appId/f2780e84-bb34-4f2b-9189-ec5c415e4a93/objectId/efc89fcc-9fa9-4300-a4fc-92d8bb6b70a2/isMSAApp//defaultBlade/Overview/appSignInAudience/AzureADMyOrg/servicePrincipalCreated/true). This can either be directly used for testing (i.e. just create another pair of credentials) or you can follow the following steps to independently replicate this / create a long-standing test resource for future scoped-down Azure tests:

1. Create a new App Registration and create credentials for it for Rancher
2. Locate the Object ID of the Service Principal created for your App Registration. The service principal object can be found in the Enterprise Applications section of the Azure CLI; it should have the same name as the app registration that you created.
3. Create a custom role with the following scope; this can easily be performed on the Azure CLI by creating a JSON file with the following contents locally (make sure to fill in the capitalized fields first) and running `az role definition create --subscription <subscription>  --role-definition @<json-file-name>`. Keep track of the ID of the object returned.
```
{
    "assignableScopes": [
        "/subscriptions/YOUR_SUBSCRIPTION_HERE"
    ],
    "description": "Scoped down permissions for Rancher Azure node driver deployments",
    "name": "YOUR_NAME_HERE",
    "actions": [
        "Microsoft.Resources/subscriptions/resourceGroups/read",
        "Microsoft.Resources/subscriptions/resourceGroups/write",
        "Microsoft.Compute/virtualMachines/*",
        "Microsoft.Compute/disks/write",
        "Microsoft.Compute/disks/read",
        "Microsoft.Compute/disks/delete",
        "Microsoft.Storage/storageAccounts/read",
        "Microsoft.Storage/storageAccounts/write",
        "Microsoft.Storage/storageAccounts/delete",
        "Microsoft.Storage/storageAccounts/blobServices/containers/read",
        "Microsoft.Storage/storageAccounts/blobServices/containers/write",
        "Microsoft.Storage/storageAccounts/blobServices/containers/delete",
        "Microsoft.Compute/images/read",
        "Microsoft.Compute/galleries/images/read",
        "Microsoft.Compute/galleries/images/versions/read",
        "Microsoft.Network/networkInterfaces/read",
        "Microsoft.Network/networkInterfaces/write",
        "Microsoft.Network/networkInterfaces/delete",
        "Microsoft.Network/networkInterfaces/join/action",
        "Microsoft.Network/publicIPAddresses/read",
        "Microsoft.Network/publicIPAddresses/write",
        "Microsoft.Network/publicIPAddresses/delete",
        "Microsoft.Network/publicIPAddresses/join/action",
        "Microsoft.Network/networkSecurityGroups/read",
        "Microsoft.Network/networkSecurityGroups/write",
        "Microsoft.Network/networkSecurityGroups/delete",
        "Microsoft.Network/networkSecurityGroups/join/action",
        "Microsoft.Compute/availabilitySets/read",
        "Microsoft.Compute/availabilitySets/write",
        "Microsoft.Compute/availabilitySets/delete",
        "Microsoft.Network/virtualNetworks/subnets/read",
        "Microsoft.Network/virtualNetworks/subnets/write",
        "Microsoft.Network/virtualNetworks/subnets/delete",
        "Microsoft.Network/virtualNetworks/subnets/join/action",
        "Microsoft.Network/virtualNetworks/read",
        "Microsoft.Network/virtualNetworks/write",
        "Microsoft.Network/virtualNetworks/delete"
    ],
    "dataActions": [
        "Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read",
        "Microsoft.Storage/storageAccounts/blobServices/containers/blobs/write",
        "Microsoft.Storage/storageAccounts/blobServices/containers/blobs/delete"
    ],
    "notDataActions": []
}
```
4. Assign that custom role to the service principal object: `az role assignment create --assignee <service-principal-object-id> --subscription <subscription> --role <id-returned-from-az-role-definition-update-command>` You can confirm that this correctly attached the permission by navigating to Subscriptions -> <org_subscription> -> Access Control (IAM) in the Azure Portal and searching up the name of your service principal object / app registration; the name of this role should appear there.

Once this is done, the client credentials created from the App Registrations should have scoped down permissions. The above error should be replicable in Rancher 2.4.3 and 2.4.4 setups and no errors should appear in Rancher 2.4 head and master head once the above commits are merged.

**Comment by aiyengar2** [comment]
https://github.com/rancher/rancher/issues/27468 is another error with the Azure driver that I discovered on trying to scope down the permissions, relating to the deletion of Azure resources. There is a fix coming out for that (https://github.com/rancher/machine/pull/88), but you should still be able to spin up a cluster properly with Azure without this fix.
