### ISSUE TITLE
Add Windows 2004 agent build

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27451]
Add Windows 2004 to our drone.yaml for continued up to date windows agent support.

Has dependency on: https://github.com/drone-plugins/drone-docker/pull/284

gz#8443
gz#12951

**Comment by luthermonson** [comment]
https://github.com/rancher/dapper/pull/85

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `65a15b94`**

- Deploy a windows VXLAN network cluster. 
- Register 3 linus nodes - 1 etcd, 1 control plane and 1 windows linux nodes.
- Register a windows 2004 node - AMI - `Windows_Server-2004-English-Core-Base-2020.11.11`
- The node fails to register

```
Digest: sha256:aeb7e77f93780634609ab45d28ac6da79aa55aa529ae89a6b0213449b41ed25f
Status: Downloaded newer image for rancher/rancher-agent:v2.5-65a15b941fb8818f6d4703197a9436a4c26a9972-head
INFO: Detecting running permission ...            
INFO: Detecting host CPU reservation ...          
INFO: Detecting host RAM reservation ...          
INFO: Detecting host DISK reservation ...         
INFO: Detecting host Docker named pipe existing ...
INFO: Detecting host Docker platform name...      
INFO: Detecting host network interface ...        
INFO: Configuring host Docker Service to start automatically...
INFO: Enabling host msiscsi service to support iscsi storage ...
Unable to find image 'rancher/rancher-agent:v2.5-4642-head' locally
docker: Error response from daemon: manifest for rancher/rancher-agent:v2.5-4642-head not found: manifest unknown: manifest unknown.
```

**Note:**
Able to register a windows 1903 node in the same cluster.

Reopening the issue.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id : `2ba49cb72`**

- Deploy a windows VXLAN network cluster.
- Register 3 linus nodes - 1 etcd, 1 control plane and 1 windows linux nodes.
- Register a windows 2004 node - AMI - Windows_Server-2004-English-Core-Base-2020.11.11
- Windows nodes are stuck in Registering state

```
docker logs 2226fd007d3b
INFO: Waiting for servcie-sidekick to prepare the entrypoint.ps1 ...
FATA: Timeout, could not found c:\opt\rke-tools\entrypoint.ps1      
INFO: Waiting for servcie-sidekick to prepare the entrypoint.ps1 ...
```

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `e3128c99`**

- K8s version - 1.19.7-rancher2-1, deployed a windows cluster with 3 linux nodes, 3 windows worker nodes.
- Cluster deployed fine and came up Active. Nodes registered.
- Validation tests look good on this cluster - includes - workload deployments, ingress, service discovery
