### ISSUE TITLE
Cannot create registry credentials in Rancher UI

### ISSUE THREAD

**Issue by andrii-litvinov** [rancher/rancher#27456]
I have upgraded to `v2.4.4` and noticed that I cannot create Registry Credentials for the project anymore. I tried to inspect request in the browser and noticed that no requests are being send to the server. The spinner on Save button (which is being renamed to Saving) keep spinning with no results. On `v2.3.x` everything works fine.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.4` UI: `v2.4.22` |
|Route|`undefined`|

**Comment by alphayax** [comment]
Take a look at this :
- https://github.com/rancher/rancher/issues/26981
- https://github.com/rancher/ui/pull/3983

**Comment by andrii-litvinov** [comment]
Thanks for quick response! I must have found it myself. Google didn't show any results, so I assumed that this issue is new in `v2.4.4`.

**Comment by andrii-litvinov** [comment]
Going through the mentioned issues I see that it says that the issues is resolved in `v2.4.4`, but it is still present, so I think I will reopen my issues for now. The workaround mentioned in this comment https://github.com/rancher/rancher/issues/26981#issuecomment-637493461  does work though.

**Comment by lwj5** [comment]
facing the same issue for both 2.4.3 and 2.4.4

**Comment by LucidNeko** [comment]
Linking in a post from the rancher forums

https://forums.rancher.com/t/rancher-2-4-4-hanging-saving-registry-credentials-for-all-namespaces/17668

**Comment by andrii-litvinov** [comment]
Seems to be resolved in 2.4.5, so closing this one. Many thanks!
