### ISSUE TITLE
monitoring - volume is used by existing pod after upgrading cluster monitoring

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#27450]
**What kind of request is this (question/bug/enhancement/feature request):**
bug found during validating this issue: https://github.com/rancher/rancher/issues/27418

**Steps to reproduce (least amount of steps as possible):**
- run rancher `v2.4.4` single install
- add a cluster with k8s `v1.17.6`
- deploy the app `Longhorn`
- enable the cluster monitoring (0.1.0) with `Enable Persistent Storage for Grafana` using Longhorn as the storage class
- upgrade Rancher to `v2.4.5-rc1`
- upgrade cluster monitoring to `v0.1.1`

**Result:**
- the new pod of `grafana-cluster-monitoring` failed to start because the volume is used by the existing pod

```
Warning | FailedMount | Unable to attach or mount volumes: unmounted volumes=[grafana-storage], unattached volumes=[cluster-monitoring-token-5k4sd grafana-storage grafana-dashboards grafana-istio-dashboards grafana-provisionings nginx-home grafana-nginx grafana-static-contents]: timed out waiting for the condition | 2 minutes ago
Warning | FailedMount | Unable to attach or mount volumes: unmounted volumes=[grafana-storage], unattached volumes=[grafana-static-contents cluster-monitoring-token-5k4sd grafana-storage grafana-dashboards grafana-istio-dashboards grafana-provisionings nginx-home grafana-nginx]: timed out waiting for the condition | 4 minutes ago
Warning | FailedMount | Unable to attach or mount volumes: unmounted volumes=[grafana-storage], unattached volumes=[grafana-dashboards grafana-istio-dashboards grafana-provisionings nginx-home grafana-nginx grafana-static-contents cluster-monitoring-token-5k4sd grafana-storage]: timed out waiting for the condition | 7 minutes ago
Warning | FailedMount | Unable to attach or mount volumes: unmounted volumes=[grafana-storage], unattached volumes=[grafana-storage grafana-dashboards grafana-istio-dashboards grafana-provisionings nginx-home grafana-nginx grafana-static-contents cluster-monitoring-token-5k4sd]: timed out waiting for the condition | 13 minutes ago
Warning | FailedAttachVolume | Multi-Attach error for volume "pvc-4fef7117-0cfe-4428-9fe8-9413e835ec97" Volume is already used by pod(s) grafana-cluster-monitoring-649c4df4b5-bxlf6 | 18 minutes ago
Normal | Scheduled | Successfully assigned cattle-prometheus/grafana-cluster-monitoring-7f4bb84f65-gmckq to jiaqi-244-w4 | Invalid date
```

![image](https://user-images.githubusercontent.com/6218999/83812542-9552c900-a670-11ea-86a5-54b3d43debf5.png)

<img width="1292" alt="Screen Shot 2020-06-04 at 2 24 34 PM" src="https://user-images.githubusercontent.com/6218999/83812562-9c79d700-a670-11ea-81e6-2d3de2035f9a.png">

Related Issue: https://github.com/rancher/rancher/issues/24582

gzrancher/rancher#10888

**Comment by jiaqiluo** [comment]
This bug does NOT happen in the upgrade path when the `Persistent Storage for Grafana` is NOT enabled. 

Steps are the same as the issue provided expected that the `Persistent Storage for Grafana` is NOT enabled.

**Comment by StrongMonkey** [comment]
@jiaqiluo are you able to reproduce with another storage driver(instead of longhorn)? I am more curious about if that's specific bug about longhorn driver.

**Comment by StrongMonkey** [comment]
When I tried to reproduce it even without upgrading rancher the pod failed to launch.

**Comment by jiaqiluo** [comment]
@StrongMonkey The cluster monitoring (v0.1.1) works on the cluster with Amazon as the cloud provider.

Steps:

- run rancher `v2.4.5-rc1` single install
- add a cluster with k8s `v1.17.6` and  Amazon as the cloud provider
- add a storage class with EBS
- enable the cluster monitoring (v0.1.1) with Enable Persistent Storage for Grafana using the storage class 

Results:
- the cluster monitoring is deployed successfully and working as expected

 
<img width="1407" alt="Screen Shot 2020-06-05 at 9 27 02 AM" src="https://user-images.githubusercontent.com/6218999/83900874-cf72a800-a70e-11ea-835f-e1541d6bbff3.png">

![image](https://user-images.githubusercontent.com/6218999/83900789-c84b9a00-a70e-11ea-998d-12ae9abebc07.png)

**Comment by StrongMonkey** [comment]
From the issue you described, the error was caused by a pod that is active using the volume during the upgrade. A possible workaround would be deleting the old pod so that volume can be released. We might also need to change the upgrading strategy to `Recreate` if volume is attached.

**Comment by StrongMonkey** [comment]
@jiaqiluo Can you try the workaround to see if that works? In our current chart we deploy grafana as k8s deployment while the prometheus-operator chart(upstream) has changed to use statefulset to deploy grafana if persist volume is used and I think that could solve this volume issue. cc @maggieliu Will possibly need more time to investigate how we can get [upstream changes](https://github.com/helm/charts/commit/b4b137e70fe56b86a45daef2bc2ad06e6e22391a#diff-9f60775633bb510fb9e3b3c20679ac09) into our current chart. Not sure this is something we need to schedule for 2.4.5.

**Comment by StrongMonkey** [comment]
@jiaqiluo Also I think I have made false conclusion that it is related to longhorn. I had an environment issue with longhorn and later it was solved. I think this is related to how we deploy grafana with persist volume enabled: grafana is deployed as a k8s deployment with persist volume and is poor at dealing with upgrade.

**Comment by jiaqiluo** [comment]
It turns out this is a better workaround:
- scale down the workload `grafana-cluster-monitoring` to 0
- wait for pods to be removed
- scale up back to 1

This way will guarantee that the new pod is using the new images.
If we delete the old pod, then there is a race between creating a pod in the old replicaSet and in the new replicaSet, and my tests show most of the time the old replicaSet wins so a new pod using the old image is running eventually

**Comment by bashofmann** [comment]
monitoring v2 is fixing this issue by switching the Grafana deployment to use

```
  strategy:
    type: Recreate
```

https://github.com/rancher/charts/blob/dev-v2.5/packages/rancher-monitoring/rancher-monitoring.patch#L2367-L2369

**Comment by maggieliu** [comment]
@jiaqiluo Can you confirm this is fixed in v2?

**Comment by jiaqiluo** [comment]
I can confirm this bug is fixed in monitoring v2.

Steps:
- run rancher:`v2.5-61a8a3691063108bc775c8e4e6f6db971541c253-head` single-install 
- provision a cluster
- install Longhorn `1.0.201`
- install Monitoring v2 `9.4.200` with persistent storage enabled for Grafana 
- confirm that monitoring is installed successfully and working properly with the persistent storage enabled for Grafana 
- upgrade the rancher-monitoring app to use the latest chart `9.4.201` 
- confirm that monitoring is upgraded successfully and working properly with the persistent storage enabled for Grafana
