### ISSUE TITLE
Documentation on exposing metrics to Prometheus

### ISSUE THREAD

**Issue by eroji** [rancher/rancher#27453]
There are little usable documentation on how to expose metrics to Prometheus, or Rancher's implementation of Prometheus. I am trying to expose metrics made available via SpringBoot's actuator. I have customized the default endpoint of /metrics to /app/metrics. The output looks like this.

```
{
  "mem": 5526266,
  "mem.free": 1428302,
  "processors": 6,
  "instance.uptime": 13824893,
  "uptime": 14021880,
  "systemload.average": 0.07,
  "heap.committed": 3879744,
  "heap.init": 4194304,
  "heap.used": 2451441,
  "heap": 3879744,
  "nonheap.committed": 1742508,
  "nonheap.init": 2496,
  "nonheap.used": 1646522,
  "nonheap": 3391488,
  "threads.peak": 326,
  "threads.daemon": 215,
  "threads.totalStarted": 1997,
  "threads": 313,
  "classes": 191394,
  "classes.loaded": 191832,
  "classes.unloaded": 438,
  "gc.parnew.count": 140,
  "gc.parnew.time": 9321,
  "gc.concurrentmarksweep.count": 7,
  "gc.concurrentmarksweep.time": 2542,
  ".post.200{timing}": 5472,
  ".post.500{timing}": 411,
  ".post.500{gauge}": 411,
  ".post.200{gauge}": 5472,
  ".post.500{counter}": 8,
  ".post.200{counter}": 355
}
```

However, I could not get Rancher's Prometheus to scrape these metrics. I have enabled the annotation in the deployment `field.cattle.io/workloadMetrics: '[{"path":"/app/metrics","port":8080,"schema":"HTTP"}]'`. I can see that it created the `ServiceMonitor ` object, however none of these metrics show up in Prometheus. I also enabled cluster and project level Prometheus monitoring, which I do not understand the need for 2 deployment for nor is that clearly explained anywhere. Can anyone clarify how to do this correctly and what the need is for 2 set of Prometheus deployments?

**Comment by immanuelfodor** [comment]
Did you manage to get the metrics show up in Prometheus? @eroji I looks like your metrics output is not in the regular Prometheus format but JSON.
