### ISSUE TITLE
UI Issues - Round three

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2745]
Version - Master with latest reskin UI

I realize some of these issues are very minor or opinion based and may not be changed :-).

- [x] Add Stack yml import - text is top aligned with button.  Should probably be centered so there isn't so much room between bottom of text and yml editbox.

![image](https://cloud.githubusercontent.com/assets/11514927/11283632/e45544b2-8ec2-11e5-9441-e3cf3b8bede4.png)

- [x] Main Stack screen and stack details page - Upgrading and Up to Date text are clickable and look like a button but don't do anything

![image](https://cloud.githubusercontent.com/assets/11514927/11285963/8379e668-8ecf-11e5-8936-d9a9a5a6994f.png)

- [x] Main stack page - Add Service button is in different position depending if Stack has Upgrade option or not.

![image](https://cloud.githubusercontent.com/assets/11514927/11286051/f8bc5e56-8ecf-11e5-8a0b-6c206a3ddffa.png)

- [x] Add Services - the add port and add service link + button is too close to the text below it.  When selected, the blue outline covers the top of the text

![image](https://cloud.githubusercontent.com/assets/11514927/11286733/f022f7b0-8ed3-11e5-853a-9548bd2c471e.png)

- [x] Edit Service - Service link's + button too close to text below it

![image](https://cloud.githubusercontent.com/assets/11514927/11287114/83a6e026-8ed6-11e5-94e7-f375570e62e1.png)

- [x] Add & Edit Service Alias - lots of white space and a grid line separating Target's + Add Service and the Select a Service dropdown.

![image](https://cloud.githubusercontent.com/assets/11514927/11286971/a65467de-8ed5-11e5-84d3-474df7165a7c.png)

- [x] Add External Service - no space between Target's + button and edit field.

![image](https://cloud.githubusercontent.com/assets/11514927/11287003/d9594118-8ed5-11e5-815c-6e36f3a38d43.png)

- [x] Edit External Service - no space between Target's + button and edit field.

![image](https://cloud.githubusercontent.com/assets/11514927/11287168/e8ebcf78-8ed6-11e5-91a1-176569ffcf7e.png)

- [ ] Multiple screens - the green solid circle and hollow circle together looks like a bug.  I know it's to tell the difference between started-once and running.  But it's still confusing.

![image](https://cloud.githubusercontent.com/assets/11514927/11287268/88576018-8ed7-11e5-9de2-25a3e76b148c.png)

**Comment by tfiduccia** [comment]
Feedback from 11/18 email:

- [ ] Wish Add Service drop-down was closer to the stack name.  If you have a really wide screen, it's kind of hard to find.  Most likely due to where the old location was.  Tani comment - I'm not sure if it's the location or that it's white on a light grey background and doesn't stand out at all.

- [ ] Not sure how I like the shadowing of boxes and not sure how it would look on a crappy screen/projection.

- [ ] The rounded state icons look too round when everything else has been squared off

- [ ] Access Control page, what does the v do?  Can it be removed?

![image](https://cloud.githubusercontent.com/assets/11514927/11309038/c45818da-8f7e-11e5-86fc-e1d23b47e354.png)

**Comment by westlywright** [comment]
@tfiduccia for the add service button, i did not move but but i changed the default styles of the button. the base font color is the dark blue now to bring a bit more focus to the button. on hover i change the text to white and background to dark blue so it does not look like its an inactive button like the old styles.

**Comment by vincent99** [comment]
checkered circle: I'm sticking with that unless someone has a better idea.. it's halfway between the stopped and running icons.

shadowed wells: nobody else has argued, projector issues would be more about the contrast between the inner & outer backgrounds than the shadows.

**Comment by deniseschannon** [comment]
I'm fine with leaving the shadowed wells.

**Comment by tfiduccia** [comment]
Version - Master
Verified Fixed
