### ISSUE TITLE
Update Minio and minio-go in rke-tools to latest version

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27467]
Update Minio Image to the latest: RELEASE.2020-07-13T18-09-56Z
https://github.com/minio/minio/releases/tag/RELEASE.2020-07-13T18-09-56Z

Update minio-go in rke-tools
https://github.com/minio/minio-go/releases/tag/v6.0.57

**Comment by soumyalj** [comment]
Tested with v2.4-head(2d58a3fcd)
1. Created a cluster with backup/restore configured to minio
Backup/restore using minio was functional. 
RKE tools shows the updated version v0.1.60.
The minio version points to `2019-09-25T18-25-51Z`

**Comment by soumyalj** [comment]
Tested with v2.4-head(e6e3632a8)
1. Create a DO cluster with backup/restore configured to minio. 
2. Create few workloads. Perform a backup snp1. Create another workload. 
3. Perform restore to snp1. 

Backup and restore was functional using minio

Rke tools was updated to the version `rancher/rke-tools : v0.1.61`
```
root@soumyauserminiotest1:~# sudo docker ps -a|grep rke-tools
d0352d14233e        rancher/hyperkube:v1.18.6-rancher1                "/opt/rke-tools/entr…"   8 minutes ago            Up 8 minutes                                      kube-proxy
3f13ba1acc99        rancher/hyperkube:v1.18.6-rancher1                "/opt/rke-tools/entr…"   9 minutes ago            Up 9 minutes                                      kubelet
651488425f6f        rancher/hyperkube:v1.18.6-rancher1                "/opt/rke-tools/entr…"   9 minutes ago            Up 8 minutes                                      kube-scheduler
d42eb2648c29        rancher/hyperkube:v1.18.6-rancher1                "/opt/rke-tools/entr…"   9 minutes ago            Up 8 minutes                                      kube-controller-manager
80cab40ca440        rancher/hyperkube:v1.18.6-rancher1                "/opt/rke-tools/entr…"   9 minutes ago            Up 9 minutes                                      kube-apiserver
e988e4fa4409        rancher/rke-tools:v0.1.61                         "/bin/bash"              9 minutes ago            Created                                           service-sidekick
86c76fbce208        rancher/rke-tools:v0.1.61                         "/bin/bash"              10 minutes ago           Exited (0) 10 minutes ago                         cluster-state-deployer

```

Minio version was also updated to the latest `rancher/minio-minio:RELEASE.2020-07-13T18-09-56Z`. 
This was observed by enabling and running the default pipeline in rancher
![Screen Shot 2020-07-22 at 12 41 50 PM](https://user-images.githubusercontent.com/18536626/88221055-bff4e300-cc18-11ea-8f69-173fa7df20fd.png)

**Comment by soumyalj** [comment]
Tested with master-head(f7e83e3e4)
Create a DO cluster with backup/restore configured to minio as a standard user
Create few workloads. Perform a backup snp1. Create another workload.
Perform restore to snp1.
Backup and restore was functional using minio

Rke tools was updated to the version rancher/rke-tools : v0.1.61
```
root@soumyamasterdotest1:~# sudo docker ps -a|grep rke-tools
ffa3548281d9        rancher/hyperkube:v1.18.6-rancher1                "/opt/rke-tools/entr…"   26 minutes ago       Up 26 minutes                                         kube-proxy
6d00725d5b17        rancher/hyperkube:v1.18.6-rancher1                "/opt/rke-tools/entr…"   26 minutes ago       Up 26 minutes                                         kubelet
7da1788c1c35        rancher/hyperkube:v1.18.6-rancher1                "/opt/rke-tools/entr…"   27 minutes ago       Up 4 minutes                                          kube-scheduler
c9352defd59d        rancher/hyperkube:v1.18.6-rancher1                "/opt/rke-tools/entr…"   27 minutes ago       Up 19 minutes                                         kube-controller-manager
c23f7c9bfdbe        rancher/hyperkube:v1.18.6-rancher1                "/opt/rke-tools/entr…"   27 minutes ago       Up 27 minutes                                         kube-apiserver
c3143dd5f8a5        rancher/rke-tools:v0.1.61                         "/bin/bash"              27 minutes ago       Created                                               service-sidekick
e77fff1af0e2        rancher/rke-tools:v0.1.61                         "/bin/bash"              58 minutes ago       Exited (0) 58 minutes ago                             cluster-state-deployer

```

**Comment by maggieliu** [comment]
Updated a default value for memory limit.

**Comment by soumyalj** [comment]
Validated with master-head (c761bcd4d)

- Minio image verification

Enable and run the default pipeline rancher/pipeline-example-go in Rancher.
Minio image was updated to the latest rancher/minio-minio:RELEASE.2020-07-13T18-09-56Z
Minio workload came up successfully. No crashloop backoff errors observed.

![Screen Shot 2020-08-03 at 3 09 17 PM](https://user-images.githubusercontent.com/18536626/89232000-5a4f1200-d59b-11ea-9876-64b7f4ab91f1.png)

- Verified that the memory limit for minio deployment was updated to 500M

![Screen Shot 2020-08-03 at 3 10 40 PM](https://user-images.githubusercontent.com/18536626/89232081-88345680-d59b-11ea-8c9e-1862c5a436ba.png)
![Screen Shot 2020-08-03 at 3 11 30 PM](https://user-images.githubusercontent.com/18536626/89232134-a7cb7f00-d59b-11ea-8e05-2e7d5f2c25d4.png)
