### ISSUE TITLE
[Backport 2.3] Update Monitoring chart to 0.1.1

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27465]
Backport Monitoring charts 0.1.1 to 2.3.8.

**Comment by StrongMonkey** [comment]
Can we just test monitoring v0.1.1 with rancher 2.3?

**Comment by jiaqiluo** [comment]
It is validated that the new version `0.1.1` does not show in Rancher` v2.3.8` 
after changing the branch of  `system-library` to `dev-v2.3`

**Comment by jiaqiluo** [comment]
the new chart version `0.1.1` is validated on Rancher `v2.3.8`.

Scenario 1: upgrading from `0.1.0` to `0.1.1`
- run Rancher `v2.3.8` single install
- add a cluster with k8s `v1.17.6-rancher2-1` with AWS as the cloud provider 
- add EBS as the storage class
- enable cluster monitoring `0.1.1` with persistent storage enabled for Prometheus and Grafana
- make sure monitoring is working properly
- change the branch of `system-library` to `dev-v2.3`
- upgrade cluster monitoring to 0.1.1

Results:
- the upgrade is successful (but need this workaround: https://github.com/rancher/rancher/issues/27418#issuecomment-642979454)
- old data are reserved and show in graphs

Scenario 2: fresh install of `0.1.1`
- run Rancher `v2.3.8` single install
- add a cluster with k8s `v1.17.6-rancher2-1` with AWS as the cloud provider 
- add EBS as the storage class
- change the branch of `system-library` to `dev-v2.3`
- enable cluster monitoring `0.1.1` with persistent storage enabled for Prometheus and Grafana

Results:
- the monitoring is working properly
