### ISSUE TITLE
NSG deletion bug in Azure node driver

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#27468]
While testing scoped down permissions for Azure, for https://github.com/rancher/rancher/issues/27447, I noticed the following error statement:
```
2020/06/05 14:17:57 [WARNING] [node-controller-rancher-machine] Error removing host "arvind-test-scoped-down-perms-gallery-image1": network.SecurityGroupsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<redacted>' with object id '<redacted>' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourceGroups/Microsoft.Network/read' over scope '/subscriptions/<redacted>/resourceGroups/providers/Microsoft.Network/networkSecurityGroups' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

The scope `Microsoft.Resources/subscriptions/resourceGroups/Microsoft.Network/read` is not a valid scope; on investigation, this is the result of an empty resource group being passed into the `network.SecurityGroupsClient#Get` call, which is because the nsgResource passed into [`DeleteNetworkSecurityGroupIfExists`](https://github.com/rancher/machine/blob/d32ea31a178bb4fe952f1885666aafa30850400c/drivers/azure/azure.go#L496-L498) is not set. 

PR with an attempt at the fix: https://github.com/rancher/machine/pull/88

~This is likely because this unexported field is set in [`SetConfigFromFlags`](https://github.com/rancher/machine/blob/d32ea31a178bb4fe952f1885666aafa30850400c/drivers/azure/azure.go#L328-L331) rather than being directly set in `Create` or `Remove`. Relocating `resolveNSGReference` to `Create` and `Remove` seems to resolve the issue.~ 
See PR for comments; same solution, incorrect diagnosis

How to Test:

Creating any Azure node driver cluster in 2.4.4 using a pooled or legacy NSG and then deleting the cluster should leave behind the NSG resource in the node template's resource group, even if all nodes are deleted.

Once this fix is in, creating a Azure node driver cluster with a pooled or legacy NSG and deleting the cluster should successfully clean up the NSG resource.

**Comment by soumyalj** [comment]
Tested with v2.4-head. 
1. Created a azure template and azure cluster 
2. Delete the azure cluster. 
After deletion, the NSG was still remaining in the resource group. IP and NIC resources were deleted.
