### ISSUE TITLE
etcd port 4001 being advertised

### ISSUE THREAD

**Issue by jhughes2112** [rancher/rancher#27476]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Install a cluster with Rancher in a docker container.
Login to any node and do the following:
`docker exec -ti etcd /bin/sh etcdctl member list`
`docker inspect etcd`

**Result:**
etcdctl member list will demonstrate the advertised ports:
```4516eede590f8d0, started, etcd-atlas, https://<nodeipaddress>:2380, https://<nodeipaddress>:2379,https://<nodeipaddress>:4001, false```

Inspecting etcd container will show that the rancher/coreos-etcd:v3.4.3-rancher1 image does not bind to port 4001 at all.

**Other details that may be helpful:**
If you run the etcd benchmark program against etcd, it will frequently fail to connect to nodes because they are being advertised as available via port 4001, which they are not.  This also may account for other bugs/performance issues.  I'm not an expert on that, but I did find that by draining my nodes one by one, stopping etcd, and running a new etcd with that port not being advertised did fix the problem I was seeing in benchmark.  I also symlinked /var/lib/etcd to my nvme ssd drive while I had it down.  Not 100% if the bad address was partially responsible, but the average/worst on the benchmark went from 0.170s/1.7s -> 0.010s/0.027s.  Dramatically better.

```docker run --rm --name benchmark -v /etc/kubernetes:/etc/kubernetes ferrandinand/etcd-benchmark --endpoints=https://10.0.0.241:2379 --target-leader --conns=1 --clients=1 put --key-size=8 --sequential-keys --total=10000 --val-size=256 --cacert /etc/kubernetes/ssl/kube-ca.pem --key /etc/kubernetes/ssl/kube-etcd-10-0-0-241-key.pem --cert /etc/kubernetes/ssl/kube-etcd-10-0-0-241.pem```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.4 but nodes were created with 2.3.4 I think
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Ubuntu 18.04LTS OS, k8s installed by Rancher
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

I would much rather have a way to modify the run command for etcd inside of Rancher somewhere, even if it were a script I could modify.  I looked, but could not find such a place.

**Comment by dgiebert** [comment]
Same issue with RKE: https://github.com/rancher/rke/issues/2123

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rke/issues/2123
