### ISSUE TITLE
[UI] How to deployment customize Rancher ui  on my server?

### ISSUE THREAD

**Issue by PmcFizz** [rancher/rancher#27479]
How to deployment customize Rancher ui  on my server?

I want kown when i build rancher/ui to static file
then  where i should upload to ?  my nginx folder to visit?

how to modify 
```
Change the value of http[s]://your-rancher:8080/v3/settings/ui-index to the same https://yourserver.com/latest2 URL
```

i dont understand this

**Comment by vincent99** [comment]
You upload it wherever you want, somewhere that is reachable by the rancher server container and the users that are going to hit it  Then set the ui-index setting to tell us where it is.

If you go to `/v3/settings/ui-index` you'll get the API UI and can edit the setting's value.

Or it's in the advanced settings of the Rancher UI, but if you get it wrong you may not be able to get back there without going through the API.

**Comment by PmcFizz** [comment]
@vincent99  hello  now  I upload my rancher/ui to my server  and i can visite it by https://1.2.3.4:1443/latest2/ 
 then  i  go to ``` /v3/settiing/ui-index ```   and see API UI

where  should  I input ``` https://1.2.3.4:1443/latest2/  `` to ?


![image](https://user-images.githubusercontent.com/13403284/84099662-b8002b80-aa3c-11ea-95f7-b8b84e985fb7.png)

can you tell me ? you are good man. 

中美友谊 永久长存

**Comment by PmcFizz** [comment]
I set the ``` /v3/settiing/ui-index `` value 
but when i visit my serve , this console hava err  what 

![image](https://user-images.githubusercontent.com/13403284/84117431-14c30c80-aa64-11ea-8ba6-0d7dff4d5f59.png)

Access to XMLHttpRequest at 'https://10.57.4.2:1443/latest2/translations/zh-hans.json?vmaster-dev' from origin 'https://10.57.4.2' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by PmcFizz** [comment]
I fix it . need nginx set cors.  thanks  
you are good man haha

**Comment by fengjiangwei65** [comment]
> I fix it . need nginx set cors. thanks
> you are good man haha

hello.
I have built rancher ui. And upload to my server.I visite it, The ui is show 404. 
![IMG_20200803_085014](https://user-images.githubusercontent.com/8224202/89136451-72586e80-d566-11ea-89d0-d6b5226065f4.jpg)
Can you help me？

**Comment by PmcFizz** [comment]
hi  brother,  404 is right , the doc is not detailed.  next  you should set ``` /v3/settiing/ui-index``` value

**Comment by fengjiangwei65** [comment]
> hi brother, 404 is right , the doc is not detailed. next you should set ` /v3/settiing/ui-index` value

hi兄弟
你后端服务用的是nginx吗？nginx的配置文件能发一下吗？

**Comment by PmcFizz** [comment]
扣扣交流吧,104-604-8974

**Comment by berlinsaint** [comment]
> 扣扣交流吧,104-604-8974

i have the same problem , i have msg you on qq
