### ISSUE TITLE
System label don't show up if there are user labels

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2747]
Version - Master with latest reskin UI

Steps:
1.  Create build with 3 10-acre hosts
2.  Go to first host's detail page
3.  Click on label tab at bottom (notice 2 system labels are displayed there)
4.  Go to top of details page and click on menu to select edit
5.  Add a label

Results:
The system labels disappeared and the only the user label is displayed

Expected:
System labels should not go away simply because user label was added.

**Comment by vincent99** [comment]
This is the same as https://github.com/rancher/rancher/issues/2342, when you edit the labels you're saving just the new user label and the others are then gone.
