### ISSUE TITLE
Service "pacs" is invalid: spec.clusterIP: Invalid value: "": field is immutable when upgrade app

### ISSUE THREAD

**Issue by kingyzf** [rancher/rancher#27475]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. enter Apps page, Upgdate one app

**Result:**
app page has error:
Failed to install app pacs. Error: UPGRADE FAILED: failed to replace object: Service "pacs" is invalid: spec.clusterIP: Invalid value: "": field is immutable

**Other details that may be helpful:**
I tried to update two app,has the same error,no same error on rancher v2.2

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
rancher:v2.4.4
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by brendarearden** [comment]
Do you know what version of helm these apps are using to install. In rancher 2.4, we introduced helm 3 which performs a 3 way merge patch on upgrades. Some things that helm 2 used to ignore are now considered on upgrade in helm 3. 

Are you attempting to do the upgrade with the `--force` flag by chance?
