### ISSUE TITLE
Deleted service stays on screen

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2748]
Version - Master with latest reskin UI

Steps:
1.  Create a stack and add a bunch of services
2.  Start all services
3.  Delete a service

Results:
The service sits there in a Removed state.  It will eventually delete but not after some time and a reload of the page.  This is both the main stack screen and the stack details screen.

Expected:
Service should not show on UI after delete.

**Comment by deniseschannon** [comment]
Service is immediately removed.

Verified with latest UI (evening 11/24)
