### ISSUE TITLE
[RFE] Ability to change the Rancher UI background color 

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#27480]
Persona: Rancher Operator/Rancher Admin

As a Rancher Operator, I would like to have in the Rancher UI a visual evidence of the environment I am working on, so that I am not running a deployment in a Dev environment, for example.

That's why I would like to have the ability to change the Rancher UI background color to differentiate Dev from Prod environments. gz#10458

**Comment by julien235** [comment]
+1
That's would be helpful

**Comment by alessandrocaprarelli** [comment]
Hi @jambajaar , I had the same need and could not find any way to do this in rancher. So, I made a chrome extension for that.
Source code: https://github.com/alessandrocaprarelli/rancher-io-background-changer
Chrome extension store: https://chrome.google.com/webstore/detail/rancherio-cluster-backgro/knnmikmlodijpadecfmmfcjflebgnlmm

It's very easy to use, just install it, click on its icon and a simple configuration page will show up. Create a new row and define your rules. The `matching string` matches the url. 

Let me know if you find it useful.
