### ISSUE TITLE
Chart Update - Argo CD v2.3.5

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#27485]
Helm 2 Chart - Argo CD v2.3.5
Located in the dev branch of https://github.com/rancher/charts

**Comment by jiaqiluo** [comment]
The new chart is validated in the following setup

- `v2.4-3148-head` with a cluster running k8s `v1.18.3-rancher2-1`
- `master-3159-head` with a cluster running k8s `v1.17.6-rancher2-1`


Steps:
- run Rancher single installed
- add a cluster 
- edit the builtin `library` to point to `dev` branch 
- deploy the app Argo CD `v2.3.5` with all default values 

Results:
- the app is deployed successfully 
- I can access to the UI
- editing and upgrading the app also take effect
