### ISSUE TITLE
[RFE] Oracle Linux 7.8 Support

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#27498]
From our conversation on slack and requesting Oracle Linux 7.8 Support, Testing, Certification.

> Is there anyway of keeping centos, rhel, and oracle linux in step with each other? I know the argument could be made that they are not exactly the same. But from all that I have read, they are binary compataible.
>
> per oracle:
>
> Does Oracle Linux offer Red Hat Enterprise Linux compatibility?  Yes, Oracle has offered application binary compatibility with Red Hat Enterprise Linux for more than ten years, with no reported issues.
>
> You can literally migrate from RHEL or CentOS by changing the repos to point to oracle's yum repos.
>
> If anyone wants to take a look: http://www.oracle.com/us/technologies/027617.pdf gz#10578

**Comment by cocampbe** [comment]
FWIW, I just updated to OL7.8. I updated a HA 3 node rancher cluster. I did notice that docker gets updated from 19.3.1 to 19.3.11. This causes the demon to halt and restart. I then started draining the nodes after noticing the interruption. Other that that, the rancher webui stayed up. If you would like any other info, let me know.

**Comment by sangeethah** [comment]
Certification for Oracle Linux 7.8 tracked in https://github.com/rancher/rancher/issues/27632
