### ISSUE TITLE
Net host container primary_ip is wrong

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#2750]
Hi,

When playing with host networking containers, I realized that the metadata api returns a wrong primary_ip for the container:

```
[root@node25-r1 /]# curl http://rancher-metadata/latest/self
host/
[root@node25-r1 /]# curl http://rancher-metadata/latest/self/container
Not found
[root@node25-r1 /]# curl http://rancher-metadata/latest/self/host/agent_ip
192.168.206.125
[root@node25-r1 /]# curl http://rancher-metadata/latest/containers/test_test_1/primary_ip
10.42.224.150
```

I would expect the host ip to be returned.

**Comment by m4ce** [comment]
Hi,

Is there any way this can be fixed in future rc releases? At the moment, I have to hack this around by looking up the container's host_uuid and then match it under the /hosts endpoint to find the host's 
agent_ip, which results in multiple calls to the metadata api.

Thank you!
Matteo

**Comment by deniseschannon** [comment]
It's on the roadmap to be included in GA, but not sure when it'll make it into the rc releases. We're focused on adding some new features and will start working on bug fixes after the rest of the features are added in.

**Comment by sangeethah** [comment]
Testes with latest build from master:

create a service with network mode set to host.
From within the container ,try to get the ipaddress of the container using - http://rancher-metadata/latest/containers/<container-name>/primary_ip

primary_ip for host containers returns the correct ip now:

<img width="638" alt="screen shot 2016-03-18 at 1 46 59 pm" src="https://cloud.githubusercontent.com/assets/4266958/13891698/ec63a472-ed0f-11e5-9953-0dff0c6a9029.png">
