### ISSUE TITLE
"Failed to obtain metrics. The metrics service may not be available."

### ISSUE THREAD

**Issue by saholman** [rancher/rancher#27515]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Use Rancher to setup a Custom cluster on OpenStack
2. Enable monitoring

**Result:**

All of the monitoring pods seem to be up, but when I try to open the graphs on the cluster summary page they never load. Eventually, a red box with "Failed to obtain metrics. The metrics service may not be available. undefined" appears in the top right a couple of times. I've rebuilt the cluster a few times from scratch with the same result.

I am also unable to view either the prometheus or grafana dashboards. Clicking on the proxy links under the System App just hangs forever.

**Other details that may be helpful:**

None for now.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.4
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom on OpenStack
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4 OpenStack instances with 2 vCPU and 4 GB RAM each. 1 with etc and control plane, 1 with etc, control plane and worker role, and 2 worker only nodes.
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Comment by lperrin-obs** [comment]
I got the same issue using canal as network driver and a custom cluster on Openstack.

**Comment by saholman** [comment]
I can get it to work with flannel, but neither Calico nor Canal work for me even with OpenStack port security disabled.

**Comment by lperrin-obs** [comment]
I solved the problem for me. It was a missing port required in Security Group, UDP/8472
