### ISSUE TITLE
Convoy - services stuck in "activating" when deployed with convoy volume drivers and global flag set.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2751]
Server Build - from master - Nov 18

Set up - 3 hosts
Host1 is not part of the convoy volume driver.
Host2 and Host3 are part of the convoy volume driver storage pool.

Deploy a service with global scale using convoy as volume driver.
1 instance  gets deployed in host2 and host3 as expected.
But there is constant attempt made to deploy another instance which keeps failing because of failing to find a placement.

**Comment by cjellick** [comment]
Spoke with @ibuildthecloud about this bug. We think it is not a blocker for the 11/24 release.

**Comment by cjellick** [comment]
We change convoy-gluster to be global. Should not be able to get into this situation anymore.

**Comment by deniseschannon** [comment]
Verified that new template has the global flag instead of specifying a host.
