### ISSUE TITLE
[Forwardport] - Cluster Controller causes Rancher to OOM when too many resources are called from downstream

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#27520]
**What kind of request is this (question/bug/enhancement/feature request):**

This is to track the fix in master (2.5) for Issue - https://github.com/rancher/rancher/issues/26166

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version a1acca856`

Steps:
Create a downstream cluster 
Create 10k+ secrets in it

Result:
Cluster is accessible.
User is able to list 999 secrets out of 10k+.
