### ISSUE TITLE
Health Check/Scheduling tabs don’t make sense for a standalone container

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2752]
Version - Master

Comment from feedback 11/18 email:
Health Check/Scheduling tabs don’t make sense for a standalone container

Additional information:
I would still keep the ability to choose a specific host.

**Comment by vincent99** [comment]
Health Check makes sense and should work, if the container is failing it should show degraded.

Scheduling makes less sense but does actually work, it will pick a host that meets the rules at the time that you start it..
