### ISSUE TITLE
Prometheus not collecting kubelet_volume_* metrics

### ISSUE THREAD

**Issue by ninjaslothx** [rancher/rancher#27522]
The cluster level monitoring doesn't appear to be collecting the kublet_volume metrics
e,g
kubelet_volume_stats_available_bytes
kubelet_volume_stats_capacity_bytes
kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free
kubelet_volume_stats_inodes_used
kubelet_volume_stats_used_bytes

Is it possible to enable collection of these?

**Comment by intelliguy** [comment]
I have the same problem.

did you solve it? and how?
