### ISSUE TITLE
Update Canal to use Flannel 0.12.0

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27532]
Update Flannel for linux

**Comment by sowmyav27** [comment]
**Verified on 2.4-head - commit id: `4269f6124`**

- Linux and windows cluster - `Kube-flannel - rancher/coreos-flannel:v0.12.0`

**Comment by sangeethah** [comment]
Tested on `2.4-head` - `7f0e24ec9`
Validated the following K8s versions for `canal` and `flannel` network configuration:

- v1.18.3-rancher2-2
- v1.17.6-rancher2-2
- v1.16.10-rancher2-2
- v1.15.12-rancher2-3

Able to bring up cluster with 1 control node , 1 etcd and 2 worker nodes successfully
Automation tests relating to networking and fqdn checks report success.

**Comment by sowmyav27** [comment]
**Validated on 2.4-head - commit id: `7f0e24ec9`**

Validated using k8s versions:
```
- v1.18.3-rancher2-2
- v1.17.6-rancher2-2
- v1.16.10-rancher2-2
- v1.15.12-rancher2-3
```
- Windows cluster comes up fine 3 linux nodes, 3 windows worker nodes
- Validated using both Windows 1809 and 1903 
- Kube flannel on the linux is `rancher/coreos-flannel:v0.12.0`

**Comment by rancher-max** [comment]
#### Validated in airgap setup using v2.4.5-rc6

- Flannel version used in fresh installs and upgraded clusters is `<private_registry>/rancher/coreos-flannel:v0.12.0`
- Validated using all versions v1.18.3-rancher2-2 (upgrade), v1.17.6-rancher2-2 (fresh install), v1.16.10-rancher2-2 (upgrade), and v1.15.2-rancher2-3 (fresh install)
