### ISSUE TITLE
Custom "defaults" support for LB haproxy

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2753]
We have to add support for LB service custom "defaults" on rancher-compose side. Here is a corresponding cattle PR: 

https://github.com/rancher/cattle/pull/1081

**Comment by sangeethah** [comment]
@alena1108 , tested with rancher server version - v0.50-rc1

I tried with the following configuration set in LB service:

"haproxyConfig": {
"global": "group haproxy",
"defaults": "balance first",
},

I see the string passed for "global" and "defaults" are appended to the end in "global" and "default" section.

I don't see the "balance first" take effect , when I try to access the LB url, i still see only round robin access.

**Comment by alena1108** [comment]
@sangeethah there is a bug - we hardcode algorithm in "backend" section, and it overrides the default. Please reopen https://github.com/rancher/rancher/issues/876

**Comment by sangeethah** [comment]
@alena1108 , reopened #876, to track the sepcific issue with balane option.


Tested with rancher server version - v0.50-rc1

Tested for LB services by passing haproxyConfig parameters for format:

"haproxyConfig": {
"global": <values>,
"defaults": <values>,
},

I see the string passed for "global" and "defaults" are appended to the end in "global" and "default" section in haproxy.conf file.

Tested with UI as well as using rancher-compose.
