### ISSUE TITLE
RFE: GitOps-style global/multi-cluster configuration policy management

### ISSUE THREAD

**Issue by jlozada77** [rancher/rancher#27541]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Other details that may be helpful:**
Customer Input:

We need the ability to comprehensively configure and manage all of our Kubernetes clusters and Rancher masters, using a GitOps style of management. A Rancher master should be able to be linked to a Git repository and branch, and any pushes to that branch should trigger immediate reconfiguration.

The configuration and policy itself should be comprehensive: it should cover relevant host configurations like sysctl settings and Docker configuration; RKE configuration (e.g. cluster.yaml); Kubernetes configs like admission controllers, ClusterRoles, ClusterRoleBindings, and 3rd party deployments like Portworx and Gatekeeper OPA. It must also cover Rancher policies like project membership, default resource reservations/requests on namespaces, cluster membership, and global roles. And finally, it should also cover the Rancher master configuration itself: authentication, access control, logging, auditing, monitoring, etc.

In addition to configuration management, we should be able to set policy: K8s NetworkPolicy, Calico NetworkPolicy, RBAC roles, Gatekeeper OPA constraints, etc -- all from a GitOps model. This would allow us to develop, test, preview, and deploy these policies in an automated fashion.

Basically anything that we need to do to configure that is in the scope of Rancher or Kubernetes, should be configurable via GitOps.

Of course, for this to work, we can't depend on copying and pasting things like cluster.yaml files and then updating dozens or hundreds of files when we need to make global or regional changes to our cluster configurations. We should be able to assign resources (clusters, masters, groups, namespaces, projects, etc.) tags/labels, and then use selectors (just like Kubernetes does) to apply policies on those resources. This model might also be paired with a hierarchy of sorts, to make the user experience a little friendlier. But note that hierarchies (e.g. a "tree view") is insufficient as the sole organizational model for configuration and policy.

As it stands today (version 2.4.x), Rancher's overall approach to management is still very fragmented. There's the "master" configuration and policy, the "cluster" configuration and policy, and then all the stuff that Rancher currently doesn't manage directly, like network/calico policy. As Rancher evolves, I would like to see Rancher approach the whole stack as a uniformly covered arena for applying configuration and policy. The Rancher API is a substantial step toward achieving this, but its reach is limited (for example, it can't reach into Kubernetes itself). And an API alone isn't a configuration management system.

**Comment by emctl** [comment]
I was researching this functionality too. It seems at present you need to either use the api or create the clusters outside of rancher then import (which is a bummer).
Having the option to have a cluster repo allowing you to spin up clusters on the fly, paired with fleet to "onboard the cluster to a spec" is very powerful for both ephemeral and production environments imo
