### ISSUE TITLE
There is a blue highlight for the State/Name toggle on main Stack page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2754]
Steps:
1.  Go to main stack page
2.  Click on State or Name button toggle on right side of screen

Results:
A blue highlight appears.  If you click anywhere else on the screen or when you first enter there is no blue highlight. 
![image](https://cloud.githubusercontent.com/assets/11514927/11309658/5187ae5c-8f82-11e5-996c-6f1519c0edde.png)

Expected:
We should get rid of it or keep it there always.

**Comment by vincent99** [comment]
That's the focused element for the browser, so you can navigate with the tab key.. I don't know why it's not on some elements but we should fix those, not remove it from everywhere.

**Comment by vincent99** [comment]
Accessibility is a feature..
