### ISSUE TITLE
Ubuntu 20.04 is not enabled in DO nodetemplate

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#27542]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Currently - Ubuntu 20.04 is not enabled while creating a DO nodetemplate

**Expected Result:**
Ubuntu 20.04 should be enabled in DO nodetemplate

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5-rc4
- Installation option (single install/HA): single

**Comment by westlywright** [comment]
Available in `latest2` and `latest-2.4`, not in an RC yet.

**Comment by sowmyav27** [comment]
**Verified on 2.4-head - ui tag: `latest-2.4`** 

20.04 LTS is enabled while creating a DO node template and user can select and save it.
