### ISSUE TITLE
Upgrade button for apps not working when new template version is available

### ISSUE THREAD

**Issue by angeloudy** [rancher/rancher#27553]
**What kind of request is this (question/bug/enhancement/feature request):**

On rancher UI, you can click on the three dot button you can click on to upgrade your application or view configurations of your application.
When there's a new chart version available, there will be a yellow button saying "Upgrade to xxxx" you can click on.
I have just installed the latest stable version of rancher on a separate kubernetes cluster and I found that button is not working

**Steps to reproduce (least amount of steps as possible):**
1. deploy an app
2. create a new chart version
3. wait for the catalog to be refreshed
4. go to apps, and click on `Upgrade to xxxx`

Expected Result:
A new page where you can reconfigure your app and hit 'Upgrade'

Actual Result:
Nothing happens

**Other details that may be helpful:**

Originally I deployed by apps via terraform rancher2 provider. Later on I found that the same problem exists even if I deploy them by hand

**Environment information**

- Rancher version : v2.4.3
- Installation option: HA, tls=external

**Comment by jsmonet** [comment]
We're experiencing the same issue with rancher: v2.4.4

**Comment by iDiogenes** [comment]
This appears to be a major issue as we are unable to update our private apps. Trying to click on upgrade via the UI does nothing and trying to do it via the cli hangs on installing and in the UI it spews out all sorts of map errors like the following:

```
Wait helm template failed. 2020/06/23 21:50:54 Warning: Merging destination map for chartWait helm template failed. 2020/06/23 21:50:54 Warning: Merging destination map for chart```

The included apps seem fine. 

The version of Rancher I am running is 2.4.4

**Comment by martindanko** [comment]
> We're experiencing the same issue with rancher: v2.4.4

Me too.

**Comment by ChrML** [comment]
Same issue here. Unable to upgrade any app of any type. Downgraded to 2.3.8 with the same catalog and upgrade works again.

**Comment by luizhenmariano** [comment]
Still Happening on 2.5.7
