### ISSUE TITLE
Monitoring - new chart 0.1.1 is  for v2.4.5 and above

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#27551]
The chart `0.1.1` should be available for Rancher `v2.4.5` and above.

**Comment by maggieliu** [comment]
This should be the case already. Based on this PR: https://github.com/rancher/system-charts/pull/250. @jiaqiluo can you check again?

**Comment by jiaqiluo** [comment]
Confirmed that the new version `v0.1.1` show on Rancher `v2.4.5` only 

and Rancher `v2.4.4` will NOT show it even changing the branch of system-chart to `dev-v2.4`
