### ISSUE TITLE
Adding catalog from Helm repository fails to sync

### ISSUE THREAD

**Issue by morot** [rancher/rancher#27557]
I'm trying to sync my helm V2 repo (catalog) in rancher and I got this error:

[INFO] Catalog sync done. 0 templates created, 15 templates updated, 0 templates deleted, 11737 templates failed
 [ERROR] CatalogController nzp [catalog] failed with : Request entity too large: limit is 3145728

---
I have set proxy-body-size: "0" of my ingress controller, didn't help.

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.4` UI: `v2.4.22` |

**Comment by janeczku** [comment]
Reproduced in v2.4.5 while trying to add Chartcenter.io repository.
1. Cluster -> Tools -> Catalog -> Add Catalog
2. Select Helm v3 and enter Catalog URL: `https://repo.chartcenter.io`

**Result:**
- Catalog status stuck on `Syncing catalog xxx` indefinitely
- No templates available to deploy

**Additional Info:**
```
[ERROR] ProjectCatalogController p-lxf9k/rancher-longhorn [projectCatalog] failed with : Request entity too large: limit is 31457288/11/2020 3:14:37 PM 2020/08/11 09:44:37 
[INFO] Updating project catalog rancher-longhorn8/11/2020 3:14:35 PM 2020/08/11 09:44:35 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 31199 templates failed

```

**Comment by sadoMasupilami** [comment]
rancher 2.5: the same happens to me. Maybe the repo is too big?

**Comment by MKlimuszka** [comment]
Assigning to QA to validate in newer versions of Rancher.

**Comment by ronhorton** [comment]
**test result** `2.7-head commit id 4092002`

Added charts repo (full rancher charts repo, but pointing to a different branch)

Repo synced; able to view charts in app from newly added repo.
