### ISSUE TITLE
cattle-cluster-agent does not use internal IP to talk to cluster

### ISSUE THREAD

**Issue by chendo** [rancher/rancher#27555]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Set up a Custom cluster that uses internal IPs to communicate, and public IPs are firewalled
2. Make cattle-cluster-agent run on a node that does not have 6443 access to the control plane's public IP

**Result:**
Rancher shows cluster as 'Unavailable' but node information/etc all work correctly.

Logs from Rancher will emit a line like this:

```
2020/06/10 03:18:48 [ERROR] ClusterController _all_ [user-controllers-controller] failed with : failed to start user controllers for cluster c-fnc9h: failed to contact server: Get https://<control-plane>:6443/api/v1/namespaces/kube-system?timeout=30s: dial tcp <control-plane>:6443: i/o timeout
```

This is due to the node that is running the cluster agent not being able to talk to the control plane over the public interface.

Expected behaviour is it should attempt to reach the control plane over the private interface.

**Other details that may be helpful:**
We have a cluster that uses Zerotier for internal IPs so we don't have to update firewall rules when we add/remove nodes. Cluster worked as normal when it was initially provisioned as cattle-cluster-agent was running on the control plane thus had access to its own public interface on port 6443, however when the agent was scheduled on another machine, This was confusing to figure out until I understood Rancher's cattle/proxying architecture.

My Slack thread is here: https://rancher-users.slack.com/archives/C3ASABBD1/p1591759485362800

**Environment information**
- Rancher version: 2.3.6
- Installation option: Single node

**Comment by mmack** [comment]
Question, i'm searching for the same "feature" right now. How did you "Set up a Custom cluster that uses internal IPs to communicate" ?

I'm on a bare matal hoster spanning a wireguard vpn. But etcd for example is still using the public ip of the nodes, and not the internal... Curious where to change that to the internal ip....

**Comment by chendo** [comment]
@mmack the 'internal IP' option when creating the docker run command for a new cluster is what I'm using. It seems to work fine for us.
