### ISSUE TITLE
Review KDM images are correct source images

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27552]
Some custom images are incorrectly referencing source image repo.

For example [here](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/k8s_rke_system_images.go#L3024) the source for etcd is incorrect:
`Etcd:                      m("quay.io/coreos/etcd:v3.4.3-rancher1"),`

It should be:

`rancher/coreos-etcd:v3.4.3-rancher1`

**Comment by Oats87** [comment]
Is the idea that we want to bypass the `mirror` logic located here: https://github.com/rancher/types/blob/master/image/mirror.go ?

**Comment by PennyScissors** [comment]
This was taken care of in these PRs:
https://github.com/rancher/kontainer-driver-metadata/pull/348
https://github.com/rancher/kontainer-driver-metadata/pull/350

**Comment by deniseschannon** [comment]
We want to bypass the logic only when we build custom images that are suffixed with rancher.

**Comment by soumyalj** [comment]
Tested with master-head(master-e919796c808d0aa643cb3491581bffcd64cfbe56-head) on a HA setup

- Deployed DO clusters with K8s version v18.8-rancher1-1, v1.17.11-rancher1-1, v1.16.15-rancher1-1
- Cluster deployment succeeded.
- Automation tests were run on the three clusters and they succeeded.
