### ISSUE TITLE
Cannot use kubectl in Rancher v2.4.4

### ISSUE THREAD

**Issue by tommy04062019** [rancher/rancher#27578]
**What kind of request is this (question/bug/enhancement/feature request):**

question
**Steps to reproduce (least amount of steps as possible):**
Run any command with kubectl in Rancher UI or copy kube config file for using kubectl

**Result:**
error: You must be logged in to the server (the server has asked for the client to provide credentials)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.4
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):  Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud 
- Kubernetes version (use `kubectl version`):

```

v1.17.6
--



```

- Docker version (use `docker version`): 
```
19.3.11
```

**Comment by rizwan-kh** [comment]
possibly your token has expired, can you try copying the new token and try and share the output?

**Comment by tommy04062019** [comment]
> possibly your token has expired, can you try copying the new token and try and share the output?
> 
> you can get the token in the kubeconfig file in Rancher UI

Hi, thank for replay but I don't think so because this also happens with a new cluster. I realize that when I show kubeconfig from UI , somehow there is no `certificate-authority-data` field in the config. Also in another normal working cluster, I see it like that `certificate-authority: /nonexistent/.kube/certs/ca.crt`.  This file didn't appear on my new cluster. Have any idea?
