### ISSUE TITLE
[Backport - 2.3.9] Update Canal to use Flannel 0.12.0

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#27577]
Update Flannel for linux
Backport for https://github.com/rancher/rancher/issues/27532

**Comment by sangeethah** [comment]
Tested on rancher server version - `v2.3.8` with KDM pointing to `dev-v2.3`

Validated the following K8s versions for canal and flannel network configuration:
- v1.17.6-rancher2-2
- v1.16.10-rancher2-2

Able to bring up cluster with 1 control node , 1 etcd and 2 worker nodes successfully using `Kube-flannel - rancher/coreos-flannel:v0.12.0`.

Automation tests relating to networking and fqdn checks report success.

**Comment by sangeethah** [comment]
`v1.15.12-rancher2-3` is not made available  when testing with `rancher server version - v2.3.8` with KDM pointing to `dev-v2.3`

**Comment by sowmyav27** [comment]
**Validated on `2.3.8` with KDM branch `dev-v2.3`**

- With k8s versions: `v1.17.6-rancher2-2` and `v1.16.10-rancher2-2`
- Windows cluster comes up fine 3 linux nodes, 3 windows worker nodes
- Validated using both Windows 1809 and 1903 
- Kube flannel on the linux is `rancher/coreos-flannel:v0.12.0`

**Comment by sowmyav27** [comment]
**Validated on 2.3.8 with KDM branch dev-v2.3**

- K8s versions: 1.15.12-rancher2-3
- kube-flannel version - `rancher/coreos-flannel:v0.12.0`
- Windows cluster comes up fine 3 linux nodes, 3 windows worker nodes
- Validated using both Windows 1809 and 1903
- Automation checks were fine on the cluster

**Comment by sangeethah** [comment]
`v1.15.12-rancher2-3` is available now when testing with rancher server version - v2.3.8 with KDM pointing to `dev-v2.3`

Able to bring up cluster with 1 control node , 1 etcd and 2 worker nodes successfully using Kube-flannel - rancher/coreos-flannel:v0.12.0.

Automation tests relating to networking and fqdn checks report success.
