### ISSUE TITLE
[RFE] AWS EKS Tags on cluster and other resources

### ISSUE THREAD

**Issue by vikas027** [rancher/rancher#27583]
As of now (Rancher 2.4.3), there is no option to specify tags on the EKS cluster and the autoscaling group (which can further tag the instances too). It would be good to have tags in place as they are heavily used in automation.

Recommended approach (IMHO) - Ask for a set of tags at the time of creating a cluster and then propagate them too all resources like EKS Cluster, Autoscaling groups, etc.

**Comment by petertang2012** [comment]
In the same boat here.
I am using terraform for eks cluster provisioning via `rancher2_cluster` resource, but it neither allows tagging via `eks_config` nor does it return workers' autoscaling group arn for further processing, which makes putting automation tags on resources very difficult.

**Comment by vikas027** [comment]
Anyone?
