### ISSUE TITLE
pod definitions assume capabilities

### ISSUE THREAD

**Issue by haircommander** [rancher/rancher#27587]
CRI-O 1.18 dropped the capabilities NET_RAW and MKNOD by default, as they're not needed for the majority of containers, and are pretty powerful. However, when running rancher with CRI-O 1.18, a user ran into [this](https://github.com/cri-o/cri-o/issues/3872) issue, which revealed there were some capabilities assumed on behalf of a rancher pod that were dropped. Since CRI-O tries to run as secure as possible by default, I do not think we should readd then capability, but rather I think it would be better if pods that need a capability request them.

**What kind of request is this (question/bug/enhancement/feature request):**
I suppose a bug?

**Steps to reproduce (least amount of steps as possible):**
install rancher with cri-o 1.18

**Result:**
```
2020/05/20 08:38:26 [INFO] Rancher version v2.4.3 (684884c) is starting
2020/05/20 08:38:26 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features:}
2020/05/20 08:38:26 [INFO] Listening on /tmp/log.sock
2020/05/20 08:38:26 [INFO] Starting API controllers
2020/05/20 08:38:26 [INFO] Running in clustered mode with ID 10.85.0.52, monitoring endpoint cattle-system/rancher
2020/05/20 08:38:27 [INFO] Starting API controllers
2020/05/20 08:38:27 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=Role controller
2020/05/20 08:38:27 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller
2020/05/20 08:38:28 [FATAL] error running the jail command: exit status 2

From a debug pod:

tar: ./urandom: Cannot mknod: Operation not permitted
tar: ./zero: Cannot mknod: Operation not permitted
tar: ./tty: Cannot mknod: Operation not permitted
tar: ./full: Cannot mknod: Operation not permitted
tar: ./random: Cannot mknod: Operation not permitted
tar: ./null: Cannot mknod: Operation not permitted
tar: Exiting with failure status due to previous errors
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- ~Docker~ CRI-O version (use `crio version`):

```
[kube@k8s-master-0 ~]$ crio --version
crio version 
Version:       1.18.1
GitCommit:     5cbf694c34f8d1af19eb873e39057663a4830635
GitTreeState:  clean
BuildDate:     2020-06-08T13:01:11Z
GoVersion:     go1.13.11
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic```
```

**Comment by markc43** [comment]
Background: #27160

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/27160
