### ISSUE TITLE
No way to start/stop sidekicks from Group Stack view

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2758]
Version - Master

Steps:
1.  Create a service with at least 1 sidekick
2.  Go to Host screen and select the Group Stack & sidekick view
3.  Try to start service and sidekick

Results:
Can start the service but there is no way to start the sidekick.  Same with stop.

Expected:
I'm not sure if when I start the service the sidekick should automatically start, or if the sidekick should have it's own menu.

**Comment by vincent99** [comment]
You can right click on them now, though there's no way you'd know that..

**Comment by cjellick** [comment]
ZOMG! YOU CAN RIGHT CLICK A SIDEKICK???

**Comment by deniseschannon** [comment]
Verified with latest UI (11/24 evening) that I'm able to right click and find options on sidekicks to start or stop services.
