### ISSUE TITLE
Load Balancers sits in degraded before coming active

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2759]
Version - Master

Steps:
1.  Create a stack
2.  Add a service
3.  Add a LB and make the service your target
4.  Start service
5.  Start balancer

Results:
The Load Balancer goes from Activating to Degraded then it becomes active.

Expected:
Shouldn't degrade before becoming Active.  Makes you think something is wrong when it's simply still starting up.

**Comment by vincent99** [comment]
I guess we can maybe show "Initializing" if all the containers are in that state, but at what point do you decide to call it degraded?

**Comment by vincent99** [comment]
This logic is now in the API, but services are marked initializing if any containers are in initializing.

**Comment by alena1108** [comment]
@tfiduccia please reassign the bug to me if API misbehaves

**Comment by tfiduccia** [comment]
Version - master UI 3/18
Verified fixed
