### ISSUE TITLE
[2.4.4] Network request failed

### ISSUE THREAD

**Issue by superxor** [rancher/rancher#27607]
v2.4.4
Custom Cluster

Since the upgrade to 2.4.4 we have A LOT of network request failed when clicking anywhere in the UI and issues with hanging kubectl commands.
Sadly the rancher logs show nothing but : 2020/06/16 14:26:54 [ERROR] Unknown error: context canceled

Any ideas on this?

**Comment by superxor** [comment]
I'm still seeing this a lot, the webui becomes useless. We have no issues with any networking for any software but rancher ui

**Comment by htwalid** [comment]
any update about this issue ? i have the same
