### ISSUE TITLE
etcd snapshot restore downloaded from StorageGRID S3 bucket fails 

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#27608]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug/feature request

**Steps to reproduce (least amount of steps as possible):**
Configure an S3 backup to a NetApp StorageGRID bucket
Attempt to restore from a backup stored in the s3 location

**Result:**
The restore will fail with an empty zip file and the following error:
   `Unable to decompress [/backup/$FILE_NAME.zip] to [/backup/$FILE_NAME]: zip: not a valid zip file`

**Other details that may be helpful:**
From the view of the S3 provider, we see a download successfully filled.
From RKE we see:
```
DEBU[0000] reading s3-endpoint-ca from [crt]
INFO[0000] Successfully downloaded [downstream-clusters/$FILE_NAME.zip]
INFO[0000] Decompressing etcd snapshot file [$FILE_NAME.zip]
FATA[0000] Unable to decompress [/backup/$FILE_NAME.zip] to [/backup/$FILE_NAME]: zip: not a valid zip file
```

Since we see a Successful download on the Rancher side, but an unsuccessful decompression, I traced the code and this is what I think is going on:

**Hypothesis:**
[`DownloadS3Backup`](https://sourcegraph.com/github.com/rancher/rke-tools/-/blob/main.go#L763) from [rke-tools main.go](https://sourcegraph.com/github.com/rancher/rke-tools/-/blob/main.go) creates a file out of the first 0 bytes of the snapshot stored in StorageGRID (which, of course, can not be decompressed) and so the restore fails.

**My reasoning:**
It looks like [`DownloadS3Backup`](https://sourcegraph.com/github.com/rancher/rke-tools/-/blob/main.go#L763) calls [`downloadFromS3WithPrefix`](https://sourcegraph.com/github.com/rancher/rke-tools/-/blob/main.go#L982) to download the file.  `downloadFromS3WithPrefix` will use [`FGetObject`](https://sourcegraph.com/github.com/rancher/rke-tools/-/blob/main.go#L1004) which uses [`fGetObjectWithContext`](https://sourcegraph.com/github.com/rancher/rke-tools/-/blob/vendor/github.com/minio/minio-go/api-get-object-file.go#L41) to copy a file of size `n` from the bucket/object depending on the md5sum it retrieves with [`objectStat`](https://sourcegraph.com/github.com/rancher/rke-tools/-/blob/vendor/github.com/minio/minio-go/api-get-object-file.go#L76).

According to someone from NetApp, StorageGRID does not have an API call for this, and we're not yet sure if this is a standard for s3.  If the md5sum that ends up in memory indicates an `objectStat.Size` of 0 bytes this would lead to the [`CopyN`](https://sourcegraph.com/github.com/rancher/rke-tools/-/blob/vendor/github.com/minio/minio-go/api-get-object-file.go#L109) 'successfully' copying 0 bytes into the part file, and creating the empty .zip, which will pass all the checks until [`isCompressed`](https://sourcegraph.com/github.com/rancher/rke-tools/-/blob/main.go#L799) actually attempts to decompress it.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.5
- Downstream cluster deployed with StorageGRID s3 backend

gzrancher/rancher#10363

**Comment by Tejeev** [comment]
This may affect a larger subset of S3 providers and only work with Minio.
See Issue #22356 where our snapshot restore fails with Hitachi S3

**Comment by superseb** [comment]
Need to check if this is the same as https://gitlab.com/gitlab-org/gitlab-workhorse/-/issues/264

**Comment by soumyalj** [comment]
- **Tested on v2.4-head(3e543f7c4)**. Verified etcd snapshot restore is functional using StorageGRID bucket

Steps:
1. Create a DO cluster configuring  S3 backup to a NetApp StorageGRID bucket as user1
2. Create a workload test1 and take a snapshot "snp1"
3. Create a workload test2 and take a snapshot "snp2"
4. Restore to snapshot "snp1". Restore was successful. 
5. Deletion of snapshots was also functional. 

Note: rke-tools version used on the v2.4-head-setup : "rancher/rke-tools:v0.1.62"

**Comment by soumyalj** [comment]
- **Tested on master-head(e20f472d4)** 

Steps:
1. Create a DO cluster configuring  S3 backup to a NetApp StorageGRID bucket as user1
2. Create a workload test1 and take a snapshot "snp1"
3. Create a workload test2 and take a snapshot "snp2"
4. Restore to snapshot "snp1".

Restore failed with the below error on master-head
```
Failed to download etcd snapshot from s3, exit code [1]: time="2020-07-27T18:52:49Z" level=fatal msg="Unable to decompress [/backup/c-hfjpr-ms-kn9l5_2020-07-27T18:14:10Z.zip] to [/backup/c-hfjpr-ms-kn9l5_2020-07-27T18:14:10Z]: zip: not a valid zip file"
```

Note: rke-tools version used on the master-setup : "rancher/rke-tools:v0.1.61"

**Comment by soumyalj** [comment]
**Validated on master-head(c53a66e22) using rke version : v1.2.0-rc4**

**Steps:**

1. Create a DO cluster configuring S3 backup to a NetApp StorageGRID bucket as user1
2. Create a workload test1 and take a snapshot "snp1"
3. Create a workload test2 and take a snapshot "snp2"
4. Restore to snapshot "snp1". Restore succeeds without any errors
5. Deletion of snapshots is also functional

rke-tools version used : rancher/rke-tools:v0.1.62
