### ISSUE TITLE
Switch from Rancher Generated Certificates (Default) to Letsencrypt

### ISSUE THREAD

**Issue by dbecher-ito** [rancher/rancher#27604]
**What kind of request is this (question/bug/enhancement/feature request):**
Question/Bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy rancher with Rancher Generated Certificates (Default) with OLD_URL
2. Then create letsencrypt Issuer and use it to issue certificate for domain
3. Switch OLD_URL at https://<OLD_URL>/g/settings/advanced to NEW_URL

**Result:**
Everything working fine, but the by Rancher generated Kubeconfig file does not work anymore:
`Unable to connect to the server: x509: certificate signed by unknown authority`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 1.17.6

How can I correct this error with the Rancher Kubeconfig file not working anymore?

**Comment by superseb** [comment]
Most (if not all) occurrences of this change are described in https://github.com/rancher/rancher/issues/14731 (or linked issues). Rancher needs to be configured according to the chosen TLS setup as described in https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/helm-rancher/.
