### ISSUE TITLE
Rancher container memory leak when runnning synch against Azure AD

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#27605]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create cluster with auth configured to Azure AD with users in large number of groups (900ish), where the AD may be throttling requests.

**Result:**
We see what appears to be an Authentication synch related memory leak in v2.4.3 when the `auth-user-info-resync-cron` cron runs.
With a sync every hour the usage went from 380>800>1000>1200.

We don't see this memory increase in the other clusters which are at 2.2.9.

**Other details that may be helpful:**

**Environment information**
Architecture:
Provider is Azure AD
Built at v2.2.9 with RKE v0.2.9
After 5 days upgraded to 2.4.2
After a few more days upgraded to 2.4.3.
There is no network isolation on this cluster.
![image](https://user-images.githubusercontent.com/8906089/84776019-b48a1880-afd7-11ea-8151-a488e019e221.png)

gzrancher/rancher#10142

**Comment by Tejeev** [comment]
https://github.com/Azure/go-autorest/pull/432

**Comment by izaac** [comment]
Validated P1 test cases functionality in Rancher `v2.4.5-rc6` HA k8s setup.
Including Users and groups working cluster and project memberships. Site access.

**Comment by izaac** [comment]
Validated Rancher `master-head (06/16/2020)` commit id: 322f55fef
Basic functionality checks of users/groups, site access. Project membership.

**Comment by soumyalj** [comment]
Validated the upgrade use case on a upgrade from v2.4.4 to v2.4.5-rc6
1. Created a setup with Rancher v2.4.4. 
2. Enabled Azure AD auth and set site access to Allow members of Clusters, Projects, plus Authorized Users and Organizations 
3. Created 2 clusters cluster1 and cluster2
4. Provide access to  "user1" at cluster level and project level for "cluster1" as an admin
5. Provide access to "group1" at cluster level and project level for "cluster2" as an admin
6. Login as "user1" and verify that user1 has access to only cluster1
7. Login as a user in "group1" and he has access to ony cluster2
6. Upgrade rancher to v2.4.5-rc6
7. Verify that user1 and user in the group have the right access permissions
8. Add new users/group to the clusters and verify the users have the right permissions as expected.

**Comment by Tejeev** [comment]
On testing [v2.4.5-rc6](https://github.com/rancher/rancher/releases/tag/v2.4.5-rc6), we see the memory leak resolved.  Thank you!

**Comment by Tejeev** [comment]
In case this ever comes up, we noted a similar memory issue in one cluster at 2.2.9. Again the cron sync was set to every 4 hours (and has now been reset to 0:00)
That cluster showed a gradual increase over a few weeks, with a much more rapid increase in the last week. It is assumed that it's the same issue but it indicates that it happens in certain circumstances which are not clear on pre 2.4 also.
