### ISSUE TITLE
Running standalone rancher in k8s 

### ISSUE THREAD

**Issue by plejik** [rancher/rancher#27603]
**question**
Hi 
I have some problem i wanna create rancher in k8s but not to manage this cluster but manage other cluster. But rancher required cluster-admin role, could it be skipped or fixed cause i don't wanna rancher make any changes to my parent cluster ? 

Log always like this an i have crashLoopback 

> customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:dev:ranche" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope

**Environment information**
- Rancher version 2.4.4:
- Installation option (single install on EKS ):

**Comment by superseb** [comment]
The reason for the HA install is to make it HA and scale better, using embedded will seriously limit scalability and manageability of Rancher, but you can still force it if you want to, see https://github.com/rancher/rancher/issues/16102#issuecomment-429306953

**Comment by plejik** [comment]
Thx
