### ISSUE TITLE
Scheduled CIS Scan option is disabled on the UI when a user edits a cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#27619]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster through API
- Wait for the cluster to come up successfully.
- Do an Edit on the cluster
- The Scheduled CIS Scan option is disabled on the UI

<img width="1430" alt="Screen Shot 2020-06-16 at 2 05 29 PM" src="https://user-images.githubusercontent.com/26032343/84832801-c624ed80-afe2-11ea-8308-4fd928bd5574.png">

**Expected Result:**
Scheduled CIS Scan option should be enabled

**Other details that may be helpful:**
**Note:** - This is not always reproducible.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5-rc6
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom RKE
- Kubernetes version (use `kubectl version`):

```
1.18.3
```

**Comment by westlywright** [comment]
The cluster in question was a windows cluster. CIS is disabled for windows clusters.
