### ISSUE TITLE
deploy cluster error

### ISSUE THREAD

**Issue by hendidediaodiao** [rancher/rancher#27626]
*Describe your issue here*

I | embed: rejected connection from "172.16.14.215:54576" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kube-ca\")", ServerName "")

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.4` UI: `v2.4.22` |
|Route|`undefined`|

**Comment by sbhnet** [comment]
Confirm the problem

**Comment by superseb** [comment]
The main issue for this error is re-using nodes without cleaning properly, causing old data to be used for communication. See https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/ what locations need to be cleaned. If this doesn't help, please provide exact steps to reproduce.
