### ISSUE TITLE
Convoy - Service stuck in "activating" state forever when it is not able to make a decision on which volume driver to pick.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2762]
Server version - Build from master

Have to more than 1 storage pools created .

Have a volume say "volume1" in both storage pools.

Create a service with  DataVolumes as below without specifying volume driver as follows:
``` 
"volume1:/<dir>" 
```
This results in service  stuck in "activating" state forever when it is not able to make a decision on which volume driver to pick. Containers keeps being created and purged.

In such cases , API should be able to error out.

**Comment by cjellick** [comment]
Won't fix. 

This is just the nature of services and other errors when creating/scheduilng/starting instances as part of a service will result in the same stuck in activating behavior. Adding API validation wouldn't help as there are other ways to get into this scenario that the api validation wouldn't catch.

There is at least some feedback in the UI as to what is going one:
![screen shot 2016-03-10 at 3 28 11 pm](https://cloud.githubusercontent.com/assets/2473240/13686914/84f03912-e6d5-11e5-9383-bedfd8763568.png)
