### ISSUE TITLE
Authentication Change: User ID Construction

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27637]
Design Discussion Summary:

ID derived from auth provider:: ex => Github-<username> is the actual user name of the resource
	○ Upgrade path: existing user will still be using "U-xxxxx", new users will start with "Provider"- "Username"
	○ If you downgrade: you need to recreate the users
	○ Impact will be the RBAC UI Screen
	○ SAML might need to be configurable

**Comment by ctrox** [comment]
We are using Keycloak as the auth provider and our user IDs are currently as described `u-<random-string>`. Does this change mean that it will be something like `Keycloak-<email>` (We have `email` defined as the user name mapping)?

What confuses me a bit is that as of Rancher 2.4.8 the user ID is a random generated string even though in the Keycloak auth settings [we have set `UID` to map to `email`](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/keycloak/#configuring-keycloak-in-rancher). Is this UID something else or is that a bug?

In general, I think it would be great if the IDs are either "Provider-Username" as described here or even better fully configurable so we can set it to be just `email`. It would make it way more user friendly for example if you create custom `RoleBindings` and you need to enter some users as the subjects.

**Comment by dramich** [comment]
@ctrox This is on hold and probably won't happen as written in the original issue. The problem is the characters allowed in the name of a resource are restricted but most providers would break these restrictions, like email since `@` is not an allowed character. We are working on additional changes to make the mapping of `u-xxx` to `provider-id` easier, for example https://github.com/rancher/rancher/issues/17358

**Comment by ctrox** [comment]
Ok yeah I get that you need some kind of ID which is a valid kubernetes resource name and I'm totally fine with that. My only gripe is that the User ID is also used as the user name in the authentication proxy. Making a request to the `TokenReview` endpoint of a Rancher cluster with my personal account, I get back the following:

```
"spec": {
  "token": "kubeconfig-u-spvb6u7ap2.c-xx:xx"
},
"status": {
  "authenticated": true,
  "user": {
    "username": "u-spvb6u7ap2",
    "groups": [
      "keycloak_group:///xx",
      "system:authenticated"
    ]
  }
}
```

The [userinfo struct](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#userinfo-v1-authentication-k8s-io) even has a field `uid` which I think would be a better fit here whereas the `username` would be the username of rancher.
