### ISSUE TITLE
Validate OL 7.8

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27632]
Validate OL 7.8

gzrancher/rancher#10733

**Comment by leflambeur** [comment]
Following this one for 10733

**Comment by superseb** [comment]
This is identical to https://github.com/rancher/rancher/issues/27498

**Comment by aaronRancher** [comment]
Docker install using Rancher curl works after enabling the `container-selinux` package
```
yum-config-manager --enable ol7_addons
curl -sSL https://releases.rancher.com/install-docker/19.03.11.sh |sh
```

Validated OL 7.8 with Selinux enabled on `Permissive` and `Enforcing`
```
$ cat /etc/selinux/config

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=enforcing
# SELINUXTYPE= can take one of three values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected.
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted
```

Validated with existing automation on HA local cluster and custom cluster
![Screen Shot 2020-07-08 at 3 31 47 PM](https://user-images.githubusercontent.com/57409052/86980801-adb77700-c139-11ea-8b65-3c4d3843743f.png)

K8s: `v1.18.3`
Docker: `19.3.11`
OL 7.8 Kernel: `4.14.35-1902.300.11.el7uek.x86_64`
