### ISSUE TITLE
UI does not list the volume after it gets created .

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2763]
Server version - Build from master

Create a volume from "Infrastructure->storagepool->"Add Volume" option.

The volume created is not listed in the UI.

I see this volume being  created in volumes DB in "requested" state.

**Comment by vincent99** [comment]
@cjellick There are no change events of any kind sent after creating a volume for me to know where it went

**Comment by westlywright** [comment]
@cjellick @vincent99 was there any update on this?

**Comment by vincent99** [comment]
@ibuildthecloud This is still true, change events aren't sent when `storagePool.volumeIds` (and also `volume.mounts`) change.

**Comment by ibuildthecloud** [comment]
Closing, same issue as https://github.com/rancher/rancher/issues/6129
