### ISSUE TITLE
System project workloads fail to come up for 1.18.4, 1.17.7 and 1.16.11 clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#27639]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy 1.17.7 and 1.16.11 k8s version cluster on latest 2.4-head 
- Corends, default http backend workloads fail to come up
- Logs of coredns pod

```
[INFO] SIGTERM: Shutting down servers then terminating
.:53
2020-06-17T23:39:26.195Z [INFO] plugin/reload: Running configuration MD5 = 68ad62e82bb7a01ce4a04dd06bd0bf2c
2020-06-17T23:39:26.195Z [INFO] CoreDNS-1.6.2
2020-06-17T23:39:26.195Z [INFO] linux/amd64, go1.12.8, 795a3eb
CoreDNS-1.6.2
linux/amd64, go1.12.8, 795a3eb
```

**Expected Result:**
System project workloads should come up successfully

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4-head commit id `143066942`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE do
- Kubernetes version (use `kubectl version`):

```
1.17.7 and 1.16.11
```

**Comment by kinarashah** [comment]
- compared the addon template and service options passed for 1.17.7 with 1.17.6 to make sure there wasn't anything missing there. 
- this issue reproduces with RKE standalone as well, so can isolate out KDM
- any user workload also fails to comes up (runs, crashes in a loop) so checked kubelet logs and kubelet was complaining about `ip command not found` ... after installing and restarting kubelet, they start working 
- seems like only coredns and metrics-server are the 2 deployments that are crashing. they're not able to reach out to api-server. In case of coredns, it gives me a plugin loop error 
`[FATAL] plugin/loop: Loop (127.0.0.1:52028 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 1104653840390867276.347750676145298530."` 
I checked the `coredns` configmap and kubelet `resolv.conf` param, but both seem to be ok. Need to look more into what's missing

**Comment by sowmyav27** [comment]
1.18.4 cluster also fails to come up with a similar behavior
Logs of coredns pod
```
.:53
[INFO] plugin/reload: Running configuration MD5 = 7b85fbe9b4156cf64b768261d4ea6e3b
CoreDNS-1.6.9
linux/amd64, go1.14.1, 1766568
[FATAL] plugin/loop: Loop (127.0.0.1:57249 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 4881447015240673956.7286356585950878771."
```

**Comment by sangeethah** [comment]
@galal-hussein's comments:
I must mention that i think the issue is related to the upgrade happened to hyperkube image, since there was some tools missing, we should compare the upstream images and see what got changed

**Comment by superseb** [comment]
Yep, we got the new Debian 10 bubstder

```
~$ docker run -ti --entrypoint bash gcr.io/google_containers/hyperkube:v1.17.6 -c 'cat /etc/os-release'
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
~$ docker run -ti --entrypoint bash gcr.io/google_containers/hyperkube:v1.17.7 -c 'cat /etc/os-release'
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

PRs incoming to fix all the changes in the image

**Comment by sowmyav27** [comment]
Reopening this issue as this was reverted.

**Comment by sowmyav27** [comment]
**Verified on 2.4.5 and 2.4.4 pointing to dev-v2.4**
- Deployed clusters (all network providers) with K8s Versions - 1.18.6, 1.17.9 and 1.16.13 and run network related test cases- on 2.4.5 pointing to dev-v2.4 (1 etcd, 1 control plane and 2 worker nodes)
- - Upgrade Testing 
```
- Deploy clusters (all network providers) with K8s Versions - 1.18.3, 1.17.6 and 1.16.10 on 2.4.5
- Run pre upgrade checks
- Upgrade (change KDM 2.4.5 pointing to dev-v2.4)
- Upgrade K8s versions to new versions 
- Run post upgrade checks
- Checks were all good.
```
- Deploy Windows 1903 clusters - 1.18.6, 1.17.9 and 1.16.13 (3 linux nodes, 3 windows worker nodes); Flannel version on windows v0.12.0-rancher1-dirty
- CIS scan works fine on all clusters

On 2.4.4 and 2.3.8 similar checks ^^^ were done.  For 2.3.8 - dev-v2.3 was used to checks the latest k8s versions.
