### ISSUE TITLE
Cannot get Gitlab auto devops to work on Rancher Managed Cluster 

### ISSUE THREAD

**Issue by obieeclark** [rancher/rancher#27644]
I am trying to setup auto devops with with Gitlab using the instructions at:

https://rancher.com/blog/2019/connecting-gitlab-autodevops-authorized-cluster-endpoints
https://docs.gitlab.com/ee/user/project/clusters/add_remove_clusters.html

and am having issues with the user account not having permissions to create a namespace.  This fails if I use a Rancher managed ID or if I use the instructions GITLAB gives.
I am using GITLAB 13.0.3-ee

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
|Route|`undefined`|

**Comment by idears-org** [comment]
Do you have any solution on this?

I'm facing the same issue, and found that it still goes failed even I manually create the gitlab-managed-apps namespace.

Seems it's an issue related to ACE

How to disable ACE and enable directly connect to k8s cluster?

**Comment by idears-org** [comment]
Well I can setup k8s integration to gitlab now by using the cert and token from https://docs.gitlab.com/ee/user/project/clusters/add_remove_clusters.html
And using ip address not domain to connect to k8s.

Now the question is I can't install all of the gitlab-managed-app(only helm and gitlab-runner can be installed)
