### ISSUE TITLE
Ability to prevent `yum -y update` execution during node driver provisioning of RHEL/CentOS hosts

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#27646]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Steps to reproduce (least amount of steps as possible):**

The rancher-machine provisioner code for RHEL/CentOS hosts currently performs `sudo -E yum -y update -x docker-*` during node provisioning (https://github.com/rancher/machine/blob/f675ca219acb7402720f060432bc81e9032f6e85/libmachine/provision/redhat.go#L155). Where users are pre-configuring an OS template with Docker and dependencies pre-installed and want a deterministic package state, according to the configured OS template, the `yum update` here prevents this.

(This is noted in https://github.com/rancher/rancher/issues/22048 which is a single issue for two separate enhancement requests).

**Environment information**
- Rancher v2.4.3

gz#10649

gz#13674

gz#13530

**Comment by luthermonson** [comment]
Discussion today about this, basics here should be a skip provision for the create command which will bypass all provisioning and docker installation. needs to be documented that the expectation is the user has already pre-installed everything they need to have installed docker themselves.

**Comment by PennyScissors** [comment]
To test this, you will need an image that has docker pre-installed (ideally using our script `https://releases.rancher.com/install-docker/19.03.sh`). I have 2 AMIs already setup for ubuntu and redhat, so if you want to use those let me know.
Additionally, you will need to enter `"none"` as the Docker Install URL in the Engine Options when creating a node template.

**Comment by slickwarren** [comment]
I was able to test the following on rancher v2.5-head (e3128c99ce74dc41ce319a42b21ebc829c74a84d):

* custom RHEL with docker v20.10, Docker Install URL left as default value ->  provisioned successfully
* custom RHEL with docker v20.10, changed Docker Install URL to `none` -> provisioned successfully
* Ubuntu with docker 19.03., Docker Install URL = `none` -> unable to provision successfully (expected)
* Ubuntu with docker 19.03 , Docker Install URL left as default value -> provisioned successfully

**Comment by sowmyav27** [comment]
Reopening for validation to be done on master-head

**Comment by slickwarren** [comment]
I also was able test the following on rancher master-head (68f4fa8e06d5d3850d68e8489691a7efbc612982):

* custom RHEL with docker v20.10, Docker Install URL left as default value -> provisioned successfully
* custom RHEL with docker v20.10, changed Docker Install URL to none -> provisioned successfully
* Ubuntu with docker 19.03., Docker Install URL = none -> unable to provision successfully (expected)
* Ubuntu with docker 19.03 , Docker Install URL left as default value -> provisioned successfully
