### ISSUE TITLE
Memory reported in workload metrics is lower than actual

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/rancher#27640]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**details**
The memory usage shown in a pods workload metrics appears to be pulled from the cAdvisor metric `container_memory_working_set_bytes`, which doesn't necessarily reflect the total memory usage of a pod.

**Other details that may be helpful:**
`container_memory_usage_bytes` may be a better metric, it is a sum of `container_memory_rss` + `container_memory_cache` + `container_memory_swap`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.4 and below

gz#10641

**Comment by MKlimuszka** [comment]
Closing as this was reported in a currently unsupported version.
