### ISSUE TITLE
Sidekicks get placed in different host from primary container when sidekick and primary service uses different storage pools. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2765]
Server version - Latest Build from master

Steps to reproduce the problem:

Set up has 5 hosts - h1,h2,h3,h4,h5 
Set up has 2 storage pools - "myconvoy" and "myconvoy2"
  "myconvoy" - h1 , h2, 
  "myconvoy2" - h4, h5,h2

Created a service with primary service using volume driver - "myconvoy" and sidekick using  volume driver - "myconvoy2".

Containers of the Primary service and sidekick services belonging to the same deployment unit gets deployed in different hosts.

Expected behavior:
All containers from primary and sidekick should get placed in host that have access to both volume drivers.

**Comment by cjellick** [comment]
@sangeethah since we made convoy-gluster and convoy-nfs global, you can no longer get into this situation. Are you comfortable closing?

**Comment by sangeethah** [comment]
@cjellick  yes,this use case is not relevant anymore since we have made  convoy-gluster and convoy-nfs global.
