### ISSUE TITLE
[RFE] - Release a digests file along with a Rancher release

### ISSUE THREAD

**Issue by vikas027** [rancher/rancher#27662]
In Rancher releases, please release a digests file of the docker images as well as it was done in [v1.6.28](https://github.com/rancher/rancher/releases/download/v1.6.28/rancher-images-digests.txt) (and lower).

This file is missing in v1.6.29 and v1.6.30.

Cheers,
Vikas

**Comment by deniseschannon** [comment]
This has been added for both releases.
