### ISSUE TITLE
[UI] show docker version and kernel version on every host in infrastructure

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#2766]
Hi,

This is related to my question in the [rancher forum](http://forums.rancher.com/t/what-if-my-application-has-a-minimum-docker-version-requirement/1033/1)

As a Rancher administrator, I would like to see the docker-engine version and kernel version on each host when viewing the infrastructure > hosts.

This is important for an admin to react on docker version sprawl, as this is inevitable after some time of adding hosts in an environment in rancher, you will have several different docker engines versions on each host. Some containers may behave differently on different engines and kernels. 

I expect Rancher being a "docker container as a service" to show the docker engine version on each host as this is at least as important as the other info shown (mem, cpu etc). Right now one has to click on each host to find out...

thanks

**Comment by cloudnautique** [comment]
@will-chan this is already done at the host level. It would be a ui change to display it differently.

**Comment by will-chan** [comment]
Nice.

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/12156958/5b1ffbbc-b48b-11e5-9f51-8e5c4d1c2181.png)

**Comment by demarant** [comment]
@vincent99 that looks good. maybe we should use the :whale: instead of the cog for docker version ;) thanks

**Comment by vincent99** [comment]
We'll put a docker logo into the icon don't, it just isn't there yet.

**Comment by tfiduccia** [comment]
Version - Master Jan 07
Verified fixed - Cog icon still there.

**Comment by demarant** [comment]
thanks for this.
@vincent99 
I can see font-awesome does not have a whale or docker icon in the brand icons set... not so important just aesthetics :) maybe this one can do https://github.com/wesbos/Font-Awesome-Docker-Icon if easy to add..
