### ISSUE TITLE
KEv2 Add secrets encryption to eks-controller

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#27673]
Add secrets encryption (KMS) to eks-controller

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `5c1c2c5d7`**

- User is able to enable secret encryption using `kmsKey` via a hosted EKS cluster
- User is able to create secrets and use it with workload as an env variable/volumes.
- Access the env variable to volumes on the workload
- `Decrypt` events are seen in `Cloud Trail` related to decrypting the secrets
