### ISSUE TITLE
Rancher2.4.5 integrate gitee to built a pipeline encounter an error  'TestAndApply Error'

### ISSUE THREAD

**Issue by 510mt** [rancher/rancher#27681]
**What kind of request is this (question/bug/enhancement/feature request):**
bug/enchancement 🐞

**Steps to reproduce (least amount of steps as possible):**
first step: everything done well when i configure the pipeline with the gitee(private gitlab enterprise installation)   
second step: when i click the button 'Authenticate', it redirect to the authorization page of gitee , at this step, it still ok, but when i finished authenticate, go back to the rancher pipeline setting page, it just show me an error '{"status":"404","error":"Not Found"} '

**Result:**
TestAndApply Error
{"status":"404","error":"Not Found"}: undefined

**Environment information**
- Rancher version : 2.4.5
- Installation option : single
- K3S version: 1.18.3+k3s1 (single)
- Docker version: 19.03.11

**Comment by ardylin** [comment]
I have this problem too

Result:
TestAndApply Error
failed to decode the config, error: 1 error(s) decoding: * 'ManagedFields[0].Time' expected a map, got 'string'

Environment information
Rancher version : 2.4.5
Installation option : HA
RKE version: 1.1.3
Docker version: 18.9.2

**Comment by yuedefeng** [comment]
failed to decode the config, error: 1 error(s) decoding: * 'ManagedFields[0].Time' expected a map, got 'string'

Rancher version : 2.4.5
Installation option : HA

**Comment by sujipo** [comment]
me too！
failed to decode the config, error: 1 error(s) decoding: * 'ManagedFields[0].Time' expected a map, got 'string'

Rancher version : 2.4.5
Installation option : HA

**Comment by victoryrao** [comment]
me too!
'ManagedFields[0].Time' expected a map, got 'string'

**Comment by sujipo** [comment]
Switching RKE to a lower version will solve this problem

**Comment by amoon78** [comment]
sujipo // can you share what RKE version can solve this problem? 
I'm having same issue on -
* Rancher version : 2.4.5
* Installation option : HA
* RKE: v1.18.3-rancher2-2

**Comment by Leixiaodong** [comment]
me too

TestAndApply Error
{"status":"404","error":"Not Found"}: undefined
