### ISSUE TITLE
反馈几个问题

### ISSUE THREAD

**Issue by lovewuqiang** [rancher/rancher#27692]
*Describe your issue here*
1.rancher搭建集群的cpu和内存信息是不准确的
2.rancher搭建的k8s集群1.16，nodeport范围是10000-60000，发布svc的nodeport用40000端口提示端口范围问题
3.导入自建k8s集群，修改了kubelet最大值，集群信息的使用pod数量不会更新。

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.5` UI: `v2.4.28` |
|Route|`undefined`|

**Comment by exqlnet** [comment]
同问
