### ISSUE TITLE
vSphere Node Driver - Datastores with empty characters causes failed provisioning

### ISSUE THREAD

**Issue by DH-Rancher** [rancher/rancher#27699]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a vSphere datastore containing empty characters. For example, `Datastore - General 01`.
2. Create a vSphere node template targeting this datastore to create the VM on.
3. Create a cluster leveraging this node template. Start with 1 node.
4. The First node will provision successfully, however, instead of creating and uploading the `user-data.iso` image into the VM's working location:

![image](https://user-images.githubusercontent.com/57356014/85415240-fb8e8580-b564-11ea-8eaf-5f5d7d114a97.png)

It is placed in the root of the datastore:

![image](https://user-images.githubusercontent.com/57356014/85415291-119c4600-b565-11ea-80c9-33d68ce4e502.png)

`[Datastore - General 01] -/user-data.iso`

**Result:**

Because of the above, subsequent nodes will not provision, because of the preexisting `user-data-.iso` file being in the root:

![image](https://user-images.githubusercontent.com/57356014/85415540-54f6b480-b565-11ea-8d4c-2f22551dce7f.png)

**Other details that may be helpful:**

In the same vSphere environment, pointing to a datastore name without empty characters provisions without issue and places the corresponding `user-data.iso` correctly inside the VM's directory:

![image](https://user-images.githubusercontent.com/57356014/85415932-cdf60c00-b565-11ea-9232-b10606b596b9.png)

This VM resides on `[p-esxi2-nvme-1] test-cluster-2/user-data.iso` 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
- Kubernetes version (use `kubectl version`): 

```
Iaas
2vCPU 4GB RAM
1.17.5
```

- Docker version (use `docker version`):

```
19.3.11
```

**Comment by DH-Rancher** [comment]
May be related : https://github.com/rancher/rancher/issues/26942

**Comment by DH-Rancher** [comment]
I think 

https://github.com/rancher/machine/blob/7fde9d7a49cd404f644c62fe0449ff5611119dd2/drivers/vmwarevsphere/vm.go#L31

Is causing this. I've added some code to debug it:

```
	p := mvm.Summary.Config.VmPathName

	log.Infof("Path is (pre split): %s", p)

	sp := strings.Split(p, " ")

	log.Infof("Path is (post split): %s", sp)

	path := strings.Replace(sp[1], fmt.Sprintf("/%s.vmx", d.MachineName), "", 1)

	log.Infof("strings.Replace %s,%s", sp[1], fmt.Sprintf("/%s.vmx", d.MachineName))

	log.Infof("Path being returned: %s", path)

	return path, nil
```

When presented with a datastore with no empty characters - in this example `p-esxi2-nvme-1` :+1: 

```
2020/07/24 14:32:10 [INFO] [node-controller-rancher-machine] (ds1) Creating cloud-init.iso
2020/07/24 14:32:10 [INFO] [node-controller-rancher-machine] (ds1) Datastore name (from cloud init) is p-esxi2-nvme-1
2020/07/24 14:32:10 [INFO] [node-controller-rancher-machine] (ds1) Uploading cloud-init.iso
2020/07/24 14:32:10 [INFO] [node-controller-rancher-machine] (ds1) Path is (pre split): [p-esxi2-nvme-1] ds1_1/ds1.vmx
2020/07/24 14:32:10 [INFO] [node-controller-rancher-machine] (ds1) Path is (post split): [[p-esxi2-nvme-1] ds1_1/ds1.vmx]
2020/07/24 14:32:10 [INFO] [node-controller-rancher-machine] (ds1) strings.Replace ds1_1/ds1.vmx,/ds1.vmx
2020/07/24 14:32:10 [INFO] [node-controller-rancher-machine] (ds1) Path being returned: ds1_1
```

But with a datastore with empty characters, such as `Datastore - General 01`

```
2020/07/24 14:28:35 [INFO] [node-controller-rancher-machine] (test2) Creating cloud-init.iso
2020/07/24 14:28:35 [INFO] [node-controller-rancher-machine] (test2) Datastore name (from cloud init) is Datastore - General 01
2020/07/24 14:28:36 [INFO] [node-controller-rancher-machine] (test2) Uploading cloud-init.iso
2020/07/24 14:28:36 [INFO] [node-controller-rancher-machine] (test2) Path is (pre split): [Datastore - General 01] test2/test2.vmx
2020/07/24 14:28:36 [INFO] [node-controller-rancher-machine] (test2) Path is (post split): [[Datastore - General 01] test2/test2.vmx]
2020/07/24 14:28:36 [INFO] [node-controller-rancher-machine] (test2) strings.Replace -,/test2.vmx
2020/07/24 14:28:36 [INFO] [node-controller-rancher-machine] (test2) Path being returned: -
```

Passing this back to the cloud-init method that uploads the ISO will leverage this return value.

**Comment by DH-Rancher** [comment]
Quick test changing 

`sp := strings.Split(p, " ")`

To

`sp := strings.Split(p, "]")`

Appears to fix this - Making this change enables the provisioning of RKE nodes onto Datastores containing empty characters. A more permanent fix might be to use regex to separate out the string instead.

**Comment by EzraBrooks** [comment]
Is this looking for an implementer? My group has been unable to update Rancher past (iirc) 2.2.x because of this bug 😢

**Comment by DH-Rancher** [comment]
@EzraBrooks - Would you be willing to validate a fix using a test version of Rancher? (I can provide instructions)

**Comment by EzraBrooks** [comment]
Sorry, I don't have the time or resources to run a test version at the moment.

**Comment by bmdepesa** [comment]
v2.4-head, v2.5-head, master-head tested in this issue: https://github.com/rancher/rancher/issues/29519#issuecomment-712872322
