### ISSUE TITLE
rancher-dns does not resolve docker-compose given domainnames

### ISSUE THREAD

**Issue by AnalogJ** [rancher/rancher#2769]
I'm trying to setup an OpenVPN docker container that will resolve rancher services. The issue I'm running into is that the rancher-dns service only seems to contain entries in the following formats

```
app
app.rancher.internal
```

While I want to use my own custom domain name

```
app.example.com
```

I thought I could get this working by specifying the `domainname` entry in my docker-compose file but that didnt work either..

```
app:
  ...
  domainname: example.com
```

Is there another way of adding additional fqdns to the rancher dns service?

**Comment by deniseschannon** [comment]
For rancher-dns service, you can specify the domain name in the name of the links.

![screen shot 2015-11-30 at 11 04 20 am](https://cloud.githubusercontent.com/assets/11410997/11481400/26fba1ac-9752-11e5-8ac9-fd483cc9596b.png)


In rancher-compose, it'd be something like:
```
test2:
  links:
  - test1:test1.example.com
```

**Comment by AnalogJ** [comment]
Hey @deniseschannon that won't work if Im dynamically linking my services using a selector tag though. Any other ways I can do it?

**Comment by deniseschannon** [comment]
Currently, there is no other way to do it when using a selector link. I've made it a request.

**Comment by sswisdom** [comment]
Hi @deniseschannon when I try to name the linked service with something like '***.***.***', i got error "Setservicelinks Error
Validation failed in API: name contains invalid characters", seems "." not expected in name, using the latest rancher/server, is this a known issue?

**Comment by deniseschannon** [comment]
@sswisdom In v1.0.0, we had stricter validation for service alias names for our internal DNS service, but we have [relaxed those rules in v1.0.1](https://github.com/rancher/rancher/issues/4252).

**Comment by sswisdom** [comment]
@deniseschannon thanks a lot, I've tried with latest server and it works well:). One more question, I could add internal service domain resolution(like pointing xxx.xx.app to private container ip) in such way only within one service scope, like adding many links to support resolve different internal domain, but we have several hundreds internal apps and each one have one internal domain name, we used to link them using dnsmasq+nginx before. Now with link mechanism, is there a way now for each app could resolve other internal domain names, or is there any plan to support add custormized internal dns entry so we could easily tackle it.

**Comment by sswisdom** [comment]
@deniseschannon thanks a lot, I've tried with latest server and it works well:). One more question, I could add internal service domain resolution(like pointing xxx.xx.app to private container ip) in such way only within one service scope, like adding many links to support resolve different internal domain, but we have several hundreds internal apps and each one have one internal domain name, we used to link them using dnsmasq+nginx before. Now with link mechanism, is there a way now for each app could resolve other internal domain names, or is there any plan to support add custormized internal dns entry so we could easily tackle it.

**Comment by sswisdom** [comment]
@deniseschannon , to make it clear, I could use nginx in one environment for reverse proxy, so is there a way for each service in the environment could resolve internal domain name like 'appname.domain.app' to the nginx container ip?

**Comment by deniseschannon** [comment]
@sswisdom At this time, we don't plan on supporting customized internal dns entries. 

I believe you could use service alias in order to resolve to `appname.domain.app`.

**Comment by flantel** [comment]
@deniseschannon it is not possible to add a Service Alias which contains a . - so adding such a name as appname.domain.app would not work. It does work if you set appname.domain.app as the name in a Service Link - perhaps Would it make sense to use the same validation for both an Alias and a Link?

**Comment by deniseschannon** [comment]
@flantel We have this issue to have validation for a link alias. https://github.com/rancher/rancher/issues/680

But we had to relax the rules in a later release as many of our users had already starting using invalid DNS labels for link aliases. Since service alias names have always had the requirements as a valid DNS label, we won't be relaxing those rules.
