### ISSUE TITLE
[RFE] Rancher Helm chart: Ability to set a custom ACME CA-server 

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#27698]
**What kind of request is this (question/bug/enhancement/feature request):**

This is a request for enhancement on the Helm Chart.

**Result:**

It would be nice to be able to set a custom LetsEncrypt CA Server.

**Other details that may be helpful:**

This would allow the use of ACME testing and https://github.com/smallstep/certificates

gz#10756

**Comment by mikekuzak** [comment]
Can we reopen this ticket, please? We have same issue, internally. Air Gap on prem installation with a custom Acme server.
