### ISSUE TITLE
Docker install fails on OL 7.8

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#27691]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a fresh instance of Oracle Linux 7.8: `OL7.8-x86_64-HVM-2020-04-28 (ami-0abffb2b264e8355e)`

Install Docker 19.03.11
```
curl -sSL https://releases.rancher.com/install-docker/19.03.11.sh |sh
```

**Result:**
Fails with:
```
curl -sSL https://releases.rancher.com/install-docker/19.03.11.sh |sh
+ '[' oraclelinux = redhat ']'
+ sudo -E sh -c 'yum install -y -q yum-utils'
Package yum-utils-1.1.31-54.0.1.el7_8.noarch already installed and latest version
+ sudo -E sh -c 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
repo saved to /etc/yum.repos.d/docker-ce.repo
+ '[' stable '!=' stable ']'
+ sudo -E sh -c 'yum makecache fast'
Loaded plugins: ulninfo
docker-ce-stable                                                 | 3.5 kB  00:00:00
ol7_UEKR5                                                        | 2.5 kB  00:00:00
ol7_latest                                                       | 2.7 kB  00:00:00
Metadata Cache Created
+ sudo -E sh -c 'yum install -y -q docker-ce-19.03.11 docker-ce-cli-19.03.11'
Error: Package: containerd.io-1.2.13-3.2.el7.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2:2.74
Error: Package: 3:docker-ce-19.03.11-3.el7.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2:2.74
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

Environment information:

Kernel version `4.14.35-1902.300.11.el7uek.x86_64`

**Comment by aaronRancher** [comment]
```
curl -sSL https://releases.rancher.com/install-docker/19.03.11.sh |sh
```
This command works in the following OL 7.7 kernel versions
`4.14.35-1902.8.4.el7uek.x86_64`
`4.14.35-1902.10.7.el7uek.x86_64`
`4.14.35-1902.10.2.1.el7uek.x86_64`

Running `yum install docker-engine` works on OL 7.8 kernel `4.14.35-1902.300.11.el7uek.x86_64` as it updates selinux. This gives docker version `19.03.1`

**Comment by cocampbe** [comment]
Just wanted to suggest always using docker-engine supplied by oracle. Not that you cannot run CE, but the docker-engine provided by oracle is  CE, but supported by oracle. I am not sure how this fits into your process. One advantage is that oracle provides support for docker-engine with both basic and premier support. 

[https://docs.oracle.com/en/operating-systems/oracle-linux/docker/#](url)

**Comment by jmgarciac** [comment]
You can find the container-selinux package is in the ol7_addons repo, enable it and you can install docker with the script as usual.
 `
yum-config-manager --enable ol7_addons
curl -sSL https://releases.rancher.com/install-docker/19.03.11.sh |sh
` 

`$> yum info container-selinux
Loaded plugins: langpacks, ulninfo
Installed Packages
Name        : container-selinux
Arch        : noarch
Epoch       : 2
Version     : 2.107
Release     : 3.el7
Size        : 40 k
Repo        : installed
From repo   : ol7_addons
Summary     : SELinux policies for container runtimes
URL         : https://github.com/containers/container-selinux
License     : GPLv2
Description : SELinux policy modules for use with container runtimes.`

**Comment by aaronRancher** [comment]
Docker install succeeds after enabling the container-selinux package
```
yum-config-manager --enable ol7_addons
curl -sSL https://releases.rancher.com/install-docker/19.03.11.sh |sh
```
Was able to run Rancher on a local cluster on Kernel `4.14.35-1902.300.11.el7uek.x86_64`

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher docker install `19.03.11.sh`

Steps:
Create a fresh instance of Oracle Linux 7.8: `OL7.8-x86_64-HVM-2020-04-28 (ami-0abffb2b264e8355e)`

Install Docker `19.03.11`
```
curl -sSL https://releases.rancher.com/install-docker/19.03.11.sh |sh
```
Result:
Docker is installed successfully:
```
+ sudo -E sh -c 'service docker start'
Redirecting to /bin/systemctl start docker.service
+ sudo -E sh -c 'docker version'
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:13:48 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:12:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker ec2-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.

```
