### ISSUE TITLE
App Deployed Via Yaml Results in Empty From on Edit

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#27705]
This is a bug filed by another users [here](https://github.com/rancher/rancher/issues/26559#issuecomment-622529710) that is separate from the initial issue filed.

**Environment information :**

Component | Version
-- | --
Rancher | v2.4.2
User Interface | v2.4.14
Helm | v2.16.3-rancher1
Machine | v0.15.0-rancher35

**Bug 1 :**

**Steps to reproduce (least amount of steps as possible):**
1. Go to Apps
2. Deploy an app using YAML
3. Then upgrade the app.
4. Use the Form view.

**Result:**
Fields are empty.

**Expected Behavior**
Fields should display the correct configuration.

**Bug 2 :**

**Steps to reproduce (least amount of steps as possible):**
1. Go to Apps
2. Deploy an app using form view
3. Then upgrade the app.
4. Show the YAML view

**Result:**
Boolean values are defined with quotes

> myboolean: "true"

The Helm chart can't be upgraded because `myboolean` is a string and not a boolean.

**Expected Behavior**

Boolean values should be parsed properly.
> myboolean: true

**Bug 3 :**

**Steps to reproduce (least amount of steps as possible):**
1. Go to Apps
2. Deploy an app using form view
3. Edit a field/value
4. Show the YAML view
(Happens if you edit the YAML first too)

**Result:**
Values are not updated

**Expected Behavior**
Values should be the same as form view.

**Comment by westlywright** [comment]
I believe all of the steps described were addressed in https://github.com/rancher/ui/commit/a5474a4b7018da6bd48af74391b1806f595828a4 which was deployed in UI Tag v2.4.28. @rancher/qa can we revalidate these issues and if so c lose this?

**Comment by jiaqiluo** [comment]
The bug cannot be reproduced in v2.4.1, v2.4.2, and v2.4.5

**Comment by jiaqiluo** [comment]
This issue is closed since it cannot be reproduced and no more users report it.
