### ISSUE TITLE
Validate Monitoring 0.1.1 for 2.4.0 to 2.4.4

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27703]
QA validation check on monitoring 0.1.1 for 2.4 to 2.4.4

**Comment by jiaqiluo** [comment]
The monitoring chart v0.1.1 is validated in the following cases:

- on a fresh install, create cluster with the default k8s version, enable cluster & project monitoring with persistent storage enabled  
	- v2.4.0 k8s 1.17.5-rancher1-1
	- v2.4.1 k8s 1.17.5-rancher1-1
	- v2.4.2 k8s 1.17.5-rancher1-1
	- v2.4.3 k8s 1.17.5-rancher1-1
	- v2.4.4 k8s 1.17.6-rancher2-1


- v2.4.2, monitoring upgrade cluster & project monitoring 0.1.0 -> 0.1.1  with persistent storage enabled  
- v2.4.4, monitoring upgrade cluster & project monitoring 0.1.0 -> 0.1.1  with persistent storage enabled  

Results:
- the monitoring works as expected, no new issue is found.

**Comment by jiaqiluo** [comment]
@maggieliu @ryansann  We need to have the min/max version changes in the dev branch for final validation.

**Comment by jiaqiluo** [comment]
the min/max version change is validated on the following Rancher versions with the branch of `system-library` being `dev-v2.4`

- from `v2.4.0` to `v2.4.3` shows both `0.1.0` and `0.1.1`
- `v2.4.5` shows only `0.1.1`
