### ISSUE TITLE
"Monitoring Version" list is empty from second RKE custom cluster created using a newly installed Rancher 2.4.4 on k3s

### ISSUE THREAD

**Issue by adacaccia** [rancher/rancher#27719]
*Trying to enable monitoring on a newly created custom cluster with 3 nodes on Rancher 2.4.4, the "Monitoring Version" list is empty. This in turn leads to error "Template system-library-rancher-monitoring allowed rancher version not match current server" seen from the Global view, if one tries to enable monitoring anyway.*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.4` UI: `v2.4.22` |
|Route|`undefined`|

**Comment by jiaqiluo** [comment]
hi @adacaccia  can you try the workaround here to see if it solves your problem : https://github.com/rancher/rancher/issues/27678#issuecomment-648387928

**Comment by adacaccia** [comment]
@jiaqiluo: thank you so much, this all of a sudden solved my problem as I was able to enable monitoring 0.1.0 straight after changing the release of system-library and then fixing it again at "release-v2.4". The "edit cluster" step was not needed in my case.
Closing now!
