### ISSUE TITLE
[Feature Request] forcefully clear the helm catalog cache

### ISSUE THREAD

**Issue by dorsany** [rancher/rancher#27717]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement / feature request

**Steps to reproduce (least amount of steps as possible):**
Rancher catalog seems to cache chart by version number
So in case that you update the same helm chart on the same helm chart **version** (including `question.yaml`) without increasing the helm chart **version** and publishing chart again, the rancher will not picking up latest change of the helm chart version that currently seated in the helm catalog (like chart museum), and the rancher will use the locally helm catalog-cache. 
In early phase of chart development, it will be very helpful to get the ability to forcefully clear the helm catalog cache so it will be much easier to put another step in the **continuous integration pipelines** to clear the cache.

In this case, I suggest a way to forcefully clear the helm catalog cache with several ways:
1) expose a rest api route to perform http post request to forcefully clear the cache
2) rancher cli command to forcefully clear the cache
3) new button in the helm catalogs page to forcefully clear the cache

or

adding additional check to update locally helm charts not just by version but also by helm chart hash (md5/crc)?

**workaround:**
1) delete the management-state/catalog-cache directory
```
kubectl -n cattle-system exec $(kubectl -n cattle-system get pod -l app=rancher --no-headers -o custom-columns=':metadata.name') -- bash -c 'rm -rf /var/lib/rancher/management-state/catalog-cache/*'
```
note: you need to refresh the relevant catalog after removing this directory

2) delete the rancher pod
```
kubectl -n cattle-system delete pod $(kubectl -n cattle-system get pod -l app=rancher --no-headers -o custom-columns=':metadata.name')
```

**Environment information**
k8s

related: https://github.com/rancher/rancher/issues/19118

**Comment by mattmattox** [comment]
This issue makes doing rapid development of catalog item very difficult.
Example: I every time I want to test a change to questions.yml. I have to "restart" Rancher which can cause users to disconnect.

**Comment by ouchuji** [comment]
This problem puzzles me too, I need to clear the cache by hand in order to test my charts repository.

**Comment by urakagi** [comment]
+1 Here. Is there any chance?

**Comment by bo-er** [comment]
Why would there be a cache in the first place? I am facing the same problem, I hope rancher provides users with an option to disable caching.

**Comment by theAkito** [comment]
Why is this issue closed? I'm waiting for this since years.
