### ISSUE TITLE
Amazon EKS: Default ami of region x for kubernetes version 1.xx is not set

### ISSUE THREAD

**Issue by Rancheroo** [rancher/rancher#27729]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
Hard to reproduce as this was triggered using a 1.12 EKS cluster which is now not available on AWS

Basically upgrade an EKS cluster from 1.12 to 1.15 using Rancher 2.4.3
and a mismatch will occur

![image](https://user-images.githubusercontent.com/56899019/85671062-dcc6f500-b704-11ea-87c7-d85363ce150d.png)

**Result:**
The result is seen in the image above

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): m5.xlarge
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

gz#10179

**Comment by mshivanna** [comment]
We upgraded our rancher instance from 2.3.5 to 2.5.1. our eks clusters were at 1.13 and 1.14 and now we are seeing 
`Default ami of region us-east-1 for kubernetes version 1.14 is not set` error.

**Comment by Rancheroo** [comment]
@mshivanna 
FYI 2.5.1 is not listed as stable and you should be careful with production environments.

It looks like the when you upgraded to Rancher v2.5, but their EKS version set in Rancher is v1.12, which in v2.5 is not matched. If you 'View in API' the cluster what version of kubernetes is listed? Does it match what is running?

You should be able to edit the cluster and select a matching version to line up with EKS, this shouldn't cause any actual action as the versions will be the same.

Once the Rancher API and the actual versions are matching then edit the cluster and filling in the AWS key/secret and hit save.

This will update the EKS kubernetes version stored in the API.

This method worked on 2.4.x however not sure with 2.5.x. If you have issues you might want to try the most stable release of 2.4.x.

**Comment by mshivanna** [comment]
@Rancheroo thanks for the suggestion we rolled it back to 2.3.6 Will test it and let you know how it goes.
