### ISSUE TITLE
toYaml in rancher-monitoring/grafana chart when setting extraVars causes problems when not using strings

### ISSUE THREAD

**Issue by Arno500** [rancher/rancher#27720]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Set extraEnv in Grafana chart (using the monitoring menu, cluster-wide).
For the example, we'll use :
- grafana.extraVars[0].name = GF_SMTP_ENABLED
- grafana.extraVars[0].value = true  

We need this env variable to enable SMTP alerts in included Grafana. But here, we only want the `true` in the value field to be quoted and set (should be `"true"`). But with toYaml, it will keep it `true`, as a boolean, thus being refused by Kubernetes (only accepting strings in env).
If I try with `"true"` directly in the field, toYaml wants to keep the string intact, and output `'"true'"`. But I can't get a simple `"true"` unfortunately.

**Result:**

**Other details that may be helpful:**
https://github.com/helm/helm/issues/4262
The toYaml function causes some problems when converting types. But for env variables, values should not be converted, only quoted.
https://github.com/helm/helm/issues/4262#issuecomment-646307498

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): Single, with helm.

**Comment by rlio** [comment]
Same problem for us Did you solve it @Arno500 ?

**Comment by Arno500** [comment]
> Same problem for us Did you solve it @Arno500 ?
@rlio I think I saw another issue where they mentioned they will refactor entirely the monitoring charts in Rancher (notably by updating Grafana). So I kind of abandoned, waiting for this new version.

**Comment by rlio** [comment]
Thanks @Arno500.  I have removed all extraVars parameters to be able to upgrade to the latest version
