### ISSUE TITLE
Longhorn Chart for Dashboard

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27725]
Actual implementation of the chart will be tracked here: https://github.com/longhorn/longhorn/issues/1043#issuecomment-649144876

**Comment by yasker** [comment]
Chart PR at https://github.com/rancher/dev-charts/pull/35

**Comment by ttpcodes** [comment]
Chart PR is now at rancher/charts#526 instead.

**Comment by khushboo-rancher** [comment]
Verified the basic longhorn flow on rancher master-head ```ec04f78```.
The app is available and the basic scenario of longhorn is working. Below scenarios are verified.
1. Install longhorn v1.0.2.
2. Default settings.
3. Create a PV/PVC for a volume.
4. Create deployment/stateful set with existing PVC.
5. Create deployment/stateful set with existing PVC with multiple replica.
6. Create stateful set with volume claim template(using longhorn storage class)
7. Create stateful set/deployment with the option create a new PVC using storage class - https://github.com/rancher/dashboard/issues/1459
8. Create stateful set/deployment with option create a new pvc with existing pv. - https://github.com/rancher/dashboard/issues/1460
9. Create a secret for longhorn backup store.
10. Basic operation of longhorn - snapshot, backup
11. Uninstall longhorn
