### ISSUE TITLE
Bump system upgrade controller version. 

### ISSUE THREAD

**Issue by MonzElmasry** [rancher/rancher#27724]
bump the latest release of system upgrade controller `v0.6.2` into rancher 
https://github.com/rancher/system-upgrade-controller/releases/tag/v0.6.1
https://github.com/rancher/system-upgrade-controller/releases/tag/v0.6.2

**Comment by davidnuzik** [comment]
Taking out of To Test. The PR is not yet merged.

**Comment by rancher-max** [comment]
#### Validated with both an rke2 cluster and k3s cluster

- See the following notice of using v0.6.2 in the logs:
```
[kube] 2020/07/30 18:59:21 get relation pod of object: cattle-system/Deployment/system-upgrade-controller

LAST DEPLOYED: Thu Jul 30 18:59:19 2020

NAMESPACE: cattle-system

STATUS: DEPLOYED

RESOURCES:

==> v1/ClusterRoleBinding

NAME            ROLE                       AGE

system-upgrade  ClusterRole/cluster-admin  4s

==> v1/ConfigMap

NAME                    DATA  AGE

default-controller-env  9     3s

==> v1/Deployment

NAME                       READY  UP-TO-DATE  AVAILABLE  AGE

system-upgrade-controller  1/1    1           1          4s

==> v1/Namespace

NAME           STATUS  AGE

cattle-system  Active  7m52s

==> v1/Pod(related)

NAME                                        READY  STATUS   RESTARTS  AGE

system-upgrade-controller-585f9d68f9-qds98  1/1    Running  0         4s

==> v1/ServiceAccount

NAME            SECRETS  AGE

system-upgrade  1        4s

NOTES:

You have deployed the Rancher K3s Upgrader

Version: v0.6.2

Description: This controller enables a k3s cluster to update itself by

reacting to Plan CRs.
```
- In Rancher UI shows using correct version as well:
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/55997940/88969114-315e1280-d265-11ea-82b5-5d2d3f584819.png">


**NOTE: K3S Single node cluster upgrades successfully, but RKE2 does not. Opening a separate issue in RKE2 repo to address this.**
