### ISSUE TITLE
UI - Not able to launch "Edit LoadBalancer" page

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2772]
Server version - v0.47.0-rc1

Steps to reproduce the prolem:
Create a LB service. 
Activate service.
Try to Edit this service.

UI is not able to to launch "Edit LoadBalancer" page.

**Comment by westlywright** [comment]
@deniseschannon can you check this on master? I followed your steps and was able to edit the service. It is worth noting it took some time for the edit service modal come up, it was loading for quite a while, but  this is a side effect of the sheer amount of services we have. The UI loads those services so we can populate the drop down. Maybe this was the issue you were experiencing?

**Comment by deniseschannon** [comment]
I did see this was working on master yesterday, but the listener ports weren't displaying. I can check all the detailed fields to see what is missing.

**Comment by westlywright** [comment]
@deniseschannon sorry i meant to mention @sangeethah. i had like 10 issues open this morning and was responding to a few

**Comment by vincent99** [comment]
Listener ports is still broken because it used part of the LB API that was removed.  Working on it.

**Comment by deniseschannon** [comment]
Able to edit load balancers with latest UI (evening 11/24)
