### ISSUE TITLE
[UI][KEv2]: Create UI for new EKS

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#27739]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

**EKS create page:**
_Note: Account access is not include but should copy RKE on AWS account access_
![image](https://user-images.githubusercontent.com/19376037/85803203-7b4e5880-b6fb-11ea-9af1-e84aa37621d4.png)

**New import page:**
![image](https://user-images.githubusercontent.com/19376037/85803245-90c38280-b6fb-11ea-8aab-23dbb5aa7b83.png)

**Import EKS page:**
![image](https://user-images.githubusercontent.com/19376037/85803276-9f119e80-b6fb-11ea-9775-6a839763774e.png)

_Note: All fields are contained in Cluster.Spec.EKSConfig_

**Input Chart for Cluster Creation**
Label | YAML value | notes
---|---|---
Cloud Credential | cloudCredential |
Region | region | 
Kubernetes Version | kubernetesVersion |
Secrets Encryption | kmsKey | its a string, just leave blank if none, get possible values from AWS Key Management Service
Service Role | serviceRole | retrieve from AWS for custom as we do today
Public Access | publicAccess |
Private Access | privateAccess |
Public Access Endpoints | publicAccessSources | probably can be hidden if publicAccess is false
VPC & Subnets | virtualNetwork, subnets, securityGroups | 
Cloudwatch Log Groups | logging | accepted values are ["audit", "api", "scheduler", "controllerManager", "authenticator"]
Add NodeGroup | nodeGroups | node group chart is show below, should be able to add new node groups, and delete current node groups
Tags | tags |

**Input Chart for Node Groups**
Label | YAML value | notes
---|---|---
Node Group Name | nodegroupName |
Instance Type | instanceType | fetch from AWS
GPU enabled | gpu |
Desired ASG Size | desiredSize |
Max Size | maxSize |
Min Size | minSize |
Node Volume Size | diskSize |
Ec2SshKey | ec2SshKey | empty string will be taken literally, no key should be nil
Add Label | labels |
Tags | tags |

**Input Chart for Import EKS**:
Label | YAML value | notes
---|---|---
Region | region |
EKS Cluster to Import | displayName |

**Comment by rmweir** [comment]
May want to flip EKS and Other provider on import page

**Comment by rmweir** [comment]
In 2.5, all new cluster should be created through this, all old cluster should be updated based on the old UI

**Comment by sowmyav27** [comment]
**On master-head - commit id: `6d6199121`**

- UI available is 
<img width="1274" alt="Screen Shot 2020-07-29 at 2 27 18 PM" src="https://user-images.githubusercontent.com/26032343/88855509-d7e3de00-d1a7-11ea-84d2-c893078ef55b.png">
<img width="1279" alt="Screen Shot 2020-07-29 at 2 27 27 PM" src="https://user-images.githubusercontent.com/26032343/88855512-d9ada180-d1a7-11ea-9fd7-368d9c116085.png">
<img width="1289" alt="Screen Shot 2020-07-29 at 2 27 33 PM" src="https://user-images.githubusercontent.com/26032343/88855516-db776500-d1a7-11ea-8809-8c638a64063d.png">

- Other UI issues are being tracked separately
