### ISSUE TITLE
Failed to list *: context deadline exceeded seen in rancher/rancher container logs

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#27736]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Run `rancher/rancher:v2.4.5` or `v2.4-head`, create a custom cluster and add a node with all roles. Watch Rancher container logs.

**Result:**
Following lines are seen:

```
Failed to list *v1.X: Get X: context deadline exceeded
```

gzrancher/rancher#11544

gzrancher/rancher#11329

**Comment by chad-barensfeld-exa** [comment]
Same issue here after upgrading to v2.4.5

**Comment by adampl** [comment]
@superseb Is this a serious issue? What does it actually mean? Does it break something?

**Comment by guleng** [comment]
I also encountered the same problem after upgrading to 2.4.5
![image](https://user-images.githubusercontent.com/40238640/86310396-91ef3500-bc50-11ea-8356-28b87f919816.png)
I monitor the API server alerts of the report
![image](https://user-images.githubusercontent.com/40238640/86310503-db3f8480-bc50-11ea-85ec-c8cc7cebe9d3.png)

**Comment by gsel** [comment]
We also have the same issue after upgrading to v2.4.5

**Comment by adampl** [comment]
In my case it ceased after upgrading the cluster to k8s 1.18.

**Comment by superseb** [comment]
No impact has been reported, if you experience any, please report back. It seems to be related to 1.18 k8s go client vs older Kubernetes versions.

**Comment by Oats87** [comment]
Encountered with Rancher running on a `1.15.2` cluster.

**Comment by superseb** [comment]
This seems to be related to `resourceVersion` changes and the watcher/informer using an old/too high `resourceVersion` causing the logging. When I restart the `kube-apiserver` using `docker restart kube-apiserver` on the control plane nodes of the cluster (or possibly just the one which address is being logged in the `https://` URL), it seems to stop.

Now figuring out how to reset/fix this.

**Comment by mhulscher** [comment]
Encountering the same issue running inside a 1.17 Kubernetes cluster.

**Comment by davidcorbin** [comment]
As @superseb said, restarting the API server on the node that rancher is trying to connect to fixed the issue. As such, rebooting the server that Rancher is connecting to also works (if you can the node going down for a short period)

**Comment by slououou** [comment]
We have the same issue on v2.4.5 in HA, installed with rke among 4 worker node. Import 100+ v1.17.3 kubernetes cluster and error log of "Failed to list *v1.X: Get X: context deadline exceeded" is overwhelming. And rancher pod would be finally terminated with follow error log:
```
...
E0722 08:57:25.085257       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.RoleBinding: Get https://10.96.0.1:443/apis/rbac.authorization.k8s.io/v1/rolebindings?resourceVersion=9227960&timeout=30s: context deadline exceeded
fatal error: concurrent map read and map write

goroutine 524208 [running]:
runtime.throw(0x3fb5abb, 0x21)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0bb753d20 sp=0xc0bb753cf0 pc=0x42fb12
...
```
Could those error eventually lead to a concurrent map read/write?

**Comment by danielkoo** [comment]
Hi @superseb ,

Not sure whether it is related (and hopefully this helps), but we were getting these errors too, and noticed on the affected control plane node containers running the version of the rancher-agent we upgraded from (v2.3.6, with image ID beginning with 697), instead of the v2.4.5 image

```
 $ docker images|grep agent
rancher/rancher-agent               v2.4.5              2e6c7ac4e072        4 weeks ago         294MB
rancher/rancher-agent               v2.3.6              697a883e05d0        3 months ago        282MB
 $ docker ps | grep 697
6006fc7b45b9        697a883e05d0                          "run.sh"                 2 hours ago         Up 2 hours                              k8s_cluster-register_cattle-cluster-agent-786cdbd4-xsgnq_cattle-system_83f41f93-c33e-43d6-8986-4a20bb1c71ce_0
e12fec09cb50        697a883e05d0                          "run.sh"                 17 hours ago        Up 17 hours                             k8s_agent_cattle-node-agent-hv4lz_cattle-system_455b6c01-2c8c-4479-8bca-c3c79f254590_0
```

following your workaround to restart the apiserver, and we see the v2.4.5 image correctly being used:

```
 $ docker ps | grep 2e6
35c06385192a        2e6c7ac4e072                          "run.sh"                 18 minutes ago       Up 18 minutes                           k8s_agent_cattle-node-agent-6kjw8_cattle-system_f0c3e78f-7c20-49b6-950b-a29c5536548f_0
```

**Comment by bentastic27** [comment]
@maggieliu @superseb We have a customer who's getting bombarded with alerts from GKE on this. So they had to turn them off, but that essentially defeats their cluster monitoring.

zd11329

**Comment by jgerry2002** [comment]
Version 2.4.5 on K3s in HA mode. I am seeing spamming notifications in the logs regarding this same issue. Does not seem to impact actual cluster, it just makes it hard to diagnose other possible issues with all the noise. 

E0811 14:02:10.179823       8 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.Service: Get https://<ip>:6443/api/v1/services?resourceVersion=696&timeout=30s: context deadline exceeded
I0811 14:02:19.802072       8 trace.go:116] Trace[1368906917]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-11 14:01:49.801708362 +0000 UTC m=+213894.988805524) (total time: 30.000336474s):

**Comment by Hitesh-Agrawal** [comment]
I see the same issue on our cluster which was upgraded yesterday from 2.3.3 to 2.4.5 , I have restarted the kube-apiserver as suggested by @superseb above and the errors seems to have gone.

**Comment by jgerry2002** [comment]
Thanks for the response, in this case it was a fresh install of 2.4.5 about 12 days ago. The restart did seem to cure the spam in the logs temporarily. Perhaps a resource issue over time in the underlying container?

**Comment by jonatan-b-kr** [comment]
We have this issue with GKE and had to disable those alerts, which is not optimal. We can't restart the GKE control plane, because it is managed by Google, and because if they did, this is a production cluster with lots of stateful sets and the restart would cause downtime.

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.4.5**

- Deploy a custom cluster.
- Rancher logs show:
```
I0825 22:02:12.561740       7 trace.go:116] Trace[1917815213]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-25 22:01:42.561415567 +0000 UTC m=+1123.685902800) (total time: 30.00030985s):
Trace[1917815213]: [30.00030985s] [30.00030985s] END
E0825 22:02:12.561751       7 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.ResourceQuota: Get https://18.223.210.60:6443/api/v1/resourcequotas?resourceVersion=679&timeout=30s: context deadline exceeded
I0825 22:02:12.562769       7 trace.go:116] Trace[141161011]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-25 22:01:42.562499589 +0000 UTC m=+1123.686986822) (total time: 30.000252538s):
Trace[141161011]: [30.000252538s] [30.000252538s] END
```

**Verified on 2.4-head- commit id: `965182f6b`**
- Deploy a custom cluster.
- Rancher logs do not show `context deadline exceeded` logs but see
```
I0825 21:30:11.768881       6 trace.go:116] Trace[1657588612]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-25 21:29:32.421567159 +0000 UTC m=+874.030196264) (total time: 39.347269541s):
Trace[1657588612]: [39.347256731s] [39.347256731s] Objects listed
I0825 21:30:11.821867       6 trace.go:116] Trace[434777563]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-25 21:29:32.446909313 +0000 UTC m=+874.055538428) (total time: 39.374919837s):
```

**Upgrade from 2.4.5 to 2.4-head commit id: `965182f6b`**

- On 2.4.5 - deploy a GKE and custom cluster (3 nodes all roles)
- Rancher logs show `context deadline exceeded` logs
- Upgrade rancher server to 2.4-head 
- Deploy a custom cluster
- Verified the rancher logs do NOT show `context deadline exceeded` logs but see
```
I0825 21:30:11.768881       6 trace.go:116] Trace[1657588612]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-25 21:29:32.421567159 +0000 UTC m=+874.030196264) (total time: 39.347269541s):
Trace[1657588612]: [39.347256731s] [39.347256731s] Objects listed
I0825 21:30:11.821867       6 trace.go:116] Trace[434777563]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-25 21:29:32.446909313 +0000 UTC m=+874.055538428) (total time: 39.374919837s):
```

@superseb Is this ^^^ log still expected ?

**Comment by superseb** [comment]
Line starting with `I` means Informational so that's fine. Are these spamming the logs or just a few at once and that's it?

**Comment by sowmyav27** [comment]
Logging a separate issue to track the multiple informational logs seen - https://github.com/rancher/rancher/issues/28567.

**Comment by laloyalo** [comment]
Hello, rancher team. This issue should not be closed, this generally happens with clusters running hundreds of apps, this won't happen in a recently deployed cluster as stated in the verification steps. The timeout for 30s is not large enough for such situations. Could you issue a recommendation on how to change such timeout?
In general, the stated solutions about upgrading Kubernetes work because the control plane gets restarted as part of the update process, but that is not a normal procedure that can be carried while hosting Rancher or the external clusters in services like GKE.
Thanks!
