### ISSUE TITLE
Private and additional trusted CA cert files created as directories, causing Rancher Pod startup to fail

### ISSUE THREAD

**Issue by yankcrime** [rancher/rancher#27733]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Installation as per the documentation for deploying Rancher via Helm on a Kubernetes cluster.  [Follow the steps](https://rancher.com/docs/rancher/v2.x/en/installation/options/tls-secrets/) to add TLS secrets, including using a private CA signed certificate:

```bash
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=rancher.127.0.0.1.dnsify.me.pem \
  --key=rancher.127.0.0.1.dnsify.me-key.pem
```

```
kubectl -n cattle-system create secret generic tls-ca \
  --from-file=rootCA.pem
```

Attempt to install Rancher via Helm, with the appropriate options set:

```
helm install rancher rancher-latest/rancher \
--namespace cattle-system \
  --set hostname=rancher.127.0.0.1.dnsify.me \
  --set ingress.tls.source=secret \
  --set privateCA=true
```

**Result:**

Rancher Pods end up in an Error state with the following log entry:

```
2020/06/25 17:06:16 [FATAL] read /etc/rancher/ssl/cacerts.pem: is a directory
```

**Other details that may be helpful:**

Reverting [this change](https://github.com/rancher/rancher/pull/18474) fixes the deployment, so the problem is related to the `mountPath` definitions in the Helm chart.  However, because two of them use the same base directory (`/etc/rancher/ssl`), the fix might not be so straightforward if a user wants to specify both a private CA cert file as well as an additional trusted CA cert.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
rancher/rancher:v2.4.5
- Installation option (single install/HA): 
HA

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ kubectl get nodes -o wide
NAME              STATUS   ROLES                      AGE   VERSION   INTERNAL-IP       EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
192.168.122.167   Ready    controlplane,etcd,worker   81m   v1.17.6   192.168.122.167   <none>        Ubuntu 18.04.4 LTS   4.15.0-106-generic   docker://19.3.12
192.168.122.229   Ready    controlplane,etcd,worker   81m   v1.17.6   192.168.122.229   <none>        Ubuntu 18.04.4 LTS   4.15.0-106-generic   docker://19.3.12
192.168.122.240   Ready    controlplane,etcd,worker   81m   v1.17.6   192.168.122.240   <none>        Ubuntu 18.04.4 LTS   4.15.0-106-generic   docker://19.3.12
```

**Comment by dmelha** [comment]
same for me with rancher 2.4.4: 
* `helm install rancher rancher-stable/rancher --namespace cattle-system --version 2.4.4 --set hostname=certmachtinghostname --set ingress.tls.source=secret --set privateCA=true`
* secret previously created: `kubectl -n cattle-system create secret generic tls-ca --from-file=cacerts.pem`
* pod error msg: `[FATAL] read /etc/rancher/ssl/cacerts.pem: is a directory`

**Comment by yankcrime** [comment]
Thanks @dmelha - it does indeed state quite clearly that:

> Make sure the file is called cacerts.pem as Rancher uses that filename to configure the CA certificate.

🤦!

**Comment by RobertoMachorro** [comment]
Posting on 2024, confirming this is still the case. File **needs** to be named *cacerts.pem*.
