### ISSUE TITLE
Plans for API clients in Python

### ISSUE THREAD

**Issue by rudimk** [rancher/rancher#27731]
**What kind of request is this (question/bug/enhancement/feature request):**
A question.

**Steps to reproduce (least amount of steps as possible):**
No steps per se, unless you try running the example in [this issue](https://github.com/rancher/client-python/issues/10).

**Result:**
NA

**Other details that may be helpful:**
While Rancher's Golang type definitions could theoretically be used to build a bare-bones Golang client, I'm wondering if there are plans to either extend and support the [client-python](https://github.com/rancher/client-python) package, or perhaps create a new client. To that end, I've seen threads about the possibility of an OpenAPI spec - I'm wondering if that's on the cards too. 

While the Rancher API is a beauty to look at - I suppose the ease and convenience of a native wrapper library always does end up sounding far more attractive. If there are no existing plans for such a client(atleast in Python), then I'd definitely like to give it a stab.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): NA
- Installation option (single install/HA): NA

**Comment by vincent99** [comment]
https://github.com/rancher/client-python ?

**Comment by rudimk** [comment]
I've mentioned `client-python` above. Sadly it doesn't seem like it's maintained.

**Comment by vincent99** [comment]
Sorry, late.. it's a completely dynamic client that works with any of our APIs; there's little to nothing to "maintain".  We use python and that client for automated testing ourselves.

**Comment by rudimk** [comment]
Ah, I see. That’s beautiful. Thanks for clearing this up! Closing this issue now.
