### ISSUE TITLE
Rancher k3s with ingress.tls.source=secret privateCA=true NGINX external load balancer

### ISSUE THREAD

**Issue by anzharip** [rancher/rancher#27742]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
1. Following this guide: https://rancher.com/docs/rancher/v2.x/en/installation/
2. Provisioned self signed cert with https://hub.docker.com/r/superseb/omgwtfssl
3. OS Ubuntu 18.04

--

**Result:**
1. k3s running, rancher pod running, cattle-node-agent running
2. cattle-cluster-agent keeps restarting with error: 

```ERROR: https://lb.k3s/ping is not accessible (Failed to connect to lb.k3s port 443: Connection refused)```
lb.k3s is a private domain name for our installation

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5 on web UI
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted on premise on top of proxmox VM
- Machine type (cloud/VM/metal) and specifications (CPU/memory): bare-metal
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:45Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:45Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:57:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by maxisam** [comment]
Have the same issue. I don't enable private CA but I set tls=external.

somehow cattle-cluster-agent still send the request through https.
