### ISSUE TITLE
Rancher Monitoring: ClusterRole settings missing

### ISSUE THREAD

**Issue by AcidAngel21** [rancher/rancher#27748]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Activate the cluster monitoring in `Rancher 2.4.5`. Then check `exporter-kube-state-cluster-monitoring` logs

**Result:**
Following errors are seen in the logs:
<pre>E0626 08:36:05.291099 1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ValidatingWebhookConfiguration: validatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:cattle-prometheus:exporter-kube-state-cluster-monitoring" cannot list resource "validatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
E0626 08:36:05.388810 1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.NetworkPolicy: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:cattle-prometheus:exporter-kube-state-cluster-monitoring" cannot list resource "networkpolicies" in API group "networking.k8s.io" at the cluster scope
E0626 08:36:05.389499 1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.MutatingWebhookConfiguration: mutatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:cattle-prometheus:exporter-kube-state-cluster-monitoring" cannot list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
E0626 08:36:05.435740 1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.VolumeAttachment: volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:cattle-prometheus:exporter-kube-state-cluster-monitoring" cannot list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope</pre>

**Other details that may be helpful:**
If I add the missing `ClusterRoles` to `exporter-kube-state-cluster-monitoring`, the errors disappear.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.4.5`
- Installation option (single install/HA): `HA`

gzrancher/rancher#10900

**Comment by jiaqiluo** [comment]
The bug is reproduced in Rancher `v2.4.5` single-install 
monitoring version `0.1.1`

```
E0626 17:49:39.814477       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.MutatingWebhookConfiguration: mutatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:cattle-prometheus:exporter-kube-state-cluster-monitoring" cannot list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
E0626 17:49:40.296305       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.NetworkPolicy: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:cattle-prometheus:exporter-kube-state-cluster-monitoring" cannot list resource "networkpolicies" in API group "networking.k8s.io" at the cluster scope
E0626 17:49:40.595377       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ValidatingWebhookConfiguration: validatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:cattle-prometheus:exporter-kube-state-cluster-monitoring" cannot list resource "validatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
E0626 17:49:40.708028       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.VolumeAttachment: volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:cattle-prometheus:exporter-kube-state-cluster-monitoring" cannot list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope```

**Comment by jiaqiluo** [comment]
this bug does NOT exist in monitoring `v0.1.0`

**Comment by jiaqiluo** [comment]
in  monitoring `v0.1.0`
```
exporter-kube-state:
  enabled: false
  apiGroup: "monitoring.coreos.com"
  image:
    repository: rancher/coreos-kube-state-metrics
    tag: v1.8.0
```
V.S.

in  monitoring `v0.1.1`
```
exporter-kube-state:
  enabled: false
  apiGroup: "monitoring.coreos.com"
  image:
    repository: rancher/coreos-kube-state-metrics
    tag: v1.9.5
```

BUT, the `rbac.yaml` are the same in both versions

**Comment by jiaqiluo** [comment]
here is the list of missing permissions
```
 list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope 
 list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope 
 list resource "validatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope 
 list resource "networkpolicies" in API group "networking.k8s.io" at the cluster scope 
```

**Comment by jiaqiluo** [comment]
The chart is available in `dev-v2.4` branch

**Comment by jiaqiluo** [comment]
the bug fix is validated on `Rancher:v2.4.6-rc3` with monitoring chart `v0.1.2`
the branch of `system-chart` is `dev-v2.4` by default

The abovementioned errors are gone in the logs of `exporter-kube-state-cluster-monitoring`

**Comment by jiaqiluo** [comment]
wait for validating the issue in `rancher:master`

**Comment by jiaqiluo** [comment]
the bug fix is validated in `Rancher:master-3286-head` with monitoring chart `v0.1.2`
the branch of `system-library` is `dev-v2.4` by default

The abovementioned errors are gone in the logs of `exporter-kube-state-cluster-monitoring`
