### ISSUE TITLE
Proxied pod/exec requires extra get permission

### ISSUE THREAD

**Issue by nikkelma** [rancher/rancher#27740]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create two new Project roles:
  1. `Exec - Create` - inherits from `Kubernetes view`, granted `Create` on `pods/exec` for all resource groups
  2. `Exec - Get` - inherits from `Kubernetes view`, granted `Get` on `pods/exec` for all resource groups
- Add user A in project with `Exec - Create`
- Add user B in same project with `Exec - Get` and `Exec - Create`

**Result:**
- User A can perform `kubectl exec -n <ns> <pod>` through kubectl
- User A _cannot_ perform `Execute shell` on the same pod through Rancher UI
- User can perform `kubectl exec -n <ns> <pod>` through kubectl
- User _can_ perform `Execute shell` on the same pod through Rancher UI

**Other details that may be helpful:**
Although the Kubernetes API server allows exec on a pod with only `create pods/exec`, Rancher also requires `get pods/exec` to use the Execute Shell button.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3
- Installation option (single install/HA): HA

**Comment by KeithTt** [comment]
There is no this perm in the new version v2.6.3, what is the new option of this perm?

**Comment by 9numbernine9** [comment]
Ran into this issue recently as well with Rancher `2.8.3` . Adding `Get` on `pods/exec` allow the shell through the UI to work, but it seems odd when this isn't required via `kubectl exec`.
