### ISSUE TITLE
AWS EBS volume expansion via PVC not working in UI.

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#27746]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Create a PVC with size 25Gi.
- Attach the PVC to a Pod.
- Edit volume and increase the size to 30Gi.
- Delete the pod and start a new one, but use the same PVC.

**Result:**
Volume size stays 25Gi (in both AWS UI and inside Pod) , but capacity shown in UI is 30Gi

**Environment information**
- Rancher version : v2.4.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type : Custom (AWS)
- Machine type : Cloud
- Kubernetes version: Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

# Storage Class 

> kubectl get sc gp2-storage-class -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    field.cattle.io/creatorId: u-72e2noxvuk
    storageclass.beta.kubernetes.io/is-default-class: "true"
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2019-12-05T11:27:09Z"
  labels:
    cattle.io/creator: norman
  name: gp2-storage-class
  resourceVersion: "9131276"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/gp2-storage-class
  uid: 98f8e9b5-e16c-41bf-b907-660494aa7e31
parameters:
  encrypted: "false"
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
> 

# PV details 

> kubectl get pv pvc-7412f0ff-35ae-418b-83d4-f28f174d7f01 -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
  creationTimestamp: "2019-12-05T11:27:52Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: eu-west-1
    failure-domain.beta.kubernetes.io/zone: eu-west-1c
  name: pvc-7412f0ff-35ae-418b-83d4-f28f174d7f01
  resourceVersion: "45895020"
  selfLink: /api/v1/persistentvolumes/pvc-7412f0ff-35ae-418b-83d4-f28f174d7f01
  uid: 43140ce4-08c2-4fb7-894a-866a3be1966c
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://eu-west-1c/vol-0290dfc0f83f1826e
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test-pv
    namespace: default
    resourceVersion: "1486"
    uid: 7412f0ff-35ae-418b-83d4-f28f174d7f01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - eu-west-1c
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - eu-west-1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2-storage-class
  volumeMode: Filesystem
status:
  phase: Bound
> 

# PVC Details 

> kubectl get pvc -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"test-pv","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"3Gi"}}}}'
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
      volume.kubernetes.io/storage-resizer: kubernetes.io/aws-ebs
    creationTimestamp: "2019-12-05T11:27:46Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: test-pv
    namespace: default
    resourceVersion: "45895095"
    selfLink: /api/v1/namespaces/default/persistentvolumeclaims/test-pv
    uid: 7412f0ff-35ae-418b-83d4-f28f174d7f01
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 25Gi <<<<<----------------- Request still stays are 25Gi
    storageClassName: gp2-storage-class
    volumeMode: Filesystem
    volumeName: pvc-7412f0ff-35ae-418b-83d4-f28f174d7f01
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 30Gi <<<<<------------------- Status shows are 30Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

# Pod spec after expanding the volume to 30 Gig 

> kubectl get pods  -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cattle.io/timestamp: "2020-06-26T10:23:58Z"
      cni.projectcalico.org/podIP: x.x.x.x/32
      cni.projectcalico.org/podIPs: x.x.x.x/32
    creationTimestamp: "2020-06-26T10:23:58Z"
    generateName: foo-7dbfc57764-
    labels:
      pod-template-hash: 7dbfc57764
      workload.user.cattle.io/workloadselector: deployment-default-foo
    name: foo-7dbfc57764-9pkf4
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: foo-7dbfc57764
      uid: 5c0ca1a5-2fa0-436b-843d-981a1ef83d43
    resourceVersion: "45895679"
    selfLink: /api/v1/namespaces/default/pods/foo-7dbfc57764-9pkf4
    uid: f937a6df-456a-4588-ac80-3929175da59a
  spec:
    containers:
    - image: ubuntu:xenial
      imagePullPolicy: Always
      name: foo
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
        runAsNonRoot: false
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      tty: true
      volumeMounts:
      - mountPath: /mnt
        name: vol1
        subPath: extradata
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-pmltb
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: ip-xx-xx-xx-xx.eu-west-1.compute.internal
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: test-pv
    - name: default-token-pmltb
      secret:
        defaultMode: 420
        secretName: default-token-pmltb
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2020-06-26T10:23:58Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2020-06-26T10:24:05Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2020-06-26T10:24:05Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2020-06-26T10:23:58Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://73945adc50e28be1c836eb987b7dd5fb13387eeb77758b2eb1c9d9f697a11122
      image: ubuntu:xenial
      imageID: docker-pullable://ubuntu@sha256:961d69a9344d5315cd83b722f2dc34a72bc9dc4a7258fdd703c3b5d64b450f87
      lastState: {}
      name: foo
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2020-06-26T10:24:05Z"
    hostIP: x.x.x.x
    phase: Running
    podIP: x.x.x.x
    podIPs:
    - ip: x.x.x.x
    qosClass: BestEffort
    startTime: "2020-06-26T10:23:58Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""  
```
** Workaround**

Edit PVC using kubectl and change request to match the size of the PV fixes the issue.

```
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
```

gz#10881
gz#13510

**Comment by sowmyav27** [comment]
**Verified on 2.4.5 and 2.3.8**

**Steps:**

- Create an AWS cloud provider cluster as a standard user.
- Create a storage class `st1`
- Edit the storage class and set `allowVolumeExpansion: true`
- Create a PVC using this class `vol-1`, size: 25G
- Deploy a workload and attach this PVC
- The volume in AWS UI and the PVC in Rancher UI size show 25GiB
- Edit the PV in Rancher, set the size to 30Gi
- View in API of the PVC 

```
"resources": {
"requests": {
"storage": "25Gi"
},
"type": "/v3/project/schemas/resourceRequirements"
},
"state": "bound",
"status": {
"accessModes": [
"ReadWriteOnce"
],
"capacity": {
"storage": "30Gi"
},
"phase": "Bound",
"type": "/v3/project/schemas/persistentVolumeClaimStatus"
},
```
- The volume in AWS UI and inside the pod (exec in the pod) shows 25GiB and the PVC in Rancher UI size show 30GiB
- However changing storage request to match the size of the PV to 30GiB does NOT fix the issue

**Comment by ansilh** [comment]
Thanks for testing it @sowmyav27 .
Yes, the workaround have slight change.

The **_request_** values have to be **_greater than the capacity_** to get new size.

```
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 35Gi <<<<<----------------- Value greater than "capacity"
    storageClassName: gp2-storage-class
    volumeMode: Filesystem
    volumeName: pvc-7412f0ff-35ae-418b-83d4-f28f174d7f01
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 30Gi <<<<<------------------- 
    phase: Bound
```

**Comment by sowmyav27** [comment]
On 2.4.5, after these step - https://github.com/rancher/rancher/issues/27746#issuecomment-651961851 and changing PV size to 30Gi in Rancher UI, the `requests` storage says 25G
```
"requests": {
"storage": "25Gi"
},
```

- Edit PVC through kubectl and change the request storage to 33G
- Save the changes made.
- The size of the volume in AWS UI changes to 33. 
- ON Rancher UI, --> VPC --> Size is seen as 33GB
- Delete the pod and scale up the workload. The exec shell of pod now shows 33Gb size.

**Comment by PennyScissors** [comment]
We currently don't support volume expansion in the Rancher UI, although it can be done directly via the API UI or kubectl at your own risk if you enable `allowVolumeExpansion: true` in the storage-class and increase the size of the persistent-volume-claim (PVC) of that storage-class. The `capacity` that can be modified via the Rancher UI (Cluster Manager) in `Cluster > Storage > Persistent Volumes > Three dots of PV > Edit` is not for volume expansion.

**Comment by ansilh** [comment]
Thanks for confirming @PennyScissors 

> The capacity that can be modified via the Rancher UI (Cluster Manager) in Cluster > Storage > Persistent Volumes > Three dots of PV > Edit is not for volume expansion

- Is there a reason to have this option in UI? From a user standpoint, I would think that this UI option is for expanding volume.
- Can we consider volume expansion via UI as a new feature? Do we need a new issue to address this?

**Comment by PennyScissors** [comment]
@ansilh A potential use case could be if the storage system doesn’t support volume expansion from Kubernetes, but able to expand it in the system itself. Then the user might want to update the PV to match the real volume size (which has been expanded though the system itself instead of Kubernetes). Given the volume expansion is there since v1.16, is a rare case. I agree with you that from a user's standpoint you would think that's what that option is for, and we should probably have a separate issue for the UI team to address that concern and add volume expansion via the UI.

**Comment by ansilh** [comment]
Hi @maggieliu , Could you please assign this to UI team?

**Comment by PennyScissors** [comment]
Summarizing things for the UI team:

This issue shows the behavior we expect because the `capacity`displayed in the Rancher UI is not meant for expanding a volume as it modifies the `Capacity` of the persistent volume (PV), but the resizing is done by increasing the size of its underlying persistent volume claim (PVC) instead. The backend seems to support volume expansion, but the Rancher UI does not because it wasn't something we added intentionally.

Taking that into consideration, I would say this is more like an enhancement request which includes the following:

1. Allow users to enable `allowVolumeExpansion: true` when creating a storage class in the Rancher UI.

2. Update the PV and PVC pages to allow users to resize a volume and display, display the updated size accordingly, and maybe re-organize things so that users don’t get confused with the `Capacity` that’s in the PV page already which is not for volume expansion. We should consider removing it altogether, since users can always update that through the API directly if needed.

3. Add validation where necessary. For example, you shouldn't be able to expand a volume if the PVC's storage class doesn't have volume expansion enabled.

**Comment by westlywright** [comment]
The UI will be exposing the `allowVolumeExpansion` parameter on the storage class. 
The UI will be adding an action to the PVC action menu that allows a user to resize (still not a full edit) the PVC. 
In both cases, editing a PV or resizing a PVC, the UI will NOT add validation or disable PV capacity edit, so it is either going to work or it wont. Additionally help text has been added to both cases linking to both the rancher and k8s docs about how volumes and volume expansion works.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `db350a63b`**

- Deployed a cloud provider AWS enabled setup.
- Add a storage class. allowVolumeExpansion is available on the UI. Default value: Disabled.

<img width="448" alt="Screen Shot 2020-12-02 at 2 10 04 PM" src="https://user-images.githubusercontent.com/26032343/100937721-4adbc900-34a8-11eb-8f07-04f59adac8a8.png">

- Create a Storage class with `allowVolumeExpansion: enabled`
- create a PVC using this storage class.
- Click on the ellipsis. An option `Resize` is available

<img width="787" alt="Screen Shot 2020-12-02 at 2 14 10 PM" src="https://user-images.githubusercontent.com/26032343/100938085-e8cf9380-34a8-11eb-8718-40cdd340a8c1.png">
