### ISSUE TITLE
Host.remove triggers re-order of create index of already deployed services

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2774]
When confirming that host.remove triggers an update of hosts in the metadata, there was a re-order of services by create index in the metadata.

Steps I took:

1. Added 6 hosts to Rancher
2. Created service with 10 services. 

While removing hosts, new containers would be created for the service. In most cases, the order of createindex would match what had happened, but in 1 case, the create index was re-ordered and maintained the new create index order.

**Comment by alena1108** [comment]
@deniseschannon I don't understand...re-ordered how? Could you put an example here?

**Comment by alena1108** [comment]
After talking with @deniseschannon clarified what re-ordered means. Basically the containers are not ordered in /latest/containers endpoint by their create index sometimes. But in fact the order is never ensured today. Lets transform this bug to enhancement as I think it would be nice to order containers based on the create-index.

**Comment by alena1108** [comment]
@deniseschannon order is in place, enjoy :)

**Comment by deniseschannon** [comment]
Added service1 of scale 10 to a Rancher setup that already had some services. Using `curl http://rancher-metadata/latest/containers` in the container, I would have assumed that the last 10 containers would be from service1. @alena1108 is that correct assumption?

**Comment by alena1108** [comment]
@deniseschannon thats correct. I totally forgot that create_index is unique per service, not per environment. So service1 and service2 can have overlapping values for this field, and sorting by it can result in containers' order being mixed. We should sort by id instead

**Comment by deniseschannon** [comment]
Verified with v0.49.0-rc1
