### ISSUE TITLE
Invalid SSL from web browser

### ISSUE THREAD

**Issue by NMark02** [rancher/rancher#27765]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
Followed these instructions https://rancher.com/blog/2020/run-rancher-k3s-mysql

**Result:**
Web browser shows "invalid SSL certificate"

**Other details that may be helpful:**
NAME                 STATUS    MESSAGE   ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
NAME       STATUS   ROLES    AGE     VERSION
k3snode1   Ready    master   2d22h   v1.18.4+k3s1
k3snode2   Ready    master   2d22h   v1.18.4+k3s1

kubectl get pods -n kube-system
NAME                                     READY   STATUS      RESTARTS   AGE
metrics-server-7566d596c8-twmmg          1/1     Running     0          2d22h
local-path-provisioner-6d59f47c7-whff8   1/1     Running     0          2d22h
helm-install-traefik-f8989               0/1     Completed   0          2d22h
coredns-8655855d6-rfqqp                  1/1     Running     0          2d22h
svclb-traefik-5z497                      2/2     Running     0          2d22h
traefik-758cd5fc85-48qmq                 1/1     Running     0          2d22h
svclb-traefik-4cm22                      2/2     Running     0          2d22h

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):
kubectl version --short && kubectl get componentstatus && kubectl get nodes && kubectl cluster-info
Client Version: v1.16.0
Server Version: v1.18.4+k3s1

- Docker version (use `docker version`):

```
Client:
 Version:           3.0.11+azure
 API version:       1.40
 Go version:        go1.12.17
```
Thanks for any help you can provide

**Comment by vincent99** [comment]
The default install generates self-signed certificates, which your browser correctly doesn't trust by default.  To get something it does trust you can:

- Tell your browser to trust the one we generated
- Buy one from a certificate authority and give it to us
- Use Let'sEncrypt to generate a cert (which is recognized by browsers)

https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/helm-rancher/#4-choose-your-ssl-configuration

**Comment by NMark02** [comment]
thanks @vincent99 I will give it a try. Thanks for the quick response. much appreciated
