### ISSUE TITLE
[UI][2.4.5] Project Owner unauthorized to create project-scoped registry secrets

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/rancher#27769]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Create downstream cluster from Rancher v2.4.5
1) Create standard-user local user and assign Project Owner permissions to default project in downstream cluster
1) Log in as standard user and attempt to create a registry secret that is scoped to "Available to all namespaces in this project"

**Result:**  
![image](https://user-images.githubusercontent.com/49007005/85967737-400f9a80-ba17-11ea-9fc0-3b6de9010bef.png)

nginx-ingress:
`POST /v3/projects/c-wrl7f:p-qtcjp/dockercredential HTTP/2.0" 403 107 "https://rancher-host/p/c-wrl7f:p-qtcjp/registries/add" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0" 237 0.001 [cattle-system-rancher-80] [] 10.42.0.14:80 107 0.000 403 b134965754232e7215643e475cd05052
`

**Other details that may be helpful:**
Creating namespace scoped secrets from the same interface works correctly

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.5
- Installation option (single install/HA):
HA

gzrancher/rancher#10916

**Comment by anouarchattouna** [comment]
**Other details that may be helpful:**
Registry credential is successfully created from the API using the same user `HTTP/1.1 201`
```json
HTTP/1.1 POST /v3/project/c-vkxct:p-hkbzn/dockercredentials
Host: mydomain.com
Accept: application/json
Content-Type: application/json
Content-Length: 220

{
  "name": "test-all-namespaces-created-by-project-owner-api",
  "namespaceId": "",
  "projectId": "c-vkxct:p-hkbzn",
  "registries": {
    "custom-docker-registry.docker.mydomain.com": {
      "username": "user",
      "password": "****"
    }
  }
}
```

Related issues https://github.com/rancher/rancher/issues/26981 https://github.com/rancher/rancher/issues/27456

**Comment by sowmyav27** [comment]
**Reproduced the issue on `2.4.5`**

- Assign User1 as Project owner of a project say Default project
- Login as User1
- Create a Registry Credential, with scope: `Available to all namespaces in this project`.
- Click on Save, user sees a `403 unauthorized` error

**Note:**
- The user - User1 is able to create a registry cred with scope `Available to a single namespace`. No error is seen in this case.
- Project owner user1 is able to create a Registry Credential, with scope: `Available to all namespaces in this project` in rancher: `v2.3.5`

**Comment by sowmyav27** [comment]
**verified on 2.4-head - commit id: `cf8f4a6f5` ui tag: `latest-2.4`** and on **master-head - commit id: `1a5e5622b`, ui tag: `latest2`**

Issue is seen fixed.

**Steps:**

- Create a standard user User1 and login as the user. Create a cluster.
- Assign User2 as Project owner of a project say Default project (As admin)
- Login as User2
- Create a Registry Credential, with scope: `Available to all namespaces in this project`.

```
name: "test"
namespaceId: null
registries: {index.docker.io: {username: "user1", password: "test"}}
type: "dockerCredential"
```
- Registry Cred is created successfully. The request sent as seen in UI is ^^^ 
- No error seen on the UI
- As a cluster owner user1 also, user is able to Create a Registry Credential, with `scope: Available to all namespaces in this project`.
