### ISSUE TITLE
[KEv2] Rework EKS managed node groups upgrade

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#27777]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
upgrade nodegroup version

**Result:**
Takes ~50 mins for 1 node, this is due to the method AWS uses for upgrading managed node groups: https://docs.aws.amazon.com/eks/latest/userguide/managed-node-update-behavior.html

`The Auto Scaling group maximum size and desired size are incremented by twice the number of distinct Availability Zones of the Auto Scaling group to ensure at least one new instance comes up in every Availability Zone of your node group.`

Nodegroups will no longer automatically upgrade. Once a cluster is upgraded a user will be able to upgrade the nodegroup manually or they can create a nodegroup and delete the old node group.

**Other details that may be helpful:**
EKSctl instructs the user to create a new node group with the desired version number, then delete the old node group:
https://eksctl.io/usage/cluster-upgrade/

**Comment by rmweir** [comment]
some scenarios and their expected behaviors after PR is in:
1. create regular cluster with proper kubernetes version and proper nodegroup version
success
2. create cluster with unsupported kubernetes version but valid format
if kubernetes version doesn't match a nodegroup version a controller error will quickly be shown for that. Otherwise once cluster is being created error will show.
3. create cluster with invalid kubernetes version format
same as 2.
4. create cluster with no kubernetes version
quick controller error
5. create cluster with empty kubernetes version
api level error saying kubernetes version cannot be empty string
6. create nodegroup with no version
quick controller error
7. create nodegroup with empty version
api level error saying kubernetes version cannot be empty string
8. create nodegroup with invalid version format
quick controller error saying nodegroup version must match cluster's kubernetes version

**Comment by deniseschannon** [comment]
Based on what I can see, this looks fixed with eks-operator v0.1.0-rc30 and can be tested now

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 67e24f2`

Tested import EKS cluster on the following scenarios:
- create nodegroup with no version
quick controller error
![Screen Shot 2020-09-22 at 5 07 27 PM](https://user-images.githubusercontent.com/57409052/93949739-464fa300-fcf6-11ea-96ee-c23f4a17ecc6.png)
```
{
"baseType": "error",
"code": "InvalidFormat",
"fieldName": "eksConfig",
"message": "InvalidFormat 422: Value can not be converted to type eksClusterConfigSpec: {\r\n\t\"amazonCredentialSecret\": \"cattle-global-data:cc-j6dwc\",\r\n\t\"displayName\": \"aaron-
...
"status": 422,
"type": "error"
}
```
Additional note: setting version to `Null` instead of an empty field, will create a node group with the same k8s version as the cluster.

- create nodegroup with empty version
api level error saying kubernetes version cannot be empty string
```
{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "nodegroup [aaron-ng3] version cannot be empty string",
"status": 422,
"type": "error"
}
```

- create nodegroup with invalid version format
quick controller error saying nodegroup version must match cluster's kubernetes version
```
InvalidParameterException: Nodegroup Kubernetes version should be equal to Cluster kubernetes version 1.17 or NodeGroup kubernetes version 1.17 { RespMetadata: { StatusCode: 400, RequestID: "affb029d-0c5b-4c45-b1b4-fcb60dd7543a" }, ClusterName: "aaron-eks4", Message_: "Nodegroup Kubernetes version should be equal to Cluster kubernetes version 1.17 or NodeGroup kubernetes version 1.17", NodegroupName: "aaron-ng3" }
```

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 67e24f2`

Tested import EKS cluster on the following scenarios:
- create nodegroup with no version
quick controller error
![Screen Shot 2020-09-22 at 5 07 27 PM](https://user-images.githubusercontent.com/57409052/93950814-60d74b80-fcf9-11ea-8055-6550f7c4ce4d.png)
```
{
"baseType": "error",
"code": "InvalidFormat",
"fieldName": "eksConfig",
"message": "InvalidFormat 422: Value can not be converted to type eksClusterConfigSpec: {\r\n\t\"amazonCredentialSecret\": \"cattle-global-data:cc-j6dwc\",\r\n\t\"displayName\": \"aaron-
...
"status": 422,
"type": "error"
}
```
Additional note: setting version to `Null` instead of an empty field, will create a node group with the same k8s version as the cluster.

- create nodegroup with empty version
api level error saying kubernetes version cannot be empty string
```
{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "nodegroup [aaron-ng3] version cannot be empty string",
"status": 422,
"type": "error"
}
```

- create nodegroup with invalid version format
quick controller error saying nodegroup version must match cluster's kubernetes version
```
InvalidParameterException: Nodegroup Kubernetes version should be equal to Cluster kubernetes version 1.17 or NodeGroup kubernetes version 1.17 { RespMetadata: { StatusCode: 400, RequestID: "affb029d-0c5b-4c45-b1b4-fcb60dd7543a" }, ClusterName: "aaron-eks4", Message_: "Nodegroup Kubernetes version should be equal to Cluster kubernetes version 1.17 or NodeGroup kubernetes version 1.17", NodegroupName: "aaron-ng3" }
```

**Comment by sowmyav27** [comment]
**Validated on master-head commit id: `0516436`**

- create regular cluster with proper kubernetes version and proper nodegroup version - cluster gets created successfully
- create cluster with unsupported kubernetes version but valid format - k8s version - 1.13 - error seen on cluster `Error creating cluster: InvalidParameterException: unsupported Kubernetes version { RespMetadata: { StatusCode: 400, RequestID: "0616cfbb-f406-4139-8aae-44db2cb3b71c" }, ClusterName: "sowmya-api-2a", Message_: "unsupported Kubernetes version" }`
- create cluster with invalid kubernetes version format - `kubernetesVersion": "abc",` - Error seen on the cluster: `Error creating cluster: InvalidParameterException: unsupported Kubernetes version { RespMetadata: { StatusCode: 400, RequestID: "9297769e-c372-47d2-b4be-e28f9a770ea3" }, ClusterName: "sowmya-api-1", Message_: "unsupported Kubernetes version" }`
- create cluster with no kubernetes version - Cluster stuck in Provisoning with error `Field [kubernetesVersion] cannot be nil for non-import cluster [c-fsngg]`
- create cluster with empty kubernetes version - error seen in API
```
{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "cluster kubernetes version cannot be empty string",
"status": 422,
"type": "error"
}
```
- create nodegroup with no version - Cluster stuck in provisioning with error `Field [version] cannot be nil for nodegroup [sow] in non-nil cluster [c-wpx9n]`
- create nodegroup with empty version - error in API
```
{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "nodegroup [sow] version cannot be empty string",
"status": 422,
"type": "error"
}
```
- create nodegroup with invalid version format - Cluster stuck in provisioning with error `Nodegroup [sow] version must match cluster [c-pqsvh] version on create`
