### ISSUE TITLE
Grafana with persistence enabled will not seamlessly upgrade

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/rancher#27779]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Launch cluster-monitoring or project-monitoring v0.1.0 with persistence enabled for Grafana
Upgrade chart to v0.1.1

**Result:**
The replacement Grafana pod in the deployment is created before the original pod is deleted, resulting in a stuck upgrade as the PVC is still bound to the first pod.

**Other details that may be helpful:**
maxSurge is currently undefined in the chart, so defaults to 25%. Changing to 0% should resolve this.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.5
- Installation option (single install/HA):
HA

gz#10888

**Comment by sangeethah** [comment]
Relating to https://github.com/rancher/rancher/issues/27450

**Comment by jiaqiluo** [comment]
closed. duplication of https://github.com/rancher/rancher/issues/27450
