### ISSUE TITLE
istio ingress gateway clashes with traefik ports for loadBalancer

### ISSUE THREAD

**Issue by spicysomtam** [rancher/rancher#27770]
**What kind of request is this (question/bug/enhancement/feature request):** bug/question/enhancement?

**Steps to reproduce (least amount of steps as possible):** 
* Deploy istio in a k3s based cluster that uses traefik ingress using the rancher gui.
* Enable Ingress Gateway using option Loadbalancer.
* Enable istio and wait for it to deploy.

**Result:**
* Pods fail to deploy on nodes due to port conflict for 80/443 (traefik already has these).

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.4
- Installation option (single install/HA): 5 node cluster (2 masters; 3 agents) using k3s install method.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Deployed in aws.
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 1.18

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:45Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Not applicable
```

As a work around, we have deployed istio as nodeport, and then edit the service (its scripted as follows):
```
kubectl get  svc/istio-ingressgateway -o yaml  | \
    sed -e 's/port: 80/port: 8480/' -e 's/port: 443/port: 8443/' -e 's/type: NodePort/type: LoadBalancer/' | \
    kubectl replace -f -
```

I think an enhancement is needed here to allow you to specify the http and https ports to use in the rancher gui, so you can set ports that don't clash with traefik.

Then we have the benefit of the default treafik ingress for k8s, plus the ability to define a second ingress for istio. Whether you choose to front both of these with a load balancer is up to you.

```

**Comment by GodSpeedXI** [comment]
I got the same problem here. I try to delete traefik lb and add config with istio gateway to access to rancher ui by using tls mode passtrough but it didn't work and got ERR_SSL_PROTOCOL_ERROR.
