### ISSUE TITLE
Readonly/Restricted User - Custom Host page throws Error

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2778]
Is it possible to disable the add host button for the restricted and read only user? It's deceiving that it looks like it would work . Keep that i

Issues with having it enabled:
1. Go through all steps to add host before getting "Method not allowed"
2. Click on "Custom" host and directed to Error message, but no indication why the error exists.

This issue is to track that when you click on Custom host, it directs to error page.

**Comment by vincent99** [comment]
Yes, with #2779 you wouldn't be able to get here in the first place..
