### ISSUE TITLE
Full SNMP integration without having to setup a webhook

### ISSUE THREAD

**Issue by robertwedd** [rancher/rancher#27782]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Feature being requested:**
What we´d like to see is an SNMP option here:
![image008](https://user-images.githubusercontent.com/39080630/86120966-7ca1cb80-bad5-11ea-94b9-975ac713ded6.jpg)
Here we'd just input our SNMP trap host and avoid the need to create the Prometheus webhook which creates more work filtering and cleaning up on our end. 

SNMP is a standard for some companies' infrastructure monitoring, so though this may require the deployment of a MIB, it makes sense to add it as a notifier option.

gz#10958

**Comment by Tejeev** [comment]
The alerts recieved using the SUSE webhook (https://github.com/SUSE/prometheus-webhook-snmp) have the following format:
```{\"alert_name\": \"A high number of leader changes within the etcd cluster are happening\", \"alert_type\": \"metric\", \"cluster_name\": \"prod01 (ID: c-tttll)\", \"comparison\": \"greater than\", \"duration\": \"3m\", \"endpoint\": \"metrics\", \"expression\": \"increase(etcd_server_leader_changes_seen_total[1h])>3\", \"group_id\": \"c-tttll:etcd-alert\", \"namespace\": \"cattle-prometheus\", \"node\": \"nbnslxrrama03\", \"prometheus\": \"cattle-prometheus/cluster-monitoring\", \"prometheus_from\": \"prod01\", \"rule_id\": \"c-tttll:etcd-alert_high-number-of-leader-changes\", \"service\": \"expose-kube-etcd-metrics\", \"threshold_value\": \"3\"} --- 174:15:31:06.32 --- {\"status\": \"firing\", \"labels\": {\"alert_name\": \"A high number of leader changes within the etcd cluster are happening\", \"alert_type\": \"metric\", \"cluster_name\": \"prod01 (ID: c-tttll)\", \"comparison\": \"great```

It looks like it's splitting each element into strings in a list and sending this on.  If we can clean this up to an easy deploy and something legible on the receiving end, it would be a useable solution for the need for SNMP traps
