### ISSUE TITLE
kubelet certificate expired, rotation will not replace it

### ISSUE THREAD

**Issue by horihel** [rancher/rancher#27783]
**What kind of request is this (question/bug/enhancement/feature request):**
bug (or user error?)

**Steps to reproduce (least amount of steps as possible):**
* on the node (on all nodes): Find an outdated cert for kubelet in /var/lib/kubelet/pki
* check (with openssl s_client) that his is the actually used (outdated) Cert.
* try to rotate certificate using rancher GUI

**Result:**
* Rotation completes, no errors
* No errors or warning about certificates in Rancher GUI
* Certificate in /var/lib/kubelet/pki is untouched and still expired.

Any requests to the kubelet that don't involve ignoring verification will fail.

Mind that the cluster is still operating fine, so the impact is only external tools spitting errors.

**Other details that may be helpful:**
This cluster is rather old (provisioned with rancher 2.0 or early 2.1 i think).

**Environment information**
- Rancher version : 2.4.5
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal (running ubuntu 18.04)
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

**Comment by gaby** [comment]
I'm running into the same issue. No matter what I try, the certificate does NOT get updated.

**Comment by superseb** [comment]
This is not handled by Rancher/RKE, only if you configure `generate_serving_certificate: true` under `kubelet` as described on https://rancher.com/docs/rke/latest/en/config-options/services/#kubelet

**Comment by gaby** [comment]
@superseb Thank you, but even with that option the certificate does NOT get rotated.

**Comment by superseb** [comment]
It doesn't rotate the certificate in the location you mentioned, because it will not be using that anymore. The argument `tls-cert-file` is used to specify what certificate the kubelet should use.
