### ISSUE TITLE
Can not login to rancher UI anymore - Rancher : mvcc database space exceed

### ISSUE THREAD

**Issue by v15170r** [rancher/rancher#27789]
**What kind of request is this (question/bug/enhancement/feature request):** bug!? (it's more an issue)

**Steps to reproduce (least amount of steps as possible):**  Since yesterday - without any change from the outside - I have some issues with my Rancher. I noticed this the first time when the Login via Rancher UI failed. After some research I found this issue could be related to the etcd database size.
![image](https://user-images.githubusercontent.com/54867008/86159602-97c20a80-bad8-11ea-9627-0ded6ad26da6.png)

So I used this threat as a guide for my analyze steps: https://etcd.io/docs/v3.4.0/op-guide/maintenance/#space-quota / https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/maintenance.md#space-quota 

_The etcd database quota size was exceeded._ 

The auto compacting is working (i can see that in the logs). I also tried compacting the storage, but rancher still complains about the database mvcc: database space exceed. I also did a defragmentation - without any change.

From:
![image](https://user-images.githubusercontent.com/54867008/86159977-1f0f7e00-bad9-11ea-91f3-5b36821a3e3e.png)
To:
![image](https://user-images.githubusercontent.com/54867008/86159996-2767b900-bad9-11ea-911f-d590092ed3ab.png)

And... the alarm list is also empty.

**Other details that may be helpful:**
Rancher Log:
![image](https://user-images.githubusercontent.com/54867008/86159811-d8ba1f00-bad8-11ea-85dd-dcf8be2fd1e6.png)
Etcd Log:
![image](https://user-images.githubusercontent.com/54867008/86159870-f5eeed80-bad8-11ea-98ff-34c2783db905.png)

I also tried several restarts from Docker, Etcd, Rancher, ...

Does anyone have an idea how to fix this issue?

I really appreciate your support !!!

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 2 Metal Nodes
- Kubernetes version (use `kubectl version`):

```
Client Version: v1.13.9
Server Version: v1.15.3
```

- Docker version (use `docker version`):

```
Server Version: 18.06.1-ce
```

**Comment by v15170r** [comment]
**Any idea in which direction i can investigate?** 

The cluster itself seems to work but the Rancher is my main Administration tool for my k8s cluster.

**Comment by kubealex** [comment]
it's not related to rancher, did you check for disk space on your master nodes? this seems related to etcd storage/limits

**Comment by v15170r** [comment]
> it's not related to rancher, did you check for disk space on your master nodes? this seems related to etcd storage/limits

Hi kubealex, thanks for your response. 
There are no alarms in etcd. And general storage on the master node looks also good.
![image](https://user-images.githubusercontent.com/54867008/86603690-50bd9480-bf72-11ea-9563-788da4223313.png)
Any idea how i can check if there is a internal storage limit?
Cheers!
