### ISSUE TITLE
KEv2: Http Proxy - AWS Signing Incorrect

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#27792]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

When attempting to make a proxy request to an Amazon endpoint the logic used to get the region and service does not take global Amazon services, like IAM, into account. 

The logic [here](https://github.com/rancher/rancher/blob/48752a0a214008c9ee556d2935c1c3ceb1b46ab1/pkg/httpproxy/sign.go#L74) assumes host coming in is defined as `https://{service}.{region}.amazonaws.com` but for global services like IAM that is not the case. Note there are special cases for china and gov, see the IAM endpoints [here](https://docs.aws.amazon.com/general/latest/gr/iam-service.html). When the code is run through the aws signer [here](https://github.com/rancher/rancher/blob/48752a0a214008c9ee556d2935c1c3ceb1b46ab1/pkg/httpproxy/sign.go#L93), region is `amazonaws` when it should either be an empty string or null (I am not sure of the conventions for this on the go sdk).

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `6d6199121`**

- User is able to see the KMS keys available while creating a hosted EKS cluster and while creating an AWS node template
