### ISSUE TITLE
Restricted User  - Add host button should be disabled

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2779]
Relevant issue: #1992

v0.47.0-rc1

Local Authentication is enabled with a restricted user in an environment.

When logged in as restricted user, the add button for hosts should be disabled. 

Currently we are allowed to launch the add page and once the user attempts to create the objects , we get a "Method not allowed" message.

It would be better to disable these add options.

**Comment by vincent99** [comment]
Basically the same as https://github.com/rancher/rancher/issues/1990, but different kind of user.
