### ISSUE TITLE
EKS kubectl not accessible in rancher shell

### ISSUE THREAD

**Issue by venkatt007** [rancher/rancher#27795]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Setup EKS cluster from rancher
Setup monitoring with rancher

**Result:**
Cluster node agents restarts frequently
Metrics server unavailable

**Other details that may be helpful:**
Able to deploy pods and access it 
Able to access the cluster using kubectl outside rancher

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
2.4.5

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): EC2 - M5.xlarge 2 nodes
- Kubernetes version (use `kubectl version`): 1.15

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by aaronRancher** [comment]
Was not able to reproduce this issue with Rancher `v2.4.5`. With monitoring enabled on cluster.
k8s version `v1.15.11-eks-af3caf`
Machine type: M5.xlarge 2 nodes

Was able to access shell and run commands.
![Screen Shot 2020-07-01 at 5 00 53 PM](https://user-images.githubusercontent.com/57409052/86302064-71759b00-bbbc-11ea-9506-fa72221c9f3d.png)

If there are other details which would help investigate this issue, please post them. Thank you.
