### ISSUE TITLE
There is a delay when pinging between containers from different hosts on initial ping.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#278]
In the first attempts to ping containers on different hosts, there is a delay before the containers are linked together. Typically losing the first 4 packets before the packets are sent back.

Any attempts to ping after the initial set up has no packet loss. 

No real issue, but I thought we could investigate to see if the delay could be improved.

**Comment by vincent99** [comment]
I've seen this too and it does seem excessively long.  It might be long enough for an application's connection to timeout and therefore fail to start.

**Comment by deniseschannon** [comment]
Even with the new DNS changes, this delay still exists as of v0.23.0-rc1.

**Comment by vincent99** [comment]
Yeah, the delay isn't DNS, it's somewhere in setting up the IPSec tunnel between the two points.  We will have to see if it can be improved, or preemptively exchange keys to setup the connection ahead of time.

**Comment by deniseschannon** [comment]
Verified with v0.56.0 that this is eliminated with the new ipsec networking.
