### ISSUE TITLE
Edit External Service - Changing from IP to hostname

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2780]
UI reskin - Build master from 11/23

Steps to Reproduce:
1. Add an external service and start from detailed stack view
2. Edit external service from detailed stack view. Change from using an IP to a hostname
3. Click on Save

Result: New hostname isn't saved and then service is in bad state which causes stack to be in bad state. (Not viewable in Rancher, blank screen)

**Comment by deniseschannon** [comment]
Please make sure the detailed stack view is also refreshed with the new hostname.

**Comment by vincent99** [comment]
I don't remember exactly what I changed but I think I fixed this @deniseschannon

**Comment by deniseschannon** [comment]
Verified with latest UI (evening 11/24)
