### ISSUE TITLE
deploying K8s cluster on vSphere using the Rancher server: "Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available. Last error: Maximum number of retries (60) exceeded"

### ISSUE THREAD

**Issue by guillierf** [rancher/rancher#27813]
using Rancher 2.4 server to deploy a K8s cluster on vSphere:

node template configuration:
creation method: clone an existing VM

I can see the different VMs created correctly on vSphere (CP, etcd, worker) and each one has a different IP obtained from DHCP.

However, on the Rancher web UI, I see this error message under each node:

"Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available. Last error: Maximum number of retries (60) exceeded"

how can I troubleshoot this?
how is the SSH process here (who is SSHing to the node? and using which account on the node?)

thanks in advance

**Comment by guillierf** [comment]
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/22355884/86396488-da115600-bc56-11ea-8072-4a065124aac6.png">

**Comment by cmccallu** [comment]
I have exactly the same problem with both a RancherOS & Ubuntu VM I'm trying to clone from. I'm assuming it needed a rancher user which I added to the Ubuntu VM and included a 
#cloud-config
ssh_authorized_keys:
  - ssh-rsa  ...

Previously I successfully used the boot2docker ISO but that method appears to be now broken in v2.4.5 I now trying

Could well be user error but better documentation and clear tutorials and steps would help here I believe!

**Comment by cmccallu** [comment]
The suggestion here worked for me https://github.com/rancher/os/issues/3016#issuecomment-639611051 but I used
https://github.com/rancher/os/releases/download/v1.5.6/rancheros-vmware-autoformat.iso

**Comment by dbsanfte** [comment]
This happened to us. It is a very generic connection error and it seems many different things can cause it.

In our case, we were running out of DHCP IP addresses and the node VMs were falling back to ipv6 link-local addresses, and Rancher obviously couldn't connect to them. Some VMs would get IP addresses and spin up, and others would not.

**Comment by cmccallu** [comment]
Thanks for the pointer! 

Cheers
Chris
