### ISSUE TITLE
Broken action links in Rancher 2.0 documentation (Cluster Administration page)

### ISSUE THREAD

**Issue by ablekh** [rancher/rancher#27811]
This is a Rancher 2.0 documentation issue. **Details links** in _Action_ column of the table located in the section _"Managing Clusters in Rancher"_ on the documentation page _"Cluster Administration"_ (https://rancher.com/docs/rancher/v2.x/en/cluster-admin/#managing-clusters-in-rancher) are broken. Apparently, the `{{<baseURL>}}` tag is not converted into a relevant value, for some reason.

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/docs/issues/2577
