### ISSUE TITLE
Imported Cluster unavailable after importing it again by mistake

### ISSUE THREAD

**Issue by rjbaat** [rancher/rancher#27822]
I am running a DO k8s cluster and imported it in Rancher interface. This is running good.
Now i was trying to import another cluster and created it in the Rancher interface. But after applying the yaml that triggers the import i noticed i was logged in on the wrong context and it was breaking the connection between the cluster and Rancher.

I am wondering how i might reissue the import command from the original Rancher connection, or how i can restore the connection otherwise. 

Or if i can remove the newly linked and old linked clusters and will it not affect the cluster itself and all its deployments? Will it touch that or is it simply removing the connection?

I don't want to end up deleting the old Unavailable connection and loosing the whole cluster with all its production data.

Hope to get some answers and help to get this restored and working properly again.

**Comment by leonardteo** [comment]
If the cluster is imported and you have the kubeconfig from DO, it should not be a problem to remove it from Rancher and reimport it. I’ve done that on several prod clusters already. Your cluster should continue to run as it only impacts the cattle-system namespace. Just ensure that you still have access to the kubeconfig from DO and that you can communicate with the cluster directly bypassing Rancher.

Generally imported clusters work best with Rancher as its loosely coupled. My Rancher K3S HA cluster managing 5 clusters somehow managed to completely barf itself. I was able to delete the cattle-system namespace from the prod clusters, and import them into a new Rancher installation just fine. I’ve also deleted clusters from within Rancher UI and reimported the clusters into another Rancher installation.

**Comment by rjbaat** [comment]
Yes i think it should be fined indeed. Since i think the cluster connection is already broken and i cant use the rancher kubeconfig. Also i do have the kubeconfig of DO. So with that i can do a reimport. 

I just want to make sure i won't drop a complete production cluster when removing it from rancher. 

The message it currently gives is: 

```
Failed to ensure monitoring project name: failed to find "cattle-prometheus" Namespace: Get https://10.245.0.1:443/api/v1/namespaces/cattle-prometheus?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers); cluster health check failed: Failed to communicate with API server: Get https://10.245.0.1:443/api/v1/namespaces/kube-system?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by jp-gouin** [comment]
Hi @leonardteo , when you have re imported your cluster.
Did you have any apps deployed with the rancher catalog ? 
And if so does those apps where correctly displayed in rancher ui after the reimport ?

Thanks,
