### ISSUE TITLE
Not able to remove namespace

### ISSUE THREAD

**Issue by sunwh0834** [rancher/rancher#27820]
Hi, 

I'm not able to delete namespace, it always shows status as 'removing', how to fix it?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.4` UI: `v2.4.22` |
|Route|`undefined`|

**Comment by leonardteo** [comment]
Try this:
`kubectl edit namespace cattle-system`

Under finalizers, if there are any, remove them.
