### ISSUE TITLE
External Authentication Configuration

### ISSUE THREAD

**Issue by kewumima** [rancher/rancher#27823]
How to config External Authentication for rancher 2.4.5?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.5` UI: `v2.4.28` |
|Route|`undefined`|

**Comment by superseb** [comment]
All authentication options are described on https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/. Please file an issue with steps followed and the error message when you encounter issues.

**Comment by kewumima** [comment]
> All authentication options are described on https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/. Please file an issue with steps followed and the error message when you encounter issues.
Thank you for your time.
What should I do if I want to use certifications developed by other third parties, such as those developed by myself?
