### ISSUE TITLE
Recursive subquestions

### ISSUE THREAD

**Issue by theAkito** [rancher/rancher#27837]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

As explained [here](https://forums.rancher.com/t/advanced-questions-yaml-features/17865), it would be very helpful, if there was a possbility to use recursive subquestions in a `questions.yaml`. Other improvements regarding the scalability of this configuration file would also be welcome.

**Comment by vincent99** [comment]
The groups are still ultimately flat and and it's not really "recursive" (self-referencing) but the Explorer apps do support nested subquestions.
