### ISSUE TITLE
Detailed service view for service alias and external service points to "Error" page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2783]
Reskin - Master build (11/23)

Steps to Reproduce:
1. Create external service or service alias
2. Click on external service or service names to go to the detailed view.

Result: Error page

Expected Result: Being able to view the detailed service page.

**Comment by westlywright** [comment]
This should be resolved by the changes being pushed in https://github.com/rancher/ui/pull/362

**Comment by deniseschannon** [comment]
Verified with master build from 11/23 evening
