### ISSUE TITLE
EKS Node Driver Enhancement in Kontainer Engine - PR Review

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#27848]
https://github.com/ribeiro-rodrigo/kontainer-engine/tree/eks-update-desirednodes

With the following rationale:

Clients on AWS as soon as they got their stuff up asked if they had to go to AWS console to resize and to upgrade their cluster to k8s 1.16.

The increase in the number of nodes in the EKS cluster is extremely important for us to be able to scale a cluster that was initially undersized in its provisioning. Currently, Rancher doesn’t provide, through its interface, the ability to edit the number of nodes in EKS, which can cause problems if the customer is not in the habit of monitoring the metrics of their nodes and to then interact with AWS Autoscaler interface, or not have any scale configured at all.

This potential PR looks to supplement that functionality and if it doesn't interfere with any ongoing dev work on future releases, it is ready to be submitted.

gz#11079

**Comment by ribeiro-rodrigo-exemplos** [comment]
Related to http://github.com/rancher/rancher/issues/27847

**Comment by deniseschannon** [comment]
As EKS v2 in v2.5 has updated node pool support, we advise all users to upgrade to v2.5 which ahs native support to scale up an EKS cluster
