### ISSUE TITLE
Update the warning msg on the feature flag page

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27849]
Update the warning msg on the feature flag page to indicate that the restart of Rancher server will cause short period of Rancher outage.

**Comment by maggieliu** [comment]
short term solution for: https://github.com/rancher/rancher/issues/26787

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 6f222168f, https://releases.rancher.com/ui/latest2/index.html
rancher/rancher:v2.4-head b7ab53e95, https://releases.rancher.com/ui/latest-2.4/index.html

Global settings feature flags page has the updated warning: 
`Feature flags allow Rancher to gate certain features behind flags. You should enable these features with caution, and they should be considered beta functionality, which could cause problems for your system. Additionally, some features (non-dynamic) require a restart of the Rancher server to be enabled. Changing non-dynamic features will restart Rancher pods, which will result in a short outage.`
