### ISSUE TITLE
UI - Rancher does not allow you to edit the number of nodes in an already created EKS cluster.

### ISSUE THREAD

**Issue by ribeiro-rodrigo** [rancher/rancher#27847]
It would be good if the EKS driver edit screen allows you to change the number of nodes in an existing EKS cluster. Thus, the user would not need to make this change through the AWS console.

Pull requests
- https://github.com/rancher/kontainer-engine/pull/231 
- https://github.com/rancher/ui/pull/4072

**Comment by deniseschannon** [comment]
As we are moving to the new EKS v2 support in Rancher v2.5, we encourage all users to upgrade and use the new provisioner which allows being able to change the number of nodes in EKS.

Thank you for your PR! @ribeiro-rodrigo
