### ISSUE TITLE
Initial DHCP requests of Rancher provisioned vSphere VMs contain incorrect hostname

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#27846]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a vSphere node template using a network with DHCP enabled
2. Provision a vSphere cluster using the node template
3. Monitor DHCP requests / leases on the DHCP server

**Result:**
Initial DHCP request of the DHCP client running on the node guest OS uses as a default hostname (depending on the OS, e.g. "localhost" or "ubuntu"). The correct hostname (derived from the node name assigned by Rancher) isn't configured by cloud-init but by docker-machine in a later stage. Consecutive DHCP requests use that hostname.

**Other details that may be helpful:**
The fact that all provisioned VMs use the same default hostname in the initial DHCP request causes problems in some infrastructure, such as DHCP lease database including incorrect/duplicate hostname entries, wrong FQDNs being propagated to the internal DNS servers, etc...

**Expected:**
The hostname should have been set by cloud-init before the initial network was setup and the first DHCP requests sent.  Cloud-init should use the `local-hostname` config in the `meta-data` file generated by the vSphere node driver.
https://cloudinit.readthedocs.io/en/latest/topics/modules.html#set-hostname

**Environment information**
Rancher version : v2.4.5

**Comment by Persi** [comment]
This Bug is a blocker in our environment currently :(

In addition, this causes another really weird behaviour in our company environment as well. Our DHCP uses short lease times (2h) currently to release it's managed IPs fast and allows for many new cluster node respawns in short time. The point is, after this 2h our nodes ask for a new DHCP lease and are issued a completely different IP, as the hostname of the node changed after the initial DHCP request. This new IP is unknown to Rancher and causes the affected cluster node to be handled as offline in Rancher. If this node is a master or etcd node this causes the complete cluster to be dead.

**Comment by janeczku** [comment]
@Persi Thanks you for the feedback. Even with a short lease time, the DHCP client should successfully renew the lease every half cycle. I would like to understand what causes this renewal to fail. I wouldn't expect this to be caused by the change of hostname since DHCP servers usually bind allocated IP's to the MAC address...

**Comment by Persi** [comment]
@janeczku that's what i would have expected as well... but unfortunately some dhcp servers (probably because of a misconfiguration?) seems to handle different VMs, with different MACs but some hostnames, as same system. It's pretty strange and I'll try to investigate further next week!

Have a nice weekend!

**Comment by Persi** [comment]
@janeczku i could reproduce above problem yesterday and found a workaround for our internal testing purposes. After defining a static unique hostname per node template via cloud-init, all created VMs received different IPs as expected. This obviously just works as long as you only spawn one VM per node template in a cluster. It seems that our corporate DHCP server really cares more about hostnames than MACs ... which is pretty annoying ...

I hope that with release 2.4.6 of Rancher this problem should be gone.

**Comment by janeczku** [comment]
Hi @Persi, it makes sense to me that you are able to work around the issue in the described way. As you have seen we have a fix in that we hope to ship in v2.4.6.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4-head

* Reproduced in v2.3.5
* Create a single node cluster, power down the node, and download `user-data.iso` 
* `META_DATA` file has the hostname commented: `#local-hostname: bdepesa-pretest1`

* Install v2.4-head
* Follow steps to reproduce
* `META_DATA` file has the hostname un-commented: `local-hostname: bdepesa-post1`

@ janeczku can you confirm your use case is resolved?

**Comment by bmdepesa** [comment]
rancher/rancher:master-head b91cabfbb

* Install master-head
* Follow steps to reproduce
* `META_DATA` file has the hostname un-commented: `local-hostname: bdepesa-clone3`

Will close once we have confirmation this resolves @janeczku's issue

**Comment by janeczku** [comment]
rancher/rancher:v2.4-head `ec33a5067fc5`
LGTM 👍  @bmdepesa 

**Steps:**
- Start packet capture of DHCP requests on the VM network
- Follow steps to reproduce

**Result:**
Initial DHCP requests contain the correct hostname (node name derived from node pool)

```
15:44:45.583278 IP (tos 0x10, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 328)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 00:50:56:aa:48:49, length 300, xid 0x1588033d, Flags [none] (0x0000)
	  Client-Ethernet-Address 00:50:56:aa:48:49
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Discover
	    Hostname Option 12, length 15: "jb-repro-master"
[TRUNCATED]
```
