### ISSUE TITLE
Unable to create node pool with azure images from marketplace

### ISSUE THREAD

**Issue by gladavius** [rancher/rancher#27854]
**What kind of request is this (question/bug/enhancement/feature request):** Feature request

**Steps to reproduce (least amount of steps as possible):**

- Create a node template with an image that come from azure marketplace (for example center-for-internet-security-inc:cis-centos-8-l1:cis-centos8-l1:1.0.4)

- Create a node pool based on the node template previously created

**Result:**

Creation of the node fail with the following error : 
```
Error creating machine: Error in driver during machine creation: Code="VMMarketplaceInvalidInput" Message="Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request. VM: 'xxxxxxxxxxxxxxxxxxxxxxx'."
--
```

**Other details that may be helpful:**

We tried to accept the terms agreement with a terraform resource like below : 
```
resource "azurerm_marketplace_agreement" "this" {
  publisher = "center-for-internet-security-inc"
  offer     = "cis-centos-8-l1"
  plan      = "cis-centos8-l1"
}
```
But it still doesn't work.

Node template should have the ability to pass plan informations.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 

Rancher | v2.4.3
-- | --
User Interface | v2.4.22
Helm | v2.16.5-rancher1
Machine | v0.15.0-rancher36

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Deployed with rke on azure

gz#11251
gz#11816

**Comment by cloudnautique** [comment]
After some digging, it looks like the CIS image is a "paid" image at $.02 /hr. In order to launch images from the marketplace that have a cost, additional fields for the plan need to be passed to the API. 

In order to use an image like the CIS hardened CentOS, you would need to pass additional information to the API.

Plans have the format below from the Template that gets generated in the UI:
```
"plan": {
                "name": "cis-centos8-l1",
                "publisher": "center-for-internet-security-inc",
                "product": "cis-centos-8-l1"
            }
```

In keeping with the image format, the plan flag could be something like: `--plan <name>:<publisher>:<product>`

**Comment by GProulx** [comment]
Hello @cloudnautique and @rawmind0 !

Do you think the pull request rancher/machine#122 could be integrated soon? This would help us removing some custom code we had to write to be able to use Marketplace Images. Is something more you could do on our side to help you be able to merge it?

Thanks,

**Comment by GProulx** [comment]
Hello again @cloudnautique and @rawmind0 

Did you get some news about when rancher/machine#122 could be merged? Are you waiting something from @mouellet (we are on the same team) to merge it?

**Comment by snasovich** [comment]
@GProulx , apologies for a delay in response and getting this over the finish line. The referenced PR is now merged and we're working on getting the remaining changes to get them in the next release.
This work is now tracked as part of https://github.com/rancher/rancher/issues/33518, so closing this one in favor of the referenced issue.
