### ISSUE TITLE
When convoy-gluster instance is stopped/deleted , existing containers do not have access to shared volumes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2785]
Server version - v0.47.0-rc1

Deployed  "Gluster FS" and "Convoy Gluster”  stacks  with 2 hosts in my setup as part of  convoy storage pool.

Tried to stop one of the existing  convoy-gluster instance. Instance keeps restarting:
Following exception is seen in logs:

```
11/23/2015 2:47:22 PMReading package lists...
11/23/2015 2:47:22 PMReading package lists...
11/23/2015 2:47:23 PMBuilding dependency tree...
11/23/2015 2:47:23 PMReading state information...
11/23/2015 2:47:23 PMvim is already the newest version.
11/23/2015 2:47:23 PMopenssh-server is already the newest version.
11/23/2015 2:47:23 PMsoftware-properties-common is already the newest version.
11/23/2015 2:47:23 PMwget is already the newest version.
11/23/2015 2:47:23 PMglusterfs-client is already the newest version.
11/23/2015 2:47:23 PM0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
11/23/2015 2:47:23 PMRegistering convoy socket at /var/lib/rancher/convoy/myconvoy1-f6970dd8-65fe-4234-8a2c-653d0f054a11.sock
11/23/2015 2:47:23 PMmkdir: can't create directory '/var/lib/rancher/convoy/myconvoy1-f6970dd8-65fe-4234-8a2c-653d0f054a11': File exists
```

The same issue is also seen when deleting one of the instances.The instance that gets started as part of service reconcile is keeps restarting. I see the same exception from above in seen in the container logs.

**Comment by sangeethah** [comment]
Tested with latest version of "Convoy Gluster" catalog.

When convoy-gluster instance is stopped/deleted , the instance are able to come back successfully.
But existing containers will not be able to access shared volumes any more. Container needs to be restarted , for getting back access to shared volumes.
New containers deployed will have access to shared volumes.

**Comment by sangeethah** [comment]
Similar behavior is also noted when convoy-gluster stack is deleted and recreated:

Deployed a glusterfs stack.
Started a convoy-gluster stack.
Deployed few services using convoy-gluster shared volumes.
Deleted convoy-gluster stack.
Created convoy-gluster stack again.
Able to start convoy-gluster stack successfully.
Able to create new containers using new shared volumes.

Issues seen:

Existing containers do not have access to existing shared volumes any more. 
When I restart the containers , they fails to start and remain in stopped state , since volume cannot be found.

Also Not able to deploy new containers using the existing shared volumes.


Following exception seen in the logs:

 "2015-12-09 23:23:58,134 ERROR [:] [] [] [] [ecutorService-1] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [instance.start:24365] on [1009] io.cattle.platform.eventing.exception.EventExecutionException: edd12c0d-99a3-43fd-8547-5bf9be02fc18 : 500 Server Error: Internal Server Error ("Cannot start container 52d23019cdcf4e566331e37c857d3f225193799bd6d77576e21891505e27ab65: Cannot find volume testcon1")"

**Comment by cjellick** [comment]
I think the same issue is reported in https://github.com/rancher/convoy/issues/74

**Comment by cjellick** [comment]
Moving out of the 1.1 milestone as we are not focusing on gluster in it. Does not apply to convoy-nfs.
