### ISSUE TITLE
Feature request: Ingress-Nginx - Ability to disable port 80 or port 443

### ISSUE THREAD

**Issue by chrisreed87** [rancher/rancher#27850]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

Certain customers have requirements to either completely disable https or http, hence blocking port 80 or 443, at the global level (not from individual annotations). This option is available in upstream nginx-ingress helm chart:

```
controller.service.enableHttp or controller.service.enableHttps
```

Feature request is to add an option like this into Rancher's deployment of ingress-nginx, via RKE cluster yaml or other mechanism.

gz#11087

**Comment by chrisfosterelli** [comment]
Not sure if this helps, but you can turn off the load balancer entirely or (I think) use the extra options to turn off the host binding: https://rancher.com/docs/rke/latest/en/config-options/add-ons/ingress-controllers/#disabling-the-default-ingress-controller

**Comment by leodotcloud** [comment]
If one needs to block ports 80 and 443, there is no point in running nginx ingress controller. Could be disabled as pointed out in the previous comment.
