### ISSUE TITLE
web gui for mobile device (phone and tablet)

### ISSUE THREAD

**Issue by Maximal2017** [rancher/rancher#27863]
There is no way to use the web interface on mobile devices, all the menus overlap and there is no way to choose anything from the drop-down list. The problem is reproduced both on phones and tablets in various operating systems ios, ipados, android. I'm record video problem:
https://www.dropbox.com/sh/v5eut1tyroxlrls/AAByY_6L1SPVcUGzG4s0yQ4ka?dl=0

**Comment by kuetemeier** [comment]
It would be great to have rancher working on mobile safari. I often take an iPad for quick fixes with me.

**Comment by tbrtje** [comment]
I second this. Even on an iPad Pro where the menus do not overlap there are problems.
The menus are seethrough and menu options are unclickable. The rest of the ui works though.
