### ISSUE TITLE
Rancher server on AKS

### ISSUE THREAD

**Issue by travis-sobeck** [rancher/rancher#27878]
Question:
I installed the rancher server on AKS with helm because it was easy and seemed like a good idea (lazy admin!)
However, now its time to sort out DR plans, backup/recovery of the rancher server.  Looks like everything is stored in etcd, which in AKS lives in ["azure land"](https://docs.microsoft.com/en-us/azure/aks/concepts-clusters-workloads#kubernetes-cluster-architecture) (I think EKS is the same).  Not finding any info on backup/restore of etcd in Azure/AKS, wondering if you/anyone has thoughts on this or running Rancher server in AKS/EKS.
Thanks.

**Comment by travis-sobeck** [comment]
FWIW I asked Azure about backup/restore of etcd in AKS and got this response.
"As etcd is part of the managed Control Plane, as of today, there's no possible procedure for the user to back up the etcd database"
"As etcd is part of the Managed Control Plane, by default etcd has been deployed in high availability with an automatic backup process and our Product Group will be able to recover in case of failure. Also, Uptime SLA can be an option that could be enabled on active and new clusters"

**Comment by superseb** [comment]
This note is present in the current HA install docs: https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/#important-notes-on-architecture

And the issue to track for support is https://github.com/rancher/rancher/issues/16627

**Comment by travis-sobeck** [comment]
Ah, I didn't see that Issue.
