### ISSUE TITLE
service.upgrade doesn't update service.publicEndpoints correctly

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2787]
Steps to reproduce:

1) create service with port 43 exposed.
2) Upgrade service to have new port, say 44.

Bug: service.publicEndpoints has both 43,44 instead of having just 44.

@ibuildthecloud @sangeethah

**Comment by sangeethah** [comment]
Tested with rancher-server version - v0.47.0-rc2

When service is upgraded and port is updated , service.publicEndpoint has only the updated port.
