### ISSUE TITLE
Option to enable Default Project Monitoring at Cluster Creation

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#27889]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Description:**
End customer does not use Rancher to interact with their RLK clusters, rather the end customer uses kubectl and standard tooling.

As such the customer has no interest in using rancher concepts like Projects so stick to the default project, however, they would like to monitor workloads.

If they were to create a project separately they could enable monitoring then but as they do not use projects to manage namespaces this isn't ideal as they rely on terraform and automation to create clusters automatically and with little user input.

As it is possible to enable system monitoring at cluster creation can it also be made possible to enable default-project monitoring at cluster creation as well to make this process better? This would also help other customers with similar automation needs.

gz#11105

**Comment by leodotcloud** [comment]
With the new monitoring v2 changes, this RFE is not quite relevant. Hence, closing.
