### ISSUE TITLE
Kubectl can not be opened from Rancher Kubectl Command 

### ISSUE THREAD

**Issue by sunwh0834** [rancher/rancher#27890]
Hi, 

I'm not able to launch Kubectl command from Rancher Screen (Cluster), 

it shows '1006' error code.  How to troubleshoot this error?

Best Regards, 

James 

|Versions|Rancher `v2.4.5` UI: `v2.4.28` |
|

**Comment by superseb** [comment]
Please describe the setup in more detail, especially the path between client and Rancher (load balancer(s)/VPN etc). Also, please check the status and logs of the Rancher agents pods in the System project.
