### ISSUE TITLE
Failed to obtain metrics

### ISSUE THREAD

**Issue by sunwh0834** [rancher/rancher#27892]
After enabled monitoring, all the services looks running well. However I'm not able to see Cluster Metrics and other metrics, 
"Failed to obtain metrics. The metrics service may not be available. undefined"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.5` UI: `v2.4.28` |
|Route|`undefined`|

**Comment by mathieubodin** [comment]
Maybe related to #27902 ?

**Comment by sunwh0834** [comment]
Hi , 

Below is the pod description:
Name:         metrics-server-697746ff48-f2fs4
Namespace:    kube-system
Priority:     0
Node:         far7pdcapp2/172.16.20.219
Start Time:   Fri, 10 Jul 2020 15:09:28 +0800
Labels:       k8s-app=metrics-server
              pod-template-hash=697746ff48
Annotations:  cni.projectcalico.org/podIP: 10.42.1.7/32
              cni.projectcalico.org/podIPs: 10.42.1.7/32
Status:       Running
IP:           10.42.1.7
IPs:
  IP:           10.42.1.7
Controlled By:  ReplicaSet/metrics-server-697746ff48
Containers:
  metrics-server:
    Container ID:  docker://a54e73f85a7a1b709d674318de8bde8279c971b812c39fade58ac451d39456ca
    Image:         rancher/metrics-server:v0.3.6
    Image ID:      docker-pullable://rancher/metrics-server@sha256:b85628b103169d7db52a32a48b46d8942accb7bde3709c0a4888a23d035f9f1e
    Port:          <none>
    Host Port:     <none>
    Command:
      /metrics-server
      --kubelet-insecure-tls
      --kubelet-preferred-address-types=InternalIP
      --logtostderr
    State:          Running
      Started:      Fri, 10 Jul 2020 15:25:35 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 10 Jul 2020 15:14:04 +0800
      Finished:     Fri, 10 Jul 2020 15:24:53 +0800
    Ready:          True
    Restart Count:  1
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from metrics-server-token-7k25m (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  metrics-server-token-7k25m:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metrics-server-token-7k25m
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     :NoExecute
                 :NoSchedule
Events:          <none>

**Comment by sunwh0834** [comment]
after checking/enabling the port on master node and work nodes, now able to see the metrics data collected.
