### ISSUE TITLE
status "Started-Once" is truncated.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2789]
Server version - v0.47.0-rc1
UI - latest UI

For containers that are started with io.rancher.container.start_once=start , the UI shows status as "Started-Once" which gets truncated

<img width="1327" alt="screen shot 2015-11-23 at 4 40 04 pm" src="https://cloud.githubusercontent.com/assets/4266958/11354526/eeaaeb10-9200-11e5-974c-1f1063adf1be.png">

**Comment by westlywright** [comment]
https://github.com/rancher/ui/pull/367 addresses this

**Comment by deniseschannon** [comment]
Verified with latest UI (evening 11/24)

<img width="316" alt="screen shot 2015-11-24 at 9 33 46 pm" src="https://cloud.githubusercontent.com/assets/11410997/11389229/11c96142-92f3-11e5-878d-cd80fa290cd2.png">
