### ISSUE TITLE
Timed out towards host='pypi.python.org', port=443 for installing netmiko / Ubuntu 18.04

### ISSUE THREAD

**Issue by toxkalcan** [rancher/rancher#27906]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
root@NetworkAutomation-1:~# pip3 install netmiko

**Result:**
Collecting netmiko
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)")': /simple/netmiko/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)")': /simple/netmiko/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)")': /simple/netmiko/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)")': /simple/netmiko/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)")': /simple/netmiko/
  Could not find a version that satisfies the requirement netmiko (from versions: )
No matching distribution found for netmiko

**Other details that may be helpful:**
I am trying to install netmiko to network-automation container in GNS3, however, I am getting timed-out errors.

root@NetworkAutomation-1:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

Upon checking, packet capture I can see destination resolves to ip, there are some TCP packet SEQ-ACK going on but never completes for some reason

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by toxkalcan** [comment]
I found out that https://pypi.python.org redirects to https://pypi.org
How can I update network automation container to download netmiko from pypi.org ? 

VAU-MB-11252:~ onur.alkara$ curl https://pypi.python.org
<html><head><title>301 Moved Permanently</title></head><body><center><h1>301 Moved Permanently</h1></center></body>

**Comment by superseb** [comment]
This seems to be similar connection error as described in https://github.com/rancher/rancher/issues/27905, merging
