### ISSUE TITLE
can't run apt-get update inside Ubuntu 18.04

### ISSUE THREAD

**Issue by toxkalcan** [rancher/rancher#27905]
root@NetworkAutomation-1:~# cat  /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
root@NetworkAutomation-1:~# apt-get update

**Result:**
Err:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Connection failed [IP: 91.189.91.39 80]
Err:2 http://ppa.launchpad.net/ansible/ansible/ubuntu bionic InRelease
  Connection failed [IP: 91.189.95.83 80]
Err:3 http://archive.ubuntu.com/ubuntu bionic InRelease
  Connection failed [IP: 91.189.88.152 80]
Err:4 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
  Connection failed [IP: 91.189.95.83 80]
Err:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Connection failed [IP: 91.189.88.152 80]

**Other details that may be helpful:** All the urls referred moved permanently ( 301 )

root@NetworkAutomation-1:~#  curl http://ppa.launchpad.net/deadsnakes/ppa/ubuntu
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://ppa.launchpad.net/deadsnakes/ppa/ubuntu/">here</a>.</p>
</body></html>

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by toxkalcan** [comment]
when I try to update it with curl command it gives me error below 

root@NetworkAutomation-1:~# apt-get download http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/bionic/main/debian-installer/binary-amd64/by-hash/
E: Unable to locate package http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/bionic/main/debian-installer/binary-amd64/by-hash
E: Couldn't find any package by glob 'http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/bionic/main/debian-installer/binary-amd64/by-hash'
E: Couldn't find any package by regex 'http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/bionic/main/debian-installer/binary-amd64/by-hash'

**Comment by superseb** [comment]
Please describe what you are trying to and the steps you are following. Both a clean `ubuntu:18.04` or the `rancher/rancher` container does not include the repositories that are listed. If this is running inside a Kubernetes cluster, try to verify `apt-get update` works when using Docker only, and if that succeeds, use https://rancher.com/docs/rancher/v2.x/en/troubleshooting/ to determine what's wrong in the cluster.
