### ISSUE TITLE
Rancher is trying to use 127.0.0.1 to login and not my domain

### ISSUE THREAD

**Issue by unlimitedcoder2** [rancher/rancher#27903]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
I ran this command sudo docker run -d --restart=unless-stopped -p 127.0.0.1:81:80 -p 127.0.0.1:4443:443 rancher/rancher

**Result:**

![image](https://user-images.githubusercontent.com/16884313/87222228-1422dc00-c36a-11ea-8756-466f3f213c81.png)

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by curx** [comment]
can you please check if the `server-url`settings in your rancher deployment match your domain settings:
`RancherUI > Global > Settings > (Advanced Settings, is default) > server-url`

or via cmds:
`docker exec <rancher-cnt> kubectl -n cattle-system get settings server-url -o jsonpath='{ .value }'`

**Comment by unlimitedcoder2** [comment]
![image](https://sharethe.minecraftdoublesmoothstoneslab.website/i/9zz4.png)
