### ISSUE TITLE
route53

### ISSUE THREAD

**Issue by Jdesk** [rancher/rancher#2790]
I'm loving rancher more than life - intuitive as heck.  However route 53 dns is constantly showing degraded - restarting - and overall just not working - I'm a bit confused when it comes to this - I already use route53 - also dns and myself do not get along and quite frankly it sucks - so this was one thing that led me to choose rancher as a container management registry as dns entries would be created and private ips would be fully taken advantage of - however I cannot get the route53 dns stack running although it claims that it is running in a "degraded state" - I have lost all network monitoring tools including cpu monitoring - yet the external hosts remain functional - I need to get into a container to make a change but I cannot from the ui - which I loved - also is there any way to setup permanent ssh keys?  I have to constantly reset root passwords and then upload my ssh keys to authenticate.  I setup all public facing route53 dns manually - i was really hoping that there was a way to get entries to be created in the format mentioned during the creation of a dns stack.

**Comment by Jdesk** [comment]
Just to add - as soon as I reset my root password - the entire host get's shut down - so when i cannot access a shell via the ui - and need to get into my host - which I still don't get how it how the ssh keys and pw have been changed again - I already went in and set them once and went through this - then they were changed on me - it's important that I always have access and any user has access - if there is some way to setup the keys for each host that would be amazing - rather than rancher set them up - we set them up and rancher uses them.

**Comment by vincent99** [comment]
I don't know what's going on, but Rancher does not get involved in, change, or know the root password, ssh key, nor ever shutdown/restart a host.  If your hosts are running RancherOS then we are somewha involved, but not in a way that makes sense with what you described.  What hosts are you running the Rancher agent on and how were they created?

 If you are using the "Add Host" screen that calls `docker-machine` to deploy hosts on a provider and generates a SSH key, which is available from the "Download Machine Config" action on the host once it is setup.

The Route53 integration issues seem like a symptom of other issues/the least of your problems right now.  It runs as a container and needs to have a working environment in the first place.

**Comment by Jdesk** [comment]
i gotcha - regarding ssh keys - i was just hoping that i could use my keys across the board - route53 - I have working environments actually :-)  - so I'm not sure as to why entries cannot be created - I run everything (almost) as a service - in a stack - made of of the linked containers that are required for applications.  Perhaps I am doing something wrong?

**Comment by Jdesk** [comment]
Maybe I'm not being clear enough - The route53 service is integral in the development of rancher - as a beta tester I'm simply pointing out a few issues I notice as I test the platform in productin/development.   I have read the documentation inside and out looking for possible errors on my part regarding several things. 

1.  The addition and/or creation of route53 dns stacks as the initial service or service addition to existing stacks with port mappings, service mappings etc., does not seem to be able to create entries within the hosted zone for the zone specified nor use anything other than private ips which is fine in many cases - however upon the creation of eg. a nodejs app that needs to be publicly available upon creation of the rancher-compose / docker-compose files or if created within the ui - is unable to create dns entries in the format specified within the api.   - this is both for instances created or running on ec2 or another provider - I use route53 dns for everything so any domain I add to the application/stack/service.

- 2nd I have noticed that upon the entry of a wildcard ssl cert - using the ui - will completely block the creation of new hosts, load-balancers - and back to our favorite subject - external dns of any sort (route53) - I have installed many ssl certs in my day so prior to placing them in the UI, naturally I concencate, then place my private key in.  I have tried using the domain cert, key file, and chain separately as well just for troubleshooting.  Now if I create an nginx container - exec into the container - put the cert in the config - and use this as an lb or proxy then boom we are good.   However it appears that rancher is not able to recognize a cert installed in this fashion - I have looked through the documents regarding ssl termination however I found it a bit unclear - I find myself regularly destroying rancher servers - then manually creating my apps from the cli using docker-compose, and then adding the server and running the discover command on each host in order to monitor apps - which I believe is what you are trying to eliminate.  

I only mention things to let you know specific issues that I notice so you guys can be aware of them and version/update accordingly.  It's not to embarrass, just being helpful because I believe in what you guys are doing - there are 100 addons to docker that can do quite a bit of amazing container manipulation/scheduling/volume creation etc. - but I have found that rancher has taken the best of all of them, added even more, and overall is the number one ui for containers and complex containerized infrastructure management.

**Comment by alena1108** [comment]
@Jdesk 

>However route 53 dns is constantly showing degraded - restarting

Could you provider route53 container logs? You can get them either from Rancher UI or from docker side by running "docker logs [container_uuid]" command.

**Comment by Jdesk** [comment]
sure can - actually at this point - rancher is creating entries however at the same time deleting entries in the zone - which has completely confused me as there are so many entries (or were) - and I can't possibly remember what was where and what app was delegated to what ip.  Also purging containers is failing and rancher repeatedly restarts them - one being redis - a zone entry has been created for redis however my concern is the repeated restart of the redis db - in relation to queries made to route 53 - not sure if this is how rancher is operating but as we all know amazon charges for what you use and although route53 is not very expensive - when queries are being made repeatedly (I have to setup a cloudfront log to check) -  - but I did look at the zone and there was an entry created for the redis container and kubernetes api proxy as well as controller.  the redis container keeps restarting (didn't have an issue in the previous version of rancher - however the latest release seems to have an issue with this container - it's my image (cloned from the official images and pused to our docker hub and quay account.   - however it keeps restarting - I'm going to get the logs right over.  give me a few minutes.

**Comment by Jdesk** [comment]
i'm grabbing all logs for rancher/server and route53 - grabbing from cli - it's my home and for some reason it just makes more sense :-).  Rancher server failed just now - It could be because I added the rancher agent to the rancher server as my curiosity got the best of me and I actually have containers on there that were there prior to the installation of rancher and I also started rancher with an nginx container - however all was fine until I added the agent the the server - also added agent to several other hosts where containers are running - is there a way for me to provide the keys to the rancher server for custom host registrations?  To give it full control and also allow me to grab machine config for easy restoration.   I'm gonna gist the logs - they are extremely long.  Or pastebin.  I'll get the link over shortly.

**Comment by Jdesk** [comment]
and fyi - i'm noticing steady improvement - she recovered herself ;-).  Redis is still an issue and route53 - I am going to remove the containers from the backend for redis but I'll grab logs for you first.  Also I'm really liking the additions eg. etcd - real discovery - I have made multiple attempts to install on coreos - not sure if compatibility is there yet - but an idea for the future and perhaps I can help out if you want - getting compatibility with coreos stabilized - I just find the coreos and I know it's kind of a competitor for you guys - but I think a strategic partnership would be beneficial to both of you being as both have been adopted by all the big players.

**Comment by Jdesk** [comment]
https://gist.github.com/Jdesk/e8657dc9cd7a8480e894
https://gist.github.com/Jdesk/e8657dc9cd7a8480e894
https://gist.github.com/Jdesk/2cad90c0c4b2dc76b19c

**Comment by deniseschannon** [comment]
Based on your logs, it looks like you were having network connectivity issues with your setup. The provider is Amazon Route 53 service, so for some reason you weren't able to connect with it. 
```
time="2015-12-01T05:20:17Z" level=error msg="Healtcheck failed: unable to reach Cattle" 
time="2015-12-01T05:20:21Z" level=error msg="Healtcheck failed: unable to reach a provider" 
```

**Comment by Jdesk** [comment]
I'm getting rate limited hard - and also system failed as a result - it was after the ratelimit was exceeded that the entire cluster shut down - and atm i'm currently screwed as I had to destroy the main server - what do you recommend in terms of size for a 10+ host network for the rancher server - the machines still exist - but the keys are not working - I can reset root pw - but that's going to take out the machine as well (at least it has in the past - but i need to reconnect them to the server) - i think my main server needs to be on aws as I can setup an auto scaling policy without shutting down the machine

**Comment by deniseschannon** [comment]
@Jdesk I'm not sure where you're at in your setup, but I believe your initial issue with route 53 was related to some networking connectivity. 

If you have other issues, please open a new one.
