### ISSUE TITLE
Unable to add node cluster from GCP to existing Cluster

### ISSUE THREAD

**Issue by ryzam** [rancher/rancher#27904]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
1. Setup one master/etcd and three workers in onprem (Ubuntu 18.0.4) VM using Rancher UI - Success

2. Setup new VM in GCP - (docker/kubernetes etc) - Success

3. `sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.4.5 --server https://xxx.xxx.xxx.xxx --token s92qrzc64jfhrr6t8d4zsmkmcqlfqnzzgwvkpbb8bm4wl6jk2kbfcb --ca-checksum c738ad58231ce95c94dd082e628f245d74d058881fed842212b6a25eafce27eb --worker`

3. Register as new node - Waiting to register with Kubernetes

![image](https://user-images.githubusercontent.com/597759/87234662-c956a200-c405-11ea-8b7e-211f1acd60d7.png)

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
 Hosted & Infrastructure Provider (GCP)
- Machine type (cloud/VM/metal) and specifications (CPU/memory):

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:34 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:11:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by superseb** [comment]
Please check/provide the logs from the created containers using the `rancher/rancher-agent` image on that node.

**Comment by ryzam** [comment]
**Logs rancher/rancher-agent:v2.4.5**

`INFO: Arguments: --server https://rancher.konti.xxx-xxxx.asia --token REDACTED --ca-checksum c738ad58231ce95c94dd082e628f245d74d058881fed842212b6a25eafce27eb --address x.x.x.x --internal-address 10.128.0.24 --worker
INFO: Environment: CATTLE_ADDRESS=35.202.226.145 CATTLE_INTERNAL_ADDRESS=10.128.0.24 CATTLE_NODE_NAME=ubuntu-k8s-1 CATTLE_ROLE=,worker CATTLE_SERVER=https://rancher.konti.xxx-xxxx.asia CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 169.254.169.254 search c.rich-sunlight-264003.internal google.internal
INFO: https://rancher.konti.xxx-xxxx.asia/ping is accessible
INFO: rancher.konti.xxx-xxxx.asia resolves to x.x.x.x
INFO: Value from https://rancher.konti.xxxx/v3/settings/cacerts is an x509 certificate
time="2020-07-13T14:56:45Z" level=info msg="Rancher agent version v2.4.5 is starting"
time="2020-07-13T14:56:45Z" level=info msg="Option etcd=false"
time="2020-07-13T14:56:45Z" level=info msg="Option controlPlane=false"
time="2020-07-13T14:56:45Z" level=info msg="Option worker=true"
time="2020-07-13T14:56:45Z" level=info msg="Option requestedHostname=ubuntu-k8s-1"
time="2020-07-13T14:56:45Z" level=info msg="Option customConfig=map[address:x.x.x.x internalAddress:10.128.0.24 label:map[] roles:[worker] taints:[]]"
time="2020-07-13T14:56:45Z" level=info msg="Listening on /tmp/log.sock"
time="2020-07-13T14:56:46Z" level=info msg="Connecting to wss://rancher.konti.xxx-xxxx.asia/v3/connect/register with token s92qrzc64jfhrr6t8d4zsmkmcqlfqnzzgwvkpbb8bm4wl6jk2kbfcb"
time="2020-07-13T14:56:46Z" level=info msg="Connecting to proxy" url="wss://rancher.konti.xxx-xxxx.asia/v3/connect/register"
time="2020-07-13T14:56:47Z" level=info msg="Starting plan monitor, checking every 15 seconds"
time="2020-07-13T14:57:06Z" level=info msg="Option worker=true"
time="2020-07-13T14:57:06Z" level=info msg="Option requestedHostname=ubuntu-k8s-1"
time="2020-07-13T14:57:06Z" level=info msg="Option customConfig=map[address:35.202.x.x internalAddress:10.128.0.24 label:map[] roles:[worker] taints:[]]"
time="2020-07-13T14:57:06Z" level=info msg="Option etcd=false"
time="2020-07-13T14:57:06Z" level=info msg="Option controlPlane=false"
time="2020-07-13T14:57:06Z" level=info msg="Option requestedHostname=ubuntu-k8s-1"
time="2020-07-13T14:57:06Z" level=info msg="Option customConfig=map[address:35.202.x.x internalAddress:10.128.0.24 label:map[] roles:[worker] taints:[]]"
time="2020-07-13T14:57:06Z" level=info msg="Option etcd=false"
time="2020-07-13T14:57:06Z" level=info msg="Option controlPlane=false"
time="2020-07-13T14:57:06Z" level=info msg="Option worker=true"
time="2020-07-13T14:57:07Z" level=info msg="Plan monitor checking 120 seconds"`

**Logs kube-proxy  rancher/hyperkube:v1.18.3-rancher2** 

`+ grep -q cloud-provider=azure
+ echo kube-proxy --cluster-cidr=10.42.0.0/16 --hostname-override=ubuntu-k8s-1 --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml --healthz-bind-address=127.0.0.1 --v=2
+ '[' kube-proxy = kubelet ']'
+ exec kube-proxy --cluster-cidr=10.42.0.0/16 --hostname-override=ubuntu-k8s-1 --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml --healthz-bind-address=127.0.0.1 --v=2
I0713 14:57:02.952679   20440 flags.go:33] FLAG: --add-dir-header="false"
I0713 14:57:02.952732   20440 flags.go:33] FLAG: --alsologtostderr="false"
I0713 14:57:02.952737   20440 flags.go:33] FLAG: --bind-address="0.0.0.0"
I0713 14:57:02.952743   20440 flags.go:33] FLAG: --cleanup="false"
I0713 14:57:02.952754   20440 flags.go:33] FLAG: --cleanup-ipvs="true"
I0713 14:57:02.952757   20440 flags.go:33] FLAG: --cluster-cidr="10.42.0.0/16"
I0713 14:57:02.952762   20440 flags.go:33] FLAG: --config=""
I0713 14:57:02.952766   20440 flags.go:33] FLAG: --config-sync-period="15m0s"
I0713 14:57:02.952771   20440 flags.go:33] FLAG: --conntrack-max-per-core="32768"
I0713 14:57:02.952777   20440 flags.go:33] FLAG: --conntrack-min="131072"
I0713 14:57:02.952784   20440 flags.go:33] FLAG: --conntrack-tcp-timeout-close-wait="1h0m0s"
I0713 14:57:02.952788   20440 flags.go:33] FLAG: --conntrack-tcp-timeout-established="24h0m0s"
I0713 14:57:02.952792   20440 flags.go:33] FLAG: --detect-local-mode=""
I0713 14:57:02.952797   20440 flags.go:33] FLAG: --feature-gates=""
I0713 14:57:02.952802   20440 flags.go:33] FLAG: --healthz-bind-address="127.0.0.1"
I0713 14:57:02.952807   20440 flags.go:33] FLAG: --healthz-port="10256"
I0713 14:57:02.952810   20440 flags.go:33] FLAG: --help="false"
I0713 14:57:02.952817   20440 flags.go:33] FLAG: --hostname-override="ubuntu-k8s-1"
I0713 14:57:02.952820   20440 flags.go:33] FLAG: --iptables-masquerade-bit="14"
I0713 14:57:02.952823   20440 flags.go:33] FLAG: --iptables-min-sync-period="0s"
I0713 14:57:02.952827   20440 flags.go:33] FLAG: --iptables-sync-period="30s"
I0713 14:57:02.952830   20440 flags.go:33] FLAG: --ipvs-exclude-cidrs="[]"
I0713 14:57:02.952843   20440 flags.go:33] FLAG: --ipvs-min-sync-period="0s"
I0713 14:57:02.952846   20440 flags.go:33] FLAG: --ipvs-scheduler=""
I0713 14:57:02.952852   20440 flags.go:33] FLAG: --ipvs-strict-arp="false"
I0713 14:57:02.952856   20440 flags.go:33] FLAG: --ipvs-sync-period="30s"
I0713 14:57:02.952859   20440 flags.go:33] FLAG: --ipvs-tcp-timeout="0s"
I0713 14:57:02.952862   20440 flags.go:33] FLAG: --ipvs-tcpfin-timeout="0s"
I0713 14:57:02.952866   20440 flags.go:33] FLAG: --ipvs-udp-timeout="0s"
I0713 14:57:02.952874   20440 flags.go:33] FLAG: --kube-api-burst="10"
I0713 14:57:02.952878   20440 flags.go:33] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0713 14:57:02.952882   20440 flags.go:33] FLAG: --kube-api-qps="5"
I0713 14:57:02.952890   20440 flags.go:33] FLAG: --kubeconfig="/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml"
I0713 14:57:02.952895   20440 flags.go:33] FLAG: --log-backtrace-at=":0"
I0713 14:57:02.952903   20440 flags.go:33] FLAG: --log-dir=""
I0713 14:57:02.952907   20440 flags.go:33] FLAG: --log-file=""
I0713 14:57:02.952911   20440 flags.go:33] FLAG: --log-file-max-size="1800"
I0713 14:57:02.952915   20440 flags.go:33] FLAG: --log-flush-frequency="5s"
I0713 14:57:02.952922   20440 flags.go:33] FLAG: --logtostderr="true"
I0713 14:57:02.952925   20440 flags.go:33] FLAG: --masquerade-all="false"
I0713 14:57:02.952929   20440 flags.go:33] FLAG: --master=""
I0713 14:57:02.952932   20440 flags.go:33] FLAG: --metrics-bind-address="127.0.0.1:10249"
I0713 14:57:02.952935   20440 flags.go:33] FLAG: --metrics-port="10249"
I0713 14:57:02.952939   20440 flags.go:33] FLAG: --nodeport-addresses="[]"
I0713 14:57:02.952947   20440 flags.go:33] FLAG: --oom-score-adj="-999"
I0713 14:57:02.952953   20440 flags.go:33] FLAG: --profiling="false"
I0713 14:57:02.952959   20440 flags.go:33] FLAG: --proxy-mode=""
I0713 14:57:02.952963   20440 flags.go:33] FLAG: --proxy-port-range=""
I0713 14:57:02.952968   20440 flags.go:33] FLAG: --show-hidden-metrics-for-version=""
I0713 14:57:02.952971   20440 flags.go:33] FLAG: --skip-headers="false"
I0713 14:57:02.952974   20440 flags.go:33] FLAG: --skip-log-headers="false"
I0713 14:57:02.952977   20440 flags.go:33] FLAG: --stderrthreshold="2"
I0713 14:57:02.952983   20440 flags.go:33] FLAG: --udp-timeout="250ms"
I0713 14:57:02.952987   20440 flags.go:33] FLAG: --v="2"
I0713 14:57:02.952990   20440 flags.go:33] FLAG: --version="false"
I0713 14:57:02.952997   20440 flags.go:33] FLAG: --vmodule=""
I0713 14:57:02.953001   20440 flags.go:33] FLAG: --write-config-to=""
W0713 14:57:02.953010   20440 server.go:225] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
I0713 14:57:02.953190   20440 feature_gate.go:243] feature gates: &{map[]}
I0713 14:57:02.953318   20440 feature_gate.go:243] feature gates: &{map[]}
W0713 14:57:02.994778   20440 server_others.go:559] Unknown proxy mode "", assuming iptables proxy
E0713 14:57:02.995273   20440 node.go:125] Failed to retrieve node info: Get https://127.0.0.1:6443/api/v1/nodes/ubuntu-k8s-1: dial tcp 127.0.0.1:6443: connect: connection refused
E0713 14:57:04.018162   20440 node.go:125] Failed to retrieve node info: Get https://127.0.0.1:6443/api/v1/nodes/ubuntu-k8s-1: dial tcp 127.0.0.1:6443: connect: connection refused
E0713 14:57:35.218302   20440 node.go:125] Failed to retrieve node info: an error on the server ("") has prevented the request from succeeding (get nodes ubuntu-k8s-1)
E0713 14:58:08.948990   20440 node.go:125] Failed to retrieve node info: an error on the server ("") has prevented the request from succeeding (get nodes ubuntu-k8s-1)
E0713 14:58:46.891014   20440 node.go:125] Failed to retrieve node info: an error on the server ("") has prevented the request from succeeding (get nodes ubuntu-k8s-1)
E0713 14:59:34.483451   20440 node.go:125] Failed to retrieve node info: an error on the server ("") has prevented the request from succeeding (get nodes ubuntu-k8s-1)
I0713 14:59:34.483636   20440 server_others.go:178] can't determine this node's IP, assuming 127.0.0.1; if this is incorrect, please set the --bind-address flag
I0713 14:59:34.483785   20440 server_others.go:183] DetectLocalMode: 'ClusterCIDR'
I0713 14:59:34.483869   20440 server_others.go:186] Using iptables Proxier.
I0713 14:59:34.484238   20440 server.go:583] Version: v1.18.3
I0713 14:59:34.484777   20440 conntrack.go:52] Setting nf_conntrack_max to 131072
I0713 14:59:34.486435   20440 config.go:315] Starting service config controller
I0713 14:59:34.486574   20440 shared_informer.go:223] Waiting for caches to sync for service config
I0713 14:59:34.486714   20440 config.go:133] Starting endpoints config controller
I0713 14:59:34.486816   20440 shared_informer.go:223] Waiting for caches to sync for endpoints config
I0713 14:59:34.487082   20440 reflector.go:175] Starting reflector *v1.Service (15m0s) from k8s.io/client-go/informers/factory.go:135
I0713 14:59:34.487671   20440 reflector.go:175] Starting reflector *v1.Endpoints (15m0s) from k8s.io/client-go/informers/factory.go:135
E0713 14:59:36.484105   20440 event.go:269] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: read tcp 127.0.0.1:47392->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
E0713 14:59:45.563237   20440 event.go:269] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: read tcp 127.0.0.1:47496->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
E0713 14:59:57.564882   20440 event.go:269] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: read tcp 127.0.0.1:47638->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
I0713 15:00:03.507607   20440 trace.go:116] Trace[1111594673]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2020-07-13 14:59:34.487203382 +0000 UTC m=+151.636565166) (total time: 29.020371812s):
Trace[1111594673]: [29.020371812s] [29.020371812s] END
E0713 15:00:03.507789   20440 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Service: an error on the server ("") has prevented the request from succeeding (get services)
I0713 15:00:03.508030   20440 trace.go:116] Trace[1528437661]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2020-07-13 14:59:34.487767107 +0000 UTC m=+151.637128891) (total time: 29.020248069s):
Trace[1528437661]: [29.020248069s] [29.020248069s] END
E0713 15:00:03.508113   20440 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Endpoints: an error on the server ("") has prevented the request from succeeding (get endpoints)
E0713 15:00:09.567572   20440 event.go:269] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: read tcp 127.0.0.1:47754->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
E0713 15:00:21.567499   20440 event.go:269] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: read tcp 127.0.0.1:47846->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
I0713 15:00:33.394215   20440 trace.go:116] Trace[8894544]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2020-07-13 15:00:04.373171458 +0000 UTC m=+181.522533308) (total time: 29.021018202s):
Trace[8894544]: [29.021018202s] [29.021018202s] END
E0713 15:00:33.394392   20440 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Service: an error on the server ("") has prevented the request from succeeding (get services)
E0713 15:00:33.563502   20440 event.go:269] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: read tcp 127.0.0.1:47942->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
I0713 15:00:34.061601   20440 trace.go:116] Trace[620656017]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2020-07-13 15:00:05.035705859 +0000 UTC m=+182.185067690) (total time: 29.025867733s):
Trace[620656017]: [29.025867733s] [29.025867733s] END
E0713 15:00:34.061753   20440 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Endpoints: an error on the server ("") has prevented the request from succeeding (get endpoints)
E0713 15:00:45.564595   20440 event.go:269] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: read tcp 127.0.0.1:48042->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
E0713 15:00:57.565270   20440 event.go:269] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: read tcp 127.0.0.1:48178->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
I0713 15:01:04.962899   20440 trace.go:116] Trace[1934686060]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2020-07-13 15:00:35.941087692 +0000 UTC m=+213.090449794) (total time: 29.021773609s):
Trace[1934686060]: [29.021773609s] [29.021773609s] END
E0713 15:01:04.963058   20440 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Endpoints: an error on the server ("") has prevented the request from succeeding (get endpoints)
I0713 15:01:05.007430   20440 trace.go:116] Trace[1167104410]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2020-07-13 15:00:35.998995547 +0000 UTC m=+213.148357397) (total time: 29.008409478s):
Trace[1167104410]: [29.008409478s] [29.008409478s] END
E0713 15:01:05.007577   20440 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Service: an error on the server ("") has prevented the request from succeeding (get services)
E0713 15:01:09.567587   20440 event.go:269] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: read tcp 127.0.0.1:48298->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
E0713 15:01:21.566639   20440 event.go:269] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: read tcp 127.0.0.1:48382->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
E0713 15:01:33.566536   20440 event.go:269] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: read tcp 127.0.0.1:48480->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
I0713 15:01:37.299398   20440 trace.go:116] Trace[790808918]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2020-07-13 15:01:08.29213159 +0000 UTC m=+245.441493424) (total time: 29.007241176s):
Trace[790808918]: [29.007241176s] [29.007241176s] END
E0713 15:01:37.299545   20440 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Service: an error on the server ("") has prevented the request from succeeding (get services)
I0713 15:01:40.139523   20440 trace.go:116] Trace[364044852]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2020-07-13 15:01:11.109360665 +0000 UTC m=+248.258722494) (total time: 29.030137996s):
Trace[364044852]: [29.030137996s] [29.030137996s] END
E0713 15:01:40.139703   20440 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Endpoints: an error on the server ("") has prevented the request from succeeding (get endpoints)
E0713 15:01:45.566754   20440 event.go:269] Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events: read tcp 127.0.0.1:48568->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
E0713 15:01:45.566946   20440 event.go:214] Unable to write event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"ubuntu-k8s-1.162157e2c16ca66f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ubuntu-k8s-1", UID:"ubuntu-k8s-1", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kube-proxy.", Source:v1.EventSource{Component:"kube-proxy", Host:"ubuntu-k8s-1"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbfbb3b959cebca6f, ext:151634576594, loc:(*time.Location)(0x28a6880)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbfbb3b959cebca6f, ext:151634576594, loc:(*time.Location)(0x28a6880)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}' (retry limit exceeded!)
I0713 15:02:16.338061   20440 trace.go:116] Trace[1721296501]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2020-07-13 15:01:47.335374308 +0000 UTC m=+284.484736117) (total time: 29.002659377s):
Trace[1721296501]: [29.002659377s] [29.002659377s] END
E0713 15:02:16.338085   20440 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Service: an error on the server ("") has prevented the request from succeeding (get services)`

**Logs kubelet rancher/hyperkube:v1.18.3-rancher2** 

`E0713 15:00:13.561661   20584 controller.go:136] failed to ensure node lease exists, will retry in 7s, error: Get https://127.0.0.1:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/ubuntu-k8s-1?timeout=10s: context deadline exceeded
E0713 15:00:13.593952   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:13.694210   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:13.794381   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:13.894694   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:13.995052   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:14.095255   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:14.195665   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:14.296069   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:14.396443   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:14.496810   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
W0713 15:00:14.512090   20584 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
E0713 15:00:14.597303   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:14.697711   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:14.798153   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:14.898604   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:14.999004   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:15.099414   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:15.199819   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:15.300225   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:15.401056   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:15.501520   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:15.601960   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:15.654338   20584 eviction_manager.go:255] eviction manager: failed to get summary stats: failed to get node info: node "ubuntu-k8s-1" not found
E0713 15:00:15.702440   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:15.802881   20584 kubelet.go:2267] node "ubuntu-k8s-1" not found
E0713 15:00:15.892264   20584 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized`

**Logs nginx-proxy rancher/rke-tools:v0.1.58** 
`2020/07/13 15:06:56 [error] 11#11: *2413 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "192.168.8.41:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2020/07/13 15:06:56 [error] 11#11: *2415 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "192.168.8.41:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2020/07/13 15:06:56 [error] 11#11: *2417 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "192.168.8.41:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2020/07/13 15:06:58 [error] 11#11: *2419 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "192.168.8.41:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2020/07/13 15:06:58 [error] 11#11: *2421 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "192.168.8.41:6443", bytes from/to client:0/0, bytes from/to upstream:0/0`

I think node from GCP try to connect to master node in on prem 192.168.8.41:6443, how to change this?

**Comment by superseb** [comment]
Workers need to be able to reach the Control Plane nodes in a cluster, as described on https://rancher.com/docs/rancher/v2.x/en/installation/requirements/ports/. Do you want to configure a different address to reach the master node for the workers?

**Comment by ryzam** [comment]
Hi @superseb , all the necessary port for tcp & udp has been open.  My master node is in on-premise and doesn't have direct public ip. So do i need to change my master node to GCP VM instance?

**Comment by superseb** [comment]
The requirements are listed on https://rancher.com/docs/rancher/v2.x/en/installation/requirements/#networking-requirements, but yes, the worker needs to be able to connect to the controlplane nodes (it locally loadbalances between all controlplane nodes in the cluster)

**Comment by superseb** [comment]
Let me know if you need anything else on this, I don't think there is a bug here.
