### ISSUE TITLE
Monitoring does not work for Windows Server Core worker nodes

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#27911]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Create new Windows Server Core VM
- Add the windows server core VM to Rancher as a worker node
- enable cluster monitoring (or have it already enabled in the cluster prior to joining)

**Result:**
exporter-node-binary-copy container fails to deploy with `encountered an error during Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)`. This prevents the exporter-node-windows-cluster-monitoring workload to finish deploying on the node.

**Other details that may be helpful:**

The same containers deploy and work without an issue on Windows Server (with Desktop experience, aka normal Windows Server) and appears isolated to Windows Server Core.

> W0713 15:16:42.243971    7340 docker_container.go:238] Cannot create symbolic link because container log file doesn't exist!

> E0713 15:16:42.243971    7340 remote_runtime.go:222] StartContainer "118f9659f56343cba90557e25f19a5ee47c15ab524b5156f143505d6107b8693" from runtime service failed: rpc error: code = Unknown desc = failed to start container "118f9659f56343cba90557e25f19a5ee47c15ab524b5156f143505d6107b8693": Error response from daemon: container 118f9659f56343cba90557e25f19a5ee47c15ab524b5156f143505d6107b8693 encountered an error during Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)
E0713 15:16:42.245009    7340 kuberuntime_manager.go:801] init container start failed: RunContainerError: failed to start container "118f9659f56343cba90557e25f19a5ee47c15ab524b5156f143505d6107b8693": Error response from daemon: container 118f9659f56343cba90557e25f19a5ee47c15ab524b5156f143505d6107b8693 encountered an error during Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)

> E0713 15:16:42.245009    7340 pod_workers.go:191] Error syncing pod 52aacfee-2aab-4321-aad6-96ca0feaffc9 ("exporter-node-windows-cluster-monitoring-7lc6l_cattle-prometheus(52aacfee-2aab-4321-aad6-96ca0feaffc9)"), skipping: failed to "StartContainer" for "exporter-node-binary-copy" with RunContainerError: "failed to start container \"118f9659f56343cba90557e25f19a5ee47c15ab524b5156f143505d6107b8693\": Error response from daemon: container 118f9659f56343cba90557e25f19a5ee47c15ab524b5156f143505d6107b8693 encountered an error during Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)"

`
StartTime:2020-07-10 15:23:27 +0000 GMT,ContainerStatuses:[]ContainerStatus{ContainerStatus{Name:exporter-node,State:ContainerState{Waiting:&ContainerStateWaiting{Reason:PodInitializing,Message:,},Running:nil,Terminated:nil,},LastTerminationState:ContainerState{Waiting:nil,Running:nil,Terminated:nil,},Ready:false,RestartCount:0,Image:rancher/wmi_exporter-package:v0.0.3,ImageID:,ContainerID:,Started:*false,},},QOSClass:BestEffort,InitContainerStatuses:[]ContainerStatus{ContainerStatus{Name:exporter-node-binary-copy,State:ContainerState{Waiting:&ContainerStateWaiting{Reason:CrashLoopBackOff,Message:back-off 5m0s restarting failed container=exporter-node-binary-copy pod=exporter-node-windows-cluster-monitoring-7lc6l_cattle-prometheus(52aacfee-2aab-4321-aad6-96ca0feaffc9),},Running:nil,Terminated:nil,},LastTerminationState:ContainerState{Waiting:nil,Running:nil,Terminated:&ContainerStateTerminated{ExitCode:128,Signal:0,Reason:ContainerCannotRun,Message:container 784f0fb958deae0ac7cff7e905d356c8663298c83c6843145b8d5e50c0194751 encountered an error during Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106),StartedAt:2020-07-13 15:11:32 +0000 GMT,FinishedAt:2020-07-13 15:11:32 +0000 GMT,ContainerID:docker://784f0fb958deae0ac7cff7e905d356c8663298c83c6843145b8d5e50c0194751,},},Ready:false,RestartCount:846,Image:rancher/wmi_exporter-package:v0.0.3,ImageID:docker-pullable://rancher/wmi_exporter-package@sha256:556b1cf82783af8c0ec298315d48bf82cf6fb1864ffdf8736477a72d67af2be4,ContainerID:docker://784f0fb958deae0ac7cff7e905d356c8663298c83c6843145b8d5e50c0194751,Started:nil,},},NominatedNodeName:,PodIPs:[]PodIP{PodIP{IP:10.42.4.3,},},EphemeralContainerStatuses:[]ContainerStatus{},},} container id:  118f9659f56343cba90557e25f19a5ee47c15ab524b5156f143505d6107b8693`

One other item to note: service-sidekick does a goroutine panic on a Windows Server Core VM while running but it reports that it recovers. This behavior is not seen on a normal windows server node.
```
I0710 15:23:40.415037    5272 device_windows.go:124] Created HostComputeNetwork vxlan0
panic: reflect: Field index out of range [recovered]
        panic: reflect: Field index out of range

goroutine 1 [running]:
encoding/json.(*encodeState).marshal.func1(0xc0001db540)
        /usr/local/go/src/encoding/json/encode.go:301 +0xa1
panic(0x121d7c0, 0x157a2b0)
        /usr/local/go/src/runtime/panic.go:513 +0x1c7
reflect.Value.Field(0x130ff60, 0xc00032b3e0, 0x99, 0x2d383632342d3032, 0xc0002e9e30, 0xc0000c82c0, 0x12ee720)
        /usr/local/go/src/reflect/value.go:816 +0x148
encoding/json.fieldByIndex(0x130ff60, 0xc00032b3e0, 0x99, 0xc00034a6d0, 0x1, 0x1, 0x12ee720, 0xc00032b3e0, 0x99)
        /usr/local/go/src/encoding/json/encode.go:842 +0x65
encoding/json.(*structEncoder).encode(0xc0002e9e00, 0xc0000c82c0, 0x130ff60, 0xc00032b3e0, 0x99, 0x1300100)
        /usr/local/go/src/encoding/json/encode.go:635 +0x149
encoding/json.(*structEncoder).encode-fm(0xc0000c82c0, 0x130ff60, 0xc00032b3e0, 0x99, 0xc0001d0100)
        /usr/local/go/src/encoding/json/encode.go:661 +0x6b
encoding/json.(*encodeState).reflectValue(0xc0000c82c0, 0x130ff60, 0xc00032b3e0, 0x99, 0x1fd0100)
        /usr/local/go/src/encoding/json/encode.go:333 +0x89
encoding/json.(*encodeState).marshal(0xc0000c82c0, 0x130ff60, 0xc00032b3e0, 0x100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:305 +0xfb
encoding/json.Marshal(0x130ff60, 0xc00032b3e0, 0x130ff60, 0xc00032b3e0, 0x0, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:160 +0x59
github.com/coreos/flannel/vendor/github.com/Microsoft/hcsshim/hcn.modifyNetwork(0xc0004c6de0, 0x24, 0xc000514460, 0x6a, 0xc000514460, 0x6a, 0x0)
        /go/src/github.com/coreos/flannel/vendor/github.com/Microsoft/hcsshim/hcn/hcnnetwork.go:224 +0x1d1
github.com/coreos/flannel/vendor/github.com/Microsoft/hcsshim/hcn.(*HostComputeNetwork).ModifyNetworkSettings(0xc0003de1e0, 0xc000069d00, 0xc00002e540, 0x31)
        /go/src/github.com/coreos/flannel/vendor/github.com/Microsoft/hcsshim/hcn/hcnnetwork.go:356 +0x13c
github.com/coreos/flannel/vendor/github.com/Microsoft/hcsshim/hcn.(*HostComputeNetwork).AddPolicy(0xc0003de1e0, 0xc00032b1d0, 0x1, 0x1, 0x2, 0x8)
        /go/src/github.com/coreos/flannel/vendor/github.com/Microsoft/hcsshim/hcn/hcnnetwork.go:377 +0x1b9
github.com/coreos/flannel/backend/vxlan.ensureLink(0xc000125480, 0xc000125480, 0x130fc60, 0x1)
        /go/src/github.com/coreos/flannel/backend/vxlan/device_windows.go:147 +0x348
github.com/coreos/flannel/backend/vxlan.newVXLANDevice(0xc0002e9b30, 0xc0002e9b30, 0xc00023a4c0, 0xc0001baf60)
        /go/src/github.com/coreos/flannel/backend/vxlan/device_windows.go:47 +0x7a
github.com/coreos/flannel/backend/vxlan.(*VXLANBackend).RegisterNetwork(0xc0006310a0, 0x2330138, 0xc00023a4c0, 0x100000000, 0xc000000000, 0xc0000ae640, 0x0, 0xc00009c082, 0xf, 0xc000663698)
        /go/src/github.com/coreos/flannel/backend/vxlan/vxlan_windows.go:149 +0x514
main.main()
        /go/src/github.com/coreos/flannel/main.go:289 +0x735
```

More logs available on request.
**Cluster information**

Cluster type: Hosted Rancher
Machine type: AWS t3a.xlarge
AMI: Windows_Server-1909-English-Core-Base-2020.06.10 (ami-0e9662f7dc78f5a18)
OS: Windows Server Datacenter 10.0.18363.900
Rancher v2.4.5
K8s v1.18.3
Docker version 19.03.5, build 2ee0c57608

gz#11061
gz#13205

**Comment by aiwantaozi** [comment]
Check the crash log, we have a [project](https://github.com/rancher/wmi_exporter-package) to package window node export [windows_exporter](https://github.com/prometheus-community/windows_exporter), logs show that container crash when modifyNetwork `github.com/Microsoft/hcsshim/hcn/hcnnetwork.go:224`, seems like this node HCS query result isn't expected one. But I'm not familiar debug with window HCS, may windows colleague help?

**Comment by maggieliu** [comment]
Also need to make sure monitoring v1 works on 1909

**Comment by aiyengar2** [comment]
@rosskirkpat I suspect the root cause here is because your Windows node doesn't have `c:\etc\wmi-exporter\wmi-exporter.exe`, which is the file that the `exporter-node-binary-copy` container tries to transfer to a new location ([as shown in the ConfigMap it mounts as the Powershell script to be run on start](https://github.com/rancher/system-charts/blob/aefdee237acd5c89ed7e6225f9040f51707f562a/charts/rancher-monitoring/v0.1.2/charts/exporter-node-windows/templates/configmap.yaml#L51)). You also similarly may not have flannel installed as a service.

Did the cluster that you were working with have Windows support already enabled via Rancher (on cluster create)? 

If you added the windows server core VM to Rancher as a worker node to a cluster that did not have Windows support enabled on creation, [some of the bootstrapping we do](https://github.com/rancher/rancher/blob/495f7a1d600af79678c8533f221991085cd42bb5/package/windows/bootstrap.ps1#L52-L80) in order to get services like `flannel` or `wmi_exporter` running on your machine may not have been run. This would explain both the errors you noted in the issue and, as noted in [the docs](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/), can only be resolved by creating a new cluster with that node.

**Comment by rosskirkpat** [comment]
@aiyengar2 
>Did the cluster that you were working with have Windows support already enabled via Rancher (on cluster create)?

Yes, it did. Seeing as the cluster is long gone at this point, I'm spinning up a new 2.4.11 mixed cluster with k8s v1.18.12 to validate the level of functionality of Windows 1909 Server Core. I'll update here with my results.

**Comment by aiyengar2** [comment]
@rosskirkpat I was able to spin up a GKE cluster with version Windows Server version 1909 Datacenter Core for Containers and deploy Monitoring V1 on it successfully, so this may be an environment-specific issue.

#### More details

I spun up a k8s cluster using the following configurations for GCE nodes:
- [ubuntu] 1 Ubuntu worker/etcd/controlplane
- [default-access-1809] 1 Windows 2019 Server, where `Identity and API access` -> `Access Scopes` -> `Allow default access`
- [default-access-1909] 1 Windows 1909 Datacenter Core for Containers, where `Identity and API access` -> `Access Scopes` -> `Allow default access`
- [allow-all-access-1909] 1 Windows 1909 Datacenter Core for Containers, where `Identity and API access` -> `Access Scopes` -> `Allow full access to all Cloud APIs`

What I noticed, however, was that the deployment of `cattle-node-agent-windows` on node `default-access-1909` was stuck on `ContainerCreating`. 

`kubectl describe` revealed that this was caused by a failure to create the pod sandbox.
![Screen Shot 2020-12-19 at 8 29 23 PM](https://user-images.githubusercontent.com/13127443/102705165-3c780600-4239-11eb-82c8-73d3ae98a109.png)

Upon checking the kubelet logs on the `default-access-1909` Windows host to see why that might be the case, I found the following logs showed up:

![Screen Shot 2020-12-19 at 8 06 56 PM](https://user-images.githubusercontent.com/13127443/102705007-88c24680-4237-11eb-80ab-c96e537240fe.png)

This issue did not affect `default-access-1809` or `allow-all-access-1909` and these specific error logs are also missing from those nodes. 

Once I removed `default-access-1909` from the cluster, Monitoring V1 was successfully deployed, so this might just be a GCE-specific issue.

**Comment by sowmyav27** [comment]
**On `2.5.4-rc7`**

- Deployed 1909 windows server core version
- monitoring v1 fails to deploy
- Error on `exporter-node-windows-cluster-monitoring` pod: `Error: failed to start container "exporter-node-binary-copy": Error response from daemon: container exporter-node-binary-copy encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)`

**Comment by sowmyav27** [comment]
**On 2.5.5, using AMI from GCP - `windows-server-1909-dc-core-for-containers-v20210112`** 

- Deploy Windows 1909 - 1 etcd/control/worker linux node, 2 linux worker nodes and 3 windows worker nodes.
- Enable monitoring v1 - 0.2.0. Monitoring is seen enabled successfully.
- `exporter-node-windows-cluster-monitoring` workload deployed successfully on Windows nodes.
- Metrics from windows nodes are available.

**Comment by aiyengar2** [comment]
@sowmyav27 can we check if the issue still appears in AWS (tested in https://github.com/rancher/rancher/issues/27911#issuecomment-750579236)?

Given that Monitoring V1 works in GKE, this could be an AMI specific issue.

**Comment by aiyengar2** [comment]
Also, instead of using `Windows_Server-1909-English-Core-Base-2020.06.10 (ami-0e9662f7dc78f5a18)`, I think we should try to reproduce using the Containers equivalent of the AMI, i.e.

`Windows_Server-1909-English-Core-ContainersLatest-2021.01.13 (ami-08c8719f1e743ff72)`

This more closely aligns with what we tested in GCP, which was Datacenter Core for Containers, not Datacenter Core Base.

Based on discussion offline during the initial error in AWS reproduced in https://github.com/rancher/rancher/issues/27911#issuecomment-750579236, one of the things I discovered was that the AMI itself did not have Docker EE installed at all so we ran the following as part of the provisioning step manually in order to get Docker EE installed:
```powershell
iwr -outf docker-install.ps1 -uri https://gist.githubusercontent.com/thxCode/cd8ec26795a56eb120b57675f0c067cf/raw/4129222b07d17fb591182ca839ce6d83e6a203e9/docker-install.ps1; ./docker-install.ps1 -Version 19.03
```

However, it's possible that more changes were required on the host in order to actually get containers on the Server Core Base.

**Comment by slickwarren** [comment]
Tested on 2.5-head (2ae4cf117ac988ce409ca0617d246008f74c7aaa) using `Windows_Server-1909-English-Core-ContainersLatest-2021.01.13` as the base AMI
* Deployed 1909 windows server ContainersLatest version
* monitoring v1 fails to deploy
* Error on exporter-node-windows-cluster-monitoring `Error from server (BadRequest): container "exporter-node" in pod "exporter-node-windows-cluster-monitoring-rfm88" is waiting to start: PodInitializing`

**Comment by SheilaghM** [comment]
@slickwarren - can you please test on a different version of Windows_Server?  A version prior to 1909.  Thanks.

**Comment by sowmyav27** [comment]
@SheilaghM We have validated monitoring on windows as said [here](https://github.com/rancher/rancher/issues/27911#issuecomment-769316393) using `Windows_Server-1909-English-Core-ContainersLatest-2021.01.13`. Monitoring v1 works on 1903/1809. It also works on 1909 using GCE nodes. This issue seems specific to AWS AMIs.

**Comment by aiyengar2** [comment]
Upgrading the version of wmi_exporter seems to do the trick!

As noted in the PR linked above, I suspect that the issue that we see was caused by the following announcement: https://support.microsoft.com/en-us/topic/you-might-encounter-issues-when-using-windows-server-containers-with-the-february-11-2020-security-update-release-b9a8fcae-950d-7a0b-ac7c-cb6b294cb809.

wmi_exporter-package v0.0.3 was built in September 17, 2019 while v0.0.4 (which works) was built on October 26th, 2020.

AWS docs seem to indicate that they keep up to date with Windows security updates (see https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-windows-ami-version-history.html#amis-2020), but I'm not sure about GCE. On looking at the actual VM, I noticed that `Get-Hotfix` didn't result in nearly as many Windows patches applied, so it's possible / likely they could have not absorbed that security fix yet.

**Comment by aiyengar2** [comment]
@sowmyav27 @slickwarren we need to test two new chart versions for this release: `v0.1.5` (for k8s 1.15 support) and `v0.2.1` (for k8s 1.16+). The only changes introduced to both are to bump the wmi_exporter-package version, so only Windows clusters need to be tested.

Both versions exist in dev-v2.5, but have not been backported into dev-v2.4. 

@Jono-SUSE-Rancher @SheilaghM we also need to create a separate issue to backport these two charts into the 2.4 release line once this has been tested. Which release do we want to target that for?

**Comment by thehejik** [comment]
I deployed windows cluster on AWS (us-east-1) by using rancher `v2.5.4-rc4` with kubernetes `v1.18.15-rancher2-1`. Also successfully deployed v1 `monitoring v0.2.1` and all the metrics from the windows worker machine are visible in Rancher Amber UI as well as in Grafana. 

<details>
  <summary>All the related resources are Ready and healthy</summary>

```
thehejik@dell:~/tmp> kubectl get all -n cattle-prometheus
NAME                                                           READY   STATUS    RESTARTS   AGE
pod/exporter-kube-state-cluster-monitoring-686c467bfb-cd7t4    1/1     Running   0          71m
pod/exporter-node-cluster-monitoring-vbkbt                     1/1     Running   0          71m
pod/exporter-node-cluster-monitoring-wf5xb                     1/1     Running   0          71m
pod/exporter-node-windows-cluster-monitoring-r4r9g             1/1     Running   0          71m
pod/grafana-cluster-monitoring-5db6bdf857-zk5df                2/2     Running   0          71m
pod/prometheus-cluster-monitoring-0                            5/5     Running   1          71m
pod/prometheus-operator-monitoring-operator-5f8bbdc5b6-p65x4   1/1     Running   0          71m

NAME                                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                        AGE
service/access-grafana                  ClusterIP   10.43.255.108   <none>        80/TCP                         71m
service/access-prometheus               ClusterIP   10.43.127.193   <none>        80/TCP                         71m
service/expose-grafana-metrics          ClusterIP   None            <none>        3000/TCP                       71m
service/expose-kube-cm-metrics          ClusterIP   None            <none>        10252/TCP                      71m
service/expose-kube-etcd-metrics        ClusterIP   None            <none>        2379/TCP                       71m
service/expose-kube-scheduler-metrics   ClusterIP   None            <none>        10251/TCP                      71m
service/expose-kubelets-metrics         ClusterIP   None            <none>        10250/TCP,10255/TCP,4194/TCP   71m
service/expose-kubernetes-metrics       ClusterIP   None            <none>        8080/TCP,8081/TCP              71m
service/expose-node-metrics             ClusterIP   None            <none>        9796/TCP                       71m
service/expose-node-metrics-windows     ClusterIP   None            <none>        9796/TCP                       71m
service/expose-operator-metrics         ClusterIP   None            <none>        47323/TCP                      71m
service/expose-prometheus-metrics       ClusterIP   None            <none>        9090/TCP                       71m
service/prometheus-operated             ClusterIP   None            <none>        9090/TCP                       71m

NAME                                                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR              AGE
daemonset.apps/exporter-node-cluster-monitoring           2         2         2       2            2           kubernetes.io/os=linux     71m
daemonset.apps/exporter-node-windows-cluster-monitoring   1         1         1       1            1           kubernetes.io/os=windows   71m

NAME                                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/exporter-kube-state-cluster-monitoring    1/1     1            1           71m
deployment.apps/grafana-cluster-monitoring                1/1     1            1           71m
deployment.apps/prometheus-operator-monitoring-operator   1/1     1            1           71m

NAME                                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/exporter-kube-state-cluster-monitoring-686c467bfb    1         1         1       71m
replicaset.apps/grafana-cluster-monitoring-5db6bdf857                1         1         1       71m
replicaset.apps/prometheus-operator-monitoring-operator-5f8bbdc5b6   1         1         1       71m

NAME                                             READY   AGE
statefulset.apps/prometheus-cluster-monitoring   1/1     71m
```
</details>

Cluster info:
- Rancher `v2.5.4-rc4` with kubernetes `v1.18.15-rancher2-1`
- Rancher with added system-library helm charts repo https://git.rancher.io/system-charts branch dev-v2.5
- AWS region us-east-1
- opened all inbound TCP and UDP traffic
- used AMIs:
   - linux master and worker: `ami-0dc3ca5b357a16549` - openSUSE-Leap-15.2-v20200710-HVM-x86_64-548f7b74-f1d6-437e-b650-f6315f6d8aa3-ami-0f5745b812a5b7654.4
  - windows worker: `ami-008ec03d9035c8ee7` - Windows_Server-1909-English-Core-ContainersLatest-2021.01.13 

linux VMs type: t3.large 10GB SDD
windows VMs type: t3.xlarge 50GB SSD

I'm going to test the same with k8s v1.15 and v0.15 monitoring chart.

**Comment by thehejik** [comment]
The same as above stands for `monitoring v0.1.5` and kubernetes `v1.15.12-rancher2-8` on rancher `v2.5.6-rc4` (the unsupported version `kubernetes_version: v1.15.12-rancher2-8` specified in 'Edit as yaml' when creating the cluster).

Also here all metrics are visible in Amber UI & Grafana and all the related resources are Ready and healthy.

<details>
  <summary>Click here to expand.</summary>

```
thehejik@dell:~/tmp> kubectl get all -n cattle-prometheus
NAME                                                          READY   STATUS    RESTARTS   AGE
pod/exporter-kube-state-cluster-monitoring-5fdddf5844-zsqts   1/1     Running   0          15m
pod/exporter-node-cluster-monitoring-92tcm                    1/1     Running   0          15m
pod/exporter-node-cluster-monitoring-tjm6j                    1/1     Running   0          15m
pod/exporter-node-windows-cluster-monitoring-rblzc            1/1     Running   0          15m
pod/grafana-cluster-monitoring-6bd6cffb9f-7scgz               2/2     Running   0          15m
pod/prometheus-cluster-monitoring-0                           5/5     Running   1          15m
pod/prometheus-operator-monitoring-operator-7b4c8c6f7-jxfrb   1/1     Running   0          16m

NAME                                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                        AGE
service/access-grafana                  ClusterIP   10.43.205.137   <none>        80/TCP                         15m
service/access-prometheus               ClusterIP   10.43.163.239   <none>        80/TCP                         15m
service/expose-grafana-metrics          ClusterIP   None            <none>        3000/TCP                       15m
service/expose-kube-cm-metrics          ClusterIP   None            <none>        10252/TCP                      15m
service/expose-kube-etcd-metrics        ClusterIP   None            <none>        2379/TCP                       15m
service/expose-kube-scheduler-metrics   ClusterIP   None            <none>        10251/TCP                      15m
service/expose-kubelets-metrics         ClusterIP   None            <none>        10250/TCP,10255/TCP,4194/TCP   16m
service/expose-kubernetes-metrics       ClusterIP   None            <none>        8080/TCP,8081/TCP              15m
service/expose-node-metrics             ClusterIP   None            <none>        9796/TCP                       15m
service/expose-node-metrics-windows     ClusterIP   None            <none>        9796/TCP                       15m
service/expose-operator-metrics         ClusterIP   None            <none>        47323/TCP                      16m
service/expose-prometheus-metrics       ClusterIP   None            <none>        9090/TCP                       15m
service/prometheus-operated             ClusterIP   None            <none>        9090/TCP                       15m

NAME                                                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR              AGE
daemonset.apps/exporter-node-cluster-monitoring           2         2         2       2            2           kubernetes.io/os=linux     15m
daemonset.apps/exporter-node-windows-cluster-monitoring   1         1         1       1            1           kubernetes.io/os=windows   15m

NAME                                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/exporter-kube-state-cluster-monitoring    1/1     1            1           15m
deployment.apps/grafana-cluster-monitoring                1/1     1            1           15m
deployment.apps/prometheus-operator-monitoring-operator   1/1     1            1           16m

NAME                                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/exporter-kube-state-cluster-monitoring-5fdddf5844   1         1         1       15m
replicaset.apps/grafana-cluster-monitoring-6bd6cffb9f               1         1         1       15m
replicaset.apps/prometheus-operator-monitoring-operator-7b4c8c6f7   1         1         1       16m

NAME                                             READY   AGE
statefulset.apps/prometheus-cluster-monitoring   1/1     15m

```
</details>

![win_monitoring-1 15](https://user-images.githubusercontent.com/12828077/107798913-0a78b100-6d5d-11eb-9e66-07d313d29966.png)
