### ISSUE TITLE
service stuck in "activating" state forever when trying to deploy with an invalid volumedriver.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2792]
Server version - V0.47.0-rc1

Deployed "Gluster FS" and "Convoy Gluster” stacks with 2 hosts in my setup as part of convoy storage pool - "convoy-gluster".

Create volume with driver as "myconvoy" (which is non existent storage pool)
Volume gets created successfully.

Launch a service using this volume driver - "myconvoy" using the following launch config:

```
    launch_config = {"imageUuid": <image id,
                     "dataVolumes": ["testnow4:/testmydir1"],
                     "volumeDriver": "myconvoy"
                     }
```

container fails to deploy with error message - 
State: Removed ( : 46518b36-e45a-441c-9c8a-ed8afe7d128c : 500 Server Error: Internal Server Error ("Error looking up volume plugin myconvoy: Post http:///var/lib/rancher/convoy/myconvoy-22410785-1b92-4580-8ce3-107038dbf183.sock/Plugin.Activate: dial unix /var/lib/rancher/convoy/myconvoy-22410785-1b92-4580-8ce3-107038dbf183.sock: connection refused"))

Service is stuck in activating state forever.

API should be able to do some checks for validity of volumedriver and error out before trying to start containers on non existent drivers.

**Comment by cjellick** [comment]
We cannot do those kind of checks. The value of volumeDriver can be anything. The user could have any number of volume drivers installed on the host and we would never know.

**Comment by deniseschannon** [comment]
@sangeethah Based on @cjellick's comment, would you be willing to close? 

If the service is stuck in activating, do we at least display the error container message?
