### ISSUE TITLE
Error Facing with Rancher and AKS

### ISSUE THREAD

**Issue by raviseerapu** [rancher/rancher#27921]
Very simple way to deploy AKS using Rancher Server. 

But the facing the same error again and again...but i could find the logs...hence posting this issue.

Error getting Resource Group 'aksrancher': resources.GroupsClient#CheckExistence: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF

No Internet firewall. No Port block..No authentication and authorization issues..etc.

**Comment by junkiebev** [comment]
Which version of Rancher? I had this issue before `v2.4.5`
