### ISSUE TITLE
Feature requests : Option in rke to add custom annotations on Nginx Ingress

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#27922]
**What kind of request is this?**
Feature request

**Other details that may be helpful:**
When deploying cluster using RKE, the Nginx ingress controller pods need few custom annotations. 

Eg:- Filebeat Autodiscover 

https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html

gz#11172

gz#11943

**Comment by oncipriani** [comment]
This functionality would indeed be useful.
