### ISSUE TITLE
[Logging v2] Chart and Installation

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#27935]

**Comment by izaac** [comment]
After settomg `enableRecreateWorkloadOnImmutableFieldChange: true` to logging and configuring a Persistent Volume I was able to see the logs reaching my Elasticsearch server.

 I deployed the chart from Dashboard in a k8s HA install. And I had to use the `local` cluster as there's a an issue accessing Apps in master-head in clusters other than `local`.

**Comment by izaac** [comment]
Closing we're tracking issues related to this epic separate issues linked to this one.
