### ISSUE TITLE
[Logging v2] Control Plane logs - rke, k3s, rke2

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#27938]

**Comment by paynejacob** [comment]
https://github.com/rancher/charts/pull/549

**Comment by cbron** [comment]
@izaac when we test here we should mimic the v1 cluster logging flow, to ensure that we would get the same thing with v2. Make sure that we don't miss the various parts of the control plane. We can chat about this.

**Comment by izaac** [comment]
Log collection validated working on:

- k3s openrc
- rke2
- Issue opened for k3s systemd -> #28584

**Comment by izaac** [comment]
RKE will be covered in #28460 and there's a separate issue for the remaining k3s QA coverage.
