### ISSUE TITLE
[Logging v2] Cluster logging - All Output Providers

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#27937]
- [x] Allows deployment to all providers via the helm chart / UI
- [x] Add cluster roles that aggregate to kube roles

Providers
- [x] Elasticsearch
- [x] Kafka
- [x] splunk
- [x] syslog

**Comment by izaac** [comment]
This issue is blocking validation: #28159

**Comment by izaac** [comment]
Rancher version `master-head (08/25/2020)` _45e3e23cd_
Outputs tested so far:
- Elasticsearch
- Splunk
- syslog

**Comment by izaac** [comment]
Rancher version `master-head (08/26/2020)` _9b6984d5f_

Output validated: 

- Kafka -> INFO Kafka version: 2.6.0


Setup kafka with basic plain communication using kafka-docker.
Checked the logs using a consumer until I got the partition with recods populated.
