### ISSUE TITLE
Rancher not deleting nodes from VMWare

### ISSUE THREAD

**Issue by B3DTech** [rancher/rancher#27933]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

We're modifying nodes, deleting, consolidating and redeploying master, etcd and worker nodes across our clusters.  We use vSphere 6.7 and have never had an issue before.  Now the nodes are being removed from Rancher, but they aren't being deleted from vCenter, which causes issues if you're redeploying a node with the same name, and leaves remnants around that we need to remember to clean up.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  v2.3.7
- Installation option (single install/HA): Single

**Comment by dbsanfte** [comment]
We also experience this with our vSphere. Rancher doesn't clean up VMs, and there's no way to force it to overwrite existing VMs in the case of a naming collision.

Rancher should have a setting whereby it will delete any existing VMs in the event of a naming collision.

**Comment by dbsanfte** [comment]
We saw this again last week where Rancher 2 lost contact with a vSphere cluster node, then spent an entire day trying to recreate it without first deleting it, spamming our vSphere cluster with requests. Why does it do this? /shrug

**Comment by behnm** [comment]
I have the same issue. 
I deleted the node vm manually,  however the rancher doesn't  after several min, show me this error again. the rancher version is 2.5.5

**Comment by UristMcMiner** [comment]
This issue still persists in Rancher 2.6.3-patch1.
