### ISSUE TITLE
image list with next lines

### ISSUE THREAD

**Issue by mjschmidt** [rancher/rancher#27934]
in the releases it would be really great if there was a next line or semicolon or something between images for all the containers needed to run in offline mode. When I down load the text file its all mashed together with no separation. It means I have to go through and manually parse the file.

**Comment by vincent99** [comment]
Where are you getting the list?  There are newlines in https://github.com/rancher/rancher/releases/download/v2.4.5/rancher-images.txt

**Comment by mjschmidt** [comment]
omg sorry vincent... i opened it with notepad instead of notepad++...

closing issue.
