### ISSUE TITLE
Monitoring v2 - disable default exporters does not work

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#27949]
**What kind of request is this (question/bug/enhancement/feature request):**
bug 

**Steps to reproduce (least amount of steps as possible):**
- Launch the Rancher-Monitoring-v2 app without Default Exporters

![image](https://user-images.githubusercontent.com/6218999/87611986-3a27e380-c6be-11ea-8053-c57451b4d106.png)

**Result:**
- all exporters related deployments are deployed, which is the opposite of what we expect 

<img width="1430" alt="Screen Shot 2020-07-15 at 5 08 36 PM" src="https://user-images.githubusercontent.com/6218999/87612090-79eecb00-c6be-11ea-8d11-2899bf8baad0.png">

- It looks like setting `Configure Default Exporters` False makes all sub-settings applied as True.

**Comment by aiyengar2** [comment]
Closing this issue out as we're moving in favor of Custom UIs for launching Monitoring V2
