### ISSUE TITLE
Istio v2: Install customizations and airgap

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#27943]
- [x] 1) Allow a user to pass in a custom IstioOperator CR overlay, which can enable custom settings. Use the [analyze](https://istio.io/docs/reference/commands/istioctl/#istioctl-analyze) cmd to check this. Ensure multiple ingress and egress gateways work.
- [x] 2) Ensure we can install custom ingress-gateways to multiple namespaces
- [x] 3) Determine if the Istio manifests need to be forked to handle our customizations. If so, create a process to copy the istio manifests and modify them, for example a patch file. The primary (but not only) point of the manifest customizations is to remove all hardcoded images. These will need to be added to the installer image. 
- [x] 4) All images used in the manifests, whether custom or built-in, must be listed (ideally programmatically) to be included in rancher-images.txt for airgap mode. This will likely be done inside dev-charts. 
- [x] 5) Mirror all the images to our dockerhub
- [x] 6) Enable istio to show up as an app in GUI by adding labels/annotations to the istio pods that are version specific. 
- [x] 7) Ensure all custom helm values work.
- [x] 8) Ensure no-downtime deploy works when upgrading both values and the control plane. If an app using Istio is deployed I should see no downtime there either, and should be able to see traffic graph in kiali. [See recommendations](https://istio.io/latest/docs/setup/upgrade/#upgrade-steps) around disruption budgets among other things.
- [x] 10) Ensure uninstallation works properly. Somewhat tricky as it will have to be a pre-delete helm hook before chart is uninstalled. Uninstall _must remove all CRDs_.
- [x] 11) Ensure privilege escalation is not possible.

**Comment by bmdepesa** [comment]
```
Ensure no-downtime deploy works when upgrading both values and the control plane. If an app using Istio is deployed I should see no downtime there either, and should be able to see traffic graph in kiali. See recommendations around disruption budgets among other things.
```
```
Ensure privilege escalation is not possible
```
These specifically and airgap install still need to be tested.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head v2.5.0-alpha3

* Deploy Rancher on a large node
* Go to dashboard in the local cluster
* Enable monitoring
* Install Istio
* Kiali deploys, but the istio installer pod has an image pull backoff error:
```
BackOff	Back-off pulling image "rancher/istio-installer:1.7.0-rancher1"	Fri, Sep 18 2020 2:03:25 pm
Failed	Failed to pull image "rancher/istio-installer:1.7.0-rancher1": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/istio-installer:1.7.0-rancher1": failed to resolve reference "docker.io/rancher/istio-installer:1.7.0-rancher1": failed to do request: Head https://registry-1.docker.io/v2/rancher/istio-installer/manifests/1.7.0-rancher1: dial tcp 52.20.56.50:443: i/o timeout	Fri, Sep 18 2020 2:03:25 pm
```
* The UI sends the correct registry information:
<img width="792" alt="Screen Shot 2020-09-18 at 2 12 00 PM" src="https://user-images.githubusercontent.com/21316915/93645999-2ba9c100-f9ba-11ea-8cce-cbf3fdc2fd37.png">

**Comment by cbron** [comment]
@brendarearden we never put registry on installer: https://github.com/rancher/charts/blob/dev-v2.5/packages/rancher-istio/charts/templates/istio-install-job.yaml#L16
It's also not setup to get picked up to images.txt because its missing repo/tag format.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.0-alpha4

* Single node airgap install
* Create a custom cluster
* Enable monitoring, Istio on local and downstream cluster
* Istio deploys successfully
* Kiali is able to display graph from Prometheus metrics
