### ISSUE TITLE
Monitoring v2 - Service for Prometheus is broken 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#27946]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run rancher:master-3301-head, single install 
- provision an RKE cluster
- install the monitoring v2 chart 
- create an ingress for the Prometheus deployment 

![image](https://user-images.githubusercontent.com/6218999/87599290-5882e480-c6a8-11ea-8649-43e930fa1041.png)

**Result:**
cannot open the URL in the browser to access to the Prometheus UI

**Cause:**
The service `rancher-monitoring-v2-prometheus` selects pods with all the following 3 labels, but the pods of Prometheus do not have the middle label, so no pod is selected. 

<img width="752" alt="Screen Shot 2020-07-14 at 4 35 46 PM" src="https://user-images.githubusercontent.com/6218999/87600149-abf53280-c6a8-11ea-9ae7-c8014e12e68d.png">

labels on the pod `prometheus-rancher-monitoring-v2-prometheus-0`
<img width="838" alt="Screen Shot 2020-07-15 at 2 40 04 PM" src="https://user-images.githubusercontent.com/6218999/87601004-19a15e80-c6a9-11ea-919e-1987df093e2b.png">

**Comment by aiyengar2** [comment]
Talked to @jiaqiluo offline about this:

The extra label added for `io.cattle.field/appId` may also affect whether data shows up on the Grafana dashboard since the label selection is modified based on the new label added.

@deniseschannon @maggieliu since this only affects the scenario where Monitoring V2 is deployed as an application within a project in Rancher 2.4, is this in scope for 2.5 or should this be 2.5.x?

**Comment by jiaqiluo** [comment]
@aiyengar2 

Confirmed on the lasted master-head `master-4911f8b116eb845ce72bda40fc449f0a4ce54025-head` with the latest chart that 
- the bug happens only when the monitoring v2 app is deployed via the MCM UI as an app (cluster -> any project -> app -> deploy). 
- the bug does NOT happen if the monitoring v2 app is installed via the dashboard (Dashboard -> app -> create)

**Comment by deniseschannon** [comment]
We only expect Monitoring v2 to be deployed through Cluster Explorer. 

@jiaqiluo How were you deploying this in Ember UI? Was this chart showing up in the Cluster Manager UI?

**Comment by jiaqiluo** [comment]
@deniseschannon  Yes, you are right that monitoring v2 should be deployed only in the Cluster Manager UI. 

This issue was logged when the Monitoring v2 at the early development stage, and the issue is not applied anymore. 

Close this issue.
