### ISSUE TITLE
Workload: cattle-node-agent-windows continuously crashing on windows cluster

### ISSUE THREAD

**Issue by khatrig** [rancher/rancher#27956]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a windows cluster using rancher UI with flannel host-gw/vxlan mode and add a windows node 

**Result:**
Workload: cattle-node-agent-windows keep crashing continuously with the following error in the log:

_WARN: Default docker named pipe is not found
WARN: Please bind mount in the docker named pipe to //./pipe/docker_engine if docker errors occur
WARN: example: docker run -v //./pipe/custom_docker_named_pipe://./pipe/docker_engine ...
FATA: https://MASKEDHOSTNAME is not accessible_

**Other details that may be helpful:**
**Event logs** -

_Warning	BackOff	Back-off restarting failed container	4 minutes ago
Warning	FailedCreatePodSandBox	(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "0eb1c96eb7c0808650eda23168fab934b08d92f23cea43758c95fb9e35677334" network for pod "cattle-node-agent-windows-9dqcj": networkPlugin cni failed to set up pod "cattle-node-agent-windows-9dqcj_cattle-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.	8 minutes ago
Normal	SandboxChanged	Pod sandbox changed, it will be killed and re-created.	8 minutes ago
Warning	FailedCreatePodSandBox	Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "0c2412c03240659f211db7393221760adec9132a1c163b986487687701f7b186" network for pod "cattle-node-agent-windows-9dqcj": networkPlugin cni failed to set up pod "cattle-node-agent-windows-9dqcj_cattle-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.	8 minutes ago
Warning	FailedCreatePodSandBox	Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "12bd4ec671973ed3f27d4568c433eaccb9d9612b66e7feb998f838cb6549d98e" network for pod "cattle-node-agent-windows-9dqcj": networkPlugin cni failed to set up pod "cattle-node-agent-windows-9dqcj_cattle-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.	8 minutes ago
Warning	FailedCreatePodSandBox	Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "2e358d457879cd37542cabbf5f82b3dc060d04f1c9aeea52b21a1ab6838734d1" network for pod "cattle-node-agent-windows-9dqcj": networkPlugin cni failed to set up pod "cattle-node-agent-windows-9dqcj_cattle-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.	8 minutes ago
Warning	FailedCreatePodSandBox	Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c4ae67283d8ff1d0d1f10bbf50ab9acf50cedc1683c6c9043bbfb72e8cbb844b" network for pod "cattle-node-agent-windows-9dqcj": networkPlugin cni failed to set up pod "cattle-node-agent-windows-9dqcj_cattle-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.	8 minutes ago
Warning	FailedCreatePodSandBox	Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "0595d641d35d1c4c2db07f13726ab61135ddfb72bfa511bbceb25a2b9213dbe4" network for pod "cattle-node-agent-windows-9dqcj": networkPlugin cni failed to set up pod "cattle-node-agent-windows-9dqcj_cattle-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.	8 minutes ago
Warning	FailedCreatePodSandBox	Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "48c3840b90ba79ac1d572b0ad47e5abd3e213851de542094c66096b46f714662" network for pod "cattle-node-agent-windows-9dqcj": networkPlugin cni failed to set up pod "cattle-node-agent-windows-9dqcj_cattle-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.	8 minutes ago
Warning	FailedCreatePodSandBox	Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "04536dc07da4ca2138dcfde9865be1e828ff7a19d35616114edf2eb68a320aed" network for pod "cattle-node-agent-windows-9dqcj": networkPlugin cni failed to set up pod "cattle-node-agent-windows-9dqcj_cattle-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.	8 minutes ago
Warning	FailedCreatePodSandBox	Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "fa62633f06f9ace5b7898c5be93509811ddadbeaf6ade496f4768230f8b650b3" network for pod "cattle-node-agent-windows-9dqcj": networkPlugin cni failed to set up pod "cattle-node-agent-windows-9dqcj_cattle-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.	9 minutes ago
Warning	FailedCreatePodSandBox	Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c044149398d417e0bfc1624a309c660c9db0216cf99cf333ad8b7c182766541c" network for pod "cattle-node-agent-windows-9dqcj": networkPlugin cni failed to set up pod "cattle-node-agent-windows-9dqcj_cattle-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.	9 minutes ago
Normal	Scheduled	Successfully assigned cattle-system/cattle-node-agent-windows-9dqcj to <MASKEDNODENAME>	Invalid date_

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  **v2.4.5**
--

- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal
- Kubernetes version (use `kubectl version`): 1.18.3

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
docker version
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by maxisam** [comment]
You should check this thread.
https://github.com/rancher/rancher/issues/27367

**Comment by khatrig** [comment]
> You should check this thread.
> https://github.com/rancher/rancher/issues/27367 

Decided not to go with rancher at this time.
