### ISSUE TITLE
Remove GuestId Vsphere Clone Default

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#27968]
When creating a vsphere node from cloning the guest id (os type) is defaulted to "otherLinux64Guest" instead of inheriting from the VM/Template that was cloned from causing some warnings.

**Comment by luthermonson** [comment]
@yankcrime fyi

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4-head b7ab53e95
rancher/rancher:master-head b91cabfbb

* Reproduced in v2.4.5
* Create a cluster from node template (clone existing machine - used an Ubuntu machine)
* After cluster is created, check node in vCenter: Edit settings > VM Options > General Options > Guest OS & Version
* Guest OS is `Other Linux 64-bit`
--
* Install v2.4-head/master-head
* Create a cluster from node template (clone existing - same machine as previous steps)
* Guest OS is `Ubuntu Linux 64-bit`
