### ISSUE TITLE
The ""Rancher logging target setting validated" log message is not seen in fluentd server after clicking test

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#27969]
**What kind of request is this:**
bug

**Steps to reproduce:**

This is only happening for me in `master-head`.
`v2.4-head (07/16/2020)` _e28427e4a_ I get the message properly in the fluentd server.

- Create cluster either RKE or import k3s
- Navigate to Tools -> Logging -> Fluentd
- Add the required settings in the fields and hit TEST

**Result:**

The button will be turn Green with `Settings validated` message,
But if we look at the logs in the fluentd server there won't be settings validated message.

Like:
`rancher: {"message":"Rancher logging target setting validated"}`

Clicking then Save after some time I see the logs flowing to the target server. So the settings worked.

**Comment by cbron** [comment]
Moving this to 2.4.7, shouldn't be in 2.5 as this is a 2.4.x bug.
Is this similar to https://github.com/rancher/rancher/issues/26543 ?

**Comment by izaac** [comment]
This is different because the message is in the fluentd target server logs. 
In the dry run issue the fluentd target server returns a 500 iirc but the Rancher UI shows "settings are ok"

**Comment by izaac** [comment]
Fluentd target configuration

`fluentd:v1.7.4-debian-2.0`

```
<source>
  @type forward
  port 9881
  bind 0.0.0.0
</source>
<match **>
  @type stdout
</match>
```

**Comment by izaac** [comment]
Logging V1 is no longer supported
