### ISSUE TITLE
make volume delete work properly

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#2796]
Issues with it:
- delete in context of shared storage pool just doesn't make sense yet
- should prevent delete of volume if there are active container mounts to it because the delete will fail in docker
- when we remove a container in python-agent, we currently set `v=True`, which is the equivalent of `docker rm -v`, which causes all volumes, even named ones to be deleted. @ibuildthecloud is going to put an issue in with docker because we think that named volumes should not get deleted in this scenario, but we need to address this in rancher more quickly as part of this issue.
  - The good news is that since the volume is not deleted from convoy or rancher, when you create a new container or service using that volume, it reuses the existing volume in both convoy and rancher and no data or rancher associations are lost.

**Comment by cjellick** [comment]
My proposal for volume delete:

First, we should have API validation and process logic that prevents a volume from being deleted if it has active container mounts.

Second, we should make convoy-agent handle storage.instance.* events for shared storage pools. We can do this by setting the agentId in the storage pool when convoy-agent sends a ExternalStoragePool create event. More details on the functionality:
- We might just NO-OP all events other than storage.instance.delete, since we don't need the functionality for any of the other events.
- When we receive the delete event, we should do a `convoy delete` (as opposed to a `docker volume rm`). Since we've already ensured via our validation and process logic that there are no container mounts to this volume, it should be safe to delete.

Third, we should re-enable the ExternalVolumeDeleteEvents in cattle, but change the behavior on the convoy/convoy-agent side such that it only sends the event when the volume is REALLY deleted from convoy (vs the current behavior where it sends an event when a convoy backed volume is removed from docker).

Fourth (work in progress): we should change python-agent so that it doesn't delete volumes when it deletes a container. This is pretty tricky because if we don't add this `-v` option, we run the risk of orphaning volumes, especially with older versions of docker, but we do have separate storage.volume.delete events that should theoretically clean everything up, so disabling should be ok. We'd just need to test thoroughly and experiment a bit.

**Comment by ibuildthecloud** [comment]
Deleting things is scary.

**Comment by cjellick** [comment]
Thanks for the input

**Comment by instcode** [comment]
I recently "Upgrade" a service that uses a share volume (created by Docker 1.9) and after the upgrading, the volume data is gone without a trace. It's lucky that this data is not important but I'm really scared of this feature.

**Comment by cjellick** [comment]
@cjellick testing email filter

**Comment by cloudnautique** [comment]
@cjellick ^

**Comment by cloudnautique** [comment]
testing

**Comment by sangeethah** [comment]
Tested with v0.56.0-rc1 and convoy-gluster version - v0.2 and convoy-nfs version - v0.2.

1. Deploy services with volumes and volumedriver  set to convoy-gluster/convoy-nfs
2. In "Storage pool" view , volume will show as being "active" with all container mount points listed.
Drop down menu will not show "Delete" option.
3. Delete the service that uses this volume.
4. In "Storage pool" view , volume will show as being "inactive" . 
Drop down menu will show "Delete" option now.Deleted container mount points are still listed which is tracked in #3378.
5. When volume is "Deleted"  , it get to "removed" state. At this point , it continues to be present in the glusterfs server/nfs server.
6. Wait for the volume to be purged (or purge the volume manually). At this point , volumes will physically get deleted from glusterfs server/nfs server.
7. When volumes are in "Deleted" state they can be restored and used by other services.

**Comment by cjellick** [comment]
Testing looks good @sangeethah. Thanks!

**Comment by bschwartz757** [comment]
Hello,

I tried out Rancher over the past week and it doesn't look it will be a good solution for me. I have a standard ubuntu 16.04 server on Digital Ocean, and I'm trying to completely remove rancher and docker; it took some digging on the internet to figure out how to do this, and I've finally got it whittled down but now I can't finish removing /var/lib/rancher and /var/lib/docker. Here are the outputs I get:

```sudo rm -rf rancher
rm: cannot remove 'rancher/volumes': Device or resource busy```

I read that using this command might help track down the running processes so they can be killed, but no dice:
```lsof +D ./
lsof: WARNING: can't stat() nsfs file system /run/docker/netns/c24324d8b667
      Output information may be incomplete.
lsof: WARNING: can't stat() nsfs file system /run/docker/netns/default
      Output information may be incomplete.
COMMAND   PID       USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
bash    16667 blakers757  cwd    DIR  253,1     4096 267276 .
lsof    27938 blakers757  cwd    DIR  253,1     4096 267276 .
lsof    27939 blakers757  cwd    DIR  253,1     4096 267276 .```

When I try to kill the processes by pid, it fails. 

docker ps shows no running containers:
```docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

when I try to remove /var/lib/docker, I get the following:
```sudo rm -rf /var/lib/docker
rm: cannot remove '/var/lib/docker/overlay': Device or resource busy
rm: cannot remove '/var/lib/docker/overlay2/5b04c89cac02bfebc6de9355808c905e149dd7cb2f324952750b49aa93393ef4/merged': Device or resource busy
rm: cannot remove '/var/lib/docker/overlay2/4a17da45150a3e24ecef6babb933872f9aa403f3a072d5d37aff3b71b9eb936a/merged': Device or resource busy```

whatever is running inside this `overlay2` folder seems to be to blame.

Just wondering if you all have any ideas, thanks.
