### ISSUE TITLE
CentOS 8  vSphere templates do not work with https://releases.rancher.com/install-docker/19.03.sh and presumably other docker install scripts based on testing

### ISSUE THREAD

**Issue by unresolvable** [rancher/rancher#27970]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Deploy K8s cluster from vanilla CentOS 8 vSphere Template using Rancher Node Templates

**Result:**

“Error creating machine: Error running provisioning: error installing docker:”

**Other details that may be helpful:**

I found 2 issues with the https://releases.rancher.com/install-docker/19.03.sh docker install script that don’t work with CentOS 8. (1.) Running “yum makecache fast” or “dnf makecache fast” fails since “fast” is not an option. i.e. - yum makecache: error: argument timer: invalid choice: ‘fast’ (choose from ‘timer’) (2.) docker-ce needs containerd.io either installed in the template or added to the install script. $sh_c “$pkg_manager install -y https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm”

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

Rancher 2.4.5 installed via Helm on K3OS v0.10.1 in vSphere 6.7
VMware ESXi, 6.7.0, 10302608
VMware vCenter Server Appliance
Version: 6.7.0.42100
Build number: 15505668

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
CentOS/RHEL 8 is tracked in https://github.com/rancher/rancher/issues/23045
