### ISSUE TITLE
Is it possible configure a pop up window or show a banner in Rancher? 

### ISSUE THREAD

**Issue by axiang99** [rancher/rancher#27971]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
Is it possible configure a pop up window or a banner to show an alert/notification after the user logins to Rancher? 
Our Rancher hosts a lot of users. We'd like to find a way to pass important message to all our users. Pop up/banner are what come to my mind. 
If you have any other suggestions to achieve this please let us know. 

Thank you so much.

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.4.5
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM
- Kubernetes version (use `kubectl version`):

```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.9

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9

```

**Comment by superseb** [comment]
This was made available in https://github.com/rancher/rancher/issues/25694
