### ISSUE TITLE
user.management.cattle.io not found

### ISSUE THREAD

**Issue by axyzxyz** [rancher/rancher#27972]
*Describe your issue here*
use rke 1.3.1 create the k8s and helm create rancher 2.45
the user unable fectch the user info
![image](https://user-images.githubusercontent.com/25541485/87751946-ca3a6a00-c831-11ea-8287-458f0f8d4fe6.png)
![image](https://user-images.githubusercontent.com/25541485/87752001-e5a57500-c831-11ea-99b8-0e4f07f160e6.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.5` UI: `v2.4.28` |
|Route|`undefined`|

**Comment by a09-capf** [comment]
I got same problem 

Component | Version
-- | --
Rancher | v2.4.5
User Interface | v2.4.28
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher43
