### ISSUE TITLE
[KEv2] Rancher eks-operator integration

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#27979]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

**Expected:**
The following should be possible through the Rancher API:

Can provision an EKS cluster with the following configurable options:
  * Logging- can have any or none of the following: audit, scheduler, authenticator, controllerManager, api
  * Private access- false/true
  * Public access- false/true
  * Public Access Sources- can be empty or contain cider block such as 0.0.0.0/16
  * Kubernetes Version- string version i.e. 1.15
  * Tags- a map of string/string
  * Amazon Credential Secret (cloud crendential)
  * Display Name- this should correspond to the desired name in EKS
  * Subnets and security groups- either both of these should be provided or neither. If neither they will be generated
  * Service Role- this is the role that EKS will use to communicate with other parts of AWS. If empty it will be generated
  * Region- this should control which region the EKS cluster is provisioned in
  * Imported- This should be false and will be covered below
  * Node groups- array of objects with the follow options
    * GPU- false/true
    * Node group Name- name of the nodegroup. Should be unique
    * Disk Size- size of EBS volume, int, can be empty
    * InstanceType- ec2 instance to use, i.e. t3.medium
    * Labels- map of string/string
    * Ec2 Ssh key- name of the key pair in amazon to use, can be left blank in which case remote access to nodes will be disabled
    * Source Security Groups- only needed if ec2 ssh key is provided, provides security group for remote access (ssh) to worker nodes
    * Desired Size- how many nodes cluster should have
    * Min size- min nodes (not relevant until cluster auto scaler is installed)
    * Max nodes- max nodes (note relevant until cluster auto scaler is installed)
    * Subnets-subnets of worker nodes. If none provided then cluster's subnets will be used.
    * Tags- a map of string/string
    * Version- kubernetes version of the worker node. If left blank worker nodes will automatically keep up with control-plane's kubernetes version. If not blank must initially be the same as control plane, then as control plane upgrade, node group will stay at its version until incremented.

Of the above fields, the following can be updated:
  * Logging
  * Private Access
  * Public Access
  * Public Access Source
  * Kubernetes Version
  * Tags
  * Amazon Credential Secret
  * Node groups- can be added or deleted, the follow fields can be updated on individual node groups
  * Version

Can import EKS clusters- must provide following fields:
  * Display Name- name of cluster in EKS to import
  * Region- region that the cluster is in
  * Amazon Credential Secret- cloud credential that has access to cluster
  * Imported - set to true

**Comment by sowmyav27** [comment]
**Validating on master-head - commit id: `6d6199121`**

- User is able to Create an EKS cluster form Rancher
- And user is able to import an eks cluster into rancher.
- Issues found during testing this feature are being tracked separately.
- Closing this issue.
