### ISSUE TITLE
Monitoring v2 - deleting the app causes cluster unhealthy 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#27980]
**What kind of request is this (question/bug/enhancement/feature request):**
bug, maybe related to the monitoring app

on `rancher:master-3301-head` single install

Steps:
- provision a cluster with DO nodes
- add the new catalog for monitoring v2
- deploy the app `rancher-monitoring-v2`
- after a while, the app shows `catalog template not found`, and the app’s detail page shows
```
Wait helm get notes failed. E0717 18:40:56.078107 19203 request.go:975] Unexpected error when reading response body: unexpected EOF Error: query: failed to query with labels: unexpected error when reading response body. Please retry. Original error: unexpected EOF : exit status 1
```

<img width="772" alt="Screen Shot 2020-07-17 at 1 33 55 PM" src="https://user-images.githubusercontent.com/6218999/87834495-6f0f7400-c83f-11ea-907d-2e0ff3875dba.png">

- this is caused by a change on the chart’s repo
- fix the chart, and the missing template error is gone, but the `Wait helm get notes failed.` still exist
- update the app, the  `Wait helm get notes failed.` still exist
- delete the app

Results:
- the cluster goes to unavailable, showing the health check fails on the control plane node
- the following 4 containers on the control plane node are restarting
```
- k8s_cluster-register_cattle-cluster-agent-6978db69cf-6222d_cattle-system_b1bf9f97-207b-4e02-b06c-3c99ebf9c9cc_4
- k8s_node-exporter_rancher-monitoring-v2-prometheus-node-exporter-2r2sl_rancher-monitoring-v2_d827c0fd-560a-406c-9d68-c98ecd48330a_5
- kube-scheduler
- kube-controller-manager
```

- after a while, the cluster is back to active
- the app `rancher-monitoring-v2`  is gone, but its deployments are all left
- Rancher logs show this
```
2020/07/17 20:54:56 [ERROR] error getting app rancher-monitoring-v2 apps.project.cattle.io "p-zwz95/rancher-monitoring-v2" not found
```

The app is gone:
<img width="1427" alt="Screen Shot 2020-07-17 at 3 08 29 PM" src="https://user-images.githubusercontent.com/6218999/87834508-78004580-c83f-11ea-95e2-1cdbb3366808.png">

But all workloads are left
<img width="1460" alt="Screen Shot 2020-07-17 at 2 00 01 PM" src="https://user-images.githubusercontent.com/6218999/87834524-7e8ebd00-c83f-11ea-8709-59bd2d3a3b7a.png">

More info:

- the helm command shows the app still exists
```
 helm list -A
NAME                 	NAMESPACE            	REVISION	UPDATED                                	STATUS  	CHART                       	APP VERSION
rancher-monitoring-v2	rancher-monitoring-v2	9       	2020-07-17 20:39:30.622996411 +0000 UTC	deployed	rancher-monitoring-v2-8.16.1	0.38.1
```

**Comment by aiyengar2** [comment]
No longer see this issue on the latest version of the monitoring chart. Closing it for now.
