### ISSUE TITLE
Add cloudscale.ch driver

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#27989]
Add cloudscale.ch driver

**Comment by aaronRancher** [comment]
The feature is verified with Rancher server `rancher\rancher:master-head` `version master-3385-head`

After enabling cloudscale in `Node Drivers`:
![Screen Shot 2020-08-03 at 5 58 12 PM](https://user-images.githubusercontent.com/57409052/89241171-ffc1b000-d5b2-11ea-9b13-96064457048c.png)

Able to deploy a cluster, scale up and down nodes, and deploy workloads:
![Screen Shot 2020-08-03 at 5 56 30 PM](https://user-images.githubusercontent.com/57409052/89241098-d0ab3e80-d5b2-11ea-8bb6-374021d0e83f.png)
