### ISSUE TITLE
Load Balancer (ELB) Configuration with web socket error

### ISSUE THREAD

**Issue by conorcurlett** [rancher/rancher#2799]
We're attempting to configure an HA Rancher environment in AWS, and we're receiving web socket errors when introducing an ELB into the configuration. 
Rancher agents are dying when adding hosts to the server, reporting

"INFO: Sending host-config applied 1-c96901873d427a0a1c167ce7d0efc305cc684a93e7094b3f956bc46a6a046e97
2015-11-24 06:27:42,291 ERROR root [140166755790928] [_logging.py:54] error from callback <function on_error at 0x7f7b1db06140>: ('Received websocket error: [%s]', WebSocketBadStatusException('Handshake status 200',)) " 

The error is about websockets and ELBs do not support them. However with ProxyPass and HTTPS/SSL enabled they should over Layer 7. 

We followed the documentation from AWS on enabled Proxy Protocol here -> http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html#enable-proxy-protocol-cli  

Are ELBs correctly supported or would you recommend using a different NLB?

Our ELB config is as follows:

 "LoadBalancerDescriptions": [
        {
            "Subnets": [
                "subnet-041e4973",
                "subnet-c9a8c790",
                "subnet-db5564be"
            ],
            "CanonicalHostedZoneNameID": "Z33MTJ483KN6FU",
            "CanonicalHostedZoneName": "elb-rancher-cluster-01-487383446.us-west-2.elb.amazonaws.com",
            "ListenerDescriptions": [
                {
                    "Listener": {
                        "InstancePort": 9999,
                        "LoadBalancerPort": 9999,
                        "Protocol": "HTTP",
                        "InstanceProtocol": "HTTP"
                    },
                    "PolicyNames": []
                },
                {
                    "Listener": {
                        "InstancePort": 80,
                        "LoadBalancerPort": 80,
                        "Protocol": "HTTP",
                        "InstanceProtocol": "HTTP"
                    },
                    "PolicyNames": []
                },
                {
                    "Listener": {
                        "InstancePort": 443,
                        "SSLCertificateId": "arn:aws:iam::481678273598:server-certificate/cluster-cert",
                        "LoadBalancerPort": 443,
                        "Protocol": "HTTPS",
                        "InstanceProtocol": "HTTP"
                    },
                    "PolicyNames": [
                        "ELBSecurityPolicy-2015-05"
                    ]
                }
            ],
            "HealthCheck": {
                "HealthyThreshold": 10,
                "Interval": 30,
                "Target": "TCP:22",
                "Timeout": 5,
                "UnhealthyThreshold": 2
            },
            "VPCId": "vpc-790c2e1f",
            "BackendServerDescriptions": [
                {
                    "InstancePort": 80,
                    "PolicyNames": [
                        "rancher-ProxyProtocol-policy"
                    ]
                },
                {
                    "InstancePort": 443,
                    "PolicyNames": [
                        "rancher-ProxyProtocol-policy"
                    ]
                },
                {
                    "InstancePort": 9999,
                    "PolicyNames": [
                        "rancher-ProxyProtocol-policy"
                    ]
                }
            ],
            "Instances": [
                {
                    "InstanceId": "i-5048b98a"
                }
            ],
            "DNSName": "elb-rancher-cluster-01-487383441.us-west-2.elb.amazonaws.com",
            "SecurityGroups": [
                "sg-88d088ec",
                "sg-955e02f1"
            ],
            "Policies": {
                "LBCookieStickinessPolicies": [],
                "AppCookieStickinessPolicies": [],
                "OtherPolicies": [
                    "rancher-ProxyProtocol-policy",
                    "ELBSecurityPolicy-2015-05"
                ]
            },
            "LoadBalancerName": "elb-rancher-cluster-01",
            "CreatedTime": "2015-11-19T23:05:24.060Z",
            "AvailabilityZones": [
                "us-west-2a",
                "us-west-2b",
                "us-west-2c"
            ],
            "Scheme": "internet-facing",
            "SourceSecurityGroup": {
                "OwnerAlias": "488678872569",
                "GroupName": "rancher-cluster"
            }
        }
    ]
}

]

**Comment by vincent99** [comment]
ELB needs to be configured as a TCP listener (+TLS if desired) on the frontend and TCP on the backend, plus proxy protocol.  They do not support WebSockets in HTTP mode, and Rancher needs the info from proxy protocol to generate the correct URLs in API responses.

**Comment by deniseschannon** [comment]
@conorcurlett I am going to close as we indicate in our docs what is supported for ELB. http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/#running-rancher-server-behind-an-elb-in-aws-with-ssl

**Comment by tuwid** [comment]
@deniseschannon link's not working, can you update the reference, please ?
