### ISSUE TITLE
Enhancement: Rancher warning log when CATTLE_NAMESPACE is not set to cattle-system

### ISSUE THREAD

**Issue by chrisreed87** [rancher/rancher#27992]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

There are sporadic networking/peering issues with downstream cattle-cluster-agents and cattle-node-agents when the environment variable `CATTLE_NAMESPACE` for the Rancher deployment is not set to `cattle-system`. It is set correctly by default but can be overridden by the end-user. Specifically have seen where if not set correct, downstream K8s upgrades will not kick-off, the job will not be sent to the cattle-cluster-agent until fixed.

Everything will mostly work fine though if not set to `cattle-system` - so perhaps a logging enhancement is needed to clearly state that `CATTLE_NAMESPACE` is not `cattle-system` as a warning or error log and prompts user to fix.

**Comment by vincent99** [comment]
If that's the only working value, why is it a variable?  It seems silly to ask and then warn if you choose anything else; it should either work or be hardcoded.

**Comment by chrisreed87** [comment]
@vincent99 - agreed. The env var seems to populate from the namespace you deploy the Rancher pods in; while the docs specify that it needs to be deployed in cattle-system, a user can override it. If there's a safe way to prevent that, I think it's the better move. Or, yes to your point, make it work regardless of which namespace it lands in
