### ISSUE TITLE
Password with a colon fails auth

### ISSUE THREAD

**Issue by DamienMure** [rancher/rancher#2800]
Hi.
A user using a colon ":" in his password is not able to log on rancher.
He directly get the "Fordidden" message on the loggin screen.
The "POST" request sent on "/v1/token" get the "403 OK" status code.

Changing the password in ldap make the auth process to work...

Regards
Damien

My configuration:
Rancher	v0.46.0
Cattle	v0.112.0
User Interface	v0.65.0
Rancher Compose	v0.5.2

**Comment by deniseschannon** [comment]
Can you provide more details from the rancher server logs on the exact ldap error when trying to authenticate with the user credentials?

@hibooboo2 Can you look into this?

**Comment by hibooboo2** [comment]
Yes looking into it right now.

**Comment by hibooboo2** [comment]
Submitted a pr to fix this.

**Comment by DamienMure** [comment]
Hi.
Thank you for the fix.
I had a look at your commit, this will solve my issue...
I hope I'll never have a login with colon in it (really unusual, but customers are always imaginative).

Best Regards.

**Comment by deniseschannon** [comment]
Thanks for closing @DamienMure, but we like to test our fixes to be sure it works in a Rancher build

**Comment by sangeethah** [comment]
Tested with v0.49.0-rc1.

When ldap user has ":" is his password , we are able to log in successfully by providing the correct password.
