### ISSUE TITLE
[CLI] - Map values are incorrectly when installing apps with values file. 

### ISSUE THREAD

**Issue by hwchiu** [rancher/rancher#28000]
**What kind of request is this (question/bug/enhancement/feature request):**
[bug]

Try to install the app with Helm values file from the CLI and the data type (list of the map) isn't included in the final yaml. 
I checked another type (string) and it works well.

**Steps to reproduce (least amount of steps as possible):**
- Install the catalog with [my testing repo](https://github.com/hwchiu/rancher-test-repo)
  - branch: master
  - scope: cluster
  - helm: v2
- Prepare customized values.yaml
```yaml
tolerations:
  - key: rancher-test
    value: testing-site
    effect: NoSchedule
```
- Install the apps with the above values file
```yaml
rancher apps install --values values.yaml --namespace default c-8t9dc:hwchiu-test hwchiu
```
- check the deployment yaml and tolerations are not included in it. 
```
- kubectl get deployment -o yaml
```

**Result:**
The tolerations should be deployment yaml if you use the native Helm way to install it. 

**Other details that may be helpful:**
I try the other two approaches to install the app with the correct result.
1. Install the App from the UI by using `Edit as YAML -> Read from File`, the tolerations are included.
2. Manually convert the customized values yaml to answer compatible format and then install with `rancher app install -a xxxxxx` 
```
tolerations[0].key: rancher-test
tolerations[0].value: testing-site
tolerations[0].effect: NoSchedule
```

But I still want to install the app with the original values file, not the answer format.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
  - Rancher | v2.4.5
  - User Interface | v2.4.28
  - Helm | v2.16.8-rancher1
  - Machine | v0.15.0-rancher43

- Installation option (single install/HA):
  - HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
> Infrastructure Provider (AWS)
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
> VM, large, 2C4G
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Rancher CLI version (use `docker version`):
```
$ rancher --version                                                                                                                                                    3 ↵
rancher version v2.4.5
```

gzrancher/rancher#11512

**Comment by Sadzeih** [comment]
I have the same issue with the `v2.4.6-rc2` release.

**Comment by Sadzeih** [comment]
Any news on this bug? I'd really like to use the rancher cli in my CD pipelines but with this bug it makes it impossible.

**Comment by Rancheroo** [comment]
I can see the same issue using a values file (link to file below) that works with a helm install command
```# helm values source: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml```
```helm install --debug argo-cd argo/argo-cd -n argo-cd --version 2.5.4 -f ./myvalues.yaml```
This works great and installs the chart with the updates values in this case
```server.config.application.instanceLabelKey: rad.com/modval```

However when using that rancher cli 2.4.5
I can see the values are passed into the aswers.yaml, however does not overwite the vlaues as suggested in this document.
I was expecting these values to used as stated in the below document.
https://github.com/rancher/rancher/wiki/Understanding-How-Rancher-Configures-Helm-Charts#ranchers-helm-controller

> For every key-value pair in answers. rancher feeds --set key=value. For valuesYaml, rancher downloads the content into an actual file and sends feeds it to helm using -f.

![image](https://user-images.githubusercontent.com/56899019/91824081-8a163600-ec7d-11ea-979a-aea99369261a.png)

![image](https://user-images.githubusercontent.com/56899019/91824135-a1edba00-ec7d-11ea-8ccb-c17bb45e6087.png)

**Comment by mgaruccio** [comment]
Any Progress on getting this resolved?  this is causing major issues for our dev teams CI/CD pipeline work.

**Comment by theAkito** [comment]
It seems like we are encountering this issue too, except we **cannot** ignore it, because it breaks our app completely. This is a huge issue, that can only be avoided by making a big workaround and putting a lot of effort in the avoidance.
Additionally, this happens when deploying a Rancher App with a `questions.yaml` through the Rancher UI.

The map seems to be (partially) missing, even though debugging the Helm Chart with Helm tools locally renders the map perfectly fine. Only Rancher is not able to process the map correctly.

**Comment by maggieliu** [comment]
related to: https://github.com/rancher/rancher/issues/27841

**Comment by toddexp** [comment]
Digging a little further into the issue I found that this a bug that was introduced between cli versions 2.3.2 and 2.4.5.

As stated it appears that the rancher cli is treating values.yaml files as answers.yaml files by mistake. If you use the cli to apply a values.yaml and then click upgrade on the app in the ui then you will see instead of the values.yaml being displayed there, the answers.yaml is.

I tested this with old apps we had installed on the cli on version 2.3.2 that treated the values.yaml properly, then installed it again with version 2.4.5 and it was converted to answers.yaml.

**Comment by jiaqiluo** [comment]
The bugfix is validated in rancher: `v2.4-3950-head` and rancher CLI `v2.4.7-rc1`
```
> ./rancher -v
rancher version v2.4.7-rc1
```



steps:
- add the repo in the issue to Rancher 
```
https://github.com/hwchiu/rancher-test-repo
master
```
![image](https://user-images.githubusercontent.com/6218999/96059119-f0c46d00-0e41-11eb-9dd8-de5a19f4506f.png)

- create the following `value.yaml` file
```
image: hwchiu/netutils
tag: latest
registry: docker.io

tolerations:
  - key: rancher-test
    value: testing-site
    effect: NoSchedule
```
- install the app via Rancher CLI
```
> ./rancher apps install --values ./values.yaml test  --no-prompt
run "app show-notes a-zcq9t" to view app notes once app is ready
```
- see the app is installed and the toleration is applied at both the app and the deployment level  

![image](https://user-images.githubusercontent.com/6218999/96059262-4f89e680-0e42-11eb-97bf-c3cb946f34f6.png)
<img width="1348" alt="Screen Shot 2020-10-14 at 5 19 50 PM" src="https://user-images.githubusercontent.com/6218999/96059284-5b75a880-0e42-11eb-9bfa-61e9799327d2.png">


Note:
The following format is NOT supported by the CLI tool 
```
image: hwchiu/netutils
tag: latest
registry: docker.io

tolerations[0].key: rancher-test
tolerations[0].value: testing-site
tolerations[0].effect: NoSchedule
```
