### ISSUE TITLE
Rancher cli apps install bug

### ISSUE THREAD

**Issue by aldmbmtl** [rancher/rancher#28003]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug/Question

**Steps to reproduce (least amount of steps as possible):**
Step 1:
Set up custom catalog pointing to private gitlab.

Step 2: 
Install rancher cli off of my rancher server at the bottom right of the interface.

Step 3:
Log into rancher with my bearer token provided from my user. I am an admin and full access.

Step 4:
Run the following command. Troll is an app on my home cluster that I use for testing. I can't share the output from my office sadly. But I get the same result here at home as I do at work.
```
> rancher apps install troll
FATA[0049] Bad response statusCode [404]. Status [404 Not Found]. Body: [code=NotFound, message=failed to find resource by id, baseType=error] from [https://MY-SERVER/v3/project/c-nmbh7:p-xdjfb/apps]

> rancher apps ls
p-xdjfb:crank             crank             active    p-xdjfb/playground   minecraft         0.1
p-xdjfb:guard-gate        guard-gate        active    p-xdjfb/playground   guard-gate        v0.1
p-xdjfb:jenkins           jenkins           active    p-xdjfb/playground   jenkins           v0.1
p-xdjfb:rpi-owncloud      rpi-owncloud      active    p-xdjfb/playground   rpi-owncloud      0.1
p-xdjfb:rpi-tranquility   rpi-tranquility   active    p-xdjfb/playground   rpi-tranquility   0.1
p-xdjfb:shank             shank             active    p-xdjfb/playground   minecraft         0.1

> rancher apps list-templates
p-xdjfb:playground-guard-gate                            guard-gate                          
p-xdjfb:playground-jenkins                                  jenkins                             
p-xdjfb:playground-minecraft                              minecraft                           
p-xdjfb:playground-rpi-owncloud                         rpi-owncloud                        
p-xdjfb:playground-rpi-tranquility                         rpi-tranquility                     
p-xdjfb:playground-troll                                        troll
```

**Other details that may be helpful:**
I can launch the app through the UI perfectly fine. But we are looking to add auto deployment to our CI at work which would be using the cli to trigger an app install/upgrade from a CI worker. We were going to use the rancher CI, but we have some projects running on ARM which the rancher CI does not seem to support sadly. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.5
- Installation option (single install/HA):
Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Imported K3s
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Metal/VM mix
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.8-beta.0", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"archive", BuildDate:"2020-01-29T00:00:00Z", GoVersion:"go1.14beta1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

p.s. Absolutely love your product! Been using rancher professionally for the last year in the VFX industry and has been awesome. This is my very first "bug" which I am sure I am just doing something dumb. 

Thanks!

**Comment by flrichar** [comment]
@aldmbmtl what is the output if you include the catalog-id? 
example:
 `rancher install app some-chart-catalog:playground-troll`
