### ISSUE TITLE
Add Member button is disabled for Cluster Owner which is an Standard User

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28005]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install Rancher
- Create three Standard Users with the local admin
- Logout from the admin account and login as the one of the Standard Users account
- Create a cluster (I used an RKE DO)
- Once the cluster is created click Edit -> Member Roles

**Result:**

![Screen Shot 2020-07-21 at 11 19 04 AM](https://user-images.githubusercontent.com/27659/88093799-640e5980-cb47-11ea-94b7-2a6458194978.png)

**Other details that may be helpful:**

If I navigate to Cluster -> Members I can add users to the cluster in that page.
~~Reproducible in `v2.4.5`~~

**Environment information**
- Rancher version: `master-head (07/21/2020)` c289ff7de
- Installation option: single and HA

**Cluster information**
- Cluster type: Infrastructure Provider - RKE DO
- Machine type: VM
- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sowmyav27** [comment]
**On 2.4.5 and on 2.4-head commit id: `b7ab53e95`**

- Create a DO/custom cluster as a standard user - user1
- Click on edit cluster --> Members --> "Add Member" button is enabled. User1 is able to add members and save.

**Comment by izaac** [comment]
Reproducible in `master-head (07/24/2020)` _80542c31b_ single install.

**Comment by westlywright** [comment]
Not sure if this is a UI issue or not. The code where all of this logic resides has not been updated since late 2019 (in master and dev2-4) so if it was a UI issue I would suspect this would also be reproducible in 2.4.5 at least.

**Comment by westlywright** [comment]
When logged in as a standard user the `/v3/users` call only returns the currently logged in user. If you log back in as the admin and give that standard user who created the cluster `Manage Users` permissions you can then add members to the cluster. This seems correct to me but either way it doesn't appear to be a UI issue.

**Comment by mrajashree** [comment]
I don't see this work in 2.4.5 either.
Adding members works when tried from the Members page, because on that page the search box is always enabled and UI makes search principals API call.
But on edit cluster, it looks like only users with "Manage Users" permission can add the users (same as what @westlywright said)
<img width="1431" alt="Screen Shot 2020-09-23 at 3 37 53 PM" src="https://user-images.githubusercontent.com/10672776/94080838-bc660f80-fdb3-11ea-9605-5279dbd7de02.png">

**Comment by maggieliu** [comment]
@izaac @sowmyav27 Can you confirm it's not a blocker anymore if we can reproduce it in 2.4? After removing the blocker label i will move this out of 2.5

**Comment by sowmyav27** [comment]
Original issue mentioned [here](https://github.com/rancher/rancher/issues/28005#issue-663230930) is also seen on 2.4.5.
