### ISSUE TITLE
Import for EKS/RKE2/K3S should be "register"

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28007]
Import has a definition of register-but-not-operate, whereas the new distros/cloud provider is more register-and-operate. This is why we need to make a 5th way of adding cluster call "Register" or something different. 

We need a new box for register.

**Comment by lvuch** [comment]
![create-cluster](https://user-images.githubusercontent.com/3013118/88593662-bd2d3000-d014-11ea-91a3-429ac2c2461e.png)

**Comment by deniseschannon** [comment]
Description text:

Register:
```
Register an existing Rancher, k3s or EKS cluster. 
```

Import: 
```
Import an existing CNCF certified Kubernetes cluster. Kubernetes configuration and infrastructure management is managed outside of Rancher. 
```

**Comment by deniseschannon** [comment]
On the register page:
Option 1:
Title: `Rancher or k3s`
Description: `Register an existing Rancher or k3s backed clusters.`
Option 2:
Title: `Amazon EKS`
Description: `Register an existing Amazon EKS cluster`

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `6d6199121` ui tag: `latest2`**

Login as standard user --> Add cluster
<img width="1362" alt="Screen Shot 2020-07-29 at 7 30 21 PM" src="https://user-images.githubusercontent.com/26032343/88873722-28703100-d1d2-11ea-8a01-e407eb8dc94b.png">
<img width="1342" alt="Screen Shot 2020-07-29 at 7 30 48 PM" src="https://user-images.githubusercontent.com/26032343/88873723-2a39f480-d1d2-11ea-9a61-a06216027289.png">
