### ISSUE TITLE
`docker` in image name results in weird behaviour

### ISSUE THREAD

**Issue by mishak87** [rancher/rancher#2801]
rancher-compose 0.5.2
rancher-ui 0.65.0
rancher 0.46.0

Launched via `rancher-compose`:
`docker-compose.yml`

``` yml
dind:
    image: docker:1.9-dind
```

UI reports

``` yml
dind:
    image: 1.9-dind
```

API

``` json
"imageUuid": "docker:1.9-dind",
```

UI shows reactivating/removed and after few seconds it shows purged. 
I have tried to manually run the container on host without issues.

EDIT: tagging and using under different name `a.b.cz/vendor/docker:1.9-dind` works.

**Comment by deniseschannon** [comment]
@hibooboo2 Could you see if this a docker-py issue or is it a Rancher issue?

**Comment by hibooboo2** [comment]
Rancher issue for sure.

**Comment by prachidamle** [comment]
@will-chan moving to 1.1 as discussed

**Comment by patrickbusch** [comment]
if using a private registry, a workaround is to retag the image and upload to the private registry. works fine for me

**Comment by nunofgs** [comment]
Just hit this issue as well. The [docker dind](https://hub.docker.com/_/docker/) images are essentially unusable in Rancher.

**Comment by akhy** [comment]
@nunofgs essentially any `docker:*` images. Temporary solution is by retagging to private registry as @patrickbusch said.

**Comment by StrongMonkey** [comment]
It is a legacy issue because we always append `docker:` to our image names and that has caused a lot of problems in parsing the image names. A workaround would be, append an extra `docker:` for all the docker images, for example, if you want to use `docker:1.12`, use `docker:docker:1.12` as your image name instead.

**Comment by disaster37** [comment]
You can use the long name to pull docker image, aka `index.docker.io/docker:dind`

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
