### ISSUE TITLE
[Backport 2.3] Update Minio

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28025]
backport for: https://github.com/rancher/rancher/issues/27467

Update Minio Image to the latest: RELEASE.2020-07-13T18-09-56Z
https://github.com/minio/minio/releases/tag/RELEASE.2020-07-13T18-09-56Z

No need to update the minio go.

**Comment by soumyalj** [comment]
Tested with v2.3-head(c2b599869). 
Minio image was updated to the latest rancher/minio-minio:RELEASE.2020-07-13T18-09-56Z.
This was observed by enabling and running the default pipeline in rancher. 

The minio container fails to come up sometimes with a crashloop error:

![Screen Shot 2020-07-24 at 4 49 11 PM](https://user-images.githubusercontent.com/18536626/88443575-ac3ead80-cdcd-11ea-8f76-3087f0e53edb.png)

It may get to active state for few seconds , but gets to crashloop backoff state again

**Comment by soumyalj** [comment]
Tested with Rancher version v2.3-head (0585677d3)

- Minio image verification

Enable and run the default pipeline `rancher/pipeline-example-go` in Rancher. 
Minio image was updated to the latest rancher/minio-minio:RELEASE.2020-07-13T18-09-56Z
Minio workload came up successfully. No crashloop backoff errors observed. 

![Screen Shot 2020-08-03 at 2 46 48 PM](https://user-images.githubusercontent.com/18536626/89230457-2f16f380-d598-11ea-84ef-e0e13fa8d74d.png)

- Re-verified that etcd backup/restore using minio target was functional

Steps:
1. Create a DO cluster with backup/restore configured to minio as a standard user
2. Create few workloads. Perform a backup snp1. Create another workload.
3. Perform restore to snp1, 

Restore was successful.

**Comment by soumyalj** [comment]
Tested with Rancher version v2.3-head (436bd83ed)

- Minio image verification

Enable and run the default pipeline `rancher/pipeline-example-go` in Rancher. 
Minio image was updated to the latest rancher/minio-minio:RELEASE.2020-07-13T18-09-56Z
Minio workload came up successfully. No crashloop backoff errors observed. 

![Screen Shot 2020-08-03 at 5 00 46 PM](https://user-images.githubusercontent.com/18536626/89238424-e6b50100-d5aa-11ea-9212-0359456de32a.png)



- Re-verified that etcd backup/restore using minio target was functional

Steps:
1. Create a DO cluster with backup/restore configured to minio as a standard user
2. Create few workloads. Perform a backup snp1. Create another workload.
3. Perform restore to snp1, 

Restore was successful. 

- Verified that the memory limit for minio deployment was updated to 500M

![Screen Shot 2020-08-03 at 5 09 41 PM](https://user-images.githubusercontent.com/18536626/89238795-26c8b380-d5ac-11ea-8228-1b9b3eb54433.png)


![Screen Shot 2020-08-03 at 5 00 32 PM](https://user-images.githubusercontent.com/18536626/89238818-3a741a00-d5ac-11ea-9dd0-ff602277a8da.png)
