### ISSUE TITLE
cis 1.4 when run from API UI on a cluster, throws an error

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28024]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Run a security scan from API UI and give in overridebenchmarkversion as `cis-1.4`
- The scan is run but an error is seen

`time="2020-07-20T22:11:39Z" level=info msg="Running Summarizer" time="2020-07-20T22:11:39Z" level=debug msg="version_mapping: map[rke-1.17:rke-cis-1.5 rke-1.18:rke-cis-1.5 rke-1.13:rke-cis-1.4 rke-1.14:rke-cis-1.4 rke-1.15:rke-cis-1.5 rke-1.16:rke-cis-1.5]" time="2020-07-20T22:11:39Z" level=debug msg="filePath: /etc/kube-bench/cfg/cis-1.4/master.yaml, controls: &{ID:1 Version:1.13 Text:Master Node Security Configuration Type:master Groups:[0xc000063140 0xc0000631a0 0xc000063200 0xc000063260 0xc0000632c0 0xc000063320 0xc000063380] Summary:{Pass:0 Fail:0 Warn:0 Info:0}}" time="2020-07-20T22:11:39Z" level=error msg="error loading controls from file /etc/kube-bench/cfg/cis-1.4/etcd.yaml: error reading file /etc/kube-bench/cfg/cis-1.4/etcd.yaml: open /etc/kube-bench/cfg/cis-1.4/etcd.yaml: no such file or directory" time="2020-07-20T22:11:39Z" level=debug msg="filePath: /etc/kube-bench/cfg/cis-1.4/node.yaml, controls: &{ID:2 Version:1.13 Text:Worker Node Security Configuration Type:node Groups:[0xc000063560 0xc0000635c0] Summary:{Pass:0 Fail:0 Warn:0 Info:0}}" time="2020-07-20T22:11:39Z" level=debug msg="filePath: /etc/kube-bench/cfg/cis-1.4/config.yaml, controls: &{ID: Version: Text: Type: Groups:[] Summary:{Pass:0 Fail:0 Warn:0 Info:0}}" time="2020-07-20T22:11:39Z" level=debug msg="total groups loaded: 9" time="2020-07-20T22:11:39Z" level=debug msg="total controls loaded: 98" time="2020-07-20T22:11:39Z" level=info msg=summarize time="2020-07-20T22:11:39Z" level=debug msg="inputDir: /tmp/kb-summarizer/input/plugins/rancher-kube-bench/results" time="2020-07-20T22:11:39Z" level=debug msg="hostDir: sowmya-test-1" time="2020-07-20T22:11:39Z" level=info msg="found error file" time="2020-07-20T22:11:39Z" level=fatal msg="error summarizing: \nThe specified --targets \"etcd\" does not apply to the CIS Benchmark cis-1.4 \\n Valid targets [master node]\n" error running kb-summarizer using override benchmark version`

**Expected Result:**
Error should not be seen. Report should be generated successfully

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO rke
- Kubernetes version (use `kubectl version`):

```
1.18.6
```

**Comment by prachidamle** [comment]
This issue has been present since the security-scan image tag 0.1.7 
https://github.com/rancher/system-charts/commit/549b489790d2f65199bdf7dadbc06b8c2b2ccad0#diff-70c84b0eb4e346b6df063668bbb2e379

It is reproducible in v2.4.3 or earlier.

It worked in rancher v2.4 but has been broken after.

**Comment by sowmyav27** [comment]
**Verified on 2.4-head  - commit id: `6708cf9f1`**

- User is able to run `cis-1.4` from the API ui when given as the `overridebenchmarkversion`. Report is generated.

**On master-head - commit id: `6d6199121`**
- `cis-1.4` does not work and gives error `level=fatal msg="error summarizing: \nThe specified --targets \"etcd\" does not apply to the CIS Benchmark cis-1.4 \\n Valid targets [master node]\n" error running kb-summarizer using override benchmark version`

**Comment by prachidamle** [comment]
Added the forward port PR to system-charts dev-v2.5: https://github.com/rancher/system-charts/pull/307

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `c53a66e22`**

- User is able to run cis-1.4 from the API ui when given as the overridebenchmarkversion. Report is generated.
