### ISSUE TITLE
Air-gapped K8s upgrade should be streamlined

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#28026]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
To upgrade k8s on an air-gapped cluster you need to first:

1. Pull the `data.json` metadata file
2. Setup local mirror and point Rancher to this location
3. Generate an image list from Rancher UI/API
4. Pull the images to the private repo

**Result:**
This means that the users have to affectively maintain a metadata mirror AND a private repo, but this seems like a lot of busy work for two files (`data.json` and `rancher-images.txt`) before you can even pull the needed images.  It would be very helpful to streamline this process.  Can we at least provide an updated `data.json` and `rancher-images.txt` in one place that is easily accessed for our air-gapped users?

gz#11294

**Comment by Crazyscorpio88** [comment]
Hello,

If I can UP this request, I opened an Issue for 1.1.14.
And I think the improvement is mandatory for Air-Gapped environments.

[https://github.com/rancher/rke/issues/2189](url)

Thanks,
