### ISSUE TITLE
Kubernetes componentstatuses Deprecation and Rancher Cluster Health Check

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#28023]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Kubernetes is working towards deprecating componentstatuses which now also doesn't work if the scheduler or controller-manager are running on the new default secure port. Rancher uses this client call to get the statues of the main components and shows it in the UI. I would recommend rancher move away from using componentstatuses and use a different mechanism of getting the main control-plane health such as prometheus or jobs. 

https://github.com/kubernetes/kubernetes/pull/93171 - 'fix component status server address' which is getting recommendation to close due to deprecation talk.
https://github.com/kubernetes/enhancements/issues/553 - Deprecate ComponentStatus
https://github.com/kubernetes/kubeadm/issues/2222 - kubeadm default init and they are looking to 'start printing a warning in kubect get componentstatus that this API object is no longer supported and there are plans to remove it.'

**Result:**
Moving away from using componentstatuses would fix issues with using the secure ports on control-plane components and issues when the managed cloud provider doesn't even show the status for components.  

**Other details that may be helpful:**

This could also help resolve the issue here: https://github.com/rancher/rancher/issues/11496

**Comment by superseb** [comment]
Is this currently broken (besides the clusters mentioned in #11496)? The way this is taken care of is that the version that removes this functionality will be validated and considered not functioning properly, where a fix/redesign will be created to make this work as part of the validation.

**Comment by mitchellmaler** [comment]
@superseb  We just upgraded our Kubeadm imported clusters to 1.17.9 which now has this problem. Upstream Kubernetes now defaults the scheduler and controller-manager to using the secure port but component states does not so it ends up being a similar issue to the AKS clusters. Now our Rancher UI shows these clusters as unhealthy always.

As a temporary "fix" could there be a way for Rancher to ignore these two cluster components and not use it to mark the cluster as unhealthy? Since component statues is not reliable we don't want Rancher to show it as unhealthy which in itself if a false positive.

**Comment by superseb** [comment]
Ok I renamed the issue to being clear that its no longer an upstream bug but a deprecation, although this was the same status it had at the k8s side at the point of filing it. The request for ignoring it has been done in the other issue as well, I will merge it with that (https://github.com/rancher/rancher/issues/11496), please emoji upvote that issue for visibility.

**Comment by dhawaldenny** [comment]
@superseb , @mitchellmaler , is there any way to disable this warnings in the ui?
`Controller Manager & Scheduler show as Unhealthy in clusters that have controller-manager and scheduler`

**Comment by mitchellmaler** [comment]
@dhawaldenny  I wish there was. In #11496 that has been mentioned as a request but there had not been any update on this issue.
