### ISSUE TITLE
Unable to enable/install cluster monitoring with 2.4.5

### ISSUE THREAD

**Issue by vitobotta** [rancher/rancher#28028]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug?

**Steps to reproduce (least amount of steps as possible):**
Fresh new RKE cluster deployed with the UI. Enabled cluster monitoring.

**Result:**
I would expect Grafana and Prometheus to be set up correctly, but the installation gets stuck and there is no sign of Prometheus, so Grafana cannot find the data source. In the Apps tab the cluster-monitoring app remains at "Installing". 
At first the operator was unable to create other resources and I had to patch a cluster role as per https://github.com/rancher/rancher/issues/26969. That allowed the operator to create some stuff, but not everything.

**Other details that may be helpful:**
Not sure it's relevant, but I have deployed the cluster in Hetzner Cloud using a node driver. I installed the Hetzner Cloud cloud controller manager and after that the node IP changed from internal to external, and the internal IP is now unset for the node.
This caused an issue with the metrics server which I fixed by setting `kubelet-preferred-address-types` to `ExternalIP`. I wonder if the issue I am having with the cluster monitoring could be related?

Thanks in advance for any help.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.4.5

- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
RKE deployed with Rancher UI

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Cloud, 4 cores / 8GB

- Kubernetes version (use `kubectl version`):
1.18.6

- Docker version (use `docker version`):
Installed by Rancher

**Comment by vitobotta** [comment]
I noticed this error when I go into the app:

```
Failed to install app cluster-monitoring. Error: UPGRADE FAILED: failed to create resource: Endpoints "expose-kube-cm-metrics" is invalid: [subsets[0].addresses[0].ip: Invalid value: "": must be a valid IP address, (e.g. 10.9.8.7), subsets[0].addresses[0].ip: Invalid value: "": must be a valid IP address]

```

So it's definitely because  of the missing internal IP. Is it possible to force it to use the external IP?

**Comment by mj520** [comment]
enable cluster monitoring with 2.4.5、 rancher agent sending large amounts of data to rancher server
and Unable to prohibit monitoring
