### ISSUE TITLE
It seems rancher os cannot be recovered from a rancher os stick

### ISSUE THREAD

**Issue by blaggacao** [rancher/rancher#2803]
After corrupting my cloud config yaml, I wanted to recover from the initial rancher os stick, with wich I infected the computer on the first hand. Aparently, the stick also reads the cloud_config file from disk, when in place and therefore fails.

Not 100% sure of this interpretation of what I see and not sure if it's intended.

**Comment by deniseschannon** [comment]
This sounds like a rancherOS issue and should be filed in rancher/os repo. 

https://github.com/rancher/os/issues

**Comment by ibuildthecloud** [comment]
@blaggacao You can boot rancheros with the kernel command line "rancher.state.dev=none".  That will prevent it from using the state partition.  You can then mount the state partition from the live system and recover.
