### ISSUE TITLE
Enable prometheus admin api on rancher monitoring

### ISSUE THREAD

**Issue by xentobias** [rancher/rancher#28036]
**What kind of request is this (question/bug/enhancement/feature request):**
bug?

**Steps to reproduce (least amount of steps as possible):**
Fresh new RKE cluster deployed with the UI. Enabled cluster monitoring.

**Result:**
I have no way to activate the admin api of prometheus monitoring. 
(https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-admin-apis)

I tried the following arguments (Rancher -> Monitoring -> Advanced Options):
`server.enableAdminApi`
`prometheus.enableAdminApi`

Thanks in advance for any help.

**Other details that may be helpful:**
The attempt to enter it directly into the deployment “prometheus-cluster-monitoring” as a start parameter (Command) has also failed. The changes are not accepted.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
`v2.4.5`
- Installation option (single install/HA):
`single install`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
`Infrastructure Provider: DigitalOcean`
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
`cloud: Shared CPU, 2 vCPUs, 4 GB RAM, 80 GB SSD`
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aleksey005** [comment]
Is it possible to provide API-access for PromQL queries?

**Comment by xentobias** [comment]
Yes, https://prometheus.io/docs/prometheus/latest/querying/api/
