### ISSUE TITLE
K8s Provider Detection Function

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28043]
Need a function to detect the k8s provider: DetectProvider(ctx, kubernetes.Interface) (string, error)
* Need a "IsProvider" function for each of the k8s providers we know of and are supporting. Returns true/false
  - Current provider list: RKE, K3s, RKE2, GKE, AKS, EKS, Minikube, KubeADM, Docker
* The high level wrapper function `DetectProvider` takes a list of providers and loops through all "IsProvider" functions to figure out which provider it is and returns a string to indicate the provider.

**Comment by dramich** [comment]
```
k3s/rke have it in the k8s version, eks, gke and aks might as well.
docker for desktop you can tell from the node OS and the fact it's one node.  minikube is one node and the hostname.
```

**Comment by dramich** [comment]
This is setup in a new repo https://github.com/rancher/provider-detector

**Comment by dramich** [comment]
Initial feedback that needs to be addressed: 
Finish out docker and minikube and drop kubeadm. 
Make the provider names public constants and then also have a public slice of all provider names. 
Make the library return a known err, like ErrUnknownProvider if no provider is detected instead of ("", nil).

**Comment by deniseschannon** [comment]
@prachidamle I've assigned this to you until CIS v2 is working by using this. When your feature is completed, can you move this to test and they can use the CIS v2 to test out detecting the different providers.

**Comment by deniseschannon** [comment]
UI is starting to use this so going to close it and if any issues are found, other tickets will be made.
