### ISSUE TITLE
Storage Pool is missing the newly added volume after the service is started

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2804]
v0.47.0-rc1

Steps to Reproduce:
1. Set up all the convoy stuff (aka, set up glusterfs from catalog, set up convoy-gluster)
2. Click on Storage Pools to see the hosts that have been allocated to the storage pool. Note there are no volumes yet.
3. Add a service using the new convoy-gluster volume driver
4. Click on Storage Pools

Result: The new volume isn't listed. When I refresh the page, it shows up.

Expected Result: The new volume to be listed when I go to the storage pool page.

**Comment by vincent99** [comment]
302 #2763
