### ISSUE TITLE
Metric Tracing Logging

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28042]
Better trace logging to help debug performance and scalability issues.

**Comment by dramich** [comment]
Trace logging for list calls was added to norman. Additional metrics still need to be added.

**Comment by sowmyav27** [comment]
**Verified on 2.4-head commit id: `f32f5d1d2`**

- Deploy rancher server
- Enable trace logging
- Create some clusters
- Rancher logs show

```
I0811 19:13:27.013543       6 trace.go:116] Trace[51146923]: "Proxy Store List" resource:clusters (started: 2020-08-11 19:13:26.770071348 +0000 UTC m=+9810.665178751) (total time: 243.415964ms):
Trace[51146923]: [214.650823ms] [214.650823ms] Completed List list-len:201
Trace[51146923]: [242.882003ms] [28.23118ms] Completed fromInternal
Trace[51146923]: [243.412754ms] [530.751µs] Completed FilterList
Trace[51146923]: [243.415964ms] [3.21µs] END
```

**Comment by sowmyav27** [comment]
Closing this issue - tracking the fix for master in here - https://github.com/rancher/rancher/issues/28489
