### ISSUE TITLE
Execute shell  disconnected v2.4.5

### ISSUE THREAD

**Issue by adou0510** [rancher/rancher#28059]
js error 2.4.5,can get logs 

![image](https://user-images.githubusercontent.com/66617271/88378796-44d82c00-cdd4-11ea-9980-83f3b0afe36f.png)

**Comment by Diyuzhou** [comment]
我也是一样的问题，rancher2.4.5 用k3s和helm部署的高可用集群
![Screen Shot 2020-07-24 at 6 01 39 PM](https://user-images.githubusercontent.com/21288434/88380924-05134380-cdd8-11ea-86ba-3ce7212ca55e.png)

**Comment by mrcdb** [comment]
I have the same issue (can see logs but not use any shell in cluster explorer) with 2.5.3. I have also tried with 2.5.1 and same error.
