### ISSUE TITLE
rancher节点运行一段时间（1天左右）之后，节点kubelet异常，导致服务器假死  ssh无法登录，这种现象很频繁的，没有任何其他pod运行

### ISSUE THREAD

**Issue by sandiandian** [rancher/rancher#28058]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
helm install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
metal
cpu 80core
mem 256G
- Kubernetes version (use `kubectl version`):
1.18.3

```
(paste the output here)
```

- Docker version (use `docker version`):
19.3.2

```
(paste the output here)
```

**Comment by sandiandian** [comment]
机器重启之后，发现一个服务器内核的问题
nmi watchdog bug soft lockup cpu#41 stuck for 67s

**Comment by sandiandian** [comment]
docker运行的rancher容器会使我的机器内核发生死锁的情况，从而导致服务器假死

**Comment by Sandiagal** [comment]
兄弟找到解决方法了吗？同样的问题，我用2.4.8的rancher，rancher集群挺好的，下游集群总有一台机器软锁。cpu、内存都很充足，软锁的机器也没运行负载容器。

**Comment by sandiandian** [comment]
最终确定为原因为rancher的nginx-ingress导致的，暂时的解决方法为按照集群时不按照ingress，如需使用，自己手动安装。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rancher/rancher"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月20日(星期三) 上午10:44
收件人:&nbsp;"rancher/rancher"<rancher@noreply.github.com&gt;;
抄送:&nbsp;" "<1041779924@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rancher/rancher] rancher节点运行一段时间（1天左右）之后，节点kubelet异常，导致服务器假死  ssh无法登录，这种现象很频繁的，没有任何其他pod运行 (#28058)





 
兄弟找到解决方法了吗？同样的问题，我用2.4.8的rancher，rancher集群挺好的，下游集群总有一台机器软锁。cpu、内存都很充足，软锁的机器也没运行负载容器。

**Comment by Sandiagal** [comment]
太感谢了 我这就去试试
