### ISSUE TITLE
Role builder doesn't update builtin RoleTemplate on upgrade from 2.4.5 to master

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#28056]
The new rule added to ["cluster-owner"](https://github.com/rancher/rancher/blob/master/pkg/data/management/role_data.go#L120) and "project-owner" roleTemplates does not get added on upgrade from 2.4.5 to master.
It gets added on fresh install of master

gzrancher/rancher#9345

**Comment by sowmyav27** [comment]
**Verified on an upgrade from 2.4.5 to master-head commit id: `8d9cedde`**

**Scenario#1**
- On 2.4.5 , Create a cluster
- create roles cloned from cluster-owner and project owner - test1 and test2
- Add user1 with role test1
- Add user2 with role test2
- Upgrade to master-head
- Cluster Owner and Project owner roles have the new "verb" added. 

**Scenario#2**

- As an Admin, create a project level role r1 cloning it from project-owner on 2.4.5
- Create a user - user2 and assign this role r1 to a project - Default
- upgrade rancher to master-head
- Login as user2
- Navigate to Projects/Namespace page.
- Edit Project --> Add quota --> Save. Error seen projects.management.cattle.io "p-ft5wh" is forbidden: User "u-eoltlv6hms" cannot update resource "projects" in API group "management.cattle.io" in the namespace "c-7877b"
- Go to default project ---> monitoring --> You do not have permission to configure project level monitoring. is seen.
- Add "Own" verb to the cloned project Owner role.
-  Login as user2 --> Projects/Namespaces --> Edit Project --> Add quota --> Save. User is able to make changes

**Scenario#3** - has an Issue

- As an Admin, create a cluster level role r1 cloning it from cluster-owner in 2.4.5
- Create a user - user3 and assign this role r1 to a project - Default
- upgrade rancher to master-head
- Login as user3
- Go to cluster level monitoring
- User sees message : You do not have permission to configure cluster level monitoring.
- Add "Own" verb for clusters to this cloned role
- Login as user3 --> Cluster level monitoring. This is enabled for the user after a delay of about 10 minutes. Reopening the issue to fix this.

**Scenario#4**

- As an Admin, create a project level role which inherits from Kubernetes Admin role only on 2.4.5
- Create a user - user1 and assign this role ^^^ to a project - Default
- upgrade rancher to master-head
- Login as user1
- Navigate to Projects/Namespaces page
- Edit project Default. Add Quota --> "Resource/Quotas" --> Enter values and click on save.
- User is NOT able to make changes error seen: projects.management.cattle.io "p-ft5wh" is forbidden: User "u-npjx57vxal" cannot update resource "projects" in API group "management.cattle.io" in the namespace "c-7877b"


**On the upgraded setup**

- Add a new user user4 with create a project level role which inherits from Kubernetes Admin role only and assign to project Default.
- login as user4
- Navigate to Projects/Namespace page.
- Edit Project --> Add quota --> Save. Error seen as expected. projects.management.cattle.io "p-ft5wh" is forbidden: User "u-zjc5eshfdz" cannot update resource "projects" in API group "management.cattle.io" in the namespace "c-7877b"
- Add a new user user5 with a role - cloned from Project owner.
- Login as user5.
- Navigate to Projects/Namespace page.
- Edit Project --> Add quota --> Save. User is able to save with no errors.
- Navigate to project Monitoring --> User is able to enable project monitoring.
- Add a new user user6 with a role - cloned from Cluster owner.
- Login as user6.
- Navigate to cluster Monitoring --> User is able to enable cluster monitoring.

**Comment by sowmyav27** [comment]
**Verified on an upgrade from 2.4.5 to master-head commit id: `4fbd822c`**

1. As an Admin, create a cluster level role r1 cloning it from cluster-owner in 2.4.5
2. Create a user - user3 and assign this role r1 to to the cluster
3. upgrade rancher to master-head
4. Login as user3
5. Go to cluster level monitoring
6. User sees message : You do not have permission to configure cluster level monitoring.
7. Add "Own" verb for clusters to this cloned role
8. Login as user3 --> Cluster level monitoring. CIS scan/monitoring (cluster level) are immediately enabled for the user and there is NO delay.
