### ISSUE TITLE
rancher 2.4.5 k3s docker problem

### ISSUE THREAD

**Issue by Diyuzhou** [rancher/rancher#28062]
I deployed rancher 2.4.5 by using k3s and helm , after I finished it , I can found my container pod by using kubect get pods command , but I can't find any docker container by using docker ps -a , please tell me why?
![Screen Shot 2020-07-24 at 6 59 07 PM](https://user-images.githubusercontent.com/21288434/88384865-cc776800-cddf-11ea-9ba4-a8ba7e3cd02f.png)

**Comment by superseb** [comment]
The default runtime is `containerd`, you can use `k3s ctr container list` or `k3s crictl ps`

**Comment by Diyuzhou** [comment]
thanks
