### ISSUE TITLE
No "Certificates Rotate" option on K3S clusters.

### ISSUE THREAD

**Issue by rptl** [rancher/rancher#28069]
Version tested: 2.4.5
Tested only with K3S cluster ( local /remote )

According docs 
> Rotate the certificates:
>     Rancher v2.2.4+: If you are running Rancher v2.2.4 or higher, you can rotate certificates from the UI. 
>     To do so, browse to the cluster in the Rancher UI, click the vertical ellipses, click Rotate Certificates, 
>     select Rotate all service certificates and click Save.

It's showing up only following options:
> Edit
> View in API
> Delete (if not local cluster)

**Comment by superseb** [comment]
I assume the linked section is from https://rancher.com/blog/2019/kubernetes-certificate-expiry-and-rotation-in-rancher-kubernetes-clusters, this also states: 
```
The instructions below detail how to rotate the certificates in both Rancher-launched and RKE-provisioned clusters, both before expiry when certificates are still valid, and also in the event that the certificates have already expired.
```

Similar to what is described on https://rancher.com/docs/rancher/v2.x/en/cluster-admin/certificate-rotation/. This is only available for Rancher Launched Kubernetes (https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/)
