### ISSUE TITLE
Internal Address Setting is not alterable, etcd from private network can't join the cluster

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#28073]
I recently connected a second site to an existing cluster, it was wished that the etcd runs also on one node of the other connected side, since this infrastructure should gradually migrate.
The problem: Everything is fine, connection works perfect routing is working, just RKE won't configure etcd correctly. This should,  at least what the docs are saying, be fixable by deploying with the internalAddress specified in the RKE config. However, this is not editable in the rancher ui and I don't seem to find a way to make it work. 

So finally reaching out here, see log below for some insight.

```
2020-07-24 21:32:58.977617 I | embed: rejected connection from "192.168.1.4:44064" (error "tls: \"192.168.1.4\" does not match any of DNSNames [\"node-1\" \"node-2\" \"localhost\" \"kubernetes\" \"kubernetes.default\" \"kubernetes.default.svc\" \"kubernetes.default.svc.cluster.local\"] (lookup kubernetes.default.svc.cluster.local on 1.1.1.1:53: no such host)", ServerName "", IPAddresses ["pub-ip" "pub-ip2" "127.0.0.1" "10.43.0.1"], DNSNames ["node-1" "node-2" "localhost" "kubernetes" "kubernetes.default" "kubernetes.default.svc" "kubernetes.default.svc.cluster.local"])

```

Version is currently rancher v2.4.3

**Comment by wzrdtales** [comment]
anyone an idea how to fix that or make rancher add those missing ips. I tried already adjusting the values in the metadata inside the local cluster (I took a backup before), but even if I change those resources there, it will restore to the before state, so either I did not alter the right ones, or I am missing something :/

@superseb maybe you can help on that?

**Comment by wzrdtales** [comment]
trying my luck again, anyone who can help on this?

**Comment by wzrdtales** [comment]
ping, trying with you  @superseb again :/ sry to bother so much

**Comment by superseb** [comment]
Please describe the issue in detail, meaning:

- Provide the `docker run` command used to register the host
- Provide `docker inspect etcd` from the current nodes and the newly added to see what is configured
- Details on network config on the current and newly added host (`ip a s`/`ip route show`)

~It is also unclear if you actually added it with the correct addresses initially or if you are trying to edit to the correct address afterwards? I wouldn't expect the latter to work, it would just need to be deleted, cleaned and re-added with the correct configuration.~ I see the edited title. Why is removing and re-adding the node not an option? You are basically running into https://github.com/rancher/rancher/issues/14102 now.

**Comment by wzrdtales** [comment]
@superseb  The nodes run also openebs, removing them would mean to have huge trouble with not loosing the data of the existing pvs... . I tried just resubmitting the joining command with the internal address provided on the old nodes, but this has no effect at all.

**Comment by wzrdtales** [comment]
> Provide the docker run command used to register the host

Which one, the new one or the old? This is not a problem with adding a new host, this is a problem altering an old one. The old one was added without the internal/external address provided, exactly that is the problem and is not alterable in the aftermath.

> Provide docker inspect etcd from the current nodes and the newly added to see what is configured

https://pastebin.com/84Np0JxJ - From one of the current nodes (newly added, I had to remove it currently b/c it can't be added need to add that first again)

Replaced ips node1 and node2 are the public ips of the nodes, those need to be the private ones instead, which is exactly what I am trying to solve.

**Comment by wzrdtales** [comment]
> Details on network config on the current and newly added host (ip a s/ip route show)

That I will not post publicly, only in a disclosed channel.

However:

ip addresses assigned: NIC1 6 Public IPs
ip addresses assigned: NIC2 2 Private IPs

For the new machine on the other side


ip addresses assigned: NIC1 1 Private IP - This one does not have a public ip, the networks are connected to each other and communicate normally on layer2, but only on the private range not publicly (this node is not exposed to the internet just the ethernet which all nodes have access to).

Routes:

Nothing special: Calico routing, I have nodes on the other side for the workers, communication is fine.

**Comment by wzrdtales** [comment]
What I have tried was editing the metadata state of rancher for this cluster already. I edited the cluster resource and node resources, however rancher will restore the state from somewhere again as soon as an update for those nodes runs. And that is where it gets stuck, where the information is coming from. In theory the task should be easy:
Reconfigure rke to use internal adresses, rollout new certificates for etcd, done.

**Comment by wzrdtales** [comment]
More infos what I tried

kubectl edit clusters/clusterId - edit ips accordingly
kubectl edit nodes/nodename - edit ips accordingly
kubectl -n clusterid edit nodes.management.cattle.io/internal-id - edit ips accordingly

rerun setup task by minor settings change

**Comment by wzrdtales** [comment]
I finally solved it oO, I just had an idea: What happens when I change the /etc/hosts file accordingly to resolve to the private ip. Did that, restarted docker, and now it started displaying the correct ips... . I tried to add the etcd host again, and worked without problems.

**Comment by wzrdtales** [comment]
ok happy to early, etcd can't join since etcd is still reporting  rejected connection from "192.168.1.3:43152" (error "tls: \"192.168.1.3\" does not match any of DNSNames

**Comment by wzrdtales** [comment]
even with spoofed dns entries it will result in this:

```
2020-08-05 17:48:17.473226 E | rafthttp: request cluster ID mismatch (got f43462c8c88a5f56 want 4137c9d7f3e23b91)
```

**Comment by wzrdtales** [comment]
I guess best thing is stop letting rancher handle etcd and take into my own hands :/

**Comment by gerwim** [comment]
Okay, I had the exact same issue: my original cluster was created on a cloud provider and only had public IP's. I wanted to move all the nodes behind a firewall, on private network. However, I could not get the new master to join the exisiting etcd cluster. Rancher would mix the external IP and the internal IP (there are numerous issues about that) and the same error would keep popping up:

```
embed: rejected connection from "10.1.0.106:51728" (error "tls: \"10.1.0.106\" does not match any of DNSNames
```

I could not get `10.1.0.106` (which is the internal IP of the machine I'd like to get off the public network) in the SSL certificate. I could not set `rke.cattle.io/internal-ip` and then rotate the certificates (to let them be regenerated).

My solution to this (after trying so much options), was to use iptables routing to rewrite the IP:
```
iptables -t nat -A OUTPUT -p tcp -d 10.1.0.61 -j DNAT --to-destination EXTERNALIP
iptables -t nat -A PREROUTING -p tcp -d 10.1.0.61 -j DNAT --to-destination EXTERNALIP
iptables -t nat -A POSTROUTING -j MASQUERADE
```

`10.1.0.61` is the IP of the new internal master node
`EXTERNALIP` is an external IP (on the firewall) which I used to NAT (just for the time being).

This makes the request to etcd appear from the original external IP (which is inside the etcd certificate `/etc/kubernetes/ssl/kube-etcd-*.pem` and allows the certificate to be used and etcd to be migrated! 🎉

**Comment by wzrdtales** [comment]
still an issue wont ever be stale

**Comment by superseb** [comment]
Is this the same as https://github.com/rancher/rancher/issues/14102 or does it have something else to it?

**Comment by gerwim** [comment]
They could be very well related. There's currently no way to change IP addresses. Rancher generates ETCD SSL certs which are bound to specific IP addresses and are not regenerated which break communications with new nodes.

**Comment by wzrdtales** [comment]
no not at all related.

This is about existing clusters that are trying to add afterwards a private network and connect a new etcd node on this private network. With rke **without** rancher this is easy pie, with rancher controlling rke it is impossible. In general I would wish more control of rke since rancher is breaking just too many things and it is really hard and some things impossible to fix those issues....

**Comment by mxm-tr** [comment]
still an issue

**Comment by ItsReddi** [comment]
> ```
> iptables -t nat -A OUTPUT -p tcp -d 10.1.0.61 -j DNAT --to-destination EXTERNALIP
> iptables -t nat -A PREROUTING -p tcp -d 10.1.0.61 -j DNAT --to-destination EXTERNALIP
> iptables -t nat -A POSTROUTING -j MASQUERADE
> ```
@gerwim do you have any script for that?

@superseb may reopen that issue.... its still valid

**Comment by gerwim** [comment]
@ItsReddi script? What do you mean? Those are three lines of commands. :-)
