### ISSUE TITLE
federation 2.0 setup on rancher latest 

### ISSUE THREAD

**Issue by rushins** [rancher/rancher#28086]
Hello 

I would like to check if Rancher is supported on Federation as per this guide https://github.com/rancher/rancher/wiki/Rancher-Kubernetes-Cluster-Federation-for-Rancher-1.x. 

the guide is quite old (federaetion 1.0) where kubernetes federation is 2.0 now , so can you guys provide a correct document with latest Rancher supported from federation method for on-prem.

BR

**Comment by vincent99** [comment]
Federation v1 is deprecated and v2 has been alpha forever, with no clear path to graduating, decelerating contributions from the developers, and limited demand from our users.  That is not a combination we generally spend time supporting.

Follow their guide if you want to use it; Rancher creates normal k8s clusters and there is nothing in particular that's Rancher-specific about installing or using it.

**Comment by rushins** [comment]
hi Vincent,
understood but need some info as we are enterprise customer of Rancher and this is indeed needed for our DR

i follow the guide and getting this error with slave authorizatin. i setup 2 Rancher latest clusters and follow the guide. here is the issue i have opened with Federation 2.

https://github.com/kubernetes-sigs/kubefed/issues/1257

while running kubefedctl join i get the error unauthoried of the slave (second cluster )

kubefedctl join slave --v=2 --host-cluster-context master --kubefed-namespace=kube-federation-system
error
I0727 16:42:07.535733 38817 join.go:148] Defaulting cluster context to joining cluster name slave
I0727 16:42:07.535797 38817 join.go:160] Args and flags: name slave, host: master, host-system-namespace: kube-federation-system, kubeconfig: , cluster-context: slave, secret-name: , dry-run: false
I0727 16:42:07.567766 38817 join.go:242] Performing preflight checks.
F0727 16:42:07.584377 38817 join.go:127] Error: Unauthorized

---
any clue because this is happening on Ranche cluster only where as i dont see the same issue on a opensource kubernetes bootstrapped cluster.

**Comment by vincent99** [comment]
If you are a customer then the ticket system we provide is the appropriate place to ask and reach the right people, not GitHub issues.  But presumably from the error, the user you're running as doesn't have enough permission to do the operation it's requesting..
