### ISSUE TITLE
If long service name, the dropdown of services on the detailed service page has the carrot on service name

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2808]
<img width="462" alt="screen shot 2015-11-24 at 9 42 50 pm" src="https://cloud.githubusercontent.com/assets/11410997/11389348/7ed67594-92f4-11e5-9873-dc46f88ad8b3.png">

**Comment by lvuch** [comment]
PR waiting on review

**Comment by lvuch** [comment]
![screen shot 2015-11-30 at 3 52 17 pm](https://cloud.githubusercontent.com/assets/3013118/11487124/61505fc8-977a-11e5-817b-55dbde272d28.png)

**Comment by tfiduccia** [comment]
Build Master
Verified Fixed
