### ISSUE TITLE
[UI] Add Public German locations to the Azure choices

### ISSUE THREAD

**Issue by adaliszk** [rancher/rancher#28082]
**What kind of request is this (question/bug/enhancement/feature request):**
feature-request

**Steps to reproduce (least amount of steps as possible):**
1. Open your Node Templates in Rancher (User picture -> Node Templates)
2. Add a new Template and Select Azure
3. In the Placement options, for Environment choose "AzurePublicCloud"
4. In the Region field, find "Germany North" or "Germany West Central" location

**Result:**
The options "Germany North" and "Germany West Central" is missing. Even if you select "AzureGermanCloud" the regions still missing "Germany North" or "Germany West Central".

**Other details that may be helpful:**
- https://azure.microsoft.com/en-us/global-infrastructure/data-residency
- https://azure.microsoft.com/en-us/global-infrastructure/geographies

In both of those links, the "Germany North" and "Germany West Central" is clearly shown, and in fact, you can select these locations if you are using the Public cloud.

**Environment information**
- Rancher version:  v2.4.5 (using `rancher/rancher:latest`)
- User Interface version: v2.4.28
- Installation option: Single (with Docker)
- Docker version:
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:50 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version a1acca856`

Germany North and Germany West Central are available in Azure node template.
![Screen Shot 2020-08-26 at 2 56 58 PM](https://user-images.githubusercontent.com/57409052/91361061-68fca380-e7ac-11ea-8f74-9038a1337563.png)

Also observed Azure config set to correct locations:
Germany North:
```
"azureConfig": {
"availabilitySet": "docker-machine",
"clientId": "",
"customData": "",
"diskSize": "30",
"dns": "",
"dockerPort": "2376",
"environment": "AzurePublicCloud",
"faultDomainCount": "3",
"image": "canonical:UbuntuServer:18.04-LTS:latest",
"location": "germanynorth",
"managedDisks": false,
"noPublicIp": false,
"nsg": "rancher-managed-hmH9AoOJ",
```
Germany West Central:
```
"azureConfig": {
"availabilitySet": "docker-machine",
"clientId": "",
"customData": "",
"diskSize": "30",
"dns": "",
"dockerPort": "2376",
"environment": "AzurePublicCloud",
"faultDomainCount": "3",
"image": "canonical:UbuntuServer:18.04-LTS:latest",
"location": "germanywestcentral",
"managedDisks": false,
"noPublicIp": false,
"nsg": "rancher-managed-hmH9AoOJ",
```
