### ISSUE TITLE
Edit of OPA gatekeeper as yaml doesn't work.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/rancher#28085]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster.
2. Navigate to dashboard, enable gatekeeper.
3. Click edit/view in yaml.
4. Change audit interval to 120, click save.

**Result:**
Saving stuck and values don't get changed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-2474-head- 374b38cb2
- Installation option (single install/HA): Single

**Comment by izaac** [comment]
@westlywright the current behavior is if I just set the values I want to upgrade:

```yaml
---
auditInterval: 120
```

Click upgrade then the operation fails.

```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Deployment.spec.template.metadata.annotations.container): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations: got "map", expected "string", ValidationError(Deployment.spec.template.spec.nodeSelector.kubernetes): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got "map", expected "string"]
```

I also tried with the same results:

```yaml
auditInterval: 120
```

```yaml
{
  auditInterval: 120
}
```

But if we copy the original installation values, edit the values we want to upgrade and then pasting this in the `Values YAML` UI the upgrade is completed.


Using the helm3 CLI `--values=values.yaml` this work with contents:

```yaml
auditInterval: 120
```

**Comment by izaac** [comment]
Opened:

https://github.com/rancher/dashboard/issues/1016

**Comment by izaac** [comment]
Upgrading YAML using the entire values.yml works but upgrade should behave as mentioned in #1016 Using specific values no the entire values.yml from installation.
