### ISSUE TITLE
Authentication: Invalid saml attributes

### ISSUE THREAD

**Issue by cdperdomo** [rancher/rancher#28087]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EC2, EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):

```
v1.16.8-eks-fd1ea7
```

- Docker version (use `docker version`):

```
(paste the output here)
```
Unable to authenticate with Keycloak. 

![image](https://user-images.githubusercontent.com/5383188/88485530-170df700-cf3c-11ea-96ce-d436283806b9.png)

**Comment by pjoshi751** [comment]
I am facing the same issue.  Tried every possible combination of Mappers in keycloak.  Also, verified the "uid" field is indeed present in the Keycloak response, yet continue to see this error at the rancher server:
```
2021/03/09 12:34:13 [ERROR] SAML: Unique ID field is not provided in SAML Response
```

**Comment by cdperdomo** [comment]
make sure you have at least these mappers enabled in the Keycloak client.

![image](https://user-images.githubusercontent.com/5383188/112159199-e196d780-8bb6-11eb-92d9-3a08414db5df.png)

**Comment by pjoshi751** [comment]
Yes, these are enabled.  But I couln't see "uid" field in SAML response from Keycloak.  Then I modified the above mappers to return a "uid".  I can see the same in SAML now, but Rancher throws the same error.   Best would be to take a debug print of what is Rancher seeing after parsing the SAML, but I don't have a dev setup:
```<saml:Attribute FriendlyName="uid"
                            Name="uid"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:type="xs:string"
                                     >testuser@xyz.com</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute FriendlyName="email"
                            Name="urn:oid:1.2.840.113549.1.9.1"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:type="xs:string"
                                     >testuser@xyz.com</saml:AttributeValue>
            </saml:Attribute>
```

**Comment by pjoshi751** [comment]
Oops, looks like the field names in the Rancher form that I had given were incorrect.  Works now.   Sorry for the bother.

**Comment by shizhiliuyu** [comment]
Hello, my ranher v2.4.5 encountered the same problem, how did you finally solve it?
