### ISSUE TITLE
If sidekick name > 63 characters, place a user friendly warning (like for stack/service)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2809]
UI as of 11/24 evening.

Steps to Reproduce:
Create a sidekick with name > 63 characters.

Result: Validation failed in API: name

Would like: "name should be 1-63 characters long" which is the text used for when creating a stack/service with too long of a name.

**Comment by vincent99** [comment]
Added schema validation of the sidekicks, which covers other things besides this:

![image](https://cloud.githubusercontent.com/assets/753917/13870201/60bd0484-ec99-11e5-9deb-c61b2193bfe0.png)

**Comment by tfiduccia** [comment]
Version - master UI 3/18
Verified fixed
