### ISSUE TITLE
catalog.cattle.io.releases - failed to delete apps 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28097]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher master-head in HA mode
- go to the dashboard 
- add a repo
- deploy and app from the repo
- delete the app after it is deployed 

**Result:**
- the app is not deleted 
- the POST request looks like this 
`https://my-address/v1/catalog.cattle.io.releases/monitoring-system/sh.helm.release.v1.rancher-monitoring.v1?action=uninstall`
- the response code is 201

**Comment by bmdepesa** [comment]
Instead of seeing a 201, I receive a 500 through UI and API:
```
{
"type": "error",
"links": { },
"code": "ServerError",
"message": "Secret \"helm-operation-mgqqr\" is invalid: data[]: Invalid value: \"\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')",
"status": 500
}
```

**Comment by izaac** [comment]
Same happens for `rancher-logging`

```json
{
    "type": "error",
    "links": {},
    "code": "ServerError",
    "message": "Secret \"helm-operation-h59gd\" is invalid: data[]: Invalid value: \"\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')",
    "status": 500,
    "type": "error"
}
```

**Comment by jiaqiluo** [comment]
on rancher/rancher:`master-3411-head`

The POST request fails with code 500 
```
code: "ServerError"
links: {}
message: "Secret "helm-operation-pmq29" is invalid: data[]: Invalid value: "": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')"
status: 500
type: "error"
```

Also, in the UI
<img width="423" alt="Screen Shot 2020-08-05 at 5 00 29 PM" src="https://user-images.githubusercontent.com/6218999/89475777-c6697b80-d73d-11ea-8565-bc919126586a.png">

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 502b1839e

The previous error is no longer seen, but the helm operation now fails with an error: 
```
helm uninstall rancher-istio
Error: uninstall: Release not loaded: rancher-istio: release: not found

**Comment by izaac** [comment]
`master-head (08/10/2020)` _dbcf168c4_

```
helm uninstall rancher-logging
Error: uninstall: Release not loaded: rancher-logging: release: not found
```

**Comment by jiaqiluo** [comment]
Same error for monitoring https://github.com/rancher/dashboard/issues/982
```
 
Mon, Aug 10 2020 3:09:03 pm
helm uninstall rancher-monitoring-crd
Mon, Aug 10 2020 3:09:03 pm
Error: uninstall: Release not loaded: rancher-monitoring-crd: release: not found
```

the namespace is missing in the helm command

**Comment by izaac** [comment]
`master-head (08/12/2020)` _d19f179c4_

```
helm uninstall rancher-logging
Error: uninstall: Release not loaded: rancher-logging: release: not found
```

**Comment by jiaqiluo** [comment]
The bug still exists on `master-d19f179c4ff15bb782e27ed50d33d169dad79f80-head`

**Comment by izaac** [comment]
`master-head (08/12/2020)` _d19f179c4_

**rancher-gatekeeper**

```
helm uninstall rancher-gatekeeper
Error: uninstall: Release not loaded: rancher-gatekeeper: release: not found
```

**Comment by izaac** [comment]
Validated on Rancher `master-head (08/20/2020)` _7f398fb3d_

I was able to install Apps in downstream clusters and remove them after install. Tested with the `rancher-gatekeeper` chart.
