### ISSUE TITLE
In a 10acre setup, if I restart the Network Agent, it will get stuck. 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#281]
Version: v0.12.0

Steps to Reproduce:
1. Start a Rancher cluster with the 10acre-ranch script.
2. Create a container
3. Restart the network agent container. 

Result: The network agent gets stuck in restarting. 
Expected Result: The network agent restarts.

**Comment by vincent99** [comment]
Works for me..

**Comment by cloudnautique** [comment]
I just saw it on 10acre ranch host running v0.50.2. Looks like Docker gets wedged.

**Comment by sangeethah** [comment]
There is another issue which also tracks the same behavior where docker stops responding when network agent is restarted- #1406 . This does not happen always.

**Comment by deniseschannon** [comment]
Closing in favor of the other network agent issues that @sangeethah listed. I don't think there is any difference between 10acre setup and regular set ups.
