### ISSUE TITLE
Kiali is not displaying trafic on the graph

### ISSUE THREAD

**Issue by Xenon341** [rancher/rancher#28109]
Hi everyone,
First, thank you for creating Rancher, it's a pleasure to work on the product :)

My first bug report here/
THe Kiali Graph is not displaying trafic, the pod logs show that a TS label is missing.

Hope you can fix it !

Thanks.

**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Install Rancher 2.4.5
Install Istio 1.5.8 with Istio ingress Gateway
Deploy a pod, with a Service, DestinationRUle and Istio Gateway
Access the deployed app

**Result:**

Open Kiali, trafic is not displayed on graph

**Other details that may be helpful:**

In the Kiali pod logs :

Skipping {destination_service="workload1-service.fmr-istio.svc.cluster.local", destination_service_name="workload1-service", destination_service_namespace="fmr-istio", destination_workload="workload1", destination_workload_namespace="fmr-istio", request_protocol="http", response_code="200", response_flags="-", source_workload="istio-ingressgateway", source_workload_namespace="istio-system"}, **missing expected TS labels**

Same bug found here : https://github.com/istio/istio/issues/24924

Some one say that going with 1.18 of Kiali fix the bug, but apparently, 1.18 is not meant to be with Istio 1.5

https://github.com/kiali/kiali/issues/1007

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider Azure
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud (3x 8vCPU, 32GO RAM)
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
19.3.12
```

gzrancher/rancher#11504

**Comment by cbron** [comment]
Yes this was mentioned in the [release notes](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/istio/release-notes/#known-issues). We can keep this issue open and use to track the upstream istio issue.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4.6-rc4
Istio 1.5.9

* Deploy a cluster
* Enable Istio 1.5.9 in a cluster (or upgrade from a previous version)
* Deploy some services and access
* Traffic shows correctly in the Kiali graph

![Screen Shot 2020-08-13 at 2 41 23 PM](https://user-images.githubusercontent.com/21316915/90190343-aeb07980-dd73-11ea-81b6-8d56a3452b1d.png)
