### ISSUE TITLE
Adding a host that was previously used in rancher, shows the stack names in hosts view (even though containers show random ID)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2810]
v0.47.0-rc3

Steps to Reproduce:
1. Add a host to Rancher
2. Start some services on the host
3. De-activate/remove host
4. Re-add Host, View host in Infrastructure -> Hosts tab

Result: All previously running containers are still running on host (as expected), but the old stack names are grouping and still showing up in the host view. No stacks/services show up in Applications->Stacks tab.

Expected Result: All containers with the ID should be in "Standalone" Containers section

<img width="318" alt="screen shot 2015-11-25 at 7 01 45 am" src="https://cloud.githubusercontent.com/assets/11410997/11400478/6e0a7f82-9342-11e5-90ea-8d11d08c6b96.png">

**Comment by vincent99** [comment]
It's not terribly practical to fix this.. the display is just based on the container label to avoid having to load and correlate all the containers by actual service.  And the container label is still there when it's imported back in.

**Comment by deniseschannon** [comment]
Okay, I'll just remember what is going on and let users know if anyone complains. It's just weird user experience.
