### ISSUE TITLE
[UI] 网址为https://172.18.110.139的网页可能暂时无法连接，或者它永久性的移动到了新网址(ERR_INVALID_RESPONSE)

### ISSUE THREAD

**Issue by alonemen** [rancher/rancher#28104]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
网址为https://172.18.110.139的网页可能暂时无法连接，或者它永久性的移动到了新网址(ERR_INVALID_RESPONSE)

**Result:**
DEBUG信息
2020/07/27 13:46:15 [ERROR] failed to serve UI: Get local: unsupported protocol scheme ""
2020/07/27 13:46:15 [DEBUG] 2020/07/27 13:46:15 http: TLS handshake error from 59.202.64.15:64883: remote error: tls: unknown certificate

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:2.2.7
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
- Kubernetes version (use `kubectl version`): 

```
Custom
cloud
v1.13.9
```

- Docker version (use `docker version`):

```
18.09.8
```

**Comment by thamerbelfkihthamer** [comment]
could any one translate the title of this issue in English, please
