### ISSUE TITLE
Don't propagate containers in Initializing states to DNS/metadata

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#2811]
Hi,

today I noticed that when a container is reported as unhealthy, it still shows up as a service container under /self/latest/service/containers.

Is this the expected behavior? When a container is unhealthy, I know it gets removed from <stack_name>.rancher.internal DNS entry. For this reason, I would also then expect to have it removed from the metadata, else how would I know if that container can be used in the service discovery?

If the container is kept in the metadata, I would then expect to have an /healthstate endpoint which I can query to determine if the container is okay or not.

Thanks,
Matteo

**Comment by m4ce** [comment]
EDIT: I've tested it again, I see that if the container fails, it gets removed. My problem comes from the fact that the container is stuck in initalizing state and it never goes into OK. Is there any setting which dictates how long a container can stay in initializing state before it's considered unhealthy?

**Comment by alena1108** [comment]
> today I noticed that when a container is reported as unhealthy, it still shows up as a service container under /self/latest/service/containers.

Thats a good catch. We should remove it from the metadata when it gets removed from DNS.

> If the container is kept in the metadata, I would then expect to have an /healthstate endpoint which I can query to determine if the container is okay or not.

We don't propagate state/health state to metadata on purpose - there is always a possibility of latency for state updates, and we don't want clients to rely on metadata for that.

>>  Or can we say that the container in INITIALIZING state should not appear in the metadata until it's OK

Thats an another good suggestion :) we shouldn't propagate containers in Initializing states to DNS/metadata. 

Thanks for reporting all the above, good bugs.

**Comment by alena1108** [comment]
Thought about possible use cases more. There are use cases when unhealthy/initializing container might need to access metadata for its internal use; sometimes even to establish an entry point for the health check itself. So it becomes a chicken/egg problem. Perhaps we should propagate "unhealthy" container data to "self" section only, and exclude it from the rest of the metadata?

@ibuildthecloud @vincent99 @cloudnautique  thoughts?

**Comment by alena1108** [comment]
Chatted with @ibuildthecloud @vincent99; the decision is - its unsafe to remove initializing/unhealthy containers from metadata. As even when considered unhealthy, the container itself might need access to metadata + other containers might need to know the info about the container becoming "ill". 

So we will add health_state as a container field, and push metadata updates on every health state change. There can be a tiny latency between health_state on rancher, and health_state on metadata, but thats the best we can do in the situation.

**Comment by m4ce** [comment]
@alena1108, sounds great, thank you!

**Comment by sangeethah** [comment]
Tested with build from master on dec 3.

container metadata has "health_state" field that tracks the "health_state" of the container.
The  "health_state" values "Initializing"/"unhealthy"/"healthy" get pushed to container metadata as they get changed.

**Comment by alena1108** [comment]
@sangeethah thats more than enough to test, thank you
