### ISSUE TITLE
Not able to create NodeTemplates

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#28119]
Rancher server - Built from master-head - `master-3366-head` ( HA install and single node install)

Steps to reproduce the problem:
Create a DO NodeTemplate.

Following errors seen in UI:

<img width="1001" alt="Screen Shot 2020-07-28 at 2 09 15 PM" src="https://user-images.githubusercontent.com/4266958/88722451-19a75280-d0dc-11ea-916c-343f5e2e1953.png">

API call failed:

Request URL: https://<ip>/meta/proxy/api.digitalocean.com/v2/regions?per_page=100
Request Method: GET
Status Code: 404 Not Found

Built-In Drivers (including Linode , DO) and seen in "Active" state.

**Comment by sowmyav27** [comment]
**Verified on latest master-head commit id: `6d6199121`**

- Able to deploy DO and custom clusters. No error seen
