### ISSUE TITLE
[BUG] Rancher API doesn't validate case sensitivity in Node Pool names

### ISSUE THREAD

**Issue by Sheldons92** [rancher/rancher#28110]
**What kind of request is this:**

Bug

**Steps to reproduce:** 

Create a Node Pool for a cluster via  the APIl using uppercase characters for node pool prefix

**Result:** 

NodePools created with Upper case characters and downstream clusters fail to provision correctly as they're expecting lowercase prefixes.

**Other details that may be helpful:**

When creating node pools via the Rancher UI, when using upper case characters they are automatically converted to lowercase.

Would expect some API Validation to reject or convert uppercase characters.

**Environment information**
- Rancher version: 

2.4.4
- Installation option:

 HA

gz#11446
SURE-2305

**Comment by snasovich** [comment]
Closing as stale. SURE-2305 is also closed with the same reason now.
