### ISSUE TITLE
Outline of boxes on scheduling rules dropdown are not visible. 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2812]
v0.47.0-rc3

Steps to Reproduce:
1. Add a host label
2. Create a service, go to scheduling, select the dropdown to see the existing labels

Result: Border on values is very faint or same color.

<img width="284" alt="screen shot 2015-11-25 at 7 23 38 am" src="https://cloud.githubusercontent.com/assets/11410997/11401089/b40c5f20-9345-11e5-9387-3b7bafa1b304.png">

**Comment by deniseschannon** [comment]
Can we also make the dropdown the same size of the text field?

**Comment by tfiduccia** [comment]
Build from Master
Verified fixed
