### ISSUE TITLE
User is able to import the same EKS cluster multiple times on Rancher UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28130]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Import cluster A (created in EKS) as test-1
- Import cluster A (created in EKS) as test-2
- Add a nodegroup ng1 in test-1
- The node gets added in the node page for test-2 cluster also
- Edit test-2 and add a node group ng2.
- The cluster goes into Updating state. ng1 gets deleted and ng2 gets added in test-2

**Expected Result:**
To avoid the above scenario, we must not allow for the same EKS cluster to be imported multiple times

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `ca3f705a4 `
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS custom
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version d5e1b21b`

Steps:
Import cluster A (created in EKS) as test-1
Import cluster A (created in EKS) as test-2

Result:
User is unable to import the same cluster twice:
![Screen Shot 2020-08-27 at 4 37 20 PM](https://user-images.githubusercontent.com/57409052/91505194-d92a2880-e883-11ea-9977-09ad92a8a8e2.png)
