### ISSUE TITLE
Consistent naming: Update detailed external service page to "Hostname"

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2813]
v0.47.0-rc3

Steps to Reproduce:
1. Create external service with a hostname
2. Click on detailed view.

Result:

<img width="298" alt="screen shot 2015-11-25 at 7 32 08 am" src="https://cloud.githubusercontent.com/assets/11410997/11401279/a7059002-9346-11e5-85b8-e675ed92b8f4.png">

Expected Result: Use "Hostname" instead of "Host name"

**Comment by tfiduccia** [comment]
Version - master 2/17
Verified fixed
