### ISSUE TITLE
Sorting on detailed service page doesn't work for hosts, IPs, State

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2814]
v0.47.0-rc3

Steps to Reproduce:
1. Create GlusterFS Catalog  on different hosts

Problem 1: Host
2. Click on "Host" on detailed service page
Result: Containers sorted by something else
Expected Result: Containers sorted by host

<img width="160" alt="screen shot 2015-11-25 at 7 39 25 am" src="https://cloud.githubusercontent.com/assets/11410997/11401494/adc66686-9347-11e5-81c7-91c3226395f7.png">

Problem 2: IPs
3. Click on IPs
Result: Containers are sorted by first digit and then second digit of the third number in the 10.42.x.x IP. 
Expected Result: Containers to be sorted by the whole number of the third number.

<img width="121" alt="screen shot 2015-11-25 at 7 37 54 am" src="https://cloud.githubusercontent.com/assets/11410997/11401463/87e58c44-9347-11e5-98ec-5069876598c6.png">

Problem: State
4. Click on "State"
Result: Not all containers are sorted by State
Expected Result: All containers to be sorted by state.

<img width="139" alt="screen shot 2015-11-25 at 7 45 42 am" src="https://cloud.githubusercontent.com/assets/11410997/11401675/96be9b9c-9348-11e5-9f8f-3e7b019d1ce5.png">

**Comment by tfiduccia** [comment]
Version - master 3.20
Verified fixed
