### ISSUE TITLE
Linode node template option is missing

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28145]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
On latest master - commit id: `6d6199121`

- Go to Node Template page --> Add Node template 
- Error is seen on the UI and Linode node template option is NOT available
<img width="1069" alt="Screen Shot 2020-07-29 at 10 50 59 AM" src="https://user-images.githubusercontent.com/26032343/88836672-e4f2d400-d18b-11ea-9f14-44f788206d31.png">

- Navigate to add cluster page
- Error seen in console: `Uncaught (in promise) Event {isTrusted: true, type: "error", target: link#driver-ui-css-linode, currentTarget: null, eventPhase: 0, …}`

**Expected Result:**
Linode node template Option should be available

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master head   commit id: `6d6199121`
- Installation option (single install/HA): HA

**Comment by vincent99** [comment]
The backend serving the assets is currently broken, turn off the driver in settings if it's in the way.

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `d19f179c4`**

Linode option is available while creating a node template
User is able to deploy a linode cluster using this node template
