### ISSUE TITLE
Get request to v1/schemas returns 502 error all the time in ECM deployed clusters

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28150]
**What kind of request is this:**
bug

**Steps to reproduce:**
- Deploy Rancher HA k8s `master-head` _b369a60f2_
- Enable ECM and from the Ember UI deploy a DO cluster.
- After the cluster gets deployed click try dashboard

**Result:**

502 GET ` /k8s/clusters/c-xxxxx/v1/schemas`

![Screen Shot 2020-07-29 at 3 33 46 PM](https://user-images.githubusercontent.com/27659/88860598-fdc1b080-d1b0-11ea-8b17-efa9d003a5f7.png)

**Environment information**
- Rancher version: `master-head (07/29/2020)` _b369a60f2_
- Installation option: HA k8s rke setup.

**Comment by izaac** [comment]
This is no longer a blocker, workaround is to refresh the browser.
I opened #28364 to track this.

**Comment by brunoscota** [comment]
Same happened for me, but in my case, I fixed removing these annotations:
`  nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";`
