### ISSUE TITLE
Adding tags are not reflected in EKS console

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#28151]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Import an EKS cluster
Edit cluster
Add a tag in `cluster options`
Save
Repeat for node group:
Edit cluster
Add a tag in `managed node groups` section in any node group
Save

**Result:**
Upon edit:
Tag is not saved in `cluster options`
Tag is saved in `managed node groups`

Neither tag is seen in EKS cluster.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-3369-head`

- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): imported

**Comment by sowmyav27** [comment]
- Same issue is seen for a Hosted EKS cluster.
- Adding tags to Nodegroups --> Tags do not reflect in the EKS console.
- Tags on the cluster level are seen in the EKS console. And Labels on the nodegroup is seen in the EKS console.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version c428bc9`

Node group tags are reflected in EKS console:
![Screen Shot 2020-09-01 at 4 15 31 PM](https://user-images.githubusercontent.com/57409052/91915551-bd51c880-ec6f-11ea-8c4b-b69be05129e1.png)
![Screen Shot 2020-09-01 at 4 15 35 PM](https://user-images.githubusercontent.com/57409052/91915559-c04cb900-ec6f-11ea-96e9-91ed72fe7888.png)
