### ISSUE TITLE
Node group is not upgraded during k8s upgrade in EKS cluster

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#28156]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Import an EKS cluster with k8s version` 1.15`
Edit cluster
Upgrade cluster to `1.16`
Save

**Result:**
Cluster will go into updating state
When cluster is available, cluster view reports that k8s version is `v1.15.11-eks-14f01f`
Node view also reports that k8s version is `v1.15.11-eks-065dce`

EKS view reports difference in k8s version:
![Screen Shot 2020-07-29 at 4 29 00 PM](https://user-images.githubusercontent.com/57409052/88863993-04542600-d1b9-11ea-8c09-aa2f86691525.png)

In API:
```
"eksConfig": {
"amazonCredentialSecret": "cattle-global-data:cc-x5mc9",
"displayName": "aaron-eks7",
"imported": true,
"kmsKey": "",
"kubernetesVersion": "1.16",
"loggingTypes": null,
"nodeGroups": [
{
"desiredSize": 2,
"diskSize": 20,
"ec2SshKey": null,
"gpu": false,
"instanceType": "t3.medium",
"labels": { },
"maxSize": 2,
"minSize": 2,
"nodegroupName": "aaron-ng7",
"subnets": [ 4 items
"subnet-1544015e",
"subnet-4b645363",
"subnet-51a1f928",
"subnet-9f90bbc5"
],
"tags": { },
"type": "/v3/schemas/nodeGroup",
"version": "1.15"
}
],
```
**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-3369-head`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported

**Comment by rmweir** [comment]
This no longer applies as nodegroups will no longer automatically update for imported or created EKS clusters: https://github.com/rancher/rancher/issues/27777
