### ISSUE TITLE
Security group not visible upon cluster edit in EKS cluster

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#28155]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Import an EKS cluster
Edit cluster

**Result:**
Security group section is empty:
![Screen Shot 2020-07-29 at 3 55 33 PM](https://user-images.githubusercontent.com/57409052/88862082-3dd66280-d1b4-11ea-897a-a6c6307bae96.png)
We would expect the security group to be shown, but not editable.

In API, security group is null:
```
"privateAccess": false,
"publicAccess": true,
"publicAccessSources": null,
"region": "us-west-2",
"secretsEncryption": false,
"securityGroups": null,
"serviceRole": "",
"subnets": [ 4 items
"subnet-...",
"subnet-...",
"subnet-...",
"subnet-..."
],
"tags": null,
"type": "/v3/schemas/eksClusterConfigSpec"
},
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-3369-head`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported

**Comment by rmweir** [comment]
Moving to test as security groups are showing for me. It is possible that you are seeing the cluster security group in the console which we have omitted in security groups in the past and continue to do so. The security groups that would be shown here are ones under "Additional Security Groups" in the EKS console. I'm not against showing the cluster security group if requested. It may be a good idea to have it in its own field on status.

**Comment by aaronRancher** [comment]
Currently blocked by https://github.com/rancher/rancher/issues/28355
Will test once edit becomes available again.

**Comment by aaronRancher** [comment]
`Additional Security Groups` are available on cluster edit.
![Screen Shot 2020-08-14 at 1 29 12 PM](https://user-images.githubusercontent.com/57409052/90297813-9eb49a80-de44-11ea-98fa-c1b7b2b2c5f7.png)
Closing issue.
https://github.com/rancher/rancher/issues/28409 created to track adding `Cluster Security Group` in cluster edit.
