### ISSUE TITLE
[rancher-dns] empty environment name when creating route53 entry

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2816]
Environment name is 'qa'.
```
<Message>FATAL problem: DomainLabelEmpty encountered at backend.backend-betas..mydomain.co</Message>
```
```
Rancher	v0.46.0
Cattle	v0.112.0
User Interface	v0.65.0
Rancher Compose	v0.5.2
```

**Comment by deniseschannon** [comment]
Could you provide some more steps on how you got to this point? 

Did you have services first and then create the route53 service?
Did you already have a route 53 service and adding service?

Where is this message from? How were you adding services?

**Comment by deniseschannon** [comment]
@ndelitski If you can provide more information on how you got to this state, that'd be great. Please re-open if you can provide more information.
