### ISSUE TITLE
Register Cluster - Can we have `Rancher or k3s` option pre-selected as the default

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#28160]
There's some weird ui refresh happening when I click on "Register cluster" and then click on "Rancher/k3s" option.

We should have it pre-selected as the default option after selecting "Register Cluster"

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `5c1c2c5d7` ui tag: latest2**

"Rancher/k3s" option is pre selected 
<img width="1495" alt="Screen Shot 2020-07-30 at 10 25 11 AM" src="https://user-images.githubusercontent.com/26032343/88968113-aaf50100-d263-11ea-90c6-02b72d772823.png">
