### ISSUE TITLE
Failed to pull image from pipeline embeded registry

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#28167]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Enabled ECM
2. Run the pipeline-example-go in the Default project.
3. Wait until the pipeline finishes, then check the example deployment deployed by the pipeline.

**Result:**
The deployment is in an unready state with the ImagePullBackOff event.

**Other details that may be helpful:**
1. It works in v2.4.5
2. Error log from registry-proxy in cattle-pipeline namespace: 
```
[error] 19#19: *2 upstream SSL certificate does not match "docker-registry.p-k76cf-pipeline.svc.cluster.local" while SSL handshaking to upstream, client: 127.0.0.1, server: , request: "GET /v2/ HTTP/1.1", upstream: "https://10.43.234.234:443/v2/", host: "127.0.0.1:34802"
```
3. The `pipeline-docker-registry` secret is missing the `cattle.io/creator: norman` label. therefore, this registry credential does not propagate to namespaces of the project.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master(973ae6503f2bb711a2d426b111ee450d17d9f0fd)
- Installation option (single install/HA): HA

**Comment by PennyScissors** [comment]
Confirming it works in v2.4.5 and v2.3 as well. Seems to only be present in master.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 8fd81a9

* Enabled ECM
* In local cluster deployed `pipeline-example-go` pipeline and ran
* Example deployment deploys successfully - image is pulled
* registry secret contains the correct label: `cattle.io/creator: norman`
