### ISSUE TITLE
[UI] AWS EC2 Template: Expose Metadata Options fields

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#28178]
Need UI fields for the EC2 Instance Metadata Options based on two new flags introduced to the nodeDriver: 
Label Name | Field | Input | Default
---|---|---|---|
Expose Endpoint for Accessing Instance Metadata | `httpEndpoint` | `enabled` or `disabled` | `enabled`
Use HTTP Tokens for Instance Metadata Requests | `httpTokens` | `required` or `optional` |  `optional`

These should be introduced under the `Instance Options` section.

More information on the fields exposed: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyInstanceMetadataOptions.html

Related Issue: https://github.com/rancher/rancher/issues/25078

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `217656d19` and 2.4-head commit id: `c761bcd4d`**

- HTTP Tokens and HTTP endpoint input fields are available. 
- When selected, right value is set on the node.
<img width="1429" alt="Screen Shot 2020-08-05 at 10 25 10 AM" src="https://user-images.githubusercontent.com/26032343/89444532-aec2d080-d706-11ea-8a8f-3b4d60a43a84.png">

- Default value seen on the UI is Http endpoint: `Enabled` and HTTP tokens: `Optional`
