### ISSUE TITLE
sudo docker run -d --restart=unless-stopped   -p 30003:443 rancher/rancher

### ISSUE THREAD

**Issue by toyanghong** [rancher/rancher#28189]
level=fatal msg="apiserver exited: Unable to find suitable network address.error='unable to select an IP from default routes.'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this."
2020/07/31 15:46:20 [FATAL] k3s exited with: exit status 1

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/14840 and the suggested tests to see why Kubernetes is reporting this.
