### ISSUE TITLE
Cannot add custom git catalog in Rancher 2.4.5

### ISSUE THREAD

**Issue by stefanvangastel** [rancher/rancher#28188]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Add a custom chart git repo in Rancher 2.4.5

**Result:**

Error: `Error unmarshalling response from [https://git.redacted.nl/redacted/helm-charts.git/index.yaml]`

**Other details that may be helpful:**

Same repo is working other Rancher servers running 2.4.1 and 2.4.4

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA on k3s

- Docker version (use `docker version`): 19.3.12 ce

Screenshots:

![chart1](https://user-images.githubusercontent.com/2473490/89037662-3db69e00-d33f-11ea-868d-4ab9ace5cf42.JPG)

![chart2](https://user-images.githubusercontent.com/2473490/89037911-a6057f80-d33f-11ea-86b2-369ac3e11e5c.PNG)

**Comment by stefanvangastel** [comment]
Oke, deployed a 2.4.4 version; same issue. Next I deployed a 2.4.5 using the Docker install option. 

Conclusion: This issue only seems to occur in **Rancher deployed on kubernetes**.

**Comment by stefanvangastel** [comment]
The issue had to do with onprem ca, fixed it using: https://rancher.com/docs/rancher/v2.x/en/installation/options/chart-options/#additional-trusted-cas

**Comment by lushtech** [comment]
I get the same problem in rancher2.5.3 and rancher2.4.8.
And it worked well when it just started before days in rancher2.5.3, but now it shows the error.
```
Error unmarshalling response from [https://gitlab.test.cn/lushatech/my-helm-charts/index.yaml]
--
``` 
and then I test it in the rancher2.4.8, it didnot work when the rancher start up.

I dont know why it can works well in the begining in rancher2.5.3, and later some days , it become to no working.

**Comment by artm** [comment]
@stefanvangastel do you remember what was causing the problem exactly and how you fixed it? The link is dead and I'm not sure what "onprem ca" implies.

**Comment by bashofmann** [comment]
@artm you can find the page here now: https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/chart-options/#additional-trusted-cas
