### ISSUE TITLE
Unable to start a machine on Exoscale

### ISSUE THREAD

**Issue by vincentbernat** [rancher/rancher#2818]
Hey!

When starting a new host on Exoscale. we get the following error: `Unsupported type: []string`. This is because the `securityGroup` configuration parameter should be a string and not an array. In `go-machine-service`, the generated JSON is incorrect:

```json
        "securityGroup": {
            "type": "array[string]",
            "nullable": true
        },
```

This should be:

```json
        "securityGroup": {
            "type": "string",
            "nullable": true
        },
```

I didn't understand how this file is generated. The copy in rancher/machine repository is up-to-date but somehow, when the files are regenerated with `scripts/generate`, they are still wrong.

**Comment by wlan0** [comment]
The generation code is correct. It correctly interpreted the type []string from this flag https://github.com/rancher/machine/blob/master/drivers/exoscale/exoscale.go#L78. This is a bug in go-machine-service. We are not parsing string slices - https://github.com/rancher/go-machine-service/blame/master/handlers/create.go#L242

**Comment by vincentbernat** [comment]
Thanks for the pointer. I'll try to fix that then (unless you already have some kind of solution).

**Comment by wlan0** [comment]
Don't worry about it. I'll fix it before the end of the day today.

**Comment by wlan0** [comment]
@vincentbernat - This PR fixes it - https://github.com/rancher/go-machine-service/issues/69

**Comment by vincentbernat** [comment]
Thanks!
