### ISSUE TITLE
Ports from Service are not visible after creation or in inactive state

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2819]
v0.47.0-rc3

Steps to Reproduce
1. Create a service with a port mapped

Result: In stack summary view, service detail page, the ports are not showing up. When the service is in active state, the ports show up (and are clickable as expected)

Note: Ports are in the API

Expected Result: In inactive state, the ports should show up with no links (like how LB handles their ports)

**Comment by vincent99** [comment]
These are only available in the API when the service is active.  Changed the message.

**Comment by tfiduccia** [comment]
Version - master 3/22
Verified fixed - port not visible when service is not active
