### ISSUE TITLE
UI isn't update without forced refresh

### ISSUE THREAD

**Issue by haswalt** [rancher/rancher#2820]
Update rancher server to latest version 0.46 - 0.47. New UI wasn't showing. Cleared browser cache to force reload, new UI shows up.

I'm assuming asset versioning / hashing isn't working correctly.

**Comment by deniseschannon** [comment]
I face this all the time, but just clear my cache. :)

**Comment by haswalt** [comment]
Yes I have my cache off usually due to web develpment however this is something that should be considered / handled for future releases considering not everybody using Rancher is a developer :)

**Comment by vincent99** [comment]
As far as I can see this works between sufficiently new releases, like v0.63.1 -> v1.0.0-rc1.

**Comment by tfiduccia** [comment]
Version - v1.0.0-rc2
Verified fixed
