### ISSUE TITLE
DNS Issues when switching kube-proxy from iptables to IPVS mode

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#28204]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
- have workloads deployed that both make use of host networking and do not make use of it
- update cluster yaml to use IPVS mode for kube-proxy and save the configuration

**Result:**
After switching from iptables to IPVS for kube-proxy, any pods and containers without host networking will no longer have functioning DNS and require a restart to resolve the DNS issue. Pods/containers that use host networking do not experience DNS issues after switching to IPVS mode and do not require restarts to continue functioning as intended. 

Is this an intended behavior?

**Environment information**
- Rancher version: v2.4.5
- Kubernetes version: v1.15.12
- Installation option (single install/HA): HA

gz#11282

gz#11806

**Comment by superseb** [comment]
@rosskirkpat Please provide steps to reproduce. I ran v2.4.5 with v1.15.12-rancher2-3 and v1.18.6-rancher-1-1, steps taken:

- Ran the DNS troubleshooting DaemonSet successfully (from https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/)
- Created 3 pods with `HostNetwork: true`
- Edited the cluster, added `proxy-mode: ipvs` to the `extra_args` of the `kubeproxy` service.
- Confirmed kube-proxy was recreated with the correct mode by checking the logs
- Ran the DNS troubleshooting again, no change from the successful run earlier, ran successful again

**Comment by rosskirkpat** [comment]
Closing this issue as it appears to be specific to a customer's environment and network configuration.
