### ISSUE TITLE
Is Rancher's logging system useless because of its multiline handling?

### ISSUE THREAD

**Issue by hatharom** [rancher/rancher#28215]
version: all of them

I have setup the logging collector through the UI. I send the data to ES.

However ton of my components has multiline stacktrace. And it seems Rancher cant handle it.
Because of this Rancher's logging system is useless, I dont want to have 50-60* times more log entry than necessary. 

There are ton of issue about this on the web, without any solution:

https://github.com/rancher/rancher/issues/21900
https://github.com/rancher/rancher/pull/22196
https://forums.rancher.com/t/updating-rancher-fluentd-logging/13382
https://stackoverflow.com/questions/57003029/how-to-config-rancher-to-send-multiline-logs-to-elasticsearch
https://forums.rancher.com/t/how-to-collect-multi-line-logs-like-java-stack-trace-logs-and-ship-it-to-elasticsearch/14795/2

So I thought that providing some additional Fluentd config in the 'edit as File' section will solve this however this section doesn't accepts anything. Not even a basic 'match' config :   "Something’s not quite right. Check your inputs"
like here:
https://forums.rancher.com/t/need-help-in-advanced-cluster-logging-configuration/16409

This whole rancher logging stuff seems broken.

**Comment by bilaltahirx** [comment]
Any update ?

**Comment by leodotcloud** [comment]
Related https://github.com/rancher/rancher/issues/21900
