### ISSUE TITLE
Two percent "%" characters appear under the "Maximum Worker Nodes Unavailable" setting in RKE template. 

### ISSUE THREAD

**Issue by kcalmond** [rancher/rancher#28210]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create an RKE Template from an existing cluster. Go back to Global, select Tools->RKE Templates. Click on v1 of the newly created template. UI shows (default) setting as "10%%"

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher | v2.4.5
User Interface | v2.4.28
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher43

- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Infra Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): v1.18.6-rancher1-1

```
screenshot attached
```

- Docker version (use `docker version`):

```
(paste the output here)
```
<img width="367" alt="image" src="https://user-images.githubusercontent.com/12177199/89239477-26311c80-d5ae-11ea-8603-ddb9d9888b0b.png">

**Comment by dennislaf** [comment]
We are also seeing the same issue. 

the template stores "10%", when you try to upgrade it adds % to "10%" making "10%%" which fails validation, upgrade again and it becomes "10%%%

![image (9)](https://user-images.githubusercontent.com/8419809/92145557-04f66280-edde-11ea-8b3f-3440777c951f.png)

**Comment by stefanlasiewski** [comment]
This is an old bug, but I wanted to point out that it should get fixed in related to https://github.com/rancher/dashboard/issues/4870
