### ISSUE TITLE
[Logging v2] - 502 When installing from Dashboard

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28225]
**What kind of request is this:**
bug

**Steps to reproduce:**
- Install Rancher HA k8s. 
- Login to Dashboard and in the local cluster click Apps from the Global Nav Bar
- Select `rancher-logging` app
- Follow the wizard

**Result:**
Error in the UI

`POST /v1/catalog.cattle.io.repos/default/dev-charts?action=install`
```json
{
    "type": "chartInstallAction",
    "charts": [{
        "chartName": "rancher-logging",
        "version": "3.4.000",
        "releaseName": "rancher-logging",
        "values": {
            "elasticsearch": {
                "enabled": true,
                "index_name": "izclustertest",
                "host": "<ip>",
                "port": "9200"
            }
        }
    }]
}
```

Response:

```html
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.17.10</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

Related: rancher/rancher#27935

**Environment information**
- Rancher version: `master-head (08/04/2020)` _447c3b490_
- Installation option: HA k8s

**Comment by cbron** [comment]
Does this have latest master-head  ? It has dev-charts in there, don't think that should be in-use anymore.

**Comment by sangeethah** [comment]
@cbron https://github.com/rancher/rancher/issues/28229

**Comment by izaac** [comment]
This is working in `master-head (08/05/2020)` _65a2b808c_
