### ISSUE TITLE
Launching kubectl fails with a blank screen/error

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#28223]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a HA setup using master-head with ECM disabled
2. Create a user cluster 
3. Launch kubectl on the user cluster and local cluster

**Result:**
kubectl fails to launch as below:
**User cluster:**

![Screen Shot 2020-08-04 at 11 06 06 AM](https://user-images.githubusercontent.com/18536626/89328684-99846e00-d642-11ea-8999-3da2e4758bcd.png)

**Local cluster**

![Screen Shot 2020-08-04 at 11 08 21 AM](https://user-images.githubusercontent.com/18536626/89328859-d7819200-d642-11ea-9fcd-db69865faeea.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head(3d7c3b3c1)
- Installation option (single install/HA): HA

Kubernetes Version: V1.18

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `d19f179c4`**

- Launch kubectl fails to load. Same issue as the original error is seen.
- Reopening the issue

**Comment by izaac** [comment]
This is not yet merged.

**Comment by izaac** [comment]
Rancher version `master-head (08/20/2020)` _56ecd6510_ 

In an HA setup I can get the kubectl console from the emberUI in the downstream clusters but the `local` cluster shows `Closed Code: 1006`

**Comment by jiaqiluo** [comment]
on rancher:`master-f7f8e8bb0649e6f163bd6ba2118622a9889236ce-head` HA setup:
- admin can launch kubectl shell on Embler UI, and open the dashboard 
- but cluster member can NOT do neither 

on rancher:`master-4ff98cc603ea47528062ee6994d2a5e58a29ed5a-head` HA setup:
- even admin can NOT launch kubectl shell on Embler UI, or open the dashboard

**Comment by prachidamle** [comment]
For admin user, kubectl shell is working fine on an HA setup launched using  master-ed2749841db0b3323e1e284ca3d2388a53f4bafd-head

For cluster-member, it is not working with this latest version yet

**Comment by sowmyav27** [comment]
**On master-head - `0ccce450`**

Cluster owner is able to do a kubectl shell through ember UI and dashboard.

**Comment by prachidamle** [comment]
So is a  cluster-member allowed to be able to use shell to the cluster? Or is this working as expected now? @sangeethah @deniseschannon @maggieliu?

**Comment by maggieliu** [comment]
@prachidamle in 2.4's ember UI, cluster member is able to launch shell and at least execute kubectl get nodes.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `7154bdb3b`**

Cluster member is NOT able to access kubectl (downstream user cluster)
<img width="1322" alt="Screen Shot 2020-09-24 at 5 24 15 PM" src="https://user-images.githubusercontent.com/26032343/94213124-f1916100-fe8a-11ea-9030-c5d90052032f.png">

**Comment by sowmyav27** [comment]
**On master-head - commit id: `9de5a850`**

- Cluster owner and CLuster member users are able to access kubectl
- But project member/owner/read only users --> Kubectl launch fails.

<img width="1319" alt="Screen Shot 2020-09-25 at 7 59 30 PM" src="https://user-images.githubusercontent.com/26032343/94328767-04c72e00-ff6a-11ea-8a34-f0c3fe9c119b.png">

Reopening the issue

**Comment by sowmyav27** [comment]
**On master-head - commit id: `c3bc230f`**

- Cluster owner/Cluster member/ project member/owner/read only users are able to access kubectl
-  project member/owner/read only users are able to access resources in the namespaces the users have access to
