### ISSUE TITLE
Default chart repo in dashboard still points to dev-charts

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#28229]
rancher/rancher:master-head a9c601609 

* Navigate to dashboard for the cluster
* The default repo in the cluster is `https://dev-charts.rancher.io`

Expected:
* The default chart should be `https://charts.rancher.io`

**Comment by maggieliu** [comment]
Need to update: https://github.com/rancher/rancher/blob/master/pkg/data/dashboard/repo.go#L19

**Comment by cbron** [comment]
New master-head image is live

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 65a2b808c)

Default chart in dashboard is pointing to https://charts.rancher.io
