### ISSUE TITLE
Volumes not listed in Storage Pool after Adding

### ISSUE THREAD

**Issue by ColtonProvias** [rancher/rancher#2822]
Upon trying to add a volume to the storage pool, it is not listed.  A JSON response is returned showing the request having gone through.  Refresh does not list it either.

**Comment by sangeethah** [comment]
This is delicate of #2763

**Comment by deniseschannon** [comment]
If you refresh, it should list it.

**Comment by ColtonProvias** [comment]
Even after refresh, it still does not list.

**Comment by deniseschannon** [comment]
@ColtonProvias Apologies, I thought it was a different issue where sometimes we see the volume being created (when used in a service) and the UI needs to be refreshed to see the volume.  

I'm going to close this issue in favor of #2763 as that is the same.
