### ISSUE TITLE
service link alias names (aka "service1 as database") and external stacks (otherstack/service1) are missing in the new UI

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2823]
Server version - v0.47.0

Create a service S1 add a service link to another service S2  by providing a name.

service link name does not show up in the service detail page/ service summary page.

<img width="1246" alt="screen shot 2015-11-25 at 11 55 14 am" src="https://cloud.githubusercontent.com/assets/4266958/11408071/bb006d50-936b-11e5-8ef5-3cab9658cefe.png">

<img width="1263" alt="screen shot 2015-11-25 at 11 54 56 am" src="https://cloud.githubusercontent.com/assets/4266958/11408072/c062bb0e-936b-11e5-95cb-d0830890c37c.png">

**Comment by deniseschannon** [comment]
Also, the service links don't show if the service is in another stack. This would be very helpful to display external links.

**Comment by deniseschannon** [comment]
To be more explicit on what is missing:

Using the UI, you'd select `test1` and place the `test1.example.com` in the name column.
 
![screen shot 2015-11-30 at 11 04 20 am](https://cloud.githubusercontent.com/assets/11410997/11511240/c9e5cc10-981c-11e5-9eca-07fb1a234fab.png)

n the old UI, it would show "test1 as test1.example.com" or some kind of text that would indicate what the "Name" is. 

In the rancher-compose, it would look like
```
links:
- test1:test1.example.com
```

But in the new UI, it just shows up as `test1`.

Similar request is related to external links (aka links to services in other stacks).

Old UI
`otherstack/service1`
New UI
`service1`

It is missing the `otherstack/` part in the link section, which is extremely helpful. 


`

**Comment by kaos** [comment]
+1

**Comment by tfiduccia** [comment]
Version - master 5-27
Missing a couple of things

- [ ] As should be lower case
![image](https://cloud.githubusercontent.com/assets/11514927/15622852/f5e7fafe-2421-11e6-916d-84bc17dba28d.png)

- [ ] When I link a service that exist in another stack it should be `<ExternalStackName>/<LinkedService> as <AsName>`.

**Comment by tfiduccia** [comment]
Version - master 6.9
Verified fixed
