### ISSUE TITLE
[controlPlane] Failed to upgrade Control Plane: [[[controlplane] Error getting node rancher-controller1: "rancher-controller1" not found]]

### ISSUE THREAD

**Issue by menih** [rancher/rancher#28235]
Simplest deployment - single node in VMware.
Define cloud vSphere, node template, using boot2docker ISO legacy, with latest image (left black)

Getting error:
[controlPlane] Failed to upgrade Control Plane: [[[controlplane] Error getting node rancher-controller1: "rancher-controller1" not found]]

Who is producing this error? Is it coming from node itself? from rancher? the IP address is known to rancher... because I see it on the UI.

**Environment information**
Rancher | v2.4.5
User Interface | v2.4.28
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher43

**Comment by menih** [comment]
Anyone? I am desperate  ...

**Comment by superseb** [comment]
Please supply full logging output from the `rancher/rancher` container.

**Comment by menih** [comment]
I figured it out... it seems that if nodes cross network broadcast domain (VLANs in our case), even if routable, rancher fails. Wonder why that is... probably some broadcast related implementation.

**Comment by zopar** [comment]
I have the same problem, how did you solved it?

**Comment by menih** [comment]
All deployments need to be in the same broadcast domain... In another word,
your rancher controller and nodes is on the same subnet.
