### ISSUE TITLE
Cluster creation and cluster ID request are not transactional

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#28239]
When creating a cluster the cluster ID is not immediately available and we need to wait for the state to be written to etcd before we can get and use it.  The workaround is to add a `sleep()`.

The expected behavior would be to perhaps return the clusterID when the creation 'transaction' had completed.

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
The code can be found here: https://github.com/opennode/waldur-mastermind/blob/develop/src/waldur_rancher/backend.py#L103-L126
Below is the function where we see the failure if there is no `sleep`.
```
    def create_cluster(self, cluster):
        mtu = self.settings.get_option('default_mtu')
        private_registry = None
        private_registry_url = self.settings.get_option('private_registry_url')
        private_registry_user = self.settings.get_option('private_registry_user')
        private_registry_password = self.settings.get_option(
            'private_registry_password'
        )
        if private_registry_url and private_registry_user and private_registry_password:
            private_registry = {
                'url': private_registry_url,
                'user': private_registry_user,
                'password': private_registry_password,
            }


        backend_cluster = self.client.create_cluster(
            cluster.name, mtu=mtu, private_registry=private_registry
        )
        self._backend_cluster_to_cluster(backend_cluster, cluster)
        # as rancher API is not transactional, give it 2s to write cluster state to etcd
        time.sleep(2)
        self.client.create_cluster_registration_token(cluster.backend_id)
        cluster.node_command = self.client.get_node_command(cluster.backend_id)
        cluster.save()
```
**Result:**
Without the sleep, the return has a blank ID

**Comment by vincent99** [comment]
This is not true at all as stated.  The immediate response to POSTing a cluster (or any other resource) is a copy of the new resource, and includes the id.

The problem you actually have is that getting that response does not mean the cluster is "ready to use".  API operations are asynchronous and you need to wait until they are finished to do things that depend on them.  Sleep 2 just happens to (sometimes) be long enough for that to have occurred.

For most resources you'd wait for the state to be "active" or transitioning to be "no", but in this case the cluster will stay pending until it has nodes.

So you want to poll (or websocket subscribe) looking for the `InitialRolesPopulated` condition on the cluster before trying to create other resources which refer to it. You don't actually have access to create a registration token for this cluster until that has occurred.

**Comment by Tejeev** [comment]
Thank you @vincent99,
I think this is what the customer meant when they said it was not transactional and if I remember correctly from our call, it actually would not return a little while, though I could be mistaken.  I've passed on what you've suggested and hopefully, this will shed some light better practices
