### ISSUE TITLE
User fails to deploy clusters on an upgraded setup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28254]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy rancher: v2.3.5
- Deploy a couple of DO rke clusters
- Upgrade to master-head and set `--features=multi-cluster-management=true` in the docker run command
-  k8s versions dropdown was blank in this case, refreshed KDM
- Deploy a one node DO RKE cluster.
- Cluster fails to come up error seen `Failed while: Wait for Condition: InitialRolesPopulated: True`

**Expected Result:**
Cluster should get deployed successfully.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `65a2b808c`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE DO
- Kubernetes version (use `kubectl version`):

```
1.18
```

**Comment by aaronRancher** [comment]
Was unable to reproduce issue with Rancher server `rancher\rancher:master-head` `version 5e1b21b93`

Steps:
Bring up a v2.3.5 setup
Provision 3 DO RKE clusters. (1 node, all roles)
Upgrade setup to master-head, `version 5e1b21b93`
Provision a new DO RKE cluster

Result:
Cluster was provisioned successfully
