### ISSUE TITLE
[go-rancher]  documentation

### ISSUE THREAD

**Issue by boedy** [rancher/rancher#2825]
First off all I would like to say I'm very impressed with the rancher project. When I started playing with it this week I was really amazed how easy it was to setup a project of mine.

I couldn't find anything about autoscaling using rancher. I guess this could be achieved quitte easily by writing a a program using the go-rancher client. I've been digging through the code though, but I find it hard getting started.

Is there any documentation somewhere?

Or maybe an other tool which could help me figure out how to use the GO client.

**Comment by emcniece** [comment]
Did that "bigger picture" have any go-rancher documentation?
