### ISSUE TITLE
Logging in as type "Admin" shows all stacks from all environments

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2826]
Rancher 0.47.0 

We have several environments.  Stacks were displaying correctly in 0.46.0  After upgrading to 0.47.0, things changed.

After logging in (using LDAP) and being placed in the Default environment, ALL stacks from ALL environments are shown in the UI.  Stacks from other Environments are apparently empty (though they do have services).

If I then change to another Environment, the correct stacks are shown, and if I change back to Default, then I see the correct stacks, with the correct services.

If I log out and log in again, then again I can see ALL stacks, not just from Default, though again the foreign stacks are displayed as empty.

**Comment by sshipway** [comment]
Note: I am logging in with an Admin account; other users seem to see only the Stacks for which they would normally have visibility.

**Comment by deniseschannon** [comment]
I have reproduced this issue.

Steps to Reproduce:
1. Enable authentication. 
2. Have 2 environments with 1 stack in each one.
3. Log out and log back in as Admin

Result: In the environment, you will see both stacks from both environments

Expected Result: You will only see the stacks in the environment you are logged in as. 

Note: This is logging in as an Admin. Logging in as a user, you get this issue: https://github.com/rancher/rancher/issues/2861

**Comment by deniseschannon** [comment]
Verified with v0.49.0-rc3, UI v0.70.0

**Comment by andyshinn** [comment]
I'm still seeing this on v0.49.1. FWIW, I've also seen similar behavior on the API keys page (showing every API key in Rancher, not just the current environment). Not hurting functionality. But anything I can do to debug?

**Comment by deniseschannon** [comment]
Can you check that your UI tag is updated? Click on the cow and show the UI version. Sometimes in upgraded setups, the UI stays the old tag.

**Comment by andyshinn** [comment]
Ah ha, I probably never closed this tab. It said:

```
Rancher	v0.49.1
Cattle	v0.121.0
User Interface	v0.68.0
Rancher Compose	v0.6.1
```

I forced a refresh of this tab and now it is:

```
Rancher	v0.49.1
Cattle	v0.121.0
User Interface	v0.71.0
Rancher Compose	v0.6.1
```

I logged out and in a couple times and it seems to be fine now! Thanks!
