### ISSUE TITLE
Aarch64  Architecture Server Deployment Store Application Failures

### ISSUE THREAD

**Issue by kerven88** [rancher/rancher#28262]
Hello sir, it's a pleasure to use the rancher product, but I have a question that I need your help with.

**Environment information**
OS version：Linux master 4.18.0-80.7.2.el7.aarch64 #1 SMP Thu Sep 12 16:13:20 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
Rancher version： rancher/rancher:v2.4.4-linux-arm64
Installation option： docker run -d --restart=unless-stopped -p 8080:80 -p 8443:443 -v /data/rancher:/var/lib/rancher/ -v /var/log/rancher/auditlog:/var/log/auditlog -e AUDIT_LEVEL=3 rancher/rancher:v2.4.4-linux-arm64

**Cluster information**
- Cluster type：Infrastructure Provider
- Machine type：4core/8G Memory
- Kubernetes version：Client Version: v1.18.6     Server Version: v1.18.6

- Docker version (use `docker version`):
Server Version: 18.09.9
Architecture: aarch64

----------------------------------------------------
1）Deploying services through your own app store，fails with the following error logs：
Failed to install app grafana. time="2020-08-06T07:34:36Z" level=error msg="failure getting variant" error="open /proc/cpuinfo: no such file or directory" Error: error while running post render on files: error while running command /kustomize.sh. error output: /kustomize.sh: line 5: /usr/bin/kustomize: cannot execute binary file: Exec format error : exit status 126
![image](https://user-images.githubusercontent.com/51351006/89506494-c5981e80-d7fd-11ea-94ca-4ccc517d07be.png)

2）But it can be deployed successfully through Helm command-line operations.
> helm install grafana grafana -n test
![image](https://user-images.githubusercontent.com/51351006/89506637-0001bb80-d7fe-11ea-99dd-b8a98984a563.png)

It looks like this error is the wrong version of kustomize, how do I handle this?

**Comment by hlyani** [comment]
The kustomize used by the rancher is 32-bit, just replace it with the latest arm64.It`s ok.

link:
https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.0.5/kustomize_v4.0.5_linux_arm64.tar.gz
