### ISSUE TITLE
Error processing clusterTemplate answers

### ISSUE THREAD

**Issue by hedgepigma** [rancher/rancher#28263]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.5` UI: `v2.4.28` |
|Route|`undefined`|

Using rkeTemplate to create a new cluster find error like “Error processing clusterTemplate answers” after clicking the save button
Is there something wrong with my configuration？

**Comment by sjaiser** [comment]
I have hit the same error. After some trial and errors with different created templates I got it running.

Here my setup - Rancher v2.4.8
I have a running cluster and created a rke template from it keeping all values from being changed to be on the safe side. I then created a new cluster with this template. This worked fine.
Next I created a new revision of the template with the possibility to change quite a few things, like PSP and S3 Bucket. Then I tried to install the template on the new cluster and in the same step changed the before locked values in the same step. Here I got the same error.
I then tried to install the new template on the newly created cluster without changing the before locked values in the same step. This worked. 
Next step was to edit the newly created cluster and I could now change the new variables...

So my guess is that you can't unlock values with a new revision of a template anfd change those values in the same step.
