### ISSUE TITLE
JS error when enabling/disabling json parsing in custom logging configuration form

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#28264]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Go to Tools -> Logging
* Switch to edit as file
* Try to enable/disable "Enable JSON Parsing"

<img width="1267" alt="Bildschirmfoto 2020-08-06 um 16 22 44" src="https://user-images.githubusercontent.com/243056/89543765-9e435080-d801-11ea-9f15-d010c51abe49.png">

**Result:**

Change has no effect. The following JS error is thrown:

```
metal.js:3001 Uncaught TypeError: Cannot read property 'isDestroyed' of undefined
    at tt (metal.js:3001)
    at t.r.<computed> [as __UPDATE__ember15967235964031178298448423__] (glimmer.js:659)
    at n.f.CoreView.extend.<computed> [as __PROPERTY_DID_CHANGE__ember15967235964031062335139214__] (glimmer.js:1755)
    at J (metal.js:1072)
    at tt (metal.js:3047)
    at n.change (glimmer.js:1912)
    at n.trigger (core_view.js:69)
    at n [as trigger] (utils.js:365)
    at e.n._run (backburner.js:1066)
    at e.n._join (backburner.js:1042)
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

**Comment by superseb** [comment]
Another example of https://github.com/rancher/rancher/issues/28060

**Comment by albertoeks** [comment]
I've been facing the same issue, is there some way to work around it? At least while this issue isn't fixed. Thanks in advance!

**Comment by bashofmann** [comment]
Rancher 2.5 includes a completely new, way more flexible logging integration. With this you won't run into this bug. https://rancher.com/docs/rancher/v2.x/en/logging/#changes-in-rancher-v2-5

As a workaround in 2.4 you could change the enable json logging flag through the API. In the API Explorer go to `/v3/clusters/CLUSTERID/clusterloggings`, navigate to your logging configuration subresource by clicking on its id in the data list and edit it.

**Comment by albertoeks** [comment]
That's awesome! Thanks for your quick response. I'm gonna change through the API for now and surely update to version 2.5 quite soon.
