### ISSUE TITLE
Node agents and cluster agents do not get upgraded on a rancher upgrade to master

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28267]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy rancher: v2.3.6
- Deploy an RKE cluster - 1 node
- Upgrade rancher server to master-head using flags - `--features=multi-cluster-management=true`
- The cattle-node-agent and cattle-cluster-agent are still seen in v2.3.6

**Expected Result:**
cattle-node-agent and cattle-cluster-agent should get upgraded to master-head

**Other details that may be helpful:**
- this has happened on an upgrade from 2.4.5 to master-head also
- Edit and upgrade k8s of the cluster

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `9b0dd20b7`
- Installation option (single install/HA): Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE do
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 8d9cedde9`

Steps:
Deploy rancher: v2.3.6
Deploy an RKE cluster - 1 node
Upgrade to master-head

Result:
The cattle-node-agent and cattle-cluster-agent are upgraded to master-head
<img width="967" alt="Screen Shot 2020-08-31 at 10 00 56 AM" src="https://user-images.githubusercontent.com/57409052/91746085-e63f6400-eb70-11ea-880d-6fd8796fb7af.png">
