### ISSUE TITLE
Fix Docker install to run pods

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#28279]
Currently, docker install doesn't work with the latest EKS operator because of the inability to create pods.

After this is fixed, EKS Operator and Global DNS should be able to work.

Should we expose Global DNS? - TBD

Minimum is that we should test EKS operator works on docker install and docker upgrade. There will be new instructions

**Comment by cbron** [comment]
`--priveleged` now needs to be added to any `docker run rancher/rancher` command. @sowmyav27 / @sangeethah I'm assuming there will be some test automation to update.

**Comment by sowmyav27** [comment]
**On master-head commit id: `82695bc75ad`**

- Bring up single node rancher install using `docker run -d --privileged --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:master-head`
- Deploy an EKS cluster (all default values selected from the UI) after the user has entered aws cloud creds.
- EKS cluster is seen in `Provisioning` state and error in eks-controller logs show
- `E0904 20:59:04.484217       1 controller.go:166] error syncing 'cattle-global-data/c-qnv6v': handler eks-controller: error creating stack with service role template: error creating master: RequestError: send request failed`
- In another master-head setup, error in eks-controller logs show
```
caused by: Post https://cloudformation.us-east-2.amazonaws.com/: dial tcp: lookup cloudformation.us-east-2.amazonaws.com on 10.43.0.10:53: read udp 10.42.0.2:55383->10.43.0.10:53: i/o timeout, requeuing
time="2020-09-04T20:57:16Z" level=info msg="Bringing up vpc"
E0904 20:57:46.608267       1 controller.go:166] error syncing 'cattle-global-data/c-m9w2f': handler eks-controller: error creating stack with VPC template: error creating master: RequestError: send request failed
caused by: Post https://cloudformation.us-east-2.amazonaws.com/: dial tcp: i/o timeout, requeuing
time="2020-09-04T20:57:46Z" level=info msg="Bringing up vpc"
E0904 20:58:56.491749       1 controller.go:166] error syncing 'cattle-global-data/c-qlbn2': handler eks-controller: error creating stack with VPC template: error creating master: RequestError: send request failed
caused by: Post https://cloudformation.us-east-2.amazonaws.com/: dial tcp: lookup cloudformation.us-east-2.amazonaws.com on 10.43.0.10:53: read udp 10.42.0.2:35666->10.43.0.10:53: i/o timeout, requeuing
time="2020-09-04T20:58:56Z" level=info msg="Bringing up vpc"
```

**Comment by sowmyav27** [comment]
**Validated** on master-head commit id: `343b8e19c7d`**

- Bring up rancher using `docker run -d --privileged --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:master-head`
- Deploy an EKS cluster - select existing subnets and security groups 
- Deploy it with one nodegroup and 2 nodes.
- EKS cluster deploys successfully and comes up Active.
