### ISSUE TITLE
RFE: Improved Certificate Handling between Rancher Server and Downstream Clusters

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#28276]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request/Enhancement

**Steps to reproduce (least amount of steps as possible):**
Currently, when changing or rotating certificates on Rancher Server Web Certificates the process is v. manual and results in a lot of situations where Rancher cannot communicate with the downstream

For example, here are the steps for changing from Self-Signed to Internal CA signed:

1. Get rkestate
2. Snapshot rke
3. Delete cert-manager namespace
4. Prepare certs incorrect format
5. Delete existing tls secret
6. Deploy tls secrets
7. Run helm upgrade
8. Restore communication between management and downstream with a token and running cluster-agent-tool script

While it may be that some of these steps still need to be run for changing between styles of certificate mgmt (i.e. helm upgrade to change the answers), it would be best if we could at least try and start automating some of the more obvious things. 

Specifically, Step8 is the most manual step here, customers and support rely on the cluster-agent-tool script to work through these issues which works great but the functionality should start being included with the product so we don't have to rely on separate scripts that some may have not heard of. 

The script pretty much just pulls the deployment from Rancher Server and then and will redeploy the cattle-cluster/cattle-node agents downstream - https://github.com/rancherlabs/support-tools/tree/master/cluster-agent-tool

This functionality would drastically reduce the amount of certificate rotation incidents and trouble we see in Support and provide better UX for customers

gz#11602

**Comment by superseb** [comment]
This is tracked in https://github.com/rancher/rancher/issues/14731

**Comment by leflambeur** [comment]
Closing in favour
