### ISSUE TITLE
rancher-ui "upgrade service" does not remember labels

### ISSUE THREAD

**Issue by jippi** [rancher/rancher#2828]
1) For a service (through the UI) I add the label `io.rancher.container.hostname_override=container_name` 
2) Start it
3) Pick "upgrade" and go to "labels" - the `io.rancher.container.hostname_override` label is gone

Running rancher docker images from <24h ago (25th of nov)

**Comment by sangeethah** [comment]
This issue is also tracked in #2551 and #2550.

**Comment by deniseschannon** [comment]
Closing in favor of #2551, #2550 and #2342.
