### ISSUE TITLE
Docs build example for rancher-compose creates standalone containers.

### ISSUE THREAD

**Issue by keras** [rancher/rancher#2829]
While using the example flask app from http://docs.rancher.com/rancher/rancher-compose/build/ I have noticed that the containers used for building the actual stack are kept in the "Standalone Containers" -section:
![screenshot from 2015-11-26 13-37-53](https://cloud.githubusercontent.com/assets/1126171/11422290/6a9176ce-9443-11e5-8693-cf9a0108ab97.png)

Is there some automatic mechanism for cleaning such containers from hosts?

**Comment by deniseschannon** [comment]
These standalone containers are not from the S3 builds. These are Docker containers that were already on your host before you added the host into Rancher. 

There are no containers that are built that are outside of the stack. 

Here are the docs on how we sync with containers that were run natively in Docker. 
http://docs.rancher.com/rancher/native-docker/

**Comment by keras** [comment]
I haven't created a single container outside of stacks (except rancher/agent).

Every time I deploy stack with some `build: ./something` docker-compose -statements I get new stopped standalone containers. Please try it yourself using the http://docs.rancher.com/rancher/rancher-compose/build/ example.

**Comment by deniseschannon** [comment]
I used the same example (before responding) and don't have any stopped standalone containers after the service is up and running.

These are containers in Docker that are not created by Rancher. When you do a `docker ps -a` on your host, what are the time stamps on the containers with the same name? What else was running in Docker before you added it to Rancher?

**Comment by keras** [comment]
I re-ran the test with the flask test. And again I see one new standalone container named 'romantic_ardinghelli'.

Container information displays following info:
```
Info
Host IP <redacted>
Container IP 172.17.0.9
Image ab2ed35c0690bed5c967c16eb35a9dd706c64b1c2d19c46f317ba03c7341c18a
Entrypoint None
Command /bin/sh,-c,pip install -r requirements.txt
```

```ShellSession
$ sudo docker ps -a -f 'name=romantic_ardinghelli'
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
07895bf617e9        ab2ed35c0690        "/bin/sh -c 'pip inst"   2 minutes ago       Exited (0) 2 minutes ago                       romantic_ardinghelli
```

There was nothing running on the machine before I installed rancher, it was totally clean ubuntu LTS installation with Docker 1.9.1 dedicated for rancher.

**Comment by keras** [comment]
Actually it seems that this issue is now gone. I upgraded rancher/server and it seems to be fixed now. I had a week old server last time but now after the upgrade it seems to be fixed :)

**Comment by deniseschannon** [comment]
Okay, cool. I was testing on v0.47.1 and rancher-compose v0.5.3.

**Comment by keras** [comment]
Hi,

This issue is back. Using versions:
```
Rancher	v0.49.0
Cattle	v0.119.0
User Interface	v0.68.0
Rancher Compose	v0.6.0
```

I created a vagrant environment to reproduce this, see following `Vagrantfile`:
```ruby
# Ubuntu based vagrant box

base_commands = [
  "sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D",
  "echo deb https://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list",
  "sudo apt-get update",
  "sudo apt-get install -y docker-engine",
]

machines = [
  {
    :name => "rancher-server",
    :memory => 1500,
    :cpus => 2,
    :commands => [
        "docker run -d --restart=always -p 8080:8080 rancher/server:latest",
    ],
  },
  {
    :name => "rancher-node",
    :memory => 1024,
    :cpus => 2,
    :commands => [],
  },

]

Vagrant.configure(2) do |config|
  machines.each_with_index.each{|machine, n|
    name = machine[:name]

    config.vm.define name do |conf|
      conf.vm.box = "ubuntu/trusty64"
      conf.vm.provider "virtualbox" do |v|
        v.memory = machine[:memory]
        v.cpus = machine[:cpus]
      end

      ip = "172.19.8.#{n+100}"
      conf.vm.network "private_network", ip: ip
      conf.vm.hostname = name

      provision_cmd = (base_commands + machine[:commands]).join("\n")

      conf.vm.provision "shell", inline: provision_cmd
    end
  }

end
```

Steps to reproduce:
- Copy above Vagrantfile to somewhere
- Run `vagrant up` and wait for the machines to wake up
- Open http://172.19.8.100:8080/
- Open shell to rancher-node -server `vagrant ssh rancher-node` and add it as custom host to the rancher environment.
- Create API key
- Deploy attached stack [flask.zip (the flask example)](https://github.com/rancher/rancher/files/56650/flask.zip) e.g. `RANCHER_URL=http://172.19.8.100:8080/v1/projects/1a5 RANCHER_ACCESS_KEY=19CD95129B9E84A03AB8 RANCHER_SECRET_KEY=R8MFxH4wVHFro4civ8FHAZDsG5nRJx78ppuS67um rancher-compose up`

After the stack has been deployed there will be one leftover stopped standalone instance with command `/bin/sh -c pip install -r requirements.txt`.

**Comment by deniseschannon** [comment]
I was able to reproduce your issue. My sense is that something happened with the 1.9.x changes in Docker, which has caused this example (which used to be on the Docker site and I can no longer find) to stop working. I definitely was able to launch the example previously using older versions of Docker.

Typically, S3 shouldn't cause having standalone containers. 

I'll look into updating the docs for another example to post. :)

**Comment by deniseschannon** [comment]
Okay, there is definitely something strange going on. When I do a `docker-compose up` with the files, it's fine, but if I try to run it using `rancher-compose up`, the host goes into reconnecting mode when trying to launch the `web` service. 

Since the host goes into reconnecting state, sometimes containers are launched but then they get stuck/removed.

I'm going to update this issue to look into why the example is causing hosts to go into reconnecting state. When that's fixed, I believe these standalone containers will not be an issue.

**Comment by deniseschannon** [comment]
As of v0.51.0 and v0.7.0, this has been fixed and no longer results in having stopped containers in the background.
