### ISSUE TITLE
Validate 0.6.2 SUC 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#28306]
On fresh installs of rancher server , validate upgrade of imported k3s clusters work with 0.6.2 SUC.

On upgraded rancher server installs , validate upgrade of imported k3s clusters continue to work and uses 0.6.2 SUC.

Related PR - https://github.com/rancher/system-charts/pull/310/files

**Comment by rancher-max** [comment]
#### Validated both scenarios using both k3s and rke2

- Uses system-upgrade-controller of v0.6.2
- Upgrade scenario upgrades the system-upgrade-controller version to v0.6.2 as expected
