### ISSUE TITLE
[UI] All stacks initially load collapsed; should be a user preference

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#2831]
In the v.0.47.0 UI, all stacks are showing collapsed on initial load. I previously found it convenient to have a heads-up view of all the services within all stacks immediately on load. But then again, I don't have that many stacks.
An "expand all / collapse all" button would be convenient in this case (and perhaps its state remembered as user preference).

**Comment by vincent99** [comment]
The state is remembered for each stack now.

**Comment by ebr** [comment]
Indeed it is! sorry, I did not clue in to that at first, d'oh. :+1:
