### ISSUE TITLE
[2.4] Review Default k8s versions for hosted k8s providers (EKS)

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28317]
Review the latest k8s versions supported by the cloud providers and update accordingly.

**Comment by cbron** [comment]
@maggieliu is this for KE v2 ? If so what priority ?

**Comment by maggieliu** [comment]
Low priority, but something we need to check before 2.5 GA. I think GKE and AKS are both pulling the latest k8s versions dynamically and EKS is the only one that requires manual update of AMIs.

**Comment by maggieliu** [comment]
AMI IDs: https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

**Comment by maggieliu** [comment]
But can be easier to retrieve the AMI IDs this way: https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html

**Comment by maggieliu** [comment]
Previous PR for updating: https://github.com/rancher/kontainer-engine/pull/233

**Comment by deniseschannon** [comment]
FYI, there is a script that could be used to get the list of AMI IDs: https://github.com/rancherlabs/eio/issues/256#issuecomment-694528476

**Comment by deniseschannon** [comment]
We no longer need to actively maintain AMI IDs for 2.5+ as we have moved to EKS v2. 

For any EKS v1 clusters, upgrades and edits only require the k8s version and not the specific AMIs. 

This is only applicable to maintaining 2.3/2.4 going forward so I've moved this to 2.4.9.

**Comment by deniseschannon** [comment]
This is only relevant for 2.4.

**Comment by cbron** [comment]
@deniseschannon  I think this is typo:

> For any EKS v1 clusters, upgrades and edits only require the k8s version and not the specific AMIs.

Believe you meant for EKS v2 clusters ? We would still need to update AMI's in Rancher for 2.4/KEv1. 

If thats true, @paynejacob can you handle the updating of AMI's for release/v2.4 branch to support KEv1. PR's above are only for CN regions, and they also need some adjustments but we'll handle that separately.

**Comment by deniseschannon** [comment]
That wasn't a typo but an explanation of why we didn't need the AMI updates for Rancher v2.5.

But yes, this ticket is to *only* track updating for release/v2.4 in rancher/kontainer-engine to get updated for the latest AMIs since it is static. 

EKS v2 is all dynamic so we no longer need to track the individual AMIs. 🎉

**Comment by paynejacob** [comment]
latest2, latest-2.4, latest-2.5 ui builds are ready

**Comment by DoNotSayYes** [comment]
**Tested on latest 2.4-head - commit** [71e29c6](https://github.com/rancher/ui/commit/71e29c6afc6ec44506ef8ff139f5b525080f50e0)

An error message could be encountered when testing CN regions
![image](https://user-images.githubusercontent.com/57614736/96410894-34d8b880-121a-11eb-88f8-f6092c554008.png)
![image](https://user-images.githubusercontent.com/57614736/96415514-4a9dac00-1221-11eb-9515-5991ea67d095.png)

**Comment by aiwantaozi** [comment]
@paynejacob  could you help pick your previous PR to [release/v2.4](https://github.com/rancher/rancher/tree/release/v2.4)?

**Comment by sowmyav27** [comment]
**On latest 2.4-head commit id: `f210f54bd`**

Error seen while launching clusters with 1.14 and 1.18 hosted EKS clusters from rancher
<img width="708" alt="Screen Shot 2020-10-19 at 11 19 27 PM" src="https://user-images.githubusercontent.com/26032343/96492983-04b50800-1262-11eb-8986-7ae5de920f58.png">

Reopening the issue for the error seen on 2.4-head

**Comment by sowmyav27** [comment]
**on 2.4-head commit id: `6b91c87ab`**

- Deploy EKS v1 1.14 and 1.18 clusters.
- Clusters come up Active.

**On master-head - commit id: `68042fa` and 2.5-head commit id: `9d38821`**
- Deploy EKS v1 1.14 and 1.18 clusters.
- Clusters come up Active.
