### ISSUE TITLE
[2.4 Forward port] Rancher K8s Auth Proxy does not utilize forward proxy (if defined) to proxy communication

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28321]
Forward port issue for https://github.com/rancher/rancher/issues/25488

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4.6-rc10

* Deploy Rancher in a semi-airgapped environment, with a proxy
  * Rancher installed a node with no public IP / direct access to the internet in EC2
  * Internet-facing load balancer points to Rancher so it is externally accessible
  * Docker settings and Rancher both use proxy
  * No private registry
* Create each of GKE, EKS, AKS, Custom clusters (custom cluster 1 created from DO node, custom cluster 2 created from on-prem nodes)
* Clusters provision
* Cluster and node agents deploy on all clusters
* Clusters are active and accessible
* View logs, exec shell, kubectl all function in all clusters
