### ISSUE TITLE
[rancher/charts] RFE: Take ownership of CRDs that already exist in the cluster

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#28326]
For CRD charts, if the CRD is already installed onto a cluster we should patch the existing CRD with the ownership metadata for the CRD chart so that it is now managed by the CRD chart's lifecycle.

This is required for `rancher-monitoring` in particular since the CRDs usually come pre-installed in a Rancher cluster.

**Comment by aiyengar2** [comment]
Temporary workaround for this issue is to delete the CRDs from the cluster before installing monitoring:

```
kubectl delete crd prometheuses.monitoring.coreos.com
kubectl delete crd prometheusrules.monitoring.coreos.com
kubectl delete crd servicemonitors.monitoring.coreos.com
kubectl delete crd podmonitors.monitoring.coreos.com # technically not needed since v1 monitoring never installed this in the first place iirc
kubectl delete crd alertmanagers.monitoring.coreos.com
kubectl delete crd thanosrulers.monitoring.coreos.com
```

**Comment by aiyengar2** [comment]
Note: the approach mentioned above has been slightly altered based on discussions in design meetings. Please see https://github.com/rancher/charts/pull/595 for updated information on the design.

The new design will still enable the CRD chart to assume ownership of any existing CRDs in the cluster and will delete the CRDs on an uninstall.

**Comment by jiaqiluo** [comment]
The enhancement is validated on rancher:`master-f7f8e8bb0649e6f163bd6ba2118622a9889236ce-head` HA setup with the latest chart 

The monitoring v2 app is installed into the local cluster successfully without deleting the existing CRDs
