### ISSUE TITLE
Support AWS keys provided by IAM role in external-dns

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#2833]
It would be great to be able use the IAM-role provided credentials, as per AWS best practices. They are already available to containers from the host via standard AWS methods, e.g. `curl http://169.254.169.254/latest/meta-data/iam/security-credentials/`.

**Comment by alena1108** [comment]
@ebr thats a legitimate enhancement request, +1

**Comment by dmweyek** [comment]
+1

**Comment by nhumrich** [comment]
+1

**Comment by damniamgood** [comment]
+1

**Comment by vincent99** [comment]
I presume this is for [external-dns](https://github.com/rancher/external-dns), not [rancher-dns](https://github.com/rancher/rancher-dns)...

**Comment by flypenguin** [comment]
any updates here? this would be *so* much better than the current setup, and it is actually AWS recommended practice as you probably know :) .

**Comment by ocervell** [comment]
+1

**Comment by bradleygolden** [comment]
+1

**Comment by superseb** [comment]
Has been added in https://github.com/rancher/external-dns/commit/36a8e8e4b46024ce783d2db82ae6c4d16bf6411a#diff-7c948afeb7ec94ba92be9ce3c063dbbf
