### ISSUE TITLE
[UI]: Add version drop downs to node groups

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#28335]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Description:**
User should be able to manually upgrade nodegroup versions to match their cluster's version by selecting from a drop down in the edit page. New nodegroups should have the same version as the cluster's kubernetes version.If the nodegroup version already matches the cluster version then the user should not be able to select another version.

**Other details that may be helpful:**
json field is "version" under "nodeGroups".

**Backend Issue:**
https://github.com/rancher/rancher/issues/27777

**Comment by sowmyav27** [comment]
**On master-head - commit id: `5ad6fdbba`**

- User should be able to manually upgrade nodegroup from Rancher UI
- New node group's have k8s versions same as the cluster
- User is NOT able to change the k8s version of the cluster when the  k8s version of the nodegroup matches the cluster.

**Comment by aaronRancher** [comment]
The enhancement is verified on `rancher\rancher:master-head` `version 5ad6fdbba` with imported EKS clusters.

- Node group k8s dropdown is visible when the node group k8s version is behind the cluster k8s version.
- New node group's have k8s versions same as the cluster
- User is NOT able to change the k8s version of the cluster when the k8s version of the node group matches the cluster.

**Comment by sowmyav27** [comment]
Related issues have been logged separately. Closing this
