### ISSUE TITLE
Cannot install rke on Azure VM

### ISSUE THREAD

**Issue by jaylondhe** [rancher/rancher#28339]
Can someone please explain what is wrong here
azureuser@myubuntu:~$ sudo docker --version
Docker version 19.03.12, build 48a66213fe

azureuser@myubuntu:~$ sudo grep -i tcpfor  /etc/ssh/sshd_config
AllowTcpForwarding yes

azureuser@myubuntu:~$ sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-08-11 04:13:39 UTC; 7min ago
     Docs: https://docs.docker.com
 Main PID: 1078 (dockerd)
    Tasks: 10
   CGroup: /system.slice/docker.service
           └─1078 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

Aug 11 04:13:37 myubuntu dockerd[1078]: time="2020-08-11T04:13:37.008228400Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Aug 11 04:13:37 myubuntu dockerd[1078]: time="2020-08-11T04:13:37.008240000Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Aug 11 04:13:37 myubuntu dockerd[1078]: time="2020-08-11T04:13:37.009021200Z" level=info msg="Loading containers: start."
Aug 11 04:13:38 myubuntu dockerd[1078]: time="2020-08-11T04:13:38.460568400Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can
Aug 11 04:13:38 myubuntu dockerd[1078]: time="2020-08-11T04:13:38.565924400Z" level=info msg="Loading containers: done."
Aug 11 04:13:39 myubuntu dockerd[1078]: time="2020-08-11T04:13:39.161273527Z" level=warning msg="Not using native diff for overlay2, this may cause degraded performance for building images:
Aug 11 04:13:39 myubuntu dockerd[1078]: time="2020-08-11T04:13:39.161588199Z" level=info msg="Docker daemon" commit=48a66213fe graphdriver(s)=overlay2 version=19.03.12
Aug 11 04:13:39 myubuntu dockerd[1078]: time="2020-08-11T04:13:39.197582967Z" level=info msg="Daemon has completed initialization"
Aug 11 04:13:39 myubuntu dockerd[1078]: time="2020-08-11T04:13:39.370419951Z" level=info msg="API listen on /var/run/docker.sock"
Aug 11 04:13:39 myubuntu systemd[1]: Started Docker Application Container Engine.

azureuser@myubuntu:~$ sudo rke config
[+] Cluster Level SSH Private Key Path [~/.ssh/id_rsa]:
[+] Number of Hosts [1]:
[+] SSH Address of host (1) [none]: 10.0.0.4
[+] SSH Port of host (1) [22]:
[+] SSH Private Key Path of host (10.0.0.4) [none]:
[-] You have entered empty SSH key path, trying fetch from SSH key parameter
[+] SSH Private Key of host (10.0.0.4) [none]:
[-] You have entered empty SSH key, defaulting to cluster level SSH key: ~/.ssh/id_rsa
[+] SSH User of host (10.0.0.4) [ubuntu]: azureuser
[+] Is host (10.0.0.4) a Control Plane host (y/n)? [y]: y
[+] Is host (10.0.0.4) a Worker host (y/n)? [n]: y
[+] Is host (10.0.0.4) an etcd host (y/n)? [n]: y
[+] Override Hostname of host (10.0.0.4) [none]:
[+] Internal IP of host (10.0.0.4) [none]:
[+] Docker socket path on host (10.0.0.4) [/var/run/docker.sock]:
[+] Network Plugin Type (flannel, calico, weave, canal) [canal]:
[+] Authentication Strategy [x509]:
[+] Authorization Mode (rbac, none) [rbac]:
[+] Kubernetes Docker image [rancher/hyperkube:v1.18.6-rancher1]:
[+] Cluster domain [cluster.local]:
[+] Service Cluster IP Range [10.43.0.0/16]:
[+] Enable PodSecurityPolicy [n]:
[+] Cluster Network CIDR [10.42.0.0/16]:
[+] Cluster DNS Service IP [10.43.0.10]:
[+] Add addon manifest URLs or YAML files [no]:

azureuser@myubuntu:~$ sudo rke up
INFO[0000] Running RKE version: v1.1.4
INFO[0000] Initiating Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [10.0.0.4]
WARN[0000] Failed to set up SSH tunneling for host [10.0.0.4]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access node with address [10.0.0.4:22] using SSH. Please check if you are able to SSH to the node using the specified SSH Private Key and if you have configured the correct SSH username. Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
WARN[0000] Removing host [10.0.0.4] from node lists
WARN[0000] [state] can't fetch legacy cluster state from Kubernetes: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [10.0.0.4]
INFO[0000] [certificates] Generating CA kubernetes certificates
INFO[0000] [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
INFO[0000] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
INFO[0000] [certificates] Generating Kubernetes API server certificates
INFO[0000] [certificates] Generating Service account token key
INFO[0000] [certificates] Generating Kube Controller certificates
INFO[0001] [certificates] Generating Kube Scheduler certificates
INFO[0001] [certificates] Generating Kube Proxy certificates
INFO[0001] [certificates] Generating Node certificate
INFO[0001] [certificates] Generating admin certificates and kubeconfig
INFO[0002] [certificates] Generating Kubernetes API server proxy client certificates
INFO[0002] Successfully Deployed state file at [./cluster.rkestate]
INFO[0002] Building Kubernetes cluster
FATA[0002] Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config

**Comment by superseb** [comment]
Please use https://rancher.com/docs/rke/latest/en/troubleshooting/ssh-connectivity-errors/.

It also seems you are running `rke up` on the same host as the host you want to provision, so `ssh azureuser@10.0.0.4` should succeed to test SSH connectivity, and then `docker ps` to ensure proper access.

**Comment by jaylondhe** [comment]
Thanks for your reply. Issue was that I didn't add the public key in ~/.ssh/authorized_keys. After adding it was successful
Appreciate your quick reply.
