### ISSUE TITLE
worker nodes missing label node-role.kubernetes.io/worker for new k8s major version 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#28345]
https://github.com/rancher/rancher/issues/26717 

Issue:
RKE expects Rancher to send service options for new introduced k8s versions (via KDM). Rancher's label sync code doesn't pass this option and so the generatePlan errors out. 

```
2020/08/11 18:13:34 [ERROR] NodeController c-mwj4v/m-25c53570c692 [machinesLabelSyncer] failed with : getDefaultKubernetesServicesOptions: No serviceOptions found for cluster version [v1.19.0-rc.4-rancher1-1] or cluster major version [v1.19]
``` 

To be fixed here, https://github.com/rancher/rancher/blob/master/pkg/controllers/managementuser/nodesyncer/nodessyncer.go#L326

**Comment by Oats87** [comment]
This should also be backported to earlier Rancher versions
