### ISSUE TITLE
Alerting v2

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#28348]
Updates the Rancher Monitoring chart introduced in https://github.com/rancher/rancher/issues/26549 to support a default AlertManager deployment.

Users should be able to:
- Create PrometheusRules alerting rules to configure a Prometheus deployment to emit custom / default alerts to all configured AlertManager deployments
- Configure a AlertManager deployments via a Secret config that allows users to set routes, inhibition rules, and notifiers based on the upstream Prometheus Operator docs

Since this chart will be a patch on the upstream Prometheus Operator chart, users will have full control over the deployment and should be able to customize their configuration in any way that the upstream Prometheus Operator currently supports, including using experimental features such as specifying remote read/write configurations to Prometheus and providing Thanos configuration.

Note: This new chart will not support configuring non-Prometheus alerts through Rancher; users are expected to create PrometheusRules in order to configure these alerts (if not already provided by the default PrometheusRules deployed as part of the chart).

Parent PR: https://github.com/rancher/charts/pull/534

**Comment by jiaqiluo** [comment]
This feature is validated on `master-616259e0274b26300169f9c06aa0945b4f31e840-head` with the latest monitoring chart.

Steps:
- run Rancher in HA mode
- enable monitoring from Dashboard UI by installing the rancher-monitoring app
- edit the secret `alertmanager-rancher-monitoring-alertmanager` in the namespace `cattle-monitoring-system` to set a notifier 
- create a new alert by applying a PrometheusRules YAML file

Result:
- the custom alert is emitted and received by the alert manager ( showing in its UI)
- the alert message is sent to Slack

More compressive tests will be done, and new issues will be made if needed.
