### ISSUE TITLE
User is not able to deploy cluster because agent manifest is unknown

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28351]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On master-head
- Deploy a one node DO cluster
- the cluster fails to come up.
- Error seen on the Node page: `Unable to find image 'rancher/rancher-agent:master-44caa588962a9004e192faf28ae9296ac46cb164-head' locally docker: Error response from daemon: manifest for rancher/rancher-agent:master-44caa588962a9004e192faf28ae9296ac46cb164-head not found: manifest unknown: manifest unknown. See 'docker run --help'. Process exited with status 125 : exit status 1`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `44caa5889`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO node driver
- Kubernetes version (use `kubectl version`):

```
1.18
```

**Comment by sangeethah** [comment]
Tested with `master-d19f179c4ff15bb782e27ed50d33d169dad79f80-head`
This issue is not seen any more.
Able to deploy a DO cluster successfully.
