### ISSUE TITLE
[Fatal bug] restart rancher/server container  in rancher-ui ,restart function has bug and loop stop rancher/server container 

### ISSUE THREAD

**Issue by jvhuaxia** [rancher/rancher#28354]
when I restart rancher/server container on the rancher-ui
![image](https://user-images.githubusercontent.com/29006793/89969749-c27fb100-dc89-11ea-8c6f-f2c048cb34f8.png)
And rancher-server container just stopped and no start

I started rancher-server container use docker start command
started rancher can in rancher ui see rancher-server container in stopping
and stop self

That's it. I cant start this rancher/server container in this loop

**Comment by vincent99** [comment]
We no longer support or maintain Rancher 1.x, having gone through a 2+ year transition to 2.x.

Whats happening is you ask for it to be restarted, that's recorded in the database, the task is picked up and the container is killed before the task has a chance to be marked done, so its repeated in next start.
