### ISSUE TITLE
When adding node to cluster receive 'Use of Closed Connection' error

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#28358]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug - Upstream in K8s and go HTTP module

**Steps to reproduce (least amount of steps as possible):**
Add a new node to the cluster, intermittently you may see this error and the machine fails to join

The solution is to restart kubelet because an idle http/2 connection has not been cleaned properly (due to upstream bugs)

**Result:**

The node fails to join and subsequent cluster upgrades will fail (say the node in question is a CP node) and this can cause production disruption to customers unaware of the bug

**Other Details**
This is not a Rancher/RKE bug directly but this issue is to track it upstream for ZD and raise awareness as I cannot find a true duplicate in Rancher issues

We are affected by it and need to be proactive in ensuring we have any upstream fix implemented

(Please correct me if wrong)

Upstream Issue
https://github.com/kubernetes/kubernetes/issues/87615

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS (no node-driver, done as custom iirc)
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 1.17.6

gz#11696

gz#12399

**Comment by maggieliu** [comment]
Looks like the upstream bug will be fixed in 1.19.5: https://github.com/kubernetes/kubernetes/pull/96778

**Comment by sangeethah** [comment]
Waiting for K8s 1.19.6 to be made available.

**Comment by anupama2501** [comment]
The issue has been addressed in the latest k8s 1.19.6-rancher1-1

Following are the checks performed on the clusters:

Rancher: 2.5.4-rc8
K8ss verified: 1.19.6-rancher1-1,1.18.14-rancher1-1,1.17.16-rancher1-1

**2.4.5-rc8 -fresh install** 

1.Fresh install of rancher on 2.5.4-rc8, verify the versions of k8s shown while creating the clusters: 1.19.6-rancher1-1,1.18.14-rancher1-1
2.Launch clusters on 4 network providers[calico, flannel, cannel and weave] for two k8s versions - 1.19.6-rancher1-1,1.18.14-rancher1-1
3.Run validation and network checks
All the checks have passed

**Upgrade testing:**
1.Rancher fresh install on 2.5.3[commit id: ]
2.Create clusters on 4 network providers for 1.19.4-rancher1-1,1.18.12-rancher1-1,1.17.14-rancher1-1
3.Run pre-upgrade checks - PASS
4.Upgarde rancher version to 2.4.5-rc8 - PASS
5.Run post-upgrade checks - PASS
6.Verify metadata container pointing dev
7.Upgrade the k8s version on all the clusters to 1.19.6-rancher1-1,1.18.14-rancher1-1,1.17.16-rancher1-1 respectively - PASS
8.Run post upgrade checks - PASS 

2.5.3 - min version checks
1.Change the metadata container pointing from release to dev
2.Create clusters on 4 network providers for the three k8s versions 1.19.6-rancher1-1,1.18.14-rancher1-1,1.17.16-rancher1-1 - PASS
3.Run network checks on all the clusters - PASS
