### ISSUE TITLE
Opening Dashboard on ECM provisioned cluster results in Get request to v1/schemas returns 502 - Available after refreshing the browser.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28364]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- After installing Rancher provision a cluster
- When the new cluster is provisioned, click in Try Dashboard.

**Result:**

![Screen Shot 2020-07-29 at 3 33 46 PM](https://user-images.githubusercontent.com/27659/88860598-fdc1b080-d1b0-11ea-8b17-efa9d003a5f7.png)

Refreshing the browser makes the Dashboard available.

**Other details that may be helpful:**

Related to: rancher/rancher#28150

**Environment information**
- Rancher version: `master-head (08/11/2020)` _d19f179c4_
- Installation option: HA k8s

**Comment by lyzhang1999** [comment]
I use Tencent TKE provider, got same problem

**Comment by wazery** [comment]
Happens to me as well on `v2.4.5`

**Comment by maggieliu** [comment]
@izaac can you reproduce this everytime?

**Comment by izaac** [comment]
@maggieliu I'm not able to reproduce this on latest master at least not consistently meaning rarely seen.

**Comment by Ileriayo** [comment]
This must have been a firewall issue. I got it fixed by opening some ports, can't remember the exact one though... Maybe 8472.

**Comment by lyzhang1999** [comment]
solved when rancher agent run success in kubernetes

**Comment by deniseschannon** [comment]
https://github.com/rancher/rancher/issues/28364

**Comment by maggieliu** [comment]
@izaac can you please test again in master? Also can you please test in 2.4 and log a bug for 2.4 also?

**Comment by izaac** [comment]
Rancher version `v2.4-head (08/26/2020)` _43fc91d70_ 
I am able to reproduce this by deploying clusters and clicking Try Dashboard as soon as the cluster is Active in Ember UI. 

Even though the Cluster is in Active state It seems that until all the `System` project workloads are finished deploying, perhaps specifically `cattle-cluster-agent` trying to open the Dashboard on these clusters end up getting this cluster `schemas` endpoint error.


I wasn't able to reproduce this on `master-head (08/26/2020)` _616259e02_ I tried a few times with different cluster types.


Opened #28577 for v2.4 follow up.
