### ISSUE TITLE
Text on UI about information on public/private access for EKS clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28369]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a hosted EKS cluster using "Private Access" as API server endpoint access
- The cluster fails to come up.
- Same issue is seen when an imported cluster has both public and private access as API server endpoint access.

A text on the UI suggesting the users to check the Rancher docs for information on public/private access and security groups rules for private traffic before configuring can be made available.

**Other details that may be helpful:**
Related to https://github.com/rancher/rancher/issues/28208 and https://github.com/rancher/rancher/issues/26930

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `d19f179c4`
- Installation option (single install/HA): HA

**Comment by westlywright** [comment]
I am going to add a small blurb about this being an advanced use case. The translation will link to Amazon's docs regarding this option for now since we new docs need to be written for this feature. If it is desired that the link change it will be easy enough after the Rancher docs have been created.

**Comment by sowmyav27** [comment]
**Verified on latest master-head - commit id: `d19f179c4` ui tag: `latest2`**

- Deploy an EKS cluster
- Networking section shows the following text with an hyperlink to endpoint docs in aws.
<img width="1288" alt="Screen Shot 2020-08-14 at 1 25 38 PM" src="https://user-images.githubusercontent.com/26032343/90289959-d49c5380-de31-11ea-933d-79bda0b541ae.png">
