### ISSUE TITLE
Update failed: error: pathspec 'origin/master' did not match any file(s) known to git. : exit status 1 on the git.rancher.io

### ISSUE THREAD

**Issue by raszkiewicz** [rancher/rancher#28362]
**What kind of request is this (question/bug/enhancement/feature request):**
Question/Issue

**Steps to reproduce (least amount of steps as possible):**
From the Rancher UI:
Apps -> Manage Catalogs

**Result:**
I'm getting error message on any catalog library install from the git.ranchar.io:

```
Update failed: error: pathspec 'origin/master' did not match any file(s) known to git. : exit status 1
```

![image](https://user-images.githubusercontent.com/22371077/90042531-cebf3a80-dc98-11ea-8e71-67c75cfc06e7.png)

**Other details that may be helpful:**

2020/08/12 16:32:17 [ERROR] CatalogController helm3-library [catalog] failed with : Update failed: error: pathspec 'origin/master' did not match any file(s) known to git.
: exit status 1
2020/08/12 16:32:17 [ERROR] CatalogController system-library [catalog] failed with : Update failed: error: pathspec 'origin/release-v2.4' did not match any file(s) known to git.
: exit status 1, [system-image-upgrade-catalog-controller] failed with : upgrade cluster c-chx55 system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogTemplate.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found
2020/08/12 16:32:17 [ERROR] CatalogController library [catalog] failed with : Update failed: error: pathspec 'origin/master' did not match any file(s) known to git.

**Environment information**
- Rancher version: `rancher/rancher` v.2.4.5
- Installation option: single install

**Cluster information**
- Cluster type: Custom
- Machine type: VM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by thuongnvbk** [comment]
Got the same error here. Does your rancher run behind a proxy or something like that?

**Comment by pensiero** [comment]
+1 same error

**Comment by fozboz** [comment]
I've had issues with those repos too. I just switched to getting them directly from GitHub.

For https://git.rancher.io/helm3-charts use https://github.com/rancher/helm3-charts
For https://git.rancher.io/charts use https://github.com/rancher/charts
For https://git.rancher.io/system-charts use https://github.com/rancher/system-charts
