### ISSUE TITLE
User cannot import an EKS cluster if the cluster is not created by the user

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28375]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
pre condition: user1 and user2 are part of the same amazon `Account`.

- As user1 create an eks cluster via eks console.
- As user2, import cluster in rancher using user2's AWS access key and secret key.
- Cluster will be stuck in waiting state.

**Expected Result:**
Cluster should get imported into Rancher. 

**Other details that may be helpful:**
User2 is able to modify cluster deployed by user1 on the EKS console. So user2 should be allowed to import cluster created by user1 in Rancher.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `d19f179c4 `
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): import EKS cluster
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by cbron** [comment]
At this point its documentation issue, so bumping out to 2.5

**Comment by sowmyav27** [comment]
Can we NOT list the credentials NOT created using the "AWS credentials" that we select while importing the cluster?

**Comment by rmweir** [comment]
I feel like these things are a little disjointed. It is the same way in amazon. You may be able to list clusters that you cannot interact with via kubectl without someone making a change to the configmap in the cluster. One is in the AWS context and the other relates to permission configured in the cluster. It would probably not be trivial to check if a given cloud credential has kubectl access to a cluster. It is also only needed for initially importing the cluster. If someone else imports it but then you use your cloud credential to configure something that you would be able to configure in the EKS console, that would work and would be valid.

**Comment by rmweir** [comment]
Documented: https://github.com/rancher/docs/pull/2723

**Comment by deniseschannon** [comment]
This is expected and documented based on the permissions.
