### ISSUE TITLE
Helm Install

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28373]
Helm install for Rancher 2.5

**Comment by maggieliu** [comment]
@sangeethah Can we start testing installing on kubeAdm and miniKube

**Comment by sangeethah** [comment]
Tested rancher helm installs on the following clusters:
1. RKE
2. K3S
3. AKS
4. EKS

**Comment by maggieliu** [comment]
@sangeethah can we capture the k8s versions we tested on for the cluster types you mentioned? Might need to capture this for support matrix.

**Comment by izaac** [comment]
tested GKE: `v1.17.9-gke.1504`

**Comment by soumyalj** [comment]
Tested EKS: **Version** : **v1.17.9-eks-4c6976**

**Comment by izaac** [comment]
Tested AKS: `v1.17.9`

**Comment by sangeethah** [comment]
Helm install of rancher for kubeAdm and miniKube clusters tracked in https://github.com/rancher/rancher/issues/29037
