### ISSUE TITLE
"ping app"

### ISSUE THREAD

**Issue by blaggacao** [rancher/rancher#2838]
`ping app` resolves in ALL containers (on the same host) across stacks to `127.0.53.53` (in my setup)

This is true even though, they have no link at all.
Consequently, when trying to link a service by the name `app` to another service, it fails like a miracle, without warning.

If this is intended behavior, it should be:

a) (prominently) documented
b) blocked in the UI as a protected name

Remember that linking by the generic token `app` is quite common style.

----------------------

```
Rancher	           v0.47.0
Cattle	           v0.115.0
User Interface	   v0.68.0
Rancher Compose	   v0.5.3
```

**Comment by blaggacao** [comment]
Oh, this was such a nasty one. :-1:

**Comment by vincent99** [comment]
Are you on Google Cloud or using their DNS?  We're not actually doing anything, it's not found and sent to the recur see server.  But `app.` is a TLD (and owned by them) and resolves on their DNS.

**Comment by blaggacao** [comment]
My system is:
Rancher Server on Virtualbox with boot2docker on my laptop
Host is RancherOS on bare metal
All is on my local network at home.

**Comment by blaggacao** [comment]
I think you are right: I can ping with the same results from RancherOS host. Moving to RancherOS repo...

**Comment by vincent99** [comment]
Google DNS is commonly used at home, and I'm not near a computer but I think it's the default in RancherOS too.

**Comment by blaggacao** [comment]
It's just on the rancherOS, the home router has an ISP NS. Nice catch!  wouldn't have been able to identify that in ages... :+1:  Thanks!

**Comment by blaggacao** [comment]
However, I wonder if with the recent inflation of TLDs this can arise to an issue of Rancher Server concern as well... just for the record.
