### ISSUE TITLE
Feature: Ability to silence/pause inactive/inaccessible clusters.

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#28382]
A customer shuts down the nodes of some downstream clusters during the off hours to save on cost. However, during this time Rancher shows errors in regards to the cluster. Largely cosmetic, but it does raise an alarming view on a daily basis.

They simply want to be able to put these clusters into a sort of "paused" state so that errors aren't shown in the Rancher UI. Simply greying them out may be beneficial here.

**Comment by leodotcloud** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/27676
