### ISSUE TITLE
Add Host/Other is missing arguments

### ISSUE THREAD

**Issue by foobarto** [rancher/rancher#2839]
When adding hosts using `docker-machine` behind corporate firewall/proxy there are few extra configuration options that need to be passed into `/etc/default/docker`.

List of arguments can be found here: https://docs.docker.com/machine/reference/create/

Most importantly there are  `--engine-env`, `--engine-insecure-registry`, `--engine-install-url`, `--engine-opt`, `--engine-registry-mirror` and `--allow-insecure-ssl`.

**Comment by cjellick** [comment]
Working on it!
https://github.com/rancher/go-machine-service/pull/66
cc @wlan0

**Comment by cjellick** [comment]
We've added all of these except `engine-install-url`, which we will be adding in the future.

**Comment by cjellick** [comment]
I do not see allow-insecure-ssl on https://docs.docker.com/machine/reference/create/

**Comment by cjellick** [comment]
For the behind-a-firewall use case, I fear that the most important one is the one we've not yet implemented: engine-install-url.

I will leave this open and assigned to me until we add that.

**Comment by cjellick** [comment]
We want to provide two options here:
1. expose the raw engine-install-url option
2.let users pick a docker version and then we pick the proper url. Maybe this is just something the UI does

**Comment by cjellick** [comment]
@sangeethah  A valid test value for `engineInstallUrl`is `https://test.docker.com/`

**Comment by sangeethah** [comment]
Tested with latest build from master - Dec 8.

Following arguments are now supported by create_machine which gets passed down to docker-machine:

engineOpts
engineInsecureRegistry
engineRegistryMirror
engineLabel
engineStorageDriver
engineInstallUrl

**Comment by sangeethah** [comment]
UI support for this feature is tracked in https://github.com/rancher/rancher/issues/2913

**Comment by sangeethah** [comment]
Tested with latest build from master - Dec 11
 
UI has support for adding all machine config options when adding hosts.
Able to add Digital Ocean machine successfully using all the "DOCKER ENGINE" options available in the UI.

@foobarto , this should be available in the next release.
