### ISSUE TITLE
[Logging v2] Airgap - Image Mirroring

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#28403]
Replace all image specs with registry/repo/tag. Add imagePullSecrets.

**Comment by cbron** [comment]
@izaac we can use this as airgap testing ticket

**Comment by izaac** [comment]
@cbron for testing airgap we need an RC to be available with all the images used by the `rancher-logging` chart in `rancher-images.txt`

**Comment by cbron** [comment]
yes and that isn't ready yet, just meant that when it is we can use this ticket for it

**Comment by sangeethah** [comment]
Blocked by https://github.com/rancher/dashboard/issues/1244

**Comment by izaac** [comment]
Rancher version: `v2.5.0-alpha3` 

logging operator gets deployed correctly.
I observed also `fluent-fluent-bit:1.5.4` `banzaicloud-fluentd:v1.11.2-alpine-2` and `banzaicloud-logging-operator:3.6.0` getting pulled from the private registry in the Airgap's local cluster.

There's still [this issue](https://github.com/rancher/dashboard/issues/1244) in `v2.5.0-alpha3`  that prevents us from installing using the `Deploy to control plane nodes` option

**Comment by cbron** [comment]
@izaac which issue is tracking the control plane nodes issue ? The linked one is closed.

**Comment by sangeethah** [comment]
@cbron Since we are using `v2.5.0-alpha3`  for  airgap testing were this issue still exists -https://github.com/rancher/dashboard/issues/1244.
We are good on all the images at this point since enabling control plane logging is not going to really have  new images being used by the logging charts.
