### ISSUE TITLE
[Logging v2] Support configuring fluentd and fluentbit buffer sizes

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#28401]
Users should be able to set a buffer size for the chart and have it applied to fluentd and fluent-bit buffers.

**Comment by nickgerace** [comment]
Tangentially related upstream issue: https://github.com/banzaicloud/logging-operator/issues/717

**Comment by nickgerace** [comment]
Finished investigation into `fluentd` and `fluentbit` settings.

## fluentd buffer settings

There really aren't many except for one. This is because fluentd buffer configuration is usually handled by outputs, which are maintained by upstream. However, that one option is in @dbason's tangentially related PR for additional fluentd configuration options: https://github.com/rancher/charts/pull/1112

## fluentbit buffer settings

Below are the recommended settings available in the [fluentbitSpec](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/v1beta1/fluentbit_types/).
These should provide the user with enough options to configure `inputTail` buffering.

- Buffer_Chunk_Size
- Buffer_Max_Size
- Mem_Buf_Limit
- Multiline_Flush
- Skip_Long_Lines

These will be added in https://github.com/rancher/charts/pull/1121

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (06/03/2021)` _be03c8b_
Charts Repo info:
```
branch: dev-v2.6
commit: bdcfd9db77de9cb97cc7947858b54f4ec41e4b23
```

I tried a few combinations while configuring `Multiline_Flush` and `Skip_Long_Lines` from the Dashboard
But this has resulted in an helm install error on each attempt:


`Error: Logging.logging.banzaicloud.io "rancher-logging" is invalid: [spec.fluentbit.inputTail.Multiline_Flush: Invalid value: "integer": spec.fluentbit.inputTail.Multiline_Flush in body must be of type string: "integer", spec.fluentbit.inputTail.Skip_Long_Lines: Invalid value: "boolean": spec.fluentbit.inputTail.Skip_Long_Lines in body must be of type string: "boolean"]`


The only thing that worked so far was leaving those values as empy string `''`


Values I tried:

```
Multiline_Flush: '4'
Skip_Long_Lines: 'On'
```

```
Multiline_Flush: 4
Skip_Long_Lines: true
```

```
Multiline_Flush: '2'
Skip_Long_Lines: 'true'
```

```
Multiline_Flush: 2
Skip_Long_Lines: 'true'
```

**Comment by izaac** [comment]
Rancher version `2.6 master-head (06/04/2021)` _772ef96e6_
Logging version: `3.9.401+up3.9.4`
```
branch: dev-v2.6
commit: bdcfd9db77de9cb97cc7947858b54f4ec41e4b23
```

I tried with all double quotes:

```
fluentbit:
      inputTail:
        Buffer_Chunk_Size: "128K"
        Buffer_Max_Size: "128K"
        Mem_Buf_Limit: "128M"
        Multiline_Flush: "2"
        Skip_Long_Lines: "true"
```

`Error: Logging.logging.banzaicloud.io "rancher-logging" is invalid: [spec.fluentbit.inputTail.Skip_Long_Lines: Invalid value: "boolean": spec.fluentbit.inputTail.Skip_Long_Lines in body must be of type string: "boolean", spec.fluentbit.inputTail.Multiline_Flush: Invalid value: "integer": spec.fluentbit.inputTail.Multiline_Flush in body must be of type string: "integer", spec.fluentbit.inputTail.Buffer_Max_Size: Invalid value: "integer": spec.fluentbit.inputTail.Buffer_Max_Size in body must be of type string: "integer"`

**Comment by nickgerace** [comment]
With https://github.com/rancher/charts/pull/1255 we will try to force the values `toString` in order to fix https://github.com/rancher/rancher/issues/28401#issuecomment-854777325.

**Comment by izaac** [comment]
Blocked by https://github.com/rancher/rancher/issues/33106

**Comment by nickgerace** [comment]
Validation payload in `values.yaml`:
```
fluentbit:
  inputTail:
    Buffer_Chunk_Size: '32k'
    Buffer_Max_Size: '32k'
    Mem_Buf_Limit: ''
    Multiline_Flush: '4'
    Skip_Long_Lines: 'Off'
```

**Comment by izaac** [comment]
I've tried this manually with helm to discard an issue with Dashboard:

I've used the values mentioned [here](https://github.com/rancher/rancher/issues/28401#issuecomment-857956241)
As well as few other combinations. I still ended up with some types errors.

```
helm upgrade --install=true --namespace=cattle-logging-system --timeout=10m0s --values=/Users/izaac/logging/values-rancher-logging-crd-3.10.0-up3.10.0.yaml --version=3.10.0+up3.10.0 --wait=true rancher-logging /Users/izaac/logging/rancher-logging-3.10.0+up3.10.0.tgz


Error: UPGRADE FAILED: failed to create resource: Logging.logging.banzaicloud.io "rancher-logging" is invalid: [spec.fluentbit.inputTail.Skip_Long_Lines: Invalid value: "boolean": spec.fluentbit.inputTail.Skip_Long_Lines in body must be of type string: "boolean", spec.fluentbit.inputTail.Multiline_Flush: Invalid value: "integer": spec.fluentbit.inputTail.Multiline_Flush in body must be of type string: "integer"]
```

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (06/14/2021)` _9d54b1a_


Configuration is passed properly and the `rancher-logging-fluentbit` secret has the passed values.

```conf
[INPUT]
    Name         tail
    Buffer_Chunk_Size  32K
    Buffer_Max_Size  32K
    DB  /tail-db/tail-containers-state.db
    Mem_Buf_Limit  3M
    Multiline_Flush  4
    Parser  docker
    Path  /var/log/containers/*.log
    Refresh_Interval  5
    Skip_Long_Lines  Off
    Tag  kubernetes.*
```

**Comment by cbron** [comment]
@nickgerace does this need docs or readme update ?

**Comment by nickgerace** [comment]
@cbron yes, will do.

**Comment by Mais316** [comment]
Please help, as issue is closed and solution is not clear how to set the fluentbit buffer size?
