### ISSUE TITLE
Rancher provisioned cluster becomes unavailable after enabling secret encryption, if secrets are deleted during the secret rewriting

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#28400]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Rancher v2.4.5 instance, and a downstream cluster. In my test lab I used https://github.com/superseb/tf-do-rancher2/ and provisioned 8vCPU, 32GB VMs, with two controlplanes, three etcd nodes and two workers.
3. Using the script below, I populated 1000 secrets in the namespaces `secret-testing`, `secret-testing2`, `secret-testing3`, `secret-testing4`, `secret-testing5`. Choice of namespaces was arbitrary, I just wanted to replicate a customer env with secrets in multiple namespaces. Relatively large number of secrets was deliberate, reproducing customer env, but also ensuring the rewrite process to encrypt secrets would take some time, providing a window to manually trigger deletion of some secrets:

```bash
  #!/bin/bash
  task(){
    dd bs=1024 count=50 </dev/urandom > random-"$1"
    echo "" >> random-"$1"
    echo "GoodData" >> random-"$1"
    kubectl --kubeconfig kubeconfig.yml -n secret-testing create secret generic secret-"$1" --from-literal=username=GoodData --from-file=password=./random-"$1"
  }

  N=100

  (
  for count in {000001..001000}
  do
    ((i=i%N)); ((i++==0)) && wait
    task "$count" &
  done
  )
```

4. Follow the Rancher server container logs, and enable managed secret encryption in the cluster per https://rancher.com/docs/rke/latest/en/config-options/secrets-encryption/#enable-encryption
5. When the Rancher server container log shows `[INFO] cluster [<cluster-id>] provisioning: Rewriting cluster secrets` execute the following script against each of the secret-testing namespaces to delete some of the secrets, whilst the rewriting is taking place:

```
#!/bin/bash
task(){
  kubectl --kubeconfig kubeconfig.yml -n secret-testing delete secret secret-"$1"
}

N=100

(
for count in {000900..001000}
do
   ((i=i%N)); ((i++==0)) && wait
   task "$count" &
done
)
```

6. Observe the RKE run will eventually fail, with an error of the following format:

```
[ERROR] ClusterController <cluster-id> [cluster-provisioner-controller] failed with : [secrets \"secret-000900\" not found secrets \"secret-000910\" not found secrets \"secret-000920\" not found secrets \"secret-000930\" not found secrets \"secret-000940\" not found secrets \"secret-000950\" not found secrets \"secret-000960\" not found secrets \"secret-000970\" not found secrets \"secret-000980\" not found secrets \"secret-000990\" not found secrets \"secret-000900\" not found secrets \"secret-000910\" not found secrets \"secret-000920\" not found secrets \"secret-000930\" not found secrets \"secret-000940\" not found secrets \"secret-000950\" not found secrets \"secret-000960\" not found secrets \"secret-000970\" not found secrets \"secret-000980\" not found secrets \"secret-000990\" not found secrets \"secret-001000\" not found secrets \"secret-000908\" not found secrets \"secret-000918\" not found secrets \"secret-000928\" not found secrets \"secret-000938\" not found secrets \"secret-000948\" not found secrets \"secret-000958\" not found secrets \"secret-000968\" not found secrets \"secret-000978\" not found secrets \"secret-000988\" not found secrets \"secret-000998\" not found secrets \"secret-000901\" not found secrets \"secret-000911\" not found secrets \"secret-000921\" not found secrets \"secret-000931\" not found secrets \"secret-000941\" not found secrets \"secret-000951\" not found secrets \"secret-000961\" not found secrets \"secret-000971\" not found secrets \"secret-000981\" not found secrets \"secret-000991\" not found]
```

7. The failure of the initial RKE run, will trigger a further run, which eventually completes successfully with: `[INFO] cluster [<cluster-id>] provisioning: Finished building Kubernetes cluster successfully`

8. Make a further edit to the cluster, in my lab I added an extra_env to the `kube-api` service:
```
[...]
  kube-api:
      [...]
      extra_env:
        - FOO=bar
```
9. Observe that upon completion of the RKE run the cluster is stuck in an Updating state with the following error: `[ERROR] ClusterController c-pr6jl [cluster-provisioner-controller] failed with : error getting secret: Internal error occurred: no matching key was found for the provided AES transformer`

10. To restore the cluster to a working state, you can perform an etcd snapshot restore to a snapshot before encryption was enabled and let the secret rewriting complete without any secret deletion during the rewrite process.

Attached Rancher log collector output from the Rancher server instance in my lab after reproducing the issue: [aseymour-rancherserver-2020-08-14_15_01_47.tar.gz](https://github.com/rancher/rancher/files/5075281/aseymour-rancherserver-2020-08-14_15_01_47.tar.gz)

**Environment information**
- Rancher v2.3.6

gzrancher/rancher#11644

**Comment by sowmyav27** [comment]
**On 2.4.5 Reproduced the issue**
- Deploy a custom cluster - 3 etcd, 2 control and 2 worker nodes.
- Create 1000 secrets in the cluster using script
```
#!/bin/bash
for j in {6..10}; do
  kubectl create namespace test$j
    for i in {2..200}; do
      kubectl create secret generic test$i --from-file=test -n test$j;
    done
done
```
- Enable encryption using [docs](https://rancher.com/docs/rke/latest/en/config-options/secrets-encryption/#enable-encryption)
- The cluster reconciles and cluster will show message "provisioning: Rewriting cluster secrets" for quite sometime.
- Rancher logs:
```
2020/11/12 00:11:58 [INFO] cluster [c-ssd29] provisioning: [addons] Executing deploy job rke-ingress-controller
2020/11/12 00:11:59 [INFO] cluster [c-ssd29] provisioning: [ingress] ingress controller nginx deployed successfully
2020/11/12 00:11:59 [INFO] cluster [c-ssd29] provisioning: [addons] Setting up user addons
2020/11/12 00:11:59 [INFO] cluster [c-ssd29] provisioning: [addons] no user addons defined
2020/11/12 00:11:59 [INFO] cluster [c-ssd29] provisioning: Rewriting cluster secrets
I1112 00:12:00.567006       6 request.go:621] Throttling request took 1.107706808s, request: PUT:https://<>:6443/api/v1/namespaces/kube-system/secrets/cronjob-controller-token-dj2cq?timeout=30s
I1112 00:12:10.567003       6 request.go:621] Throttling request took 1.924767846s, request: PUT:https://<>:6443/api/v1/namespaces/test10/secrets/test116?timeout=30s
I1112 00:12:20.766977       6 request
```
- Deleted some secrets using script
```
#!/bin/bash
for j in {6..10}; do
  kubectl create namespace test$j
    for i in {2..50}; do
      kubectl delete secret test$i -n test$j;
    done
done
```
- Cluster fails with error
<img width="1405" alt="Screen Shot 2020-11-11 at 4 16 14 PM" src="https://user-images.githubusercontent.com/26032343/98881524-117ee300-243f-11eb-9efd-7813a774628d.png">

- Cluster comes to Active state eventually
- Edit cluster, add these params in cluster.yaml and save changes made to cluster
```
services:
  kube-api:
    extra_env:
        - test=value
```
- Cluster fails to come up with error
<img width="1423" alt="Screen Shot 2020-11-11 at 4 56 07 PM" src="https://user-images.githubusercontent.com/26032343/98881591-34a99280-243f-11eb-9fd2-73ba5225d199.png">
- Error: `Cluster health check failed: Failed to communicate with API server: Unauthorized; error getting secret: Internal error occurred: no matching key was found for the provided AES transformer`
- Restore from etcd snapshot, taken before creating secrets/enabling secrets.
- Cluster comes up Active

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `bb69b039`**

**Scenario#1**

- Deploy 200 secrets (as the batch size is 250) on a cluster.
- Enable Secrets encryption on the cluster.
- The cluster goes into updating state --> Rewriting of secrets begin
- Delete few secrets
- The Rewriting of secrets finish and cluster finishes upgrading and the cluster comes up Active.
- Edit cluster, add these params in cluster.yaml and save changes made to cluster

```
services:
  kube-api:
    extra_env:
        - test=value
```
- Cluster comes up Active after updating

**Scenario#2**
- Deploy about 1000 secrets
- Enable Secrets encryption on the cluster.
- The cluster goes into updating state --> Rewriting of secrets begin
- Delete few secrets
- The Rewriting of secrets finish and cluster finishes upgrading and the cluster comes up Active.
- Edit cluster, add these params in cluster.yaml and save changes made to cluster

```
services:
  kube-api:
    extra_env:
        - test=value
```
- Cluster comes up Active after updating
