### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by pkrasam** [rancher/rancher#28414]
I am setting up a downstream user cluster based on/of `k3s` and importing it into Rancher UI and for reason the new clusters sits/shows as `Pending`

When checking the downstream cluster with these commands, I see the above error

`kubectl get po -A`
```
NAMESPACE       NAME                                     READY   STATUS             RESTARTS   AGE
kube-system     metrics-server-7566d596c8-xxfrk          1/1     Running            0          27h
kube-system     helm-install-traefik-jtbcp               0/1     Completed          1          27h
kube-system     svclb-traefik-qzv2c                      2/2     Running            1          27h
kube-system     local-path-provisioner-6d59f47c7-ssvdq   1/1     Running            1          27h
kube-system     coredns-8655855d6-9jtlz                  1/1     Running            0          27h
kube-system     traefik-758cd5fc85-jglw2                 1/1     Running            0          27h
cattle-system   cattle-node-agent-ld265                  0/1     CrashLoopBackOff   308        27h
cattle-system   cattle-cluster-agent-7b8f4c4fd5-8b5wm    0/1     Error              309        27h
```

`kubectl logs cattle-cluster-agent-7b8f4c4fd5-8b5wm -n cattle-system`
```
time="2020-08-15T10:28:57Z" level=info msg="NotBefore: 2016-10-24 21:09:52 +0000 UTC"
time="2020-08-15T10:28:57Z" level=info msg="NotAfter: 2017-10-24 21:09:52 +0000 UTC"
time="2020-08-15T10:28:57Z" level=info msg="SignatureAlgorithm: SHA1-RSA"
time="2020-08-15T10:28:57Z" level=info msg="PublicKeyAlgorithm: RSA"
time="2020-08-15T10:28:57Z" level=fatal msg="Server certificate is not valid, please check if the host has the correct time configured and if the server certificate has a notAfter date and time in the future. Certificate information is displayed above. error: Get https://rancher.w3m.pkrasam.co: x509: certificate has expired or is not yet valid"
```
..it is showing an expired date of 2016 and 2017 …where is this coming from?

The full thread on this subject can be found in our slack channel
https://rancher-users.slack.com/archives/CGGQEHPPW/p1597412216101100

**Comment by superseb** [comment]
I see a lot of info was placed in the Slack thread but I can't find a solid description of what the setup looks like, if you can describe what DNS name is configured with what IP address(es) pointing to what load balancer with what configuration and what the nodes IP addresses are, it will help trace down the issue. I assume manually running `curl https://rancher.w3m.pkrasam.co` returns you a valid certificate (every time)? What does it resolve to on the host running the `curl`, is that the same as on the nodes? It it the same if the pod container does the lookup?
