### ISSUE TITLE
rancher-compose only works with full to volumes

### ISSUE THREAD

**Issue by vegasbrianc** [rancher/rancher#2841]
There is a slight difference between docker-compose and rancher-compose. When using docker-compose it is assumed that the volume path is based from the directory in which you run docker-compose.

docker-compose file Example:
```
volumes:
    - ./voting-app:/app
```
rancher-compose doesn't use the same path for volumes as docker-compose and instead requires that you use full path of the volume.

rancher-compose file example

```
volumes:
    - /root/example-app/test-app:/app
```

This is a "gotchya" as if you reuse docker-compose files from other projects they will fail and troubleshooting is not really easy.

**Comment by ca0abinary** [comment]
+1 it would be nice to have path expansion for cases like mine where i need to run two solr servers and they each need their own path on the volume. i can't use a service in this case and need to manage each instance manually.

**Comment by deniseschannon** [comment]
Verified with v0.8.0-rc1.

**Comment by deniseschannon** [comment]
We will be release v0.7.3 with GA and will need to re-verify when we add a new v0.8.0-rcx.

**Comment by deniseschannon** [comment]
Verified with v0.8.0-rc3 that it's working as expected
