### ISSUE TITLE
[KEv2]: EKSv2 Add syncing

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#28422]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Description:**
If fields for an EKS cluster are updated in the EKS console, they should be displayed in rancher and should not be over written on update unless it is the field being changed.

**Explanation of approach:**
All fields in the EKSConfig will be nillable. If a field is nilled then it is considered "unmanaged". Fields that are "managed" have been modified in Rancher at least once before.

There is a new field on status called UpstreamSpec. This is updated every 5 minutes and represents the state of the cluster in EKS. Most or all fields will not be nil. When this is updated it will check to see if the EKS cluster is currently being updated by Rancher. This is evaluated by checking if spec and applied spec are equal. If it is not updating then all fields in EKSConfig that are no nil will be overwritten with the fields in upstreamSpec. If it is updating then this step is skipped.

The UI will display fields from the upstreamSpec. If a field is edited then it will be sent in the update.

**Comment by sowmyav27** [comment]
**Validated on master-head - commit id: `e919796c8`**

- Deployed a hosted EKS cluster through Rancher
- Verified the following scenarios and issues:
```
- Logging set in EKS console does not sync back to Rancher
- Cluster level Tags set do not reflect
- Endpoint-access-update does NOT reflect
- Labels and tags on Nodegroups, does NOT reflect
- Cluster is in Updating state in EKS, in Rancher, the state is Active state
- Scale up the nodes in a nodegroup - added nodes reflect in the Rancher nodes page but on an edit cluster, the node group is NOT available
- Adding new nodegroup - added nodes reflect in the Rancher nodes page but on an edit cluster, the node group is NOT available
```

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `33f755f18`**

- Basic syncing use cases work for a hosted EKS and an imported EKS cluster
- Tracking issues related to this separately.
- Closing this issue
