### ISSUE TITLE
Imported cluster cleanup does not clean cluster-agent

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#28428]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Import an RKE cluster
Wait for cluster to come up
Verify cattle-system and system workloads
Delete cluster
Check cluster pods

**Result:**
cattle-cluster-agent is not cleaned
```
Aarons-MBP:documents aaronyee$ kc get pods --all-namespaces
NAMESPACE       NAME                                      READY   STATUS      RESTARTS   AGE
cattle-system   cattle-cluster-agent-58b9678978-bfvxp     1/1     Running     0          53s
ingress-nginx   default-http-backend-598b7d7dbd-thxgd     1/1     Running     0          118m
ingress-nginx   nginx-ingress-controller-hpwc8            1/1     Running     0          118m
kube-system     canal-mtgcb                               2/2     Running     0          118m
kube-system     coredns-849545576b-m7xwz                  1/1     Running     0          118m
kube-system     coredns-autoscaler-5dcd676cbd-f4t8h       1/1     Running     0          118m
kube-system     metrics-server-697746ff48-5rnnj           1/1     Running     0          118m
kube-system     rke-coredns-addon-deploy-job-jzqgr        0/1     Completed   0          118m
kube-system     rke-ingress-controller-deploy-job-cnmvd   0/1     Completed   0          118m
kube-system     rke-metrics-addon-deploy-job-52gz4        0/1     Completed   0          118m
kube-system     rke-network-plugin-deploy-job-mgks4       0/1     Completed   0          118m
```

Because of this, when the cluster is reimported, system workloads are not able to be seen in Rancher UI. https://github.com/rancher/rancher/issues/28255

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-d19f179c4ff15bb782e27ed50d33d169dad79f80-head`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported

**Comment by deniseschannon** [comment]
@aaronRancher can you confirm that this was working in 2.4.x and it's not longer working in master-head? There have been a lot of changes in this area so want to validate it one more time before a dev looks into it.

**Comment by aaronRancher** [comment]
@deniseschannon This was working in 2.4.x: https://github.com/rancher/rancher/issues/28255#issuecomment-675160890
Will retest in master-head.

**Comment by aaronRancher** [comment]
This behavior is seen in Rancher server `rancher\rancher:master-head` `version 8b3b5cc`.
Tested with an EKS cluster and RKE cluster.

Steps:
Import an EKS cluster
Wait for cluster to come up
Verify cattle-system and system workloads
Delete cluster
Check cluster pods

Result:
Cluster agent is seen after cluster deletion from Rancher server.
```
Aarons-MBP:~ aaronyee$ kc get pods --all-namespaces
NAMESPACE       NAME                                    READY   STATUS    RESTARTS   AGE
cattle-system   cattle-cluster-agent-55868d65c9-l2s2x   1/1     Running   0          13m
kube-system     aws-node-6hgrb                          1/1     Running   0          31m
kube-system     aws-node-8m8l5                          1/1     Running   0          31m
kube-system     coredns-67bfd975c5-pv5tj                1/1     Running   0          38m
kube-system     coredns-67bfd975c5-rncns                1/1     Running   0          38m
kube-system     kube-proxy-t9qms                        1/1     Running   0          31m
kube-system     kube-proxy-vjhwv                        1/1     Running   0          31m
```
