### ISSUE TITLE
Catalog jenkins: Needs new version tag (1.625.2)

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [rancher/rancher#2842]
There is no jenkins:1.625.1 tag at the docker hub. Is there any way to edit the service template?

**Comment by deniseschannon** [comment]
You can make a PR at https://github.com/rancher/rancher-catalog. :)

While waiting for the catalog to be updated, you can always expand the "Preview" of the catalog to get the full docker-compose.yml, rancher-compose.yml and answers to use for a `rancher-compose up`. 

http://docs.rancher.com/rancher/rancher-compose/

**Comment by deniseschannon** [comment]
We will most likely make a new version of Jenkins template in order for those that had started it would have an upgrade path.

**Comment by cloudnautique** [comment]
rancher/rancher-catalog#54 has been pushed. I also opened an issue with the maintainers to see if they plan to continue removing previous tags.

**Comment by deniseschannon** [comment]
I was able to launch the new template. I don't have an old template, so I won't be able to test the upgrade path.
