### ISSUE TITLE
Rancher monitoring, grafana prometheus datasource cannot be added

### ISSUE THREAD

**Issue by herrbpl** [rancher/rancher#28437]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Open Grafana panel of Rancher monitoring
2) Log in and add Custom Prometheus datasource with nonexisting url, like http://notexisting:1234
3) Click Save & Test

Grafana reports "Data source is working" and saves it. In reality, all requests go to http://prometheus-operated:9090 not the URL specified in config

**Result:**
Data source is shown as succesfully added but any quering against it in Explorer reveals that requests go to default RANCHER_MONITORING data source

**Other details that may be helpful:**
Tried with both rancher/grafana-grafana:6.3.6 and rancher/grafana-grafana:7.1.0 images

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.4
- Installation option (single install/HA): HA

**Comment by fc-ds** [comment]
I have the same problem.
Any progress on this ?
