### ISSUE TITLE
How to save the data of rancherHA deployed by rke

### ISSUE THREAD

**Issue by Diyuzhou** [rancher/rancher#28436]
Do as the instruction of the official website  found that when I execute helm install rancher rancher-stable/rancher  --namespace cattle-system  --set hostname=hostname , there is no argument like dburl to save my ha rancher's data, how can I do that when I deployed a rancher ha on rke kubernetes clusters by helm

**Comment by superseb** [comment]
This is described on https://rancher.com/docs/rancher/v2.x/en/installation/how-ha-works/. Rancher will use cluster resources to store data and those are stored in the cluster's datastore (in case of RKE, etcd). How to manage backups/snapshots is described on https://rancher.com/docs/rancher/v2.x/en/backups/
