### ISSUE TITLE
can't edit cluster properties

### ISSUE THREAD

**Issue by Diyuzhou** [rancher/rancher#28431]
I want to edit my test cluster's properties such as to open private image repository but I got failure after save it.
![Screen Shot 2020-08-18 at 10 33 53 AM](https://user-images.githubusercontent.com/21288434/90463895-aa52da80-e13e-11ea-9f76-4bb319e0c625.png)

only got such message below:
I0818 10:37:10.006621       6 trace.go:116] Trace[2053347243]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-18 10:36:40.006246254 +0800 CST m=+1874967.096357722) (total time: 30.000352494s):
Trace[2053347243]: [30.000352494s] [30.000352494s] END
E0818 10:37:10.006637       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.ReplicationController: Get https://172.19.76.243:6443/api/v1/replicationcontrollers?resourceVersion=1312&timeout=30s: context deadline exceeded
I0818 10:37:24.867143       6 trace.go:116] Trace[1891595818]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-18 10:36:54.866745638 +0800 CST m=+1874981.956857049) (total time: 30.000375172s):
Trace[1891595818]: [30.000375172s] [30.000375172s] END
E0818 10:37:24.867163       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.ResourceQuota: Get https://172.19.76.243:6443/api/v1/resourcequotas?resourceVersion=1312&timeout=30s: context deadline exceeded

**Comment by superseb** [comment]
What is the setup, please fill in the issue template. Rancher single or HA, what Rancher version, what Kubernetes version if HA? Apparently it's fronted by NGINX, what is the logging showing there when this error pops up? The logging from `rancher/rancher` container is annoying but not relevant to this error, please supply more logging.
