### ISSUE TITLE
I want to deploy catalog on specific host

### ISSUE THREAD

**Issue by xrain0610** [rancher/rancher#2844]
--------------- SUGGESTS
Hi , I think , the catalog should add the filter of the hosts,
>i have more than 20 hosts, but only 5 host have storage (more than 1TB),
but  i only want to deploy the gluster-fs to the specific host.

>in addtion, I can't set the crrently volume on host , like /home (mount /dev/vdb1),
i think, the catalog should add more options to config,
thanks.

--------------- BUGS
i update the rancher to v0.47.0, find some bugs,

> 1. In host details (/infra/hosts/1h14/containers), when i change the host use the select input, but ,the page can't load new data , it also take the old data to show.

> 2. when i deploy the gluster-fs , then i delete it , but the STORAGE POOLS(/infra/storagepools) can't delete the pool.  it always show what i deleted.

**Comment by deniseschannon** [comment]
I'm going to break up your issue into different parts:

Created enhancement request to allow scheduling catalog entries based on host labels: https://github.com/rancher/rancher/issues/2852

"in addtion, I can't set the crrently volume on host , like /home (mount /dev/vdb1),
i think, the catalog should add more options to config,
thanks."

I'm assuming this is talking about the glusterFS catalog entry? I'll need @cjellick to comment on whether or not this would be possible before creating an enhancement request. 

As for your bugs,

1. I'm not sure what you mean. Have you tried clearing your cache? There is an open issue for browsers and upgrading. https://github.com/rancher/rancher/issues/2820

2. The storage pool is related to convoy-gluster. I'm assuming you have tried deleting that stack. There is an issue tracking the fact that the storage pool is not deleted. https://github.com/rancher/rancher/issues/2788

**Comment by deniseschannon** [comment]
@xrain0610 I've commented with updates on all the issues you had. Please open a new issue if you need any other assistance.
