### ISSUE TITLE
[Monitoring V2] Update default images on monitoring charts to Rancher mirrors

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#28441]
Need to update several images in monitoring charts to use Rancher mirrors

#### `rancher-monitoring`
- [x] quay.io/coreos/prometheus-operator
- [x] quay.io/prometheus/prometheus
- [x] docker.io/jimmidyson/configmap-reload
- [x] quay.io/coreos/prometheus-config-reloader
- [x] quay.io/prometheus/alertmanager
- [x] squareup/ghostunnel
- [x] jettech/kube-webhook-certgen
~k8s.gcr.io/hyperkube~ (removed from the chart)

#### `rancher-monitoring` subcharts
- [x] prometheus/node-exporter
- [x] kiwigrid/k8s-sidecar
- [x] grafana/grafana
- [x] quay.io/coreos/kube-state-metrics
- [x] directxman12/k8s-prometheus-adapter-amd64
- [x] bats/bats
- [x] curlimages/curl
- [ ] busybox

#### `rancher-pushprox`
- [x] alpine

**Comment by aiyengar2** [comment]
#### Note about https://github.com/rancher/charts/pull/576
This PR only merges in the default images to the `rancher-monitoring` and `rancher-pushprox` charts themselves. There will be a separate PR required for adding support for private registry and using Rancher images on the subcharts of `rancher-monitoring` since it may either require:
 - Forking the subcharts themselves into `rancher/charts` by introducing new `package.yaml` files and maintaining a patch for them
- Adding support to `rancher/charts` for supporting patches on subcharts.

**Comment by jiaqiluo** [comment]
on `master-4911f8b116eb845ce72bda40fc449f0a4ce54025-head`, install the monitoring v2 chart into the local cluster.

All images are pulled from Rancher's mirror 
```
> k get pods -n cattle-monitoring-system -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.containers[*].image}{"\n"}{end}'
prometheus-rancher-monitoring-prometheus-0	rancher/prom-prometheus:v2.18.1 rancher/coreos-prometheus-config-reloader:v0.38.1 rancher/jimmidyson-configmap-reload:v0.3.0
pushprox-kube-controller-manager-client-r24nw	rancher/pushprox-client:v0.1.0-rancher1-client
pushprox-kube-controller-manager-client-rpfz2	rancher/pushprox-client:v0.1.0-rancher1-client
pushprox-kube-controller-manager-client-zdhwf	rancher/pushprox-client:v0.1.0-rancher1-client
pushprox-kube-controller-manager-proxy-58cb99b888-7lqd8	rancher/pushprox-proxy:v0.1.0-rancher1-proxy
pushprox-kube-etcd-client-dnrbr	rancher/pushprox-client:v0.1.0-rancher1-client
pushprox-kube-etcd-client-h5qkq	rancher/pushprox-client:v0.1.0-rancher1-client
pushprox-kube-etcd-client-rxt2h	rancher/pushprox-client:v0.1.0-rancher1-client
pushprox-kube-etcd-proxy-6687f86784-mdfch	rancher/pushprox-proxy:v0.1.0-rancher1-proxy
pushprox-kube-proxy-client-dj5r5	rancher/pushprox-client:v0.1.0-rancher1-client
pushprox-kube-proxy-client-g68pj	rancher/pushprox-client:v0.1.0-rancher1-client
pushprox-kube-proxy-client-v2hbp	rancher/pushprox-client:v0.1.0-rancher1-client
pushprox-kube-proxy-proxy-6d879b7876-mnsqg	rancher/pushprox-proxy:v0.1.0-rancher1-proxy
pushprox-kube-scheduler-client-b82ds	rancher/pushprox-client:v0.1.0-rancher1-client
pushprox-kube-scheduler-client-r8rd2	rancher/pushprox-client:v0.1.0-rancher1-client
pushprox-kube-scheduler-client-v8b5l	rancher/pushprox-client:v0.1.0-rancher1-client
pushprox-kube-scheduler-proxy-5bc6f4bd96-bsbst	rancher/pushprox-proxy:v0.1.0-rancher1-proxy
rancher-monitoring-grafana-6cff987597-ps54z	rancher/kiwigrid-k8s-sidecar:0.1.151 rancher/grafana-grafana:7.0.6
rancher-monitoring-kube-state-metrics-7c55ddf46c-xfmlr	rancher/coreos-kube-state-metrics:v1.9.7
rancher-monitoring-operator-85969fcd66-z7p59	rancher/coreos-prometheus-operator:v0.38.1 rancher/squareup-ghostunnel:v1.5.2
rancher-monitoring-prometheus-adapter-5c6549fbb7-cm6bc	rancher/directxman12-k8s-prometheus-adapter-amd64:v0.6.0
rancher-monitoring-prometheus-node-exporter-d68bc	rancher/prom-node-exporter:v1.0.0
rancher-monitoring-prometheus-node-exporter-qjlk5	rancher/prom-node-exporter:v1.0.0
rancher-monitoring-prometheus-node-exporter-wkb7x	rancher/prom-node-exporter:v1.0.0
```

New issue will be logged if needed.
