### ISSUE TITLE
validation on field.cattle.io/publicEndpoints usage

### ISSUE THREAD

**Issue by ninjaslothx** [rancher/rancher#28448]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

Hey, I'm just wondering if someone can help explain the annotation on the nginx ingress
`field.cattle.io/publicEndpoints: [{"addresses":["x.x.x.x"]`

All of my ingress deployments are getting this annotation and ending up with the same external IP. 
Is this configurable/where is this setting coming from?
It appears to be a list, can we add more than 1 IP to this default annotation? 

Any help would be appreciated!

**Comment by theAkito** [comment]
How did you solve this issue?

**Comment by qrkourier** [comment]
I too am investigating the same clue. I don't know why my ingresses have this IP address. I'm running Rancher Desktop and the Traefik ingress has a new IP that's unreachable from the host machine.

**Comment by theAkito** [comment]
From what I understand now, after my investigation, once the Ingress is "found" by your Ingress Controller, it is "registered", which includes setting this label.

The IP is most likely the IP assigned to the node, where the Ingress Controller resides.

Did you already post on the [Traefik Forum](https://community.traefik.io/)?
