### ISSUE TITLE
[feedback] [ui] new design v0.47.0

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#2845]
Hey there,
somewhere I had read that feedback to new ui is welcome. Now here is mine.
First of all I know it is sometime hard to tell what important information is and what is not. For me **Applications > Stacks** degraded in this category. Here is what I missing now (what I had before)
* **Active service links.** In my experience it was nice to see which links are given in a complete stack. E.g. I have a service sometimes switching links to other service. Now I can't see (at one glimpse) which ones are active and which are not. (Also if a service is deleted and recreated all his connection/links are lost. The old view helped me to see this at once). Maybe if was able to setup somewhere what I want to display in the info sections. (e.g. load balancer show links) Image name is not that important for me to be displayed here.
* **Direct access to service container.** I had direct access to service container e.g. able to get directly logs. Now I have go into service view logs go back and so on. The **(i)** beside of the name gives me an extended view on the service but also not to containers (e.g. logs).

Furthermore **Applications > Stacks**: I can see the benefits switching from columns/boxes to rows. But as I mentioned before it would be more powerful if I was able to configure the displayed information as mentioned before.
I like the **extend tab view** for services, also recognizing of services using the same image and displaying tabs beside of the currently viewed tab. But also here if I was be able to configure what I see it would be more powerful. E.g. I rather had environments variables instead of *Info* column.

**Infrastructure > Hosts**: (where are)/miss the round corners. : /  

Overalls for me it feels like it got inspired by Microsofts tile / box / Excel view which is not that appealing for me but I definitely see the benefits mentioned before.

Keep it up! I like what you creating here and I am thankful for that. :+1:

**Comment by nlf** [comment]
I very much agree with the log accessibility comment. Being able to reach the logs for a container is pretty crucial, so as simple as it can be made is best.

**Comment by sshipway** [comment]
The immediately visible Service Links and Logs are something I miss, though they are still accessible via another step (click service name)  and I understand that screen space needs to be saved.  Our system is litkely to end up with hundreds of Stacks and the old UI was only practical with a dozen or less.

One thing still missing is an easy way to view the Scheduling rules for a service.  Currently, you have to deduce them from looking at the labels; it would be more helpful to have them explained in the service information.

**Comment by vincent99** [comment]
FWIW I don't disagree..  I did sneak in right-click on the container state icons in the (i) info popup so you can get to the container actions directly from there.

**Comment by mishak87** [comment]
@vincent99 Sneaky and very useful thanks!

**Comment by ebr** [comment]
Agree with the comments from @fentas and @sshipway. @vincent99 not sure if I'm missing something, but I don't see the right-click menu you've mentioned...

Another thing I'd like to point out: 
![screen shot 2015-11-30 at 11 38 47 am](https://cloud.githubusercontent.com/assets/2433541/11477647/f38dcfa2-9756-11e5-85db-45417c028d76.png)

with the "Stop" button being where it is now, it has become very easy to accidentally stop a service when trying to get to the drop-down menu - especially while on a dinky trackpad or on mobile. The "stop" function could benefit from a confirmation prompt in this layout.

I generally preferred the old layout, but "change is scary", so i'll reserve my judgement until getting more familiar with the new one.

**Comment by jloisel** [comment]
I prefer the previous layout too. This one feels too bright to my eyes. I miss the boxes in the stacks view, rows are painful to read. I would love to have all the information on the graph view. I like this view because it shows clearly how the containers are linked together.

Btw, the graph icon is still broken on chromium on my machine. It works only with Firefox or Google Chrome. Other icons are fine. Not sure what goes on with this one.

**Comment by ebr** [comment]
ah, @deniseschannon explains where to find the right-click menu in this comment: https://github.com/rancher/rancher/issues/2849#issuecomment-160702674 :) Awesome.

**Comment by vincent99** [comment]
@lvuch is working on a design that will make the actions on the dots discoverable rather than having to know that you can right-click on them.

**Comment by will-chan** [comment]
@lvuch can you review this and work on changes to make the UX better?  This is good feedback.

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/12629127/b19dc072-c503-11e5-8897-73077a8be4d0.png)

**Comment by tfiduccia** [comment]
version - master 1/27
Verified fixed
