### ISSUE TITLE
Installed Rancher in an RKE cluster, getting connection refused and cert-manager cannot complete challenge

### ISSUE THREAD

**Issue by vitobotta** [rancher/rancher#28463]
**What kind of request is this (question/bug/enhancement/feature request):**
Not sure if it's a bug. 

**Steps to reproduce (least amount of steps as possible):**
I deployed an RKE cluster I want to use with Rancher in HA mode. Then I installed cert-manager and Rancher with helm just fine. No errors or anything like that. However cert-manager cannot complete the challenge because requests to the challenge URL return a connection refused. I get the same with curl. One thing I am wondering is that in the ingress-nginx namespace I see only one service for the default backend. Shouldn't there be another service there? I tried removing and readding the ingress controller with RKE but it's still the same. Requests to the IP of the node on port 80 work as expected with the default backend.

**Result:**
Cannot connect to ingress controller on port 80 and cert manager cannot complete the challenge to issue the certificate, so I cannot open Rancher.

**Other details that may be helpful:**
Not sure if it may be relevant but I am using Weave for the encryption.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.4.5
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VPS, 2 cores, 8GB of ram
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
19.03.12
```

**Comment by superseb** [comment]
Can you supply additional info?

* What RKE version did you use to create the cluster?
* Are the `nginx-ingress-controller` pods running? (https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-resources/#ingress-controller)
* What is the response when you curl the IP on port 80? (`curl -v`)
* What is the response when you curl the FQDN? (`curl -v`)
* What does the FQDN resolve to?

**Comment by vitobotta** [comment]
@superseb I forgot to close this. Ehm.... this is embarrassing but I had set the wrong IP in the DNS record :p
