### ISSUE TITLE
[feature] Roles for API keys

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2846]
There should be some way to assign roles to API keys.  Thus, an API key could be restricted to Read-Only functions, or Developer access.

In addition it would be useful (for monitoring purposes) to be able to create global API keys that will work for ALL Environments, or for a specified subset, or that have Admin rights.  This would allow the API to be used to create new Environments.

**Comment by vincent99** [comment]
This half exists, though not in the UI.  If you go to /v1/apikeys in a browser you can create a key for the user/account rather than a project.  It has access to whatever the account who owns it does, including creating new environments ("projects" in the API).

**Comment by sshipway** [comment]
Interesting, but not so helpful for us as we use LDAP as the backend and so cannot easily create a special account for an API key (our backend LDAP synchronises through to somany things that we cannot create service accounts in it like this)
I am assuming that API keys generated through the UI are not associated with a user identiy, but are associated with the Environment (and so do not have access to other environments).  I may be wrong on this though, as there is not much information online about this
