### ISSUE TITLE
Allow docker logs support for rke on logging v2

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#28460]
Users should be able to configure rke1 to get logs from the docker containers rather than the rke log.

**Comment by sangeethah** [comment]
Blocked on https://github.com/rancher/rancher/issues/28741

**Comment by izaac** [comment]
I get logs from the RKE additional sources now in RKE clusters but I've opened a couple of issues, one, not all the logs are getting collected from start of file and the other im not getting all the log files event logs in the output (Elasticsearch) I opened separate issues for follow up.

#28796
#28799
