### ISSUE TITLE
Combine k3s options into single flag for logging v2

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#28461]
Users should be able to select which container daemon they are using for k3s rather than choosing between 2 top level k3s options.

**Comment by paynejacob** [comment]
the new format is

k3s:
  enabled: true
  container_engine: "systemd"

**Comment by izaac** [comment]
Rancher version:

The k3s additional sources flags are working when installing the chart and using `values.yml`. 

Log collection for control plane sources is still under development https://github.com/rancher/charts/pull/549


Still need to cover `openrc` container_engine.

**Comment by izaac** [comment]
Rancher version: `master-head (08/26/2020)` _9b6984d5f_

Validated the `container_engine: "openrc"` option with k3s on Alpine.

Pre-requirement for Alpine: https://rancher.com/docs/k3s/latest/en/advanced/#additional-preparation-for-alpine-linux-setup

Opened a separate issue for uninstall error: #28565
