### ISSUE TITLE
Istio v2: Grafana Addon

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#28468]
- [x] Ensure Rancher monitoring's grafana can be used.
- [x] Ensure that grafana dashboards are being installed/updated and working properly. See [new guide](https://istio.io/latest/docs/ops/integrations/grafana/#import-from-grafana-com), ideally we can bundle that in our installer.

**Comment by cbron** [comment]
PR available here: https://github.com/rancher/istio-installer/pull/13

**Comment by bmdepesa** [comment]
`rancher/rancher:v2.5-head 0465f04`
Chart test, so not needed on master-head

* Create a cluster
* Deploy a cluster
* Enable Rancher monitoring
* Enable Istio with ingress gateway
* Deploy some demo app and create traffic
* Navigate to Grafana from Rancher Monitoring overview page
* All new graphs are shown and contain some data -- these graphs come from Istio so did not do excessive testing

![Screen Shot 2020-10-22 at 8 13 12 AM](https://user-images.githubusercontent.com/21316915/97711548-7834f180-1a7a-11eb-9ff3-245ef957badd.png)
