### ISSUE TITLE
[UI] Ability to view Logs and Execute the console from the stacks view

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#2849]
First off, love the new ui, great job!

One of the problems i've found so far is that when in the stacks view, when i use the down arrow on a specific container, i no longer have the options to view the logs or the open a console from there.  i'm forced to go find the container in the infrastructure view to get at those two commands.

![screenshot 2015-11-30 10 28 08](https://cloud.githubusercontent.com/assets/26738/11475831/71084bb0-974d-11e5-9241-5899372c1a82.png)

**Comment by liubaishui** [comment]
+1

**Comment by deniseschannon** [comment]
Click on the info icon "i" next to the service name. It will pull up a summary view of the service with an icon of containers. Right click on a container icon and you have the all the container options.

**Comment by ebr** [comment]
@deniseschannon thanks for clearing up where to find that elusive right-click menu! :)

**Comment by deniseschannon** [comment]
@jwhitcraft @liubaishui I'm going to close as there is an easy way to do this on the stack view. 

![screen shot 2015-11-30 at 11 02 09 am](https://cloud.githubusercontent.com/assets/11410997/11481355/d4b518f6-9751-11e5-800f-b3e3e08b6d58.png)
