### ISSUE TITLE
Moving a rancher/server to a new host

### ISSUE THREAD

**Issue by shakefu** [rancher/rancher#2850]
I couldn't find any docs on this - so I thought I'd ask. We have to move our rancher/server to a new host because we ran out of disk space.

Is there a best practice for how to do this? We have already upgraded the service once, so we're using volumes-from with the old container. We tried committing that container and exporting the image, but the new host didn't seem to pick up the configuration.

**Comment by andyshinn** [comment]
I tried to do this recently and was unsuccessful. See http://forums.rancher.com/t/how-to-reconnect-agents-to-moved-server/928/3 for more information. What I did not try was just running the agent `docker run` command again on an already running agent (I stopped and removed the agent first). Sorry this isn't really answering the question. But hopefully gives you some things to think about.

**Comment by shakefu** [comment]
We managed it with roughly the following steps:

1. Stop rancher/server
2. Dump /var/lib/mysql from rancher/server container (or in our case, because we had upgraded, the rancher-data container).
3. Extract the dump on the new host.
4. Fix the permissions of the dump.
5. Start up rancher/server on the new host.
6. Change the Host Registration to point at the new host.
7. For each of the hosts in the infrastructure, stop the rancher/agent.
8. For each of the hosts in the infrastructure, start a new rancher/agent using the Custom Host docker command for the new rancher/server.
9. Rejoice.

We also tried the "lazy" approach:
We have an Auto Scaling Group where instances self-bootstrap themselves into the Rancher cluster using the API to get a registrationToken.

Destroying an instance and allowing the ASG to recreate one, while also deleting the host from Rancher (to reschedule its containers) did work to get a new live host running.

However, we ran into a Docker bug where the many simultaneous pulls of docker images in the bootstrapping caused layer corruption. It was also considerably slower to destroy/initialize/bootstrap/reschedule than to just restart the rancher/agent, so we abandoned that.

Neither of these approaches was particularly fast, or scalable, since we had to go into each host to stop and reload the rancher/agent. It got the job done since we're currently only piloting 5 hosts, but if we'd had a full production infrastructure of several hundred hosts, it would have been *extremely* painful. 

I suspect if we were using Rancher in Production we'd want the HA setup anyway, which looks like it's still pretty far away from being easily deployable. However that would probably let us fail over the rancher/server to a new host instead of having to deal with all this.

**Comment by digitalLumberjack** [comment]
That would be very convenient :+1:

**Comment by ryanaverill** [comment]
+1

**Comment by will-chan** [comment]
We have a brand new way of deploying this in an HA Setup.  Hopefully, this will take the pain away of moving the Rancher to a new host with a new IP.

**Comment by djskinner** [comment]
Awesome. Is there some documentation about how to do this?

**Comment by EugenMayer** [comment]
done this right now, but rather 
```
docker exec -it rancher-server bash
mysqldump --all-databases > /tmp/alldbs.sql
exit
docker cp rancher-server:/tmp/alldbs.sql .
scp alldbs.sql newserver:
```

Then join your new server and install rancher-server just the usual way. When it is up and running

```
docker cp alldbs.sql rancher-server:/tmp
docker exec -it rancher-server bash
mysql < /tmp/alldbs.sql
exit
docker stop rancher-server
docker start rancher-server
```

Now you will need to enable auth again and as it has been written before, readjust every single host / agent to follow the new ip

**Comment by nico01f** [comment]
I'm suggest my post, sorry for my english but i just want help.

https://medium.com/@nifo/how-to-migrate-a-rancher-server-593a0aaa3192

**Comment by superseb** [comment]
Here's another guide: https://gist.github.com/superseb/f44d51cc42c7e5a0049d393d6d2563e7
