### ISSUE TITLE
[UI] Invalid UI Banners setting causes full UI failure

### ISSUE THREAD

**Issue by nikkelma** [rancher/rancher#28504]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Option A: Set the `ui-banner` value to invalid JSON (e.g. `This is my banner`)
Option B: Set the object to have a field `showHeader` or `showFooter` as a non-string value (e.g. `{"showHeader": false}`)

**Result:**
Option A: Error with message "Unexpected token T in JSON at position 1" is displayed
Option B: Error with message "t.showHeader.toLowerCase is not a function" is displayed

**Other details that may be helpful:**
No validation occurs for settings, and the UI does not account for any exceptions thrown

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): any

**Comment by sowmyav27** [comment]
2.4 PR: https://github.com/rancher/ui/pull/4140/files

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.4.6-rc11**

Option A: Set the ui-banner value to invalid JSON (e.g. This is my banner)
Option B: Set the object to have a field showHeader or showFooter as a non-string value (e.g. {"showHeader": false})

Option A: gives error: `Unexpected token a in JSON at position 0`
OptionB: gives error
<img width="524" alt="Screen Shot 2020-08-28 at 2 29 33 PM" src="https://user-images.githubusercontent.com/26032343/91616899-90ce4180-e93b-11ea-9ed7-b15239078169.png">


**On 2.4.6**

Option A --> Error in console - `Uncaught (in promise) SyntaxError: Unexpected token d in JSON at position 0`
OptionB --> works fine. User is able to load UI

**Comment by nikkelma** [comment]
Didn't notice the error in the console when the UI was working as expected, apologies for missing that. What endpoint are you hitting that you get `Uncaught (in promise) SyntaxError: ...`? I can only recreate when going to the settings page directly.

**Comment by nikkelma** [comment]
When I could recreate the error in the console, the cause was due to the settings danger-zone component also assuming a setting with kind `json` can always be successfully parsed as JSON [1]. This call is only used to pretty-print the contents of the setting; @westlywright what do you think about falling back to the raw setting text if `JSON.parse` fails?

[1] https://github.com/rancher/ui/blob/2aa083b7acb022e7a98fcfd2909a52b095d9bd98/lib/shared/addon/components/settings/danger-zone/component.js#L71-L76

**Comment by sowmyav27** [comment]
@nikkelma Option A --> Error in console - Uncaught (in promise) SyntaxError: Unexpected token d in JSON at position 0 --> Was seen On Settings page --> Edit UI Banners to have an invalid value "This is my banner". Click on Save.

**Comment by nikkelma** [comment]
Perfect, thank you @sowmyav27! I don't want to miss anything in this second pass.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `27000be` ui tag: `latest2`**

- Option A: Set the ui-banner value to invalid JSON (e.g. This is my banner)
- UI does not load
- Error in console:

```
Uncaught SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at n.init (component.js:36)
    at n [as init] (utils.js:365)
    at b (core_object.js:89)
    at Function.e.create (core_object.js:686)
    at e.n.create (container.js:554)
    at t.a.create (glimmer.js:5540)
    at Object.evaluate (runtime.js:1569)
    at e.t.evaluate (runtime.js:73)
    at e.t.evaluateSyscall (runtime.js:3488)
```
- Option B: Set the object to have a field showHeader or showFooter as a non-string value (e.g. {"showHeader": false}) --> Works. No error seen

**Comment by nikkelma** [comment]
What setup exactly was used to produce this issue? I ran the following:
```
docker run --privileged -d --restart=unless-stopped -p 80:80 -p 443:443 \
  rancher/rancher:master-27000be7ea7eba97cc8efd59d7e58515e9538d30-linux-amd64
```
and attempted to recreate, but saw no errors. If I can recreate and get a fix out tomorrow, I'd like to see if this can make it into 2.5 GA, else I'll happily push it to 2.5.x.

**Comment by sowmyav27** [comment]
@nikkelma This was on a HA setup using RKE cluster. 
The UI failed to load after these steps
- Set the ui-banner value to invalid JSON (e.g. This is my banner)
- Click on "Edit `ui-banner`" option in the UI. The UI is stuck

**Comment by sowmyav27** [comment]
**On master-head - commit id: `c3bc230fe` ui tag: `latest2`**

1. Set the ui-banner value to invalid JSON (e.g. This is my banner)
2. Set the object to have a field showHeader or showFooter as a non-string value (e.g. {"showHeader": false})

No errors seen in the above two usecases. User is able to edit and save. UI loads.
