### ISSUE TITLE
[Forward port] Windows parameter issues

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28507]
This is to track the forward port effort for the following issue:
https://github.com/rancher/rancher/issues/25108
https://github.com/rancher/rancher/issues/28143
https://github.com/rancher/rancher/issues/28440

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `8d9cedde9`**

**Scenario#1**
- User is able to deploy windows cluster with NO prefix path set - 1 linux node, 2 windows worker nodes. (1903)
- `"RKE_NODE_PREFIX_PATH=c:/",` docker inspect kubelet shows.

**Scneario#2**
- Deploy a windows 1903 cluster with prefix path in cluster.yml as
```
prefix_path: /opt/custom_path/
win_prefix_path: 'c:\host\opt\'
```
- Cluster comes up successfully
- docker inspect kubelet shows `"RKE_NODE_PREFIX_PATH=c:\\host\\opt",`

**Scenario#3**
- Deploy a windows 1903 cluster with prefix path in cluster.yml as
```
prefix_path: /opt/custom_path
win_prefix_path: 'c:\host\opt'
```
- Cluster comes up successfully
- docker inspect kubelet shows `"RKE_NODE_PREFIX_PATH=c:\\host\\opt",`
