### ISSUE TITLE
[UI] Rancher UI multi download of kubeconfig clusters files

### ISSUE THREAD

**Issue by asemen2608** [rancher/rancher#28503]
**What kind of request is this (question/bug/enhancement/feature request):**

feature request

   A **multi-select option for download kubeconfig** files for many clusters at the same time.
  implementation can be different, at this point it's an exploratory request.

    Want to be able to select a number of clusters and ideally be able to download one mega-kubeconfig file.

**Steps to reproduce (least amount of steps as possible):**

In UI select   -> global -> clusters  there is not filed to select kubconfig file for download

**Result:**
no multi download 

**Other details that may be helpful:**

To give a bit more context here:
    The customer has many clusters. Dozens. Operators managing these clusters want to be able to manage them from their laptops.
    Now they go to each cluster individually and manually download kubeconfig, then work with them using CLI tools, That’s cumbersome & error-prone.

Suggestion:    
A select filed in the cluster view to mark and download the kubectl config file at once for example as a zip file.
See the red marked part:

See screenshots below

**Environment information**
- Rancher version 2.4.5 

- Docker version  all 

gz#11880

**Comment by asemen2608** [comment]
![rancher-fr2_](https://user-images.githubusercontent.com/61939253/91042656-69613700-e612-11ea-8752-c7ea325b0a3f.png)

**Comment by asemen2608** [comment]
A summary Download link for all marked Kubeconfig files or cluster to be like shown here "Download KUBCONF:"

**Comment by superseb** [comment]
This sounds like an extension of https://github.com/rancher/rancher/issues/13853

**Comment by bgagnon** [comment]
An archive of multiple kubeconfig YAML files is less usable then the merged approach described in #13853.

**Comment by asemen2608** [comment]
Could the download of Konfig File per cluster be implemented in Rancher v2.4.x and v.2.5.x?

**Comment by asemen2608** [comment]
Any update?

**Comment by asemen2608** [comment]
Could we get the cluster kubeconfig filed download in Rancher v2.5.3?
(To choose kubeconfig file per cluster for download)

**Comment by leodotcloud** [comment]
Agree with @bgagnon, just downloading all the kubeconfig files is not useful at all but a merged one would be. Closing this in favor of 13853.
