### ISSUE TITLE
[UI] Rancher UI display Validation failed in API: StatefulSet.apps "test" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

### ISSUE THREAD

**Issue by gsakun** [rancher/rancher#28500]
# What kind of request is this (question/bug/enhancement/feature request):

bug: after deploy a statefulset workload with pvc , If I want to edit some properties of this workload , such as env, then it will show Validation failed in API: StatefulSet.apps "test" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden in the rancher UI, but the prompt indicates that these properties are modifiable, and it can be modified normally by editing YAML. See the screenshot below for details:
![image](https://user-images.githubusercontent.com/24608247/90870832-c075ca80-e3cc-11ea-9cbb-3120b5dd3f19.png)

# Steps to reproduce (least amount of steps as possible):

1. Create a statefulset workload with A PVC template and add env on the UI
2. Edit this workload env,then click save and the issue will accurrd

# Result:

display Validation failed in API: StatefulSet.apps "test" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.

# Other details that may be helpful:

same problem in rancher v2.2.0

# Environment information

- Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI):
  Rancher version: 2.4.5
- Installation option (single install/HA):
  single

# Cluster information

- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
  Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
  VM: 6
  cpu: 8 core
  memory: 12 G
- Kubernetes version (use kubectl version):
  v1.15.3
- Docker version (use docker version):
  18.09

**Comment by athosss** [comment]
@nikkelma same problem in v2.4.5

**Comment by gsakun** [comment]
![image](https://user-images.githubusercontent.com/24608247/91537180-79e21c00-e948-11ea-821f-76b53d7fd948.png)

**Comment by gsakun** [comment]
![image](https://user-images.githubusercontent.com/24608247/91537373-c4639880-e948-11ea-97eb-d52de8d9f8c7.png)
