### ISSUE TITLE
[UI]: After use comtue rancher/ui ,the api-ui view don't visit on offline .

### ISSUE THREAD

**Issue by PmcFizz** [rancher/rancher#28525]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
on offline,  when I use a custom rancher/ui , I find the api-ui view don't visit。  and I find after I use custome rancher/ui for rancher, the api view load `rancher.com` source。 as picture

![image](https://user-images.githubusercontent.com/13403284/90995847-c13a7680-e5ef-11ea-81b9-8dfe8dfea465.png)

**can you offer a way to use custome ui and api-ui can visite on offline ?**

**Result:**
api-ui don‘t visite on offline

**Comment by vincent99** [comment]
If you're using master or another non-release build, you can change them but `ui-index` and `api-ui-index` point to our CDN by default intentionally.

**Comment by PmcFizz** [comment]
Thanks your fast repley.  can you support modify `api-ui-index` point to my CDN ?

**Comment by PmcFizz** [comment]
@vincent99  Hi， if don‘t support modify `api-ui-index` after deploy custom ranhcer/ui now.  please tell me .thanks.
