### ISSUE TITLE
Bindings: Allow host label scheduling for catalog entries

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2852]
V0.47.0

It would be nice to be able to specifically schedule catalog entries on certain hosts based on host label

Source: #2844

**Comment by pdaniel-frk** [comment]
Hello,

What is the status of this issue? Did you managed to do something with it?

Regards.

**Comment by deniseschannon** [comment]
This issue is still open and currently not targeted for a release.

For now, a workaround would be to preview the catalog item and you can download the docker-compose.yml and rancher-compose.yml and edit them to add in the host labeling scheduling requirements. You can either use the "Add Stack" to add in the files or rancher-compose CLI.

**Comment by sangeethah** [comment]
Tested with Rancher server version - v1.2.0-pre4-rc1.

While creating stack , we now provide the ability to override "labels" and ""ports" that are specified in docker-compose/rancher-compose.yml files by passing bindings parameter.

Need UI support for exposing the bindings parameters.

**Comment by joshwget** [comment]
After discussing with @ibuildthecloud and @vincent99, we're going to go with #3239 instead of adding bindings.
