### ISSUE TITLE
For clusters provisioned with rancher2 TF provider, nginx ingress comments are injected into cluster yaml when editing via the UI

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#28532]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1) provision downstream cluster using rancher2 TF provider
2) edit new downstream cluster in the Rancher UI

**Result:**
The cluster won't be able to be saved as nginx ingress comments are injected into the cluster yaml and need to be removed to be able to save. The screenshot below has an example of this issue

**Other details that may be helpful:**

![image](https://user-images.githubusercontent.com/55704795/91069695-ba1d6380-e603-11ea-9b44-d291584b33b2.png)

**Environment information**
- Rancher version: v2.4.5
- Installation option: HA

**Cluster information**
- Cluster type: Custom
- Kubernetes version: v1.17.5

gz#11486

**Comment by deniseschannon** [comment]
It seems like because the addon in the cluster.yaml has the word "ingress", it's injecting additional comments into the cluster.yml. 

How do we decide how to add comments into the yaml when editing the yaml? @westlywright

**Comment by westlywright** [comment]
The final decision on this was to remove comments from the edit cluster yaml.

**Comment by izaac** [comment]
Rancher version: `v2.4.5`

I used the rancher terraform quickstart aws provider. It setups a rancher server with a custom downstream cluster. You can check it here: https://github.com/rancher/quickstart/tree/master/aws

After the cluster becomes active and I tried navigating to Cluster Edit -> Edit as YAML -> Edit the cluster name -> Save

I am able to save the new config. Not able to reproduce.

@rosskirkpat is there a terraform configuration file or specific configuration that we can use to reliably reproduce this issue?
cc @westlywright

**Comment by westlywright** [comment]
@izaac I never mentioned that but the root cause has nothing to do with the TF provider, you just need another key in the cluster config that has `ingress` in it. I was able to reproduce by doing the following:

Create cluster
Edit Cluster as yaml, after the `addon_job_timeout` key place the following (ensure the indentation matches the aforementioned timeout key)
```
addons: |-
  ---
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: test-network-policy
    namespace: default
  spec:
    podSelector:
      matchLabels:
        role: db
    policyTypes:
    - Ingress
    - Egress
    ingress:
    - {}
```
Save the cluster.
Edit the cluster and select the yaml view again. It was at this point you'd see the comments get inserted above `ingress` mentioned in this ticket. With the new code, you should not see any comments from Rancher in the file.

**Comment by izaac** [comment]
Reproduced in `2.4.5` with the steps provided by @westlywright

**Comment by izaac** [comment]
Rancher version: `v2.5-head (12/10/2020)` _baf4867_
Rancher version: `master-head (12/10/2020)` _46b0df4_

There aren't any more comments in the Edit as YAML view.
Editing and adding the yaml with `ingress` keywords doesn't inject any comments. 
I am able to save the 2.4.5 code and edit and save again without issues.
