### ISSUE TITLE
Dashboard - cluster namespaces dropdown in Global Nav showing namespaces as Not in Project for downstream clusters

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28537]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- Install Rancher (Single or HA)
- Deploy an RKE cluster I used single node cluster.

**Result:**

In the Global Nav Bar the Combobox dropdown shows Projects but not the namespaces under the project. 
All the Namespaces are shown as **Not in a Project**

**Other details that may be helpful:**

Cluster with the issue:

![Screen Shot 2020-08-24 at 12 13 37 PM](https://user-images.githubusercontent.com/27659/91086816-4af43f00-e604-11ea-88b5-3e9884856827.png)

Cluster without the issue **(local cluster HA)**:

![Screen Shot 2020-08-24 at 11 30 38 AM](https://user-images.githubusercontent.com/27659/91086869-5f383c00-e604-11ea-9937-db61e4316899.png)

**Environment information**
- Rancher version: `master-head (08/24/2020)` _8a60de75d_
- Installation option: single/HA

**Comment by sangeethah** [comment]
The same issue is also seen when testing Dashboard on rancher installed using docker command.

**Comment by vincent99** [comment]
Do they show up in a project in the old ui?

**Comment by izaac** [comment]
Yes this is working fine in the Ember UI.

Comparing the local cluster list of namespaces response and the downstream cluster response we found that the downstream data is missing the project label:



```json
 "labels": {
                "field.cattle.io/projectId": "p-5v9hg"
            },
```

**Comment by dramich** [comment]
I think this is caused by https://github.com/rancher/rancher/issues/28338

**Comment by vincent99** [comment]
@dramich i don't see how that's related?

Apparently there's both a label and an admiration for the project id but the annotations is the important one and the dashboard is currently using the label.

**Comment by dramich** [comment]
@vincent99 the root cause of the other issue is the controllers not being ran in the agent. One of the controllers is the `namespaceHandler` which translates from the anno to the label on the namespace.

**Comment by izaac** [comment]
Rancher version: HA k8s `master-head (08/26/2020)` _a1acca856_ 

Validated this is working on local cluster, and downstream rke, imported k3s, gke clusters.

**Comment by izaac** [comment]
Rancher version: `master-head (08/27/2020)` _5e1b21b93_

I tried this in a Rancher **single install using docker**, DO cluster I still see this issue. HA local and downstream in the HA Rancher is looking good.

**Comment by deniseschannon** [comment]
This doesn't appear to be an issue now. Due to the changes in docker run and being able to start handling eks-operator and stuff, that also affected the ability to add the labels that the UI was using in dashboard. 

Can you please test @izaac?

**Comment by izaac** [comment]
@deniseschannon sure I will check on a recent Rancher build.

**Comment by izaac** [comment]
Rancher version `master-head (09/17/2020)` _ 33f755f_ HA k8s
Rancher version `master-head (09/17/2020)` _ 33f755f_ Single Install

- Validated the `local` cluster the menu shows Projects and Namespaces.
- Validated the `downstream` clusters the menu shows Projects and Namespaces.
- Validated I can use the namespaces filters dropdown.
