### ISSUE TITLE
UI Updates - Set View Preference, Banners showing off cluster explorer/v2 tools

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#28534]
*New User Login*
- [x] Add in ability to set your view (cluster manager vs. cluster explorer). 
       * The should be a default to select "cluster manager" for upgraded setups and automation, but the UI should not select a default in order to have the user to specifically select one. 
       * There should be text that indicates you can change this view in user settings. 

*First Log in to 2.5*
- [x] Show a splash screen with what’s new in 2.5 and anything we want to highlight. This should be added in regardless of your view preference. 

Note: Text and bullet points still TBD. 

*Cluster Overview*
- [x] Add banner that can be removed/cancelled that highlights Cluster Explorer benefits. Ability to click on banner to go to Cluster Explorer. 

 Note: Final Banner still TBD.

*Navigation Bar*
- [x] Any time we are within a cluster/project, show the cluster explorer button where the "try dashboard" button is today. 
- [x] Add into Cluster level tools, links for tools only available in cluster explorer. These should go to the Apps/Marketplace page. Could they select the actual app?
    - [x] Backup and Restore
    - [x] Fleet
    - [x] OPA
    - [x] Rio

*v1 Tools Pages*
- [x] Add banner (similar to cluster overview banner) that cannot be removed/cancelled. This banner indicates that a v2 version of the tool exists in cluster explorer. Clicking on it should bring you to Apps/Marketplace page. If possible, also ability to have selected that app?
  - [x] Monitoring (Cluster, Project)
  - [x] Alerts (Cluster, Project)
  - [x] Notifiers (Cluster)
  - [x] Istio (Cluster)
  - [x] Logging (Cluster, Project)
  - [x] CIS Scans (Cluster)
  - [ ] Catalogs (Global, Cluster, Project)
  - [x] Multi-Cluster App (Global)

Note: Final banner still TBD

**Comment by cloudnautique** [comment]
In the "whats new" banner we are going to cover a broad list of the new features, and include text from the release notes to describe. 

Here is the list of features we can use for now, can we include some lorem ipsum to describe the features underneath. I don't know that we want people hung up on words yet.

```
Fleet - GitOps at Scale
EKS Cluster enhancements
Monitoring v2
Logging v2
CIS v2
Istio
Rancher Backup / Restore Operator
New single binary Rancher install
Registered Cluster support
New Cluster Explorer view
```

For the monitoring, logging, and CIS tools pages we should include messaging:

`We have made big improvements to <tool> click here(docs link) for details on whats new and how to migrate`

**Comment by cloudnautique** [comment]
For the cluster explorer view:

`Try out the new cluster explorer to view and manage your Kubernetes resources. `

**Comment by maggieliu** [comment]
What's new wording: https://granitecomputing.sharepoint.com/:w:/s/ProductManagement/EVaXgbySaXRNtsWonaCIes8BOTbhCI29KNAaKhPUNAzbBA?e=fsxTZI

**Comment by maggieliu** [comment]
The information should be from this release notes: https://github.com/rancher/rancher/releases/tag/untagged-d396a40fd14da55f7f02

**Comment by deniseschannon** [comment]
Decided to push out figuring out what to do with catalogs until post 2.5.
