### ISSUE TITLE
Running on specific host

### ISSUE THREAD

**Issue by thbeh** [rancher/rancher#2853]
From the rancher web gui, how can I configure a container to run on a specific host instead of letting rancher to determine

**Comment by andyshinn** [comment]
1. Navigate to *Stacks* and click on a stack (such as `Default`)
1. Click the *Advanced Options* link under the configuration
1. Click on the *Scheduling* tab
1. Click the radio button to *Run all containers on a specific host*
1. Select the host the container should be run on

**Comment by thbeh** [comment]
Could I also use either docker-compose or rancher-compose to do the same?

**Comment by deniseschannon** [comment]
Adding a host label to the host and using a scheduling rule can accomplish the same thing. 

Host Label Info: http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/#host-labels
Scheduling Rules in Rancher-Compose: http://docs.rancher.com/rancher/rancher-compose/scheduling/
