### ISSUE TITLE
Missing a service link from container details view

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#2854]
http://forums.rancher.com/t/reverse-container-link-to-its-service/1089?u=kaos
> There is links from Stack -> Service -> Container (And host), but once in the container view, I miss a link going back to the service. Which would also come in handy, of course, if you reach the container view from the infrastructure/containers list, to get to the service view for that container.

**Comment by deniseschannon** [comment]
+1

**Comment by sshipway** [comment]
+1 -- This has been annoying me for ages.  It's not so big, but improves usability of the UI

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/13901773/d6dad968-edeb-11e5-9fdb-12e9f5570a34.png)

**Comment by kaos** [comment]
👍🏽
sön 20 mars 2016 kl. 00:01 skrev Vincent Fiduccia <notifications@github.com

**Comment by tfiduccia** [comment]
Version - master 3.20
Verified fixed
