### ISSUE TITLE
Add button to be show import cluster command when no cluster has been registered or add hosts to a custom cluster if no hosts have been added

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#28548]
Currently if you import a cluster and don't save the kubectl command, later the command is unfindable. 
Similarly, if you try to add a custom host, which provides a docker run command, the command is hidden in the "Edit" view of the cluster. 

On the cluster overview page, can we add an image/button to re-direct back to the pages from the import/custom pages that provide the commands if there are no hosts added to the cluster? 

As soon as a node is registered, this should be removed. 

**Imported Cluster Overview** 
<img width="1213" alt="Screen Shot 2020-08-25 at 7 45 03 AM" src="https://user-images.githubusercontent.com/11410997/91189166-f6ee6680-e6a6-11ea-971a-a6b4bde8f702.png">

Redirect to "Import Cluster" page:

<img width="1204" alt="Screen Shot 2020-08-25 at 7 49 49 AM" src="https://user-images.githubusercontent.com/11410997/91189669-94e23100-e6a7-11ea-8151-ab0a1664a05e.png">

**Custom Cluster Overview**
<img width="1223" alt="Screen Shot 2020-08-25 at 7 46 15 AM" src="https://user-images.githubusercontent.com/11410997/91189261-171e2580-e6a7-11ea-820f-a71cc0ee0e26.png">

Redirect to "Add Cluster - Custom" page:

<img width="1208" alt="Screen Shot 2020-08-25 at 7 50 34 AM" src="https://user-images.githubusercontent.com/11410997/91189777-b4795980-e6a7-11ea-9807-240e7e101873.png">

**Comment by lvuch** [comment]
<img width="947" alt="Screen Shot 2020-08-25 at 2 43 56 PM" src="https://user-images.githubusercontent.com/3013118/91231620-69c90300-e6e2-11ea-8b72-380aef85c5fa.png">

**Comment by westlywright** [comment]
@rancher/qa Please note that the requirements have changed (and approved):

Users will not be redirected to the add/edit cluster routes. Users WILL be presented with a modal that shows the command for the respective clusters (import or custom).
Button Text is `Add Host` for both types of clusters (different from the screenshot)
`Add Host` also exists as an action on the cluster via the action menu button on a cluster in the UI.
After a host has been registered a message will display success in the modal and will auto dismiss the modal after 3 seconds. Users should still be able to dismiss as well.

All other requirements regarding when to show the buttons still apply.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version b72b399` and `rancher\rancher:master-v2.5-head` `version 71da156`

**Imported cluster:**
Steps:
Create an imported cluster in Rancher
Do not add a cluster
Save
Click on cluster

User is given the option to add a cluster:
![Screen Shot 2020-11-13 at 4 20 45 PM](https://user-images.githubusercontent.com/57409052/99130174-da3e3c80-25cc-11eb-811f-231ad1d76bdd.png)
Cluster register command is given in a modal:
![Screen Shot 2020-11-13 at 4 20 53 PM](https://user-images.githubusercontent.com/57409052/99130178-dd392d00-25cc-11eb-80c8-31fea3578fa5.png)
On cluster edit, the user is unable to save any edits made.
![Screen Shot 2020-11-13 at 4 21 17 PM](https://user-images.githubusercontent.com/57409052/99130921-f4791a00-25ce-11eb-9fc6-3592e732b11d.png)
Once a cluster is registered, the user can make edits:
![Screen Shot 2020-11-13 at 4 34 14 PM](https://user-images.githubusercontent.com/57409052/99130839-b976e680-25ce-11eb-849c-56343a58cb30.png)

**Imported cluster:**
Steps:
Create a custom cluster in Rancher
Do not add nodes
Save
Click on cluster

User is given the option to add a host:
![Screen Shot 2020-11-13 at 4 23 10 PM](https://user-images.githubusercontent.com/57409052/99130876-d1e70100-25ce-11eb-965e-c1004b4bf70f.png)
Node register command is given in a modal:
![Screen Shot 2020-11-13 at 4 23 16 PM](https://user-images.githubusercontent.com/57409052/99130878-d4495b00-25ce-11eb-81f1-499021d50952.png)
On cluster edit, the user is able to save any edits made. Even if there is no host.
![Screen Shot 2020-11-13 at 4 26 23 PM](https://user-images.githubusercontent.com/57409052/99130901-e4f9d100-25ce-11eb-92a3-b38e0073c376.png)
