### ISSUE TITLE
[UI] EKSv2 Syncing

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#28541]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Description:**
UI should pull values from status.UpstreamSpec unless the field is not nil on Spec. On create no fields in spec in request should be nil. Empty maps and array should be sent as such and not as nil. On edit only changed fields should be sent in an update. More explanation on how syncing works can be found in backend issue.

**Backend Issue:**
https://github.com/rancher/rancher/issues/28422

**Comment by rmweir** [comment]
On create a vallue of null is being sent for ec2SshKey in a created nodegroup. For some reason this does not occur when running master locally or running the build given to me, eksv2-sync-save-v2, (by setting in ui-index) prior to merge.

![image](https://user-images.githubusercontent.com/19376037/93270761-9e226300-f766-11ea-8dc6-18ddabd46536.png)

**Comment by sowmyav27** [comment]
**On master-head - commit id: `01c13f69c` and UI tag: `latest2 `**

- Create a hosted EKS cluster, create a nodegroup, and leave the sshKey with NO value
- Click on create.
- Request sent has `ec2SshKey: ""`
- Cluster starts provisioning

**Comment by sowmyav27** [comment]
**On master-head - commit id: `53cf961ef`**

- P1 use case of syncing from EKS console to Rancher works - Hosted and Import clusters works as expected. UI displays values correctly.
- Any other issues found during this will be logged separately.
