### ISSUE TITLE
Add ability for creation and use of scheduling templates on workloads (PodNodeSelector)

### ISSUE THREAD

**Issue by asemen2608** [rancher/rancher#28546]
**What kind of request is this (question/bug/enhancement/feature request):**

feature request

**Steps to reproduce (least amount of steps as possible):**

1.1 Create a custom workload rule:
Create a rule in UI at workload (select in UI Cluster -> Projekt -> Namespace)
A space for the rule name should be added, is missing.
Open on the right 3... -> Edit at workload and select "Node Scheduling"
Add ruleset for Scheduling for example for bare metal nodes.
See screen shot: 1_1_edit_ruleset_mask.png
-> save

1.2 Predefined Rules
There is missing a tab to see all predefined rules,
Could be added the same level as the Workload below
"Workload" "Load Balancing" "Service Discovery" "Volumes" "Predefined Rules"
(cluster -> project)
See screenshot: 1_2_predefined_rules.png

2.1 Select Scheduling on workload
(cluster -> project -> click on workload or click on Edit & Workload
-> Node Scheduling
Add to select "Add predefined rules"
See screenshot on the right down corner: 2_1_add_to_workload.png
And save added rules in workload
2_2_save_added_rules_in_worlkoad.png

3.1 Rules in Overview
The added rules should be visible at "Node Scheduling"
See screenshot: 3_1_apply_rule_in_overview.png  

And in the overview in UI at workload (select in UI Cluster -> Projekt -> Namespace -> click on the right 3 dots e.g. below "Delete".
See screenshot: 3_2_apply_rule_in_overview.png
~                                                  **Other details that may be helpful:**
  

**Result:**
Implementation of Scheduling rules

**Other details that may be helpful:**

Creation of templates and reuse of predefined workload rules.
Faster deployment of workloads on dev, test, and production running on a different namespaces.

Rancher UI: Add scheduling templates on workloads

**Environment information**

    Rancher v2.4.5

**Other details that may be helpful:**

**Cluster information**

- Dev and test are vms
- Production is on bare metal

gz#11883

**Comment by asemen2608** [comment]
![1_1_edit_ruleset_mask](https://user-images.githubusercontent.com/61939253/91157175-493e8000-e6c5-11ea-97b9-69c21246d590.png)
![1_2_predefined_rules](https://user-images.githubusercontent.com/61939253/91157180-49d71680-e6c5-11ea-83a2-b82df6f1e58b.png)
![2_1_add_to_workload](https://user-images.githubusercontent.com/61939253/91157184-4a6fad00-e6c5-11ea-8836-0bfed622a7ae.png)
![2_2_save_added_rules_in_workload](https://user-images.githubusercontent.com/61939253/91157187-4a6fad00-e6c5-11ea-884d-baf3401a74aa.png)
![3_1_apply_rule_in_overview](https://user-images.githubusercontent.com/61939253/91157189-4b084380-e6c5-11ea-9954-4b2a03ab4bc1.png)
![3_2_apply_rule_in_overview](https://user-images.githubusercontent.com/61939253/91157191-4ba0da00-e6c5-11ea-84e2-c5543a7313b0.png)

**Comment by vincent99** [comment]
This is not a "UI feature". As described you're defining an entire new scheduling primitive for k8s that does not currently exist and would involve significant backend work to define and implement first.

Tacking on extra capabilities to a standard resource type is a mistake we have made in the past and would generally avoid, because it creates confusion and incompatibility.

The [PodNodeSelector](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector) admission controller can accomplish what sounds like largely the same goals, in an already existing & simpler upstream implementation.

**Comment by asemen2608** [comment]
Could it be implemented with the suggested upstream "PodNodeSelector" for creation and use of scheduling templates on workloads?

**Comment by vincent99** [comment]
PodNodeSelector works in the opposite direction.  The namespace is annotated to say what nodes pods in that NS are permitted to run on (and/or will run on by default).  You don't do anything to the workloads (except they still can have a normal node selector to further limit the choices down).

There's also:
- Config files on disk of the API server (per server, per cluster) involved
- Restarts required to change that config
- The admission controller needs to be enabled for the cluster in the first place
- It is not on by default, so it's supported out of the box by ~0% of clusters.
- There's no support for querying  the API of an arbitrary cluster to tell if a controller is enabled or not.

**Comment by asemen2608** [comment]
What could be offered cutomer to be implemented? 
What would you suggest?

**Comment by asemen2608** [comment]
Do we have an update for customer?

**Comment by asemen2608** [comment]
In what version this feature request is planed?

**Comment by vincent99** [comment]
It's not planned for any version.  A particular user can go enable the PodNodeSelector admission controller and it can do roughly what you're asking for.  But for all the reasons I said above it is unlikely to ever be made a first-class feature.

**Comment by asemen2608** [comment]
The customer will try to solve the problem with the mentioned PodNodeSelector.
From my site, this Issue can be closed.
