### ISSUE TITLE
Custom cluster fails to deploy

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28556]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps: (when this issue was hit)** 

- Deploy a custom cluster and GKE on 2.4.5
- Upgrade rancher to 2.4-head commit id: `965182f6b`
- Deploy a new custom cluster - all roles - 3 nodes.
- Cluster fails to come up with error - `[controlPlane] Failed to upgrade Control Plane: [[host ip-<node-3> not ready]]`
- Node-1 - Registered as a "Control plane" (as seen on the UI) with only Private Ip address
- Node-2 - Stuck in registering
- share-mnt logs

```
+ docker start kubelet
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
+ docker start kubelet
Error response from daemon: {"message":"No such container: kubelet"}
Error: failed to start containers: kubelet
+ sleep 2
```
- Node-3- In Unavailable state: with error `Kubelet stopped posting node status.`
- kubeapiserver logs:
```
W0825 22:35:07.765531       1 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {https://<>:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp <>:2379: connect: connection refused". Reconnecting...
W0825 22:35:59.677998       1 handler_proxy.go:102] no RequestInfo found in the context
E0825 22:35:59.678071       1 controller.go:114] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
, Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
I0825 22:35:59.678094       1 controller.go:127] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.
W0825 22:37:59.679807       1 handler_proxy.go:102] no RequestInfo found in the context
E0825 22:37:59.680052       1 controller.go:114] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
, Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
I0825 22:37:59.680156       1 controller.go:127] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.
```

**Other details that may be helpful:**
This does not happen always. Deployed another 3 node all roles cluster custom in the same setup which deployed successfully.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4-head commit id: `965182f6b`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.18.6
```

**Comment by superseb** [comment]
```Deploy a new custom cluster - all roles - 3 nodes.```
* What cloud is used for the instances for the 3 nodes? What are the specifications?

``` only Private Ip address```
* Please supply exact `docker run` commands for each node

As the log contains a connection refused, this might either be etcd failing to start due to lack of resources or a network issue where nodes can't reach each other (public/private IP addresses used).

Also the instance type running `rancher/rancher` would be helpful, as well as the full log from that container (with trace logging)

**Comment by sowmyav27** [comment]
- Nodes are AWS instances.
- Docker run command is exactly what we get from rancher UI along with public and private Ip addresses. something similar to `sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.4-3520-head --server https://<rancher-server> --token pqkkn478dxrl4qpwpbpwz5rshcqkxfgr7qv7jg6rp7bbv4x2s9xcl7 --ca-checksum 1ec8e68b772bdb4c1720fc893a5eb067ef946eeea4422a43c0769a47af3df2b0 --address <public ip> --internal-address <private-ip> --etcd --controlplane --worker`

**Comment by sowmyav27** [comment]
**Verified on an upgrade from 2.4.5 to 2.4.6-rc11**

**Steps:**

- On 2.4.5, deploy a 3 node all roles (AWS instances) custom cluster.
- Upgrade to 2.4.6-rc11.
- Deploy 3 custom clusters 
- - One 1 node all roles custom cluster
- - Two 3 nodes all roles custom cluster
- All the clusters deployed successfully. No issues seen.

**Comment by sowmyav27** [comment]
Closing this issue as this was not reproducible. Will reopen/log a new one if we see something similar
