### ISSUE TITLE
[DOCS] There is no mention of read only access

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#2855]
I find the [documentation](http://docs.rancher.com/rancher/configuration/access-control/) for what privileges you get a bit thin for the various levels. Most notably for the read only user access.

We noticed that a read only user now can read the logs of a container, which is good. As it was, the read only user was kind of pointless. But I'm not sure what else a read only user can and can not do (and don't feel like setting up a test system for the sole purpose of finding out by trying everything, also as it may change from one release to another)

**Comment by deniseschannon** [comment]
You will actually need to go to the environment section of the documentation to learn about the roles. 

I just updated it to add the "Restricted" role of an enviornment. Hope it helps!

http://docs.rancher.com/rancher/configuration/environments/

**Comment by kaos** [comment]
Ah, yes, thank you, that makes sense.

Perhaps a link from the access control page, hinting that more information is available in a different section would be helpful as well.. :)
