### ISSUE TITLE
Change Auto theme to use OS preference

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#28561]
- In <=2.4 the "auto" theme is dark from 6pm-6am.
- Dashboard/Vue looks at the OS's preference if available (in macOS, System Preferences -> General -> Appearance) and falls back to 6-6 if not supported.
- This change applies the same thing to Ember in 2.5 so that Cluster Explorer and Cluster Manager will match.

**Comment by izaac** [comment]
To get an old browser version that doesn't support the media query feature from which the UI is checking the theme to apply in Rancher and test the 6pm-6am time range Look into the MDN browser support link [here](https://codepen.io/kleinfreund/pen/NmpKZM).

In this case I used Firefox 66.0.6 in Ubuntu 20.04. Download the binary from the Mozilla Firefox archives.
The time is client based, meaning the time in the OS from where we access Rancher with a browser will tell Rancher which Theme to use when in Auto mode and no media query support.


To validate the Dark/Light change select this preference in a modern browser/OS combination like a Chrome based browser and latest OS X with dark theme support (**with** media query support). `macOS, System Preferences -> General -> Appearance` 
The appearance will change dynamically.



There's also the case where we use a modern OS and browser but the OS doesn't communicate the OS theme setting to the browser (Ubuntu 20.04 / Firefox 80). In these cases the default setting for Firefox is Light theme. If we want to use Dark theme we can follow the this instruction:

> For Firefox 67+ on Ubuntu, configure ui.systemUsesDarkTheme=1 via about:config (Right-click → New → Integer) because it doesn't seem like the OS properly communicates the preferred color scheme to the browser.



Rancher version: `master-head (08/27/2020)` _5e1b21b93_ Single docker Install. DO downstream cluster to check Dashboard<->Cluster Manager navigation transitions.


- Validated that changing the OS theme setting the Cluster Manager UI (Ember) changes accordingly when in Auto mode, navigating to Dashboard I noticed the Dashboard theme match Ember's theme.
- Validated that changing the OS theme setting the Dashboard UI (Vue) changes accordingly when in Auto mode, navigating to Dashboard I noticed the Cluster Manager theme match Vue's theme.
- Validated the 6am-6pm time range is still honored using an old browser version.
