### ISSUE TITLE
Dashboard Overview not loading when a Cluster Member has no access to any namespace

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28568]
- Create a cluster `cluster1`
- Create a second cluster `cluster2`
- As admin assign `user1` to both `cluster1` and `cluster2` as `Cluster Member`
- As `user1` In `cluster1` create a new project and add a namespace to it. 
  - Default and System projects shouldn't be accessible for a `Cluster Member`
- Leave `cluster2` as-is
- Try opening the Dashboard from `cluster2`

GET to https://<rancher_host>/k8s/clusters/c-xxxxx/v1/namespaces returns 405

```
{"type":"error","links":{},"code":"MethodNotAllowed","message":"Method GET not supported","status":405,"type":"error"}
```

Browser displays:

**HTTP Error 405:
Method GET not supported
Reload**

- Opening the Dashboard from `cluster1` works as it has at least one namespace.

If relevant, the setup was HA Rancher
Rancher version master-head 8bd924599 (04/20/2020)

**Comment by dramich** [comment]
This appears to be working on latest master-head

**Comment by izaac** [comment]
Rancher version: `master-head (09/14/2020)` _0f691dc70f86bbda3d6563af11779300a6191584_ HA k8s

Created Downstream DO cluster.
Added a `Cluster Member` to it with role `Standard User` 
Login with this cluster member.
Try Access Dashboard


![Screen Shot 2020-09-14 at 4 26 59 PM](https://user-images.githubusercontent.com/27659/93147996-9780e680-f6a7-11ea-8fa6-e6a4728ede33.png)

![Screen Shot 2020-09-14 at 4 27 03 PM](https://user-images.githubusercontent.com/27659/93148004-9b146d80-f6a7-11ea-8180-d4f9e2868ed6.png)


As soon as I add a namespace as this standard user I am able to access the Dashboard.

**Comment by dramich** [comment]
The root cause is that the user does not have permissions in the downstream cluster to list namespaces. This makes sense as they don't have any namespaces to access so the permissions were never created in rancher and pushed downstream to the user cluster. The same behavior is seen if using the kubeconfig for the user and attempting to list namespaces against the downstream cluster using kubectl. @westlywright @vincent99 Can dashboard handle this situation gracefully?

**Comment by dramich** [comment]
After some more testing, I don't think it will matter if dashboard handles this one situation. The user is still missing permissions in the downstream cluster so they can't even make that first namespace. This issue falls under the ongoing RBAC consideration/work @ibuildthecloud has. Rancher currently does this push reactively to things getting created through it vs being proactive and pushing the perms before a user needs them.

**Comment by maggieliu** [comment]
@ibuildthecloud will fix the 405 error on dashboard in this use case. However, dashboard will be blank until cluster member is granted access to a project or creates a project.

**Comment by izaac** [comment]
This is now working on latest `master-head (09/19/2020)` _bd88c23_ 
But there's a blocker issue #29021

**Comment by deniseschannon** [comment]
@izaac can we close this and just track the other issue separately? This issue is clearly about dashboard not loading for cluster members, which is fixed, but the other issue is a different problem.

**Comment by izaac** [comment]
Closing, original reported issue is not reproducible https://github.com/rancher/rancher/issues/28568#issuecomment-695349970
