### ISSUE TITLE
unable to deploy a container when using a private registry deployed by rancher on the same host

### ISSUE THREAD

**Issue by bsauvajon** [rancher/rancher#2856]
Hi,

We use artifactory to deploy our own docker images.
The artifactory server is running in a container deployed by rancher, and accessed through a load balancing service.
If I want to deploy a new container on the same host, the agent can't access the registry.
It seems that the packets sent by the agent are not catched by the iptables rules, so it can't connect to the lb service. A workaround was to manually add the CATTLE_PREROUTING chain in the OUTPUT chain of NAT table.
Is it a good idea to make it by default on each hosts ?

**Comment by deniseschannon** [comment]
This sounds like the Hairpin NAT issue that we have. 

https://github.com/rancher/rancher/issues/1920

**Comment by deniseschannon** [comment]
@bsauvajon As I mentioned, I think this is the Hairpin NAT issue.
