### ISSUE TITLE
"Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go informational logs seen in rancher logs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28567]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a custom cluster. (3 nodes all roles)
- Rancher logs do not show context deadline exceeded logs but see
```
I0825 21:30:11.768881       6 trace.go:116] Trace[1657588612]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-25 21:29:32.421567159 +0000 UTC m=+874.030196264) (total time: 39.347269541s):
Trace[1657588612]: [39.347256731s] [39.347256731s] Objects listed
I0825 21:30:11.821867       6 trace.go:116] Trace[434777563]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-25 21:29:32.446909313 +0000 UTC m=+874.055538428) (total time: 39.374919837s):
```

**Other details that may be helpful:**
^^^ these logs are seen multiple times in rancher logs
Also seen on an upgrade from 2.4.5 to 2.4-head.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4-head commit id: `965182f6b `
- Installation option (single install/HA): single

**Comment by cbron** [comment]
This is a a performance warning that the setup is slow, taking a long time to respond, so it's a symptom not a bug. Can be handled elsewhere.
