### ISSUE TITLE
Need a screen to indicate wait for the shell to open when launching kubectl

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28569]
Need a UI indicate while waiting for shell to open when launching kubectl

**Comment by westlywright** [comment]
Message already exists in the window in the upper right. The message was quite dark though and not called out, so I changed the color to the warning text color which highlights it a lot more. If we'd like to address the design further maybe we should do it post 2.5? 

![Screen Shot 2020-09-25 at 3 05 46 PM](https://user-images.githubusercontent.com/858614/94319975-ab96d480-ff40-11ea-9fed-c91e69ab64f2.png)

**Comment by sowmyav27** [comment]
**ON rancher-master-head - commit id: `4ac3a87` ui tag: latest2**

- Dark mode
<img width="1801" alt="Screen Shot 2020-09-25 at 4 51 00 PM" src="https://user-images.githubusercontent.com/26032343/94325923-c758a580-ff55-11ea-8016-2d3eabd80314.png">

- Light mode:
<img width="1850" alt="Screen Shot 2020-09-25 at 4 51 18 PM" src="https://user-images.githubusercontent.com/26032343/94325930-d0e20d80-ff55-11ea-9320-92b0eb9612ff.png">

**Comment by westlywright** [comment]
I'm going to leave the connecting message yellow, this is how the dashboard functions when showing the connecting message in the shell. I believe it pulls the users attention to the message. After connecting it will show the message in black, again this is how the dashboard functions.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `27000be`**

Behavior is seen as described here - https://github.com/rancher/rancher/issues/28569#issuecomment-699245604
