### ISSUE TITLE
 tls-rancher-ingress not updated after certificate rotation

### ISSUE THREAD

**Issue by Cobra1978** [rancher/rancher#28563]
Hi.

I have a Rancher 2.4.5 Cluster isntalled on CentOS7 Machine installed with rancher-generated self-signed cert.

Yesterday the certificate had expired, so i've issued the rotation witth
`bin/rke_linux-amd64 cert rotate --config rancher-cluster.yml`

Now cattle-node-agent and cuttle-cluster-agent are giving error because the certificate is not valid, and this is because the secret " tls-rancher-ingress" was not updated to the new certificate.

If i connect in https directly to one of the 3 management host i'see the correct certificate with one year of validity, but obviously i see the default backend error.

How can i solve this?

![immagine](https://user-images.githubusercontent.com/33548070/91294817-642ef400-e79a-11ea-865b-e5aa1b09ce93.png)

**Comment by superseb** [comment]
`rke cert rotate` only rotates certificates of the Kubernetes components (as described on https://rancher.com/docs/rke/latest/en/cert-mgmt/#certificate-rotation). The mentioned certificate is the certificate that someone added to be used in the nginx-ingress to access Rancher itself. If this certificate expired, you need to replace the certificate. This is described on https://rancher.com/docs/rancher/v2.x/en/installation/options/tls-secrets/.

If you didn't configure your own certificate, please supply the exact `helm install` command (and other commands if applicable) you used to install Rancher onto the cluster.

**Comment by Cobra1978** [comment]
Thanks for the reply.

I didn't supplied any certificate, i've simply followed the official documentation and installed cert-manager to manage the certificate, the exact command i've used are the oen in the Docs

The version of cert-manager is 0.5.2, and 've never updated it, maybe this could be related to my problem?

**Comment by superseb** [comment]
Please share the logs of pod containers in the `cert-manager` namespace.

**Comment by Cobra1978** [comment]
Could be because is a very old installation, but cert-manager is installed in the cattle-system namespace.

THe logs i see in the cert-manager pro are like these:

`E0827 08:34:49.927841       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"9b|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"9bd14db6-d2c9-4ad9-a2d1-47dd3cc292d0\"}":{|...

E0827 08:34:50.943375       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"bf|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"bf044f45-1fd4-431e-b3c0-95a043474170\"}":{|...

E0827 08:34:51.956135       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"bf|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"bf044f45-1fd4-431e-b3c0-95a043474170\"}":{|...

E0827 08:34:52.968772       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"36|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"361abc79-c7e4-11e9-bf9a-00505694e1ad\"}":{|...

E0827 08:34:53.980658       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"89|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"89ef2e1a-4515-475d-9820-839f0a56993c\"}":{|...

E0827 08:34:54.993232       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"54|..., bigger context ...|f:job-name":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"54d0dfb6-8df3-47a6-84cb-1e4ce926d2f2\"}":{|...

E0827 08:34:56.004906       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"7d|..., bigger context ...|"f:release":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"7d54c26a-4687-4a0b-8ef9-c566dc8b586a\"}":{|...

E0827 08:34:57.017786       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"36|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"361abc79-c7e4-11e9-bf9a-00505694e1ad\"}":{|...

E0827 08:34:58.029780       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"8e|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"8e394dff-e83c-4d07-b199-97831335838c\"}":{|...

E0827 08:34:59.046569       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"89|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"89ef2e1a-4515-475d-9820-839f0a56993c\"}":{|...

E0827 08:35:00.061900       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"36|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"361abc79-c7e4-11e9-bf9a-00505694e1ad\"}":{|...

E0827 08:35:01.074419       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"2d|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"2d8934cc-c7e4-11e9-a35a-00505694c32f\"}":{|...

E0827 08:35:02.086803       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"89|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"89ef2e1a-4515-475d-9820-839f0a56993c\"}":{|...

E0827 08:35:03.099109       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"2d|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"2d8934cc-c7e4-11e9-a35a-00505694c32f\"}":{|...

E0827 08:35:04.111031       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"8e|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"8e394dff-e83c-4d07-b199-97831335838c\"}":{|...

E0827 08:35:05.123373       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"54|..., bigger context ...|f:job-name":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"54d0dfb6-8df3-47a6-84cb-1e4ce926d2f2\"}":{|...

E0827 08:35:06.137424       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"89|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"89ef2e1a-4515-475d-9820-839f0a56993c\"}":{|...

E0827 08:35:07.151014       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"36|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"361abc79-c7e4-11e9-bf9a-00505694e1ad\"}":{|...

E0827 08:35:08.163272       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"36|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"361abc79-c7e4-11e9-bf9a-00505694e1ad\"}":{|...

E0827 08:35:09.176138       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"36|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"361abc79-c7e4-11e9-bf9a-00505694e1ad\"}":{|...

E0827 08:35:10.190426       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"54|..., bigger context ...|f:job-name":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"54d0dfb6-8df3-47a6-84cb-1e4ce926d2f2\"}":{|...

E0827 08:35:11.202776       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"2d|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"2d8934cc-c7e4-11e9-a35a-00505694c32f\"}":{|...

E0827 08:35:12.215413       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"89|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"89ef2e1a-4515-475d-9820-839f0a56993c\"}":{|...

E0827 08:35:13.227791       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"9b|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"9bd14db6-d2c9-4ad9-a2d1-47dd3cc292d0\"}":{|...

E0827 08:35:14.240463       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"8e|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"8e394dff-e83c-4d07-b199-97831335838c\"}":{|...

E0827 08:35:15.256453       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"54|..., bigger context ...|f:job-name":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"54d0dfb6-8df3-47a6-84cb-1e4ce926d2f2\"}":{|...

E0827 08:35:16.268380       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"8e|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"8e394dff-e83c-4d07-b199-97831335838c\"}":{|...

E0827 08:35:17.281385       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"36|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"361abc79-c7e4-11e9-bf9a-00505694e1ad\"}":{|...

E0827 08:35:18.295018       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"89|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"89ef2e1a-4515-475d-9820-839f0a56993c\"}":{|...

E0827 08:35:19.308625       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"36|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"361abc79-c7e4-11e9-bf9a-00505694e1ad\"}":{|...

E0827 08:35:20.322123       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"2d|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"2d8934cc-c7e4-11e9-a35a-00505694c32f\"}":{|...

E0827 08:35:21.336040       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"54|..., bigger context ...|f:job-name":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"54d0dfb6-8df3-47a6-84cb-1e4ce926d2f2\"}":{|...

E0827 08:35:22.348688       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"2d|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"2d8934cc-c7e4-11e9-a35a-00505694c32f\"}":{|...

E0827 08:35:23.362588       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"2d|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"2d8934cc-c7e4-11e9-a35a-00505694c32f\"}":{|...

E0827 08:35:24.379349       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"bf|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"bf044f45-1fd4-431e-b3c0-95a043474170\"}":{|...

E0827 08:35:25.396650       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"36|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"361abc79-c7e4-11e9-bf9a-00505694e1ad\"}":{|...

E0827 08:35:26.408442       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"8e|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"8e394dff-e83c-4d07-b199-97831335838c\"}":{|...

E0827 08:35:27.426383       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"89|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"89ef2e1a-4515-475d-9820-839f0a56993c\"}":{|...

E0827 08:35:28.439974       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"2d|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"2d8934cc-c7e4-11e9-a35a-00505694c32f\"}":{|...

E0827 08:35:29.452050       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"36|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"361abc79-c7e4-11e9-bf9a-00505694e1ad\"}":{|...

E0827 08:35:30.464292       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"2d|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"2d8934cc-c7e4-11e9-a35a-00505694c32f\"}":{|...

E0827 08:35:31.479149       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"89|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"89ef2e1a-4515-475d-9820-839f0a56993c\"}":{|...

E0827 08:35:32.494886       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"36|..., bigger context ...|generation":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"361abc79-c7e4-11e9-bf9a-00505694e1ad\"}":{|...

E0827 08:35:33.507227       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"89|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"89ef2e1a-4515-475d-9820-839f0a56993c\"}":{|...
E0827 08:35:34.527463       1 reflector.go:205] github.com/jetstack/cert-manager/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},"k:{\"uid\":\"89|..., bigger context ...|plate-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"89ef2e1a-4515-475d-9820-839f0a56993c\"}":{|...

Wrap lines
Previous Container
`

**Comment by Cobra1978** [comment]
I there any way to obtain the rancher root cert? with the root cert i can eventualy generate by myselv a certificate, issuing a csr and obtaining the cert and key, so as i have the interface correctly working i can then follow the steps to upgrade the cert manager?

Could this be a solution?

**Comment by superseb** [comment]
This seems to be an incompatibility between k8s version and cert-manager, what RKE version (`rke --version`) and Kubernetes version (`kubectl version`) are you using?

**Comment by Cobra1978** [comment]
```
 bin/kubectl version --insecure-skip-tls-verify
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```
```
bin/rke_linux-amd64 --version
rke version v1.1.3
```

**Comment by Cobra1978** [comment]
Hi.

I know that this support is for free and i can't pretend anything, but our developers are asking for a solution because by now we can't interact with rancher2, so we can't deploy new version of our develop application.

Thanks.

**Comment by superseb** [comment]
When did the errors start appearing? Directly after upgrading to k8s 1.18? This helps in isolating what caused it which helps in choosing the right solution.

Based on what I know now is that you should upgrade cert-manager, but because it's such an old version you probably want to verify this in your test environment before applying it to production. The sequence is described in the docs, https://rancher.com/docs/rancher/v2.x/en/installation/options/upgrading-cert-manager/. I would also test first what version of cert-manager resolves the issue with the errors (assuming it caused by upgrading to k8s 1.18)

**Comment by Cobra1978** [comment]
Honestly i don't know when those errors start appearing, and i don't have enough log history.

Upgrading cert manager could be a solution, but helm refuses to launch commands because the expired cert, and i didn't find any option to tell hm to ignore the cert.

**Comment by Cobra1978** [comment]
Yeppa!

Found the option for helm (a flag in kube/config), updated cert-manager and the cluster is back, fully functional!

Thanks superseb, you are my savior!
