### ISSUE TITLE
[Logging v2] Control Plane logs - GKE

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#28574]
Add as many relevant control plane logging locations as possible for GKE.

**Comment by nickgerace** [comment]
Building off similar work to EKS: https://github.com/rancher/charts/pull/583

**Comment by nickgerace** [comment]
Research done earlier this week for GKE control plane logging. Waiting for team sync on the issue.

**Comment by nickgerace** [comment]
Relevant conversation: https://community-banzaicloud.slack.com/archives/CGMPPBZBK/p1605025609156400

**Comment by izaac** [comment]
Logging Chart version `3.8.201`

Rancher version: `v2.5-head (12/08/2020)` _8d759be_
Rancher version: `master-head (12/07/2020)` _a5e40aa_


Observed this upstream issue too: https://github.com/banzaicloud/logging-operator/issues/582
We need to handle rotating logs: https://github.com/rancher/rancher/issues/30383
