### ISSUE TITLE
[Logging v2] Control Plane logs - EKS

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#28572]
EKS:

https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html

kublet logs can be scraped from /var/log/messages

**Comment by paynejacob** [comment]
https://github.com/rancher/rancher/issues/28572

**Comment by izaac** [comment]
Rancher version `master-head (09/08/2020)` _76c26fb0f_
Elasticsearch: `7.8.0`

I was able to see the kubelet logs stored in the Elasticsearch backend after they were collected from the cluster nodes `/var/log/messages` path
