### ISSUE TITLE
Update k8s version for 2.4

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28576]
Update to:
1.18.8, 1.17.11, 1.16.15 => 1.18.9, 1.17.12, 1.16.15

Should be available for 2.4.4+

**Comment by superseb** [comment]
@PennyScissors Can we move to the new repository location (`us.gcr.io/k8s-artifacts-prod/hyperkube`) as described in https://github.com/rancher/rancher/issues/25748

**Comment by sowmyav27** [comment]
**Validated on 2.4.8 and 2.4.4 - KDM pointing to dev-v2.4**

- 1.18.8, 1.17.11, 1.16.15 k8s - deployed using all network providers. 
- Network checks succeeded

**Comment by sangeethah** [comment]
Reopening to test the latest set of versions.

**Comment by sowmyav27** [comment]
**Validated on 2.4.8 - KDM pointing to dev-v2.4**

- 1.18.9-rancher1-1, 1.17.12-rancher1-1, 1.16.15-rancher1-2 and 1.15.12-rancher2-6 k8s - deployed using all network providers.
- Windows cluster and validation tests on all ^^^ 4 k8s versions look good
