### ISSUE TITLE
Load balancer service to: not showing the stack name

### ISSUE THREAD

**Issue by blackjid** [rancher/rancher#2858]
Rancher: v0.47.0
UI: v0.68.0

<img width="800" alt="screen shot 2015-12-01 at 11 10 59 am" src="https://cloud.githubusercontent.com/assets/228037/11506505/c44dc806-981d-11e5-97c7-643cf566c402.png">

I have a stack for a global load balancer, the load balancer forward traffic to services in other stacks. 
I think in the UI the stack name should be used if the load balancer target is outside the current stack.

Now the UI is showing `to: web, web, web2` which is not very useful, it would be better something like `to: stack1/web, stack2/web, stack3/web2`

Also the services could be links using the underlying host-ip or hostname definition.

**Comment by deniseschannon** [comment]
Similar to https://github.com/rancher/rancher/issues/2823

**Comment by tfiduccia** [comment]
Version - Master Jan 07
Verified fixed
