### ISSUE TITLE
AKS clusters with kubenet+calico fail to deploy

### ISSUE THREAD

**Issue by ams0** [rancher/rancher#28593]
When creating an AKS cluster thru the web interface and selecting "Advanced networking" and kubenet plugin, the choice of Network Policy is none or "Calico". The deployment fails with:

```
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NetworkPolicyNotSupported" Message="NetworkPolicy is not supported (only azure and calico are supported)" Target="networkProfile.networkPolicy"

```

I suspect it's the capitalization of the "C" in calico the culprit, perhaps here: https://github.com/rancher/ui/blob/da5ef3345dedfba9031d2f8f3fb7511df2fe4840/lib/shared/addon/components/cluster-driver/driver-azureaks/component.js#L21 but I don't know how to build and test rancher (any hint appreciated).

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.6-rc12` UI: `v2.4.31` |
|Route|`undefined`|

**Comment by superseb** [comment]
This is the same as https://github.com/rancher/rancher/issues/26710
