### ISSUE TITLE
Microsoft Arc Conformance testing for RKE clusters

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28598]
Need to perform Microsoft Arc conformance test for RKE clusters.
https://rancher.atlassian.net/wiki/spaces/EN/pages/680296460/Microsoft+Arc+Testing
* Review to see if the steps are translated into RKE correctly
* Review the failed tests to see if there is anything we can do to pass them

**Comment by sangeethah** [comment]
Initial set of runs were done on the following configuration:

Rancher Helm install - `v2.4.5`
Custom cluster - `k8s 1.18.6`
1 controlplane
1 etcd
3 worker nodes

Sonobuoy Test results:
Plugin: azure-arc-conformance
Status: failed
Total: 6
Passed: 4
Failed: 2
Skipped: 0

Failed tests:
test_cluster_metadata
test_kubernetes_configuration_helm_operator

**Comment by dramich** [comment]
The instructions for getting a cluster into azure arc are [here](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/connect-cluster). After importing the cluster into arc follow the instructions [here](https://github.com/Azure/azure-arc-certification#running-conformance-tests) to run the conformance testing. 
The instructions in the wiki are incorrect so should be updated to match this (easier) flow.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 8fd81a9

* RKE ec2 v1.19.1-rancher1-1
* 1 node all roles
* 2 dedicated workers

```
$ sonobuoy results arc-passing.tar.gz
Plugin: azure-arc-conformance
Status: passed
Total: 6
Passed: 6
Failed: 0
Skipped: 0
```
