### ISSUE TITLE
Dashboard Overview - k3s openrc cluster returns all zero for allocatable and requested and Memory/Core graphs are not displayed

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28594]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- Create a one node downstream k3s cluster with openrc (Alpine Linux)
- Import the cluster in Rancher
- Navigate from Cluster manager (Ember UI) to Dashboard.

**Result:**

- In the cluster Overview there is some cluster information but the Memory/Cores are not shown

`/v1/management.cattle.io.clusters/<cluster-id>`

```
"capacity": {
"cpu": "0",
"memory": "0",
"pods": "0"
},

"allocatable": {
"cpu": "0",
"memory": "0",
"pods": "0"
},

requested": {
"cpu": "0",
"memory": "0",
"pods": "0"
},
```

**Other details that may be helpful:**

**Environment information**
- Rancher version: `master-head (08/26/2020)` _a1acca856_
- Installation option: HA k8s

** k3s cluster**

v1.18.8+k3s1, Alpine Linux 3.12

k3s systemd cluster I see these metrics properly retrieved and rendered in the Dashboard.

**Comment by davidnuzik** [comment]
@izaac can you confirm you followed additional steps required for each alpine node before k3s install? https://rancher.com/docs/k3s/latest/en/advanced/#additional-preparation-for-alpine-linux-setup

**Comment by izaac** [comment]
@davidnuzik yes I followed those pre-requirement steps before installing on alpine.

**Comment by davidnuzik** [comment]
Thanks @izaac 
I think this may be something for the K3s team and will see if we can have someone take a look soon.

**Comment by davidnuzik** [comment]
I was mistaken I thought for some reason RHEL-like os'es like CentOS used OpenRC. This seems to only be Alpine and related distros. We do not formally support these. As such, this is a nice to have and lower priority in my opinion @maggieliu 
K3s team will not be looking at this in the short term.

**Comment by izaac** [comment]
In latest master (described here: https://github.com/rancher/rancher/issues/29139#issuecomment-699172816) both systemd and openrc are showing this behavior.

> Rancher version: `master-head (09/25/2020)` _df9345c_
> 
> HA k3s local cluster shows all the resource graphs properly.
> RKE downstream cluster shows all the resource graphs properly.
> 
> Imported k3s clusters (one openrc and one systemd) resource graphs are not even present in the Dashboard cluster overview.

**Comment by izaac** [comment]
Dashboard has had a number of release iterations since this was observed and this is no longer applicable. Closing
