### ISSUE TITLE
about loadbalance http timeout

### ISSUE THREAD

**Issue by xrain0610** [rancher/rancher#2859]
Hi,
today i use the loadbalance to do a long time http query,
but  always  return 504 timeout,
the error isn't my application returned.
i think , should add the timeout setting for the http loadbalance.

thanks

**Comment by alena1108** [comment]
Its already been set in haproxy config (default value is 50 seconds):

https://github.com/rancher/cattle/blob/c7feeac86a773aaf7eb53fede987bca9eb1b6463/resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl#L27

Here is the config param description:

https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4-timeout%20server 

If the default value is not enough for your app, we are going to allow user to override default haproxy settings in the next rancher release. Refer to this PR for the updates:

https://github.com/rancher/cattle/pull/1081
