### ISSUE TITLE
[UI]: additional nodegroups added do not send version

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#28604]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Add a nodegroup during create or edit in addition to the first one that is created

**Result:**
The version is not greyed out and once created or saved there is an error because the version for the additional nodegroup is an empty string.

**Comment by westlywright** [comment]
For clarification later on, on `CREATE` the version for node groups does get sent correctly and the dropdown is NOT selectable. This is the desired UX as the user should not be able to change the node group version number if we are creating a fresh cluster.

**Comment by westlywright** [comment]
A fix is available in `latest2`

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `c428bc9feb4b`**

- Deploy an EKS cluster with 2 nodegroups.
- Correct version is sent  in the request
- Version dropdown in the nodegroups is NOT selectable. it is disabled and the version matches the cluster's k8s version
- Edit an EKS cluster --> Add a node group . version dropdown of this node group is disabled and the version matches the cluster's k8s version
- Save changes made. Correct k8s version is sent in the request
