### ISSUE TITLE
Creating default environment for users with no "name" creates a "null Default"

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2860]
v0.47.0

Steps to Reproduce:
1. Enable local auth
2. Add a user (do not specify a name)
3. Log in as user

Result: The default environment that is created is called "null Default". This seems like an error.

Expected Result: To not create an environment with the word "null" in it. If no name is specified, could we use the username to create the environment name?

**Comment by hibooboo2** [comment]
Sure will make a patch for this today.

**Comment by deniseschannon** [comment]
Verified with v0.49.0-rc1
