### ISSUE TITLE
Logging in as type "user" results in empty stack page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2861]
v0.47.0

Steps to Reproduce:
1. Enable Local Auth
2. Add a second user (as user role) and add to Default environment as member, restricted or readonly role
3. Make sure there are host/stacks/services in the Default environment
3. Log out
4. Log in as second user

Result: Log in to "Default" environment but there are no stacks shown. If I click on Refresh, the stacks are shown. 

Expected Result:  Log in to "Default" environment and show the stacks that are part of environment. Note: the page loads fine for anyone logging in who has an "Admin" level account, but not the "User" level account.

**Comment by vincent99** [comment]
Same underlying issue as #2826

**Comment by deniseschannon** [comment]
Verified with v0.49.0-rc3, UI v0.70.0
