### ISSUE TITLE
Clicking on cluster Explorer hyperlink gives a 404 error

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28612]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- From Local cluster --> Click on Cluster explorer
<img width="1274" alt="Screen Shot 2020-08-27 at 10 25 15 PM" src="https://user-images.githubusercontent.com/26032343/91524517-4950a280-e8b4-11ea-90cf-9bc716c155df.png">

- User is redirected to `https://<rancher-server>/dashboard/c/local` page with a 404 error
<img width="600" alt="Screen Shot 2020-08-27 at 10 25 01 PM" src="https://user-images.githubusercontent.com/26032343/91524556-5b324580-e8b4-11ea-81bd-1c6754778281.png">

**Expected:**
User should be navigated to the dashboard page.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `7636d25d8d`
- Installation option (single install/HA): HA

**Comment by sangeethah** [comment]
Tested with rancher server version -` master-6a6f13cec32b8d046e36622f82a2fc0b5c1e0ef7-head`
Able to launch "cluster explorer" successfully for local and downstream clusters.
