### ISSUE TITLE
[Forward port] Rancher K8s Auth Proxy does not utilize forward proxy (if defined) to proxy communication

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28618]
Need to forward port to master for this issue: https://github.com/rancher/rancher/issues/25488

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 6a6f13c

* Deploy Rancher in a semi-airgapped environment, with a proxy
  * Rancher installed a node with no public IP / direct access to the internet in EC2
  * Internet-facing load balancer points to Rancher so it is externally accessible
  * Docker settings and Rancher both use proxy
* Create each of GKE, EKS, and custom cluster created from DO node
* Clusters provision
* Cluster and node agents deploy on all clusters
* Clusters are active and accessible
* View logs, exec shell, kubectl all function in all clusters
