### ISSUE TITLE
Swarm support in Rancher

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#2862]
Make Swarm the native scheduler in Rancher
Put all Rancher scheduling enhancements in a Swarm scheduling filter
Optionally enable/disable Swarm master (so we don't always expose the Swarm master to the Internet)

**Comment by RVN-BR** [comment]
interested in other schedulers so i'll follow this.

**Comment by will-chan** [comment]
Closing issue as the primary task is complete.
