### ISSUE TITLE
In rancher pod logs, seeing many "Timeout: Too large resource version" for k8s < 1.18

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28623]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Verified on 2.4.6 HA setup**

- Local cluster version - 1.18.6
- Custom cluster deployed - 1.18.6
- Logs do NOT show "Too large resource version"
- Deployed a 1.17 DO cluster.
- Logs show:
```
I0828 14:36:05.210920       6 trace.go:116] Trace[913108035]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-28 14:35:25.986833664 +0000 UTC m=+1804.731151172) (total time: 39.224054273s):
Trace[913108035]: [39.224054273s] [39.224054273s] END
E0828 14:36:05.210957       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.Service: Timeout: Too large resource version: 679, current: 593
I0828 14:37:06.227318       6 trace.go:116] Trace[444066509]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-28 14:36:27.0066873 +0000 UTC m=+1865.751004808) (total time: 39.220594868s):
Trace[444066509]: [39.220594868s] [39.220594868s] END
E0828 14:37:06.227352       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.Service: Timeout: Too large resource version: 679, current: 593
I0828 14:38:19.782877       6 trace.go:116] Trace[1357282124]: "Reflector ListAndWatch" name:github.com/rancher/norman/controller/generic_controller.go:237 (started: 2020-08-28 14:37:40.560958921 +0000 UTC m=+1939.305276539) (total time: 39.221890754s):
Trace[1357282124]: [39.221890754s] [39.221890754s] END
E0828 14:38:19.782916       6 reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.Service: Timeout: Too large resource version: 679, current: 593
```

**Other details that may be helpful:**
Upstream bug: https://github.com/kubernetes/kubernetes/issues/94315

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.6
- Installation option (single install/HA): Single/HA

gzrancher/rancher#12072

gzrancher/rancher#11577

**Comment by janeczku** [comment]
- Causes various Cattle controllers to become stuck. E.g. cluster provisioning stuck for several minutes.
- Increases system load on downstream API server

[rancher-log.txt.gz](https://github.com/rancher/rancher/files/5149115/rancher-log.txt.gz)


Possible causing:
- https://github.com/rancher/rancher/issues/26688
- https://github.com/rancher/rancher/issues/27788

**Comment by mattmattox** [comment]
@sowmyav27 Can this be validated on the following versions.
Rancher: v2.3.6 / v2.4.5
K8s: v1.15.5 / v1.16.13
Docker: v18.6.3
OS: Ubuntu 18.04.5

**Comment by sowmyav27** [comment]
**Verified on an upgrade from 2.3.6 to 2.4.8-rc2**

- Deployed 2 custom clusters - 1 etcd, 1 control, 3 worker nodes- docker `19.3.12` and `OS: Ubuntu 18.04.3 LTS` with k8s 1.15.11
- Deployed 2 AWS rke clusters - 1 control, 3 etcd and 3 worker - `Docker Version: 18.6.3` and `OS: Ubuntu 18.04.5 LTS` with k8s 1.15.11
- Pre upgrade checks on the cluster looked good.
- Upgrade rancher to 2.4.8-rc2
- Post upgrade checks on the cluster looked good.
- Upgrade k8s of 1 custom cluster and 1 rke cluster to 1.16.13 and other 2 clusters to 1.17.9
- Post k8s upgrade checks on the cluster looked good.
- Rancher logs do NOT show `reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.Service: Timeout: Too large resource version`

**Comment by dnoland1** [comment]
@sowmyav27 We also need to make sure Kubernetes v1.15.5 is tested as well.

**Comment by sowmyav27** [comment]
On fresh install of `2.4.8-rc2`

- Deployed 1 custom cluster - 1 etcd, 1 control plane and 2 worker nodes with k8s 1.15.12, 1.16.13, 1.17.9 and 1.18.6 (on separate rancher setups)
- Verified the rancher logs do NOT show `Too large resource version`

**Comment by sowmyav27** [comment]
@dnoland1 2.3.6 does not have k8s `v1.15.5` and has `1.15.11` in the dropdown.

**Comment by dnoland1** [comment]
@sowmyav27 Right, but you can click "Edit as YAML" and enter 1.15.5 for the Kubernetes version. We need to ensure this fix works on this specific version. Very likely 1.15.11 and 1.15.5 will have the same behavior, but still important to verify this.

**Comment by sowmyav27** [comment]
**Verified on an upgrade from 2.3.6 to 2.4.8-rc2**

- Deployed 2 AWS rke clusters - 1 control, 3 etcd and 3 worker - `Docker Version: 18.6.3` and `OS: Ubuntu 18.04.5 LTS` with k8s `1.15.5-rancher1-2`
- Pre upgrade checks on the cluster looked good.
- Upgrade rancher to 2.4.8-rc2
- Upgrade one cluster to 1.16.13 and 1 to 1.17.9
- Rancher logs do NOT show `reflector.go:178] github.com/rancher/norman/controller/generic_controller.go:237: Failed to list *v1.Service: Timeout: Too large resource version`

the logs show these info statements
```
Trace[1118249768]: [1.300807s] [1.300760067s] About to write a response
I0903 01:12:46.013943      22 shared_informer.go:197] Waiting for caches to sync for garbage collector
I0903 01:12:46.018444      22 trace.go:116] Trace[1159701769]: "Get" url:/apis/management.cattle.io/v3/clusters/c-4b992,user-agent:Go-http-client/1.1,client:127.0.0.1 (started: 2020-09-03 01:12:44.795090348 +0000 UTC m=+39.939018017) (total time: 1.223324526s):
Trace[1159701769]: [1.221408066s] [1.221373003s] About to write a response
I0903 01:12:46.024989      22 trace.go:116] Trace[1962513180]: "Get" url:/apis/management.cattle.io/v3/clusters/c-4b992,user-agent:Go-http-client/1.1,client:127.0.0.1 (started: 2020-09-03 01:12:44.839760553 +0000 UTC m=+39.983688220) (total time: 1.185199949s):
Trace[1962513180]: [1.180247075s] [1.180194897s] About to write a response
```

**Comment by sowmyav27** [comment]
**Verified on master-head commit id: `5d5ef3f8fcb`**

- Deployed clusters 1.15, 1.16, 1.17 and 1.18 1 node custom clusters
- `Too large resource version` is NOT seen in the rancher logs
