### ISSUE TITLE
[rancher/charts scripts] Patch script needs to produce consistent diffs

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#28627]
Related to comments on https://github.com/rancher/charts/pull/544#issuecomment-676625798, it is suspected that using a GNU vs. BSD diff causes the patch to get swapped around on a make patch. This caused several non-commit-related differences to be introduced in https://github.com/rancher/charts/pull/544.

The scripts need to be updated so that it produces a consistent diff across different OSs.

**Comment by maggieliu** [comment]
Closing this in favor of : https://github.com/rancher/rancher/issues/28730
