### ISSUE TITLE
[rancher/charts scripts] RFE: Support CRD charts for Rancher Original charts

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#28628]
Need the ability for charts like `rancher-backup-restore-operator` and CIS `rancher-cis-benchmark` to be able to use the generateCRDCharts flag defined in the `package.yaml`. 

In general, this will require modifying the scripts to not assume that the existence of a package.yaml implies the chart comes from an upstream source (e.g. `clean` automatically deletes the chart/ folder just based on whether the `package.yaml` exists rather than based on whether it has a URL in that `package.yaml`).

**Comment by cbron** [comment]
@aiyengar2 wouldn't we still have a package.yaml to specify which CRD to use ? I was thinking changes would be that existence of package.yaml doesn't necessarily mean its upstream.

**Comment by aiyengar2** [comment]
> @aiyengar2 wouldn't we still have a package.yaml to specify which CRD to use ? I was thinking changes would be that existence of package.yaml doesn't necessarily mean its upstream.

Yes; now the existence of the `url` field in the `package.yaml` is what should imply that it's referring to an upstream chart. Otherwise, any / every chart should be able to define a `package.yaml` (and use CRD charts) once these changes are in.

**Comment by cbron** [comment]
https://github.com/rancher/charts/pull/620
