### ISSUE TITLE
Update OPA to the latest

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28633]
Update the OPA chart to the latest stable: https://github.com/open-policy-agent/gatekeeper/releases
Make it not experimental anymore

gzrancher/rancher#12073

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head`

Gatekeeper has options for Chart Version:
![Screen Shot 2020-09-11 at 10 04 58 AM](https://user-images.githubusercontent.com/57409052/92964713-6b583200-f429-11ea-9730-f63d7c545574.png)
Gatekeeper is installed with latest version:
![Screen Shot 2020-09-11 at 12 21 59 PM](https://user-images.githubusercontent.com/57409052/92964718-6d21f580-f429-11ea-989f-beb03944f20c.png)

Found bug while testing new version:
https://github.com/rancher/dashboard/issues/1229
