### ISSUE TITLE
Cannot move istio-system namespace to system project.

### ISSUE THREAD

**Issue by jaggerwang** [rancher/rancher#28643]
After I enabled Istio, the `istio-system` namespace is not in any project, and I tried to move it into `System` project, but there is no `Move` button in the namespace's operation drop list.

![image](https://user-images.githubusercontent.com/1255011/91696353-063b4b80-eba2-11ea-94e0-0ece72425779.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`): 1.18.6
- Istio version: 1.5.9

**Comment by cbron** [comment]
Hi @jaggerwang is this issue still occurring ? There was an unrelated issue where the move action wasn't showing up at the right times and you had to refresh the page. If so can you provide:

* what role your user is, and if the cluster-admin can move it
* how istio was installed, through tools menu or manually via helm chart or istioctl 
* any special options/values set when installing
* if Istio was previously installed/uninstalled on the cluster
