### ISSUE TITLE
Dashboard - returning 404 "<cluster>undefined"  when accessing it after the cluster is deployed

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28646]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Deploy Rancher HA ( `master-head (08/31/2020)` _8d9cedde9_)
- In HA setup access to the dashboard on the local cluster

**Result:**
![Screen Shot 2020-08-31 at 9 36 30 AM](https://user-images.githubusercontent.com/27659/91744247-06215880-eb6e-11ea-8db2-428298d0721a.png)

**Other details that may be helpful:**

Deploying other clusters and trying to access the downstream cluster Dashboard results in the same 404 and appears that the cluster-id is appended with the `undefined` suffix string.

**Environment information**
- Rancher version:  `master-head (08/31/2020)` _8d9cedde9_
- Installation option: HA k8s

**Comment by aaronRancher** [comment]
Dashboard can be accessed by refreshing the page.
But returning to cluster manager and then trying to access dashboard again will result in this error once more.

**Comment by sangeethah** [comment]
Tested with rancher server version - `master-c428bc9feb4b11539bacdfa13f173f22a593eaa4-head`

This issue is not seen anymore.
