### ISSUE TITLE
[Logging V2] Mirror debug fluentbit and fluentd images

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#28657]
banzaicloud/fluentd rancher/banzaicloud-fluentd v1.10.4-alpine-2-debug
fluent/fluent-bit rancher/fluent-fluent-bit 1.5.0-debug

**Comment by nickgerace** [comment]
Up for review. Had to update the image SemVers to v1.11.2 and 1.5.4 respectively.

**Comment by izaac** [comment]
Rancher version: `master-head (10/12/2020)` _f7c0bdb_

I validated the images are pulled properly by upgrading the chart app yaml tag from Dashboard (or during fresh install): All workloads `rancher-logging-*fluentbit` get the `rancher/fluent-fluent-bit:1.5.4-debug` image applied.

From:
![Screen Shot 2020-10-12 at 2 42 01 PM](https://user-images.githubusercontent.com/27659/95792862-28dc7c00-0c99-11eb-814d-d61d11173629.png)

To:
![Screen Shot 2020-10-12 at 2 42 08 PM](https://user-images.githubusercontent.com/27659/95792872-2ed25d00-0c99-11eb-85f3-22ef74dd2b28.png)


We still need to validate this in an RC Airgap setup.

**Comment by cbron** [comment]
Thanks for moving to RC, still need one of those to confirm its in images.txt.

**Comment by mrajashree** [comment]
Can be tested with v2.5.2-rc1

**Comment by izaac** [comment]
Rancher version `v2.5.2-rc1`

`rancher/fluent-fluent-bit-debug:1.5.4-debug` is not in `rancher-images.txt`

```
ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: manifest for <private_registry>/rancher/fluent-fluent-bit:1.5.4-debug not found: manifest unknown: manifest unknown
```

Installation works with the standard image.

**Comment by cbron** [comment]
The debug image isn't in the rancher-images.txt list because it still needs to be added to the values.yaml file, even though nothing in the chart will actually use it.

**Comment by nickgerace** [comment]
Added it to ```values.yaml``` in charts PR [#794](https://github.com/rancher/charts/pull/794).

**Comment by nickgerace** [comment]
PR merged. It should be able to be added to ```rancher-images.txt``` now.

**Comment by mrajashree** [comment]
Can be tested with v2.5.2-rc2

**Comment by izaac** [comment]
Rancher version: `v2.5.2-rc2` 

Installation succeeded using normal install and appending`-debug` to the fluent-bit tag.

Both images were pushed properly using the `rancher-images.txt`
