### ISSUE TITLE
[UI] Replace RKE2 with RKE Federal

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#28650]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Component

**Summary:**
RKE2 clusters will be known as "RKE Federal". Today when you import an RKE2 cluster into ECM the cluster will show up as "RKE2". We should change this -- the cluster should show up and be recognized as "RKE Federal".

**Related:**
RancherD will need to be recognized separately. Today, with no changes made, RancherD would be recognized as an RKE2 cluster. This will need to be changed so it is recognized as a "rancherd" cluster. A separate issue tracks this work here: https://github.com/rancher/rancher/issues/28651

**Comment by sangeethah** [comment]
With latest build from master  - `master-31d7ad327d0287329873868ead67b34f2cda7b01-head` , imported RKE2 clusters show up as "RKE Federal".
<img width="1156" alt="Screen Shot 2020-09-13 at 8 31 16 AM" src="https://user-images.githubusercontent.com/4266958/93022075-bd20c980-f59b-11ea-9067-b4cddb4a148d.png">
