### ISSUE TITLE
rancher agent get incorrect ip when starts in EC2 VPC

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2865]
172.30.2.90 is an internal address. if i up 10 hosts all of them will have `172.30.2.90` address and obviously my cross-host communication become broken...
<img width="298" alt="screenshot 2015-12-02 01 17 59" src="https://cloud.githubusercontent.com/assets/3070298/11516150/b68d7016-9892-11e5-9179-ac145f6387fa.png">
I am using this workaround so far:
```bash
agent_ip=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
docker run -e CATTLE_AGENT_IP="$agent_ip" ...
```
But I am not sure if it survive start/stop host and reassignment new public ip. What do you think?

**Comment by deniseschannon** [comment]
If you start/stop a host and get a new public IP, the workaround to get the host working again is to launch the agent command with the `-e CATTLE_AGENT_IP`. So if you want the IP to be updated, that is the only way right now. This allows your host to continue using the managed network and containers/services would continue to work as normal.

I'm not sure what your curl command is doing exactly, but if you are just worried about re-running the agent command whenever there is a new IP, then it will work.

**Comment by deniseschannon** [comment]
@ndelitski Please re-open if you still have any questions regarding how to update the IP.
