### ISSUE TITLE
Helm-operation pod goes to the Windows node 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28665]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug
found during validating the monitoring app, but it happens to all apps.

**Steps to reproduce (least amount of steps as possible):**
- run rancher:`master-c428bc9feb4b11539bacdfa13f173f22a593eaa4-head` 
- add a custom cluster with Windows node 
- go to dashboard -> apps -> install monitoring v2 

**Result:**
- the helm-operation pod is assigned to the Windows node, but the image does not support Windows.
<img width="1408" alt="Screen Shot 2020-08-31 at 4 57 49 PM" src="https://user-images.githubusercontent.com/6218999/91780216-bceff980-ebab-11ea-828b-8f9a0c0c134a.png">

**Comment by deniseschannon** [comment]
The fix allows the ability for the helm operation pod to only be deployed on Linux worker nodes, but none of the charts are Windows compliant.

**Comment by jiaqiluo** [comment]
The bug fix is validated on `master-ef11fe3b0ae51b35fc1f11b454222ca1f8b4b7d3-head`

The helm operation pod is assigned to a Linux worker node in the mixed cluster.
