### ISSUE TITLE
Run Conformance Testing

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28660]
Need to run the conformance test on:
Rancher => 1.18
RKE1 => 1.18 
Rancher => 1.17

And submit the result to: https://github.com/cncf/k8s-conformance

**Comment by bmdepesa** [comment]
https://github.com/cncf/k8s-conformance/pull/1110
https://github.com/cncf/k8s-conformance/pull/1111
https://github.com/cncf/k8s-conformance/pull/1112

**Comment by bmdepesa** [comment]
All PRs have been merged. 

RKE v1.18
Rancher RKE v1.17, v1.18 are all certified
