### ISSUE TITLE
GlusterFS catalog template does not work on RancherOS

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2866]
From http://forums.rancher.com/t/glusterfs-catalog-continually-restarting-0-47-0-using-catalog-template-3-7-5-rancher1/1085/10

Attempting to run the GlusterFS catalog entry on RancherOS hosts results in an error.

```
time="2015-11-27T08:17:05.956478206Z" level=error msg="HTTP Error" err="Cannot start container 46692e7091874b4dcac7f0bc1bc52b06fe4a6de224a9775faae9ad6bd0a3733e: error gathering device information while adding custom device \"/dev/fuse\": lstat /dev/fuse: no such file or directory" statusCode=500
```

**Comment by cusspvz** [comment]
Can I propose my BTSync image instead? :laughing: :laughing:

**Comment by ibuildthecloud** [comment]
@cusspvz Where is that?  BTsync sounds cool, but is that all closed source?

**Comment by deniseschannon** [comment]
Verified working as of 12/3. 

Note: We updated the catalog item and did not add a new template.

**Comment by cusspvz** [comment]
@ibuildthecloud BTSync software is CS and Freemium.

The useful part is that you can place read-only nodes outside your cluster for backup purposes.
