### ISSUE TITLE
[Logging v2] - rancher-logging logging operator fails to deploy on Windows cluster

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28664]
**What kind of request is this:**
Bug

**Steps to reproduce:**

- Create a Windows cluster (Custom - etcd, control plane, 1 worker-linux, 2 worker-windows)
- Deploy `rancher-logging`

**Result:**

`rancher-logging` logging operator fails to deploy

ErrImagePull: rpc error: code = Unknown desc = image operating system "linux" cannot be used on this platform

**Other details that may be helpful:**

![Screen Shot 2020-08-31 at 4 45 02 PM](https://user-images.githubusercontent.com/27659/91779141-8d3ff200-eba9-11ea-9b8e-d786b6f2e31a.png)

The Linux worker is tainted with `NoSchedule`
Windows workers are not tainted.

**Environment information**
- Rancher version: `master-head (08/31/2020)` _8d9cedde9_ 
- Installation option: HA k8s

**Comment by deniseschannon** [comment]
Might be same root cause as https://github.com/rancher/rancher/issues/28665

**Comment by cbron** [comment]
Should be fixed by: https://github.com/rancher/rancher/issues/28720

**Comment by izaac** [comment]
Rancher version: `v2.5-head (12/01/2020)`  _df2cd2d_
Rancher version: `master-head (12/01/2020)` _a549b47_

rancher-logging version `3.8.001`

fluentbit Pods are only scheduled in the Linux Workers. This was previously validated in #28720 but this time the chart version is newer.
