### ISSUE TITLE
Token expire - the value is in milliseconds when auth-token-max-ttl-minutes is 0 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28678]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher v2.4.6 single install
- edit `v3/settings/auth-token-max-ttl-minutes` to 0 
- Add API Key in Rancher UI
<img width="982" alt="Screen Shot 2020-09-01 at 12 14 35 PM" src="https://user-images.githubusercontent.com/6218999/91895849-bd8c9c80-ec4c-11ea-9248-d6d025240e87.png">

**Result:**
- track the network traffic 
<img width="389" alt="Screen Shot 2020-09-01 at 12 14 28 PM" src="https://user-images.githubusercontent.com/6218999/91895855-bf566000-ec4c-11ea-8c02-b2ead395302a.png">

the value `86400000` is in milliseconds, but the backend expects it is in minutes, thus the expiration date is wrong 
![image](https://user-images.githubusercontent.com/6218999/91895932-e7de5a00-ec4c-11ea-8d51-28ea0f49d640.png)

**Comment by kinarashah** [comment]
This affects the following two scenarios: 
- In 2.4.6, if auth token max ttl is 0 and input ttl is day/month/year from UI. 
- In 2.4.6, if token is created using api `v3/tokens` and input ttl is in milliseconds.

**Comment by jiaqiluo** [comment]
The bugfix is validated on rancher:`v2.4.7-rc2` with the default UI

The steps are the same, and tokens get the correct expiration date.
