### ISSUE TITLE
Support for AKS Availibility Zones

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#28675]
A customer would like support for Availability Zones in Rancher provisioned AKS clusters. This feature is documented here:

https://docs.microsoft.com/en-us/azure/aks/availability-zones

**Comment by prabalsharma** [comment]
AKSv2 supports AZs for supported locations
<img width="771" alt="Screen Shot 2021-07-13 at 3 49 46 PM" src="https://user-images.githubusercontent.com/3749546/125535079-bad5b6b5-f480-4525-ac39-08dc43456f34.png">
<img width="617" alt="Screen Shot 2021-07-13 at 3 50 07 PM" src="https://user-images.githubusercontent.com/3749546/125535109-7e524499-2b8e-409a-b1a4-c1ddfe43cc1d.png">
