### ISSUE TITLE
I have installed k3s with rancher and also multi master etcd but here in rancher UI it shows etcd not applicable but everything works fine. 

### ISSUE THREAD

**Issue by himanshusharma-git** [rancher/rancher#28672]
*Describe your issue here*

![image](https://user-images.githubusercontent.com/40313710/91855500-e465c580-ec82-11ea-8f6a-dc9e32a39e5c.png)

---

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.6` UI: `v2.4.31` |
|Route|`undefined`|

**Comment by qskwood** [comment]
I may have this issue on 2.5.3. What information is needed to diagnose further?

**Comment by rpelissi** [comment]
Hi,
I got the exact same issue. Deployed a k3s cluster with cluster-init to have etc on 3 nodes. The deployed rancher with helm.
Everything looks good except this message and I am not sure if it is normal or not..

Here is my recipe:
- 3 node for the cluster and 2 worker nodes
- Used k3sup to deply the nodes
- node1:
k3sup install \
  --ip $SERVER_IP \
  --user $USER \
  --cluster \
  --k3s-version v1.19.5+k3s1
- node2+3
k3sup join \
  --ip $NEXT_SERVER_IP \
  --user $USER \
  --server-user $USER \
  --server-ip $SERVER_IP \
  --server \
  --k3s-version v1.19.5+k3s1

On worker nodes:
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.19.5+k3s1 K3S_TOKEN=<TOKEN> K3S_URL=https://<LB ip>:6443 sh -

curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
chmod 700 get_helm.sh
./get_helm.sh

helm repo add rancher-stable https://releases.rancher.com/server-charts/stable

kubectl create namespace cattle-system

kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml

kubectl create namespace cert-manager

helm repo add jetstack https://charts.jetstack.io

helm repo update

export KUBECONFIG=/etc/rancher/k3s/k3s.yaml


helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.0.4
  
  
helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=rancher.domain.com

Like it is mentioned everything is green except this.
Thanks to confirm if my recipe is not correct, if it is normal, or if it is a bug.
Thanks!

**Comment by arbrog** [comment]
I also ran into this following a very similar setup process to @rpelissi except I'm only using one node atm. 
K3s v1.20.4+k3s1
Docker 20.10

**Comment by evya123** [comment]
I also have the same problem with 
rancher version is v2.4.15 and the k3s version is v1.19.8+k3s1

**Comment by APoniatowski** [comment]
same here, fresh install (HA config)

**Comment by muralidigi** [comment]
I ran into the same issue with Fresh Install of 3 Node K3S: UI: Rancher Version 2.5.7

NAME    STATUS   ROLES                       AGE   VERSION
q81   Ready    control-plane,etcd,master   25h   v1.20.6+k3s1
q82   Ready    control-plane,etcd,master   24h   v1.20.6+k3s1
q83   Ready    control-plane,etcd,master   24h   v1.20.6+k3s1

**Comment by GLTSC** [comment]
The same problem, offline installation of K3S, three master nodes, etcd cluster；helm install Rancher
K3s：v1.20.7+k3s1
Docker：19.3
Rancher：v2.5.8
OS: Centos 7.4
![image](https://user-images.githubusercontent.com/37522067/124448272-d73ec900-ddb4-11eb-8981-2174fe171f6e.png)

**Comment by donPabloNow** [comment]
Has anyone solved this issue? I am receiving the same error message for no apparent reason

**Comment by donPabloNow** [comment]
![Screenshot_20211030_073333](https://user-images.githubusercontent.com/6468571/139521649-ef49eeb1-8c09-4ecb-b76b-d48141de9f52.png)
