### ISSUE TITLE
Starting up a preconfigured Jenkins instance on centos6

### ISSUE THREAD

**Issue by MarcusSjolin** [rancher/rancher#2867]
I am currently trying out this feature from the catalog and I was able to start it up. Then I realised that I need to set up a Docker API Server to be able to spawn Dockerised Jenkins slaves, so I reconfigured Docker on the host and restarted the process. At this point I was unable to boot up my stack again when the rancher host was attached. Whereby I removed the stack and tried to rebuild it. Unable to start up the actual Jenkins server i proceed to remove all cache files from rancher and reattach the host and try again, this did not help and I'm out of ideas. Do you have any other things that could affect this? 

The /var/jenkins_home does not exist on the host.

/Marcus

**Comment by MarcusSjolin** [comment]
It does successfully boot up docker storage and docker plugins, just that the main server process is stuck at starting, however it does not appear in the Docker ps command

**Comment by cloudnautique** [comment]
About the time you saw this issue the catalog was trying to use jenkins:1.625.1 which was unable to pull from Docker hub. Depending on how thorough you cleaned up Docker/Rancher it could have removed the image from the cache and been unable to refresh. Can you see it in docker ps -a ? If so are there log entries that you can get at?

On CentOS when mounting the Docker socket into a container you need --privileged, which is not used in the catalog. Though I would expect it to still boot. 

Also, as an aside, the jenkins-swarm plugin in the catalog is setup to connect into Jenkins and provide access to the hosts docker socket.

**Comment by deniseschannon** [comment]
@MarcusSjolin Please let me know if you are still having issues with the jenkins catalog entry. As @cloudnautique mentioned we have updated the catalog entry.
