### ISSUE TITLE
Multiple chart upgrades

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#28686]
Add upgrade operation in catalog service that takes multiple charts

**Comment by maggieliu** [comment]
Dev is done waiting to coordinate with frontend.

**Comment by ibuildthecloud** [comment]
Front end PR: https://github.com/rancher/dashboard/pull/1177

**Comment by sangeethah** [comment]
Blocked on https://github.com/rancher/rancher/issues/28842

**Comment by bmdepesa** [comment]
rancher/rancher:master-head <>

* Fresh install / upgrade of Istio chart with `auto-install` for Kiali CRDs
  * Install Request from UI contains array with both charts
  * Both charts are correctly installed
  * Upgrade request from UI contains array with both charts and upgrade is successful
* The Kiali auto-install for Istio is set to a specific version - we can also `match` the auto-install chart version to the parent chart version -- this still needs to be tested.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head e919796

* Tested the above and verified `match` versions in Kiali
