### ISSUE TITLE
[Logging V2] Update upstream logging operator to 3.6.0

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#28682]
Banzai Cloud has released a new version of the logging operator with breaking changes. we need to update to this new version to prevent breaking changes later on.

https://github.com/banzaicloud/logging-operator/releases/tag/3.6.0

**Comment by izaac** [comment]
Rancher version `master-head (09/14/2020)` _e919796c808d0aa643cb3491581bffcd64cfbe56_

Validated the installation using helm of the `rancher-logging` 3.6.000 chart.
Validated the use of the `globalOutputRefs` `localOutputRefs` works after install.
Logs were flowing to the configured Output (Elasticseach)
`additionalLoggingSources` continued working too.
