### ISSUE TITLE
[Request] multiple ssl on load balancer

### ISSUE THREAD

**Issue by alexw23** [rancher/rancher#2869]
Would it be possible to select multiple certificates on a load balancer (http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#5.1-crt)

Rather then a drop down - could have a checklist that will loop through each certificate in a directory.

This will make it much more efficient as right now we are locked down to a public ip/port of 80/443, so we want our load balancers to route to multiple services at once to save on the number of running instances.

This means instead of having 6 instances of a load balancer routing to 1 service each. We can have 6 instances routing to 6 services.

**Comment by vincent99** [comment]
Other than the specifics of what kind of html input it is, you can already do this.  There is one primary certificate for old clients that don't support SNI, and then right below that you can add many "Alternate Certs" that will be used if SNI matches.
