### ISSUE TITLE
Rancher apps uncompatible with Helm3 CLI

### ISSUE THREAD

**Issue by imilchev** [rancher/rancher#28699]
**What kind of request is this (question/bug/enhancement/feature request):** If I install a Helm3 chart via the UI it is possible to see the chart in helm using `helm ls -A`. However, trying to upgrade that same chart using helm fails. If I deploy the exact same helm chart using the Helm3 CLI, then upgrading is also possible but, of course, I no longer see that in Apps in the Rancher UI. Is it possible to somehow get both to work (UI + Helm CLI)?

**Steps to reproduce (least amount of steps as possible):** In my case I had `bitnami/kafka` installed via the UI and I tried to upgrade it via Helm CLI and the goal was to upgrade the `replicaCount`. This failed.

**Result:** Failed with Helm saying that it is not possible to update StatefulSet properties after deployment and only replicas field can be changed.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): single install (Docker)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): bare-metal
- Kubernetes version (use `kubectl version`): v1.18.6

**Comment by Just-Insane** [comment]
Would also like to know if this is possible. Access to the management UI of my cluster keeps failing and being able to update via the CLI would be very useful.
