### ISSUE TITLE
Failed etcd encryption when rewriting secrets

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#28707]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy v1.15.5 custom cluster
- Create a large number of secrets (100k at 1k in size)
- Enable etcd encryption

**Result:**
The cluster will get stuck updating and will keep failing 

**Other details that may be helpful:**
We currently believe the failure of the encryption function is due to a long-running `LIST`​ of `core/v1/secrets​` within their cluster. RKE has a hardcoded 30-second timeout on the K8s clientset (seen here: https://github.com/rancher/rke/blob/v1.0.6/k8s/k8s.go#L32 and with a constant definition here: https://github.com/rancher/rke/blob/v1.0.6/k8s/k8s.go#L18), and performs a `LIST`​ call to the Kubernetes API server. Upon the data provided by the customer, it is evident that it can (and likely does) take over 30 seconds for the `LIST`​ call to be performed, hence leading to the errors similar to:
```
E0819 02:40:54.107871 8 request.go:879] Unexpected error when reading response body: net/http: request canceled (Client.Timeout exceeded while reading body)
```

I used this script to create dummy secrets.
```
#!/bin/bash
task(){
  dd bs=1024 count=1 </dev/urandom > random-"$1"
  echo "" >> random-"$1"
  echo "GoodData" >> random-"$1"
  kubectl --kubeconfig kubeconfig -n secrets create secret generic secret-"$1" --from-literal=username=GoodData --from-file=password=./random-"$1"
  rm -f random-"$1"
}
N=50
(
for count in {000000..100000}
do
   ((i=i%N)); ((i++==0)) && wait
   task "$count" &
done
)
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.6
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 6/32GB (3 etcd, 2 cp, and 96 worker nodes)
- Kubernetes version (use `kubectl version`): v1.15.5

**Comment by Oats87** [comment]
@mattmattox Using your script, were you able to reproduce the timeout?

**Comment by mattmattox** [comment]
Moving this over to https://github.com/rancher/rancher/issues/28752
