### ISSUE TITLE
Rancher fails to configure iptables on startup

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#2870]
I don't know if this is causing any problems, but I thought I'd mention the error for your review.

===================================================================
[[apply.sh:5] iptables-save
[[apply.sh:5] sed 's/-A POSTROUTING //'
[[apply.sh:5] grep -- '-A POSTROUTING.* -o docker0 -j MASQUERADE'
[apply.sh:5] MASQ='-s 172.17.42.0/24 ! -o docker0 -j MASQUERADE
-s 172.17.0.0/16 ! -o docker0 -j MASQUERADE'
[apply.sh:7] '[' -n '-s 172.17.42.0/24 ! -o docker0 -j MASQUERADE
-s 172.17.0.0/16 ! -o docker0 -j MASQUERADE' ']'
[apply.sh:8] cat
[apply.sh:12] sed -i '/#POSTRULES/r masq-rules' content-home/etc/cattle/host-iptables
[apply.sh:15] apply_config iptables-restore -n etc/cattle/host-iptables
[scripts.sh:147] local file=etc/cattle/host-iptables
[scripts.sh:148] local 'cmd=iptables-restore -n'
[scripts.sh:150] iptables-restore -n content-home/etc/cattle/host-iptables
iptables-restore v1.4.21: Need TCP, UDP, SCTP or DCCP with port specification
Error occurred at line: 23
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
[scripts.sh:151] '[' -e /var/lib/cattle/etc/cattle/host-iptables ']'
[scripts.sh:154] return 1

=====================================================================
The host server was created in vsphere. I don't have this problem on an openstack server, btw. Is is possible that vmware doesn't allow containers to edit iptables?

**Comment by deniseschannon** [comment]
@eebjr Were you using docker-machine to start an agent or were you running it using a custom command? If you were using docker-machine, then this could be similar to https://github.com/rancher/rancher/issues/3233.

**Comment by deniseschannon** [comment]
@eebjr If you are still seeing this, please re-open. We've recently updated docker-machine.
