### ISSUE TITLE
tagged v2.4.7-rc4, but after v2.4.7  been released!

### ISSUE THREAD

**Issue by adrianovieira** [rancher/rancher#28710]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**

check your tags (https://github.com/rancher/rancher/tags)

**Result:**

![image](https://user-images.githubusercontent.com/5561794/92019916-bc7f6c00-ed2d-11ea-9b43-ddad97fe2176.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by maggieliu** [comment]
@adrianovieira  Thanks for the question. It was tagged by mistake. We re-tagged a 2.4.8-rc1
