### ISSUE TITLE
Add validation in CI to check no multiple new versions of the same chart in a given release

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28711]
Need to add validation logic in CI to make sure we don't create multiple new chart versions in the rancher/charts repo for a given release.

**Comment by maggieliu** [comment]
reverted here: https://github.com/rancher/charts/pull/632

**Comment by aiyengar2** [comment]
Should be addressed as part of https://github.com/rancher/rancher/issues/28730; not sure if we want to close this issue out in favor of that or address this sooner.

@StrongMonkey any thoughts?

**Comment by maggieliu** [comment]
close in favor of #28730
