### ISSUE TITLE
no error reported in the UI when creating/cloning/editing an AWS Node Template if missing the required perms

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#28719]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

- create new aws cloud credentials where the aws account is missing the `kms:ListKeys` IAM permission
- attempt to create a node template while using the newly created cloud credential
- select your region and cloud credentials
- hit `Next: Authenticate & configure nodes`

**Result:**

The `Next: Authenticate & configure nodes` button will turn into a `Loading` button that will endlessly sit at loading. you won't see any errors or timeouts and it will continue to say it is Loading for as long as you leave the Node Template UI box up (I hit Cancel after 10 minutes). 

**Other details that may be helpful:**

This change to the required AWS perms was introduced in v2.4.6 in rancher/rancher#27965 

You have to enable the browser dev tools to see what the underlying issue is.

When using the dev tools to inspect the traffic, you will see a single request going out once you click "Next" to the KMS endpoint in your chosen AWS region 

For me, this was https://XXXXX/meta/proxy/kms.us-east-1.amazonaws.com/

This is the error that I got back:

`{"__type":"AccessDeniedException","Message":"User: arn:aws:iam::XXXX:user/YYYYY is not authorized to perform: kms:ListKeys on resource: *"}`

**Environment information**
- Rancher version: v2.4.6

gzrancher/rancher#12099

**Comment by westlywright** [comment]
There was some logic in place that attempted to handle the error gracefully but this clearly did not work. The logic was a bit to specific so I've made the error handling a massively more generic here. We still wont display a big red error. If the call succeeds and the user selects to encrypt with kms keys a dropdown with the keys they can see. If the call fails the user may still select to encrypt and enter the KeyARN if they know it. In this case the user will see warning text to this effect.

**Comment by westlywright** [comment]
Fix is available in `latest-2.4`
