### ISSUE TITLE
Linking of services broken with host-networking

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#2871]
Hi,

given the following stack and services:

```
stackA/serviceA
stackB/serviceB
```

* WORKS: if both services are running in managed network and stackA/serviceA links to stackB/serviceB
* WORKS: if stackA/serviceA runs under managed network, stackB/serviceB under host-networking and stackA/serviceA links to stackB/serviceB
* BROKEN: stackA/serviceA runs under host-networking, stackB/serviceB under managed network and stackA/serviceA links to stackB/serviceB
* BROKEN: if both services are running in host-networking and stackA/serviceA links to stackB/serviceB

I've also tested with services running in the same stack, behavior is the same.

Cheers,
Matteo

**Comment by deniseschannon** [comment]
Thanks for the detailed analysis. In order to take advantage of the Rancher DNS and host networking, you'll aso need to add the `io.rancher.container.dns=true` label to the service. 

RancherDNS is only available by default to managed network, but host networking can work with this label. 

http://docs.rancher.com/rancher/labels/

**Comment by m4ce** [comment]
@deniseschannon,

the services I tested with were having io.rancher.container.dns set to true when under host networking, but the environment variables docker sets up when linking were not there.

Cheers,
Matteo

**Comment by deniseschannon** [comment]
Docker doesn't support linking with `--net=host`, so we won't be doing it either. 

If you try to run a  container with `--links and --net=host`, you'll get this error:
`ERROR: Conflicting options: --net=host can't be used with links. This would result in undefined behavior`
