### ISSUE TITLE
Update the KMS encryption key dropdown box to a text box

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28724]
Related to change made here: https://github.com/rancher/rancher/issues/27965

Anyone trying to manipulate node templates now needs the kmskey listing permissions. Need to change the dropdown box to text box to remove this listing requirement.

**Comment by westlywright** [comment]
This form field already had a text input, the bug stemmed from how I was handling the error. It was too specific and I've made that error handling more generic so it will catch any case that this call fails on and replace the dropdown with a text input. With this UX if the call to fetch the keys succeeds the user will be able to select a key, if it fails the user will only be able to enter a key in a text box. Additionally if the call fails and the user selects the Encryption option they will see some warning help text under the input letting them know we couldn't load the data but they can enter the KeyARN if they know it.

**Comment by westlywright** [comment]
Fix is available in `latest-2.4`

**Comment by sowmyav27** [comment]
**On 2.4-head - latest ui: `v2.4-3573-head`**

- Create an AWS note template
- Enter AWS cloud creds and click on Next/Authenticate
- User sees an error in the console
- In the Instances Section, enable Encryption. User sees this.

<img width="1722" alt="Screen Shot 2020-09-03 at 11 30 59 AM" src="https://user-images.githubusercontent.com/26032343/92153526-49333400-edd9-11ea-996b-9ab2a1d717a7.png">

**Comment by westlywright** [comment]
I don't think there is a problem here. The dropdown takes custom entries and is one we use elsewhere through the UI. The call failing will be reported in the console but it is handled and does not prevent you from creating or editing a node template.

**Comment by sowmyav27** [comment]
**In 2.4-head `v2.4-3573-head`**

1. Create an AWS node template
2. Enter AWS cloud creds and click on Next/Authenticate
3. User sees an error in the console
4. In the KMS keys inputfield, enter a KMS key (able to list this key in the AWS console)
5. Bring up a cluster using this node template
6. nodes are created with Encryption enabled and this Key is used.

**Comment by sowmyav27** [comment]
reopening for a fix in master.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `5d5ef3f8f`**

- Create an AWS node template
- Enter AWS cloud creds and click on Next/Authenticate
- User sees an error in the console
- User is able to enter a KMS key value in the field when encryption is set to true
- User is able to create a node template
