### ISSUE TITLE
[Logging V2] Windows Support

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#28721]
Ensure we can collect logs from windows nodes.
gz#16339

**Comment by nickgerace** [comment]
https://github.com/banzaicloud/logging-operator/issues/656

**Comment by nickgerace** [comment]
Relevant PR: https://github.com/banzaicloud/logging-operator/pull/665

**Comment by cbron** [comment]
Need to test airgap.

**Comment by izaac** [comment]
Rancher version: `v2.5-head (04/08/2021)` _7426ba8_
Logging chart version: `3.9.400-rc02`
Windows nodes: `Windows 2019 LTSC`

Files in the path `C:\var\log\containers` are symlinks to empty/non-existent files so the Windows Nodes logs are not generated properly and thus not sent to the clusterOutput.

```
Directory of C:\var\log\containers
04/07/2021  10:27 PM    <DIR>          .
04/07/2021  10:27 PM    <DIR>          ..
04/07/2021  10:21 PM    <SYMLINK>      cattle-node-agent-windows-v4xg5_cattle-system_agent-9d26a3dc258d04d0b086e0072a9c71359e3f56a5e753e337ab9149d9ca202a4c.log [\var\log\pods\cattle-system_cattle-node-agent-windows-v4xg5_c9882c25-c7df-4e78-869f-016a7de38ca5\agent\1.log]
04/07/2021  10:21 PM    <SYMLINK>      cattle-node-agent-windows-v4xg5_cattle-system_agent-f1ee57798723a65c2a325512e7709c6abe966a457f99030312195365f2753485.log [\var\log\pods\cattle-system_cattle-node-agent-windows-v4xg5_c9882c25-c7df-4e78-869f-016a7de38ca5\agent\0.log]
04/07/2021  10:25 PM    <SYMLINK>      rancher-logging-win-agent-fluentbit-jnfhm_cattle-logging-system_fluent-bit-45af2731c3721ab2a4cd2781d443d97917ff4b1d65e8b3308144a8396542ff18.log [\var\log\pods\cattle-logging-system_rancher-logging-win-agent-fluentbit-jnfhm_c129385b-56ce-4dfc-9ee7-b7d8b551bba5\fluent-bit\0.log]
               3 File(s)              0 bytes
               2 Dir(s)  80,392,036,352 bytes free
               
               

# windows aggregator pod log

[2021/04/07 22:25:40] [ info] [sp] stream processor started
[2021/04/07 22:27:02] [error] [C:\projects\fluent-bit-2e87g\plugins\in_tail\tail_file.c:1041 errno=0] No error
[2021/04/07 22:27:02] [error] [input:tail:tail.0] link_inode=1125899907198775 cannot detect if file: C:\var\log\containers\fleet-agent-766d87bb55-lwd6k_fleet-system_fleet-agent-8032cda970ec762201df6e81c7391ee6141b8a08075fd1afddf2fccc012a5e75.log
[2021/04/07 22:27:02] [ info] [input:tail:tail.0] inode=1125899907198772 handle rotation(): C:\var\log\containers\fleet-agent-766d87bb55-lwd6k_fleet-system_fleet-agent-8032cda970ec762201df6e81c7391ee6141b8a08075fd1afddf2fccc012a5e75.log => C:\ProgramData\docker\containers\8032cda970ec762201df6e81c7391ee6141b8a08075fd1afddf2fccc012a5e75\8032cda970ec762201df6e81c7391ee6141b8a08075fd1afddf2fccc012a5e75-json.log
```

**Comment by nickgerace** [comment]
Found the issue: symlinks do not always work, depending on the containers version.
```
administrator@IP-AC1F0B93 C:\var\log\containers>dir

04/08/2021  04:49 PM    <DIR>          .
04/08/2021  04:49 PM    <DIR>          ..
04/08/2021  04:39 PM    <SYMLINK>      cattle-node-agent-windows-2zmcb_cattle-system_agent-84ddb2c97ebb0f19d024e1d98af5dfab130bf0b4167b80c33b0bc8d6a8907d40.log [\var\log\pods\cattle-s
ystem_cattle-node-agent-windows-2zmcb_6ea9ccc6-5ac4-48ef-91e5-c694f80c9eaf\agent\0.log]
04/08/2021  04:49 PM    <SYMLINK>      rancher-logging-win-agent-fluentbit-ss8mq_cattle-logging-system_fluent-bit-fdc46cb9e68f67266dfae47455af0c5b54592350d20099ac5bee140ebfea9958.log
[\var\log\pods\cattle-logging-system_rancher-logging-win-agent-fluentbit-ss8mq_d945a6bc-84e6-455a-8ed7-69ad1480cf02\fluent-bit\0.log]
               2 File(s)              0 bytes
               2 Dir(s)  80,642,416,640 bytes free
```

This affects both locations used for tailing logs.

```
administrator@IP-AC1F0B93 C:\var\log\containers>dir \var\lib\rancher\rke\log

04/08/2021  04:39 PM    <DIR>          .
04/08/2021  04:39 PM    <DIR>          ..
04/08/2021  04:39 PM    <SYMLINK>      kube-proxy_bf9c37fe003e6417b7c00dda1a25aa50183ea091daff4ec1d7ac35c6b11d36db.log [C:\ProgramData\docker\containers\bf9c37fe003e6417b7c00dda1a25aa
50183ea091daff4ec1d7ac35c6b11d36db\bf9c37fe003e6417b7c00dda1a25aa50183ea091daff4ec1d7ac35c6b11d36db-json.log]
04/08/2021  04:39 PM    <SYMLINK>      kubelet_081472190c2777a4e9364f173a25e23be31eb04337672e41a6bdd68342460654.log [C:\ProgramData\docker\containers\081472190c2777a4e9364f173a25e23be
31eb04337672e41a6bdd68342460654\081472190c2777a4e9364f173a25e23be31eb04337672e41a6bdd68342460654-json.log]
04/08/2021  04:39 PM    <SYMLINK>      nginx-proxy_6dbf5a192135d40046f6c6b7177376aaaa064dccd9adf81952db7f76b88816b4.log [C:\ProgramData\docker\containers\6dbf5a192135d40046f6c6b717737
6aaaa064dccd9adf81952db7f76b88816b4\6dbf5a192135d40046f6c6b7177376aaaa064dccd9adf81952db7f76b88816b4-json.log]
04/08/2021  04:37 PM    <SYMLINK>      service-sidekick_9374610b1e82ee862178e425fa13e8e6de3b39de9cede2b006e4d1f4019256d9.log [C:\ProgramData\docker\containers\9374610b1e82ee862178e425
fa13e8e6de3b39de9cede2b006e4d1f4019256d9\9374610b1e82ee862178e425fa13e8e6de3b39de9cede2b006e4d1f4019256d9-json.log]
               4 File(s)              0 bytes
               2 Dir(s)  80,642,416,640 bytes free

**Comment by nickgerace** [comment]
Update: all logs eventually reach `C:\ProgramData\docker\containers\**\*.log`

**Comment by nickgerace** [comment]
Relevant upstream issue: https://github.com/fluent/fluent-bit/issues/2087

**Comment by izaac** [comment]
After a second check in a call with Nick 
I see the logs getting collected from the `\var\log\containers` symlinks. Specifically with a sample windows webserver and a ClusterOutput of type fluentd.
Chart version `3.9.400-rc02`

```
2021-04-09 19:16:27.087750900 +0000 kubernetes.C.var.log.containers.win-webserver-6d88dcc49f-5v52x_windows_windowswebserver-68989f57157d3b7d6045d86735fd7eb7ae79c8644ce5fb9e919bb1b3b2dd4cff.log: {"log":"<html><body><H1>Windows Container Web Server</H1><p>IP 10.42.5.51 callerCount 204 </body></html>\r\n","stream":"stdout","time":"2021-04-09T19:16:27.0877509Z","kubernetes":{"pod_name":"win-webserver-6d88dcc49f-5v52x","namespace_name":"windows","pod_id":"1c7b9702-f1b8-479a-b55f-4698e99e7a3a","labels":{"app":"win-webserver","pod-template-hash":"6d88dcc49f"},"host":"ip-ac1f0f5d","container_name":"windowswebserver","docker_id":"68989f57157d3b7d6045d86735fd7eb7ae79c8644ce5fb9e919bb1b3b2dd4cff","container_hash":"mcr.microsoft.com/windows/servercore@sha256:201846cfdf83cd260757fab57389400e38bd462c84fb4a56ad0f5b5861250367","container_image":"mcr.microsoft.com/windows/servercore:1809"}
```

There aren't control plane logs in that path however.

**Comment by nickgerace** [comment]
Confirmed that logs are being shipped properly on Windows nodes from `\var\log\containers`.
This was validating with the following steps:

1. Delete the opeator `deployment` and `statefulset` to render the logging system "static" 
2. Changed the `fluent-bit.conf` via the `win-agent` secret to print to stdout
3. Deleted the agent pod and tailed the new pod to detect stdout
4. Confirmed that `\var\log\containers` symlinks were working and that logs were being ingested properly
5. However, discovered that `\var\lib\rancher\rke\log` was not being ingested, which has resulted in creation of https://github.com/rancher/rancher/issues/32021

As a result of this investigation, this issue is dependent on https://github.com/rancher/rancher/issues/32021 being solved, _but_ the original concern that caused this to be reopened has been resolved.

Thank you for the help! @paynejacob @izaac @luthermonson

**Comment by nickgerace** [comment]
This issue is also dependent on https://github.com/rancher/rancher/issues/32016's resolution.

**Comment by nickgerace** [comment]
This can be tested for everything but airgap. The airgap backport PR is awaiting a passing build. 
https://github.com/rancher/rancher/pull/32061

**Comment by izaac** [comment]
Airgap test will be done as part of https://github.com/rancher/rancher/issues/32016

**Comment by izaac** [comment]
Rancher version `v2.5.8-rc2` 
Logging Chart version: `3.9.400-rc03`
Fluentd ClusterOutput.
Windows 2019 (1809)

Logs from `C:\var\log\containers` are collected. I see logs in the clusteroutput also using a Windows webserver app.
RKE logs from `C:\var\lib\rancher\rke\log` are collected too using the `additionalLoggingSources.rke.enabled=true` 
Ran into this issue: https://github.com/rancher/rancher/issues/32074

There is a pending Dashboard `values.yaml` issue that needs to be addressed: https://github.com/rancher/dashboard/issues/2626

**Comment by izaac** [comment]
master-head issue: #32077

**Comment by nickgerace** [comment]
Opened a new issue that @izaac encountered here: https://github.com/rancher/dashboard/issues/2684

Source: https://github.com/rancher/rancher/issues/28721#issuecomment-818321740

The UI sets `global.cattle.windows.enabled` to true, but not `additionalLoggingSources.rke.enabled` to true because the provider is `'rke.windows'` and not `rke`.

To be clear: https://github.com/rancher/dashboard/issues/2626 has been closed in favor of https://github.com/rancher/dashboard/issues/2684
