### ISSUE TITLE
Rewrite charts build scripts

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#28730]
When charts was initially developed it's goal was just to pull in and patch upstream charts. Since then it has developed into a full framework with the work around splitting CRDs, annotation management, vendoring and patching sub-charts, chart validation, and working with local charts.

To do all that we used bash which has become unreadable and confusing. Ideally we can turn into a go framework, or a different framework that is more readable and maintainable long-term.

**Comment by cbron** [comment]
We should consider going the route of forking or rewriting specific features instead of using build scripts for them, as 1 or 2 charts (monitoring/istio) contribute the majority of the complexity.

**Comment by cbron** [comment]
related https://github.com/rancher/charts/pull/649

**Comment by cbron** [comment]
All original charts should be moved out of the charts repo into their own repo, then pulled into charts with package.yaml. See fleet for example.

**Comment by aiyengar2** [comment]
Should resolve https://github.com/rancher/rancher/issues/28320

**Comment by cbron** [comment]
One more thing we should do: not generate directly to main branch as method of pushing to production. Right now if there is a problem in the generate scripts that problem would go directly into `main` (production). 
We should instead remove `main-source`, and have a `staging-source` and `staging` branch, and have our push to production simply be a PR to move the static files from `staging` to `main`. That step would still only happen during a release.

**Comment by cbron** [comment]
If possible we should automate a "blocklist" during PR validation, where if an asset that is already live on `main` is attempted to be changed the PR fails.
