### ISSUE TITLE
Enhancement for rke etcd encryption rewrite process - client timeout

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#28752]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
- Create a large cluster (100+ nodes)
- Create a large number of secrets (10,000+)
- Enable etcd encryption

**Result:**
RKE has a hardcoded 30-second timeout on the K8s clientset (seen here: https://github.com/rancher/rke/blob/v1.0.6/k8s/k8s.go#L32 and with a constant definition here: https://github.com/rancher/rke/blob/v1.0.6/k8s/k8s.go#L18) and performs a LIST​ call to the Kubernetes API server. Upon the data provided by the customer, it is evident that it can (and likely does) take over 30 seconds for the LIST​ call to be performed.

It would be helpful if this timeout could be customized,

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.6
- Installation option (single install/HA): HA

gz#11659

**Comment by sowmyav27** [comment]
**On 2.5.1,**

- deploy a cluster - 3 etcd, 3 control and 3 worker nodes.
- Create 22k secrets - 15k size on this cluster
- Enable secrets encryption on the cluster.
- There was no client timout seen. The encryption finished, and the cluster came up Active. 

Could not reproduce the issue

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `bb69b0` and master-head - commit id: `4297ee10`**

- deployed a custom cluster  - 3 etcd, 3 control and 3 worker nodes
- Created about 10k secrets on the cluster (15kb size)
- Enable secrets encryption on the cluster.
- There was no client timout seen. The encryption finished, and the cluster came up Active.
