### ISSUE TITLE
Enhancement for rke etcd encryption rewrite process - batch

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#28753]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**

- Create a large cluster (100+ nodes)
- Create a large number of secrets (10,000+)
- Enable etcd encryption

**Result:**
Right now, when enabling or changing the encryption keys. We create a list of all secrets as the bring of the process then go through that list. The problem is what happens when secrets change and/or get deleted during that process. Currently, if a secret created after the process has started it will get missed. Also if a secret is deleted the rewrite will error out and stop and can leave the cluster in a broken state.

**Other details that may be helpful:**
It would be helpful if we broke the process up by namespace or something like that. So we don't have to start over every time there is an issue.

Also, it would be helpful if in the debug logging. If it printed more information about where it's at in the rewrite process.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.6
- Installation option (single install/HA): HA

gz#11659

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/28400

**Comment by sowmyav27** [comment]
Currently the batch size if 250. But reopening this issue for some logging about it in debug/trace mode in rancher logs.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `48254f94` and master-head commit id: ``**

```
2020/12/23 21:58:16 [DEBUG] [rewrite-secrets] retrieving cluster secrets with batch size: 250
```

**Comment by sowmyav27** [comment]
Reopening for the fixes to be vendored into master branch

**Comment by sowmyav27** [comment]
Master is tracked here - https://github.com/rancher/rancher/issues/30646
