### ISSUE TITLE
[backport] RFE: Flag to change the number of Helm Version Histories we keep for Charts deployed by Rancher

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#28765]
https://github.com/rancher/rancher/issues/28728

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4-head 6e6f3429b

* Rancher HA install
* Deploy downstream cluster
* Helm v2
  * Check `/v3/settings/helm-max-history` and see the default set to `10`
  * Deploy an app from a Helm v2 catalog and upgrade 10 times
  * Check ConfigMaps for the project where the app was deployed and see 10 ConfigMaps for each version of the app
  * Change `/v3/settings/helm-max-history` to `2` and upgrade the app again
  * Check ConfigMaps and see 2 ConfigMaps listed for the app version history
  * Upgrade again and see only 2 ConfigMaps listed with the appropriate versions
* Helm v3
  * Check `/v3/settings/helm-max-history` and see the value set to `2`, change it to `4`
  * Deploy an app from a Helm v3 catalog and upgrade 5 times
  * Check Secrets for the project where the app was deployed and see 5 secrets for each version of the app
  * Change `/v3/settings/helm-max-history` to `2` and upgrade the app again
  * Check Secrets and see 2 secrets listed for the app version history
  * Upgrade again and see only 2 secrets listed with the appropriate versions
* Set the value to `2` and upgrade 4 or 5 times
  * Revert to the oldest version of the app (preferably a previous verson)
  * The app rolls back successfully
