### ISSUE TITLE
Missing translation for ui-default-landing setting's description.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#28762]
Rancher server version - `master-82695bc75adbe7ff9f2aeaaf1d62bc3e9dbea59c-head`

Steps to reproduce the problem:
Deploy Rancher server.
Navigate to setting page:

<img width="704" alt="Screen Shot 2020-09-04 at 3 37 40 PM" src="https://user-images.githubusercontent.com/4266958/92289272-c5ef0c80-eec4-11ea-95d8-bebce762395d.png">

**Comment by deniseschannon** [comment]
Fixed in master-head as of 9/22.

![Screen Shot 2020-09-22 at 9.25.25 AM.png](https://zube.io/files/rancher/51b149057661e525b60e96d63a1e81fb-screen-shot-2020-09-22-at-9-25-25-am.png)
