### ISSUE TITLE
Streamline the hosts display so that they are more uniform for all different OS types 

### ISSUE THREAD

**Issue by hrwebasst** [rancher/rancher#2876]
When server stats or ip addresses differ the display for hosts can be annoyingly different. I know it's minor...
![display server](https://cloud.githubusercontent.com/assets/9060082/11541672/4ed8c050-98e8-11e5-8b1b-af279f0ddd8c.png)

**Comment by vincent99** [comment]
@hrwebasst Is this better in 0.59+?  They're on more specific separate rows now.
