### ISSUE TITLE
failed to import RKE2 cluster into Rancher

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28763]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- create a 3-node RKE2 cluster, version `beta16`
- run rancher:`master-4911f8b116eb845ce72bda40fc449f0a4ce54025-head` in HA mode
- import the RKE2 cluser into Rancher 

**Result:**
- the pod of `cattle-cluster-agent` shows the following error
```
ERROR: https://jiaqi84723.qa.rancher.space/ping is not accessible (Could not resolve host: jiaqi84723.qa.rancher.space)
```

**Other details that may be helpful:**
- I can import k3s cluster and RKE cluster into the same Rancher setup without any problem.
- the URL is accessible 
```
> curl -k https://jiaqi84723.qa.rancher.space/ping
pong%
```

**Comment by jiaqiluo** [comment]
the following versions work as the last time we did the same test

RKE2 - beta11 
Rancher - v2.5.0-alpha1

**Comment by rancher-max** [comment]
Installing rke2 cluster was done with the following steps:

```
sudo -i
sudo mkdir -p /etc/rancher/rke2 && \
sudo vi /etc/rancher/rke2/config.yaml
tls-san: 
  - <some valid fqdn>
token: <node token>
server: https://<node1 public IP>:9345

curl -sfL https://raw.githubusercontent.com/rancher/rke2/master/install.sh -o install.sh && \
chmod +x install.sh

sudo INSTALL_RKE2_VERSION=v1.18.4-beta16+rke2 INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD='installer' ./install.sh
```

The contents of config.yaml should only include `token` and `server` values when adding additional server nodes. Also, if adding agent node, it's the same but without `tls-san` value and then one change on the final command for: `INSTALL_RKE2_TYPE='agent'`

**Comment by ShylajaDevadiga** [comment]
Using 
Rancher master-head (commit id 343b8e1) on a HA Setup

Importing k3s cluster (v1.18.8+k3s1) was successful.
Importing rke2 cluster (v1.18.4-beta17+rke2)  failed with cluster-agent being in CrashLoopBackoff state.
```
 kubectl get pods -A  --kubeconfig=/etc/rancher/rke2/rke2.yaml
NAMESPACE       NAME                                                  READY   STATUS             RESTARTS   AGE
cattle-system   cattle-cluster-agent-6847744b78-sv7lt                 0/1     CrashLoopBackOff   7          16m

Events:
  Type     Reason     Age                     From                       Message
  ----     ------     ----                    ----                       -------
  Normal   Scheduled  5m                      default-scheduler          Successfully assigned cattle-system/cattle-cluster-agent-6847744b78-sv7lt to ip-172-31-15-154
  Normal   Pulling    5m                      kubelet, ip-172-31-15-154  Pulling image "rancher/rancher-agent:master-343b8e19c7dafc0118564458186ef57fedee7558-head"
  Normal   Pulled     4m49s                   kubelet, ip-172-31-15-154  Successfully pulled image "rancher/rancher-agent:master-343b8e19c7dafc0118564458186ef57fedee7558-head"
  Normal   Created    3m51s (x3 over 4m45s)   kubelet, ip-172-31-15-154  Created container cluster-register
  Normal   Started    3m51s (x3 over 4m45s)   kubelet, ip-172-31-15-154  Started container cluster-register
  Warning  Unhealthy  3m34s (x11 over 4m39s)  kubelet, ip-172-31-15-154  Readiness probe failed: Get "http://10.42.0.8:8080/health": dial tcp 10.42.0.8:8080: connect: connection refused
  Warning  BackOff    3m16s (x3 over 4m3s)    kubelet, ip-172-31-15-154  Back-off restarting failed container
```

![image](https://user-images.githubusercontent.com/56045581/92551592-34a8ce80-f213-11ea-99f4-5f6ecf9b450a.png)

**Comment by MonzElmasry** [comment]
fixed via:  https://github.com/rancher/rke2/pull/299

**Comment by ShylajaDevadiga** [comment]
Validated using rke2 master build
```
rke2 -v
rke2 version v1.18.4-dev+babe152f 
```
Import was successful and URL is accessible
```
curl -k  https://sowmya-ha.qa.rancher.space/ping
pong
```
![image](https://user-images.githubusercontent.com/56045581/92789921-274d2a80-f360-11ea-92bb-ff4594e066f1.png)
