### ISSUE TITLE
[Monitoring V2] Check k3s cluster with minimum CPU requirements

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#28787]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Install Monitoring V2 on a cluster with minimum CPU requirements. I used 3 DigitalOcean Droplets each with 1 GB / 1 CPU + 25 GB SSD Disk + 1000 GB transfer.

**Result:**
The whole cluster crashed.

This was tested during the initial prototypes of Monitoring V2 so it's possible this issue no longer exists, but we should double check that we do not encounter this error on the latest version of the chart.

Update: I think the whole cluster was crashing before since we didn't have resource limits / requests introduced at the time. Now that we do, the issue is that the Prometheus pod keeps getting OOMKilled

**Comment by jiaqiluo** [comment]
The `Prometheus` container keeps crashing because of `OOMKill` although the node and clusters have sufficient memory resource

About the setup:
Rancher `master-76c26fb0f9d491d1dc12fbde8947812175c277ba-head`, HA installation
Imported K3s cluster, `v1.18.8+k3s1`, 2 server nodes + 3 worker nodes 


The crash happens no matter the pod `prometheus-rancher-monitoring-prometheus-0` is assigned to server node or worker nodes. 


<img width="1433" alt="Screen Shot 2020-09-08 at 10 58 45 AM" src="https://user-images.githubusercontent.com/6218999/92513734-a0fce100-f1c5-11ea-84a4-42af1925faf2.png">

<img width="1413" alt="Screen Shot 2020-09-08 at 11 03 53 AM" src="https://user-images.githubusercontent.com/6218999/92513738-a22e0e00-f1c5-11ea-8671-283c4e0a78e9.png">

**Comment by aiyengar2** [comment]
#### Summary of investigation
It seems like k3s is sending additional metrics that are already scraped from kube-scheduler / kubelet / kube-apiserver / kube-proxy via kube-controller-manager.

This is based off of comparing the scraped metrics from kube-controller-manager (port 10252) on a k3s cluster running monitoring v2 and a RKE1 cluster running monitoring v2

```bash
$ wc -l k3s/* rke/*                                 
   23408 k3s/kube_total_metrics_10249
   23408 k3s/kube_total_metrics_10251
   23408 k3s/kube_total_metrics_10252
   257 k3s/kube_uniq_metrics_10249
   257 k3s/kube_uniq_metrics_10251
   257 k3s/kube_uniq_metrics_10252
   23408 rke/kube_total_metrics_10249
   23408 rke/kube_total_metrics_10251
   1810 rke/kube_total_metrics_10252
   257 rke/kube_uniq_metrics_10249
   257 rke/kube_uniq_metrics_10251
   135 rke/kube_uniq_metrics_10252
```
From what we see here, it seems like k3s the 122 extra types of series that are being sent to kube-controller-manager are resulting in 21,598 extra metrics being scraped.

#### Parity for Metrics

##### Metrics that are unique to K3s Controller Manager
> aggregator_openapi_v2_regeneration_count
> aggregator_openapi_v2_regeneration_duration
> aggregator_unavailable_apiservice
> apiextensions_openapi_v2_regeneration_count
> apiserver_admission_controller_admission_duration_seconds_bucket
> apiserver_admission_controller_admission_duration_seconds_count
> apiserver_admission_controller_admission_duration_seconds_sum
> apiserver_admission_step_admission_duration_seconds_bucket
> apiserver_admission_step_admission_duration_seconds_count
> apiserver_admission_step_admission_duration_seconds_sum
> apiserver_admission_step_admission_duration_seconds_summary
> apiserver_admission_step_admission_duration_seconds_summary_count
> apiserver_admission_step_admission_duration_seconds_summary_sum
> apiserver_admission_webhook_admission_duration_seconds_bucket
> apiserver_admission_webhook_admission_duration_seconds_count
> apiserver_admission_webhook_admission_duration_seconds_sum
> apiserver_current_inflight_requests
> apiserver_init_events_total
> apiserver_longrunning_gauge
> apiserver_registered_watchers
> apiserver_request_duration_seconds_bucket
> apiserver_request_duration_seconds_count
> apiserver_request_duration_seconds_sum
> apiserver_request_terminations_total
> apiserver_request_total
> apiserver_response_sizes_bucket
> apiserver_response_sizes_count
> apiserver_response_sizes_sum
> apiserver_watch_events_sizes_bucket
> apiserver_watch_events_sizes_count
> apiserver_watch_events_sizes_sum
> apiserver_watch_events_total
> authentication_token_cache_active_fetch_count
> authentication_token_cache_fetch_total
> authentication_token_cache_request_duration_seconds_bucket
> authentication_token_cache_request_duration_seconds_count
> authentication_token_cache_request_duration_seconds_sum
> authentication_token_cache_request_total
> etcd_object_counts
> etcd_request_duration_seconds_bucket
> etcd_request_duration_seconds_count
> etcd_request_duration_seconds_sum
> grpc_client_handled_total
> grpc_client_msg_received_total
> grpc_client_msg_sent_total
> grpc_client_started_total
> kubelet_cgroup_manager_duration_seconds_bucket
> kubelet_cgroup_manager_duration_seconds_count
> kubelet_cgroup_manager_duration_seconds_sum
> kubelet_container_log_filesystem_used_bytes
> kubelet_containers_per_pod_count_bucket
> kubelet_containers_per_pod_count_count
> kubelet_containers_per_pod_count_sum
> kubelet_http_inflight_requests
> kubelet_http_requests_duration_seconds_bucket
> kubelet_http_requests_duration_seconds_count
> kubelet_http_requests_duration_seconds_sum
> kubelet_http_requests_total
> kubelet_node_config_error
> kubelet_node_name
> kubelet_pleg_discard_events
> kubelet_pleg_last_seen_seconds
> kubelet_pleg_relist_duration_seconds_bucket
> kubelet_pleg_relist_duration_seconds_count
> kubelet_pleg_relist_duration_seconds_sum
> kubelet_pleg_relist_interval_seconds_bucket
> kubelet_pleg_relist_interval_seconds_count
> kubelet_pleg_relist_interval_seconds_sum
> kubelet_pod_start_duration_seconds_bucket
> kubelet_pod_start_duration_seconds_count
> kubelet_pod_start_duration_seconds_sum
> kubelet_pod_worker_duration_seconds_bucket
> kubelet_pod_worker_duration_seconds_count
> kubelet_pod_worker_duration_seconds_sum
> kubelet_pod_worker_start_duration_seconds_bucket
> kubelet_pod_worker_start_duration_seconds_count
> kubelet_pod_worker_start_duration_seconds_sum
> kubelet_run_podsandbox_duration_seconds_bucket
> kubelet_run_podsandbox_duration_seconds_count
> kubelet_run_podsandbox_duration_seconds_sum
> kubelet_running_container_count
> kubelet_running_pod_count
> kubelet_runtime_operations_duration_seconds_bucket
> kubelet_runtime_operations_duration_seconds_count
> kubelet_runtime_operations_duration_seconds_sum
> kubelet_runtime_operations_total
> kubeproxy_network_programming_duration_seconds_bucket
> kubeproxy_network_programming_duration_seconds_count
> kubeproxy_network_programming_duration_seconds_sum
> kubeproxy_sync_proxy_rules_duration_seconds_bucket
> kubeproxy_sync_proxy_rules_duration_seconds_count
> kubeproxy_sync_proxy_rules_duration_seconds_sum
> kubeproxy_sync_proxy_rules_endpoint_changes_pending
> kubeproxy_sync_proxy_rules_endpoint_changes_total
> kubeproxy_sync_proxy_rules_iptables_restore_failures_total
> kubeproxy_sync_proxy_rules_last_timestamp_seconds
> kubeproxy_sync_proxy_rules_service_changes_pending
> kubeproxy_sync_proxy_rules_service_changes_total
> scheduler_binding_duration_seconds_bucket
> scheduler_binding_duration_seconds_count
> scheduler_binding_duration_seconds_sum
> scheduler_e2e_scheduling_duration_seconds_bucket
> scheduler_e2e_scheduling_duration_seconds_count
> scheduler_e2e_scheduling_duration_seconds_sum
> scheduler_framework_extension_point_duration_seconds_bucket
> scheduler_framework_extension_point_duration_seconds_count
> scheduler_framework_extension_point_duration_seconds_sum
> scheduler_pending_pods
> scheduler_plugin_execution_duration_seconds_bucket
> scheduler_plugin_execution_duration_seconds_count
> scheduler_plugin_execution_duration_seconds_sum
> scheduler_pod_preemption_victims_bucket
> scheduler_pod_preemption_victims_count
> scheduler_pod_preemption_victims_sum
> scheduler_pod_scheduling_attempts_bucket
> scheduler_pod_scheduling_attempts_count
> scheduler_pod_scheduling_attempts_sum
> scheduler_pod_scheduling_duration_seconds_bucket
> scheduler_pod_scheduling_duration_seconds_count
> scheduler_pod_scheduling_duration_seconds_sum
> scheduler_queue_incoming_pods_total
> scheduler_schedule_attempts_total
> scheduler_scheduler_cache_size
> scheduler_scheduler_goroutines
> scheduler_scheduling_algorithm_duration_seconds_bucket
> scheduler_scheduling_algorithm_duration_seconds_count
> scheduler_scheduling_algorithm_duration_seconds_sum
> scheduler_scheduling_algorithm_predicate_evaluation_seconds_bucket
> scheduler_scheduling_algorithm_predicate_evaluation_seconds_count
> scheduler_scheduling_algorithm_predicate_evaluation_seconds_sum
> scheduler_scheduling_algorithm_preemption_evaluation_seconds_bucket
> scheduler_scheduling_algorithm_preemption_evaluation_seconds_count
> scheduler_scheduling_algorithm_preemption_evaluation_seconds_sum
> scheduler_scheduling_algorithm_priority_evaluation_seconds_bucket
> scheduler_scheduling_algorithm_priority_evaluation_seconds_count
> scheduler_scheduling_algorithm_priority_evaluation_seconds_sum
> scheduler_scheduling_duration_seconds
> scheduler_scheduling_duration_seconds_count
> scheduler_scheduling_duration_seconds_sum
> scheduler_total_preemption_attempts
> scheduler_volume_scheduling_duration_seconds_bucket
> scheduler_volume_scheduling_duration_seconds_count
> scheduler_volume_scheduling_duration_seconds_sum
> ssh_tunnel_open_count
> ssh_tunnel_open_fail_count
> storage_operation_duration_seconds_bucket
> storage_operation_duration_seconds_count
> storage_operation_duration_seconds_sum
> storage_operation_status_count
> volume_manager_total_volumes

##### Metrics that are unique to RKE Controller Manager
> endpoint_slice_mirroring_controller_addresses_skipped_per_sync_bucket
> endpoint_slice_mirroring_controller_addresses_skipped_per_sync_count
> endpoint_slice_mirroring_controller_addresses_skipped_per_sync_sum
> endpoint_slice_mirroring_controller_changes
> endpoint_slice_mirroring_controller_desired_endpoint_slices
> endpoint_slice_mirroring_controller_endpoints_added_per_sync_bucket
> endpoint_slice_mirroring_controller_endpoints_added_per_sync_count
> endpoint_slice_mirroring_controller_endpoints_added_per_sync_sum
> endpoint_slice_mirroring_controller_endpoints_desired
> endpoint_slice_mirroring_controller_endpoints_removed_per_sync_bucket
> endpoint_slice_mirroring_controller_endpoints_removed_per_sync_count
> endpoint_slice_mirroring_controller_endpoints_removed_per_sync_sum
> endpoint_slice_mirroring_controller_endpoints_sync_duration_bucket
> endpoint_slice_mirroring_controller_endpoints_sync_duration_count
> endpoint_slice_mirroring_controller_endpoints_sync_duration_sum
> endpoint_slice_mirroring_controller_endpoints_updated_per_sync_bucket
> endpoint_slice_mirroring_controller_endpoints_updated_per_sync_count
> endpoint_slice_mirroring_controller_endpoints_updated_per_sync_sum
> endpoint_slice_mirroring_controller_num_endpoint_slices
> endpoint_slice_mirroring_controller_rate_limiter_use
> get_token_count
> get_token_fail_count
> leader_election_master_status
> node_ipam_controller_cidrset_allocation_tries_per_request_bucket
> node_ipam_controller_cidrset_allocation_tries_per_request_count
> node_ipam_controller_cidrset_allocation_tries_per_request_sum
> node_ipam_controller_cidrset_cidrs_allocations_total
> node_ipam_controller_cidrset_usage_cidrs

**Comment by aiyengar2** [comment]
Until https://github.com/rancher/k3s/issues/2262 is investigated / resolved, we can't make any definitive steps forward in changing the chart's behavior for monitoring k3s clusters.

Users who deploy Rancher Monitoring will need to specify a higher-than-default resource memory limit for Prometheus (i.e. recommended to set `prometheus.prometheusSpec.resources.memory.limit=2500Mi` and `prometheus.prometheusSpec.resources.memory.request=1750Mi`). This will be enforced as the default on the Rancher Dashboard UI as part of https://github.com/rancher/dashboard/issues/1230.

**Comment by david-nano** [comment]
So not sure why `scheduler_scheduling_algorithm_duration_seconds_count` isn't available?
