### ISSUE TITLE
[UI] when I use custom rancher/ui,  the resource is very big. 

### ISSUE THREAD

**Issue by PmcFizz** [rancher/rancher#28782]
**question:**
when I follow office step to deploy my custom `rancher/ui`。 I find the `vernder.js` is very big than use rancher image resource
this my custome ui  
![image](https://user-images.githubusercontent.com/13403284/92447309-a2d89b80-f1e9-11ea-8c09-5424a75d2c65.png)

and this result that I run rancher images

![image](https://user-images.githubusercontent.com/13403284/92447431-c7cd0e80-f1e9-11ea-9ade-b8f3a4fd5fbc.png)

what's  wrong ?   how to reduce the resource size ？

Thanks

@vincent99

**Comment by vincent99** [comment]
Probably your server isn't serving it gzipped.

**Comment by PmcFizz** [comment]
> Probably your server isn't serving it gzipped.

oh Thanks your replay。 I should ask devops start gizp。 
 I hava a question, I find the js don't hava hash suffix  after build。 but I use you offer way。I think between I build and you build hava difference. but I don‘t know  what's it 。
