### ISSUE TITLE
ports metadata field for LB services does not include protocol.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2878]
Server version - v0.47.0

Steps to reproduce the problem:
Create a LB service with http listener with source port - 901 and target port - 80 

ports metadata field for this LB services has values - ["901:80"] 
Should we include protocol as well ? When regular service has ports ,  ports metadata field includes protocol as well.

**Comment by alena1108** [comment]
@sangeethah "http" is implied for lb service when no protocol is specified (in both rancher-compose and API). So 100:100 implies http, and 100:100/tcp means tcp
