### ISSUE TITLE
Docs hyperlink opens page in the same window as rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28788]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a custom cluster.
- Navigate to cluster --> Tools --> CIS scan page
- `docs` hyperlink in `We've made big improvements to CIS in Cluster Explorer. See docs for details on what's new and how to migrate.` should open the page in a new tab/window.
- Currently it opens the page in the same window.

**Expected Result:**
`docs` hyperlink should open the page in a new tab/window.
<img width="1423" alt="Screen Shot 2020-09-08 at 11 14 18 AM" src="https://user-images.githubusercontent.com/26032343/92514063-2ed8cc00-f1c6-11ea-8666-760e54a3e5b1.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `76c26fb0`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.18
```

**Comment by deniseschannon** [comment]
Docs links have been fixed to open in new tabs as of v2.5

**Comment by sowmyav27** [comment]
Link to docs here opens in a new tab on 2.5-head - commit id: `2ae4cf117a`
<img width="1346" alt="Screen Shot 2021-01-31 at 12 31 52 PM" src="https://user-images.githubusercontent.com/26032343/106397083-81f32b80-63c0-11eb-9349-fc587cace23a.png">
