### ISSUE TITLE
[Logging v2] additionalLoggingSources is retrieving only latest log lines (tail)

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28796]
SURE-3538

**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- Install Rancher HA
- Provision a DO RKE cluster (one node)
- Deploy the logging-operator enabling one of the additionalLoggingSources (rke1, k3s, eks, rke2) to the DO cluster using helm
- With rke1 as example go the logs path in one of the nodes

**Result:**

Not getting all the logs collected from start of file (head)

Example

In this cluster these are the logs for `RemoveContainer` from the Kubelet logged events **3 Matches**

![Screen Shot 2020-09-08 at 3 48 47 PM](https://user-images.githubusercontent.com/27659/92534974-03b4a380-f1eb-11ea-8e14-09d50e4c720c.png)

But in reality only the last few lines of that kubelet log was collected because in the logs are 10 more `RemoveContainer` events that happened before the events logged in Elasticsearch.

```
/var/lib/rancher/rke/log# ls
etcd_0880501a8ff560760cc27cf9a4a8e10c8dabd07c06c23acc2e22de41a6f4ca33.log
kube-apiserver_2fcb780ea51a1744e080fedb5bc927280a3c239435963944b8eac3d97644a791.log
kube-controller-manager_5941855f6401f18cf33efe48aea073d5f5e1c390aeaeff781b3ca81b128d37e7.log
kube-proxy_f72d73eab6cf263fa4ee2b86bd061109d8210536e2443aa508f71e58b0b5a481.log
kube-scheduler_5b1fd036cb8839d5d4087ab9f9d1bc02a4f29daa59e77bfc715989b2faed28cc.log
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log
```

```
/var/lib/rancher/rke/log#  grep -Hn RemoveContainer *
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:822:{"log":"I0908 22:03:59.349152   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 58594a6943b3fc55d2ab83c89a9c70e51121db6dbd0592194915b86220260d45\n","stream":"stderr","time":"2020-09-08T22:03:59.350659376Z"}
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:865:{"log":"I0908 22:04:03.460798   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 808c58c1dff0a18c1287d218ec47bb815de4c95f26baf3203e0183b354bd7500\n","stream":"stderr","time":"2020-09-08T22:04:03.460850559Z"}
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:918:{"log":"I0908 22:04:08.541186   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: d43ca20d7c0ee5f2bb72ade65bcda5be45acd0295a091fc906cfe1e6711b06da\n","stream":"stderr","time":"2020-09-08T22:04:08.541279649Z"}
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:973:{"log":"I0908 22:04:13.630755   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: a02fad61eed43239528bf6de0dcc6ace35e203a02510ce0b83e8cdb1786712ce\n","stream":"stderr","time":"2020-09-08T22:04:13.632098373Z"}
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:1317:{"log":"I0908 22:07:57.236712   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 7e5acc4bf66be63084a545184e578655feb356929a9a9281aba21d7a074fc6bf\n","stream":"stderr","time":"2020-09-08T22:07:57.239209801Z"}
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:1376:{"log":"I0908 22:07:58.307063   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 6ffb12e31189ccbd2640af92f1dedef8e79f3813b495abe9b03b59c5bf00e68a\n","stream":"stderr","time":"2020-09-08T22:07:58.307208418Z"}
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:1461:{"log":"I0908 22:07:59.633243   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 7dd66bf31f96d01b435c824208c71d5a8c2bd2b148ed2e15c2dd193a23e81b61\n","stream":"stderr","time":"2020-09-08T22:07:59.634759075Z"}
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:1682:{"log":"I0908 22:11:18.396851   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: fd3d3733dd2a766cfd3d63022a180000e22dfcd3609192a83366d15153963268\n","stream":"stderr","time":"2020-09-08T22:11:18.397005011Z"}
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:1686:{"log":"I0908 22:11:18.427277   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 753297e032fca4b369794c9cbe08f773ef7dba78f0134658ff0f73ad4afa5b10\n","stream":"stderr","time":"2020-09-08T22:11:18.42798835Z"}
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:1721:{"log":"I0908 22:11:19.478651   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: cbd751eea539952742232110c8c2d350ef0bdc08ebfade3ec3b80ceb90713cc6\n","stream":"stderr","time":"2020-09-08T22:11:19.478704143Z"}
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:1753:{"log":"I0908 22:11:44.509739   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 6ffb12e31189ccbd2640af92f1dedef8e79f3813b495abe9b03b59c5bf00e68a\n","stream":"stderr","time":"2020-09-08T22:11:44.509924507Z"}
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:1754:{"log":"I0908 22:11:44.533725   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 7e5acc4bf66be63084a545184e578655feb356929a9a9281aba21d7a074fc6bf\n","stream":"stderr","time":"2020-09-08T22:11:44.53393341Z"}
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log:1755:{"log":"I0908 22:11:44.557081   20312 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 7dd66bf31f96d01b435c824208c71d5a8c2bd2b148ed2e15c2dd193a23e81b61\n","stream":"stderr","time":"2020-09-08T22:11:44.557634186Z"}
```

```
grep -Hn RemoveContainer * | wc -l
13
```

**Other details that may be helpful:**

```
helm install rancher-logging-crd https://charts.rancher.io/assets/rancher-logging/rancher-logging-crd-3.4.000.tgz --create-namespace=true --namespace=cattle-logging-system
helm install --create-namespace=true --namespace=cattle-logging-system rancher-logging -f values.yaml https://charts.rancher.io/assets/rancher-logging/rancher-logging-3.4.000.tgz
```

values.yaml
```yaml
disablePvc: true
additionalLoggingSources:
  rke1:
    enabled: true
  rke2:
    enabled: false
  k3s:
    enabled: false
    container_engine: "systemd" # openrc or systemd
  eks:
    enabled: false
images:
  config_reloader:
    repository: rancher/jimmidyson-configmap-reload
    tag: v0.2.2
  fluentbit:
    repository: rancher/fluent-fluent-bit
    tag: 1.5.0
  fluentd:
    repository: rancher/banzaicloud-fluentd
    tag: v1.10.4-alpine-2
  syslog_forwarder:
    repository: rancher/fluent-bit-out-syslog
    tag: 0.1.0
global:
  systemDefaultRegistry: ""

```

**Environment information**
- Rancher version: `master-head (09/08/2020)` _4fbd822ce_
- Installation option: HA k8s

**Cluster information**
- Cluster type: Infrastructure provider DO RKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 8GB RAM
- Kubernetes version:  v1.18.6

**Comment by paynejacob** [comment]
I am unable to reproduce this issue.  I edited the kubelet log before installing logging.  Then installed logging and configured a cluster flow and output provided by @izaac.  After around 5m I was able to search the result from the head of the kubelet log.  There was a significant delay in getting the log.

`
root@jpayne-master1:/var/lib/rancher/rke/log# head kubelet_b1a5a47ab3fc6fd87fea6b7373fc9f08befe4d18970fdf3201a895cc9d11b716.log 
{"log": "FINDMEJPAYNEEXAMPLE FINDME findme","stream":"stderr","time":"2020-09-10T22:07:27.648077806Z"}
{"log":"+ grep -q cloud-provider=azure\n","stream":"stderr","time":"2020-09-10T22:07:27.648077806Z"}
`



`
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 18.08647,
    "hits" : [
      {
        "_index" : "rke1logtest1",
        "_type" : "_doc",
        "_id" : "hDteenQBfNX2bqiu4L1m",
        "_score" : 18.08647,
        "_source" : {
          "log" : "FINDMEJPAYNEEXAMPLE FINDME findme",
          "stream" : "stderr",
          "time" : "2020-09-10T22:07:27.648077806Z",
          "kubernetes" : {
            "pod_name" : "nsenter-wl9ipz",
            "namespace_name" : "default",
            "pod_id" : "933d1ffd-4276-4b93-89a9-d8c0ae55de4c",
            "labels" : {
              "run" : "nsenter-wl9ipz"
            },
            "host" : "jpayne-master1",
            "container_name" : "nsenter",
            "docker_id" : "eeddf99334428dae7646a33c2e5498625b6b3c0e5d1803af788363c39a0950b6",
            "container_hash" : "alpine@sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321",
            "container_image" : "alpine:latest"
          }
        }
      }
    ]
  }
}`

**Comment by izaac** [comment]
I will do another round with latest, this has been inconsistent however not all files in the log path are getting collected from `head`. It requires a bit more analysis to cover each file but I do see missing logs in the Output.

In the meantime could you try this, go the the log path in the node (make one node cluster, all roles) and check the files are there. 


`/var/lib/rancher/rke/log# ls`

_(sample filenames)_
```
etcd_0880501a8ff560760cc27cf9a4a8e10c8dabd07c06c23acc2e22de41a6f4ca33.log
kube-apiserver_2fcb780ea51a1744e080fedb5bc927280a3c239435963944b8eac3d97644a791.log
kube-controller-manager_5941855f6401f18cf33efe48aea073d5f5e1c390aeaeff781b3ca81b128d37e7.log
kube-proxy_f72d73eab6cf263fa4ee2b86bd061109d8210536e2443aa508f71e58b0b5a481.log
kube-scheduler_5b1fd036cb8839d5d4087ab9f9d1bc02a4f29daa59e77bfc715989b2faed28cc.log
kubelet_5961b7e98ca3fe465f793b0ca724ced1d60dad73404b2270feddeeddfb62ab4c.log
```


After 5 minutes of collected logs stored in the Output check **each** log file in the filesystem, head or first 50 lines, try to look for matches in the output for each.

**Comment by paynejacob** [comment]
I was able to reproduce this:

1. Create do cluster running rke with 1 node.

2. exec into the node with node_shell

3. add the following line to the top of each file in /var/lib/rancher/rke/log `{"log": "<filename> findme", "stream":"stderr", "time": "2020-09-11T22:42:04.879103858Z"}`

4. Install the helm chart:
- helm install rancher-logging-crd https://charts.rancher.io/assets/rancher-logging/rancher-logging-crd-3.4.000.tgz --create-namespace=true --namespace=cattle-logging-system
- helm install --create-namespace=true --namespace=cattle-logging-system rancher-logging --set additionalLoggingSources.rke1.enabled=true https://charts.rancher.io/assets/rancher-logging/rancher-logging-3.4.000.tgz

5. Create a cluster flow and output
- kubectl apply -f flow.yaml
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: es-output-sample
  namespace: cattle-logging-system
spec:
  elasticsearch:
    host: jpayne.do.rancher.space
    port: 7200
    scheme: http
    ssl_verify: false
    ssl_version: TLSv1_2
    index_name: rke1logtest1
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: flow-sample
  namespace: cattle-logging-system
spec:
  filters:
    - tag_normaliser: {}
  outputRefs:
    - es-output-sample
```

6. navigate to http://jpayne.do.rancher.space:7200/rke1logtest1/_search?pretty&q=findme

**Comment by paynejacob** [comment]
I will leave it run over the weekend to see if they get picked up

**Comment by paynejacob** [comment]
I have been able to reproduce logging sometimes not picking up logs with the following steps.  I proved that the logs are not leaving fluentbit by adding the stdout filter to fluentd.  below is the script I used to test this.

[head.sh.txt](https://zube.io/files/rancher/d3a9a03e4144e577deb0191819d23d2e-head-sh.txt)[head.yml.txt](https://zube.io/files/rancher/8dfd6369cdcae2f1739b98011bff463f-head-yml.txt)

before running the install script open a shell on the node and run `sudo curl -L https://raw.githubusercontent.com/paynejacob/sequential-log-generator/master/example.sh | sh`

once this script starts run the head.sh above. 

once all the logging pods are up https://jpayne.do.rancher.space:7200/examplelogs/_search?pretty should return 3k+ log entries.

all of this was tested on a single node rke do cluster.

**Comment by deniseschannon** [comment]
This is an issue within Banzai Operator. @izaac Can you open an issue on their side and link to this issue?

**Comment by izaac** [comment]
https://github.com/banzaicloud/logging-operator/issues/582

**Comment by izaac** [comment]
I am observing this issue with GKE and AKS kubelet logs. I added a comment to the upstream issue.

**Comment by nickgerace** [comment]
@paynejacob we might be able to patch this on our side. Would have to take a look... thoughts?
https://github.com/banzaicloud/logging-operator/issues/582#issuecomment-816572973

**Comment by paynejacob** [comment]
In the cases where we run our own fluentbit pod this is already the case.  By default the tail input reads all logs in the file.  In the case of GKE and AKS the issue is with log rotation running before rancher logging is set up.  We do not have a way to read compressed logs.  In the cases where we use the systemd input we could change some settings to collect more logs but this is currently limited to due to preformance considerations.  We would need to better understand those implications before moving forward.

**Comment by deniseschannon** [comment]
Moved from 2.5 line to review for triage for 2.6

**Comment by SheilaghM** [comment]
This is working as designed. The filters they have by default don't handle our information.

The fluentbit under the logging operator is not designed to process non kubernetes logs. The issue can be that these log lines are processed by the kubernetes filter which cannot attach metadata information to them, or at least fails in some cases. The workaround is to create a fully separate daemonset with a custom fluentbit config to process those logs, send them to stdout and then the logging operator can handle them as usual container logs.

In the cases where we run our own fluentbit pod this is already the case. By default the tail input reads all logs in the file. In the case of GKE and AKS the issue is with log rotation running before rancher logging is set up. We do not have a way to read compressed logs. We limit the logs we collect due to performance considerations. We would need to better understand those implications before moving forward.
