### ISSUE TITLE
[request] [ui] Stack progress

### ISSUE THREAD

**Issue by themotu** [rancher/rancher#2880]
when starting a stack having some sort of indication of what's going on with deployment would be good. (1/4) services deployed, (downloading/starting on example2)

something of that nature.

![suggestion](https://cloud.githubusercontent.com/assets/9060082/11543004/2bc744ae-98ef-11e5-9284-c07b11f9791a.png)

**Comment by will-chan** [comment]
Closing this as we are working on a 2.0 UI.
