### ISSUE TITLE
[RFE] Support OIDC authentication in addition to SAML

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28804]
Rancher OIDC Requirements

**Support OIDC authentication in addition to SAML**.

- Implementation can match existing SAML workflow as an MVP.
- Utilize OIDC response to determine all available groups of admin user, then define a list of those groups that can be mapped to Rancher roles. 

**Support CRD method of group/role management.**

- Can be based off of ArgoCD's model, using CRDs to define Group/Role permissions.
- Instead of determining groups through an OIDC response, the groups can be predefined in CRs that get compared to OIDC responses to determine access.

**Separate authentication and authorization to be able to support OIDC/Keycloak authentication with LDAP authorization.**

- Should allow Rancher to define groups in LDAP and sync with Rancher.
- Should use OIDC as pure authentication, not utilize OIDC groups for authorization.
- Should compare OIDC response username/DN against LDAP-synced users/groups for authorization.
- Still should support CRD methodology.

**Comment by maggieliu** [comment]
Closed. Will create a new issue when the PRD is available for supporting keycloak using OIDC

**Comment by wzrdtales** [comment]
no one wants keycloak, really... it's a mess

**Comment by wzrdtales** [comment]
https://github.com/coreos/go-oidc
