### ISSUE TITLE
k8s为1.18.8时异常告警

### ISSUE THREAD

**Issue by 15051863961** [rancher/rancher#28802]
![1599612610(1)](https://user-images.githubusercontent.com/62975132/92541807-a9165880-f279-11ea-8528-0d732bc11f26.png)
环境：redhat7.5
docker:19.03.12
k8s:1.18.8
rancher:2.4.5-2.4.8
rancher会一直提示：警告: 组件 controller-manager 不健康
警告: 组件 scheduler 不健康
但是不影响使用，希望能够解决一下。

**Comment by lynk-coder** [comment]
/etc/kubernetes/manifests/scheduler.conf

**Comment by lynk-coder** [comment]
/etc/kubernetes/manifests/controller-manager.conf
/etc/kubernetes/manifests/scheduler.conf
这两个文件里面，删除--port=0这个配置
然后systemctl restart kubelet

**Comment by 15051863961** [comment]
好的，谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lynk"<notifications@github.com&gt;; 
发送时间: 2020年9月10日(星期四) 下午4:59
收件人: "rancher/rancher"<rancher@noreply.github.com&gt;; 
抄送: "Thinking"<201840026@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rancher/rancher] k8s为1.18.8时异常告警 (#28802)





 
/etc/kubernetes/manifests/controller-manager.conf
 /etc/kubernetes/manifests/scheduler.conf
 这两个文件里面，删除--port=0这个配置
 然后systemctl restart kubelet

**Comment by lynk-coder** [comment]
get cs在1.19被作废了。目前版本的rancher都是用get cs获取状态的  后续估计会更改

**Comment by 15051863961** [comment]
好的，我说怎么之前跨大版本都可以，这次一个小版本都不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lynk"<notifications@github.com&gt;; 
发送时间: 2020年9月11日(星期五) 中午11:02
收件人: "rancher/rancher"<rancher@noreply.github.com&gt;; 
抄送: "Thinking"<201840026@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rancher/rancher] k8s为1.18.8时异常告警 (#28802)





 
get cs在1.19被作废了。目前版本的rancher都是用get cs获取状态的  后续估计会更改

**Comment by lynk-coder** [comment]
1.18.6机制做了调整了。

**Comment by arthurlogilab** [comment]
According to google translate we hit the same bug, and @lynk-coder 's suggestion fixed it. Thanks ! 

Maybe an issue in english could be done so that other rancher users can find this information ?

**Comment by lucernae** [comment]
Encountered the same problem. For english readers, use this google translate link:

https://github.com/rancher/rancher/issues/28802

**Comment by aladdinwang** [comment]
> 好的，谢谢啦
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lynk"<notifications@github.com&gt;; 发送时间: 2020年9月10日(星期四) 下午4:59 收件人: "rancher/rancher"<rancher@noreply.github.com&gt;; 抄送: "Thinking"<201840026@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [rancher/rancher] k8s为1.18.8时异常告警 (#28802) /etc/kubernetes/manifests/controller-manager.conf /etc/kubernetes/manifests/scheduler.conf 这两个文件里面，删除--port=0这个配置 然后systemctl restart kubelet — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> /etc/kubernetes/manifests/controller-manager.conf
> /etc/kubernetes/manifests/scheduler.conf
> 这两个文件里面，删除--port=0这个配置
> 然后systemctl restart kubelet

docker安装rancher的话，这两个文件在哪里？
