### ISSUE TITLE
[feature] Launch template support

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#28803]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement/bug

**Description:**
1. Add launch templates field to EKS Cluster Config spec.
2. If field is nil on upstreamSpec hide it.
3. Launch template can only be updated if nodegroup was created with one.
4. Nodegroup must not contain node size or instance type if custom launch template is not nil.
5. *Possibly write fields from launch template to upstreamSpec so they can be displayed.

Add field for launch template, cannot create cluster with it or update it, only for imported clusters

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `dba332111` and master-head - commit id: `9ef8e69d`**

- Launch Template support has been validated.
- All related issues have been logged and are tracked separately

**Comment by aaronRancher** [comment]
Verified with Rancher server `rancher\rancher:master-head` `version d7203b4` and `rancher\rancher:v2.5-head` `version 05fbcbb`

Validated Launch Template Support.
Validated Launch Template syncing:
https://github.com/rancher/rancher/issues/30021

Related issues are tracked separately.
