### ISSUE TITLE
User is not able to list charts/apps/repos in Dashboard and error seen in console/request

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28816]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a master-head rancher in a HA setup. 
- Navigate to Dashboard --> Apps
- Charts/Apps/Repos are not listed.
<img width="1085" alt="Screen Shot 2020-09-09 at 1 46 41 PM" src="https://user-images.githubusercontent.com/26032343/92653244-ec38f180-f2a2-11ea-9fe1-2cab3e6f222c.png">

- Request sent while loading the page: `https://<rancher-server>/v1/catalog.cattle.io.clusterrepos/rancher-partner-charts?link=index`
- Response:
`{"type":"error","links":{},"code":"ServerError","message":"converting (url.Values) to (v1.GetOptions): unknown conversion","status":500,"type":"error"}`

**Expected Result:**
User should be able to list Charts/Apps/Repos on dashboard

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `4ff98cc6`
- Installation option (single install/HA): HA

**Comment by izaac** [comment]
I am getting the charts in Rancher version: `master-head (09/09/2020)` _4ff98cc603ea47528062ee6994d2a5e58a29ed5a_
 - HA k8s
 - Single Docker install


The last commit I have this working is `master-head (09/08/2020)` _ f7f8e8bb0649e6f163bd6ba2118622a9889236ce_

**Comment by sowmyav27** [comment]
**On master-head - commit id: `c63f8fda`**

- User is able to list Apps/repos.
- No error is seen.
