### ISSUE TITLE
Remove k8s 1.15 in Rancher 2.5

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28828]
Update KDM to remove k8s 1.15. User should no longer be able to provision k8s 1.15 clusters.

**Comment by soumyalj** [comment]
Tested with master-head(master-bcc8261487ecdd37761fc7a010950e4cffd40874-head)

Verified K8s version v1.15 is not displayed for users. 
![Screen Shot 2020-09-17 at 3 48 21 PM](https://user-images.githubusercontent.com/18536626/93536210-5aae2d00-f8fd-11ea-9669-88375ce96caa.png)
