### ISSUE TITLE
Error while applying agent YAML, it will be retried automatically

### ISSUE THREAD

**Issue by likeabook** [rancher/rancher#28827]
![1599716491(1)](https://user-images.githubusercontent.com/5488621/92686007-68970780-f36b-11ea-96ac-aa368fd98875.jpg)

The newly created cluster can use other functions except PV. What is the reason for this problem?

Error while applying agent YAML, it will be retried automatically: exit status 1, clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver unchanged clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master unchanged namespace/cattle-system unchanged serviceaccount/cattle unchanged clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged secret/cattle-credentials-bc430b7 unchanged clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged deployment.apps/cattle-cluster-agent unchanged daemonset.apps/cattle-node-agent unchanged daemonset.apps/kube-api-auth unchanged Error from server (BadRequest): error when creating "management-statefile_path_redacted": Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 25, error found in #10 byte of ...\|xMjM0In0="},"kind":"\|..., bigger context ...\|3peS4muaZuuiDvSIsInBhc3N3b3JkIjoiQWJjZC4xMjM0In0="},"kind":"Secret","metadata":{"annotations":{"kube\|...

**Comment by likeabook** [comment]
解决办法，将集群的网络改为 flannel 模式。
如果不成功就将 rancher 卸载再重装。

**Comment by janeczku** [comment]
Thanks for the report. We are already tracking it here: https://github.com/rancher/rancher/issues/28768
