### ISSUE TITLE
[Monitoring V2] Rebase to new upstream repo

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#28822]
Upstream Prometheus operator has been changed to [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) and is located in a new repository. We need to rebase the `rancher-monitoring` chart to reflect the latest changes in the Helm chart in upstream before release and also track any future changes from the right upstream branch.

**Comment by aiyengar2** [comment]
#### Note to QA:

This will also contain an update to images, so we'll need to test whether the images specified in the chart after merge exist.

Related to https://github.com/rancher/image-mirror/pull/35

**Comment by jiaqiluo** [comment]
here is the list of expected images 
```
grafana/grafana rancher/grafana-grafana 7.1.5
prom/prometheus rancher/prom-prometheus v2.18.2
prom/alertmanager rancher/prom-alertmanager v0.21.0
prom/node-exporter rancher/prom-node-exporter v1.0.1
```

**Comment by jiaqiluo** [comment]
This issue is validated on `master-8fd81a9b46847317a95ab654ae58053787d57687-head`

the kube-prometheus-stack chart is used, and the above-mentioned images are used.
