### ISSUE TITLE
"Cluster health check failed: cluster agent is not ready" error seen during cluster provisioning after which it proceeds to succeed.

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28836]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a 3 nodes custom cluster - 1 etcd, 1 control and 1 worker nodes
- sometimes the cluster is seen in an error state `Cluster health check failed: cluster agent is not ready` after it has finished provisioning. Nodes will be seen Active in this case. But the cluster is seen in an error state.
- After about2 to 3 minutes (approx) the cluster comes to Active state.
- Seen happening quite often on master-head but NOT everytime.

<img width="1447" alt="Screen Shot 2020-09-09 at 4 23 55 PM" src="https://user-images.githubusercontent.com/26032343/92746891-826b2700-f338-11ea-8e24-bd4f00e96a17.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - `c63f8fda`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom cluster
- Kubernetes version (use `kubectl version`):

```
1.18
```

**Comment by dramich** [comment]
This is not unexpected behavior when first setting up a cluster. When doing a custom cluster this will just run the base agent image to get it connected into rancher. After the cluster connects rancher will determine if the current agent has all the required features/settings/etc. and if not will redeploy the agent with the desired configuration. Trace logging can be enabled and the difference between the configs can be viewed to see what rancher is changing in the config for the agent.

**Comment by sowmyav27** [comment]
@dramich This issue seems to be happening recently on master and happens quite often. This was not seen before. Reopening the issue to see why would that be the case.

**Comment by dramich** [comment]
https://github.com/rancher/rancher/commit/01490ab3a78180692e7cb6e23aef8f35efe030c5
It is a newer change which is an additional check to the cluster health sync process. If the agent deployment is not ready the check fails and we try again in ~15 seconds. See previous comment for why the agent is deployed twice.

**Comment by sowmyav27** [comment]
Closing the issue based on comments https://github.com/rancher/rancher/issues/28836#issuecomment-694939845 and https://github.com/rancher/rancher/issues/28836#issuecomment-694437028

**Comment by slash1387** [comment]
@sowmyav27 please re-open

1. fresh install
```
docker run -d --restart=unless-stopped --name=rancher2.5.1 -p 80:80 -p 443:443 --privileged rancher/rancher:v2.5.1
```
2. Global -> Add Cluster -> Existing Nodes -> Choose all 3 roles (etcd, worker, control-plane)
3. exec docker run on 2 or 1 nodes, they register and start to setup...
```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.5.1 --server https://10.3.2.19 --token slrznggf27dbr42tfpwxqfzldkjwbbrrhjft4bpn67p289f7hftz9n --ca-checksum 52cfb3fb1446db991cb01d707e254b0f13048a40e2416d5a9c1facfa66699587 --etcd --controlplane --worker
```
3. wait...it will stop with ERROR: Cluster health check failed: cluster agent is not ready
![image](https://user-images.githubusercontent.com/66519368/95628552-919bdc80-0a7e-11eb-8fc1-4f72f7e2cd88.png)

not working!

**Comment by yceoshda** [comment]
I have the same kind of issue when provisionning a new custom cluster. I guess since I had the problem described here https://github.com/rancher/rancher/issues/16454 It's the same kind of issue (cluster's DNS cannot resolv my Rancher's hostname since it's not public). The added trouble being that unlike in 2.4.8 where I could edit the cattle-cluster-agent deployment to change the dnsConfig ... this time I can't ... rendering the provisionned cluster useless.

**Comment by kwims** [comment]
Same issue here for the newer version 2.5.1. worked find for version 2.4.8

**Comment by sowmyav27** [comment]
@slash1387 Did the cluster recover after the error ? Because this error mentioned in the original issue was an intermittent error (always reproducible and cluster would recover after about 5 minutes). If the error persisted, you could log a new issue to track it.

**Comment by kwims** [comment]
@sowmyav27  like I said I got the exact same problem and after several hour ( like 6h) It still did not recover. So in my oppinion the bug reported by @slash1387  still exists

**Comment by sowmyav27** [comment]
@kwims The error mentioned in the original issue was an intermittent error (always reproducible and cluster would recover after about 5 minutes). If the error persisted, could you please log a new issue to track it.

**Comment by slash1387** [comment]
@sowmyav27 the cluster did not recover. I wiped my nodes clean and disabled firewalld and then it worked. There must be some new kind of dns port requirement which previous versions did not have!

**Comment by pasinsjr** [comment]
have the same problem here I tested with version 2.4.8 like @kwims said, it works fine. one thing that my setup may different is I didn't use DNS on the node that joined custom cluster (I added domain directly to the hosts file of node)

**Comment by Himansh-ilink** [comment]
i have tested with 2.4.8. It is working fine, but with rancher 2.5.0 & 2.5.1 getting below error.
"This cluster is currently Error; areas that interact directly with it will not be available until the API is ready.
Cluster health check failed: cluster agent is not ready". Can someone from  @rancher team please look this issue.

**Comment by kachar** [comment]
I'm experiencing the problem as well with a EKS cluster created by Rancher 2.5.1

It looks like the cluster endpoint provided by AWS has invalid SSL certificate and doing a curl request to it gives the following:

```shell
$ curl https://D5296A.....F34A.gr7.eu-central-1.eks.amazonaws.com -v
*   Trying 18.157.153.109:443...
* TCP_NODELAY set
* Connected to D5296A.....F34A.gr7.eu-central-1.eks.amazonaws.com (18.157.153.109) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
```

Rancher error:

```
This cluster is currently Error; areas that interact directly with it will not be available until the API is ready.

Cluster health check failed: cluster agent is not ready
```


I can only assume that rancher displays the error because it can't connect to the api endpoint.

**Comment by maggieliu** [comment]
Reopening to see if there is anyway to improve this.

**Comment by Ranczo** [comment]
I'm having the same problem on a bare-metal single node installation with Rancher v2.5.1.

**Comment by gumutianqi** [comment]
I also have the same issue.
![image](https://user-images.githubusercontent.com/1057589/97855431-b14cba80-1d35-11eb-975b-615594104af1.png)

**Comment by tuxpeople** [comment]
+1 for having this problem with Bare Metal on Rancher 2.5.1

**Comment by superseb** [comment]
This issue describes the **temporary** message that is shown while the cluster agent becomes Ready. After that, the message goes away. If your message does not go away after a few minutes, this is a different issue and, after searching for existing issues, you can create a new issue for this as it is a different situation.

**Comment by deniseschannon** [comment]
As this is a transient messgae, this is expected.

**Comment by sowmyav27** [comment]
After an offline conversation with @deniseschannon , changing it to 2.5.7 for it to be looked at

**Comment by janeczku** [comment]
An average user seeing this error lasting for more than a minute would not interpret this as a transient message but rather assume that the cluster provisioning has failed.

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/issues/30427

**Comment by sowmyav27** [comment]
2.5 PR: https://github.com/rancher/rancher/pull/31039

**Comment by jiaqiluo** [comment]
The bug fix is validated on the following two rancher versions:
- rancher/rancher:`v2.5-head` 2ae4c
- rancher/rancher:`master-head `d160b

Steps:
- run rancher single-install
- provision a clsuer with EC2 node-driver, the cluster contains 1 etcd, 1 control plan, and 3 workers 
- Monitor the changes of the cluster's state during the whole provisioning process 

Results:
- the state or cluster never become `Error`
- the following error never show up: `Cluster health check failed: cluster agent is not ready` 
- the cluster is provisioned successfully
