### ISSUE TITLE
enhancement: Offer Chart Options when performing CIS Scans

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#28833]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
When performing as CIS scan the scan is installed as a helm chart via System Charts

This is an issue for customers who use different registries in different clusters as the downstream cluster is not always guaranteed to have access to the Global Default Registry which is where the System Charts will attempt to deploy form by default (thereby failing) (https://github.com/rancher/system-charts/blob/dev-v2.4/charts/rancher-cis-benchmark/0.1.2/values.yaml#L76)

I believe a sensible solution would be to expose the chart options where allow global.systemDefaultRegistry to be set so this limitation can be avoided

-however-

The main issue here is the lack of an option to change the registry from which CIS Scans pull and run; if exposing the chart options is not viable in fixing this then I am open to other suggestions

**Result:**
We give customers the freedom to run their cis-scans in environments that would be considered secure and segregated under normal circumstances

**Other details that may be helpful:**
Rancher Version 2.4.5

gzrancher/rancher#11158

**Comment by sowmyav27** [comment]
On `2.5.0-rc2`

- Global - system default registry --> no value set
- Private registry set at the cluster
- Deploy CIS v2 app
- The images for the app are pulled from the default global registry and NOT the cluster level private registry

Reopening the issue.

**Comment by deniseschannon** [comment]
With v2 and how the operator works, isn't this a completely different ask than what you're testing @sowmyav27 

Don't we just need to be able to configure where the operator image is located, which is an option in the helm chart? It has nothing to do with the system default registry. You can just change where/how we deploy the cis-operator image to use a specific image located in your private registry.

Isn't this solved with CIS v2?

**Comment by sangeethah** [comment]
Related issue - https://github.com/rancher/dashboard/issues/1554

**Comment by sowmyav27** [comment]
**On master-head - commit id: `cb9e8a105c1f`**

**Scenario#1**
- Set Global default registry to `reg1` and cluster level to `reg2`
- While deploying CIS v2 app, set this in the values.yaml

```
cattle:
        clusterId: c-bq9ds
        clusterName: custom-2
        systemDefaultRegistry: reg2
```
- CIS v2 app is seen deployed using images from reg2

**Scenario#2**
- Do not set Global default registry and set cluster level to `reg2`
- While deploying CIS v2 app, set this in the values.yaml

```
cattle:
        clusterId: c-bq9ds
        clusterName: custom-2
        systemDefaultRegistry: reg2
```
- CIS v2 app is seen deployed using images from reg2
