### ISSUE TITLE
  Alert: Component controller-manager is unhealthy.

### ISSUE THREAD

**Issue by tzachish1** [rancher/rancher#28835]
when importing from existing cluster [version 1.19.1 Rancher is unable to determine the status of Controller manager and Scheduler 

1. create a K8 on version 1.19
2. import existing cluster to Rancher

**Result:**
Recieving 2 alerts :
Alert: Component controller-manager is unhealthy.
Alert: Component scheduler is unhealthy.

**Other details that may be helpful:**
v1 ComponentStatus is deprecated in v1.19+
https://github.com/kubernetes/kubernetes/pull/93570

**Environment information**
- Rancher version 2.4.8
- Installation option (single install/HA): HA

**Comment by maggieliu** [comment]
Support for 1.19 will be available in Rancher 2.5
