### ISSUE TITLE
Support 1.17.12, 1.18.9, 1.19.2

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28838]
Support 1.17.12, 1.18.9, 1.19.2, which is targeted to release on 9/16

**Comment by soumyalj** [comment]
- Verified that K8s versions v1.17.12, v18.9, v1.19,2 and v1.16.15 are supported in master-head(2b260f05fc348dd)
- Automation runs succeeded
- It was also verified that ingress-controller version is updated to `rancher/nginx-ingress-controller:nginx-0.35.0-rancher1
` for clusters with all supported K8s versions

![Screen Shot 2020-09-18 at 6 21 57 PM](https://user-images.githubusercontent.com/18536626/93657173-18f8b180-f9e5-11ea-94d8-b9d718bb8d13.png)
