### ISSUE TITLE
[Logging v2] Update chart to support k8s providers constants for additionalLoggingSources

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28847]
**What kind of request is this:**
bug

**Steps to reproduce:**

Change the current values.yaml to accept constants instead of using rke1, rke2, etc keys as described here:

https://github.com/rancher/dashboard/issues/1109#issuecomment-690719309

**Result:**

- Issue observed is described here https://github.com/rancher/dashboard/issues/1109#issuecomment-690470086

**Other details that may be helpful:**

**Environment information**
- Rancher version: `master-head (09/10/2020)` _198ec5bdf52d3ed2b4865cfcf6ac1d61150bf55f_
- Installation option: k8s HA

**Comment by paynejacob** [comment]
https://github.com/rancher/charts/pull/638

**Comment by izaac** [comment]
Rancher version `master-head (09/17/2020)` _33f755f_

Validated the values.yml with the following cluster types:

- RKE
- RKE Federal
- EKS
- k3s

The `rke1` is now `rke`. All others are working as expected.
