### ISSUE TITLE
RFE: Support SUSE MicroOS/Fedora CoreOS and Ignition

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#28846]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Today using Rancher you cannot provision a Fedora CorsOS or SUSE MicroOS node since it only supports ignition and not cloud-init. Rancher should support managing ignition config in nodetemplates rather than just cloud-init so SUSE MicroOS or Fedora CorsOS can be supported.

Another issue is when running in a VMware environment it wants to use the guestinfo instead of a cloud-init drive. So if we can disable mounting that drive and only use guestinfo metadata.

**Comment by Amos-85** [comment]
@deniseschannon
will you consider to support ignition?

**Comment by mitchellmaler** [comment]
Updated issue to include SUSE MicroOS which also only supports Ignition (except for OpenStack)

**Comment by Amos-85** [comment]
Flatcar-OS is also in the list.

**Comment by mitchellmaler** [comment]
Still not supported. Would be a nice addition.

**Comment by idc77** [comment]
reopen?
