### ISSUE TITLE
Rancher Dashboard doesn't work when Rancher/cluster is configured with a proxy

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/rancher#28850]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1) Rancher run with - `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e HTTP_PROXY="http://10.199.12.174:3128" -e HTTPS_PROXY="http://10.199.12.174:3128" -e NO_PROXY="localhost,127.0.0.1,10.199.0.0/16,<rancher hostname>" -v /var/lib/rancher:/var/lib/rancher --name rancher rancher/rancher`
1) All downstream nodes configured with HTTP_PROXY and NO_PROXY in docker environment variables through /etc/systemd/system/docker.service.d/http-proxy.conf​
```
[Service]
Environment="HTTP_PROXY=http://10.199.12.174:3128" NO_PROXY="localhost,127.0.0.1,10.199.0.0/16,<rancher hostname>"
```
3) Custom cluster created, nodes joined to cluster with docker run command
4) Once nodes stabilize and become active, the "Try Dashboard" link shows up.

**Result:**
Dashboard link redirects to /dashboard/fail-whale/
Rancher server logs `http: proxy error: proxyconnect tcp: failed to find Session for client <IP of proxy>`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.2
- Installation option (single install/HA):
rancher on single-node docker
custom downstream cluster on 3 nodes with all roles.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 6a6f13c

* Rancher and custom cluster are both configured behind a proxy 
* Provisioning cluster succeeds
* Dashboard can be accessed for the downstream cluster

**Comment by bmdepesa** [comment]
@cevatkerim can you provide more details on how your environment is configured, including cluster types, and what symptoms you are seeing? Additional details on proxy configuration would also be helpful. 

We have not seen this in recent releases with our test configurations (with Rancher and/or downstream clusters deployed behind a proxy).
