### ISSUE TITLE
"?" shown when containers are in "updating-healthy" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2885]
Server vesion - V0.47.0

Create LB services and start the service.
"?" shown when LB containers are in "updating-healthy" state.

<img width="173" alt="screen shot 2015-12-02 at 4 30 03 pm" src="https://cloud.githubusercontent.com/assets/4266958/11548548/8b87c26a-9912-11e5-8fd0-621187cc0751.png">

**Comment by vincent99** [comment]
Not really sure how to create that situation, but added to the state list.

**Comment by tfiduccia** [comment]
Sangeetha can you reproduce this?

**Comment by sangeethah** [comment]
@tfiduccia , I dont see this happen anymore. When i logged this bug, just creating LB services and start the ing service would should this bug.
