### ISSUE TITLE
Add method for manual only metadata.json refresh

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#28857]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
At the moment metadata is automatically (periodically) refreshed according to the `refresh-interval-minutes`
![image](https://user-images.githubusercontent.com/8906089/92898327-cd0ea100-f415-11ea-9ad0-b5df61025867.png)

**Result:**
When deploying multiple clusters with the need to control config drift, or when working with partially air-gapped clusters with Rancher url's proxied, the available images may shift from one day to the next and without warning the admins of a partially air-gapped cluster may find they need to pull images to the private repos in order for clusters to successfully deploy (breaking Rancher based deployment operations).

It would be helpful to have an option for manually refreshing the images when desired (perhaps a button in the UI?)

**Workaround**
Current workaround is to manually mirror the metadata and update that independently when needed
See: https://rancher.com/docs/rancher/v2.x/en/admin-settings/k8s-metadata/#configuring-the-metadata-synchronization

gz#12226

**Comment by dnoland1** [comment]
We do have a "Refresh Kubernetes Metadata" button. It's under Tools -> Drivers:
![image](https://user-images.githubusercontent.com/468462/92949739-718de480-f410-11ea-95ce-314509de2c0a.png)

**Comment by Tejeev** [comment]
🤦🏾 
Thanks David

**Comment by Tejeev** [comment]
Just in case anyone comes searching:

Under Global > Tools > Drivers, there is a Refresh Kubernetes Metadata button.
​This is a global refresh, but you should be able to use this to manually refresh your metadata by setting the `refresh-interval-minutes` to 0 and using this button to perform the metadata refresh.
