### ISSUE TITLE
Chart - no charts available for non-cluster-owner role

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28861]
bug rancher `6a6f13` HA installation 

As a standard user, cluster member/ project owner/ project member, go to dashboard -> apps 

<img width="1305" alt="Screen Shot 2020-09-11 at 10 15 25 AM" src="https://user-images.githubusercontent.com/6218999/92955472-08ab6a00-f41a-11ea-9d2e-bb8171a7d4a0.png">

------

It turns out only admin/ cluster owner can see charts. 
All other roles ( cluster member, project owner, project member) can NOT see charts.

```
> k get clusterrepos.catalog.cattle.io -A
Error from server (Forbidden): clusterrepos.catalog.cattle.io is forbidden: User "u-q84bt" cannot list resource "clusterrepos" in API group "catalog.cattle.io" at the cluster scope
```

**Comment by dramich** [comment]
None of the new types have RBAC associated with them yet which is why this only works for admins. Per discussion with @ibuildthecloud we aren't ready to implement this yet so a fix is TBD.

**Comment by deniseschannon** [comment]
Still discussing the exact level of permissions for each type, but need to be implemented to add access to these CRD types to our built-in roles. 

Type | Cluster Owner | Cluster Member | Project Owner | Project Member
---|---|---|---|---
ClusterRepos | CRUD | CRUD | R | R
Operations | R | R | R | R 
Releases | R | R | R | R

**Comment by jiaqiluo** [comment]
on rancher:`master-9addfe297070f85eb3020d0e54571adaa438ccec-head`, docker install 

As a standard user, cluster member/ project owner/ project member can see apps in the dashboard now.

**Comment by jiaqiluo** [comment]
This issue can be closed since the original bug in the ticket is fixed.

A new issue is made for the RBAC table.

**Comment by sangeethah** [comment]
Related issue - https://github.com/rancher/rancher/issues/29038
