### ISSUE TITLE
[Release task] Charts cleanup and branch changes

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#28872]
- [x] Create branches
- [x] Update the github workflow branches as necessary
- [x] Change branch to source and primary, and make source an orphan branch
- [x] ~Update the branches in rancher~ this actually is already done by default
- [x] Same for partner-charts
- [x] Same for RKE-charts (maybe)
- [x] We have several charts in the charts repo that have multiple versions in order to do upgrade testing. Ensure those get deleted prior to 2.5 going out. 
- [x] Need github pages branch changed to main

**Comment by cbron** [comment]
@bmdepesa there might still be one duplicate but this should be ready to test otherwise. We can throw into review if you want to wait until then.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.0-rc4

* All v2 system charts have only one version, including fleet.
