### ISSUE TITLE
[Monitoring V2] Rename grafana-dashboards and remove grafana-datasources

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#28887]
Based on conversation with @ibuildthecloud and @vincent99:
- The `grafana-dashboards` namespace will be renamed to `cattle-dashboards`
- The `grafana-datasources` namespace will be entirely deprecated and all RBAC associated to it which was added to the chart will be removed. Instead, those ConfigMaps will be created in the original `cattle-monitoring-system` namespace and the RBAC used to define permissions to view/edit Grafana Datasources will be the default `monitoring-admin`, `monitoring-edit`, and `monitoring-view` roles.

**Comment by jiaqiluo** [comment]
This is validated on rancher:"master-9addfe297070f85eb3020d0e54571adaa438ccec-head" with the repo `https://git.rancher.io/charts` pointing to `dev-v2.5`

The Monitoriing app is deployed, and namepases `cattle-dashboards` and cattle-monitoring-system` are created.
