### ISSUE TITLE
[RFE] Add support for logz.io in Rancher logging

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#28889]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Other details that may be helpful:**

https://docs.logz.io/shipping/shippers/fluentd.html

The fluentd plugin has been included in the Gemfile [with this PR](https://github.com/rancher/fluentd/pull/19)

gz#12176

**Comment by miraculixx** [comment]
This looks interesting. How can this be added to an existing Rancher installation?

**Comment by dkeightley** [comment]
The logz.io shipper is now available in monitoring v2
