### ISSUE TITLE
Backport: AKS NetworkPolicy is not supported - due to case sensitivity

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#28880]
Backport: https://github.com/rancher/rancher/issues/26710

**Comment by aaronRancher** [comment]
Was unable to reproduce this issue with `rancher\rancher:<>` `version v2.4.8`.
Steps:
- Create a AKS cluster with advance settings - Network Plugin : azure, Network Policy: Calico and selecting a Virtual network

API request:
```
logAnalyticsWorkspaceResourceGroup: ""
masterDnsPrefix: ""
maxPods: 110
name: ""
networkPlugin: "azure"
networkPolicy: "Calico"
```
Cluster was provisioned successfully without any error.

The bug fix is verified with Rancher server `rancher\rancher:master-head` `version e98728f`

API request:
```
masterDnsPrefix: ""
maxPods: 110
name: ""
networkPlugin: "azure"
networkPolicy: "calico"
```
Cluster was provisioned successfully without any error.

**Comment by aaronRancher** [comment]
This behavior is not seen in `rancher\rancher:v2.4-3786-head`
API request:
```
masterDnsPrefix: ""
maxPods: 110
name: ""
networkPlugin: "azure"
networkPolicy: "calico"
```
Cluster was provisioned successfully without any error.

This behavior is not seen in `rancher\rancher:v2.5-eb990af-head`
API request:
```
masterDnsPrefix: ""
maxPods: 110
name: ""
networkPlugin: "azure"
networkPolicy: "calico"
```
Cluster was provisioned successfully without any error.
