### ISSUE TITLE
Rancher crashes after opening the "System" project

### ISSUE THREAD

**Issue by pensiero** [rancher/rancher#28882]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Open a Cluster
- Select the "System" project into the cluster

**Result:**
Rancher crashes, the cluster becomes unavailable, after ~10secs it gets available again
![Screenshot 2020-09-12 at 23 01 58](https://user-images.githubusercontent.com/2010696/93005607-e1a48380-f552-11ea-8f69-9ce817e16766.png)

If I don't open the "System" project, nothing particular bad happens, everything runs as usual.

**Other details that may be helpful:**
For a brief second, I have the possibility to see the pods in the `System` project, and it seems the following are unavailable
- `exporter-kube-state-cluster-monitoring` (2 pod available, however many pods not available)
- `rke-kube-dns-addon-delete-job` (totally unavailable)

![Screenshot 2020-09-12 at 23 01 35](https://user-images.githubusercontent.com/2010696/93005608-e406dd80-f552-11ea-9195-4a737c05a995.png)
![Screenshot 2020-09-12 at 23 01 36](https://user-images.githubusercontent.com/2010696/93005609-e49f7400-f552-11ea-8ef7-1efa87456fa8.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.6
- Installation option (single install/HA): single install (server and node on 2 separate machines)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal, 64GB RAM, 8 cores CPU   
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Comment by vincent99** [comment]
The red response is from CloudFlare.  The exact message isn't quite there but you probably don't want your server proxied through them in general.  It's probably something like they're refusing to proxy a request that Rancher is making to itself because it has their headers in it and they they think it's a loop.

**Comment by pensiero** [comment]
Got it, I guess I can disable Cloudflare, however I was using it as SSL proxy, so I would need to find another way to get https.
@vincent99 do you think that is related to the fact when I try to access "System", the cluster goes down?

**Comment by vincent99** [comment]
You don't need a proxy for that.. Kubernetes and Rancher are TLS-only by default

**Comment by pensiero** [comment]
Thanks, I disabled the Cloudflare proxy, and used Let's Encrypt through `--acme-domain` parameter. All good now!
