### ISSUE TITLE
Service type cannot be altered from HeadlessService to ClusterIP

### ISSUE THREAD

**Issue by hweidner** [rancher/rancher#28883]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

- Select a cluster and namespace
- Go to "Workloads" -> "Service discovery"
- Select "Add Record"
- Enter a service name, select e.g. "one or more external ip addresses" and enter an external address (or choose another option, it does not matter), and save. Do not select "Show advanced options" in this step. The new service will be created as "Headless service" without a cluster IP address.
- Edit the created service. Select "Show advanced options", change the service type from "Headless Service" to "ClusterIP (internal only)". Select a port mapping. Save the altered configuration.

I expect that the service is altered and a new internal cluster IP address is assigned.

**Result:**

The service stays unchanged. Now cluster IP is assigned. When editing again, it still appears as "Headless Service".

**Other details that may be helpful:**

- The problem does not occur when the service is initially created as a "ClusterIP" service from the beginning. Just altering an existing service is not possible.
- I have verified this with a RKE cluster and a MicroK8s cluster.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.8
- Installation option (single install/HA): single install from Docker image
- Docker version (use `docker version`): 19.03.8

**Comment by hweidner** [comment]
Today, I installed the new version Rancher 2.5.0. The bug is still present.

**Comment by hweidner** [comment]
The bug is still present in the current Rancher version 2.5.8.

**Comment by silviokuehn** [comment]
This bug seems to still be present in Rancher v2.6.12.
