### ISSUE TITLE
Not created cluster...

### ISSUE THREAD

**Issue by oguzhansrky** [rancher/rancher#28885]
*kubernetes cluster not installed. pre-pulling kubernetes images 3 repeated times* 
I've been waiting for 20 minutes.

rancher container it keeps rebooting.

![image](https://user-images.githubusercontent.com/52497227/93006995-fe998080-f56b-11ea-8b35-d0a71d3fe642.png)
![image](https://user-images.githubusercontent.com/52497227/93007017-399bb400-f56c-11ea-9dcf-8d8a96a17f80.png)

This system was working the last time I used it, what the hell did you do?

"""Rancher v2.4.8 same in this version"""

Docker version 19.03.12, build 48a66213fe
Rancher `v2.4.5` UI: `v2.4.28` |
Ubuntu 18.04.5 LTS

**Comment by oguzhansrky** [comment]
![image](https://user-images.githubusercontent.com/52497227/93015983-75fbfe00-f5c6-11ea-871c-8ac4dd437449.png)

Rancher repo timeout? Really?

**Comment by cloudbring** [comment]
I came to say the same thing. This stopped working on me between v2.4.5 and v2.4.8. Gonna downgrade back to v2.4.5 and see if it works.

**Comment by oguzhansrky** [comment]
> I came to say the same thing. This stopped working on me between v2.4.5 and v2.4.8. Gonna downgrade back to v2.4.5 and see if it works.

I've tried all the versions and versions I have installed before, buddy. There is no result ... rancher repositories not working
