### ISSUE TITLE
[Rancher UI] Cosmetic improvement for previewing Helm templates

### ISSUE THREAD

**Issue by onpaws** [rancher/rancher#28896]
**What kind of request is this (question/bug/enhancement/feature request):**
Cosmetic improvement to improve Helm template legibility for all browser window widths (vs just smaller widths)

**Steps to reproduce (least amount of steps as possible):**
  - Navigate from the Rancher main menu Apps
    <img src="https://user-images.githubusercontent.com/182515/93084412-46b3c280-f694-11ea-8f7a-57daa9f7bb0a.png" width="150">
  - Click Launch on the upper right
    <img src="https://user-images.githubusercontent.com/182515/93084509-6b0f9f00-f694-11ea-922f-8de2f9d3513a.png" width="300">
  - Scroll down and pick a Helm chart with many files, for example [Sentry](https://github.com/sentry-kubernetes/charts/tree/5.1.0)
  - Scroll to the bottom and click PREVIEW at the very bottom of the page:
    ![image](https://user-images.githubusercontent.com/182515/93020680-a8195a00-f5de-11ea-8646-53d30f20356f.png)

**Result:**
Attempting to preview the Helm template files is unnecessarily annoying - have to scroll around a lot for charts with lots of templates.
<details>
<summary>How its like now</summary>

![before](https://user-images.githubusercontent.com/182515/93020358-d5650880-f5dc-11ea-8859-7c873a01e6ea.gif)
</details>

<details>
  <summary>How I'd like it to be</summary>

  ![after](https://user-images.githubusercontent.com/182515/93020394-14935980-f5dd-11ea-827a-e5586fbf9e4e.gif)
</details>

**Other details that may be helpful:**
I already implemented a one liner CSS change that makes this happen. Will link it in a subsequent comment.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): n/a

**Comment by onpaws** [comment]
https://github.com/rancher/ui/pull/4166

**Comment by izaac** [comment]
Rancher version: `master-head (09/29/2020)` _a2a141e_ Single install.

Global Apps Preview dropdown are looking good. 

But Project Apps Preview still shows the dropdown with 33% of width.

![Screen Shot 2020-09-29 at 2 44 50 PM](https://user-images.githubusercontent.com/27659/94620411-700f4980-0263-11eb-9b7f-83b5276cc41f.png)

**Comment by onpaws** [comment]
Thanks @izaac! 
I went ahead and opened a basically identical [one liner PR]() that I believe should address the Project Apps Preview you've identified. First time Rancher contributor here. What do you think, look OK?

**Comment by izaac** [comment]
Sure @onpaws thanks for the contribution we would need to check with a UI developer first to check the change and I will check it in a build further down the line.

**Comment by izaac** [comment]
Rancher version: `master-head (09/29/2020)` _a2a141e_

Both Global and Project Charts have this dropdown displayed as expected with the change.

Sample in Project app:

![Screen Shot 2020-09-29 at 6 04 34 PM](https://user-images.githubusercontent.com/27659/94631988-41529c80-027e-11eb-8062-9d572848e4ad.png)
