### ISSUE TITLE
v2 Istio - Kiali link in Istio dashboard do not work

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#28901]
rancher/rancher:master-head ef11fe3

* Deploy Rancher
* Deploy a cluster
* Deploy v2 Monitoring
* Deploy v2 Istio
* After Istio is deployed, the Istio dashboard link is shown in the main menu
* Navigate to the Istio dashboard and `Kiali` and `Prometheus` links are shown, but neither take the user to the services

In the current version, by default, Kiali is deployed in the `istio-system` namespace: `rancher-istio-kiali`, and Prometheus is deployed in `cattle-monitoring-system` ns: `prometheus-rancher-monitoring-prometheus`

```
# api/v1/namespaces/istio-system/services/http:kiali:20001/proxy/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"kiali\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kiali",
    "kind": "services"
  },
  "code": 404
}

# and
# api/v1/namespaces/istio-system/services/http:prometheus:9090/proxy/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"prometheus\" not found",
  "reason": "NotFound",
  "details": {
    "name": "prometheus",
    "kind": "services"
  },
  "code": 404
}
```

**Comment by cbron** [comment]
Removing prometheus from this issue as that will be handled via 28495

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 8fd81a9

* Deploy a cluster
* Install monitoring & Istio
* Go to Istio Overview page
* Kiali link opens successfully
