### ISSUE TITLE
Make non-privileged docker run failure more obvious

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#28910]
Starting in 2.5 our docker run command requires the `--privileged` flag. If you don't supply the flag, the container still starts up but about a minute later k3s fails with a non-obvious error, alongside a great deal of error messages. 

Solution: 
We should attempt to exit soon after running the command with an obvious error.

**Comment by sangeethah** [comment]
Tested with rancher server version - `8fd81a9`
When installing rancher using docker install with out privileged  flag , we see the following errors in the logs:
`ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes`
