### ISSUE TITLE
Rancher not provisioning vSphere: Error with pre-create check: "unexpected EOF";

### ISSUE THREAD

**Issue by brtduvally** [rancher/rancher#28919]
Rancher doesn't appear to be connecting to vSphere to provision, but can, since it obtained Datacenter info during the Node Template creation, verified from events log in vSphere. 

Error in UI for each node is: `Error with pre-create check: "unexpected EOF"; Timeout waiting for ssh key`

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create vSphere credentials
2. Create Node Template using data pulled from vSphere
3. Create cluster or any number of nodes and roles using Node Template. 
  * RKE settings used were known good from existing running clusters
  * using Default RKE settings produced same result

**Result:**
Nodes retry to be created but UI only ever reports `Error with pre-create check: "unexpected EOF"; Timeout waiting for ssh key`. This refreshes forever. Rancher doesn't ever connect with vSphere.

**Other details that may be helpful:**
create command used (obtained via trace logging)

```
2020/09/14 20:19:25 [TRACE] create cmd [create -d vmwarevsphere --engine-install-url https://releases.rancher.com/install-docker/19.03.sh --vmwarevsphere-memory-size 4096 --vmwarevsphere-ssh-user docker --vmwarevsphere-vcenter XXXXXXXX --vmwarevsphere-folder /DEV/vm/vo --vmwarevsphere-password XXXXXXXX --vmwarevsphere-pool /Brown-CIT/host/unity-qa/Resources --vmwarevsphere-ssh-password tcuser --vmwarevsphere-ssh-user-group staff --vmwarevsphere-clone-from /DEV/vm/templates/UBUNTU_18.04-Rancher --vmwarevsphere-network /DEV/network/10.4.25.x --vmwarevsphere-cfgparam disk.enableUUID=TRUE --vmwarevsphere-creation-type template --vmwarevsphere-ssh-port 22 --vmwarevsphere-username XXXXXXXX --vmwarevsphere-vcenter-port 443 --vmwarevsphere-cloud-config /MRQYNSTNPK/cloud-config --vmwarevsphere-disk-size 50000 --vmwarevsphere-cpu-count 2 --vmwarevsphere-datacenter /DEV --vmwarevsphere-datastore-cluster /DEV/datastore/ds-dev-sdrs1]
2020/09/14 20:19:25 [INFO] Provisioning node dranchtestcpcit1
```
rancher-machine run output (pastebin) (thank you David Holder)
[tdbrown rancher-machine output](https://pastebin.com/S2abTUjM)

vSphere version: 6.4.0.44000

**Environment information**
- Rancher version: 2.4.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere on-prem
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 2Cpu, 8g Mem
- Kubernetes version (use `kubectl version`):  v1.17.6
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Docker version (use `docker version`): Server version: 19.03.6

**Comment by lwilliams1990** [comment]
I'm currently investigating the same issue in our environment. I've still not managed to resolve the issue.

It seems to be something to do with distributed port groups in our VMware environment; to re-create the issue I've been using 2.4-head:

`docker run -d --restart=unless-stopped -p 80:80 -p 443:443  --privileged rancher/rancher:v2.4-head
docker exec -ti containerID loglevel --set trace
docker logs containerID | tee unexpected_EOF.log`

When you search the log for "panic: reflect.Value.Addr of unaddressable value", the last response from vCentre prior is always a port group for me. If I remove this port group it proceeds a little further but ultimately fails against another.

**Comment by lwilliams1990** [comment]
To update here, we decommissioned some legacy infrastructure from our environment that had a traffic filtering and marking policy applied to one of the port groups. Once this was removed this issue was resolved.
