### ISSUE TITLE
Fedora CoreOS: Error response from daemon: error setting label on mount source '/usr/lib/modules': relabeling content in /usr is not allowed

### ISSUE THREAD

**Issue by dirien** [rancher/rancher#28918]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

- Install  Fedora CoreOS 
- Install  Rancher Agent

**Result:**
 2020/09/15 18:12:00 [WARNING] Can't start Docker container [kube-proxy] on host [193.148.162.99]: Error response from daemon: error setting label on mount source '/usr/lib/modules': relabeling content in /usr is not allowed

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.8
- Installation option (single install/HA): single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM Fedora CoreOS 32.20200824.3.0 stable

- Docker version (use `docker version`):

```
 Server Version: 19.03.11

```

**Comment by dirien** [comment]
Let me link following releated issues:

https://github.com/rancher/rke/pull/2214
https://github.com/rancher/rke/issues/2194

**Comment by Oats87** [comment]
The changes were merged and should land in RKE `1.2.0` and Rancher `2.5.0`.

**Comment by superseb** [comment]
This is the same as https://github.com/rancher/rke/issues/2194

**Comment by dirien** [comment]
Same  issue in flatcar linux...
