### ISSUE TITLE
Menu for Download CLI shows up on Left side of screen

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2891]
Version - Master 12/2

Steps:
1.  Click on Download CLI

Results:  The menu pops up on the left side of the screen instead of on the right under the download text
![image](https://cloud.githubusercontent.com/assets/11514927/11569252/20342228-99ae-11e5-87fc-45872505526d.png)

Expected:
The menu to drop-down in proper place

**Comment by will-chan** [comment]
I believe this has been fixed.  Can you reproduce on latest?

**Comment by sangeethah** [comment]
Tested with server version - V0.52.0-rc4.

Download CLI option now appears in the bottom right hand side and options show up above them.
<img width="1239" alt="screen shot 2016-01-06 at 3 14 47 pm" src="https://cloud.githubusercontent.com/assets/4266958/12157702/7ca54fec-b488-11e5-9d1e-79f20bec4f08.png">
