### ISSUE TITLE
Airgap - workload coredns does not pull from the private registry in the local cluster in docker install 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28916]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- prepare a private registry for Rancher's images
- run Rancher `v2.5.0-alpha2` single install in airgap environment with the option -e CATTLE_SYSTEM_CATALOG=bundled in the docker command
- Rancher is deployed successfully
- go to `local` cluster -> system project 

**Result:**
- Workload `coredns` does not pull from the private registry
![image](https://user-images.githubusercontent.com/6218999/93242113-2723a500-f73b-11ea-9299-4dd4dc88c220.png)

**Comment by maggieliu** [comment]
Only affects local docker cluster

**Comment by jiaqiluo** [comment]
The bugfix is validated on rancher: `v2.5.0-alpha3`, docker install in airgap env
 
![image](https://user-images.githubusercontent.com/6218999/93531786-a6a8a400-f8f4-11ea-8548-602aeac4cfef.png)

The image is included in the Rancher image, so it does not need to pull from the private registry.
