### ISSUE TITLE
Can't delete volume after created

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2892]
Version - Master 12/2

Steps:
1.  Create a mysql container (make sure volume is created and listed in Host details)
2.  Delete/Purge container
3.  Go to Storage tab in Host details page
4.  Try to remove volume

Results:
You can't remove, the drop-down menu only has View in API and no delete

Expected:
Should be able to remove the volume.

**Comment by deniseschannon** [comment]
I believe this is a duplicate of https://github.com/rancher/rancher/issues/2796
