### ISSUE TITLE
[2.3 Backport] Update k8s to the latest 1.16 and 1.17

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28925]

**Comment by maggieliu** [comment]
Need to test a Windows setup to make sure flannel is using 12 and working.

**Comment by deniseschannon** [comment]
* Backport to 1.16.15-rancher1 (not sure if it should be 1-1 or 1-2) as both are in dev-v2.4
* Update to 1.17.14 (to be released oct 14)

**Comment by ryansann** [comment]
- I backported `v1.16.15-rancher1-2`, this made more sense after discussing with @kinarashah 
- Both `v1.16.15-rancher1-2` and `v1.17.13-rancher1-1` have a few other updated images as compared to previous k8s versions in 2.3:
  - `rancher/coreos-etcd`
  - `rancher/rke-tools`
  - `rancher/cluster-proportional-autoscaler`
  - `rancher/nginx-ingress-controller`
  - `rancher/nginx-ingress-controller-defaultbackend`

**Comment by kinarashah** [comment]
Yeah, I agree. Since we're backporting versions from v2.4, it'd make sense to pick the latest versions there and update all images as required vs introducing a new version in v2.3 and then users needing to do another update. (This is because only the images changed, but the addon templates are the same)

**Comment by sowmyav27** [comment]
**On 2.3.9 - KDM pointing to dev-v2.3**

- Windows clusters - 1 etcd/control, 1 worker node linux, 3 windows worker nodes - using k8s versions: `v1.16.15-rancher1-2` and `v1.17.13-rancher1-1`
- Flannel version on windows nodes: `v0.12.0-rancher1 `
- Validations checks on the windows clusters look good.

**Comment by izaac** [comment]
ARM64 clusters in `v2.3.9` are experiencing this isssue: https://github.com/rancher/rancher/issues/29556

**Comment by izaac** [comment]
Done on Rancher `v2.3.9`

K8s post-upgrade tests

v1.15.12-rancher2-3 -> No new version 
v1.16.13-rancher1-1 -> 1.16.15-rancher1-2
v1.17.9-rancher1-1 -> v1.17.13-rancher1-1



Fresh install KDM tests and regression tests.

Clusters with network drivers, both fresh install and k8s upgrade.

Flannel
Calico
Canal
Weave

K8s versions Fresh install (pointing kdm to `dev-v2.3`

v1.15.12-rancher2-3
1.16.15-rancher1-2
v1.17.13-rancher1-1

**Comment by jiaqiluo** [comment]
Networks tests for new k8s versions in v2.3.9 are passed

the following 2 versions:
- v1.17.13-rancher1-1 
- v1.16.15-rancher1-2

and the following network providers:
- canal
- flannel
- calico
- weave
