### ISSUE TITLE
“dashboard" feature flag should not visible in the UI

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#28928]
Rancher server version - Latest build from master - 

Fresh install of 2.5 server.
Go to settings->Feature Flags
“dashboard” feature flag is available and enabled by default. 
We are allowed to disable this as well. 

Expected behavior:
We should not have “dashboard" feature flag.

**Comment by soumyalj** [comment]
Tested on master-head(bcc8261487ecdd3776)

**Steps:**

- Deploy a fresh install  HA setup 
- Navigate to Settings -> Feature flags
- The dashboard feature flag is still displayed and activated
- We can still deactivate the feature flag. Once deactivated, the HA setup is unavailable only for few seconds and becomes available again
After deactivating the feature flag, the UI button to access the dashboard is not available in each of the clusters. But we can access the dashboard on local and downstream clusters using the call :
https://xyz/dashboard/c/local/explorer
https://xyz/dashboard/c/c-jsdfd/explorer

**Comment by deniseschannon** [comment]
Is this still in the API? @dramich

**Comment by sangeethah** [comment]
@dramich We see the dashboard feature flag is  still in fresh install .

**Comment by dramich** [comment]
@sangeethah May need to check what version you are running, the feature was literally deleted from the code so that isn't possible.

**Comment by sangeethah** [comment]
On Fresh install of master-head - `bd88c` , we dont see the dashboard feature flag enabled anymore as expected.

<img width="1272" alt="Screen Shot 2020-09-19 at 6 34 14 PM" src="https://user-images.githubusercontent.com/4266958/93692371-35f5b900-faa7-11ea-8747-7176d2641b3a.png">

**Comment by sangeethah** [comment]
This issue now tracks the UI fixes needed for hiding the dashboard feature flag on upgrade cases -  https://github.com/rancher/rancher/issues/28930#issuecomment-694633565

**Comment by sangeethah** [comment]
Tested with Rancher server version -` v2.5.0-rc2`
ui-index - `https://releases.rancher.com/ui/latest2/index.html`

Deploy rancher v2.4.8 single node setup
At the global level, navigate to settings --> Feature Flags.
Deactivate Dashboard
Deploy few clusters in the setup and verify dashboard button is not available
Upgrade rancher to ` v2.5.0-rc2` with --privileged flag
After upgrade, the dashboard feature flag is still "disabled" , but the dashboard button is available to be used in each of the clusters.

<img width="1218" alt="Screen Shot 2020-09-26 at 9 03 31 AM" src="https://user-images.githubusercontent.com/4266958/94344862-2ca0ab00-ffd7-11ea-90dc-128fd5a7f1a3.png">

**Comment by sangeethah** [comment]
Tested with latest build from master - `27000be`

On an upgraded set up (from 2.4.8 with dashboard disabled) , "dashboard" feature flag is not available in the  settings --> Feature Flags as expcted.
