### ISSUE TITLE
Airgap - helm-operation pod in downstream cluster does not use the private registry 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28923]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run the latest rancher:`master-01c13f69cb277e037f6d58323cb0859300e8af5d-head`, single install in airgap environment 
- provision a custom cluster
- go to the custom clueter -> dashboard -> apps -> install monitoring 

**Result:**
- there is a helm-operation pod created in the cattle-system namespace in the system project in the custom cluster, but it does not pull images from the private registry so fails to start 

![image](https://user-images.githubusercontent.com/6218999/93270505-27856580-f766-11ea-875c-64f577199bc8.png)

**Comment by cbron** [comment]
Fairly sure this is just an images.txt issue. The helm deployer code has registry prefix: 
* https://github.com/rancher/rancher/blob/master/pkg/catalogv2/helmop/operation.go#L627
* https://github.com/rancher/rancher/blob/master/pkg/settings/setting.go#L97-L99

But the images.txt of last alpha is 0.1.1, which would explain why it worked originally but fails now. The tag got updated to 0.1.2 on last master-head build. So if we cut new alpha it should work.

**Comment by jiaqiluo** [comment]
This bug still exists in rancher: `v2.5.0-alpha3` 

<img width="1399" alt="Screen Shot 2020-09-17 at 2 30 05 PM" src="https://user-images.githubusercontent.com/6218999/93530659-cccd4480-f8f2-11ea-8e45-fea697784b02.png">


<img width="1429" alt="Screen Shot 2020-09-17 at 2 26 14 PM" src="https://user-images.githubusercontent.com/6218999/93530647-c9d25400-f8f2-11ea-9ef4-d9de10b435f7.png">

**Comment by cbron** [comment]
Found issue, this should actually work in local cluster, can we start airgap testing there @jiaqiluo / @sangeethah ? Issue should only be with downstream.

**Comment by jiaqiluo** [comment]
the bug still exists in dowsteam cluster in rancher:`v2.5.0-alpha4` docker instll setup 

![image](https://user-images.githubusercontent.com/6218999/93690631-79442d80-fa8f-11ea-8ffe-964bf9a135fe.png)

**Comment by cbron** [comment]
@jiaqiluo can you try restarting the agent downstream and see if that fixes it ?

**Comment by jiaqiluo** [comment]
@caleblloyd  after restarting the pod in the deployment `cattle-cluster-agent`, and re-install the monitoring v2, the app is deployed successfully.

**Comment by deniseschannon** [comment]
@jiaqiluo Was this tested on the local cluster or downstream user cluster?

**Comment by jiaqiluo** [comment]
@deniseschannon  downstream user cluster

**Comment by deniseschannon** [comment]
@jiaqiluo Can you try this again with monitoring to see if it's the same error as in this issue? https://github.com/rancher/rancher/issues/29026

If it's the same issue, I'd like to consolidate to 1 issue that is generic to all downstream user clusters.

**Comment by cbron** [comment]
Another thing to try debugging here is updating the setting multiple times, or try updating a different setting to see if that syncs. Each change would send another update for that setting. Not a solution but if that doesn't fix it then points to larger problem. Would be good to get logs here too, to see if any errors exist.

If we don't see this in any other airgap testing I think bumping to 2.5.x is reasonable. Might have been a one time fluke.

**Comment by cbron** [comment]
Have we seen this since the alpha builds ? Seems like it never showed up on any RC or the live release. cc @jiaqiluo @sangeethah  If we didn't and community doesn't either, we will close out.

**Comment by jiaqiluo** [comment]
The bugfix is validated in Rancher v2.5.1 docker-install airgap setup 

After installing the monitoring v2 in the downstream cluster, there are helm operation pods being created in the downstream cluster using images from the private registry and eventually, the app is installed successfully.

<img width="1373" alt="Screen Shot 2020-10-09 at 2 09 35 PM" src="https://user-images.githubusercontent.com/6218999/95631816-2da2f500-0a39-11eb-9f8f-9c2ba66f9dd1.png">


This issue is closed.
