### ISSUE TITLE
Airgap - helm-operation pod keeps creating in the local cluster 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28926]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run the latest rancher:`master-01c13f69cb277e037f6d58323cb0859300e8af5d-head`, single install in airgap environment 
- go to the local cluster -> system project 

**Result:**
- there are more and more pods for helm-operation created 
- and they might be related to the rancher-webhook app  

<img width="1408" alt="Screen Shot 2020-09-15 at 3 25 16 PM" src="https://user-images.githubusercontent.com/6218999/93271661-a9768e00-f768-11ea-9351-68a0bdbe6a23.png">

![image](https://user-images.githubusercontent.com/6218999/93271644-a2e81680-f768-11ea-8974-2921aab4f586.png)

**Comment by maggieliu** [comment]
@ibuildthecloud should the helm-operation pod be more aggressive in cleaning up pods? When we error out it fills up with pods every quickly.

**Comment by ibuildthecloud** [comment]
@maggieliu Yes, we need to not try so much.  I'll address this.

**Comment by jiaqiluo** [comment]
The bugfix is validated on rancher: `v2.5.0-alpha3`, docker install in airgap env

**Comment by jiaqiluo** [comment]
The fix is validated on rancher:`v2.5.0-alpha4` 
the steps are the same as the issue provides.

![image](https://user-images.githubusercontent.com/6218999/93690563-92001380-fa8e-11ea-838f-86e53133204f.png)
