### ISSUE TITLE
[UI] "Error connecting to proxy" while running locally

### ISSUE THREAD

**Issue by sulemansuleman** [rancher/rancher#28935]
I cloned the **ui** repository to my local machine. I followed the steps as mentioned in the README.md file of **ui** repository. The application starts properly but unfortunately on the login page (the first page which appears when the application starts), it gives this error **Error connecting to proxy** as shown in the screenshot attached herewith this ticket. Do i need to change anything in the code? I don't see anything regarding this in the README.md file.
![screenshot](https://user-images.githubusercontent.com/26137440/93331793-22392100-f821-11ea-951d-d0174c188ff5.PNG)

**Comment by vincent99** [comment]
You probably aren't also running all of Rancher locally, so you need to point it at a running installation.  `RANCHER="https://your-rancher.com" yarn start`
