### ISSUE TITLE
Error seen in the EKS cluster in rancher when the k8s version of cluster is upgraded in the EKS console 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28939]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On master-head - commit id: `01c13f69cb`
- Deploy a hosted EKS cluster with k8s version 1.16 in Rancher
- In EKS console, update the k8s version of the cluster to 1.17
- After the upgrade goes through in the EKS console, the cluster is seen stuck in `Updating` state in rancher with error `InvalidParameterException: Unsupported Kubernetes minor version update from 1.17 to 1.16 { RespMetadata: { StatusCode: 400, RequestID: "e91de687-25da-4f96-a0e7-7b86a9eb58eb" }, ClusterName: "sowmya-0916-2", Message_: "Unsupported Kubernetes minor version update from 1.17 to 1.16" }`
<img width="1418" alt="Screen Shot 2020-09-16 at 11 20 46 AM" src="https://user-images.githubusercontent.com/26032343/93376754-ea28e280-f80e-11ea-801f-92e40e8e14ee.png">

- View in API of the cluster - In `eksConfig` spec: `"kubernetesVersion": "1.16"` and `upstreamSpec` has `"kubernetesVersion": "1.17",`

**Expected Result:**
Cluster in Rancher should get successfully upgraded to 1.17 when the k8s version of the cluster is changed in EKS console.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `01c13f69cb`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS hosted
- Kubernetes version (use `kubectl version`):

```
1.16 to 1.17
```

**Comment by sowmyav27** [comment]
Not able to reproduce this issue with the same set of steps.

**Comment by sowmyav27** [comment]
Hit this issue again on master-head - commit id: `33f755f18`

- Deploy an EKS cluster with 2 node groups in k8s 1.15
- Updated k8s in EKS console to 1.16
- The cluster on Rancher is now stuck in `Updating` state

<img width="1446" alt="Screen Shot 2020-09-17 at 10 59 07 AM" src="https://user-images.githubusercontent.com/26032343/93509627-d8aa0e00-f8d4-11ea-88a8-56abbbe9af2e.png">

**Comment by sowmyav27** [comment]
**On master-head - commit id: `5ad6fdb`** - Not able to reproduce this issue.

- Deployed an EKS with k8s 1.15 from Rancher.
- Upgrade cluster to 1.16 in EKS console
- When the cluster finishes upgrading, cluster in Rancher is seen in Active state and with upgraded k8s version.
- No error seen

<img width="1304" alt="Screen Shot 2020-09-20 at 11 24 36 AM" src="https://user-images.githubusercontent.com/26032343/93718891-e9a48a80-fb33-11ea-8167-a2d03342e74d.png">

**Comment by aaronRancher** [comment]
The bug is not seen on `rancher\rancher:master-head` `version 9addfe2` with an imported EKS cluster:

Steps:
Deploy an EKS k8s 1.16 cluster from the EKS console.
Import cluster into Rancher
Upgrade cluster to 1.17 in EKS console

Result:
Cluster finishes upgrading and is seen in active state
<img width="1254" alt="Screen Shot 2020-09-20 at 12 51 21 PM" src="https://user-images.githubusercontent.com/57409052/93720799-2c6c5f80-fb40-11ea-8be7-cde93b4938f1.png">
