### ISSUE TITLE
Dashboard feature flag remains deactivated after upgrade 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#28930]
**What kind of request is this (question/bug/enhancement/feature request):**Bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy rancher v2.4.8 single node setup
2. At the global level, navigate to settings --> Feature Flags.
3. Deactivate Dashboard
4. Deploy few clusters in the setup and verify dashboard button is not available 
5. Upgrade rancher to master-head(master-01c13f69cb277) with --privileged flag

**Result:**
After upgrade it was observed that dashboard feature flag was still "Deactivated"  and the users do not have the option to switch to Dashboard view
<img width="1357" alt="Screen Shot 2020-09-15 at 5 41 49 PM" src="https://user-images.githubusercontent.com/18536626/93279701-bef5b300-f77c-11ea-87f9-d84d6589282f.png">

The dashboard feature flag should be enabled on a upgrade to master-head setup

Note: The dashboard feature flag can be manually activated and users can switch to dashboard view from the clusters.

Question: Should the dashboard feature flag be visible in "Settings" after upgrade or in a fresh install setup?

**Comment by soumyalj** [comment]
Tested with upgrade from v2.4.8 to master-head

1. Deploy rancher v2.4.8 single node setup
2. At the global level, navigate to settings --> Feature Flags.
3. Deactivate Dashboard
4. Deploy few clusters in the setup and verify dashboard button is not available 
5. Upgrade rancher to master-head(d671d58a30606) with --privileged flag

After upgrade, the dashboard feature flag is still "Deactivated" , but the dashboard button is available to be used in each of the clusters.

**Comment by soumyalj** [comment]
Related issue: https://github.com/rancher/rancher/issues/28928

**Comment by deniseschannon** [comment]
Backend is working as expected and we will hide the feature flag using this ticket: https://github.com/rancher/rancher/issues/28928
