### ISSUE TITLE
Cluster Provider Detection- Windows vs. Linux RKE clusters

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28947]
Need to differentiate Linux cluster vs Windows cluster for RKE1. If it's a Windows cluster need to be RKE.Windows.

**Comment by StrongMonkey** [comment]
Backend change is merged and ready to test. When provisioning a window cluster, click ViewAPI and cluster.status.provider should be rke.windows.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `9ee39b`**

- Deploy a windows cluster - custom - 1 linux all roles, 3 windows worker node. VXLAN
- View in API of the cluster shows provider=rke

**Comment by StrongMonkey** [comment]
@sowmyav27 Backend fix is merged and once build is done it is available for test.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `e2e530c19` and master-head - commit id: `a31eecf55`**

- Deploy a cluster - linux nodes(windows disabled). Provider was seen as rke
- Deploy a windows enabled - add only linux nodes. Provider was seen as rke
- Deploy a windows enabled cluster. Add windows worker nodes. Provider is seen as rke.windows when the windows nodes have registered in the cluster.

**Upgrade from 2.5.3 to 2.5-head - commit id: `7e386eb`**
- Deploy a cluster - linux nodes(windows disabled). 
- Deploy a windows enabled - add only linux nodes.
- Deploy a windows enabled cluster. Add windows worker nodes.
- Provider for all these 3 clusters is rke ^^^
- On an upgrade to 2.5-head , windows cluster with windows nodes has provider: rke.windows. other two clusters have provider: rke

**Upgrade from 2.5.3 to master-head**
- Deploy a cluster - linux nodes(windows disabled). 
- Deploy a windows enabled - add only linux nodes.
- Deploy a windows enabled cluster. Add windows worker nodes.
- Provider for all these 3 clusters is rke ^^^
- On an upgrade to 2.5-head , windows cluster with windows nodes has provider: rke.windows. other two clusters have provider: rke
