### ISSUE TITLE
rancher logs show a constant "v1 ComponentStatus is deprecated in v1.19+" logs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28943]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On latest master-head - HA setup
- Rancher logs show constant logs

```
W0916 22:28:19.846787       6 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W0916 22:28:34.856551       6 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W0916 22:28:49.847228       6 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W0916 22:29:04.846982       6 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W0916 22:29:19.847345       6 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W0916 22:29:34.848055       6 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W0916 22:29:49.847517       6 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `53cf961efce4c`
- Installation option (single install/HA): HA

**Comment by Oats87** [comment]
I believe this is coming from `client-go` when it is retrieving `ComponentStatus` from the K8s apiserver. We can probably mute this warning, but we should think about this from a more grand perspective, i.e. not relying on `ComponentStatus` anymore

**Comment by ibuildthecloud** [comment]
We use component status in two ways.
1. The status is aggregated to the v3.Node objects and show on the cluster page in ember
2. Every 15 seconds or so we listen them as a healthcheck that we can talk to downstream clusters.

**Comment by deniseschannon** [comment]
As this will most likely be dropped in later k8s versions, we need to account for what/how to fix this. Note: This is only applicable for v2.5+ as it has k8s 1.19 as the client-go version.

**Comment by bashofmann** [comment]
Would addressing this also directly fix https://github.com/rancher/rancher/issues/11496?

**Comment by deniseschannon** [comment]
In our client-go fork, which is referenced in Rancher https://github.com/rancher/rancher/blob/master/go.mod#L22, we need to update the client-go fork to suppress the deprecation warning. 

The actual fix regarding component status and how Rancher uses it will be in #11496

**Comment by sadiapoddar** [comment]
2.5.2 rancher logs seeing these warnings
W1117 11:24:57.845187       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1117 11:25:12.846285       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1117 11:25:27.844398       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1117 11:25:42.859348       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1117 11:25:57.844324       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1117 11:26:12.844388       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1117 11:26:27.844319       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1117 11:26:42.845506       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+

**Comment by sadiapoddar** [comment]
Tested on the master, master-5ebc964. I am still seeing all these go client warings. 
------ docker logs -------
W1203 18:33:36.055508       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1203 18:33:51.052719       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1203 18:34:06.067995       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1203 18:34:14.880921      29 watcher.go:199] watch chan error: etcdserver: mvcc: required revision has been compacted
W1203 18:34:21.072161       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1203 18:34:36.068047       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1203 18:34:51.109527       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1203 18:35:06.997876       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1203 18:35:14.391171      29 watcher.go:199] watch chan error: etcdserver: mvcc: required revision has been compacted
W1203 18:35:21.268842       7 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+

**Comment by sadiapoddar** [comment]
Verified on master-head, commit a31eecf and 2.5-head, commit e2e530c

Don't see the go client's Component deprecation warnings in logs.
------- docker logs ---------
2020/12/03 22:27:57 [INFO] APIVersion /v1 Kind ComponentStatus
2020/12/03 22:27:59 [INFO] APIVersion /v1 Kind ComponentStatus
2020/12/03 22:28:16 [INFO] APIVersion /v1 Kind ComponentStatus
2020/12/03 22:28:46 [INFO] APIVersion /v1 Kind ComponentStatus
2020/12/03 22:28:47 [INFO] APIVersion /v1 Kind ComponentStatus
2020/12/03 22:29:08 [INFO] APIVersion /v1 Kind ComponentStatus
