### ISSUE TITLE
Monitoring v2 - Prometheus cannot scrape metrics from CoreDNS in GKE

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28942]
**What kind of request is this (question/bug/enhancement/feature request):**
bug 

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:`master-01c13f69cb277e037f6d58323cb0859300e8af5d-head` HA mode 
- provision a GKE cluster 
![image](https://user-images.githubusercontent.com/6218999/93397060-9f6a9300-f82d-11ea-8d4a-e11e899d2cdb.png)
- go to dashboard -> apps -> install monitoring v2 

**Result:**

<img width="1848" alt="Screen Shot 2020-09-16 at 3 07 03 PM" src="https://user-images.githubusercontent.com/6218999/93397720-05a3e580-f82f-11ea-9f87-f7ed0a7f5fbb.png">

it looks like there is no CoreDNS, but kubeDNS in the GKE cluster. 
```
>  k get pods -n kube-system
NAME                                                        READY   STATUS    RESTARTS   AGE
event-exporter-gke-8489df9489-vwv9t                         2/2     Running   0          4h39m
fluentd-gke-869wg                                           2/2     Running   0          4h37m
fluentd-gke-d6dvm                                           2/2     Running   0          4h37m
fluentd-gke-scaler-cd4d654d7-cd6f7                          1/1     Running   0          4h38m
fluentd-gke-td5xw                                           2/2     Running   0          4h38m
gke-metrics-agent-5ls22                                     1/1     Running   0          4h38m
gke-metrics-agent-6f4ll                                     1/1     Running   0          4h38m
gke-metrics-agent-hw7h5                                     1/1     Running   0          4h38m
kube-dns-7c976ddbdb-fnzlb                                   4/4     Running   0          4h38m
kube-dns-7c976ddbdb-mmkql                                   4/4     Running   0          4h39m
kube-dns-autoscaler-645f7d66cf-xvxtt                        1/1     Running   0          4h38m
kube-proxy-gke-c-t89jp-default-0-232b2dc0-g0jr              1/1     Running   0          4h38m
kube-proxy-gke-c-t89jp-default-0-232b2dc0-tf91              1/1     Running   0          4h38m
kube-proxy-gke-c-t89jp-default-0-232b2dc0-x98f              1/1     Running   0          4h38m
l7-default-backend-678889f899-8k4dr                         1/1     Running   0          4h39m
metrics-server-v0.3.6-64655c969-hkvxj                       2/2     Running   0          4h38m
prometheus-to-sd-2dgxx                                      1/1     Running   0          4h38m
prometheus-to-sd-642x6                                      1/1     Running   0          4h38m
prometheus-to-sd-7b4cl                                      1/1     Running   0          4h38m
stackdriver-metadata-agent-cluster-level-58686788fc-d2hpc   2/2     Running   0          4h38m
```

**More info:**
This does NOT happen for AKS or EKS.

**Comment by aiyengar2** [comment]
@jiaqiluo this cluster is using `kube-dns`, not `core-dns`. Can you redeploy the Helm chart with `kubeDns.enabled=true` and `coreDns.enabled=false` and see if you still get the same issue for scraping?

Seems like GKE by default still uses kubeDNS, so I'll add a fix to [this issue](https://github.com/rancher/dashboard/issues/1230) in order to ensure that GKE clusters specifically switch the default from scraping coreDNS to scraping kubeDNS.

**Comment by jiaqiluo** [comment]
@aiyengar2  

1. after updating the monitoring with `kubeDns.enabled=true` and `coreDns.enabled=false`, Prometheus show kube-dns in the target list 

2. but there are no endpoints detected for kube-dns and some other targets, we may need to update the selectors in the serverMonioring CRDs for GKE? 

<img width="1272" alt="Screen Shot 2020-09-17 at 4 11 43 PM" src="https://user-images.githubusercontent.com/6218999/93537795-5be15900-f901-11ea-8562-cc19bae5910e.png">

**Comment by aiyengar2** [comment]
@jiaqiluo good catch! This seems like a generic problem with using the kubeDns exporter since it's not being created in the right namespace.

**Comment by jiaqiluo** [comment]
the bug fix is validated with the latest chart  in rancher:`master-8fd81a9b46847317a95ab654ae58053787d57687-head`

steps are the same as the issue provides. 
<img width="725" alt="Screen Shot 2020-09-18 at 5 37 11 PM" src="https://user-images.githubusercontent.com/6218999/93655010-bd72f780-f9d5-11ea-95a6-8cac2e435858.png">
