### ISSUE TITLE
Version shown for an EKS cluster is incorrect

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28953]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

- Deploy a hosted EKS cluster with 1.15 k8s version from Rancher
- Upgrade the k8s version of the cluster in EKS console to 1.16
- The k8s version of the cluster in the EKS console is 1.16
- The k8s version seen on the UI is 1.15
<img width="1266" alt="Screen Shot 2020-09-16 at 7 00 01 PM" src="https://user-images.githubusercontent.com/26032343/93413138-6f35eb00-f853-11ea-823a-c1a8f285df05.png">

- K8s version of the cluster in the API is 1.16 and on an edit cluster is 1.16

**Expected Result:**
k8s version on the Ui should match the cluster's k8s version

**Note:**
- On upgrading the k8s version of the nodegroups, the k8s version on the UI changed to 1.16

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `53cf961efc`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted EKS
- Kubernetes version (use `kubectl version`):

```
1.15 to 1.16
```

**Comment by maggieliu** [comment]
@rmweir is this a UI issue?

**Comment by westlywright** [comment]
So after spending a bit of time digging into this and watching very closely for the update to come in I can say that this is NOT a UI issue. I'm not sure its an issue at all? I tested this on two cluster upgrades. Both created from rancher ui, one 1.15 and 1.16. I upgraded both clusters separately, both via the AWS Console Web UI. Both clusters in the rancher UI updated their versions around ~30 seconds after the cluster finished upgrading in AWS (timing measurement in no way scientific). I verified the updates are coming in correctly over the web socket. Either this is no longer a problem or there is an expectation that the cluster would reflect the updated version faster? But as far as the UI it is working correctly.

**Comment by westlywright** [comment]
Can we retest this? Please make sure that the Cluster is done updating in Amazon, and allow some time for the changes to populate down to the api then out to the UI. The UI reads its cluster version off the upstream spec, if there is some discrepancy please verify the version is updated there before kicking back to UI.

**Comment by sowmyav27** [comment]
**On latest 2.5-head - commit id: `6498b2f4f`**

- Deploy a hosted EKS cluster with 1.15 k8s version from Rancher
- Upgrade the k8s version of the cluster in EKS console to 1.16
- The k8s version of the cluster in the EKS console is 1.16
- The k8s version seen on the UI is 1.16

Closing the issue. Will reopen/log a new one if we hit this issue again.
