### ISSUE TITLE
[Bug]:edit ui-banners , rancher will don't server。

### ISSUE THREAD

**Issue by PmcFizz** [rancher/rancher#28958]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
click  setting
click edit ui-banners

input code `{
banner:{background:red}
}` on  ui-banners

![image](https://user-images.githubusercontent.com/13403284/93456098-d0bb8f80-f90f-11ea-901b-3a9747964396.png)

**Result:**
![image](https://user-images.githubusercontent.com/13403284/93456173-e4ff8c80-f90f-11ea-9771-7b1ab4f40c92.png)

error happen

and don't reload ,login agin error happen again

**Other details that may be helpful:**
start rancher use image 
`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
windows
chrome

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

whatever use input on ui-banners， rancher server should be normally 
@vincent99  Hi   Look this issues。

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/28504
