### ISSUE TITLE
When entering rancher, I go to last Environment instead of default

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2895]
Version - Master

Steps:
1.  Make sure you are unauthenticated
2.  Create multiple Environments
3.  Leave Default as the default login
4.  Go to another environment and add a host
5.  Close window, clear browser stuff
6.  Go back into rancher

Results:
Instead of taking me to Default environment, it takes me to the last one I was in

Expected:
Since we say there is a default, I assumed it would go back to that environment.  Not sure if this is case if you are unauthenticated.  If not maybe we shouldn't have that option.

**Comment by andyshinn** [comment]
Hmm, I've been working on prototyping stuff in Rancher using environments for the last couple weeks and actually like this behavior. I'm not quite sure the distinction of `default` in this case (I assumed it was just the default if you had never navigated to one). But I would find it annoying to have to keep going back to the global default every time I log in.

Soooo is it actually a bug or a *feature*? :smirk_cat:

**Comment by deniseschannon** [comment]
@andyshinn You can set what environment to log in as your `default` in the `Manage Environments` section. So as a user, you can set which environment you want to go to when logging in.

**Comment by vincent99** [comment]
This could be a combination of userprefs not saving before or you're not authenticated so there's only one default env setting that several people could be touching.  But this seems to work OK to me now.  The project you're in is stored in the browser's sessionStorage, so if you're in the same session (which is a window/tab usually) the value will still be there and we'll use the last one you were in.  If that's not set then it looks at the default value.  And if that environment isn't there, then it picks another one, and sets that as the new default value.

**Comment by tfiduccia** [comment]
Version - master 3/22
Verified fixed
