### ISSUE TITLE
Security group information is missing when creating exoscale machine

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2896]
Version - Master 12/02

Steps:
1.  Go to hosting page
2.  Click on Add host
3.  Select exoscale
4.  Put in API key and Secret Key
5.  Select custom for Security Group and select Rancher-master
6.  Click next

Results: Security Group information is now showing up
![image](https://cloud.githubusercontent.com/assets/11514927/11571531/17a61948-99ba-11e5-8f84-cccdfadeb714.png)

Expected:  Security Group info to show up

**Comment by vincentbernat** [comment]
I am able to reproduce this only if I select the first security group as a custom group. If I select another one, it works just fine. I suppose that the `onchange` handler is not firing up. A possible fix would be to take the first custom security group when none is selected, but maybe there is a cleaner way to do that.

I see that the Amazon EC2 template does exactly the same thing. And it has exactly the same problem. I'll welcome any tip on the proper way to fix that.

**Comment by tfiduccia** [comment]
Version - master 3/24
Verified fixed
