### ISSUE TITLE
"can't downgrade" is seen in the k8s version dropdown of a nodegroup in EKS cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28965]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a hosted EKS cluster with k8s 1.15
- After the cluster is deployed successfully, From the EKS console update the k8s version of the cluster to 1.16
- The cluster upgrades to 1.16 in Rancher
- Edit cluster
- The nodegroups are in 1.15
- The nodegroups are in 1.15 k8s version and show in the dropdown `can't downgrade`

<img width="1305" alt="Screen Shot 2020-09-16 at 7 22 14 PM" src="https://user-images.githubusercontent.com/26032343/93512598-60921700-f8d9-11ea-81a8-04732890f4b5.png">

**Expected Result:**
`can't downgrade` should NOT be shown for 1.15 k8s version as it is the one the nodegroup is currently on

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `33f755f18`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted EKS
- Kubernetes version (use `kubectl version`):

```
1.15
```

**Comment by westlywright** [comment]
The UX now does not allow the user to specify a specific version for upgrade. We are now more in line with how aws does it and the user is only presented with an option to upgrade when the node version is behind the cluster. And then you can only match the cluster version.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `c983bb` ui tag: `latest2`**

- Deploy a hosted EKS cluster with k8s 1.15
- After the cluster is deployed successfully, From the EKS console update the k8s version of the cluster to 1.16
- The cluster upgrades to 1.16 in Rancher
- Edit cluster --> User is not given multiple options to upgrade nodegroup's k8s version

<img width="661" alt="Screen Shot 2020-09-25 at 10 49 28 AM" src="https://user-images.githubusercontent.com/26032343/94302937-e8070800-ff21-11ea-85f0-b709c4d37ab1.png">
