### ISSUE TITLE
After deleting a nodegroup from EKS console, the same nodegroup is re created in the cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28967]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a hosted EKS cluster with 2 nodegroups. 
- When the cluster is deployed in EKS console and comes up Active on rancher, from the EKS console, delete one nodegroup. (no update is happening on the cluster at this time)
- No other edit is performed on the cluster from rancher.
- The cluster goes into `updating` state.
- The nodes get deleted, but the node group gets re created.

**Expected Result:**
When no other update happens on the cluster, the deleted nodegroup should NOT get created back

**Other details that may be helpful:**
This is NOT always reproducible

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `33f755`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted EKS
- Kubernetes version (use `kubectl version`):

```
1.15
```

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:master-head` `version 53cf961`

Steps:
Import an EKS cluster with multiple node groups
After cluster is active, in Rancher, edit the cluster
Add logging
Wait for cluster to update
In the EKS console, delete a node group
Wait for cluster to update

Result:
Node group is recreated.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version db8a864`

Steps:
Import an EKS cluster with 2 node groups
After cluster is active, in Rancher, edit the cluster
Add logging
Wait for cluster to update
In the EKS console, delete a node group
Wait for cluster to update

Result:
Node group is deleted from Rancher side. upstreamSpec is synced with 1 node group.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `db8a864f4`**

- Deploy a hosted EKS cluster with 2 nodegroups.
- When the cluster is deployed in EKS console and comes up Active on rancher, from the EKS console, delete one nodegroup. (no update is happening on the cluster at this time)
- No other edit is performed on the cluster from rancher.
- The nodegroup is seen deleted in the EKS console. Edit cluster, and the nodegroup deleted is NOT available in the cluster in Rancher
