### ISSUE TITLE
Multiple k8s version upgrade options available for a nodegroup in an EKS cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28966]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy a hosted EKS cluster with k8s 1.15
- After the cluster is deployed successfully, From the EKS console update the k8s version of the cluster to 1.16
- The cluster upgrades to 1.16 in Rancher
- Edit cluster
- The nodegroups are in 1.15
- In the dropdown, 1.17 and 1.16 options are available.
<img width="1305" alt="Screen Shot 2020-09-16 at 7 22 14 PM" src="https://user-images.githubusercontent.com/26032343/93512929-e615c700-f8d9-11ea-8cba-3f00e161e1e3.png">

**Expected Result:**

- From the EKS console, user can do an `Update` on the nodegroup which will upgrade to the cluster's version (if the cluster is on 1.16) nodegroups can update to 1.16. 
- Update from the EKS console also gives user two options - `Rolling Update` and `Forced update`
- From Rancher option to `update` a node group should be available rather than allowing the user to choose from a dropdown

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `33f755`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted EKS
- Kubernetes version (use `kubectl version`):

```
1.15
```

**Comment by westlywright** [comment]
The UX now does not allow the user to specify a specific version for upgrade any longer. We are now more in line with how aws does it and the user is only presented with an option to upgrade when the node version is behind the cluster. And then you can only match the cluster version.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `c983bb` ui tag: `latest2`**

- Deploy a hosted EKS cluster with k8s 1.15
- After the cluster is deployed successfully, From the EKS console update the k8s version of the cluster to 1.16
- The cluster upgrades to 1.16 in Rancher
- Edit cluster --> User is not given multiple options to upgrade nodegroup's k8s version

<img width="661" alt="Screen Shot 2020-09-25 at 10 49 28 AM" src="https://user-images.githubusercontent.com/26032343/94302937-e8070800-ff21-11ea-85f0-b709c4d37ab1.png">
