### ISSUE TITLE
EKS cluster is stuck when updating mismatched k8s version in both cluster and node group

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#28968]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Import a k8s 1.15 EKS cluster with a k8s 1.15 node group
From EKS console side, upgrade cluster to 1.16
Wait for update/sync on Rancher side
From Rancher side, upgrade k8s 1.17 and upgrade node group to 1.16 in the same edit

**Result:**
Cluster is stuck in updating state:
![image](https://user-images.githubusercontent.com/57409052/93514046-90421e80-f8db-11ea-933e-026c1617a070.png)
User is unable to edit k8s version to correct this:
![Screen Shot 2020-09-17 at 11 47 50 AM](https://user-images.githubusercontent.com/57409052/93514093-a0f29480-f8db-11ea-9362-ee269955df69.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher\rancher:master-head` `version 53cf961`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported

**Comment by aaronRancher** [comment]
Deleting the cluster from Rancher and reimporting it will reset the k8s versions on edit.
Cluster is no longer stuck updating on reimport.

**Comment by cbron** [comment]
@aaronRancher did the first upgrade finish completely ? Or was it still updating.

**Comment by aaronRancher** [comment]
@cbron Neither upgrade completed. The cluster did not enter updating when viewed in EKS console. From the console side, the cluster had not changed at all.

**Comment by sowmyav27** [comment]
A similar issue - **On master-head - commit id: `33f755f1`**

- Deploy a hosted EKS cluster - with k8s 1.15
- When the cluster comes up Active, Edit the k8s version from EKS console of the cluster to 1.16
- When the sync has finished to Rancher, the cluster in Rancher is now in 1.16 but the node groups are in 1.15 k8s version
- Edit cluster and change the k8s version to 1.17
- Error seen on the cluster
<img width="1453" alt="Screen Shot 2020-09-17 at 4 10 59 PM" src="https://user-images.githubusercontent.com/26032343/93537781-5421b480-f901-11ea-9658-43313388d89b.png">

- User is NOT able to come out of this state

**Comment by cbron** [comment]
Believe this needs a UI component before it can be moved to test. @rmweir can link/create the UI issue.

**Comment by rmweir** [comment]
There is already validation for this in the eks-operator. This results in a controller error. I was working on implementing an API level error, but we realized some edge case that make it complicated and would probably lead to some bad side effects. I think the better fix would be to not allow the users to go from 1.a to 1.b in the UI unless the effective versions of the nodegroups are all 1.a or equal to the cluster version. The other fix would be to simply allow someone to downgrade the version after it has been updated (maybe).

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version df9345c`

Node group k8s dropdown has been removed.
If cluster k8s version is `1.16` and node group k8s version is `1.15`, an option is given to upgrade node groups.
![Screen Shot 2020-09-25 at 11 01 22 AM](https://user-images.githubusercontent.com/57409052/94301247-1800dc00-ff1f-11ea-85c1-9771e32151b6.png)
If the user selects a new k8s version for the cluster, a note will appear under the node group k8s version:
![Screen Shot 2020-09-25 at 10 53 25 AM](https://user-images.githubusercontent.com/57409052/94302168-a4f86500-ff20-11ea-812c-0b8ef0e06109.png)
![Screen Shot 2020-09-25 at 10 46 50 AM](https://user-images.githubusercontent.com/57409052/94302010-62cf2380-ff20-11ea-9a97-2a9f4e9277d0.png)

**Comment by aaronRancher** [comment]
Reopening, as this behavior is still seen when cluster k8s version is updated to `1.17` when node group version is `1.15`. We should not allow users to upgrade k8s version when the node group version is not the same as current k8s version.
![Screen Shot 2020-09-25 at 11 29 32 AM](https://user-images.githubusercontent.com/57409052/94305952-ec81ef80-ff26-11ea-90e9-7a6091fe2700.png)

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 4ac3a87`

Cluster can only be upgraded 1 version at a time:
![Screen Shot 2020-09-25 at 5 30 59 PM](https://user-images.githubusercontent.com/57409052/94325798-0d613980-ff55-11ea-8ed2-325552726a5e.png)

When node group k8s version is behind cluster k8s version, cluster k8s version cannot be upgraded:
![Screen Shot 2020-09-25 at 5 29 48 PM](https://user-images.githubusercontent.com/57409052/94325807-21a53680-ff55-11ea-9b47-2725f2146f1b.png)
