### ISSUE TITLE
[Monitoring V2] Switch from using rancher/busybox to rancher/library-busybox

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#28978]
As documented in https://github.com/rancher/image-mirror/pull/35#discussion_r490596648, the name for the image has changed and needs to be updated in the charts.

This image is used by both the `grafana` subchart and `rancher-pushprox` chart.

**Comment by jiaqiluo** [comment]
This is validated on Rancher:`master-db8a864f4acf6f7e70727a8ab9bed029b1c20220-head` with the lastest chart. 

The image `rancher/library-busybox:1.31.1` is used.
 
![image](https://user-images.githubusercontent.com/6218999/93671893-93641880-fa5b-11ea-849d-70dae6ba16a1.png)
