### ISSUE TITLE
Enable Local Cluster Upon upgrade to 2.5

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28979]
Upon upgrading to 2.5, local cluster should be enabled. If user forces to set the addLocal=off, then there should be a warning and Rancher shouldn't start.

**Comment by sowmyav27** [comment]
**Using master-head - commit id: `f1a410a97`**

**HA install**

- On a fresh install of master with `f1a410a97`
- rancher fails to come up. Error in logs:

```
docker logs ee8d1f022420
2020/09/21 18:07:55 [INFO] Rancher version f1a410a97 (f1a410a97) is starting
2020/09/21 18:07:55 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:false Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Agent:false Features:}
2020/09/21 18:07:55 [FATAL] add-local flag must be set to 'true', see Rancher 2.5.0 release notes for more information
```

**Upgrade from 2.4.8 to master-head**

- Deploy a HA in 2.4.8 with `--set addLocal="false"`
- No local cluster is available in rancher
- Deploy a custom cluster
- Upgrade to master-head and do not set `addLocal` flag
- local cluster is available in rancher
- Deploy an EKS cluster. EKS cluster comes up Active. 

**Single node install** 

- bring up rancher - `docker run -d --privileged --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:master-head --add-local=false`
- Rancher logs show:

```
2020/09/21 17:17:44 [FATAL] add-local flag must be set to 'true', see Rancher 2.5.0 release notes for more information
```

**Comment by Exagone313** [comment]
How do you start 2.5.x without a local cluster?
