### ISSUE TITLE
Adding a new restricted admin role

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28977]
For Rancher 2.5 local cluster needs to be enabled for most of the features to work. In order to address the security concern around admin having access to local cluster, there is a need to introduce a new restricted admin role that has access to all downstream clusters except local cluster.

Scenarios to consider:
1. I turn on the new restricted-admin role
2. That role gives people with access to it the permission to create GlobalRoleBindings and GlobalRoles
3. If a user with this role creates a GlobalRole that gives access to “/” (or simply “pods” for a more direct example) and then assigns that role to someone (or themselves) and they get access to those additional resources in the local cluster, it is a bad privilege escalation bug.

Similarly, if the restricted-admin user is able to create clusterRole-template-bindings in the local cluster, they would be able to assign themselves as cluster-owner in the cluster and it is again privilege escalation.

we might need a restrict-local-cluster-rbac flag that the user supplies in place of turning off local cluster. Its function would be to cause our rbac controllers to not “realize” crtb/prtbs in the local cluster

**Comment by dramich** [comment]
There is a new restricted-admin role added to rancher. It will have admin access to all rancher CRD types except PRTBs and CRTBs with limited access to being able to create GRBs. For GRBs it can only assign a GRB that has rules the restricted admin already possesses. This will allow them to create new users and add them to rancher but not much else. 

The restricted-admin DOES NOT have access to any native Kubernetes types in the local cluster. This includes but is not limited to secrets, namespaces, RBAC objects etc. 

The restricted-admin DOES have full admin access in all downstream clusters. 

The restricted-admin can create other restricted-admins as that would be equal to their level of access.

**Comment by dnoland1** [comment]
Started testing and hit an issue deploying helm chart with this option turned on. See https://github.com/rancher/rancher/issues/29186 . So wasn't able to get too far in trying this out.

**Comment by dnoland1** [comment]
Hit https://github.com/rancher/rancher/issues/29279 while testing. Need to make sure we prevent the restricted admin from being able to modify or delete any of the rancher related workloads, namespaces, etc. in the local cluster.

**Comment by dnoland1** [comment]
Getting an error when creating a cluster as a restricted admin. Filed here - https://github.com/rancher/rancher/issues/29324

**Comment by dnoland1** [comment]
From my testing of this, there are still some rough edges, in particular the user experience (see https://github.com/rancher/rancher/issues/29325). However, technically it appears to accomplish the job of protecting the `local` cluster from undesired modifications. I'm okay closing this out.
