### ISSUE TITLE
Allow one main Rancher install to manage multiple downstream Rancher installs with local cluster

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28983]
There is a need to all for a main Rancher install that manages multiple downstream Rancher installs with local cluster.

**Comment by dnoland1** [comment]
I've hit a few issues with having Rancher v2.5.0-rc2 manage Rancher 2.4.8 clusters which I have reported here:

- https://github.com/rancher/rancher/issues/29238
- https://github.com/rancher/rancher/issues/29239

**Comment by dnoland1** [comment]
Having better luck with using Rancher 2.4.8 to manage Rancher 2.5.0-rc clusters.

**Comment by dnoland1** [comment]
I'm okay closing this out for now and will go with the strategy of using Rancher v2.4.8 to manage Rancher v2.4.x/v2.5.x clusters. Once all managed clusters are on 2.5.x, will upgrade main Rancher to v2.5.x. If I run into any issues with us, will open new GH issues.
