### ISSUE TITLE
Because the View boxes don't look like buttons, it was confusing on how to select the default.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#28986]
Issue:  The first time I get into Rancher I have to select a default view & neither one of the views is selected by default.  So the continue button stays grey and I'm not sure how to fix it.  The default view boxes don't say I need to click on one?
After I select one is highlighted blue.
![image](https://user-images.githubusercontent.com/11514927/93528819-c8ebf300-f8ef-11ea-91c7-4dc8be9bfb83.png)

I think we need to make this so that the options either have a radio option available or something?

**Comment by lvuch** [comment]
@tfiduccia @vincent99 As discussed on Monday radio buttons next to the text would solve this

**Comment by deniseschannon** [comment]
Radio buttons were added

**Comment by sowmyav27** [comment]
**Login screen once rancher is deployed on master-head - commit id: `27000be7`**

<img width="854" alt="Screen Shot 2020-09-26 at 4 56 35 PM" src="https://user-images.githubusercontent.com/26032343/94352396-89bd5080-0019-11eb-8fae-a8d4ba38588a.png">
