### ISSUE TITLE
Error while upgrading the k8s version of an EKS v1 cluster upgraded from 2.4.8 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28999]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- deploy an EKS v1 on 2.4.8 in 1.16 k8s version
- Upgrade to master-head
- Edit cluster, upgrade k8s version of the cluster to 1.17
- Save changes made
- Error on the UI
- API Request sent has an error in the response
- Response: `{"baseType":"error","code":"InvalidBodyContent","message":"cannot modify EKS subnets after creation","status":422,"type":"error"}`

**Expected Result:**
User should be able to edit a v1 EKS cluster

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `8fd81a9b`
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS v1
- Kubernetes version (use `kubectl version`):

```
1.16 to 1.17
```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version e9a98a3`

Steps:
deploy an EKS v1 on 2.4.8 in 1.16 k8s version
Upgrade to master-head
Edit cluster, upgrade k8s version of the cluster to 1.17
Save

Result:
Cluster can be edited and upgraded:
![Screen Shot 2020-09-23 at 11 30 59 AM](https://user-images.githubusercontent.com/57409052/94054285-51efa800-fd90-11ea-88b6-ab47a8c040b3.png)
