### ISSUE TITLE
[2.4] Rancher panic when draining a node in the API 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#28998]
https://github.com/rancher/rancher/issues/28905

**Comment by sowmyav27** [comment]
**Verified on 2.4-head commit id: `928e9ce7e`**

- Deploy a DO rke cluster - 1 node all roles and 1 worker node.
- Drain the worker node from API UI. 
- Request sent:

```
{
"deleteLocalData": false,
"force": false,
"gracePeriod": -1,
"ignoreDaemonSets": null,
"timeout": 120
}
```
- Request sent in Rancher logs:
```
Draining node sowmya-test-24-w-1 in c-xdk88 with flags --delete-local-data=false --force=false --grace-period=-1 --ignore-daemonsets=true --timeout=120s
```
- Node is drained successfully. No panic seen on the rancher server.
