### ISSUE TITLE
Snapshot and Backup Service

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#29]
Rancher should support local storage volumes (i.e., storage volumes built on local disks.) Rancher storage volumes provide the following capabilities:

1.	Snapshot. A crash-consistent snapshot of the volume.
2.	Backup. Store a copy of the snapshot on secondary storage. Only changed blocks should be copied.
3.	Restore. Reconstruct a new volume from a backup stored in secondary storage.
4.	Rollback. Stop container, and restart the container with an older version of the volume.

We will rely on thin pools in Linux device mapper to implement local storage volumes for Docker. Note that in Rancher storage volumes are not mirrored. Losing a Linux host will result in data loss. The user can restore from a snapshot backup, but they will lose the latest changes that have not been backed up.

Rancher will format newly create storage volumes as ext4 file systems before handing them over to Docker containers.

Backup are snapshot functions are implemented as follows:

1.	Volume snapshots can be backed up to secondary storage, which can be object storage or NFS shares
2.	Backup is performed incrementally from local disk to secondary storage (only changed blocks are copied)
3.	A snapshot backup is stored as a directory of 2MB segments
4.	Each 2MB segment can be shared among multiple snapshot backups
5.	When a snapshot backup is deleted, unused 2MB segments can be GC’ed
6.	Volumes can be reconstituted from a snapshot backup
7.	To replicate a volume from one server to another, simply take a snapshot, backup the snapshot, and reconstitute the snapshot on the target server

The following figure illustrates how 3 snapshot backups are stored in the secondary storage. The 3 snapshots shared some 2MB segments. Both the directory and 2MB segments are stored in the secondary storage.

![snapshots](https://cloud.githubusercontent.com/assets/9485278/5604293/03ca52a8-9368-11e4-99a9-70469f9d49b3.png)

**Comment by vincent99** [comment]
302 http://github.com/rancher/convoy
