### ISSUE TITLE
Monitoring V2 - installation is broken 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#29007]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
install Monitoring V2 into a downstream RKE cluster 

**Result:**

the `rancher-monitoring-crd` chart is installed, but the `rancher-monitoring` fails because it cannot find the `rancher-monitoring-crd`. 
```
helm --debug install --create-namespace=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-9.4.200.yaml --version=9.4.200 --wait=true rancher-monitoring /home/shell/helm/rancher-monitoring-9.4.200.tgz
install.go:172: [debug] Original chart version: "9.4.200"
install.go:189: [debug] CHART PATH: /home/shell/helm/rancher-monitoring-9.4.200.tgz
Error: execution error at (rancher-monitoring/templates/validate-install-crd.yaml:16:7): Required CRDs are missing. Please install the rancher-monitoring-crd chart before installing this chart.
helm.go:94: [debug] execution error at (rancher-monitoring/templates/validate-install-crd.yaml:16:7): Required CRDs are missing. Please install the rancher-monitoring-crd chart before installing this chart.
```

**Comment by aiyengar2** [comment]
Was not able to reproduce the bug listed in the logs, but found that the chart installation was broken for a different reason in https://github.com/rancher/charts/pull/668; the annotations on the alertmanager secret to direct helm to create it on a pre-install were missing, the chart deployment would consistently fail.

Tested out the chart deployment locally after making the change and it seems to work on a fresh cluster now without the error indicated by the logs on this ticket; once this is merged in, can you recheck @jiaqiluo ?

**Comment by jiaqiluo** [comment]
This is not reproducabe in the latest mster-head and the latest chart. 
Closed this issue for now, and will reopen if it happens again.
