### ISSUE TITLE
helm-operation pods deployed and in Unavailable state in downstream clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29002]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a new HA setup - RKE cluster.
- Deploy a downstream custom RKE cluster
- In the cluster --> System project
- Helm-operation pods are in Unavailable state.
<img width="1455" alt="Screen Shot 2020-09-18 at 12 05 43 PM" src="https://user-images.githubusercontent.com/26032343/93640921-3fe8c080-f9b0-11ea-9d36-b7c80fe6632a.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `8fd81a9b`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom rke - 5 nodes - 1 etcd, 1 control and 3 worker nodes
- Kubernetes version (use `kubectl version`):

```
1.19
```

**Comment by maggieliu** [comment]
related to : https://github.com/rancher/rancher/issues/28876

**Comment by ibuildthecloud** [comment]
@sowmyav27 helm operation pods are created by (shockily) doing helm operations in the cluster.  So rancher should not be doing any helm operations by default in the downstream clusters.  If it is, that is definitely a bug. In this scenario did you manually install any charts in the downstream cluster yourself as part of testing? Specifically did you go to the apps/catalog screen in the vue UI for the RKE custom cluster and install anything such as monitoring/logging?

Also what would be help, if you can reproduce this, is if you show the "Recent Operations" screen from the Apps page in vue.  That would show more details about the operations as what they were trying to do and also you can click the actions button and get the logs for them.

**Comment by sowmyav27** [comment]
On master-head `5ad6fdbb` - 

- Deploy a downstream cluster (custom cluster 3 nodes all roles)
- No helm operation pods seen in the cluster --> System project
- Deploy CIS v2 app from Dashboard in the custom cluster
- `helm-operation-l94g9` pod seen in `Succeeded` state in downstream cluster --> System project workloads page.
- Deploy backup restore and logging apps, helm-operation pods seen in `Succeeded` state in the custom cluster
-  "Recent Operations" screen from the Apps page in vue:
<img width="1668" alt="Screen Shot 2020-09-20 at 11 47 43 AM" src="https://user-images.githubusercontent.com/26032343/93719393-1f973e00-fb37-11ea-91f0-14994047f1c5.png">

**Comment by ibuildthecloud** [comment]
@soumyalj Yes, if an apps fails to install the helm-operator is left in an unready state so that the logs are available after the fact to debug.  They will be deleted after 1 hour.

**Comment by sowmyav27** [comment]
Closing the issue.

**Comment by tdubb123** [comment]
so any idea why helm operation pods failed? I got same issue deploying rancher on gke with helm
