### ISSUE TITLE
Not able to list v2 apps/repos/charts on a k8s 1.14 cluster 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29001]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a 1.14 cluster on rancher: v2.3.3
- Upgrade rancher to latest master-head
- Navigate to Dashboard
- Go to Apps
- v2 Apps, charts and Repos are NOT listed
<img width="664" alt="Screen Shot 2020-09-18 at 12 52 43 PM" src="https://user-images.githubusercontent.com/26032343/93639469-e2ec0b00-f9ad-11ea-9ac5-af9da2530aee.png">

**Expected Result:**
v2 Apps, charts and Repos should be available

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3 to master-head - commit id: `8fd81a9`
- Installation option (single install/HA): single node install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom RKE aws nodes
- Kubernetes version (use `kubectl version`):

```
1.14
```

**Comment by sangeethah** [comment]
This issue is not seen on 1.16 clusters  in 2.3.3 .

Deploy a 1.16 cluster on rancher: v2.3.3
Upgrade rancher to latest master-head
Navigate to Dashboard
Go to Apps
Able to see repos and charts dispalyed.

**Comment by deniseschannon** [comment]
Can you try upgrading to 1.16 in this scenario to see if the charts show up after?

**Comment by sowmyav27** [comment]
**To Validate:**

- Deploy a 1.14 cluster on rancher: v2.3.3 (RKE1, DO Node driver - 1 etcd/1 control and 1 worker nodes)
- Upgrade rancher to latest master-head
- Navigate to Dashboard
- Go to Apps & Marketplace
- v2 Apps, charts and Repos are NOT listed
- Upgrade to `v1.16.10-rancher2-2` (Changing in cluster.yml
- Go to Apps & Marketplace
- charts and Repos should be listed.

**Comment by thehejik** [comment]
Retested once again with upgraded RKE1 DO cluster upgraded in `rancher:master-head bfdeb22` from v1.14 to `v1.16.15-rancher1-4` (Edit Cluster -> Edit as YAML). The cluster became active and I was also able list v2 charts and repos.

Closing.
