### ISSUE TITLE
Grouping/filtering hosts by label

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2902]
It would be useful to be able to filter and/or group the hosts on the InfraStructure/Hosts page by host labels. For example, if I have a "role" label defined on some hosts, I would like to group all the hosts that have the same value for the "role" label into a visually distinct group. Another example would be to only show hosts that have a specific label and value combination. Simple globbing on the value would be nice to have.

**Comment by dahendel** [comment]
+1 I am going through this right now in our infrastructure testing environment. Lots of machines very cluttered.

**Comment by hwinkel** [comment]
:+1:

**Comment by deniseschannon** [comment]
This is actually a duplicate of https://github.com/rancher/rancher/issues/1824
