### ISSUE TITLE
Changes made from the EKS console side will get lost , when there is a change made from rancher server side before the sync interval

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29023]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a hosted EKS cluster with 2 nodegroups.
- When the cluster is deployed in EKS console and comes up Active on rancher, from the EKS console, delete one nodegroup. (no update is happening on the cluster at this time)
- Do an edit on the cluster from Rancher immediately. (within the 5 min window before the sync happens) 
- Enable logging types
- The cluster goes into updating state.
- When the cluster comes up Active, the nodegroup is NOT deleted. But the logging type is enabled on the cluster

**Other details that may be helpful:**
This is happening because any edit from Rancher will override the edit in EKS console, if done within the 5 min window.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `db8a864f4`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted EKS
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by deniseschannon** [comment]
If this is part of the design and nothing can be done cause of the 5 min window, let's make sure to document this.

**Comment by cbron** [comment]
This is in review, will be merged soon.
