### ISSUE TITLE
[Logging v2] enabling control plane nodes in Airgap setup I ended up with error on the additionalLoggingResources configcheck workload

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29025]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install Rancher `v2.5.0-alpha4` single node Airgap
- In the local cluster (k3s) go to Dashboard
- Install the `rancher-logging` app enabling the Control Plane Logs chart option.

**Result:**

- `rancher-logging` gets installed but the additionalLoggingResource has a configcheck issue and workloads are not created

Seems like the workloads are trying to pull a newer image from upstream **banzaicloud/fluentd:v1.11.2-alpine-3**
 
`ImagePullBackOff: Back-off pulling image "banzaicloud/fluentd:v1.11.2-alpine-3"`

`rancher-images.txt` only lists `rancher/banzaicloud-fluentd:v1.11.2-alpine-2`

**Other details that may be helpful:**

**Environment information**
- Rancher version: `v2.5.0-alpha4`
- Installation option: Single Rancher Airgap

**Comment by paynejacob** [comment]
https://github.com/rancher/charts/pull/671

**Comment by izaac** [comment]
Reopening there's a registry issue to be fixed in `alpha5` #29026

**Comment by paynejacob** [comment]
https://github.com/rancher/charts/pull/691

**Comment by izaac** [comment]
Rancher version: `v2.5.0-rc1`

https://github.com/rancher/rancher/issues/29026#issuecomment-698583479

This is now working.
