### ISSUE TITLE
convoy-gluster not able to start after having a previous convoy-gluster running

### ISSUE THREAD

**Issue by amalagaura** [rancher/rancher#2903]
Recreating issue from https://github.com/rancher/rancher/issues/2893. Probably related to https://github.com/rancher/rancher/issues/2796, but I am trying with different storage-pool and volume names.

I was recreating gluster and convoy-gluster because I needed to recreate gluster and now I am unable to get convoy-gluster started again.

I tried creating different names for the storage-pool and volumes but no luck either. I tried rebooting but nothing is cleared and the convoy-gluster volumes does not start.

```
12/3/2015 4:22:29 PMtime="2015-12-03T21:22:29Z" level=debug msg="Volume gluster-volume is being mounted it to /var/lib/rancher/convoy/convoy-gluster-5fb86e34-64fb-4e60-91eb-31511b36d2f7/glusterfs/mounts/gluster-volume, with option [-t glusterfs]" pkg=util
12/3/2015 4:22:30 PMtime="2015-12-03T21:22:30Z" level=debug msg="Cleaning up environment..." pkg=daemon
12/3/2015 4:22:30 PMtime="2015-12-03T21:22:30Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/gluster-volume /var/lib/rancher/convoy/convoy-gluster-5fb86e34-64fb-4e60-91eb-31511b36d2f7/glusterfs/mounts/gluster-volume], output Mount failed. Please check the log file for more details.\n, error exit status 1"
12/3/2015 4:22:30 PM{
12/3/2015 4:22:30 PM	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/gluster-volume /var/lib/rancher/convoy/convoy-gluster-5fb86e34-64fb-4e60-91eb-31511b36d2f7/glusterfs/mounts/gluster-volume], output Mount failed. Please check the log file for more details.\n, error exit status 1"
12/3/2015 4:22:30 PM}
12/3/2015 4:22:30 PMtime="2015-12-03T21:22:30Z" level=info msg="convoy exited with error: exit status 1"
12/3/2015 4:22:30 PMtime="2015-12-03T21:22:30Z" level=info msg=Exiting.
```

**Comment by haswalt** [comment]
Any news on this? I removed my old convoy stack as the catalog template was deleted. Now my setup is broken because I cant create a new convoy gluster setup.

**Comment by cjellick** [comment]
How's it broken @haswalt? Anything interesting in the logs? We did fix some issues around redeploying the stack. So, with today's templates, you should be able to deploy gluster and convoy, delete, and redeploy.

Unfortunately, the fix won't work if you deployed a very early version of the template. There may be some manual cleanup required on your hosts. Specifically, with convoy _not_ installed, you'd need to delete the /etc/docker/plugins/convoy-gluster.spec file and then restart docker.

**Comment by haswalt** [comment]
I deployed the first version of the template when it was released so having to attempt you second fix. Is there anything that needs removing from rancher itself to properly clean up the old convoy?

**Comment by cjellick** [comment]
@haswalt no, assuming you deleted the stacks for convoy and gluster

**Comment by haswalt** [comment]
I actually just tried clearing out my db, plugins on nodes and any lingering rancher config/volumes on nodes and recreated my env. Still can't create a new convoy-gluster stack due to the error above.

Using convoy-glusterfs v0.1 and glusterfs v3.7.5

**Comment by yobasystems** [comment]
Any progress on this? The convoy gluster is slightly broken, but i must add a key feature for rancher.

**Comment by deniseschannon** [comment]
@haswalt It looks like from @cjellick first comment, you'll need to manually cleanup the hosts and restart docker on the hosts. Did you do that as well? 

@yobasystems Did you also try what @cjellick has indicated on how to clean up your hosts?

**Comment by yobasystems** [comment]
@deniseschannon Yes i tried cleaning the hosts with
    sudo rm -R /etc/docker/plugins/convoy*
    sudo rm -R /var/lib/rancher/convoy*

**Comment by haswalt** [comment]
@deniseschannon I did the same as @yobasystems when I attempted. Trying with the latest version of the template on 0.56 as well.

**Comment by haswalt** [comment]
I can confirm that it now works with the latest catalog version on rancher 0.56.0

**Comment by yobasystems** [comment]
@haswalt Was this with fresh install or upgrade? Hosts or Server?

**Comment by haswalt** [comment]
I upgraded my cluster this morning. 

Upgraded server from 0.51.0 to 0.56.0, hosts left to upgrade the agents themselves.

I'm running my cluster as:

Rancher Server
MySQL Server
Zookeeper Cluster / Redis

3 Host nodes

**Comment by deniseschannon** [comment]
@yobasystems Let me know if/when you get this working. I'm leaving the issue open until you have confirmed that it's working for you.

**Comment by deniseschannon** [comment]
@yobasystems If you still can't get this working, please re-open. Please make sure to use the latest version of Rancher (v0.56.1) and v0.2 template of convoy-gluster

**Comment by yobasystems** [comment]
Sorry i havent had chance to re try, i'm going to have a look now and rebuild from scratch all hosts and rancher server.

**Comment by yobasystems** [comment]
running into differant problems now. Maybe related to [#3117](https://github.com/rancher/rancher/issues/3117)

**Comment by christianwiedemann** [comment]
Hi, 
I have the same problem with a fresh install. Rancher (v0.59.1) and v0.2 template of convoy-gluster.
Getting: 
r-8e11aa91-9ce0-413a-a865-da9faa6b5a4b/glusterfs/mounts/my_vol, with option [-t glusterfs]" pkg=util
6.3.2016 18:13:54time="2016-03-06T17:13:54Z" level=debug msg="Cleaning up environment..." pkg=daemon
6.3.2016 18:13:54time="2016-03-06T17:13:54Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/my_vol /var/lib/rancher/convoy/convoy-gluster-8e11aa91-9ce0-413a-a865-da9faa6b5a4b/glusterfs/mounts/my_vol], output Mount failed. Please check the log file for more details.\n, error exit status 1"
6.3.2016 18:13:54{
6.3.2016 18:13:54	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/my_vol /var/lib/rancher/convoy/convoy-gluster-8e11aa91-9ce0-413a-a865-da9faa6b5a4b/glusterfs/mounts/my_vol], output Mount failed. Please check the log file for more details.\n, error exit status 1"
6.3.2016 18:13:54}
6.3.2016 18:13:54time="2016-03-06T17:13:54Z" level=info msg="convoy exited with error: exit status 1"

**Comment by deniseschannon** [comment]
@christianwiedemann I have had no issues with installing convoy-gluster. Could you open a new issues and provide more details on your OS/setup?

**Comment by clintbeacock** [comment]
@christianwiedemann: I'm getting the same errors with v0.2

In my case, I think the convoy setup got interrupted/did not complete the first time, and I can't get it going.

Please post back if you find a workaround.

**Comment by bacheson** [comment]
same problem ... clean install w/ Rancher v0.63 and convoy-agent v0.3.0

 /var/lib/rancher/convoy/convoy-gluster-f2e9f379-ccad-4d4d-8b5f-2204cb222da2/glusterfs/mounts/developer-wangbing-data], output Mount failed. Please check the log file for more details.\n, error exit status 1"
3/17/2016 9:08:16 PM{
3/17/2016 9:08:16 PM	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/developer-wangbing-data /var/lib/rancher/convoy/convoy-gluster-f2e9f379-ccad-4d4d-8b5f-2204cb222da2/glusterfs/mounts/developer-wangbing-data], output Mount failed. Please check the log file for more details.\n, error exit status 1"
3/17/2016 9:08:16 PM}

**Comment by djmaze** [comment]
Same problem here, same versions as @bacheson.

**Comment by renaudManda** [comment]
+1 but with rancher 1.0 and convoy-agent v0.3.0

just something strange in the UI furing the creation of the convoy-agent I see convoy-agent v0.2.0 (in template version) but convoy-agent v0.3.0 is in fact used.

**Comment by clintbeacock** [comment]
Same result here.  Rancher v1.0.0

I haven't had it happen in a while in my local vms, but just tried on a couple live servers and it won't get going.

**Comment by avoinea** [comment]
+1 

Same here. Rancher v1.0.0, convoy-agent:v0.3.0, docker 1.10.3

**Comment by avoinea** [comment]
Somehow I managed to make it work after cleaning up:

```
/etc/docker/plugins/convoy*
/var/lib/rancher/convoy
```

It is possible to conflict with `convoy-nfs`

The think is that it happen only when deployed with `rancher-compose` CLI, so maybe the exported ymls have issues.

**Comment by AgustinCB** [comment]
Same problem here.

We weren't able to delete 

/etc/docker/plugins/convoy*
/var/lib/rancher/convoy

They were busy, probably in use by docker, even though gluster and convoy-gluster stacks were deleted. 

We tried replacing the servers to remove that data without turning out the services, but it didn't work either.

**Comment by AgustinCB** [comment]
OK. I fixed it by manually creating the subdirectory in the brick (/data/glusterfs/brick1) and the volume (I did it with replica 3, since the stack has 3 containers) using gluster. It was the only way for me.

**Comment by rawmind0** [comment]
In my case, the problem was with glusterfs cluster. 

I don't know why, because the package has retain_ip: true and it shouldn't, but 2 of 3 containers of glusterfs server change them ip's and the glusterfs cluster was not able to get reconfigured correctly. Only one server of the cluster had the glusterfs info (which retained it ip), and the 2 news gets isolated from the cluster. 

I fixed it by doing a login into glusterfs (which retain it ip) and adding the "new" peers, and the "new" replicas bricks to my volumes. convoy-gluster started to work again.

**Comment by deniseschannon** [comment]
This is no longer an issue. 

I was able to launch convoy-gluster (v0.2) with glusterfs (3.7.9-rancher1) using v1.1.0-dev4 on RancherOS v0.4.5 hosts. After deleting the services, I was able to re-add glusterfs and convoy-gluster with no issues. 

There was a known issue with the very first version of convoy-gluster that was causing this issue, that is no longer an issue. Please open a new bug if anyone is still facing issues with this issue.
