### ISSUE TITLE
App in dashboard - discrepancy in RBAC around built-in roles and APP's CRDs. Cluster member is not able to deploy apps.

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#29038]
This table is from https://github.com/rancher/rancher/issues/28861#issuecomment-693572886

Type | Cluster Owner | Cluster Member | Project Owner | Project Member
---|---|---|---|---
clusterrepo.catalog.cattle.io | CRUD | R | R | R
operation.catalog.cattle.io | R | R | R | R 
release.catalog.cattle.io | R | R | R | R
app.catalog.cattle.io (still to be completed/added) | R | R | R | R

on rancher:`master-9addfe297070f85eb3020d0e54571adaa438ccec-head` docker install, we can confirm that the permission for  `clusterrepo.catalog.cattle.io` is applied as the table requires. 

But we see the following problem for `operation.catalog.cattle.io`:
- as a standard user,  cluster member, go to dashboard -> apps -> charts -> deeply any app, for example monitoring
- the UI will show the following error 
<img width="953" alt="Screen Shot 2020-09-20 at 12 02 09 PM" src="https://user-images.githubusercontent.com/6218999/93720831-9c7ae580-fb40-11ea-9e82-af3feafc7448.png">

- but if we log in as cluster owner/ admin, we can see there is a helm-operation pod created and in failed state, the logs of the pods says it fails because the cluster member does not have permission to get servericeaccounts in the `cattle-monitoring-system` namespace 

<img width="1866" alt="Screen Shot 2020-09-20 at 12 02 47 PM" src="https://user-images.githubusercontent.com/6218999/93720853-bc120e00-fb40-11ea-9349-909ae6b467db.png">

- if the cluster member can only Read the `operation.catalog.cattle.io`, the above pod should NOT be created.

**Comment by mrajashree** [comment]
For the two issues described above:
1. Cluster-member only gets get/list/watch permissions on operations and releases from the projects they are part of. I think @ibuildthecloud is adding in support for letting users select a project before installing an app, that way the cluster-member will have to create a project (or be added to one) and install app in it. That I think will resolve the schema error. cc @maggieliu 
2. The [roletemplates only have get/list/watch permissions](https://github.com/rancher/rancher/pull/28991/files#diff-cf8ade09cc844032ba6e10f1cc4243de) on operations for all non cluster-owner roles. But the operation CR gets created by [rancher controller](https://github.com/rancher/rancher/blob/master/pkg/catalogv2/helmop/operation.go#L551) (that runs as admin) on helm install. So I believe with the RBAC permissions from the table, the cluster-member still cannot create an operation CR directly. But it gets created for it. cc @deniseschannon

**Comment by maggieliu** [comment]
Yep, @ibuildthecloud is working on #1. Need Darren/Denise to confirm whether or not the second issue/behavior is problematic or not.

**Comment by maggieliu** [comment]
Confirmed #2 is expected behavior.

**Comment by jiaqiluo** [comment]
> 1. Cluster-member only gets get/list/watch permissions on operations and releases from the projects they are part of. I think @ibuildthecloud is adding in support for letting users select a project before installing an app, that way the cluster-member will have to create a project (or be added to one) and install app in it. That I think will resolve the schema error. cc @maggieliu

This is not working.

  
**Steps to reproduce (least amount of steps as possible):**
I see this happens in the latest-master head 67e24f2 
- log in as a cluster member, create a project
- go to dashboard -> go to the monitoring installation page
- I need to set the target project then click install
- an error shows in UI: `the server rejects our request due to an error in our request (get namespaces)`
<img width="1147" alt="Screen Shot 2020-09-22 at 4 10 04 PM" src="https://user-images.githubusercontent.com/6218999/93947461-9a578900-fcf0-11ea-9637-426d9f8b2302.png">

- also notice the namespace `cattle-monitoring-system` is created in the project, but NO helm-operation pod is created
- try to install the app again, this time there is NO option for setting the project
- click install, a helm-operation pod is created in the system-project, and it fails with the following logs ("u-lkgx6" is the cluster member's id)

```
helm --debug install --create-namespace=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-9.4.200.yaml --version=9.4.200 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-9.4.200.tgz
install.go:172: [debug] Original chart version: "9.4.200"
install.go:189: [debug] CHART PATH: /home/shell/helm/rancher-monitoring-crd-9.4.200.tgz
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: clusterroles.rbac.authorization.k8s.io "rancher-monitoring-crd-manager" is forbidden: User "u-lkgx6" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
helm.go:94: [debug] clusterroles.rbac.authorization.k8s.io "rancher-monitoring-crd-manager" is forbidden: User "u-lkgx6" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
could not get information about the resource
```

**Expected Results:**
- cluster member should be able to install the monitoring v2 in his project 

**Questions:**
- why the first attempt of installing monitoring v2 fails but create the namespace?

**Comment by maggieliu** [comment]
@jiaqiluo Can we check if cluster member can deploy any other charts?

**Comment by jiaqiluo** [comment]
- As a cluster member, try to install Datadog into my project via the dashboard, the following error should in the helm-operation pod's log 
```
helm --debug install --create-namespace=true --namespace=ns-1 --timeout=10m0s --values=/home/shell/helm/values-datadog-2.4.200.yaml --version=2.4.200 --wait=true datadog /home/shell/helm/datadog-2.4.200.tgz
install.go:172: [debug] Original chart version: "2.4.200"
install.go:189: [debug] CHART PATH: /home/shell/helm/datadog-2.4.200.tgz
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: clusterroles.rbac.authorization.k8s.io "datadog-kube-state-metrics" is forbidden: User "u-q6pv7" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
helm.go:94: [debug] clusterroles.rbac.authorization.k8s.io "datadog-kube-state-metrics" is forbidden: User "u-q6pv7" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
``` 

![image](https://user-images.githubusercontent.com/6218999/94045113-dab41700-fd83-11ea-8a67-6858bcf904f4.png)

![image](https://user-images.githubusercontent.com/6218999/94045136-e4d61580-fd83-11ea-8fc6-c8adcc006648.png)

- as the same clsuter member, try to install Datadog via the MCM UI, we hit the same error 
![image](https://user-images.githubusercontent.com/6218999/94045356-341c4600-fd84-11ea-8429-36550a256bd1.png)

<img width="1420" alt="Screen Shot 2020-09-23 at 10 03 24 AM" src="https://user-images.githubusercontent.com/6218999/94045374-3a122700-fd84-11ea-80b3-6becb545758f.png">

**Comment by mrajashree** [comment]
@jiaqiluo yup this means the cluster-member should not be able to install these apps, can you try artifactory-ha? I think it creates resources that cluster-member has permissions for

**Comment by jiaqiluo** [comment]
@mrajashree 
You are right, whether the app can be installed successfully depons on the permisons of the user who insalls it. 

This is confirmed that the cluster member, the project owner, and the project member all can install the WordPress app successfully via dashboard.

**Comment by mrajashree** [comment]
okay thanks for checking @jiaqiluo . Whether a cluster-member should be able to launch v2 monitoring (or other v2 apps that create similar resources like clusterroles) should be decided separately for each app @maggieliu

**Comment by maggieliu** [comment]
I think as long as we have the same behavior as in catalog v1 we should be fine.

**Comment by jiaqiluo** [comment]
this issue can be closed.

new isseus are logged here:
- https://github.com/rancher/rancher/issues/29109
= https://github.com/rancher/rancher/issues/29110
