### ISSUE TITLE
[EKSv2]: secrets for eks cluster are not cleaned up

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#29040]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create an EKS cluster.
Delete the EKS cluster and wait for all resources associated to delete in EKS and for the EKSClusterConfig to no longer exist.

**Result:**
Secret is not deleted.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 67e24f2`

Steps:
Import an EKS cluster
From local kubectl shell, see the cluster secret.
Before cluster deletion:
![image](https://user-images.githubusercontent.com/57409052/93943843-316c1300-fce8-11ea-8de3-e533f093028a.png)
Delete the cluster
Verify secret is deleted
After cluster deletion:
![image](https://user-images.githubusercontent.com/57409052/93943838-2ca75f00-fce8-11ea-8428-0ad9084a5768.png)

**Comment by sowmyav27** [comment]
**on master- commit - `051643`**

- Deploy a hosted EKS cluster 
- A secret is created in cattle-global-data namespace
- Delete the cluster from Rancher.
- Once the cluster is deleted from the EKS console, the secret is also seen deleted from cattle-global-data namespace
