### ISSUE TITLE
System Charts Cleanup

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29049]
Cleaning up the dev2.5 branch to dev2.4

**Comment by cbron** [comment]
@sangeethah not sure if/how we want to test that PR, its just a min/max update.

**Comment by jiaqiluo** [comment]
on rancher: `v2.4.8`
- swtich the branch of `system-library` to `dev-v2.4`
- go to a cluser -> tools -> cluster monitoring 
- only `0.1.2` in the version list 

on rancher: `v2.5.0-alpha4`
- swtich the branch of `system-library` to `dev-v2.4`
- go to a cluser -> tools -> cluster monitoring 
- only `0.1.3` in the version list
