### ISSUE TITLE
[2.4 Backport] unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29056]
Backport for: https://github.com/rancher/rancher/issues/26674

**Comment by kinarashah** [comment]
Available to test with `v2.4.9-rc1`

**Comment by izaac** [comment]
Same checks done as the original fix here https://github.com/rancher/rancher/issues/26674#issuecomment-697962578 


> Rancher is installed successfully with cert-manager both v0.15.0 and v1.0.1
> 
> - all workloads in the system project in local cluster are active 
> - adding a custom cluster is successful
