### ISSUE TITLE
Slow memory leak in Rancher nodes (related to AD client and leaking goroutines?)

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#29055]
Slow memory leak in Rancher pods related to Azure client. Dumps show most of the leaking goroutines are coming from http conn.serve which could indicate an open connection.

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
See: https://github.com/rancher/rancher/issues/27605
This is a continuation of the above investigation.

**Environment information**
Architecture:
Provider is Azure AD
Built at v2.2.9 with RKE v0.2.9
After 5 days upgraded to 2.4.2
After a few more days upgraded to 2.4.3.
We upgraded to 2.4.5 to resolve rancher/rancher#27605 

There is no network isolation on this cluster.
![image](https://user-images.githubusercontent.com/8906089/93818764-b3116180-fc52-11ea-9e8b-3cae6bdeb41e.png)

gzrancher/rancher#12369
gzrancher/rancher#10142

**Comment by dramich** [comment]
@izaac For testing, can you run regression for the AzureAD provider? One way to tell my changes are working is to turn on debug and watch the logs, after the cache is populated you should see the debug messages seen [here](https://github.com/rancher/rancher/pull/29521) drop in time significantly. One way to force the log is login-logout-login with the same user.

**Comment by izaac** [comment]
Rancher version: `master-head (10/19/2020)` 

I validated this is working. The only case where I've noticed a slow down was the first time I logged into Rancher where I assume the cache was built:

`[INFO] [AZURE_PROVIDER] Completed gathering users groups, took 45.200841592s, keys in cache:1001`

Subsequent login requests were really quick:

`[INFO] [AZURE_PROVIDER] Completed gathering users groups, took 848.69µs, keys in cache:1001`

Also covered: 

- Site access P1 cases
- Cluster owner/member P1s
- Project owner/member P1s
- Refresh group membership

I will check `v2.5-head` and `v2.4-head` backports next

**Comment by izaac** [comment]
I performed the same regression [tests done](https://github.com/rancher/rancher/issues/29055#issuecomment-712461266) (see above) in `master-head` In the following Rancher versions:

`v2.5-head (63e99b6) (10/19/2020)`
[INFO] [AZURE_PROVIDER] Completed gathering users groups, took 11.976168432s, keys in cache:1002
[INFO] [AZURE_PROVIDER] Completed gathering users groups, took 50.59µs, keys in cache:1002


`v2.4-head (6b91c87ab) (10/19/2020)`
[INFO] [AZURE_PROVIDER] Completed gathering users groups, took 47.350210137s, keys in cache:1007
[INFO] [AZURE_PROVIDER] Completed gathering users groups, took 1.009536ms, keys in cache:1007
