### ISSUE TITLE
Update OPA Gatekeeper to v3.1.1

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#29053]
Update OPA Gatekeeper to v3.1.1 -> https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.1.1

PR: https://github.com/rancher/charts/pull/670

**Comment by PennyScissors** [comment]
PR: https://github.com/rancher/charts/pull/670

**Comment by aaronRancher** [comment]
The update is verified with Rancher server `rancher\rancher:master-head` `version ed27498`

v3.1.1 is seen in install dropdown:
![Screen Shot 2020-09-21 at 5 05 38 PM](https://user-images.githubusercontent.com/57409052/93833159-b265d480-fc2c-11ea-9832-db0cb93b3a74.png)
v3.1.1 is installed and deployed:
![Screen Shot 2020-09-21 at 5 03 03 PM](https://user-images.githubusercontent.com/57409052/93833107-8ba79e00-fc2c-11ea-86b0-56eaeb3184ee.png)
Constraints are enforced:
![Screen Shot 2020-09-21 at 1 45 54 PM](https://user-images.githubusercontent.com/57409052/93833342-3029e000-fc2d-11ea-8478-bff326e2061a.png)
P1 use cases were tested and verified.
