### ISSUE TITLE
[Monitoring V2] Support Hardened Cluster - Hardened Scan

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29059]
Need to make sure the CIS hardened profile scan passes for Monitoring

**Comment by jiaqiluo** [comment]
in rancher:`master-f470ae4c5e3b3d17a497ddea8e06bdba9b053451-head` single-insall
- add a harden cluster ( 3 etcd, 2 control plane, 3 workers)
- enable the monitoring v2 in the cluster 

results:
see the following workloads failed to assigned pods to nodes

Workload: pushprox-kube-controller-manager-client
```
Error creating: pods "pushprox-kube-controller-manager-client-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: "secret": secret volumes are not allowed to be used]
```

Workload: pushprox-kube-proxy-client
```
Error creating: pods "pushprox-kube-proxy-client-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[0]: Invalid value: "secret": secret volumes are not allowed to be used spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used]
```

Workload: pushprox-kube-scheduler-client
```
Error creating: pods "pushprox-kube-scheduler-client-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[0]: Invalid value: "secret": secret volumes are not allowed to be used spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used]
```

![screencapture-167-172-196-234-p-c-6qwpr-p-fkcxv-workloads-2020-10-13-13_42_38](https://user-images.githubusercontent.com/6218999/95914017-fa72a580-0d59-11eb-9570-fb1065edb033.png)

**Comment by jiaqiluo** [comment]
`v2.5-b72284720041c18fa2e64f63896c0388133aa9f6-head` 
still hit the same error https://github.com/rancher/rancher/issues/29059#issuecomment-707997762

**Comment by jiaqiluo** [comment]
The bug fix is validated on monitoring v2 chart `9.4.201` on 
- rancher:`v2.5-7eb1792946639251f51bd109b630f9c1cf8940c2-head`
- rancher:`master-3d755ff62ae975044b19d1b74c564e9920127f73-head`

Steps:
- run rancher single install
- provision a hardened RKE cluster 
- deploy monitoring v2
- deploy CIS Scan v2
- run CIS test with the profile `rke-profile-hardened`

Results:
all tests are passed 

![image](https://user-images.githubusercontent.com/6218999/97477129-764d2000-190c-11eb-9713-de566655e826.png)

**Comment by bbarclay** [comment]
Error creating: pods "node-exporter-" is forbidden: PodSecurityPolicy: unable to admit pod:

Getting something similar? Any solution for this yet?

**Comment by aiyengar2** [comment]
@bbarclay node-exporter should be creating a PodSecurityPolicy as seen here: https://github.com/rancher/charts/blob/461f58c59c955c1a3f56312beeb1ad3e986f509f/charts/rancher-monitoring/rancher-monitoring/9.4.202/charts/prometheus-node-exporter/templates/psp.yaml#L4

Do you have that field enabled on the Helm chart? Which version of the Monitoring chart are you encountering that issue in?
