### ISSUE TITLE
KEv2- Ensure CIS hardened profile scan passes

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29067]
When the following operators are deployed on a hardened Rancher management cluster, the CIS hardened profile scan should pass:
- [ ] AKS
- [ ] GKE
- [ ] EKS

**Comment by thedadams** [comment]
In my testing, I wasn't able to get a hardened cluster scan to pass, but installing the operators did not change any of the failures. I believe that if a cluster scan were to pass, then installing the operators would not affect its pass status.

**Comment by sowmyav27** [comment]
This issue is to make the scans for GKE/EKS/AKS clusters pass. Moving it to next milestone.

**Comment by sowmyav27** [comment]
After offline conversation, The issue requirement has been changed to "When the following operators are deployed on a hardened Rancher management cluster, the CIS hardened profile scan should pass: AKS/GKE/EKS" Moving this back to 2.6.0 milestone.

**Comment by sowmyav27** [comment]
On master-head - commit id: `9e0d1b2`

- After deploying a GKE v2 cluster, this command lists namespaces;:
```
> kubectl get serviceaccounts --all-namespaces -o json | jq -r '.items[] | select(.metadata.name=="default") | select((.automountServiceAccountToken == null) or (.automountServiceAccountToken == true))' | jq .metadata.namespace

"c-5l5vq"
"cluster-fleet-default-c-5l5vq-f3ed0cbb698f"
"p-7nh79"
"p-pzqfh"
```
5.1.5 and 5.3.2 fail.

**Comment by thedadams** [comment]
@sowmyav27 The operator only uses the `cattle-system` and `cattle-global-data` namespaces. The namespaces included in this list you provided are not touched by the operator.

**Comment by sowmyav27** [comment]
Closing this issue. And no additional tests fail.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `21ab02c`**

- AKS v2, GKEv2 and EKSv2 deploy on a HA with local RKE1 hardened.
<img width="1256" alt="Screen Shot 2021-07-29 at 7 16 58 AM" src="https://user-images.githubusercontent.com/26032343/127508271-077a9e07-6465-4bf2-912f-60f86f219e1c.png">
