### ISSUE TITLE
 KEv2 - Support Install on Hardened Cluster

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29066]
Support Install on Hardened Cluster
- [ ] AKS
- [ ] GKE
- [ ] EKS

**Comment by sowmyav27** [comment]
**On master-head commit id: `9d54b1a`**

- Deploy an RKE HA local cluster that is hardened based on steps listed [here](https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.5/1.6-hardening-2.5/) 
- When the HA rancher setup comes up Active, deploy an EKS v2 and GKE v2 clusters
- GKE operator fails to deploy with error - `CreateContainerConfigError: container has runAsNonRoot and image will run as root (pod: "gke-config-operator-6d75c9bfb7-pqbqh_cattle-system(40154ecf-f4f5-466b-89e1-6bbc6ed15cd2)", container: gke-operator)`
- EKS fails with - `CreateContainerConfigError: container has runAsNonRoot and image will run as root (pod: "eks-config-operator-84df76b946-5hslf_cattle-system(6ff42efd-06c4-41b6-9db3-88e9e3088369)", container: eks-operator)`

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version f33188d` with the following steps:
- Deployed an RKE HA local cluster that is hardened based on steps listed [here](https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.5/1.6-hardening-2.5/) 
- When the HA rancher setup comes up Active, deploy EKSv2 , AKSv2 and GKEv2 clusters
- And import EKSv2 , AKSv2 and GKEv2 clusters.

Result:
- EKSv2 cluster becomes available in Rancher and EKS console. EKS operator version `v1.1.1-rc7`. k8s version `v1.20.4`
- AKSv2 cluster becomes available in Rancher and AKS console. AKS operator version `v1.0.1-rc16`. k8s version `v1.19.9`
- GKEv2 cluster becomes available in Rancher and GKE console. GKE operator version `v1.1.1-rc8`. k8s version `1.19.9-gke.1900`
- Imported clusters are registered successfully.
