### ISSUE TITLE
Removing controlplane nodes does not remove/stop controlplane components on those nodes

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/rancher#29060]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Create HA cluster with 3 controlplane/etcd nodes
Remove 1 node

**Result:**
The deleted node still has kube api components running on it and can still hold leases from the cluster.

**Other details that may be helpful:**
Rancher should attempt to delete/stop the kube api components on the node when removing it.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): HA

gz#12206

**Comment by superseb** [comment]
Same as https://github.com/rancher/rancher/issues/26545
