### ISSUE TITLE
[ISTIO] Hardened Cluster Support - CIS scan should pass

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29076]
Need to make sure the hardened CIS profile scan passes

**Comment by doflamingo721** [comment]
**This issue is not active on rancher 2.6.3.**

Steps followed:
1. Rancher Server version: 2.6.3
2. Create a downstream hardened cluster following rancher's [hardening guide](https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/).
3. Install istio from Apps and marketplace.
4. Install CIS-Benchmark from Apps and marketplace.
5. Run the `rke-profile-hardened-1.6` scan

Result:
The scan passed without any failures.

**Comment by Martin-Weiss** [comment]
Just to be sure to be sure - did you also verify this with RKE2 and having master/workers where masters have the taint CriticalAddonsOnly=true:NoExecute?

**Comment by doflamingo721** [comment]
@Martin-Weiss No I didn't. Is that required? Sorry, couldn't find that in the issue description/repro steps.

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss No I didn't. Is that required? Sorry, couldn't find that in the issue description/repro steps.

We just had to realize that there are issues with the CIS scan not working in hardened RKE2 clusters and if the documented taints are set on the masters.. so thought if you are testing on rke maybe it is worth to test with rke2, too..

**Comment by doflamingo721** [comment]
> We just had to realize that there are issues with the CIS scan not working in hardened RKE2 clusters and if the documented taints are set on the masters.. so thought if you are testing on rke maybe it is worth to test with rke2, too..

Could you log a separate issue with the details of the problem your facing for CIS scan not working in hardened RKE2 clusters?

**Comment by Martin-Weiss** [comment]
Already escalated to Support so assuming support creates the required Jira ticket..

**Comment by rishabhmsra** [comment]
**Validated on 2.6-head**

**Rancher Server:**
- Version: v2.6-head (7efbeab)
- docker install

**Steps followed:**
- Created a downstream hardened cluster (4 nodes, 1-cp, 1-etcd, 2-worker)
- Installed monitoring chart (100.1.0+up19.0.3)
- Installed istio (100.1.0+up1.11.4)
- Ran the `rke-profile-hardened-1.6` scan.

**Result:**
- CIS can pass without any failures.
