### ISSUE TITLE
[EKS] Support custom instance roles for node groups

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#29071]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Other details that may be helpful:**

In environments where permissions to manage IAM roles/policy attachments are not permitted, selecting a pre-existing instance role is desired when creating a cluster/node group.

https://docs.aws.amazon.com/eks/latest/userguide/worker_node_IAM_role.html

SURE-4536

**Comment by thedadams** [comment]
To be clear: I am not working on this issue. A community member is submitting the required PRs; I am providing reviews and guidance.

https://github.com/rancher/eks-operator/pull/53

**Comment by hmike96** [comment]
How long roughly until the v2.6.2 release? @thedadams

**Comment by snasovich** [comment]
@hmike96 , at this time we're not ready to share the release date for 2.6.2, but we're _probably_ looking at late calendar Q4 '21 or early Q1 '22.

**Comment by thedadams** [comment]
UI issue: https://github.com/rancher/dashboard/issues/4568

**Comment by kinarashah** [comment]
Refer to review comments and code https://github.com/rancher/eks-operator/pull/53, make sure to test it to see if it works for all usecases.

**Comment by annablender** [comment]
Smoke test plan (p0 and p1 cases)

## Testing

1. Provision 2 node EKS cluster with 1 node group with no user-defined node role. Cluster should come up active. Expected on the v3 object:

```
config.spec.NodeGroups.NodeRole = <generated role>
config.status.EKSStatus.GeneratedNodeRole = <generated role>
```

2. Provision 2 node EKS cluster with 1 node group with a user-defined node role (select from existing roles in EKS). Cluster should come up active. Expected on the v3 object:

```
config.spec.NodeGroups.NodeRole = <user defined role>
config.status.EKSStatus.GeneratedNodeRole = ""
```

3. Provision 2 node EKS cluster with 2 node groups, 1 with no-user defined role and 1 with a user-defined node role (select from existing roles in EKS). The node group with no user-defined role should have the default role generated for it. Cluster should come up active. Expected on the v3 object:

```
config.spec.NodeGroups
    NodeRole = <generated role>
    NodeRole = <user defined role>
config.status.EKSStatus.GeneratedNodeRole = <generated role>
```

**Comment by Josh-Diamond** [comment]
Ticket #29071 - Test Plan
---

To be verified on `v2.7-head` + eks-operator `v1.0.5-rc2`:

- Scenario 1 - **NOT YET TESTED**
    - Test: `Provision EKS w/ 1 node group + no user-defined role`
    - Result: expected to successfully provision
- Scenario 2 - **NOT YET TESTED**
    - Test: `Provision EKS w/ 1 node group + user-defined role assigned` 
    - Result: expected to successfully provision
- Scenario 3 - **NOT YET TESTED**
    - Test: `Provision EKS w/ multiple node group; some w/ user-defined role, some without` 
    - Result: expected to successfully provision
- Scenario 4 - **NOT YET TESTED**
    - Test: `Provision EKS on v2.6.8 => upgrade rancher to v2.7-head => add node group w/ user-defined role`
    - Expected to successfully provision

All scenarios to be tested as a standard user
---

Scenario 1:
1. Fresh install of rancher `v2.7-head`
2. Provision downstream EKS cluster w/ 1 node group - [2 nodes] - and no user-defined role assigned
3. Expected Result - Cluster provisions successfully

---

Scenario 2:
1. Fresh install of rancher `v2.7-head`
2. Provision downstream EKS cluster w/ 1 node group - [2 nodes] - and with user-defined role assigned
3. Expected Result - Cluster provisions successfully

---

Scenario 3:
1. Fresh install of rancher `v2.7-head`
2. Provision downstream EKS cluster w/ 2 nodes group - [2 nodes each] - one with user-defined role + one without
3. Expected Result - Cluster provisions successfully

---

Scenario 4:
1. Fresh install of rancher `v2.6.8`
2. Provision downstream EKS cluster w/ 1 node group - [2 nodes; no user-defined role]
3. Once cluster successfully provisions, upgrade rancher to `v2.7-head`
4. Once `Active`; add a node group - [2 nodes; user-defined role assigned] 
5. Expected Result - Cluster successfully updates + is `Active`

**Comment by annablender** [comment]
This was a very complex backend issue to test.

I had to do incremental testing first. Then, I had to have the following setup to test properly test: Rancher `v2.7-head` local instance with `go.mod` files updated to use the local version of my eks-operator for updated function signatures. Kubectl apply the eks crds manifest to the Rancher instance so I was using an updated CRD. Run local eks-operator attached to the instance. The https://github.com/rancher/dashboard/issues/4568 is not finished yet so I simulated UI input for each node group `NodeRole` in the code to test.

My test cases are passing and should work for future iterations of adding node group node roles. @Josh-Diamond I've updated my Notes section in my [test plan](https://github.com/rancher/rancher/issues/29071#issuecomment-1248584761). Once the PRs are merged, this is ready to test.

**Comment by annablender** [comment]
Note: the eks-operator won't be bumped until 2.7.0 is released.

**Comment by annablender** [comment]
The fix for this issue has been updated after a team review. Most notably, unnecessary deep copies have been removed and the `generatedNodeRole` is now set on the Status in the handler instead of in `nodegroup.go` which does not coincide with the utility function in that file. This issue has been retested using [this test plan](https://github.com/rancher/rancher/issues/29071#issuecomment-1248584761) on rancher `v2.7` head. All scenarios are working. Both PRs are DNM until a 2.7.1 branch is released.

**Comment by annablender** [comment]
@Josh-Diamond This is ready to test.

**Comment by Josh-Diamond** [comment]
UI PR above was merged; moving issue `to-test`

**Comment by Josh-Diamond** [comment]
UI issue was moved `to-test`, however associated PR, https://github.com/rancher/ui/pull/4913, was not yet merged; moving back to `blocked` until PR is merged and issue is truly ready `to-test`

**Comment by Josh-Diamond** [comment]
associated PR above was just merged; moving issue back `to-test`

**Comment by snasovich** [comment]
@annablender , moving this one back to "In Review" as it looks like we're referencing eks-operator `v1.1.6-rc1` (https://github.com/rancher/rancher/blob/216bb7f5fc36e93ef5df2a47aaf10ce592e697f2/go.mod#L107) which doesn't seem to exist on https://github.com/rancher/eks-operator/releases and we've decided to move on to `v1.2.0` (with latest `v1.2.0-rc2` is what we probably want referenced).

cc: @Josh-Diamond

**Comment by Josh-Diamond** [comment]
Ticket #29071 - Test Template - NOT YET TESTED
---

With Docker on a single-node instance:

Verified on rancher ``:

| Scenario | Test Case | Result |
|---|---|---|
| 1 | `Provision EKS w/ 1 node group + no user-defined role` | |
| 2 | `Provision EKS w/ 1 node group + user-defined role assigned` | |
| 3 | `Provision EKS w/ multiple node group; some w/ user-defined role, some without` | |
| 4 | `Provision EKS on v2.6.8 => upgrade rancher to v2.7-head => add node group w/ user-defined role` | |

---

Scenario 1:
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream EKS w/ 1 node group (of 2 nodes) and no user-define role assigned

**Comment by annablender** [comment]
@Josh-Diamond This can now be tested. on `v2.7-head` as Rancher is now referencing the correct EKS operator version https://github.com/rancher/rancher/blob/77f87c498b1517dcca5ae7fcf707dc8ebe7a95db/go.mod#L107.

**Comment by Josh-Diamond** [comment]
Ticket #29071 - Test Template - NOT YET STARTED
---

With Docker on a single-node instance:

Verified on rancher ``:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | `Provision EKS 1.23 w/ 1 node group + no user-defined role` | |
| 2. | `Provision EKS 1.23 w/ 1 node group + user-defined role assigned` | |
| 3. | `Provision EKS 1.23 w/ 2 node groups; one w/ user-defined role, one without` | |
| 4. | `Provision EKS 1.23 on v2.6.9 => upgrade rancher to v2.7-head => add node group w/ user-defined role` | |
| 5. | `Provision EKS 1.22 on v2.6.9 => upgrade rancher to v2.7-head => upgrade cluster + nodes to 1.23 => add node group w/ user-defined role` ||
| 6. | `Import EKS w/ user-defined role from AWS Console into Rancher, add node group w/ user-defined role from Rancher UI` ||
| 7. | `Import EKS cluster w/ no user-defined role assigned` ||
| 8. | `Provision EKS cluster w/ no user-defined role assigned; Update to use user-defined role;` - [expected cluster error] ||

---

Scenario 1:
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream EKS w/ 1 node group (of 2 nodes) and no user-define role assigned

**Comment by annablender** [comment]
Retesting is currently blocked by
* https://github.com/rancher/rancher/issues/39931
* https://github.com/rancher/dashboard/issues/7754

**Comment by annablender** [comment]
Waiting on PR https://github.com/rancher/ui/pull/4936 to be merged

**Comment by Josh-Diamond** [comment]
Moving to `Next up`, as associated Dashboard blockers are now ready `to-test`

**Comment by Josh-Diamond** [comment]
Ticket rancher/rancher#29071 - Test Results [cont.] - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-da810a7523fb4c1b529bee374e9d2574f33ab0c8-head` with `rancher/eks-operator:v1.2.0-rc2`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | `Provision EKS 1.23 w/ 1 node group + no user-defined role` | ✅ |
| 2. | `Provision EKS 1.23 w/ 1 node group + user-defined role assigned` | ✅ |
| 3. | `Provision EKS 1.23 w/ 2 node groups; one w/ user-defined role, one without` | ✅  |
| 4. | `Provision EKS 1.22 on v2.6.9 => upgrade rancher to v2.7-head => upgrade cluster + nodes to 1.23 => add node group w/ user-defined role` | ✅ |
| 5. | `Import EKS w/ user-defined role from AWS Console into Rancher, add node group w/ user-defined role from Rancher UI` | ✅ |
| 6. | `Provision EKS cluster w/ no user-defined role assigned; Update to use user-defined role;` - [expected to be unable to update role]  | ✅ |

---

Scenario 1:
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream 1.23 EKS w/ 1 node group (of 2 nodes) and no user-define role assigned
4. Verified - Cluster successfully provisions - [ `v1.23.14-eks-ffeb93d` ]
5. Verified - v3 object reflects generated role with `NodeRole`  and `GeneratedNodeRole` fields
   - `config.spec.eksConfig.nodeGroups.nodeRole = <generated_role>`
   - `config.status.eksStatus.generatedNodeRole = <generated_role>`
6. Verified - EKS Console reflects accurate role for node group

---

Scenario 2:
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream 1.23 EKS w/ 1 node group (of 2 nodes) with user-define role assigned
4. Verified - Rancher is using `eks-operator: v1.2.0-rc2`
5. Verified - Cluster successfully provisions and is `Active` - [ `v1.23.14-eks-ffeb93d` ]
6. Verified - v3 object `NodeRole`  points to custom role and `GeneratedNodeRole`  points to empty string; as expected
7. EKS Console reflects accurate node group role

---

Scenario 3:
1. Fresh install of rancher v2.7-head 
2. As standard user, provision a downstream EKS cluster 1.23 w/ 2 node groups: one with NO user-defined role and one WITH user-defined role assigned; (select from existing roles in EKS and ensure it has required IAM policy ec2.amazon.aws)
3. Cluster should come up `Active`
4. Verified -  Rancher is using `eks-operator: v1.2.0-rc2` 
5. Verified - v3 object reflects the following with NodeRole  and GeneratedNodeRole fields:
    - `config > spec > NodeGroups > NodeRole = <generated_role>`  
    - `config > spec > NodeGroups > NodeRole = <user_defined_role>`

    - `config > status > EKSStatus > GeneratedNodeRole = <generated_role>`
6. Verified - EKS Console reflects accurate roles for node groups

---

Scenario 4:
1. Fresh install of rancher `v2.6.9`
2. As admin, create a standard user
3. As standard user, provision a downstream EKS cluster w/ k8s `v1.22.16-eks-ffeb93d`
4. Once `active`, upgrade rancher server to `v2.7-e54432ebcfba5cfdf92cf055b89a7ebff2537ef7-head`
5. Once successfully upgraded to `2.7-head`, update the cluster to k8s `v1.23.14-eks-ffeb93d`
6. Once `active`, `Edit Config` and add a new node group w/ custom role
7. Verified - Cluster comes up `Active`
8. Verified - v3 object reflects accurate values for `NodeRole`  and `GeneratedNodeRole` fields
9. Verified - EKS Console reflects accurate roles for node groups

---

Scenario 5:
1. From EKS Console, create EKS cluster w/ 1 node group (of 2 nodes) w/ user-defined role assigned
2. Verified - cluster successfully provisions w/ user-defined node role for node groups
3. Fresh install of rancher `v2.7-head`
4. As admin, create a standard user
5. As standard user, import cluster created in step 1 into Rancher
6. Verified - Cluster successfully imports and is `active`
7. Verified - After sync occurs, v3 object reflects accurate values for `nodeRole` and `generatedNodeRole` fields
8. From RancherUI, `Edit Config` of cluster and add a new node group w/ same custom role assigned in step 1 when creating initial node group
9. Verified- All node roles available in AWS Console are populated in RancherUI dropdown
10. Verified - Cluster successfully provisions additional node group w/ custom role
11. Verified - v3 object reflects accurate values for `NodeRole`  and `GeneratedNodeRole` fields
12. Verified - EKS Console reflects accurate roles for node groups

---

Scenario 6:
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream 1.23 EKS w/ 1 node group (of 2 nodes) and no user-define role assigned
4. Verified - Cluster successfully provisions - [ `v1.23.13-eks-fb459a0` ]
5. Verified - v3 object reflects generated role with `NodeRole`  and `GeneratedNodeRole` fields
   - `config.spec.eksConfig.nodeGroups.nodeRole = <generated_role>`
   - `config.status.eksStatus.generatedNodeRole = <generated_role>`
6. `Edit Config` and attempt to update node group to use custom role
7. Verified - `N/A` - unable to edit existing node group role; as expected
