### ISSUE TITLE
Nanoseconds in projectlogging

### ISSUE THREAD

**Issue by stayfrostnl** [rancher/rancher#29078]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Activate Elasticsearch at project level

**Result:**
Log timestamps contain only seconds

**Other details that may be helpful:**
In https://github.com/rancher/rancher/issues/20675 it was fixed for cluster level but when we look at this template it isnt for project level? See https://github.com/rancher/rancher/blob/master/pkg/controllers/managementuser/logging/generator/templatesource.go

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
1.18.6
```

- Docker version (use `docker version`):

```
19.3.11
```

**Comment by izaac** [comment]
Reproduced in Rancher version `v2.4.10`

Timestamps shown the nanoseconds always as `.000`

Validated nanoseconds are now included in Rancher version `v2.4-head (11/17/2020)` _011c9dcd1_

**Comment by izaac** [comment]
Opened a new issue for 2.5+ #30152
