### ISSUE TITLE
Upgrade to machine v0.5.0

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#2908]
Yup

**Comment by sangeethah** [comment]
With the latest build from master  - docker-machine version 0.5.2 ( 0456b9f ) is available.

Existing validation test cases for Digitial Ocean machine and Amazon machine test cases succeed. 

2 test cases relating to passing invalid vpc and invalid subnet have a different behavior now.

1. test_amazon_ec2machine_invalid_vpc_valid_subnet - fails with "exit status 1" error message.  This used to successfully deploy machine in the subnet.

2. test_amazon_ec2machine_valid_vpc_invalid_subnet - fails with "exit status 1" error message. Error message we got for earlier version of docker machine is "The subnet ID '<subnetId>' does not exist"
