### ISSUE TITLE
Upgrade of a cluster from 1.18 to 1.19 fails for Canal network provider

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29083]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a 4 node - 1 etcd, 1 control and 2 worker nodes - Canal network provider cluster on latest master
- K8s version of this ^^^ cluster is v1.18.9
- When the cluster comes up successfully, upgrade k8s version of the cluster to 1.19.2
- Cluster fails to come up with an error `Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system`
- Error seen in the `rke-network-plugin-pod`: 
`The ClusterRoleBinding "canal-calico" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"calico-node"}: cannot change roleRef`

**Expected Result:**
Cluster should come up successfully after an k8s 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `903a8925f5`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom rke
- Kubernetes version (use `kubectl version`):

```
1.18.9 to 1.19.2
```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 67e24f2`

Steps:
Deploy a 4 node - 1 etcd, 1 control and 2 worker nodes - Canal network provider cluster on latest master with k8s version `v1.18.9`
Canal version:
![Screen Shot 2020-09-22 at 4 04 50 PM](https://user-images.githubusercontent.com/57409052/93946233-96763780-fced-11ea-9bae-b55fa1ba8994.png)

When the cluster comes up successfully, upgrade k8s version of the cluster to 1.19.2

Result:
Cluster is upgraded successfully.
![Screen Shot 2020-09-22 at 4 04 42 PM](https://user-images.githubusercontent.com/57409052/93946219-8d856600-fced-11ea-92b4-1ad29dfc108c.png)
Canal version after upgrade:
![Screen Shot 2020-09-22 at 3 55 12 PM](https://user-images.githubusercontent.com/57409052/93946303-c1f92200-fced-11ea-9524-ab1973936d27.png)
