### ISSUE TITLE
Missing banners to re-direct to dashboard for Isito

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#29088]
In monitoring/logging/cis, we have banners added to the top to have links to re-direct to the v2 version.

Can we add these for Istio, alerts and notifiers? 

Istio -> `/istio`

`The latest versions of Istio are only available in Cluster Explorer. See docs for details on what's new and how to migrate.`

alerts and notifiers page -> `monitoring` - For this text, can update it to 

`We've updated alerts to be directly integrated with monitoring in Cluster Explorer. See docs for details on what's new and how to migrate.`

`We've updated notifiers to be directly integrated with monitoring in Cluster Explorer. See docs for details on what's new and how to migrate.`

<img width="855" alt="Screen Shot 2020-09-22 at 11 18 37 AM" src="https://user-images.githubusercontent.com/11410997/93921409-6450df80-fcc5-11ea-9ba3-b51c978c6834.png">

PR that added the banner for monitoring/logging/cis: 
https://github.com/rancher/ui/pull/4147

**Comment by sangeethah** [comment]
Tested with latest build from master - `27000be`

Following banner redirects seen for  Istio, alerts , notifiers and monitoring as expected.

Redirect to "Cluster Explorer" from Notifier is broken . Use is taken to "<ip>:/monitoring" which is "404 page not found" error.

Reopening to fix this redirect issue.

**Comment by sangeethah** [comment]
Tested with latest build from master:

Redirect to "Cluster Explorer" from Notifier works as expected. We are taken to "Monitoring" page.
