### ISSUE TITLE
[Monitoring V2] Old version of rancher-monitoring shows up in the UI

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29098]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Navigate to the App install page on the Dashboard UI for Rancher Monitoring

**Result:**
Old package version number before the rebase to a new upstream in https://github.com/rancher/charts/pull/641 shows up.

![Screen Shot 2020-09-22 at 3 39 27 PM](https://user-images.githubusercontent.com/13127443/93944622-17333480-fcea-11ea-800b-b7521cb27c45.png)

**Other details that may be helpful:**

There is no tgz for `8.16.100` and we don't want to support it since it was a prior version created before our official release.

![Screen Shot 2020-09-22 at 3 42 10 PM](https://user-images.githubusercontent.com/13127443/93944661-2fa34f00-fcea-11ea-9691-6eade8aec103.png)

**Comment by jiaqiluo** [comment]
still see 2 vesions in the latest master-head e9a98a3

**Comment by jiaqiluo** [comment]
only one vesion shows for monitoring v2 in the lastest master-head
![image](https://user-images.githubusercontent.com/6218999/94070983-ff21ea80-fda7-11ea-8b3f-6f36967f6a84.png)
