### ISSUE TITLE
Uncaught TypeError when clicking on dropdown for Scheduling

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2910]
Version - Master 12/03

Steps;
1.  Add a couple of labels to your hosts
2.  Make sure Developer Tools are open
3.  Create a service and under Advanced Options/Scheduling click on the drop-down for Key or Value

Results:
The service still works and the rule is followed but the Debugger pauses on caught exception - Uncaught TypeError: Cannot read property 'relatedTarget' of undefined.

Expected:
Probably shouldn't do this.

**Comment by vincent99** [comment]
Can you still reproduce this?  I tried..

**Comment by tfiduccia** [comment]
Version - master 3/22
Verified fixed
