### ISSUE TITLE
Creating a hosted EKS cluster with a clustername that already exists in AWS console, results in the existing cluster in AWS console being updated

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29103]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On master-head - commit id: `051643663`
- Deploy an EKS cluster with k8s 1.15
- eksConfig:

```
"eksConfig": {
"amazonCredentialSecret": "cattle-global-data:cc-gc5lk",
"displayName": "sowmya-3",
"imported": false,
"kmsKey": "",
"kubernetesVersion": "1.15",
"loggingTypes": [ ],
"nodeGroups": [
{
"desiredSize": 2,
"diskSize": 20,
"ec2SshKey": "",
"gpu": false,
"instanceType": "t3.medium",
"labels": { },
"maxSize": 2,
"minSize": 2,
"nodegroupName": "sow-ng",
"subnets": [ ],
"tags": { },
"type": "/v3/schemas/nodeGroup",
"version": "1.15"
}
],
"privateAccess": false,
"publicAccess": true,
"publicAccessSources": [ ],
"region": "us-west-2",
"secretsEncryption": false,
"securityGroups": [
"sg-<>"
],
"serviceRole": "",
"subnets": [ 2 items
"subnet-<>",
"subnet-<>"
],
"tags": { },
"type": "/v3/schemas/eksClusterConfigSpec"
},
```

- Upstream spec:
```
"eksStatus": {
"securityGroups": null,
"subnets": null,
"type": "/v3/schemas/eksStatus",
"upstreamSpec": {
"amazonCredentialSecret": "cattle-global-data:cc-gc5lk",
"displayName": "sowmya-3",
"imported": false,
"kmsKey": "",
"kubernetesVersion": "1.17",
"loggingTypes": [ ],
"nodeGroups": [ ],
"privateAccess": false,
"publicAccess": true,
"publicAccessSources": [
"0.0.0.0/0"
],
"region": "us-west-2",
"secretsEncryption": false,
"securityGroups": [
"sg-<>"
],
"serviceRole": "",
"subnets": [ 2 items
"subnet-<>",
"subnet-<>"
],
"tags": { },
"type": "/v3/schemas/eksClusterConfigSpec"
},
"virtualNetwork": ""
},
```
- The cluster is seen stuck in Updating state with error
<img width="1271" alt="Screen Shot 2020-09-22 at 5 19 39 PM" src="https://user-images.githubusercontent.com/26032343/93950482-7435e700-fcf8-11ea-8566-ce2d9f0cffe7.png">

- Cluster created in EKS console has k8s version 1.17
- This issue ^^^ happened when I created a cluster - `sowmya-3` with k8s 1.17, and deleted it immediately and provisioned another hosted cluster with k8s 1.15 this time.

**Note:**
This will also happen when we deploy a hosted EKS cluster with cluster name `cluster-1` where `cluster-1` is already existing in the AWS console. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `051643663`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted EKS
- Kubernetes version (use `kubectl version`):

```
1.15
```

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `393468f`**

**Scenario#1**

- Create an EKS cluster in AWS console - k8s 1.17
- Cluster is in `Creating` state
- Create a hosted EKS cluster in Rancher - k8s 1.15
- Error seen in rancher:

<img width="1327" alt="Screen Shot 2020-11-12 at 8 42 16 PM" src="https://user-images.githubusercontent.com/26032343/99029642-d86e6d80-2527-11eb-8a0c-d9e8afb0bc59.png">

**Scenario#2**
- Create a hosted EKS cluster in `rancher 1` (master-head)
- Create a hosted EKS cluster in `rancher 2` - 2.5-head with the same name
- Fails with error Secret already exists
- Delete the cluster from `rancher 2`.
- Cluster gets deleted from EKS console and rancher 1, the worker nodes get deleted and error seen on rancher 1- - 
<img width="1261" alt="Screen Shot 2020-11-12 at 8 47 10 PM" src="https://user-images.githubusercontent.com/26032343/99029818-5599e280-2528-11eb-9841-7554de9a2a49.png">

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `71da1569f`**

**Scenarios validated:**
**Scenario#1**
- Create an EKS cluster in the EKS console
- Create a hosted EKS from Rancher using same name
- Should not be allowed - Error seen: "Cannot create cluster [sowmya-eks-2] because a cluster in EKS exists with the same name"

**Scenario#2**

- Create an EKS cluster in the EKS console
- Create a hosted EKS from Rancher using same name
- Should not be allowed 
- Delete cluster from EKS console
- Cluster in Rancher recovers ad comes up Active.

**Scenario#3**

- Create an EKS cluster in Rancher.
- Delete cluster immediately
- create another one using the same name. Cluster comes up Active

**Scenario#4**

- Create an EKS cluster in 1 Rancher server r1
- Create an EKS from another Rancher r2 using same name
- The cluster throws an error as expected.
- Delete the cluster from Rancher r2 - logs show `time="2020-11-17T13:07:54Z" level=warning msg="cluster [c-f6x45] never advanced to creating status, will not delete EKS cluster"`
- The cluster in EKS does not get deleted

**Scenario#5**

- Create an EKS cluster in the EKS console - name: `test1`
- Create an imported EKS from Rancher using same name- `test1`, select `test1` from the dropdown of cluster names to import
- Does not allow - "Cannot create cluster [test1] because a cluster in EKS exists with the same name"

**Question:** Why is this not allowed? When a user enters `test1` in EKS console while creating a cluster, while importing it, why should a user give another name?

**Comment by sowmyav27** [comment]
To add to this check done [here](https://github.com/rancher/rancher/issues/29103#issuecomment-728916805), as part of scenario#5
- Create an EKS cluster in the EKS console - name: sowmya-import-2
- Create an imported EKS from Rancher using name- sowmya-import, select sowmya-import-2 from the dropdown of cluster names to import
- Fails with error `ResourceNotFoundException: No cluster found for name: sowmya-import. { RespMetadata: { StatusCode: 404, RequestID: "8f83b6cb-58c6-459c-bc78-354df0bbbe29" }, Message_: "No cluster found for name: sowmya-import." }`

**Comment by thedadams** [comment]
This new scenario is an issue with the front-end. Following the steps that Sowmya laid out, the request that is made to the backend makes no reference to the cluster that exists in EKS. For example, I tried to import a cluster named `test` in Rancher giving it the name `donnie-test` and the request did not mention the `test` cluster that exists in EKS:
```
{"dockerRootDir":"/var/lib/docker","enableClusterAlerting":false,"enableClusterMonitoring":false,"enableNetworkPolicy":false,"windowsPreferedCluster":false,"type":"cluster","name":"donnie-test","eksConfig":{"imported":true,"displayName":"donnie-test","region":"us-east-2","type":"eksclusterconfigspec","amazonCredentialSecret":"cattle-global-data:cc-bf4ng"},"labels":{}}
```

**Comment by sowmyav27** [comment]
**Verified on 2.5-head - commit id:`db350a`**

- `eks-operator:v1.0.5-rc2` is deployed
- Create an EKS cluster in the EKS console - name: test1
- Create an imported EKS from Rancher using same name- test1, select test1 from the dropdown of cluster names to import
- Cluster is created successfully
