### ISSUE TITLE
App - cluster member/ project owner/ project member can not see logs of the helm-operation pod  

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#29110]
**What kind of request is this (question/bug/enhancement/feature request):**
bug on rancher:master-head 2229f5c

in the dashboard, cluster member/ project owner/ project member can install/upgrade apps, but he cannot see the logs of the helm-operation pod.

notice the `Disconnected` at the right lower corner 

![image](https://user-images.githubusercontent.com/6218999/94050651-69786200-fd8b-11ea-8815-4858e3fea540.png)

**Comment by dramich** [comment]
Running 4ac3a87 this appears to be working. Using a cluster-member installing the rancher catalog then wordpress app I am seeing logs. 
![Screen Shot 2020-09-25 at 4 08 00 PM](https://user-images.githubusercontent.com/13897607/94320083-ee58ac80-ff40-11ea-8441-e05533144081.png)

**Comment by jiaqiluo** [comment]
reopen this issue since it happens again in the rancher:master-head 4ac3a87

This a cluster member who has his own project and namespace 

<img width="1741" alt="Screen Shot 2020-09-25 at 4 27 01 PM" src="https://user-images.githubusercontent.com/6218999/94324762-3206e280-ff50-11ea-8cf4-83887929967e.png">

**Comment by StrongMonkey** [comment]
@dramich It is a rbac issue, I fixed in this PR. https://github.com/rancher/rancher/pull/29181

**Comment by sowmyav27** [comment]
On `9de5a8509d7` --> master-head commit id:,

Cluster member, project owner/member users are able to see logs while deploying apps
