### ISSUE TITLE
Provider on imported rke2 cluster shows as RKE Federal

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rancher#29114]
Versions:
RKE2 Version: v1.18.8-beta20+rke2
Node OS: RHEL7.8, RHEL8
Rancher Version:2.5.0-alpha4

Issue:
When RKE2 Cluster is imported into rancher, Provider is seen as RKE Federal. As per the conversation during standup with @cjellick it is expected to be RKE Government

Expected result:
RKE Government

Actual result:
RKE Federal

![image](https://user-images.githubusercontent.com/56045581/94058554-08a25700-fd96-11ea-9752-eeb0a501f660.png)

**Comment by sangeethah** [comment]
Tested with latest build from master - `3950b8ea` 

Imported rke2 cluster shows up as  "RKE Government" :

<img width="1061" alt="Screen Shot 2020-09-24 at 12 11 48 PM" src="https://user-images.githubusercontent.com/4266958/94190956-a878e700-fe61-11ea-90e6-31f305ef6edc.png">
