### ISSUE TITLE
[Logging v2] Installing the chart in local k3s cluster with additional Logging enabled is expecting a Persistent Volume 

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29111]
**What kind of request is this:**
bug

**Steps to reproduce:**
- `v2.5.0-alpha5`
- Install a Rancher with an HA k3s local cluster or single Rancher install (now with local k3s cluster by default)
- Then from Dashboard -> Apps install `rancher-logging` with the Cluster Plane option enabled.
- Click Install

**Result:**

- The main logging operator, fluentbit and fluentd gets properly installed 
- The `additionalLoggingSources` workloads however fluentd is expecting to bind a persisting volume

`Running "VolumeBinding" filter plugin for pod "rancher-logging-k3s-fluentd-0": pod has unbound immediate PersistentVolumeClaims`

**Other details that may be helpful:**

This is not reproducible in Downstream k3s clusters

![Screen Shot 2020-09-23 at 11 28 51 AM](https://user-images.githubusercontent.com/27659/94054108-09d08580-fd90-11ea-96e7-413b6181347b.png)

![Screen Shot 2020-09-23 at 11 28 59 AM](https://user-images.githubusercontent.com/27659/94054118-0ccb7600-fd90-11ea-87de-52cad7fc4c4b.png)

**Environment information**
- Rancher version: `v2.5.0-alpha5`
- Installation option: single and HA k3s

**Cluster information**
- Cluster type: k3s

Kubernetes v1.18.8+k3s1

**Comment by paynejacob** [comment]
https://github.com/rancher/charts/pull/691

**Comment by izaac** [comment]
This is working now in latest `master-head (09/24/2020)` _3950b8e_

Rancher Single and HA k3s local cluster.

**Comment by izaac** [comment]
Works in an airgap setup in `v2.5.0-rc1`
