### ISSUE TITLE
OKE Cluster driver: Add support for flexible compute shapes such as VM.Standard.E3

### ISSUE THREAD

**Issue by jlamillan** [rancher/rancher#29124]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**

1. Create cluster in Rancher UI
2. Select Oracle OKE
3. In the version drop-down list, notice that [flexible compute shapes](https://docs.cloud.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm#Flexible%20Shapes) are listed, however you cannot select the the number of CPU's or memory.

**Result:**
Cannot select the parameters of the flexible shape.

**Other details that may be helpful:**

Because you can customize the number of OCPUs for flexible shapes, the UI would need to also take these parameters when a flexible compute shape such as VM.Standard.E3 was chosen.

**Environment information**
- Rancher version: v2.4.8 (using rancher/rancher:latest)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by jlamillan** [comment]
On a related note, we should filter out the flex shapes until they are fully supported.

**Comment by jlamillan** [comment]
Support for using flexible shapes on nodes has been [added](https://github.com/rancher-plugins/kontainer-engine-driver-oke/commit/1208467793dc3bd4e19942991c69bff5eacb027e) to the OKE cluster driver.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `30e53bd4` and master-head commit id: `5bf4b5de`**

- Spin up an OKE cluster with these fields set with some values `nodeShape": "VM.Standard.E3.Flex",`, `"flexOcpus": 12,` and `customBootVolumeSize": 50,`
- The cluster comes up Active.
- These fields are set in the API of the cluster in Rancher
- And on the backend, was able to verify the values are set on the cluster/nodepools.
