### ISSUE TITLE
DNS resolution does not work for sidekick service name/containers.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2912]
Server version - Build from master - dec 3

steps to reproduce the problem:
Create a service - s1 with sidekick service - s2.
From with in the containers of service - s1 , try to ping s2/containers within s2 using the container names.

In both cases , DNS resolution does not work.

**Comment by sangeethah** [comment]
Tested with latest build from master - Dec 4.

DNS resolution work for sidekick services by service name and container names.

**Comment by mattwilliamson** [comment]
Can you please give an example if I have a `mysql` service with a `setup` sidekick. How would the sidekick connect to the mysql server? If I use `mysql` it uses the round-robin DNS, rather than being tied to the container it is a sidekick to. I'm running 0.59.1.

**Comment by deniseschannon** [comment]
@mattwilliamson Can you share your docker-compose.yml so that we can understand what you are trying to do? You can find it under "View Config" in the stack menu dropdown.
