### ISSUE TITLE
[EKSv2] If eks-operator deploy fails, it is not retried

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#29127]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Set system-charts catalog branch to a branch that does not contain the eks-operator chart.
If eks-operator app is already running be sure to delete it.
Create eks cluster
Observe error in the UI
Change branch to dev-v2.4

**Result:**
App deploy is never retried.

**Comment by sowmyav27** [comment]
**Reproduced this issue on 2.5.1**

- Set system-charts catalog branch to a branch that does not contain the eks-operator chart - `dev` branch.
- Create eks cluster
- Error seen on cluster - `Failed to deploy eks-operator: catalogtemplates.management.cattle.io "system-library-rancher-eks-operator" not found` and cluster is seen in `Provisioning` state.
- Change branch to dev-v2.4
- The eks operator app does NOT get deployed.

**On 2.5-head commit id: `52583ea7a0` and master-head - commit id: `e4dc2513`**

- Set system-charts catalog branch to a branch that does not contain the eks-operator chart - `dev` branch.
- Create eks cluster
- Error seen on cluster - `Failed to deploy eks-operator: catalogtemplates.management.cattle.io "system-library-rancher-eks-operator" not found` and cluster is seen in `Provisioning` state.
- Change branch to dev-v2.4
- eks operator workload is deployed. 
- Error message on the cluster is NOT seen anymore.
- Cluster starts provisioning. 
- Clusters come up active.

**Comment by RogerSik** [comment]
Same issue here. But i'm worried that i will get into troubles when switching vom branch 2.6 to branch 2.5
