### ISSUE TITLE
Extend support for passing engine related parameters when adding hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2913]
Expose the following fields in UI when adding hosts:

engine-opt
engine-insecure-registry: Specify insecure registries to allow with the created engine
engine-registry-mirror: Specify registry mirrors to use
engine-label: Specify labels for the created engine
engine-storage-driver: Specify a storage driver to use with the engine
engine-env
engineInstallUrl

**Comment by sangeethah** [comment]
Tested with rancher-server version - V0.50.0-rc4

When adding host , user is presented with docker engine related options that can be passed.

**Comment by Jdesk** [comment]
i know this issue is close - and this is quite unconventional - but great addition!
