### ISSUE TITLE
Huawei Yunkun ARM Server adaptation

### ISSUE THREAD

**Issue by kongge-cfw** [rancher/rancher#29132]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**
1、Two Huawei Cloud Kunpeng ARM servers, one deployed Rancher2.4.5, and created a cluster
2、Another server serves as the node of the cluster (page create three types selected)
3、New node failed

**Result:**

![image](https://user-images.githubusercontent.com/62277657/94126493-4385b700-fe8a-11ea-8e1b-9e7949940715.png)

**Other details that may be helpful:**
After communication, the initial reason may be：rancher/calico-pod2daemon-flexvol:v3.13.4   and  rancher/calico-cni:v3.13.4 There is no arm version

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): single install
- Docker version (use `docker version`):   Docker version 18.06.3-ce, build d7080c1

```
(paste the output here)
```

**Comment by kingsd041** [comment]
@kongge-cfw As a temporary solution, you can edit `canal` and replace the following image:

`rancher/calico-pod2daemon-flexvol:v3.13.4` -->  `calico/pod2daemon-flexvol:v3.13.4`
`rancher/calico-cni:v3.13.4`   -->   `calico/cni:v3.13.4`
`rancher/calico-node:v3.13.4`  -- > `calico/node:v3.13.4`
