### ISSUE TITLE
Add Load-Balancer ability to route only to instances on specific Hosts

### ISSUE THREAD

**Issue by markrendle** [rancher/rancher#2914]
I have identical services running in 17 Azure data centres, which talk to data stores in those DCs. I route AJAX requests to specific DCs using domain prefixes like `north-eu-blob.cloudlens.io`, and I need those requests to be handled in that DC. [I asked about this in the Forums](http://forums.rancher.com/t/load-balancer-behavior-across-multiple-dcs/1157) and it appears that the load-balancer will round-robin to all instances of a service, regardless of DC.

What I would like to be able to do is run a load-balancer instance on every host, and have it route requests only to other instances running on the exact same host.

Another alternative would be routing based on Host tags, so the load-balancer only routes to instances running on Hosts that have an arbitrary tag, although that sounds like it would be more complicated.

**Comment by will-chan** [comment]
I think this is a good feature that Rancher can add in the near future so that we can manage services at a "data-center" level for traffic efficiency.  The alternative for now if course creating stacks that contain your LB + Services and adding the appropriate host affinity rules but it does get cumbersome when you add large number of data centers.

**Comment by cusspvz** [comment]
My two cents on this! :)

**Comment by chuck7000** [comment]
+1

**Comment by fentas** [comment]
+1 for
> [...] routing based on Host tags, so the load-balancer only routes to instances running on Hosts that have an arbitrary tag, although that sounds like it would be more complicated.

I would be need for my current use case.

**Comment by Schinti95** [comment]
Any update on this feature? Or does anyone have an idea for a workaround?

**Comment by slaash** [comment]
+1

**Comment by soundman666** [comment]
+1000

**Comment by vincent99** [comment]
http://docs.rancher.com/rancher/v1.6/en/cattle/labels/#target-service-labels
