### ISSUE TITLE
Auth configuration of OpenLDAP fails with error "Error creating ssl connection: LDAP Result Code 200 "": EOF"

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#29153]
**What kind of request is this:**
Bug

**Steps to reproduce:**
- Configure LDAP with `StartTLS` over port 389
- Configure authentication in Rancher UI by keeping "TLS" in tick and port as 389

**Result:**

Getting below error message in the UI
```
TestAndApply Error
Error creating ssl connection: LDAP Result Code 200 "": EOF
```

**Other details that may be helpful:**

Based on the code, we don't have a call for StartTLS
https://github.com/rancher/rancher/blob/release/v2.4/pkg/auth/providers/common/ldap/ldap_util.go#L35

Probably we need one more UI button for StartTLS along with TLS (either one can be active at a time) and may need another condition like below in the code. (Probably need more changes if we are going to pass that as a config flag like TLS)

```
....
    } else if StartTLS {
        lConn, err := ldapv2.Dial("tcp", fmt.Sprintf("%s:%d", server, port))
        if err != nil {
            return nil, fmt.Errorf("Error creating connection: %v", err)
        }
        tlsConfig = &tls.Config{RootCAs: caPool, InsecureSkipVerify: false, ServerName: server}
        err = lConn.StartTLS(tlsConfig)
        if err != nil {
            return nil, fmt.Errorf("Error creating ssl connection: %v", err)
        }
   } ....
```

**Environment information**
- Rancher version: v2.4.5
- Installation option: HA

gz#12435

**Comment by mrajashree** [comment]
Backend PRs are merged, waiting for UI before moving it to test

**Comment by mrajashree** [comment]
can be tested through API

**Comment by izaac** [comment]
Opened #30359 to add the setting in the settings summary.

**Comment by izaac** [comment]
Rancher version: `2.5.4-rc1`
Rancher version: `master-head (12/05/2020)` _e129f92_

Validated the original LDAP test server without StartTLS fails if we try to use it over port 389.
Validated the new LDAP server with StartTLS succeeds to enable the openLDAP authentication.
Spot check P1 scenarios manually done with the StartTLS test server.

Regression tests done with the original LDAP test server without StartTLS for:

openLDAP
FreeIPA
ActiveDirectory
