### ISSUE TITLE
[UI] links

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#2915]
I miss the link as name info.. where a link `target:alias` would show up as `target (as alias)` in a section with all links, which was very nice. Also the little icons for the various links where a nice plus.

Now, the only place I've found the alias info is when I go into the edit dialog for a service (not considering the api pages).

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/2823

**Comment by kaos** [comment]
Right. I missed that one, thanks.
