### ISSUE TITLE
500 error is returned when installing an app which creates a namespace via the dashboard 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#29167]
**What kind of request is this (question/bug/enhancement/feature request):**
bug maste-head e9a98a3
found during installing monitoring v2 but could be a general issue for all apps that creates namespace while installing process. 

**Steps to reproduce (least amount of steps as possible):**
- installing the monitoring v2 app for the first time in the dashboard 

**Result:**
The following error shows in the UI. 
But the namespace is created actually( can find it in the target project)
Clicking on the install button again will trigger the installing of the app. 

<img width="800" alt="Screen Shot 2020-09-25 at 11 49 57 AM" src="https://user-images.githubusercontent.com/6218999/94305892-cd835d80-ff26-11ea-9bed-bd1d09f29dac.png">

<img width="785" alt="Screen Shot 2020-09-25 at 11 50 08 AM" src="https://user-images.githubusercontent.com/6218999/94305897-ceb48a80-ff26-11ea-865f-201a1483aad5.png">
<img width="796" alt="Screen Shot 2020-09-25 at 11 50 38 AM" src="https://user-images.githubusercontent.com/6218999/94305900-cf4d2100-ff26-11ea-92b3-70ca70a792f0.png">

**Comment by aiyengar2** [comment]
Unable to reproduce this after taking the following steps:
- Logged in as the admin user on rancher
- Spun up a new digital ocean cluster
- Went to the Apps page on the Dashboard UI
- Clicked on the Rancher Monitoring chart and installed with no changes to default
- Chart successfully deploys and there’s no error

Seems like this is an ephemeral issue that appears once in a while. We need more information to figure out how to reproduce the issue consistently.

**Comment by jiaqiluo** [comment]
see this in rancher:v2.5.0-rc3 docker-install airgap setup
