### ISSUE TITLE
Banner Boxes for Pipelines, Multicluster Apps

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#29179]
Need banner boxes similar to the ask in here: https://github.com/rancher/rancher/issues/29088

Use this language for now:

```
	
We've updated deploying apps at scale with Fleet in Cluster Explorer. 
```

Link on Cluster Explorer to dashboard page.

- [x] Pipelines
- [x] Multi-cluster Apps

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 27000be

* Multicluster apps is missing the link to Cluster Explorer: 
  * `multiclusterapp: We've updated deploying apps at scale with Fleet in Cluster Explorer.`
  vs 
  * `pipeline: We've updated deploying apps at scale with Fleet in <a href="{dashboardLink}/fleet">Cluster Explorer</a>`

* The pipeline banner is only showing on the repository authentication screen, and not on the pipelines landing page where I would expect it to be shown -- users will not see the banner if they only deploy an example pipeline. 

![Screen Shot 2020-09-27 at 8 38 51 AM](https://user-images.githubusercontent.com/21316915/94369292-b4e98380-009d-11eb-9572-18b7e10fcc40.png)

![Screen Shot 2020-09-27 at 8 34 41 AM](https://user-images.githubusercontent.com/21316915/94369302-bdda5500-009d-11eb-8944-1c0f27bcf896.png)

**Comment by deniseschannon** [comment]
@westlywright With the assumption of the local cluster existing in dashboard, can we automatically have it navigate to the local cluster for the link in multi-cluster apps?

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 27000be

* Links navigate to Fleet from Multicluster Apps 
* The pipeline banner can be seen when enabling both the example and custom repositories
* Deprecation notices are shown
