### ISSUE TITLE
2.5 UI Notices for Deprecated Features

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#29178]
Provide UI notifications in Rancher 2.5 to users that these features are being deprecated.
The features and functionality are replaced with new versions/implementations of the tools and users will need to migrate before upgrading from 2.5 to the minor release in the future.
- [x] Rancher Monitoring - Ember UI based 
- [x] Alerting - Ember UI
- [x] Notifiers - Ember UI
- [x] Rancher Logging - Ember UI based
- [x] CIS Benchmark 1.4 -  Ember UI based
- [x] Istio 1.5 - Newer versions available in 2.5.
- [x] Rancher MultiCluster Apps - Being replaced by Fleet GitOps
- [x] Rancher Pipelines - Being replaced by Fleet GitOps

**Comment by deniseschannon** [comment]
Need the actual docs location for the deprecation notice to be added. 

Since we're moving from info to warning of the deprecation, I've update the banner class to `bg-warning`.

**Comment by sangeethah** [comment]
Monitoring, Alerting . Notifiers , logging and CIS benchmark have the deprecation message. The link to docs- 
`https://rancher.com/docs/rancher/v2.x/en/reference/deprecation` is not available yet.

`Restore/Backup` is now renamed as `Rancher Backups`

`MultiCluster App`s  and `Pipelines` changes are tracked in  https://github.com/rancher/rancher/issues/29179
