### ISSUE TITLE
rancher-webhook error on Rancher 2.5.0-rc2 alerts after upgrades delayed

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29187]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install Rancher, no `rancher-webhook` found in System project after install

**Result:**

`[ERROR] Failed to install system chart rancher-webhook: failed to find chartName rancher-webhook version 0.1.0-beta100: NotFound 404`

**Other details that may be helpful:**

- We initially identified this error after upgrading from `2.4.8` to `2.5.0-rc2`
- Alerts stopped working after upgrade.

```
2020/09/26 04:12:09 [ERROR] error syncing 'c-z5r7p/kube-components-alert': handler cluster-alert-group-controller: Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found, requeuing
2020/09/26 04:12:09 [ERROR] error syncing 'c-z5r7p/deployment-event-alert': handler cluster-alert-rule-controller: Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found, requeuing
2020/09/26 04:12:09 [ERROR] error syncing 'c-z5r7p/scheduler-system-service': handler cluster-alert-rule-controller: Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found, requeuing
2020/09/26 04:12:09 [ERROR] error syncing 'c-z5r7p/db-over-size': handler cluster-alert-rule-controller: Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found, requeuing
2020/09/26 04:12:09 [ERROR] error syncing 'p-vvfvr/memory-close-to-resource-limited': handler project-alert-rule-controller: Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found, requeuing
2020/09/26 04:12:09 [ERROR] error syncing 'c-z5r7p/high-number-of-leader-changes': handler cluster-alert-rule-controller: Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found, requeuing
2020/09/26 04:14:29 [ERROR] error syncing 'c-z5r7p/car-nq6cj': handler cluster-alert-rule-controller: Update Webhook Receiver Config: Get secret: secrets "webhook-receiver" not found, requeuing
```

**Environment information**
- Rancher version: `v2.5.0-rc2`
- Installation option: HA k8s RKE

**Cluster information**
- Cluster type: RKE DO
- Machine type: VM - three 8GB worker nodes DigitalOcean
- Kubernetes version: v1.18.8

**Comment by izaac** [comment]
I got a late alert after upgrade. Updated the issue tittle.

**Comment by StrongMonkey** [comment]
I believe this is fixed. @izaac

**Comment by izaac** [comment]
Rancher version: `master-head (09/27/2020)` _ec04f78_ Single Rancher
Rancher version: `master-head (09/27/2020)` _ec04f78_ HA k8s RKE with RKE Linode downstream cluster

I no longer reproduce the failure:

> [ERROR] Failed to install system chart rancher-webhook: failed to find chartName rancher-webhook version 0.1.0-beta100: NotFound 404

The other errors are pre-existing from Rancher `v2.4.8` #28954
