### ISSUE TITLE
rancher-webhook does not deploy in local cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29189]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Bring up a master-head / 2.5.0-rc2 - rancher-webhook is not installed in the local cluster.
- Rancher log shows error `2020/09/26 04:17:57 [ERROR] Failed to install system chart rancher-webhook: failed to find chartName rancher-webhook version 0.1.0-beta100: NotFound 404`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - `9de5a85`
- Installation option (single install/HA): HA and single install

**Comment by jiaqiluo** [comment]
reopen this issue because rancher-webhook is not deployed in the latest master-head 9de5a85

![image](https://user-images.githubusercontent.com/6218999/94331263-f4ba4900-ff7f-11ea-8e77-07efde313a76.png)

**Comment by sowmyav27** [comment]
**on master-head - commit id: `27000be7`**

rancher-webhook is seen deployed in a local cluster in HA setup.
