### ISSUE TITLE
Add ability to delete storage pools

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#2918]
Separate from deleting volumes. Mentioned in #2893

**Comment by blahRus** [comment]
+1

**Comment by asciifaceman** [comment]
Came here to search for this before I opened it myself +1

**Comment by alexishida** [comment]
+1

**Comment by clintbeacock** [comment]
I'll +1 this as well.  We really need to be able to clean up unused pools.

**Comment by boedy** [comment]
+1

**Comment by cjellick** [comment]
Note to self, when this is implemented, make sure to let @vincent99 know.

**Comment by ibuildthecloud** [comment]
Note to @vincent99, @cjellick will tell you when you need to implement this :)

**Comment by guruvan** [comment]
Is there some sort of guidance on a brute force method that's safe (i.e. emptying the storage_pool and storage_pool_host_map tables in the db or something?) 

This is apparently preventing me from implementing convoy on my production network (and I really need it for several services :)

**Comment by mobiusEnd** [comment]
@guruvan personally i have tried to manually purge all the entities in both tables (if they were not already purged), and it worked. However as I was purging ALL, it was a straightforward process. YMMV

purged existing entities in storage_pool
![screen shot 2016-04-09 at 1 39 28 pm](https://cloud.githubusercontent.com/assets/17175484/14402019/b521bb8e-fe58-11e5-9010-53654f60cb32.png)

and purged storage_pool_host_map directly
![screen shot 2016-04-09 at 1 39 14 pm](https://cloud.githubusercontent.com/assets/17175484/14402020/bff73642-fe58-11e5-8001-f7a2592cca46.png)

**Comment by cjellick** [comment]
Here is some guidance on how to "manually" delete storage pools. I've tested this locally but not exhaustively. So, this isn't officially supported.

Storage pools can be deleted via the API. If you go to the storage pool API for your project (ie http://localhost:8080/v1/projects/1a5/storagepools/), you should be able to find your convoy-nfs or convoy-gluste storage pool. _Note that in the above URL, the 1a5 is my environment id, it wont be the project id for everyone. Go to the API tab to get the proper root to your environment's API endpoint._

Once you've found it, you should be able to deactivate, then remove, then purge (reloading after each action to get the new possible actions).

That will delete the storage pool in the rancher API. But that doesn't clean up everything. You would also need to go to the Applications > Systems tab and delete the convoy-gluster (or whatever you called it) service.

That delete's the convoy containers but that _still_ doesn't clean up everything. You need to go to the hosts and remove /etc/docker/plugins/convoy-gluster.spec file (name may be different) and then restart the docker daemon.

If you do all that, you'll have cleaned up everything you can. However, if you still have containers that are marked as using a convoy-gluster container, the docker daemon will slow down when it tries to manipulate those containers because it will retry for up to 30ish seconds to talk to the now non-existent driver.

Again, this is not a bulletproof officially supported clean up and you might still run into weird edge case issues, but hopefully it helps you out.

**Comment by guruvan** [comment]
@cjellick thanks for this, it's very helpful for this and other issues I'm seeing as well! :) makes the whole process much more clear to me. I presume one should also remove the /var/lib/rancher/convoy/convoy-gluster-UUID as well. I presume I'll run into a few edge cases after having messed around manually in the db to get things running. Thanks to @picoCreator 's suggestion I've manually done some similar in the db, and had success. Using the API seems a more straightforward & safer process. 

The last point is enlightening - I'll keep my eye out for this.

**Comment by cjellick** [comment]
@ibuildthecloud this should be getting addressed as part of your volume driver/storage pool refactor?

**Comment by deniseschannon** [comment]
Closing after talking to @cjellick 

when you delete a storage infrastructure stack, the storage driver is deleted and when the driver is deleted, the storage pool *IS* deleted too.

**Comment by asciifaceman** [comment]
Sometimes being subscribed to an issue for a year can pay off

**Comment by beatcracker** [comment]
Had the same issue after upgrade to Rancher v1.2.2. `Convoy` storage pool was removed, and replaced with `rancher-nfs` instead. But it still showed in UI.

Here is how to remove storage pool in `v2-beta` API:

1. Go to http://rancher-server:8080/v2-beta/projects/1a5/storagepools/
2. Search (Ctrl-F) for storage pool to remove (`convoy-nfs`)
3.  Click on `self` link (e.g.: http://rancher-server:8080/v2-beta/projects/1a5/storagepools/1sp3)
4. Click `deactivate`, then `remove`, then `purge` (reloading after each action to get the new possible actions).

See @cjellick 's [note](https://github.com/rancher/rancher/issues/2918#issuecomment-217216012) for info about  environment IDs.

**Comment by fabiorauber** [comment]
@beatcracker Thanks! Worked like a charm!

**Comment by zambon** [comment]
@beatcracker @fabiorauber you may also have to remove the storage plugin from the hosts, restarting Docker Engine around that. At least that is the case in Rancher v1.1. Something like:

```
systemctl stop docker.service
rm /etc/docker/plugins/<storage-pool-name>.spec
systemctl start docker.service
```

**Comment by fabiorauber** [comment]
@zambon Thanks, docker was indeed complaining about a missing convoy plugin.
