### ISSUE TITLE
GlobalDNS assigns local cluster IP in Cloudflare

### ISSUE THREAD

**Issue by abhi1693** [rancher/rancher#29191]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create GlobalDNS provider for Cloudflare with proxy enabled
2. Create GlobalDNS entry on the project
3. Inside the local cluster on the ingress, add an annotation: `external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"`

**Result:**
My local cluster has private IP addresses and the project cluster has public IP addresses. The IP in Cloudflare gets mapped to the private IP of the local cluster instead of the public IP of the project cluster with proxy disabled. The proxy is disabled which it should be but the IP addresses point to the local cluster which causes the DNS resolution to fail.

**Other details that may be helpful:**
This only happens intermittently and I have not found a cause to this so far.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.8
- Installation option (single install/HA): HA

**Comment by abhi1693** [comment]
I have also noticed that initially the cluster endpoint indeed shows up with public IPs however after a few minutes it automatically changes to the private IPs of the local cluster.

@maggieliu Sorry to tag you here, but this issue is causing our production workloads to lose external access

**Comment by maggieliu** [comment]
@sangeethah Can QA help and see if they can reproduce this issue?

**Comment by abhi1693** [comment]
I did more extensive testing on this. In very rare cases, the annotation `kubernetes.io/ingress.class: rancher-external-dns` is not set on my ingress properly. I'm doing this programmatically now to make sure that the Public IPs are picked up.

I'm still unaware of why this annotation is not setting up.

**Comment by izaac** [comment]
@abhi1693 I can't reproduce in `v2.4.10` I have a couple of questions.

You've mentioned that the local HA cluster has only Internal IPs? Or those nodes have both internal and external IPs ?
The downstream cluster has only External IPs.

I've set the annotation as you mentioned in the local HA cluster ingress. `external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"`
I tried deploying a Multi-Cluster App selecting only a project in the downstream cluster.
I see the DNS entries created in Cloudflare all having external IP addresses.
My local HA cluster and downstream cluster have both internal/external IP addresses.

**Comment by abhi1693** [comment]
@izaac My local HA cluster only has private IPs. It is behind an L4 NGINX proxy. My downstream clusters only have Public IPs. Here is my exact scenario for you to replicate:

1. I have 8 downstream hardened clusters. The hardening guide used was taken from your docs as a reference.
2. My local HA cluster is hardened too
3. There are no apps on my local cluster except monitoring and logging that comes with Rancher
4. On all of my downstream cluster, I'm running MQTT broker for which I was doing the following
  a. add {'8883':'default/mqtt:8883'} to `tcp-services` configmap under `ingress-nginx` -> this was to allow `8883` port to be opened
  b. add a global dns entry for the broker
  c. add the `external-dns.alpha.kubernetes.io/cloudflare-proxied: false` annotation on the local cluster to the appropriate ingress
  d. The first ingress always worked without any issues
  e. All the subsequent ingresses worked initially but then `kubernetes.io/ingress.class: rancher-external-dns` annotation was getting lost automatically which caused the public IPs to get replaced with private ones from my local HA cluster.

To tackle this lost annotation issue, I'm running a cron job on my local cluster that if the dns resolution fails, it checks the annotations and fixes them for us.

Let me know if you need any other information

**Comment by abhi1693** [comment]
I have not faced this issue since upgrading to 2.5.x. This can be closed if you guys are not working on this.
