### ISSUE TITLE
"Explorer" link in Cluster detail and Nav links for features under "Tools" is available for clusters are not functional when the clusters are still in "provisioning" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#29199]
Rancher server version - Build from master -`27000be`

Steps to reproduce the problem:
Create a custom cluster and do not add any nodes so that cluster is in "provisioning" state.

Scenario 1:
Clicking on the "Explorer" button for the cluster in the cluster list view takes user to a blank dashboard page.

<img width="1233" alt="Screen Shot 2020-09-27 at 12 58 23 PM" src="https://user-images.githubusercontent.com/4266958/94374440-2555cc00-00c1-11eb-850c-60f0f85571bb.png">

Scenario 2:
Navigate to "Tools":
<img width="1198" alt="Screen Shot 2020-09-27 at 12 34 52 PM" src="https://user-images.githubusercontent.com/4266958/94374318-479b1a00-00c0-11eb-8124-519e30192c1c.png">

Navigating to "cluster explorer" link that is presented when Notifier, Logging, Monitoring, Istio, CIS links are accessed , results in rendering a "404 not found " Dashboard page.

We should not be showing cluster explorer links in these cases.

**Comment by izaac** [comment]
Rancher version: `master-head (09/29/2020)` _ec04f78_ HA k8s with DO RKE and GKE downstream clusters.

These links are now available until the cluster is in *Available* state.
Opened a separate issue for the Monitoring link returning 503 #29234
