### ISSUE TITLE
Cloud Providers tooltip has a broken link

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29192]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Create or edit cluster (I used RKE Linode)
- Hover the mouse pointer over the cloud providers tooltip.
- Click the link

**Result:**

![Screen Shot 2020-09-26 at 1 42 22 PM](https://user-images.githubusercontent.com/27659/94349959-72bd3500-fffe-11ea-8ff5-0be6d5497f36.png)

The link is returning 404

https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/

**Other details that may be helpful:**

**Environment information**
- Rancher version: `master-head (09/26/2020)` _27000be_
- Installation option: single

**Comment by deniseschannon** [comment]
I cannot find any existing documentation of in-tree cloud providers as k8s is moving forward with moving in tree into out of tree: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20190125-removing-in-tree-providers.md

**Comment by deniseschannon** [comment]
I've updated to this link and updated the label to "In-tree Cloud Providers" to set up for when we also move to out of tree support: https://kubernetes.io/blog/2019/04/17/the-future-of-cloud-providers-in-kubernetes/

**Comment by izaac** [comment]
Rancher version `master-head (09/27/2020)` _ec04f78_

- Checked the different infrastructure providers UI forms.
- A new tab is open in browser.
- This page opens as expected: https://kubernetes.io/blog/2019/04/17/the-future-of-cloud-providers-in-kubernetes/
- No longer a 404 link. 


## Link text in Create and Edit Forms




### Create Form

![Screen Shot 2020-09-27 at 2 54 24 PM](https://user-images.githubusercontent.com/27659/94376826-eaa85f80-00d1-11eb-9a4c-51034f23c286.png)


![Screen Shot 2020-09-27 at 2 55 38 PM](https://user-images.githubusercontent.com/27659/94376835-f3993100-00d1-11eb-999d-aff8a404cd07.png)


### Edit Form

![Screen Shot 2020-09-27 at 2 59 29 PM](https://user-images.githubusercontent.com/27659/94376854-10cdff80-00d2-11eb-8431-85ae4701bffe.png)


![Screen Shot 2020-09-27 at 2 57 31 PM](https://user-images.githubusercontent.com/27659/94376860-19263a80-00d2-11eb-86c6-070285369228.png)
