### ISSUE TITLE
Unable to execute shell after setting a new CATTLE_AGENT_IP to private IP address for existing host

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#292]
Version: v0.12.0

Steps to Reproduce:

1. Create an environment with at 1 host.  
1. Create ubuntu containers on host
1. Update private IP of host. 
1. Attempt to execute shell of container on host.

Result: Unable to connect the container. It only shows connecting.
Expected Result: To be able to access the execute shell prompt.
![screen shot 2015-03-23 at 9 41 00 am](https://cloud.githubusercontent.com/assets/11410997/6785075/bcbc70b4-d140-11e4-80d0-243165f7f9c1.png)

Note: I still get this error after restarting all my containers including the network agent container. I also get this error if I delete/purge all containers (including network agent) and start a new container.

**Comment by vincent99** [comment]
The shell, logs, and cpu/memory stats for a host/container all open a web socket from your browser to directly to the (container's) host.  So the IP address of the host needs to be reachable from your computer.

**Comment by deniseschannon** [comment]
Is it possible to update the UI so that some kind of user friendly message would be shown to indicate that the IP is not reachable from your computer and that's why those functions don't work?

**Comment by vincent99** [comment]
Yes, #240.  I won't know a specific reason why though, just more of a "connection {timed out, was rejected}, please figure out why {host ip}:{port} isn't reachable".  We also have a way to proxy these websockets through the master(s) so that the individual hosts don't have to be available on the public internet.  This isn't on by default, but will probably need to be soon for SSL support.

**Comment by cglewis** [comment]
I'm getting:

```
WebSocket connection to 'ws://172.17.42.1:9345/v1/stats/e1147318-1457-4695-b1c7-ab900aea6eea?
```

Is there a way to set it to the host ip instead of the docker bridge ip?

**Comment by ibuildthecloud** [comment]
@cglewis You can set -e CATTLE_AGENT_IP=x.x.x.x in the Docker run command when you register the host to force the host to a specific IP

**Comment by cglewis** [comment]
@ibuildthecloud perfect, thanks!

**Comment by grigio** [comment]
I'm having the same issue using the [Vagrantfile](https://github.com/rancherio/os-vagrant/blob/master/Vagrantfile). @ibuildthecloud You mean to run the agent command like this?

```
sudo docker run -d --privileged -e CATTLE_AGENT_IP=172.19.8.101 -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.5.2 http://172.19.8.101:8080/v1/scripts/C5287CC66C698E4F89C5:1429398000000:51D982Oj40h0VK1A21o3H2QA
```

**Comment by cjellick** [comment]
@deniseschannon With the introduction of websocket-proxy, this issue should be fixed (or more correctly, it just isnt applicable any more).

**Comment by deniseschannon** [comment]
V0.28.0 Verified fixed with websocket proxy.
