### ISSUE TITLE
Can't create Packet host/machine

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2920]
Version - Master 12/03

Steps:
1.  Try to add a Packet host

Results:
Error in driver during machine creation: Too many retries waiting for SSH to be available. Last error: Maximum number of retries (60) exceeded

Expected:
Should create

Comments:
It was created on the Packet side but wasn't able to finish.

**Comment by tfiduccia** [comment]
Tried a couple more times with same result.  Was able to create one from previous build.

**Comment by cjellick** [comment]
Assigning to @sangeethah since @tfiduccia doesn't work until later in the week

**Comment by sangeethah** [comment]
Tested with v0.49.0-rc3

Able to add Packet host successfully.
