### ISSUE TITLE
[Authentication IdP] Login with Keycloak user makes me login as Default Admin

### ISSUE THREAD

**Issue by Amaujow** [rancher/rancher#29207]
**What kind of request is this (question/bug/enhancement/feature request):**
I use an IdP (Keycloak) for Rancher's authentication. 
There is a bug when login Rancher with one of the Keycloak users, i'm authenticated as Default Admin instead of the Keycloak user. 
But for others Keycloak Users, the authentication works fine. 

**Steps to reproduce (least amount of steps as possible):**
I configure authentication with Terraform like that : 
```
resource "rancher2_auth_config_keycloak" "keycloak" {
  display_name_field = "givenName"
  groups_field = "member"
  idp_metadata_content = "<keycloak entity descriptor>"
  rancher_api_host = "<rancher-url>"
  sp_cert = <<EOF
-----BEGIN CERTIFICATE-----
<public key>
-----END CERTIFICATE-----
EOF
  sp_key = <<EOF
-----BEGIN PRIVATE KEY-----
<private key>
-----END PRIVATE KEY-----
EOF
  uid_field = "givenName"
  user_name_field = "email"
}
```
And i configure my keycloak client like that : 

![image](https://user-images.githubusercontent.com/65776377/94419440-10da0800-0183-11eb-8ef0-3c33d3199aa1.png)

With mappers : 
![image](https://user-images.githubusercontent.com/65776377/94419497-2a7b4f80-0183-11eb-964e-4004f7f4e501.png)

**Result:**
Only for my user "devjava", there is a bug with the authentication process : 

1. I'm authenticating with my devjava user thanks to keycloak.

2. I'm logged in as a keycloak user : 
![image](https://user-images.githubusercontent.com/65776377/94419923-b0979600-0183-11eb-82d0-9718f23cb3c4.png)

3. But when i go in "Preference", i realize i'm logged in as Default Admin : 
![image](https://user-images.githubusercontent.com/65776377/94419998-cefd9180-0183-11eb-867b-58438fb94ae5.png)

**Other details that may be helpful:**
When i applied the terraform file that configure Rancher, I was already connected as Default Admin on Rancher. 

**Environment information**
- Rancher version : v2.4.5
- Installation option (single install/HA): single install 

**Cluster information**
- Cluster type :  Cloud Kubernetes managed by OVH 
- Kubernetes version : version 1.18 

Does someone already had this problem ?

**Comment by fad3t** [comment]
Hi,
That's most likely because your "external principal" and "local principal" (local admin) share the same ID.
Cf. https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/#external-authentication-configuration-and-principal-users
Kr,
Fred.
