### ISSUE TITLE
Rancher Migration

### ISSUE THREAD

**Issue by nileshbhadana** [rancher/rancher#29204]
We are running Rancher in a EKS cluster and managing our multiple Kubernetes clusters using Rancher.
Now we are planning to migrate this to another Region in AWS. We want to migrate the Rancher setup to another EKS cluster in different region.
Gone through the documentations but didn't find anything on this.
Can any help around this.

Thanks in Advance

**Comment by mrajashree** [comment]
@nileshbhadana we have a new feature in 2.5.x with which you can migrate rancher to a new cluster. To use it you'll have to upgrade to 2.5.2 (stable release), and install the app `rancher backups` in the local cluster (where rancher is running). These [docs](https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/migrating-rancher/) have steps for it
