### ISSUE TITLE
Not able to log in rancher server after a while - 404 errors seen on v3/settings , v3/preferences,v3/users 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#29201]
Rancher server version - Build from master - `27000be`

Steps to reproduce the problem:
Had a  HA setup .
Created 1 downstream cluster and create few resources in it.

After a while , I am not able to log in to rancher server UI anymore.

After providing the correct username/password (global admin) , I am redirected back to log in page.

I see 404 errors seen on v3/settings , v3/preferences,v3/users calls made as part of log in.

```
Request URL: https://<url/v3/settings/server-url?sort=nameRequest 
Method: GET
Status Code: 404
```

When attempting to access the same request from browser, it works.

**Comment by maggieliu** [comment]
related to: https://github.com/rancher/rancher/issues/29206

**Comment by tallmanbrew** [comment]
After upgrading from 2.4.6 to 2.5 I see 404 errors seen on v3/settings , v3/preferences,v3/users calls made as part of log in.
The login page shows the Howdy message with a 404 error below it and a reload button below that. Never even get a chance to login.

**Comment by sangeethah** [comment]
@tallmanbrew Could you try to clear your cache and log in from a different browser to see if it works ?

**Comment by tallmanbrew** [comment]
Yeah I have done that new browsers, cleared cache browsers, different machines. All result in the 404 screen.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `7eb1792` and master-head commit id: `b7e8c0d3d1`**

This issue is not seen. Closing it.

Will log a new one if seen again.
