### ISSUE TITLE
Is there a way to disable the namespace created for every user?

### ISSUE THREAD

**Issue by sharkymcdongles** [rancher/rancher#29202]
When a user is created it creates a namespace named after the user like: u-oqfzaerwvc

Is there any way to disable this feature?

**Comment by vincent99** [comment]
No, they are used to store things that are scoped to a user.  It is recommended that the cluster Rancher is installed on be used for only that; if you're not careful about the RBAC granted, you can easily create situations where a user of the management cluster can edit things to escalate their privilege to the other clusters registered to Rancher.
