### ISSUE TITLE
rancher-catalog-service should die if cattle stops

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#2921]
When cattle is starting rancher-catalog-service, rcs should monitor cattle and die if cattle dies. Without this, if you restart cattle locally, rcs cannot be restarted because the port is in use.

Here's how we do it in websocket-proxy:
https://github.com/rancher/websocket-proxy/blob/master/proxy/proxy.go#L78-L93

**Comment by prachidamle** [comment]
@ibuildthecloud do we need this change? Or does Cattle take care of shutting down the rancher-catalog-service while being stopped?

**Comment by prachidamle** [comment]
@cjellick We do take care of this in the "linux" version as mentioned by @ibuildthecloud. Here https://github.com/rancher/rancher-catalog-service/blob/master/manager/catalog_manager_linux.go

**Comment by cjellick** [comment]
@prachidamle in this issue I am referring to when we run locally while developing. @ibuildthecloud is the only rancher/cattle dev that runs linux on his laptop. Everyone else gets into a state where they have to manually kill processes.

Its nuisance when developing locally but _definitely not_ a release 1.0 issue.

 I eventually just built an alias that I run every single time I start cattle:
```
alias dierc='pkill -9 rancher-catalog; pkill -9 rancher-compose-executor'
```

I still feel we should change it so that it behaves like websocket proxy and kills itself but if @ibuildthecloud wants to overrule me and close this issue, so be it.
