### ISSUE TITLE
Rancher's Apps are attached to an LDAP user, causing a failure to deploy later on

### ISSUE THREAD

**Issue by royerhq** [rancher/rancher#29211]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Get any LDAP user to deploy an App. 
2) Deactivate/Remove LDAP user and/or lower its permissions in Rancher to Read only 
3) Try to upgrade the App with an LDAP user that has Full Access (Project Owner).

**Result:**
App will fail to deploy because LDAP user that was used to deploy the App does not exist and/or no longer has enough permissions

**Other details that may be helpful:**
The below snippet shows the app has a creatorId. Such ID is what prevents the upgrade for happening. The creatorId, should have 0 impact when deploying an app. This causes issues at deployment times
```
],
"created": "2019-11-15T00:00:24Z",
"createdTS": 1573776024000,
"creatorId": "u-ovbat2zvx5t",    <----- This is what I would like to change 
"externalId": "catalog://?catalog=test&template=admin-test&version=v1.15.0",
"id": "p-zjcrj:admin-test",
```

**Environment information**
- Rancher version - 2.3.5
- Installation option (single install/HA): HA

**Comment by cambierr** [comment]
this bug also affects us
