### ISSUE TITLE
Error in importing existing cluster: "Failed to connect to proxy" error="websocket: bad handshake" #

### ISSUE THREAD

**Issue by axistwelve** [rancher/rancher#29217]
Just created a new issue as wasn't sure if I should comment on a closed ticket.

Original ticket Reference https://github.com/rancher/rancher/issues/18831
Hi,

I am experiencing exactly this same issue. Rancher and the new cluster are on the same subnet. I have created another cluster against this rancher on a different subnet in the different DC fine. But this is not working, I rebuild using flannel and this hasn't helped in solving

Using the script above I am able to log  the node in rancher but it stay stuck in registering.

Using TOKEN: f4k79b2mrl9sq4f48lvthpvp6mwwgr9rlwmvvfj5sl5dfv2c2l2hkn
Using URL: https://abc.sh/v3/connect/register
Using PARAMS:
{
  "Node": {
          "customConfig": {
            "address": "192.168.15.200",
            "roles": [
            ],
            "labels": [
            ]
          },
          "etcd": false,
          "controlPlane": false,
          "worker": false,
          "requestedHostname": "192.168.15.200"
}
}
*   Trying 192.168.15.51...
* TCP_NODELAY set
* Connected to rancher.a12.sh (192.168.15.51) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.abc.sh
*  start date: May 22 20:54:21 2020 GMT
*  expire date: May 23 20:54:21 2022 GMT
*  issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*  SSL certificate verify ok.
> GET /v3/connect/register HTTP/1.1
> Host: rancher.abc.sh
> User-Agent: curl/7.58.0
> Accept: */*
> Connection: Upgrade
> Upgrade: websocket
> Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==
> Sec-WebSocket-Version: 13
> X-API-Tunnel-Token: f4k79b2mrl9sq4f48lvthpvp6mwwgr9rlwmvvfj5sl5dfv2c2l2hkn
> X-API-Tunnel-Params: ewogICJOb2RlIjogewogICAgICAgICAgImN1c3RvbUNvbmZpZyI6IHsKICAgICAgICAgICAgImFkZHJlc3MiOiAiMTkyLjE2OC4xNS4yMDAiLAogICAgICAgICAgICAicm9sZXMiOiBbCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJsYWJlbHMiOiBbCiAgICAgICAgICAgIF0KICAgICAgICAgIH0sCiAgICAgICAgICAiZXRjZCI6IGZhbHNlLAogICAgICAgICAgImNvbnRyb2xQbGFuZSI6IGZhbHNlLAogICAgICAgICAgIndvcmtlciI6IGZhbHNlLAogICAgICAgICAgInJlcXVlc3RlZEhvc3RuYW1lIjogIjE5Mi4xNjguMTUuMjAwIgp9Cn0K
>
< HTTP/1.1 101 Switching Protocols
HTTP/1.1 101 Switching Protocols
< Server: nginx/1.15.6
Server: nginx/1.15.6
< Date: Mon, 28 Sep 2020 10:32:22 GMT
Date: Mon, 28 Sep 2020 10:32:22 GMT
< Connection: upgrade
Connection: upgrade
< Upgrade: websocket
Upgrade: websocket
< Sec-WebSocket-Accept: qGEgH3En71di5rrssAZTmtRTyFk=
Sec-WebSocket-Accept: qGEgH3En71di5rrssAZTmtRTyFk=
< Strict-Transport-Security: max-age=15724800; includeSubDomains
Strict-Transport-Security: max-age=15724800; includeSubDomains
* TLSv1.2 (IN), TLS alert, Client hello (1):
* Empty reply from server
* Connection #0 to host rancher.abc.sh left intact
curl: (52) Empty reply from server

I was able to create the Cluster in reverse using the "From existing nodes" option but this doesn't allow me to update the default max-pods limit which I need as these are large boxes in a dev cluster a 110 pods per box is way to small.

I am using rancher 2.4.8

_Originally posted by @axistwelve in https://github.com/rancher/rancher/issues/18831#issuecomment-699927896_

**Comment by axistwelve** [comment]
Ok this still isn't working, but I have found a work around. If I create using the "From existing nodes" option for bare metal, I can edit the yaml file in the interface and update the services to add the extra_opts for max-pods: NNN

**Comment by sfhl** [comment]
Hi there,

is there any solution to this?
I am using rancher (v2.4.12) on kuernetes behind a traefik instance, which is also serving tls/ssl for this domain. I am trying to import some clusters, but getting the same errors.
Testing websockets from he nodes, gives no errors.

```
HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Sec-Websocket-Accept: qGEgH3En71di5rrssAZTmtRTyFk=
Upgrade: websocket

▒{"name":"ping","data":{}}▒{"name":"ping","data":{}}
```

Any helo woudl be much appreciated.

Thanks in advance!

**Comment by xkkker** [comment]
> 

hi, did you fix this problem? Have the same problem here~

**Comment by xkkker** [comment]
> I found that my rancher agent could see the rancher control instance. I was able to test this by exec onto the rancher agent container and run a curl https:///ping and you should get pong back. If it times out it means you have a routing issue. You can edit the agent pod setup to add hosts entries or dns etc. start there see where you get to

Thanks for your reply.
I get the response like this. It seems that rancher can be reach successfully. Any other ideas? 
And I refresh the certificate this morning.I wonder there is some relations ?
