### ISSUE TITLE
[charts] Longhorn windows clusters tolerations

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#29220]
Longhorn doesn't need to support windows nodes, but it does need to add the correct selectors and tolerations to handle windows clusters.

**Comment by yasker** [comment]
@cbron What exactly should we do here? Any examples?

**Comment by cbron** [comment]
Yes I'll send you doc

**Comment by yasker** [comment]
Examples here:

https://github.com/rancher/rancher/pull/28685/files

https://github.com/rancher/system-charts/blob/dev-v2.4/charts/rancher-monitoring/v0.1.2/templates/_helpers.tpl#L134-L151

**Comment by yasker** [comment]
@shuo-wu IIRC, we have added this for the v1.1.0 chart, right? if so, can you point out the modification so we can move this to the testing phase.

**Comment by shuo-wu** [comment]
I think the essential is this annotation: https://github.com/rancher/charts/blob/fa2d96adcf597382be2a93bd20760c3601010294/packages/longhorn/longhorn.patch#L54

**Comment by cbron** [comment]
There are two parts to our windows support: 
1. Adding an annotation to the chart which says what OS's the chart supports (Shuo's link in comment above)
2. Either adding windows images to the manifests or adding taints/tolerations to the chart so a linux-only deployment doesn't end up on a windows node.

Part 2 still needs to get done. I don't see it in the various workloads: 
* https://github.com/rancher/charts/blob/dev-v2.5/charts/longhorn/templates/daemonset-sa.yaml
* https://github.com/rancher/charts/blob/dev-v2.5/charts/longhorn/templates/deployment-driver.yaml

**Comment by shuo-wu** [comment]
Actually I am worried about the Longhorn workloads dynamically deployed by the longhorn manager. The tolerations and node selectors cannot be applied to those workloads.

**Comment by cbron** [comment]
Without those tolerations/selectors then Longhorn will not work on a windows cluster, meaning a cluster with 1 linux node and multiple windows nodes.

**Comment by yasker** [comment]
@shuo-wu So it seems the WIndows support is not completed? Since it involves taint/node selector needs to be added into dynamically provisioned workloads, it needs to be done as part of the v1.1.1 release. Can you file an issue in Longhorn and track it?

**Comment by deniseschannon** [comment]
@yasker Is there an issue associated with this?

@Jono-SUSE-Rancher We should add this to the project plan to track independently with the Longhorn team.

**Comment by yasker** [comment]
The Longhorn issue is https://github.com/longhorn/longhorn/issues/2199

**Comment by cbron** [comment]
Is this finished then ?

**Comment by yasker** [comment]
Waiting for reverting the annotation removal and merge the PR.

**Comment by innobead** [comment]
This was supported in longhorn char 1.1.1 which was already delivered, so I think probably we can close this.

**Comment by Jono-SUSE-Rancher** [comment]
Thanks for the update @innobead. I will close with your recommendation.

**Comment by Jono-SUSE-Rancher** [comment]
I lied. @khushboo-rancher - Can you confirm this is good to go and close it when QA is pleased? :)

**Comment by khushboo-rancher** [comment]
This is working fine with Rancher-master `8073489`

Validation - **Pass**

The longhorn app doesn't appear for windows cluster but one can install using helm and putting the node-selector.

**Comment by Jono-SUSE-Rancher** [comment]
Thank you kindly @khushboo-rancher - Be pleased! 😁

**Comment by cbron** [comment]
@khushboo-rancher 
> one can install using helm and putting the node-selector.

That should happen automatically, users shouldn't have to input the Rancher taints/tolerations to be able to deploy to Rancher's windows clusters. I don't see them in here: 
* deployment: https://github.com/rancher/charts/blob/dev-v2.5/charts/longhorn/longhorn/1.1.100/templates/deployment-driver.yaml#L94-L101
* values: https://github.com/rancher/charts/blob/dev-v2.5/charts/longhorn/longhorn/1.1.100/values.yaml#L126-L135

**Comment by cbron** [comment]
Right, forgot about that.
For future reference see the above link. We choose not to add them to longhorn by default. Rancher's cluster explorer apps will not display longhorn in a mixed cluster, and solution to getting it working via API (or cluster-manager charts) is in longhorn docs.
