### ISSUE TITLE
What's New in 2.5 showing in v2.4.8 when rancher manages rancher cluster

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#29238]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Install Rancher 2.5.0-rc2
2. Create a new k3s 1.19.2 cluster with two master nodes.
3. Import cluster into Rancher 2.5.0-rc2
4. Add https://releases.rancher.com/server-charts/latest as a global catalog
5. Deploy Rancher 2.4.8 onto the imported k3s 1.19.2 cluster using the app catalog using the System project. Using addLocal=off, replicas=2, other options should not matter.
6. Log into the new Rancher 2.4.8 cluster as admin.

**Result:**
![image](https://user-images.githubusercontent.com/468462/94591942-9c17d400-023d-11eb-941f-ee5d12e90049.png)
Note, version in bottom left corner is v2.4.8, but seeing "What's New in 2.5" screen.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.8
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
AWS EC2 - m5.large - 2vCPU, 8GB RAM
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2+k3s1", GitCommit:"d38505b124c92bffd45f6e0654adb9371cae9610", GitTreeState:"clean", BuildDate:"2020-09-21T17:00:07Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):
containerd 1.4.0

gzrancher/rancher#12528

**Comment by vincent99** [comment]
The code to show this doesn't even exist in 2.4.  So you must be getting the index.html from the "outer" rancher, or the "inner" one is pointed at a master build of the UI instead of its packaged copy, or something like that.

I suspect this has never really worked but  nobody has noticed that the UI build is always that of the "outer" Rancher.

**Comment by dnoland1** [comment]
I might have also had a browser caching issue because at one point when I clicked the version link in the bottom left corner it showed "Rancher" component was v2.5, but the "User Interface" was v2.4. Did a force reload on the browser and they seemed to sync up. Have no plans to run a v2.4 cluster managed by a v2.5 cluster but will run v2.5 managed by v2.4. I'm ok closing this one for now.

**Comment by sowmyav27** [comment]
**Validated v2.5 rancher managed by v2.4 rancher**

- Create a Rancher HA installation (2.4.8)
- Create a k3s cluster
- Import the k3s cluster into Rancher 
- Install Rancher onto the k3s clusters (2.5.1)
- "Whats New" page is seen only on 2.5.1.

As per comments - https://github.com/rancher/rancher/issues/29238#issuecomment-706488931 closing this issue now.
