### ISSUE TITLE
403 Forbidden error when trying to port-forward workload using Rancher kubeconfig

### ISSUE THREAD

**Issue by ntx-ben** [rancher/rancher#29248]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Log into remote blank Alpine 3.12 VM
- Install k3s v1.19.2+k3s1 (`INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --disable servicelb,traefik"`)
- Deploy istio v1.7.2 with default profile
- Deploy metallb v0.9.3
- Deploy Rancher v2.4.8
- Deploy any workload exposing a port (i.e. httpbin)
- Copy&Paste the Admin kubeconfig file from Rancher UI to local kubeconfig file (edit to change IP for remote VM)
- Locally run `kubectl --kubeconfig ./rancherconfig.yaml port-forward svc/httpin 8080:80 -n httpbin`

**Result:**
`error: error upgrading connection:`

When using the k3s kubeconfig (`/etc/rancher/k3s/k3s.yaml`) locally with kubectl, port-forwarding works. However, when trying to use Rancher's kubeconfig file (under Admin user), I get the error mentioned earlier. Adding -v9 to kubectl, I can see this:

`I0929 14:48:53.697686   19304 round_trippers.go:443] POST https://k8s.REDACTED.com/k8s/clusters/c-bcrmr/api/v1/namespaces/httpbin/pods/httpbin/portforward 403 Forbidden in 62 milliseconds`

Istio's logs also show the same error.

Since I am the Admin, I don't see what other permission I would need to add for this to be allowed. Any clues?

Thanks

**Environment information**
- Rancher version v2.4.8
- Single k3s cluster, v1.19.2+k3s1

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Self-Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.19.2

**Comment by pgcayen** [comment]
Currently affecting my teammates and me. We cannot port-forward any of our services for debugging purposes...

**Comment by GodSpeedXI** [comment]
Oh, now 2021, there are no any solution. 😭

**Comment by kungfuchicken** [comment]
👀

**Comment by kungfuchicken** [comment]
Are you running Istio and the Nginx ingress, or just Istio?

**Comment by GodSpeedXI** [comment]
> Are you running Istio and the Nginx ingress, or just Istio?

I need to save cost on aws nlb. so, I created only istio ingress and bypass to rancher pod.

**Comment by ntx-ben** [comment]
Updated Rancher to v2.5.6, still seeing this issue...

**Comment by ntx-ben** [comment]
Updated to Rancher v2.6.0, still seeing this issue

**Comment by anders-swanson** [comment]
Issue is still present in rancher 2.6.8 - cannot exec, attach, or port-forward with kubectl when rancher runs behind an NGINX proxy. Believe to be related to the use of SPDY in these kubectl commands.
I tested directly with an NGINX reverse proxy directly to the kubernetes API (without the rancher proxy), and the connection upgrade to SPDY worked. So may be an interaction between the NGINX proxy and the rancher proxy that breaks the connection.

**Comment by ntx-ben** [comment]
Running v2.7.8 and still having this issue...
