### ISSUE TITLE
Unable to load Helm charts with "+" in the version

### ISSUE THREAD

**Issue by bpfoster** [rancher/rancher#29244]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):** Attempt to launch a helm chart with a `+` in the version.

**Result:**
Red popup -
```
Error loading app data
catalogtemplateversions.management.cattle.io "chart-name-0.1.1+123" not found
```

**Other details that may be helpful:**
Per Helm documentation, valid [SemVer 2.0](https://semver.org/spec/v2.0.0.html) versions are acceptable.  If we use the version format of `<version core> "+" <build>`, Rancher is unable to load the chart and provides the aforementioned error.  If I replace `+` with `-`, Rancher loads the chart just fine.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.8
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted?
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud.  4 vCPU / 16 GiB RAM
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:09:53 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:16:24 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by PhilipSchmid** [comment]
This issue is still relevant as for example Rancher 2.5.9 still fails with `Error loading app data catalogtemplateversions.management.cattle.io "sonarqube-sonarqube-lts-1.0.18+121" not found` when trying to deploy the "sonarqube-lts" Helm chart from the [official repo](https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube-lts) https://SonarSource.github.io/helm-chart-sonarqube.

![image](https://user-images.githubusercontent.com/5549063/136566999-9d8316eb-b4fa-4142-98b7-c9e6719ff106.png)

Rancher has the regarding CR (`catalogtemplateversions.management.cattle.io`) stored with a `-` between `<VERSION>-<Build Metadata>`:
```
$ k get catalogtemplateversions.management.cattle.io | grep sonar
sonarqube-sonarqube-1.1.1-98                                                 43m
sonarqube-sonarqube-1.1.3-107                                                43m
sonarqube-sonarqube-1.1.6-121                                                43m
sonarqube-sonarqube-dce-0.1.2-121                                            43m
sonarqube-sonarqube-lts-1.0.16-98                                            43m
sonarqube-sonarqube-lts-1.0.17-107                                           43m
sonarqube-sonarqube-lts-1.0.18-121                                           43m
```

Nevertheless, according to https://semver.org/#spec-item-10 `<VERSION>+<Build Metadata>` would be valid semver.

Thanks & regards,
Philip

**Comment by PhilipSchmid** [comment]
Unstale

**Comment by PhilipSchmid** [comment]
Unstale

**Comment by PhilipSchmid** [comment]
Unstale

**Comment by bpfoster** [comment]
Unstale

**Comment by PhilipSchmid** [comment]
Unstale
