### ISSUE TITLE
[Logging v2] - rancher-logging should only list chart version 3.6.000 in Dashboard Apps

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29245]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- Install latest master-head
- Dashboard -> Apps & Marketplace
- rancher-logging
- click in the Version dropdown

**Result:**

![Screen Shot 2020-09-29 at 11 31 22 AM](https://user-images.githubusercontent.com/27659/94601896-ff5b3380-0248-11eb-957d-fa8872f3eeeb.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version: `master-head (09/29/2020)` _ec04f78_
- Installation option: HA k8s RKE

**Comment by maggieliu** [comment]
closing this in favor of: https://github.com/rancher/rancher/issues/28872
