### ISSUE TITLE
install-docker scripts broken on CentOS 7/RHEL 7/OEL 7 installations where $releasever is '7Server'

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#29246]
Error seen during install using `https://releases.rancher.com/install-docker/19.03.sh`:

```
failure: repodata/repomd.xml from docker-ce-stable: [Errno 256] No more mirrors to try. 
https://download.docker.com/linux/centos/7Server/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

Manual workaround (credit to https://github.com/docker/for-linux/issues/1111#issuecomment-700084728):
```
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum-config-manager --setopt="docker-ce-stable.baseurl=https://download.docker.com/linux/centos/7/x86_64/stable" --save
```

Upstream:

-  https://github.com/docker/for-linux/issues/1111
- https://forums.docker.com/t/docker-ce-stable-x86-64-repo-not-available-https-error-404-not-found-https-download-docker-com-linux-centos-7server-x86-64-stable-repodata-repomd-xml/98965

**Comment by jlamillan** [comment]
Affects Oracle Linux as well.

**Comment by superseb** [comment]
This should work now, please report if still experiencing issues

**Comment by kiraitachi** [comment]
Hi dont know if its related....but the issue for me happens on Fedora 33. When installing it created the docker repo with "Centos" instead of "Fedora" on the repos.d file.

I had to review the script code and change the following lines:

```
centos|fedora|rhel|ol)
			# installing centos packages
			yum_repo="$DOWNLOAD_URL/linux/centos/$REPO_FILE"
```

Change the "centos" for "fedora" the rest of the script will continue just fine and repo will be created correctly.

Cheers!

**Comment by Yvesco10** [comment]
The answer for this error is very simple.
Watch the solution (with other solutions) on below YouTube channel link:

https://www.youtube.com/watch?v=vQROyY1ThqM&list=PLpccrVgzeAplnWU2NHe3EbBh0toyIIVoh
