### ISSUE TITLE
install-docker scipts failing on OL 8.2 ('yum makecache fast')

### ISSUE THREAD

**Issue by jlamillan** [rancher/rancher#29253]
The script to install Docker is failing to install on Oracle Linux 8.2 (Likely affects RHEL, Fedora, etc.) due to an invalid argument `fast` on `yum makecache`. 

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a node using Oracle Linux 8.2: e.g. `Oracle-Linux-8.2-2020.09.23-0`
1. Install Docker using 18.09.sh, 19.03.11, etc.
`curl -sSL https://releases.rancher.com/install-docker/19.03.11.sh |sh`

**Result:**

Fails with:
```sh
+ '[' oraclelinux = redhat ']'
+ sh -c 'yum install -y -q yum-utils'
+ sh -c 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
Adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
+ '[' stable '!=' stable ']'
+ sh -c 'yum makecache fast'
usage: yum makecache [-c [config file]] [-q] [-v] [--version]
                     [--installroot [path]] [--nodocs] [--noplugins]
                     [--enableplugin [plugin]] [--disableplugin [plugin]]
                     [--releasever RELEASEVER] [--setopt SETOPTS]
                     [--skip-broken] [-h] [--allowerasing] [-b | --nobest]
                     [-C] [-R [minutes]] [-d [debug level]] [--debugsolver]
                     [--showduplicates] [-e ERRORLEVEL] [--obsoletes]
                     [--rpmverbosity [debug level name]] [-y] [--assumeno]
                     [--enablerepo [repo]] [--disablerepo [repo] | --repo
                     [repo]] [--enable | --disable] [-x [package]]
                     [--disableexcludes [repo]] [--repofrompath [repo,path]]
                     [--noautoremove] [--nogpgcheck] [--color COLOR]
                     [--refresh] [-4] [-6] [--destdir DESTDIR]
                     [--downloadonly] [--comment COMMENT] [--bugfix]
                     [--enhancement] [--newpackage] [--security]
                     [--advisory ADVISORY] [--bz BUGZILLA] [--cve CVES]
                     [--sec-severity {Critical,Important,Moderate,Low}]
                     [--forcearch ARCH] [--timer]
yum makecache: error: argument timer: invalid choice: 'fast' (choose from 'timer')
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Master
- Installation option (single install/HA):
Single
- OS
Red Hat Enterprise Linux release 8.2 (Ootpa)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
OCI Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory):

```
(paste the output here)
```

- Docker version (use `docker version`):

I've tried to install docker using the `18.09.0.sh` and `19.03.9.sh` scripts

```
(paste the output here)
```

**Comment by superseb** [comment]
EL like OS version 8 support is covered in https://github.com/rancher/rancher/issues/23045
