### ISSUE TITLE
Unable to launch any hosts using the new docker-machine in a local auth setup 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2925]
v0.49.0-rc1

Steps I took:
1. Turned on local auth
2. Added an additional user account
3. Logged in using user account on another browser
4. Use original browser (logged in as admin) to try to launch DO machines. 

Result: `exit status 1` for every host even though machine is created in DO.

**Comment by cjellick** [comment]
Relevant stack trace:
```
goroutine 21 [running]:
github.com/rancher/go-machine-service/handlers.getMachineDir(0x0, 0x0, 0x0, 0x0, 0x0)
        /gprojects/go-machine-service/src/github.com/rancher/go-machine-service/handlers/common.go:35 +0x8d
github.com/rancher/go-machine-service/handlers.PurgeMachine(0xc20830c000, 0xc208080000, 0x0, 0x0)
        /gprojects/go-machine-service/src/github.com/rancher/go-machine-service/handlers/remove.go:22 +0x359
```

**Comment by cjellick** [comment]
Eureka! Figured it out and will fix.
We changed go-rancher client to not return an error if a request gets a 404 response

**Comment by deniseschannon** [comment]
The issue seemed to reside in adding a custom host at the same time as a host using machine. 
 
Did not have the issue in v0.49.0-rc3.
