### ISSUE TITLE
Three groups of Namespace: All in Projects/Namespaces UI

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#29268]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Install Rancher. Using helm chart option restrictedAdmin=true
2. Go to local cluster and click Projects/Namespaces

**Result:**
![image](https://user-images.githubusercontent.com/468462/94645741-74f2ee00-02a1-11eb-9bb2-49a6b70f9df6.png)
Why are there 3 sections with Namespace: All ?

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.5.0-rc3
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
aws ec2 m5.large (2vcpu 8gb ram)
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2+k3s1", GitCommit:"d38505b124c92bffd45f6e0654adb9371cae9610", GitTreeState:"clean", BuildDate:"2020-09-21T17:00:07Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
containerd 1.4.0

**Comment by vincent99** [comment]
They're grouped by projectId (system, none, and default, respectively) but I'm guessing that you don't have RBAC to get the project due to whatever changed on the backend.  This was previously never the case, and then the lack of finding a project is causing a translation that just seems written wrong to be shown as the grouping row.

**Comment by dnoland1** [comment]
Right, setting restrictAdmin to true will limit the RBAC permissions given to the admin, so it's a new use case.
