### ISSUE TITLE
When provisioning images using vSphere- verify object ID, rather than name

### ISSUE THREAD

**Issue by nathanabarry** [rancher/rancher#29276]
When Rancher creates a VM and has not cleaned up the previous instance, it runs into a duplicate name race condition and creates VMs with identical names until the esxi host exhausts the number of registered VMs.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.8` UI: `v2.4.34` |
|Route|`undefined`|

**Comment by nathanabarry** [comment]
closing and moving to rancher machine vsphere provisioner

**Comment by nathanabarry** [comment]
Rancher machine wants issues opened against mainline rancher

**Comment by luthermonson** [comment]
we dont explicitly support esxi but it works a bit and in ways you found it doesnt. we only support full [vsphere](https://rancher.com/support-maintenance-terms/#2.4.x) which does do unique VM names which stops this behavior. if you want to propose a fix via PR to [machine](https://github.com/rancher/machine) we'd consider it but I don't think this is something we can commit to fixing. it is however a call that @deniseschannon needs to make so I'll defer to her final decision.
