### ISSUE TITLE
Not able to deploy a v2 app in a Project

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29282]
**On master-head - commit id: `eb96d76c`**

- on a HA setup, deploy Rancher backup app in Dashboard.
- Select a project - System and enter S3 creds and deploy.
- Error seen

<img width="1687" alt="Screen Shot 2020-09-29 at 8 38 22 PM" src="https://user-images.githubusercontent.com/26032343/94697808-7b0ebc00-02ed-11eb-9feb-8849837849c0.png">

**Note:**
Same issue is seen when CIS Benchmark v2 app is deployed

On clicking on "Install" again, it installs, with no error in the console

**Comment by sangeethah** [comment]
Reopening to get fix in 2.5-release branch

**Comment by cbron** [comment]
Fix is in 2.5 release branch

**Comment by izaac** [comment]
Rancher version: `v2.5-head (10/02/2020)` _v2.5-66f4adaa689b25d104b7dbd630391c2a421a20d4-head_

Not able to reproduce the reported issue with Logging v2 (`rancher-logging`).

**Comment by izaac** [comment]
Validated also with a more recent build of `v2.5-head` _ce572b5_

**Comment by sowmyav27** [comment]
**ON v2.5-head - commit id: `ce572b5` and on master-head commit id: `87e7cdf5af`**

- User is able to deploy CIS v2 and rancher backups in a project - Tested on `System` project. Deployments were seen in the project.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head ce572b5

* Deployed Istio into `default` project
* Workloads show in ember ui default project

**Comment by jiaqiluo** [comment]
rancher:v2.5-head a034814

- Deployed Monitoring v2 into default project
- Workloads show in ember UI default project
