### ISSUE TITLE
Move the "Continuous Delivery" link

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29300]
* Remove the link from the Tools dropdown
* Add "Continuous Delivery" next to  "Apps" under global

**Comment by maggieliu** [comment]
@deniseschannon / @ibuildthecloud  Can you confirm this is what we want to do?

**Comment by sowmyav27** [comment]
**On master-head - commit id: `cb9e8a105c1`**

<img width="820" alt="Screen Shot 2020-10-01 at 11 21 03 AM" src="https://user-images.githubusercontent.com/26032343/94849686-a91dfa00-03da-11eb-8380-cc3e3adb0bc3.png">
- ON clicking on Continuous Delivery takes the user to the cluster explorer page.
<img width="721" alt="Screen Shot 2020-10-01 at 11 37 35 AM" src="https://user-images.githubusercontent.com/26032343/94849716-b63ae900-03da-11eb-8f7b-56d821acac81.png">
