### ISSUE TITLE
[RFE] Update Azure AD API from ADAL to MSAL

### ISSUE THREAD

**Issue by oxr463** [rancher/rancher#29306]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Configure Azure AD for auth, (See: https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/azure-ad).

**Result:**

Rancher is using the deprecated Azure AD graph endpoint, https://graph.windows.net.

There is a new "v2" API for this [[1]], and there is a blog post describing what has changed [[2]].

We need Rancher to upgrade its internal AzureAD auth libraries to use the new MSAL API. The current ADAL-based API is completely deprecated and no longer receives security or feature updates, which could potentially pose a security risk.

**Other details that may be helpful:**

N/A

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Latest
- Installation option (single install/HA): Either

[1]: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration
[2]: https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363

gz#12523

**Comment by miraculixx** [comment]
This may help to assess the priority:

![image](https://user-images.githubusercontent.com/859611/96864815-4bc11a00-1469-11eb-892e-cb297c10e14b.png)

The Learn more link is https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363

**Comment by oxr463** [comment]
> Starting June 30th, 2022, we will end support for ADAL and Azure AD Graph and will no longer provide technical support or security updates. Apps using Azure AD Graph after this time will no longer receive responses from the Azure AD Graph endpoint. Apps using ADAL on existing OS versions will continue to work after this time but will not get any technical support or security updates.

Looks like we still have a couple of years before they stop providing security updates.

**Comment by dramich** [comment]
The go MSAL library is not ready for public preview yet and has no releases so we can not update at this time. Once it's considered stable we can start the transition. 
https://github.com/AzureAD/microsoft-authentication-library-for-go

**Comment by WolfspiritM** [comment]
Right now there doesn't seem to be any way to use AzureAd with Rancher anymore. There is no way to create an app that uses "Azure Active Directory Graph" as that is greyed out. I've opened an issue for that https://github.com/rancher/rancher/issues/35599

**Comment by sunib** [comment]
I also wasn't able to follow this tutorial because of this bug: https://rancher.com/docs/rancher/v2.6/en/admin-settings/authentication/azure-ad/

![image](https://user-images.githubusercontent.com/1828380/152508062-307407fe-f7f9-42bb-9036-418ccd47d000.png)

Could you please update your docs to show how we could achieve this coupling?

**Comment by codecae** [comment]
This issue needs a bump!!!  We're nearing EOL for Azure AD Graph.  On June 30th 2022,  the Azure AD Graph endpoints will stop servicing API calls and will no longer send responses.

**Comment by WolfspiritM** [comment]
> This issue needs a bump!!! We're nearing EOL for Azure AD Graph. On June 30th 2022, the Azure AD Graph endpoints will stop servicing API calls and will no longer send responses.

I agree this needs some attention but luckily Microsoft will not retire Azure Ad Graph on June 30.
They moved the date to at least the end of the year:
https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview

**Comment by maxsokolovsky** [comment]
I am concerned by what @sunib mentioned here and what I checked too: https://github.com/rancher/rancher/issues/29306#issuecomment-1029813915
Looks like in the portal, Azure AD admins cannot create **new** app registrations using permissions from the old Azure AD Graph API. 
Microsoft say they will fully retire the API only at the end of the year, yet they don't allow to assign permissions to new app registrations already?
This means that Rancher users already cannot link a **new** AD app as an Azure AD auth provider. Existing apps can still be registered.

**Comment by sunib** [comment]
There is no way anymore to click this together in the Azure portal, it is said to be possible on the command line but I was not able to get it working within an hour (see the other ticket for a more elaborate summary on that).

I decided not to use Rancher because of this: we can't leave Azure for now (and off course it's important to use single sign on).

**Comment by codecae** [comment]
You can use the new permissions with the old endpoint url and it works fine with new app registrations.

**Comment by maxsokolovsky** [comment]
@codecae, interesting, I am surprised that it works, since Rancher still contacts the old Azure AD Graph endpoint (graph.windows.net). I will try it and see how it works. Perhaps this is Microsoft's handling this internally somehow?

Microsoft will not update the existing main Azure SDK, as far as I understand. Instead, they offer a new separate SDK: https://github.com/microsoftgraph/msgraph-sdk-go

But it is in community preview, so it cannot be used for production at all now. There are alternative SDKs though, such as https://github.com/manicminer/hamilton. That one is used in production, for example, by HashiCorp in their Azure Terraform provider.

**Comment by samjustus** [comment]
sure-2551

**Comment by anupama2501** [comment]
Following test cases were validated on v2.6-head c0786cf

P0 checks:

**Fresh checks:**
- Install rancher on v2.6-head
- Enable Azure AD auth by selecting the standard endpoint using the existing app
- Verify no message appears in rancher UI for the end point upgrade as the endpoint should be the latest
- Verify the endpoints configured are the latest by running the command against the local cluster's kubeconfig kubectl describe authconfig azuread | grep graph
- Create a downstream cluster - c1
- As an admin, create 2 projects P1 and P2.
- Add users from Azure AD to the downstream cluster as user1:cluster Owner, user2:cluster member, user3: custom [Create Projects], user4: Project P1 - owner, user5: Project P2 member, user6: Read-only in project P1, user7: custom view workloads in project P2
- Log in as the new user1 and verify user can list the cluster 
- Run pre-upgrade checks by creating a user token for the cluster owner
- Verify all the pre-upgrade checks work 
- Login as user2 - create a few workloads, Verify user can list cluster members but cannot delete any member
- Login as user3 - Verify user3 cannot create projects, cannot create workloads, ingresses etc
- Login as user4 - Verify user can only list  the namespaces and workloads in P1, can create namespace, workloads, ingress in only P1
- Login as user5 - Verify user can only list  the namespaces and workloads in P2, can create namespace, workloads, ingress in only P2 and cannot manage members in P2
- Login as user6 - Verify user6 can only view project members, workloads  but cannot manage workloads
- Login as user7 - Verify user6 can only view  workloads but cannot manage workloads or list members

New endpoints upgraded to:
```
https://graph.microsoft.com/
https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/authorize
https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/token
```

**Upgrade checks:**

- Install rancher on v2.6.5
- Enable Azure AD auth by selecting the standard endpoint
- Verify no message appears in rancher UI for the end point upgrade as the endpoint should be the latest (for v2.6.5)
- Create 3 downstream clusters - c1, c2
- Add group1 as restricted admin 
- Add users from Azure AD to the downstream cluster as user1:cluster Owner, user2: cluster member in cluster1
- Create an API token as user1 from profile in the top right corner >> Account & API keys >> Create API Key and copy the bearer token
- Run pre-upgrade checks jenkins job by using the token created from the above step for the cluster owner
- Login as user2 - create a few workloads, Verify user can list cluster members but cannot delete/add users
- Add user3 as cluster custom Manage cluster members in cluster1
- Login as user3 - Verify user3 cannot create projects, cannot create workloads, ingresses etc and can only manage members from c1 
- Create 2 projects P1 and P2 as an admin in cluster c2.
- Add as an admin user4 as project owner in P1, user5 as project member in cluster c2 and project P2, user6: Read-only in project P1, user7: custom view workloads in P2
- Login as user4 - Verify user can only list  the namespaces and workloads in P1, can create namespace, workloads, ingress in only P1
- Login as user5 - Verify user can only list  the namespaces and workloads in P2, can create namespace, workloads, ingress in only P2 and cannot manage members in P2
- Login as user6 - Verify user6 can only view project members, workloads  but cannot manage workloads in project P1
- Login as user7 - Verify user7 can only view  workloads but cannot manage workloads or list members in project P2
- Upgrade rancher server to v2.6.6-rc or v2.6-head as an admin
- Verify a banner is displayed in the UI upon logging in as an admin that says API end points should be upgraded post rancher upgrade.
- From auth providers >> Azure AD auth >> click on the upgrade end point button to upgrade the end points. 
- Add the additional permissions to the app in azure portal:
- Group.Read.All
- User.Read.All
- Verify the upgrade is successful by running the command kubectl describe authconfig azuread | grep graph
- Run post upgrade jenkins job checks on the clusters c1 with the API token created from step 7.
- Repeat steps 9 through 17.
- Create a downstream cluster c3
- Add users u11:cluster owner, u12:cluster member, u13: project owner, u14: project member in the cluster
- Login as respective users and verify the login is successful
- Run pre upgrade checks on the cluster c13
- From c1 remove the users u1, u2 and add u3:CO and u4:CM
- Verify u1, u2 cannot access cluster c1 and u3, u4 can access the cluster


**Other checks:**

1. Upgrade from 2.6.5 >> 2.6.6 - As a restricted admin - PASS
2. Disable auth - PASS
3. Disable and re enable auth post rancher upgrade from 2.6.5 to 2.6.6 - PASS
4. Rollback via docker - https://github.com/rancher/rancher/issues/38025
5. Roll back via Backup/restore on same cluster - PASS
6. Roll back via Backup/restore on a migrated cluster - PASS
7. Backup/restore post upgrade - PASS
8. Refresh Users - PASS
9. Refresh Groups - PASS
10. Delete users - PASS

**Comment by rootwuj** [comment]
Validated on rancher v2.6-head (`df1b202`)

End point set to China:

**Fresh checks:**

1. Install rancher on v2.6-head
2. Enable Azure AD auth by selecting the **china** endpoint using the existing app
3. Verify no message appears in rancher UI for the end point upgrade as the endpoint should be the latest
4. Verify the endpoints configured are the latest by running the command against the local cluster's kubeconfig kubectl describe authconfig azuread | grep graph
5. Create a downstream cluster - c1
6. As an admin, create 2 projects P1 and P2.
7. Add users from Azure AD to the downstream cluster as user1:cluster Owner, user2:cluster member, user3: custom [Manage cluster members], user4: Project P1 - owner, user5: Project P2 member, user6: Read-only in project P1, user7: custom view workloads in project P2
8. Log in as the new user1 and verify user can list the cluster 
9. Run pre-upgrade checks by creating a user token for the cluster owner
10. Verify all the pre-upgrade checks work
11. Login as user2 - create a few workloads, Verify user can list cluster members but cannot delete any member
12. Login as user3 - Verify user3 cannot create projects, cannot create workloads, ingresses etc
13. Login as user4 - Verify user can only list the namespaces and workloads in P1, can create namespace, workloads, ingress in only P1
14. Login as user5 - Verify user can only list the namespaces and workloads in P2, can create namespace, workloads, ingress in only P2 and cannot manage members in P2
15. Login as user6 - Verify user6 can only view project members, workloads but cannot manage workloads
16. Login as user7 - Verify user7 can only view workloads but cannot manage workloads or list members

China new endpoint upgraded to:
```
Endpoint:	https://login.partner.microsoftonline.cn/
Graph Endpoint:	https://microsoftgraph.chinacloudapi.cn
Token Endpoint:	https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/token
Auth Endpoint:	https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/authorize
```

**Upgrade checks:**


1. Install rancher on v2.6.5
2. Enable Azure AD auth by selecting the china endpoint
3. Verify no message appears in rancher UI for the end point upgrade as the endpoint should be the latest (for v2.6.5)
4. Create 2 downstream clusters - c1, c2
5. Add group1 as restricted admin 
6. Add users from Azure AD to the downstream cluster as user1:cluster Owner, user2: cluster member in cluster1
7. Create an API token as user1 from profile in the top right corner >> Account & API keys >> Create API Key and copy the bearer token
8. Run pre-upgrade checks by using the token created from the above step for the cluster owner
9. Login as user2 - create a few workloads, Verify user can list cluster members but cannot delete/add users
10. Add user3 as cluster custom Manage cluster members in cluster1
11. Login as user3 - Verify user3 cannot create projects, cannot create workloads, ingresses etc and can only manage members from c1 
12. Create 2 projects P1 and P2 as an admin in cluster c2.
13. Add as an admin user4 as project owner in P1, user5 as project member in cluster c2 and project P2, user6: Read-only in project P1, user7: custom view workloads in P2
14. Login as user4 - Verify user can only list the namespaces and workloads in P1, can create namespace, workloads, ingress in only P1
15. Login as user5 - Verify user can only list the namespaces and workloads in P2, can create namespace, workloads, ingress in onlyP2 and cannot manage members in P2
16. Login as user6 - Verify user6 can only view project members, workloads but cannot manage workloads in project P1
17. Login as user7 - Verify user7 can only view workloads but cannot manage workloads or list members in project P2
18. Upgrade rancher server to v2.6-head as an admin
19. Verify a banner is displayed in the UI upon logging in as an admin that says API end points should be upgraded post rancher upgrade.
20. From auth providers >> Azure AD auth >> click on the upgrade end point button to upgrade the end points. 
21. Add the additional permissions to the app in azure portal:
	- Group.Read.All
	- User.Read.All
22. Verify the upgrade is successful by running the command kubectl describe authconfig azuread | grep graph
23. Run post upgrade jenkins job checks on the clusters c1 with theAPI token created from step 7.
24. Repeat steps 9 through 17.
25. Create a downstream cluster c3
26. Add users u11:cluster owner, u12:cluster member, u13: project owner, u14: project member in the cluster
27. Login as respective users and verify the login is successful
28. Run pre upgrade checks on the cluster c3
29. From c1 remove the users u1, u2 and add u3:CO and u4:CM
30. Verify u1, u2 cannot access cluster c1 and u3, u4 can access the cluster

**Comment by maxsokolovsky** [comment]
## Release note

*Please put this one at the top of release notes, since this mentions a major change.*

Microsoft have deprecated the Azure AD Graph API that Rancher had been using for authentication via Azure AD. 
A configuration update is necessary to make sure users can still use Rancher with Azure AD.
[See the docs for details.](http://localhost:9001/rancher/v2.6/en/admin-settings/authentication/azure-ad/#migrating-from-azure-ad-graph-api-to-microsoft-graph-api)
Issue https://github.com/rancher/rancher/issues/29306.

**Comment by anupama2501** [comment]
re opening fir a few more validations
