### ISSUE TITLE
[rancher-dns] Rancher DNS returns incorrect status code for recursive queries

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#2930]
### Steps to reproduce
1. Get a shell to a running container that is using the managed network (image needs to have `dig` utility installed)
2. `$ dig nonexistantdomain.xyz @8.8.8.8` -> Status: NXDOMAIN
3. `$ dig nonexistantdomain.xyz @169.254.169.250`

### Expected result
Rancher DNS replies with Status: NXDOMAIN

### Actual result
Rancher DNS replies with Status: NOERROR

**Comment by janeczku** [comment]
https://github.com/rancher/rancher-dns/blob/master/main.go#L178
```GO
	msg, err := ResolveTryAll(fqdn, question.Qtype, answers.Recursers(clientIp))
	if err == nil {
		msg.SetReply(req)
		w.WriteMsg(msg)
```
`SetReply()` shouldn't be used on a message that is already a reply. It also set's the status code to NOERROR.

```DOC
func (dns *Msg) SetReply(request *Msg) *Msg
SetReply creates a reply message from a request message.
```

**Comment by sangeethah** [comment]
Tested with latest build from master

dig nonexistantdomain.xyz @169.254.169.250 now returns NXDOMAIN.

<img width="573" alt="screen shot 2015-12-22 at 11 43 08 am" src="https://cloud.githubusercontent.com/assets/4266958/11964340/d53c815e-a8a1-11e5-95fc-e6d996e0c116.png">
