### ISSUE TITLE
CIS Scan 1.1.12 (Ensure that the etcd data directory ownership is set to etcd:etcd) not working

### ISSUE THREAD

**Issue by ajchiarello** [rancher/rancher#29311]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
In an RKE nodepool cluster, make sure that the etcd data directory (/var/lib/rancher/etcd, as seen in the ps -ef | grep etcd output) is owned by etcd:etcd, then run a CIS scan (hardened).

**Result:**
The CIS scan incorrectly reports that the data directory is not owned by etcd.

**Other details that may be helpful:**
Changing the permissions on /var/lib/etcd allows the system to pass, despite this not being the value assigned to the data-dir flag on etcd.

**Environment information**
- Rancher version 2.4.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 4CPU, 32G RAM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by ajchiarello** [comment]
Is this issue addressed in Rancher 2.5.x?

**Comment by sowmyav27** [comment]
- Deploy a 1 node rke cluster  on `master-6d4d6b0f5`
- As per Hardening guide: https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.3.x/rancher-v2.3.5/benchmark-2.3.5/#1-1-12-ensure-that-the-etcd-data-directory-ownership-is-set-to-etcd-etcd-scored
```
 On the etcd server node, get the etcd data directory, passed as an argument --data-dir, from the below command:

ps -ef | grep etcd
Run the below command (based on the etcd data directory found above). For example,

chown etcd:etcd /var/lib/etcd
```
- Login to the node, do `ps -ef | grep etcd`
```
--data-dir=/var/lib/rancher/etcd/
```
- But there is no folder etcd in 
```
root@sowmya-test-m-1:~# cd /var/lib/rancher/etcd
bash: cd: /var/lib/rancher/etcd: No such file or directory
```

**Comment by chuegel** [comment]
That's because etcd is running as a docker container:
```
docker exec -it etcd   ls -la /var/lib/rancher/
total 0
drwxr-xr-x. 3 root root 18 Feb 16 13:20 .
drwxr-xr-x. 1 root root 21 Feb 16 13:20 ..
drwx------. 3 root root 20 Feb 16 13:20 etcd
```
