### ISSUE TITLE
When Global default registry to `reg1` and cluster level to `reg2`,  helm-operation pod and fleet agent get deployed using images from reg1

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29317]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Set Global default registry to `reg1` and cluster level to `reg2`
- While deploy CIS v2 app on the override the default registry to `reg2`, helm-operation pod gets deployed using `reg1` and all the cis related pods get deployed using `reg2`.
- registry settings from v3/cluster is used for all the system containers in this cluster but not for fleet agent that gets auto deployed 

**Other details that may be helpful:**
related to - https://github.com/rancher/rancher/issues/28833 and https://github.com/rancher/dashboard/issues/1554

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `cb9e8a105c1f`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):custom RKE - 1 node all roles
- Kubernetes version (use `kubectl version`):

```
1.19
```

**Comment by StrongMonkey** [comment]
@sowmyav27 I am not able to reproduce this, can you retest and let me know if you reproduce it? In my setup all fleet-agent are able to change reg from the global setting.

**Comment by StrongMonkey** [comment]
@sowmyav27 Also what's the cluster-level registry you are setting?

**Comment by StrongMonkey** [comment]
Also There is likely that cluster-level registry will not applied to fleet-agent. Fleet-agent is installed by fleet-controller so it only respect the global registry when installing fleet-controller.

**Comment by sowmyav27** [comment]
@StrongMonkey 
- Global level registry: `reg1` and Cluster level registry `reg2`.
- Deploy CIS v2 and override the system default registry in CICS v2's charts, and use `reg2` registry, We see the helm operation pods, for deploying the CIS v2 charts use images from `reg1` and NOT `reg2`. Is this expected? 
- Also yes, fleet agent uses images from `reg1` and NOT `reg2`. Is this expected?

**Comment by deniseschannon** [comment]
@sowmyav27 @StrongMonkey @cbron 

We need clearer defintion of what the cluster registry is supposed to do as it's primarily for deploying the RKE components and was never expected to be used for ALL cluster components.

So yes, I believe that we are using reg1 as expected for the components that are not IN the dedicated helm chart.

**Comment by StrongMonkey** [comment]
@sowmyav27 Yeah due to how fleet works It will not use cluster-registry. Fleet will only use global regsitry and deploy fleet-agent to downstream cluster.

**Comment by sowmyav27** [comment]
Closing this issue based on https://github.com/rancher/rancher/issues/29317#issuecomment-710313226 and https://github.com/rancher/rancher/issues/29317#issuecomment-710357883
