### ISSUE TITLE
Disable local cluster dashboard access to restricted admin

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#29325]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
1. Deploy rancher with restrictedAdmin=true helm chart option
2. Log in as admin
3. Navigate to local cluster

**Result:**
Preferred if the dashboard access for the local cluster is completely removed for restricted admins. When a restricted admin logs in, they should not see the local cluster, similar to how deploying with helm chart option addLocal=off.

Currently restricted admins can see the local cluster and it appears they can do things like enable monitoring and this doesn't work. This is not a good user experience.

gzrancher/rancher#12606

**Comment by deniseschannon** [comment]
@dramich Is there a way to identify if someone logged in is a restricted admin? or anything identifying on the user that could be used by the UI to "hide" the local cluster?

**Comment by dramich** [comment]
UI can check a users perms but that doesn't guarantee they shouldn't see it. restricted-admin has full access to all rancher CRDs so even if you hide it in the UI they can still touch it through kubectl.

**Comment by deniseschannon** [comment]
@dnoland1 Are you only looking to hide it from a visual perspective?

**Comment by dnoland1** [comment]
@deniseschannon Preferably both visual and API/CLI, but I'm okay with just visually hiding the local cluster on the UI as long as a restricted admin cannot stop the rancher workload or anything else that could disrupt service.

**Comment by maggieliu** [comment]
Based on the design discussion, need to add a setting that can be passed in on installation to hide local cluster in UI from all users.

**Comment by maggieliu** [comment]
@westlywright we need to hide the local cluster from the list when the new setting HideLocalCluster is true.

**Comment by dnoland1** [comment]
Tested on v2.5-0465f049780def811e00ab32067f95734f6a88f5-head. After installation, logged in as admin, navigated to https://server-url/v3/settings/hide-local-cluster and changed the `hide-local-cluster` setting from false to true. Reloaded browser. Was no longer able to see the local cluster in the UI.

Regarding the comment:
> Based on the design discussion, need to add a setting that can be passed in on installation to hide local cluster in UI from all users.

How do I enable this during installation? Is there a Helm Chart value I can pass?

**Comment by maggieliu** [comment]
@dnoland1 Here are the instructions from Rajashree:

During helm install of rancher we can set CATTLE_HIDE_LOCAL_CLUSTER to true through[ values.yaml ](https://github.com/rancher/rancher/blob/master/chart/values.yaml#L35)
`# extraEnv:`

and even after installing rancher it can be set through API by going to v3/settings

but for the hosted rancher use case, the managed rancher instances are installed as apps and we want local cluster hidden during install, so while installing that rancher app that setting can be set to true in values.yaml

**Comment by dnoland1** [comment]
Tested 2.5.2-rc4 using extraEnv. This is what goes out in the API call (from api audit logs):
```"requestBody": {
  "links": null,
  "actions": null,
  "answers": {
    "addLocal": "auto",
    "antiAffinity": "required",
    "auditLog.destination": "hostPath",
    "auditLog.level": "2",
    "auditLog.maxAge": "7",
    "auditLog.maxBackups": "7",
    "auditLog.maxSize": "100",
    "extraEnv[0].name": "CATTLE_HIDE_LOCAL_CLUSTER",
    "extraEnv[0].value": "true",
    "hostname": "myhost",
    "replicas": "2",
    "restrictedAdmin": "true",
    "tls": "external"
  },
```
However, Rancher is stripping the double quotes and when the app deploys, getting the error:
`Failed to install app rancher. Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true}],"ima|..., bigger context ...|ue"},{"name":"CATTLE_HIDE_LOCAL_CLUSTER","value":true}],"image":"rancher/rancher:v2.5.2-rc4","imageP|...`

Appear to be hitting this issue - https://github.com/rancher/rancher/issues/26088

**Comment by sowmyav27** [comment]
Closing this issue as [this](https://github.com/rancher/rancher/issues/29325#issuecomment-719864450) issue is tracked in this https://github.com/rancher/rancher/issues/26088
