### ISSUE TITLE
Links for Multi-Cluster Apps text section need to be fixed

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#29321]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1.  Go to Multi-Cluster Apps page

**Result:**  
- [x] The deprecated link, opens support terms in same tab and closes rancher.  Have it open in new tab.

- [x] Reword message cause Cluster Explorer is not same as the Continuous Delivery product.  Take out the "in Cluster Explorer."  and link the Continuous Delivery text.  Maybe even say "Rancher's new Continuous Delivery tool."?

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head ce572b5
v3/settings/uiofflinepreferred set to `false`

* Banner is present
* Link to support opens in a new tab
* Text is updated to `Multi-cluster apps are deprecated in Rancher v2.5+. Deploying apps to multiple clusters is available using Rancher Continuous Delivery.`
