### ISSUE TITLE
v1 monitoring chart does not deploy on local k3 cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#29328]
Rancher server version - `5a60e25bd7`

Setup - HA setup with K3 (v1.19.2+k3s1) local cluster - 2 control planes and 1 worker node 

Steps to reproduce the problem:
Try to install v1 monitoring.

After enabling monitoring, nothing happens. No workloads relating to monitoring app gets deployed.
It stays in "Monitoring API is not ready"  state.

Note - Installing v2 monitoring succeeds in local k3s cluster.

**Comment by cbron** [comment]
Bumping back to 2.5.1 as its any k3s cluster, this would include rke2.

**Comment by wirwolf** [comment]
Actual issue. This feature will remain in 2.5?(display statistic about load, memory and network in deployment info)

**Comment by wirwolf** [comment]
@maggieliu

**Comment by aiyengar2** [comment]
@wirwolf that effort is being tracked in https://github.com/rancher/dashboard/issues/812

**Comment by deniseschannon** [comment]
@jiaqiluo Can we check if this is still an issue or if it's working now? cc: @sowmyav27

**Comment by jiaqiluo** [comment]
Monitoring v1 (`0.2.0`) is working on the local k3s cluster (`v1.19.7+k3s1`) now.

The k3s cluster contains 
- 2 server nodes 
- 3 worker nodes
- MySQL v5.7.26 on AWS as the database 

Steps:
- install rancher:`master-head` 59ebdc2 into the k3s cluster by using Rancher:v2.5.5 chart and passing `RANCHER_IMAGE_TAG=master-head`
- enable both Cluster and Project Monitoring v1 `0.2.0` in the local cluster

Results:
- the monitoring v1 is enabled successfully
- the monitoring apps are installed and active in the local cluster
- the cluster pages shows metrics as expected 
- P0 checks for both Cluster and Project Monitorin are passed 

![image](https://user-images.githubusercontent.com/6218999/106518374-0617e280-6497-11eb-8760-7cea6e770338.png)
