### ISSUE TITLE
Amazon ec2 host stuck at creating

### ISSUE THREAD

**Issue by pavankumarkatakam** [rancher/rancher#2933]
While adding hosts with type amazon ec2 it stuck at that point with the message "Setting up machine…
In Progress", But when go to my ec2 account there is security group created with "rancher-machine" but no ec2 instance started. 

Here is docker logs

 "level=error msg="Unable to create EventRouter" Err="Get https://www.rancherserver.tk/v1: x509: certificate signed by unknown authority"

please tell me whats going wrong with this? im running rancher server with docker in digital ocean.

**Comment by pavankumarkatakam** [comment]
Forget to mention one thing, im using ssl from https://letsencrypt.org/ organization.

**Comment by pavankumarkatakam** [comment]
Its solved by linking nginx with full chain certificate rather than only certificate.

**Comment by ddffx** [comment]
Just putting it out here for others that this works on *Digital Ocean Host* creation as well. So it is **letsencrypt** specific.
On nginx config use certificate **fullchain.pem** and key as **privkey.pem**
```
ssl_certificate [cert_path]/fullchain.pem;
ssl_certificate_key [cert_path]/privkey.pem;
```
