### ISSUE TITLE
Update min version of charts in system-charts

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29337]
Rancher-monitoring 0.1.3
~k3s Upgrader 0.2.1~ ( chart removed)
Lower the rancher-min-version to be available in 2.4.9

**Comment by deniseschannon** [comment]
@jiaqiluo This issue is to test the latest monitoring chart (0.1.3) in 2.4.9.

**Comment by jiaqiluo** [comment]
The following validations are done:

1. the monitoring v0.1.3 chart does NOT show in v2.4.8
2. in Rancher:v2.4-3786-head, monitoring v0.1.3 is installed in the following k8s clusters successfully 
- v1.18.9-rancher1-1
- 1.17.12-rancher1-1
- 1.16.15-rancher1-2
- 1.15.12-rancher2-6

The following validations will be done when v2.4.9 RC is available:
- check that only 0.1.3 shows in v2.4.9
- upgrade monitoring v0.1.2 to v0.1.3

**Comment by kinarashah** [comment]
Available to test with `v2.4.9-rc1`

**Comment by jiaqiluo** [comment]
There are 3 versions showing in rancher: `v2.4.9-rc1` ( system-library branch `dev-v2.4`)
We should show only `0.1.4` in v2.4.9 


![image](https://user-images.githubusercontent.com/6218999/96495970-79a22680-11fd-11eb-95d7-4b8590f40ff8.png)

**Comment by jiaqiluo** [comment]
the `0.1.4` chart is validated in the upgrading scenario from `0.1.2` & rancher: `v2.4.8` to `v2.4.9-rc1`

- run rancher `v2.4.8` single install 
- provision clusters for all supported k8s versions 
- enable the cluster monitoring `0.1.2` in all clusters 
- upgrade rancher to `v2.4.9-rc1`
- upgrade monitoring to `0.1.4`

**Comment by jiaqiluo** [comment]
The bug fix is validated in v2.4.9-rc1  with the latest system-chart update 

Now only the 0.1.4 shows in the dropdown list.

<img width="899" alt="Screen Shot 2020-10-20 at 5 56 58 PM" src="https://user-images.githubusercontent.com/6218999/96660235-e997d600-12fd-11eb-8496-ad004ea457b5.png">
