### ISSUE TITLE
Can't refresh kdm metadata in v2.5-head

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29339]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- Install HA k8s v2.5-head

**Result:**

`failed to refresh failed to create or update driverMetadata: driverMetadata: unable to find default k8s version in current k8s v1.19.x [v1.16.15-rancher1-2 v1.17.12-rancher1-1 v1.18.9-rancher1-1]`

![Screen Shot 2020-10-02 at 12 25 42 PM](https://user-images.githubusercontent.com/27659/94961911-70e5ec80-04aa-11eb-8ff8-43e104a03180.png)
![Screen Shot 2020-10-02 at 12 25 51 PM](https://user-images.githubusercontent.com/27659/94961920-74797380-04aa-11eb-80c3-755718d74a1f.png)

**Other details that may be helpful:**
`rke-metadata-config`
```json
{
  "refresh-interval-minutes": "1440",
  "url": "https://releases.rancher.com/kontainer-driver-metadata/dev-v2.5/data.json"
}
```

**Environment information**
- Rancher version: `v2.5-ce572b5f1557878b2b201272baf6449cf5eec12c-head`
- Installation option: HA

**Comment by maggieliu** [comment]
master-head should work. Will fix in 2.5.1 to ensure 2.5-head works.

**Comment by sangeethah** [comment]
https://github.com/rancher/rancher/pull/29343

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `a034814 `**

- No error seen while refreshing KDM
- K8s versions are seen while creating a cluster in the dropdown.
- Closing the issue.
