### ISSUE TITLE
[2.4 Backport] prometheus-auth is using an old unmaintained version of Alpine Linux

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29342]
related to: https://github.com/rancher/rancher/issues/29290

 Rebuild https://github.com/rancher/prometheus-auth

**Comment by aiyengar2** [comment]
Closing this issue out in favor of https://github.com/rancher/rancher/issues/29290 since this change only needs to be merged into 2.4 as Monitoring V2 does not use this image.
