### ISSUE TITLE
Update version of Git in Rancher for Rancher catalog cloning

### ISSUE THREAD

**Issue by eksavoy** [rancher/rancher#2934]
Hi,

I can't access to the catalog and when i see in logs, i have this erreur loop : 

``` log
Cloning into './DATA'...
fatal: unable to access 'https://github.com/rancher/rancher-catalog.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.
time="2015-12-07T09:42:10Z" level=fatal msg="Failed to clone the catalog from githubexit status 128"
time="2015-12-07T09:42:11Z" level=info msg="Starting Rancher Catalog service"
time="2015-12-07T09:42:11Z" level=info msg="Cloning the catalog from github url https://github.com/rancher/rancher-catalog.git"
```

It seems like a problem with git and https.

**Comment by deniseschannon** [comment]
Can you provide your Rancher server version? Also, is this a fresh install or upgraded setup?

**Comment by elerion** [comment]
I use the lastest version so i think it's v0.49.0, and today I use a fresh install and I have the same problem 

```logs
time="2015-12-08T10:07:46Z" level=info msg="Starting Rancher Catalog service"
time="2015-12-08T10:07:46Z" level=info msg="Using catalog library=https://github.com/rancher/rancher-catalog.git"
time="2015-12-08T10:07:46Z" level=info msg="Cloning the catalog from git url https://github.com/rancher/rancher-catalog.git"
Cloning into './DATA/library'...
fatal: unable to access 'https://github.com/rancher/rancher-catalog.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.
time="2015-12-08T10:09:53Z" level=fatal msg="Failed to clone the catalog from git exit status 128"
```

**Comment by prachidamle** [comment]
@elerion did you look at this http://askubuntu.com/questions/186847/error-gnutls-handshake-failed-when-connecting-to-https-servers

Seems like some git issue?

**Comment by elerion** [comment]
Yes I saw this issue but I can't doing this in my containers each time I upgrade version of rancher.
I seen that it's seems fixed in this version : https://github.com/rancher/rancher/releases/tag/v0.49.1
But I have the same probleme

**Comment by deniseschannon** [comment]
This is neither a Rancher or Catalog issue. This is actually an issue with Git. 

How have you set up your Rancher instance? Is it a plain install?

**Comment by deniseschannon** [comment]
@elerion Since this is neither a Rancher or Catalog issue, I'm going to close it.

**Comment by aemneina** [comment]
reopening this as it looks like an issue with the version of git that the rancher server ships with.

**Comment by aemneina** [comment]
might even be solved with the rancher/server ubuntu version being bumped.

**Comment by janeczku** [comment]
The GNUTLS shipped in the server-base image does not work with some cipher configurations that are used out there.
E.g. given a git server with the following TLS configuration Rancher is fails to sync the catalog:

```

**Comment by nheinemans** [comment]
We are experiencing the same issues on our Rancher 1.6 environment. We moved our git repo to SSL recently, and catalog cloning from rancher is throwing errors. Please let us know when this will be fixed.

**Comment by nheinemans** [comment]
@deniseschannon Can you please give a timeframe for the solution for this issue?

**Comment by xirixiz** [comment]
GitLab is formatting their API URLs differently these days and not allowing basic auth at the beginning of the URL anymore. Instead, you have to insert a token at the end. The following URL works in a browser:

`https://gitlab.com/api/v4/projects/<projectID>/repository/files/index%2Eyml/raw?ref=master&private_token=0000000000`

So it seems like this would work fine if either GitLab didn't change formatting, or if Rancher could support sending a header so it's possible to add a private_token variable.

For now the workaround is to do the following.

```
- Generate SSH keys
- Add the public key to the GitLab repo to a user with sufficient permissions to the GitLab repository.
- Add the private key to the Docker container.
    -  Add the generated private key to /root/.ssh/id_rsa  (different manners how to get the job done, volume, copy, etc). 
     - sudo docker exec <container id/name> chmod 400 /root/.ssh/id_rsa
     - sudo docker exec <container id/name> sh -c 'ssh-keyscan <gitlab url> >> /root/.ssh/known_hosts'
    - The configure the catalog url to use ssh instead of http(s): git@<gitlab url>:<project>/catalog.git
```

That's it. Not a very pretty solution, but at least it's a workaround.
