### ISSUE TITLE
Testing restrictedAdmin

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29340]
Need more thorough testing on the new restrictedAdmin role. 
* Make sure it has restricted access to local cluster 
* Make sure it has all the same permission as global admin on downstream clusters.

**Comment by jiaqiluo** [comment]
reopen this issue. New issues are tracked internally.

**Comment by deniseschannon** [comment]
@jiaqiluo Let's close in favor of the other opened issues. If tehre are more issues, please open them as a separate issue.
