### ISSUE TITLE
"display-name" is not mapped to the cluster name when EKS v2 cluster name is corrected

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29353]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a hosted EKS cluster with name - `cluster-1`
- Create another hosted EKS cluster with the same name. Give in all the details. In the last step, the cluster will fail with error
<img width="873" alt="Screen Shot 2020-10-02 at 7 55 21 PM" src="https://user-images.githubusercontent.com/26032343/94983518-4753b200-04f8-11eb-96ca-c9ba1f4f235a.png">

- Change clustername to a new one in the UI `cluster-2`
- And click "Save" / "Create" .
- API request sent has

```
displayName: "sowmya-new-eks"
name: "sowmya-new-eks2"
```

**Expected Result:**
- displayName: "sowmya-new-eks" should be exposed separately on the UI. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.0-rc5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted EKS
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by sowmyav27** [comment]
**On master-head - commit id: `e90c4018156`**

- Create a hosted EKS cluster with name - `sow-new-master`
- Create another hosted EKS cluster with the same name. Give in all the details. In the last step, the cluster will fail with error
<img width="974" alt="Screen Shot 2020-10-17 at 3 21 24 AM" src="https://user-images.githubusercontent.com/26032343/96312057-743fb300-1028-11eb-9b1a-2973dbd0bc50.png">

- Change clustername to a new one in the UI `sow-new-master-2`
- API Request sent has

```
name: "sow-new-master-2"
displayName: "sow-new-master-2"
```
- New cluster is deployed successfully. No error seen

**On 2.5-head commit id: `d6946c5`**
- Create a hosted EKS cluster with name - `sow-new`
- Create another hosted EKS cluster with the same name. Give in all the details. In the last step, the cluster will fail with error
<img width="809" alt="Screen Shot 2020-10-17 at 3 24 43 AM" src="https://user-images.githubusercontent.com/26032343/96312059-786bd080-1028-11eb-817a-a329b04a8dc8.png">

- Change clustername to a new one in the UI `sow-new-2`
- API Request sent has

```
name: "sow-new-2"
displayName: "sow-new"
```
- Same error is seen again while deploying the cluster.
- Reopening the issue.

**Comment by westlywright** [comment]
I am kicking this back to test, I suspect the ticket got moved to test before the build was done. I was able to confirm on master this works as expected.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `5682e2c1`**

- Create a hosted EKS cluster with name - sow-new
- Create another hosted EKS cluster with the same name. Give in all the details. In the last step, the cluster will fail with error - Validation failed. Cluster already exists
- Change clustername to a new one in the UI sow-new-2
- API Request sent has

```
name: "sow-new-2"
displayName: "sow-new-2"
```
- New cluster is deployed successfully. No error seen
