### ISSUE TITLE
[UI] Add --log-driver and --log-opt in create Service/Container UI

### ISSUE THREAD

**Issue by elerion** [rancher/rancher#2935]
Hi,

I have seen that docker compose and rancher compose supoort log driver and log opts, It will be great to support this feature in rancher ui.

Kings regards

**Comment by atrauzzi** [comment]
:+1:

**Comment by atrauzzi** [comment]
Whoa, 1.1?  I think you guys should reconsider.

This is actually a big issue for me right now.  My containers are blowing up my nodes because of the amount of data they're outputting.  All that data goes to the hard drive and seems to also impact the amount of memory docker uses.

**Comment by deniseschannon** [comment]
@atrauzzi This is supported in the API and rancher-compose, but it just hasn't been made into the UI. So if you really need to use it, consider using rancher-compose. To make it easier, you can just look at the docker-compose.yml of the services that you want to add the log driver/log opt by clicking on "View Config" for the stack level and then export that docker-compose.yml and add in the log_driver and log_opt to the services that you want. 

```
foo:
  image: nginx
  log_driver: json-file
  log_opt:
    labels: foo
```

**Comment by atrauzzi** [comment]
I'm not really set up for rancher-compose at the moment.  I definitely have every intention to be, but I'm still figuring out my workflows for everything.

Not having this in the UI will be a major pain point for me.

**Comment by deniseschannon** [comment]
If you don't want to set up rancher-compose, you can always use the "add stack" option and still put in the exported docker-compose.yml and rancher-compose.yml with the changes to start new services with the log driver/log opt in the docker-compose.yml.

**Comment by atrauzzi** [comment]
I'll take a look at that in the interim.  I know you guys are probably tight for resources, although you may want to be absolutely certain about the priority given to this.  It's subtle, but I bet lots of people are going to run afoul of it. :)

**Comment by vincent99** [comment]
There really hasn't aftually been that much interest, as you can see from the lack of endless stream of +1s here... but fine, if it's that important to you :smile:

https://github.com/vincent99/ui/commit/744415f2c31b6074591843c68124a14204d7f135

**Comment by atrauzzi** [comment]
Nice!  That's awesome, and to be honest .. I've dealt with many issues in the past that keep a low profile, but affect a lot of people.  I definitely get that feeling from this one.

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/13998328/db6d877c-f0f3-11e5-8e04-f76ea17f39ce.png)

**Comment by tfiduccia** [comment]
version - v1.0.0-rc4
Not working - I added driver = syslog and the service won't start.  The logs say:
Invalid Date Invalid Daterunning logs job: unknown log opt 'driver' for json-file log driver

**Comment by tfiduccia** [comment]
Version - v1.0.0-rc4
Verified fixed
