### ISSUE TITLE
"Unauthorized 401 must authenticate" error seen on login page sometimes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29357]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Bring up single node install of rancher.
- And try to login immediately.
- Sometimes user sees this error. Clicking on Continue does not help in logging in

<img width="844" alt="Screen Shot 2020-10-01 at 8 53 48 AM" src="https://user-images.githubusercontent.com/26032343/94984882-d2877480-0505-11eb-9765-2935193f180d.png">

**Expected Result:**
"Unauthorized 401 must authenticate"

**Other details that may be helpful:**
To get out of this enter `https://<rancher-server>/login` in the browser and hit enter. This issue will not be seen
Try to login as soon as rancher server comes up.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.0-rc5
- Installation option (single install/HA): single

**Comment by vincent99** [comment]
I tried several times and wasn't able to replicate this.. it's probably some sort of server race, keep the network tab dev tools tab open and check server logs if you can get it to happen again.

**Comment by nikhilgorantla** [comment]
This behaviour is seen when used https://<endpoint> 
Works fine when used http://<envpoint>

I can replicate this behaviour

**Comment by tfiduccia** [comment]
I tried production twice using https:// and I got it once and the other time it worked just fine?  So it's still in v2.5.0.  If I see again I'll check server logs.  The console logs had two errors:
Failed to load resource: the server responded with a status of 401 (Unauthorized)
https://23.xx.xxx.xxx/v3/users?action=changepassword 401 (Unauthorized)

**Comment by matrixes** [comment]
I have just prepared a new desktop computer with Ubuntu 18.04 to test Rancher out.

Just now did step 2 and 3 from this guide https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/ and when I was asked to set a password, clicking the Continue-button, the following request was sent:

`https://192.168.1.110/v3/users?action=changepassword`

With the following response:

`{"type":"error","status":"401","message":"Unauthorized 401: must authenticate"}`

I have a metric ton of logs saved from `docker logs -f` if that's of any use to you.

**Comment by tfiduccia** [comment]
@matrixes - we are aware of the issue.  The current work-around is to refresh the browser page while on that login screen.  Then it will let you put in the password and continue.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `7eb1792` and master-head commit id: `b7e8c0d3d1`**

This issue is not seen. Closing it.

Will log a new one if seen again.
