### ISSUE TITLE
Elevated CPU, load, network utilization after 2.4.8 to 2.5.0-rc7 upgrade

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#29364]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Upgrade Rancher from v2.4.8 to v2.5.0-rc7

**Result:**
Upgrade performed at around 8:35AM PDT on October 4, 2020.
CPU before upgrade 15-20%. After upgrade 45-55%:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/468462/95022365-b1b93f00-062b-11eb-9055-5e66721f1e23.png">

Load average before upgrade 0.5-1. After upgrade 1.5-3:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/468462/95022372-c269b500-062b-11eb-85cf-b944cfc4f66e.png">

Network I/O before upgrade 0-2mbps. After upgrade 2-5mbps:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/468462/95022411-0361c980-062c-11eb-96d3-912431368393.png">

Database CPU (RDS Aurora) before upgrade 10-20%. After upgrade 80-90%!!!:
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/468462/95022451-41f78400-062c-11eb-9c91-9be3aad888b8.png">

**Other details that may be helpful:**
here are the logs from both rancher pods: 
[rancher-logs-2020-10-04.zip](https://github.com/rancher/rancher/files/5323805/rancher-logs-2020-10-04.zip)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.4.8 -> 2.5.0-rc7
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
aws ec2 m5a.large (2vcpu, 8gb ram)
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8+k3s1", GitCommit:"6b595318666804506c19cfc3d3d228423d38fab1", GitTreeState:"clean", BuildDate:"2020-08-14T20:42:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
containerd 1.3.3

gzrancher/rancher#12807

**Comment by maggieliu** [comment]
Showing this error multiple times a second in the logs:
`2020/10/04 17:17:38 [ERROR] error getting app cluster-monitoring apps.project.cattle.io "p-qkmbm/cluster-monitoring" not found`

**Comment by dnoland1** [comment]
Recent copy of logs: 
[rancher-logs-2020-10-04-2.zip](https://github.com/rancher/rancher/files/5324351/rancher-logs-2020-10-04-2.zip)

**Comment by sangeethah** [comment]
The local 2 node Rancher cluster in this case is being managed by another Rancher cluster.

**Comment by maggieliu** [comment]
related to: https://github.com/rancher/rancher/issues/28983

**Comment by dramich** [comment]
This is being caused by the local cluster being enabled in the downstream rancher setup. This is easy to reproduce using a 2.5 rancher master and downstream rancher clusters v2.4.8 and leaving the local cluster enabled and also in 2.5 which has it always turned on

**Comment by bmdepesa** [comment]
We were able to reproduce this with with 2.4.8/2.5.0 and 2.5.0/2.5.0 on the host and tenant clusters. 

* Create a Rancher HA installation
* Create a k3s cluster
* Import the k3s cluster into Rancher
* Install Rancher onto the k3s clusters (via helm or catalog - reproduces both ways)
* Enable cluster monitoring on the imported cluster from the host cluster
* View Rancher logs of the tenant cluster and see the error repeatedly:
```
2020/10/07 16:42:31 [ERROR] error getting app cluster-monitoring apps.project.cattle.io "p-lch7c/cluster-monitoring" not found
2020/10/07 16:42:31 [ERROR] error getting app cluster-monitoring apps.project.cattle.io "p-lch7c/cluster-monitoring" not found
2020/10/07 16:42:31 [INFO] Updating workload [cattle-prometheus/exporter-node-cluster-monitoring] with public endpoints [[{"nodeName":"local:machine-7dmh4","addresses":["13.58.69.223"],"port":9796,"protocol":"TCP","podName":"cattle-prometheus:exporter-node-cluster-monitoring-wm48m","allNodes":false},{"nodeName":"local:machine-2vtf5","addresses":["3.15.239.212"],"port":9796,"protocol":"TCP","podName":"cattle-prometheus:exporter-node-cluster-monitoring-wv662","allNodes":false}]]
```

**Comment by mrajashree** [comment]
@dnoland1 v2.5.2-rc3 can be used now for testing

**Comment by sowmyav27** [comment]
Blocked because of issue - https://github.com/rancher/rancher/issues/29690

**Comment by sowmyav27** [comment]
**Verified using 2.5-head commit id: `1599dc142 `**

- Create a Rancher HA installation (2.4.8)
- Create a k3s cluster
- Import the k3s cluster into Rancher 
- Install Rancher onto the k3s clusters (2.5.1)
- Enable cluster monitoring on the imported cluster from the host cluster
- View Rancher logs of the tenant cluster and see the error similar to:

```
2020/10/07 16:42:31 [ERROR] error getting app cluster-monitoring apps.project.cattle.io "p-lch7c/cluster-monitoring" not found
2020/10/07 16:42:31 [ERROR] error getting app cluster-monitoring apps.project.cattle.io "p-lch7c/cluster-monitoring" not found
2020/10/07 16:42:31 [INFO] Updating workload [cattle-prometheus/exporter-node-cluster-monitoring] with public endpoints [[{"nodeName":"local:machine-7dmh4","addresses":["13.58.69.223"],"port":9796,"protocol":"TCP","podName":"cattle-prometheus:exporter-node-cluster-monitoring-wm48m","allNodes":false},{"nodeName":"local:machine-2vtf5","addresses":["3.15.239.212"],"port":9796,"protocol":"TCP","podName":"cattle-prometheus:exporter-node-cluster-monitoring-wv662","allNodes":false}]]
```

- Upgrade rancher from 2.5.1 to 2.5-head.
- Errors are not seen in the logs anymore.

**Comment by dnoland1** [comment]
Tested on v2.5-head. Last 20 minutes of graphs are on the new version, before that, rancher v2.5.1 was running.
![image](https://user-images.githubusercontent.com/468462/96961539-bdc14f80-14b9-11eb-9e2c-5d7143f572d6.png)
![image](https://user-images.githubusercontent.com/468462/96961559-c87be480-14b9-11eb-90bc-8c16851de23a.png)
![image](https://user-images.githubusercontent.com/468462/96961578-d16cb600-14b9-11eb-83ca-8045fe612e11.png)
![image](https://user-images.githubusercontent.com/468462/96961702-11cc3400-14ba-11eb-863a-b6a92202d4b3.png)
