### ISSUE TITLE
ui-offline-preferred as "dynamic" does not work does not work in 2.5-head

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29362]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- `ui-offline-preferred` in v3/settings is `dynamic` by default and the ui-index - `https://releases.rancher.com/ui/latest2/index.html` and dashboard index `"https://releases.rancher.com/dashboard/latest/index.html"` does not pull the latest UI changes. 
- For example: On 2.5-head with `ui-offline-preferred` is dynamic, the fixes for issue -- https://github.com/rancher/dashboard/issues/1602 is NOT available. When `ui-offline-preferred` is false, the fixes are seen. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `5d2dd90`
- Installation option (single install/HA): Single node

**Comment by cbron** [comment]
Believe this is a dupe of https://github.com/rancher/rancher/issues/29307 ?

**Comment by cbron** [comment]
> For example: On 2.5-head with ui-offline-preferred is dynamic, the fixes for issue is NOT available. When ui-offline-preferred is false, the fixes are seen.

This is actually correct because the dockerhub tag is v2.5-head, and that happens to match the release pattern of `v2.*`, it would only pull the latest on master-head. That is not what we actually want though, so we should adjust the `IsRelease` function.

**Comment by nickgerace** [comment]
Opened PR for backport to release/v2.5: #29572

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `b7228` and master-head - commit id: `b7228` with ui-offline-preferred - dynamic**

This issue is seen fixed - https://github.com/rancher/dashboard/issues/1583 . i.e: Default scan selected for an RKE node driver cluster - `rke-profile-permissive`

When ui-offline-preferred - false, Default scan selected for an RKE node driver cluster - `rke-profile-permissive`
