### ISSUE TITLE
K8s versions of the worker nodes do not get upgraded

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29370]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Bring up a HA setup - local cluster - k3s on rancher: 2.5.0-rc7
- Deploy a windows cluster - 1 linux ctrl and etcd, 1 worker node and 3 windows worker nodes (1903) k8s 1.18.9
- Upgrade k8s to 1.19.2
- K8s versions of the windows + linux worker nodes do not get upgraded
- seems like it stopped right after the master node got upgraded - `c-f8zvm` - cluster id

```
2020/10/05 04:50:57 [INFO] cluster [c-f8zvm] provisioning: [ingress] ingress controller nginx deployed successfully
2020/10/05 04:50:57 [INFO] cluster [c-f8zvm] provisioning: [addons] Setting up user addons
2020/10/05 04:50:57 [INFO] cluster [c-f8zvm] provisioning: [addons] no user addons defined
2020/10/05 04:50:57 [INFO] cluster [c-f8zvm] provisioning: Finished building Kubernetes cluster successfully
2020/10/05 04:51:03 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:37209
W1005 04:51:03.039196       8 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
2020/10/05 04:51:03 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/10/05 04:51:03 [INFO] Updated cluster [c-f8zvm] with node version [1]
2020/10/05 04:51:03 [INFO] Provisioned cluster [c-f8zvm]
2020/10/05 04:51:03 [INFO] checking cluster [c-f8zvm] for worker nodes upgrade
W1005 04:51:03.326876       8 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1005 04:51:06.040560       8 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
W1005 04:51:18.318061       8 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
```

**Expected Result:**
Windows + Linux worker nodes' k8s should get upgraded

**Other details that may be helpful:**

- k8s upgrade worked on windows nodes when upgraded from 1.18.8 to 1.19.2 from 2.4.8 to 2.5.0-rc7 on a HA setup with RKE local cluster
- k8s versions of a worker node get upgraded on 2.5.0-rc7 - HA with k3s cluster on an AWS node driver cluster (all linux nodes)
- Happens on an upgrade from 1.17 to 1.18 also
- This issue is working on 2.4.8 on a HA k3s cluster

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.0-rc7
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Windows custom
- Kubernetes version (use `kubectl version`):

```
1.18.9 to 1.19.2
```

**Comment by bmdepesa** [comment]
I was able to reproduce this with a linux cluster: 

* rancher v2.5.0-rc8, RKE local cluster 
* RKE ec2 downstream cluster  `1.16.15`
* Upgrade cluster to `1.17.12`
* Worker nodes do not upgrade 
```
> kubectl get nodes
NAME         STATUS   ROLES                      AGE   VERSION
bmd-ec2-e1   Ready    controlplane,etcd,worker   16m   v1.17.12
bmd-ec2-w1   Ready    worker                     14m   v1.16.15
bmd-ec2-w2   Ready    worker                     14m   v1.16.15
```

**Comment by izaac** [comment]
- Rancher v2.5.0-rc8, **K3s** local cluster 1.18.3
- RKE DO downstream cluster 1.16.15
- Upgrade cluster to 1.17.12
- Worker nodes do not upgrade


```
kubectl get no
NAME                     STATUS   ROLES                      AGE   VERSION
izaac-do-repro1-all-1    Ready    controlplane,etcd,worker   31m   v1.17.12
izaac-do-repro1-wrkr-1   Ready    worker                     30m   v1.16.15
izaac-do-repro1-wrkr-2   Ready    worker                     30m   v1.16.15
```

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `72d1332ed`**
- Deploy a k3s HA cluster.
- Deploy a windows cluster - 1 etcd/control, 1 worker linux nodes, and 3 windows worker nodes, in 1.17 k8s version
- Upgrade k8s to 1.18. All nodes including worker nodes got upgraded to the right version.
- Upgrade cluster k8s to 1.19. All nodes including worker nodes got upgraded to the right version.
- deploy an rke custom cluster - 1 etcd/control and 3 worker nodes. with k8s 1.17
- Upgrade k8s to 1.18. All nodes including worker nodes got upgraded to the right version.
- Upgrade cluster k8s to 1.19. All nodes including worker nodes got upgraded to the right version.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 72d1332ed

* Rancher in HA on RKE local cluster
* One custom cluster
* One ec2 node driver cluster
* All clusters have 1 node with all roles and 2 dedicated workers
* Upgrade each cluster from 1.15 -> 1.16
* Upgrade each cluster from 1.16 -> 1.17
* All cluster nodes upgrade to the correct versions

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `bb0344d`**

- Deploy a k3s HA cluster.
- Deploy a windows cluster - 1 etcd/control, 1 worker linux nodes, and 3 windows worker nodes, in 1.17 k8s version
- Upgrade k8s to 1.18. All nodes including worker nodes got upgraded to the right version.
- Upgrade cluster k8s to 1.19. All nodes including worker nodes got upgraded to the right version.
