### ISSUE TITLE
Creating new cluster stuck on "Pre-pulling kubernetes images"

### ISSUE THREAD

**Issue by UpperCenter** [rancher/rancher#29378]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Spin up a new Ubuntu Server 20.04 LTS virtual machine.
- Install the latest Docker, as per their [documentation](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository).
- Install Rancher, as per the [documentation](https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/).
- Create a new cluster from the web ui. (Add Cluster -> From existing nodes (custom) -> name cluster -> next -> select "etcd, Control Plane and worker")
- Paste docker string into terminal.

**Result:**
Cluster starts to create, but seems to get stuck on "Pre-pulling kubernetes images"

**Other details that may be helpful:**
* I have a stable internet connection.
* VM has 6 VCPU's and 8GB RAM and 100GB HDD

**Environment information**
- Docker Information:
```bash
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Rancher Version:
![image](https://user-images.githubusercontent.com/46819924/95104347-9d5d6b00-072d-11eb-8f19-b0c5ebf3a319.png)

- Installation option: Single Install.

**Rancher Error Screenshot**
![image](https://user-images.githubusercontent.com/46819924/95103207-41461700-072c-11eb-9c8c-a2d426bc3e71.png)

### Can anyone provide some insight into this issue?
Thanks a lot!

**Comment by superseb** [comment]
Pre-pulling images should not be any different than running `docker pull $IMAGE` on the node itself. What happens when that is manually run on the node? What is the Docker daemon logging at the moment it gets stuck at pre-pulling?

**Comment by UpperCenter** [comment]
> Pre-pulling images should not be any different than running `docker pull $IMAGE` on the node itself. What happens when that is manually run on the node? What is the Docker daemon logging at the moment it gets stuck at pre-pulling?

I'm not sure exactly what `$IMAGE` should be being pulled exactly.

I deleted the cluster, and started a new one up using the same steps. The Docker logs are included in the screenshot, sorry it's quite messy.

---

![image](https://user-images.githubusercontent.com/46819924/95261584-8e0c1980-0822-11eb-94cb-600403b196cd.png)

**Comment by superseb** [comment]
The default version for v2.4.8 is v1.18.8 and the image is `rancher/hyperkube:v1.18.8-rancher1`, you can try running `docker pull rancher/hyperkube:v1.18.8-rancher1`. The log regarding this operation should come from the Docker daemon, thats either in `/var/log/docker.log` or using `journalctl -u docker`.

It seems you are trying to run Rancher on the same machine you are trying to add to a cluster, we have specific docs on this here: https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/advanced/#running-rancher-rancher-and-rancher-rancher-agent-on-the-same-node. This is not the root cause of the issue (if the logs from the `rancher/rancher` container are actually stuck on `Pre-pulling kubernetes images`)

If you re-use nodes, you should follow https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/ as the install process can leave files behind that conflict with a new installation.

**Comment by UpperCenter** [comment]
It looks like the image has been pulled locally.
![image](https://user-images.githubusercontent.com/46819924/95311329-5e422d80-0885-11eb-9467-4a1ecb718d32.png)

---

I will follow the install steps in the doc you linked for a single node environment, and let you know. Thanks for the help.

**Comment by superseb** [comment]
Please run `rancher/rancher` with the `--debug` argument so it logs in debug and provide the logging. Also try to do this when the cluster provisioning is stuck (as well as capture the Docker logging), to pinpoint what is going on at that point.

**Comment by UpperCenter** [comment]
Do you also need me to run the Docker daemon in debug mode as documented [here?](https://docs.docker.com/config/daemon/#enable-debugging)

**Comment by superseb** [comment]
More info is usually good, if Rancher tries to pull the image and it hangs, and manually around the same time it works, we can compare the calls to Docker in that log.

**Comment by superseb** [comment]
Any info on this?

**Comment by UpperCenter** [comment]
Yeah, these are the logs being generated when I try and spin up a cluster:

```bash
INFO: Arguments: --server https://172.16.0.102 --token REDACTED --ca-checksum 8c9e2e6138c6af83b64a2736eb0f6b7aa048439c9d6b963e5151cc6c7b73725f --etcd --controlplane --worker
INFO: Environment: CATTLE_ADDRESS=172.16.0.102 CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=ganeymede CATTLE_ROLE=,etcd,worker,controlplane CATTLE_SERVER=https://172.16.0.102 CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 172.16.0.253 search cyber.local
ERROR: https://172.16.0.102/ping is not accessible (Empty reply from server)
INFO: Arguments: --server https://172.16.0.102 --token REDACTED --ca-checksum 8c9e2e6138c6af83b64a2736eb0f6b7aa048439c9d6b963e5151cc6c7b73725f --etcd --controlplane --worker
INFO: Environment: CATTLE_ADDRESS=172.16.0.102 CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=ganeymede CATTLE_ROLE=,etcd,worker,controlplane CATTLE_SERVER=https://172.16.0.102 CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 172.16.0.253 search cyber.local
INFO: https://172.16.0.102/ping is accessible
INFO: Value from https://172.16.0.102/v3/settings/cacerts is an x509 certificate
time="2020-10-16T14:11:50Z" level=info msg="Listening on /tmp/log.sock"
time="2020-10-16T14:11:50Z" level=info msg="Rancher agent version v2.5.1 is starting"
time="2020-10-16T14:11:50Z" level=info msg="Option customConfig=map[address:172.16.0.102 internalAddress: label:map[] roles:[etcd worker controlplane] taints:[]]"
time="2020-10-16T14:11:50Z" level=info msg="Option etcd=true"
time="2020-10-16T14:11:50Z" level=info msg="Option controlPlane=true"
time="2020-10-16T14:11:50Z" level=info msg="Option worker=true"
time="2020-10-16T14:11:50Z" level=info msg="Option requestedHostname=ganeymede"
time="2020-10-16T14:11:50Z" level=info msg="Connecting to wss://172.16.0.102/v3/connect/register with token 4j8g5qbjpk2c6hjfj5gpfkxdkdfpgzknl4hcctrjjflnxkrrczmbbx"
time="2020-10-16T14:11:50Z" level=info msg="Connecting to proxy" url="wss://172.16.0.102/v3/connect/register"
time="2020-10-16T14:11:50Z" level=error msg="Failed to connect to proxy. Response status: 400 - 400 Bad Request. Response body: Operation cannot be fulfilled on nodes.management.cattle.io \"m-2076849aadf4\": the object has been modified; please apply your changes to the latest version and try again" error="websocket: bad handshake"
time="2020-10-16T14:11:50Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2020-10-16T14:12:00Z" level=info msg="Connecting to wss://172.16.0.102/v3/connect/register with token 4j8g5qbjpk2c6hjfj5gpfkxdkdfpgzknl4hcctrjjflnxkrrczmbbx"
time="2020-10-16T14:12:00Z" level=info msg="Connecting to proxy" url="wss://172.16.0.102/v3/connect/register"
time="2020-10-16T14:12:00Z" level=info msg="Starting plan monitor, checking every 15 seconds"
time="2020-10-16T14:13:42Z" level=error msg="Remotedialer proxy error" error="websocket: close 1006 (abnormal closure): unexpected EOF"
time="2020-10-16T14:13:52Z" level=info msg="Connecting to wss://172.16.0.102/v3/connect with token 4j8g5qbjpk2c6hjfj5gpfkxdkdfpgzknl4hcctrjjflnxkrrczmbbx"
time="2020-10-16T14:13:52Z" level=info msg="Connecting to proxy" url="wss://172.16.0.102/v3/connect"
time="2020-10-16T14:13:52Z" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp 172.16.0.102:443: connect: connection refused"
time="2020-10-16T14:13:52Z" level=error msg="Remotedialer proxy error" error="dial tcp 172.16.0.102:443: connect: connection refused"
time="2020-10-16T14:14:02Z" level=info msg="Connecting to wss://172.16.0.102/v3/connect with token 4j8g5qbjpk2c6hjfj5gpfkxdkdfpgzknl4hcctrjjflnxkrrczmbbx"
time="2020-10-16T14:14:02Z" level=info msg="Connecting to proxy" url="wss://172.16.0.102/v3/connect"
```

**Comment by superseb** [comment]
This is the `rancher/rancher-agent` logging, can you share the `rancher/rancher` debug logging around the same timestamps?
