### ISSUE TITLE
Update k8s versions-10/14

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29373]
Expected versions
1.17.13
1.18.10
1.19.3

**Comment by maggieliu** [comment]
Duplicated

**Comment by deniseschannon** [comment]
Reopened to track the specific versions in the release

**Comment by jiaqiluo** [comment]
upgrading to new k8s versions is validated on a Rancher:`v2.5.1` single-install setup  

Steps:
- provision clusters for (all network providers) * (all k8s versions). each cluster has 1 etcd, 1 control plane, 2 workers.
- run pre-upgrade test
- upgrade (change KDM 2.5.1 pointing to dev-v2.5) 
- upgrade K8s versions to new versions 
- run post-upgrade checks



Before upgrade | New K8s version (KDM branch dev-v2.5) 
-- | --  
v1.16.15-rancher1-2 | No new version  
v1.17.12-rancher1-1 | v1.17.13-rancher1-1  
v1.18.9-rancher1-1 | v1.18.10-rancher1-1 
v1.19.2-rancher1-1 | v1.19.3-rancher1-1

**Comment by sowmyav27** [comment]
**On 2.5.1 - KDM pointing to dev-v2.5**

- Clusters with k8s versions - v1.17.13-rancher1-1, v1.18.10-rancher1-1, v1.19.3-rancher1-1 were deployed using all 4 network providers. Network checks passed on all these clusters.
- Automation checks passed on Canal clusters.
- Issue found while deploying ARM64 clusters - https://github.com/rancher/rancher/issues/29556
- Windows on these 3 k8s version ^^^ look good, validation checks passed.
