### ISSUE TITLE
[UI] Add new E2 Compute Shapes to OKE driver static list (v2.4.x)

### ISSUE THREAD

**Issue by jlamillan** [rancher/rancher#29382]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**

1. Create cluster in Rancher UI
2. Select Oracle OKE
3. In the version drop-down list, notice that some of the E2-based compute shapes are missing from the list. 

**Result:**
New 2-based compute shapes are missing from the list.

**Other details that may be helpful:**

We shouldn't need to make these types up manual updates in Rancher 2.5+ since they will be pulled _dynamically_.

**Environment information**
- Rancher version: v2.4.8 (using rancher/rancher:latest)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
Available in `latest-2.4`

**Comment by aaronRancher** [comment]
The feature is verified with Rancher server `rancher\rancher:master-head` `version e90c401`
Observed new E2 shapes in dropdown. Will need a fix to include a scroll bar. @westlywright 
![Screen Shot 2020-10-16 at 3 52 18 PM](https://user-images.githubusercontent.com/57409052/96321625-fbf6d480-0fca-11eb-9567-a654065d0480.png)

The feature is not seen in with Rancher server `rancher\rancher:v2.4-3962-head`
Did not observe new E2 compute shapes:
![Screen Shot 2020-10-16 at 4 14 25 PM](https://user-images.githubusercontent.com/57409052/96321603-e41f5080-0fca-11eb-8db1-aff2597de205.png)

Observed removed shapes in the dropdown:
![Screen Shot 2020-10-16 at 4 07 13 PM](https://user-images.githubusercontent.com/57409052/96321605-e681aa80-0fca-11eb-8f52-4bd8fa6e6bd9.png)

UI version: `"https://releases.rancher.com/ui/latest-2.4/index.html"`
Reopening for a fix in `2.4-head`

**Comment by deniseschannon** [comment]
@aaronRancher I can't imagine how the 1 PR would only show some of the changes.  

2.5 and Master pulls everything dynamically so testing it is very different than 2.4.

**Comment by deniseschannon** [comment]
@aaronRancher I see these shapes in v2.4-head. Can you re-test?

**Comment by aaronRancher** [comment]
Verified with Rancher server `rancher\rancher:v2.4-4033-head`

Observed new E2 shapes in dropdown
![Screen Shot 2020-10-20 at 4 52 52 PM](https://user-images.githubusercontent.com/57409052/96658680-03371e80-12fa-11eb-8be0-9e862c8279ae.png)
