### ISSUE TITLE
Default stack with no services, but I have a stack with services cause applications page to re-direct to  "Add first service"

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2938]
v0.49.0-rc1

Steps to Reproduce:
1. Have a fresh setup with no services
2. Add a service using rancher-compose in a different stack
3. Go to applications page

Result: Greeted with "Adding your first service" because there are no services in my stack. I can get to the stacks page by clicking on stack.

Expected Result: Go directly to stacks page as I have a stack (that is not the default).

**Comment by vincent99** [comment]
This is old, Seems to work for me now

**Comment by deniseschannon** [comment]
Verified no longer an issue in v1.1.0-rc2
