### ISSUE TITLE
[2.4 backport] Panic in rancher when upgrading k8s version of cluster with drain enabled

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29391]
2.4 Backport for: https://github.com/rancher/rancher/issues/29381

**Comment by jiaqiluo** [comment]
The bugfix is validated in v2.4-3786-head HA mode upgraded from v2.4.8 

- in v2.4.8 deploy Rancher HA in a rke cluster
- add several custom RKE clusters (through API) k8s - v1.17.11-rancher1-1, v1.16.15-rancher1-1
- upgrade rancher to 2.5-head
- Upgrade k8s version of the cluster to 1.18.9

All clusters are upgraded, and no restart/panic for rancher pods
