### ISSUE TITLE
Cattle Cluster and node agent of local cluster are present when upgraded to 2.5.0

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29397]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On 2.4.5 HA setup --> Cattle Cluster agent and cattle node agents are present in local cluster.
- On a fresh install of 2.5.0 --> Cattle Cluster agent and cattle node agents are NOT present in local cluster.
- on upgrading from 2.4.5 to 2.5.0, Cattle Cluster agent and cattle node agents are seen to be in 2.4.5 and not upgraded.

Should we delete Cattle Cluster agent and cattle node agents when upgraded to 2.5.0 ? 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.0
- Installation option (single install/HA): HA

gzrancher/rancher#12689

**Comment by rene-demonsters** [comment]
Wouldn't removing them break downgrading (or require special instructions)?

Also I started (but couldn't finish, see https://github.com/rancher/rancher/issues/28605#issuecomment-704252705) an upgrade to 2.5.0 coming from 2.4.8. In my case cattle-cluster-agent was upgraded to 2.5.0, but cattle-node-agent was (still) stuck at 2.4.8. 

Rancher itself is a single node docker install in our case.

**Comment by peetasan** [comment]
Upgrading from 2.4.8 to 2.5.1 I see that cluster-agents are not upgraded in the local cluster, while they are correctly upgraded in the imported clusters. Shall I upgrade/remove the ones stuck on 2.4.x?

**Comment by froland-git** [comment]
Hi everyone!
We are trying to add a new cluster to our EKS Rancher Server 2.5.0 using Terraform. But I ran into a problem:
`Cluster health check failed: deployments.apps "cattle-cluster-agent" not found`

**Comment by ibuildthecloud** [comment]
@froland-git That should be a temporary message that could happen before the agent is actually deployed.  Did the message persist or cause the cluster deployment to fail?

**Comment by preetam-patil** [comment]
@ibuildthecloud : We did encounter the same issue since we setup completely new rancher setup 2.5.1. The issue persisted since last 3-4 days for us. We are unable to spin up any clusters using Rancher 2.5.1 till now.Please suggest.

**Comment by sowmyav27** [comment]
**Verified on an upgrade from 2.4.8 to 2.5.2-rc3**

- Deploy a HA setup - 1 custom rke cluster and 1 imported rke cluster on rancher v2.4.8
- Upgrade rancher to 2.5.2-rc3
- Local ha cluster does not have cattle-cluster agent and node agent.
- Imported rke cluster has the cattle cluster agent only.
