### ISSUE TITLE
[2.4 backport] K8s versions of the worker nodes do not get upgraded

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29390]
Backport for: https://github.com/rancher/rancher/issues/29370

**Comment by izaac** [comment]
Rancher version: `v2.4-3786-head (10/07/2020)` _4dbd153bf_ k3s HA `v1.18.9+k3s1`

Windows downstream cluster

- One `Control Plane`
- One `etcd`
- One Linux `Worker`
- Three Windows `Workers`
- k8s `v1.15.12-rancher2-5`

Upgraded to k8s `v1.16.15-rancher1-1` All nodes were upgraded correctly.

```
kubectl get nodes
NAME               STATUS   ROLES          AGE   VERSION
ip-172-31-10-229   Ready    controlplane   37m   v1.16.15
ip-172-31-15-219   Ready    worker         36m   v1.16.15
ip-172-31-2-85     Ready    etcd           37m   v1.16.15
ip-ac1f07d7        Ready    worker         33m   v1.16.15
ip-ac1f0c57        Ready    worker         33m   v1.16.15
ip-ac1f0dea        Ready    worker         30m   v1.16.15
```
