### ISSUE TITLE
Containers not linked after setting a new CATTLE_AGENT_IP to private IP address for existing host AND adding any new containers

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#294]
Version: v0.12.0

Steps to Reproduce:

1. Create an environment with at 4 hosts (Host A, Host B, Host C, Host D). 
1. Create containers on 3 hosts (Host A, Host B, Host C).
1. Update private IP on Host A. 
1. Using the shell prompt, ping containers between all 3 hosts. This works for for now between all Hosts.
1. If I create the first container on Host D.

Result: 
* Containers on Host B & Host C can ping each other. 
* Containers on Host A cannot be reached from any host. No errors, just 100% packet loss. 
* Container on Host D errors out as "Destination Host Unreachable" from Host B/C. 

Following steps change the communication between hosts:
Scenario 1: If I create additional containers as the first container on a host, the communication between containers remain the same. The host that just got the new network agent and container will not be able to communicate with any container.

Scenario 2: As soon as I create a container on a host that already had the network agent. All the hosts (except for Host A) will be able to communicate with each other. This would include any host in Scenario 1 that was previously not working.

Expected Result: All communication between Host A and other hosts after IP is reset to the host's private IP.

**Comment by will-chan** [comment]
please re-test.

**Comment by deniseschannon** [comment]
Expectation should be that all network traffic for mix of public/private IPs in a Rancher setup should be routable. 

After updating all hosts to a private IP, networking will work after you add a new container.
