### ISSUE TITLE
Certificate replace problem

### ISSUE THREAD

**Issue by impsik** [rancher/rancher#29401]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
According to documentation (which is is down at the moment: https://rancher.com/docs/rancher/v2.x/en/installation/options/tls-secrets/) if i need to replace certificate i should delete the tls-rancher-ingress secret using kubectl -n cattle-system delete secret tls-rancher-ingress and add a new one. 
If i delete this secret then it's right back. If i try to replace certificate & key using UI, then automatically it puts back this dynamiclistener-ca certificate.

Aloso tried:
`kubectl -n cattle-system delete secret tls-rancher-ingress; kubectl -n cattle-system create secret tls tls-rancher-ingress   --cert=tls.crt   --key=tls.key`
secret "tls-rancher-ingress" deleted
secret/tls-rancher-ingress created

Still that self signed is back
Also:
```
kubectl -n cattle-system create secret tls tls-rancher-ingress \
>   --cert=tls.crt \
>   --key=tls.key \
>   --dry-run --save-config -o yaml | kubectl apply -f -
```
W1006 12:10:44.596723   19501 helpers.go:535] --dry-run is deprecated and can be replaced with --dry-run=client.
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
secret/tls-rancher-ingress configured

**Result:**

**Other details that may be helpful:**
helm.sh/chart=cert-manager-v0.12.0

**Environment information**
- Rancher version: 2.4.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.10

```

**Comment by impsik** [comment]
Anyone? Maybe a hint if i'm doing something wrong or you need more info?

**Comment by burak00136** [comment]
> Anyone? Maybe a hint if i'm doing something wrong or you need more info?

**Comment by Kampe** [comment]
I see the same issue with my certificate replacements.  Looking at the ingress-nginx controller shows 404's - anyone have a solution to this? 

```
GET /.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx HTTP/1.1" 404
```
