### ISSUE TITLE
Rancher 2.5 does not start on 'just docker' node (not kubernetes)

### ISSUE THREAD

**Issue by pgonin** [rancher/rancher#29407]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
When I follow instructions from https://rancher.com/quick-start/
on SUSE Linux Enterprise Server 15 SP2 CHOST (Container Host - with docker by default)

`sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher`

**Result:**
The Rancher container fails to start and is stuck on Restarting STATUS
```
# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                          PORTS               NAMES
3da64aa88709        rancher/rancher     "entrypoint.sh"     15 minutes ago      Restarting (1) 34 seconds ago                       bold_hoover
```

**Other details that may be helpful:**
I did not try to reproduce on Ubuntu yet or SLES15SP1 (which are actually supported)

**Environment information**
- Docker version (use `docker version`):

```
# docker --version
Docker version 19.03.5, build 633a0ea838f1

# docker images --digests
REPOSITORY          TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
rancher/rancher     latest              sha256:f08b814d51c592d3c4029ffc65e5319b64aa44f208a85cc1e600b4e0d97dad78   918b8c8305e4        11 hours ago        964MB
```

I understand the image is expecting to run on a kubernetes node
```
# docker logs bold_hoover
ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
```

**Comment by vincent99** [comment]
The quick start page hasn't been updated yet, but as the message says you need to add `--privileged` to the docker options now.

**Comment by pgonin** [comment]
Indeed, same with bionic.

It works fine with the command `sudo docker run --privileged -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher`

Thanks. Closing.

While you're on the quick start page the link https://rancher.com/support-maintenance-terms/all-supported-versions/ redirects by default to https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.3.4/ (at least in my case)

**Comment by pgonin** [comment]
and it's actually documented correctly in https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/
