### ISSUE TITLE
Internal Rancher load balancer mysteriously stops working

### ISSUE THREAD

**Issue by rzachariah** [rancher/rancher#2940]
Hi there,

I've set up a routing solution with two Rancher load balancers, a public one which, routes traffic from a public port, and an internal one, which does path based routing. I have these in two separate stacks. One of the stacks (the internal one) is portable from environment to environment. The other depends on ports available on the host.

Usually, this works fine, but occasionally the internal load balancer stops working. It becomes unable to route traffic. When I restart it, it starts working again. I don't see anything in the log that indicates the problem. Do you have any suggestions for how to diagnose this?

Here's the rancher LB log. Looks like nothing interesting happens until I restart the service today.

11/25/2015 2:12:17 PMINFO: Updating monit
11/25/2015 2:12:17 PMINFO: Downloading http://10.164.51.171:8080/v1//configcontent//monit current=
11/25/2015 2:12:17 PMINFO: Running /var/lib/cattle/download/monit/monit-1-d166a713486fe4c0f039e152939d8d3b8ab8e6c2518e13d88f0b7ec68da46109/apply.sh
11/25/2015 2:12:17 PMINFO: ROOT -> ./
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/monit/
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/monit/monitrc
11/25/2015 2:12:17 PMINFO: Sending monit applied 1-d166a713486fe4c0f039e152939d8d3b8ab8e6c2518e13d88f0b7ec68da46109
11/25/2015 2:12:17 PMINFO: Getting haproxy
11/25/2015 2:12:17 PMINFO: Updating haproxy
11/25/2015 2:12:17 PMINFO: Downloading http://10.164.51.171:8080/v1//configcontent//haproxy current=
11/25/2015 2:12:17 PMINFO: Running /var/lib/cattle/download/haproxy/haproxy-1-02ea5d48cf5da5fc868cc4906e972d5178969de851be5b1e12dc5f3386e18378/apply.sh
11/25/2015 2:12:17 PMINFO: ROOT -> ./
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/haproxy/
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/haproxy/certs/
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/haproxy/certs/default.pem
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/haproxy/certs/certs.pem
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/haproxy/haproxy.cfg
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/monit/
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/monit/conf.d/
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/monit/conf.d/haproxy
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/default/
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/default/haproxy
11/25/2015 2:12:17 PMINFO: Sending haproxy applied 1-02ea5d48cf5da5fc868cc4906e972d5178969de851be5b1e12dc5f3386e18378
11/25/2015 2:12:17 PMINFO: HOME -> ./
11/25/2015 2:12:17 PMINFO: HOME -> ./etc/
11/25/2015 2:12:17 PMINFO: HOME -> ./etc/cattle/
11/25/2015 2:12:17 PMINFO: HOME -> ./etc/cattle/startup-env
11/25/2015 2:12:17 PMINFO: ROOT -> ./
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/init.d/
11/25/2015 2:12:17 PMINFO: ROOT -> ./etc/init.d/agent-instance-startup
11/25/2015 2:12:17 PMINFO: Sending agent-instance-startup applied 1-557156a6c83b3adc996b56beb2d4469f282a091c31fd17461c90ee76fa7fe6e0
11/25/2015 2:12:17 PMmonit: generated unique Monit id 8acbdc5e5df331e582dfd74eda23a6cf and stored to '/var/lib/monit/id'
11/25/2015 2:12:17 PMStarting monit daemon with http interface at [localhost:2812]
12/7/2015 2:46:40 PM
The system is going down NOW!
12/7/2015 2:46:40 PM
Sent SIGTERM to all processes
12/7/2015 2:46:41 PM
Sent SIGKILL to all processes
12/7/2015 2:46:41 PM
Requesting system reboot
12/7/2015 2:46:59 PMINFO: Downloading agent http://10.164.51.171:8080/v1/configcontent/configscripts
12/7/2015 2:46:59 PMINFO: Updating configscripts
12/7/2015 2:46:59 PMINFO: Downloading http://10.164.51.171:8080/v1//configcontent//configscripts current=
12/7/2015 2:46:59 PMINFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f5763391fb7914dcd14001f29ffe28d1167a3bfcc0ee0ec05d2ca9c722103c02/apply.sh
12/7/2015 2:46:59 PMINFO: Sending configscripts applied 1-f5763391fb7914dcd14001f29ffe28d1167a3bfcc0ee0ec05d2ca9c722103c02
12/7/2015 2:46:59 PMINFO: Updating agent-instance-startup
12/7/2015 2:46:59 PMINFO: Downloading http://10.164.51.171:8080/v1//configcontent//agent-instance-startup current=
12/7/2015 2:46:59 PMINFO: Running /var/lib/cattle/download/agent-instance-startup/agent-instance-startup-2-557156a6c83b3adc996b56beb2d4469f282a091c31fd17461c90ee76fa7fe6e0/apply.sh
12/7/2015 2:46:59 PMINFO: Updating services
12/7/2015 2:46:59 PMINFO: Downloading http://10.164.51.171:8080/v1//configcontent//services current=
12/7/2015 2:46:59 PMINFO: Running /var/lib/cattle/download/services/services-1-061405f3edd960bfdfe1cfb8447be40eab5b4b608731608e224cc51c5dc30b91/apply.sh
12/7/2015 2:46:59 PMINFO: HOME -> ./
12/7/2015 2:46:59 PMINFO: HOME -> ./services
12/7/2015 2:46:59 PMINFO: Sending services applied 1-061405f3edd960bfdfe1cfb8447be40eab5b4b608731608e224cc51c5dc30b91
12/7/2015 2:46:59 PMINFO: Getting agent-instance-scripts
12/7/2015 2:46:59 PMINFO: Updating agent-instance-scripts
12/7/2015 2:46:59 PMINFO: Downloading http://10.164.51.171:8080/v1//configcontent//agent-instance-scripts current=
12/7/2015 2:46:59 PMINFO: Running /var/lib/cattle/download/agent-instance-scripts/agent-instance-scripts-1-4b5124bd74cd423f98d57550b481ec77ec3a7135c6a650886ab95c043305d642/apply.sh
12/7/2015 2:46:59 PMINFO: HOME -> ./
12/7/2015 2:46:59 PMINFO: HOME -> ./events/
12/7/2015 2:46:59 PMINFO: HOME -> ./events/config.update
12/7/2015 2:46:59 PMINFO: HOME -> ./events/ping
12/7/2015 2:46:59 PMINFO: Sending agent-instance-scripts applied 1-4b5124bd74cd423f98d57550b481ec77ec3a7135c6a650886ab95c043305d642
12/7/2015 2:46:59 PMINFO: Getting monit
12/7/2015 2:46:59 PMINFO: Updating monit
12/7/2015 2:46:59 PMINFO: Downloading http://10.164.51.171:8080/v1//configcontent//monit current=
12/7/2015 2:46:59 PMINFO: Running /var/lib/cattle/download/monit/monit-1-d166a713486fe4c0f039e152939d8d3b8ab8e6c2518e13d88f0b7ec68da46109/apply.sh
12/7/2015 2:46:59 PMINFO: ROOT -> ./
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/monit/
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/monit/monitrc
12/7/2015 2:46:59 PMINFO: Sending monit applied 1-d166a713486fe4c0f039e152939d8d3b8ab8e6c2518e13d88f0b7ec68da46109
12/7/2015 2:46:59 PMINFO: Getting haproxy
12/7/2015 2:46:59 PMINFO: Updating haproxy
12/7/2015 2:46:59 PMINFO: Removing haproxy-34-39f1f6bdd2527b0410ecb7df9b0e2ca45693af0171597b58595d57a7c1083aa6
12/7/2015 2:46:59 PMINFO: Downloading http://10.164.51.171:8080/v1//configcontent//haproxy current=
12/7/2015 2:46:59 PMINFO: Running /var/lib/cattle/download/haproxy/haproxy-59-f2841f471f610f1abdb0bec6ce97912d8d19cd0ea731af73dd3c4ec7be331be2/apply.sh
12/7/2015 2:46:59 PMINFO: ROOT -> ./
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/haproxy/
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/haproxy/certs/
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/haproxy/certs/default.pem
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/haproxy/certs/certs.pem
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/haproxy/haproxy.cfg
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/monit/
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/monit/conf.d/
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/monit/conf.d/haproxy
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/default/
12/7/2015 2:46:59 PMINFO: ROOT -> ./etc/default/haproxy
12/7/2015 2:47:00 PMINFO: Sending haproxy applied 59-f2841f471f610f1abdb0bec6ce97912d8d19cd0ea731af73dd3c4ec7be331be2
12/7/2015 2:47:00 PMINFO: HOME -> ./
12/7/2015 2:47:00 PMINFO: HOME -> ./etc/
12/7/2015 2:47:00 PMINFO: HOME -> ./etc/cattle/
12/7/2015 2:47:00 PMINFO: HOME -> ./etc/cattle/startup-env
12/7/2015 2:47:00 PMINFO: ROOT -> ./
12/7/2015 2:47:00 PMINFO: ROOT -> ./etc/
12/7/2015 2:47:00 PMINFO: ROOT -> ./etc/init.d/
12/7/2015 2:47:00 PMINFO: ROOT -> ./etc/init.d/agent-instance-startup
12/7/2015 2:47:00 PMINFO: Sending agent-instance-startup applied 2-557156a6c83b3adc996b56beb2d4469f282a091c31fd17461c90ee76fa7fe6e0
12/7/2015 2:47:00 PMStarting monit daemon with http interface at [localhost:2812]

**Comment by cusspvz** [comment]
@rzachariah could you please tell me if it stops responding or it just delays your http requests?

**Comment by alena1108** [comment]
@rzachariah is it easy to reproduce? If so, could you please check the following once the issue occurs:

* login to the LB instance and try to send a request to any of your backend targets - this is to ensure that the LB instance can reach other instances on the managed network
* login to any other instance of the managed network, and try to reach the LB instance 10.42.x.x:[listening port]. This is to ensure LB is accessible by other instances on the managed network.

@sangeethah have you noticed anything like that behavior while running validation tests? If not, we could run a small test:

1) Setup LB with one backend - nginx for example.
2) Write a script sending http requests to the LB every second. See if any of the requests got dropped at any point.

**Comment by deniseschannon** [comment]
@rzachariah If you are still facing this issue, please re-open and provide the details requested above.
