### ISSUE TITLE
Typo in Cluster Exporter - App Rancher Monitoring - Rancher v2.5.0

### ISSUE THREAD

**Issue by pirminjanka** [rancher/rancher#29406]
There is a typo in Cluster Exporter App Rancher Monitoring (Promeheis instead of Prometheus):

![Screenshot from 2020-10-06 16-29-26](https://user-images.githubusercontent.com/6124253/95221234-871be180-07f7-11eb-8c82-bc849f595a58.png)

**Comment by vincent99** [comment]
Prometheis is the [preferred](https://prometheus.io/docs/introduction/faq/#what-is-the-plural-of-prometheus) plural of Prometeus.
