### ISSUE TITLE
404 received when using browser navigation back from the explorer

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#29409]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Deploy 2.5.0
Create a cluster
Click the "Explorer" button next to the cluster from the list page
Hit "back" in your browser

**Result:**
You'll get a 404 from Nuxt.js

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.0
- Installation option (single install/HA): HA

**Comment by Oats87** [comment]
This is being tracked in the rancher/dashboard issue here: https://github.com/rancher/dashboard/issues/1635

**Comment by deniseschannon** [comment]
Closing in favor of the dashboard issue.
