### ISSUE TITLE
RFE Support specifying UI images path in Rancher Helm Chart

### ISSUE THREAD

**Issue by wjimenez5271** [rancher/rancher#29419]
Goal is to support the functionality that is in the docker install format of Rancher in Helm based installs as described here https://github.com/rancher/ui/tree/master/public/assets/images/logos. Implementation should involve adding one parameter, the Helm equivalent of: `-v /path/to/your/logos:/usr/share/rancher/ui/assets/images/logos`

gzrancher/rancher#12687

**Comment by rawmind0** [comment]
@wjimenez5271 , submitted a PR https://github.com/rancher/rancher/pull/29443, adding the option to add rancher pvc for custom logos.

**Comment by dnoland1** [comment]
@rawmind0 Saw the PR for this. Is it possible to have the option of using a hostPath instead of a PVC? Our plan is to copy custom logos to a directory on the host during bootstrap and having a hostPath will allow us to easier mount it into the pod without having to get the custom logos into a PVC.

**Comment by dkeightley** [comment]
Or a ConfigMap that stores the logo file data as filename key/values? When moving Rancher (v2.5) between underlying clusters the PVC could become troublesome.

**Comment by rawmind0** [comment]
@dnoland1 , i was already valuating on this option, but finally i though that using pvc seems a more proper way on a k8s cluster. Hostpath use case could be covered using https://github.com/rancher/local-path-provisioner. 

Instead of copy files during bootstrap, another good option could be add a git repo option and a sidecar on the chart, to pull custom logos from a git repo. Also, custom logos will be always updated without the need to copy them again. What do you think??

@dkeightley , the problem i can see using ConfigMap is that you should provide all the logos files to helm, to be able to render all custom logos within the ConfigMap

**Comment by dkeightley** [comment]
@rawmind0 got it, if there was a 'custom' directory the ConfigMap could volume mount only the logos that were being updated, and the UI preferred logos from this directory, it would make this approach easier.

**Comment by rawmind0** [comment]
@dkeightley, a custom directory where?? I don't fully get your point..

**Comment by rawmind0** [comment]
As discussed with @dkeightley , updated PR's https://github.com/rancher/rancher/pull/29443 https://github.com/rancher/rancher/pull/29444 adding the chance to use persistentVolumeClaim or configMap as custom logos persistence volume.

**Comment by rawmind0** [comment]
Resuming how the feature should work on PR's #29443 #29444:
* Added chart values
```
# Rancher custom logos persistence
customLogos:
  enabled: false
  ## set ui private label
  # privateLabel: label
  ## Volume kind to use as persistence, persistentVolumeClaim or configMap
  volumeKind: persistentVolumeClaim
  ## Use an existing volume. Custom logos should be copied to the volume by the user
  # volumeName: volume
  ## Just for volumeKind: persistentVolumeClaim 
  ## To disables dynamic provisioning, set storageClass: "" or storageClass: "-"
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 1Gi
```
* Custom logos can use 2 distinct volumes kind for persistence (user should copy files at the volume):
  *  `configMap`:  use existing one with customLogos.volumeName.
  * `persistentVolumeClaim`: create new pvc or use existing one with `customLogos.volumeName`. pvc `customLogos.storageClass`, `customLogos.accessMode` and `customLogos.size` can also be configured.
* Custom logos [private label](https://github.com/rancher/ui/tree/master/public/assets/images/logos#private-labeling) can also be configured by the chart setting `customLogos.privateLabel`. This is set as an option to Rancher setting `/v3/settings/ui-pl`, setting `CATTLE_UI_PL` env variable at Rancher pods. The downside of using env variable is that to update value, Rancher should be redeployed.

**Comment by superseb** [comment]
Because privateLabel is a separate setting is not related to logos, I would prefer to have `privateLabel` as a top level key which is then only applied if its used, else nothing changes. Although probably used together frequently, I dont think privateLabel is part of custom logos where it now lives under the `customLogos` configuration key. @wjimenez5271 thoughts?

**Comment by wjimenez5271** [comment]
@superseb makes sense to me, but I'd defer to @dnoland1 on this as he will be consuming this feature first.

**Comment by dnoland1** [comment]
Agree with @superseb. Would make more sense to have `privateLabel` as a top level key or maybe under `settings`. My use case doesn't have a need to set privateLabel during helm install/upgrade, so it's a nice to have. Can always do it via API or Terraform.

**Comment by rawmind0** [comment]
@superseb , @dnoland1 how private Label is not related with custom logos?? Why is it explained on custom logos readme?? May be i'm missing something, but for me is part of the same, customize the ui view. By one side, changing the images with the custom logos and by other way changing private label to update the text. At the moment, there is no `settings` section on the chart values definition, and it set it alone as `privateLabel` seems to me a little bit out of context. For me makes more sense to set `customLogos.privateLabel` than `privateLabel` because of the context. 

Anyway, not a problem set it on one place or another, but please tell me to update and close this.

**Comment by rawmind0** [comment]
Updated PR's removing optional `customLogos.privateLabel` var to set `CATTLE_UI_PL` env var. Rancher chart `extraenv` may be used to add env var if needed

**Comment by vincent99** [comment]
If you're going to do this you should have a second subpath mounted on top of `usr/share/rancher/ui-dashboard/dashboard/_nuxt/img/pl` for the new vue UI at the same time (https://github.com/rancher/dashboard/pull/1704/)

**Comment by jiaqiluo** [comment]
Reopen this issue because we need to add support for passing logos to the dashboard.

**Comment by rawmind0** [comment]
> If you're going to do this you should have a second subpath mounted on top of usr/share/rancher/ui-dashboard/dashboard/_nuxt/img/pl for the new vue UI at the same time (rancher/dashboard#1704)

@vincent, you mean that we need 2 volumes mounted at, ember ui [`/usr/share/rancher/ui/assets/images/logos`](https://github.com/rancher/ui/tree/master/public/assets/images/logos) and vue ui  [`/usr/share/rancher/ui-dashboard/dashboard/_nuxt/img/pl`](https://github.com/vincent99/dashboard/blob/8c6abe36a934e985a61c3b799f9965d830fe0707/assets/images/pl/README.md), isn't it??  Both volumes are required always, or ember ui can be logo customized without vue ui logo customization and viceversa??

**Comment by maggieliu** [comment]
@jiaqiluo created a different issue to track the need for cluster explorer side. Can you please validate this RFE is ok for the cluster manager side? If it is we can close it and track the dashboard/cluster explorer side via this [issue](https://github.com/rancher/rancher/issues/29813)

**Comment by vincent99** [comment]
You need two mounts, since they're two different directories, but could do it with one volume/two mounts with subPaths I think...

**Comment by rawmind0** [comment]
Submitted PR's https://github.com/rancher/rancher/pull/29897 and https://github.com/rancher/rancher/pull/29896 providing volume subpaths for ember and vue ui custom logos

**Comment by rawmind0** [comment]
PR #29897 implements the solution using one volume with 2 subpaths. But subpath option has a limitation if using `volumeKind: configmap` storage, [`A container using a ConfigMap as a subPath volume mount will not receive ConfigMap updates`](https://kubernetes.io/docs/concepts/storage/volumes/#configmap). Is redeployment on configmap update acceptable to you??

The alternative to subpath option would be using 2 volumes, that doesn't have the update limitation but 2 volumes should be managed.  

@dkeightley  @dnoland1 , what option is preferred here??

**Comment by jiaqiluo** [comment]
The first part of the enhancement [Updated chart and tests to allow specify Rancher custom logos persistence](https://github.com/rancher/rancher/pull/29444) is validated on rancher:`v2.5.2-rc6` HA mode.

Steps:
- use RKE CLI to provision a 1-node RKE cluster with k8s `v1.19.3` 	
- ssh into the node to put customized icons to a directory. [the original icons](https://github.com/rancher/ui/tree/master/public/assets/images/logos)
```
> pwd
/home/ubuntu/custom-icons
> ls
README.md        fail-cloud3.svg        fail-plane.svg  helm-v3.svg          provider-local.svg          text.svg                welcome-scene.png
dark.svg         fail-cloud4.svg        fail-prop.svg   main-loading.svg     provider-orchestration.svg  welcome-back-hill.svg   welcome-sun.svg
fail-cloud1.svg  fail-cloud5.svg        favicon.ico     main.svg             rancher-logo-cow-white.svg  welcome-cow.svg
fail-cloud2.svg  fail-cowparachute.svg  graphic.svg     provider-custom.svg  rke.svg                     welcome-front-hill.svg
```

- create the PV and PVC in the cluster 

the sample YAML for the PV 
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: custom-icon-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/custom-icons"
```
```
>  k get pvc -A
NAMESPACE       NAME              STATUS   VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cattle-system   custom-icon-pvc   Bound    custom-icon-pv   10Gi       RWO            manual         42m
```

- install rancher with the following command
```
> helm install rancher rancher-latest/rancher \
--version v2.5.2-rc6 \
--namespace cattle-system
--set hostname=<your-hostname>
--set customLogos.enabled=true
--set customLogos.volumeName=custom-icon-pvc
--set customLogos.size=10Gi
```


Results:
The only 2 icons that I changed shows in the UI
```
favicon.ico
helm-v3.svg 
```

<img width="1542" alt="Screen Shot 2020-11-03 at 1 55 57 PM" src="https://user-images.githubusercontent.com/6218999/98041191-c7fb1c00-1dde-11eb-9e84-02fa70a5e991.png">

**Comment by dnoland1** [comment]
> PR #29897 implements the solution using one volume with 2 subpaths. But subpath option has a limitation if using `volumeKind: configmap` storage, [`A container using a ConfigMap as a subPath volume mount will not receive ConfigMap updates`](https://kubernetes.io/docs/concepts/storage/volumes/#configmap). Is redeployment on configmap update acceptable to you??
> 
> The alternative to subpath option would be using 2 volumes, that doesn't have the update limitation but 2 volumes should be managed.
> 
> @dkeightley @dnoland1 , what option is preferred here??

@rawmind0 Let's stick with what you already implemented. I think we can make that work. If we run into problems, we can try the second option.

**Comment by vincent99** [comment]
You probably don't really want to use a configmap anyway, that's going to limit the size of the images you can store.

**Comment by rawmind0** [comment]
> @rawmind0 Let's stick with what you already implemented. I think we can make that work. If we run into problems, we can try the second option.

@dnoland1, It's gonna work but implies a Rancher redeployment if using configMap and it's updated. Ok, going ahead with subpath option

> You probably don't really want to use a configmap anyway, that's going to limit the size of the images you can store.

Completely agreed @vincent99 . We had some discussions about that but @dkeightley is pretty interested on that option.
