### ISSUE TITLE
[Logging V2]  Logs should include data about their source

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#29410]
Currently some of the logs rancher collects do not have any meta data on them regarding service, container, file.  Without this data it is not possible to filter these logs in a meaningful way.  

e.g. of an log that cannot be filtered

```
{
  "_index": "k8s-components",
  "_type": "_doc",
  "_id": "QPnx_nQBv93224yCqqCu",
  "_version": 1,
  "_score": null,
  "_source": {
    "log": "I1006 17:24:07.743856   14521 setters.go:77] Using node IP: \"10.99.1.102\"\n",
    "stream": "stderr",
    "time": "2020-10-06T17:24:07.744186749Z",
    "foo": "bar"
  },
  "fields": {
    "time": [
      "2020-10-06T17:24:07.744Z"
    ]
  },
  "highlight": {
    "log": [
      "I1006 17:24:07.743856   14521 @kibana-highlighted-field@setters.go@/kibana-highlighted-field@:77] Using node IP: \"10.99.1.102\""
    ]
  },
  "sort": [
    1602005047744
  ]
}
```

**Comment by izaac** [comment]
Blocked by #29620

**Comment by izaac** [comment]
Rancher version `master-head (10/21/2020)`  I've validated that the latest chart version is collecting the node logs properly from the RKE node logs. `/var/lib/rancher/logging/rke` 

I saw the [expected output format](https://github.com/rancher/charts/pull/787#issuecomment-708039576) in the Elastic Search output.

**Comment by izaac** [comment]
I will validate this in `2.5-head` too.

**Comment by izaac** [comment]
Rancher version `v2.5-head (10/21/2020)` _61a8a36_ 

I've validated that the latest chart version is collecting the node logs properly from the RKE node logs. `/var/lib/rancher/logging/rke` 

I saw the [expected output format](https://github.com/rancher/charts/pull/787#issuecomment-708039576) in the Elastic Search output.

**Comment by mscbpi** [comment]
> Rancher version `v2.5-head (10/21/2020)` _[61a8a36](https://github.com/rancher/rancher/commit/61a8a3691063108bc775c8e4e6f6db971541c253)_
> 
> I've validated that the latest chart version is collecting the node logs properly from the RKE node logs. `/var/lib/rancher/logging/rke`
> 
> I saw the [expected output format](https://github.com/rancher/charts/pull/787#issuecomment-708039576) in the Elastic Search output.

Hi izaac,

I don't see logs coming from `/var/lib/rancher/logging/rke` but rather `/var/lib/rancher/rke/log/*` in latest rancher, and rancher logging charts.

There's quite no reference anywhere to `/var/lib/rancher/logging/rke` while this file is growing and can be the cause of `Disk Pressure`. 

Is a ClusterFlow / ClusterOutput supposed to process this file ?
