### ISSUE TITLE
local k3s cluster should not be upgradable in Rancher single install mode 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#29412]
**What kind of request is this (question/bug/enhancement/feature request):**
bug 

**Steps to reproduce (least amount of steps as possible):**
- run rancher:v2.5.0, single install 
- edit the local cluster, and there are new k3s version available in the dropdown list 

 
<img width="1428" alt="Screen Shot 2020-10-06 at 11 56 44 AM" src="https://user-images.githubusercontent.com/6218999/95247710-0f37c200-07cb-11eb-905a-f586ef31ef40.png">

- choose a newer version and upgrade 

**Result:**
The local cluster starts the upgrading process which will never finish 
<img width="1441" alt="Screen Shot 2020-10-06 at 11 35 01 AM" src="https://user-images.githubusercontent.com/6218999/95246018-c1ba5580-07c8-11eb-9ecd-03f764343ba7.png">
 
**Expected Result:**

We do not support upgrading the local k3s cluster in a rancher single-install setup.

**Comment by aleksey005** [comment]
joy 
send one unvalidated byte and the system will crash
scream

**Comment by jiaqiluo** [comment]
This is not an issue in v2.4.x in the docker-install mode 
 
![screencapture-64-225-121-169-c-local-edit-2020-10-08-10_25_55](https://user-images.githubusercontent.com/6218999/95493129-e5a8a300-0950-11eb-8fcb-665cfdca3e9b.png)

**Comment by jiaqiluo** [comment]
The bugfix is validated on rancher:`v2.5-7a10a58973a03121a49f8f4efb1f52292a446b7d-head`, docker install 

Now there is no upgrade option for the local cluster on the edit page 

<img width="1467" alt="Screen Shot 2020-10-16 at 11 35 18 AM" src="https://user-images.githubusercontent.com/6218999/96296731-998add80-0fa4-11eb-91f1-13b2b9925be9.png">

**Comment by jiaqiluo** [comment]
reopen to wait for the fix available in master-head

**Comment by cbron** [comment]
Just merged in master.

**Comment by jiaqiluo** [comment]
The bugfix is validated in rancher:`master-35e2ab8aad5a06f89c4dde7daeb8ca179c27ae77-head` 

No upgrade option for the local cluster in docker-install mode.

**Comment by alexfok007** [comment]
i hit this bug, may i know the solution to stop upgrading the local cluster ?

**Comment by cbron** [comment]
@alexfok007 In rancher 2.5.1 it's not possible to hide this but it will be fixed in 2.5.2. In 2.5.1 you might get away with changing the local clusters driver setting to `"local"` but that isn't tested and it might not stick.

**Comment by TrueCarry** [comment]
I encountered this issue in single node docker install v2.5.7. Any options to fix besides upgrading to 2.5.8 which is not stable yet?

**Comment by dramich** [comment]
@cbron This is still an issue, 2.5.7 shows multiple versions you can upgrade a `docker run` local cluster to. 
![Screen Shot 2021-04-05 at 11 36 36 AM](https://user-images.githubusercontent.com/13897607/113605025-54667080-9603-11eb-8c3b-ddbfa6c689da.png)

**Comment by cbron** [comment]
@dramich we are attempting to fix via UI now. I'm going to close this and re-open: https://github.com/rancher/rancher/issues/30977

**Comment by cbron** [comment]
Potential fix if you do happen to update your cluster and it gets into a weird waffling state, try editing the cluster's k3sConfig k8s version back to what it was.

**Comment by hornbech** [comment]
My cluster is stuck in upgrading. 

Can I somehow revert it to the version that works? I'm guessing that it is persisted somewhere in the k3s cluster, but can't find it.
