### ISSUE TITLE
Etcd Not Applicable after update local k3s cluster

### ISSUE THREAD

**Issue by aleksey005** [rancher/rancher#29417]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** Update cluster in single node from 2.4.8 to 2.5.0 and update version Kubernetes to 1.19 in cluster "local" k3s.

**Result:** Cluster not update and cicle update state

**Other details that may be helpful:** this bad guys (( - Etcd Not Applicable

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.0
- Installation option (single install/HA): single bare metal

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal 12 CPU 12GB
- Kubernetes version (use `kubectl version`):

```
cluster not work
```

- Docker version (use `docker version`): 

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        

```

**Comment by jiaqiluo** [comment]
https://github.com/rancher/rancher/issues/29412

**Comment by aleksey005** [comment]
Please, close.
