### ISSUE TITLE
Cannot upgrade v2 Istio after deleting v2 Monitoring/CRDs

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#29418]
rancher/rancher:v2.5.0

* Install v2 Monitoring
* Install v2 Istio
* Install some other Prometheus for use with Istio 
```
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.7/samples/addons/prometheus.yaml
```
* Delete v2 Monitoring / CRDs
* Attempt to upgrade v2 Istio  to add the updated prometheus URLs to values YAML
* An error is shown in the UI that `rancher-monitoring is required to install this chart` 

*Workaround* 
* To workaround, install the monitoring CRDS (either by installing v2 monitoring and only deleting the monitoring app & leaving CRD chart, or installing only the CRD chart manually) -- v2 Istio can then be upgraded

*Other info*
* The required CRDs are present when Rancher is initially installed (without installing Monitoring) but they are deleted when v2 monitoring / CRDs are removed.

**Comment by cbron** [comment]
I think this is something that should be addressed in monitoring (and maybe Istio) docs. If user uninstalls the monitoring CRDs they are going to wipe out any prometheus instance in the cluster and Istio won't be upgradeable/installable.

**Comment by brendarearden** [comment]
I think this is the approach we are going to take 

**Current State:** The Rancher Istio chart requires the monitoring.coreos.com.prometheus/v1 crd to be installed prior to installing the istio chart.

**Problem:** A user can create a basic prometheus installation without using any Prometheus CRDs. There is also a problem where other charts might install this CRD but never install monitoring for istio so kiali would have issues or when other charts get uninstalled that delete this CRD. 

**Solution:** Remove this requirement, add a UI message on the Istio Overview page with the Kiali Dashboard link to remind users to ensure they have some form of monitoring installed for kiali to work correctly, and add more documentation around this. This will ensure if the crd is already installed somewhere the user would be aware of why their kiali graphs aren’t working and this will also allow any prometheus installation to be used, not just ones that use the crds

**Issues**
https://github.com/rancher/dashboard/issues/1646

**Comment by brendarearden** [comment]
After some additional discussion with @deniseschannon and @mantis-toboggan-md, the solution will change to: 

**Front End Solution:** Remove the warning from the ui, append a sentence in the existing Kiali Dashboard link description to remind users to ensure they have some form of monitoring installed if they want data. 

**Backend Solution:** Remove the crd requirement, add an app-readme to the istio chart that details the prometheus requirement for kiali, update the existing istio chart readme to make it more clear about the prometheus requirement for kiali, and add similar clarification to the docs.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 0390ff5

* Deploy Rancher
* Create a cluster
* Install and uninstall v2 Monitoring/CRD charts or delete one of the required CRDs (which is available on a fresh cluster)
```
kubectl delete crd servicemonitors.monitoring.coreos.com
```
* Attempt to install Istio - warning does not appear
* Install Istio with Kiali disabled, or install Prometheus before installing Istio
```
helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm install my-prometheus-operator stable/prometheus-operator
```
