### ISSUE TITLE
Clusters with AWS cloud provider enabled and using a VPC with private hosted zones (custom DNS) can't use cloud provider resources

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#29413]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- create a new windows custom cluster
- enable the AWS cloud provider
- try to join EC2 windows worker nodes in us-gov-west region to the cluster using the docker run command

**Result:**
attempts to add new windows ec2 worker nodes in us-gov-west region will fail

**Other details that may be helpful:**

If a custom cluster with live Windows nodes is switched from having no cloud provider to using the AWS cloud provider, the windows node will disappear from the cluster view and new ones cannot be added.

Linux only clusters in the us-gov-west function as expected when using the AWS cloud provider with a custom cluster

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom with AWS cloud provider enabled
- Kubernetes version (use `kubectl version`): tested both v1.17.4 and v1.18.6

gz#11752

**Comment by deniseschannon** [comment]
@rosskirkpat One thing to point out is that this use case is not supported (for windows or linux). If a user decides to "switch" to enable/disable cloud providers, then they need to start a new cluster with or without the cloud provider enabled.  

```
If a custom cluster with live Windows nodes is switched from having no cloud provider to using the AWS cloud provider,
```

From my understanding with @luthermonson, this is not how they are "switching" but I also wanted to clarify to ensure that they aren't doing it. My understanding is that they are actually starting new clusters with it enabled and still seeing this problem.

**Comment by sowmyav27** [comment]
**On 2.4.5**

- Deployed a 4 node windows cluster - 2 linux nodes - 1 etcd/control and 1 worker nodes, 2 windows worker nodes (from gov cloud )
- Enable cloud provider. (cluster k8s version: 1.18.10)
- Register the nodes.
- The cluster comes up
- Create a PV and attach it to a workload by creating a PVC.
- PV is attached successfully

**Comment by maggieliu** [comment]
When using DHCP Options Sets, only one domain name can be specified in the domain-name field. This is a requirement on the AWS side: https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html

**Comment by deniseschannon** [comment]
Note: This has been narrowed down that this is not only Windows cluster, but all cluster types.

**Comment by superseb** [comment]
Some issues to refer to for this issue: 
* https://github.com/kubernetes/kubernetes/issues/11543
* https://github.com/kubernetes/kubernetes/issues/61486

Based on this it seems like a years old problem that is not being actively worked on. It doesn't seem that the out-of-tree cloud provider for AWS has made changes around this.

@luthermonson @rosskirkpat Can you confirm this is accurate and I'm not mistaken the issue for something else?

**Comment by superseb** [comment]
According to @rosskirkpat , this is no longer an issue.
