### ISSUE TITLE
User Interface version is incorrect

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29415]
On 2.5.0-rc4:

- User Interface is seen as: vmaster-dev
<img width="560" alt="Screen Shot 2020-10-02 at 1 02 20 PM" src="https://user-images.githubusercontent.com/26032343/94965033-99241a00-04af-11eb-8a44-62c36fd46f31.png">

- On 2.4.8 - its 2.4.34
<img width="528" alt="Screen Shot 2020-10-02 at 12 54 12 PM" src="https://user-images.githubusercontent.com/26032343/94965073-a6410900-04af-11eb-8e37-aab7c3286eeb.png">

**Comment by westlywright** [comment]
This should be good to go on the 2.5 branch for this.

**Comment by sowmyav27** [comment]
**On 2.5.0 User Interface is seen as:**
<img width="593" alt="Screen Shot 2020-10-06 at 4 38 04 PM" src="https://user-images.githubusercontent.com/26032343/95359692-49629b80-087f-11eb-8ee4-f0b76958a2a1.png">
