### ISSUE TITLE
My Windows node cannot access a NodePort service

### ISSUE THREAD

**Issue by ranchersvet** [rancher/rancher#29411]
**What kind of request is this (question/bug/enhancement/feature request):**
/bug

**Steps to reproduce (least amount of steps as possible):**
Install a three-node Windows cluster.
Schedule one workload (pod) on one of the nodes and configure a nodeport.
The workload should be accessible via all nodes.

**Result:**
Delete the workload if it gets recreated on a different node the workload is now not accessible via some of the nodes, but accessible via other nodes.

**Other details that may be helpful:**
The issue is a bug in Microsoft windows os.

https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/common-problems#my-windows-node-cannot-access-a-nodeport-service

It is addressed in KB4571748 form 08/20/2020

https://support.microsoft.com/en-us/help/4571748/windows-10-update-kb4571748

After applying the update or update to a newer KB the problem is resolved.

gzrancher/rancher#11707

gzrancher/rancher#12213

**Comment by maggieliu** [comment]
waiting for confirmation that the provided patch fixed the issue or not.

**Comment by maggieliu** [comment]
@ranchersvet confirmed that this is resolved.
