### ISSUE TITLE
rancher-webhook fails to deploy in a local cluster of HA setup with k8s v1.16

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29420]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Bring up a HA cluster with local RKE cluster with k8s `v1.16.15-rancher1-2`
- rancher-webhook fails to deploy in local cluster
- Logs of helm-operation pod:

```
helm upgrade --history-max=5 --install=true --namespace=cattle-system --reset-values=true --timeout=5m0s --values=/home/shell/helm/values-rancher-webhook-0.1.0-beta500.yaml --version=0.1.0-beta500 --wait=true rancher-webhook /home/shell/helm/rancher-webhook-0.1.0-beta500.tgz
checking 5 resources for changes
Looks like there are no changes for ServiceAccount "rancher-webhook"
Looks like there are no changes for ClusterRoleBinding "rancher-webhook"
Looks like there are no changes for Service "rancher-webhook"
Looks like there are no changes for Deployment "rancher-webhook"
Error: UPGRADE FAILED: failed to create resource: ValidatingWebhookConfiguration.admissionregistration.k8s.io "rancher.cattle.io" is invalid: webhooks[0].admissionReviewVersions: Invalid value: []string{"v1"}: must include at least one of v1beta1
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.0
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): local RKE
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by zhcsyncer** [comment]
Is there a workaround now?

**Comment by dramich** [comment]
@zhcsyncer You can edit the `ValidatingWebhookConfiguration` by adding `v1beta1` to the  `admissionReviewVersions` as seen in the pull request: https://github.com/rancher/webhook/pull/10/files

`kubectl edit ValidatingWebhookConfiguration rancher.cattle.io`

**Comment by zhcsyncer** [comment]
> @zhcsyncer You can edit the `ValidatingWebhookConfiguration` by adding `v1beta1` to the `admissionReviewVersions` as seen in the pull request: https://github.com/rancher/webhook/pull/10/files
> 
> `kubectl edit ValidatingWebhookConfiguration rancher.cattle.io`

How? 

racher-webhook is deploy failed, There is no ValidatingWebhookConfiguration `rancher.cattle.io` in the cluster.

![image](https://user-images.githubusercontent.com/13214840/96153152-ec7e7980-0f3f-11eb-9b40-6118eb7cc076.png)

Maybe I can upgrade App `rancher-webhook`'s answers that used a latest image?

I also try to build, but failed...

**Comment by dramich** [comment]
Ah, yeah, I see. I cut a new release for the webhook so once that builds and propagates to the catalog you should be able to deploy it.

**Comment by zhcsyncer** [comment]
> Ah, yeah, I see. I cut a new release for the webhook so once that builds and propagates to the catalog you should be able to deploy it.

The above workaround seems a little bit error🤣, Should be update version of chart.

So, I just need to wait for available catalog version refreshed?

**Comment by sowmyav27** [comment]
charts PR: https://github.com/rancher/charts/pull/789

**Comment by StrongMonkey** [comment]
Available to test on master-head.
