### ISSUE TITLE
Logging to elasticsearch don't work

### ISSUE THREAD

**Issue by adrianovieira** [rancher/rancher#29423]
**What kind of request is this (question/bug/enhancement/feature request):**
Question/bug

**Steps to reproduce (least amount of steps as possible):**
I followed this https://rancher.com/docs/rancher/v2.x/en/logging/legacy/cluster-logging/elasticsearch, anyway:
- setup logging as Elasticsearch
- fill username and password to ship logs
- hit button ***Test***
- hit save button

**Result:**
***Test*** data is sent to elasticsearch, but real logs isn't shipped to elasticsearch.

**Other details that may be helpful:**
:man_shrugging: I'm not sure whatelse..

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted/custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, cpu: 8 cores, 16GB
- Kubernetes version (use `kubectl version`): 1.18.3

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by bmdepesa** [comment]
Hi @adrianovieira, 

What version of Rancher are you using? 

Did you configure your index properly when setting up ElasticSearch? 

https://www.elastic.co/guide/en/cloud/current/ec-configure-index-management.html

**Comment by adrianovieira** [comment]
Hi @bmdepesa,

Rancher: v2.4.5 

Yes! I did configure. And that ***TEST*** buttom of the Rancher UI appears to work (it sends "some data" to Elasticsearch).

But any new data arrive on our elasticsearch after that "TEST" check.

**Comment by izaac** [comment]
@adrianovieira could you provide the Elasticsearch version and if there are any errors shown in the logging operator pods?

**Comment by adrianovieira** [comment]
I'm ashamed!

I resqueted my operator team to check all setup again.

They told me that they filled UI form with the wrong user/pass to send logs to elasticsearc.

Now everything is working.

Thank you both by your attention.

**Comment by warthur1214** [comment]
i have this issue too
