### ISSUE TITLE
config.yaml not functional in rancherd

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#29422]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Install rancherd by setting values in config.yaml. For example:
```
curl -sfL https://get.rancher.io | sudo sh -

sudo mkdir -p /etc/rancher/rke2 && \
sudo vi /etc/rancher/rke2/config.yaml
# contents are:
write-kubeconfig-mode: 644

sudo systemctl enable rancherd-server.service && \
sudo systemctl start rancherd-server.service

export KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin && \
alias k=kubectl

k get nodes
# error: error loading config file "/etc/rancher/rke2/rke2.yaml": open /etc/rancher/rke2/rke2.yaml: permission denied
```

**Result:**
rancherd is not using the values in config.yaml, forcing users to install it via the binary if wanting to use non-default options.

**Other details that may be helpful:**
pure rke2 is functioning correctly.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.0

**Comment by StrongMonkey** [comment]
Backported in https://github.com/rancher/rancher/pull/29581, available to test in the next rc.

**Comment by mrajashree** [comment]
Can be tested with v2.5.2-rc1

**Comment by rancher-max** [comment]
#### Validated in v2.5.2-rc1

- Scenario mentioned in the issue description is working now
- Am able to join server and agent nodes using config.yaml
