### ISSUE TITLE
Rancher 2.4.8 Memory Leak

### ISSUE THREAD

**Issue by thecrazyrussian** [rancher/rancher#29429]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Currently, the issue exists in 1 production cluster somewhat replicated to a test cluster.
We have around ~60 downstream clusters that are often disconnected. We have many catalog apps but so does our test environment which does not have these issues. 

**Result:**
After running for a couple of days, the pods continue to use more memory until they exhaust all of the nodes' memory and cause a node crash.

This is a grafana time-laps of the events, note the continuous increase in memory consumption.
![Rancher Pod Memory 2](https://user-images.githubusercontent.com/3221320/95366567-3957b580-0899-11eb-997a-d836542d218e.jpg)
![Rancher Pod Memory 1](https://user-images.githubusercontent.com/3221320/95366573-39f04c00-0899-11eb-9439-c31db19049c1.jpg)

**Mitigation**
To prevent the nodes from crashing, we set a limit on the rancher pods that would prevent them from bringing down the cluster at 6Gig per pod. That has allowed the pod to crash and restart without taking the node down.

**Other details that may be helpful:**
We saw a couple of other issues related to memory leaks that might be relevant since we also use azure ad and catalogs.

**Environment information**
2 x k3s,4cpu 16gb nodes in Azure
Rancher 2.4.8
Hosted MySQL
Azure AD Rbac

There is already a disconnected cluster issue from last year.
https://github.com/rancher/rancher/issues/24204 (open)

As well as 2 other open leak Issues that may not be related but since we use both Azure AD and catalogs, it is worth looking into. 
https://github.com/rancher/rancher/issues/29055 (azure ad - open)
https://github.com/rancher/rancher/issues/22949 (catalog - open)

gz#13272

**Comment by dramich** [comment]
To test, create a rancher setup, enable monitoring and add clusters to it. I used 15 but the more you have the fast you can see the leak. Then, delete both agent deployments/daemonsets from the downstream clusters. This will cause rancher to try and reconnect to the clusters in a loop. If done properly the logs should show `Stopping cluster agent for <ID>` every two minutes which is expected and how the leak is reproduced. 

```
kubectl delete deployment -n cattle-system cattle-cluster-agent &&
kubectl delete daemonsets.apps -n cattle-system cattle-node-agent
```

**Comment by sowmyav27** [comment]
A panic issue seen on 2.4.11 - https://github.com/rancher/rancher/issues/30220

**Comment by bmdepesa** [comment]
Reopening until https://github.com/rancher/rancher/pull/30379 is merged

**Comment by bmdepesa** [comment]
Reproduced in Rancher v2.4.8
* RKE cluster, Rancher installed via Helm with `replicas=1` and monitoring enabled on the local cluster
* Create 30 imported clusters
  * In this case, imported the same cluster repeatedly as it updates the agents in the cluster
* Delete the agents deployment/ds from the `cattle-system` ns on each cluster
* In the logs, see `Stopping cluster agent ...` every 2 minutes
* Memory usage for the `rancher` pod increases over many hours. In this case, starting around 300mb usage, it eventually increased to 1.2gb at its peak

rancher/rancher:v2.5.4-rc6
rancher/rancher:master-head 4297ee1
* Use the [scaling framework](https://github.com/rancher/rancher2-scaling) to provision a k3s cluster with Rancher installed via Helm, `replicas=1`, and local monitoring enabled
* Use the scaling framework to create and import 30 k3s clusters
* Delete the agents deployment/ds from the `cattle-system` ns in each cluster
* Every 2 minutes, `Stopping cluster agent ...` appeared in logs
  * Sometimes the `Rancher` pod may need to be restarted for the controllers to begin looping - this is unclear why
* Over the course of 12 hours, memory usage was avg 306mb, with a peak of 321mb
  * The grafana image below shows a few instances where the monitoring workloads restarted, but this is unrelated to the `rancher` pods
  
  
<img width="1965" alt="Screen Shot 2020-12-19 at 9 30 21 AM" src="https://user-images.githubusercontent.com/21316915/102694427-36a10700-41de-11eb-8638-0b09d318ddfe.png">
