### ISSUE TITLE
[Rancher v2.5] Alert: Component controller-manager,scheduler  is unhealthy.

### ISSUE THREAD

**Issue by jniltinho** [rancher/rancher#29427]
**Kubernetes 1.19.2**

- Alert: Component controller-manager is unhealthy.
- Alert: Component scheduler is unhealthy.

![rancher-error-kubernetes19](https://user-images.githubusercontent.com/1027494/95358851-e2a1aa00-089f-11eb-8fdc-439b4bb34e32.png)

**Cluster information**
- Cluster type (Imported):
- Machine type (metal):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Thu Jun 18 08:26:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

**Comment by mitchellmaler** [comment]
@jniltinho Unfortunately this is due to deprecation of the insecure ports of the kube control plane components and it defaulting to the secure ports. Rancher uses component-status to get those statuses which is also deprecated and only uses the insecure ports. You can check this issue out where others have had the same problem https://github.com/rancher/rancher/issues/11496

**Comment by jniltinho** [comment]
**Fix Error**

```
##master
sed -i 's|- --port=0|#- --port=0|' /etc/kubernetes/manifests/kube-scheduler.yaml
sed -i 's|- --port=0|#- --port=0|' /etc/kubernetes/manifests/kube-controller-manager.yaml

##master and all worker
systemctl restart kubelet
```

**Comment by mitchellmaler** [comment]
That does fix it but --port is deprecated and will be removed in a later version. That also makes the controller-manager and scheduler run on the insecure port which is not best practice.

```The port on which to serve unsecured, unauthenticated access. Set to 0 to disable. (default 10252) (DEPRECATED: see --secure-port instead.)```

**Comment by superseb** [comment]
Closing for https://github.com/rancher/rancher/issues/11496
