### ISSUE TITLE
image rancher/rancher-agent:v2.5.0

### ISSUE THREAD

**Issue by gloubix** [rancher/rancher#29424]
Hi !

Trying to pull docker pull rancher/rancher-agent:v2.5.0

but seems corrupted :-/

docker pull rancher/rancher-agent:v2.5.0
v2.5.0: Pulling from rancher/rancher-agent
171857c49d0f: Already exists
419640447d26: Already exists
61e52f862619: Already exists
8337e8208979: Pulling fs layer
167454f0e957: Pulling fs layer
151cee340873: Pulling fs layer
b3d5a16b3068: Waiting
2fb5152e9c94: Waiting
b4ba41728bf5: Waiting
0f7d6bdd0d2a: Waiting
error pulling image configuration: unknown blob

Happen on any machine (linux)

**Comment by patsch9** [comment]
same problem

**Comment by bashofmann** [comment]
I can reproduce the same on a Mac with Docker for Desktop 2.4.10 with engine 19.03.13.

**Comment by vincent99** [comment]
We are looking into this but it's the middle of the night where most employees are.  It worked yesterday when it was pushed and seems to have spontaneously broken on DockerHub without change.

**Comment by vincent99** [comment]
I don't know what caused it but the rc9 image still works and is the same commit as the final 2.5.0 so I pulled/tagged/pushed it and it's working again.

```
mercury:~ vincent$ docker pull rancher/rancher-agent:v2.5.0-rc9
v2.5.0-rc9: Pulling from rancher/rancher-agent
171857c49d0f: Already exists
419640447d26: Already exists
61e52f862619: Already exists
d2660c701716: Pull complete
2ca890213e14: Pull complete
151cee340873: Pull complete
4cf6c654dc9d: Pull complete
b39e08485db7: Pull complete
1992d6134193: Pull complete
4b478dc7850b: Pull complete
Digest: sha256:c76cbbc1b820adff497d86516f9114227eb13991e13deb888ca1f272fe50944b
Status: Downloaded newer image for rancher/rancher-agent:v2.5.0-rc9
docker.io/rancher/rancher-agent:v2.5.0-rc9
mercury:~ vincent$ docker tag rancher/rancher-agent:v2.5.0-rc9 rancher/rancher-agent:v2.5.0
mercury:~ vincent$ docker push rancher/rancher-agent:v2.5.0
The push refers to repository [docker.io/rancher/rancher-agent]
86992b8b564f: Layer already exists
5d1552920303: Layer already exists
df6881b27b79: Layer already exists
d64b2e06d38a: Layer already exists
beba24fe4b52: Layer already exists
b08e316274b9: Layer already exists
e1e344519b78: Layer already exists
7a694df0ad6c: Layer already exists
3fd9df553184: Layer already exists
805802706667: Layer already exists
v2.5.0: digest: sha256:f500c70b159aa7f8b5f73d740cbf24095ef7478dffea0e59815ee85305523565 size: 2416
```

**Comment by jsiebens** [comment]
when running rancher/rancher-agent:v2.5.0 on arm64 I've got the following error:

```
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by cjellick** [comment]
Hm. Something very strange is going on.
We found this just yesterday afternoon on another image https://twitter.com/dweomer/status/1313595511035711488?s=21

**Comment by cjellick** [comment]
@jsiebens and others experiencing **arm64 problems** - The bandaid we applied to fix this was a quick and simple pull, retag, push. This dropped all architectures other than amd64.

We will get this fixe today. I suspect within the next 6 hours.

**Comment by justincormack** [comment]
"standard_init_linux.go:211: exec user process caused "exec format error"" means there is no image for arm64 architecture.

**Comment by justincormack** [comment]
How are you pushing these multiarch images?

**Comment by cjellick** [comment]
@justincormack the arm64 thing is caused by the bandaid that one of our engineers did in the middle of the night. He just pulled our most recent RC, tagged, and pushed. This was to stop the bleeding and we new it would drop all architectures other than linux/amd64.

So, the rancher/rancher-agent:v2.5.0 image is not a good one to investigate right now.

`rancher/klipper-helm:v0.3.1` was the other corrupted image and that was republished through our build pipeline, so it has proper multi-arch.

**Comment by justincormack** [comment]
Ok but you repushed rancher/klipper-helm:v0.3.1 so I cant see what was broken (we do not keep deleted content on Hub so I can't see what you pushed before).

Where is the code that pushes these multi arch images?

**Comment by cjellick** [comment]
yep, stand by. getting that

**Comment by cjellick** [comment]
Deeply appreciate you looking at this. I am working through our images to see if i can find another experienceing the problem.

I also attempt to dig up the the drone plugin code

**Comment by justincormack** [comment]
Yeah the plugin code for plugins/manifest:1.0.2 would be useful

**Comment by cjellick** [comment]
https://github.com/drone-plugins/drone-manifest/tree/v1.0.2

**Comment by cjellick** [comment]
Note that these broken images were validated to work after being pushed and then some amount of time later stopped working.

**Comment by justincormack** [comment]
How do you validate them?

**Comment by cjellick** [comment]
I just mean we ran them after the fact. Like after 2.5.0 was published, we ran rancher such that rancher/rancher-agent:v2.5.0 was pulled and launched successfully.

**Comment by justincormack** [comment]
Yeah I just was wondering which architectures you tested....

**Comment by justincormack** [comment]
the manifest plugin and config looks sane at first glance

**Comment by justincormack** [comment]
(also I guess, did you pull and test on a different machine that had no cache?)

**Comment by cjellick** [comment]
Completely empty cache, like no docker image layers whatsoever? I cannot garauntee that. I'll have to ask around.

**Comment by cjellick** [comment]
We have a still-broken one @justincormack :
ranchr/rancher-agent:v2.5.0-alpha5

https://hub.docker.com/layers/rancher/rancher-agent/v2.5.0-alpha5/images/sha256-e82ba1cd0bdd512a7d25b993b66c688ba7ae7e2c30a44314ebe111a15b36c45c?context=repo

**Comment by justincormack** [comment]
so long as its not the build amchine should be meaningful. Thanks

**Comment by dweomer** [comment]
@cjellick asked me to post similar issues that I noticed via googling yesterday (limited to one month out):
- https://github.com/argoproj/argo/issues/4216
- https://github.com/minio/minio/issues/10629
-

**Comment by justincormack** [comment]
Thanks. If you see any more on your repos can you let me know here.

**Comment by justincormack** [comment]
@cjellick do you know when  rancher/rancher-agent:v2.5.0 was first created?

**Comment by cbron** [comment]
That image was created at 2020-10-05 10:30 PST, give or take a few minutes. It existed right afterwards as we run some smoke tests after we release, and that was confirmed by a few people.

**Comment by cbron** [comment]
I actually have the logs in my console history from when I generated the image sha's a few minutes after the release: 

```
v2.5.0: Pulling from rancher/rancher-agent
171857c49d0f: Already exists
419640447d26: Already exists
61e52f862619: Already exists
8337e8208979: Pull complete
167454f0e957: Pull complete
151cee340873: Pull complete
b3d5a16b3068: Pull complete
2fb5152e9c94: Pull complete
b4ba41728bf5: Pull complete
0f7d6bdd0d2a: Pull complete
Digest: sha256:51799b2c2f72d7276f9902692b74eb555f41b9611f00ca99aaf481d43c906127
Status: Downloaded newer image for rancher/rancher-agent:v2.5.0
```

**Comment by brandond** [comment]
The odd thing is that it's always the config blob that disappears. To date it's also always been for amd64, but that's the most common client arch so it could be happening on others and we just haven't noticed it due to decreased usage.

**Comment by brandond** [comment]
Found another one with missing config blob - this one on arm64: `rancher/coreos-flannel:v0.13.0-rancher1`

**Comment by sowmyav27** [comment]
**Found issues on 2.5.0 for the following:**

- rancher-agent
- Flannel - `coreos-flannel:v0.13.0-rancher1` while deploying an ARM64  1.19.2 k8s cluster and windows cluster

**Verified on 2.5.1-rc1**
- Deployed a windows 1.19 cluster
- Deployed an arm64 1.19 cluster
- Rancher-agent works fine.
