### ISSUE TITLE
[UI] Catalog service not loading properly

### ISSUE THREAD

**Issue by lkoenigsberger** [rancher/rancher#2943]
Rancher	v0.49.0
Cattle	v0.119.0
User Interface	v0.70.0
Rancher Compose	v0.6.0

I get the following error:
```
Mixed Content: The page at 'https://rancher-server/apps/catalog/library:elasticsearch' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://rancher-server/v1-catalog/templates/library:elasticsearch:1'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by lkoenigsberger** [comment]
Also the Catalog Images at the catalog page give this warning:
```
Mixed Content: The page at 'https://rancher-mgmt.konetserv.io/apps/catalog' was loaded over HTTPS, but requested an insecure image 'http://rancher-mgmt.konetserv.io/v1-catalog/templates/library:sysdig-cloud?image'. This content should also be served over HTTPS.
```

**Comment by antmanler** [comment]
+1

and kubernetes tab is missing...

**Comment by kaos** [comment]
+1
![screen shot 2015-12-08 at 10 45 46](https://cloud.githubusercontent.com/assets/72965/11652624/06dcf162-9d99-11e5-9ee0-29c2fa066813.png)

**Comment by vincent99** [comment]
k8s is unrelated to this but also fixed in the next build.

**Comment by sangeethah** [comment]
Reopening to test .

**Comment by sangeethah** [comment]
Tested with rancher-server version - v0.49.1-rc2

Set up - Rancher server rancher-server with SSL behind Nginx container as https reverse proxy.
Able to list the catalog and create stack using "Elastic Search" template.
