### ISSUE TITLE
How to disable the local cluster in Rancher v2.5?

### ISSUE THREAD

**Issue by jniltinho** [rancher/rancher#29439]
How to disable the local cluster in Rancher v2.5?

In Rancher v2.5 every time you run the docker image it creates a local cluster, as I do so it doesn't create a local cluster, I would like to have the behavior of Rancher v.2.4.8.

Disable/Delete local cluster

**Comment by superseb** [comment]
From https://github.com/rancher/rancher/releases/tag/v2.5.0:

```
The local cluster can no longer be turned off, which means all admins will have access to the local cluster. If you would like to restrict permissions to the local cluster, there is a new restricted-admin role that must be used.
```
