### ISSUE TITLE
Cannot proceed with upgrade of controlplane since 1 host(s) cannot be reached prior to upgrade

### ISSUE THREAD

**Issue by angeloudy** [rancher/rancher#29449]
I am running rancher 2.4.3.
I created my kubernetes clusters on AWS with `Custom` EC2 instances in terraform rancher2 provider2.
Then I tried update my kubernetes cluster with `aws_cloud_provider` option in order to use persistent volume and the cluster became unavailable. I tried various things including restart the controller one by one, restore the cluster from snapshot.
Eventually I ended up with two working controller nodes and the kubernetes cluster came back.
And then I tried to get the third(actually the first one broken) controller node working. 
I tried with following commands on the ec2 node:
```
sudo docker kill $(docker ps -qa)
sudo docker rm $(docker ps -qa)

sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.4.3 --server https://rancher.xxx.xxx --token fvwn25nckllxbjjrgnz7p5q5d6tqj89q567lhttdf5f6mktb6x2dch4 --etcd --worker --controlplane

```
After this, the third controller joined the cluster, but the cluster stills shows `etcd-0 unhealthy`
I went to the node and checked the logs from etcd container and got something like this
```
rafthttp: request cluster ID mismatch
```

Then I delete the controller node from the UI and launched a new ec2 instance and ran 
```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.4.3 --server https://rancher.xxx.xxx --token fvwn25nckllxbjjrgnz7p5q5d6tqj89q567lhttdf5f6mktb6x2dch4 --etcd --worker --controlplane
```

And this time I got the error in the title and the new node stuck at `Registering` state.

**Comment by angeloudy** [comment]
And later on it shows another error ```Failed to reconcile etcd plane: Failed to add etcd member [etcd-ip-172-31-1-36] to etcd cluster```

**Comment by angeloudy** [comment]
The issue was fixed by deleting the corrupted etcd member.
```
docker exec etcdctl member remove memberId
```

**Comment by ac0592** [comment]
I meet thr problem,but wait half hour,it be ok.

**Comment by EtachGu** [comment]
mybe  ssh not work, you should set the auhtorized_keys in host1
