### ISSUE TITLE
Since Upgrade 2.4.8 to 2.5.0 Calico node X.X.X.41'' is already using the IPv4 address 10.43.0.1.

### ISSUE THREAD

**Issue by lucky4ever2** [rancher/rancher#29441]
Yesterday I had upgrade Rancher 2.4.8 to 2.5.0.
Since then the workload Canal has the status "Upgrading workload"
1 of 3 pods is running. The other two in "Unavailable". In the log there is an "Unavailable" Pod: 

```
2020-10-08 13:57:16.586 [INFO][9] startup/startup.go 361: Early log level set to info

2020-10-08 13:57:16.586 [INFO][9] startup/startup.go 377: Using NODENAME environment for node name

2020-10-08 13:57:16.586 [INFO][9] startup/startup.go 389: Determined node name: X.X.X.40

2020-10-08 13:57:16.587 [INFO][9] startup/startup.go 421: Checking datastore connection

2020-10-08 13:57:16.596 [INFO][9] startup/startup.go 445: Datastore connection verified

2020-10-08 13:57:16.596 [INFO][9] startup/startup.go 109: Datastore is ready

2020-10-08 13:57:16.623 [INFO][9] startup/startup.go 746: Using autodetected IPv4 address on interface br-91df7d8e38eb: 10.43.0.1/16

2020-10-08 13:57:16.623 [INFO][9] startup/startup.go 563: Node IPv4 changed, will check for conflicts

2020-10-08 13:57:16.629 [WARNING][9] startup/startup.go 1106: Calico node 'X.X.X.41' is already using the IPv4 address 10.43.0.1.

2020-10-08 13:57:16.630 [WARNING][9] startup/startup.go 1310: Terminating

Calico node failed to start
```

I also upgraded to Rancher 2.5.1 today and I had restart all Pods, but this did not work

**What kind of request is this (question/bug/enhancement/feature request):**

question/bug?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.5.1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 
- Kubernetes version (use `kubectl version`): 1.19.2

- Docker version (use `docker version`): 19.3.13

**Comment by superseb** [comment]
Can you provide more info on your initial setup (Rancher v2.4.8 but what k8s version was the cluster before you went to 1.19.2)? You entered `Imported` as cluster type but I assume its custom? The more information you can provide on your setup (type of nodes/OS/Docker), what is different on the node that has the pod running vs unavailable?

**Comment by lucky4ever2** [comment]
I set up the cluster like this:
nodes:
   - address: X.X.X.39
     user: admin
     role: [controlplane, worker, etcd]
   - address: X.X.X.40
     user: admin
     role: [controlplane, worker, etcd]
   - address: X.X.X.41
     user: admin
     role: [controlplane, worker, etcd]

services:
   etcd:
     snapshot: true
     creation: 6h
     retention: 24

# Required for external TLS termination with
# ingress-nginx v0.22 +
ingress:
   provider: nginx
   options:
     use-forwarded-headers: "true"

The cluser was set up with an earlier version of Rancher. I think it was 2.4.X.

The nodes are all configured the same

When I updated to Rancher 2.5.0, I first updated RKE to version 1.2.0.

**Comment by superseb** [comment]
Ok this seems to be an RKE issue. Please supply what RKE version you used before upgrading to 1.2.0 and what k8s version the cluster was before upgrading it.

**Comment by lucky4ever2** [comment]
RKE Version 1.1.7
k8s: 1.18.8

**Comment by tabnul** [comment]
try this:
kubectl set env daemonset/canal -n kube-system IP_AUTODETECTION_METHOD=can-reach=10.100.1.5

where 10.100.1.5 should be an ip adress preferable in your LAN that can be used as a valid destination to select the right NIC to listen on.

Quite sure its a bug in either rancher or RKE but this is a workaround for the time being.

**Comment by superseb** [comment]
@lucky4ever2 can you share the output of `ip addr show` and/or `ifconfig` from the nodes?

**Comment by Oats87** [comment]
@lucky4ever2 @tabnul Do you have a docker bridge network created on your hosts?

**Comment by Oats87** [comment]
After creating a docker bridge network like:
```
docker network create -d bridge test
```
and then registering that node with my cluster, I get logs similar to the original issue:
```
2020-10-22 01:49:27.526 [INFO][8] startup/startup.go 361: Early log level set to info
2020-10-22 01:49:27.527 [INFO][8] startup/startup.go 377: Using NODENAME environment for node name
2020-10-22 01:49:27.527 [INFO][8] startup/startup.go 389: Determined node name: ck-centos7-1
2020-10-22 01:49:27.532 [INFO][8] startup/startup.go 421: Checking datastore connection
2020-10-22 01:49:27.560 [INFO][8] startup/startup.go 445: Datastore connection verified
2020-10-22 01:49:27.560 [INFO][8] startup/startup.go 109: Datastore is ready
2020-10-22 01:49:27.616 [INFO][8] startup/startup.go 746: Using autodetected IPv4 address on interface br-aee575964855: 172.18.0.1/16
```

This is on K8s `1.19.3` on `2.5.2-rc1`

**Comment by Oats87** [comment]
Looks like Calico changed behavior from `v3.13.4` to `v3.16.0`. In the 3.13.x series Calico did not run the auto-detect logic if `CALICO_NETWORKING_BACKEND` was `none`, but now it runs regardless of that environment variable setting.

I would recommend not having a docker bridge configured on your nodes as a more proper fix, setting an environment variable on the Canal/Calico manifests will be overwritten by RKE on the next corresponding `rke up`.

**Comment by tabnul** [comment]
> @lucky4ever2 @tabnul Do you have a docker bridge network created on your hosts?

Not that i know of, at least its an OOTB docker installation, i do however have a docker image of node-exporter running on the masters which might have changed something.

**Comment by Oats87** [comment]
@tabnul Can you provide the output of both `ip addr show` as well as `docker network ls`?

**Comment by tabnul** [comment]
from one of the affectec master hosts:

**ip addr show**
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fe:ef:50:97:3a:85 brd ff:ff:ff:ff:ff:ff
    inet 10.100.1.242/24 brd 10.100.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::fcef:50ff:fe97:3a85/64 scope link
       valid_lft forever preferred_lft forever
3: br-a6d86c0b6dc1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:92:63:d0:bb brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-a6d86c0b6dc1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:92ff:fe63:d0bb/64 scope link
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:a4:93:7e:53 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
6: veth3ac6b32@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-a6d86c0b6dc1 state UP group default
    link/ether 52:4c:c5:fa:99:b6 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::504c:c5ff:fefa:99b6/64 scope link
       valid_lft forever preferred_lft forever
7: caliae6bf11809a@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
8: cali03389e6f61e@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
9: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether c2:65:55:cd:55:48 brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.0/32 brd 10.42.0.0 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::c065:55ff:fecd:5548/64 scope link
       valid_lft forever preferred_lft forever
```


**docker network ls**
```
NETWORK ID          NAME                    DRIVER              SCOPE
328a975621a3        bridge                  bridge              local
a6d86c0b6dc1        dockercompose_default   bridge              local
f13e6458dcfc        host                    host                local
35c242b23b40        none                    null                local
```

**Comment by Oats87** [comment]
@tabnul the `dockercompose_default` network is your problem. Did you set up your node exporter by using `docker-compose`?

**Comment by tabnul** [comment]
> @tabnul Can you provide the output of both `ip addr show` as well as `docker network ls`?


> @tabnul the `dockercompose_default` network is your problem. Did you set up your node exporter by using `docker-compose`?

Hi, yes it is. 
So it seems the new behavior of calico interferes with this .
scenario.

**Comment by lucky4ever2** [comment]
>
>
> @lucky4ever2 can you share the output of `ip addr show` and/or `ifconfig` from the nodes?

ip addr show  (public ip replaced by X)
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:X:X:X:X:02 brd ff:ff:ff:ff:ff:ff
    inet X.X.X.39/24 brd X.X.X.255 scope global dynamic eth0
       valid_lft 5347sec preferred_lft 5347sec
    inet6 fe80::215:X:X:X/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:X:X:X:X:03 brd ff:ff:ff:ff:ff:ff
    inet 192.168.123.11/22 brd 192.168.123.255 scope global dynamic eth1
       valid_lft 343sec preferred_lft 343sec
    inet6 fe80::215:X:X:X/64 scope link
       valid_lft forever preferred_lft forever
4: br-91df7d8e38eb: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:9b:dd:b4:9b brd ff:ff:ff:ff:ff:ff
    inet 10.43.0.1/16 brd 10.43.255.255 scope global br-91df7d8e38eb
       valid_lft forever preferred_lft forever
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:f7:d1:8f:56 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:f7ff:fed1:8f56/64 scope link
       valid_lft forever preferred_lft forever
6: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 46:4a:c7:ab:6f:fc brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.0/32 brd 10.42.0.0 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::444a:c7ff:feab:6ffc/64 scope link
       valid_lft forever preferred_lft forever
12: calia433078af39@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
13: cali0d88aad0bcb@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
15: califeac733e094@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
16: cali174d431c733@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
`




> 
> 
> @lucky4ever2 @tabnul Do you have a docker bridge network created on your hosts?

Yes with: `sudo docker network create --driver=bridge --subnet=10.43.0.0/16 br0_rke`

**Comment by Oats87** [comment]
@lucky4ever2 What is the purpose of your `br0_rke` bridge network?

**Comment by Oats87** [comment]
@lucky4ever2 I’m guessing that the reason you’ve created a `br0_rke` network is due to: https://github.com/rancher/rke/issues/1231

If this is the case, you should not need this `br0_rke` network if you have a default route on your host.

**Comment by lucky4ever2** [comment]
Yes, thats right. What can i do? Can I remove the Bridge?

**Comment by lucky4ever2** [comment]
Today i deleted the br0_rke from all nodes. That is the solution! Now all canal pods have the status "Running".
