### ISSUE TITLE
[rancher/charts] PRs to dev branch should ensure that packageVersion is updated

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29446]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

In the current scripts, a chart owner who pushes changes to `<branch>-source` without updating the `packageVersion` will update the contents of `<branch>` in place; as a result, making changes to `main-source` without updating the package version could cause impacts to existing charts currently stored in `main` tied to an earlier release.

Therefore, when making changes to a branch like `dev-v2.5-source` (that will later be cherry-picked into `main-v2.5-source`) via a PR, we should take one of the two following steps:
- Add a PR checklist (similar to rancher/image-mirror [here](https://github.com/rancher/image-mirror/pull/42)): this PR checklist should remind chart owners and reviewers to ensure that the packageVersion is different than the one currently found in the main branch to ensure that, when changes are ported over to main-source, they don't accidentally overwrite main.
- Modify Github PR workflow: fail if the tgz file generated by `make charts` for packages that were modified in this pull request already exists in the `main` branch.

Should also be addressed in https://github.com/rancher/rancher/issues/28730 for the rewrite.

**Comment by aiyengar2** [comment]
@cbron @deniseschannon can we add in the PR checklist for now since that should be an easy fix to get in?

**Comment by cbron** [comment]
Can you add that in, its just a file https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template

**Comment by aiyengar2** [comment]
As mentioned in https://github.com/rancher/charts/pull/783#issuecomment-726978704, this will be addressed in https://github.com/rancher/rancher/issues/28730 instead since the PR checklist approach doesn't work for a non-default branch like `dev-v2.5-source`.
