### ISSUE TITLE
Intermittent connectivity problems between containers

### ISSUE THREAD

**Issue by danvanwijk** [rancher/rancher#2944]
Running v0.47 with around 60 hosts (ubuntu 14.04).

The problem:
1. Service A with 12 containers is linked to Service B with 6 containers, running on different host machines. (service-b:service-b-link-name)
2. They communicate using Ranchers managed network.
3. Service A perform a GET to "service-b-link-name" hostname, which picks one of the 6 IPs returned from the DNS server.
4. This is where the problem starts. The GET times out since it can't connect to the IP for some reason. Trying the same IP from another container (on another host) in Service A works fine, so it's not a problem with the actual container in Service B.
5. Wait 5-60 mins or some undefined period of time and the same IP will start to work again.

So, for some reason our hosts are randomly failing to communicate with eachother using Ranchers managed network. Any guidelines on how to fix this? I'm unsure if it happened after our upgrade from 0.46 to 0.47. During the upgrade we also updated some hosts to Docker 1.9.1 and added new hosts as well. Hard to pinpoint what the actual cause might be.

**Comment by danvanwijk** [comment]
Changed about 100 containers (50 in once service, 50 in another) to use host network instead of Ranchers managed. It seems to have been working since. Can't say if it's coincidence or not.

Can the number of containers in the managed network affect the stability/performance?

**Comment by Rucknar** [comment]
@danvanwijk I've used many more than that on a managed network without issue. 
Might be worth running a ping from one network agent to a network agent on another host, try see if host to host traffic across the IPSEC tunnel is stable.

**Comment by danvanwijk** [comment]
Thanks for your input. Do you know what factors in Rancher can affect the stability on the tunnel?

**Comment by jwhitcraft** [comment]
I'm seeing this same problem, were i have 5 hosts with about 250 to 300 containers and some of the hosts can ping containers on other hosts, but some hosts can not ping containers on other hosts.

**Comment by sangeethah** [comment]
With rancher-server version - v0.56.0 , we updating ipsec to use charon instead of racoon.
If you still see issues with this version, please log a new issue to track it.
