### ISSUE TITLE
[Monitoring V2] Switch to using a single PushProx for k3s by default

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29445]
Related Issues: https://github.com/rancher/rancher/issues/28787, https://github.com/rancher/k3s/issues/2262

Since `kube-proxy`, `kube-controller-manager`, and `kube-scheduler` are all emitting the same metrics from k3s, the Monitoring chart is [advised](https://github.com/rancher/k3s/issues/2262#issuecomment-705652249) to switch to just monitoring the `kube-proxy` port with a single PushProx deployment that scrapes the component `k3s-server` instead.

On testing this, we'll need to ensure the following:
1. Metrics can still be scraped as expected
2. Grafana Dashboards based on metrics that are collected here are not impacted
3. PrometheusRules on metrics that are collected here are not impacted (need to simulate an issue and ensure that an alarm is triggered on the Prometheus UI)

We'll also need to identify if the original default memory metrics are fine so we can rollback the increase memory limits / requests in k3s that were based on https://github.com/rancher/rancher/issues/28787#issuecomment-693611821.

**Comment by cjellick** [comment]
👍

**Comment by jiaqiluo** [comment]
this enhancement is validated on rancher:`v2.5-daf8ccef73e08ae6b041ebd642b0686176f80e18-head` single install

Steps:
- import a k3s cluster with version `v1.18.9+k3s1`, 1 master, 2 workers
- enable monitoring v2 chart `9.4.200` in the cluster 
- confirm that monitoring works 
- upgrade the monitoring to chart `9.4.201`, and need to set `k3sServer.enabled` to `true` manually 
<img width="1592" alt="Screen Shot 2020-10-15 at 5 28 37 PM" src="https://user-images.githubusercontent.com/6218999/96200477-d86e5400-0f0e-11eb-814c-b01ef009f7a2.png">

- confirm the monitoring is ugprade, and all component continue works
- in Gerafana, the dashboard for proxy, controller, and kube scheduler still get and show new data  
- in Promethes, the targets for proxy, controller, and kube scheduler are still active 
<img width="909" alt="Screen Shot 2020-10-15 at 5 12 55 PM" src="https://user-images.githubusercontent.com/6218999/96200641-40bd3580-0f0f-11eb-9b7f-b36febf37839.png">

- pushbox for kube-proxy, kube-controller, and kube-scheduler are removed, instead, pushbox for k3s sever is deployed 

before:
<img width="1390" alt="Screen Shot 2020-10-15 at 5 33 25 PM" src="https://user-images.githubusercontent.com/6218999/96200371-97763f80-0f0e-11eb-8106-abd99aeac317.png">

after:
<img width="1405" alt="Screen Shot 2020-10-15 at 5 33 42 PM" src="https://user-images.githubusercontent.com/6218999/96200688-5c284080-0f0f-11eb-91f3-886e6a973436.png">
