### ISSUE TITLE
[2.4] Update k8s versions-10/14

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#29459]
Backport https://github.com/rancher/rancher/issues/29373

Expected versions for 2.4
1.17.13
1.18.10

**Comment by aaronRancher** [comment]
Observed new versions for 2.4:
Pointing KDM to dev-v2.4:
![Screen Shot 2020-10-15 at 1 51 38 PM](https://user-images.githubusercontent.com/57409052/96185008-1f981d00-0eee-11eb-94df-36856b28e940.png)

Ran upgrade testing on Rancher `v2.4.8`:
Provisioned clusters with each k8s version on each network provider
Ran automation
Updated KDM to dev-v2.4
Upgraded k8s version on clusters
Ran automation

**Comment by bmdepesa** [comment]
rancher/rancher:v2.4.8
* Fresh installs for `v1.18.10-rancher1-1`, `v1.17.13-rancher1-1` for all network providers - automation pass
* Fresh install for `v1.18.10-rancher1-1` on ARM64 - automation pass
* Fresh install for `v1.17.13-rancher1-1`, `v1.18.10-rancher1-1` on Windows w/ Flannel - automation pass
--
* Fresh install for `v1.17.13-rancher1-1` on ARM64 fails - #29556 

rancher/rancher:v2.4.4
* Fresh install for `v1.17.13-rancher1-1` - automation pass
* `v1.18.10-rancher1-1` is correctly not present

rancher/rancher:v2.4.5
* Fresh install for `v1.18.10-rancher1-1` - automation pass
* `v1.17.13-rancher1-1` is also present
