### ISSUE TITLE
[Bug] Annotations of projects are not reflected on namespaces within

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#29452]
I noticed this way earlier, but finally coming here and opening this ticket.

When you set an annotation on a project the expectation is that rancher copies that to all namespaces wihtin this same project. This is important if you want members of a project being able to create new namespaces and in scenarios where you have custom scheduler active that depends on annotations being set on the namespace.

**Comment by vincent99** [comment]
This is not, and has never been, a feature of projects as far as I'm aware.

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/21463
