### ISSUE TITLE
[Monitoring V2] Support multiple Monitoring V2 deployments

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29456]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

Need to investigate whether it is possible to deploy multiple Monitoring V2 charts deployments onto a cluster (or deploy Monitoring V2 with another Prometheus Operator in the same cluster) when the Operators are scoped to particular namespaces https://github.com/rancher/charts/blob/1d17a5bb6767f6468815b005b688fb73f7baa228/charts/rancher-monitoring/values.yaml#L1635-L1641.

If this is possible, docs should be added to show how this can be supported. We should also investigate if a similar option can be exposed in Monitoring V1 to allow users to enable both Monitoring V1 and Monitoring V2 within a cluster.

Related Issue: https://github.com/rancher/rancher/issues/25044

**Comment by SheilaghM** [comment]
With the rebase, we can support this. Need to sync with PM as to whether this is desired. Allows us to move toward Project Monitoring, but this may not have been asked for yet.

**Comment by all4innov** [comment]
Is there is any news or recommendation for _project monitoring_ that is highly missing in v2.5

**Comment by aiyengar2** [comment]
@all4innov not yet. The current chart does deploy Prometheus Operator, which can support deploying multiple Prometheis based on the Prometheus CRs in your cluster (we deploy 1 by default), but no official recommendation for how to set up project monitoring currently exists.

Please open up an RFE for Project Monitoring V2!

cc: @cloudnautique

**Comment by all4innov** [comment]
can be closed: developed as new feature starting rancher 2.6.5 ( Prometheus Federator ) 
https://github.com/rancher/rancher/releases/tag/v2.6.5 
![image](https://user-images.githubusercontent.com/520080/168300569-6442db52-5986-46fb-92c9-5fa8d196dfb0.png)
