### ISSUE TITLE
[Monitoring V2] Using the same PV as Monitoring V1

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29457]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1. Set up Monitoring V1 with Persistent Volumes enabled
1. Create a Grafana Dashboard via the Grafana UI (persisted via PV, not via ConfigMap)
1. Disable Monitoring V1
1. Enable Monitoring V2 with the same PV as in Monitoring V1

**Result:**
Do the dashboards persist?

If there are any other steps we could take in order to make it easier for a user to take Monitoring V1 PVs and use them for Monitoring V2 to avoid losing data during the migration, we should look into that.

**Comment by jiaqiluo** [comment]
In Monitoring v1:
 
1. the PV is created with RWO and it is removed automatically if the PVC is removed. This means we cannot reuse the PV for Prometheus. 
2. The PV and PVC for Grafana is removed automatically when monitoring is disabled.

**Comment by aiyengar2** [comment]
Thanks for investigating @jiaqiluo ! Since the PV from monitoring v1 is not reusable and there's no clear path forward for a solution, I'm closing this issue.
