### ISSUE TITLE
Remote access to port 80 of the RancherDocker container failed,

### ISSUE THREAD

**Issue by stringk245** [rancher/rancher#29462]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1.docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher
2. a local browser accesses the Linux server Rancherdocker container

**Result:**
Remote access to port 80 of the RancherDocker container failed,
For example, a local browser accesses the Linux server Rancherdocker container

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
19.0
```
(paste the output here)
```

**Comment by superseb** [comment]
Please supply output of the `rancher/rancher` container  and the output of `curl -vL http://127.0.0.1` from the host the container is running on and/or remote host that is trying to access it.

**Comment by oguzhansrky** [comment]
I have that same problem!!!

docker logs -f rancher

ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes


---------------------------

Although I added a privileged flag, the log is as follows

ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes


![image](https://user-images.githubusercontent.com/52497227/95664390-199de700-0b50-11eb-950a-9a1cbd3271fd.png)


this was working 3 weeks ago....

**Comment by oguzhansrky** [comment]
hey,

rancher/rancher:v2.3.4 working.............

**Comment by stringk245** [comment]
> Please supply output of the `rancher/rancher` container and the output of `curl -vL http://127.0.0.1` from the host the container is running on and/or remote host that is trying to access it.
Rancher docker container  status is  up  and  the local browser(browser of Linux server ) accesses the Linux server Rancher docker container successful, and Linux server  "curl -vL http://127.0.0.1" successful,

just  browser Remote access to port 80 of the RancherDocker container failed,
(windows browser Remote access to port 80 of the RancherDocker container failed, cant not open,
but windows  "curl http://192.168.0.100:80" successful,get this "<a href="https://192.168.0.100/">Found</a>."
why  windows browser Remote access failed ????
)
Rancherdocker logs:
E1012 01:27:11.663927      43 core.go:232] failed to start cloud node lifecycle controller: no cloud provider provided
W1012 01:27:11.663935      43 controllermanager.go:525] Skipping "cloud-node-lifecycle"
W1012 01:27:11.663943      43 controllermanager.go:525] Skipping "endpointslice"
I1012 01:27:11.665129      43 controllermanager.go:533] Started "pv-protection"
W1012 01:27:11.665137      43 controllermanager.go:525] Skipping "ttl-after-finished"
I1012 01:27:11.665171      43 pv_protection_controller.go:81] Starting PV protection controller
I1012 01:27:11.665177      43 shared_informer.go:197] Waiting for caches to sync for PV protection
I1012 01:27:11.667136      43 controllermanager.go:533] Started "disruption"
I1012 01:27:11.667179      43 disruption.go:330] Starting disruption controller
I1012 01:27:11.667186      43 shared_informer.go:197] Waiting for caches to sync for disruption
I1012 01:27:11.668266      43 controllermanager.go:533] Started "csrcleaner"
W1012 01:27:11.668273      43 controllermanager.go:512] "tokencleaner" is disabled
I1012 01:27:11.668323      43 cleaner.go:81] Starting CSR cleaner controller
E1012 01:27:11.669393      43 core.go:91] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail
W1012 01:27:11.669399      43 controllermanager.go:525] Skipping "service"
W1012 01:27:11.669405      43 controllermanager.go:525] Skipping "root-ca-cert-publisher"
I1012 01:27:11.670617      43 controllermanager.go:533] Started "job"
I1012 01:27:11.670682      43 job_controller.go:143] Starting job controller
I1012 01:27:11.670689      43 shared_informer.go:197] Waiting for caches to sync for job
I1012 01:27:11.671810      43 controllermanager.go:533] Started "deployment"
I1012 01:27:11.671824      43 deployment_controller.go:152] Starting deployment controller
I1012 01:27:11.671830      43 shared_informer.go:197] Waiting for caches to sync for deployment
I1012 01:27:11.672964      43 controllermanager.go:533] Started "csrapproving"
I1012 01:27:11.673022      43 certificate_controller.go:118] Starting certificate controller "csrapproving"
I1012 01:27:11.673031      43 shared_informer.go:197] Waiting for caches to sync for certificate-csrapproving
I1012 01:27:11.674074      43 controllermanager.go:533] Started "cronjob"
I1012 01:27:11.674138      43 cronjob_controller.go:97] Starting CronJob Manager
I1012 01:27:11.675407      43 controllermanager.go:533] Started "csrsigning"
I1012 01:27:11.675472      43 certificate_controller.go:118] Starting certificate controller "csrsigning"
I1012 01:27:11.675478      43 shared_informer.go:197] Waiting for caches to sync for certificate-csrsigning
I1012 01:27:11.676598      43 controllermanager.go:533] Started "ttl"
I1012 01:27:11.676654      43 ttl_controller.go:116] Starting TTL controller
I1012 01:27:11.676660      43 shared_informer.go:197] Waiting for caches to sync for TTL
I1012 01:27:11.684339      43 controllermanager.go:533] Started "namespace"
I1012 01:27:11.684370      43 namespace_controller.go:200] Starting namespace controller
I1012 01:27:11.684374      43 shared_informer.go:197] Waiting for caches to sync for namespace
I1012 01:27:11.694880      43 controllermanager.go:533] Started "serviceaccount"
I1012 01:27:11.694979      43 serviceaccounts_controller.go:116] Starting service account controller
I1012 01:27:11.695008      43 shared_informer.go:197] Waiting for caches to sync for service account
I1012 01:27:12.767395      43 garbagecollector.go:129] Starting garbage collector controller
I1012 01:27:12.767430      43 shared_informer.go:197] Waiting for caches to sync for garbage collector
I1012 01:27:12.767491      43 graph_builder.go:282] GraphBuilder running
I1012 01:27:12.767562      43 controllermanager.go:533] Started "garbagecollector"
I1012 01:27:12.773354      43 controllermanager.go:533] Started "replicaset"
I1012 01:27:12.773467      43 replica_set.go:180] Starting replicaset controller
I1012 01:27:12.773489      43 shared_informer.go:197] Waiting for caches to sync for ReplicaSet
I1012 01:27:12.787080      43 controllermanager.go:533] Started "pvc-protection"
I1012 01:27:12.788264      43 pvc_protection_controller.go:100] Starting PVC protection controller
I1012 01:27:12.788299      43 shared_informer.go:197] Waiting for caches to sync for PVC protection
I1012 01:27:12.791616      43 shared_informer.go:197] Waiting for caches to sync for resource quota
I1012 01:27:12.850619      43 shared_informer.go:204] Caches are synced for node 
I1012 01:27:12.850652      43 range_allocator.go:172] Starting range CIDR allocator
I1012 01:27:12.850659      43 shared_informer.go:197] Waiting for caches to sync for cidrallocator
I1012 01:27:12.850665      43 shared_informer.go:204] Caches are synced for cidrallocator 
I1012 01:27:12.865570      43 shared_informer.go:204] Caches are synced for PV protection 
I1012 01:27:12.865623      43 shared_informer.go:204] Caches are synced for ClusterRoleAggregator 
I1012 01:27:12.873206      43 shared_informer.go:204] Caches are synced for certificate-csrapproving 
I1012 01:27:12.875683      43 shared_informer.go:204] Caches are synced for certificate-csrsigning 
I1012 01:27:12.876838      43 shared_informer.go:204] Caches are synced for TTL 
I1012 01:27:12.884768      43 shared_informer.go:204] Caches are synced for namespace 
I1012 01:27:12.895324      43 shared_informer.go:204] Caches are synced for service account 
I1012 01:27:13.060693      43 shared_informer.go:204] Caches are synced for expand 
I1012 01:27:13.151853      43 shared_informer.go:204] Caches are synced for attach detach 
I1012 01:27:13.154311      43 shared_informer.go:204] Caches are synced for ReplicationController 
I1012 01:27:13.157398      43 shared_informer.go:204] Caches are synced for taint 
I1012 01:27:13.157508      43 taint_manager.go:186] Starting NoExecuteTaintManager
I1012 01:27:13.158227      43 shared_informer.go:204] Caches are synced for HPA 
I1012 01:27:13.159315      43 shared_informer.go:204] Caches are synced for persistent volume 
I1012 01:27:13.163077      43 shared_informer.go:204] Caches are synced for GC 
I1012 01:27:13.167418      43 shared_informer.go:204] Caches are synced for disruption 
I1012 01:27:13.167449      43 disruption.go:338] Sending events to api server.
I1012 01:27:13.170855      43 shared_informer.go:204] Caches are synced for job 
I1012 01:27:13.172027      43 shared_informer.go:204] Caches are synced for deployment 
I1012 01:27:13.173751      43 shared_informer.go:204] Caches are synced for ReplicaSet 
I1012 01:27:13.188516      43 shared_informer.go:204] Caches are synced for PVC protection 
I1012 01:27:13.253080      43 shared_informer.go:204] Caches are synced for endpoint 
I1012 01:27:13.328902      43 shared_informer.go:204] Caches are synced for daemon sets 
I1012 01:27:13.333898      43 shared_informer.go:204] Caches are synced for stateful set 
I1012 01:27:14.253864      43 shared_informer.go:197] Waiting for caches to sync for garbage collector
I1012 01:27:14.923958      43 shared_informer.go:204] Caches are synced for resource quota 
I1012 01:27:14.954240      43 shared_informer.go:204] Caches are synced for garbage collector 
I1012 01:27:14.967978      43 shared_informer.go:204] Caches are synced for garbage collector 
I1012 01:27:14.968020      43 garbagecollector.go:138] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
I1012 01:27:14.991884      43 shared_informer.go:204] Caches are synced for resource quota 
2020-10-12 01:27:32.871300 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/cloud-controller-manager\" " with result "range_response_count:1 size:309" took too long (113.04004ms) to execute
2020-10-12 01:32:00.627880 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/kube-scheduler\" " with result "range_response_count:1 size:289" took too long (124.704273ms) to execute
2020-10-12 01:33:06.838207 W | etcdserver: request "header:<ID:7587849703508351762 > txn:<compare:<target:MOD key:\"/registry/leases/kube-system/cloud-controller-manager\" mod_revision:630892 > success:<request_put:<key:\"/registry/leases/kube-system/cloud-controller-manager\" value_size:229 >> failure:<request_range:<key:\"/registry/leases/kube-system/cloud-controller-manager\" > >>" with result "size:18" took too long (103.924034ms) to execute
2020-10-12 01:34:17.158742 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/kube-scheduler\" " with result "range_response_count:1 size:289" took too long (106.077727ms) to execute
2020-10-12 01:35:09.461584 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/kube-controller-manager\" " with result "range_response_count:1 size:307" took too long (103.716707ms) to execute
2020-10-12 01:36:40.706386 I | mvcc: store.index: compact 630551
2020-10-12 01:36:40.892532 I | mvcc: finished scheduled compaction at 630551 (took 185.085427ms)
2020-10-12 01:38:33.493146 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/kube-scheduler\" " with result "range_response_count:1 size:289" took too long (134.624773ms) to execute
2020-10-12 01:39:35.533328 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/cloud-controller-manager\" " with result "range_response_count:1 size:308" took too long (231.592756ms) to execute
E1012 01:39:44.406060      43 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
2020-10-12 01:40:35.316850 W | etcdserver: read-only range request "key:\"/registry/services/endpoints/kube-system/kube-controller-manager\" " with result "range_response_count:1 size:456" took too long (102.018992ms) to execute
2020-10-12 01:41:40.751047 I | mvcc: store.index: compact 631765
2020-10-12 01:41:40.803871 I | mvcc: finished scheduled compaction at 631765 (took 51.837687ms)
2020-10-12 01:42:54.222194 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/kube-scheduler\" " with result "range_response_count:1 size:288" took too long (104.629294ms) to execute
E1012 01:43:42.400355      43 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
E1012 01:44:34.535109      43 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted

**Comment by stringk245** [comment]
> rancher/rancher:v2.3.4 working


rancher/rancher:v2.3.4 working ????
i use  rancher/rancher:stable  and  rancher/rancher:laster  all failed,
Linux server "curl -vL http://127.0.0.1" successful 
Linux server browser  open "http://127.0.0.1" or open "http://linux_ip" successful,
windows "curl -vL http://linux_ip" successful 
windows browser  open "http://linux_ip" failed !!!!!

**Comment by stringk245** [comment]
@superseb @oguzhansrky 
sorry,,,,,, everything is ok, Please ignore this question，
Because of the limitation of our company's network firewall
