### ISSUE TITLE
Grafana option is not showing in Rancher

### ISSUE THREAD

**Issue by avadhut007** [rancher/rancher#29468]
*Describe your issue here*
I have BareMetal K8s Cluster Ver.1.19.1 
I imported the cluster into Rancher UI. 
After adding monitoring from Rancher UI in Bare metal Cluster, It shows Prometheus but not the Grafana UI.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.4` UI: `v2.4.22` |
|Route|`undefined`|

**Comment by aiyengar2** [comment]
@avadhut007 did you follow the instructions on https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.0.x-v2.4.x/cluster-monitoring/#enabling-cluster-monitoring and https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.0.x-v2.4.x/cluster-monitoring/viewing-metrics/#accessing-the-cluster-level-grafana-instance?
