### ISSUE TITLE
No access to Grafana for imported clusters 

### ISSUE THREAD

**Issue by lucasdrai** [rancher/rancher#29467]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Import an existing cluster into Rancher
Enable monitoring on this cluster
wait for monitoring to be ready

**Result:**
Monitoring is enbaled but no Grafana logo appears + no access to Grafana possible
![image](https://user-images.githubusercontent.com/60136085/95715341-f7988780-0c69-11eb-82a4-3808256da455.png)

When I try to acces directly from the local URL I got this result:
![image](https://user-images.githubusercontent.com/60136085/95717212-e69d4580-0c6c-11eb-91dd-abf115ad1056.png)

![image](https://user-images.githubusercontent.com/60136085/95717322-0f253f80-0c6d-11eb-9fc7-c2cbd503775b.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud (google cloud)
- Kubernetes version (use `kubectl version`): v1.16.13-gke.401

**Comment by rgaume-delfingen** [comment]
Hello, I have the same issue... Did you manage to find a fix ?
