### ISSUE TITLE
Improvement - Rancher UI - Generate an access link on each service running on the cluster

### ISSUE THREAD

**Issue by konvergence** [rancher/rancher#29463]
Hi,

Kubernetes API allow us to access on the services via the poxy API
(https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/)

When Rancher monitoring is enabled, Rancher add link to the service of grafana or prometheus
example : 

````
https://my-rancher/k8s/clusters/local/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/
https://my-rancher/k8s/clusters/local/api/v1/namespaces/cattle-prometheus/services/http:access-prometheus:80/proxy/
````

It will really cool to generate into the Rancher UI, a "proxy http url link" for each service (if they can support it)

```
https://<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/<namespace-name>/services/http:<service-name>:<port>/proxy/
````

Regards

**Comment by gaby** [comment]
This is a valid use-case. No matter who I try Rancher keeps ignoring the "Rancher-Proxy" option they use in their charts.
