### ISSUE TITLE
Catalogs cannot import self-signed CA

### ISSUE THREAD

**Issue by DesistDaydream** [rancher/rancher#29466]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
When I add catalog, there was no option to import the ca.crt file.
When I [configured secure harbor](https://goharbor.io/docs/2.1.0/install-config/configure-https/), I used a self-signed CA,but I can't use it in rancher

The helm command has the --ca-file flag to import the certificate

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.4.5
- Installation option (single install/HA):single

**Comment by superseb** [comment]
Did you try configuring the CA according to https://rancher.com/docs/rancher/v2.x/en/installation/resources/chart-options/#additional-trusted-cas?

**Comment by DesistDaydream** [comment]
> Did you try configuring the CA according to https://rancher.com/docs/rancher/v2.x/en/installation/resources/chart-options/#additional-trusted-cas?

Thank you for your prompt reply!
The method you provide is to import other CAs when rancher is deployed in the k8s cluster.
If I just use docker to run a single-node rancher server, are there similar parameters that can be imported into other CAs?

**Comment by superseb** [comment]
It is documented here: https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/advanced/#custom-ca-certificate

**Comment by DesistDaydream** [comment]
Is this method only applicable to 2.5.X? I just failed the test on 2.4.5, but 2.5.1 succeeded

**Comment by superseb** [comment]
No it won't. And it should work in 2.4 as well, let me know what the error was you were seeing on 2.4 and what exact `docker run` command you used.
