### ISSUE TITLE
changing catalog.refresh.interval.seconds does not result in catalog being pulled at the specified refresh interval.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2947]
Server version - v0.49.0-rc2

Changed catalog.refresh.interval.seconds  to 60 secs using  /v1/activesettings/ .

Even after this change , catalog is being pulled only every 5 minutes (default settings).

```
"id": "1as11",
"type": "activeSetting",
"links": {
"self": "…/v1/activesettings/1as11",
},
"actions": { },
"name": "catalog.refresh.interval.seconds",
"activeValue": "60",
"inDb": true,
"source": "Database",
"value": "60",
},
```

value in settings:

| 11 | catalog.refresh.interval.seconds   | 60

**Comment by prachidamle** [comment]
This is not a bug with rancher-catalog-service code. The refresh interval can be changed for the service by restarting it and passing the parameter -refreshInterval=<time in seconds>
@ibuildthecloud any pointers on how can I make this changes in cattle?

**Comment by prachidamle** [comment]
Fixed with PR https://github.com/rancher/cattle/pull/1449

**Comment by sangeethah** [comment]
Tested with latest build from master:

Changed catalog.refresh.interval.seconds to 30 secs using /v1/activesettings/ .

Changes made to the catalog gets synced within the next 30 secs.
