### ISSUE TITLE
[Monitoring V1 UI] Add ability to specify tolerations for more components

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29479]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

Currently, our Monitoring V1 pane only provides the ability to supply a toleration for the Prometheus pod; for clusters like https://github.com/rancher/rancher/issues/27253 which have taints on all of the nodes, this prevent Monitoring V1 from being deployed.

Once the backend changes from https://github.com/rancher/rancher/issues/27253 are in to support passing in tolerations for operator-init, can we add in the ability to supply tolerations for the following Monitoring components on the Rancher Cluster Manager Monitoring UI:
```
operator.tolerations
operator-init.tolerations
grafana.tolerations
exporter-kube-state.tolerations
```

![Screen Shot 2020-10-12 at 1 06 28 PM](https://user-images.githubusercontent.com/13127443/95786049-bfa23c00-0c8b-11eb-9dbe-2068debecb0d.png)

**Comment by Jono-SUSE-Rancher** [comment]
@gaktive & @nwmac - Did you guys want to prioritize this and see if there is any room in either 2.5.7 or 2.6 for this to get done?

**Comment by gaktive** [comment]
I'll mark it for 2.6 for now based on what we have to get done for 2.5.7 and ensure it's on our radar. @Jono-SUSE-Rancher let us know if we need someone to jump on this sooner.
