### ISSUE TITLE
UI - PVs of longhorn always show the default volume attributes in edit/display mode.

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/rancher#29484]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster on rancher v2.4.8.
2. Deploy longhorn v1.0.2
3. Create a persistent volume selecting volume plugin as ```longhorn``` with volume attributes as 
```
"volumeAttributes": {
"numberOfReplicas": "2",
"size": "1Gi",
"staleReplicaTimeout": "10"
}
```
4. Click the PV created in step 3.

**Result:**
The volume attributes displays as ```numberOfReplicas``` as 3, ```size``` as 2Gi and ```staleReplicaTimeout``` as 20 always.
<img width="1271" alt="Screen Shot 2020-10-12 at 4 22 21 PM" src="https://user-images.githubusercontent.com/60111667/95798564-3698fe00-0ca7-11eb-8614-144e8844d3f1.png">

In the API view, it appears fine.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.8
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO cluster 4 nodes(1 etcd/control plane, 3 worker nodes)
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): v1.18.9

**Comment by khushboo-rancher** [comment]
Verified with master-head  ```6c00180```

Validation- **Pass**

The longhorn pvs shows the correct value.
<img width="1337" alt="Screen Shot 2020-10-15 at 4 01 21 PM" src="https://user-images.githubusercontent.com/60111667/96194954-56772e80-0f00-11eb-8d02-cb2ecbced17c.png">

**Comment by catz** [comment]
It seems the same issue exists in rancher 2.11
