### ISSUE TITLE
Integration metrics in UI don't work if using MonitoringV2

### ISSUE THREAD

**Issue by jbilliau-rcd** [rancher/rancher#29486]
**What kind of request is this (question/bug/enhancement/feature request):**
question, maybe bug?

**Steps to reproduce (least amount of steps as possible):**
1.) I freshly installed Rancher 2.5.1 via Helm. I then enabled monitoring via the *Tools > Monitoring* tab, with *"Enable Node Exporter"* set to **true**. I go back to the cluster dashboard, and I get the green bars showing utilization as well as workload metrics, Grafana links, etc. All is great.

<img width="520" alt="dashboard-working" src="https://user-images.githubusercontent.com/69006307/95801843-acae5c80-0cc9-11eb-8a16-b27efa251952.png">

2.) I set *"Enable Node Exporter"* to **false**. Workload/cluster metrics and Grafana dashboard still work, but green utilization bars no longer do. Not sure why they need *"Enable Node Exporter"* as a dependency for functioning....?
3.) I then disable it entirely, and use the new **MonitoringV2** option. *Cluster Explorer > Apps and Marketplace > rancher-monitoring*.  I do all the base options, and disable AlertManager. It all goes successful. I go back to the cluster dashboard and see no grafana links, no metrics, nothing.

<img width="358" alt="dashboard-notworking" src="https://user-images.githubusercontent.com/69006307/95802032-4e35ae00-0cca-11eb-8757-226eb3a592d8.png">

**Result:**

<img width="523" alt="broke" src="https://user-images.githubusercontent.com/69006307/95802767-5ee72380-0ccc-11eb-9f3a-3a795b710ae8.png">

AS you can see, the live metrics are all completely broke.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`v.2.5.1):
- Installation option (single install/HA): HA install on AWS EKS

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted - AWS EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): - cloud
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6"

I guess the core at what im trying to understand is what does Rancher require from Prometheus/Grafana/etc. in order to display integrated metrics in the UI? Something is missed from the MonitoringV2 installed stack that is present in the Tools > Monitoring stack.

**Comment by arodus** [comment]
We have the exact same issue as @jbilliau-rcd, were you able to come up with a solution?

**Comment by jbilliau-rcd** [comment]
Nope, I still am not sure what is the magic sauce behind the curtain that allows for Rancher UI integration with metrics. It seems to only work with the deprecated monitoring.

**Comment by arodus** [comment]
The magic sauce is basically the proxy to the `access-grafana` service in the `cattle-prometheus` namespace. 
After doing some research it seems that showing the metrics in the cluster overview is not yet supported with monitoring v2.
See #803 and #812 for reference.

**Comment by jbilliau-rcd** [comment]
ah good deal, thanks for the response. I guess I'll wait for the update that adds it back in.
