### ISSUE TITLE
Changes synced to catalog  is not reflected in rancher catalog view until a refresh is done.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2949]
Rancher server version - v0.49.0-rc2

Steps to reproduce the problem:
Renamed one of the existing templates in the catalog entry.
Waited for the catalog changes to be synced to the rancher server.
Even after this , the new name for the template is not reflected in the catalog view.
Even going to other tabs and re entering the c catalog view , does not reflect this change.

When a manual refresh is done, the changes are reflected in the catalog view.

**Comment by vincent99** [comment]
Changed to reload when you leave and reenter the catalog screen.

**Comment by sangeethah** [comment]
Tested with latest build from master - Dec 9.

Catalog view gets reload when you leave and reenter the catalog screen.UI is able to reflect theChanges synced to catalog when the catalog screen is reentered.
