### ISSUE TITLE
Install Rancher on k3s with "--no-deploy traefik --disable servicelb"

### ISSUE THREAD

**Issue by GodSpeedXI** [rancher/rancher#29497]
I have installed k3s with --no-deploy traefik --disable servicelb.
Following the instruction, I have installed cert-manager then install rancher with halm by using lets'encrypt.

All everything look fine
```
kubectl get service -n cattle-system                                                                                                                                                                        
NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
cm-acme-http-solver-rqqsz   NodePort    10.43.218.189   <none>        8089:32493/TCP   50m
rancher                     ClusterIP   10.43.136.148   <none>        80/TCP           50m
rancher-webhook             ClusterIP   10.43.212.251   <none>        443/TCP          41m
```
```
kubectl get pod -n cattle-system                                                                                                                                                                            
NAME                               READY   STATUS      RESTARTS   AGE
cm-acme-http-solver-f8t8d          1/1     Running     0          61m
helm-operation-4v69m               0/2     Completed   0          53m
helm-operation-f8d9z               0/2     Completed   0          53m
helm-operation-tdn2d               0/2     Completed   0          52m
helm-operation-wvjhv               0/2     Completed   0          54m
helm-operation-xmlqc               0/2     Completed   0          52m
rancher-6c68dc64b4-7brhl           1/1     Running     0          61m
rancher-6c68dc64b4-9knq5           1/1     Running     1          61m
rancher-6c68dc64b4-wsp9m           1/1     Running     0          61m
rancher-webhook-6f69f5fd94-gsfqg   1/1     Running     0          52m
```

Then, I accessed rancher via https://rancher.mydomain.com:32493 and got the message "ERR_SSL_PROTOCOL_ERROR".
It seems like the cert is incorrect. I have no clue how to fix this.

I installed k3s without traefik, because I just need to install istio with ingress gateway to handle 80 and 443 that was taken by traefik when install k3s.

Are there another way to install rancher with another ingress?

Spec:
Rancher 2.5
K3S 1.9

**Comment by superseb** [comment]
This seems to be the same as https://github.com/rancher/rancher/issues/24066, Rancher is exposed by default using an ingress but without an ingress controller this won't work. The port you are seeing is from cert-manager, not from Rancher, so you won't be able to reach Rancher using that. Pretty sure its a HTTP endpoint to obtain the Lets Encrypt certificate. As seen in https://github.com/rancher/rancher/issues/24066, it needs some work.
