### ISSUE TITLE
Ability to refresh catalog from UI.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2950]
Server version - v0.49.0-rc2

By default the catalog.refresh.interval.seconds is set to 5 mts.
It would be good to provide user with ability to refresh catalog from UI , so that UI is able to reflected the changes made to the catalog immediately.

**Comment by zhangyihong** [comment]
+1

**Comment by vincent99** [comment]
This issue got missed or was a duplicate, there is already a refresh button in the upper-right corner of the main catalog screen.
