### ISSUE TITLE
[2.4] Add EKS 1.18 in UI 

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#29508]
https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-eks-supports-kubernetes-version-1-18/
KEv1 PR coming soon for this in https://github.com/rancher/rancher/issues/28317

**Comment by deniseschannon** [comment]
@westlywright we need to make sure the UI PR is backported to 2.4 and 2.5

**Comment by westlywright** [comment]
My bad, I already asked @paynejacob to make them, I should have made sure they were linked to this ticket.

https://github.com/rancher/ui/pull/4225
https://github.com/rancher/ui/pull/4226

**Comment by sowmyav27** [comment]
**On 2.5 head commit id: `b7228472` and on master-head - commit id: `5682e2` and On latest 2.4-head commit id: `f210f54bd`**
- K8s versions seen in the dropdown while launching a hosted EKS cluster are:
<img width="673" alt="Screen Shot 2020-10-19 at 11 28 29 PM" src="https://user-images.githubusercontent.com/26032343/96493595-cf5cea00-1262-11eb-8df8-d95d28f08137.png">
