### ISSUE TITLE
OL 7.8 cluster creation errors with wrong image

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#29503]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a node template for Oracle Cloud Infrastructure
See `Oracle-Linux-7.8` as the only default option
![image](https://user-images.githubusercontent.com/57409052/95399606-64540080-08bd-11eb-923b-9d089ac5addd.png)
Create template with `Oracle-Linux-7.8` selected
Create cluster using the node template

**Result:**
Cluster creation fails with:
`Error with pre-create check: "could not retrieve image id for an image named Oracle-Linux-7.7"; Timeout waiting for ssh key`
![Screen Shot 2020-10-07 at 4 38 56 PM](https://user-images.githubusercontent.com/57409052/95399538-3e2e6080-08bd-11eb-9653-a2029681c66e.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher\rancher:2.4-head` `version eb990af`
- Installation option (single install/HA): single

**Comment by aaronRancher** [comment]
This issue tracks the error message seen in this UI issue: https://github.com/rancher/rancher/issues/29096

**Comment by jlamillan** [comment]
This is because v1.0.0 of the Docker machine driver tries to look up the id of the default image (which is OL 7.7) as the pre-check.

When OL 7.7 was purged from OCI, the pre-check started failing. v1.0.1 fixed this.

**Comment by jlamillan** [comment]
PR to back-port to `release/v2.4` https://github.com/rancher/rancher/pull/29505

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.4-3950-head`

Steps:
Create a node template for Oracle Cloud Infrastructure
See `Oracle-Linux-7.8` as the only default option
Create template with `Oracle-Linux-7.8` selected
Create cluster using the node template

Result:
Saw cluster provisioning with the correct OL image:
![Screen Shot 2020-10-14 at 4 52 54 PM](https://user-images.githubusercontent.com/57409052/96058029-2a47a900-0e3f-11eb-805b-3812de6b193b.png)

Correct image is used in OCI config:
```
"ociConfig":{
      "fingerprint":"",
      "nodeAvailabilityDomain":"AD-1",
      "nodeCompartmentId":"<ID>,
      "nodeImage":"Oracle-Linux-7.8",
      "nodeShape":"VM.Standard1.1",
...
```
