### ISSUE TITLE
EKS Forbidden Error

### ISSUE THREAD

**Issue by WoodProgrammer** [rancher/rancher#29506]
Hello everyone,

I have a rancher cluster deployed with 2.5.0, while I try to import an EKS cluster to management cluster it returning Unauthorized so I have checked my AWS credentials but there is no problem that related with permission.

How can I fix this problem?
Thanks

![Screen Shot 2020-10-13 at 2 47 29 AM](https://user-images.githubusercontent.com/16826090/95926019-e5caf780-0dc3-11eb-9bf3-f02c9465a7df.png)

**Comment by sowmyav27** [comment]
@WoodProgrammer Can you please check if credentials used to register the cluster match the role or user used by tool to create the EKS cluster as mentioned here - https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/#security-and-compliance. This is often the case if a tool like "eksctl" was used to create the cluster.

**Comment by kachar** [comment]
I had the same problem with EKS cluster created via Rancher UI. 

It seems that AWS do not provide valid SSL certificate for the api endpoint of the cluster, so Rancher is unable to connect and shows the error
