### ISSUE TITLE
When catalog.url is changed , catalog view does not have images until a manual refresh is done.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2951]
Server version - v0.49.0-rc2

Change the  catalog.url to point to a different git hub repo.
We see the new catalog being synced to rancher-server.
Navigate to catalog view.
The new catalog is presented to the user , but the images of do not get loaded until a manual refresh is done.

<img width="1135" alt="screen shot 2015-12-08 at 10 02 11 am" src="https://cloud.githubusercontent.com/assets/4266958/11663809/2d2e8f5c-9d93-11e5-9e7f-7a83350c48e5.png">

**Comment by vincent99** [comment]
@wes when you have the setting for catalog URLs, can you clear the cached catalog

**Comment by vincent99** [comment]
I think this was fixed last release by a similar issue.

**Comment by sangeethah** [comment]
Tested with latest build from master:
Change the catalog.url to point to a different git hub repo.
We see the new catalog being synced to rancher-server.
Navigate to catalog view.
The new catalog is presented to the user along with the image for the catalog entries.
