### ISSUE TITLE
vSphere/ESXi 7.0 support 

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#29519]
**What kind of request is this (question/bug/enhancement/feature request):**
RFE

**Steps to reproduce (least amount of steps as possible):**
vSphere 7 does not yet appear to be supported by Rancher.  In fact, the support matrix only appears to endorse v6.5 and v6.7 and issues exist for v6.9 (#25404) and v6.7 (#27732)

**Request:**
Expand support to v7.  It sounds like this is in the works but we do not yet have an ETA or milestone and I could not find an issue to track it (thus this one)

gzrancher/rancher#12749

**Comment by DH-Rancher** [comment]
I would like to get some feedback from the community before we mark it as resolved, but based on my testing thus far it has passed the issues we've previously seen.

## Issue List

|GH Issue Reference  | Description | Tested on vSphere 7?  |
|---|---|---|
| #25404  | VMs get created in vsphere but get an error message in vsphere recent task window: "A specified parameter was not correct: deviceChange[1].device.key" on VMware Cloud on AWS 6.9  | Yes, Pass (based on 27732)  |
| #27699  | Datastores with empty characters causes failed provisioning  | Yes, Pass  |
| #27732  | A specified parameter was not correct: deviceChange[1].device.key" on vSphere/ESXi 7 (on prem)   | Yes, Pass  |

## Test Parameters (vCenter)

**vCenter Version** : 7.0.1.00000  
**vCenter Build Number** : 16860138  
**ESXi Version** : 7.0.0  
**ESXi Build Version** : 15843807   
**Rancher version** :  v2.4-4012-head (to test changes/fixes)
**Rancher version** : v2.5.1 (current `latest` release)

## Test Parameters (Template)

**CPU** : 2  
**Memory**: 2GB  
**Hard Disk 1** : 16GB  
**CD/DVD** : Present  
**Network** : vDS Port Group "VDS-MGMT-PXE"  

## Test Case 1 - Add additional device

Steps:

* Create Node Template based on the aforementioned template
* Configure Node Template to add an additional vNIC connected to another port group, resulting in two: `VDS-MGMT-PXE` and `VDS-MGMT-DEFAULT`

Current Behavior (As of v2.5.1):

```Error creating machine: Error in driver during machine creation: A specified parameter was not correct: deviceChange[1].device.key ```

Behaviour in 2.5-head

No issues observed. Resulting VM configuration as expected.

## Test Case 2 - Modifying existing VM

* Create Node Template based on the aforementioned template
* Configure Node Template to leverage a different network port group to what is defined in the template, therefore invoking a reconfiguration event. The port group is configured is `VDS-MGMT-DEFAULT`

Current Behavior (As of v2.5.1):

```Error creating machine: Error in driver during machine creation: A specified parameter was not correct: deviceChange[1].device.key ```

Behaviour in 2.5-head

No issues observed. Resulting VM configuration as expected.

## Test Case 3 - Deploying to a Datastore with empty characters

* Create Node Template based on the aforementioned template
* Configure Node Template to deploy to a Datastore with empty characters - `Datastore - General 01` 


Current Behavior (As of v2.5.1): 

First VM provisions OK  
Subsequent VM's will error with ` Error creating machine: Error in driver during machine creation: 500 Internal Server Error `

First VM mounts the user-data iso as `[Datastore - General 01] -/user-data.iso` - This is not expected and causes issues.

Behaviour in 2.5-head

The first VM mounts the user-data iso as `[Datastore - General 01] testvm1/user-data.iso` - `testvm1` is the VM name. This is correct.

The second VM mounts the user-data iso as `[Datastore - General 01] testvm2/user-data.iso` - `testvm2` is the VM name. This is correct.

If there are any additional issues needed to be tested - please let us know!

Thank you.

**Comment by dbsanfte** [comment]
It would be good to have this series of issues looked at around Rancher's ability to recover from VM name conflicts, because this does not always seem to happen:

https://github.com/rancher/rancher/issues/29402

**Comment by ssurovich** [comment]
Im not sure if the team wanted any feedback, but I tested vSphere 7 update1 this morning, and the error still occurs after the VM are deployed "A specified parameter was not correct: deviceChange[1].device.key".  - Running Rancher 2.5.1, VMs are deployed using the boot2docker ISO.

**Comment by DH-Rancher** [comment]
@ssurovich These changes haven't been committed to 2.5.1. If you want to test it out you could do something like:

```
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:v2.4-head
```
* Log into Rancher  
* Configure Cloud Credential and Node Template  
* Attempt to create a cluster

**Comment by ssurovich** [comment]
Hi @DH-Rancher   -  Thanks for that update, apologies I took awhile to reply, but this IS working with vSphere 7.0 without any issues now... Thanks you!!

**Comment by DH-Rancher** [comment]
No worries @ssurovich - Appreciate you providing feedback :+1:
