### ISSUE TITLE
add user and password options to Rancherd

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#29530]
Allow for Rancherd to have a cli flag allowing for the specifying of a password for an admin user to be created, or allow for a flag that stands up Rancher in the same way as a default install with the admin user and blank password to allow for this to continue to work with automation scripts that set the password via https calls.

**Comment by davidnuzik** [comment]
We'd like to add a flag for setting a password via cli for the admin user. This would be an initial implementation of this such that we would, as securely as possible, write some hash or something to disk. If anyone has feedback on this I'm open to it.

This will need to be improved upon and later; we may need to support other methods of authentication. This will need further discussion later.

**Comment by StrongMonkey** [comment]
@aaronRancher 
There should be two option in rancherd CLI now.
```
rancherd reset-admin --password $yourpassword # Specifying the password 
rancherd reset-admin --password-file /path/to/password-file # Specifying the file which contains password
```

Test if you were able to access rancher using the password you set from command line or files.

**Comment by aaronRancher** [comment]
Tested with Rancherd version `v1.18.12+rke2r1`
Installed Rancherd with:
`curl -sfL https://get.rancher.io | sudo INSTALL_RANCHERD_VERSION=v2.5.4-rc2 sh -`
```
root@ip-<IP>:/home/ubuntu# rancherd reset-admin --password testpass
INFO[0000] Server URL: https://<IP>:8443%!(EXTRA string=<IP>)
INFO[0000] Default admin and password created. Username: admin, Password: testpass
```

Rancher is accessible using the password set from the command line.

**Comment by aaronRancher** [comment]
Tested with Rancherd version `v1.18.12+rke2r1`
Installed Rancherd with:
`curl -sfL https://get.rancher.io | sudo INSTALL_RANCHERD_VERSION=v2.5.4-rc2 sh -`
```
root@ip-<IP>:/home/ubuntu# echo testpass123 > ./password.txt
root@ip-<IP>:/home/ubuntu# rancherd reset-admin --password-file ./password.txt
INFO[0000] Default admin reset. New username: admin, new Password: testpass123
```
Rancher is accessible using the password set from the file.

**Comment by sowmyav27** [comment]
Reopening to test on master branch

**Comment by aaronRancher** [comment]
Tested with Rancherd version `baf4867cb (HEAD)`
Installed Rancherd with:
`RKE2_RUNTIME_IMAGE=rancher/rancher-runtime:v2.5.4-rc2 ./rancherd server --write-kubeconfig-mode 644 2>&1 & `

```
root@ip-<IP>:/home/ubuntu# rancherd reset-admin --password testpass
INFO[0000] Server URL: https://<IP>:8443%!(EXTRA string=<IP>)
INFO[0000] Default admin and password created. Username: admin, Password: testpass
```
Rancher is accessible using the password set from the command line.

```
root@ip-<IP>:/home/ubuntu# echo testpass123 > ./password.txt
root@ip-<IP>:/home/ubuntu# rancherd reset-admin --password-file ./password.txt
INFO[0000] Default admin reset. New username: admin, new Password: testpass123
```
Rancher is accessible using the password set from the file.
