### ISSUE TITLE
Bug: EKS: Rancher Deployment: [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set

### ISSUE THREAD

**Issue by ankitsoni17-png** [rancher/rancher#29533]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Install rancher with self-signed certificate(using cert-manager) in EKS.

**Result:**
Deployment, service and ingress is created successfully but pod logs shows the below error:

```
2020/10/15 11:21:53 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/10/15 11:21:54 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/10/15 11:21:55 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/10/15 11:21:56 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/10/15 11:21:57 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/10/15 11:21:58 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/10/15 11:21:59 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/10/15 11:22:00 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/10/15 11:22:01 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/10/15 11:22:02 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/10/15 11:22:03 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/10/15 11:22:04 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set

```

**Other details that may be helpful:**
I am trying to deploy Rancher (2.4.8) on EKS serevr and using cert-manager to generate the certificate. All the resources are deployed and in running state but there is an error in pod logs due to which server is not accessible.

```
[ankit@rancher ~]$ kubectl -n cattle-system get all
NAME                                  READY   STATUS    RESTARTS   AGE
pod/rancher-server-66bc987745-jtnr8   1/1     Running   0          18h
pod/rancher-server-66bc987745-st89m   1/1     Running   0          18h
pod/rancher-server-66bc987745-t99qt   1/1     Running   0          18h

NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/rancher-server   ClusterIP   10.100.225.99   <none>        80/TCP    3d6h

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rancher-server   3/3     3            3           3d6h

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/rancher-server-66bc987745   3         3         3       3d6h
[ankit@rancher ~]$ kubectl -n cattle-system get issuer
NAME             READY   AGE
rancher-server           23h

```
Also when I described the ingress, there I cannot find the backend configured.

```
[ankit@rancher ~]$ kubectl -n cattle-system describe ingress
Name:             rancher-server
Namespace:        cattle-system
Address:
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  tls-rancher-ingress terminates rancher.example.com
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  rancher.example.com
                             rancher-server:80 (137.182.41.109:80,137.182.43.5:80,137.182.46.21:80)
Annotations:              cert-manager.io/issuer: rancher-server
                          cert-manager.io/issuer-kind: Issuer
                          nginx.ingress.kubernetes.io/proxy-connect-timeout: 30
                          nginx.ingress.kubernetes.io/proxy-read-timeout: 1800
                          nginx.ingress.kubernetes.io/proxy-send-timeout: 1800
Events:                   <none>
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.8 (stable)
- Installation option (single install/HA): single install (using helm) 

**Cluster information**
- Cluster type : EKS
- kubectl version: "v1.18.6"
- Kubernetes version (use `kubectl version`): "v1.15.11-eks-af3caf"

**Comment by superseb** [comment]
If you access the Rancher UI on the configured address, you will get prompted to configure `server-url`, which will make this error go away. If you are running on EKS you will need to expose Rancher probably using the way you want (either ingress or load balancer provided by AWS)

**Comment by ankitsoni17-png** [comment]
> If you access the Rancher UI on the configured address, you will get prompted to configure `server-url`, which will make this error go away. If you are running on EKS you will need to expose Rancher probably using the way you want (either ingress or load balancer provided by AWS)

Hi @superseb 
Is it possible to disable the ingress in Rancher helm chart and deploy it via NodePort service. I have a nginx server configured on EKS. I will make an entry on nginx(on some other port) to route the traffic on Rancher service.

And one more doubt I have is that the hostname should point the loadbalancer IP address (of rancher) or the ingress IP address to access the server?

**Comment by superseb** [comment]
This was recently offered in a PR here: https://github.com/rancher/rancher/pull/30397
