### ISSUE TITLE
[Monitoring V2] Update README.md / app-README.md

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29547]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request / bug

The Rancher Monitoring [README.md](https://github.com/rancher/charts/blob/main/charts/rancher-monitoring/README.md) currently directly copies what is available in `kube-prometheus-stack` instead of having Rancher specific information. For example, the [installation instructions](https://github.com/rancher/charts/tree/main/charts/rancher-monitoring#install-chart) are misleading since they tell the user how to install the upstream chart, not the Rancher chart.

To make it easier for a Helm user to understand how to install the app (since this will not be added to the Rancher docs in general), the `README.md` should be overlaid (instead of patched) to have Rancher Monitoring specific information only and link to the upstream `kube-prometheus-stack` README.md for the appropriate chart version.

Also need to take care of a minor bug in the `app-README.md` where it points to the wrong repo.

**Comment by aiyengar2** [comment]
Since having the upstream README.md + the Rancher-specific README.md is a common problem across all feature charts, figuring out a way to elegantly allow chart owners to specify the Rancher-specific README.md updates should be tracked in https://github.com/rancher/rancher/issues/28730 as well.

The reason why README.md updates aren't something we want to track in a patch file is because it just introduces an unnecessary set of conflicts that need to be resolved on rebasing to a new upstream version of a feature chart.

**Comment by aiyengar2** [comment]
> Also need to take care of a minor bug in the `app-README.md` where it points to the wrong repo.

Tracked in https://github.com/rancher/charts/pull/818; this does not close out the main issue however.

**Comment by SheilaghM** [comment]
Closing because old.
