### ISSUE TITLE
[UI] Add a field to accept Entity ID for Keycloak

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#29553]
Keycloak provider needs to accept a new field called Entity ID of type string, json tag: `entityID`

https://github.com/rancher/rancher/issues/29212

**Comment by mrajashree** [comment]
Discussed with @westlywright offline that Entity Id is not a required field. So it shouldn't show as required in the UI.

**Comment by izaac** [comment]
- Rancher version: `master-head (10/19/2020)` _e4dc25135_
- Rancher version: `v2.5-head (10/19/2020)` _52583ea7a_

This was tested and validated as part of #29212 
https://github.com/rancher/rancher/issues/29212#issuecomment-712514167
