### ISSUE TITLE
[2.5 Forward port] Editing deployed Rancher Logging looses state if you Edit as File

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#29558]
Forward port issue for https://github.com/rancher/rancher/issues/26559

**Comment by izaac** [comment]
Rancher version: `v2.5-head` _63e99b6_
I validated the **Fluentd Configuration** state is preserved navigating back and forth as Form and as File.

I will work on #29562 (`master`). `v2.4-head` was validated already in #26559
