### ISSUE TITLE
Installing Loki chart from URL, "Error: gzip: invalid header"

### ISSUE THREAD

**Issue by zhcsyncer** [rancher/rancher#29557]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Add loki repository https://grafana.github.io/loki/charts
2. Install Loki 

**Result:**
![image](https://user-images.githubusercontent.com/13214840/96203930-a5bb6e80-0f95-11eb-9825-2d6132e5308c.png)

**Other details that may be helpful:**

```log
rancher-7c7b6bd945-45zp2 rancher 2020/10/16 01:53:40 [ERROR] Unknown error: gzip: invalid header
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.1
- Installation option (single install/HA):

```bash
~ (⎈ infra-cluster|cattle-system) ❯❯❯ helm get values rancher -n cattle-system
USER-SUPPLIED VALUES:
hostname: r.xxx.com
ingress:
  extraAnnotations:
    kubernetes.io/ingress.class: edge-nginx
    kubernetes.io/ingress.provider: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  tls:
    source: secret
replicas: 1
```

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyun.1", GitCommit:"4f7ea78", GitTreeState:"", BuildDate:"2020-05-08T07:29:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Fgruntjes** [comment]
Same issue here but with a custom chart from a private chartmuseum repo

**Comment by Fgruntjes** [comment]
@thedadams thnx for the fix! This also gave me the insight to add a slash to the url in my repository spec and now I have a working chart repository.

**Comment by jiaqiluo** [comment]
The bug fix is validated in rancher:`master-0390ff5bc542936c93969624c3644ddefb139b52-head` 

Steps:
- add the repo using the URL `https://grafana.github.io/loki/charts` , notice that a `/` is added to the end 
![image](https://user-images.githubusercontent.com/6218999/96771537-a50c4900-1396-11eb-9e65-c640c5f10785.png)
- install the app Loki

Results:
the app is installed successfully 
![image](https://user-images.githubusercontent.com/6218999/96771664-d38a2400-1396-11eb-9965-6c6e3c82db1d.png)

**Comment by cbron** [comment]
This is causing the HTTP helm indexes to be downloaded forever in a loop.

**Comment by Fgruntjes** [comment]
@cbron Had the same issue here but that's actualluy due to a bug in chartmuseum to be more precise https://github.com/rancher/rancher/issues/23256 was the bug I found in rancher wich led me to https://github.com/helm/chartmuseum/issues/152 and contains your solution.

**Comment by izaac** [comment]
Rancher version: `master-head (10/29/2020)` _d61a1a4_
Rancher version: `v2.5-head (10/29/2020)` _0465f04_

I validated I was able to install from the third party repo without adding a trailing slash and the apps were retrieved from the repo. Listed in the Charts page and I was able to install the Loki app. `https://grafana.github.io/loki/charts`

Checking the Rancher server logs for the repo index refresh I only found the added repo refreshed a few times over a period of ~30 mins.

```
2020/10/29 23:09:30 [INFO] Downloading repo index from https://grafana.github.io/loki/charts/index.yaml
2020/10/29 23:09:30 [INFO] Downloading repo index from https://grafana.github.io/loki/charts/index.yaml
2020/10/29 23:09:30 [INFO] Downloading repo index from https://grafana.github.io/loki/charts/index.yaml
2020/10/29 23:14:30 [INFO] Downloading repo index from https://grafana.github.io/loki/charts/index.yaml
```

No other repo index log was found.
