### ISSUE TITLE
Host Support - Docker Machine - Vmware Fusion

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#2955]
Hopefully possible, it would be ace if rancher would support for vmware fusion through docker machine. (https://docs.docker.com/machine/drivers/vm-fusion/)

**Comment by deniseschannon** [comment]
Since we're staring to add in full support for docker-machine v0.5.0, we should be able to add support for this (as far as I can understand).

**Comment by Rucknar** [comment]
Given Vmware's recent move away from supporting desktop software, i'm going to close this ticket as we've chosen not to invest any time in it. If you'd still like to track it though for a feature, by all means feel free to re-open.
