### ISSUE TITLE
[Forward port] Editing deployed Rancher Logging looses state if you Edit as File

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#29562]
Forward port issue for https://github.com/rancher/rancher/issues/26559

**Comment by izaac** [comment]
Rancher version: `master-head` _f3d8bb0_
I validated the **Fluentd Configuration** state is preserved navigating back and forth as Form and as File.

v2.4-head` was validated already in #26559 and `v2.5-head` was validated too in #29558
