### ISSUE TITLE
AWS Clusters AMI Testing for Root Block Device 

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#29568]
We are merging a PR which will pull an AMI and grab the root block device name instead of using a hidden nodetemplate/rancher-machine field called DeviceName. This was defaulted to `/dev/sda1` which is not always the root block device and forced people to use the API to update this field if your AMI did not have this location as the root block device.

The default for this flag is now changed to an empty string so if that is passed machine will lookup the AMI and assign the root block device of the new instance based on what the AMI has instead of the wrong default.

Basics for testing this will be to make AWS Clusters and change the AMI a bunch and make sure the cluster comes up. As an added bonus, this PR will include support for Fedora CoreOS, if you can find an AMI for that give it a shot too.

**Comment by izaac** [comment]
### Rancher version: `v2.4.8`.

I reproduced the issue with a CoreOS based cluster node won't come up. Using latest stable CoreOS ami `ami-0372b0fe5a117e5c2` with Boot Device Name `/dev/xvda`

```
2020/10/16 23:44:55 [INFO] [node-controller-rancher-machine] Provisioning with fedora...
2020/10/16 23:45:27 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2020/10/16 23:45:27 [INFO] [node-controller-rancher-machine]
2020/10/16 23:45:27 [INFO] Generating and uploading node config izaac-coreos2-all-1
2020/10/16 23:45:27 [ERROR] NodeController c-4pj2k/m-hv5km [node-controller] failed with : Error creating machine: Error running provisioning: RHEL ssh command error: command: sudo -E yum install -y curl err: exit status 1 output: sudo: yum: command not found
2020/10/16 23:45:27 [INFO] Creating jail for c-4pj2k
2020/10/16 23:45:27 [INFO] Generating and uploading node config
2020/10/16 23:47:27 [INFO] Removing node izaac-coreos2-all-1
2020/10/16 23:47:27 [INFO] [node-controller-rancher-machine] About to remove izaac-coreos2-all-1
2020/10/16 23:47:27 [INFO] [node-controller-rancher-machine] WARNING: This action will delete both local reference and remote instance.
2020/10/16 23:47:47 [INFO] [node-controller-rancher-machine] Successfully removed izaac-coreos2-all-1
2020/10/16 23:47:47 [INFO] Removing node izaac-coreos2-all-1 done
```

### Rancher version `v2.4-head` _f210f54bd_


I validated the fix in  I used the same CoreOS ami `ami-0372b0fe5a117e5c2` with Boot Device Name `/dev/xvda`

The Fedora CoreOS nodes were active and the cluster was created succesfully k8s `v1.18.10-rancher1-1`
I also validated using the following operating systems bringing up clusters. With Boot Device Name `/dev/sda1`

- Ubuntu 18.04
- CentOS 7.8.2003  ami-0a248ce88bcc7bd23

**Comment by izaac** [comment]
Reopening to get this forwardport to `2.5-head` and `master-head`

**Comment by olivierlemasle** [comment]
Cf https://github.com/rancher/rancher/issues/29593 for Fedora CoreOS tests

**Comment by izaac** [comment]
Rancher version: `v2.5-head (10/21/2020)` _61a8a36_
Rancher version: `master-head (10/21/2020)` _0390ff5_

Performed [the same checks](https://github.com/rancher/rancher/issues/29568#issuecomment-710701222) as `2.4-head` on both `v2.5-head` and `master-head` I no longer see a node creation error while creating the cluster with Fedora CoreOS. I used the weave CNI plugin.
