### ISSUE TITLE
Rancher 2.5.0 & 2.5.1 cluster agent pod crashing.

### ISSUE THREAD

**Issue by Himansh-ilink** [rancher/rancher#29564]
Hello, I am  facing issue with rancher 2.5.1 & 2.5.0. I am using fedora coreos in my environment. i tried with k8s 1.17, 1.18 & 1.19 k8s version.
![issue](https://user-images.githubusercontent.com/62114274/96247776-3448e380-0fc8-11eb-9689-7eb47b1d7273.PNG)
can someone please help.

Thank you

**Comment by superseb** [comment]
Was the flexvolume directory configured as described in https://github.com/rancher/rke/issues/1744#issuecomment-597362929?

**Comment by Himansh-ilink** [comment]
@superseb yes flexvolume is configured and calico pod is in running state still getting same error.

**Comment by superseb** [comment]
@Himansh-ilink Please share the exact cluster YAML used with the configuration and the exact OS version.

**Comment by Himansh-ilink** [comment]
@superseb i have tried with ubuntu 18.04 & fedora coreos 32 Operating system.
Below is my rke template configuration.
# 
# Cluster Config
# 
answers: {}
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
fleet_workspace_name: fleet-default
local_cluster_auth_endpoint:
  enabled: true
name: cluster
# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509|webhook
  authorization: {}
  bastion_host:
    ssh_agent_auth: false
  cloud_provider: {}
  dns:
    linear_autoscaler_params: {}
    node_selector: null
    nodelocal:
      ip_address: ''
      node_selector: null
      update_strategy: {}
    reversecidrs: null
    stubdomains: null
    update_strategy: {}
    upstreamnameservers: null
  ignore_docker_version: true
# 
# # Currently only nginx ingress provider is supported.
# # To disable ingress controller, set `provider: none`
# # To enable ingress on specific nodes, use the node_selector, eg:
#    provider: nginx
#    node_selector:
#      app: ingress
# 
  ingress:
    provider: nginx
  kubernetes_version: v1.19.3-rancher1-1
  monitoring:
    provider: metrics-server
    replicas: 1
# 
#   If you are using calico on AWS
# 
#    network:
#      plugin: calico
#      calico_network_provider:
#        cloud_provider: aws
# 
# # To specify flannel interface
# 
#    network:
#      plugin: flannel
#      flannel_network_provider:
#      iface: eth1
# 
# # To specify flannel interface for canal plugin
# 
#    network:
#      plugin: canal
#      canal_network_provider:
#        iface: eth1
# 
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: calico
  restore:
    restore: false
# 
#    services:
#      kube-api:
#        service_cluster_ip_range: 10.43.0.0/16
#      kube-controller:
#        cluster_cidr: 10.42.0.0/16
#        service_cluster_ip_range: 10.43.0.0/16
#      kubelet:
#        cluster_domain: cluster.local
#        cluster_dns_server: 10.43.0.10
# 
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: 30000-32767
    kube-controller: {}
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy: {}
    scheduler: {}
  ssh_agent_auth: false
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
scheduled_cluster_scan:
  enabled: false
  scan_config:
    cis_scan_config:
      override_benchmark_version: rke-cis-1.5
      profile: permissive
  schedule_config:
    cron_schedule: 0 0 * * *
    retention: 24

**Comment by superseb** [comment]
The cluster yaml is not according to the linked comment, there is a space missing which causes wrong indentation and the kube-controller part is missing. Also, this is only needed for Fedora, not for Ubuntu.

Can you also share the setup details (single/HA), what command you used to install the setup and what certificates you are using for the setup?

**Comment by mikekuzak** [comment]
Seems to have the same issue Rancher V2.5.1 / Flatcar 2512.5.0

```
E1022 14:31:22.247211    9641 pod_workers.go:191] Error syncing pod 6f433035-dc92-4bc0-b2f8-8d28574a0c5c ("canal-btcw5_kube-system(6f433035-dc92-4bc0-b2f8-8d28574a0c5c)"), skipping: failed to "StartContainer" for "flexvol-driver" with CrashLoopBackOff: "back-off 5m0s restarting failed container=flexvol-driver pod=canal-btcw5_kube-system(6f433035-dc92-4bc0-b2f8-8d28574a0c5c)"
E1022 14:31:33.247082    9641 pod_workers.go:191] Error syncing pod 6f433035-dc92-4bc0-b2f8-8d28574a0c5c ("canal-btcw5_kube-system(6f433035-dc92-4bc0-b2f8-8d28574a0c5c)"), skipping: failed to "StartContainer" for "flexvol-driver" with CrashLoopBackOff: "back-off 5m0s restarting failed container=flexvol-driver pod=canal-btcw5_kube-system(6f433035-dc92-4bc0-b2f8-8d28574a0c5c)"
E1022 14:31:45.246993    9641 pod_workers.go:191] Error syncing pod 6f433035-dc92-4bc0-b2f8-8d28574a0c5c ("canal-btcw5_kube-system(6f433035-dc92-4bc0-b2f8-8d28574a0c5c)"), skipping: failed to "StartContainer" for "flexvol-driver" with CrashLoopBackOff: "back-off 5m0s restarting failed container=flexvol-driver pod=canal-btcw5_kube-system(6f433035-dc92-4bc0-b2f8-8d28574a0c5c)"
E1022 14:31:56.247120    9641 pod_workers.go:191] Error syncing pod 6f433035-dc92-4bc0-b2f8-8d28574a0c5c ("canal-btcw5_kube-system(6f433035-dc92-4bc0-b2f8-8d28574a0c5c)"), skipping: failed to "StartContainer" for "flexvol-driver" with CrashLoopBackOff: "back-off 5m0s restarting failed container=flexvol-driver pod=canal-btcw5_kube-system(6f433035-dc92-4bc0-b2f8-8d28574a0c5c)"
W1022 14:32:08.330198    9641 docker_container.go:257] Cannot create symbolic link because container log file doesn't exist!
E1022 14:32:08.330329    9641 remote_runtime.go:222] StartContainer "7dceb13d8964a54a7baa9b629f050918596b45d397828ba7846862422d08d115" from runtime service failed: rpc error: code = Unknown desc = failed to start container "7dceb13d8964a54a7baa9b629f050918596b45d397828ba7846862422d08d115": Error response from daemon: error while creating mount source path '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds': mkdir /usr/libexec/kubernetes: read-only file system
E1022 14:32:08.330397    9641 kuberuntime_manager.go:809] init container start failed: RunContainerError: failed to start container "7dceb13d8964a54a7baa9b629f050918596b45d397828ba7846862422d08d115": Error response from daemon: error while creating mount source path '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds': mkdir /usr/libexec/kubernetes: read-only file system
E1022 14:32:08.330417    9641 pod_workers.go:191] Error syncing pod 6f433035-dc92-4bc0-b2f8-8d28574a0c5c ("canal-btcw5_kube-system(6f433035-dc92-4bc0-b2f8-8d28574a0c5c)"), skipping: failed to "StartContainer" for "flexvol-driver" with RunContainerError: "failed to start container \"7dceb13d8964a54a7baa9b629f050918596b45d397828ba7846862422d08d115\": Error response from daemon: error while creating mount source path '/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds': mkdir /usr/libexec/kubernetes: read-only file system"
I1022 14:32:15.318140    9641 kubelet.go:1954] SyncLoop (PLEG): "canal-btcw5_kube-system(6f433035-dc92-4bc0-b2f8-8d28574a0c5c)", event: &pleg.PodLifecycleEvent{ID:"6f433035-dc92-4bc0-b2f8-8d28574a0c5c", Type:"ContainerDied", Data:"66abaa47b79229d0e866f0879c1604a3d1f12c795bdec5786b396418829d0286"}
W1022 14:32:15.318235    9641 pod_container_deletor.go:75] Container "66abaa47b79229d0e866f0879c1604a3d1f12c795bdec5786b396418829d0286" not found in pod's containers

```

**Comment by mikekuzak** [comment]
Yes this works: 

```
rke_config {

    kubernetes_version    = var.k8s_cluster_version
    ignore_docker_version = false

    network {
      plugin = var.k8s_cluster_network_plugin

        options = {
        canal_flex_volume_plugin_dir = "/opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds"
        flannel_backend_type         = "vxlan"
      }
    }

    services {
      etcd {
        creation  = "12h"
        retention = "24h"
      }

      kube_controller {
        extra_args = {
          flex-volume-plugin-dir = "/opt/kubernetes/kubelet-plugins/volume/exec/"
        }
      }
}
```
I guess this just the workaround applied, should be dealt within the Rancher provisioning engine I believe.

**Comment by Himansh-ilink** [comment]
@superseb I am using single vm setup of rancher & it is working fine,But when I am configuring custom cluster using rke template, cattle-cluster-agent is crashing, below are  the log of kubelet.

![image](https://user-images.githubusercontent.com/62114274/96953085-ea06bb80-150d-11eb-9556-4aa8d9a8af75.png)

I1023 03:21:00.456883 1421815 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 686b9120e382722c593f1137908f88cd51dee4fcfb71205b8195bce0a409608b
E1023 03:21:00.457560 1421815 pod_workers.go:191] Error syncing pod 79d6c2c3-69d3-4f76-ad8f-64ce61cb6038 ("cattle-cluster-agent-d7b98f66c-jtfnv_cattle-system(79d6c2c3-69d3-4f76-ad8f-64ce61cb6038)"), skipping: failed to "StartContainer" for "cluster-register" with CrashLoopBackOff: "back-off 5m0s restarting failed container=cluster-register pod=cattle-cluster-agent-d7b98f66c-jtfnv_cattle-system(79d6c2c3-69d3-4f76-ad8f-64ce61cb6038)"
I1023 03:21:14.631198 1421815 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 686b9120e382722c593f1137908f88cd51dee4fcfb71205b8195bce0a409608b
E1023 03:21:14.631920 1421815 pod_workers.go:191] Error syncing pod 79d6c2c3-69d3-4f76-ad8f-64ce61cb6038 ("cattle-cluster-agent-d7b98f66c-jtfnv_cattle-system(79d6c2c3-69d3-4f76-ad8f-64ce61cb6038)"), skipping: failed to "StartContainer" for "cluster-register" with CrashLoopBackOff: "back-off 5m0s restarting failed container=cluster-register pod=cattle-cluster-agent-d7b98f66c-jtfnv_cattle-system(79d6c2c3-69d3-4f76-ad8f-64ce61cb6038)"


My rke template configuration are as follow:

 
# Cluster Config
 docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
 # Rancher Config
 rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509
  dns:
    linear_autoscaler_params:
      cores_per_replica: 128
      max: 0
      min: 1
      nodes_per_replica: 4
      prevent_single_point_failure: true
    node_selector: null
    nodelocal:
      node_selector: null
      update_strategy:
        rolling_update: {}
    reversecidrs: null
    stubdomains: null
    update_strategy:
      rolling_update: {}
    upstreamnameservers: null
  ignore_docker_version: true
  ingress:
    provider: nginx
  kubernetes_version: v1.18.10-rancher1-1
  monitoring:
    provider: metrics-server
    replicas: 1
  network:
    mtu: 0
    options:
      calico_flex_volume_plugin_dir: /opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
      flannel_backend_type: vxlan
    plugin: calico
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube_controller:
        extra_args:
          flex-volume-plugin-dir = "/opt/kubernetes/kubelet-plugins/volume/exec/"
	kube_api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: 30000-32767
  ssh_agent_auth: false
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
scheduled_cluster_scan:
  enabled: false
  scan_config:
    cis_scan_config:
      debug_master: false
      debug_worker: false
      override_benchmark_version: rke-cis-1.5
      profile: permissive
  schedule_config:
    cron_schedule: 0 0 * * *
    retention: 24
windows_prefered_cluster: false

**Comment by Himansh-ilink** [comment]
@superseb I am using below command to provision custom cluster using rke template.
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.5.1 --server https://rancherpublicurl.com --token hwz6675wdbhrhthfmfhp8xvsh7wlfdtdgjfqxt4r8p27gdf9gx7ftg --internal-address 192.168.x.x --etcd --controlplane --worker

**Comment by superseb** [comment]
Please use the following commands to check the status and logs of the cluster agent:

```
$ docker ps -a --filter "label=io.kubernetes.container.name=cluster-register"
$ docker ps -a -q --filter "label=io.kubernetes.container.name=cluster-register" | while read container; do echo "=> $container"; docker logs $container; done
```

Are you using a private CA signed certificate?

**Comment by Himansh-ilink** [comment]
I am using let'sencrypt certificate for rancher url.
I have tried above command and result is shcking me.
INFO: Environment: CATTLE_ADDRESS=10.42.68.198 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_FEATURES= CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=true CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-79657cc9c7-bqfdd CATTLE_SERVER=https://testrancherurl
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5
ERROR: https://testrancherurl/ping is not accessible (The requested URL returned error: 404)

i can able to ping my rancher domain from cluster vm, can you please help here, how i can solve this issue.

**Comment by superseb** [comment]
When you first login to the UI, you are setting the `server-url` which should be an FQDN that is resolvable via DNS. Is the ping from the cluster vm based on DNS or something else (like `/etc/hosts`)? What does manual resolving show against the cluster DNS? (`dig rancher.yourdomain.com @10.43.0.10`) vs what is on the host (`dig rancher.yourdomain.com`)

**Comment by superseb** [comment]
Any update on this?

**Comment by Himansh-ilink** [comment]
Today I will check and let you know about FQDN.

**Comment by superseb** [comment]
Let me know if this still needs investigating
