### ISSUE TITLE
airgap - rancher/rancher-operator:v0.1.0 is used but rancher/rancher-operator:v0.1.0-alpha8 is in the images.txt file

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29599]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- Install Rancher `v2.5.2-rc1` Airgap.
- Check the logs and Rancher will be trying to pull `rancher/rancher-operator:v0.1.0`

**Result:**

`Error syncing pod 80a1d956-ef65-45f8-bdb3-30ca650b229f ("rancher-operator-8667f7c985-48zcf_rancher-operator-system(80a1d956-ef65-45f8-bdb3-30ca650b229f)"), skipping: failed to "StartContainer" for "rancher-operator" with ImagePullBackOff: "Back-off pulling image \"<private_registry>/rancher/rancher-operator:v0.1.0\""`

**Other details that may be helpful:**

`rancher/rancher-operator:v0.1.0-alpha8` is in `rancher-images.txt`

`rancher-operator-system   rancher-operator-8667f7c985-48zcf   0/1     ImagePullBackOff   0          9m57s`

**Comment by cbron** [comment]
This looks like a duplicate of https://github.com/rancher/rancher/issues/29591  @izaac / @jiaqiluo

**Comment by jiaqiluo** [comment]
@cbron yep, the same symptom for a different image.

**Comment by mrajashree** [comment]
Can be tested with v2.5.2-rc3

**Comment by izaac** [comment]
Rancher version: `v2.5.2-rc3 (10/21/2020)`

rancher-images.txt has now `rancher/rancher-operator:v0.1.0`.
No errors in logs after fresh install as previously noticed.
