### ISSUE TITLE
Support multiple links to same service

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2959]
Rancher should support multiple alias to the same service as a link.

For example, I want to link Service B to Service A as alias C and alias D.  I should be able to resolve "C" and "D" to Service A from any containers in Service B.

**Comment by sangeethah** [comment]
Tested with server version - v0.50.0-rc1

We now have support multiple links to same service. 

Link Service B to Service A as alias C and alias D. 
From within the containers of service A , we are able use both C and D to resolve to containers of service B.

Metadata for service A , has information about only 1 alias - tracked in #3014
