### ISSUE TITLE
Helm charts with a '+' in the version string cause error in catalog syncing

### ISSUE THREAD

**Issue by MG2R** [rancher/rancher#29605]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Add a Helm Chart with a '+' in the version name to a Helm repo
2. Try to sync said repo as a catalog in Rancher Server

**Result:**
```
2020/10/15 12:14:53 [ERROR] CatalogController nexus [catalog] failed with : failed to update templates. Multiple error(s) occurred: [CatalogTemplateVersion.management.cattle.io "nexus-test-semver-0.0.2+test" is invalid: metadata.name: Invalid value: "nexus-test-semver-0.0.2+test": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')];
```

**Other details that may be helpful:**
This seems to be the same bug as reported (and reportedly fixed) in issue  #24863 .
That bugfix should be in v2.4.0, according to the [release notes](https://github.com/rancher/rancher/releases/tag/v2.4.0), I'm running v2.4.6 so this shouldn't be an issue anymore. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.6
- Installation option (single install/HA): HA

**Comment by acolliot** [comment]
Same here with v2.4.8 and Harbor registry
