### ISSUE TITLE
ca cannot auto update

### ISSUE THREAD

**Issue by minchieh-fay** [rancher/rancher#29607]
Useful | Info
-- | --
Versions | Rancher v2.4.3 UI: v2.4.3
env | offline
node | only one
docker | 19.03
regeister | private 

* step 1  
save rancher:v2.4.3 to my private regeister
``` shell
./rancher-save-images.sh
./rancher-load-images.sh hub.myPrivateRepo.io:8080
```

* step 2
``` shell
# one centos 7.8 host
date -s "2020-10-17"   # set to that right day(Last Friday Did)
```
* step 3
``` shell
# run rancher
 docker run -d --restart=unless-stopped \
	-p 9080:80 -p 9443:443 \
	--privileged \
	-v /var/deploy/rancher/data/:/var/lib/rancher/ \
	-e CATTLE_SYSTEM_DEFAULT_REGISTRY=hub.myPrivateRepo.io:8080 -e CATTLE_SYSTEM_CATALOG=bundled 
	hub.myPrivateRepo.io:8080/rancher/rancher:v2.4.3
``` 

* step 4
 open rancher web, `https://192.168.1.3:9443`,   it's works, and i set password to it, it's ok

* step 5
 ``` 
date -s "2021-10-15"   # set 363 days later to `2020-10-17`,  this day is `2020-10-17`
```

* step 6
 check web(`https://192.168.1.3:9443`), it's works ok

* step 7
Saturday and Sunday passed......

* step 8
todoy is Monday('2020-10-19'),   and the day of Rancher's node is '2021-10-17' (one year passed)
check web(`https://192.168.1.3:9443`),   **it cannot open!!!**

* step 9
ssh to Rancher's node, and run:
```
curl -k https://192.168.1.3:9443
curl -k  https://127.0.0.1:9443
# all is faild to connect, `server refused`
```
* step 10
look logs
```
docker logs {rancher/rancher containtd ID}
```
2021/10/17 16:00:53 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:00:53.121976 I | http: TLS handshake error from 127.0.0.1:53970: remote error: tls: bad certificate
2021/10/17 16:00:55 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:00:55.123008 I | http: TLS handshake error from 127.0.0.1:53972: remote error: tls: bad certificate
2021/10/17 16:00:57 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:00:57.124074 I | http: TLS handshake error from 127.0.0.1:53974: remote error: tls: bad certificate
2021/10/17 16:00:59 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:00:59.125200 I | http: TLS handshake error from 127.0.0.1:53976: remote error: tls: bad certificate
2021-10-17 16:01:01.126244 I | http: TLS handshake error from 127.0.0.1:53978: remote error: tls: bad certificate
2021/10/17 16:01:01 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:01:03.127417 I | http: TLS handshake error from 127.0.0.1:53980: remote error: tls: bad certificate
2021/10/17 16:01:03 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:01:05.128494 I | http: TLS handshake error from 127.0.0.1:53982: remote error: tls: bad certificate
2021/10/17 16:01:05 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:01:07.129503 I | http: TLS handshake error from 127.0.0.1:53984: remote error: tls: bad certificate
2021/10/17 16:01:07 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021/10/17 16:01:09 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:01:09.130630 I | http: TLS handshake error from 127.0.0.1:53986: remote error: tls: bad certificate
2021/10/17 16:01:11 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:01:11.131759 I | http: TLS handshake error from 127.0.0.1:53988: remote error: tls: bad certificate
2021-10-17 16:01:13.132939 I | http: TLS handshake error from 127.0.0.1:53990: remote error: tls: bad certificate
2021/10/17 16:01:13 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:01:15.134037 I | http: TLS handshake error from 127.0.0.1:53992: remote error: tls: bad certificate
2021/10/17 16:01:15 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021/10/17 16:01:17 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:01:17.135117 I | http: TLS handshake error from 127.0.0.1:53994: remote error: tls: bad certificate
2021-10-17 16:01:19.136097 I | http: TLS handshake error from 127.0.0.1:53996: remote error: tls: bad certificate
2021/10/17 16:01:19 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:01:21.137122 I | http: TLS handshake error from 127.0.0.1:53998: remote error: tls: bad certificate
2021/10/17 16:01:21 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:01:23.138376 I | http: TLS handshake error from 127.0.0.1:54000: remote error: tls: bad certificate
2021/10/17 16:01:23 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:01:25.139753 I | http: TLS handshake error from 127.0.0.1:54002: remote error: tls: bad certificate
2021/10/17 16:01:25 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:01:27.140916 I | http: TLS handshake error from 127.0.0.1:54004: remote error: tls: bad certificate
2021/10/17 16:01:27 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
2021-10-17 16:01:29.142155 I | http: TLS handshake error from 127.0.0.1:54006: remote error: tls: bad certificate
2021/10/17 16:01:29 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version?timeout=30s: x509: certificate has expired or is not yet valid
```

```

**Comment by kingsd041** [comment]
Rancher v2.4.8 has the same issue

**Comment by kingsd041** [comment]
It seems that it is caused by the expiration of the K3S certificate. I can manually update the K3S certificate through the following operations

```
docker exec -it rancher_server kubectl delete secret k3s-serving -n kube-system
docker exec -it rancher_server rm -rf /var/lib/rancher/k3s/server/tls/dynamic-cert.json
docker restart rancher_server
```

**Comment by minchieh-fay** [comment]
> It seems that it is caused by the expiration of the K3S certificate. I can manually update the K3S certificate through the following operations
> 
> ```
> docker exec -it rancher_server kubectl delete secret k3s-serving -n kube-system
> docker exec -it rancher_server rm -rf /var/lib/rancher/k3s/server/tls/dynamic-cert.json
> docker restart rancher_server
> ```

u are right, tks 
hope official solution

**Comment by olekuz** [comment]
the same for v2.4.4

**Comment by neozeed** [comment]
```
root@steady35:~# docker exec -it ff1694c08125 kubectl delete secret k3s-serving -n kube-system
Unable to connect to the server: x509: certificate has expired or is not yet valid

```

Guess it's drifted far too out of date by now.

**Comment by neozeed** [comment]
I got it working again:

```
docker exec -it docker_container -c "rm -rf /var/lib/rancher/k3s/server/tls/dynamic-cert.json"
docker exec -it docker_container -c "kubectl --insecure-skip-tls-verify=true delete secret k3s-serving -n kube-system"
docker exec -it docker_container -c "k3s kubectl --insecure-skip-tls-verify=true delete secrets -n kube-system k3s-serving"
docker exec -it docker_container -c "k3s kubectl --insecure-skip-tls-verify=true delete secrets -n cattle-system serving-cert"
docker restart docker_container
```
