### ISSUE TITLE
Unable to import/Add an existing Kubernetes cluster to Rancher [2.5.1]

### ISSUE THREAD

**Issue by allaboutopensource** [rancher/rancher#29614]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
I am trying to add/import a existing kubernetes cluster which is built using RKE into my rancher Environment. It ask me to run the below command to add the cluster to the rancher:

Run the kubectl command below on an existing Kubernetes cluster running a supported Kubernetes version to import it into: kubectl apply -f https://rancher.example.com/v3/import/sl9xvw8ftwgxqtr4n457l9mkp2gmw6zphkwdw87zbqc4zjwhkfgd2f.yaml

**Result:**

after running the above command i am getting an error:

Unable to connect to the server: x509: certificate is valid for ingress.local, not rancher.example.com

**Other details that may be helpful:**
the existing kubernetes cluster is running within VM on openstack environment .

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.1
- Installation option (single install/HA):HA mode

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Hosted on vmware esxi 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM with 8Gb ram and 8vcpus
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): 

```
[root@rke-node01 ~]# docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64

```

**Comment by rmweir** [comment]
Hello @allaboutopensource, is this an airgap with proxy setup by chance? If not then it looks like it is a setup issue with your certs.

**Comment by allaboutopensource** [comment]
yes, it was issue with the certs, i applied the cert and created the secret and everything looks fine.
