### ISSUE TITLE
[2.4 Backport] Add OCI meta handler API for OKE and OCI drivers

### ISSUE THREAD

**Issue by jlamillan** [rancher/rancher#29621]
**What kind of request is this (question/bug/enhancement/feature request):**

- Backport of https://github.com/rancher/rancher/pull/26963

We'd like to back-port the PRs required for the OKE and OCI drivers to fetch their UI values dynamically from the OCI API.

For Rancher server, this means pulling in the OCI metadata API to retrieve values for the UI.

Rancher Server PR (available in 2.5+): https://github.com/rancher/rancher/pull/26963
Rancher UI PR for OCI driver (available in 2.5+): https://github.com/rancher/ui/pull/3952
Rancher UI PR for OKE driver (available in 2.5+): https://github.com/rancher/ui/pull/3953

**Comment by jlamillan** [comment]
@deniseschannon

**Comment by aaronRancher** [comment]
Verified with Rancher server `rancher\rancher:v2.4-4037-head`

OCI cluster driver now populates available OS's dynamically:
![Screen Shot 2020-10-21 at 3 31 54 PM](https://user-images.githubusercontent.com/57409052/96799792-c1b97880-13b8-11eb-8b23-6ff2af69dd62.png)
OKE cluster driver now populates available OS's dynamically:
![Screen Shot 2020-10-21 at 3 36 37 PM](https://user-images.githubusercontent.com/57409052/96799793-c2eaa580-13b8-11eb-81c0-384022cce430.png)
