### ISSUE TITLE
Default k8s version for EKS clusters should be 1.18

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29624]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Currently The default k8s verison in EKS console while creating an eks cluster is 1.17.
- In Rancher - we have 1.18.

**Expected Result:**
The default k8s version is 1.17 while dpeloying a hosted EKS cluster

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4-head, 2.5head, master-head - latest UI
- Installation option (single install/HA): single

**Comment by deniseschannon** [comment]
We don't need to match our default k8s versions with the EKS console. I think it makes sense to move to the latest EKS version available.

**Comment by sowmyav27** [comment]
closing as per comments - https://github.com/rancher/rancher/issues/29624#issuecomment-714741332
