### ISSUE TITLE
Removal of rke-templates broke doc links

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#29631]
Below commit resulted in broken links in docs
https://github.com/rancher/rancher/commit/744202bd9ad8e2b370ddcef1ab7cb714ca15ea52

https://rancher.com/docs/rancher/v2.x/en/installation/resources/advanced/rke-add-on/layer-4-lb/
- (3319:4) 'Template..' => https://rancher.com/docs/rancher/v2.x/en/installation/options/cluster-yml-templates/3-node-certificate (HTTP 404)
- (3320:4) 'Template..' => https://rancher.com/docs/rancher/v2.x/en/installation/options/cluster-yml-templates/3-node-certificate-recognizedca (HTTP 404)

**Comment by ansilh** [comment]
Hi @cjellick , Please let me now if I can link this to 2.4.8 tag
Cc: @catherineluse

**Comment by cjellick** [comment]
Yeah, that would work. I cannot find the broken link when i visit that page. Maybe it was fixed already? Can you give me text to search for on the docs page so that I can find and click the broken link?

**Comment by catherineluse** [comment]
Yeah I fixed it already.

**Comment by ansilh** [comment]
Thanks @catherineluse
