### ISSUE TITLE
Upgrade instructions for 2.5 need to mention removing alerts/notifiers

### ISSUE THREAD

**Issue by al45tair** [rancher/rancher#29637]
**What kind of request is this (question/bug/enhancement/feature request):**
Documentation request.

**Steps to reproduce (least amount of steps as possible):**
Upgrade from Rancher 2.4 to 2.5 on a system that has alerts and notifiers configured.

**Result:**
You can't successfully disable monitoring, because the alerts and notifiers are configured, which causes Rancher to keep recreating the monitoring daemons even though monitoring is actually shown as disabled in the UI.

The upshot is that you can't then successfully enable the new monitoring system via the app in Cluster Explorer.

**Other details that may be helpful:**
Deleting all the alerts and notifiers (including project alerts and cluster alerts) resolves the problem. This should be mentioned in the documentation.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.1
- Installation option (single install/HA): HA

**Comment by aiyengar2** [comment]
@al45tair thanks for calling this out. We have added the documentation here https://github.com/rancher/docs/pull/2813, which shows up in https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/migrating/ to address this, so I'll close out this ticket.

On the same note, for any users who are looking for a way to check why Monitoring V1 doesn't appear to be disabled, disabling Monitoring V1 involves the following steps:
- Either 1) remove all Notifiers from the Notifier tab of the Cluster or 2) Navigate to each Alert tab (for the whole cluster and for each individual project) and remove any `recipients` under any of the Alert Groups that you have defined.
- On each project that has Project Monitoring enabled, disable it under the Monitoring tab of the Project
- Disable Cluster Monitoring by navigating to the Monitoring tab of the Cluster

The script at https://github.com/bashofmann/rancher-monitoring-v1-to-v2/pull/3 may help you audit why Monitoring V1 doesn't appear to be disabled.
