### ISSUE TITLE
Monitoring V2 - Grafana and Prometheus not working

### ISSUE THREAD

**Issue by benzman81** [rancher/rancher#29634]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable Cluster monitoring
- Try to access Grafana
- Try to access Prometheus Graph, Rules or Targets

**Result:**
- Encounter Bad Gateway (502) in Grafana dashboard
- Cannot open Prometheus Graph, Rules or Targets

**Other details that may be helpful:**
We use a custom cluster based on virtual machines. Previously it used to be rancher v2.3.0/k8s 1.14.x with old monitoring enabled. Now, we upgraded to rancher v2.5.1/k8s 1.19.3. We disabled the old monitoring, but some resources kept getting recreated as a message in the new monitoring install area (helm chart) in cluster explorer showed us. Back in cluster manager we then deleted all alerts and alert groupt everwhere and the notifiers. Afterward we removed the recreated ressources of old monitoring. Now, nothing was recreated anymore and the message in the new monitoring install area (helm chart) in cluster explorer was gone. After installing the helm chart the new monitoring was visible in cluster explorer, but all prometheus links cannot be opened (red disabled symbol) and when opening grafana all dashboard items show Bad Gateway (502).

Ressources seem to be all running:
```
NAME                                                      READY   STATUS    RESTARTS   AGE
pushprox-kube-controller-manager-client-2d9dp             1/1     Running   0          7m44s
pushprox-kube-controller-manager-client-bmvp5             1/1     Running   0          7m44s
pushprox-kube-controller-manager-client-jx2tw             1/1     Running   0          7m44s
pushprox-kube-controller-manager-client-qrntw             1/1     Running   0          7m44s
pushprox-kube-controller-manager-client-zhvtb             1/1     Running   0          7m44s
pushprox-kube-controller-manager-proxy-6df75f64bb-n2gl9   1/1     Running   0          7m44s
pushprox-kube-etcd-client-454gf                           1/1     Running   0          7m43s
pushprox-kube-etcd-client-5wcrp                           1/1     Running   0          7m44s
pushprox-kube-etcd-client-mtwhj                           1/1     Running   0          7m44s
pushprox-kube-etcd-client-qb7sc                           1/1     Running   0          7m43s
pushprox-kube-etcd-client-ts5hr                           1/1     Running   0          7m44s
pushprox-kube-etcd-proxy-7bf98f5cd-djv7g                  1/1     Running   0          7m44s
pushprox-kube-proxy-client-c4qxj                          1/1     Running   0          7m44s
pushprox-kube-proxy-client-cpxv9                          1/1     Running   0          7m44s
pushprox-kube-proxy-client-cwd5s                          1/1     Running   0          7m44s
pushprox-kube-proxy-client-fcb4p                          1/1     Running   0          7m43s
pushprox-kube-proxy-client-fj9qm                          1/1     Running   0          7m44s
pushprox-kube-proxy-client-ldpt4                          1/1     Running   0          7m44s
pushprox-kube-proxy-client-nqqzs                          1/1     Running   0          7m43s
pushprox-kube-proxy-client-stjxs                          1/1     Running   0          7m44s
pushprox-kube-proxy-client-xss28                          1/1     Running   0          7m44s
pushprox-kube-proxy-client-z2jc6                          1/1     Running   0          7m43s
pushprox-kube-proxy-proxy-cc7bfb666-rx8md                 1/1     Running   0          7m44s
pushprox-kube-scheduler-client-9b4d7                      1/1     Running   0          7m44s
pushprox-kube-scheduler-client-9ch2r                      1/1     Running   0          7m44s
pushprox-kube-scheduler-client-hs88z                      1/1     Running   0          7m44s
pushprox-kube-scheduler-client-s4l5d                      1/1     Running   0          7m44s
pushprox-kube-scheduler-client-zprl5                      1/1     Running   0          7m44s
pushprox-kube-scheduler-proxy-6c7598b646-vbwrg            1/1     Running   0          7m44s
rancher-monitoring-operator-5bf588db58-r7mqt              2/2     Running   0          7m44s
rancher-monitoring-prometheus-adapter-795d5d4f75-lsggd    1/1     Running   0          7m44s
rancher-monitoring-prometheus-node-exporter-dhr57         1/1     Running   0          7m43s
rancher-monitoring-prometheus-node-exporter-fwc6n         1/1     Running   0          7m43s
rancher-monitoring-prometheus-node-exporter-l8ndx         1/1     Running   0          7m43s
rancher-monitoring-prometheus-node-exporter-tstkb         1/1     Running   0          7m43s
rancher-monitoring-prometheus-node-exporter-tvkhn         1/1     Running   0          7m43s
rancher-monitoring-prometheus-node-exporter-v8hsn         1/1     Running   0          7m43s
rancher-monitoring-prometheus-node-exporter-vltpj         1/1     Running   0          7m43s
rancher-monitoring-prometheus-node-exporter-wtqlb         1/1     Running   0          7m43s
rancher-monitoring-prometheus-node-exporter-xd5mt         1/1     Running   0          7m43s
rancher-monitoring-prometheus-node-exporter-zp6j7         1/1     Running   0          7m43s
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.5.1/k8s 1.19.3
- Installation option (single install/HA):
Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Nodes have version from 17.9.1, 18.9.0 and 19.3.5
Rancher server is docker version 17.03.2-ce
```
[helm-operation-hh9xd_undefined.log](https://github.com/rancher/rancher/files/5406951/helm-operation-hh9xd_undefined.log)
![2020-10-19 19_55_31-Home - Grafana](https://user-images.githubusercontent.com/14224592/96553643-bdf0fd80-12b5-11eb-982c-9c01d91c3f91.png)
![2020-10-19 19_59_53-Dashboard](https://user-images.githubusercontent.com/14224592/96553757-eaa51500-12b5-11eb-95a2-4768c17e2eae.png)

**Comment by benzman81** [comment]
Looking at the pvc's I can see that the volume is not created. We use the nfs-client-provisioner that prints out the message `failed to provision volume with StorageClass "nfs-client": claim Selector is not supported`. I will check further and give feedback here. Might be releated to https://github.com/helm/charts/issues/11707

**Comment by benzman81** [comment]
Ok, that was it. I removed everything again. Now, when before hitting the **install** button I clicked **Edit as yaml** and removed the selector part from the storageSpec. Then it installs correctly and the volume gets bound using the  nfs storage.

**Comment by benzman81** [comment]
closed as this seems to be a bug in nfs client provisioner

**Comment by sotoz** [comment]
I also have the same problem. Removing the selector part from storageSpec didn't resolve the issue.

**Comment by aiyengar2** [comment]
Related: https://github.com/rancher/rancher/issues/29839#issuecomment-719817302

@sotoz please open up a new issue if you are still encountering a bug!
