### ISSUE TITLE
GKE - Create cluster throwing invalid projectID with json key

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29646]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install Rancher v2.5.2-rc2 or master-head
- Try to start provisioning a GKE cluster and read from File the json key

**Result:**

![Screen Shot 2020-10-20 at 10 51 12 AM](https://user-images.githubusercontent.com/27659/96625259-cb60b480-12c2-11eb-9f3b-4a0079e28741.png)

**Environment information**
- Rancher version: `v2.5.2-rc2` and `master-head (10/20/2020)` _298a206_
- Installation option: HA

**Comment by izaac** [comment]
This is not reproducible in `v2.5.1`

**Comment by rmweir** [comment]
@westlywright Looks like this is caused by this commit in rancher/ui: https://github.com/rancher/rancher/issues/29646

**Comment by izaac** [comment]
Rancher version: `v2.5-head (10/22/2020)` _1599dc1_
Rancher version: `master-head (10/22/2020)` _a3a4c87_

I validated I now can create GKE clusters from the Rancher Ember UI. No more errors.
