### ISSUE TITLE
Upgrade Logging Operator to 3.7.3

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#29642]
https://github.com/banzaicloud/logging-operator/releases/tag/3.7.0

**Comment by izaac** [comment]
Rancher version `v2.5-head (11/17/2020)` _9a67809_
Rancher version `master-head (11/17/2020)` _90cdb6d6d_

Logging chart version: `3.7.301`

P1 test cases executed while testing this other Windows issue #28720
