### ISSUE TITLE
Rancher set up with Terraform reports "repository does not exist or may require 'docker login': denied: requested access to the resource is denied" when repository exists and permissions are provided

### ISSUE THREAD

**Issue by l-x-u** [rancher/rancher#29641]
**What kind of request is this (question/bug/enhancement/feature request):** question, bug(?)

**Steps to reproduce (least amount of steps as possible):**

Configure a registry secret using terraform like so, using valid credentials which are confirmed to work with docker hub:

```
resource "rancher2_registry" "foo" {
  provider = rancher2.admin
  name = "foo"
  description = "Foo Docker Registry"
  project_id = data.rancher2_project.default.id
  registries {
    address = "docker.io"
    username = "foo"
    password = var.docker_hub_password
  }
}

```

Deploy a Rancher App using the `rancher2_app` resource with the following contained in its chart's `Deployment`'s `spec.template.spec`:

```
      imagePullSecrets:
      - name: foo
```

**Result:** Despite the appropriate configuration, rancher reports the following:

```
ErrImagePull:  rpc error: code = Unknown desc = Error response from daemon: pull access  denied for xxxxxx/xxx:xx, repository does not exist or may  require 'docker login': denied: requested access to the resource is  denied
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.8
- Installation option (single install/HA): HA

**Comment by TechCanuck** [comment]
This is a doc mismatch that we tripped over this week.  Update your registry address to be "index.docker.io" instead of  "DockerHub".

**Comment by h0jeZvgoxFepBQ2C** [comment]
Is this issue related also to the digital ocean setup? https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/digital-ocean-qs/

I want to use a private registry in namespaces, but can't make it work at all, I always get the error message, independent if I use "DockerHub", custom with docker.io, index.docker.io,... 

No idea how to make this running?
