### ISSUE TITLE
Error Provisioning Cluster - Cluster health check failed: cluster agent is not ready

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29652]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- Install v2.5.2-rc2, v2.5-head or master-head
- Try to provision a custom or RKE cluster

**Result:**

Agents are in active state but the cluster shows this error

`Cluster health check failed: cluster agent is not ready`

![Screen Shot 2020-10-20 at 9 45 40 AM](https://user-images.githubusercontent.com/27659/96640082-82ffc180-12d7-11eb-86bb-b44fa16eaa2b.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version: `v2.5.2-rc2
- Installation option: HA RKE k8s `byo-valid` certificates option

**Comment by izaac** [comment]
At first I thought this was #29620 but here the nodes are Active but the cluster is in Error state.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head

Kubelet logs on one of my clusters' controlplane nodes are showing:
```
E1020 20:13:23.157228   12224 pod_workers.go:191] Error syncing pod ee7e29e6-ebee-4c9a-8448-8f6051466c0a ("cattle-cluster-agent-67dc69955d-nktfm_cattle-system(ee7e29e6-ebee-4c9a-8448-8f6051466c0a)"), skipping: failed to "StartContainer" for "cluster-register" with CrashLoopBackOff: "back-off 5m0s restarting failed container=cluster-register pod=cattle-cluster-agent-67dc69955d-nktfm_cattle-system(ee7e29e6-ebee-4c9a-8448-8f6051466c0a)"
I1020 20:13:24.001867   12224 setters.go:77] Using node IP: "172.31.11.103"
```

**Comment by Himansh-ilink** [comment]
I am also facing this issue in my cluster,  can someone please look into it from rancher team.**This cluster is currently Error; areas that interact directly with it will not be available until the API is ready.

Cluster health check failed: cluster agent is not ready**

**Comment by izaac** [comment]
Rancher version: `master-head (10/21/2020)` _0390ff5_

Letsencrypt and byo-valid certs install methods worked fine now.
I was able to provision Custom and Driver RKE clusters.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `56bf444`**

- Deployed a DO cluster - 1 etcd, 1 control and 2 worker nodes.
- Cluster has come up active

**Comment by izaac** [comment]
Rancher version: `v2.5-head` _61a8a36_ HA k8s

All 4 certificate installation options are working.
Deployed custom cluster with 1 control plane, 1 etcd, 3 workers.

All downstream clusters came up in Active state.

**Comment by Himansh-ilink** [comment]
Hello,
Rancher 2.5.1 cattle-cluster-agent is crashing continously. Below are kubelet error.
 Error syncing pod 050443da-1b74-4852-bbdf-fbd6c037fbaa ("cattle-cluster-agent-67bb5d68bb-cxm2j_cattle-system(050443da-1b74-4852-bbdf-fbd6c037fbaa)"), skipping: failed to "StartContainer" for "cluster-register" with CrashLoopBackOff: "back-off 2m40s restarting failed container=cluster-register pod=cattle-cluster-agent-67bb5d68bb-cxm2j_cattle-system(050443da-1b74-4852-bbdf-fbd6c037fbaa)"

**Comment by zzbmmbzz** [comment]
I got same error:
```
E1102 08:03:06.972523    4586 pod_workers.go:191] Error syncing pod 361262a0-e783-48a8-8884-cb669f49a52e ("cattle-cluster-agent-6c65467b77-fnglv_cattle-system(361262a0-e783-48a8-8884-cb669f49a52e)"), skipping: failed to "StartContainer" for "cluster-register" with CrashLoopBackOff: "back-off 5m0s restarting failed container=cluster-register pod=cattle-cluster-agent-6c65467b77-fnglv_cattle-system(361262a0-e783-48a8-8884-cb669f49a52e)"
```

**Comment by zhaoge26** [comment]
I also got this error, I found dns error in k8s_coredns_coredns, I used a custom domain as url, but i didn't resolve it. after I added the dns setting, worked...

**Comment by karkul** [comment]
hi @zhaoge26 how did you do that? can you share us your notes? I'm using IP Address I mean I'm not using any DNS configuration. Thanks
