### ISSUE TITLE
Login to Active Directory fails with error code 500

### ISSUE THREAD

**Issue by ranchersvet** [rancher/rancher#29653]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Install Rancher, set up AD authentication.
Sometimes AD authentication fails with error code 500. Deleting the user from rancher UI resolves the problem and the user can log in again.

Relevant Rancher logs:
2020/10/14 17:34:53 [ERROR] API error response 500 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: can't find unique user for principal activedirectory_user://CN=peng,CN=Users,DC=w,DC=pdtpartners,DC=com
2020/10/14 17:36:09 [ERROR] API error response 500 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: can't find unique user for principal activedirectory_user://CN=peng,CN=Users,DC=w,DC=pdtpartners,DC=com
2020/10/14 17:38:30 [ERROR] API error response 500 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: can't find unique user for principal activedirectory_user://CN=peng,CN=Users,DC=w,DC=pdtpartners,DC=com

Rancher 2.4.5
gz#12832
gz#14705

**Comment by khuedoan** [comment]
I'm experiencing the same issue with Rancher 2.4.8

**Comment by maggieliu** [comment]
Refinement notes: 
* W/o a consistent reproduction scenario it will be hard to find the root cause.
* Need more logs
* One possible thing is look at what data is stored when user is first created and what happens when the user is deleted to see if there is anything that could go wrong when creating the user and if anything is re-used.
