### ISSUE TITLE
Rancher Webhook - installable on hardened cluster

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29651]
Allow installation for rancher webhook on hardened cluster

**Comment by StrongMonkey** [comment]
Can this be tested along with https://github.com/rancher/rancher/issues/29696? I think rancher-webhook works in hardened cluster.

**Comment by jiaqiluo** [comment]
This is validated on rancher:v2.5.4-rc1 

Steps:
- follow the documentation to prepare a hardened cluster by using RKE CLI rancher.com/docs/rancher/v2.x/en/security/rancher-2.4/hardening-2.4
- install Rancher v2.5.4-rc1  into the cluster
Results:

<img width="1515" alt="Screen Shot 2020-12-04 at 11 56 57 AM" src="https://user-images.githubusercontent.com/6218999/101214835-ecdeeb00-3639-11eb-8551-4e882555d745.png">
