### ISSUE TITLE
Container Labels Not Removing

### ISSUE THREAD

**Issue by michlaustn** [rancher/rancher#2965]
Hello,

When I set a label on an application, it is active for the application.  However on the next stop/start/restart of the container the label has gone from the application.  An example of this being the ```io.rancher.container.pull_image``` label.  I set this to always so that it will use the latest version of the image in the registry, however on the next restart the label is gone.

Component	Version
Rancher	v0.49.0
Cattle	v0.119.0
User Interface	v0.70.0
Rancher Compose	v0.6.0

Thanks.

**Comment by deniseschannon** [comment]
I am unable to reproduce.

Steps I tried:
1. Add a service with either using the checkbox for "pull image always" or explicit label (`io.rancher.container.pull_image=always`). 
2. Try to start/stop/restart the container and the label is still there. Try to start/stop/restart the service, the label is still there.

**Comment by michlaustn** [comment]
If I select a running service e.g. named web.  Then I use the upgrade option to set a new label on the service e.g. ```io.rancher.container.pull_image```, save and finish the upgrade.  If I then restart the service the latest image is correctly downloaded and used.  However if I then make another amendment to the image and push a new one up and restart the service again, it does not download the latest image.  Going back to the upgrade option again I can no longer see the label that was set.  If I set it again and restart the service then the image is updated to the latest one I just pushed.

**Comment by michlaustn** [comment]
I should also add that, during testing a moment ago.  I amended my image to install an additional php module and pushed.  I tested this locally and could see the php module installed.  I proceeded to restart the Rancher web service for it to download the latest image. Upon testing the container I could not see the module installed.

Checking from the Rancher ui I could not see the label set.  It was only visible when viewing via the api.  For the image to be pulled down, I need to set the label again via the ui, upgrade and restart the effected service.

**Comment by michlaustn** [comment]
Exporting the config also does not include the labels after a restart.  I must add the label back in and then export for the compose files to include the label.

**Comment by deniseschannon** [comment]
What version of Rancher are you using? 

It sounds like you have this issue where cloning/upgrading was removing the system labels.  https://github.com/rancher/rancher/issues/2342

In Rancher v0.49.0+, we've added places in the UI to support the labels.  https://github.com/rancher/rancher/issues/2550

**Comment by michlaustn** [comment]
We upgraded to the latest release but still seem to be having the same issues;

Component	Version
Rancher	v0.49.1
Cattle	v0.121.0
User Interface	v0.71.0
Rancher Compose	v0.6.1

**Comment by deniseschannon** [comment]
Are you using the labels or the actual UI equivalent components? 

For `io.rancher.container.pull_image`, there is an equivalent checkbox under the image name to allow you request to always pull. You need to use the UI equivalents to get have the label always be set.

**Comment by deniseschannon** [comment]
@michlaustn Please re-open if you are still having issues. As I mentioned, you would need to use the UI equivalents when upgrading/cloning and cannot use the actual label in the labels section.
