### ISSUE TITLE
Allow rancherd upgrades using system-upgrade-controller

### ISSUE THREAD

**Issue by MonzElmasry** [rancher/rancher#29658]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request
just like k3s and rke2, rancherd needs to support upgrades using system-upgrade-controller

Needed steps : 

- [x] Create rancher/rancherd-upgrade repo for upgrade images
- [ ] Add dispatch in rancher/rancher to target rancherd-upgrade repo on new releases https://github.com/rancher/rancher/pull/29659

**Comment by davidnuzik** [comment]
There are some concerns on the UX of this manner of upgrades. For now, we are going to table this.

**Comment by davidnuzik** [comment]
Closing. We are no longer going down this path for rancherd upgrades.
