### ISSUE TITLE
How to adjust the node fault detection interval setting of cluster

### ISSUE THREAD

**Issue by bao2314483** [rancher/rancher#29669]
I want to set up the k8s cluster configuration
- --node-monitor-period="5s" .
- --node-monitor-grace-period: "10s"
- --node-startup-grace-period: "10s" 
- --pod-eviction-timeout: "5s"

But I don't know how to set it 
By Rancher2.4.8

**Comment by superseb** [comment]
Please see https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#cluster-config-file and https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/ and https://rancher.com/docs/rke/latest/en/example-yamls/. Let us know if this doesn't work or if you run into any issue.
