### ISSUE TITLE
UI warning when deleting a node in a 2 node cluster

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29665]
related to this: https://github.com/rancher/rancher/issues/24547#issuecomment-700783389

**Comment by sadiapoddar** [comment]
Tested with 2.5.-head, v2.5-100198aff107b9a0feccdcc3e6fb5b57e83f1fd7-head
Currently, we don't issue a warning if the etcd node of a two nodes cluster is deleted. 
Reproduced the issue.
1. Created a 2 nodes (all roles enable) cluster
2. Determine the etcd leader node
3. Deleted the etcd leader node and note UI didn't issue any warning
<img width="1335" alt="Screen Shot 2020-11-04 at 2 53 31 PM" src="https://user-images.githubusercontent.com/72409237/98177472-8edeac80-1eaf-11eb-9139-ce98175a1b21.png">


When the fix will be available, will verify that users get a warning in UI

**Comment by sadiapoddar** [comment]
The fix is working as expected, closing the isse
