### ISSUE TITLE
After starting Rancher server, there is an admin account `1a1` that is visible

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2967]
v0.49.0

Steps to Reproduce:

1. Launch Rancher Server
2. Go to accounts tab

Result: There is an admin account that has the ID of `1a1`. This is confusing as it makes it seem like there is some admin floating around. This account remains even after authentication. If this is deactivated/deleted, will there be issues?

Expected Result: This admin account shouldn't be shown if it's only used internally.

**Comment by hibooboo2** [comment]
That Account Is always there, not always used but not removed as if a user uses no auth but has apikeys then turns on auth we want apikeys to continue to work,

**Comment by hibooboo2** [comment]
Also default project Belongs to 1a1

**Comment by deniseschannon** [comment]
So as a new user, what would happen if i deactivate/delete it when auth is on, or before we turn on auth? I haven't done those test cases, but if Rancher is going to break because of that, we need to either hide it or disable the ability to remove.

**Comment by deniseschannon** [comment]
I tried to deactivate the account (as the API allows you to do so) and it basically made my Rancher setup unusable. It got stuck in "Deactivating" and when I try to refresh, I just get "Error" page. We need to at least not allow users to deactivate/delete this account if we make it visible.

**Comment by hibooboo2** [comment]
It depends on the setup you are using. If you are using a new setup it should be fine. But it it is a longrunning one that has upgraded it may have it so that the person logged in is actually 1a1.

**Comment by deniseschannon** [comment]
It was a new set up.

**Comment by deniseschannon** [comment]
Verified with v1.0.0-rc1 that 1a1 is no longer able to be removed if it's the last (and required) admin.
