### ISSUE TITLE
Canal not starting properly  , fresh install 

### ISSUE THREAD

**Issue by tabnul** [rancher/rancher#29670]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Either upgrade rancher to 2.5.1 and kubernetes to v1.19.3-rancher1-1 , or do a fresh install of the same products.

**Result:**
Canal will not be able to start properly, 2 out of 3 masters won't start  , with the errormessage;

```
2020-10-21 14:47:27.561 [WARNING][8] startup/startup.go 1106: Calico node 'k8s2master1' is already using the IPv4 address 172.18.0.1.
2020-10-21 14:47:27.561 [WARNING][8] startup/startup.go 1310: Terminating
```

**Other details that may be helpful:**
I had this issue both after an upgrade, and after a fresh install.
Upgrade came from rancher 2.4.5 and kubernetes 1.18.6.

I was able to fix this specific issue on my old upgraded setup by removing Canal, and installing Calico manually with the option;
IP_AUTODETECTION_METHOD=reacheabledestination
Apparently there is an issue with the selection of the NIC.

However this new canal installation broke my old setup (problems with cattle services) hence my fresh install.... which has the same issue now.
I tried setting the variable manually but this did not work either. I am not going to reinstall calico this time because dont want to start over again. Also tried this, but didnt work unfortunately;
kubectl set env daemonset/canal -n kube-system IP_AUTODETECTION_METHOD=reacheabledestination

**Environment information**
- Rancher version 2.5.1
- Installation option (single install/HA): HA, 3 master, 2 slaves.
- Ubuntu 18.0.4 LTS

**Cluster information**
- Cluster type RKE, launched by Rancher 2.5.1
- Machine type Proxmox VMs, 6x 8GB / 4 cores AMD64
- Kubernetes version v1.19.3-rancher1-1
- Docker version: 19.03.8

**Comment by tabnul** [comment]
duplicate https://github.com/rancher/rancher/issues/29441

**Comment by tabnul** [comment]
I found a workaround, in fact its almost the same as in the description but without the typo.

kubectl set env daemonset/canal -n kube-system IP_AUTODETECTION_METHOD=can-reach=10.100.1.5

where 10.100.1.5 should be an ip adress preferable in your LAN that can be used as a valid destination to select the right NIC to listen on.

Quite sure its a bug in either rancher or RKE but this is a workaround for the time being.

**Comment by superseb** [comment]
This went from v3.13.4 to v3.16.1, so we need to check what has been changed between these releases regarding `IP_AUTODETECTION_METHOD`. Does it always 100% work on v2.4.x and never works in v2.5.x? Because it seems the default is `first-found` which should fail on the older version as well (or something changed in the behavior of it). Can you share the output of `ip addr show` and/or `ifconfig` from the host?

**Comment by superseb** [comment]
Lets actually move this to https://github.com/rancher/rancher/issues/29441
