### ISSUE TITLE
Certify RKE2 for SAP

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29673]

**Comment by rawmind0** [comment]
RKE2 sap di approval has been started by suse sap team. 

Investigating reported RKE2 issue related to https://github.com/kubernetes/kubernetes/issues/96980

**Comment by rawmind0** [comment]
RKE2 has been certified at April 13th 2021!

These are the published sap notes:
* https://launchpad.support.sap.com/#/notes/2871970 - [sap_note_3038897_rke2_di31.pdf](https://zube.io/files/rancher/2e95bbd10cd49e0e6a9c74b3b6c93664-sap_note_3038897_rke2_di31.pdf)
* https://launchpad.support.sap.com/#/notes/3038897 - [sap_note_2871970_di31_prereqs.pdf](https://zube.io/files/rancher/d4a4ee1235b197c813555cfcd07de2c2-sap_note_2871970_di31_prereqs.pdf)
