### ISSUE TITLE
If a registry is deleted, another one with the same address cannot be added

### ISSUE THREAD

**Issue by wundram** [rancher/rancher#2968]
If we delete a custom registry pointing to a name, like some.thing.com, delete it, (remove and purge), and then try and create a new registry in the same environment with the name some.thing.com, it fails with a ServerAddressUsed error.   The underlying API is returning code 400.

**Comment by deniseschannon** [comment]
Reproduced with v0.49.0

**Comment by sangeethah** [comment]
Tested with server version - v0.50.0-rc1

Add a custom registry pointing to a name, like some.thing.com, 
Delete and purge it.
Try and create a new registry in the same environment with the name some.thing.com.
Able to create the registry successfully.
