### ISSUE TITLE
Unable to deploy on AWS with Quickstart / Terraform

### ISSUE THREAD

**Issue by mrethers** [rancher/rancher#29682]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Follow the steps on AWS quickstart doc

**Result:**
Failed running cluster err:[Failed to create Certificates deployer container on host [18.207.137.140]: Failed to create Docker container [cert-deployer] on host [18.207.137.140]: Error response from daemon: create \/etc/kubernetes: "\\/etc/kubernetes" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path]
========================================

  on ..\rancher-common\rke.tf line 4, in resource "rke_cluster" "rancher_cluster":
   4: resource "rke_cluster" "rancher_cluster" {

**Other details that may be helpful:**

**Environment information**
Using rancher quickstart commit 453ba69c0c813599941a4b28a1b55f77a75b585c (latest)

**Comment by superseb** [comment]
What OS are you running?

**Comment by mrethers** [comment]
Windows 10 Pro

**Comment by superseb** [comment]
This should be solved by bumping to version as verified in https://github.com/rancher/terraform-provider-rke/issues/248#issuecomment-705015987, let me know if this doesn't work for you.

**Comment by superseb** [comment]
Let me know if this doesn't solve the issue.
