### ISSUE TITLE
Provisioning failing when using Rancher OS

### ISSUE THREAD

**Issue by sandeep444033** [rancher/rancher#29680]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug
**Steps to reproduce (least amount of steps as possible):**

Install RKE UI version v2.5.1.
Create a node template with VM template as RKE OS version v1.5.6.
Then imitate a cluster creation for Rancher UI with vSphere node driver.

**Result:**
On Rancher UI the cluster creation hangs waiting for ssh to be available,

2020/10/21 19:45:26 [INFO] [node-controller-rancher-machine] Waiting for machine to be running, this may take a few minutes...
2020/10/21 19:45:26 [INFO] [node-controller-rancher-machine] Detecting operating system of created instance...
2020/10/21 19:45:26 [INFO] [node-controller-rancher-machine] Waiting for SSH to be available...

[root@rancher ~]# tail -f /var/log/messages
Oct 21 19:46:55 rancher sshd[2139]: Connection closed by authenticating user docker 172.29.239.200 port 49242 [preauth]
Oct 21 19:46:59 rancher sshd[2141]: Connection closed by authenticating user docker 172.29.239.200 port 49254 [preauth]
Oct 21 19:47:03 rancher sshd[2143]: Connection closed by authenticating user docker 172.29.239.200 port 49264 [preauth]
Oct 21 19:47:03 rancher su: + pts/0 root:root
Oct 21 19:47:06 rancher sshd[2148]: Connection closed by authenticating user docker 172.29.239.200 port 49278 [preauth]
Oct 21 19:47:10 rancher sshd[2150]: Connection closed by authenticating user docker 172.29.239.200 port 49294 [preauth]
Oct 21 19:47:14 rancher sshd[2152]: Connection closed by authenticating user docker 172.29.239.200 port 49310 [preauth]
Oct 21 19:47:17 rancher sshd[2155]: Connection closed by authenticating user docker 172.29.239.200 port 49322 [preauth]
Oct 21 19:47:21 rancher sshd[2157]: Connection closed by authenticating user docker 172.29.239.200 port 49330 [preauth]
Oct 21 19:47:25 rancher sshd[2159]: Connection closed by authenticating user docker 172.29.239.200 port 49348 [preauth]
Oct 21 19:47:28 rancher sshd[2162]: Connection closed by authenticating user docker 172.29.239.200 port 49360 [preauth]

Actually the node is up and when I ssh in to it and tail on /var/log/messages I see the following,

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
RKE UI version v2.5.1.
- Installation option (single install/HA):
Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by montysinha7** [comment]
I have the sane issue, please advise if this issue was ever resolved.

**Comment by sandeep444033** [comment]
@montysinha7 

The issue still persists.
