### ISSUE TITLE
Digital Ocean Managed Kubernetes (dok8s) provision failure with manual installation

### ISSUE THREAD

**Issue by leebenson** [rancher/rancher#29697]
I'm not sure whether this is a Digital Ocean issue, or something with `rancher-latest/rancher`, but I'm consistently getting errors attempting to install Rancher on a DO Managed Kubernetes cluster following the [Rancher installation docs](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/) irrespective of machine config or zone.

Installing Rancher seems to intermittantly take down the whole cluster. Errors are described below.

### Error

After installation, a dump of active pods typically shows something like the following:

```
➜  site git:(main) kubectl get pods --namespace cattle-system
NAME                       READY   STATUS      RESTARTS   AGE
helm-operation-dcrc9       2/2     Running     0          115s
helm-operation-x2b4m       2/2     Running     0          3m36s
helm-operation-zxdjc       0/2     Completed   0          4m15s
rancher-699975f4b7-4xlfw   1/1     Running     0          5m53s
rancher-699975f4b7-7l87l   1/1     Running     1          5m53s
rancher-699975f4b7-px55h   1/1     Running     1          5m53s
```

But after multiple runs, eventually surfaces errors, typically with one of the three deployed Rancher containers:

```
➜  site git:(main) kubectl get pods --namespace cattle-system
NAME                       READY   STATUS      RESTARTS   AGE
helm-operation-dcrc9       2/2     Running     0          6m23s
helm-operation-x2b4m       2/2     Running     0          8m4s
helm-operation-zxdjc       0/2     Completed   0          8m43s
rancher-699975f4b7-4xlfw   0/1     Error       1          10m
rancher-699975f4b7-7l87l   0/1     Running     2          10m
rancher-699975f4b7-px55h   1/1     Running     1          10m
```

Note the error on `rancher-699975f4b7-4xlfw` in this case.

After several more minutes, I get intermittent connections errors that seem to affect all infrastructure, not just retrieving pods:

```
➜  site git:(main) kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout
```

This continues for the life of the cluster.

## Eventual (semi)-stability

After some hours, a deployed Rancher cluster _occasionally_ settles down; the latest attempt shows:

```
➜  site git:(main) kubectl get pods --namespace cattle-system                                                          
NAME                              READY   STATUS    RESTARTS   AGE
rancher-699975f4b7-4xlfw          1/1     Running   24         12h
rancher-699975f4b7-7l87l          1/1     Running   24         12h
rancher-699975f4b7-px55h          1/1     Running   24         12h
rancher-webhook-669d998d9-grftr   1/1     Running   0          11h
```

Note the 24 restarts!

This isn't always the case. Sometimes clusters time out for life. The maximum number of days I've kept a cluster alive to assess progress is 3.

Probing a little further with:

```bash
kubectl logs rancher-699975f4b7-px55h -c rancher --previous --namespace cattle-system
```

Yields:

```
2020/10/21 21:51:24 [INFO] Rancher version v2.5.1 (eb990af66) is starting
2020/10/21 21:51:24 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:true AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Agent:false Features:}
2020/10/21 21:51:24 [INFO] Listening on /tmp/log.sock
2020/10/21 21:51:54 [INFO] Waiting for server to become available: Get "https://10.245.0.1:443/version?timeout=15m0s": dial tcp 10.245.0.1:443: i/o timeout
2020/10/21 21:52:26 [INFO] Waiting for server to become available: Get "https://10.245.0.1:443/version?timeout=15m0s": dial tcp 10.245.0.1:443: i/o timeout
2020/10/21 21:52:58 [INFO] Waiting for server to become available: Get "https://10.245.0.1:443/version?timeout=15m0s": dial tcp 10.245.0.1:443: i/o timeout
2020/10/21 21:53:30 [INFO] Waiting for server to become available: Get "https://10.245.0.1:443/version?timeout=15m0s": dial tcp 10.245.0.1:443: i/o timeout
2020/10/21 21:54:02 [INFO] Waiting for server to become available: Get "https://10.245.0.1:443/version?timeout=15m0s": dial tcp 10.245.0.1:443: i/o timeout
2020/10/21 21:54:02 [FATAL] startup canceled
```

## VM config

I've tried with 2-3 nodes, each with at least 2 vCPUs, 8GB RAM per node, and ample disk space (120GB per.)

## Installation config

I used the following options to install. Note that TLS has been set to external. Typically, I'd deploy a k8s `LoadBalancer` separately to connect a DO SSL certificate ID with their managed load balancer, to point to the cluster.

This has historically worked well, but I don't get that far in this config due to the cluster being up and down:

```bash
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=<host> \
  --set tls=external
```

### `kubectl` version

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### **What kind of request is this (question/bug/enhancement/feature request):**

Question/bug -- not sure!

### Rancher version

Latest Rancher via `rancher-latest/rancher`

### Installation option (single install/HA):

Deployed to a managed Digital Ocean Kubernetes cluster, via [the official Rancher installation docs](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/), using `tls=external` and avoiding the cert-manager setup.

### Docker version (use `docker version`):

N/A / Unknown

**Comment by maggieliu** [comment]
@sowmyav27 Can you test installing Rancher on DO Managed Kubernetes cluster and see what is the error.

**Comment by jiaqiluo** [comment]
Rancher v2.5.1 is installed successfully into a Digital Ocean Managed K8S cluster. 

Steps:
- create a k8s cluster in DO
![image](https://user-images.githubusercontent.com/6218999/98422768-dd27b300-2049-11eb-88e5-6498eef86659.png)

```
> k version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- install the Ingress Controller via DO's management panel 
<img width="1246" alt="Screen Shot 2020-11-06 at 4 06 06 PM" src="https://user-images.githubusercontent.com/6218999/98422858-1cee9a80-204a-11eb-84ba-2889df309a54.png">

```
>  helm list -n ingress-nginx 
NAME         	NAMESPACE    	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
nginx-ingress	ingress-nginx	1       	2020-11-06 22:38:17.842100025 +0000 UTC	deployed	ingress-nginx-2.1.0	0.32.0
```

A load balancer is created by the ingress controller. 
 
- Install Cert-Manager
```
>  helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.0.4 \
  --set installCRDs=true
```

- Prepare the DNS name which points to the load balancer
- Install Rancher v2.5.1
```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=<redacted>
```

Results:
- Rancher is installed successfully, and the UI is accessible from the above hostname
```
helm list -n cattle-system 
NAME           	NAMESPACE    	REVISION	UPDATED                                	STATUS  	CHART                        	APP VERSION
rancher        	cattle-system	1       	2020-11-06 15:43:56.868167 -0700 MST   	deployed	rancher-2.5.1                	v2.5.1
rancher-webhook	cattle-system	1       	2020-11-06 22:45:39.773448536 +0000 UTC	deployed	rancher-webhook-0.1.0-beta500	0.1.0-beta5
```

```
> k get pods -n cattle-system
NAME                              READY   STATUS      RESTARTS   AGE
helm-operation-4wxzz              0/2     Completed   0          31m
helm-operation-6nb8w              0/2     Completed   0          30m
helm-operation-g5b5v              0/2     Completed   0          28m
helm-operation-k5krf              0/2     Completed   0          30m
helm-operation-l2jtw              0/2     Completed   0          30m
helm-operation-r9m8f              0/2     Completed   0          30m
rancher-66d4d887f6-8fhqb          1/1     Running     0          31m
rancher-66d4d887f6-r79v9          1/1     Running     1          31m
rancher-66d4d887f6-s8fwx          1/1     Running     0          31m
rancher-webhook-669d998d9-85kcw   1/1     Running     0          30m
```

- A downstream cluster using EC2 instance is provisioned successfully 

![image](https://user-images.githubusercontent.com/6218999/98423331-90dd7280-204b-11eb-8bc5-1ad3506a8bd1.png)
