### ISSUE TITLE
Hosted Rancher is not able to manage downstream cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29690]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a rancher server - 2.4.8 - will be the rancher hosting other rancher clusters - HA setup
- Deploy another imported k3s cluster. And install Rancher in this cluster in 2.5.1
- Upgrade the rancher in this ^^^ to 2.5.2-rc3
- The downstream cluster in the hosted Rancher becomes Unavailable

<img width="1442" alt="Screen Shot 2020-10-21 at 7 22 11 PM" src="https://user-images.githubusercontent.com/26032343/96816767-becb8180-13d2-11eb-8497-ace3c1fc03fd.png">

**Expected Result:**
Hosted Rancher should be able to manage downstream cluster. 

**Other details that may be helpful:**
cattle cluster agent and node agents have been removed here -  https://github.com/rancher/rancher/issues/29397

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.2-rc3
- Installation option (single install/HA): HA

**Comment by dnoland1** [comment]
Issue caused by cattle node and cluster agents getting removed in downstream cluster. Could be related to https://github.com/rancher/rancher/commit/8a6d0a940f06b2a8c415dd47bfd8cad80cb10d53

**Comment by ibuildthecloud** [comment]
I'm not totally sure how to fix this issue. So on upgrade we will delete any cluster/node agent that are for rancher 2.4 or earlier.  So if rancher 2.5 was managing rancher 2.5 and then you upgraded you wouldn't see this issue.

**Comment by ibuildthecloud** [comment]
I think I'll only delete cluster/node agents where the server url matches itself.

**Comment by sowmyav27** [comment]
**Verified using 2.5-head commit id: `1599dc142`**

- Deploy a rancher server - 2.4.8 - will be the rancher hosting other rancher clusters - HA setup
- Deploy another imported k3s cluster. And install Rancher in this cluster in 2.5.1
- Upgrade the rancher in this ^^^ to 2.5-head.
- Cattle and node agents of this ^^ cluster are available and in version 2.4.8.
- Cluster is up and Active.

**Comment by dnoland1** [comment]
Tested v2.5.1 -> v2.5-head upgrade. Cattle node and cluster agents continued to run.
