### ISSUE TITLE
User is not able to create clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29702]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Login to rancher
- Add cluster --> Select custom cluster
- The page is stuck in loading
- Error in console:

```
component.js:935 Uncaught (in promise) TypeError: Cannot read property 'toString' of undefined
    at n.initUpgradeStrategy (component.js:935)
    at n.setupComponent (component.js:1652)
    at t.invoke (backburner.js:371)
    at e.t.flush (backburner.js:263)
    at e.t.flush (backburner.js:470)
    at e.n._end (backburner.js:1044)
    at _boundAutorunEnd (backburner.js:684)
```

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `9124f6ed`
- Installation option (single install/HA): single

**Comment by ibuildthecloud** [comment]
This is caused by bee119b8f8e0af2c49b2732fc97cefd0383b08d5.  That commit is on the 2.5 release branch.

**Comment by ibuildthecloud** [comment]
The issue I'm guessing is that a the Drain field is coming back as null when that previously wasn't possible.

**Comment by westlywright** [comment]
Ive added a UI check for this [here](https://github.com/rancher/ui/pull/4245/files#diff-1e0bd4ff252e24acb5e26b146ca23e15e8b8f968a619633a5b0ca59e1b1c69c9R997) that handles the nullable state of drain. From what I understand it seems like the backend change will on affect terraform provider but the UI check is low impact and prevents us from hitting this same bug again.

**Comment by izaac** [comment]
Rancher version: `v2.5-head (10/22/2020)` _1599dc1_

Edit custom cluster and I get this error. I can't edit there's this overlay that prevents me from selecting anything unless I hit back on the browser.


```
Uncaught (in promise) TypeError: Ember.get(...) is undefined
    initUpgradeStrategy component.js:935
    setupComponent component.js:1652
    invoke backburner.js:371
    flush backburner.js:263
    flush backburner.js:470
    _end backburner.js:1044
    _boundAutorunEnd backburner.js:684
    promise callback*i/< backburner.js:29
    flush Ember
    _scheduleAutorun backburner.js:1263
    _end backburner.js:1054
    _boundAutorunEnd backburner.js:684
    promise callback*i/< backburner.js:29
    flush Ember
    _scheduleAutorun backburner.js:1263
    _end backburner.js:1054
    _boundAutorunEnd backburner.js:684
    promise callback*i/< backburner.js:29
    flush Ember
    _scheduleAutorun backburner.js:1263
    _end backburner.js:1054
    _boundAutorunEnd backburner.js:684
    promise callback*i/< backburner.js:29
    flush Ember
    _scheduleAutorun backburner.js:1263
    _end backburner.js:1054
    _boundAutorunEnd backburner.js:684
    promise callback*i/< backburner.js:29
    flush Ember
    _scheduleAutorun backburner.js:1263
    _end backburner.js:1054
    _boundAutorunEnd backburner.js:684
    promise callback*i/< backburner.js:29
    flush Ember
    _scheduleAutorun backburner.js:1263
    _ensureInstance backburner.js:1251
    schedule backburner.js:820
    <anonymous> Ember
    m rsvp.js:429
    p rsvp.js:404
    e rsvp.js:527
    Ember 2
    e rsvp.js:521
    e rsvp.js:1039
    Ember 3
    v rsvp.js:494
    b rsvp.js:477
    invoke backburner.js:373
    flush backburner.js:263
    flush backburner.js:470
    _end backburner.js:1044
    _boundAutorunEnd backburner.js:684
    promise callback*i/< backburner.js:29
    flush Ember
    _scheduleAutorun backburner.js:1263
    _ensureInstance backburner.js:1251
    schedule backburner.js:820
    <anonymous> Ember
    m rsvp.js:429
```

**Comment by sowmyav27** [comment]
**On 2.5-head latest commit id: `1599dc14` and master-head latest - commit id: `9124f6e`**

- Click on Add cluster --> AWS.
- User is able to select an option from the Cloud Provider options seen.
- Select Amazon as the cloud provider.
- Deploy a cluster.
- User is able to deploy a cloud provider enabled cluster.
