### ISSUE TITLE
This is a bug?Or do I really have to wait until then?

### ISSUE THREAD

**Issue by liubao425** [rancher/rancher#29728]
![image](https://user-images.githubusercontent.com/11306738/96952775-352ac980-1522-11eb-98ae-67a63040dd89.png)

**Comment by superseb** [comment]
Thanks for reporting, you can see the real date when you click `Register here`: https://info.rancher.com/rancher-kubernetes-online-training-2020-10-29

I passed the wrong date along to get fixed.
