### ISSUE TITLE
API reports stacks as "active" when "stopped" or "degraded"

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2972]
I have a stack defined, holding a service with 5 instances.
If I query the stack in the API, it has a state "active" (correct).
When I stop the stack, it shows in the UI as "stopped", but the API still reports it as "active".
Similarly, if I kill one instance, the UI reports it as "degraded" but the API still returns "active".

The API returns "activating" when I set up a new stack, but after that it always shows "active".  

This makes it difficult to monitor stacks via the API as it is not clear if a stack is degraded or sctive without doing all the calculations for the scheduler.

**Comment by vincent99** [comment]
It probably shouldn't be this way (added to #1052) but `degraded` isn't an actual state in the API.  It's made up by the UI as a combination of the service state, the number of containers vs scale, and the healthState of the containers.

**Comment by sshipway** [comment]
It would be a great help to remote monitoring plugins (eg https://github.com/sshipway/check_rancher ) if the degraded state were exposed by the API and bubbled up to the stack.  The calculation is not trivial and is a fairly important indicator of health.

**Comment by vincent99** [comment]
Agree, as I said I already added it to the list.

**Comment by deniseschannon** [comment]
I'm going to close this in favor of #1052, where it has the list of changes we want for v2 of the API.
