### ISSUE TITLE
Validate Oracle Linux 7.9

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29737]
Validate Oracle Linux 7.9 on 2.4 branch

**Comment by aaronRancher** [comment]
Validated with Rancher server `rancher\rancher:2.4-head` `version ed9bdcc` with the following configurations:

oracleLinux-7.9-docker-19.03-selinux-on
oracleLinux-7.9-docker-19.03-selinux-off
oracleLinux-7.9-docker-19.03.11-selinux-on
oracleLinux-7.9-docker-19.03.11-selinux-off
