### ISSUE TITLE
[RFE] Add GKE pricing API during cluster creation

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#29732]
I would be helpful to add a cost estimate to the node pool creation / node options part of the rancher UI. 
Making cost visible to the creator before cluster creation or cluster update.

Pricing data API should be available from here:
https://cloud.google.com/billing/v1/how-tos/catalog-api

gz#12999

**Comment by sladyn98** [comment]
@zaggash Hey is this issue open for outside contributors to take a shot at ?

**Comment by zaggash** [comment]
> @zaggash Hey is this issue open for outside contributors to take a shot at ?

Yup, the rancher repository is public, this issue also.

**Comment by sladyn98** [comment]
Thanks Any starting points ? Or where to begin

**Comment by zaggash** [comment]
I'll let the people in charge to answer that question.
I do not have the answer myself.
