### ISSUE TITLE
Validate RHEL 7.9

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29736]
Validate Validate RHEL 7.9 on 2.4 branch

**Comment by jiaqiluo** [comment]
Validated RHEL 7.9 with Rancher `v2.4-4037-head` and K8s version `v1.18.10-rancher-1-2` 
Cluster provisioning and validation tests succeeded for the below:

- rhel-7.9-docker-19.03-selinux-on 
- rhel-7.9-docker-19.03-selinux-off 
- rhel-7.9-docker-native-113-selinux-on

**Comment by jiaqiluo** [comment]
reopen to wait for validating rhel-7.9-docker-17.03-selinux-on

**Comment by jiaqiluo** [comment]
- rhel-7.9-docker-17.03-selinux-on  FAILED: https://github.com/rancher/rancher/issues/29749#issuecomment-716036842
- rhel-7.9-docker-17.03-selinux-off PASS
