### ISSUE TITLE
Wrong certificate field description when adding certificates as secret

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#29734]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Try to add a certificate as secret:
- Open a project
- Resources -> Secrets
- Select tab Certificates
- Click `Add Certificate`

**Result:**
The field description and the embedded text both say CA certificate while it should be just certificate.

<img width="1454" alt="Screenshot 2020-10-23 at 19 28 53" src="https://user-images.githubusercontent.com/2620179/97035170-3847a900-1566-11eb-9c48-1f815d05c26e.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-a3a4c874867565671e91a87a9036fba70e2eb39e-head`
- Installation option (single install/HA): single

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 55fc963` and `rancher\rancher:v2.5-head` `version bebfe0d`

Certificate field description has been fixed.
![Screen Shot 2020-10-26 at 3 56 02 PM](https://user-images.githubusercontent.com/57409052/97237435-58fd4200-17a4-11eb-9176-6b796e7a5fef.png)

Reopening for a fix in `2.4-head`:
![Screen Shot 2020-10-26 at 4 11 18 PM](https://user-images.githubusercontent.com/57409052/97238147-eab97f00-17a5-11eb-856c-c267a1a8cdcf.png)

**Comment by bmdepesa** [comment]
Fixed in `v2.4-4095-head`

![Screen Shot 2020-10-27 at 6 35 22 AM](https://user-images.githubusercontent.com/21316915/97308933-a9b18100-181e-11eb-905d-b67e893987e7.png)
