### ISSUE TITLE
Etcd memory increase on RKE managed clusters after 2.5.1 upgrade

### ISSUE THREAD

**Issue by sharkztex** [rancher/rancher#29730]
**What kind of request is this (question/bug/enhancement/feature request):**
question

Steps to reproduce (least amount of steps as possible):
Upgraded Rancher to version 2.5.1

**Result:**

Memory consumption on etcd process increased dramatically. This effected all 3 of our RKE managed clusters.

**Other details that may be helpful:**
Below is a chart of pre/post upgrade of Rancher 2.5.1, the same symptoms apply to managed clusters that are running the newer (3.4.13) and older version(3.4.3) of etcd.
The Rancher management cluster is running an older version of Kubernetes 1.13.5, but the managed RKE clusters are up to date. Is there a knock effect on not getting the management cluster up to the latest version?

![image](https://user-images.githubusercontent.com/23399954/96979872-2559b800-1517-11eb-8e71-ae54435a68f6.png)

**Environment information**
- Rancher version: 2.5.1
- Installation option: HA
- OS: Ubuntu 16.04
- Rancher HA Management Servers: Kubernetes version: 1.13.5. Docker version: 19.3.12
- Managed RKE Clusters: Kubernetes version: 1.19.3. Docker version 19.3.12

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Virtual Machines. 4 Cores/20Gb memory
- Kubernetes version (use `kubectl version`):

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by superseb** [comment]
Is it only memory or also CPU? Do you have Rancher installed by any chance on the RKE clusters that are managed by this Rancher RKE cluster?

**Comment by sharkztex** [comment]
Hi @superseb , it's only the memory that's been impacted.
Rancher is installed on it's own 3 node RKE cluster, the other managed RKE clusters are running on separate nodes.

**Comment by maggieliu** [comment]
@sharkztex Can you clarify what the graph represents? It will be helpful if you can provide some logs. Also we don't officially support 2.5 on k8s 1.13, can you try on a newer k8s version and see if this can be reproduced?

**Comment by sharkztex** [comment]
Thanks @maggieliu, the graph represents the memory at 100% utilization post upgrade and pre upgrade it was at a constant 35% utilization on the etcd nodes with original memory allocation of 12Gb. To mask this issue we increased the memory on the nodes to 20Gb, and this tends to climb from a starting point of 35% and reaches 75%, the dip in memory ties in when etcd was compacting every hour.
![image](https://user-images.githubusercontent.com/23399954/97078507-92874f00-15e4-11eb-82a6-2e96e02a9677.png)
![image](https://user-images.githubusercontent.com/23399954/97078554-d5492700-15e4-11eb-88e2-b7cf5e4a8e03.png)

I'll will undertake the upgrade early next week and let you know how I get on. Thanks for all your input.

**Comment by sharkztex** [comment]
Hi, sorry for the late reply on this issue. Conducted a upgrade on the Rancher management cluster to version 1.17.4.
The etcd memory issue still occurs. I went through the troubleshooting topics in https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/etcd/ but everything is ok.
![image](https://user-images.githubusercontent.com/23399954/98256663-be0c2100-1f76-11eb-8166-7358e8437bd7.png)

![image](https://user-images.githubusercontent.com/23399954/98256282-463df680-1f76-11eb-8358-27c7a6af4433.png)

**Comment by timmy59100** [comment]
Same here with 2.5.2

**Comment by timmy59100** [comment]
Since we upgraded from 2.4.6 to 2.5.2 the etcd traffic is very high and we get timeouts.
Should we downgrade again or is there a fix?
You clearly see in the graph, when we did the upgrade.

![image](https://user-images.githubusercontent.com/7300669/99798225-f09a4a00-2b30-11eb-8472-d2a12f089741.png)
