### ISSUE TITLE
There are cases that a rancher-monitoring dashboards cannot display with timeout.

### ISSUE THREAD

**Issue by atuk721** [rancher/rancher#29756]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create single RKE cluster on VM using rke command.
2. Install Rancher v2.5.1 on it.
3. Create new Rancher managed 3 nodes cluster on bare metal using Rancher.
4. Install rancher-monitoring on Rancher managed cluster using Apps & Marketplace's chart via Cluster Explorer.
5. Show Monitoring page and click Alertmanager, Grafana, Prometheus Graph, and more.

**Result:**

It shows a right page or the following error.

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "error trying to reach service: dial tcp 10.42.0.57:8080: i/o timeout",
  "code": 500
}
```

**Other details that may be helpful:**

A success or error is determined whether the following pods are placed which node.

* rancher-monitoring-grafana-*
* rancher-monitoring-operator-*
* rancher-monitoring-prometheus-adapter-*

Or if output policy in iptables on nodes is changed to ACCEPT, they can display without problem.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.1
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal (CPU: Intel(R) Xeon(R) CPU L5630  @ 2.13GHz, memory: 32GB)
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by aiyengar2** [comment]
@atuk721 we have not encountered this error before in custom / imported RKE clusters with Monitoring V2 enabled on them before. 

Based on:
> Or if output policy in iptables on nodes is changed to ACCEPT, they can display without problem.

This could be specific to your environment if you are setting custom logic for the firewall on your nodes.

#### Context that can help debug this for custom setups

When you load the Monitoring page and click on Prometheus or Grafana, the following links are used:
```
Grafana: RANCHER_URL/k8s/clusters/CLUSTER_ID/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/SOME_PATH
Prometheus: RANCHER_URL/k8s/clusters/CLUSTER_ID/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/SOME_PATH
```

These links tell the Rancher UI to proxy through the Service `rancher-monitoring-<prometheus|grafana>` at the given port and these services internally redirect port `9090|80` to port `8080` on the respective pods.

Both Prometheus and Grafana pods have nginx containers listening at port `8080`, which serve as a reverse proxy for the actual Prometheus / Grafana containers in the Pods.

It seems like the error you are encountering is related to some networking configuration that might be dropping the response from nginx to the Rancher proxy?

**Comment by lungdart** [comment]
I'm currently having a similar issue on an EKS hosted rancher with an imported EKS cluster (All rancher-monitoring services)

When I access the monitoring URL for any of the monitoring stack, I get a 503 timeout. But if I port-forward directly to the service (Through the rancher kubernetes API URL) it works just fine. I've checked all my VPC and TGW routes, and everything seems fine. Node security groups are also passing all traffic between VPCs.

Let me know if there are additional troubleshooting steps I can take, or details I can provide. I wish I could just allow a port forwarding option as the solution, but I need to expose these portals to the dev teams who use them and don't want to setup RBAC and teach them kubectl. I suppose I could apply ingresses if I get desperate.

# Configuration details
## Rancher cluster
* Cloud provider: EKS
* Kubernetes Version: 1.21
* Rancher Version: 2.6.3

## Imported cluster
* Cloud provider: EKS
* Kubernetes Version: 1.21
* Rancher monitoring helm chart version: 100.1.2+up19.0.3
* Rancher monitoring helm chart values: N/A (DEFAULTS)

**Comment by murand78** [comment]
@lungdart I encountered the same issue on EKS. 
I was generally unable to use 'kubectl proxy' on all services, but the port-forward worked.
The problem was the security group attached to worked node, that did not allow access to pod ports with source the cluster security group ( the one used by the CP).

**Comment by murand78** [comment]
No, I did not edit the aws-auth configmap, but in my case the Rancher Local cluster is installed onPremises, and I connect to AWS using Access Keys
