### ISSUE TITLE
Inside the rancher-agent, `cadvisor -version` should show the actual version running

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2975]
Currently, if you exec into the rancher-agent container and go to `var/lib/cattle/bin/`, running `cadvisor -version` only displays `cAdvisor version  ()`. 

This doesn't indicate what version of cadvisor is actually running.

**Comment by sangeethah** [comment]
The same issue is tracked in #2709

**Comment by deniseschannon** [comment]
Duplicate of #2709
