### ISSUE TITLE
failed to remove finalizer on controller.cattle.io

### ISSUE THREAD

**Issue by shalev123d** [rancher/rancher#29752]
**What kind of request is this (question/bug/enhancement/feature request):**
Issue getting started

**Steps to reproduce (least amount of steps as possible):**
Hi all,

We're trying to get Rancher server up and running on our hosted k8s cluster, using the cert-manager and the rancher Helm chart.
Rancher was deployed successfully according to Helm and the pods are running, but no access to the UI.
When we checked the logs for the rancher pod, we saw those messages on repeat:

2020/10/26 07:22:22 [ERROR] error syncing 'tencentkubernetesengine': handler mgmt-kontainer-driver-lifecycle: error getting schema: dynamicschemas.management.cattle.io "cluster" not found, requeuing
2020/10/26 07:22:22 [ERROR] error syncing 'oraclecontainerengine': handler mgmt-kontainer-driver-lifecycle: error getting schema: dynamicschemas.management.cattle.io "cluster" not found, requeuing
2020/10/26 07:22:22 [ERROR] error syncing 'azurekubernetesservice': handler mgmt-kontainer-driver-lifecycle: error getting schema: dynamicschemas.management.cattle.io "cluster" not found, requeuing
2020/10/26 07:22:22 [ERROR] error syncing 'aliyunkubernetescontainerservice': handler mgmt-kontainer-driver-lifecycle: error getting schema: dynamicschemas.management.cattle.io "cluster" not found, requeuing
2020/10/26 07:22:22 [ERROR] error syncing 'googlekubernetesengine': handler mgmt-kontainer-driver-lifecycle: error getting schema: dynamicschemas.management.cattle.io "cluster" not found, requeuing
2020/10/26 07:22:39 [ERROR] error syncing 'p-j5vhd/u-6nfmnk6qfz-member': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2020/10/26 07:22:39 [ERROR] error syncing 'p-xdr8b/u-yykepq6du7-member': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2020/10/26 07:22:39 [ERROR] error syncing 'p-xdr8b/creator-project-owner': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2020/10/26 07:22:39 [ERROR] error syncing 'p-j5vhd/creator-project-owner': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing

All of the pods in the other namespaces are running, CRDs and pre-requisites are installed according to the documentation.
We tried to reinstall but we got the same outcome, any idea why?

Much thanks

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Trying to install 2.5
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

- Docker version (use `docker version`):

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by buker** [comment]
Reopen issue. I have same problem 
`[ERROR] error syncing 'c-m-qz6w9d6l/p-chv2r': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing`

**Comment by rex** [comment]
Yeah this is definitely still a problem, and is causing me a lot of grief at the moment. 

```
2022/06/21 23:32:03 [ERROR] error syncing 'p-dqll5/u-2uenovl37u-member': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2022/06/21 23:32:03 [ERROR] error syncing 'p-2jj8w/u-sjn5ppgsf2-member': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2022/06/21 23:32:04 [ERROR] error syncing 'c-v56t4/ambassador-cluster-owner': handler mgmt-auth-crtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-crtb-controller, requeuing
2022/06/21 23:32:05 [ERROR] error syncing 'c-v56t4/metallb-cluster-owner': handler mgmt-auth-crtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-crtb-controller, requeuing
2022/06/21 23:32:05 [ERROR] error syncing 'c-v56t4/creator-cluster-owner': handler mgmt-auth-crtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-crtb-controller, requeuing
2022/06/21 23:32:10 [ERROR] error syncing 'p-dqll5/creator-project-owner': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2022/06/21 23:32:10 [ERROR] error syncing 'p-2jj8w/sites-service-official-project-member': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2022/06/21 23:32:10 [ERROR] error syncing 'p-2jj8w/creator-project-owner': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2022/06/21 23:32:10 [ERROR] error syncing 'p-2jj8w/visitor-display-official-project-member': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2022/06/21 23:32:10 [ERROR] error syncing 'p-2jj8w/leaderboard-service-project-member': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
```

**Comment by GeorgeHahn** [comment]
I worked around this by removing finalizers from the relevant `clusters.management.cattle.io` and `clusters` resources. I don't know if any other resources are left hanging around, but the deleted cluster no longer appears in the rancher UI.

**Comment by xingxing122** [comment]
2022/10/11 15:05:14 [ERROR] error syncing 'local': handler mgmt-cluster-rbac-delete: create not allowed while custom resource definition is terminating, handler cluster-deploy: create not allowed while custom resource definition is terminating, requeuing
2022/10/11 15:05:14 [ERROR] error syncing 'c-m-xxwr49vg/p-m9r5k': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2022/10/11 15:05:14 [ERROR] error syncing 'c-m-xxwr49vg/p-j9snx': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2022/10/11 15:05:15 [ERROR] error syncing 'c-m-xxwr49vg/creator-cluster-owner': handler mgmt-auth-crtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-crtb-controller, requeuing
2022/10/11 15:05:16 [ERROR] error syncing 'p-j9snx/creator-project-owner': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2022/10/11 15:05:16 [ERROR] error syncing 'p-m9r5k/creator-project-owner': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2022/10/11 15:05:16 [ERROR] error syncing 'fleet-local/local': handler cluster-create: failed to create local/local-fleet-local-owner management.cattle.io/v3, Kind=ClusterRoleTemplateBinding for cluster-create fleet-local/local: create not allowed while custom resource definition is terminating, requeuing
2022/10/11 15:05:16 [ERROR] error syncing 'c-m-xxwr49vg/p-j9snx': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2022/10/11 15:05:16 [ERROR] error syncing 'c-m-xxwr49vg/p-m9r5k': handler mgmt-project-rbac-remove: failed to remove finalizer on controller.cattle.io/mgmt-project-rbac-remove, requeuing
2022/10/11 15:05:17 [ERROR] error syncing 'local': handler mgmt-cluster-rbac-delete: create not allowed while custom resource definition is terminating, handler cluster-deploy: create not allowed while custom resource definition is terminating, requeuing
2022/10/11 15:05:18 [ERROR] error syncing 'c-m-xxwr49vg/creator-cluster-owner': handler mgmt-auth-crtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-crtb-controller, requeuing
2022/10/11 15:05:18 [ERROR] error syncing 'p-m9r5k/creator-project-owner': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2022/10/11 15:05:18 [ERROR] error syncing 'p-j9snx/creator-project-owner': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing

**Comment by hemkvo** [comment]
我也遇到了这个问题 有什么解决方式么
