### ISSUE TITLE
User is not able to login to Rancher after logging out

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29751]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Login as an admin
- Logout
- Login back as admin
- User is prevented from logging in with error `An unknown error occured while attempting to login. Please contact your system administrator.`
- Error in console: `Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)` 
- API Response : `{"baseType":"error","code":"InvalidCSRFToken","message":"Invalid CSRF token","status":422,"type":"error"}`

To get out of this situation, user has to refresh the page, and user will be able too login OR open a new tab/browser

**Expected Result:**
User should be able to login

**Other details that may be helpful:**
happens most of the times

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head and master-head commit id: `a3a4c874`
- Installation option (single install/HA): single

**Comment by StrongMonkey** [comment]
I looked at it and it looks like a UI bug. When logout server expect `x-api-csfr` header to be set to match the cookie. I don't see the header being set until I refresh the page.

![Screenshot from 2020-10-27 21-31-52](https://user-images.githubusercontent.com/9203378/97391273-1585ff00-189c-11eb-8d7b-d18c7aece89d.png)

**Comment by StrongMonkey** [comment]
It can probably be fixed by deleting the csfr cookie when logout.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `7eb1792` and master-head commit id: `b7e8c0d3d1`**

- Login as an admin
- Logout
- Login back as admin
- User is able to login with no errors
