### ISSUE TITLE
ldap: support multiple search bases

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#2976]
In order to support objects from different parts of a larger tree, it would be useful to be able to specify more than one search base.

ref: http://forums.rancher.com/t/ldap-multiple-search-bases/1207

**Comment by prachidamle** [comment]
@kaos what is the primary reason for not specifying the larger superset of the multiple trees, as the base-domain? 
Is it that everyone under the parent tree gets access? we can solve this by creating a "whitelist" of domains allowed + specify the base domain (superset domain of the subset domains), and that would find your object (using the superset domain) but allow it access only if it falls under the whitelisted domains.

**Comment by kaos** [comment]
It is because the search base is used for both groups and users. And using a common parent includes a lot of entries we don't want to have.

I think that was it, anyway. Can't really say I remember exactly any longer. And with that, I realize this can't be a very high prio request, as it haven't been nagging at me that much since I wrote it.

Feel free to file it under "nice to have" ;)

**Comment by andrewrust** [comment]
Comment as requested by @chrisurwin :

We have a very large, complex Active Directory tree and as such the location for Users/Groups is not in a single search base.

We will either need the ability to search for Users and Groups accross mutliple search bases or, as per the above comment from @prachidamle , have the ability to specify a single User and/or Group search base (as is currently possible) along with a whitelist to allow only specific domain paths to be whitelists and actually used for Active Directory authentication.

**Comment by ntwrkguru** [comment]
@prachidamle As others have said, we have a complex (perhaps not organized in the best manner) AD. The only common search base is the base DN. I'd like to extend this to groups as well as, again, the common search base is the base DN and, in our case, that's many tens of thousands of entries.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
