### ISSUE TITLE
invalidate UI after server upgrade

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#2977]
Pre:
Logged in on 0.49.0, session times out due to inactivity..

Action:
Server upgrade to 0.49.1

Post:
Click on page, gets login screen (ok), logs in, lands at application page (still fine), check the version by clicking on the cow in the corner, which presents the old version (0.49.0) instead of the new one.
a page refresh and the version info is correct again.

Expected:
correct version info after login without the need to reload the page.

**Comment by vincent99** [comment]
All the assets are fingerprinted, but the server needs to send a `Cache-Control: max-age=0, no-cache` header so that the actual index.html gets re-pulled by the browser.

**Comment by tfiduccia** [comment]
Must wait for next build again

**Comment by tfiduccia** [comment]
User Interface version tag is not updating.

**Comment by vincent99** [comment]
@westlywright the ui.js is now not-fingerprinted so it ends up using a cached copy of the most important file

**Comment by westlywright** [comment]
rancher/ui#483

**Comment by tfiduccia** [comment]
Version - master 3/17
Does not work.... I check the box and add http://ghe.rancher.io/ into the Enterprise Host* field and it's directing to https://http//ghe.rancher.io//login/oauth/

**Comment by tfiduccia** [comment]
Version - master 3/17
Does not work.  When I refresh the page after update, the screen goes blank.

**Comment by deniseschannon** [comment]
@tfiduccia Could this one be a duplicate? https://github.com/rancher/rancher/issues/4008

**Comment by tfiduccia** [comment]
@deniseschannon This is not the same issue.  The white page is preventing the testing of original issue - "Versions not updating after upgrade".  Once the white page is fixed, then the original issue still needs to be tested.

**Comment by tfiduccia** [comment]
Version - v1.0.0-rc2
Verified fixed
