### ISSUE TITLE
if --no-cacerts is specified but setting exists, setting is used when generating kubeconfig

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#29771]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

It appears that over 18 months ago when I was first setting up my cluster the setting/cacerts got populated, but I then switched to using letsencrypt.

**Result:**

In 2.4 this seemed to not be a problem, but 2.5 the setting started to get used in kubeconfig generation

This led to x509 unknown certificate authority errors because it was loading in a bad certificate when using the Rancher 2 proxied url for kubernetes clusters.

**Other details that may be helpful:**

Deleting of the setting cacerts from the local cluster and a restart of rancher resolved the issue.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5
- Installation option (single install/HA): HA

**Comment by StrongMonkey** [comment]
@ekristen Were you using self-generated before 2.5 and then when you upgrade to 2.5 with letsencrypt the kubeconfig still have the leftover CA?

**Comment by StrongMonkey** [comment]
The only chance I could think is that If you use privateCA for your helm chart, you will need to reset the helm value `--set privateCA=false`. If this is true rancher will not clean up the cacert setting.

**Comment by ekristen** [comment]
I was never using a self-generated but my HA cluster is 18+ months old.  It's possible initially I didn't set `letsencrypt` but @ibuildthecloud asked me to open an issue.

The helm chart doesn't have `privateCA` set in the user supplied values so it's using the default.

**Comment by ekristen** [comment]
This is still happening on 2.6.0. `privateCA` is set to false. Just ran a helm upgrade again to be sure

```
helm upgrade rancher -n cattle-system rancher-latest/rancher --version=2.6.0 --set hostname=r2.private.io --set ingress.tls.source=letsEncrypt --set letsEncrypt.email=erik@private.io --set privateCA=false
```

TLS certificate is LetsEncrypt, it's managed and working, however all generated kubeconfig files for cluster access over r2.private.io contains certificate-authority-data which causes kubectl to throw errors because it's the wrong data.

**Comment by ekristen** [comment]
I fixed it. `settings.management.cattle.io/cacert` had a value set for the field `value`, created on 2020-10-26, which coincides with my upgrade to 2.5.
