### ISSUE TITLE
[UI] pass cluster name on template request via query parameter

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#29774]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Description:**
Pass name of applicable cluster where applicable as query param when sending GET request to template API.

**Backend Issue:**
https://github.com/rancher/rancher/issues/29773

**Comment by rmweir** [comment]
The filter and all kubeVersion compatibility logic will be bypassed if the instance of rancher is not using an actual release. If it is being tested on a non-release such as master-head, the work around would be to set the environment variable that maps to the server-version setting. For docker the command would be `sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e CATTLE_SERVER_VERSION=2.5.3 --privileged rancher/rancher:master-head`

**Comment by jiaqiluo** [comment]
The UI is validated on rancher:master-head 6f96683 as part of https://github.com/rancher/rancher/issues/29773#issuecomment-738286704

The GET request passes the new parameter `ClusterName`
<img width="627" alt="Screen Shot 2020-12-03 at 12 37 55 PM" src="https://user-images.githubusercontent.com/6218999/101083703-2ba57000-356a-11eb-914b-87eb02d6e023.png">

and version links are returned 

<img width="358" alt="Screen Shot 2020-12-03 at 12 38 36 PM" src="https://user-images.githubusercontent.com/6218999/101083706-2c3e0680-356a-11eb-8349-859054f6afab.png">

**Comment by jiaqiluo** [comment]
Will revisit this issue when the backend is fixed.

**Comment by jiaqiluo** [comment]
As @thedadams points out in his comment https://github.com/rancher/rancher/issues/29773#issuecomment-738459873 the value of the `ClusterName` should be the cluster's real name, like `c-ctdzb`, not the display name, like `1-17`. 

Reopen this issue for a fix in the UI.

**Comment by jiaqiluo** [comment]
The validation is done on 
- rancher:master-head  a31eecf55
- rancher:v2.5-head ef237669e


now the "real" cluster name is passed. See https://github.com/rancher/rancher/issues/29773#issuecomment-739054280 for the detailed result of the validation. 

<img width="731" alt="Screen Shot 2020-12-04 at 3 22 27 PM" src="https://user-images.githubusercontent.com/6218999/101221295-a3e06400-3644-11eb-8bff-aa329ef83ab7.png">
