### ISSUE TITLE
Unable to provision AWS EC2 cluster using node templates, all nodes reporting "Waiting for SSH to be available"

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#29788]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

> note: exact steps unknown as no root cause yet

- [follow docs for creating rke clusters using aws ec2 node templates 
](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/node-pools/ec2/#2-create-a-node-template-with-your-cloud-credentials-and-information-from-ec2)
- nodes are provisioned in AWS and show in the list of ec2 instances

**Result:**

failure in provisioning downstream cluster as all nodes are stuck on "Waiting for SSH to be available". Appears entirely isolated to EC2 node driver provisioning

**Other details that may be helpful:**

- Appear to have full connectivity between Rancher (on-prem) and Downstream nodes (EC2)
- Dev cluster is working, Prod cluster cannot finish provisioning nodes
- Dev and Prod Rancher have identical setup, same datacenter, same Load balancing rules
- Dev and Prod downstream aws nodes have identical setup, same VPC, same Subnet, same Security Group
- You can SSH to the downstream aws nodes from the Rancher servers
- The downstream node can talk back to the Rancher URL, nothing blocked
- Custom clusters work, adding a node via the docker join command the cluster adds without issue. Isolated to EC2 node driver provisioning
- Tried different variations of AMIs using multiple kernels (newer and older), didn't work.

- verified rancher-machine command works from within the rancher pod
- `use-private-address` vs `private-address-only` - in the node template, one set to `true`, one set to `false` - tried setting both to true
- turn on trace logging, get the exact command rancher runs to create a node, run that manually via rancher-machine and it works
- rke cluster yaml and rancher installation all basic vanilla

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EC2 AWS using node templates
- Kubernetes version (use `kubectl version`): v1.17.5
- Docker version (use `docker version`): 19.03.x

gz#11298

**Comment by maggieliu** [comment]
This is no longer an issue per user.

**Comment by fastmanu** [comment]
Well, i actually have this issue too. I can't figure out, nor find in the documentation, how to specify in the node template, that the Rancher server should provision the node over the private network (172.31.0.0, aka internal IP).

Once the node is created, the server correctly gets both external and internal addresses. But the server tries to ssh[22]/docker[2376] over the public ip (which obviously doesn't allow this kind of traffic).

Some help would be really appreciated.
