### ISSUE TITLE
Cattle cluster agent fails to resolve Rancher hostname

### ISSUE THREAD

**Issue by TomasTokaMrazek** [rancher/rancher#29780]
I am unable to successfully provision kubernetes cluster with single node for all roles. The node will get active, but cluster stays in error state due to `cluster agent is not ready`. Further investigaion shows, that cattle-cluster-agent is unable to ping rancher server and shuts itself down. This step is repeated every few minutes with the same result. Cluster never fully recovers.

Docker logs from repeatedly created container:
```
INFO: Environment: CATTLE_ADDRESS=10.42.0.6 CATTLE_CA_CHECKSUM=5bd5632b37de5f40b5ef0233aa01fe86ae081c22e2f6633dcb8fbde586a6e80a CATTLE_CLUSTER=true CATTLE_FEATURES= CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=true CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-7c56d97f45-wfx95 CATTLE_SERVER=https://rancher.<MY DOMAIN>
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local <MY DOMAIN> options ndots:5
ERROR: https://rancher.<MY DOMAIN>/ping is not accessible (The requested URL returned error: 404)
```

**Network description**
I have two DNS set up. One is public, with wildcard A record pointing to my homelab behind pfSense, and second DNS in pfSense itself. This DNS is not publicly visible and is used only as a resolver for internal services inside homelab network. The rest is forwarded to Cloudflare 1.1.1.1. Internal DNS resolver is configured to automatically register all DHCP clients. Both Rancher and VM nodes uses DHCP.

**Inftrastructure**
- vSphere 6.7
- pfSense (firewall, router, dns resolver)

**Rancher**
- Version: 2.5.1
- Installation: Single Node Installation via Docker with self-signed CA
- Docker Image: rancher:rancher/latest
- VM Host: unmodified Ubuntu 18.04 cloud image

**Cluster**
Architecture | amd64
-- | --
Docker Version | 19.3.13
Kernel Version | 5.4.0-51-generic
Kubelet Version | v1.19.3
Kube Proxy Version | v1.19.3
Operating System Image | Ubuntu 20.04.1 LTS
Operating System | linux

- Provider: vSphere
- Node Template: unmodified Ubuntu 20.04 cloud image
- Cloud Config
```
#cloud-config

ssh_authorized_keys:
  - ssh-rsa <public key>
  
users:
  - default
```

**Comment by TomasTokaMrazek** [comment]
I tried to remove wildcard A record for the domain from public DNS just to see, what happens. To my surprise, cluster recovered. I created the wildcard record again as this is not the correct solution.

I haven't edited `/etc/resolv.conf` anywhere. Rancher is resolved correctly from every VM including the node itself meaning that DNS resolver is configured correctly. 

Dig from the node via coredns:
```
ubuntu@srv01-node-1:~$ dig rancher.mydomain.cz @10.43.0.10

; <<>> DiG 9.16.1-Ubuntu <<>> rancher.mydomain.cz @10.43.0.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31076
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;rancher.mydomain.cz.	IN	A

;; ANSWER SECTION:
rancher.mydomain.cz. 30	IN	A	192.168.10.177

;; Query time: 0 msec
;; SERVER: 10.43.0.10#53(10.43.0.10)
;; WHEN: Tue Oct 27 16:46:20 UTC 2020
;; MSG SIZE  rcvd: 97
```

Logs:
```
ubuntu@srv01-node-1:~$ sudo docker ps -a -q --filter "label=io.kubernetes.container.name=cluster-register" | while read container; do echo "=> $container"; sudo docker logs $container; done
=> 5711cd5745e7
INFO: Environment: CATTLE_ADDRESS=10.42.0.7 CATTLE_CA_CHECKSUM=5bd5632b37de5f40b5ef0233aa01fe86ae081c22e2f6633dcb8fbde586a6e80a CATTLE_CLUSTER=true CATTLE_FEATURES= CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=true CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-5cbd984497-rl599 CATTLE_SERVER=https://rancher.mydomain.cz
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local mydomain.cz options ndots:5
ERROR: https://rancher.mydomain.cz/ping is not accessible (The requested URL returned error: 404)

```

**Comment by superseb** [comment]
Your setup probably needs some customization regarding how DNS is handled. Both https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/ and https://github.com/rancher/rancher/issues/16697#issuecomment-441659499 should probably be enough. (given that the 404 is based on the name being resolved to your wildcard DNS)

**Comment by TomasTokaMrazek** [comment]
I don't understand, how a record in public DNS affects this, when nodes in cluster and Rancher itself has DNS set up as 192.168.10.1, which is DNS Resolver in pfSense with implicit hostname resolution for rancher.mydomain.cz and IP: 192.168.10.177. 

If there is an issue with ndots, the query to 192.168.10.1 translates as rancher.mydomain.rancher.mydomain.cz, which is unknown to the pfSense DNS resolver It then calls upstream, where wildcard record is. But why the resolution starts to work, when I remove wildcard certificate? This should return unresolvable hostname instead.

I've read all topics availible, yet I fail to see, how I should reconfigure something on my end. Hostname resolution works everywhere but Rancher / K8s cluster. And if I should change some configuration in Rancher, what exactly should I do? My apologies, but it's not aparent from the links you provided nor from the other readings.

**Comment by TomasTokaMrazek** [comment]
So today I wanted to continue with cluster setup just to be welcomed to functional cluster. It recovered after nearly 500 retries without any intervention on my side. I was still sleeping 4 hours ago. There must be something wrong either in Rancher or Kubernetes or CoreDNS.
```
d66e2d8e8470        141c7125f5a2                                      "run.sh"                 4 hours ago         Up 4 hours                                    k8s_cluster-register_cattle-cluster-agent-5cbd984497-rl599_cattle-system_d6ab7e95-e8af-4276-a03e-b7d5784be833_477
b9e5e5b45f42        141c7125f5a2                                      "run.sh"                 4 hours ago         Exited (1) 4 hours ago                        k8s_cluster-register_cattle-cluster-agent-5cbd984497-rl599_cattle-system_d6ab7e95-e8af-4276-a03e-b7d5784be833_476
```

**Comment by superseb** [comment]
A potential solution is in https://github.com/rancher/rancher/issues/16697#issuecomment-521334029. If you believe there is a bug here, please provide the DNS server logs and the commands (and command output) issued during that logging where you query the actual hostname and the hostname with added search domains which we can then lookup why CoreDNS is not resolving this properly.

Normally the wildcard record returns a result which is then used and ends up at the wrong place (404), while removing this lets the query succeed with the actual record. This should also be testable by switching between having a wildcard record and not having a wildcard record and running the DNS queries manually to see what the result of the query is.

**Comment by superseb** [comment]
Let me know if this needs further investigation

**Comment by korenlev** [comment]
+ one , i see the same issues using rancher 2.5.7 and 2.5.8 , what is the status of any resolution ?

**Comment by korenlev** [comment]
my setup is on AWS, exactly the same error

**Comment by superseb** [comment]
This is a closed issue, and it was regarding having a wildcard DNS record causing issues (it routed to a place where the name was not known, hence the 404). If you are experiencing issues with your setup, please file a new issue with all the details requested in the issue template and logs so we can investigate.

**Comment by korenlev** [comment]
Hi, i will open a new one, just mentioning this should not close as we at big prod app use wildcards in dns and can not install rancher since 2.5.x

**Comment by karbowiak** [comment]
Just ran head first into this exact issue on 2.8.0, using Ubuntu 22.04 LTS images.

Only recourse i see is getting a new domain to run rancher on, without any wildcards - which doesn't seem right
