### ISSUE TITLE
With a Cloud Provider enabled, Windows worker nodes cannot join cluster due to DNS suffixes being passed to kubelet as commands

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#29782]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- setup multiple DNS suffixes in AWS DHCP Options Sets
- enable aws cloud provider in a new mixed cluster
- add new windows worker node

**Result:**

kubelet will be unable to start due to interpreting the DNS suffix options as commands.

For example:

`--hostname-override=ip-X-X-X-X.XXXXX.com gad.XXXXX.com apa.gad.XXXXX.com eur.gad.XXXXX.com gmea.gad.XXXXX.com nam.XXXXX.com us-east-1.compute.internal --feature-gates=HyperVContainer=true,WindowsGMSA=true
`

They will see the following when adding windows nodes in the kubelet logs:

`10328 server.go:163] unknown command: apa.gad.XXXXX.com`

**Other details that may be helpful:**

Issue can be addressed in the following powershell script by truncating to the first hostname returned.

https://github.com/rancher/rke-tools/blob/v0.1.65/windows/cloud-provider.psm1#L229-L232

gzrancher/rancher#12873

**Comment by sowmyav27** [comment]
**Validated On 2.4.9-rc5**

- Deploy windows cluster - AWS cloud provider enabled, on k8s 1.18,1.17,1.16 and 1.15
- Deploy PVC and LB
- PVC and LB deployed successfully on all clusters except for this [issue](ttps://github.com/rancher/rancher/issues/29775)

**Comment by sowmyav27** [comment]
Closing this issue as the forward port issue is tracked separately.
