### ISSUE TITLE
Validate Oracle Linux 7.9 and 8.2

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29798]
Validate Oracle Linux 7.9 and 8.2
Docker 19.03.x

- Deploy downstream clusters using Oracle Linux 7.9 and Docker versions: 19.03.x
- Deploy downstream clusters using Oracle Linux 8.2 and Docker versions: 19.03.x
- Deploy HA setup ; local cluster running on Oracle Linux 7.9 and Docker version: 19.03.x
- Deploy HA setup ; local cluster running on Oracle Linux 8.2 and Docker version: 19.03.x

**Comment by aaronRancher** [comment]
Validated Oracle Linux 7.9 on `rancher\rancher:v2.5-head` `version cc777eb`
Docker versions: 19.03, 19.03.11

**Comment by aaronRancher** [comment]
Validated Oracle Linux 8.2 on `rancher\rancher:v2.5-head` `version cc777eb`
Docker versions: 19.03, 19.03.11

Installed docker with:
```
 curl -L https://releases.rancher.com/install-docker/19.03.sh | sh
 curl -L https://releases.rancher.com/install-docker/19.03.11.sh | sh
```
