### ISSUE TITLE
Device Mappings Disappear

### ISSUE THREAD

**Issue by ronag** [rancher/rancher#2979]
Device mappings are not shown in the config view nor do they exist when upgrading a container.  Even though the container was created with device mappings.

1. Do an upgrade with device mappings
2. Verify that device mapping works
3. Check config view
  - Device mapping doesn't exists
4. Do upgrade again
  - Device mapping doesn't exists

**Comment by deniseschannon** [comment]
@ronag Do you have a good example I could try and reproduce with? I have never really used the device mappings...

**Comment by ronag** [comment]
Just map e.g. `/dev/USB0:/dev/USB0`

**Comment by deniseschannon** [comment]
I honestly don't know how to verify that this is an issue, but will tag it for our UI team to take a look.

**Comment by vincent99** [comment]
Tracking in https://github.com/rancher/rancher/issues/3707
