### ISSUE TITLE
[Forward port] With a Cloud Provider enabled, Windows worker nodes cannot join cluster due to DNS suffixes being passed to kubelet as commands

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29791]
forward port for: https://github.com/rancher/rancher/issues/29782

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/29817

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `0465f049`**

**Comment by sowmyav27** [comment]
**On master-head - commit id: `15d5fda06`**

- Deployed windows clusters k8s versions 1.19,1.18,1.17 and 1.16 clusters. 1 etcd/control and 1 worker linux nodes, 3 windows worker nodes
- Deployed LB. LB works
- Created PV, deployed workload, attached PVC using the PV. Works.
