### ISSUE TITLE
rancher v2.3.1 starting tls server: Get https://localhost:6444/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by d3y** [rancher/rancher#29802]
自建的kubernetes集群证书到期后，通过 kubeadm 生成了新的证书，导致通过 docker 部署的单点 Rancher 无法使用。报错日志如下：
E1028 05:44:27.660001      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.ReplicaSet: Get https://localhost:6444/apis/apps/v1/replicasets?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
E1028 05:44:27.660335      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.Service: Get https://localhost:6444/api/v1/services?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
E1028 05:44:27.660574      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.PersistentVolumeClaim: Get https://localhost:6444/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
E1028 05:44:27.661437      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.StorageClass: Get https://localhost:6444/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48208: remote error: tls: bad certificate
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48210: remote error: tls: bad certificate
E1028 05:44:27.665173      32 reflector.go:126] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:223: Failed to list *v1.Pod: Get https://localhost:6444/api/v1/pods?fieldSelector=status.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
E1028 05:44:27.665434      32 leaderelection.go:306] error retrieving resource lock kube-system/kube-controller-manager: Get https://localhost:6444/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: x509: certificate has expired or is not yet valid
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48212: remote error: tls: bad certificate
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48204: remote error: tls: bad certificate
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48214: remote error: tls: bad certificate
E1028 05:44:27.666943      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.PersistentVolume: Get https://localhost:6444/api/v1/persistentvolumes?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48216: remote error: tls: bad certificate
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48196: remote error: tls: bad certificate
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48198: remote error: tls: bad certificate
E1028 05:44:27.669024      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.ReplicationController: Get https://localhost:6444/api/v1/replicationcontrollers?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
E1028 05:44:27.674854      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.StatefulSet: Get https://localhost:6444/apis/apps/v1/statefulsets?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48206: remote error: tls: bad certificate
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48200: remote error: tls: bad certificate
time="2020-10-28T05:44:27.701227872Z" level=fatal msg="starting tls server: Get https://localhost:6444/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: x509: certificate has expired or is not yet valid"

我回调了系统时间，Rancher 可以正常使用，查看 ssl 证书发现时间为1年后，应该不存在证书到期的问题。
在正常的系统时间下，删除 /var/lib/rancher/k3s/tls 下的证书，并重启了 docker ，rancher 可以正常运行。但是无法连接相应的集群，我应该如何解决这个问题呢？
![image](https://user-images.githubusercontent.com/43953721/97397535-6e997580-1924-11eb-8202-7040093559f1.png)

**Comment by kingsd041** [comment]
@d3y  Please use English to create an issue, or go to https://gitee.com/rancher/rancher to create a Chinese issue
