### ISSUE TITLE
level=fatal msg="starting tls server: Get https://localhost:6444/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by d3y** [rancher/rancher#29803]
I called back the system time and Rancher can be used normally. After checking the ssl certificate, I found that the time is 1 year, there should be no certificate expiration problem.
The log is as follows:
In normal system time, delete the certificate under /var/lib/rancher/k3s/tls and restart docker, rancher can run normally. But I cannot connect to the corresponding cluster. How should I solve this problem?
E1028 05:44:27.660001      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.ReplicaSet: Get https://localhost:6444/apis/apps/v1/replicasets?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
E1028 05:44:27.660335      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.Service: Get https://localhost:6444/api/v1/services?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
E1028 05:44:27.660574      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.PersistentVolumeClaim: Get https://localhost:6444/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
E1028 05:44:27.661437      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.StorageClass: Get https://localhost:6444/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48208: remote error: tls: bad certificate
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48210: remote error: tls: bad certificate
E1028 05:44:27.665173      32 reflector.go:126] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:223: Failed to list *v1.Pod: Get https://localhost:6444/api/v1/pods?fieldSelector=status.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
E1028 05:44:27.665434      32 leaderelection.go:306] error retrieving resource lock kube-system/kube-controller-manager: Get https://localhost:6444/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: x509: certificate has expired or is not yet valid
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48212: remote error: tls: bad certificate
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48204: remote error: tls: bad certificate
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48214: remote error: tls: bad certificate
E1028 05:44:27.666943      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.PersistentVolume: Get https://localhost:6444/api/v1/persistentvolumes?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48216: remote error: tls: bad certificate
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48196: remote error: tls: bad certificate
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48198: remote error: tls: bad certificate
E1028 05:44:27.669024      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.ReplicationController: Get https://localhost:6444/api/v1/replicationcontrollers?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
E1028 05:44:27.674854      32 reflector.go:126] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.StatefulSet: Get https://localhost:6444/apis/apps/v1/statefulsets?limit=500&resourceVersion=0: x509: certificate has expired or is not yet valid
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48206: remote error: tls: bad certificate
2020/10/28 05:44:27 http: TLS handshake error from 127.0.0.1:48200: remote error: tls: bad certificate
time="2020-10-28T05:44:27.701227872Z" level=fatal msg="starting tls server: Get https://localhost:6444/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: x509: certificate has expired or is not yet valid"
![image](https://user-images.githubusercontent.com/43953721/97398782-bde0a580-1926-11eb-94b7-55d7c82a7259.png)

**Comment by d3y** [comment]
Look like a certificate problem:
E1028 06:08:20.290973      32 prometheus.go:162] failed to register latency metric admission_quota_controller: duplicate metrics collector registration attempted
E1028 06:08:20.291013      32 prometheus.go:174] failed to register work_duration metric admission_quota_controller: duplicate metrics collector registration attempted
E1028 06:08:20.291035      32 prometheus.go:189] failed to register unfinished_work_seconds metric admission_quota_controller: duplicate metrics collector registration attempted
E1028 06:08:20.291063      32 prometheus.go:202] failed to register longest_running_processor_microseconds metric admission_quota_controller: duplicate metrics collector registration attempted
W1028 06:08:20.459379      32 genericapiserver.go:315] Skipping API batch/v2alpha1 because it has no resources.
W1028 06:08:20.466915      32 genericapiserver.go:315] Skipping API node.k8s.io/v1alpha1 because it has no resources.
E1028 06:08:20.484918      32 prometheus.go:138] failed to register depth metric admission_quota_controller: duplicate metrics collector registration attempted
E1028 06:08:20.484970      32 prometheus.go:150] failed to register adds metric admission_quota_controller: duplicate metrics collector registration attempted
E1028 06:08:20.485005      32 prometheus.go:162] failed to register latency metric admission_quota_controller: duplicate metrics collector registration attempted
E1028 06:08:20.485037      32 prometheus.go:174] failed to register work_duration metric admission_quota_controller: duplicate metrics collector registration attempted
E1028 06:08:20.485067      32 prometheus.go:189] failed to register unfinished_work_seconds metric admission_quota_controller: duplicate metrics collector registration attempted
E1028 06:08:20.485092      32 prometheus.go:202] failed to register longest_running_processor_microseconds metric admission_quota_controller: duplicate metrics collector registration attempted
time="2020-10-28T06:08:20.504672605Z" level=info msg="Running kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --port=10251 --secure-port=0"
time="2020-10-28T06:08:20.517054866Z" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --cluster-signing-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --port=10252 --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --use-service-account-credentials=true"
time="2020-10-28T06:08:20.533877650Z" level=fatal msg="starting tls server: Get https://localhost:6444/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: x509: certificate has expired or is not yet valid"
2020/10/28 06:08:20 [FATAL] k3s exited with: exit status 1

**Comment by janschwirtz** [comment]
Maybe duplicate of #26984?

**Comment by klention** [comment]
the same here.
regarding #26984 I can not find the mentioned certificates (token-node.crt, localhost.crt). In fact I do not have the path (/var/lib/rancher/management-state/tls/) neither. The only path I can find containing certificates on rancher server is: /var/lib/rancher/k3s/server/tls
What can we do to renew those certs? Cause rotating from Rancher UI (after changing the time a few days back) doesn't help.

**Comment by klention** [comment]
https://github.com/rancher/rancher/issues/26984#issuecomment-712233261
this helped
