### ISSUE TITLE
[2.4.x] Need UI warning for Process started in UI container shell stays even after closing the UI

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29811]
We need a warning msg around the kubectl shell that:
User must explicitly type "exit" before closing the window in the UI, else process started in UI container shell will continue to run.

As per this comment: https://github.com/rancher/rancher/issues/16192#issuecomment-526276609

**Comment by westlywright** [comment]
I am not adding the warning as I've added logic to automatically send the exit command before the connection is closed. In my testing I was able to open and close the shell from the UI and only saw one process created so it seemed more appropriate than the warning.

**Comment by sadiapoddar** [comment]
Verified the fix with 2.4-head, v2.4-4278-head
Verification steps
1. created a ubuntu workload
2. Once the workload is running, invoke the workload shell from UI
3. Closed the shell, repeat steps 2 and 3 a few times.
4. Not seeing any processes from the previous connection
<img width="1787" alt="Screen Shot 2020-11-13 at 4 42 39 PM" src="https://user-images.githubusercontent.com/72409237/99133669-aadcff00-25cf-11eb-8789-1ad4ed9988ba.png">

5. Each invocation it's only the fixed number of process per connection. 

Looks like it's now sending "exit" upon closing the shell and all process for the current connection get  terminated upon closing.
