### ISSUE TITLE
Apps & Marketplace: undefined undefined message when refreshing Charts

### ISSUE THREAD

**Issue by axeljnilsson94** [rancher/rancher#29828]
**What kind of request is this (question/bug/enhancement/feature request):**
Kind: Bug

**Steps to reproduce (least amount of steps as possible):**
Setup a private helm repository with credentials (clientSecret) in the Cluster Explorer of a given cluster managed by Rancher.
Go to Apps & Marketplace -> Charts -> Deploy Charts, choose which repository to refresh and press the refresh button.

**Result:**
When pressing refresh I get a pop-up error saying _undefined undefined_ which I can close or acknowledge with and OK button.
![rancher_undefined](https://user-images.githubusercontent.com/54094285/97545020-b07cf700-19ca-11eb-9b91-6357cde50e68.PNG)
**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher 2.5.1
- Installation option (single install/HA): HA (3 node)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere Provision Cluster or RKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.18.9

- Docker version (use `docker version`): 19.3.8

**Comment by fad3t** [comment]
Hi,

I'm having the same issue on Rancher 2.5.3 (running on top of RKE 1.18.10).

I have the default chart repositories configured (Partners and Rancher). Refreshing them seems to be OK (they're marked as Active).
However in the Charts section, the list is empty. I'm getting the same "undefined: undefined" error whenever I try to refresh the list of charts.

Note this cluster was upgraded from 2.4.x.

Any suggestion is welcome :blush:
Fred.

**Comment by axeljnilsson94** [comment]
Hi,

In my case the entire Rancher installation is on premise with no internet connection. So the default charts are not suppose to be available.

 I am limited in which logs and monitoring I can share on this forum. @fad3t perhaps you could provide some Rancher logs and installation details to help the Rancher guys locate the issue?

Best regards
Axel
