### ISSUE TITLE
Deactivate/Delete buttons on overly showing up before rest of overlay

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2982]
Version - Master 12/10

Steps:
1.  Go to Manage Environments
2.  Click on deactivate for an environment

Results:
The Deactivate button shows up before the overlay has dropped down.  This is now true with all overlays, including the ones for Edit and Delete.  This wasn't the case before and not sure if we changed the order in which things are created.  But it's weird to see the buttons on the page before the overlay is ready.

Expected:
Not to see the buttons before the overlay is ready.

**Comment by vincent99** [comment]
This was fixed a while ago when the modal library changed..

**Comment by tfiduccia** [comment]
Version - 1.2.0-rc2
Verified fixed
