### ISSUE TITLE
Bump RKE2 version

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#29825]
The rancher/rke2 team is planning an RKE2 release on or around ~11/2/20~ 11/11/20.
The RKE2 version used in any Dockerfiles, etc should be bumped accordingly.

You can reference https://github.com/rancher/rancher/pull/29367/files for where changes are needed.

**Comment by StrongMonkey** [comment]
@davidnuzik Can you move this out to 2.5.2?

**Comment by davidnuzik** [comment]
On 11/11 we will release `v1.18.11+rke2r1`

**Comment by davidnuzik** [comment]
@StrongMonkey @maggieliu we should bump to incoming v1.18.12+rke2r2 version that is incoming. I should use the same issue here (reopen it) or a new one?

**Comment by maggieliu** [comment]
Let's just re-open.

**Comment by rancher-max** [comment]
#### Validated on master build

**Results:**
Correctly using v1.18.12+rke2r2
I believe we should leave this open as there is a pending v1.18.13+rke2r1 release coming out that may hit before this rancher release.

**Steps:**
1. Build rancherd from master: `wget -O rancherd https://releases.rancher.com/rancherd/rancherd-master`
2. Make the binary executable
3. Run rancherd: `sudo RKE2_RUNTIME_IMAGE=rancher/rancher-runtime:v2.5.4-rc2 rancherd server --write-kubeconfig-mode 644 2>&1 &`

Validated that the image it pulls for `hardened-kubernetes` is v1.18.12+rke2r2.
Validated the node after coming up is version v1.18.12+rke2r2.
Validated that after running `rancherd reset-admin` the UI is available and appears to be generally functional.

**Comment by izaac** [comment]
```
export INSTALL_RANCHERD_VERSION=v2.5.4-rc4
curl -sfL https://get.rancher.io | sh -

[INFO]  using v2.5.4-rc4 as release
[INFO]  downloading checksums at https://github.com/rancher/rancher/releases/download/v2.5.4-rc4/sha256sum.txt
[INFO]  downloading tarball at https://github.com/rancher/rancher/releases/download/v2.5.4-rc4/rancherd-amd64.tar.gz
[INFO]  verifying installer
[INFO]  unpacking tarball file
Dec 12 00:19:25 izrd1 rancherd[1321]: time="2020-12-12T00:19:25Z" level=info msg="Pulling runtime image \"index.docker.io/rancher/rancher-runtime:v2.5.4-rc4\""
Dec 12 00:19:34 izrd1 rancherd[1321]: time="2020-12-12T00:19:34Z" level=info msg="Starting rke2 v2.5.4-rc4 (HEAD)"
Dec 12 00:19:36 izrd1 rancherd[1321]: time="2020-12-12T00:19:36Z" level=info msg="Pulling image docker.io/rancher/hardened-etcd:v3.4.13-k3s1..."
Dec 12 00:19:40 izrd1 rancherd[1321]: time="2020-12-12T00:19:40Z" level=info msg="Pulling image docker.io/rancher/hardened-kubernetes:v1.18.12-rke2r2-amd64..."

kubectl get no
NAME    STATUS   ROLES         AGE   VERSION
izrd1   Ready    etcd,master   66s   v1.18.12+rke2r2

rancherd --version
rancherd version v2.5.4-rc4 (HEAD)
go version go1.14.12
```

Rancher UI opens properly after the daemonset is in running state.
