### ISSUE TITLE
Add validation for generated changes in ci script

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#29821]
rancher/types drone script checks for generated changes: https://github.com/rancher/types/blob/release/v2.4/scripts/test
We should add the same in rancher so the builds will pass only if generated changes are included for release/v2.5 and master branches

**Comment by cbron** [comment]
Tasks issue: https://github.com/rancher/tasks/issues/119

**Comment by Jono-SUSE-Rancher** [comment]
Closing issue in favor of the task issue https://github.com/rancher/tasks/issues/119
