### ISSUE TITLE
[UI]Cannot load rancher-compose from View Config

### ISSUE THREAD

**Issue by shotai** [rancher/rancher#2983]
1. If create a service with 'Always run one instance of this container on every host' selected, the UI cannot show the rancher-compose.yml in View Config page.

2. If change the service from the drop down list, the configuration will not change to the selected service.

Rancher	v0.49.0
Cattle	v0.119.0
User Interface	v0.70.0
Rancher Compose	v0.6.0

![capture](https://cloud.githubusercontent.com/assets/8721272/11725367/639378cc-9f47-11e5-989a-07d6ea2fc105.PNG)

**Comment by deniseschannon** [comment]
The first one isn't a bug. Since you have a global scale, there is nothing in a rancher-compose.yml. 

The second one is a bug in the UI.

**Comment by vincent99** [comment]
`{}` is a valid empty YAML file.

Fixed the dropdown switching.

**Comment by tfiduccia** [comment]
Version - Master Jan 07
Verified fixed
