### ISSUE TITLE
[FATAL] leaderelection lost for cattle-controllers

### ISSUE THREAD

**Issue by braghettos** [rancher/rancher#29856]
**What kind of request is this (question/bug/enhancement/feature request):**
When I try to add a lot of chart repositories to the catalog, the Rancher Management Cluster doesn't answer anymore to the UI and the underlying infrastructure gets stucked.

**Steps to reproduce (least amount of steps as possible):**
terraform apply -target rancher2_catalog.catalogs 

**Result:**
The Rancher UI is not available anymore, CPU of kube-api-server is at 250% and taking all the available RAM.

**Other details that may be helpful:**
9 catalogs per 8 cluster. The total is 72.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher 2.4.8

- Installation option (single install/HA):
Both in single install and HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Cloud, 8 core and 32GB RAM

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Docker version 19.03.13, build 4484c46d9d
```

**Comment by raelix** [comment]
> **What kind of request is this (question/bug/enhancement/feature request):**
> When I try to add a lot of chart repositories to the catalog, the Rancher Management Cluster doesn't answer anymore to the UI and the underlying infrastructure gets stucked.
> 
> **Steps to reproduce (least amount of steps as possible):**
> terraform apply -target rancher2_catalog.catalogs
> 
> **Result:**
> The Rancher UI is not available anymore, CPU of kube-api-server is at 250% and taking all the available RAM.
> 
> **Other details that may be helpful:**
> 9 catalogs per 8 cluster. The total is 72.
> 
> **Environment information**
> 
> * Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
>   Rancher 2.4.8
> * Installation option (single install/HA):
>   Both in single install and HA
> 
> **Cluster information**
> 
> * Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
>   Custom
> * Machine type (cloud/VM/metal) and specifications (CPU/memory):
>   Cloud, 8 core and 32GB RAM
> * Kubernetes version (use `kubectl version`):
> 
> ```
> Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> * Docker version (use `docker version`):
> 
> ```
> Docker version 19.03.13, build 4484c46d9d
> ```

Same issue for me using terraform with a for_each for the catalogs creation goes in stuck with 503 and does not start anymore.
