### ISSUE TITLE
[Forwardport] Can't delete nodes from cluster in updating/error stat

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29852]
Forward port of https://github.com/rancher/rancher/issues/29801

**Comment by sowmyav27** [comment]
PRs:
https://github.com/rancher/rancher/pull/29847
https://github.com/rancher/rancher/pull/29846

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `cc777eb` and master-head - commit id: `d61a1a4a`**
- Validated the original issue - [here](https://github.com/rancher/rancher/issues/29801#issue-730950421) using automation and it is seen fixed.
- Validated upgrade of cluster - drain enabled/disabled
- Validated adding/deleting worker nodes from node driver and custom clusters. NO issues seen

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head cc777eb
rancher/rancher:master-head 5d3ffc1

Performed regression testing around vSphere PV drain

* Create a cluster w/ cloud provider on vSphere
* Create a workload w/ a PV attached
* Delete the node where the workload is running
* Workload is drained, scheduled to another node
* PV is attached to the rescheduled workload
