### ISSUE TITLE
[Monitoring V2] Rebase rancher-monitoring to kube-prometheus-stack 14.x.x

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29871]
**What kind of request is this (question/bug/enhancement/feature request):**
feature enhancement

The current upstream chart [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) has been updated to version 10.x.x (compared to Rancher Monitoring at 9.4.2) and supports Prometheus Operator version `0.42.1`, which adds support for a whole host of features including:
- A brand new `Probe` CRD
- Updated images that could allow us to support ARM (https://github.com/rancher/rancher/issues/29015)

This new version will also drop support for clusters that are not k8s 1.16+ due to the new [`kubeVersion`](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/Chart.yaml#L23).

The current monitoring chart needs to be rebased against this new upstream to absorb these enhancements.

gz#13675
gz#14300
gz#14609
gz#15721
gz#15408
gz#15614

**Comment by bashofmann** [comment]
kube-prometheus-stack 11.0.0 has been released yesterday, which includes prometheus-operator 0.43.0 (https://github.com/prometheus-community/helm-charts/pull/280) including the AlertmanagerConfigs CRDs.

**Comment by aiyengar2** [comment]
As noted in https://github.com/rancher/image-mirror/pull/49#pullrequestreview-530412079, although we already merged a Prometheus Operator image for v0.43.0 in https://github.com/rancher/image-mirror/pull/47 to `rancher/coreos-prometheus-config-reloader` and `rancher/coreos-prometheus-operator`, we should actually be pushing those images new repositories at `rancher/prometheus-operator-prometheus-operator` and `rancher/prometheus-operator-prometheus-config-reloader`.

When this issue is reprioritized, we should redo the image updates with the new repository.

**Comment by immanuelfodor** [comment]
I'm coming from https://github.com/rancher/rancher/issues/29149 and the rebase would include the option to disable the subPath config which would make Local Path Provisioner work with Prometheus: https://github.com/rancher/local-path-provisioner/issues/4 I have a dirty hack now to make it still work but it needs a permanent solution provided by this issue. Hope it will progress soon.

**Comment by aquam8** [comment]
Please keep this in upcoming 2.5.7 and not delay any further, thank you

**Comment by dbason** [comment]
Bumping the version of Prometheus is also worthwhile.  Prometheus 2.19.x has reasonable improvements in memory usage and start-up time.

**Comment by aiyengar2** [comment]
Rebasing will also resolve Monitoring-related concerns from https://github.com/rancher/rancher/issues/31514.

**Comment by immanuelfodor** [comment]
By the way, is anybody working on this or we are all just waiting for somebody from Rancher to pick it up? 😃

**Comment by immanuelfodor** [comment]
Nevermind, I've just seen the new working flag (3 days ago).

**Comment by aiyengar2** [comment]
#### Note for QA

There are two primary things that need to be tested outside of all monitoring tests today:
1. Grafana introduced grafana.imageRenderer.enabled, which [replaces PhantomJS](https://grafana.com/blog/2020/05/07/grafana-7.0-preview-new-image-renderer-plugin-to-replace-phantomjs/) in rendering PNGs from graphs. This code path needs to be tested in hardened (with CIS 1.16 scan) + windows clusters to ensure newly added annotations / PSP logic is sufficient.
2. The nginx proxy for Prometheus has been changed from port 8080 to 8081 due to Prometheus Operator hard-coding 8080 as the port for the configReloader in Prometheus Operator v0.43.0. This code path also needs to be tested, specifically in upgrade scenarios.

**Comment by aiyengar2** [comment]
For anyone following this issue, once this upgrade is complete we will be at:
- kube-prometheus-stack 14.5.0
- grafana 6.6.4
- kube-state-metrics 2.13.1
- node-exporter 1.16.2
- prometheus-adapter 2.2.1

This means we are at the tip for kube-prometheus-stack, with all dependencies updated to the latest that can is supported by that version of the chart today.

**Comment by aiyengar2** [comment]
This issue should also be tested to see if it addresses https://github.com/rancher/rancher/issues/29015.

I've updated the Prometheus Adapter repository to use the one that supports ARM images too. I believe Grafana and kiwi grid also support ARM now at the image versions we are at.

cc: @joshimoo

**Comment by slickwarren** [comment]
Tests performed on 2.5.8-rc2 using monitoring v14.5.100-rc5:
(all done on windows and linux clusters)
clean install — fail (existing configmap)
Upgrade 9.4.20x -> 14.5.100 — pass
uninstall + reinstall — fail (existing configmap)

Uninstall upgraded 14.5.100 — pass
Uninstall clean 14.5.100 — pass
**Master-head base case - install latest + p0 testcase — issue on master-head, filing forwardport for this** 
ARM install — PASS!
monitoring v1 to v2 — pass

rbac — view only — pass
rbac — cluster owner — pass

alerts (slack) — pass
custom metrics (prometheus) — pass
pod monitor — pass
custom prom rule — pass
scrape interval — prometheus — pass
resource limits — prometheus — pass
PV — prometheus — pass

1.16 k8s — pass
1.15 k8s — Error: chart requires kubeVersion: >=1.16.0-0 which is incompatible with Kubernetes v1.15.12 (Expected)



PV — grafana statefulset — pass
PV persist graphs in grafana — pass
ALL grafana.searchNamespace — pass
custom grafana.searchNamespace — pass
custom grafana.namespace — pass


CIS benchmark — pass (with and without imageRenderer)

Grafana.imageRenderer — CIS scan pass
grafana.imageRenderer — Windows pass
grafana.imageRenderer — linux pass

prom port 8080 -> 8081 appears to be working fine
Upgrade from 9.4.20X -> 14.5.100-rcX — pass
