### ISSUE TITLE
Helm error on Rancher upgrade from 2.5.1 to 2.5.2-rc4 and also on fresh install of 2.5.2-rc4

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29874]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- Install Rancher RKE HA v2.5.1 (Bring your own valid certs method)
- Here I configured a few apps like logging, monitoring, istio, etc.
- Upgrade HA to v2.5.2-rc4

**Result:**

`Error: UPGRADE FAILED: cannot patch "rancher" with kind Ingress: Ingress.extensions "rancher" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified`

![Screen Shot 2020-10-30 at 5 22 12 PM](https://user-images.githubusercontent.com/27659/97766632-7ac43500-1ad4-11eb-95f6-428bda946ae0.png)

**Other details that may be helpful:**

```
 k get po -n cattle-system
NAME                               READY   STATUS             RESTARTS   AGE
helm-operation-cp6qz               0/2     Completed          0          12m
helm-operation-kxph9               0/2     Completed          0          11m
helm-operation-ntqxn               0/2     Completed          0          11m
helm-operation-pwgzb               0/2     Completed          0          10m
helm-operation-qcvwn               0/2     Completed          0          10m
rancher-589757dd7-ggmv2            0/1     CrashLoopBackOff   6          13m
rancher-589757dd7-h84dg            0/1     CrashLoopBackOff   6          13m
rancher-589757dd7-tc5l7            0/1     CrashLoopBackOff   6          13m
rancher-webhook-698dd9dc76-9vcb6   1/1     Running            0          11m
```

**Environment information**
- Rancher version: `v2.5.1` upgrade to `v2.5.2-rc4`
- Installation option: HA

**Cluster information**
- Cluster type: Infrastructure Provider Linode Driver RKE
- Machine type: VM Worker nodes 8 GB RAM and 4vcpu
- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sowmyav27** [comment]
**Issue seen on a fresh install of `2.5.2-rc4` also**
```
./helm3 install rancher rancher-latest/rancher --version 2.5.2-rc4 --namespace cattle-system --set hostname=<hostname>
Error: Ingress.extensions "rancher" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified
```

**Comment by mrajashree** [comment]
Rancher chart's [ingress.yaml](https://github.com/rancher/rancher/blob/release/v2.5/chart/templates/ingress.yaml#L39) needs to add [pathType](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#httpingresspath-v1-networking-k8s-io) which seems to be the required/missing field

**Comment by cbron** [comment]
This is really just a side-effect of https://github.com/rancher/rancher/issues/29144
We can close this and move that to re-opened.

**Comment by sowmyav27** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/29144
