### ISSUE TITLE
error: endpoints "default-http-backend" not found

### ISSUE THREAD

**Issue by zzbmmbzz** [rancher/rancher#29891]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Install rancher with guide: https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/

1. `kubectl create namespace cattle-system`
```
root@rancher01:~# kubectl describe namespaces cattle-system
Name:         cattle-system
Labels:       field.cattle.io/projectId=p-rrkcg
Annotations:  cattle.io/status:
                {"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2020-11-02T04:01:28Z"},{"Type":"InitialRolesPopu...
              field.cattle.io/projectId: local:p-rrkcg
              lifecycle.cattle.io/create.namespace-auth: true
Status:       Active

No resource quota.

No LimitRange resource.
```

2. Install Rancher with certificates from files
`kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=./keys/tls.crt --key=./keys/tls.key`
```
root@rancher01:~# kubectl describe secret tls-rancher-ingress -n cattle-system   
Name:         tls-rancher-ingress
Namespace:    cattle-system
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
tls.crt:  2374 bytes
tls.key:  1730 bytes
```

3. Install Rancher 
`helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=[domain_name] --set ingress.tls.source=secret`

4. Verify that the Rancher Server is Successfully Deployed
`kubectl -n cattle-system rollout status deploy/rancher`
```
deployment "rancher" successfully rolled out
```

**But when I check on ingress, I got this error: **
`Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)`
Full detail:
```
root@rancher01:~# kubectl describe ing rancher -n cattle-system
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Name:             rancher
Namespace:        cattle-system
Address:          localhost
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  tls-rancher-ingress terminates example.com
Rules:
  Host                     Path  Backends
  ----                     ----  --------
  rancher-test.pal.net.vn  
                              rancher:80   10.42.0.7:80,10.42.0.8:80,10.42.0.9:80)
Annotations:               field.cattle.io/publicEndpoints:
                             [{"addresses":[""],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"r...
                           meta.helm.sh/release-name: rancher
                           meta.helm.sh/release-namespace: cattle-system
                           nginx.ingress.kubernetes.io/proxy-connect-timeout: 30
                           nginx.ingress.kubernetes.io/proxy-read-timeout: 1800
                           nginx.ingress.kubernetes.io/proxy-send-timeout: 1800
Events:
  Type    Reason  Age                From                      Message
  ----    ------  ----               ----                      -------
  Normal  CREATE  17m                nginx-ingress-controller  Ingress cattle-system/rancher
  Normal  UPDATE  16m (x2 over 17m)  nginx-ingress-controller  Ingress cattle-system/rancher
```

**Cluster information**
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 8 cores CPU, 16GB RAM
- Kubernetes version (use `kubectl version`):

```
root@rancher01:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
root@rancher01:~# docker version
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:18 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:23:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

I tried searched on Google but still can not solve this problems, so please help me for this one. If you need more information please let me know.
Thanks

**Comment by zzbmmbzz** [comment]
I have try access test domain and it work normally. I check on load balancing and it does not facing any errors, but I checked with `kubectl` command it still facing error: `Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)`
May I know what is the difference or what things that I missed?
Thanks

On web console:
![image](https://user-images.githubusercontent.com/41033532/97830878-01f5f080-1d01-11eb-92c3-6dad0a27cb7f.png)

kubectl command:
![image](https://user-images.githubusercontent.com/41033532/97830753-a3307700-1d00-11eb-8274-6e1be2a11dc8.png)
![image](https://user-images.githubusercontent.com/41033532/97830829-e2f75e80-1d00-11eb-8de2-d10f9d716d30.png)

**Comment by Oats87** [comment]
That is a benign error -- https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L2473

The Ingress object that the rancher chart creates does not define a default backend (because we don't need one), and thus `kubectl` falls back to trying to find the `default-http-backend` in `kube-system` which does not exist.

The "real" `default-http-backend` that comes with `RKE` can be found in `nginx-ingress`.

```
kubectl describe endpoints default-http-backend -n ingress-nginx
```

**Comment by zzbmmbzz** [comment]
yah, Thanks for your explanation.
