### ISSUE TITLE
Invalid kiali WEB_ROOT in 2.5 rancher-kiali-server charts

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#29898]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Install rancher-istio (which includes rancher-kiali-server) in Rancher 2.5 through the Cluster Explorer
* Go to Istio -> Kiali
* Refresh the page

**Result:**
The URL in the browser is rewritten to an invalid proxy URL and the proxy endpoint returns an error

![Bildschirmfoto 2020-11-02 um 14 16 57](https://user-images.githubusercontent.com/243056/97872846-fc0b0a00-1d16-11eb-947a-adf0dd6b95e2.png)

**Other details that may be helpful:**
The kiali service is not called `rancher-istio-kiali` anymore, but `kiali`. The overwritten `WEB_ROOT` url in https://github.com/rancher/charts/blob/dev-v2.5-source/packages/rancher-kiali-server/rancher-kiali-server.patch#L125 still references the old(?) service name. Also from my testing a `/kiali` suffix seems to be necessary now.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.2-rc6
- rancher-istio version: 1.7.300
- Installation option (single install/HA): HA

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.5.2-rc6`

Steps:
Install rancher-istio in Rancher 2.5 through the Cluster Explorer
Go to Istio -> Kiali
Refresh the page

Result:
Page refreshes to the following:
![Screen Shot 2020-11-16 at 3 08 29 PM](https://user-images.githubusercontent.com/57409052/99315820-7d3ac480-2820-11eb-8099-dd87135e0068.png)

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.5-head` `version 71da156`

Kiali is loaded properly on refresh.

**Comment by aaronRancher** [comment]
This behavior is still seen in Rancher server `rancher\rancher:master-head` `version b72b399`

Reopening for a fix in master-head.

**Comment by bashofmann** [comment]
Do we need to merge the fix in the chart somewhere else for this as well?

**Comment by aaronRancher** [comment]
Whoops. Did not have system-charts pointing to the correct branch. 
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version c845a29`
Kiali is loaded properly on refresh.
