### ISSUE TITLE
UI: Links in certificates domain names are incorrect

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2989]
In the Infrastructure/Certificates page, open any existing certificate.
In the Domain Names frame, the CN and other AltNames of the cert are listed, as links.

These should be linked to https://domainname/ but are instead linked to /domainname, which means that clicking will send you to https://rancherserver/domainname which is incorrect and results in a Jetty error page.

**Comment by tfiduccia** [comment]
Version - master jan 07
Verified fixed
