### ISSUE TITLE
Istio v2: Jaeger

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29903]

**Comment by cbron** [comment]
example of addon: https://istio.io/latest/docs/ops/integrations/jaeger/

**Comment by cbron** [comment]
Also need to add documentation around our approach in docs and readme

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 8d759be
rancher/rancher:master-head e4ce376

* Create a cluster
* Install Istio app w/ Jaeger & ingress gateway enabled
* Deploy demo bookservice
* Send 100 requests to the service through the ingress gateway:
```
for i in {1..100}; do curl http://<worker_node>:31380/productpage; done
```
* From Istio dashboard page, navigate to Jaeger
* Service dropdown should contain multiple services, tracing should work
