### ISSUE TITLE
[EKSv2]: Rancher should be able to fully communicate with private EKS clusters

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#29907]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Create or register private EKS cluster (a cluster that only has Private Access enabled).

**Result:**
Error: "Failed to communicate with cluster.
Even if a cluster is created as Public/Private then has public disabled, the agent will connect but health checks will error.

**Desire:**
Registering a private EKS cluster should work and rancher should be able to communicate with it.
Creating a private EKS cluster should work. This flow will still require the user to use a command to deploy the agent, similar to regular imported clusters, described here:  https://github.com/rancher/rancher/issues/28356.

**Notes:**
It is possible to import a private cluster through regular import. This is because imported clusters tunnel any communication between rancher and the downstream server through the agent and communicate with the kubernetes service IP (which is private) instead of the public endpoint. The solution for this should probably use this same approach for EKS clusters. Requests should be tunneled and instead of using the public Kube API endpoint, the kubernetes service ip should be used. Part of this is handled in authorizeCluster function located in pkg/tunnelserver/tunnel.go.

This is blocking: https://github.com/rancher/rancher/issues/28356

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `395b4fe77`**

Validated the following use cases:

**Use case#1**

- Deploy an EKS cluster with only Private access enabled.
- The cluster comes to Waiting to register state
- Import the cluster using import command from Rancher UI ( rancher server is on the same subnet/security group as the EKS cluster).
- Eks cluster come sup Active.

**Usecase#2**

- Edit the above created cluster.
- Add a nodegroup
- Save changes made.
- Cluster goes into Updating state and nodes get added and the cluster comes up Active.

**Usecase#3**

- Edit the above cluster. Update the k8s version. Save the changes made.
- Cluster goes into Updating state

**Comment by aaronRancher** [comment]
This enhancement is verified with Rancher server `rancher\rancher:master-head` `version e129f92` and `rancher\rancher:master-head` `version 6ad4dce72`

**Hosted EKS cases:**
Use case#1
- Deploy an EKS cluster with only Private access enabled.
- The cluster comes to Waiting to register state
- Import the cluster using import command from Rancher UI ( rancher server is on the same subnet/security group as the EKS cluster).
- Eks cluster come sup Active.

Use case#2
- Deploy an EKS cluster with both Private and Public access enabled.
- Wait for cluster to become active.
- Edit cluster. Disable Private access.
- Wait for cluster to update.
- Edit cluster. Verify Rancher can still reach cluster.

Use case#3
- Deploy an EKS cluster with Public access enabled.
- Wait for cluster to become active.
- Edit cluster. Disable Public access. Enable Private access.
- Wait for cluster to update.
- Edit cluster. Verify Rancher can still reach cluster.

**Imported EKS cases:**
Use case#1:
- In EKS console, create a cluster with only Private access.
- In Rancher, import cluster using cluster-agent import command.
- EKS cluster becomes active.

Use case#2:
- In EKS console, create a cluster with Public and Private access.
- In Rancher, import cluster.
- Wait for cluster to become active.
- Edit cluster. Disable Public access. Enable Private access.
- Wait for cluster to update.
- Edit cluster. Verify Rancher can still reach cluster.

**Comment by aaronRancher** [comment]
Tested an additional use case for hosted private EKS cluster.

- Create a single node Rancher setup in DO (separated from EC2 VPCs and subnets).
- In Rancher, deploy an EKS cluster with only Private access enabled.
- The cluster comes to Waiting to register state
- Import the cluster using import command from Rancher UI (cluster must be reached from the same VPC and subnet)
- EKS cluster comes up Active.

**Comment by jinzishuai** [comment]
> * Import the cluster using import command from Rancher UI (cluster must be reached from the same VPC and subnet)
> * EKS cluster comes up Active.

Thank you @aaronRancher  I have a similar problem but instead of k3s and EKS being on the same VPC and subnet, they are in difference AWS accounts with VPC peering cross-connected with unrestricted networking. Is there any reason for that not to work in the same procedure as you described?  Thanks.

**Comment by jinzishuai** [comment]
> > * Import the cluster using import command from Rancher UI (cluster must be reached from the same VPC and subnet)
> > * EKS cluster comes up Active.
> 
> Thank you @aaronRancher I have a similar problem but instead of k3s and EKS being on the same VPC and subnet, they are in difference AWS accounts with VPC peering cross-connected with unrestricted networking. Is there any reason for that not to work in the same procedure as you described? Thanks.

Never mind. I got it it working after mapping the role/user: https://eksctl.io/usage/iam-identity-mappings/#manage-iam-users-and-roles
And in my experience with v2.5.5, I didn't even have to do the manual import command (I am using EKSv3). Thanks.
