### ISSUE TITLE
[UI] Add 2 LB selection for AKS

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#29908]
EDIT: The `AgentStorageProfile` change is purely on the backend. Only the 2 LB selection is needed for AKS.

~~The current Azure API does not use `AgentStorageProfile` for `ManagedClusterAgentPoolProfile`. It should be removed from the UI, dependent on the below PR being merged.~~

- Related issue: https://github.com/rancher/rancher/issues/23715
- Discussion context: https://github.com/rancher/rancher/pull/29901#discussion_r516197359
- Dependent PR: https://github.com/rancher/rancher/pull/29901
- Go module for Azure API: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-09-01/containerservice#ManagedClusterAgentPoolProfile

**Comment by maggieliu** [comment]
Also need the ability to select between the 2 LB options for AKS. Combining #29902 into this one.

**Comment by cbron** [comment]
This should happen for both 2.4 and 2.5.

**Comment by westlywright** [comment]
The UI doesn't expose the `AgentStorageProfile`, I dont think we ever have. I am adding the new lb sku param though.

**Comment by westlywright** [comment]
Exposed the loadBalancerSku on Azure AKS cluster create in a new select field. Available in `latest2`, `latest-2.5` & `latest-2.4`

**Comment by sowmyav27** [comment]
**Validated on 2.4-head commit id: `a61621e57`**

- Create an AKS cluster. Options seen on the UI
<img width="822" alt="Screen Shot 2020-11-03 at 2 34 57 PM" src="https://user-images.githubusercontent.com/26032343/98053176-d6503480-1dec-11eb-83d9-a3c61d3012d6.png">

- Select Basic/Standard and create the cluster. When the cluster comes up, verified in the backend LB is set as basic/Standard.

**Comment by cbron** [comment]
Re-opening to handle new backend with default empty string.

**Comment by westlywright** [comment]
* On cluster create the UI will set default value for  `loadBalancerSku` to `standard`. 
* On cluster edit, UI does nothing with the field, user can not change the value. 
* Ive also added logic that if the `loadBalancerSku` is undefined or empty string and mode is edit, we don't show the LoadBalancer Sku select input.

**Comment by sowmyav27** [comment]
Reopening this for a fix as per the latest discussions offline. 
Expected: Basic should be seen as default in the dropdown for `loadBalancerSku`

**Comment by sowmyav27** [comment]
**On 2.4-head - commit id: `2bc5432cd`**

- Deploy an AKS cluster . Select loadBalanceSku = Standard and create the cluster.
- API request sent contains "loadBalanceSku"=basic.

Reopening the issue.

**Comment by sowmyav27** [comment]
**On 2.4-head - commit id: `2bc5432cd`, 2.5-head commit id: `715fcc719` and on master-head - commit id: `ad28e2661`**

- Deploy an AKS cluster . Select loadBalanceSku = Standard/basic and create the cluster.
- AKS cluster created has loadBalanceSku set to standard/basic
- Also the default value in the drop down in "Basic"
