### ISSUE TITLE
[Monitoring / Alerting] Create scripts for auditing what needs to be disabled to remove Monitoring / Alerting V1

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29905]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

As documented in https://github.com/rancher/dashboard/issues/1167, we currently cannot deploy Monitoring V2 for users who are have Monitoring / Alerting V1 enabled in their cluster due to the existence of >1 operator (adding support for deploying both is tracked in https://github.com/rancher/rancher/issues/28513).

However, preventing Rancher ECM from deploying Prometheus Operator for Monitoring V1 / Alerting V1 can be tricky due to the current logic used to determine whether Monitoring / Alerting V1 should be enabled in the cluster. Disabling it involves:
- Disabling Project Monitoring through every single Project within the cluster (e.g. `project.Spec.EnableProjectMonitoring=false` for all projects)
- Deleting all <Cluster|Project>AlertRules that reference a notifier (which sets `cluster.Spec.EnableClusterAlerting=false`) and/or deleting all notifiers
- Disabling Cluster Monitoring (e.g. `cluster.Spec.EnableClusterMonitoring=false`)

There are also issues that could be brought up based on whether the RKE template used by a user requires that monitoring or alerting be enabled on a cluster level.

Ideally, there should be a script that a cluster owner should be able to run that is able to "audit" what configuration a user may have failed to disable when trying to remove Monitoring V1 from a cluster. It would also be nice if this could be contained within a k8s manifest for a `Job` that a user can deploy onto their cluster.

**Comment by jiaqiluo** [comment]
The following cases are tested for this script.

test case | expected result| result
----------| ---------------| -------
cluster monitoring is enabled | the warning message should show in the output| pass
project monitoring is enabled | the warning message should show in the output| pass
project monitoring is enabled in more than 1 cluster | the warning message should show in the output|  pass
notifier is added but not used by any alert | no warning should show | pass
notifier is added and used by any cluster alert | the warning message should show in the output|  pass
notifier is added and used by any project alert | the warning message should show in the output|  pass
RKE Template is used and enable_cluster_monitoring is true | the warning message should show in the output|  pass
RKE Template is used and enable_cluster_monitoring and enable_cluster_alerting are true | the warning message should show in the output|  pass
RKE Template is used and enable_cluster_alerting is true | the warning message should show in the output|  **failed** 

Where there is only the `enable_cluster_alerting` is `true` in the cluster template revision, there will be no `monitoring-operator` app deployed in the cluster, and `enableClusterAlerting` and `enableClusterMonitoring` are false when viewing the cluster in API. Therefore the script does not return any warning message. 

Adding a notifier and assigning it to an alert group triggers the deployment of the `monitoring-operator` app, but setting enableClusterAlerting true in the template does not. I am not sure if this is a problem and if we need to handle it in the script.

**Comment by aiyengar2** [comment]
@jiaqiluo I think the failed case above should be fine. Even if the user has `enable_cluster_alerting=true`, it shouldn't affect their ability to deploy Monitoring V2 unless, as you mentioned, they add a notifier and assign it to an alert group. So the overall purpose of the script (e.g. to assist users in migrating from Monitoring / Alerting V1 to V2) is still accomplished.

@bashofmann would you agree or do you think the script should be fixed to still throw out a warning in that case?

**Comment by jiaqiluo** [comment]
@aiyengar2  I agree and I am ok to close this issue if @bashofmann  says yes.

**Comment by bashofmann** [comment]
Thanks @jiaqiluo for testing all these different cases. 

I agree, I don't think we have to handle the "RKE Template is used and enable_cluster_alerting is true" case.

**Comment by aiyengar2** [comment]
Awesome, let's close this issue then.
