### ISSUE TITLE
Use third-party JWTs for authentication against Rancher/Kubernetes API

### ISSUE THREAD

**Issue by bradjones1** [rancher/rancher#29914]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature request

**Steps to reproduce (least amount of steps as possible):**

Currently, users (or the API) can create tokens in Rancher to access the Rancher and Kubernetes APIs through Rancher, where their permissions are resolved against Rancher's authorization scheme. However, this requires the tokens be created in advance by the user and loaded into any external system requiring programmatic access. It's possible to use products like Vault to further provide an abstraction around secrets storage, but the API key lifecycle is up to the user.

**Result:**

As a result of the current API key-only approach, we are unable to use technology such as JWT (JSON Web Tokens) which would allow third-party auth providers to sign a token that could then be used to identify a user. This could be done by consulting an assertion value that maps to the canonical user ID in Rancher, for instance.

**Other details that may be helpful:**

I researched other open or closed tickets and didn't find a similar request.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.x
- Installation option (single install/HA): HA with Helm 3

**Comment by bradjones1** [comment]
Not stale.

**Comment by bradjones1** [comment]
Not stale.

**Comment by glermaidt** [comment]
THIS^! - We cannot get Vault Kubernetes Auth integration to work on Rancher RKE clusters.

**Comment by glermaidt** [comment]
Not stale
