### ISSUE TITLE
fix some machine config options

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#2991]
rename engineOpts to engineOpt
change type of engineOpt, engineLabel, and engineEnv from string array (with values like "key=val") to map like: {"key": "val"}

**Comment by cjellick** [comment]
sorry sangeetha, i realize you just tested these

**Comment by cjellick** [comment]
@vincent99 will have ui support for these today, so you could way until they are in the ui and test them that way

**Comment by sangeethah** [comment]
sure @cjellick . I will wait for the UI to be available and make sure all the engine opts settings works as expected.

**Comment by sangeethah** [comment]
Tested with latest build from master  - Dec 11.

UI has support for adding all machine config options when adding hosts.

Able to add Digital Ocean machine successfully using all the "DOCKER ENGINE" options available in the UI.
