### ISSUE TITLE
Disable the ability to uncheck the "Public Access" checkbox

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#29921]
Currently, EKS has the Public and Private access as checkboxes, but we rely on the public endpoints of the EKS cluster for the cluster to connect with Rancher. 

Let's grey out (disable) the ability to un-check the Public Access checkbox. 

<img width="491" alt="Screen Shot 2020-11-03 at 2 24 28 PM" src="https://user-images.githubusercontent.com/11410997/98047202-676cde80-1de0-11eb-877c-539ca29791fd.png">

Due to https://github.com/rancher/rancher/issues/29907

**Comment by deniseschannon** [comment]
Please test that on create and edit, you cannot uncheck the public access checkbox.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 0852920` and `rancher\rancher:v2.5-head` `version 2859fc5`

Public access checkbox is greyed out and cannot be deselected.
<img width="830" alt="Screen Shot 2020-11-04 at 7 50 39 AM" src="https://user-images.githubusercontent.com/57409052/98126446-d6931300-1e72-11eb-8642-a0a263f26d34.png">
<img width="690" alt="Screen Shot 2020-11-04 at 7 52 16 AM" src="https://user-images.githubusercontent.com/57409052/98126477-e01c7b00-1e72-11eb-9639-d8ac82c9f3c6.png">

**Comment by aaronRancher** [comment]
Reopening to verify from hosted EKS cluster.

**Comment by westlywright** [comment]
We are rolling back the change to `disable` the checkbox but the tooltip warning will remain in place.

**Comment by sowmyav27** [comment]
**On master-head commit id: `6d4d6b0` ui tag: `latest2` and 2.5-head commit id: `6d4d6b0` ui tag: `latest-2.5`**

- During an edit and create of a Hosted EKS cluster, this tooltip is seen
<img width="454" alt="Screen Shot 2020-11-04 at 8 39 13 PM" src="https://user-images.githubusercontent.com/26032343/98199674-98343d00-1ee0-11eb-9043-c2ef307ca42a.png">

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 3ac4845` and `rancher\rancher:v2.5-head` `version 31a25e7`

- On an edit of an imported EKS cluster, public access can be unchecked. Tooltip is still seen.

![Screen Shot 2020-11-05 at 10 12 57 AM](https://user-images.githubusercontent.com/57409052/98273486-8fc71b00-1f4f-11eb-910c-4c7fbd01592c.png)
