### ISSUE TITLE
Error from server (InternalError): an error on the server ("error trying to reach service: write tcp 172.17.0.2:443->10.143.129.27:6981: i/o timeout") has prevented the request from succeeding

### ISSUE THREAD

**Issue by wwwlde** [rancher/rancher#29928]
**What kind of request is this (question/bug/enhancement/feature request):**

```
Error from server (InternalError): an error on the server ("error trying to reach service: write tcp 172.17.0.2:443->10.143.129.27:6981: i/o timeout") has prevented the request from succeeding
```

Time after time I got following error while trying to reach k8s cluster via kubectl and rancher UI. I do not really understand to what direction to search for a problem. Could you suggest something? Is this some network issue or something else?

**Steps to reproduce (least amount of steps as possible):**

This error is not permanent. Can't reproduce it in permanent way.

```
$ kubectl -n monitoring logs -f -l app=prometheus --all-containers=true | grep -i -E 'duplicate|order'
```

**Result:**

```
Error from server (InternalError): an error on the server ("error trying to reach service: write tcp 172.17.0.2:443->10.143.129.27:6981: i/o timeout") has prevented the request from succeeding
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

v2.5.1

- Installation option (single install/HA):

Single install

**Cluster information**

- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):

AWS

- Machine type (cloud/VM/metal) and specifications (CPU/memory):

VM

- Kubernetes version (use `kubectl version`):

```
1.16
```

- Docker version (use `docker version`):

```
19.03.6-ce
```

**Comment by lucasrodri** [comment]
Hi @wwwlde,

The same problem happened to me after I apply an app (graylog).

I just restarted the docker images with "docker restart $ (docker ps -a -q)" and everything went back to normal.
