### ISSUE TITLE
Drop-down to switch another certificate doesn't work

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2992]
Version - Master 12/10

Steps:
1.  Go to Certificate Page
2.  Add two Certs
3.  Click on Cert name to go to details page
4.  Try to use drop-down at top of page to switch to other cert

Results:  In the UI nothing happen, in dev tools you see an error - Uncaught TypeError: Cannot read property 'transitionToRoute' of undefined.

Expected:  Should switch.

**Comment by sangeethah** [comment]
Tested with latest build from master:
Able to use Drop-down to switch another certificate from certificate detail page.
