### ISSUE TITLE
Error while upgrading AKS cluster on an upgraded rancher setup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29924]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy an AKS cluster - 1.17.11 k8s version on 2.4.8
- Upgrade rancher to 2.4-head
- Edit cluster --> loadBalancerSku is seen set to "Standard"
<img width="459" alt="Screen Shot 2020-11-03 at 6 06 58 PM" src="https://user-images.githubusercontent.com/26032343/98061325-76638900-1e00-11eb-84e8-6438d04ec42e.png">

- Upgrade k8s version to 1.18.8 and save changes made
- `loadBalancerSku` value sent in the API request is "Standard"
- Error seen on the cluster `Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PropertyChangeNotAllowed" Message="Changing property 'networkProfile.loadBalancerSku' is not allowed." Target="networkProfile.loadBalancerSku"` 

**Expected Result:**
UI should not show default value "Standard". The loadBalancerSku for clusters from 2.4.8 is "basic"

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): upgrade form 2.4.8 to 2.4-head commit id: `a61621e57`
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AKS
- Kubernetes version (use `kubectl version`):

```
1.17 to 1.18
```

**Comment by cbron** [comment]
Closing for now as issues appear isolated to backend, the already existing issue.
