### ISSUE TITLE
Set display-name in charts for UI 

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#29934]
This only changes how the UI displays our feature charts, has no functional changes.

**Comment by izaac** [comment]
Rancher version: `master-head (11/05/2020)` _3ac4845_

The names displayed in the UI  are matching the `catalog.cattle.io/display-name` annotation.

![Screen Shot 2020-11-05 at 10 08 49 AM](https://user-images.githubusercontent.com/27659/98273004-00216c80-1f4f-11eb-867e-9e7b4f329cd0.png)


Removing the `"catalog.cattle.io/hidden": "true"` annotation from Rio to validate it too:

![Screen Shot 2020-11-05 at 10 25 45 AM](https://user-images.githubusercontent.com/27659/98275029-65765d00-1f51-11eb-82d3-ba2e18b54e43.png)

**Comment by izaac** [comment]
Rancher version: `v2.5-head (11/05/2020)` _31a25e7_
Validated the display name. The [same checks](https://github.com/rancher/rancher/issues/29934#issuecomment-722522684) done in `master-head`
