### ISSUE TITLE
Question: Can i use rancher-monitoring chart in a rke only no rancher cluster?

### ISSUE THREAD

**Issue by IJOL** [rancher/rancher#29938]
As said i'm trying to have monitoring activated in my rke only no rancher k8s cluster, is that possible? are  there any ties with rancher, I've overlooked in the charts?

I've  used rke v1.1.3, which sections should apply to my install in the values file assuming the former answer is yes? rke or rke2 ones?

My only objective with monitoring is to see how etcd  is doing, and the standard prometheus stack doesn't give that to me out of the box, for my rke cluster, so I'm trying that charts.. if anyone can give me better advice i will be graefull..

**Comment by IJOL** [comment]
Are there any repos a standard helm v3 could use to install it, or I need to go with the sources ?

**Comment by aiyengar2** [comment]
The Helm Repo used by Rancher is http://charts.rancher.io (you can check chart versions at the [index.yaml](http://charts.rancher.io/index.yaml)).

Also, there's one more caveat I forgot to mention: you will need to install the corresponding version of the `rancher-monitoring-crd` chart before installing `rancher-monitoring`. Rancher's Dashboard UI usually automatically downloads both for you when you install `rancher-monitoring`.

`rancher-monitoring-crd` will contain the necessary Prometheus Operator CRDs that `rancher-monitoring` relies on to set up Prometheus, Alertmanager, and various configurations in your cluster. If you already have the Prometheus Operator CRDs installed onto your cluster, you can omit this installation step.
