### ISSUE TITLE
"Default Domain:" should be indicated as a not required field in OpenLDAP access control page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2994]
Server version - Build form master - Dec 10

When trying to configure access control using "OpenLDAP" , "Default Domain:" is indicated with a "*" to mean it is a required field.

This field is optional for OpenLDAP configuration and UI should reflect this.

**Comment by vincent99** [comment]
AFAIK this field is meaningless with OpenLDAP, so it's hidden now.

**Comment by sangeethah** [comment]
Tested with server version - v0.50.0-rc2 . This field is not presented in not presented in the "OpenLDAP access control page" anymore.
