### ISSUE TITLE
Error: object does not implement the Object interfaces from indexer

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#29947]
The error below is seen coming from auth indexers:

2020/10/08 22:57:54 [ERROR] ProjectRoleTemplateBindingController <project-id>/<role>[mgmt-auth-prtb-controller] failed with : object does not implement the Object interfaces 

A restart of rancher fixed the issue indicating there was an invalid object in the cache

**Comment by jiaqiluo** [comment]
The bugfix is validated on the following rancher versions:
- v2.4-4221-head
- v2.5-36bb757e5687ebde7d44adbb523c1674512815c5-head
- master-f49309520b999078752e0cb1406af5f02545e4f7-head

After running RBAC-related tests on the setup, there is no warning about indexByMembershipBindingOwner in Rancher's logs.
