### ISSUE TITLE
[EKSv2]: enabling GPU in Rancher does not enable it on the cluster in AWS console and enabling GPU for an EKS cluster should result in the correct AMI being used

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#29949]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Enable GPU

**Result:**
non-GPU ami is used

**Other details that may be helpful:**
Add the following to createNodegroup function in the eks-operator:
`if gpu := group.Gpu; aws.BoolValue(gpu) {
		nodeGroupCreateInput.AmiType = aws.String(eks.AMITypesAl2X8664Gpu)
	}`

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.5.1`

Steps:
Create a hosted EKS cluster
Under node groups, enable GPU
![Screen Shot 2020-11-05 at 3 19 19 PM](https://user-images.githubusercontent.com/57409052/98305895-f3693c80-1f7f-11eb-8c0e-776fce238607.png)
Create cluster

Results:
On cluster edit, GPU is shown as enabled under node group:
![Screen Shot 2020-11-05 at 3 36 44 PM](https://user-images.githubusercontent.com/57409052/98305956-0a0f9380-1f80-11eb-8289-c4fa1af360d3.png)
In API view, GPU is not enabled
```
"nodeGroups": [
{
"desiredSize": 2,
"diskSize": 20,
"ec2SshKey": null,
"gpu": null,
"instanceType": "t3.medium",
"labels": { },
"maxSize": 2,
"minSize": 2,
"nodegroupName": "aaron-ng3",
```

**Comment by aaronRancher** [comment]
AMI used in node group:
![Screen Shot 2020-11-05 at 4 06 30 PM](https://user-images.githubusercontent.com/57409052/98306449-19dba780-1f81-11eb-9aee-9024ce5c6aa4.png)
![Screen Shot 2020-11-05 at 4 07 44 PM](https://user-images.githubusercontent.com/57409052/98306451-1a743e00-1f81-11eb-9a3e-a5a6b39cd8a9.png)

**Comment by aaronRancher** [comment]
In v2.5.1 cluster creation response header, GPU is being set:
```
eksConfig: {imported: false, amazonCredentialSecret: "cattle-global-data:cc-kd2tn", displayName: "aaron-test",…}
amazonCredentialSecret: "..."
displayName: "aaron-test"
imported: false
kmsKey: ""
kubernetesVersion: "1.17"
loggingTypes: []
nodeGroups: [{desiredSize: 2, diskSize: 20, ec2SshKey: "", gpu: true, instanceType: "t3.medium", maxSize: 2,…}]
0: {desiredSize: 2, diskSize: 20, ec2SshKey: "", gpu: true, instanceType: "t3.medium", maxSize: 2,…}
```

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:v2.5-head` `version 36bb757`

GPU is set in API view:
```
eksConfig": {
"amazonCredentialSecret": "...",
"displayName": "aaron-eks5",
"imported": false,
"kmsKey": "",
"kubernetesVersion": "1.17",
"loggingTypes": [ ],
"nodeGroups": [
{
"desiredSize": 2,
"diskSize": 20,
"ec2SshKey": "",
"gpu": true,
"instanceType": "t3.medium",
"labels": { },
"maxSize": 2,
"minSize": 2,
"nodegroupName": "aaron-ng6",
"subnets": [ ],
"tags": { },
"type": "/v3/schemas/nodeGroup",
"version": "1.17"
}
],
```

AMI used in node group:
![Screen Shot 2020-11-05 at 6 39 32 PM](https://user-images.githubusercontent.com/57409052/98315803-4fd75680-1f96-11eb-8697-ffc6bb2436bc.png)
![Screen Shot 2020-11-05 at 6 38 49 PM](https://user-images.githubusercontent.com/57409052/98315804-506fed00-1f96-11eb-9955-e25555179657.png)

**Comment by sowmyav27** [comment]
Reopening the issue for a fix for this use case:

**on 2.5-head latest - commit id: `36bb757e`**

- Create an EKS cluster, set GPU - true on a nodegroup
- The API request sent has GPU: true
- When the cluster is Active, GPU on the cluster is No and View in API -- gpu": null,

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.5-head` `version 715fcc7` and `rancher\rancher:master-head` `version ad28e26`

GPU is set in API view:
```
"nodeGroups": [
{
"desiredSize": 2,
"diskSize": 20,
"ec2SshKey": "",
"gpu": true,
"instanceType": "t3.medium",
"labels": { },
"maxSize": 2,
"minSize": 2,
"nodegroupName": "aaron-ng2",
"subnets": [ ],
"tags": { },
"type": "/v3/schemas/nodeGroup",
"version": "1.17"
}
],
```

`AL2_x86_64_GPU AMI` is used for node group:
![Screen Shot 2020-11-06 at 3 36 35 PM](https://user-images.githubusercontent.com/57409052/98421278-355cb600-2046-11eb-8792-c29d20043a22.png)
![Screen Shot 2020-11-06 at 3 34 24 PM](https://user-images.githubusercontent.com/57409052/98421281-35f54c80-2046-11eb-910e-1e5b25743798.png)
