### ISSUE TITLE
[cli] bug when specifying token cache-dir

### ISSUE THREAD

**Issue by tjcain** [rancher/rancher#29955]
There is a bug in the newly merged cache dir code meaning it does not function as intended. I've proposed a fix: https://github.com/rancher/cli/pull/289

**Comment by dramich** [comment]
This will be available in v2.4.8-rc1

**Comment by sowmyav27** [comment]
**Using 2.4.7 cli version:**
`./rancher token --cache-dir /Users/test/cli-token-2 --server https://<server> --user admin` --> Saves the token in the current working directory under .cache/token/admin_.json

**Using v2.4.8-rc1 cli version:**
`./rancher token --cache-dir /Users/test/cli-token --server https://<server> --user admin` --> Saves the token in `/Users/test/cli-token/token/admin_.json`
