### ISSUE TITLE
[Monitoring V2] Provide a way to send Rancher Proxy based external URLs

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29968]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Deploy the Monitoring App that does not use an Ingress and trigger an alert to AlertManager. This can be done by:

1. Creating a dummy PrometheusRule that always fires, e.g. 

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: cattle-monitoring-system
  name: dummy-rule
spec:
  groups:
  - name: dummy-alert
    rules:
    - alert: ExampleAlert
      expr: vector(1)
```

2. Editing the alertmanager.yaml key in the Secret `alertmanager-rancher-monitoring-alertmanager` within the `cattle-monitoring-system` namespace to add in a receiver / route configuration, e.g.

```
receivers:
- name: 'slack-notifications'
  slack_configs:
  - send_resolved: true
    text: '{{ template "slack.rancher.text" . }}'
    api_url: <insert-slack-webhook-here>
route:  
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: 'slack-notifications'
templates:
- /etc/alertmanager/config/*.tmpl
```

**Result:**

The [`Link to Alertmanager`](https://github.com/rancher/charts/blob/1d17a5bb6767f6468815b005b688fb73f7baa228/charts/rancher-monitoring/values.yaml#L469) uses the Alertmanager's External URL field, which [defaults to the cluster internal URL](https://github.com/rancher/charts/blob/1d17a5bb6767f6468815b005b688fb73f7baa228/charts/rancher-monitoring/templates/alertmanager/alertmanager.yaml#L26) of `http://rancher-monitoring-alertmanager.cattle-monitoring.system:9093`. This link is invalid outside of the cluster, so it doesn't make much sense to have in a notification.

The `Source` link on the Alertmanager UI is broken since it is similarly configured via Prometheus's External URL field,  which defaults to `http://rancher-monitoring-prometheus.cattle-monitoring.system:9090`.

![Screen Shot 2020-11-06 at 1 14 15 PM](https://user-images.githubusercontent.com/13127443/98415348-00deff00-2032-11eb-8185-db94fa922387.png)

Note that this would not be the case if a user is using an Ingress since Prometheus / Alertmanager deployed via Ingress automatically modifies both fields to point to the Ingress URL.

**Other details that may be helpful:**

There are a couple of options that could be taken to support this:

#### Option 1: Expose UI options to allow the user to set the externalURL for both from the Chart deployment page

This is the easiest solution that just involves a UI change, but introduces two caveats:
- a user who modifies the Rancher URL would need to redeploy monitoring to update the links. 
- this may impact users who want to be able to access Prometheus / Alertmanager when the Rancher proxy is down via something like `kubectl port-forward`. This depends on whether this setting breaks the ability for the Prometheus / Alertmanager UI to function as expected when the external URL (e.g. `<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-<alertmanager|prometheus>:<9093|9090>/proxy`) does not match the current URL (e.g. `http://localhost:<port-to-forward-to>`).

Both of these solutions need to be further investigated.

#### Workaround based on Option 1

Users can set the external URLs by clicking on `Edit as YAML` on the Chart Options when deploying the Monitoring chart. You will need to modify:
- `alertmanager.alertmanagerSpec.externalUrl=<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-alertmanager:9093>/proxy`
- `prometheus.prometheusSpec.externalUrl=<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy`.

#### Option 2: Design a backend solution that does not involve redeploying the chart

For either of these solutions, we would need a way for the Dashboard UI to provide the necessary value for the Rancher server URL.

##### Issue 1: `Source` link is broken

Prometheus hard-codes the `generatorURL` for an alert to be based on its externalURL [here](https://github.com/prometheus/prometheus/blob/4e5b1722b342948a55b3d7753f6539040db0e5f0/cmd/prometheus/main.go#L964).

The only solution that seems possible is to put an nginx proxy in front of Alertmanager as well that uses something similar to the [nginx `http_sub_module`](http://nginx.org/en/docs/http/ngx_http_sub_module.html) to rewrite the HTTP response from a GET request to `RANCHER_URL/k8s/clusters/CLUSTER_ID/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-alertmanager:9093/proxy/api/v2/alerts/groups`.

It would need to update references to the URL `http://rancher-monitoring-prometheus.cattle-monitoring-system:9090` to the appropriate Rancher URL; this would be okay even in setups with Ingresses since they won't be using the cluster local DNS either way.

It's unclear how we would be able to update the server URL via this approach though.

Example screenshot of the current HTTP response is shown below:

![Screen Shot 2020-11-06 at 1 44 50 PM](https://user-images.githubusercontent.com/13127443/98417669-41d91280-2036-11eb-91f6-d04e3786c570.png)

#### Issue 2: `Link to Alertmanager` is broken

- [ ] Modify the [`rancher_defaults.tmpl`](https://github.com/rancher/charts/blob/1d17a5bb6767f6468815b005b688fb73f7baa228/charts/rancher-monitoring/values.yaml#L469) to use another template to construct the External URL, where the other template is kept up-to-date with the correct Rancher URL to be used.

- [x] Alternatively, we could just drop this field when we detect the External URL to be `http://rancher-monitoring-prometheus.cattle-monitoring-system:9090` as we know that the link is broken either way.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.1

**Comment by aiyengar2** [comment]
Based on offline discussion, it was confirmed that the path we would take for this issue would be to expose a UI field for setting the external URL and making it a value that is set on Helm deploy.

The caveat with this approach is that a user who install rancher-monitoring would need to perform a `helm upgrade` iff they modify the Rancher URL after upgrading the chart since Rancher will not automatically upgrade feature charts.

**Comment by bashofmann** [comment]
If a user modifies the Rancher URL, they need to do some manual steps already at the moment. For example the Rancher URL  (and CA checksum( in the downstream agents is not changed automatically.

**Comment by aiyengar2** [comment]
@deniseschannon based on offline discussion with @bashofmann, most users seem to be exposing Prometheus / Alertmanager / Grafana via Rancher magic links (not ingress), so I'm pulling this back to 2.5.8.

**Comment by aiyengar2** [comment]
This solution resolves https://github.com/rancher/rancher/issues/29969 in Alerting V2 and can be backported to Alerting V1 if the relevant cattle fields are made available to the Alerting V1 deployment.

**Comment by aiyengar2** [comment]
FYI https://github.com/prometheus/alertmanager/issues/1881 is still an issue from upstream, so you will still need to copy paste the link for the source links to work based on https://github.com/prometheus/alertmanager/issues/1881#issuecomment-576827227.

**Comment by bangnh1** [comment]
I do workaround by using `reReplaceAll`:

`
{{ define "__rancherurl" }}https://<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-alertmanager:9093>/proxy/{{ end }}
`

`
*Graph:* <{{ template "__rancherurl" . }}{{ .GeneratorURL | reReplaceAll "http://rancher-monitoring-prometheus.cattle-monitoring-system:9090/" "$1" }}|:chart_with_upwards_trend:>
`

**Comment by slickwarren** [comment]
I was able to test the following on 2.5-head (7002499) using monitoring v14.5.100-rc5:
* deploy monitoring with default settings
  * viewing yaml after deployment shows that the external URL is now set in global.cluster
* setup an alert
  * alert message link now uses external URL. Link works, brings you to the alertmanager page where alert is firing
* manually set externalURL
  * set in yaml -- if not same value as rancher's externalURL, part of prom will break (expected)
* on older version of rancher (v2.5.7) manually set external URL on latest monitoring (using dev-v2.5)
  * alert links are now working

### Needs Info On:
* **creating ingress for prometheus (prometheus.ingress settings)** -> not sure how to set this up, seems to need ingress-nginx but this is already deployed with monitoring (?)
  * if both external URL and ingress are set, alert link should be using ingress
  * all prom services should work in this case

**Comment by slickwarren** [comment]
to test with an ingress, we did the following on 2.5-head (31f00c1):
* deployed monitoring (UI updates global.cattle.url = rancher's current external URL)
* setup alerts (receiver, prometheus rule, route)
* deployed an ingress targeting service `alertmanager-operated` on port 9093 (autogenerated name using .xip.io)
* added that ingress to monitoring -> alertmanager.alertmanagerSpec.externalURL = your_ingress
* wait for your alert to trigger -> user sees ingress used in link of alert manager (not global.cattle.url value) -- PASS
