### ISSUE TITLE
Buggy Scheduling

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#2997]
Is the plan to abandon the current scheduler for swarm? I've attached an image that shows what rancher ends up looking like after 3-4 days. I've experienced this again and again from the day I started using this otherwise fantastic platform.

![rancher-scheduling-jam](https://cloud.githubusercontent.com/assets/9341738/11732565/6ef660ea-9f73-11e5-8acd-676f08d3bb11.png)

**Comment by Ilya-Kuchaev** [comment]
+1

**Comment by Rucknar** [comment]
Might be worth pasting your config, i can't say i've seen such issues?

**Comment by bacheson** [comment]
This scheduling problem is extremely easy to reproduce. Scale any image up to 100 containers. Perform an upgrade and 9/10 you'll get all sorts of unknown exception errors.

5 nodes with the same config:

Containers: 61
Images: 118
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-264537-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 7.691 GB
 Data Space Total: 107.4 GB
 Data Space Available: 42.44 GB
 Metadata Space Used: 14.18 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.133 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.99 (2015-06-20)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-19-generic
Operating System: Ubuntu 15.10
CPUs: 16
Total Memory: 29.44 GiB
Name: rancher-node-1
ID: P7VP:A252:ILVW:L63P:FW7Y:ZTOE:LODR:7HQR:6XPI:5X6G:7BRK:NEH2

**Comment by Rucknar** [comment]
Is it only when performing actions such as upgrade you hit the issue? Do you get any issues with standard create/remove? Done through the GUI or the CLI?

**Comment by bacheson** [comment]
It appears Ubuntu 15.10 is the problem. Reverting everything to Ubuntu 14.10 solved everything. It would be extremely helpful to put up a notice on the install page. Ubuntu 15.10 should be avoided.
