### ISSUE TITLE
Cluster health check failed: cluster agent is not ready on a rancher port 8443 ui

### ISSUE THREAD

**Issue by MoulderUtes** [rancher/rancher#29975]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug when trying to create a cluster to rancher setup on port 8080 and 8443

**Steps to reproduce (least amount of steps as possible):**
Set up machine to run docker and run this code 
`sudo docker run -d --restart=unless-stopped \
  -p 8080:80 -p 8443:443 --privileged \
  -v /opt/rancher:/var/lib/rancher \
  rancher/rancher:latest  `
Then try to add a new kubernetes cluster and attach a node that is etcd, control plane, and worker. 
If you try to use the default command the node cant find the cluster so I added the 8443 port to the ip. See code
`sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.5.1 --server https://192.168.1.75 --token 6bgll5n7rrpgpjx55zfpj5wf2spzg4gvvfdpzzvp4ww2lhsfw2mczb --ca-checksum 3128c7d9478b3cca6d93402efece0fd17b77a77772c1bea51fa8fe981e66ff0f --worker`
**Result:**
After a lot of waiting you get a error on the cluster saying 
`Cluster health check failed: cluster agent is not ready`

**Other details that may be helpful:**
The local cluster is running a debian vm on proxmox. The node for the new cluster is running on that same machine but in another proxmox vm. (I set it up this way so I could move the node arroud between proxmox machines) I can change this but think I would get the same error on a new machine. 

**Environment information**
Rancher v2.5.1
Single install 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Running on my personal machine (idk what that is considered) 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4 cpu 8gb ram
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCom                                                                                        mit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:                                                                                        "2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd                                                                                        64"}
The connection to the server localhost:8080 was refused - did you specify the ri                                                                                        ght host or port?

```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:25 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by superseb** [comment]
There is no need to manually adjust values if they are set up correctly. The `server-url` value should be configured with the port if thats the way it is exposed, this will then be used in the generated command and also later in the process when the cluster agent is deployed. The `server-url` is configured when you first login to Rancher.

**Comment by MoulderUtes** [comment]
Yeah I realized this. When because I was using persistent volumes the port would not automatically switch. I have since reverted to a snapshot of the machine before the volume was created so for sure no left over data. I also was still getting some errors but now the web ui is not connecting. I think this is an unrelated issue but I will have another update by the end of today.

**Comment by MoulderUtes** [comment]
Yeah so I I figured it out. 

TO ANY GOOGLERS 
If you are using a persistent volume and change your port make sure you change what rancher thinks the url is. (when it asks you after the login just leave it default). If you don't it messes things up. Thanks for the answers anyways superseb. And from what I can tell the support for rancher is off the charts.
