### ISSUE TITLE
EKS: Error:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)

### ISSUE THREAD

**Issue by ankitsoni17-png** [rancher/rancher#29977]
What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Deploy rancher version 2.4.8 with cert-manager on EKS.

**Result:**
Ingress will not able to find the default backend service

**Other details that may be helpful:**
I am trying to deploy Rancher on Kubernetes using helm charts and with cert-manager but it is not working. The ingress is not able to find the default backend service.
```
[ankit@rancher ~]$ kubectl -n cattle-system describe ingress
Name:             rancher-server
Namespace:        cattle-system
Address:
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  tls-rancher-ingress terminates rancher.ankit.com
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  rancher.example.com
                             rancher-server:80 (137.182.41.109:80,137.182.43.5:80,137.182.46.21:80)
Annotations:              cert-manager.io/issuer: rancher-server
                          cert-manager.io/issuer-kind: Issuer
                          nginx.ingress.kubernetes.io/proxy-connect-timeout: 30
                          nginx.ingress.kubernetes.io/proxy-read-timeout: 1800
                          nginx.ingress.kubernetes.io/proxy-send-timeout: 1800
Events:                   <none>

```
All the other resources are in running state. But still I am not able to access the rancher server.
```
[ankit@rancher ~]$ kubectl -n cattle-system get all
NAME                                  READY   STATUS    RESTARTS   AGE
pod/rancher-server-66bc987745-jtnr8   1/1     Running   0          18h
pod/rancher-server-66bc987745-st89m   1/1     Running   0          18h
pod/rancher-server-66bc987745-t99qt   1/1     Running   0          18h

NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/rancher-server   ClusterIP   10.100.225.99   <none>        80/TCP    3d6h

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rancher-server   3/3     3            3           3d6h

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/rancher-server-66bc987745   3         3         3       3d6h
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.4.8
- Installation option (single install/HA): single install (using helm3)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

```

**Comment by tarantila** [comment]
Did you found a solution? I have an install without cert-manager and the same error.

**Comment by tarantila** [comment]
> Did you found a solution? I have an install without cert-manager and the same error.

I found this answer:

"The Ingress object that the rancher chart creates does not define a default backend (because we don't need one), and thus kubectl falls back to trying to find the default-http-backend in kube-system which does not exist.

The "real" default-http-backend that comes with RKE can be found in the namespace ingress-nginx."

See here: https://www.gitmemory.com/issue/rancher/rancher/29891/720233246

So i guess it's not an error ;)

**Comment by ankitsoni17-png** [comment]
> > Did you found a solution? I have an install without cert-manager and the same error.
> 
> I found this answer:
> 
> "The Ingress object that the rancher chart creates does not define a default backend (because we don't need one), and thus kubectl falls back to trying to find the default-http-backend in kube-system which does not exist.
> 
> The "real" default-http-backend that comes with RKE can be found in the namespace ingress-nginx."
> 
> See here: https://www.gitmemory.com/issue/rancher/rancher/29891/720233246
> 
> So i guess it's not an error ;)

Hi @tarantila 
I don't have ingress-nginx namespace. I simply deployed the Rancher using helm chart in cattle-system namespace. For me there is only rancher deployment and ingress is present. I have my hostname which is active. But still I am not able to see the rancher UI.
Also tried to patch the rancher service to load balancer from Cluster-IP but still no luck. Even there is no error in rancher-server pod logs. If it is working for then please let me know how you configured it.
For me  everything is deployed on EKS.
