### ISSUE TITLE
[cli] Enhancements to token command

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29983]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**
Currently after generating the token using `rancher token --cache-dir` command, user has to change the kubeconfig and use env vars to use the token

Steps:
```
- Set `https://<Rancher-Server-IP/v3/settings/kubeconfig-generate-token` to false.
- Save the kubeconfig from the cluster in rancher server. 
- `./rancher token --cache-dir /Users/test/cli-token --server https://<server> --user admin`
- RANCHER_CACHE_DIR=/Users/test/cli-token kubectl get nodes
- username password is required for the first time login and not for the next.
```

**Other details that may be helpful:**
Related issue - https://github.com/rancher/rancher/issues/29955

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.8-rc1 rke version on rancher version 2.4.9-rc10

**Comment by dramich** [comment]
The token command cache should use the same location as the default dir the CLI already uses to store state. There was a new envvar added with the flag `cache-dir` which should be removed and a new global envvar should be setup to specify the dir the state file is going to be kept in. Currently the token command is storing state wherever the CLI is ran from so if you change directories the cli requires another login and stores another file at that location.
