### ISSUE TITLE
Test support for managed providers out-of-bounds kube versions

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#29988]
We follow the support matrix for Kubernetes versions for RKE create clusters via KDM. However it is possible that a cluster made with a managed provider (EKS/GKE) goes out of bounds. So far we haven't run into many problems in this area because typically cloud providers are far behind upstream. 

For example [GKE has a flag](https://github.com/rancher/kontainer-engine/blob/release/v2.4/drivers/gke/gke_driver.go#L227-L229) which auto-upgrades the cluster over time. It's also possible they could simply provision a new version in a very old version of rancher. I don't think upgrading an existing compatible cluster from the cloud provider side would prove this case as I believe Rancher would still treat it as the non-upgraded version. Although an auto-upgrade would do same thing, so thats probably as good of a test case as we are going to get given current stable releases.

The main case we would like to check is if 2.4.x supports K8s 1.19, as GKE is disabling basic auth in 1.19 (See [28673](https://github.com/rancher/rancher/issues/28673), though that version is [currently in alpha](https://cloud.google.com/kubernetes-engine/docs/release-notes#no-channel)) and it will break our implementation if someone ends up there. So we are trying to determine if it is worth backporting a fix, if the cluster is broken regardless then its not worth backporting. We could also check 2.3 with 1.18 even though its a separate case. 

[GKE versions](https://cloud.google.com/kubernetes-engine/docs/release-notes)
[EKS versions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)

**Comment by jiaqiluo** [comment]
the GKE cluster with k8s `v1.18.10-gke.2101` is validated on rancher:`v2.3.9`

Steps:
- run rancher:v2.3.9 single install
- via Rancher UI provision a GKE cluster with k8s `v1.17.13-gke.2001` (the higest version available on Rancher's UI) 
<img width="1458" alt="Screen Shot 2020-11-18 at 5 01 19 PM" src="https://user-images.githubusercontent.com/6218999/99606767-a47fc600-29c7-11eb-900b-8bf429a6137c.png">

- run pre-upgrade tests on the cluster 
- on Google Cloud's console, upgrade the GKE cluster to `v1.18.10-gke.2101` ( both the master and worker nodes)
- confirm that the new version show properly on Rancher's UI
- run post-upgrade tests on the cluster 
![image](https://user-images.githubusercontent.com/6218999/99606959-ff192200-29c7-11eb-8218-c97e09443eea.png)
- enable cluster monitoring v1 and confirm the monitoring v1 works

**Comment by jiaqiluo** [comment]
the GKE cluster with k8s `v1.18.10-gke.2101` is validated on rancher:`v2.4.10`

This time the cluster is created on Goggle Cloud directly and imported into Rancher. 
![image](https://user-images.githubusercontent.com/6218999/99608705-aa77a600-29cb-11eb-8920-082577adf2d5.png)
