### ISSUE TITLE
istio 1.7

### ISSUE THREAD

**Issue by cywang4** [rancher/rancher#29992]
When to support istio 1.7 ?

**Comment by cbron** [comment]
@cywang4 istio 1.7 is supported in rancher 2.5

**Comment by siucng2222-c** [comment]
In Rancher webpage, Cluster Manger > Tools section mentioned that Rancher 2.5.3 certified for Istio Service Mesh 1.5.9 version only ...? 
https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.5.3/

**Comment by cbron** [comment]
@siucng2222-c yes cluster-manager only supports the 1.5.x line. In the cluster-explorer section you can see 1.7.1, and 1.8 will be coming soon.
