### ISSUE TITLE
Updating an AKS cluster with a new Client Secret fails

### ISSUE THREAD

**Issue by adaliszk** [rancher/rancher#29998]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy an AKS cluster
2. Edit the cluster using a new Client Secret

**Result:**
The Cluster gets into an error state with the message of:
Containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PropertyChangeNotAllowed" Message="Changing property 'servicePrincipalProfile.secret' is not allowed." Target="servicePrincipalProfile.secret"

**Environment information**
- Installation option (single install/HA): HA (Deployed in an AKS via helm)
- Rancher version 2.5.2-rc8
- User Interface version 2.5.2
- Helm version 2.16.8-rancher1
- Machine version 0.15.0-rancher46

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Azure
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Standard_B2ms (2xCPU/8G RAM)
- Kubernetes version (use `kubectl version`): 1.18.10

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version : 19.3.12

**Comment by dgiebert** [comment]
Did you find a solution for this @adaliszk as this is also happening to me right now?

**Comment by adaliszk** [comment]
Hey @dgiebert,
the workaround I have found was to delete the cluster (without de-provisioning) and add it back again. Sorry that I forgot to add the info to the ticket.

**Comment by dgiebert** [comment]
For everybody coming across this issue, I found a solution that worked out yesterday it is documented here:
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/aks/update-credentials.md#update-aks-cluster-with-new-service-principal-credentials
