### ISSUE TITLE
AD Users invalid after moved to another OU

### ISSUE THREAD

**Issue by checkelmann** [rancher/rancher#29996]
We are currently restructuring our AD and all Users will be moved to a new OU. 
Now no user got a valid user object in Rancher anymore, as the user CN is changed.

The principal id of the user is still the old one. And I don't have the possibility to change this for the users.

![image](https://user-images.githubusercontent.com/584370/98666878-eb2d4a80-234d-11eb-8c7b-bf7abfeeffdb.png)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Login in Rancher with a Active Directory User
- Move the Active Directory User to another OU
- The activedirectory_user principalIds is not updated and the user information could not be fetched

**Result:**
![image](https://user-images.githubusercontent.com/584370/98666654-97bafc80-234d-11eb-9696-57aa5a5f9d69.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA): Single

I would appreciate any help!

**Comment by finkr** [comment]
We have the same issue each time we move a user in ActiveDirctory.

The user should be stored in Rancher using Active Directory userPrincipalName (user@exemple.com), which is unique and stable, as opposed to DistinguishedNAme. (see https://serverfault.com/q/567776/238995 )
