### ISSUE TITLE
Clicking on Download CLI does not download rancher cli

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29990]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On 2.5.2-rc8
- Click on Download CLI on the bottom right corner of Rancher UI
- Click on MacOS/Windows (any)
- It does not download the cli.

**Expected Result:**
User should be able to download CLI by clicking o "Download CLI"

**Other details that may be helpful:**

- Right click on Download CLI and open in new Tab downloads the rancher CLI
- Works on 2.5.1

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.2-rc8
- Installation option (single install/HA): single

**Comment by sowmyav27** [comment]
**On master-head commit id: `82510802`**

- Click on Download CLI on the bottom right corner of Rancher UI
- Click on MacOS/Windows (any)
- Rancher CLI is downloaded.

**Comment by jiaqiluo** [comment]
the bug fix is validated on `v2.5-574ddd9d29098c919e58b75cea0f086d7cdb98df-head` with the lastet UI 

All 3 options are clickable and can trigger the download of the corresponding CLI 
![image](https://user-images.githubusercontent.com/6218999/98623619-5da81700-22c9-11eb-9081-628feea68014.png)
