### ISSUE TITLE
Unable to create an EKS cluster after upgrading from 2.3.0 to 2.5.1

### ISSUE THREAD

**Issue by sigginet** [rancher/rancher#29994]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug, very similar to #28764

**Steps to reproduce (least amount of steps as possible):**
1. Start with Rancher 2.3.0 using Docker 17 (Let's encrypt SSL)
2. Upgrade to Rancher 2.5.1 according to the instructions in the Docs
3. Create an EKS 1.17 cluster from the web interface, new VPC and security groups

**Result:**
Installation is stuck in deploying eks-operator, `can't find system project`
![image](https://user-images.githubusercontent.com/1608474/98655171-135d7f00-2337-11eb-8d61-141a352609ff.png)

**Other details that may be helpful:**
I have two other imported EKS clusters which were imported in Rancher 2.3.0.
I tried upgrading Docker to 19 after receiving the errors, but this didn't help.

This seems to be very similar to #28764, except I have a local k3s cluster, which was created during installation.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.1
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): EC2 Cloud, t2.large, 2 vCPU, 8GB memory
- Kubernetes version (use `kubectl version`): 1.17.9

```
I1109 13:04:33.641822      26 shared_informer.go:230] Caches are synced for garbage collector 
I1109 13:04:33.641939      26 garbagecollector.go:142] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
I1109 13:04:33.683110      26 shared_informer.go:230] Caches are synced for resource quota 
2020/11/09 13:04:28 [ERROR] error syncing 'local/cluster-scan-manual-failure-only': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:04:28 [ERROR] error syncing 'local/high-memmory': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:04:31 [INFO] Refreshing driverMetadata in 1440 minutes
2020/11/09 13:04:31 [INFO] driverMetadata: refreshing data from upstream https://releases.rancher.com/kontainer-driver-metadata/release-v2.5/data.json
2020/11/09 13:04:31 [INFO] Retrieve data.json from local path /var/lib/rancher-data/driver-metadata/data.json
2020/11/09 13:04:32 [INFO] Unable to obtain token for telemetry service. Telemetry will not be launched.
2020/11/09 13:04:33 [ERROR] error syncing 'local-node': handler node-syncer: can't find system project, requeuing
2020/11/09 13:04:38 [ERROR] error syncing 'local/etcd-system-service': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:04:47 [ERROR] error syncing 'local/high-cpu-load': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:04:47 [ERROR] error syncing 'local/cluster-scan-manual-all': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:04:47 [ERROR] error syncing 'local/db-over-size': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:04:47 [ERROR] error syncing 'local/no-leader': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:04:47 [ERROR] error syncing 'local/scheduler-system-service': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:04:47 [ERROR] error syncing 'local/cluster-scan-scheduled-all': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:04:48 [ERROR] error syncing 'local/deployment-event-alert': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:04:53 [ERROR] error syncing 'local-node': handler node-syncer: can't find system project, requeuing
2020/11/09 13:04:58 [ERROR] error syncing 'local/cluster-scan-alert': handler cluster-alert-group-deployer: can't find system project, handler cluster-alert-group-controller: can't find system project, requeuing
2020/11/09 13:04:58 [ERROR] error syncing 'local/etcd-alert': handler cluster-alert-group-deployer: can't find system project, handler cluster-alert-group-controller: can't find system project, requeuing
2020/11/09 13:04:58 [ERROR] error syncing 'local/kube-components-alert': handler cluster-alert-group-deployer: can't find system project, handler cluster-alert-group-controller: can't find system project, requeuing
2020/11/09 13:04:58 [ERROR] error syncing 'local/node-alert': handler cluster-alert-group-deployer: can't find system project, handler cluster-alert-group-controller: can't find system project, requeuing
2020/11/09 13:04:58 [ERROR] error syncing 'local/event-alert': handler cluster-alert-group-deployer: can't find system project, handler cluster-alert-group-controller: can't find system project, requeuing
2020/11/09 13:05:00 [INFO] checking cluster [c-bspnz] upstream state for changes
2020/11/09 13:05:00 [INFO] initial upstream spec for cluster [c-bspnz] has not been set by eks cluster handler yet, skipping
2020/11/09 13:05:08 [ERROR] error syncing 'local/node-disk-running-full': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:05:08 [ERROR] error syncing 'local/cluster-scan-scheduled--failure-only': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:05:08 [ERROR] error syncing 'local/controllermanager-system-service': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:05:08 [ERROR] error syncing 'local/high-number-of-leader-changes': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:05:09 [ERROR] error syncing 'local/cluster-scan-manual-failure-only': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:05:09 [ERROR] error syncing 'local/high-memmory': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
2020/11/09 13:05:19 [ERROR] error syncing 'local/etcd-system-service': handler cluster-alert-rule-deployer: can't find system project, handler cluster-alert-rule-controller: can't find system project, requeuing
```

- Docker version (use `docker version`): 17 before upgrade. Currently 19.03.13

```
ubuntu@rancher-rancherserver:~$ docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:59 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:30 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by sigginet** [comment]
After reading the source code a bit, I noticed that it's trying to fetch the system project (Just like the error message says). So I checked if the local had any system project.
Turns out that it's missing the system project.
![image](https://user-images.githubusercontent.com/1608474/98664012-bc10dc00-2341-11eb-96a1-00e292b4a79d.png)


Any tips on creating the system project without breaking the environment?

**Comment by sigginet** [comment]
The cluster explorer shows that all pods are not in a namespace.

![image](https://user-images.githubusercontent.com/1608474/98664907-df885680-2342-11eb-8969-918a78c64d0a.png)

I'm going to create a system Project and see what happens.

**Comment by sigginet** [comment]
I created `System` and `Default` projects, then moved the active namespaces to the System project.
I still get these errors `can't find system project`

**Comment by sigginet** [comment]
@aaronRancher can you show me how a proper rancher local cluster is set up with a screenshot or data dump?

Alternatively, I can just delete the Rancher installation and start from scratch, it won't be a huge loss since we're not relying on it in production yet

**Comment by aaronRancher** [comment]
Hello @sigginet.
I tried to reproduce your issue, but was unable to. Here is how the local cluster looks:
![Screen Shot 2020-11-11 at 4 23 54 PM](https://user-images.githubusercontent.com/57409052/98876042-a501e500-243a-11eb-97f7-fc92ab0e3e19.png)
Local system pods in cluster explorer view:
![Screen Shot 2020-11-11 at 4 24 31 PM](https://user-images.githubusercontent.com/57409052/98876103-c793fe00-243a-11eb-832d-1ab60babf271.png)

I was able to deploy a hosted EKS cluster after upgrade from v2.3.0 to v2.5.1. K8s version v1.17.12
![Screen Shot 2020-11-11 at 4 25 51 PM](https://user-images.githubusercontent.com/57409052/98876189-f9a56000-243a-11eb-8e74-6b0f47ad0b4a.png)

You can try a new installation of Rancher v2.5.1. If you continue to see this issue, please let me know. Thank you.

**Comment by sigginet** [comment]
![image](https://user-images.githubusercontent.com/1608474/98922759-c3172600-24ca-11eb-8672-fa52b7cd8530.png)
Here are the deployments on my end, they seem to be the same except the EKS config operator is missing from the cattle-system namespace.

I have a lot of namespaces that are weird and very old:
![image](https://user-images.githubusercontent.com/1608474/98923016-0a051b80-24cb-11eb-8efb-307fc2a582e2.png)

Here are the system namespaces:
![image](https://user-images.githubusercontent.com/1608474/98923140-2ef98e80-24cb-11eb-8531-f222f5df0f2d.png)

One interesting thing that I see is that the local namespace is outside the System project.

@aaronRancher:
1. How do the namespaces look on your end in a fresh installation?
2. Are the random namespaces outside projects or in a specific project?
3. Is there a kubectl command I can run to mimic the installation trying to find the system project?

**Comment by sigginet** [comment]
Well, I gave up and reinstalled everything.
Now when I created the cluster I noticed that I'm allowed to enter forbidden characters for cluster creation
![image](https://user-images.githubusercontent.com/1608474/99059114-04283c80-2596-11eb-97f1-e747c8139c7e.png)
I included a fullstop in the cluster name, but AWS EKS doesn't allow that

**Comment by Tejeev** [comment]
Hi @sigginet I was researching something else and I came across your comment.  I've gone ahead and opened https://github.com/rancher/rancher/issues/30133 as I believe Rancher should validate input when possible.
