### ISSUE TITLE
Removed catalog defaulted in catalog drop down resulting in empty catalog list.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3000]
Server Version - Build from master - Dec 10

Steps to reproduce the problem:
Using settings page -> "Add Catalog URL" option , add multiple catalogs say catalog1 and catalog2.

Launch catalog to make sure all catalogs are listed.
Choose "catalog2"  to list all catalog entries from "catalog2".

Got to settings page -> "Add Catalog URL" option ,and removed "catalog2".

Launch catalog page.
By default "catalog2" (which is currently) removed is selected in dropdown and empty catalog view is presented to the user.

**Comment by vincent99** [comment]
Changed to reset catalog and category when re-entering the screen

**Comment by sangeethah** [comment]
Tested with latest build from master:
When catalog url is removed from Admin->Settings page and then catalog page is launched the deleted catalog url entry does not appear in the "Catalog" drop down. User is presented with the catalogs that  are currently configured.
