### ISSUE TITLE
OPA GA: Update OPA to the latest version

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30018]
Current version for OPA is 3.2.1

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version a549b47` and `rancher\rancher:v2.5-head` `version 9ee39b9`

Gatekeeper `v3.2.1` is available:
![Screen Shot 2020-11-30 at 10 25 26 AM](https://user-images.githubusercontent.com/57409052/100643394-33a9a980-32f7-11eb-990b-1b9bbeb4fbbc.png)
![Screen Shot 2020-11-30 at 10 29 34 AM](https://user-images.githubusercontent.com/57409052/100643397-34424000-32f7-11eb-9f8c-d674383ed88a.png)
