### ISSUE TITLE
Validate rancherd upgrades

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30013]
Validate rancherd upgrades (drop in newer binary or tarball and run, ensure upgrade success)

To Validate:
- Deploy rancherd v1
- Deploy few downstream clusters. (Custom cluster, EKS/GKE, Azure)
- Run pre upgrade checks
- Upgrade rancherd to v2
- Run post upgrade checks

**Comment by izaac** [comment]
rancherd `v2.5.2`
Downstream clusters: 
- RKE DO `v1.18.12` - 1 cp, 1 etcd, 3 workers
- GKE `v1.17.13-gke.2600` - 3 workers
- Custom `v1.18.12` - 1 cp, 1 etcd, 3 workers

Local HA cluster provisioned with rancherd on Ubuntu 20.04. 3 master nodes `t3a.medium`
Upgraded to `v2.5.3-rc1`.
Executed pre-upgrade and post-upgrade tests. Passed.

**Comment by izaac** [comment]
rancherd `v2.5.2`
Downstream clusters: 
- RKE DO `v1.19.4` - 1 cp, 1 etcd, 3 workers

Local HA cluster provisioned with rancherd on Ubuntu 20.04. 3 master nodes **and 1 worker** `t3a.medium`
Upgraded to `v2.5.3-rc1`.
Executed pre-upgrade and post-upgrade tests. Passed.
