### ISSUE TITLE
Create/Update launch templates for EKS managed node groups

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#30019]
**What kind of request is this (question/bug/enhancement/feature request):**
feature (for `eks-operator`)

**New Result:**
If the user specifies a launch template for node group creation, `eks-operator` should validate the launch template and use it for the creation of the node group instead of specifying the node group configuration.

Also, if the launch template version is updated, then `eks-operator` should validated the updated version and use it to update the managed node group.

AMI type could be provided in either of these scenarios only if the launch template does not specify one.

**Other details that may be helpful:**
The `EKSClusterConfig` CRD needs to be updated to allow the template id and version and AMI type to be put in `Status` and `Spec`.

**Comment by thedadams** [comment]
https://github.com/rancher/rancher/issues/28803

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `dba332111`**

- verified user is able to create/update nodegroups with rancher managed launch templates and also those that have AWS existing launch templates.
- Able to deploy a hosted EKS cluster using a custom AMI created by AWS packer. 
- Any related issues have been logged separately. Closing this issue
