### ISSUE TITLE
Include catalog name when listing templates in catalog view when templates from  all catalogs are listed( "All" option).

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3001]
Server version - Build form master - Dec 10

When there are multiple catalogs configured , it will be useful to  include catalog name for template entries when listing templates  from  all catalogs ( "All" option).

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/11819715/97152e22-a31e-11e5-84f2-d9883ff31c0f.png)

**Comment by sangeethah** [comment]
Tested with latest build from master:

Catalog name is included when listing templates in catalog view.
