### ISSUE TITLE
Validate RHEL8 with SELinux set to Enforcing with cis-1.5 enabled using Rancherd

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30011]
Validate RHEL8 with SELinux set to Enforcing with cis-1.5 enabled (can automation have this on by default?)

Related issue: https://github.com/rancher/rancher/issues/29797

Validate:
- Deploy rancherd latest with RHEL8 with SELinux set to Enforcing with cis-1.5 enabled setup
- Verify the cluster comes up, workloads in system project are Active.
- Deploy a downstream cluster and run validation checks
- Verify if user is able to deploy v2 apps on rancherd local cluster.

**Comment by aaronRancher** [comment]
RHEL8 with SELinux enforced is validated with a cis-1.5 enabled setup using Rancherd.
AMI used: `ami-0ff391c1c79d2cb84`

Config:
```
write-kubeconfig-mode: "0644"
tls-san: <hostname>
token: "secret"
server: https://<IP>
cloud-provider-name: "aws"
node-name: <Node name>
profile: cis-1.5
```
Installed with:
```
curl -sfL https://get.rancher.io | sudo INSTALL_RANCHERD_VERSION=v2.5.3 sh -
```

Automation checks on downstream clusters passes.
User is able to deploy V2 apps on rancherd local cluster
