### ISSUE TITLE
Use launch template provided by user

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#30020]
**What kind of request is this (question/bug/enhancement/feature request):**
feature (for `eks-operator`)

**New Result:**
If the user specifies a launch template, rancher should use the template id and version (or the default version if a version is not listed) to create the node group.

**Other details that may be helpful:**
If the launch template version that the user specifies does not have an `ImageId`, then rancher should respect the selection of the GPU instance checkbox.

**Comment by thedadams** [comment]
https://github.com/rancher/rancher/issues/28803

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `3e96d7fb` and master-head - commit id: `9ef8e69`**

- Use cases have been tested for Pre existing launch templates on hosted and import EKS clusters
- If the user specifies a launch template, rancher uses existing template to create nodegroup
- If the launch template version that the user specifies does not have an ImageId, then rancher respects selection of GPU field, when set to true, instance launch is GPU enabled.
- Any related issues have been logged separately.
