### ISSUE TITLE
Update EKSClusterConfig syncing to include launch template information

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#30021]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**New Result:**
Syncing EKS clusters needs to take into account the template ids on each node group. This also includes the writing the `eksclusterconfig` CRD properly to reflect the new values. There is some subtlety here: there may be a launch template on a node group that was specified by Rancher and not by the user. Therefore, in this case, the template id and version should not be written to `Spec`.

**Other details that may be helpful:**
The `eks-operator` should be updated here to include the new fields on the `EKSClusterConfig` type. A `go generate` may be required.

**Comment by thedadams** [comment]
https://github.com/rancher/rancher/issues/28803

**Comment by aaronRancher** [comment]
The enhancement is verified with Rancher server `rancher\rancher:v2.5-head` `version 8201e08`

EKS Config syncing includes template information. Template IDs are seen on each node group when using a preexisting launch template from EKS console.
Node group config:
```
"nodeGroups": [ 3 items
{
"desiredSize": 2,
"diskSize": null,
"ec2SshKey": null,
"gpu": false,
"imageId": null,
"instanceType": null,
"labels": { },
"launchTemplate": {
"id": "lt-01cf5f5cd-----",
"name": "sowmya-test",
"type": "/v3/schemas/launchTemplate",
"version": 2
},
"maxSize": 2,
"minSize": 2,
"nodegroupName": "aaron-ng-byolt",
"requestSpotInstances": false,
"resourceTags": null,
"spotInstanceTypes": null,
"subnets": [ 3 items
"subnet-",
"subnet-",
"subnet-"
],
"tags": { },
"type": "/v3/schemas/nodeGroup",
"userData": null,
"version": "1.18"
},

When a node group uses a Rancher Managed template, the launch template ID is omitted from the node group config:
```
"desiredSize": 2,
"diskSize": 20,
"ec2SshKey": null,
"gpu": false,
"imageId": null,
"instanceType": "t3.medium",
"labels": { },
"launchTemplate": null,
"maxSize": 2,
"minSize": 2,
"nodegroupName": "aaron-test-gpu",
"requestSpotInstances": false,
"resourceTags": { },
"spotInstanceTypes": null,
"subnets": [ 3 items
"subnet-",
"subnet-",
"subnet-"
],
"tags": { },
"type": "/v3/schemas/nodeGroup",
"userData": null,
"version": "1.18"
```

**Comment by aaronRancher** [comment]
Verified with Rancher server `rancher\rancher:master-head` `version d7203b4` and `rancher\rancher:v2.5-head` `version 05fbcbb`

All launch template fields are synced on cluster edit and in API:
User Data
Instance type 
Node volume size 
SSH Key 
Image ID
Resource Tags 
Template ID
Template version
GPU enabled
Resource tags
Spot instances

UI syncing issues will be tracked separately:
https://github.com/rancher/rancher/issues/31277
