### ISSUE TITLE
Uncrypted recurring S3 backup via rancher-backup operator fails with invalid AWS net/http header

### ISSUE THREAD

**Issue by caiobegotti** [rancher/rancher#30038]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

0. create S3 bucket `lalala-etcd-snapshot` with AES256 encryption on the server side and these allow rules in the IAM:

```
"s3:GetObject",
"s3:PutObject",
"s3:DeleteObject",
"s3:ListBucket",
```

1. create the following plain text secret for S3 access:

```
apiVersion: v1
kind: Secret
metadata:
  name: s3-backups-etcd-snapshot
  namespace: cattle-system
type: Opaque
data:
  accessKey: "AKIA..."
  secretKey: "mDzJ2SCm..."
```

2. create the backup object (I did it via the UI at first but this is the resulting YAML):

```
apiVersion: resources.cattle.io/v1
type: resources.cattle.io.backup
kind: Backup
metadata:
  name: lalala-etcd-snapshot
spec:
  resourceSetName: rancher-resource-set
  retentionCount: 72
  schedule: 0 * * * *
  storageLocation:
    s3:
      bucketName: lalala-etcd-snapshot
      credentialSecretName: s3-backups-etcd-snapshot
      credentialSecretNamespace: cattle-system
      endpoint: s3.us-west-2.amazonaws.com
      insecureTLSSkipVerify: true
      region: us-west-2
```

**Result:**

```
INFO[2020/11/11 19:39:24] Compressing backup CR lalala-etcd-snapshot 
INFO[2020/11/11 19:39:24] invoking set s3 service client s3-accessKey="\x00\xa2\x00\\\x017,n\rd\x957\b\xfeF"
s3-bucketName=lalala-etcd-snapshot s3-endpoint=s3.us-west-2.amazonaws.com
s3-endpoint-ca= s3-folder= s3-region=us-west-2
ERRO[2020/11/11 19:40:46] error syncing 'lalala-etcd-snapshot': handler backups:
failed to check s3 bucket:lalala-etcd-snapshot,
err:Head https://lalala-etcd-snapshot.s3.dualstack.us-west-2.amazonaws.com/:
net/http: invalid header field value "AWS4-HMAC-SHA256
Credential=\x00\xa2\x00\\\x017,n\rd\x957\b\xfeF/20201111/us-west-2/s3/aws4_request,
SignedHeaders=host;x-amz-content-sha256;x-amz-date, 
Signature=8f11dff2300a6773d6bb7a1db8be452c1808cb1b7991e41a32c0f81c6b44b8d2" for key Authorization, requeuing 
```

**Other details that may be helpful:**

The documentation is not clear about a working example so I'm not sure if my settings are correct to be honest.

I tried disabling the S3 bucket server-side encryption but it failed in the same way.

I tried creating the S3 secret via Rancher's UI directly too. It worked.

**Environment information**
- Rancher version: 2.5.1
- Installation option: single

**Cluster information**
- Cluster type: imported AWS EC2 cluster set up manually with Terraform
- Kubernetes version: v1.18.9

**Comment by mrajashree** [comment]
@caiobegotti I see that you are using IAM roles to grant access to the bucket, if that's the case, you don't need to provide credentials also. 

- If you want to use IAM roles, can you make sure the IAM role has [these exact permissions](https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/configuration/backup-config/#iam-permissions-for-ec2-nodes-to-access-s3) (notice the two different statements for List and Put/Get/Delete). Once you have the right permissions for IAM role and this IAM role attached to your ec2 instances on which rancher is running, you can leave `credentialSecretName` and `credentialSecretNamespace` fields empty.
- If you want to use your aws credentials instead, while creating the Secret containing accessKey and secretKey, the keys should be base64 encoded. If you create this Secret via Rancher dashboard, it does the base64 encoding for you. If you're creating this Secret using kubectl instead, encode the keys individually and use that value in the Secret. You can use this command:
```
 echo -n "<accessKey>" | base64
```
[This](https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/configuration/backup-config/#s3) doc has more information about S3 configuration. And [this](https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/configuration/backup-config) doc has steps for configuring other fields too. Let me know if this works

**Comment by caiobegotti** [comment]
Yeah, my bad, I totally forgot about base64 in secrets... sigh :-(
