### ISSUE TITLE
Rancher cli cannot execute kubectl commands without giving --insecure-skip-tls-verify

### ISSUE THREAD

**Issue by fabn** [rancher/rancher#30035]
I found this issue lot of times, I'm using rancher cli to deploy from CI and I need to always give --insecure-skip-tls-verify to be able to execute rancher cli commands

Here's a transcript of my build (using rancher/cli2:v2.4.9 as base image) 

```
$ wget -qO /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
$ chmod +x /usr/local/bin/kubectl
$ echo 1 | rancher login "$RANCHER_SERVER_URL" -t "$RANCHER_API_TOKEN"
NUMBER    CLUSTER NAME   PROJECT ID      PROJECT NAME     PROJECT DESCRIPTION
1         my-cluster       local:p-4wnlw   SomeProject
Select a Project:time="2020-11-11T18:28:51Z" level=info msg="Saving config to /root/.rancher/cli2.json"
$ rancher context switch "$RANCHER_PROJECT"
time="2020-11-11T18:28:52Z" level=info msg="Setting new context to project SomeProject"
time="2020-11-11T18:28:52Z" level=info msg="Saving config to /root/.rancher/cli2.json"
$ rancher kubectl get pods -n ${RANCHER_NAMESPACE} --insecure-skip-tls-verify
NAME                           READY   STATUS    RESTARTS   AGE
... list of running pods ...
$ rancher kubectl get pods -n ${RANCHER_NAMESPACE}
Unable to connect to the server: x509: certificate signed by unknown authority
exit status 1
```

Every `kubectl` command must be given using `--insecure-skip-tls-verify` flag, otherwise it returns this error

```
Unable to connect to the server: x509: certificate signed by unknown authority
```

Is this something expected?

**Comment by superseb** [comment]
This should be the same result if you create a kubeconfig from the UI and use that with kubectl vs using the CLI (meaning not CLI specific). This comes down to how Rancher is installed (single or HA) and how the certificate setup is. The error indicates that the kubeconfig is either missing a private CA certificate which is taken from `/v3/settings/cacerts` which is populated by mounting the file in single or providing `privateCA=true` on Helm install and adding that CA certificate as a secret, or if this is already there (or not if you are using a certificate signed by a recognized CA), then the configured server certificate is probably missing one or more intermediates to complete the chain to the CA. If you can provide how you installed Rancher and what the certificate setup is, we can help trace down the issue.

**Comment by fabn** [comment]
Yes, it's an HA installation made by helm with letsencrypt.

```
USER-SUPPLIED VALUES:
certmanager:
  version: 0.9.1
hostname: dev.xxx.com
ingress.tls.source: letsEncrypt
letsEncrypt.email: xxx@gmail.com
```

```
$ helm ls -n cattle-system
NAME   	NAMESPACE    	REVISION	UPDATED                            	STATUS  	CHART        	APP VERSION
rancher	cattle-system	5       	2020-11-02 17:55:15.32915 +0100 CET	deployed	rancher-2.4.8	v2.4.8
```

I've installed rancher following canonical instructions found here: https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/

It's installed on a DigitalOcean cluster with no L4 load balancer in front of it. I'm accessing it using the ingress controller.
Browser access works like a charm, and everything else is working I'm just having this issue with rancher-cli.

**Comment by fabn** [comment]
Maybe related to this #23146, since it's a long running cluster and I updated it lot of times.

**Comment by superseb** [comment]
That's only applicable if you changed certificate setup between updates. If you create a kubeconfig in the UI, does it contain `certificate-authority-data` for the cluster that points to Rancher? If so, what certificate is in there?

To rule out this is caused due to being in the container, do you get the same response when you use the kubeconfig with kubectl somewhere else (on Linux/Mac/Windows)

**Comment by fabn** [comment]
I checked that data stored in `.rancher/cli2.json` after login is the same of `certificate-authority-data` in my local `~/.kube/config` and the K8S api is actually exposed under an EP like `https://some-random-uuid.k8s.ondigitalocean.com` that actually uses a self signed certificate, thus it must not be a rancher cli issue.

I'm wondering why when using kubectl locally I'm not having any issue, but I think is related on how DigitalOcean manages cluster authentication: https://www.digitalocean.com/docs/kubernetes/how-to/connect-to-cluster/

I'll keep investigating.

**Comment by fabn** [comment]
I made a couple mistakes in my previous message. My local `.kube/config` is different than the one generated by rancher, If I get a `kubeconfig.yaml` from rancher UI I obtain the same exact behavior of CLI. Again I think this is related on how DigitalOcean manage authentication.

If I compare rancher generated kubeconfig with the one downloaded by DO I see the following differences:

```
server:
  DO: https://some-random-uuid.k8s.ondigitalocean.com
  rancher: https://my-rancher-url/k8s/clusters/local
certificate-authority-data: # Same value for both
user:
  token:
    DO: some random hex token
    rancher: kubeconfig-user-49bz5:some random hex token
```

If I change server url and try to connect to DO original URL I get X509 error, and if I pass `--insecure-skip-tls-verify` I obviously get an authentication error

**Comment by superseb** [comment]
The kubeconfig retrieved by the CLI is the same as when you create it via the UI. The default server it will use is Rancher itself as a proxy. It uses the CA certificate that is in `certificate-authority-data` to validate the certificate, but if you used `letsEncrypt` as source, this should be cleared (can be checked under Settings -> `cacerts` or by visiting `$RANCHER_URL/v3/settings/cacerts`). What DO generates is their own kubeconfig using direct access to the clusters which is not related to what Rancher does, so comparing them won't help tracing down the issue. Did you install cert-manager and nginx-ingress manually on the DO k8s cluster?

**Comment by fabn** [comment]
> Did you install cert-manager and nginx-ingress manually on the DO k8s cluster?

Yes I installed them using helm upon cluster creation in DO

> It uses the CA certificate that is in `certificate-authority-data` to validate the certificate, but if you used `letsEncrypt` as source, this should be cleared (can be checked under Settings -> `cacerts` or by visiting `$RANCHER_URL/v3/settings/cacerts`).

It's not empty, it contains DO cert data.

For the records here's the content of `/root/.rancher/cli2.json` upon rancher-cli login

```json
{
  "Servers": {
    "rancherDefault": {
      "accessKey": "token-lstpq",
      "secretKey": "randomHEXstuff",
      "tokenKey": "token-lstpq:randomHEXstuff",
      "url": "https://my-rancher-url",
      "project": "local:p-68llz",
      "cacert": ""
    }
  },
  "CurrentServer": "rancherDefault"
}
```

Here's the settings output from `$RANCHER_URL/v3/settings/cacerts`

```json
{
  "baseType": "setting",
  "created": "2019-09-23T21:05:20Z",
  "createdTS": 1569272720000,
  "creatorId": null,
  "customized": true,
  "default": "",
  "id": "cacerts",
  "labels": {
    "cattle.io/creator": "norman"
  },
  "links": {
    "remove": "https://my-rancher-url/v3/settings/cacerts",
    "self": "https://my-rancher-url/v3/settings/cacerts"
  },
  "name": "cacerts",
  "source": "db",
  "type": "setting",
  "uuid": "bfa71520-8189-497d-9780-3e1bac4b944e",
  "value": "-----BEGIN CERTIFICATE-----\nHERE'S the DO self signed cert\n-----END CERTIFICATE-----"
}
```

**Comment by fabn** [comment]
I also checked in another cluster I manage (installed with same procedure but on baremetal with RKE) that `cacert` is empty and everything works. Also if I remove `certificate-authority-data` from downloaded kubeconfig everything works. 

So I think the issue can be solved by clearing that setting, is that possible?

**Comment by fabn** [comment]
I debugged installed helm chart and I find out that output of `helm get values rancher -n cattle-system --all` was the following (relevant part)

```yaml
COMPUTED VALUES:
ingress:
  extraAnnotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  tls:
    source: rancher
ingress.tls.source: letsEncrypt
privateCA: false
```

Don't know why my `--set ingress.tls.source=letsEncrypt` was stored by helm in this way.

For this reason rancher containers was running without `--no-cacerts` option and thus the issue.

Thanks for your support anyway.
