### ISSUE TITLE
Add HTTP proxy support for Continuous Delivery (Fleet)

### ISSUE THREAD

**Issue by somaritane** [rancher/rancher#30042]
**What kind of request is this (question/bug/enhancement/feature request):**
`enhancement`

**Steps to reproduce (least amount of steps as possible):**

Prerequisite: Rancher is deployed in on-prem environment behind the HTTP proxy, with Continuous Delivery feature (Fleet) enabled.
In Cluster Manager / Continuous Delivery / Git Repos, register new Git Repo pointing to external git repository, e.g.:

- Name: `podinfo`
- Repository URL: `https://github.com/stefanprodan/podinfo.git`
- Paths: `/charts/podinfo`
- Deploy To: pick target cluster

**Result:**

It is expected that application from registered "podinfo" GitRepo is deployed to desired cluster.
However, application is not deployed, "podinfo" GitRepo object is stuck in "Git Updating" state, and its `status:` property contains the following message:
>  `Repo [https://github.com/stefanprodan/podinfo.git] is not accessible:
    >  Get "https://api.github.com/repos/stefanprodan/podinfo/commits/master": context
      deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Other details that may be helpful:**

Following issues have been identified and addressed after investigation:

- [gitjob controller](https://github.com/rancher/gitjob), used by Fleet, doesn't support HTTP proxy settings, therefore it can't clone external git repositories  when deployed behind the proxy. This issue is addressed by https://github.com/rancher/gitjob/pull/20
- Fleet helm chart doesn't have support for HTTP proxy settings. Addressed by https://github.com/rancher/fleet/pull/143
- Although Rancher supports HTTP proxy settings, it doesn't pass them to Fleet deployment bundled with Rancher. Addressed by https://github.com/rancher/rancher/pull/29936 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5.2`
- Installation option (single install/HA): HA

**Comment by somaritane** [comment]
@StrongMonkey, just checking, is there anything else I can do to help with review and apparent merge of related PR to upstream? 
This would help us a lot. We are eager to evaluate Fleet coming with Rancher 2.x on our environment, but are not able to,  due to missing HTTP proxy support.
Thanks a lot.

**Comment by StrongMonkey** [comment]
@somaritane Thanks for the PRs! So far the only one left is to add proxy to fleet chart. I will review that by end of day and once it's merged you can test with rc build(or v2.5-head build). QA will also be able to verify that.

**Comment by izaac** [comment]
Reproduced in Rancher `v2.5.2`

**Comment by izaac** [comment]
Rancher version `v2.5-head (12/03/2020)` _e2e530c_
Rancher version `master-head (12/03/2020)` _a31eecf_

Rancher RKE HA setup behind proxy.
Added one RKE downstream cluster to each Rancher version.
Navigated to Continuous Delivery (Fleet) in the Dashboard.
Added a repository `https://github.com/rancher/fleet-examples` with path `simple`
The `simple` bundle was properly deployed in the default namespace. All resources in active status.
