### ISSUE TITLE
[EKSv2]: no nodegroup message is confusing

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#30041]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
register an EKS cluster that does not have a managed nodegroup

**Result:**
errors is displayed that states "Cannot deploy agent without nodegroups. Deploy a nodegroup".

This is triggered by not having a _managed_ nodegroup. Also, it's not completely true that an agent cannot be deployed without a managed nodegroup, but amanged nodegroups are the supported way of managing node for an EKS cluster in rancher. Error should be changed to something like "Cluster must have a managed nodegroup. Agent may not deploy without one".

**Notes:**
Clarification for anyone curious:
`The new EKS implementation exclusively supports managed nodegroups. That's not to say that the cluster cannot have non managed nodegroup nodes, but at least one is needed so rancher can confirm it is able to deploy the rancher agent and it is the way to provision new nodes through rancher`

**Comment by bmdepesa** [comment]
This refers to an imported cluster.

**Comment by kravciak** [comment]
Fix works fine on v2.5.6-rc4. Warning message shows / disappears fine when I add / remove managed node group to imported cluster.
![Screenshot from 2021-02-12 12-00-58](https://user-images.githubusercontent.com/538604/107779758-19079e00-6d46-11eb-9f46-d4c5815b0c84.png)
