### ISSUE TITLE
Not able to view catalog entries from other catalogs when there is a problem cloning one of the catalogs. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3004]
Server version - Build from master - Dec 10

Using settings page -> "Add Catalog URL" option , add multiple catalogs (in my case 4 catalog entries)
Set invalid value for one of entries.

There is repeated attempts made to clone all the catalogs , even though there was failure encountered only when cloning one of the catalog entries.

This is tracked in - #3003.

We are not able to list catalog entries for the other 3 catalogs which we should be able to clone successfully.

```
Request URL:http://104.197.188.156:8080/v1-catalog/catalogs
Request Method:GET
Status Code:503 Service Unavailable
```

**Comment by prachidamle** [comment]
Fixed this, PR https://github.com/rancher/rancher-catalog-service/pull/36

**Comment by prachidamle** [comment]
PR rancher/rancher-catalog-service#36 is merged, marking this as fixed.

**Comment by sangeethah** [comment]
Tested with latest build from master:

Using settings page -> "Add Catalog URL" option , added 2 catalogs - "test1" and "test2" where "test2" was set to invalid catalog url.

catalog service is not constantly restarting.

I am able to view catalog entries from other catalogs that have been synced successfully.

When I try to view catalogs from "test2" , following message is presented to the user "There are no compatible templates in this Catalog."
