### ISSUE TITLE
Upgrade to Rancher 2.5.2: cattle-cluster-agent hammers apiserver, very high CPU usage

### ISSUE THREAD

**Issue by horihel** [rancher/rancher#30048]
**What kind of request is this (question/bug/enhancement/feature request):**
possible bug

**Steps to reproduce (least amount of steps as possible):**
upgrade existing rancher from 2.4.8 to 2.5.2

**Result:**
cattle-agent cpu utilization skyrockets
![grafik](https://user-images.githubusercontent.com/6735079/98927075-5dca3180-24d8-11eb-96ac-db854a2b179b.png)

upgrade took place at 08:00, since then cattle-agent heats the CPU. It also seems to affect kube-apiserver (also taking >100%)

I have this on 2 clusters, one using vsphere and one custom bare metal provisioned by rancher. 

Requests to kube-apiserver also went up at the same time
![grafik](https://user-images.githubusercontent.com/6735079/98927809-4ccdf000-24d9-11eb-9010-579277571834.png)

Judging by more prometheus metrics it seems to write a lot to "apps" resources:
![grafik](https://user-images.githubusercontent.com/6735079/98928619-44c28000-24da-11eb-868e-462cb2826ec7.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.5.2
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
2 Clusters show the problem: one rancher provisioned on Vsphere and one Custom/Bare Metal, also rancher provisioned.
- Machine type (cloud/VM/metal) and specifications (CPU/memory):

Vsphere-Cluster:
VMs (3 mgmt nodes, 4 CPU, 16GB RAM each, 6 workers, 4 CPUs, 16GB RAM each), based on RancherOS

Custom Cluster:
Metal, 5 mixed nodes, (4-8 CPUs, 8-64GB memory).

- Kubernetes version (use `kubectl version`):
1.18.10

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
metal cluster: 19.3.8
VM cluster: 19.3..8
```

**Comment by lucky4ever2** [comment]
I'm not sure if it's the same problem, but since the update from 2.5.1 to 2.5.2 I've also had problems with high cpu.
I did the update at 9:30 am and since then my monitoring system (checkmk) shows a much higher CPU load and CPU utilization on every node. The RAM is not affected.

![grafik](https://user-images.githubusercontent.com/46378117/99044424-0ab3b580-2590-11eb-8926-daf336259f85.png)

![grafik](https://user-images.githubusercontent.com/46378117/99044615-51091480-2590-11eb-80d5-559dab20409c.png)

I have a Rancher Cluster based on VMs (Hyper-V) with 3 Nodes and Bare Metal Cluster with 3 Nodes created with rancher. 
It affects both clusters (Kubernetes Version 1.19.3).

kube-apiserver in top display:
![grafik](https://user-images.githubusercontent.com/46378117/99048239-9714a700-2595-11eb-8707-0dc9be1e994c.png)

**Comment by horihel** [comment]
I rolled back rancher to 2.4.8 and the problem is gone.

**Comment by lucky4ever2** [comment]
how did you roll back rancher?

**Comment by horihel** [comment]
as i'm using a docker install, basically following this doc: https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/single-node-rollbacks/

**Comment by lucky4ever2** [comment]
I have now restored the vm snapshots. Now it looks good again:
![grafik](https://user-images.githubusercontent.com/46378117/99074523-2fbc1e80-25b8-11eb-82c2-6369640ba9a6.png)
![grafik](https://user-images.githubusercontent.com/46378117/99074549-3c407700-25b8-11eb-970b-3401caaa7861.png)
![grafik](https://user-images.githubusercontent.com/46378117/99074605-58dcaf00-25b8-11eb-8307-2f7ed19e0c9f.png)

**Comment by mrajashree** [comment]
@horihel @lucky4ever2 do you have Project Network Isolation enabled on these clusters? and do you see the logs reported in [this](https://github.com/rancher/rancher/issues/30052#issue-741735409) issue?

**Comment by lucky4ever2** [comment]
Yes, i have Network Isolation enabled. I don't have any logs because I wanted to downgrade again quickly.

**Comment by mrajashree** [comment]
@lucky4ever2 okay, it's a known issue with 2.5.2, we're tracking it with [this](https://github.com/rancher/rancher/issues/30045) issue. The workaround is to turn off project network isolation. But I see that you have already successfully rolled back to 2.4.x so you don't need to turn off network isolation on 2.4.x
Once @horihel confirms if he has the same issue, we can close this issue and use the other one for tracking the fix.

**Comment by horihel** [comment]
I can confirm that network isolation was enabled on both clusters on my side too.

as i already rolled back, i can not immediately confirm if disabling solves the problem. I'll try and setup a new test env.

**Comment by maggieliu** [comment]
closing in favor of: https://github.com/rancher/rancher/issues/30045

**Comment by horihel** [comment]
is it possible to re-open this issue?
upgrading to 2.5.3 did _not_ solve the problem
disabling network isolation (after upgrade) did _not_ solve the problem.
(in relation to #30045:): redeploying ingress controller did _not_ solve the problem.

cluster operation seems to be still working, although slower than usual. 

please advise, otherwise i need to downgrade again.

**Comment by horihel** [comment]
tried the upgrade to 2.5.3 again today, this time turning PNI off before upgrading. Still misbehaving.

downgraded and upgraded to 2.4.11 instead - this time behaviour of cattle-cluster-agent seems to be normal.

so 2.4.11 seems to be fine, 2.5.3 (stable) seems to be still misbehaving.

**Comment by danielschlegel** [comment]
I also have high cpu on 2.5.3 if i try to go to system project. The server has less than 10% CPU usage while idle, if i try to access system project CPU goes to 300% and request failes after timeout.

**Comment by nickvth** [comment]
Please reopen, still issues wih 2.5.3
