### ISSUE TITLE
[UI] rke.windows should show as Windows

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30046]
The cluster provider function has been modified to differentiate between linux RKE1 vs windows RKE1 [here](https://github.com/rancher/rancher/issues/28947), need to update the UI to show windows

**Comment by StrongMonkey** [comment]
@westlywright Backend change is merged in 2.5-head and master.

**Comment by westlywright** [comment]
@sowmyav27 mentioned that she is not seeing the change in master or 2.5. I add the awaiting backend tag again, can @sowmyav27 or @StrongMonkey remove the tag when the backend is fixed? Thanks

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `395b4fe7`**
- Windows cluster shows `RKE1`. And custom shows `Custom` as the provider.

**Expected:**
- now that windows shows provider as `rke.windows` in View in API, it should still show the right provider - Custom on the UI.

**Comment by deniseschannon** [comment]
`rke.windows` should show `Windows` as the provider

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `3df817c5` and master-head - commit id: `e4ce3766`**

- Windows cluster, provider is shown as "Windows"
<img width="1255" alt="Screen Shot 2020-12-09 at 3 22 49 PM" src="https://user-images.githubusercontent.com/26032343/101700801-86d7d680-3a32-11eb-8926-c1447ba41549.png">

- Custom cluster windows enabled - with just linux nodes, shows cluster type as "Custom"
