### ISSUE TITLE
Ingress controller has labels in pods

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30045]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Upgrade usecase:**

- On 2.4.8, deploy a DO cluster with Project Isolation enabled.
- create workload and ingress ing01 pointing to this
- Upgrade Rancher to 2.5.2
- Notice user ingresses go to `Initializing` state.
- The ingress still has only one worker node's ip address under loadBalancer when doing a View/Edit in Yaml for the ingress
- Ingress-controller's pods have `podName` label on and off
- disable and then enable project network isolation
- `field.cattle.io/podName: nginx-ingress-controller-bfnkt` label on the ingress controller is seen. 
- And User Ingresses are stuck in Initializing state. 
- Rancher logs in debug mode:
```
2020/11/12 20:02:19 [DEBUG] podHandler: addLabelIfHostPortsPresent: deleting podNameFieldLabel map[app:ingress-nginx controller-revision-hash:7649c75c8c field.cattle.io/podName:nginx-ingress-controller-2r8pd pod-template-generation:1] in ingress-nginx
2020/11/12 20:02:19 [DEBUG] netpolMgr: delete: existing=nil, err=networkPolicy.networking.k8s.io "ingress-nginx/hp-nginx-ingress-controller-2r8pd" not found
2020/11/12 20:02:19 [DEBUG] podHandler: Sync: {TypeMeta:{Kind:Pod APIVersion:v1} ObjectMeta:{Name:nginx-ingress-controller-2r8pd GenerateName:nginx-ingress-controller- Namespace:ingress-nginx SelfLink:/api/v1/namespaces/ingress-nginx/pods/nginx-ingress-controller-2r8pd UID:c7437eac-db2f-446b-ad3f-93faec7be429 ResourceVersion:26731 Generation:0 CreationTimestamp:2020-11-12 19:29:32 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app:ingress-nginx controller-revision-hash:7649c75c8c pod-template-generation:1] Annotations:map[prometheus.io/port:10254 prometheus.io/scrape:true] OwnerReferences:[{APIVersion:apps/v1 Kind:DaemonSet Name:nginx-ingress-controller UID:cc372d02-48ab-4082-b5e2-c974431a0ebb Controller:0xc0099ff579 BlockOwnerDeletion:0xc0099ff57a}] Finalizers:[] ClusterName: ManagedFields:[{Manager:kube-controller-manager Operation:Update APIVersion:v1 Time:2020-11-12 19:29:32 +0000 UTC FieldsType:FieldsV1 FieldsV1:&FieldsV1{Raw:*<redacted>

```

**Expected Result:**
- `field.cattle.io/podName: nginx-ingress-controller-bfnkt` label on the ingress controller should NOT be seen

**Other details that may be helpful:**

- Related issue: https://github.com/rancher/rancher/issues/26677
- This also happens on an upgrade from 2.4.8 to 2.4.10
- This flapping is seen on a fresh install of 2.5.2 also - deploy a cluster on 2.5.2, debug statements in rancher logs show the flapping

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.8 to 2.5.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE DO
- Kubernetes version (use `kubectl version`):

```
1.18.10-rancher1-2
```

**Comment by UberKuber** [comment]
@sowmyav27, the process I've tested now is as per below:

1. Disable project network isolation on the cluster
2. Redeploy nginx ingress controller daemonset
3. Enable project network isolation on the cluster

I have tested this process against multiple downstream clusters behind Rancher v2.5.2 and Rancher v2.4.10 and it's resolved the issue from what I can pick up.

**Comment by al45tair** [comment]
Personally, I've just installed my patched ingress-nginx into our cluster again ([here is the patch](https://github.com/al45tair/ingress-nginx/commit/fa16751c9c55f825adb9651b94f85f35b59ebdf5)).

This resolves the problem by making the ingress controller ignore Rancher's podName label.

**Comment by kinarashah** [comment]
For testing: 

Fresh Install Rancher v2.4-head and v2.5-head 
- Create cluster with Project Network Isolation Enabled >=2 worker nodes. 
- Confirm pods of `nginx-ingress-controller` in system project don't have podName labels. 
- Turn on debug, redeploy `nginx-ingress-controller` and confirm the pods don't get updated without cause. Can be confirmed by looking for `delete podNameLabel` in logs. 
- Create user ingress, confirm the status.LoadBalancer shows IPs of all the worker nodes. 

Upgrade Scenario: 
- Rancher v2.4.8 or earlier, Create cluster with Project Network Isolation Enabled >=2 worker nodes. 
- Create few network policies. These would be in addition to the ones Rancher creates on default for project network isolation. 
- Create few user ingresses. status.LoadBalancer might not have IPs of all the worker nodes. 
- Upgrade to v2.4-head/v2.5-head/corresponding RCs 
- Confirm pods of `nginx-ingress-controller` in system project don't have podName labels. 
- Turn on debug, redeploy `nginx-ingress-controller` and confirm the pods don't get updated without cause. Can be confirmed by looking for `delete podNameLabel` in logs. 
- Delete pods of `nginx-ingress-controller` in system project one by one. Confirm user ingresses don't go to Initializing state. 
- Confirm user network policies remain as is and don't get deleted. 
- On user ingresses, confirm the status.LoadBalancer shows IPs of all the worker nodes. 
- Check Kubelet logs to confirm there are no unlimited SyncLoop updates on nginx ingress. 

Note: There are a few ways Ingress could be redeployed. 
- Redeploy from UI / `kubectl rollout restart ds nginx-ingress-controller -n ingress-nginx`: These could temporarily let user ingresses to go to Initializing state. But they should become active after all the pods are Active and running. 
- Delete pods of the ds manually and wait for the new pod to be running, then delete the next pod. This doesn't result into user ingresses go to Initializing state. (AFAIK, needs confirmation). 

Upgrade Scenario from v2.4.9/v2.4.10/v2.5.2: 
- Continue from step 4.

**Comment by sowmyav27** [comment]
**On 2.4-head - commit id: `6a09f523f`**

- Create cluster with Project Network Isolation Enabled 1 etcd/control and 2 worker nodes.
- Pods of `nginx-ingress-controller` in system project do not have podName labels.
- In Debug mode, redeploy `nginx-ingress-controller` and confirm the pods don't get updated without cause. `podHandler: addLabelIfHostPortsPresent: deleting podNameFieldLabel` is NOT seen in logs.
- Deploy user ingress, verified the status.LoadBalancer shows IPs of all the worker nodes - 2 worker nodes.
```
status:
  loadBalancer:
    ingress:
    - ip: <ip-1>
    - ip: <ip-2>
```

**Comment by leflambeur** [comment]
Thanks, @kinarashah and @sowmyav27 for the quick turnaround on this :)

**Comment by sowmyav27** [comment]
### **Fresh Install use case - On `2.5.3-rc1`**

- Create cluster with Project Network Isolation Enabled 1 etcd/control and 2 worker nodes.
- Pods of `nginx-ingress-controller` in system project do not have podName labels.
- In Debug mode, redeploy `nginx-ingress-controller` and confirm the pods don't get updated without cause. `podHandler: addLabelIfHostPortsPresent: deleting podNameFieldLabel` is NOT seen in logs.
- Deploy user ingress, verified the status.LoadBalancer shows IPs of all the worker nodes - 2 worker nodes.
```
status:
  loadBalancer:
    ingress:
    - ip: <ip-1>
    - ip: <ip-2>
```

**Comment by sowmyav27** [comment]
Closing this as its been validated on 2.5.3 and 2.4 branches.
