### ISSUE TITLE
Set PriorityClass for kube-flannel, kube-dns, kube-dns-autoscaler, metrics-server to system-node-critical

### ISSUE THREAD

**Issue by asemen2608** [rancher/rancher#30047]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Manually patch and add priorityclasses for kube-flannel, kube-dns, kube-dns-autoscaler, metrics-server to system-node-critical deployments:
```
kubectl patch daemonset kube-flannel --patch '{"spec": {"template": {"spec": {"priorityClassName": "system-node-critical"}}}}'

kubectl patch deployment kube-dns --patch '{"spec": {"template": {"spec": {"priorityClassName": "system-cluster-critical"}}}}'

kubectl patch deployment kube-dns-autoscaler --patch '{"spec": {"template": {"spec": {"priorityClassName": "system-cluster-critical"}}}}'

kubectl patch deployment metrics-server --patch '{"spec": {"template": {"spec": {"priorityClassName": "system-cluster-critical"}}}}'
```

Run kube-flannel update in a cluster upgrade.

**Result:**
The Priority Class settings get lost on a cluster upgrade because the daemonset is overwritten with default settings.

**Other details that may be helpful:**

The goal is to set a PriorityClass for kube-flannel, kube-dns, kube-dns-autoscaler, metrics-server, or flag them as "system-cluster-critical" in Rancher UI which will not be removed or overwritten on update or upgrade.

Using PriorityClass has the side effect that if not set for "kube-flannel, kube-dns, kube-dns-autoscaler and metrics-server" they get a lower priority, which can cause critical issues.

Manually patched and added PriorityClass for kube-dns, kube-dns-autoscaler, kube-flannel, and metrics-server these deployments work until an update is deployed. It should not remove their PriorityClass setting.

Perhaps, to set Rancher to use the Kubernetes "system-cluster-critical" value for the affected workloads.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.8
- Installation option (single install/HA): HA

gz#13214

**Comment by superseb** [comment]
Todo:

* Determine what is the current state of upstream and decide if this is the new default or if this needs to be made configurable
* Implement the choice from above
* Test if the setting is configured
* Add docs on the new default/configurable setting

**Comment by asemen2608** [comment]
The point is the customer is using **priorityClassName** for his cluster to prioritizes pods. The side effect is that kube-flannel, kube-dns and kube-dns-autoscaler has by default no  **priorityClassName**.
The could be too slow, the cluster would crash. 
Therefore the customer is patching. On update, the patches get lost.

**Comment by asemen2608** [comment]
Please share a status update. Is planed ETA for Rancher v2.5.5?

**Comment by PennyScissors** [comment]
@asemen2608 Can you provide more information on how to reproduce this issue? I did the following and no success:

1. Run rancher v2.4.8 from docker image
2. Create cluster k8s version v1.15.12-rancher2-7 and use kube-flannel
3. Patch flannel and metrics-server from kubectl as following:
```
kubectl patch deployment metrics-server --patch '{"spec": {"template": {"spec": {"priorityClassName": "system-cluster-critical"}}}}' -n kube-system
kubectl patch daemonset kube-flannel --patch '{"spec": {"template": {"spec": {"priorityClassName": "system-node-critical"}}}}' -n kube-system
```
4. Verify priority class was set
```
kubectl get deployment metrics-server -n kube-system -o yaml
kubectl get daemonset kube-flannel -n kube-system -o yaml
```
5. Increase `Recurring etcd Snapshot Interval` to `13` in the UI's Cluster Edit page to trigger an update
6. Check priority class in kube-flannel and metrics-server (Template is different and kept changes from patch)
7. Upgrade cluster to k8s v1.16.15-rancher1-3
8. Check priority class in kube-flannel and metrics-server (Template is different and kept changes from patch)

**Comment by asemen2608** [comment]
PriorityClass could be set in rkeConfig.
For example:
- https://rancher.com/docs/rke/latest/en/config-options/add-ons/dns/
- https://rancher.com/docs/rke/latest/en/config-options/add-ons/network-plugins/

```
dns:
provider: coredns
priorityClassName: system-cluster-critical
network:
plugin: flannel
priorityClassName: system-node-critical 
```

**Comment by deniseschannon** [comment]
This is currently available to test in 2.5-head and the master PRs are slowly geting in. We should start testing with 2.5-head first

**Comment by slickwarren** [comment]
Here is what will be tested:
* rancher v2.5-head (4cb2ebe259c073a2ea0611736731b98280ca6951)
* configure `priority_class_name` via cluster yaml file through rancher UI (when provisioning cluster)
* format is `<service_name>_priority_class_name: <priority_class>` i.e. `metrics_server_priority_class_name: system-node-critical` which is a parameter under `options`, except for metrics_server and ingress 
* check these resources by running `kubectl get <type> -n <namespace> -o yaml | grep priorityClassName`. 
*  find the type and namespace by navigating to the `system` project of your cluster


what has been tested and is working correctly:
* metrics_server
* nginx_ingress_controller + default_http_backend
* canal
* kube-flannel
* calico_kube_controllers


tested, but not configuring:
* coredns_autoscaler  yaml persists, but resource `<service_name>_priority_class_name` does not exist
* coredns -- yaml persists, but resource `<service_name>_priority_class_name` does not update

(fixes will be posted later by @PennyScissors for above issues)

still need to test: 
kubedns, nodelocal, calico

**Comment by slickwarren** [comment]
part of this (dns) is still not working correctly and appears to be a UI issue. 
when passing this through the yaml:
```
dns:
  options:
    coredns_priority_class_name: system-node-critical
```
the UI converts this to camelCase instead of the values used in the yaml
![image](https://user-images.githubusercontent.com/16691014/107437856-7997a080-6ae4-11eb-8eb2-b6273eec1fa8.png)

All other addons are able to have a `<service_name>_priority_class_name` set through the yaml.

**Comment by PennyScissors** [comment]
Just wanted to clear up a few things:

This issue was filed for specific addons, but the configurable priority class name option has been to all of these so that we don't need to update them in the future.
* calico
* canal
* flannel
* coredns
* kubedns
* nodelocaldns
* metrics-server
* weave
* ingress

The coredns issue is not in the backend. The backend work is complete, but to fix the issue itself [this UI issue](https://github.com/rancher/rancher/issues/31230) must be resolved first. At a high level, the problem is the UI is changing `addon_name_priority_class_name` to `addonNamePriorityClassName` and it breaks because the backend expects the former (underscore_case) for `dns.options` specifically.
All other addons can be tested as they are not affected, but DNS can only be tested using the API UI or RKE standalone until the UI issue is fixed.

**Comment by slickwarren** [comment]
now able to save DNS config type correctly tested on 2.5-head (03b8153) and master-head(007e298)
all of the addons from the above comment have been tested and work properly with <addon_name>_priority_class_name set in the yaml when provisioning the cluster.

**Comment by slickwarren** [comment]
documentation request here: https://github.com/rancher/docs/issues/3122
