### ISSUE TITLE
[2.4] Rancher 2.4.8 Memory Leak

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30058]
backport for https://github.com/rancher/rancher/issues/29429

**Comment by sowmyav27** [comment]
This has been reverted because of - https://github.com/rancher/rancher/issues/30220

**Comment by bmdepesa** [comment]
Reproduced in Rancher v2.4.8
* RKE cluster, Rancher installed via Helm with `replicas=1` and monitoring enabled on the local cluster
* Create 30 imported clusters
  * In this case, imported the same cluster repeatedly as it updates the agents in the cluster
* Delete the agents deployment/ds from the `cattle-system` ns on each cluster
* In the logs, see `Stopping cluster agent ...` every 2 minutes
* Memory usage for the `rancher` pod increases over many hours. In this case, starting around 300mb usage, it eventually increased to 1.2gb at its peak

rancher/rancher:v2.4-4534-head

* Use the [scaling framework](https://github.com/rancher/rancher2-scaling) to provision a k3s cluster with Rancher installed via Helm, `replicas=1`, and local monitoring enabled
* Use the scaling framework to create and import 30 k3s clusters
* Delete the agents deployment/ds from the `cattle-system` ns in each cluster
* Every 2 minutes, `Stopping cluster agent ...` appeared in logs
  * Sometimes the `Rancher` pod may need to be restarted for the controllers to begin looping - this is unclear why
* Over the course of 12 hours, memory usage was avg 308mb, with one peak of 320mb
