### ISSUE TITLE
Failed To Upgrade Control Plane - 400 bad request - unable to update cni config

### ISSUE THREAD

**Issue by JRNC** [rancher/rancher#30054]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Setup an on-prem HA Rancher cluster, add a cluster using the "existing nodes" option, and run the docker run command on a new node.

**Result:**
In the Rancher UI, the error message "Failed To Upgrade Control Plane" is shown.

Looking in the kubelet container logs on the node shows "node "mynodehostname" not found," "Failed to contact API server when waiting for CSINode publishing," "Unable to update cni config: no networks found in /etc/cni/net.d," and "Unable to register node "mynodehostname" with API server: nodes is forbidden: User "system:node" cannot create resource "nodes" in API group "" at the cluster scope"

The rancher-agent container logs show "Connecting to proxy" url="wss://my.fqdn.com/v3/connect/register" then ""Failed to connect to proxy. Response status: 400 - 400 Bad Request. Response body: Operation cannot be fulfilled on nodes.management.cattle.io \"m-29f347a6ebdd\": the object has been modified; please apply your changes to the latest version and try again" error="websocket: bad handshake"

**Other details that may be helpful:**
The environment is compromised of on-prem VMs. The Rancher server was stood up using the instructions for an HA Rancher cluster using a 3 node RKE cluster. The Rancher cluster is fronted by a layer 4 NGINX load balancer that was configured using Rancher's recommended nginx.conf template. The servers are behind a proxy for internet access and are all on the same subnet.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):  v1.19.3

```
(paste the output here)
```

- Docker version (use `docker version`): 19.03.13

```
(paste the output here)
```

**Comment by aiyengar2** [comment]
What kind of OS are the existing nodes running? This error seems similar to https://github.com/rancher/rancher/issues/26880.

**Comment by bombonato** [comment]
Same here when trying add worker node to existing cluster using RKE with docker . I not received the "400 bad request" at /v3/connect/register, but failed kubelet logs with ""Unable to update cni config: no networks found in /etc/cni/net.d,". I checked that "/etc/cni" directory is empty.
I saw the #26880 and check /etc/sysctl.d/90-kubelet.conf, it's alread created (not by me).
This node already exist at past, but I have some issues with DNS resolutions/CoreDNS and tried to remove that node from rancher ui, clean all docker directories, containers, images, and tried to add again through docker rke command to add worker node.
Important note:
- I change my kube-proxy to ipvs mode and ipvs-strict-arp (to use with Metallb)
- I upgrade my kubernets to: v1.18.12-rancher1-1 (from 1.18.08 to 1.18.10 to 1.18.12)

@JRNC or anyone has any tip or workaround? 

My enviroment:
- RKE with docker
- VMs (VMWare)
- 3 nodes: Controlplane, etcd, worker
- 2 nodes: worker
- Ubuntu 20.04
- Kernel 5.4.0-54-generic
- kubernets: v1.18.12-rancher1-1
- Docker version 19.03.13
- Docker changed to "Cgroup Driver: systemd"
- Docker images:
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
rancher/hyperkube       v1.18.12-rancher1   5a4e0e4992f4        4 days ago          1.56GB
rancher/rke-tools       v0.1.66             fc106f3a0e0e        3 weeks ago         133MB
rancher/rancher-agent   v2.5.1              141c7125f5a2        5 weeks ago         472MB

**Comment by JRNC** [comment]
I was able to resolve my issue. There were a few changes made, but I think it was primarily an issue with running out of disk space on my /var logical volume and having an entry in my /etc/hosts file for our primary domain, when this node was in a subdomain.

**Comment by lindhe** [comment]
Just to clarify, @JRNC: do you mean the disk space of `/var/` on the actual host machine for the node, or in the container?

**Comment by JRNC** [comment]
Host machine of the node. That being said, now I am trying to remove a node, rebuild it and add it to a new cluster and that is failing to upgrade the control plane (running RHEL 7 on nodes).

**Comment by JRNC** [comment]
As mentioned above, I have resolved my initial issue. I am now running into an issue with re-registering a node to a new cluster, but I will open a different issue for this.

**Comment by lindhe** [comment]
Oooh. I see 95% disk usage on my system drive. Perhaps this can be resolved via Black Friday...
