### ISSUE TITLE
[2.3] KDM Release - k8s patches for Nov

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30069]
Update k8s to the latest patches:
1.17.14 - 2.3.8+

**Comment by jiaqiluo** [comment]
the new k8s version `v1.17.14-rancher1-1` is validated. 
The KDM `dev-2.3` branch is used.
 
- on rancher:`v2.3.8`, network tests are passed for all network providers on 1.17.14 clusters 
- on rancher:`v2.3.9`, both network and upgrade tests are passed for all network providers on 1.17.14 clusters
- on rancher:`2.3.7`, the new version does not show up

**Comment by jiaqiluo** [comment]
RKE CLI `v1.0.14-rc1` is validated for supporting the new k8s version `v1.17.14-rancher1-1`

**Comment by sowmyav27** [comment]
Validated on `v1.0.14-rc2` using k8s `v1.17.14-rancher1-1`. Checks passed

**Comment by superseb** [comment]
- kontainer-driver-metadata PR merged
- RKE v1.0.14 released
- Updated forum announcement for 2.3.x
