### ISSUE TITLE
Installing Helm chart from Azure Blob Storage repository fails

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#30068]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a Helm repository on Azure Blob Storage (using authenticated access with SAS token)
      - Either create your own (see [details](https://medium.com/@fmataraci6/using-azure-blob-service-as-private-helm-repository-82fda8db2ba9))
      - or use the existing repository hosted under [this URL](https://tpblob.blob.core.windows.net/helm?sp=rl&st=2020-11-12T17:35:18Z&se=2020-12-12T17:35:00Z&sv=2019-12-12&sr=c&sig=NPnaHbZIArf70vL40KSUUBgRD6fMDy1NyJ3QoS7BCvc%3D)
2. Confirm that the repository is indeed working when used with the Helm v3 command line (`helm repo add azure-blob <URL>`)
3. Add the repository to Rancher (Cluster Explorer -> Marketplace -> Repositories)
4. Deploy a chart from the repository

**Result:**

Chart installation fails with error:
> Error: gzip: invalid header

Rancher logs:
```
2020/11/12 17:52:42 [INFO] Downloading repo index from https://tpblob.blob.core.windows.net/helm/index.yaml?sp=rl&st=2020-11-12T17:35:18Z&se=2020-12-12T17:35:00Z&sv=2019-12-12&sr=c&sig=NPnaHbZIArf70vL40KSUUBgRD6fMDy1NyJ3QoS7BCvc%!D(MISSING)
2020/11/12 17:52:42 [INFO] Downloading repo index from https://tpblob.blob.core.windows.net/helm/index.yaml?sp=rl&st=2020-11-12T17:35:18Z&se=2020-12-12T17:35:00Z&sv=2019-12-12&sr=c&sig=NPnaHbZIArf70vL40KSUUBgRD6fMDy1NyJ3QoS7BCvc%!D(MISSING)
2020/11/12 17:52:48 [ERROR] Unknown error: gzip: invalid header
```

**Expected Result:**

Helm CLI supports this chart repository and it should work in Rancher as well.

**Background info:**

The URL for the repository hosted on Azure Blob Storage contains an SAS token as query string parameters.

Example:
```
https://tpblob.blob.core.windows.net/helm?sp=rl&st=2020-11-12T17:35:18Z&se=2020-12-12T17:35:00Z&sv=2019-12-12&sr=c&sig=NPnaHbZIArf70vL40KSUUBgRD6fMDy1NyJ3QoS7BCvc%3D
```

Root cause:

The query parameters are correctly used by Rancher while fetching the Chart index.     
But while constructing the download URL for the chart package, the query string is invalidated by appending a slash to the end of the query string instead of to the end of the path (see [commit](https://github.com/rancher/rancher/commit/b4e7f18659a23e17793674ff6b33372e479248d6)). The query string is then also completely lost by creating a new URL instance from `net.ResolveReference` without retaining the query string of the base URL.

**Environment information**
Rancher version: 2.5.2

**Comment by janeczku** [comment]
@slickwarren  you may use this new URL to test (the previous one expired):

```
https://tpblob.blob.core.windows.net/helm?sp=rl&st=2021-02-11T18:14:13Z&se=2021-10-09T18:14:00Z&sv=2019-12-12&sr=c&sig=KwupnM%2Fkh7u1i99Ow%2BlcLpl5R%2BBULWu7MwLk9bvaL1c%3D
```

**Comment by slickwarren** [comment]
I am still seeing the issue occur on 2.5-head (8b65a6a) and master-head (990c1ad)
`POST https://<IP>/v1/catalog.cattle.io.clusterrepos/azure-from-ticket?action=install 500 (Internal Server Error)`
`{"type":"error","links":{},"code":"ServerError","message":"gzip: invalid header","status":500,"type":"error"}`
<img width="1001" alt="Screen Shot 2021-02-11 at 11 45 17 AM" src="https://user-images.githubusercontent.com/16691014/107690183-a1ab0f00-6c5e-11eb-978a-e208d49a18d8.png">
<img width="1521" alt="Screen Shot 2021-02-11 at 11 37 27 AM" src="https://user-images.githubusercontent.com/16691014/107690187-a40d6900-6c5e-11eb-9b66-4775d1affb82.png">

**Comment by janeczku** [comment]
@slickwarren The test artifact was corrupt (The object urls in the index.yaml ware expired as well). I have fixed the file and it should be retested with that same URL.

First, verify that the URL for the chart repository is now working:

```
helm repo add test https://tpblob.blob.core.windows.net/helm?sp=rl&st=2021-02-11T18:14:13Z&se=2021-10-09T18:14:00Z&sv=2019-12-12&sr=c&sig=KwupnM%2Fkh7u1i99Ow%2BlcLpl5R%2BBULWu7MwLk9bvaL1c%3D
helm repo update
helm fetch test/hello-world
```

Then use that same URL to retest.

```
https://tpblob.blob.core.windows.net/helm?sp=rl&st=2021-02-11T18:14:13Z&se=2021-10-09T18:14:00Z&sv=2019-12-12&sr=c&sig=KwupnM%2Fkh7u1i99Ow%2BlcLpl5R%2BBULWu7MwLk9bvaL1c%3D
```

**Comment by slickwarren** [comment]
ah, yes that fixed it and the error no longer occurs (tested on 2.5-head (8b65a6a) and master-head (990c1ad))
<img width="1524" alt="Screen Shot 2021-02-11 at 1 56 04 PM" src="https://user-images.githubusercontent.com/16691014/107703708-e6d83c80-6c70-11eb-93e9-43bab944e4cc.png">

**Comment by janeczku** [comment]
@slickwarren I created a complete new chart repository on Azure Blob for bugfix validation. It has the following content:

### Test repo:


```
$ ls helm-repo
hello-world           hello-world-0.1.0.tgz index.yaml

$ cat helm-repo/index.yaml
apiVersion: v1
entries:
  hello-world:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-02-12T11:41:17.835336+01:00"
    description: A Helm chart for Kubernetes
    digest: b21f1406874aa6dc89776ee2245f2055b1302f073b6bb58667119b99cf27630d
    name: hello-world
    type: application
    urls:
    - hello-world-0.1.0.tgz
    version: 0.1.0
generated: "2021-02-12T11:41:17.834569+01:00"
```

Chart URI:

``` 
https://tpblob.blob.core.windows.net/helm?sp=rl&st=2021-02-12T10:36:52Z&se=2021-09-23T10:36:00Z&sv=2019-12-12&sr=c&sig=j69iuJJ7Elbasi9NqHuA3vvxmSQ52QiU%2FMMJUW8Ope8%3D
```

### Bugfix validation test steps:

1. Using the Helm CLI, verify the chart repo is valid and the hello-world chart can be downloaded:


```
helm repo add test https://tpblob.blob.core.windows.net/helm?sp=rl&st=2021-02-12T10:36:52Z&se=2021-09-23T10:36:00Z&sv=2019-12-12&sr=c&sig=j69iuJJ7Elbasi9NqHuA3vvxmSQ52QiU%2FMMJUW8Ope8%3D
helm repo update
helm repo fetch test/hello-world
```

2. Verify installation of the chart via Cluster Explorer UI fails on Rancher 2.5.3

3. Verify installation of the chart via Cluster Explorer UI succeeds on Rancher 2.5.5-head

**Comment by slickwarren** [comment]
using `https://tpblob.blob.core.windows.net/helm?sp=rl&st=2021-02-12T10:36:52Z&se=2021-09-23T10:36:00Z&sv=2019-12-12&sr=c&sig=j69iuJJ7Elbasi9NqHuA3vvxmSQ52QiU%2FMMJUW8Ope8%3D` as the entry for helm repository, I was able to do the following:
* verify repo can be fetched from a local machine by running:
```
helm repo add test https://tpblob.blob.core.windows.net/helm?sp=rl&st=2021-02-12T10:36:52Z&se=2021-09-23T10:36:00Z&sv=2019-12-12&sr=c&sig=j69iuJJ7Elbasi9NqHuA3vvxmSQ52QiU%2FMMJUW8Ope8%3D
helm repo update
helm repo fetch test/hello-world
```
* Add repo to v2.5.2, 2.5-head (dba332111aacdba283baabdc6501d5c42079a3e4) and master-head (98fe72a)
* installation of chart on v2.5.2 fails (expected)
* installation of chart on 2.5-head and master-head succeeds.
