### ISSUE TITLE
[Monitoring V2] Remove deprecated references to kubernetes-charts.storage.googleapis.com

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#30063]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

`kubernetes-charts.storage.googleapis.com` is deprecated as of November 13th, 2020. While this won't affect the packaged charts in `rancher/charts`, this will affect the ability to prepare the current Monitoring chart once it is deprecated.

**Comment by jiaqiluo** [comment]
in the monitoring chart `9.4.201`, the repo `kubernetes-charts.storage.googleapis.com` is used at the following 2 places in the [requirmetns.yaml](https://github.com/rancher/charts/blob/main/charts/rancher-monitoring/requirements.yaml)
```
  - name: kube-state-metrics
    version: 2.8.14
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: kubeStateMetrics.enabled
 
  - name: prometheus-adapter
    version: 2.4.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: prometheus-adapter.enabled
```




Now in the monitoring chart `v9.4.202`, there are replaced by the following new values:
```
  - name: kube-state-metrics
    version: 2.8.14
    repository: https://charts.helm.sh/stable/
    condition: kubeStateMetrics.enabled

  - name: prometheus-adapter
    version: 2.7.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-adapter.enabled
```
https://github.com/rancher/charts/blob/dev-v2.5/charts/rancher-monitoring/requirements.yaml
