### ISSUE TITLE
Saving userPreferences sometimes fails with 422 status code

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#3007]
We are on:
```
Component 	Version
Rancher 	v0.49.1
Cattle 	v0.121.0
User Interface 	v0.71.0
Rancher Compose 	v0.6.1
```

**Issue**

I want to change the default login environment. I am Admin of Rancher. I go to Manage Environments > click on another environment that is not default > in the menu click "Set as default environment"

Go back to the list of environments and see that the previous action was not applied. I retried looking at the browser network inspector and found that the PUT method returns a status code 422 (Unprocessable Entity).  I would have expect an error message in the UI.

Attached the screendump of the browser (firefox 39.0), same on Chrome 47.

![rancher default login environment png 1180x937](https://cloud.githubusercontent.com/assets/320440/11742728/77ec1e94-a002-11e5-93a9-17488801fb75.png)

**Comment by vincent99** [comment]
@hibooboo2 did the fix for this 422 make it in?

**Comment by demarant** [comment]
tried again in v0.50.0-rc2 and issue is there as well

**Comment by hibooboo2** [comment]
Now @vincent99

**Comment by tfiduccia** [comment]
Version - master 1/29
Verified fixed
