### ISSUE TITLE
[EKS] Selecting security groups should be optional when selecting custom VPC

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#30083]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Create a new EKS cluster
2. Select a custom VPC

**Result:**
User is required to select one or more security groups. This should be optional and the user should be able to proceed without security groups.

Related backend issue:
https://github.com/rancher/rancher/issues/29826

**Comment by aaronRancher** [comment]
The enhancement is verified with Rancher server `rancher\rancher:master-head` `version a549b47` and `rancher\rancher:v2.5-head` `version 9ee39b9`

User is not required to choose security groups after selecting a custom VPC:
![Screen Shot 2020-11-30 at 12 17 38 PM](https://user-images.githubusercontent.com/57409052/100659246-95750e00-330d-11eb-8372-a96eec06ddf4.png)
![Screen Shot 2020-11-30 at 12 19 49 PM](https://user-images.githubusercontent.com/57409052/100659250-96a63b00-330d-11eb-935e-9debd914adc6.png)
