### ISSUE TITLE
'https://git.rancher.io/helm3-charts/': The requested URL returned error: 503 

### ISSUE THREAD

**Issue by ohauer** [rancher/rancher#30084]
Not sure if this is the right way to report.

I've checked on two rancher system (different locations) both show 
'https://git.rancher.io/${any}-charts/': The requested URL returned error: 503 

Rancher versions in use:
 2.4.10 and 2.5.2

**Comment by KaulSe** [comment]
seems to be fixed now 👍

**Comment by superseb** [comment]
This should be resolved by now

**Comment by AppleCidder** [comment]
please reopen it appears to be down again.
