### ISSUE TITLE
Rancher cluster exporter page check pod  detailed information 404 error 

### ISSUE THREAD

**Issue by qiang93** [rancher/rancher#30086]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**
using owner　permissions　member　create a deployment application,in cluster exporter page check pod detailed information

**Result:**
![image](https://user-images.githubusercontent.com/26239197/99211911-769e5400-2804-11eb-9f1b-e0bbd45803ae.png)

![image](https://user-images.githubusercontent.com/26239197/99211684-d6e0c600-2803-11eb-8d6c-12d28ce53096.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.2
- Installation option (single install/HA): 3 node HA mode

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): v1.17.9

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by maggieliu** [comment]
@qiang93 can you please clarify which owner role are you referring to (Cluster owner, Project Owner, custom role?).  Also can you list out the detailed steps on how the pod is created what permission the user has.

**Comment by qiang93** [comment]
> @qiang93 can you please clarify which owner role are you referring to (Cluster owner, Project Owner, custom role?). Also can you list out the detailed steps on how the pod is created what permission the user has.

authorized user using (Project Owner) role
