### ISSUE TITLE
v2.5.2 continuous delivery install error

### ISSUE THREAD

**Issue by dazsco** [rancher/rancher#30085]
![1](https://user-images.githubusercontent.com/30418809/99147708-071e4c80-26be-11eb-9be9-9fc561223678.png)

**Comment by maggieliu** [comment]
@dazsco can you provide more information by fill out the issue's template? It looks like the helm operator pod has problem not specific to continuous delivery. Please provide logs if possible for the pods and rancher logs

**Comment by dazsco** [comment]
rancher logs:
`
2020/11/21 14:54:05 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-zsbx2 failed, watch closed
I1121 14:54:05.712775      30 topology_manager.go:233] [topologymanager] Topology Admit Handler
I1121 14:54:05.733601      30 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "pod-impersonation-helm-op-8b6mh-token-l4kjw" (UniqueName: "kubernetes.io/secret/dd3964ca-a63e-47eb-9587-7eb5d7d16113-pod-impersonation-helm-op-8b6mh-token-l4kjw") pod "helm-operation-dd5tv" (UID: "dd3964ca-a63e-47eb-9587-7eb5d7d16113") 
I1121 14:54:05.733666      30 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "admin-kubeconfig" (UniqueName: "kubernetes.io/configmap/dd3964ca-a63e-47eb-9587-7eb5d7d16113-admin-kubeconfig") pod "helm-operation-dd5tv" (UID: "dd3964ca-a63e-47eb-9587-7eb5d7d16113") 
I1121 14:54:05.733727      30 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "data" (UniqueName: "kubernetes.io/secret/dd3964ca-a63e-47eb-9587-7eb5d7d16113-data") pod "helm-operation-dd5tv" (UID: "dd3964ca-a63e-47eb-9587-7eb5d7d16113") 
I1121 14:54:05.733794      30 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "user-kubeconfig" (UniqueName: "kubernetes.io/configmap/dd3964ca-a63e-47eb-9587-7eb5d7d16113-user-kubeconfig") pod "helm-operation-dd5tv" (UID: "dd3964ca-a63e-47eb-9587-7eb5d7d16113") 
E1121 14:54:08.112886      30 remote_runtime.go:128] StopPodSandbox "22b37f324bca9208717a966989e334c1575f5574bfc72546741bbe689b61b95e" from runtime service failed: rpc error: code = Unknown desc = failed to destroy network for sandbox "22b37f324bca9208717a966989e334c1575f5574bfc72546741bbe689b61b95e": unknown FS magic on "/var/run/netns/cni-1d8a2904-9a46-fd8a-9faa-a56a00210068": 794c7630
E1121 14:54:08.113002      30 kuberuntime_manager.go:895] Failed to stop sandbox {"containerd" "22b37f324bca9208717a966989e334c1575f5574bfc72546741bbe689b61b95e"}
E1121 14:54:08.113107      30 kubelet.go:1576] error killing pod: failed to "KillPodSandbox" for "eb25ae9c-df46-436d-984f-35bf8fdc561a" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"22b37f324bca9208717a966989e334c1575f5574bfc72546741bbe689b61b95e\": unknown FS magic on \"/var/run/netns/cni-1d8a2904-9a46-fd8a-9faa-a56a00210068\": 794c7630"
E1121 14:54:08.113144      30 pod_workers.go:191] Error syncing pod eb25ae9c-df46-436d-984f-35bf8fdc561a ("helm-operation-v5p7m_cattle-system(eb25ae9c-df46-436d-984f-35bf8fdc561a)"), skipping: error killing pod: failed to "KillPodSandbox" for "eb25ae9c-df46-436d-984f-35bf8fdc561a" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"22b37f324bca9208717a966989e334c1575f5574bfc72546741bbe689b61b95e\": unknown FS magic on \"/var/run/netns/cni-1d8a2904-9a46-fd8a-9faa-a56a00210068\": 794c7630"
W1121 14:54:09.040902      30 pod_container_deletor.go:77] Container "22b37f324bca9208717a966989e334c1575f5574bfc72546741bbe689b61b95e" not found in pod's containers
W1121 14:54:09.659502       8 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
I1121 14:54:09.855838      30 reconciler.go:196] operationExecutor.UnmountVolume started for volume "pod-impersonation-helm-op-dr4p4-token-wjrvk" (UniqueName: "kubernetes.io/secret/eb25ae9c-df46-436d-984f-35bf8fdc561a-pod-impersonation-helm-op-dr4p4-token-wjrvk") pod "eb25ae9c-df46-436d-984f-35bf8fdc561a" (UID: "eb25ae9c-df46-436d-984f-35bf8fdc561a") 
I1121 14:54:09.856011      30 reconciler.go:196] operationExecutor.UnmountVolume started for volume "data" (UniqueName: "kubernetes.io/secret/eb25ae9c-df46-436d-984f-35bf8fdc561a-data") pod "eb25ae9c-df46-436d-984f-35bf8fdc561a" (UID: "eb25ae9c-df46-436d-984f-35bf8fdc561a") 
I1121 14:54:09.856083      30 reconciler.go:196] operationExecutor.UnmountVolume started for volume "admin-kubeconfig" (UniqueName: "kubernetes.io/configmap/eb25ae9c-df46-436d-984f-35bf8fdc561a-admin-kubeconfig") pod "eb25ae9c-df46-436d-984f-35bf8fdc561a" (UID: "eb25ae9c-df46-436d-984f-35bf8fdc561a") 
I1121 14:54:09.856125      30 reconciler.go:196] operationExecutor.UnmountVolume started for volume "user-kubeconfig" (UniqueName: "kubernetes.io/configmap/eb25ae9c-df46-436d-984f-35bf8fdc561a-user-kubeconfig") pod "eb25ae9c-df46-436d-984f-35bf8fdc561a" (UID: "eb25ae9c-df46-436d-984f-35bf8fdc561a") 
I1121 14:54:09.863452      30 operation_generator.go:782] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/eb25ae9c-df46-436d-984f-35bf8fdc561a-data" (OuterVolumeSpecName: "data") pod "eb25ae9c-df46-436d-984f-35bf8fdc561a" (UID: "eb25ae9c-df46-436d-984f-35bf8fdc561a"). InnerVolumeSpecName "data". PluginName "kubernetes.io/secret", VolumeGidValue ""
I1121 14:54:09.864413      30 operation_generator.go:782] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/eb25ae9c-df46-436d-984f-35bf8fdc561a-pod-impersonation-helm-op-dr4p4-token-wjrvk" (OuterVolumeSpecName: "pod-impersonation-helm-op-dr4p4-token-wjrvk") pod "eb25ae9c-df46-436d-984f-35bf8fdc561a" (UID: "eb25ae9c-df46-436d-984f-35bf8fdc561a"). InnerVolumeSpecName "pod-impersonation-helm-op-dr4p4-token-wjrvk". PluginName "kubernetes.io/secret", VolumeGidValue ""
W1121 14:54:09.871143      30 empty_dir.go:453] Warning: Failed to clear quota on /var/lib/kubelet/pods/eb25ae9c-df46-436d-984f-35bf8fdc561a/volumes/kubernetes.io~configmap/user-kubeconfig: ClearQuota called, but quotas disabled
I1121 14:54:09.871660      30 operation_generator.go:782] UnmountVolume.TearDown succeeded for volume "kubernetes.io/configmap/eb25ae9c-df46-436d-984f-35bf8fdc561a-user-kubeconfig" (OuterVolumeSpecName: "user-kubeconfig") pod "eb25ae9c-df46-436d-984f-35bf8fdc561a" (UID: "eb25ae9c-df46-436d-984f-35bf8fdc561a"). InnerVolumeSpecName "user-kubeconfig". PluginName "kubernetes.io/configmap", VolumeGidValue ""
W1121 14:54:09.873071      30 empty_dir.go:453] Warning: Failed to clear quota on /var/lib/kubelet/pods/eb25ae9c-df46-436d-984f-35bf8fdc561a/volumes/kubernetes.io~configmap/admin-kubeconfig: ClearQuota called, but quotas disabled
I1121 14:54:09.873584      30 operation_generator.go:782] UnmountVolume.TearDown succeeded for volume "kubernetes.io/configmap/eb25ae9c-df46-436d-984f-35bf8fdc561a-admin-kubeconfig" (OuterVolumeSpecName: "admin-kubeconfig") pod "eb25ae9c-df46-436d-984f-35bf8fdc561a" (UID: "eb25ae9c-df46-436d-984f-35bf8fdc561a"). InnerVolumeSpecName "admin-kubeconfig". PluginName "kubernetes.io/configmap", VolumeGidValue ""
I1121 14:54:09.956703      30 reconciler.go:319] Volume detached for volume "pod-impersonation-helm-op-dr4p4-token-wjrvk" (UniqueName: "kubernetes.io/secret/eb25ae9c-df46-436d-984f-35bf8fdc561a-pod-impersonation-helm-op-dr4p4-token-wjrvk") on node "local-node" DevicePath ""
I1121 14:54:09.956754      30 reconciler.go:319] Volume detached for volume "data" (UniqueName: "kubernetes.io/secret/eb25ae9c-df46-436d-984f-35bf8fdc561a-data") on node "local-node" DevicePath ""
I1121 14:54:09.956776      30 reconciler.go:319] Volume detached for volume "user-kubeconfig" (UniqueName: "kubernetes.io/configmap/eb25ae9c-df46-436d-984f-35bf8fdc561a-user-kubeconfig") on node "local-node" DevicePath ""
I1121 14:54:09.956795      30 reconciler.go:319] Volume detached for volume "admin-kubeconfig" (UniqueName: "kubernetes.io/configmap/eb25ae9c-df46-436d-984f-35bf8fdc561a-admin-kubeconfig") on node "local-node" DevicePath ""

`

**Comment by dazsco** [comment]
@maggieliu I think it is because the docker hub proxy is not enabled and the request for the official docker image timed out. Can I set up the docker hub in rancher?
