### ISSUE TITLE
[2.4] Ingress issue with PNI

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30089]
Backport for the following issues:
https://github.com/rancher/rancher/issues/30045
https://github.com/rancher/rancher/issues/30055
https://github.com/rancher/rancher/issues/30044

**Comment by sowmyav27** [comment]
**On 2.4-head commit id: `6a09f523f`**

[This](https://github.com/rancher/rancher/issues/30055) issue is NOT seen.
[This](https://github.com/rancher/rancher/issues/30044) issue is seen fixed.

### **Fresh Install use case - On 2.4-head - commit id: `6a09f523f`**

- Create cluster with Project Network Isolation Enabled 1 etcd/control and 2 worker nodes.
- Pods of `nginx-ingress-controller` in system project do not have podName labels.
- In Debug mode, redeploy `nginx-ingress-controller` and confirm the pods don't get updated without cause. `podHandler: addLabelIfHostPortsPresent: deleting podNameFieldLabel` is NOT seen in logs.
- Deploy user ingress, verified the status.LoadBalancer shows IPs of all the worker nodes - 2 worker nodes.
```
status:
  loadBalancer:
    ingress:
    - ip: <ip-1>
    - ip: <ip-2>
```
### Upgrade from 2.4.8 to 2.4-head
On 2.4.8
- Deploy a cluster - 2 worker nodes, 1 etcd/control plane node
- Deploy a workload and an ingress pointing to the workload.
- User ingress has only one worker node's ip address in status.LoadBalancer
```
status:
  loadBalancer:
    ingress:
    - ip: <wk01>
```
- Create network policies using [doc](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource)
- Upgrade rancher to 2.4-head
- User ingress in Initializing state. And does not recover
- User ingress has no worker nodes' ip address in status.LoadBalancer
```
status:
  loadBalancer: {}
```
- podHandler: addLabelIfHostPortsPresent: deleting podNameFieldLabel --> is seen in the logs 
```
2020/11/19 02:57:49 [DEBUG] podHandler: addLabelIfHostPortsPresent: deleting podNameFieldLabel map[app:ingress-nginx controller-revision-hash:7649c75c8c field.cattle.io/podName:nginx-ingress-controller-p79hj pod-template-generation:1] in ingress-nginx
```
- pods of nginx-ingress-controller in system project don't have podName labels
- Redeploy `nginx-ingress-controller`. Wait for the workload and pods to come to Active
- User ingress is seen in `Active` state.
- pods of nginx-ingress-controller in system project don't have podName labels
- User ingress has both the worker nodes' ip address in status.LoadBalancer
```
status:
  loadBalancer:
    ingress:
    - ip: <wk01>
    - ip: <wk02>
```
- User created network policies do not get deleted
- Kubelet logs on the worker node do not show repeated Sync Loop updates/messages

### Upgrade from 2.4.8 to 2.4-head - Scenario#2
On 2.4.8
- Deploy a cluster - 2 worker nodes, 1 etcd/control plane node
- Deploy a workload and an ingress pointing to the workload.
- User ingress has only one worker node's ip address in status.LoadBalancer
```
status:
  loadBalancer:
    ingress:
    - ip: <wk01>
```
- Create network policies using [doc](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource)
- Upgrade rancher to 2.4.10
- Bug is reproduced
- Upgrade rancher to 2.4-head - commit id: `6a09f523f`
- User ingress in Initializing state. And does not recover
- User ingress has no worker nodes' ip address in status.LoadBalancer
```
status:
  loadBalancer: {}
```
- pods of nginx-ingress-controller in system project don't have podName labels
- Redeploy `nginx-ingress-controller`. - by deleting the pods of ingress controller. Wait for the workload and pods to come to Active
- User ingress is seen in `Active` state.
- pods of nginx-ingress-controller in system project don't have podName labels
- User ingress has both the worker nodes' ip address in status.LoadBalancer
```
status:
  loadBalancer:
    ingress:
    - ip: <wk01>
    - ip: <wk02>
```
- User created network policies do not get deleted
- Kubelet logs on the worker node do not show repeated Sync Loop updates/messages
- Delete pods of the ds ingress controller manually and wait for the new pod to be running, then delete the next pod. This doesn't result into user ingresses go to Initializing state.
