### ISSUE TITLE
[2.4] When alerts only configured notifiers that are not webhook forwarded, rancher server returns secrets "Webhook -receiver" not found error

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30088]
backport for https://github.com/rancher/rancher/issues/28954

**Comment by izaac** [comment]
Rancher version: `v2.4-head (11/16/2020)` _36358bd29_ 

I don't see the webhook errors in the Rancher server logs. Alerts are getting sent to the slack notifier.
