### ISSUE TITLE
Add ability to use scale sets with AKS clusters

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#30096]
Right now, Rancher leverages Availablity Sets when creating AKS clusters. The limitation here is that we cannot change node sizes after the fact and creating a new cluster is necessary to do that.

Using Scale Sets for the node pool seems to be a much more flexible method in this regard as it allows us to leverage multiple node pools and multiple node sizes.

gz#13366

**Comment by MCKLMT** [comment]
Any news?

**Comment by Confusingboat** [comment]
+1 for this feature

**Comment by prabalsharma** [comment]
Autoscaling for NPs has been implemented in AKSv2
<img width="1292" alt="Screen Shot 2021-07-13 at 3 54 08 PM" src="https://user-images.githubusercontent.com/3749546/125535422-509bc8d4-11a7-496a-b33e-34b454592383.png">

Please let me know if "Scale Set" does not mean Autoscaling.

**Comment by prabalsharma** [comment]
"Enable virtual machine scale sets" is enabled by default on AKSv2
