### ISSUE TITLE
[cli] Configure kubernetes token cache dir

### ISSUE THREAD

**Issue by tjcain** [rancher/rancher#30092]
It is currently not possible to configure the location of cached kubernetes tokens generated by the cli command `token`. A fix was attempted as part of https://github.com/rancher/rancher/issues/29807, but this had to be rolled back. 

@dramich [pointed out](https://github.com/rancher/rancher/issues/29807#issuecomment-726233399) that the token should be a new field on `ServerConfig` and a new `RANCHER_CONFIG_DIR` env var added. I have submitted https://github.com/rancher/cli/pull/291 to address these changes.

This would result in the token being stored along with the rest of the rancher cli config in the `~/.rancher/` directory by default.

**Comment by dramich** [comment]
PR: https://github.com/rancher/cli/pull/291
Available in `v2.4.10-rc1`

**Comment by bmdepesa** [comment]
Reproduced in rancher/cli:v2.4.9

* Create a cluster
* Set `/v3/settings/kubeconfig-generate-token` to false in the UI
* Download the `kubeconfig` for the cluster (it should contain a script for getting the token from the CLI command)
* From some directory, execute `kubectl get pods`
  * User is prompted for authentication
* Change directory and run again
  * User is again prompted for authentication
---
With rancher/cli:v2.4.10-rc2:
* Set `export RANCHER_CONFIG_DIR=/somedir/ranchercliconfig`
* From some directory, execute `kubectl get pods`
  * User is prompted for authentication
  * Auth is saved: `INFO[0005] Saving config to /somedir/ranchercliconfig/cli2.json`
* Change directory and run again
* Cached token is used
