### ISSUE TITLE
[CLI] Compatible with Apps and Marketplace

### ISSUE THREAD

**Issue by toddexp** [rancher/rancher#30095]
The rancher-cli is not currently compatible with the new apps and marketplace charts in Rancher 2.5. The rancher-cli is helpful with automation and not having this feature in the cli is an impediment. The rancher-cli is helpful with automation because it has auth into the clusters. Using the helm cli would require having a kubeconfig file which at new cluster creation with automation is not setup. Rancher also stores the helm repositories rather than the repositories having to be stored locally. This makes the automation tools more repeatable for users.

**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
`rancher app install rancher-monitoring rancher-monitoring`

**Result:**
This deploys rancher-monitoring from the 2.4 apps catalog. There is no way to deploy the one from the 2.5 apps and marketplace.

**Other details that may be helpful:**
Any other commands from `rancher apps` is only interacting with the 2.4 catalogs. Commands like `rancher apps ls` or `rancher apps lt` only shows the apps and repositories from 2.4 and not what is in from 2.5. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.1
- Installation option (single install/HA): HA
- Rancher cli: 2.4.7

**Comment by Daniel-Vaz** [comment]
I there any workaround for this issue ?

**Comment by hari-narayanan94** [comment]
I am also looking for a solution for the above stated probelm . On the other hand I was not able to get it to work even via helm ,  for some reason iam not able to add the helm chart repo of racher . @toddexp can you please let me know how we can get rancher apps to install atleast via helm ,  i am not able to grab the rancher charts even via helm

**Comment by toddexp** [comment]
Hi @hari-narayanan94. I am another community member like yourself. I am not sure of workaround. I have not yet tried to use the regular helm cli. I may try this soon. If I make any progress with that I will be sure to share.

**Comment by hari-narayanan94** [comment]
@loganhz Can you please guide if there is any way we could install charts from apps and marketplace into a cluster via rancher  programmatically via API or helm or any means ?? Iam looking to install rancher-istio and rancher-monitoring

**Comment by toddexp** [comment]
I was able to find a work around with the helm cli. I would still prefer the rancher cli for the reasons listed when opening this issue.

I assume you are also trying to do automation from your comments, so this was all the steps I needed. The kubeconfig steps may be able to be omitted depending on your use case.
```
# create temporary kubeconfig file to be used later with helm
rancher cluster kubeconfig {CLUSTER_ID} > {/path/to/temp/kubeconfig}

# add rancher repo to helm
helm repo add {REPO_NAME} http://charts.rancher.io/

# install helm chart using temporary kubeconfig file
# used rancher-monitoring as an example since that was the one used in the initial example
helm upgrade --kubeconfig={/path/to/temp/kubeconfig} --install=true --namespace=cattle-monitoring-system --wait=true rancher-monitoring-crd {REPO_NAME}/rancher-monitoring-crd
helm upgrade --kubeconfig={/path/to/temp/kubeconfig} --install=true --namespace=cattle-monitoring-system --wait=true rancher-monitoring {REPO_NAME}/rancher-monitoring
```

Additionally [Terraform](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/app_v2) should be able to deploy the new apps and market place charts as well. I have not personally tested this, however.

**Comment by hari-narayanan94** [comment]
I was also find out a way to trigger this via Rancher API using this endpoint 

{rancher-url}/k8s/clusters/{rancher-clusterid}/v1/catalog.cattle.io.clusterrepos/rancher-charts?action=install

**Comment by fabiorauber** [comment]
Still relevant.

**Comment by sneumann** [comment]
At least should be documented more visibly. There is some notion of the difference in https://rancher.com/docs/rancher/v2.6/en/helm-charts/, but nothing mentions how to do that on the command line. Yours, Steffen

**Comment by yagyaomnius** [comment]
This is  blocking  operations via cli, can someone please look into this ?

**Comment by nandlalushir** [comment]
This issue is still relevant
