### ISSUE TITLE
Porting Ember API (Adding validations into Webhook)

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30098]
Place holder ticket to the work needed on porting over Ember API. Start with cluster provisioning related validations:

Cluster Provisioning - Node Pools
Node Templates
Cloud Credentials
Cluster Templates
Dynamic UI for Node drivers/cluster drivers
Cluster Provisioning - Imported
Cluster Provisioning - Custom
Cluster Provisioning - Hosted (EKS until AKS/GKE is ready)

**Comment by deniseschannon** [comment]
I don't think this is a valid request anymore based on how we've decided to move forward with cluster provisioning.
