### ISSUE TITLE
Why not allow remember password

### ISSUE THREAD

**Issue by Widerstehen** [rancher/rancher#30104]
I use chrome browser，it can remember username but can not remember password when i login rancher.

**Comment by vincent99** [comment]
You can do that with a password manager or the tools built into all the major browsers.  Rancher installs commonly give people the equivalent of root access to fleets of powerful nodes or to sensitive data within them; leaving it logged in all the time is not a great idea for many people.

If you really want it anyway, there's a setting for how long ui sessions are good for that you can set to a as long as you want

**Comment by Widerstehen** [comment]
Thank you for your quick reply.
