### ISSUE TITLE
Deployments - Edit as Form - imagePullSecrets not available

### ISSUE THREAD

**Issue by tinohager** [rancher/rancher#30107]
**What kind of request is this (question/bug/enhancement/feature request):**
question/feature request

I can't find a select option for `imagePullSecrets` in the edit form of deployments.
Is the functionality not yet integrated or should a different configuration be used here?
Without `imagePullSecrets` I get an access error on image pull.

![image](https://user-images.githubusercontent.com/8215186/99381758-cb58d200-28cb-11eb-924c-a98fc2ea0b02.png)

I have add my own Registry here:
![image](https://user-images.githubusercontent.com/8215186/99382003-28ed1e80-28cc-11eb-9e21-9f920f48f4f5.png)

**Cluster information**
v2.5.2

**Comment by sowmyav27** [comment]
Related issue in dashboard - https://github.com/rancher/dashboard/issues/1811
