### ISSUE TITLE
Windows worker registration command is not available

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30111]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a custom cluster on `2.5-head`
- Windows enabled - VXLAN/HostGW. Click on Next --> go to registration command page
- Click on Windows, windows registration command is not displayed

<img width="1326" alt="Screen Shot 2020-11-17 at 10 00 46 AM" src="https://user-images.githubusercontent.com/26032343/99406667-297db900-28bc-11eb-9ea2-891dac9bfd8d.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `71da15`
- Installation option (single install/HA): single node

**Cluster information**

- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Windows custom

**Comment by sadiapoddar** [comment]
repro with the latest 2.5.-head,  commit 145984
1. select add cluster as the custom cluster
2. select the network type as "Flannel" and enable window support
3. go to the registration page for the exact command and select os as window
There are two issues.
1. For the window the node roles "etcd" and "control plane" were selectable and should be grayed out in case of win os. 
2. The command it generated is not PowerShell command
<img width="1086" alt="Screen Shot 2020-11-23 at 4 30 46 PM" src="https://user-images.githubusercontent.com/72409237/100030964-77f1f280-2da9-11eb-94b3-0b99c302ca1a.png">

**Comment by sadiapoddar** [comment]
Verified the fix 2.5-head 9ee39b9, and mater-head, a549b47.
steps.

1. select add cluster as the custom cluster
2. select the network type as "Flannel" and enable window support
3. go to the registration page for the exact command and select os as window
4. Now when the user selects the window, the Powershell command list for worker
5. Created a  custom cluster and registered the worker VM using the command listed in step 4.
<img width="773" alt="Screen Shot 2020-11-30 at 5 35 59 PM" src="https://user-images.githubusercontent.com/72409237/100686390-109ceb00-3333-11eb-8a3a-b321ec80d675.png">

**Comment by sadiapoddar** [comment]
The issue is fixed.
