### ISSUE TITLE
CIS v2/rancher-cis-benchmark: 1.0.300

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#30123]
This is the ticket to track the chart changes coming in for CIS v2 in release 2.5.4:

repo: https://github.com/rancher/charts/blob/dev-v2.5-source/

Changes scoped:

- [x] - CIS v2 scheduling, alerting and custom benchmarks
- [x] - CIS 1.6
- [x] - rke2 benchmark support

cc @mrajashree @briandowns

**Comment by briandowns** [comment]
This PR adds RKE2 support. https://github.com/rancher/charts/pull/815

**Comment by mrajashree** [comment]
This PR adds changes for CIS 1.6 profile and some report generation changes https://github.com/rancher/charts/pull/863

**Comment by sowmyav27** [comment]
**Verified on 2.5-head latest using `rancher-cis-benchmark: 1.0.300` version**

- Alerting, Scheduled scan, Custom benchmark versions, CIS 1.5 updates and CIS 1.6. 
- All issues related are being tracked separately.

**Comment by rancher-max** [comment]
Validated functional for rke2 as part of https://github.com/rancher/cis-operator/issues/59#issuecomment-740425928.

Leaving that issue open for a final review regarding potential issues with the rke2 profiles, but as far as the cisv2 operator working for rke2, this has been validated as working.
