### ISSUE TITLE
If a service has non-string metadata, convoy-gluster wont work.

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3012]
When deploying convoy-gluster, if **any** service in the environment has a metadata entry with a map as the value like:
```
{
  "elasticsearch": {
    "yml": {
      "cluster.name": "es",
      "node.data": "false",
      "node.master": "true",
      "node.name": "${HOSTNAME}"
    }
  },
  "io.rancher.service.hash": "6cf9dab7d556f3abbb3646b209a98d0794723867"
}
```
you'll get an errror like this in the convoy-gluster storagepool container:
```
12/11/2015 12:16:23 PMtime="2015-12-11T19:16:23Z" level=error msg="Error while reading host info [json: cannot unmarshal object into Go value of type string]"
```

So, steps to repro would be to deplo[y the elasticsearch catalog entry and then deploy convoy-gluster. Then look at the storagepool container logs.

The convoy-glsuter stack comes up fine, but the storage pool is never registered in rancher.

**Comment by joostliketoast** [comment]
is there any workaround for now? I still have this error after removing the elasticsearch catalog entry

**Comment by cjellick** [comment]
@joostliketoast no work around. i'll try to squeeze in a fix this week though

**Comment by cjellick** [comment]
Fixed with the new release of convoy-gluster convoy-nfs

**Comment by sangeethah** [comment]
Tested with  convoy-gluster  version - v0.2.

Deployed convoy-gluster
Deployed Elastic search template.
After this deployed convoy-gluster template.
Once service is activated fully ,convoy-gluster storage pool gets created successfully.
No errors seen in the convoy-gluster storagepool container.
