### ISSUE TITLE
Cluster agents not removed on local cluster after upgrading to 2.5.2

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#30128]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy HA Rancher 2.4.8 
- Upgrade Rancher to 2.5.1

- Since agents stayed in the 2.4.8 version, manually changed the agent image to 2.5.1 to make it up to date (This action was intentional since thinking the versions should match with rancher version) 

- Upgrade v.2.5.1 to v2.5.2

**Result:**

Agents stayed with version v2.5.1

**Other details that may be helpful:**

Agents should be removed from local cluster regardless of the version of agents.
Fix on bug https://github.com/rancher/rancher/issues/29397 handles agents with version 2.4.x during v2.5.2 upgrade.

Is it ok to delete cluster and node agent workloads manually from local cluster in this scenario?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.2
- Installation option (single install/HA): HA

gz#13352

**Comment by maggieliu** [comment]
This is a won't fix. User shouldn't manually change the agent image to 2.5.1. If anyone did this, the workaround is manually delete the agents after upgrading to 2.5.2.
