### ISSUE TITLE
Upgrading Kubernetes clears nginx-configuration config map

### ISSUE THREAD

**Issue by rene-demonsters** [rancher/rancher#30127]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Go to the `System` project of any cluster that's not running the latest k8s version
2. Edit the `nginx-configuration` config map and for example set `use-forwarded-headers` to true
3. Edit the cluster and update the Kubernetes version and wait for it to finish
4. Go to the `System` project and check the `nginx-configuration` you'll see all settings have been lost.

**Result:**
After the update the entire `nginx-configuration` config map has been thrown away. I would expect it to be untouched. In our case this has caused logins to break as use-forwarded-proto was no longer being passed on to the workloads.

**Environment information**
- Rancher version: v2.4.8
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type: imported
- Kubernetes version: 1.18.10 => 1.18.12, but I've seen it on other versions too

**Comment by superseb** [comment]
This is expected, we have the option to configure nginx ingress and those will be used when provisioning is triggered. It is documented here https://rancher.com/docs/rke/latest/en/config-options/add-ons/ingress-controllers/#configuring-nginx-ingress-controller. 

If this doesn't work, let me know.

**Comment by Napsty** [comment]
@superseb Sorry to comment on an already closed issue, but the RKE `ingress:` settings only work for the "local" cluster, not for downstream clusters. Upgrading Kubernetes in a downstream cluster still removes the config map of the nginx-configuration. I think that is also the problem described by @rene-demonsters. 

> Edit the cluster and update the Kubernetes version and wait for it to finish

Sounds more like edit cluster in UI than in RKE YAML.

I can confirm that this issue is still happening, when upgrading Kubernetes of a downstream cluster. Confirmed with Rancher 2.5.10.

**Comment by superseb** [comment]
The functionality of RKE remains the same, the configmap is under RKE's control and is configured according to what is configured in the YAML. If you make changes outside of RKE, those will not be persisted if RKE updates the configuration according to the YAML. If this is not what you are seeing, please create a new issue with exact steps to reproduce so we can take a look.

**Comment by Napsty** [comment]
Thx @superseb for the quick answer.

Just to be sure I understand:

>The functionality of RKE remains the same, the configmap is under RKE's control and is configured according to what is configured in the YAML.

This means the RKE cluster yaml also applies to downstream clusters? Or did you mean something else?

**Comment by superseb** [comment]
Each cluster has it's own definition, there is no shared configuration here. If the `local` cluster is created by RKE, it's configuration is determined by the `cluster.yml` (or `rancher-cluster.yml`) and provisioned using `rke up`.

For clusters created using Rancher, it is specified for that cluster as shown on https://rancher.com/docs/rancher/v2.5/en/cluster-admin/editing-clusters/rke-config-reference/#editing-clusters-with-yaml

**Comment by Napsty** [comment]
> For clusters created using Rancher, it is specified for that cluster as shown on https://rancher.com/docs/rancher/v2.5/en/cluster-admin/editing-clusters/rke-config-reference/#editing-clusters-with-yaml

awesome, that was the missing info I needed. thanks!

**Comment by Napsty** [comment]
@superseb I actually just had a case this week where Rancher was updated from 2.5.8 to 2.5.12 and Kubernetes updated to 1.20.15 and the Ingress Config Map disappeared after the update. Even though it was defined in the cluster.yml:

```
  ingress:
    default_backend: false
    http_port: 0
    https_port: 0
    options:
      proxy-body-size: 200m
    provider: nginx
```

**Comment by superseb** [comment]
I think you are hitting https://github.com/rancher/rke/issues/2834 / https://github.com/rancher/rancher/issues/36484

**Comment by Napsty** [comment]
Yep, sounds like. Thanks for the link!
