### ISSUE TITLE
[Monitoring V2] rancher-monitoring: 9.4.202

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#30137]
#### Rancher Release

2.5.4

#### Repo

`rancher/charts`

#### Changes

Display name should be `Monitoring` https://github.com/rancher/charts/commit/11431d72985f7d312ec739ea4f822c20b7b89258#diff-93c5f8e80a04a2a5141b2c41f8f760a87649f1cd8a9b0112598103988b4f1317

`app-README.md` should be updated https://github.com/rancher/charts/commit/cdd938c8816e4f9830d0ffa17fb8801f1f2eeb24#diff-93c5f8e80a04a2a5141b2c41f8f760a87649f1cd8a9b0112598103988b4f1317

Added a PSP for the Alertmanager Config Secret pre-install Job + Service Account patch pre-install job. We should make sure the PSP gets created for both.

Updated a subchart (packaged as separate chart in `rancher/charts`) that is used by `rancher-monitoring` when deploying PushProx proxies onto RKE, RKE2, KubeAdm, and k3s clusters called `rancher/pushprox` (new version 0.1.2).
- Adds in a PSP for PushProx proxies. We should make sure the PSP gets created.

Updated Prometheus Adapter version to 2.7.1. We should make sure the image exists / can be pulled in for private registries and that any custom metrics specified in the Prometheus Adapter secret are emitted as expected to the k8s Custom / Resource Metrics API.

Updated the Helm repository for dependencies to remove the deprecated `kubernetes-charts.storage.googleapis.com` for https://github.com/rancher/rancher/issues/30063. This does not need any testing as it can be verified by just looking at the [`requirements.yaml`](https://github.com/rancher/charts/blob/022a19fedb3fd3251aaea4f94b87af0d56a1786e/charts/rancher-monitoring/requirements.yaml#L2-L18) of the generated chart.

With these fixes, the Rancher Monitoring chart should also work for hardened RKE clusters where there is no default PSP for the namespace (e.g. default project is not selected, as shown in https://github.com/rancher/rancher/issues/29980)

**Comment by jiaqiluo** [comment]
(This is not the final list, will keep it updated)
Checklist for closing this issue:
- [x] the name of the installed app is `monitoring`
![image](https://user-images.githubusercontent.com/6218999/101703074-62cec200-3a3f-11eb-82c9-c8e3a7bd53c8.png)
- [x] the app's README is updated to this version https://github.com/rancher/charts/commit/cdd938c8816e4f9830d0ffa17fb8801f1f2eeb24#diff-e70629698a0ad2d0af6ea6ea1ff058280e710483b23a0a4b725043976968b3da
![image](https://user-images.githubusercontent.com/6218999/101703122-77ab5580-3a3f-11eb-9a26-1c673571b9ba.png)
- [ ] When installing monitoring in the cluster with PSP enabled, PSP should be created for `Alertmanager Config Secret pre-install Job`, `Service Account patch pre-install job`, and `pushprox` 
- [ ] `Pushprox 0.1.2` should be used 
- [ ] `Prometheus Adapter 2.7.1` should be used and any custom metrics specified in the Prometheus Adapter secret are emitted as expected to the k8s Custom / Resource Metrics API
- [x] remove the deprecated `kubernetes-charts.storage.googleapis.com` repo https://github.com/rancher/rancher/issues/30063
- [x] Monitoring should work for hardened RKE clusters where there is no default PSP for the namespace (e.g. default project is not selected, as shown in #29980)

**Comment by adampl** [comment]
I remember having an issue with Notifiers - after being created, my notifier wasn't visible in the UI, it could only be edited directly in the secret.

**Comment by jiaqiluo** [comment]
hi @adampl thank you for the feedback. I did not notice the issue on my setup. Please log a new bug if you see it happens again.

**Comment by aiyengar2** [comment]
@adampl did you initially configure the Receivers via providing an Alertmanager Config Secret? If you did, it's possible our UI just doesn't natively support rendering a configuration you have within it, which is why you needed to directly edit the secret. More information on the constraints / expectations can be found in https://github.com/rancher/dashboard/issues/1239

**Comment by adampl** [comment]
@aiyengar2 No, I've created it in the Notifiers page. Now I can't check again, because I reverted back to Monitoring V1. There were also other config issues/limitations which scared me away, but now I don't remember exactly what they were about.
