### ISSUE TITLE
Install Market place apps in Rancher VIA Rest API

### ISSUE THREAD

**Issue by hari-narayanan94** [rancher/rancher#30130]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
Im trying to automate End to End AKS cluster Provisioning , I was able to find Rest API commands to authenticate with Rancher and Import the cluster . Iam trying to install new istio from the Rancher Apps and Market place via API (Not the one from Cluster manager) , is there some way to programmatically do that ? 

I tried to directly run Helm commands (helm install rancher-istio . --create-namespace -n istio-system) , but even that dosent seem to work , as iam not able to download the Helm chart , it looks like rancher-istio helm chart is not available publicly

**Comment by hari-narayanan94** [comment]
I was able to find out a way to do this via this endpoint :) <rancherURL>/k8s/clusters/<clusterid>/v1/catalog.cattle.io.clusterrepos/rancher-charts?action=install

**Comment by gsel** [comment]
@hari-narayanan94 Hi, can you please share one exact API Call example

**Comment by DanSibbernsen** [comment]
> @hari-narayanan94 Hi, can you please share one exact API Call example

@justcloudnative I was in the same boat, figured it out through other searches. It was a bit more of a pain in the butt than I expected, so I'll describe it here :)

You can see the endpoint if you navigate to `{rancherURL}/k8s/clusters/{clusterid}/v1/catalog.cattle.io.clusterrepos/rancher-charts` you'll see the "install" action. From there, you've got your basic endpoint fill-ins.

You supply the body of the POST as the fill-ins for those charts. I was installing rancher-monitoring, so I required 2 charts to be installed, rancher-monitoring-crd and rancher-monitoring. To get the specifics of those charts, just go to the "Apps & Marketplace" part of the Rancher cluster and select "edit as YAML." I believe you only need to supply the fields that you want to override, everything else will remain the default of what's in the rancher-charts yaml. 

Here's an example:

```
{
	"charts": [
		{
			"chartName": "rancher-monitoring-crd",
			"releaseName": "rancher-monitoring-crd",
			"version": "16.6.0"
		},
		{
			"chartName": "rancher-monitoring",
			"releaseName": "rancher-monitoring",
			"version": "16.6.0",
			"values": {
				"alertmanager": {
					"alertmanagerSpec": {
						"podAntiAffinity": "hard",
						"replicas": "2",
					}
				},
				"prometheus": {
					"prometheusSpec": {
						"podAntiAffinity": "hard",
						"replicas": "2",
					}
				}
			}
		}
	],
	"disableOpenAPIValidation": false,
	"namespace": "cattle-monitoring-system",
	"noHooks": false,
	"projectId": "",
	"timeout": null,
	"wait": false
}
```

I wish the documentation was a bit clearer from the API perspective. I wasn't even aware of the `{rancherURL}/k8s/clusters` way to access the REST API, previously I only knew about the `{rancherURL}/v3/clusters`

**Comment by DanSibbernsen** [comment]
@justcloudnative  FYI: the fields that are not overridden by you are *not* set to the default of what's in the rancher-charts yaml. I was trying to setup Prometheus AlertManager and discovered that the `alertManager.alertmanagerSpec.templateFiles` field wasn't being populated. So you likely have to specify *all* of the fields within the POST you need. This is kind of a pain in the butt and is unlikely to make maintenance easier, so I'll likely look into deploying this as a helm chart without interacting with the API.

**Comment by jaredkipe** [comment]
@DanSibbernsen I'm essentially in the same boat you're in and coming to the same conclusions.... The Rancher UI wraps around a lot of stuff that isn't easily accomplished by just creating an `App.catalog.cattle.io/v1` kubernetes object or similar.  (in fact, don't do this because you won't be able to remove it due to it not actually getting installed)

**Comment by jjscarafia** [comment]
HI! did any of you find the way to deploy the charts on rancher 2.6 (no legacy mode)?
Any way to get the chart, pass answers and get the contento to call the "install" of the recommended endpoint?

With v3 (norman) I was doing something like this:
```

project.create_app(createData = {
   "answers": answers,
   "targetNamespace": appName,
   "externalId": catalogExternalId,
})
```
Any help appretiated

cc @vincent99  I believe we are on the same need asked here https://forums.rancher.com/t/api-view-in-rancher-2-6/36819
Thanks!

**Comment by DanSibbernsen** [comment]
Hi @jjscarafia , I did in fact find a way to install this via helm. It's not super well advertised, but here's some sample code that should suffice:

```
helm repo add rancher-charts https://charts.rancher.io
helm install --create-namespace --namespace cattle-monitoring-system rancher-monitoring-crd rancher-charts/rancher-monitoring-crd --version 16.6.0
helm install --create-namespace --namespace cattle-monitoring-system rancher-monitoring rancher-charts/rancher-monitoring --version 16.6.0 --values ./rancher-monitoring-values.yml
```

The values for it are still pretty vast, and there's a bit of a learning curve in terms of updating the alertmanager / prometheus-targets from the helm chart, but it does use the defaults.

you can see the helm values via 
```helm show values rancher-charts/rancher-monitoring --version 16.6.0```

**Comment by jjscarafia** [comment]
Hi @deniseschannon 
Thanks for the detailed answer.
Yes, as you said, we're looking to do this from python, so we're trying to use some api. If we don't find any maybe we can call from python the helm commands.

Thanks!

**Comment by jjscarafia** [comment]
Hi, just writing here again in case anyone find out **how to deploy** (and modify) **charts** on **rancher 2.6 / 2.7** (no legacy mode) **via api**?

Any way to get the chart, pass answers and get the contento to call the "install" of the recommended endpoint?

With v3 (norman) I was doing something like this:


project.create_app(createData = {
   "answers": answers,
   "targetNamespace": appName,
   "externalId": catalogExternalId,
})

Thanks!
