### ISSUE TITLE
[Monitoring V1] rancher-monitoring: v0.2.0

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#30138]
#### Rancher Release

2.5.3

#### Repo

`rancher/system-charts`

#### Changes

Upgrades Prometheus Operator to v0.39.0. Note: this is only deployable in k8s 1.16+ clusters now, so we should check that k8s 1.15 clusters are unable to view this upgrade but eligible cluster can (both imported and created).

~CRDs removed the `helm/hook: crd-install` annotation, but they should still be deployable via the `operator-init` job in a cluster that does not have those CRDs currently installed via Helm 2.~ Note: added back in in https://github.com/rancher/system-charts/pull/383 and https://github.com/rancher/system-charts/pull/382#

CRD fields were updated, exposing new stuff like `clusterAdvertiseAddress` and `disableMountSubPath`.  The apiVersion was also updated from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`. We should check that an upgrade scenario properly updates the CRDs to have these new fields and apiVersions and doesn't break any existing setups for Alerting / Monitoring.

Memory request for Prometheus Operator has been updated to 100m by default. This should be changed in upgraded setups as well.

Prometheus Operator ClusterRole now has the additional permission to get namespaces.

Two new images were created https://github.com/rancher/image-mirror/pull/49/files that should be checked.

`disableSubMountPath` should be enabled by default when Persistent Storage is selected based on https://github.com/rancher/rancher/issues/29149. We should check that this does not break any of our current PV setups with Monitoring V1 on an upgrade.

**Comment by jiaqiluo** [comment]
(Draft)

### on the fresh installation case
- [x] Prometheus Operator to v0.39.0 on k8s 1.16+ clusters
Confirmed that rancher/coreos-prometheus-operator:v0.39.0 is used. 

- [ ] The version does not show in the k8s 1.15 cluster 

- [x] CRD api version is apiextensions.k8s.io/v1
Confirmed 
```
> k get crd prometheusrules.monitoring.coreos.com -o yaml | head -1
apiVersion: apiextensions.k8s.io/v1
> k get crd prometheuses.monitoring.coreos.com -o yaml | head -1
apiVersion: apiextensions.k8s.io/v1
```

- [x] Memory request for Prometheus Operator has been updated to 100m by default. 
Confirmed that the memory request for the deployment `prometheus-operator-monitoring-operator` is 100m

- [x] Prometheus Operator ClusterRole now has the additional permission to get namespaces
Confirmed
```
> k get clusterrole prometheus-operator-monitoring-operator -o yaml
...
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
```

- [x] [two new images](https://github.com/rancher/image-mirror/pull/49/files)
Confirmed by the following two images are used 
```
- rancher/coreos-prometheus-config-reloader:v0.39.0
- rancher/coreos-prometheus-operator:v0.39.0
```

- [x] `disableSubMountPath` should be enabled by default when Persistent Storage is selected
This is tracked separately by https://github.com/rancher/rancher/issues/29149.


### upgrade Rancher from v2.5.3 to v2.5-head
after upgrading the monitoring:
- [ ] Monitoring continue working
- [ ] CRD api version is changed to `apiextensions.k8s.io/v1`
- [ ] Memory request for Prometheus Operator has been updated to 100m 
- [ ] [two new images](https://github.com/rancher/image-mirror/pull/49/files) are used

**Comment by jiaqiluo** [comment]
The general functionality of the new monitoring chart 0.2.0  is validated. 
New issues are tracked by their own issues. 

This issue can be closed.
