### ISSUE TITLE
[Logging v2] rancher-charts 3.8.001

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#30139]
## Repository

https://github.com/rancher/charts

## Changes

Status | Link | Title | Note
-- | -- | -- | --
merged | https://github.com/rancher/charts/pull/857 | Update logging chart with upstream version 3.8.0 | contains image-mirror PR
merged | https://github.com/rancher/charts/pull/851 | Add base cloud logging contents for AKS and GKE | n/a
merged | https://github.com/rancher/charts/pull/817 | Update logging chart with upstream version 3.7.3 | contains image-mirror PR
merged | https://github.com/rancher/charts/pull/813 | Add updating chart with upstream workflow | n/a

**Comment by nickgerace** [comment]
Confirmed with @paynejacob that the version is 3.8.001.

**Comment by izaac** [comment]
Rancher version: `v2.5-head (12/01/2020)`  _df2cd2d_
Rancher version: `master-head (12/01/2020)` _a549b47_

The rancher-logging version is `3.8.001`. Spot checks done as part of #28664 validation
