### ISSUE TITLE
When a service is linked to same service using multiple alias , metadata includes information about only 1 link.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3014]
Server version - v0.50.0-rc1

Steps to reproduce the problem:
Created a service test11 and created 3 service links to service -test2 using service names - "link1" ," link2" and "link3".

Metadata includes information about only 1 link:

<img width="612" alt="screen shot 2015-12-11 at 3 18 52 pm" src="https://cloud.githubusercontent.com/assets/4266958/11757999/d3f712da-a01a-11e5-81b3-8838af27d5a3.png">

**Comment by alena1108** [comment]
Not going to fix in release 1.0 as it would require building v3 for metadata. Today for service link map[] structure with key=serviceId is used, so duplicates are not supported. Have to change data type to array[serviceLink] where serviceLink is a composite object of 2 fields: serviceId, alias
