### ISSUE TITLE
Istio chart should set minimum cpu/memory request

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#30144]
The v1 istio chart has a minimum cpu and memory requirement for the cluster. V2 should do this also with chart annotations, see the helm chart reqs doc. We can use the most common istio installation as the case.

**Comment by cbron** [comment]
Parent mem/cpu issue: https://github.com/rancher/dashboard/issues/1849

**Comment by Ellenqs** [comment]
This is validated on Rancher `v2.5-head (df89971)`.
Istio version:` v1.8.100-rc01`

**Steps**
- Deploy rancher single install.
- Create a downstream cluster (1 control plane, 1 etcd, 3 worker).
- Go to cluster explorer, install monitoring, then install istio.
- Go to App & Marketplace, find rancher-istio in Installed Apps, click view YAML, check chart annotations in the file.

**Result:**
Istio is installed successfully and the cpu and memory requests are shown in annotation.

<img width="385" alt="Screen Shot 2021-02-08 at 2 41 22 PM" src="https://user-images.githubusercontent.com/75277058/107299716-e94a5480-6a2c-11eb-83a8-3157832496b9.png">

**Comment by cbron** [comment]
@Ellenqs is there a warning when you don't have enough resources ? Or is that not built yet.

**Comment by bmdepesa** [comment]
@cbron that's covered in this issue (see the linked comment): https://github.com/rancher/dashboard/issues/1849#issuecomment-730016535 which is in `Next Up`. We'll test that part of the functionality with that issue.
