### ISSUE TITLE
Rancher v2.5.2 Bug - Can't access single project tab "cluster not ready"

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#30147]
Just upgraded an existing cluster. After the upgrade everything is available, but I can't access one of the projects anymore. 

![ranchererror22](https://user-images.githubusercontent.com/1786821/99656050-bbbcc300-2a5c-11eb-8b29-e7e5971c9281.png)

**Comment by wzrdtales** [comment]
I can manually reach this project with the project url. But it never becomes active in the navigation...

**Comment by superseb** [comment]
Please share more info in https://github.com/rancher/rancher/issues/30032, upgrade from what version, what kind/version cluster, is there anything different for this project, whats the API output, whats the log from upgrading, is there anything in debug/trace logging currently that might relate to that cluster/project)
