### ISSUE TITLE
Cluster agent allowing all taints causes issue with draining

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#30156]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create an EKS cluster with a node group with 2 nodes.
2. Determine which node the cluster agent is running on.
3. Cordon that node.
4. Use kubectl to delete the cluster agent pod.

**Result:**
The pod will be rescheduled on the same, cordoned pod. This is because cordoning the node taints the node, but the cluster agent is setup to accept all taints.

**Other details that may be helpful:**
This causes a slightly larger problem when resizing the node group. If the node with the cluster agent gets deleted during a node group resize, then the cluster agent will go into a 60s delete/relaunch loop for 15 minutes. This is because EKS cordons the node and tries to reschedule the agent, but the agent gets scheduled on the same, cordoned node. This doesn't cause consistent issues, but would cause minor display problems if the user tries to change the cluster between agent deletion and restart every 60s.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
2.5.x

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Any cluster where the cluster agent is run on a worker node.

**Comment by thedadams** [comment]
Verified that https://github.com/rancher/rancher/pull/30304 fixes this issue:

1. Created a cluster with two nodes.
2. Cordoned the node the cluster agent is running on.
3. The cluster agent was successfully evicted to the other node.

**Comment by cbron** [comment]
Closing this now as this was a tech-debt issue and it has been confirmed as fixed.
