### ISSUE TITLE
when an existing catalog url is removed/renamed , all services that were launched from this catalog shows "Error Checking Upgrades" .

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3015]
Server version - V0.50.0-rc2

Steps to reproduce the problem:

Add 1 new "catalog url" from Admin->Settings tab.

Deploy few stacks from catalogs from both catalog url.

Delete one of the  "catalog url" from Admin->Settings tab.

After this , all the stacks deployed from this catalog show ""Error Checking Upgrades".

<img width="948" alt="screen shot 2015-12-11 at 4 51 57 pm" src="https://cloud.githubusercontent.com/assets/4266958/11759030/b1bb9314-a027-11e5-9305-8ba967b62966.png">

**Comment by vincent99** [comment]
What would you like it to do?  The template no longer exists so there's no upgrade info available.

**Comment by sangeethah** [comment]
Ideal scenario would be for us to not present any message at all about upgrade availability at all in such cases were we are not able to get the template info.

**Comment by vincent99** [comment]
Entire catalog removed, replaced a different one with the same name, individual template removed, the catalog service is broken, externalId manually changed, etc are all indistinguishable.. We have an externalId and got back an error asking for info about the template it corresponds to.

**Comment by vincent99** [comment]
Changed to "Template version not found" if the upgrade response is 404, to differentiate that between the catalog server being down and getting back 503/any other code.

![image](https://cloud.githubusercontent.com/assets/753917/13185905/cb3fb24c-d700-11e5-9da8-eec9e952b696.png)

**Comment by tfiduccia** [comment]
Version - master 3/2
Verified fixed
