### ISSUE TITLE
Fleet changes in 2.5.3

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#30157]
Tracking fleet and rancher-operator changes in 2.5.3

**Repo**
rancher/charts, dev-v2.5-source branch

**Changes**
Adding http proxy setting to fleet https://github.com/rancher/rancher/issues/30042
Resolving harden cluster issue https://github.com/rancher/rancher/issues/29696
Adding custom ca and insecureSkipTls https://github.com/rancher/fleet/issues/150 

**New image**
rancher/fleet:v0.3.2(-rc)
rancher/rancher-operator:v0.1.2(-rc)

**Comment by izaac** [comment]
in `rancher/fleet:v0.3.2-rc4` the git repos are stuck in `Git Updating`

We can't get the fleet cluster objects created when provisioning new Rancher clusters. 
GitRepos are stuck so we can't deploy bundles to the fleet clusters (assuming they exist)

**Comment by izaac** [comment]
Unassigning myself, the only issue left is #29696

**Comment by sangeethah** [comment]
Closing this issue.
Remaining 1 issue that is not yet validated is tracked in https://github.com/rancher/rancher/issues/29696
