### ISSUE TITLE
[2.5] Support for UAE in AKS

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30151]
Forward port for https://github.com/rancher/rancher/issues/28341

**Comment by sadiapoddar** [comment]
I installed the latest v2.5-db350a6 and master-5ebc964, I am not seeing "UAE xxx" in the region list to pick from in UI. I am seeing in the commit the new region coded is been added, however, I am not able to see those changes in UI. 

<img width="759" alt="Screen Shot 2020-12-02 at 3 05 41 PM" src="https://user-images.githubusercontent.com/72409237/100942684-a6aa5000-34b0-11eb-8813-04bfe21468ae.png">

**Comment by sadiapoddar** [comment]
Verified on master-head, commit a31eecf and 2.5-head, commit e2e530c
I am seeing inconsistent "UAE" region support between master-head and 2.5-head.
On the master-head branch, it listed two regions, 1. "UAE North" and 2. "UAE Central. but 2.5-head has only "UAE North",

<img width="422" alt="Screen Shot 2020-12-03 at 4 42 28 PM" src="https://user-images.githubusercontent.com/72409237/101110874-d7f94d80-358e-11eb-92ca-504cc2b2bd82.png">

<img width="495" alt="Screen Shot 2020-12-03 at 4 46 51 PM" src="https://user-images.githubusercontent.com/72409237/101110894-e182b580-358e-11eb-963d-b17dde64b929.png">

Reopening to fix the issue.

**Comment by westlywright** [comment]
@sadiapoddar UAE central was specifically removed from 2.5-head in [this commit](https://github.com/rancher/ui/commit/e3c5f0fb0bd558438cd747163552b82c8a9a92c0#diff-eada1f2c96e1e1231979445638c910c5241a499ec4187905df709c5071d3baa0) because it could not be verified before the release. Its still in master head and will need to be validated before the next major release. @codyrancher can you confirm this is the plan?

**Comment by codyrancher** [comment]
@westlywright that is the plan.

**Comment by sowmyav27** [comment]
Will be tracking UAE Central validation in this issue - https://github.com/rancher/rancher/issues/30278

**Comment by sadiapoddar** [comment]
Verified, 2.5-head, v2.5-ef23766
1. The UI dropdown menu in AKS cluster creation has the "UAE North" region listed as the location to pick from
2. Created an AKS cluster in "UAE North" and it looks good.
