### ISSUE TITLE
[2.5] Joining node to cluster fails on windows with docker 19.03.13

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30159]
forward port for https://github.com/rancher/rancher/issues/30148

**Comment by sowmyav27** [comment]
**Verified on 2.5-head commit id: `db350a63` and master-head - commit id: `1cb480f9`**

- Deployed windows cluster - 1 node all roles - linux and 2 windows worker node - 1903 version and docker 19.03.13 installed
- deployed workloads and ingress (work as expected)
- windows with 19.03.12 also work
