### ISSUE TITLE
Logging in through Azure Apps portal breaks Azure SSO (due to source change?)

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#30166]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Requires the use of Azure SSO and My Apps
   
1.  Check that you can log in successfully at the Rancher URL, log out, and log back in again
2.  Logout
3.  Log in through Azure My Apps portal redirection (it fails and no attempt to login again on this tab will work)
4.  If you close the tab and go to the URL directly in a new tab, it works again

**Result:**
![image](https://user-images.githubusercontent.com/8906089/101670184-c1e60400-3a4a-11eb-95a9-8697462f0345.png)

**Other details that may be helpful:**
Workaround by closing the tab and going to the Rancher URL directly in a new tab
There is a recording of the failure available

**Environment information**
- Rancher version: v2.4.8

gz#12178

**Comment by Jono-SUSE-Rancher** [comment]
@gaktive - Hey Gary, can you have someone from UI take a look at this? It’s caused because Chrome detects that items are being loaded from a different hostname. If it turns out to _not_ be a UI issue let me know.

**Comment by gaktive** [comment]
@Jono-SUSE-Rancher is this needed for 2.5.8? or what version?

**Comment by Jono-SUSE-Rancher** [comment]
@gaktive  - Hey Gary, can you just work with the team and determine if this is truly a frontend issue, and if so, what the level of effort might be on it?

**Comment by izaac** [comment]
@Tejeev I will need more details on how this integration works as our AzureAD QA app redirects to the Homepage it has in its settings.

I tried changing that Homepage URL to my rancher server URL but I wasn't logged in automatically just redirected to the login page to login with Azure AD.

**Comment by gaktive** [comment]
@izaac were there any other updates to this issue outside of Github since we last looked at this? I'm checking on Slack for additional history since I last looked at this but last I saw, this was working OK in Cluster Explorer so it's a matter of confirming that this was tested on Manager.

Let me know and I could have someone in UI verify if it wasn't already done by QA.

**Comment by izaac** [comment]
Hi @gaktive no more action was done from QA since my last comment. I tried using the "My Apps" Azure feature but we don't have this configured in our test Azure AD

**Comment by gaktive** [comment]
@izaac I'm getting asked about the status of this feature, so if QA doesn't have an Azure AD to test this, then let me know and I can see if someone in UI can verify this.

**Comment by gaktive** [comment]
cc @sowmyav27 though she's out

**Comment by izaac** [comment]
Hi @gaktive we don't have an Azure QA environment integrated with Azure Apps, that's the reason we weren't able to repro or follow up this further.

**Comment by gaktive** [comment]
OK, thanks. Checking if anyone in UI has this kind of setup.
