### ISSUE TITLE
[2.4 backport] k8s 1.19 removes basic auth but it's in use by kontainer-engine

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#30170]
https://github.com/rancher/rancher/issues/28673

**Comment by deniseschannon** [comment]
This seems to only be needed for IF we add in k8s 1.19 to 2.4, but there are no plans to do so.

**Comment by cbron** [comment]
@deniseschannon this was the situation where its possible cloud providers like GKE could end up above what RKE/Rancher supports.

**Comment by sadiapoddar** [comment]
Verified the fix on 2.4-head, commit ca0c2b9f4
Steps
Created a 3 nodes gke cluster
From google console, Disabled basic-auth as recommended via gcloud container clusters update CLUSTER_NAME --no-enable-basic-auth
In Rancher, UI -> Edited the Cluster (using same SA credentials as on initial cluster setup)
Triggered the operational (e.g. update master cluster Kubernetes version from 1.17.14-gke.1600 to 1.17.17-gke-400)
Rancher triggered the update and the cluster return healthy state after the update
From the console re enabled the basic-auth and cluster updated without any error

<img width="1357" alt="Screen Shot 2020-12-28 at 11 12 55 AM" src="https://user-images.githubusercontent.com/72409237/103237853-c5f49b80-48fd-11eb-8208-2b7e2694a83f.png">
