### ISSUE TITLE
Add options to Global DNS

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#30184]
Backend issue: https://github.com/rancher/rancher/issues/28391

We are adding an additional options sections to the 3 global DNS providers. The backend PR adds the option from the API, this issue just needs to add the "options" section to the bottom of those providers.

**Comment by cbron** [comment]
@westlywright this needs to go into 2.5 and 2.4, you want an issue for 2.4 also ?

**Comment by westlywright** [comment]
@cbron no but can you target the correct 2.4 milestone? If its targeted at a 2.4.x release the fix goes into >=2.4.x.

**Comment by cbron** [comment]
Backend changes merged in master/2.5/2.4 branches.

**Comment by anupama2501** [comment]
Verified the issue as part of ((#28391))
