### ISSUE TITLE
[2.4 - new chart] global dns / rancher-external-dns 0.1.2

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#30186]
System-charts

Changes:

rancher/rancher#28391

**Comment by anupama2501** [comment]
Verified as part of https://github.com/rancher/rancher/issues/30197 on external DNS version 0.1.2
<img width="1262" alt="Screen Shot 2020-12-21 at 10 10 25 AM" src="https://user-images.githubusercontent.com/38144301/102808239-e314f180-4374-11eb-9457-0ce13d1d81df.png">
