### ISSUE TITLE
[2.4] Global DNS options

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#30185]
Backport of https://github.com/rancher/rancher/issues/28391

**Comment by cbron** [comment]
@anupama2501 this issue is to test on 2.4, did we do that or are we waiting for 2.4.12 ? 
Also somewhat related, this ticket is to track that there is a new globalDNS chart in general in 2.4: https://github.com/rancher/rancher/issues/30186

**Comment by anupama2501** [comment]
@cbron  this has been verified as part of https://github.com/rancher/rancher/issues/30197
