### ISSUE TITLE
Node local-node has disk pressure

### ISSUE THREAD

**Issue by benzman81** [rancher/rancher#30195]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
none

**Result:**
Currently I get the alert "Node local-node has disk pressure" on the local cluster. Since this is some virtual node rancher creates I have no clue where to look and how to free space. Any help appreciated. THX.

**Other details that may be helpful:**
none

**Environment information**
- Rancher version: 2.5.2
- Installation option: single install

**Comment by benzman81** [comment]
somehow healed itself after an hour. Anyway, how can this be solved in the future?

**Comment by superseb** [comment]
This is running inside the container, so its either the filesystem where Docker root is, or where you have mounted `/var/lib/rancher` from the container on the host. This should also be seen in the container log.

**Comment by benzman81** [comment]
So it is the filesystem that has no diskspace where I started the container ` rancher/rancher`?

**Comment by superseb** [comment]
You should be able to spot it on the host by running `df -h` but you can also `docker exec` into the `rancher/rancher` container and run `df -h`.

**Comment by benzman81** [comment]
Thanks, so I have to look on the machine where container `rancher/rancher` was started. That is the hint I needed. Maybe this should be documented somewhere as I couldnt find any information about the local cluster and node.
