### ISSUE TITLE
[2.4] Add options to Global DNS

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30197]
Backport UI for https://github.com/rancher/rancher/issues/30184

**Comment by anupama2501** [comment]
Following are the steps that were verified:
Rancher details:

Component | Version
Rancher | v2.4-4488-head
User Interface | v2.4-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher48


On 2.4-head[commit ID:v2.4-4488-head], create a DNS provider with the additional options, added the key aws.batchChangeSize with a value of 2000 and the value is reflecting in the local DNS app with 3 worker nodes, 3 etcd and 3 control plane
![image](https://user-images.githubusercontent.com/38144301/102736858-c3d97e00-42fa-11eb-945f-352e131c84b8.png)
![image](https://user-images.githubusercontent.com/38144301/102736869-cb992280-42fa-11eb-8a94-17aafae8d930.png)

Changed the values from the additional option to a different value and it reflected the changed value.
Verified changing the values from the edit yaml/API and saved. The values are reflected as expected.
<img width="580" alt="Screen Shot 2020-12-20 at 7 45 04 PM" src="https://user-images.githubusercontent.com/38144301/102737348-06e82100-42fc-11eb-84b9-c1cdb3859d37.png">
