### ISSUE TITLE
Prometheus fails with cluster_domain other then cluster.local: proxyconnect tcp: dial tcp: lookup pushprox-kube-controller-manager-proxy.cattle-monitoring-system.svc.cluster.local  no such host

### ISSUE THREAD

**Issue by chuegel** [rancher/rancher#30191]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
 - Upgraded from rancher 2.4.8 
 - disabled monitoring in Cluster Manager  
  - deployed Monitoring via Cluster Explorer 

All pods are running fine:

![image](https://user-images.githubusercontent.com/6955465/99943271-52e18d80-2d71-11eb-94ab-270147f910ff.png)

```
kubectl get po -n cattle-monitoring-system
NAME                                                      READY   STATUS    RESTARTS   AGE
alertmanager-rancher-monitoring-alertmanager-0            2/2     Running   0          3d17h
prometheus-rancher-monitoring-prometheus-0                4/4     Running   1          17h
pushprox-kube-controller-manager-client-4vp86             1/1     Running   0          3d17h
pushprox-kube-controller-manager-client-htm5x             1/1     Running   0          3d17h
pushprox-kube-controller-manager-client-s5cxz             1/1     Running   0          3d17h
pushprox-kube-controller-manager-proxy-6df75f64bb-b2l8k   1/1     Running   0          3d17h
pushprox-kube-etcd-client-7jbvl                           1/1     Running   0          3d17h
pushprox-kube-etcd-client-bm4wm                           1/1     Running   0          3d17h
pushprox-kube-etcd-client-ptckk                           1/1     Running   0          3d17h
pushprox-kube-etcd-proxy-7bf98f5cd-sbgm8                  1/1     Running   0          3d17h
pushprox-kube-proxy-client-4g6lb                          1/1     Running   0          3d17h
pushprox-kube-proxy-client-5sv8s                          1/1     Running   0          3d17h
pushprox-kube-proxy-client-hrmng                          1/1     Running   0          3d17h
pushprox-kube-proxy-client-mhtmd                          1/1     Running   0          3d17h
pushprox-kube-proxy-client-pwxkr                          1/1     Running   0          3d17h
pushprox-kube-proxy-client-sh926                          1/1     Running   0          3d17h
pushprox-kube-proxy-proxy-cc7bfb666-rswsd                 1/1     Running   0          3d17h
pushprox-kube-scheduler-client-94fbx                      1/1     Running   0          3d17h
pushprox-kube-scheduler-client-cwcgm                      1/1     Running   0          3d17h
pushprox-kube-scheduler-client-fvxgx                      1/1     Running   0          3d17h
pushprox-kube-scheduler-proxy-6c7598b646-qzxx2            1/1     Running   0          3d17h
rancher-monitoring-grafana-6c9bc449d4-zdctg               3/3     Running   0          3d17h
rancher-monitoring-kube-state-metrics-5c549477ff-9ksvc    1/1     Running   0          3d17h
rancher-monitoring-operator-866cbfbcdc-zjgrk              2/2     Running   0          3d17h
rancher-monitoring-prometheus-adapter-795d5d4f75-fw8m7    1/1     Running   0          3d17h
rancher-monitoring-prometheus-node-exporter-55nww         1/1     Running   0          3d17h
rancher-monitoring-prometheus-node-exporter-f7j6v         1/1     Running   0          3d17h
rancher-monitoring-prometheus-node-exporter-gcwkk         1/1     Running   0          3d17h
```

**Result:**
Prometheus fails on some targets with: `Get "http://10.2.28.41:10252/metrics": proxyconnect tcp: dial tcp: lookup pushprox-kube-controller-manager-proxy.cattle-monitoring-system.svc.cluster.local on 10.2.68.10:53: no such host`

where 10.2.68.10 is the kube-dns service 

![image](https://user-images.githubusercontent.com/6955465/99943582-d0a59900-2d71-11eb-9530-fe9c22e8bbc3.png)

**Other details that may be helpful:**
My cluster domain is `lab.local` and not `cluster.local` as Prometheus tries to fetch

This is inside a pod:
```
bash-5.0# nslookup pushprox-kube-controller-manager-proxy.cattle-monitoring-system.svc.cluster.local
Server:		10.2.68.10
Address:	10.2.68.10#53

** server can't find pushprox-kube-controller-manager-proxy.cattle-monitoring-system.svc.cluster.local: NXDOMAIN

nslookup pushprox-kube-controller-manager-proxy.cattle-monitoring-system.svc.lab.local
Server:		10.2.68.10
Address:	10.2.68.10#53

Name:	pushprox-kube-controller-manager-proxy.cattle-monitoring-system.svc.lab.local
Address: 10.2.68.112

bash-5.0# nslookup pushprox-kube-controller-manager-proxy.cattle-monitoring-system.svc
Server:		10.2.68.10
Address:	10.2.68.10#53

Name:	pushprox-kube-controller-manager-proxy.cattle-monitoring-system.svc.lab.local
Address: 10.2.68.112

bash-5.0# cat /etc/resolv.conf
nameserver 10.2.68.10
search default.svc.lab.local svc.lab.local lab.local 
options ndots:5

```

```
kubectl exec -it -n cattle-monitoring-system   pushprox-kube-controller-manager-client-cx2sq -- /bin/sh
/ $ cat /etc/resolv.conf
nameserver 10.2.68.10
search cattle-monitoring-system.svc.lab.local svc.lab.local lab.local 
options ndots:5
```

I'm not sure why Prometheus tries to use the default cluster.local domain name. 
Any hints are much appreciated.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by chuegel** [comment]
Ok I found the issue. The cluster domain is hard coded (proxyUrl)  in following yaml files:

```
rancher-monitoring-kube-scheduler 
rancher-monitoring-kube-proxy
rancher-monitoring-kube-etcd 
```

**Comment by aiyengar2** [comment]
@chuegel thanks for catching this. It's hard-coded in the `rancher-pushprox` helper function here: https://github.com/rancher/charts/blob/4476584d9b9b09d6393585b3e60b47d3cf4a32e4/charts/rancher-pushprox/templates/_helpers.tpl#L30

To fix this, I think it would make sense to expose a `global.clusterDomain: cluster.local` in the `values.yaml` of both `rancher-monitoring` and `rancher-pushprox` and replace the following code for rancher-pushprox:
```
{{ printf "http://%s.%s.svc.%s:%d" (include "pushProxy.proxy.name" .) .Release.Namespace (.Values.global.clusterDomain) (int .Values.proxy.port) }}
```

We can then  expose a UI field to configure that.

#### Workaround

As shown in https://github.com/rancher/charts/blob/4476584d9b9b09d6393585b3e60b47d3cf4a32e4/charts/rancher-pushprox/templates/_helpers.tpl#L28, you can override the proxyURL to whatever you want. So for your case, you might want to override the following in the [values.yaml](https://github.com/rancher/charts/blob/4476584d9b9b09d6393585b3e60b47d3cf4a32e4/charts/rancher-monitoring/values.yaml#L25-L86) for the relevant cluster type:
```yaml
<clusterType>Scheduler:
  clients:
    proxyURL: pushprox-kube-controller-manager-proxy.cattle-monitoring-system.svc.lab.local:8080
<clusterType>Proxy:
  clients:
    proxyURL: pushprox-kube-scheduler-proxy.cattle-monitoring-system.svc.lab.local:8080
<clusterType>Etcd:
  clients:
    proxyURL: pushprox-kube-etcd-proxy.cattle-monitoring-system.svc.lab.local:8080
```

**Comment by bashofmann** [comment]
Is it even necessary that the hostnames are full qualified and contain the cluster domain? E.g. `pushprox-kube-controller-manager-proxy.cattle-monitoring-system:8080` should also just work, regardless of the cluster domain, shouldn't it?

**Comment by aiyengar2** [comment]
@bashofmann good call out. Another option would be to complete remove the `cluster_domain` field entirely, which would be a quick PR to the rancher-pushprox chart. I wrote a quick PR in https://github.com/rancher/charts/pull/895#pullrequestreview-552028526 to address this.

cc: @maggieliu @cloudnautique if we want to get this in / if we have testing bandwidth for this, I could modify the PR to set it up for the current release (2.5.4). Otherwise, it should be ready for merging in 2.5.5 with the packageVersion bump.

**Comment by slickwarren** [comment]
I was able to reproduce this by doing the following:
* create HA rancher cluster on 2.4.8
* created various clusters + imported into rancher (these were GKE clusters)
* enabled monitoring on said clusters
* upgrade rancher 2.4.8 -> 2.5.2
* disabled monitoring v1, enabled monitoring v2 on existing clusters
* imported RKE cluster with `cluster.domain: lab.local`
* enabled v2 monitoring on RKE imported cluster

This puts the RKE prometheus targets in the same state that the user reports.  
`cattle-monitoring-system/rancher-monitoring-kube-controller-manager` is down, etc.  

Based on the way I reproduced this, it appears that the imported cluster does not need v1 monitoring enabled previously to see this issue.

**Comment by agi0rgi** [comment]
Having the same issue here, from a fresh installed Rancher 2.5.5 in HA.
The imported cluster is an RKE HA Cluster version 1.2.3, with Monitoring v2 enabled, throws the very same errors as @chuegel 
 reports

**Comment by chuegel** [comment]
@agi0rgi I'm getting the same issue as you described. What do you mean you had to re-enroll all RKE Cluster nodes?

**Comment by agi0rgi** [comment]
> @agi0rgi I'm getting the same issue as you described. What do you mean you had to re-enroll all RKE Cluster nodes?

@chuegel i had to remove one node at a time from the RKE Cluster (the one i was trying to install monitoring onto), and while removing each node, i changed their "address" field from the hostname to the actual IP address of the node (we were relying on DNS before).

To sum it up, for each of the nodes of your cluster (Both controlplanes and workers), you have to:
- Comment out from the "cluster.yaml" file, the definition of the node you wish to change the address field
``` 
#- address: rke-master1
#  port: "22"
#  internal_address: ""
#  role:
#  - controlplane
#  - etcd
#  hostname_override: ""
#  user: rancher
#  docker_socket: /var/run/docker.sock
#  ssh_key: ""
#  ssh_key_path: ~/.ssh/id_rsa
#  ssh_cert: ""
#  ssh_cert_path: ""
#  labels: {}
#  taints: []
```
- Run rke up (I noticed that it may fail at first, so give it a retry)
- De-comment the definition of the node with the changed address:
``` 
- address: 10.10.10.11
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: "rke-master1"
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
```
- Run rke up (I noticed that it may fail at first, so give it a retry)

That way you also have the IP Addresses in the certificates SANs.

**Comment by chuegel** [comment]
It worked for me with protocol `http`
