### ISSUE TITLE
"Help" Page

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#3019]
On the top right dropdown, add a link to a "help" page or perhaps to our dashboard

This page should contain the following:

- Link to forums (any way to more tightly integrate with our forums?)
- Link to file bugs/issues with Github
- Link to docs
- Link to docs FAQ/Troubleshooting
- Link to  Rancher "Learn"/"Tutorial" Page
- Contact for Commercial Support description

**Comment by tfiduccia** [comment]
Version - master 1/27
Verified fixed - help added, links clicked
