### ISSUE TITLE
RKE cluster down with etcd server panic because snapshot is missing

### ISSUE THREAD

**Issue by mamiapatrick** [rancher/rancher#30202]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
Power failure of rancher node (RancherOS)

**Result:**
By inspecting the log I got an error
```
etcdserver: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
panic: recovering backend from snapshot error: database snapshot file path 
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.3.2
- Installation option (single install/HA): HA (3 nodes of etcd and 2 master)

**Cluster information**

```
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 8 CPU, 8 Gb RAM
- Kubernetes version (use `kubectl version`): v1.15.5
```

- Docker version (use `docker version`):

```
Rancher 2.3.1
 RKE 0.3.1
 Kubernetes v1.15.5
```

**Comment by BlackHades** [comment]
i am also having this issue

panic: recovering backend from snapshot error: failed to find database snapshot file (snap: snapshot file doesn't exist)
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc2cc4e]

goroutine 1 [running]:
go.etcd.io/etcd/etcdserver.NewServer.func1(0xc0002aef50, 0xc0002acf48)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/server.go:335 +0x3e
panic(0xed6960, 0xc000164030)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc00000d720, 0x10aeaf5, 0x2a, 0xc0002ad018, 0x1, 0x1)
	/home/ec2-user/go/pkg/mod/github.com/coreos/pkg@v0.0.0-20160727233714-3ac0863d7acf/capnslog/pkg_logger.go:75 +0x135
go.etcd.io/etcd/etcdserver.NewServer(0x1085123, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc000116f80, 0x1, 0x1, 0xc000116e00, ...)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/server.go:456 +0x42f7
go.etcd.io/etcd/embed.StartEtcd(0xc0000fdb80, 0xc0000fe100, 0x0, 0x0)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/embed/etcd.go:211 +0x9d0
go.etcd.io/etcd/etcdmain.startEtcd(0xc0000fdb80, 0x108423e, 0x6, 0x1, 0xc0001bd1d0)
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/etcd.go:302 +0x40
go.etcd.io/etcd/etcdmain.startEtcdOrProxyV2()
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/etcd.go:144 +0x2f71
go.etcd.io/etcd/etcdmain.Main()
	/tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/main.go:46 +0x38
main.main()
	/tmp/etcd-release-3.4.3/etcd/release/etcd/main.go:28 +0x20
2020/11/28 14:49:25 [FATAL] etcd exited

**Comment by mamiapatrick** [comment]
@BlackHades 

tell me which etcd had this panic on your side, the ectd nodes of your RKE cluster or this stack is the log of rancher/rancher container?

**Comment by Yabbo** [comment]
docker ps: 
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                          PORTS               NAMES
1ef8f4c3ea98        rancher/rke-tools:v0.1.69              "/docker-entrypoint.…"   4 minutes ago       Up 4 minutes                                        etcd-rolling-snapshots
77d8f8619988        rancher/coreos-etcd:v3.4.13-rancher1   "/usr/local/bin/etcd…"   4 minutes ago       Restarting (2) 35 seconds ago                       etcd


docker logs etcd:
2021-02-04 03:46:58.246403 I | etcdserver: recovered store from snapshot at index 17100188
2021-02-04 03:46:58.253518 C | etcdserver: recovering backend from snapshot error: failed to find database snapshot file (snap: snapshot file doesn't exist)
panic: recovering backend from snapshot error: failed to find database snapshot file (snap: snapshot file doesn't exist)
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc0587e]
