### ISSUE TITLE
Editing External service results in error message - "Unknown action: setservicelinks"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3020]
Rancher server version - v0.50.0-rc2

Create an external service pointing to hostname.
Activate this service.
Edit this service and change the hostname and save.
User is presented with - Unknown action: setservicelinks
<img width="972" alt="screen shot 2015-12-14 at 12 11 59 pm" src="https://cloud.githubusercontent.com/assets/4266958/11792761/911e75a4-a25c-11e5-88ce-0f53133ea31c.png">

The changed hostname is actually saved even though this error message is seen.

**Comment by alena1108** [comment]
should be fixed in the UI. setServiceLinks action was disabled for external services @vincent99 ^^

**Comment by sangeethah** [comment]
Tested with latest build from master

Able to edit external services.
