### ISSUE TITLE
Rancher Import Problem

### ISSUE THREAD

**Issue by oassuncao** [rancher/rancher#30214]
I'm using Rancher 2.5.1 and I'm importing my AKS and GKE clusters.

The cluster was imported but after a few seconds I receive the error bellow

> Admission webhook "rancherauth.cattle.io" denied the request: user "system:serviceaccount:cattle-system:rancher" (groups=["system:serviceaccounts" "system:serviceaccounts:cattle-system" "system:authenticated"]) is attempting to grant RBAC permissions not currently held: {APIGroups:["*"], Resources:["secrets"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["catalogs"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["cisbenchmarkversions"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["cisconfigs"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["clusters"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["clustertemplaterevisions"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["features"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["globaldnses"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["globaldnsproviders"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["kontainerdrivers"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["multiclusterapps"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["nodedrivers"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["nodetemplates"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["podsecuritypolicytemplates"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["preferences"], Verbs:["*"]} {APIGroups:["management.cattle.io"], Resources:["principals"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["rkeaddons"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["rkek8sserviceoptions"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["rkek8ssystemimages"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["roletemplates"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["settings"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["templates"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["templateversions"], Verbs:["get" "list" "watch"]} {APIGroups:["project.cattle.io"], Resources:["sourcecodecredentials"], Verbs:["*"]} {APIGroups:["project.cattle.io"], Resources:["sourcecoderepositories"], Verbs:["*"]}; resolution errors: [[clusterroles.rbac.authorization.k8s.io "cluster-admin" not found, clusterroles.rbac.authorization.k8s.io "system:discovery" not found]]
--

![image](https://user-images.githubusercontent.com/3209775/100108869-0a49d300-2e4a-11eb-9507-36a3c6db0b42.png)

I looked at service accounts existents on my cluster, but I didn't find any with the name **rancher**

**Comment by oassuncao** [comment]
I resolved this problem by creating a ClusterRoleBinding to cluster-admin and system:discovery

**Comment by Cahdek** [comment]
> I resolved this problem by creating a ClusterRoleBinding to cluster-admin and system:discovery

I am experiencing this as well. Can you provide the kubectl command you used?
I tried:
kubectl create clusterrolebinding cluster-admin-binding -n cattle-system --clusterrole cluster-admin --user rancher
