### ISSUE TITLE
Notifications when new version of Rancher is available

### ISSUE THREAD

**Issue by smw355** [rancher/rancher#3022]
It would be great if somewhere in Rancher users were notified that a newer version of the software was available for upgrade.

**Comment by Ilya-Kuchaev** [comment]
+1

**Comment by Rucknar** [comment]
http://forums.rancher.com/c/announcements
I get an email when a new release is made available.

**Comment by ibuildthecloud** [comment]
@smw355 are you saying you'd like something in the Rancher UI itself?

**Comment by vincent99** [comment]
Yes, it's going into the help screen (by reading the forum announcements)

**Comment by kaos** [comment]
@vincent99 can't you reference issues from your commit messages, that way we can learn were stuff is implemented without having to search for it.. ;)

**Comment by vincent99** [comment]
https://github.com/rancher/ui/pull/418

**Comment by kaos** [comment]
Ah thanks Vincent, a cross ref to #3019 would've worked too :)

**Comment by tfiduccia** [comment]
Version - master Jan 07
Verified added.
