### ISSUE TITLE
[2.3] KDM Release - k8s patches for Dec 

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30223]
1.17.16 -2.3.8+

**Comment by anupama2501** [comment]
Following are the checks performed on the clusters:

Rancher: 2.3.10-rc2
K8ss verified: 1.17.16-rancher1-1

2.3.10-rc2 -fresh install

1.Fresh install of rancher on 2.3.10-rc2, verify the versions of k8s shown while creating the clusters: 1.17.16-rancher1-1
2.Launch clusters on 4 network providers[calico, flannel, cannel and weave] for two k8s versions - 1.17.16-rancher1-1
3.Run validation and network checks
All the checks have passed

Upgrade testing:
1.Rancher fresh install on 2.3.9
2.Create clusters on 4 network providers for 1.17.14-rancher1-1
3.Run pre-upgrade checks - PASS
4.Upgarde rancher version to 2.3.10-rc2 - PASS
5.Run post-upgrade checks - PASS
6.Verify metadata container pointing dev
7.Upgrade the k8s version on all the clusters to 1.17.16-rancher1-1 respectively - PASS
8.Run post upgrade checks - PASS

**Comment by anupama2501** [comment]
2.3.8 - min version checks
1.Change the metadata container pointing from master to dev
2.Create clusters on 4 network providers for the three k8s versions 1.17.16-rancher1-1 - PASS
3.Run network checks on all the clusters - PASS
