### ISSUE TITLE
k8s version update - Dec Patches

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30221]
Update k8s versions to:
1.19.6 - 2.5.0+
1.18.14 - 2.4.5+
1.17.16 -2.4.4+

**Comment by maggieliu** [comment]
@PennyScissors will be updating the 1.17.16 and 1.19.6

**Comment by anupama2501** [comment]
Following are the checks performed on the clusters:

Rancher: 2.5.4-rc8
K8ss verified: 1.19.6-rancher1-1,1.18.14-rancher1-1,1.17.16-rancher1-1

2.5.4-rc8 -fresh install

1.Fresh install of rancher on 2.5.4-rc8, verify the versions of k8s shown while creating the clusters: 1.19.6-rancher1-1,1.18.14-rancher1-1
2.Launch clusters on 4 network providers[calico, flannel, cannel and weave] for two k8s versions - 1.19.6-rancher1-1,1.18.14-rancher1-1
3.Run validation and network checks
All the checks have passed

Upgrade testing:
1.Rancher fresh install on 2.5.3[commit id: ]
2.Create clusters on 4 network providers for 1.19.4-rancher1-1,1.18.12-rancher1-1,1.17.14-rancher1-1
3.Run pre-upgrade checks - PASS
4.Upgarde rancher version to 2.4.5-rc8 - PASS
5.Run post-upgrade checks - PASS
6.Verify metadata container pointing dev
7.Upgrade the k8s version on all the clusters to 1.19.6-rancher1-1,1.18.14-rancher1-1,1.17.16-rancher1-1 respectively - PASS
8.Run post upgrade checks - PASS

2.5.3 - min version checks
1.Change the metadata container pointing from release to dev
2.Create clusters on 4 network providers for the three k8s versions 1.19.6-rancher1-1,1.18.14-rancher1-1,1.17.16-rancher1-1 - PASS
3.Run network checks on all the clusters - PASS
