### ISSUE TITLE
[2.4] KDM Release - k8s Dec Patches

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30222]
1.18.13 - 2.4.5+
1.17.16 -2.4.4+

**Comment by anupama2501** [comment]
Following are the checks performed on the clusters for k8s:

**Rancher: 2.4.12-rc3**
**K8ss verified: 1.18.14-rancher1-1,1.17.16-rancher1-1**

**2.4.12-rc3 -fresh install**

1.Fresh install of rancher on 2.4.12-rc3, verify the versions of k8s shown while creating the clusters: 1.18.14-rancher1-1.1.17.16-rancher1-1
2.Launch clusters on 4 network providers[calico, flannel, cannel and weave] for two k8s versions - 1.18.14-rancher1-1, 1.1.17.16-rancher1-1
3.Run validation and network checks
All the checks have passed

**Upgrade testing:**
1.Rancher fresh install on 2.4.11
2.Create clusters on 4 network providers for 1.18.12-rancher1-1,1.17.14-rancher1-1
3.Run pre-upgrade checks - PASS
4.Upgrade rancher version to 2.4.12-rc3 - PASS
5.Run post-upgrade checks - PASS
6.Change the metadata container pointing from release to dev
7.Upgrade the k8s version on all the clusters to 1.18.14-rancher1-1,1.17.16-rancher1-1 respectively - PASS
8.Run post upgrade checks - PASS

**Upgrade testing on different types of clusters:**
1.Rancher fresh install on 2.4.11
2.Create clusters on DO with k8s 1.16.5-rancher1-3, custom ubuntu on k8s 1.15.12-rancher1-2, EC2 rancherOS with k8s 1.17.14-rancher1-1, custom ubuntu with k8s 1.18.12-rancher1-1
3.Run pre-upgrade checks - PASS
4.Upgrade rancher version to 2.4.12-rc3 - PASS
5.Run post-upgrade checks - PASS
6.Change the metadata container pointing from release to dev
7.Upgrade the k8s version on all the clusters of 1.18.12-rancher1-1,1.16.5-rancher1-13,1.15.12-rancher1-2 to 1.18.14-rancher1-1 and 1.17.14-rancher1-1 to 1.17.16-rancher1-1 respectively - PASS
8.Run post upgrade checks - PASS
9.Run network checks - PASS

2.4.5 - min version checks
1.Fresh install rancher on 2.4.5
2.Create clusters on 4 network providers for the three k8s versions 1.18.14-rancher1-1 - PASS
3.Run network checks on all the clusters - PASS

2.4.4 - min version checks
1.Fresh install rancher on 2.4.4
2.Create clusters on 4 network providers for the three k8s versions 1.17.16-rancher1-1 - PASS
3.Run network checks on all clusters - PASS
