### ISSUE TITLE
Admin user lost when reinstall a HA rancher on K3S

### ISSUE THREAD

**Issue by wangxi83** [rancher/rancher#30243]
Hi,all

I installed a HA rancher on a K3S cluster with helm.
And I used system-tools to remove it with "system-tools remove --kubeconfig=xxx" by some reson.
Everything was ok, except the namespaces "cattle-system, local,  and some 'p-xxxx'" were in status "Terminating", and I solved to delete them with "k3s kubectl edit namespaces xxxx" and modifed "finalizers" field.

Then, I reinstall rancher with helm.

But when it setted up, I could not login with "admin user".
I suppose to change the admin's password

> KUBECONFIG=/etc/rancher/k3s/k3s.yaml
> k3s kubectl --kubeconfig $KUBECONFIG -n cattle-system exec $(kubectl --kubeconfig $KUBECONFIG -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- reset-password

it shows:

```
W1126 09:18:36.297686     168 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
0 users were found with authz.management.cattle.io/bootstrapping=admin-user label. They are []. Can only reset the default admin password when there is exactly one user with this label.
command terminated with exit code 1
```

and I used command:

> k3s kubectl get users -l authz.management.cattle.io/bootstrapping=admin-user -o json

I got empty user items:

```
[root@k3s01 ~]# k3s kubectl get users -l authz.management.cattle.io/bootstrapping=admin-user -o json
{
    "apiVersion": "v1",
    "items": [],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
```

what I missed? need help! I just want to uninstall and reinstall a HA rancher

**Comment by tinnkm** [comment]
i exec the following comand,sloved this problem,hope it will work for you
```shell
kubectl --kubeconfig $KUBECONFIG -n cattle-system exec $(kubectl --kubeconfig $KUBECONFIG -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- ensure-default-admin
```

**Comment by wangxi83** [comment]
> i exec the following comand,sloved this problem,hope it will work for you
> 
> ```shell
> kubectl --kubeconfig $KUBECONFIG -n cattle-system exec $(kubectl --kubeconfig $KUBECONFIG -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- ensure-default-admin
> ```

well,  thanks, "ensure-default-admin", i'll try it...

**Comment by vildek** [comment]
Same problem with K8s. Because of rancher bloatware and poor helm delete process, some garbage is left after removing all namespaces related to rancher. When you install new rancher cluster, it doesn't create an user in db and you are stuck. Awesome solution. Funny that Rancher states in their website that they don't leave anything in cluster after you uninstall it.

**Comment by wangxi83** [comment]
> > i exec the following comand,sloved this problem,hope it will work for you
> > ```shell
> > kubectl --kubeconfig $KUBECONFIG -n cattle-system exec $(kubectl --kubeconfig $KUBECONFIG -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- ensure-default-admin
> > ```
> 
> well, thanks, "ensure-default-admin", i'll try it...
