### ISSUE TITLE
[2.5.2] Kubernetes upgrade to 1.19.4 failed - Secrets cattle-system not found

### ISSUE THREAD

**Issue by lexbutler0** [rancher/rancher#30245]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
upgrade from 2.5.1 to 2.5.2, upgrade kubernetes v1.19.3-rancher1-1 to v1.19.4-rancher1-1

**Result:**
the upgrade process failed

```
This cluster is currently Updating.
Secrets "cattle-system/c-c-2mdz5" not found
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.2
- Installation option (single install/HA): single docker

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): self hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3xVM, 4cpu/6gb mem/100gb ssd
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by pangliang** [comment]
same problem

**Comment by lexbutler0** [comment]
any solution? workaround? hint?

it looks like cannot deploy new app until it is in upgrading status
