### ISSUE TITLE
Rancher2/Kubernetes with canal generate few IPspoofing on enterprise network that break Cisco ACI

### ISSUE THREAD

**Issue by disaster37** [rancher/rancher#30247]
**What kind of request is this (question/bug/enhancement/feature request):** BUG
In our company, we have deployed kubernetes cluster from Rancher2 with canal CNI. All nodes are in the same VLAN. Our network infrastructure is powered by Cisco ACI (Application Centric Infrastructures).

We have found  that the NAT seems not working as expected because of it seems to spoof external IP. 
Our pod network is `10.42.*.*.` Our node network is `10.0.0.*.` And some pod can consume external resources like database on network `10.0.100.*.` We have enterprise Firewall between kube network and database network. For exemple, we have a pod with IP `10.42.0.1`, a kube node with IP `10.0.1.1` and external database with IP `10.0.100.1`. In our Firewall, we look some IPspoffing from kube node with source IP 10.0.100.1 (the database IP) and destination 10.42.0.1. When we compare time from Ipspoofing and kubernetes event, it's doing when the pod is destroying. So we suspect a kind of NAT Issue when DB respond to pod and when to pod is being destroyed.

In standard network, it's not a real matter, but is not so simple on Cisco ACI. The LEAF learn source IP 10.0.100.1 on kube network instead on database network. So the IP 10.0.100.1 is duplicated on leaf table and the server 10.0.100.1 become unreachable from all server in datacenter.

**Steps to reproduce (least amount of steps as possible):**
Force a high network traffic from a statefullset workload to external ressources (like proxy or query on database)
Then update the stefullset workload to force recreate pod (add label)

**Result:**
You can look spoofing alart on your Firewall with  the external service IP as source IP (db or proxy) and the pod IP as target. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.8
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):v1.18.6

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by abdelens** [comment]
How do you know it is a kube node that spoofed the IP 10.0.100.1? do you see the initial request in fw logs (from 10.0.1.1 to 10.0.100.1)? some firewalls logs packet as spoofed when it is coming from an unexpected interface so it's maybe not a real ip spoofing. 
Could you share your nat rules, maybe there is overlapping with db network. 
did firewall and db connected to the ACI leaf?

**Comment by disaster37** [comment]
We know that is kube node that spoof IP 10.0.100.1 because of :

- the `10.42.*.*` network is only used on internal kubernetes VXLAN. Moreover, we track the IP allocation on pod, and we know that IP (10.42.0.1) is the pod IP juste before it restarted.
- each time we restart the pod that read on DB (logstash over jdbc for event ingestion), we have the  spoofing on firewall and the matter on Cisco ACI

And yes, we can look on Firewall that 10.0.1.1  call with 10.0.100.1 (10.0.1.1 -> 10.0.100.1)

There are only iptables rules managed by kubernetes. Are you sure to look them ? It's very big...

All server, database, firewall is connected on ACI Leaf indirectly (I think there are some intermediate switch).

**Comment by disaster37** [comment]
After check all OS requirement from RKe: https://rancher.com/docs/rke/latest/en/os/

I found we have 2 kernel modules that are not loaded:
```
module x_tables is not present
module xt_tcpudp is not present
```

You think it can be a link with issue ?
