### ISSUE TITLE
Cluster health check failed: cluster agent is not ready - DNS - /etc/resolv.conf

### ISSUE THREAD

**Issue by bor8** [rancher/rancher#30248]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug.

**Steps to reproduce (least amount of steps as possible):**
Add all VMs as nodes.
Get error in Rancher: `Cluster health check failed: cluster agent is not ready`
Get error in ctop (docker container cluster-register):
```markdown
INFO: Environment: CATTLE_ADDRESS=10.XXX.YYY.ZZZ CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_FEATURES= CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=true CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-XXX-YYY CATTLE_SERVER=https://rancher.example.com
INFO: Using resolv.conf: nameserver 10.XXX.YYY.ZZZ search cattle-system.svc.cluster.local svc.cluster.local cluster.local ffm.web web options ndots:5
**ERROR: https://rancher.example.com/ping is not accessible (Failed to connect to rancher.example.com port 443: Connection timed out)**
Problem: rancher Readiness probe for cattle-cluster-agent cattle-system  :cluster-register failed (failure): Get http://10.XXX.YYY.ZZZ/health: dial tcp :8080: connect: connection refused  # some other container
```

**Result:**
Rancher only shows the general error message. You can neither see the event logs nor use kubectl (the buttons are not there or are disabled)!!!

**Other details that may be helpful:**
I do not have full control over the DNS. I do not know what happens if I use the internal IP 172.XXX.YYY.ZZZ instead of rancher.example.com. Since I am unsure, I have left it at rancher.example.com. Since the DNS returns an IP for this which is not accessible from everywhere, I provided my own DNS with `/etc/hosts` and `sudo apt install dnsmasq` on Ubuntu 18.04 and included my VM IP via `upstreamnameservers` in YAML in my Rancher GUI. Most docker containers receive the newly added nameservers, but not all! It probably did not work for the docker container cluster-register!!! Maybe this is a bug!!! Only when I went with `docker exec -it <ID> bash` into the docker container and added "nameserver 172.XXX.YYY.ZZZ" to the `/etc/resolv.conf`, it worked.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 11 VMs, 8 CPU cores, 16 GB RAM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-16T17:18:52Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by bor8** [comment]
Additional question: Where and how can I add hostAliases for the whole cluster? Furthermore I don't find/see "Networking" like in https://github.com/rancher/rancher/issues/13328.

**Comment by superseb** [comment]
The configured `server-url` in Rancher should be a DNS resolvable name which is accessible by every node in the cluster(s). By manually querying `rancher.example.com` to the cluster DNS (which runs at 10.43.0.10 by default, this is configurable),  you can see if the DNS properly resolves in the cluster (`dig rancher.example.com @10.43.0.10`)

Please share the exact cluster configuration YAML with the addresses so we can determine what is configured. Also, if you tear everything down and set the DNS up properly from scratch, does it work then? This isolates to it not working at all or if its only related to changing it half way. Adding hostAliases is really not a sustainable workaround.

**Comment by bor8** [comment]
I have now rebuilt everything back to a private IP for Docker Rancher. Works. I find it "a shame" that you can't make an "/etc/hosts entry" for ALL containers in either Docker or RKE. That would make it so much easier for me to bypass DNS.
