### ISSUE TITLE
Users ID and namespaces

### ISSUE THREAD

**Issue by kombiwagon** [rancher/rancher#30251]
I have deployed Rancher-2.4.5 in my claster and I've noticed that each Rancher's user has own ID and this ID exist like namespace in cluster.
Becouse i have a lot of users in Rancher it is uncomfortable for me becouse I have simultanousle a lot of new namespaces in cluster.

Is it possible change this behaviour ? 
Why Rancher create new namespace for each user? 

example: 
#kubectl get namespace
u-hfnrtwqnfp         
u-lswfjb62zz         
u-x6enl73cpn         
u-yhf7ygrbjc         
u-z74m53gg2v

Thank you in advance for any reply

**Comment by SkySonR** [comment]
same issue, please assist

**Comment by SckyzO** [comment]
Hello, 

I have the same problem and the same question. Why is a namespace automatically created with the user ID? is it obligatory?
If not, how to prohibit the creation of this namespace??
