### ISSUE TITLE
Accidentially deleted kubelet pod on worker node

### ISSUE THREAD

**Issue by discostur** [rancher/rancher#30253]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

Hi,

i accidentially deleted the kubelet pod on one of our k8s worker nodes:

```
docker stop UUID && docker rm UUID
``` 

Now rancher says ` Kubelet stopped posting node status`. Is there any way to get the kubelet pod back again?

I even tried to re-add the node to the cluster without success (node was not deleted nor cleaned up):
```
docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.3.9 ...
``` 

Rancher Agent is still running on the node. Do i have to remove the node completly and re-add it as a fresh node / installation? Seems to me like a big overhead instead of just re-creating the kubelet pod ...

Thanks

**Environment information**
- Rancher v2.3.9
- Single Installation

**Comment by skyscooby** [comment]
What method and infrastructure did you use to create your Kubernetes cluster?

If this is an external cluster that was imported to Rancher then you should use those tools or procedures to re-establish the node as a member of the cluster as Rancher isn't directly managing nodes in that case and assumes other tools are doing this.

If it is a rancher managed cluster you should be able to simply delete the node in the in cluster manager and rancher should see that a node is missing and re-create it using the same process it did the first time.

**Comment by discostur** [comment]
@skyscooby Installation method was `custom / existing nodes`. Sure, i can just delete the node and re-add it to the cluster.

I tought there would be a nicer way of fixing the node because just one pod is missing ... 

Anyway - thanks for your help ;)
