### ISSUE TITLE
[Continuous Delivery] Target Customization not applied when using intersected groups

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#30252]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Have two k3s clusters (`cluster-a`, `cluster-b`) registered in Rancher
2. Create a cluster group (`group-ab`) containing both clusters
3. Create two additional cluster groups containing one cluster each (`group-a`, `group-b`)
4. Create a repository containing the Kubernetes manifests to apply to both clusters ([see example](https://github.com/janeczku/k3s-fleet-demos/tree/master/hello-world))
5. Create a fleet.yaml to specify a  named cluster group customization for `group-b`:
```
targetCustomizations:
  - name: colorize
    yaml:
      overlays:
        - green-color
    clusterGroup: group-b
```
6. Create a GitRepo resource in Rancher using the `clusterGroup` target type and specifying the group containing both clusters, ie.  -> Deploy To -> Target Type: Cluster Group -> `group-ab`

**Expected Result:**

The green-color overlay is applied to `cluster-b` as it is contained in `group-b`

**Actual  Result:**

The green-color overlay is not applied to `cluster-b`

**Environment information**

Rancher 2.5.2

**Comment by deniseschannon** [comment]
Closing in favor of fleet issue.
