### ISSUE TITLE
Registering an EKS cluster defaults to manually entered name

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#30262]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Select to register an existing EKS cluster
2. Enter any name (like `donnie-test`)
3. Select an EKS cluster with a different name (like `test`)

**Result:**
The request that is made to the backend has no reference to the cluster that already exists in EKS. For example, the scenario above would have no reference to the cluster `test`, only to the name `donnie-test`.

**Other details that may be helpful:**
Request example: ```{"dockerRootDir":"/var/lib/docker","enableClusterAlerting":false,"enableClusterMonitoring":false,"enableNetworkPolicy":false,"windowsPreferedCluster":false,"type":"cluster","name":"donnie-test","eksConfig":{"imported":true,"displayName":"donnie-test","region":"us-east-2","type":"eksclusterconfigspec","amazonCredentialSecret":"cattle-global-data:cc-bf4ng"},"labels":{}}```

Related Issue:
https://github.com/rancher/rancher/issues/29103

Specifically, this comment: https://github.com/rancher/rancher/issues/29103#issuecomment-733993630

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 5ebc964` and `rancher\rancher:v2.5-head` `version db350a6`

Steps:
Import an EKS cluster.
Enter a cluster name.
Import an EKS cluster with a different name:
![Screen Shot 2020-12-01 at 3 57 42 PM](https://user-images.githubusercontent.com/57409052/100811492-00027880-33f8-11eb-8212-5dd414095946.png)

Result:
Display name is correct in request:
```
eksConfig: {imported: true, displayName: "aaron-eks", region: "us-east-2", type: "eksclusterconfigspec",…}
amazonCredentialSecret: "..."
displayName: "aaron-eks"
imported: true
region: "us-east-2"
type: "eksclusterconfigspec"
```
Cluster is registered with non-display name:
![Screen Shot 2020-12-01 at 4 02 07 PM](https://user-images.githubusercontent.com/57409052/100811480-fc6ef180-33f7-11eb-8791-e701db3ab961.png)
