### ISSUE TITLE
Cannot add Resolving Server

### ISSUE THREAD

**Issue by bibby** [rancher/rancher#3027]
Rancher Server version: 0.50-rc4

While adding a service, I expand *Advanced Options* and open the *Networking* tab. Attempting to add a _Resolving Server_ will throw a javascript error, and expected UI components do not expand.

```
Uncaught Error: <ui@component:form-networking::ember1238> had no action handler for: addDns
```

Edit: Browser: Chromium Version 45.0.2454.101 Ubuntu 14.04 (64-bit)

**Comment by vincent99** [comment]
@bibby d'oh.. thanks.

**Comment by tfiduccia** [comment]
error - Uncaught Error: <ui@component:form-networking::ember18445> had no action handler for: addDns

**Comment by schuylr** [comment]
Is this fixed in a release yet? I'm still reproducing the problem in v0.50.2

**Comment by deniseschannon** [comment]
@schuylr No, it's still in resolved. When it's closed, it's officially in a release and someone on the team will have verified it.

**Comment by deniseschannon** [comment]
In Master 12/21, expanding on the resolving server, opens the dialogue. 

But if you try to click on the "X" to remove a line, it doesn't remove it.

**Comment by deniseschannon** [comment]
Verified the + and x are working in UI v0.77.0 and master build.
