### ISSUE TITLE
Can not create secrets with dot in the name using Rancher UI.

### ISSUE THREAD

**Issue by ranchersvet** [rancher/rancher#30277]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Try to create a secret using Rancher UI and name the secret with a name that contains a dot "." like `tt.test`

**Result:**
You will fail with an error message:
"Name" contains an invalid character. . 
**Other details that may be helpful:**
Using kubectl secrets is created without problems.

`` kubectl create secret tls tt.test --cert=one.pem --key=one.key``
``secret/tt.test created
``
The issue is like issue [#25955](https://github.com/rancher/rancher/issues/25955)
This one is reported in version 2.4.8

gz#13612

**Comment by Ellenqs** [comment]
Tested this on Rancher `v2.4.8` and `v2.5.5`

**Steps**:

- Deploy rancher single install.
- In ember UI, go to default project, create a secret naming with dot -> "sec.test", "sec.t.t".

**Result:**
Secret created successfully. There is no error message.

![Screen Shot 2021-02-01 at 4 01 55 PM](https://user-images.githubusercontent.com/75277058/106533468-15069100-64a7-11eb-8f2b-08427016001a.png)

Additional test:
Name the secret with two continuous dots ".." such as "tt..test", it will have an error:
<img width="437" alt="Screen Shot 2021-02-01 at 3 24 10 PM" src="https://user-images.githubusercontent.com/75277058/106530724-ba1e6b00-64a1-11eb-9b69-2e0d94870027.png">

**Comment by ryansann** [comment]
I tested this on `release/v2.4 HEAD` and `release/v2.5 HEAD` and am able to successfully create a secret with name: `hello.world`. There doesn't appear to be anything to fix here.

**Comment by sowmyav27** [comment]
@Ellenqs Can you validate this issue on 2.5-head and 2.4-head and close it out?

**Comment by Ellenqs** [comment]
Validated this on rancher `v2.4-4847-head,` and `2.5-head,4cb2ebe`.

Do same steps on the two versions:
**Steps:**

- Deploy rancher single install.
- In ember UI, go to default project, create a secret naming with dot.

**Results**
Secret created successfully.

**Result on v2.4-head:**
![Screen Shot 2021-02-09 at 12 10 50 PM](https://user-images.githubusercontent.com/75277058/107429520-dbeaa400-6ad8-11eb-8ecd-32108e48b7c9.png)
**Result on v2.5-head:**
![Screen Shot 2021-02-09 at 12 11 36 PM](https://user-images.githubusercontent.com/75277058/107429527-ddb46780-6ad8-11eb-972d-6838e6d33e57.png)

**Comment by ranchersvet** [comment]
I did some additional research, the secrets can be created, it fails when you try to add the certificate. 
![cert-with-dot](https://user-images.githubusercontent.com/67922252/107715575-3597cd80-6c95-11eb-8a24-f0bd21a2234e.png)
