### ISSUE TITLE
[2.5.2] Cluster health check failed: cluster agent is not ready

### ISSUE THREAD

**Issue by tandaly** [rancher/rancher#30285]
[2.5.2] Cluster health check failed: cluster agent is not ready

![image](https://user-images.githubusercontent.com/3762187/100735269-e9661c80-340b-11eb-853d-01198602b94d.png)

**Comment by superseb** [comment]
The output of the following commands can help diagnose the issue:

* `docker ps -a` from controlplane and worker
* Output of `docker ps -a -q --filter "label=io.kubernetes.container.name=cluster-register" | while read container; do echo "=> $container"; docker logs $container; done` (this container runs on one of the nodes)
* If the error is the same (`Could not resolve host`), please try manual DNS resolution:
  - Run `dig rancher.yourdomain.com @10.43.0.10` on controlplane
  - Run `dig rancher.yourdomain.com @10.43.0.10` on worker
* `docker logs $(docker ps -q -f label="io.kubernetes.container.name"=coredns)`

**Comment by xiliangMa** [comment]
I have same problem by ranhcer v2.5.5.
`Cluster health check failed: cluster agent is not ready`

**Comment by niusmallnan** [comment]
This PR can fix this issue: https://github.com/rancher/rancher/pull/31039
I think 2.5.6 can address this issue.

**Comment by superseb** [comment]
@xiliangMa Please file a new issue with all the requested info from the issue template.

**Comment by phoenix-young** [comment]
> * dig rancher.yourdomain.com @10.43.0.10

Same Issue

When I try dig myrancher.domain.com it's ok
But if i try dig myrancher.domain.com @{ip} it is not ok and with following output:
;; global options: +cmd
;; connection timed out; no servers could be reached
