### ISSUE TITLE
Support Keycloak using OIDC

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30280]
Please list the breakdown tickets below:

https://github.com/rancher/rancher/issues/30675
https://github.com/rancher/rancher/issues/30676

**Comment by cbron** [comment]
@izaac @richard-cox backend has merged, UI already merged AFAIK. There may be some backend changes in future but we will track what those are and how to test them, we should start QA now/soon to see if there are larger problems.

**Comment by izaac** [comment]
https://github.com/rancher/rancher/issues/33036

**Comment by izaac** [comment]
Remaining issues update: 

https://github.com/rancher/rancher/issues/33337
https://github.com/rancher/rancher/issues/33314

**Comment by izaac** [comment]
We're missing here the secure http certificate ready keycloak to test the certificates fields part of the Dashboard issue: https://github.com/rancher/dashboard/issues/2191
Most of the testing was done as part of https://github.com/rancher/rancher/issues/30280
Latest rancher build tested: `2.6 master-head (07/01/2021)` _c1151f6_

**Comment by izaac** [comment]
We want this issue to be fixed first to do a final round of QA using only the Dashboard UI
https://github.com/rancher/dashboard/issues/3588

**Comment by izaac** [comment]
Rancher version: `2.6-head (08/10/2021)` _723f747_

The dashboard issue is not a blocker and it was validated today, a validation pass was done to check site, cluster and project access.

A nestedgroup issue was identified in the process and tracked as a separate issue as it's not Keycloak specific.
https://github.com/rancher/rancher/issues/34142
