### ISSUE TITLE
Add built-in OTC CCE driver

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30297]

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version ff16903` and `rancher\rancher:v2.5-head` `version 8d759be`

OTC CCE driver is available under Global > Tools > Drivers
Cluster driver:
![Screen Shot 2020-12-09 at 11 37 06 AM](https://user-images.githubusercontent.com/57409052/101672389-0bb2f800-3a13-11eb-9001-39a29333ea31.png)
Node driver:
![Screen Shot 2020-12-09 at 11 36 31 AM](https://user-images.githubusercontent.com/57409052/101672402-0eade880-3a13-11eb-83a7-5c1a965cee3b.png)
Create cluster UI:
![Screen Shot 2020-12-09 at 11 37 23 AM](https://user-images.githubusercontent.com/57409052/101672411-11104280-3a13-11eb-870b-d92fbcc76149.png)

**Comment by sowmyav27** [comment]
Keeping this issue open to get a confirmation if the backend has been validated.

**Comment by vladimirhasko** [comment]
Hello Maggie,

Could you please check https://github.com/rancher/ui/pull/4317/files ? 
We were expecting that our container cluster driver name will be properly displayed  in Add Cluster section but we currently see only "Otcce" name. We would like to see there "Open Telekom Cloud" name.
Is there any other pull request needed for changing this name or why we don't see it?
![cluster_name](https://user-images.githubusercontent.com/32979462/101914331-78b9bf80-3bc4-11eb-8977-0f9aa3ca56e6.jpg)

**Comment by maggieliu** [comment]
@westlywright can you help with the question ^^

**Comment by westlywright** [comment]
@vladimirhasko The OTC driver UI is hosted externally. I peaked at the source and its using the raw string not the translation. It will need to be updated by the party responsible for hosting the component. (

**Comment by outcatcher** [comment]
@westlywright Isn't translation added in https://github.com/rancher/ui/pull/4317 enough?

**Comment by westlywright** [comment]
@outcatcher Terribly sorry, I misunderstood something the other night apparently. There is going to be a couple minor change son my end to ensure this works correctly. I'll get them merged shortly to fix this.

**Comment by westlywright** [comment]
The UI changes have been merged. LMK if there are any more issues with the translation.

**Comment by outcatcher** [comment]
@westlywright Thank you!

**Comment by vladimirhasko** [comment]
many thanks @westlywright , it now shows perfectly.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.4-rc8

* Enabled the node driver
* The full name is shown in the UI
![Screen Shot 2021-01-05 at 10 58 51 AM](https://user-images.githubusercontent.com/21316915/103712887-27f57680-4f78-11eb-8f11-e11ef185df06.png)
