### ISSUE TITLE
[2.4] Enabling monitoring on new cluster gives intermittent 500 errors and object has been modified error 

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30290]
backport for: https://github.com/rancher/rancher/issues/30188

**Comment by jiaqiluo** [comment]
the bug fix is validated on v2.4-4378-head 8e306b57b

see https://github.com/rancher/rancher/issues/30188#issuecomment-737574038 for the testing script.

Run the same script 10 times in a row and do not see the error happen.
