### ISSUE TITLE
[Backup/Restore] Chart version 1.0.3

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#30293]
In 2.5.4 there's a new tag 1.0.3 for backup-restore-operator, for this bug https://github.com/rancher/backup-restore-operator/issues/56
Increment Rancher Backup chart version for this change

**Comment by sowmyav27** [comment]
[This](https://github.com/rancher/backup-restore-operator/issues/56#issuecomment-738816373) Issue has been validated and closed. Backup chart version - 1.0.300
