### ISSUE TITLE
Dockershim depreciation since kubernetes 1.20.0

### ISSUE THREAD

**Issue by Pea13** [rancher/rancher#30307]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

The next kubernetes version (1.20.0) will depreciate dockershim: https://github.com/kubernetes/kubernetes/pull/94624
Has rancher planned something about this ? We still have time but a CRI change needs to be well prepared.

Regards,

**Comment by mitchellmaler** [comment]
I suspect RKE2/federal will come in play here since it supports CRI

**Comment by Pea13** [comment]
More informations about the futur removal here : https://kubernetes.io/blog/2020/12/02/dockershim-faq/

**Comment by rene-demonsters** [comment]
Rancher released a blogpost about it here: https://support.rancher.com/hc/en-us/articles/360053308831-Rancher-Operational-Advisory-Related-to-deprecation-of-dockershim-in-Kubernetes-v1-20

**Comment by catherineluse** [comment]
The support article moved here. https://rancher.zendesk.com/hc/en-us/articles/360053308831-Rancher-Operational-Advisory-Related-to-deprecation-of-dockershim-in-Kubernetes-v1-20

Rancher is going to maintain a fork of cri-dockerd.
https://www.mirantis.com/blog/the-future-of-dockershim-is-cri-dockerd/
