### ISSUE TITLE
Security group section is blank while creating an EKS v2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30301]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create an EKS v2 cluster.
- Give in cluster name --> Credentials, Select EKS role
- Click on Next --> Under Networking section choose Subnet: `Standard: VPC and Subnet are automatically created`
- Click on next.
- Logging and Managed node group section is seen
- From networking section, select `Custom: Choose from your existing VPC and Subnets` radio button
- The security group section is blank

<img width="1452" alt="Screen Shot 2020-12-01 at 7 27 53 PM" src="https://user-images.githubusercontent.com/26032343/100825554-2d0d5600-340d-11eb-9003-0ce4bf21964f.png">

Error in console:
<img width="367" alt="Screen Shot 2020-12-01 at 7 37 52 PM" src="https://user-images.githubusercontent.com/26032343/100825562-2ed71980-340d-11eb-87d5-b87d0df1a314.png">

**Expected Result:**
Security group section should not be blank

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `db350a63b` and master-head commit id: `5ebc9642649`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted EKS v2

**Comment by westlywright** [comment]
The change for this will make the VPC selection uneditable after moving on to the next step. I believe we used to do this for EKS v1 as well (need to verify). Regardless this change will be the one that goes in at this point, changing the code so that the choice can be altered after selected would require a lot of changes and introduce too much risk for regression IMO. If we want to revisit we should do so post 2.5.4.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `b2953cbc` and master-head - commit id: `278c1f988`**

Subnet cannot be changed after selecting one and clicking on Next in the network section while creating an EKS hosted cluster.
