### ISSUE TITLE
ADFS Auth fails with Invalid SAML Attributes

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#30306]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Enable auth with AD then disable and enable auth with ADFS

**Result:**
Invalid SAML Attribute messages, SAML Trace shows that SAML Attributes are in fact fine

Rancher logs indicate a failure to get UPN (also fine in the SAML trace)

No other info is shown to be discovered and the environment has been validated several times for correct settings

**Other details that may be helpful:**
Debug logging in Rancher showed no extra information, equivalent environments configured with ADFS OOTB work

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.8

gz#12724

**Comment by paynejacob** [comment]
Validated on 238e9f21be0554b8c237a1226e337bea0a972c56.  I first configured AD auth and was able to log in.  AD auth was disabled and ADFS was configured.  I was able to login with an ADFS user.

**Comment by anupama2501** [comment]
On 2.5.5 was able to reproduce.
From the global --> authentication --> enable AD auth --> disable AD ---> Enable the ADFS auth and when we try to save, it fails with the error "Invalid SAML Attributes"

**Comment by anupama2501** [comment]
On v2.5-4e48b8a9fbedad498fa21fd00e6e426ab3e13770-head
From Auth providers --> Enable AD and save --> Disable AD and enable ADFS by providing all the details --> Enabling goes through without any error --> Logout and login with ADFS credentials --> Authentication goes through and users are allowed to login

**Comment by anupama2501** [comment]
Changing the label to-test as @paynejacob has provided the commit ID for master-head https://github.com/rancher/rancher/pull/31106

**Comment by anupama2501** [comment]
on master-2dca0c67b48331c23c05c025208bacfc258d45bd-head
From Auth providers --> Enable AD and save --> Disable AD and enable ADFS by providing all the details --> Enabling goes through without any error --> Logout and login with ADFS credentials --> Authentication goes through and users are allowed to login
Log in as standard user --> Able to create a cluster

**Comment by anupama2501** [comment]
Rancher before upgrade v2.5.6
After upgrade : v2.5-fa087c81628de057406608f077d0952bb03cea56-head

Upgrade testcase:

- Create rancher server on v2.5.6
- Upgrade the cluster to v2.5-fa087c81628de057406608f077d0952bb03cea56-head
- Enable AD and disable 
- Enable ADFS, log out and login as a standard user
- Create a cluster as standard user
