### ISSUE TITLE
Logging the sync with Rancher Catalog every 5 minutes fills up your logs.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3031]
Provide a UI way of being able to update the sync with the rancher catalog.

Also, make it so we don't log it in the `docker logs rancherserver` as it fills up your logs even if you haven't done anything.

**Comment by vincent99** [comment]
We're worried about ~100 bytes every 5 minutes ≈ 10MB/year?

**Comment by deniseschannon** [comment]
It just looks like something is wrong in the logs. Someone already posted saying that they see that line fill up their logs after 7 hours and think that it's a bug.

**Comment by will-chan** [comment]
@deniseschannon can you add more to this?  I assume this is not a normal thing  but something that caused the logs to fill up.

**Comment by deniseschannon** [comment]
Nope, the default is to sync with catalog every 5 minutes and log that we are syncing. So yoru logs will quickly fill up with this...

```
time="2015-12-29T03:56:46Z" level=info msg="Pulling the catalog library from the repo to sync any new changes to ./DATA/library" 
time="2015-12-29T04:01:46Z" level=info msg="Pulling the catalog library from the repo to sync any new changes to ./DATA/library" 
time="2015-12-29T04:06:46Z" level=info msg="Pulling the catalog library from the repo to sync any new changes to ./DATA/library" 
time="2015-12-29T04:11:46Z" level=info msg="Pulling the catalog library from the repo to sync any new changes to ./DATA/library" 
time="2015-12-29T04:16:46Z" level=info msg="Pulling the catalog library from the repo to sync any new changes to ./DATA/library" 
time="2015-12-29T04:21:46Z" level=info msg="Pulling the catalog library from the repo to sync any new changes to ./DATA/library" 
time="2015-12-29T04:26:46Z" level=info msg="Pulling the catalog library from the repo to sync any new changes to ./DATA/library" 
time="2015-12-29T04:31:46Z" level=info msg="Pulling the catalog library from the repo to sync any new changes to ./DATA/library" 
time="2015-12-29T04:36:46Z" level=info msg="Pulling the catalog library from the repo to sync any new changes to ./DATA/library"
```

**Comment by vincent99** [comment]
I mean we can move it to debug instead of info if nothing changed, but again, 10MB/year.

**Comment by ibuildthecloud** [comment]
Personally I can't stand this one.  The message should be logged at debug.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher-catalog-service/pull/37
