### ISSUE TITLE
UI issues in "Resize" of PVC

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30316]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**On 2.5-head - commit id: `db350a63b`**

- Deployed a cloud provider AWS enabled setup.
- Add a storage class. allowVolumeExpansion is available on the UI. Default value: Disabled.
- Create a Storage class with `allowVolumeExpansion: enabled`
- create a PVC using this storage class.
- Click on the ellipsis. An option `Resize` is available
<img width="787" alt="Screen Shot 2020-12-02 at 2 14 10 PM" src="https://user-images.githubusercontent.com/26032343/100938085-e8cf9380-34a8-11eb-8718-40cdd340a8c1.png">

**Issue#1**
PVC name has `?` in the end. 

**Issue#2**
The value of "Requested Capacity" from the UI is sent as `requests: {storage: "50Gi"}`. Should this field be renamed as Requested Storage instead as a View in API of the PVC has these `resources.requests.storage` and `capacity.storage` which are I believe two different things.

```
"resources": {
"requests": {
"storage": "25Gi"
},
"type": "/v3/project/schemas/resourceRequirements"
},
"state": "bound",
"status": {
"accessModes": [
"ReadWriteOnce"
],
"capacity": {
"storage": "20Gi"
},
```

**Other details that may be helpful:**
Related to fix in - https://github.com/rancher/rancher/issues/27746

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): **On 2.5-head - commit id: `db350a63b`**
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS node driver

**Comment by PennyScissors** [comment]
I investigated this a little further and found this error (`kubectl describe pvc <pvcName>`) after trying to resize a second time as you described:
```  
Warning  VolumeResizeFailed  102s (x9 over 12m)  volume_expand  (combined from similar events): error expanding volume "default/pvc1" of plugin "kubernetes.io/aws-ebs": AWS modifyVolume failed for vol-02f39449067337c96 with VolumeModificationRateExceeded: You've reached the maximum modification rate per volume limit. Wait at least 6 hours between modifications per EBS volume.
           status code: 400, request id: e4b9070d-6c82-4295-8150-4564b48a6e66
```

**Comment by sadiapoddar** [comment]
Verified on master-head, commit a31eecf and 2.5-head, commit e2e530c
steps used to verify.
1. created a cluster in using "amazon" as a cloud provider and setting  User  IAM policy as RancherK8SUnrestrictedCloudProviderRoleUS 
2. created storage class with enabling "Allow Volume Expansion: enabled
3. Added a persistent volume with a
 workload running on the cluster
4. Tried to resize the PV using UI option and 
5. Notices that both issues have been fixed.
 issue#1 one changed the title from "Resize PVC: volume name?" to "Resize PVC: volume name"
issue#2 the label "Requested Capacity" changed to "Requested Storage"

<img width="550" alt="Screen Shot 2020-12-03 at 3 21 33 PM" src="https://user-images.githubusercontent.com/72409237/101104850-f0626b80-3580-11eb-92d4-97a0e42dac0d.png">
