### ISSUE TITLE
broken pipe

### ISSUE THREAD

**Issue by gzdnb** [rancher/rancher#30322]
*Describe your issue here*

2020/12/03 09:52:30 [ERROR] Error during subscribe write tcp 10.244.1.34:80->10.244.1.1:56480: write: broken pipe

pod的shell也是连接一会，在你不持续输入命令的情况下就会自动断开

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.3` UI: `v2.5.3` |
|Route|`undefined`|

**Comment by judddd** [comment]
我也有相同的错误 请问你解决了吗
