### ISSUE TITLE
Severe Regression in 3.16.1 Calico - Fixed in 3.16.5

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#30324]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Perform a rolling update to etcd (similar to our cluster upgrades) during an update to v1.19

**Result:**
https://github.com/projectcalico/calico/issues/4109

You will very likely hit this bug which causes watcher errors repeatedly and never passed back (they are swallowed by go-calico)

Upgrading to 3.16.5 should resolve this, I propose we update KDM to have a release addressing this bug as it will impact customers looking to move to v1.19

**Other details that may be helpful:**

The customer upgraded to v1.19 at 6pm on the 20th and immediately hit this issue, it took time to build up corresponding with the nature of the bug causing a build-up in watchers

gz#13734

**Comment by sowmyav27** [comment]
On 2.5.2 - 

- Deployed a Canal cluster on 1.18 k8s version - 3 etcd, 1 control and 3 worker nodes. Enabled cluster monitoring.
- Upgraded k8s to 1.19.4-rancher1-1
- No logs seen on calico node and calico-kube-controller pods.
- No increase in metrics after upgrade.

**Comment by sangeethah** [comment]
on rancher server - `v2.5.4-rc4` , `1.19.4-rancher1-2` clusters created with "calico" network uses calico - `v3.16.5` . Automation runs on these clusters succeed.

**Comment by sowmyav27** [comment]
Automation checks on Canal clusters - Node driver look good on `2.5.4-rc4` on `1.19.4-rancher1-2` clusters

**Comment by sowmyav27** [comment]
Closing the issues after https://github.com/rancher/rancher/issues/30324#issuecomment-743783468 and https://github.com/rancher/rancher/issues/30324#issuecomment-743911437 validations
