### ISSUE TITLE
EKS import command should only display if private network is selected and public is not

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#30332]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create an EKS cluster in rancher
2. Select private and public networks
3. Click "Create"

**Result:**
The UI will display an import command. This command shouldn't be displayed because public network was selected.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version a31eecf` and `rancher\rancher:master-head` `version 82a0a33` 

Steps:
Create an EKS cluster in rancher
Select private and public networks
![Screen Shot 2020-12-03 at 12 29 49 PM](https://user-images.githubusercontent.com/57409052/101084215-de75ce00-356a-11eb-9470-05ab1776d6d8.png)
Click "Create"

Result:
UI does not show import command.
Cluster provisions successfully.
