### ISSUE TITLE
First Cluster in Error with "cattle-cluster-agent" not found and doesn't recover. Other clusters with same config come up Active

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#30338]
**What kind of request is this:**
Bug

**Steps to reproduce:**

- Install Rancher 2.5-head (12/03/2020) _e2e530c_
  - This setup is HA RKE behind proxy.
- Provision a single node all roles RKE DO cluster using node template.

**Result:**

`2020/12/03 22:19:00 [ERROR] error syncing 'c-44k5q': handler cluster-deploy: Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (Forbidden): error when retrieving current configuration of: Resource: "rbac.authorization.k8s.io/v1, Resource=clusterroles", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRole" Name: "proxy-clusterrole-kubeapiserver", Namespace: "" from server for: "management-state/tmp/yaml-469034348": clusterroles.rbac.authorization.k8s.io "proxy-clusterrole-kubeapiserver" is forbidden: User "u-argmhnkq2n" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope Error from server (Forbidden): error when retrieving current configuration of: Resource: "rbac.authorization.k8s.io/v1, Resource=clusterrolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding" Name: "proxy-role-binding-kubernetes-master", Namespace: "" from server for: "management-state/tmp/yaml-469034348": clusterrolebindings.rbac.authorization.k8s.io "proxy-role-binding-kubernetes-master" is forbidden: User "u-argmhnkq2n" cannot get resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope Error from server (Forbidden): error when retrieving current configuration of: Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace" Name: "cattle-system", Namespace: "" from server for: "management-state/tmp/yaml-469034348": namespaces "cattle-system" is forbidden: User "u-argmhnkq2n" cannot get resource "namespaces" in API group "" in the namespace "cattle-system" Error from server (Forbidden): error when retrieving current configuration of: Resource: "/v1, Resource=serviceaccounts", GroupVersionKind: "/v1, Kind=ServiceAccount" Name: "cattle", Namespace: "cattle-system" from server for: "management-state/tmp/yaml-469034348": serviceaccounts "cattle" is forbidden: User "u-argmhnkq2n" cannot get resource "serviceaccounts" in API group "" in the namespace "cattle-system" Error from server (Forbidden): error when retrieving current configuration of: Resource: "rbac.authorization.k8s.io/v1beta1, Resource=clusterrolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRoleBinding" Name: "cattle-admin-binding", Namespace: "" from server for: "management-state/tmp/yaml-469034348": clusterrolebindings.rbac.authorization.k8s.io "cattle-admin-binding" is forbidden: User "u-argmhnkq2n" cannot get resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope Error from server (Forbidden): error when retrieving current configuration of: Resource: "/v1, Resource=secrets", GroupVersionKind: "/v1, Kind=Secret" Name: "cattle-credentials-cd2543f", Namespace: "cattle-system" from server for: "management-state/tmp/yaml-469034348": secrets "cattle-credentials-cd2543f" is forbidden: User "u-argmhnkq2n" cannot get resource "secrets" in API group "" in the namespace "cattle-system" Error from server (Forbidden): error when retrieving current configuration of: Resource: "rbac.authorization.k8s.io/v1, Resource=clusterroles", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRole" Name: "cattle-admin", Namespace: "" from server for: "management-state/tmp/yaml-469034348": clusterroles.rbac.authorization.k8s.io "cattle-admin" is forbidden: User "u-argmhnkq2n" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope Error from server (Forbidden): error when retrieving current configuration of: Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment" Name: "cattle-cluster-agent", Namespace: "cattle-system" from server for: "management-state/tmp/yaml-469034348": deployments.apps "cattle-cluster-agent" is forbidden: User "u-argmhnkq2n" cannot get resource "deployments" in API group "apps" in the namespace "cattle-system" Error from server (Forbidden): error when retrieving current configuration of: Resource: "apps/v1, Resource=daemonsets", GroupVersionKind: "apps/v1, Kind=DaemonSet" Name: "cattle-node-agent", Namespace: "cattle-system" from server for: "management-state/tmp/yaml-469034348": daemonsets.apps "cattle-node-agent" is forbidden: User "u-argmhnkq2n" cannot get resource "daemonsets" in API group "apps" in the namespace "cattle-system" Error from server (Forbidden): error when retrieving current configuration of: Resource: "apps/v1, Resource=daemonsets", GroupVersionKind: "apps/v1, Kind=DaemonSet" Name: "kube-api-auth", Namespace: "cattle-system" from server for: "management-state/tmp/yaml-469034348": daemonsets.apps "kube-api-auth" is forbidden: User "u-argmhnkq2n" cannot get resource "daemonsets" in API group "apps" in the namespace "cattle-system" , requeuing`

![Screen Shot 2020-12-03 at 3 27 55 PM](https://user-images.githubusercontent.com/27659/101096274-92cc2000-357c-11eb-8abd-69eb51c56117.png)

**Other details that may be helpful:**

- Additional clusters with same node template and configuration succeed provisioning.

**Environment information**
- Rancher version: `v2.5-head (12/03/2020)` _e2e530c_
- Installation option: HA RKE 

**Cluster information**
- Cluster type: RKE DO
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 8GB and 160 GB HD
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
Might be related to rancher/rancher#30325

**Comment by maggieliu** [comment]
Can we test if this still happens or not? Since the blocker #30325 is fixed

**Comment by maggieliu** [comment]
Waiting for someone from the team to hit this issue again.

**Comment by izaac** [comment]
Rancher version `v2.5.4-rc1`

I've not run into this issue again, I setup a couple of HA RKE behind proxy Rancher servers and I was able to provision clusters without any issue.

I will close this issue and we will keep an eye if we end up with a setup with these symptoms.
