### ISSUE TITLE
How to disable IPv6 on Rancher v2.4.11?

### ISSUE THREAD

**Issue by bor8** [rancher/rancher#30345]
**What kind of request is this (question/bug/enhancement/feature request):**
Question and bug.

**Steps to reproduce (least amount of steps as possible):**
Disable IPv6 on Ubuntu 18.04:
```
sudo sed -i -e 's/GRUB_CMDLINE_LINUX_DEFAULT="maybe-ubiquity"/GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1 maybe-ubiquity"/' /etc/default/grub
sudo sed -i -e 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="ipv6.disable=1"/' /etc/default/grub
sudo update-grub
```
Start build a custom cluster.

**Result:**

```
Logs k8s_weave_weave-net-2s5xp_kube-system_716bab36-d565-47fc-b130-18a14c63eb7a_3
DEBU: 2020/12/04 13:49:31.914678 [kube-peers] Checking peer "XX:XX:XX:XX:XX:XX" against list &{[]}
Peer not in list; removing persisted data
INFO: 2020/12/04 13:49:32.028499 Command line options: map[conn-limit:200 datapath:datapath db-prefix:/weavedb/weave-net docker-api: expect-npc:true host-root:/host http-addr:127.0.0.1:6784 ipalloc-init:consensus=0 ipalloc-range:10.XXX.0.0/16 metrics-addr:0.0.0.0:6782 name:XX:XX:XX:XX:XX:XX nickname:XXX no-dns:true port:6783]
INFO: 2020/12/04 13:49:32.028582 weave  2.6.4
FATA: 2020/12/04 13:49:32.225441 creating bridged fastdp veth pair: setting accept_ra to 0: open /proc/sys/net/ipv6/conf/vethwe-bridge/ accept_ra: no such file or directory
```

**Other details that may be helpful:**
With older version (2.4.2 IIRC) it worked!

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.11
- Installation option (single install/HA): single Docker

**Comment by bor8** [comment]
v2.4.11 - problem
v2.4.10 - problem

v2.4.2 - works

**Comment by bor8** [comment]
It looks repaired. When is weave 2.6.5 and 2.7.0 available in Rancher? Is there any way to get the weave version of a Rancher version out without installing Rancher?

**Comment by cblack34** [comment]
@bor8 you can use system image to change the version of weave pulled.

**Comment by bor8** [comment]
@cblack34 Thank you. But my first question is not answered yet, so when is the new weave version available in Rancher without having to do any pull-ups? Let me explain my second question a bit: I would like to know which Rancher version is associated with which weave version without having to install Rancher.

**Comment by leandrosolagna** [comment]
Same, Just ran into this problem and it would be nice to know which version of Rancher is using which weave version.
