### ISSUE TITLE
Once a day a new agent container gets spawned on every node and is stuck in error "websocket: bad handshake" 

### ISSUE THREAD

**Issue by manuel-koch** [rancher/rancher#30344]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Our cluster suffered expired certificate issue like described in https://github.com/rancher/rancher/issues/26984.
Somehow I managed to fix the problem as described in suggested solutions of ticket, see comment https://github.com/rancher/rancher/issues/26984#issuecomment-718898677 and https://github.com/rancher/rancher/issues/26984#issuecomment-720320606.
But afterwards I noticed that every day a new container gets started on all my cluster nodes, that fails to communicate with rancher server and stays stuck in this connection problem, adding a new container day-by-day.
I removed all nodes and re-added them to the cluster but the problem still exists.

**Result:**

E.g. the spawned container looks like "rancher/rancher-agent:v2.3.2"
and it gets started with the following arguments ( I obfuscated host and token here )

```
 "--server",
"https://<RANCHER_SERVER>",
"--token",
"<TOKEN>",
"--no-register",
"--only-write-certs"
```

and every of those containers contains errors like ( I obfuscated host and token here ):

```
time="2020-12-04T07:48:51Z" level=info msg="Connecting to wss://<RANCHER_SERVER>/v3/connect with token <TOKEN>"
time="2020-12-04T07:48:51Z" level=info msg="Connecting to proxy" url="wss://<RANCHER_SERVER>/v3/connect"
time="2020-12-04T07:48:51Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-4htqn/m-7de9314afa70\" not found" error="websocket: bad handshake"
time="2020-12-04T07:48:51Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2020-12-04T07:49:01Z" level=info msg="Connecting to wss://<RANCHER_SERVER>/v3/connect with token <TOKEN>"
time="2020-12-04T07:49:01Z" level=info msg="Connecting to proxy" url="wss://<RANCHER_SERVER>/v3/connect"
time="2020-12-04T07:49:01Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-4htqn/m-7de9314afa70\" not found" error="websocket: bad handshake"
time="2020-12-04T07:49:01Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2020-12-04T07:49:11Z" level=info msg="Connecting to wss://<RANCHER_SERVER>/v3/connect with token <TOKEN>"
time="2020-12-04T07:49:11Z" level=info msg="Connecting to proxy" url="wss://<RANCHER_SERVER>/v3/connect"
time="2020-12-04T07:49:11Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-4htqn/m-7de9314afa70\" not found" error="websocket: bad handshake"
time="2020-12-04T07:49:11Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
```

**Other details that may be helpful:**

I already remove all nodes and re-added them to the cluster ( and noticed that the used token changed ).
Though the k8s cluster is working normally ( as far as I can say ) I wonder why I still get those agent errors daily that spam nodes filesystem with high frequency logs and spawn containers daily that are stuck in error and don't get stopped/killed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.2
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): v1.15.9

- Docker version (use `docker version`): 19.3.14

![nodes](https://user-images.githubusercontent.com/8177285/101141128-24d33780-3614-11eb-9343-175c905fcfa5.png)

**Comment by initializ-mk** [comment]
Try adding web socket annotation to rancher ingress, mapping to the rancher service:
`kubectl get ing rancher -n cattle-system -o yaml`

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: rancher
    cert-manager.io/issuer-kind: Issuer
    field.cattle.io/publicEndpoints: '[{"addresses":["xx.xx.xx.xx"],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"<rancher.host>","allNodes":false}]'
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: rancher
    meta.helm.sh/release-namespace: cattle-system
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/websocket-services: rancher
    nginx.org/websocket-services: rancher
  creationTimestamp: "2020-12-30T06:12:12Z"
  generation: 1
  labels:
    app: rancher
    app.kubernetes.io/managed-by: Helm
    chart: rancher-2.5.3
    heritage: Helm
    release: rancher
  name: rancher
  namespace: cattle-system
  resourceVersion: "103599298"
  selfLink: /apis/extensions/v1beta1/namespaces/cattle-system/ingresses/rancher
  uid: 02fecf91-ae38-47a9-a3ac-824df210f5d8
spec:
  rules:
  - host: rancher.gke
    http:
      paths:
      - backend:
          serviceName: rancher
          servicePort: 80
  tls:
  - hosts:
    - <rancher.host>
    secretName: tls-rancher-ingress
```

**nginx.ingress.kubernetes.io/websocket-services: rancher**
**nginx.org/websocket-services: rancher**

**Comment by manuel-koch** [comment]
@initializ-mk I can't find any secret named "tls-rancher-ingress" in our cluster ?
And our cluster was not setup using helm ( it looks like you initially deployed this Ingress via a helm chart rancher-2.5.3 )
Our cluster is running from single docker container for rancher server, e.g. 
```
docker run -d --restart=unless-stopped --name rancher-server \
       -p 8080:80 \
       -v /opt/rancher:/var/lib/rancher \
       rancher/rancher:<RANCHER_VERSION> \
       --no-cacerts
```
