### ISSUE TITLE
exact match for hostnames should be given priority over wildcard match.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3035]
Server version - V0.50.0-rc5

Create an LB service with following targets:
 <img width="750" alt="screen shot 2015-12-15 at 3 17 06 pm" src="https://cloud.githubusercontent.com/assets/4266958/11827271/be585362-a33f-11e5-8f8c-c56bc49a0cda.png">

ACL rules get programmed as below in haproxy:

<img width="764" alt="screen shot 2015-12-15 at 3 16 42 pm" src="https://cloud.githubusercontent.com/assets/4266958/11827256/aba66b0a-a33f-11e5-9a5a-7ff8615cd2af.png">

When I try to access LB url "/name.html" with host set to "abc.domain.com"  , i expect to reach services from "test188167".  Instead I reach container in "test961368".

**Comment by alena1108** [comment]
After the fix, the order would be the following:

* not null path and not null non-wildcard domain
* not null non-wildcard domain
*  not null path and not null wildcard domain
* not null wildcard domain
* not null path

**Comment by sangeethah** [comment]
Tested with server version - v0.51.0
Exact match for hostnames is given priority over wildcard matches now.
