### ISSUE TITLE
Missing save/cancel button on the screen for edit cluster when the cluster is imported (including local cluster)

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#30354]
**What kind of request is this:**
Bug

**Steps to reproduce:**

- Create an RKE HA setup. `master-head (12/04/2020)` _a31eecf_
  - This only happens in RKE HA local cluster. k3s single install local cluster is ok.
- After installation the local HA cluster should show up in the UI (As the default Rancher `admin`)
- Edit Local cluster
- Click Member Roles

**Result:**

There's no way to edit the Members here and there's a warning about managing users in this cluster.
However the Members tab in the Cluster navigation bar is active and we can proceed to manage users there.

![Screen Shot 2020-12-04 at 11 29 45 AM](https://user-images.githubusercontent.com/27659/101206039-c5812180-362b-11eb-8cf7-6938a4cbb866.png)

**Other details that may be helpful:**

Should we allow the user to apply changes as how it works with local k3s single install clusters or Disable the Members section for consistency.

### Important
For Fleet RBAC we must manage users on this local cluster to manage **fleetworkspaces**.

**Environment information**
- Rancher version: `master-head (12/04/2020)` _a31eecf_
- Installation option: HA RKE

**Comment by izaac** [comment]
Reproduced in Rancher `v2.5.3` Same behavior.

**Comment by maggieliu** [comment]
Missing save/cancel button on the screen for edit cluster when the cluster is imported (including local cluster)

**Comment by izaac** [comment]
Rancher version `v2.4.11` it has buttons and I can add a user from Cluster edit.

![Screen Shot 2020-12-04 at 1 25 04 PM](https://user-images.githubusercontent.com/27659/101211333-45ab8500-3634-11eb-8504-728b5cea917b.png)

**Comment by izaac** [comment]
Rancher version: `v2.5-head (12/07/2020)` _6ad4dce_
Rancher version: `master-head (12/07/2020)` _a5e40aa_

I am able to see the Save and Cancel buttons in the latest builds.
I am also able to add members to the local cluster from cluster edit.
