### ISSUE TITLE
[Feature request] Helm values as a file path in addition to in-line

### ISSUE THREAD

**Issue by iankittomar** [rancher/rancher#30365]
*I would love to use fleet if it provides Helm values as a file path option*

I don't want to make fleet.yml file more complex and long after inserting big custom.values.yml file.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.3` UI: `v2.5.3` |
|Route|`undefined`|

**Comment by ron1** [comment]
Duplicates https://github.com/rancher/fleet/issues/179
