### ISSUE TITLE
Validate RHEL/CentOS 8.3

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#30375]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.3_release_notes/index
https://lists.centos.org/pipermail/centos-announce/2020-December/035874.html

gz#14177

**Comment by ryebread157** [comment]
Please validate RHEL/CentOS8 with Docker CE 19.03.x as well as 20.10.x, see available releases here: https://download.docker.com/linux/centos/8/x86_64/stable/Packages/

**Comment by superseb** [comment]
Docker 20.10.x is covered in https://github.com/rancher/rancher/issues/30406

**Comment by superseb** [comment]
Duplicate of https://github.com/rancher/rancher/issues/31093
