### ISSUE TITLE
Cluster health check failed: cluster agent is not ready

### ISSUE THREAD

**Issue by amagan424** [rancher/rancher#30378]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
when creating a new cluster facing this issue

**Result:**
it is an in the picture 

**Other details that may be helpful:**

**Environment information**
- Rancher version - 2.5.2
- Installation option - single host

**Cluster information**
- Cluster type - custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
The Machine i am using is an VM and the details of the CPU/memory are as follows:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz
Stepping:              2
CPU MHz:               2593.993
BogoMIPS:              5187.98
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid xsaveopt arat md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities

- Kubernetes version (use `kubectl version`):

<img width="959" alt="rancher" src="https://user-images.githubusercontent.com/75645592/101517284-954cc200-394e-11eb-8263-15d06d671e99.PNG">
the version of kubernetes i am trying to install on VM is v1.17.14

- Docker version (use `docker version`):

```
Client:
 Debug Mode: false

Server:
 Containers: 29
  Running: 15
  Paused: 0
  Stopped: 14
 Images: 11
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765aba0d05254012b0b9e595e995c09186427f
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.6.1.el7.x86_64
 Operating System: Red Hat Enterprise Linux Server 7.8 (Maipo)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 15.49GiB
 Name: vrexkubm-ho-02p.sys.comcast.net
 ID: ICLO:YJHV:IELN:V4BI:4GBT:EY3R:GFUF:FFPV:KSPG:LCH2:FGLW:66MG
 Docker Root Dir: /usr/local/rex/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  docker-interact.g.comcast.net
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled

```

**Comment by amagan424** [comment]
hello i am trying to install in our VM but after installation of everything the cluster says agent is not healthy and fails can someone please help me , we are trying to implement rancher into our production so this is a blocker for us 
thank you

**Comment by superseb** [comment]
The output of the following commands can help diagnose the issue:

* `docker ps -a` from controlplane and worker
* Output of `docker ps -a -q --filter "label=io.kubernetes.container.name=cluster-register" | while read container; do echo "=> $container"; docker logs $container; done` (this container runs on one of the nodes)
* If the error is the same (`Could not resolve host`), please try manual DNS resolution:
  - Run `dig rancher.yourdomain.com @10.43.0.10` on controlplane
  - Run `dig rancher.yourdomain.com @10.43.0.10` on worker
* `docker logs $(docker ps -q -f label="io.kubernetes.container.name"=coredns)`

**Comment by amagan424** [comment]
@superseb here is the information you asked for 

 1) docker ps -a output from my controlplane host:
```

CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                     PORTS                                      NAMES
2ee78592e761        444dfdf0ae3c                          "run.sh"                 3 minutes ago       Exited (1) 2 minutes ago                                              k8s_cluster-register_cattle-cluster-agent-65768974cb-6xnmh_cattle-system_1661d680-60a5-4f00-b577-5877a0618e61_11
c1fee0d23369        444dfdf0ae3c                          "run.sh"                 24 minutes ago      Up 24 minutes                                                         k8s_agent_cattle-node-agent-9v4sx_cattle-system_dd2c8b14-6fa6-4651-b5a9-b7a7a8cb52a4_0
7582f225d088        rancher/pause:3.1                     "/pause"                 24 minutes ago      Up 24 minutes                                                         k8s_POD_cattle-node-agent-9v4sx_cattle-system_dd2c8b14-6fa6-4651-b5a9-b7a7a8cb52a4_0
76c0b251ef38        96148b821282                          "/bin/sh -c 'kube-ap…"   24 minutes ago      Up 24 minutes                                                         k8s_kube-api-auth_kube-api-auth-7t4vq_cattle-system_4e8d6c7d-3c02-4eae-bb8d-25d71b4c7247_0
283f0ec426af        rancher/pause:3.1                     "/pause"                 24 minutes ago      Up 24 minutes                                                         k8s_POD_kube-api-auth-7t4vq_cattle-system_4e8d6c7d-3c02-4eae-bb8d-25d71b4c7247_0
a3ccc5ce0dc7        rancher/pause:3.1                     "/pause"                 38 minutes ago      Up 38 minutes                                                         k8s_POD_cattle-cluster-agent-65768974cb-6xnmh_cattle-system_1661d680-60a5-4f00-b577-5877a0618e61_0
fc67ffbe0d79        rancher/rancher-agent:v2.5.2          "run.sh -- share-roo…"   41 hours ago        Exited (0) 41 hours ago                                               share-mnt
73a15bffc5be        rancher/coreos-flannel                "/opt/bin/flanneld -…"   41 hours ago        Up 41 hours                                                           k8s_kube-flannel_canal-ntj6k_kube-system_763313d7-a497-46dc-95c0-b7173101f9ea_0
9669823e9f48        rancher/calico-node                   "start_runit"            41 hours ago        Up 41 hours                                                           k8s_calico-node_canal-ntj6k_kube-system_763313d7-a497-46dc-95c0-b7173101f9ea_0
66255a417db3        rancher/calico-pod2daemon-flexvol     "/usr/local/bin/flex…"   41 hours ago        Exited (0) 41 hours ago                                               k8s_flexvol-driver_canal-ntj6k_kube-system_763313d7-a497-46dc-95c0-b7173101f9ea_0
7cb1cd80e28e        rancher/calico-cni                    "/install-cni.sh"        41 hours ago        Exited (0) 41 hours ago                                               k8s_install-cni_canal-ntj6k_kube-system_763313d7-a497-46dc-95c0-b7173101f9ea_0
bbc3d49835c2        rancher/pause:3.1                     "/pause"                 41 hours ago        Up 41 hours                                                           k8s_POD_canal-ntj6k_kube-system_763313d7-a497-46dc-95c0-b7173101f9ea_0
8ba73527fc54        rancher/hyperkube:v1.17.14-rancher1   "/opt/rke-tools/entr…"   41 hours ago        Up 41 hours                                                           kube-proxy
14958ea4f9f5        rancher/hyperkube:v1.17.14-rancher1   "/opt/rke-tools/entr…"   41 hours ago        Up 41 hours                                                           kubelet
899226031a3c        rancher/hyperkube:v1.17.14-rancher1   "/opt/rke-tools/entr…"   41 hours ago        Up 41 hours                                                           kube-scheduler
8f8158d08df6        rancher/hyperkube:v1.17.14-rancher1   "/opt/rke-tools/entr…"   41 hours ago        Up 41 hours                                                           kube-controller-manager
435ada42bb15        rancher/hyperkube:v1.17.14-rancher1   "/opt/rke-tools/entr…"   41 hours ago        Up 41 hours                                                           kube-apiserver
968ceb23d41d        rancher/rke-tools:v0.1.66             "/bin/bash"              41 hours ago        Created                                                               service-sidekick
775ec7a8c6df        rancher/coreos-etcd:v3.4.3-rancher1   "/usr/local/bin/etcd…"   41 hours ago        Up 41 hours                                                           etcd
8a40c6499664        rancher/rke-tools:v0.1.66             "/docker-entrypoint.…"   41 hours ago        Exited (0) 41 hours ago                                               cluster-state-deployer
b5c7b37c1409        rancher/rancher:v2.5.2                "entrypoint.sh"          41 hours ago        Up 41 hours                0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   angry_hertz

```

2) the output of **docker ps -a -q --filter "label=io.kubernetes.container.name=cluster-register" | while read container; do echo "=> $container"; docker logs $container; done**
[root@vrexkubm-ho-01p ~]# docker ps -a -q --filter "label=io.kubernetes.container.name=cluster-register" | while read container; do echo "=> $container"; docker logs $container; done
=> 2ee78592e761
INFO: Environment: CATTLE_ADDRESS=10.42.0.4 CATTLE_CA_CHECKSUM=68b122d58279a28eaf079c63921c67597deecc846cd1130c1670f1c549609aa3 CATTLE_CLUSTER=true CATTLE_FEATURES= CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=true CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-65768974cb-6xnmh CATTLE_SERVER=https://vrexkubm-ho-01p.sys.comcast.net
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local sys.comcast.net cable.comcast.com ula.comcast.net options ndots:5
ERROR: https://vrexkubm-ho-01p.sys.comcast.net/ping is not accessible (Could not resolve host: vrexkubm-ho-01p.sys.comcast.net)

3) the host i am currently using is a controlplane and an etcd node not an worker node

[root@vrexkubm-ho-01p ~]# dig rancher.yourdomain.com @10.43.0.10

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.2 <<>> rancher.yourdomain.com @10.43.0.10
;; global options: +cmd
;; connection timed out; no servers could be reached


4) **there seems to be no container with coredns i don't see any logs can you please help**

**Comment by superseb** [comment]
CoreDNS pods run on the workers and could indicate why there is no DNS resolving in the cluster. Are the hosts running firewalld?

**Comment by amagan424** [comment]
@superseb to add a worker as well my cluster is not coming up it is failing to create a cluster itself

**Comment by superseb** [comment]
@amagan424 Either add a node with all roles as first node or edit the cluster and run the `docker run` command at the bottom on an extra node with the worker role so that the needed system add-ons can run.

**Comment by amagan424** [comment]
@superseb i was able to fix the cluster agent it is just that inorder to create a successfull cluster in Rancher v2.5.2 i just needed to make sure that we have both controlplane and worker nodes added , i just did that and the issue has been solved

thank you for immediate response i am going ahead and closing the issue

**Comment by amagan424** [comment]
the issue resolved by adding worker node
