### ISSUE TITLE
Pod logs are not displayed if accessed via cluster explorer

### ISSUE THREAD

**Issue by ranchersvet** [rancher/rancher#30372]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Pod logs in rancher UI can be accessed via the classical UI. 
Switch to Cluster Explorer UI navigate to the same pod and try to access the logs the page will be white.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): single install

gz#13802

**Comment by gaktive** [comment]
For those of you following this ticket, this should be resolved with 2.6.1 via https://github.com/rancher/dashboard/issues/4220
