### ISSUE TITLE
Upping a service after forcefully removing not longer works

### ISSUE THREAD

**Issue by dsvmacdonald** [rancher/rancher#3037]
After using Rancher Compose to up a service and then forcefully removing it, upping it again fails  with message:

Failed Creating rabbit : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name] from [http://xxx.xxx.xxx.xxx:8080/v1/services] 

In Rancher UI, services are still listed (as previous version).  When I delete the services from the UI and then try tor upping the service via Rancher Compose, it works.

FYI - I manually passed in stack name in all Rancher Compose operations

Rancher version: 0.50
Rancher Compose Version: 0.6.2

**Comment by alena1108** [comment]
The fix is coming shortly, the current workaround - remove the entire stack and recreate it from the compose (I believe its what you did when you removed all the services from the UI and upped the stack in the compose)

**Comment by sangeethah** [comment]
Tested with rancher server version - v0.50.1-rc1
Upping a service after forcefully removing it  works as expected.

```
Sangeethas-MacBook-Pro:rancher-compose-v0.6.2 sangeethahariharan1$ ./rancher-compose -p hello -f dc-1.yml -r rc-1.yml up
INFO[0000] Creating stack hello                         
INFO[0000] Creating service test1                       
INFO[0001] Project [hello]: Starting project            
INFO[0001] [0/1] [test1]: Starting                      
INFO[0006] [1/1] [test1]: Started                       
INFO[0006] Project [hello]: Project started             
Sangeethas-MacBook-Pro:rancher-compose-v0.6.2 sangeethahariharan1$ ./rancher-compose -p hello -f dc-1.yml -r rc-1.yml rm --force
INFO[0000] Project [hello]: Deleting project            
INFO[0000] [0/1] [test1]: Deleting                      
INFO[0000] [0/1] [test1]: Deleted                       
Sangeethas-MacBook-Pro:rancher-compose-v0.6.2 sangeethahariharan1$ ./rancher-compose -p hello -f dc-1.yml -r rc-1.yml up
INFO[0000] Creating service test1                       
INFO[0001] Project [hello]: Starting project            
INFO[0001] [0/1] [test1]: Starting                      
INFO[0007] [1/1] [test1]: Started                       
INFO[0007] Project [hello]: Project started    
```
