### ISSUE TITLE
Use Engine Environment variables when provisioning a node

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/rancher#30408]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Have Rancher and a downstream nodedriver cluster in an environment where proxy is required to access the internet.
Deploy node in the downstream cluster using a node template that defines proxy environment variables via Engine Environment

**Result:**
The environment variables defined in the template are not used when Rancher attempts to install docker on the node with `sh -c 'if ! type docker; then curl -sSL https://releases.rancher.com/install-docker/19.03.sh | sh -; fi`. 
This can cause the install to hang and provisioning to timeout unless these environment variables are defined in /etc/environment, either via cloud-config, or baked into an image.

**Other details that may be helpful:**
These environment variables are added to a service override for docker. It would be ideal if they were used in the initial deployment, and perhaps an optional checkbox to add these variables to /etc/environment at provisioning. This would allow operators to deploy a node entirely from Rancher using standard images, without any image building process

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.x -> v2.5.3
- Installation option (single install/HA): 

gz#13697
SURE-2627

**Comment by superseb** [comment]
Sounds the same as https://github.com/rancher/rancher/issues/13206

**Comment by slickwarren** [comment]
I was able to reproduce this on 2.6-head (931a0f0) by doing the following:
* deploy a proxied rancher setup (rancher only has internet access through proxy)
* define proxy in `node template` -> `engine options` -> `engine environment` for http_proxy, https_proxy, no_proxy
* deploy the cluster
  * even if you define proxy env. vars in the cluster (under `advanced options`), the cluster fails to come to an active state. 


a potential workaround; for custom nodes, you can login to the node and define the docker proxy settings, which allows the node to provision with the proxied rancher cluster.

**Comment by deniseschannon** [comment]
Engineering will never update to make this enhancement due to the varying OSes that would need to be supported for this use case. 

Recommendation would be to use either cloud config or a built-in image that has the proxy environment variables configured on the host.
