### ISSUE TITLE
No ingress when using RKE v1.2.4-rc2 and Rancher v2.5-head on HA infrastructure

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#30405]
**What kind of request is this:**
Bug

**Steps to reproduce:**

- Follow the RKE HA install docs and try provisioning Rancher in it
- Rancher chart used `v2.5.4-rc2` and image override to `v2.5-head`

`helm_v3 install rancher rancher-latest/rancher --version 2.5.4-rc2 --namespace cattle-system --set hostname=<hostname> --set ingress.tls.source=secret --set rancherImageTag=v2.5-head`

**Result:**

Rancher is provisioned but there isn't ingress-nginx namespace created thus no access to Rancher.

**Environment information**
- Rancher version: `v2.5-head (12/09/2020)`
- Installation option: HA RKE
- RKE version: v1.2.4-rc2  

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

Might be related to: https://github.com/rancher/rancher/issues/25590

**Comment by nickgerace** [comment]
Pending new RC from @paynejacob to see if this solves itself.
Reference: https://github.com/rancher/rke/pull/2373

**Comment by izaac** [comment]
@nickgerace new RKE or Rancher RC?

**Comment by nickgerace** [comment]
Both since the RKE RC would need to vendored into Rancher.

**Comment by nickgerace** [comment]
Moving back to QA since this issue may be resolved once the next RKE RC is in 2.5-head (needs this commit: https://github.com/rancher/rke/pull/2373)

**Comment by nickgerace** [comment]
`rke v1.2.4-rc3` is out.

**Comment by izaac** [comment]
This is working with rke `v1.2.4-rc3` 

Rancher version `v2.5.4-rc3`
Rancher version `v2.5-head (12/10/2020)` _3463f5a_
