### ISSUE TITLE
Validate Docker 20.10.x

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#30406]
https://docs.docker.com/engine/release-notes/#version-2010
https://github.com/moby/moby/releases/tag/v20.10.1

* Update `install-docker` script to latest and use `VERSION` environment variable to set version
* Validate all setups with Docker with the latest version

**Comment by immanuelfodor** [comment]
In the meantime, I used `rke up --ignore-docker-version` as a temporal workaround to bring up the cluster after the Docker 20.10.0 update. It works fine on Centos Stream (upgraded from CentOS 8) with Docker packages from https://download.docker.com/linux/centos/8/x86_64/stable/Packages/ and `firewalld` disabled.

```bash
$ containerd -v
containerd containerd.io 1.4.3 269548fa27e0089a8b8278fc4fc781d7f65a939b

$ docker version
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:59:27 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:57:25 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

**Comment by mcmcghee** [comment]
I can confirm everything _appears_ to be working fine on 20.10.1 w/ Ubuntu 18.04.

**Comment by deniseschannon** [comment]
@rawmind If you have any questions on how to work on this, please contact @superseb

**Comment by rawmind** [comment]
@deniseschannon I have no questions but maybe @rawmind0 has ones. 😉

**Comment by rawmind0** [comment]
PR merged and https://releases.rancher.com/install-docker/20.10.sh published

**Comment by rawmind0** [comment]
Updated KDM with PR https://github.com/rancher/kontainer-driver-metadata/pull/478

**Comment by sadiapoddar** [comment]
Tried the task on 2.5-head, commit 5f3fcb8
1. installed 20.10.2 docker on ther rancher server
2. pulled the image of 2.5-head, commit v2.5-5f3fcb8433
3. During creating node template don't see the docker 20.10.2.sh is listed as the default one for the users and current default is 19.3.sh

<img width="1264" alt="Screen Shot 2021-02-03 at 11 31 40 AM" src="https://user-images.githubusercontent.com/72409237/106799316-f83b9c00-6613-11eb-8838-f8665707458c.png">
4. if users pull the latest during creating node template it installed 20.10.3 on the downstream node

**Comment by sadiapoddar** [comment]
Verified on 2.5-head, df89971b, and master-head fbe2c30
On vSphere, Azure, and Amazone cloud provider
1. created node template by selecting the docker engine installation default script "https://releases.rancher.com/install-docker/20.10.sh"
2. Deployed cluster using the node template created 
3. Verified the cluster nodes docker version was 20.10.x version

There was an issue during cluster deployment on Linode and Digital Ocen provider using node template with docker version 20.10.x. 

We are tracking the issue by
https://github.com/rancher/rancher/issues/31151

**Comment by rawmind0** [comment]
@sadiapoddar , the fix for the issue https://github.com/rancher/rancher/issues/31151 is already merged and to be tested, https://github.com/rancher/rancher/issues/31151#issuecomment-777588258
