### ISSUE TITLE
Can't select groups with Okta integration

### ISSUE THREAD

**Issue by tl-Quentin-Cloarec** [rancher/rancher#30401]
We recently upgraded rancher to v2.5.3 and it messed with our Okta SAML integration.

Groups and users that were mapped before the upgrade are still there and working.

However, when trying to `add member` to a project/namespace we don't have any group showing in the drop-down.

![Screenshot 2020-12-09 at 16 05 46](https://user-images.githubusercontent.com/66247216/101654555-94905a80-3a38-11eb-9200-67eab66b0034.png)

I ran a SAML-tracer and found out that the request sent by rancher

`https://myranchermaster/v1-saml/okta/saml/acs`

 returns all the correct groups.

We've also tried to delete/recreate the SAML integration without success.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.3` UI: `v2.5.3` |
|Route|`undefined`|

gz#16100

**Comment by tl-Quentin-Cloarec** [comment]
we manage to fix this by using the API/terraform. 

It's still not working on the UI.

**Comment by fabiograssofy** [comment]
Hello,
we have the same issue on 2.5.5. The SAML assertion contains the groups, but they're note present in Rancher. The groups drop-down is empty.


Example of SAML assertion:

`<saml2:Attribute Name="groups"
                       NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
        <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                              xsi:type="xs:string">Group1</saml2:AttributeValue>
        <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                              xsi:type="xs:string">Group2</saml2:AttributeValue>
        <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                              xsi:type="xs:string">Group3</saml2:AttributeValue>
							  ... and so on ...
      </saml2:Attribute>`

It will be useful to use groups from SAML assertion, so any help will be appreciated.

Thanks

**Comment by izaac** [comment]
Reproduced in 2.5.5

**Comment by izaac** [comment]
Rancher version `v2.5.5`
Rancher version `v2.5-head (03/03/2021)`  _5a5c039_

The API UI show the groups in both versions. Ember isn't.

![Screen Shot 2021-03-03 at 4 37 16 PM](https://user-images.githubusercontent.com/27659/109887560-2fb35d80-7c3f-11eb-85cb-4feb705f586f.png)

**Comment by izaac** [comment]
Do we need a `v2.5` PR too for this? @westlywright @codyrancher

**Comment by westlywright** [comment]
@izaac I cherry-picked it back to master for Cody. Its in 2.5-head already.

**Comment by izaac** [comment]
@westlywright got it, thank you!

**Comment by izaac** [comment]
Rancher version: `v2.5-head (04/19/2021)`  _a0eebbb_
Rancher version: `master-head (04/19/2021)`  _1c3629f_

Validated that groups are populated in the Ember UI.
