### ISSUE TITLE
Rancher 2.5 Shell size (columns) limited to 80 

### ISSUE THREAD

**Issue by bramamad** [rancher/rancher#30402]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Use "Execute Shell" to a POD or Container

**Result:**
There are only 80 columns usable in terminal window. - With kubectl exec we have normally 178 columns.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5
- Installation option (single install/HA): single 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by lumachan** [comment]
I can confirm this behaviour (Rancher 2.5.3).

Works nice in Rancher 2.4.X.

Would be nice to have a fix.

**Comment by starDemo** [comment]
same question ,wait for a fix

**Comment by felixng1028** [comment]
same question ,wait for a fix

**Comment by magiccommon** [comment]
same

**Comment by Hitesh-Agrawal** [comment]
Yeah waiting for a fix, its really cumbersome.

**Comment by vj-gsr** [comment]
Same here. this is kinda annoying.

**Comment by felixng1028** [comment]
Same here.

**Comment by orsi-dev** [comment]
same here

**Comment by Hitesh-Agrawal** [comment]
Any update guys, this is really annoying..

**Comment by slickwarren** [comment]
validated on 2.5-head (23a29c306a1279cb1aa124f41992508ff60b508a) and master-head  (41045a8bd742ca24c69dc3a9d54a1888686c0159)
* overflow no longer occurs
<img width="1637" alt="Screen Shot 2021-01-22 at 11 44 31 AM" src="https://user-images.githubusercontent.com/16691014/105537873-6fce0a80-5ca7-11eb-8b0a-65ce0af7c96b.png">

**Comment by slickwarren** [comment]
verified still broken on 2.5.5:
* limit to 80 characters (no overflow for system shells) 
<img width="101" alt="Screen Shot 2021-01-22 at 12 04 05 PM" src="https://user-images.githubusercontent.com/16691014/105539770-0bf91100-5caa-11eb-9143-bad49f456001.png">
<img width="591" alt="Screen Shot 2021-01-22 at 12 00 07 PM" src="https://user-images.githubusercontent.com/16691014/105539551-c2102b00-5ca9-11eb-84fe-60340d5ebcad.png">
* overflow issue + limit to 80 characters when user/hostname not truncated 
<img width="697" alt="Screen Shot 2021-01-22 at 12 03 36 PM" src="https://user-images.githubusercontent.com/16691014/105539937-482c7180-5caa-11eb-9223-5ad418c8bae4.png">

**Comment by sunliusi** [comment]
any update?

**Comment by starDemo** [comment]
v2.5.6 can fix it?

**Comment by slickwarren** [comment]
yes, this will be fixed in 2.5.6
