### ISSUE TITLE
Am not getting relationship data back from api for Secrets & Configmaps

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#30413]
**Steps to reproduce (least amount of steps as possible):**
1.  Create a Secret and a Config map
2. Create a deployment that references that secret & Config map in the environment variables section
3. Go to secret & config map detail pages and look at related resources

**Result:**  Nothing show up in related resource.  Should show deployment

**Comment by anupama2501** [comment]
Able to reproduce this on 2.5.5:

- From cluster explorer --> Secrets --> Add secret [add key-value pair]
- From cluster explorer --> config maps --> Add configmap [add key-value parir]
- Now from deployments --> Create deployment --> add image, environment variables [add variables] select the config map and secret created in the above step
- Once the deployment is active --> secrets/config maps --> click on the added secret/config map and in related resources tab no workloads seen
On dashboard:
<img width="300" alt="Screen Shot 2021-04-02 at 10 45 50 AM" src="https://user-images.githubusercontent.com/38144301/113440106-9f347e00-93a0-11eb-82ce-8f81c5b0b0ce.png">



On ember UI:
<img width="300" alt="Screen Shot 2021-04-02 at 10 44 15 AM" src="https://user-images.githubusercontent.com/38144301/113439994-70b6a300-93a0-11eb-82b6-76b9c135145a.png">

**Comment by anupama2501** [comment]
Verified the issue on : v2.5-bdec2f2a84e6dc5bca61b727ca5306174c816f33-head
From cluster explorer --> Config maps --> create a config map with key/value pair 
Create a secret key/value pair
From the deployments --> create a workload with env variables --> configmap/secret key attached created from the above step
Now if we verify the cluster explorer --> Config maps/secrets --> click on the created configmap --> related resources has the workload 
<img width="300" alt="Screen Shot 2021-04-02 at 3 38 06 PM" src="https://user-images.githubusercontent.com/38144301/113459213-96a46d80-93c9-11eb-8e1d-b29f74c4cb75.png">

**Comment by anupama2501** [comment]
Re-opening the issue for master-head PR

**Comment by deniseschannon** [comment]
This doesn't need a PR for master-head unless it is broken. 

Wrangler is updated fairly frequently on master-head automatically. 

Can you test this out @anupama2501 ?
