### ISSUE TITLE
rancher compose with dollar sign

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#3041]
How i can add dollar sign to metadata in rancher-compose.yml

add some string :)
![screenshot 16](https://cloud.githubusercontent.com/assets/4653589/11844804/72269f28-a432-11e5-9962-48d2ad8daf2b.png)

and in result :(
![screenshot 17](https://cloud.githubusercontent.com/assets/4653589/11844806/74dda932-a432-11e5-845b-8865d9ce8e7b.png)

**Comment by andyshinn** [comment]
According to the Docker Compose documentation, you use two `$` to have a literal `$`: https://docs.docker.com/compose/compose-file/#variable-substitution.

**Comment by Negashev** [comment]
@andyshinn It's not help

i write: kernel: "$$VAR_NOT_INTERPOLATED_BY_COMPOSE"
![screenshot 19](https://cloud.githubusercontent.com/assets/4653589/11862560/4cba8f48-a4ae-11e5-8853-a7f6180e36dc.png)

and i write:   kernel: "${VAR_NOT_INTERPOLATED_BY_COMPOSE}"
![screenshot 20](https://cloud.githubusercontent.com/assets/4653589/11862567/6a7e9038-a4ae-11e5-924e-fe057146febe.png)

**Comment by Negashev** [comment]
kernel: "\$VAR_NOT_INTERPOLATED_BY_COMPOSE"
![screenshot 21](https://cloud.githubusercontent.com/assets/4653589/11862617/fcae6438-a4ae-11e5-9395-3a2f8e01190e.png)

**Comment by Negashev** [comment]
It's work!

i write: kernel: "$$VAR_NOT_INTERPOLATED_BY_COMPOSE"

![screenshot 19](https://cloud.githubusercontent.com/assets/4653589/11862560/4cba8f48-a4ae-11e5-8853-a7f6180e36dc.png)
