### ISSUE TITLE
Certifcate information in Kubeconfig File screen shows '+' as '&#43;'

### ISSUE THREAD

**Issue by jmkelm08** [rancher/rancher#30412]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
From the cluster dashboard page, click the Kubeconfig File button

**Result:**
If the "certificate-authority-data" section should contain `+` it will instead show up in the browser as `&#43;`.

Example from browser source:
`
HJpYnV0ZXM&<span class="token comment">#43;CnN1YmplY3Q9L0M9VVMvU1Q9Q29sb3JhZG8vTD1EZW52ZXIvTz1Mb2NraGVlZCBNY\</span>
`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
This happens in 2.4.5 as well as 2.5.3

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): EC2 t3a.medium
- Kubernetes version (use `kubectl version`): 1.19.4

- Docker version (use `docker version`): 19.03.4

**Comment by duncanhkc** [comment]
I encountered this too today. The version of Rancher we use is also 2.4.5.
