### ISSUE TITLE
RKE cluster RHEL8 nodes. Rancher 2.5.3 install fail 

### ISSUE THREAD

**Issue by asemen2608** [rancher/rancher#30428]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Install RKE on RHEL 8.3 or RHEL 8.2 three node cluster
rke up

**Result:**

./ilrancher03/k8s/containerlogs/kube-apiserver:2020-12-05T08:09:04.270138873Z W1205 08:09:04.270045       1 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {https://10.230.5.31:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: authentication handshake failed: read tcp 10.230.5.33:46520->10.230.5.31:2379: read: connection timed out". Reconnecting...

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher 2.5.3
- Installation option (single install/HA):
HA 

Terraform provisioning RKE cluster of 3 nodes and then installs a helm deployment of the latest stable Rancher (2.5.3) on it.
The installation goes well on RHEL7.8 nodes but times out on RHEL8 nodes (8.2 and 8.3).
Rancher pods have the following warnings: 

Warning FailedScheduling 16m default-scheduler 0/3 nodes are available: 3 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
Normal Scheduled 15m default-scheduler Successfully assigned cattle-system/afa-rancher-5f76969684-5njmw to 10.230.5.31
Warning FailedScheduling 16m default-scheduler 0/3 nodes are available: 3 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate. 
..
Warning FailedCreatePodSandBox 15m (x3 over 15m) kubelet (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "79ce49143f45aec14cf49525317ff0dbc920b23d6558c9dfbab40fd8455733bb" network for pod "afa-rancher-5f76969684-5njmw": networkPlugin cni failed to set up pod "afa-rancher-5f76969684-5njmw_cattle-system" network: stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/
Warning Unhealthy 10m kubelet Readiness probe failed: Get http://10.42.2.2:80/healthz: dial tcp 10.42.2.2:80: connect: connection refused 

- Docker version (use `docker version`):
19.03.13

**Comment by superseb** [comment]
What k8s version is used for the cluster? Is firewalld enabled or disabled?

**Comment by asemen2608** [comment]
k8s is version v1.18.8

**Comment by asemen2608** [comment]
The firewall is disabled on the RHEL8 nodes

NAME          STATUS  ROLES                      AGE    VERSION  INTERNAL-IP  EXTERNAL-IP  OS-IMAGE                              KERNEL-VERSION                CONTAINER-RUNTIME
10.230.5.31  Ready    controlplane,etcd,worker  4d23h  v1.18.8  10.230.5.31  <none>        Red Hat Enterprise Linux 8.3 (Ootpa)  4.18.0-240.1.1.el8_3.x86_64  docker://19.3.13
10.230.5.32  Ready    controlplane,etcd,worker  4d23h  v1.18.8  10.230.5.32  <none>        Red Hat Enterprise Linux 8.3 (Ootpa)  4.18.0-240.1.1.el8_3.x86_64  docker://19.3.13
10.230.5.33  Ready    controlplane,etcd,worker  4d23h  v1.18.8  10.230.5.33  <none>        Red Hat Enterprise Linux 8.3 (Ootpa)  4.18.0-240.1.1.el8_3.x86_64  docker://19.3.13

**Comment by superseb** [comment]
RHEL8/CentOS8 support was introduced in k8s 1.19 as the base image was changed to support the newer components in RHEL8/CentOS8.

**Comment by asemen2608** [comment]
The customer uses Terraform to deploy.
The same deployment with CentOS 7 (Rancher 2.5.3) works fine

**Comment by asemen2608** [comment]
Switch in Rancher UI in cluster set up to Kubernetes v1.19 with the firewall disabled, solved this issue.
