### ISSUE TITLE
rancher-externalip-webhook chart enhancements

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#30424]
rancher-externalip-webhook:0.1.4

In the [rancher-externalip-webhook chart](https://github.com/rancher/externalip-webhook): 

* Expose the following as questions: 
  * `certificates.certManager.enabled`
  * `certificates.secretName`
  * `certificates.caBundle`
* In the chart's app-readme (not the helm readme) note that `cert-manager` integration is enabled by default, and if it is not installed, users will need to disable and provide their own certificates. Ensure this displays correctly in both ember and vue. 
* The link to `values.yaml` in the readme takes the user to a 404 page in Rancher. This should be removed or linked to the full [values.yaml](https://github.com/rancher/externalip-webhook/blob/master/chart/values.yaml)

**Comment by rawmind0** [comment]
Created PR https://github.com/rancher/externalip-webhook/pull/8 adding all requested enhancements.

**Comment by cbron** [comment]
Moving back to 2.5.4, we should have time to QA.

**Comment by cbron** [comment]
@rawmind0 looks like your PR closed it, re-opening for QA.

**Comment by rawmind0** [comment]
@bmdepesa new 2.5 rancher-external-ip-webhook v0.1.500 should be available at dev

**Comment by bmdepesa** [comment]
With chart `rancher-externalip-webhook:0.1.5` from dev branches

Tested in both ember UI and dashboard

* The readme is updated with the information about cert-manager being enabled by default, and how to provide your own certificates
* Certificate options are exposed as questions
* Link to `values.yaml` is fixed to the full link. 
* Deploying chart from both repositories is successful with both deployment options

![Screen Shot 2020-12-11 at 7 25 52 AM](https://user-images.githubusercontent.com/21316915/101916267-ee516b80-3b83-11eb-892f-7a4de312e8df.png)

![Screen Shot 2020-12-11 at 7 35 32 AM](https://user-images.githubusercontent.com/21316915/101916273-f1e4f280-3b83-11eb-9144-2602657b720b.png)
