### ISSUE TITLE
Update `Add Label` to `Add Engine Label` area so that it helps differentiate host label/engine label

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3043]
v0.50.0
UI v0.74.0

![screen shot 2015-12-16 at 9 48 48 am](https://cloud.githubusercontent.com/assets/11410997/11849002/651fc4d8-a3da-11e5-9788-d99e6137a882.png)

**Comment by tfiduccia** [comment]
Version - master jan 07
Verified fixed
