### ISSUE TITLE
Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s)

### ISSUE THREAD

**Issue by cpharishnec** [rancher/rancher#30441]
**What kind of request is this (question/bug/enhancement/feature request):**
unable to create a cluster on Azure VM 

**Steps to reproduce (least amount of steps as possible):**
-Added Node Template
-Added RKE Template 
-Add cluster with Azure Option 

**Result:**
The cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) 

**Other details that may be helpful:**
Frest HA Setup running in Azure

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Azure 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Azure Cloud  VM [Standard D2 v2 (2 vcpus, 7 GiB memory) - Linux (ubuntu 18.04)]
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCom                                 mit:"", GitTreeState:"clean", BuildDate:   "2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd                                 64"}

```
(paste the output here)
```

![image](https://user-images.githubusercontent.com/13827511/101924671-f5fe2800-3bf6-11eb-8c73-1af7131ef5c6.png)

- Docker version (use `docker version`): 19.3.14

```  
(paste the output here)
```

**Comment by abhi1693** [comment]
I'm also getting this issue on vsphere

**Comment by deniseschannon** [comment]
What roles did you select for your nodes It seems that you are missing a etcd role

**Comment by superseb** [comment]
Please login to the node and share the logs from the `rancher/rancher-agent` container when this happens. @cpharishnec @abhi1693

**Comment by abhi1693** [comment]
@deniseschannon @superseb  I had a 5 node cluster and all nodes had all 3 roles. 2 nodes failed and the cluster never recovered. I'll share the logs when this happens again. But I doubt I'll be able to recreate the exact scenario. I even tried removing them, recovering from snapshot nothing worked

**Comment by snasovich** [comment]
Closing due to lack of updates and age
