### ISSUE TITLE
Exclude cattle.io/cluster-agent from the ignored node labels

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#30445]
For https://github.com/rancher/rancher/pull/30304, we added `cattle.io/cluster-agent=true` as the node label that can be used to influence where to schedule the `cattle-cluster-agent`. But because of the ignored node labels (https://github.com/rancher/ui/blob/2.5-fixes/lib/shared/addon/utils/constants.js#L608-L621), this gets hidden in the UI and ignored when edited. Discussed with Vincent that we can add a one-off exclusion for this specifically (which is better than renaming it)

So the node label with key `cattle.io/cluster-agent` should not be ignored/hidden/greyed out/made uneditable.

**Comment by sadiapoddar** [comment]
Verified the fix on master-head, 495f7a1d
1. Added the cattle.io/cluster-agent label in one of the hosted cluster worker nodes 
2. Deleted the cattle-cluster-agent,
3. Noticed that cattle-cluster-agent created on the worker node where the cattle.io/clsuter-agent label was added
4. Deleted the label and repeated the tests

The cattel.io/cluster is editable now and the functionalities are working with the fix. 
<img width="517" alt="Screen Shot 2020-12-15 at 12 03 02 AM" src="https://user-images.githubusercontent.com/72409237/102187963-8cd21b00-3e69-11eb-84a6-386d87ab4a40.png">
