### ISSUE TITLE
rancher-externalip-webhook new version in 2.5.4

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#30446]
Covers: https://github.com/rancher/rancher/issues/30424
This issue is just to track that this new chart version is coming out.

**Comment by cbron** [comment]
Since this is first chart in series we need to do light airgap testing.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.4-rc4
RancherD airgap install

* Provision a cluster
* Navigate to Apps in the Dashboard
* Create certs secret and deploy `rancher-externalip-webhook` chart w/ provided certs and provide an allowed CIDR
* App deploys successfully
* Create a service with an externalIP not matching the allowed CIDR
* The request is rejected by the webhook
