### ISSUE TITLE
We are allowed to edit services and set its name to of an existing service name. Futher edits on this service errors out with "Validation failed in API: name is not unique".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3044]
Server version - V0.50.0-rc5

Steps to reproduce the problem:

Create a service S1 with name - "test1".
Create a service S2 with name - "test2".
Update service S2 and set name to "test1". This update is successful. This should not be allowed.

Now try to edit service S1/S2 and set a new name (like test3). This update fails with "Validation failed in API: name is not unique" error.

**Comment by alena1108** [comment]
Steps to reproduce the bug:

1) Create services foo and bar
2) rename service foo to bar - allowed, bug.
3) try to rename service bar to anything else - always fails. Caused by previously allowed duplicated naming on step 1)

**Comment by sangeethah** [comment]
Tested with lasted build from master.

We are not allowed to edit a service and set its name to of an existing service name. API fails with status code 422.
