### ISSUE TITLE
"rejected by webhook" warnings messages seen in rancher logs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30452]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Bring up a rancher server - 2.5-head
- deploy a bunch of clusters - custom/EKS clusters
- Rancher server logs have a lot of these warnings.

```
W1211 20:48:54.428110      26 dispatcher.go:141] rejected by webhook "rancher.cattle.io": &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"admission webhook \"rancher.cattle.io\" denied the request: Unauthorized", Reason:"Unauthorized", Details:(*v1.StatusDetails)(nil), Code:401}}
W1211 20:48:54.471165      26 dispatcher.go:141] rejected by webhook "rancher.cattle.io": &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"admission webhook \"rancher.cattle.io\" denied the request: Unauthorized", Reason:"Unauthorized", Details:(*v1.StatusDetails)(nil), Code:401}}
```

**Result:**

**Other details that may be helpful:**

- I see this on 2 setups where an upgrade was done - 2.5.2/2.5.3 to 2.5-head
- No obvious errors/issues seen while accessing the server/clusters
- see it on a fresh install of 2.5.4-rc4 also after a cluster starts provisioning.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `baf4867c`
- Installation option (single install/HA):  single

**Comment by StrongMonkey** [comment]
https://github.com/rancher/charts/pull/893

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `182e3de71` and `rancher/rancher-webhook:v0.1.0-beta9`**

- Deploy rancher, deploy few clusters. Warning messages seen in logs
```
W1214 23:57:21.439516      25 dispatcher.go:141] rejected by webhook "rancher.cattle.io": &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"admission webhook \"rancher.cattle.io\" denied the request: Unauthorized", Reason:"Unauthorized", Details:(*v1.StatusDetails)(nil), Code:401}}
2020/12/14 23:57:21 [INFO] [mgmt-cluster-rbac-delete] Creating Default project for cluster c-922mp
W1214 23:57:21.463837      25 dispatcher.go:141] rejected by webhook "rancher.cattle.io": &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"admission webhook \"rancher.cattle.io\" denied the request: Unauthorized", Reason:"Unauthorized", Details:(*v1.StatusDetails)(nil), Code:401}}
```

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `e2295c664` and `rancher/rancher-webhook:v0.1.0-beta9`**

- Deploy rancher, deploy a DO cluster.
- No warning messages seen.

**Comment by sowmyav27** [comment]
Closing this as per https://github.com/rancher/rancher/issues/30452#issuecomment-745407581.
