### ISSUE TITLE
Cloning/upgrading a service checks the "set a specific hostname" option

### ISSUE THREAD

**Issue by msh100** [rancher/rancher#3045]
If you go to clone or upgrade a service, under advanced options for the new service on the networking tab the radio box "Set a specific hostname" will always be set, even if "Use the container name" was selected on the previous service.

This is also the default option when creating a new service however I suspect that this is incorrect as it's an empty text box.

![image](https://cloud.githubusercontent.com/assets/4477262/11850890/e05e1846-a427-11e5-96c7-01392cf62b26.png)

**Comment by deniseschannon** [comment]
Reproduced with v0.50.1.

**Comment by vincent99** [comment]
This should have been fixed in the last round of things that don't clone

**Comment by deniseschannon** [comment]
Verified this is working in master 3/21.
