### ISSUE TITLE
[Monitoring V1] can not upgrade from 0.1.4 to v0.2.0

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#30455]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Path 1:
- run rancher:v2.5.3 single-install 
- add a cluster with supported version 
- enable the cluster monitoring 0.1.4
- upgrade rancher to v2.5-head  3d7ffc
- upgrade monitoring from 0.1.4 to 0.2.0

Path 2:
- run rancher:v2.5-head  3d7ffc single-install
- add a cluster with supported version 
- enable the cluster monitoring 0.1.4
- upgrade monitoring from 0.1.4 to 0.2.0

Path 3:
- run rancher:v2.5.3 single-install 
- add a cluster with supported version 
- enable the cluster monitoring 0.1.4
- change the branch of `system-library` to `dev-v2.5`
- upgrade monitoring from 0.1.4 to 0.2.0

**Result:**

Failed to upgrade the monitoring because the following 2 PUT requests failed 
![image](https://user-images.githubusercontent.com/6218999/101964771-be2fba00-3bcf-11eb-8ae1-26bc96469ee9.png)

And the responses are the same 
![image](https://user-images.githubusercontent.com/6218999/101964799-d1db2080-3bcf-11eb-9812-e00f9123be49.png)

no error shows in Rancher's logs

**Comment by jiaqiluo** [comment]
Once this bug is fixed, the following will be checked after upgrading the monitoring 

- [ ] Monitoring continue working
- [ ] CRD api version is changed to `apiextensions.k8s.io/v1`
- [ ] Memory request for Prometheus Operator has been updated to 100m 
- [ ] [two new images](https://github.com/rancher/image-mirror/pull/49/files) are used

**Comment by westlywright** [comment]
A couple things from the UI side, short of some small changes for a dependency update (framework syntax changes) there have been no major updates to the code controlling this area. I did investigate a bit more and tested an upgrade from `0.1.3` -> `0.1.4` and the upgrade succeeds without error. It seems to be related to the `0.2.0` upgrade only. Additionally I was able to upgrade a traditional Wordpress app without issue which I added as a sort of control. 

The UI flow to upgrade Monitoring is as follows:
POST to cluster action `editMonitoring` with the payload containing only the answers object
PUT to project app `cluster-monitoring` with the payload containing only the new `externalId` and `targetNamespace`. 
PUT to project app `monitoring-operator` with the payload containing only the new `externalId` and `targetNamespace`. 
POST to cluster action `viewMonitoring ` with the payload containing only the action `viewMonitoring`

The two PUT calls fail with the same error above but no additional info. 

I am not 100% sure why the monitoring UI doesn't upgrade the app like the traditional global and project apps but I suspect it has to do with the custom backend that we wrote to tie all this together. The difference being the traditional apps use an upgrade action where here we're doing everything by sending the external id's. Initially this doesn't seem to be related to any specific UI change.

**Comment by aiyengar2** [comment]
@guangbochen @aiwantaozi would you have any insight into why we're seeing this error?

**Comment by GGGitBoy** [comment]
@aiyengar2 This seems to be an existing problem, but because we added `kubeVersion: ">=1.16.0-0"` to `Chart.yaml` of 0.2.0, it was triggered.

we can check here 
https://github.com/rancher/rancher/blob/master/pkg/catalog/manager/manager.go#L215-L227

the clusterName here is empty, which results in failure to get the cluster
https://github.com/rancher/rancher/blob/master/pkg/api/norman/store/app/store.go#L69-L70

I think it will be fixed if add parameter `projectId` when UI PUT to project app `cluster-monitoring` and `monitoring-operator`

**Comment by westlywright** [comment]
@GGGitBoy Thanks for the info that worked like a charm!

**Comment by sangeethah** [comment]
Tested with rancher server version - `v2.5-e2295c`
1. Add a cluster 
2. Enable the cluster monitoring 0.1.4
3. Upgrade monitoring from 0.1.4 to 0.2.0

Able to upgrade to 0.2.0 successfully.

**Comment by jiaqiluo** [comment]
Steps:
- run rancher:`v2.5.3` single-install
- add a cluster with supported version
- enable the cluster monitoring `0.1.4`
- enable the project monitoring `0.1.4`
- upgrade rancher to v2.5-head e2295c
- upgrade cluster monitoring from `0.1.4` to `0.2.0`
- upgrade project monitoring from `0.1.4` to `0.2.0`

Results:
- the upgrade succeeds 
- `projectId` is in the payload of the PUT request 
<img width="511" alt="Screen Shot 2020-12-16 at 11 21 17 AM" src="https://user-images.githubusercontent.com/6218999/102390363-8ccd3a80-3f91-11eb-8d3f-61f9447d57d8.png">
