### ISSUE TITLE
Cannot install rancher monitoring from marketplace. It keeps failing.

### ISSUE THREAD

**Issue by auser1029** [rancher/rancher#30459]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
I tried installing rancher monitoring from the marketplace (default settings). It failed to install for some unknown reason. I proceeded to uninstall it (Clicking on the delete button). It failed to delete and became stuck in uninstalling. 

![rancher-monitoring](https://user-images.githubusercontent.com/11544292/101990986-82900100-3c5e-11eb-8c12-2237eb7ff859.png)

Here is the error in the helm operation pod:
```
helm uninstall --namespace=cattle-monitoring-system rancher-monitoring-crd
creating 1 resource(s)
Error: warning: Hook pre-delete rancher-monitoring-crd/templates/jobs.yaml failed: jobs.batch "rancher-monitoring-crd-delete" already exists
```
I successfully uninstalled it manually from the kubectl console
```
helm delete --namespace=cattle-monitoring-system --no-hooks rancher-monitoring-crd
```
Now, every time I try to install the monitoring package from the UI, I get the following error:

```
helm upgrade --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-9.4.201.yaml --version=9.4.201 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-9.4.201.tgz
Release "rancher-monitoring-crd" does not exist. Installing it now.
creating 4 resource(s)
beginning wait for 4 resources with timeout of 10m0s
creating 1 resource(s)
Error: failed post-install: warning: Hook post-install rancher-monitoring-crd/templates/jobs.yaml failed: jobs.batch "rancher-monitoring-crd-create" already exists
```

I am pretty new to helm, so not sure how to get this installed correctly.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.3
- Installation option (single install/HA): Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.19.4

- Docker version (use `docker version`): 5:19.03.14~3-0~ubuntu-focal

**Comment by auser1029** [comment]
I was able to make some progress by deleting the cattle monitoring namespace to remove any left-over objects. Now I am back at the original error.
`kubectl delete namespaces cattle-monitoring-system
`

Now, when I install it hangs here:

```
helm upgrade --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-9.4.201.yaml --version=9.4.201 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-9.4.201.tgz
Release "rancher-monitoring-crd" does not exist. Installing it now.
creating 4 resource(s)
beginning wait for 4 resources with timeout of 10m0s
creating 1 resource(s)
Watching for changes to Job rancher-monitoring-crd-create with timeout of 10m0s
Error: failed post-install: timed out waiting for the condition 
```


Any tips on how to progress with the installation or get more debugging logs?

**Comment by auser1029** [comment]
I just reinstalled the rancher cluster and it worked.

**Comment by exocode** [comment]
Just for others: I increased the resources of my nodes (drastically) and it worked too.
