### ISSUE TITLE
Update example in volumes box to [/vol/on/host:]/path/in/container[:ro]

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3046]
I have a simple container service defined, that uses an ephemeral directory mapping.  
Under CoreOS 766/Docker 1.7 this starts up fine; however under CoreOS 877/Docker 1.9 the instance fails to start.  Digging into the logs, I can see the message:
````
State: stopped Internal server error  Cannot start container  Unable to set up mount point Neither source nor volume defined
````
Firstly, it would be more helpful if Rancher made this log more visible when a container fails to start.  Maybe show "Last error" in the Container status page?
Secondly, why does this work with an older Docker host but not a more recent one?

The service definition:
````
Minecraft:
  environment:
    EULA: 'TRUE'
  tty: true
  image: itzg/minecraft-server
  volumes:
  - :/data
  stdin_open: true
````
Is this another instance of a service created before Rancher upgrade having invalid configuration that generates a docker command incompatible with 1.9?

The problem seems to be that the definition for the volume is using :/data rather than /data to indicate a dynamically created volume, which is apparently valid in Docker 1.7 but not in 1.9.  It is possible for the Rancher system to detect this older syntax and correct it automatically, if it realises that the container is to be started on a 1.8 or later host?

**Comment by deniseschannon** [comment]
We are looking to introduce an error state. https://github.com/rancher/rancher/issues/3080

From what I understand the volumes part that you have is invalid. It might have happened to work in previous Docker volumes, but it's invalid.
 
```
volumes:
 - :/data
```
Local volumes must start with `/` or `.`, so either `/:/data` or `.:/data` would be valid. 
https://docs.docker.com/compose/compose-file/#volumes-volume-driver

**Comment by sshipway** [comment]
It is worth noting that the when creating a new container and clicking the "Volumes" tab, the example given is:
````
[/vol/on/host]:/path/in/container[:ro]
````
which is therefore incorrect.  It should be
````
[/vol/on/host:]/path/in/container[:ro]
````
A small thing, but might help prevent others making this mistake.

**Comment by will-chan** [comment]
We should at least fix the example in the UI.

**Comment by vincent99** [comment]
Changed to `[volumename: or /path/on/host:]/path/in/container[:ro]`

**Comment by tfiduccia** [comment]
version - master ui 1/22
example updated
Verified fixed
