### ISSUE TITLE
TTL for token during login is ignored and auth-user-session-ttl-minutes is used instead

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#30465]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Perform a login as below specifying a TTL.
```
curl -v -X POST 'https://rancher.example.com/v3-public/localProviders/local?action=login' \
-H 'content-type: application/json' \
-H 'accept: application/json' \
--data-binary '{"username":"admin","password":"admin","description":"Test token created from CLI/curl","responseType":"json","ttl":60000}'
```

**Result:**
The return token has a default value of `"ttl":57600000`, picked up from setting `auth-user-session-ttl-minutes`. Instead, 60000 should have been used.

**Other details that may be helpful:**
Here is the code: https://github.com/rancher/rancher/blob/v2.5.2/pkg/auth/providers/publicapi/login.go#L114. We need to add a condition check to populate the TTL from the request.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.2

**Comment by vincent99** [comment]
The input ttl was intentionally ignored after the setting was added.

**Comment by leodotcloud** [comment]
Looking at the [PR](https://github.com/rancher/rancher/pull/22108/files), I think the TTL from the request was never carried forward?

>The input ttl was intentionally ignored after the setting was added.

Could you please share more details?

**Comment by vincent99** [comment]
It used to be provided by the UI in the action input. Then the setting was added, so that is the length now.  As its name suggests, the setting is **the ttl**, not the max allowed or a default.

**Comment by leodotcloud** [comment]
This breaks the use case of "Get a short-lived token (say 5 min, configurable from the client) using your login credentials to run a script". With the new setting, this is now determined by the API server.

**Comment by vincent99** [comment]
Using the login flow outside of the UI was not ever much of a consideration.  Because most of the providers are oauth flows where you have no credentials to enter (to us) and no way to connect a browser interaction back to the calling script easily.
