### ISSUE TITLE
Rancher high availability installation error

### ISSUE THREAD

**Issue by herrywen-nanj** [rancher/rancher#30461]
My env is k3s:v1.18  and rancher-version:2.4.8
![image](https://user-images.githubusercontent.com/33476935/102010588-ee1ac100-3d79-11eb-850a-2650590882cf.png)

My ingress can't resolve the domain name, only through pod_ IP access rancher,And I'm also patch cattle cluster agent_ Pod,But it's still wrong.How should I deal with this? I hope to pass zhou1.rancher.com Visit rancher

Here are some details：
![image](https://user-images.githubusercontent.com/33476935/102011067-f1637c00-3d7c-11eb-84bb-baec717f4483.png)

**Comment by herrywen-nanj** [comment]
l resolve this problem，Here is my solution
```
[root@k8s-master1 opt]# kubectl get pods -n cattle-system -o wide
NAME                                    READY   STATUS             RESTARTS   AGE     IP               NODE          NOMINATED NODE   READINESS GATES
rancher-6f67c5495d-tgx8n                1/1     Running            2          4h37m   10.42.2.5        k8s-node2     <none>           <none>
rancher-6f67c5495d-9sqlk                1/1     Running            2          4h37m   10.42.1.4        k8s-node1     <none>           <none>
rancher-6f67c5495d-c7xkq                1/1     Running            0          4h31m   10.42.0.10       k8s-master1   <none>           <none>
cattle-node-agent-wgqh4                 1/1     Running            0          14m     192.168.74.151   k8s-master1   <none>           <none>
cattle-cluster-agent-85c74b44cc-qgrqm   0/1     CrashLoopBackOff   7          14m     10.42.2.7        k8s-node2     <none>           <none>
cattle-node-agent-xgtpk                 0/1     CrashLoopBackOff   7          14m     192.168.74.150   k8s-node1     <none>           <none>
cattle-node-agent-mf7c8                 0/1     CrashLoopBackOff   7          14m     192.168.74.149   k8s-node2     <none>           <none>
[root@k8s-master1 opt]# kubectl logs -f pod/cattle-cluster-agent-85c74b44cc-qgrqm -n cattle-system                       
INFO: Environment: CATTLE_ADDRESS=10.42.2.7 CATTLE_CA_CHECKSUM=5e83c06029aa6ebd14b7ecd5107871a8696da5be42a5762e32673db1da08cff8 CATTLE_CLUSTER=true CATTLE_FEATURES=dashboard=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-85c74b44cc-qgrqm CATTLE_SERVER=https://zhou1.rancher.com
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.43.0.10 options ndots:5
ERROR: https://zhou1.rancher.com/ping is not accessible (Could not resolve host: zhou1.rancher.com)
```

When I got the  error, I found that DNS resolution within the cluster could not find the domain name of the Ranger server，So I added DNS resolution inside pod, and the problem was solved.
```
kubectl -n cattle-system patch  deployments cattle-cluster-agent --patch '{
    "spec": {
        "template": {
            "spec": {
                "hostAliases": [
                    {
                        "hostnames":
                        [
                            "zhou1.rancher.com"     #your rancher domain name
                        ],
                            "ip": "192.168.74.151"    #your rancher server's ip
                    }
                ]
            }
        }
    }
}'


kubectl -n cattle-system patch  daemonsets cattle-node-agent --patch '{
    "spec": {
        "template": {
            "spec": {
                "hostAliases": [
                    {
                        "hostnames":
                        [
                            "zhou1.rancher.com"     #your rancher domain name
                        ],
                            "ip": "192.168.74.151"    #your rancher server's ip
                    }
                ]
            }
        }
    }
}'
```

If you have any other questions, please leave a message~~

**Comment by superseb** [comment]
The docs specify the requirements for an HA install using k3s here (https://rancher.com/docs/rancher/v2.x/en/installation/resources/k8s-tutorials/infrastructure-tutorials/infra-for-ha-with-external-db/) which includes a DNS record and a load balancer. The DNS record chosen is configured in Rancher for accessing the Rancher UI and for system components to connect back to Rancher. This should either be a domain you own and control the DNS over (to create the record) or use a DNS service (like one that translates `$IP.$DOMAIN` to `$IP`)

Manually patching resources is a technical way to solve this but this "fix" will be removed when Rancher is upgraded as the agents will be redeployed. This also does not account for other components that use the Rancher hostname to connect.

Let me know if you run into issues with the requirements described in the docs, I would advise against manually patching resources to resolve a hostname to an IP address.
