### ISSUE TITLE
[Rancher] New Longhorn chart for 2.5.4

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#30476]
PRs included: https://github.com/rancher/charts/pull/894
There are no image changes.

**Comment by deniseschannon** [comment]
Only need to validate that this chart is hidden on a windows cluster and shows up on the list for a linux cluster.

**Comment by sowmyav27** [comment]
on 2.5.4-rc4, deploy Longhorn `v1.0.2`
Annotation seen in the app `catalog.cattle.io/os: linux`
