### ISSUE TITLE
Aliyun ACK cluster driver is not visible on Rancher for create a new cluster

### ISSUE THREAD

**Issue by AEnguerrand** [rancher/rancher#30489]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Activate the cluster driver for Aliyun ACK (inside Tools/Drivers)
2. Go the page for  add new cluster to Rancher (`<rancher-url>g/clusters/add/selectadd` where the list of drivers/options lists for creating a new cluster)

**Result:**
The Aliyun ACK cluster driver is not visible, so not possible to add a cluster with this driver. But the Aliyun ACK driver is mark activate/download on the Tools/Driver page.

**Other details that may be helpful:**

- I tried to activate all the drivers (nodes and cluster): everything is visible, except the Aliyun ACK driver
- I tried reinstalling the driver, deactivating it, etc .: unable to see the driver

URL of the driver/version of the driver use: https://github.com/rancher/kontainer-engine-driver-aliyun/releases/download/v0.2.4/kontainer-engine-driver-aliyun-linux
API output about the driver: 
````
{
	[...]
	"active": true,
	"actualUrl": "https://github.com/rancher/kontainer-engine-driver-aliyun/releases/download/v0.2.4/kontainer-engine-driver-aliyun-linux",
	"annotations": {
		"lifecycle.cattle.io/create.mgmt-kontainer-driver-lifecycle": "true"
	},
	"baseType": "kontainerDriver",
	"builtIn": false,
	"checksum": "",
	"conditions": [ {
			"lastUpdateTime": "2020-12-04T11:02:11Z",
			"status": "True",
			"type": "Downloaded"
		},
		{
			"lastUpdateTime": "2020-12-04T11:02:11Z",
			"status": "True",
			"type": "Installed"
		},
		{
			"lastUpdateTime": "2020-12-15T09:22:47Z",
			"status": "True",
			"type": "Inactive"
		},
		{
			"lastUpdateTime": "2020-12-15T09:22:55Z",
			"status": "True",
			"type": "Active"
		}
	],
	[...]
	"executablePath": "/management-state/bin/kontainer-engine-driver-aliyun",
	[...]
	"labels": {
		"cattle.io/creator": "norman"
	},
	"links": {
		"remove": "…/v3/kontainerDrivers/kd-wwbk2",
		"self": "…/v3/kontainerDrivers/kd-wwbk2",
		"update": "…/v3/kontainerDrivers/kd-wwbk2"
	},
	"name": "aliyun",
	"state": "active",
	"transitioning": "no",
	"transitioningMessage": "",
	"type": "kontainerDriver",
	"uiUrl": "",
	"url": "https://github.com/rancher/kontainer-engine-driver-aliyun/releases/download/v0.2.4/kontainer-engine-driver-aliyun-linux",
	[...]
}
````

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.1
- Installation option (single install/HA): HA on an RKE cluster

**Comment by superseb** [comment]
This is the default for Rancher v2.5.1 (https://github.com/rancher/rancher/blob/v2.5.1/pkg/data/management/kontainerdriver_data.go#L63), did you change anything on the driver while testing?

**Comment by AEnguerrand** [comment]
Yes, I have tried to install another version from the driver repository ([https://github.com/rancher/kontainer-engine-driver-aliyun/releases](https://github.com/rancher/kontainer-engine-driver-aliyun/releases)).

I tried with this version (https://drivers.rancher.cn/kontainer-engine-driver-aliyun/0.2.6/kontainer-engine-driver-aliyun-linux), I the same issue, nothing visible on the "add cluster" page.

**Comment by AEnguerrand** [comment]
Ok, I found the problem the UI link (js file) was not the correct URL on my config it's was from an old version of Rancher (so with an upgrade it breaks driver interface, but, weirdly, we don't have more information about that on the Rancher UI / API). And thanks for link to the code link to that!

**Comment by cwdsuzhou** [comment]
@AEnguerrand 

![image](https://user-images.githubusercontent.com/12230714/178898834-af8e5796-f7b2-4609-9d58-300a8696738a.png)



This website seems unsafe now
