### ISSUE TITLE
[rancherd] Bump RKE2 version - 1.18.16

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#30492]
The rancher/rke2 team is planning an RKE2 release on or around 12/22/2020. This will not become stable until about 7 days post-release since this is a new minor version bump for RKE2.

If we are ready to update rancherd to 1.19.x kubernetes (RKE2) then we should proceed to update rancher/rancher as necessary.

The RKE2 version used in any Dockerfiles, etc should be bumped accordingly.

If needed, you can reference the last issue where this was done: https://github.com/rancher/rancher/issues/29825

**Comment by davidnuzik** [comment]
v1.19.5+rke2r1 should go [stable ](https://github.com/rancher/rke2/issues/609)on 1/4/2021 assuming there are no serious bugs reported by the community.

**Comment by davidnuzik** [comment]
v1.19.5+rke2r1 is now stable and ready to pick up and pull into Rancher for 2.5.5 release.
a v1.19.6+rke2r1 release might be available at that time but might not be "stable" right in time. We should probably stick with v1.19.5 rke2

**Comment by davidnuzik** [comment]
@StrongMonkey @cbron FYI the RKE2 team is planning a release of v1.19.7+rke2r1 to land on 1/13/2021. It will be stable the day after most likely.

**Comment by davidnuzik** [comment]
@StrongMonkey @cbron FYI the RKE2 team is planning a release of v1.19.8+rke2r1 to land on 2/19/2021 at the latest. It looks like we want to target this in 2.5.6 so this should be the release we use.

**Comment by cbron** [comment]
Another confirmation that we are aiming for that 2/19 release as the RancherD version going out in 2.5.6

**Comment by cjellick** [comment]
2.5's rancherd is on rke2 1.18. we should not jump to 1.19. just stay on 1.18

https://github.com/rancher/rancher/blob/release/v2.5/package/Dockerfile.runtime#L1

I'm updating the title of this to reflect 1.18 instead of 1.19

**Comment by rancher-max** [comment]
Validated in both airgap and standard HA install: rancherd is using v1.18.16+rke2r1 now and there are no noticed regressions
