### ISSUE TITLE
favicon is missing on explorer

### ISSUE THREAD

**Issue by ahmadalli** [rancher/rancher#30499]
I'm using rancher v2.5.2 and favicon is fine on the other places but not on the explorer

**Comment by ahmadalli** [comment]
I'm getting 404

```
curl -I https://rancher.foo.barfavicon.png
HTTP/1.1 404 Not Found
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
date: Fri, 18 Dec 2020 15:45:44 GMT
content-length: 19
```

**Comment by sadiapoddar** [comment]
Verified on 2.5-head, commit id v2.5-be9683f, the "favicon.png" been added on the explorer view

<img width="988" alt="Screen Shot 2021-01-15 at 10 56 17 PM" src="https://user-images.githubusercontent.com/72409237/104800805-1c2e5f00-5785-11eb-9c42-858dcfd7ad6f.png">
