### ISSUE TITLE
Images missing from release artificat images.txt

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#30496]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Download images.txt from v2.5.4-rc5

**Result:**
Missing images:
```
rancher/fleet-agent:v0.3.2-rc5
rancher/gitjob:v0.1.10
rancher/fleet:v0.3.2-rc5
rancher/rancher-operator:v0.1.2-rc1
rancher/rancher-runtime:v2.5.4-rc5
```

**Other details that may be helpful:**
Without these images in images.txt, airgap setups will not fully come up. Operators will need to manually pull, tag, and push these images without the help of `rancher-save-images` and `rancher-load-images` shell scripts. Below is the file that I downloaded directly from the releases page.
[rancher-images(3).txt](https://github.com/rancher/rancher/files/5697549/rancher-images.3.txt)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.4-rc5 (also noticed on rc4)
- Installation option (single install/HA): not applicable

**Comment by StrongMonkey** [comment]
Our chart generating script doesn't seem to generate the latest rc of fleet/rancher-operator.

**Comment by izaac** [comment]
Rancher version: `v2.5.4-rc6` 

These images are now pulled properly in an Airgapped install.

```
rancher/fleet-agent:v0.3.2-rc5
rancher/fleet:v0.3.2-rc5
rancher/gitjob:v0.1.11
rancher/rancher-operator:v0.1.2-rc2
rancher/rancher-runtime:v2.5.4-rc6
```
