### ISSUE TITLE
[UI][Backport] 2.4: pass cluster name on template request via query parameter

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#30504]
**Original issue:**
https://github.com/rancher/rancher/issues/29774

**Comment by jiaqiluo** [comment]
This is validated rancher:v2.5-head 23eee560a

The `GET` request for template passes the new parameter `ClusterName`

Steps:
- go to any project 
- go the apps -> launch 
- click any chart in the list 

Result:
the request 
<img width="1170" alt="Screen Shot 2020-12-22 at 2 52 07 PM" src="https://user-images.githubusercontent.com/6218999/102936555-9a893100-4465-11eb-8b92-f67785dc9496.png">

and the response
<img width="1173" alt="Screen Shot 2020-12-22 at 2 53 27 PM" src="https://user-images.githubusercontent.com/6218999/102936630-c1dffe00-4465-11eb-98f6-ec8e18a2c1e0.png">
