### ISSUE TITLE
helm3-library charts are not bundled with system charts

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#30502]
rancher/rancher:2.5.4-rc4

In an airgapped install, Rancher does not include the `helm3-library` charts when bundling system charts. This prevents a user from installing the `rancher-externalip-webhook` chart in the cluster manager (Ember view) in particular.

* Install Rancher, airgapped with `useBundledSystemChart=true`
* In `Catalogs`, `helm3-library` is not bundled

**Comment by cbron** [comment]
Not going to pursue this for now, as this would include many other charts and you can workaround by installing tgz.
