### ISSUE TITLE
Rancherd initial password login failure

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#30501]
rancher/rancher#29565 

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
The issue is seen intermittently. 2 out of 5 times while bringing up rancherd.
Seen only with rancherd-master and not on 2.5.4-rc4

1.wget -O rancherd https://releases.rancher.com/rancherd/rancherd-master
2.sudo RKE2_RUNTIME_IMAGE=rancher/rancher-runtime:v2.5.4-rc4 ./rancherd server --write-kubeconfig-mode 644 2>&1 &
3.systemctl daemon-reload
4.while true; do ./rancherd reset-admin; sleep 1; done 
[Immediately stopped after the first password generation]
                **or** 
5.rancherd reset-admin

The login with the initial password will fail with 401 error.
If step 4 or step 5 is performed again after the failure and a new password is generated, the login goes through without any issues.

**Result:**
<img width="588" alt="Screen Shot 2020-12-13 at 9 56 34 PM" src="https://user-images.githubusercontent.com/38144301/102270085-6a281c80-3ed2-11eb-9a87-a698b1c9589c.png">
<img width="809" alt="Screen Shot 2020-12-13 at 9 56 23 PM" src="https://user-images.githubusercontent.com/38144301/102270116-78763880-3ed2-11eb-8804-b9e8417db207.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
  Rancher | v2.5.4-rc4
  User Interface | v2.5.4-rc4
  Helm | v2.16.8-rancher1
  Machine | v0.15.0-rancher48

**Comment by StrongMonkey** [comment]
The lastest rancherd build is available on `https://releases.rancher.com/rancherd/master/rancherd`. Make sure you download from here and check the version by running `rancherd -v`.

**Comment by StrongMonkey** [comment]
Running reset-admin in a while loop could cause a race condition where the password is reseted but it is never printed out before the command get canceled. I think as long as we can verify if the next reset command reset the password it should be fine.
