### ISSUE TITLE
Login fail ( cannot read property forEach of Null)

### ISSUE THREAD

**Issue by nczz** [rancher/rancher#3050]
<img width="1276" alt="2015-12-17 02 19 26" src="https://cloud.githubusercontent.com/assets/5238961/11864756/4f916094-a4da-11e5-96c7-e4e12b455b85.png">
When I login in my Rancher server's admin account, I got the fail message as this screenshot.

But normal in demo account.

**Comment by deniseschannon** [comment]
What's your Rancher version, how are you authenticated?

Is it a fresh setup or upgrade?

We set up auth all the time and are always logging into Rancher as admin, so I will need more details in order to help reproduce.

**Comment by nczz** [comment]
@deniseschannon thanks for your reply. I forgot to put these information, sorry.

- Rancher v0.47 (fresh setup)
- local authentacated

**Comment by deniseschannon** [comment]
Can you try the latest version of Rancher? v0.50.1

I use local auth all the time and have no issues logging in as an admin.

**Comment by deniseschannon** [comment]
@nczz If you are still facing this issue with the latest version, please re-open. As mentioned, I use local auth all the time and never face this issue. 

If you re-open, please provide browser.
