### ISSUE TITLE
Launching eks v2 using 1.14 gives error "unsupported Kubernetes version" 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30518]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Launch a hosted eks cluster with 1.14 k8s version.
- Error seen on the cluster `Error creating cluster: InvalidParameterException: unsupported Kubernetes version { RespMetadata: { StatusCode: 400, RequestID: "86e6c199-15e1-422d-8bb6-7fb4f2cb847e" }, ClusterName: "sowmya-114", Message_: "unsupported Kubernetes version" }`

**Result:**
1.14 should not be available in the dropdown while 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `e2295c`
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): eks v2
- Kubernetes version (use `kubectl version`):

```
1.14
```

**Comment by westlywright** [comment]
@sowmyav27 can you attach the values of `ui-k8s-default-version-range` and `ui-k8s-supported-versions-range` settings?

**Comment by sowmyav27** [comment]
`ui-k8s-default-version-range`

```
{
"baseType": "setting",
"created": "2020-12-15T16:20:03Z",
"createdTS": 1608049203000,
"creatorId": null,
"customized": true,
"default": "<=1.14.x",
"id": "ui-k8s-default-version-range",
"links": {
"remove": "…/v3/settings/ui-k8s-default-version-range",
"self": "…/v3/settings/ui-k8s-default-version-range",
"update": "…/v3/settings/ui-k8s-default-version-range"
},
"name": "ui-k8s-default-version-range",
"source": "db",
"type": "setting",
"uuid": "f427738a-43f2-4469-9d29-dc54c8b855af",
"value": "<=v1.19.x"
}
```
- `ui-k8s-supported-versions-range`
```
{
"baseType": "setting",
"created": "2020-12-15T16:20:02Z",
"createdTS": 1608049202000,
"creatorId": null,
"customized": true,
"default": ">= 1.11.0 <=1.14.x",
"id": "ui-k8s-supported-versions-range",
"links": {
"remove": "…/v3/settings/ui-k8s-supported-versions-range",
"self": "…/v3/settings/ui-k8s-supported-versions-range",
"update": "…/v3/settings/ui-k8s-supported-versions-range"
},
"name": "ui-k8s-supported-versions-range",
"source": "db",
"type": "setting",
"uuid": "f47043ee-bd57-40b7-bf19-5ef661e580c1",
"value": ">=v1.16.x <=v1.19.x"
}
```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 4297ee1` and `rancher\rancher:v2.5-head` `version bb69b03`

As 1.14 was deprecated this month, EKS k8s v1.14 is no longer available:
![Screen Shot 2020-12-21 at 1 17 26 PM](https://user-images.githubusercontent.com/57409052/102818563-1c5a5b00-438f-11eb-82a1-fcff8a0d0da3.png)
