### ISSUE TITLE
Process environment.create fails with Timeout

### ISSUE THREAD

**Issue by utrack** [rancher/rancher#3051]
When trying to create a stack from catalog (es in my case) the process creating it (named `environment.create`) gets stuck indefinitely.

On a closer look, the `rancher-compose-executor` fails with the error:

```
io.cattle.platform.async.utils.TimeoutException
	at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1.run(RetryTimeoutServiceImpl.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Rancher service spam this in logs: 

```
time="2015-12-17T10:11:09Z" level=info msg="Starting rancher-compose-executor" version=v0.6.1
time="2015-12-17T10:11:11Z" level=info msg="Setting log level" logLevel=info
time="2015-12-17T10:11:11Z" level=info msg="Starting go-machine-service..." gitcommit="4c789a5"
time="2015-12-17T10:11:39Z" level=fatal msg="Unable to create event router" error="Get http://192.168.10.5:25001/v1: dial tcp 192.168.10.5:25001: i/o timeout"
time="2015-12-17T10:11:41Z" level=error msg="Unable to create EventRouter" Err="Get http://192.168.10.5:25001/v1: dial tcp 192.168.10.5:25001: i/o timeout"
time="2015-12-17T10:11:41Z" level=info msg="Exiting go-machine-service..."
time="2015-12-17T10:11:41Z" level=info msg="Starting rancher-compose-executor" version=v0.6.1
time="2015-12-17T10:11:43Z" level=info msg="Setting log level" logLevel=info
time="2015-12-17T10:11:43Z" level=info msg="Starting go-machine-service..." gitcommit="4c789a5"
```

`192.168.10.5` is host's IP. However it could happily use `127.0.0.1` instead.

Further research shows that I can't ping 192.168.10.5 (host's IP) from the Rancher container. Docker bug or Rancher's?

**Comment by deniseschannon** [comment]
What version of Rancher are you running?

Also, how is your Rancher set up? Fresh install or upgraded? How many hosts? What OS version?

Were you able to get other containers running on the host? Are you able to ping from one network agent container to another if multiple hosts?

**Comment by deniseschannon** [comment]
@utrack If you can provide the requested information, please re-open. We create stacks all the time without these issues, so I need to understand your setup in order to try and reproduce.

**Comment by Slamper** [comment]
I experience the same thing on my deployment.

Rancher	v0.51.0
Cattle	v0.130.0
User Interface	v0.78.0
Rancher Compose	v0.7.0

The environment was upgraded several times and is a small environment of the rancher server and 2 additional hosts running CoreOS 835.9.0.
I am able to run my own Stacks but creation of stacks from the catalog fails as described by the issue creator.

Please reopen

**Comment by deniseschannon** [comment]
What version of docker are you running? Rancher doesn't work great with Docker 1.8.x and we got the issues fixed in Docker 1.9.1. 

Are you able to create a stack with a docker-compose.yml? If you go to "Add Stack", there is a section that allows you to add your own docker-compose.yml to immediately create a stack. Is it all catalog items or just a certain one?

**Comment by Slamper** [comment]
@deniseschannon I'm running Docker 1.9.1. The creation also fails when I use my own *rancher*-compose.yml when I go to "Add Stack". It also shows "No Services" in the Stack view after I create the stack from both the yml or the catalog

**Comment by deniseschannon** [comment]
@Slamper What is your rancher-setup? Is it standalone or multi node?

**Comment by Slamper** [comment]
@deniseschannon It's standalone.

**Comment by johnrengelman** [comment]
My rancher server has just started experiencing this same issue. Can't create empty stacks or create new stacks from a catalog entry.

**Comment by deniseschannon** [comment]
I haven't been able to reproduce and the engineer who worked on this is on vacation. When he gets back, I'll be asking him to take a look. 

Have you guys been able to find any workaround?

**Comment by deniseschannon** [comment]
Actually, a workaround would be to use the Rancher-compose CLI and upload your docker-compose.yml and rancher-compose.yml templates using the CLI. For catalog entries, if you expand the "Preview", you should be able to see the templates.

**Comment by deniseschannon** [comment]
Also, do you have rancher-server on the same machine as your rancher-agents?

**Comment by Slamper** [comment]
@deniseschannon The Server and agents are in different machines. I found out that when I restart the server everything works for about a day and the timeouts again until I restart it.

**Comment by Moridinmhael** [comment]
adding my comment into this, experiencing much the same problem, and just get progressively worse.

**Comment by ibuildthecloud** [comment]
Now all services that are launch from cattle (go-machine-service, rancher-compose-executor), will use localhost by default.  https://github.com/rancher/cattle/pull/1419

**Comment by deniseschannon** [comment]
If anyone faces this issue in a v1.0.0+ release, please re-open.

**Comment by bnenu** [comment]
Hi,

The same problem seems to appear with creating new projects in a swarm environment from a docker-compose file.

io.cattle.platform.async.utils.TimeoutException
	at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1.run(RetryTimeoutServiceImpl.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Rancher version v1.1.0-dev1
- Fresh install, Standalone
- Host Ubuntu 14.04.4 LTS
- Docker 1.11.1
- Rancher server is o a different machine (Ubuntu 14.04.4LTS, Docker 1.11.1 different network)
I was able to create single containers on the host from the CLI, everything else seems to work.

**Comment by deniseschannon** [comment]
Are you able to create empty projects? Or does it only fail when passing in a docker-compose.yml?

**Comment by mostafahussein** [comment]
I have similar issue with the wordpress catalog and custom catalog with the following error, I don't know what could cause such errors:

```
io.cattle.platform.async.utils.TimeoutException: Timeout
	at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl.retry(RetryTimeoutServiceImpl.java:43)
	at sun.reflect.GeneratedMethodAccessor390.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

![screenshot from 2017-01-06 14-58-44](https://cloud.githubusercontent.com/assets/4104127/21718539/c948cb04-d420-11e6-9f5e-28b37acd0d91.png)


| Rancher  |  1.2.1  | 
|---|---|
|  Docker |1.12.2   |
| Hosts  | Ubuntu  | 

What should I do ? Passing the docker-compose.yml to the form or creating the stack by selecting it from a catalog both have the same issue
