### ISSUE TITLE
Validate setting service_cluster_ip_range, cluster_cidr, service_cluster_ip_range, cluster_dns_server.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#30522]
Validate the following settings in cluster.yml

<img width="666" alt="Screen Shot 2020-12-15 at 12 45 53 PM" src="https://user-images.githubusercontent.com/4266958/102410315-3ff35f00-3fa5-11eb-9461-bf929c8ac8d8.png">

Essentially the address will be split into 2 x 16 bit networks.
as the 198.18.0.0/15 range includes the ranges
198.18.0.0/16
198.19.0.0/16
and applied in the cluster.yaml as shown in the picture in the thread.

gz#13371

**Comment by sangeethah** [comment]
![image (2)](https://user-images.githubusercontent.com/4266958/105051528-b1e71a00-5a23-11eb-8231-27781b6c09a4.png)

**Comment by izaac** [comment]
Rancher `v2.5.5`

Local HA RKE cluster using the settings above described.
Downstream RKE DO cluster using the same settings described.

- Automation test suite passed on the downstream cluster.
- Manual checks done on Ingress, Backup/Restore, nodeport, clusterIp tests.

Charts testing is in progress and I will update the results here in a new comment.

**Comment by izaac** [comment]
Rancher `v2.5.5`

Local HA RKE cluster using the settings above described. `v1.19.6-rancher1-1`
Downstream RKE DO cluster using the same settings described. `v1.19.6-rancher1-1`

v1 Charts:

- Istio `1.5.900`
- Monitoring `0.2.0`
- logging `0.2.3`
- Pipelines `rancher/pipeline-jenkins-server:v0.1.4`
- Alerts `0.2.0`


v2 Charts:

- Logging `3.8.201`
- OPA Gatekeeper


Issues in v2 Charts opened:
Monitoring
https://github.com/rancher/rancher/issues/30901

Istio
https://github.com/rancher/rancher/issues/30902
