### ISSUE TITLE
Deleted nodes showing up in rancher UI with delete option disabled

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#30526]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1.Spin up a windows custom cluster with rancher 2.5.3 with k8s v1.16.15-rancher1-3
2.Upgrade the rancher to 2.5.4-rc5
3.Upgrade the k8s version from the UI to 1.17.14-rancher1-2 
4.Add in a few worker nodes to the custom cluster
5.Once they are active, delete the worker nodes from the UI page.
6.Now if we go back to the nodes page, we see all the deleted nodes appear in the UI with delete option disabled.

**Result:**
<img width="1526" alt="Screen Shot 2020-12-16 at 5 12 01 PM" src="https://user-images.githubusercontent.com/38144301/102425481-42b07d00-3fc2-11eb-9439-327612e525f3.png">

**Other details that may be helpful:**
We tried deleting existing worker nodes on one of the custom linux clusters we have, and the deleted worker node doesn't appear in the nodes page.
For the windows cluster, kubectl shows all the deleted nodes as well.
<img width="439" alt="Screen Shot 2020-12-16 at 5 20 37 PM" src="https://user-images.githubusercontent.com/38144301/102426230-ccad1580-3fc3-11eb-94c9-ee86ca105d85.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.5.4-rc5
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom

Rancher | v2.5.4-rc5
User Interface | v2.5.4-rc5
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher48

- Docker version (use `docker version`):

19.3.12

**Comment by kinarashah** [comment]
Note: This could happen on any custom cluster. Unrelated to windows cluster, @jiaqiluo saw this on a linux cluster as well.

**Comment by deniseschannon** [comment]
Does it happen on a fresh install of a cluster?
Does this only happen on upgraded Rancher clusters?
Does this only happen on upgraded k8s version clusters?

Is this consistent or intermittently?

**Comment by sowmyav27** [comment]
@deniseschannon This has happened on two different setups, just 2 times. One was on an upgraded setup(from 2.5.3) and the other one was on a fresh install air gapped setup on 2.5.4-rc

**Comment by kinarashah** [comment]
@sowmyav27 @anupama2501 Haven't been able to root cause this yet, it's not always reproducible. Could we enable `trace` logging on rancher server and try to reproduce again? That'd be of help to identify where is the issue.

**Comment by sowmyav27** [comment]
Additional validation:
- delete windows worker node and verify if it gets deleted from rancher

**Comment by sowmyav27** [comment]
**On 2.5.6-rc5**

- Deployed lInux and windows custom clusters.
- Deleted worker nodes.
- Nodes get deleted from the cluster.

**Comment by sowmyav27** [comment]
- Verified on upgrade from 2.5.5 to 2.5.6-rc6. 
- Deleted nodes are deleted from cluster and do not appear in rancher Nodes again.
- Verified on custom windows and linux clusters.
