### ISSUE TITLE
Add Digital Ocean Host fails

### ISSUE THREAD

**Issue by curratore** [rancher/rancher#3052]
I am trying to add a host from DO.
Added the token, an ubuntu image, http://get.docker.com, overlay filesystem, etc.
But always has the same final:

`Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (5) exceeded`

**Comment by curratore** [comment]
Here are the versions
![rancherscreenshot](https://cloud.githubusercontent.com/assets/1506358/11869500/9f3d22aa-a4c0-11e5-9b3d-aeb29e4e39b4.png)

**Comment by cjellick** [comment]
@curratore Unfortunately, that combination is not going to work.

The base OS used by docker-machine's digitalocean driver does not have the minimally required linux kernel version and does not have overlayfs enabled. It is using 3.13.0-71-generic and overlayfs [requires 3.18](https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/#configure-docker-with-the-overlay-storage-driver).

**Comment by cjellick** [comment]
I'm going to close this issue, but please refer to the referenced one for our plan to address.
