### ISSUE TITLE
Number of secrets rewritten during encryption process is seen incorrect

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30531]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster, and create some secrets
- K get secrets -A --> On the cluster gives 137 secrets
- enable secrets encryption

```
services:
  kube-api:
    secrets_encryption_config:
      enabled: true
```

- View in API of the cluster --> Do a rotateEncryptionKey action.
- Logs of rancher server show that 150 secrets have been rewritten.
- Logs in Rancher server:

```
2020/12/17 04:28:54 [INFO] cluster [c-fzvn2] provisioning: Rewriting cluster secrets
2020/12/17 04:29:02 [INFO] cluster [c-fzvn2] provisioning: [rewrite-secrets] 50 secrets rewritten
2020/12/17 04:29:14 [INFO] cluster [c-fzvn2] provisioning: [rewrite-secrets] 100 secrets rewritten
2020/12/17 04:29:26 [INFO] cluster [c-fzvn2] provisioning: [rewrite-secrets] 150 secrets rewritten
2020/12/17 04:29:29 [INFO] cluster [c-fzvn2] provisioning: [rewrite-secrets] Operation completed
```

**Expected Result:**
The exact secrets rewritten must be shown. (maybe it is rounded off to the next batch size)

**Other details that may be helpful:**
Related to the fix for - https://github.com/rancher/rancher/issues/27735

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `bb69b03`
- Installation option (single install/HA): Single node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE DO
- Kubernetes version (use `kubectl version`):

```
1.19 (Any)
```

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `bb69b03`**

- Deployed a custom RKE cluster. 
- Secrets available on the cluster : 52
- Enable secret's encryption on the cluster

```
2020/12/22 20:00:06 [INFO] cluster [c-n5qzv] provisioning: Rewriting cluster secrets
I1222 20:00:06.778829       8 request.go:645] Throttling request took 1.09226937s, request: PUT:https://104.236.38.91:6443/api/v1/namespaces/fleet-system/secrets/fleet-agent?timeout=30s
2020/12/22 20:00:15 [INFO] cluster [c-n5qzv] provisioning: [rewrite-secrets] 50 secrets rewritten
I1222 20:00:16.978691       8 request.go:645] Throttling request took 1.93807491s, request: PUT:https://104.236.38.91:6443/api/v1/namespaces/security-scan/secrets/default-token-jl5k7?timeout=30s
2020/12/22 20:00:17 [INFO] cluster [c-n5qzv] provisioning: [rewrite-secrets] Operation completed
2020/12/22 20:00:17 [INFO] cluster [c-n5qzv] provisioning: Finished building Kubernetes cluster successfully
```
Original issue stated is NOT seen - https://github.com/rancher/rancher/issues/30531#issue-770106230

However, can we add a log statement to show the total number of secrets encrypted?

**Comment by ryansann** [comment]
Thank you for that @sowmyav27 

I added additional logging to capture the total number of secrets rewritten as a part of [this PR](https://github.com/rancher/rke/pull/2387)

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `48254f94`**

Deploy a cluster and add some secrets in the cluster.
```
k get secrets -A | wc -l
174
```
Rotate encryption keys. Logs say
```
Rewriting cluster secrets
2020/12/23 21:58:16 [DEBUG] [rewrite-secrets] batch 1, retrieved 181 secrets from cluster
```
After the rewriting process, number of secrets: 176
```
k get secrets -A | wc -l
176
```

Question: why is there this mismatch? 
Reopening the issue

**Comment by superseb** [comment]
@sowmyav27 How much time was there between the commands? There are two possibilities I found that can cause difference in secret count:

* During the process, kube-apiserver restarts on each node and this causes additional default-token's to be created and cleaned up
* After the rewrite, at least one additional secret is created (rke-deployer-token)
* Each embedded kubectl session creates a new secret

Based on my testing, the numbers check out at the point retrieval. This was tested by querying the controlplane nodes continuously while rotating the encryption key (notice the `--no-headers` to not count the printed header:

```
while true; do kubectl get secrets -A --no-headers | wc -l; sleep 1; done
```

Also by using `kubectl get secrets -A`, you can check the AGE of the token to see if any new were created.

**Comment by sowmyav27** [comment]
@superseb Question: When only 52 secrets are available, why does it say "retrieved 60 secrets from cluster" ? 

- Deploy a cluster, enable secrets encryption
```
kubectl get secrets -A --no-headers | wc -l
52
```
- Do a rotate encryption on the cluster. Rancher logs show
```
2020/12/30 00:52:18 [DEBUG] [rewrite-secrets] batch 1, retrieved 60 secrets from cluster
2020/12/30 00:52:18 [DEBUG] [rewrite-secrets] All secrets retrieved and sent for rewrite
2020/12/30 00:52:20 [DEBUG] Triggering auth refresh on user-xtlqr
2020/12/30 00:52:20 [DEBUG] Skipping refresh for user-xtlqr due to max-age
2020/12/30 00:52:26 [INFO] cluster [c-cw586] provisioning: [rewrite-secrets] 50 secrets rewritten
2020/12/30 00:52:28 [DEBUG] removing old encryption key, provider config: [newKey]
2020/12/30 00:52:28 [INFO] cluster [c-cw586] provisioning: [rewrite-secrets] Operation completed, 60 secrets rewritten
```

**Comment by sowmyav27** [comment]
Agree with @superseb 's comments - https://github.com/rancher/rancher/issues/30531#issuecomment-751989521
During the rewrite process, new tokens are created and are deleted when the updating process of cluster is completed. And there is an increment of 1 secret.

Logging a separate issue to track this. - https://github.com/rancher/rancher/issues/30666

Closing this issue, tracking the fix/check on master branch  - https://github.com/rancher/rancher/issues/30667
