### ISSUE TITLE
Network Agent boot loop

### ISSUE THREAD

**Issue by utrack** [rancher/rancher#3053]
Network Agent's container enters bootloop on ` ip link add dev arpproxy type dummy` if `CONFIG_DUMMY` not set when compiling kernel. Maybe detect it and bail out?

**Comment by timbutler** [comment]
Also having this issue when attempting to run within a nested Linux container environment (Docker within a container). While it's a corner case, it'd be great to have this working in this environment.

**Comment by ibuildthecloud** [comment]
@timbutler What version of rancher?  We don't require dummy anymore so if this is still the case then we just left some legacy stuff around.

**Comment by timbutler** [comment]
@ibuildthecloud Sorry for not confirming earlier, this has been fixed in the newer releases and indeed working within a Linux container environment.

**Comment by ibuildthecloud** [comment]
@timbutler Cool thanks.  And Docker-in-Docker-in-Docker-in-Docker works just fine with rancher :)  Do it all the time.
