### ISSUE TITLE
load balancing 413 Request Entity Too Large 

### ISSUE THREAD

**Issue by lingdu0001** [rancher/rancher#30530]
Rancher versions:
2.5.3
rancher/server or rancher/rancher:
rancher/server
rancher/agent or rancher/rancher-agent:
rancher/rancher-agent
Infrastructure Stack versions:
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

Docker version: (docker version,docker info preferred)
18.03.1-ce
Operating system and kernel: (cat /etc/os-release, uname -r preferred)
centos7 3.10.0-862.3.3.el7.x86_64
Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
DO
Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher
Environment Template: (Cattle/Kubernetes/Swarm/Mesos)

Steps to Reproduce:
1.create new load balancing of the upload file service
2.upload file up to 4M
3.413 Request Entity Too Large

It was good before, but not ok after I upgraded to 2.5.3。
I have added this config as below:
nginx.ingress.kubernetes.io/proxy-body-size: 0

**Comment by superseb** [comment]
Please use the issue template from this repository when filing issues.

What kind of cluster are you working in? What version is that cluster as that determines what version of NGINX ingress controller used. Just upgrading Rancher does not change anything regarding ingress controllers in clusters, this would require an upgrade of the cluster you are working in (or Rancher's cluster but you are using single node). Does the NGINX ingress logs also log the error when you are trying to access (see https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-resources/#ingress-controller). Where did you apply the mentioned configuration? Both options are described in https://github.com/rancher/rancher/issues/14323, maybe they have changed in later NGINX versions.
