### ISSUE TITLE
loadbalance don't create container !!!!

### ISSUE THREAD

**Issue by xrain0610** [rancher/rancher#3054]
Component	Version
Rancher	v0.49.1
Cattle	v0.121.0
User Interface	v0.71.0
Rancher Compose	v0.6.1

I don't know why my loadbalance now have 0 containers, and it show the green status..

**Comment by xrain0610** [comment]
can't upload the image...
![Uploading 32.png…]()

**Comment by xrain0610** [comment]
Stacks LoadBalance  Service: 
 Shadowsocks
 
State: Active
Type: Load Balancer FQDN: None Scale: Global
Ports
Containers
Links
State	Name	IP Address	Host	Image (Command)	Stats	 
This service does not have any containers yet.

**Comment by xrain0610** [comment]
I find the problem , when i  select "Always run one instance of this container on every host" and set the scheduling options , it doesn't create container

**Comment by deniseschannon** [comment]
Do you have a host that would match the scheduling options? Do you have a host label that exists on one of the hosts so that the LB could launch containers?

**Comment by xrain0610** [comment]
yes ,  i only one host can access the public network, so  i set the label as "role=gate",  when i update the rancher to the v0.49.1  , the problem occured, I update the rancher server to v0.50.1 just now, the problem always occured, and I find the  rancher/agent-instance has new version v0.6.0 , but my system always deploy it use the version v0.5.0.

**Comment by xrain0610** [comment]
@deniseschannon yes , i only one host can access the public network, so i set the label as "role=gate", when i update the rancher to the v0.49.1 , the problem occured, I update the rancher server to v0.50.1 just now, the problem always occured, and I find the rancher/agent-instance has new version v0.6.0 , but my system always deploy it use the version v0.5.0.

**Comment by xrain0610** [comment]
@deniseschannon i see the log 2015/12/18 上午2:33:47INFO: Downloading agent http://hk.simcu.com:65534/v1/configcontent/configscripts
2015/12/18 上午2:33:47
2015/12/18 上午2:33:47gzip: stdin: not in gzip format
2015/12/18 上午2:33:47tar: Child returned status 1
2015/12/18 上午2:33:47tar: Error is not recoverable: exiting now
2015/12/18 上午2:33:47
The system is going down NOW!
2015/12/18 上午2:33:47
Sent SIGTERM to all processes
2015/12/18 上午2:33:48
Sent SIGKILL to all processes
2015/12/18 上午2:33:48
Requesting system reboot
2015/12/18 上午2:34:01INFO: Downloading agent http://hk.simcu.com:65534/v1/configcontent/configscripts
2015/12/18 上午2:34:02
2015/12/18 上午2:34:02gzip: stdin: not in gzip format
2015/12/18 上午2:34:02tar: Child returned status 1
2015/12/18 上午2:34:02tar: Error is not recoverable: exiting now
2015/12/18 上午2:34:02
The system is going down NOW!
2015/12/18 上午2:34:02
Sent SIGTERM to all processes
2015/12/18 上午2:34:03
Sent SIGKILL to all processes
2015/12/18 上午2:34:03
Requesting system reboot

**Comment by alena1108** [comment]
@xrain0610 can you check Rancher logs? "Child returned status 1" usually indicates that there is something wrong with haproxy config generation, and you should be able to see this error in Rancher logs.

**Comment by xrain0610** [comment]
the server logs (docker logs):
2015/12/18 上午2:40:422015/12/17 18:40:42 http: proxy error: net/http: request canceled
2015/12/18 上午2:40:472015-12-17 18:40:47,310 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [11] count [1]
2015/12/18 上午2:40:472015-12-17 18:40:47,310 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [19] count [1]
2015/12/18 上午2:40:472015-12-17 18:40:47,310 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [57] count [1]
2015/12/18 上午2:40:472015-12-17 18:40:47,310 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [82] count [1]
2015/12/18 上午2:40:472015-12-17 18:40:47,311 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [83] count [1]
2015/12/18 上午2:40:472015-12-17 18:40:47,311 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [84] count [1]
2015/12/18 上午2:40:472015-12-17 18:40:47,311 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [85] count [1]
2015/12/18 上午2:40:472015-12-17 18:40:47,311 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [98] count [1]
2015/12/18 上午2:40:472015-12-17 18:40:47,311 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [486] count [1]
2015/12/18 上午2:40:52time="2015-12-17T18:40:52Z" level=info msg="Registering backend for host [2caab249-3aa5-428f-958c-5aeb44642d0c]"
2015/12/18 上午2:40:522015-12-17 18:40:52,316 ERROR [:] [] [] [] [ecutorService-6] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [57] count [1]
2015/12/18 上午2:40:522015-12-17 18:40:52,316 ERROR [:] [] [] [] [ecutorService-6] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [84] count [1]
2015/12/18 上午2:40:52time="2015-12-17T18:40:52Z" level=info msg="Registering backend for host [7f29fa50-08c9-4624-bc5c-d3e44ba63424]"
2015/12/18 上午2:40:52time="2015-12-17T18:40:52Z" level=info msg="Registering backend for host [72554672-93bc-491b-9607-d71f00bc216e]"
2015/12/18 上午2:40:52time="2015-12-17T18:40:52Z" level=info msg="Registering backend for host [42895b05-765c-4b77-8782-0bc0852768ff]"
2015/12/18 上午2:40:53time="2015-12-17T18:40:53Z" level=info msg="Registering backend for host [0f4b5382-4d2a-43cc-bc9d-1a9849e7f033]"
2015/12/18 上午2:40:53time="2015-12-17T18:40:53Z" level=info msg="Registering backend for host [429e3e36-a82b-43fa-a33b-2fe40722ccf4]"
2015/12/18 上午2:40:53time="2015-12-17T18:40:53Z" level=info msg="Registering backend for host [d7ea4562-b46e-4334-890f-f5a28fc1a454]"
2015/12/18 上午2:40:53time="2015-12-17T18:40:53Z" level=info msg="Registering backend for host [a28532c7-a944-4e83-b2d1-7ce814203c7b]"
2015/12/18 上午2:40:56time="2015-12-17T18:40:56Z" level=info msg="Registering backend for host [60d7ee80-a68e-4e1a-8501-87b3d190e336]"
2015/12/18 上午2:41:51time="2015-12-17T18:41:51Z" level=error msg="Error during upgrade: [websocket: version != 13]"
2015/12/18 上午2:41:512015/12/17 18:41:51 http: multiple response.WriteHeader calls
2015/12/18 上午2:42:06time="2015-12-17T18:42:06Z" level=error msg="Error during upgrade: [websocket: version != 13]"
2015/12/18 上午2:42:062015/12/17 18:42:06 http: multiple response.WriteHeader calls

**Comment by alena1108** [comment]
@xrain0610 is it the only exception you are seeing? Could you try to create a new lb service the same way you've created your problematic one, and tail rancher logs. See if there are any other exceptions coming up

**Comment by xrain0610** [comment]
@alena1108  I run a new lb ,
the logs:

2015/12/18 上午2:47:512015-12-17 18:47:51,483 ERROR [6ab20ced-519f-49aa-9c53-03c89531b1a1:321838] [instance:3775] [instance.start->(InstanceStart)->instance.allocate->(InstanceAllocate)] [] [cutorService-44] [c.p.a.e.i.AllocatorEventListenerImpl] No allocator handled [EventVO [id=4f9d6685-7ff9-4f19-b693-43f511aad84d, name=instance.allocate, previousNames=null, replyTo=reply.9720736743973859, resourceId=3775, resourceType=instance, publisher=null, transitioning=null, transitioningMessage=null, transitioningInternalMessage=null, previousIds=null, data={}, time=Thu Dec 17 18:47:51 UTC 2015, listenerKey=instance.allocate, transitioningProgress=null]]
2015/12/18 上午2:47:512015-12-17 18:47:51,493 ERROR [6ab20ced-519f-49aa-9c53-03c89531b1a1:321838] [instance:3775] [instance.start->(InstanceStart)->instance.allocate] [] [ecutorService-5] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: Failed to find a placement
2015/12/18 上午2:47:51	at io.cattle.platform.eventing.exception.EventExecutionException.fromEvent(EventExecutionException.java:53) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.eventing.impl.AbstractEventService.callSync(AbstractEventService.java:263) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.process.common.handler.EventBasedProcessHandler.handle(EventBasedProcessHandler.java:109) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.process.instance.InstanceAllocate.handle(InstanceAllocate.java:47) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:456) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:396) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:390) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:390) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:520) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:323) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:259) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:256) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:188) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:161) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:110) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:107) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.execute(AbstractObjectProcessLogic.java:131) [cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.process.instance.InstanceStart.allocate(InstanceStart.java:205) [cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.process.instance.InstanceStart.handle(InstanceStart.java:70) [cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:456) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:396) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:390) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:390) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:520) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:323) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:259) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:256) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:188) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:161) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:110) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:107) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:107) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:66) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at sun.reflect.GeneratedMethodAccessor445.invoke(Unknown Source) ~[na:na]
2015/12/18 上午2:47:51	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_91]
2015/12/18 上午2:47:51	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_91]
2015/12/18 上午2:47:51	at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135) [cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
2015/12/18 上午2:47:51	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_91]
2015/12/18 上午2:47:51	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_91]
2015/12/18 上午2:47:51	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_91]
2015/12/18 上午2:47:51
2015/12/18 上午2:47:512015-12-17 18:47:51,494 ERROR [6ab20ced-519f-49aa-9c53-03c89531b1a1:321838] [instance:3775] [instance.start->(InstanceStart)] [] [ecutorService-5] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [3775]

**Comment by alena1108** [comment]
@xrain0610 

this error indicates that we file to find a placement for the lb container. Most likely due to the ports already being in use on this host. Try changing public ports for your LB service to the ones that are not allocated already.

**Comment by xrain0610** [comment]
@alena1108  i can't upload the image to github T_T, 
can i give you my account ?  you can login my test enviroment, and the error also occourd,  i try to set the lb four random ports, but it  doesn't work~

**Comment by xrain0610** [comment]
@alena1108 I send you a email for my test enviroment,  please check your email (alena@rancher.com)  thanks.

**Comment by alena1108** [comment]
@xrain0610 we don't support random ports yet, its gonna be available only when the following PR gets merged: 

https://github.com/rancher/cattle/pull/1165

Just check what ports are in use by your existing services, and pick the one that is not in use

**Comment by xrain0610** [comment]
@alena1108 , thanks, but i mean that i try some unused port to create loadbalance  , but it can't work also.

**Comment by xrain0610** [comment]
@alena1108  I find the problem,   when i update to v0.49.0, my host lable doesn't have effect,  when I remove the host lable and re-set the lable ,  It work well.
