### ISSUE TITLE
Question about "Database usage close to the quota 500M"

### ISSUE THREAD

**Issue by eroji** [rancher/rancher#30544]
Using the default monitoring configuration and alerts, there is an alert for `Database usage close to the quota 500M` which is looking at the Prometheus metric for `sum(etcd_debugging_mvcc_db_total_size_in_bytes)`. I am unclear as to what exactly is this a quote of. On the controlplane nodes that I'm hosting etcd, there is sufficient disk space and I can see that the container is mounting out to `/var/lib/etcd`. I do not see any error/warnings in the etcd logs about running out of space, and there does not to be any configuration on etcd to cap the database size, which leads me to believe this 500M value is arbitrarily set. Can someone share the reasoning for this value, and if I need to take any necessary action for etcd? Can this alert be safely disregarded?

**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
NA

**Result:**
The "Database usage close to the quota 500M" alert is triggering

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 16C/32GB
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by Gallardo994** [comment]
Been running with this alert for over 6 months for sure, probably more. It can be safely ignored

**Comment by rwd5213** [comment]
Yeah, from what I can tell its just set wrong. The default storage size for etcd is 2GB, so if you are running 3 etcd nodes the max would be 6Gbs. I reset it to alarm at 5Gbs

**Comment by beatsandpics** [comment]
This has been described here:
https://support.rancher.com/hc/en-us/articles/360039216452?input_string=prometheus+alert%3A+database+usage+close+to+the+quota+500m

And the reduce the space follow:
https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/etcd/#etcd-space-errors
