### ISSUE TITLE
No default values set for secretsEncryptionConfig in a cluster created from API

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30558]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster through API
- `secretsEncryptionConfig` value is not set on the cluster. View in API of the cluster, `secretsEncryptionConfig` is NOT set

**Expected Result:**
- secretsEncryptionConfig should be set to false by default
```
"secretsEncryptionConfig": {
"enabled": false,
"type": "/v3/schemas/secretsEncryptionConfig"
},
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `bb69b039`
- Installation option (single install/HA): HA install(any)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom cluster
- Kubernetes version (use `kubectl version`):

```
1.19 (Any)
```

**Comment by deniseschannon** [comment]
We shouldn't' expect an explicit default that is set as the default is naturally false. so not having it in the config implies false.

**Comment by sowmyav27** [comment]
@deniseschannon This issue was closed in favor of the current on - https://github.com/rancher/rancher/issues/30560
UI is not able to handle this usecase. Only way would be to edit and set values in cluster.yml. Is that how we want it to be?

**Comment by deniseschannon** [comment]
Yes, if you need to see the default value, then it woudl be through the cluster.yml.
