### ISSUE TITLE
[ui] Edit as yaml not respecting case of keys

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#30555]
Running 2.5-head, when editing a cluster as yaml, at least one key is getting lower-cased when the API/k8s has the field capitalized

![Screen Shot 2020-12-18 at 1 23 04 PM](https://user-images.githubusercontent.com/13897607/102658159-3fd59980-4134-11eb-912b-ac92b9e750bd.png)
![Screen Shot 2020-12-18 at 1 22 47 PM](https://user-images.githubusercontent.com/13897607/102658165-43692080-4134-11eb-957d-33cc9152b21a.png)

**Comment by westlywright** [comment]
Adding my findings from our chat incase we need to revisit. 

>When looping through the fields to build the yaml we hit the `customConfig` in the `secretsEncryptionConfig` it has a type of `map[json]`. The UI takes that type `json` and tries to get the resources fields for it by doing a lookup on the schemas loaded into the global store and finds none. We dont have a schema for arbitrary json. All this causes us to fall into a branch where we camelToUnderline the key and grab the data off the field without processing any further [here](https://github.com/rancher/ui/blob/master/lib/shared/addon/components/cluster-driver/driver-rke/component.js#L1333-L1335)

**Comment by sowmyav27** [comment]
On an upgrade from 2.4.8 to 2.5-head - commit id: `bd660e16` this issue https://github.com/rancher/rancher/issues/30555#issue-771153222 is seen fixed.

- On 2.4.8, deploy a cluster, enable custom encryption of secrets on the cluster. 
- Upgrade rancher server to 2.5-head
- Edit cluster --> Edit as yaml --> Modify a value say max Unavailable worker, and save changes made.
- The params are sent as is to the API. 

<img width="333" alt="Screen Shot 2020-12-22 at 1 12 49 PM" src="https://user-images.githubusercontent.com/26032343/102933788-cac9d300-4457-11eb-8ff9-918e6c47b0cc.png">
<img width="346" alt="Screen Shot 2020-12-22 at 1 12 37 PM" src="https://user-images.githubusercontent.com/26032343/102933792-cc939680-4457-11eb-80c0-64702f30b12d.png">
