### ISSUE TITLE
Bogus Rancher DNS AAAA response

### ISSUE THREAD

**Issue by Osso** [rancher/rancher#3055]
This is the behavior in 0.49.1
14:33:45.271475 IP 10.42.154.232.59997 > 169.254.169.250.domain: 43130+ A? web-proxy. (27)
14:33:45.271568 IP 10.42.154.232.59997 > 169.254.169.250.domain: 25109+ AAAA? web-proxy. (27)
14:33:45.272229 IP 169.254.169.250.domain > 10.42.154.232.59997: 43130* 1/0/0 A 10.42.11.188 (43)
14:33:45.316767 IP 169.254.169.250.domain > 10.42.154.232.59997: 25109 0/1/0 (102)
14:33:45.829205 IP 10.42.154.232.46340 > 169.254.169.250.domain: 3416+ PTR? 250.169.254.169.in-addr.arpa. (46)

And this is the new behavior in 0.50.x
14:37:51.624377 IP 10.42.154.232.50098 > 169.254.169.250.domain: 41157+ A? web-proxy. (27)
14:37:51.624471 IP 10.42.154.232.50098 > 169.254.169.250.domain: 26770+ AAAA? web-proxy. (27)
14:37:51.624744 IP 169.254.169.250.domain > 10.42.154.232.50098: 41157* 1/0/0 A 10.42.11.188 (43)
14:37:51.626281 IP 169.254.169.250.domain > 10.42.154.232.50098: 26770 NXDomain 0/1/0 (102)

Answering NXDomain causes nginx to consider the domain as invalid
It triggers a situation similar to this https://www.kb.cert.org/vuls/id/714121
except in our case it's not really a vulnerability.

For nginx I disabled ipv6 querying to make it work with 0.50.1:
resolver 169.254.169.250 ipv6=off;

**Comment by thresheek** [comment]
This kind of behaviour is also outlined as bad in https://www.ietf.org/rfc/rfc4074.txt.

**Comment by sangeethah** [comment]
Tested with rancher-server version - V0.51.0-rc2

dig AAAA <service name>   returns status - NOERROR.
