### ISSUE TITLE
On the Cluster Explorer View State of Deployments is shown as unknown for k8s 1.20 clusters

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rancher#30556]
**Version:**
Rancher version: 2.5.3
K3S: v1.20.0-rc5+k3s1

**Describe the issue: **
On the Cluster Explorer View on the new UI, State of Deployments is shown as unknown with k3s as local cluster. Screenshot attached.

**Steps to reproduce:**
Create a two node cluster on a HA setup

**Other details that may be helpful:**
On Cluster Manager on the old UI, Deployment state is shown as Active. Screenshot attached

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Local
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):
```
kubectl version --short
Client Version: v1.18.2
Server Version: v1.20.0-rc5+k3s1
```

![image](https://user-images.githubusercontent.com/56045581/102664980-cab89300-4138-11eb-8196-163fb5c9f7e5.png)

![image](https://user-images.githubusercontent.com/56045581/102664367-752fb680-4137-11eb-8cd6-2c384def50fb.png)

**Comment by vincent99** [comment]
View in API one in dashboard? (enable Developer Tools in Prefs screen to get the action if not already there)

**Comment by ShylajaDevadiga** [comment]
State is not seen under metadata in the API
![image](https://user-images.githubusercontent.com/56045581/102668114-fdb25500-413f-11eb-966f-8b142f1f2ac3.png)

**Comment by ShylajaDevadiga** [comment]
Above issue is seen in imported k3s cluster as well only in k3s v1.20.0-rc5+k3s1. Rancher version 2.5.3
Issue is NOT seen in k3s v1.19.5+k3s2 (local or imported)

**Comment by skurfuerst** [comment]
Confirming, having the same issue.
Rancher for me runs on k3s HA cluster, and the cluster which exhibits this behavior is  v1.20.0+k3s2

**Comment by ibuildthecloud** [comment]
This is because k8s v1.20 has dropped the metadata.selfLink field which was being used.

**Comment by skurfuerst** [comment]
@ibuildthecloud aaaah that's a K8S field... understood. I thought it would be from rancher. thanks for the explanation ❤️

**Comment by skurfuerst** [comment]
Here a fix for Lens (might help for fixing) https://github.com/lensapp/lens/pull/1804/files

... and for all users: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25#issuecomment-742616668

**Comment by brandond** [comment]
Putting selfLink back via FeatureGate is just a temporary bodge though; it's gone for good in 1.21 so its removal needs to be handled properly.

**Comment by skurfuerst** [comment]
Hey @brandond - absolutely! Still it helps for me for the upcoming months :-)

**Comment by kennyatzeroeyes** [comment]
Also seeing this bug:

K3S: v1.20.0+k3s2

**Comment by brandond** [comment]
@kennyatzeroeyes yes, please read the issue history. Kubernetes 1.20 is not yet supported by any released version of Rancher.

**Comment by kennyatzeroeyes** [comment]
makes sense.. had this issue and found it being tracked here.. so just reporting that same behavior. is there any idea of how long it might take to resolve?

**Comment by brandond** [comment]
If you just want to follow the issue without me-tooing on a confirmed version incompatibility, you can hit the subscribe button over to the right of the comments. Right above the subscribe button is the milestone for this issue; if you click on that it'll tell you the expected due date for that release.

**Comment by kennyatzeroeyes** [comment]
ty @brandond very helpful and much appreciated

**Comment by BoBiene** [comment]
> Putting selfLink back via FeatureGate is just a temporary bodge though; it's gone for good in 1.21 so its removal needs to be handled properly.
> [kubernetes/kubernetes#80978](https://github.com/kubernetes/kubernetes/pull/80978)

How can i configure the --feature-gates=RemoveSelfLink=false for a k3s ?

I have tried:
````yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.20.0
apiServer:
  extraArgs:
    - --feature-gates=RemoveSelfLink=false
````

**Comment by skurfuerst** [comment]
@BoBiene you need to add command line arguments to the `k3s` invocation - as an example:

```
k3s --disable=traefik --disable=local-storage --disable-network-policy --flannel-backend=none --kube-apiserver-arg=feature-gates=EphemeralContainers=true,RemoveSelfLink=false  --kube-scheduler-arg=feature-gates=EphemeralContainers=true --kube-controller-manager-arg=feature-gates=EphemeralContainers=true  --kubelet-arg=feature-gates=EphemeralContainers=true
```

**Comment by anupama2501** [comment]
Verified the issue on v2.5-head [v2.5-3d62d5d656dd16cf5359edb87250715728c2822b-head] **k3s single install**.
k3s:  v1.20.2+k3s1

Rancher | v2.5-3d62d5d656dd16cf5359edb87250715728c2822b-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49


Steps followed:
Import k3s  single node into rancher.
Create a few workloads
Go to the dashboard page, and select all namespaces and in the deployment verify all of them are active. 

<img width="1105" alt="Screen Shot 2021-01-19 at 2 16 24 PM" src="https://user-images.githubusercontent.com/38144301/105101310-79673080-5a63-11eb-9a74-5deaaa2068ca.png">


On **k3s HA cluster**, followed same steps as above on v2.5-head [v2.5-3d62d5d656dd16cf5359edb87250715728c2822b-head].
k3s:  v1.20.2+k3s1

<img width="1109" alt="Screen Shot 2021-01-19 at 2 37 36 PM" src="https://user-images.githubusercontent.com/38144301/105102624-e975b680-5a63-11eb-8963-ccfb74575770.png">

**Comment by sowmyav27** [comment]
Reopening the issue to be validate don master-head.

**Comment by anupama2501** [comment]
Rancher master-head:
Rancher | master-3ba112acba52c36b87c2bf88c40a64c693fba41d-head
User Interface | vmaster-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

K3s version: K3Sv1.20.2+k3s1

For single and HA k3s cluster verified:
Import k3s single node/HA into rancher.
Create a few workloads
Go to the dashboard page, and select all namespaces and in the deployment verify all of them are active.

<img width="1124" alt="Screen Shot 2021-01-19 at 3 44 52 PM" src="https://user-images.githubusercontent.com/38144301/105107749-99035680-5a6d-11eb-8cca-175e6d43fd9f.png">
<img width="1099" alt="Screen Shot 2021-01-19 at 3 44 31 PM" src="https://user-images.githubusercontent.com/38144301/105107756-9acd1a00-5a6d-11eb-9ac1-ecdcba698baa.png">
