### ISSUE TITLE
Rotate encryption not shown in dropdown

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#30552]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
In Rancher launch an RKE cluster
Edit cluster
Enable `Secrets Encryption`
![Screen Shot 2020-12-18 at 12 00 55 PM](https://user-images.githubusercontent.com/57409052/102650821-b79dc700-4128-11eb-9d12-366856dabc8a.png)
Return to cluster view. Click on dropdown.

**Result:**
`Rotate Encryption Keys` is not available in the dropdown:
![Screen Shot 2020-12-17 at 5 07 17 PM](https://user-images.githubusercontent.com/57409052/102650978-ec118300-4128-11eb-8694-0dc0de21b3f1.png)

The option becomes available after refreshing the page:
![Screen Shot 2020-12-18 at 11 09 40 AM](https://user-images.githubusercontent.com/57409052/102650986-ef0c7380-4128-11eb-9213-ce56df43b37e.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5-head` `version bb69b03`
- Installation option (single install/HA): Single install

**Comment by westlywright** [comment]
This is not a bug, it was [designed this way](https://github.com/rancher/rancher/issues/30077#issuecomment-747638322). If the cluster is in a transitioning state the action will not show up in the UI until the cluster is done transitioning to prevent the user from shooting themselves in the foot.

**Comment by maggieliu** [comment]
@aaronRancher Can you close if you are ok with this.

**Comment by aaronRancher** [comment]
This issue is seen when cluster comes out of updating state. When cluster is in active state, `rotate encryption` is not always seen.
Reopening issue.

**Comment by sowmyav27** [comment]
@westlywright this issue was seen when a cluster was active. Exact steps (how I saw this issue)

- Enable secrets encryption in a cluster
- When the cluster comes back to Active, Click on "ellipsis" to see the action "Rotate encryption"
- Go to Cluster --> Snapshots page (any page)
- Navigate back to Cluster page (dashboard) to perform the action of rotating the key
- The Action will NOT be available. 
- Refresh the page(Hard refresh)
- The action will now be available on the cluster.

**Comment by westlywright** [comment]
@sowmyav27 my bad, I was able to reproduce with the extra info. Thanks.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 4297ee1` and `rancher\rancher:v2.5-head` `version bb69b03`

Tested with the steps above, `Rotate Encryption Keys` is available consistently:
![Screen Shot 2020-12-21 at 3 07 30 PM](https://user-images.githubusercontent.com/57409052/102826978-f2a93000-439e-11eb-8fa6-300a10e2dad9.png)
