### ISSUE TITLE
Last backup is not shown on encryption key rotation

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#30553]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
In Rancher launch an RKE cluster.
Edit cluster.
Enable Secrets Encryption.
![Screen Shot 2020-12-18 at 12 00 55 PM](https://user-images.githubusercontent.com/57409052/102653390-1fa1dc80-412c-11eb-8ba8-20827e698758.png)
Navigate to another page in rancher. (Settings for example)
Return to cluster view. Click dropdown.
Rotate Encryption Keys.
![Screen Shot 2020-12-18 at 11 09 40 AM](https://user-images.githubusercontent.com/57409052/102653416-26305400-412c-11eb-90fc-d88b57758a18.png)

**Result:**
The last backup is not shown:
![Screen Shot 2020-12-18 at 11 57 00 AM](https://user-images.githubusercontent.com/57409052/102655721-069b2a80-4130-11eb-8b6e-927bb637fcae.png)

Expected:
![Screen Shot 2020-12-18 at 12 26 16 PM](https://user-images.githubusercontent.com/57409052/102655716-0438d080-4130-11eb-93a7-81cc5507b008.png)
This bug is not always reproducible. It is most common while navigating through different Rancher pages and while refreshing the page. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5-head version` `bb69b03`
- Installation option (single install/HA): Single install

**Comment by westlywright** [comment]
@aaronRancher The easiest way to reproduce this is navigating to the Cluster level dashboard page (`c/c-<id>/monitoring`) and refreshing the page, if you open the modal at that point you will see the issue. I'll have the pr in shortly.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 4297ee1` and `rancher\rancher:v2.5-head` `version bb69b03`

Steps:
In Rancher launch an RKE cluster.
Edit cluster.
Enable Secrets Encryption.
Navigate to cluster dashboard.
Refresh the page.
Rotate Encryption Keys.

Result:
The last back up date is shown.
![Screen Shot 2020-12-21 at 3 18 45 PM](https://user-images.githubusercontent.com/57409052/102827916-b4147500-43a0-11eb-9f56-dc9ce199edde.png)
