### ISSUE TITLE
Update logging v1 to 0.2.3

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#30568]
Motivated by: https://github.com/rancher/rancher/issues/30279
Backport issue: https://github.com/rancher/rancher/issues/30569

Minimum validation: Logging v1 0.2.3 works on clusters with at least one Windows Server 1909 node, and in both VXLAN and Host GW configurations.

**Comment by sowmyav27** [comment]
**on 2.5-head - commit id: `bb69b03`**

- Deployed windows 1809 `Windows_Server-2019-English-Full-ContainersLatest` and 1909 `Windows server english core base` nodes clusters - 1 etcd, 1 control, 1 worker node linux and 3 windows worker nodes.
- Enabled cluster level logging using elastic search and Fluentd
- `0.2.3`rancher-logging app is deployed.
- Logging on the cluster works fine - Deployed workloads, logs seen in Kibana and fluentd container.

**Comment by sowmyav27** [comment]
**Verified logging on 2.5-head - commit id: `bd660e1`**

Logging v1 on linux cluster works fine. Version: 0.2.3

**Verified upgrade usecase from 2.5.3 to 2.5-head - commit id: `bd660e1`**

- Deploy a cluster, enable logging v1 - cluster level using elastic search.
- Upgrade rancher to 2.5-head.
- Logging is upgraded to 0.2.3
- Deploy some workloads. Logging v1 works on a linux cluster.
