### ISSUE TITLE
[2.4] Update logging v1 to 0.2.3

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#30569]
Motivated by: https://github.com/rancher/rancher/issues/30279
Original issue: https://github.com/rancher/rancher/issues/30568

Minimum validation: Logging v1 0.2.3 works on clusters with at least one Windows Server 1909 node, and in both VXLAN and Host GW configurations.

**Comment by sadiapoddar** [comment]
The fix on v2.4-4531-head, commit id be04d2d was verified by enabling logging fluentd and elasticsearch. 

Created a Linux cluster with
    - 3 worker nodes
    - 1 control plane
    - 3 etcd

1. Once the cluster was and running, created a few projects, workloads 
2.  Enabled elasticsearch logging on some of the cluster, and projects
3.  Verified the elasticsearch log server for the cluster and project level logs
4.   Enabled the fluentd logging for some of the clusters and workloads. and verified that fluentd server was receiving both
      cluster and project level logs.

fluentd logs
020-12-23 23:08:10.828311415 +0000 c-mpd7p:p-t57fr.var.log.containers.sadia-76bf6d7878-jkllh_ns1_sadia-b06e466e70c9819c60916b42e5724007c7b279650bf44ef446a8a7dff1dfe86c.log: {"log":"\u001b]0;root@sadia-76bf6d7878-jkllh: /\u0007root@sadia-76bf6d7878-jkllh:/# exit\r\n","stream":"stdout","docker":{"container_id":"b06e466e70c9819c60916b42e5724007c7b279650bf44ef446a8a7dff1dfe86c"},"kubernetes":{"container_name":"sadia","namespace_name":"ns1","pod_name":"sadia-76bf6d7878-jkllh","container_image":"ubuntu:xenial","container_image_id":"docker-pullable://ubuntu@sha256:3355b6e4ba1b12071ba5fe9742042a2f10b257c908fbdfac81912a16eb463879","pod_id":"243c271b-13a8-4d61-bec4-78ca582fb144","host":"ip-xxxxx","labels":{"pod-template-hash":"76bf6d7878","workload_user_cattle_io/workloadselector":"deployment-ns1-sadia"},"master_url":"https://1xxx:443/api","namespace_id":"61985ceb-2779-4561-b551-f41e5bb2ae95","namespace_labels":{"cattle_io/creator":"norman","field_cattle_io/projectId":"p-t57fr"}},"tag":"c-mpd7p:p-t57fr.var.log.containers.sadia-76bf6d7878-jkllh_ns1_sadia-b06e466e70c9819c60916b42e5724007c7b279650bf44ef446a8a7dff1dfe86c.log","log_type":"k8s_normal_container","projectID":"c-mpd7p:p-t57fr"}


log version
<img width="901" alt="Screen Shot 2020-12-23 at 2 05 57 PM" src="https://user-images.githubusercontent.com/72409237/103044276-d3dca200-4534-11eb-845a-d4f85172e288.png">

Cattle-logging pods
<img width="1214" alt="Screen Shot 2020-12-23 at 2 06 09 PM" src="https://user-images.githubusercontent.com/72409237/103044333-fcfd3280-4534-11eb-997f-7c36944c47f4.png">


elasticsearch logs

 0;root@sadiawk-65b6cbb54b-clgm5: /root@sadiawk-65b6cbb54b-clgm5:/# exit stream:stdout docker.container_id:50b35cb28667f4a17b18befe46ed283173f1370c25365795414a92d76f8adc2f kubernetes.container_name:sadiawk kubernetes.namespace_name:ns2 kubernetes.pod_name:sadiawk-65b6cbb54b-clgm5 kubernetes.container_image:ubuntu:xenial kubernetes.container_image_id:docker-pullable://ubuntu@sha256:3355b6e4ba1b12071ba5fe9742042a2f10b257c908fbdfac81912a16eb463879 kubernetes.pod_id:818b91a0-133e-4a27-b5c1-df4ead6ad206 kubernetes.host:ip-xxx kubernetes.labels.pod-template-hash:65b6cbb54b kubernetes.labels.workload_user_cattle_io/workloadselector:deployment-ns2-sadiawk kubernetes.master_url:https://xxxxx/api kubernetes.namespace_id:0bedfd1f-11ee-4219-ad05-a6e1290f567c kubernetes.namespace_labels.cattle_io/creator:norman kubernetes.namespace_labels.field_cattle_io/projectId:p-qnggf tag:c-mpd7p:p-qnggf.var.log.containers.sadiawk-65b6cbb54b-clgm5_ns2_sadiawk-50b35cb28667f4a17b18befe46ed283173f1370c25365795414a92d76f8adc2f.log log_type:k8s_normal_container projectID:c-mpd7p:p-qnggf @timestamp:2020-12-23T23:21:20.056784191+00:00 _id:3q_okXYB9d1b7lSZQVmQ _type:container_log _index:linux-custom_proj2-2020-12-23 _score:0
