### ISSUE TITLE
Add ability to highlight text on table headers

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3057]
When there are errors in deploying a service/container, there is no easy way to grab the error except to take a screenshot.

<img width="308" alt="screen shot 2015-12-17 at 9 12 46 am" src="https://cloud.githubusercontent.com/assets/11410997/11876389/5b6f2ee6-a49e-11e5-95b5-da088422f34d.png">

**Comment by vincent99** [comment]
The state is not there anymore, and is selectable..
