### ISSUE TITLE
Review busybox container for rancher-audit-log

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#30583]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

The community busybox image (default) [used for the rancher-audit-log container](https://github.com/rancher/rancher/blob/master/chart/templates/deployment.yaml#L161) can be subject to rate limiting, review usage or the location where this is pulled.

gz#14039

**Comment by azbpa** [comment]
facing this issue currently that the busybox image can't be pulled due to Docker rate limits.

```
32m         Normal    Pulling             pod/rancher-7858c99595-x8pbb    Pulling image "busybox"
33m         Warning   Failed              pod/rancher-7858c99595-x8pbb    Failed to pull image "busybox": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Is there already some workaround? Or is it planed to put this image under the Rancher namespace?

**Comment by deniseschannon** [comment]
It looks like this was at least mitigated so that we would only pull the image if it wasn't already present. https://github.com/rancher/rancher/pull/30648
