### ISSUE TITLE
Unable to login as admin after restore, Cause: found more than one users with username admin

### ISSUE THREAD

**Issue by mverleun** [rancher/rancher#30588]
**What kind of request is this (question/bug/enhancement/feature request): bug**

**Steps to reproduce (least amount of steps as possible):**
1. Create a backup job using the Rancher Backup GUI and store the backup in a S3 bucket.
2. Wait for the backup job to complete.
2. Wipe the nodes of the cluster clean.
3. Re-install Rancher on these nodes using RKE.
4. Restore the backup created in step 1 by creating a restore job through the GUI. Set the `prune` option to false.
5. Wait for the restore job to finish.
6. Logout of the cluster, wipe cookies and try to login as user admin again

**Result:**
The GUI will not allow you to login due to an 'unkown error'. Inspection of the logfiles reveales that this is because more than one users with the name admin are found. `[ERROR] API error response 500 for POST /v3-public/localProviders/local?action=login. Cause: found more than one users with username admin`

**Other details that may be helpful:**
This issue is similar to  #30242. 

It is not completely unexpected that this happens. An admin user is included in the backup. This user has a different name than the admin user that was created when Rancher was reinstalled.
Once the restore completes the system has two different users that share the name admin.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by philipsparrow** [comment]
I just experienced this too.
In case someone is looking for a workaround:
`kubectl get users -o yaml` to find the 2 `admin` usernames and change the username of one of them.
