### ISSUE TITLE
Default to IfNotPresent for the rancher-audit-log container

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#30582]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

Inline [with the `rancher` container](https://github.com/rancher/rancher/blob/master/chart/templates/deployment.yaml#L56), default to `IfNotPresent` for the busybox `rancher-audit-log` sidecar container in the helm chart.

gz#14039

**Comment by nickngch** [comment]
#27384

**Comment by nickngch** [comment]
I have a similar issue #27384

**Comment by cbron** [comment]
Putting in 2.5.5 for now assuming we all agree on PR, can bump depending on design and timing.

**Comment by thehejik** [comment]
In current rancher-2.5.6-rc4 after enabling audit logging by `helm upgrade [...] --set auditLog.level=1` I can see that sidecar  audit-log busybox container has:
``` yaml
    ...
    image: busybox
    imagePullPolicy: IfNotPresent
    name: rancher-audit-log
```

I also tried rancher-2.5.5 and the busybox container has `imagePullPolicy: Always` set there.

@bmdepesa may I close?

**Comment by thehejik** [comment]
This is done, we may continue on following v2.6 issue, closing
