### ISSUE TITLE
Docker Engine section in Add Host for Packet is on same line as Add Label

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3059]
Version 0.50.1

Steps;
1.  Go to Host Page
2.  Click on Add Host
3.  Select Packet

Results:  The Docker Engine section is messed up and showing up on same line as add label

![image](https://cloud.githubusercontent.com/assets/11514927/11877937/a79e6474-a4af-11e5-907e-29270cf28a0c.png)

Expected:
Should show up on next line like all other add pages.

**Comment by vincent99** [comment]
These are under an advanced options toggle now.

**Comment by tfiduccia** [comment]
Version - master 3.20
Verified fixed
