### ISSUE TITLE
[Logging v2] Parser and tail-db paths are not always accessible on RKE fluent-bit

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#30595]
The `fluent-bit` pods in logging v2 need to have consistent access to `tail-db` and `parsers.conf` in RKE logging configurations. The fix will most likely be in the [RKE subdirectory of the logging chart](https://github.com/rancher/charts/tree/dev-v2.5/charts/rancher-logging/templates/loggings/rke).

**Comment by izaac** [comment]
Rancher version `v2.5.5`

Reproduced by deleting one of the pods in the `rancher-logging-rke-aggregator` daemonset. 

After the pod is re-created i started observing this in the pods logs in the saemonset:

```
[2021/01/12 22:35:11] [error] [input:tail:tail.0] parser 'json' is not registered
[2021/01/12 22:35:11] [error] [sqldb] cannot open database /tail-db/tail-containers-state.db
[2021/01/12 22:35:11] [error] [input:tail:tail.0] could not open/create database
[2021/01/12 22:35:11] [ info] [sp] stream processor started
```

**Comment by izaac** [comment]
Rancher version `v2.5-head (01/12/2020)` _65a15b9_

I think the helm chart has some formatting issues in this Rancher version.
```

helm upgrade --install=true --namespace=cattle-logging-system --timeout=10m0s --values=/home/shell/helm/values-rancher-logging-3.8.201.yaml --version=3.8.201 --wait=true rancher-logging /home/shell/helm/rancher-logging-3.8.201.tgz
--
Tue, Jan 12 2021 4:34:55 pm | Release "rancher-logging" does not exist. Installing it now.
Tue, Jan 12 2021 4:34:56 pm | Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(DaemonSet.spec.template.spec.volumes[0]): unknown field "type" in io.k8s.api.core.v1.Volume, ValidationError(DaemonSet.spec.template.spec.volumes[1]): unknown field "type" in io.k8s.api.core.v1.Volume, ValidationError(DaemonSet.spec.template.spec.volumes[2]): unknown field "type" in io.k8s.api.core.v1.Volume, ValidationError(DaemonSet.spec.template.spec.volumes[3]): unknown field "type" in io.k8s.api.core.v1.Volume]


```

**Comment by izaac** [comment]
Opened: https://github.com/rancher/rancher/issues/30809 for the above mentioned issue.

**Comment by izaac** [comment]
Rancher version: `v2.5-head (01/15/2021)` _be9683f_
RKE DO cluster with k8s `v1.18.14`
Logging v2 chart version:  `3.8.201`

I changed the image in the `rancher-logging-rke-aggregator` to use the fluent-bit debug one:

`kubectl set image -n cattle-logging-system daemonset.apps/rancher-logging-rke-aggregator fluentbit=rancher/fluent-fluent-bit:1.6.4-debug`

Login to one of the pods in the daemonsets. Check the following paths:

`kubectl exec -n cattle-logging-system  -it rancher-logging-rke-aggregator-s7qr7 sh`

```
/tail-db
/fluent-bit/etc/fluent-bit.conf
```

Log out from the pod and remove one of the daemonset pods.
Wait for the pod to get recreated

Once it's recreated check each pod logs in the daemonset to not have these errors:

```
[error] [sqldb] cannot open database /tail-db/tail-containers-state.db
[error] [input:tail:tail.0] could not open/create database
```

Choose one pod and get in the shell again:

`kubectl exec -n cattle-logging-system  -it rancher-logging-rke-aggregator-s7qr7 sh`

Check the paths again they should exist. Specially /tail-db which was originally overwritten before the fix.

```
/tail-db
/fluent-bit/etc/fluent-bit.conf
```
