### ISSUE TITLE
rancher backup fails to run one-off to minio with CA data or with verification off

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#30591]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

- install rancher backup with no default storage engine
- configure a one-off backup to a minio endpoint
- include CA data

**Result:**

- backup fails to run 

```
ERRO[2020/12/22 19:01:05] error syncing 'rancher-backup': handler backups: open -----BEGIN CERTIFICATE----- 
<complete ca certificate follows>
-----END CERTIFICATE-----: file name too long, requeuing 
```

**Other details that may be helpful:**

Looks to me like the CA certificate is being stuffed into the filename parameter?

I also ran it without the CA data and with "skip tls verification" and it fails because it performs TLS verification:

```
ERRO[2020/12/22 19:12:20] error syncing 'backup-2020-12-22t1608': handler backups: failed to check s3 bucket:rancher-backups, err:Head https://minio.cl.monach.us/rancher-backups/: x509: certificate signed by unknown authority, requeuing 
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): K3s 1.19.4+k3s1

**Comment by t3hcr** [comment]
[Filed a similar issue yesterday ](https://github.com/rancher/rancher/issues/31238) and looks like maybe we're having the same issue @oskapt - will follow along here too.

**Comment by mosesdd** [comment]
@oskapt according to the documentation the CA data should be added bas64 encoded. https://rancher.com/docs/rancher/v2.5/en/backups/configuration/backup-config/#s3
but anyway, I get the same error with the base64 string
