### ISSUE TITLE
前端底部导航栏在Chrome上会停在页面中间挡住页面

### ISSUE THREAD

**Issue by zhaoge26** [rancher/rancher#30600]
*Describe your issue here*

前端网页，最底部的导航栏，总是不能自动到底部位置，经常停在中间界面，挡住了部分页面。
Chrome 版本 87.0.4280.88（正式版本） (x86_64)

一张图正常，另一张图把“保存”按钮给挡住了...换到Safari就正常。

<img width="1406" alt="屏幕快照 2020-12-23 上午11 47 50" src="https://user-images.githubusercontent.com/10614875/102957303-0e364700-4515-11eb-9583-68f4bb607c7f.png">

<img width="1436" alt="屏幕快照 2020-12-23 上午11 47 57" src="https://user-images.githubusercontent.com/10614875/102957286-fe1e6780-4514-11eb-8f94-c625a2ee8a61.png">

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.3` UI: `v2.5.3` |
|Route|`undefined`|

**Comment by Martion2017** [comment]
同样的情况，我已经解决了，不是rancherui的问题，是因为我在chrome中安装了adblock插件，关闭去广告插件后问题解决。
