### ISSUE TITLE
forwardport: Cluster Private Registry setting not adhered to when pulling rancher-agent image during Node Driver cluster provisioning

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#30605]
forward port: https://github.com/rancher/rancher/issues/26366

gz#13629

**Comment by ryansann** [comment]
I will hold off on merging the linked forwardport PRs until the [original issue](https://github.com/rancher/rancher/issues/26366) has been tested and validated by QA

**Comment by slickwarren** [comment]
I was able to successfully add a DO cluster through an insecure private registry on v2.5.6-rc3

all images were pulled through the private registry successfully.  
Repro steps: 
* create rancher server on version 2.5.6-rc3
* create private registry
* configure private registry for insecure access, download load/save images for release 2.5.6-rc3
* create DO template in rancher, pointing to your insecure private registry
* add  Digital Ocean Node Driver cluster with Private Registry configured
* wait for new cluster to provision, login to cluster and `docker ps` to verify source of images all match your private registry

(note: insecure private registry not required for repro)
I was able to validate the following on 2.5.6-rc3
```
Scenario 1
While creating a node driver cluster, the incorrect username and/or password are specified in the private registry configuration.

Result:
When navigating to Cluster > Nodes, the user will see an authentication error for each node

Solution:
Navigate to Cluster > Nodes, choose Edit Cluster and reenter the private registry credentials correctly and save changes. When the node provisioning is retried with valid credentials, it will succeed.

Scenario 2
While creating a node driver cluster, an incorrect registry url is provided

Result:
When navigating to Cluster > Nodes, the user will see an error like dial tcp: lookup bad.host: no such host

Solution:
Navigate to Cluster > nodes, choose Edit Cluster and reenter the correct registry url and credentials, then save changes. When the node provisioning is retried with a valid registry url and credentials, it will succeed.
```
