### ISSUE TITLE
forward port: Rancher Istio chart injection-template is behind Istio master

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#30604]
forwardport :https://github.com/rancher/rancher/issues/28950

**Comment by anupama2501** [comment]
The issue has been verified on Rancher version 

Rancher | v2.5-2ae4cf117ac988ce409ca0617d246008f74c7aaa-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher50


Istio Version[1.5.901]
Monitoring[0.2.0]

Steps performed:
Create a cluster and in the tools --> istio[version 1.5.901] --> enable, tools --> monitoring[0.2.0] --> enable
Create a namespace and add the label to enable sidecar istio-injection=enabled
Deploy a workload in the above namespace with the container image "ubuntu:xenial" and adding the annotations:
sidecar.istio.io/proxyCPU=111m
sidecar.istio.io/proxyCPULimit=222m
sidecar.istio.io/proxyMemory=111Mi
sidecar.istio.io/proxyMemoryLimit=222Mi

With the new fix, the annotations in the pod are displayed accordingly:
<img width="561" alt="Screen Shot 2021-01-29 at 3 51 16 PM" src="https://user-images.githubusercontent.com/38144301/106339269-e8563d80-624a-11eb-898d-1505d36788a7.png">
<img width="526" alt="Screen Shot 2021-01-29 at 3 49 01 PM" src="https://user-images.githubusercontent.com/38144301/106339288-fe63fe00-624a-11eb-8ad9-2ab353b2c889.png">
