### ISSUE TITLE
Flannel Backend and Project Network Isolation input fields do NOT seem to have any value selected in Dark mode.

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30608]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Enable "Dark mode" on rancher
- Create a custom cluster with `Flannel Backend` and Host GW/VXLAN selected; A windows enabled cluster
- Click on "Next" and done.
- Click on Edit cluster.
- Flannel Backend and Project Network Isolation input fields do NOT seem to have any value selected.

**Light mode:**
<img width="885" alt="Screen Shot 2020-12-22 at 10 05 40 PM" src="https://user-images.githubusercontent.com/26032343/102965326-7b5cc480-44a2-11eb-8c22-9489f55170f5.png">

**Dark mode:**
<img width="975" alt="Screen Shot 2020-12-22 at 10 05 26 PM" src="https://user-images.githubusercontent.com/26032343/102965332-7dbf1e80-44a2-11eb-8910-53b2dfba76b9.png">

**Expected Result:**
Values selected should be visible

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `bd660e161d`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.19(Any)
```

**Comment by lvuch** [comment]
this is an issue with chrome, confirmed by @vincent99

**Comment by vincent99** [comment]
The display of radio, select, and checkboxes is entirely up to the OS & browser so there's nothing we can do to style these*.  Chrome on macOS uses transparency for disabled which makes it blend into the background.  If you look in Firefox they don't and they're still visible.

*: Other than to not use the native components in the first place. This is what Dashboard does and how they look different, but is not something I really want to get into at this point for the old UI.

**Comment by deniseschannon** [comment]
@sowmyav27 I added this to the v2.5.7 milestone so that you can close it because it's won't fix.

**Comment by sowmyav27** [comment]
Closing this issue
