### ISSUE TITLE
forward port: Node template values not changing while switching cloud credentials for vSphere 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#30601]
forward port: https://github.com/rancher/rancher/issues/30074

**Comment by sowmyav27** [comment]
PRs:
- https://github.com/rancher/ui/pull/4383
- https://github.com/rancher/ui/pull/4382

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version a10993e` and `rancher\rancher:v2.5-head` `version ac48370`

Steps:
Create vSphere credentials by following the steps detailed here #26997 (comment)
Create 2 cloud credentials.
In Rancher, create a new vSphere node template.
Switch between the credentials and see fields update.

Result:
Node template values update on cloud credential change.
![05cac098de82cc534da8b61dc5d06892](https://user-images.githubusercontent.com/57409052/105769996-e5421100-5f1b-11eb-8c67-24bc3e97de1b.gif)
