### ISSUE TITLE
[Backport] 2.4: V1 Logging on recently upgraded/created AKS clusters fails with "Connection reset by peer"

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#30618]
**Original Issue:**
https://github.com/rancher/rancher/issues/30425

**Comment by izaac** [comment]
Rancher version `v2.4.13-rc1 (01/12/2020)` 
rancher-logging v1 chart version: `0.2.4`
Azure AKS: `v1.18.10`
Docker: `19.3.12`

I left logging collecting the cluster container logs for 3 hours I didn't see the exception thrown on any of the fluentd containers.
Logs where flowing properly during this time window.

Logging provider: Elasticsearch `7.8.0`

Repro details: https://github.com/rancher/rancher/issues/30425#issuecomment-749581725
