### ISSUE TITLE
Launch template support in Rancher UI

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#30613]
The Ember UI should be updated to support the new launch template support in Rancher. Specifically, each managed node group can be broken up into two sections: "Nodes" and "Group"

The Nodes section should include:
- Launch template id and version drop downs
- GPU Enabled Instance checkbox (ignored if AMI in launch template, user responsibility)
- Spot instance checkbox
- Instance type dropdown (required if no template selected)
- Node volume size (required if no template selected)
- SSH Key dropdown
- AMI dropdown
- Resource tags (map display like current "Tags")
- User data (text area)

Caveats:

1. If a user selects a template id, then the versions dropdown should be selected and instance type, node volume size, ssh key, resource tags, and user data should all be hidden, greyed out, or possibly the other fields are populated from the instance template data.
2. If a user selects a template id and version and checks the "Spot instance" checkbox, there should be a warning with something like "Amazon recommends using spot instances in EKS with multiple instance types. Since the template you selected can have at most one instance type, your nodes may be interrupted more often."
3. If a user selects a template id and version and checks the "GPU Enabled" checkbox, then there should be a warning that this selection will be ignored if their launch template includes a custom AMI. Or hide/grey out the checkbox if the selected launch template version has a custom AMI, if possible.
4. If a user selects the "Spot Instance" checkbox and does not bring their own launch template, then they should be able to select multiple instance types. This is a recommendation of Amazon based on instance availability.

The Group section should include:
- Name (required)
- Desired, Maximum, and Minimum size (required)
- Labels
- Tags

Editing scenarios:
- If the node group is backed by a Rancher managed launch template, then everything is editable except for GPU Enabled and Spot Instances. If spot instances was selected then the instance types are also not editable.
- If a user specified their own template id and version, then only the template version is editable.

Rancher managed templates:
The launch templates created by Rancher should not be listed on in the UI for users to use and their own templates. All the Rancher managed templates have names that begin with `rancher-managed-lt-`. These can be filtered out so that a user cannot select these templates to be used with other node groups.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `` and master-head commit id: `98fe72a40`**

- Node sections have these fields:
```
- Launch template id and version drop downs
- GPU Enabled Instance checkbox (ignored if AMI in launch template, user responsibility)
- Spot instance checkbox
- Instance type dropdown (required if no template selected)
- Node volume size (required if no template selected)
- SSH Key dropdown
- AMI - Issue logged - https://github.com/rancher/rancher/issues/31293
- Resource tags (map display like current "Tags")
- User data (text area)
```
- Group details have fields:
```

- Name (required)
- Desired, Maximum, and Minimum size (required)
- Labels
- Tags

```
- Rancher managed node templates have names that begin with `rancher-managed-lt-` when seen in the AWS console. These arent visible/available in the Rancher UI.
- If the node group is backed by a Rancher managed launch template, then everything is editable except for GPU Enabled and Spot Instances.
- Points/Caveats from [here](https://github.com/rancher/rancher/issues/30613#issue-773898047) are validated. 
- Tracking related issues in separate tickets
