### ISSUE TITLE
Failed to create Pod sandbox occasionally stops Windows pods from deploying

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#30623]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Try to either add a Windows node from a cloud provider (e.g. GCE, AWS) onto a cluster or deploy the first Windows Pod onto a Windows Host that is already on the cluster.

**Result:**
Occasionally, the Pod that is being deployed (`cattle-node-agent-windows` on provisioning) will be stuck in `ContainerCreating`. 

A `kubectl describe` might reveal that this was caused by a `Failed create pod sandbox`, as shown here:
![Screen Shot 2020-12-19 at 8 29 23 PM](https://user-images.githubusercontent.com/13127443/102705165-3c780600-4239-11eb-82c8-73d3ae98a109.png)

And the kubelet logs might reveal that this was caused by a failure to access the instance metadata for your cluster, as shown here for GCE:

![Screen Shot 2020-12-19 at 8 06 56 PM](https://user-images.githubusercontent.com/13127443/102705007-88c24680-4237-11eb-80ab-c96e537240fe.png)

**Other details that may be helpful:**

Originally documented in https://github.com/rancher/rancher/issues/27911#issuecomment-748561838 but possibly misdiagnosed as a GCE specific problem.

If this happens to `cattle-node-agent-windows` (which sets up flannel, wmi_exporter, etc. on the host), it's possible that this can have weird effects on other Windows pods that are deployed / reliant on it (possibly the root cause of https://github.com/rancher/rancher/issues/27911).

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): dev

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom (Windows)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Ubuntu 18.04, Windows Server 1809/2019, Windows Server 1909
- Kubernetes version (use `kubectl version`): 1.19

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by aiyengar2** [comment]
Most likely related to something funky with the logic in https://github.com/rancher/rke-tools/blob/3863636eed1af4012dbad4a3c4477303ca75474b/windows/cloud-provider.psm1#L152-L180.

I noticed that the error appears shortly after kube-proxy or nginx-proxy is run on the host via rke-tools.

e.g. running `while(1){docker ps; curl 169.254.169.254; sleep 5}` outputted the following (where the IP address points to internal.metadata.google):

```
... <many more lines> ...

CONTAINER ID        IMAGE                                                                        COMMAND                  CREATED             STATUS              PORTS               NAMES
2c32461cce42        rancher/rke-tools:v0.1.68                                                    "pwsh -NoLogo -NonIn…"   22 seconds ago      Up 21 seconds                           nginx-proxy
ddd588a63388        rancher/hyperkube:v1.19.5-rancher1                                           "pwsh -NoLogo -NonIn…"   34 seconds ago      Up 33 seconds                           kubelet
7c7bfa1008e7        rancher/hyperkube:v1.19.5-rancher1                                           "pwsh -NoLogo -NonIn…"   46 seconds ago      Up 21 seconds                           kube-proxy
b71f5f04785d        rancher/rke-tools:v0.1.68                                                    "pwsh -NoLogo -NonIn…"   2 minutes ago       Up 8 seconds                            service-sidekick
7d00bb4a966f        rancher/rancher-agent:master-9c7419571a0bd8d82cac0139360623073ef0892e-head   "pwsh -NoLogo -NonIn…"   14 minutes ago      Up 14 minutes                           zealous_jackson
0.1/
computeMetadata/
CONTAINER ID        IMAGE                                                                        COMMAND                  CREATED             STATUS              PORTS               NAMES
2c32461cce42        rancher/rke-tools:v0.1.68                                                    "pwsh -NoLogo -NonIn…"   28 seconds ago      Up 26 seconds                           nginx-proxy
ddd588a63388        rancher/hyperkube:v1.19.5-rancher1                                           "pwsh -NoLogo -NonIn…"   40 seconds ago      Up 38 seconds                           kubelet
7c7bfa1008e7        rancher/hyperkube:v1.19.5-rancher1                                           "pwsh -NoLogo -NonIn…"   52 seconds ago      Up 2 seconds                            kube-proxy
b71f5f04785d        rancher/rke-tools:v0.1.68                                                    "pwsh -NoLogo -NonIn…"   2 minutes ago       Up 14 seconds                           service-sidekick
7d00bb4a966f        rancher/rancher-agent:master-9c7419571a0bd8d82cac0139360623073ef0892e-head   "pwsh -NoLogo -NonIn…"   14 minutes ago      Up 14 minutes                           zealous_jackson
0.1/
computeMetadata/
CONTAINER ID        IMAGE                                                                        COMMAND                  CREATED             STATUS              PORTS               NAMES
2c32461cce42        rancher/rke-tools:v0.1.68                                                    "pwsh -NoLogo -NonIn…"   33 seconds ago      Up 32 seconds                           nginx-proxy
ddd588a63388        rancher/hyperkube:v1.19.5-rancher1                                           "pwsh -NoLogo -NonIn…"   45 seconds ago      Up 43 seconds                           kubelet
7c7bfa1008e7        rancher/hyperkube:v1.19.5-rancher1                                           "pwsh -NoLogo -NonIn…"   57 seconds ago      Up 8 seconds                            kube-proxy
b71f5f04785d        rancher/rke-tools:v0.1.68                                                    "pwsh -NoLogo -NonIn…"   2 minutes ago       Up 19 seconds                           service-sidekick
7d00bb4a966f        rancher/rancher-agent:master-9c7419571a0bd8d82cac0139360623073ef0892e-head   "pwsh -NoLogo -NonIn…"   14 minutes ago      Up 14 minutes                           zealous_jackson
curl: (7) Failed to connect to 169.254.169.254 port 80: Network unreachable

**Comment by sirredbeard** [comment]
Are you still experiencing this issue?

**Comment by aiyengar2** [comment]
I haven't seen this recently @sirredbeard but I've only been working with Windows 1909 Server Core nodes recently. The issue here was with 1809/2019
