### ISSUE TITLE
Rancher fails to run jail command on first startup

### ISSUE THREAD

**Issue by WolfSkin0** [rancher/rancher#30631]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug/question
I'm not sure what to classify this as, as I don't know whether this is an error on my end or not.

**Steps to reproduce (least amount of steps as possible):**
1. Create 2 kubeadm nodes with openSUSE Kubic
2. Make one `control-plane, etcd` with `kubeadm init` and join the other as `worker`
3. Add weave CNI
4. Install cert-manager
5. Use helm to install rancher with letsEncrypt as issuer
6. Grab a rancher pod log

**Result:**
Rancher pods never deploy, healthz fails and they crash multiple times
https://hastebin.com/raw/icifimasaz

**Other details that may be helpful:**
Kubic does not use the docker runtime, I believe it uses CRI-O. I'm not sure whether that is the thing that would be causing the issue or not.

**Environment information**
- Rancher version: rancher-latest/rancher
- Installation option: 2-node non-HA with kubeadm (1 control-plane, etcd and 1 worker)

- `/etc/os-release`
```
NAME="openSUSE MicroOS"
# VERSION="20201221"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20201221"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20201221"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:MicroOS"
LOGO="distributor-logo"
```

- kernel = `5.9.14-1-default`

**Cluster information**
- Cluster type: Custom Hetzner kubeadm on openSUSE Kubic
- Machine type: KVM, 4vCPU, 8GB ram
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-16T00:00:00Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-16T00:00:00Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/27160

**Comment by cardoso81priscila** [comment]
@cardoso81priscila
![20201130_163940](https://user-images.githubusercontent.com/75869019/103154015-9ade4080-4773-11eb-92d9-b3922e917833.jpg)
#vamosjuntosparasempre
