### ISSUE TITLE
Question: Embed Metrics UI missing from v2.5.0 and above

### ISSUE THREAD

**Issue by ducthinh993** [rancher/rancher#30638]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**

**Result:**

Hi team, before v2.5.0, Rancher UI is embed with prometheus graph in deployment. It's really helpful for Rancher users ability to see their application metrics without access to grafana. Is there any plan to bring it back ?

Thanks alot.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): >= 2.5.0
- Installation option (single install/HA): any

**Comment by lopf** [comment]
We do have the same question. Any insights?
