### ISSUE TITLE
[UI] Cloning service doesn't clone labels

### ISSUE THREAD

**Issue by xaka** [rancher/rancher#3064]
Here is what service information looks like:
<img width="1420" alt="screen shot 2015-12-17 at 5 43 09 pm" src="https://cloud.githubusercontent.com/assets/504813/11887216/e1e2f10e-a4e6-11e5-979e-cc7ccedf0b4e.png">

And here is what cloning service looks like:
<img width="1439" alt="screen shot 2015-12-17 at 5 43 30 pm" src="https://cloud.githubusercontent.com/assets/504813/11887218/e79de0d6-a4e6-11e5-9841-197c739029ad.png">

Component | Version
--- | ---
Rancher | v0.50.1
Cattle | v0.127.0
User Interface | v0.74.0
Rancher Compose | v0.6.2

**Comment by deniseschannon** [comment]
This is a duplicate of https://github.com/rancher/rancher/issues/2342

But in v0.50.1, you should have UI options for most of the UI options for labels.

https://github.com/rancher/rancher/issues/2550

There is a small bug with container hostname when cloning again. 
https://github.com/rancher/rancher/issues/3045

**Comment by xaka** [comment]
Oh snap! My bad. I searched through issues and didn't find one.
