### ISSUE TITLE
[Forward port] - Enhancement for rke etcd encryption rewrite process - batch

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30646]
Forward port of - https://github.com/rancher/rancher/issues/28753

**Comment by ryansann** [comment]
Batch was forward ported in this PR:
- rancher/rke#2326

With additional logging forward ported in this PR:
- rancher/rke#2391

**Comment by sowmyav27** [comment]
**On master-head commit id: `eda2a07`**

- Deploy a cluster and add some secrets in the cluster.
- Rotate Encryption keys on the cluster
- logs in rancher server
```
2021/03/10 03:06:12 [DEBUG] [rewrite-secrets] retrieving cluster secrets with batch size: 250
```
