### ISSUE TITLE
Automate configuration of GitHub Authentication via Rancher 2 API?

### ISSUE THREAD

**Issue by snooyen** [rancher/rancher#30643]
**What kind of request is this (question/bug/enhancement/feature request):**
I'd like to automate the configuration of GitHub Authentication.

Watching the request flow I can see that I need to use the following API actions:
- "…/v3/githubConfigs/github?action=configureTest"
- "…/v3/githubConfigs/github?action=testAndApply"

However, I am unsure how to obtain the `code` parameter required by the testAndApply API action.
```
{
  "code": "????",
  "enabled": true,
  "githubConfig": {
    "actionLinks": {
      "configureTest": "https://my_rancher.com/v3/githubConfigs/github?action=configureTest",
      "testAndApply": "https://my_rancher.com/v3/githubConfigs/github?action=testAndApply"
    },
    "baseType": "authConfig",
    "created": "2020-12-18T17:49:11Z",
    "createdTS": 1608313751000,
    "creatorId": null,
    "enabled": true,
    "hostname": "github.com",
    "id": "github",
    "labels": {
      "cattle.io/creator": "norman"
    },
    "links": {
      "self": "https://my_rancher.com/v3/githubConfigs/github",
      "update": "https://my_rancher.com/v3/githubConfigs/github"
    },
    "name": "github",
    "tls": true,
    "type": "githubConfig",
    "uuid": "<REDACTED>",
    "scheme": "https://",
    "clientId": "<REDECATED>",
    "clientSecret": "<REDACTED>",
    "accessMode": "restricted",
    "allowedPrincipalIds": []
  },
  "description": "UI Session",
  "ttl": 57600000
}
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.3
- Installation option (single install/HA): HA on K8s

**Comment by vincent99** [comment]
The code comes from github and is given back to the browser after completion of the login.

The actions are to prevent users from shooting themselves in the foot with a broken config, but you don't need to use them if you're just trying to automate.  PUT the config directly to `/v3/githubConfigs/github`.
