### ISSUE TITLE
CPU, load, and memory increase after upgrading from v2.5.3 to v2.5.4-rc8

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#30652]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Upgrade a Rancher v2.5.3 environment to Rancher v2.5.4-rc8

**Result:**
On one node, CPU has jumped about 40% since upgrade. Memory jumped about 20% on same node:
![image](https://user-images.githubusercontent.com/468462/103332764-2c71da80-4a20-11eb-900e-1a39377fdc9e.png)

**Other details that may be helpful:**
Upgrade was at 18:59. Unknown if this can be reproduced on other environments.

Snapshot of top output on the node that had the memory/CPU jump:
```
Tasks: 171 total,   1 running, 170 sleeping,   0 stopped,   0 zombie
%Cpu(s): 62.5 us,  3.2 sy,  0.0 ni, 34.1 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem :   7710.5 total,    126.0 free,   6414.0 used,   1170.5 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   3192.3 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   1218 root      20   0 3271604   2.4g  54260 S  10.0  31.3  90:00.20 k3s-server
 453148 root      20   0 2675064   1.5g  42164 S   1.3  20.4   9:52.26 rancher
  10886 ubuntu    20   0   10.6g   1.2g  16600 S   0.3  15.5  29:10.56 prometheus
   8611 root      20   0  519828 313784  21048 S   0.3   4.0   4:49.23 agent
 471837 ubuntu    20   0  905876 212544  33360 S 110.0   2.7 110:33.43 fleetcontroller
   1268 root      20   0  290436 108276  34900 S   4.3   1.4  12:24.80 containerd
 471810 ubuntu    20   0  738404  73656  22872 S   0.3   0.9   0:59.09 gitjob
 473491 root      20   0  758972  67988  36824 S   0.0   0.9   0:19.86 fleetagent
 457400 ubuntu    20   0  739832  52776   9024 S   0.7   0.7   0:44.51 rancher-operato
 451232 472       20   0  757728  45644  12224 S   2.7   0.6   1:32.81 grafana-server
 455725 root      20   0  739228  43816   8840 S   0.0   0.6   0:05.66 webhook
   3283 systemd+  20   0  740656  42464   7860 S   0.3   0.5   1:47.79 nginx-ingress-c
   3367 systemd+  20   0  153428  40436   1772 S   0.0   0.5   0:22.87 nginx
   3368 systemd+  20   0  153288  40432   1832 S   0.0   0.5   0:38.91 nginx
```
The high CPU usage for fleetcontroller could be related to https://github.com/rancher/fleet/issues/185

**Comment by sowmyav27** [comment]
Not able to reproduce this issue on an upgrade from 2.4.11 to 2.5.3 to 2.5.4-rc8

**Steps:**

- Deploy a HA setup on 2.4.11. Enable monitoring on the local cluster.
- Deploy a downstream cluster. Run pre upgrade checks
- Upgrade rancher to 2.5.3
- No increase in CPU seen. 
- Go to Continuous Delivery
- Create a new Fleet repository. Used https://github.com/chrisurwin/fleet-demo.git and main branch. Named it f1 and add to this downstream cluster.
- Add a couple of more repos to this cluster and URL: `https://github.com/rancher/fleet-examples`
- The CPU usage now increases to 35 %

<img width="1413" alt="Screen Shot 2020-12-30 at 2 18 34 PM" src="https://user-images.githubusercontent.com/26032343/103384418-355bbe00-4aab-11eb-8fa7-85345d18301f.png">
<img width="716" alt="Screen Shot 2020-12-30 at 2 20 20 PM" src="https://user-images.githubusercontent.com/26032343/103384422-3a207200-4aab-11eb-8612-b30a3200786d.png">

- Upgrade rancher to 2.5.4-rc8
- There is a spike for about 5 minutes and the CPU utilization comes back to 35-36%
- Delete repo `f1` added from above ^^^
- The CPU utilization goes down to 15%

<img width="1427" alt="Screen Shot 2020-12-30 at 2 22 10 PM" src="https://user-images.githubusercontent.com/26032343/103384482-7358e200-4aab-11eb-8d4d-5531953c4f88.png">

**Comment by dnoland1** [comment]
Looks like a new Git Repo was added a few hours before the upgrade yesterday and the bundles went into an error state about 15 minutes after the upgrade. The increase in CPU and memory is likely the result of https://github.com/rancher/fleet/issues/185 and not the upgrade.

**Comment by sowmyav27** [comment]
**Upgraded from 2.4.11 to 2.5.3 to 2.5-head - commit id: `48254f944`**

- Deploy a HA setup on 2.4.11. Enable monitoring on the local cluster.
- Deploy a downstream cluster. Run pre upgrade checks
- Upgrade rancher to 2.5.3
- No increase in CPU seen.
- Go to Continuous Delivery
- Create a new Fleet repository. Used https://github.com/chrisurwin/fleet-demo.git and main branch. Named it f1 and add to this downstream cluster. - Increased from 7 to 13%
- Add a couple of more clusters and repos to these clusters
- The CPU usage increased.
- Upgrade to 2.5-head.
- After about 10 minutes the fleet agent got updated to `fleet:0.3.200-rc6` in the local cluster
- And the CPU utilization went down to almost the original value - 8%
<img width="1255" alt="Screen Shot 2020-12-31 at 10 05 37 AM" src="https://user-images.githubusercontent.com/26032343/103421145-c1272600-4b4f-11eb-8592-2005514d27d4.png">
