### ISSUE TITLE
Helm failed to install rancher.

### ISSUE THREAD

**Issue by aliyunk8s** [rancher/rancher#30660]
Installing rancher with Helm，Chart version is 2.5.3，Now an error is reported when rancher's pod starts，Check the log with kubectl logs and find the following errors:
2020/12/31 09:27:16 [INFO] APIVersion project.cattle.io/v3 Kind SourceCodeCredential
2020/12/31 09:27:16 [INFO] APIVersion project.cattle.io/v3 Kind PipelineSetting
2020/12/31 09:27:16 [INFO] APIVersion metrics.k8s.io/v1beta1 Kind NodeMetrics
2020/12/31 09:27:16 [INFO] APIVersion metrics.k8s.io/v1beta1 Kind PodMetrics
2020/12/31 09:27:17 [INFO] Reconciling GlobalRoles
2020/12/31 09:27:17 [INFO] Reconciling RoleTemplates
2020/12/31 09:27:17 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:17 [ERROR] failed to call leader func: failed to add management data: error creating default pspt: the server does not allow this method on the requested resource (post podsecuritypolicytemplates.meta.k8s.io)
2020/12/31 09:27:19 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:21 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:22 [INFO] Reconciling GlobalRoles
2020/12/31 09:27:22 [INFO] Reconciling RoleTemplates
2020/12/31 09:27:22 [ERROR] failed to call leader func: failed to add management data: error creating default pspt: the server does not allow this method on the requested resource (post podsecuritypolicytemplates.meta.k8s.io)
2020/12/31 09:27:23 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:25 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:27 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:27 [INFO] Reconciling GlobalRoles
2020/12/31 09:27:27 [INFO] Reconciling RoleTemplates
2020/12/31 09:27:27 [ERROR] failed to call leader func: failed to add management data: error creating default pspt: the server does not allow this method on the requested resource (post podsecuritypolicytemplates.meta.k8s.io)
2020/12/31 09:27:29 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:31 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:32 [INFO] Reconciling GlobalRoles
2020/12/31 09:27:32 [INFO] Reconciling RoleTemplates
2020/12/31 09:27:32 [ERROR] failed to call leader func: failed to add management data: error creating default pspt: the server does not allow this method on the requested resource (post podsecuritypolicytemplates.meta.k8s.io)
2020/12/31 09:27:33 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:35 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:37 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:37 [INFO] Reconciling GlobalRoles
2020/12/31 09:27:37 [INFO] Reconciling RoleTemplates
2020/12/31 09:27:37 [ERROR] failed to call leader func: failed to add management data: error creating default pspt: the server does not allow this method on the requested resource (post podsecuritypolicytemplates.meta.k8s.io)
2020/12/31 09:27:39 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:41 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:42 [INFO] Reconciling GlobalRoles
2020/12/31 09:27:42 [INFO] Reconciling RoleTemplates
2020/12/31 09:27:42 [ERROR] failed to call leader func: failed to add management data: error creating default pspt: the server does not allow this method on the requested resource (post podsecuritypolicytemplates.meta.k8s.io)
2020/12/31 09:27:43 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:45 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:47 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:47 [INFO] Reconciling GlobalRoles
2020/12/31 09:27:47 [INFO] Reconciling RoleTemplates
2020/12/31 09:27:47 [ERROR] failed to call leader func: failed to add management data: error creating default pspt: the server does not allow this method on the requested resource (post podsecuritypolicytemplates.meta.k8s.io)
2020/12/31 09:27:49 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:51 [INFO] Waiting for initial data to be populated
2020/12/31 09:27:52 [INFO] Reconciling GlobalRoles
2020/12/31 09:27:52 [INFO] Reconciling RoleTemplates
2020/12/31 09:27:52 [ERROR] failed to call leader func: failed to add management data: error creating default pspt: the server does not allow this method on the requested resource (post podsecuritypolicytemplates.meta.k8s.io)
......
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=Project workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=RkeK8sSystemImage workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=AuthConfig workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=PodSecurityPolicyTemplate workers
W1231 09:28:00.968025       7 reflector.go:425] pkg/mod/github.com/rancher/client-go@v1.19.0-rancher.1/tools/cache/reflector.go:157: watch of *v3.DynamicSchema ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
W1231 09:28:00.968055       7 reflector.go:425] pkg/mod/github.com/rancher/client-go@v1.19.0-rancher.1/tools/cache/reflector.go:157: watch of *v3.MultiClusterApp ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
W1231 09:28:00.968070       7 reflector.go:425] pkg/mod/github.com/rancher/client-go@v1.19.0-rancher.1/tools/cache/reflector.go:157: watch of *v3.Pipeline ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=DynamicSchema workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=ProjectLogging workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=CisConfig workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=GlobalDns workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=RkeK8sServiceOption workers
2020/12/31 09:28:00 [INFO] Shutting down project.cattle.io/v3, Kind=SourceCodeCredential workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=MultiClusterAppRevision workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=UserAttribute workers
W1231 09:28:00.968090       7 reflector.go:425] pkg/mod/github.com/rancher/client-go@v1.19.0-rancher.1/tools/cache/reflector.go:157: watch of *v3.GlobalRole ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
W1231 09:28:00.968111       7 reflector.go:425] pkg/mod/github.com/rancher/client-go@v1.19.0-rancher.1/tools/cache/reflector.go:157: watch of *v3.ProjectLogging ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=Node workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=Token workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=NodePool workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=NodeDriver workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=ClusterRoleTemplateBinding workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=Group workers
W1231 09:28:00.968526       7 reflector.go:425] pkg/mod/github.com/rancher/client-go@v1.19.0-rancher.1/tools/cache/reflector.go:157: watch of *v3.ProjectRoleTemplateBinding ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
2020/12/31 09:28:00 [INFO] Shutting down /v1, Kind=Namespace workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=User workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=ClusterTemplateRevision workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=Group workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=PodSecurityPolicyTemplateProjectBinding workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=UserAttribute workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=MultiClusterApp workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=User workers
2020/12/31 09:28:00 [INFO] Shutting down management.cattle.io/v3, Kind=ClusterRegistrationToken workers
W1231 09:28:00.969818       7 reflector.go:425] pkg/mod/github.com/rancher/client-go@v1.19.0-rancher.1/tools/cache/reflector.go:157: watch of *v3.KontainerDriver ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
W1231 09:28:00.969918       7 reflector.go:425] pkg/mod/github.com/rancher/client-go@v1.19.0-rancher.1/tools/cache/reflector.go:157: watch of *v3.AuthConfig ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
2020/12/31 09:28:00 [FATAL] leaderelection lost for cattle-controllers

**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
v1.15.6
```

- Docker version (use `docker version`):

```
19.03.8
```

**Comment by aliyunk8s** [comment]
Can someone answer that?

**Comment by hectoralicea** [comment]
I just came across this issue today. Any help would be appreciated. last line in kc log is:
```
2021/03/29 22:40:29 [INFO] Waiting for initial data to be populated
2021/03/29 22:40:31 [INFO] Waiting for initial data to be populated
2021/03/29 22:40:33 [INFO] Waiting for initial data to be populated
I0329 22:40:35.316580       8 leaderelection.go:253] successfully acquired lease kube-system/cattle-controllers
2021/03/29 22:40:35 [INFO] Steve auth startup complete
2021/03/29 22:40:35 [INFO] Starting catalog.cattle.io/v1, Kind=Operation controller
2021/03/29 22:40:35 [INFO] Starting /v1, Kind=Pod controller
2021/03/29 22:40:35 [INFO] Starting catalog.cattle.io/v1, Kind=App controller
2021/03/29 22:40:35 [INFO] Reconciling GlobalRoles
2021/03/29 22:40:35 [INFO] Reconciling RoleTemplates
2021/03/29 22:40:35 [INFO] Shutting down catalog.cattle.io/v1, Kind=App workers
2021/03/29 22:40:35 [INFO] Shutting down /v1, Kind=Pod workers
2021/03/29 22:40:35 [INFO] Shutting down catalog.cattle.io/v1, Kind=Operation workers
2021/03/29 22:40:35 [FATAL] leaderelection lost for cattle-controllers
```
