### ISSUE TITLE
[Forwardport] Number of secrets rewritten during encryption process is seen incorrect

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30667]
Forward port of https://github.com/rancher/rancher/issues/30531- for validating on master-head.

**Comment by ryansann** [comment]
[This comment](https://github.com/rancher/rancher/issues/30531#issuecomment-754136095) details why additional secrets are being seen. It is expected due to tokens being created. 

Moving to test.

**Comment by sowmyav27** [comment]
**On master-head commit id: `eda2a07`**

- Deploy a cluster and add some secrets in the cluster.
```
kubectl get secrets -A | wc -l
     308

```
- Rotate Encryption keys on the cluster
- logs in rancher server
```
2021/03/10 03:06:12 [DEBUG] [rewrite-secrets] retrieving cluster secrets with batch size: 250
2021/03/10 03:06:12 [INFO] cluster [c-67kqz] provisioning: [controlplane] Restarted kube-apiserver on controlplane nodes successfully
2021/03/10 03:06:12 [DEBUG] [rewrite-secrets] batch 1, retrieved 250 secrets from cluster
2021/03/10 03:06:12 [DEBUG] [rewrite-secrets] batch 2, retrieved 57 secrets from cluster
2021/03/10 03:06:12 [INFO] cluster [c-67kqz] provisioning: Rewriting cluster secrets
```

**Comment by sowmyav27** [comment]
Master PR: https://github.com/rancher/rke/pull/2391
