### ISSUE TITLE
[2.4] backport Release Arm fix for Rancher 2

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#30678]
https://github.com/rancher/rancher/issues/26906

**Comment by kinarashah** [comment]
https://github.com/rancher/kontainer-driver-metadata/pull/465

**Comment by kinarashah** [comment]
Available to test with dev-v2.4 KDM update, `rke-tools` has been updated to `v0.1.69`

| Kubernetes Version | Rancher Versions |
| --------- | ------ | 
| 1.18.15 | 2.4.5+ |
| 1.17.17 | 2.4.4+ |

**Comment by kinarashah** [comment]
`rke-tools` has been updated to `v0.1.69` also for the following versions: 
Kubernetes Version | Rancher Versions
-- | --
v1.16.15-rancher1-4 | 2.4.4+
v1.15.12-rancher2-8 | 2.4.6+

**Comment by deniseschannon** [comment]
The new confd image has been validated by the person hitting the specific machine issue.
