### ISSUE TITLE
[Keycloak using OIDC] - Create Authentication Calls

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#30676]
Be able to authenticate user through Keycloak using OIDC calls

**Comment by merlindorin** [comment]
Hi,

we have an integration with Keycloak (with extra controller) and this feature make my day.

Hope we will have support for group/role in the first iteration.

thx

**Comment by cbron** [comment]
Since we only made two issues in epic and other is closed, I am going to close this in favor of parent.
