### ISSUE TITLE
Wrong branch on catalog addition

### ISSUE THREAD

**Issue by shalev123d** [rancher/rancher#30682]
Hi,

We're trying to add a new catalog through the cluster explorer:

![image](https://user-images.githubusercontent.com/36129614/102757511-19a13b00-437a-11eb-90f3-939cb431d192.png)

when trying to install anything we get the error - "error: found in chart.yaml, but missing in charts/ directory: common"

So we viewed the rancher pod's logs and we're seeing:
`error syncing 'test7': handler helm-clusterrepo-ensure: git clone --depth=1 -n --branch master https://github.com/prometheus-community/helm-charts management-state/git-repo/test7/d01baf591873fcc91548afa8a7cdc16c5bb691b6a9de214b825ca8a2a2143104 error: exit status 128, detail: Cloning into 'management-state/git-repo/test7/d01baf591873fcc91548afa8a7cdc16c5bb691b6a9de214b825ca8a2a2143104'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
, requeuing`

it's trying to pull from master even though it's configured to pull from 'main'

Thanks!

**Comment by jiaqiluo** [comment]
Here is what I saw on v2.5-head fc09f27 single install

Steps:
- run v2.5-head fc09f27 single install
- add a cluster
- go to the cluster explorer -> Apps
- add the abovementioned repo
```
URL: https://github.com/prometheus-community/helm-charts
branch: main
```
- go to the `Charts` page

results:
The `Charts` page is stuck on the loading 

More info:
- the same repo can be added successfully in the catalog v1 in the cluster management UI
- and we can deploy apps from it.
![image](https://user-images.githubusercontent.com/6218999/103688477-151a7c00-4f4f-11eb-954a-ac5c8f62623b.png)

**Comment by jiaqiluo** [comment]
I cannot reproduce this bug on v2.5.3 single install 

Steps:
- run v2.5.3 single install
- add a cluster
- go to the cluster explorer -> Apps
- add the abovementioned repo
<img width="1864" alt="Screen Shot 2021-01-05 at 12 25 44 PM" src="https://user-images.githubusercontent.com/6218999/103690282-b30f4600-4f51-11eb-9b29-7d9c04a54cb0.png">

Results:
- I can see all apps in this repo 
![screencapture-206-189-173-155-dashboard-c-c-lkr5v-apps-charts-2021-01-05-12_30_35](https://user-images.githubusercontent.com/6218999/103690366-db974000-4f51-11eb-9bab-438c34f08ba9.png)

- and I can also install one of them
![screencapture-206-189-173-155-dashboard-c-c-lkr5v-apps-catalog-cattle-io-app-2021-01-05-12_28_22](https://user-images.githubusercontent.com/6218999/103690397-ebaf1f80-4f51-11eb-8909-82a86d16738d.png)
