### ISSUE TITLE
[Monitoring V2] Warn if cluster does not have minimum CPU / memory limits to deploy chart

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#30684]
Context: https://github.com/rancher/dashboard/issues/1849

Need to add the following annotations for the Monitoring V2 chart.

```yaml
catalog.cattle.io/requests-cpu: "<minimum-cpu>m"
catalog.cattle.io/requests-memory: "<minimum-memory>Mi"
```

Note: Unlike Monitoring V1, which dynamically calculates the memory / cpu required based on the number of nodes in the cluster, the minimum memory and minimum CPU that will trigger a warning for Monitoring V2 will be fixed. It will initially be set to the default amount of memory / cpu used by the Monitoring chart when deployed onto a 5 node RKE cluster with all cluster-specific exporters enabled.

**Comment by aiyengar2** [comment]
#### Original Resource Statistics

```bash
# Note: Limits do not account for PushProx or Prometheus Adapter deployments
arvindiyengar: ~/Downloads/test 
$ kubectl describe nodes | grep "Allocated resources:" -A 8
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests   Limits
  --------           --------   ------
  cpu                250m (6%)  0 (0%)
  memory             0 (0%)     0 (0%)
  ephemeral-storage  0 (0%)     0 (0%)
  hugepages-1Gi      0 (0%)     0 (0%)
  hugepages-2Mi      0 (0%)     0 (0%)
--
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests   Limits
  --------           --------   ------
  cpu                250m (6%)  0 (0%)
  memory             0 (0%)     0 (0%)
  ephemeral-storage  0 (0%)     0 (0%)
  hugepages-1Gi      0 (0%)     0 (0%)
  hugepages-2Mi      0 (0%)     0 (0%)
--
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                250m (12%)  0 (0%)
  memory             0 (0%)      0 (0%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
Events:
--
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                370m (18%)  0 (0%)
  memory             80Mi (4%)   170Mi (8%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
--
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                360m (18%)  10m (0%)
  memory             90Mi (4%)   190Mi (10%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
```

``` bash
arvindiyengar: ~/Downloads/test 
$ kubectl top nodes
NAME                        CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
arvind-monitoring-agent1    148m         3%     1311Mi          16%       
arvind-monitoring-agent2    136m         3%     1365Mi          17%       
arvind-monitoring-server1   1109m        55%    1659Mi          87%       
arvind-monitoring-server2   499m         24%    1554Mi          82%       
arvind-monitoring-server3   1750m        87%    1711Mi          90%  
```

#### Resource Statistics After Enabling Monitoring V2

```bash
# Note: Limits do not account for PushProx or Prometheus Adapter deployments
arvindiyengar: ~/Downloads/test 
$ kubectl describe nodes | grep "Allocated resources:" -A 8
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests      Limits
  --------           --------      ------
  cpu                1600m (40%)   2700m (67%)
  memory             1055Mi (13%)  2625Mi (33%)
  ephemeral-storage  0 (0%)        0 (0%)
  hugepages-1Gi      0 (0%)        0 (0%)
  hugepages-2Mi      0 (0%)        0 (0%)
--
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                550m (13%)  500m (12%)
  memory             260Mi (3%)  450Mi (5%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
--
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                350m (17%)  200m (10%)
  memory             30Mi (1%)   50Mi (2%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
Events:
--
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                470m (23%)  200m (10%)
  memory             110Mi (5%)  220Mi (11%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
--
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                460m (23%)  210m (10%)
  memory             120Mi (6%)  240Mi (12%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
```

```bash
arvindiyengar: ~/Downloads/test 
$ kubectl top nodes
NAME                        CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
arvind-monitoring-agent1    164m         4%     1650Mi          20%       
arvind-monitoring-agent2    231m         5%     1484Mi          18%       
arvind-monitoring-server1   308m         15%    1423Mi          75%       
arvind-monitoring-server2   184m         9%     1341Mi          70%       
arvind-monitoring-server3   221m         11%    1520Mi          80% 
```

####

**Comment by aiyengar2** [comment]
Based on the limits alone, we see that we need roughly:

- CPU: 2700 + 500 + 200 + 200 + 200 -> 3800m

- Memory: 2625 + 450 + 50 + 50 + 50 -> 3225Mi

*Note that this does not account for the memory limits required for Prometheus Adapter or PushProx (5x1 for proxy + 3x3 for etcd, controlplane, scheduler).*

And based on the actual memory / cpu used (based on kubectl top), we see:

- CPU: (164 + 231 + 308 + 184 + 221) - (91 + 93 + 257 + 191 + 205) -> 271m

- Memory: (1650 + 1484 + 1423 + 1341 + 1520) - (1308 + 1361 + 1539 + 1373 + 1400) -> 437Mi

#### Recommendation

In practice, the amount of memory used by Monitoring on a cluster without any real workloads is <1m CPU + <1Mi memory, but this doesn't account for actual clusters that this will be deployed on. Therefore, using the prescribed limits is a better bet for defining the minimum amount of memory required.

Assuming the 14 PushProxies + 1 Prometheus Adapter require roughly a minimum of 50m / 50Mi limits (since those aren't currently added to the Monitoring chart), I think we should add about 750m / 750Mi to the limits above, bringing us to an expectation of **around 4500m CPU + 4000Mi Memory** to deploy Monitoring V2 on the cluster.

#### How does this compare to the requirements for Monitoring V1 in our docs?

Similar. Based on [Rancher docs](https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.0.x-v2.4.x/cluster-monitoring/#resource-consumption-of-prometheus-pods), a 5 node setup sets its memory limits to roughly
- CPU: 3400m
  - Prometheus: 1000 + 100 + 500 + 50 + 100
  - Grafana: 50 + 50 + 200 + 100
  - Other: 100 + 200 + 200 + (100 x 5) + 100 + 100 + 50
- Memory: 2755Mi
  - Prometheus: 1000 + 100 + 200 + 50 + 25
  - Grafana: 50 + 50 + 200 + 100
  - Other: 200 + 200 + 100 + (30 x 5) + 130 + 150 + 50

Considering updates to the underlying components and the addition of PushProxies + Prometheus Adapter, an increase of around 1100m and 1245Mi seems like a conservative bet, although I don't think that amount is strictly required.

**Comment by jiaqiluo** [comment]
The enhancement is validated on monitoring v2 chart `v9.4.203-rc04` on  v2.5-head a85f4d1

Steps:
- run rancher in single-install 
- create a downstream cluster
- go to the dashboard to install monitoring v2 chart `v9.4.203-rc04`
- go to the `installed app` page, view the app rancher-monitoring in API

Results:

The following annotations are applied on the app

<img width="638" alt="Screen Shot 2021-02-23 at 5 28 27 PM" src="https://user-images.githubusercontent.com/6218999/108927531-af1cad80-75fd-11eb-9ea5-987d2ed48430.png">
