### ISSUE TITLE
Old Apps showing in Explorer but not in ClusterManager

### ISSUE THREAD

**Issue by jsbrain** [rancher/rancher#30695]
Hello,

I just upgraded to v2.5.3 from v2.4.11. Now I noticed that in the new Explorer view there are old application deployments listed that I deleted months ago. They were not showing in v2.4.11 but now in v2.5.3 they are. When I try to delete them via the GUI I get an Error stating: "Error: uninstall: Release not loaded: ghostdb3: release: not found"

So apparently there are some kind of old "artifacts" of those applications but the releases/apps are actually not running anymore and should have been deleted completely. When I try to run `helm ls` manually they don't show up either. Not sure if this is somehow related to my upgrade from helm2 to helm3 but I don't know if that would explain why they are showing up in the Explorer View but not in the ClusterManager View ... 🤷🏻‍♂️

So my actual question: How can I clean this up? Some idea where I could find and delete the data/config files that are causing this?

Thanks!

**Comment by kfastov** [comment]
I have this issue in v2.5.5. After upgrading from v2.4.2 there are some applications left from the monitoring which was enabled in the cluster manager. When I try to uninstall them, it throws the same error. `helm ls -A` output does not include these apps either.
