### ISSUE TITLE
During edit of a vSphere node template some fields don't get populated with the previously set values

### ISSUE THREAD

**Issue by sadiapoddar** [rancher/rancher#30690]
v2.5-head, commit 0588087

Steps to repro
1. Create a node temple by adding especially network, deployment from either temple, content lib, and the template name and save
2.  Click on an edit of the previously created node temple
2. Notice that the following fields are blank and don't show what were the fields were selected before

<img width="1872" alt="Screen Shot 2021-01-05 at 1 51 53 PM" src="https://user-images.githubusercontent.com/72409237/103731990-52a4f680-4f9b-11eb-9f66-795c742a3cc8.png">

gz#14332

gz#14999

**Comment by ansilh** [comment]
This worked fine till v2.5.3

![14jan-01](https://user-images.githubusercontent.com/11064902/104556482-b0a1a000-5665-11eb-98d6-0cc7458cfb89.gif)

The issue started after upgrading to v2.5.4
![14jan-02](https://user-images.githubusercontent.com/11064902/104557209-d7140b00-5666-11eb-8275-dc092572898a.gif)

**Comment by codyrancher** [comment]
@qa this affected all of the scheduling fields, tags, networks and creation method dropdowns so please verify all of those.

You should also verify that cloud credential switching will clear the fields and select the first option. 

I also noticed what appears to be a backend error when making use of the use cluster datastore option if you'd like to file an issue for that. I suspect it's the backend because the error mentions an invalid body and the front end doesn't specify a body for get requests.

![image.png](https://zube.io/files/rancher/92094cd9188419e434e0746846791913-image.png)
![image.png](https://zube.io/files/rancher/4232b550377470b6aa9cb56f22e26db2-image.png)

**Comment by sadiapoddar** [comment]
Verified on 2.5-head, eb160e0

- Create a node temple by adding especially network, deployment from either temple, content lib, and the template name and 
- save
- Click on an edit of the previously created node temple
- Verified all the fields populated with the previously set values. 
- The fix is working as expected.

**Comment by bmdepesa** [comment]
@sadiapoddar please validate on `master-head` as well and check the cases listed in this comment: https://github.com/rancher/rancher/issues/30690#issuecomment-774364289

**Comment by sadiapoddar** [comment]
Verified the fix on 2.5-head, df89971
Did the following 
1. Switched to a new credential and verified it reset all the previous value
2. Select the first one created credential and filled out all the drops down 
3. Save the template by giving a name
4. Opened the template for a re-edit
5. Verified that all the provided values during creating the template are preserved.
<img width="1289" alt="Screen Shot 2021-02-10 at 10 44 59 AM" src="https://user-images.githubusercontent.com/72409237/107563627-29791680-6b96-11eb-9e2e-09447c39a60f.png">
<img width="1205" alt="Screen Shot 2021-02-10 at 10 45 17 AM" src="https://user-images.githubusercontent.com/72409237/107564223-f4b98f00-6b96-11eb-90ea-46e6a7ae7793.png">

<img width="1224" alt="Screen Shot 2021-02-10 at 10 45 46 AM" src="https://user-images.githubusercontent.com/72409237/107563964-8ffe3480-6b96-11eb-9190-0e41f95aaedb.png">
<img width="1092" alt="Screen Shot 2021-02-10 at 10 45 58 AM" src="https://user-images.githubusercontent.com/72409237/107563946-8d034400-6b96-11eb-8e3c-18da2f99572c.png">



@codyrancher The error you are seeing when the user selects "use datastore cluster"  it's the right error msg since our vCenter doesn't have a datastore cluster. 


Need to verify the fix on master-head, currently blocked by 
https://github.com/rancher/rancher/issues/31232

**Comment by sadiapoddar** [comment]
Verified the fix on the master-head, 98fe72a
Steps

- Switched to a new credential and verified it reset all the previous value
- Select the first one created credential and filled out all the drops down
- Save the template by giving a name
- Opened the template for a re-edit
- Verified that all the provided values during creating the template are preserved.

**Comment by sadiapoddar** [comment]
https://github.com/rancher/rancher/issues/31285

**Comment by sadiapoddar** [comment]
Filed the following issue to track the vCenter tags/attributes that are not available during creating a vSphere node template.
https://github.com/rancher/rancher/issues/31285
