### ISSUE TITLE
Ingress Controller Use Fake Certificate Instead My real Certificate

### ISSUE THREAD

**Issue by Leon-pan** [rancher/rancher#30691]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Background: configuring Ingress rules with ssl

1. Choose a certificate
2. select my website Certificate
3. add Host ：def.k8s.mywebsite.com.cn

**Result:**

- Certificate doesn't work
- Certificate CN display :Kubernetes Ingress Controller Fake Certificate

**Other details that may be helpful:**

same way configuring 
1. Choose a certificate
2. select my website Certificate
3. add Host ：k8s.mywebsite.com.cn
**it works well**

**Environment information**
cluster work : v1.19.4-rancher1-1

**Comment by superseb** [comment]
Please share the `Subject Alternative Name` entries from the certificate you are using, you can look those up using `openssl x509 -in cert.pem -noout -text` and look for the entries under `X509v3 Subject Alternative Name:`.

**Comment by Leon-pan** [comment]
> Please share the `Subject Alternative Name` entries from the certificate you are using, you can look those up using `openssl x509 -in cert.pem -noout -text` and look for the entries under `X509v3 Subject Alternative Name:`.

            X509v3 Subject Alternative Name:
                DNS:*.mywebsite.com.cn, DNS:mywebsite.com.cn

**Comment by superseb** [comment]
Wildcard certificates only apply to a single component, not multiple. So your certificate is valid for `k8s.mywebsite.com.cn` but not for `def.k8s.mywebsite.com.cn`. To support `def.k8s.mywebsite.com.cn` you need to have `*.k8s.mywebsite.com.cn` in your certificate.

**Comment by Leon-pan** [comment]
> Wildcard certificates only apply to a single component, not multiple. So your certificate is valid for `k8s.mywebsite.com.cn` but not for `def.k8s.mywebsite.com.cn`. To support `def.k8s.mywebsite.com.cn` you need to have `*.k8s.mywebsite.com.cn` in your certificate.

OK.I see.3Q
