### ISSUE TITLE
Fleet and webhook do not come back to older version after a backup restore from 2.5.4-rc to 2.5.3

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30707]
Steps:

- Deployed Rancher HA on 2.5.3
- Take a backup b1 using rancher backups
- Upgrade to 2.5.4-rc8
- Restore from backup b1
- After restore of rancher on the same setup, the rancher version continued to be on 2.5.4-rc8
- Change the image of rancher to 2.5.3 on the local cluster.
- The agents on the downstream clusters go back to 2.5.3
- Fleet agent is still seen to be on 0.3.2 (newer version)
- Webhook is seen to be on `rancher/rancher-webhook:v0.1.0-beta9` (newer version)

**Expected:**
Fleet agent and Webhook should go back to the older versions when the rancher is started with 2.5.3

**Comment by StrongMonkey** [comment]
This is the expected behavior. From rancher 2.5.0 to 2.5.5, rancher will always try to install the latest version of fleet.

**Comment by sowmyav27** [comment]
Closing as per - https://github.com/rancher/rancher/issues/30707#issuecomment-770282139 and related issue to track the resourceset changes when fleet/webhook is not auto upgraded- https://github.com/rancher/backup-restore-operator/issues/69
