### ISSUE TITLE
[v2.5] Additional flag to encrypt all ebs volumes associated with ami

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#30700]
Issue to track update to machine

https://github.com/rancher/machine/pull/104
https://github.com/rancherlabs/rancher-security/issues/503

**Comment by sowmyav27** [comment]
**On 2.5.5**

- Created an AMI with root volume with KMS key1 and another volume with KMS key2
- Launch EC2 node driver cluster. Use this ^^^ AMI in node template and EBS Encryption: true and KMS key: key1
- When the node comes up and the cluster comes up active, the node is created with KMS key1 for the root volume and KMS key 2 for the other volume


**On 2.5.6-rc3**

- Created an AMI with root volume with KMS key1 and another volume with KMS key2
- Launch EC2 node driver cluster. Use this ^^^ AMI in node template and EBS Encryption: true and KMS key: key1
- When the node comes up and the cluster comes up active, the node is created with KMS key1 for root disk and the other volume.
