### ISSUE TITLE
[Monitoring v2] failed to install when Prometheus is disabled

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#30712]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy rancher v2.5-head (6c03627)
* install cluster that is monitoring-capable -> go to cluster explorer
* enable monitoring v2 (v9.4.202) with prometheus disabled (via 'edit yaml' option)

**Result:**
unable to enable monitoring at all when prometheus is disabled 

**Other details that may be helpful:**
I changed `enabled` to false for prometheus in the yaml 
<img width="393" alt="Screen Shot 2021-01-06 at 1 42 42 PM" src="https://user-images.githubusercontent.com/16691014/103836030-b16e7c80-503c-11eb-8c5a-5dbdfbd4a596.png">
and was presented with this in the logs:
* happens on a clean install and on upgrade from default monitoring v2 -> disable prometheus
```
Wed, Jan 6 2021 4:33:37 pm | helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-9.4.202.yaml --version=9.4.202 --wait=true rancher-monitoring /home/shell/helm/rancher-monitoring-9.4.202.tgz
Wed, Jan 6 2021 4:33:37 pm | load.go:112: Warning: Dependencies are handled in Chart.yaml since apiVersion "v2". We recommend migrating dependencies to Chart.yaml.
Wed, Jan 6 2021 4:33:39 pm | Error: UPGRADE FAILED: error validating "": error validating data: [apiVersion not set, kind not set]
```
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted, linode 8 core
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud, 8 core 32gb ram
- Kubernetes version (use `kubectl version`):  v1.19.6

- Docker version (use `docker version`): 

```
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:18:53 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by jiaqiluo** [comment]
the same bug is on v2.5.4-rc8

![screencapture-178-128-8-87-dashboard-c-c-6jhwv-apps-catalog-cattle-io-app-2021-01-06-18_06_48](https://user-images.githubusercontent.com/6218999/103838338-0ebcfa80-504a-11eb-8a9b-812823055daa.png)

**Comment by jiaqiluo** [comment]
same bug in v2.5.3

![screencapture-138-68-250-33-dashboard-c-c-kjd88-apps-catalog-cattle-io-app-2021-01-06-18_25_13](https://user-images.githubusercontent.com/6218999/103839439-9b68b800-504c-11eb-9bd3-1db1e46c8ba3.png)

**Comment by aiyengar2** [comment]
Thanks for catching this!

This issue is found in upstream as well; I opened up a ticket here https://github.com/prometheus-community/helm-charts/issues/550.

The fix is relatively simple, so the linked PR should resolve it. Tested it locally and the error no longer shows up.

**Comment by slickwarren** [comment]
tested on rancher v2.5-head (7e1997c) monitoring v2.4.903-rc01
<img width="1254" alt="Screen Shot 2021-02-02 at 8 55 42 AM" src="https://user-images.githubusercontent.com/16691014/106636331-ad982200-6536-11eb-8801-7510ab5ce90e.png">

was able to successfully:
* deploy monitoring with prometheus disabled
* upgrade prometheus disabled -> enabled
* upgrade prometheus enabled -> disabled

logs all report success with prometheus enabled/disabled
