### ISSUE TITLE
Provisioning fails with node template and SLES15 AMI

### ISSUE THREAD

**Issue by alexrenna** [rancher/rancher#30717]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a node template for EC2, and use ami-0a8c72379d44c5e14 -> SLES15SP2 x86_64

**Result:**

Error creating machine: /etc/sysconfig/SuSEfirewall2 No such file or directory

**Other details that may be helpful:**

SuSEfirewall2 is no longer available in SLES15 
https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15/#fate-320794

**Environment information**
- Rancher version v2.5.3
- Installation option HA

**Cluster information**
- Cluster type Infrastructure Provider
- Machine type cloud
- Kubernetes version v1.19.4

**Comment by luthermonson** [comment]
@alexrenna the fix for this is in v2.5.6-rc3 if you want to try and validate it with your ami. rancher qa is about to sign off on this using us-East-1 AMIs but want to be sure you're happy too.

**Comment by alexrenna** [comment]
tested on eu-central-1 with ami-0a8c72379d44c5e14, it works now. thanks

**Comment by luthermonson** [comment]
@alexrenna reopening so QA can sign off and close it. they're trying to repro in 2.5.5 and confirm fixed in 2.5.6 too.

**Comment by Ellenqs** [comment]
Validated with ami on AWS east2: ami-08bddf70836446637->SLES15SP2
On rancher version: v2.5.5 and v2.5-head (e3128c9)

Same steps on the two rancher versions:

- Bring up a rancher single install.
- Add a EC2 cluster by setting the ami-08bddf70836446637 in the node template (1 control plane, 1 etcd, 3 workers)

Results:

- on v2.5.5, the issue can be reproduced.
![Screen Shot 2021-01-29 at 9 13 59 AM](https://user-images.githubusercontent.com/75277058/106306073-60ecd800-6212-11eb-91b6-a817ecac00f3.png)


- on v2.5-head, the cluster is provisioned successfully
