### ISSUE TITLE
Launching kubectl/shell for the cluster doesn't use a private registry for the image

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#30735]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Provision a Rancher downstream cluster with, or enable, [a private registry for the cluster](https://rancher.com/docs/rancher/v2.x/en/admin-settings/config-private-registry/#setting-a-private-registry-with-credentials-when-deploying-a-cluster)
- Using cluster explorer/manager launch a kubectl or shell

**Result:**

- The `dashboard-shell-xxx` pod container image is defined with `rancher/shell` from Docker Hub

**Other details that may be helpful:**

In an air gap environment, this prevents kubectl/shell windows from succeeding

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.4
- Installation option (single install/HA): N/A

**Cluster information**
- Kubernetes version (use `kubectl version`): v1.19.6

gz#14262

**Comment by jimmyw86878** [comment]
We get the same issue here.

We use a private registry to deploy a K8S cluster without Internet. Rancher still try to pull rancher-shell image from docker hub when we launch the kubectl/shell in rancher UI.
My information:
rancher/rancher: v2.5.5
rancher/rancher-agent: v2.5.5
Kubernetes: v1.19.6

**Comment by jimmyw86878** [comment]
@dkeightley Do you have any temporary workaround for this issue?
I tried to load the rancher-image:v0.1.5 manually (I pulled the image on other Internet connected host) but Rancher still want to pull from docker hub via Internet. I think the image pull policy is set to `always` for rancher/shell deployment?

**Comment by dkeightley** [comment]
Hi @jimmyw86878 I'm afraid at present I'm not aware of a way to override the image location, however in my testing (also with Rancher v2.5.5) the pod is created with `imagePullPolicy: IfNotPresent`.

As the kube-scheduler will place the pod, it could be started on potentially any node in the cluster.

**Comment by jimmyw86878** [comment]
@dkeightley Thank you for your reply !
For now, I will not use kubectl/shell on Rancher UI.  On the other hand, I may install kubectl on host and use generated config for ~/.kube/config.

Still, it would be nice to use kubectl/shell on Rancher UI.

**Comment by deniseschannon** [comment]
It looks like we need to prepend registry to the shell command.
https://github.com/rancher/rancher/blob/master/pkg/api/steve/clusters/shell.go#L143

which is actually in  `PrefixPrivateRegistry`

**Comment by StrongMonkey** [comment]
This is because shell only takes global-registry-setting, not cluster-private-registry setting. I guess the right way to fix is to use cluster-private-registry first if it is set, then global-registry-setting.

**Comment by StrongMonkey** [comment]
Available to test. Make sure cluster registry and system-default registry can all be applied into downstream cluster and local clyster for shell and helm app(in dashboard).

**Comment by slickwarren** [comment]
tested on v2.5.8-rc4:

<img width="586" alt="Screen Shot 2021-04-15 at 5 03 38 PM" src="https://user-images.githubusercontent.com/16691014/114953140-9f0a9880-9e0c-11eb-9196-1bc4ba5198fb.png">


<img width="542" alt="Screen Shot 2021-04-15 at 5 03 18 PM" src="https://user-images.githubusercontent.com/16691014/114953143-a0d45c00-9e0c-11eb-808c-110f58a18de5.png">
shell is now working as expected on both dashboard and
