### ISSUE TITLE
rancher-istio installation fails when clusters uses PodSecurityPolicies

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#30744]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Create a cluster with PodSecurityPolicy Support
* Install rancher-istio

**Result:**
The installation fails because of missing PSPs for the istio installer/uninstaller pods as well as missing PSPs for all istio components (istiod, cni, kiali, ...).

**Other details that may be helpful:**
The banzaicloud istio operator contains some policies for istio: https://github.com/banzaicloud/istio-operator/tree/release-1.7/config/overlays/psp/resources.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): HA
- rancher-istio version: 1.7.301
- Kubernetes version: v1.19.6

**Comment by cbron** [comment]
part of https://github.com/rancher/rancher/issues/28622

**Comment by brendarearden** [comment]
PSPs have been added to the istio, kiali and jaeger charts - you can enable PSP by setting `.Values.global.defaultPodDisruptionBudget.enabled=true` from the rancher-istio chart and attempt an install into a secure cluster. The global value will enabled the kiali and jaeger PSPs if those dependencies are installed

**Comment by anupama2501** [comment]
PR for the issue: https://github.com/rancher/charts/pull/1071/commits

Rancher: v2.5.7,
Istio: 1.7.301/1.8.300
Not able to reproduce the issue. Following are the steps I tried:
1. Create an infrastructure provider cluster with pod security policy enabled
2. Install istio and add .Values.global.rbac.enabled=false by editing the yaml file.
3. helm installation goes through successfully. no error is seen


@brendarearden  Please let me know if there are any additional steps to be performed.

**Comment by anupama2501** [comment]
Reproduced on rancher 2.5.8-rc10
kubernetes 1.20.6-rancher1-1
istio version 1.9.300

1. Create a downstream cluster on rancher server with pod security policy set to restricted in the advanced options
2. Once the cluster is active, install monitoring and install istio without selecting the project into which it should be installed.
3. Istio installation fails with the error:
<img width="400" alt="Screen Shot 2021-04-28 at 1 57 19 PM" src="https://user-images.githubusercontent.com/38144301/116473253-ceb59980-a82b-11eb-86b3-3a42aef919fc.png">
<img width="400" alt="Screen Shot 2021-04-28 at 1 58 13 PM" src="https://user-images.githubusercontent.com/38144301/116473268-d4ab7a80-a82b-11eb-8308-036f7d2aa111.png">


1. Create a downstream cluster on rancher with pod security policy set to restricted 
2. Install monitoring and while installing istio, set '.Values.global.rbac.pspEnabled' to true 
3. Istio installs without any error:
<img width="400" alt="Screen Shot 2021-04-28 at 2 40 15 PM" src="https://user-images.githubusercontent.com/38144301/116476181-b6e01480-a82f-11eb-996d-2c6b70a6625b.png">
