### ISSUE TITLE
Update Rancher server helm chart to limit k8s versions based on support matrix

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#30745]

**Comment by sowmyav27** [comment]
**Using `2.5.5-rc4`**

Deploying HA using k3s version: v1.20.0+k3s2 gives error `chart requires kubeVersion: < 1.20.0 which is incompatible with Kubernetes v1.20.0+k3s2` . Installation of k8s 1.19 and k3s <1.20 (1.18) works fine.
