### ISSUE TITLE
Kiali unable to acquire traces

### ISSUE THREAD

**Issue by shpwrck** [rancher/rancher#30752]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

* Deploy Rancher (I used 2.5.3)
* Deploy Rancher Monitoring (I used 9.4.202)
* Deploy Istio 1.7.301 <- Version required for tracing integration
* Deploy Bookinfo
* Open Kiali
* Navigate to Services -> $SERVICE -> Tracing

**Result:**

Kiali will claim that it cannot collect traces.
![image](https://user-images.githubusercontent.com/58433720/104057588-67160880-51c0-11eb-9059-41874d4caca9.png)
![image](https://user-images.githubusercontent.com/58433720/104057630-7b5a0580-51c0-11eb-96ae-4165233eb98d.png)

**Other details that may be helpful:**

This happens because the jaeger configuration sets `QUERY_BASE_PATH` to `/jaeger` but the `in_cluster_url` is set to the root: 'http://tracing.istio-system.svc:16686'

Fixes:
* Change `in_cluster_url` to `http://tracing.istio-system.svc:16686/jaeger`
* Change `QUERY_BASE_PATH` to `/`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.3
- Installation option (single install/HA): HA

**Cluster information**
- Kubernetes version (use `kubectl version`): 1.19

**Comment by anupama2501** [comment]
Issue is seen on 2.5.4 as well:
Rancher | v2.5.4
User Interface | v2.5.4
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

Followed the same steps as mentioned above:
Deploy monitoring and istio with jaeger tracing enabled as standard user on single node installation and deploy the bookinfo workload. 
In kiali --> services --> default namespace --> traces and inbound metrics have the same error:

![image](https://user-images.githubusercontent.com/38144301/104068992-3632d500-51ba-11eb-99f5-a8b1993e6c0f.png)

**Comment by haswalt** [comment]
I'm seeing the same on v2.5.3. Also seeing (possibly related) issue with collecting metrics from prometheus. I have the monitoring app installed in it's default location.

Can confirm the above changes to the `in_cluster_url` and `QUERY_BASE_PATH` fix the trace access from Kiali

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.6-rc4
rancher-istio:v1.8.100-rc01

* Install rancher-monitoring
* Install Istio w/ Kiali enabled
* Deploy demo bookservice
* Kiali is installed and accessible
* Traffic graph, metrics, and traces show correctly 
* Values yaml shows the correct values:
```
..
tracing:
      in_cluster_url: 'http://tracing.istio-system.svc:16686/jaeger'
..
tracing:
  contextPath: /jaeger
```
