### ISSUE TITLE
Service container deletes and creates new one if you select Never (start once)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3075]
version - 0.50.1-rc2

Steps:
1.  Add a host
2.  Add a Service, use hello-world for image and under Advanced Options, select Never (Start Once) for Auto-restart
3.  Start the service

Results:
The container is created, then after it's done, it degrades to started once.  Then the container is deleted, and another one is created.  What is the point of having this option if it just continues to basically restart the service by creating the container over and over again?

Expected:
The container to not delete and stay in a started once state.

**Comment by alena1108** [comment]
@tfiduccia I can't reproduce the issue on the latest. Steps taken are the same as you've done.

Could you re-test on the latest? Also can you double check if this label was set on the service:

io.rancher.container.start_once	true

**Comment by tfiduccia** [comment]
Version - master Jan 07
Verified not reproducible.
