### ISSUE TITLE
Logging setting

### ISSUE THREAD

**Issue by disaster37** [rancher/rancher#30769]
**What kind of request is this (question/bug/enhancement/feature request):**
question / feature request

**Steps to reproduce (least amount of steps as possible):**
I should to send logging on Elasticsearch cluster. We use static alias index with ILM / Rolleover underground.
There are no way to set static index when configure Elasticsearch logging (from ui). So I edit setting as form, to set my static index. It's work fine, but with this way I can't set the buffer (flush internal). Default to 60s, it break the wall Elasticsearch cluster because of the bulk request is too big.

There are a way to edit setting as form and control the buffer ?

**Result:**

No way to controll payload size

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.8
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.18.6

```
(paste the output here)
```

- Docker version (use `docker version`): 19.3.8

```
(paste the output here)
```

**Comment by vuhoanghiep** [comment]
Hi @disaster37, i'm also facing this issue. Could you show me how to add ILM alias to output. I tried ilm_rollover_alias but no luck. Thanks!
