### ISSUE TITLE
HealthState field to the service

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3077]
We have to introduce health_state as a service filed. Today UI generates this state based on the health state of the containers in the service, and that solution wouldn't work for people integrating with our APIs directly. 

@vincent99

**Comment by alena1108** [comment]
@prachidamle assigning this ticket to you; it would be a great way for you to get more familiar with cattle process/object states orchestration.

**Comment by sangeethah** [comment]
Tested with v0.63.0-rc2.

HealthState is now available as a field in both  Environment (Stack) and service level.
Bugs found when testing this feature will be tracked as different bugs .
One such issue - https://github.com/rancher/rancher/issues/3904
