### ISSUE TITLE
Windows nodes fail to create the RKE log directory if the prefixPath is not set on a Windows cluster

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#30782]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- create a downstream windows cluster without setting `win_prefix_path`

**Result:**
during the Windows node join process, the agent will report an error similar to the one below. The node will still successfully register but certain directories that are essential for Windows logging will not be present, most notably `c:\var\lib\rancher\rke\log` which is the [default location for symlinks](https://github.com/rancher/rancher/blob/master/pkg/rkeworker/docker.go#L353-L358) that point to the Docker logs for kubelet, kube-proxy, service-sidekick, rancher agent, and nginx-proxy

```
level=error msg=\"failed to check plan: Error response from daemon: invalid volume specification: 'c:\\\\/var/lib:c:/var/lib'\"\n",
```

**Other details that may be helpful:**
The proposed fix is to either modify the prefixPath override to `c:` or not set it at all [here](https://github.com/rancher/rancher/blob/master/pkg/rkeworker/docker.go#L447-L450 ). Further discussion and testing needs to be completed.

**Environment information**
- Rancher version: v2.4.11

gz#14257

**Comment by sowmyav27** [comment]
**On 2.4.5**

- Deploy a windows cluster. 
- Login to the windows node
- Logs exist in `c:\var\lib\rancher\rke\log` directory

**On 2.4.8/2.5-head- commit id: `3d62d5d65` reproduced the issue**

- Deploy a windows cluster. 
- Login to the windows node
- `c:\var\lib\rancher\rke\log` directory does not exist

**Comment by sowmyav27** [comment]
**On 2.4-head - commit id: `178fff088`**

- Deploy a windows cluster.
- Login to the windows node
- `c:\var\lib\rancher\rke\log` exists

<img width="1114" alt="Screen Shot 2021-01-22 at 4 49 54 PM" src="https://user-images.githubusercontent.com/26032343/105563165-ed0e7500-5cd1-11eb-80f8-b8b43eafe1e5.png">
