### ISSUE TITLE
[Continuous Delivery] Adding Git repository fails when path contains uppercase characters

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#30792]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a Git repository
2. Add the following directory to the root of the repository: "SubFolder"
3. Create a GitRepo resource in Rancher Continous Delivery referencing the Git repository URL and specifying `/SubFolder`  in the Path field.

**Result:**
The GitRepo resource enters a permanent error state

> time="2021-01-12T13:20:49Z" level=fatal msg="Bundle.fleet.cattle.io \"isitbrokenornot-SubFolder\" is invalid: metadata.name: Invalid value: \"isitbrokenornot-SubFolder\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"

<img width="715" alt="Screenshot 2021-01-12 at 14 23 03" src="https://user-images.githubusercontent.com/3813921/104348975-9f8c4e00-5502-11eb-842d-3b52c5e6aff8.png">

**Other details that may be helpful:**

Rancher 2.5.3

**Comment by dnoland1** [comment]
See also https://github.com/rancher/fleet/issues/198 which may be a duplicate or related issue.
