### ISSUE TITLE
Option to disable auto fleet updates

### ISSUE THREAD

**Issue by boxboatmatt** [rancher/rancher#30791]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Release new `fleet` chart to rancher/charts
2. Rancher 2.5 automatically updates to new chart
3. If new `fleet` release causes issues no ability to revert to previous version (auto update will force the latest version)

**Result:**

Recommend that Rancher add the ability to freeze `fleet` (or any other managed app deployment that uses this methodology). Rancher released a version of `fleet` that caused issues with private git repositories and resulted in multiple days of `fleet` downtime for affected users with no ability by the end user to restore working functionality due to the auto upgrade feature for `fleet`. 

**Other details that may be helpful:**

See https://github.com/rancher/fleet/issues/216 for reference. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5
- Installation option (single install/HA): HA

**Comment by oak-tree** [comment]
Rollback will be also good feature in case the auto update is on

**Comment by boxboatmatt** [comment]
Agreed... but I think rollback is already there by virtue of the fact that you canmanage the fleet deployment under the Cluster Explorer -> Installed Apps. If you find the fleet install you can temporarily roll it back to version `0.3.1` but after a few minutes it will auto update to `0.3.2`.

**Comment by kalinon** [comment]
this is still needed.

**Comment by vincent99** [comment]
Didn't we already do this? There's a minimum version of Fleet for the version of Rancher that's running and it's upgraded only when not satisfied.  Which would be upon performing a Rancher upgrade that includes increasing the minimum.

**Comment by boxboatmatt** [comment]
It appears the original issue of auto-upgrading fleet when a new chart has been published no longer occurs - my Rancher 2.5.8 installations are still on Fleet 0.3.5. I was looking at the release notes for 2.5.9 though and I don't see anything identifying a minimum Fleet version which may be helpful going forward if they are going to be tied together tightly

**Comment by kalinon** [comment]
> Didn't we already do this? There's a minimum version of Fleet for the version of Rancher that's running and it's upgraded only when not satisfied. Which would be upon performing a Rancher upgrade that includes increasing the minimum.

hmmm that may be what happened with my upgrade. Even with this, will it upgrade/overwrite a custom fleet install? 

Guess if there was some documentation on this it would be helpful.
