### ISSUE TITLE
Project-level roles that project owners cannot assign

### ISSUE THREAD

**Issue by oxr463** [rancher/rancher#30805]
> Is there a way to set up a role so that a Project Owner can not assign it to users. I would like to create a few special roles that I do not want a project owner to assign by mistake. For example, I do not want a project owner to be able to grant access to create daemonsets but I do need to grant this access to some users that are approved to run a daemonset in the cluster. I've created my role but any project owner can assign it.

gz#13867

**Comment by cbron** [comment]
I'm assuming you want this done at project level, but you can do this today with k8s rbac. Just make a Role and Bind it to certain users in those project namespaces.
