### ISSUE TITLE
[Logging v1] Add Windows 2004 and 20H2 to logging

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#30808]
Relevant repos:
- https://github.com/rancher/fluentd
- https://github.com/rancher/system-charts

Previous, similar work: https://github.com/rancher/rancher/issues/30279

**Comment by nickgerace** [comment]
Required images to have 2004 and 20H2 mainfests:

- [x] https://github.com/rancher/fluentd on `master`
- [ ] https://github.com/rancher/configmap-reload on `rancher`

**Comment by izaac** [comment]
Rancher version: `v2.5-head (02/12/2021)` _dba3321_

Windows workloads failed on Windows 20H2. 

- cattle-cluster-agent
- fleet
- logging

Support for this Windows version is listed as unsupported in our support Matrix.

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "cattle-node-agent-windows-vsfs6": Error response from daemon: hcsshim::CreateComputeSystem 6626c787c760e329dfbc1aae9cc7a55253799a193b38d3fe2418b5482970d1b3: The container operating system does not match the host operating system
```

Should we move create a separate issue for Windows 20H2 with a different milestone? @sowmyav27

**Comment by izaac** [comment]
Opened a separate issue to follow up 20H2 in a future release: https://github.com/rancher/rancher/issues/31313

**Comment by sowmyav27** [comment]
**On `v2.5-3e96d7f`**

- Deployed a windows 2004 cluster - VXLAn using k8s 1.19.7-rancher2-1 - 1 etcd, 1 control plane and 1 linux worker nodes, 3 windows worker nodes.
- Cluster is deployed successfully.
- Enabled Logging v1 using Elastic search - `v0.2.3`
- Deploy a workload. type - daemonset
- Logs are seen in elastic search from all windows worker nodes
