### ISSUE TITLE
[RFE] vSphere node driver - Need option to set 'numCoresPerSocket' in node template

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#30814]
**What kind of request is this:**
Feature request

**Description**
As of now, we can set the number of CPUs while defining the node template 
But in some cases, the `Cores Per Socket` needs to be tuned (details are in the below blog post)
https://blogs.vmware.com/performance/2017/03/virtual-machine-vcpu-and-vnuma-rightsizing-rules-of-thumb.html

The go library provided by VMware has the option to change this parameter.
```
govc vm.change -vm master-01 -e cpuid.coresPerSocket=1
```

gz#14317

**Comment by Eric-TAS** [comment]
Hello,
I also have the same need. 
Strange that few people are interested in this subject which would allow a better use of virtualization.
Someone would have a tip?
