### ISSUE TITLE
[2.5.3] OpenLDAP - API error response 500 for POST /v3-public/openLdapProviders/openldap?action=login

### ISSUE THREAD

**Issue by Nicolas-TS** [rancher/rancher#30818]
Hi everyone !

**What kind of request is this (question/bug/enhancement/feature request):**

Bug 

**Steps to reproduce (least amount of steps as possible):**

1. On the Rancher UI, configure the authentication based on the Openldap module
2. Configure fields according to your LDAP schema 
3. On the "Test and enable authentification" use a LDAP account (user1 for example) to save the Openldap configuration
4. Log in the Rancher UI using the LDAP account used in step 3 (user1)

**Result:**

In Rancher logs :
```
[ERROR] API error response 500 for POST /v3-public/openLdapProviders/openldap?action=login. Cause: can't find unique user for principal openldap_user://uid=user1,ou=users,o=company
```

In Rancher UI :
```
An unknown error occurred while attempting to login. Please contact your system administrator.
```

**Other details that may be helpful:**
If we go back to the OpenLDAP configuration, then "Edit" and we use another LDAP account for "Test and enable authentication" (user2 for example), the user "user1" have now access to Rancher UI but "users2" have the error.

**Environment information**
- Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): Rancher 2.5.3
- Installation option (single install/HA): Single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Vsphere Cluster
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Virtual Machines
- Kubernetes version (use `kubectl version`): v1.18.3
- Docker version (use `docker version`): 19.3.11

**Comment by ebartz** [comment]
@Nicolas-TS did you solve the issue somehow or are you still facing the same issue?
