### ISSUE TITLE
The content under the page project is loaded slowly and times out irregularly

### ISSUE THREAD

**Issue by 573009114** [rancher/rancher#30815]
## phenomenon:

with more and more namespace and resources under the project, the phenomenon of loading page timeout will appear randomly every day. Sometimes refresh can solve the problem,But more often it needs to be restarted rancher server pod

## system architecture: 
```
user-->LB(4 layer)-->rancher(HA)
```
## rancher version: 
```
2.4.x
```

**Comment by ywllongge** [comment]
Please say your cluster scale

**Comment by ywllongge** [comment]
You can split resources into multiple clusters

**Comment by 573009114** [comment]
Currently, it manages seven kubernetes clusters, with the largest cluster of 90 machines.
The rancher cluster has three machines

**Comment by ywllongge** [comment]
You can try the next kubesphere

**Comment by ywllongge** [comment]
As the rancher version 2.4.2 has a known bug, try upgrading the version or disabling dashboards as regards memory leakage

**Comment by 573009114** [comment]
I'll try this solution
https://github.com/rancher/rancher/issues/26624
