### ISSUE TITLE
Omitting --worker flag when adding new node results in longer register times in 2.5.x

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#30824]
A user is experiencing much longer registration times (15 minutes vs 3 minutes) when omitting the --worker flag when adding workers to custom clusters in 2.5.x, this seems to be new behavior that does not exist in 2.4.x or prior. Previously, the role was getting added relatively quickly. Some logs that may indicate a cause on the agent are the following:

```
time="2021-01-06T20:28:48Z" level=warning msg="Error while getting agent config: invalid response 500: Operation cannot be fulfilled on nodes.management.cattle.io \"m-088056b9d546\": the object has been modified; please apply your changes to the latest version and try again"
```

This seems to cause the agent to wait a bit before trying again for a new plan. This is fixed by adding the flag. 

gz#14196

**Comment by deniseschannon** [comment]
There have been significant performance improvements in the course of v2.5.x and the latest version v2.5.10 definitely has the fix that brings registration times back to previous amounts. I have been unable to find the exact release and issue, but trying v2.5.10 will definitely have these performance fixes.
