### ISSUE TITLE
[ui]custom ui not work for version 2.5.2

### ISSUE THREAD

**Issue by ssongjunxian** [rancher/rancher#30821]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
Rancher/UI based master branch pulled code, modified, packaged into a new UI package and deployed. When the backend Rancher Server is 2.4.8, you can see the custom UI when you change the UI-index. But when the backend Rancher Server is version 2.5.2, the custom UI cannot be seen by modifying the UI-index. 

**Result:**
not work for rancher  2.5.2

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
Docker version 19.03.14, build 5eb3275d40
```
(paste the output here)
```

**Comment by vincent99** [comment]
2.5+ has a new separate setting from the URL for whether to use it or not.  Set `/v3/settings/ui-offline-preferred` to `false`.

**Comment by ssongjunxian** [comment]
> 2.5+ has a new separate setting from the URL for whether to use it or not. Set `/v3/settings/ui-offline-preferred` to `false`.

worked, thank you
