### ISSUE TITLE
[OIDC] Generic & Keycloak: Create / Edit / Detail Page

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#30823]
These requirements are for two new provider options to be added for auth:

1. A Keycloak OIDC provider

1. A generic OIDC provider

The priority is for Keycloak OIDC provider. Generic OIDC provider will not be released if there are issues with it. Time should not be spent correcting issues with the Generic portion of this issue. 

**Page Title:** Configure Keycloak OIDC **[Or]** Config OIDC

**Confirmed Fields:**
| Name      | Type |
| ----------- | ----------- |
| Client ID      | Text       |
| Client Secret   | Text        |
|Token Endpoint URL | Text |
|Authorization Endpoint URL | Text | 
|Certificate| Cert Field or Upload from File |  
|RedirectURL| Text | Default to: server-url from settings|

Backend Issue: https://github.com/rancher/rancher/issues/30280

**Comment by gaktive** [comment]
We need to move this work to Dashboard. Existing ticket (which is hopefully portable): https://github.com/rancher/dashboard/issues/2191
