### ISSUE TITLE
Adding a cluster results in Network Error: network policies and firewall rules

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#30835]
**What kind of request is this (question/bug/enhancement/feature request):**
Flaky bug (unsure of full repro steps)

**Steps to reproduce (least amount of steps as possible):**
* rancher 2.5.5 , configure linode cluster (I was using the 6 core instance on US-West)

**Result:**
* cluster cannot be added with error `[[network] Host [<IP>] is not able to connect to the following ports: [<IP>]. Please check network policies and firewall rules]` on step `Waiting to register with Kubernetes`

**Other details that may be helpful:**
* I have `remember me for 30 days` selected for linode login. Today my 30 days were up and was logged out at about the same time this error occurred on my rancher server (I was able to provision a few clusters with the same node template earlier in that session).  Even after logging back in and making a new template (with the same credentials), I ran into the same error

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5 and v2.5-head (093d342289c9f6b6889864f29790e8d32abe77a9)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Linode
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 6vCPU 16gb ram
- Kubernetes version (use `kubectl version`): unable to check but likely v1.19.6 (cluster not fully provisioned)

- Docker version (use `docker version`): unable to check but likely 19.3.14

**Comment by deniseschannon** [comment]
What OS are you using that this failed?

**Comment by slickwarren** [comment]
I think I tried both 20.04 and 18.04 as the linode OS, both resulted in the same error.

**Comment by sowmyav27** [comment]
Issue was seen on a DO rke cluster. It is not always reproducible.

**Comment by superseb** [comment]
@slickwarren @sowmyav27 Please share the setup when this is seen again

**Comment by slickwarren** [comment]
this is reproducible when using azure node provisioning on master-head (c0508344405fb9bd55198d2196e93fe3fc33ade7)
with the default network settings

Also confirmed that the same settings works fine on a 2.5.8 cluster

**Comment by slickwarren** [comment]
on master-head (5d2b7ac), I am now able to provision an azure cluster.  
* tested a single node cluster through dashboard (RKE)-- pass
* multi node cluster through dashboard (RKE) -- pass
