### ISSUE TITLE
Unchecking DNS checkbox for clone/upgrade doesn't reset DNS to null

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3083]
Version - 0.50.2-rc2

Steps:
1.  Add a service
     Advanced Options/Networking - Set Network to Host and check DNS checkbox
2.  Clone or Upgrade the service and go to Networking and uncheck DNS

Results:
The new cloned service has DNS checked, the system label is created and set to true 
![image](https://cloud.githubusercontent.com/assets/11514927/11906600/fd717126-a58a-11e5-864f-dc1b6b50fd9e.png)

Expected:
DNS should not be true and the label should not be created

**Comment by bacheson** [comment]
Enabling the DNS checkbox when creating a service exposes the same bug in reverse.

**Comment by vincent99** [comment]
Added to #3707
