### ISSUE TITLE
[2.3] backport Release Arm fix for Rancher 2

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#30831]
Since the confd update is in rke-tools and being added with all new k8s patches, this will be available in all versions of Rancher. 

rancher/rancher#26906

**Comment by kinarashah** [comment]
@sowmyav27 could we close this issue?

**Comment by deniseschannon** [comment]
Users with this specific hard-ware have tested it in 2.4, which has the same versions, so this can be closed.

**Comment by kinarashah** [comment]
https://github.com/rancher/kontainer-driver-metadata/pull/464
