### ISSUE TITLE
Cisco ACI (noiro) images exist in rancher-images.txt release artifact

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#30840]
Currently, `noiro` prefixed images (Cisco ACI) exist in `rancher-images.txt`. As this is not a supported CNI (like Weave), we shouldn't include the images.

```
$ curl -sL https://github.com/rancher/rancher/releases/download/v2.5.5/rancher-images.txt | grep ^noiro
noiro/aci-containers-controller:5.1.1.0.1ae238a
noiro/aci-containers-host:5.1.1.0.1ae238a
noiro/cnideploy:5.1.1.0.1ae238a
noiro/gbp-server:5.1.1.0.1ae238a
noiro/openvswitch:5.1.1.0.1ae238a
noiro/opflex-server:5.1.1.0.1ae238a
noiro/opflex:5.1.1.0.1ae238a
```

This also applies to the generated image list when you download it from the UI.

**Comment by slickwarren** [comment]
checked on v2.5.6-rc3, and found no `noiro` entries in rancher-images.txt 
* https://github.com/rancher/rancher/releases/v2.5.6-rc3

**Comment by deniseschannon** [comment]
Checked on v2.6.0-rc1 and found no `noiro` entries in rancher-images.txt

https://github.com/rancher/rancher/releases/tag/v2.6.0-rc1
