### ISSUE TITLE
cattle-cluster-agent behind proxy: can't add Chart Repository

### ISSUE THREAD

**Issue by kinolaev** [rancher/rancher#30846]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
create cluster behind proxy and add any public Chart Repository, for example, `https://charts.jetstack.io`

**Result:**
Chart Repository hangs with the "Downloading" status, `connect: no route to host` in `cattle-cluster-agent` logs

**Other details that may be helpful:**
as I understand `cattle-cluster-agent` created with template [systemtemplate/template.go](https://github.com/rancher/rancher/blob/v2.5.5/pkg/systemtemplate/template.go) and it has no proxy environment variables

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.5
- Installation option (single install/HA): HA

**Comment by kinarashah** [comment]
Possibly related: https://github.com/rancher/rancher/issues/29961

**Comment by kinarashah** [comment]
Thank you for opening the issue, tracking it in #29961
