### ISSUE TITLE
Can't clone/upgrade service that has container run on specific host

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3085]
v0.50.2-rc2

Steps;
1.  Add Service, in Advanced Options/Scheduling select Run containers on a specific host and pick a running host.
2.  Try to upgrade or create clone service but don't change the scheduling option

Results:
Validation failed in API: requestedHostId
![image](https://cloud.githubusercontent.com/assets/11514927/11908298/2705432a-a598-11e5-97a2-6476d241441c.png)

Expected:
Should be able to clone/upgrade service without changing that particular option

**Comment by vincent99** [comment]
Dupe #2065
