### ISSUE TITLE
Monitoring receiver and route not showing

### ISSUE THREAD

**Issue by nayrnet** [rancher/rancher#30852]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
`kubectl get secrets -n cattle-monitoring-system alertmanager-rancher-monitoring-alertmanager -o json | jq  -r '.data."alertmanager.yaml"' | base64 -d`

**Result:**
```
global:
  resolve_timeout: 5m
receivers:
  - name: 'null'
  - slack_configs: []
    email_configs: []
    webhook_configs:
      - http_config: {}
        send_resolved: true
        url: >-
 https://outlook.office.com/webhook/REDACTED
    name: Teams
  - slack_configs: []
    email_configs: []
    webhook_configs: []
    name: pagerduty
    pagerduty_configs:
      - service_key: <secret>
        send_resolved: true
        description: 'prvk8s: {{ template "pagerduty.default.description" .}}'
  - slack_configs: null
    email_configs: null
    webhook_configs:
      - send_resolved: true
        url: >-
 http://prometheus-msteams.prometheus-msteams.svc.cluster.local:2000/teams
        http_config: {}
    name: prometheus-msteams
  - slack_configs: []
    email_configs: []
    webhook_configs: []
    opsgenie_configs:
      - api_key: <secret>
        send_resolved: true
        description: 'prvk8s: {{ template "opsgenie.default.description" .}}'
        priority: >-
          {{ range .Alerts }}{{ if eq .Labels.severity "critical"}}P1{{else if
          eq .Labels.severity "warning"}}P2{{else if eq .Labels.severity
          "info"}}P3{{else}}P4{{end}}{{end}}
    name: opsgenie
route:
  group_by:
    - job
    - alertname
  group_interval: 2m
  group_wait: 30s
  receiver: prometheus-msteams
  repeat_interval: 12h
  routes:
    - group_by: []
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      match:
        severity: critical
      match_re: {}
      receiver: opsgenie
templates:
  - /etc/alertmanager/config/*.tmpl
 ```

When I copy this same YAML into my environment, the receives and routes are empty. I don't see any errors in my server logs and the response data payload is empty in my test environment:

{"type":"collection","links":{"self":"https://support.rancher.cloud/k8s/clusters/c-l2nsg/v1/secrets/alertmanager-rancher-monitoring-alertmanager"},"createTypes":{"secret":"https://support.rancher.cloud/k8s/clusters/c-l2nsg/v1/secrets"},"actions":{},"resourceType":"secret","revision":"26852","data":[]}

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): HA

gz#14030

**Comment by deniseschannon** [comment]
Where was this YAML generated or where is it from?

**Comment by nayrnet** [comment]
After upgrading to Rancher 2.5.5 the routes and receivers showed back up in the WebUI, seems this issue had already been fixed in a later release.
