### ISSUE TITLE
Rancher 2.5.5 Unable to add node to an Imported RKE cluster 

### ISSUE THREAD

**Issue by adacaccia** [rancher/rancher#30860]
**What kind of request is this (question/bug/enhancement/feature request):**bug/enhancement

**Steps to reproduce (least amount of steps as possible):**

- Firstly you would need an RKE cluster solely managed by kubectl, several months off Rancher 2.3.5 blew away with insurmountable etcd issues.
- Then just:

```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org
```

**Result:**
Rancher 2.5.5 is Up&Running, but when you click "Edit Cluster", the resulting page shows a header like:

> Edit Cluster: <cluster-name> (Imported)

And because of the "Imported" status, I guess, the page provides very little functionality, missing (among many others) the ability to enroll a new node!

**Other details that may be helpful:**

More precisely, an RKE cluster which is currently "orphaned" by a previous version of Rancher, and into which the new 2.5 version is able to install successfully, why should it marked as "Imported"? Isn't RKE Rancher-native, anyway?
And even if the RKE cluster should be considered "Imported", why not provide the ability to at least add a new node, since there's no kubectl no other way around that, currently?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): Helm in Kubernets (RKE cluster), 3 Pods + rancher-webhook pod deployed.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported ("Orphaned" Rancher-less RKE cluster created by Rancher 2.3.5) 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud DO - spec. 8 vCPU/16 GB RAM
- Kubernetes version (use `kubectl version`): v1.17.2

```
(paste the output here)
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Result:**

Unable to add a new node, as the cluster is marked as "Imported".

**Other details that may be helpful:**

**Comment by superseb** [comment]
Clusters that are imported to Rancher need to be managed by the tool it was created with. In this case that is RKE, you can use the RKE CLI to manage your cluster. The ability to recognize it is an RKE cluster and to fully manage it like a Rancher created/provisioned cluster (custom), is covered in https://github.com/rancher/rancher/issues/22763.
