### ISSUE TITLE
Can not login as a standard user (who is part of 1000 groups) with AD auth without trying many times. 

### ISSUE THREAD

**Issue by Ellenqs** [rancher/rancher#30869]
**What kind of request is this (question/bug/enhancement/feature request):**
question/bug

**Steps to reproduce (least amount of steps as possible):**
1. Set up AD authentication
2. Create a standard user
3. login as standard user

**Result:**
Got login error many times before login successfully.

<img width="427" alt="Screen Shot 2021-01-15 at 11 47 53 AM" src="https://user-images.githubusercontent.com/75277058/104772339-1d7d6e80-5728-11eb-97b0-9720142b118d.png">

API error : 
```
{baseType: "error", code: "ServerError", message: "server error while authenticating", status: 500,…}
baseType: "error"
code: "ServerError"
message: "server error while authenticating"
status: 500
type: "error"
```

Rancher log:

```
2021/01/15 22:36:07 [ERROR] Unknown error: Error creating ssl connection: LDAP Result Code 200 "": x509: cannot validate certificate for ******** because it doesn't contain any IP SANs
2021/01/15 22:36:48 [INFO] Updating user user-4pwnt. Adding principal
2021/01/15 22:38:22 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-qtl2c
2021/01/15 22:38:22 [INFO] [mgmt-auth-grb-controller] Creating clusterRoleBinding for globalRoleBinding grb-qtl2c for user u-4rg9h with role cattle-globalrole-user
2021/01/15 22:39:02 [ERROR] API error response 500 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: ldap: connection timed out
2021/01/15 22:39:33 [INFO] Creating user for principal activedirectory_user://CN=testuser2,CN=Users,DC=testad,DC=rancher,DC=io
2021/01/15 22:39:33 [INFO] Creating globalRoleBindings for u-npjx57vxal
2021/01/15 22:39:33 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-pf8l7
2021/01/15 22:39:33 [INFO] [mgmt-auth-grb-controller] Creating clusterRoleBinding for globalRoleBinding grb-pf8l7 for user u-npjx57vxal with role cattle-globalrole-user
2021-01-15 22:39:45.555813 I | mvcc: store.index: compact 8110
2021-01-15 22:39:45.582530 I | mvcc: finished scheduled compaction at 8110 (took 25.847113ms)
E0115 22:40:49.925131      24 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
E0115 22:42:37.323254      24 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
2021-01-15 22:44:45.559876 I | mvcc: store.index: compact 9381
2021-01-15 22:44:45.588543 I | mvcc: finished scheduled compaction at 9381 (took 27.846738ms)
2021/01/15 22:45:25 [ERROR] API error response 500 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: ldap: connection timed out
E0115 22:49:37.787219      24 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
2021-01-15 22:49:45.563884 I | mvcc: store.index: compact 10609
2021-01-15 22:49:45.589640 I | mvcc: finished scheduled compaction at 10609 (took 24.950368ms)
2021-01-15 22:54:45.567656 I | mvcc: store.index: compact 11837
2021-01-15 22:54:45.592170 I | mvcc: finished scheduled compaction at 11837 (took 23.682082ms)
E0115 22:54:55.262359      24 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted

```

**Other details that may be helpful:**
This issue is seen on 2.4.12, 2.5.5 also

**Environment information**
- Rancher version: v2.4.13-rc3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
- Kubernetes version (use `kubectl version`): 1.18.14/1.18.15

**Comment by prachidamle** [comment]
@Ellenqs seems like this is a rancher test AD setup, can you share the details on how to configure this setup and the user credentials so that I can reproduce at my end. Thanks!

**Comment by Ellenqs** [comment]
> @Ellenqs seems like this is a rancher test AD setup, can you share the details on how to configure this setup and the user credentials so that I can reproduce at my end. Thanks! You can slack me the details.

Here is the AD setup link: https://github.com/rancherlabs/the-ranch/wiki/Authentication-Test-Setup-configuration#ad-with-tls-enabled

**Comment by prachidamle** [comment]
@Ellenqs I see this issue happen only in case this particular user `testuser2` for this AD setup - since this user is part of 1000+ groups the query to sync all the user's groups is timing out.

We need to increase the connection timeout in the AD config for this setup to not hit this issue. Also, while investigating found a small enhancement we can do to avoid synching unncessary group details during user login. PR is https://github.com/rancher/rancher/pull/31067

**Comment by prachidamle** [comment]
@Ellenqs To test the login for `testuser2` user for this setup , it is a must to increment the connection timeout to 10000 ms atleast. The fix merged is to avoid syncing unnecessary details and that has reduced the time needed to login this user - but still this incremented timeout of 10000 ms is needed.

**Comment by Ellenqs** [comment]
This is validated on Rancher `v2.5-head 3c4c625f` and `master-head 88cee26`.

For both versions do the same steps as below.

**Steps**

- Deploy rancher single install.
- Set up AD authentication,  setting ""server connection timeout" to 10000 ms.
- Logout,  login as "testuser2" . (Try this step multiple times)
- Edit the AD authentication by setting ""server connection timeout" to 5000ms.
- Logout,  login as "testuser2" . (Try this step multiple times)

**Results**

Users login successfully on both versions when the timeout is set to 10000ms. (Same error occurred when timeout is set to 5000 ms). This is expected.
