### ISSUE TITLE
Google Cloud Platform UI to be able to work with Shared VPC

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#30864]
Currently, Rancher UI is unable to create clusters when a project is a "service project" on a shared VPC.

In this scenario, the service project must use a network that's provided to it by the Host Project, which owns all organization level networks.

Current Rancher UI only lists "local networks" (local to the project), not offering a way to select "Networks shared with my project".

Rancher2 terraform provider is able to create clusters with this configuration. Being able to do so confirms the problem's scope is the UI.

Attached are GCP screens showing how their interface lists the relevant objects and a simple terraform file showing how the objects are configured to be sent to rancher.

**Comment by fabrinator** [comment]
I'm curious for view the attached files. Can you post them here? I don't have access to the link that you provided.

Kind Regards

**Comment by mtterry-qfree** [comment]
I'm running into this issue currently. we have a requirement that we have a shared VPC in which we deploy to. I'm looking into simply "importing" my gke cluster, but i'm sure that's not ideal.

**Comment by cbron** [comment]
This can only be truly tested through the UI

**Comment by prabalsharma** [comment]
I was able to create a public cluster on a `service project` using shared vpc from a `host project`, on 2.5-head UI
