### ISSUE TITLE
 How to delete the built-in local cluster, I don't need this

### ISSUE THREAD

**Issue by dw-3** [rancher/rancher#30879]
rancher latest

docker 1.18.9
![image](https://user-images.githubusercontent.com/20983001/104979676-cfc27800-5a3f-11eb-9698-b6cb44494aed.png)

**Comment by a983132370** [comment]
Before Rancher v2.5, it was possible to run the Rancher server using this flag to hide the local cluster: --add-local=false.
But after Rancher v2.5 ..

**Comment by dw-3** [comment]
how do this?
