### ISSUE TITLE
Storage Pool and Volumes name are blue and clickable but don't go anywhere

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3088]
v0.50.2-rc2

Steps:
1.  Create two hosts and add convoy.glusterfs=true as label 
2.  Create and started Gluster FS
3.  Create and started Convoy Gluster FS
4.  Added new Stack
5.  Create Service (scale 2)
  	image - ubuntu
     	Volumes - tani:/tani1
     	Volume Driver - convoy-gluster
6.  Go to Infrastructure/Storage pool
7.  In Volume section, click on convoy-gluster storage pool name (goes to blank page)
8.  Under Volumes/Name click on tani (nothing happens)

Results:
Goes to a blank page for storage pool name and for volume name does nothing.

Expected:
Should either not be a link, or it should go somewhere.

**Comment by lvuch** [comment]
fix in https://github.com/rancher/rancher/issues/3088

**Comment by tfiduccia** [comment]
Version - master 3/23
Verified fixed
