### ISSUE TITLE
When View/Edit YAML report invalid character '\\x1f' looking for beginning of value

### ISSUE THREAD

**Issue by Leon-pan** [rancher/rancher#30881]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. https://rancher/c/c-579x2/projects-namespaces
2. choose one namespace
3. click View/Edit YAML

**Result:**
![image](https://user-images.githubusercontent.com/37100346/104991511-e1187e00-5a59-11eb-9e61-f3bea747f7b0.png)

report invalid character '\\x1f' looking for beginning of value
![image](https://user-images.githubusercontent.com/37100346/104991549-f5f51180-5a59-11eb-8f8d-f46c5300d643.png)

**Other details that may be helpful:**
some namespace can work,other can't.

![image](https://user-images.githubusercontent.com/37100346/104991590-1329e000-5a5a-11eb-930c-9477a28e8bb9.png)

**Environment information**

- cluster local : v1.19.5+k3s2
- cluster work : v1.19.6-rancher1-1

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by Leon-pan** [comment]
rancher log
![Snipaste_2021-01-19_09-53-25](https://user-images.githubusercontent.com/37100346/104992242-94ce3d80-5a5b-11eb-95d8-1c326406703c.png)

**Comment by 615don** [comment]
I have the same problem but when trying to edit workloads. I can edit namespaces just fine but not a single workload works.

**Comment by hachi-zzq** [comment]
可以通过 kubectl 命令行绕过去。

**Comment by Leon-pan** [comment]
> 可以通过 kubectl 命令行绕过去。

kubectl 怎么获取整个namespace的yml，集群迁移有用

**Comment by hachi-zzq** [comment]
kubectl get pods
