### ISSUE TITLE
Add support for service restart.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3089]
Expose service restart option in UI to extend support for rolling upgrade - #2423

**Comment by xaka** [comment]
Would be really nice to have it. It's available in UI for containers, but not service.

**Comment by jurajseffer** [comment]
It looks like you can close this ticket. I do have a question however about the implementation of rolling service restarts, e.g. one container at a time. Is the container removed from the load balancer before it's stopped and then added after it's started and passed health checks? Or does it just restart the container but load balancer might send requests to it during its restart?

**Comment by will-chan** [comment]
@alena1108 can you answer this question and close the issue.  Thanks?

**Comment by alena1108** [comment]
@jurajseffer 

> Or does it just restart the container but load balancer might send requests to it during its restart?

Today we do not synchronize between container stop and removing it from the LB, but we are planning to implement it in the future. Here is the issue were we keep track of it:

https://github.com/rancher/rancher/issues/2777#issuecomment-251520654


@will-chan this issue should probably remain opened for the UI component to support rolling restart for the service (already available via API)
