### ISSUE TITLE
[UI] Add option in node template to skip Docker installation

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#30895]
Issue: https://github.com/rancher/rancher/issues/27646
Backend PR: https://github.com/rancher/machine/pull/109

Add option `None` to Docker installation options to let users opt-in for skipping it.
The new option should set `engineInstallURL` to `"None"` for the backend to skip the Docker installation.
Additionally, a note that informs users it will skip docker installation and the expectation is the user has already pre-installed everything should be included.

**Comment by deniseschannon** [comment]
Based on the backend issue https://github.com/rancher/rancher/issues/27646 , are we able to use "None" and "none" in the options?

**Comment by westlywright** [comment]
It looks like the backend says "none". I'll update the value and push a new build.

**Comment by westlywright** [comment]
@slickwarren please dont test this yet, i need to change the value in the UI.

**Comment by vincent99** [comment]
The backend should probably be case-insensitive on this...

**Comment by slickwarren** [comment]
Tested on master-head (fbe2c30d9ffbca7635fe82ccc09f797cfc13c288) and 2.5-head (8201e080df72f45f5bbb5b603c76c22629a723ae) 
* none option in engine options -> docker:  
<img width="1320" alt="Screen Shot 2021-02-05 at 3 49 38 PM" src="https://user-images.githubusercontent.com/16691014/107101301-bbb2a080-67cb-11eb-8ea4-bea12ee60a4e.png">
* also tested changing different capitalization (NoNe) and that worked as well.
