### ISSUE TITLE
kubelet has disk pressure - I have tried locating excess container logs as suggested but none exist....

### ISSUE THREAD

**Issue by L00131130** [rancher/rancher#30898]
'''
# Run kubectl commands inside here
# e.g. kubectl get all
> kubectl describe node ubuntu-server
Name:               ubuntu-server
Roles:              controlplane,etcd,worker
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ubuntu-server
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/controlplane=true
                    node-role.kubernetes.io/etcd=true
                    node-role.kubernetes.io/worker=true
Annotations:        flannel.alpha.coreos.com/backend-data: {"VtepMAC":"2a:3e:62:1b:16:2c"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 192.168.0.109
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4IPIPTunnelAddr: 10.42.0.1
                    rke.cattle.io/external-ip: 192.168.0.109
                    rke.cattle.io/internal-ip: 192.168.0.109
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 26 Aug 2020 20:31:55 +0000
Taints:             node.kubernetes.io/disk-pressure:NoSchedule
                    node.kubernetes.io/unschedulable:NoSchedule
Unschedulable:      true
Lease:
  HolderIdentity:  ubuntu-server
  AcquireTime:     <unset>
  RenewTime:       Tue, 19 Jan 2021 21:37:51 +0000
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Tue, 19 Jan 2021 14:32:51 +0000   Tue, 19 Jan 2021 14:32:51 +0000   FlannelIsUp                  Flannel is running on this node
  MemoryPressure       False   Tue, 19 Jan 2021 21:33:17 +0000   Wed, 26 Aug 2020 20:31:55 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         True    Tue, 19 Jan 2021 21:33:17 +0000   Tue, 19 Jan 2021 21:32:57 +0000   KubeletHasDiskPressure       kubelet has disk pressure
  PIDPressure          False   Tue, 19 Jan 2021 21:33:17 +0000   Wed, 26 Aug 2020 20:31:55 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Tue, 19 Jan 2021 21:33:17 +0000   Tue, 19 Jan 2021 14:32:13 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  192.168.0.109
  Hostname:    ubuntu-server
Capacity:
  cpu:                16
  ephemeral-storage:  20511312Ki
  hugepages-2Mi:      0
  memory:             30094396Ki
  pods:               110
Allocatable:
  cpu:                16
  ephemeral-storage:  18903225108
  hugepages-2Mi:      0
  memory:             29991996Ki
  pods:               110
System Info:
  Machine ID:                 7265fe765262551a676151a24c02b7b6
  System UUID:                fb79222c-ef08-4d94-ad56-d81340278eb5
  Boot ID:                    99ac02d8-e33f-4e02-98b1-1c08c0a3c834
  Kernel Version:             5.4.0-53-generic
  OS Image:                   Ubuntu 20.04.1 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://19.3.8
  Kubelet Version:            v1.18.6
  Kube-Proxy Version:         v1.18.6
PodCIDR:                      10.42.0.0/24
PodCIDRs:                     10.42.0.0/24
Non-terminated Pods:          (9 in total)
  Namespace                   Name                                     CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                                     ------------  ----------  ---------------  -------------  ---
  cattle-system               cattle-cluster-agent-9649d6d8f-4qq5v     0 (0%)        0 (0%)      0 (0%)           0 (0%)         1s
  cattle-system               cattle-node-agent-24p5n                  0 (0%)        0 (0%)      0 (0%)           0 (0%)         43m
  cattle-system               kube-api-auth-krmkn                      0 (0%)        0 (0%)      0 (0%)           0 (0%)         42m
  ingress-nginx               default-http-backend-598b7d7dbd-f649n    10m (0%)      10m (0%)    20Mi (0%)        20Mi (0%)      2s
  ingress-nginx               nginx-ingress-controller-pwrhc           0 (0%)        0 (0%)      0 (0%)           0 (0%)         5m59s
  kube-system                 canal-7c2nv                              250m (1%)     0 (0%)      0 (0%)           0 (0%)         146d
  kube-system                 coredns-849545576b-bbzsh                 100m (0%)     0 (0%)      70Mi (0%)        170Mi (0%)     109s
  kube-system                 coredns-autoscaler-5dcd676cbd-mgk8k      20m (0%)      0 (0%)      10Mi (0%)        0 (0%)         1s
  kube-system                 metrics-server-697746ff48-ptjh5          0 (0%)        0 (0%)      0 (0%)           0 (0%)         2s
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                380m (2%)   10m (0%)
  memory             100Mi (0%)  190Mi (0%)
  ephemeral-storage  0 (0%)      0 (0%)
Events:
  Type     Reason                 Age                  From                    Message
  ----     ------                 ----                 ----                    -------
  Warning  ImageGCFailed          39m                  kubelet, ubuntu-server  wanted to free 901515673 bytes, but freed 0 bytes space with errors in image deletion: [rpc error: code = Unknown desc = Error response from daemon: conflict: unable to remove repository reference "rancher/coreos-etcd:v3.4.3-rancher1" (must force) - container a91c91c204e7 is using its referenced image a0b920cf970d, rpc error: code = Unknown desc = Error response from daemon: conflict: unable to remove repository reference "rancher/hyperkube:v1.18.6-rancher1" (must force) - container 3879d572f107 is using its referenced image 5a1e9f24e782, rpc error: code = Unknown desc = Error response from daemon: conflict: unable to remove repository reference "rancher/rke-tools:v0.1.59" (must force) - container 2ee5bc1ffe64 is using its referenced image 904d2afa34c8, rpc error: code = Unknown desc = Error response from daemon: conflict: unable to remove repository reference "rancher/rancher:latest" (must force) - container 3103d8354839 is using its referenced image fb0772b142fe]
  Normal   NodeHasNoDiskPressure  11m (x53 over 7h5m)  kubelet, ubuntu-server  Node ubuntu-server status is now: NodeHasNoDiskPressure
  Warning  EvictionThresholdMet   5m6s (x219 over 7h)  kubelet, ubuntu-server  Attempting to reclaim ephemeral-storage
  Normal   NodeHasDiskPressure    5m1s (x50 over 7h)   kubelet, ubuntu-server  Node ubuntu-server status is now: NodeHasDiskPressure
'''

**Comment by superseb** [comment]
If the disk/mount is full, you need to resize it to allocate more space (or clean up data that is not needed, or mount another disk/volume to the location that is taking space). It automatically tries to cleanup images but not images that are in use. `df -h` and/or `df -i` on the node having disk pressure will reveal what is getting full.

**Comment by L00131130** [comment]
thomas@ubuntu-server:/$ sudo df -h
[sudo] password for thomas: 
Filesystem                         Size  Used Avail Use% Mounted on
udev                                15G     0   15G   0% /dev
tmpfs                              2.9G  1.9M  2.9G   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   20G   16G  3.3G  83% /
tmpfs                               14G     0   14G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                               14G     0   14G   0% /sys/fs/cgroup
/dev/sda2                          976M  292M  618M  33% /boot
/dev/loop0                          56M   56M     0 100% /snap/core18/1932
/dev/loop1                          56M   56M     0 100% /snap/core18/1944
/dev/loop2                          71M   71M     0 100% /snap/lxd/16922
/dev/loop3                          68M   68M     0 100% /snap/lxd/18150
/dev/loop4                          32M   32M     0 100% /snap/snapd/10707
/dev/loop5                          32M   32M     0 100% /snap/snapd/10492
tmpfs                              2.8G     0  2.8G   0% /run/user/1000
overlay                             20G   16G  3.3G  83% /var/lib/docker/overlay2/7b566d5cf199cc8a398c3ba7d68e763974dedb02a2bdf1cdd77ad3d54177fc62/merged
overlay                             20G   16G  3.3G  83% /var/lib/docker/overlay2/50b609d824b22e54a1338639a9086ce82e98bd08257e9edb12f3a3258927cbc9/merged
overlay                             20G   16G  3.3G  83% /var/lib/docker/overlay2/67661aa9ea49c852df6a915771261c18e26f8005aea4c08ce26960b07495097f/merged
overlay                             20G   16G  3.3G  83% /var/lib/docker/overlay2/07904042959d8dd8e65389f2154c9c0b9b179f28a35018c2af7f66179e561fed/merged
overlay                             20G   16G  3.3G  83% /var/lib/docker/overlay2/3aee2dcf2be86171052f220075e52b7a724b4bca8d71a571b639214e3faba7d9/merged
overlay                             20G   16G  3.3G  83% /var/lib/docker/overlay2/ff09100ba600aa93f515a3193961941928a84e4bfcfaacde9f41e70fe7f8bafe/merged
overlay                             20G   16G  3.3G  83% /var/lib/docker/overlay2/7580e34c3f1a40effceb9d872fe7d593e2a1df2289dd5c6b871d64b3cabc50f5/merged
shm                                 64M     0   64M   0% /var/lib/docker/containers/a91c91c204e7f9f8a941aebffb6276e66095fde173b81cb51fdaa8bbcc7df99d/mounts/shm
shm                                 64M     0   64M   0% /var/lib/docker/containers/94d0828b9f4ee980c9859a9ff55a15e1bf1bbad904cebadf1e3f448062a09668/mounts/shm
shm                                 64M     0   64M   0% /var/lib/docker/containers/61155cf5cae084e0f8d0918c4d43b9bfea92229ea0b64378b1dee77df048b645/mounts/shm
shm                                 64M     0   64M   0% /var/lib/docker/containers/42ac1abb61753d9d35de532e9bfa252307f6d24c1f551e238c9bba65c4d53bac/mounts/shm
shm                                 64M     0   64M   0% /var/lib/docker/containers/3879d572f107af6401e185833e9cc1eaada5f16660a5ad431fee99ec9469d85f/mounts/shm
shm                                 64M     0   64M   0% /var/lib/docker/containers/35f2e2eb00cbf18fd17936dd78f63cd68d3fd9ff8353125248e77f28a031c76c/mounts/shm
tmpfs                               15G   12K   15G   1% /var/lib/kubelet/pods/9b65d82e-fe77-4031-b139-022a543d2df2/volumes/kubernetes.io~secret/canal-token-lpb6s
overlay                             20G   16G  3.3G  83% /var/lib/docker/overlay2/6309382089cadad070c4d243bfcc4b3175d516f94230023f406b85f0f3b70fe9/merged
shm                                 64M     0   64M   0% /var/lib/docker/containers/4937719919f1c2028fd6aa7d646372e7574c16991d1d12fea2226c9b170b4347/mounts/shm
overlay                             20G   16G  3.3G  83% /var/lib/docker/overlay2/8823118e3016060312015dd108c9c6d2d7983dc6004611d6348ff57f47ed139f/merged
overlay                             20G   16G  3.3G  83% /var/lib/docker/overlay2/98f8f73e2edb74e469495bb2bf76b3ccabdc1c54566b64b5962e732314538a63/merged
tmpfs                               15G   12K   15G   1% /var/lib/kubelet/pods/7a329c09-6dbd-48fc-b4f4-23c9c5a875a6/volumes/kubernetes.io~secret/coredns-token-jnfgz
overlay                             20G   16G  3.3G  83% /var/lib/docker/overlay2/f034df031cabaa54904ee475120d649bdf149e46a10cea7c72c5931e4dcbd3e2/merged
shm                                 64M     0   64M   0% /var/lib/docker/containers/9464faabd54307092eb91913cf6f360721f1addbf873b6aeea26a0b2fbd595a9/mounts/shm
overlay                             20G   16G  3.3G  83% /var/lib/docker/overlay2/308a7c1963dcbc6544deada57398d479f6c2390505c6fd81ee5e88b1f6e9e78d/merged


any Idea what all these 20G overlays are???

**Comment by L00131130** [comment]
completed a docker purge -a but that only cleared 1.2 Gb
How can I identify the overlays that are worthy of deletion?

**Comment by superseb** [comment]
Here are the limits for garbage collection: https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/, so you are hitting that, thats why it's trying to free space but it apparently can't.

My system with `rancher/rancher:latest` and the node being added to a cluster comes in at 9GB, you have 16GB in use. Did you locate where the space is being used? Is it in the Docker root directory or somewhere else in root (`/`)?

If you have workloads running that add up to the usage you are seeing you have to extend your disk.

**Comment by L00131130** [comment]
I have seemed to have located the issue with a code-server container which had a large dlib package.. I deleted this deployment and the issues have stopped so far consistently.  I will be redeploying one by one to see if I experience the same issue again but I suppose increasing the default ephemeral storage size would have worked, I was unable to figure that out...
