### ISSUE TITLE
Links not showing up in graph or in edit/clone until I refresh

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3090]
v0.50.2-rc2

Steps:
1.  Create a new Stack
2.  Add a service call service1
3.  Add a service called service2 and link it to 1
4.  Add a load balancer and link it to service2
5.  Add a Service alias and link it to Load balancer
6.  Go to graph
7.  Edit/clone/upgrade any of the above services

Results:  None of the targets/links are showing up.  It looks like there were never created.
![image](https://cloud.githubusercontent.com/assets/11514927/11909898/6cea180e-a5aa-11e5-9a2c-decb6d8b7b55.png)

after refresh
![image](https://cloud.githubusercontent.com/assets/11514927/11909965/0a1d544c-a5ab-11e5-9b19-dc084d1a86cf.png)

Expected:
Links/targets should show up in beginning.  It's very confusing to the user that they don't show up anywhere until after a refresh of the screen.

**Comment by deniseschannon** [comment]
Did you have a second environment? You might be hitting #1389.

**Comment by vincent99** [comment]
Works for me™, but running with the fix for #1389...

**Comment by tfiduccia** [comment]
Version - master 01/19
Verified fixed
