### ISSUE TITLE
Kubeconfig token gets automatically disabled after some time (no store found)

### ISSUE THREAD

**Issue by nikhilno1** [rancher/rancher#30905]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Possibly after Active Directory was configured

**Result:**
Unable to run kubectl commands. Get following error:
"error: You must be logged in to the server (the server has asked for the client to provide credentials)"

Can see that the corresponding token has enabled set to false.
```
{
"annotations": {
"lifecycle.cattle.io/create.cat-token-controller_c-tvkq7": "true"
},
"authProvider": "local",
"baseType": "token",
"clusterId": "c-tvkq7",
"created": "2021-01-19T14:55:10Z",
"createdTS": 1611068110000,
"creatorId": null,
"current": false,
"description": "Kubeconfig token",
"enabled": false,
"expired": false,
"expiresAt": "",
"groupPrincipals": null,
"id": "kubeconfig-user-8ttkw.c-tvkq7",
"isDerived": true,
"labels": {
"authn.management.cattle.io/kind": "kubeconfig",
"authn.management.cattle.io/token-userId": "user-8ttkw",
"cattle.io/creator": "norman"
},
"lastUpdateTime": "",
"links": {
"remove": "…/v3/tokens/kubeconfig-user-8ttkw.c-tvkq7",
"self": "…/v3/tokens/kubeconfig-user-8ttkw.c-tvkq7",
"update": "…/v3/tokens/kubeconfig-user-8ttkw.c-tvkq7"
},
"name": "kubeconfig-user-8ttkw.c-tvkq7",
"ttl": 0,
"type": "token",
"userId": "user-8ttkw",
"userPrincipal": "map[metadata:map[creationTimestamp:<nil>]]",
"uuid": "21803f6b-1905-4a96-ab2f-4980e166e7cd"
}
```
If I try to set it back to enable, I get "store not found error"
```
{
"baseType": "error",
"code": "NotFound",
"message": "no store found",
"status": 404,
"type": "error"
}

```
**Other details that may be helpful:**
It is an RKE cluster created from Rancher. I had previously configured Active Directory but later removed it.
As a workaround, I delete the token and download the new kubeconfig file. After that I am able to run kubectl commands for 30 mins or so before I run into this issue again.
One more thing I noticed is that my Rancher UI session also gets terminated even though the expiry is set to 24 hours.
And I have to enter the password twice to login. The first time, I get the login screen back and second attempt works.

I have also tried disabling the kubeconfig-generate-token setting so that I can login using username/password but even in that case I faced the same problem.

**Environment information**
- Rancher version: v2.5.5
- Installation option: HA (K3S)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Created a new cluster on existing VM
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM (16 cores, 28 GB RAM)
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:37:17 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:35:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[commscope@ansu demo]$

```

**Comment by nikhilno1** [comment]
Hello, any comments on this issue? Thanks

**Comment by nikhilno1** [comment]
Hello, this issue is really coming in the way of using Rancher. I am unable to use Rancher CLI since the tokens keep getting disabled. Can someone help please?

**Comment by nikhilno1** [comment]
So finally I did a re-installation of Rancher and K3s cluster including creating a new external MySQL DB. That has resolved this problem.

**Comment by Gidiklf** [comment]
@nikhilno1  could you provide more details it happend to us as well while we are using Active Directory a random user get the following error on kubectl commands:
"You must be logged in to the server" 
and the token state changed to enabled: false

**Comment by nikhilno1** [comment]
As I mentioned...I did a re-installation. It's important to create a new DB.

**Comment by Gidiklf** [comment]
Which db? We are using the active directory Authenticator

**Comment by nikhilno1** [comment]
I used external mysql DB.
