### ISSUE TITLE
Incorrect info message is seen while "Adding hosts" to an import cluster 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30904]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Click on Add cluster --> Other Cluster --> Give in a Name `test-import`--> Create
- From Rancher --> cluster - `test-import` --> Ellipsis --> "Add Host"
- UI Shows `You are creating an EKS cluster that has private API access only. Rancher requires network access to the Kubernetes endpoint to complete cluster creation; You must manually run one of the following commands.` which is incorrect.
<img width="1896" alt="Screen Shot 2021-01-19 at 5 15 01 PM" src="https://user-images.githubusercontent.com/26032343/105113696-43817680-5a7a-11eb-8379-e97d6a4073d9.png">

**Expected Result:** 
That info message is not applicable in this case

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.5 / 2.5-head - commit id: `3d62d5d65`
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Import cluster
- Kubernetes version (use `kubectl version`):

```
any
```

**Comment by slickwarren** [comment]
this is changed on rancher v2.5-head (5f3fcb84337d7e63b7d4513aaa0a33b61ff2ffbe)
* Click on Add cluster --> Other Cluster --> Give in a Name test-import--> Create
* From Rancher --> cluster - test-import --> Ellipsis --> "Add Host"
<img width="1729" alt="Screen Shot 2021-02-03 at 10 10 10 AM" src="https://user-images.githubusercontent.com/16691014/106791121-5dd65b00-6609-11eb-96f3-814b8c9156b8.png">

### **no info message displays**
@westlywright is that expected? Or should we display the same info message displayed when the user creates the imported cluster
<img width="1401" alt="Screen Shot 2021-02-03 at 10 13 11 AM" src="https://user-images.githubusercontent.com/16691014/106791493-d3dac200-6609-11eb-833c-31055aeaf91b.png">

**Comment by westlywright** [comment]
No, if its import we should see the import cluster info/modal. I'll investigate.

**Comment by slickwarren** [comment]
fixed on 2.5-head (8201e080df72f45f5bbb5b603c76c22629a723ae)
<img width="1704" alt="Screen Shot 2021-02-05 at 3 01 55 PM" src="https://user-images.githubusercontent.com/16691014/107098069-3dea9700-67c3-11eb-976c-4772003c42e4.png">

**Comment by sowmyav27** [comment]
Reopening for validating on master-head

**Comment by slickwarren** [comment]
also verified fixed on master-head (fbe2c30d9ffbca7635fe82ccc09f797cfc13c288) 
<img width="1745" alt="Screen Shot 2021-02-05 at 3 39 51 PM" src="https://user-images.githubusercontent.com/16691014/107100154-6759f180-67c8-11eb-9dbf-7078c481e050.png">
