### ISSUE TITLE
Cluster Explorer responds with "improper constraint" on 4 digit chart version

### ISSUE THREAD

**Issue by mogoman** [rancher/rancher#30912]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a helm chart with a 4 digit version, example 0.0.1.1
2. Install the chart using the Rancher Cluster Explorer

**Result:**

Message in red "improper constraint: 0.0.1.1" 

![Screenshot 2021-01-20 at 16 36 30](https://user-images.githubusercontent.com/1077806/105198660-2c0bc180-5b3e-11eb-8be3-342b44baeb5b.png)

**Other details that may be helpful:**

3 digit version numbers not affected, example 0.0.1 or 0.0.2 install without problems. Using cluster manager, it is possible to install catalog apps with 4 digit version numbers.

**Environment information**
- Rancher version 2.5.5

**Comment by vincent99** [comment]
Helm chart versions are [defined to be](semver), and a valid semver has exactly 3 numbers.
