### ISSUE TITLE
Template reset settings after editing and saving 

### ISSUE THREAD

**Issue by myl82** [rancher/rancher#30910]
We use rancher with VmWare.
When I try to re-edit existing template I found that settings for some fields are reset. 
Fields is not empty but values in this fields, like "Data Center", "Resource Pool", "Data Source",  are changing to first value from drop-down menu.
Why it happens? Is it possible to fix it? 

--
Rancher v2.5.5

**Comment by stranljip** [comment]
I can reproduce this with a completely fresh install (Rancher with Docker on single node). The behavior is reproducable with different browsers (tested: Firefox 85, Chrome 88.0). The effects occurs as well with re-editing an existing template as well as cloning a template.
For me the following fields are reset:
- Scheduling
  - Resource Pool
  - Data Store
  - Folder
- Instance Options
  - Virtual Machine (Creation Method is set on Clone existing VM)
 The following fields are completely lost:
- networks

**Comment by fm4991** [comment]
same here :-(

**Comment by epnixsite** [comment]
I can confirm this still persits even on latest v2.4.13 version..

**Comment by stranljip** [comment]
kind/bug

**Comment by MichelZ** [comment]
Same here, 2.5.5. Really annoying problem :(
These fields seem to be affected for me:

- Data Store (gets reset to the first one in the list)
- Folder (just empty)
- Host (gets reset to "Any")
- Template (just empty)
- Networks (network is removed)

**Comment by MichelZ** [comment]
Duplicate of #30891

**Comment by asauerwein-nts** [comment]
2.5.7 resolved this for me

**Comment by myl82** [comment]
Yes, as I see, after Rancher 2.5.7 update the issue resolved for me too.
