### ISSUE TITLE
Audit logs - UI hangs and no details presented when info button is clicked as soon as the audit entry appears.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3091]
Server - Build from master

Steps to reproduce the problem:

Restarted a service using api.
As soon as a new "api.service.create" audit entry shows up in the "Audit Log" , click on info button .
UI hangs and I see only "Dismiss" button.

<img width="1192" alt="screen shot 2015-12-18 at 5 03 46 pm" src="https://cloud.githubusercontent.com/assets/4266958/11910342/5d829432-a5a9-11e5-94e8-75f9115fa77b.png">

sometimes I see the contents load after waiting for couple of minutes.

**Comment by westlywright** [comment]
@sangeethah I am not seeing this locally. I could have been resolved by one of the other fixes i put in. When everything is merged in lets see if this is still a problem. Is there a status you'd like me to change it to in cases like this?

**Comment by sangeethah** [comment]
@westlywright , This  issue is not reproducible always. But seems to happen when you try to click on info button as soon as the audit entry is available. You can mark as "status-to-test" and assign  the bug back to me . I will see if I can reproduce with later build.

**Comment by sangeethah** [comment]
Tested with latest build from master:
Not able to reproduce the issue where UI hangs when trying to view information for an audit entry. I do see a small delay in loading the information after the "Dismiss" button appears, but not able to reproduce the issue where the UI hangs.
