### ISSUE TITLE
Istio sidecar injection - workload deployment failed with error in sidecar injector 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#30921]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

Istio Version: 1.5.901

**Steps to reproduce (least amount of steps as possible):**
1. Spin up a rancher 2.4-head[e0e2866e7]
2. Add a cluster with 2 worker nodes and 1 etcd, 1 control plane
3. Enable monitoring and istio
4. Create a namespace with istio side-car injection enabled
5. Deploy a workload in the above namespace
6. The deployment fails with the error :
```
2021-01-20T20:16:08.176482Z	error	Injection data: err=failed parsing generated injected YAML (check Istio sidecar injector configuration): error converting YAML to JSON: yaml: line 160: did not find expected key spec=
**Result:**
```
**Other details that may be helpful:**
Istio side car injector pod logs has the following error:
```
2021-01-20T21:34:39.032436Z	info	AdmissionReview for Kind=/v1, Kind=Pod Namespace=anupama-istio-ns Name= (anupama-istio-wk-6f4f6c95fb-***** (actual name not yet known)) UID=8ef6fa83-c9b3-43d4-ba4e-e8e7b3fb9b9b Rfc6902PatchOperation=CREATE UserInfo={system:serviceaccount:kube-system:replicaset-controller 1045e5ca-031e-4b1c-b4ef-4b3d98115407 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]}
2021-01-20T21:34:39.044493Z	warn	Failed to unmarshal template error converting YAML to JSON: yaml: line 160: did not find expected key rewriteAppHTTPProbe: true
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

Rancher | 2.4-head[e0e2866e7]
User Interface | v2.4-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

- Installation option (single install/HA): Single

**Comment by anupama2501** [comment]
The issue is not seen on v2.4.12, followed same steps as above.
Rancher version v2.4.12 (f65114dc6), Istio version: 1.5.900
Spin up a rancher 2.4-head[e0e2866]
Add a cluster with 2 worker nodes and 1 etcd, 1 control plane
Enable monitoring and istio
Create a namespace with istio side-car injection enabled
Deploy a workload in the above namespace

**Comment by Ellenqs** [comment]
I see the same error happen on v2.5-head commit: 23a29c3

> Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post "https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s": context deadline exceeded

**Comment by paynejacob** [comment]
https://github.com/rancher/system-charts/pull/401

**Comment by anupama2501** [comment]
Verified the issue on 2.4-head[4c214400c]
Istio [1.5.901]
Steps performed:
Create a cluster as a standard user with 1 control plane, 2 worker nodes and 1 etcd
From the tools of the cluster [v1 charts] enable monitoring and enable istio [1.5.901]
once all the namespaces come active, create a namespace with istio-sidecar injection enabled in the namespace
Deploy a workload in this namespace
Workloads came active without the issue mentioned above 

<img width="1175" alt="Screen Shot 2021-01-22 at 3 59 44 PM" src="https://user-images.githubusercontent.com/38144301/105561246-0f50c480-5ccb-11eb-8fed-489573a18123.png">
<img width="700" alt="Screen Shot 2021-01-22 at 3 59 34 PM" src="https://user-images.githubusercontent.com/38144301/105561252-14157880-5ccb-11eb-9856-997a0eaf005f.png">
