### ISSUE TITLE
Cluster stuck in provisioning	[controlPlane] Failed to upgrade Control Plane: [[host worker-1 not ready]]

### ISSUE THREAD

**Issue by sidheshdivekar29** [rancher/rancher#30926]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a custom cluster, copy paste command for worker node.

**Result:**
Cluster stuck in [controlPlane] Failed to upgrade Control Plane: [[host worker-1 not ready]

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v.2.5.1
- Installation option (single install/HA):
Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM ubuntu 16.04.2, 2 processors, 1024MB
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
20.10.2
```
![Screen Shot 2021-01-20 at 11 59 42 PM](https://user-images.githubusercontent.com/15738685/105320997-b7f00e80-5b7b-11eb-9612-4ed32632f218.png)

**Comment by dalwar23** [comment]
For me it was the `cgroup` warning ⚠️ form docker that was putting `kubelet` into `crash loop`. So I fixed the docker warnings and restarted docker and the cluster came up online in no time.

**Comment by johnny12150** [comment]
> For me it was the `cgroup` warning ⚠️ form docker that was putting `kubelet` into `crash loop`. So I fixed the docker warnings and restarted docker and the cluster came up online in no time.
> 
> As for the `worker` nodes, i had to stop all the containers (also cleaned up the images) and run the `rancher` worker join command in all the worker nodes. It took about 20 mins for 3 worker node to come up and register itself with the cluster.

@dalwar23 
How did you solve the `kubelet into `crash loop` problem?
Could you provide more detailed information?
I am facing the same issue. Tks!

**Comment by dalwar23** [comment]
Here is a link that helped me - [StackExchange](https://unix.stackexchange.com/questions/342735/docker-warning-no-swap-limit-support)

**Comment by antonio-antonucci** [comment]
I am having the same issue unfortunately

Environment information
- Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI):
   - v2.6.3
- Installation option (single install/HA):
   - Single install

Cluster information
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
   - Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
   - VM ubuntu Ubuntu 20.04.3 LTS, 2 processors, 4096 MB
- Kubernetes version (use kubectl version):
   - Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
- Docker version
  -  20.10.7

**Comment by antonio-antonucci** [comment]
Solved ... it was a space issue on /var

**Comment by VardyNg** [comment]
> Solved ... it was a space issue on /var

Can you explain further? Where do you have a space issue with /var ? Thanks!

**Comment by thatsankur** [comment]
In Similar environment it works on one machine while fails with this error on other machine. I checked all machine have same number of ports open but this error is not going away.

**Comment by cuichenggen** [comment]
> Solved ... it was a space issue on /var

Can you explain further? Where do you have a space issue with /var ? Thanks!
