### ISSUE TITLE
[rancher-compose] rancher-compose up doesn't work after rancher-compose rm -f

### ISSUE THREAD

**Issue by boedy** [rancher/rancher#3093]
Maybe related to: https://github.com/rancher/rancher/issues/1723

After running `rancher-compose rm -f` all my services are removed, but my stack remains. I don't mind this, but if I run `rancher-compose up -d` again It will throw the following error for all my services:

```
ERRO[0000] Failed Creating <service name> : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name] from [<serverip>:8080/v1/services]
```

I have to delete the stack in the UI before I can run `rancher-compose up -d` again

**Comment by deniseschannon** [comment]
What version of Rancher are you running? There was a bug in v0.50.0 that has now been fixed where service name validation was occurring against removed services. So if you had a service that has been removed and in your DB, it wouldn't allow you to create a new one. 

This is most likely your issue and you need to upgrade to v0.50.2.

**Comment by boedy** [comment]
Yes I was on v0.50.0. I've just updated and seems to be working now.
