### ISSUE TITLE
Verify postgreSQL as a k3s backend

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#30932]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement/feature request

**Details:**

Currently k3s does not support postgresql on the Rancher Support Matrix, we need to perform Validation Steps to achieve this

ref - https://github.com/k3s-io/k3s/issues/2828

@cjellick 

gz#14360

**Comment by davidnuzik** [comment]
@rancher-max can you post test results / information in this issue?

**Comment by rancher-max** [comment]
Validated per our db certification matrix:
- Fresh Installation and run Sonobuoy Conformance tests
- Run functional test (all automated regression tests) on imported k3s cluster on Rancher
- Validate a longhorn deployment

k3s version: v1.19.5+k3s2
postgres version 11.5 (on AWS RDS)

**Comment by davidnuzik** [comment]
@rancher-max If we haven't yet we should also check: 1.17, 1.18, 1.20 K3s. Even if this is minimally a smoke test becuase we need to add it to the support matrix page for each of those versions soon.

**Comment by rancher-max** [comment]
The same as above has been validated now using the following versions: `v1.17.17+k3s1`, `v1.18.15+k3s1`, and `v1.20.2+k3s1`.
Note this was all done using Rancher v2.5.5.

**Comment by davidnuzik** [comment]
The plan is to get this added to the upcoming Rancher v2.5.6 support matrix.

**Comment by leflambeur** [comment]
@davidnuzik would we be able to validate 12.5 as well as 11.5?

**Comment by davidnuzik** [comment]
@leflambeur is there a deal at stake or anything I should be aware of? Feel free to enter a new GH issue to request this and notify me. Perhaps for March k3s patches we can do this (next Rancher v2.5.7).
