### ISSUE TITLE
Flags "force" and "delete_local_data" are bound together on cluster "upgrade_strategy"

### ISSUE THREAD

**Issue by lce-financial-com** [rancher/rancher#30933]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Log in to Rancher UI
- Select one cluster
- Click to edit the cluster
- Test the following behaviours:
-- Enabling only delete-local-data: doesn't work, flag is set back to false
-- Enabling only force: set both force and delete-local-data to true
-- Enabling both at the same time: works as the one above (both are enabled).

**Result:**
Flags are both enabled/disabled together when they should work separately.

**Environment information**
- Rancher version: 2.5.5
- Installation option: HA

**Cluster information**
- Cluster type: Hosted
- Machine type: metal
- Kubernetes version (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
```
Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by thecrazyrussian** [comment]
Still an issue in 2.5.8, this affects anyone updating the settings via the ui.
