### ISSUE TITLE
[v2.5.5] CA certificate box not active in OpenLDAP StartTLS authentication page

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#30930]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement 

**Steps to reproduce (least amount of steps as possible):**
- Install Rancher v2.5.5
- Configure authentication with OpenLDAP 
- Select StartTLS

**Result:**

CA certificate box is not active

**Other details that may be helpful:**

The issue is already addressed in 2.4.13-rc1 and also verified in the v2.5 master branch as per below comment
https://github.com/rancher/rancher/issues/30783#issuecomment-759702923
Opening this issue to track the milestone for the fix.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): HA

gz#14516

**Comment by Jono-SUSE-Rancher** [comment]
It looks like this was already validated but support was looking for an explicit issue in 2.5.

**Comment by izaac** [comment]
@Jono-SUSE-Rancher that's correct this functionality was validated a few builds back in v2.5.

But I double checked this in these newer build to be on the safe side too.


  - `master-head (02/05/2021)` _fbe2c30_
  - `v2.5-head (02/05/2021)` _8201e08_
