### ISSUE TITLE
Add minFleetVersion to rancher

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#30934]
Rancher auto-install/upgrade system charts(fleet,rancher-operator,rancher-webhook), which is not desirable. We need to add setting `min$(system-chart-name)Version` in rancher, so that if rancher detects that the current system has chart installed and meets minVersion, it should not attempt to upgrade.

**Comment by slickwarren** [comment]
I was able to test the following on 2.5-head (03b8153) and master-head (3134a9a) on a single install cluster: 
* CATTLE_RANCHER_WEBHOOK_MIN_VERSION
* CATTLE_RANCHER_OPERATOR_MIN_VERSION
* CATTLE_FLEET_MIN_VERSION

**note:** each chart deploys with the latest available version by default when creating a new rancher server. I was able to install older versions of each chart by going to `cluster explorer` -> Marketplace & Apps, selecting the app to modify, and changing the version there. 
To trigger the min_chart_version, I stopped rancher from running (as if doing a backup), and reran with the environment variable set (-e <APP>_MIN_VERSION=X.Y.Z for single install, --set 'extraEnv[0].name=<APP>_MIN_VERSION' --set 'extraEnv[0].value=X.Y.Z' for HA installs.

the following tests were performed:
* set <app> version to lower than the specified min version -- result: upgrades to latest chart version -- PASS
* set <app> version to higher or equal to specified min version -- result: remains on old version -- PASS
* set min version to nonexistent version lower than <app> version -- result: remains on old version -- PASS
* set min version to nonexistent version higher than <app> version -- result: upgrades to latest version -- PASS
* set min version to  invalid entry (ex. x.0y.123) -- result: logs show `[ERROR] Failed to install system chart <app>: Invalid Semantic Version` -- PASS
* set min version to null -- result: logs show `[ERROR] Failed to install system chart <app>: Invalid Semantic Version` -- PASS
* set multiple app versions at once -- result: older and newer chart versions behaved as stated in the above cases -- PASS

**Comment by slickwarren** [comment]
reopening for discussion (cc @sowmyav27 )
