### ISSUE TITLE
[rancher-compose] Update documentation to mentioned support for env_file option similar to docker-compose

### ISSUE THREAD

**Issue by xaka** [rancher/rancher#3095]
It looks like `env_file` option is missing for http://docs.rancher.com/rancher/rancher-compose/commands/, but present for `rancher-compose --help`. Not a big problem, but took me a while with a help from @cloudnautique to realize it's actually supported.

**Comment by cloudnautique** [comment]
Hi @xaka, the rancher-compose command does support environemnt files `-e` or `--env-file` should work. The command is built off of docker/libcompose which was contributed by us back to Docker. It is still a work in progress, but it is a Golang implementation of compose (which is python based). There is a PR on libcompose to add strict checking. 

Rancher compose does make some subtle changes in behavior that we feel help with managing production workloads. We also extend it to add support for some concepts that are not in the upstream docker compose, like load balancers, health checks etc.

**Comment by xaka** [comment]
Wow! That's nice. The reason I opened issue is because I couldn't find it in documentation nor on --help. Is it out of date or I'm too drunk?

**Comment by cloudnautique** [comment]
`rancher-compose --help` shows it for me.. I think it was added in rancher-compose v0.4.x maybe you have a really old version? :)

 I also couldn't find it in the docs, so we should fix that for sure.  Carry on with the :beer: :smile:

**Comment by xaka** [comment]
Alright alright, it's my fault (well, not actually mine, but :beers:), but I just double checked http://docs.rancher.com/rancher/rancher-compose/commands/ and couldn't find anything useful :stuck_out_tongue: . I'm going to change the title...

**Comment by deniseschannon** [comment]
@xaka Thanks for pointing out the outdated docs. I've updated them now. 

Rancher-compose is a bit trickier for me to catch updates cause I"m not following the docker/libcompose repo. Maybe I should be ;)
