### ISSUE TITLE
IPv4 Forwarding not active on newly created local clusters with RKE

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [rancher/rancher#30967]
***hat kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Install Rancher 2.5.5 on bare metal or virtual machine.
Create a new custom node on the local machine with default options plus enabling etcd, controlplane and worker.
Issuing docker command and wait until provisioning of the new clusternode is done.
Check IP-Forwarding status on new cluster shell by "sysctl net.ipv4.ip_forward"

**Result:**
0 = ipv4.ip_forward is not active

**Expected:**
Either ipv4_ip_forwarding set to 1 by default or an instruction how to archive this.

**Other details that may be helpful:**
The forwarding cannot be activated in the shell as the root-filesystem is read-only.
Trying to run a Wireguard workload on this node is not possible, because IP4 forwarding is mandatory.

**Environment information**
Version: Rancher 2.5.5.
Installation option: single install

**Cluster information**
- Cluster type:  Custom
- Machine type: VM
- Provider: RKE
- Kubernetes version: v1.19.6
- Docker version: 19.03.14

**Comment by DaveNadeau** [comment]
I'm having the same issue and it is affecting my ability to run WireGuard in a Rancher pod.  If I execute shell for the running pod and type: "sysctl -w net.ipv4.ip_forward=1" the connection instantly works, however, each time the pod is restarted the command needs to be run in the shell to get it to work.  Editing the .yaml file does not work as the changes to not persist.

**Comment by husdupflorin** [comment]
> I'm having the same issue and it is affecting my ability to run WireGuard in a Rancher pod. If I execute shell for the running pod and type: "sysctl -w net.ipv4.ip_forward=1" the connection instantly works, however, each time the pod is restarted the command needs to be run in the shell to get it to work. Editing the .yaml file does not work as the changes to not persist.

Hey, have you found any solution for this?

**Comment by Sesshoumaru-sama** [comment]
The issue still persists.
The idea with the "Init-Container" is great, but I still would request a streamliend fix for this. Its quite essential.
