### ISSUE TITLE
Add GCP cloud credential option

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#30981]
For GKEv2 we need to make a cloud credential that works with GCP. This should not introduce a node driver to GCP.

**Comment by prabalsharma** [comment]
I was able to create CC on 2.5-head-7426ba83e using UI and checked the created secret using kubectl

**Comment by prabalsharma** [comment]
was tested on master-head https://zube.io/rancher/rancher/c/37660

**Comment by prabalsharma** [comment]
invalid json bug: https://github.com/rancher/rancher/issues/32020

**Comment by prabalsharma** [comment]
2.5-head-7426ba83e: deletion of CC from UI, cleans the secret as well.
