### ISSUE TITLE
Add helm notation to CRD generation in eks-operator

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#30997]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. generate crd by running `go generate` in eks-operator

**Result:**
The new CRD is missing the annotation `"helm.sh/resource-policy": keep`. This annotation tells helm not to delete the crd on a helm delete. The CRD in system-charts includes this annotation because deleting the CRD could causes underlying EKSClusterConfigs to delete and other errors to be encountered. Without the annotation this would happen if the user deletes the app or if rancher upgrade the app (which it does automatically when newer versions are available). The typical workflow for updating the crd in the chart is to run go generate in eks-operator and then copy over the produced CRD. Right now, this would lead to the omission of the annotation. In the future if the process of updating the crd in the chart is ever automated we could instead add the annotation after generation since there's no reason to assume outside of rancher it would be desired.

**Other details that may be helpful:**
Should be able to add code to `pkg/codegen/main.go` to add annotation to crd on `go generate`.

**Comment by cbron** [comment]
This can move forward now.

**Comment by thedadams** [comment]
Closing because there is nothing for QA to test here. These changes were to ensure that code generation was adding things to the CRD that we have already put there manually.
