### ISSUE TITLE
EKS provisioning errors with: [resourceTags] cannot be nil

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#31007]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
From Rancher, launch an EKS cluster
Keep default values in fields
Create cluster

**Result:**
![Screen Shot 2021-01-27 at 10 50 36 AM](https://user-images.githubusercontent.com/57409052/106035565-82728600-6091-11eb-804a-bb265e757e68.png)

Node group config:
```
desiredSize: 2
diskSize: 20
ec2SshKey: ""
gpu: false
instanceType: "t3.medium"
labels: {}
launchTemplate: null
maxSize: 2
minSize: 2
nodegroupName: "aaron-ng2"
requestSpotInstances: false
resourceTags: {}
subnets: []
tags: {}
type: "nodeGroup"
userData: ""
version: "1.18"
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5-2ec02e7-head`
- Installation option (single install/HA): single

**Comment by aaronRancher** [comment]
Node group config from Rancher `v2.5.5`
```
desiredSize: 2
diskSize: 20
ec2SshKey: ""
gpu: false
instanceType: "t3.medium"
labels: {}
maxSize: 2
minSize: 2
nodegroupName: "aaron-ng1"
subnets: []
tags: {}
type: "nodeGroup"
version: "1.18"
```
The `resourceTags` field is not seen.

**Comment by sowmyav27** [comment]
**On 2.5-head latest - commit id: `24c32a3`**

- Create a hosted EKS. Give in values for Resource Tags for the `resourceTags: {test1: "values1"}`
- API request contains `resourceTags: {test1: "values1"}`
- But View in API of the cluster, has `resourceTags": null,`

**Comment by aaronRancher** [comment]
On cluster create, the UI removes the resource tag.
![af4b83ca36536de7163d52d74fc77de2](https://user-images.githubusercontent.com/57409052/106047515-f1a3a680-60a0-11eb-9310-0f18c0f294cd.gif)

In API view, `resourceTags` are null:
```
nodeGroups": [
{
"desiredSize": 2,
"diskSize": 20,
"ec2SshKey": "",
"gpu": false,
"imageId": null,
"instanceType": "t3.medium",
"labels": { },
"launchTemplate": null,
"maxSize": 2,
"minSize": 2,
"nodegroupName": "aaron-ng5",
"requestSpotInstances": null,
"resourceTags": null,
"spotInstanceTypes": null,
"subnets": [ ],
```

**Comment by westlywright** [comment]
> **On 2.5-head latest - commit id: `24c32a3`**
> 
> * Create a hosted EKS. Give in values for Resource Tags for the `resourceTags: {test1: "values1"}`
> * API request contains `resourceTags: {test1: "values1"}`
> * But View in API of the cluster, has `resourceTags": null,`
> * Cluster is seen stuck in Provisioning with `Field [resourceTags] cannot be nil for nodegroup [sow] in non-nil cluster [c-qtkhx]` error

Because the API Request is sent with the resourceTags object I do not believe this is a UI issue, and more than likely a backend issue. @thedadams Can you take a look?

**Comment by westlywright** [comment]
@aaronRancher i suspect the tags are removed in the UI because the api responds with the new cluster object which causes the ui store to update the state of the cluster object and subsequently the ui re-renders (and removes the now null resource tags) before we've had a chance to transition away from this route.

**Comment by thedadams** [comment]
@aaronRancher This sounds like a problem I was running into in testing related to `rancher-operator`. These changes require `rancher-operator` to be at version 0.3.1-rc1 on the cluster for this to work.

**Comment by cbron** [comment]
I think we worked past error, it was because rancher-operator isn't auto-deploying now. Although @thedadams we do need to fix the tag, rc got duped: `rancher-operator-0.1.3-rc100-rc00.tgz`

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `e3128c9 `**

- Upgraded rancher-operator to `rancher-operator:0.1.3-rc100-rc00` manually. 
- Able to deploy an EKS cluster now
