### ISSUE TITLE
[Logging v2] - Chart version 3.9.000-rc01 fails to install with invalid metadata error

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#31006]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install Rancher 2.5-head 
- Deploy RKE cluster with PSP enabled
- Navigate to dashboard and install Logging chart version 3.9.000-rc01

**Result:**

```

---------------------------------------------------------------------
--
Wed, Jan 27 2021 11:13:02 am | SUCCESS: helm upgrade --install=true --namespace=cattle-logging-system --timeout=10m0s --values=/home/shell/helm/values-rancher-logging-crd-3.9.000-rc01.yaml --version=3.9.000-rc01 --wait=true rancher-logging-crd /home/shell/helm/rancher-logging-crd-3.9.000-rc01.tgz
Wed, Jan 27 2021 11:13:02 am | ---------------------------------------------------------------------
Wed, Jan 27 2021 11:13:02 am | helm upgrade --install=true --namespace=cattle-logging-system --timeout=10m0s --values=/home/shell/helm/values-rancher-logging-3.9.000-rc01.yaml --version=3.9.000-rc01 --wait=true rancher-logging /home/shell/helm/rancher-logging-3.9.000-rc01.tgz
Wed, Jan 27 2021 11:13:02 am | Release "rancher-logging" does not exist. Installing it now.
Wed, Jan 27 2021 11:13:03 am | creating 16 resource(s)
Wed, Jan 27 2021 11:13:03 am | Error: PodSecurityPolicy.extensions "psp.logging-operator" is invalid: metadata.annotations[seccomp.security.alpha.kubernetes.io/defaultProfileName]: Invalid value: "docker/default,runtime/default": must be a valid seccomp profile
```

**Environment information**
- Rancher version: `v2.5-head (01/27/2021)` _2ec02e7_
- Installation option: HA RKE

Reference: https://github.com/rancher/rancher/issues/30771

**Comment by nickgerace** [comment]
**Working theory**: We are reaching a conflict between #30771's PR and the upstream. When upstream's `rbac.psp.enabled` is `true`, it will interfere.

values.yaml | description | default value 
-- | -- | --
`rbac.enabled` | Create rbac service account and roles  | `true`                        
`rbac.psp.enabled` | Must be used with `rbac.enabled` true. If true, creates & uses RBAC resources required in the cluster with [Pod Security Policies](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) enabled. | `false`

**Comment by izaac** [comment]
Rancher version `v2.5-head (01/30/2021)` _2ae4cf1_
Rancher version `master-head (01/30/2021)` _59ebdc2_
Logging chart version `3.9.000-rc02`

Fluentd output
Cluster types
- RKE EC2 with PSP 
- RKE EC2 no PSP 
- EKS
- k3s


Validated install is now fixed.
