### ISSUE TITLE
[Cluster Manager UI] payload include both old and new answers after app upgrade

### ISSUE THREAD

**Issue by c3y1huang** [rancher/rancher#31001]
**What kind of request is this (question/bug/enhancement/feature request): bug**

In Longhorn we observed after upgrade from v1.0.2 to v1.1.0, the payload passed from rancher UI `Edit as a Form` includes both new and old `answers` keys and values. This confuses helm in rancher and caused panic.
```
Wait helm template failed.
2020/12/31 17:51:03 Warning: Merging destination map for chart 'longhorn'. Overwriting table item 'ui', with non table value: longhornio/longhorn-ui
```

**Steps to reproduce (least amount of steps as possible):**
1. Deploy Longhorn via Rancher UI - Cluster Manager.
2. Set version to 1.0.2.
3. Set `Use Default Image` to False and click `Launch`.
4. Upgrade to version 1.1.0 with no change in existing parameters and will see errors on UI.

**Result:**
![Screenshot-2021-01-27-09:32:46](https://user-images.githubusercontent.com/22583541/105929478-a7133180-6082-11eb-9aca-51fe2bbb4b3e.png)

**Other details that may be helpful:**
https://github.com/longhorn/longhorn/issues/2121#issuecomment-767939129

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM with 4 CPU/8 memory
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Dec 18 12:21:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Thu Dec 10 13:23:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.4
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Comment by pulberg** [comment]
any update here?

**Comment by pulberg** [comment]
any update here?

**Comment by pulberg** [comment]
I couldn't have my environment broken any longer, so I removed the failed Longhorn installation and re-installed with v1.1.2.  As a customer this is very disappointing and very frustrating.
