### ISSUE TITLE
Dangerous DNS behaviour

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#3100]
v0.50.0

I have SERVICE1 in STACKA. I also have SERVICE1 in STACKB.

Within STACKB nslookup SERVICE1 is resolving to the service in STACKA. 

The containers all have network=host and the container network enabled. Basically the stacks are not being respected. Is this expected behaviour?

**Comment by bacheson** [comment]
Ok this is even more interesting. I've enabled managed networking on all services. This re-produces another baffling situation:

StackA
-service1
-service2
-service3

StackB
-service2

in StackA
  1) nslookup service2 -> StackA:service2
  2) stop service2
  3) nslookup service2 -> StackB:service2

This is extremely dangerous behaviour.

**Comment by deniseschannon** [comment]
This is a known issue and duplicate of https://github.com/rancher/rancher/issues/2873. I will close in favor of the other one.

**Comment by liubaishui** [comment]
I have the same error.

**Comment by Rucknar** [comment]
+1
