### ISSUE TITLE
On Rhel8.2 hitting lstio init fail error during deploying a bookservice in lstio,

### ISSUE THREAD

**Issue by sadiapoddar** [rancher/rancher#31012]
This issue was encountered on both lstio v1 and v2 of rancher v2.5.5 and cluster node's os Rhel 8.2,4.18.0-193.el8.x86_64

Steps to repro

1. Deploy Rancher
2. Create a cluster (at least 3 worker nodes, of size t3.medium)
3. From the Cluster page, Navigate to Tools > Istio
4. Ensure the Ingress Gateway component is selected and install Istio & Monitoring
5. Create a project / ns
6. From the namespace menu, enable Istio auto-injection
7. Deploy the Demo bookservice application into the created project/ns by `Import yaml` (see below)
8. Import the demo bookservice yaml into the created namespace (see below)
Notice that the lstio pod creation failed during the init process, 

lstio pod log shows the following error,
---------------- 
iptables-restore --noflush /tmp/iptables-rules-1611603064086011080.txt952732650
iptables-restore v1.6.1: iptables-restore: unable to initialize table 'nat'
Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
iptables-save
panic: exit status 2

**Comment by cbron** [comment]
@sadiapoddar RHEL 8 has seLinux on by default, was it disabled before this test ? If not then this should really be labelled istio seLinux support. Its possible installing with the cni plugin will fix this. It would actually be nice to know if using istio+cni-plugin works on seLinux.

**Comment by sadiapoddar** [comment]
@cbron 

-Yes the selLinux was enabled
-No we didn't disable it before testing

I couldn't find the "istio seLinux support" label though to make it. Please feel free to pick the correct label

**Comment by sadiapoddar** [comment]
Hi @cbron,
We install istio chart by enabling selLinux and installing/enabling cni plugin
The book service deployment was successful in both on v1 and v2 charts.

**Comment by sadiapoddar** [comment]
Closing the bug, since it worked by enabling CNI plugin on SELinux enabled platform.
