### ISSUE TITLE
AKS Provisioner: Handler

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#31016]
Similar to https://github.com/rancher/rancher/issues/31011, we need another controller that manages the translation from AKS to Rancher. This would replicate what's in place for EKS

PR rancher/rancher#31333

**Comment by gaktive** [comment]
PR? https://github.com/rancher/rancher/pull/31333

**Comment by mjura** [comment]
I have opened PR with AKS provisioner handler
https://github.com/rancher/rancher/pull/31333

**Comment by prabalsharma** [comment]
Tested via test plan
