### ISSUE TITLE
AKS Provisioner: Cloud Credentials

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#31014]
We need to look at using cloud credentials with the AKS Provisioner.
https://github.com/rancher/rancher/issues/31014

Fix: https://github.com/rancher/rancher/pull/32288

**Comment by cbron** [comment]
This one is just the integration to the cluster object, as the azure cloud credentials themselves already exist.

**Comment by gaktive** [comment]
Need to add the TenantID still along with some other bits of code.

**Comment by mjura** [comment]
After discussion we agreed to not add tenantId to Cloud Credentials, because it might brake rancher machine for RKE.

**Comment by cbron** [comment]
Reopening, we are looking at adding again.

**Comment by cbron** [comment]
QA cases to test: 
* that it doesn't break existing setups without a tenant
* fresh clusters with and without a tenant
* not sure this is valid use case, but see if you can convert existing cloud-credential cluster to one with a tenant

**Comment by cbron** [comment]
We also need to test plain old azure node driver with and without tenant, and upgrading that from 2.5

**Comment by prabalsharma** [comment]
> QA cases to test:
> 
> * that it doesn't break existing setups without a tenant

Does not, as AKSv1 don't use stored CC

> * fresh clusters with and without a tenant

This is not possible, as cc created without tenantID does not show up in list of CCs while provisioning AKSv2 cluster

> * not sure this is valid use case, but see if you can convert existing cloud-credential cluster to one with a tenant

No possible. V1 cluster does not use stored CC
