### ISSUE TITLE
convoy-gluster volume mount is read-only

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#3101]
My convoy-gluster template seems to have become read-only all of a sudden.

On one of the hosts:

```
[rancher@ip-xx-xxx-xxx-xxx ~]$ docker volume ls
DRIVER              VOLUME NAME
local               b20c7f57a864ec3ca68a27113537f8609ec7ce1f1304c7792c1845645a431421
local               75504daa44af55642bc56abb94c4322f3406bdc95368d55e2e50090cffde3b74
local               56bad73d13538f3f7e727383b3f3c31c19c98808c2ab6b316c5f43441b37912d
convoy-gluster      src
```

Screenshot of the volume config of the container on the same host:

![screen shot 2015-12-21 at 12 30 20 pm](https://cloud.githubusercontent.com/assets/12628715/11936865/a597e84e-a7de-11e5-9b0f-ae18d1a4a0f9.png)

Trying to `touch` a file on the mount path in the container:

```
deploy@ip-xx-xxx-xxx-xxx:/var/www/apps/jewlr4$ touch test.txt
touch: cannot touch ‘test.txt’: Read-only file system
```

To reproduce this issue, I killed 2/3 of my hosts, and Amazon autoscaled back up to 3, then Rancher reinitialized gluster on them.

**Comment by cloudnautique** [comment]
I believe this is the behavior of GlusterFS. It will go into readonly if the majority of replicas are unavailable. 

Also, this template does not automatically handle failure recovery. It is left to the user to run GlusterFS commands to bring the volume back online.

**Comment by schuylr** [comment]
Thanks! By majority of replicas, is that  > 50%? Any idea where GlusterFS determines this?
