### ISSUE TITLE
AKS Provisioner: Sync

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#31015]
Similar to https://github.com/rancher/rancher/issues/31010, we need to work on a controller that manages syncing data between AKS and Rancher

**Comment by gaktive** [comment]
EKS did something like this (I think): https://github.com/rancher/rancher/issues/28422

**Comment by cbron** [comment]
PR: https://github.com/rancher/rancher/pull/31333

**Comment by prabalsharma** [comment]
tested on rc4 via api
