### ISSUE TITLE
Rancher-catalog service should not blow up on a bad entry

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#3102]
If an entry is missing a rancher-compose file, or the service is unable to process the yaml, that entry should be skipped and processing should continue. The message should be logged to the console. 

An example of the current behavior can be seen with an entry that doesn't contain a rancher-compose.yml file.

**Comment by prachidamle** [comment]
Fixes are in PR: https://github.com/rancher/rancher-catalog-service/pull/39

**Comment by deniseschannon** [comment]
Verified v0.63.0-rc1

Tested with a missing rancher-compose.yml.

Rancher-catalog-service doesn't blow up and in rancher/server logs the error of the missing file.
