### ISSUE TITLE
EKS v2 cluster fails to come up when using a Rancher Managed Launch Template

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31029]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a hosted EKS cluster.
- Give in the following details for the nodegroups/Launch Template.
- Cluster Options and Networking -- Default values.
- Select Logging Types: Audit,API and Authenticator

<img width="1113" alt="Screen Shot 2021-01-28 at 7 43 05 AM" src="https://user-images.githubusercontent.com/26032343/106162271-c7072b80-613c-11eb-8b9d-620840c6875e.png">

- The Node group creation has failed in EKS
<img width="1325" alt="Screen Shot 2021-01-28 at 7 45 57 AM" src="https://user-images.githubusercontent.com/26032343/106162370-e00fdc80-613c-11eb-8536-1c6b2e08e61c.png">

- Error seen in Rancher is: `Waiting for API to be available; ResourceInUseException: Nodegroup cannot be updated as it is currently not in Active State { RespMetadata: { StatusCode: 409, RequestID: "9fccff8d-ced7-453b-80ae-bd9cdc3a1d87" }, ClusterName: "eks-tc1", Message_: "Nodegroup cannot be updated as it is currently not in Active State", NodegroupName: "sowmya-node" }`

**Expected Result:**
Cluster should come up Successfully.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `e3128c9`
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted EKS
- Kubernetes version (use `kubectl version`):

```
Any
```

**Comment by thedadams** [comment]
I believe the problem may be that the custom AMI you are using has not been setup correctly. It needs to be configured per the documentation: https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/

**Comment by sowmyav27** [comment]
Closing this one out as the helper text on the UI for a "Custom AMI" is being tracked here - https://github.com/rancher/rancher/issues/31032
