### ISSUE TITLE
[EKSv2] Add help text for custom AMI box

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#31032]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

Using custom AMIs with EKS requires some detailed configuration for the AMI. A help text with a link to the AWS documentation would be helpful for the user.

The documentation link is https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id `2ae4cf11` and master-head commit id: `59ebdc`**

- Create a hosted EKS cluster --> Managed Node group section has this text
<img width="1382" alt="Screen Shot 2021-02-01 at 12 45 07 PM" src="https://user-images.githubusercontent.com/26032343/106516284-ab2cbe00-648b-11eb-8ea0-87ba6b2a57e5.png">

- Opens to [this](https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/) page
