### ISSUE TITLE
Catalog configuration options: Type int allows to type "e", but restricts other letters.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3104]
Version v0.50.2

Steps to Reproduce:
1. Open Apache Zookeeper from Catalog
2. Try to change number of nodes to something else. Note: This is type `int`

Result: I am able to type `-`, `.` and `e` in the textbox, but only numbers should be allowed.

Expected Result: Since a number is expected, we should restrict all invalid keys.

Additional error: When saving `e`, which is obviously invalid, it says "Number of Nodes: is required", but it really should indicate that the number is invalid.

**Comment by vincent99** [comment]
This is a browser "feature".. `e` is valid because it means "times 10 to the".  `1.234e3` => `1234`
