### ISSUE TITLE
Istio dashboard - kiali and jaeger should not be active after disabling in v2 charts

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#31046]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Istio chart version: rancher-istio:1.7.601-rc02

1. Spin up rancher 2.5-head [v2.5-24c32a358229e3027a72ce619541e09e46a9424b-head]
2. Create a cluster
3. Enable monitoring and istio by enabling kiali/jaeger 
4. Uninstall istio and re-install it by disabling kiali and jaeger
5. Once the istio is installed succefully, we still see Kiali and jaeger active eventhough disabled from step4.
This happens if the same version of istio is uninstalled and re-installed again. If we install a new version of istio rather than what was used from step3 issue is not seen.

**Result:**
Istio shouldn't have kiali and jaeger active if they are disabled while installing

**Other details that may be helpful:**
After uninstalling istio:
<img width="1419" alt="Screen Shot 2021-01-28 at 2 58 05 PM" src="https://user-images.githubusercontent.com/38144301/106209132-58948e80-6179-11eb-92fb-541f8aeeb9d9.png">

**Re-installing istio:**
<img width="1620" alt="Screen Shot 2021-01-28 at 2 55 53 PM" src="https://user-images.githubusercontent.com/38144301/106209193-72ce6c80-6179-11eb-98bd-ad938d9e5689.png">
<img width="1114" alt="Screen Shot 2021-01-28 at 2 38 40 PM" src="https://user-images.githubusercontent.com/38144301/106209245-87126980-6179-11eb-8118-c0f69855cee8.png">
<img width="1267" alt="Screen Shot 2021-01-28 at 3 01 43 PM" src="https://user-images.githubusercontent.com/38144301/106209370-c04ad980-6179-11eb-892b-ac85f3236f1e.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): Single

Rancher | v2.5-24c32a358229e3027a72ce619541e09e46a9424b-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

**Comment by cbron** [comment]
@brendarearden can you see if this is API or UI issue

**Comment by brendarearden** [comment]
This does not appear to be a UI issue. The kiali and jaeger services are sticking around after uninstalling istio, so when you install istio again, those services already exist regardless of if you enabled them or not. This is what is causing the urls to be active since the UI is checking for those services. A solution is to ensure uninstalling the istio chart also removes the dependencies that it installed with it.

**Comment by brendarearden** [comment]
So after looking into this a bit more, this is occurring if you uninstall the rancher-kiali-server-crd prior to uninstalling the rancher-istio installation. If you select both of them to delete at the same time, since the crd chart is smaller, it ends up getting removed first resulting in rancher-istio not having the definitions it needs to finish deleting. To resolve this issue, ensure you are always removing rancher-istio PRIOR to deleting the rancher-kiali-server-crd. The resolution for this issue will be to add documentation to the chart and rancher docs.

**Comment by aaronRancher** [comment]
Reproduced this issue with Rancher server `rancher\rancher:v2.5-head` `version 03b8153`

Steps:
Create a cluster on Rancher `v2.5-head`
Install Monitoring
Install Istio. Enable Kiali and Jaeger
![Screen Shot 2021-02-18 at 11 53 47 AM](https://user-images.githubusercontent.com/57409052/108413231-f9f68980-71e7-11eb-9054-87252369fc4a.png)
Observe Kiali and Jaeger in Istio Overview
Uninstall `rancher-istio` and `rancher-kiali-server-crd` at the same time
Reinstall Istio without Kiali and Jaeger enabled
![Screen Shot 2021-02-18 at 12 19 18 PM](https://user-images.githubusercontent.com/57409052/108413325-1e526600-71e8-11eb-948c-05d4930764e9.png)

Result:
Kiali and Jaeger are still active in Istio overview:
![Screen Shot 2021-02-18 at 12 47 43 PM](https://user-images.githubusercontent.com/57409052/108413370-2c07eb80-71e8-11eb-92eb-927f1d773813.png)

Other information:
Noticed an error when uninstalling `rancher-istio` and `rancher-kiali-server-crd` at the same time.
![image](https://user-images.githubusercontent.com/57409052/108413738-9de03500-71e8-11eb-9be1-98c5b7571791.png)

**Comment by aaronRancher** [comment]
Encountered this issue using the following steps:
Create a cluster on Rancher `v2.5-head`
Install Monitoring
Install Istio. Enable Kiali and Jaeger
Observe Kiali and Jaeger in Istio Overview
Uninstall `rancher-istio` FIRST
Uninstall `rancher-kiali-server-crd`
No error is seen when uninstalling in this order
Reinstall Istio without Kiali and Jaeger enabled

Result:
Kiali and Jaeger are still active in Istio overview.
![Screen Shot 2021-02-18 at 1 21 22 PM](https://user-images.githubusercontent.com/57409052/108416647-3af09d00-71ec-11eb-8618-3e9fd3182174.png)

**Comment by brendarearden** [comment]
@aaronRancher did you see any error messages from helm in the terminal when you uninstalled rancher-istio?

**Comment by brendarearden** [comment]
@aaronRancher did you see any error messages from helm in the terminal when you uninstalled rancher-istio?

**Comment by aaronRancher** [comment]
When uninstalling rancher-istio first, I did not see any errors.

**Comment by aaronRancher** [comment]
Was able to see kiali and jaeger inactive by using the following steps:
Create a cluster on Rancher v2.5-head
Install Monitoring
Install Istio. Enable Kiali and Jaeger
Observe Kiali and Jaeger in Istio Overview
Uninstall rancher-istio FIRST
Wait for all services to be deleted.
Uninstall rancher-kiali-server-crd
No error is seen when uninstalling in this order
Reinstall Istio without Kiali and Jaeger enabled

Result:
Kiali and Jaeger are unavailable.
![Screen Shot 2021-02-18 at 2 24 42 PM](https://user-images.githubusercontent.com/57409052/108423927-ba369e80-71f5-11eb-86a4-9c14168bfdcd.png)

Additional details:
I had uninstalled rancher-kiali-server-crd right after I saw a success in helm uninstall of rancher-istio. I should have waited a little longer for all the services to delete. In our logs, we start the deletion of kiali and jaeger services, but do not notify when they are deleted.
![Screen Shot 2021-02-18 at 2 27 12 PM](https://user-images.githubusercontent.com/57409052/108424008-d2a6b900-71f5-11eb-8fbc-0cb50df5280d.png)

**Comment by cbron** [comment]
So fix was to wait between deleting main chart and CRD chart ?

**Comment by aaronRancher** [comment]
That is what worked for me.
