### ISSUE TITLE
[forwardport] Cisco ACI (noiro) images exist in rancher-images.txt release artifact

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31057]
forwardport: rancher/rancher#30840
PRs: https://github.com/rancher/rancher/pull/30884, https://github.com/rancher/rke/pull/2414, https://github.com/rancher/rke/pull/2416

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by deniseschannon** [comment]
Checked on v2.6.0-rc1 and found no noiro entries in rancher-images.txt

https://github.com/rancher/rancher/releases/tag/v2.6.0-rc1
