### ISSUE TITLE
[UI] Refer to docs for Windows Server versioning

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#31055]
Windows Server 1903 SAC has reached EOM. The current wording suggests that all Windows Server versions at and above 1809 are valid, when that is not the case. In fact, Windows Server SAC releases reach EOM after ~1 year and release about ~6 months. Referring to the docs would provide one source of truth that's easier to maintain and would provide consistent messaging (note: the docs should be updated as well to reflect 1903 SAC EOM, but that is a separate issue).

**Comment by sowmyav27** [comment]
Reopening for a fix in 2.5.

**Comment by nickgerace** [comment]
I believe https://github.com/rancher/ui/pull/4406 fixed the issue. Was there a problem?

**Comment by nickgerace** [comment]
@sowmyav27 - I think I may have been wrong actually. I was about to open a backport PR, but I remember @westlywright's note about `2.5-fixes` here: https://github.com/rancher/ui/pull/4406#issuecomment-770975522
I believe the issue should be good to go back into "To Test"

**Comment by nickgerace** [comment]
Backported commit (cherry-picked): https://github.com/rancher/ui/commit/593ce0912d15dbc5dcbf5edf5fea07e972ec6710

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `4e48b8a` and on master-head - commit id: `4891e2e4`**

- Deploy a custom windows cluster.
- Select Windows for registration command on the UI
- UI shows

<img width="1398" alt="Screen Shot 2021-03-15 at 9 23 19 AM" src="https://user-images.githubusercontent.com/26032343/111186412-3b245400-8570-11eb-89f8-68e6ab924d45.png">
