### ISSUE TITLE
Rancherd server doesn't know the etcd node address to run health checks

### ISSUE THREAD

**Issue by cortopy** [rancher/rancher#31069]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Configure rancherd local rke2 cluster to listen on a private network. My `/etc/rancher/rke2/config.yaml` file is like this:

```
bind-address: 192.168.0.2
advertise-address: 192.168.0.2
```

2. Start/Restart server

**Result:**

Everything is working fine. However, when running `journalctl -eu rancherd-server -f` it gets to a point where log entries like this are non-stop

```
Feb 01 16:38:04 my-server rancherd[10321]: time="2021-02-01T16:38:04Z" level=info msg="Failed to test data store connection: this server is a not a member of the etcd cluster. Found [my-server-13ebc21f=https://192.168.0.2:2380], expect: my-server-13ebc21f=89.130.158.12"
```

where `89.130.158.12` (not my real IP) is the external IP of the node.

**Other details that may be helpful:**

It seems as if the checks that the rancherd server does to know if etcd is up do not include the actual IP addresses of the etcd nodes.

I noticed this when upgrading my rancher cluster with rancherd

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.5
- Installation option (single install/HA): rancherd single node

**Comment by ftrinciante** [comment]
Any resolution to this error?
