### ISSUE TITLE
Launch template values persist when switched between different Launch templates in EKS v2

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31064]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Pre requiste** 
- Have a few Launch templates with different values for instance Type/AMI/resource tags created in a region

**Steps:**

- Deploy an EKS v2 hosted cluster.
- Give in a credential. --> Nodegroups section, Click Launch template dropdown, select LT1
- The details of LT1 will be populated
- From dropdown Select LT2 --> Details of this gets populated. Switch back to LT1. Details of LT1 are not populated in the UI. Details of LT2 remain on the UI

**Expected Result:**
Values of previously selected Launch Templates should not persist

**Other details that may be helpful:**

- Switch a couple of time between different Launch Templates (LT)s in the dropdown to see the issue
- Only way to get out of this is do not select any Launch template in the dropdown, clears everything on the UI.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `2ae4cf117ac9`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted EKS
- Kubernetes version (use `kubectl version`):

```
1.18(Any)
```

**Comment by aaronRancher** [comment]
The bug fix is verified with `rancher\rancher:master-head` `version 990c1ad` and `rancher\rancher:v2.5-head` `version 8b65a6a`

Steps:
- Deploy an EKS v2 hosted cluster.
- Give in a credential. --> Nodegroups section, Click Launch template dropdown, select LT1
- The details of LT1 will be populated
- From dropdown Select LT2 --> Details of this gets populated. Switch back to LT1. Details of LT1 are not populated in the UI. Details of LT2 remain on the UI

Result:
Launch template fields update on template ID change:
![213c20ca8f966b911da48849417cdf55](https://user-images.githubusercontent.com/57409052/107715737-290f7700-6c8d-11eb-83c5-a61504426876.gif)
