### ISSUE TITLE
Includes k3s upgrade images when uses image export script in dev, master, or non semver tag that is equal to kd.RancherVersionDev

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#31061]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Use export script with TAG set to dev, master, or a value equal to kd.RancherVersionDev.

**Result:**
Using export script with TAG set to dev, master, or a value equal to kd.RancherVersionDev will result in no k3s
upgrade or related images being added to the images text.

**Other details that may be helpful:**
Nothing should be observably different when rancher-images texts are produced for tagged releases. QA can verify that an rc tag has a rancher-images text that includes k3s-upgrade images for compatible k3s versions in https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.5/data/data.json. Each compatible version will cause some supporting images to be added as well. Can confirm by making sure klipper-helm images are add to images-text.

**Comment by cbron** [comment]
Aiming for 2.5.6 on this one as I am assuming it will merge before then, but it can slip to 2.5.7 without a problem.

**Comment by jiaqiluo** [comment]
This is validated on rancher:`v2.5.6-rc4`

Steps:
- get the compatible k3s versions from the [here](https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.5/data/data.json)
- get the `rancher-images.txt` from rancher:`v2.5.6-rc4`'s [release page](https://github.com/rancher/rancher/releases/tag/v2.5.6-rc4)

Results:
- there are four compatible k3s versions for rancher:v2.5.6
```
v1.17.17+k3s1
v1.18.15+k3s1
v1.19.7+k3s1
v1.20.2+k3s1
```
- the `klipper-helm` images are in the `rancher-images.txt` file 
```
rancher/klipper-helm:v0.2.3
rancher/klipper-helm:v0.2.7
rancher/klipper-helm:v0.3.0
rancher/klipper-helm:v0.4.3
```
- the `k3s-upgrade` images are in the `rancher-images.txt` file  
```
rancher/k3s-upgrade:v1.17.17-k3s1
rancher/k3s-upgrade:v1.18.15-k3s1
rancher/k3s-upgrade:v1.19.7-k3s1
rancher/k3s-upgrade:v1.20.2-k3s1
```

**Comment by jiaqiluo** [comment]
Since we will not get RCs from the master branch soon, I created a forward port issue for tracking it on the master branch https://github.com/rancher/rancher/issues/31121

**Comment by cbron** [comment]
Re-opening because this was reverted as secondary parallel fix was implemented.

**Comment by rmweir** [comment]
Should just test that rancher-images.txt looks how it normally does on release.

**Comment by jiaqiluo** [comment]
This is re-validated on v2.5.6-rc6 
1. All k3s-related images are in the rancher-images.txt file
2. All regular tests for air-gap installation are passed
