### ISSUE TITLE
Add nodegroup during an edit EKS v2 cluster, does not let user select a Launch template

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31063]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy an EKS v2 cluster (with Rancher managed Launch Template or Custom AWS _ Rancher managed Launch Templates)
- After the cluster comes up Active, --> Edit cluster
- Add a new node group
- The Launch Template dropdown is disabled.

<img width="1238" alt="Screen Shot 2021-01-29 at 2 43 46 PM" src="https://user-images.githubusercontent.com/26032343/106335319-67df0f00-6241-11eb-9354-cbeb47daa0c1.png">

**Expected Result:**
Launch Template dropdown should be enabled.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `2ae4cf117`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS v2 hosted
- Kubernetes version (use `kubectl version`):

```
1.18 (Any)
```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 55384b8` and `rancher\rancher:v2.5-head` `version 6adfcd6` 

On EKS cluster edit, user is able to select a launch template while creating a new node group.
![Screen Shot 2021-02-03 at 1 06 20 PM](https://user-images.githubusercontent.com/57409052/106802872-c54bd500-6620-11eb-8316-8be215873dd0.png)
