### ISSUE TITLE
Ensure eks-operator doesn't auto-upgrade without rancher-upgrade

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#31062]
Using this framework: https://github.com/rancher/rancher/issues/30934

Ensure that eks-operator does not auto-upgrade for <2.5.6 Rancher clusters.

**Comment by thedadams** [comment]
Some ideas to test this:
## Ensure Rancher 2.5.6 has the correct version of eks-operator:
1. Deploy Rancher 2.5.6 RC
2. Create an EKS cluster in Rancher
3. Go to the System project in the local cluster: the version of eks-operator should be 1.0.6-rcx

## Ensure Rancher 2.5.5. does not have the latest version of eks-operator:
1. Deploy Rancher 2.5.5 (or older)
2. Create an EKS cluster in Rancher
3. Go to the System project in the local cluster: the version of eks-operator should be 1.0.5

**Comment by aaronRancher** [comment]
Validated the above scenarios.

Ensure Rancher 2.5.6 has the correct version of eks-operator:
- Deploy Rancher 2.5.6 RC (v2.5.6-rc4)
- Create an EKS cluster in Rancher
- Check the version of eks-operator in the system project of the local cluster. eks-operator is `eks-operator:v1.0.6-rc3`

Ensure Rancher 2.5.5. does not have the latest version of eks-operator:
- Deploy Rancher 2.5.5
- Create an EKS cluster in Rancher
- Check the version of eks-operator in the system project of the local cluster. eks-operator is `eks-operator:v1.0.5`
- Change the branch of the system-charts repo to "dev-v2.5"
- Edit the EKS cluster and save the changes
- Check the version of eks-operator in the system project of the local cluster. eks-operator is STILL  `eks-operator:v1.0.5`
