### ISSUE TITLE
Rancher still redirects despite "tls=external"

### ISSUE THREAD

**Issue by zchef2k** [rancher/rancher#31071]
Deployed on a freshly provisioned cluster, I cannot get externally terminated SSL traffic to rancher on account of redirects.

**What kind of request is this:**
question/possible bug

**Steps to reproduce (least amount of steps as possible):**

1. Deploy rancher on Kubernetes per instructions [here](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/).
2. Follow "tls=external" instructions [here](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/chart-options/#external-tls-termination) to terminate SSL on an upstream proxy (HAProxy, in this case) whose backends are cluster nodes on 80/tcp.
3. Test that you can reach rancher directly on the cluster on 80/tcp using the "required" headers mentioned [here(https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/chart-options/#external-tls-termination).

```
curl -H "Host:rancher.hostname.com" \
       -H "X-Forwarded-Proto:https" \
       -H "X-Forwarded-Port:443" \
       -H "X-Forwarded-For:<ip of client>" \
       -i <ip of worker node>
```

**Result:**
Either the ingress or rancher itself redirects (302) to port 443. This causes loops when coming through the upstream proxy.

**Other details that may be helpful:**

Helm command used to deploy rancher:
```
helm install rancher rancher-latest/rancher \
        --namespace cattle-system \
        --set hostname=rancher.hostname.com \
        --set tls=external`
```

Resulting ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.100.50.51","10.100.50.52","10.100.50.53"],"port":80,"protocol":"HTTP","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"rancher.hostname.com","allNodes":false}]'
    meta.helm.sh/release-name: rancher
    meta.helm.sh/release-namespace: cattle-system
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  creationTimestamp: "2021-02-01T16:48:18Z"
  generation: 1
  labels:
    app: rancher
    app.kubernetes.io/managed-by: Helm
    chart: rancher-2.5.5
    heritage: Helm
    release: rancher
  name: rancher
  namespace: cattle-system
  resourceVersion: "19410"
  selfLink: /apis/extensions/v1beta1/namespaces/cattle-system/ingresses/rancher
  uid: 174e53d6-5ab1-4d60-b56b-55a4aeafbda4
spec:
  rules:
  - host: rancher.hostname.com
    http:
      paths:
      - backend:
          serviceName: rancher
          servicePort: 80
status:
  loadBalancer:
    ingress:
    - ip: 10.100.50.51
    - ip: 10.100.50.52
    - ip: 10.100.50.53
```

**Environment information**
- Rancher version: 2.5.5
- Installation option: Single Install

**Cluster information**
- Cluster type:  Deployed using RKE
- Machine type: CentOS 7.9 VMs (4 vCPU/8G RAM) on Nutanix
- Kubernetes version: v1.17.14

**Comment by zchef2k** [comment]
The cluster's ingress needed to be configured per [this](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/chart-options/#configuring-ingress-for-external-tls-when-using-nginx-v0-25). The consequences of not setting this (302 loops, in my case) are not apparent. Perhaps additional guidance in that section would be helpful.

**Comment by Vacant0mens** [comment]
Is there a way to have Rancher only listen on only port 80 without redirecting? Is the `tls=external` option is (in theory) supposed to do that? Because it's not working for me. Even inside of the cluster, hitting the Rancher pod directly on http/80, it gets redirected to https/443.

**Comment by cdstg** [comment]
same thing is happening for me with  tls=external   and i also tried disabling  Traefik
but ist not listing on port 80 
mine also k3s

**Comment by josh383451** [comment]
> same thing is happening for me with tls=external and i also tried disabling Traefik but ist not listing on port 80 mine also k3s
> 
> Updated as per https://github.com/ninedongsu
> 
> seems that the Traefik does not allow the forwarded headers by default
> 
> https://doc.traefik.io/traefik/v2.0/routing/entrypoints/
> 
> edit k3s traefik manifest file add valuesContent.additionalArguments into /var/lib/rancher/k3s/server/manifests/traefik.yaml file. valuesContent: |- additionalArguments: - "--entryPoints.web.forwardedHeaders.insecure"
> 
> More update the file keep getting overridden I added a file /var/lib/rancher/k3s/server/manifests/traefik-config.yaml with this inside problem solved
> 
> apiVersion: helm.cattle.io/v1 kind: HelmChartConfig metadata: name: traefik namespace: kube-system spec: valuesContent: |- additionalArguments: - "--entryPoints.web.proxyProtocol.insecure" - "--entryPoints.web.forwardedHeaders.insecure"

Adding the additionalArgument to the traafik file fixed my issue.
Rancher 2.7.6
