### ISSUE TITLE
"nodegroupName cannot be an empty" Error seen while creating an EKS v2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31078]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy a hosted EKS cluster with an existing AWS launch template with v1 (This launch template has 2 versions v1 and v2)
- Wait for the cluster to come up active.
- Edit cluster --> managed Node group section, change version from 1 to 2.
- The nodegroup name changes to n/a
<img width="608" alt="Screen Shot 2021-02-01 at 1 47 03 PM" src="https://user-images.githubusercontent.com/26032343/106522468-a4ef0f80-6494-11eb-9784-26b56e72f2a8.png">

- Save changes made, error seen on UI: `nodegroupName cannot be an empty`

**Expected Result:**
The nodegroup name should not change to n/a on a version change

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `2ae4cf117`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted EKS v2
- Kubernetes version (use `kubectl version`):

```
1.18 (Any)
```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 54b3a75` and `rancher\rancher:v2.5-head` `version 8201e08`

Steps:

- Deploy a hosted EKS cluster with an existing AWS launch template with v1 (This launch template has 2 versions v1 and v2)
- Wait for the cluster to come up active.
- Edit cluster --> managed Node group section, change version from 1 to 2.

Result:
Node group name does not change. User is able to save changes and see cluster update.
![Screen Shot 2021-02-04 at 11 22 00 AM](https://user-images.githubusercontent.com/57409052/106938000-a8280c80-66db-11eb-8e53-76ab01bc7e45.png)
