### ISSUE TITLE
No warning when a use selects a launch template which specifies instance type and enables spot instance

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31077]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Create a hosted EKS cluster
- Select a custom AWS Launch template (This will have instance type set)
- Check Spot instances, select spot instance types
- Deploy the cluster
- Cluster is stuck in updating state with error: `InvalidRequestException: Cannot specify instance types in launch template and API request { RespMetadata: { StatusCode: 400, RequestID: "a1453cde-67b4-4b5f-88c0-4acad15a1acb" }, ClusterName: "sowmya-spot-custom-25", Message_: "Cannot specify instance types in launch template and API request", NodegroupName: "sow-spot-2" }`

Can we add a note/warning in the UI that when user selects an AWS launch template and Spot instances "instance template should not specify an “instance type.” "

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `2ae4cf11`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted EKS
- Kubernetes version (use `kubectl version`):

```
1.18 (Any)
```

**Comment by westlywright** [comment]
Hmm I didn't test this scenario when I made a previous fix for when a user select spot instances without a template. I'll add logic to handle this coming down from the launch template. The instance type will get set null before save and you should see the help text that that field wont be sent, same as the other scenario I mentioned.

**Comment by sowmyav27** [comment]
Verified on 2.5-head commit id: `8201e080` and master-head commit id: `b4b2322fd`

- When user selects spot instances, Instance type is disabled and a note is available on the UI
<img width="1390" alt="Screen Shot 2021-02-04 at 3 59 10 PM" src="https://user-images.githubusercontent.com/26032343/106976682-b1ca6800-670d-11eb-996f-adb4c903d222.png">
