### ISSUE TITLE
Run Run Conformance Testing for k8s 1.20

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#31082]
k8s 1.20.2-rancher2-1 is avaiable starting at rancher 2.5.6. We need to run Conformance Testing for RKE/Rancher v1.20.2-rancher2-1.

**Comment by slickwarren** [comment]
RKE PR: https://github.com/cncf/k8s-conformance/pull/1330

**Comment by slickwarren** [comment]
Rancher PR: https://github.com/cncf/k8s-conformance/pull/1332

**Comment by slickwarren** [comment]
both of the above PRs have been approved and merged
