### ISSUE TITLE
When cloning a service with portMap by providing only private port (no public port) ,  public port gets the random port assigned.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3108]
Server version - Build from master

Steps to reproduce the problem:
Try to create a service - S1 with portMap by providing only private port (no public port).
Clone this service.
Public port has the port value assigned for service S1.
Activating this service without changing the public port will result in service stuck in "Activating" state.

Expected Behavior:
On cloning this service , we should be able to present the public port as being empty to trigger random port allocation.

**Comment by vincent99** [comment]
This would be in the UI, though there's no way for me to know it was a random port.  I'm not sure I agree with fixing it though anyway, it's a complete clone and the same thing would happen if you had specified an explicit public port.  It won't necessarily fail either unless that port is taken on every host.
