### ISSUE TITLE
Validate RancherOS 1.5.7 with Docker 20.10.2

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31095]
Validate the following scenarios:
- Deploy downstream custom cluster with RancherOS 1.5.7 with Docker 20.10.2, run validation tests
- Deploy v1 charts in the downstream cluster with RancherOS 1.5.7 with Docker 20.10.2, verify P0 use case works fine
- Deploy v2 charts in the downstream cluster with RancherOS 1.5.7 with Docker 20.10.2, verify P0 use case works fine
- Deploy node driver cluster with RancherOS 1.5.7 with Docker 20.10.2, cluster comes up Active, run validation tests
- HA setup with local cluster using RancherOS 1.5.7 with Docker 20.10.2, deploy a downstream custom cluster and run validation tests (Checking the health/sanity of the HA install here)

**Comment by sadiapoddar** [comment]
Created a downstream cluster using rancher OS 1.5.7(picking an ami listed in aws) 
and don't see the node's Docker version is 20.10.2 it's still 19.3.14

<img width="868" alt="Screen Shot 2021-02-03 at 11 12 03 AM" src="https://user-images.githubusercontent.com/72409237/106796823-b826ea00-6610-11eb-855b-8b884a5192c0.png">

**Comment by sowmyav27** [comment]
Closing this as we wont be support this.
