### ISSUE TITLE
Validate Oracle Linux 8.3 with Docker 20.10.x

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31094]
Validate the following scenarios:
- Deploy downstream custom cluster with Oracle Linux 8.3 with Docker 20.10.x, run validation tests
- Deploy v1 charts in the downstream cluster with Oracle Linux 8.3 with Docker 20.10.x, verify P0 use case works fine
- Deploy v2 charts in the downstream cluster with Oracle Linux 8.3 with Docker 20.10.x, verify P0 use case works fine
- Deploy node driver cluster with Oracle Linux 8.3 with Docker 20.10.x, cluster comes up Active, run validation tests
- HA setup with local cluster using Oracle Linux 8.3 with Docker 20.10.x, deploy a downstream custom cluster and run validation tests  (Checking the health/sanity of the HA install here)

**Note:**
Latest docker version is 20.10.3

**Comment by slickwarren** [comment]
progress: 
- [x] Deploy downstream custom cluster with Oracle Linux 8.3 with Docker 20.10.2, run validation tests -- **pass**
- [x] Deploy v1 charts in the downstream cluster with Oracle Linux 8.3 with Docker 20.10.2, verify P0 use case works fine -- **all pass, except for monitoring (not all prometheus targets up, further investigation required)**
- [ ] Deploy v2 charts in the downstream cluster with Oracle Linux 8.3 with Docker 20.10.2, verify P0 use case works fine
- [x] Deploy node driver cluster with Oracle Linux 8.3 with Docker 20.10.2, cluster comes up Active, run validation tests -- **pass**
- [ ] HA setup with local cluster using Oracle Linux 8.3 with Docker 20.10.2, deploy a downstream custom cluster and run validation tests  (Checking the health/sanity of the HA install here)

**Comment by sowmyav27** [comment]
@slickwarren Can you test CIS benchmark on 2.5-head and then we can close this issue? As we have separate issues logged for monitoring ?

**Comment by slickwarren** [comment]
CIS is now passing on 2.5-head (761c805). So I will close this issue.
