### ISSUE TITLE
[rancher-logging] Missing ability to configure resource settings for fluentd statefulset

### ISSUE THREAD

**Issue by ebauman** [rancher/rancher#31099]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Steps to reproduce (least amount of steps as possible):** Attempt to configure resource limitations/requests on the helm chart prior to rolling out rancher-logging. 

**Result:** You can't. 

**Other details that may be helpful:**

Banzai Cloud Logging resource allows for configuration of resource settings as part of the FluentdSpec object.
(see https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/fluentd_types/)

This is not currently exposed in our helm chart for logging. A user may override the Loggingobjects we create to add this information, but we should manage it from the helm chart.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v.2.5.3
- Installation option (single install/HA): HA

**Comment by nickgerace** [comment]
Spoke to @izaac about testing this feature. This is merely an exposure of upstream `spec` field(s) in Logging CRs.

**Comment by izaac** [comment]
I reproduced the reported behavior with chart version `3.8.201` not able to set the resource on fluentbit and fluentd.

Chart version `3.9.000-rc4`

Edit as YAML before installing the chart and under `spec.fluentbit.resources` and `spec.fluentd.resources` 

Set the values to:

```yaml
resources:
  limits:
    cpu: 1500m
    memory: 1500M
  requests:
    cpu: 1000m
    memory: 1000M
```

The [official documentation](https://banzaicloud.com/docs/one-eye/logging-operator/operation/requirements/) use integers but I was getting type error in the latest chart so i used strings as it was expecting that value type.


After installing we can check the logging apps:

```
kubectl get loggings.logging.banzaicloud.io
NAME                  AGE
rancher-logging       4m45s
rancher-logging-rke   4m45s

kubectl get loggings.logging.banzaicloud.io rancher-logging -o yaml
```

Where these values set during install are applied to the spec. I tested setting them both and individually.

Sample applieg Logging configuration passing fluentd and fluentbit values during install. Using Edit as YAML from the chart options.

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  annotations:
    meta.helm.sh/release-name: rancher-logging
    meta.helm.sh/release-namespace: cattle-logging-system
  creationTimestamp: "2021-02-09T01:18:32Z"
  generation: 5
  labels:
    app.kubernetes.io/instance: rancher-logging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rancher-logging
    app.kubernetes.io/version: 3.9.0
    helm.sh/chart: rancher-logging-3.9.000-rc04
  managedFields:
  - apiVersion: logging.banzaicloud.io/v1beta1
    manager: manager
    operation: Update
    time: "2021-02-09T01:18:40Z"
  - apiVersion: logging.banzaicloud.io/v1beta1
    manager: Go-http-client
    operation: Update
    time: "2021-02-09T01:24:52Z"
  name: rancher-logging-rke
  resourceVersion: "10136"
  selfLink: /apis/logging.banzaicloud.io/v1beta1/loggings/rancher-logging-rke
  uid: 1c8e98de-d505-4b88-b734-17c509088f9b
spec:
  controlNamespace: cattle-logging-system
  fluentbit:
    extraVolumeMounts:
    - destination: /var/lib/rancher/logging/
      readOnly: true
      source: /var/lib/rancher/logging/
    image:
      repository: rancher/fluent-fluent-bit
      tag: 1.6.10
    inputTail:
      Parser: json
      Path: /var/lib/rancher/logging/rke
      Tag: rke
    nodeSelector:
      kubernetes.io/os: linux
    resources:
      limits:
        cpu: 1500m
        memory: 1500M
      requests:
        cpu: 1000m
        memory: 1000M
    security:
      podSecurityPolicyCreate: true
      roleBasedAccessControlCreate: true
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      value: "true"
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      value: "true"
  fluentd:
    configReloaderImage:
      repository: rancher/jimmidyson-configmap-reload
      tag: v0.4.0
    disablePvc: true
    image:
      repository: rancher/banzaicloud-fluentd
      tag: v1.11.5-alpine-9
    nodeSelector:
      kubernetes.io/os: linux
    resources:
      limits:
        cpu: 1500m
        memory: 1500M
      requests:
        cpu: 1000m
        memory: 1000M
    security:
      podSecurityPolicyCreate: true
      roleBasedAccessControlCreate: true
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
status:
  configCheckResults:
    c3054702: true
```
