### ISSUE TITLE
Validate Ubuntu 20.04 with docker 20.10.2

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31097]
Validate the following scenarios:
- Deploy downstream custom cluster with Ubuntu 20.04 with Docker 20.10.2, run validation tests
- Deploy node driver cluster with Ubuntu 20.04 with Docker 20.10.2, cluster comes up Active, run validation tests
- HA setup with local cluster using Ubuntu 20.04 with Docker 20.10.2, deploy a downstream custom cluster and run validation tests (Checking the health/sanity of the HA install here)

**Comment by Ellenqs** [comment]
Validate the following scenarios in Rancher `v2.5-head (8201e08) `:

**Steps:**
1. Create a private ami in aws which runs ubuntu20.04 with docker 20.10.2.
2. Execute the following three scenarios:
   
- On rancher single install set up, deploy downstream custom cluster (k8s v1.20.2-rancher2-1)with the created ami, run validation tests.
- On rancher single install set up, deploy node driver cluster(k8s v1.20.2-rancher2-1) with the created ami, cluster comes up Active, run validation tests.
- HA setup with local cluster using the created ami, deploy a downstream custom cluster(k8s v1.20.2-rancher2-1) and run validation tests.

**Results:**

  All tests pass in those three scenarios, failed test cases in automation pass by manual testing.

**Comment by pulberg** [comment]
Will you also be validating this for Rancher v2.4.x?
