### ISSUE TITLE
Show Site Access form when re-configuring an Authentication Provider

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#31090]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Rancher v2.5.5 instance
2. Enable PingIdentity Authentication Provider (https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/ping-federate/)
3. Under Site Access restrict access to only Authorized Users and Organization and select a group
4. Disable PingIdentity Authentication Provider
5. Attempt to re-enable PingIdentity Authentication Provider with a user not in previously select group

**Result:**

Observe error `[ERROR] SAML: User does not have access <nil>` in Rancher logs and `An unknown error occurred while attempting to login. Please contact your system administrator` in the UI.

**Other details that may be helpful:**

Suggest showing the Site Access form when re-configuring an authentication provider, so it is clear what existing restrictions are configured.

Viewing the authConfig via the API, observe that `accessMode: "required"` is set. To workaround the issue, set this to "unrestricted" via API and then re-configure authentication provider via UI.

**Environment information**
- Rancher v2.5.5
- Users encountered this with AD FS and PingIdentity

gz#14522

SURE-2727

**Comment by samjustus** [comment]
please look into SURE-3948 as well.
