### ISSUE TITLE
Unable to pass boolean values to Rancher app

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#31109]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Add the rancher catalog to a rancher install - https://releases.rancher.com/server-charts/latest
2. Deploy rancher as an app to a downstream cluster. To hide the local cluster, pass the following two answers:
variable: extraEnv[0].name   value: CATTLE_HIDE_LOCAL_CLUSTER
variable: extraEnv[0].value   value: true

**Result:**
Deployment fails with error:
```
Failed to install app rancher. Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in          #10       byte of ...|,"value":true}],"ima|..., bigger context ...|ue"},{"name":"CATTLE_HIDE_LOCAL_CLUSTER","value":true}],"image":"rancher/rancher:v2.5.2-rc4","imageP|...
```

**Other details that may be helpful:**
Related to:
https://github.com/rancher/rancher/issues/26088
https://github.com/rancher/rancher/issues/29325#issuecomment-719864450

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- v2.4.13 (deploying Rancher v2.5.5 downstream using catalog app)
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
k3s
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
AWS m5a.large (2vCPU, 8GB RAM)
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15+k3s1", GitCommit:"60f1e80dcb07a32a42688e149778778ffb00ca9a", GitTreeState:"clean", BuildDate:"2021-01-14T22:50:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
NA, using containerd

gz#14692

**Comment by kravciak** [comment]
I was able to reproduce the issue with following components:

```
k3s: v1.20.4+k3s1
helm: v3.5.3 (https://releases.rancher.com/server-charts/latest)
rancher chart: 2.5.7
```

```
helm install rancher rancher-latest/rancher --namespace cattle-system \
  --set hostname=35.239.129.47.xip.io \
  --set extraEnv[0].name=CATTLE_HIDE_LOCAL_CLUSTER \
  --set extraEnv[0].value=true
```

Deployment works fine if I remove `extraEnv` arguments

**Comment by PennyScissors** [comment]
@kravciak If you are using the Helm CLI tool directly, you can use the `--set-string` flag to make sure `true` (bool value) is set as a quoted string.

**Comment by anupama2501** [comment]
Reproduced on v2.5.8:
Helm: v3.3.4
rancher chart: v2.5.8

helm install rancher rancher-latest/rancher --namespace cattle-system \
  --set hostname=XXXX \
  --set extraEnv[0].name=CATTLE_HIDE_LOCAL_CLUSTER \
  --set extraEnv[0].value=true

Error reproduced: 
```
Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true}],"ima|..., bigger context ...|er"},{"name":"CATTLE_HIDE_LOCAL_CLUSTER","value":true}],"image":"rancher/rancher:v2.5.8","imagePullP|...\n'
```

**Comment by anupama2501** [comment]
Verified on master-head f33188d

Helm: v3.3.4
rancher chart: v2.5.9
helm install rancher rancher-latest/rancher --namespace cattle-system
--set hostname=XXXX
--set-string extraEnv[0].name=CATTLE_HIDE_LOCAL_CLUSTER
--set-string extraEnv[0].value=true

Deployment succeeded and the error is not seen.
