### ISSUE TITLE
Random port allocation is not done for sidekicks.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3110]
Server version - Build from master

Steps to reproduce the problem:
Create a service with sidekick service which has port map providing only private port.
Activate service.
Once the service is activated, sidekick containers do not have any mapped ports.

**Comment by cloudnautique** [comment]
I thought everything network wise has to be setup on the primary service?

**Comment by sangeethah** [comment]
Tested with latest build from master:

Create a service with sidekick service which has port map providing only private port.
Activate service.
Once the service is activated, sidekick containers  have ports that are exposed on host from the assigned serviceportrange for the environment.
