### ISSUE TITLE
[Forwardport] [Catalog v2] can not change the url or branch of the builtin catalog `Rancher`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31100]
forwardport: rancher/rancher#30594
prs: https://github.com/rancher/rancher/pull/31075

**Comment by sowmyav27** [comment]
Will be validated with a 2.6.0-rc, when made available

**Comment by slickwarren** [comment]
on master-head (3e89bb8): 
* changed URL and branch of rancher builtin catalog 
<img width="1259" alt="Screen Shot 2021-05-12 at 11 59 03 AM" src="https://user-images.githubusercontent.com/16691014/118030356-08050380-b31a-11eb-85ac-1c217182ecaf.png">

based on comments from https://github.com/rancher/rancher/issues/30594#issuecomment-771165152, waiting for an RC to test airgap

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by deniseschannon** [comment]
No need to validate airgap as you won't be able to change what charts are pulled in as we package them directly.
