### ISSUE TITLE
[Forwardport] Includes k3s upgrade images when uses image export script in dev, master, or non semver tag that is equal to kd.RancherVersionDev

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#31121]
Forward port of https://github.com/rancher/rancher/issues/31061

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by jiaqiluo** [comment]
@sowmyav27  Please review and close the issue

**Comment by jiaqiluo** [comment]
This is validated on rancher:`v2.6.0-rc1`

Steps:
- get the compatible k3s versions from here https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.6/data/data.json
- get the rancher-images.txt from rancher:v2.6.0-rc1's release page https://github.com/rancher/rancher/releases/tag/v2.6.0-rc1

Results:

- there are 3 compatible k3s versions for `rancher:v2.6.0-rc1`
```
v1.19.13+k3s1
v1.20.9+k3s1
v1.21.3+k3s1
```

- the `klipper-helm` images are in the rancher-images.txt file
```
rancher/klipper-helm:v0.4.3
rancher/klipper-helm:v0.6.1-build20210616
```

- the `k3s-upgrade` images are in the rancher-images.txt file
```
rancher/k3s-upgrade:v1.19.13-k3s1
rancher/k3s-upgrade:v1.20.9-k3s1
rancher/k3s-upgrade:v1.21.3-k3s1
```

**Comment by jiaqiluo** [comment]
@sowmyav27 Please review and close the issue
