### ISSUE TITLE
Fail to deploy a downstream cluster

### ISSUE THREAD

**Issue by Ellenqs** [rancher/rancher#31126]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy rancher.
- Create a downstream cluster (AWS ec2/Digital Ocean droplet)

**Result:**
The nodes are in active state, but the cluster is in the provisioning state with the following message in UI:
![Screen Shot 2021-02-03 at 2 52 10 PM](https://user-images.githubusercontent.com/75277058/106822454-08fc0a00-6634-11eb-8665-863494519be1.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version: `v2.5-head 55c6751`
- Installation option (single install/HA): Single install

- Docker version (use `docker version`):19.3.15

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/pull/31124

**Comment by Ellenqs** [comment]
Validated on Rancher `v2.5-head (8201e08)` and `master-head(fbe2c30)`.

**Steps:**

- Deploy rancher single install.
- Add a downstream cluster with ec2 provider.

**Results:**
The cluster is deployed with no error message.

**Comment by Ellenqs** [comment]
Validated on Rancher `v2.5-head (8201e08)`

**Steps:** 

- Deploy rancher single install.
- Add a downstream cluster with ec2 provider.

**Results:**
The cluster is deployed successfully with no error message.

**Comment by Ellenqs** [comment]
This is reopened waiting for PR of master-head.

**Comment by deniseschannon** [comment]
@kinarashah It doesnt look like the original PR to add env vars to the agent is in master? What issue is that associated with?

**Comment by deniseschannon** [comment]
@qian The changes related to this fix hasn't been introduced into master, so this could be closed with just the fix for 2.5.

**Comment by sowmyav27** [comment]
Waiting for a PR/fix for this issue in master-head. Using this issue to track it as per offline conv with @kinarashah . Moving to reopened.

**Comment by Ellenqs** [comment]
Validated on Rancher `master-head 007e298`.

**Steps**

- Deploy rancher single install.
- Create two downstream clusters (AWS, Digital Ocean).

**Results**
Clusters have been created successfully, all nodes are in active state with no error messages.
