### ISSUE TITLE
rke-network-plugin-deploy-job fails to deploy after k8s upgrade to 1.20.2-rancher2-1

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31129]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy clusters 1.19,1.18,1.17,1.16 on 2.5.5 rancher server
- Run pre upgrade automation checks - deploys workloads, ingress, service discovery
- Upgrade rancher to 2.5.6-rc4
- RUn post upgrade checks - this looked good.
- Upgrade k8s - 1.19 to 1.20.2-rancher1-1
- On all the clusters **except** the cluster where the upgrade was done from 1.17 to 1.20.2, other clusters are stuck in Provisioning.
- Error seen: `Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system`
- Logs of network plugin pod:

```
configmap/canal-config unchanged
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org configured
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrole.rbac.authorization.k8s.io/calico-node unchanged
clusterrole.rbac.authorization.k8s.io/flannel unchanged
clusterrolebinding.rbac.authorization.k8s.io/canal-flannel unchanged
daemonset.apps/canal configured
serviceaccount/canal unchanged
deployment.apps/calico-kube-controllers unchanged
serviceaccount/calico-kube-controllers unchanged
The ClusterRoleBinding "canal-calico" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"calico-node"}: cannot change roleRef
poddisruptionbudget.policy/calico-kube-controllers unchanged
```

**Expected Result:**
Network plugin pod gets deployed and cluster comes up Active

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.6-rc4
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom cluster rke

**Comment by sowmyav27** [comment]
**Validated on an upgrade from 2.5.5 to 2.5-head - commit id `8201e08`**

- Deploy Canal - 1.19, calico - 1.18, weave - 1.16 and flannel - 1.17 clusters. 
- Run pre upgrade checks - they look good.
- Upgrade rancher to 2.5-head
- post upgrade checks look good.
- Upgrade k8s version of all clusters to 1.20.2-rancher2-1
- weave and flannel clusters upgrade successfully.
- canal and calico clusters are stuck in provisioning `Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system`

Reopening the issue

**Comment by sowmyav27** [comment]
Reopening this issue as the issue is seen on an upgrade from 2.5.5 to 2.5-head, cluster - calico - 1.18 to 1.20 k8s versions.

**Comment by StrongMonkey** [comment]
Related issue https://github.com/projectcalico/calico/issues/4237. Quick fix is to add `preserveUnknownFields: false` to the crd until upstream fixed it.

**Comment by sowmyav27** [comment]
**testing from 2.5.5 to 2.5-head commit id: `761c805d`**

- Deploy calico 1.18 and canal 1.19 clusters
- run pre upgrade checks
- Upgrade rancher to 2.5-head
- run post upgrade checks
- update k8s version to 1.20.2-rancher2-1
- Calico cluster fails to come up with error `Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system`
- Canal clster come sup Active.

**Comment by sowmyav27** [comment]
**Validated from 2.5.5 to 2.5-head commit id: `dba332111`**

- Deploy calico 1.18 and 1.19 and canal 1.18 and 1.19 clusters
- run pre upgrade checks
- Upgrade rancher to 2.5-head
- run post upgrade checks
- update k8s version to 1.20.2-rancher2-1
- Clusters come up active. Post upgrade checks look good.

**Comment by sowmyav27** [comment]
Reopening for fix in master

**Comment by sowmyav27** [comment]
**Verified on an upgrade from 2.5.5 to master-head - commit id: `9ef8e69d2d`**

- Deployed clusters - Calico and canal - 1.18 k8s, Flannel, weave - 1.17 and 1.19 k8s versions.
- Upgrade to master, upgrade k8s versions, no errors seen.
- Clusters come up Active.
