### ISSUE TITLE
Audit Logs - Filtering by Resource Id, returns all resource types with the specified id.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3112]
Server version - Build from master

Tried to get all audit log entries for resource id -"1e14" .
We are presented with a list that has entries relating to service - "1s14" as well as environment - "1e14"

<img width="1498" alt="screen shot 2015-12-21 at 3 22 24 pm" src="https://cloud.githubusercontent.com/assets/4266958/11943934/ade41ca8-a7f6-11e5-93ae-1a03df397761.png">

**Comment by hibooboo2** [comment]
@westlywright Filter using resource type and Id That should fix this problem. Otherwise the id is the same. Since Id doesn't indicate type.

**Comment by westlywright** [comment]
@hibooboo2 its not an issue for you. the requirement changed that we will only allow users to execute a search of resourceType:resourceId together. They are independent now.

**Comment by westlywright** [comment]
@sangeethah just want to make it clear after this launches you will have to execute a search specifically selecting the search button. And resource type must be selected before you can enter a resource id.

**Comment by sangeethah** [comment]
Tested with Build from master:

resourceId can be specified only when resourceType is specified. Also we need to click on "search" button to initiate a search.  When resourceId and resourceType is specified , search returns correct set of entries relating to the id.
