### ISSUE TITLE
No serviceOptions found for cluster version [v1.20.2-rancher2-1] error seen when provisioning clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31130]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- deployed 1 node rke DO and a 1 linux, 1 windows node clusters
- The clusters are stuck in Provisioning state

<img width="1262" alt="Screen Shot 2021-02-03 at 11 25 52 PM" src="https://user-images.githubusercontent.com/26032343/106859021-551c6e00-6677-11eb-932e-a0c4eac99a5d.png">

**Expected Result:**
Cluster should come up successfully.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `b4b2322f`
- Installation option (single install/HA):

**Cluster information** 
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke custom and node driver
- Kubernetes version (use `kubectl version`):

```
1.20.2-rancher2-1
```

**Comment by StrongMonkey** [comment]
Can you test on the latest master and let me know if it solves the issue

**Comment by sowmyav27** [comment]
**on master-head - commit id: `fbe2c30d9`**

- Deployed AWS rke clusters with k8s 1.20.2-rancher2-1
- Clusters came up Active
