### ISSUE TITLE
unable to install default chart option for rancher-backups and cis-benchmark RC00 

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31137]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* v2.5.6-rc4 
* go to charts and install default options for rancher backups/CIS-benchmark

**Result:**
* fails with error `This chart requires rancher-<cis-benchmark/backup>-crd=match but no matching chart was found`
<img width="1539" alt="Screen Shot 2021-02-04 at 9 29 02 AM" src="https://user-images.githubusercontent.com/16691014/106935647-778ea580-66d0-11eb-81bc-e1ca392745c8.png">
**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.6-rc4 and 2.5-head (8201e08)
- Installation option (single install/HA): single install

- Docker version (use `docker version`): 19.03.15

**Comment by deniseschannon** [comment]
@aiyengar2 @cbron Could this be related to the most recent chart re-write changes or anything?

**Comment by slickwarren** [comment]
CIS benchmark and Backups are now able to be installed on 2.5-head (4cb2ebe) and master-head (fbe2c30) for rc00 (default options):
<img width="1523" alt="Screen Shot 2021-02-08 at 8 12 43 AM" src="https://user-images.githubusercontent.com/16691014/107247031-ba5cc000-69e5-11eb-90b1-427d22ce40ef.png">
<img width="806" alt="Screen Shot 2021-02-08 at 8 12 57 AM" src="https://user-images.githubusercontent.com/16691014/107247044-bdf04700-69e5-11eb-8afa-8822ed5272e8.png">
