### ISSUE TITLE
2.5.5 cannot pull local-registry/rancher/rke-tools:v0.1.69

### ISSUE THREAD

**Issue by jehutyy** [rancher/rancher#31136]
**Bug**
I get a `cannot pull local-registry/rancher/rke-tools:v0.1.68` when adding a node to newly created cluster from rancher gui.
`local-registry` is a docker registry v2 loaded with images from rancher 2.5.5 release air gap assets got from `rancher-images.txt`, `rancher-load.sh` and `rancher-save.sh`.

**Steps to reproduce (least amount of steps as possible):**
* create a one node rke cluster with help of terraform rke provider with a private registry.
*  install rancher 2.5.5 from helm chart 
* create a cluster and add a node

**Result:**
you should get a `cannot pull local-registry/rancher/rke-tools:v0.1.68`

**Other details that may be helpful:**
It is a air gap install following rancher air gap instruction from website.
I'm doing it with terraform but I guess you can reproduce directly from rke, helm and kubectl.

**Environment information**
* latest rke terraform provider 
* latest helm terraform provider
* latest kubernetes terraform provider
* latest rancher2 terraform provider

**Comment by superseb** [comment]
Please provide the exact Terraform files and exact versions used. Also please provide full log of `terraform apply` and the output from `docker pull local-registry/rancher/rke-tools:v0.1.68` on the host.

**Comment by jehutyy** [comment]
Alright so for the sake of clarity I just reproduce this error with a rancher single node install in docker with a private registry with images from rancher 2.5.5 assets.
And I get the same error : `local-registry/rancher255/rancher/rke-tools:v0.1.69`

**Comment by tomhouweling1987** [comment]
I also can confirm that rke-tools:v0.1.69 and hyperkube:v1.19.7-rancher1 are not in de rancher-images.txt of version 2.5.5.

[rancher-images.txt](https://github.com/rancher/rancher/releases/download/v2.5.5/rancher-images.txt)
...
rancher/grafana-grafana:6.7.4
rancher/grafana-grafana:7.1.5
rancher/hyperkube:v1.16.15-rancher1
rancher/hyperkube:v1.17.16-rancher1
rancher/hyperkube:v1.18.14-rancher1
rancher/hyperkube:v1.19.6-rancher1
rancher/istio-1.5-migration:0.1.1
.....
rancher/rancher:v2.5.5
rancher/rke-tools:v0.1.66
rancher/rke-tools:v0.1.68
rancher/security-scan:v0.1.14
rancher/security-scan:v0.2.2
....

**Comment by jiaqiluo** [comment]
Hi @jehutyy @tomhouweling1987 

The `rancher-images.txt` is generated as part of the build process, so we don't update it directly. 

Instead, we release new K8s versions and images at https://github.com/rancher/kontainer-driver-metadata, and if Rancher can connect to the internet, it checks the URL `https://releases.rancher.com/kontainer-driver-metadata/release-v2.5/data.json` to update on its local `rke-metdata-config`. You can find it at Settings -> rke-metdata-config. 

If Rancher runs in an air-gap environment, it means Rancher cannot connect to the abovementioned URL, so it should NOT get any new K8s versions, and of course, should NOT use any new images. 

If you can check the API endpoint `https://your-server-url/v3/rkek8ssystemimages` on your setup, can you look up the image `rancher/rke-tools:v0.1.68`? You should see the K8s versions that use it. 

I find the following k8s versions that use the image `rancher/rke-tools:v0.1.68` on my v2.5.5 setup. My setup can access the internet, so it can update its `rke-metdata-config`

```
rancher/rke-tools:v0.1.68 is used by the following RKE versions 
- v1.15.12-rancher2-8
- v1.16.15-rancher1-4
- v1.17.17-rancher1-1
- v1.18.15-rancher1-1
- v1.19.7-rancher1-1
```

**Comment by jehutyy** [comment]
Alright thank you for your answer I understand better what I did wrong.

Is there a way to disable this behaviour ? It would be very valuable since when I'm testing air gap deployment 
on my laptop it would allow me to *not* disconnect from internet during install.

On a higher level would it be a possibility to put a more visible warning in air gap install instructions ?

**Comment by tomhouweling1987** [comment]
Hey @jiaqiluo ,

I think i found my problem. The rancher pulls the system images from a private registry but rancher itself can connect to the internet. So if he downloads the new metafile he sees a new version of rke-tools and k8s and want to use it. Because of the private registry and the air-gapped method to pull and push images to the private registry it cant find the new rke-tools and k8s image.

I tested it in a full air-gapped environment and i've got no problem. There it uses the rke-tools:v0.1.68 and k8s v1.19.6-1

Thnx for your great explanation of air-gapped setups :).

@jehutyy
For the Terraform setup we added a setting, deleted the url and the refresh interval to 0:

```
#
# Rancher 2 rke-metadata-config
#
resource "rancher2_setting" "rke-metadata-config" {

  depends_on = [rancher2_bootstrap.admin]

  provider = rancher2.admin

  name  = "rke-metadata-config"
  value = "{\"refresh-interval-minutes\": \"0\",\"url\": \"\"}"
}
```

For the single docker install i would set these settings manually before creating a cluster.
Maybe @jiaqiluo can say if this should work? I didnt test it yet.

**Comment by jiaqiluo** [comment]
Hi @jehutyy @tomhouweling1987

Rancher does not support setting the value of `rke-metdata-config` as a parameter in either the `docker run` command or the `helm install` command. 

You can edit it after Rancher runs up by 
- going to Settings on Rancher's UI 
- calling Rancher's API
- edit the CR in the local cluster: `kubectl get settings.management.cattle.io rke-metadata-config`
