### ISSUE TITLE
Audit Logs - Not able to launch any other action from audit log page when there are lot of entries audit logs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3113]
Server version - Build from master

Rancher sever set up has ~76000 entries.
There is also service creation/deletion that is happening using api keys , when trying to access the Audit log page.

Lauch "Admin"->"Audit Log" page.
After page is loaded , tryning to click on "i" for any entry/ clicking on "Next" button does nothing.
Even clicking on other tabs like process/admin , does nothing.

There is a constant attempt to get audit entries that happens constantly in the background.

**Comment by westlywright** [comment]
next button will be working, the info button will not work on latest until latest gets latest rancher

**Comment by sangeethah** [comment]
Tested with latest build from master:

Rancher sever set up has ~76000 entries.
There is also service creation/deletion that is happening using api keys , when trying to access the Audit log page.

Lauch "Admin"->"Audit Log" page.It takes few seconds to launch the page initially. 
But after that able to click on "i" to launch information for any entry,  clicking on "Next" button works. Also able to access other tabs.
