### ISSUE TITLE
Rancher docker install scripts are not working anymore on RHEL 7.x

### ISSUE THREAD

**Issue by brutus333** [rancher/rancher#31132]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

try to install docker-ce on a RHEL7.x server using one of the Rancher docker install scripts from: https://github.com/rancher/install-docker

**Result:**
the script is failing at yum makecache with:

```
+ sh -c 'yum makecache'
Loaded plugins: search-disabled-repos
https://download.docker.com/linux/centos/7Server/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.
```

**Other details that may be helpful:**
 Following the source of the issue I found that docker changed the URL base from https://download.docker.com/linux/centos/7Server to https://download.docker.com/linux/centos/7

This change is recent (in the last one week or two).

One possible workaround is to add `--releasever 7` to the yum commands (by altering the pkg_manager variable in the docker install script).

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): N/A
- Installation option (single install/HA):
N/A

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): N/A
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): N/A

```
(paste the output here)
```

- Docker version (use `docker version`):

```
19.03
```

**Comment by superseb** [comment]
Please test if using `19.03.14.sh` works as expected.

**Comment by sowmyav27** [comment]
- On Rhel 7.7 docker install fails
```
curl -L https://releases.rancher.com/install-docker/19.03.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17251  100 17251    0     0  43422      0 --:--:-- --:--:-- --:--:-- 43563
+ sudo -E sh -c 'yum install -y -q yum-utils iptables'
https://download.docker.com/linux/centos/7Server/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

```
- Installation of `19.03.14.sh` also fails in the same way
```
curl -L https://releases.rancher.com/install-docker/19.03.14.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17251  100 17251    0     0  70306      0 --:--:-- --:--:-- --:--:-- 70412
+ sudo -E sh -c 'yum install -y -q yum-utils iptables'
https://download.docker.com/linux/centos/7Server/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

**Comment by brutus333** [comment]
For me it worked with 19.03.14

**Comment by rawmind0** [comment]
For me `19.03.14.sh` is working fine, but `19.03.15.sh` and `20.10.x.sh` are failing just at rhel7, due to https://github.com/rancher/rancher/issues/29246

Working on a fix

**Comment by rawmind0** [comment]
Submitted PR with fix, https://github.com/rancher/install-docker/pull/68

**Comment by slickwarren** [comment]
* rhel AND oracle linux 7.9 with the 19.03 install script (currently 19.03.15) install correctly
* rhel AND oracle linux 7.9 installing 20.10.03 I get: 
```
+ sudo -E sh -c 'yum install -y -q docker-ce-cli-20.10.3-3.el7'
warning: /var/cache/yum/x86_64/7Server/docker-ce-stable/packages/docker-ce-cli-20.10.3-3.el7.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
Public key for docker-ce-cli-20.10.3-3.el7.x86_64.rpm is not installed
Importing GPG key 0x621E9F35:
 Userid     : "Docker Release (CE rpm) <docker@docker.com>"
 Fingerprint: 060a 61c5 1b55 8a7f 742b 77aa c52f eb6b 621e 9f35
 From       : https://download.docker.com/linux/centos/gpg
+ sudo -E sh -c 'yum install -y -q docker-ce-20.10.3-3.el7'
Error: Package: containerd.io-1.4.3-3.1.el7.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2:2.74
Error: Package: docker-ce-rootless-extras-20.10.3-3.el7.x86_64 (docker-ce-stable)
           Requires: slirp4netns >= 0.4
Error: Package: docker-ce-rootless-extras-20.10.3-3.el7.x86_64 (docker-ce-stable)
           Requires: fuse-overlayfs >= 0.7
Error: Package: 3:docker-ce-20.10.3-3.el7.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2:2.74
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by rawmind0** [comment]
@slickwarren , rhel 7 is working fine to me installing 20.10.03

```
+ sudo -E sh -c 'yum install -y -q docker-ce-cli-20.10.3-3.el7'
Failed to set locale, defaulting to C
warning: /var/cache/yum/x86_64/7Server/docker-ce-stable/packages/docker-ce-cli-20.10.3-3.el7.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
Public key for docker-ce-cli-20.10.3-3.el7.x86_64.rpm is not installed
Importing GPG key 0x621E9F35:
 Userid     : "Docker Release (CE rpm) <docker@docker.com>"
 Fingerprint: 060a 61c5 1b55 8a7f 742b 77aa c52f eb6b 621e 9f35
 From       : https://download.docker.com/linux/centos/gpg
+ sudo -E sh -c 'yum install -y -q docker-ce-20.10.3-3.el7'
Failed to set locale, defaulting to C
+ command_exists iptables
+ command -v iptables
+ start_docker
+ '[' '!' -z ']'
+ '[' -d /run/systemd/system ']'
+ sudo -E sh -c 'systemctl start docker'
+ sudo -E sh -c 'docker version'
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:34:14 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:32:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker ec2-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
```

oracle linux 7 is also failing to me, as docked package has a new requirements coming from developers repo. Submitted PR https://github.com/rancher/install-docker/pull/69 to fix the issue

**Comment by rawmind0** [comment]
PR https://github.com/rancher/install-docker/pull/69 already merged and published

**Comment by slickwarren** [comment]
this is now working on AWS Marketplace versions of Oracle Linux 7.9 and RHEL 7.9 using both docker 19.03.15 and 20.10.03.  Using AMIs without explicit support from redhat are likely not to work with Rancher's install scripts due to dependency issues.

**Comment by oxr463** [comment]
@slickwarren can you share the AMI ID you are using?

I am using `ami-029c0fbe456d58bd1`:

```
cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

curl https://releases.rancher.com/install-docker/20.10.sh | sh
[ . . . TRUNCATED . . . ]
INFO: Searching repository for VERSION '20.10.3'
INFO: yum list --showduplicates 'docker-ce' | grep '20.10.3.*el' | tail -1 | awk '{print $2}'
+ '[' -n 20.10.3-3.el7 ']'
+ sh -c 'yum install -y -q docker-ce-cli-20.10.3-3.el7'
Package 1:docker-ce-cli-20.10.3-3.el7.x86_64 already installed and latest version
+ sh -c 'yum install -y -q docker-ce-20.10.3-3.el7'
Error: Package: docker-ce-rootless-extras-20.10.5-3.el7.x86_64 (docker-ce-stable)
           Requires: slirp4netns >= 0.4
Error: Package: docker-ce-rootless-extras-20.10.5-3.el7.x86_64 (docker-ce-stable)
           Requires: fuse-overlayfs >= 0.7
Error: Package: 3:docker-ce-20.10.3-3.el7.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2:2.74
Error: Package: containerd.io-1.4.4-3.1.el7.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2:2.74
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by slickwarren** [comment]
we used https://aws.amazon.com/marketplace/pp/B07Z5GM7W6?ref=cns_srchrow and https://aws.amazon.com/marketplace/pp/B087SQZKTP?ref=cns_srchrow

**Comment by Oats87** [comment]
This doesn't seem to be a complete fix; the `rhui` repositories are a cloud-specific source of packages. On a non-cloud-AMI based system, you will need to enable the `rhel-7-server-extras-rpms` in order to receive a successful install of docker 20.10

Regardless, when looking at the AMI as provided by @oxr463 , I see that the RHUI repos are in fact on the system. It's strange that the latest install script is not properly enabling the corresponding `rhui-rhel-7-server-rhui-extras-rpms` repository.

**Comment by rawmind0** [comment]
> This doesn't seem to be a complete fix; the rhui repositories are a cloud-specific source of packages. On a non-cloud-AMI based system, you will need to enable the rhel-7-server-extras-rpms in order to receive a successful install of docker 20.10

Thanks @Oats87 , i'll add it to the script

> Regardless, when looking at the AMI as provided by @oxr463 , I see that the RHUI repos are in fact on the system. It's strange that the latest install script is not properly enabling the corresponding rhui-rhel-7-server-rhui-extras-rpms repository.

It seems that the cloud-specific repo is called in a distinct way, depending on the ami used:
- Tested at `ami-0768d11005626f47b` (no suscription) repo is called `rhel-7-server-rhui-extras-rpms` 
- Tested at `ami-018c55e9d34f949e9` (suscription) repo is called `rhui-rhel-7-server-rhui-extras-rpms` 

Also adding both to the script

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/install-docker/pull/70 

Could you please try with `https://raw.githubusercontent.com/rancher/install-docker/694466ba305830563fd87f4d31c3c73853dc99de/dist/20.10.3.sh`

**Comment by slickwarren** [comment]
I was able to test with the following AMI using the latest `20.10.sh` script:
ami-0768d11005626f47b (no subscription)
ami-04d7524f0f99dcb18 (community redhat, us-east-2 rhel 7.9)
ami-015d9f9ba68b67486 (community redhat hvm, 8.2)
all of which installed fine with the script.
