### ISSUE TITLE
Upgrade Helm to 3.5.2+

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#31145]
https://github.com/helm/helm/releases/tag/v3.5.2
We'll need to review all new changes from our current version, not just this version, as recent versions had some fairly large changes.

**Comment by cbron** [comment]
This needs to be paused due to version constraints in 3.5.2.

**Comment by cbron** [comment]
Moving to 2.6 to handle complications. Also assigning multiple people to handle multiple sides of the work.

**Comment by SheilaghM** [comment]
This will be a breaking change and there are a lot of changes that have to be done in conjunction. It's best to do these as one large piece and not have to do migrations repeatedly.

**Comment by aiyengar2** [comment]
rancher/charts changes are in. We can now proceed with the upgrade.

**Comment by kravciak** [comment]
Works fine on master-head (8073489)
Monitoring v2 (100.0.0+up16.6.0)
Chart repo: dev-v2.6 (375fdb1a74e2bb1418e8d03d7831c76c679883a7)

Tested with those steps:
 - rancher single server (docker)
 - deployed DO infra provider cluster in emberUI (1 control / 1 etcd / 3 workers)
 - installed monitoring v2 from dashboard

Result:
- docker logs does not contain any relevant errors
- helm install output does not show any warnings / errors

I tested other charts as part of https://github.com/rancher/rancher/issues/32914

**Comment by brendarearden** [comment]
@kravciak this is expected and is okay. The version is showing up like that because we are using a forked branch version of helm for this release. In our rancher/helm repo we previously have used tags, but this version has not been tagged so it is showing up with the hash for the branch.
