### ISSUE TITLE
nonexistent tag used in image pull: rancher/fluentd:v0.1.24 -- Logging v1

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31144]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy rancher v2.5.6-rc4
* launch logging with fluentd

**Result:**
* fluentd deployment unable to pull image 
* checking docker hub does not show version rancher/fluentd:v0.1.24

`ImagePullBackOff: Back-off pulling image "rancher/fluentd:v0.1.24"` and `ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: manifest for rancher/fluentd:v0.1.24 not found: manifest unknown: manifest unknown`

**Other details that may be helpful:**
* https://hub.docker.com/r/rancher/fluentd/tags?page=1&ordering=last_updated does not have `rancher/fluentd:v0.1.24`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.6-rc4
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom, Oracle Linux 8.3 with docker 20.10.3 and node driver ubuntu 18.04 docker version 19.03.15
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 8vCPU 32GB mem
- Kubernetes version (use `kubectl version`):

- Docker version (use `docker version`): 20.10.03

**Comment by luthermonson** [comment]
@slickwarren the builds actually failed, give us a bit and we'll figure it out.

**Comment by luthermonson** [comment]
@slickwarren please try again, we fixed the build and the tags/manifests are good.

**Comment by slickwarren** [comment]
now able to successfully install rancher/fluentd:v0.1.24.
thanks!
