### ISSUE TITLE
Logging V1 'edit as file' -> `dry run` option resets file entry to default

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31149]
**What kind of request is this (question/bug/enhancement/feature request):**
* Bug

**Steps to reproduce (least amount of steps as possible):**
* launch logging v1 on a cluster/project
* select `edit as file` above `none` and enter your credentials
* run `test run`
* scroll back up to the file entry section

**Result:**
* file entry is cleared
* this is an issue if your dry run passes, and you click save immediately after
<img width="498" alt="Screen Shot 2021-02-04 at 4 37 49 PM" src="https://user-images.githubusercontent.com/16691014/106974146-08817300-6709-11eb-8531-8f79df0bb560.png">
<img width="323" alt="Screen Shot 2021-02-04 at 4 37 27 PM" src="https://user-images.githubusercontent.com/16691014/106974098-f99ac080-6708-11eb-9906-e6cf919cd175.png">
<img width="373" alt="Screen Shot 2021-02-04 at 4 37 56 PM" src="https://user-images.githubusercontent.com/16691014/106974099-f99ac080-6708-11eb-92f3-2cb89d94feb1.png">
<img width="639" alt="Screen Shot 2021-02-04 at 4 37 14 PM" src="https://user-images.githubusercontent.com/16691014/106974102-fa335700-6708-11eb-8875-442c4f5877ab.png">

**Other details that may be helpful:**
if you accidentally save the incorrect/template as your logging, I was unable to successfully get my setup to work from file, even after disabling logging, re-enabling, and immediately saving the config (without doing the dry-run).  Trying the exact same file on a 'fresh' cluster was able to enable logging (again, without messing with the dry run)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): this is an issue on v2.5.5 and also tested v2.5.6-rc4
- Installation option (single install/HA): single and HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): imported (aws) 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 8 vCPU
- Kubernetes version (use `kubectl version`):

- Docker version (use `docker version`): 19.03.15 and 20.10.3

**Comment by slickwarren** [comment]
after some further testing, this appears to only happen for logging outside of the `system` project and is only through the UI. No API call was made to make the change.

**Comment by slickwarren** [comment]
still seeing this issue on 2.5-head 7adf738ff65dcda4c69314da038ea7e4cc1aea3e and master-head (98fe72a40efb771428cd3eac0096db4ac0b5cdae) pulled about an hour ago
* followed same steps as in original post

**Comment by Ellenqs** [comment]
Validated on Rancher v2.5-head 03b8153 and master-head 007e298.

**Steps:**

- launch logging v1 on a cluster/project
- select edit as file above none and enter your credentials
- run `test run`
- scroll back up to the file entry section

**Result:**
The content of file entry (hostname and port) still exist. Empty cache and hard refresh the page, they are still there.

<img width="778" alt="Screen Shot 2021-02-18 at 11 15 13 AM" src="https://user-images.githubusercontent.com/75277058/108409390-06c0b080-71db-11eb-9270-2713a3e42e6a.png">
