### ISSUE TITLE
fleet agent - history is unlimited - crashes kubernetes with memory leak

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#31156]
An old issue, again in a new system.

https://github.com/rancher/rancher/pull/28766

This was an issue already with the old rancher apps and it is here again. The fleet-agent does not clean up itself and additionally seems to have some trouble with some custom validation of the deployed version (will link another ticket here).

This results in a memory leak and crashes whole kubernetes clusters.

----

**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by janeczku** [comment]
@wzrdtales Can you please provide the steps to reproduce as well as the information about your environment?

**Comment by wzrdtales** [comment]
change the fleet agent, i.e. add a http proxy. see how fleet agent starts going crazy and after that also the indefinite history becomes apparent.

**Comment by wzrdtales** [comment]
apparently some of your colleagues stumbled upon this individually already https://github.com/rancher/fleet/commit/361655898fcb11571ffaa170698fd252900815dc

**Comment by janeczku** [comment]
Apparently, this was already reported previously and fix is in progress: https://github.com/rancher/fleet/issues/232
