### ISSUE TITLE
Unable to deploy DO/Linode cluster with docker 20.10.x

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31151]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Deploy a 1 node DO cluster.
2. Node fails to finish registering, is stuck in provisioning with error `Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded`

**Expected Result:**
Node should be provisioned and cluster should come up successfully.

**Other details that may be helpful:**
- this does not happen on an AWS node driver cluster
- This does not happen when using DO + 19.03 latest docker
- This happens on a Linode cluster also.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `8201e080df7` and master-head - commit id: `fbe2c30`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO rke node driver
- Kubernetes version (use `kubectl version`):

```
1.20
```

- Docker version (use `docker version`):

```
20.10.x
```

**Comment by rawmind0** [comment]
The issue seems related with docker-machine https://github.com/docker/machine/issues/4865 and docker 20.10.03 installation. The problem seems to be a race condition when the docker daemon is restarted with the docker-machine config applied, so the docker daemon is not listening at tcp port, making docker-machine check fails.

@sowmyav27 have you tested if the manual execution of the docker-install script works fine on DO/linode vms??

**Comment by sowmyav27** [comment]
@rawmind0 Yes, manual installation of 20.10.x docker install script works fine on a DO node.

**Comment by rawmind0** [comment]
Running docker-machine manually is confirming the issue,
```
rancher-machine create --driver digitalocean --digitalocean-access-token XXXX --digitalocean-image "ubuntu-18-04-x64" --digitalocean-size "s-1vcpu-1gb" --engine-install-url https://releases.rancher.com/install-docker/20.10.sh rancher-machine-test
Running pre-create checks...
Creating machine...
(raul-machine-test) Creating SSH key...
(raul-machine-test) Creating Digital Ocean droplet...
(raul-machine-test) Waiting for IP address to be assigned to the Droplet...
(raul-machine-test) Created droplet ID 230222274, IP address 142.93.76.123
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker from: https://releases.rancher.com/install-docker/20.10.sh
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
```

Docker 20.10.3 is installed successfully, but once rancher-machine  [configure auth](https://github.com/rancher/machine/blob/master/libmachine/provision/utils.go#L64), the docker service is not restarting properly, so it's not listening on tcp port, making check fails.

Submitted PR https://github.com/rancher/machine/pull/112 to fix the issue, 

Tested with patched build on DO ubuntu 18.04 and 20.04
```
rancher-machine-patched create --driver digitalocean --digitalocean-access-token XXXX --digitalocean-image "ubuntu-18-04-x64" --digitalocean-size "s-1vcpu-1gb" --engine-install-url https://releases.rancher.com/install-docker/20.10.sh rancher-machine-test
Running pre-create checks...
Creating machine...
(raul-machine-test) Creating SSH key...
(raul-machine-test) Creating Digital Ocean droplet...
(raul-machine-test) Waiting for IP address to be assigned to the Droplet...
(raul-machine-test) Created droplet ID 230227736, IP address 68.183.54.225
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker from: https://releases.rancher.com/install-docker/20.10.sh
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: ./bin/rancher-machine-Darwin-x86_64 env raul-machine-test
(raul-machine-test) Closing plugin on server side
```

```
rancher-machine-patched create --driver digitalocean --digitalocean-access-token XXXX --digitalocean-image "ubuntu-20-04-x64" --digitalocean-size "s-1vcpu-1gb" --engine-install-url https://releases.rancher.com/install-docker/20.10.sh raul-machine-test
Running pre-create checks...
Creating machine...
(raul-machine-test) Creating SSH key...
(raul-machine-test) Creating Digital Ocean droplet...
(raul-machine-test) Waiting for IP address to be assigned to the Droplet...
(raul-machine-test) Created droplet ID 230229342, IP address 167.71.176.166
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker from: https://releases.rancher.com/install-docker/20.10.sh
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: ./bin/rancher-machine-Darwin-x86_64 env raul-machine-test
(raul-machine-test) Closing plugin on server side
```

**Comment by rawmind0** [comment]
Released new rancher-machine version including the patch, https://github.com/rancher/machine/releases/tag/v0.15.0-rancher51

**Comment by rawmind0** [comment]
rancher-machine version updated and merged at Rancher: 
* 2.5: https://github.com/rancher/rancher/pull/31219
* master: https://github.com/rancher/rancher/pull/31220
