### ISSUE TITLE
secret kubeconfig not found - fleet

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#31159]
This error is never resolving and there since the first upgrade and still there with rancher v2.5.5

![image](https://user-images.githubusercontent.com/1786821/107033628-e134af80-67b5-11eb-9542-c9986561246d.png)

maybe this is  even releated to the major trouble of the later upgrades described here ... https://github.com/rancher/rancher/issues/30032

**Comment by masanetes** [comment]
I have a similar problem. Has this been resolved in subsequent versions?
