### ISSUE TITLE
cattle-pipeline registry-proxy port conflicts with nginx-ingress-controller

### ISSUE THREAD

**Issue by danielhass** [rancher/rancher#31155]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Update from v2.4.8 to v2.5.5

**Result:**
Rancher is deploying a namespace `cattle-pipeline` with a daemon set called `registry-proxy`. This daemon set is configured to use the host networking namespace and is exposing port 80. This conflicts with our Rancher managed nginx-ingress-controller deployments. Currently we worked around this via editing the daemon set to not use the host network mode, so our nginx-ingress is running fine. But this results in a crash-loop of the aforementioned `registry-proxy` daemon set.

**Other details that may be helpful:**
We do not have any Rancher Pipelines in use. And as this feature is deprecated as of v2.5 we would also be fine with removing the whole daemon set if its not needed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): HA

**Comment by bemanuel** [comment]
Same problem here.

**Comment by zhaog918** [comment]
Same problem here.

**Comment by widewing** [comment]
I ran into this problem too. why is this closed? is there a solution?

**Comment by C-PET** [comment]
Same issue here as well V2.6.2
