### ISSUE TITLE
Validate Postgresql 12.5 as a K3s backend

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#31158]
**What kind of request is this (question/bug/enhancement/feature request):**
Continuation of rancher/rancher#30932 

We also need to validate 12.5 as a backend as well

@davidnuzik

gz#14360

**Comment by rancher-max** [comment]
Validated per our db certification matrix:

- Fresh Installation and run Sonobuoy Conformance tests
- Run functional test (all automated regression tests) on imported k3s cluster on Rancher
- Validate a longhorn deployment

k3s versions: v1.17.17+k3s1, v1.18.16+k3s1, v1.19.8+k3s1, v1.20.4+k3s1
postgres version 12.5 (on AWS RDS)
rancher version v2.5.6
