### ISSUE TITLE
Catalogue defaults do not display for enum and boolean

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3115]
Rancher 0.50.2

When defining a new Catalogue item with a variable parameter of type ENUM, the default value is not displayed in the GUI.  However, on submit, if no option is selected then the default will be used.

It would be better if the item in the dropdown corresponding to the default value were selected in the GUI to make it clear what will be used.

The same problem exists for Boolean type variables.

**Comment by tfiduccia** [comment]
version - master jan 07
Verified fixed
