### ISSUE TITLE
rotateEncryption action is not available on the cluster in the UI 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31150]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Enable secret encryption on the cluster
2. Secrets are encrypted with a key
3. API has rotateEncryptionKey option. 
4. On the cluster UI, there is NO option to Rotate Encryption Keys

**Expected Result:**
An action to rotate the encryption keys should be available on the UI

**Other details that may be helpful:**
Happens on 2.5.5 also

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.5 and 2.5-head - commit id: `8201e08`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do/custom
- Kubernetes version (use `kubectl version`):

```
any
```

**Comment by deniseschannon** [comment]
For now, let's move this out of v2.5.6 as I'm not sure if we want to view this in the UI.

**Comment by sowmyav27** [comment]
This cluster had default recurring etcd backup set as 12 hours. But the default safe backup time interval for showing this action on the UI is 6 hours.

**Comment by westlywright** [comment]
@deniseschannon to be clear are we moving this ticket out of 2.5.6? or are we rolling back the UI functionality completely?

**Comment by sowmyav27** [comment]
@westlywright as per an offline discussion with @deniseschannon we will have this feature from UI and backend as is for now.
