### ISSUE TITLE
SAML - Authentication pop up always show 404 on HA Rancher installs

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#31163]
**What kind of request is this:**
Bug

**Steps to reproduce:**

### Only reproduces on HA setups

- Install Rancher HA RKE
- As admin go and try to enable a SAML based auth. I used Okta and Keycloak
- After entering the correct credentials the popup should redirect to Rancher and self close it.

**Result:**

Instead the pop up shows a 404 Page Not Found 

![Screen Shot 2021-02-05 at 10 20 11 AM](https://user-images.githubusercontent.com/27659/107067640-cdc91a80-679c-11eb-8765-523e6106ce20.png)

**Other details that may be helpful:**

This is only reproducible in HA, Single Docker install works.

Not much info in logs
```
2021/02/05 17:05:03 [TRACE] REST GET apis/management.cattle.io/v3//tokens/token-rmlwj
2021/02/05 17:05:03 [DEBUG] Triggering auth refresh on user-855c9
2021/02/05 17:05:03 [DEBUG] Skipping refresh for user-855c9 due to max-age
2021/02/05 17:05:03 [TRACE] GET: 9.215187ms, authconfigs
2021/02/05 17:05:07 [DEBUG] Wrote ping
2021/02/05 17:05:07 [DEBUG] Wrote ping
2021/02/05 17:05:07 [DEBUG] Wrote ping
2021/02/05 17:05:07 [DEBUG] Wrote ping
2021/02/05 17:05:08 [DEBUG] Wrote ping
2021/02/05 17:05:08 [DEBUG] Wrote ping
2021/02/05 17:05:11 [TRACE] REST GET apis/management.cattle.io/v3//tokens/token-rmlwj
2021/02/05 17:05:11 [DEBUG] Triggering auth refresh on user-855c9
2021/02/05 17:05:11 [DEBUG] Skipping refresh for user-855c9 due to max-age
2021/02/05 17:05:11 [TRACE] GET: 25.752975ms, authconfigs
2021/02/05 17:05:11 [TRACE] REST UPDATE api//v1/cattle-global-data/secrets/keycloakconfig-spkey
2021/02/05 17:05:11 [TRACE] GET: 13.81793ms, authconfigs
2021/02/05 17:05:11 [TRACE] GET: 15.836876ms, authconfigs
2021/02/05 17:05:11 [TRACE] REST GET apis/management.cattle.io/v3//tokens/token-rmlwj
2021/02/05 17:05:11 [DEBUG] Triggering auth refresh on user-855c9
2021/02/05 17:05:11 [DEBUG] Skipping refresh for user-855c9 due to max-age
2021/02/05 17:05:11 [TRACE] GET: 3.488143ms, authconfigs
2021/02/05 17:05:11 [TRACE] REST GET apis/management.cattle.io/v3//authconfigs/keycloak
2021/02/05 17:05:11 [TRACE] REST GET api//v1/cattle-global-data/secrets/keycloakconfig-spkey
2021/02/05 17:05:12 [DEBUG] Wrote ping
2021/02/05 17:05:12 [DEBUG] Wrote ping
2021/02/05 17:05:12 [TRACE] REST GET apis/management.cattle.io/v3//tokens/token-rmlwj
2021/02/05 17:05:12 [DEBUG] Triggering auth refresh on user-855c9
2021/02/05 17:05:12 [DEBUG] Skipping refresh for user-855c9 due to max-age
2021/02/05 17:05:12 [DEBUG] Wrote ping
2021/02/05 17:05:12 [DEBUG] Wrote ping
2021/02/05 17:05:13 [DEBUG] Wrote ping
2021/02/05 17:05:13 [DEBUG] Wrote ping
2021/02/05 17:05:13 [TRACE] REST LIST api//v1//componentstatuses
```

**Environment information**
- Rancher version: 
  - `master-head (02/05/2021)` _fbe2c30_
  - `v2.5-head (02/05/2021)` _8201e08_
- Installation option: HA

**Comment by izaac** [comment]
This is not a blocker for QA, but we don't want it in the final release. Removing the blocker tag.

**Comment by prachidamle** [comment]
@izaac Can you capture the http traffic when you are configuring SAML provider and seeing this error? That should capture the "AuthConfig" that UI is current sending to API

**Comment by eest** [comment]
Could this be the same issue as #18380? See my debugging results at the end of that issue for details. While I was working with Shibboleth it sounds pretty similar. I did not _always_ see the 404, it depended on what rancher pod happened to receive the request in relation to which pod handled my setup request.

**Comment by izaac** [comment]
@eest I might've been very lucky then I was very consistently experiencing the 404 in the latest `*-head` builds. But you are correct those look the same symptoms I've observed.

**Comment by eest** [comment]
@izaac could you maby try to run curl a few times against the metadata url when the problem occurs (replacing "/saml/acs" for "/saml/metadata" in the screenshot above)? If it behaves like it did for me you will see a repeating pattern of one successful request among several failed ones depending how many rancher replicas you have.

**Comment by izaac** [comment]
@eest this is correct, I got 404 a few times and metadata was returned some times valid xml content `/v1-saml/keycloak/saml/metadata`

I reproduced this on `v2.5.5`

**Comment by izaac** [comment]
If I get a 404 and then I hit Refresh in the popup and click `Resend` in the confirmation dialog I get the auth enabled.

**Comment by eest** [comment]
@prachidamle my guess why it appears to work better after a resend is probably because for each resend a new rancher pod has the chance to be the one to handle that web request. Given 3 replicas, after initial send 1/3 pods have the SAML endpoints temporarily enabled, after a resend (given that the resent request does not happen to be handled by the already enabled replica) there is now a 2/3 chance to succeed etc.

I'm guessing for this to work properly instead of special-casing the initial setup phase with a "enable it in this process temporarily when I see the request" it should instead be handled by only writing config to the db and have all replicas pick it up that way. Config is already written to the db today, but with `enabled: false`, which is why I think the other replica control loops ignore it as it stands. I am not sure why, but maby this is to not leave an unfinished setup phase enabled forever if never completed.

For pointers to the specific parts of the code that lead me to this conclusion, see my linked issue above.

**Comment by scila1996** [comment]
Same issue ! i have install rancher on kubernetes with default replicas equal 3. But AFDS return 404 when redirect to

https://<rancher server>/v1-saml/adfs/saml/acs

But when i set replicas equal 1. It work immediately !

**Comment by arcreigh** [comment]
Was just able to replicate this on 2.5.7 single node docker install. F5 and resend was able to continue onwards with the config.

**Comment by scila1996** [comment]
Hi all !

i was solved this problem, maybe it's not cause by rancher server. Problem is the LoadBalancer or Ingress Controller, in my case and most systems use NGINX Ingress, we must add this annotation to fix this

```
ingress:
  extraAnnotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-name: route
```

and then, we can scale Rancher Server to replicas=3 or more than !

**Comment by hoanbc** [comment]
> Hi all !
> 
> i was solved this problem, maybe it's not cause by rancher server. Problem is the LoadBalancer or Ingress Controller, in my case and most systems use NGINX Ingress, we must add this annotation to fix this
> 
> ```
> ingress:
>   extraAnnotations:
>     nginx.ingress.kubernetes.io/affinity: cookie
>     nginx.ingress.kubernetes.io/affinity-mode: persistent
>     nginx.ingress.kubernetes.io/session-cookie-name: route
> ```
> 
> and then, we can scale Rancher Server to replicas=3 or more than !

i did resolve my problem with this solution. rancher v2.6.6

**Comment by izaac** [comment]
Assigning this old issue to Auth QA SME for follow up depending on priorities.

**Comment by Jono-SUSE-Rancher** [comment]
@prachidamle  @martyav - Same as the other issue: Are we able to take this out of v2.7.7 since that has been released and move this to either a future milestone or has it been completed sufficiently for the ticket to be closed?

**Comment by martyav** [comment]
@I have no objections. It's listed in the published release note and is also linked to from the original PR if we need to track it from GH.

**Comment by Jono-SUSE-Rancher** [comment]
This has been added to release notes as a known issue and can be resolved at another time.
