### ISSUE TITLE
Urgent!!!! rancher mariadb end of life

### ISSUE THREAD

**Issue by ElZakariyae** [rancher/rancher#31161]
Hello,

We are running a rancher 1 server with single node setup and we just noticed that our Mariadb version will be no longer supported and we have to upgrade it to a newer version at least 10.3.

Could you please confirm that we can upgrade the RDS Mariadb to 10.3? if not do you have any good suggestions?

Note that we have to find a solution before February 9 2021.

Thanks. 

Rancher version: v1.6.28
AWS RDS Mariadb Version: 10.1.34

**Comment by vincent99** [comment]
The end-of-life for Rancher 1.x was 7+ months ago, following over 2 years of notice that 2.x was going to be the only way forward.  So we no longer maintain or test 1.x.  

The docs have long contained:

> NOTE:
Currently, MariaDB 10.3 and MySQL 8.x are not supported

So the immediate answer to your question is "probably not", but I don't know what the reason for that note was anymore or what consequence it might have.  I would spin up a newer version as a separate rds instance, copy the data over and see what happens at this point.

**Comment by ElZakariyae** [comment]
Hello @vincent99 

Thanks for your prompt reply.

That's clear, we also think to install a Mariadb in a virtual machine (maybe within the rancher server machine)with a supported version and take a db dump of the current db, can you please clarify how to configure the new database in rancher?

**Comment by vincent99** [comment]
With the same flags you're currently using to point to RDS... https://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#launching-rancher-server---single-container---external-database
