### ISSUE TITLE
Air gap installation doesn't have right images set for each 2.5.x versions

### ISSUE THREAD

**Issue by jehutyy** [rancher/rancher#31165]
I've tested 2.5.5, 2.5.4 and 2.5.3 single node and HA and every each of these doesn't allow to create a cluster then add a new node following air gap instructions (with private registry).

Each of them successfully permit to add a node but during node bootstrapping I inevitably hit `cannot pull rke-tools:v0.1.69` even though `rancher-images.txt` specify v0.1.66 and v0.1.68.

**Comment by sowmyav27** [comment]
@jehutyy We recently released newer versions of k8s [here](https://github.com/rancher/rancher/issues/30827). For an airgapped setup please review this [documentation](https://rancher.com/docs/rancher/v2.x/en/admin-settings/k8s-metadata/#air-gap-setups)

**Comment by jiaqiluo** [comment]
Hi, @jehutyy  Do you host and sync your Rancher server with a local mirror of the RKE metadata? 
That is the only possibility, as far as I know, that Rancher can know and use a new tag that is not included in its `rancher-images.txt` when it is installed in the air-gap environment.

Or is it possible that your Rancher server has access to the internet, or at least to `https://releases.rancher.com/kontainer-driver-metadata/release-v2.5/data.json` ?

**Comment by jehutyy** [comment]
Ho thanks both for your answer. I was not aware of that new specificity. As you can imagine I do not host a local mirror for rke metadata. 

Just to be sure that I understand correctly, can you confirm that in order to deploy rancher and further rancher hosted cluster, the airgap installation instruction are not self sufficient?

I never stumbled upon instructions about rke metatadata while browsing air gap instruction. 

For the sake of completeness, we've several rancher 2.3.7 cluster and never have had to do much more than download rancher-images.tar.gz and deploy rancher (with rke or docker) and subsequent cluster.

**Comment by jiaqiluo** [comment]
this is the duplication of https://github.com/rancher/rancher/issues/31136

@jehutyy Please check my latest response to the above issue.

**Comment by jehutyy** [comment]
@jiaqiluo Thank you very much I'll have a look.
