### ISSUE TITLE
User ID Tracking in Audit Logs

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#31166]
This ticket is for the feature/enhancement: "User level audit log traceability."

Description:

Rancher needs to include the Identity Provider name(common name of the user in the external Auth provider) in both the Rancher and downstream Kubernetes audit logs. 

Problem:
A Rancher Admin can not trace an event from the Rancher audit logs and into the Kubernetes audit logs without knowing the mapping of Identity Provider user → u-xXXX id mapping.

Learning the Identity Provider user and u-XXXX mapping requires Rancher API, UI, or local cluster access. For users delivering KaaS without allowing Rancher users access to Rancher there is no way to know the mapping.

KaaS operators are in the critical path of answering questions from cluster owners “who did X in the cluster?”. This inhibits the self-service model.

Requirements:
A downstream cluster admin should be able to look at the Kubernetes audit logs and know that external IDP user X performed an action without needing to view anything in Rancher.

If the audit logs are shipped off of the cluster, a user of the logging system should be able to identify the user in the Identity Provider system.

A Rancher Admin should be able to view Rancher audit logs and follow through to the Kubernetes audit log by Identity Provider username.

Related tickets:
https://rancher.zendesk.com/agent/tickets/7326

gz#17013

**Comment by prachidamle** [comment]
Steps to test this fix for Kubernetes Audit log:

1. On a rancher setup, deploy a cluster and enable audit log feature via the cluster.yml, example this is the config needed at minimum to enable Kubernetes audit logs
`services:
  kube-api:
    audit_log:
      enabled: true
 `
 Details for more config here: https://rancher.com/docs/rke/latest/en/config-options/audit-log/#example-configurations
 
 2. Enable Authentication by configuring some external auth provider like github/LDAP etc.
 
 3. Login as an  admin or a standard user and deploy some workload in say the cluster's default project
 
 4. Check the Kubernetes audit logs on the cluster's node at `/var/log/kube-audit/audit-log.json` path 
 
 5. Grep for the "impersonatedUser" entry in the log and check the "extra" field under it. The username and principalid of the user from the external auth provider should be logged.
 
Sample Snippet of Audit logs as seen for a rancher setup with OpenLDAP auth enabled, when a user scales up a workload:

`root@prachi-doaudit1:~# tail -f /var/log/kube-audit/audit-log.json | grep impersonat
{{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"338cd247-9a98-4687-8996-50c687420591","stage":"ResponseComplete","requestURI":"/apis/apps/v1/namespaces/default/deployments/myapp?timeout=45s","verb":"update","user":{"username":"system:serviceaccount:cattle-system:kontainer-engine","uid":"9ec5e24d-3e01-47cb-b7fe-0ec7e1714f2c","groups":["system:serviceaccounts","system:serviceaccounts:cattle-system","system:authenticated"]},"impersonatedUser":{"username":"user-h9vkf","groups":["openldap_group://cn=caringQA,ou=groups,dc=us-west-2,dc=compute,dc=internal","openldap_group://cn=uniquegroup,ou=groupsDuplicate,dc=us-west-2,dc=compute,dc=internal","system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["openldap_user://uid=testuser1,ou=dev,dc=us-west-2,dc=compute,dc=internal"],"username":["testuser1"]}},"sourceIPs":["10.42.0.12"],"userAgent":"rancher/v0.0.0 (linux/amd64) kubernetes/$Format cluster c-shcnd","objectRef":{"resource":"deployments","namespace":"default","name":"myapp","uid":"65cfbb0f-fa66-447c-bc31-12374b249a40","apiGroup":"apps","apiVersion":"v1","resourceVersion":"14817"},"responseStatus":{"metadata":{},"code":200},"requestReceivedTimestamp":"2021-04-30T22:03:44.866046Z","stageTimestamp":"2021-04-30T22:03:44.879041Z","annotations":{"authentication.k8s.io/legacy-token":"system:serviceaccount:cattle-system:kontainer-engine","authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"globaladmin-user-h9vkf\" of ClusterRole \"cluster-admin\" to User \"user-h9vkf\""}}`

The following has been added to the audit log:
`
"extra":{"principalid":["openldap_user://uid=testuser1,ou=dev,dc=us-west-2,dc=compute,dc=internal"],"username":["testuser1"]
`

**Comment by prachidamle** [comment]
Steps to test this fix with Rancher API audit logs:
1. Enable API audit log at Rancher level, by deploying the server with options like `--set auditLog.level=1` as documented here https://rancher.com/docs/rancher/v2.x/en/installation/resources/advanced/api-audit-log/

2. This will create a sidecar container in the Rancher pod to collect the audit log . This container (rancher-audit-log) will stream the log to stdout. You can collect this log as you would any container log.

3. The Impersonate-Extra headers have been added to this audit log as well to log the user's username and principalid.

4. Following are the Rancher API audit (at AUDIT_LEVEL=1 (metadata)) logs showing the extra info logged when deploying a workload
`
{"auditID":"3910f1da-cf54-4c98-8237-4f5fdc60b80c","requestURI":"/v3/projects/c-shcnd:p-v2gcw/workload","user":{"name":"user-h9vkf","group":["openldap_group://cn=caringQA,ou=groups,dc=us-west-2,dc=compute,dc=internal","openldap_group://cn=uniquegroup,ou=groupsDuplicate,dc=us-west-2,dc=compute,dc=internal","system:authenticated","system:cattle:authenticated"],"extra":{"principalId":["openldap_user://uid=testuser1,ou=dev,dc=us-west-2,dc=compute,dc=internal"],"userName":["testuser1"]}},"method":"POST","remoteAddr":"172.31.36.137:52730","requestTimestamp":"2021-05-03T19:15:38Z","responseTimestamp":"2021-05-03T19:15:38Z","responseCode":201,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Content-Length":["872"],"Content-Type":["application/json"],"Impersonate-Extra-Principalid":["openldap_user://uid=testuser1,ou=dev,dc=us-west-2,dc=compute,dc=internal"],"Impersonate-Extra-Username":["testuser1"],"Impersonate-Group":["openldap_group://cn=caringQA,ou=groups,dc=us-west-2,dc=compute,dc=internal","openldap_group://cn=uniquegroup,ou=groupsDuplicate,dc=us-west-2,dc=compute,dc=internal","system:authenticated","system:cattle:authenticated"],"Impersonate-User":["user-h9vkf"],"Origin":["https://ec2-3-137-201-13.us-east-2.compute.amazonaws.com"],"Referer":["https://ec2-3-137-201-13.us-east-2.compute.amazonaws.com/p/c-shcnd:p-v2gcw/workloads/run"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"],"X-Api-Action-Links":["actionLinks"],"X-Api-Csrf":["69009294cc"],"X-Api-No-Challenge":["true"],"X-Forwarded-For":["108.221.20.194"],"X-Forwarded-Host":["ec2-3-137-201-13.us-east-2.compute.amazonaws.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Pro
to":["https"],"X-Real-Ip":["108.221.20.194"],"X-Request-Id":["32dfa067c7b8873f4b0c8092cda86e82"],"X-Scheme":["https"]},"responseHeader":{"Content-Encoding":["gzip"],"Content-Type":["application/json"],"Expires":["Wed 24 Feb 1982 18:42:00 GMT"],"X-Api-Schemas":["https://ec2-3-137-201-13.us-east-2.compute.amazonaws.com/v3/project/c-shcnd:p-v2gcw/schemas"],"X-Content-Type-Options":["nosniff"]}} `

**Comment by anupama2501** [comment]
Verified the following on master-head commit: 5d2b7ac
Node drivers and custom clusters:
Enabled auth openLDAP auth and logged in as admin user - u1

- Create a cluster c1 and enabled audit log by setting the level as metadata in "edit as yaml" of the cluster
- Create a namespace, workload logged in as u1 -- Verified auditlogs and the username as given in the Authprovider is displayed in the audit logs
- Delete the workload as u2 -- Verified auditlogs for deletion is displayed in the auditlogs
- Change the authprovider to AD and create a workload in the cluster c1 -- Verified the new user is displayed in the audit logs 

Enabled auditlogs on the rancher server
- Create a cluster c1
- Create a namespace, workload logged in as u1 -- Verified auditlogs and the username as given in the Authprovider is displayed in the audit logs of the rancher server 
- Delete the workload as u2 -- Verified auditlogs for deletion is displayed in the auditlogs of the rancher server 
- Change the authprovider to AD and create a workload in the cluster c1 -- Verified the new user is displayed in the audit logs 
of the rancher server

**Comment by anupama2501** [comment]
Verified:
**On rke2 cluster 1 node all roles, auth: okta - SAML**
1. Create an rke2 cluster with amazon ec2 nodes
2. Once the cluster is active, from control plane node [add on all cps if more than 1 cps exist] create a file for the auditlog.yaml and the contents:
```
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata
```
3. Auditlogs enabled by adding the contents: 
```
audit-policy-file: "/home/ubuntu/auditlog.yaml"
kube-apiserver-arg:
- 'audit-log-path=/var/lib/rancher/rke2/server/logs/audit-log'
```
4. Once the cluster is up and active, created a workload, namespace and delete the workload. Sample audit logs for the same:
Output when the workload creation was **successful**:
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"1071a5d2-ae9a-493c-a21a-4305d89d4e2d","stage":"ResponseComplete","requestURI":"/apis/apps/v1/namespaces/default/deployments?includeObject=Object\u0026timeout=15m0s","verb":"create","user":{"username":"system:serviceaccount:cattle-system:rancher","uid":"ee8f0c85-58b2-4f0f-82d7-e47ce11e9e7d","groups":["system:serviceaccounts","system:serviceaccounts:cattle-system","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["rancher-57d9978dc7-xqpk4"],"authentication.kubernetes.io/pod-uid":["a515ab12-0ffc-418e-86b5-ffa87a50c411"]}},"impersonatedUser":{"username":"user-zcw99","groups":["system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["okta_user://iza**"],"username":["iza***"]}},"sourceIPs":[""],"userAgent":"rancher/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"deployments","namespace":"default","name":"test3","apiGroup":"apps","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":201},"requestReceivedTimestamp":"2021-05-19T15:03:07.620866Z","stageTimestamp":"2021-05-19T15:03:07.680165Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"globaladmin-user-zcw99\" of ClusterRole \"cluster-admin\" to User \"user-zcw99\""}}
```

When workload creation **failed**:
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"28415b9f-0b7d-466c-b80c-9b941804af03","stage":"ResponseComplete","requestURI":"/apis/apps/v1/namespaces/default/deployments?includeObject=Object\u0026timeout=15m0s","verb":"create","user":{"username":"system:serviceaccount:cattle-system:rancher","uid":"ee8f0c85-58b2-4f0f-82d7-e47ce11e9e7d","groups":["system:serviceaccounts","system:serviceaccounts:cattle-system","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["rancher-57d9978dc7-xqpk4"],"authentication.kubernetes.io/pod-uid":["a515ab12-0ffc-418e-86b5-ffa87a50c411"]}},"impersonatedUser":{"username":"user-zcw99","groups":["system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["okta_user://iza***"],"username":["iza***"]}},"sourceIPs":[""],"userAgent":"rancher/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"deployments","namespace":"default","name":"test2","apiGroup":"apps","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":409},"requestReceivedTimestamp":"2021-05-19T15:02:57.078814Z","stageTimestamp":"2021-05-19T15:02:57.097689Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"globaladmin-user-zcw99\" of ClusterRole \"cluster-admin\" to User \"user-zcw99\""}}
```



**Hosted Kubernetes cluster rancher logs:**
1. Create a gke cluster from rancher Kubernetes cluster after enabling rancher audit logs on the rancher server and github auth enabled
2. Once the cluster is active, verify the rancher logs which shows the username for the cluster creation with the username
```
{"auditID":"8cc1d883-0ec2-4f35-814d-341bb3070856","requestURI":"/v3/cluster?_replace=true","user":{"name":"user-vccfn","group":["github_org://9343010","github_team://1395580","github_team://1753055","system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["github_user://38144301"],"username":["an***"]}},"method":"POST","remoteAddr":"","requestTimestamp":"2021-05-19T14:23:23Z","responseTimestamp":"2021-05-19T14:23:23Z","responseCode":201,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Connection":["keep-alive"],"Content-Length":["2004"],"Content-Type":["application/json"],"Impersonate-Extra-Principalid":["github_user://38144301"],"Impersonate-Extra-Username":["an***"],"Impersonate-Group":["github_org://9343010","github_team://1***","github_team://1***","system:authenticated","system:cattle:authenticated"],"Impersonate-User":["user-vccfn"],"Origin":["https://***"],"Referer":["https://***/g/clusters/add/launch/googlegkev2"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"],"X-Api-Action-Links":["actionLinks"],"X-Api-Csrf":["3fd2831aee"],"X-Api-No-Challenge":["true"]},"responseHeader":{"Content-Encoding":["gzip"],"Content-Type":["application/json"],"Expires":["Wed 24 Feb 1982 18:42:00 GMT"],"X-Api-Schemas":["https://***/v3/cluster/schemas"],"X-Content-Type-Options":["nosniff"]}}

```
Adding a member as a standard user in the cluster that results in failure log:
```
{"auditID":"f81bba02-d3fe-4613-831a-0f0995af6e1d","requestURI":"/v3/clusterroletemplatebinding","user":{"name":"u-nfhhhy2o22","group":["openldap_group***","openldap_group***","system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["openldap_user***"],"username":["te***"]}},"method":"POST","remoteAddr":"","requestTimestamp":"2021-05-19T15:30:55Z","responseTimestamp":"2021-05-19T15:30:55Z","responseCode":403,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Connection":["keep-alive"],"Content-Length":["186"],"Content-Type":["application/json"],"Impersonate-Extra-Principalid":["openldap_user***"],"Impersonate-Extra-Username":["te***"],"Impersonate-Group":["openldap_group***","openldap_group***,"system:authenticated","system:cattle:authenticated"],"Impersonate-User":["u-nfhhhy2o22"],"Origin":["https://***"],"Referer":["https://***/c/c-8dhd5/security/members/add"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"],"X-Api-Action-Links":["actionLinks"],"X-Api-Csrf":["2f4cc7e252"],"X-Api-No-Challenge":["true"]},"responseHeader":{"Content-Encoding":["gzip"],"Content-Type":["application/json"],"Expires":["Wed 24 Feb 1982 18:42:00 GMT"],"X-Api-Schemas":["https://74.207.249.193/v3/schemas"],"X-Content-Type-Options":["nosniff"]}}
```

**Comment by anupama2501** [comment]
Verified on master-d8acb2177f6132874c970b070cc39d35544b85b0-head

1. Created a node driver cluster and enabled OpenLDAP auth and auditlog. Through a jenkins job using api keys created workloads, namespaces. Verified the audit logs recorded with the username as present in the auth provider.

Some logs when workloads are created through API keys 
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"78fc4408-6b33-4e86-9147-9ee93296d384","stage":"ResponseComplete","requestURI":"/api/v1/namespaces/anupre-app-ns?timeout=45s","verb":"get","user":{"username":"system:serviceaccount:cattle-system:kontainer-engine","uid":"64cdba68-2010-4f45-824d-193b343bc951","groups":["system:serviceaccounts","system:serviceaccounts:cattle-system","system:authenticated"]},"impersonatedUser":{"username":"u-nfhhhy2o22","groups":["openldap_group***,"openldap_group***","system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["openldap_user***"],"username":["t***2"]}},"sourceIPs":["***"],"userAgent":"rancher/v0.0.0 (linux/amd64) kubernetes/$Format cluster c-fv4fd","objectRef":{"resource":"namespaces","namespace":"anupre-app-ns","name":"anupre-app-ns","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":200},"requestReceivedTimestamp":"2021-05-20T17:58:49.452457Z","stageTimestamp":"2021-05-20T17:58:49.458561Z","annotations":{"authentication.k8s.io/legacy-token":"system:serviceaccount:cattle-system:kontainer-engine","authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"crb-62os3ea2f5\" of ClusterRole \"cluster-owner\" to User \"u-nfhhhy2o22\""}}
```


2. Using Rancher CLI, downloaded the rancher cli and logged into the cluster with API keys into the cluster from rancher CLI> The username with which the keys were associated is logged in the audit logs

```
{"auditID":"805ff69e-e391-4d03-b259-fd17a16d25b1","requestURI":"/v3/projects?limit=-1\u0026removed_null=1\u0026state_ne=inactive\u0026state_ne=stopped\u0026state_ne=removing\u0026system=false","user":{"name":"u-e4pdqvmcdl","group":["openldap_group***","openldap_group:***","system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["openldap_user:***"],"username":["te***"]}},"method":"GET","remoteAddr":"***:57536","requestTimestamp":"2021-05-20T19:22:53Z","responseTimestamp":"2021-05-20T19:22:53Z","responseCode":200,"requestHeader":{"Accept-Encoding":["gzip"],"Impersonate-Extra-Principalid":["openldap_user:***"],"Impersonate-Extra-Username":["te***"],"Impersonate-Group":["openldap_group:***l","openldap_group:/***","system:authenticated","system:cattle:authenticated"],"Impersonate-User":["u-e4pdqvmcdl"],"

```



3. Using api keys and curl command, created dns provider and created a worklaod in the cluster to verify the rancher and cluster level audit logs respectively.

```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"fca6e1f1-f382-434a-8d31-a237e860cb60","stage":"ResponseComplete","requestURI":"/apis/apps/v1/namespaces/anupre-app-ns/deployments?timeout=45s","verb":"create","user":{"username":"system:serviceaccount:cattle-system:kontainer-engine","uid":"64cdba68-2010-4f45-824d-193b343bc951","groups":["system:serviceaccounts","system:serviceaccounts:cattle-system","system:authenticated"]},"impersonatedUser":{"username":"u-nfhhhy2o22","groups":["openldap_group***","openldap_group***","system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["openldap_user***"],"username":["**te*****"]}},"sourceIPs":[""],"userAgent":"rancher/v0.0.0 (linux/amd64) kubernetes/$Format cluster c-fv4fd","objectRef":{"resource":"deployments","namespace":"anupre-app-ns","name":"wk-api","apiGroup":"apps","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":201},"requestReceivedTimestamp":"2021-05-20T19:16:32.874749Z","stageTimestamp":"2021-05-20T19:16:32.889516Z","annotations":{"authentication.k8s.io/legacy-token":"system:serviceaccount:cattle-system:kontainer-engine","authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"crb-62os3ea2f5\" of ClusterRole \"cluster-owner\" to User \"u-nfhhhy2o22\""}}

```
