### ISSUE TITLE
Monitoring V1/V2 targets rancher-monitoring-kubelet/exporter-kubelets-cluster-monitoring are down on OL 8.3

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31167]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* deploy rancher v2.5.6-rc4
* downstream cluster running Oracle Linux 8.3 and docker v20.10.3
* deploy monitoring (v1 or v2)
* wait for deployment to complete

**Result:**
* rancher-monitoring-kubelet (monitoring v1) or exporter-kubelets-cluster-monitoring (monitoring v2) are down in prometheus
<img width="832" alt="Screen Shot 2021-02-04 at 7 50 32 PM" src="https://user-images.githubusercontent.com/16691014/107089135-f825d280-67b2-11eb-85a6-c2d3eb764a80.png">
<img width="1009" alt="Screen Shot 2021-02-04 at 6 49 39 PM" src="https://user-images.githubusercontent.com/16691014/107089139-fb20c300-67b2-11eb-8d9b-d7b3e27a5e70.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.6-rc4
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4vCPU each, 5 node cluster. also tested on 2vcpu cluster with 5 nodes
- Kubernetes version (use `kubectl version`):

- Docker version (use `docker version`): 20.10.3

**Comment by slickwarren** [comment]
from Arvind: 
you’re using k8s 1.20, and https://github.com/kubernetes/kubernetes/pull/94272 indicates that the kubelet metrics are now coming from a different port (. . .) we need to make sure it only goes out to clusters using k8s 1.20+

**Comment by deniseschannon** [comment]
@aiyengar2 Is this something we can change for the user in the chart templates? Where if it's a certain k8s version, we change the ports?

**Comment by aiyengar2** [comment]
@deniseschannon yes, we also currently do this for dashboards here https://github.com/rancher/charts/blob/5331c96a42a9a862afeaed440661a6d69a3dae40/charts/rancher-monitoring/rancher-monitoring/9.4.203-rc01/templates/grafana/dashboards/k8s-cluster-rsrc-use.yaml#L6

**Comment by aiyengar2** [comment]
Actually, I don't think any backend changes are necessary. I looked into the chart and just realized that we expose this field  [here](https://github.com/rancher/charts/blob/main/charts/rancher-monitoring/values.yaml#L1093) so it can be modified in the given `values.yaml` view of our already released chart.

@slickwarren can you test out the following workaround? If it works, I'll create a UI ticket to expose this field and automatically set it when the cluster version is detected to be k8s 1.20 (although users will have to manually change this on a helm upgrade).

#### Workaround

Set `kubelet.serviceMonitor.resourcePath=/metrics/resource`

**Comment by aiyengar2** [comment]
After talking to @vincent99, I decided to make the necessary changes on the backend to support this use case instead of relying on the UI to set these values.

@slickwarren I'm leaving this issue to test since I want to test the workaround mentioned in https://github.com/rancher/rancher/issues/31167#issuecomment-777692557 for Monitoring V2. Monitoring V1 has no workaround until we get the changes merged in.

Once they are merged in, you should be able to test the changes on Monitoring V2 version 9.4.203-rc02 (pending https://github.com/rancher/rancher/issues/31304) and Monitoring V1 version 0.2.1 (pending https://github.com/rancher/rancher/issues/31305).

@luthermonson @superseb I also created and closed two issues tagged for this release to 1) call out the fact that this issue is related to k8s 1.20 clusters in general, not jut OL 8.3 and 2) make it easier for users to find out the workaround / chart upgrade necessary if they encounter these issues in any k8s 1.20 cluster. 

We need to make sure the release notes include the comments mentioned on those tickets so that k8s 1.20 users can know what version of monitoring they need to upgrade to in order to have a proper setup.

**Comment by slickwarren** [comment]
I was able to confirm the workaround for monitoring v2 :
<img width="601" alt="Screen Shot 2021-02-12 at 2 10 06 PM" src="https://user-images.githubusercontent.com/16691014/107828576-fffaef00-6d3d-11eb-988b-767204247a25.png">

**Comment by aiyengar2** [comment]
@slickwarren as mentioned above, now that the PRs are merged we need to test the changes on k8s 1.20 clusters with Monitoring V2 version 9.4.203-rc02 and Monitoring V1 version 0.2.1

**Comment by slickwarren** [comment]
on 2.5 head (96dc206633a286c5fbae8d5240fa9354a88b823b) and master-head (f69f96b) using monitoring v2 version 9.4.203-rc02, all targets are now up and all other p0 tests passed 🎉 

however on the same rancher versions for 2.5-head and master-head, monitoring v1 version 0.2.1 never fully initiates and is stuck in `Monitoring API is not ready` on rancher UI.  looking at the server logs, there are some errors reported: 

```
[ERROR] error syncing '<cluster_id>': handler cluster-monitoring-handler: failed to get cattle-prometheus/prometheus-operated endpoints: endpoints "cattle-prometheus/prometheus-operated" not found, requeuing
[ERROR] error syncing '<project>/cluster-monitoring': handler helm-controller: wait helm template failed. Error: render error in "rancher-monitoring/charts/exporter-kubelets/templates/servicemonitor.yaml": template: rancher-monitoring/charts/exporter-kubelets/templates/servicemonitor.yaml:90:13: executing "rancher-monitoring/charts/exporter-kubelets/templates/servicemonitor.yaml" at <include "kubelet.serviceMonitor.resourcePath" .>: error calling include: template: rancher-monitoring/charts/exporter-kubelets/templates/_helpers.tpl:3:14: executing "kubelet.serviceMonitor.resourcePath" at <.Values.kubelet.serviceMonitor.resourcePath>: nil pointer evaluating interface {}.serviceMonitor
: exit status 1, requeuing

```

**Comment by slickwarren** [comment]
master-2bccb50ce1c6d45c59fea8e5d114b18f3e89a80d-head and v2.5-96dc206633a286c5fbae8d5240fa9354a88b823b-head
now have all targets up using monitoring v1 v0.2.1, and all other p0 tests passed
