### ISSUE TITLE
Cluster goes into Updating state when no action is performed on the cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31168]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- This rancher server - 2.5-head commit id: `8201e080` has been running for 40 hours.
- A Do cluster - 1 node - k8s 1.20.2-rancher2-1 is deployed and is running.
- An EKS v2 cluster is deployed.
- Deployed another EKS v2 cluster. And the cluster is in provisioning state when the DO cluster goes into Updating state.
- No action was performed on the DO cluster.
- It reconciles and come back Active. 

**Expected Result:**
It should not go into an Updating state.

**Other details that may be helpful:**

- This may not be always reproducible.
- Contact me for the logs

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `8201e080` 
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO rke
- Kubernetes version (use `kubectl version`):

```
1.20
```

- Docker version (use `docker version`):

```
19.3.15
```

**Comment by rmweir** [comment]
After looking at thee logs it seems that metadata refresh ran and detected an update for RKE system images. This would cause the provisioner handler to update the RKE cluster once it is entered. I am still figuring out what would have triggered the RKE cluster.

**Comment by sowmyav27** [comment]
Closing this based on comments - https://github.com/rancher/rancher/issues/31168#issuecomment-777155020
