### ISSUE TITLE
[UI] vSphere cluster provisioning

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#31162]
Starting 2.5.6, the out-of-tree vSphere CPI+CSI can be used for the vSphere clusters. With this, the UI for cluster creation page when vSphere node driver is selected should have the following changes:
Under **Cloud provider**:
- [x] Rename In-Tree Cloud provider => Cloud Provider
- [x] Indicate "In-Tree" on options that are In Tree
- [ ] ~Put a warning for In-Tree indicating that it's deprecated~. - We have decided to remove this warning as the statement of in-tree is in the info section. 
- [x] Add messaging "out of tree cloud provider for vsphere is available through the vsphere-csi/cpi helm charts."
   - Custom and Vsphere drivers
   - Remove the please edit messaging from the vsphere driver

https://github.com/rancher/rancher/issues/23357

**Comment by gaktive** [comment]
If there are questions, ping @deniseschannon for context.

**Comment by codyrancher** [comment]
@mrajashree 
1. Does 'Remove the Custom option' refer to removing the Custom attributes accordion?
![image](https://user-images.githubusercontent.com/55104481/107693797-d5d8fc80-6c6b-11eb-9665-875ffe9ed7a9.png)

2. Do we just want links labeled CPI and CSI or is there more context that we can provide?

**Comment by deniseschannon** [comment]
No, this is only related to the cloud provider sections. @codyrancher 

Let's discuss.

**Comment by deniseschannon** [comment]
@sadiapoddar @bmdepesa When you test this change, can you please review the Cloud provider section for Custom drivers and every other node provisioning option to ensure we are showing the correct items in that section?

**Comment by sadiapoddar** [comment]
Verified on 2.5-head, 03b8153
Test1 
1. Selected custom (in-tree) provider and also noticed the in-tree deprecation warning and message. 
2. provided the cloud provider config in cluster YMAL and
3. Created the cluster as in-tree

Test2
1. Selected "external" for creating an out-of-tree and noticed a warning which is not relevant. Instead we can say the requirement as "After creating an external cluster, install cpi and csi driver to make out-of-tree  ...... " 
I am not sure about the exact wording but I listed the workflow below, we need to communicate that with the users.

<img width="1170" alt="Screen Shot 2021-02-18 at 6 14 49 PM" src="https://user-images.githubusercontent.com/72409237/108448284-435dcd80-7216-11eb-8d53-f412f502c980.png">

2. The links for CPI and CSI driver are misleading during creating a cluster, these driver needs to be installed once the external cluster is created and ready. Also, there is some dependency between these drivers. CPI needs to installed first, after installation is complete, we need to check if all the nodes are marked with the vSphere provider information before we can start installing CSI driver. 

**The right workflow for the external (out-of-tree) are as follows**

1. create a cluster by selecting external, 
<img width="243" alt="Screen Shot 2021-02-18 at 6 06 07 PM" src="https://user-images.githubusercontent.com/72409237/108448456-99327580-7216-11eb-88aa-60c0292ae6c6.png">

2. Once the cluster is up, install CPI driver 
3. Chek all the nodes are marked with the vSphere provider information
```
kubectl describe nodes | grep "ProviderID"
```
4. Then install CSI driver


Reopening this bug, we need to remove the CPI and CSI driver link from the cluster creation page and change the warning message.

**Comment by sowmyav27** [comment]
To validate: warning that "in-tree cloud providers are deprecated" is not available anymore

**Comment by deniseschannon** [comment]
- [ ] Update text for the "External" option to "External (Out-of-tree)"

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 30e53bd
rancher/rancher:master-head 465bb3b

In add cluster:
* vSphere - External option is indicated as out-of-tree and a message about installing `vsphere-cpi-driver` and `vsphere-csi-driver` is shown, the message about editing YAML is not shown
* "in-tree cloud providers are deprecated" warning is no longer shown
* "External (Out-of-tree)" is shown correctly on external providers
* In tree providers are correctly indicated as in-tree for Azure and AWS clusters. Linode & DO cloud provider options are "Custom" and "External" (this was the previous behavior as well)
* Custom clusters have all options presented

vSphere:
* Created a vSphere cluster selecting "External (Out-of-tree)" 
* Installed `vsphere-cpi-driver` and `vsphere-csi-driver` charts
* Provisioned a volume attached to a workload from the CSI storage class successfully

Azure:
![Screen Shot 2021-02-24 at 4 47 31 PM](https://user-images.githubusercontent.com/21316915/109082377-1a7b8380-76c1-11eb-819e-dbc0d395b0d4.png)
AWS:
![Screen Shot 2021-02-24 at 4 46 54 PM](https://user-images.githubusercontent.com/21316915/109082378-1bacb080-76c1-11eb-9952-4d4f13a92a95.png)
vSphere:
![Screen Shot 2021-02-24 at 4 45 43 PM](https://user-images.githubusercontent.com/21316915/109082383-1bacb080-76c1-11eb-80bd-034321740cdf.png)
Custom:
![Screen Shot 2021-02-24 at 4 57 58 PM](https://user-images.githubusercontent.com/21316915/109082646-9bd31600-76c1-11eb-8608-be94ca28fcdb.png)
