### ISSUE TITLE
Backport: Sporadic driver error during K8s upgrade: listen tcp 127.0.0.1:0: bind: address already in use

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#31160]
https://github.com/rancher/rancher/issues/28360

We need to update to the latest telemetry version in v2.4.

**Comment by izaac** [comment]
Rancher version `v2.4-head (02/08/2021)`  _94efb14b9_
 I was able to check this with the steps provided https://github.com/rancher/rancher/issues/28360#issuecomment-771134043 

I see the number of connections is kept steadily low even after multiple request to the report endpoint.
I also validated the /v1-telemetry endpoint was properly updated after adding clusters.

**Comment by izaac** [comment]
```
root@bc51f17523fc:/var/lib/rancher# env  |grep -i tele
TELEMETRY_VERSION=v0.5.14
```
