### ISSUE TITLE
Import EKS v2 cluster is stuck in Waiting state with message "Cluster must have at least one managed nodegroup."

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31170]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create an EKS cluster in the EKS console. Do not add any nodegroups yet
- Import this cluster in rancher. 
- Cluster will be stuck in Waiting state with message `Cluster must have at least one managed nodegroup.`
- Add a nodegroup in the cluster from the EKS console.
- The nodegroups are seen on the "Nodes" page in Rancher. But Edit cluster do not show the nodegroups
- The cluster is seen stuck in Waiting state with message "Cluster must have at least one managed nodegroup."
- Eks-operator logs say `time="2021-02-06T00:04:11Z" level=info msg="cluster [c-8d6w7] finished updating"`

**Expected Result:**
Cluster should come up Active

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): on 2.5-head - commit id: `8201e080`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Import EKS v2
- Kubernetes version (use `kubectl version`):

```
1.18 (Any)
```

**Comment by sowmyav27** [comment]
On 2.5-head, cannot reproduce this issue. Closing this for now. Will log a new one if I see this issue again.

**Comment by leppaott** [comment]
This is happening on rancher-stable. Can someone point to documentation on why "Cluster must have at least one managed nodegroup."?

I imported existing EKS cluster with unmanaged nodegroups: and everything what I need seems to be working fine so why the warning?

**Comment by rmweir** [comment]
The documentation may not elaborate but basically we cannot confirm whether the cluster has nodegroups through the api unless they are managed nodegroups. We need to confirm there is a nodegroup to make sure the rancher agent can be deployed.

**Comment by rmweir** [comment]
@leppaott the documentation may not elaborate but basically we cannot confirm whether the cluster has nodegroups through the api unless they are managed nodegroups. We need to confirm there is a nodegroup to make sure the rancher agent can be deployed.

**Comment by jonathanribas** [comment]
Hi, we have same issue here on 2.5.6.

1/ Due to AWS North Virgina service outage yesterday, Rancher deleted automatically all our Node Groups, so our services went down.

We had to manually recreate Node Groups from AWS Console as Rancher UI was displaying "Cluster must have at least one managed nodegroup.". After creating them manually, Rancher UI still displays the same message, it seems a link is broken somewhere inside Rancher database.

2/ Do you guys know in which cases Rancher can ask for a Node Group deletion?

**Comment by Vitorspk** [comment]
Hi, we have the same issue on 2.5.8.

**Comment by zakariarain** [comment]
We have the same issue with 2.6.3

**Comment by zakariarain** [comment]
Same issue with 2.6.2

**Comment by Leen15** [comment]
We have the same issue. Any workaround?

**Comment by SharpThunder** [comment]
Same issue still continues opened new issue in #36465

**Comment by FuzzyPickle** [comment]
I am seeing this issue where the cluster seems to be working but Rancher says:

```
This cluster is currently Waiting.

Cluster must have at least one managed nodegroup.
```
It will flip to active temporarily then back to this "Waiting" message.  

AWS EKS 1.21.5-eks-9017834

**Comment by sgran** [comment]
> We need to confirm there is a nodegroup to make sure the rancher agent can be deployed.

Why?  Why can't you rely on the nodes API if you need to check for capacity?

**Comment by thedadams** [comment]
In EKS, user workloads cannot be scheduled on control plane nodes. In addition, unmanaged nodes aren't accessible in the EKS API.

While Rancher might be able to see unmanaged nodes, eks-operator, the operator that communicates with EKS, does so strictly through the API.

**Comment by juanpciceri** [comment]
Ive got a cluster where there is an active nodegroup but still Im receving the same error. @thedadams @sowmyav27  can you help me?
