### ISSUE TITLE
Glusterfs server cannot rejoin cluster after restart container

### ISSUE THREAD

**Issue by CBR09** [rancher/rancher#3117]
Hello @cjellick, @ibuildthecloud
Using the default compose template, I was able create glusterfs cluster successfully. However, when I tried to restart one of these servers container, it couldn't rejoin cluster. The error logs's shown as below:

>12/22/2015 10:31:59 AM/opt/rancher/common.sh: line 5: [: : integer expression expected
12/22/2015 10:31:59 AMContainers are starting...
12/22/2015 10:31:59 AMWaiting for Gluster Daemons to come up
12/22/2015 10:32:30 AM/opt/rancher/peerprobe.sh: line 39: [: : integer expression expected
12/22/2015 10:32:45 AM/opt/rancher/peerprobe.sh: line 39: [: : integer expression expected
12/22/2015 10:33:00 AM/opt/rancher/peerprobe.sh: line 39: [: : integer expression expected
12/22/2015 10:33:15 AM/opt/rancher/peerprobe.sh: line 39: [: : integer expression expected

My envoriment:
RancherOS 0.4.1
Rancher 0.50.2

Thanks

**Comment by will-chan** [comment]
@cloudnautique can you look into this?

**Comment by yobasystems** [comment]
Any info on this? I'm also running into these errors.

    22/01/2016 14:17:10/opt/rancher/peerprobe.sh: line 39: [: : integer expression expected

**Comment by onjin** [comment]
it looks this container cannot connect to gluster daemon
```
sh-4.2# gluster pool list
Connection failed. Please check if gluster daemon is operational.
```

**Comment by yobasystems** [comment]
Fresh install of rancher server, fresh ubuntu 15.10 hosts with docker version 1.9.1. All hosts added, glusterfs deployed and active. Convoy from template 0.2 deployed and getting this error:

`05/02/2016 12:30:14Waiting for metadata...........
05/02/2016 12:30:14Could not reach metadata.`

**Comment by deniseschannon** [comment]
We have removed GlusterFS from the catalog as users were expecting a robust tool as an alternative persistent storage for Docker volumes.  

Closing this issue.
