### ISSUE TITLE
After upgrade to rancher 2.5.5, cattle-cluster-agent still misbehaves

### ISSUE THREAD

**Issue by horihel** [rancher/rancher#31177]
**What kind of request is this (question/bug/enhancement/feature request):**
This is a continuation of issue #30048, which was closed apparently because a different similar looking problem was resolved. Unfortunately the issue still exists.
to rule out problems with project network isolation, this cluster has been running without it since the last bug report - no change in upgrade behaviour though. It's still impossible to upgrade to 2.5.x without running into this problem.

**Steps to reproduce (least amount of steps as possible):**
1. Have a rancher and a few clusters (in my case running 2.4.12)
2. upgrade to 2.5.5
3. watch during the update cattle-cluster-agent starts to misbehave, causing serious cpu and network usage.

**Result:**
in addition to the charts mentioned in the other bugs, i also looked at networking and you can easily see the massive change in behaviour of cluster-agent between 2.4.12 and 2.5.5:
![grafik](https://user-images.githubusercontent.com/6735079/107186063-e0816080-69e3-11eb-85a0-122acd3e4441.png)

Notable changes in api-controller metrics too:
![grafik](https://user-images.githubusercontent.com/6735079/107186188-14f51c80-69e4-11eb-954e-1106d96a31ca.png)

The one apiserver container it selected is seriously impacted:
![grafik](https://user-images.githubusercontent.com/6735079/107186258-33f3ae80-69e4-11eb-97cc-bbf8b34a7d33.png)

And cluster-agent itself has become tremendously hungry:
![grafik](https://user-images.githubusercontent.com/6735079/107186325-5685c780-69e4-11eb-844e-82586bcf5f6c.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.5.5

- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Vsphere hosted and Custom (bare metal)

- Machine type (cloud/VM/metal) and specifications (CPU/memory):

VMs, 16GB, 4CPU each, 3 mgmt, 6 workers

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
[docker@k8s-development-v4-mgmt1 ~]$ docker version
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275
 Built:             Tue Dec  1 19:14:24 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275
  Built:            Tue Dec  1 19:21:08 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by horihel** [comment]
had to rollback to 2.4.12 - but if i can get a hint where to find more clues about what's going wrong, i can schedule an upgrade again. 
I couldn't find anything in the logs that stood out enough for me to point to the problem.
this does not seem to happen with fresh clusters, only these two fairly old clusters seem to have the problem.

**Comment by wontfixthis** [comment]
Same Problem with Rancher 2.5.2 after upgrading from 2.4.3

**Comment by horihel** [comment]
@wontfixthis i have the hopes that v2.5.6 could fix the problem, because #30168 _looks_ similar.

i'll try to find time to test this soon.

**Comment by Tejeev** [comment]
@horihel have you had the opportunity to test with v2.5.6 or later yet?

**Comment by horihel** [comment]
He @Tejeev  - yes - we're on 2.5.8 now and the problem disappeared. 
In the end it seems to have been related to helm2 remnants in the kube-system namespace which cattle-agent couldn't digest.

**Comment by rchench** [comment]
we have rancher 2.5.9 installed in HA mode. Some downstream clusters (also HA) kube-apiservers (all imported) are experiencing high CPU and OOM kill, then eventually died. Via the apiserver pprof, it shows that CPU spent most of time in constructing something related to rancher apps/catalogs. Stops rancher-cluster-agent in the downstream cluster, it goes back to normal. So:

- the issue still exists in 2.5.9
- it does not happen for all clusters, but quite annoying for those impacted clusters. 
- suspect to be the new "App Marketplace" feature in cluster explorer and it tries to pull all apps from the cluster regardless if it is installed via Rancher or not. not able to turn it off
- the helm charts installed in the downstream cluster may not be perfect (especially those upgraded from helm2 to helm3), but rancher at least shall have a mechanism to stop processing it rather than drive the apiserver crazy. it is similar to the app catalogs feature in 2.4.x. if the helm repo does not fulfill the rancher requirement, it shall not keep pulling till triggering OOM kill.

Suggest to re-open the issue and continue the triage and fix.

**Comment by Tejeev** [comment]
@rchench  Could you please open a new issue with your findings and referencing this one?
