### ISSUE TITLE
cant remove app rancher-logging monitoring-oprator after upgrading to 2.5.5

### ISSUE THREAD

**Issue by chuegel** [rancher/rancher#31179]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Not sure. We migrated from 2.4.8 to 2.5.5 and those two apps are constantly re-deployed to the cluster after deleting them.
Monitoring is disabled in Cluster Manager

**Result:**
<img width="1156" alt="grafik" src="https://user-images.githubusercontent.com/6955465/107198592-92755880-69f5-11eb-927a-2f8af1ff44f8.png">

<img width="1278" alt="grafik" src="https://user-images.githubusercontent.com/6955465/107198801-dbc5a800-69f5-11eb-9f7d-d86e1e34beab.png">

How can I completely remove rancher-logging and monitoring-operator app from the cluster?

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMs
- Kubernetes version (use `kubectl version`): 

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
 docker version
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:48 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:16:13 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by chuegel** [comment]
I overlooked a project monitoring instance. Removed it and now the app could be uninstalled

**Comment by oscarsix** [comment]
I have the same issue. Cant remove the App "rancher-monitoring" after upgrading to 2.5.5

monitoring-operator   rancher-monitoring   0.2.0     monitoring-operator   2                 deployed

What did you removed ?
