### ISSUE TITLE
Unable to use spot instances in EKS clusters

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#31194]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create an EKS cluster in Rancher.
During Node group creation, leave Launch Template field blank.
Enable `Request Spot Instances`
![Screen Shot 2021-02-08 at 4 40 25 PM](https://user-images.githubusercontent.com/57409052/107295769-4d6d1880-6a2d-11eb-97e6-31b24f1340b8.png)
Create cluster.

**Result:**
Cluster goes into error state. Errors with: `Nodegroup [aaron-test-spot2] in cluster [c-7mxrz]: spotInstanceTypes must be specified when requesting spot instances`
![Screen Shot 2021-02-08 at 4 40 46 PM](https://user-images.githubusercontent.com/57409052/107298110-fae22b00-6a31-11eb-9c69-441dc6917ecd.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `version v2.5-4cb2ebe2` and `master-head 86600ea`
- Installation option (single install/HA): Single install

**Comment by aaronRancher** [comment]
This behavior is also seen when requesting spot instances using a preexisting template.

**Comment by thedadams** [comment]
@aaronRancher This is the expected behavior. The user must specify instance types (in about the middle of the node group config)

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `dba332111`**

- Create a hosted EKS cluster with rancher managed Launch template with spot instances ON.
- The cluster is created successfully.
- And the instances are of type: Spot.
- - Edit cluster --> On the UI this is set
```
Request Spot Instances
Yes
```
