### ISSUE TITLE
No scroll bar in EKS User Data field

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#31197]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
In Rancher, create an EKS cluster
During Node Group creation, observe User Data field.
![Screen Shot 2021-02-08 at 6 10 41 PM](https://user-images.githubusercontent.com/57409052/107301674-27e60c00-6a39-11eb-9942-799832d5ebbc.png)

**Result:**
There is no scroll bar. The only way to navigate through user data is through arrow keys.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `version v2.5-4cb2ebe2` and `master-head 86600ea`
- Installation option (single install/HA): Single install

**Comment by aaronRancher** [comment]
Tested with `rancher\rancher:master-head` `version 990c1ad` and `rancher\rancher:v2.5-head` `version 8b65a6a`

No scroll bar in EKS node group user data field.
![Screen Shot 2021-02-11 at 11 23 55 AM](https://user-images.githubusercontent.com/57409052/107684503-20547c00-6c60-11eb-98b8-1ed7be7a40d9.png)
Reopening for fix.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `3e96d7f` and master-head commit id: `9ef8e69`**

user data field is scrollable.
<img width="796" alt="Screen Shot 2021-02-14 at 5 28 16 PM" src="https://user-images.githubusercontent.com/26032343/107896344-d9c68200-6eea-11eb-8ffe-1e754f24cb64.png">
