### ISSUE TITLE
Rancher v2.5 fleet and rancher-operator namespaces created outside any project

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#31209]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Deploy Rancher v2.5.5 into an RKE cluster
2. View Projects/Namespaces

**Result:**

Observe cluster-fleet-local-local-*, fleet-clusters-system, fleet-default, fleet-local and rancher-operator-system Namespaces that exist outside of any project, per the screenshot below. Can these be created within the System project by default?

![Screenshot from 2021-02-09 16-50-10](https://user-images.githubusercontent.com/9771530/107393438-18c79280-6afb-11eb-816b-8991e6addc19.png)

**Environment information**
- Rancher v2.5.5

**Comment by kinarashah** [comment]
Links to refer: 
List of system namespaces:  https://github.com/rancher/rancher/blob/master/pkg/settings/setting.go#L63 
Controller adding system annotation to namespace on create: https://github.com/rancher/rancher/blob/master/pkg/controllers/managementuser/rbac/namespace_handler.go#L62

**Comment by thehejik** [comment]
The same thing happens in rancher `2.5.6-rc5`

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.5.5**

- Deploy a Rancher HA setup with RKE local cluster.
- These namespaces are not in any project
<img width="1284" alt="Screen Shot 2021-06-15 at 1 02 57 PM" src="https://user-images.githubusercontent.com/26032343/122116150-214a1580-cdda-11eb-9036-71252ffe7795.png">

**On master-head commit id: `2b50005ae `**
- Except for fleet-system, all other namespaces have been moved under System Project
<img width="1291" alt="Screen Shot 2021-06-15 at 1 04 18 PM" src="https://user-images.githubusercontent.com/26032343/122116490-8867ca00-cdda-11eb-86c8-7ee58cabd830.png">

**Comment by sowmyav27** [comment]
Blocked because of https://github.com/rancher/rancher/issues/33203

**Comment by StrongMonkey** [comment]
Should be ready to test since #33203 is fixed and ready to test too.

**Comment by sowmyav27** [comment]
Will validate after this issue is fixed - https://github.com/rancher/rancher/issues/33677

**Comment by sowmyav27** [comment]
Waiting for this issue to be fixed - https://github.com/rancher/rancher/issues/33203

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to v2.6-head commit id: `c10ef4b0`**

- On 2.5.9 deploy a couple of downstream cluster
- Upgrade to 2.6head
- Rancher operator namespace is not available anymore.
- Fleet-system and cattle-fleet-system namespaces and other fleet related namespaces are seen in System project
<img width="1350" alt="Screen Shot 2021-08-17 at 9 35 43 PM" src="https://user-images.githubusercontent.com/26032343/129838236-847e38b4-764f-4f17-89a9-0b342f1577ff.png">
