### ISSUE TITLE
Authorization Cluster Endpoint (not working for me, not sure if I am doing something wrong)

### ISSUE THREAD

**Issue by anissmajlovic** [rancher/rancher#31201]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
First time when I deployed Kubernetes cluster using Rancher 2.5.5 I deployed cluster with Authorization Cluster Endpoint disabled. To be honest when I did first time Kubernetes deployment I was not sure what is Authorization Cluster Endpoint and now when I know I decided that I need that feature (basically to authenticate with Kubernetes cluster without Rancher).
To enable Authorization Cluster Endpoint I created a RKE Template with Enable Authorization Cluster Endpoint, and then update cluster with new template version. 

**Result:**
Now, when I download config file using Rancher UI, I can see authorization for each Master nodes and Rancher. However when I tried to use command with specific context (one of master nodes):
kubectl --context CLUSTER-NAME-NODENAME get nodes
First hang and after sometime I would receive message below:
Unable to connect to the server: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
- Rancher 2.5.5:latest
- HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by smajlovica** [comment]
Hello

Small update:
if I change in kubernetes config file public IP for example https://192.168.26.11:6443 to https://127.0.0.1:6443, then is working fine -- of course I have to be on master node to do this.

How can I change that I can use public IP instead of local 127.0.0.1 IP?

Thanks

**Comment by smajlovica** [comment]
I found solution, problem was with proxy in OS.

Thanks
