### ISSUE TITLE
Duplicate host entry after dist-upgrade

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#3120]
<img width="633" alt="screen shot 2015-12-22 at 4 04 45 am" src="https://cloud.githubusercontent.com/assets/5386568/11952871/7227909e-a861-11e5-94b1-0e1853aa4ca2.png">

After running a dist-upgrade to Ubuntu 15.04, I had to do some strange maneuvers with the rancher-agent image. Afterwards this happened. 

This happened after another dist-upgrade, but I didn't have to do anything strange with the agent.

**Comment by vincent99** [comment]
Showing up as a new host would suggest that `/var/lib/rancher/state/` is getting wiped out somehow.

**Comment by willseward** [comment]
Strange, I'll try to repro this is report back

**Comment by deniseschannon** [comment]
@willseward If you are still having this issue, please re-open.
