### ISSUE TITLE
OPA Gatekeeper - Remove experimental tag

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#31203]
Currently OPA still has the experimental flag on it. 

We should remove the annotation in the chart to remove marking it experimental.

**Comment by aaronRancher** [comment]
Validated on Rancher server `rancher\rancher:v2.5-head` `version 03b8153`

Experimental tag is no longer seen on OPA Gatekeeper:
![Screen Shot 2021-02-17 at 3 23 43 PM](https://user-images.githubusercontent.com/57409052/108275829-251fa100-7134-11eb-9b95-d57aeb774e43.png)

Old experimental tag:
![Screen Shot 2021-02-17 at 2 48 20 PM](https://user-images.githubusercontent.com/57409052/108275741-04574b80-7134-11eb-90c7-92b8f7895b88.png)
