### ISSUE TITLE
[gdapi-python] old requirements

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#3121]
Hi,

I can't use `cattle-cli` in my project, due to conflicting version requirements for the `requests` package.

Any reason why the `setup.py` file is so hard-wired to a specific version, by using the requirements.txt file ?

**Comment by vincent99** [comment]
I think we just suck at python... Want to put in a PR? :-)

**Comment by kaos** [comment]
Ok, will do :)
In the mean time.. https://caremad.io/2013/07/setup-vs-requirement/
