### ISSUE TITLE
[EKSv2] Make spot instance types more obvious

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#31213]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Create an EKS cluster and enable "Request Spot Instances" for a node group

**Result:**
1. The "Instance type" section is greyed out and the "Additional Instance Types" section appears.

**Other details that may be helpful:**
It should be more obvious that the user must add instance types to "Additional Instance Types."
Perhaps:
1. the name of the this section should change to "Spot Instance Types" and should be required
2. the "Instance type" dropdown should disappear instead of greyed out to emphasize that it will not be used.

**Comment by westlywright** [comment]
I've removed the instance type selector and replaced it with the warning that was there before. I also made spot instance types required if request spot instances is set.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `3e96d7f` and master-head commit id: `9ef8e69`**

- Create a hosted EKS cluster.
- Warning is seen when Spot instances is enabled/set to True

<img width="1229" alt="Screen Shot 2021-02-14 at 5 23 19 PM" src="https://user-images.githubusercontent.com/26032343/107895764-58222480-6ee9-11eb-86f7-33c9a537ed07.png">

- When Spot instances is enabled, and no spot instance types is given error seen on UI: `Node Groups requesting spot instances must include one or more spot instance types.`
