### ISSUE TITLE
Add feature flag for token hashing and make it opt-in functionality

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#31214]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Description:**
* ~~Add a setting for opting into token hashing.~~ 
* Set opt-in setting to false.
* Implement logic to only hash tokens if user has opted in.
* Once opted in, token hashing should be permanent and non reversible.

**Comment by sowmyav27** [comment]
**On master-head commit id: `4d41301`**

- Deploy a downstream cluster and a kubeconfig token.
- Activate Token hashing
- All tokens get hashed

```
authn.management.cattle.io/token-hashed: "true"
      authn.management.cattle.io/token-userId: u-mo773yttt4
            f:authn.management.cattle.io/token-hashed: {}
            f:authn.management.cattle.io/token-userId: {}
        f:token: {}
  token: $2:6PNSxvFY5hA:h9mD2JTEiOAnuOwuI7fVOxr9NTi7sZpe6nymay7rTN8
```
- Deactivate the token hashing feature. Error seen - `{"baseType":"error","code":"InvalidBodyContent","message":"feature flag cannot be changed from current value: true","status":422,"type":"error"}`
