### ISSUE TITLE
Private repository image xxx/yyy/zzz

### ISSUE THREAD

**Issue by Stapelpanda** [rancher/rancher#3122]
While using a private repository with Rancher i ran into a problem, when adding an URL with more than two parts rancher shows an 422 error regarding the ImageUUID.

Example config:

```
**docker-compose.yml**
node1:
  image: private.repository.url:5000/tools/common/chat
```

**Comment by prachidamle** [comment]
@will-chan moving to 1.1 as discussed

**Comment by guzmo** [comment]
This is a show stopper for us since we cant have all our images in a big pile. Is it prioritized?

**Comment by deniseschannon** [comment]
It is currently set to be in our next stable release (v1.1). You can always look at the milestone to see which release it's expected to land in. 

Please note that based on different priorities, the milestone could change later.

**Comment by deniseschannon** [comment]
@StrongMonkey This may be the same issue as https://github.com/rancher/rancher/issues/5025

**Comment by soumyalj** [comment]
Tested with rancher v1.2.0-pre4-rc7. Able to create containers with private repository images below : 
1. 605812595399.dkr.ecr.us-east-1.amazonaws.com/soumyatestrepo:v1
2. 605812595399.dkr.ecr.us-east-1.amazonaws.com/soumya/namespace1/namespace2:latest
3. localhost:5000/ubuntu
4. localhost:5000/foo/bar/ubuntu
