### ISSUE TITLE
[v2.5] KDM release: k8s feb patches

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#31222]
This KDM release is going out with Rancher `v2.5.6` release for new k8s versions: v1.17.18, v1.18.16, v1.19.8 and v1.20.3.

- There are existing k8s versions in `dev-v2.5` that haven't been released (absent in `release-v2.5`), so the same versions can be updated. Following versions need to be updated with their compatible rancher server versions: 

| update [version](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/k8s_rke_system_images.go#L3590) from | to | update [rancher version constraints]( https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/rke/k8s_version_info.go#L278) 
| --------------- | --------------- | -----------| 
| v1.20.2-rancher2-1 | v1.20.3-rancher1-1 | 2.5.6+ | 
| v1.19.7-rancher2-1 | v1.19.8-rancher1-1 |  2.5.0+ | 
| v1.18.15-rancher2-1 | v1.18.16-rancher1-1 | 2.4.5+ | 
|v1.17.17-rancher2-1 | v1.17.18-rancher1-1 | 2.4.4+ | 

- Following [system images](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/k8s_rke_system_images.go) need to be updated: 

| Name | Kubernetes Version |  Version |
| ------ | ------ | ------| 
| windowsPodInfra | v1.20.3 | v0.1.6 | 

- [Update constraints for all addon versions](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) so the new Kubernetes versions use the right template. Refer to the table below to confirm the template name. 

<details>
<summary> Confirm the versions for System Images and Addon templates are correct. Update this table if new versions get introduced. Click to view the full list. </summary>

| Name | Kubernetes Version |  Version | [Update constraints for addon versions](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) if required | 
| ------ | ------ | ------| ---- | 
| etcd |  1.17.18, v1.18.16 | v3.4.3-rancher1 | 
| etcd | v1.19.8 | v3.4.13-rancher1 | 
| etcd | v1.20.3 | v3.4.14-rancher1 | 
|  | 
| kube-dns | v1.17.18 | v1.15.0 |  kubeDnsv116
| kube-dns |  v1.18.16 | v1.15.2 | kubeDnsv116
| kube-dns |  v1.19.8, v1.20.3 | v1.15.10 | kubeDnsv116 
|  | 
| core-dns| v1.17.18 | v1.6.5 | coreDnsv117
| core-dns| v1.18.16 | v1.6.9 | coreDnsv117
| core-dns| v1.19.8 | v1.7.0 | coreDnsv117
| core-dns| v1.20.3 | v1.8.0 | coreDnsv117 
|  | 
| flannel | v1.17.18, v1.18.16 | v0.12.0| flannelv116
| flannel | v1.19.8, v1.20.3 | v0.13.0| flannelv116 
|  | 
| calico, canal |  v1.17.18, v1.18.16 | v3.13.4 | canalv117PrivilegedCalico3134, calicov117Privileged 
| calico, canal | v1.19.8 | v3.16.5 | canalv3165, calicov3165
| calico, canal | v1.20.3 | v3.7.2 |  canalv3171, calicov3171
|  | 
| weave | v1.17.18, v1.18.16 | v2.6.4 | weavev116
| weave | v1.19.8 | v2.7.0 | weavev116
| weave | v1.20.3 | v2.8.1 | weavev120
|  | 
| aci | all | 5.1.1.0.1ae238a | aciv500 
|  | 
| metrics-server | v1.17.18, v1.18.16, v1.19.8 | v0.3.6 | metricsServerv18
| metrics-server | v1.20.3 | v0.4.1 | metricsServerv120
|  | 
| podInfra | v1.17.18, v1.18.16 | 3.1 | 
| podInfra | v1.19.8, v1.20.3 | 3.2 | 
|  | 
| node local |  v1.17.18, v1.18.16 | 1.15.7| nodelocalv115
| node local | v1.19.8, v1.20.3 | 1.15.13 | nodelocalv115
|  | 
| rancher forks | 
| dns-autoscaler | v1.17.18, v1.18.16 | v1.7.1 | 
| dns-autoscaler | v1.19.8, v1.20.3 | v1.8.1 | 
|  | 
| flannel-cni | all | v0.3.0-rancher6 | 
|  | 
| ingress | v1.17.18, v1.18.16, v1.19.8 | nginx-0.35.0-rancher2 | nginxIngressV11512
| ingress | v1.20.3 | nginx-0.43.0-rancher1 | nginxIngressV11512
|  | 
| ingress-backend |  all | 1.5-rancher1 | 
|  | 
| rke-tools | all | v0.1.71 | 
| | 
| windowsPodInfra |  v1.17.18, v1.18.16, v1.19.8, v1.20.3 | v0.1.6 | 
</details>

**Comment by anupama2501** [comment]
Verifications on 2.5.6-rc5  – PASS
Spin up a rancher cluster with 2.5.6-rc5. 
Verified the metadata is pointing to dev-v2.5
KDM job pointing to dev-v2.5 for all the network providers on the k8s version v1.20.4-rancher1-1.
Once the job succeeds, ran network test cases on all the clusters - PASS
Ran validation test cases on the canal cluster - PASS



Verification on Rancher | v2.5.5 - PASS 
Spin up a rancher cluster with 2.5.6-rc5. 
Verified the metadata is pointing to release-v2.5 and updated it to dev-v2.5
KDM job pointing to dev-v2.5 for all the network providers on the k8s version v1.19.8-rancher1-1, v1.18.16-rancher1-1, v1.17.17-rancher2-1 for all the network providers.
Once the job succeeds, ran network test cases on all the clusters - PASS
Ran validation test cases on the canal cluster - PASS

**Comment by slickwarren** [comment]
Verification of Upgrade testing (v2.5.5) KDM -- PASS
* using rancher v2.5.5 with release-v2.5 KDM:
  * test downstream clusters on v1.19.7-rancher1-1 and v1.18.15-rancher1-1
  * run preupgrade checks PASS
  * change KDM to dev-v2.5 
  * upgrade all ds clusters by one patch version (v1.19.7-rancher1-1 or v1.18.16-rancher1-1)
  * run postupgrade checks (PASS -- one test failed, no signs it was related to version changes)
  * verified all other image versions matched expected version number (rke-tools, etcd, node local, ...)

Verification of Min checks (v2.5.3) KDM -- PASS
* using v2.5.3 pointing to dev-v2.5: 
  * test downstream clusters on the latest (v1.19.7-rancher1-1 and v1.18.16-rancher1-1)
  * run network tests (PASS -- one test failed, no signs it was related to KDM version)
  * verified all other image versions matched expected version number (rke-tools, etcd, node local, ...)

**Comment by sowmyav27** [comment]
Reopening this to check 1.17.7-rancher2-1 (rke tools version)

To validate:
- fresh install of 2.5.6-rc5 Deploy canal cluster with `1.17.7-rancher2-1` k8s version.
- Verify new rke-tools is available
- Run network checks on this cluster

**Comment by sowmyav27** [comment]
**On 2.5.5**

**Steps:**
- changed KDMDeploy canal cluster with `1.17.7-rancher2-1` k8s version.
- rke-tools available - `rancher/rke-tools v0.1.71`
- tests on the cluster look good
