### ISSUE TITLE
[v2.4] KDM release: k8s feb patches

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#31223]
This KDM release is going out with Rancher `v2.4.14` release for new k8s versions: v1.18.16.

- All existing k8s versions in `dev-v2.4` have been released (are present in `release-v2.4`) so we need to introduce new k8s versions. To introduce a new k8s version, basecopy the latest existing version in a separate commit, followed by another commit to update what's changed. Following versions need to be created with their compatible rancher server versions: 

| basecopy [version](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/k8s_rke_system_images.go#L3590) from | create | set [rancher version constraints]( https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/rke/k8s_version_info.go#L278) 
| --------------- | --------------- | -----------| 
| v1.18.15-rancher1-1 | v1.18.16-rancher1-1 | 2.4.5+ | 

Since k8s is not releasing a new `v1.17.18`, but we have rancher specific changes for v1.17, we'd still introduce a new version with suffix `rancher2-1`: 
| basecopy [version](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/k8s_rke_system_images.go#L3590) from | create | set [rancher version constraints]( https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/rke/k8s_version_info.go#L278) 
| --------------- | --------------- | -----------| 
|v1.17.17-rancher1-1 | v1.17.17-rancher2-1 | 2.4.4+ | 

- Following [system images](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/rke/k8s_rke_system_images.go) need to be updated: 

| Name | Kubernetes Version |  Version |
| ------ | ------ | ------| 
| windowsPodInfra | v1.17.17-rancher2-1, v1.18.16 | v0.1.6 | 
| rke-tools | v1.17.17-rancher2-1, v1.18.16 | v0.1.71

- Add docker version if a new docker version was introduced in [docker info](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/rke/k8s_docker_info.go) 

| Kubernetes Version | Docker Version |
| ------ | ------| 
| All versions in the file | 20.10.x | 

- [Update constraints for all addon versions](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) so the new Kubernetes versions use the right template. Refer to the table below to confirm the template name. 

<details>
<summary> Confirm the versions for System Images and Addon templates are correct. Update this table if new versions get introduced. Click to view the full list. </summary>

| Name | Kubernetes Version |  Version | [Update constraints for addon versions](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) if required | 
| ------ | ------ | ------| ---- | 
| etcd |  1.17.18, v1.18.16 | v3.4.3 | 
|  | 
| kube-dns | v1.17.18 | v1.15.0 |  kubeDnsv116
| kube-dns |  v1.18.16 | v1.15.2 | kubeDnsv116
|  | 
| core-dns| v1.17.18 | v1.6.5 | coreDnsv117
| core-dns| v1.18.16 | v1.6.9 | coreDnsv117
|  | 
| flannel | v1.17.18, v1.18.16 | v0.12.0| flannelv116
|  | 
| calico, canal |  v1.17.18, v1.18.16 | v3.13.4 | canalv117PrivilegedCalico3134, calicov117Privileged 
|  | 
| weave | v1.17.18, v1.18.16 | v2.6.4 | weavev116
|  | 
| aci | - | - | -  
|  | 
| metrics-server | v1.17.18, v1.18.16 | v0.3.6 | metricsServerv18
|  | 
| podInfra | v1.17.18, v1.18.16 | 3.1 | 
|  | 
| node local |  v1.17.18, v1.18.16 | 1.15.7| nodelocalv115
|  | 
| rancher forks | 
| dns-autoscaler | v1.17.18, v1.18.16 | v1.7.1 | 
|  | 
| flannel-cni | all | v0.3.0-rancher6 | 
|  | 
| ingress | v1.17.18, v1.18.16 | nginx-0.35.0-rancher2 | nginxIngressV11512
|  | 
| ingress-backend |  all | 1.5-rancher1 | 
|  | 
| rke-tools | all | v0.1.71 | 
| | 
| windowsPodInfra |  v1.17.18, v1.18.16 | v0.1.6 | 
</details>

**Comment by sowmyav27** [comment]
**Validated this scenario:**

- On 2.4.13 KDM job pointing to release-v2.4 in k8s 1.18.15
- Pre upgrade checks passed
- Upgrade KDM to dev-v2.4
- Upgrade K8s versions to new version - 1.18.16
- Post upgrade checks passed

**Comment by anupama2501** [comment]
Min checks on v2.4.5 - PASS

Spin up rancher on v2.4.5 and verify metadata config pointing to release-v2.4
Updated the metadata config pointing to release-v2.4 to dev-v2.4
KDM job for all network providers on the k8s version v1.18.16-rancher1-1


Validations on v2.4.14-rc1 fresh install  - PASS

Spin up rancher on v2.4.14-rc1 and verify metadata config pointing to release-v2.4
KDM job for all network providers on the k8s version v1.18.16-rancher1-1
Ran network related test cases on all the clusters - PASS
Ran validation test cases on canal cluster - PASS

Verified the rke-tools version v0.1.71 on the nodes of the clusters of v2.4.14-rc1 and v2.4.5

**Comment by sowmyav27** [comment]
Reopening this to check 1.17.7-rancher2-1 (rke tools version)

To validate:
- fresh install of 2.4.14-rc1, Deploy canal cluster with `1.17.7-rancher2-1` k8s version.
- Verify new rke-tools is available
- Run network checks on this cluster

**Comment by sowmyav27** [comment]
Reopening this for an update for 2.4 rke to support docker 20.10 version

**Comment by sowmyav27** [comment]
Verified the following:

- using rke `v1.1.15-rc3`, docker 20.10, rke checks for `v1.17.17-rancher2-1` 
- fresh install of 2.4-head - commitid: `c5f3d37ab`, Deploy canal cluster with 1.17.7-rancher2-1 k8s version.
- New rke-tools is available `rancher/rke-tools - v0.1.71`
- Validation checks on the cluster passed.
