### ISSUE TITLE
[UI][KEv2] UI for GKE v2 Provisioner

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#31221]
Feature: Similar to what was done for EKS (per https://zube.io/rancher/rancher/c/30415), we need a UI for the GKE v2 Provisioner.

It should be mostly identical though do note these small differences:
- Cloud Credentials need to be in place before setting up a GKE cluster 
- GKE should be able to rely on the proxy API but there's no REST API, just RPC
- We'll need an additional field for GCP Features though we'll keep it simple and rely on the spec. There's no backend toggle and we won't need things like Cloud TPU at this time. This could fall under a tab called Features
- GKE parlance uses Node Pools instead of Node Options and we can have multiples
- Private Clusters also behave differently so we need to careful to direct people to create a Public Cluster or a Private Cluster with Optional IP Ranges, otherwise we enter an air gap scenario
- Based on current backend Google endpoint communications needing to be preserved, we may need a parallel endpoint if we can't proxy using the existing one(s).

https://github.com/Klaven/gke-operator
https://github.com/Klaven/gke-operator/tree/init

**Comment by gaktive** [comment]
Backend should have this feature in a preliminary state to start looking at UI.

**Comment by westlywright** [comment]
@gaktive I am adding the waiting backend label to this for now. I had a conversation with @cmurphy to better grasp the status. It looks like the GKE operator work is done (or mostly) but the UI needs the operator to be pulled back into rancher/rancher via https://github.com/rancher/rancher/pull/31625. Once that is merged we can remove that label.

**Comment by gaktive** [comment]
@westlywright sounds good

**Comment by cmurphy** [comment]
Here's some information on all the parameters gke-operator supports and how they're intended to be used in the UI.

Also check the examples directory for more information: https://github.com/rancher/gke-operator/tree/master/examples

| Field                                           | Type                 | Mutable | Required for create | Proposed UI Default                   | Notes                                                                                                                                                                                            |         |                       |
|-------------------------------------------------|----------------------|---------|---------------------|---------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|-----------------------|
| autopilot                                       | boolean              | no      | yes                 | false                                 | requires clusterAddons.httpLoadBalancing=true and clusterAddons.horizontalPodAutoscaling=true and region=set and zone=unset; node pools will be ignored/should be []                             |         |                       |
| clusterAddons                                   | object               | yes     | yes                 | {}                                    |                                                                                                                                                                                                  |         |                       |
| clusterAddons.horizontalPodAutoscaling          | boolean              | yes     | no                  | true or unset                         |                                                                                                                                                                                                  |         |                       |
| clusterAddons.httpLoadBalancing                 | boolean              | yes     | no                  | true or unset                         |                                                                                                                                                                                                  |         |                       |
| clusterAddons.networkPolicyConfig               | boolean              | yes     | no                  | true or unset                         |                                                                                                                                                                                                  |         |                       |
| clusterIpv4Cidr                                 | string               | no      | yes                 | ""                                    | exclusive with ipAllocationPolicy.useIpAliases                                                                                                                                                   |         |                       |
| clusterName                                     | string               | no      | yes                 | user must provide                     |                                                                                                                                                                                                  |         |                       |
| description                                     | string               | no      | yes                 | ""                                    |                                                                                                                                                                                                  |         |                       |
| enableKubernetesAlpha                           | boolean              | no      | yes                 | false                                 |                                                                                                                                                                                                  |         |                       |
| googleCredentialSecret                          | string               | yes     | yes                 | user must select                      |                                                                                                                                                                                                  |         |                       |
| imported                                        | boolean              | no      | yes                 | false                                 |                                                                                                                                                                                                  |         |                       |
| ipAllocationPolicy                              | object               | no      | yes                 | {useIpAliases=true}                   |                                                                                                                                                                                                  |         |                       |
| ipAllocationPolicy.clusterIpv4CidrBlock         | string               | no      | no                  | "" or unset                           | must be valid CIDR                                                                                                                                                                               |         |                       |
| ipAllocationPolicy.clusterSecondaryRangeName    | string               | no      | no                  | "" or unset                           | found in /meta/gkeSubnetworks or /meta/gkeSharedSubnets                                                                                                                                          |         |                       |
| ipAllocation.createSubnetwork                   | boolean              | no      | no                  | false                                 | requires subnetworkName if set                                                                                                                                                                   |         |                       |
| ipAllocation.nodeIpv4CidrBlock                  | string               | no      | no                  | "" or unset                           | must be valid CIDR                                                                                                                                                                               |         |                       |
| ipAllocation.servicesIpv4CidrBlock              | string               | no      | no                  | "" or unset                           | must be valid CIDR                                                                                                                                                                               |         |                       |
| ipAllocation.servicesSecondaryRangeName         | string               | no      | no                  | "" or unset                           | found in /meta/gkeSubnetworks or /meta/gkeSharedSubnets                                                                                                                                          |         |                       |
| ipAllocation.subnetworkName                     | string               | no      | no                  | "" or unset                           | required if createSubnetwork=true                                                                                                                                                                |         |                       |
| ipAllocation.useIpAliases                       | boolean              | no      | no                  | true                                  | this is another name for VPC as opposed to routes-based                                                                                                                                          |         |                       |
| kubernetesVersion                               | string               | yes     | yes                 | latest available in /meta/gkeVersions |                                                                                                                                                                                                  |         |                       |
| locations                                       | array of strings     | yes     | yes                 | []                                    | will be filled in by current zone on backend if zone is set                                                                                                                                      |         |                       |
| loggingService                                  | string               | yes     | yes                 | ""                                    | empty is equivalent to 'logging.googleapis.com/kubernetes'; 'logging.googleapis.com' is legacy; explicitly set 'none' to disable; modification requires modification to monitoringService too    |         |                       |
| maintenanceWindow                               | string               | yes     | yes                 | ""                                    | must be HH:MM format                                                                                                                                                                             |         |                       |
| masterAuthorizedNetworks                        | object               | no      | yes                 | {}                                    |                                                                                                                                                                                                  |         |                       |
| masterAuthorizedNetworks.cidrBlocks             | array of object      | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| masterAuthorizedNetworks.cidrBlocks.cidrBlock   | string               | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| masterAuthorizedNetworks.cidrBlocks.displayName | string               | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| masterAuthorizedNetworks.enabled                | boolean              | no      | no                  | false or unset                        |                                                                                                                                                                                                  |         |                       |
| monitoringService                               | string               | yes     | yes                 | ""                                    | empty is equivalent to 'monitoring.googleapis.com/kubernetes'; 'monitoring.googleapis.com' is legacy; explicitly set 'none' to disable; modification requires modification to loggingService too |         |                       |
| network                                         | string               | no      | yes                 | "default"                             | found in /meta/gkeNetworks or /meta/gkeSharedSubnets                                                                                                                                             |         |                       |
| networkPolicyEnabled                            | boolean              | no      | yes                 | false                                 |                                                                                                                                                                                                  |         |                       |
| nodePools                                       | array of objects     | yes     | yes                 | []                                    | default could either be empty list or list of one node pool with default attributes copied from console; node pools can be added                                                                 | deleted | or modified on update |
| nodePools.autoscaling                           | object               | yes     | no                  | {}                                    |                                                                                                                                                                                                  |         |                       |
| nodePools.autoscaling.enabled                   | boolean              | yes     | no                  | false or unset                        |                                                                                                                                                                                                  |         |                       |
| nodePools.autoscaling.maxNodeCount              | integer              | yes     | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.autoscaling.minNodeCount              | integer              | yes     | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.config                                | object               | no      | yes                 | {}                                    |                                                                                                                                                                                                  |         |                       |
| nodePools.config.diskSizeGb                     | integer              | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.config.diskType                       | string               | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.config.imageType                      | string               | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.config.labels                         | string key/value map | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.config.localSsdCount                  | integer              | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.config.machineType                    | string               | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.config.oauthScopes                    | array of strings     | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.config.preemptible                    | boolean              | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.config.taints                         | array of objects     | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.config.taints.effect                  | string               | no      | no                  | unset                                 | Possible values: "EFFECT_UNSPECIFIED" - Not set; "NO_SCHEDULE" - NoSchedule; "PREFER_NO_SCHEDULE" - PreferNoSchedule; "NO_EXECUTE" - NoExecute                                                   |         |                       |
| nodePools.config.taints.key                     | string               | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.config.taints.value                   | string               | no      | no                  | unset                                 |                                                                                                                                                                                                  |         |                       |
| nodePools.initialNodeCount                      | integer              | yes     | yes                 | 3                                     |                                                                                                                                                                                                  |         |                       |
| nodePools                                       | management           | object  | yes                 | yes                                   | {}                                                                                                                                                                                               |         |                       |
| nodePools.management.autoRepair                 | boolean              | yes     | no                  | true                                  | must be set to false if enableKubernetesAlpha=true                                                                                                                                               |         |                       |
| nodePools.management.autoUpgrade                | boolean              | yes     | no                  | true                                  | must be set to false if enableKubernetesAlpha=true                                                                                                                                               |         |                       |
| nodePools.maxPodsConstraint                     | integer              | no      | yes                 | 110                                   |                                                                                                                                                                                                  |         |                       |
| nodePools.name                                  | string               | no      | yes                 | must be set by user                   | used to identify additions/deletions                                                                                                                                                             |         |                       |
| nodePools.version                               | string               | yes     | yes                 | same as kubernetesVersion             |                                                                                                                                                                                                  |         |                       |
| privateClusterConfig                            | object               | no      | yes                 | {}                                    |                                                                                                                                                                                                  |         |                       |
| privateClusterConfig.enablePrivateEndpoint      | boolean              | no      | no                  | false or unset                        |                                                                                                                                                                                                  |         |                       |
| privateClusterConfig.enablePrivateNodes         | boolean              | no      | no                  | false or unset                        |                                                                                                                                                                                                  |         |                       |
| privateClusterConfig.masterIpv4CidrBlock        | string               | no      | no                  | "" or unset                           | must be valid CIDR                                                                                                                                                                               |         |                       |
| projectID                                       | string               | no      | yes                 | must be set                           |                                                                                                                                                                                                  |         |                       |
| region                                          | string               | no      | yes                 | ""                                    | exclusive with zone                                                                                                                                                                              |         |                       |
| subnetwork                                      | string               | no      | yes                 | must be set                           | found in /meta/gkeSubnetworks or /meta/gkeSharedSubnets                                                                                                                                          |         |                       |
| zone                                            | string               | no      | yes                 | ""                                    | exclusive with region                                                                                                                                                                            |         |                       |
