### ISSUE TITLE
Rancher Backups: x509: certificate signed by unknown authority (with insecureTLSSkipVerify set to true)

### ISSUE THREAD

**Issue by t3hcr** [rancher/rancher#31238]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* installed Rancher backup with a default of our on-prem S3 storage (Cohesity)
* Configured a one-time backup (encryption: unencrypted, storage location: default configured during installation - S3)
* insecureTLSSkipVerify is set to true

**Result:**
Backup fails to run. Error: failed to check s3 bucket:myBucketName, err:Get https://my-endpoint.my-domain.com:3000/myBucketName/?location=: x509: certificate signed by unknown authority

**Other details that may be helpful:**
The error thrown seems like TLS cert verification is still occurring and causing the issue.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): VMs hosted on-premises with VMware vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3x VM in HA, each VM with 4 vCPU, 8GB RAM
- Kubernetes version (use `kubectl version`): v1.19.6
- Docker version (use `docker version`): v19.3.14

**Comment by matteogazzadi** [comment]
Issue still present in Rancher v2.6.5

**Comment by shivan** [comment]
I solved it on my side by using insecureTLSSkipVerify = true and adding the CA-certificate base64 encoded.

Also I configured rancher with additionalTrustedCAs=true and a generic secret  tls-ca-additional ([see also here](https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/chart-options/#additional-trusted-cas)). But I think the first configuration was the solution.

**Comment by superseb** [comment]
The requirement to provide CA certificate when setting insecureTLSSkipVerify will be removed in https://github.com/rancher/backup-restore-operator/issues/254
