### ISSUE TITLE
[UI] Fix DNS options YAML/JSON conversion on cluster creation

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#31230]
As part of issue https://github.com/rancher/rancher/issues/30047, an `options` field was added to the DNS config type so that users can provide additional key-value pairs to configure DNS in the cluster in the same way we already do it for network config.

Cluster config example:
![image](https://user-images.githubusercontent.com/8951271/107446119-9fc43d00-6af2-11eb-9bd7-8577194e71ac.png)

**Problem:**
The Ember UI is not handling the JSON/YAML conversion of `dns.options` in the same way as `network.options`. When the YAML edit view specifically is used to configure the cluster (It works fine in the API UI and RKE standalone), the `dns.options` key-value pairs get converted into JSON/camelCase, whereas `network.options` are handled in a special way as they preserve their YAML/underscore_case. Since the backend expects YAML/underscore_case , the `dns.options` key-value pairs never make it to RKE.

Network options after cluster creation:
![image](https://user-images.githubusercontent.com/8951271/107443932-8caf6e00-6aee-11eb-9758-f019d8028b0a.png)

DNS options after cluster creation :
<img width="495" alt="image" src="https://user-images.githubusercontent.com/8951271/107444248-13644b00-6aef-11eb-9df5-57ace79aaeb4.png">

**Solution:**
The backend handles `dns.options` in the exact same way as `network.options`, so their behavior should be matched in the UI as well.

**Comment by slickwarren** [comment]
<img width="453" alt="Screen Shot 2021-02-17 at 1 46 39 PM" src="https://user-images.githubusercontent.com/16691014/108275150-c0137d80-712a-11eb-8362-de10d3bb48d2.png">
UI now saves DNS config type correctly 
tested on 2.5-head (03b8153174e6762438cd906f6dc64eaa2f0802ae) and master-head(007e2985af1f24749d704020929a1c635f97e7ef)
