### ISSUE TITLE
[Monitoring] namespace and resources in cattle-prometheus keeps being recreated

### ISSUE THREAD

**Issue by mscbpi** [rancher/rancher#31233]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Disable Monitoring v1, Enable Monitoring v2

**Result:**
Monitoring v2 works, but cattle-prometheus namespace is still present. Then Monitoring v2 helm chart complains about v1 being present.

**Other details that may be helpful:**
Monitoring v1 was one activated

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- 2.5.5
- Installation option (single install/HA):
HA - RKE1

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
RKE Launched on vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM
- Kubernetes version (use `kubectl version`):
1.18.15

- Docker version (use `docker version`):
19.3.11

**Comment by mscbpi** [comment]
I may have found a workaround by deleting all alerts object that were created by default in Cluster Manager. They are also present in more recent clusters (where monitoring v1 has never been deployed), there legacy `cluster-monitor` does not keep deploying though.

**Comment by aiyengar2** [comment]
@mscbpi check out https://github.com/bashofmann/rancher-monitoring-v1-to-v2; the `check_monitoring_disabled.py` script should help you identify why Monitoring / Alerting V1 are still deployed.

**Comment by mscbpi** [comment]
I could not execute the script for some reasons but I have checked every step manually through the API, things that were not visible in Cluster Manager GUI for some reasons.

Indeed  `enableClusterMonitoring` and `enableClusterAlterting` were set to `true` , some notifiers were present while not visible in the GUI. Also the RKE template had to be adjusted. Now it is correctly reported as false and it seems it is stable, i.e. no recreation of the `cluster-monitor`.
