### ISSUE TITLE
Cluster provisioning is failing error "Error while applying agent YAML, it will be retried automatically: exit status 1"

### ISSUE THREAD

**Issue by sadiapoddar** [rancher/rancher#31232]
master-head, eac20a5

Steps to repro
1. Create a node driver cluster or a custom cluster
2. Notice that deployment failure during applying agent YMAL file 

<img width="1312" alt="Screen Shot 2021-02-09 at 7 30 58 PM" src="https://user-images.githubusercontent.com/72409237/107470416-3ce99a80-6b20-11eb-838d-c235f941669c.png">

-------- error logs --------------
```
2021/02/10 02:27:19 [ERROR] error syncing 'system-default-registry': handler copy-settings: the server could not find the requested resource, requeuing
2021/02/10 02:28:32 [ERROR] error syncing 'c-5l7rp': handler cluster-deploy: Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (InternalError): an error on the server ("dial tcp 127.0.0.1:6080: connect: connection refused") has prevented the request from succeeding , requeuing
2021/02/10 02:28:41 [ERROR] error syncing 'install-uuid': handler copy-settings: the server could not find the requested resource, requeuing
2021/02/10 02:28:41 [ERROR] error syncing 'system-default-registry': handler copy-settings: the server could not find the requested resource, requeuing
2021/02/10 02:28:59 [ERROR] error syncing 'c-5l7rp': handler cluster-deploy: Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (InternalError): an error on the server ("dial tcp 127.0.0.1:6080: connect: connection refused") has prevented the request from succeeding , requeuing
```

**Comment by sowmyav27** [comment]
This issue is not seen on latest 2.5-head

**Comment by sadiapoddar** [comment]
Currently, we can't verify any bugs on the master-head.

**Comment by ibuildthecloud** [comment]
https://github.com/rancher/rancher/pull/31249/files

**Comment by sadiapoddar** [comment]
verified on master-head, 990c1ad
By creating a node driver cluster and also a custom cluster.
Cluster Creation was successful

**Comment by sadiapoddar** [comment]
verified on master-head, 990c1ad

- By creating a node driver cluster and also a custom cluster.
- Cluster Creation was successful

**Comment by sadiapoddar** [comment]
will verify on 2.5-head and v2.6

**Comment by sadiapoddar** [comment]
Verified on 2.5-head, 3e96d7f by creating 
- a node driver cluster 
- a custom cluster.

Clusters creation was successful
