### ISSUE TITLE
Fleet, rancher webhook and rancher operator helm pods fail to deploy

### ISSUE THREAD

**Issue by Ellenqs** [rancher/rancher#31257]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. On 2.5-head, rancher server Go to the local cluster --> Apps and market place --> Installed apps. 
2. Rancher webhook, fleet and rancher operator  are not installed
3. Go to recent operations --> Rancher webhook, fleet and rancher operator helm pods are in failed state
4. The helm operation pods show the following error in logs : 
<img width="399" alt="Screen Shot 2021-02-10 at 2 54 53 PM" src="https://user-images.githubusercontent.com/75277058/107584143-dbbdd780-6bb0-11eb-9dd6-0bfa00e1e19c.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher v2.5-head - commit id: `ce47f5f`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS
- Kubernetes version (use `kubectl version`): v1.20.2

Rancher server logs:
```
2021/02/10 22:05:49 [ERROR] Failed to install system chart rancher-operator: failed to install , pod cattle-system/helm-operation-vtvnz exited 1
2021/02/10 22:06:14 [ERROR] Failed to install system chart rancher-webhook: failed to install , pod cattle-system/helm-operation-tcwcv exited 1
2021/02/10 22:06:38 [ERROR] Failed to install system chart rancher-operator-crd: failed to install , pod cattle-system/helm-operation-q2swp exited 1
2021/02/10 22:07:03 [ERROR] Failed to install system chart fleet: failed to install , pod cattle-system/helm-operation-7dtbs exited 1
2021/02/10 22:07:27 [ERROR] Failed to install system chart fleet-crd: failed to install , pod cattle-system/helm-operation-8bq66 exited 1
```

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/31255
https://github.com/rancher/rancher/pull/31256

**Comment by Ellenqs** [comment]
Validated on Rancher `v2.5-head, 05fbcbb` and `master-head, d7203b4`.

**Steps:**

- Deploy rancher HA setup.
- Go to local cluster, go to cluster explorer -> Apps & marketplace -> installed apps,  check apps installed.
- Go to recent operations, check helm pods states.

**Results**
On both versions

- Fleet v0.3.4 -rc5, rancher webhook 0.1.0-beta901-rc00 , rancher operator v0.1.3-rc5 all deployed successfully. 
- Helm operation pods ( which Rancher deployed for install the above-mentioned apps) are in the `active` state.


<img width="897" alt="Screen Shot 2021-02-16 at 11 58 48 AM" src="https://user-images.githubusercontent.com/75277058/108115082-7c4b4600-704e-11eb-8dce-6db7fd1bcf42.png">

<img width="1242" alt="Screen Shot 2021-02-16 at 11 35 02 AM" src="https://user-images.githubusercontent.com/75277058/108113200-0fcf4780-704c-11eb-8819-e8dff757263a.png">

**Comment by Ellenqs** [comment]
Validated on Rancher `v2.5-head, 05fbcbb` and `master-head, d7203b4`.

**Steps:**

- Deploy rancher HA setup.
- Go to local cluster, go to cluster explorer -> Apps & marketplace -> installed apps,  check apps installed.
- Go to recent operations, check helm pods states.

**Results**
On both versions

- Fleet v0.3.4 -rc5, rancher webhook 0.1.0-beta901-rc00 , rancher operator v0.1.3-rc5 all deployed successfully. 
- Helm operation pods ( which Rancher deployed for install the above-mentioned apps) are in the `active` state.


<img width="897" alt="Screen Shot 2021-02-16 at 11 58 48 AM" src="https://user-images.githubusercontent.com/75277058/108115082-7c4b4600-704e-11eb-8dce-6db7fd1bcf42.png">

<img width="1242" alt="Screen Shot 2021-02-16 at 11 35 02 AM" src="https://user-images.githubusercontent.com/75277058/108113200-0fcf4780-704c-11eb-8819-e8dff757263a.png">
