### ISSUE TITLE
[EKSv2] Clean up launch template versions on error

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#31263]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement/bug

**Steps to reproduce (least amount of steps as possible):**
1. Create an EKS cluster (or edit an existing cluster)
2. Create a node group without specifying a launch template
3. Set the desired size to 2 and maximum and minimum size to 1.

**Result:**
The update will fail. Go to the EC2 console to view the rancher-managed launch template. Many launch template versions will be created until the user fixes the problem.

What should happen is the operator should delete versions of the launch template when creation fails for some reason. The version number will continue to increase, but they should be deleted as the operator continues to fail.

**Other details that may be helpful:**
This is only for Rancher-managed launch templates.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `d7203b4`**

- `rancher/eks-operator:v1.0.6-rc3`
- Create an EKS cluster
- Create a node group , do not select an existing AWS lanch template
- Set the desired size to 2 and maximum and minimum size to 1. Cluster fails to come up.
- In the EKS console --> launch templates --> Version count is 793, but available versions are only 2
<img width="407" alt="Screen Shot 2021-02-16 at 9 28 10 PM" src="https://user-images.githubusercontent.com/26032343/108160458-f9ea7280-709d-11eb-857d-4040a07ab4fe.png">
