### ISSUE TITLE
[v2.4] Cluster stuck "currently Upgrading, updating worker node" on Cordoned workers

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#31268]
Backport https://github.com/rancher/rancher/issues/30049

**Comment by slickwarren** [comment]
waiting on main ticket to move back to QA

**Comment by slickwarren** [comment]
I was able to verify this fix on v2.4-4886-head: 
* create 1 node with all roles, and 3 more with only `worker` role
* ssh into the 3rd worker node with the downloaded keys, download an old image, and tag it as the version of rancher you're using `docker pull rancher/rancher-agent:v2.3.9; docker tag rancher/rancher-agent:v2.3.9 rancher/rancher-agent:v2.5-05fbcbb75ba84a80c5aaa243985e892c52b9ac32-head`
* go to `system` -> `cattle-node-agent` and select the pod running on worker 3. Delete the pod (it will restart with the image tagged previously)
* go to the cluster -> nodes, `edit cluster`, and add control plane to worker 1 , then save changes
* the cluster will update all nodes, and worker 3 will remain in `cordoned` state indefinitely. 
* ssh into the local cluster and `docker exec <rancher_container> bash
* make sure vi is installed `apt-get install vim && export EDITOR=vi`
* kubectl edit nodes.management.cattle.io m-xxxx -n c-xxxx
  * edit value of `appliedNodeVersion` to the value from `cluster.Status.nodePlan.NodeVersion`
  * for the `status` field of  lastUpdateTime with type: Upgraded (found near appliedNodeVersion), edit `status` value to `"True"`
  * save your changes
* after some time, the cordoned node now returns to active state
