### ISSUE TITLE
Feature charts should have rancher min/max version

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#31264]
We can do in similar way to system-charts: https://github.com/rancher/system-charts/blob/dev-v2.5/charts/rancher-monitoring/v0.1.0/questions.yml

Note that internal apps such as fleet and operator have their own system, see: https://github.com/rancher/rancher/issues/30934

**Comment by brendarearden** [comment]
https://github.com/rancher/rancher/blob/8476503a1a631c25ead03293736fbfb85d69c906/pkg/catalogv2/content/content.go#L212 This appears to already be added here, as part of this commit https://github.com/rancher/rancher/commit/fa26506587a029a7774c5bb3756772c3e95175d4. I am working on adding tests, and will update documentation and chart annotations as necessary.

**Comment by cbron** [comment]
@brendarearden to help QA, can you setup one feature chart to have this in dev and then revert after they test. Or find some other way to QA.

**Comment by brendarearden** [comment]
I have an example branch that can be used as a repository in rancher to test against: 
Type: Github Repo
Url: https://github.com/brendarearden/charts
Branch: testing-branch
Chart with the annotation: rancher-istio
The test is: depending on the rancher version that you are on, the chart should show or not show up available in the drop down. 
Set-up: have a rancher setup that you have set the rancher-server version to a release version. 

If you would like, you can fork the branch or make your own - the test does not need valid charts, it just needs a valid index.yaml that lists charts with the `atalog.cattle.io/rancher-version` annotation on it.

**Comment by jiaqiluo** [comment]
The enhancement is validated on rancher:v2.5-head 9e412a346

The following repo is used:
```
Url: https://github.com/brendarearden/charts
Branch: testing-branch
Chart with the annotation: rancher-istio
```

The annotation on each version in the [index.yaml](https://github.com/brendarearden/charts/blob/testing-branch/index.yaml) file
Istio Version | Annotation  
------------- | ----------  
1.7.700 | ~2.6.0               
1.7.600 | <2.6.0                
1.7.500 | >= 2.5.0-alpha < 2.6.0 
1.7.400 | >= 2.4.1-alpha < 2.5.8 
1.7.103 |   
1.7.102 | >= 2.4.1 < 2.5.7
1.7.101 | >= 2.4.3



The following command is used to change the version of Rancher by setting the environment variable `CATTLE_SERVER_VERSION`
```
sudo docker run -d --privileged --restart=unless-stopped -p 80:80 -p 443:443 \
--env CATTLE_SERVER_VERSION=v2.7.0 rancher/rancher:v2.5-head
```

Here are chart versions in the UI for each Rancher version
Rancher Vesion | Istio Version in UI
-------------- | -------------------
v2.5.0 | 1.7.101, 1.7.102, 1.7.103, 1.7.400, 1.7.500, 1.7.600
v2.5.8 | 1.7.101, 1.7.103, 1.7.500, 1.7.600
v2.6.0 | 1.7.101, 1.7.103, 1.7.700
v2.7.0 | 1.7.101, 1.7.103
