### ISSUE TITLE
Audit Logs - Environment field is empty.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3127]
Server Version - Build from master

Steps to reproduce the problem:
Go to Admin-> Admin Log page.
All Audit Log entries have  Environment field as empty string.

<img width="963" alt="screen shot 2015-12-22 at 7 35 39 am" src="https://cloud.githubusercontent.com/assets/4266958/11958822/f6665b5c-a87e-11e5-998a-62e0a2ca6820.png">

**Comment by westlywright** [comment]
@sangeethah on latest the environment field is showing up

**Comment by sangeethah** [comment]
Tested with latest build from master.

Environment field is shown in audit log entries.
