### ISSUE TITLE
Docker install scripts are not working for v17.06 and below

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31284]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* install rancher on v2.5-head (8b65a6abbf4371d4919eeefd25cd08805e1487e1)
* provision downstream cluster, selecting one of the following scripts: 17.06, 17.03, 1.13)
  * you could also run these scripts on a fresh node (ubuntu 18.04 and 20.04 tested)

**Result:**
* node fails to provision "Error with docker install"
* running script directly for v17.x on node gives:
```
cut -d   -f 4
+ sh -c apt-get install -y -q docker-ce=
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '' for 'docker-ce' was not found
```
* for 1.13:
`E: Version '' for 'docker-engine' was not found`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-head (8b65a6abbf4371d4919eeefd25cd08805e1487e1) and master-head (990c1ad98b671185d415c8cac42829617b03ebcf)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted (DO, Linode), custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

- Docker version (use `docker version`): 17.06, 17.03, 1.13

**Comment by rawmind0** [comment]
@slickwarren , 17.06.sh, 17.03.sh, 1.13.sh scripts hasn't been updated. Have you tested these os/docker combination before?? Not all docker versions are compatible with all os versions.

As can be checked on docker package definition, docker is not providing docker-ce packages for:
* Ubuntu 18.04 for docker older than 18.09: https://download.docker.com/linux/ubuntu/dists/bionic/stable/binary-amd64/Packages
* Ubuntu 20.04 for docker older than 19.03: https://download.docker.com/linux/ubuntu/dists/focal/stable/binary-amd64/Packages

**Comment by rawmind0** [comment]
Docker just provide 17.09, 17.06 and 17.03 packages for [ubuntu 16.04](https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/) and [ubuntu 14.04](https://download.docker.com/linux/ubuntu/dists/trusty/pool/stable/amd64/)

Afaik, docker doesn't provide 1.1x packages anymore. They were published from deprecated/offline [https://yum.dockerproject.org](https://github.com/rancher/install-docker/blob/master/dist/1.13.1.sh#L29) 

17.09, 17.06 and 17.03 should work fine at ubuntu 16.04 or 14.04

**Comment by slickwarren** [comment]
Tested on the following: 
* ubuntu 16 + docker 20.10, 19.03, 17.03 -- all installed correctly 
as you said, docker v1.1x did not work on ubuntu 16
