### ISSUE TITLE
During creating node template in vSphere  the tag/attributes are not available to select from. 

### ISSUE THREAD

**Issue by sadiapoddar** [rancher/rancher#31285]
v2.5-head, df89971 and master-head, 98fe72a

Currently, the tags and custom attribute fields are grayed out during node template creation.
Steps to repro:
1. from amber UI select "add template"
2. Create the vCenter credential by providing the server, user/pass info
3. Notice if you try to add tags or attributes the fields are grayed out

<img width="1205" alt="107564223-f4b98f00-6b96-11eb-90ea-46e6a7ae7793" src="https://user-images.githubusercontent.com/72409237/107699745-5cd9a500-6c6b-11eb-95f8-f86e5895e9d7.png">

But we have some VM tags and attributes available in the vCenter. Ideally, these tags and attributes should available in the dropdown for the users to select from.

Addition info that can be helpful.
on v2.5.0, during creating node template tags/attributes are available in the dropdown.

<img width="761" alt="Screen Shot 2021-02-11 at 1 21 49 PM" src="https://user-images.githubusercontent.com/72409237/107700391-4718af80-6c6c-11eb-8e10-ff0313fdcc5d.png">
<img width="707" alt="Screen Shot 2021-02-11 at 1 22 04 PM" src="https://user-images.githubusercontent.com/72409237/107700511-70394000-6c6c-11eb-95f4-5832c2a0c762.png">

**Comment by mfbrj** [comment]
Only `Add custom attribute` are grayed here.
![image](https://user-images.githubusercontent.com/835834/108398716-18fd1780-71f8-11eb-80c9-2fe0eb1d5645.png)
`Rancher 2.5.5`

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head  30e53bd UI: v2.5-dev
rancher/rancher:master-head 465bb3b UI vmaster-dev

In both environments:
* Create a vSphere node template
* Tags from vSphere are shown in the dropdown correctly
* Attributes from vSphere are shown in the dropdown correctly
* Selecting multiple tags and attributes in the node template and creating the cluster applies the tags and attributes correctly to the VM in vSphere
