### ISSUE TITLE
Add GKE to the resourceset for the rancher backup operator

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#31281]
For the upcoming GKE v2 provisioner, we need to add gke to the resourceset for https://github.com/rancher/backup-restore-operator

**Comment by jiaqiluo** [comment]
the support for GKE resources is added in the app `rancher-backup 1.0.4-rc3`

**Comment by sowmyav27** [comment]
Blocked because of https://github.com/rancher/rancher/issues/32152

**Comment by sowmyav27** [comment]
**on 2.5-head commit id: `31f00c1 ` verified using backup restore chart - `rancher-backup:1.0.400-rc03`**

- Deployed rancher HA
- Deployed a GKEv2 cluster and an AWS node drive rke cluster
- Take backup b1
- Bring up a new RKE cluster, restore on this cluster from b1.
- Deploy rancher HA on this. 
- Edit the GKE cluster and add a nodepool.
- Scale up the rke node driver cluster - worker nodes.
- the clusters come up fine and the nodepool and nodes are added.
