### ISSUE TITLE
SAML Ping Auth - Add a field to accept Entity ID

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#31287]
**What kind of request is this:**
bug/improvement

**Steps to reproduce:**

We had this same field exposed in the UI for keycloak in the past.

https://github.com/rancher/rancher/issues/29553 
Ping hosted applications use the Entity ID (`spEntityId`) to match the App Client ID 

The field shouldn't be required.

**Result:**

The EntityID sent by Rancher defaults to the metadata url which is invalid clientid in this case. 
Example:

![Screen Shot 2021-02-09 at 1 14 24 PM](https://user-images.githubusercontent.com/27659/107714320-4ee74c80-6c8a-11eb-9375-a2f53b6d72d0.png)

**Environment information**
- Rancher version: `master-head (02/11/2021)` _98fe72a_
- Installation option: single and HA

**Comment by gaktive** [comment]
Does this make sense to you @westlywright ?

**Comment by deniseschannon** [comment]
This is a new field that is now required as part of Ping authentication that has come up as of re-validating the SAML providers for the updated backend vendor update.

@mantis-toboggan-md Is this field available on the Vue UI for when configuring Ping?

**Comment by mantis-toboggan-md** [comment]
Yes; the entity id field is available for all saml providers except Okta

**Comment by izaac** [comment]
Rancher version `v2.5-head (02/26/2021)` _67228a3_
Rancher version `master-head (02/26/2021)` _465bb3b_

Validated using the default Entity ID
Validated with a custom ID in the SP (ping) and sending the correct ID
Validated with a custom ID in the SP (ping) and sending the incorrect ID (fails as expected)
