### ISSUE TITLE
ACL rules not programmed in LB

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3128]
Server version - Build from master

Steps to reproduce the problem:

Create LB rule with following hostname routing rules:

<img width="856" alt="screen shot 2015-12-22 at 10 34 19 am" src="https://cloud.githubusercontent.com/assets/4266958/11962855/c7d8b2da-a897-11e5-9c52-24a60fceea88.png">

Acl rules are not getting programmed in haproxy config:

<img width="737" alt="screen shot 2015-12-22 at 10 36 54 am" src="https://cloud.githubusercontent.com/assets/4266958/11962876/f59cfcda-a897-11e5-9a30-79296601e5d6.png">

**Comment by alena1108** [comment]
@sangeethah happens because empty protocol was defaulted to tcp for the ports. And we don't configure host name routing rules for tcp

**Comment by rancherdev** [comment]
@alena1108 , even when I pass "http" explicitly for listener from UI , I see it being saved as "tcp"

**Comment by alena1108** [comment]
@sangeethah because its not a UI issue, but the java issue

**Comment by sangeethah** [comment]
Tested with latest build from master:
ACL rules get programmed when LB has targets with host name routing.
