### ISSUE TITLE
An information popup to tell user what to do with Machine Config

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#313]
Once I download Machine Config from Host, I don't know what to do after that.  Please add an information popup of some sort to direct user.

**Comment by deniseschannon** [comment]
We'll include this information into the documentation.

**Comment by vincent99** [comment]
I'd still like to at least link to that documentation from the UI when you click it.  Or maybe we could include a `README.txt` in the archive that's downloaded that points you there.

**Comment by deniseschannon** [comment]
Here's the link for machine config:

https://rancherio.github.io/rancher/docs/infrastructure/hosts/#machine-config

**Comment by tfiduccia** [comment]
Redesigning for 2.0
