### ISSUE TITLE
Load balancer health_state stuck in updating-healthy

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#3130]
Hi,

I've deployed a load balancer using the 'rancher/load-balancer-service' docker image.

It looks like the health_state never transition from updating-healthy to healthy, do you see the same issue?

Cheers,
Matteo

**Comment by deniseschannon** [comment]
How are you deploying the service? You should never have to pick the `rancher/load-balancer-service` image?

**Comment by m4ce** [comment]
@deniseschannon, http://docs.rancher.com/rancher/rancher-compose/rancher-services/#load-balancer

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml and rancher-compose.yml? We don't see any issues with load balancers becoming healthy.

Also, is this a load balancer that was from a previous installation or a new load balancer?

**Comment by m4ce** [comment]
@deniseschannon, I got back today and I no longer see the issue :/ I would close this ticket as I don't seem to be able to reproduce it, it could be that it just took longer to transition from updating-healthy to healthy.

Thank you,
Matteo
