### ISSUE TITLE
Enhancement: remove unsupported Docker versions from Docker Install URL list

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31303]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
* see ticket rancher/rancher#31284 for more details (specifically [this comment](https://github.com/rancher/rancher/issues/31284#issuecomment-777877501)) 
* Not all docker versions are expected to work with each OS
* Docker version v1.13 is no longer supported, but still listed in our supported versions/options

**Result:**

**Other details that may be helpful:**
Can we: 
* remove unsupported version 1.13 from our list of `docker install urls` - brought out into separate issue https://github.com/rancher/rancher/issues/31340
<img width="141" alt="Screen Shot 2021-02-12 at 10 33 53 AM" src="https://user-images.githubusercontent.com/16691014/107808073-e6e24600-6d1d-11eb-99a8-dde180a2d58a.png">
* for node driver provisioned template, restrict `docker install urls` to versions of docker that work with that os 
  * example: if user selects Ubuntu 18, the list would only include docker version v18.x+

<img width="141" alt="Screen Shot 2021-02-12 at 10 33 53 AM" src="https://user-images.githubusercontent.com/16691014/107808385-55bf9f00-6d1e-11eb-8356-424dbbadc4df.png">

**Comment by vincent99** [comment]
Who's going to maintain this list of what's supported for every version of every OS, or in some cases determine what OS is selected (e.g. by "ami-1a7fvq")?

**Comment by gaktive** [comment]
We can remove the v.v13.x easily from the UI. But for a mapping of OS to Docker, we'd need a new ticket to do create a static list on the backend.
