### ISSUE TITLE
UI Performance Issue with Secrets

### ISSUE THREAD

**Issue by olds463** [rancher/rancher#31302]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Open chrome developer tools, goto "Network" tab, sort by size.
2. Navigate to your cluster project homepage 
3. All secrets are pulled from an API call regardless if you're viewing a route on the ui that displays secrets. 

**Result:**
Homepage of cluster (workloads shown) fetches all project level secrets. This causes, in my scenario, 8MB of 
data to be returned via v3/project/c-vtxqr:p-n8f7b/namespacedsecrets?limit=-1&sort=name

This is causing very slow initial page loads (upwards of 60s)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
2.5.5 via k3s

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by vincent99** [comment]
This is part of the data model for Cluster Manager to track relationships between resources and secrets (among other common types that are always loaded on page load) and is not going to change.

The Cluster Explorer UI does less of this in general with a few more efficient ways in the API it uses to track relationships.

But for types where some related info is needed that aren't covered by that, "n" calls to get individually referenced records quickly becomes slower than loading the whole set.  And for the list pages the only way to do arbitrary sorting/filtering/paging/live updating is to have the whole collection in memory, render the appropriate subset and update it from watch events.
