### ISSUE TITLE
[UI][KEv2] UI for AKS v2 Provisioner

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#31315]
Feature: Similar to what was done for EKS (per https://zube.io/rancher/rancher/c/30415), we need a UI for the AKS v2 Provisioner.

@mjura can offer some screenshots for additional context on what he foresees since some parts of the discussion flew by quickly so hopefully I didn't miss anything. The UX should be mostly identical to what's already in EKS with some parallels to GKE, though do note these small differences:

- Cloud Credentials will need a Subscription field along with Tenet, though Tenets might be derivable from the Subscription. That said, it's possible to have multiple Tenets under an Azure Subscription. @satadruroy to confirm how possible that lookup is though the API may help out.

- Node Options need to have these two options added: VM Sizes and Node Count, which then tie into Availability Zones (AZ). The tricky thing is that not all regions have support for AZs. There isn't an Azure API that we're aware of that detect that if an AZ falls into a specific region, so we'll need a static list. As the UX experience goes, we can look at allowing a user to pick a region and then tell them if AZs are supported there. (There was discussion regarding using the general proxy if it can leverage cloud credentials similar to how EKS can look up things. Using the frontend is preferred over the backend though.)
* AZs shouldn't have to change per node pools. Whatever the user would normally pick in the first screen should be the default.

- Need new section: Node Pools, which ties into agentpools. The Azure interface allows users to specify whether a Primary Node Pool relies on either `system` (normally used for control planes) and `user` (what is most typically needed for Rancher). Primary Node Pools would specify Mode, OS, Count & Size but for subsequent node pools, we'd hide the mode, forcing a default of `user`. 
* Node Count: there are maximums tied to subscriptions we need to warn about
* OS: need to advise that Linux and Windows pools aren't interchangeable (or cross-accessible)
* OS Disk Size: not exposed in the API?

- Maximum pods per node defaults to 110 with a maximum of 250.

- Need Networking section, which can adopt HTTP App Routing along with section for Security with a new field: Support Private Kubernetes Service Support.

- For Load Balancing, although there are two choices (Standard and Basic), some are specific to regions and AZs. We should default to Standard since Basic has less options and may be deprecated soon. 

- choices for clusters are either Public or Private with descriptions. There are questions about whether private nodes are in fact public but that involves detecting IP changes. @mjura or @satadruroy ?)

- new section needed: Node Autoscaler, which would be a checkbox under Node Options

- RBAC shouldn't require a UI since we need to have it enabled. That said, upon registering or importing a cluster without RBAC (i.e, RBA is disabled in the object coming into Rancher), we need to warn that it won't work without RBAC enabled -- this should be in the docs too. Registration likely will need a minor change for options & upgrades to exclude RBAC.

- Some moving of items around to be considered, though we have to strike a balance between a consistent Rancher UI (Ember) experience and the Azure workflow:
* as above, move HTTP App Routing to Networking. Do note we have to be careful with the defaults as the API sets it True, which we can leave as is.
* move Monitoring a new section called Advanced, which could reside between Cluster Options and Node Options
* group the Username & SSH Key together since they're commonly associated with each other
* Kubernetes Options should have both Name and Kubernetes
* Use the new Rancher proxy endpoints to get available regions and VM sizes (https://github.com/rancher/rancher/issues/32594)

**Comment by satadruroy** [comment]
Cloud Credentials: Users in a tenant can have multiple subscriptions and a subscription can switch between tenants so it is not a 1-1 relationship between tenant and subscriptions.Recommend adding tenant id as an additional field to the trio of client id, secret and subscription id.   Need to discuss with @cbron any possible impact on Azure VMs (from v1?) of adding in tenant id in the creds. [1]

Basic/Standard LB: Basic LBs have several limitations, so maybe best to default to standard LB for new clusters. For registering pre-created clusters we'll have to display the LB the cluster was provisioned with, and offer the option to pick any of the two but then again if there are additional node pools involved it can only be standard. [2]

Private Cluster: Typically, AKS worker nodes do *not* get public IPs, regardless of whether it's a private cluster or not (there are exceptions). With a private cluster, the control plane does not have a public endpoint and Rancher agent would have to be deployed from a node in the same vnet to be able to connect with the apiserver. [3] 

[1] https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-subscriptions-associated-directory

[2] https://docs.microsoft.com/en-us/azure/load-balancer/skus#skus

[3] https://docs.microsoft.com/en-us/azure/aks/private-clusters#options-for-connecting-to-the-private-cluster

**Comment by mjura** [comment]
Here are print screens from Azure portal which could help us with option organization and naming 

1. Creating new AKS cluster 

![aks-basic](https://user-images.githubusercontent.com/4455471/108210940-6c099880-712c-11eb-8daf-f7c8cdb64e2a.png)

2. AKS node pools tab

![aks-nodepools](https://user-images.githubusercontent.com/4455471/108211082-978c8300-712c-11eb-874b-74a67fbcdac6.png)
 
3. Adding new node pool tab

![aks-addnodepool](https://user-images.githubusercontent.com/4455471/108211108-9d826400-712c-11eb-911f-d732aac5a09d.png)

4. AKS networking tab

![aks-networking](https://user-images.githubusercontent.com/4455471/108211140-a5420880-712c-11eb-9752-ed40c018f7d6.png)

**Comment by gaktive** [comment]
This will move over to Vue in the Dashboard for 2.6. Let me transfer this over to that repo.

**Comment by cbron** [comment]
@gaktive @vincent99 don't we need AKSv2/GKEv2 in both ember and vue through 2.6 ? I thought we had said that. Would be weird to have only AKSv2 not in ember.

**Comment by gaktive** [comment]
@cbron this came up during 2.6 UI planning with @deniseschannon -- we could potentially iFrame the Ember version in Vue but there's a push for net new pages to be in Vue going forward in 2.6. GKE would be an iFrame for now but AKS could be in Dashboard natively.

**Comment by gaktive** [comment]
Target is for the UI to be in Ember for 2.6. We'll need an iFrame for the Vue Dashboard.

**Comment by cmurphy** [comment]
Could we have the UI validate the length of the node pool name for Windows nodes? See note [here](https://github.com/rancher/aks-operator/pull/5/files#diff-1aa54d4941ca80708078867e1b130aff086719689479dea38683fded2f3c7852R394-R396) and [this request](https://github.com/rancher/aks-operator/pull/5#discussion_r628905427)

**Comment by westlywright** [comment]
@cmurphy I can add that validation, yes.

**Comment by prabalsharma** [comment]
Tested via test plan
