### ISSUE TITLE
cattle-node-agent-windows on Windows cloud provider enabled setup fails to come up

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31316]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Validated using windows 2004 and 1909 (1.19.7 k8s version)
- Deploy windows cluster - 1 etcd, 1 control and 1 worker linux nodes and 3 windows worker nodes (Cloud config enabled)
- The cattle-node-agent-windows in the system project for the cluster is not Active.

Logs:
```
(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c4f1d825a1c516f555aceaf31e49ff0c0425fbee29744848fea937c1263b2c15" network for pod "cattle-node-agent-windows-z7sz8": networkPlugin cni failed to set up pod "cattle-node-agent-windows-z7sz8_cattle-system" network: open /run/flannel/subnet.env: The system cannot find the path specified.
```

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `dba332111`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom windows
- Kubernetes version (use `kubectl version`):

```
1.19
```

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `30e53bd`**

- Bring up windows cluster with HostGW network
- Register 1 linux all roles and 2 windows clusters.
- Cloud config is not enabled
- The cluster comes up Active and the windows node agent is up and Active.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `5a5c039`**

- Deployed windows clusters
```
- Host GW, Cloud provider enabled, Windows 2004 - Windows_Server-2004-English-Core-ContainersLatest-2021.01.13, 1.20.4 k8s
- Host GW, Cloud provider enabled, Windows 1909, Windows_Server-1909-English-Core-ContainersLatest-2021.01.13, 1.20.4 k8s
- VXlan, Cloud provider enabled, Windows 1909, Windows_Server-1909-English-Core-ContainersLatest-2021.01.13, 1.20.4 k8s
```
- Cluster comes up Active. Windows Node agents on the cluster is Active.
- rke tools - `rancher/rke-tools v0.1.72 `

**Comment by luthermonson** [comment]
root cause came from a newline being added to a cache we use for hostname. we use that hostname in the --hostname-override on the kubelet and it ultimately would set `<hostname>\r\n` and basically everything fell apart after that. found out newline was coming from the utf8 updates we made for 20h2. made a minor tweak to use a different system.io.file func to write the cache.
