### ISSUE TITLE
Audit Logs - api.stack.create api link results in 404.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3131]
Server version - V0.51.0-rc3

Create a stack.
Go to Admin->Audit Log and locate the api.stack.create entry.

Click on the link in "Resource Type:Id" field.
API link presented to the user is of the format - http://<ip>:8080/v1/stack/1s1 . which results in "404 Not Found" 
This should have been http://<ip>:8080/v1/environment/1e1 instead.

**Comment by vincent99** [comment]
Event type should be `api.stack.create` but `resourceType` and the link should still be environment.

**Comment by sangeethah** [comment]
Tested with latest build from master


API link presented to the user for api.stack.create event is of the format http://<ip-address>:8080/v1/environments/1e35 and provides information about the environment.
