### ISSUE TITLE
Failed pods are displayed in the UI long after the pod are gone.

### ISSUE THREAD

**Issue by ranchersvet** [rancher/rancher#31310]
Failed pods are displayed in the UI long after the pods are gone.
Rancher v2.5.3
Custom cluster v1.17.6
gz#14888
![pods](https://user-images.githubusercontent.com/67922252/107828610-d26a7180-6d4e-11eb-8af3-ae232c21bda7.jpg)

**Comment by superseb** [comment]
What are the steps to reproduce here? Please provide the output from `kubectl` from this deployment/from these pods. Was the websocket active? Does it still show after a refresh?
