### ISSUE TITLE
[Epic]: Logging and Rancher SELinux RPM

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#31311]
Create logging policy for rke1 and rke2 and update feature chart: https://github.com/rancher/rancher/issues/30949
Logging aggregator sidecar: https://github.com/rancher/rancher/issues/31309
~rancher RPM: https://github.com/rancher/rke2-selinux/issues/1~
rancher RPM: https://github.com/rancher/rancher/issues/31888
RPM Docs: https://github.com/rancher/docs/issues/3028

**Comment by cbron** [comment]
Adding this as to-test for now since required pieces are in-test also. But I'll keep open for docs stuff after. We can leave in "review" if that makes more sense.

**Comment by izaac** [comment]
I am closing this issue to reduce noise and I am also linking the remaining work that's being done on separate issues below.


Validation issue for `3.9.4` logging chart on `master-head` #32062
SELinux validation for RKE1 and RKE2 (Rancher Federal) #31309
  - RKE1 fully validated on `v2.5-head`
  - RKE2 systemd collector still not working on `v2.5-head`
  - Opened #32063 to validate SELinux on `v2.6` (`master-head`)
Windows Logging: #28721
