### ISSUE TITLE
Audit Logs - Resource Type drop down should include "stack" instead of "environment".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3132]
Server version - v0.51.0-rc3

All the stack related actions appear in audit log entries with "event type" as api.stack.* and  resoucetype:id as "stack:<n>s<n>".

Resource Type drop down does not include "stack" instead has "environment".

Expected Behavior:
Resource Type drop down should include "stack" instead of "environment".

This is related to issue tracked in #3131

**Comment by vincent99** [comment]
The type is still `environment` in the API and remapping that will only make things more confusing...
