### ISSUE TITLE
Add Support for "resourceNames" in Rancher's RBAC

### ISSUE THREAD

**Issue by asemen2608** [rancher/rancher#31329]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**

Limit at Rancher's level RBAC to prevent people from deleting specific namespaces with a given name. 
In Kubernetes, that would be translated to:

rules:
- apiGroups: [""]
resources: ["namespaces"]
resourceNames: ["cattle-system"]
verbs: ["list", "get", "watch"]

However, the particular field "resourceNames" isn't visible for end-users in Rancher.

**Result:**

Unpossible prevent people from deleting specific namespaces with a given name. 

**Other details that may be helpful:**

Rancher role templates are just Kubernetes roles. As such, whilst the Rancher UI does not expose the resourceNames field of rules, this field exists on the API object (schema can be seen at https://<rancher_url>/v3/schemas/policyRule). 
Therefore, a user can add or edit resourceNames for a role, within the API Explorer, by clicking 'View in API' for a role from the Rancher UI.

tried out "nonResourceURLs," collide with preexistent Kubernetes objects if use them in a name. 
For example, when we tried to block "cattle-system" using "nonResourceURLs"  the result is:

>> Invalid value: []string{"namespaces/cattle-system"}: rules cannot apply to both regular resources and non-resource URLs

**Environment information**
- Rancher v2.4.8 
- HA

gz#14965

**Comment by patrickdappollonio** [comment]
Still relevant.
