### ISSUE TITLE
imageID, userdata values from pre existing AWS Launch templates do not sync back to Rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31321]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create an EKS cluster in EKS console using a launch template
- The launch template has been created using custom AMI, and userdata field also has value.
- Custom AMI: `ami-020b9012dfce5d885`
- userdata

```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="
--==MYBOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"
#!/bin/bash
set -ex
B64_CLUSTER_CA=<Certificate authority>
API_SERVER_URL=<API server endpoint>
K8S_CLUSTER_DNS_IP=<Service IPv4 range (without the /16)>
/etc/eks/bootstrap.sh <cluster name> --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL --dns-cluster-ip $K8S_CLUSTER_DNS_IP
--==MYBOUNDARY==--\
```

- Wait for the cluster, nodegroups to come up Active in EKS console
- Import this cluster into Rancher.
- View in API of the cluster when the cluster comes up Active:

```
pstreamSpec": {
"amazonCredentialSecret": "cattle-global-data:cc-bkmvz",
"displayName": "sowmya-import-3",
"imported": true,
"kmsKey": "<key>",
"kubernetesVersion": "1.18",
"loggingTypes": [ ],
"nodeGroups": [
{
"desiredSize": 2,
"diskSize": null,
"ec2SshKey": null,
"gpu": null,
"imageId": null,
"instanceType": null,
"labels": { },
"launchTemplate": {
"id": "lt-000fe5d30da786b02",
"name": "sowmya-custom-ami",
"type": "/v3/schemas/launchTemplate",
"version": 3
},
"maxSize": 2,
"minSize": 2,
"nodegroupName": "sow-custom-ami-new",
"requestSpotInstances": false,
"resourceTags": null,
"spotInstanceTypes": null,
"subnets": [ 3 items
"subnet-ee**",
"subnet-1e**",
"subnet-61**"
],
"tags": { },
"type": "/v3/schemas/nodeGroup",
"userData": null,
"version": "1.18"
}
],
"privateAccess": false,
"publicAccess": true,
"publicAccessSources": [
"0.0.0.0/0"
],
"region": "us-east-2",
"secretsEncryption": true,
"securityGroups": null,
"serviceRole": null,
"subnets": null,
"tags": {
"key1": "value1"
},
"type": "/v3/schemas/eksClusterConfigSpec"
},
"virtualNetwork": ""
},
```
- Edit cluster --> Image ID and userdata fields are blank

**Expected Result:**
Image ID and userdata fields should reflect what is available in the EKS backend.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `3e96d7fb`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Import EKS
- Kubernetes version (use `kubectl version`):

```
1.18(Any)
```

**Comment by thedadams** [comment]
This is the expected behavior. Rancher does not sync back the launch template information for user-provided launch templates because that would require that Rancher overwrites the cluster's `Spec`, which we shouldn't do.

This is also consistent with EKS: any value that is set in the launch template in EKS says "Provided in launch template".

**Comment by cbron** [comment]
Confirmed with @rmweir that this is expected behavior so we can close. As Donnie, said the actual EKS cluster does not contain these fields, as they exist in the launch template which we are just referencing.

**Comment by sowmyav27** [comment]
Closing the issue based on comments - https://github.com/rancher/rancher/issues/31321#issuecomment-779239830 and https://github.com/rancher/rancher/issues/31321#issuecomment-780699488
