### ISSUE TITLE
500 error on /v3/kontainerdrivers/rancher-images as a result of non-existent /var/lib/rancher/management-state/catalog-cache directory

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#31336]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a cluster with RKE and install Rancher via helm
2. Navigate to https://<rancher_url>/v3/kontainerdrivers/rancher-images and refresh the page many times

**Result:**

Observe many requests fail with the following error:

```
{
"baseType": "error",
"code": "ServerError",
"message": "error getting image list for linux platform",
"status": 500,
"type": "error"
}
```

Rancher pod logs show errors of the following format:

```
2021/02/16 09:16:44 [ERROR] API error response 500 for GET /v3/kontainerdrivers/rancher-images. Cause: failed to fetch images from system charts: failed to get chart and version from "management-state/catalog-cache/df6f64f73bb427a3c62ced202ca09db9cf9f2547296217da13a2eb43d5cf5c08": stat management-state/catalog-cache/df6f64f73bb427a3c62ced202ca09db9cf9f2547296217da13a2eb43d5cf5c08: no such file or directory
```

**Other details that may be helpful:**

`/var/lib/rancher/management-state/catalog-cache` appears to exist only on the Rancher leader Pod. As a result requests for `/v3/kontainerdrivers/rancher-images` only succeeded when served by the leader Pod.

**Environment information**
- Reproduced with Rancher v2.4.4, v2.4.13 and v2.5.5

gz#15049

**Comment by paynejacob** [comment]
The image list is generated at request time by looking at the catalog `index.yaml` files and then crawling the chart `values.yml` one by one.  This depends on the rancher pod cloning all the chat repositories locally.  In an HA environment only the leader rancher pod clones these repositories.  When the ingress round robins requests they can end up on pods that do not have the repositories cloned causing a 5XX error.  

Proposed Solutions:
- **Ensure this request is only served by the leader pod.** This could be done by splitting the rancher service into leader and non leader pods and having the ingress route some paths to the leader service.  This solution is somewhat fragile given the list of paths that can only be served by the leader pod would need to be maintained.
- **Clone the charts repositories onto each pod.**  This solution would be the easiest to implement however it will generate significantly more traffic to our charts repositories and could cause issues with charts data getting stale, causing the images endpoint to return different content based on what pod serves the request.
- **Store the images list in etcd and generate it on the leader pod.**  When the leader pod clones the charts repositories it could generate the images list and store it in etcd.  The other pods could then serve this request by reading from etcd.

References:
https://github.com/rancher/rancher/blob/master/pkg/api/norman/customization/kontainerdriver/actionhandler.go#L155
https://github.com/rancher/rancher/blob/master/pkg/catalog/helm/helm.go#L171
https://github.com/rancher/rancher/blob/master/pkg/image/resolve.go#L183

**Comment by paynejacob** [comment]
After talking to @dramich and @vincent99 the solution to this is to  return a 4XX response when a principal is going to be bound to 2 users. The user should be sent to documentation for why this is not possible.

When a user configures an authentication provider they are asked to login with a test account.  This test account's principal is bound to the local user that was used to configure the provider.  This gives the user instant access to the authentication provider's information and allows them to configure other users right away.  

If the authentication provider is disabled and the reconfigured with a different test user, the request should be rejected.  The only possible solutions for this would involve breaking audit trails  or not binding the user to the local account, causing confusion when they attempt to continue with setup.  Instead the user should be informed why rancher cannot proceed and given guidance on how to proceed.

**Comment by anupama2501** [comment]
Reproduced the issue on rancher HA server: **v2.5.5** 

1. Bring up rancher server using the helm command
2. navigated to https://<url>/v3/kontainerdrivers/rancher-images
Error seen in the API `{"baseType":"error","code":"ServerError","message":"error getting image list for linux platform","status":500,"type":"error"}`
Also, in the rancher pod logs: ```2021/07/06 20:14:55 [ERROR] API error response 500 for GET /v3/kontainerdrivers/rancher-images. Cause: failed to fetch images from system charts: failed to get chart and version from "management-state/catalog-cache/df6f64f73bb427a3c62ced202ca09db9cf9f2547296217da13a2eb43d5cf5c08": stat management-state/catalog-cache/df6f64f73bb427a3c62ced202ca09db9cf9f2547296217da13a2eb43d5cf5c08: no such file or directory
```

On the non-leader rancher pods, ` cannot access '/var/lib/rancher/management-state/catalog-cache': No such file or directory` is not seen. Only present in the leader pod.

**Comment by anupama2501** [comment]
Verified on master-head rancher server commit: `3e44415`
**Upgrade testcase:**
1. Created rancher server on v2.5.5 and upgrade to master-head version via helm
2. Navigated to https://url/v3/kontainerdrivers/rancher-images 
3. Verified image list has been downloaded by navigating to the above url multiple times.

**Fresh install master-head 3e44415:
Verified by the same steps as above to download the image multiple times and see the images are downloaded without errors.

**Comment by sowmyav27** [comment]
Reopening for one more check.

**Comment by anupama2501** [comment]
Verified on master-head 3e44415

- From the leader rancher pod shell executed the command:
- curl -u <cattle_accesskey>:<cattle_secretkey> --insecure 'https://podip:443/v3/kontainerdrivers/rancher-images'
- Sample image list displayed:

``` rancher/rancher-agent:master-3e44415af2332fcc305cdb68907794d8b3b3e29a-head
busybox
rancher/coreos-flannel:v0.13.0-rancher1
rancher/flannel-cni:v0.3.0-rancher6
rancher/hyperkube:v1.17.17-rancher2
rancher/hyperkube:v1.18.19-rancher1
rancher/hyperkube:v1.19.11-rancher1
rancher/hyperkube:v1.20.7-rancher1
rancher/hyperkube:v1.21.1-rancher2
rancher/kube-api-auth:v0.1.5
```

- Repeated for non-leader rancher pods and verified the image list is displayed as above without any error.
