### ISSUE TITLE
rancher deployed on k3s cluster with embeded etcd show 'etcd not applicable' even if the status is Healthy

### ISSUE THREAD

**Issue by rpelissi** [rancher/rancher#31334]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Install a k3s v1.19.5+k3s1 cluster with embedded etc. Deploy rancher 2.5.5 with helm.

**Result:**
Everything is ok on the Dashboard status exept the etc that is 'etcd not applicable'. But since the etcd ha is avaible and accesible, we should have the status ok on the dashboard.
If we go to the dashbord explorer in the Rancher/Cluster section we can see in the local entry this information:
..
  componentStatuses:
  - conditions:
    - message: ok
      status: "True"
      type: Healthy
    name: controller-manager
  - conditions:
    - message: '{"health":"true"}'
      status: "True"
      type: Healthy
    name: etcd-0
  - conditions:
    - message: ok
      status: "True"
      type: Healthy
    name: scheduler
..

So the status of etcd is there as long as the sceduler and the control pane. We should see the state of etcd also.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- 2.5.5.
- Installation option (single install/HA):
I use k3sup in order to deploy the k3s cluster. I deploy the v1.19.5+k3s1 version

Here is my recipe:

    3 node for the cluster and 2 worker nodes
    Used k3sup to deply the nodes
    node1:
    k3sup install
    --ip $SERVER_IP
    --user $USER
    --cluster
    --k3s-version v1.19.5+k3s1
    node2+3
    k3sup join
    --ip $NEXT_SERVER_IP
    --user $USER
    --server-user $USER
    --server-ip $SERVER_IP
    --server
    --k3s-version v1.19.5+k3s1

On worker nodes:
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.19.5+k3s1 K3S_TOKEN= K3S_URL=https://:6443 sh -

curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
chmod 700 get_helm.sh
./get_helm.sh

helm repo add rancher-stable https://releases.rancher.com/server-charts/stable

kubectl create namespace cattle-system

kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml

kubectl create namespace cert-manager

helm repo add jetstack https://charts.jetstack.io

helm repo update

export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

helm install
cert-manager jetstack/cert-manager
--namespace cert-manager
--version v1.0.4

helm install rancher rancher-stable/rancher
--namespace cattle-system
--set hostname=rancher.domain.com

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): baremetal
- Machine type (cloud/VM/metal) and specifications (CPU/memory): vm
- Kubernetes version (use `kubectl version`):
kubectl  version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+k3s1", GitCommit:"b11612e2744f39f01bfd208ff97315930c483667", GitTreeState:"clean", BuildDate:"2020-12-11T17:29:23Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5+k3s1", GitCommit:"b11612e2744f39f01bfd208ff97315930c483667", GitTreeState:"clean", BuildDate:"2020-12-11T17:29:23Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

kubectl get node
NAME       STATUS   ROLES         AGE     VERSION
node-1     Ready    etcd,master   2d16h   v1.19.5+k3s1
node-2     Ready    etcd,master   2d16h   v1.19.5+k3s1
node-3     Ready    etcd,master   2d16h   v1.19.5+k3s1
worker-1   Ready    <none>        2d16h   v1.19.5+k3s1
worker-2   Ready    <none>        2d16h   v1.19.5+k3s1

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by APoniatowski** [comment]
Having the same issue here

![image](https://user-images.githubusercontent.com/39518296/113573966-77048380-961b-11eb-8ac0-fee7f1e2832c.png)
