### ISSUE TITLE
Project network isolation can be enabled if RKE network plugin supports network policies

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#31338]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
When configuring an RKE network provider that supports Kubernetes network policies, such as the Cisco ACI CNI plugin, Rancher should allow the cluster option to enable Project Network Isolation to be set (`enable_network_policy: true`).

Currently, when enabling the network isolation with such a compatible network provider the cluster provisioning fails with a validation error.

The validation is implemented here:

https://github.com/rancher/rancher/blob/41045a8bd742ca24c69dc3a9d54a1888686c0159/pkg/api/norman/store/cluster/cluster_store.go#L713-L714

**Other details that may be helpful:**

Rancher 2.5.5

**Comment by ryansann** [comment]
# Support Matrix

Rancher RKE Cluster Project Network Isolation (PNI) support per CNI
| CNI | Supports PNI |
| ----------- | ----------- |
| Calico | Yes |
| Canal | Yes |
| Weave | Yes |
| ACI | Yes |
| None/Custom | Yes |
| Flannel | No |

# Testing

Currently Rancher only allows for PNI to be enabled when selecting the Canal Network Provider when provisioning an RKE cluster. These changes allow for PNI to be enabled when using other CNIs. 

Until [this UI issue](FILL ME IN) is complete, you can provision a cluster with PNI enabled by Selecting your CNI, editing the cluster as YAML, and flipping the top-level `enable_network_policy` field to true in the RKE config.

## Allowed Network Paths
With PNI enabled, and the below testing setup, these are the network paths that should be allowed
![pni-allowed](https://user-images.githubusercontent.com/8824599/114619804-c96b2300-9c5f-11eb-9c0e-7b7a4235034d.png)

## Disallowed Network Paths
And these are the network paths that should not be allowed
![pni-not-allowed](https://user-images.githubusercontent.com/8824599/114619836-cf610400-9c5f-11eb-81ff-66579a34e87d.png)

## Steps

1. Launch a cluster with a CNI that supports PNI (see support matrix above) and with PNI enabled
2. Create a project: `pni-testing` and a namespace within it `testing`
3. Launch the Rancher Hello World example as a workload in both the `default` and `pni-testing` projects, e.g. 
![hello-world](https://user-images.githubusercontent.com/8824599/114617707-5791da00-9c5d-11eb-9919-08ad2a20e6b0.png)
4. Create an ingress for each `hello-world` workload, e.g.
![hello-world-ingress](https://user-images.githubusercontent.com/8824599/114618015-b5bebd00-9c5d-11eb-881f-3200c0feb49e.png)
5. Navigate to the generated xip.io url of the ingress and validate that the hello-world application loads, e.g.
![hello-world-app](https://user-images.githubusercontent.com/8824599/114618196-eef72d00-9c5d-11eb-84e9-d1bf80159964.png)
Do this for the hello-world deployed in the `default` project and the `pni-testing` project
6. Deploy connection testing workloads
- NOTE: this step uses [this simple app](https://github.com/ryansann/conn-test)
- deploy `conn-test` workload to `default` project, which will be configured to talk to the `hello-world` workload in the same, `default` project. This is an allowed network path. e.g.
![conn-test-default](https://user-images.githubusercontent.com/8824599/114620846-d5a3b000-9c60-11eb-9416-4c0f60ff7793.png)
- deploy `conn-test-cross-proj` workload to `default` project. This workload is configured to talk to the `hello-world` workload in the `pni-testing` project. This is a disallowed network path as it crosses project boundaries e.g. 
![conn-test-cross-proj](https://user-images.githubusercontent.com/8824599/114621230-4cd94400-9c61-11eb-9eec-57aafbc74df7.png)
- repeat the above with the `pni-testing` project, i.e. deploy `conn-test` and `conn-test-cross-proj` there as well
- validate that all allowed network paths are in fact working and all disallowed network paths are receiving i/o timeouts. To do this, check that the logs of each `conn-test` workload have entries like `got succesful response: 200 OK` and each `conn-test-cross-proj` workload has logs like: `error calling http://hello-world.default.svc.cluster.local: Get "http://hello-world.default.svc.cluster.local": dial tcp 10.42.0.8:80: i/o timeout`
7. Repeat these steps for clusters provisioned with different CNIs that support PNI
