### ISSUE TITLE
EKS V2 - Rename Image Input

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#31341]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement - broken out from https://github.com/rancher/rancher/issues/31293

For EKS v2 cluster on create and edit rename Node Group `Image ID` field to `AMI ID`

**Comment by Ellenqs** [comment]
Validated on Rancher `v2.5-head , 03b8153` and `master-head bda4456`.

**Steps are same for both two verisons:**

- Deploy rancher single install.
- Select EKS cluster to config.
- Go to Node Group page.
- Check the  name of `IMG-ID` changed to `AMI-ID`.

**Results**

On both versions, we can see the name is changed to `AMI ID`.

<img width="1250" alt="Screen Shot 2021-02-17 at 3 22 04 PM" src="https://user-images.githubusercontent.com/75277058/108281253-441e3300-7134-11eb-88e2-f67143b0fca4.png">
