### ISSUE TITLE
saving agentEnvVars through v3 api only saves schema type Error: Invalid Value: spec.template.spec.containers[0].env

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31342]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy rancher v2.5-head (3e96d7f)
* deploy a downstream cluster 
* update agentEnvVars using v3 api (I set proxy settings HTTP_PROXY, HTTPS_PROXY, NO_PROXY

**Result:**
* this cluster and any subsequent clusters will have an error related to `spec.template.spec.containers[0].env`
* API is clearing the agentEnvVars set, and resetting with an empty name and the schema type
<img width="486" alt="Screen Shot 2021-02-12 at 3 06 37 PM" src="https://user-images.githubusercontent.com/16691014/108100752-2f11a900-703b-11eb-92b4-c12a799c7234.png">
<img width="318" alt="Screen Shot 2021-02-16 at 9 12 51 AM" src="https://user-images.githubusercontent.com/16691014/108100754-3042d600-703b-11eb-8bda-a76080277cbf.png">

**Other details that may be helpful:**
blocking ticket  https://github.com/rancher/rancher/issues/29993

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head (3e96d7f)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): tested with provisioned, imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

- Docker version (use `docker version`): tested 19.03 and 20.10

**Comment by slickwarren** [comment]
closing, reported this issue in the main ticket: https://github.com/rancher/rancher/issues/24876

**Comment by mightymouse2045** [comment]
> * update agentEnvVars using v3 api (I set proxy settings HTTP_PROXY, HTTPS_PROXY, NO_PROXY

How do you do this by the way?
