### ISSUE TITLE
Enhancement: remove unsupported 1.13 Docker version from Docker Install URL list

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#31340]
This is a breakout from issue rancher/rancher#31303 to just remove the specific 1.13 version from the list.

remove unsupported version 1.13 from our list of docker install urls

![image](https://user-images.githubusercontent.com/1955897/108096612-11633480-7079-11eb-908a-02fdc6e1bb72.png)

**Comment by Ellenqs** [comment]
Validated on Rancher `v2.5-head 03b8153`  and `master-head 007e298`.

**Steps**

- Try adding node templates, under `engine options`, check the docker install url dropdown.

**Results**

On both 2.5-head and master-head, the unsupported docker version (v1.13) has been removed.

<img width="248" alt="Screen Shot 2021-02-18 at 8 07 23 AM" src="https://user-images.githubusercontent.com/75277058/108395810-07514b00-71cb-11eb-90ef-de9773e9431c.png">
