### ISSUE TITLE
"Upgrade strategy needs to be set" but docs say Optional

### ISSUE THREAD

**Issue by untoldone** [rancher/rancher#3134]
I tried to POST to:

`curl --user <access>:<secret> -XPOST https://<rancher-host>/v1/projects/<project>/services/<service>/?action=upgrade`

and got

    {
      "id": "6b889bae-9e71-4e5d-aca1-ce33128d15ec",
      "type": "error",
      "links": {},
      "actions": {},
      "status": 422,
      "code": "MissingRequired",
      "message": null,
      "detail": null,
      "fieldName": "Upgrade strategy needs to be set"
    }

Yet the docs at http://docs.rancher.com/rancher/api/api-resources/service/ currently list all parameters as optional. Also worth noting is that I can't seem to find definitions of the parameter types anywhere in the docs: http://docs.rancher.com/rancher/api/api-resources/serviceUpgrade/. I ended up looking at the UI with a debugger to figure out the proper contents + type. Expected was that either parameters are optional or that docs reflect API.

Thanks!

**Comment by vincent99** [comment]
They are mutually-optional.. you need to send one or the other.  There is a page for those fields but they're not linked for some reason:

http://docs.rancher.com/rancher/api/api-resources/inServiceUpgradeStrategy/
http://docs.rancher.com/rancher/api/api-resources/toServiceUpgradeStrategy/

@prachidamle Can you look into why the links aren't generated there (or to any of the types in the above 2 links)

**Comment by prachidamle** [comment]
@vincent99 found the bug and added a fix to generate the links needed. PR https://github.com/rancher/go-rancher/pull/53 contains this fix as well.

**Comment by deniseschannon** [comment]
Fixed the docs based on PR and published it.

**Comment by deniseschannon** [comment]
Verified that latest docs generation fixes this issue.

**Comment by JulianKingman** [comment]
@deniseschannon I don't see them in the docs:
http://docs.rancher.com/rancher/api/api-resources/
