### ISSUE TITLE
Add GCP cloud credentials in UI

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#31346]
Add an option in the cloud credential dropdown for google cloud platform.
This will be a bit different as google provides credentials as one json blob instead of separate fields for each key.

Example: 
```
{
  "type": "",
  "project_id": "",
  "private_key_id": "",
  "private_key": "",
  "client_email": "",
  "client_id": "",
  "auth_uri": "",
  "token_uri": "",
  "auth_provider_x509_cert_url": "",
  "client_x509_cert_url": ""
}
```

Backend issue: https://github.com/rancher/rancher/issues/30981

**Comment by prabalsharma** [comment]
was tested via test plan
