### ISSUE TITLE
UI: Needs to hide the benchmark version rke-cis-1.6 and onwards for CIS v1 

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#31343]
This is the UI ticket for the backend issue: https://github.com/rancher/rancher/issues/31242

steps to reproduce (least amount of steps as possible):
Create a new custom cluster from ember UI, enabling Scheduled CIS scan with default profile RKE-CIS-1.6 ( RKE-CIS-1.6 Permissive and Hardened profiles affected)

Result:
Custom cluster creation fails with errors:

From ember UI error: Validation failed in API: cisScanHandler: error fetching benchmark version info rke-cis-1.6: cisbenchmarkversions.management.cattle.io "rke-cis-1.6" not found

From API: Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [baseType=error, code=InvalidBodyContent, message=cisScanHandler: error fetching benchmark version info rke-cis-1.6: cisbenchmarkversions.management.cattle.io "rke-cis-1.6" not found] from [https://<RANCHER_URL>/v3/clusters]

Other details that may be helpful:
The default CIS scan profile rke-cis-1.6 doesn’t exist at api https://<RANCHER_URL>/v3/cisbenchmarkversions nor https://<RANCHER_URL>/v1/management.cattle.io.cisbenchmarkversions

Setting CIS scan profile to rke-cis-1.5 (permissive or hardened) makes the cluster be deployed successfully.

I do not see it added into KDM cis_config either. So Backend  for CIS v1 does not support rke-cis-1.6

From where does UI list this version? Can we hide the CIs-1.6 benchmark versions for CIS v1?

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `3e96d7fb1`**

- Deploy a custom cluster
- From Ember UI, run CIS scans --> User is presented with following options:

<img width="760" alt="Screen Shot 2021-02-16 at 11 31 56 AM" src="https://user-images.githubusercontent.com/26032343/108112189-98e57f00-704a-11eb-8ebc-f570ec15ae59.png">

- Select RKE cis 1.6 permissive and click on run scan
- Error seen: `RunSecurityScan Error Validation failed in API: invalid override benchmark version specified is not a valid option`

**Comment by codyrancher** [comment]
@prachidamle the options weren't based off of `/v3/cisbenchmarkversions` it was based off of `/v3/cisConfig` which still contains 1.6. I don't recall why that choice was made but it was made in conjunction with the backend. Can you remove the version from there on the backend?

**Comment by prachidamle** [comment]
I see @codyrancher I will fix that - it got added recently to KDM by mistake it seems.

**Comment by prachidamle** [comment]
This is now seen fixed in latest v2.5-head, marking to-test.

**Comment by Ellenqs** [comment]
On Rancher `v2.5-head a85f4d1`.

- Deploy a custom cluster.
- From Ember UI, run CIS scans --> User is presented with following options which now has only CIS-1.5:
<img width="765" alt="Screen Shot 2021-02-22 at 3 58 21 PM" src="https://user-images.githubusercontent.com/75277058/108786498-98585700-7528-11eb-99fe-58c8d1cd2995.png">
- Select RKE cis 1.5 permissive and click on run scan. The scan pass.

<img width="1295" alt="Screen Shot 2021-02-22 at 4 08 33 PM" src="https://user-images.githubusercontent.com/75277058/108786579-be7df700-7528-11eb-8df6-ba841bc0eeb6.png">
