### ISSUE TITLE
Redeploy button does not work on deployments in Cluster Explorer UI

### ISSUE THREAD

**Issue by sadhugit** [rancher/rancher#31353]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
1. Go to any cluster and navigate to ClusterExplorer
2. Click on Workloads and create a deployment with any image in the default namespace
3. Once it's successful, login into the pod  and creates few files (#touch t1 t2)
4. select deployment and performs a redeployment operation.
**Result:**

Even though redeploy operation returns 200 success code, but in the background, it just refreshes the page. I ran the shell script[ a simple while loop] on the container. I redeployed, my script is continuously running even after redeploying, and all the previously created files t1,t2 still present after redeployment.

The same behavior **not** observed in the Cluster manager.

**Other details that may be helpful:**

**Environment information**
- Rancher version 2.5.5 ,also applicable to 2.5.3
- Installation option (single install/HA):

```
(paste the output here)
```

**Comment by vincent99** [comment]
https://github.com/rancher/dashboard/issues/1810
