### ISSUE TITLE
Rancher 2.5.5 node templates for Vsphere do not repopulate settings on edit

### ISSUE THREAD

**Issue by Pelmorex** [rancher/rancher#31356]
Rancher 2.5.5 node templates for Vsphere do not repopulate settings on edit.

When you open an existing vsphere node template for editing in the Rancher 2.5.5 GUI, the previous settings are not populated in the page.  All settings related to Vsphere as well as the network to deploy in are lost.

This only started to appear with upgrade to version 2.5.5
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.5` UI: `v2.5.4` |
|Route|`undefined`|

**Comment by stranljip** [comment]
Duplicate of #30891

**Comment by radekw** [comment]
I'm seeing the same behavior on v2.4.15. The issue seems to be fixed in v2.5.7 (but another [bug](https://github.com/rancher/rancher/issues/32120) appeared there).
