### ISSUE TITLE
Audit entries show the api calls made by rancher-compose-executor as being made by "machineServiceAccount".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3135]
Server version - v0.51.0-rc3

Create a stack from catalog entry.
Following are he audit log entries that appear:

<img width="718" alt="screen shot 2015-12-23 at 12 41 21 pm" src="https://cloud.githubusercontent.com/assets/4266958/11985576/0b95cf2e-a97b-11e5-9a0e-f113b6e57b28.png">

All the api calls made by rancher-compose-executor are shown as being made by "machineServiceAccount".

**Comment by hibooboo2** [comment]
@sangeethah The screenshot you posted does not seem to show anything other than a failed host connection. As for the logs showing that the requests are made by machineServiceAccout I believe that is the account that makes the requests. So why would it be an error that this is reflected in the logs?
