### ISSUE TITLE
[EKSv2] Disk size creates another disk instead of increasing root disk size

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#31361]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create an EKS cluster in Rancher without specifying a launch template
2. Check the "Storage" tab for one of the instances that are created for the cluster

**Result:**
There are two storage devices (/dev/xvda and /dev/sdr).

**Other details that may be helpful:**
This is not the intended outcome. There should be one storage device with the size specified by the user in the Rancher UI. This one device will have name /dev/xvda, in this case.

**Comment by aaronRancher** [comment]
Reproduced this issue on Rancher server `rancher\rancher:v2.5-head` `version 03b8153`

Steps:
Create an EKS cluster in Rancher without specifying a launch template.
Note the default volume size is 20 GiB.
Create cluster.
After cluster is becomes active, navigate to an instance in EKS console.
Navigate to storage tab:
![Screen Shot 2021-02-17 at 4 32 01 PM](https://user-images.githubusercontent.com/57409052/108281827-b8110900-713d-11eb-9937-56fe559b28c9.png)

There are two volumes with each with 20 GiB.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.5-head` `version b4be2b2`

Steps:
Create an EKS cluster in Rancher without specifying a launch template.
Note the default volume size is 20 GiB.
Create cluster.
After cluster is becomes active, navigate to an instance in EKS console.
Navigate to storage tab.

Result:
There is only 1 volume with size 20 GiB.
![Screen Shot 2021-02-22 at 9 20 05 AM](https://user-images.githubusercontent.com/57409052/108737189-9625d680-74ef-11eb-8ba4-d6895b9c624d.png)

**Comment by aaronRancher** [comment]
EKS operator version on `rancher\rancher:v2.5-head` `version b4be2b2`: `rancher/eks-operator:v1.0.6-rc4`
