### ISSUE TITLE
Audit Logs - Log information about entries deleted in audit_log table.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3136]
Server version - V0.51.0-rc3

Changed the setting - audit_log.purge.after.seconds to a lower value.
When the next cleanup thread executed , audit_logs that were older than the purge settings gets deleted from AUDIT_LOG DB. 
rancher server logs does not include the information about these deleted entries.

```
cattle-debug.log:2015-12-23 21:43:50,308 DEBUG [:] [] [] [] [ecutorService-9] [i.c.p.core.cleanup.TableCleanUp     ] Starting clean up for PROCESS_INSTANCE table, SERVICE_EVENT table, and CONTAINER_EVENT table. 
cattle-debug.log:2015-12-23 21:43:50,322 DEBUG [:] [] [] [] [ecutorService-9] [i.c.p.core.cleanup.TableCleanUp     ] Clean up for PROCESS_INSTANCE, SERVICE_EVENT, CONTAINER_EVENT and AUDIT_LOG tables finished.
```

**Comment by vincent99** [comment]
What is the bug here?  That the "Starting cleanup" doesn't say "AUDIT_LOG" but the "...finished" one does?

**Comment by sangeethah** [comment]
@vincent99 , when entries from audit_log get deleted , I don't see logs stating that the "n" number of entries were deleted from audit_log  similar to what we see when entries are deleted in process_instance table.

"""
Deleted 48 from PROCESS_INSTANCE in 58ms, 0 from SERVICE_EVENT in 5ms, and 0 from CONTAINER_EVENT in 0ms.0 from CONTAINER_EVENT in 2ms.
"""

**Comment by sangeethah** [comment]
Tested with latest build from master:

rancher-server logs includes the count of audit_log entries that were deleted as part of cleanup process.
```
2016-03-09 00:13:22,900 INFO  [:] [] [] [] [ecutorService-5] [i.c.p.core.cleanup.TableCleanUp     ] Deleted 0 from PROCESS_INSTANCE in 0ms, 0 from PROCESS_EXECUTION in 1ms, 0 from SERVICE_EVENT in 5ms, and 0 from CONTAINER_EVENT in 1ms.0 from CONFIG_ITEM_STATUS in 1ms, 6672 from AUDIT_LOG in 2882ms. 
```
