### ISSUE TITLE
Get "Cannot validate kube version for template" when trying to create a cluster with v0.2.0 monitoring

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#31364]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Run the following terraform to create a cluster:
```terraform
resource "rancher2_cluster" "cluster020" {
  name = "dnoland-test-cluster-0-2-0"
  description = "testing monitoring v0.2.0"
  rke_config {
    network {
      plugin = "canal"
    }
  }
  enable_cluster_monitoring = true
  cluster_monitoring_input {
    version = "0.2.0"
  }
}
```

**Result:**
Get the error:
Cannot validate kube version for template [system-library-rancher-monitoring-0.2.0]]

**Other details that may be helpful:**
Works fine if version = "0.1.4"

Looks like a "kubeVersion" was introduced in 0.2.0, that wasn't there in 0.1.4
```
k get catalogtemplateversions -n cattle-global-data system-library-rancher-monitoring-0.1.4 -ocustom-columns=NAME:metadata.name,KUBEVER:.spec.kubeVersion
NAME                                      KUBEVER
system-library-rancher-monitoring-0.1.4   <none>
k get catalogtemplateversions -n cattle-global-data system-library-rancher-monitoring-0.2.0 -ocustom-columns=NAME:metadata.name,KUBEVER:.spec.kubeVersion
NAME                                      KUBEVER
system-library-rancher-monitoring-0.2.0   >=1.16.0-0
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.5.5
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
AWS m5a.large
- Kubernetes version (use `kubectl version`):
```
> k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2+k3s1", GitCommit:"d38505b124c92bffd45f6e0654adb9371cae9610", GitTreeState:"clean", BuildDate:"2020-09-21T17:00:07Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
using containerd
```
gz#15192

**Comment by jiaqiluo** [comment]
The error happens because of the `kubeVersion` requirement which was introduced since Monitoring v1 chart `v0.2.0`: https://github.com/rancher/system-charts/blob/52be656700468904b9bf15c3f39cd7112e1f8c9b/charts/rancher-monitoring/v0.2.0/Chart.yaml#L12

```
kubeVersion: ">=1.16.0-0"
```

We need to update terraform example to mention this change.

**Comment by rawmind0** [comment]
@jiaqiluo , submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/589 mentioning kubeVersion requirement since V1 monitoring chart v0.2.0

**Comment by rawmind0** [comment]
PR already merged. Updated docs will be published at https://registry.terraform.io/providers/rancher/rancher2/latest/docs once we cut new tfp provider

Please, reopen issue if needed

**Comment by sowmyav27** [comment]
PR for docs: https://github.com/rancher/terraform-provider-rancher2/pull/589

**Comment by slickwarren** [comment]
just for clarity, installing monitoring 0.2.0 onward through terraform is unsupported at this time. Documentation has been updated to reflect this.

**Comment by RiccardoBoettcher** [comment]
> just for clarity, installing monitoring 0.2.0 onward through terraform is unsupported at this time. Documentation has been updated to reflect this.

When will that change? Is there a plan to do so?
How can one continue to provision the cluster_monitoring from terraform?
