### ISSUE TITLE
View/Edit Yaml does not work for a k8s 1.20 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31367]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a workload 
- Do a View/Edit Yaml when the workload is Active
- Error on UI:

<img width="1094" alt="Screen Shot 2021-02-17 at 6 29 43 PM" src="https://user-images.githubusercontent.com/26032343/108296355-3bd2f180-714e-11eb-8503-c92ea4a0dde6.png">

- Error seen in Network tab of dev console: `404 Not Found`

**Expected Result:**
User should be able to View/Edit yaml of the workload

**Other details that may be helpful:**
- Happens for an ingress/HPA also.
- Works fine on a 1.19.7 cluster

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `03b815317`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO rke
- Kubernetes version (use `kubectl version`):

```
1.20
```

- Docker version (use `docker version`):

```
20.10
```

**Comment by vincent99** [comment]
I presume this is from using K8s 1.20 and the new lack of a self link.

**Comment by sowmyav27** [comment]
I see this working on a 1.19k8s cluster and see the issue on a 1.20 k8s cluster.

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `1ee983f4`**

- Deploy a workload
- Do a View/Edit Yaml when the workload is Active
- View/Edit Yaml works
