### ISSUE TITLE
Support for Out-of-tree OpenStack cloud controller in Rancher

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#31369]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Description:**
The new [OpenStack CPO](https://github.com/kubernetes/cloud-provider-openstack) has many plugins useful to the users hosting their clusters on OpenStack.  The [OpenStack Cloud Controller Manager](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md) is of particular interest and arguably the most important of these plugins.

The in-tree cloud controller manager is deprecating in v1.20 and everyone will need to use out-of-tree cloud providers. Many large users rely on OpenStack for their infrastructure and Rancher UI could be enhanced to allow users to select "OpenStack" as a Cloud Provider option when creating a custom cluster. Users would then be able to provide openstack configuration options such as the `auth-url`, keystone `username`/`password`, `domain-id`/domain-name`, `tenant-id`, etc in the UI. When deploying the cluster, Rancher would automatically create the resources needed for the `openstack-cloud-controller-manager` workload.

This RFE was filed beginning of Oct 2020 but the scope of work for the inclusion of the vSphere and OpenStack out of tree drivers is large so splitting this off from https://github.com/rancher/rancher/issues/23357 as requested.

gz#12592

**Comment by GillesMocellin** [comment]
Don't forget OpenStack users !
SUSE provides OpenStack, it should be a Rancher main supported IaaS environment !

PS:
And think about OpenStack Magnum too KaaS
