### ISSUE TITLE
Rancher system-agent

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#31379]
This is used to track the efforts Chris Kim is making to rework the rancher-agent.
This is a WIP currently with a fork at https://github.com/oats87/rancher-agent

**Comment by Oats87** [comment]
The new Rancher agent is going to be called `system-agent` and will live in the `rancher/system-agent` repository.

**Comment by deniseschannon** [comment]
System-agent is now part of RKE2 provisioning and no specific testing needed around it.
