### ISSUE TITLE
Audit log - Links for some entries point to rancher server ui.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3137]
Server version - V0.51.0-rc3

For the following audit log entries , clicking on the link for resourcetype:id field takes us to rancher server ui:

container link:
<img width="1418" alt="screen shot 2015-12-23 at 2 16 06 pm" src="https://cloud.githubusercontent.com/assets/4266958/11986160/5a4dc58a-a981-11e5-9f42-73be8015e99e.png">

githubconfig link:
<img width="1408" alt="screen shot 2015-12-23 at 2 14 35 pm" src="https://cloud.githubusercontent.com/assets/4266958/11986167/6514c2d4-a981-11e5-9ae9-de6c63f43c3c.png">

stack link:
<img width="1432" alt="screen shot 2015-12-23 at 2 11 48 pm" src="https://cloud.githubusercontent.com/assets/4266958/11986169/6b4a37c4-a981-11e5-9f1c-fb06989c88a8.png">

**Comment by vincent99** [comment]
These don't have a `resource` link so shouldn't be linked.

**Comment by tfiduccia** [comment]
Version - Master Jan 07
Verified fixed
