### ISSUE TITLE
Vault Integration

### ISSUE THREAD

**Issue by blaggacao** [rancher/rancher#3138]
https://github.com/rancher/rancher/issues/1269

I want to suggest explicitly to genuinly support Hashicorp's vaultproject for Secrets Management as a first class rancher artifact. This is for conses gathering, please share your opinion or close if it is not inline with product strategy...

https://www.vaultproject.io/

**Comment by raphink** [comment]
:+1:

**Comment by laurentgrangeau** [comment]
+1
I would greatly appreciate this feature in the next release !

**Comment by crackmac** [comment]
👍

**Comment by hwinkel** [comment]
of course as Passwords in $ENVs is strictly avoided by the production security team and blocks some deployments

**Comment by cloudnautique** [comment]
This is being addressed in the secrets API

**Comment by raphink** [comment]
@cloudnautique is there a ticket to follow progress on this API, or is it already implemented?

**Comment by cloudnautique** [comment]
@raphink its largely to address: #1269

**Comment by deniseschannon** [comment]
Closing and testing with #1269 instead
