### ISSUE TITLE
Rancher 2.5.x Cluster Explorer favicon missing & title says Dashboard

### ISSUE THREAD

**Issue by nayrnet** [rancher/rancher#31396]
Story: As a Rancher User any time I browse away from Cluster Explorer I struggle to return to the tab as the Blue Cow Favicon is not displayed and the title just says "Dashboard" instead of "Rancher"

Attached screenshot comparison of Cluster Manager vs Cluster Explorer:

![Screen Shot 2021-02-19 at 2 23 41 PM](https://user-images.githubusercontent.com/3732081/108563070-195fe600-72be-11eb-956f-0a3cb33cda21.png)
![Screen Shot 2021-02-19 at 2 23 27 PM](https://user-images.githubusercontent.com/3732081/108563074-1a911300-72be-11eb-83aa-fc7eaa15a861.png)

**Comment by Tejeev** [comment]
It would be nice to have a new icon as the current one is used in a few other places (ZenDesk in particular)

**Comment by vincent99** [comment]
@nayrnet The icon was [fixed](https://github.com/rancher/rancher/issues/30499) in 2.5.6.

@Tejeev If you want a different icon, give a different one to ZenDesk.  We're not changing the public product because someone copied it from the UI into a random internal tool.

**Comment by Tejeev** [comment]
@vincent99 fair point
