### ISSUE TITLE
github accounts avatars are not shown anymore, identity api urls gives 404

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#3139]
we use github authentication.
When I upgraded to version v0.51.0 from v0.50.2 I just realised that the avatar images for the accounts are not resolvable, see image below, so I cannot distinguish any more the accounts, as there is no username text alternative to the image (never use only images). as you can see from the inspect there are lot of 404s on the avatars image urls.

![screenshot from 2015-12-24 18 33 28](https://cloud.githubusercontent.com/assets/320440/11996876/61009672-aa6d-11e5-817e-8e412ee4f9de.png)

**Comment by vincent99** [comment]
The username *is* shown, but requires loading the identity.  We store GitHub user_ids, not usernames, because you can change your username (and then worse, someone else can take your old one).

**Comment by ibuildthecloud** [comment]
@vincent99 why are we getting 404s?

**Comment by demarant** [comment]
@vincent99, @ibuildthecloud 

maybe the following info can help you replicate/debug

we use github groups

Via chrome inspect I looked at my specific username _demarant_ and user_id _320440_ 
the identity loading url I see in the browser failing with 404 is:

[our-rancher-server]/v1/identities/1igithub_user%3A320440

it is urlencoded. Than went manually  to the identities API just by going to
[our-rancher-server]/v1/identities
to verify if such identity is properly there
I find my account and clicked on it and got a different URL
[our-rancher-server]/v1/identities/1i!github_user:320440
and this one works properly! :)

So the URL used in the API calls is missing the excalmation mark *!* after the 1i and before the github_user id
 /v1/identities/1i!

so hopefully this is just a url rewriting issue.

**Comment by michaellopez** [comment]
+1

We are hitting this bug too but with OpenLDAP configuration. The `/admin/accounts` page is causing requests that 404. The audit log page on the other hand gets it right and its shown properly there.

I tracked it down to the missing exclamation mark too.

`<rancher>/v1/identities/1iopenldap_user%3Auid%3Dmichael%2Ccn%3Dusers%2Cdc%3Dsub%2Cdc%3Ddomain%2Cdc%3Dtld` causes 404.

`<rancher>/v1/identities/1i!openldap_user%3Auid%3Dmichael%2Ccn%3Dusers%2Cdc%3Dsub%2Cdc%3Ddomain%2Cdc%3Dtld` works correctly.

**Comment by tfiduccia** [comment]
version - master jan 07
Verified fixed
