### ISSUE TITLE
cattle-cluster-agent and cattle-node-agent got 400 Bad Request when ping

### ISSUE THREAD

**Issue by wangxi83** [rancher/rancher#31392]
Hi, all

I build up a HA rancher(v2.4.10) via K3S.

There're some special in the K3S cluster that 

1. I've changed the SRC_PORT and containerPort and hostPort of  DaemonSet:svclb-traefik, so that , My cluster listens at 30080 and 30443. All things goes well....I can visit rancher via https://my-domain:30443.
2. my-domain has a public-CA signed certificate.
3. my-domain is polled to 3 ips.  my-domain  ---> ip1, ip2, ip3

In above cases , cattle-cluster-agent and cattle-node-agent could not run, they are aways Unavailable and restarted.
The log shows that: 

```
INFO: Environment: CATTLE_ADDRESS=10.42.2.8 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_FEATURES=dashboard=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-68799f7d6b-qcwgh CATTLE_SERVER=https://my-domain:30443
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5
ERROR: https://my-domain:30443/ping is not accessible (The requested URL returned error: 400 Bad Request)
```

I don't know why I meet 400 Bad Request and what causes.

I tried `curl -k  https://my-domain:30443/ping` on a node, it repsonsed 400 Bad Request
I tried `curl -k  https://my-domain:30443/ping` on other machine, it responsed "pong" as well
I tried `curl -k https://my-domain:30443/ping` in rancher pod's shell, it repsonsed 400 Bad Request
I tried `curl -k https://rancher.cattle-system/ping` in rancher pod's shell, it repsonsed "pong"

Can anyone give some help! Thanks!!

**Comment by wangxi83** [comment]
I found that, if I use
`echo -n | openssl s_client -showcerts -connect my-domain:30443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /root/test.crt`
the content of test.crt is different between on node and on other machine
Why??what's happend??

**Comment by superseb** [comment]
Can you show the certificates? That is a good indication what is going wrong. If you are pointing it to 3 IPs, please query the IPs directly with a hostname (e.g. `curl --resolve`) or just point it to one IP if your DNS TTL is low enough to find what is causing the HTTP 400 and track it down from there (is it coming from NGINX, what is NGINX logging etc)

**Comment by wangxi83** [comment]
> Can you show the certificates? That is a good indication what is going wrong. If you are pointing it to 3 IPs, please query the IPs directly with a hostname (e.g. `curl --resolve`) or just point it to one IP if your DNS TTL is low enough to find what is causing the HTTP 400 and track it down from there (is it coming from NGINX, what is NGINX logging etc)

Finally, I've found it was an certificates error. 
In the node, wrong certificates got because of NAT configuration.

Thanks for your suggest!
