### ISSUE TITLE
vSphere node driver - VM deployed from content library always get placed in root folder instead of the one in node template.

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#31407]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create node template for vSphere with custom Folder and creation method as content library 
![node_template](https://user-images.githubusercontent.com/11064902/108619989-c0738780-744e-11eb-9995-07233154791b.png)

**Result:**
- VM gets created in root folder instead of the one mentioned in node template.
<img width="365" alt="vcenter_output" src="https://user-images.githubusercontent.com/11064902/108620010-eac54500-744e-11eb-9297-8e6dbda138a2.png">
**Other details that may be helpful:**

- Rancher trace log shows that the directory is indeed passed to `rancher-machine` via flag `vmwarevsphere-folder`
```
[TRACE] buildCommand args: [rancher-machine --debug create -d vmwarevsphere --engine-install-url https://releases.rancher.com/install-docker/19.03.sh --vmwarevsphere-cfgparam disk.enableUUID=TRUE --vmwarevsphere-datastore /NUCDC/datastore/DS01 --vmwarevsphere-network /NUCDC/network/DPortGroup 1 --vmwarevsphere-datacenter /NUCDC --vmwarevsphere-disk-size 20000 --vmwarevsphere-ssh-password tcuser --vmwarevsphere-folder /NUCDC/vm/test folder/k8s vms --vmwarevsphere-memory-size 2048 --vmwarevsphere-pool /NUCDC/host/esxi01.ansil.io/Resources --vmwarevsphere-creation-type library --vmwarevsphere-password Vmware@123 --vmwarevsphere-ssh-user-group staff --vmwarevsphere-vcenter-port 443 --vmwarevsphere-content-library test content library --vmwarevsphere-ssh-port 22 --vmwarevsphere-ssh-user docker --vmwarevsphere-username administrator@ansil.io --vmwarevsphere-vcenter 192.168.110.40 --vmwarevsphere-clone-from ubuntu-18-cloud-template --vmwarevsphere-cpu-count 2 --vmwarevsphere-cloud-config /RDEVSVNQER/cloud-config all-in-one-node1]
```
- Rancher trace log 
[rancher_node_driver_debug.log](https://github.com/rancher/rancher/files/6017410/rancher_node_driver_debug.log)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.11
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): v1.18.15-rancher1-1

gz#15270

**Comment by slickwarren** [comment]
on master-head (351f7ca04973c1f023653f171c0f621f31bf2ca2) I was able to set the folder, and the VM was correctly installed in that folder
<img width="197" alt="Screen Shot 2021-05-12 at 4 23 37 PM" src="https://user-images.githubusercontent.com/16691014/118056244-70fe7280-b33e-11eb-88ad-46d99217690d.png">
<img width="668" alt="Screen Shot 2021-05-12 at 4 23 19 PM" src="https://user-images.githubusercontent.com/16691014/118056247-722f9f80-b33e-11eb-8c6f-513eda591b62.png">

**Comment by slickwarren** [comment]
I was also able to set the folder to root and see that the VM was configured there correctly. These were both (this test and the one posted above) done with a content library template and on master-head (351f7ca)
