### ISSUE TITLE
Global Role `Create RKE Templates` is broken 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#31406]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- run rancher:v2.5-head 96dc20 in single-install mode
- as admin, add a standard user `user1`
- as admin, assign the global role `Create RKE Templates` to `user1`
![image](https://user-images.githubusercontent.com/6218999/108618160-03931380-73d9-11eb-89f2-1a1beb394385.png)

- log in as `user1`, go to Tools -> RKE Templates -> create a new RKE Template

**Result:**
Failed to create the RKE Template with the following error 
`
unable to access clusterTemplate by id: Forbidden 403: clustertemplates.management.cattle.io "ct-gfvsm" is forbidden: User "u-lhjpw" cannot get resource "clustertemplates" in API group "management.cattle.io" in the namespace "cattle-global-data"
`
<img width="927" alt="Screen Shot 2021-02-21 at 12 03 15 AM" src="https://user-images.githubusercontent.com/6218999/108618127-c595ef80-73d8-11eb-9308-f44181fdb1cd.png">

**More Info:**
It works on rancher:`v2.5.5`

**Comment by prachidamle** [comment]
Just tested with latest v2.5-head HA setup (30e53bd4927449b67b707164a3c9557fac2d9194), I cannot reproduce this issue.

This is what I did:
- Created an HA setup with v2.5-head (30e53bd4927449b67b707164a3c9557fac2d9194)
- Logged in as admin, created a rke template T1, admin could create the template
- Added a standard user user1
- Logged in as user1, tried creating rke template T2 - error denying create was presented as expected.
- Logged back as admin and edited user1 and assigned the "Create RKE Templates" permission
- Logged in as user1 and tried creating rke template T2 - successfully created.

<img width="1434" alt="Screen Shot 2021-02-23 at 3 26 13 PM" src="https://user-images.githubusercontent.com/1470602/108922302-bd61ce00-75eb-11eb-87ec-93dc5c5428e2.png">

**Comment by prachidamle** [comment]
@jiaqiluo Do you see this working as expected with latest v2.5-head?

**Comment by jiaqiluo** [comment]
I cannot reproduce the bug on the `v2.5-head` 30e53b single-install following exactly the same steps as the issue provides. 

Close the issue.
