### ISSUE TITLE
Rancher error syncing 'fleet'

### ISSUE THREAD

**Issue by agvaliente** [rancher/rancher#31400]
Hello

I have installed rancher rancher-2.5.5 on kubernetes 1.19, the pods rancher is reporting this error:

[ERROR] error syncing 'fleet': handler mcm-start: error running the jail command: exit status 2, requeuing

The option used was:

helm install rancher rancher-stable/rancher
--namespace cattle-system
--set hostname=rancher.ptmindra.net
--set ingress.tls.source=secret
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by agvaliente** [comment]
Hello

My details are:

Image rancher: rancher/rancher:v2.5.5
Installation option is single install

Kubernetes version is V1.19 in bare metal

I use CRIO as runtime of container:
OS-IMAGE		           CONTAINER-RUNTIME
CentOS Linux 7 (Core)        cri-o://1.19.0

**Comment by kryptonn** [comment]
Same here, did you figure out your problem ?

**Comment by krouma** [comment]
> Same here, did you figure out your problem ?

If you haven't found workaround yet, it is here: https://github.com/rancher/rancher/issues/27160#issuecomment-643653677
