### ISSUE TITLE
集群导入问题

### ISSUE THREAD

**Issue by wanglei2659297** [rancher/rancher#31409]
**What kind of request is this (question/bug/enhancement/feature request):question

**Steps to reproduce (least amount of steps as possible):**
控制台连不上集群了,显示集群不可用，如图：
![image](https://user-images.githubusercontent.com/37511495/108635512-b12a2380-74ba-11eb-8e5e-bc6d9d239352.png)
![image](https://user-images.githubusercontent.com/37511495/108635517-ba1af500-74ba-11eb-8cdc-11a31671d68d.png)

**Result:**

**Other details that may be helpful:**

我用rancher建立的集群，集群共有4台机器在腾讯云服务器中。
rancher控制台在阿里云服务器中，跟集群不在一个局域网中，一直运行的挺正常，但是现在rancher突然连不上集群了。

我想在想把rancher和集群都放到腾讯云里，在腾讯云里新建rancher，并把集群导入到这个新的rancher中，请问如何处理
rancher版本:2.4.5
k8s版本1.15

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM
- Kubernetes version (use `kubectl version`):1.15

```

```

- Docker version (use `docker version`):

```

```

**Comment by wanglei2659297** [comment]
建立集群的命令类似如下;

**Comment by wanglei2659297** [comment]
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.4.5 --server https://abcd1234.cn:55443 --token 9725xp9h2xp82d8w4f6579ggxr8ldvvcvzmffbp8q8wpjvgv585pl7 --ca-checksum 3ef8ab85606352c8d6d1becf429f2183bcc7943d8196beae8902f12b11b13118 --etcd --controlplane --worker

**Comment by kingsd041** [comment]
Please modify it to English and reopen it
