### ISSUE TITLE
60 queries/s from  idle rancher

### ISSUE THREAD

**Issue by dmzaytsev** [rancher/rancher#3141]
I have set two-nodes rancher cluster according http://docs.rancher.com/rancher/installing-rancher/installing-server/multi-nodes/
the cluster has idle state now, one environment, two hosts, no deployed containers.
But I see about 60 queries per second from rancher  on MySql instance
![image](https://cloud.githubusercontent.com/assets/9972909/12009264/bf6870aa-ac92-11e5-872f-09215a4155de.png)

does it have to be like that?

**Comment by will-chan** [comment]
I assume you are using latest (v0.51.0) release of rancher/server.  Does Google Cloud SQL tell which which query is hitting the DB?

**Comment by deniseschannon** [comment]
@dmzaytsev If you're able to provide more details, please re-open.
