### ISSUE TITLE
reload 3 or more pods, it cause deploy on the same hosts,and doesn't work

### ISSUE THREAD

**Issue by kwz1993** [rancher/rancher#31413]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
if I reload 3 or more pods, it cause deploy on the same hosts,and doesn't work.  it will be cause the CPU to rise abnormally,so that pods restart failed. 

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
rancher v2.4.8

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by vincent99** [comment]
Unless you specify an anti-affinity scheduling rule, there is no guarantee that multiple pods for a workload will end up on different nodes.

**Comment by admun** [comment]
I am seeing the same issue. I added a `app=xxx` label and from node scheduling add require rules to `key=app no in set value=xxx`

Not sure this is related to a old issue #14752

**Comment by vincent99** [comment]
What you have said there is "schedule this pod onto a node that does not have the *node* label app=boinc-client".  You don't have any nodes with that label, so this has zero effect on scheduling.

What you are saying you want is "schedule this pod onto a node that is not already running any *pods* with the label app=boinc-client".  This is called [pod anti-affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity).  UI support for  configuring these is only in the newer "Explorer" interface.

**Comment by admun** [comment]
@vincent99 ack. Yes, indeed I want pod anti-affinity.

As mentioned, the affinity block are added by the Rancher UI, not the explorer interface...

Let me give it a try and report back.

**Comment by admun** [comment]
confirmed able to setup pod anti-affinity using the pod scheduling tab in explorer UI
