### ISSUE TITLE
kube-api server unable to reach cluster admission webhooks 

### ISSUE THREAD

**Issue by alemsh** [rancher/rancher#31420]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug
**Steps to reproduce (least amount of steps as possible):**
I am not sure exactly when the issue occurred, only that it seems to now be affecting all webhooks.

The closest event I can see is starting after installing a new nginx ingress controller (via helm, with a new ingressClass)

**Result:**

Either creating new ingresses or certificates with cert manager will fail with the following:

`Error from server (InternalError): error when creating "nginx-ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post https://webtest-ingress-nginx-controller-admission.default.svc:443/networking/v1beta1/ingresses?timeout=10s: context deadline exceeded
`
**Other details that may be helpful:**

We are running canal for networking, vxlan backend. As far as I can tell, the nat rules seems to be correct.

I've tried reaching the webhook service using nsenter, which works going from the kubelet/other pods worker node to the service, but does not work when going from the kube-api server 

`nsenter -t 35876 -n wget --no-check-certificate --spider --timeout=300 http://10.43.207.108:443`

Canal configmap

```
apiVersion: v1
data:
  canal_iface: ""
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "WARNING",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {
              "type": "host-local",
              "subnet": "usePodCidr"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "/etc/kubernetes/ssl/kubecfg-kube-node.yaml"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]
    }
  masquerade: "true"
  net-conf.json: |
    {
      "Network": "10.42.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
  typha_service_name: none
  veth_mtu: "1450"
kind: ConfigMap
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Baremetal cluster provisioned via Rancher v2.4.5
- Machine type (cloud/VM/metal) and specifications (CPU/memory): CentOS 7, 3 etcd/controlplane nodes, 4 worker nodes
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

```

- Docker version: 
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.39
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:34:14 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:22:32 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

```

**Comment by maxisam** [comment]
i have similar issues. Mine is Calico.

**Comment by maxisam** [comment]
Switch to Weave. Problem solved. Something must wrong with the network policy thing.
