### ISSUE TITLE
Scale down option should be greyed out if there is only 1 etcd node

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#31424]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Rancher 2.5-head [2 etcd, 1 cp, 3 worker nodes] with drain before delete enabled for etcd.
2. Once the cluster is active, click on the scale down option until no etcd nodes are left
3. Cluster goes into error state.

**Result:**
Can we have the scale down option greyed out as the original "-" button, when we have only 1 etcd node.

<img width="300" alt="Screen Shot 2021-02-22 at 2 21 27 PM" src="https://user-images.githubusercontent.com/38144301/108778222-e9148380-7519-11eb-9dbb-1b85778af570.png">

Rancher | v2.5-a85f4d1f87feea0083ebf8ae517a140f39de7fbd-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher51

https://github.com/rancher/rancher/issues/22871

**Comment by westlywright** [comment]
With the action menu items are not disabled, they either appear or they don't. I suspect @sowmyav27 knows this but I wanted to make sure it was clear that the option won't be greyed out.

**Comment by anupama2501** [comment]
Rancher | v2.5-87006de30625c046523a329b03ea2580db35fb57-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher52

Created a cluster with 3 etcd, 2 cp , 1 worker node.
Scaled down the cp, worker and etcd until only one node is present and verified the scale down option is not present for any of the nodes.
<img width="300" alt="Screen Shot 2021-02-24 at 1 57 17 PM" src="https://user-images.githubusercontent.com/38144301/109071379-7f76af80-76a8-11eb-80c0-01553fe6f4ff.png">

**Comment by anupama2501** [comment]
Verfied on the master-head 

Rancher | master-465bb3b80cb9f2d8c002fa9d7c37be20d38ed411-head
User Interface | vmaster-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher52

Followed same steps as above and see the scale down option disappear if only 1 etcd,cp or worker node present.

<img width="240" alt="Screen Shot 2021-02-24 at 3 32 34 PM" src="https://user-images.githubusercontent.com/38144301/109080497-8a840c80-76b5-11eb-86d5-e6c6a7ae113f.png">
