### ISSUE TITLE
Nodes stuck in Removing state after upgrade to 2.5.6-rc5

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#31427]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install Rancher 2.5.3 HA RKE with a Windows downstream cluster 
  - 1 control plane, 1 etcd, 1 Linux worker, 3 windows workers
  - Windows 1909 was used for testing.
- Once the cluster is active, upgrade to 2.5.6-rc5
- After Upgrade, verify the cluster is active and agents upgraded in the downstream cluster.
- Remove one Windows node.

**Result:**

The windows node is stuck in removing state.

Server Logs show:

```
2021/02/22 23:28:57 [INFO] Deleted cluster node m-790a61b12701 [ip-ac1f0acb]
2021/02/22 23:29:18 [INFO] checking cluster [c-rdpf9] for worker nodes upgrade

2021/02/22 23:29:18 [ERROR] error syncing 'c-rdpf9/upgrade_': handler rke-worker-upgrader: failed to find plan for <Public_IP>, requeuing
W0222 23:31:47.179312       8 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2021/02/22 23:32:02 [INFO] checking cluster [c-rdpf9] for worker nodes upgrade
2021/02/22 23:32:02 [ERROR] error syncing 'c-rdpf9/upgrade_': handler rke-worker-upgrader: failed to find plan for <Public_IP>, requeuing
2021/02/22 23:35:11 [ERROR] Error during subscribe websocket: close sent
```

![Screen Shot 2021-02-22 at 4 46 51 PM](https://user-images.githubusercontent.com/27659/108785006-cf7d3700-752d-11eb-94c8-468a09d2dd0b.png)

**Environment information**
- Rancher version: `v2.5.6-rc5`
- Installation option: HA RKE

https://github.com/rancher/rancher/issues/30526

**Comment by sowmyav27** [comment]
on a fresh install of 2.5.6-rc5, deploy windows and linux clusters. Able to delete worker nodes successfully - both windows and linux nodes.

**Comment by aaronRancher** [comment]
On an upgraded HA setup from `v2.5.5` to `v2.5.6-rc5`. Upgraded k8s from `1.18.14-rancher1-1` to `1.18.16-rancher1-1` Able to delete worker node successfully.

**Comment by sowmyav27** [comment]
Seen happening on an AKS cluster. 

Steps taken:

- Deploy `v1.18.14` AKS cluster in 2.5.5
- Upgrade rancher to 2.5.6-rc5
- Upgrade k8s version of the cluster to `v1.19.7`
- The nodes are seen stuck in Removing/Cordoned state

<img width="830" alt="Screen Shot 2021-02-22 at 5 37 46 PM" src="https://user-images.githubusercontent.com/26032343/108792279-bed0bf00-7535-11eb-94f8-f3e1c567ee3b.png">

**Comment by sowmyav27** [comment]
**Reproduced this issue on an upgrade from 2.5.5 to 2.5.6-rc6**

- Deployed a windows node on 2.5.5
- upgrade rancher server to 2.5.6-rc6
- delete a windows worker node
- the node is stuck in `Waiting on user-node-remove_c-f9pt5` removing state

**Comment by sowmyav27** [comment]
**Verified on an upgrade from 2.5.5 to 2.5-head commit id: `87006de306`**

**Cluster#1**

- Deployed a windows node on 2.5.5
- upgrade rancher server to 2.5-head
- delete a windows worker node
- the node is stuck in `Waiting on user-node-remove_c-j5s46` status

**Cluster#2**

- Deploy v1.18.14 AKS cluster in 2.5.5
- Upgrade rancher to 2.5-head
- Upgrade k8s version of the cluster to v1.19.7
- The nodes are seen stuck in Removing/Cordoned state

**Comment by sowmyav27** [comment]
**Upgraded from 2.5.5 to 2.5-head commit id: `67228a3c`**

**Cluster#1**

- Deployed a windows node on 2.5.5
- upgrade rancher server to 2.5-head
- delete a windows worker node
- the node is deleted successfully from rancher UI. `Kubectl get nodes` on the cluster doesnt have the node (is deleted successfully)
