### ISSUE TITLE
agentEnvVars are being applied outside of the cluster they were added to

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31422]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* rancher on v2.5-head (b4be2b2)
* provision downstream cluster behind proxy (follow instructions [here for full downstream proxy instructions](https://github.com/rancher/rancher/issues/29993#issuecomment-782766995).  instructions for adding agentEnvVars through v3 api is also included there)
* delete downstream proxied cluster
* provision normal downstream cluster (not behind proxy)
* add a new git repo (example here for fleet)

**Result:**
fleet-agent has the error `level=error msg="Current credential failed, failing back to reregistering: Get \"https://<rancher_server_ip>/apis/fleet.cattle.io/v1alpha1/namespaces/cluster-fleet-default-<cluster_id>-<bundle_id>/bundledeployments\": proxyconnect tcp: dial tcp <proxy_private_ip>:<proxy_port>: i/o timeout"`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-head (b4be2b2)
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): proxied cluster -> imported, normal cluster -> linode provisioned
- Machine type (cloud/VM/metal) and specifications (CPU/memory): proxied cluster -> 2vCPU, normal cluster -> 4vCPU
- Kubernetes version (use `kubectl version`): v1.20.4

- Docker version (use `docker version`): v20.10.3

**Comment by kinarashah** [comment]
Should be fixed with https://github.com/rancher/rancher/issues/29993

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 31f00c1
rancher/fleet:v0.3.5-rc5

* Create a proxy server
* Create a Rancher server that is not behind a proxy (public IP only)
* Create a node with no public IP, configured to use a proxy, and install k3s on this node
* Import the proxied k3s cluster and include the proxy information in the Agent Environment variables section
* The k3s cluster registers successfully to the Rancher server
* Deploy a GitRepo to the imported & proxied k3s cluster
* The bundle deploys successfully
* Create a non-proxied Digital Ocean cluster
* The cluster creates successfully and the fleet agent does not try to connect to the proxy
* Create a GitRepo and see it deployed to the non-proxied downstream cluster successfully

Forwardport for master: https://github.com/rancher/rancher/issues/32244
