### ISSUE TITLE
[Monitoring V2] Missing Linux annotation in 9.4.203 rc versions

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#31421]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a downstream cluster and try to install Monitoring.

**Result:**
Linux-only does not show up for 9.4.203
![Screen Shot 2021-02-22 at 11 55 23 AM](https://user-images.githubusercontent.com/13127443/108762353-d9d70b00-7504-11eb-89a9-9970db4f0d81.png)

**Other details that may be helpful:**
This was because https://github.com/rancher/charts/commit/89059319985b502950cb5f5fd0a587d281c007ff#diff-93c5f8e80a04a2a5141b2c41f8f760a87649f1cd8a9b0112598103988b4f1317 seems to have been dropped during the charts script migration patch changes as seen here: https://github.com/rancher/charts/blob/5a770824e0324da7121229137e83b959a3a9c63b/packages/rancher-monitoring/generated-changes/patch/Chart.yaml.patch#L7-L15.

This is also confirmed in https://github.com/aiyengar2/charts-diff/blob/a6535725f6295921bd2c7bc830dad9f28b9a291a/diff/rancher-monitoring.diff#L17 (note: aiyengar2/charts-diff was a repository that tracked the differences between each chart from the currently released one during the migration), which shows that the annotation was removed but never added back.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head `b4be2b2`

**Comment by aiyengar2** [comment]
Testable on `9.4.203-rc04`, we should see Linux-only pop up for the latest RC on the UI (previous RCs do not need to be modified since they will not be released).

**Comment by jiaqiluo** [comment]
the fix is validated on v2.5-head a85f4d1

Results:
- the `Linux-only` label shows for monitoring chart `9.4.203-rc04`

<img width="1067" alt="Screen Shot 2021-02-22 at 2 35 16 PM" src="https://user-images.githubusercontent.com/6218999/108773612-dc912a80-751b-11eb-874b-cbaf2fb2626b.png">

- monitoring `9.4.203-rc04` is installed successfully into the downstream cluster
