### ISSUE TITLE
exec shell on GKE cluster fails with 1006 error

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31434]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On 2.5.6-rc5, launch a GKE cluster.
- Create a deployment
- Do an exec shell on it pod
- The shell gets closed with 1006 error
- Error In the console - `component.js:126 WebSocket connection to 'wss://<rancher-server>/k8s/clusters/c-t2w8z/api/v1/namespaces/default/pods/wk02-7df6d5f6f7-bfx46/exec?container=wk02&stdout=1&stdin=1&stderr=1&tty=1&command=%2Fbin%2Fsh&command=-c&command=TERM%3Dxterm-256color%3B%20export%20TERM%3B%20%5B%20-x%20%2Fbin%2Fbash%20%5D%20%26%26%20(%5B%20-x%20%2Fusr%2Fbin%2Fscript%20%5D%20%26%26%20%2Fusr%2Fbin%2Fscript%20-q%20-c%20%22%2Fbin%2Fbash%22%20%2Fdev%2Fnull%20%7C%7C%20exec%20%2Fbin%2Fbash)%20%7C%7C%20exec%20%2Fbin%2Fsh' failed: HTTP Authentication failed; no valid credentials available`

**Expected Result:**
Exec shell should work

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.6-rc5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): GKE hosted
- Kubernetes version (use `kubectl version`):

```
1.18
```

**Comment by thedadams** [comment]
In order to test this completely, leave the GKE cluster running for more an an hour (1 hour and 1 minute is fine). Then test to make sure everything works correctly. This was an auth problem and it takes an hour for the original token to expire.

**Comment by slickwarren** [comment]
this was tested on 2.5-head (f9b93ea78d49fb087aaa5be4b97517529638cba2) and executing into the shell both immediately and after 1+hours is now working as expected. Waiting on a build for master-head to confirm there as well.
