### ISSUE TITLE
Create a custom loadbalancer with automatic add / remove containers?

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#3143]
I found caddy webserver with proxy / lb feature, included (Let's Encrypt) https support which could be uses as http / https proxy. The configuration file is simple  and it should be easy to build a Caddy LB, but what's about automatic config changes (add / remove linked containers)?

Is there a (simple) way using the rancher api or a stand-alone docker container based solution?

**Comment by will-chan** [comment]
Today, Rancher programs the HAProxy directly but when we do a refactor of the LB Service code (post 1.0 GA), we will look into changing the behavior to sending config data to our metadata server and having our HAProxy LB read from that before programming itself.  With this, you can technically add any other LB engines like Caddy or NGINX although you will still need to create your own script/logic to read from the meta data and configuring the engine.

**Comment by pwFoo** [comment]
Hi @will-chan
nice improvements to Rancher / LBs!

Instead oft building my own LB lets encrypt integration to Rancher haproxy LB (via API, not the LE client) would be better.

But custom LB is also interesting feature.

**Comment by pwFoo** [comment]
For today use I created a Caddy webserver based ReverseProxy with Docker-Gen to update the configuration. Works fine as docker http/s revproxy with ssl support (LE integrated v0.8.0+).

Rancher LB will be used for other tcp connections like SSH. 
Once Rancher LB has integrated support for LE I'll switch back :)

**Comment by hwinkel** [comment]
should this be reopened, as @will-chan has mentioned custom load balancer will be added. we in example need to balance UDP traffic where custom LB may based on latest nginx comes in

**Comment by deniseschannon** [comment]
@hwinkel Are you looking for the refactor load balancer issue? 

https://github.com/rancher/rancher/issues/2179

**Comment by vincent99** [comment]
What Will is talking about is mostly refactoring the haproxy balancer to be more loosely coupled with cattle.

There should already be enough info in metadata to build your own balancer service, and we have no  immediate plans of actually building other implementations based on other software.

(And haproxy does not support UDP at all, as far as I know)

**Comment by macmladen** [comment]
@pwFoo Can you share your solution with Caddy? It sounds like an interesting solution.

**Comment by pwFoo** [comment]
It should be updated / improved in the future... But it should work.
https://bitbucket.org/pwFoo/docker-caddy-revproxy-gen/overview

**Comment by macmladen** [comment]
Thanks for sharing!

I am still looking for some solution to have my multiple container apps (docker4drupal.org 5 container that runs one Drupal site) that I start with `docker-compose` recognized with some proxy which will expose them to clients on port 80/443 with domain name (project1_nginx_1 to test1.example.com, project2_nginx_1 to test2.example.com). Obviously, I am not getting **netwoking** right ;)

**Comment by pwFoo** [comment]
>It should be updated / improved in the future... But it should work.
> https://bitbucket.org/pwFoo/docker-caddy-revproxy-gen/overview

It stops work if you use new Rancher Server because the ip address is empty (rancher network ip is set by label instead of ip value like done with docker native network).
