### ISSUE TITLE
Include kube-api audit log with Rancher Logging

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#31437]
Right now, the contents of `/var/log/kube-audit/` are not included with our setup of Logging on v1 or v2 it looks like. We should include that path for fluentd to pull from.

gz#15039

**Comment by dbason** [comment]
This could be achieved with a DaemonSet deploying FluentBit, or a new Logging object in v2.  I like the idea of having a Logging, as you can then isolate the flow of logs for the audit log.  As the audit log is often tied to compliance I think it's beneficial to have it isolated from other logging config/changes/
