### ISSUE TITLE
vSphere: tagging does not work

### ISSUE THREAD

**Issue by Xat59** [rancher/rancher#31433]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1/ create a vSphere node-template and add tags for testing purpose
2/ create a cluster on vSphere using the node-template created at step 1
3/ wait for the cluster to be created and ready
4/ k8s node VM in vSphere do not have the specified tags

In rancher-server logs I can see the tagging : 
`2021/02/23 09:51:29 [INFO] [node-controller-rancher-machine] (k8s01node4) Adding 3 tag(s) to VM`

**Result:**
In vSphere, the instance is not tagged : 

![image](https://user-images.githubusercontent.com/1276192/108829813-ef156d80-75c8-11eb-8269-0d6c485a1389.png)

**Other details that may be helpful:**
I am speaking about instance tagging into vSphere, not speaking about Kubernetes label or annotation.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/server:latest v2.5.5 
- Installation option (single install/HA): docker image

Thank a lot for the help .

**Comment by junkiebev** [comment]
I'm periodically seeing this in 2.5.12 as well.
