### ISSUE TITLE
Creating resources from YAML in a non-default namespace errors

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#31435]
The issue was originally recorded in their UI ticket, but the actual bug is a backend issue.

The UI ticket is rancher/rancher#1745 in /rancher/dashboard
(https://github.com/rancher/dashboard/issues/1745)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
https://github.com/rancher/dashboard/issues/1745#issuecomment-783765215

also see https://github.com/rancher/dashboard/issues/1745#issuecomment-783767887

**Comment by brendarearden** [comment]
Confirmed this fix was indeed a ui fix - will be closing this one as a duplicate and re-open the UI issue for testing.
