### ISSUE TITLE
Services as nested objects to stack

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3144]
and containers as nested objects for a service. It makes it easier to retrieve all services for stack and all containers for service w/o parsing /latest/containers latest/services.

With that change we have to reduce the size of metadata config file as it can grow huge, by avoiding duplicated content. For that, we are going to switch to .yml representation as this format supports references. 

Also we have to start versioning our metadata so backwards compatibility doesn't get broken.

**Comment by sangeethah** [comment]
Tested with latest build from master:

There is now support for returning service objects for  /stacks/<name>/services  and container objects for  /services/<name>/containers.  But the rancher-metadata versions 2015-07-25 and 2015-12-19 are interchanged for their return types which is tracked in #3194. 

Closing this issue.
