### ISSUE TITLE
Drain on delete for nodes in Rancher provisioned clusters fails when node is running Pods with emptyDir volumes

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#31455]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Rancher v2.5.2 instance
2. Provision a vSphere Node Driver clusters, with the vSphere Cloud Provider configured, with a single node controlplane/etcd node pool, and a two node worker node pool
3. Create a simple Deployment, I used nginx, with an emptyDir volume configured and a nodeSelector for the second worker node
4. Scale the worker node pool down to 1

**Result:**

The second worker node is deleted without being successfully drained, the Rancher Pod logs show the following sequence:

```
2021/02/24 13:49:41 [INFO] node [aseymour-worker2] requires draining before delete
2021/02/24 13:49:41 [INFO] node [aseymour-worker2] attempting to drain, retrying up to 3 times
2021/02/24 13:49:43 [ERROR] node [aseymour-worker2] kubectl drain error, retrying: exit status 1
[...]
2021/02/24 13:49:45 [ERROR] node [aseymour-worker2] kubectl drain error, retrying: exit status 1
[...]
2021/02/24 13:49:48 [ERROR] node [aseymour-worker2] kubectl drain error, retrying: exit status 1
2021/02/24 13:49:48 [INFO] [node-controller-rancher-machine] About to remove aseymour-worker2
[...]
2021/02/24 13:49:49 [INFO] [node-controller-rancher-machine] Successfully removed aseymour-worker2
```

**Other details that may be helpful:**

Without the `delete-local-data=true` option a drain will fail if the node has Pods using an emptyDir volume, this option should be added to the drain on delete logic. Arguably we should also use the force=true option, in case there are Pods "not managed by a ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet." The node is about to be deleted, so local data/un-managed Pods should not prevent draining, which needs to occur to ensure vSphere Cloud Provider volume vmdks are not deleted.

**Environment information**
- Rancher v2.5.2

**Comment by sowmyav27** [comment]
**On 2.5-head**

see the same issue for an AWS node driver cluster with drain on delete enabled.

- Deploy a node driver cluster, enable drain on delete on the worker nodes.
- Create a pod with emptyDir Volumes

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
```


**Result:**
Rancher logs:
```
2021/02/25 17:01:41 [INFO] node [sowmya-delete-6] requires draining before delete
2021/02/25 17:01:41 [DEBUG] node [sowmya-delete-6] has no NodeDrainInput, creating one with 60s timeout
2021/02/25 17:01:41 [INFO] node [sowmya-delete-6] attempting to drain, retrying up to 3 times
2021/02/25 17:01:42 [ERROR] node [sowmya-delete-6] kubectl drain error, retrying: exit status 1
2021/02/25 17:01:44 [ERROR] node [sowmya-delete-6] kubectl drain error, retrying: exit status 1
2021/02/25 17:01:46 [INFO] Updated cluster [c-wbp78] with node version [1]
2021/02/25 17:01:46 [INFO] Provisioned cluster [c-wbp78]
```


**Other details that may be helpful:**
Similar to this issue - https://github.com/rancher/rancher/issues/31455

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `30e53bd`
- Installation option (single install/HA): single

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head f9b93ea

* First reproduced in `rancher/rancher:master-head  465bb3b` (build from 2/24) by following the steps above, and also including a vSphere volume in the same workload
```
2021/02/25 23:42:32 [INFO] Updating cluster [c-np64m]
2021/02/25 23:42:32 [INFO] Removing node bmd-vsdrain2-w2
2021/02/25 23:42:32 [INFO] node [bmd-vsdrain2-w2] requires draining before delete
2021/02/25 23:42:32 [INFO] Creating system token for u-7hgg3gdrjq, token: node-removal-drain-u-7hgg3gdrjq
2021/02/25 23:42:32 [INFO] node [bmd-vsdrain2-w2] attempting to drain, retrying up to 3 times
2021/02/25 23:42:33 [ERROR] node [bmd-vsdrain2-w2] kubectl drain error, retrying: exit status 1
2021/02/25 23:42:35 [ERROR] node [bmd-vsdrain2-w2] kubectl drain error, retrying: exit status 1
```
* After the node is deleted without drain, the replacement pod cannot mount the vSphere volume:
```
Warning	FailedAttachVolume	Multi-Attach error for volume "pvc-fcda09db-ed3a-4d5f-9972-7481c3ac9232" Volume is already exclusively attached to one node and can't be attached to another
```
--

Tested the same scenario on `rancher/rancher:v2.5-head f9b93ea`:
* The node to be removed is cordoned and drained successfully:
```
2021/02/26 00:12:19 [INFO] node [bmd-drain99-w2] kubectl drain response: node/bmd-drain99-w2 cordoned
WARNING: ignoring DaemonSet-managed Pods: cattle-system/cattle-node-agent-gbx4s, ingress-nginx/nginx-ingress-controller-rbp8k, kube-system/canal-r2qvr
evicting pod kube-system/coredns-6f85d5fb88-5gc4m
evicting pod default/test2-79978dcb6b-z7d59
pod/test2-79978dcb6b-z7d59 evicted
pod/coredns-6f85d5fb88-5gc4m evicted
node/bmd-drain99-w2 evicted

2021/02/26 00:12:19 [INFO] [node-controller-rancher-machine] About to remove bmd-drain99-w2
2021/02/26 00:12:19 [INFO] [node-controller-rancher-machine] WARNING: This action will delete both local reference and remote instance.
2021/02/26 00:12:20 [INFO] [node-controller-rancher-machine] (bmd-drain99-w2) Removing cloud-init.iso
2021/02/26 00:12:21 [INFO] [node-controller-rancher-machine] Successfully removed bmd-drain99-w2
```
* The replacement pod is scheduled and contains all volumeMounts (emptyDir and vSphere volume)

Still needs to be tested on `master-head`

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `f9b93ea78`**

- Deploy a node driver cluster, enable drain on delete on the worker nodes.
- Create a pod with emptyDir Volumes

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
```


**Result:**
Rancher logs:
```
021/02/26 06:57:36 [INFO] node [sowmya-aws-w2] kubectl drain response: node/ip-<>.us-east-2.compute.internal cordoned
WARNING: ignoring DaemonSet-managed Pods: cattle-system/cattle-node-agent-kxpz5, ingress-nginx/nginx-ingress-controller-m4ncr, kube-system/canal-h6wbx; deleting Pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet: default/test-pd
evicting pod default/test-pd
pod/test-pd evicted
node/ip-<>.us-east-2.compute.internal evicted
```
- The pod gets evicted and deleted as expected.

Waiting for builds on master-head
