### ISSUE TITLE
Remove Rancher Data

### ISSUE THREAD

**Issue by michaelkoro** [rancher/rancher#31458]
**What kind of request is this (question/bug/enhancement/feature request):**
question/bug

**Steps to reproduce (least amount of steps as possible):**
- Install Rancher with Helm on AWS EKS
- Helm delete rancher release
- Re-install rancher with helm

**Result:**
Rancher will be deployed but its data is "corrupt". admin password must be reset when trying to access the UI, and once you’re in, the local EKS (on which Rancher was installed), will be marked as "removing", with the following error:
"waiting on cluster-scoped-gc".
So my question is - when I remove the rancher release, how can I guarantee all rancher data is deleted ? and also, how do I know, and how can I manage where Rancher stores all its data ?
It is also worth noting That I removed all rancher-created resources manually using the attached script.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5
- Installation option (single install/HA): HA

Thanks !

[cleanup.txt](https://github.com/rancher/rancher/files/6037316/cleanup.txt)

**Comment by juanmancebo** [comment]
+1
