### ISSUE TITLE
How to renew serving-cert?

### ISSUE THREAD

**Issue by tommc3** [rancher/rancher#31459]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
- Install HA Rancher with RKE and Let's Encrypt
- Goto Local Cluster, System Project, Secrets, Certificates

**Result:**
- Serving cert expires after 1 year
![Screen Shot 2021-02-24 at 9 02 23 AM](https://user-images.githubusercontent.com/410664/109037356-7b826780-767f-11eb-8a08-dcb018101164.png)

What is the best practice to renew this certificate?

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Ubuntu VM on AWS
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by Leen15** [comment]
UP.
Any response to this?
My serving-cert certificate is expired and I cannot connect to my clusters.

Thanks
