### ISSUE TITLE
Node getting overwhelmed with rancher-agent containers when running with cgroups v2

### ISSUE THREAD

**Issue by daddz** [rancher/rancher#31454]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Create new node with cgroups v2 activated (kernel boot parameter: systemd.unified_cgroup_hierarchy=1)
2. Create new cluster with "existing nodes"
3. Add node with cgroups v2 with all roles (etcd, cp, worker)

**Result:**
* 'share-mnt' container fails constantly with the following log message:
```
INFO: Arguments: -- share-root.sh docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.5-87006de30625c046523a329b03ea2580db35fb57-head --server <REDACTED> --token <REDACTED> --no-register --only-write-certs --node-name <REDACTED>
+ trap 'exit 0' SIGTERM
++ grep :devices: /proc/self/cgroup
++ head -n1
++ awk -F/ '{print $NF}'
++ sed -e 's/docker-\(.*\)\.scope/\1/'
+ ID=
+ bash -c 'docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:v2.5-87006de30625c046523a329b03ea2580db35fb57-head --server https://<REDACTED> --token <REDACTED> --no-register --only-write-certs --node-name <REDACTED>'
1db2b0c1cc5b4d599f7c4403b5bff20aa4e4deda2d7bcca49c37f006099553cf
+ docker kill --signal=SIGTERM
docker: "kill" requires a minimum of 1 argument.
See 'docker kill --help'.
Usage:  docker kill [OPTIONS] CONTAINER [CONTAINER...]
Kill a running container
```
* New rancher-agent containers are getting spawned over time
* Node dies when running out of memory due to huge number of rancher-agent containers

**Workaround:**
* Revert to cgroups v1
* Cleanup all containers on the node and recreate cluster

**Notes:**
* Maybe related to https://github.com/rancher/rancher/issues/14735

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-87006de30625c046523a329b03ea2580db35fb57-head
- Installation option (single install/HA): single

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:32 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Comment by daddz** [comment]
Forgot to add this:
Docker daemon is also running with the systemd cgroupdriver - `daemon.json`:
```
{
    "exec-opts": ["native.cgroupdriver=systemd"]
}
```
Not sure if this has any effect on the issue but the workaround is still working with this cgroup driver.

**Comment by Goldcap** [comment]
Having the same issue, running CGroups2 on CentOS nodes, but we just schedule duplicate agent removal via cron :) This is not, however, a trivial issue, and would be great for Rancher folks to take a look.

**Comment by Confusingboat** [comment]
I started seeing this issue on my openSUSE MicroOS nodes after they enabled cgroups v2 by default earlier this year. The workaround seems to work, but I would like to not have to revert to cgroups v1.

When considering the fact that SUSE acquired Rancher last year, and how potentially convoluted diagnosing the symptoms this bug presents can be, I would view this as a high priority issue, since it prevents SUSE's own products from working together correctly out of the box.

**Comment by harridu** [comment]
metoo, using Debian 11

**Comment by JumpMaster** [comment]
Seeing this issue on Debian 11 too.

**Comment by bangbang93** [comment]
> Seeing this issue on Debian 11 too.
> 
> Rolling back to cgroup v1 appears to fix this.
> 
> ```
> vi /etc/default/grub
> 
> GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
> 
> sudo update-grub
> ```

confirmed resolve with rolling back to cgroup v1. So maybe something with cgroup v2?
Debian 10 is fine. Debian 11 is 100% reproducable.

**Comment by proligde** [comment]
Same problem on Ubuntu 21.10 with `5.13.0-21-generic`

I added the `GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"`, updated grub, rebooted. I also restarted docker daemon with cgroup drvier `systemd`, which indeed didn't change the behaviour.

Problem: I still get loads of agent containers due to the `share-mnt` container crashlooping.

I'm afraid this is due to the workaround step I skipped: `deleting all containers and recreating the cluster`. Is there a nicer way to circumvent the problem? Like removing all agents (including `share-mnt`) and re-executing the docker command adding the node to the cluster? 

Thanks in advance for any help.

**Comment by PhilipSchmid** [comment]
unstale

**Comment by qeternity** [comment]
This issue is not resolved, and is prevalent on a cluster that has been upgraded to 22.04

**Comment by qeternity** [comment]
> > Seeing this issue on Debian 11 too.
> > Rolling back to cgroup v1 appears to fix this.
> > ```
> > vi /etc/default/grub
> > 
> > GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
> > 
> > sudo update-grub
> > ```
> 
> confirmed resolve with rolling back to cgroup v1. So maybe something with cgroup v2? Debian 10 is fine. Debian 11 is 100% reproducable.

This fix indeed works for us. Very confused as this has been marked resolved. It is anything but.

**Comment by neseih** [comment]
It seems related to an old rancher-agent version (In my case it was 2.5.9)
The following helped on Ubuntu 22.04 without changing grub options (BEWARE: EVERYTHING IS RESET ON THAT NODE, MAKE BACKUP OF ALL FILES)
- remove node from rancher
- Execute cleanup script: ```curl -sLO https://github.com/rancherlabs/support-tools/raw/master/extended-rancher-2-cleanup/extended-cleanup-rancher2.sh```
- Re-register node with latest registration script (my version: v2.8.1)
- check with docker ps -a | grep share-mnt, should say Exited (0)...

**Comment by Vashiru** [comment]
Seeing this issue as well. Ubuntu 22.04, was running 18.04 up until earlier today and working fine. Rancher agent is v2.4.4.

Setting the cgroup to cgroupv1 as @JumpMaster suggested resolves the issue. Wonder if it's safe to just update the Rancher agent version...

**Comment by cclose** [comment]
I was having a similar issue with this as well. The cgroup to v1 change didn't fix it for me at first.

I was running Ubuntu 22.04, Rancher2.5.5, and Docker 27.x
Tried the above fix, still had runaway rancher-agents.
Downgraded Docker to 24.0.2 and the issue stopped (letting containerd version track w/e docker-ce wanted, i think 1.6.x)

The real fix is to update Rancher, but need to update a lot of nodes first to be able to do so.
