### ISSUE TITLE
AKS v2 Provisioner: add Register Cluster option

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#31462]
For the AKS v2 Provisioner, we need to add a function to register a cluster. This should match what we do in EKS currently (let us know if you need details on that).

**Comment by cbron** [comment]
PR https://github.com/rancher/rancher/pull/31333

**Comment by prabalsharma** [comment]
can only be fully tested when UI is available (to make sure clusters are listed to select for import)

**Comment by prabalsharma** [comment]
https://zube.io/rancher/rancher/c/39023

**Comment by prabalsharma** [comment]
tested via test plan
