### ISSUE TITLE
GKE v2 Provisioner: add Register Cluster option

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#31461]
For the GKE v2 Provisioner, we need to add a function to register a cluster. This should match what we do in EKS currently (let us know if you need details on that).

**Comment by cmurphy** [comment]
This will need the UI to be done to fully test. In the UI, you should be able to select a cloud credential, and then be able to select from a list of clusters that already exist in GKE. Should test that it gets registered successfully, that you have kubectl access to it, that properties like the kubernetes version are visible from the rancher UI, and that changes made from Rancher or from the GKE console don't overwrite each other.

**Comment by prabalsharma** [comment]
This was tested via test plan
