### ISSUE TITLE
Can't create EC2 Node Templates from UI as Standard User on master

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#31469]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install latest master-head Rancher
- Create an standard user
- Login as a standard user
- Create an EC2 cloud credential
- Try creating a node template

**Result:**

`MissingParameter: The request must contain the parameter AWSAccessKeyId`

![Screen Shot 2021-02-24 at 5 37 07 PM](https://user-images.githubusercontent.com/27659/109086275-831a2e80-76c8-11eb-9137-a60121366b20.png)

**Other details that may be helpful:**

Can't reproduce on `v2.5-head` _87006de_
Linode provider is working on master.

**Environment information**
- Rancher version: `master-head (02/24/2021)` _465bb3b_
- Installation option: HA/Single

**Comment by sowmyav27** [comment]
Dup of https://github.com/rancher/rancher/issues/31319. Closing this one
