### ISSUE TITLE
View Edit/Yaml for workloads fails for a k8s 1.20 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31467]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a 1.20 k8s cluster.
- Deploy a daemonset/statefulset/Cron type workloads.
- View/Edit Yaml of the workloads 
- Error seen

![Screen Shot 2021-02-24 at 3 56 07 PM](https://user-images.githubusercontent.com/26032343/109082425-d5ebea00-76b8-11eb-827f-2e097109b94c.png)

- API request response:
```
apiVersion: v1
code: 404
details: {}
kind: Status
message: the server could not find the requested resource
metadata: {}
reason: NotFound
status: Failure

```

**Other details that may be helpful:**

- Related to: https://github.com/rancher/rancher/issues/31367
- View/Edit Yaml of a deployment/Job type workoads works.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `87006de`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE cluster
- Kubernetes version (use `kubectl version`):

```
1.20
```

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:v2.5-head` `version f9b93ea`
Steps:
1. Launch a k8s `v1.20.4-rancher1-1` cluster.
2. Create the following types of workloads:
  - Deployment
  - Daemonset
  - Statefulset
  - Cron
  - Job
3. View YAML in each workload.
Ex:
![Screen Shot 2021-02-25 at 3 22 38 PM](https://user-images.githubusercontent.com/57409052/109227293-5542f180-777d-11eb-88b7-d41ae616e163.png)
4. Edit YAML in each workload (except job).
- Tested by changing the image. Saw workloads update.

**Comment by aaronRancher** [comment]
This issue is still seen in `rancher\rancher:master-head` `version 465bb3b`
The following workloads see an error when attempting to view YAML:
Cron
Daemonset
Statefulset
![Screen Shot 2021-02-25 at 3 14 47 PM](https://user-images.githubusercontent.com/57409052/109227499-a81ca900-777d-11eb-962b-f73e6c8e5c34.png)

The following workloads can view and/or edit YAML:
Deployment
Job

Reopening for fix.

**Comment by StrongMonkey** [comment]
@aaronRancher Master-build is failing. Make sure the commit is newer than https://github.com/rancher/rancher/commit/d343acc9faf6d24f82c3c2a38f4542080a3194c1 and then test it.

**Comment by aaronRancher** [comment]
Will track the master-head build in a forwardport: https://github.com/rancher/rancher/issues/31524
Closing with findings from v2.5-head.
