### ISSUE TITLE
Support for private catalogs with Git SSH protocol

### ISSUE THREAD

**Issue by johnrengelman** [rancher/rancher#3147]
It would be nice to be able to specify the connection information for a private Git repository when adding a catalog entry. This would include the private SSH key to use for connecting when using the `git+ssh` protocol.

**Comment by mcuadros** [comment]
If you wish to use private repositories is better use https protocol and a token, we are running our private catalog using this pattern and works perfect.

`https://<your-token>:@github.com/your/private-catalog`

**Comment by CBR09** [comment]
+1

**Comment by airtonix** [comment]
@mcuadros that only works for github. What about bitbucket, private stash, private gitlab, private other git.

What you really need to be doing is this:

```
[ + ] Add Catlog

[  Catalog Name                                            ] [ Catalog URI                                         ]
one of the following:
-  [ Button Upload: Private Key ]
-  [ Button: Generate SSH Key ]
```

**Comment by SydOps** [comment]
+1 for this feature

**Comment by shoutcool** [comment]
+1 this feature would be great. 
We normally work with Bitbucket over ssh URLs. So we had to enable the http access to Bitbucket, just because of Rancher

**Comment by jlee70** [comment]
+1

**Comment by juanfont** [comment]
+100000

**Comment by gerhro** [comment]
+1

**Comment by swartel-fa** [comment]
+1

**Comment by NDevox** [comment]
+1. This is a serious problem for some businesses.

**Comment by ekristen** [comment]
+1

**Comment by gcallsen** [comment]
+1

**Comment by leroy0211** [comment]
+1

**Comment by Kurisutian** [comment]
+1
Definitely something I would also need when using rancher at our company. It's a must have to me!
Any status updates as it's tagged for a closed milestone?

**Comment by swartel-fa** [comment]
up please

**Comment by royerhq** [comment]
+1

**Comment by superseb** [comment]
Closing this as duplicate of https://github.com/rancher/rancher/issues/3248, it will be referenced.
