### ISSUE TITLE
Ability to generate random password in UI when editing an existing user

### ISSUE THREAD

**Issue by sadhugit** [rancher/rancher#31478]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Request to add a "Generate" UI Object to generate random passwords in the **Edit User** page. 

i.e., Currently, Rancher provides a "Generate" option to generate a password for new user creation.  It would be better to have the generate random password option available in UI when editing the user.

gz#15326

**Comment by leodotcloud** [comment]
The new UI in the upcoming 2.6 release doesn't have this problem.
