### ISSUE TITLE
Enable nginx-ingress-controller:nginx-0.43.0-rancher1 for k8s v1.19

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#31480]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Kubernetes v1.19.x custom cluster with Rancher v2.5.5
2. Configure the ingress-nginx validating admission webhook
3. Attempt to deploy a `networking.k8s.io/v1` apiVersion ingress resource

**Result:**

Ingress fails the validating webhook with the following error:

```
error when creating "ingress.yaml": admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: rejecting admission review because the request does not contains an Ingress resource but networking.k8s.io/v1, Resource=ingresses with name testingress in namespace test
```

Kubernetes v1.19 introduced stable support for ingresses within the `networking.k8s.io/v1` apiVersion and attempting to create ingress resources with the apiVersion `networking.k8s.io/v1beta1` results in a warning of the following format:

```
Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

rancher/nginx-ingress-controller:nginx-0.35.0-rancher2, currently the default for RKE provisioned v1.19 clusters, lacks support for  `networking.k8s.io/v1` in the validating admission webhook. This was enabled with v0.40.0 (https://github.com/kubernetes/ingress-nginx/pull/6187 https://github.com/kubernetes/ingress-nginx/commits/controller-v0.35.0/internal/admission/controller/main.go). rancher/nginx-ingress-controller:nginx-0.43.0-rancher1 will be the default ingress-nginx version for RKE provisioned v1.20 clusters. Request here is to backport this for future v1.19 patch releases, so users who enable the ingress-nginx validating webhook can create ingress resources in `networking.k8s.io/v1`, as expected.

**Environment information**
- Rancher v2.5.5
- K8s v1.19.x

**Comment by Jono-SUSE-Rancher** [comment]
We should back port this for k8s:

- 1.19
- 1.18
- 1.17

**Comment by deniseschannon** [comment]
In 2.5.11. 1.19.16 is shipped with rancher/nginx-ingress-controller:nginx-0.49.3-rancher1
