### ISSUE TITLE
Bug: `management.cattle.io.token` schema is unavailable to `standard-user`

### ISSUE THREAD

**Issue by richard-cox** [rancher/rancher#31482]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Access `/v1/schemas/management.cattle.io.token` whilst logged in as a standard-user

**Result:**
```
{
"type": "error",
"links": { },
"code": "NotFound",
"message": "no such schema",
"status": 404
}
```

**Other details that may be helpful:**
In Cluster Manager API Keys are managed by the Norman `token` schema. This is usable by admins and standard-users. In 2.5.6 the new Cluster Explorer keys feature is managed by the new Steve `management.cattle.io.token` schema. This is retrievable by admins but not standard-users.

Note - The explorer still uses the old Norman endpoint to create tokens

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.5.3
- Installation option (single install/HA):
Single install via helm

**Comment by deniseschannon** [comment]
This isn't a backend bug but per @ibuildthecloud the UI should be using the Norman API for API key management.
