### ISSUE TITLE
Permission denied (publickey) when attempting to SSH into Rancher Server

### ISSUE THREAD

**Issue by PatrickLownds** [rancher/rancher#31481]
****I'm new to Rancher**. I've followed the docs to build out a quickstart environment in Azure and after getting over a few hurdles with some gaps I've managed to get Rancher Server deployed. I seem to be having trouble connecting via SSH to the Rancher node (to run rke) It seems like a certificate authentication issue. I've just used the terraform scripts in the quickstart repro. What do I need to do to get authentication working via SSH?:**

**ssh -i ~/.ssh/ubuntu ubuntu@public_ip:**

**Permission denied (publickey):**

**Other details that may be helpful:**

**Rancher Quick Start deployment in Azure**

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by rfparedes** [comment]
The documentation or the template (or both) should be updated. It looks like you are trying to use the ssh key in your home directory ~/.ssh which is what it appears you should use from the documentation.  Instead, when you run a terraform apply from quickstart/azure, it creates an id_rsa and id_rsa.pub in quickstart/azure.  This is the key you must use so:

ssh -i  <PATH_TO>/quickstart/azure/id_rsa ubuntu@public_ip
