### ISSUE TITLE
Host not registered yet

### ISSUE THREAD

**Issue by silviupanaite** [rancher/rancher#3148]
All my host are not available anymore. The host in question is the host rancher is on, same problem applies to other hosts.
Component	Version
Rancher	v0.51.0
Cattle	v0.130.0
User Interface	v0.78.0
Rancher Compose	v0.7.0

INFO: Downloading https://xxx.com/v1//configcontent//host-config current=host-config-1-xxx
INFO: Already up to date
INFO: Sending host-config applied 1-xxx
2015-12-29 14:07:28,631 ERROR root [140361307787344] [_logging.py:54] error from callback <function on_error at 0x7fa869e34668>: ('Received websocket error: [%s]', WebSocketBadStatusException('Handshake status 500',)) 

time="2015-12-29T14:07:28Z" level="info" msg="Starting event router." 
time="2015-12-29T14:07:28Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 

I1229 15:07:28.661187 12599 storagedriver.go:132] No backend storage selected
I1229 15:07:28.661243 12599 storagedriver.go:134] Caching stats in memory for 2m0s
I1229 15:07:28.661325 12599 manager.go:128] cAdvisor running in container: "/docker/xxx"
time="2015-12-29T14:07:28Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"xxx\", From:\"-simulated-\", Time:0}" 
time="2015-12-29T14:07:28Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"xxx\", From:\"-simulated-\", Time:0}" 
time="2015-12-29T14:07:28Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"xxx\", From:\"-simulated-\", Time:0}" 
time="2015-12-29T14:07:28Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"8b0a3ae166b827f46d9269f399162f0f31b36caf1c47b8df8400fdcae28c82e8\", From:\"-simulated-\", Time:0}" 
time="2015-12-29T14:07:28Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"xxx\", From:\"-simulated-\", Time:0}" 
time="2015-12-29T14:07:28Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"xxx\", From:\"-simulated-\", Time:0}" 
time="2015-12-29T14:07:28Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"xxx\", From:\"-simulated-\", Time:0}" 
time="2015-12-29T14:07:28Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"xxx\", From:\"-simulated-\", Time:0}" 

time="2015-12-29T14:07:28Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=0 reportedUuid="xxx"

How can I solve this problem?

**Comment by silviupanaite** [comment]
logs from rancher/server

17:35:52.565 [main] INFO  ConsoleStatus - [DONE ] [11725ms] Startup Succeeded, Listening on port 8081
time="2015-12-29T17:35:53Z" level=info msg="Starting websocket proxy. Listening on [:8080], Proxying to cattle API at [localhost:8081], Monitoring parent pid [7]." 
time="2015-12-29T17:35:54Z" level=info msg="Starting Rancher Catalog service" 
time="2015-12-29T17:35:54Z" level=info msg="Using catalog library=https://github.com/rancher/rancher-catalog.git" 
time="2015-12-29T17:35:54Z" level=info msg="Cloning the catalog from git url https://github.com/rancher/rancher-catalog.git" 
Cloning into './DATA/library'...
time="2015-12-29T17:35:54Z" level=info msg="Setting log level" logLevel=info 
time="2015-12-29T17:35:54Z" level=info msg="Starting rancher-compose-executor" version=v0.7.0 
time="2015-12-29T17:35:54Z" level=info msg="Starting go-machine-service..." gitcommit=5023ae4 
time="2015-12-29T17:35:54Z" level=info msg="Initializing event router" workerCount=10 
time="2015-12-29T17:36:17Z" level=error msg="Unable to start EventRouter" Err="Timed out waiting for transtion." 
time="2015-12-29T17:36:17Z" level=info msg="Exiting go-machine-service..." 
time="2015-12-29T17:36:18Z" level=info msg="Setting log level" logLevel=info 
time="2015-12-29T17:36:18Z" level=info msg="Starting go-machine-service..." gitcommit=5023ae4 
time="2015-12-29T17:36:20Z" level=fatal msg="Unable to start event router" error="Timed out waiting for transtion." 
time="2015-12-29T17:36:22Z" level=info msg="Starting rancher-compose-executor" version=v0.7.0 
time="2015-12-29T17:36:22Z" level=info msg="Initializing event router" workerCount=10 
time="2015-12-29T17:36:29Z" level=error msg="Unable to start EventRouter" Err="Timed out waiting for transtion." 
time="2015-12-29T17:36:29Z" level=info msg="Exiting go-machine-service..." 
time="2015-12-29T17:36:30Z" level=info msg="Setting log level" logLevel=info 
time="2015-12-29T17:36:30Z" level=info msg="Starting go-machine-service..." gitcommit=5023ae4 
time="2015-12-29T17:36:32Z" level=fatal msg="Unable to start event router" error="Timed out waiting for transtion." 
time="2015-12-29T17:36:34Z" level=info msg="Starting rancher-compose-executor" version=v0.7.0 
time="2015-12-29T17:36:34Z" level=info msg="Initializing event router" workerCount=10 
time="2015-12-29T17:36:36Z" level=error msg="Hijack error." error="http: Hijack is incompatible with use of CloseNotifier" 
time="2015-12-29T17:36:36Z" level=info msg="Registering backend for host [9b96b5c2-6341-4cc6-8d9b-16ddb3c0401f]" 
time="2015-12-29T17:36:37Z" level=error msg="Hijack error." error="http: Hijack is incompatible with use of CloseNotifier" 
time="2015-12-29T17:36:38Z" level=info msg="Registering backend for host [78d00f45-1648-45b3-8a03-8d5122c3e71e]" 
time="2015-12-29T17:36:40Z" level=error msg="Unable to start EventRouter" Err="Timed out waiting for transtion." 
time="2015-12-29T17:36:40Z" level=info msg="Exiting go-machine-service..." 
time="2015-12-29T17:36:42Z" level=info msg="Setting log level" logLevel=info 
time="2015-12-29T17:36:42Z" level=info msg="Starting go-machine-service..." gitcommit=5023ae4 
time="2015-12-29T17:36:44Z" level=fatal msg="Unable to start event router" error="Timed out waiting for transtion." 
time="2015-12-29T17:36:46Z" level=info msg="Starting rancher-compose-executor" version=v0.7.0 
time="2015-12-29T17:36:46Z" level=info msg="Initializing event router" workerCount=10 
time="2015-12-29T17:37:00Z" level=error msg="Unable to start EventRouter" Err="Timed out waiting for transtion." 
time="2015-12-29T17:37:00Z" level=info msg="Exiting go-machine-service..." 
time="2015-12-29T17:37:00Z" level=info msg="Setting log level" logLevel=info 
time="2015-12-29T17:37:00Z" level=info msg="Starting go-machine-service..." gitcommit=5023ae4 
2015/12/29 17:37:04 http: proxy error: net/http: request canceled

**Comment by silviupanaite** [comment]
Downgraded to 0.50 and host are again reachable, but looking into the api audit logs (UI)


Name	Resource Type:Id	Exit Reason	Started	Ended	Duration
 instance.create	instance:31801	DELEGATE	7 minutes ago	5 minutes ago	118.608 sec
 instance.start	instance:31801	TIMEOUT	5 minutes ago	2 minutes ago	197.893 sec


-----------
  NicActivate			5 minutes ago	3 minutes ago	124.267 sec
 network.activate	network:11	ALREADY_DONE	5 minutes ago	5 minutes ago	-
 vnet.activate	vnet:5	ALREADY_DONE	5 minutes ago	5 minutes ago	-
  ipaddressnicmap.create	ipAddressNicMap:8062	DELEGATE	5 minutes ago	5 minutes ago	3.964 sec
 ipaddressnicmap.activate	ipAddressNicMap:8062	DONE	5 minutes ago	4 minutes ago	29.082 sec
  ipaddress.create	ipAddress:8074	DELEGATE	4 minutes ago	4 minutes ago	18.296 sec
  ipaddress.activate	ipAddress:8074	DONE	4 minutes ago	3 minutes ago	55.715 sec
 IpAddressActivate			4 minutes ago	3 minutes ago	34.264 sec
 ipaddress.activate	ipAddress:8074	ALREADY_DONE	3 minutes ago	3 minutes ago	-

**Comment by silviupanaite** [comment]
Upgraded to rancher 50.1 :)

**Comment by deniseschannon** [comment]
@silviupanaite You had no issues upgrading to v050.1, but had issues when you upgraded to v0.51.0? 

Can you describe your setup? Is it a single server or multi-node server setup?

**Comment by silviupanaite** [comment]
single server, all host have ubuntu and docker 1.7.1 installed. al rancher ports are opened.

**Comment by silviupanaite** [comment]
Now I'm trying to add  new host, debian 8, and I get 
WebSocketBadStatusException('Handshake status 500',))  from the agent dos in the new network.

**Comment by deniseschannon** [comment]
@silviupanaite Is this a different set up from the one that you have going on in the other thread about v0.56.1 and ipsec issues? 

In that thread, it sounded like you were able to get 2 ubuntu hosts running and linking to each other, but still having issues with debian.

**Comment by deniseschannon** [comment]
@silviupanaite I haven't heard back in awhile. If you are still having this issue, please re-open.
