### ISSUE TITLE
Update Windows bootstrapping to support wins v0.1.x

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#31499]
This issue tracks the changes necessary in the rancher/rancher repository to update the bootstrapping process for creating a Windows cluster to automatically install the newer version of wins that will support `.\wins.exe up[grade]` and `.\wins.exe cli proxy --publish TCP:<port>`.

Once this issue is merged in, any future Windows clusters should be able to support wins upgrades and using the new Monitoring V2 chart with no changes.

This issue does not track existing cluster upgrades, which will instead be tracked as part of https://github.com/rancher/wins/issues/20.

**Comment by thehejik** [comment]
Windows clusters deployed with rancher:v2.5-head `b2a34d7` are now able to run v2 monitoring with enabled windowsExporter (so far it has to be enabled manually in values YAML) out-of-the-box without a need to deploy `rancher-wins-upgrader` chart.

Tested within 1st testcase listed at https://confluence.suse.com/display/EN/Monitoring+v2+Windows+Support
