### ISSUE TITLE
[Monitoring V2] Add rancher-windows-exporter

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#31497]
Creates a Helm chart that packages the [windows-exporter_package](https://github.com/rancher/rancher/issues/31148) using the latest `wins cli proxy` feature to publish the windows-exporter host port as a Pod port that can be scraped by Prometheus and adds it to the Monitoring V2 chart

**Comment by thehejik** [comment]
This helm chart is now required (when windowsExporter is enabled) by v2 monitoring `rancher-monitoring-9.4.204-rc08` from `dev-v2.5` helm chart repo. Intentionally it's not visible as an extra chart in Cluster explorer.

Tested within https://confluence.suse.com/display/EN/Monitoring+v2+Windows+Support
