### ISSUE TITLE
Add rancher-wins-upgrader on rancher/charts

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#31504]
Adds https://github.com/rancher/wins/issues/20 as a forked Helm chart that can be deployed by users in Windows Clusters only

**Comment by thehejik** [comment]
Helm chart from `dev-v2.5` repo successfully deployed and tested within the EPIC testing and https://confluence.suse.com/display/EN/Monitoring+v2+Windows+Support

It's compatible with windows nodes deployed on rancher:2.5.7
