### ISSUE TITLE
Large numbers of streamwatcher.go:114] Unexpected EOF during watch stream event decoding: unexpected EOF in kubelet logs

### ISSUE THREAD

**Issue by dbason** [rancher/rancher#31506]
**What kind of request is this (question/bug/enhancement/feature request):**Bug

**Steps to reproduce (least amount of steps as possible):**
Deploy a new Rancher downstream cluster (have set up on Ubuntu 18.04 in AWS)
Check the logs for kubelet container on a worker only node

**Result:**
Groups of `streamwatcher.go:114] Unexpected EOF during watch stream event decoding: unexpected EOF` logs are output every 30s

**Other details that may be helpful:**
Related to https://github.com/rancher/rancher/issues/14971

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.5.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Have seen this on prem, and AWS
- Kubernetes version (use `kubectl version`):  Have seen this on v1.18.12, v1.19.6, and v1.17.14

gz#15237
gz#15657
gz#15799

**Comment by slickwarren** [comment]
on master-head (29674d9) and 2.5-head (14c8c62a05f364adf85523d0afd54b24d9dc4cda: 
there is no log of `streamwatcher.go:114` using amazon nodes in a custom downstream cluster
verified that `rancher/rke-tools                            v0.1.75`

Was also able to repro on v2.5.8, viewing the logs of `kubelet` container. 
rke tools for 2.5.8 is on version `v0.1.74`
