### ISSUE TITLE
[UI] show agent env vars on cluster page - Imported Clusters

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#31505]
Same as https://github.com/rancher/rancher/issues/31023 but for Imported clusters. 

https://github.com/rancher/rancher/issues/31023#issuecomment-786281821

**Comment by codyrancher** [comment]
@kinarashah is it supposed to be a part of Import Amazon EKS as well?

**Comment by codyrancher** [comment]
@qa I haven't been able to verify editing once the cluster is fully imported as my imports fail with or without agentEnvVars so please double check that.

While the cluster is still importing the form field is shown as editable but there is no save button. This is an existing issue.

**Comment by kinarashah** [comment]
@codyrancher Yeah, we want this field to be available for all Imported clusters

**Comment by slickwarren** [comment]
on v2.5-67228a3cdba34161e1e03a4639b9c5b445e7b81b-head I was able to verify agentEnvVars are added to an import cluster: 
* provision import cluster and add some environment variables under the `advanced options` tab
<img width="1325" alt="Screen Shot 2021-02-26 at 11 59 26 AM" src="https://user-images.githubusercontent.com/16691014/109349018-22a30280-782a-11eb-9fb5-b388d165884d.png">

* run the import registration command on the cluster to be imported
* wait for rancher to connect the downstream cluster -- while waiting, you can check the API for the import cluster on yaml. Under `agentEnvVars` you should see the name/value/type of the variable you added through the UI -- PASS
<img width="272" alt="Screen Shot 2021-02-26 at 12 03 51 PM" src="https://user-images.githubusercontent.com/16691014/109349382-b70d6500-782a-11eb-97f8-a15ea4fd4add.png">

* check in `cattle-cluster-agent` workload for the envVar you added either through the shell or in the UI -- PASS

**Comment by sowmyav27** [comment]
Had an offline conv with @deniseschannon. We will support Env vars from the UI for Import clusters and NOT for EKS import clusters.

**Comment by sowmyav27** [comment]
Reopening for a check on master-head

**Comment by slickwarren** [comment]
validated master-head (f1e3e76d32284fe4d248073fe28a4b21a9b04628) with the [same steps from above](https://github.com/rancher/rancher/issues/31505#issuecomment-786873167)

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `5a5c039` and master-head commit id: `f1e3e76d`**

After changes - https://github.com/rancher/ui/pull/4481
- Secrets are not available. Only key/value pair is available for entering agent Env variables - during create and edit of custom rke/rke node driver/ import rke/k3s clusters.
<img width="1437" alt="Screen Shot 2021-03-01 at 5 31 53 PM" src="https://user-images.githubusercontent.com/26032343/109583465-cd2e5600-7ab4-11eb-8d30-72675f95f7b1.png">

- Able to add env variables on edit/create clusters.
