### ISSUE TITLE
Validate PostgreSQL 13.1 as a K3s backend

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#31503]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement/feature request

Request to validate PostgreSQL 13.1 as a k3s datastore with the recent [RDS PostgreSQL 13.1 support](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.version131).

gz#15274

**Comment by davidnuzik** [comment]
Tentatively scheduling for K3s QA team to test and validate for Rancher 2.5.7 release.

**Comment by ShylajaDevadiga** [comment]
Validated postgres 13.1 on k3s versions v1.18.16+k3s1, v1.19.8+k3s1, v1.20.4+k3s1 using rancher version v2.5.6 as per our DB validation matrix.
