### ISSUE TITLE
Support for SAML Ping and openLDAP for group search

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#31519]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Use the test Ping configured Rancher provided by Dev `v2.5-head` 30e53bd
- Navigate to `Global` -> `Security` -> `Authentication`
- Select `Restrict access to only Authorized Users and Organizations` or
  - `Allow members of Clusters, Projects, plus Authorized Users and Organizations`
- Click in the memberships dropdown

**Result:**

According to [Documentation](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/ping-federate/)

> When adding groups, you must select the group from the drop-down that is next to the text box. Rancher assumes that any input from the text box is a user.

But the Dropdown doesn't populate .

**Other details that may be helpful:**

This worked with ADFS and Keycloak
The Ping setup was provided by Dev and it's using an OpenLDAP data store.

I tried also the membership dropdown on Cluster and Project members.

![Screen Shot 2021-02-26 at 8 27 01 AM](https://user-images.githubusercontent.com/27659/109334690-495b3c00-781e-11eb-8503-91ff0341fc4d.png)

**Environment information**
- Rancher version: `2.5-head` _30e53bd_
- Installation option: HA

**Comment by izaac** [comment]
Reproduced in `v2.5.5` with the Same Ping backend.

**Comment by fabiograssofy** [comment]
Same issue using Okta ad IdP

**Comment by prachidamle** [comment]
@izaac This seems to be an issue of this Ping setup because it is using an openLDAP datastore. In openLDAP, a user does not have a "member" property in the user schema - a group instead has the "member" attribute that lists the users that are part of the group.

So if we attach an AD datastore to this Ping setup, we wont see this problem. In Active Directory a user has the "memberOf" property which will populate the " My groups" field in Rancher.

**Comment by dbason** [comment]
@prachidamle issue still exists with Okta though.  The group dropdown is populated in the API, it's just the UI that doesn't get the groups.  Would it help to create a separate issue for Okta?

**Comment by izaac** [comment]
@dbason thanks for following up on this could you open a separate issue for Okta? 
Please include Rancher version and double check the [caveats](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/okta/) described in docs.

**Comment by izaac** [comment]
@dbason there's an existing issue https://github.com/rancher/rancher/issues/30401

**Comment by Jono-SUSE-Rancher** [comment]
@izaac Does the API UI get populated?

**Comment by izaac** [comment]
@Jono-SUSE-Rancher

Short answer: not from our test using OpenLDAP. I didn't see the groups populated in the API UI.

Long:

In order to fully test this statement https://github.com/rancher/rancher/issues/31519#issuecomment-790005611 we should create an AD Datastore and use it with a new SP connection to make the Rancher integration (instead of OpenLDAP).

I had a conversation with @prachidamle about issues a ran into while creating the AD Datastore and corresponding SP connection in Ping Federate but i think other priorities came and we didn't follow up on that.

@prachidamle could you help checking why the AD datastore is not allowing me to use any AD user?

**Comment by junkiebev** [comment]
I believe only Shibboleth currently has the option to configure an openLDAP datastore for querying users - is this something that could be integrated into all SAML providers? It's a blocker for our migration to Okta

Happy to open an RFE in the support portal if that'd be useful.

![image](https://user-images.githubusercontent.com/6684332/155816608-dc78368d-f7fd-481b-8cc2-bf0067990ea4.png)

**Comment by izaac** [comment]
Assigning this old issue to Auth QA SME for follow up depending on priorities.
