### ISSUE TITLE
Subdomains and domains not resolving on public port 80

### ISSUE THREAD

**Issue by Jdesk** [rancher/rancher#3151]
No matter what on compute nodes setup sub domains and domains will not resolve to app.foo.com:port. or app.foo.com.   If created via cli, is not an issue - however my situation is also unique.  

I had a previously created nfs server setup using nfsv3 with the appropriate folders mountable however since this is basically just loopback storage even though it's on another server - it's cloud based, not on premise.  It should not matter when something is a public facing app.  obviously dbs don't go on public ports. We also used to be able to have the app on public port 80 and container port (usually using the port app is developed to listen on) and rancher would do the forwading.  

 Even using route53 (which I use) and in the past rancher had issues creating dns entries - now it doesn't which rocks (hate dns). However as needed if an app was done and we wanted to put it into our portfolio and want it on a pretty sub-permalink (sorry wordpress speaking) - Even port with subdomain is fine. 

In previous version of rancher server - we could simply manually change the port to 80 in rancher and have it on a separate port inside the container - then point as many domains as we wanted at it. Put etcd plus kubernetes in the mix and it was a beatiful thing to say the least as even when rancher went down, the apps stayed up then we could add via cli to the rancher host.  

Now apps will only resolve publicly to ip and port. eg 1.2.3.4:5678  I love how everything is coming along by the way - the features are actually making things too simple it feels - but hey that is fine - rather than typing - let's produce during deploy time.  However I know it's still beta - and there are bugs you want to know about.

**Comment by deniseschannon** [comment]
@Jdesk I broke up your issue into paragraphs to help us try to understand better. 

It'd be easier if you could provide a docker-compose.yml of your stack and the desired behavior of what you want the stack to do. (Assuming you are using Route53).

**Comment by deniseschannon** [comment]
@Jdesk 

Please re-open with the requested docker-compose.yml of your stack and your desired behavior.
