### ISSUE TITLE
kev2: eks-operator arm64 support

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#31517]
Right now we only support amd

Ideally we should also adjust the drone file to use the dockerhub plugin instead of writing manually. 

And stop using brian's personal image for the repo.

**Comment by thedadams** [comment]
arm64 is not officially supported by Rancher. However, a dev environment pointing to a k3s cluster running on a arm64 device was used to verify that eks-operator was successfully deployed to the k3s cluster. Also, an EKS cluster was created and deleted from Rancher with this setup with no issues.
