### ISSUE TITLE
[monitoring] issue with rancher-monitoring in a k3s cluster

### ISSUE THREAD

**Issue by iioragg** [rancher/rancher#31518]
Hi everyone,
I am unable to install monitoring on my k3s cluster via rancher 2.5.5, every pods is running, but the solution not work.
In particular, I notice that pushprox-clients are unable to contact the pushprox-server.
By installing the various components separately **without rancher**, they work (there is not the pushprox)

Is there the possibility to remove the pushprox from the deployment or is it essential for rancher?
Has anyone with a k3s cluster had similar issues?
Thanks.

**Comment by Beng89** [comment]
I'm encountering this issue as well, when trying to access Grafana I see:

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "error trying to reach service: dial tcp 10.42.2.17:8080: i/o timeout",
  "code": 500
}
```

In the pushprox logs there are errors trying to connect to port 8080 on the host machine ip addresses.

**Comment by iioragg** [comment]
Very thanks for your answer, changing the flannel backend from IPSec to wireguard fix the problem.
