### ISSUE TITLE
Can't uninstall istio when monitoring is not installed

### ISSUE THREAD

**Issue by kravciak** [rancher/rancher#31513]
Rancher: master-head (465bb3b)
Istio: 1.8.300-rc01

To reproduce (all settings left default):
- go to Cluster Explorer -> Apps & Marketplace
- install Istio (Monitoring is not installed)
- go to installed apps
- remove istio & kiali

```
helm uninstall --namespace=istio-system rancher-istio
creating 1 resource(s)
Watching for changes to Job istioctl-uninstaller with timeout of 5m0s
Add/Modify event for istioctl-uninstaller: MODIFIED
istioctl-uninstaller: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Add/Modify event for istioctl-uninstaller: MODIFIED
Starting delete for "istioctl-uninstaller" Job
Error: uninstallation completed with 1 error(s): unable to build kubernetes objects for delete: unable to recognize "": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
```

**Comment by brendarearden** [comment]
@kravciak I think this is unrelated to monitoring not being installed but is related to this https://github.com/rancher/rancher/issues/31046#issuecomment-781649242

try the following steps to resolve this issue: 
* go to Cluster Explorer -> Apps & Marketplace
* install Istio (Monitoring is not installed)
* go to installed apps
* remove istio and wait for install to complete
* remove kiali

**Comment by sowmyav27** [comment]
@slickwarren can you try [this set of steps](https://github.com/rancher/rancher/issues/31513#issuecomment-786764689) on a 2.5-head?

**Comment by slickwarren** [comment]
on v2.5-head (67228a3) Istio: 1.8.300-rc01 following [these steps](https://github.com/rancher/rancher/issues/31513#issuecomment-786764689) (without monitoring installed) I was able to uninstall Istio without any issues
