### ISSUE TITLE
Custom Cluster edits do not update in registration command before clicking save

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31529]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
* create a custom cluster with some environment variables
* edit the custom cluster
* remove/add new/edit existing environment variables

**Result:**
* registration command that is displayed to user on edit page does not update with user's changes to environment variables
example: removed 4/5 variables, but registration command still has them listed
<img width="1072" alt="Screen Shot 2021-02-26 at 5 37 31 PM" src="https://user-images.githubusercontent.com/16691014/109371387-88f34980-7859-11eb-9170-f0c53f69e161.png">
* also, if you save an environment variable that has no values/keys, it is saved in the registration command as `-e =`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-head (67228a3cdba34161e1e03a4639b9c5b445e7b81b)
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE
- Kubernetes version (use `kubectl version`): ANY

**Comment by kinarashah** [comment]
@slickwarren I've put in a fix to update the registration command, but can put changes for no values/keys later since it's not a common usecase.

**Comment by gaktive** [comment]
Part of the command comes from the server and the UI; the `-e =` comes from the server. 

One of two issues is happening here: the command that's displayed on this screen has not been updated based on prior entries used in the wizard, so the UI needs to refresh the view here with an updated command. 

The other is that the API needs to give us an updated command, so the server ideally gives us the right command during the edit phase. Perhaps the API could give UI the command with any `-e` parameters and the UI would have the logic to put them back in.

Vince to check with Kinara.

**Comment by gaktive** [comment]
Based on activity in https://github.com/rancher/rancher/issues/31545, for 2.5.6, we'll only expose the key/value option. We'll sort out the balancing act with the `-e` for 2.5.7.

**Comment by westlywright** [comment]
That proposed changes for this will slightly alter how clusters are edited. When editing a custom or imported cluster the user will no longer be presented with the commands immediately. This is because environment variables must be saved on cluster because they are not appended to the command like we do with roles and other advanced options in the command window, they are actually apart of the command as it is fetched from the cluster. So in order for the user to have an updated command they must save first the env vars first. If I remember correctly this is pretty close to how it would function prior to all the new EKS import work that was done last year and probably makes more sense as it explicitly requires the user to save if they've made changes before getting the new command. If the user doesn't want to make changes and the cluster is in the correct state then they can fetch the reg command via the action menu rather then editing a cluster.

**Comment by slickwarren** [comment]
Tested on v2.5-head (51253e556b6cc3d9b285b559c4ff043e2301d687):
* Import Clusters: (rke, k3s, eks)
  * edit envVars after creation -> changes to envVars still written to yaml
  * edit envVars after registration cmd applied -> new envVars shown in `cattle-cluster-agent`
  * test EKS cluster import (no registration cmd)
    * able to add new node
  * import cluster with envVars in yaml -> cluster imports with said envVars saved

* Custom Clusters: 
  * preview no longer available on edit page
  * changes to envVars save to registration cmd correctly
  * create w/o envVars -> no envVars shown in `cattle-cluster-agent`
  * Add envVars -> new envVars shown in `cattle-cluster-agent`
  * add more envVars -> new envVars shown in `cattle-cluster-agent`
  * delete some vars -> select envVars removed from `cattle-cluster-agent`
  * delete all vars -> envVars removed from `cattle-cluster-agent`


### Reopening for the following issues:

* when clicking `save` on edit screen for imported cluster, user is brought to a second `save/cancel` page that has no options. User must click cancel or save again (even though changes are already saved) in order to get past the screen
<img width="1362" alt="Screen Shot 2021-03-17 at 9 27 40 AM" src="https://user-images.githubusercontent.com/16691014/111517249-19fb6900-8712-11eb-82f8-87ab0a70b5b1.png">
<img width="1382" alt="Screen Shot 2021-03-17 at 9 27 33 AM" src="https://user-images.githubusercontent.com/16691014/111517255-1a93ff80-8712-11eb-8cad-2876fe0d4ccd.png">


* when editing custom cluster, the only way to add new node/get reg. cmd again is to save an edit to the cluster -> should expose registration cmd on `node` page like we do when there are no nodes registered. You mentioned `If the user doesn't want to make changes and the cluster is in the correct state then they can fetch the reg command via the action menu rather then editing a cluster.` but I don't see that option after the custom cluster has registered its first node
<img width="1230" alt="Screen Shot 2021-03-17 at 11 16 44 AM" src="https://user-images.githubusercontent.com/16691014/111517410-4616ea00-8712-11eb-8695-57c1d546ec9a.png">
<img width="1287" alt="Screen Shot 2021-03-17 at 11 16 33 AM" src="https://user-images.githubusercontent.com/16691014/111517424-4911da80-8712-11eb-88e0-088638e06f50.png">

**Comment by westlywright** [comment]
@slickwarren I believe I inadvertently fixed the double save button comment while I was developing GKE v2 provisioner. The second comment actually ended up having a bug opened by another dev https://github.com/rancher/rancher/issues/32031 which we can use to track that if.

**Comment by slickwarren** [comment]
on v2.5-70024998a0e95374a135177953a04f4539e2d59c-head and master-39d572aff5ccef43ff0bb9432f9e8f9b9b29d234-head : 
* add import cluster -- normal behavior
* edit import cluster -- double save no longer exists -- pass
* add custom cluster -- normal behavior
* edit custom cluster -- normal behavior


closing : the above was verified fixed and the second issue is now in #32031
