### ISSUE TITLE
exec shell on cluster fails with 1006 error

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31521]
forwardport: rancher/rancher#31434 for master-head

**Comment by slickwarren** [comment]
This appears to still be broken using shell on master-head (7e5ad7fa94db771808e727c6607dd539304e6ffe)
* deployed GKE cluster
* tried to access shell, but error is presented with 1006 error

**Comment by cbron** [comment]
@slickwarren the original issue is that it timed out after an hour, that was from the OAuth stuff. Is the shell not starting at all ? Or is the shell image missing the first slash ?

**Comment by slickwarren** [comment]
shell wasn't starting at all, let me retry today and check if it was missing the slash

**Comment by cbron** [comment]
Ok. If its different error we should repurpose this issue and take away forwardport stuff. We don't think its related to Oauth issue.

**Comment by cbron** [comment]
Adding Wes and Darren, not sure where problem is, need to investigate.

**Comment by slickwarren** [comment]
I'm also seeing this on hosted AKS, imported AKS, and any vsphere cluster on both dashboard shell and ember shell using master-head (1e1ed67329d6224e7a10f1c1a529eaff60ba48ea) Local cluster does not appear to have this issue

**Comment by slickwarren** [comment]
blocked by the ticket above

**Comment by slickwarren** [comment]
on master-head (8073489):
* provision gke cluster
* execute into shell
  * perform a shell function (i.e. kubectl get nodes)
* wait 1hr -> execute into shell again
  * perform a shell function (i.e. kubectl get nodes)

All tests have passed
