### ISSUE TITLE
custom cluster/node driver environment variable types other than key/value pairs should be disabled when creating a cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31528]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* create a custom cluster or node driver cluster
  * add environment variable
 
**Result:**
custom cluster allows addition of any type
<img width="310" alt="Screen Shot 2021-02-26 at 5 25 31 PM" src="https://user-images.githubusercontent.com/16691014/109371005-ad4e2680-7857-11eb-90c1-a97ed343929a.png">

* node driver allows these types
example of node driver cluster create page:
<img width="354" alt="Screen Shot 2021-02-26 at 5 26 23 PM" src="https://user-images.githubusercontent.com/16691014/109371024-c48d1400-7857-11eb-973e-160cbdc61975.png">
* requesting to disable all types except for key/value pairs, as they are irrelevant upon cluster create

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head (67228a3cdba34161e1e03a4639b9c5b445e7b81b)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE cluster
- Kubernetes version (use `kubectl version`): ANY

**Comment by sowmyav27** [comment]
On cluster create when these environment variable are given, cluster fails to come up. (on 2.5.6-rc6)

- Create a custom cluster
- Env variables given 

<img width="1046" alt="Screen Shot 2021-02-27 at 3 04 20 PM" src="https://user-images.githubusercontent.com/26032343/109402733-1e9be100-790d-11eb-9b8d-25b7b96e21f2.png">

- Cluster fails to come up with error: `Error while applying agent YAML, it will be retried automatically: exit status 1, clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver unchanged clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master unchanged namespace/cattle-system unchanged serviceaccount/cattle unchanged clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged secret/cattle-credentials-70954d8 unchanged clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged daemonset.apps/kube-api-auth unchanged Error from server (Invalid): error when creating "management-statefile_path_redacted": Deployment.apps "cattle-cluster-agent" is invalid: spec.template.spec.containers[0].env[8].valueFrom.fieldRef.fieldPath: Invalid value: "metadata": error converting fieldPath: field label not supported: metadata Error from server (Invalid): error when creating "management-statefile_path_redacted": DaemonSet.apps "cattle-node-agent" is invalid: spec.template.spec.containers[0].env[8].valueFrom.fieldRef.fieldPath: Invalid value: "metadata": error converting fieldPath: field label not supported: metadata`
- Edit cluster --> Remove the pod Field env variable.
- The cluster comes up Active

**Expected:**
Fields not applicable should be disabled while creating a cluster.

**Comment by gaktive** [comment]
@kinarashah do you know if the Pod Field actually valid for node driver clusters? Someone in UI could disable this but it'd be helpful to know if both Pod Field and Resource are needed by design since UI is just consuming this.

**Comment by gaktive** [comment]
For creating a proxy, only the Key/Value can work. The create/edit page is going to be tricky to detect the state so as a workaround, we can hide the other variables and then use the API to edit the Resource and Pod Field for 2.5.6.

**Comment by gaktive** [comment]
To clarify, Key/Value should only appear for node driver clusters. For creation of the other type, we can leave it as is.

**Comment by sowmyav27** [comment]
To validate:
- Create custom/node drive cluster. Agent env variable section should have option to add only Key/Value pair
- Edit custom/node drive cluster. Agent env variable section should have option to add only Key/Value pair
- Create import cluster. Agent env variable section should have all options in the dropdown
- Create import cluster. Agent env variable section should have all options in the dropdown
- Values field should be marked mandatory (both in custom/import)

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `5a5c039` and master-head commit id: `f1e3e76d`**

After final changes for 2.5.6 - https://github.com/rancher/ui/pull/4481

- Secrets are not available. Only key/value pair is available for entering agent Env variables - during create and edit of custom rke/rke node driver/ import rke/k3s clusters.
<img width="1437" alt="Screen Shot 2021-03-01 at 5 31 53 PM" src="https://user-images.githubusercontent.com/26032343/109583465-cd2e5600-7ab4-11eb-8d30-72675f95f7b1.png">
