### ISSUE TITLE
Support profile picture for non-GitHub authenticated users

### ISSUE THREAD

**Issue by michaellopez** [rancher/rancher#3152]
Looking at [the code in rancher/ui](https://github.com/rancher/ui/blob/dc3e9fa905475dea35c2df43079bff582f35a2e0/app/models/identity.js#L11) I see that profile pictures are only supported for GitHub authenticated users.

We've set up access control with OpenLDAP (via Mac OS X Server's Open Directory), it's working fine for authentication. But I'd like support for either fetching the profile picture from the OpenLDAP directory via configurable attribute on users or fetching e-mail from OpenLDAP via configurable attribute on users and using that with Gravatar. Or something else that does not involve users uploading images to Rancher. Is this possible and something Rancher would be willing to implement?

**Comment by will-chan** [comment]
This is definitely something we can add.

**Comment by kaos** [comment]
See also #2016, most notably rancher/cattle#859.

**Comment by michaellopez** [comment]
@kaos Thanks for your input. I did find those discussions and changes. But that implementation has been replaced by [`io.cattle.platform.api.auth.Identity`](https://github.com/rancher/cattle/blob/ff09ddd7464cb32cce9639ce5f36b6dbca548aab/code/framework/api/src/main/java/io/cattle/platform/api/auth/Identity.java) and `io.cattle.platform.iaas.api.auth.integration.github.resource.GithubClient` is the only class [that sets](https://github.com/rancher/cattle/blob/7eccae59e32810cb61bb0501f8924c3550b7aa8a/code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/github/resource/GithubClient.java#L106,L108) the value so that `io.cattle.platform.iaas.api.auth.integration.github.resource.GithubAccountInfo` [can create](https://github.com/rancher/cattle/blob/master/code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/github/resource/GithubAccountInfo.java#L43) an Identity with a proper profile picture for users. Non of the other user IdentityProviders handle profile picture for `io.cattle.platform.api.auth.Identity`. I would like for them to do so :)

Also, https://github.com/rancher/cattle/pull/859 defaulted to identicons based on the user id without possibility to use e-mail for Gravatar or picture in LDAP.

**Comment by kaos** [comment]
Ok, great.

+1 for getting this fixed, eventually.. :)

**Comment by JasonvanBrackel** [comment]
@deniseschannon Why was this closed?

**Comment by okunc** [comment]
same here, having this option would be nice @deniseschannon , unclear why it's been closed

**Comment by kaos** [comment]
:(

**Comment by BloodyIron** [comment]
Why was this closed? @deniseschannon

**Comment by ScionOfDesign** [comment]
Agreed. It's rather shocking that Rancher doesn't support Gravatar or Libravatar.

**Comment by BloodyIron** [comment]
It would be nice to also pull it from authentication domains like ActiveDirectory/LDAP/etc

**Comment by soakes** [comment]
any updates on this? Just in the middle of mirgrating away from Github to Gitlab and ran into this issue.

**Comment by BloodyIron** [comment]
Yeah I really would like to see more profile picture options, like from AD/LDAP/SSO.

**Comment by liviuc-altvfx** [comment]
Weird that this isn't supported yet. Any comments, anyone?
