### ISSUE TITLE
Secrets listed are incorrect in the UI on cluster create

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31531]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a custom cluster.
- Create a secret `test1` in default project and namespace
- Create a secret `test2` in system project and cattle-system namepsace
- Edit cluster --> Agent Environment Variables field --> Secret key
- The dropdown shows only `test1`
- Select `test1` and key and save changes made.
- The cluster is seen Active but nodeagent and cattle cluster agents fail to come up `CreateContainerConfigError: secret "test1" not found`
- Edit cluster from API UI and give `test2` and key of this in the agentEnv field
- The cluster and agents come up Active and the value of secret/key is saved in the agents' Edit/View in YAML of the agent workload.

**Expected Result:**
Should only secrets from cattle-system namespace be displayed in the UI ? 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.6-rc6
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom cluster
- Kubernetes version (use `kubectl version`):

```
1.20 Any
```

**Comment by codyrancher** [comment]
@sowmyav27 it should be showing all secrets.

@kinarashah should we only be showing cattle-system? Any idea why it couldn't find test1 in the example @sowmyav27 showed?

**Comment by gaktive** [comment]
This should be made obsolete by the fix in 31528. Once that's in, we can confirm that this is resolved by its removal.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `5a5c039` and master-head commit id: `f1e3e76d`**

- Secrets are not available. Only key/value pair is available for entering agent Env variables - during create and edit of custom rke/rke node driver/ import rke/k3s clusters.
<img width="1437" alt="Screen Shot 2021-03-01 at 5 31 53 PM" src="https://user-images.githubusercontent.com/26032343/109583465-cd2e5600-7ab4-11eb-8d30-72675f95f7b1.png">
