### ISSUE TITLE
Variable Name for agent Env variables is not marked mandatory which cause error while creating cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31532]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a custom cluster, give in agent Env variables Type: `Secret Key`, No Variable Name, Secret and Key values 
- Cluster fails to come up with error `....<redacted>DaemonSet.apps "cattle-node-agent" is invalid: spec.template.spec.containers[0].env[6].name: Required value`
- Edit cluster Give in a Variable Name also like

<img width="1003" alt="Screen Shot 2021-02-27 at 2 15 56 PM" src="https://user-images.githubusercontent.com/26032343/109402429-a6342080-790a-11eb-9557-67aeb8cc1dc1.png">

- The cluster comes up Active

**Question:**
Is `Variable Name` a required field ? Can it be marked Mandatory ? 
Is it possible to not "Save" cluster until the Variable name is entered as cluster creation fails if it is not provided.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.6-rc6
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom RKE
- Kubernetes version (use `kubectl version`):

```
1.20 Any
```

**Comment by gaktive** [comment]
Quick fix: simply add a label to make the field mandatory with some validation and then marking the field as mandatory with a red star.
Long-term fix: we need a fix on the server side so that the schema properly tells us this.

**Comment by sowmyav27** [comment]
@gaktive Do we need this as we are only showing key/value pair for 2.5.6 as mentioned - https://github.com/rancher/rancher/issues/31528#issuecomment-788105650 ?

**Comment by gaktive** [comment]
@sowmyav27 by the sounds of it, if key/value isn't set, this error occurs so it's still required. Correct me if I'm interpreting something wrong.

**Comment by codyrancher** [comment]
I'm going to go ahead and just add the indicator as I saw it fail on my end without the variable name with key value.

**Comment by sowmyav27** [comment]
PRs:
- https://github.com/rancher/ui/pull/4476
- https://github.com/rancher/ui/pull/4477

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `5a5c039` and master-head commit id: `f1e3e76d`**

- Variable Name field is marked mandatory
<img width="1437" alt="Screen Shot 2021-03-01 at 5 31 53 PM" src="https://user-images.githubusercontent.com/26032343/109583465-cd2e5600-7ab4-11eb-8d30-72675f95f7b1.png">
