### ISSUE TITLE
Add Docker 20.10.4/20.10.5

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#31539]
https://github.com/moby/moby/releases/tag/v20.10.4
https://github.com/moby/moby/releases/tag/v20.10.5

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `bdec2f2`**

- Deployed DO/AWS clusters with `https://releases.rancher.com/install-docker/20.10.sh` and docker version `Version:          20.10.5` was deployed on the node and cluster came up Active. 
- Deployed DO/AWS clusters with `https://releases.rancher.com/install-docker/20.10.4.sh` and docker version `Version:          20.10.4` was deployed on the node and cluster came up Active.
