### ISSUE TITLE
[UI] Unable to edit Environment Variables on imported k3s cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31545]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* import cluster with environment variables
* wait for cluster to become active
* edit cluster and navigate to environment variables section

**Result:**
* environment variables are not listed on the import cluster `edit` page 
<img width="1444" alt="Screen Shot 2021-03-01 at 11 11 02 AM" src="https://user-images.githubusercontent.com/16691014/109547763-a22a0f00-7a80-11eb-8e3a-162b4c289d03.png">

**Other details that may be helpful:**
* other cluster types do have this UI option (i.e. custom cluster)
* We are able to update the agentEnvVars for import clusters through the API

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.6-rc6
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): imported k3s
- Kubernetes version (use `kubectl version`): 1.20 (any)

- Docker version (use `docker version`): 20.04 (any)

**Comment by deniseschannon** [comment]
@kinarashah should we be able to edit these environment variables on an imported cluster?

**Comment by kinarashah** [comment]
@deniseschannon this is allowed through API for all cluster types

**Comment by codyrancher** [comment]
Just as a note. I left the order as Advanced then K3s options because the change involved is actually risky to change the order right now. If we want to switch it please open a ticket for a future release.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `5a5c039` and master-head commit id: `f1e3e76d`**

After final changes for 2.5.6 - https://github.com/rancher/ui/pull/4481

- Secrets are not available. Only key/value pair is available for entering agent Env variables - during create and edit of custom rke/rke node driver/ import rke/k3s clusters.
<img width="1437" alt="Screen Shot 2021-03-01 at 5 31 53 PM" src="https://user-images.githubusercontent.com/26032343/109583465-cd2e5600-7ab4-11eb-8d30-72675f95f7b1.png">
