### ISSUE TITLE
[UI] Unable to edit import cluster through UI

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31547]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* import cluster with environment variables
* wait for cluster to become active
* edit cluster and try to save edits

**Result:**
* no save option is available on the edit page

**Other details that may be helpful:**
* this also occurs on 2.5.5 (so this is not a regression)
* We are able to update the agentEnvVars for import clusters through the API
* never able to `save` changes. UI button only shows non-clickable `create` button
<img width="1374" alt="Screen Shot 2021-03-01 at 11 40 14 AM" src="https://user-images.githubusercontent.com/16691014/109549571-fdf59780-7a82-11eb-9eb4-75d384f7aeca.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.6-rc6
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): imported 
- Kubernetes version (use `kubectl version`): 1.20 (any)

- Docker version (use `docker version`): 20.04 (any)

**Comment by slickwarren** [comment]
verified on 2.5-dev and vmaster-dev (3/1/21 at 3:20 PM):
* create import cluster via rancher with or without agent environment variables
* wait for cluster to become active (run registration command on import cluster)
* edit import cluster through UI
* environment variables are editable under `advanced options`
<img width="747" alt="Screen Shot 2021-03-01 at 3 21 52 PM" src="https://user-images.githubusercontent.com/16691014/109572457-11642b00-7aa2-11eb-8564-a114c67558b6.png">

**Comment by slickwarren** [comment]
after the above changes and revalidating, k3s import clusters do not have the option to edit environment variables after cluster goes to active state on 2.5-head 5a5c039d6ed75dc3803abd03c3d3504441f7e02c using 2.5-dev UI
<img width="1365" alt="Screen Shot 2021-03-01 at 5 32 08 PM" src="https://user-images.githubusercontent.com/16691014/109583095-2ea1f500-7ab4-11eb-81fc-9b3cf8980d46.png">

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `5a5c039` and master-head commit id: `f1e3e76d`**

- Create an imported RKE/K3s clusters
- Edit cluster
- Add agent Env variables
- Save changes made.
- Agent env variables are successfully added -- verified on the cluster agent in the clusters
