### ISSUE TITLE
FATA[0051] Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system

### ISSUE THREAD

**Issue by ccs-digital** [rancher/rancher#31554]
**What kind of request is this (question/bug/enhancement/feature request):**

bug
**Steps to reproduce (least amount of steps as possible):**
rke up --local

**Result:**
FATA[0051] Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v1.0.16
- Installation option (single install/HA):singlehost

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
Version:           18.09.9
```
(paste the output here)
```
INFO[0016] [network] Setting up network plugin: calico
INFO[0016] [addons] Saving ConfigMap for addon rke-network-plugin to Kubernetes
INFO[0016] [addons] Successfully saved ConfigMap for addon rke-network-plugin to Kubernetes
INFO[0016] [addons] Executing deploy job rke-network-plugin
FATA[0051] Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system

**Comment by superseb** [comment]
Please file this using https://github.com/rancher/rke/issues/new as this is an RKE CLI issue. And please supply as much info as possible (OS name/kernel etc). Also please try the latest version (RKE v1.2.5) to see if that resolves the issue.
