### ISSUE TITLE
Clone option for Vm results in user being directed to http://<rancher ip>:8080/fail page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3156]
Server version - V0.51.0

Enable Virtual Machine support in UI.
Add a virtual machine.
Once virtual machine gets to "Running" state , click on "Clone" option.

User is directed to http://<rancher ip>:8080/fail page.

**Comment by tfiduccia** [comment]
Version - master UI 3/17
Verified fixed
