### ISSUE TITLE
Update rancher-images.txt generator to handle multiple chart version

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#31568]
Problem:
Currently, the rancher-images.txt generator extracts images from the latest version of each chart. That logic doesn't work for monitoring v1 because in some cases we may need to update an old chart to add support for a k8s version, which results in the images missing from the rancher-images.txt.

Solution:
Update the rancher-images.txt generator to extract images from charts in the `rancher/system-charts` repository based on the `rancher_min_version` stated in the charts `questions.yaml`. E.g. if we are releasing Rancher v2.5.6, images in charts with `rancher_min_version: v2.5.6-rc0` and over should be included in the rancher-images.txt

Notes:
This change will be applicable to all charts at one point, so it would be good to take that into consideration when implementing a fix for it.

**Comment by cbron** [comment]
cc @rmweir this will affect your stuff

**Comment by rmweir** [comment]
@cbron @PennyScissors That's true. I would wait for https://github.com/rancher/rancher/pull/31492 to get merged before working on this.

**Comment by cbron** [comment]
Since this got bumped to 2.6, do we need to do anything special for monitoring in 2.5.8 ?

**Comment by PennyScissors** [comment]
Closing in favor of this [issue](https://github.com/rancher/rancher/issues/33037)
