### ISSUE TITLE
k8s v1.21

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#31567]
Thursday, April 8th: Week 13 - Kubernetes v1.21.0 released

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/32188

**Comment by kinarashah** [comment]
- [ ] Tag a new [hyperkube-base](https://github.com/rancher/hyperkube-base) to get the latest OS packages. The Dockerfile contains the commands to update and upgrade all OS packages - [Hyperkube base is now v0.0.3](https://github.com/rancher/hyperkube-base/releases/tag/v0.0.3) 
- [ ] Create a new [hyperkube](https://github.com/rancher/hyperkube) branch and update k8s version to 1.21 - https://github.com/rancher/hyperkube/pull/185 
- [ ] Tag a new hyperkube image - [v1.21.0-rancher1](https://github.com/rancher/hyperkube/tree/v1.21.0-rancher1)
- [ ] Update RKE to use v1.21 - https://github.com/rancher/rke/pull/2528

**Comment by kinarashah** [comment]
- [ ] Update calico to [v3.19.0](https://github.com/projectcalico/calico/releases/tag/v3.19.0)

**Comment by kinarashah** [comment]
- [ ] `v1.21.1` will be released 5/12. Update existing key `v1.21.0-rancher1-1` to `v1.21.1-rancher1-1`.

**Comment by kinarashah** [comment]
- [ ] Go through existing issues for addon changes in template and update them. node-local dns [#32180] and ingress-nginx [#30356]

**Comment by kinarashah** [comment]
- [ ] Update `etcd` to `v3.4.16` https://github.com/rancherlabs/eio/issues/455

**Comment by kinarashah** [comment]
- [ ] A new version of kube-dns was released, Update kube-dns to `v0.17.4`

**Comment by kinarashah** [comment]
Upgrade from `v1.20.6-rancher1-1` to `v1.21.1-rancher1-1` failing in RKE build, debugging right now to find the issue. 
Fresh install `v1.21.1-rancher1-1` works fine.

**Comment by kinarashah** [comment]
**To test**: 
- [x] Update calico to [v3.19.0](https://github.com/projectcalico/calico/releases/tag/v3.19.0) - https://github.com/rancher/image-mirror/pull/101
- [x] Update ingress to [0.46.0](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.46.0) - https://github.com/rancher/ingress-nginx/pull/48 - [nginx-0.46.0-rancher1](https://github.com/rancher/ingress-nginx/releases/tag/nginx-0.46.0-rancher1) 
- [x] Update calico to `v3.19.0`
- [x] Update kube-dns to `v1.17.4` 
- [x] Update core-dns to `v1.8.3`
- [x] Update cluster-proportional-autoscaler to `v1.8.3` 
- [x] Update pause to `v3.4.1` 
- [x] Update metrics-server to `v0.4.4`

**Comment by anupama2501** [comment]
Validated on the master-head version f6c1d82
k8s version : v1.21.1-rancher1-1

Jenkins job to spin clusters on all the network providers - calico, flannel, weave and canal
Ran validations tests and seeing failures:

- Service discover test - https://github.com/rancher/rancher/issues/32801
- Ingress tests -  Failed with the error: ``` Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io" ```
- Launching kubectl failed with the error ``` websocket._exceptions.WebSocketBadStatusException: Handshake status 500 Internal Server Error ```

**Comment by anupama2501** [comment]
Verified the following versions on the commit-id master-head [29286fc](url)
k8s version: v1.21.1-rancher1-1 

**Versions verified on all the clusters - Weave, calico, flannel and canal**

ingress: nginx-0.46.0-rancher1
kube-dns: mirrored-k8s-dns-kube-dns:1.17.4 + 2 images
core dns: mirrored-coredns-coredns:1.8.3
cluster-proportional-autoscaler : mirrored-cluster-proportional-autoscaler:1.8.3
pause: mirrored-pause:3.4.1   
metrics-server: mirrored-metrics-server:v0.4.4
etcd: mirrored-coreos-etcd:v3.4.16-rancher1 

Calico:
calico node: mirrored-calico-node:v3.19.0 

Canal:
canal node: mirrored-calico-node:v3.19.0 

Flannel:
coreos-flannel:v0.13.0-rancher1

Weave:
weave-net: weave-kube:2.8.1

**Comment by kinarashah** [comment]
We'd need to update addons to the latest again since a few of them have newer versions released: 
- Flannel - v0.14.0 
- Calico - v3.19.1
- CoreDNS - v1.8.4 
- MetricsServer - v0.5.0 
- KubeDNS - v1.18.0

**Comment by sowmyav27** [comment]
Blocked by - https://github.com/rancher/rancher/issues/33704 for running further validation checks

**Comment by anupama2501** [comment]
Blocked by further validations https://github.com/rancher/rancher/issues/33755

**Comment by sowmyav27** [comment]
On master - Validated these for 1.21 k8s:
- Deploy HA rancher on 1.21 k8s
- Deploy downstream 1.21 k8s clusters
- KDM job - all network providers
- Upgrade from 1.20 to 1.21
- Validation tests on 1.21 k8s
- v1/v2 charts on 1.21 k8s downstream clusters
Closing this issue
