### ISSUE TITLE
Update google oauth and azure UI to work with vue UI

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/rancher#31562]
Google oauth and Azure AD auth flows need to be modified to allow both UIs to specify the same return route -- `/verify-auth `and `/verify-auth-azure` -- while configuring these providers. The `state` query param, currently used as a nonce, should be converted to a base64 encoded json object that tracks which UI the request originated from; the API will need to read this query param and redirect to /verify for the Ember ui and /dashboard/auth/verify for the Vue UI. Changes needed in Ember:

- Move & combine existing /verify-auth and /verify-auth-azure routes into /verify
    - (note: /verify already exists but is for a SaaS flow that never got used and can be dropped)
- On login send: state=`urlencode(base64(stringify({ to: "ember", provider: "azure" })))`
- add nonce support to Azure while you're add it

related dashboard issues: https://github.com/rancher/dashboard/issues/2116 https://github.com/rancher/dashboard/issues/2340

**Comment by sowmyav27** [comment]
**On master-head - commit id: `5d2b7ac`**

Able to enabled Azure AD Auth
