### ISSUE TITLE
User being redirected to http://<rancher ip>:8080/fail page when accessing vm link from storage pool tab.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3157]
Server version - v0.51.0

Server version - V0.51.0

Had a convoy-nfs stack deployed from catalog.
Enable Virtual Machine support in UI.
Add a virtual machine - test123 with disk from convoy-nfs driver.
Add a virtual machine - test456 with same disk from convoy-nfs driver.

Got to storage pool tab and click on the virtual machine link in the Mount field.
user being redirected to http://<rancher ip>:8080/fail page.
After this , the mount entries which used to have the vm names becomes blank.

Before clicking the vm name link:

<img width="1004" alt="screen shot 2015-12-30 at 5 00 34 pm" src="https://cloud.githubusercontent.com/assets/4266958/12059839/c71be1e2-af17-11e5-8d3f-8c7c21f73295.png">

After clicking the vm name link:
<img width="980" alt="screen shot 2015-12-30 at 5 01 03 pm" src="https://cloud.githubusercontent.com/assets/4266958/12059840/cd388260-af17-11e5-9bf5-73e8ed882099.png">

**Comment by vincent99** [comment]
No VMs in 1.2..

**Comment by will-chan** [comment]
https://github.com/rancher/rancher/issues/3096
