### ISSUE TITLE
New charts in v2.5.8

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#31594]
### System charts (v1):

Name | Version | Backend Dev(s)
--- | --- | ---
gke-operator | 1.0.100 | @cmurphy 
eks-operator | 1.0.700 (OOB, already released) | @thedadams 
eks-operator | 1.0.800 | @thedadams 
rancher-monitoring | 0.2.2 | @rmweir 

### Feature charts (v2):

Name | Version | Backend Dev(s)
--- | --- | ---
Istio | 1.8.5 | @brendarearden 
Istio | 1.9.3 | @brendarearden 
Kiali | 1.32.1| @brendarearden 
Logging | 3.9.4 | @nickgerace 
Longhorn | 1.1.100 | @innobead 
rancher-alerting-drivers | 1.0.100 | @jiaqiluo 
rancher-prom-to-teams | 0.2.000 | @jiaqiluo 
rancher-sachet | 1.0.100 | @jiaqiluo 
fleet | 0.3.5 | @nickgerace, @StrongMonkey
fleet-agent | 0.3.5 | @nickgerace, @StrongMonkey 
rancher-operator   | 0.1.4 | @thedadams, @StrongMonkey
rancher-cis-benchmark | 1.0.400 | @prachidamle 
rancher-backup | 1.0.400 | @jiaqiluo, @nickgerace
rancher-webhook | 0.1.0 | 
rancher-gatekeeper | 3.3.001 | @aiyengar2 
rancher-grafana | 6.6.401 | @aiyengar2 
rancher-kube-state-metrics | 2.13.101 | @aiyengar2 
rancher-monitoring | 14.5.100 | @aiyengar2 
rancher-node-exporter | 1.16.201 | @aiyengar2 
rancher-prometheus-adapter | 2.12.101 | @aiyengar2 
rancher-pushprox | 0.1.300 | @aiyengar2 
rancher-windows-exporter | 0.1.000 | @aiyengar2 
rancher-wins-upgrader | 0.0.100 | @aiyengar2 
rancher-tracing | 1.20.1 | @brendarearden

**Comment by jiaqiluo** [comment]
**Feature charts (v2):**
- rancher-alert-driver 1.0.100
- rancher-prom-to-teams 1.0.100
- rancher-sachet 1.0.100

**Comment by prachidamle** [comment]
CIS V2 Feature chart: 

rancher-cis-benchmark: 1.0.4

**Comment by cbron** [comment]
@prachidamle you can just edit description above to add it to table

**Comment by sowmyav27** [comment]
**On 2.5.8-rc9**

- Rancher-backups chart version validated: `1.0.400` as part of this issue - https://github.com/rancher/backup-restore-operator/issues/95

**Comment by cbron** [comment]
Added longhorn 1.1.1.1

**Comment by prabalsharma** [comment]
v2.5-1963c2e01996894c36480583903f5d5642702269-head
rancher/**gke-operator:v1.0.1-rc7**

**Comment by aaronRancher** [comment]
On `v2.5.8-rc12`
Validated eks operator version: `v1.0.8`

**Comment by izaac** [comment]
Logging `3.9.400` was validated as part of this main version bump https://github.com/rancher/rancher/issues/31644 
As well as other windows related issues.

**Comment by anupama2501** [comment]
Istio 1.9.300 and 1.8.500 istio versions are validated on rancher v2.5.8-rc9 as part of the istio validtaions for the security releases.
Kiali 1.32.0 has been validated as part of https://github.com/rancher/rancher/issues/31979 on rancher version v2.5-41f173ae93c6692f44054fe0b02ce93bd3056a9f-head

**Comment by khushboo-rancher** [comment]
Validated Longhorn v1.1.1 with v2.5.8-rc12.

Validation - **Pass**

An observation - The downstream cluster didn't show the latest version initially, on refreshing the page it started showing the latest Longhorn version.

**Comment by slickwarren** [comment]
validated monitoring v14.5.100 with v2.5.8-rc5 -- part of testing https://github.com/rancher/rancher/issues/29871  --  **pass**
validated monitoring v0.2.2 with v2.5.8-rc12 --  p0 test cases for monitoring v1  charts-- **pass**

**Comment by izaac** [comment]
```
status:
  branch: dev-v2.5
  commit: 1b856479033464d10ff5f2c6a523941fe1bd7157
```
Rancher version `v2.5.8-rc15`
Fleet: `v0.3.5-rc9`
Validated.

**Comment by rancher-max** [comment]
CIS v2 feature chart validated for rke1, rke2, and k3s -- permissive and hardened profiles for all. Versions used on Rancher v2.5.8-rc15:
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/55997940/116757049-2259eb80-a9c2-11eb-9aa6-357c114ebe59.png">

**Comment by cbron** [comment]
Gatekeeper 3.3.001 was added by @aiyengar2 in this commit: https://github.com/rancher/charts/commit/ad288264bbf31ba75b55fb4de5a34c39096b38fa#diff-0b08d0a93739baf1149976091e3b293c9fd0007ca1c9555169eb8e167b5eb376R3

**Comment by cbron** [comment]
@brendarearden is kiali supposed to be 1.32.0 or 1.32.1 ?

**Comment by brendarearden** [comment]
@cbron you are correct - the chart version is Kiali 1.32.1 (I have updated the chart above to reflect that) - the Kiali version in in the chart is 1.32.0, but we had to change the chart version due to the leading zero issue.

**Comment by sowmyav27** [comment]
**on 2.5.8-rc19**
feature charts repo commit:
```
status:
  branch: dev-v2.5
  commit: 3cd4b8063ed136e7fbd0de269bec75c1514ad5cc
```
- Validated monitoring v2 P0 checks - version: `14.5.100`
- Validated WIns-upgrader - version: `0.0.100`

**Comment by sowmyav27** [comment]
Summary:

### Validated these charts and versions:
```
monitoring v2 - 14.5.100
wins-upgrader - 0.0.100
monitoring v1 - v0.2.2
rancher-alerting-drivers - v1.0.100
Longhorn - v1.1.1
Istio v2 - 1.9.300 and 1.8.500 
Kiali - 1.32.0
rancher-istio-tracing - 1.20.0
Logging - 3.9.400
eks operator - v1.0.8
gke-operator - v1.0.1
rancher-backup - 1.0.400
```
