### ISSUE TITLE
Missing mount information in Storage pool tab when VM using shared data disk is deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3159]
Server version - V0.51.0

Had a convoy-nfs stack deployed from catalog.
Enable Virtual Machine support in UI.
Add a virtual machine - testnew1 with disk - data1234 from convoy-nfs driver.
Add a virtual machine - testnew2 with same disk from convoy-nfs driver.

Got to storage pool tab .

Deleted testnew2 VM.

Go to storage pool tab: (Deleted VM entry is still listed)

<img width="991" alt="screen shot 2015-12-30 at 5 16 08 pm" src="https://cloud.githubusercontent.com/assets/4266958/12059913/911037ea-af19-11e5-96ff-ddfcdb88c636.png">

Refresh storage pool tab:( VM name is missing)
<img width="985" alt="screen shot 2015-12-30 at 5 18 17 pm" src="https://cloud.githubusercontent.com/assets/4266958/12059918/c5c73fb0-af19-11e5-9627-1130e371c86e.png">

**Comment by vincent99** [comment]
No VMs in 1.2..

**Comment by will-chan** [comment]
Obsolete.
