### ISSUE TITLE
TTL Token values not respected on External SAML Auth

### ISSUE THREAD

**Issue by capta1nk1rk** [rancher/rancher#31593]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

This issue has been confirmed when using both Shibboleth and Okta as external authentication providers.  Highly possible that this occurs with any SAML provider:

1. In the Rancher UI, navigate to global -> settings -> auth-user-session-ttl-minutes
2. Set auth-user-session-ttl-minutes to a non-zero value
3. Exit out of Rancher, login as a user authenticated via Shibboleth or Okta

**Result:**

When viewing the user-session/web-ui token, you will notice that no matter what value is provided in auth-user-session-ttl-minutes, the ttl value is set to 0 (unlimited).  Local user tokens respect the timeout value, but Shibboleth+Okta logins do not.

**Environment information**
- Rancher version: Confirmed on v2.5.3, may be present in newer versions as well

gz#15217

gz#15950

**Comment by adianas** [comment]
Can this solution be backported to v2.4, as one of the customers expects to upgrade to v2.5 in about 3 months?

**Comment by vincent99** [comment]
No, the TTL option doesn't even exist in 2.4; they are always good "forever" (until deleted).

**Comment by axeal** [comment]
@vincent99 Checking in a v2.4.11 lab I see the `auth-user-session-ttl-minutes` is present in Settings and this value is reflected in the ttl value of session tokens.management.cattle.io resources (testing with a local user). This also appears to be adhered to, as setting the value to 1, I am re-directed to login, when attempting to click a link after being idle for more than a minute?

**Comment by izaac** [comment]
This also needs a 2.5 PR for the fix.
`master-head` (2.6) fix is linked

**Comment by izaac** [comment]
Reproduced on `v2.5.3`

Local users session tokens have `ttl` matching the `auth-user-session-ttl-minutes` but in milliseconds in `/v3/tokens`
SAML users in Okta this value is 0 always.

Reopening to get the 2.5 PR which is not yet linked.

**Comment by kinarashah** [comment]
Fix backported to release/v2.5, should be available in `v2.5-head` once build passes

**Comment by izaac** [comment]
Backport issue for 2.5.x https://github.com/rancher/rancher/issues/32691

**Comment by izaac** [comment]
Rancher version `master-head` _3e89bb8_
SAML Backends used: Okta and Keycloak

- Users session token default to what's set in `auth-user-session-ttl-minutes`
- Zero in `auth-user-session-ttl-minutes` is also honored.
- Setting 5 minutes (30000 milliseconds) And wait for the session to expire redirects the user to the login screen as expected.
