### ISSUE TITLE
Rancher 2.5 Air-gap goes to github

### ISSUE THREAD

**Issue by coddan** [rancher/rancher#31597]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Similar to this one: (took some information from community forum that have the same issue)

docker run -d --restart=unless-stopped \
-p 80:80 -p 443:443 \
-e CATTLE_SYSTEM_CATALOG=bundled \
-e CATTLE_SYSTEM_DEFAULT_REGISTRY=secretregistry/docker.io-mirror \
-v /etc/rancher/ssl/hostcert.crt:/etc/rancher/ssl/cert.pem \
-v /etc/rancher/ssl/hostkey.key:/etc/rancher/ssl/key.pem \ 
-v /etc/rancher/ssl/cacert.pem:/etc/rancher/ssl/cacerts.pem \ 
-v /opt/rancher:/var/lib/rancher \ 
-e AUDIT_LEVEL=1  \
-v /var/log/rancher/auditlog:/var/log/auditlog \ 
--privileged \ 
"secretregistry/docker.io-mirror/rancher/rancher:latest”

The same settings with 2.4.x latest we found, is working.
This is for the local cluster that it´s creates, did not add a new cluster, so do not know if that works.

**Result:**
Feb 4 20:36:01 RTST-A0101 journal: E0204 19:36:01.531114 40 kuberuntime_manager.go:727] createPodSandbox for pod “helm-operation-p7d4h_cattle-system(b32591c0-b958-4f1d-93b9-dd2c7c419cf7)” failed: rpc error: code = Unknown desc = failed to get sandbox image “docker.io/rancher/pause:3.1”: failed to pull image “docker.io/rancher/pause:3.1”: failed to pull and unpack image “docker.io/rancher/pause:3.1”: failed to resolve reference “docker.io/rancher/pause:3.1”: failed to do request: Head https://registry-1.docker.io/v2/rancher/pause/manifests/3.1: dial tcp 52.72.232.213:443: i/o timeout
Feb 4 20:36:01 RTST-A0101 journal: E0204 19:36:01.531168 40 pod_workers.go:191] Error syncing pod b32591c0-b958-4f1d-93b9-dd2c7c419cf7 (“helm-operation-p7d4h_cattle-system(b32591c0-b958-4f1d-93b9-dd2c7c419cf7)”), skipping: failed to “CreatePodSandbox” for “helm-operation-p7d4h_cattle-system(b32591c0-b958-4f1d-93b9-dd2c7c419cf7)” with CreatePodSandboxError: “CreatePodSandbox for pod “helm-operation-p7d4h_cattle-system(b32591c0-b958-4f1d-93b9-dd2c7c419cf7)” failed: rpc error: code = Unknown desc = failed to get sandbox image “docker.io/rancher/pause:3.1”: failed to pull image “docker.io/rancher/pause:3.1”: failed to pull and unpack image “docker.io/rancher/pause:3.1”: failed to resolve reference “docker.io/rancher/pause:3.1”: failed to do request: Head https://registry-1.docker.io/v2/rancher/pause/manifests/3.1: dial tcp 52.72.232.213:443: i/o timeout”
Feb 4 20:36:02 RTST-A0101 journal: E0204 19:36:02.530509 40 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox image “docker.io/rancher/pause:3.1”: failed to pull image “docker.io/rancher/pause:3.1”: failed to pull and unpack image “docker.io/rancher/pause:3.1”: failed to resolve reference “docker.io/rancher/pause:3.1”: failed to do request: Head https://registry-1.docker.io/v2/rancher/pause/manifests/3.1: dial tcp 54.236.131.166:443: i/o timeout

**Comment by GLTSC** [comment]
Has it been resolved? I encountered the same problem, but did not find a related solution......
