### ISSUE TITLE
Unable to launch EKS Cluster - Create Launch Template Failed

### ISSUE THREAD

**Issue by haydursek** [rancher/rancher#31605]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1. Use RKE to launch vanilla EKS cluster in AWS using all default options.

**Result:**
Cluster creation fails with message: 'Cluster must have at least one managed nodegroup.' In AWS I can see the cluster is created but no nodes are added. The user being used to provision the resources has full admin access in AWS. I have tried launching into an existing VPC and creating a new one as part of the cluster launch. Both options fail with the 'CreateLaunchTemplate' failure and internal error below.

**Other details that may be helpful:**
I can see in AWS cloud trail that the error is actually with the launch template as below:

```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "A**U",
        "arn": "arn:aws:iam::4**6:user/s**i",
        "accountId": "4**6",
        "accessKeyId": "A**P",
        "userName": "s**i"
    },
    "eventTime": "2021-03-05T20:15:38Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "CreateLaunchTemplate",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "34.204.151.222",
    "userAgent": "aws-sdk-go/1.36.7 (go1.13.8b4; linux; amd64)",
    "errorCode": "Server.InternalError",
    "errorMessage": "An internal error has occurred",
    "requestParameters": {
        "CreateLaunchTemplateRequest": {
            "LaunchTemplateName": "rancher-managed-lt-eks-demo-v3",
            "LaunchTemplateData": {
                "UserData": "<sensitiveDataRemoved>"
            },
            "TagSpecification": {
                "ResourceType": "launch-template",
                "tag": 1,
                "Tag": {
                    "Value": "do-not-modify-or-delete",
                    "tag": 1,
                    "Key": "rancher-managed-template"
                }
            }
        }
    },
    "responseElements": null,
    "requestID": "2a2a1acc-84e6-431b-b197-693b837a2d96",
    "eventID": "4227db83-def7-4815-81c1-6eb4fe553c13",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "eventCategory": "Management",
    "recipientAccountId": "4***6"
}
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.6
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AWS t3.medium - 2 vCPU 8G RAM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
```

- Docker version (use `docker version`):

```
19.03.13-ce
```

**Comment by sowmyav27** [comment]
@haydursek Assuming the EKS cluster was creating using Rancher UI, can you give us the request sent by Rancher to create the EKS cluster ?

**Comment by haydursek** [comment]
@sowmyav27 Sure, where can i find that ?
