### ISSUE TITLE
Catalog stuck in refreshing state for several hours

### ISSUE THREAD

**Issue by abhi1693** [rancher/rancher#31614]
**What kind of request is this (question/bug/enhancement/feature request):**
This bug was not in v2.5.5. I have checked the logs, the syncing finishes successfully but the state does no change. It only happens with bitnami repo for me. Due to this, my terraform operations keep timing out.

**Steps to reproduce (least amount of steps as possible):**
1. Go to global catalogs
2. Add bitnami repo: https://charts.bitnami.com/bitnami

**Result:**
The refreshed state should become active after syncing is finished.

**Other details that may be helpful:**
![image](https://user-images.githubusercontent.com/5083532/110230753-02192d80-7f39-11eb-96ee-df66817bfad8.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.6
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

_Note: I have been able to reproduce this issue on `v2.5.5`, `v2.5.6` and `v2.5.7`_

**Comment by abhi1693** [comment]
```
2021/03/09 09:37:40 [INFO] Catalog sync done. 0 templates created, 2 templates updated, 0 templates deleted, 0 templates failed
W0309 09:37:55.613570      10 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021/03/09 09:38:14 [ERROR] error syncing 'bitnami': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
2021/03/09 09:38:59 [INFO] Updating global catalog bitnami
2021/03/09 09:39:34 [INFO] Catalog sync done. 0 templates created, 2 templates updated, 0 templates deleted, 0 templates failed
2021/03/09 09:40:08 [ERROR] error syncing 'bitnami': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
W0309 09:40:39.238377      10 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

**Comment by abhi1693** [comment]
I am able to reproduce this issue even on a single node rke node setup running on my localhost.

**Comment by jonathon2nd** [comment]
Was this issue ever resolved for you? Seems to be occurring for my installation now.
https://github.com/rancher/rancher/issues/31940

**Comment by abhi1693** [comment]
@jonathon2nd Even after a month, it is still stuck. No matter what I do, it keeps timing out.
