### ISSUE TITLE
Rancher deployed Fleet doesn't persist workspace changes

### ISSUE THREAD

**Issue by dbason** [rancher/rancher#31617]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* Deploy a k8s 1.18 cluster using custom nodes.
* Create a new Fleet workspace.
* Move cluster to new workspace.
* Upgrade k8s to 1.19

**Result:**
Cluster has moved back to the fleet-default workspace in the UI.

**Expected Result:**
Cluster should stay in the workspace it was moved to

**Other details that may be helpful:**
Have tested adding a clusterID and upgrading the fleet-agent app to use that but still results in the cluster moving back to fleet-default

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.6
- Installation option (single install/HA): HA

gz#15537

**Comment by StrongMonkey** [comment]
I am not able to reproduce this issue. What I did:
1. Create a custom k8s 1.18 cluster in rancher.
2. Create a new fleetworkspace w1, assign cluster to w1.
3. Upgrade cluster to 1.19
4. Cluster stays in w1 workspace.

Let me know if there are other details that can help me reproduce this issue.

**Comment by dbason** [comment]
@StrongMonkey my bad with the repro instructions sorry.  It appears that this is only happening when you use RKE templates.  So following your steps above beginning at 3:
3. Convert custom cluster to RKE template.
4. Create new revision with new k8s version
5. Apply new revision to the custom cluster
6. Cluster has moved back to fleet default workspace.

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.5.6`.

Steps:
1. Deploy a k8s 1.18 cluster using custom nodes.
2. Create a new Fleet workspace.
3. Move cluster to new workspace.
4. Convert custom cluster to RKE template.
5. Create new revision with new k8s version
6. Apply new revision to the custom cluster

Result:
Cluster has moved back to fleet default workspace.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 2dca0c6` and `rancher\rancher:v2.5-head` `version 51253e5` 

The workspace is copied when cluster is upgraded using RKE template. Cluster remains in new workspace.

**Comment by aaronRancher** [comment]
Tested an upgrade use case for this issue.

Steps:
1. Deploy Rancher `v2.5.6`
2. Deploy a k8s 1.18 cluster using custom nodes.
3. Create a new Fleet workspace.
4. Move cluster to new workspace.
5. Convert custom cluster to RKE template.
6. Create new revision with new k8s version (1.19)
7. Upgrade Rancher setup to `v2.5-head`
7. Apply new revision to the custom cluster

Result:
The workspace is copied when cluster is upgraded using RKE template. Cluster remains in new workspace.
