### ISSUE TITLE
Load Balancer need in upgrade button

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#3161]
If I wanted to add some ports balancer, I need to create a new LB service, you can add this option to the `edit` button to add or `upgrade` service button for LB

**Comment by asciifaceman** [comment]
+1 unless there is something we are unaware of, I have to use "clone" to change ports

**Comment by will-chan** [comment]
Our API should support this so it looks like we are missing UI to enable this.

**Comment by djskinner** [comment]
+1

**Comment by andyshinn** [comment]
I also noticed that the load balancer doesn't allow me to edit advanced routed services in the UI (no services show up when I edit the load balancer).

**Comment by nunofgs** [comment]
Any news on UI for this?

**Comment by vincent99** [comment]
1.2 does either upgrade or edit, according to what is needed for the change requested.

**Comment by tfiduccia** [comment]
Version - master 11/06
Verified upgrade is available.
