### ISSUE TITLE
ARM64 rancher/rke-tools:v0.1.72 confd Exec format error

### ISSUE THREAD

**Issue by adrootrr** [rancher/rancher#31623]
rancher/rke-tools:v0.1.72

/usr/bin/nginx-proxy: line 4: /usr/bin/confd: cannot execute binary file: Exec format error

**Comment by hamishliu** [comment]
me too

**Comment by hamishliu** [comment]
/usr/bin/nginx-proxy: line 4: /usr/bin/confd: cannot execute binary file: Exec format error
2022/05/18 06:31:21 [notice] 7#7: using the "epoll" event method
2022/05/18 06:31:21 [notice] 7#7: nginx/1.20.1
2022/05/18 06:31:21 [notice] 7#7: built by gcc 10.2.1 20201203 (Alpine 10.2.1_pre1) 
2022/05/18 06:31:21 [notice] 7#7: OS: Linux 4.18.0-193.28.1.el7.aarch64
2022/05/18 06:31:21 [notice] 7#7: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/05/18 06:31:21 [notice] 7#7: start worker processes
2022/05/18 06:31:21 [notice] 7#7: start worker process 8
2022/05/18 06:31:21 [notice] 7#7: start worker process 9
