### ISSUE TITLE
Stacks should have "stopped" state

### ISSUE THREAD

**Issue by haswalt** [rancher/rancher#3162]
When a stack is fully stopped by the user the stack shouldn't show up a degraded but instead should have a stopped status.

In my use case I have some stacks i'm still in the process of designing or aren't in use currently so are effectively turned off. However in my UI i see several degraded services, only 1 of which is actually having problems. This is kind of misleading and doesn't make it easy to spot actually degraded services.

**Comment by will-chan** [comment]
Adding a new 2.0 UI.

**Comment by andyshinn** [comment]
Then, is this feature tracked somewhere else? I subscribe to GitHub issues so that I know when features are merged.
