### ISSUE TITLE
404 page not found after upgrade to 2.5.6

### ISSUE THREAD

**Issue by mfbrj** [rancher/rancher#31624]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Upgrade from Rancher 2.5.5 to 2.5.6:
```
helm repo update
helm fetch rancher-stable/rancher
helm upgrade rancher rancher-stable/rancher --reuse-values --version=2.5.6
```
The upgrade is successful. The 2 replicas are running fine.

**Result:**
Although, when I acess https://rancher.mydomain.com the browser shows only `404 page not found` in a blank page.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): HA in a k3s cluster v1.19.7+k3s1 with 2 nodes.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere on premise
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7+k3s1", GitCommit:"5a00e38db4c198fb0725a6b709380aed8053d637", GitTreeState:"clean", BuildDate:"2021-01-14T23:09:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
(paste the output here)
```

gz#15642

**Comment by pulberg** [comment]
Same issue here, 404 page after upgrade.

**Comment by dbason** [comment]
This is because of a new value introduced in the chart for 2.5.6.  The `--reuse-values` flag doesn't merge in new default values from the chart.  If you use the following commands to upgrade it will avoid this issue:
```
helm get values rancher -n cattle-system -o yaml > values.yaml
helm upgrade rancher rancher-latest/rancher \
  --namespace cattle-system \
  -f values.yaml \
  --version=2.5.6
```

**Comment by mfbrj** [comment]
@dbason It worked fine! Thanks!

**Comment by dbason** [comment]
Good to hear!  I'll close this issue out.
