### ISSUE TITLE
Agent startup /v1/hostapiproxytokens error 500 (code: CantConstructUrl)

### ISSUE THREAD

**Issue by id-romain** [rancher/rancher#3163]
rancher/server version: v0.51.0
rancher/agent version: v0.8.2

Creating a rancher cluster from scratch (3 server nodes, 1 agent ATM), I am facing a problem where the agent, after registration, keeps failing and logging errors.

I can not see any abnormal log lines on rancher-server instance, only pulling catalog library for sync purpose...

The full startup log below:
INFO: Starting agent for 12554282610BFD11EBB7
INFO: Access Key: 12554282610BFD11EBB7
INFO: Config URL: http://rancher-prod-1:8090/v1
INFO: Storage URL: http://rancher-prod-1:8090/v1
INFO: API URL: http://rancher-prod-1:8090/v1
INFO: IP: 10.240.0.24
INFO: Port:
INFO: Required Image: rancher/agent:v0.8.2
INFO: Current Image: rancher/agent:v0.8.2
INFO: Using image rancher/agent:v0.8.2
INFO: Downloading agent http://rancher-prod-1:8090/v1/configcontent/configscripts
INFO: Updating configscripts
INFO: Downloading http://rancher-prod-1:8090/v1//configcontent//configscripts current=
INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/apply.sh
INFO: Sending configscripts applied 1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319
INFO: Updating pyagent
INFO: Downloading http://rancher-prod-1:8090/v1//configcontent//pyagent current=
INFO: Running /var/lib/cattle/download/pyagent/pyagent-1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c06069547103e24f5f4562a2db5d4805d60/apply.sh
INFO: Updating host-api
INFO: Downloading http://rancher-prod-1:8090/v1//configcontent//host-api current=
INFO: Running /var/lib/cattle/download/host-api/1-1dcc85d77415faddc4d6d204d2bd622d835de4b5ee4b472651419b58189c474a/apply.sh
INFO: Sending host-api applied 1-1dcc85d77415faddc4d6d204d2bd622d835de4b5ee4b472651419b58189c474a
INFO: Updating agent-binaries
INFO: Downloading http://rancher-prod-1:8090/v1//configcontent//agent-binaries current=
INFO: Running /var/lib/cattle/download/agent-binaries/1-4200f9b686342da8e941359211b1d8c5f98877ae293d0ead231d43507f1c9eae/apply.sh
INFO: Sending agent-binaries applied 1-4200f9b686342da8e941359211b1d8c5f98877ae293d0ead231d43507f1c9eae
INFO: Updating python-agent
INFO: Downloading http://rancher-prod-1:8090/v1//configcontent//python-agent current=
INFO: Running /var/lib/cattle/download/python-agent/1-5fa9b53964d8b1335257916f7b4687aec2e17c9516e578f5406f29160eec1cd1/apply.sh
INFO: Sending python-agent applied 1-5fa9b53964d8b1335257916f7b4687aec2e17c9516e578f5406f29160eec1cd1
INFO: Updating cadvisor
INFO: Downloading http://rancher-prod-1:8090/v1//configcontent//cadvisor current=
INFO: Running /var/lib/cattle/download/cadvisor/1-4d2b4356ab14bc1fa7ec7cd83f35b7e975a16cea01634683b577c9498c98de25/apply.sh
INFO: HOME -> ./
INFO: HOME -> ./bin/
INFO: HOME -> ./bin/cadvisor
INFO: HOME -> ./bin/cadvisor.sh
INFO: Sending cadvisor applied 1-4d2b4356ab14bc1fa7ec7cd83f35b7e975a16cea01634683b577c9498c98de25
INFO: Updating volmgr
INFO: Downloading http://rancher-prod-1:8090/v1//configcontent//volmgr current=
INFO: Running /var/lib/cattle/download/volmgr/1-c813690c24ae9a12f0792378c78a48f447b243517233d7969b99baefbea5af15/apply.sh
INFO: Sending volmgr applied 1-c813690c24ae9a12f0792378c78a48f447b243517233d7969b99baefbea5af15
INFO: Sending pyagent applied 1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c06069547103e24f5f4562a2db5d4805d60
INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
INFO: Executing /var/lib/cattle/pyagent/main.py
INFO: Updating host-config
INFO: Downloading http://rancher-prod-1:8090/v1//configcontent//host-config current=
INFO: Running /var/lib/cattle/download/host-config/host-config-1-9def75b14980117cf9381f41a0fee28772ff81761831469da2db7c990ce8628c/apply.sh
INFO: HOME -> ./
INFO: HOME -> ./etc/
INFO: HOME -> ./etc/cattle/
INFO: HOME -> ./etc/cattle/api.crt
INFO: Sending host-config applied 1-9def75b14980117cf9381f41a0fee28772ff81761831469da2db7c990ce8628c
time="2016-01-04T08:48:51Z" level="info" msg="Starting event router." 
time="2016-01-04T08:48:51Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
time="2016-01-04T08:48:51Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"6ceef88295867520b80b439df7ec7f74db3e9c418098dc307e7aef090dabec65\", From:\"-simulated-\", Time:0}" 
time="2016-01-04T08:48:51Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=0 reportedUuid="98b491bb-f83a-49ee-9746-47687b0888c5" 
I0104 08:48:51.986737 24664 storagedriver.go:132] No backend storage selected
I0104 08:48:51.986825 24664 storagedriver.go:134] Caching stats in memory for 2m0s
I0104 08:48:51.986990 24664 manager.go:128] cAdvisor running in container: "/docker/8f86325cbaf1463147373927df03c078ffdae771e0e7143f756429390a8ba120/docker/6ceef88295867520b80b439df7ec7f74db3e9c418098dc307e7aef090dabec65"
I0104 08:48:51.992225 24664 fs.go:108] Filesystem partitions: map[/dev/sda1:{mountpoint:/ major:8 minor:1 fsType: blockSize:0}]
I0104 08:48:52.003045 24664 machine.go:48] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I0104 08:48:52.003105 24664 manager.go:163] Machine: {NumCores:1 CpuFrequency:2599998 MemoryCapacity:3884019712 MachineID: SystemUUID:EB5084F1-A011-6603-1739-973474149021 BootID:db8c0afb-be77-4fb4-af75-794a7fcd23af Filesystems:[{Device:/dev/sda1 Capacity:9694191616}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:21474836480 Scheduler:cfq}] NetworkDevices:[{Name:eth0 MacAddress:42:01:0a:f0:00:18 Speed:0 Mtu:1460}] Topology:[{Id:0 Memory:3884019712 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]}] CloudProvider:GCE InstanceType:n1-standard-1}
I0104 08:48:52.004189 24664 manager.go:169] Version: {KernelVersion:4.2.3-rancher ContainerOsVersion:Unknown DockerVersion:1.9.1 CadvisorVersion: CadvisorRevision:}
I0104 08:48:52.008963 24664 factory.go:236] Registering Docker factory
I0104 08:48:52.009871 24664 factory.go:93] Registering Raw factory
I0104 08:48:52.018986 24664 manager.go:1006] Started watching for new ooms in manager
I0104 08:48:52.019032 24664 oomparser.go:199] OOM parser using kernel log file: "/var/log/messages"
I0104 08:48:52.022812 24664 manager.go:250] Starting recovery of all containers
I0104 08:48:52.046550 24664 manager.go:255] Recovery completed
I0104 08:48:52.056388 24664 cadvisor.go:96] Starting cAdvisor version: - on port 9344
time="2016-01-04T08:48:52Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=1 reportedUuid="98b491bb-f83a-49ee-9746-47687b0888c5" 
time="2016-01-04T08:48:53Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=2 reportedUuid="98b491bb-f83a-49ee-9746-47687b0888c5" 
time="2016-01-04T08:48:54Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=3 reportedUuid="98b491bb-f83a-49ee-9746-47687b0888c5" 
time="2016-01-04T08:48:55Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=4 reportedUuid="98b491bb-f83a-49ee-9746-47687b0888c5" 
time="2016-01-04T08:48:56Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=5 reportedUuid="98b491bb-f83a-49ee-9746-47687b0888c5" 
time="2016-01-04T08:48:58Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=6 reportedUuid="98b491bb-f83a-49ee-9746-47687b0888c5" 
time="2016-01-04T08:48:59Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=7 reportedUuid="98b491bb-f83a-49ee-9746-47687b0888c5" 
time="2016-01-04T08:49:00Z" level="fatal" msg="Bad response from [http://rancher-prod-1:8090/v1/hostapiproxytokens], statusCode [500]. Status [500 Server Error]. Body: [{\"id\":\"a2bc507d-4b4d-4c60-aef7-323e49f9a335\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":500,\"code\":\"CantConstructUrl\",\"message\":\"CantConstructUrl\",\"detail\":null}]" 
time="2016-01-04T08:49:01Z" level="info" msg="Starting event router." 
time="2016-01-04T08:49:01Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
time="2016-01-04T08:49:01Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"6ceef88295867520b80b439df7ec7f74db3e9c418098dc307e7aef090dabec65\", From:\"-simulated-\", Time:0}" 
time="2016-01-04T08:49:01Z" level="fatal" msg="Bad response from [http://rancher-prod-1:8090/v1/hostapiproxytokens], statusCode [500]. Status [500 Server Error]. Body: [{\"id\":\"4d7ac1c7-9ce8-407a-9803-43dd6f428ff9\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":500,\"code\":\"CantConstructUrl\",\"message\":\"CantConstructUrl\",\"detail\":null}]" 
time="2016-01-04T08:49:03Z" level="info" msg="Starting event router." 
time="2016-01-04T08:49:03Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
time="2016-01-04T08:49:03Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"6ceef88295867520b80b439df7ec7f74db3e9c418098dc307e7aef090dabec65\", From:\"-simulated-\", Time:0}" 
time="2016-01-04T08:49:03Z" level="fatal" msg="Bad response from [http://rancher-prod-1:8090/v1/hostapiproxytokens], statusCode [500]. Status [500 Server Error]. Body: [{\"id\":\"4aa8d552-89e5-42af-914c-086e9f798b65\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":500,\"code\":\"CantConstructUrl\",\"message\":\"CantConstructUrl\",\"detail\":null}]"

**Comment by id-romain** [comment]
Same happens from browser when requesting endpoints:
- /v1/hosts/1h2/containerstats
- /v1/hosts/1h2/hoststats

Response body example:
{"id":"79f28876-3a47-4189-ae4c-c19e4e27c6ed","type":"error","links":{},"actions":{},"status":500,"code":"CantConstructUrl","message":"CantConstructUrl","detail":null}

**Comment by cjellick** [comment]
@id-romain when you launch rancher server, what values are you setting for `CATTLE_HOST_API_PROXY_MODE ` and `CATTLE_HOST_API_PROXY_HOST `?
See this bit of documentation in case you need a reference: http://docs.rancher.com/rancher/installing-rancher/installing-server/multi-nodes/#configuration

**Comment by id-romain** [comment]
I am running rancher server with docker-compose, and those are the environment variables set for proxy:
- CATTLE_HOST_API_PROXY_MODE="ha"
- CATTLE_HOST_API_PROXY_HOST="146.148.20.18:9999"

146.148.20.18 is the public IP address on the node on which lives the websocket proxy container, listening on port 9999.

**Comment by id-romain** [comment]
Ok, fixed it.
There is a typo in documentation, quotes should not be used to provide API_PROXY environment variables.

Everything works with following configuration:
- CATTLE_HOST_API_PROXY_MODE=ha
- CATTLE_HOST_API_PROXY_HOST=146.148.20.18:9999

Should I let you close the issue ?

**Comment by cjellick** [comment]
Will assign to our chief documenter for a doc update. Thanks!
