### ISSUE TITLE
"error while applying agent YAML for cluster" seen on a cluster edit when "agentEnvVars: []" 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#31635]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

```
Rancher | v2.5.6
User Interface | v2.5.6
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher52
```

**Steps to reproduce (least amount of steps as possible):**
1. On rancher 2.5.6, create a cluster
2. Edit the cluster and change the k8s version to the latest
3. The status on the cluster takes more than 30 sec to change to updating. Before its changed to updating following error is displayed on the UI:
<img width="1319" alt="Screen Shot 2021-03-08 at 8 24 59 PM" src="https://user-images.githubusercontent.com/38144301/110418515-93c58f80-804c-11eb-96a9-72dca865567d.png">

4. Cluster comes up `Active` after updating without any issue

**Other details that may be helpful:**
- Issue not seen on 2.5.5
- Following are the logs seen in the rancher box:
```

2021/03/09 04:20:54 [ERROR] error syncing : handler cluster-deploy: Error while applying agent YAML, 
it will be retried automatically: exit status 1, clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver
unchanged clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master 
unchanged namespace/cattle-system unchanged serviceaccount/cattle unchanged clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged secret/cattle-credentials 
unchanged clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged error: error parsing management-state/tmp/yaml-180688893: 
error converting YAML to JSON: yaml: line 81: did not find expected key , requeuing

```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

Rancher | v2.5.6
User Interface | v2.5.6
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher52

- Installation option (single install/HA):
Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM and 2vcpu/4gb
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}```
```

**Comment by sowmyav27** [comment]
Happens in this scenario also on `2.5.6`:

- Deploy a cluster
- Edit cluster --> Change Drain Nodes to true
- Save changes made
- API request sent has `agentEnvVars: []`
- Error seen in rancher logs: `2021/03/09 05:09:15 [DEBUG] clusterDeploy: deployAgent: error while applying agent YAML for cluster [c-hpzgt], try `
- Cluster comes to Active state. 

But in this case
- Deploy a cluster
- Edit cluster --> Change Drain Nodes to true
- Add Env variable - Key and value pair
- Save changes made
- Cluster goes into Updating state immediately and comes up Active. No error seen in the logs.

**Comment by kinarashah** [comment]
@codyrancher I can possibly fix this by checking len(agentEnvVars), but is there a reason why we send `agentEnvVars: []` instead of `nil` when nothing has been entered for the field?

**Comment by codyrancher** [comment]
@kinarashah the arraylist component required there to be a value which is typically set to an empty array. It's not normally a problem but it can be changed before saving.

**Comment by kinarashah** [comment]
This is fixed in `v2.5.8-rc2`.

**Comment by anupama2501** [comment]
Verified on v2.5.8-rc2
From rancher server create an infrastructure provider with all roles enabled for a node with k8s version v1.18.17-rancher1-2
Once the cluster is active, edit the cluster and set the k8s to v1.19.9-rancher1-2
Status of the cluster is changed to updating and no error is seen

**Comment by anupama2501** [comment]
@kinarashah if we set the drain on delete to True by editing the cluster, I do not see any error but the status "updating" for the cluster is not shown. Is there a reason why?

**Comment by anupama2501** [comment]
Verified on master-ea6b9dd5d853c6cb51d798e4dd4c61835562eddb-head

- Create an infrastructure provider [linode with 1cp+etcd, 3 worker nodes], K8s version: v1.18.17-rancher1-2
- Once the cluster is active, update the k8s version to v1.19.9-rancher1-2
- Status of the cluster changes to updating in 2-3 seconds and no errors seen.
- Once the cluster is active again, set the node on delete to True and no error seen in this case as well[once by adding the environment variables key/value pair]
