### ISSUE TITLE
Update logging chart to 3.9.4

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#31644]
Banzai has released a new version of the logging operator with some bug fixes.  It also introduces the concept of global filters.

This release fixes the issue where the logging operator can get in a state where it cannot reconcile the fluentd configuration.  Global filters will allow users to create a filter that applies on logs before any match or filter mechanism.

We need to update the chart version here https://github.com/rancher/charts/blob/dev-v2.5-source/packages/rancher-logging/package.yaml and add the new images to https://github.com/rancher/image-mirror.

**Comment by nickgerace** [comment]
This includes the changes necessary to complete https://github.com/rancher/rancher/issues/28721

**Comment by nickgerace** [comment]
Charts epic: https://github.com/rancher/rancher/issues/31594

**Comment by izaac** [comment]
Testing done on these other issues using the new 3.9.4 (`3.9.400-rc02`):
https://github.com/rancher/rancher/issues/30949
https://github.com/rancher/rancher/issues/31309

**Comment by izaac** [comment]
P0 Coverate was done in `v2.5-head`.
#32062 Was opened for `master-head` (`2.6`)
