### ISSUE TITLE
Automatic port allocation

### ISSUE THREAD

**Issue by dnadave** [rancher/rancher#3164]
Need the ability for Rancher to automatically assign an open port within a range for containers needing a mapping from an internal port to an external port.  Users cannot see all assigned ports as running processes are hidden in different environments.  Assigning a port already allocated does not result in an error, but in a hung initiation where the container is indicated as being initiated, but never exits that state even after several days.

**Comment by will-chan** [comment]
We just added this feature with 0.51.  Did you try this out with the latest Rancher version?

**Comment by dnadave** [comment]
I'll try this out.  Is there a way to save the rancher configuration and
user credentials between upgrades?

**Comment by will-chan** [comment]
You can follow the instructions here to upgrade:
http://docs.rancher.com/rancher/upgrading/

**Comment by dnadave** [comment]
Hi Will:

The upgrade worked and dynamic port allocation is working great.   One
question, though.  How do I enable health checks when the port is
dynamically allocated?

Thanks!!

Dave H

**Comment by vincent99** [comment]
The health check uses the overlay network and connects to the container port, not the public IP and dynamically-assigned host port.
