### ISSUE TITLE
Upgrade k8s version sees memory increase on downstream clusters

### ISSUE THREAD

**Issue by asemen2608** [rancher/rancher#31640]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Rancher 2.5.5
Upgrade Kubernetes from 1.17.9 to 1.18.15 and then to 1.19.7 downstream on clusters nodes

The following shows the results in memory consumption after the Kubernetes upgrade.
The lines refer to Prometheus screenshots graphs attached.

1.  Master nodes memory usage has increased slowly from 80% to 100% memory usage in a week. See graph "I" (green, red, blue lines)

2. The green master node was replaced "II". The memory consumption grows slowly up from 30% over the week to below 80% or more.

3. The red node was restarted. The memory consumption on the 2nd graph went down to 22%. Memory consumption is slowly growing. Slow growth in the time span of a week up to 80% is expected.

4. On the blue master nodes, etcd and kube-apiserver were restarted. The memory consumption went only about ca. 4% down.

**Result:**

There is a memory freeing up problem on master nodes of the downstream cluster after Kubernetes upgrade. The freeing up memory is not working. In opposite, the nodes have growing memory consumption up to 100%

Expected is no memory consumption increase after Kubernetes upgrade.

**Other details that may be helpful:**

- A workaround is to restart the nodes.  See drop of memory consumption of node presenting the red line on 2nd graph
- A restart of etcd and kube-apiserver showed a too low reduction of memory consumption. See node blue line on 2nd graph

**Environment information**
- Rancher version  v2.5.5
- Installation option HA

![prometheus](https://user-images.githubusercontent.com/61939253/110466012-6f61c580-80d5-11eb-8096-eae41df0d335.png)
![prometheus2](https://user-images.githubusercontent.com/61939253/110466015-6ffa5c00-80d5-11eb-90c3-caf3cb4c40a8.png)

gz#15443
SURE-2818

**Comment by izaac** [comment]
Rancher version: `v2.5.9`

I did a pass with a default installation of a Downstream cluster which is just provisioning the Downstream cluster without any other feature or chart installed to check the resource utilization. 

In this graphic from CloudWatch monitoring the node resources from an EC2 RKE1 cluster the Yellow is where the cluster provisioning occurred using Kubernetes version 1.17

In Red line marks the upgrade to k8s 1.18
And finally the Green line marks the 1.19 k8s upgrade

![upgrade-k8s](https://user-images.githubusercontent.com/27659/132569284-b3e98afa-823a-4b49-8a27-2ea54e5aafdf.png)


There's a noticeable change in memory usage in the control plane but this doesn't make the cluster go above 50% usage, could this indicate that in the cluster used in this issue there might be other feature or software that made the memory usage specially worse than in this "vanilla" Downstream cluster used for testing?

Can we have more details on which charts or apps are being used here?

**Comment by nickgerace** [comment]
I doubt this is the same issue, but this might be related: https://github.com/rancher/rancher/issues/32419#issuecomment-849000867

**Comment by nickgerace** [comment]
@asemen2608: @izaac and I are seeing heightened usage in our matching environment, but not to the same degree that you have. I am curious if there is an app containing an operator that may be hitting this: https://github.com/rancher/rancher/issues/31640#issuecomment-916381236

Our older controllers within Rancher hit this issue in the past as well. Does upgrading to (at least) `v1.19.13` or `v1.21.3` solve the issue? I do notice that your graphs target the control plane, but I am curious if CRDs are the issue potentially.

**Comment by deniseschannon** [comment]
Based on the investigation within upstream k8s, it looks like fixes went in:

https://github.com/kubernetes/kubernetes/issues/102749

It appears that this was fixed in the 

1.19.14+
1.20.9+
1.21.3+ 

Therefore, if we test from upgrading from one of these version to a later version, we shouldn't see this issue. 

Sending it over to test.

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.6-head 8c785a1
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE1 node driver 
Downstream K8s version: 1.19.14

----------

### Testing: ###
1. Provision a rke1 node driver cluster (aws)
  k8s version: 1.19.14
  3 nodes: different role each
2. configure cloud watch to have access to memory metrics
3. upgrade k8s to 1.20.x

I don't see any issues with memory (i used t3.xlarge nodes)
![memory](https://user-images.githubusercontent.com/40282141/156016304-709cb6bf-27f9-427e-8491-b9906533fde2.jpg)
