### ISSUE TITLE
rancher-backup operator not found in App catalog of v2.5.5

### ISSUE THREAD

**Issue by adacaccia** [rancher/rancher#31643]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Follow [official docs](https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/back-up-rancher/) 

**Result:**
1. In the Rancher UI, go to the Cluster Explorer.
2. Click Apps.
3. Click Rancher Backups.
... but there's no "Rancher backup" app listed!

**Other details that may be helpful:**
Still got issues trying to start a second node, so was hoping to solve everything by means of an upgrade to v2.5.6, but I'd like to make a backup prior to upgrade!

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): RancherD v2.5.5
- Installation option (single install/HA): HA

**Comment by sowmyav27** [comment]
On 2.5.5, in the `local` cluster in the setup, `Rancher Backups` is available.

@adacaccia Can you please confirm if you are looking to install the Rancher Backup app in the local cluster of the rancher setup ?

**Comment by adacaccia** [comment]
Tank you @sowmyav27 you're right! One should:
1. Go to local cluster
2. Go to "Default" (not "System") project
3. Go to Dashboard
4. Then "Apps" and Rancher Backups is there!
So I gues documentation needs a few more lines, explaining exactly where to look, since it's not obvious.
