### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by always-waiting** [rancher/rancher#31658]
the container *k8s_cluster-register_cattle-cluster-agent-7986b95f46-m9wpl_cattle-system_9f9c744c-b81f-417d-ad40-ea367ec63338_0* logs showed that: 

```
time="2021-03-11T07:06:27Z" level=info msg="Connecting to wss://deploy-smartops.xxx.com/v3/connect/register with token xxxxxxxxxxxxxxx"
time="2021-03-11T07:06:27Z" level=info msg="Connecting to proxy" url="wss://deploy-smartops.xxx.com/v3/connect/register"
time="2021-03-11T07:06:37Z" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp: i/o timeout"
time="2021-03-11T07:06:37Z" level=error msg="Remotedialer proxy error" error="dial tcp: i/o timeout"
```

how can i fix it?

anyone can help me?

**Comment by always-waiting** [comment]
@chrisbulgaria 
could you help me to handle this question?

**Comment by always-waiting** [comment]
@slickwarren 
could you help me to handle this question?

**Comment by slickwarren** [comment]
hi, please fill out the form below to give some context to your issue. The more detail you can provide about your setup, the more likely we can provide useful information to help:



**What kind of request is this (question/bug/enhancement/feature request):**


**Steps to reproduce (least amount of steps as possible):**


**Result:**


**Other details that may be helpful:**


**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):



**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by always-waiting** [comment]
@slickwarren thanks for reply!
the problem has been solved

**Comment by godocean** [comment]
@always-waiting , how did you solve it? I met the same issue. could you kindly share your solution? Thanks ahead!
