### ISSUE TITLE
Catalog: GlusterFS + Convoy GlusterFS installation failed 

### ISSUE THREAD

**Issue by zijam** [rancher/rancher#3165]
I have tried to install GlusterFS with Convoy GlusterFS on Rancher, but have not got any luck running it.

```
1/5/2016 4:07:54 PMtime="2016-01-05T15:07:54Z" level=error msg="Get http:///host/var/run/conoy-convoy-gluster.sock/v1/volumes/list: dial unix /host/var/run/conoy-convoy-gluster.sock: no such file or directory"
```

I'm using Docker-Machine on OSX.
I have two virtualbox image running with boot2docker
![screen shot 2016-01-05 at 16 11 24](https://cloud.githubusercontent.com/assets/695088/12118478/07763b44-b3c7-11e5-9bd0-1870d19cb446.png)

Running the latest Rancher version
![screen shot 2016-01-05 at 16 11 16](https://cloud.githubusercontent.com/assets/695088/12118477/0191d81e-b3c7-11e5-928d-67d7891f8f47.png)

**Comment by zijam** [comment]
More info:
```
1/5/2016 4:09:12 PMtime="2016-01-05T15:09:12Z" level=error msg="Get http:///host/var/run/conoy-convoy-gluster.sock/v1/volumes/list: dial unix /host/var/run/conoy-convoy-gluster.sock: no such file or directory"
1/5/2016 4:09:12 PMtime="2016-01-05T15:09:12Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/5/2016 4:09:12 PMtime="2016-01-05T15:09:12Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/my_vol /var/lib/rancher/convoy/convoy-gluster-5f02d115-2203-4fa1-9bf2-51d1a7f72909/glusterfs/mounts/my_vol], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/5/2016 4:09:12 PM{
1/5/2016 4:09:12 PM	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/my_vol /var/lib/rancher/convoy/convoy-gluster-5f02d115-2203-4fa1-9bf2-51d1a7f72909/glusterfs/mounts/my_vol], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/5/2016 4:09:12 PM}
1/5/2016 4:09:12 PMtime="2016-01-05T15:09:12Z" level=info msg="convoy exited with error: exit status 1"
1/5/2016 4:09:12 PMtime="2016-01-05T15:09:12Z" level=info msg=Exiting.
```

It looks like the GlusterFS Catalog never create a volume 
```
[root@glusterfs_glusterfs-server_3 /]# gluster volume list                      
No volumes present in cluster                                                   
[root@glusterfs_glusterfs-server_3 /]# gluster volume status                    
No volumes present                                                              
[root@glusterfs_glusterfs-server_3 /]# 
```
Or peers never gets connected:
```
[root@glusterfs_glusterfs-server_3 /]# gluster pool list                        
UUID                                    Hostname        State                   
ac0f5cec-d2b8-4cbc-8006-9361c1e8171f    10.42.21.237    Disconnected            
7d717715-9be7-4eaf-b7aa-8854711ad072    localhost       Connected               
[root@glusterfs_glusterfs-server_3 /]#   
```

Both virtual host are running on the same host 
```
SilverPro:~ siyalrach$ docker-machine ls
NAME                ACTIVE   DRIVER       STATE     URL                         SWARM
data                -        virtualbox   Running   tcp://192.168.99.101:2376   
dev                 *        virtualbox   Running   tcp://192.168.99.100:2376   
```

**Comment by deniseschannon** [comment]
One of the issues that you seem to have is that both of your hosts from your screenshot have the same IP address. Are those the IP addresses for the virtual machines? To update them, you can re-run the rancher/agent command on the host and include `-e CATTLE_AGENT_IP=<ip_of_machine>` to the list of arguments so that are IP gets set correctly. 

After you fix the IPs, can you see that both network agents are able to ping each other by executing into the network agents on one of the host and ping the container IP of the other network agent? This would confirm that cross host communication is working. 

It looks like your glusterfs didn't get set up correctly, which is why you are having the issues with convoy-gluster. I don't know much about glusterfs, but that's what I read with your issue.

**Comment by deniseschannon** [comment]
I was just reading another issue (https://github.com/rancher/rancher/issues/2903), did you have a very early version of the template running? 

Here's what @cjellick wrote in the other issue that you might actually be facing: 
"We did fix some issues around redeploying the stack. So, with today's templates, you should be able to deploy gluster and convoy, delete, and redeploy.

Unfortunately, the fix won't work if you deployed a very early version of the template. There may be some manual cleanup required on your hosts. Specifically, with convoy not installed, you'd need to delete the /etc/docker/plugins/convoy-gluster.spec file and then restart docker."

**Comment by zijam** [comment]
Yes, you are right. IP addresses where wrong. 
I have this setup now:
![screen shot 2016-01-06 at 21 52 19](https://cloud.githubusercontent.com/assets/695088/12154456/dd63ca66-b4bf-11e5-82e4-d420c759eca4.png)

But it looks like it's related to the other issue #2903 
Logs from one of the Convoy GlusterFS
![screen shot 2016-01-06 at 21 59 15](https://cloud.githubusercontent.com/assets/695088/12154657/1431e3a6-b4c1-11e5-9b58-028dee05e36e.png)
![screen shot 2016-01-06 at 21 58 51](https://cloud.githubusercontent.com/assets/695088/12154658/1432ed6e-b4c1-11e5-9e77-b460ad933dbb.png)

Connection between GlusterFS peers are timing out 
![screen shot 2016-01-06 at 22 01 24](https://cloud.githubusercontent.com/assets/695088/12154659/14362b3c-b4c1-11e5-8146-c1b1bdcb441f.png)

**Comment by deniseschannon** [comment]
Okay, I'll close in favor of the other issue as your logs are the same. Please follow the other issue.
