### ISSUE TITLE
GKE Operator lets me create 2 clusters with the same subnetwork

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#31662]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. install https://github.com/rancher/system-charts/tree/dev-v2.5/charts/rancher-gke-operator/1.0.100
2. Create 2 clusters simultaneously with same subnetwork name
3. Try deleting one cluster after creation 

**Result:**
Both clusters get created using same subnetwork. Therefore, when I try to delete any one cluster, GCP won't allow it.

**Other details that may be helpful:**

When 2 clusterConfigs with same subnetworkName is applied simultaneously, both cluster gets created using the same Subnetwork.  
```
± kubectl apply -f gkeclusterconfig-basic-v1.0.1-rc1.yaml ; kubectl apply -f gkeclusterconfig-v1.0.1-rc1.yaml;
gkeclusterconfig.gke.cattle.io/prabal-gkev2-rc1-basic created
gkeclusterconfig.gke.cattle.io/prabal-gkev2-rc1 created
± gcloud container clusters describe prabal-gkev2-rc1-cluster --zone us-east1-b | grep subnetworkName
  subnetworkName: subnet-test
 ± gcloud container clusters describe prabal-gkev2-rc1-basic-cluster --zone us-east1-b | grep subnetworkName
  subnetworkName: subnet-test
  ```

When I apply the same configs sequentially, I get an error. Which is correct, as subnetwork is already in use by the 1st cluster 

```
msg="Cluster prabal-gkev2-rc1-cluster is running"
time="2021-03-09T23:48:30Z" level=error msg="error syncing 'default/prabal-gkev2-rc1-basic': handler gke-controller: googleapi: Error 400: Subnetwork \"projects/suse-css-platform/regions/us-east1/subnetworks/subnet-test\" cannot be created, it already exists in region \"us-east1\"., badRequest, requeuing”
```

 Letting 2 clusters use the same subnetwork causes problems in deletion. Cluster don’t get deleted as subnetwork is in use by the other 
 `Google Compute Engine: The subnetwork resource 'projects/suse-css-platform/regions/us-east1/subnetworks/subnet-test' is already being used by 'projects/suse-css-platform/zones/us-east1-b/instances/gke-prabal-gkev2-rc1-clu-my-node-pool-590768b2-lqt9’.`
Sequence of deletion: Delete one of the 2 clusters( expect the above error on subnet), then delete the other cluster (gets deleted), again try deleting the first cluster (gets completely cleaned up this time)
 
 This can very well be a `GCP issue`. If that is the case, then we need to decide if we wan't to leave it as it is or implement some sort of check in gke-operator to avoid users from facing cluster deletion issues.

**Environment information**
- RKE -Single VM GCE 
- rancher v2.5.5   
- gke-operator  rancher-gke-operator-1.0.100 v1.0.1-rc1 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by satadruroy** [comment]
How is this any different from creating two clusters simultaneously from two console windows or two concurrent `gcloud container clusters create` with same network settings?

**Comment by cmurphy** [comment]
Can you share an example manifest that you're using for this? I guess you're using `ipAllocationPolicy.createSubnetwork` and `ipAllocationPolicy.subnetworkName`?

I'm trying this on RC3 with two clusters with this same manifest except for different cluster names:

```
apiVersion: gke.cattle.io/v1
kind: GKEClusterConfig
metadata:
  name: example-cluster-1
spec:
  clusterName: "colleen-test-1"
  description: "example cluster"
  zone: "us-west1-a"
  projectID: "suse-css-platform"
  kubernetesVersion: "1.18.15-gke.1100"
  clusterIpv4Cidr: ""
  ipAllocationPolicy:
    createSubnetwork: true
    subnetworkName: "new-subnet-2"
    useIpAliases: true
  networkPolicyEnabled: false
  network: "colleen-test-network"
  subnetwork: ""
...
```
```
$ kubectl apply -f cluster-1.yaml --wait=0 ; kubectl apply -f cluster-2.yaml 
gkeclusterconfig.gke.cattle.io/example-cluster-1 created
gkeclusterconfig.gke.cattle.io/example-cluster-2 created
```

The operator starts creating both of them but GKE errors out on one of them: "Google Compute Engine: Invalid value for field 'networkInterfaces[0].aliasIpRanges[0].subnetworkRangeName': 'gke-colleen-test-1-pods-4bb2dc20'. Subnetwork Range name specified does not exist or belong to the given subnetwork."

Even if this wasn't the case and they were both successfully created, I agree with @satadruroy that this isn't the responsibility of the operator to validate. There's no way the operator could know that a subnetwork is about to exist so the creation of a cluster using `createSubnetwork` with the same subnet name should be invalid. The only option I see is to just not support `createSubnetwork` and say that the user must use the `default` subnet or precreate a subnet.
