### ISSUE TITLE
UI - Sidekicks section created in Hosts page when there is no sidekick

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3166]
v0.51.0

Steps To Reproduce:
1. Create a stack that has a sidekicked service (example could be jenkins from catalog). 
2. Create a load balancer.

Result in Hosts page: 
![screen shot 2016-01-05 at 1 56 30 pm](https://cloud.githubusercontent.com/assets/11410997/12128766/4ef084e2-b3b4-11e5-9ee7-aa498031ef39.png)

Expected Result: There shouldn't be a "Sidekicks" section for this service. 

![screen shot 2016-01-05 at 1 56 38 pm](https://cloud.githubusercontent.com/assets/11410997/12128769/520a7d04-b3b4-11e5-90ca-545b7e05b3d8.png)

**Comment by vincent99** [comment]
If any services in that section have sidekicks, they all show the box so you don't end up with weird out of alignment things where the right half is sometimes sidekicks and sometimes other containers.

**Comment by vincent99** [comment]
Obsolete, they're not rendered this way anymore
