### ISSUE TITLE
[QA] Test v2 Rancher features in a hardened environment

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#31664]
Test in a hardened cluster running Rancher from master for the purposes of understanding what all v2 features may break in an environment outlined below:

CIS Hardened profile + SELinux enabled. You can try this with RKE2. You can use the same OS as before, CentOS 8.3.

IF Rancher will not run at all then fall back to just SELinux enabled.
IF any of the v2 features won't work in CIS Hardened or SELinux or both, document each feature that does not work whether it's CIS Hardened, SELinux, or both.

We should end up with a chart that lists what v2 features do/do not work so that we can run with this and start working on solving issues with any features that have problems.
Example of v2 features: istio, monitoring, logging, networking, etc

**Comment by davidnuzik** [comment]
I think this was already tested - now we just need to add CIS Hardened on top of the SELinux Enforcing.

**Comment by deniseschannon** [comment]
Validated as a separate effort. Separate issues were filed if the feature wasn't working on hardened clusters and will be tracked in those individual issues.
