### ISSUE TITLE
UI - Error messages are not within the table header

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3167]
v0.51.0

Steps to Reproduce:
1. Create 2 load balancer with same exposed port
2. Find the container that errors out due to port conflict

Result: The error message is overlapping with the table.
![screen shot 2016-01-05 at 2 12 48 pm](https://cloud.githubusercontent.com/assets/11410997/12129261/46018004-b3b7-11e5-9d42-bc6f0836ccf8.png)

Expected Result: The error message not overlap with the table.

**Comment by tfiduccia** [comment]
Version - master 3.20
Verified fixed
