### ISSUE TITLE
Rancher deletes PV VMDK when node is deleted

### ISSUE THREAD

**Issue by tanskann** [rancher/rancher#31675]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Provision a cluster with vSphere provider
2. Add vSphere as cloud provider & as storage class provisioner
3. Provision some disks using PVC
4. Mount those disks to containers using Pod and make a note of the node where the Pod is running
5. Delete that specific node from UI

**Result:**
Watch your precious data vanish when Rancher deletes the node together with the corresponding PV VMDK attached to it.

**Other details that may be helpful:**
Rancher should first deattach the VMDKs before deleting node so that no data loss occurs.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.5-ac483705ad321e9bdfc868bcf72a0c6ca167d7e1-head
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): v1.19.7-rancher1-1

**Comment by chrismathis** [comment]
We had the same problem two times now with Rancher v2.4.8
When removing a node from the cluster the PV for cluster monitoring got deleted.
