### ISSUE TITLE
GKE operator: Update proxy calls

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#31678]
- [x] Split v1 and v2 calls as necessary
- [x] Make v2 calls work with new cloud credentials

**Comment by cbron** [comment]
Needs main PR merged and 2.5 backport

**Comment by mjura** [comment]
2.6 PR: #31759 
2.5 PR: #31894

**Comment by cbron** [comment]
@prabalsharma or @sowmyav27 need to ensure when testing this one or GKEv2 in general, that GKEv1 clusters continue to be editable. This PR specifically updates the API for them, which should be backwards compatible, but need to double check.

**Comment by prabalsharma** [comment]
@aaronRancher I guess you have tested this as part of the test plan.

**Comment by aaronRancher** [comment]
Validations were done as part of the GKE test plan.

Tested GKEv1 compatibility with the following test cases:
- From Rancher v2.5.7, deploy a GKEv1 cluster. Upgrade to v2.5-head and check compatibility.
- Edit a GKEv1 cluster in a v2.5-head setup.

Tested V2 cloud credentials with the following test cases:
- Create, edit, and delete Google cloud credentials.
- Update Google cloud credentials in a cluster edit. Verify cluster can be edited with new valid credentials.
- Test GKEv2 functionality with Google cloud credentials.
- Verify a cluster edit cannot be made with invalid creds (errors with: `Get "https://container.googleapis.com/...": oauth2: cannot fetch token: 400 Bad Request Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}`).
