### ISSUE TITLE
[backport] Private Registry authentication with no credentials fails

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#31682]
backport of:
- https://github.com/rancher/rancher/issues/31600

**Comment by sowmyav27** [comment]
**On 2.4.15-rc1 validated the following scenarios:**

Clusters came up fine and the System project images pulled were from the right reg

**Cluster level Private Registry**
- Node driver cluster with Priv reg with no Auth
- Node driver cluster with Priv reg with Auth
- Custom cluster with Priv reg with no Auth
- Custom cluster with Priv reg with Auth

**Global Level Private Registry**
- Node driver cluster with Priva reg with no Auth
- Custom cluster with Priva reg with no Auth
