### ISSUE TITLE
Helm chart unexpectedly alters local cluster and uninstallation is impossible

### ISSUE THREAD

**Issue by AndreKR** [rancher/rancher#31699]
I recently ran
```
helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=rancher.example.com --set tls=external
```
on a k3s server (`k3s version v1.17.4+k3s1 (3eee8ac3)`), expecting it would install Rancher in the namespace `cattle-system` which would then allow me to use Rancher to manage other clusters.
On a side note, I used `--set tls=external`, hoping that's the correct setting to let Traefik deal with Let's encrypt. I didn't really understand why the docs say you'd need an extra `cert-manager`.

Instead of simply installing Rancher in the given namespace, it completely took over the local cluster, added a ton of CRDs, added several namespaces and added the cluster to the new Rancher installation.

Then I tried to remove all that again by running
```
system-tools_linux-amd64 remove -c /etc/rancher/k3s/k3s.yaml
```
This caused several problems in the cluster:
* The cluster's service loadbalancer for Traefik was gone. After `service k3s stop`/`service k3s start` it's back.
* For some reason I haven't investigated yet, Traefik has stopped using the proper certificates and serves the example certificates instead
* A lot of stuff wasn't actually removed.

System tools reported:
```
[...]
WARN[0016] Can't build dynamic client for [clusteralertgroups]: the server could not find the requested resource

WARN[0016] Can't build dynamic client for [projectalertrules]: the server could not find the requested resource

WARN[0016] Can't build dynamic client for [globalroles]: the server could not find the requested resource

WARN[0017] Can't build dynamic client for [nodes]: the server could not find the requested resource

WARN[0017] Can't build dynamic client for [clusters]: the server could not find the requested resource

INFO[0017] Removed all Cattle resources succuessfully
INFO[0019] Removed all Cattle CRDs succuessfully
INFO[0019] Removing Rancher Namespace [cattle-system]
INFO[0021] Successfully removed namespace [cattle-system]
INFO[0021] Rancher Management Plane removed successfully
```
but when I run `kubectl get crd` I get:
```
NAME                                               CREATED AT
prometheuses.monitoring.coreos.com                 2021-03-14T21:51:59Z
prometheusrules.monitoring.coreos.com              2021-03-14T21:51:59Z
alertmanagers.monitoring.coreos.com                2021-03-14T21:51:59Z
servicemonitors.monitoring.coreos.com              2021-03-14T21:51:59Z
kontainerdrivers.management.cattle.io              2021-03-14T21:51:32Z
helmcharts.k3s.cattle.io                           2019-04-23T08:38:58Z
globalrolebindings.management.cattle.io            2021-03-14T21:51:32Z
projectroletemplatebindings.management.cattle.io   2021-03-14T21:51:33Z
projectalertgroups.management.cattle.io            2021-03-14T21:51:33Z
nodedrivers.management.cattle.io                   2021-03-14T21:51:32Z
clusterroletemplatebindings.management.cattle.io   2021-03-14T21:51:32Z
projects.management.cattle.io                      2021-03-14T21:51:33Z
clusteralertgroups.management.cattle.io            2021-03-14T21:51:32Z
roletemplates.management.cattle.io                 2021-03-14T21:51:33Z
users.management.cattle.io                         2021-03-14T21:51:30Z
podsecuritypolicytemplates.management.cattle.io    2021-03-14T21:51:33Z
globalroles.management.cattle.io                   2021-03-14T21:51:32Z
nodes.management.cattle.io                         2021-03-14T21:51:32Z
projectalertrules.management.cattle.io             2021-03-14T21:51:33Z
clusters.management.cattle.io                      2021-03-14T21:51:29Z
```

**Comment by AndreKR** [comment]
Something similar was reported [here](https://github.com/rancher/rancher/issues/20918#issuecomment-544880313), but I don't know *how* similar.

**Comment by vincent99** [comment]
Giving Helm a namespace is required, but charts are by no means restricted to that namespace when you say that.

CRDs are cluster-scoped and there is no such thing as putting them "in" a namespace.  Rancher uses them, and other dynamically created namespaces, as the database and the mechanism for enforcing RBAC separation between the clusters/users/etc that it manages.  That may be "unexpected" to you but it is all normal, and part of the reasons we suggest the cluster Rancher is installed on be dedicated to that.

The traefik (v1.x, as shipped with k3s) controller does not provision certificates for ingresses.  That is not what `external` is for.  You need a cert and the standard way to auto-provision either a self-signed one or LetsEncrypt is via cert-manager.

What happens on remove is another matter, and sounds like it's not working right.  And yes at least somewhat related to that issue.

**Comment by AndreKR** [comment]
> That may be "unexpected" to you, but it is all normal, and part of the reasons we suggest the cluster Rancher is installed on be dedicated to that.

What I found unexpected is that after the install Rancher not only *runs* on that cluster but also *manages* it. Are those CRDs and additional namespaces needed for Rancher to run or for Rancher to manage the cluster?

> The traefik (v1.x, as shipped with k3s) controller does not provision certificates for ingresses.

By default it's not enabled, right, but all you need to do is edit the manifest as [described](https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig) in the docs, in particular set `acme.enabled: "anything"` and it will happily request certificates for every ingress host. That's how I use it and I don't know why anyone would want it any other way (except maybe when running into rate limits).

**Comment by vincent99** [comment]
Most are for the state of Rancher itself, though it does also register the cluster it's installed on as "local" and then there are a few things put onto all clusters that are managed.

Cert-manager works everywhere, regardless of what ingress controller is installed or what options it was configured with, so the install instructions reflect that.  K3s is one of the few distros where Traefik is the default controller (and mainly only because there were no ARM builds of nginx at the time).  The server also needs to know what its cert is, to put info from it in kubeconfigs and agent commands, and expects to find that in a particular secret.
