### ISSUE TITLE
[Backport] exec shell on GKE cluster fails with 1006 error

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31690]
Backport of https://github.com/rancher/rancher/issues/31434

**Comment by thedadams** [comment]
A related problem to this is the "Launch kubectl" button does not work an hour after the cluster is created.

**Comment by slickwarren** [comment]
currently blocked by https://github.com/rancher/rancher/issues/33241

**Comment by slickwarren** [comment]
on v2.4-5860-head:
executing into the shell both immediately and after 1+hours is now working as expected
