### ISSUE TITLE
Excessive CPU on calico-node pods

### ISSUE THREAD

**Issue by Quantas** [rancher/rancher#31695]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Updated cluster to latest docker (20.10.x) and k8s (1.20.4) releases.

**Result:**
Witness calico-node pods using > 100% cpu

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.6
- Installation option (single install/HA): HA

**Comment by Quantas** [comment]
This is still an issue I'm noticing.

**Comment by dkeightley** [comment]
This is possibly related to https://github.com/projectcalico/calico/issues/4129

v3.17.2 calico was first available in `v1.20.4-rancher1-1`. It appears this might be the same version in the upgrade, so it would be interesting to confirm the image version running while the issue was occurring.

**Comment by Quantas** [comment]
I believe I still see the issue, every 3 weeks or so, I need to restart my master node because 3.22.0 calico-node is running up the CPU.

**Comment by naah69** [comment]
this problem make we troubled too.
we had to restart node three times in one day.
it there any way to fix it?
rollback calico?
