### ISSUE TITLE
Add logic to import a machine from its extractedConfig field

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#317]
@cjellick created an issue in rancherio/go-machine-service

Add logic to re-import a machine from it's extractedConfig field if that machine doesn't exist on disk.
This will allow to recover from situations where we've lost the go-machine-service's underlying disk (where docker-machine maintains state). This will also allow us to ultimately support mutli-host go-machine-service

**Comment by cjellick** [comment]
@will-chan This one will be needed when we hammer out a fully functional HA setup for Rancher.
Where does that put it? Is it needed for beta or GA?
