### ISSUE TITLE
Bump EC2 AMI

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#31708]
Our default EC2 AMI is out of date, we should update it.

**Comment by thehejik** [comment]
I just deployed Amazon EC2 cluster by using EC2 node driver on rancher:master-head `077fbf6`.

I was using a Node Template for the cluster where I basically just selected region `us-east-2` and kept the AMI field empty.

Once the cluster was provisioned the VMs were using a corresponding ubuntu 20.04 AMI `ami-02fc6052104add5ae` for `us-east-2` region according to the PR above ... [reflink]( https://github.com/rancher/machine/pull/115/files#diff-c513cd9dfff7727888e7b2b58972a8528abf96a9a84638f9b633bcd217865449R34
)

I'm not sure if this is a problem but the link under the AMI field in the Node Template wizard https://github.com/rancher/os/blob/master/README.md/#user-content-amazon is pointing to another images (for `us-east-2` region shows `ami-004259f4c48585992` which is rancheros-v1.5.8-hvm-1 from 02/2021).

**Comment by sowmyav27** [comment]
@thehejik That is expected. That link will point to the RancherOS AMIs

**Comment by thehejik** [comment]
When using the same approach as in https://github.com/rancher/rancher/issues/31708#issuecomment-815040675 on **rancher:v2.5-head** `93d921f` the very same public image `ami-02fc6052104add5ae` ~ `ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210325` is used.

All good, closing.
