### ISSUE TITLE
AKS Cluster Upgrade showing cluster nodes in error only on Cluster Manager.  Waiting on User-Node-Remove

### ISSUE THREAD

**Issue by slessardjr** [rancher/rancher#31701]
**What kind of request is this (question/bug/enhancement/feature request):** BUG

**Steps to reproduce (least amount of steps as possible):**
Create AKS Cluster with oldest version possible
Upgrade to 1.19.7

**Result:**
Cluster Manager shows cluster in error, waiting on user-node-remove for some nodes.
Cluster Explorer looks to be in the right state

**Other details that may be helpful:**
AKS cluster is healthy and the nodes should not remove. In another AKS cluster The node was deletes and rancher just says kubelet stopped posting status along with the waiting on user-node-remove.  We did this upgrade for two other clusters and didn't have any issues but they were executed on 2.5.2

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.6
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Azure AKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 8 Core CPU / 32 GB Ram
- Kubernetes version (use `kubectl version`): 1.19.7

> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"14f897abdc7b57f0850da68bd5959c9ee14ce2fe", GitTreeState:"clean", BuildDate:"2021-01-22T17:29:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
> 

Cluster Explorer showing the cluster in a good status
![AKS_Cluster_Explorer](https://user-images.githubusercontent.com/6098292/111185366-46837980-8588-11eb-8424-1b7c7de33fa9.png)

Cluster Manager showing the cluster in error and waiting to remove nodes.
![AKS_Cluster_Manager](https://user-images.githubusercontent.com/6098292/111185388-4aaf9700-8588-11eb-9cd4-a24d58d41c93.png)

**Comment by slickwarren** [comment]
I tested the following: 
- on HA rancher v2.5.5 deploy an AKS cluster with 1.17.13
- Deploy another cluster with 1.18.10
- upgrade rancher to v2.5.6
- upgrade k8s version on both to 1.19.7

I did the update of k8s simultaneously.  AKS does not allow for [upgrading more than 1 minor version at a time](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions). When attempting through rancher, the error was reported in the UI and remains in an error state.  

<img width="1339" alt="Screen Shot 2021-03-15 at 11 23 30 AM" src="https://user-images.githubusercontent.com/16691014/111214822-a16c9f00-858f-11eb-9bf2-fcae7cc8c044.png">

The other (v1.18.10) cluster remained in `upgrading` stage for longer than expected (at least 10 minutes) but eventually was able to upgrade to v1.19.7 with all services up in both ember and dashboard UIs. 

Currently, there is an [issue with Azure](https://status.azure.com/en-us/status). Once that resolves, I will continue testing old version upgrades.

**Comment by NotANormalNerd** [comment]
We have the same problem:

* The underlying VMs are deleted but the nodes in rancher won't be deleted
* Cloud: Hetzner with Hetzner Cloud Controller
* Rancher v2.5.7
* We have mutliple Nodes in Error state after manually deleting them or scaling them down.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/2896599/111290870-db4cac80-8646-11eb-9b72-665b525cabca.png">

**Comment by slickwarren** [comment]
I was able to continue testing today, and was able to successfully upgrade AKS clusters. 
* on HA rancher v2.5.5 deploy an AKS cluster with 1.17.13
* Deploy another cluster with 1.18.10
* upgrade rancher to v2.5.6
* upgrade minor version of each cluster 1 at a time

**Comment by slessardjr** [comment]
You started with a later version of Rancher. These clusters we created were created with a 2.4.x version of rancher.  I'm wondering if something about the "older version" might have more to do with it.  Can you shed more light on what "Waiting for user-node-remove" means, especially for a cloud provider k8s?

What's confusing me is that the cluster manager shows one state, while the explorer shows another state.

**Comment by anupama2501** [comment]
On version: 
Rancher | v2.5.7
User Interface | v2.5.6

Performed the following tests. Haven't seen the issue mentioned above

<h3>Scenario 1:</h3>
Bring up a cluster with amazon node template with 1 etcd, 1 cp and 4 control planes and kubernetes version 1.20
Once the cluster is active, delete 1 worker node
Node is cordoned and removed

<h3>Scenario 2</h3>
Bring up a cluster with linode node template with 1 etcd, 1 cp and 4 control planes and kubernetes version 1.19
Once the cluster is active, scale down 1 worker node
Node is cordoned and removed


<h3>Scenario 3</h3>
Bring up a cluster with DO node template with 1 etcd, 1 cp and 4 control planes and kubernetes version 1.20
Once the cluster is active, create a workload with ephemeral volume.
Delete the node with the ephemeral volume attached
Node is cordoned and removed

Sample screenshot for all the three scenarios:
<img width="1116" alt="Screen Shot 2021-03-16 at 10 36 10 AM" src="https://user-images.githubusercontent.com/38144301/111366419-b3624680-8650-11eb-9cef-a7a872d598ed.png">

**Comment by slessardjr** [comment]
My issue was able to be resolved.  It appears that due to my upgrade path that some finalizers for the node CRDs that rancher uses to keep the node state were added in what appears to be a bug or possible upgrade path.  The finalizer as I understand it from rancher support is removed in the latest version(s?) of rancher.  

I don't want to pass on mis-information so I don't want to paste any resolution steps until Rancher has time to vet their process and distribute it to those affected.

**Comment by sowmyav27** [comment]
Similar issue - https://github.com/rancher/rancher/issues/31427

**Comment by sowmyav27** [comment]
Upgraded from 2.4.12 to 2.5.5 to 2.5.7 (HA setup). Had an AKS cluster and an RKE custom cluster. Deleting nodes from custom cluster and k8s upgrade of the AKS cluster went through on 2.5.7. No issues seen.

**Comment by slessardjr** [comment]
> Upgraded from 2.4.12 to 2.5.5 to 2.5.7 (HA setup). Had an AKS cluster and an RKE custom cluster. Deleting nodes from custom cluster and k8s upgrade of the AKS cluster went through on 2.5.7. No issues seen.

Can you do the test where you start at 2.4.3.  Create the cluster. Upgrade to 2.5.2 then to 2.5.6 using helm deployment for upgrade.  Then at 2.5.6 upgrade the AKS cluster.

**Comment by NotANormalNerd** [comment]
For my case the nodes are deleted at my Cloud provider just hang around in rancher.
If you go into the cluster explorer for the `local` cluster and then into the nodes, edit yaml and set the `user-remove` annotation to `false` it will delete the node from rancher.

I don't know about the side effects but it will delete the node finally fro rancher.
