### ISSUE TITLE
Rancher-Logging - syslog outout - UDP not working

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rancher#31717]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug or enhancement request

**Steps to reproduce (least amount of steps as possible):**

Deploy rancher logging and configure clusteroutput to a syslog server using insecure UDP 514

**Result:**

No logs are send. Using TCP 514 - logs are send.
Verified with tcpdump.

**Environment information**
- Rancher version "2.5.5"
- Installation option HA

**Cluster information**
- Cluster type RKE2
- Machine type VM
- Kubernetes version (use `kubectl version`): 1.19

**Comment by Martin-Weiss** [comment]
It is still required to get UDP support added for syslog forwarding..

**Comment by Martin-Weiss** [comment]
How can we re-open?

**Comment by stefanlasiewski** [comment]
@Martin-Weiss There is some discussion over at https://github.com/rancher/rancher/issues/32144 . Looks like the plugin is broken. Feel free to join the conversation over there.

(I'm a fellow user)
