### ISSUE TITLE
Certificate Error for the pushprox-kube-etcd-client

### ISSUE THREAD

**Issue by derfred** [rancher/rancher#31716]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Install the rancher-monitoring app using the Cluster Explorer

**Result:**
1. The `etcdMembersDown` and `etcdInsufficientMembers` alerts are firing
2. The `pushprox-kube-etcd-client` logs show the following: `level=error ts=2021-03-16T09:06:59.924Z caller=main.go:89 err="failed to scrape https://PUBLICIP:2379/metrics: Get https://PUBLICIP:2379/metrics: x509: certificate is valid for 10.0.0.6, 127.0.0.1, 10.43.0.1, not PUBLICIP"`

**Other details that may be helpful:**
1. The cluster is using a private network (10.0.0.0/8)
2. Changing the following entry in the `pushprox-kube-etcd-client` DaemonSet YAML to the private IP fixes the log entry, but not the alerts firing:
```
  containers:
  - args:
    - --fqdn=10.0.0.6     <---- Manually changed from $(HOST_IP)
    - --proxy-url=$(PROXY_URL)
    - --metrics-addr=$(PORT)
    - --allow-port=2379
    - --tls.cert=/etc/ssl/push-proxy/push-proxy.pem
    - --tls.key=/etc/ssl/push-proxy/push-proxy-key.pem
    - --tls.cacert=/etc/ssl/push-proxy/push-proxy-ca-cert.pem
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

Rancher | v2.5.5
User Interface | v2.5.4
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

- Installation option (single install/HA):
Single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom using the Hetzner Driver
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VMs
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:23:45Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by superseb** [comment]
Thanks, this is the same as https://github.com/rancher/rancher/issues/31650
