### ISSUE TITLE
Rancher process keeps consuming CPU until failure with 'generate_serving_certificate: true' enabled

### ISSUE THREAD

**Issue by Rancheroo** [rancher/rancher#31712]
SURE-3089
SURE-3433

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create an environment (as described below) and power off 50% of the workers overnight, power back on in the morning.
Environment specs
RHEL 7.9
Docker 1.13.1
K8s
local 1.17.13
downstream 1.18.10
Scale the cluster up to 60 nodes
CIS 1.5 Hardening applied
'generate_serving_certificate: true'

The Rancher logs are literally spammed with generate certificate messages that seems more aggressive then needed.
![image](https://user-images.githubusercontent.com/56899019/111233506-37143700-8641-11eb-8918-9dc4bdffd03e.png)

**Result:**
When the generate_service_certificate: true is enabled, the CPU for the rancher process on the rancher pods keeps getting larger until the cluster fails.

![image](https://user-images.githubusercontent.com/56899019/111230960-87d56100-863c-11eb-8e51-8e20f895830b.png)

**Other details that may be helpful:**
I have a sneaking suspicion that this is to do with an outdated crypto library on the RHEL operating system.

Initially, we thought this was something to do with clusters being powered off after hours and Rancher spinning its wheels to poll them. However, this setting seems much more likely to be the culprit.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.10
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): m5.xlarge
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): I have docker info not version

```
Containers: 50
 Running: 36
 Paused: 0
 Stopped: 14
Images: 21
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-1160.6.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.9 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 15.22 GiB
Name: pcbc-dev-rancher-master-blue-0
ID: NZOC:STDU:BHHW:XMWE:ZNCO:57XJ:DPZY:2MB6:QV6D:HFGK:5TV2:HDVD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.auiag.corp:8080
Https Proxy: http://proxy.auiag.corp:8080
No Proxy: localhost,127.0.0.1,169.254.169.254,10.42.0.0/16,10.43.0.0/16,iagcloud.net,nexus3.auiag.corp,nexus3-uat.auiag.corp,nexus3.iag.com.au
Registry: https://registry.access.redhat.com/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: registry.access.redhat.com (secure), registry.redhat.io (secure), docker.io (secure), docker.io (secure)

```

gz#14625

**Comment by snasovich** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/36025 which is the same issue and already has necessary labels and such.
