### ISSUE TITLE
Graph view overlaps footer

### ISSUE THREAD

**Issue by smw355** [rancher/rancher#3172]
When in graph view, applications now seem to sit on top of the new lower nav section.  See screen shot below. 

![image](https://cloud.githubusercontent.com/assets/9849879/12131908/7cf677c2-b3cb-11e5-8b5e-c12c161694c5.png)

**Comment by tfiduccia** [comment]
Version - master 3/4
Still overlaps on my laptop
![image](https://cloud.githubusercontent.com/assets/11514927/13543425/5515a760-e228-11e5-993d-ab37e909fc98.png)

**Comment by westlywright** [comment]
Tested this on my local and on latest.rancher and seems to be resolved. 

https://www.dropbox.com/s/g6vobe3gqyjkij4/Screenshot%202016-03-09%2014.38.40.png?dl=0

**Comment by tfiduccia** [comment]
Version - master 3/16
Fixed Verified.
