### ISSUE TITLE
"404 page not found" when accessing the WebUI of Rancher Server v2.4.13

### ISSUE THREAD

**Issue by FredChenChwThrox** [rancher/rancher#31724]
Dear team:

I come accros a issue when installing single node rancher server v2.4.13.
I got a "404 page not found" when trying to access the WebUI through https://my-host-ip.

I have searched the existing issues with similar problems. But it shows the problem should be fixed before.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
I follow the install doc on https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/install-rancher/ to install a new rancher server on Ubuntu18.04 with Docker  20.10.5 and latest k3s

```
docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:05 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
I install the docker as a standalone docker container. 
```
 docker ps
CONTAINER ID   IMAGE                                    COMMAND                  CREATED        STATUS        PORTS                                      NAMES
ee0606ba8648   127.0.0.1:5000/rancher/rancher:v2.4.15   "entrypoint.sh"          45 hours ago   Up 45 hours   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   blissful_wescoff
613346278f97   registry:2                               "/entrypoint.sh /etc…"   4 days ago     Up 4 days     0.0.0.0:5000->5000/tcp                     registry
dcd8ab5fd9f2   897ce3c5fc8f                             "entry"                  4 days ago     Up 4 days                                                k8s_lb-port-443_svclb-traefik-p5xzt_kube-system_700ff6a8-8e6d-484b-afb7-8b29521ea87f_0
ddb2e45e4096   897ce3c5fc8f                             "entry"                  4 days ago     Up 4 days                                                k8s_lb-port-80_svclb-traefik-p5xzt_kube-system_700ff6a8-8e6d-484b-afb7-8b29521ea87f_0
747219a20de2   aa764f7db305                             "/traefik --configfi…"   4 days ago     Up 4 days                                                k8s_traefik_traefik-6f9cbd9bd4-9g264_kube-system_e20d38a7-75ea-494d-a376-d25e98c634ab_0
d941206248f1   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_svclb-traefik-p5xzt_kube-system_700ff6a8-8e6d-484b-afb7-8b29521ea87f_0
8357523eb02a   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_traefik-6f9cbd9bd4-9g264_kube-system_e20d38a7-75ea-494d-a376-d25e98c634ab_0
a4251e527d10   148c19256271                             "local-path-provisio…"   4 days ago     Up 4 days                                                k8s_local-path-provisioner_local-path-provisioner-5ff76fc89d-mg7pq_kube-system_18d61593-5f65-4f3c-97c6-9fc97e0d0bcf_0
2ab642ca4fcd   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_local-path-provisioner-5ff76fc89d-mg7pq_kube-system_18d61593-5f65-4f3c-97c6-9fc97e0d0bcf_1
7ffb497e7e7a   296a6d5035e2                             "/coredns -conf /etc…"   4 days ago     Up 4 days                                                k8s_coredns_coredns-854c77959c-94pd6_kube-system_b490e8bc-b244-49cd-968a-aefb8ab714ff_0
c349d65abc72   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_coredns-854c77959c-94pd6_kube-system_b490e8bc-b244-49cd-968a-aefb8ab714ff_1
62525d463ee1   9dd718864ce6                             "/metrics-server"        4 days ago     Up 4 days                                                k8s_metrics-server_metrics-server-86cbb8457f-bd6kw_kube-system_4e1b1f70-0a1f-4575-ae5c-53a640fdd71f_0
fc04e9864366   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_metrics-server-86cbb8457f-bd6kw_kube-system_4e1b1f70-0a1f-4575-ae5c-53a640fdd71f_0
```

**Result:**
I got a "404 page not find" error when access the WebUI

I also try the curl cmd on local:
```
 curl --no-proxy '*' -kv https://127.0.0.1
```
on the terminal, and it shows the same result

```
$ curl --no-proxy '*' -kv https://127.0.0.1
* Rebuilt URL to: https://127.0.0.1/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=Colorado; L=Boulder; O=ExampleCorp; OU=IT; CN=*.example.com; emailAddress=admin@example.com
*  start date: Oct 24 21:09:52 2016 GMT
*  expire date: Oct 24 21:09:52 2017 GMT
*  issuer: C=US; ST=Colorado; L=Boulder; O=ExampleCorp; OU=IT; CN=*.example.com; emailAddress=admin@example.com
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5617441d5580)
> GET / HTTP/2
> Host: 127.0.0.1
> User-Agent: curl/7.58.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 404
< content-type: text/plain; charset=utf-8
< vary: Accept-Encoding
< x-content-type-options: nosniff
< content-length: 19
< date: Mon, 15 Mar 2021 09:31:18 GMT
<
404 page not found
* Connection #0 to host 127.0.0.1 left intact

```

I check the logs and it show nothing help to me.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.13
- Installation option (single install/HA): single install

**Comment by RichardSong-dev** [comment]
> 
> 
> Dear team:
> 
> I come accros a issue when installing single node rancher server v2.4.13.
> I got a "404 page not found" when trying to access the WebUI through https://my-host-ip.
> 
> I have searched the existing issues with similar problems. But it shows the problem should be fixed before.
> 
> **What kind of request is this (question/bug/enhancement/feature request):**
> Bug
> 
> **Steps to reproduce (least amount of steps as possible):**
> I follow the install doc on https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/install-rancher/ to install a new rancher server on Ubuntu18.04 with Docker 20.10.5 and latest k3s
> 
> ```
> docker version
> Client: Docker Engine - Community
>  Version:           20.10.5
>  API version:       1.41
>  Go version:        go1.13.15
>  Git commit:        55c4c88
>  Built:             Tue Mar  2 20:18:05 2021
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.5
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       363e9a8
>   Built:            Tue Mar  2 20:16:00 2021
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.4.4
>   GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
>  runc:
>   Version:          1.0.0-rc93
>   GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> ```
> 
> ```
> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> I install the docker as a standalone docker container.
> 
> ```
>  docker ps
> CONTAINER ID   IMAGE                                    COMMAND                  CREATED        STATUS        PORTS                                      NAMES
> ee0606ba8648   127.0.0.1:5000/rancher/rancher:v2.4.15   "entrypoint.sh"          45 hours ago   Up 45 hours   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   blissful_wescoff
> 613346278f97   registry:2                               "/entrypoint.sh /etc…"   4 days ago     Up 4 days     0.0.0.0:5000->5000/tcp                     registry
> dcd8ab5fd9f2   897ce3c5fc8f                             "entry"                  4 days ago     Up 4 days                                                k8s_lb-port-443_svclb-traefik-p5xzt_kube-system_700ff6a8-8e6d-484b-afb7-8b29521ea87f_0
> ddb2e45e4096   897ce3c5fc8f                             "entry"                  4 days ago     Up 4 days                                                k8s_lb-port-80_svclb-traefik-p5xzt_kube-system_700ff6a8-8e6d-484b-afb7-8b29521ea87f_0
> 747219a20de2   aa764f7db305                             "/traefik --configfi…"   4 days ago     Up 4 days                                                k8s_traefik_traefik-6f9cbd9bd4-9g264_kube-system_e20d38a7-75ea-494d-a376-d25e98c634ab_0
> d941206248f1   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_svclb-traefik-p5xzt_kube-system_700ff6a8-8e6d-484b-afb7-8b29521ea87f_0
> 8357523eb02a   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_traefik-6f9cbd9bd4-9g264_kube-system_e20d38a7-75ea-494d-a376-d25e98c634ab_0
> a4251e527d10   148c19256271                             "local-path-provisio…"   4 days ago     Up 4 days                                                k8s_local-path-provisioner_local-path-provisioner-5ff76fc89d-mg7pq_kube-system_18d61593-5f65-4f3c-97c6-9fc97e0d0bcf_0
> 2ab642ca4fcd   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_local-path-provisioner-5ff76fc89d-mg7pq_kube-system_18d61593-5f65-4f3c-97c6-9fc97e0d0bcf_1
> 7ffb497e7e7a   296a6d5035e2                             "/coredns -conf /etc…"   4 days ago     Up 4 days                                                k8s_coredns_coredns-854c77959c-94pd6_kube-system_b490e8bc-b244-49cd-968a-aefb8ab714ff_0
> c349d65abc72   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_coredns-854c77959c-94pd6_kube-system_b490e8bc-b244-49cd-968a-aefb8ab714ff_1
> 62525d463ee1   9dd718864ce6                             "/metrics-server"        4 days ago     Up 4 days                                                k8s_metrics-server_metrics-server-86cbb8457f-bd6kw_kube-system_4e1b1f70-0a1f-4575-ae5c-53a640fdd71f_0
> fc04e9864366   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_metrics-server-86cbb8457f-bd6kw_kube-system_4e1b1f70-0a1f-4575-ae5c-53a640fdd71f_0
> ```
> 
> **Result:**
> I got a "404 page not find" error when access the WebUI
> 
> I also try the curl cmd on local:
> 
> ```
>  curl --no-proxy '*' -kv https://127.0.0.1
> ```
> 
> on the terminal, and it shows the same result
> 
> ```
> $ curl --no-proxy '*' -kv https://127.0.0.1
> * Rebuilt URL to: https://127.0.0.1/
> *   Trying 127.0.0.1...
> * TCP_NODELAY set
> * Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/certs/ca-certificates.crt
>   CApath: /etc/ssl/certs
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
> * ALPN, server accepted to use h2
> * Server certificate:
> *  subject: C=US; ST=Colorado; L=Boulder; O=ExampleCorp; OU=IT; CN=*.example.com; emailAddress=admin@example.com
> *  start date: Oct 24 21:09:52 2016 GMT
> *  expire date: Oct 24 21:09:52 2017 GMT
> *  issuer: C=US; ST=Colorado; L=Boulder; O=ExampleCorp; OU=IT; CN=*.example.com; emailAddress=admin@example.com
> *  SSL certificate verify result: self signed certificate (18), continuing anyway.
> * Using HTTP2, server supports multi-use
> * Connection state changed (HTTP/2 confirmed)
> * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> * Using Stream ID: 1 (easy handle 0x5617441d5580)
> > GET / HTTP/2
> > Host: 127.0.0.1
> > User-Agent: curl/7.58.0
> > Accept: */*
> >
> * Connection state changed (MAX_CONCURRENT_STREAMS updated)!
> < HTTP/2 404
> < content-type: text/plain; charset=utf-8
> < vary: Accept-Encoding
> < x-content-type-options: nosniff
> < content-length: 19
> < date: Mon, 15 Mar 2021 09:31:18 GMT
> <
> 404 page not found
> * Connection #0 to host 127.0.0.1 left intact
> ```
> 
> I check the logs and it show nothing help to me.
> 
> **Environment information**
> 
>     * Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.13
> 
>     * Installation option (single install/HA): single install

Hello @FredChenChwThrox, I have got the same problem like you, but I can access the web ui at first right after I finishing the installation of rancher for the first time. After I finished installing k3s couple minutes later, I got the 404 response. The problem is obtained by reinstalling rancher or stop the k3s service.
Have you solve this problem? Any suggestion will be appreciated!

**Comment by FredChenChwThrox** [comment]
> > Dear team:
> > I come accros a issue when installing single node rancher server v2.4.13.
> > I got a "404 page not found" when trying to access the WebUI through https://my-host-ip.
> > I have searched the existing issues with similar problems. But it shows the problem should be fixed before.
> > **What kind of request is this (question/bug/enhancement/feature request):**
> > Bug
> > **Steps to reproduce (least amount of steps as possible):**
> > I follow the install doc on https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/install-rancher/ to install a new rancher server on Ubuntu18.04 with Docker 20.10.5 and latest k3s
> > ```
> > docker version
> > Client: Docker Engine - Community
> >  Version:           20.10.5
> >  API version:       1.41
> >  Go version:        go1.13.15
> >  Git commit:        55c4c88
> >  Built:             Tue Mar  2 20:18:05 2021
> >  OS/Arch:           linux/amd64
> >  Context:           default
> >  Experimental:      true
> > 
> > Server: Docker Engine - Community
> >  Engine:
> >   Version:          20.10.5
> >   API version:      1.41 (minimum version 1.12)
> >   Go version:       go1.13.15
> >   Git commit:       363e9a8
> >   Built:            Tue Mar  2 20:16:00 2021
> >   OS/Arch:          linux/amd64
> >   Experimental:     false
> >  containerd:
> >   Version:          1.4.4
> >   GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
> >  runc:
> >   Version:          1.0.0-rc93
> >   GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
> >  docker-init:
> >   Version:          0.19.0
> >   GitCommit:        de40ad0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > $ kubectl version
> > Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
> > Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I install the docker as a standalone docker container.
> > ```
> >  docker ps
> > CONTAINER ID   IMAGE                                    COMMAND                  CREATED        STATUS        PORTS                                      NAMES
> > ee0606ba8648   127.0.0.1:5000/rancher/rancher:v2.4.15   "entrypoint.sh"          45 hours ago   Up 45 hours   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   blissful_wescoff
> > 613346278f97   registry:2                               "/entrypoint.sh /etc…"   4 days ago     Up 4 days     0.0.0.0:5000->5000/tcp                     registry
> > dcd8ab5fd9f2   897ce3c5fc8f                             "entry"                  4 days ago     Up 4 days                                                k8s_lb-port-443_svclb-traefik-p5xzt_kube-system_700ff6a8-8e6d-484b-afb7-8b29521ea87f_0
> > ddb2e45e4096   897ce3c5fc8f                             "entry"                  4 days ago     Up 4 days                                                k8s_lb-port-80_svclb-traefik-p5xzt_kube-system_700ff6a8-8e6d-484b-afb7-8b29521ea87f_0
> > 747219a20de2   aa764f7db305                             "/traefik --configfi…"   4 days ago     Up 4 days                                                k8s_traefik_traefik-6f9cbd9bd4-9g264_kube-system_e20d38a7-75ea-494d-a376-d25e98c634ab_0
> > d941206248f1   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_svclb-traefik-p5xzt_kube-system_700ff6a8-8e6d-484b-afb7-8b29521ea87f_0
> > 8357523eb02a   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_traefik-6f9cbd9bd4-9g264_kube-system_e20d38a7-75ea-494d-a376-d25e98c634ab_0
> > a4251e527d10   148c19256271                             "local-path-provisio…"   4 days ago     Up 4 days                                                k8s_local-path-provisioner_local-path-provisioner-5ff76fc89d-mg7pq_kube-system_18d61593-5f65-4f3c-97c6-9fc97e0d0bcf_0
> > 2ab642ca4fcd   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_local-path-provisioner-5ff76fc89d-mg7pq_kube-system_18d61593-5f65-4f3c-97c6-9fc97e0d0bcf_1
> > 7ffb497e7e7a   296a6d5035e2                             "/coredns -conf /etc…"   4 days ago     Up 4 days                                                k8s_coredns_coredns-854c77959c-94pd6_kube-system_b490e8bc-b244-49cd-968a-aefb8ab714ff_0
> > c349d65abc72   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_coredns-854c77959c-94pd6_kube-system_b490e8bc-b244-49cd-968a-aefb8ab714ff_1
> > 62525d463ee1   9dd718864ce6                             "/metrics-server"        4 days ago     Up 4 days                                                k8s_metrics-server_metrics-server-86cbb8457f-bd6kw_kube-system_4e1b1f70-0a1f-4575-ae5c-53a640fdd71f_0
> > fc04e9864366   rancher/pause:3.1                        "/pause"                 4 days ago     Up 4 days                                                k8s_POD_metrics-server-86cbb8457f-bd6kw_kube-system_4e1b1f70-0a1f-4575-ae5c-53a640fdd71f_0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Result:**
> > I got a "404 page not find" error when access the WebUI
> > I also try the curl cmd on local:
> > ```
> >  curl --no-proxy '*' -kv https://127.0.0.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > on the terminal, and it shows the same result
> > ```
> > $ curl --no-proxy '*' -kv https://127.0.0.1
> > * Rebuilt URL to: https://127.0.0.1/
> > *   Trying 127.0.0.1...
> > * TCP_NODELAY set
> > * Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
> > * ALPN, offering h2
> > * ALPN, offering http/1.1
> > * successfully set certificate verify locations:
> > *   CAfile: /etc/ssl/certs/ca-certificates.crt
> >   CApath: /etc/ssl/certs
> > * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> > * TLSv1.3 (IN), TLS handshake, Server hello (2):
> > * TLSv1.2 (IN), TLS handshake, Certificate (11):
> > * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> > * TLSv1.2 (IN), TLS handshake, Server finished (14):
> > * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> > * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
> > * TLSv1.2 (OUT), TLS handshake, Finished (20):
> > * TLSv1.2 (IN), TLS handshake, Finished (20):
> > * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
> > * ALPN, server accepted to use h2
> > * Server certificate:
> > *  subject: C=US; ST=Colorado; L=Boulder; O=ExampleCorp; OU=IT; CN=*.example.com; emailAddress=admin@example.com
> > *  start date: Oct 24 21:09:52 2016 GMT
> > *  expire date: Oct 24 21:09:52 2017 GMT
> > *  issuer: C=US; ST=Colorado; L=Boulder; O=ExampleCorp; OU=IT; CN=*.example.com; emailAddress=admin@example.com
> > *  SSL certificate verify result: self signed certificate (18), continuing anyway.
> > * Using HTTP2, server supports multi-use
> > * Connection state changed (HTTP/2 confirmed)
> > * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> > * Using Stream ID: 1 (easy handle 0x5617441d5580)
> > > GET / HTTP/2
> > > Host: 127.0.0.1
> > > User-Agent: curl/7.58.0
> > > Accept: */*
> > >
> > * Connection state changed (MAX_CONCURRENT_STREAMS updated)!
> > < HTTP/2 404
> > < content-type: text/plain; charset=utf-8
> > < vary: Accept-Encoding
> > < x-content-type-options: nosniff
> > < content-length: 19
> > < date: Mon, 15 Mar 2021 09:31:18 GMT
> > <
> > 404 page not found
> > * Connection #0 to host 127.0.0.1 left intact
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I check the logs and it show nothing help to me.
> > **Environment information**
> > ```
> > * Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.13
> > 
> > * Installation option (single install/HA): single install
> > ```
> 
> Hello @FredChenChwThrox, I have got the same problem like you, but I can access the web ui at first right after I finishing the installation of rancher for the first time. After I finished installing k3s couple minutes later, I got the 404 response. The problem is obtained by reinstalling rancher or stop the k3s service.
> Have you solve this problem? Any suggestion will be appreciated!

Hi Richard:

I found my issue caused by the traefik on k3s, I didn't configure the ACL for Rancher UI. Disable it can fix the problem.
