### ISSUE TITLE
Rancher/rancher-agent out of date (latest available release is v2.4.8)

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31729]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
when installing monitoring v2, this old image is used

**Result:**
<img width="1281" alt="Screen Shot 2021-03-16 at 8 41 54 PM" src="https://user-images.githubusercontent.com/16691014/111503458-03e6ac00-8704-11eb-98fb-b524e0a84a56.png">

**Other details that may be helpful:**
already spoke with @aiyengar2 who will update the image

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

- Docker version (use `docker version`):

**Comment by aiyengar2** [comment]
@prachidamle @cbron we're also out of date with kubectl images in rancher-gatekeeper and rancher-cis-benchmark. Updated those in the PR for this issue too.

**Comment by cbron** [comment]
Was bumping kubectl mandatory for a fix or just a general update ? We should attempt to keep the versions in line with what is in rancher.

**Comment by aiyengar2** [comment]
General update; we can omit it in the PR if there are any objections.

w.r.t. keeping all versions in line, [Fleet](https://github.com/rancher/fleet/issues/311) has been bumped to 1.20.2, so we should either revert that or bump kubectl across all feature charts as well.

**Comment by cbron** [comment]
We can bump everywhere as long as it doesn't cause problems, I'd just like to keep it uniform if possible.

**Comment by slickwarren** [comment]
Tested on 2.5-head (b2a34d7cef440e3ed1de7d506233aa3a332649ae) using the latest monitoring RC `9.4.204-rc07`
<img width="936" alt="Screen Shot 2021-03-31 at 8 54 26 AM" src="https://user-images.githubusercontent.com/16691014/113174340-21853c80-91ff-11eb-949d-f8a56542f219.png">

* the image tag has been updated to 2.5.7
