### ISSUE TITLE
[Fleet] Cluster stuck in Wait Check-In state

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#31737]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
On Rancher `master-head`, deploy a custom cluster (I used 1 node all roles)
Navigate to Dashboard > Continuous Delivery > Clusters

**Result:**
Cluster is stuck in `Wait Check-In` state:
![Screen Shot 2021-03-17 at 1 34 29 PM](https://user-images.githubusercontent.com/57409052/111542056-7b313580-872e-11eb-98bf-ab16c785bc4a.png)

**Other details that may be helpful:**
This is not seen in Rancher `v2.5-head` `version 51253e5`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher `master-head` `version 2dca0c6`
- Installation option (single install/HA): single install

**Comment by sowmyav27** [comment]
Closing this as its a dup of - https://github.com/rancher/rancher/issues/30978
