### ISSUE TITLE
How could I cleanup the Processes stalled?

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [rancher/rancher#3173]
![screenshot from 2016-01-06 11-58-50](https://cloud.githubusercontent.com/assets/897428/12138828/e2c1e52c-b46c-11e5-90fa-2debeb651e5a.png)

**Comment by cjellick** [comment]
In this case, would need to know the underlying causes. Can you click into one or two of these and expand all the underlying processes and share that info?
