### ISSUE TITLE
Logging v2 - rke logs not seen in Elasticsearch after upgrading to latest 3.9.x RC

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#31731]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install Rancher version `v2.5-head`
- Install the logging v2 (chart `3.8.201`)
   - Use a clusteroutput and clusterflow pointing to an Elasticsearch instance.
- Validate the RKE logs are flowing
- Upgrade the chart to `3.9.002-rc01` from Dashboard.

**Result:**

- After upgrade the logs are not seen in the Elasticsearch output
- No errors in the rke-aggregator pods

**Other details that may be helpful:**
Elasticsearch version: `elasticsearch:7.8.0`

**Environment information**
- Rancher version: `v2.5-head (03/16/2021)` _868c715_
- Installation option: HA

https://github.com/rancher/rancher/issues/31309

**Comment by izaac** [comment]
Using a different output (the example logging app) this works as expected.

**Comment by paynejacob** [comment]
I am able to get rke logs on 3.9.400-rc02 on es 6 and 7.

The es clusters were installed on the same downstream kubernetes cluster as logging.

GET /all-logs/_search?pretty&q=stderr

returns

```
{
        "_index" : "all-logs",
        "_type" : "_doc",
        "_id" : "AASSqXgBQJqxLMczhkOr",
        "_score" : 0.46689463,
        "_source" : {
          "filename" : "/var/lib/rancher/rke/log/kube-controller-manager_10a0caf893f464940f06a6c330ea7950d26a8dc408c53e663ade371b9774ca19.log",
          "log" : "I0406 23:42:14.980525       1 event.go:291] \"Event occurred\" object=\"es7/elasticsearch-master-elasticsearch-master-0\" kind=\"PersistentVolumeClaim\" apiVersion=\"v1\" type=\"Normal\" reason=\"FailedBinding\" message=\"no persistent volumes available for this claim and no storage class is set\"\n",
          "stream" : "stderr",
          "time" : "2021-04-06T23:42:14.980689962Z"
        }
      }
```

[flowsandoutputs.zip](https://zube.io/files/rancher/16d63334f088706019f5db58b3aed89e-flowsandoutputs.zip)

**Comment by izaac** [comment]
Confirmed this is working now with chart version `3.9.400.rc02`
