### ISSUE TITLE
Consolidate (base) images

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#31738]
* `rancher/rancher` and `rancher/rancher-agent` or on `ubuntu:18.04`
* Most of the logging/alert images are on `ubuntu:16.04`
* Some tools containers are on `nginx-alpine`
* `rancher/kube-api-auth` use `ubuntu:16.04`

Would be good to consolidate to one base image. In 1.6 we have server-base/agent-base, maybe a single base image for ourselves would help, to also include common tools (but not the whole world in binaries).

**Comment by sirredbeard** [comment]
This was proposed and well-received in DAR. This would also likely benefit our CVE scanning/reporting process. The current suggestion is UBI for now, SLES micro later.

**Comment by snasovich** [comment]
`rancher/rancher` and `rancher/rancher-agent` are moved to SLE BCI per https://github.com/rancher/rancher/issues/33127

**Comment by cbron** [comment]
This has been completed in rancher/agent/kube-api-auth. Closing.
