### ISSUE TITLE
rancher-windows-exporter is available in feature charts for a windows cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31740]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On 2.5-head, commit id: `ff68b3a`
- Deploy a windows cluster
- Go to Dashboard --> Apps and Market place --> Charts --> `rancher-windows-exporter` is available
<img width="1241" alt="Screen Shot 2021-03-17 at 3 12 40 PM" src="https://user-images.githubusercontent.com/26032343/111547858-0b737880-8737-11eb-9f38-192a228ad341.png">

**Expected Result:**
`rancher-windows-exporter` should not be available

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): On 2.5-head, commit id: `ff68b3a`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): windows custom cluster
- Kubernetes version (use `kubectl version`):

```
any
```

**Comment by sowmyav27** [comment]
PR: https://github.com/rancher/charts/pull/1042

**Comment by aiyengar2** [comment]
Switched from https://github.com/rancher/charts/pull/1042 to https://github.com/rancher/charts/pull/1059 to avoid blocking this issue on the Dashboards

**Comment by thehejik** [comment]
The `windows-exporter` app disappeared from Apps & Marketplace menu on dev-v2.5 helm chart repo. 

Closing, thanks.
