### ISSUE TITLE
Error in driver during machine creation: No suitable endpoint could be found in the service catalog

### ISSUE THREAD

**Issue by amoon78** [rancher/rancher#31741]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
When I tried to provision openstack downstream cluster with openstack node template, it returns authentication failed error on creating machine. 
But, i can successfully create machine by openstack api with same credential so, i'm sure it's not related to credential issue. 
Could you please let me know where i can see full logs for node driver provisioning to investigate more? 
And, can i know what nova api url is used from rancher to provision openstack node?
is it http://nova-server-url:8774/compute/v2.1/ or, just http://nova-server-url:8774/v2.1/ ?

**Result:**
`Error creating machine: Error in driver during machine creation: Authentication failed`
or, 
`Error creating machine: Error in driver during machine creation: No suitable endpoint could be found in the service catalog.`

**Other details that may be helpful:**
Our nova api url format is http://nova-server-url:8774/v2.1/project-id/~

**Environment information**
- kubernetes_version: v1.19.7-rancher1-1
- Rancher version: 2.5.6
- Installation option: gke cluster (HA)
- OpenStack nova version: rocky

**Comment by amoon78** [comment]
is there any way to see payload for creating openstack node? 
I tested with more node template option and now, i got No suitable endpoint error instead of auth fail. 
`Error creating machine: Error in driver during machine creation: No suitable endpoint could be found in the service catalog.`
I feel like there are something missing in openstack nova driver so, full params didn't pass to api. 
The reason why i think is, it works with single openstack region but, with multi-region, it fails. 
So, i suspect there are something missing to pass region.

**Comment by planetxpress** [comment]
Having the same problem with instance creation using an OpenStack node template in a multi-region environment.

We know that rancher is successfully authenticating and passing our template variables in all the previous calls, as we are locating the network, flavor, and image IDs. Also we confirm the key pair is successfully created in Nova in the region we expect it to be created in.

However I would like to know what API call Rancher is making and with what payload when it receives a `No suitable endpoint could be found in the service catalog` error on what I assume is the instance creation. 

```
2021/03/19 21:18:38 [INFO] [node-controller-rancher-machine] Running pre-create checks...
2021/03/19 21:18:38 [INFO] [node-controller-rancher-machine] Creating machine...
2021/03/19 21:18:38 [INFO] [node-controller-rancher-machine] (asdfasdf1) Authenticating... map[ApplicationCredentialId: ApplicationCredentialName: AuthUrl:https://keystone:5000/v3 CaCert:/4LDEDPYJT5/cacert DomainId: DomainName:staging Insecure:true TenantDomainID: TenantDomainName:staging
 TenantID: TenantName:sandbox UserDomainID: UserDomainName:staging UserId: Username:testbot]
2021/03/19 21:18:39 [INFO] [node-controller-rancher-machine] (asdfasdf1) Found network id using its name map[ID:376c9b48-33a1-44f0-b9f5-50aaaad0ce74 Name:sandbox-net]
2021/03/19 21:18:39 [INFO] [node-controller-rancher-machine] (asdfasdf1) Found flavor id using its name map[ID:cae9cdf4-1ac2-42b3-a7ae-c9f989c260fc Name:c4.xlarge]
2021/03/19 21:18:39 [INFO] [node-controller-rancher-machine] (asdfasdf1) Found image id using its name map[ID:f04b44f9-5f23-4b2b-8f23-6f2ca69fe770 Name:centos7-latest]
2021/03/19 21:18:39 [INFO] [node-controller-rancher-machine] (asdfasdf1) Creating Key Pair... map[Name:asdfasdf1-046ba1ceabb044b1848997f376921c21ffbc40b6484b5b2d0becb847c7304406]
2021/03/19 21:18:39 [INFO] [node-controller-rancher-machine] (asdfasdf1) Creating OpenStack instance... map[FlavorId:cae9cdf4-1ac2-42b3-a7ae-c9f989c260fc ImageId:f04b44f9-5f23-4b2b-8f23-6f2ca69fe770]
2021/03/19 21:18:41 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2021/03/19 21:18:41 [INFO] [node-controller-rancher-machine]
2021/03/19 21:18:41 [INFO] Generating and uploading node config asdfasdf1
2021/03/19 21:18:41 [DEBUG] [GenericEncryptedStore]: set secret called for mc-m-6w5rq
2021/03/19 21:18:41 [DEBUG] [GenericEncryptedStore]: updating secret mc-m-6w5rq
2021/03/19 21:18:41 [DEBUG] getNodeTemplate parsed [cattle-global-nt:nt-6fm2s] to ns: [cattle-global-nt] and n: [nt-6fm2s]
2021/03/19 21:18:41 [ERROR] [node] enqueing node pool c-xb6b6:np-x6q4g
2021/03/19 21:18:41 [DEBUG] Cleaning up [/opt/jail/c-xb6b6/management-state/node/nodes/asdfasdf1]
2021/03/19 21:18:42 [DEBUG] [nodepool] bad node found: m-6w5rq
2021/03/19 21:18:42 [ERROR] error syncing 'c-xb6b6/m-6w5rq': handler node-controller: Error creating machine: Error in driver during machine creation: No suitable endpoint could be found in the service catalog., requeuing
```

**Comment by vincent99** [comment]
https://github.com/rancher/machine/blob/master/drivers/openstack/openstack.go#L512

If the last thing you're setting is the ssh key, then probably the volume create...

**Comment by planetxpress** [comment]
A volume create would be a problem, as we don't have Cinder in this environment. However based on our config, I don't believe we should be hitting any logic that would make a request from the volume service, or am I mistaken?

```
"openstackConfig": {
  "activeTimeout": "200",
  "applicationCredentialId": "",
  "applicationCredentialName": "",
  "applicationCredentialSecret": "",
  "authUrl": "https://keystone:5000/v3",
  "availabilityZone": "",
  "bootFromVolume": false,
  "cacert": "",
  "configDrive": false,
  "domainId": "",
  "domainName": "staging",
  "endpointType": "",
  "flavorId": "",
  "flavorName": "c4.xlarge",
  "floatingipPool": "",
  "imageId": "",
  "imageName": "centos7-latest",
  "insecure": false,
  "ipVersion": "4",
  "keypairName": "",
  "netId": "",
  "netName": "sandbox-net",
  "novaNetwork": false,
  "region": "lax1a",
  "secGroups": "",
  "sshPort": "22",
  "sshUser": "root",
  "tenantDomainId": "",
  "tenantDomainName": "staging",
  "tenantId": "",
  "tenantName": "sandbox",
  "userDataFile": "",
  "userDomainId": "",
  "userDomainName": "staging",
  "userId": "",
  "username": "testbot",
  "volumeDevicePath": "",
  "volumeId": "",
  "volumeName": "",
  "volumeSize": "0",
  "volumeType": ""
},
```

**Comment by planetxpress** [comment]
Perhaps this may be my issue here https://github.com/rancher/machine/blob/master/drivers/openstack/openstack.go#L851-L852

The block storage client seems to be getting initialized in createMachine even though the machine is not using block storage.

**Comment by amoon78** [comment]
thanks all! i'm pretty sure my issue is related to storage now. I just checked  docker/machine repository and can't see initBlockStorage step in createMachine()
https://github.com/docker/machine/blob/master/drivers/openstack/openstack.go#L751-L766

I'm going to close this issue with this bug type issue ticket. 
https://github.com/rancher/rancher/issues/31787
