### ISSUE TITLE
rancher-images.txt is missing ToolsSystemImages

### ISSUE THREAD

**Issue by adianas** [rancher/rancher#31758]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Explanation:**
rancher-images.txt doesn't contain the images found in ToolsSystemImages: https://github.com/rancher/rancher/blob/v2.5.7/pkg/apis/management.cattle.io/v3/tools_system_images.go

**Result:**
Not all the necessary images for running Rancher are found in rancher-images.txt

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): HA Air-gapped

gz#15829

**Comment by dramich** [comment]
The images listed in [tools_system_images.go](https://github.com/rancher/rancher/blob/v2.5.7/pkg/apis/management.cattle.io/v3/tools_system_images.go) are mirrored through https://github.com/rancher/rke/blob/master/types/image/mirror.go and exist in dockerhub but pipeline always uses the original image that is in the tools_system_images file. This only applies to images that aren't ranchers and require being mirrored. 

The [images-list](https://github.com/rancher/image-mirror/blob/master/images-list) needs to be updated to include the three non-rancher images from tools_system_images and then tools_system_images needs to be updated to use the mirrored version of the image. This work is being done as part of a larger effort to consolidate all the image mirrors. 

https://github.com/rancher/rancher/issues/31598

**Comment by rmweir** [comment]
The images in that file are being translated to their rancher mirrored counterparts using the mirror function from https://github.com/rancher/rke/blob/master/types/image/mirror.go, which you can see as m() here: https://github.com/rancher/rancher/blob/v2.5.7/pkg/apis/management.cattle.io/v3/tools_system_images.go#L19. The rancher version for all of these are in rancher-images.txt. We plan on replacing these lines with hardcoded values and the mirrored images will be prefixed with `rancher/mirrored-`; our intention currently is to include this in a coming 2.5 release and beyond. For now here are the rancher equivalents of each of the mirrored images that are included in rancher-images.txt for v2.5.7:
```
jenkins/jnlp-slave:3.35-4 rancher/jenkins-jnlp-slave:3.35-4
plugins/docker:18.09 rancher/plugins-docker:18.09
minio/minio:RELEASE.2020-07-13T18-09-56Z rancher/minio-minio:RELEASE.2020-07-13T18-09-56Z
```

**Comment by rmweir** [comment]
The file has been changed to use new mirrored images with "mirrored-" prefix and now contains hard coded values which should make it easier to understand.
**Testing:**
Confirm that pipelines work in an airgap setup. This will achieve two things: it will validate that the new mirrored images work and that the rancher-images.txt does indeed contain the images need to run pipelines in airgap.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.8-rc6

* Checked v2.5.8-rc6 `rancher-images.txt` for all images listed in https://github.com/rancher/rancher/blob/v2.5.7/pkg/apis/management.cattle.io/v3/tools_system_images.go#L19
* Created a v2.5.8-rc6 airgap setup
* Added an airgapped custom cluster
* Created a Gitlab instance accessible to the airgapped nodes and populated with an example pipeline project - https://github.com/bmdepesa/pipeline-example
* Authorized the Gitlab repo and selected the example pipeline
* Executed
* Pipeline run was successful and all non-Rancher images were using the mirrored images

![Screen Shot 2021-04-21 at 3 39 52 PM](https://user-images.githubusercontent.com/21316915/115629808-e505a780-a2b7-11eb-9608-e925512948b0.png)
![Screen Shot 2021-04-21 at 3 31 41 PM](https://user-images.githubusercontent.com/21316915/115629816-e6cf6b00-a2b7-11eb-9454-c37c45467a2a.png)
