### ISSUE TITLE
[2.5.7] Deleting a node pool does not delete all of the backend nodes

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#31765]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- create a new infrastructure provider cluster with 2 node pools
- first node pool with 3x controlplane 
- second node pool with 3x worker
- delete second node pool 

**Result:**
the node pool will be deleted but only the first node will be deleted from the node pool. There will be 2/3 worker nodes left alive in the backend

**Other details that may be helpful:**
The issue does not exist in 2.5.5 and is specific to 2.5.7

**Environment information**
- Rancher version: v2.5.7

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.5.8**

Steps:
- Deploy an RKE DO/AWS cluster with 1 nodepool with etcd/control plane roles. and 2 worker nodepools with 2/3 nodes.
- When the cluster is up and when the nodes are Active, delete one of the worker nodepools
- An error will be seen on One of the worker nodes in the nodepool , and this worker node will NOT be deleted from DO in the backend. The other worker. nodes get deleted
- Error in the rancher logs:
```
2021/03/19 22:42:44 [DEBUG] [nodepool] attempting to delete node m-l6f2h
2021/03/19 22:42:44 [ERROR] error syncing 'c-l6t2j/np-4pkxw': handler nodepool-provisioner: nodepools.management.cattle.io "np-4pkxw" not found, requeuing
2021/03/19 22:42:44 [DEBUG] Failed to get node for machine [m-4dn7d], preparing to delete
2021/03/19 22:42:44 [INFO] Deleted cluster node m-4dn7d [sowmya-worker-3]
2021/03/19 22:42:44 [DEBUG] Failed to get node for machine [m-4dn7d], preparing to delete
2021/03/19 22:42:44 [DEBUG] Failed to get node for machine [m-l6f2h], preparing to delete
2021/03/19 22:42:44 [INFO] Deleted cluster node m-4dn7d [sowmya-worker-3]
2021/03/19 22:42:44 [DEBUG] Deleting v1.node for [sowmya-worker-3] node
2021/03/19 22:42:44 [ERROR] error syncing 'c-l6t2j/_machine_all_': handler machinesSyncer: Failed to delete machine [m-l6f2h]: nodes.management.cattle.io "m-l6f2h" not found, requeuing
2021/03/19 22:42:44 [DEBUG] Deleting v1.node for [sowmya-worker-2] node
```

**On 2.5.8-rc1**
- Deploy an RKE DO/AWS cluster with 1 nodepool with etcd/control plane roles. and 2 worker nodepools with 2/3 nodes.
- When the cluster is up and when the nodes are Active, delete one of the worker nodepools
- All the worker nodes in the nodepool get deleted from Rancher and from the backend. 
- Deleting the cluster deletes all the nodes from backend.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `b2a34d7` and on master-head commit id: `f63b2758`**

- Deploy an RKE DO/AWS cluster with 1 nodepool with etcd/control plane roles. and 2 worker nodepools with 2/3 nodes.
- When the cluster is up and when the nodes are Active, delete one of the worker nodepools
- All the worker nodes in the nodepool get deleted from Rancher and from the backend.
- Deleting the cluster deletes all the nodes from backend.
