### ISSUE TITLE
KEv2/GKE: missing parity with KEv1 fields

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#31764]
**What kind of request is this (question/bug/enhancement/feature request):** feature request

The GKE operator CRD is missing fields that the kontainer-engine GKE driver had:

`Locations` - "Specify default node locations" - additional zones to increase node pool availability
`MaintenancePolicy.Window` - cluster-level maintenance policy

We should add these to maintain feature parity with the old driver.

**Comment by cmurphy** [comment]
How to test:

On GKEClusterConfigSpec set

```
locations: []
```

or 

```
locations:
- <zone>
- <another zone>
- etc
```

On GKEClusterConfigSpec set

```
maintenanceWindow: ""
```

or

```
maintenanceWindow: <time in HH:MM format>
```

**Comment by prabalsharma** [comment]
@cmurphy can you please elaborate on this feature, how it is different for what we already have in GKE operator?
I am looking at my rc4 clusterConfig and I can see that I had tested this feature in gke operator rc4: 
```
  locations:
  - us-west1-a
  # - us-west1-b
  # - us-west1-c
  maintenanceWindow: "00:00"
  ```

**Comment by prabalsharma** [comment]
Tested on master-1e1ed67329d6224e7a10f1c1a529eaff60ba48ea-head: rancher/gke-operator:v1.0.1
from api
```
  "region": "us-west1",
  "zone": "",
  "locations": [],
  "maintenanceWindow": ""
 ```
 
 will wait for Colleen's reply, before closing this (in case, I misunderstood something).

**Comment by cmurphy** [comment]
@prabalsharma this is just about testing those two fields, so this can be closed.
