### ISSUE TITLE
Scale down does not delete the node from the backend - DO

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31770]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy an RKE cluster - etcd/control plane - 3 nodes and 2 worker nodes pools wit 2/3 nodes
- "Scale Down" on a  worker node in a nodepool.
- The nodes get removed from the Rancher UI
- But it does not get deleted from the backend in DO console

**Note:**
Hit this issue once and was not able to reproduce this

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.6
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO RKE
- Kubernetes version (use `kubectl version`):

```
1.20 (Any)
```

**Comment by luthermonson** [comment]
@sowmyav27 tested this with all the fixes going into 2.5.8 including the fixes coming for https://github.com/rancher/rancher/issues/31507 and this scenario worked in my environment. I'm going to get everything merged in and this to test as it should be solved. if you see this again please leave the environment up and let me investigate. (note, leaving same message on the other DO nodepool ticket)

**Comment by sowmyav27** [comment]
**On 2.5.8-rc4 and master-head - commit id: `1c3629`**

- Tried the steps as mentioned in the original issue's description
- Was not able to reproduce this issue.


Closing this. If this issue is seen, will open a new one.
