### ISSUE TITLE
Node stuck in unavailable state but the node pool is seen deleted

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31772]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy an RKE DO cluster, with 1 nodepool - all roles, 2 nodepools with worker roles
- Wait for the cluster and the nodes to come up
- In one of the worker nodepool, scale up the worker nodes.
- When the node gets the IP address and is in the registering state
- Delete this noodepool
- The worker node is seen stuck in Unavalable state, and the nodepool is seen deleted.
- However the node has been deleted in DO in the backend. 
- The other nodepools do not have the "Scale Up" and scale Down options
<img width="1296" alt="Screen Shot 2021-03-19 at 11 25 29 PM" src="https://user-images.githubusercontent.com/26032343/111909534-e9ba1000-8a1a-11eb-9023-4c9c35e712b4.png">

**Other details that may be helpful:**
- On 2.5.5, the node is seen stuck in Removing state, for sometime but eventually getting removed from Rancher and the backend.
- Not always reprooducable

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8-rc1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE DO
- Kubernetes version (use `kubectl version`):

```
1.20 (Any)
```

**Comment by luthermonson** [comment]
@sowmyav27 tested this with all the fixes going into 2.5.8 including the fixes coming for https://github.com/rancher/rancher/issues/31507 and this scenario worked in my environment. I'm going to get everything merged in and this to test as it should be solved. if you see this again please leave the environment up and let me investigate. (note, leaving same message on the other DO nodepool ticket)

**Comment by sowmyav27** [comment]
**On 2.5.8-rc4 and master-head - commit id: `1c3629`**

- Tried the steps as mentioned here - https://github.com/rancher/rancher/issues/31772#issue-837099752.
- Was not able to reproduce this issue.


Closing this. If this issue is seen, will open a new one.
