### ISSUE TITLE
[v2.5] KDM release: k8s march patches

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#31782]
This is a KDM release for new k8s versions: v1.18.17, v1.19.9 and v1.20.5. It's not going out with any Rancher release, it's a KDM + RKE release only.

- There are existing k8s versions in `dev-v2.5` that haven't been released (absent in `release-v2.5`), so the same versions can be updated. Following versions need to be updated with their compatible rancher server versions: 

| update [version](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/k8s_rke_system_images.go#L3590) from | to | update [rancher version constraints]( https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/rke/k8s_version_info.go#L278) 
| --------------- | --------------- | -----------| 
| v1.20.4-rancher1-2 | v1.20.5-rancher1-1 | 2.5.6+ | 
| v1.19.8-rancher1-2 | v1.19.9-rancher1-1 |  2.5.0+ | 
| v1.18.16-rancher1-2 | v1.18.17-rancher1-1 | 2.4.5+ |

- Following [system images](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/k8s_rke_system_images.go) need to be updated: 

| Name | Kubernetes Version |  Version |
| ------ | ------ | ------| 

- [Update constraints for all addon versions](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) so the new Kubernetes versions use the right template. Refer to the table below to confirm the template name. 

<details>
<summary> Confirm the versions for System Images and Addon templates are correct. Update this table if new versions get introduced. Click to view the full list. </summary>

| Name | Kubernetes Version |  Version | [Update constraints for addon versions](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) if required | 
| ------ | ------ | ------| ---- | 
| etcd |  v1.18.17 | v3.4.3-rancher1 | 
| etcd | v1.19.9 | v3.4.13-rancher1 | 
| etcd | v1.20.5 | v3.4.14-rancher1 | 
|  | 
| kube-dns |  v1.18.17 | v1.15.2 | kubeDnsv116
| kube-dns |  v1.19.9, v1.20.5 | v1.15.10 | kubeDnsv116 
|  | 
| core-dns| v1.18.17 | v1.6.9 | coreDnsv117
| core-dns| v1.19.9 | v1.7.0 | coreDnsv117
| core-dns| v1.20.5 | v1.8.0 | coreDnsv117 
|  | 
| flannel | v1.18.17 | v0.12.0| flannelv116
| flannel | v1.19.9, v1.20.5 | v0.13.0| flannelv116 
|  | 
| calico, canal |  v1.18.17 | v3.13.4 | canalv117PrivilegedCalico3134, calicov117Privileged 
| calico, canal | v1.19.9 | v3.16.5 | canalv3165, calicov3165
| calico, canal | v1.20.5 | v3.7.2 |  canalv3171, calicov3171
|  | 
| weave | v1.18.17 | v2.6.4 | weavev116
| weave | v1.19.9 | v2.7.0 | weavev116
| weave | v1.20.5 | v2.8.1 | weavev120
|  | 
| aci | all | 5.1.1.0.1ae238a | aciv500 
|  | 
| metrics-server | v1.18.17, v1.19.9 | v0.3.6 | metricsServerv18
| metrics-server | v1.20.5 | v0.4.1 | metricsServerv120
|  | 
| podInfra | v1.18.17 | 3.1 | 
| podInfra | v1.19.9, v1.20.5 | 3.2 | 
|  | 
| node local |  v1.18.17 | 1.15.7| nodelocalv115
| node local | v1.19.9, v1.20.5 | 1.15.13 | nodelocalv115
|  | 
| rancher forks | 
| dns-autoscaler | v1.18.17 | v1.7.1 | 
| dns-autoscaler | v1.19.9, v1.20.5 | v1.8.1 | 
|  | 
| flannel-cni | all | v0.3.0-rancher6 | 
|  | 
| ingress | v1.18.17, v1.19.9 | nginx-0.35.0-rancher2 | nginxIngressV11512
| ingress | v1.20.5 | nginx-0.43.0-rancher1 | nginxIngressV11512
|  | 
| ingress-backend |  all | 1.5-rancher1 | 
|  | 
| rke-tools | all | v0.1.71 | 
| | 
| windowsPodInfra | all | v0.1.6 | 
</details>

**Comment by anupama2501** [comment]
on 2.5.7 verified:

- kdm job pointing to release-v2.5on k8s v1.20.4-rancher1-1,v1.19.8-rancher1-1,v1.18.16-rancher1-1 on all network providers
- Ran pre-upgrade checks 
- Changed the rke-metadata-config to point to dev-v2.5
- Verified newer k8s versions on the clusters
- Upgraded the k8s to the next version  v1.20.5-rancher1-1, v1.19.9-rancher1-1, v1.18.17-rancher1-1 on all network providers
- Ran post upgrade checks

All of the scenarios have passed

**Comment by sowmyav27** [comment]
**On 2.5.7**

- KDM pointing to dev-v2.5, KDM job (Cluster creation succeeds for 1.20, 1.19, 18 k8s versions with all network provider) and Network related checks on these clusters worked fine.
- Validation checks on the Canal network provider clusters looked good. (Automation)

**Comment by slickwarren** [comment]
2.5.3 pointing to dev-v2.5

KDM job (Cluster creation succeeds for k8s versions -  All k8s with all network provider - 1.19, 1.18) and run network related test cases- 2.5.3 pointing to dev-v2.5 
- Validation has passed for all network providers on v1.18.17-rancher1-1 and v1.19.9-rancher1-1
