### ISSUE TITLE
[v2.4] KDM release: k8s march patches

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#31781]
This is a KDM release for new k8s versions: v1.18.17. It's not going out with any Rancher release, it's a KDM + RKE release only. 

- All existing k8s versions in `dev-v2.4` have been released (are present in `release-v2.4`) so we need to introduce new k8s versions. To introduce a new k8s version, basecopy the latest existing version in a separate commit, followed by another commit to update what's changed. Following versions need to be created with their compatible rancher server versions: 

| basecopy [version](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/k8s_rke_system_images.go#L3590) from | create | set [rancher version constraints]( https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/rke/k8s_version_info.go#L278) 
| --------------- | --------------- | -----------| 
| v1.18.16-rancher1-1 | v1.18.17-rancher1-1 | 2.4.5+ | 

- Following [system images](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/rke/k8s_rke_system_images.go) need to be updated: 

| Name | Kubernetes Version |  Version |
| ------ | ------ | ------| 

- Add docker version if a new docker version was introduced in [docker info](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/rke/k8s_docker_info.go) 

| Kubernetes Version | Docker Version |
| ------ | ------| 

- [Update constraints for all addon versions](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) so the new Kubernetes versions use the right template. Refer to the table below to confirm the template name. 

<details>
<summary> Confirm the versions for System Images and Addon templates are correct. Update this table if new versions get introduced. Click to view the full list. </summary>

| Name | Kubernetes Version |  Version | [Update constraints for addon versions](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) if required | 
| ------ | ------ | ------| ---- | 
| etcd |  v1.18.17 | v3.4.3 | 
|  | 
| kube-dns | v1.18.17 | v1.15.2 | kubeDnsv116
|  | 
| core-dns| v1.18.17| v1.6.9 | coreDnsv117
|  | 
| flannel | v1.18.17 | v0.12.0| flannelv116
|  | 
| calico, canal |  v1.18.17 | v3.13.4 | canalv117PrivilegedCalico3134, calicov117Privileged 
|  | 
| weave | v1.18.17 | v2.6.4 | weavev116
|  | 
| aci | - | - | -  
|  | 
| metrics-server | v1.18.17| v0.3.6 | metricsServerv18
|  | 
| podInfra | v1.18.17| 3.1 | 
|  | 
| node local |  v1.18.17 | 1.15.7| nodelocalv115
|  | 
| rancher forks | 
| dns-autoscaler | v1.18.17| v1.7.1 | 
|  | 
| flannel-cni | all | v0.3.0-rancher6 | 
|  | 
| ingress | v1.18.17 | nginx-0.35.0-rancher2 | nginxIngressV11512
|  | 
| ingress-backend |  all | 1.5-rancher1 | 
|  | 
| rke-tools | all | v0.1.71 | 
| | 
| windowsPodInfra |  v1.18.17 | v0.1.6 | 
</details>

**Comment by anupama2501** [comment]
Version v2.4.5 min version checks

metadata config pointing to dev-v2.4
KDM job on the k8s version v1.18.17-rancher1-1 on all the network [calico,weave,flannel,canal] for cluster creation
All the clusters have come up with the k8s version v1.18.17-rancher1-1 on all networks

**Comment by slickwarren** [comment]
v2.4.15 Fresh Install checks 
* 2.4.15 - pointing to dev-v2.4 (fresh install checks) 

* KDM job (Cluster creation succeeds for all k8s versions with all network provider) and run network related test cases 
* run Validation tests for all the Canal clusters 
all clusters came up with k8s v1.18.17-rancher1-1 with each provider. validation tests passed

**Comment by slickwarren** [comment]
v2.4.15 upgrade tests: 
On 2.4.15 KDM job pointing to release-v2.4:

* Run pre upgrade checks

* Upgrade dev-v2.4

* Upgrade K8s versions to new versions

* Run post upgrade checks

all validation steps passed with each provider, each using v1.18.17-rancher1-1

**Comment by slickwarren** [comment]
2.5.3 pointing to dev-v2.5

KDM job (Cluster creation succeeds for k8s versions -  All k8s with all network provider - 1.19, 1.18) and run network related test cases- 2.5.3 pointing to dev-v2.5 
- Validation has passed for all network providers on v1.18.17-rancher1-1 and v1.19.9-rancher1-1

**Comment by sowmyav27** [comment]
RKE checks using `v1.1.16-rc1` look good.
