### ISSUE TITLE
unable to use kubectl, x509: certificate is valid for 127.0.0.1, 172.17.0.2, not rancher server ip errors

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#31784]
Rancher server: v2.5.6 
Steps to Reproduce: Don't have the exact steps, history afaik: 
- Created a single node rancher setup 
- Created two DO clusters 
- Was able to use kubeconfig to kubectl and access local + 2 Do clusters 
- Left the setup for ~10days 
- kubeconfigs no longer work 

```
kshah$ kubectl --kubeconfig local get pods
Unable to connect to the server: x509: certificate is valid for 127.0.0.1, 172.17.0.2, not <rancher-ip>
```

Have the setup around, ping me for access and the logs.

**Comment by rawmind0** [comment]
The Rancher server is working fine now, accessing properly to the 2 DO clusters and the local. 

As the Rancher server is running as single node setup, the most probable reason for the issue would be that at some point the Rancher docker ip (172.17.0.2) has been updated (after a node reboot, or something like this). Now the Rancher docker ip is properly set and the access to the clusters seems working fine.
