### ISSUE TITLE
Purged containers still show up in other container's Details page

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3178]

**Comment by vincent99** [comment]
It seems we already do this?  https://github.com/rancher/ui/commit/500a33ffa3002a997fa8ac6165a887288fb50793

**Comment by tfiduccia** [comment]
Steps to reproduce original problem:
1.  Create a volume
2.  Create two container that each use the volume
3.  Delete one of the containers
In the other container's details page, the deleted container is still listed as sharing the volume

**Comment by tfiduccia** [comment]
Version - master 7/8
Verified fixed
