### ISSUE TITLE
V2 monitoring: prometheus operator's hostNetwork value defaults to true  on imported EKS resulting in port conflicts

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#31786]
`prometheusOperator.hostNetwork` is being set to true in the yaml when enabling V2 monitoring on imported EKS clusters. However, it's normal set to false in the values.yaml:

```
# Required for use in managed kubernetes clusters (such as AWS EKS) with custom CNI (such as calico),
# because control-plane managed by AWS cannot communicate with pods' IP CIDR and admission webhooks are not working
##
hostNetwork: false
```

This results in the rancher-monitoring-operator not being able to start due to something else already listening on 8080 on the nodes. It's pretty rare (I'm yet to see it) for users to utilize a custom CNI (per the values comments as being the reason why) so perhaps not calculating this to true is a better default here.

gz#15838
gz#15787

**Comment by aiyengar2** [comment]
@bentastic27 thank you for calling this out! Since this value is overridden by the Rancher Dashboard UI, I've created an issue in https://github.com/rancher/dashboard/issues/2573 to address this.

Will close this issue out in favor of resolution on the rancher/dashboard issue.
