### ISSUE TITLE
PLEG is not healthy K8 1.20.4/Ubuntu 20.04

### ISSUE THREAD

**Issue by Moumouls** [rancher/rancher#31793]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Install Rancher (2.5.7)
- Launch a RKE cluster with Kubernetes 1.20.4
- Use Ubuntu 20.04 on Nodes
- Deploy many statefulsets (+20) and some cron jobs each minutes

**Result:**
Nodes start to fall into PLEG error.

**Other details that may be helpful:**
After a downgrade (full reinstall) to K8 1.18.16 and Ubuntu 18.04 everything works correctly.
This issue seems reproducible since i've done a full reinstall twice with K8 1.20.4 and Ubuntu 20.04 and the issue still persist.
Also i see the issue on my 3 nodes (all nodes have Ubuntu 20.04)

Node flapping seems to come from Statefulset and CronJobs.
This command is useful to find the container that hangs on `docker inspect`: `docker ps -a | tr -s " " | cut -d " " -f1 | xargs -Iarg sh -c 'echo arg; docker inspect arg> /dev/null'`

**Environment information**
- Rancher version 2.5.7:
- Installation option (single install/HA): HA, Digital Ocean Kubernetes

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom (Launched by Rancher)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal , 8 CPU, 32 GB RAM on each node, 3 nodes, OVH VPS provider
- Kubernetes version (use `kubectl version`): 1.20.4

- Docker version (use `docker version`): Issue is reproducible on 19.03 and 20.10 (installed via Rancher scripts), i think that docker is not involved here in the issue.

Related comment on kubernetes repo: https://github.com/kubernetes/kubernetes/issues/45419#issuecomment-803358917

Note: I'm sorry but I no longer have access to the mentioned cluster so i can't provide more information/logs.

**Comment by angeloudy** [comment]
We just hit exactly the same issue on Rancher 2.5.2.
We are running aprox 1000 pods.
The cluster has been running without issue for months.
What I did yesterday was replacing the worker nodes with ebs_encrypted volumes.
I simply changed `encrypt_ebs_volume` to `true` in my node-template and deleted old nodes one by one.

**Comment by ralf-berger** [comment]
Observing the same issue in a small cluster, several hosts are constantly switching to not ready.

**Comment by angeloudy** [comment]
I have just hit this issue again on another cluster.
What I have noticed is that the PLEG issue only happen on m5.xlarge instances, never happened on m5.large instances, probably because xlarge instances are running more pods.
As a workaround, I force rescheduled some pods on xlarge instances and added `docker restart kubelet` to crontab.

**Comment by herrenP** [comment]
Happens to us too. Rancher 2.5.5, Ubuntu 20.04. Seen the issue on nodes running ~100 to ~200 pods with maxPods set to 250. Restarting docker or rebooting the nodes does not help. They return to this state after a short while.

**Comment by Moumouls** [comment]
@ralf-berger @angeloudy @herrenP what is you K8 , Node OS versions, Docker version, Provider ? It could be really helpful to identify the final source (since the PLEG error source is commonly hard to identify).

**Comment by herrenP** [comment]
- Kubernetes: 1.19.8-rancher1-1
- Node OS: Ubuntu 20.04
- Docker: 20.10.3 (also tried 20.10.5 at some point)
- Provider: EC2 on AWS

**Comment by Moumouls** [comment]
@herrenP did you try to deploy new nodes with Ubuntu 18 ?

Also since it seems reproducible in your env, could you run `docker ps -a | tr -s " " | cut -d " " -f1 | xargs -Iarg sh -c 'echo arg; docker inspect arg> /dev/null'` on the Node stucked to identify the container that hangs ?

The command will hang on the container id that block the PLEG process. Then search the container name with `docker ps`

If i remember in my case it was a Rancher/pause container.

**Comment by ralf-berger** [comment]
> what is you K8 , Node OS versions, Docker version, Provider?

* Kubernetes: v1.20.4-rancher1-1
* Docker: 20.10.5
* OS: Ubuntu 20.04.2 LTS
* Provider: bare-metal and Hyper-V (affected equally)
* other cluster config: Canal with network isolation, PSP enabled, using Longhorn storage

Rancher is running as stand-alone container, all nodes are running control-plane/etcd plus workloads.

**Comment by herrenP** [comment]
> @herrenP did you try to deploy new nodes with Ubuntu 18 ?
> 
> Also since it seems reproducible in your env, could you run `docker ps -a | tr -s " " | cut -d " " -f1 | xargs -Iarg sh -c 'echo arg; docker inspect arg> /dev/null'` on stucked nodes to identify the container that hangs ?
> 
> The command will hang on the container id that block the PLEG process. Then search the container name with `docker ps`
> 
> If i remember in my case it was a Rancher/pause container.

We tried that command earlier today and in all cases it was the Rancher/pause container.

**Comment by Moumouls** [comment]
Okay it seems that we found the final source of the issue, sadly from my experience the only way i found to fix this issue is to create a new cluster with a downgraded K8 version and a good old Ubuntu 18.04.

> After a downgrade (full reinstall) to K8 1.18.16 and Ubuntu 18.04 everything works correctly.

**Comment by angeloudy** [comment]
Looks like related to this one [here](https://github.com/moby/moby/issues/40817)

**Comment by angeloudy** [comment]
@Moumouls What version of docker you are running after you downgraded to Ubuntu 18.04? We are running k8s 1.19.4, docker 18.9.9, Ubuntu 16.04.

**Comment by Moumouls** [comment]
@angeloudy 19.03 seems okay on ubuntu 18.04

**Comment by angeloudy** [comment]
I upgraded docker to 19.3 and the issue is now gone.

**Comment by raelix** [comment]
Same issue here, docker inspect hangs and PLEG on nodes. Reproducible on:
Docker Server Version: 19.03.14
OS: CentOS Linux release 7.6.1810 (Core)  and 7.9
Rancher: 2.5.5 and 2.5.7 ( tried both)

PLEG appears most often on Kubernetes 1.20 and when the max number of pods per node is increased.

It's a critical issue and affects the stability of production systems. Are there any workaround suggested?

**Comment by Moumouls** [comment]
@raelix on my side the only workaround was to downgrade K8 version. Just for the issue documentation using the docker ps command provided above can you confirm that the container blocking the process is the rancher:pause one ?

**Comment by raelix** [comment]
Hello @Moumouls I'm already using K8s v1.18.14 with Docker 19.3.14,  the stuck container was coredns but seems to be every time a different container. This issue seems happens more frequently when there are more than 110 pods per node but still don't see any possible work-around

**Comment by Moumouls** [comment]
Your issue looks like i little bit different, does your node recover after some time or hang for ever ?

110 pods by node is already the max recommended by K8: https://kubernetes.io/docs/setup/best-practices/cluster-large/

May be you have resource issue then docker do not have any sufficient resource to handle the PLEG hook.

I don't know if you have a custom cluster, but did you try to increase memory/cpu on nodes, what kind of server do you have for your cluster ?

**Comment by raelix** [comment]
Hi @Moumouls I tried killing the runc pending command and the PLEG disappears but the ```Cluster health check failed: cluster agent is not ready``` is still there until I restart the node. 
They are bare-metal with at last 16 CPU and 64 GB RAM, when this happens I have still 30GB of RAM free and just 60% of CPU used.

I don't have more that 110 pods because I know about the limits but the issue seems to be present when the node comes to be too loaded of statefulset and PV (I use longhorn). 
Why docker should hangs on ```docker inspect``` command?  This sounds to be the bug mentioned by you

**Comment by herrenP** [comment]
> * Kubernetes: 1.19.8-rancher1-1
> * Node OS: Ubuntu 20.04
> * Docker: 20.10.3 (also tried 20.10.5 at some point)
> * Provider: EC2 on AWS

We worked around the PLEG issue by keeping the versions as seen in the quote above but we then downgraded `containerd` from 1.4.4 to 1.4.3.

From "System information" in Rancher on one of our nodes:
```
Architecture | amd64
Docker Version | 20.10.3
Kernel Version | 5.4.0-1029-aws
Kubelet Version | v1.20.5
Kube Proxy Version | v1.20.5
Operating System Image | Ubuntu 20.04.1 LTS
Operating System | linux
```

From terminal on the same node:
```
someuser@somenode:~$ containerd --version
containerd containerd.io 1.4.3 269548fa27e0089a8b8278fc4fc781d7f65a939b
```

**Comment by terickson** [comment]
So we had this problem too.  We saw the issue using: 
```
Ubuntu:  20.04
Rancher: 2.5.6
Docker: 19.03
K8s: 1.20.5 and 1.19.9
``` 
On K8s 1.18.17 we were fine with the same Ubuntu, Rancher, and Docker.  We found that if we upgraded docker to the latest version in apt: docker 20.10.6 then K8s 1.20.5 was good so it looks like the latest version of docker fixes this issue.

Unfortunately that is not a configuration option in our current version of Rancher so if you use the UI after you build a node you will have to login to the node and apt upgrade docker.
In our case we are using Terraform to create our cluster and it uses the RKE template system.  If you are using this system, you can specify a script to install docker in fact rancher hosts their script for 19.03 here: https://releases.rancher.com/install-docker/19.03.sh
So we downloaded that script and modified it to use 20.10.6 and then linked our Terraform deployment to it so when we build workers they automatically get the correct version of docker.  Hope this helps.

**Comment by Moumouls** [comment]
Okay so it seems to be a runc issue combined may be to the 20+ Ubuntu version.
Here a link to the K8 discussion: https://github.com/kubernetes/kubernetes/issues/45419#issuecomment-819574343

A runc upgrade/downgrade should fix the issue or using Ubuntu 18.04 with runc rc 93 should works

Here the exact version that currently works on my side with 18.04:

```
runc version 1.0.0-rc93
commit: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
spec: 1.0.2-dev
go: go1.13.15
libseccomp: 2.4.3
```

**Comment by rdxmb** [comment]
Same problem here on a physical machine:

```
Operating System: Ubuntu 20.04.2 LTS
Kernel Version: 5.4.0-70-generic
Docker: 19.03.14
Cgroup Driver: cgroupfs
kubelet --version
Kubernetes v1.20.5
```

Is there any workaround without downgrading Ubuntu OS?

**Comment by rdxmb** [comment]
> I upgraded docker to 19.3 and the issue is now gone.

Is this really a fix? Sounds strange, if it is a runc issue ... . 

> We found that if we upgraded docker to the latest version in apt: docker 20.10.6 then K8s 1.20.5 was good so it looks like the latest version of docker fixes this issue.

same...

Is there already a runc issue on Github for that?

**Comment by terickson** [comment]
@rdxmb We upgraded to docker 20.10.6 which stabilized K8s and allowed us to stay on Ubuntu 20.04.

**Comment by rdxmb** [comment]
@terickson Thanks! (I've just realized that this is the rancher project...)

**Comment by rdxmb** [comment]
does not work in my case

`drei   NotReady                   <none>                 11d    v1.20.5   10.139.0.93   <none>        Ubuntu 20.04.2 LTS   5.4.0-70-generic   docker://20.10.6`

`Apr 27 20:28:23 drei kubelet[3420809]: E0427 20:28:23.488516 3420809 kubelet.go:1857] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 12m2.115005491s ago; threshold is 3m0s`

I will switch over to the kubernetes-issue ...

**Comment by angeloudy** [comment]
I am still having this issue. It happens when usage reaches around 50 pods per node regardless of CPU & memory usage. Then I have to add more nodes to avoid this issue.

**Comment by cocampbe** [comment]
I just ran into this issue after an upgrade to 1.19.6 of RKE on a downstream cluster. I run OL7.9, after updating the following.

docker -engine-19.03.11.ol-9.el7.x86_64
docker-cli-19.03.11.ol-9.el7.x86_64
runc-1.0.0-92.rc92.el7.x86_64

**Comment by cocampbe** [comment]
Just hit this issue again, but for a different reason. I figured I would share. We are using longhorn in our cluster. We added new nodes to the cluster and I forgot to install the iscsi and nfs client. After installing the necessary packages and rebooting,  the nodes are working as expected.

**Comment by minchieh-fay** [comment]
easy to solve it:
`not use runc-1.0.0-rc93`
upgrade or downgrade any version, but not 1.0.0-rc93
look: [deadlock of read from closed pip](https://github.com/opencontainers/runc/pull/2871/commits/7b3e0bcf2907c29e67eb49fb7ef6c03ea6456d45)
