### ISSUE TITLE
[BUG] namespaces are no longer being placed in appropriate projects and there is no advisory on this if it is expected behaviour

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#31797]
**What kind of request is this (question/bug/enhancement/feature request):**
Release notes should note when namespaces will not be in a project.  
At this time fleet namespaces, cattle-dashboards, rancher-operator-system and others from deployed apps are not being assigned a project by default.  For users relying on project-based RBAC this can cause security issues if they are not aware of this change.

Additionally, when users create namespaces using tools that are project unaware, the users do not see these namespaces as they are not in a project the users have access to. 

Can we please either put these in a default project until such a time as we can migrate to nested namespaces and/or update our release notes to say that a user should assign these namespaces to a project (assuming they are not using namespace or project-based network isolation).  It would help and prevent confusion if the release notes talked about these changes and the reason for them.

gz#15698

**Comment by gaby** [comment]
This issue has been going on for ages... They refuse to fix it. Every time I use Helm I have to manually create the namespace in Rancher so it doesnt end up without a Project.

**Comment by gaby** [comment]
👍🏻 Still a valid bug, been a bug for years now.

**Comment by vincent99** [comment]
Projects have never been been and will not be required and nothing has "changed".

The Explorer UI (which is the only one in 2.6) shows you all namespaces you have access to, regardless of what project they're in (or not).

**Comment by gaby** [comment]
Still valid

**Comment by gaby** [comment]
Still valid

**Comment by gaby** [comment]
Still valid

**Comment by gaby** [comment]
Still valid

**Comment by gaby** [comment]
🙃 valid
