### ISSUE TITLE
Passwords stored in clear text in MySQL

### ISSUE THREAD

**Issue by writeameer** [rancher/rancher#3180]
Hi there,

The settings table appears to store all passwords in the clear. If I try:

<pre>
select * from setting where name like '%password%'
</pre>

Account passwords are in the clear:

![capture](https://cloud.githubusercontent.com/assets/221149/12158482/6cb617e6-b52e-11e5-8dd0-50e265eee8f6.PNG)

Can we please encrypt such items ? Thanks.

Ameer Deen.

**Comment by kaos** [comment]
Related to #1269

**Comment by flaccid** [comment]
Just a bump here - making sure we cover this for GA :)

**Comment by vainkop** [comment]
The issue is still present in 1.6.10. I was able to retrieve private registry password as plaintext right from mysql db!

**Comment by deniseschannon** [comment]
With the release of Rancher 2.x, development on v1.6 is very limited.
