### ISSUE TITLE
[BUG] After upgrade to Logging v2, using the same index prefix broke log forwarding

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#31802]
Using index `rkemgmt` did not create an index though `rkemgmt-v2`, `rkemgmtnew`, and `rkemgmtz` did. Existing indices from v1 are all of the format `rkemgmt-YYYY-MM-DD` 
When moving from logging v1 to v2, we lost the ability to define the date in the index suffix and we believe there may be some relationship.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy logging v1 with the date format set to YYYY-MM-DD
2. Let run for a few days
3. Deactivate Logging, and enable Logging v2 with the suffix in the Date Format  ![image](https://user-images.githubusercontent.com/8906089/112388504-27ed5300-8ceb-11eb-8ffa-9bd9a6568aae.png)

**Result:**
No new indices will be created.
If you change the name and wait 5 min you should see the new index form without a date suffix
![image (7)](https://user-images.githubusercontent.com/8906089/112388736-84507280-8ceb-11eb-9b9e-16c3b00aeb85.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.7

**Comment by paynejacob** [comment]
This is supported in logging v2 but is not enabled by default.  You will need to configure your output to enable index rollover.

https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/elasticsearch/#elasticsearch-rollover_index
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/elasticsearch/#elasticsearch-index_date_pattern
https://github.com/uken/fluent-plugin-elasticsearch#rollover_index

**Comment by MKlimuszka** [comment]
@Tejeev , Jacob provided answers in the above comment. Can this be closed?
