### ISSUE TITLE
Page refresh too frequently 

### ISSUE THREAD

**Issue by roi3363** [rancher/rancher#31804]
Seems like the UI page refreshes every couple of seconds which leads to loss of work, so one has to work super fast before the page refreshes. It's pretty frustrating. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.5` UI: `v2.5.4` |

**Comment by vincent99** [comment]
The only time the UI reloads itself is if the WebSocket connection is connected, dropped for more than 30 seconds, and then reconnected.
