### ISSUE TITLE
after upgrade k3s version,rancher still display old version

### ISSUE THREAD

**Issue by lerit** [rancher/rancher#31816]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. rancher import k3s cluster (version 1.18.3)
2. update k3s version to 1.19.1
    reference:https://rancher.com/docs/k3s/latest/en/upgrades/basic/#manually-upgrade-k3s-using-the-binary
    2.1 replace k3s bin with new version
    2.2 restart new k3s

**Result:**
3. in rancher:
  3.1 first picture: display new k3s version
![1(1)](https://user-images.githubusercontent.com/4743467/112716783-72f1ab00-8f23-11eb-957e-a2c22e16a088.png)
 3.2 secode picture: when i click update cluster ,it still display old k3s version
![2(1)](https://user-images.githubusercontent.com/4743467/112716828-9f0d2c00-8f23-11eb-8314-c1aa4f41a283.png)
 so,when i click  save(change nothing),it throw error:
```
validation failed in API:cannot ugrade k3s cluster version from 1.19.1 to 1.18.3,new version must be highter
```
in k3sconfig,it still show old version,i think it is a bug

![3(11)](https://user-images.githubusercontent.com/4743467/112717741-89026a00-8f29-11eb-88d8-d98e15035430.png)

**after upgrade,rancher can manage k3s and k3s work fine,but if i want update cluster name or other  metainfo in the future,i will face this issue.**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
   2.4.4
- Installation option (single install/HA):
   single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3+k3s1", GitCommit:"96653e8d86b74a1f73eadf09d4edc44778c2f8dd", GitTreeState:"clean", BuildDate:"2020-06-01T16:47:11Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3+k3s1", GitCommit:"96653e8d86b74a1f73eadf09d4edc44778c2f8dd", GitTreeState:"clean", BuildDate:"2020-06-01T16:47:11Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by lerit** [comment]
need help

**Comment by lerit** [comment]
need help

**Comment by andrei-bamboi** [comment]
same issue here. didn't found an solution.
