### ISSUE TITLE
how to avoid create p-xxxxx  namespace 

### ISSUE THREAD

**Issue by yxxhero** [rancher/rancher#31819]
**What kind of request is this (question/bug/enhancement/feature request):**
Question: 
Why rancher create so many namespace: like p-xxxxx, How to avoid it. Thanks very much.

**Comment by yxxhero** [comment]
Anyone can help me?

**Comment by vincent99** [comment]
There is one for each project Rancher manages; there is no way to "avoid" them, they are how access control between projects is accomplished and this is part of the reason we suggest that the cluster  Rancher is installed on be dedicated to that.

**Comment by yxxhero** [comment]
@vincent99   thanks very much!
