### ISSUE TITLE
port link for ssl enabled lb points to http://<ipaddress>:<port> resulting in "No data received" error when accessing the link.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3182]
Server version - v0.52.0-rc4

Steps to reproduce the problem:
Create a LB service with ssl enabled listening ports and activate it.

From the "Applications" page , click on the link for "Ports:" field for this LB. 
User is taken to http://<ipaddress>:<port> resulting in "No data received" error.

Expected Behavior:
link should point to  https://<ipaddress>:<port>.

**Comment by tfiduccia** [comment]
version - master jan 07
Verified fixed
