### ISSUE TITLE
Rancher imported cluster tries to install fleet-agent with image not listed in rancher-images.txt

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rancher#31821]
**What kind of request is this (question/bug/enhancement/feature request):**

https://github.com/rancher/rancher/releases/download/v2.5.5/rancher-images.txt has rancher/fleet-agent:v0.3.2 but deployment of fleet-agent in downstream cluster wants fleet-agent:v0.3.3!

**Steps to reproduce (least amount of steps as possible):**

Deployed RKE2 1.20 and Rancher 2.5.5 in airgap environment.
Then imported an other downstream RKE2 cluster.

In the downstream cluster the fleet-agent has "ImagePullBackOff" and needs rancher/fleet-agent:v0.3.3 but that image is not in the on-premise registry as it is not listed in https://github.com/rancher/rancher/releases/download/v2.5.5/rancher-images.txt

**Result:**

Fleet-agent does not work as the pod does not start

**Other details that may be helpful:**

**Environment information**
- Rancher version v2.5.5
- Installation option (single install/HA) HA

**Cluster information**
- Cluster type: Imported RKE2 1.20
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): v1.20.4+rke2r1

Q: why does rancher v2.5.5 deploy a fleet agent with image 0.3.3 if this version is not included in the rancher-images.txt?

**Comment by Martin-Weiss** [comment]
Could it be that for some reason "fleet in the rancher-cluster does a self-update to v0.3.3"?

**Comment by vincent99** [comment]
Install 2.5.7 instead.. https://github.com/rancher/rancher/issues/30934

**Comment by Martin-Weiss** [comment]
> 
> 
> Install 2.5.7 instead.. #30934

Thanks! Just to understand this properly - this is a bug fixed in 2.5.7 and 2.5.5 is not supported anymore so 2.5.5 needs to be upgraded to get things fixed?

**Comment by vincent99** [comment]
It was fixed in 2.5.6, but you'd want 2.5.7 for other reasons.  2.5.5 is "supported", but if you want to not have this issue then you need A newer version where it was changed...

**Comment by Martin-Weiss** [comment]
Thanks - so if there will not be a backport I will move forward to 2.5.7, now
