### ISSUE TITLE
[Monitoring V2] Remove PrometheusRules translating windows-exporter to node-exporter

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#31831]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a Windows Cluster and install Monitoring V2 with Windows. 

Then navigate to PrometheusRules in the Monitoring Pane and click on the PrometheusRule titled `rancher-monitoring-windows-exporter-relabel-rules`. Take a look at the YAML view.

**Result:**

![Screen Shot 2021-03-29 at 2 24 09 PM](https://user-images.githubusercontent.com/13127443/112902058-6e9bce00-909a-11eb-83c4-824eb6c3f97a.png)

~All recording rules are based on wmi_ series, which are not exported by windows-exporter anymore. Those should be windows_ series.~

This PrometheusRule should no longer exist, as of https://github.com/rancher/rancher/issues/31742#issuecomment-811471567, since we are no longer taking the Monitoring V1 route of translating windows-exporter series to node-exporter series (the initial purpose of this PrometheusRule).

**Comment by aiyengar2** [comment]
Updated this issue based on https://github.com/rancher/rancher/issues/31742#issuecomment-811471567; this PrometheusRule should no longer exist.

**Comment by slickwarren** [comment]
confirmed on 2.5-head (2f2cfe6) using rancher-monitoring:9.4.204-rc09, rancher-monitoring-windows-exporter-relabel-rules no longer exists in prom rules

<img width="1766" alt="Screen Shot 2021-04-05 at 10 57 38 AM" src="https://user-images.githubusercontent.com/16691014/113607290-e4092080-95fd-11eb-8609-f0c51cf08529.png">
