### ISSUE TITLE
[Monitoring V2] Job label for windows-exporter should be windows-exporter, not kube-windows

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#31832]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a Windows Cluster and install Monitoring V2 with Windows. 

Then navigate to Prometheus's Graph UI and try to search any series prefixed with `windows_`

**Result:**

The `job` label is `rancher-monitoring-windows-exporter`. 

![Screen Shot 2021-03-29 at 2 32 48 PM](https://user-images.githubusercontent.com/13127443/112902876-a48d8200-909b-11eb-8474-1ac2255bbc1b.png)

Should be `windows-exporter`, similar to how we see node-exporter today.

![Screen Shot 2021-03-29 at 2 33 37 PM](https://user-images.githubusercontent.com/13127443/112902974-c25ae700-909b-11eb-879b-9dc5878953e9.png)

**Comment by kravciak** [comment]
I tested this on rancher v2.5.7 with dev-v2.5 chart, it the bug is fixed.
```...,job="windows-exporter",namespace=...```

![Screenshot from 2021-04-01 11-16-02](https://user-images.githubusercontent.com/538604/113272415-e3aa1600-92db-11eb-9d93-9d377975e12e.png)
