### ISSUE TITLE
KEv2 Operators (EKS/AKS/GKE) should get the same ca-additional as the Rancher deployment

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#31846]
There are some users that put Rancher behind a proxy that get SSL errors when creating EKS clusters in the eks-operator pod:

```
time="2021-03-10T14:40:21Z" level=error msg="error syncing 'cattle-global-data/c-clq89': handler eks-controller: error getting role: RequestError: send request failed\ncaused by: Post https://iam.amazonaws.com/: x509: certificate signed by unknown authority, requeuing"
time="2021-03-10T14:49:09Z" level=warning msg="cluster [c-clq89] never advanced to creating status, will not delete EKS cluster"
```

A fix is to mount the ca-addtional.pem from the [tls-ca-addtional](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/chart-options/#additional-trusted-cas) secret inside /etc/ssl/certs on the pod.

gz#15594
gz#15618

**Comment by bentastic27** [comment]
I made a PR for the EKS one, but perhaps the same changes need to apply in all of the provider kubernetes operators (AKS/GKS) as well.

**Comment by ranchersvet** [comment]
Even after the workaround is applied, the Rancher pods log this error:

2021/03/31 13:07:31 [ERROR] error syncing 'c-sh8jx/m-h6hg4': handler node-controller: unable to refresh config for node m-h6hg4: nodetemplates.management.cattle.io "nt-pg6jb" not found, requeuing
2021/03/31 13:10:00 [INFO] checking cluster [c-rz2lr] upstream state for changes
2021/03/31 13:10:00 [INFO] cluster [c-rz2lr] currently updating, skipping spec sync
2021/03/31 13:15:00 [INFO] checking cluster [c-rz2lr] upstream state for changes
2021/03/31 13:15:00 [INFO] cluster [c-rz2lr] currently updating, skipping spec sync
2021/03/31 13:19:13 [ERROR] error syncing 'c-rz2lr': handler eks-operator-controller: Post "https://XXXXXXXXXXXXXXXXXXXXXX.gr7.us-east-2.eks.amazonaws.com/api/v1/namespaces": x509: certificate signed by unknown authority, requeuing
2021/03/31 13:20:00 [INFO] checking cluster [c-rz2lr] upstream state for changes
2021/03/31 13:20:00 [INFO] cluster [c-rz2lr] currently updating, skipping spec sync
2021/03/31 13:24:00 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-rz2lr: ClusterUnavailable 503: cluster not found, requeuing

So I think at some point, the code is not reading the ca-addtional.pem certificate, which is mounted in the pod.

**Comment by StrongMonkey** [comment]
I assume this will also be an issue for all other providers. Changed the title to make sure we address EKS/AKS/GKE.

**Comment by gaktive** [comment]
Backport to 2.5.x still needs to be merged but everything else in place for 2.6.

**Comment by prabalsharma** [comment]
@thedadams do you the repro steps for this?
I tried to repro this on Rancher 2.5.5 behind the proxy using QA proxy setup but did not see the above mentioned error for EKS.

**Comment by thedadams** [comment]
@prabalsharma The QA setup doesn't use a certificate on the proxy. I had to set it up manually to test this scenario.

**Comment by prabalsharma** [comment]
Blocked on: https://github.com/rancher/rancher/issues/33398 & https://github.com/rancher/rancher/issues/33241

**Comment by prabalsharma** [comment]
(tested on b6bcfad)
All 3 clusters got created. However, I am still seeing some issues:

Rancher is not able to communicate with the created AKS cluster

```
Failed to communicate with cluster: error getting service account token: Post "https://aks-proxy-7a83b20e.hcp.eastus.azmk8s.io:443/api/v1/namespaces": x509: certificate signed by unknown authority
```


```
Doing /etc/rancher/ssl
W0721 19:37:43.529565 9 loader.go:223] Config not found: /home/aks-operator/.kube/config
time="2021-07-21T19:37:43Z" level=info msg="Starting aks.cattle.io/v1, Kind=AKSClusterConfig controller"
time="2021-07-21T19:37:43Z" level=info msg="Creating cluster [aks-proxy]"
time="2021-07-21T19:37:43Z" level=info msg="Checking if resource group [Prabal-rg] exists"
time="2021-07-21T19:37:43Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2021-07-21T19:37:44Z" level=info msg="Creating AKS cluster [aks-proxy]"
time="2021-07-21T19:37:51Z" level=info msg="Waiting for cluster [c-mvpgn] to finish creating"
time="2021-07-21T19:37:51Z" level=info msg="Waiting for cluster [c-mvpgn] to finish creating"
time="2021-07-21T19:37:52Z" level=info msg="Waiting for cluster [c-mvpgn] to finish creating"
time="2021-07-21T19:38:22Z" level=info msg="Waiting for cluster [c-mvpgn] to finish creating"
time="2021-07-21T19:38:53Z" level=info msg="Waiting for cluster [c-mvpgn] to finish creating"
time="2021-07-21T19:39:23Z" level=info msg="Waiting for cluster [c-mvpgn] to finish creating"
time="2021-07-21T19:39:54Z" level=info msg="Waiting for cluster [c-mvpgn] to finish creating"
time="2021-07-21T19:40:24Z" level=info msg="Waiting for cluster [c-mvpgn] to finish creating"
time="2021-07-21T19:40:55Z" level=info msg="Waiting for cluster [c-mvpgn] to finish creating"
time="2021-07-21T19:41:27Z" level=info msg="Cluster [aks-proxy] created successfully"
time="2021-07-21T19:41:28Z" level=info msg="Checking configuration for cluster [aks-proxy]"
time="2021-07-21T19:41:28Z" level=info msg="Configuration for cluster [aks-proxy] was verified"
```

On GKE and EKS, I am seeing
```	
CrashLoopBackOff: back-off 5m0s restarting failed container=cluster-register pod=cattle-cluster-agent-86bcb758f9-rb6zs_cattle-system(4dc465d6-357c-4b5f-aec3-40fb84617e44)
```

On Ember UI, I also saw an intermitent error popup
```Error
Get "https://5A5AB6A040028754450501772CF2FEFF.gr7.us-west-2.eks.amazonaws.com/api/v1/namespaces/kube-node-lease/persistentvolumeclaims?timeout=45s": x509: certificate is not valid for any names, but wanted to match 5A5AB6A040028754450501772CF2FEFF.gr7.us-west-2.eks.amazonaws.com
```

Some screenshots: 
<img width="1268" alt="Screen Shot 2021-07-21 at 3 56 16 PM" src="https://user-images.githubusercontent.com/3749546/126570180-3c60d2cc-502d-4858-8b6f-fe7469372ff8.png">

<img width="1227" alt="Screen Shot 2021-07-21 at 4 00 01 PM" src="https://user-images.githubusercontent.com/3749546/126570482-688f951d-2756-4b90-a613-56ec0b10e90e.png">

<img width="1267" alt="Screen Shot 2021-07-21 at 4 00 58 PM" src="https://user-images.githubusercontent.com/3749546/126570542-5cbeba58-ef17-4d5e-a2d3-54ea695ab2dd.png">

<img width="1323" alt="Screen Shot 2021-07-21 at 4 04 07 PM" src="https://user-images.githubusercontent.com/3749546/126570761-a5f21fd8-dd5a-4203-930b-4972a2ae2bad.png">

**Comment by prabalsharma** [comment]
I am still seeing the issues mentioned in my above comment, on 21ab02c

**Comment by prabalsharma** [comment]
@thedadams moved backport issue to review as well https://github.com/rancher/rancher/issues/32903, just so that we don't miss 2.5 merge (if required)

**Comment by thedadams** [comment]
As discussed offline, this issue only covers deploying of the hosted clusters. Any issues that may occur outside of provisioning and updating the config are outside the scope of this issue.

**Comment by prabalsharma** [comment]
waiting on build

**Comment by prabalsharma** [comment]
tested on v2.6-222dced3a7f8914dd94c8afcc5c47a7f09c8be99-head
I could provision AKS, GKE, EKS clusters and also update and sync them. However, there are still some issues with Rancher behind a proxy with certs. Follow up card: https://github.com/rancher/rancher/issues/33919 

QA on master-head: TBD

**Comment by prabalsharma** [comment]
same results ^, on master-61339fb7f8ff0b7833a80cbb3913f152477871b7-head
