### ISSUE TITLE
Google node driver cluster creation option available

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31858]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
On rancher server --> Add cluster --> Google node driver cluster option is available
<img width="1295" alt="Screen Shot 2021-03-30 at 8 54 22 PM" src="https://user-images.githubusercontent.com/26032343/113088382-51e6bf80-919a-11eb-8007-5b1d130cec45.png">

**Expected Result:**
This should NOT be available

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `cf376738e4`
- Installation option (single install/HA): single

**Comment by cbron** [comment]
Moving this to 2.5.8, as it appears there. We will forwardport to both branches.

**Comment by kravciak** [comment]
Google button disappeared from all fresh rancher installs.
I tried to reproduce on 2.5.5, 2.5.7, 2.5-head, master-head, `Google` infrastructure provider is not available anywhere.

Button is visible only on rancher UI that was created yesterday.
