### ISSUE TITLE
Too many Trace log messages seen in rancher logs when trace is not enabled 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31859]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy 2.5-head commit id: `118f9996`
- Deployed an EKS cluster/ DO rke on the rancher server.
- Noticed a a bunch of these log statements in rancher server. 
- Trace logs was _NOT_ enabled, but could see Trace logs
- Rancher logs contain:
[logs1.txt](https://github.com/rancher/rancher/files/6233716/logs1.txt)

**Other details that may be helpful:**

- A lot of these are seen, which makes it tough for the actual logs about cluster deployment and others hard to find.
- Is this expected?
- Reach out for more logs/this should be easily reproducible

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `118f999 `
- Installation option (single install/HA): single

**Comment by StrongMonkey** [comment]
These trace logs are coming from k8s api server. This is because recently we updated internal k3s version https://github.com/rancher/rancher/pull/31653. Would be better to suppress the log in future releases.

**Comment by StrongMonkey** [comment]
Going to change k3s(k8s) logs into a file `k3s.log` at working dir of rancher single-docker-install container. This file is constantly rotated by k3s to avoid growing file too big.(thanks @superseb for pointing it out.)

**Comment by sowmyav27** [comment]
**On master-head commit id: `5715b8a9`**

The logs in the original description are not available in rancher logs.
