### ISSUE TITLE
Cluster provisioning errors on master and the cluster is stuck in the error state

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#31857]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Version: master-cf376738e499ba538e80d8d02f37592391094ac4-head

Spin up a rancher server on master-head
create a cluster with 1etcd,1 worker and 1 cp
Once the cluster comes active, in a few minutes following error is seen:
```

namespace/cattle-system unchanged
serviceaccount/cattle unchanged
clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged
secret/cattle-credentials-7af00f1 unchanged
clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged
daemonset.apps/cattle-node-agent unchanged
daemonset.apps/kube-api-auth unchanged
error: unable to decode "management-state/tmp/yaml-086339767": 
resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace:
 Name: Annotations: ReadString: expects " or n, but found 3, error found in #10 byte of ...|ailable":3},
"name":"|..., bigger context ...|tations":{"management.cattle.io/scale-available":3},
"name":"cattle-cluster-agent","namespace":"cattl|...
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):

master-cf376738e499ba538e80d8d02f37592391094ac4-head

- Installation option (single install/HA): Single 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure 

- Kubernetes version (use `kubectl version`): v1.20.5

**Comment by sowmyav27** [comment]
**See this issue on master-head commit id: `cf37673`**

- Deployed a DO 1 node all roles cluster.
- The cluster is seen stuck in Provisioning state with error

```
Error while applying agent YAML, it will be retried automatically: exit status 1, clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver unchanged clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master unchanged namespace/cattle-system unchanged serviceaccount/cattle unchanged clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged secret/cattle-credentials-6e68107 unchanged clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged daemonset.apps/cattle-node-agent unchanged daemonset.apps/kube-api-auth unchanged error: unable to decode "management-statefile_path_redacted": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: Name: Annotations: ReadString: expects " or n, but found 3, error found in #10 byte of ...\|ailable":3},"name":"\|..., bigger context ...\|tations":{"management.cattle.io/scale-available":3},"name":"cattle-cluster-agent","namespace":"cattl\|...
```

**Comment by anupama2501** [comment]
Verified on master-f63b275882b7aedd5cc9bf74f3c9101da749f8eb-head

- Deployed a DO cluster with single node [etcd, cp, worker]
- Cluster has come up fine without any issues
- Enabled auth and deployed a linode as a standard user with 1 node all roles
- Cluster has come up fine without any issues
