### ISSUE TITLE
Catalog UI: Description section that uses readme is not updated in the UI when switching between templates using dropdown

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3186]
v0.51.0

Steps to Reproduce:
1. Go to Catalog, select Apache Zookeeper.
2. Use dropdown to select another template.

Result: The description section remains the same and doesn't get updated.

Expected Result: The description section to be updated. 

Note: The only difference is that Apache Zookeeper has an explicit README.md file. If you pick another service that doesn't have a README.md in the catalog, the description gets updated.

**Comment by ViBiOh** [comment]
:+1: See it today with my personal Catalog

**Comment by vincent99** [comment]
Yes, the readme content isn't cleared if the new template doesn't have one.

**Comment by deniseschannon** [comment]
Verified with v0.56.0-rc1
