### ISSUE TITLE
Mirror CIS Scan V1 image

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#31872]
Note:
This will be discussed during image workshop
https://github.com/rancher/rancher/issues/31598

Description:
We are going to start mirroring images with the prefix "mirrored". The process to do so is as follows:

Create ticket at in EIO repo for new dockerhub repo​.
Add image to image-list at https://github.com/rancher/image-mirror.​
Example: rancher/image-mirror#77

Change references of image in chart/rancher to use new image.
Example: rancher/charts#1005

CIS Scan v1 - @prachidamle

**Comment by prachidamle** [comment]
All images used by rancher-cis-benchmark:1.0.4

Images in images.txt | Action
----|------
rancher/mirrored-sonobuoy-sonobuoy: v0.16.3 |  already mirrored and exists here
rancher/cis-operator:v1.0.4 | no action, rancher owns the image
rancher/security-scan:v0.2.3  | no action, rancher owns the image

So I think this ticket can be closed.

**Comment by prachidamle** [comment]
@rmweir @cbron Can you review and confirm the CIS mirroring is done and  this can be closed?

**Comment by prachidamle** [comment]
We have used the mirrored image for CIS v2 - Opened a PR now to use it for CIS v1 system chart as well.

**Comment by cbron** [comment]
By mirrored image I'm assuming you mean just sonobuoy ? That one would be needed. If the other 2 are rancher owned they don't need anything to be done.

**Comment by prachidamle** [comment]
yes only the sonobuoy one

**Comment by rmweir** [comment]
@prachidamle can this be move to test?

**Comment by prachidamle** [comment]
Verified on master-head commit 861fb9208fd59c7f0c5266f087ccf050c1577ead

- Launched a downstream rke cluster
- In ember UI, Cluster --> Tools --> CIS Scans launched a **CIS V1** scan with profile "rke-cis-1.5"
- Under system project, the pods launched show the **"rancher/mirrored-sonobuoy-sonobuoy: v0.16.3"** used
- Screenshot:
<img width="1370" alt="Screen Shot 2021-07-22 at 9 58 39 PM" src="https://user-images.githubusercontent.com/1470602/126739174-9177da11-e870-45b7-97d5-3c0e44c8374f.png">

<img width="1059" alt="Screen Shot 2021-07-22 at 10 04 15 PM" src="https://user-images.githubusercontent.com/1470602/126739388-af90e5cd-c686-4148-bf66-fbad81834ed0.png">
