### ISSUE TITLE
Mirror Monitoring v1 image

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#31871]
Note:
This will be discussed during image workshop
https://github.com/rancher/rancher/issues/31598

Description:
We are going to start mirroring images with the prefix "mirrored". The process to do so is as follows:

Create ticket at in EIO repo for new dockerhub repo​.
Add image to image-list at https://github.com/rancher/image-mirror.​
Example: rancher/image-mirror#77

Change references of image in chart/rancher to use new image.
Example: rancher/charts#1005

Monitoring v1 - @aiyengar2

**Comment by cbron** [comment]
Closing, will use parent issue.

**Comment by jiaqiluo** [comment]
Reopen this for easier tracking of the progress.

**Comment by jiaqiluo** [comment]
This can be validated on monitoring v1 chart v0.2.3

**Comment by slickwarren** [comment]
following the table in this PR https://github.com/rancher/image-mirror/pull/96 I was able to verify that the following images are now mirrored (net new shown):
* rancher/coreos-prometheus-config-reloader:v0.39.0 -> rancher/mirrored-coreos-prometheus-config-reloader:v0.39.0
* rancher/coreos-prometheus-operator:v0.39.0 -> rancher/mirrored-coreos-prometheus-operator:v0.39.0
* rancher/thanosio-thanos:v0.15.0 -> rancher/mirrored-thanosio-thanos:v0.15.0 (enabled by adding the answers [here](https://github.com/rancher/rancher/issues/24793#issue-543953314) on install of monitoring v1)
