### ISSUE TITLE
Mirror rancher-external-dns system-chart images issue

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#31873]
Note:
This will be discussed during image workshop
https://github.com/rancher/rancher/issues/31598

Description:
We are going to start mirroring images with the prefix "mirrored". The process to do so is as follows:

Create ticket at in EIO repo for new dockerhub repo​.
Add image to image-list at https://github.com/rancher/image-mirror.​
Example: rancher/image-mirror#77

Change references of image in chart/rancher to use new image.
Example: rancher/charts#1005

DNS - @prachidamle

**Comment by prachidamle** [comment]
EIO ticket to create new repo at dockerhub: https://github.com/rancherlabs/eio/issues/454

**Comment by prachidamle** [comment]
Adding image to image-mirror list: https://github.com/rancher/image-mirror/pull/109

**Comment by prachidamle** [comment]
PR to update system-chart https://github.com/rancher/system-charts/pull/461

**Comment by anupama2501** [comment]
On master-head commit: 629146a

Images from Linux Image list is not listing `rancher/mirrored-kubernetes-external-dns v0.7.3` but is listing `rancher/kubernetes-external-dns:v0.7.3`

After creating an external DNS provider from Global --> DNS Providers -->  `cattle-global-data` namespace gets deleted.

Some logs in the rancher server:

```
[kube] 2021/05/26 17:05:46 Starting delete for "systemapp-anupama-dns-rancher-external-dns" Service
[kube] 2021/05/26 17:05:46 Starting delete for "systemapp-anupama-dns-rancher-external-dns" Deployment
[kube] 2021/05/26 17:05:47 Starting delete for "systemapp-anupama-dns-rancher-external-dns" ClusterRoleBinding
[kube] 2021/05/26 17:05:47 Starting delete for "systemapp-anupama-dns-rancher-external-dns" ClusterRole
[kube] 2021/05/26 17:05:47 Starting delete for "systemapp-anupama-dns-rancher-external-dns" ServiceAccount
[kube] 2021/05/26 17:05:47 Starting delete for "systemapp-anupama-dns-rancher-external-dns" Secret
2021/05/26 17:05:46 [DEBUG] Skipping refresh for system-user u-b4qkhsnliz 
[kube] 2021/05/26 17:05:46 Starting delete for "systemapp-anupama-dns-rancher-external-dns" Service
2021/05/26 17:05:46 [TRACE] REST GET apis/management.cattle.io/v3//tokens/helm-token-u-b4qkhsnlizd64rl
```

Related issue: https://github.com/rancher/rancher/issues/31638

**Comment by prachidamle** [comment]
I am able to ```docker pull rancher/mirrored-kubernetes-external-dns:v0.7.3```

**Comment by rmweir** [comment]
@prachidamle I think the issue is that the version in Chart.yaml in 0.1.3 is 0.1.2, and therefore the images aren't being extracted from it: https://github.com/rancher/system-charts/blob/dev-v2.6/charts/rancher-external-dns/v0.1.3/Chart.yaml#L6.

**Comment by prachidamle** [comment]
ahh, ok. I will update the chart version, Thanks @rmweir

**Comment by ekristen** [comment]
Is it possible that the reason things are being deleted are due to this issue? https://github.com/rancher/rancher/issues/31638

**Comment by prachidamle** [comment]
Validated on master-head commit: 861fb9208fd59c7f0c5266f087ccf050c1577ead

- The linux image list contains entry: ``` rancher/mirrored-kubernetes-external-dns:v0.7.3 ```
- After creating a  GlobalDNSProvider  named "test" from Tools --> Global DNS Providers, workload ```systemapp-test-rancher-external-dns``` is launched using image "rancher/mirrored-kubernetes-external-dns:v0.7.3"
- Screenshot:

<img width="1338" alt="Screen Shot 2021-07-22 at 9 29 29 PM" src="https://user-images.githubusercontent.com/1470602/126737863-78bdfb0d-6e2f-4e2a-aebd-e9cd4bd6a923.png">
<img width="1444" alt="Screen Shot 2021-07-22 at 9 29 42 PM" src="https://user-images.githubusercontent.com/1470602/126737867-5f849e4f-0f2f-4b0f-b8df-ba108a129e9b.png">
