### ISSUE TITLE
Logging to stdout and syslog

### ISSUE THREAD

**Issue by clemenko** [rancher/rancher#3187]
I have recently started playing with using the --log-driver for docker on a CoreOS host. I have noticed that with this log driver I am not able to "View Logs" from the Rancher interface. I think this is a docker issue. Not sure. Have you encountered this?

**Comment by ebr** [comment]
I *think* you need to be using the `json-file` driver in order for the logs to be accessible by Rancher. You can, however, use a log routing service (such as [logspout] (https://github.com/gliderlabs/logspout)) to copy your logs to multiple desired destinations. it's working very well for us to route logs into to an aggregator that is listening on the syslog port.

**Comment by clemenko** [comment]
Looks like it will work. THANKS!
