### ISSUE TITLE
Mirror OPA Gatekeeper image

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#31875]
Note:
This will be discussed during image workshop
https://github.com/rancher/rancher/issues/31873

Description:
We are going to start mirroring images with the prefix "mirrored". The process to do so is as follows:

Create ticket at in EIO repo for new dockerhub repo​.
Add image to image-list at https://github.com/rancher/image-mirror.​
Example: rancher/image-mirror#77
Change references of image in chart/rancher to use new image.
Example: rancher/charts#1005

OPA Gatekeeper - @cmurphy

**Comment by cmurphy** [comment]
This is done https://hub.docker.com/r/rancher/mirrored-openpolicyagent-gatekeeper

**Comment by SheilaghM** [comment]
Maybe done.  Does it need review?

**Comment by cmurphy** [comment]
Just going to close this, it can be tracked in the [main issue](https://github.com/rancher/rancher/issues/31598) if something else is needed
