### ISSUE TITLE
Auth redirect logic change

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31874]
Master- PR : https://github.com/rancher/rancher/pull/31563
Related issue: https://github.com/rancher/dashboard/issues/2538, 
https://github.com/rancher/dashboard/issues/2349
https://github.com/rancher/dashboard/issues/2340

Logging this issue for a 2.5 PR

**Comment by anupama2501** [comment]
Verified on v2.5-6bb6c97e2a737f3d683a2c0ca476b8a27dce485e-head

**Issue1:** 
From the cluster-explorer, Users and authentication --> Auth Providers --> Azure AD --> copy the 'Reply URL' and paste in the registration portal test app
Provide the Tenant ID, Application ID and Application Secret and select standard as the Endpoints in the Azure AD in the auth providers page --> Authenticate with Azure and the authentication goes through without any error
Create a cluster logged in as a standard user

**Issue2:**
From the cluster-explorer, Users and authentication --> Auth Providers --> Azure AD --> copy the 'Reply URL' and paste in the registration portal test app
Select the endpoints as custom, and add the endpoint, graph endpoint, token endpoint and auth endpoint
Enable and the auth goes through.
Logged in as standard user and created a cluster, cluster has become active

**Issue3:**
from cluster explorer --> Users and auth --> Auth providers --> Enable Azure AD by providing the details
Log out and login --> Users are taken to rancher login page
Login again and no errors seen.
