### ISSUE TITLE
After creating a node group from EKS console, node group is not seen on cluster edit

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#31896]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Deploy Rancher `v2.5-head` `version bdec2f2`
Create a hosted EKS cluster.
After cluster becomes available, create a node group from EKS console.
Wait for node group to deploy in EKS console and for Rancher cloud refresher to sync (5 min. by default)
Edit the cluster.

**Result:**
The added node group is not seen on cluster edit. The added nodes are seen on cluster node view.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5-head` `version bdec2f2`
- Installation option (single install/HA): Single install

**Comment by aaronRancher** [comment]
This behavior is seen in Rancher `master-head` `version 89c4d85`
This issue is not seen in Rancher `v2.5.7`

**Comment by aaronRancher** [comment]
Related to this issue, Rancher logs show consistent errors when updating an EKS cluster:
```
2021/04/02 18:39:09 [DEBUG] EKS cluster [c-8kqbt] will be managed by eks-operator-controller, skipping update
2021/04/02 18:39:09 [INFO] waiting for cluster EKS [c-8kqbt] to update
2021/04/02 18:39:09 [ERROR] error syncing 'c-8kqbt': handler cluster-refresher-controller: lastRefreshTime is required, requeuing
```
Will test this use case once the fix is available.

**Comment by sowmyav27** [comment]
**Use cases to test:**

- Import usecase --> Modify the cluster from EKS console. Verify Sync goes through and changes reflect back in rancher.
- Import usecase with AWS LT --> Modify the cluster from EKS console. Verify Sync goes through and changes reflect back in rancher.
- Hosted EKS cluster --> Add node group using AWS LT (LT created in AWS console) --> Modify the LT version from EKS console. Verify Sync goes through and changes reflect back in rancher.

**Comment by aaronRancher** [comment]
Tested following use cases with Rancher server `rancher\rancher:master-head` `version b202f20` and `rancher\rancher:v2.5-head` `version d1083bc`

Scenario 1:
Create a hosted EKS cluster.
After cluster becomes available, create a node group from EKS console.
Wait for node group to deploy in EKS console and for Rancher cloud refresher to sync (5 min. by default)
Edit the cluster.
Result:
The node group created from EKS console is seen on Rancher cluster edit.

Scenario 2:
Create an EKS cluster from EKS console with k8s version 1.17.
From Rancher, import the EKS cluster.
From EKS console, upgrade the cluster to k8s version 1.18.
From EKS console, add a node group.
Wait for Rancher cloud refresher to sync (5 min. by default).
Edit the cluster.
Result:
The cluster upgrade and new node group are reflected in Rancher.

Scenario 3:
Create an EKS cluster from EKS console using a preexisting launch template with multiple versions.
From Rancher, import the EKS cluster.
From EKS console, change the launch template version of the node group.
Wait for Rancher cloud refresher to sync (5 min. by default).
Edit the cluster.
Result:
The new launch template and its fields are reflected in Rancher.

Scenario 4:
From Rancher, create a hosted EKS cluster using a preexisting launch template with multiple versions using "version 1".
After cluster becomes available, edit the cluster from EKS console.
From EKS console, change the launch template version to "version 2"
Result:
The new launch template and its fields are reflected in Rancher.

Issues found during testing:
https://github.com/rancher/rancher/issues/32057
