### ISSUE TITLE
Not able to reach rancher-metadata

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3189]
Server version - Build from master

Steps to reproduce the problem:
Create and activate service.
From within any container, try to access rancher-metadata.

<img width="676" alt="screen shot 2016-01-07 at 12 02 49 pm" src="https://cloud.githubusercontent.com/assets/4266958/12181416/d9829bbc-b536-11e5-82b2-226d3e107875.png">

 Following error constantly seen in rancher-dns.log

<img width="663" alt="screen shot 2016-01-07 at 11 48 52 am" src="https://cloud.githubusercontent.com/assets/4266958/12181431/f59795e6-b536-11e5-9ea4-274ea2710b43.png">

**Comment by alena1108** [comment]
@vincent99 and @ibuildthecloud fixed it, its in the master already

**Comment by sangeethah** [comment]
Tested with latest build from master:

Note  - This was a setup with older master build that had the rancher-metadata service not being reachable.

Containers that are run on new hosts added to the set up have no problem accessing rancher-metadata.

But containers that are in the old hosts still have the same issue. Does this suggest that we will have the same issue when upgrading from v0.51.0 to a future rc release of v0.52.0 ?

**Comment by vincent99** [comment]
There's just nothing restarting it since the init script changed.. Restart the network agent or host.

**Comment by sangeethah** [comment]
Restarting host fixed the issue.
