### ISSUE TITLE
Instance type is set for a nodegroup when Spot instances is set in a launch template in eksv2

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31908]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a hosted EKS v2 cluster
- Use a Launch Template with Spot instances set
- Choose spot instance type: t3.medium
- Deploy the cluster
- Cluster throws an error `Nodegroup [sow] in cluster [c-vfdrx]: instance type should not be specified when requestSpotInstances is specified, use spotInstanceTypes instead`
- API request sent contains `instanceType: "t3.medium"` and `spotInstanceTypes: ["t3.medium"] 0: "t3.medium"`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `2f2cfe63`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS v2 hosted
- Kubernetes version (use `kubectl version`):

```
1.18(ANY)
```

**Comment by thedadams** [comment]
@sowmyav27 Launch templates that specify Spot Instances are not allowed in EKS managed node groups. This is a restriction from EKS, not Rancher. I believe that the UI is handling this correctly.

![Screen Shot 2021-04-05 at 11 40 55 AM](https://user-images.githubusercontent.com/3682717/113612917-4d406200-9605-11eb-887d-0be6153c2d85.png)

**Comment by aaronRancher** [comment]
This behavior is reproduced on Rancher `v2.5.7`.

Steps:
Deploy a hosted EKS v2 cluster
Use a Launch Template with Spot instances set
Choose spot instance type: `t3.medium`
Deploy the cluster

Result:
Cluster provisioning errors with:
```
Nodegroup [aaron-ng] in cluster [c-899c4]: instance type should not be specified when requestSpotInstances is specified, use spotInstanceTypes instead
```

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5-head` `version 93d921f` and `master-head` `version 4569c59` 

The error message has changed, reflecting the comment from @thedadams 
```
Waiting for API to be available; InvalidParameterException: Instance market options are not supported with the launch template. { RespMetadata: { StatusCode: 400, RequestID: "ca27607f-4604-41a5-a99c-0672c15d5f49" }, Message_: "Instance market options are not supported with the launch template." }
```

**Comment by aaronRancher** [comment]
On `v2.5-head` and `master-head`, the API request no longer has `instanceType` set. Only `spotInstanceTypes` is populated when using a launch template with spot instances enabled.
```
nodeGroups: [,…]
0: {desiredSize: 2, diskSize: 20, ec2SshKey: "", gpu: false, imageId: "", instanceType: "", labels: {},…}
desiredSize: 2
diskSize: 20
ec2SshKey: ""
gpu: false
imageId: ""
instanceType: ""
labels: {}
launchTemplate: {id: "lt-0eeeff14d2d4b8a2c", name: "aaron-spot", type: "/v3/schemas/launchTemplate", version: 1}
id: "lt-0eeeff14d2d4b8a2c"
name: "aaron-spot"
type: "/v3/schemas/launchTemplate"
version: 1
maxSize: 2
minSize: 2
nodegroupName: "aaron-ng"
requestSpotInstances: true
resourceTags: {}
spotInstanceTypes: ["t3.medium"]
0: "t3.medium"
subnets: []
tags: {}
type: "/v3/schemas/nodeGroup"
userData: ""
version: "1.18"
```
