### ISSUE TITLE
Error after a k8s upgrade of the eksv2 cluster from EKS console

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31909]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a hosted EKS cluster with 1.17 k8s version
- When the cluster has come up successfully, change the k8s version of the cluster from the EKS console to 1.18
- Wait for the cluster to finish upgrading in the eks console, and wait for the sync. (noticed the setup after about 8 hours)
- The cluster is stuck in Updating state in Rancher with error: `InvalidParameterException: Unsupported Kubernetes minor version update from 1.18 to 1.17 { RespMetadata: { StatusCode: 400, RequestID: "b950725d-17f9-4d4a-9aaf-3fd6b862701d" }, ClusterName: "sowmya-1", Message_: "Unsupported Kubernetes minor version update from 1.18 to 1.17" }`
- Cluster in the EKS console is upgraded to 1.18 successfully
- Upstream spec and EKS config both have 1.17 k8s version. 
- EKS Config
```
eksConfig": {
"amazonCredentialSecret": "cattle-global-data:cc-fgbgz",
"displayName": "sowmya-1",
"imported": false,
"kmsKey": "",
"kubernetesVersion": "1.17",
......
```
- Upstream spec:
```
"upstreamSpec": {
"amazonCredentialSecret": "cattle-global-data:cc-fgbgz",
"displayName": "sowmya-1",
"imported": false,
"kmsKey": "",
"kubernetesVersion": "1.17",
......
```

**Expected Result:**
Cluster should get updated successfully in Rancher with no error.

**Other details that may be helpful:**
eks operator versioon: `rancher/eks-operator:v1.0.8-rc2`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `2f2cfe636`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted EKS
- Kubernetes version (use `kubectl version`):

```
1.17 to 1.18 (k8s upgrade)
```

**Comment by thedadams** [comment]
This issue is a related to syncing, which is fixed here: https://github.com/rancher/rancher/pull/31901

I verified that fix also fixes this issue.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server Rancher server `rancher\rancher:master-head` `version b202f20` and `rancher\rancher:v2.5-head` `version d1083bc`

Steps:
- Deploy a hosted EKS cluster with 1.17 k8s version
- When the cluster has come up successfully, change the k8s version of the cluster from the EKS console to 1.18
- Wait for the cluster to finish upgrading in the eks console, and wait for the sync. 

Result:
Cluster k8s upgrade from EKS console is reflected in Rancher. 
Upstream and EKS config both reflect the correct k8s version (1.18)
