### ISSUE TITLE
KEv2: Autopilot support for GKE operator

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#31918]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature request - Add support for Autopilot mode for GKE clusters.

**Comment by cmurphy** [comment]
Reverted this in https://github.com/rancher/gke-operator/pull/23, can reevaluate after 2.5.8 whether it makes sense to try to find a workaround to get this to work.

**Comment by totogo** [comment]
It would be great if Rancher supports GKE autopilot
