### ISSUE TITLE
Chart repo status stuck on "downloading" when error occurred

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#31915]
Create a new chart repository

Git URL:  https://github.com/janeczku/keepalived-ingress-vip.git
Branch:   archive

Result:

The displayed state remains "downloading". When clicking on the repo it shows that actually the download already failed.

Expected:

The state should convey that an error occured, e.g.  "download failed".

<img width="820" alt="Screenshot 2021-04-01 at 12 02 52" src="https://user-images.githubusercontent.com/3813921/113278710-86659300-92e2-11eb-8f5f-0965f2f58698.png">

Rancher 2.5.6

**Comment by gaktive** [comment]
Not a UI issue so passing over to rancher/rancher

**Comment by FruityWelsh** [comment]
This seems like two issues:
 1. on a backend side the download failed
 1. The UI is misrepresenting the state by saying it is still downloading
