### ISSUE TITLE
If you delete the Default environment, but leave other environments up, connection to host degrades and you cannot add hosts back

### ISSUE THREAD

**Issue by dnadave** [rancher/rancher#3192]
We had an environment where all of my users were already added and a host was up.  We then deleted all other environments, including Default.  We then lost the connection to the host under the remaining environment and we cannot add it back.  rancher-agent is running, but is not connected to the server.

Rancher 0.51.0

**Comment by deniseschannon** [comment]
@dnadave Per our email exchange, running  `rm -rf /var/lib/rancher/state; docker rm -fv rancher-agent; docker rm -fv rancher-agent-state` before running the rancher-agent command again solved your issue.
