### ISSUE TITLE
Import YAML creates resources in local cluster instead of downstream cluster

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#31922]
Opening issue to track backend fix for https://github.com/rancher/dashboard/issues/2585 on master-head.

PR in `v2.5-head`: rancher/rancher#31836

**Comment by deniseschannon** [comment]
This fix was already added in master. https://github.com/rancher/rancher/blob/master/pkg/api/steve/proxy/proxy.go#L69

Can you test in master-head? @aaronRancher

**Comment by aaronRancher** [comment]
Currently blocked by: https://github.com/rancher/rancher/issues/31964

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 8c014ef`. With the following steps.

Import YAML in cluster explorer:
![Screen Shot 2021-05-07 at 4 43 02 PM](https://user-images.githubusercontent.com/57409052/117518177-a4fb2180-af53-11eb-8cfc-df4934cec903.png)
Test import YAML in default namespace and in user-created namespace
![Screen Shot 2021-05-07 at 4 49 38 PM](https://user-images.githubusercontent.com/57409052/117518341-3b2f4780-af54-11eb-94f4-90058b3b68f9.png)
Verified that resources are created in the downstream cluster namespaces and not in local cluster.
