### ISSUE TITLE
[Monitoring V2] Persist dashboards for Rancher Cluster Overview in Grafana

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#31921]
Adds the dashboards in https://github.com/rancher/dashboard/issues/812 to the Grafana so that they are deployed with the Monitoring chart itself.

**Comment by slickwarren** [comment]
I was able to test the cluster metrics, verifying what is in v1 cluster dashboard is now in grafana when v2 monitoring is deployed.  moved back to reivew, as Node and Workload graphs are still being added into grafana

**Comment by aiyengar2** [comment]
This issue should also test https://github.com/rancher/rancher/issues/31990 and https://github.com/rancher/rancher/issues/31742.

**Comment by aiyengar2** [comment]
This issue should also ensure https://github.com/rancher/rancher/issues/32101 is true to allow UI to embed cluster overview dashboards.

**Comment by slickwarren** [comment]
on 2.5.8-rc9 using 14.5.100:

* ensure #32101 is true to allow UI to embed cluster overview dashboards. -- pass
* #31742. -- pass
* #31990 -- pass
* reverified  cluster metrics, verifying what is in v1 cluster dashboard is now in grafana when v2 monitoring is deployed
* node and workload metrics are in grafana (will be added to 2.6 UI later) are working as expected (showing graphs similar to v1 metrics for node/workload/pod
<img width="260" alt="Screen Shot 2021-04-23 at 4 30 06 PM" src="https://user-images.githubusercontent.com/16691014/115939002-66447200-a451-11eb-8712-36d574c03d29.png">

**Comment by slickwarren** [comment]
also did a passthrough of the following on v2.5.8-rc9:

* an upgrade from an older version of Monitoring on a Linux cluster does not change the contents of the Home dashboard (the one that shows up when you open Grafana) unless it is to rectify a mistake in the previous version of the dashboard w.r.t. metrics shown or change the visualization to be more adept at visualizing what it seeks to show
PASS (9.4.204 -> 14.5.100 does not change grafana homepage)


* That a clean install of Monitoring onto a Linux cluster has:
  * Data for every single dashboard -- pass (some small issues filed [here](https://github.com/rancher/rancher/issues/32357))
  * Logically accurate data for every single dashboard e.g. if there are things like CPU / Memory usage, we should make sure the values shown actually make sense -- pass
  * Logically accurate options for template variables values based on items deployed onto the cluster  (i.e. new/custom workloads will populate on nodes/workloads/pods grafana pages) -- pass
  * Logically accurate labels should appear for the legends of each dashboard and titles should be cased correctly and cleanly described (legend in this case is the menu that populates when hovering over a graph) -- pass

**Comment by sowmyav27** [comment]
On a windows cluster on `2.5.8-rc12`:

- Enable Monitoring v2 on the cluster
- Verified `Set security.allow_embedding to true` 
- metrics for node/workload/pod in Grafana - show metrics from Windows nodes/pods
- Prometheus Graphs show metrics from windows pods.
- Prometheus targets are `UP` including windows nodes.
