### ISSUE TITLE
Logging v2 chart fails to deploy

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31925]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- As a standard user
- On 2.5-head commit id: `2f2cfe63`, deploy a custom cluster - all roles - 3 nodes
- deploy Logging v2 chart version: `3.9.400-rc00`
- The chart fails to deploy with error `helm upgrade --install=true --namespace=cattle-logging-system --timeout=10m0s --values=/home/shell/helm/values-rancher-logging-3.9.400-rc00.yaml --version=3.9.400-rc00 --wait=true rancher-logging /home/shell/helm/rancher-logging-3.9.400-rc00.tgz Release "rancher-logging" does not exist. Installing it now. Error: template: rancher-logging/templates/loggings/root/logging.yaml:11:16: executing "rancher-logging/templates/loggings/root/logging.yaml" at <.Values.global.windows.enabled>: nil pointer evaluating interface {}.enabled`

**Expected Result:**
Chart should get deployed successfully

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `2f2cfe63`
- Installation option (single install/HA): single node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom rke
- Kubernetes version (use `kubectl version`):

```
1.20 (Any)
```

**Comment by nickgerace** [comment]
Figured out the issue. Regenerated a patch after a rebase, which was missing a `values.yaml` field: https://github.com/rancher/charts/pull/1076/files

Fixing now.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `2f2cfe6`**

- Deployed a 3 node all roles custom cluster
- Deploy logging v2 - `rancher-logging:3.9.400-rc02` version
- Verified logging chart deploys successfully with no errors.
