### ISSUE TITLE
Monitoring V2 on windows can't upgrade to include windowsExporter.enabled=true

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31923]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy a windows downstream cluster
* install monitoring with default settings on the cluster
* upgrade monitoring with `windowsExporter.enabled: true`

**Result:**
the DaemonSet | `rancher-monitoring-windows-exporter` has a deployment that is crashing, with the error `Failed to connect to proxy
<img width="1660" alt="Screen Shot 2021-04-05 at 11 42 41 AM" src="https://user-images.githubusercontent.com/16691014/113620520-41f23400-960f-11eb-95ff-dcfa117314c3.png">

**Other details that may be helpful:**
the default use case (enabling windows exporter on install, not on upgrade) works fine.  

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-head 2f2cfe6
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Windows (used QA Automation)
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 1.20.5

- Docker version (use `docker version`): windows:  19.3.14 linux: 20.10.5

**Comment by aiyengar2** [comment]
@slickwarren I'm unable to reproduce this in the latest chart. Can you try again?

**Comment by slickwarren** [comment]
I was not able to reproduce this using monitoring version 14.5.100-rc3
