### ISSUE TITLE
rancher-wins-upgrader chart offers new install instead of upgrade

### ISSUE THREAD

**Issue by kravciak** [rancher/rancher#31927]
**To reproduce:**

- Deploy a windows cluster - 3 linux nodes - 1 etcd, 1 control and 1 worker nodes  (I added 10 windows worker nodes, probably not necessary)
- Point the feature charts to dev-v2.5 branch

- Deploy rancher-wins-upgrader with the following override:
```
masquerade:
  enabled: true
  as: c:\\etc\wmi-exporter\wmi-exporter.exe
```
- Deploy Monitoring v2 on the cluster into System Project (can be probably skipped)
- Deploy rancher-wins-upgrader again.

**Expected result:**
Rancher dashboard shows `UPGRADE` button when I open Apps & Marketplace -> Charts -> rancher-wins-upgrader

**Current result**
UI shows `INSTALL` button, after clicling there is an error deploying chart:
```
helm install --generate-name=true --namespace=default --timeout=10m0s --values=/home/shell/helm/values-rancher-wins-upgrader-0.0.100-rc00.yaml --version=0.0.100-rc00 --wait=true /home/shell/helm/rancher-wins-upgrader-0.0.100-rc00.tgz
--
Mon, Mar 29 2021 4:58:24 pm | Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodSecurityPolicy "wins-upgrader" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "rancher-wins-upgrader-0-1617029904": current value is "rancher-wins-upgrader-0-1617028158"
```

**Environment information**
- Rancher version v2.5.8-rc1
- Windows: ami-008ec03d9035c8ee7
- Installation option single install (docker)

**Comment by aiyengar2** [comment]
@vincent99 hmm so re: your comment

> The UI is doing what it's supposed to here; the chart lacks the fixed namespace and name annotations, so it can be installed multiple times.

Are the annotations you are referring to here `catalog.rancher.io/namespace` and `catalog.rancher.io/release-name`? I see that those annotations already exist in https://github.com/rancher/charts/blob/a85fa88c2b701a2f6e6df413a807b746b7f07134/charts/rancher-wins-upgrader/rancher-wins-upgrader/0.0.100-rc00/Chart.yaml#L1-L5.

> If it's supposed to be only installed once it should be annotated as such.

I think this is the annotation that I might be missing but I'm not aware of such an annotation. Can you link me to the annotation that I need to add to enforce that this app should only be installed once in the cluster?

**Comment by vincent99** [comment]
@aiyengar2 Yes those, but this chart has the wrong prefix on 3 of 4 annotations.  The right one is `catalog.cattle.io/...`, not `catalog.rancher.io/...`.

**Comment by kravciak** [comment]
I deployed rancher-wins-upgrader 0.0.100-rc01 chart on rancher 2.5.8-rc3 and I see upgrade button as expected.
