### ISSUE TITLE
[HELP] when I create so many namespace over 5000 in a project, The rancher api is very slow, Why? 

### ISSUE THREAD

**Issue by yxxhero** [rancher/rancher#31935]
[HELP] when I create so many namespace over 5000 in a project, The rancher api is very slow, Why? 

Similar URL:
https://x.x.x.x:443/v3/projects/c-mgmmx:p-v4f65/workloads?namespaceId=ops-test
when I access it. The number of tcp established  is very high. over 25000. In the kube-apiserver.

Why?  Thanks very much.
Does rancher have any restrictions or suggestions on this?

**Comment by yxxhero** [comment]
@vincent99  We look forward to your reply.

**Comment by yxxhero** [comment]
anyone can help me?

**Comment by yxxhero** [comment]
anyone can help me?

**Comment by vincent99** [comment]
...Don't do that?  Namespaces are the main division of RBAC and some things scale linearly (or maybe worse) with the number of them.

**Comment by yxxhero** [comment]
@vincent99 Thanks very much.
