### ISSUE TITLE
Rancher UI doesn't show loadbalancer ip address

### ISSUE THREAD

**Issue by Br1zl0p** [rancher/rancher#31937]
**What kind of request is this (question/bug/enhancement/feature request):**
Question/Bug

**Steps to reproduce (least amount of steps as possible):**
- install metallb 
- create service of type LoadBalancer

**Result:**
 Service is reachable with the assinged ip address from metallb but the loadbalancer ip is not shown as externalIP in the Rancher UI.

**Other details that may be helpful:**

**Environment information**
- Rancher version: 2.5.7
- Installation option: HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Selfhosted
- Kubernetes version (use `kubectl version`): 1.18.6
- Docker version (use `docker version`): 19.03.12

Output from  `kubectl get svc whoami-loadbalancer -o yaml`:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.10.10.4"],"port":80,"protocol":"TCP","serviceName":"default:whoami-loadbalancer","allNodes":false}]'
    field.cattle.io/targetWorkloadIds: '[''default/whoami'']'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2021-04-06T09:23:13Z"
  managedFields: [...]
  name: whoami-loadbalancer
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: whoami
    uid: 41c199ee-50b5-4fe7-9096-eaa644b3e208
  resourceVersion: "49646708"
  selfLink: /api/v1/namespaces/default/services/whoami-loadbalancer
  uid: 7cd7d657-7f61-49f9-bdf4-76ffe915c134
spec:
  clusterIP: 10.43.35.194
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30308
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-whoami
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.10.10.4
```

Service in the Rancher UI:
![rancher](https://user-images.githubusercontent.com/15386339/113722649-e9936300-96f0-11eb-8c88-05ffdee0d3e8.png)

**Comment by Martin-Weiss** [comment]
+1 - just ran into exactly this problem, too!
