### ISSUE TITLE
Validate v1 and v2 charts for SLES 15 SP1

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31945]
Validate v1 and v2 charts for SLES 15 SP1.
- Deploy rancher 2.5-head
- Deploy v1 charts and verify the P0 usecase (note down the chart version)
- Deploy v2 charts and verify the P0 usecase (note down the chart version)

**Comment by thehejik** [comment]
**Test environment:**
* rancher:v2.5-head `9b0058c` with k8s `v1.20.5` on AWS t2.medium instance type and `us-east-2` region
* 1x master (control-plane + etcd) and 3x worker
* using official aws image for SLE15SP1 `suse-sles-15-sp1-chost-byos-v20210304-hvm-ssd-x86_64`, `ami-014b2be5492b26b99`

**Few v1 charts validated so far:**
v1 charts **logging** - used fluentd - rancher-logging 0.2.4
:+1: cluster level
:+1: project level
:+1: edit as yaml

v1 **alerting** - no version
:+1: minimum - webhook
:+1: :boom: high cpu with enabled v1 monitoring - webhook 
... due broken v1 monitoring (needed for high cpu alert) - pod prometheus-proxy pod says ImagePullBackOff: Back-off pulling image "rancher/library-nginx:1.19.9-alpine", workaround is to use rancher/library-nginx:1.19.2 instead, https://github.com/rancher/rancher/issues/32010

v1 **pipeline** - no version
:+1: simple testcase with example repo and without Github Oauth

**Comment by thehejik** [comment]
**Test environment:**
* Tested on rancher:2.5.8-rc12 
* the rest is as before

**v2 charts validation report:**
:+1: **monitoring** - 14.5.100 - installed in System project

:+1: **logging** - 3.9.400 - clusterOutput (cluster level), Output (namespace level) 

:+1: **istio** - 1.9.300 - demoapp deployed and tested

:+1: **OPA Gatekeeper** - 3.3.001 - a namespace without label cannot be created

:-1: :boom: **FAILED** **CIS Benchmark** - 1.0.400 - scan with rke-profile-permissive-1.6 - NEW https://github.com/rancher/rancher/issues/32428

:+1: **fleet/Continous Delivery** - `rancher/fleet-agent:v0.3.5-rc6` - Guestbook app deployed

**SKIPPED** **Backup and Restore** - local cluster only
