### ISSUE TITLE
[Monitoring V2] Use global.cattle.windows.enabled for windowsExporter

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#31942]
The condition for deploying rancher-windows-exporter should be whether global.cattle.windows.enabled is true.

**Comment by thehejik** [comment]
**Test report:**
Overall test result: works as expected.

**Testing environment:**
* rancher v2.5-head `9b0058c` HA on AWS (with v1 monitoring disabled, wins-upgrader not deployed)
* kubernetesVersion: `v1.20.5`
* 3 linux nodes - 1 etcd, 1 control and 1 worker nodes, 3 windows nodes (used windows core 1909 `ami-008ec03d9035c8ee7`) 
* Used `dev-v2.5` feature helm charts
* Tested versions of chart: `rancher-monitoring-14.5.100-rc05`
* v2 monitoring deployed into `System` project by selecting `RKE` from Cluster Type dropdown in General tab and setting `global.cattle.windows.enabled=true` in values.yaml (+ see workaround)

**Results:**
* `windowsExporter.enabled` key is not present in values.yaml anymore
* windowsExporter key has been replaced by `global.cattle.windows.enabled` (false by default)
* Windows exporters are present in prometheus/targets and in grafana as well (after applying the workaround below)

Workaround for #32024:
The chart is broken at this moment due https://github.com/rancher/rancher/issues/32024. To workaround this issue I did an initial deployment of v2 Monitoring which failed, then I cloned existing `rancher-monitoring-etcd` ConfigMap from `cattle-dashboard` namespace to `cattle-monitoring-system` namespace with the original name and content and redeployed the chart by selecting `Edit/Upgrade` in `Installed Apps` menu. The v2 monitoring deployment was successful then.

**Comment by thehejik** [comment]
Has to be retested on `master-head` and `dev-v2.6` helm chart repo as well.

**Comment by sowmyav27** [comment]
Closing this, tracking master-head validation here - https://github.com/rancher/rancher/issues/32089
