### ISSUE TITLE
when I go to Audit Log screen, dev tool showing 404 error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3195]
version - master jan 07

Steps:
1.  Go to Audit Logs

Results: The dev tool seems to be throwing a couple of errors everytime I go to this page
GET http://23.236.51.56:8080/v1/identities/1i!rancher_id%3A7 404 (Not Found)

Expected:
No error

**Comment by vincent99** [comment]
@hibooboo2 Do we know what these identities are for and can it not send them if I'm not going to be able to get them?

**Comment by prachidamle** [comment]
@tfiduccia cant reproduce this, I am able to load the Audit Logs page in my setup.
Can you add any other steps to reproduce?

**Comment by prachidamle** [comment]
Got this picture from @tfiduccia 

This error is seen in developer-tools -> console. Not shown on rancher UI. 


![pasted image at 2016_03_17 02_52 pm](https://cloud.githubusercontent.com/assets/1470602/13862405/564024d0-ec50-11e5-99c8-22d97f8dc99a.png)

**Comment by prachidamle** [comment]
@tani, can you re-test and see if this still happens. I dint see it.

**Comment by tfiduccia** [comment]
Actually I get more errors now.
![image](https://cloud.githubusercontent.com/assets/11514927/17082405/c549c020-5131-11e6-9e37-e00ef0980211.png)
