### ISSUE TITLE
rancher-operator fails to deploy 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31954]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a rancher server - single nod eon master-head
- Rancher operator has failed to deploy (dashboard of the local cluster)

<img width="1637" alt="Screen Shot 2021-04-06 at 3 10 03 PM" src="https://user-images.githubusercontent.com/26032343/113784379-2f006200-96ea-11eb-8991-67ae1e546751.png">

- Logs of helm operation pods:
```
helm upgrade --history-max=5 --install=true --namespace=rancher-operator-system --reset-values=true --timeout=5m0s --values=/home/shell/helm/values-rancher-operator-0.1.400-rc01.yaml --version=0.1.400-rc01 --wait=true rancher-operator /home/shell/helm/rancher-operator-0.1.400-rc01.tgz
checking 4 resources for changes
Looks like there are no changes for ServiceAccount "rancher-operator"
Looks like there are no changes for ClusterRole "rancher-operator"
Looks like there are no changes for ClusterRoleBinding "rancher-operator"
Looks like there are no changes for Deployment "rancher-operator"
beginning wait for 4 resources with timeout of 5m0s
Deployment is not ready: rancher-operator-system/rancher-operator. 0 out of 1 expected pods are ready
Deployment is not ready: rancher-operator-system/rancher-operator. 0 out of 1 expected pods are ready
Deployment is not ready: rancher-operator-system/rancher-operator. 0 out of 1 expected pods are ready
Deployment is not ready: rancher-operator-system/rancher-operator. 0 out of 1 expected pods are ready
....
Deployment is not ready: rancher-operator-system/rancher-operator. 0 out of 1 expected pods are ready
Deployment is not ready: rancher-operator-system/rancher-operator. 0 out of 1 expected pods are ready
Deployment is not ready: rancher-operator-system/rancher-operator. 0 out of 1 expected pods are ready
Deployment is not ready: rancher-operator-system/rancher-operator. 0 out of 1 expected pods are ready
Deployment is not ready: rancher-operator-system/rancher-operator. 0 out of 1 expected pods are ready
Deployment is not ready: rancher-operator-system/rancher-operator. 0 out of 1 expected pods are ready
Deployment is not ready: rancher-operator-system/rancher-operator. 0 out of 1 expected pods are ready
Error: UPGRADE FAILED: timed out waiting for the condition
```

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `215677e2`
- Installation option (single install/HA): single

**Comment by thedadams** [comment]
@sowmyav27 Can you try this again? I believe it was fixed by: https://github.com/rancher/charts/pull/1087

**Comment by sowmyav27** [comment]
**On maser-head commit id: `077fbf6 `**

I see rancher-operator has deployed, but i see the CRD and the app's version different. Is this expected?
<img width="1390" alt="Screen Shot 2021-04-06 at 9 26 12 PM" src="https://user-images.githubusercontent.com/26032343/113810315-d1d2d380-971e-11eb-955a-60435b83d84f.png">

**Comment by thedadams** [comment]
No, they should not be different. I am going to look into this.

**Comment by thehejik** [comment]
I don't see `rancher-operator*` deployment/pods deployed also the namespace `rancher-operator-system` is gone - maybe it was removed in meantime?

I was trying to deploy a fresh rancher server as single-node docker deployment and also as HA RKE (deployed by using 2.5.8-rc12 rancher chart) custom cluster provisioned by CI, both with the same result.

Cluster Explorer is working as far as I can see. There is no Ember UI available anymore.

Tried on rancher:master-head `7e5ad7f`

**Comment by thedadams** [comment]
@thehejik rancher-operator has been removed from the master branch of rancher. See https://github.com/rancher/rancher/issues/32179

**Comment by thehejik** [comment]
@thedadams thanks. Closing.
