### ISSUE TITLE
EKS cluster cannot recover from error state

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#31950]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- On `v2.5-head` `version 93d921f` and `master-head` `version 4569c59`
- Deploy a hosted EKS v2 cluster
- Use a Launch Template with Spot instances set
- Choose spot instance type: t3.medium
- Deploy the cluster
- The cluster will error with `Waiting for API to be available; InvalidParameterException: Instance market options are not supported with the launch template. { RespMetadata: { StatusCode: 400, RequestID: "ca27607f-4604-41a5-a99c-0672c15d5f49" }, Message_: "Instance market options are not supported with the launch template." }`
- Attempt to recover the cluster by editing the cluster.
- Delete the node group and create a new node group with default values.
- Save cluster.

**Result:**
Cluster is stuck in waiting state:
`Failed to communicate with cluster: Post "https://...l4.us-east-2.eks.amazonaws.com/api/v1/namespaces": x509: certificate signed by unknown authority`

The cluster and node group is available from the EKS console.

**Other details that may be helpful:**
Steps were taken from this issue: https://github.com/rancher/rancher/issues/31908

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
`v2.5-head` `version 93d921f` and `master-head` `version 4569c59`
- Installation option (single install/HA): single install

**Comment by thedadams** [comment]
This is a known issue.
The fix for master is here: https://github.com/rancher/rancher/pull/31930
The fix for 2.5 is here: https://github.com/rancher/rancher/pull/31946

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 5337233`

After cluster edit, by deleting the original node group and creating a new one, the cluster recovers.

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5-head` `version ebee7eb`

Cluster recovers after recreating node group.
