### ISSUE TITLE
Accessing clusters and v2 charts page is slow

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31963]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a DO cluster - all roles 3 nodes on a rancher master-head setup
- When the cluster is up and active, Try accessing the Default/System project of the deployed cluster.
- The page takes too long to load and rancher logs show:
- Rancher logs show:

```
I0407 04:02:28.336283      24 request.go:645] Throttling request took 1.045507152s, request: GET:https://127.0.0.1:6444/apis/management.cattle.io/v3?timeout=32s
I0407 04:02:45.444299      24 request.go:645] Throttling request took 1.045014219s, request: GET:https://127.0.0.1:6444/apis/management.cattle.io/v3?timeout=32s
I0407 04:02:59.388484      24 request.go:645] Throttling request took 1.045439151s, request: GET:https://127.0.0.1:6444/apis/management.cattle.io/v3?timeout=32s
```

**Note:**
Loading charts/apps also takes sometime, and these appear in rancher logs

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `215677`
- Installation option (single install/HA): single

**Comment by sowmyav27** [comment]
Do not notice this in master-head commit id: `077fbf6`. Will keep an eye out for this issue

**Comment by cbron** [comment]
If this is master-head only shouldn't this be 2.6 ? Also what version of k8s was it, I think one had performance issues.

**Comment by SheilaghM** [comment]
As this may be related to something Darren is doing, this should not be in 2.5.8.  After discussion with Dan, moving to 2.6.

**Comment by Jono-SUSE-Rancher** [comment]
@sowmyav27 Unless this is still happening now on master, can we close this ticket?

**Comment by sowmyav27** [comment]
This is not seen on master- commit id: `360edae `
