### ISSUE TITLE
getting started and FAQ links are broken on help page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3196]
Version - Master Jan 07

Steps:
1.  Go to Help
2.  Under Issues & Documentation section, click on the "getting started" link
3.  Go back and click on Check out our FAQs

Results: For Getting started I get a "password required" page, for FAQs, I get a 404 page not found.
![image](https://cloud.githubusercontent.com/assets/11514927/12185584/15128bca-b559-11e5-9dee-a74aa33da66f.png)

Expected:
Both links should work.

Comments:
Was informed the getting started is not up yet.  Will keep in bug to remind myself to click it.

**Comment by vincent99** [comment]
FAQ fixed, getting started is the "right" link but the page isn't up yet.

**Comment by tfiduccia** [comment]
version - master 1/19
Verified fixed
