### ISSUE TITLE
The built-in K3S upgrade in Rancher is stuck

### ISSUE THREAD

**Issue by yl-yue** [rancher/rancher#31971]
**What kind of request is this (question/bug/enhancement/feature request):**
question/bug

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.5.7
- Installation option (single install/HA):single install

**Steps to reproduce (least amount of steps as possible):**
K3S upgrade stuck and repeated prompt (this prompt will close and appear again and again in a few seconds, and keep repeating)
![image](https://user-images.githubusercontent.com/39790401/113884025-3c544400-97f1-11eb-93c3-e938a5d2b73f.png)
The relevant containers have all been upgraded
![image](https://user-images.githubusercontent.com/39790401/113884421-889f8400-97f1-11eb-99f1-b2e1112e435f.png)

The K3S upgraded here is the K3S built into Racher. This result appeared after I clicked the upgrade from the UI. I checked the relevant container logs, but did not find any useful information

#26448

**Comment by yl-yue** [comment]
Racher is installed in Docker single-node mode. I tried to use the backup data before K3S upgrade to restore, but the problem still exists, and now upgrade and rollback are not available.

**Comment by dweomer** [comment]
@yl-yue apologies on the slow response. Is this issue still a problem for you?

**Comment by yl-yue** [comment]
Yes, it hasn't been resolved. I couldn't get him to stop leveling up, and I couldn't get him to succeed.
