### ISSUE TITLE
Google cloud credential not available on v2.5

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#31983]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

From v2.5-head, navigate to Cloud Credentials -> Add Cloud Credential -> Cloud Credential Type

**Result:**

Google is not on the list.

**Other details that may be helpful:**

On master, Google is an available cloud credential type: 

![rancher-master-cc](https://user-images.githubusercontent.com/1220710/114053496-d9d86380-9843-11eb-809a-67e5a4ac378c.png)

But not so on v2.5:

![screenshot-2 5-cc](https://user-images.githubusercontent.com/1220710/114053565-e78de900-9843-11eb-9f1b-ba0ee710ec3e.png)

Even though googleCredentialConfig is part of the cloudcredential API schema:

![screenshot-2 5-cc-api](https://user-images.githubusercontent.com/1220710/114053651-ff656d00-9843-11eb-8c52-43d28fb2c933.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-dev
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
Haven't merged into 2.5 yet, will be soon.

https://github.com/rancher/ui/pull/4505

**Comment by westlywright** [comment]
In latest2 and will be in rc3+.

**Comment by prabalsharma** [comment]
I was able to create CC on 2.5-head-7426ba83e using UI and checked the created secret using kubectl
