### ISSUE TITLE
[monitoring v2] cannot install newest version 14.5.100-rcXX

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31991]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* try to install version 14.5.100-rcXX (rc 00 or 01)

**Result:**
CRD fails to install (see log for details)

[monitoring-crd.log](https://github.com/rancher/rancher/files/6280838/container.2.log)

**Other details that may be helpful:**
workaround: reinstall monitoring, then quickly delete the job for the crd
workaround: install older version, then upgrade to latest

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8-rc2
- Installation option (single install/HA): tested on both

**Comment by aiyengar2** [comment]
This issue should also test windows clusters, re: https://github.com/rancher/rancher/issues/31993

**Comment by slickwarren** [comment]
the CRD deployment now completes successfully on 14.5.100-rc03. However there are other issues related to install https://github.com/rancher/rancher/issues/32024

**Comment by aiyengar2** [comment]
Re-opening this ticket since the fix pushed in https://github.com/rancher/charts/pull/1093 causes CRs installed onto the cluster to also be wiped out on a Helm upgrade. This would be a critical bug since it would cause Prometheus and Alertmanagers that are deployed on a Cluster to be completely wiped out on an upgrade and needs to be rolle

**Comment by aiyengar2** [comment]
Note: This issue's fix as also did to https://github.com/rancher/rancher/issues/32025 and https://github.com/rancher/rancher/issues/31993, so we should make sure those use cases also pass when testing this re-opened ticket.

**Comment by aiyengar2** [comment]
The bug introduced in the fix is related to https://github.com/rancher/rancher/issues/32225, so this issue should address that as well when fixed.

**Comment by slickwarren** [comment]
reopened other issues appropriately (linked above) based on testing on v2.5.8-rc9:

* the default use case on linux appears to be working fine (clean install of monitoring)
