### ISSUE TITLE
After Rancher upgrade new clusters are up but the nodes will be stuck at "waiting to register"

### ISSUE THREAD

**Issue by ranchersvet** [rancher/rancher#31999]
We tried upgrading to Rancher 2.5.X for the second time and it still didn't work. We encountered more issues than the first time we tried.

We tried upgrading from Rancher 2.4.8.

Information that might help: we run Rancher on Kubernetes as a Deployment with 2 replicas.

## Timeline

I will provide the original markdown file of the issue, it is much easier to read.
Time in EST

* 18:20: Deployment of the new Rancher version (2.5.8-rc1)
*  operators are reading through the Rancher logs and observing multiple Kubernetes resources being migrated during the upgrade process.
* 18:44: Migrations look to be done,  operators try to create some Kubernetes clusters.
* 19:00: Clusters are up but the same issue from 2.5.5 is happening, where the nodes will be stuck at "waiting to register", although nodes were created and the agent is configured and connected to Rancher, yet Rancher hasn't instructed the agent to move forward.
*  operators are investigating.
* 19:15:  operators restart all of the kube-apiserver to try and unblock Rancher, since restarting the server seems to fix the issue where Rancher instructs no action to the agents. Clusters provisioning seems to progress a little bit (some instructions are sent to the agents) but get stuck again.
* 19:20:  operators restart Rancher and they still observe the same behavior of clusters stuck. The new cluster creation is showing the same issue.
* 19:45:  operators decide to run the logs-collector script on all of the nodes to make sure that we collect some information to provide to Rancher support while the issue still happens. This is before they attempt a rollback.
* Go pprof information is collected from the Pod that holds most of the operations.
* 20:00:  operators decide to rollback to 2.4.8 after finding inconclusive evidence of what might have affected the upgrade leaving cluster creation stuck.
* 20:14: Deployment is started, image rollback is successful.
* 20:20: The ETCD database start filling up very quickly
* 20:30: The ETCD database reach the default limit of 2GB per host. ETCD is now read-only.
* 20:35: The operators decide to increase the maximum size of the ETCD database to 8GB using the `--quota-backend-bytes` option since `kubectl` operations that modify resource state are failing because of ETCD being read-only.
* 20:45: The ETCD is back online but the database size keeps increasing to 2.4GB and then becomes stable.
* 20:52:  operators now have issues authenticating with the kube-apiserver. They now decide to restore from an ETCD backup prior the upgrade to 2.5.8-rc1.
* The authentication error message seen was: `Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver, verb=get, resource=nodes, subresource=proxy)`
* The ETCD restore was done with kube-apiserver deactivated. The rancher was not able to be scaled down due to the previous error.
* 21:30: ETCD restore is done,  operators restart the kube-apiserver.
* 21:40:  operators works on restoring the Cluster services.
* 21:50: Rancher is now back up and running correctly, users cluster have now reconnected to Rancher.
*  operators tries creating clusters. It is not working, very similar issues than the 2.5.8-rc1 upgrade.
* 21:57:  operators see some logs about some conflicting information between the Rancher pods, they decide to scale down Rancher to 1 pod.
* A theory was being proposed since operators saw that Rancher's operator "list" process was getting stuck but we couldn't find concrete evidence. This was seen both in the new 2.5.8 version as well as after the downgrade.
* A second theory that was analyzed was that Rancher might potentially be fighting against itself while having 2 pods, which could explain the previous bullet point as the "list" being mangled by both pods. To test this theory, operators decided to scale down the pod to 1.
* 22:04: New clusters are now unblocked and are coming up correctly.
* 22:10:  operators continue validating that we can create/remove and scale/downscale a cluster.
* Everything seems to be working correctly. We no longer see clusters being created, establishing the websocket connection and just hang in a pending state waiting for Rancher to send instructions after the downscale to 1 pod.
* 22:27: Rancher outage is closed and Rancher is backup and running correctly.
* 22:30: Clean up inside the cluster to make sure that it is tidy before the night.

## The issue that made us rollback

We had the same issue twice, the first time after trying to upgrade to 2.5.5 in January, and now when we tried to upgrade to 2.5.8-rc1 from 2.4.8.

We were able to create clusters. Node was provisioned but Rancher is stuck waiting for the node to register.

Using the Rancher CLI we were able to SSH on the nodes.

On these nodes, docker was running and only 1 container was Active. The rancher-agent, which was not running from Kubernetes itself, it seemed to have been deployed on docker (using the randomized docker name, as usual). From the logs we saw from that container, it seemed ready to receive information from Rancher because it successfully connected to the Rancher WebSocket.

When doing docker ps -a we saw that the share-mnt container had run, but the output was different than from a container that was created using Rancher 2.4.8.

But this doesn't seem to be the problem.

That was the case on any cluster we created trying to reproduce the issue.

## Issue after the rollback and etcd restore

This issue described in the timeline happened after having rollbacked the Rancher version to 2.4.8, restoring the etcd database and after Rancher filled the etcd database.

It was very similar to the issue we had on Rancher 2.5.5/2.5.8-rc1. The difference was that the share-mnt container was not deployed on the node.

What we did to fix that issue was to scale down Rancher from 2 to 1 pod. We decided to do that because we saw some conflicting information from both Rancher pods related to the new clusters.

See these logs for example:

$ kubectl logs -n cattle-system rancher-5b9d47dbbf-ct6lx -c rancher |grep c-2bswz
2021/03/24 01:52:29 [WARNING] error updating ns c-2bswz status: Operation cannot be fulfilled on namespaces "c-2bswz": the object has been modified; please apply your changes to the latest version and try again
2021/03/24 01:53:39 [INFO] Handling backend connection request [c-2bswz:m-x72jt]

$ kubectl logs -n cattle-system rancher-5b9d47dbbf-glxsx -c rancher |grep c-2bswz
2021/03/24 01:52:29 [INFO] [mgmt-cluster-rbac-delete] Creating namespace c-2bswz
2021/03/24 01:52:29 [INFO] [mgmt-cluster-rbac-delete] Creating Default project for cluster c-2bswz
2021/03/24 01:52:29 [INFO] [mgmt-cluster-rbac-delete] Creating System project for cluster c-2bswz
2021/03/24 01:52:29 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-2bswz
2021/03/24 01:52:29 [INFO] [mgmt-project-rbac-create] Creating creator clusterRoleTemplateBinding for user u-ndz6c4bwfl for cluster c-2bswz
2021/03/24 01:52:29 [INFO] [mgmt-auth-crtb-controller] Creating clusterRole c-2bswz-clusterowner
2021/03/24 01:52:29 [INFO] [mgmt-auth-crtb-controller] Creating clusterRoleBinding for membership in cluster c-2bswz for subject u-ndz6c4bwfl
2021/03/24 01:52:29 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-2bswz
2021/03/24 01:52:29 [INFO] [mgmt-auth-prtb-controller] Creating clusterRole c-2bswz-clustermember
2021/03/24 01:52:29 [INFO] [mgmt-auth-crtb-controller] Creating role cluster-owner in namespace c-2bswz
2021/03/24 01:52:29 [INFO] [mgmt-auth-prtb-controller] Creating clusterRole c-2bswz-clustermember
2021/03/24 01:52:29 [INFO] [mgmt-auth-prtb-controller] Creating clusterRoleBinding for membership in cluster c-2bswz for subject u-ndz6c4bwfl
2021/03/24 01:52:29 [INFO] [mgmt-auth-prtb-controller] Creating role project-owner in namespace c-2bswz
2021/03/24 01:52:29 [ERROR] ProjectRoleTemplateBindingController p-sktnn/creator-project-owner [mgmt-auth-prtb-controller] failed with : clusterroles.rbac.authorization.k8s.io "c-2bswz-clustermember" already exists
2021/03/24 01:52:29 [INFO] [mgmt-auth-prtb-controller] Updating clusterRoleBinding clusterrolebinding-m78b8 for cluster membership in cluster c-2bswz for subject u-ndz6c4bwfl
2021/03/24 01:52:29 [INFO] [mgmt-cluster-rbac-delete] Updating cluster c-2bswz
2021/03/24 01:52:30 [INFO] Creating jail for c-2bswz
2021/03/24 01:53:39 [INFO] Creating jail for c-2bswz
Once we saw this error: error updating ns c-2bswz status we decided to scale down the Rancher pods to 1. The clusters that were stuck were all unstuck following this operation and were subsequently provisioned correctly.
gz#16062
gz#15796

**Comment by vijaytrainer** [comment]
+1, similar behaviour experienced on v2.5.7

**Comment by rlio** [comment]
+1 same behaviour

**Comment by leisurelyclouds** [comment]
select all role will be success

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 7002499
rancher/rancher:master-head fffd630

* Reproduced in v2.5.7
* Using [rancher2-scaling](https://github.com/rancher/rancher2-scaling) framework, added 150 clusters to the server
* Around 100 clusters, the imported clusters would become active with provider information (K3S version) populated, but show no nodes
* Added two nodedriver (ec2) clusters and they were stuck in `waiting to register`
* Upgraded to v2.5-head
* After upgrading, the affected clusters completed provisioning
* Add another 150 clusters and the clusters all registered correctly

In fresh installs for both `v2.5-head` and `master-head` added 200 clusters and all clusters provisioned successfully.

**Comment by dramich** [comment]
https://github.com/kubernetes/client-go/issues/973

**Comment by dramich** [comment]
https://github.com/rancher/rancher/pull/32870

**Comment by jiaqiluo** [comment]
available for testing in rancher `v2.5.9-rc1`

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.9-rc3

We performed a smoke test to validate the behavior of the fix on a smaller scale, and the user's upgrade was successful using `v2.5.9-rc3`

In v2.5.8:
* Create 300-600 custom clusters (with no nodes backing)
* Some clusters would get stuck in a pending provisioning state with no status message: `Waiting for etcd, controlplane and worker nodes to be registered`
* After a few minutes these would continue to the correct state (but takes longer with more clusters)
![Screen Shot 2021-06-22 at 11 14 46 AM](https://user-images.githubusercontent.com/21316915/123128912-608eec80-d400-11eb-9a80-5abf793edc5c.png)


In v2.5.9-rc3
* Created 450 custom clusters (with no nodes)
* All clusters correctly went into the correct state
