### ISSUE TITLE
[monitoring v2] windows rancher-monitoring-crd-create in crashloopback on clean install of 14.5.100-rcX

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31993]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy a downstream windows cluster
* follow steps in https://github.com/rancher/rancher/issues/31991 for workaround to install latest version of monitoring
* deploy monitoring v2 v14.5.100-rc1 or rc0
  * enable windowsExporter on install

**Result:**
<img width="1790" alt="Screen Shot 2021-04-08 at 3 21 26 PM" src="https://user-images.githubusercontent.com/16691014/114104987-bf70ab00-9880-11eb-8781-9e2f231e2c71.png">
* this pod fails with `for: "/etc/config/crd-manifest.yaml": CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema` full logs below
[full-logs.log](https://github.com/rancher/rancher/files/6281953/container.3.log)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8-rc2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Windows
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
- Kubernetes version (use `kubectl version`): v1.20.5

- Docker version (use `docker version`): 20.10.5

**Comment by aiyengar2** [comment]
Closing this out in favor of https://github.com/rancher/rancher/issues/31991, which should also test windows clusters.
