### ISSUE TITLE
[monitoring v2] windows monitoring-windows-exporter pods in crashloopback: failed to connect to proxy

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31994]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy downstream windows cluster
* follow steps in https://github.com/rancher/rancher/issues/31991 for workaround to install latest version of monitoring
* deploy monitoring v2 v14.5.100-rc1 or rc0
  * enable windowsExporter
 

**Result:**
```
INFO[2021-04-08T22:44:57Z] Connecting to proxy                           url="ws://rancher_wins_proxy"
ERRO[2021-04-08T22:44:57Z] Failed to connect to proxy. Empty dialer response  error="open \\\\.\\pipe\\rancher_wins_proxy: The system cannot find the file specified."
FATA[2021-04-08T22:44:57Z] open \\.\pipe\rancher_wins_proxy: The system cannot find the file specified.
```
2/3 windows worker nodes fail to connect with the above error
<img width="1293" alt="Screen Shot 2021-04-08 at 3 44 57 PM" src="https://user-images.githubusercontent.com/16691014/114105487-b207f080-9881-11eb-8964-ec5b72e61836.png">
<img width="1792" alt="Screen Shot 2021-04-08 at 3 22 38 PM" src="https://user-images.githubusercontent.com/16691014/114105501-b9c79500-9881-11eb-9782-10b11d382766.png">

**Other details that may be helpful:**
targets are also down
<img width="1710" alt="Screen Shot 2021-04-08 at 4 20 20 PM" src="https://user-images.githubusercontent.com/16691014/114107709-60159980-9886-11eb-8155-d505a2713bcc.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  v2.5.8-rc2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): windows
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 1.20.5

- Docker version (use `docker version`): 20.10.5

**Comment by aiyengar2** [comment]
Since this problem only shows up in the workaround which is not the suggested way for users to be able to install the chart (i.e. quickly deleting the CRD job could leave CRDs in a weird state, which is definitely not recommended for users to ever do), I'm closing out this issue in favor of https://github.com/rancher/rancher/issues/31991 as well.
