### ISSUE TITLE
Longhorn images not included in rancher-images.txt

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31995]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* download the https://github.com/rancher/rancher/releases/download/v2.5.8-rc2/rancher-images.txt file 
* search for any image using `longhorn`

alternative way to test:
* setup private registry using https://github.com/rancher/rancher/releases/download/v2.5.8-rc2/rancher-images.txt for image list
* deploy rancher setting the private registry from above as the global private registry
* deploy a downstream cluster (deploys correctly)
* go to apps & marketplace
* deploy longhorn with default settings

**Result:**
* rancher-images.txt does not contain any longhorn images

* deployment of longhorn will not pull any images for longhorn i.e. `rancher/mirrored-longhornio-longhorn-manager:v1.1.0`
<img width="1124" alt="Screen Shot 2021-04-08 at 4 16 30 PM" src="https://user-images.githubusercontent.com/16691014/114107445-e2518e00-9885-11eb-8ba8-eb17a4bf42f3.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8-rc2
- Installation option (single install/HA): single

**Comment by cbron** [comment]
These do exist in 2.5.7, so it was a recent change. cc @PennyScissors also

**Comment by slickwarren** [comment]
on v2.5.8-rc10,  longhorn is now able to install through a private registry without any issues with images. below is a screenshot of the longhorn images that were missing last time on an airgapped setup
<img width="1101" alt="Screen Shot 2021-04-27 at 12 51 03 PM" src="https://user-images.githubusercontent.com/16691014/116304355-54b3e080-a757-11eb-9609-eae86335e841.png">
