### ISSUE TITLE
Grafana graphs showing `value`, but should show instance

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31990]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* deploy monitoring v2
* navigate to grafana homepage

**Result:**
<img width="563" alt="Screen Shot 2021-04-08 at 12 03 46 PM" src="https://user-images.githubusercontent.com/16691014/114094504-3e5de780-9871-11eb-995c-5e706478d2ab.png">
* `value` should be the instance that the data is being collected from 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8-rc2
- Installation option (single install/HA): HA

**Comment by aiyengar2** [comment]
Closing this issue out in favor of https://github.com/rancher/rancher/issues/31921, which should address this as a test case within it.
