### ISSUE TITLE
environment means different things in Audit Log and Processes page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3199]
Version - master Jan 07

Comment:
In the Audit Log, environment actually refers to Environment events.  But in the Processes page, it refers to the Stack events.  This is very confusing.

This is probably not a UI issue and something not easily fixed, but I think we should make an effort to fix it.

**Comment by vincent99** [comment]
APIv2.. The audit log is showing API resources and that's what they're actually called.

**Comment by vincent99** [comment]
Need api v1.1 for this..

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre3, events for stack now start with stack. instead of environment.
Verified fixed
