### ISSUE TITLE
Add ability to specify IP used for External DNS programming

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#3201]
Currently, Rancher DNS (Route 53, CloudFlare, any other external DNS service) only programs the host IP to where the container of a service lands.  The problem comes when a host has multiple networks and Rancher is only capable of configuring a single IP for establishing the overlay ipsec network.  The most common setup is when a host has both a public and private network and uses the private network to establish Rancher's managed network and wants to expose/publish services using an External DNS via the public network.  In this case, Rancher has no idea what the public IP of the host is.

A way to do this is to allow the agents to be installed with another ENV variable that specifies the IP that should be used for External DNS.

**Comment by mcuadros** [comment]
+1

**Comment by CBR09** [comment]
+1 for this

**Comment by alejom99** [comment]
+1

**Comment by gcallsen** [comment]
+1!

**Comment by Mackaber** [comment]
+1

**Comment by tombmurphy** [comment]
+1
this would be very useful on EC2 for example using EIPs.

**Comment by mrproper** [comment]
Even if the dns service took a label name to use which contained the public ip of the host would be useful

**Comment by alena1108** [comment]
@mrproper I don't think that would work as you can have multiple hosts in the system, and you will have to keep track which public ip address is assigned to which host. Plus the hosts can be added to Rancher after dns service is already deployed

**Comment by mrproper** [comment]
@alena1108 Thats my point
When you add a host add a label as part of that say "dns_ip" the dns service when making state changes looks up that label (or some other specified label) and will use that otherwise falling back to the cattle agent ip. either this or just another environment variable for the agent like CATTLE_AGENT_IP

**Comment by alena1108** [comment]
@mrproper label on the host makes sense

**Comment by taketnoi** [comment]
+1

**Comment by alena1108** [comment]
@prachidamle during the host registration, ip address for external dns is going to be provided in host labels section. Host labels are already being propagated to metadata, so external-dns should just read it from there. If label is not found, or empty, the ip address should be set to Host ip as before.

Will update the bug with the label name as soon as its finalized.

**Comment by sangeethah** [comment]
Tested with latest build from master and "Route53 DNS" version- v0.3.0-rancher1.
Able to set io.rancher.host.external_dns_ip when registerting host .
Ip specified in this host label is being used when Route53 rules get created by "Route53 DNS" service.

Following 2 issues  are logged to track more support for this feature - https://github.com/rancher/rancher/issues/4067 and https://github.com/rancher/rancher/issues/4067
