### ISSUE TITLE
[Forwardport]Private Registry authentication with no credentials fails

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32012]
Forwardport of rancher/rancher#31600

**Comment by sowmyav27** [comment]
@slickwarren Can we test this using 2.5.8 images.txt file ?

**Comment by slickwarren** [comment]
the following was tested on master-head (744c23307d61bd5e0951a1a6c76f32335f8011fa):
Cluster level Private Registry
* Node driver cluster with Priv reg with no Auth
* Custom cluster with Priv reg with no Auth

Global Level Private Registry
* Node driver cluster with Priva reg with no Auth
* Custom cluster with Priva reg with no Auth
