### ISSUE TITLE
Back-off pulling image "rancher/library-nginx:1.19.9-alpine"

### ISSUE THREAD

**Issue by kravciak** [rancher/rancher#32010]
To reproduce:

 - spin up a cluster in 2.5.8-rc2 (used rancher-v3_ontag_windows_certification job) 
 - deploy wins-upgrader without masquerading (default)
 - enable Monitoring V1

prometheus-cluster-monitoring-0 pod not starting because of
```
ImagePullBackOff: Back-off pulling image "rancher/library-nginx:1.19.9-alpine"
```

Quick workaround is to change pod and set image to library-nginx:1.19.2-alpine.

**Comment by aiyengar2** [comment]
@kravciak all of these images should be prefixed with mirrored- as well when we test this

**Comment by aiyengar2** [comment]
@kravciak I talked to @rmweir offline and we agreed that we'll keep the task of making all the images mirrored- in https://github.com/rancher/rancher/issues/31871. For this change, we only will expect the nginx image to be pointing to the mirrored- repository.

cc: @sowmyav27

**Comment by kravciak** [comment]
Works fine on 2.5.8-rc3, image now comes from `rancher/mirrored-library-nginx:1.19.9-alpine`
