### ISSUE TITLE
[Logging v2] Collect RKE node logs on Windows

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#32021]
Application logs live in `\var\log\containers`, but node logs (kubelet, etc.) live in `\var\lib\rancher\rke\log`. We need to ingest and process these as well.

Relevant issue: https://github.com/rancher/rancher/issues/28721

**Comment by nickgerace** [comment]
How this implementation will works: https://github.com/rancher/charts/pull/1104#issuecomment-817027090

**Comment by nickgerace** [comment]
What logs need to be collected: https://github.com/rancher/charts/pull/1104#issuecomment-817035989

**Comment by nickgerace** [comment]
This can be tested for everything but airgap. The airgap backport PR is awaiting a passing build. 
https://github.com/rancher/rancher/pull/32061

**Comment by izaac** [comment]
@nickgerace for airgap also needs RC. But that will be tested on #32016

**Comment by izaac** [comment]
Rancher version `v2.5.8-rc2` 
Logging Chart version: `3.9.400-rc03`
Fluentd ClusterOutput.

I am now getting logs from the `/var/lib/rancher/rke/log/`
It translate to Windows path: `C:\var\lib\rancher\rke\log`
- Symlinks go to: ` C:\ProgramData\docker\containers\<folder hash>\filename.log`

**Comment by izaac** [comment]
Issue for `master-head` validation: #32070
