### ISSUE TITLE
GKEv2 CC creation gets stuck on validation, when an invalid json used

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32020]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Deploy Rancher v2.5-7426ba83ec4751e7bb664df9e5fe52329eb1129d-head
2. Add Google Cloud Credential using an invalid json eg: {asdasdasd} or sadasdsad or {key:value}
3. Click create

**Result:**
Gets stuck on `Validating Keys`, instead of showing an error
<img width="1013" alt="Screen Shot 2021-04-09 at 11 40 04 AM" src="https://user-images.githubusercontent.com/3749546/114226362-56447280-9928-11eb-8dcc-234703c7f5fa.png">

**Other details that may be helpful:**
if I provide a valid  json with wrong values, then I see an error, as expected. eg 

```
{
"key1" : "value1"
}
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cmurphy** [comment]
This seems like a UI issue to me, the browser console gives this error message:

```
VM141:1 Uncaught SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at n.fetchZones (component.js:339)
    at n.willSave (component.js:258)
    at n [as willSave] (index.js:443)
    at n.save (new-or-edit.js:54)
    at e.n._join (backburner.js:1079)
    at e.n.join (backburner.js:790)
    at d (index.js:168)
    at index.js:3698
    at o (index.js:146)
```

Not something that a backend fix would be able to address.

**Comment by prabalsharma** [comment]
passed on v2.5-a5d9602ce1f264764b22e26a2425f99cb812cf97-head
merged to master
