### ISSUE TITLE
[Cluster-Manager] No Access to Cluster Registration Command After Adding First Node

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#32031]
**What kind of request is this (question/bug/enhancement/feature request):**
need to be able to add additional nodes after adding your first to a custom cluster

**Steps to reproduce (least amount of steps as possible):**
* Create custom cluster, see registration token
* copy/paste token into server
* after one node is added the "get registration command" button disappers
* try and add a second node

**Result:**
registration token used to be in the cluster edit screen and is now moved to a step two in the create cluster process and what seems to be a button which appears when no nodes are in a cluster. need a way to bring up the same cluster registration command in the UI to add additional nodes.

**Other details that may be helpful:**

**Environment information**
this is happening now in latest UI for 2.5-head and master

- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by kravciak** [comment]
I replicated the issue on rancher v2.5.8-rc2.
Fix is working fine on on v2.5 (41f173a) and master-head (1c3629f).

After registering first node `Registration Cmd` button is still available in cluster menu.
I added worker node with this cmd, worked fine as well.
