### ISSUE TITLE
Upgrades to an equal semver are not allowed

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#32034]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Description:**
Wondering if we can have rancher only block strict semver downgrades but allow a "grade change" when it compares equal. There's probably more to this than initially meets the eye, but could be helpful for situations such as mentioned below.

**Steps to reproduce (least amount of steps as possible):**
Try to "upgrade" to an equal semver version, for example from v1.18.17+k3s1 to v1.18.17-alpha1+k3s2. 

**Result:**
Currently blocked by the api: `cannot upgrade cluster version from [v1.18.17+k3s1] to [v1.18.17-alpha1+k3s2]. New version must be higher.`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7

**Comment by davidnuzik** [comment]
This would help out QA if we are able to prioritize this
