### ISSUE TITLE
Logger V2 throwing a lot of error for  wrong time format

### ISSUE THREAD

**Issue by maxisam** [rancher/rancher#32040]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

just install logging 3.9.0000 from Rancher

**Result:**

There are tons of errors from rancher-logging-rke-aggregator console like 

[2021/04/11 05:49:51] [error] [parser] cannot parse '2021-04-11T05:49:51.218507225Z'
[2021/04/11 05:49:51] [ warn] [parser:json] invalid time format %d/%b/%Y:%H:%M:%S %z for '2021-04-11T05:49:51.218507225Z'

**Other details that may be helpful:**

rancher/mirrored-fluent-fluent-bit:1.6.10

**Environment information**
- Rancher version 2.5.7
- Installation option (single install/HA): HA

**Comment by serverbaboon** [comment]
I had the same issue , I just upgraded ti logging 3.9.400 and the issue seems to be fixed.
