### ISSUE TITLE
Failed rancher-gatekeeper 3.3.0 installation on private access EKS cluster

### ISSUE THREAD

**Issue by giuseppeCozzolino** [rancher/rancher#32049]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create EKS cluster with Private Access
2. Access Cluster Explorer and install OPA Gatekeeper v3.3.0 
3. rancher-gatekeeper-crd:3.3.000 successfully installed
4. rancher-gatekeeper:3.3.000 installation failed after 10 mins

<img width="1791" alt="Schermata 2021-04-12 alle 15 30 27" src="https://user-images.githubusercontent.com/77336342/114402354-05d94900-9ba4-11eb-9904-2f0fd7427ea2.png">

<img width="1781" alt="Schermata 2021-04-12 alle 15 31 09" src="https://user-images.githubusercontent.com/77336342/114402536-37521480-9ba4-11eb-9af0-67b90f403fbd.png">

<img width="1513" alt="Schermata 2021-04-12 alle 15 32 17" src="https://user-images.githubusercontent.com/77336342/114402636-50f35c00-9ba4-11eb-9d9c-484208fac613.png">

**Result:**
Installation successful like for EKS cluster with Public Access

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.7
- Installation option (single install/HA):all
- 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3 nodes t3.large ASG: desired 3 minimum 2 maximum 5
- Kubernetes version (use `kubectl version`):

**Comment by prachidamle** [comment]
Seems to be some conflicts with the priorityClass settings for the cluster. The gatekeeper helm chart mentions that the pods have been start with `system-cluster-critical` priorityClass. Does the cluster not allow this? 
Similar issue found here https://github.com/rancher/rancher/issues/32049

**Comment by giuseppeCozzolino** [comment]
@prachidamle thanks for the answer.
I didn't put the system-cluster-critical priorityClass. It's done automatically by Rancher.
Is it probably related to the private access selection?
Testing the same cluster configuration but with Public Access it works fine.
