### ISSUE TITLE
rancher/rke2-upgrade images are missing from rancher-images.txt

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#32051]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Rancher uses the `rancher/rke2-upgrade` images to upgrade a RKE2 cluster from the Rancher UI with the system-upgrade-controler.
These images are missing from the published rancher-images.txt images list, which is used in air-gapped setups to pull all necessary Rancher images into a private registry.
Of course these images can be pulled manually, but it would be nice to have them included to make air-gapped RKE2 + Rancher setups easier.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.7
- Installation option (single install/HA): HA, air-gapped

**Comment by cbron** [comment]
This may not be fixed as-is, but rather as the new provisioning framework will address it. This use case should be tested either way.

**Comment by ron1** [comment]
@cbron this issue is relevant to 2.5.x as well as 2.6. As such, would it be possible to add milestone 2.5.9 to this issue in addition to 2.6?

**Comment by cbron** [comment]
Related to: https://github.com/rancher/rancher/issues/32403

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by bashofmann** [comment]
Looks good, the `rancher/rke2-upgrade` image is part of the `rancher-images.txt`.

**Comment by slickwarren** [comment]
on v2.6.0-rc1:
* rancher/rke2-upgrade:v1.21.3-rc3-rke2r2 is included in rancher-images.txt
