### ISSUE TITLE
Remove Docker 1.10 Cli from Agent

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#32052]
per request of @ibuildthecloud and some feedback we received from docker, we need to stop abusing the docker 1.10 client binaries.

**Comment by kravciak** [comment]
Works fine on master-head (66c31dd) and 2.5-head (e9c4413)
Docker is removed from linux agent container, windows containers still have it (as expected)

I am not creating separate ticket for 2.5-head since it will be probably reverted.
