### ISSUE TITLE
Rancher DNS should *always* resolve

### ISSUE THREAD

**Issue by spicykaiju** [rancher/rancher#3205]
In response to #3100 and #2873, can you please consider Rancher DNS *always* resolving registered services and containers no matter of service and/or container placement? To be clear, if the Rancher DNS service is queried from anywhere, it will always resolve any given service and container FQDN that it has registered records for.

I understand the idea of adding in resolution logic between containers/services that are not linked, however I think that this provides very little benefit vs. the added complexity. This is especially problematic for services external to Rancher.

It would be helpful to understand why this design decision was made. Thanks!

**Comment by deniseschannon** [comment]
Once we implement https://github.com/rancher/rancher/issues/2817, your requests should be satisfied. 

@alena1108 will be adding more details on how it will work in that issue.

**Comment by spicykaiju** [comment]
that's great, thanks!
