### ISSUE TITLE
GKEv2 UI, Doesn't show node pools for registered clusters

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32060]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Register a GKE cluster with node pools
2. Go to edit cluster:

<img width="1362" alt="Screen Shot 2021-04-12 at 12 08 03 PM" src="https://user-images.githubusercontent.com/3749546/114447885-be44c400-9b87-11eb-8140-6eb33e34d9a1.png">

I don't see  any node pools

**Result:**
I can see node pools in API:
<img width="659" alt="Screen Shot 2021-04-12 at 12 09 24 PM" src="https://user-images.githubusercontent.com/3749546/114448054-ee8c6280-9b87-11eb-8e33-848d193deee5.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-6f71d4c7346c63a60c671d59185e1595fe826ac7-head
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cmurphy** [comment]
I think the problem is in the UI merging the upstream and downstream attributes, specifically here: https://github.com/rancher/ui/blob/cfd4dfa03f6a6bef36a404a85df14501c4513fe3/app/models/cluster.js#L1024-L1030

The field is called `nodePools` for GKE, not `nodeGroups`.
