### ISSUE TITLE
[Logging v2] Validate chart 3.9.4 on master-head

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32062]
**What kind of request is this:**
qa

**Steps to reproduce :**

- Install the latest 3.9.4 Logging chart on master-head and validate P0 scenarios.

**Other details that may be helpful:**

Original issue: https://github.com/rancher/rancher/issues/31644
Coverage of `v2.5-head` RKE1 was done in the referenced issue.

**Comment by sowmyav27** [comment]
After an offline discussion, closing this as we will not be validating chart changes separately for master-head
