### ISSUE TITLE
[Logging v2] - aggregator should not write to the host for rke and rke2 on master

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32063]
**What kind of request is this:**
Validate rancher/rancher#31309 on `master-head`

**Steps to reproduce (least amount of steps as possible):**

- Referenced issue had validation blocked on downstream clusters due to: rancher/rancher#31964
- RKE1 was validated on `v2.5-head` rancher/rancher#30949

**Comment by sowmyav27** [comment]
After an offline discussion, closing this as we will not be validating chart changes separately for master-head
