### ISSUE TITLE
GKE v2 UI, cannot Edit a registred cluster 

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32068]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Register a GKE cluster with node pools
2. Go to edit cluster
3. Upgrade k8s verion
4. Click Save

**Result:**
The Edit will gets stuck in `Saving` state

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-6f71d4c7346c63a60c671d59185e1595fe826ac7-head
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cmurphy** [comment]
This is a UI issue, it's not handling the possibility that most attributes of a registered cluster will be null:

```
Uncaught TypeError: Cannot convert undefined or null to object
    at n.willSave (component.js:600)
    at n [as willSave] (index.js:443)
    at n.driverSave (cluster-driver.js:53)
    at e.n._join (backburner.js:1079)
    at e.n.join (backburner.js:790)
    at d (index.js:168)
    at index.js:3698
    at o (index.js:146)
    at index.js:3697
    at n.save (index.js:3659)
```

component.js:

```
599      if (!Ember.get(config, 'masterAuthorizedNetworks.enabled')) {
600        delete config.masterAuthorizedNetworks.cidrBlocks;
601      }
```

**Comment by prabalsharma** [comment]
passed on v2.5-4e70ed29ccc5de7c61516ba0367c7c4904989b56-head
