### ISSUE TITLE
[Logging v2] Collect RKE node logs on Windows on master

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32070]
**What kind of request is this:**
QA

**Steps to reproduce:**
- Validate rancher/rancher#32021 on master

**Result:**

testing done on `v2.5.8-rc2`: https://github.com/rancher/rancher/issues/32021#issuecomment-818301480

values yaml (Edit as YAML during Logging chart install)
We need to make sure `additionalLoggingSources.rke.enabled` is `true`
`global.windows.enabled` should be `true`

These values need fix on dashboard
rancher/rancher#2626

**Comment by sowmyav27** [comment]
Closing this as testing on master is not required.
