### ISSUE TITLE
Logging V2] Windows Support on master

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32077]
**What kind of request is this:**
QA

**Steps to reproduce:**

Validate this on master (2.6): https://github.com/rancher/rancher/issues/28721

### This was done on `v2.5`

Rancher version `v2.5.8-rc2` 
Logging Chart version: `3.9.400-rc03`
Fluentd ClusterOutput.
Windows 2019 (1809)

Logs from `C:\var\log\containers` are collected. I see logs in the clusteroutput also using a Windows webserver app.
RKE logs from `C:\var\lib\rancher\rke\log` are collected too using the `additionalLoggingSources.rke.enabled=true` 
Ran into this issue: https://github.com/rancher/rancher/issues/32074

**Comment by sowmyav27** [comment]
After an offline discussion, closing this as we will not be validating chart changes separately for master-head
