### ISSUE TITLE
system project pod restarts in a HA rancher server setup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32081]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a HA rancher setup. The rancher nodes - t3a.medium AWS instances.
- Deployed a 5 node custom cluster and a GKE hosted cluster (Stuck in provisioning with an error)
- Noticed the following pods in System project have many restarts

```
rancher, cert-manager, cert-manager-cainjector, cert-manager-webhook, Fleet agent/controller, gitjob, ingress-controller, canal, metrics server.
```

**Other details that may be helpful:**
- Rancher seems unusually slow. Like accessing projects in a cluster/dashboard
- I dont see it on a new version of rancher - b75af2a31 2.5head and with t3.xlarge nodes. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `6bb6c97e`
- Installation option (single install/HA): HA

**Comment by SheilaghM** [comment]
2 CPU and 4 GB of memory is very small. The smallest we recommend is 2 CPU and 8 GB RAM. t3.large is the smallest we should test with. It looks like the host was running out of memory per Dan.

**Comment by sowmyav27** [comment]
Closing this based on the requirements in docs - https://rancher.com/docs/rancher/v2.x/en/installation/requirements/#rke-and-hosted-kubernetes
