### ISSUE TITLE
Unknown error Get https://10.96.0.1:443/api/v1/xxxxxx?timeout=30s net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by godocean** [rancher/rancher#32085]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
choose and click a project in a cluster from rancher UI

**Result:**
get red error message from up right in the UI
![image](https://user-images.githubusercontent.com/17870432/114547496-16b3b880-9c91-11eb-91dc-6c47a6bd7678.png)
From output of rancher pod I also catch error log as below:

[ERROR] Unknown error: Get https://10.96.0.1:443/api/v1/namespaces?timeout=30s: net/http: TLS handshake timeout

**Other details that may be helpful:**
This kind of error not happen all the time, but more and more frequent recently,
The imported cluster itself works well in the master node with kubectl command, but error happened when using rancher to manage it.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 101 VM with 8c/32G
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by godocean** [comment]
Is there anyone met the same issue? I think it should be very common...

**Comment by wangfeng-1** [comment]
> Is there anyone met the same issue? I think it should be very common...

I have the same problem

**Comment by wangfeng-1** [comment]
> > Is there anyone met the same issue? I think it should be very common...
> 
> I have the same problem

I have three clusters, dev, test, and prod. They are in different public clouds. There is no problem with dev and test, but there is a problem with prod. I suspect it is a network problem, so I won't confirm it for the time being.

**Comment by hectoralicea** [comment]
I have the same issue, and do not know how to fix.  
It appears one of my macs will only support TLS 1.3, and the rancher ingress will only support TLS 1.2. My other mac appears to support TLS 1.2 and connects.
 
This is the sslscan report on my 1st Mac which does NOT have TLS 1.2 enabled. Notice all the protocols disabled.
```
ha85006$ sslscan rancher.rke2-dev
Version: 2.0.9-static
OpenSSL 1.1.1k  25 Mar 2021

Connected to 3.138.69.192

Testing SSL server rancher.rke2-dev on port 443 using SNI name rancher.rke2-dev

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   disabled
TLSv1.1   disabled
TLSv1.2   disabled
TLSv1.3   disabled

  TLS Fallback SCSV:
Connection failed - unable to determine TLS Fallback SCSV support

  TLS renegotiation:
Session renegotiation not supported

  TLS Compression:
OpenSSL version does not support compression
Rebuild with zlib1g-dev package for zlib support

  Heartbleed:

  Supported Server Cipher(s):
Certificate information cannot be retrieved.

[~/ansible-playbooks/ansible-role-k8s] (master)
```

This is the sslscan report on my 2nd Mac which DOES have TLS 1.2 enabled. Notice 1.2 is enabled.
```
hector$ sslscan rancher.rke2-dev
Version: 2.0.9-static
OpenSSL 1.1.1k  25 Mar 2021
Connected to 3.138.69.192
Testing SSL server rancher.rke2-dev on port 443 using SNI name rancher.rke2-dev
  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   disabled
TLSv1.1   disabled
TLSv1.2   enabled
TLSv1.3   disabled
  TLS Fallback SCSV:
Server supports TLS Fallback SCSV
  TLS renegotiation:
Session renegotiation not supported
  TLS Compression:
OpenSSL version does not support compression
Rebuild with zlib1g-dev package for zlib support
  Heartbleed:
TLSv1.2 not vulnerable to heartbleed
  Supported Server Cipher(s):
Preferred TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  ECDHE-RSA-CHACHA20-POLY1305   Curve 25519 DHE 253
  Server Key Exchange Group(s):
TLSv1.2  128 bits  secp256r1 (NIST P-256)
TLSv1.2  192 bits  secp384r1 (NIST P-384)
TLSv1.2  260 bits  secp521r1 (NIST P-521)
TLSv1.2  128 bits  x25519
TLSv1.2  224 bits  x448
  SSL Certificate:
Signature Algorithm: ecdsa-with-SHA256
RSA Key Strength:    2048
Subject:  
Altnames: DNS:rancher.rke2-dev
Issuer:   dynamiclistener-ca
Not valid before: Apr 26 15:30:48 2021 GMT
Not valid after:  Jul 25 15:30:48 2021 GMT
[~/ansible-playbooks/ansible-role-k8s] (master)
```
any ideas on how to fix this on my mac that fails to work or how to increase the support of Rancher Ingress to support TLS 1.3 would be helpful.

**Comment by hectoralicea** [comment]
> I have the same issue, and do not know how to fix.
> < removed text>
> any ideas on how to fix this on my mac that fails to work or how to increase the support of Rancher Ingress to support TLS 1.3 would be helpful.

I found the issue.  I was trying to access this https over a Cisco AnyConnect VPN.  Once I dropped the VPN connection it started working.  Apparently the TLS2 security handshaking was detecting a "Man in the Middle", which was the VPN, and dropping the negotiation.

**Comment by godocean** [comment]
I've already found the root cause.
It's a network connection problem since my k8s cluster nodes across different datacenter, and the cattle-cluster-agent pod in this cluster was located in a different location which is not in the same location compared to the rancher control plane node. After I migrate the cattle-cluster-agent to the same location with rancher control plane node, it works again.
