### ISSUE TITLE
[log] View log repeat output

### ISSUE THREAD

**Issue by zxxf18** [rancher/rancher#32084]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Enter the rancher dashboard
Choose a deployed deployment
Click on the corresponding pod
Select view logs in the pod operation
At this time, the window will print the log normally
But after clicking the settings button in the lower right corner to select the previous container and cancel it, you will find that the console will repeatedly output the same log twice
Repeat this operation, each time the console will add the same log output

**Result:**
The same line of log will be output multiple times

**Other details that may be helpful:**
My guess is that a new data channel is established for each operation, and the identity of the channel established each time is the same, so there is a situation of data superimposition.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.5.7
- Installation option (single install/HA):single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud  cpu：2 * Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz  mem：8G
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8+k3s1", GitCommit:"6b595318666804506c19cfc3d3d228423d38fab1", GitTreeState:"clean", BuildDate:"2020-08-14T20:42:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
no docker, with containerd
```

**Comment by vincent99** [comment]
This was fixed already for 2.5.8, the old connection wasn't closed before opening a new one.

**Comment by slickwarren** [comment]
this is not reproducible on v2.5-head (7002499):
Steps to reproduce (least amount of steps as possible):
* Enter the rancher dashboard
* Choose a deployed deployment
* Click on the corresponding pod
* Select view logs in the pod operation
* At this time, the window will print the log normally
* But after clicking the settings button in the lower right corner to select the previous container and cancel it,

**Comment by sowmyav27** [comment]
PR: https://github.com/rancher/dashboard/pull/2661
