### ISSUE TITLE
Volumes section doesn't show up in Storage Pool page until refresh

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3208]
version - master jan 07

Steps:
1.  Create two hosts and add convoy.glusterfs=true as label 
2.  Create and started Gluster FS
3.  Create and started Convoy Gluster FS
4.  Go to Storage Pool page and see the Hosts section has been added
5.  Added new Stack
6.  Create Service (scale 2)
  	image - ubuntu
     	Volumes - tani:/tani1
     	Volume Driver - convoy-gluster
7.  Start service and wait for it to completely start
8.  Go to Storage Pool page

Results:
The Volumes Section is not showing up.  If I hit browser refresh button, it will appear

Expected:
Volume section should show up without having to manually refresh browser.

**Comment by tfiduccia** [comment]
This is still happening with today's master build.  Added Volumes are also not showing up until refresh.

**Comment by vincent99** [comment]
There's no change event to tell me that a volume was created (or what pool it's in)

**Comment by deniseschannon** [comment]
@tfiduccia Can you try this again? I think it's working in v1.1.0.

**Comment by tfiduccia** [comment]
Version 1.1.0
This is still broken.  Tried adding volume through service and just clicking on Add Volume and the volume did not show up until I hit refresh.

**Comment by cjellick** [comment]
This should be addressed by a combination of @ibuildthecloud's volume driver changes + @vincent99 adjusting for those changes. I'm going to assign to @vincent99.

**Comment by vincent99** [comment]
Same as #2763?
