### ISSUE TITLE
Containers cannot ping between hosts

### ISSUE THREAD

**Issue by pedrommone** [rancher/rancher#3209]
This is an fresh install of everything, from the OS to the Rancher. I've setup and VPN and some containers for testing purpose.

When I try to ping the IP `http://i.imgur.com/mevVcew.png` **(from host 10 to 11)** I get this:
```
PING 10.42.148.45 (10.42.148.45) 56(84) bytes of data.
From 10.42.0.1 icmp_seq=1 Destination Host Unreachable
From 10.42.0.1 icmp_seq=2 Destination Host Unreachable
From 10.42.0.1 icmp_seq=3 Destination Host Unreachable
From 10.42.0.1 icmp_seq=4 Destination Host Unreachable
From 10.42.0.1 icmp_seq=5 Destination Host Unreachable
From 10.42.0.1 icmp_seq=6 Destination Host Unreachable
From 10.42.0.1 icmp_seq=7 Destination Host Unreachable
From 10.42.0.1 icmp_seq=8 Destination Host Unreachable
From 10.42.0.1 icmp_seq=9 Destination Host Unreachable
From 10.42.0.1 icmp_seq=10 Destination Host Unreachable
From 10.42.0.1 icmp_seq=11 Destination Host Unreachable
From 10.42.0.1 icmp_seq=12 Destination Host Unreachable
```

if I try to ping the container `10.42.241.171` **(from host 11 to 10)** I get this:
```
PING 10.42.241.171 (10.42.241.171) 56(84) bytes of data.
^C
--- 10.42.241.171 ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 6999ms

root@11:~# ping 10.42.241.171
PING 10.42.241.171 (10.42.241.171) 56(84) bytes of data.
^C
--- 10.42.241.171 ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 8999ms
```

I've the following setup:
![Setup](http://i.imgur.com/hulIuq1.png)

Also running this rancher version:
![Rancher](http://i.imgur.com/mevVcew.png)

**Comment by pedrommone** [comment]
I've just built the setup again and things still doesnt work.

Btw, launched agents this way: `sudo docker run -e CATTLE_AGENT_IP="PUBLIC_IP" -e CATTLE_HOST_LABELS='server=10' -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.8.2 http://rancher.ezdlv.com:8080/v1/scripts/38C62E9C48A701DD4827:1452279600000:OAzE0oWF1epILaQFfBtENhk64HE`

**Comment by pedrommone** [comment]
**Solved**

Just changed `DEFAULT_FORWARD_POLICY` on `/etc/default/ufw` to `ACCEPT`. 

Its documented here http://docs.rancher.com/rancher/faqs/troubleshooting/#running-ubuntu-and-containers-are-unable-to-communicate-with-each-other

**Comment by egobude** [comment]
I had the same issue on centos today.I switched from managed to host network. Now i am able to ping between hosts. No sure if this is the right setting but it works :)

#486
