### ISSUE TITLE
Change Network Provider Dropdown to indicate PNI is available for additional RKE CNIs

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#32106]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

Related Issue: https://github.com/rancher/rancher/issues/31338

For the above issue, we are enabling Project Network Isolation for additional CNIs when provisioning an RKE cluster.

This will require a change to the UI. Currently, in the `Network Provider` dropdown, we see:
![pni-ui](https://user-images.githubusercontent.com/8824599/114623768-92e3d700-9c64-11eb-9094-c673e1a569a5.png)

This should change to:
```
Flannel (Network Isolation Not Available)
Calico
Canal
Weave
```
Since Project Network Isolation can be utilized on all but Flannel

Additionally, if Canal, Calico, or Weave is selected from the `Network Provider` dropdown, we should not disable the `Project Network Isolation` checkbox selection. Currently this works for Canal but not Calico and Weave.

**Comment by westlywright** [comment]
@bmdepesa this is currently only available in 2.5-head.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 31f00c1

* Create a cluster
* CNIs are listed correctly
  * Calico
  * Canal
  * Weave
  * Flannel (Network Isolation Unvavailable)
* Project Network Isolation toggle is available for Calico, Canal, Weave
* Toggling PNI sets the `enable_network_policy` value appropriately in the cluster yaml 

Functional validations in https://github.com/rancher/rancher/issues/31338

One issue found - 
If a CNI is selected where PNI is allowed, and the toggle is set to `Enabled`, then the CNI is switched to `Flannel`, the PNI toggle stays at `Enabled`, with the corresponding `enable_network_policy` value set to `true` in the cluster yaml. 

This behavior does not occur in v2.5.8-rc4 or lower: when changing to a CNI without support for PNI, the flag is set to disabled. 

![Screen Shot 2021-04-16 at 4 08 15 PM](https://user-images.githubusercontent.com/21316915/115092070-f886cc00-9ecd-11eb-9f37-597fa2def762.png)

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 31f00c1
rancher/ui:v2.5-dev

The issue is no longer seen. Enabling PNI on a CNI that supports it and switching to `Flannel` now sets the PNI flag to disabled and updates the cluster yaml appropriately.
