### ISSUE TITLE
Duplicate crb seen on the server after upgrading from 2.4.15 to 2.5-head

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#32105]
Rancher: 
Before Upgrade: 2.4.15
After Upgrade: v2.5-70024998a0e95374a135177953a04f4539e2d59c-head
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a rancher server 2.4.15 single install
2. Create users 1-5
3. As user1 create a cluster1 [3 worker, 1etcd, 1cp] 
4.  As user2 create a cluster2 [3 worker,1etcd+cp]
5. As admin add a project P1 in cluster1 and add user3 as PO and PM and user4 as PM in the project and add project P2 and user4 as PO in the cluster2.
6. Restart the rancher server on 2.4.15 and get a list of duplicate role bindings and cluster role bindings
7. Remove the user3 as PO from the project P1.
8. Upgrade the cluster to v2.5-700249-head
9. Add user3 as PO in project P2
10. Get a list of rolebindings and duplicate role bindings created for the user3.

**Result:**
Duplicate crbs should have been deleted when we upgrade to 2.5-head

**Other details that may be helpful:**
From the script to find duplicates
```
DEBU[0000] groups of duplicate cluster role bindings: 1 
DEBU[0000] total duplicate cluster role bindings: 2     
{
  "clusterrolebindings": {
    "u-xxxx/c-xxxx-clustermember": [
      "/clusterrolebinding-xxxx",
      "/clusterrolebinding-yyyy"
    ]
  }
}                                                                                                                                                                                           

```

json for the crbs:
1.
```
{   
            "apiVersion": "rbac.authorization.k8s.io/v1",
            "kind": "ClusterRoleBinding",
            "metadata": {
                "creationTimestamp": "2021-04-13T18:25:15Z",
                "generateName": "clusterrolebinding-",
                "labels": {
                    "06f55ce7-5186-418b-bf66-1acbaa21aea1": "memberhsip-binding-owner",
                    "auth.management.cattle.io/rtb-label-updated": "true",
                    "cattle.io/creator": "norman",
                    "p-7kqwj_prtb-qrz9d": "membership-binding-owner"
                },
                "name": "clusterrolebinding-kmmjl",
                "resourceVersion": "31074",
                "selfLink": "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/clusterrolebinding-kmmjl",
                "uid": "564e6062-27bf-4593-99ac-094d9980299e"
            },
            "roleRef": {
                "apiGroup": "rbac.authorization.k8s.io",
                "kind": "ClusterRole",
                "name": "c-njql8-clustermember"
            },
            "subjects": [
                {   
                    "apiGroup": "rbac.authorization.k8s.io",
                    "kind": "User",
                    "name": "u-zxrfs"
                }
            ]
        },

```
2.
```
 {
            "apiVersion": "rbac.authorization.k8s.io/v1",
            "kind": "ClusterRoleBinding",
            "metadata": {
                "creationTimestamp": "2021-04-13T18:25:15Z",
                "generateName": "clusterrolebinding-",
                "labels": {
                    "06f55ce7-5186-418b-bf66-1acbaa21aea1": "memberhsip-binding-owner",
                    "auth.management.cattle.io/rtb-label-updated": "true",
                    "cattle.io/creator": "norman",
                    "p-7kqwj_prtb-qrz9d": "membership-binding-owner"
                },
                "name": "clusterrolebinding-scw6d",
                "resourceVersion": "31094",
                "selfLink": "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/clusterrolebinding-scw6d",
                "uid": "cf3b2a80-925b-44a9-a2b5-0ffa1cfc9c21"
            },
            "roleRef": {
                "apiGroup": "rbac.authorization.k8s.io",
                "kind": "ClusterRole",
                "name": "c-njql8-clustermember"
            },
            "subjects": [
                {
                    "apiGroup": "rbac.authorization.k8s.io",
                    "kind": "User",
                    "name": "u-zxrfs"
                }
            ]
        },

```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
v2.5-70024998a0e95374a135177953a04f4539e2d59c-head
- Installation option (single install/HA): Single

https://github.com/rancher/rancher/issues/29932

**Comment by prachidamle** [comment]
@anupama2501 do you have any rancher server logs?

**Comment by anupama2501** [comment]
@prachidamle I can provide you my setup details if necessary. Have the logs too for the same.

**Comment by prachidamle** [comment]
The error seen in rancher server logs:
```
2021/04/14 06:48:25 [INFO] CleanupDuplicateBindings, checking configmap
2021/04/14 06:48:25 [INFO] Calling Duplicate CRB and RB cleanup
2021/04/14 06:48:25 [INFO] Starting bindings cleanup
2021/04/14 06:48:25 [ERROR] Error in building the cluster config invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
2021/04/14 06:48:25 [WARNING] Error in cleaning up Duplicate CRB and RB: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

In HA setups, the inClusterConfig is found and this can proceed. Seems for a single node, we need to find another way. Workaround is to set the KUBECONFIG env while starting rancher server.

**Comment by anupama2501** [comment]
@prachidamle  This is also seen with the same test scenarios if we upgrade from 2.5.7 to 2.5-head on single install.

**Comment by deniseschannon** [comment]
@anupama2501 If the master PR isn't created/merged before you pick this up, please create a forwardport issue to track it instead of reopening this one.

**Comment by anupama2501** [comment]
Verified on 2.5.8-rc10

1. On rancher 2.5.6, create 4 test users,  user1-4, as user1 create a cluster with 1 cp+etcd+worker and as user2 create a cluster with 1cp+etcd+worker
2. Create P1 to cluster1, P2 to cluster2 and add user3 as PO and PM of P1 and user4 as PO and PM of P2.
3. Remove user3 as PO of P1 and user4 as PO of P2
4. Get list of duplicates and upgrade to v2.5.8-rc3 [duplicates are still seen after upgrade as expected]
5. Upgrade the rancher server to v2.5.8-rc10 and verified duplicates are removed.

**Comment by prachidamle** [comment]
@anupama2501 The forwardport PR for the original issue has been updated with this fix as well. So can you close the forward-port issue? here is the combined PR: https://github.com/rancher/rancher/pull/31833

**Comment by anupama2501** [comment]
Verified on 2.4.15

1. On rancher 2.4.15, create 4 test users, user1-4, as user1 create a cluster with 1 cp+etcd+worker and as user2 create a cluster with 1cp+etcd+worker
2. Create P1 to cluster1, P2 to cluster2 and add user3 as PO and PM of P1 and user4 as PO and PM of P2.
3. Remove user3 as PO of P1 and user4 as PO of P2
4. Get list of duplicates and upgrade to v2.5.8-rc3 [duplicates are still seen after upgrade as expected]
5. Upgrade the rancher server to v2.5.8-rc10 and verified duplicates are removed.

**Comment by anupama2501** [comment]
@prachidamle the PR for master-head is not merged yet. Therefore would like to keep the ticket for forward port open and perform validations on the ticket once the PR is merged.
