### ISSUE TITLE
forwardport: Generate an images sources text file

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#32114]
Forward port of: https://github.com/rancher/rancher/issues/31663

Description:
Image export script should generate a file similar to rancher-images.txt that includes sources (what uses the image in rancher). Source can be "system" meaning it is for RKE or needed for base functionality such as pipelines, "core" meaning it is needed for core rancher functionality, "rancher" meaning it is the rancher or rancher-agent image, "k3sUpgrade", or any of the charts/system-charts.

Testing:
To test compare rancher-images.txt to previous version and make sure there aren't any unexpected difference. An unexpected difference would be something like many images missing. Another thing to validate is the the rancher-images-sources.txt should contain the same number of rows as the rancher-images.txt.

PR in `v2.5-head`: https://github.com/rancher/rancher/pull/31492
PR in `master-head`: https://github.com/rancher/rancher/pull/31905

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by deniseschannon** [comment]
Validated the rancher-images-sources.txt file in the assets of v2.6.0-rc1 has the same list of images in rancher-images.txt
