### ISSUE TITLE
Update rancher-images generator to support feature charts min/max

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#32111]
Problem:
Feature charts now support adding a Rancher version constraint and the rancher-images generator needs to be updated to pick images based on those constraints. 

Solution:
Update the rancher-images generator to pick images in a feature chart if the rancher tag that's being released is within the chart's min/max range. E.g. if we are releasing rancherVersion 2.5.8, images in charts with a `min <= rancherVersion` and `max >= rancherVersion` (when provided, max is optional)  should be included in the rancher-images file as well. 

Important notes:
- We prep the feature charts by extracting the tarball of each chart's latest version and build a virtual index like we do with system charts. This logic will likely need to change since all charts will need to be readable to check for their min/max. 
- When we build the virtual index, we sort charts based on their version in descending order (0 elem is latest). Feature charts have uncommon semver format (E.g `v1.2.3.000-rc01`) compared to system charts, so we need to verify that there are sorted in the correct order.

Similar issue for system-charts [here](https://github.com/rancher/rancher/issues/31568).

**Comment by cbron** [comment]
Shouldn't this be 2.6.0 ?

**Comment by PennyScissors** [comment]
Closing in favor of this [issue](https://github.com/rancher/rancher/issues/33037)
