### ISSUE TITLE
Service sits in activating and continually tries to recreate container after it errors out

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3211]
version - master jan 07

Steps:
1. Add a service and under volume put "abc efg:/abc sss or abdd sdjks skdfj:/adf"
2. Try to start the service

Results:  The container actually is throwing an error saying it can't create because the volume name has invalid characters.
![image](https://cloud.githubusercontent.com/assets/11514927/12206207/e4782df4-b5fc-11e5-82bd-470821bdd971.png)
![image](https://cloud.githubusercontent.com/assets/11514927/12206319/7ab65476-b5fd-11e5-9298-33a61595da23.png)

Expected:
Maybe the service should degrade and stop trying since it will never be able to resolve.

**Comment by will-chan** [comment]
Alena, hasn't this been somewhat addressed with your error handling?

**Comment by alena1108** [comment]
>> Maybe the service should degrade and stop trying since it will never be able to resolve.

all we are gonna do is - provide an error to the user

@will-chan better error reporting is being taken care of by the error handling PR
