### ISSUE TITLE
rancher-compose: Show current state of service after it's been started.  

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3212]
Currently, after you start a service in rancher-compose, it will just indicate that the service is started (regardless if any containers were created). There are cases where the service will have been logged as started, but due to scheduling rules, no containers were created.

It'd be nice if rancher-compose could also provide the state of the service after it's been created. 

https://forums.rancher.com/t/if-unable-to-schedule-service-rancher-compose-returns-started-anyway/1064

**Comment by andyshinn** [comment]
A little related is https://github.com/rancher/rancher/issues/2958. I'd love the ability for statuses like this to be conveyed as exit codes so I can fail deployments and builds in a CI scenario.
