### ISSUE TITLE
kubectl get logs not work

### ISSUE THREAD

**Issue by bilemedimkq** [rancher/rancher#32125]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** 
https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/#about-rancherd-installs
I followed the steps on these documents. I have installed this to three vm servers.(HA-Cluster)
and create one pod
```
apiVersion: v1
kind: Pod
metadata:
  name: test1
  namespace: jenkins
spec:
  containers:
    - name: docker
      image: docker:20.10-dind
      command:
        - cat
      tty: true
```

**Result:**
i get error on get logs.

```
> kubectl logs test1 -n jenkins
Error from server: Get https://n3-paean:10250/containerLogs/jenkins/test1/docker: dial tcp: lookup n3-paean on 213.133.98.98:53: no such host
```
![image](https://user-images.githubusercontent.com/42588052/114701932-1caaa780-9d2c-11eb-9148-7c41b78fbf33.png)

* n3-paean is cluster node.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom (Hetzner Cloud VMs)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 4 VCpu 8 GB memory per node
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16+rke2r1", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-24T15:46:26Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16+rke2r1", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-24T15:46:26Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): Rancherd (v1.18.16+rke2r1)

**Comment by han-ysys** [comment]
same problem here with rancher version 2.5.7 and `kubectl version`:
```shell
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5+rke2r1", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-04-02T03:22:00Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bilemedimkq** [comment]
is there someone to help ?

**Comment by bilemedimkq** [comment]
?

**Comment by han-ysys** [comment]
It seems to be a hostname resolution problem. I found a workaround about argument `kube-apiserver-arg: "kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"`
I installed rancher with rke2, adding this to `/etc/rancher/rke2/config.yaml` works. You could try to restart kubernetes with `--kube-apiserver-arg="kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"`

**Comment by bilemedimkq** [comment]
@han-ysys Thank you for reply!
i added `kube-apiserver-arg: "kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname` to `/etc/rancher/rke2/config.yaml` and its work now!
