### ISSUE TITLE
forwardport of [log] View log repeat output #32084

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32128]
forwardport: [log] View log repeat output #32084

**Comment by vincent99** [comment]
There is no such thing as "forward porting" a fix to 2.6 because there are currently no separate dashboard branches for 2.5 vs 2.6 vs master

**Comment by sowmyav27** [comment]
Closing based on https://github.com/rancher/rancher/issues/32128#issuecomment-819913918
