### ISSUE TITLE
[Forwardport][Epic] GKE fixes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32140]
These issues have been validated in 2.5.8/2.5-head. Tracking the master-head validations in this ticket

- https://github.com/rancher/rancher/issues/32065
- https://github.com/rancher/rancher/issues/32161
- https://github.com/rancher/rancher/issues/31010
- https://github.com/rancher/rancher/issues/31011
- https://github.com/rancher/rancher/issues/31461
- https://github.com/rancher/rancher/issues/32141
- https://github.com/rancher/rancher/issues/30864

**Comment by prabalsharma** [comment]
master-1e1ed67329d6224e7a10f1c1a529eaff60ba48ea-head
- [ ] #32065
- [ ] #32161 
- [ ] #31010 
- [ ] #31011 
- [ ] #31461 
- [ ] #32141 
- [ ] #30864
