### ISSUE TITLE
[monitoring v2] not installing correctly on RKE2 -- ingress-nginx not deploying

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32145]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug
parent ticket : https://github.com/rancher/dashboard/issues/2485 

**Steps to reproduce (least amount of steps as possible):**
* deploy RKE2 cluster
* deploy monitoring with default settings

**Result:**
monitoring fails to deploy

**Other details that may be helpful:**

tested on v2.5-head (70024998a0e95374a135177953a04f4539e2d59c):
* RKE2 -- upgrade from 9.4.202 -> 14.5.100-rc7 -- default settings -- ingress-nginx is enabled, but failures upgrading the cluster **FAIL** 
--first upgrade attempt -- 
<img width="1792" alt="Screen Shot 2021-04-14 at 12 38 12 PM" src="https://user-images.githubusercontent.com/16691014/114772542-c71dcd00-9d22-11eb-89b8-8f29fdcdb87a.png">
--attempting upgrade with no changes -- below
* also happens on clean install of RKE2 -- 14.5.100-rc7 -- default settings -- ingress-nginx is enabled, but failures upgrading the cluster **FAIL** -- even when manually adding the namespace, no pods are deployed to it and targets are not up in prometheus for ingress-nginx
<img width="1792" alt="Screen Shot 2021-04-14 at 12 41 07 PM" src="https://user-images.githubusercontent.com/16691014/114772533-c422dc80-9d22-11eb-87a0-3889562d81e6.png">

* RKE2 -- clean install of 14.5.100-rc5 -- ingress-nginx disabled -- pass

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-head (70024998a0e95374a135177953a04f4539e2d59c)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted (linode)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 8vCPU (2 nodes, 1 all, 1 worker, 4vCPU each)
- Kubernetes version (use `kubectl version`): 1.20.5

- Docker version (use `docker version`): 20.10.5

**Comment by aiyengar2** [comment]
This should have been addressed in https://github.com/rancher/dashboard/issues/2485. Not sure why we closed it out with failed tests

**Comment by aiyengar2** [comment]
Seems like the error seems to indicate that rke2 doesn't have nginx ingress installed by default (unlike rke1), so this would be a UI change that needs to be rolled back.

**Comment by aiyengar2** [comment]
Closing this out in favor of the re-opened dashboard ticket in https://github.com/rancher/dashboard/issues/2485.
