### ISSUE TITLE
Add "docker-machine reports:" or something like that to docker-machine errors

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3214]
It's hard for users to distinguish what are true rancher errors versus docker-machine when launching hosts through the UI.

It'd be nice to pre-pend the messages from docker-machine with some kind of message indicating "docker-machine reports:".

Suggestion from: https://forums.rancher.com/t/creating-hosts-from-rancher-on-digitalocean-fails-with-various-error-messages/1377/2

**Comment by vincent99** [comment]
The docker machine says...

![image](https://cloud.githubusercontent.com/assets/753917/12210742/7d76d728-b619-11e5-91ae-51bd07055069.png)

**Comment by cjellick** [comment]
lol.

**Comment by will-chan** [comment]
Closed due to inactivity.

**Comment by gerich-home** [comment]
I vote for the issue to be reopened and fixed. It's terribly hard to guess why something went wrong when I see error in UI (in almost all places in Rancher: when adding a host, when adding/updgrading a service)
