### ISSUE TITLE
[rancher/charts] Modify released/ directory to contain release-v2.5 + dev-v2.5 contents and drop old RCs

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#32146]
Previously, our dev-v2.5 branch had a released/ directory which contained older versions of RCs from previous releases.

e.g. we kept all the old rcs for Monitoring from the 2.5.6/2.5.7 release (9.4.203-rcXX) [here](https://github.com/rancher/charts/tree/dbb28034e0aea00ba8c0e58f1a9cbc6b2f61b8ed/released/assets/rancher-monitoring)

Based on conversation with @cbron @PennyScissors @brendarearden and @thedadams offline, we are switching the purpose of this directory to contain everything within the release-v2.5 branch post a `make sync` with dev-v2.5. i.e. the dev-v2.5 branch's released/ folder (will rename to `to-be-released/`) will now contain what will be released in the next Rancher release (e.g. 2.5.8 today).

**Comment by slickwarren** [comment]
the following was tested:
* rancher RCs only contain released versions (i.e. no charts have RCs listed) 
  * v2.5.8-rc8 through rc10 -- pass
* dev branches should list RCs in chart versions
  * v2.5-head (42f722b) -- pass


Reopening for the following issue:
  * master-head (b504bc8) -- fail (RC versions are not listed

**Comment by aiyengar2** [comment]
On v2.5-head in the same commit hash I don't see rcVersions in the local cluster:

![Screen Shot 2021-04-28 at 3 07 09 PM](https://user-images.githubusercontent.com/13127443/116478801-81d5c100-a833-11eb-9e0a-207270335303.png)

Same for v2.5-head in a downstream cluster:
![Screen Shot 2021-04-28 at 3 12 30 PM](https://user-images.githubusercontent.com/13127443/116479234-28ba5d00-a834-11eb-9d01-1df9d281647b.png)

Moving issue back to test; maybe it was an ephemeral issue with syncing the chart repository?

**Comment by slickwarren** [comment]
@aiyengar2 I am enabling this option in the tests above. Is that not your use case?
<img width="618" alt="Screen Shot 2021-04-29 at 8 12 01 AM" src="https://user-images.githubusercontent.com/16691014/116574563-b17fda00-a8c2-11eb-8843-7979d0b3ea1f.png">

**Comment by aiyengar2** [comment]
I tried enabling the option but I'm still unable to reproduce this.

![Screen Shot 2021-04-29 at 12 12 16 PM](https://user-images.githubusercontent.com/13127443/116607972-80fe6700-a8e7-11eb-9d70-393a2f9e1e39.png)

![Screen Shot 2021-04-29 at 12 12 36 PM](https://user-images.githubusercontent.com/13127443/116607995-852a8480-a8e7-11eb-82c2-7904072eff68.png)

**Comment by slickwarren** [comment]
I think this was some sort of initial cache for lack of a better term.
