### ISSUE TITLE
Feature Request: Helm/node-selection

### ISSUE THREAD

**Issue by dmakeroam** [rancher/rancher#32159]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature Request: Helm/node-selection:

- To support appropriate node selection based on the specified requirement, we should have node affinity, node selector, tolerations field on the helm chart

**Comment by jordanorc** [comment]
It would be great to have it.

**Comment by dmakeroam** [comment]
> It would be great to have it.

Have you ever used "mustMerge" function? Could you help me to take a look on this? 

https://github.com/rancher/rancher/pull/32013
