### ISSUE TITLE
Post installing Rancher 2.5.7 how to tell rancher about proxies settings ?

### ISSUE THREAD

**Issue by nagaraj200788** [rancher/rancher#32158]
Navigate to Tools-->Catalogs and for all services i am seeing 

Error in HTTP GET to [https://kubernetes-charts-incubator.storage.googleapis.com/index.yaml], error: Get "https://kubernetes-charts-incubator.storage.googleapis.com/index.yaml": dial tcp 142.250.67.48:443: connect: no route to host

I doubt rancher host not reaching due to proxy and while installing i had set proxies in linux profiles hence installation went fine.
Post installation host to tell to rancher host ?

--

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.5.7
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VM
- Kubernetes version (use `kubectl version`):

```
Error in HTTP GET to [https://kubernetes-charts-incubator.storage.googleapis.com/index.yaml], error: Get "https://kubernetes-charts-incubator.storage.googleapis.com/index.yaml": dial tcp 142.250.67.48:443: connect: no route to host
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by dramich** [comment]
Follow the directions here, rancher should be ran with the proxy flags along with using our list of no_proxy options: https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/behind-proxy/
