### ISSUE TITLE
[GKEv2] [UI] Cannot update image types in node pools independently

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#32167]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Go to create a GKE cluster.
2. Configure one node pool.
3. Click "Add Node Pool". Try to change "Image Type".

**Result:**

Changing the Image Type of one node pool changes it for the other one.

![image-types](https://user-images.githubusercontent.com/1220710/114939590-85aa2200-9df5-11eb-953a-37e38e1413eb.gif)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-eb775db432486e1ac84dd9d30060c4854764584d
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by prabalsharma** [comment]
passed on v2.5-a5d9602ce1f264764b22e26a2425f99cb812cf97-head
