### ISSUE TITLE
Graphs are receiving data every 5 seconds but showing every second

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3216]
version - master jan 07

Steps:
1.  Create a host or a container
2.  Click on host name or container name

Results:  Data points coming in every 5 seconds but graphs are showing for every second
![image](https://cloud.githubusercontent.com/assets/11514927/12210607/65e5c80e-b618-11e5-8dbd-2d7fdb886041.png)

Expected: Show points every 5 seconds and slow down how fast it's coming across (right now it's very difficult to mouse over a point because it's going by so quickly)

**Comment by cjellick** [comment]
@vincent99 you just need us to send the same data, but on a 5 second interval instead?
@tfiduccia is this all stats (host, aggregated) or just container stats?

**Comment by vincent99** [comment]
@cjellick As it is right now with the cAdvisor interval changed, I get data points every 1 second but they're the same point 5 times, then a new point 5 times, etc.  So I want one frame with one different point (per resource) every 5 seconds.

**Comment by vincent99** [comment]
And I think it's all stats, single host/container or aggregated.

**Comment by vincent99** [comment]
This is reverted back to 1 second for now.

**Comment by tfiduccia** [comment]
Version - master 1/29
Verified fixed
