### ISSUE TITLE
[KEv2][UI] Node autoscaling is mislabeled

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#32176]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Create a GKE cluster. Create a node pool.

**Result:**

There is a checkbox under "Customize Node Pools" labeled "Horizontal Pod Autoscaling". Horizontal pod autoscaling is a cluster-level idea and is already available in "Cluster Addons". Node pools support a different type of autoscaling that GKE just calls "autoscaling" which is for scaling the node count up and down, not pod count.

![image](https://user-images.githubusercontent.com/1220710/114947726-7e3d4580-9e02-11eb-9d6e-0311c3b842e4.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by prabalsharma** [comment]
fixed on 2.5-head
