### ISSUE TITLE
Add support to enable/disable feature flags using helm options

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#32177]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Currently right now when we upgrade using helm upgrade <rancher> there is no way to disable/enable feature flags. 
We have to upgrade 1st then make an API call to disable it.

So right now if I don’t want a fleet installed when upgrading the Rancher application.

- Helm upgrade rancher application from rancher helm charts..
 ```curl --retry 3 --retry-delay 10 -s -X PUT  -H "Authorization: Bearer $RANCHERAPITOKEN" - -H 'Content-Type: application/json' -H 'Accept: application/json' -d "${PAYLOAD}" "https://${RANCHEREND}/v3/features/${FEATURE}```
- Clean up all the namespaces and other workloads that are now overhead for something I don’t want… like
  - Every object in fleet-system namespace including the namespace itself
  - Every object in rancher-operator-system namespace including the namespace itself
- Bounce rancher leader pod on local kuberentes cluster that is running rancher app.

**Result:**
N/A

**Other details that may be helpful:**
The end goal would be adding the following flags to the Rancher Helm chart.
```
helm upgrade rancher .....
--set feature.fleet=disable \
--set feature.istio-virtual-service-ui=disable \
.....
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): HA

gz#16453

**Comment by leodotcloud** [comment]
@mattmattox Can you please check https://rancher.com/docs/rancher/v2.5/en/installation/resources/feature-flags/#enabling-features-for-kubernetes-installs and verify if this ticket can be closed?

**Comment by leodotcloud** [comment]
Based on offline discussion, closing the ticket.
