### ISSUE TITLE
[v2.4] KDM release: k8s april patches

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#32178]
### **Kubernetes Updates:**
This is a KDM release for new k8s versions: `v1.18.18`. It's not going out with any Rancher release, it's a KDM + RKE release only.

| New k8s versions | Rancher versions | 
| --- | --- | 
|`v1.18.18-rancher1-1` | 2.4.5+ | 

### **Rancher updates:**
- All rancher mirrored images will now be prefixed with `"rancher/mirrored-`. 
- Following new rancher patch versions for #32002: 
`v1.17.16-rancher1-2`, `v1.17.17-rancher1-2`, `v1.17.17-rancher2-2` 
`v1.18.14-rancher1-2`, `v1.18.15-rancher1-2`, `v1.18.16-rancher1-2` and `v1.18.17-rancher1-2`

### **Developer changelog:** 
- All existing `v1.18.x` versions in dev-v2.4 need to be released or have been released (are present in release-v2.4) so we need to introduce new k8s version. To introduce a new k8s version, basecopy the latest existing version in a separate commit, followed by another commit to update what's changed. Following versions need to be created with their compatible rancher server versions:

| basecopy [version](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/k8s_rke_system_images.go#L3590) from | create | set [rancher version constraints]( https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/rke/k8s_version_info.go#L278) 
| --------------- | --------------- | -----------| 
| v1.18.17-rancher1-2 | v1.18.18-rancher1-1 | 2.4.5+ |

**Comment by sowmyav27** [comment]
**On 2.4.15**
### Fresh Install checks passed 
- for k8s `v1.18.18-rancher1-1` and `v1.17.17-rancher2-2`
- Cluster creation succeeded for all k8s versions with all network provider and network related checks looked good.
- On canal clusters, validation tests looked good. (automation passed)
