### ISSUE TITLE
Remove force_tcp from node-local-dns for forwarded queries to upstream

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#32180]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Steps to reproduce (least amount of steps as possible):**

The default RKE deployment of node-local-dns will use `force_tcp` to upgrade workload DNS requests to TCP for the upstream query, this can add latency to the request and potentially overwhelm upstream nameservers serving large clusters or have limits configured.

**Other details that may be helpful:**

A suggestion is to follow upstream changes and avoid using `force_tcp` for these forwarded requests.
  * https://github.com/kubernetes/kubernetes/pull/93471/files

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4 / v2.5

_edit_: Add example errors to help tracking, if the upstream nameservers are unable to accommodate the TCP queries, or respond in a timely manner, i/o timeouts such as the below could be observed in the node-local-dns pods, where 10.1.2.4 is an upstream nameserver:

```
[ERROR] plugin/errors: 2 subdomain.example.com.example.com. A: read tcp 10.1.2.3:60096->10.1.2.4:53:53: i/o timeout
[ERROR] plugin/errors: 2 subdomain.example.com. A: read tcp 10.1.2.3:60038->10.1.2.4:53: i/o timeout
```

gz#16394

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (05/24/2021)` _d31a7fe_
RKE version for local HA cluster `v1.3.0-rc2`


## Deployed an RKE cluster with k8s `v1.21.1-rancher1-1`

Using this RKE version with the 1.21 k8s I see the `force_tcp` config option dropped as expected.
On k8s versions below 1.21 the `force_tcp` is included.

## Rancher HA RKE1 downstream RKE DO clusters

With the 1.21 k8s I see the `force_tcp` config option dropped as expected.
On k8s versions below 1.21 the `force_tcp` is included.

**Comment by izaac** [comment]
Closing this was validated on master (2.6). Backport issues will be created separately if required.
