### ISSUE TITLE
UI: vSphere - anti-affinity rules (iFrame into Vue)

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#32191]
Still need to gather some details here before work can start on the UI, including the backend work (once I find the ticket) but...

We need the ability to toggle the affinity/anti-affinity options for vSphere. This can be done in the older UI and we can create an iFrame in the newer one to refer to this.

**Comment by gaktive** [comment]
Here's the backend ticket: https://github.com/rancher/rancher/issues/29894

> When using the vSphere node driver, users should be able to specify vSphere anti-affinity scheduling rules per node group. This needs to work for all supported versions of vSphere in Rancher. Users should be able to set the rules via the UI and when provisioning through the Terraform provider.

**Comment by Sahota1225** [comment]
Closing this ticket combination of dashboard and backend ticket. https://github.com/rancher/rancher/issues/29894 https://github.com/rancher/dashboard/issues/7181
