### ISSUE TITLE
[GKE] Cannot switch cloud credentials for imported cluster

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#32196]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
**Scenario 1:**
- From Rancher, create 2 Google Cloud Credentials with valid service accounts ("cred1" and "cred2").
- From GKE console, create a cluster.
- From Rancher, import the cluster with "cred1".
- After cluster becomes available, edit the cluster.
- Change the cluster cloud credential to "cred2".
- Edit the cluster using "cred2". Add a node group.

**Result:**
Cluster goes into error state with:
`Googleapi: Error 400: Auto_upgrade and auto_repair cannot be false when release_channel REGULAR is set., badRequest`

**Scenario 2:**
- From Rancher, create 1 Google Cloud Credential with valid service account ("cred1")
- From GKE console, create a cluster.
- From Rancher, import the cluster with "cred1".
- After cluster becomes available, edit the cluster.
- BEFORE the cluster edit is saved, disable the service account associated with the cloud credential from GKE console.
- Save the cluster.
- The cluster will error with `Get "https://...": oauth2: cannot fetch token: 400 Bad Request Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}` This is expected.
- From GKE console, reenable the service account.
- Edit the cluster. Try to bring the cluster out of error state. Add a node pool.
- Save.

**Result:**
Cluster goes into error state with:
`Googleapi: Error 400: Auto_upgrade and auto_repair cannot be false when release_channel REGULAR is set., badRequest`

**Other details that may be helpful:**
This is not seen with hosted clusters. So far, only seen with imported clusters.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5-41f173a-head`
- Installation option (single install/HA): single install

**Comment by cmurphy** [comment]
This is not related to switching the cloud credential, you will see the same behavior without doing so. When creating a cluster in the GKE web UI, under "Control plane version" it will default to selecting "release channel". When we create a cluster through Rancher it uses "Static version". When you add a node pool through Rancher, "Auto upgrade" and "Auto repair" default to off, but GKE requires them to be turned on when using the "regular" channel in "release channel" mode. So the way around this is either to create the cluster in GKE using "Static version" from the start, or check "Auto upgrade" and "Auto repair" when you add a new node pool.

**Comment by aaronRancher** [comment]
@cmurphy Thank you for pointing this out.

Tested and validated the following scenarios on `v2.5-41f173a-head`:
Scenario 1:
- From Rancher, create 2 Google Cloud Credentials with valid service accounts ("cred1" and "cred2").
- From GKE console, create a cluster.
- From Rancher, import the cluster with "cred1".
- After cluster becomes available, edit the cluster.
- Change the cluster cloud credential to "cred2".
- Edit the cluster using "cred2". Add a node group. Enable `Auto Upgrade` and `Auto Repair`.
Result:
The cluster is updated successfully. New node group is added.

Scenario 2:
From Rancher, create 1 Google Cloud Credential with valid service account ("cred1")
From GKE console, create a cluster using "Static version"
From Rancher, import the cluster with "cred1".
After cluster becomes available, edit the cluster.
Add a node group. Do not enable `Auto Upgrade` and `Auto Repair`
Result:
The cluster is updated successfully. New node group is added.

Scenario 3:
From Rancher, create 1 Google Cloud Credential with valid service account ("cred1")
From GKE console, create a cluster.
From Rancher, import the cluster with "cred1".
After cluster becomes available, edit the cluster.
BEFORE the cluster edit is saved, disable the service account associated with the cloud credential from GKE console.
Save the cluster.
The cluster will error with `Get "https://...": oauth2: cannot fetch token: 400 Bad Request Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}` This is expected.
From GKE console, reenable the service account.
Edit the cluster. Try to bring the cluster out of error state. Add a node pool. Enable `Auto Upgrade` and `Auto Repair`.
Result:
The cluster is updated successfully. New node group is added.

**Comment by cmurphy** [comment]
@aaronRancher based on your latest validation, do you think this bug can be closed? Or is there something we should address?

**Comment by aaronRancher** [comment]
Closing this issue, as this is not a bug.
Will track the needed UI change and documentation here: https://github.com/rancher/rancher/issues/32282
