### ISSUE TITLE
[Forwardport] git-remote-http defunct processes from cluster-register_cattle-cluster-agent

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32197]
Forwardport of https://github.com/rancher/rancher/issues/30172

**Comment by sowmyav27** [comment]
Master: PR https://github.com/rancher/rancher/pull/31847

**Comment by kravciak** [comment]
Blocked on rancher/rancher#31964

**Comment by kravciak** [comment]
Works as expected in master-head (909237a). Tested with k3s cluster.
