### ISSUE TITLE
[Forwardport] CIS scan downstream cluster with project network isolation activated fails at 5.3.2 Hardended

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32203]
Forwardport for issue - https://github.com/rancher/rancher/issues/30211

**Comment by sowmyav27** [comment]
Master PR: https://github.com/rancher/rancher/pull/32033

**Comment by aaronRancher** [comment]
Currently blocked by: https://github.com/rancher/rancher/issues/31964

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 8c014ef` with the following steps:

- Deploy a downstream clsuter with PNI enabled.
![Screen Shot 2021-05-10 at 12 51 22 PM](https://user-images.githubusercontent.com/57409052/117716437-7321cf00-b18e-11eb-9999-6645f3d45973.png)
- Install the CIS Operator in cluster explorer
- Navigate to Cluster Applications > CIS Benchmark
- Create a new, one-time scan with profile: rke-profile-hardened-1.6
- Allow the scan to run and once completed, click into it to view the results
- 5.3.2 test has failed.
- System project has no Networkpolicy defined even when the PNI is enabled on the cluster

```
> kubectl get networkpolicies -n cis-operator-system
NAME                POD-SELECTOR   AGE
default-allow-all   <none>         41m
> kubectl get networkpolicies -n cattle-system
No resources found in cattle-system namespace.
```

Do not see the `hn-nodes` and `np-default ` network policies get created after cluster is provisioned:
```
> kubectl get networkpolicies -A
NAMESPACE             NAME                                POD-SELECTOR                                             AGE
cis-operator-system   default-allow-all                   <none>                                                   43m
fleet-system          default-allow-all                   <none>                                                   50m
ingress-nginx         hp-nginx-ingress-controller-md99t   field.cattle.io/podName=nginx-ingress-controller-md99t   49m
```
Network policies are not added to new namespaces:
```
> kubectl get networkpolicies -n test-ns
No resources found in test-ns namespace.
```

**Comment by aaronRancher** [comment]
Will track fix for network policy creation here: https://github.com/rancher/rancher/issues/32659

**Comment by aaronRancher** [comment]
On Rancher `master-head` `version 3d465ee`
- Install the CIS Operator/Chart in a downstream cluster where PNI is enabled on the cluster
- Navigate to Cluster Applications > CIS Benchmark
- Create a new, one-time scan with profile: rke-profile-hardened-1.6
- Allow the scan to run and once completed, click into it to view the results
- 5.3.2 test has passed

## **Namespace Creation**
Pre requisite: Create a PNI enabled cluster.
1. Create namespace in no project - No rancher policy is added; CIS hardened scan fails on 5.3.2 test.
2. Create namespace in default project - testns; the following networkpolicy are added.
```
> kubectl get networkpolicy -n testns
NAME         POD-SELECTOR   AGE
hn-nodes     <none>         4m6s
np-default   <none>         4m6s
```
3. Create namespace in system project - np-default-allow-all is added to this namespace
4. Create new project and create namespace testnewns in it - hn-nodes and np-default networkpolicy are added
```
> kubectl get networkpolicy -n testnewns
NAME         POD-SELECTOR   AGE
hn-nodes     <none>         3m59s
np-default   <none>         3m59s
```
## **Namespace Moving**
1. Move namespace with no network policies from no project to non system project. hn-nodes and np-default policies get added to this namespace.
2. Move namespace with user network policies from no project to non system project - hn-nodes and np-default get added to the namespace along with the user defined networkpolicy
```
# testnone ns in no project with user networkpolicy
> kubectl get networkpolicy -n testnone
NAME                  POD-SELECTOR   AGE
test-network-policy   role=db        10s
# move ns to non-system project
> kubectl get networkpolicy -n testnone
NAME                  POD-SELECTOR   AGE
hn-nodes              <none>         5s
np-default            <none>         5s
test-network-policy   role=db        54s
```
3. Move namespace with user network policies from non system project to no project - user network policy remained on the namespace and hn-nodes and np-default are deleted from the namespace.
4. Move namespace with no network policies from no project to system project - np-default-allow-all gets added to the namespace
5. Move namespace with user network policies from no project to system project - np-default-allow-all is not added to the namespace. User network policies are retained
6. Move namespace with user network policies from default project to system project - hn-nodes and np-default deleted, np-default-allow-all is not added, user network policies are retained --> CIS scan - 1.6 hardened 5.3.2 test passed.
6. Move namespace with user network policies from System project to default project - hn-nodes and np-default are added, and user network policies are retained
