### ISSUE TITLE
Enhance agent logging on worker requirement

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#32204]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Create custom cluster
- Add node with etcd and controlplane node (no node with worker role)

**Result:**
- Wait agent logging "Starting plan monitor, checking every 15 seconds" and nothing happens
- Cluster will show "Waiting for etcd, controlplane and worker nodes to be registered"

**Other details that may be helpful:**
This was introduced in v2.5.6, see https://github.com/rancher/rancher/issues/31244#issuecomment-790274280 where it is now required to have a node with the worker role registered before the cluster starts provisioning.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): single

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 3e89bb8`
UI shows cluster is still provisioning:
![Screen Shot 2021-05-11 at 4 03 32 PM](https://user-images.githubusercontent.com/57409052/117896278-0cc3ac00-b275-11eb-84c0-f7870e170fa8.png)

Logs from rancher-agent in control plane/etcd node:
```
time="2021-05-11T22:31:20Z" level=info msg="Connecting to wss://.../v3/connect/register with token ..."
time="2021-05-11T22:31:20Z" level=info msg="Connecting to proxy" url="wss://.../v3/connect/register"
time="2021-05-11T22:31:20Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-11T22:31:22Z" level=info msg="Starting plan monitor, checking every 15 seconds"
```

After adding a worker node, the cluster comes into active state.
