### ISSUE TITLE
"Services CIDR range is smaller than minimum (14 < 16)" error seen on GKEv2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32207]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy a cluster with the following details
<img width="938" alt="Screen Shot 2021-04-18 at 5 30 54 PM" src="https://user-images.githubusercontent.com/26032343/115167323-0c683480-a06c-11eb-8f13-655074263771.png">

- Error seen on cluster `Googleapi: Error 400: Services CIDR range is smaller than minimum (14 < 16)., badRequest`

**Expected Result:**

- Is this expected?
- If so is it worth to add some note or warning or some link to google docs? As if there is this error, user has no way to edit this cluster and make changes to the field.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `1c3629fb` ; would happen on 2.5-head also
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted GKE
- Kubernetes version (use `kubectl version`):

```
1.17 (Any)
```

**Comment by cmurphy** [comment]
It's expected given https://cloud.google.com/kubernetes-engine/docs/concepts/alias-ips#cluster_sizing_secondary_range_svcs

I could add some validation for the CIDR ranges but that starts to get into the business of duplicating GKE's validation which we said we want to avoid. These attributes are immutable once the cluster is created but @westlywright is there a way they could be edited if the cluster doesn't exist in GKE yet?

**Comment by westlywright** [comment]
@cmurphy The API UI would be the best option.

**Comment by westlywright** [comment]
Ive added basically the same validation logic to the UI that looks for a min/max and if our entered mask fits in that range. Ive also added a couple helper labels to indicate what the min/max are (based on the min/max's in @cmurphy pr) so hopefully users wont even hit the validator error. Probably no need for the back end validation unless they can do more complex validations.

**Comment by sowmyav27** [comment]
**On 2.5.8-rc7 and master-head commit id: `1c3629f`**

The UI shows 
<img width="832" alt="Screen Shot 2021-04-20 at 9 51 11 PM" src="https://user-images.githubusercontent.com/26032343/115498592-b8ec1700-a222-11eb-87f7-ea7daa5aba8c.png">

No other UI validation happens.

@westlywright is this expected?

**Comment by westlywright** [comment]
The PR to revert the min/max validation is in review currently. As discussed offline I'm looking at an alternative to edit the fields if we're in this weird state where the cluster never provisioned but I'm not sure this will work either?

**Comment by cmurphy** [comment]
@westlywright the fix to be able to edit the fields in the cluster is now in v2.5 (but not in master).

**Comment by westlywright** [comment]
@sowmyav27 @cmurphy Ive opened a PR that adds logic to allow the user to edit the cluster IF `cluster.transitioning = 'error'` AND `cluster.state = 'provisioning'` AND `cluster.gkeStatus.upstreamSpec` is empty or `null`.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id `124e7afc`**

- Deploy a cluster GKEv2 hosted. Error seen on cluster `Googleapi: Error 400: Services CIDR range is smaller than minimum (14 < 16)., badRequest`
- Edit cluster change the Cluster secondary Range name and Services Secondary Range Name to right values
- the error goes away and the cluster provisions successfully and comes up Active in Rancher.
