### ISSUE TITLE
RKE Cluster gets Upgraded after upgrade from Rancher v2.4.8 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#32216]
**Rancher v2.4.8** (**RKE v1.1.6**) -> **Rancher v2.4.12+** (**RKE v1.1.13+**) / **Rancher v2.5.0+** (**RKE v1.2.0+**)
Steps to Reproduce: 
- Rancher server `v2.4.8` 
- Create a RKE cluster (Make sure to not use any SELinux nodes) 
- Upgrade Rancher to `v2.4.12+` or `v2.5.0+` 
- Observe that the cluster goes to Updating state and worker nodes also get updated 
- Following can be seen in the logs: 
```
2021/04/15 11:21:41 [INFO] binds changed for [kube-proxy] old: [/etc/kubernetes:/etc/kubernetes:z /run:/run /lib/modules:/lib/modules:z,ro] new [/etc/kubernetes:/etc/kubernetes:z /run:/run /lib/modules:/lib/modules:ro] 
```

**Comment by anupama2501** [comment]
Tried the following test scnearios:
On 2.4.8 not able to reproduce the issue
1.  Create a cluster with all roles [worker,cp,etcd] enabled on one node
     Upgrade the rancher version from 2.4.8 to 2.5.7
    Cluster goes into updating state but the logs as mentioned in the description are not seen. Following logs are seen while 
    the server is in updating state:
  <img width="500" alt="Screen Shot 2021-04-19 at 10 57 33 AM" src="https://user-images.githubusercontent.com/38144301/115316606-7f39e400-a12e-11eb-8e37-a5e30735dada.png">
  <img width="500" alt="Screen Shot 2021-04-19 at 10 59 17 AM" src="https://user-images.githubusercontent.com/38144301/115316612-8234d480-a12e-11eb-9a6d-eac781c65097.png">

2. Create a cluster with roles cp+etcd on one node and worker on another node
    Upgrade from v2.4.8 to v2.4.15
    Cluster doesn't go into updating state
3. Create a cluster with roles cp+etcd+worker on the same node
    Upgrade the rancher from v2.4.8 to v2.4.15
    Cluster goes into updating state, but the logs mentioned in the description are not seen

**Comment by anupama2501** [comment]
^^ Re-opening this issue as the logs appear to be different than posted in the description.

**Comment by kinarashah** [comment]
Let's eliminate k8s versions where ACI images were introduced (we already know the issue and has been fixed separately). Don't use any version mentioned in https://github.com/rancher/rancher/issues/32002#issuecomment-818374779 

**Steps to reproduce:** 
- Rancher server `v2.4.8`
- Create a RKE cluster (Make sure to not use any SELinux nodes) 
    - 1 etcd+control plane node, 1 worker only node 
    - k8s version = `v1.17.5-rancher1-1` or any version not mentioned in the linked comment 
- Upgrade Rancher to `v2.4.15` or `v2.5.7` (`v2.4.12+` or `v2.5.0+`) 
- Cluster stays in `Active` state (doesn't go to `Updating` state)
- Edit Cluster and change Cluster Name 

**Behavior:** 
- Cluster reconciles and goes through the provisioning steps again 
- Following can be seen in the logs for etcd/control plane node: 
```
2021/04/20 19:22:20 [INFO] Renaming container [kube-proxy] to [old-kube-proxy] on host [165.227.22.173], try #1
2021/04/20 19:22:20 [INFO] Starting container [kube-proxy] on host [165.227.22.173], try #1
2021/04/20 19:22:21 [INFO] Removing container [old-kube-proxy] on host [165.227.22.173], try #1
```
- Following can be seen in the logs for worker only node: 
```
2021/04/20 19:22:35 [INFO] binds changed for [kube-proxy] old: [/etc/kubernetes:/etc/kubernetes:z /run:/run /lib/modules:/lib/modules:z,ro] new [/etc/kubernetes:/etc/kubernetes:z /run:/run /lib/modules:/lib/modules:ro]
``` 

**Expected Behavior:** 
- Changing cluster name shouldn't result into cluster reconciling again and it should stay in `Active` state.

**Comment by kinarashah** [comment]
This issue is expected because of the binds were changed for `kube-proxy`. 

It'd help to release note this, 

**Release Note:** 
For users upgrading from `<=v2.4.8` to `v2.4.12+`/`v2.5.0+` , please note that Editing cluster and changing any trivial field like cluster name will result into cluster reconciliation and upgrading `kube-proxy` on all nodes [because of a change in `kube-proxy` binds](https://github.com/rancher/rke/pull/2214#issuecomment-680001568). This only happens on the first edit and later edits shouldn't affect the cluster.

**Comment by sowmyav27** [comment]
**Reproduced the original issue**

- On 2.4.8 deploy RKE clusters with k8s version - 1.18.17, v1.16.15 
- Upgrade from 2.4.8 to 2.5.7
- v1.16.15 --> does not go into updating state
- 1.18.17 --> goes into updating state because of [issue](https://github.com/rancher/rancher/issues/32002#issuecomment-818374779)
- Edit and save `v1.16.15` cluster without making any changes in the cluster
- Cluster goes into Updating state
- rancher Logs show

```
2021/04/20 22:46:38 [INFO] checking cluster [c-bv5wx] for worker nodes upgrade
2021/04/20 22:46:38 [INFO] binds changed for [kube-proxy] old: [/etc/kubernetes:/etc/kubernetes:z /run:/run /lib/modules:/lib/modules:z,ro] new [/etc/kubernetes:/etc/kubernetes:z /run:/run /lib/modules:/lib/modules:ro]
2021/04/20 22:46:38 [INFO] checking cluster [c-bv5wx] for worker nodes upgrade
2021/04/20 22:46:38 [INFO] binds changed for [kube-proxy] old: [/etc/kubernetes:/etc/kubernetes:z /run:/run /lib/modules:/lib/modules:z,ro] new [/etc/kubernetes:/etc/kubernetes:z /run:/run /lib/modules:/lib/modules:ro]
```
