### ISSUE TITLE
Unable to deploy v1 logging on hosted GKEv2 - log-aggregator unable to mkdir on read-only file system

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#32211]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- deploy upstream cluster with rancher/rancher:v2.5-head `41f173a`
- from the rancher emberUI provision Hosted GKEv2 cluster - use default values from the wizard
- deploy v1 cluster/project level logging `rancher-logging-0.2.4` and configure it to use fluentd as a target (GKE cluster->Tools->Logging)
- go to System project on GKE cluster, click Resources->Workload and check if `rancher-logging-log-aggregator-linux` DaemonSet in namespace `cattle-logging` is ready

**Result:**
- any pod from `rancher-logging-log-aggregator-linux` DaemonSet is not running and reporting:
```
Error: failed to start container "log-aggregator": Error response from daemon: error while creating mount source path '/usr/libexec/kubernetes/kubelet-plugins/volume/exec': mkdir /usr/libexec/kubernetes: read-only file system
```
Used image for the pods `rancher/log-aggregator:v0.1.7`
Anyway the logs from the GKE cluster are showing in fluentd logs.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.5-head `41f173a`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted GKEv2 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): default
- Kubernetes version (use `kubectl version`): `v1.17.17-gke.3000`

**Comment by thehejik** [comment]
The same chart does work normally on local RKE and also on downstream Amazon EKS cluster.

**Comment by cmurphy** [comment]
Was this something that worked on GKE v1? The read-only filesystem for GKE nodes isn't new.

**Comment by izaac** [comment]
The default image value in 2.5.7 is `Ubuntu`, in GKEv2 the default is `Container Optimized OS` could that be the reason? @cmurphy @thehejik

**Comment by thehejik** [comment]
> The default image value in 2.5.7 is `Ubuntu`, in GKEv2 the default is `Container Optimized OS` could that be the reason? @cmurphy @thehejik

@izaac Indeed, looks like the reason - it works with GKE image `Ubuntu with Docker` ~ `ubuntu-gke-1804-1-17-v20201216`. It doesn't work with default `Container-Optimized OS with Docker` ~ `gke-11717-gke3000-cos-81-12871-1226-0-v210223-pre`

**Comment by cmurphy** [comment]
Good find @izaac, that seems to be it. According to @westlywright the COS image is the default from GCP and so that's why it's the default in the GKE v2 UI. v2 logging should work with the COS image since there's been work done to avoid writing to the node filesystem. Would an acceptable fix for this be to document (somewhere?) that logging v1 will only work if the node pool image type is changed to Ubuntu? Or do we need to change the default back to Ubuntu to maintain backwards compatibility?

**Comment by cmurphy** [comment]
I added a note about this to the docs here: https://staging.rancher.com/docs/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/gke/config-reference/#image-type
