### ISSUE TITLE
Close X button in Access Control message on top does nothing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3221]
version - master jan 07

Steps:
1.  go to rancher and makes sure you are in unauthenticated state
2.  Click on the X in Access Control message window, that is in the top menu area.
![image](https://cloud.githubusercontent.com/assets/11514927/12211415/14a848f8-b61e-11e5-9b8b-b60adc10e3bf.png)

Result:
Nothing happens

Expected:
Message to go away or no X to exist

**Comment by vincent99** [comment]
This is a side-effect of #3007, setting the preference fails so the UI isn't updated.
