### ISSUE TITLE
[Forwardport] Project network isolation can be enabled if RKE network plugin supports network policies

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#32220]
Issue: rancher/rancher#31338 
PR: https://github.com/rancher/rancher/pull/32193

**Comment by ryansann** [comment]
PR has been merged

**Comment by bmdepesa** [comment]
Currently blocked by https://github.com/rancher/rancher/issues/32659

**Comment by bmdepesa** [comment]
rancher/rancher:v2.6-head 6c14c33

Tested enabling Project Network Isolation with the following CNIs for RKE1 clusters:
* Canal
* Calico
* Weave

## Test Case
* Create multiple projects and deploy 2 workloads in each using `ranchertest/mytestcontainer` image
* From each project, `ping` a workload in the project and in another project
  * Workloads within the same project have a successful ping
  * Workloads in separate projects are not able to communicate
