### ISSUE TITLE
When sorting by State, Started-Once is in middle of running states

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3222]
Version - master jan 07

Steps:
1.  Create a bunch of containers, some that will continuously run and other that will only run once.  The names of the Started-Once should be between the Running containers
2.  Go to the Containers page or the Service details page and sort by state

Results:
The Started-Once in interspersed with the Running.
![image](https://cloud.githubusercontent.com/assets/11514927/12211896/c2baf2bc-b621-11e5-9c7f-aee364b56d3b.png)

Expected:
They should be separate as they are two different states and we display them as two different states.

**Comment by vincent99** [comment]
It was sorting on by the color, not then additionally the state text..

**Comment by tfiduccia** [comment]
version 1/19
Verified Fixed
