### ISSUE TITLE
Unable to start longhorn when deploying app

### ISSUE THREAD

**Issue by orwtech** [rancher/rancher#32224]
Keep writing: 

Deployment is not ready: longhorn-system/longhorn-driver-deployer. 0 out of 1 expected pods are ready

Goes on for a looooong time and ends with:

Error: UPGRADE FAILED: timed out waiting for the condition

Rancher 2.5.5
Longhorn 1.1.0000

helm upgrade --history-max=5 --install=true --namespace=longhorn-system --timeout=10m0s --values=/home/shell/helm/values-longhorn-crd-1.1.000.yaml --version=1.1.000 --wait=true longhorn-crd /home/shell/helm/longhorn-crd-1.1.000.tgz
--
Tue, Feb 23 2021 4:43:07 pm | checking 8 resources for changes
Tue, Feb 23 2021 4:43:07 pm | Looks like there are no changes for CustomResourceDefinition "engines.longhorn.io"
Tue, Feb 23 2021 4:43:07 pm | Looks like there are no changes for CustomResourceDefinition "replicas.longhorn.io"
Tue, Feb 23 2021 4:43:07 pm | Looks like there are no changes for CustomResourceDefinition "settings.longhorn.io"
Tue, Feb 23 2021 4:43:07 pm | Looks like there are no changes for CustomResourceDefinition "volumes.longhorn.io"
Tue, Feb 23 2021 4:43:07 pm | Looks like there are no changes for CustomResourceDefinition "engineimages.longhorn.io"
Tue, Feb 23 2021 4:43:07 pm | Looks like there are no changes for CustomResourceDefinition "nodes.longhorn.io"
Tue, Feb 23 2021 4:43:07 pm | Looks like there are no changes for CustomResourceDefinition "instancemanagers.longhorn.io"
Tue, Feb 23 2021 4:43:08 pm | Looks like there are no changes for CustomResourceDefinition "sharemanagers.longhorn.io"
Tue, Feb 23 2021 4:43:08 pm | beginning wait for 8 resources with timeout of 10m0s
Tue, Feb 23 2021 4:43:10 pm | Release "longhorn-crd" has been upgraded. Happy Helming!
Tue, Feb 23 2021 4:43:10 pm | NAME: longhorn-crd
Tue, Feb 23 2021 4:43:10 pm | LAST DEPLOYED: Tue Feb 23 15:43:07 2021
Tue, Feb 23 2021 4:43:10 pm | NAMESPACE: longhorn-system
Tue, Feb 23 2021 4:43:10 pm | STATUS: deployed
Tue, Feb 23 2021 4:43:10 pm | REVISION: 3
Tue, Feb 23 2021 4:43:10 pm | TEST SUITE: None
Tue, Feb 23 2021 4:43:10 pm |  
Tue, Feb 23 2021 4:43:10 pm | ---------------------------------------------------------------------
Tue, Feb 23 2021 4:43:10 pm | SUCCESS: helm upgrade --history-max=5 --install=true --namespace=longhorn-system --timeout=10m0s --values=/home/shell/helm/values-longhorn-crd-1.1.000.yaml --version=1.1.000 --wait=true longhorn-crd /home/shell/helm/longhorn-crd-1.1.000.tgz
Tue, Feb 23 2021 4:43:10 pm | ---------------------------------------------------------------------
Tue, Feb 23 2021 4:43:10 pm | helm upgrade --history-max=5 --install=true --namespace=longhorn-system --timeout=10m0s --values=/home/shell/helm/values-longhorn-1.1.000.yaml --version=1.1.000 --wait=true longhorn /home/shell/helm/longhorn-1.1.000.tgz
Tue, Feb 23 2021 4:43:10 pm | checking 16 resources for changes
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for ServiceAccount "longhorn-service-account"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for ConfigMap "longhorn-default-setting"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for ConfigMap "longhorn-storageclass"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for ClusterRole "longhorn-role"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for ClusterRole "longhorn-admin"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for ClusterRole "longhorn-edit"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for ClusterRole "longhorn-view"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for ClusterRoleBinding "longhorn-bind"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for Role "longhorn-psp-role"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for RoleBinding "longhorn-psp-binding"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for Service "longhorn-backend"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for DaemonSet "longhorn-manager"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for Deployment "longhorn-driver-deployer"
Tue, Feb 23 2021 4:43:10 pm | Looks like there are no changes for Deployment "longhorn-ui"
Tue, Feb 23 2021 4:43:10 pm | beginning wait for 16 resources with timeout of 10m0s
Tue, Feb 23 2021 4:43:12 pm | Deployment is not ready: longhorn-system/longhorn-driver-deployer. 0 out of 1 expected pods are ready
Tue, Feb 23 2021 4:43:14 pm | Deployment is not ready: longhorn-system/longhorn-driver-deployer. 0 out of 1 expected pods are ready
Tue, Feb 23 2021 4:43:16 pm | Deployment is not ready: longhorn-system/longhorn-driver-deployer. 0 out of 1 expected pods are ready
Tue, Feb 23 2021 4:43:18 pm | Deployment is not ready: longhorn-system/longhorn-driver-deployer. 0 out of 1 expected pods are ready
...
...
...
Tue, Feb 23 2021 4:53:10 pm | Deployment is not ready: longhorn-system/longhorn-driver-deployer. 0 out of 1 expected pods are ready
Tue, Feb 23 2021 4:53:10 pm | Error: UPGRADE FAILED: timed out waiting for the condition

**Comment by gaktive** [comment]
This was lost in a non-Zube view within the Dashboard for a while. This doesn't look UI related so passing this on to the main Rancher repo for investigation.
