### ISSUE TITLE
Rancher unable to fetch userinfo seen for users on master-head

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#32230]
Issue seen only on master-head [master-1c3629fbe520d4cfe66b95c31cfdd2f3946f39dc-head]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. From global --> security --> users --> create users --> Users name has unable to fetch user info
Following is seen in the logs :
``` 
baseType: "error", code: "ServerError", message: "users.management.cattle.io "" not found",…}
baseType: "error"
code: "ServerError"
message: "users.management.cattle.io "" not found"
status: 500
type: "error
**Result:**
```

**Other details that may be helpful:**
Create a cluster and create a project. Add the user created above with any roles, following error is seen for the user but the creation goes through 
<img width="300" alt="Screen Shot 2021-04-19 at 5 16 56 PM" src="https://user-images.githubusercontent.com/38144301/115318670-0f7a2800-a133-11eb-8c41-bf5dd4548029.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-1c3629fbe520d4cfe66b95c31cfdd2f3946f39dc-head
- Installation option (single install/HA): Single

Similar to https://github.com/rancher/rancher/issues/21417

**Comment by Jono-SUSE-Rancher** [comment]
What auth provider did you use? Does this happen with across all users or just one user? Can you reproduce it again with the same auth provider setup?

**Comment by sowmyav27** [comment]
Dup of https://github.com/rancher/rancher/issues/32117
