### ISSUE TITLE
pushprox-kube-etcd-client does not tolerate node-role.kubernetes.io/master:NoSchedule taint

### ISSUE THREAD

**Issue by brandond** [rancher/rancher#32245]
The current example breaks the Rancher Monitoring package when applied during the installation.

```yaml
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
```

This breaks the pushprox-kube-etcd-client which has a toleration expecting a taint of `node-role.kubernetes.io/master` with an effect of `NoSchedule`

```
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Equal
```

#### Proposed Changes ####

Change example to:

```yaml
node-taint:
  - "node-role.kubernetes.io/master:NoSchedule"
```

#### Types of Changes ####

Updates documentation to use upstream standard taints.

#### Challenges to Accepting This Change ####

After reconfiguring my Ansible automation for building rke2 clusters I found out that if one applies this change, it breaks the helm controller integration due to the fact that the controller has its taints for the jobs it creates hard coded.

https://github.com/k3s-io/helm-controller/blob/4ed68f1ecd2ba59cdf5090fb2c166f7055f8cf99/pkg/helm/controller.go#L287

Applying this change without changing the behavior of the helm controller would break the RKE2 bootstrapping process.
> Submitted by @estenrye in rancher/rke2#901

**Comment by estenrye** [comment]
Reproduction Instructions:

1. Provision 8 Ubuntu hosts

| hostname | ip address |
| --- | --- |
| haproxy01 | 10.5.99.18 |
| haproxy02 | 10.5.99.19 |
| controlplane01 | 10.5.99.21 |
| controlplane02 | 10.5.99.22 |
| controlplane03 | 10.5.99.23 |
| node01 | 10.5.99.31 |
| node02 | 10.5.99.32 |
| node03 | 10.5.99.33 |

kube-api server  is load balanced at 10.5.99.20

2. Clone https://github.com/estenrye/slides
3. Perform the following steps

```bash
#### provision dns as needed.  dev.ryezone.com entries are already available in Cloudflare ####
ansible-playbook -i dev-cluster_inventory.yml rancher_01_dns.yml

#### configure HAProxy Load Balancer ####
ansible-playbook -i dev-cluster_inventory.yml rancher_02_haproxy.yml

#### initialize first server node ####
ansible-playbook -i dev-cluster_inventory.yml rancher_03_rke2.yml

#### initialize remaining server and agent nodes ####
ansible-playbook -i dev-cluster_inventory.yml rancher_04_rke2_additional_nodes.yml

#### remove drain configuration in haproxy directing all kube api and node join traffic to initial node. ####
ansible-playbook -i dev-cluster_inventory.yml rancher_05_undrain-additional-controlplane-nodes.yml

#### install applications ####
ansible-playbook -i dev-cluster_inventory.yml rancher_06_install_apps.yml
```

4. Manually join the existing cluster.
5. Manually install the Rancher Monitoring application through the user interface.  Use default options.

**Comment by brandond** [comment]
As @aiyengar2 pointed out on Slack, the tolerations are part of the chart values (`rke2ControllerManager.clients.tolerations`) and can be overridden.

Ref: https://github.com/rancher/charts/blob/cbd4e36640ec51912df13769b93fb85499fcd166/charts/rancher-monitoring/rancher-monitoring/14.5.100-rc07/values.yaml#L182

**Comment by Martin-Weiss** [comment]
How do we "fix" the taints for all existing rke2 deployments in case we change what was documented so far?

**Comment by estenrye** [comment]
@brandond I created a video of the behavior I experience when trying to deploy the rancher monitoring helm chart.

https://youtu.be/AukiwNIbFPM

I also demonstrated a workaround in the video to get things to work after deployment.

**Comment by estenrye** [comment]
As I demonstrated in the video, I believe the root cause is here:

https://github.com/rancher/charts/blob/cbd4e36640ec51912df13769b93fb85499fcd166/charts/rancher-monitoring/rancher-monitoring/14.5.100-rc07/values.yaml#L226-L228

I think you may be able to resolve it by replacing it with this:

```yaml
    - effect: "NoExecute"
      operator: "Exists"
    - effect: "NoSchedule"
      operator: "Exists"
```

**Comment by estenrye** [comment]
Tried using the builtin rke2 upgrade controller in rancher and ran into the same issue where the workload does not have the CriticalAddonsOnly taint.

![image](https://user-images.githubusercontent.com/17356933/115710120-9dbefb80-a337-11eb-899e-fe4662679265.png)

**Comment by estenrye** [comment]
Continuing on the upgrade controller issues.  Once I got the system-upgrade-controller to deploy, none of the workloads it spawns support the CriticalAddonsOnly taint for upgrading RKE2 server nodes.

```
automation-user@controlplane01:~$ kubectl describe pod -n cattle-system apply-rke2-master-plan-on-controlplane01-with-8328420e692-nwkzl
Name:           apply-rke2-master-plan-on-controlplane01-with-8328420e692-nwkzl
Namespace:      cattle-system
Priority:       0
Node:           <none>
Labels:         controller-uid=7127949b-5698-404e-a174-742605cdab1b
                job-name=apply-rke2-master-plan-on-controlplane01-with-8328420e692-547ba
                plan.upgrade.cattle.io/rke2-master-plan=8328420e692ecd89c06ecce046b0f6c089a2f7b6331567e81bfb6f37
                upgrade.cattle.io/controller=system-upgrade-controller
                upgrade.cattle.io/node=controlplane01
                upgrade.cattle.io/plan=rke2-master-plan
                upgrade.cattle.io/version=v1.20.5-rke2r1
Annotations:    kubernetes.io/psp: global-unrestricted-psp
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  Job/apply-rke2-master-plan-on-controlplane01-with-8328420e692-547ba
Init Containers:
  drain:
    Image:      rancher/kubectl:v1.18.0
    Port:       <none>
    Host Port:  <none>
    Args:
      drain
      controlplane01
      --pod-selector
      !upgrade.cattle.io/controller
      --ignore-daemonsets
      --delete-local-data
      --force
    Environment:
      SYSTEM_UPGRADE_NODE_NAME:             (v1:spec.nodeName)
      SYSTEM_UPGRADE_POD_NAME:             apply-rke2-master-plan-on-controlplane01-with-8328420e692-nwkzl (v1:metadata.name)
      SYSTEM_UPGRADE_POD_UID:               (v1:metadata.uid)
      SYSTEM_UPGRADE_PLAN_NAME:            rke2-master-plan
      SYSTEM_UPGRADE_PLAN_LATEST_HASH:     8328420e692ecd89c06ecce046b0f6c089a2f7b6331567e81bfb6f37
      SYSTEM_UPGRADE_PLAN_LATEST_VERSION:  v1.20.5-rke2r1
    Mounts:
      /host from host-root (rw)
      /run/system-upgrade/pod from pod-info (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from system-upgrade-token-lhrr4 (ro)
Containers:
  upgrade:
    Image:      rancher/rke2-upgrade:v1.20.5-rke2r1
    Port:       <none>
    Host Port:  <none>
    Environment:
      SYSTEM_UPGRADE_NODE_NAME:             (v1:spec.nodeName)
      SYSTEM_UPGRADE_POD_NAME:             apply-rke2-master-plan-on-controlplane01-with-8328420e692-nwkzl (v1:metadata.name)
      SYSTEM_UPGRADE_POD_UID:               (v1:metadata.uid)
      SYSTEM_UPGRADE_PLAN_NAME:            rke2-master-plan
      SYSTEM_UPGRADE_PLAN_LATEST_HASH:     8328420e692ecd89c06ecce046b0f6c089a2f7b6331567e81bfb6f37
      SYSTEM_UPGRADE_PLAN_LATEST_VERSION:  v1.20.5-rke2r1
    Mounts:
      /host from host-root (rw)
      /run/system-upgrade/pod from pod-info (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from system-upgrade-token-lhrr4 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  host-root:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:  Directory
  pod-info:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  system-upgrade-token-lhrr4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  system-upgrade-token-lhrr4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  58m   default-scheduler  0/6 nodes are available: 1 node(s) had taint {CriticalAddonsOnly: true}, that the pod didn't tolerate, 5 node(s) didn't match node selector.
  Warning  FailedScheduling  58m   default-scheduler  0/6 nodes are available: 1 node(s) had taint {CriticalAddonsOnly: true}, that the pod didn't tolerate, 5 node(s) didn't match node selector.
```

**Comment by bashofmann** [comment]
I think we should separate the system-upgrade-controller and monitoring into separate issues, since these are separate components.

For the system-upgrade-controller there is already an issue here https://github.com/rancher/rancher/issues/32050.

**Comment by estenrye** [comment]
Workaround for deployment with Fleet:

## Rancher Monitoring CRD Fleet Deployment.  

### fleet.yml

```yaml
defaultNamespace: cattle-monitoring-system
helm:
  chart: rancher-monitoring-crd
  repo: https://charts.rancher.io
  releaseName: rancher-monitoring-crd
  version: 9.4.203
targetCustomizations:
- helm:
    clusterSelector: {}
```

## Rancher Monitoring Fleet Deployment

### fleet.yml

```yaml
defaultNamespace: cattle-monitoring-system
helm:
  chart: rancher-monitoring
  repo: https://charts.rancher.io
  releaseName: rancher-monitoring
  version: 9.4.203
targetCustomizations:
- helm:
    values:
      rke2Etcd:
        clients:
          tolerations:
            - effect: NoExecute
              key: CriticalAddonsOnly
              value: "true"
              operator: Equal
    clusterSelector: {}
```

**Comment by aiyengar2** [comment]
Maybe the solution here would be to just remove the [`key`](https://github.com/rancher/charts/blob/cbd4e36640ec51912df13769b93fb85499fcd166/charts/rancher-monitoring/rancher-monitoring/14.5.100-rc07/values.yaml#L227) from the toleration. No other PushProx exporter keys tolerations either by default, so this might be a good step to take in general. And a user who wanted to override this toleration to be scoped to specific keys could always modify the values.yaml.

@brandond any thoughts / concerns about this? Otherwise, I'm going to go ahead with this approach for the fix.

**Comment by slickwarren** [comment]
on master-head (4f9850d), I was able to reproduce this issue by doing the following:
* bring up an RKE2 cluster
* taint CP nodes with `CriticalAddonsOnly=true:NoExecute`
* install monitoring v2 (v14.5.101+)
* observe no metrics in grafana -> etcd
* no pods deployed in pushprox-kube-etcd-client

**Comment by brandond** [comment]
Sorry I missed the tag @aiyengar2 but I agree, changing `key: node-role.kubernetes.io/master        operator: "Equal"` to `operator: "Exists"` sounds good to me.

**Comment by aiyengar2** [comment]
Forward ported to 2.6

**Comment by slickwarren** [comment]
currently blocked by https://github.com/rancher/rancher/issues/32852 (need to use dashboard to install monitoring v2)

**Comment by slickwarren** [comment]
on master-head (f90b36e), I was able to verify that pushprox-etcd workload is deploying pods, and the grafana `etcd` page does have metrics coming in:
* bring up an RKE2 cluster
* taint CP nodes with `CriticalAddonsOnly=true:NoExecute`
* install monitoring v2 (14.5.101+up14.5.0)
* observe metrics in grafana -> etcd
* pods succefully deployed in pushprox-kube-etcd-client
