### ISSUE TITLE
[UI] Import cluster doesn't show registration command after specifying additional environment variables

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#32242]
rancher/rancher:v2.5-head 31f00c1, master-head ca3ea81
rancher/ui:v2.5-dev, vmaster-dev

## Steps:
* Import an existing cluster
* Specify some Agent Environment Variables in the `Advanced` import options
* Save

## Results
* The user is directed to the global dashboard / cluster listing instead of being shown the cluster registration command

## Expected
* The cluster registration / import command is displayed immediately

This does not occur when no agent environment variables are specified - the cluster registration command appears as expected.

**Comment by codyrancher** [comment]
### Note for QA
This actually has nothing to do with the Agent Environment Variables. This was occurring spuriously and I never found a pattern to reproduce it consistently so you'll just have to keep trying to reproduce until you're satisfied this works.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.8-rc9
rancher/rancher:master-head 

* Created several (~10 each) of imported clusters with and without agent environment variables
* Cluster import registration command was displayed every time
