### ISSUE TITLE
[rancher alerting drivers] Upgrading chart does not deploy configmap for newly selected provider

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32249]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy monitoring
* deploy rancher monitoring drivers
  * enable MS teams
* upgrade existing rancher-monitoring-drivers deployment
  * enable SMS

**Result:**
* deployment times out with pod from sachet deployment failing 
<img width="774" alt="Screen Shot 2021-04-20 at 3 25 10 PM" src="https://user-images.githubusercontent.com/16691014/115471316-9e974680-a1ec-11eb-9f9f-a22672292911.png">

**Other details that may be helpful:**
found when testing rancher/rancher#29951

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8-rc6
- Installation option (single install/HA): single

**Comment by jiaqiluo** [comment]
This issue can be tested on `rancher-alerting-drivers` chart version `1.0.100-rc03`

**Comment by slickwarren** [comment]
tested on v2.5.8-rc7 on chart version 1.0.100-rc03:
* deploy monitoring
* deploy rancher monitoring drivers
  * enable MS teams
* upgrade existing rancher-monitoring-drivers deployment
  * enable SMS
this workflow is now working as expected
