### ISSUE TITLE
Category not showing up in Upgrade screen

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3224]
version - master jan 07

Steps:
1. Go to catalog and add Elasticsearch with older version
2. Wait for it to complete and click on Upgrade Available button

Results: Category is empty, this is true for all catalogs that have upgrades.
![image](https://cloud.githubusercontent.com/assets/11514927/12212162/547cc034-b624-11e5-99b5-85c28d36e29a.png)

Expected:
We should fill in the category.  Elasticsearch is ELK and Route53 is RancherServices.

**Comment by vincent99** [comment]
This is an issue with the response for `templateversion` vs `template` in the API..

![image](https://cloud.githubusercontent.com/assets/753917/12251344/9204ca0a-b88b-11e5-9a99-67b0f22e6730.png)

![image](https://cloud.githubusercontent.com/assets/753917/12251348/9cd2b2a8-b88b-11e5-8ffb-b5b3b06ab04e.png)

**Comment by tfiduccia** [comment]
Version - 1.2.0-pre4-rc10
This looks like it was fixed, so I'm closing
