### ISSUE TITLE
[Forwardport] Docs hyperlink on Rancher UI points to Archived docs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32258]
Forwardport of https://github.com/rancher/rancher/issues/31860

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 55f0bb2`

The "Help & Docs" link redirects the user to archived docs: `https://rancher.com/docs/rancher/v2.x/en`
This is also seen in Dashboard following the doc link in `https://.../dashboard/support`

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 54d4afc`
`Help and Docs` link points to `https://rancher.com/docs/rancher/v2.5/en/`
![Screen Shot 2021-06-16 at 9 20 48 AM](https://user-images.githubusercontent.com/57409052/122256872-4eeb9900-ce84-11eb-8129-8804f417ddb0.png)
