### ISSUE TITLE
rancher/windows_exporter-package missing from rancher-windows-images.txt

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32265]
**What kind of request is this:**
bug

**Steps to reproduce:**

- [Populate the private registry](https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/populate-private-registry/) with windows images using `rancher-windows-images.txt` from `v2.5.8-rc7`
- Update the repo tags from the Linux bastion/registry 

`./rancher-load-images.sh --windows-image-list ./rancher-windows-images.txt --windows-versions "1809" -r <private_registry_url>`

**Result:**

```
Error response from daemon: No such image: rancher/windows_exporter-package:v0.0.1
The push refers to repository [<private_registry_url>/rancher/windows_exporter-package]
An image does not exist locally with the tag: <private_registry_url>/rancher/windows_exporter-package
```

This is the `rancher-windows-images.txt` content:

```
rancher/configmap-reload:v0.3.0-rancher4
rancher/fluentd:v0.1.24
rancher/hyperkube:v1.17.17-rancher2
rancher/hyperkube:v1.18.18-rancher1
rancher/hyperkube:v1.19.10-rancher1
rancher/hyperkube:v1.20.6-rancher1
rancher/kubelet-pause:v0.1.6
rancher/rancher-agent:v2.5.8-rc7
rancher/rke-tools:v0.1.74
rancher/wmi_exporter-package:v0.0.7
```

**Environment information**
- Rancher version: `v2.5.8-rc7`
- Installation option: single airgap RKE

**Comment by aiyengar2** [comment]
Reassigned to @nickgerace since the fix for this is being tackled in https://github.com/rancher/rancher/issues/32290

cc: @cbron @SheilaghM

**Comment by aiyengar2** [comment]
After talking to @nickgerace , I re-assigned this back to me since chart changes are required to add the `os` tag to each image.

**Comment by izaac** [comment]
Rancher version: `2.5.8-rc10`

I still hit this issue on rc10. 

```
Error response from daemon: No such image: rancher/windows_exporter-package:v0.0.1
The push refers to repository [<private_registry_host>/rancher/windows_exporter-package]
An image does not exist locally with the tag: <private_registry_host>/rancher/windows_exporter-package
```

[rancher-windows-images.txt](https://github.com/rancher/rancher/releases/download/v2.5.8-rc10/rancher-windows-images.txt) content:

```
rancher/configmap-reload:v0.3.0-rancher4
rancher/fluent-bit:1.6.10
rancher/fluentd:v0.1.24
rancher/hyperkube:v1.17.17-rancher2
rancher/hyperkube:v1.18.18-rancher1
rancher/hyperkube:v1.19.10-rancher1
rancher/hyperkube:v1.20.6-rancher1
rancher/kubelet-pause:v0.1.6
rancher/rancher-agent:v2.5.8-rc10
rancher/rke-tools:v0.1.74
rancher/wmi_exporter-package:v0.0.7
```

**Comment by aiyengar2** [comment]
In rancher/rancher master today, I see the following in rancher-windows-images.txt on trying to build:

```
rancher/configmap-reload:v0.3.0-rancher4
rancher/fluent-bit:1.6.10
rancher/fluentd:v0.1.24
rancher/hyperkube:v1.15.12-rancher1
rancher/hyperkube:v1.16.7-rancher1
rancher/hyperkube:v1.17.3-rancher1
rancher/hyperkube:v1.18.17-rancher1
rancher/hyperkube:v1.19.10-rancher1
rancher/hyperkube:v1.20.6-rancher1
rancher/kubelet-pause:v0.1.3
rancher/kubelet-pause:v0.1.6
rancher/rancher-agent:local-test
rancher/rke-tools:v0.1.52
rancher/rke-tools:v0.1.56
rancher/rke-tools:v0.1.74
rancher/windows_exporter-package:v0.0.1
rancher/wins:v0.1.0
rancher/wmi_exporter-package:v0.0.7
```

So this issue will probably be resolved in rc11. Moving back to test.

**Comment by nickgerace** [comment]
Moved to waiting for RC for rc11 @aiyengar2

**Comment by izaac** [comment]
Rancher version `v2.5.8-rc11`

`windows_export-package` is included in the `rancher-windows-images.txt`
Monitoring v2 was deployed for type Windows.

Namespace `cattle-monitoring-system`
Daemonset `rancher-monitoring-windows-exporter`

Pods are able to come up active for the windows exporter.
