### ISSUE TITLE
Upgrade vSphere CSI Chart to v2.2.0

### ISSUE THREAD

**Issue by ron1** [rancher/rancher#32262]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

Upgrade vSphere CSI Chart to v2.2.0

**Comment by fabiorauber** [comment]
Still needed.

**Comment by PennyScissors** [comment]
Closing this since CSI is currently at v2.2.1. It was updated [here](https://github.com/rancher/charts/pull/1325) to address other issues related to CVEs.
