### ISSUE TITLE
[Logging v2] Provide option to only collect Linux node logs on Windows Clusters

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#32264]
Since `global.cattle.windows.enabled` is an immutable field set by the dashboard, we need another field for enabling/disabling Windows log collection, or we need to evaluate using nil flags.

- Original issue: https://github.com/rancher/rancher/issues/28721
- Source issue: https://github.com/rancher/dashboard/issues/2684
- Source comment: https://github.com/rancher/dashboard/issues/2684#issuecomment-824072685

**Comment by nickgerace** [comment]
Opened as a result of: rancher/dashboard#2684 (comment)

**Comment by izaac** [comment]
Rancher version: `v2.5.8-rc9` 
Logging chart version: `3.9.400` (no RC is shown)

Scenario Default:
The option is working now, the default if the key doesn't exist is `global.cattle.windows.enabled = true`
nodeagent daemonsets are deployed as expected.


Scenario to False
Setting `global.cattle.windows.enabled = false`, is preserved after chart install.
nodeagent daemonsets are **NOT** deployed as expected.


Scenario Upgrade from True to False (Failed)
The node agents are still present after upgrading `global.cattle.windows.enabled` from `true to `false`.


The commented documentation in `values.yaml` is removed from the Rancher UI `Values YAML` view, we need to make sure is included in the doc issue.

https://github.com/rancher/docs/issues/3141

**Comment by nickgerace** [comment]
> ### Scenario Upgrade from True to False (Failed)
>
> The node agents are still present after upgrading global.cattle.windows.enabled from true to false.

@izaac: confirmed that this is an upstream issue after investigation with @aiyengar2 @paynejacob. Reproduction steps have been filed in the upstream issue: https://github.com/banzaicloud/logging-operator/issues/725

**Comment by nickgerace** [comment]
Moving this to `To Test` for the following scenarios:

- Install with default values
- Install, `global.cattle.windows.enabled` set to `true`
- Install, `global.cattle.windows.enabled` set to `false`

Creating a new issue to track the following scenario:

- Upgrade, `global.cattle.windows.enabled` changed to `false` when already to `true`

**Comment by izaac** [comment]
Rancher version: `v2.5.8-rc9`
Logging Chart version: `3.9.400` (latest build as this is not showing the RC anymore in 2.5)


The following scenarios worked as expected.


- Install with default values
- Install, `global.cattle.windows.enabled` set to `true`
- Install, `global.cattle.windows.enabled` set to `false`
