### ISSUE TITLE
[Monitoring V2] Provide a way to prevent deploying Windows components on Windows clusters

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#32274]
Currently, the only way to trigger whether or not to deploy Monitoring components onto a Windows cluster is to set `global.cattle.windows.enabled` to true or false.

However, in the Cluster Explorer UI, you will not be able to upgrade Monitoring to set this value to false since the UI automatically set the value to true if the chart itself contains `global.cattle.windows.enabled=false` (since it is considered to be unchanged by the user, which means it should be overridden).

The fix for this would be to remove `global.cattle.windows.enabled=false` in the values.yaml of the Helm chart and change calls to that field to check whether the field is invalid + whether it is set to true before processing it via Helm, as described in https://github.com/rancher/charts/pull/1133#pullrequestreview-641502481.

**Comment by SheilaghM** [comment]
LOE 0.5 days.  Small change we believe it should be fixed before release.

**Comment by thehejik** [comment]
**Test report:**
I installed v2 `rancher-monitoring-14.5.100` with `global.cattle.windows.enabled=true` on windows 1909 cluster deployed on top of `rancher:2.5.8-rc10` - windows-exporter pods were deployed and running.

Then upgraded with `global.cattle.windows.enabled=false` set and windows-exporter pods/DS was gone.

Also the opposite way when installed with `global.cattle.windows.enabled=false` and upgraded with `global.cattle.windows.enabled=true` worked as expected.

I didn't notice that `windows.enabled=true` is commented out - it was either available/enabled in values.yaml when `Windows` clusterType was selected or it wasn't there at all when another clusterType was selected.

**Comment by slickwarren** [comment]
reopening for test based on comments here https://github.com/rancher/rancher/issues/32530#issuecomment-832180717

**Comment by slickwarren** [comment]
on v2.5.8-rc19, I was able to verify that:
* deploying a windows cluster with default settings also deploys windowsExporter
* modifying the deploy yaml to disable windowsExporter using the following settings does disable correctly (added at the bottom of the yaml.  set `true` to `false`)
<img width="253" alt="Screen Shot 2021-05-05 at 10 12 10 AM" src="https://user-images.githubusercontent.com/16691014/117182897-c6a9ac80-ad8b-11eb-8e6b-b4ba625d84fe.png">
* re-enabling windowsExporter re deploys the pods
* deploying clean install of monitoring with windowsExporters disabled does not deploy windowsExporter pods

**Note**: the new way to disable windowsExporter is `windowsExporter.clients.enabled=false`
