### ISSUE TITLE
Can change main admin account to user

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3227]
version - master jan 07

Comment:
Before I authenticated, I was able to go to Account and make my main admin account a user.  This seems dangerous and maybe we shouldn't allow them to do this with their main admin account.

**Comment by vincent99** [comment]
@hibooboo2 Is this prevented by your change to disallow having no admins?

**Comment by deniseschannon** [comment]
Verified with v0.63.0 that this is no longer possible.

![screen shot 2016-03-14 at 12 24 08 pm](https://cloud.githubusercontent.com/assets/11410997/13757028/dd203aa8-e9df-11e5-8c30-b62255c1e5fb.png)
