### ISSUE TITLE
[Forwardport] rancher-images.txt is missing ToolsSystemImages 

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#32279]
rancher/rancher#31758

**Comment by sowmyav27** [comment]
Validate only in rancher-images.txt for all expected images.

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by brendarearden** [comment]
Validation: PASSED

Validated images from https://github.com/rancher/rancher/blob/v2.6.0-rc1/pkg/apis/management.cattle.io/v3/tools_system_images.go existed in https://github.com/rancher/rancher/releases/download/v2.6.0-rc1/rancher-images.txt
|tools_system_image| rancher_images.txt | Found|
|--------|-------|---------|
|rancher/pipeline-jenkins-server:v0.1.4 | rancher/pipeline-jenkins-server:v0.1.4| TRUE|
|rancher/mirrored-jenkins-jnlp-slave:4.7-1|rancher/mirrored-jenkins-jnlp-slave:4.7-1|TRUE|
|rancher/pipeline-tools:v0.1.16|rancher/pipeline-tools:v0.1.16|TRUE|
|rancher/mirrored-plugins-docker:19.03.8|rancher/mirrored-plugins-docker:19.03.8|TRUE|
|rancher/mirrored-minio-minio:RELEASE.2020-07-13T18-09-56Z|rancher/mirrored-minio-minio:RELEASE.2020-07-13T18-09-56Z|TRUE|
|registry:2|registry:2|TRUE|
|rancher/pipeline-tools:v0.1.16|rancher/pipeline-tools:v0.1.16|TRUE|
|rancher/kube-api-auth:v0.1.5|rancher/kube-api-auth:v0.1.5|TRUE|
