### ISSUE TITLE
[Forwardport]  User created network policies are deleted when disabling Network project isolation on the cluster

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#32278]
Forwardport of: https://github.com/rancher/rancher/issues/30135

Master-head PR: https://github.com/rancher/rancher/pull/32227

**Comment by ryansann** [comment]
PR is merged

**Comment by aaronRancher** [comment]
This issue is validated on Rancher `master-head` `version f3c64f2`

After PNI is disabled, user created network policies do not get deleted. Node port and host port policies are deleted.
