### ISSUE TITLE
[rancher-wins-upgrader] rancher/wins image doesn't show up in air gapped setups

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#32280]
rancher/wins doesn't show up in rancher-images.txt, probably because image and repository is a field within a list as seen [here](https://github.com/rancher/charts/blob/6cbef79083183ff1f0d1e3070de12b343dc61ff3/released/charts/rancher-wins-upgrader/rancher-wins-upgrader/0.0.100/values.yaml#L21-L22).

Needs to be resolved to support wins upgrades in air gapped setups. Alternatively, a user could workaround this issue by using the rancher/windows_exporter-package image instead, although that contains an extra unnecessary binary.

**Comment by sowmyav27** [comment]
@aiyengar2 is this related to this issue - https://github.com/rancher/rancher/issues/32265 ?

**Comment by aiyengar2** [comment]
I think this is unrelated, but I'm not sure. The wins-upgrader chart is different than other charts since the image and repository tag exist in a list, so it's possible our scripts just don't handle that at this point.

But I'm not familiar enough with the scripts to know that off-hand, so may need to investigate.

**Comment by nickgerace** [comment]
I actually do think they are related. I think feature charts Windows images are not being added to `rancher-windows-images.txt`

**Comment by aiyengar2** [comment]
Reassigned to @nickgerace since the fix for this is being tackled in https://github.com/rancher/rancher/issues/32290

cc: @cbron @SheilaghM

**Comment by aiyengar2** [comment]
After talking to @nickgerace , I re-assigned this back to me since chart changes are required to add the `os` tag to each image.

**Comment by slickwarren** [comment]
this appears to be working as of 2.5.8-rc11 (the chart installs successfully)
<img width="929" alt="Screen Shot 2021-04-27 at 5 22 19 PM" src="https://user-images.githubusercontent.com/16691014/116328159-41b40700-a77d-11eb-9c09-a769e2ed376b.png">
