### ISSUE TITLE
No Previous button on Audit Log screen

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3228]
Version - master jan 07

Steps:
1.  Create a bunch of environments, services, hosts, and containers
2.  Go to Audit Log screen
3.  Click on Next at bottom a couple of times

Results:
You go to Next page.  But there is no Previous, only First.  So I can never just go back 1 page.

Expected:
Should really be a previous button so I can go back one.

**Comment by vincent99** [comment]
This is missing from the API.

**Comment by will-chan** [comment]
Closed due to inactivity.
