### ISSUE TITLE
1) Restarting container skips Initializing stage 2) Container may never exit Initializing state

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3229]
Today here are the supported state transitions for health state:

initializing->healthy
healthy->unhealthy
unhealthy->healthy

So when container is created, it goes to initializing state. Then it either goes to healthy state if the health check is successful, or gets stuck in initializing state if health check never succeeds. It never goes from initializing to unhealthy.

Bugs:

1) If health check is misconfigured on a container, it would get stuck in initializing forever, and the service would never reconcile. Solution: add configurable failed health check timeout, and destroy the container in initializing state when it entered this state > currentTime - timeout

2) On a container restart, if init scripts take a bit longer to execute than usual, its possible that health check fails for this container, and it goes to unhealthy state and gets recreated. The correct solution would be - repeat initializing->healthy lifecycle not only for newly created container, but for every container restart.

@ibuildthecloud @will-chan

**Comment by alena1108** [comment]
Updates:

1) Added one extra state transition "reinitializing". So the state transitions are the following:

initializing->healthy
healthy->unhealthy
unhealthy->healthy
healthy->reinitializing
reinitializing->healthy

2) Added 2 extra parameters to the healthCheck API object:

initializingTimeout (milliseconds, null by default)- defines after which time instances in initializing state are going to be removed 
reinitializingTimeout (milliseconds, null by default)  - same as the above, but for reinitializing state

By default those parameters are null, so the instances in initializing/reinitializing states are never gonna be removed by the cleanup thread.

**Comment by alena1108** [comment]
@sangeethah a little more info in addition to my last comment:

Instance goes to reinitializing state on every restart

**Comment by sangeethah** [comment]
Tested with server version - v0.55.0-rc3

1. When restarting containers of service with health check enabled , thee health_state transitions from healthy->reinitializing and reinitializing->healthy

2. set "initializingTimeout"  to 1 minute when configuring health check for a services. 
Misconfigure health check for  this service, so it would get in initializing state.

After  every 1 minute ( + a max of cleanup thread interval which is 1 minute) , the instances get removed and service reconcile triggers creation of a new instance.

3. set "reinitializingTimeout"  to 1 minute when configuring health check for a services. 
    get the container state to be stuck in "reinitiailizing" state ( changed the health_state in db directly to simulate the scenario of being stuck in "reinitializing" when restarting the service).

In the next 1 minute ( + a max of cleanup thread interval which is 1 minute) , the instances should gets removed .
