### ISSUE TITLE
Cannot import k3s v1.21

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#32298]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a k3s v1.21.0-rc1+k3s1 cluster
2. Attempt to import it into rancher

**Result:**
It fails to successfully import:
![image](https://user-images.githubusercontent.com/55997940/115793684-66753c80-a381-11eb-804b-a4067fab90a7.png)

**Other details that may be helpful:**
The k3s apiserver logs with --v=9 show the following:
```
pr 22 15:33:14 centos01 k3s: E0422 15:33:14.764538    7904 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, Token has been invalidated]"
Apr 22 15:33:14 centos01 k3s: I0422 15:33:14.764604    7904 httplog.go:89] "HTTP" verb="GET" URI="/version" latency="4.719321ms" userAgent="rancher/v0.0.0 (linux/amd64) kubernetes/$Format cluster c-ptdl5" srcIP="10.42.0.10:46508" resp=401
--
Apr 22 15:33:18 centos01 k3s: E0422 15:33:18.952774    7904 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, Token has been invalidated]"
Apr 22 15:33:18 centos01 k3s: I0422 15:33:18.952863    7904 httplog.go:89] "HTTP" verb="GET" URI="/api/v1/namespaces/kube-system?timeout=45s" latency="4.536598ms" userAgent="rancher/v0.0.0 (linux/amd64) kubernetes/$Format cluster c-ptdl5" srcIP="10.42.0.10:46508" resp=401
```

- No errors in the `cattle-cluster-agent` pod logs. It actually appears to be running. 
- Potentially related to 1.21 changes with service account issuer discovery - it’s mandatory that you provide an OpenID provider endpoint now, and upstream kubeadm just points it at the provider built in to the apiserver which is what k3s 1.21 also now does. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7 and v2.5.8-rc8
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): v1.21
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:23:45Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0-rc1+k3s1", GitCommit:"2705431d9645d128441c578309574cd262285ae6", GitTreeState:"clean", BuildDate:"2021-04-21T23:32:39Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by brandond** [comment]
It appears that Rancher is storing the service account token from the initial pod, and then trying to reuse that on subsequent requests even though that pod has been deleted?

```
Apr 22 15:54:45 centos01 k3s: I0422 15:54:45.268803   11471 claims.go:173] Could not retrieve bound pod cattle-system/cattle-cluster-agent-7dbc5bfdf5-qljlr for service account cattle-system/cattle: pods "cattle-cluster-agent-7dbc5bfdf5-qljlr" not found
Apr 22 15:54:45 centos01 k3s: E0422 15:54:45.268868   11471 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, Token has been invalidated]"
Apr 22 15:54:45 centos01 k3s: I0422 15:54:45.268964   11471 httplog.go:89] "HTTP" verb="GET" URI="/version" latency="4.221998ms" userAgent="rancher/v0.0.0 (linux/amd64) kubernetes/$Format cluster c-ptdl5" srcIP="10.42.0.10:52436" resp=401
```

```
[root@centos01 ~]# kubectl get pods -A -o wide -w
NAMESPACE       NAME                                      READY   STATUS      RESTARTS   AGE   IP           NODE                 NOMINATED NODE   READINESS GATES
kube-system     metrics-server-86cbb8457f-l79cz           1/1     Running     0          12m   10.42.0.3    centos01.lan.khaus   <none>           <none>
kube-system     local-path-provisioner-5ff76fc89d-wgtnc   1/1     Running     0          12m   10.42.0.4    centos01.lan.khaus   <none>           <none>
kube-system     coredns-7448499f4d-6pspd                  1/1     Running     0          12m   10.42.0.6    centos01.lan.khaus   <none>           <none>
kube-system     helm-install-traefik-crd-jc2fp            0/1     Completed   0          12m   10.42.0.2    centos01.lan.khaus   <none>           <none>
kube-system     svclb-traefik-s4nhg                       2/2     Running     0          12m   10.42.0.8    centos01.lan.khaus   <none>           <none>
kube-system     helm-install-traefik-hzvq6                0/1     Completed   1          12m   10.42.0.5    centos01.lan.khaus   <none>           <none>
kube-system     traefik-97b44b794-vq4ng                   1/1     Running     0          12m   10.42.0.7    centos01.lan.khaus   <none>           <none>
kube-system     svclb-traefik-4wgjk                       2/2     Running     0          11m   10.42.1.2    centos02.lan.khaus   <none>           <none>
cattle-system   cattle-cluster-agent-7dbc5bfdf5-qljlr     0/1     Running     0          59s   10.42.0.9    centos01.lan.khaus   <none>           <none>
cattle-system   cattle-cluster-agent-55479cb4c8-hzh6r     0/1     Running     0          6s    10.42.0.10   centos01.lan.khaus   <none>           <none>
cattle-system   cattle-cluster-agent-55479cb4c8-hzh6r     1/1     Running     0          10s   10.42.0.10   centos01.lan.khaus   <none>           <none>
cattle-system   cattle-cluster-agent-7dbc5bfdf5-qljlr     0/1     Terminating   0          63s   10.42.0.9    centos01.lan.khaus   <none>           <none>
cattle-system   cattle-cluster-agent-7dbc5bfdf5-qljlr     0/1     Terminating   0          64s   10.42.0.9    centos01.lan.khaus   <none>           <none>
cattle-system   cattle-cluster-agent-7dbc5bfdf5-qljlr     0/1     Terminating   0          65s   10.42.0.9    centos01.lan.khaus   <none>           <none>
cattle-system   cattle-cluster-agent-7dbc5bfdf5-qljlr     0/1     Terminating   0          65s   10.42.0.9    centos01.lan.khaus   <none>           <none>
```

**Comment by brandond** [comment]
Also relevant: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume

**Comment by ibuildthecloud** [comment]
@brandond is there any chance the to the token reference by the service account itself?  If Rancher just grabbed the secret from k8s and used that I assume the token would stay valid?  It sounds like k8s is getting more serious about invalidating tokens so we will have to figure out a better long term approach.

**Comment by brandond** [comment]
Yeah I think that if Rancher grabbed the service account secret directly instead that would work. The issue (as you said) appears to be that it's just using the InCluster token and sending that back to the server, which is no longer an OK thing to do:
https://github.com/rancher/rancher/blob/7529f433297bf4f1c4a9cb2d0d52bb52f01e12d1/pkg/tunnelserver/tunnel.go#L303

**Comment by rancher-max** [comment]
This is fixed on master-head commit id `2d7fa0e`. Importing does not give any errors.

I am not able to validate yet on v2.5-head as the push in drone failed: https://drone-publish.rancher.io/rancher/rancher/5392. Leaving open until I can validate here or in the next 2.5.8 rc.

**Comment by brandond** [comment]
FWIW it appears that there's no way to request the legacy behavior of mounting the secret directly instead of the token, short of disabling the FeatureGate when starting control plane.

https://github.com/kubernetes/kubernetes/blob/release-1.21/plugin/pkg/admission/serviceaccount/admission.go#L524-L532

**Comment by brandond** [comment]
For future reference: https://github.com/zshihang/enhancements/blob/bbcf8f4dbd87077fd463d148830dc2a5108e603b/keps/sig-auth/0000-token-controller-deprecation/README.md#motivation

> One solution is to provision long-lived certificates for certificate-based auth with the kubernetes.io/kube-apiserver-client signer for CSRs

**Comment by rancher-max** [comment]
Validated import is successful on v2.5.8-rc12
