### ISSUE TITLE
Transition KEV2 charts to feature-charts

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32293]
~Pre-req for: https://github.com/rancher/rancher/issues/31592~

- [x] EKS chart - @thedadams 
- [x] GKE chart - @thedadams
- [x] AKS chart - @cmurphy 
- [ ] EKS removal from system-charts in 2.6 - @thedadams  
- [ ] GKE removal from system-charts in 2.6 - @thedadams 
- [ ] AKS removal from system-charts in 2.6 - @cmurphy

**Comment by cbron** [comment]
Primary thing to test here is upgrade path from 2.5 (system-charts) to 2.6 (feature-charts)

**Comment by sowmyav27** [comment]
Will be testing this issue as part of https://github.com/rancher/rancher/issues/31592
