### ISSUE TITLE
[rancher alerting drivers]  add links to the upstream examples

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#32296]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement 

Currently, when SMS is enabled, A configmap for rancher-sachet is created with no content. 

For a better user experience, we can add the link to the upstream and examples as comments in rancher-sachet's configmap. 

Sample result:

![image](https://user-images.githubusercontent.com/6218999/115789641-48f0a480-a37a-11eb-9166-46b3497fb582.png)

**Comment by slickwarren** [comment]
tested on v2.5.8-rc10:
* installed SMS via rancher-alerting-drivers chart
* in the sachet configmap, now there is a template (just as it appears in Jack's screenshot above) to help the user configure their sms alerts
