### ISSUE TITLE
New charts in v2.6

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#32294]
### System charts (v1):

Name | Version | Backend Dev(s)
--- | --- | ---
~gke-operator~ | ~1.1.100~ | ~@cmurphy (if not moved to rancher/charts)~ Moved to rancher/charts
~aks-operator~ | ~1.0.100~ | ~@mjura (if not moved to rancher/charts)~ Moved to rancher/charts
~eks-operator~ | ~1.1.100~ | ~@thedadams~ Moved to rancher/charts
~rancher-operator~ | ~TBD~ | ~@thedadams @StrongMonkey (if not transitioned to Rancher)~ Moved into Rancher
monitoring   | v0.3.0 | @aiyengar2 @jiaqiluo 
rancher-cis-benchmark | 0.2.0 | @prachidamle 
rancher-external-dns | v0.2.0 | @prachidamle 
rancher-istio | 1.5.920 | @brendarearden
rancher-logging | 0.3.0 | @paynejacob 
rancher-k3s-upgrader (system-upgrade-controller) | 0.3.0 | @cmurphy 

### Feature charts (v2):

Name | Version | Backend Dev(s)
--- | --- | ---
rancher-vsphere-csi      | 100.0.0 | @PennyScissors 
rancher-vsphere-cpi      | 100.0.0 | @PennyScissors 
Logging v2               | 100.0.0+up3.12.0 | @nickgerace @paynejacob 
Monitoring V2            | 100.0.0+up16.6.0 | @aiyengar2 @jiaqiluo 
gke-operator             | 100.0.0+up1.1.1 | @thedadams
aks-operator             | 100.0.0+up1.0.1 | @thedadams
eks-operator             | 100.0.0+up1.1.1 | @thedadams
rancher-backup           |  2.0.0 | @jiaqiluo 
rancher-alerting-drivers | 100.0.0 | @jiaqiluo 
rancher-prom2teams       | 100.0.0+up0.2.0| @jiaqiluo 
rancher-sachet           | 100.0.0       | @jiaqiluo 
rancher-cis-benchmark    | 2.0.0 | @prachidamle 
fleet                    | 100.0.0+up0.3.6  | @nickgerace 
longhorn                 | 100.0.0+up1.1.2 |  
rancher-gatekeeper       | 100.0.0+up3.5.1 | @cmurphy 
rancher-istio            | 100.0.0+up1.10.4 | @brendarearden 
rancher-kiali-server     | 100.0.0+up1.35.0 | @brendarearden 
rancher-tracing          | 100.0.0 | @brendarearden 
rancher-pushprox         | 100.0.0 | @aiyengar2
rancher-prometheus-adapter | 100.0.0+up2.14.0 | @aiyengar2
rancher-grafana          | 100.0.0+up6.11.0 | @aiyengar2
rancher-windows-exporter | 100.0.0 | @aiyengar2
rancher-node-exporter    | 100.0.0+up1.18.1 | @aiyengar2
rancher-kube-state-metrics | 100.0.0+up3.2.0 | @aiyengar2
rancher-wins-upgrader    | 100.0.0+up0.0.1 | @aiyengar2
system-upgrade-controller | 100.0.0+up0.3.0 | @aiyengar2
rancher-webhook | 1.0.0+up0.2.0 (this will be beta until right before release) | @dramich @ryansann @thedadams 
external-ip-webhook | 100.0.0+up1.0.0 | @cmurphy  
rancher-sriov  | 100.0.0+up0.1.0 |  @manuelbuil

**Comment by cbron** [comment]
release-note: need to clarify why everything moved to 100

**Comment by deniseschannon** [comment]
@kinarashah Can you review that these are the versions that you see in the PRs that we make to bring the dev branches into the release branches?

**Comment by cbron** [comment]
Some of these are wrong / need updating. Going through now.

**Comment by aiyengar2** [comment]
As discussed offline with @cbron, I have opened up the PR to change v0.2.3 -> v0.3.0 for Monitoring V1. Updated the above description accordingly as well.

**Comment by prachidamle** [comment]
PR https://github.com/rancher/system-charts/pull/516 opened to update rancher-external-dns v0.1.3 to rancher-external-dns v0.2.0

**Comment by izaac** [comment]
Rancher version: `v2.6.0-rc10` - Fresh Install - RHEL 8.4 RKE1 Nodes

`v2.5.9` -> `v2.6.0-rc10` - Upgrade - RHEL 8.3 RKE1 Nodes

**Fresh install** worked, the fluentd pods no longer show the Ruby plugin error in the logs. The logs are flowing to Elasticsearch.
**Fresh install**  the fluentd image version was: `v0.1.30`

**Upgrade** path worked, logs were flowing before and after upgrade. 
During **Upgrade** the Logging v1 App was upgraded automatically without intervention as expected from `0.2.4` to `0.3.0`
During **Upgrade** the fluentd image was upgraded from `v0.1.24` to `v0.1.30`

`rancher-images.txt` is also including this new fluentd image version `v0.1.30`
