### ISSUE TITLE
forward port: catalog refreshes constantly

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32319]
#23256 forwardport

**Comment by sowmyav27** [comment]
Master PR: https://github.com/rancher/rancher/pull/32217

**Comment by slickwarren** [comment]
tested on master-head (7e5ad7f):
* add the catalog https://charts.bitnami.com/bitnami through the dashboard UI
* After the catalog is done syncing edit the catalog yaml and add the line gitBranch: master directly under the url field.
Watch the rancher server logs `2021/04/22 09:43:45 [INFO] Downloading repo index from https://charts.bitnami.com/bitnami/index.yaml` -- does not repeat in logs, still see initial download log -- pass
