### ISSUE TITLE
New catalogs do not log `downloading` new charts

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32318]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy rancher v2.5.8-rc9 or later with `trace` logging enabled 
  * view logs as you do the next step
* Add a catalog (i.e. https://charts.bitnami.com/bitnami ) through the dashboard UI

**Result:**
no log will show up regarding the download of new charts

**Other details that may be helpful:**
in issue https://github.com/rancher/rancher/issues/23256#issuecomment-824971111 we were spamming the download, but it appears that the code change that fixed that is unrelated to the initial download log

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8-rc9
- Installation option (single install/HA): single

- Kubernetes version (use `kubectl version`): 1.20

- Docker version (use `docker version`): 20.10.3

**Comment by dramich** [comment]
We log `2021/04/26 15:20:31 [INFO] Downloading repo index from https://charts.bitnami.com/bitnami/index.yaml` when adding a new chart.

**Comment by slickwarren** [comment]
ok, yes I see that now on v2.5.8-rc9. thank you
