### ISSUE TITLE
XMLParserError on Add Host EC2 ap-northeast-2

### ISSUE THREAD

**Issue by keizie** [rancher/rancher#3231]
POST /v1/proxy/ec2.ap-northeast-2.amazonaws.com/ returns 403 and HTML document
that reads as follow;

> <!DOCTYPE html>
> &lt;!-- If you are reading this, there is a good chance you would prefer sending an
> "Accept: application/json" header and receiving actual JSON responses. --&gt;
> (snip)

Other URLs for different AZs return 200 and proper XML document.

**Comment by vincent99** [comment]
See https://github.com/rancher/rancher/issues/3185
