### ISSUE TITLE
Fleet agents bundle on ErrApplied state after upgrade to `v2.5.8-rc9`

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32317]
**What kind of request is this:**

**Steps to reproduce:**

- RKE HA install `v2.5.7`
- Upgrade to `v2.5.8-rc9`

**Result:**

Fleet Agents on local and downstream clusters on error state

`message: 'query: failed to query with labels: secrets is forbidden: User "system:serviceaccount:fleet-system:fleet-agent"
        cannot list resource "secrets" in API group "" in the namespace "fleet-system"'`
<img width="866" alt="Screen Shot 2021-04-23 at 12 03 23 PM" src="https://user-images.githubusercontent.com/27659/115918590-8ca3e680-a42c-11eb-89b9-7523fa374a62.png">

**Other details that may be helpful:**

OpenLDAP auth

**Environment information**
- Rancher version: `v2.5.7` upgrade to `v2.5.8-rc9`
- Installation option: HA

**Comment by izaac** [comment]
Rancher version `v2.5.8-rc11` upgrade from `v2.5.7`
Fleet versions `v0.3.5-rc7` upgrade from `v0.3.4`

After upgrading the fleet controller on local I see the fleet agents properly upgrading to `v0.3.5-rc7` too.
P1 test case continued working after upgrade.

**Comment by StrongMonkey** [comment]
@izaac Hey Can we retest this with rc9 when you have a chance? I recently found that the previous fix to deal with upgrade is not good, as it causes chatty connection to downstream cluster.

**Comment by izaac** [comment]
@izaac sure thing I will @StrongMonkey

**Comment by izaac** [comment]
@StrongMonkey at this point do I need an RC? I don't see `0.3.5` listed as an option to upgrade on `v2.5-head`

![Screen Shot 2021-04-29 at 5 36 06 PM](https://user-images.githubusercontent.com/27659/116635013-86bd7200-a912-11eb-9d8f-04be126418af.png)

**Comment by izaac** [comment]
Rancher version: `v2.5-head (04/29/2021)` _7723077_ Upgrade from `v2.5.7`
Fleet version: `v0.3.5-rc9` upgrade from `0.3.4`

After the fleet controller gets upgraded on local I see the fleet agents properly upgrading to v0.3.5-rc9 too on downstream clusters.
P1 test case continued working after upgrade.
