### ISSUE TITLE
[monitoring v2] windows exporter fails to come up: json error on check-wins-version pod

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32321]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* deploy rancher v2.5.8-rc9
* deploy a downstream windows cluster with multiple windows worker nodes
* deploy monitoring v14.5.100

**Result:**
One of the windows exporter pods fails to deploy 
<img width="1687" alt="Screen Shot 2021-04-23 at 4 22 58 PM" src="https://user-images.githubusercontent.com/16691014/115938625-38126280-a450-11eb-86ce-244c920823f6.png">
<img width="862" alt="Screen Shot 2021-04-23 at 4 22 12 PM" src="https://user-images.githubusercontent.com/16691014/115938630-3b0d5300-a450-11eb-9cf5-5443b0083edc.png">

```
CrashLoopBackOff: back-off 5m0s restarting failed container=check-wins-version pod=rancher-monitoring-windows-exporter-nw4jw_cattle-monitoring-system(458ac74e-068d-4dce-9cf5-cca9539d2949)
```

```
ConvertFrom-Json: Conversion from JSON failed with error: Unexpected character encountered while parsing value: . Path '', line 0, position 0.
```

**Other details that may be helpful:**
rancher-wins version v0.1.0  
Windows_Server-1909-English-Core-ContainersLatest-2021.01.13
content of `etc/rancher/wins/config` 

```
{"whiteList":{"processPaths":["c:\\etc\\wmi-exporter\\wmi-exporter.exe","c:\\etc\\kubernetes\\bin\\kube-proxy.exe","c:\\etc\\kubernetes\\bin\\kubelet.exe","c:\\etc\\nginx\\nginx.exe","c:\\opt\\bin\\flanneld.exe","c:\\etc\\rancher\\wins\\wins-up
grade.exe","c:\\etc\\windows-exporter\\windows-exporter.exe"],"proxyPorts":[9796]}}    
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8-rc9
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Windows
- Machine type (cloud/VM/metal) and specifications (CPU/memory): t3.xlarge
- Kubernetes version (use `kubectl version`): v1.20.6

- Docker version (use `docker version`):19.3.14

**Comment by thehejik** [comment]
@slickwarren Did you choose ClusterType=Windows and set `global.cattle.windows.enabled=true` instead of `windowsExporter.enabled=true` which should be removed from end of `values.yaml` file after selecting Windows? (waiting for https://github.com/rancher/dashboard/pull/2743)

It works for me on 2.5.8-rc9 on Windows 1909.

![windows-exporter-258rc9](https://user-images.githubusercontent.com/12828077/116060374-1c8e9e00-a682-11eb-8313-26a9766e10cf.png)

**Comment by sowmyav27** [comment]
@slickwarren Can you please validate this on 2.5.8-rc10 and confirm ?

**Comment by sowmyav27** [comment]
On 2.5.8-rc12, I dont see this issue. `ClusterType=Windows ` was set while deploying monitorng. Basic checks f monitooring v2 on windows cluster worked.

**Comment by augustobeilfuss2** [comment]
Im facing this error to, someone solve this?

**Comment by herrbpl** [comment]
This problem is still there with rancher-monitoring:102.0.1+up40.1.2 and with:
```yaml
global:
  cattle:
    windows:
      enabled: true
```
