### ISSUE TITLE
[Logging v2] - dockerRootDirectory is applied to Linux workloads make possible to setup this for Windows nodes

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32328]
**What kind of request is this:**
Improvement

**Steps to reproduce:**

- On Windows clusters we have this view that allows the user to set a couple of settings from UI.
  - `global.dockerRootDirectory`
  - `additionalLoggingSources.rke.enabled`

<img width="1073" alt="Screen Shot 2021-04-23 at 5 06 32 PM" src="https://user-images.githubusercontent.com/27659/115940451-7ca0fc80-a456-11eb-90be-ee3c1105c6c4.png">

**Result:**

If left empty the Docker Root input default to `/var/lib/docker` But this can be changed.

However this is only applied to Linux workloads. The Windows daemonsets use the default `C:\ProgramData\docker` and is not changed.

**Other details that may be helpful:**

Changing this value to a Windows path results in a broken install:

```
Error: Logging.logging.banzaicloud.io "rancher-logging" is invalid: [spec.fluentbit.extraVolumeMounts.source: Invalid value: "C:\\ProgramData\\docker/containers/": spec.fluentbit.extraVolumeMounts.source in body should match '^/.+$', spec.fluentbit.extraVolumeMounts.destination: Invalid value: "C:\\ProgramData\\docker/containers/": spec.fluentbit.extraVolumeMounts.destination in body should match '^/.+$']
```

**Environment information**
- Rancher version: `v2.5.8-rc9`
- Installation option: any

**Comment by nickgerace** [comment]
This is actually intentional and will need to be documented.
Here is the Logging v2 Windows Epic for docs: https://github.com/rancher/docs/issues/3222

**Comment by izaac** [comment]
Closing in favor of including docs for Windows.
