### ISSUE TITLE
couldn't access the cluster after changing rancher hostname

### ISSUE THREAD

**Issue by Nilegfx** [rancher/rancher#32326]
**What kind of request is this (question/bug/enhancement/feature request):**
question

I am not sure if I missed it in the docs or it is not well documented, How can I change a currently-running rancher hostname? 

**Steps to reproduce (least amount of steps as possible):**
run helm upgrade with a new hostname
```
helm upgrade --install \
  --namespace cattle-system \
  --set hostname=new-host-name.com \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=email@email.com \
  rancher \
  rancher-stable/rancher
```

**Result:**
the cluster is no longer accessible neither from rancher UI or from the local kubeconig. on rancher interface I got
```
Cluster health check failed: Failed to communicate with API server during namespace check: Get "https://10.0.0.3:6443/api/v1/namespaces/kube-system?timeout=45s": context deadline exceeded;

```
when inspecting the logs from the container `rancher/rancher-agent:v2.5.7` I got 

```
INFO: Arguments: --server https://rancher.m3ntorship.xyz --token REDACTED -r -n m-67hl5
INFO: Environment: CATTLE_ADDRESS=xxx.xxx.xxx.xxx CATTLE_AGENT_CONNECT=true CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=m-67hl5 CATTLE_SERVER=https://old-host-name.com CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 127.0.0.53 options edns0 trust-ad
WARN: Loopback address found in /etc/resolv.conf, please refer to the documentation how to configure your cluster to resolve DNS properly
ERROR: https://old-host-name.com/ping is not accessible (The requested URL returned error: 526)
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
```
Rancher | v2.5.7
-- | --
User Interface | v2.5.6
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher52

```
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider (hetzner with hetzner node template)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud (2vcpu/4gb)
- Kubernetes version (use `kubectl version`): 

```
Client Version: v1.19.0
Server Version: v1.20.5-rancher1-1 (couldn't get the version from the command as the cluster is not accessible)
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by bnneupart** [comment]
I have the same issue, none of the 8 clusters are available after a hostname change.

Why did I changed the hostname, - well because the Lets Encrypt certificate did not update and I was completely locked out...
