### ISSUE TITLE
[Forwardport ] Unable to provision GKE cluster from Rancher UI on upgraded server

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32338]
Forwardport of https://github.com/rancher/rancher/issues/32124

**Comment by cmurphy** [comment]
@sowmyav27 what is the specific upgrade case that isn't working for this one - is it upgrading from 2.5.7 to master, or from 2.5-head to master?

**Comment by sowmyav27** [comment]
**Upgraded from 2.5.7 to master-head commit id: `70ba0d59`**

Able to deploy a hosted GKE cluster.
