### ISSUE TITLE
Kiali v1.32.0 Display dropdown erroring

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#32330]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy Istio v1.9.3 with tracing and jeager enabled
2. Deployed the bookinfo app, and hit the productpage a few times to generate traffic (other test application could be used, as long as there is a service to view traces for)
3. Navigate to the service in the kiali dashboard and click on the tracing tab
4. Click on the Display drop down and select a display setting using the radio selection buttons

**Result:**
Any previous tracing page turns into an error page, and the Display dropdown becomes disabled. 
![Screen Shot 2021-04-23 at 4 50 36 PM](https://user-images.githubusercontent.com/19455540/115943284-d52ac680-a463-11eb-8378-07b1ba38e2d4.png)

**Other details that may be helpful:**

**Environment information**
Rancher Version: rancher/rancher:v2.5.8-rc9 
Istio Version: v1.9.3 (this has Kiali v1.32.0 bundled with it) 
Installation Option: Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Linode
- Kubernetes version (use `kubectl version`): v1.20.6

**Upstream Issue**
https://github.com/kiali/kiali/issues/3939

**Comment by brendarearden** [comment]
This issue was fixed upstream with this PR https://github.com/kiali/kiali/pull/3950 and is slotted for the v1.34.0 milestone at this time

**Comment by brendarearden** [comment]
https://github.com/rancher/charts/blob/dev-v2.6/assets/rancher-istio/rancher-istio-100.0.0.tgz << The 100.0.0 version of the rancher-istio chart has Istio v1.10.1 and auto installs Kiali 1.35.0.

**Comment by brendarearden** [comment]
This is available for testing in the dev-v2.6 branch. rancher-istio v100.0.0 (this installs istio 1.10.2) and rancher-kiali-server v100.0.0 (this install kiali 1.35.0)

**Comment by anupama2501** [comment]
Verified on master-head 9e0d1b2 istio - `v1.10.2` and kiali `v1.35.0`

- Installed istio in a downstream cluster
- From kiali --> services --> product page, changed the display value to a percentile - no errors are seen
