### ISSUE TITLE
GKEv2UI- do not have option to specify default node locations for Regional clusters

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32345]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
GKE allows users to specify default node locations for Regional clusters.
<img width="702" alt="Screen Shot 2021-04-26 at 11 05 27 AM" src="https://user-images.githubusercontent.com/3749546/116129753-51e5bc80-a67f-11eb-8f14-41c75c33e371.png">

It will be nice to have the same feature in GKEv2UI as well
Current UI:
<img width="1337" alt="Screen Shot 2021-04-26 at 11 06 15 AM" src="https://user-images.githubusercontent.com/3749546/116129861-6d50c780-a67f-11eb-8028-47ddaf501d70.png">

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-1963c2e01996894c36480583903f5d5642702269-head
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
This didn't seem to be part of the original requirements so I think this should be targeted at >2.5.8. If its a must have I believe this impact is fairly low from a UI perspective but I'd prefer to push it out as we're getting very close to release. 

cc: @sowmyav27 @gaktive

**Comment by prabalsharma** [comment]
It will be nice if we can push this to 2.6. This definitely will add a new feature in UI, which will open ground for regression and substantial number for permutation and combinations of test cases. I think this is too close to a release for me to be comfortable. 
@gaktive your call :)

**Comment by gaktive** [comment]
2.6 is fine by me. I can reread if there was demand for such a feature for 2.5.8 but if there's a way to do it in the backend/API, that's fine.

**Comment by prabalsharma** [comment]
Tested on master-629146a3fbbc8d5677aecece78e627580dd7c95d-head

The feature itself works. However, it will be nice if the zone selection option gets disabled for Regional Cluster on `Edits / Update` (to match GCP UI).

Right now, for a Regional cluster, UI allows me to select additional zones when I "Edit" the cluster from Rancher (as expected, it does not actually do anything).

GCP behaviour:

`Editing default node zones is available only in zonal clusters.`
