### ISSUE TITLE
GKEv2UI: support for 1.20 k8s version 

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32347]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
Right now UI supports only `validMaterVersions`. However, a user can create a GKE 1.20 cluster on gcloud and `register` it on Rancher.
Not sure if we want to support this version from `Rapid Channel`
This is how it looks right now if a user `registers` a 1.20 cluster:

<img width="1221" alt="Screen Shot 2021-04-26 at 11 36 40 AM" src="https://user-images.githubusercontent.com/3749546/116133554-b1de6200-a683-11eb-8bb0-7d443b2fe4e2.png">
<img width="826" alt="Screen Shot 2021-04-26 at 11 37 11 AM" src="https://user-images.githubusercontent.com/3749546/116133606-c0c51480-a683-11eb-8318-4d029f90206d.png">

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-1963c2e01996894c36480583903f5d5642702269-head
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
With the changes [here](https://github.com/rancher/ui/pull/4569) the if the current version does not exist in the list of versions then I will push that version into the list so you dont see an empty dropdown and will add "support" for this version if it was launched on 1.20 in the console. The user will not be able to upgrade the cluster to anything greater than what is in the list though.  

Beyond that I think this falls into new feature or at the very least enhancement territory and shouldn't be pushed into 2.5.8. If anything we should open a new ticket for post 2.5.8 where we can update the backend and ux to support stable vs release channels. 

cc: @sowmyav27 @gaktive

**Comment by prabalsharma** [comment]
I think this fix should be okay, as a user won't see empty version, on registering 1.20 GKE. 
This is anyways a feature request and can be either moved to some future milestone or can be rejected.
