### ISSUE TITLE
Load Balancer - binding to public IP?

### ISSUE THREAD

**Issue by miko** [rancher/rancher#3234]
Hello,
I have my host with public IPs 1.2.3.4 and 1.2.3.5, and LD scheduled to run on this host.
Is it possible to run Load Balancer so it could bind only to one of those IP addresses? I tried to put 1.2.3.4:80 in Listening Ports, but then get I get exception:

```
Unknown exception running process [service.activate:853104] on [24] io.github.ibuildthecloud.gdapi.exception.ClientVisibleException: PortWrongFormat
        at io.cattle.platform.core.util.PortSpec.<init>(PortSpec.java:41) ~[cattle-iaas-model-0.5.0-SNAPSHOT.jar:na]
```

I cannot put simply port 80, because 1.2.3.5:80 is used by other process. Any way to get around the issue?

**Comment by pedrommone** [comment]
Currently, Rancher bind `0.0.0.0:*`, you can try with iptables rules.

**Comment by pedrommone** [comment]
I see that now we can have it on Load Balancer but when try to bring an LB with specific IP binding I get this error on container

```
INFO: Downloading agent http://rancher.masked.com:8080/v1/configcontent/configscripts
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system reboot
```

**Comment by will-chan** [comment]
Closed due to inactivity.
