### ISSUE TITLE
Cannot use kubectl shell in UI on k3s 1.21 cluster

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#32348]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Import a 1.21 k3s cluster
2. Attempt to launch the kubectl shell

**Result:**
It fails to launch with `Closed Code: 1006` and a 500 Network Error

**Other details that may be helpful:**
This fails whether the 1.21 cluster was upgraded from 1.20 or is imported directly as a clean install.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit `2d7fa0e`
- Installation option (single install/HA): single

**Comment by cbron** [comment]
1.21 isn't supported until 2.6: https://github.com/rancher/rancher/issues/31567

**Comment by sangeethah** [comment]
We have addressed this issue for imported clusters - https://github.com/rancher/rancher/issues/32298

**Comment by rancher-max** [comment]
Bumping out the milestone for this. kubectl shell, logs, and exec shell all work on v2.5.8-rc12, so this is probably more related to other changes on master-head.

**Comment by thehejik** [comment]
I'm seeing something similar in Ember UI `rancher/rancher:master-head f90b36e` when clicked on `Launch kubectl` button on RKE DO downstream cluster with k8s `v1.21.1-rancher1-1` (3x cp+etcd, 3x worker). The console window reports `Close Code: 1006` and web developers console reporting error message `WebSocket is already in CLOSING or CLOSED state.`

**Comment by cmurphy** [comment]
@StrongMonkey's fix for https://github.com/rancher/rancher/issues/32657 fixes this issue, so closing this as a duplicate.
