### ISSUE TITLE
Containers re-scheduled on master restart

### ISSUE THREAD

**Issue by msh100** [rancher/rancher#3235]
I guess this is more of a question than an issue and am unsure where I should be posting it. So sorry in advance.

The Rancher master service was unexpectedly terminated (Host machine powered down). After some hours it came back, during this duration all the hosts on Rancher were online and the containers were running as normal.

When the host came back online with Rancher, it started to kill and reschedule the already running containers. Is this normal? Is there any specific configuration for the services which needs to be set in order to prevent this from happening - I would much prefer if the containers continues to run as they were before (not reschedule them).

Thanks!

**Comment by deniseschannon** [comment]
I just tried to reproduce, but was unable. I killed my host and then started my rancher server container again. Mine didn't re-schedule any running containers.

Is one of your hosts the one with rancher server running on it? 
Were all the containers re-scheduled or just some? It sounds like some of the containers were deemed unhealthy so they were re-scheduled.

**Comment by msh100** [comment]
Thanks for the reply.

The rancher server doesn't run any containers - I am not too sure why the services would be deemed unhealthy. Maybe there are logs for why a container re-schedules? Where could I find these?

I also noticed that some containers re-scheduled when I added a new service, unsure what the trigger is.

**Comment by deniseschannon** [comment]
Are you able to look to see which service/containers are being re-scheduled? Do you have some health checks on services?

**Comment by msh100** [comment]
@deniseschannon where are the logs for this kind of thing? I can try reproduce it with a bit more information then :smile:

**Comment by deniseschannon** [comment]
You might be able to find them in rancher/server logs. I was just wondering whether or not you could tell from the UI.

**Comment by deniseschannon** [comment]
@msh100 Please re-open if you are able to provide logs for the rancher/server container. Another thing I thought of when I re-read this was whether or not your rancher/server and rancher/agent were on the same host. If so, then the containers would have appeared to be re-scheduled because your host would have had those containers stopped and Rancher would have started them up again.
