### ISSUE TITLE
[rancher alerting drivers] support hardened cluster and CIS scan

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#32358]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

The current rancher-alerting-drives app `1.0.100-rc4` will fail to be installed into a hardened cluster because 

1. missing the permission to use secret as volume.  Related error message:
```
[FailedCreate] pods "rancher-alerting-drivers-sachet-644cbb856-" is forbidden: unable to validate against any pod security policy: [spec.volumes[1]: Invalid value: "secret": secret volumes are not allowed to be used]
```
2. the following 2 checks will fail on CIS scan with Profile: rke-profile-hardened-1.6. This does not prevent the app from installation, but it is better to fix them. 
```
5.1.5 | Ensure that default service accounts are not actively used. (Automated)
5.3.2 | Ensure that all Namespaces have Network Policies defined (Automated)
```

**Comment by cbron** [comment]
@jiaqiluo can you make a backport issue and put into 2.5

**Comment by jiaqiluo** [comment]
the fix is available in rancher-alerting-driver 100.0.0

need to validate:
- the app can be installed into a hardened cluster with both sub-charts enabled 
- can pass the CIS scan

**Comment by slickwarren** [comment]
reopening for the following issue: unable to install chart on master-head (5715b8a)

here are the valid logs: 
```
Watching for changes to Job rancher-alerting-drivers-patch-sa with timeout of 10m0s
Add/Modify event for rancher-alerting-drivers-patch-sa: MODIFIED
rancher-alerting-drivers-patch-sa: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Add/Modify event for rancher-alerting-drivers-patch-sa: MODIFIED
rancher-alerting-drivers-patch-sa: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
Add/Modify event for rancher-alerting-drivers-patch-sa: MODIFIED
Error: failed post-install: job failed: BackoffLimitExceeded
```

**Comment by jiaqiluo** [comment]
can be tested in rancher-alerting-driver 100.0.0

need to validate:

- the app can be installed into a hardened cluster with both sub-charts enabled
- can pass the CIS scan

**Comment by slickwarren** [comment]
Tested the following on master-head (44bb5b4):
*  rancher-alerting-drivers:100.0.0 can be installed into a hardened cluster with both sub-charts enabled
* CIS scan passes (cis 1.6 hardened)
