### ISSUE TITLE
Error seen - "Error 400: Current master version can only be set to one of "REGULAR" channel supported versions [1.18.16-gke.502, 1.18.16-gke.2100, 1.19.8-gke.1600]" on k8s upgrade of a GKEv2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32360]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy an imported GKE cluster with k8s version - `1.18.16-gke.502` (this k8s version is from the Regular Channel chosen by default in GCE Console)
- After the cluster comes up Active, Edit cluster --> change the k8s version of the cluster to `1.18.16-gke.1201` seen in the dropdown
- Error seen: `Googleapi: Error 400: Current master version can only be set to one of "REGULAR" channel supported versions [1.18.16-gke.502, 1.18.16-gke.2100, 1.19.8-gke.1600]., badRequest`

**Expected Result:**
UI should not show k8s version which are noot applicable

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `124e7afc`
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted GKE v2

**Comment by westlywright** [comment]
@sowmyav27 I have having trouble repro'ing this. I was able to fully upgrade the versions you've outlined here. I also tried the scenario where I check the option to upgrade the node pool at the same time. I upgraded my rancher server to latest 2.5 head and attempted to repro again with no luck.
Also I investigated the gkeVersions call and it looks like the `validMasterVersions` param in that response only contains versions from the stable or regular channel, not the rapid so I dont think it is that. 
I was able to go from regular channel versions to stable, and back from a stable release to a regular release without issue. 
Additionally in one of my tests, before I upgrade the cluster in the rancher ui I opened the same cluster in the google console, selected the `Upgrade Available` button to upgrade the cluster and saw that when the cluster is on `1.18.16-gke.502` that `1.18.16-gke.1201` is available to select. I'm not quite sure how you got into this scenario. Do you have any further info that may help?

**Comment by sowmyav27** [comment]
Happens when we Deploy an imported GKE cluster with k8s version - 1.18.16-gke.502 (this k8s version is from the Regular Channel chosen by default in GCE Console).

**Comment by cmurphy** [comment]
I've reproduced this, but I would argue that the error message is clear. It provides the supported versions and they are available to pick from when you go back to edit the cluster, and then the update proceeds normally. We could address it more thoroughly by adding a release channel attribute for clusters and then the UI could filter `/meta/gkeVersions` by channels, but I think that could wait until 2.6.

**Comment by westlywright** [comment]
Ive been investigating this to see if I can find a workaround. Currently there is no definitive way to determine if its rapid, regular, or stable release channel. Nothing on the cluster tells us this because it's not implemented. There are too many assumptions that have to be made by the UI in this case to make this solvable without implementing the release channel logic on the backend to indicate what channel we are in. I was thinking the UI could add some logic that checks the imported k8s version exists in one of the `validVersions` params for a particular channel but that wont work because versions from both Regular and Stable can and do exist in static `validVersions` list. Additionally `1.18.16-gke.2100` also exists in both Regular and Stable channels as well as the static `validVersions` list. Basically the only workaround I see until we implement release channels is to edit the cluster and select a version from the error message and save. I did this and my cluster was upgrade correctly.

**Comment by gaktive** [comment]
Looks like we can workaround this in the UI

**Comment by westlywright** [comment]
On edit of an imported GKE cluster we will look up the cluster object from GKE to get the release channel. The main change here is that the versions dropdown will be very limited and will only contain valid versions from that channel, which is 3. Non-imported clusters remain unaffected and will see the full static version list. Additionally I have added a bit of help text below the versions drop down that indicates Stable/Regular/Rapid Channel or Static version for rancher clusters. This does not allow you to choose a channel, simply an indicator of what channel the cluster is on.

**Comment by prabalsharma** [comment]
Test case: Change channel from GCP
1. Provision a GKE cluster from Rancher. This will be a stable channel cluster with k8s version 1.17.17-gke.3700
2. Go to GCP change the Channel to Release
3. Now go to Rancher and Edit the version to 1.18.17-gke.700
<img width="1348" alt="Screen Shot 2021-04-29 at 3 17 14 PM" src="https://user-images.githubusercontent.com/3749546/116625132-fecd6d00-a8fd-11eb-9a93-39bd07408ee0.png">

**Comment by sowmyav27** [comment]
**Verified these usecases on 2.5-head commit id: `42f722b7`**

- Deploy an imported GKE cluster with default k8s version (regular channel)
- Import this cluster in Rancher.
- After the cluster comes up Active, Edit cluster --> Below the Kubernetes version, text seen `Regular channel`
- User is allowed to upgrade k8s version without any issue. 
- Regular channel's k8s versions are only available in the dropdown

Also verified scenarios where the cluster was created from Rapid/Stable and Static channels. No issues seen

In this following scenario, the order of the k8s versions displayed is incorrect. Would be good to have them in an order

- Deploy an imported GKE cluster with default k8s version (Stable channel)
- Import this cluster in Rancher.
- After the cluster comes up Active in Rancher, Edit cluster in GCE console.
- Change the channel to point to Regular channel 
- Edit cluster, the k8s versions are not in a dropdown
<img width="632" alt="Screen Shot 2021-04-29 at 2 24 46 PM" src="https://user-images.githubusercontent.com/26032343/116627064-46092d00-a901-11eb-8429-75e9560cc870.png">

**Comment by sowmyav27** [comment]
Reopening it for this issue - https://github.com/rancher/rancher/issues/32360#issuecomment-829632166

**Comment by prabalsharma** [comment]
https://github.com/rancher/rancher/issues/32360#issuecomment-829632166

Passed

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `4e4bd25d`**

- Deploy an imported GKE cluster with default k8s version (Stable channel)
- Import this cluster in Rancher.
- After the cluster comes up Active in Rancher, Edit cluster in GCE console.
- Change the channel to point to Regular channel
- Edit cluster, the k8s versions are in an order

<img width="708" alt="Screen Shot 2021-04-30 at 7 00 13 PM" src="https://user-images.githubusercontent.com/26032343/116767652-5941f880-a9e6-11eb-9894-1a7e1476b2e9.png">
