### ISSUE TITLE
[service][LB] New instances not recognized within running container

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#3236]
Hey there,
I have the following construction.
- SSH Service registering on dynamic hosts.
- LB pointing to SSH Service
- Service A (1x Container) linked with LB. (nodejs script connecting via SSH > LB > dynamic hosts)

Now these hosts are as already mentioned dynamic meaning sometimes up to 10 and in between also zero. Within `rancher/server` all seems ok. SSH Service/container gets created as soon a new host comes up and so on.
But I am not sure if new hosts get reflected within Service A.
One thing is for sure. If dynamic hosts drops to zero and then (e.g.) one again Service A is not able to connect via LB (guessing LB does not know the new host in scope of the running container of Service A).
As soon I restart the container of Service A connecting to the new host via LB is no problem.
Still I have to confirm if this is true for every new host or if it is a side effect of zero instances.

**Comment by deniseschannon** [comment]
I'm not sure if I completely can follow your setup. Could you share your docker-compose.yml? That might be easier for me to understand.

**Comment by deniseschannon** [comment]
@fentas If you're able to share your docker-compose.yml, please re-open and share. As I mentioned earlier, I was unable to understand what you were trying to do. :)
