### ISSUE TITLE
RKE2 Provisioning: AWS (v2 Cloud Credential and Node Pool)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32367]
AWS as a v2 Cloud Credential
```
apiVersion: v1
kind: Secret
metadata:
  name: #string
  annotations:
    provisioning.cattle.io/driver: aws
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
type: provisioning.cattle.io/cloud-credential
#data:
#  key: string
#immutable: boolean
```

AWS as a Node Driver

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: <NAME OF CLOUD CREDENTIAL>
  kubernetesVersion: v1.20.5+rke2r1
  rkeConfig:
      nodePools:
#      - cloudCredentialSecretName: string
#        controlPlaneRole: boolean
#        displayName: string
#        etcdRole: boolean
#        hostnamePrefix: string
#        labels:
#          key: string
#        name: string
#        nodeConfig:
#          apiVersion: string
#          fieldPath: string
#          kind: string
#          name: string
#          namespace: string
#          resourceVersion: string
#          uid: string
#        paused: boolean
#        quantity: int
#        rollingUpdate:
#          maxSurge: string
#          maxUnavailable: string
#        taints:
#          - effect: string
#            key: string
#            timeAdded: string
#            value: string
#        workerRole: boolean
```

**Comment by slickwarren** [comment]
on master-head (5d2b7ac) I am unable to provision a single-node cluster using EC2 (RKE2).  seems like potentially an issue with CAPI, as other issues at this stage have generally passed this stage of provisioning
<img width="569" alt="Screen Shot 2021-05-17 at 2 58 27 PM" src="https://user-images.githubusercontent.com/16691014/118561784-69651200-b720-11eb-9975-6b96f47953ae.png">

I do not see any nodes created in ec2. (I had the default, us west 2 selected, but also checked other regions to be sure it wasn't created elsewhere)

**Comment by sowmyav27** [comment]
Related issue - https://github.com/rancher/rancher/issues/32664

**Comment by kinarashah** [comment]
Available to test once https://drone-publish.rancher.io/rancher/rancher/6028 passes

**Comment by slickwarren** [comment]
on master-head (01665d0):
* provision downstream cluster using ec2 provisioner, single node, rancher installed via docker (self signed certs) -- pass
* provision downstream cluster using ec2 provisioner, single node, rancher is HA installed (byo certs) -- pass
* calling out that, multi-node use case is tracked here: #32362
