### ISSUE TITLE
Go back to previous URL when logging back in

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#3238]
If you try to load a page, like http://rancher:8080/apps/add?githubRepo=something, but aren't logged in, you should get sent back to the same URL after logging in.

**Comment by kaos** [comment]
+1

on a related note, it would be nice to have a perm-link option somewhere, that also conveys the selected environment, for sharing links etc..

**Comment by vincent99** [comment]
@kaos #677

**Comment by tfiduccia** [comment]
version - master 1/19
Verified fixed
