### ISSUE TITLE
RKE2 Provisioning: Cluster Options - Authorized Cluster Endpoint (ACE)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32388]
```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.20.5+rke2r1
  rkeConfig:

#    localClusterAuthEndpoint:
#      caCerts: string
#      enabled: boolean
#      fqdn: string
```l

**Comment by rancher-max** [comment]
### Validated using master-head build `6757965`

Performed the following checks on all below scenarios:
- `kube-api-auth` deployed as expected 
- local kubectl shell works correctly
- Downloaded kubeconfig correctly has two contexts, and one of them is directly to the IP of my node. Using this context works for kubectl requests. Example:
  ```
  $ k config get-contexts && k get nodes
  CURRENT   NAME                      CLUSTER                   AUTHINFO   NAMESPACE
            maxempty                  maxempty                  maxempty   
  *         maxempty-maxempty-x627l   maxempty-maxempty-x627l   maxempty   
  NAME                      STATUS   ROLES                       AGE     VERSION
  maxempty-maxempty-x627l   Ready    control-plane,etcd,master   9m50s   v1.21.2+rke2r1
  ```

**Scenario 1: Enabling ACE but leaving FQDN and Cert empty**

**Scenario 2: Enabling ACE with both FQDN and Cert supplied**

**Scenario 3: Enabling ACE with only FQDN supplied**

**Scenario 4: Disabling ACE**
- Validated `kube-api-auth` is not deployed
- local kubectl shell works correctly
- There is only 1 context in downloaded kubeconfig

---

### There are 2 failures that I am reopening this issue to address

1. When attempting to use Cert but no FQDN, I should see an error but I do not
2. When editing a cluster to remove or add ACE, it gets stuck in provisioning with only the following in the rancher-system-agent logs:
  ```
  Jun 30 19:17:50 maxedit-maxedit-j9nq7 rancher-system-agent[1420]: time="2021-06-30T19:17:50Z" level=debug msg="[K8s] writing an applied checksum value of 48988f444c5f391934a21ecf4d02087a3956e03704abdfdae6c9e8f59eea9b90 to the remote plan"
  Jun 30 19:17:50 maxedit-maxedit-j9nq7 rancher-system-agent[1420]: time="2021-06-30T19:17:50Z" level=debug msg="[K8s] updating lastAppliedResourceVersion to 1351977"
  Jun 30 19:17:52 maxedit-maxedit-j9nq7 systemd[1]: Stopping Rancher System Agent...
  Jun 30 19:17:52 maxedit-maxedit-j9nq7 systemd[1]: rancher-system-agent.service: Succeeded.
  Jun 30 19:17:52 maxedit-maxedit-j9nq7 systemd[1]: Stopped Rancher System Agent.
  ```

**Comment by rancher-max** [comment]
I want to add a note that the edit issue may be its own separate issue. I saw this when trying to deploy manifests as well and update the manifests on the cluster, with the same logs. I can create a new issue for that if desired?

**Comment by rancher-max** [comment]
The remaining issue has been fixed. Confirmed on v2.6-head commit `222dced`. Error received: `admission webhook "rancherauth.cattle.io" denied the request: CACerts defined but FQDN is not defined`
