### ISSUE TITLE
Can't Add Node to the Cluster Without Adding Role: All

### ISSUE THREAD

**Issue by zeeshanalisyed** [rancher/rancher#32396]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Go to Add Cluster in Rancher UI
- Add A Cluster with Cloud Provider None
- Click Next
- Now Execute docker Command given by racnher to add or Register Node into the cluster with etcd,controlplane selection
**Result:**
Node will stuck on Registration Mode Until and Unless I create the next Node with All Roles e.g. etcd,controlplane,worker

**Other details that may be helpful:**
Using Latest Rancger

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): latest
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom or None
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM (1/8GB)
- Kubernetes version (use `kubectl version`): v1.19.3

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:59 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Comment by superseb** [comment]
A worker is a requirement before cluster provisioning starts, see https://github.com/rancher/rancher/issues/31244#issuecomment-790274280
