### ISSUE TITLE
AKSV2: Update existing AKS proxy calls

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32399]
Proxy calls will need to be handled via cloud credentials now. If there are any functional changes please list them in the PR.

**Comment by cbron** [comment]
This went to test, but also needs 32587 to go to test before work can be done.

**Comment by prabalsharma** [comment]
How do I test this? 
Is dynamic cluster list for imports and  VNET list, good enough?

**Comment by cbron** [comment]
That you can do those things specifically with a cloud credential, and that AKSv1 proxy calls without a cloud credential are not impacted.

**Comment by prabalsharma** [comment]
I looked at AKSv1 on 2.6, after providing azure creds, UI was able to populate a list of k8s version (VNET is not part of AKSv1, Cluster list is part of imports and that cannot be done via AKSv1 on 2.6)
Also, I was also able to edit AKSv1 cluster after upgrading Rancher 2.5.8 to 2.6 (covered in test plan)
