### ISSUE TITLE
rancher server image can't be used

### ISSUE THREAD

**Issue by xinzhongyoumeng** [rancher/rancher#32395]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1.install dapper
curl -sL https://releases.rancher.com/dapper/latest/dapper-$(uname -s)-$(uname -m) > /usr/local/bin/dapper
chmod +x /usr/local/bin/dapper
2.build rancher server image
git clone https://github.com/rancher/rancher.git
git checkout v2.5.2

in order to speed up build, so we delete the test.
diff --git a/scripts/ci b/scripts/ci
index 247193c..3c56997 100755
--- a/scripts/ci
+++ b/scripts/ci
@@ -5,6 +5,5 @@ cd $(dirname $0)

 ./validate
 ./build
-./test
 ./package
 ./chart/ci

finally,
$ make 

**Result:**
in dist founder:
$ cat images
rancher/rancher:dev
rancher/rancher-agent:master-head

we can get the docker image(rancher/rancher:dev), we use this image to start rancher server by cli(docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:dev), but failed.
we curl 0.0.0.0:80 
curl: (56) Recv failure: Connection reset by peer

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
 Rancher version:v2.5.2
 lnstallation option:single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:42 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:19:17 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by superseb** [comment]
It takes a bit of time to start up and respond on HTTP(S), what is in the log of the container?

**Comment by xinzhongyoumeng** [comment]
In addition, I use the rancher dockerfile to build image, the result is same as we use dapper.
Here is how to build:
in rancher src directory：
$ go build
then we get the rancher binary file,
$ cd rancher/package/
$ docker build -t rancher:build .
then we get the image. And we start the container
$ docker run -d --restart=unless-stopped \
  -p 81:80 -p 4432:443 \
  --privileged \
  rancher:build
the result is the same as before.
Here is the log.
[one.log](https://github.com/rancher/rancher/files/6383718/one.log)

**Comment by superseb** [comment]
Does it respond when you `docker exec` into the container and run `curl -v https://localhost` ? The way to build the image according to our CI is running `make` in the root of repository.

**Comment by xinzhongyoumeng** [comment]
> Does it respond when you `docker exec` into the container and run `curl -v https://localhost` ? The way to build the image according to our CI is running `make` in the root of repository.

$ curl -v https://localhost

* Rebuilt URL to: https://localhost/
*   Trying 10.45.3.6...
* TCP_NODELAY set
* Connected to static-proxy.g0.360es.cn (10.45.3.6) port 3128 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to localhost:443
> CONNECT localhost:443 HTTP/1.1
> Host: localhost:443
> User-Agent: curl/7.58.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 503 Service Unavailable
< Server: squid/3.5.20
< Mime-Version: 1.0
< Date: Tue, 27 Apr 2021 10:37:54 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 3551
< X-Squid-Error: ERR_CONNECT_FAIL 111
< Vary: Accept-Language
< Content-Language: en
<
* Received HTTP code 503 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 503 from proxy after CONNECT
root@ac503253f5c9:/var/lib/rancher# * Rebuilt URL to: https://localhost/
2021-04-27 10:37:55.762189 E | etcdmain: error verifying flags, 'k3s' is not a valid flag. See 'etcd --help'.
root@ac503253f5c9:/var/lib/rancher# *   Trying 127.0.0.1...
2021-04-27 10:37:55.788796 E | etcdmain: error verifying flags, 'k3s' is not a valid flag. See 'etcd --help'.
root@ac503253f5c9:/var/lib/rancher# * TCP_NODELAY set
2021-04-27 10:37:55.805231 E | etcdmain: error verifying flags, 'k3s' is not a valid flag. See 'etcd --help'.
root@ac503253f5c9:/var/lib/rancher# * connect to 127.0.0.1 port 443 failed: Connection refused
2021-04-27 10:37:55.822289 E | etcdmain: error verifying flags, 'k3s' is not a valid flag. See 'etcd --help'.
root@ac503253f5c9:/var/lib/rancher# *   Trying ::1...
2021-04-27 10:37:55.841029 E | etcdmain: error verifying flags, 'k3s' is not a valid flag. See 'etcd --help'.
root@ac503253f5c9:/var/lib/rancher# * TCP_NODELAY set
2021-04-27 10:37:55.858631 E | etcdmain: error verifying flags, 'k3s' is not a valid flag. See 'etcd --help'.
root@ac503253f5c9:/var/lib/rancher# * Immediate connect fail for ::1: Network is unreachable
2021-04-27 10:37:55.873614 E | etcdmain: error verifying flags, 'k3s' is not a valid flag. See 'etcd --help'.
root@ac503253f5c9:/var/lib/rancher# *   Trying ::1...
2021-04-27 10:37:55.893354 E | etcdmain: error verifying flags, 'k3s' is not a valid flag. See 'etcd --help'.
root@ac503253f5c9:/var/lib/rancher# * TCP_NODELAY set
2021-04-27 10:37:55.907522 E | etcdmain: error verifying flags, 'k3s' is not a valid flag. See 'etcd --help'.
root@ac503253f5c9:/var/lib/rancher# * Immediate connect fail for ::1: Network is unreachable
2021-04-27 10:37:55.922004 E | etcdmain: error verifying flags, 'k3s' is not a valid flag. See 'etcd --help'.
root@ac503253f5c9:/var/lib/rancher# * Failed to connect to localhost port 443: Connection refused
2021-04-27 10:37:55.936401 E | etcdmain: error verifying flags, 'k3s' is not a valid flag. See 'etcd --help'.
root@ac503253f5c9:/var/lib/rancher# * Closing connection 0
2021-04-27 10:37:55.951650 E | etcdmain: error verifying flags, 'k3s' is not a valid flag. See 'etcd --help'.
root@ac503253f5c9:/var/lib/rancher# curl: (7) Failed to connect to localhost port 443: Connection refused
bash: syntax error near unexpected token `7'

**Comment by xinzhongyoumeng** [comment]
> curl -v https://localhost

$ curl -v https://localhost
* Rebuilt URL to: https://localhost/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 443 failed: Connection refused
*   Trying ::1...
* TCP_NODELAY set
* Immediate connect fail for ::1: Network is unreachable
*   Trying ::1...
* TCP_NODELAY set
* Immediate connect fail for ::1: Network is unreachable
* Failed to connect to localhost port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 443: Connection refused

**Comment by xinzhongyoumeng** [comment]
> Does it respond when you `docker exec` into the container and run `curl -v https://localhost` ? The way to build the image according to our CI is running `make` in the root of repository.

**Comment by xinzhongyoumeng** [comment]
I'm sorroy to close this by hand mistake.

**Comment by xinzhongyoumeng** [comment]
> Does it respond when you `docker exec` into the container and run `curl -v https://localhost` ? The way to build the image according to our CI is running `make` in the root of repository.

yes, but I can't get the response. If you have any suggestion?
