### ISSUE TITLE
forwardport: Longhorn images not included in rancher-images.txt

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32408]
forwardport of rancher/rancher#31995

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by deniseschannon** [comment]
Verified in the rancher-images.txt for v2.6.0-rc1 that the previous missing longhorn issues were in the release asset: 
https://github.com/rancher/rancher/releases/download/v2.6.0-rc1/rancher-images.txt

@sowmyav27 Who typically is responsible for validating that longhorn can install on an air-gap install?

**Comment by sowmyav27** [comment]
Longhorn is deployed successfully on an 2.6.0-rc1 airgap setup
