### ISSUE TITLE
[Forward port] Duplicate crb seen on the server after upgrading from 2.4.15 to 2.5-head

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#32401]
Forward port of the issue https://github.com/rancher/rancher/issues/32105 for master-head validations

**Comment by prachidamle** [comment]
@anupama2501 The forwardport PR for the original issue has been updated with this fix as well. So can you close the forward-port issue? here is the combined PR: https://github.com/rancher/rancher/pull/31833

**Comment by anupama2501** [comment]
Verified on master-8c014efa85314ab1cb1cb79261d2db9251ccf31d-head

1. On v2.4.15 --> created a users and added to project of cluster1 as owner and member and to cluster2 Project as owner and member. Restarted rancher and verified duplicates were created. 
2. Upgraded the rancher to v2.5.7 and added the same user by creating a new project as project owner and member. Verified new duplicates were created.
3. Upgraded rancher to the master-head commit mentioned above. Verified once the cluster is active all the duplicates are removed.
