### ISSUE TITLE
Test 1.22 early as it is dropping support for deprecated features

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32405]
https://kubernetes.io/docs/reference/using-api/deprecation-policy/

Here's what's getting dropped by version

https://kubernetes.io/docs/reference/using-api/deprecation-guide/

**Comment by paynejacob** [comment]
One feature being dropped is the ComponentStatus.  We use the component status to generate our ClusterComponentStatus object.  The state of the ClusterComponentStatus is displayed on the cluster page in the Ember UI.

Action items:
- The ember ui will always display unknown statuses for any cluster 1.22 or greater.  We may want to hide the status section for these clusters
_ The health syncer will need to be disabled for clusters 1.22 or greater or constant error messages will be logged.

https://github.com/rancher/rancher/blob/7676979baacb6122b858b0001104c52eef8c36a7/pkg/controllers/managementuser/healthsyncer/healthsyncer.go

**Comment by deniseschannon** [comment]
As 1.22 has GA-ed, we're creating other issues to track the release and closing this one.
