### ISSUE TITLE
rancher/wins:v0.1.0 missing for the wins-upgrader chart in v2.5.8-rc10

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32402]
**What kind of request is this:**

**Steps to reproduce:**

- Rancher Airgap install, save and load images to a [private registry from windows server](https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/populate-private-registry/)
- Provision a downstream windows cluster using the private registry
- Install the wins upgrader chart from Dashboard

**Result:**

Wins upgrade chart is installed from Dashboard without errors
but the `wins-upgrader-default` daemonset fails to come up active because `rancher/wins:v0.1.0` is missing

`ImagePullBackOff: Back-off pulling image "<private_registry_url>/rancher/wins:v0.1.0"`

**Other details that may be helpful:**

**Environment information**
- Rancher version: `v2.5.8-rc10`
- Installation option: single RKE Airgap

**Comment by aiyengar2** [comment]
Same comment as https://github.com/rancher/rancher/issues/32265#issuecomment-827775718, should be available in rc11

**Comment by izaac** [comment]
Rancher version `v2.5.8-rc11`
`rancher/wins:v0.1.0` is included in `rancher-windows-images.txt` and I see the pod come up active with this image from private registry.

Daemonset in `cattle-wins-system`
`wins-upgrader-default`
