### ISSUE TITLE
Corrupted Accounts

### ISSUE THREAD

**Issue by dax0** [rancher/rancher#3240]
I was in the webui and I deleted all users and now I just get a fail page when I go to the dashboard.  I tried to disable security from MySQL but it was already disabled. Any ideas?

**Comment by Rucknar** [comment]
I remember seeing something about how the default user that rancher uses behind the scenes is sometimes presented under the users tab, usually 1a1 with no username specified. I thought that this was subsequently hidden from view but it appears on my install. I suspect if you removed that user, you might have a experience issues. 

Just found a discussion on that : https://github.com/rancher/rancher/issues/2967

**Comment by deniseschannon** [comment]
@hibooboo2 This is exactly why we need to hide the account I mention in #2967

**Comment by hibooboo2** [comment]
If deleting 1a1 is causing issues than it doesn't need to be hidden we need to fix that issue. Deleting any account should not cause cattle to fail. Unless security is on and it is the last account.

**Comment by deniseschannon** [comment]
The last statement "unless security is on and it is the last account" is exactly the situation that the user most likely got into. @dax0 can verify.

**Comment by vincent99** [comment]
When access control is disabled you are implicitly logging into the `1a1` user.  Hiding that the account exists is bad, as it's the (default) single most important account and also the one you may be using.  Ditto prevention deactivation/deletion of it, changing yourself has legitimate uses.

The most reasonable thing to do seems to be to have the UI (but not the API) prevent you from deactivating the logged-in account.  And maybe do the same for demoting yourself.. there is no explicit ordering of account types but it could just be `if (type is admin) { no... }`.  Then if you want to do one of those things you have to get another admin to do it, or use the API.

**Comment by dax0** [comment]
Here's what confused me, it made me create a user when I enabled access control.  Then I disabled and wanted to enable it again and it once again asked me to create an account.  Since I already had an account, I thought I'd have to delete the existing accounts to be safe - which is what I did - and then I broke everything.

**Comment by vincent99** [comment]
It's not exactly labeled explicitly in the UI, but the `1a1` account exists at install and is who you're "logged in to" while access control is off.  When you turn on access control you are adding a credential to that existing account, not creating a new one.

**Comment by tfiduccia** [comment]
Probably should not be able to edit this account's Account Type either.  It would probably be bad if no admin exist.

**Comment by hibooboo2** [comment]
With the merge of rancher/cattle#1362 you can no longer lose the last admin account in rancer.

**Comment by deniseschannon** [comment]
Verified with v0.61.0-rc3 that you are unable to deactivate/edit whoever your last admin is in Rancher, which would prevent this issue.
