### ISSUE TITLE
forwardport: [rancher-wins-upgrader] rancher/wins image doesn't show up in air gapped setups

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32417]
forward port for: [rancher-wins-upgrader] rancher/wins image doesn't show up in air gapped setups rancher/rancher#32280

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by sowmyav27** [comment]
Check these images show in rancher-images.txt file - https://github.com/rancher/rancher/issues/32280#issuecomment-828048360

**Comment by deniseschannon** [comment]
I wasn't able to find the rancher/wins image in the v2.6.0-rc1 `rancher-images.txt` file, but it is in the `rancher-windows-images.txt`. 

As per the original issue, I validated that between v2.5.7 and v2.5.8, this image was introduced in the `rancher-windows-images.txt` file and not in the `rancher-images.txt`.
