### ISSUE TITLE
Role with permission deployments/scale does not work, statefulsets/scale does not exist

### ISSUE THREAD

**Issue by Hitesh-Agrawal** [rancher/rancher#32424]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
We don't have statefulsets/scale as an option in resources
Create a role to enable developers only restart deployments (scale down/up deployments) with inherit role -> "View Workload".
![image](https://user-images.githubusercontent.com/39374310/116383819-d75e9d80-a834-11eb-96a7-5ff5dcee667b.png)

**Result:**
The developers are not able to scale down/up the deployments.

**We need to have "update" permission on deployments resources to allow developers to  scale down/up deployments.**
If we allow "update" permission on deployments , the developers are able to update environment variables , image version , resource settings etc on the deployments type workload, which gives them more access than what we want.
![image](https://user-images.githubusercontent.com/39374310/116384277-548a1280-a835-11eb-93b4-5ab86434b15a.png)

**Environment information**

**Rancher version** : v2.5.7
**Installation option**: HA

**Cluster information**

**Cluster type** : RKE
**Kubernetes version (use kubectl version)**: v1.18.6
**Docker version** : 19.3.13

**Comment by Hitesh-Agrawal** [comment]
Can someone from rancher team look into this.

**Comment by Hitesh-Agrawal** [comment]
Any update on this?

**Comment by vincent99** [comment]
There is no field-level RBAC in kubernetes, so what you're asking for does not exist.  You either have permission to update the entire resource, or none of it.

The type names with a slash as you're trying to show are sub-resources (e.g. pod logs) but as you've noted the replica count is not in one; it's a property of the workload in the same resource as the image, envvars, etc.

It is possible to build a validating webhook or OPA constraint to enforce something like this, but not in just native k8s.

**Comment by rptaylor** [comment]
> The type names with a slash as you're trying to show are sub-resources (e.g. pod logs) but as you've noted the replica 
> count is not in one; it's a property of the workload in the same resource as the image, envvars, etc.

I don't believe that's correct: you do need a separate RBAC role for the /scale subresource to use `kubectl scale` on a deployment, like this:

```
  - apiGroups: ["apps"]
    resources: ["deployments/scale", "statefulsets/scale"]
    verbs: ["get", "update", "patch"]
```

See e.g. https://stackoverflow.com/questions/56205304/scale-kubernetes-deployments-via-api
