### ISSUE TITLE
v2 CIS Benchmark stuck when creating security-scan-runner pod after triggering a scan

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#32428]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* Deploy an upstream cluster using rancher:v2.5.8-rc12
* Go to Cluster Explorer for the local/upstream cluster and install `CIS Benchmark` app in version 1.0.400
* Create a Scan, `select rke-cis-permissive-1.6` scan profile from dropdown and click on Create

**Result:**
* scan is Reported as `Active`
* go to Pods in Cluster Explorer and see if pod `pod security-scan-runner-scan-*` is created and Running
* in my case the runner pod using image `rancher/security-scan:v0.2.3-rc3` is reporting state `Createcontainererror` and in Recent Event tab reporting:

```Error: Error response from daemon: create /var/log/journal: " /var/log/journal" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path```

**Other details that may be helpful:**
* used SLE15 as image for rancher local cluster - same result with added downstream cluster

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8-rc12
- Installation option (single install/HA): any

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom on AWS EC2
- Machine type (cloud/VM/metal) and specifications (CPU/memory): t3.xlarge
- Kubernetes version (use `kubectl version`): v1.19.9

**Comment by thehejik** [comment]
It doesn't work with sle15sp2/sp1 nor ubuntu on `1.0.400` - but previous v2 CIS chart `1.0.301` is working fine.

* The failing chart `1.0.400` is using image `rancher/security-scan:v0.2.3-rc3`
* The working chart `1.0.301` is using image `rancher/security-scan:v0.2.2`

**Comment by prachidamle** [comment]
@thehejik I think this issue is due to the space present in the path " /var/log/journal". This was fixed by @meldafrawi recently we will need to update the `rancher-cis-benchmark` chart with the latest build

**Comment by prachidamle** [comment]
Just tested on an rke cluster using rancher/cis-operator:v1.0.4-rc4 and rke permissive scan runs fine.

**Comment by sowmyav27** [comment]
On 2.5.8-rc12 - with `rancher/cis-operator:v1.0.4-rc5`, the CIS scan - rke permissive 1.6 runs on a downstream DO cluster.

**Comment by thehejik** [comment]
Thanks, I was able to deploy CIS Scan `1.0.400` chart from `dev-v2.5` chart repo on `rancher:2.5.8-rc12` and the scan is now Passing on SLE15SP1. No further action was needed - just that I had to refresh `Apps` several times to get latest chart update.

Snippet from current CIS values.yaml:
```
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.4-rc5
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.3-rc5
```
