### ISSUE TITLE
gkeV2- Labels field at cluster level, is missing 

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32433]
**What kind of request is this (question/bug/enhancement/feature request):** feature request

**Steps to reproduce (least amount of steps as possible):**
We are missing cluster level `Labels` parameter

<img width="834" alt="Screen Shot 2021-04-28 at 11 14 11 AM" src="https://user-images.githubusercontent.com/3749546/116452714-de74b400-a812-11eb-88bd-31a2b02c38eb.png">

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-1963c2e01996894c36480583903f5d5642702269-head
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
The UI for exposing cluster labels has been merged. The backend build that adds it to the schema keeps failing though. When the backend is in the front end should work. I verified that it is in fact sending the `labels` param on the `gkeConfig`.

**Comment by prabalsharma** [comment]
I can create a label. 
<img width="846" alt="Screen Shot 2021-05-03 at 11 13 26 AM" src="https://user-images.githubusercontent.com/3749546/116915210-971a6900-ac00-11eb-9ec9-dbc89ef084e3.png">
However, I cannot `delete` or `add a new one`, once the cluster is created.

GCP:

<img width="582" alt="Screen Shot 2021-05-03 at 11 27 22 AM" src="https://user-images.githubusercontent.com/3749546/116916712-8bc83d00-ac02-11eb-8145-a8378222f2a0.png">

**Comment by westlywright** [comment]
Added a UI fix to make the fields editable. Did not know they were.

**Comment by prabalsharma** [comment]
I am still seeing issues with `delete`

1. I cannot delete a label from Rancher, if there is only one label present
2. If there are two labels and I try to delete one from Rancher, both labels get deleted (and I can no longer add a new label with the old key=value which got deleted, from Rancher)

**Comment by westlywright** [comment]
There seem to be two issues here.

Back end: After a cluster is created which includes cluster labels (`gkeConfig.labels`) and the cluster has had enough time to provision and complete its first round trip sync, the labels exist in the upstream spec config and the metadata object in the Google GKE Console UI, but the `gkeConfig.labels` parameter is now null. 

Front end: When we have labels in our upstream config and the user removes the labels during edit, the UI doesn't send an empty map to indicate the removal of the labels (see rancher/ui#4609)
