### ISSUE TITLE
GKEv2- NP labels not getting set

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32435]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a GKE cluster 
2. Add `Node Labels`
3. click save

**Result:**
Once you click `save`. The request gets sent but gets lost in response and we end up with a cluster, with no NP labels.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cmurphy** [comment]
This one seems to be UI. Nodepool labels exist in the schema:

![image](https://user-images.githubusercontent.com/1220710/116456498-357c8800-a817-11eb-8c3f-02b45ae24e03.png)


And if I create it in the API it works:

![image](https://user-images.githubusercontent.com/1220710/116456395-167df600-a817-11eb-9c10-69b21a7e0dc6.png)

**Comment by westlywright** [comment]
@cmurphy its not UI, @prabalsharma and I went over this. I saved a cluster with node pool labels. The labels are sent to the api, but the response back contains a null labels in the node pool.

**Comment by cmurphy** [comment]
@westlywright sorry I still think it's UI:

UI is passing the labels as an array of "key=value" strings:

![image](https://user-images.githubusercontent.com/1220710/116492207-88266600-a850-11eb-91fb-50c57450a72e.png)

but the data type is a map/object. If I change the request to `"labels":{"foo": "bar"}` then it works with curl.

**Comment by westlywright** [comment]
@cmurphy My bad. I'm surprised the api doesn't error but I'll fix the ui.

**Comment by prabalsharma** [comment]
NP label gets set on GCP. However, `Edit` view (after cluster creation) still shows `None`

<img width="488" alt="Screen Shot 2021-04-29 at 12 25 58 PM" src="https://user-images.githubusercontent.com/3749546/116606775-100a7f80-a8e6-11eb-8330-5556ee9e8fc7.png">
