### ISSUE TITLE
Add Host AWS EC2 Account Access XMLParserError

### ISSUE THREAD

**Issue by asciifaceman** [rancher/rancher#3243]
Similar to https://github.com/rancher/rancher/issues/2472

When entering the Account Access keys following error occures:
`XMLParserError: s.getElementsByTagName(...)[0] is undefined`

```
Component 	Version
Rancher 	v0.51.0
Cattle 	v0.130.0
User Interface 	v0.78.0
Rancher Compose 	v0.7.0
```

I am seeing a 403 Forbidden on a POST concerning `http://rancherhost:8080/v1/proxy/ec2.ap-northeast-2.amazonaws.com/`

Unfortunately just regenerating keys isn't a valid solution unless last resort for me.
This was working until v0.51.0 for me.

**Comment by vincent99** [comment]
See https://github.com/rancher/rancher/issues/3185 .. it's not actually your keys.

**Comment by asciifaceman** [comment]
Thanks for the heads up, I will wait for the next release instead of making local changes.

+1 for Vincent
