### ISSUE TITLE
[GKE] Added cluster owner cannot edit cluster without providing cloud credential.

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#32446]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
On Rancher `v2.5.8-rc12`
Login as user1
Create a GKE cloud credential - test1
Create a GKE cluster using this credential
Verify the Cluster comes up Active
As Admin user, add user2 as cluster Owner of this cluster
Login as standard user2
Edit cluster

**Result:**
Cluster cannot be edited. Blocked with error: `cloud credential not found`
![Screen Shot 2021-04-28 at 2 03 21 PM](https://user-images.githubusercontent.com/57409052/116489101-ebac9580-a848-11eb-98cd-4c93064a867d.png)

**Other details that may be helpful:**
This is not seen on an EKSv2 cluster. User2 is able to access the cluster edit without providing their own cloud credential.
This issue is closely related to https://github.com/rancher/rancher/issues/32441, but the use case is slightly different. In EKS, the added cluster owner is not required to provide their own cloud credentials. Currently in GKE, the added cluster owner IS required to provide their own cloud credentials, or else the cluster cannot be edited.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5.8-rc12`
- Installation option (single install/HA): single install

**Comment by cmurphy** [comment]
@aaronRancher this looks like the same problem as described in https://github.com/rancher/rancher/issues/32441 - could we consolidate them?

**Comment by cmurphy** [comment]
It's a slightly different problem than #32441 because it's happening when the UI uses the cloud credential to call /meta/gkeZones where the other one is about modifying the cluster object, but the ultimate problem is the same, which is that cloud credentials aren't shared between users. If this cloud credential check was removed it would still run into #32441.

**Comment by rmweir** [comment]
https://github.com/rancher/rancher/compare/master...rmweir:gke-cluster-param?expand=1

**Comment by aaronRancher** [comment]
This issue is reproduced on Rancher `v2.5-head` `version f5f267f`

User2 cannot edit cluster after being made cluster owner by admin. Cannot get past error `cloud credential not found`

**Comment by aaronRancher** [comment]
Waiting on fix from: https://github.com/rancherlabs/rancher-security/issues/732

**Comment by aaronRancher** [comment]
This issue is validated on `Rancher v2.5-head` `version f5f267f` after a hard refresh to receive UI changes.
UI PR: https://github.com/rancher/ui/pull/4611

User2 is able to access the edit cluster page without having to provide their own cloud credential.
Tested an edit by scaling the node pool as user2. Cluster is scaled in Rancher and GKE console.

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 7d5a854` with the following steps:
Login as user1
Create a GKE cloud credential - test1
Create a GKE cluster using this credential
Verify the Cluster comes up Active
As Admin user, add user2 as cluster Owner of this cluster
Login as standard user2
Edit cluster

Result:
user2 is able to edit the cluster
