### ISSUE TITLE
Correctly provide the instances sizes for EC2 region's

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32444]
Currently we default to t2.medium for the ec2 node driver. Some ec2 regions do not have that and only have t3. 
We should either: 
* Hardcode what is available for exceptional regions
* Pull dynamically based on current region selected

See: https://github.com/rancher/rancher/issues/31980

**Comment by snasovich** [comment]
Closing due to age and lack of recent updates/interest in this.
