### ISSUE TITLE
Added cluster owner for GKEv2 and EKSv2 clusters cannot make edits

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#32441]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Login as user1
2. Create a GKE cloud credential - test1
3. Create a GKE cluster using this credential
4. Verify the Cluster comes up Active
5. As Admin user, add user2 as cluster Owner of this cluster
6. Login as standard user2 
7. Create a cloud credential as user2
8. Edit GKE cluster with user2 cloud cred
10. Add a nodepool to the cluster

**Result:**
Edit fails with `error accessing cloud credential`
![Screen Shot 2021-04-28 at 2 26 44 PM](https://user-images.githubusercontent.com/57409052/116474775-c8282180-a82d-11eb-9fd0-c3ecaf98d44f.png)

**Other details that may be helpful:**
API error:
![Screen Shot 2021-04-28 at 2 15 44 PM](https://user-images.githubusercontent.com/57409052/116473630-3ff54c80-a82c-11eb-8957-2d7072927869.png)
The UI sends the correct cloud credential in the GKE config.
![Screen Shot 2021-04-28 at 2 16 36 PM](https://user-images.githubusercontent.com/57409052/116473682-5dc2b180-a82c-11eb-9ba4-587b33e5f4b7.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5.8-rc12`
- Installation option (single install/HA): single install

**Comment by sowmyav27** [comment]
Seen on a hosted EKSV2 cluster too on 2.5.8-rc12 using the steps mentioned in the original issue's description

**Comment by aaronRancher** [comment]
Additionally, user2 can access the EKSv2 cluster without creating a cloud credential. On the GKEv2 cluster, user2 must create their own cloud credential or they cannot get to the edit ui (fails with `cloud credential not found`)

**Comment by aaronRancher** [comment]
This issue is seen on `v2.5.8-rc12` with an EKS cluster with the following steps.
eks operator version: `eks-operator:v1.0.8`
Steps:
Login as user1
Create an AWS cloud credential - test1
Create a EKS cluster using this credential
Verify the Cluster comes up Active
As Admin user, add user2 as cluster Owner of this cluster
Login as standard user2
Edit GKE cluster with user2
Scale the node group.

Edit fails with `error accessing cloud credential`

This behavior is not seen on `v2.5.7` with an EKSv2 cluster.
eks operator version: `eks-operator:v1.0.7`
Steps:
Login as user1
Create an AWS cloud credential - test1
Create a EKS cluster using this credential
Verify the Cluster comes up Active
As Admin user, add user2 as cluster Owner of this cluster
Login as standard user2
Edit GKE cluster with user2
Scale the node group.

The cluster is edited successfully. Node group is scaled in Rancher and EKS console.

**Comment by thedadams** [comment]
@westlywright We have narrowed down that something changed in the UI between 2.5.8-rc2 and 2.5.8-rc3. When I edit an EKS cluster in 2.5.8-rc1, the request sent by the UI contains a partial update:
```{"name":"donnie-test","eksConfig":{"nodeGroups":[{"desiredSize":1,"diskSize":11,"ec2SshKey":"","gpu":false,"imageId":"","instanceType":"t3.medium","labels":{},"launchTemplate":null,"maxSize":1,"minSize":1,"nodegroupName":"all","requestSpotInstances":false,"resourceTags":{},"spotInstanceTypes":[],"subnets":["subnet-0b18785c6669f8fed","subnet-0474d47f8adc92561","subnet-04fd4f103106c3c2e"],"tags":{},"type":"/v3/schemas/nodeGroup","userData":"","version":"1.18"}]}}```

However, the same update in 2.5.8-rc3 the UI sends a full update:
```{"dockerRootDir":"/var/lib/docker","enableClusterAlerting":false,"enableClusterMonitoring":false,"enableNetworkPolicy":false,"windowsPreferedCluster":false,"agentImage":"rancher/rancher-agent:master-head","agentImageOverride":null,"allocatable":{"cpu":"1930m","memory":"3422852Ki","pods":"17"},"annotations":{"authz.management.cattle.io/creator-role-bindings":"{\"created\":[\"cluster-owner\"],\"required\":[\"cluster-owner\"]}","clusters.management.cattle.io/ke-last-refresh":"1619805939","lifecycle.cattle.io/create.cluster-agent-controller-cleanup":"true","lifecycle.cattle.io/create.cluster-provisioner-controller":"true","lifecycle.cattle.io/create.cluster-scoped-gc":"true","lifecycle.cattle.io/create.mgmt-cluster-rbac-remove":"true"},"answers":{"clusterId":null,"projectId":null,"type":"/v3/schemas/answer"},"apiEndpoint":"https://3176C8C3FFFA5BD4FB0ECB8685B8E3C8.gr7.us-east-2.eks.amazonaws.com","appliedEnableNetworkPolicy":false,"appliedPodSecurityPolicyTemplateId":null,"appliedSpec":{"dockerRootDir":"/var/lib/docker","enableClusterAlerting":false,"enableClusterMonitoring":false,"enableNetworkPolicy":null,"windowsPreferedCluster":false,"agentImageOverride":"","answers":{"clusterId":null,"projectId":null,"type":"/v3/schemas/answer"},"clusterTemplateId":null,"clusterTemplateRevisionId":null,"defaultClusterRoleForProjectMembers":null,"defaultPodSecurityPolicyTemplateId":null,"description":"","desiredAgentImage":"","desiredAuthImage":"","displayName":"","eksConfig":{"imported":false,"amazonCredentialSecret":"cattle-global-data:cc-z5ffb","displayName":"donnie-test","kmsKey":"","kubernetesVersion":"1.18","loggingTypes":[],"nodeGroups":[{"desiredSize":1,"diskSize":11,"ec2SshKey":null,"gpu":false,"imageId":null,"instanceType":"t3.medium","labels":{},"launchTemplate":null,"maxSize":1,"minSize":1,"nodegroupName":"all","requestSpotInstances":false,"resourceTags":{},"spotInstanceTypes":null,"subnets":["subnet-0b18785c6669f8fed","subnet-0474d47f8adc92561","subnet-04fd4f103106c3c2e"],"tags":{},"type":"/v3/schemas/nodeGroup","userData":null,"version":"1.18"}],"privateAccess":false,"publicAccess":true,"publicAccessSources":["0.0.0.0/0"],"region":"us-east-2","secretsEncryption":false,"securityGroups":[],"serviceRole":"","subnets":[],"tags":{},"type":"/v3/schemas/eksClusterConfigSpec"},"internal":false,"localClusterAuthEndpoint":{"enabled":false,"type":"/v3/schemas/localClusterAuthEndpoint"},"type":"/v3/schemas/clusterSpec"},"authImage":null,"baseType":"cluster","caCert":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EUXpNREUzTVRZek0xb1hEVE14TURReU9ERTNNVFl6TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHNTClB1eTJpeXlNK21FcS9aUG5qRXlSZnZhMHA3aCt0NktYaGQzM29LK1BCMEkxajE5SDdvWVFjNXdEOWNWWGZPb0MKb3gxeVN6SmN5MmR1MEtWVzE0aHpBS3N0ZGpVd1BTdmk4M1VoRG12VXFFaHdsWFp6SGlIQVNBWDFQZ0FjbWVHTgpVL0FidTEwQWFyZjg3M29ZbGMxMUJTUXlXR1RJRW5xOHNBcHJ6eWNQN1JkVy9nV0d5eWhzTi9RZmRnTlc3dWpvCmlJbWNGRFdIYVBjY0tMNlYwSnRDeDhuQ2ZSYUt4K0ZZQWVranRaT2V6bGY3WkN3eDBueFFzTFViSlVuYWs4Y1gKK0dCNlNFS0tyd0xpeGxjYkIyZjB4US9oT04vNE5WemF4YnE0QmEzbWppc2F2MWdOR05wVHpjTmlRNFBqREVUOQoyNVFEcm00U1JGdnF3VzlWTWdNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFYmdWblpNVkxHSUR0aXJGK1NVdGJ3elU1WkUKQ0VLSWNhcDg1OTIxQmc5SVVRUGpPQ0xiTEZKS3g3TlgrZjVOenAvc2MzbCtWYmVCSkpMMHhTMXd6M2d4L1BPNQpSdHlMWmptTzQxanRLWTJwdU4xNVFlRml3U1JmQWZUc0duNzVRZmNDM2RoVFFrYnphSDBOUnRCeDZ5bHNwUktxCi9EeTlvZS9QOEJvOUdNcVR6THhvS0poYzZNWVJvdjZlUWY2MUIvZ0wrRHF1MDV2dTRkaFBUQ3dTamVLYW1zN08KNGxCTkkwT3EvMVd5NzdhRGUrT2RWUTA1RG1lQ2FYRDBobE51WTNwd2M1WWJaRmdYZGI2NjhRZEtjZm9YUEM2MwprRDNWY1B1dVp3QzdpRVpKU0V2YVVpdkplS3NkOWJGL2ZCK0xJOStOTkw0bTBQcC9mZ0ZpQVlNTzg5Zz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=","capabilities":{"nodePoolScalingSupported":false,"pspEnabled":false,"loadBalancerCapabilities":{"healthCheckSupported":false,"type":"/v3/schemas/loadBalancerCapabilities"},"type":"/v3/schemas/capabilities"},"capacity":{"cpu":"2","memory":"3977860Ki","pods":"17"},"clusterTemplateId":null,"clusterTemplateRevisionId":null,"componentStatuses":[{"conditions":[{"message":"ok","status":"True","type":"Healthy"}],"name":"controller-manager","type":"/v3/schemas/clusterComponentStatus"},{"conditions":[{"message":"{\"health\":\"true\"}","status":"True","type":"Healthy"}],"name":"etcd-0","type":"/v3/schemas/clusterComponentStatus"},{"conditions":[{"message":"ok","status":"True","type":"Healthy"}],"name":"scheduler","type":"/v3/schemas/clusterComponentStatus"}],"conditions":[{"status":"True","type":"Pending"},{"lastUpdateTime":"2021-04-30T10:20:29-07:00","status":"True","type":"Provisioned"},{"lastUpdateTime":"2021-04-30T10:23:14-07:00","status":"True","type":"Waiting"},{"lastUpdateTime":"2021-04-30T10:08:37-07:00","status":"True","type":"BackingNamespaceCreated"},{"lastUpdateTime":"2021-04-30T10:08:37-07:00","status":"True","type":"DefaultProjectCreated"},{"lastUpdateTime":"2021-04-30T10:08:37-07:00","status":"True","type":"SystemProjectCreated"},{"lastUpdateTime":"2021-04-30T10:08:37-07:00","status":"True","type":"InitialRolesPopulated"},{"lastUpdateTime":"2021-04-30T10:08:37-07:00","status":"True","type":"CreatorMadeOwner"},{"lastUpdateTime":"2021-04-30T10:08:39-07:00","status":"True","type":"NoDiskPressure"},{"lastUpdateTime":"2021-04-30T10:08:39-07:00","status":"True","type":"NoMemoryPressure"},{"lastUpdateTime":"2021-04-30T10:48:17-07:00","status":"True","type":"Updated"},{"lastUpdateTime":"2021-04-30T10:23:01-07:00","status":"False","type":"AlertingEnabled"},{"lastUpdateTime":"2021-04-30T10:23:03-07:00","status":"True","type":"SystemAccountCreated"},{"lastUpdateTime":"2021-04-30T10:23:10-07:00","status":"True","type":"AgentDeployed"},{"lastUpdateTime":"2021-04-30T10:23:12-07:00","status":"True","type":"GlobalAdminsSynced"},{"lastUpdateTime":"2021-04-30T10:23:12-07:00","status":"False","type":"PrometheusOperatorDeployed"},{"lastUpdateTime":"2021-04-30T10:23:14-07:00","status":"True","type":"Ready"}],"created":"2021-04-30T17:08:36Z","createdTS":1619802516000,"creatorId":"u-j4rjm","defaultClusterRoleForProjectMembers":null,"defaultPodSecurityPolicyTemplateId":null,"description":null,"desiredAgentImage":null,"desiredAuthImage":null,"driver":"EKS","eksConfig":{"imported":false,"amazonCredentialSecret":"cattle-global-data:cc-z5ffb","displayName":"donnie-test","kmsKey":null,"kubernetesVersion":"1.18","loggingTypes":[],"nodeGroups":[{"desiredSize":2,"diskSize":11,"ec2SshKey":null,"gpu":false,"imageId":null,"instanceType":"t3.medium","labels":{},"launchTemplate":null,"maxSize":2,"minSize":2,"nodegroupName":"all","requestSpotInstances":false,"resourceTags":{},"spotInstanceTypes":null,"subnets":["subnet-0b18785c6669f8fed","subnet-0474d47f8adc92561","subnet-04fd4f103106c3c2e"],"tags":{},"type":"/v3/schemas/nodeGroup","userData":null,"version":"1.18"}],"privateAccess":false,"publicAccess":true,"publicAccessSources":["0.0.0.0/0"],"region":"us-east-2","secretsEncryption":false,"securityGroups":[],"serviceRole":null,"subnets":[],"tags":{},"type":"/v3/schemas/eksClusterConfigSpec"},"eksStatus":{"managedLaunchTemplateID":"lt-07a3aade23da0fd82","managedLaunchTemplateVersions":{"all":"2"},"privateRequiresTunnel":null,"securityGroups":null,"subnets":["subnet-0b18785c6669f8fed","subnet-0474d47f8adc92561","subnet-04fd4f103106c3c2e"],"type":"/v3/schemas/eksStatus","upstreamSpec":{"imported":false,"amazonCredentialSecret":"cattle-global-data:cc-z5ffb","displayName":"donnie-test","kmsKey":null,"kubernetesVersion":"1.18","loggingTypes":[],"nodeGroups":[{"desiredSize":1,"diskSize":11,"ec2SshKey":null,"gpu":false,"imageId":null,"instanceType":"t3.medium","labels":{},"launchTemplate":null,"maxSize":1,"minSize":1,"nodegroupName":"all","requestSpotInstances":false,"resourceTags":{},"spotInstanceTypes":null,"subnets":["subnet-0b18785c6669f8fed","subnet-0474d47f8adc92561","subnet-04fd4f103106c3c2e"],"tags":{},"type":"/v3/schemas/nodeGroup","userData":null,"version":"1.18"}],"privateAccess":false,"publicAccess":true,"publicAccessSources":["0.0.0.0/0"],"region":"us-east-2","secretsEncryption":false,"securityGroups":[],"serviceRole":null,"subnets":[],"tags":{},"type":"/v3/schemas/eksClusterConfigSpec"},"virtualNetwork":"vpc-0d18a1e7824c2b5e5"},"fleetWorkspaceName":"fleet-default","gkeStatus":{"privateRequiresTunnel":null,"type":"/v3/schemas/gkeStatus","upstreamSpec":null},"id":"c-bcwlt","internal":false,"istioEnabled":false,"labels":{"cattle.io/creator":"norman","fleet.cattle.io/cluster-name":"c-bcwlt","provisioning.cattle.io/claimed-by-name":"c-bcwlt","provisioning.cattle.io/claimed-by-namespace":"fleet-default","rancher.cattle.io/claimed-by-name":"c-bcwlt","rancher.cattle.io/claimed-by-namespace":"fleet-default"},"limits":{"cpu":"0","memory":"340Mi","pods":"0"},"name":"donnie-test","nodeCount":1,"nodeVersion":0,"provider":"eks","requested":{"cpu":"310m","memory":"140Mi","pods":"7"},"state":"active","transitioning":"no","transitioningMessage":"","type":"cluster","uuid":"83fa32ef-df59-403e-bd77-85485ef89977","version":{"buildDate":"2021-03-10T21:33:25Z","compiler":"gc","gitCommit":"7737de131e58a68dda49cdd0ad821b4cb3665ae8","gitTreeState":"clean","gitVersion":"v1.18.16-eks-7737de","goVersion":"go1.13.15","major":"1","minor":"18+","platform":"linux/amd64","type":"/v3/schemas/info"},"expiringCerts":[]}```

The full update is what is breaking this particular issue for EKS. Because of syncing and cloud-credentials (at least), the validation in the backend expects the UI to send only the parts of the cluster that are being changed. When the UI sends the full cluster object on update, the backend is validating the entire cluster object (including cloud-credentials) and that is causing a problem.

Is there a reason the UI is sending the full cluster on update? If there is not, then sending a partial update as before (in 2.5.8-rc2) will fix this issue.

**Comment by westlywright** [comment]
@thedadams No it should be sending only the updates, with the exception of the node pools where the full node pool array and node pool properties are sent every time, not just the changes as is expected with the main eksConfig or gkeConfig. This is a UI issue that introduced when I refactored the eks syncing logic to be generic for both eks and gke. PR is up.

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5-head` `version 4e4bd25`

Saw the same issue on a GKEv2 cluster. Cluster edit errors with `error accessing cloud credential`.

This behavior is not seen on a EKSv2 cluster. User2 is able to edit the cluster without an error. Was able to scale a node pool and see the change reflected in Rancher and EKS console.

**Comment by aaronRancher** [comment]
After checking with @westlywright and @rmweir, this behavior seen on the GKE cluster is due to this issue: https://github.com/rancher/rancher/issues/32446

Currently, user2 does not have access to the cloud credential originally created by user1. So to access the edit page of the GKE cluster, we create a new cloud credential for user2.
This causes the new credential to be sent in the edit request (in this case, the node pool is scaled):
```
{name: "aaron-user1",…}
gkeConfig: {googleCredentialSecret: "cattle-global-data:cc-8645q", nodePools: [{,…}]}
googleCredentialSecret: "cattle-global-data:cc-8645q"
nodePools: [{,…}]
name: "aaron-user1"
```
The UI is no longer sending the entire config, only the fields that were edited. This results in an error. User2 cannot change the cloud credential unless they have access to the old credential.

To test this, we can make the same edit from the API, and remove the cloud credential from the request. When this is done, the edit succeeds. The node pool is scaled in both Rancher and GKE console.

**Comment by sowmyav27** [comment]
Waiting for this - https://github.com/rancher/rancher/issues/32446 to be fixed to test this issue completely.

**Comment by aaronRancher** [comment]
Validated this issue on a GKE cluster. On `Rancher v2.5-head` `version f5f267f`.
User2 is able to make an edit (add a node pool) when added as a cluster owner. Node pool is added in Rancher and GKE console.

Validated as a part of this issue:
https://github.com/rancher/rancher/issues/32446#issuecomment-831618414
