### ISSUE TITLE
Plan to support rke2 cluster.yaml configuration?

### ISSUE THREAD

**Issue by jmatsushita** [rancher/rancher#32453]
**What kind of request is this (question/bug/enhancement/feature request):**
**Question**

Is there a plan to support the possibility to configure a new rke2 cluster via a cluster.yaml configuration file? https://docs.rke2.io/install/install_options/install_options/#configuration-file This would allow to define cluster templates and new clusters from existing configuration as well as reuse this file with the terraform provider (see related issue https://github.com/rancher/terraform-provider-rancher2/issues/639)

**Comment by superseb** [comment]
Please follow https://github.com/rancher/rancher/issues/32374
