### ISSUE TITLE
Rancher cluster explorer , view pod logs screen doesn't seem to fit in the frame 

### ISSUE THREAD

**Issue by vrajannagari** [rancher/rancher#32464]
Login to rancher
Choose a cluster -> Cluster explorer ,
Pods -> view pod logs 

Notice that the bottom portion of the screen is completely cut off and cannot figure out what are the options available, how we can download ,filter logs, change the amount of logs to be displayed etc.

Versions|Rancher `v2.5.7` UI: `v2.5.6` |
![Screen Shot 2021-04-29 at 3 19 13 PM](https://user-images.githubusercontent.com/43918827/116613456-4c49da00-a8fe-11eb-8ae1-477c254096c6.png)

**Comment by vincent99** [comment]
https://github.com/rancher/dashboard/issues/2632
https://github.com/rancher/dashboard/issues/2488
