### ISSUE TITLE
Drop old Logging v2 charts

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#32460]
Similar to: https://github.com/rancher/charts/pull/1158

**Comment by izaac** [comment]
Rancher version `v2.5.8-rc16`
```
status:
  branch: dev-v2.5
  commit: 8d8c3c7db866f1d7fcb73719358cec8aaa178860
```

I still see old versions listed besides the latest on the Dashboard.
I am able to install oldest version available. `3.6`

![Screen Shot 2021-04-30 at 5 24 21 PM](https://user-images.githubusercontent.com/27659/116765268-2a715580-a9d9-11eb-8683-e62a00b48b86.png)

**Comment by cbron** [comment]
Oh, I did a poor job of explaining this one. I meant only the latest RC for any version new in 2.5.8. We definitely want to see all the [previously released logging versions](https://github.com/rancher/charts/tree/release-v2.5/assets/rancher-logging), just only one new version for 2.5.8.

**Comment by izaac** [comment]
I think the reason of the `(Linux-only)` on older versions is the added windows support in `3.9.400` this is commonly seen in other charts like Monitoring.

```yaml
  branch: dev-v2.5
  commit: 8d8c3c7db866f1d7fcb73719358cec8aaa178860
```

- Fresh install `v2.5.8-rc17`
- Upgrade path from `v2.5.7` -> `v2.5.8-rc17`

The charts shown in the version dropdown include the latest chart of 2.5.8 (3.9.400) and the others previously released as [mentioned](https://github.com/rancher/rancher/issues/32460#issuecomment-830633787).

![Screen Shot 2021-05-01 at 8 17 17 AM](https://user-images.githubusercontent.com/27659/116786827-ab6e3280-aa55-11eb-805d-73c7032f1565.png)
