### ISSUE TITLE
[Forwardport] No error displayed when no nodepool name is entered during an Edit of a GKEv2 cluster

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#32486]
Forwardport of https://github.com/rancher/rancher/issues/32467

PR for `v2.5-head`: https://github.com/rancher/rancher/pull/32468

**Comment by cmurphy** [comment]
The forwardport was merged: https://github.com/rancher/rancher/pull/32482

**Comment by aaronRancher** [comment]
This issue is validated on Rancher `master-head` `version d7ef41e`
Steps:
Deploy a hosted/imported GKE cluster.
When the cluster is up and Active, Edit cluster --> Add a nodepool and without entering a name, click on Save

Result:
An error is shown from UI:
![Screen Shot 2021-05-14 at 9 54 31 AM](https://user-images.githubusercontent.com/57409052/118303525-6658f000-b49a-11eb-9d1d-4fc68985f25d.png)
