### ISSUE TITLE
Support private repositories for Rancher Catalog

### ISSUE THREAD

**Issue by donny-dont** [rancher/rancher#3248]
Currently Rancher Catalog only supports public GitHub repositories for the catalog. For organizations attempting to limit the access to Rancher having the ability to support private GitHub repositories would be beneficial to have.

**Comment by vincent99** [comment]
It does not *need* to be GitHub or hosted on the internet or public or anything in particular.  The catalog service basically just runs `git clone ${url you provided}`.

If authentication is required to clone that URL, that needs to be provided.  For basic auth you can do `https://user:pass@host/path`.  For SSH (e.g. `git@github.com:org/repo`) the private key needs to be put into the rancher/server container.  But it appears we don't package SSH so that's a problem..

**Comment by donny-dont** [comment]
Providing the OAuth token for the repository ended up working for us. It might be nice if the catalog did something similar to Drone with the .netrc file so it would just work.

**Comment by flypenguin** [comment]
oh and I would need that, too ... maybe in 0.52?
especially with that meetup getting closer ...  :grin:

**Comment by donny-dont** [comment]
After thinking about it the issue is more about usability. It would be nice if you had GitHub OAuth setup if the UI could search for repositories on GitHub for the catalog repository. In general terms it would be nice if the UI gave you an error message saying that it could not pull the catalog instead of having to go to the logs to figure out it couldn't grab the catalog. It would suggest that either it doesn't exist so you should check the repository url or if it couldn't authenticate suggest a URL which contains the username password or OAuth token.

**Comment by flypenguin** [comment]
AFAIR setting up github oauth requires a callback from github to rancher - which is currently running in our AWS VPC and can't be reached from the outside world. That would be a problem, cause I had to enable access to rancher from "the internet", which I kinda don't want to do. (but please correct me if I'm wrong)

**Comment by CumpsD** [comment]
This would be very nice to have, we wouldnt create a private catalog if it ends up on a public space. Being able to use a private repo would be nice.

**Comment by nor-bu** [comment]
Hi, @vincent99 i try ti add a private catalog with a http://user:pass@host/path but it won't work.
Whe i use the same url on my computer for test it works fine.

Can you help me?

**Comment by dj-hedgehog** [comment]
For those using GitLab:
You can pull from a private repo by using a URL in this format:
https://gitlab-ci-token:<token>@git.example.com/group/mycatalog.git

You can find the CI token for the project when editing a project as the "Runners token" (you probably have to enable builds and set up a runner).

**Comment by rb1980** [comment]
I can't get catalog to work with an internally hosted gitlab server. To be clear: when you say:
> For those using GitLab:
>You can pull from a private repo by using a URL...
Do you mean more specifically a repository in gitlab that is NOT set to public?
My catalog repo is PUBLIC on my PRIVATE gitlab server, but I can't get it to work.
I am able to `git clone https://my.private.gitlab.server/group/catalog.git` from the rancher management hosts, with no auth just fine. Which leads me to believe I don't need a CI token.
Wondering if anyone else has gotten this to work, and what I am missing.

**Comment by galindro** [comment]
+1

**Comment by DirkBrand** [comment]
@rb1980 I have exactly the same issue as you, but using a private Bitbucket instance with a repo that I made public (i.e. no username and password required).  Catalog service doesn't like that.  I tried using http rather than https, but that didn't help.  What do you mean by 'turning https off'?

**Comment by InAnimaTe** [comment]
@dj-hedgehog You can no longer do that ;( Gitlab-CI now generates unique tokens for each CI run.

You could generate your own personal access key, but that is global r/w for your account meaning if someone got that key, you're screwed ;(

I'm probably going to have to do my own image where ssh is installed and I copy in a private key. In that case, I can merely do a deploy key for the specific repo containing my catalog.

**Comment by remotesyssupport** [comment]
With github we found that we could use [x-oauth-cloning ](https://github.com/blog/1270-easier-builds-and-deployments-using-git-over-https-and-oauth) based cloning for private github repos:

example:  https://<token>:x-oauth-basic@github.com/owner/repo.git

and it worked perfectly fine. Hope this helps

**Comment by NDevox** [comment]
For bitbucket it is possible to generate an API key for teams under the API key in the manage team page.

This will allow you to access the repo with https via `https://{team-name}:{API-key}@bitbucket.org/{team-name}/{repo}`

**Comment by flaccid** [comment]
The way I'm doing it is using the following script to run Rancher, https://github.com/flaccid/rightscripts/blob/master/install_and_run_rancher.bash. Set `RANCHER_CONTAINER_SSH_PRIV_KEY` with the git repo's SSH priv key needed and if required set `RANCHER_CONTAINER_POST_CMDS` to something like `sh -c 'ssh-keyscan -p 7999 my.git.host.com >> /root/.ssh/known_hosts` so the host key is accepted when checkout is attempted by server. A solution for git+ssh until native support.

**Comment by ekristen** [comment]
It would be really nice to see this added as soon as possible. Adding the ability to store credentials or ssh key when adding a custom catalog.

**Comment by mattdodge** [comment]
Surprised no one has mentioned this but you can use [Personal Access Tokens](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) for this. Granted, they are tied to a user and not an organization or repo or anything, but they get the job done and at least prevent you from having to make your repo public.

Go to your account (or if your team has a bot Github account) and make a personal access token. The token just needs the `"repo"` permission to access private repos. Then your git clone URL looks something like `https://account_username:personal_access_token@github.com/yourorg/yourrepo.git`.

**Comment by royerhq** [comment]
"For SSH (e.g. git@github.com:org/repo) the private key needs to be put into the rancher/server container. But it appears we don't package SSH so that's a problem.."

This would be great if this can happen soon :)

**Comment by ferhimedamine** [comment]
+1 for usuablity, we need a way support managing private ssh keys.. in order to be able to pull private catalogs. with the introduction of secrets, that would be a good combo

**Comment by mrfelton** [comment]
The suggested workarounds with private access tokens do not work with rancher 2.x. It fails with the following error:

> "transitioningMessage": "parse git clone https://[myuser]:[mytoken]@github.com/[myorg]/[myrepo].git/index.yaml: first path segment in URL cannot contain colon",

**Comment by pdschandler** [comment]
Hello, SSH functionality would be great, but I don't hate using https and tokens for this. However, GitLab is apparently formatting their API URLs differently these days and not allowing basic auth at the beginning of the URL. Instead, you have to insert a token at the end. The following URLs work in a browser:
`https://gitlab.com/<mycompany>/<myrepo>/raw/index.yml?private_token=0000000000`
`https://gitlab.com/api/v4/projects/<projectID>/repository/files/index%2Eyml/raw?ref=master&private_token=0000000000`
...but for RancherOS I obviously need to remove index.yml first. You're probably seeing the issue already, the end result is this:
`https://gitlab.com/<mycompany>/<myrepo>/raw?private_token=0000000000/index.yml`
...and the same result for the other URL.

So it seems like this would work fine if either GitLab didn't change to this insane formatting, or if RancherOS could support sending a simple header so I can add a `private_token` variable.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/13371 which will be released in 2.2.
Please raise a new issue if you have other questions.

**Comment by akkie** [comment]
@pdschandler A workaround would be to use a URL such as:
```
https://gitlab.com/<mycompany>/<myrepo>/raw/index.yml?private_token=00000000&bullshit=
```

Which ends in an URL like:
```
https://gitlab.com/<mycompany>/<myrepo>/raw/index.yml?private_token=00000000&bullshit=/index.yaml
```

Anyway, it seems this issue is fixed with the next 2.2 release

**Comment by pdschandler** [comment]
Thanks @akkie but I don't think that will work for my main use-case. Changing the fake ignore variable will not traverse the folder structure at all. RancherOS expects to find an index.yml file on it's own within a root folder path, and then uses that information to find folders in the same location that have docker-compose files in them. Thanks though, good idea in terms of one-off links.

**Comment by leodotcloud** [comment]
Thanks to https://github.com/rancher/rancher/issues/3248#issuecomment-265512324. The following steps worked for me to configure a private repo in github as a catalog in Rancher (tried on v2.2.8)

I generated a personal access token on github (Settings > Developer Settings > Personal Access Token) with "repo" access.

In the catalog page:
Username: <token from above step>
Password: `x-oauth-basic`
