### ISSUE TITLE
GKE V2 - No API error when adding second node pool with duplicate name

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#32493]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a hosted GKE v2 cluster through the UI with one node pool.
When active, edit cluster, and add a second node pool with the same name as the first

**Result:**
Cluster goes into an infiniate update loop. From the Rancher UI the cluster status never changes from `Updating` and on the GKE console side a new node pool is never created. The cluster will resize the node pool, finish, then start resizing again. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-a7ebbe6e68b94d0f83430f7c889e14f203fe43dc-head
- Installation option (single install/HA): HA

**Comment by prabalsharma** [comment]
Passed:

<img width="523" alt="Screen Shot 2021-05-03 at 12 09 08 PM" src="https://user-images.githubusercontent.com/3749546/116921101-60485100-ac08-11eb-9081-c7bb5ba922ae.png">
