### ISSUE TITLE
Authorized Cluster Endpoint for RKE2-based downstream clusters?

### ISSUE THREAD

**Issue by szalayg** [rancher/rancher#32507]
**Is your feature request related to a problem? Please describe.**
At a customer we have set up a Rancher Cluster with RKE2 and deployed Rancher successfully, as we have to switch from SuSe CaaSp. We could also successfully add a downstream RKE2 Cluster.
But. We would like to have an Authorized Cluster Endpoint to have the downstram clusters available at one single entry point (so no specific networking rules for the third party partners when accessing the network). So far it is only supported for Clusters created via Rancher. But those are not RKE2 clusters, afaik. Is there any way to create an RKE2 donstream cluster with Rancher for this kind of access (or any other solution to get the desired result)?

**Describe the solution you'd like**
I'd like to have an opportunity to either create RKE2 Downstream Clusters via Rancher itself, or the possibility to import them with full Authorized Cluster Endpoint support.

**Describe alternatives you've considered**
Theoretically it could be possible to create a cluster, and then switch to containerd (the servers are running Ubuntu, and they offer a tool for that: _juju_), but we are not sure, whether it

- would work further as expected
- would get support from Rancher/SuSe.

Since RKE2 is based on containerd, we would like to avoid the pains and risks with any workaround, but also we want to stick to a version which is more secure and is expected to have further support.

**Additional context**

**Comment by szalayg** [comment]
Copied from https://github.com/rancher/rke2/issues/945 , as suggested. I did not find an issue with similar content.

**Comment by cbron** [comment]
This is being worked on here: https://github.com/rancher/rancher/issues/31604

**Comment by Martin-Weiss** [comment]
We still required this feature!

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss Can we merge this into #31604?

Yes - as long as we can configure this feature for each imported cluster - during import and also after the import / for existing, already imported clusters  ;-).
