### ISSUE TITLE
some VPS will not boot rancheros.iso, yet work with IPXE script as follows:

### ISSUE THREAD

**Issue by PaulCharlton** [rancher/rancher#3250]
some VPS will not boot rancheros.iso, yet work with IPXE script as follows:

 rancheros.iso - MD5 0d91759f0a6599e1aea3ec9a95c61c11
 downloaded from latest 10-Jan-2016

==> ipxe script that works:

[ipxe script 20160113.pdf](https://github.com/rancher/rancher/files/88497/ipxe.script.20160113.pdf)

==> dmesg log from ISO boot: 

[dmesg log 20160110.pdf](https://github.com/rancher/rancher/files/88496/dmesg.log.20160110.pdf)

**Comment by deniseschannon** [comment]
@PaulCharlton This sounds like a RancherOS issue, would you mind opening it up in the rancher/os repo instead? https://github.com/rancher/os/issues

**Comment by PaulCharlton** [comment]
transferring issue to rancher/os
