### ISSUE TITLE
Unable to start Rancher fresh install on OpenSuse MicroOs or Tumbleweed. level=fatal msg="failed to find memory cgroup, you may need to add \"cgroup_memory=1 cgroup_enable=memory\" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)"

### ISSUE THREAD

**Issue by cryolithic** [rancher/rancher#32505]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

Install MicroOs or Tumbleweed and follow Rancher pre-req setup.
`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher`
`docker logs docker-cntr -f`

**Result:**
container exits after starting
Final log lines 
```
time="2021-05-03T05:26:17.156924491Z" level=info msg="Wrote kubeconfig /etc/rancher/k3s/k3s.yaml"
time="2021-05-03T05:26:17.156939752Z" level=info msg="Run: k3s kubectl"
time="2021-05-03T05:26:17.156943745Z" level=info msg="k3s is up and running"
time="2021-05-03T05:26:17.156979922Z" level=warning msg="Failed to find cpuset cgroup, you may need to add \"cgroup_enable=cpuset\" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)"
time="2021-05-03T05:26:17.156989272Z" level=error msg="Failed to find memory cgroup, you may need to add \"cgroup_memory=1 cgroup_enable=memory\" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)"
time="2021-05-03T05:26:17.156999855Z" level=fatal msg="failed to find memory cgroup, you may need to add \"cgroup_memory=1 cgroup_enable=memory\" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)"
2021/05/03 05:26:17 [FATAL] k3s exited with: exit status 1
```
[rancher.log](https://github.com/rancher/rancher/files/6412980/rancher.log)

**Other details that may be helpful:**
I was able to run without issue on Debian Buster (proxmox)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher 2.5.7

- Installation option (single install/HA):
Currently single install

- Docker version (use `docker version`):

```
Client:
 Version:           20.10.5-ce
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        363e9a88a11b
 Built:             Wed Mar  3 00:00:00 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.5-ce
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a88a11b
  Built:            Wed Mar  3 00:00:00 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.1.5_catatonit
  GitCommit:
[rancher.log](https://github.com/rancher/rancher/files/6412990/rancher.log)

```

**Comment by zolexander** [comment]
I have same issue on Fedora 34, and Arch ( latest update on rolling release):
Docker version:
`Client:
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c28948e
 Built:             Mon Apr 12 14:10:41 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.3
  Git commit:       8728dd246c
  Built:            Mon Apr 12 14:10:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.0
  GitCommit:        8c906ff108ac28da23f69cc7b74f8e7a470d1df0.m
 runc:
  Version:          1.0.0-rc94
  GitCommit:        2c7861bc5e1b3e756392236553ec14a78a09f8bf
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`
On fedora 34:
`Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:35 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:20 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`
The logs are same on both system.
I was able  to run without issue on ubuntu 21.04,on  Linux mint 20.10 too.
[rancher.log](https://github.com/rancher/rancher/files/6475783/rancher.log)

**Comment by pdostal** [comment]
Hello, this issue has been reported also as [bugzilla.opensuse.org#1185167](https://bugzilla.opensuse.org/show_bug.cgi?id=1185167).

@thkukuk made there interesting comment:
> openSUSE switched already to cgroups v2, but looks like k3s is still using cgroups v1.

We can see this also on latest Tumbleweed on [openqa.opensuse.org](https://openqa.opensuse.org/group_overview/78) where last successfull test passed 19. 4. on `v2.5.8-rc2` and is constantly failing since 20. 4. `v2.5.8-rc4`.

**Comment by dhawton** [comment]
Looks related to the version of k3s used. Fixed in https://github.com/k3s-io/k3s/releases/tag/v1.20.4%2Bk3s1 but Rancher is using v1.19.8+k3s1

**Comment by ismaail** [comment]
same issue on Arch Linux

- Docker version 20.10.7
- docker-compose version 1.29.2

**Comment by diegonicacio** [comment]
Same issue on Arch 

- Docker version 20.10.8
- Kernel  5.13.10-arch1-1

**Comment by atrauzzi** [comment]
This gonna be fixed?

**Comment by manno** [comment]
Rancher 2.6.1 uses a newer version of k3s (v1.21.3+k3s1). However now I run into something like described in https://github.com/rancher/rancher/issues/34617 

When running `docker run -d -p 80:80 -p 443:443 --privileged -v /opt/rancher:/var/lib/rancher  ancher/rancher:v2.6.1`  , `/opt/k3s.log` contains this at the end:

```
E1012 14:43:32.370151     106 node_container_manager_linux.go:57] "Failed to create cgroup" err="cannot enter cgroupv2 \"/sys/fs/cgroup/kubepods\" with domain controllers -- it is in an invalid state" cgroupName=[kubepods]
E1012 14:43:32.370181     106 kubelet.go:1384] "Failed to start ContainerManager" err="cannot enter cgroupv2 \"/sys/fs/cgroup/kubepods\" with domain controllers -- it is in an invalid state"
```

**Comment by cedvan** [comment]
Same issue with Fedora Core OS :cry:  :
```
Operating System: Fedora CoreOS
Version: 34.20211031.3.0
Kernel: 5.14.14-200.fc34.x86_64
CPU: 2 Intel(R) Xeon(R) CPU E5-2470 0 
RAM: 4G
HDD0 (sda): 30G
Rancher version: v2.6.2
```
