### ISSUE TITLE
xip.io down

### ISSUE THREAD

**Issue by mruepp** [rancher/rancher#32500]
Since 30.4.21, xip.io is down. I figure, every rancher cluster using this integrated service and/or oauth integration is down. What is the intended plan to mitigate this situation?

**Comment by abhi1693** [comment]
You can try using https://nip.io/. It's an alternative to xip.io

**Comment by mruepp** [comment]
How to change the rancher domain name? Unable to connect, error 404 default backend. Unable to load the gui at all. Authentication is over azure service principal.

**Comment by vincent99** [comment]
Since it was written by a Basecamp employee and went down at nearly the same time as their kerfuffle it doesn't seem like a stretch to imagine they're related.

You can change the `ingress-ip-domain` setting to a different domain.

@mruepp the server URL is supposed to be something fixed (that you can update the value it resolves to when needed); an xip name is not any better for you than using the IP directly.  You will need to manually update the ingress, certs, and all the clusters trying to connect to the old name.

**Comment by docwho76** [comment]
Due to https://github.com/rancher/rancher/issues/24018 causing https://github.com/rancher/rancher/issues/23960 it seems like it is not possible to even switch to nip.io names. All I get is 503s from gateways.

**Comment by docwho76** [comment]
So, to anyone who is trying to switch to nip.io, here is what I had to do:

1. Click "Add Ingress" like you normally would in the Load Balancer section
2. Click over to the "Service Discovery" section QUICKLY and download the YAML for the ingress it just made
3. Watch the Ingress provision and then delete the ingress it created
4. Now import the YAML for the ingress you saw it create

At this point, you will have a working ingress for that workload. Adding further ingresses this way does not cull the ingresses you manually import.

**Comment by docwho76** [comment]
Nevermind, the ingresses stop working after some time.

**Comment by mruepp** [comment]
For everyone using the rancher quickstart terraform, the last article here resolved the issue. In short:
- Upgrade helm chart by connecting to the rancher cluster (kube_config_rancher_server.yaml) with the new url
- Rancher should be up again
- For every connected (imported) cluster, use the respective context:
```
get secrets kubectl -n cattle-system get secret
modify the secret cattle-credentials-<RANDOM_HASH>. change data.url (encode it with base64 beforehand)
modify both node and cluster agent in the same VM
modify cluster agent deployment
kubectl -n cattle-system edit deployment cattle-cluster-agent.
change CATTLE_SERVER env to your new domain/url
modify node agent
kubectl -n cattle-system edit daemonsets cattle-node-agent
change CATTLE_SERVER env to your new domain/url
```

**Comment by piyush94** [comment]
> Since 30.4.21, xip.io is down. I figure, every rancher cluster using this integrated service and/or oauth integration is down. What is the intended plan to mitigate this situation?

If you have cluster access from kubectl, you can edit the ingress entry and change `<your-address>.xip.io` to `<your-address>.nip.io`. No need to change `ingress-ip-domain` in Rancher global settings. This worked for me.

**Comment by luchatex** [comment]
rancher  -->全局(Global)-->高级设置(Settings)-->ingress-ip-domain-->nip.io
done!

**Comment by luchatex** [comment]
rancher  -->全局(Global)-->高级设置(Settings)-->ingress-ip-domain-->nip.io
done!

**Comment by robinbraemer** [comment]
Hey folks! Just wanted to point out that [knative](https://github.com/knative/serving) has switched to [**sslip.io**](https://sslip.io/) in its latest [release](https://github.com/knative/serving/releases/tag/v0.23.1) which is possibly one of the better alternatives to xip.io or nip.io. sslip is managed by VMware and supports custom domains, IPv6 and Let's Encrypt certificates.

**Comment by deniseschannon** [comment]
In v2.5.10, we will start using xip.io instead of sslip.io. 

https://github.com/rancher/rancher/issues/34214

**Comment by mruepp** [comment]
> In v2.5.10, we will start using xip.io instead of sslip.io.
> 
> #34214

I dont think so because xip.io is still down.

**Comment by deniseschannon** [comment]
Apologies, I mis-wrote and have corrected it. 

We are replacing xip.io with sslip.io
