### ISSUE TITLE
[Monitoring V2] Rebase to kube-prometheus-stack 16.x.x

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#32519]
Recurrent ticket to keep track of rebasing Monitoring V2 to the latest offering from [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack).

All dependencies will be updated accordingly as well.

### On Grafana Labs AGPLv3

Due to the recent news that Grafana Labs open-source projects will be switching to [AGPLv3](https://grafana.com/blog/2021/04/20/grafana-loki-tempo-relicensing-to-agplv3/), Monitoring V2 will **no longer upgrade the version of Grafana beyond 7.5.4** (which corresponds to a Helm chart version of [**6.8.2**](https://github.com/grafana/helm-charts/blob/6aa383a64e514bbb19830db19ea3a1badd7865ab/charts/grafana/Chart.yaml#L3)) until further notice.

**Comment by aiyengar2** [comment]
As part of this rebase, we should switch the CRD chart to using `rancher/shell` instead of `rancher/rancher-agent`.

cc: @StrongMonkey

**Comment by aiyengar2** [comment]
As part of this rebase, we will also need to switch the upstream Helm repository of kube-state-metrics from `kubernetes/kube-state-metrics` to `prometheus-community/helm-charts`, in accordance with a change from upstream.

**Comment by aiyengar2** [comment]
> As part of this rebase, we should switch the CRD chart to using `rancher/shell` instead of `rancher/rancher-agent`.
> 
> cc: @StrongMonkey

After investigation, we found out that `rancher/shell` requires root user privileges, which is an escalation of the current privileges we have with `rancher/rancher-agent`. Therefore, we are sticking to the old rancher/rancher-agent image.

**Comment by aiyengar2** [comment]
### Update On Grafana Labs AGPLv3

Since [the 7.5.7 release of Grafana](https://github.com/grafana/grafana/archive/refs/tags/v7.5.7.zip) does not contain the AGPLv3 license, we will now instead rebase to the upstream Helm chart at [6.11.0](https://github.com/grafana/helm-charts/blame/bf7e1110a5ee9258190d0377fea319bb8e764e62/charts/grafana/Chart.yaml) and bump the appVersion to 7.5.7.

Starting at [the 8.0.0 release of Grafana](https://github.com/grafana/grafana/archive/refs/tags/v8.0.0.zip), AGPLv3 is used so we will no longer keep Grafana up-to-date.

**Comment by aiyengar2** [comment]
Pushing Grafana rebase to a separate ticket in https://github.com/rancher/rancher/issues/33210

**Comment by slickwarren** [comment]
on master-head (ad099ee) tested the following:
clean install — Pass
Upgrade 9.4.20x -> 100.0.0+up16.6.0 — pass
uninstall + reinstall — pass
p0 usecase -- pass
Uninstall upgraded 100.0.0+up16.6.0 — pass
Uninstall clean 100.0.0+up16.6.0 — pass
checked all prometheus targets and grafana dashboards

**Comment by LockedThread** [comment]
What issue does Rancher have with Grafana's new license?
