### ISSUE TITLE
RKE2 Provisioning: Downloading SSH keys, SSH shell and RBAC around SSH key access

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32516]
- Added ability to download SSH keys
- Added ability to SSH through a shelll

Needs testing around RBAC, who should be able to access keys and shell

**Comment by anupama2501** [comment]
Verified on master-8c014efa85314ab1cb1cb79261d2db9251ccf31d-head

Create a cluster node driver - 1 node all roles
Once the node is active, from the cluster --> nodepools --> click on the ellipsis --> download ssh keys and login with the IP in the nodes - Pass
From the same location, execute into shell using ssh - PASS

**Comment by anupama2501** [comment]
Re-opening this issue for RBAC testcases: https://github.com/rancher/rancher/issues/32414

**Comment by anupama2501** [comment]
Closing this ticket as opened a new ticket to verify RBAC cases
