### ISSUE TITLE
Update Kiali to 1.34.0+

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#32529]
This version is not released yet and is not a known security release. 

- [ ]  Mirror images in rancher/image-mirror repo
- [ ] Pull changes into rancher-kiali-server chart
- [ ]  Update Istio Chart.yaml and Values.yaml to use the most recent version of Kiali

This version will have a fix for https://github.com/rancher/rancher/issues/32330

**Comment by brendarearden** [comment]
https://github.com/rancher/charts/blob/dev-v2.6/assets/rancher-istio/rancher-istio-100.0.0.tgz << The 100.0.0 version of the rancher-istio chart has Istio v1.10.1 and auto installs Kiali 1.35.0.

**Comment by brendarearden** [comment]
This is available for testing in the dev-v2.6 branch. rancher-istio v100.0.0 (this installs istio 1.10.2) and rancher-kiali-server v100.0.0 (this install kiali 1.35.0)

**Comment by anupama2501** [comment]
Kiali v1.35.0, istio v1.10.2

Create a downstream cluster with 3worker, 1etcd, 1 cp

- Install istio version 1.10.2 by enabling kiali
- Verified the version of kiali installed is rancher/mirrored-kiali-kiali:v1.35.0
- Deploy a demo bookservice app in the istio-injected namespace and verified the app has installed by nodeIP:port/productpage
- From cluster explorer --> istio --> click on the kiali --> from graph [select namespace where the app is installed], the traffic is shown for the book demo app
- Install the weighted demo bookservice app and verified traffic generated from kiali --> graph --> verified the traffic going through ingress gateway
- Enable egress gateway and verified the traffic via egress gateway

Blocked on update testing: #33737

**Comment by anupama2501** [comment]
Verified on master-head 21ab02c
1. Installed istio 1.9.600 and kiali 1.32.100 - deployed book demo app
2. Upgraded istio to version 1.10.2 
3. Verified kiali is upgraded to 1.35.0 - deployed weight based book demo and verified its working as expected
4. Updating by enabling egress-gateway and verified traffic goes through egress-gateway
