### ISSUE TITLE
rancher-machine: need ssh timeout to be configurable

### ISSUE THREAD

**Issue by sleepy-manul** [rancher/rancher#32526]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
We have (due to company policy) to use customized RHEL7 images that cause new VMs to have a very long setup time (on average 15 minutes) until the VM is finally ready to use and the ssh port opens. Because rancher-machine has a hard-coded limit for ssh timeouts (60 attempts * 3 seconds = 180 seconds = 3 minutes), we are currently unable to have the Rancher Azure node driver provision the VMs. 

The location of the hard-coded in the source code of rancher-machine timeout is here:
https://github.com/rancher/machine/blob/master/libmachine/mcnutils/utils.go#L102

**Result:**
When using an operating system with a long setup time, the machine provisioning fails with the error message "Error detecting OS: Too many retries waiting for SSH to be available. Last error: Maximum number of retries (60) exceeded"

**Other details that may be helpful:**
I have compiled my "own" version of Rancher that uses a timeout of 60 attempts * 60 seconds, but I lack the skills in Go to make the timeout truly configurable from the Rancher UI and submit a PR proposal.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): HA in an RKE cluster (3 nodes). Rancher is working fine in general.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure provider: Microsoft Azure
- Machine type (cloud/VM/metal) and specifications (CPU/memory): D2s_v3, 8 GiB RAM, 64 GiB HDD, customised Red Hat Enterprise 7 installation image (enterprise policy) with a very long setup time (ca. 15 mins)
- Kubernetes version (use `kubectl version`): v1.20.4-rancher1-1

```
Error detecting OS: Too many retries waiting for SSH to be available. Last error: Maximum number of retries (60) exceeded
```

- Docker version (use `docker version`):19.3.14

```
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:42 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:19:17 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by stupiddog1979** [comment]
Sadly, I have not received a review of this ticket and my corresponding PR. Please have a look at it.
