### ISSUE TITLE
Random IPs returned by DNS cause issue only in Debian distro

### ISSUE THREAD

**Issue by CBR09** [rancher/rancher#3252]
Hi @vincent99 and @ibuildthecloud,

I have launched a stack which consist of:
- redis service (scale=2): 10.42.60.196 and 10.42.213.237
- debian service (scale=1)

Firstly, I loged in to the shell of debian container and issue a ping command to redis service:
>root@d5a75ff509b7:/# ping -c1 redis                                             
>PING redis (`10.42.60.196`): 56 data bytes                                        
>64 bytes from 10.42.60.196: icmp_seq=0 ttl=64 time=0.046 ms                     
>--- redis ping statistics ---                                                   
>1 packets transmitted, 1 packets received, 0% packet loss                       
>round-trip min/avg/max/stddev = 0.046/0.046/0.046/0.000 ms                      
>root@d5a75ff509b7:/# ping -c1 redis                                             
>PING redis (`10.42.60.196`): 56 data bytes                                        
>64 bytes from 10.42.60.196: icmp_seq=0 ttl=64 time=0.063 ms                     
>--- redis ping statistics ---                                                   
>1 packets transmitted, 1 packets received, 0% packet loss                       
>round-trip min/avg/max/stddev = 0.063/0.063/0.063/0.000 ms                      
>root@d5a75ff509b7:/# ping -c1 redis                                             
>PING redis (`10.42.60.196`): 56 data bytes                                        
>64 bytes from 10.42.60.196: icmp_seq=0 ttl=64 time=0.045 ms                     
>--- redis ping statistics ---                                                   
>1 packets transmitted, 1 packets received, 0% packet loss                       
>round-trip min/avg/max/stddev = 0.045/0.045/0.045/0.000 ms   

Theoretically, the ping command should return the IPs randomly. In this case, if the first ping return IP `10.42.60.196`, the second one should return another IP `10.42.213.237`. However, I've tried it many time but it only returned the first one.

Additionally,  I also try to ping another public domain to verify the theory. In this case, it works correctly.
>root@d5a75ff509b7:/# ping -c1 haivl.com                                         
>PING haivl.com (`104.27.130.248`): 56 data bytes                                  
>64 bytes from 104.27.130.248: icmp_seq=0 ttl=61 time=193.795 ms                 
>--- haivl.com ping statistics ---                                               
>1 packets transmitted, 1 packets received, 0% packet loss                       
>round-trip min/avg/max/stddev = 193.795/193.795/193.795/0.000 ms                
>root@d5a75ff509b7:/# ping -c1 haivl.com                                         
>PING haivl.com (`104.27.131.248`): 56 data bytes                                  
>64 bytes from 104.27.131.248: icmp_seq=0 ttl=61 time=193.762 ms                 
>--- haivl.com ping statistics ---                                               
>1 packets transmitted, 1 packets received, 0% packet loss                       
>round-trip min/avg/max/stddev = 193.762/193.762/193.762/0.000 ms  

I then tried another case, this time I used ubuntu as a host to issue ping command, it doesn't have any issue as above. So I think this could be a DNS problem only in debian distro.

Thanks

**Comment by vincent99** [comment]
Works for me with `debian:latest`; Does your image maybe have dnsmasq or something else that's doing local caching?

`ping -c1 test` several times:
```
PING test.rancher.internal (10.42.145.53): 56 data bytes                        
PING test.rancher.internal (10.42.171.129): 56 data bytes                       
PING test.rancher.internal (10.42.171.129): 56 data bytes                       
PING test.rancher.internal (10.42.171.129): 56 data bytes                       
PING not7.rancher.internal (10.42.145.53): 56 data bytes  
```

```
root@0f24785dfd11:/# dig not7                                                   
                                                                                
; <<>> DiG 9.9.5-9+deb8u4-Debian <<>> test                                      
;; global options: +cmd                                                         
;; Got answer:                                                                  
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26558                       
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0         
                                                                                
;; QUESTION SECTION:                                                            
;test.                          IN      A                                       
                                                                                
;; ANSWER SECTION:                                                              
test.                   600     IN      A       10.42.171.129                   
test.                   600     IN      A       10.42.145.53                    
                                                                                
;; Query time: 7 msec                                                           
;; SERVER: 169.254.169.250#53(169.254.169.250)                                  
;; WHEN: Wed Jan 13 19:17:40 UTC 2016                                           
;; MSG SIZE  rcvd: 54

root@0f24785dfd11:/# uname -a                                                   
Linux 0f24785dfd11 3.16.0-57-generic #77~14.04.1-Ubuntu SMP Thu Dec 17 23:20:00 
UTC 2015 x86_64 GNU/Linux

root@0f24785dfd11:/# cat /etc/os-release                                        
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"                                       
NAME="Debian GNU/Linux"                                                         
VERSION_ID="8"                                                                  
VERSION="8 (jessie)"                                                            
ID=debian                                                                       
HOME_URL="http://www.debian.org/"                                               
SUPPORT_URL="http://www.debian.org/support/"                                    
BUG_REPORT_URL="https://bugs.debian.org/"                                       
```

**Comment by deniseschannon** [comment]
@CBR09 If you are still having this issue, please re-open. As @vincent99 mentioned, he didn't have any issues with `debian:latest`.
