### ISSUE TITLE
Validate fleet and logging work after deploying wins_upgrader

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32538]
On 2.5.7 and 2.5.8-rc

- On 2.5.7 have a windows cluster
- Upgrade to 2.5.8-rc
- Deploy wins_upgrader
- Deploy logging v2 and validate fleet

Validate ^^^ After fix for this issue https://github.com/rancher/rancher/issues/32194

**Comment by izaac** [comment]
Upgrade from `2.5.7` to `2.5.8-rc19`

I install `rancher-wins-upgrader` with `masquerade.enabled = true`

But the Init pod fails to come up active, this is the log:

```
 k logs -n cattle-wins-system wins-upgrader-default-qp7zh -c wins-upgrader
Error formatting a string: Index (zero based) must be greater than or equal to
zero and less than the size of the argument list..
At C:\scripts\upgrade.ps1:45 char:26
+ ... insUpgradePath = $('{0}{1}' -f $prefixPath -f $env:WINS_UPGRADE_PATH)
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({0}{1}:String) [], ParentCont
   ainsErrorRecordException
    + FullyQualifiedErrorId : FormatError
```

**Comment by izaac** [comment]
### Scenario 1

- Setup fleet with extra clusters for checks
- Upgrade from 2.5.7 to 2.5.8-rc19
- Install wins-upgrader  `masquerade.enabled = true`
- Install Logging chart on the windows cluster
- Check container and rke logs are flowing to the clusteroutput
- Check Fleet continues to work after upgrade.
  - Also removing adding back the git repo works and the windows bundle gets installed.

### Scenario 2

- Setup fleet with extra clusters for checks
- Upgrade from 2.5.7 to 2.5.8-rc19
- Install Logging chart on the windows cluster
- Install wins-upgrader  `masquerade.enabled = true`
- Check container and rke logs are flowing to the clusteroutput
- Check fleet works by installing windows bundles on the windows cluster
