### ISSUE TITLE
[Server] error with external db

### ISSUE THREAD

**Issue by elerion** [rancher/rancher#3253]
Hi,

I use rancher with an external database so I created my mysql database. To start rancher I use this command : 

```bash
docker run -d -p 9001:8080 --name rancher \                                                                                                                                                                     ~/Docker 130
-e CATTLE_DB_CATTLE_MYSQL_HOST=XX.XX.XX.XX\
-e CATTLE_DB_CATTLE_MYSQL_PORT=3306 \
-e CATTLE_DB_CATTLE_DATABASE=cattle \
-e CATTLE_DB_CATTLE_USERNAME=cattle \
-e CATTLE_DB_CATTLE_PASSWORD=cattle \
rancher/server
```

But I have an error : 

```
14:02:00.221 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class '' for connect URL 'null'
.
.
.
.
Caused by: java.sql.SQLException: No suitable driver
        at java.sql.DriverManager.getDriver(DriverManager.java:278) ~[na:1.7.0_91]
        at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1437) ~[commons-dbcp-1.4.jar:1.4]
        ... 65 common frames omitted
```

And differents variable are correctly set up

```
CATTLE_CATTLE_VERSION=v0.130.0
CATTLE_DB_CATTLE_DATABASE=cattle
CATTLE_DB_CATTLE_MYSQL_HOST=XX.XX.XX.XX
CATTLE_DB_CATTLE_MYSQL_PORT=3306
CATTLE_DB_CATTLE_USERNAME=cattle
```

**Comment by deniseschannon** [comment]
Did you create the cattle DB? Per the docs, you need to create the DB before trying to connect to it. 

http://docs.rancher.com/rancher/installing-rancher/installing-server/#using-an-external-database

**Comment by elerion** [comment]
Hi,

Yes I have done this, but It seems that a problem with my server. I solved it with a restart my server

**Comment by kangjianhua** [comment]
docker run -d --restart=always -p 8080:8080 \
    -e CATTLE_DB_CATTLE_MYSQL_HOST=172.16.100.100 \
    -e CATTLE_DB_CATTLE_MYSQL_PORT=3306 \
    -e CATTLE_DB_CATTLE_MYSQL_NAME=cattle \
    -e CATTLE_DB_CATTLE_USERNAME=cattle \
    -e CATTLE_DB_CATTLE_PASSWORD=cattle \
    rancher/server

Same as above mistakes  ？？？？？

error log：
2016/5/10 下午6:17:31	at liquibase.Liquibase.update(Liquibase.java:181) ~[liquibase-core-3.1.0.jar:na]
2016/5/10 下午6:17:31	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:342) ~[liquibase-core-3.1.0.jar:na]
2016/5/10 下午6:17:31	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:299) ~[liquibase-core-3.1.0.jar:na]
2016/5/10 下午6:17:31	at io.cattle.platform.liquibase.Loader.afterPropertiesSet(Loader.java:62) ~[cattle-framework-db-loader-0.5.0-SNAPSHOT.jar:na]
2016/5/10 下午6:17:31	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1571) ~[spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
2016/5/10 下午6:17:31	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1509) ~[spring-beans-3.2.5.RELEASE.jar:3.2.5.RELEASE]
2016/5/10 下午6:17:31	... 44 common frames omitted
2016/5/10 下午6:17:31Caused by: liquibase.exception.DatabaseException: Error executing SQL ALTER TABLE cattle.resource_pool ADD CONSTRAINT idx_pool_item UNIQUE (pool_type, pool_id, item): Specified key was too long; max key length is 1000 bytes
2016/5/10 下午6:17:31	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:61) ~[liquibase-core-3.1.0.jar:na]
2016/5/10 下午6:17:31	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:106) ~[liquibase-core-3.1.0.jar:na]
2016/5/10 下午6:17:31	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1189) ~[liquibase-core-3.1.0.jar:na]
2016/5/10 下午6:17:31	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1172) ~[liquibase-core-3.1.0.jar:na]
2016/5/10 下午6:17:31	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:352) ~[liquibase-core-3.1.0.jar:na]
2016/5/10 下午6:17:31	... 53 common frames omitted
2016/5/10 下午6:17:31Caused by: java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 1000 bytes
2016/5/10 下午6:17:31	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125) ~[mariadb-java-client-1.3.4.jar:na]
2016/5/10 下午6:17:31	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69) ~[mariadb-java-client-1.3.4.jar:na]
2016/5/10 下午6:17:31	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:261) ~[mariadb-java-client-1.3.4.jar:na]
2016/5/10 下午6:17:31	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:290) ~[mariadb-java-client-1.3.4.jar:na]
2016/5/10 下午6:17:31	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:344) ~[mariadb-java-client-1.3.4.jar:na]
2016/5/10 下午6:17:31	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264) ~[commons-dbcp-1.4.jar:1.4]
2016/5/10 下午6:17:31	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264) ~[commons-dbcp-1.4.jar:1.4]
2016/5/10 下午6:17:31	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:294) ~[liquibase-core-3.1.0.jar:na]
2016/5/10 下午6:17:31	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:54) ~[liquibase-core-3.1.0.jar:na]
2016/5/10 下午6:17:31	... 57 common frames omitted
2016/5/10 下午6:17:31Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Specified key was too long; max key length is 1000 bytes
2016/5/10 下午6:17:31	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:475) ~[mariadb-java-client-1.3.4.jar:na]
2016/5/10 下午6:17:31	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.result(AbstractQueryProtocol.java:396) ~[mariadb-java-client-1.3.4.jar:na]
2016/5/10 下午6:17:31	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:378) ~[mariadb-java-client-1.3.4.jar:na]
2016/5/10 下午6:17:31	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:334) ~[mariadb-java-client-1.3.4.jar:na]
2016/5/10 下午6:17:31	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:280) ~[mariadb-java-client-1.3.4.jar:na]
2016/5/10 下午6:17:31	... 62 common frames omitted
2016/5/10 下午6:17:31STARTUP FAILED [7291] ms

help me ，please！

**Comment by rapklein** [comment]
Had the same problem and resolved it by deleting the special characters in the db password. In my case I used to have a `_`-sign. Another user reported the same thing about a `$`-sign in the db password in the rancher forums.

**Comment by HcgRandon** [comment]
Removing special characters fixed this for me. This should be documented somewhere as it recently changed. Special chars worked for a very long time.

**Comment by superseb** [comment]
Just tested again with `_` and `$` but no issues. I can look into if you can share a string with the character you used in it. Or ping me on Rancher Users Slack (https://slack.rancher.io)

**Comment by HcgRandon** [comment]
Make sure to also try with &, %, *, ^ I believe one of these was the culprit. Sadly I overwrote the old password after I got this fixed. I can look around thou. I might have it in a file somewhere

**Comment by shuimqs** [comment]
Now I also have this problem, the database cannot connect, excuse me, later, did you solve it, how did you solve it??
