### ISSUE TITLE
cluster v2: custom cluster registration command is not registering nodes in the cluster

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#32532]
master-90dc82bfc7ff26f3b3f8922595d491cbf8c9d3dd-head

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a rancher on master-head
2. Create a custom cluster and run the registration command on the node
3. No output is seen after the command is run

**Result:**
The registration command should have registered nodes in the cluster

**Other Information:** 

curl command if used with "-k" has registered the node and the cluster has come up active  and the Kubeconfig present in the cluster returns all the nodes in the cluster but the node is stuck in "Waitingfordatasecret"

<img width="400" alt="Screen Shot 2021-05-04 at 8 35 28 AM" src="https://user-images.githubusercontent.com/38144301/117029724-cb9b2d00-acb3-11eb-871b-20b239ab307f.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-90dc82bfc7ff26f3b3f8922595d491cbf8c9d3dd-head
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AWS t3.medium
- Kubernetes version (use `kubectl version`): v1.20.6+rke2r1

**Comment by slickwarren** [comment]
I tried again on master-head (91a6f51) and got the following :
```
      curl -fL https://<IP>/system-agent-install.sh |  sh -s - --server https://<IP> --token <TOKEN>--ca-checksum <CHECKSUM> --etcd --controlplane --worker
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

```

I was able to get the script running by downloading the script first `wget --no-check-certificate`, then installing locally with 
```
./system-agent-install.sh  --server https://<IP> --token <TOKEN>--ca-checksum <CHECKSUM> --etcd --controlplane --worker
```

This allowed the custom node to provision on master-head (91a6f51) 

However on the latest commit (8072008) I get a panic on the system agent
```
root@localhost:~# rancher-system-agent 
INFO[0000] Rancher System Agent version v0.0.1-alpha16 (8cafa67) is starting 
INFO[0000] Using directory /var/lib/rancher/agent/work for work 
INFO[0000] Starting remote watch of plans               
INFO[0000] Starting local watch of plans in /var/lib/rancher/agent/plans 
panic: invalid configuration: no server found for cluster "agent"

goroutine 6 [running]:
github.com/rancher/system-agent/pkg/remoteplan.(*watcher).start(0xc000078300, 0x1727060, 0xc00041a600)
	/go/src/github.com/rancher/system-agent/pkg/remoteplan/watcher.go:44 +0x765
created by github.com/rancher/system-agent/pkg/remoteplan.Watch
	/go/src/github.com/rancher/system-agent/pkg/remoteplan/watcher.go:31 +0xb5
```

**Comment by anupama2501** [comment]
Verified on master-360edaec8f7e236611fdd30e6798874bac267d5b-head
1. Created a custom cluster with 1 node all roles k8s version v1.20.6+rke2r1 
2. Created a custom cluster with 1 node all roles k8s version v1.21.0-alpha2+rke2r1
In the above 2 cases, clusters have come active.
