### ISSUE TITLE
"Edit Cluster" UI nonfunctional for imported k3os clusters

### ISSUE THREAD

**Issue by philomory** [rancher/rancher#32544]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy Rancher 2.5.7 (I used `rancherd`, not sure if that matters)
2. Create a cluster (I registered an existing k3s single-node cluster, not sure if that matters)
3. After the cluster is created, open the Cluster Dashboard for that cluster
4. Click the three-dots menu on the right side (next to "Kubectl File") and select "Edit"
5. You will be at the "Edit cluster" page.
6. Attempt to make changes:
  1. Try adding a description to your cluster
  2. Try adding a new cluster member in the "Member Roles" section
  3. Try adding a new label or annotation in the "Labels and Annotations" section

**Result:**
There is no "save" or "submit" or "apply" button to save your changes. If you navigate away (on the presumption that changes are applied as soon as they are made in the browser) the changes do not actually persist.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.7
- Installation option (single install/HA): HA

**Comment by philomory** [comment]
So, interestingly enough, if you follow these steps with a cluster that hasn't completed registration yet (in other words, a cluster in the "Pending" state), then the "edit cluster" page does have a "Save" button and it is possible to save changes to the cluster annotations, labels, membership, etc.

**Comment by davidcorbin** [comment]
Seeing the same behavior on version 2.5.8 when trying to edit a k3s cluster that's been imported. 

![Screen Shot 2021-05-20 at 1 58 43 PM](https://user-images.githubusercontent.com/5752872/119026823-9a895080-b973-11eb-9418-45cea0b3c30e.png)
Notice, no edit button for labels and annotations.

**Comment by philomory** [comment]
This is not stale.

**Comment by davidcorbin** [comment]
If nobody else has started looking into this, I can get a PR in with a fix later this week.

**Comment by philomory** [comment]
It occurs to me... is 2.6 planning to remove this UI entirely? If so, then I guess I can understand why no one has bothered to fix this. But if not, then it definitely deserves some attention.

**Comment by vincent99** [comment]
There will be no direct access to the old/Ember UI in 2.6, but parts of some pages (including this one) will be IFRAMEd in to the new/dashboard/explorer/Vue UI.

You guys are conflating at least 2 separate issues here.

Labels and Annotations are [intentionally/explicitly not editable](https://github.com/rancher/ui/blob/master/lib/shared/addon/components/cru-cluster/template.hbs#L89) for imported k3s/rke clusters.  Before the cluster has actually registered it isn't known to be k3s/rke yet.  I don't remember why specifically, but also don't know what there is of value for you to edit here and we would need to know exactly why it was disabled before we're going take a PR allowing it.  It has [been that way](https://github.com/rancher/ui/blame/3d13864e53041537f3630e9d9635a3f551083e4f/lib/shared/addon/components/cru-cluster/template.hbs#L122) for as long as "recognizing" the imported cluster type has existed.

The total lack of a "Save" button I don't think anyone can reproduce, and I don't see any obvious code path to cause.  Stupid question but are you scrolled down to the bottom of the page?  (@davidcorbin 's screenshot isn't, and he's only mentioning the labels thing).

**Comment by philomory** [comment]
![image](https://user-images.githubusercontent.com/200123/126231199-03a80452-a7a2-4e2f-95af-969ccea874a5.png)
![image](https://user-images.githubusercontent.com/200123/126231325-3754681a-d12f-49a2-9adb-ccd831328372.png)

**Comment by vincent99** [comment]
There's a 3rd "accordion" of k3s options so something about your particular cluster is probably causing a JS error and stopping rendering there halfway through the page.  Open up the browser dev tools console before clicking edit.  There is never supposed to be an edit screen without a save/cancel button at the bottom.

While they are synced both ways I think, the normal place to apply labels for Fleet would be to the Fleet cluster, which is a different resource.

**Comment by philomory** [comment]
OK, this must be some unique error on this test installation. I'll blow it away and make a new one and see if the problem goes away. That said, there are no errors in the JS console in either Chrome or Firefox when loading the page.

**Comment by philomory** [comment]
This is not stale

**Comment by philomory** [comment]
@vincent99 I'm also realizing that this makes it impossible to update the cluster membership for a k3os cluster. You can't do that from the Fleet UI.
