### ISSUE TITLE
Rancher operator fails to deploy on CIS hardened RKE cluster

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#32547]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create an RKE cluster following the Rancher HA install documentation and the [CIS 1.6 hardening guidelines](https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.5/1.6-hardening-2.5/)
2. Install Rancher Helm chart on the cluster
3. Check status of the deployment in the `rancher-operator-system`

**Result:**
Rancher-Operator in the `rancher-operator-system` namespace fails to successfully deploy due to missing access to  pod security policy

>  Error creating: pods "rancher-operator-79b8c96444-" is forbidden: PodSecurityPolicy: unable to admit pod: []

**Environment information**
- Rancher version: 2.5.7
- Installation option (single install/HA): HA
- RKE Version: 1.2.8
- Kubernetes Version: v1.19.10-rancher1-1

gz#17244

**Comment by janeczku** [comment]
Regression? https://github.com/rancher/rancher/issues/29696

**Comment by sowmyav27** [comment]
On 2.5.4, rancher-operator fails to deploy on the local cluster in a HA setup with BYO valid certs. 
Other related issues - 
- https://github.com/rancher/rancher/issues/32823
- https://github.com/rancher/rancher/issues/32825

**Comment by sowmyav27** [comment]
Closing this issue as deploying rancher on 2.5.8 HA install with the updated docs worked fine - https://github.com/rancher/rancher/issues/32823#issuecomment-852729565
