### ISSUE TITLE
Invalid catalog seems to kill rancher settings and catalog page

### ISSUE THREAD

**Issue by flypenguin** [rancher/rancher#3254]
I added an internal catalog to the rancher settings page. After doing this, the settings page is completely blank, and the Applications/Catalog page returns an error.

* Using Rancher 0.51.
* private catalog: `git@github.com:CognotektGmbH/production-rsas-client.git` (should be first commit)

**Comment by vincent99** [comment]
Apparently we don't have `ssh` packaged in so it can't clone (https://github.com/rancher/rancher/issues/3248).  https://github.com/rancher/rancher-catalog-service/pull/36 should fix the part where it's not running when a clone fails.

**Comment by flypenguin** [comment]
can please somebody help me in getting my catalog and settings page back? :neutral_face:

**Comment by vincent99** [comment]
If you open up the browser console before clicking on settings, is there any error shown after clicking?  Putting in that value breaks the catalog but not settings for me..

Go to http[s]://your-rancher:8080/v1/settings/catalog.url .  If you can copy the activeValue and post it here that might help replicate the settings UI problem;  then click the blue Delete button and Send Request to restore the default value.

**Comment by flypenguin** [comment]
might be a few days until I can give that information, being currently busy trying some other stuff. but I will move back to catalogs in the next days.

**Comment by flypenguin** [comment]
Okay, I have the very same problem now, but now I did _not_ enter a custom rancher catalog. (Actually I didnt enter any settings AFAIR) . My settings page is simply white. Could use some help here.

When I click on settings with the Firefox console open I get this:

![rancher_settings_console](https://cloud.githubusercontent.com/assets/5030694/13002944/ac8fc208-d172-11e5-8ea3-84e4ab58bd00.png)

Ideas?

**Comment by deniseschannon** [comment]
Verified with v0.63.0-rc3

Invalid catalog (tested with a git@github) doesn't break Catalog. I am still able to see the other catalog entries. 

@flypenguin Let us know if you still need help getting back your settings page.

**Comment by flypenguin** [comment]
@deniseschannon first of all thanks for all the help, and sorry for not getting back here. looks good now, didnt try to break it again ;) .
