### ISSUE TITLE
Can't deploy downstream rke2 cluster with multiple nodes 

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32543]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy a downstream cluster with the following configuration (using DO or equivalent)
 * specify 3 pools for the cluster:
    * etcd with 3 nodes
    * controlplane with 1 node
    * worker with 2 nodes
  * use k8s version 1.20.6

**Result:**
* cluster does not come to active state

**Other details that may be helpful:**
these resources are not active yet in the cluster
<img width="434" alt="Screen Shot 2021-05-04 at 6 32 03 PM" src="https://user-images.githubusercontent.com/16691014/117088335-0f6b5200-ad07-11eb-9619-126fc7af36f5.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): msater-head 91a6f51
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE2 on Digital Ocean
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 2vCPU each
- Kubernetes version (use `kubectl version`): 1.20.6+rke2r1

**Comment by sowmyav27** [comment]
Closing it and tracking this here - https://github.com/rancher/rancher/issues/32610

**Comment by sowmyav27** [comment]
Reopening this as on master-head - commit id: `909237a`, this doesnt work

-  DO RKE2 node driver clusters.
- Cluster1 - 1 node all roles + 1 worker node --> Only all roles node comes up in the cluster. Worker node is stuck and cluster is stuck in `Provisioning` state
- Cluster 2 - 1 etcd, 1 cp, 1 worker nodes --> Cluster doesnt come up Active. Stuckin `Reconciling` state
- The nodes are however created in the backed.

**Comment by anupama2501** [comment]
Issue on master-head - commit id: 909237a is seen for custom clusters as well:
1. Custom cluster - 1 node all roles and 1 worker node :  worker node is stuck in ```Waitingfornoderef ``` and the cluster is stuck in provisioning state in the dashboard but the cluster is shown active on ember UI.
2. Custom cluster - 1 node etcd + cp, 1 worker node : all nodes are stuck in ```Waitingfornoderef ``` and the cluster is stuck in ```Provisioning```

**Comment by anupama2501** [comment]
On master-head commit: 909237a
1. Create an rke2 node driver cluster with 3. nodes all roles enabled on all the nodes
2. Cluster is stuck in provisioning state with the pool1 in active state and the other two node pools in ```Nodeconditionsfailed``` state.
3. On ember UI the cluster is active with all the nodes in active state as well.

**Comment by slickwarren** [comment]
on master-head (d7ef41e) I am able to provision a downstream a downstream cluster with dedicated nodes per role using Digital Ocean, which appears to be working as expected. Also tested deploying multi-node clusters with shared roles (i.e.  node with etcd+CP, 2 worker nodes)

related issues: https://github.com/rancher/rancher/issues/32739 ,  https://github.com/rancher/rancher/issues/32741

**Comment by izaac** [comment]
Rancher version: `v2.6 master-head` _55f0bb2_

Can't provision on EC2 with multi-node roles
Single node all roles work but multi node isn't
