### ISSUE TITLE
Internal DNS 

### ISSUE THREAD

**Issue by rlex** [rancher/rancher#3255]
Either i'm blind or there is no such feature... If not, here is feature request: manage not only external dns, but internal as well.
Example: 

```
container.app.prod.dck.zone -> External IP (how it works now)
container.app.prod.int.dck.zone -> Internal IP (managed by rancher's networking daemons)
```

Can be used for debugging/management, for example. Right now, i need to use IPs for accessing some of my containers.

**Comment by vincent99** [comment]
Internal DNS is built-in and doesn't require deploying an external DNS provider stack from the catalog.

If you have `service1` and `service2`, resolving `service2` or `service2.rancher.internal` from `service1` will return the 10.42.x.y IPs of the `service2` containers.

**Comment by rlex** [comment]
>If you have service1 and service2, resolving service2 or service2.rancher.internal from service1 will return the 10.42.x.y IPs of the service2 containers.

But this will not work if i just connect to rancher network with VPN? I have openvpn on one of rancher compute nodes, so i am able to connect to internal, not yet "exposed" ports to verify things.  
i'm asking about "mirror" of zones, with additional subdomain indicated that this is internal zone, pointed to internal network addresses.

**Comment by vincent99** [comment]
Ok, fair enough as a new feature of external-dns.  It's not a mirror though, only services that expose public ports are published to external DNS.  You'd want to publish all of them for internal.

You should be able to make it sorta work today by running something like dnsmasq on the VPN server, pointing the clients resolv.conf to the VPN server, and have dnsmasq send requests to the internal DNS service (169.254.169.250).

**Comment by pedrommone** [comment]
+1 for this feature

**Comment by rlex** [comment]
Thanks for accepting this feature request!
i thought about exporting all containers name -> IP mapping using rancher's API and sending them to same route53 zone i use for external IPs, but i haven't found containers names in API, only IDs.

**Comment by ppiccolo** [comment]
:+1:

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
