### ISSUE TITLE
GKE and EKS, some fields not working fine using rancher go cli

### ISSUE THREAD

**Issue by rawmind0** [rancher/rancher#32553]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Use go client API binding to create a GKEv2 cluster, letting `Cluster.GKEConfig.Labels` empty

**Result:**

Error creating GKEv2 cluster from google api, saying that `Labels` can't be nil creating a cluster

**Other details that may be helpful:**

Checked that gke-operator `Labels` API field is generated with `omitempty` tag set at rancher go cli 
* type [GKEClusterConfigSpec.Labels](https://github.com/rancher/rancher/blob/dbc17a0565e38bb4966c4eea047d5301e414a280/pkg/client/generated/management/v3/zz_generated_gke_cluster_config_spec.go#L40) at rancher generated go cli . `omitempty` tag is set
* type [GKEClusterConfigSpec.Labels](https://github.com/rancher/gke-operator/blob/master/pkg/apis/gke.cattle.io/v1/types.go#L40) at gke-operator API. `omitempty` tag is set

Otherwise, gke-operator`validateCreateRequest` function is generating error if [labels](https://github.com/rancher/gke-operator/blob/master/internal/gke/create.go#L247) is nil

Due to `GKEClusterConfigSpec.Labels` is defined with `omitempty` tag set at rancher go cli, and `gke-operator-validateCreateRequest` function, this field can't be let empty if using Rancher go cli.

**Comment by cmurphy** [comment]
I can't reproduce this with the current provider. I see what I think is a workaround in the terraform provider here:

https://github.com/rancher/terraform-provider-rancher2/blob/3c79846bef90b150e05913e75392f7312de7bdde/rancher2/structure_cluster_gke_config.go#L326-L328

I can reproduce the problem if I omit those lines.

From my perspective this is a perfectly reasonable workaround and it makes the `omitempty` in the Rancher generated client code not a problem. Setting the `Labels` field to something is the right solution and it's what the validator in gke-operator is trying to encourage. Is there any downside to keeping it that way?

**Comment by rawmind0** [comment]
Current terraform provider is patched to make work this feature, but the issue is still there. Basically, the workaround applied is not to use the Rancher go cli for submit EKS/GKE clusters, instead use map[string]interface{}. The patch is not just what you pointed, it's here, https://github.com/rancher/terraform-provider-rancher2/blob/3c79846bef90b150e05913e75392f7312de7bdde/rancher2/resource_rancher2_cluster.go#L133

The workaround works, but using maps instead of proper Rancher go cli object. `omitempty` is still a problem in the Rancher generated client code.

**Comment by cmurphy** [comment]
Same comment as for https://github.com/rancher/rancher/issues/32440#issuecomment-869797213 this is mainly important to the terraform client code.

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 44bb5b4` with the following steps:
- From Rancher dashboard UI, deploy EKSv2 and GKEv2 clusters.
- Make an edit to the clusters (ex: scale the node pool)
- Import EKSv2 and GKEv2 clusters.
- Make an edit to the clusters (ex: scale the node pool)
- Using Terraform Rancher2 provider version `1.16.0`, deploy EKSv2 and GKEv2 clusters.
- Using Terraform, edit the clusters (ex: scale the node pool)

Result:
EKSv2 clusters can be created from Rancher UI, imported from Rancher UI, and created with Terraform Rancher2 provider. Clusters are available in Rancher and EKS console.
EKS operator version `v1.1.1-rc7`. `k8s version v1.20.4`
Edits made from Rancher and Terraform Rancher2 provider are successful and are reflected in Rancher and EKS console. Clusters were provisioned with Terraform using rancher managed launch templates and with preexisting launch templates.

GKEv2 clusters can be created from Rancher UI, imported from Rancher UI, and created with Terraform Rancher2 provider. Clusters are available in Rancher and GKE console.
GKE operator version `v1.1.1-rc8`. `k8s version 1.19.9-gke.1900`
Edits made from Rancher and Terraform Rancher2 provider are successful and are reflected in Rancher and GKE console.
