### ISSUE TITLE
Unable to create GKE Cluster >= 1.19

### ISSUE THREAD

**Issue by SwitchTV-BenBettridge** [rancher/rancher#32566]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):** Attempt to deploy a GKE >= 1.19 cluster using Rancher 2.5.7 (Deployed via helm)

**Result:** Error message: "Basic authentication was removed for GKE cluster versions >= 1.19. The cluster cannot be created with basic authentication enabled. Instructions for choosing an alternative authentication method can be found at: https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication."

**Other details that may be helpful:** I have ensured that "Legacy Authentication" is set to Disabled - which is the default value.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type: Hosted GKE
- Machine type and specifications: Google Cloud (n4-standard)
- Kubernetes version: N/A
- Docker version: N/A

**Comment by intonet** [comment]
hi, The same here.
