### ISSUE TITLE
catalog refresh does not happen on an upgraded rancher setup for over 10 minutes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32560]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On 2.5.7 deployed a couple of downstream clusters. (my case it was couple of windows clusters 3 linux and 3 windows nodes)
- upgraded rancher to 2.5.8-rc9
- Fleet agent did not upgrade (it was over 10 minutes)
- Fleet agent was still in 0.3.4

**Other details that may be helpful:**
After a manual refresh of the chart repo, upgraded the fleet agents on both the clusters

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8-rc19
- Installation option (single install/HA): Single

**Comment by Jono-SUSE-Rancher** [comment]
@sirredbeard - Can you double check and make sure this has nothing to do with the fact that Sowmya was upgrading with the windows clusters/windows nodes? I'm not sure how windows behaves around the fleet agent.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/pull/33234 This could potentially fix the timing issue.

**Comment by sowmyav27** [comment]
**On 2.5.8 to master-head upgrade - commit id: `a11f947`**

The new fleet-agent is deployed only after about 15 minutes after the upgrade. The old fleet agent is removed meanwhile (logged this issue too track it)

But reopening as it takes about 15 minutes for the new fleet-agent `rancher/fleet-agent:v0.3.6-rc2` to get deployed

**Comment by cmurphy** [comment]
I'm not seeing this issue, @sowmyav27 is this still reproducible? Here is what I tried:

1. Installed a 2.5.8 cluster from rancher-stable with helm:

```
$ helm install rancher rancher-stable/rancher --set hostname=429604a2fec0.ngrok.io --namespace=cattle-system --version=v2.5.8
```

2. Registered a downstream "Other cluster"
3. fleet-agent 0.3.5 is installed in the fleet-system namespace
![image](https://user-images.githubusercontent.com/1220710/125887671-64f4d034-4f54-4b7e-bcc6-7555d8da0dce.png)

4. Built rancher chart from 1b81a0615ddef614e41c8ca53ccb309c447ac350 and upgraded to it:

```
helm upgrade rancher ~/dev/rancher/build/chart/rancher --namespace=cattle-system  --set hostname=429604a2fec0.ngrok.io --set rancherImageTag=master-head
```
5. fleet-agent on downstream cluster is installed in the cattle-fleet-system namespace shortly after cattle-cluster-agent finishes upgrading
![image](https://user-images.githubusercontent.com/1220710/125888206-088e7348-81bd-406a-842b-d03e85061529.png)

The old one is still there, which could be a problem, but the new one is there too.

**Comment by sowmyav27** [comment]
**On upgrade 2.5.8 to master-head commit id: `d3ad5d3`**

- On 2.5.9 deployed a couple of downstream clusters. Azure/AWS/AKS clusters
- upgraded rancher to master
- New Fleet agent is deployed. - `0.3.6-rc5`
- Old fleet agent got deleted from Local and downstream clusters.

Closing this issue for now and will reopen or log one later if seen again
