### ISSUE TITLE
rancher 2.5.7 in v1.20.6+k3s1 promethues oom 

### ISSUE THREAD

**Issue by ReigenDing** [rancher/rancher#32571]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

cluster: v1.20.6+k3s1 
DB: embedded etcd
runtime: containerd 1.4.4-k3s  
os: RHEL 7.4 (3.10.0-693.el7.x86_64).

init command:  curl -sfL https://get.k3s.io | sh -s -- server  --cluster-init --data-dir /app/rancher/k3s
join cluster command: K3S_URL=https://domains:6443 K3S_TOKEN=****************  curl -sfL https://get.k3s.io | sh -s -- server --data-dir /app/rancher/k3s.

then click "Rancher Explorer"  and  "apps & Marketplace" install Monitoring from helm chart https://git.rancher.io/charts 

**Result:**
cause promethues OOM keep restarting
 
![image](https://user-images.githubusercontent.com/37658394/117272976-46b83b00-ae8e-11eb-9ee4-69a054886e2e.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
-  rancher image docker.io/rancher/rancher                                              v2.5.7                   3ea53a0e3b904       366MB
![image](https://user-images.githubusercontent.com/37658394/117273997-3bb1da80-ae8f-11eb-9c7c-edb13e8cd5bb.png)

- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):
- 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+k3s1", GitCommit:"8d0432824a9fd9474b67138b7630c33f285d332f", GitTreeState:"clean", BuildDate:"2021-04-16T19:04:44Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+k3s1", GitCommit:"8d0432824a9fd9474b67138b7630c33f285d332f", GitTreeState:"clean", BuildDate:"2021-04-16T19:04:44Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}


(paste the output here)
```

- containerde version (use `crictl version`):

```
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.4.4-k3s1
RuntimeApiVersion:  v1alpha2
(paste the output here)
```

**Comment by fad3t** [comment]
Same here, memory usage of the prometheus container is incredibly high.
![image](https://user-images.githubusercontent.com/43849398/126347874-18b227a4-b4f2-402b-9d7a-b2ba6d188b76.png)
I'm using monitoring chart 14.5.100 on top of RKE (3 master, 3 worker). Scrape interval is set to 1m.

Any idea how to reduce the memory usage?
