### ISSUE TITLE
AKSv2: convert static info to dynamic api proxy calls

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32587]
This includes: 
* Resource groups (cluster list)
* VM list
* location list

**Comment by prabalsharma** [comment]
There is no RG list. Its a txt field 
Cluster list for imports is dynamic
@cbron what is VM list? Do you mean VNET list?
Location list is dynamic

**Comment by prabalsharma** [comment]
I got confirmation that its only Cluster List not RG. Closing this now.
