### ISSUE TITLE
GKE/AKS Windows compatability

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32586]
See if: 
a) we can easily create clusters with Windows nodes
b) if your features deploy correctly on them. I am assuming there will be problems with taints and tolerations.

**Comment by cmurphy** [comment]
Additional fields were needed in the spec in order to create Windows nodes https://github.com/rancher/aks-operator/pull/5

Besides that, AKS requires at least one node pool to be a "System" type and "System" node pools are Linux-only, similar to the way GKE requires at least one non-windows node pool. So there's not an issue with taints, and actually none of the nodes in any node pools seem to have any taints. The cluster agent gets deployed successfully and the cluster explorer comes up fine.

**Comment by prabalsharma** [comment]
tested on aks operator rc4
> See if:
> a) we can easily create clusters with Windows nodes
Works
> b) if your features deploy correctly on them. I am assuming there will be problems with taints and tolerations.

monitoring v2 installs fine. However, when I go to Grafana, **the monitoring data is populated only for linux nodes** (not windows nodes)

**Comment by cmurphy** [comment]
Update: I haven't entirely gotten it to work yet, but I think it /should/ work without needing any changes in aks-operator.

What I've done so far:
1. followed [this guide](https://docs.microsoft.com/en-us/azure/aks/rdp) to set up an RDP connection to the windows nodes in the cluster (the `az` commands did not work, but you can reproduce most of it via the web UI).
2. installed [wins](https://github.com/rancher/wins) on the nodes. 
3. installed the monitoring chart through Rancher, setting `global.windows.enabled=true` in `values.yaml`. For some reason this never seems to take on the first install, I have to go upgrade it and change it again.
4. Eventually you should see a healthy `rancher-monitoring-windows-exporter` daemonset running on the nodes using the `kubernetes.io/os=windows` selector.

At that point things seem to look fine but there are still no metrics in grafana for those nodes. In the Prometheus "Targets" UI I see the error "Get "http://10.42.0.112:9796/metrics": context deadline exceeded" for the `cattle-monitoring-system/rancher-monitoring-windows-exporter/0 (0/2 up)` target, so I think it's something wrong with the VNet or something wrong with how I'm running wins.exe.

**Comment by cbron** [comment]
Hmm. We should talk about this on Monday. Don't think you need to put any more work on it for now. It's mostly a question of what Rancher typically does for windows nodes, and how to align expectations with that. But that last part about VNet we may need to dive into at some point.

**Comment by cbron** [comment]
@prabalsharma can you test fleet and logging on mixed node GKE and AKS clusters, we think those will work by default, though you might have to enable the `global.cattle.windows.enabled` flag. 
Monitoring I don't think will work on either. But can you also test that and open up a bug issue if it doesn't work. We can use this issue solely for whats going live in 2.6.

**Comment by cmurphy** [comment]
For posterity, one other thing I tried for monitoring was to add an inbound and outbound rule for port 9796 to the security group for the vnet the node pool is in. Should also note that that IP address `10.42.0.112` is the IP address of the windows exporter pod and is in the same subnet as the node range.

**Comment by cmurphy** [comment]
https://github.com/rancher/aks-operator/pull/17 and https://github.com/rancher/rancher/pull/32869 are merged so it should now not be possible to create node pools with os type "Windows".

**Comment by prabalsharma** [comment]
I don't see a UI card for this. I cannot create Windows NPs using Rancher UI, yet.

**Comment by prabalsharma** [comment]
tested on master-3d465ee
Added to https://github.com/rancher/rancher/issues/33183
