### ISSUE TITLE
[v2.4] KDM release: k8s may patches

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#32584]
### **Kubernetes Updates:**
This is a KDM release for new k8s versions: `v1.18.19`. It's not going out with any Rancher release, it's a KDM + RKE release only.

| New k8s versions | Rancher versions | 
| --- | --- | 
|`v1.18.19-rancher1-1` | 2.4.5+ | 

### **Rancher updates:**
- `rke-tools` is updated to `v0.1.75`

### **Developer changelog:** 
- All existing `v1.18.x` versions in dev-v2.4 need to be released or have been released (are present in release-v2.4) so we need to introduce new k8s version. To introduce a new k8s version, basecopy the latest existing version in a separate commit, followed by another commit to update what's changed. Following versions need to be created with their compatible rancher server versions:

| basecopy [version](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/k8s_rke_system_images.go#L3590) from | create | set [rancher version constraints]( https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/rke/k8s_version_info.go#L278) 
| --------------- | --------------- | -----------| 
| v1.18.18-rancher1-1 | v1.18.19-rancher1-1 | 2.4.5+ |

**Comment by kinarashah** [comment]
Available to test with `dev-v2.4` KDM and RKE `v1.1.18-rc1`, Drone link: https://drone-publish.rancher.io/rancher/rke/993

**Comment by sowmyav27** [comment]
- RKE checks on `v1.1.18-rc1` for `v1.18.19-rancher1-1` version look good.
- Min checks for `2.4.5` pointing to dev-v2.4 for `v1.18.19-rancher1-1` version look good. Deployed clusters with all network provider and network related checks passed.

**Comment by aaronRancher** [comment]
- Validated fresh install checks on Rancher v2.4.15 with KDM pointing to `dev-v2.4`. Cluster creation succeeds for `v1.18.19-rancher1-1` with all network providers. Network validation checks have passed.
- Validated upgrade install checks on Rancher v2.4.15 with KDM pointing to `release-v2.4`. Cluster creation succeeds for `v1.18.18-rancher1-1` with all network providers. Pointed KDM to `dev-v2.4` and upgraded all clusters to `v1.18.19-rancher1-1`. Post-upgrade network validation checks have passed.
