### ISSUE TITLE
Api view not loading on air-gapped network.

### ISSUE THREAD

**Issue by clemenko** [rancher/rancher#3258]
When deploying Rancher on an air gapped network the "view in api" links load a blank page. Upon source inspection the page is trying to load a css sheet from https://release.rancher.com/api-ui/1.0.4./ui.min.css. And it is also trying to load a js script from https://release.rancher.com/api-ui/1.0.4./ui.min.js

Can this be bundled into the server itself so it will work on a air gapped network?

**Comment by vincent99** [comment]
It can but is more involved because other CSS/fonts/etc from public CDNs are also loaded and need to be bundled.

**Comment by clemenko** [comment]
Is there anyway to bundle the CSS/fonts/etc?

**Comment by vincent99** [comment]
In API-UI 1.0.6, needs integration into cattle.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.2.0-pre1-rc3
"view in api" loads properly  on rancher-server deployed in air-gapped network.
