### ISSUE TITLE
Add username at login to Rancher API Audit log at metadata (level 1)

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#32588]
Rancher API Audit log have been enhanced by this fix https://github.com/rancher/rancher/issues/31166 to log username and principalid data for the authenticated user for every request that gets logged at Metadata level (audit log level=1).

This is the "extra" that is logged for an authenticated user with above fix:
"extra":{"principalid":["openldap_user://uid=testuser1,ou=dev,dc=us-west-2,dc=compute,dc=internal"],"username":["testuser1"]}}

But when there is a login  failure,  there is no username logged at Metadata level, since there is no authenticated user entity present. (If the Audit level is set to 2 and above, entire request body is logged, but it is beneficial to log the username at Metadata level so that service providers can track login failures easily)

This enhancement is to log `extra.username` in the Rancher API audit logs at Metadata level for a Login request - the username field of the login form is read and logged in the Rancher API audit log.

This is supported only for authproviders which work with a username/password form of login like AD,LDAP, local. For other token/SAML based providers there will be no username logged for login resuests at Metadata level.

gz#7326

**Comment by prachidamle** [comment]
This is how the extra.username gets added to Rancher API audit log at level 1

{"auditID":"0d9bf2c1-831b-4ef5-a788-d6a16e00c280","requestURI":"/v3-public/openLdapProviders/openldap?action=login","user":{"name":"system:cattle:error","group":["system:unauthenticated","system:cattle:error"],"extra":{"username":["testuser1"]}},"method":"POST","remoteAddr":"172.31.36.137:40670","requestTimestamp":"2021-05-06T23:58:41Z","responseTimestamp":"2021-05-06T23:58:41Z","responseCode":401,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Content-Length":["140"],"Content-Type":["application/json"],"Origin":["https://ec2-3-137-201-13.us-east-2.compute.amazonaws.com"],"Referer":["https://ec2-3-137-201-13.us-east-2.compute.amazonaws.com/login"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"],"X-Api-Action-Links":["actionLinks"],"X-Api-Csrf":["b48c1e9c74"],"X-Api-No-Challenge":["true"],"X-Forwarded-For":["108.221.20.194"],"X-Forwarded-Host":["ec2-3-137-201-13.us-east-2.compute.amazonaws.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["108.221.20.194"],"X-Request-Id":["9692ad2fee70dea1088afebba64df50e"],"X-Scheme":["https"]},"responseHeader":{"Content-Type":["application/json"],"Expires":["Wed 24 Feb 1982 18:42:00 GMT"],"X-Api-Schemas":["https://ec2-3-137-201-13.us-east-2.compute.amazonaws.com/v3-public/schemas"],"X-Content-Type-Options":["nosniff"]},"userloginName":"testuser1","requestBody":{"username":"testuser1","password":"qqqqq","description":"UI Session","responseType":"cookie","ttl":57600000,"labels":{"ui-session":"true"}}}

**Comment by anupama2501** [comment]
Verified the following on master-head commit: 5d2b7ac

- Enabled auditlogging while bringing up a rancher server 
- Enabled auth openLDAP auth and logged in as admin user - u1 
- Login as admin and verified the login details are audited
- Provided incorrect login details and the login failure has been recorded in the audit logs with the username

**For failed login:**
```
,"requestURI":"/v3-public/openLdapProviders/openldap?action=login","user":{"name":"system:cattle:error","group":["system:unauthenticated","system:cattle:error"]},
```
```
"requestURI":"/v3-public/azureADProviders/azuread?action=login","user":{"name":"system:cattle:error","group":["system:unauthenticated","system:cattle:error"]},"method":"POST",
```

**For successful login:**

```
//5e0d1316-aa15-4c94-83e1-7db91acc7795","azuread_group://748274fd-3ec7-40d1-b08b-775c1a8ec1af","azuread_group://fbfa2921-0088-4c1d-a92b-569feff96ac2","azuread_group://***","azuread_group://***","openldap_group://","system:authenticated","system:cattle:authenticated"],
```

On cluster level login successful authentication:
```
"groups":["system:serviceaccounts","system:serviceaccounts:cattle-system","system:authenticated"]},"impersonatedUser":{"username":"user-hvw46","groups":["okta_group://Everyone","okta_group://","system:authenticated","system:cattle:authenticated"
```

**Comment by anupama2501** [comment]
Rancher | master-4f9850d2ae920b4350b5312fd53c045aa7e7a0c4-head 
@axeal @prachidamle  I tried this on the 

I see the extra field logged if the login action is through ember UI. However if I try to login from dashboard UI, I see that its not getting logged. As both the UI are using v3 api this shouldn't have been any different. 

Thank you for pointing it out.

**Failed login on ember UI**

`{"auditID":"e58c7ae6-56fd-4530-823a-76b8c74e235a","requestURI":"/v3-public/openLdapProviders/openldap?action=login","user":{"name":"system:cattle:error","group":["system:unauthenticated","system:cattle:error"],"extra":{"username":["abcdjjej"]}},"method":"POST","remoteAddr":"xxx:61279","requestTimestamp":"2021-05-21T15:25:23Z","responseTimestamp":"2021-05-21T15:25:23Z","responseCode":422,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Connection":["keep-alive"],"Content-Length":["134"],"Content-Type":["application/json"],"Origin":["https://xxx"],"Referer":["https://xxx/login"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"],"X-Api-Action-Links":["actionLinks"],"X-Api-Csrf":["0ad7a96e89"],"X-Api-No-Challenge":["true"]},"responseHeader":{"Content-Type":["application/json"],"Expires":["Wed 24 Feb 1982 18:42:00 GMT"],"X-Api-Schemas":["https://xxx/v3-public/schemas"],"X-Content-Type-Options":["nosniff"]},**"userLoginName":"abcdjjej"**}`

**successful login using local on ember UI**

`{"auditID":"8b360a97-a988-4eba-bf8e-9ce0a5921c57","requestURI":"/v3-public/localProviders/local?action=login","user":{"name":"system:cattle:error","group":["system:unauthenticated","system:cattle:error"],"extra":{"username":["user333"]}},"method":"POST","remoteAddr":"73.202.240.53:61176","requestTimestamp":"2021-05-21T15:29:42Z","responseTimestamp":"2021-05-21T15:29:42Z","responseCode":200,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Connection":["keep-alive"],"Content-Length":["143"],"Content-Type":["application/json"],"Origin":["https://23.239.20.61"],"Referer":["https://23.239.20.61/login"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"],"X-Api-Action-Links":["actionLinks"],"X-Api-Csrf":["0d1e7fafb3"],"X-Api-No-Challenge":["true"]},"responseHeader":{"X-Content-Type-Options":["nosniff"]},"userLoginName":"user333"}
{"auditID":"915da1c2-d0c4-496e-b2a0-90ba0524ef58","requestURI":"/v3/users?me=true","user":{"name":"u-tjlpk","group":["system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["local://u-tjlpk"],"username":["user333"]}},"method":"GET","remoteAddr":"73.202.240.53:61176","requestTimestamp":"2021-05-21T15:29:42Z","responseTimestamp":"2021-05-21T15:29:42Z","responseCode":200,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Connection":["keep-alive"],"Content-Type":["application/json"],"Impersonate-Extra-Principalid":["local://u-tjlpk"],"Impersonate-Extra-Username":["user333"],"Impersonate-Group":["system:authenticated","system:cattle:authenticated"],"Impersonate-User":["u-tjlpk"],"Referer":["https://23.239.20.61/login"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"],"X-Api-Action-Links":["actionLinks"],"X-Api-Csrf":["0d1e7fafb3"],"X-Api-No-Challenge":["true"]},"responseHeader":{"Content-Encoding":["gzip"],"Content-Type":["application/json"],"Expires":["Wed 24 Feb 1982 18:42:00 GMT"],"X-Api-Schemas":["https://23.239.20.61/v3/schemas"],"X-Content-Type-Options":["nosniff"]}}
`


**Failed login on dashboard** 
`
{"auditID":"b1162cf4-5f49-4f44-bfe0-06965c52b67c","requestURI":"/v3-public/openLdapProviders/openldap?action=login","user":{"name":"system:cattle:error","group":["system:unauthenticated","system:cattle:error"]},"method":"POST","remoteAddr":"xxx:65404","requestTimestamp":"2021-05-21T15:36:34Z","responseTimestamp":"2021-05-21T15:36:34Z","responseCode":422,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Connection":["keep-alive"],"Content-Length":["87"],"Content-Type":["application/json;charset=UTF-8"],"Origin":["https://23.239.20.61"],"Referer":["https://xxx/dashboard/auth/login?timed-out"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"],"X-Api-Csrf":["31164124a8"]},"responseHeader":{"Content-Type":["application/json"],"Expires":["Wed 24 Feb 1982 18:42:00 GMT"],"X-Api-Schemas":["https://xxx/v3-public/schemas"],"X-Content-Type-Options":["nosniff"]}}
`

**Comment by anupama2501** [comment]
Verified on master-head f90b36e

Validated the following scenarios:

1. first-login as admin from cluster explorer new UI - valid credentials
```
{"auditID":"9002493a-c492-4031-92fa-16ae3e2e5347","requestURI":"/v1/management.cattle.io.settings/first-login",
"user":{"name":"user-4xrqk","group":["system:authenticated","system:cattle:authenticated"],

> "extra":{"principalid":["local://user-4xrqk"],"username":["admin"]}}
"method":"PUT","requestTimestamp":"2021-05-25T18:18:48Z","responseTimestamp":"2021-05-25T18:18:49Z",

> "responseCode":200,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Connection":["keep-alive"],"Content-Length":["1030"],"Content-Type":["application/json"],"Origin":["https://"],"Referer":["https://**/dashboard/auth/setup"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"],""responseHeader":{"Content-Encoding":["gzip"],"Content-Type":["application/json"],"Expires":["Wed 24 Feb 1982 18:42:00 GMT"],"X-Api-Cattle-Auth":["true"],"X-Api-Schemas":["https://*/v1/schemas"],"X-Content-Type-Options":["nosniff"]}

,"userLoginName":"admin"}
```
2. Enabled auth provider openLDAP - logged out and logged in as openLDAP user valid credentials:
```
{"auditID":"54adb4f8-b731-46db-ba0d-56fb0b9bdf9a","requestURI":"/v3-public/openLdapProviders/openldap?action=login","user":{"name":"system:cattle:error","group":["system:unauthenticated","system:cattle:error"],

> "extra":{"username":["testuser1"]}},
"method":"POST","remoteAddr":":56607","requestTimestamp":"2021-05-25T18:23:36Z","responseTimestamp":"2021-05-25T18:23:36Z",

> "responseCode":200,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Connection":["keep-alive"],"Content-Length":["98"],"Content-Type":["application/json;charset=UTF-8"],"Origin":["https://"],"Referer":["https:///dashboard/auth/login?logged-out"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"],"X-Api-Csrf":["5d3c310a06"]},"responseHeader":{"X-Api-Cattle-Auth":["false"],"X-Content-Type-Options":["nosniff"]},

"userLoginName":"testuser1"}


```

3. Auth provider - logged in with invalid credentials:
```
{"auditID":"2ec53070-ce39-4017-b199-7f8718c3f607","requestURI":"/v3-public/openLdapProviders/openldap?action=login","user":{"name":"system:cattle:error","group":["system:unauthenticated","system:cattle:error"],

> "extra":{"username":["testuser333"]}},
"method":"POST","remoteAddr":":57097","requestTimestamp":"2021-05-25T18:26:21Z","responseTimestamp":"2021-05-25T18:26:21Z",

> "responseCode":422,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Connection":["keep-alive"],"Content-Length":["139"],"Content-Type":["application/json"],"Origin":["https://"],"Referer":["https:///login"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"],"X-Api-Action-Links":["actionLinks"],"X-Api-Csrf":["9a2fda205b"],"X-Api-No-Challenge":["true"]},"responseHeader":{"Content-Type":["application/json"],"Expires":["Wed 24 Feb 1982 18:42:00 GMT"],"X-Api-Cattle-Auth":["false"],"X-Api-Schemas":["https:///v3-public/schemas"],"X-Content-Type-Options":["nosniff"]},

"userLoginName":"testuser333"}

```

4. Local user - Logged in with invalid credentials:
```
{"auditID":"3fc1c86d-5ca7-4c6a-8dff-eb4866c98aff","requestURI":"/v3-public/localProviders/local?action=login","user":{"name":"system:cattle:error","group":["system:unauthenticated","system:cattle:error"],

> "extra":{"username":["admin"]}},
"method":"POST","remoteAddr":":54548","requestTimestamp":"2021-05-25T19:13:59Z","responseTimestamp":"2021-05-25T19:13:59Z",

> "responseCode":401,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Connection":["keep-alive"],"Content-Length":["90"],"Content-Type":["application/json;charset=UTF-8"],"Origin":["https://"],"Referer":["https:///dashboard/auth/login?logged-out\u0026local"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"],"X-Api-Csrf":["69af974f10"]},"responseHeader":{"Content-Type":["application/json"],"Expires":["Wed 24 Feb 1982 18:42:00 GMT"],"X-Api-Cattle-Auth":["false"],"X-Api-Schemas":["https:///v3-public/schemas"],"X-Content-Type-Options":["nosniff"]},"userLoginName":"admin"}

```

5. Logged in as local standard user - valid credentials:
```
{"auditID":"a6970756-beec-48dd-a0c5-45f27883d6a8","requestURI":"/v3-public/localProviders/local?action=login","user":{"name":"system:cattle:error","group":["system:unauthenticated","system:cattle:error"],

> "extra":{"username":["user2"]}},
"method":"POST","remoteAddr":":56666","requestTimestamp":"2021-05-25T19:22:39Z","responseTimestamp":"2021-05-25T19:22:39Z",

> "responseCode":200,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Connection":["keep-alive"],"Content-Length":["94"],"Content-Type":["application/json;charset=UTF-8"],"Origin":["https://"],"Referer":["https:///dashboard/auth/login?logged-out\u0026local"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"],"X-Api-Csrf":["3f6bd982f3"]},"responseHeader":{"X-Api-Cattle-Auth":["false"],"X-Content-Type-Options":["nosniff"]},

"userLoginName":"user2"}

```
