### ISSUE TITLE
Operation cannot be fulfilled on apps.project.cattle.io "rancher-eks-operator"

### ISSUE THREAD

**Issue by mayconfsbrito** [rancher/rancher#32592]
Suddenly at the morning, I've opened my Rancher and all my clusters are displaying this message:

_Failed to deploy eks-operator: Operation cannot be fulfilled on apps.project.cattle.io "rancher-eks-operator": the object has been modified; please apply your changes to the latest version and try again_

We really didn't any direct intervention in Rancher or in the RKE cluster where it installed.

All clusters are working normally, but I made a test removing and adding one of these clusters again and all workloads can be shown in Rancher (even namespaces).

How can I fix that?

<br class="Apple-interchange-newline">

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.7` UI: `v2.5.7` |
|Route|`undefined`|

**Comment by oxr463** [comment]
@mayconfsbrito why do the versions not match? If you install Rancher v2.5.7 via helm, then it should also say v2.5.7 in the UI.

**Comment by mayconfsbrito** [comment]
Yes, it was v2.5.7.
I mean, it was because I fixed removing every cluster and connecting again to rancher.
Also I needed to move all my projects/namespaces again.

**Comment by oxr463** [comment]
> Yes, it was v2.5.7.
> I mean, it was because I fixed removing every cluster and connecting again to rancher.
> Also I needed to move all my projects/namespaces again.

That is what I ended up doing as well.
