### ISSUE TITLE
External DNS - support for suffixes

### ISSUE THREAD

**Issue by AirbornePorcine** [rancher/rancher#3259]
It would be great for us if the external DNS service would support adding a suffix after the standard <serviceName>.<stackName>.<environmentName>

eg. myservice.mystack.env.mysuffix.anothersuffix.domain.com

This would help Rancher's external DNS structure fit better with pre-established DNS structures.

**Comment by vincent99** [comment]
The DNS services create records for `<service>.<stack>.<environment>.<base>`.  The `<base>` (which is called different "root domain", "hosted zone", etc depending on the provider) can be whatever you want, like `mysuffix.anothersuffix.domain.com`.  Or are you saying you want those suffixes to somehow vary depending on the service/stack/environment?

**Comment by AirbornePorcine** [comment]
Well, specifically the problem is with Route53. My hosted zone name has to be domain.com as I understand it, because you can't create a hosted zone for a subdomain. Do correct me if I'm wrong there, but that's the reason why I'd need the suffix separate - so I can still enter domain.com in the configuration for Route53 DNS on Rancher (so it will talk to the correct hosted zone on AWS).

**Comment by deniseschannon** [comment]
@AirbornePorcine It seems like you could create a hosted zone for a subdomain? At least that's what I think I"m reading when I google. 

http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingNewSubdomain.html

**Comment by AirbornePorcine** [comment]
Thanks, you're 100% correct - my bad.
