### ISSUE TITLE
[UI] [AKS] Use new proxy calls to get regions and VM sizes

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#32594]
Currently, the UI has hard-coded regions and VM sizes. There will be new proxy calls in Rancher to get these items from the Azure API.

- Get Regions -- `/meta/aksRegions`
- Get VM sizes -- `/meta/aksVMSizes`

Dependent on https://github.com/rancher/rancher/issues/32587

**Comment by prabalsharma** [comment]
both locations and VM sizes are dynamic

**Comment by gaktive** [comment]
This was marked Done in Zube but that didn't translate to Github. Done!
