### ISSUE TITLE
[Forwardport] Setting MaxPodsConstraint for GKE operator fails

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32597]
https://github.com/rancher/rancher/issues/32585

**Comment by prabalsharma** [comment]
https://github.com/rancher/rancher/issues/32585#issuecomment-849170163

**Comment by prabalsharma** [comment]
tested on 21ab02c

Looks good 

<img width="1193" alt="Screen Shot 2021-07-28 at 3 27 56 PM" src="https://user-images.githubusercontent.com/3749546/127404339-9f1464d2-681d-4f26-a8ea-8b16551a6dc2.png">

**Comment by gaktive** [comment]
This was marked done in Zube but not in Github.
