### ISSUE TITLE
Cluster Provisioning v2: Support Rancher Rollback/Downgrade (Rancher app)

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#32598]
RKE2 needs to support both the Rancher application and etcd backup scenarios:

- Backup/Restore of the Rancher application - This only affects the resources defined in the Rancher application resource set.

- etcd backup/restore of the management/local RKE cluster - This only affects the management/local cluster, but not the resources in the downstream clusters.

**Comment by snasovich** [comment]
@Jono-SUSE-Rancher , is this to support base Rancher backup/restore when it's installed on RKE2 (without any downstream clusters)? I would think it's already supported by existing backup/restore configuration as it's unlikely to be affected by which type of k8s cluster Rancher is deployed to. Could you please clarify?

**Comment by deniseschannon** [comment]
This is to support being able to use backup/restore and expect the new clusters to be backed up and restored.

Use cases include:
Backup and restore Rancher with newly provisioned RKE2 and RKE1 clusters - Migrate Rancher 2.6 from 1 k8s cluster to another with a couple of downstream clusters
Backup 2.5 and upgrade to 2.6 and then restore Rancher to 2.5 state
Start with 2.5, upgrade to 2.6 add more clusters, backup and then restore to 2.6 on a different k8s cluster

**Comment by StrongMonkey** [comment]
> Backup 2.5 and upgrade to 2.6 and then restore Rancher to 2.5 state

At this point, cluster-agent on downstream cluster has already been upgraded to 2.6 version. If we are going to support this use case, we might have to deal issues that came with downstream cluster too during restore.

**Comment by sowmyav27** [comment]
**On 2.6.0-rc8**

Verified these usecases
using backup restore latest charts verified
- Upgrade from 2.5.9 to 2.6.0-rc8 and rollback to 2.5.9 in same cluster
- Upgrade from 2.5.9 to 2.6.0-rc8 and rollback to 2.5.9 in a new RKE1 local cluster
- Upgrade from 2.5.9 to 2.6.0-rc8 and take backup b1. Deploy RKE2 cluster. Restore to b1
- Backup and restore in 2.6.0-rc8
