### ISSUE TITLE
[2.5] Backport Kubernetes component status filter

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#32607]
https://github.com/rancher/rancher/issues/11496

The changes from this pr need to be backported to 2.5: https://github.com/rancher/rancher/pull/32277

**Comment by deniseschannon** [comment]
@paynejacob please make sure this is resolved for imported clusters and newly provisioned AKS clusters.

**Comment by slickwarren** [comment]
closing as dupe of https://github.com/rancher/rancher/issues/32905
