### ISSUE TITLE
[backport] gke and eks operators api *string type doesn't match at generated rancher go cli

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32609]
https://github.com/rancher/rancher/issues/32440

**Comment by aaronRancher** [comment]
GKEv2 provisioning on v2.5.10 is currently blocked by: https://github.com/rancher/rancher/issues/33721

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5-head` `version 500de20` with the following steps:
- From Rancher dashboard UI, deploy EKSv2 and GKEv2 clusters.
- Using Terraform Rancher2 provider version `1.16.0`, deploy EKSv2 and GKEv2 clusters.

Result:
- EKSv2 cluster becomes available in Rancher and EKS console. User is able to provision clusters through Rancher UI and Terraform Rancher2 provider. EKS operator version `v1.0.10-rc1`. k8s version `v1.20.7-eks-8be107`
- GKEv2 cluster becomes available in Rancher and GKE console. User is able to provision clusters through Rancher UI and Terraform Rancher2 provider. GKE operator version `v1.1.1-rc7`. k8s version `v1.19.9-gke.1900`
