### ISSUE TITLE
Long stack name moves the upgrade button, should wrap

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#3260]
![image](https://cloud.githubusercontent.com/assets/753917/12302310/c7dd1a22-b9e1-11e5-8461-777f3af49ced.png)

**Comment by sshipway** [comment]
Same problem happens with a very long Stack description, causing incorrect wrapping similar to above

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/520

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed
