### ISSUE TITLE
[Backport] ingress-nginx in Prometheus Targets of a cluster are down when port 10254 is not open monitoring v2 is enabled 

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32606]
https://github.com/rancher/rancher/issues/32563

**Comment by sowmyav27** [comment]
On 2.5-head commit id: `0e5876`

- Deploy an AWS node driver cluster with rancher-nodes
- SG in the instances are

<img width="694" alt="Screen Shot 2021-07-23 at 10 27 15 PM" src="https://user-images.githubusercontent.com/26032343/126858416-38589b04-0821-4996-ba28-62462caa6b00.png">

- Enable Monitoring v2 set `rkeIngressNginx: enabled=true`
- ingress-nginx are up and Active
