### ISSUE TITLE
Cluster explorer fails to come up on a cluster right after it comes up Active for ~2-3 minutes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32612]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster from Ember UI (DO RKE 1 node)
- Wait for the cluster to come up Active
- All the workloads in System project will come up Active.
- Access Cluster explorer
- 500 internal server error is seen
- This happens for ~2-3 minutes and after that, user is able to access the cluster explorer consistently.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `360edae `
- Installation option (single install/HA): Single

**Comment by Jono-SUSE-Rancher** [comment]
Yes, this is a known issue - Cluster Explorer won't be ready until your API server is ready. Now that RKE1 cluster provisioning is embedded into cluster explorer, what happens? Can you retest?

**Comment by sowmyav27** [comment]
This happens even after the cluster comes up Active. Happens when rke1/rke2 clusters.

**Comment by deniseschannon** [comment]
There is nothing the front end or backend can do as we are waiting for the API server of k8s to start up which can vary even if the clsuter is active. 

This is a won't fix.

**Comment by sowmyav27** [comment]
Closing based on https://github.com/rancher/rancher/issues/32612#issuecomment-880191725

**Comment by deniseschannon** [comment]
"Active" doesn't mean the api-server is up and running yet
