### ISSUE TITLE
Downstream AKS cluster always using `kubenet`

### ISSUE THREAD

**Issue by valeriano-manassero** [rancher/rancher#32616]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- enter in Rancher UI
- add a new AKS downstream cluster setting `Azure CNI` in advanced tab

**Result:**
resulting AKS is using `kubenet` CNI ignoring the setup done by the Rancher UI

**Environment information**
- Rancher version 2.5.8
- Installation option (single install/HA): HA

**DOWNSTREAM Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AKS agentpool with D8s_v3 machines
- Kubernetes version: tested creating 1.19 and 1.20 AKS clusters

**Comment by valeriano-manassero** [comment]
Issue is still there.

**Comment by valeriano-manassero** [comment]
issue still there

**Comment by valeriano-manassero** [comment]
Issue still there 🤔

**Comment by superseb** [comment]
@valeriano-manassero I tested this using v2.5.11 and the AKS cluster got created with Azure CNI. Can you share a bit more specifics on the values you are using when creating the cluster? Did you check https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni for possible limitations? Can you capture the web request made when creating the cluster to see if the value is properly passed?

**Comment by valeriano-manassero** [comment]
Hi @superseb , I tested after upgrading Rancher to v2.5.11 and I'm not able to reproduce the issue anymore so it's a good news. For me it's fixed.
