### ISSUE TITLE
[rancher alerting drivers] Need a Logo for the helm chart 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#32624]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

We need a logo for the helm chart.  
The logo shows in the Chart list in the Cluster Explorer UI.

**Comment by lvuch** [comment]
@jiaqiluo I will slack you the svg as gh does not support it

**Comment by jiaqiluo** [comment]
A logo should shows in the UI for rancher-alerting-driver 100.0.0

**Comment by jiaqiluo** [comment]
Here is the logo file: https://github.com/rancher/charts/blob/dev-v2.6/assets/logos/alerting-drivers.svg
But it will not show in the UI until the charts are merged into to release branch because the chart uses the url to the actual repo used in production: https://github.com/rancher/charts/blob/4184cf61eb7e92dbdad2e370cf90cd3cea006fef/charts/rancher-alerting-drivers/rancher-alerting-drivers/100.0.0/Chart.yaml#L16
 
We have to wait until charts are merged into the release-v2.6 branc to validate this issue.

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by brendarearden** [comment]
The chart repo for the v2.6.0-rc1 is still pointed to `https://git.rancher.io/charts`  branch `dev-v2.6` so this cannot be validated until its merged into rancher/charts `release-v2.6` branch, which will happen a few days before the 2.6 official release. 

Do we want to merge just this chart to release-v2.6 ahead of time? Or is it okay to leave this in QA Next Up till then?

**Comment by cbron** [comment]
Moving this to 2.6.1 to validate there, as we need github pages to change branches and that only happens post-release. If this isn't working in 2.6.0 its not end of the world.

**Comment by slickwarren** [comment]
on v2.6-head (6a0a991) the new image is displaying correctly on the charts page, and install page(s).
<img width="329" alt="Screen Shot 2021-09-13 at 9 15 09 AM" src="https://user-images.githubusercontent.com/16691014/133121730-ff336d73-a7dc-44c8-a10d-70161e3d4fe1.png">
