### ISSUE TITLE
Validate that the "system-default-registry" setting is set to a valid URL.

### ISSUE THREAD

**Issue by ikogan** [rancher/rancher#32625]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug/Enhancement

**Steps to reproduce (least amount of steps as possible):**
It might be a challenge to reproduce this specific thing but:

1. Edit the `system-default-registry` setting to an invalid HTTPS URl like `https:/my.private.registry/`.

**Result:**

Rancher will accept the invalid URL and attempt to modify the cluster, leading to a broken situation. Even after unsetting this value, some components may end up broken. In our cluster, we had a control plane node that had ended up breaking it's etcd. We only noticed this issue when trying to upgrade to Kubernetes 1.20 and having that node fail with the following:

```
[ERROR] cluster [c-zszzv] provisioning: Failed to set up SSH tunneling for host [x.x.42.1]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var$!F(MISSING)run%!F(MISSING)docker.so/v1.24/info": can not build dialer to [c-zszzv:m-5rwhp]
```

Perhaps this error is unrelated, but we we noticed the Node's registration URL contained the invalid system default registry. The only way to fix this was to destroy and re-create the node.

**Other details that may be helpful:**
Rancher should validate that the URL provided is actually a valid registry URL.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.19.6
- Docker version (use `docker version`): 1.19

**Comment by ikogan** [comment]
This seems like a fairly simple thing to fix and can easily cause serious cluster breakage. Would it be possible to implement this validation in the GUI?

**Comment by ikogan** [comment]
Does anyone know if this is something that has been improved in 2.6?

**Comment by mxm-tr** [comment]
Still facing the issue on 2.6.6
