### ISSUE TITLE
Load Balancer - expose HAProxy stats endpoint

### ISSUE THREAD

**Issue by AirbornePorcine** [rancher/rancher#3262]
It would be very handy if the default HAProxy stats endpoint could be exposed so our monitoring solutions can consume it. Or even better, if these stats could be integrated into Rancher's view of a LB container.

**Comment by sshipway** [comment]
With the current (0.51) version of Rancher, a Load Balancer lets you define some additional custom sections for the HAProxy global and defaults sections.  This should allow you to add the necessary configuration items to expose this endpoint, unless I've misunderstood it?  I've not tried to do it myself yet though.

**Comment by AirbornePorcine** [comment]
Unfortunately the current version only lets you add to the defaults/global section, and unless I'm mistaken you need to add a whole new listener in order to enable exposing the stats page.

**Comment by sshipway** [comment]
What about using this to expose the stats enpoint on a dedicated port:
````
    global
        stats socket ipv4@0.0.0.0:9999 level admin
        stats timeout 2m
````
as is mentioned on https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#9 ?  Might not be so secure, though.

However I've very little experience with HAProxy so I may be misunderstanding this.  I do notice that people also use the various options within the `listen` section and even add a whole new listen section for them.  I suppose that Rancher could also allow a third config block to be defined to hold any new listen sections....   

+1 for having the stats integrated into the Rancher UI as well

**Comment by alena1108** [comment]
@AirbornePorcine @sshipway we are going to add support for custom config on listen/backend as a part of the feature described in this bug:

https://github.com/rancher/rancher/issues/2179

**Comment by Dids** [comment]
Any ETA on this? I have projects that depend on monitoring bandwidth using the HAProxy stats endpoint.

**Comment by deniseschannon** [comment]
Closing in favor of #2179, but we are moving towards Rancher GA and due to lack of time, not all the refactoring may not make it in.
