### ISSUE TITLE
GKE Service Account is not updated for GKEv1 clusters

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#32622]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
In Google Cloud Platform, ready 2 service accounts.
In Rancher `v2.5.7`, provision a GKE cluster with service account alpha.
After cluster is made available, upgrade the setup to Rancher `v2.5.8`
Edit the cluster by loading service account beta. Save the cluster.
In Google Cloud Platform, disable service account alpha.
In Rancher, scale the node count of the cluster using service account beta.

**Result:**
Cluster edit fails with:
`Cluster health check failed: Failed to communicate with API server during namespace check: Unauthorized; Get "https://container.googleapis.com/v1/...?alt=json&prettyPrint=false": oauth2: cannot fetch token: 400 Bad Request Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}`

**Other details that may be helpful:**
This issue is a continuation of https://github.com/rancher/rancher/issues/28527 which was validated for GKEv2, but not GKEv1.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8
- Installation option (single install/HA): single install

**Comment by cbron** [comment]
@aaronRancher we can close this now right ? This was misunderstanding, that GKEv1 would upgrade to v2.

**Comment by aaronRancher** [comment]
@cbron This is not a cluster upgrade from GKEv1 to v2. This is a scenario where a GKEv1 cluster loses functionality after a Rancher upgrade. After the Rancher upgrade, a user cannot edit the cluster using a valid second service account. GKEv1 clusters should continue to work even after a Rancher upgrade.

**Comment by cbron** [comment]
@aaronRancher is this consistently reproducible ? Can you create this and send to me/devs tmrw.

**Comment by aaronRancher** [comment]
Amendment to my above comment. This did not work to begin with in v2.5.6. https://github.com/rancher/rancher/issues/28527#issuecomment-799841603
So this is actually not a loss in functionality. It simply did not work in previous Rancher versions.

**Comment by aaronRancher** [comment]
Closing issue after consulting with team. No changes will be made to gkev1 clusters as no functionality is lost on upgrade.
