### ISSUE TITLE
Route53 service programs AWS before stack metadata is set for it

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3263]
https://forums.rancher.com/t/rancher-just-wiped-my-route-53-zone/1448

Caused by bug in go-rancher-metadata. Route53 service accesses /self/stack information to get the environment name. And go-rancher-metadata doesn't validate response code when accessing metadata endpoints, so empty stack data is returned to route53 service which results in environmentName part being empty in FQDN.

Things to fix:

* go-rancher-metadata to return error when http response !=200
* in external-dns code, wait for the self/stack information to be set before proceeding further.

**Comment by alena1108** [comment]
This bug is not very easy to reproduce. The steps user has taken:

1) Deploy route53 service, let it run for a day or two.
2) Make sure all the records for your services are present on Route52 at the end of the second day

**Comment by sangeethah** [comment]
Tested with latest build from master:

1) Deployed route53 service and let the server run for couple of days.
2) Made sure all the records for your services are present on Route52 at the end of the second day
