### ISSUE TITLE
RKE2 Provisioning - Upgrading Rancher Server

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#32630]
Need to test:

**2.5.0 Helm Chart Options**
- Test using Fleet feature flag toggled to OFF. Upgrading to v2.6 should automatically turn this on.

**2.6.0 Helm Chart Options**
- RKE2 Provisioning feature flag is toggled ON
- RKE2 Provisioning feature flag is toggled OFF
- Test with Fleet feature flag toggled OFF to determine outcome

**Note:** Fleet is now a required feature flag to be turned on. Test use cases around fleet feature flag.

**Comment by izaac** [comment]
Upgrading from 2.5.8 to 2.6 `master-head` with fleet disabled. This enables fleet `master-head`
Follow up doc issue: #32688

**Comment by izaac** [comment]
Rancher 2.5.8 to `master-head (06/08/2021)` _3d465ee_


`helm upgrade rancher rancher-latest/rancher --version 2.5.8 --namespace cattle-system --set hostname=<RANCHER_HOST> --set 'extraEnv[0].name=CATTLE_FEATURES' --set 'extraEnv[0].value=rke2=false' --set rancherImageTag=master-head`

I was able to see the setting is disabled after the upgrade and I provisioning an RKE1 cluster worked after the upgrade.
The RKE1 <-> RKE2 switch wasn't available either in the Create Cluster page.

![Screen Shot 2021-06-08 at 9 54 59 AM](https://user-images.githubusercontent.com/27659/121226809-cc3d5b00-c83f-11eb-82fd-4762adfdc3d5.png)
![Screen Shot 2021-06-08 at 9 56 20 AM](https://user-images.githubusercontent.com/27659/121226827-cfd0e200-c83f-11eb-9c3a-d2badc176e81.png)

**Comment by izaac** [comment]
`master-head (06/08/2021)` _ce97613e8_ 
Opened issue on dashboard as the `/dashboard/home` shows emtpy
https://github.com/rancher/dashboard/issues/3192

RKE1 Provisioning worked
RKE2 Provisioning issue: https://github.com/rancher/rancher/issues/33095

**Comment by izaac** [comment]
Ability to turn fleet off from UI was disabled.
`rke2=off` scenario works as expected
Opened issues around `rke2=true` (might not be directly related).
Fleet GitOps feature turn on and off will be followed up on this other issue: https://github.com/rancher/rancher/issues/32808
