### ISSUE TITLE
RKE2 Provisioning - Support Downstream Clusters behind a Proxy

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#32633]
We need to test the ability to upgrade RKE2 when the Downstream Clusters are behind a proxy.

**Comment by deniseschannon** [comment]
@bashofmann There is indication that this may have been addressed in the 2.6.0 release, but we didn't have bandwith to fully validate this use case. Would you be able to take a try again for us? Thank you!

**Comment by bashofmann** [comment]
I tested it with 2.6.0 and also 2.6.0-head a6e7905  and neither `/var/lib/rancher/rke2/system-agent-installer/rke2-sa.env`, nor `/etc/systemd/system/rancher-system-agent.env` are updated when I edit the agent environment variables in the cluster configuration.

**Comment by deniseschannon** [comment]
Thanks @bashofmann!

@Oats87 I thought we were able to edit this and it would propagate down?

**Comment by snasovich** [comment]
@thedadams , please check if it's working now with your recent changes and if it doesn't what needs to be implemented.

**Comment by thedadams** [comment]
Moving this to v2.6.1 because the changes here are also needed for https://github.com/rancher/rancher/issues/34908

**Comment by thedadams** [comment]
As far as I understand this issue, the last thing to test fix and test was from this comment: https://github.com/rancher/rancher/issues/32633#issuecomment-905886622

That is, updating the `agentEnvVars` should propagate down to the `system-agent` and `system-upgrade-controller`. The evidence that this happened correctly is that the files `/etc/systemd/system/rancher-system-agent.env` and `/var/lib/rancher/rke2/system-agent-installer/rke2-sa.env` both contain the new `agentEnvVars`.

A test strategy:
1. Deploy an RKE2 cluster with default settings.
2. Wait for the cluster to become active.
3. Edit the cluster and add an `agentEnvVar` with key `NO_PROXY` and value `localhost`
4. Save the cluster. The cluster will reconcile, during which time it won't be possible to "explore" the cluster. That is expected.
5. Once the cluster is active and you are able to "explore" the cluster, you can SSH to the nodes and ensure that the two files above contain the new environment variable.

**Comment by slickwarren** [comment]
on 2.6-head (931a0f0):
each of the below steps were verified by checking `/etc/systemd/system/rancher-system-agent.env` and `/var/lib/rancher/rke2/system-agent-installer/rke2-sa.env`
* deploy non-proxied downstream cluster -> upgrade cluster with proxy settings -- pass
* deploy proxied downstream cluster -- pass
* deploy proxied downstream cluster -> modify/remove proxy settings -> update to original proxy settings -- pass
