### ISSUE TITLE
nfs provide

### ISSUE THREAD

**Issue by gssjl2008** [rancher/rancher#32639]
*Describe your issue here*

How to use nfs to dynamically provide pvc in k8s1.20？
must set:
 - --feature-gates=RemoveSelfLink=false 
Where do I need to set up？

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.8` UI: `v2.5.8` |
|Route|`undefined`|

**Comment by superseb** [comment]
Please see https://rancher.com/docs/rancher/v2.x/en/cluster-admin/editing-clusters/#editing-clusters-with-yaml or https://github.com/rancher/rancher/issues/30556#issuecomment-759390415
