### ISSUE TITLE
v1/management.cattle.io.settings/system-default-registry 404 not found on New clusters deployed with Rancher 2.5.8

### ISSUE THREAD

**Issue by runecalico** [rancher/rancher#32642]
**What kind of request is this (question/bug/enhancement/feature request):**
The rancher terraform provider complains of 404 not found when trying to use rancher2_app_v2 (install an app) on a cluster as the v1 API location does not exist - https://mycluster.local/k8s/clusters/myclusterID/v1/management.cattle.io.settings/system-default-registry

On 2.5.7 rancher clusters created DO have this v1 API location, however once upgraded to 2.5.8 (or a new install of 2.5.8) any new clusters deployed will NOT have this API location which breaks at least this specific terraform resource.  I am submitting the Issue to the rancher Issues as it seems to be a change in rancher, if that is an intended change then I can open up an issue with the rancher provider to support whatever the new API/method is to get that info, if it's NOT and intended change then this is the right place :)

**Steps to reproduce (least amount of steps as possible):**
Create vsphere Cloud Credential in gui
Create vsphere Node Template in gui
Create vsphere cluster in gui 
- Kubernetes "v1.20.6-rancher1-1", Rancher 2.5.8, Ubuntu 20.04LTS nodes
wait for cluster to provision/sync.
Get Cluster ID

**Result:**
Browse to https://mycluster.local/k8s/clusters/myclusterID/v1/management.cattle.io.settings/system-default-registry and get a 404 error
The API location doesn't exist, so it is not necessary to use terraform to validate it doesn't exist.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
This behavior is seen on a fresh install of the rancher 2.5.8, on kubernetes v1.20.5-rancher1-1 (setup using rke v1.2.8) on Ubuntu 20.04LTS nodes (3 of them).
As well as an 2.5.7 cluster upgraded to 2.5.8

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by rawmind0** [comment]
At previous Rancher versions, global settings were synced on all downstream k8s clusters API, but not anymore from v2.5.8. So global settings as `system-default-registry`, has to be got from local cluster always. 

Submitted PR at tfp to fix the issue https://github.com/rancher/terraform-provider-rancher2/pull/663

**Comment by vkruoso** [comment]
@rawmind0 is there a workaround about the `system-default-registry` issue? How can I create it manually? I understand your PR will change the behavior of the provider to use the global rancher default registry?

**Comment by rawmind0** [comment]
@vkruoso , yes, the PR is changing the behavior of the provider to use the global rancher default registry. It's already included at released Rancher2 tf provider v1.15.0

**Comment by rawmind0** [comment]
Please, reopen issue if needed

**Comment by vkruoso** [comment]
Awesome! Thanks @rawmind0!
