### ISSUE TITLE
Not able to start route53 srevice.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3264]
Server version - Build from master

Try to launch route53 service from catalog.

Container - route53_route53_1 keeps restarting.
Following exception is seen in container logs:

```
1/13/2016 1:09:51 PMtime="2016-01-13T21:09:51Z" level=fatal msg="Error reading stack info: json: cannot unmarshal object into Go value of type string"
1/13/2016 1:10:00 PMtime="2016-01-13T21:10:00Z" level=fatal msg="Error reading stack info: json: cannot unmarshal object into Go value of type string"
1/13/2016 1:10:09 PMtime="2016-01-13T21:10:09Z" level=fatal msg="Error reading stack info: json: cannot unmarshal object into Go value of type string"
```

**Comment by alena1108** [comment]
New template v0.2.1 was released for DNS. @sangeethah could you test following use cases:

1) fresh deploy using the latest version
2) Upgrade existing erroring out service to the new version

**Comment by sangeethah** [comment]
1.Deploying v0.2.1 version of "Route 53" works fine. Able to see the record sets getting programmed as expected.
2.Deployed v0.1.7 version of "Route 53"  where route53_route53_1 keeps restarting. Upgrade to v0.2.1 version of "Route 53" . After upgrade , "Route 53" service works fine. Able to see the record sets getting programmed as expected.
