### ISSUE TITLE
Network Policies are not defined when enabling PNI

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#32659]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Provision a downstream cluster with Project Network Isolation enabled:
![Screen Shot 2021-05-10 at 12 51 22 PM](https://user-images.githubusercontent.com/57409052/117719952-e9c0cb80-b192-11eb-98da-d64b4795261c.png)

**Result:**
Do not see the `hn-nodes` and `np-default ` network policies get created after cluster is provisioned:
```
> kubectl get networkpolicies -A
NAMESPACE             NAME                                POD-SELECTOR                                             AGE
cis-operator-system   default-allow-all                   <none>                                                   43m
fleet-system          default-allow-all                   <none>                                                   50m
ingress-nginx         hp-nginx-ingress-controller-md99t   field.cattle.io/podName=nginx-ingress-controller-md99t   49m
```
Network policies are not added to new namespaces:
```
> kubectl get networkpolicies -n test-ns
No resources found in test-ns namespace.
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-head` `version 8c014ef`
- Installation option (single install/HA): single install

**Comment by aaronRancher** [comment]
@ryansann Yes. The new namespace `test-ns` belongs to a project. This was tested with a namespace in a new project. And with a namespace in the default project.

**Comment by ryansann** [comment]
Running Rancher off of master and can confirm the behavior you have seen @aaronRancher 

This looks to be caused by missing projectId labels on all namespaces, I am investigating what's causing this

**Comment by ryansann** [comment]
This should be back to working as expected. The issue had to do with controllers in `pkg/controllers/managementagent` not being triggered for downstream cluster resources. This is fixed and now namespaces have `projectId` labels, which is allowing PNI to work as expected.

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/pull/32951/commits/1952830252abddea062a13ab23a66cbc8335e757

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 772ef96` with a downstream DO cluster.

After provisioning a cluster with PNI enabled:
`hn-nodes` and `np-default` network policies are created on cluster creation:
```
> kubectl get networkpolicies -A
NAMESPACE         NAME                   POD-SELECTOR   AGE
cattle-system     np-default-allow-all   <none>         10m
default           hn-nodes               <none>         10m
default           np-default             <none>         10m
fleet-system      default-allow-all      <none>         11m
ingress-nginx     np-default-allow-all   <none>         10m
kube-node-lease   np-default-allow-all   <none>         10m
kube-public       np-default-allow-all   <none>         10m
kube-system       np-default-allow-all   <none>         10m
security-scan     np-default-allow-all   <none>         10m
```
Network policies are also added in new namespaces inside and outside of default project:
```
> kubectl get networkpolicies -n testns
NAME         POD-SELECTOR   AGE
hn-nodes     <none>         7s
np-default   <none>         7s
```

**Comment by aaronRancher** [comment]
Tested enabling PNI on a downstream cluster provisioned with PNI disabled.
Before PNI is enabled:
```
> kubectl get networkpolicies -A
NAMESPACE      NAME                POD-SELECTOR   AGE
fleet-system   default-allow-all   <none>         9m56s
```
After PNI is enabled:
```
> kubectl get networkpolicies -A
NAMESPACE         NAME                   POD-SELECTOR   AGE
cattle-system     np-default-allow-all   <none>         21s
default           hn-nodes               <none>         21s
default           np-default             <none>         21s
fleet-system      default-allow-all      <none>         10m
ingress-nginx     np-default-allow-all   <none>         21s
kube-node-lease   np-default-allow-all   <none>         21s
kube-public       np-default-allow-all   <none>         21s
kube-system       np-default-allow-all   <none>         21s
security-scan     np-default-allow-all   <none>         21s
```
Network policies are also added in new namespaces inside and outside of default project after PNI is enabled.
