### ISSUE TITLE
UI session timed out page doesn't provide a login form or link to login

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#3266]
A little usability bug. When re-visiting Rancher UI when session as timed out user is redirect to `http://rancher.mydomain.com/login?timedOut=true` and presented with "Your session has timed out. Log in again to continue." however there is no form or link to login.

If the user goes to `http://rancher.mydomain.com/` manually the same page is rendered again, the user needs to know to go to `http://rancher.mydomain.com/login` as the workaround to be able to log back in.

Rancher	v0.51.0
Cattle	v0.130.0
User Interface	v0.78.0
Rancher Compose	v0.7.0

![screen shot 2016-01-14 at 9 02 10 am](https://cloud.githubusercontent.com/assets/131730/12309215/8c51a47a-ba9d-11e5-9950-22815fd8f002.png)

**Comment by vincent99** [comment]
@flaccid What kind of auth are you using and does this still happen for you?

**Comment by flaccid** [comment]
@vincent99 I believe at the time this was with local auth. I can't seem to replicate on local, ldap or github auth on a variety of versions so I am guessing this was fixed by stealth at some point. Perhaps close and re-open in future if someone runs into again/regresses.

**Comment by vincent99** [comment]
@flaccid works for me, thanks.
