### ISSUE TITLE
Deleting an RKE cluster from Dashboard does not delete the cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32663]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a cluster using new Dashboard
- Create an RKE cluster (toggle and choose RKE from RKE vs RKE2)
- Wait for the cluster to come up successfully.
- It will be available in the Cluster Management page (From left Panel --> Cluster Management)
- API Request sent: Method: `DELETE ` and request URL: `https://<server>/v1/provisioning.cattle.io.clusters/fleet-default/c-cjc9c`
- However, the cluster is seen on the `Left Pane` under Cluster Explorer but is disabled _or_ Greyed out.

**Expected Result:**
The cluster should be deleted in Rancher.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `8c014ef`
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE EC2/any
- Kubernetes version (use `kubectl version`):

```
Any
```

**Comment by izaac** [comment]
Rancher version `v2.6 master-head (05/18/2021) _55f0bb2_

This also happens with DO clusters.
https://github.com/rancher/rancher/issues/32663

**Comment by sowmyav27** [comment]
**On master-head commit id: `f90b36e`**

- Create a cluster using new Dashboard
- Create an RKE cluster (toggle and choose RKE from RKE vs RKE2)
- Wait for the cluster to come up successfully.
- It will be available in the Cluster Management page (From left Panel --> Cluster Management)
- Delete cluster, cluster is deleted successfully from Cluster management page and the nodes are deleted from the backend.
