### ISSUE TITLE
[Back port] [Rancher Alerting Drivers] Support Hardened Cluster

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#32665]
back port of https://github.com/rancher/rancher/issues/32358

**Comment by jiaqiluo** [comment]
can be validated in the chart rancher-alerting-drivers `1.0.200`

**Comment by slickwarren** [comment]
alerting-drivers 1.0.200 has passed all cis hardened scans on 2.5-head (0e58768)
