### ISSUE TITLE
Renew Rancher https certificate 

### ISSUE THREAD

**Issue by tempman5** [rancher/rancher#32670]
Question.

Rancher https certificate is expired today. It puts:

Issued for: dynamic
Issued by: cattle-ca
It expires today.

How can I renew it? And how I could change it to custom certificate signed by our CA? We have a private windows domain CA.

Rancher version: 2.4.10
Kubernetes version: 1.17.13
Operating System: Ubuntu Server 20.04
Not sure about Cluster type :-) I think that it is custom, I have a cluster with 3 master and 5 workers (not HA).
Machine type: VM
Docker version: 19.03.15

```

**Comment by tempman5** [comment]
Some help please? Thanks

**Comment by tempman5** [comment]
Some help about this please?

**Comment by tempman5** [comment]
Could someone help me with this please? Thanks beforehand.

**Comment by maxisam** [comment]
I am dealing with this issue as well. It seems pretty complicated. After I did first 2 steps. Rancher can't start correctly, so I have to revert back to the old certificate.

https://rancher.com/docs/rancher/v2.5/en/installation/resources/update-ca-cert/

Do you figure out how to do it?
