### ISSUE TITLE
AKS Provisioner: HTTP application routing

### ISSUE THREAD

**Issue by mjura** [rancher/rancher#32674]
The HTTP application routing solution makes it easy to access applications that are deployed to Azure Kubernetes Service (AKS) cluster. When the solution's enabled, it configures an Ingress controller in AKS cluster.

Epic https://github.com/rancher/rancher/issues/31045

PR: https://github.com/rancher/aks-operator/pull/11

**Comment by gaktive** [comment]
UI needed: https://github.com/rancher/rancher/issues/32991

**Comment by prabalsharma** [comment]
Tested on master-3d465ee, aks operator rc7
