### ISSUE TITLE
Rancher Monitoring Grafana Home dashboard disk utilization wrong

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#32679]
**What kind of request is this (question/bug/enhancement/feature request):**
 Bug

**Steps to reproduce (least amount of steps as possible):**
* Install rancher-monitoring v2
* Go to Monitoring -> Grafana
* The Grafana Home dashboard is opened

**Result:**
The disk utilization dial is wrong. The utilization of each node is around 8%, but the overall dial shows 0.08%.

<img width="1705" alt="Bildschirmfoto 2021-05-11 um 19 11 17" src="https://user-images.githubusercontent.com/243056/117857391-03ded480-b28d-11eb-8638-9f5c503cc4cb.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8
- Installation option (single install/HA): HA

**Comment by slickwarren** [comment]
appears to be working correctly now on master-head (3e89bb868a4596c36cbeee93bd909d8a3b8fc1fa):
RKE2 cluster:
<img width="594" alt="Screen Shot 2021-05-12 at 11 49 30 AM" src="https://user-images.githubusercontent.com/16691014/118028732-47325500-b318-11eb-8dc0-81d5ac29c22d.png">

windows cluster:
<img width="594" alt="Screen Shot 2021-05-12 at 11 54 26 AM" src="https://user-images.githubusercontent.com/16691014/118029261-d93a5d80-b318-11eb-8071-c90170aad66a.png">
