### ISSUE TITLE
Pull in rke2 images to images.txt

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32678]
We need to add a setting for which version of rke2 to use, and given that setting we can download the rke2 images.txt and append it to ours: https://github.com/rancher/rke2/releases/download/v1.21.0-alpha3%2Brke2r1/rke2-images-all.linux-amd64.txt
This should ensure the `rancher-images-sources.txt` ist sets the source as `rke2`.

**Comment by ron1** [comment]
@cbron consider taking care of https://github.com/rancher/rancher/issues/32671 while you are at it.

**Comment by cbron** [comment]
@ron1 I believe there is already issue for that: https://github.com/rancher/rancher/issues/32051
However it will likely be addressed in different way.

**Comment by ron1** [comment]
@cbron thx for the feedback. I will close https://github.com/rancher/rancher/issues/32671 as a dupe. Thx again.

**Comment by cbron** [comment]
Actually this itself is dupe of https://github.com/rancher/rancher/issues/32403
