### ISSUE TITLE
Cannot use the deallocateFromHost parameter on instance.stop action

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3268]
If you do, the container ping logic that makes cattle and the host match  will effectively reallocate it.

This can be observed in test_allocation.test_compute_free, which currently fails inconsistently. If you add a time.sleep(10) to line just before the final `assert host.computeFree == start_free`, it will fail every time.

Steps to reproduce:
1. container is create and started
2. container is stopped and deallocated - this puts instance.state == stopped and instance.allocationState == inactive and instancehostmap.state == removed
3. the ping logic (which looks for instances with non-removed instanceHostMaps) finds that the instance exists on the host but not in rancher (bc no instanceHostMap)
4. ping logic issues a start via containerEvent for the container. because  containerEvents result in NoOP events down in python-agent, this wont change the state of the actual container on the host
5a. in real life with a real host, the container stays stopped and the next pings creates a stop event for the container result in an instance with state == stopped, allocation_state == active
5b. in simulator life with a simulate host, the simulator doesnt pay attention to the NoOp flag and starts the container. this results in an instance with state == started, allocation_state == active

so, in both real and simulator versions, we stomp on the deallocation and basically immediately reallocate it.

**Comment by cjellick** [comment]
ping @ibuildthecloud

**Comment by ibuildthecloud** [comment]
deallocFromHost is now removed https://github.com/rancher/cattle/pull/1513

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.0.0-rc1

container.stop action has only remove and timeout option. There is no deallocFromHost option.
