### ISSUE TITLE
[Backport] Enhance agent logging on worker requirement

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#32683]
Backport https://github.com/rancher/rancher/issues/32204

**Comment by Jono-SUSE-Rancher** [comment]
This needs to be validated on a v.2.5.9-RC as well as a v2.5-head.

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5-head` `version b82981b` with the following steps:
Create custom cluster
Add node with etcd and controlplane node (no node with worker role)
View logs from etcd/controlplane node rancher-agent.

Result:
Logs from rancher-agent in control plane/etcd node:
```
time="2021-07-02T21:31:15Z" level=info msg="Connecting to proxy" url="wss://.../v3/connect/register"
time="2021-07-02T21:31:15Z" level=info msg="Starting plan monitor, checking every 15 seconds"
```
Did not see logging for worker requirement.

Expected the logs `Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered`

**Comment by aaronRancher** [comment]
Worker requirement logging is also not seen on master-head.
Tracking issue here: https://github.com/rancher/rancher/issues/33494

**Comment by aaronRancher** [comment]
Moving back to test. Will track the missing logs in the above issue.

**Comment by aaronRancher** [comment]
Will validate this issue after fix has been backported: https://github.com/rancher/rancher/issues/33624

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5-head` `version 0e58768` with the following steps:
- Create an RKEv1 custom cluster
- Add node with etcd and control plane node (no node with worker role)
- View logs from rancher-agent in control plane/etcd node.

Result:
Worker requirement logs are seen on custom cluster.
```
time="2021-07-19T23:59:00Z" level=info msg="Connecting to proxy" url="wss://.../v3/connect/register"
time="2021-07-19T23:59:00Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-07-19T23:59:02Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
```
After adding a worker node, worker requirement logs stop and the cluster comes into active state.
