### ISSUE TITLE
Disabling fleet from feature flags on Rancher Ember UI breaks Rancher HA

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32680]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install Rancher 2.6 (master-head) k8s RKE HA
- Disable fleet from Ember UI `Global -> Settings -> Feature Flags -> Disable fleet.

**Result:**

Rancher pods are in `CrashLoopBackOff`
`[FATAL] multi-cluster-management features requires feature fleet=true`

```
 k get po -n cattle-system
NAME                               READY   STATUS             RESTARTS   AGE
helm-operation-kr5bp               0/2     Completed          0          2m42s
helm-operation-ljk9r               0/2     Completed          0          2m24s
helm-operation-tqr28               0/2     Completed          0          3m8s
rancher-664c44c8bf-44d6m           0/1     CrashLoopBackOff   1          4m24s
rancher-664c44c8bf-9t58n           0/1     CrashLoopBackOff   1          4m24s
rancher-664c44c8bf-tnmp6           0/1     CrashLoopBackOff   1          4m24s
rancher-webhook-5966888dd6-kqzjb   1/1     Running            0          2m15s
```

**Other details that may be helpful:**

During upgrade from 2.5.8 to 2.6 (master-head) the same behavior is observed.

Sample upgrade helm command:

`helm upgrade rancher rancher-latest/rancher --version 2.5.8 --namespace cattle-system --set hostname=<RANCHER_HOSTNAME> --set 'extraEnv[0].name=CATTLE_FEATURES' --set 'extraEnv[0].value=fleet=false' --set rancherImageTag=master-head`

**Environment information**
- Rancher version: Rancher 2.6 (master-head _1e1ed6732_)
- Installation option: HA

Reference issue: https://github.com/rancher/rancher/issues/32630

**Comment by izaac** [comment]
Upgrading from 2.5.8 installed with fleet disabled and then upgrading to `master-head` (without setting the feature flags variables in helm) results in an upgraded rancher with fleet enabled.

The pods were restarted a few times (~3 times) 

`That worked but the pods were restarted a few times[FATAL] feature flag [fleet] value has changed, rancher must be restarted`

**Comment by deniseschannon** [comment]
While updating the `fleet` feature flag to be constantly on, can you also make it hidden?

**Comment by deniseschannon** [comment]
@izaac The feature flag should now be hidden in the UI.

**Comment by izaac** [comment]
Rancher version `v2.6 master-head (06/01/2021)` _618c9ef_

The fleet Feature Flag is not visible/available on a later Rancher build.
Checked both `Cluster Manager (Ember)` and `Cluster Explorer (Vue)`
