### ISSUE TITLE
gkeV2- will nice to be able to set "Minimum number of nodes" to 0 in "autoscaling"

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32685]
**What kind of request is this (question/bug/enhancement/feature request):** **Feature Request**

**Steps to reproduce (least amount of steps as possible):**
1 . Create GKE cluster
2. Node pools --> Enable Autoscaling
3. Minimum node count = 0
4. Create

**Result:**

```
MinNodeCount in the NodePool must be >= 1 and <= maxNodeCount

```

**Other details that may be helpful:**
GKE allows user to set "Minimum number of nodes" to 0 in "autoscaling". This allows users to bring down node count in such node pools to 0, via `Cluster Edit`.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-1e1ed67329d6224e7a10f1c1a529eaff60ba48ea-head
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cbron** [comment]
This may be possible in gcp, but Rancher needs at least one node to function as the agent needs to be deployed. Especially for private cluster scenarios, you may get to an unrecoverable state.
