### ISSUE TITLE
[Backport] Rancher keeps stale data in /var/lib/rancher/management-state/rke

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#32682]
Backport https://github.com/rancher/rancher/issues/21976

**Comment by kravciak** [comment]
Tested as part of original issue https://github.com/rancher/rancher/issues/21976

**Comment by Ryan-Lochrane** [comment]
Upgraded from v2.5.7 to v2.5.11 and the issue doesn't seem to be resolved. I still see ~30GB in the Management-state directory
