### ISSUE TITLE
Fleet feature gets enabled after upgrade to 2.6 from an upgraded 2.5 without fleet enabled but pods get restarted a few times

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32688]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

- Install rancher 2.5.8 HA with fleet feature disabled.
  - `--set 'extraEnv[0].name=CATTLE_FEATURES' --set 'extraEnv[0].value=fleet=false'`
- Upgrade the HA to 2.6 without any features variables in the `helm`

**Result:**

Rancher gets upgraded to 2.6
pods get restarted a few times in the process.

**Other details that may be helpful:**

```
Log:
[FATAL] feature flag [fleet] value has changed, rancher must be restarted


NAME                               READY   STATUS      RESTARTS   AGE
rancher-7984cc8b4-ftd97            1/1     Running     3          55m
rancher-7984cc8b4-v2pkm            1/1     Running     0          50m
rancher-7984cc8b4-xf224            1/1     Running     3          55m
```

In this case two of the pods restarted 3 times.

Related issue: https://github.com/rancher/rancher/issues/32680

**Environment information**
- Rancher version: 2.6 _1e1ed67_
- Installation option: HA RKE

**Comment by Jono-SUSE-Rancher** [comment]
This is expected behavior as fleet is required for operation in 2.6. We will make sure to document in release notes.

**Comment by izaac** [comment]
Rancher version `2.6 master-head (05/26/2021)` _6395fbccd_
Upgrade from 2.5.8
RKE1 HA

[before_upgrade_fleet_false.log](https://github.com/rancher/rancher/files/6550340/before_upgrade_fleet_false.log) - 2.5.8
[after_upgrade_fleet_false.log](https://github.com/rancher/rancher/files/6550337/after_upgrade_fleet_false.log) - master-head

Pods restarted, logs with `--previous`
Pod3 wasn't restarted, so it has no previous container logs.
[after_upgrade_pod2.log](https://github.com/rancher/rancher/files/6550338/after_upgrade_pod2.log)
[after_upgrade_pod1.log](https://github.com/rancher/rancher/files/6550339/after_upgrade_pod1.log)

**Comment by izaac** [comment]
@StrongMonkey I've attached the logs in my previous comment. Of an upgrade from 2.5.8 with fleet disabled to master-head

What's the reason only two of the pods were restarted. And why the third pod wasn't restarted.

**Comment by izaac** [comment]
Rancher `v2.6 master-head (07/12/2021)`  _ad099ee_

Upgrade from 2.5.8 with fleet disabled. The Rancher setup is HA RKE1.
The rancher pods were restarted as expected and the `fleet` feature flag set to `enabled`.  The continuous delivery flag was enabled too.

The pods were restarted in this distribution: one pod 2 times, second pod 1 time and the third pod wasn't restarted.

```
rancher-5ddd6c9f97-bg4rf           1/1     Running     2          23m
rancher-5ddd6c9f97-lg88p           1/1     Running     1          23m
rancher-5ddd6c9f97-vx94n           1/1     Running     0          21m
```
