### ISSUE TITLE
[Backport] Creating cluster with multiple nodes, some of the nodes remain in Active until the other nodes provision

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#32681]
Backport https://github.com/rancher/rancher/issues/30346

**Comment by thehejik** [comment]
**Test report:**
* Tested on rancher/rancher:v2.5-head `12cd346`
* used DO driver for deployment of 3 `worker` nodes and 3 nodes with `control plane` and `etcd` roles from Ember UI
* The deployment was successful and done at once - not in batches of 5 nodes as before

![anim-do](https://user-images.githubusercontent.com/12828077/118004767-09e6bb00-b34a-11eb-9268-c4cc11417e54.gif)

Closing.

**Comment by Jono-SUSE-Rancher** [comment]
Re-opened this because it needs to be tested for the v2.5.9 milestone.

**Comment by dramich** [comment]
https://github.com/rancher/rancher/pull/32870

**Comment by jiaqiluo** [comment]
available for testing in rancher `v2.5.9-rc1`

**Comment by thehejik** [comment]
**Test report:**
* Tested on `rancher/rancher:v2.5.9-rc2`
* used DO driver for deployment of 3 `worker` nodes and 3 nodes with `control plane` and `etcd` roles from Ember UI
* The deployment was successful and provisioning was done at once - not in batches of 5 nodes as before

![do-provisioning-259rc2](https://user-images.githubusercontent.com/12828077/121329345-6cb17f00-c915-11eb-8a69-77fb337e3fd1.png)

Close.
