### ISSUE TITLE
While creating custom cluster using rke2, taints flag is not available.

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rancher#32695]
Build from master-8c014efa85314ab1cb1cb79261d2db9251ccf31d

Describe the issue:
taints flag is not available.

Steps to reproduce:

1. Click on Cluster Management->Create-Custom
2. Enter Name to the the cluster-> Create
3. Click on the name of the cluster in the next window
4. Click on Show Advanced
5. Enter the label and taints
6. Copy the registration command and execute it on the node previously created.

```
curl --insecure -fL https://<redacted>/system-agent-install.sh |  sh -s - --server https://<redacted> --token <redacted> --ca-checksum <redacted> --label foo=bar --taints mykey=myval:PreferNoSchedulecurl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16323    0 16323    0     0  1328k      0 --:--:-- --:--:-- --:--:-- 1328k
[INFO]  Label: foo=bar
[FATAL]  Unknown argument passed in (--taints)
```

Additional info:
Verified node taint can be set on a standalone rke2 server.
```
kubectl describe nodes |grep taint
                    rke2.io/node-args: ["server","--token","********","--node-label","foo=bar","--node-taint","mykey=myval:PreferNoSchedule"]
```

While testing found few other flags are not available
--address
--internal-address
--node-name

**Comment by deniseschannon** [comment]
@Oats87 Can you support both `taints` and `taint`?

As RKE1 had `taints` and we want the commands to be able to match.

**Comment by deniseschannon** [comment]
Can you open a new issue for supporting `--node-name` `--address` and `--internal-address` and assigned to @Oats87 ?

**Comment by Oats87** [comment]
@deniseschannon do we want to support both `--taint` and `--taints`? Not entirely sure why we pluralized it in the first place.

**Comment by deniseschannon** [comment]
Yes, `--taint` should be the correct one to use, but we used `--taints` as keeping up with legacy commands from RKE1.

**Comment by ShylajaDevadiga** [comment]
While provisioning rke2 custom cluster using DO, taints fail to be applied on the cluster due to invalid format stored in config
Follow the steps to reproduce to create the cluster.

**Value stored in config**
```
"node-taint": [
    "key1=value1=NoSchedule:"
  ],
```
**Logs:**
```
Jun 24 20:49:54 shyubu rke2[1375]: E0624 20:49:54.440717    1375 server.go:156] "Failed to parse kubelet flag" err="invalid argument \"key1=value1=NoSchedule:\" for \"--register-with-taints\" flag: invalid t
aint effect: , unsupported taint effect"
``` 
**Format when taint is applied  on a standalone rke2 node as seen in logs is as below**
```
--register-with-taints=key1=value1:NoSchedule
```

**Comment by ShylajaDevadiga** [comment]
Closing this issue in favor of https://github.com/rancher/rancher/issues/33419 as original issue with taint flag is resolved.
