### ISSUE TITLE
Feature request: Display existing LimitRange on namespaces on AKS imported cluster

### ISSUE THREAD

**Issue by alasgarov** [rancher/rancher#32697]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature request

**Steps to reproduce (least amount of steps as possible):**

Import into the Rancher an existing AKS cluster where LimitRanges are already defined on namespaces. 

Go to Cluster Explorer --> click on Namespaces on the left hand-side list --> click on a namespace you which to check --> click on config on the right-hand upper corner.

You can see that nothing is defined in "Container Resource Limit", even though limitrange is actually already defined on this namespace and you can see it by running: _kubectl get limitrange -n blahblah -o yaml_ from the shell. 

**Result:**

If you define a limitange from Rancher UI then it will be visible from that point on. Before creating new Resource Limits it would be useful to see the existing ones. Please implement this feature. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  2.5.7
- Installation option (single install/HA):  single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):      AKS imported
- Kubernetes version -     19.9

```
(paste the output here)
```

- Docker version (use `docker version`):     20.10.6

```
(paste the output here)
```

**Comment by ealasgarov** [comment]
this issue is still relevant, it would be good to get this feature implemented.
