### ISSUE TITLE
AKS v2: Provide the resource groups to the UI

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#32699]
It'd helpful for the resource groups to be exposable via the API or backend so that it could appear in the UI.

Epic https://github.com/rancher/rancher/issues/31045

PR https://github.com/rancher/rancher/pull/32656

**Comment by cbron** [comment]
What does this issue mean exactly ? I don't know what "resource groups" means in AKS context. Should that PR be linked to issue 32587 instead @mjura  ?

**Comment by mjura** [comment]
Wes wanted to have cluster names with resource groups names where they are created.
This was implemented in another proxy UI call https://github.com/rancher/rancher/pull/32656

**Comment by cbron** [comment]
Ok, closing this one and reusing 32587 instead to clean up issues
