### ISSUE TITLE
Error while uninstalling v2 apps

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32694]
On 2.5-head - commit id: `395b4fe77`

- Install rancher-backups: v1.0.300
- Select `rancher-backup` and `rancher-backup-crd` and click on "Delete" after they have been successfully installed.
- `rancher-backup-crd` gets deleted first
- Error in `rancher-backup` uninstallation logs: 

```
helm uninstall --namespace=cattle-resources-system rancher-backup
Error: uninstallation completed with 1 error(s): unable to build kubernetes objects for delete: unable to recognize "": no matches for kind "ResourceSet" in version "resources.cattle.io/v1"
```

**Comment by deniseschannon** [comment]
@sowmyav27 We don't plan on fixing this and expect users to understand that they need to delete the helm chart using the CRDs before the CRD charts themselves.

**Comment by sowmyav27** [comment]
Closing this based on these comments - https://github.com/rancher/rancher/issues/32694#issuecomment-866316914
