### ISSUE TITLE
Upgrade rancher-instance for python >= 2.7.9 for SSL SNI support

### ISSUE THREAD

**Issue by dkiser** [rancher/rancher#3269]
As a rancher/agent user, I should be able to allow the python `websocket` library to talk to an endpoint that supports SSL SNI, so that I can allow the websocket-proxy or integrated websocket-proxy/rancher-server to live behind an SSL SNI relay load balancer.

problem
-----------

error connecting to websocket endpoint during rancher/agent bootstrapping
```bash
error from callback <function on_error at 0x7fa3e324d758>: ('Received websocket error: [%s]', SSLError(8, '_ssl.c:510: EOF occurred in violation of protocol'))
```

This was due to an haproxy SNI relay load balancer tier closing the connection due to the lack of SNI headers in the TLS packet, ultimately bubbling up to the python exception above.

solution
----------
I jumped into the rancher-agent container, installed python 2.7.9 and updated the system python symlink and the agent was then able to connect to a rancher-server behind an SNI SSL relay load balancer (haproxy).  

According to https://github.com/liris/websocket-client/blob/b614606b35a9b336875e46fe6d4e856392cb9b71/websocket/_http.py#L126  the rancher/agent image either needs to utilize Python >=2.7.9 or >= 3.2 for SNI to work properly.

**Comment by vincent99** [comment]
I agree, much like last time we talked about it :-). https://github.com/rancher/rancher/issues/2185

**Comment by dkiser** [comment]
Ha totally forgot about that.
