### ISSUE TITLE
Provider of custom RKE2 cluster identified as Unknown on Cluster Management page in Explorer

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#32709]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* Deploy custom RKE2 cluster from Cluster Management in Explorer UI
* Go to `Cluster Management` and see Provider type of the newly created cluster

**Result:**
The provider is detected as `Unknown/RKE2` on `Cluster Management` page:
![management_provider](https://user-images.githubusercontent.com/12828077/118141481-b20f8900-b409-11eb-8b80-a4aad126bf0a.png)

**Other details that may be helpful:**
* in Ember UI the RKE2 cluster is correctly detected as `Rke2`
* on`Cluster Dashboard` page within Explorer UI the provider is correctly detected as `RKE2`:
![dashboard_provider](https://user-images.githubusercontent.com/12828077/118140822-05350c00-b409-11eb-9af6-5c316926307b.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher/rancher:master-head` `351f7ca`
- Installation option (single install/HA): any

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom RKE2

**Comment by vincent99** [comment]
https://github.com/rancher/dashboard/issues/2985
