### ISSUE TITLE
Cannot provision linode cluster - `name not registered for interface: "*cli.StringSlice"`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32701]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy a linode cluster

**Result:**
I got this error from the node when deploying a downstream linode cluster on master-head (3e89bb868a4596c36cbeee93bd909d8a3b8fc1fa) through dashboard and through ember UI:
```
Error setting machine configuration from flags provided: gob: name not registered for interface: "*cli.StringSlice"; Timeout waiting for ssh key	
```

**Other details that may be helpful:**
this is working with other providers, such as DO. so this is linode specific

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (3e89bb868a4596c36cbeee93bd909d8a3b8fc1fa) 
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): linode provisioned
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4vcpu

**Comment by thedadams** [comment]
https://github.com/rancher/machine/pull/124

**Comment by slickwarren** [comment]
on master-head (5d2b7ac), I am now able to provision a linode RKE cluster thorugh dashboard and ember
* single node through dashboard and ember -- pass
* multi-node through dashboard -- pass
