### ISSUE TITLE
[monitoring v2] Magic links not clickable, but all services are working as expected

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32703]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy monitoring v2 on a downstream RKE2 cluster v14.5.101

**Result:**
* none of the links are accessible on the monitoring tab
<img width="1297" alt="Screen Shot 2021-05-12 at 11 45 18 AM" src="https://user-images.githubusercontent.com/16691014/118028177-a2b01300-b317-11eb-8f73-dd4345c4068e.png">

**Other details that may be helpful:**
* on the cluster dashboard page, embedded grafana and the grafana links work
<img width="1413" alt="Screen Shot 2021-05-12 at 11 45 34 AM" src="https://user-images.githubusercontent.com/16691014/118028212-ad6aa800-b317-11eb-9775-51a89e8fdde6.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (3e89bb8)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Digital Ocean provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 6vCPU
- Kubernetes version (use `kubectl version`): v1.21.0-alpha3+rke2r1

**Comment by aquam8** [comment]
Hi!

I happened to try to migrate to Rancher 2.5.8 and Monitoring 14.5.100. It's the same for me. Monitoring landing page does not show any clickable links BUT the embedded Grafana graphs work. Clicking on 'Grafana (new window)' link opens Grafana in new page (nice!). From there clicking onto left menu bar Dashboard / Home fails BUT I can load other dashboards.

Environment information
- Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): 2.5.8
- Installation option (single install/HA): single

Cluster information
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted EKS (private cluster)
Machine type (cloud/VM/metal) and specifications (CPU/memory): m5.large (cpu: 2, mem: 8GB)
Kubernetes version (use kubectl version): v1.19.6-eks-49a6c0

**Comment by aquam8** [comment]
I can confirm that enabling 'alertManager' in Helm makes those links on the Monitoring landing page clickable as report in https://github.com/rancher/dashboard/issues/2494#issuecomment-809580866

**Comment by thehejik** [comment]
Seems this has been fixed in recent `rancher/rancher:master-head f223834` on custom RKE2 with v2 monitoring `14.5.101` - the links are working:
![monitoring_links](https://user-images.githubusercontent.com/12828077/118260916-30743580-b4b3-11eb-90fa-1b2344b80e15.png)

**Comment by Jono-SUSE-Rancher** [comment]
@sowmyav27 - If this is working on the current version of master, do we need to keep this open? Are you keeping this for tracking purposes?

**Comment by slickwarren** [comment]
currently blocked by https://github.com/rancher/rancher/issues/32943

**Comment by slickwarren** [comment]
on master-head (772ef96) magic links are working properly on RKE/RKE2 clusters
