### ISSUE TITLE
Created local cluster when updated Rancher 2.4.X to 2.5.X

### ISSUE THREAD

**Issue by tempman5** [rancher/rancher#32708]
Question.
We've updated our Rancher version from 2.4.10 to 2.5.8.
Is it normal that when process done it creates a new local cluster name with K3s provider? Our current cluster is Custom with 9 nodes, 4 master and 5 workers.
I can see both cluster names from the Rancher GUI. It doesn't allow delete the local cluster. The new local cluster is with a newer version of Kubernetes (1.19.8+k3s1) and our custom cluster is with 1.17.13.
I've done something bad :-? Thanks beforehand.

Cheers...

**Comment by superseb** [comment]
https://github.com/rancher/rancher/releases/v2.5.0

```The local cluster can no longer be turned off, which means all admins will have access to the local cluster. If you would like to restrict permissions to the local cluster, there is a new restricted-admin role that must be used.
```

**Comment by tempman5** [comment]
But then please, is it normal that I have a separated cluster or my nodes should be together to local cluster and not in a separated custom cluster? Thanks beforehand.

**Comment by superseb** [comment]
The `local` cluster is the embedded cluster running in the `rancher/rancher` container when using Docker single install or is the cluster that you installed Rancher on using the Helm chart. Basically it was always there but you could turn it off in the UI but now its visible. The link in the release notes shows you how you can disable access to it, but you can't turn it off/hide it anymore.
