### ISSUE TITLE
vsphere ssh command error -- can't provision downstream nodes on vsphere

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32715]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* deploy rancher on vsphere
* setup node template for vsphere on rancher server
* deploy downstream cluster (single node is fine to use with all roles)

**Result:**
node has the following error, and eventually times out
```
Error getting ssh command 'exit 0' : ssh command error: command: exit 0 err: exit status 255 output:
```

**Other details that may be helpful:**
this was attempted with 6.7 and 7, both of which have the error 
<img width="620" alt="Screen Shot 2021-05-13 at 10 54 56 AM" src="https://user-images.githubusercontent.com/16691014/118165895-b3c15880-b3d9-11eb-8ae8-7ccd4d70631b.png">

also it appears that the VM/rancher is not configuring hardware requests correctly either
<img width="1358" alt="Screen Shot 2021-05-13 at 1 03 44 PM" src="https://user-images.githubusercontent.com/16691014/118180678-aad98280-b3eb-11eb-8e13-a3e2dd5503e4.png">
<img width="321" alt="Screen Shot 2021-05-13 at 1 02 47 PM" src="https://user-images.githubusercontent.com/16691014/118180681-ac0aaf80-b3eb-11eb-9312-02bcc9226174.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (351f7ca04973c1f023653f171c0f621f31bf2ca2) 
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vsphere 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4vCPU
- Kubernetes version (use `kubectl version`): 1.20, 1.19

**Comment by slickwarren** [comment]
on master-head (5d2b7ac), I am able to provision downstream clusters again on vsphere. Filing a seperate ticket for the incorrect hardware assignments

**Comment by cbron** [comment]
@slickwarren / @thedadams  did this ever happen in 2.5 or only master/2.6 ?

**Comment by slickwarren** [comment]
I only noticed this on master/2.6
