### ISSUE TITLE
When deleting a Stack/Service there should be a purge/restore similar to what is done for single containers

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#3272]
Right now when deleting a container via Rancher UI > Hosts one get the option to purge or restore. This is great functionality, especially the restore so one can recover from mistakes.

I think the same functionality should be made available from the Application > Stacks. When I choose a stack > delete, I expect the Stack to remain visible with state "deleting" and giving me the option of "purge" or "restore" the same way as it is done for the single container. The same should apply when deleting single Service within a Stack.

**Comment by vincent99** [comment]
Removed ("deleted") vs Purged states are really intended more for companies with data-retention requirements to retain data for a period of time and be invisible to the (non-admin) users (though this is not currently actually the case, see #384 .  Will likely be bundled with a v2 API cleanup effort).  Not as a 2nd are you really-really sure you want to delete confirm.  Higher-level constructs like stack and service don't have any actual data to retain other than what is in the database (and not lost on delete).
