### ISSUE TITLE
share-mnt container keep restarting

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32727]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a 2 nodes - 1 all roles + 1 worker node
- wait for the cluster to come up
- The share-mnt on the nodes keep restarting with error

```
INFO: Arguments: -- share-root.sh docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:master-c0508344405fb9bd55198d2196e93fe3fc33ade7-head --server https://173.255.210.121 --token REDACTED --ca-checksum 3a8bab0e52493281656c17361c02f97015f43bb9fd5330c123972d1c6ecc05d4 --no-register --only-write-certs --node-name sowmya-domaster-1
/usr/bin/run.sh: line 26: /usr/bin/share-root.sh: Permission denied
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `c0508344`
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO RKE1
- Kubernetes version (use `kubectl version`):

```
1.20.6 (Any)
```

**Comment by StrongMonkey** [comment]
Can we retest this? https://github.com/rancher/rancher/pull/32662 Luther made a change which removes share-root.sh and it should fix this issue.

**Comment by thehejik** [comment]
**Test report:**
The container `share-mnt` is still restarting with Exit code 137 on both nodes (all roles & worker) on latest `rancher/rancher:master-head 5d49b92`

```
root@master1:~# docker ps -a --filter name=share-mnt --no-trunc
CONTAINER ID                                                       IMAGE                                                                        COMMAND                                                                                                                                                                                                                                                     CREATED       STATUS                            PORTS     NAMES
8837d6ba9dc48ba6a99f1b64491624225f074ff741f8bf4ebdbfa72378647b0b   rancher/rancher-agent:master-5d49b92f479a00773607fb41fe851f98271148c0-head   "run.sh --no-register --only-write-certs --node-name master1 --server https://rancher --token REDACTED '--ca-checksum 51fb85fa9be6c1f4ad8f0761286904b72a0aa000784a7f80b9d7f2b0f2f42958'"   3 hours ago   Exited (137) About a minute ago             share-mnt
```

But the error is probably different as now I don't see `Permission Denied` or any other Error in `share-mnt` container log:
```
root@master1:~# docker logs 8837d6ba9dc4
INFO: Arguments: --no-register --only-write-certs --node-name master1 --server https://rancher --token REDACTED --ca-checksum 51fb85fa9be6c1f4ad8f0761286904b72a0aa000784a7f80b9d7f2b0f2f42958
INFO: Environment: CATTLE_ADDRESS=1.2.3.4 CATTLE_AGENT_CONNECT=true CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=master1 CATTLE_SERVER=https://rancher CATTLE_TOKEN=REDACTED CATTLE_WRITE_CERT_ONLY=true
INFO: Using resolv.conf: nameserver 127.0.0.53 options edns0
WARN: Loopback address found in /etc/resolv.conf, please refer to the documentation how to configure your cluster to resolve DNS properly
INFO: https://rancher/ping is accessible
INFO: rancher resolves to 4.3.2.1
time="2021-06-01T11:53:24Z" level=info msg="Listening on /tmp/log.sock"
time="2021-06-01T11:53:24Z" level=info msg="Rancher agent version 5d49b92f4 is starting"
time="2021-06-01T11:53:24Z" level=info msg="Option requestedHostname=master1"
time="2021-06-01T11:53:24Z" level=info msg="Option dockerInfo={RDOI:VN6F:I5L2:L643:J2IL:RLE7:XVZC:H4GK:ZP4A:QOAB:PWK3:3IWA 45 30 0 15 17 overlay2 [[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] [] {[local] [bridge host ipvlan macvlan null overlay] [] [awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} true false true true true true true true true true true true false 187 true 160 2021-06-01T11:53:24.244868861Z json-file cgroupfs 1 0 4.15.0-143-generic Ubuntu 18.04.5 LTS 18.04 linux x86_64 https://index.docker.io/v1/ 0xc00033eaf0 2 4136153088 [] /var/lib/docker    master1 [provider=digitalocean] false 20.10.6   map[io.containerd.runc.v2:{runc [] <nil>} io.containerd.runtime.v1.linux:{runc [] <nil>} runc:{runc [] <nil>}] runc {  inactive false  [] 0 0 <nil> []} false  docker-init {d71fcd7d8303cbf684402823e425e9dd2e99285d d71fcd7d8303cbf684402823e425e9dd2e99285d} {b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7 b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7} {de40ad0 de40ad0} [name=apparmor name=seccomp,profile=default]  [] [WARNING: No swap limit support]}"
time="2021-06-01T11:53:24Z" level=info msg="Option customConfig=map[address:1.2.3.4 internalAddress: label:map[] roles:[] taints:[]]"
time="2021-06-01T11:53:24Z" level=info msg="Option etcd=false"
time="2021-06-01T11:53:24Z" level=info msg="Option controlPlane=false"
time="2021-06-01T11:53:24Z" level=info msg="Option worker=false"
time="2021-06-01T11:53:24Z" level=info msg="Connecting to wss://rancher/v3/connect with token REDACTED"
time="2021-06-01T11:53:24Z" level=info msg="Connecting to proxy" url="wss://rancher/v3/connect"
time="2021-06-01T11:53:25Z" level=info msg="attempting to stop the share-mnt container so it can reboot on startup"
```

Anyway there are suspicious messages in journal log like `Container 8837d... failed to exit within 10 seconds of signal 15` and `error="read /proc/self/fd/115: file already closed"` where the container_id corresponds to `share-mnt` container:
```
root@master1:~# journalctl -u docker -u containerd
Jun 01 12:13:57 master1 containerd[4089]: time="2021-06-01T12:13:57.608356625Z" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/8837d6ba9dc48ba6a99f1b64491624225
Jun 01 12:14:09 master1 dockerd[5593]: time="2021-06-01T12:14:09.647239538Z" level=info msg="Container 8837d6ba9dc48ba6a99f1b64491624225f074ff741f8bf4ebdbfa72378647b0b failed to exit within 10 seconds of signal 15 - using 
Jun 01 12:14:09 master1 dockerd[5593]: time="2021-06-01T12:14:09.754914077Z" level=info msg="ignoring event" container=8837d6ba9dc48ba6a99f1b64491624225f074ff741f8bf4ebdbfa72378647b0b module=libcontainerd namespace=moby to
Jun 01 12:14:09 master1 containerd[4089]: time="2021-06-01T12:14:09.754777588Z" level=info msg="shim disconnected" id=8837d6ba9dc48ba6a99f1b64491624225f074ff741f8bf4ebdbfa72378647b0b
Jun 01 12:14:09 master1 containerd[4089]: time="2021-06-01T12:14:09.755624263Z" level=error msg="copy shim log" error="read /proc/self/fd/115: file already closed"
```

Reopening as `mnt-share` container keeps restarting.

**Comment by thehejik** [comment]
Exit code 137 mean that the container was killed which would correspond to the notes here https://github.com/rancher/rancher/pull/32662/files#diff-61358711e980ccf505246fd3915f97cbd3a380e9b66f6fa5aad46749968c5ca3R368 

Is it intentional?

**Comment by luthermonson** [comment]
the container is stopped and looks like it sends a sigterm which trips a 137... it doesnt matter as on reboot it will start again. are you 100% sure the share-mnt container keeps restarting as you say? the behavior we expect is for it to start, deploy it's cert payload and then immediately stop itself. sitting with a 137 isn't a problem as long as you can reboot the node and it again comes up, rewrites the files and stops itself again. if you can replicate this pod restarting behavior let's talk in real time and debug it. msg me on slack and we'll work through it. putting back into retest as i'm like 99% sure we're fine here as long as we confirm it's not restarting over and over and over again.

**Comment by slickwarren** [comment]
on master-head (29674d9):
* downstream cluster with 1 all-roles node and 1 worker node -- `share-mnt` exited (137)  -- pass

on 2.5-head (14c8c62a05f364adf85523d0afd54b24d9dc4cda):
* downstream cluster with 1 all-roles node and 1 worker node -- `share-mnt` is restarting, with the `permission denied` error that was originally reported in this ticket. -> will open a new ticket for this

Just as a note, on `2.5.8`, the same use case exits with (0).

**Comment by StrongMonkey** [comment]
Is this reopened for v2.5 or v2.6? The comment says master passed. @slickwarren

**Comment by slickwarren** [comment]
This is reopened for 2.6 (there is a[ backport open for 2.5](https://github.com/rancher/rancher/issues/33039)). I was able to repro this on master-head (d8824a1)

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `ba95a584` and master-head commit id: `c6594d8`**

- Deploy a 2 nodes - 1 all roles + 1 worker node
- wait for the cluster to come up
- The share-mnt on the nodes is in exited status
