### ISSUE TITLE
[GUI][2.5.8]: Secrets Encryption radio buttons on Edit Cluster won't toggle

### ISSUE THREAD

**Issue by rene-demonsters** [rancher/rancher#32737]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Upgrade to Rancher 2.5.8 from 2.4.15 (unsure if this is a requirement)
2. After upgrading, edit a cluster in Cluster Manager
3. Try and enable / disable Secrets Encryption

**Result:**
Both radio buttons can be turned on, can't switch between them:
![image](https://user-images.githubusercontent.com/20322259/118297656-bf4a7780-b4de-11eb-8376-6121bfed2184.png)

**Other details that may be helpful:**
Cluster didn't have Secrets Encryption enabled in the past, the function seems to be new).

I think I've narrowed it down to this section of code:
https://github.com/rancher/ui/blob/b7d30b4ea6108f791ec84ebaa3037bb8349e74f0/lib/shared/addon/components/cluster-driver/driver-rke/template.hbs#L570-L603, but I'm not sure how to fix it. 

There seems to have been some other issues regarding this field during the development of 2.5.x:
https://github.com/rancher/rancher/issues/30555
https://github.com/rancher/ui/blob/b7d30b4ea6108f791ec84ebaa3037bb8349e74f0/lib/shared/addon/components/cluster-driver/driver-rke/component.js#L1326-L1328

**Environment information**
- Rancher version: 2.5.8
- Installation option (single install/HA): Single node docker install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): N/A
- Kubernetes version (use `kubectl version`): 1.18.18-rancher1-1

- Docker version (use `docker version`): N/A

**Comment by Vashiru** [comment]
Seems to only occur on Editing existing clusters. Upon creating new ones it works just fine.
