### ISSUE TITLE
Add possibility to Clone an entire Stack

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#3273]
Right now under Applications > Stacks one is able to clone a single service. As a user I expect to be able to clone the entire Stack. 

This is extremely useful when developing and experimenting a new Stack deployment via the UI, before exporting it and moving it to the file system. 

Cloning a stack is also useful when you want to have a higher degree of HA where two instances of the same Stack are running, scheduled on different Hosts and can be connect to a common Load Balancer.

**Comment by vincent99** [comment]
#2096
