### ISSUE TITLE
[KEv2][AKS] Node pools are deleted for imported clusters

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#32734]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a cluster in AKS.
2. Create an imported AKSClusterConfig in aks-operator

**Result:**

aks-operator will attempt to delete the node pools in the AKS cluster.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cmurphy** [comment]
Fixed in https://github.com/rancher/aks-operator/pull/6

**Comment by prabalsharma** [comment]
tested on aks-operator rc4 via backend
