### ISSUE TITLE
Need support for new machine types in Azure

### ISSUE THREAD

**Issue by ccittadino-ctic** [rancher/rancher#32736]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Use Rancher to provision a cluster in Azure

**Result:**
You are unable to select anything beyond v3 offerings (v4 and v5 should be available by example)

**Other details that may be helpful:**
Already discussed with the Azure SDK owners here: https://github.com/Azure/azure-sdk-for-go/issues/14646#issuecomment-840370967

They state the supported path for machine types is to discover/query them vs the existing hard-coded list.

Discussed this change to Rancher with @dramich who recommended we open this ticket for follow-up.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8
- Installation option (single install/HA): HA

**Comment by ccittadino-ctic** [comment]
This issue has not been addressed and a solution is still needed.

**Comment by ccittadino-ctic** [comment]
This issue has not been addressed and a solution is still needed.

**Comment by christianrowlands** [comment]
This issue has not been addressed and a solution is still needed. I can imagine people will stop using Rancher with Azure if they can't select the newer VM types that are cheaper.
