### ISSUE TITLE
Feature Request: Add vcluster support

### ISSUE THREAD

**Issue by michaelandrepearce** [rancher/rancher#32733]
Feature request:
I would be great if we could using the rancher management, spin up virtual clusters on top of existing physical, vcluster.com was just open sourced by loft which is based itself on k3s it would be great to get this kind of support in rancher natively, so you get a single stop shop, same controls ldap and user experience.

**Comment by michaelandrepearce** [comment]
This is still a request. Also a subscribed customer with an active support rfe ticket for this

**Comment by michaelandrepearce** [comment]
Still a request. Also a customer we have a internal rfe request for this as well.

**Comment by olljanat** [comment]
@ananace FYI. Vcluster recently added support for k0s and vanilla k8s which might help to that issue https://www.vcluster.com/docs/operator/other-distributions

**Comment by michaelandrepearce** [comment]
Ping to unstale

**Comment by iMikeG6** [comment]
If a may, I would also add +1 for this feature. Vcluster is really awsome and adding rancher on top would be a perfect combination. it would also be great to have an option to add securityContext so rancher agent can run on rootless k8s vcluster.

**Comment by stmcallister** [comment]
Hello! I'm a developer advocate over at LoftLabs (creators of vCluster), and I wanted to let everyone in this thread know that we just released an OSS Rancher Integration for vCluster! You can read more about it at the [vcluster-rancher-operator](https://github.com/loft-sh/vcluster-rancher-operator) project as well as the [vcluster-rancher-extension-ui](https://github.com/loft-sh/vcluster-rancher-extension-ui) project.

You can also see it in action in the [vCluster OSS on Rancher: Creating Virtual Clusters in Rancher](https://youtu.be/vom4Lr8VZNY?si=fNO2C5Z1HwXh0Tqd) video on YouTube.
