### ISSUE TITLE
Can't deploy downstream rke2  Custom cluster with dedicated role per node

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32741]
**What kind of request is this (question/bug/enhancement/feature request):**
* bug

**Steps to reproduce (least amount of steps as possible):**
* get rancher command for custom cluster
* run rancher command on 3 different nodes, each with different roles (worker, etcd, cp)

**Result:**
* nodes fail to register with rancher/cluster never comes up active

**Other details that may be helpful:**
* single node deployment with all roles appears to work normally

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):master-head (d7ef41e)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4vcpu, 3 nodes
- Kubernetes version (use `kubectl version`): v1.21.1-alpha4+rke2r1

**Comment by slickwarren** [comment]
this is still an issue on master-head (979d2ba). on a custom cluster, dedicated nodes are not registering.

**Comment by Oats87** [comment]
I can confirm that this also does not work if you specify all 3 roles (`--controlplane --etcd --worker`) on multiple nodes.

**Comment by slickwarren** [comment]
on master-head (629146a) I was able to verify the following using digital ocean as the provider:
* single node cluster
* dedicated node per role
* multi-role per role (all combos of 2 roles)
* downstream HA (all roles, 3 nodes)
* mixed roles per node (some nodes with 1 role, some with 2, some with all 3)
all of the above cases have passed, and are showing as running/active (both nodes and the clusters) in the `cluster management` and `explore cluster` views

Also confirmed with Chris (from above comment) that he was on yesterday's commit (f90b36e)

**Comment by davidnuzik** [comment]
@galal-hussein to look into.

**Comment by anupama2501** [comment]
Verified on master-head 5e9c776 
**Rancher Single install** 
1. From the explorer --> created a custom cluster 
2. Ran the registration command from the custom cluster on 3 different AWS instances with 1 role on each node
3. The nodes have registered with the cluster and the cluster has come up active

**Comment by slickwarren** [comment]
https://github.com/rancher/rancher/pull/32946
