### ISSUE TITLE
[Logging v2] Update to upstream 3.10.0

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#32748]
Source: https://github.com/banzaicloud/logging-operator/tags

**Comment by cbron** [comment]
This should be 2.6 with a potential backport later, I'll move.

**Comment by nickgerace** [comment]
Talked to @paynejacob, and since 3.10.0 primarily solves bug issues, we will upgrade to 3.10.0 instead of 3.9.5.

**Comment by izaac** [comment]
Rancher version `2.6 master-head (06/09/2021)` _97ca638_

Most of the P1 tests were done while testing this k3s issue https://github.com/rancher/rancher/issues/32993 (SELinux CentOS 7.9, CentOS 8.3, non-SELinux Alpine 3.13)
Further testing was done on RKE1 in this build too. Non-SELinux CentOS 7.9

I will do sanity check on other providers next. (GKE, EKS, rke2)

**Comment by izaac** [comment]
Rancher version `2.6 master-head (06/09/2021)` _97ca638_

Sanity checks done on 
RKE2 -> `v1.21.1-rc2+rke2r1`
GKE -> `v1.19.9-gke.1900`
EKS -> `v1.19.8-eks-96780e`
AKS -> `v1.19.9`
