### ISSUE TITLE
immutable infrastructure and stack template compliancy, how to see diff of Stack versions

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#3274]
Some of the great benefits of docker is that it makes it possible to achieve the benefits of immutable infrastructure. With Rancher we can avoid users to access the host directly and make changes to hosts, which will eventually conflict with the dev/prod parity principles. We can achieve this by allowing devops to deploy "Stacks" either directly via the Rancher CLI or via the Rancher Catalog.

One issue we have encountered with the current Rancher is that although you can run a Stack as defined in a version control system, a member of an environment is still able to modify the Stack at any moment, adding new services and changing the scale. When this happen there is no easy way to detect it. Users may add a new service or a new container, or you do some quick fixes after a service disruption. Right now one has to export manually the Stack config and do a diff against the original stored in git. 

As a Rancher environment admin, I would like to be able to see Diff of the original Stack version (when it was first created) against the new changes made via the Rancher UI. I expect to see this on the Applications > Stack page, maybe under the stack menu something called "View history of changes" with a diff possibility among the changes done. Maybe this can be created by using the new Audit Log. I would also like to see a visual marker on the Stack that have changed from what is defined in a Catalog.

**Comment by sorenroug** [comment]
When I use rancher-compose I basically have to a webbrowser open to the rancher GUI as well. There is no `rancher-compose ps` and I can't see via rancher-compose if sometime in the past someone have modified the stack via the GUI. There is no `rancher-compose diff docker-compose.yml`

It would also be nice to know if a service has restarted in the last 24 hours.

**Comment by will-chan** [comment]
Closed due to inactivity.
