### ISSUE TITLE
v2 cluster nodepools IP should have externalIP only and not None for the external IP

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#32758]
On master-8c014efa85314ab1cb1cb79261d2db9251ccf31d-head

1. Create a cluster on the rancher server 1 node al roles enabled
2. Once the node is active, from explorer --> EXPLORE CLUSTER --> Select the cluster created and from cluster dropdown --> nodes --> Verify the external IP is None and internal IP is displayed. The IP displayed in the cluster is external IP 
3. Only external IP should be visible and None can be removed with internal IP option removed in the header

<img width="600" alt="Screen Shot 2021-05-10 at 5 39 29 PM" src="https://user-images.githubusercontent.com/38144301/117741501-81d0ac00-b1b7-11eb-8188-a9eb2fc00ff0.png">

**Comment by deniseschannon** [comment]
It would be helpful if we could see the `yaml` of the cluster object when filing issues to see if it's a UI or backend issue.

**Comment by anupama2501** [comment]
@deniseschannon cluster yaml : 
[anupam-multietcd.txt](https://github.com/rancher/rancher/files/6542802/anupam-multietcd.txt)

**Comment by deniseschannon** [comment]
Can you re-test this as well as show what the yaml is for the node object on the page? 

The cluster.yml doesn't help me show what the node object actually is.

**Comment by anupama2501** [comment]
Verified on b2f8824
1. Create a node driver rke2 cluster from explorer
2. Once the cluster is active, verified the cluster shows the IP value and not None for External/Internal IP from explore cluster --> cluster --> nodes 


node object yaml:

[anupama-auditlog-ndriver-c1.txt](https://github.com/rancher/rancher/files/6605669/anupama-auditlog-ndriver-c1.txt)
