### ISSUE TITLE
Stack is King, make it more visible

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#3275]
**motivation**
The Stack is the most important artifact imo for Rancher. It represents the "application" we want to run, what we devops care about. Hosts are important too...but not the same level, eventually hosts should be much less prominent from the user experience. 

**specific issues and proposals for UI improvements**
On the Hosts page, stacks  are kind of difficult to identify ... with the current design it is difficult to see how a certain stack is spread across hosts. 
1. I would like to easily select a Stack from the hosts page (maybe a select menu from the top) and get it highlighted across the hosts. 
2. on the hosts page, I want to be able to click on a specific Stack heading (right now it is just a light gray header) and be redirected to the Stack page.
3. I find it also quite annoying that when clicking on a container that belongs to a Stack, the upper part "that remind on a site breadcrumb" now shows the Host. Also when navigation via the Stack, drilling down to a container you end up in the host From a user perspective a container belongs more to a Stack and not to a Host (infact it can be moved at any point to any other host).

**Comment by sshipway** [comment]
+1 for this, especially (2) and (3) which have been annoying to me several times.

For (1), how about being able to click on an icon on a stack header on one host, and all corresponding stack headers are highlighted over all hosts.  The hosts screen is very chaotic and it is hard to identify easily how a stack is spread.

**Comment by tfiduccia** [comment]
So what did we do?

**Comment by vincent99** [comment]
None of those things, as far as I can remember?

**Comment by will-chan** [comment]
Closed due to inactivity.
