### ISSUE TITLE
Vpshere downstream clusters use incorrect hardware sizes when creating with content library template

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32761]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* configure node template for vsphere using content library for creation method
  * specify non-default hardware (cpu/memory) i.e. 4vCPU, 4GB Memory

**Result:**
* nodes use default value (perhaps from the template in the content library?) instead of values specified by rancher
<img width="702" alt="Screen Shot 2021-05-17 at 9 36 47 AM" src="https://user-images.githubusercontent.com/16691014/118525255-d31af700-b6f3-11eb-89f7-ad6b6402907f.png">
<img width="123" alt="Screen Shot 2021-05-17 at 9 36 34 AM" src="https://user-images.githubusercontent.com/16691014/118525258-d3b38d80-b6f3-11eb-878e-54b5ca635a21.png">

**Other details that may be helpful:**
hardware specs from rancher appear to be used correctly when using a datacenter creation method/template

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (5d2b7ac)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Vsphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4vCPU, 4GB Ram
- Kubernetes version (use `kubectl version`): v1.20.6

**Comment by ansilh** [comment]
Created PR https://github.com/rancher/machine/pull/128 to address this issue.
