### ISSUE TITLE
[KEv2][UI] Set string fields to "" on create

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#32770]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

This isn't reproducible right now, this is in anticipation of merging fixes to https://github.com/rancher/rancher/issues/32440.

For GKE, the fields `gkeConfig.clusterIpv4Cidr` and `gkeConfig.maintenanceWindow` need to send `""` instead of `null` if left unset. Otherwise, once changes are merged in Rancher, cluster create will fail with an error like "Field [clusterIpv4CidrBlock] cannot be nil for non-import cluster [c-ztz6q]".

The same needs to be done for any string fields for EKS that are currently sending `null` by default instead of `""`.

**Result:**

**Other details that may be helpful:**

Original issue: https://github.com/rancher/rancher/issues/32440

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by prabalsharma** [comment]
tested on master-629146a3fbbc8d5677aecece78e627580dd7c95d-head
