### ISSUE TITLE
Rancher chart README references auditLog.maxBackups not auditLog.maxBackup

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#32773]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

The Rancher chart README at https://github.com/rancher/rancher/tree/master/chart references the option auditLog.maxBackups, which should be auditLog.maxBackup per the [values.yaml](https://github.com/rancher/rancher/blob/master/chart/values.yaml) and [deployment.yaml template](https://github.com/rancher/rancher/blob/master/chart/templates/deployment.yaml).

**Comment by pgdagenais** [comment]
We could maybe also integrate this other change: https://github.com/rancher/rancher/pull/32429

The `extraAnnotations` values doesn't match the readme also.
