### ISSUE TITLE
Fleet is applying git repo yamls in the alphabetical order

### ISSUE THREAD

**Issue by BrundaBS** [rancher/rancher#32772]
Hi Team,

 Fleet is making a list of resources in the bundle yaml based on the alphabetical order of yaml files from the git repo. Creation of the resources is also following the same order mentioned in the fleet bundle.  For example,

Git repo contains :-
Deployment.yaml
Namespace.yaml

Fleet is trying apply the Deployment yaml(Alphabetical order) first and it is failing because namespace doesn't exist. Even though namespace creation yaml is present.
 
Is there any specific reason behind this way of execution? 
 
 Fleet version - 0.3.5
 Rancher version - 2.5.8

**Comment by atsai1220** [comment]
Try separating them into different paths that result in different Bundles so they ultimately reconcile.
