### ISSUE TITLE
EKS Support for node taints on managed groups

### ISSUE THREAD

**Issue by vkruoso** [rancher/rancher#32781]
Looks like AWS released an update for managed node groups that now supports node taints.
https://aws.amazon.com/about-aws/whats-new/2021/05/amazon-eks-managed-node-groups-adds-support-kubernetes-node-taints/?nc1=h_ls

This feature request is to add it to Rancher managed EKS clusters and the terraform provider.

**Comment by jmatsushita** [comment]
Is it the case that this feature would need to be implemented in https://github.com/rancher/eks-operator ? Would it be possible to enable issues on the eks-operator repo or should they be posted here?

**Comment by MAXxATTAXx** [comment]
This will be a very helpful addition. GKE taints seem to be supported but not eks. Is there any workaround that can be applied currently?

**Comment by neerajjose** [comment]
This would be really a helpul feature. Can we have this??
