### ISSUE TITLE
custom cluster unable to register nodes from ec2 as non-root user

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32786]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy some nodes on ec2 (open-all security group)
* get rancher run cmd for RKE2 cluster
* run cmd on ec2 nodes

**Result:**
* nodes never register with rancher 
* tried with dedicated nodes per role, all roles for a single downstream node

**Other details that may be helpful:**
related: https://github.com/rancher/rancher/issues/32785

from the logs 
```
[INFO]  Generating Cattle ID
sh: 463: cannot create /etc/rancher/agent/cattle-id: Directory nonexistent
curl: (23) Failed writing body (0 != 1404)
[INFO]  Successfully downloaded Rancher connection information
[INFO]  systemd: Creating service file
sh: 283: cannot create /etc/systemd/system/rancher-system-agent.service: Permission denied
[INFO]  Creating environment file /etc/systemd/system/rancher-system-agent.env
tee: /etc/systemd/system/rancher-system-agent.env: Permission denied
Failed to reload daemon: Interactive authentication required.
[INFO]  Enabling rancher-system-agent.service
Failed to enable unit: Interactive authentication required.
[INFO]  Starting/restarting rancher-system-agent.service
Failed to restart rancher-system-agent.service: Interactive authentication required.
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (55f0bb2) and (f6c1d82)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): v1.21.1-alpha4+rke2r1

**Comment by kinarashah** [comment]
https://github.com/rancher/docs/issues/3285

**Comment by slickwarren** [comment]
on master-head () I still have a similar issue. I am using an ec2 node with open-all security group
```
[INFO]  Role requested: etcd
[INFO]  Role requested: controlplane
[INFO]  Role requested: worker
[INFO]  Using default agent configuration directory /etc/rancher/agent
[INFO]  Using default agent var directory /var/lib/rancher/agent
mkdir: cannot create directory ‘/var/lib/rancher’: Permission denied
mkdir: cannot create directory ‘/etc/rancher’: Permission denied
[INFO]  Successfully downloaded CA certificate
[INFO]  Value from https://<rancher_ip>/cacerts is an x509 certificate
[INFO]  Successfully tested Rancher connection
[INFO]  Downloading rancher-system-agent from https://<rancher_ip>/assets/rancher-system-agent-amd64
curl: (23) Failed writing body (0 != 934)
[INFO]  Successfully downloaded the rancher-system-agent binary.
chmod: cannot access '/usr/bin/rancher-system-agent': No such file or directory
sh: 440: cannot create /etc/rancher/agent/config.yaml: Directory nonexistent
sh: 449: cannot create /etc/rancher/agent/config.yaml: Directory nonexistent
[INFO]  Generating Cattle ID
sh: 463: cannot create /etc/rancher/agent/cattle-id: Directory nonexistent
curl: (23) Failed writing body (0 != 1032)
[INFO]  Successfully downloaded Rancher connection information
[INFO]  systemd: Creating service file
sh: 283: cannot create /etc/systemd/system/rancher-system-agent.service: Permission denied
[INFO]  Creating environment file /etc/systemd/system/rancher-system-agent.env
tee: /etc/systemd/system/rancher-system-agent.env: Permission denied
Failed to reload daemon: Interactive authentication required.
[INFO]  Enabling rancher-system-agent.service
Failed to enable unit: Interactive authentication required.
[INFO]  Starting/restarting rancher-system-agent.service
Failed to restart rancher-system-agent.service: Interactive authentication required.
See system logs and 'systemctl status rancher-system-agent.service' for details.
```

**Comment by ibuildthecloud** [comment]
@slickwarren I believe the issue is that you are running the custom command as non-root.  Can you try running as root.  We are going to add a root user check in the script.

**Comment by ibuildthecloud** [comment]
https://github.com/rancher/system-agent/pull/15

**Comment by slickwarren** [comment]
running the command as root does get past this error and the cluster can get to an active state in the UI (on master-head 979d2ba).  Updated this ticket's title to reflect this.

**Comment by slickwarren** [comment]
this command is from master-head (f90b36e):
```curl -fL https://<ip>/system-agent-install.sh |  sh -s - --server https://<ip> --token <token> --ca-checksum <checksum> --etcd --controlplane --worker```
which does now include a warning if the user doesn't run as sudo.  However, the RKE1 command just includes `sudo` in the copied command.  I think that should be added here as well
example from rke1 custom command:
```sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:master-f90b36efb4cf50088e63e081e359ddd9b94c8ecf-head --server https://<ip> --token <token> --ca-checksum <checksum> --worker```

**suggested fix**
add `sudo` to the command that the user copies from rancher
