### ISSUE TITLE
Ability to ssh into existing machine and launch rancher/agent

### ISSUE THREAD

**Issue by RVN-BR** [rancher/rancher#3278]
I think the title says it all/most...

I think it could be useful to provision from rancher server to a machine via SSH (basically it would SSH to the machine and run the rancher agent...)  This can potentially help with IP address problems many of us are seeing where Rancher is not obtaining the correct IP of the host (and must be overriden by CATTLE_AGENT_IP manually on each deploy...)

SSH could support either user/pass or ssh keys for login...  I see this mostly useful for local datacenters I guess, but could be useful for other cloud providers where a real API isnt supported yet....

**Comment by vincent99** [comment]
We tried this in 2.x alias and the experience was not good for various reasons, so we don't intend to support this again.
