### ISSUE TITLE
Istio 1.10+

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#32795]
https://istio.io/latest/news/releases/1.10.x/announcing-1.10/

(not a known security/CVE release)

**Comment by brendarearden** [comment]
This is available for testing in the dev-v2.6 branch. rancher-istio v100.0.0 (this installs istio 1.10.2) and rancher-kiali-server v100.0.0 (this install kiali 1.35.0)

**Comment by anupama2501** [comment]
Verified fresh install cases istio `v1.10.2`, kiali `v1.35.0`

Create a downstream node driver with 3 worker, 1 etcd, 1 cp

**P1 case:**

- Install monitoring 14.5.10 and istio by enabling jaeger and kiali
- Deploy book demo app in istio enabled namespace
- Verified from kiali the traffic from the book demo app - looks good
- Verified the jager traces for the bookdemo app - looks good
- For kiali verified the url set for in_cluster_url from apps & marketplace → istio → components → edit as yaml → in_cluster_url: 'http://tracing.istio-system.svc:16686/jaeger```
- Verified in kiali --> services --> default namespace --> traces and inbound metrics no errors are seen

**Ingress gateway:**

- istio with ingress gateway and kiali enabled and the custom overlay file with ingress-gateway yaml file and modified ingress-gateway yaml.
- Deploy book demo app
- verified the traffic in kiali goes through the ingress gateway provided

**Egress gateway:**

- Enable Istio with the egress gateway and Kiali options selected
- Create a namespace and enable istio-injection by adding the istio-injection=enabled label
- Apply the egress test yaml to the namespace in your cluster:
` kubectl apply -n testns-dos -f egressgateway.yaml`
- Deploy a workload with image ranchertest/mytestcontainer to the created namespace
- Exec into the pod for the deployed workload and run the command:
`curl -sL -o /dev/null -D - http://edition.cnn.com/politics`
- Verified the traffic in kiali and see the cnn go through egress gateway

**Comment by anupama2501** [comment]
Blocked on upgrade test https://github.com/rancher/rancher/issues/33737

**Comment by anupama2501** [comment]
Verified master-head 21ab02c

Upgrade from istio v1.9.600,kiali 1.32.100 to v1.10.2, kiali 1.35.00

Test1: 
1. Installed v1.9.600 and deployed book demo
2. Upgraded to v1.10.2 and redeployed weight based - works as expected

Test2:
1. Installed istio 1.9.600 with overlay file provided - deployed book demo
2. Upgraded to 1.10.2 with modified overlay file - verified kiali and jaeger work fine
3. Deployed weight based demo - works as expected

Test3:
1. uninstalled istio and re-installed v1.9.600 and deployed book demo
2. Before upgrading removed kiali-crd and upgraded to v1.10.2  by enabling kiali - verified kiali is installed 
3. Deployed weight based demo, works as expected
4. Updated istio by enabling egress-gateway and verified traffic through egress gateway

Ran upgrade from istio v1.8.600 to v1.10.2 and ran test1 - works as expected
