### ISSUE TITLE
Roles show up incorrectly in Rancher, but are correct when viewed in kubectl for nodes with mixed/dedicated roles per node

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32799]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* deploy a downstream RKE2 cluster with dedicated nodes per role

**Result:**
* roles show up only as `all` or `etcd` but should have independent roles
* cluster below has 2control plane, 3etcd, 3workers
<img width="1799" alt="Screen Shot 2021-05-19 at 1 46 11 PM" src="https://user-images.githubusercontent.com/16691014/118886502-dd80f080-b8ad-11eb-8651-0153572c4ad9.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (55f0bb2)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 2vCPU
- Kubernetes version (use `kubectl version`):v1.21.1-alpha4+rke2r1

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/32654
