### ISSUE TITLE
Audit ETCD backup logs 

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#32794]
Rancher 2.4.8 and 2.5.8

When running a large setup (hundreds of RKE clusters) there are many `etcd backup` logs. They should be audited to determine if some/all can be moved to debug/removed/condensed.

**Comment by Jono-SUSE-Rancher** [comment]
@superseb - Can you sync up with @dramich to better understand the finer details here and then tackle this for your next up?

**Comment by anupama2501** [comment]
Verified on master-29286fc23aadd0e636e3ca85b86e5397df1f180a-head

Created a cluster on ember UI and verified the rancher logs while backups are created and see that logs for backup moved to Debug:
`2021/05/24 22:57:17 [DEBUG] [etcd-backup] checking backups for cluster [local]`
`2021/05/24 22:57:17 [DEBUG] [etcd-backup] checking backups for cluster [c-bkzzv]`
`2021/05/24 23:22:17 [DEBUG] [etcd-backup] cluster [c-g56gc] has no backups, creating first backup`
`2021/05/24 23:22:17 [DEBUG] [etcd-backup] cluster [c-gsgtn] has no backups, creating first backup`
`2021/05/24 23:22:17 [DEBUG] [etcd-backup] cluster [c-g56gc] new backup is created: c-g56gc-rl-5mwnt`
`2021/05/24 23:22:17 [DEBUG] [etcd-backup] cluster [c-gsgtn] new backup is created: c-gsgtn-rl-tv6d7`
