### ISSUE TITLE
Error for Host registration does not go away

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3280]
version - master jan 14th

Steps:
1.  Create a new build
2.  Try to add a host for the first time
3.  In Host Registration URL click on Something else radio button but don't put anything in it.
4.  Click on Save (this will bring up Please provide a DNS name or IP address
5.  Click on cancel.
6.  Now try to add a host again or go to the setting page

Results:
The error is still there.  This happens in settings page as well.

Expected:
Error should clear once you leave the page.

**Comment by vincent99** [comment]
I think this is gone now with @westlywright converting them to components.

**Comment by tfiduccia** [comment]
Version - master 3/8
Verified fixed
