### ISSUE TITLE
Allow user to disable fleet gitops in 2.6

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#32808]
Rancher has feature flag fleet in 2.5, which can be disabled. In 2.6 fleet is required as part of provisioing process and can't be disabled. However the gitops part of fleet can be disabled since it is not used internally by provisioning. We need to add ability to allow user to disable fleet gitops.

**Comment by SheilaghM** [comment]
Daishan was working on this and almost done. Seemed sensible to let him finish.

**Comment by StrongMonkey** [comment]
Rancher 2.6 will be adding a new feature flag called `continous-delivery`. This contains the gitops feature of fleet.
1. For rancher 2.6, `fleet` feature is required to be turned on. `continous-delivery` is turn on by default too, and can be disabled if user doesn't want gitops feature of fleet.

2. For upgrade from rancher 2.5:

a). If user has `fleet` feature turned **on** in 2.5 and upgrade to 2.6, nothing will change. Both `fleet` and `continous-delivery` will be turned on

b) If user has `fleet` feature turned **off** in 2.5 and upgrade to 2.6. `fleet` feature will be forced to turned on since it is required. `continous-delivery` feature will be set to false.

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (06/15/2021)` _2b50005 _
Rancher HA RKE1
Fleet `100.0.0+up0.3.6-rc2`
UI Issue found when the feature is disabled: https://github.com/rancher/dashboard/issues/3246

I was able to deploy with the feature flag enabled and disabled with helm.
When the feature is `disabled` after helm install I am still able to provision `rke2` clusters (DO).

Will continue testing of Upgrade paths.

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (06/15/2021)` _2b50005_

### Upgrades

Upgrade from 2.5.8 to master-head Default values (rke2 provisioning works) - PASS
Upgrade from 2.5.8 to master-head with options set to true (fleet and continuous-delivery) - PASS

### Pending Upgrade scenarios


Upgrade from 2.5.8 (Fleet disabled) to master-head with defaults (expecting `fleet` and `continuous delivery` _enabled_)
Upgrade from 2.5.8 (Fleet disabled) to master-head with `continuous delivery` disabled (expecting `fleet` _enabled_ and `continuous delivery` _disabled_)


I am doing an RKE2 provisioning as sanity check but that's blocked by: https://github.com/rancher/rancher/issues/33207

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (06/16/2021)` __

Ran into this known issue during upgrade I just had to wait some time until the old fleet controller was removed and the new fleet controller was installed.
https://github.com/rancher/fleet/issues/419

###  Upgrades

Upgrade from 2.5.8 (Fleet disabled) to master-head with defaults (expecting `fleet` and `continuous delivery` _enabled_) - PASS
Upgrade from 2.5.8 (Fleet disabled) to master-head with `continuous delivery` disabled (expecting `fleet` _enabled_ and `continuous delivery` _disabled_) - PASS


Sanity check: Provisioning RKE2 after upgrade worked. RKE2 DO
