### ISSUE TITLE
After adding catalog or changing virtual machine and saving, it takes me off of settings page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3281]
Version - master jan 14

Steps:
1.  Go to setting
2.  Change anything on the page and click save

Results:
Takes you off settings page and back to page you were on previously

Expected:
Should stay on settings page.

**Comment by vincent99** [comment]
This should no longer be relevant now that each setting section has it's own save..

**Comment by tfiduccia** [comment]
Version - master 3/8
Verified fixed
