### ISSUE TITLE
Rancher pods are not cleaned up on rollback from master to v2.5.8

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#32813]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Bring up a Rancher `v2.5.8` setup.
Deploy a downstream cluster.
Upgrade the setup to `master-head` (`version f6c1d82` was used during testing)
Verify Rancher pods are created in downstream cluster. (Image: `rancher/rancher:master-f6c1d829f5f074edf1a0a46ca1903c17ba7ce3bd-head`)
Rollback the setup to Rancher `v2.5.8`

**Result:**
Rancher pods are not deleted. Pods still use image: `rancher/rancher:master-f6c1d829f5f074edf1a0a46ca1903c17ba7ce3bd-head`.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  v2.5.8
- Installation option (single install/HA): single install

**Comment by deniseschannon** [comment]
We need to add in behavior for the Rancher to remove itself based on the following conditions:

* mcm agent feature flag is enabled - within the Rancher server pod inside the downstream cluster 
* Finds a cluster agent that is 2.5.x or earlier - on the downstream cluster

If these conditions are met, we should kick off a helm remove of the Rancher server helm chart using the catalog v2 code. By using the catalog v2 code, it will launch a pod that will call the helm operation to remove the Rancher server helm chart, which will remove the Rancher pod

**Comment by deniseschannon** [comment]
As we are removing the Rancher pod deployment this will no longer be an issue.

**Comment by aaronRancher** [comment]
Moving back "To-Test" until this issue is resolved: https://github.com/rancher/rancher/issues/33221

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5.8` on upgrade to `master-head` `version ad099ee` with the following steps:
Bring up a Rancher `v2.5.8` setup.
Deploy a downstream cluster.
Upgrade the setup to master-head (version ad099ee was used during testing)
Verify Rancher pods are not created.
Rollback the setup to Rancher v2.5.8

On upgrade to `master-head`, rancher pods are not seen on downstream clusters. Rancher pods are not seen on rollback to `v2.5.8`.
