### ISSUE TITLE
cert-manager 1.0.4 fails to install on rke1 hardened cluster configured cis-1.5 compliant

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32823]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Create an RKE cluster with nodes/kubernetes cis-1.5 compliant (See [doc](https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.4/hardening-2.4/))
- Install cert-manager (step 4 in the [docs](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/))

**Result:**

`Error creating pods`

```Events:
  Type     Reason        Age                   From                   Message
  ----     ------        ----                  ----                   -------
  Warning  FailedCreate  50s (x17 over 6m18s)  replicaset-controller  Error creating: pods "cert-manager-6d87886d5c-" is forbidden: PodSecurityPolicy: unable to admit pod: []
```

**Other details that may be helpful:**
Related: https://github.com/rancher/rancher/issues/29696

**Environment information**
- Rancher version: NA
- Installation option: 3 node RKE1

**Comment by sowmyav27** [comment]
On 2.5.8 using cluster.yml for RKE local cluster from here - https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.5/1.6-hardening-2.5/, no error is seen. HA setup of Rancher is deployed successfully

**Comment by sowmyav27** [comment]
Closing based on https://github.com/rancher/rancher/issues/32823#issuecomment-852729565
