### ISSUE TITLE
Broken again (Upping a service after forcefully removing not longer works #3037)

### ISSUE THREAD

**Issue by dsvmacdonald** [rancher/rancher#3282]
Removing of Stack Name is broken again in Rancher v0.51.0 and Rancher Compose v0.7.0.

Original issue #3037.
Workaround mentioned in #3037 still valid.

**Comment by deniseschannon** [comment]
The issue in #3037 was that if you had an old service that was removed but still in your DB, adding a service with the same name was throwing the "notunique" error.

Can you provide the rancher-compose error that you see this time?

**Comment by deniseschannon** [comment]
@dsvmacdonald Closing this issue as I haven't heard back. If you are still having issues, can you provide more information and re-open?
