### ISSUE TITLE
Feature chart versions are not showing up on refresh 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#32836]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. From the dashboard create a cluster with 1 node all roles DO rke1
2. Install monitoring from explore cluster --> apps and market place --> monitoring
3. While installing istio into the system project verify from the dropdown the versions are not seen.
Screenshot for reference 
<img width="349" alt="Screen Shot 2021-05-21 at 2 41 53 PM" src="https://user-images.githubusercontent.com/38144301/119204459-54eb8700-ba4a-11eb-9a69-c603dc0b9a81.png">
4. Refresh the repository from charts --> chart repositories and rancher and the versions still don't show up

**Other details that may be helpful:**
Workaround: 
Delete the repositiory and re-upload, chart versions will be shown in the istio dropdown:
<img width="1514" alt="Screen Shot 2021-05-21 at 3 39 42 PM" src="https://user-images.githubusercontent.com/38144301/119205078-12c34500-ba4c-11eb-8ddf-8f6c271e3863.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8
- Installation option (single install/HA): Single 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure provider DO 1 node all roles and Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 8GB ram, 4vcpus

**Comment by cbron** [comment]
I repurposed this issue so it was generic, istio is just an example, this was one of our first OOB releases.

**Comment by anupama2501** [comment]
Waiting on https://github.com/rancher/rancher/issues/33665 to verify the ticket.

**Comment by anupama2501** [comment]
Verified on master-head 9e0d1b2

Istio OOB version v1.9.600 shows up in the list of versions
Installed istio - works fine
