### ISSUE TITLE
Can still see deleted services in link drop-down

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3283]
version - master 01/14

Steps;
1.  Create a service and call it service1
2.  Create another service and call it service2
3.  Delete and wait for service1 to be completely removed from the ui
4.  Edit service2 and click on Link drop-down (or create a new service)

Results:  service1 still exists.  It will eventually be removed, but everywhere else it in the UI it's gone.  It should also be removed from list of service links

**Comment by RVN-BR** [comment]
AFAIK its just some cache or something... in my expeience its usually out within 60s...  

Is there a focused effort on ironing out all these UI issues, imHo there are other areas of problems/features more important?

**Comment by vincent99** [comment]
@RVN-BR tfiduccia is the UI QA; that's her job.

**Comment by RVN-BR** [comment]
ooops.... sorry abt that then! :+1: right on catching all the little things :)
