### ISSUE TITLE
Allow for PNI to be enabled for GKE clusters

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#32832]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Result:**
When provisioning a GKE cluster or registering an existing GKE cluster, users should be able to select an option that will enable PNI

**Other details that may be helpful:**
GKE cluster provisioning has an option that allows for specifying "Enable Network Policies". This will cause the cluster to provisioned with the Calico CNI, which supports NetworkPolicy resources. GKE cluster provisioning should be enhanced to toggle this during provisioning if PNI is selected.

**Comment by aaronRancher** [comment]
UI validation and toggle for `Network Policy for Nodes` has been done as part of: https://github.com/rancher/rancher/issues/33026

Tested on Rancher `master-head` `version 5b0da3d`.
Create a GKEv2 cluster with PNI enabled.
After cluster is available, the following network policies are seen:
```
> kubectl get networkpolicies -A
NAMESPACE             NAME                   POD-SELECTOR   AGE
cattle-fleet-system   default-allow-all      <none>         31m
cattle-system         np-default-allow-all   <none>         30m
default               hn-nodes               <none>         30m
default               np-default             <none>         30m
kube-node-lease       np-default-allow-all   <none>         30m
kube-public           np-default-allow-all   <none>         30m
kube-system           np-default-allow-all   <none>         30m
```
Network policies are created in new namespaces in default/new projects:
```
kubectl get networkpolicies -n testns
NAME         POD-SELECTOR   AGE
hn-nodes     <none>         4s
np-default   <none>         4s
```

The same behavior is seen on an imported GKE cluster with PNI enabled.
