### ISSUE TITLE
Failed to get System Project ID: failed to find any cattle system project

### ISSUE THREAD

**Issue by helloworldff** [rancher/rancher#32848]
*Describe your issue here*

nothing change, rancher  gave me this：
当前集群状态 Error.
Failed to get System Project ID: failed to find any cattle system project
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.7` UI: `v2.5.6` |
|Route|`undefined`|

**Comment by denwork** [comment]
I also have the problem. The rancher in AKC and the version is v1.18.8-aliyun.1
I'm tring to install monitor get the error.
