### ISSUE TITLE
Stop button in stack is not working depending on the state of services

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3284]
version - master 01/14

Steps:
1.  Add a service with the mysql image, do not start it
2.  Add a service alias and link it to the sql image service
3.  Start the service alias, after it starts, start the service
4.  Either from the main stack page or stack details page, click on stack's main Stop Services button

Results:  Nothing happens.  I do get a POST http://130.211.140.246:8080/v1/environments/1e10/?action=deactivateservices 500 (Internal Server Error) in dev tools.

Expected:  Button should work.

**Comment by RVN-BR** [comment]
I'm seeing a similar but not identical issue...  The "stop stack" button doesnt work on any of our stacks (where they did before).  Even a stack with a single service.  The Stop next to the service *does* work...

Rancher is returning {"id":"97195240-9e60-4d77-ad16-de13070469f4","type":"error","links":{},"actions":{},"status":500,"code":"Internal Server Error","message":"Internal Server Error","detail":null} when the UI calls http://172.17.8.101:8080/v1/environments/1e1/?action=deactivateservices

**Comment by deniseschannon** [comment]
There is bug in the validation of the service states when stopping stacks that needs to be corrected.

**Comment by tfiduccia** [comment]
Version - master 2/18
Verified fixed - will be in next build
