### ISSUE TITLE
new cluster status showing provisioning and never be active since deployment of new cluster and wworker node registration

### ISSUE THREAD

**Issue by sriazcloud** [rancher/rancher#32846]
*Describe your issue here*
new cluster status showing provisioning and never be active since deployment of new cluster and wworker node registration

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.8` UI: `v2.5.8` |
|Route|`undefined`|

**Comment by superseb** [comment]
Please describe your issue in more detail and provide screenshot of the cluster status and logging to help diagnose the issue. What type of cluster did you create, what actions did you take, what error is shown (if any), what node(s) did you add with what role, what is the logging in the `rancher/rancher` container in the setup and in the `rancher/rancher-agent` container on the node?
