### ISSUE TITLE
[ERROR] Failed to connect to peer wss://192.168.69.224/v3/connect [local ID=192.168.195.165]: websocket: bad handshake

### ISSUE THREAD

**Issue by sandeep-sarpe** [rancher/rancher#32845]
I have installed Rancher 2.4.8 using helm chart on k3s cluster. 

I am getting below error on rancher agent
[ERROR] Failed to connect to peer wss://192.168.69.224/v3/connect [local ID=192.168.195.165]: websocket: bad handshake

I did the networking tests according to https://rancher.com/docs/rancher/v2.x/en/troubleshooting/networking/
The tests are passed successfully on master and slaves. 
Also, check MTU configurations. I set them all to 1450

But still getting the above error. Please advise. Thanks in advance!

**Comment by superseb** [comment]
Please share the full log, is it showing continuously or just once? Do you have any other functional issues besides this log line? Keep in mind 2.4.8 is over 6 months old already. (if you didnt mistype for 2.5.8)
