### ISSUE TITLE
RKE2 provisioning multinode cluster fails to provision as one of the nodes stuck in waiting for infra state

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#32856]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a node driver rke2 cluster with 3 etcd nodes, 2 cp+ worker nodes
2. All of the nodes in the cluster are active except for the 1 node with role etcd stuck in "waiting for Infra" as a result the cluster is stuck in provisioning.
3. On the ember UI --> cluster is seen active with the rest 4 nodes that are active

**Result:**
Cluster has failed to come up active and stuck in provisioning
<img width="600" alt="Screen Shot 2021-05-24 at 12 37 11 PM" src="https://user-images.githubusercontent.com/38144301/119398740-d16da800-bc8c-11eb-835e-305e5e5ccbf5.png">

**Other details that may be helpful:**
This issue is not seen always. I created another cluster with 3 etcd nodes and 2 cp+ worker nodes and see the cluster has come active.

Some errors in the rancher logs:
```
2021/05/24 19:06:54 httputil: ReverseProxy read error during body copy: tunnel disconnect
W0524 19:06:54.899342       7 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.ServiceAccount ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0524 19:06:54.899453       7 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Deployment ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0524 19:06:54.899532       7 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1beta1.CronJob ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0524 19:06:54.899633       7 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1beta1.Ingress ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
```

```
2021/05/24 18:24:16 [TRACE] secretsController: AddHandler: obj [anu-explorertest-rke-state] is not in cluster [c-m-5c138119], returning nil
2021/05/24 18:24:16 [TRACE] secretsController: AddHandler: obj [anu-explorertest-bootstrap-template-dqp2b-machine-bootstravf95w] is not in cluster [c-m-5c138119], returning nil
2021/05/24 18:24:16 [TRACE] secretsController: AddHandler: obj [anu-explorertest-bootstrap-template-dqp2b-machine-plan] is not in cluster [c-m-5c138119], returning nil
2021/05/24 18:24:16 [TRACE] secretsController: AddHandler: obj [anu-explorertest-bootstrap-template-dqp2b-machine-plan-tokhxxlz] is not in cluster [c-m-5c138119], returning nil
2021/05/24 18:24:16 [TRACE] secretsController: AddHandler: obj [anu-explorertest-bootstrap-template-dqp2b-machine-plan] is not in cluster [c-m-5c138119], returning nil
2021/05/24 18:24:16 [TRACE] secretsController: AddHandler: obj [anu-explorertest-bootstrap-template-dqp2b-machine-bootstrap] is not in cluster [c-m-5c138119], returning nil
2021/05/24 18:24:16 [TRACE] secretsController: AddHandler: obj [anu-explorertest-kubeconfig] is not in cluster [c-m-5c138119], returning nil
2021/05/24 18:24:18 [TRACE] secretsController: AddHandler: obj [anu-explorertest-nodepool-pool1-b54sm-machine-driver-secret] is not in cluster [c-m-5c138119], returning nil
2021/05/24 18:24:18 [TRACE] secretsController: AddHandler: obj [anu-explorertest-nodepool-pool1-b54sm-machine-state] is not in cluster [c-m-5c138119], returning nil
2021/05/24 18:24:18 [TRACE] secretsController: AddHandler: obj [anu-explorertest-nodepool-pool1-b54sm-machine-provision-tondbvh] is not in cluster [c-m-5c138119], returning nil
2021/05/24 18:24:21 [TRACE] secretsController: AddHandler: obj [anu-explorertest-nodepool-pool1-b54sm-machine-state] is not in cluster [c-m-5c138119], returning nil
2021-05-24 18:24:23.376192 I | mvcc: store.index: compact 307489

```

On ember UI:
<img width="600" alt="Screen Shot 2021-05-24 at 12 38 09 PM" src="https://user-images.githubusercontent.com/38144301/119398802-ecd8b300-bc8c-11eb-8c8a-35a00fa2bb67.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-d60543a03cdaf53e0bb497478b7426664e1b29ae-head
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4GB, 2 vcpus
- Kubernetes version (use `kubectl version`): v1.21.1-alpha5+rke2r1

**Comment by slickwarren** [comment]
on master-head (629146a) I am seeing a similar issue, but the node is actually registered and working properly (just isn't displaying correctly on the dashboard -> cluster management page)

<img width="551" alt="Screen Shot 2021-05-27 at 12 01 34 PM" src="https://user-images.githubusercontent.com/16691014/119882639-7bdf0880-bee3-11eb-8ad2-73c3ab1e0d0e.png">
<img width="1847" alt="Screen Shot 2021-05-27 at 12 01 16 PM" src="https://user-images.githubusercontent.com/16691014/119882644-7da8cc00-bee3-11eb-84a7-3092e1fbfb46.png">
<img width="1412" alt="Screen Shot 2021-05-27 at 12 00 57 PM" src="https://user-images.githubusercontent.com/16691014/119882646-7da8cc00-bee3-11eb-861c-cd3e9f3018c5.png">

**Comment by kinarashah** [comment]
The difference in cluster states - Active in Ember UI vs Provisioning in Vue is expected based on new provisioning changes. 

From https://github.com/rancher/rancher/issues/32690#issuecomment-854168819, 

> The state of the cluster will roll up the state of all nodes in the new cluster provisioning v2 framework. Therefore any nodes in the cluster that is any provisioning state will show up as provisioning for the cluster.
> 
> There is a new type of cluster (provisioning.cattle.io) that was introduced with the new cluster provisioning framework which is used in Vue.
> 
> When creating the new RKE2 cluster (provisioning.cattle.io), we also create the old cluster type (management.cattle.io), but in this old cluster type, the cluster is treated as an imported cluster since it was created outside of the old provisioning framework. Therefore, the state of the cluster will be Active as soon as the cluster agent is deployed and is not reliant on the state of the nodes.

We expect the node stuck in provisioning to actually come up Active and then cluster be Active. But if the node is actually stuck in provisioning, that'd be a different bug.

**Comment by anupama2501** [comment]
Verified on master-head 6b430f3
1. Created an rke2 multi node cluster with 3 etcd, 2 cp DO from cluster explorer.
2. Verified all nodes are active, cluster comes up active and is not stuck in provisioning.
