### ISSUE TITLE
clusters aren't accessible through dashboard under `explore cluster`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32852]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy an RKE1 cluster (through ember or dashboard)
* wait for cluster to be active

**Result:**
* cluster isn't accessible through dashboard or through ember's `explorer` buttons (redirected to fail-whale)

**Other details that may be helpful:**

This was attempted on linode, DO, and custom downstream rke1 clusters
<img width="239" alt="Screen Shot 2021-05-24 at 9 25 48 AM" src="https://user-images.githubusercontent.com/16691014/119382144-7df05f80-bc76-11eb-9aa2-33ed234b8d87.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (979d2ba)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom, linode, DO
- Machine type (cloud/VM/metal) and specifications (CPU/memory): various (2vCPU minimum)
- Kubernetes version (use `kubectl version`):v1.20.6

**Comment by nwmac** [comment]
The UI checks for the presence of the "Connected" condition, if this is present we check it for bring true.

If it is not, we look at the ready condition.

The backend is returning the connected condition as false for RKE clusters, which is why they can't be accessed.

**Comment by slickwarren** [comment]
update: this is also happening for RKE2 clusters

**Comment by sowmyav27** [comment]
PR: https://github.com/rancher/rancher/pull/32865

**Comment by slickwarren** [comment]
This is now working on master-head (f90b36e):
* deploy RKE1/RKE2 cluster
* wait for cluster to show as `active`
* cluster(s) are accessible through `cluster explorer`
