### ISSUE TITLE
Validate RHEL on RKE2 clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32850]
Validate RHEL on RKE2 clusters - cluster provisioning from Rancher
- Custom clusters
- Node drivers - AWS/ DO

**Comment by aaronRancher** [comment]
Testing on Rancher `master-head` `version c1151f6`

Deployed a custom RKEv2 cluster with RHEL 8.4 nodes (kernel version `4.18.0-305.el8.x86_64`, AMI: `ami-036519a485aaa136b`). SELinux enabled. Version `v1.21.2+rke2r1`. Local system project workloads are healthy.
Deployed a DO node driver cluster with CentOS 8.3 nodes. Version `v1.21.2+rke2r1`. Local system project workloads are healthy.

EC2 node driver provisioning is blocked by this issue: #33078

**Comment by aaronRancher** [comment]
Tested EC2 node driver on Rancher `v2.6-head` `version 0784199`
- Deployed an EC2 node driver RKEv2 cluster with RHEL 8.4 nodes (kernel version `4.18.0-305.el8.x86_64`, AMI: `ami-02caee2e326b62236`). SELinux enabled. Version `v1.21.3-rc5+rke2r2`. Local system workloads are healthy. Ran validation tests. Failures were validated manually.
