### ISSUE TITLE
Intermittent connection timeouts and nginx ingress-controller configuration

### ISSUE THREAD

**Issue by jimmy-at** [rancher/rancher#32860]
**What kind of request is this (question request):**
Question: We have our HA Minio data storage on our Rancher managed k8s cluster. From outside cluster we are trying to access Minio using nginx ingress-controller and getting intermittent connection timeouts.

Snippet from etc/nginx/nginx.conf in one of the nginx-ingress-controller pods is as below:

pid /tmp/nginx.pid;
daemon off:
**worker_processes 96;**
worker_shutdown_timeout 10s;
events {
             multi_accept               on;  
             worker_connections   16384;
             use                              epoll;
}

To resolve the timeout issue, we need to modify 
worker_processes 96;

to 
worker_processes auto;

What needs to be done to make this change happen and so the change effect will pass to the down stream cluster.

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by superseb** [comment]
Configuration options for ingress are documented at https://rancher.com/docs/rke/latest/en/config-options/add-ons/ingress-controllers/#configuring-nginx-ingress-controller, how to apply those changes to a cluster is described at https://rancher.com/docs/rancher/v2.x/en/cluster-admin/editing-clusters/#editing-clusters-with-yaml
