### ISSUE TITLE
Bug: GlobalDNS Catalog will not stay installed. Rancher 2.5.8 / K8S 1.20.x

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#32867]
---

**Update:** See comment below, this seems to be garbage cleanup happening because GlobalDNSProvider owns the ConfigMap that's put in the project namespace, and that means it's cross namespace ownership which is now treated as the owner cannot be found and it performs GC.

---

This is a weird issue, I started to attach to another issue but this seems to warrant it's own with a link back to ensure the information is clear.

I've witnessed this problem on k8s 1.20.6 deployed with RKE and also RKE2 1.20.6.

Other issues: https://github.com/rancher/rancher/issues/31638

This is happening very quickly on the cluster, it's very hard to actually see what is going, from the rancher logs, the helm install is done, and then immediate is helm delete. 

Even more strange is the fact that I was able to obtain the resource for the app.catalog.cattle.io and it's owner is set to a ConfigMap, but the code for 2.5.8 suggests it should be the GlobalDNSProvider. It's possible I'm looking at the wrong source though. https://github.com/rancher/rancher/blob/v2.5.8/pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go#L244-L250

**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Have 1.20.6 cluster with 2.5.8 installed

1. Open Cluster Manger
2. Tools
3. Global DNS Providers
4. Create a Route53 provider, populate with random values (valid not necessary)
5. Click Create

**Result:**

Rancher installs with helm v2 (tiller) and then immediate uninstalls the Global DNS provider.

**Other details that may be helpful:**

Everything seemed to work ok on 2.5.8 and K8s 1.18, when upgraded to 1.20.6 the global dns providers were removed.

Editing the global DNS provider showed the install happen with an immediate uninstall.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported/Local CLuster
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal, 4 cores, 16GB
- Kubernetes version (use `kubectl version`): 1.20.6

**Comment by ekristen** [comment]
@deniseschannon @cloudnautique I don't like to ping you both, but from what I can tell this could be a pretty big issue for people relying on Global DNS if they upgrade to 1.20.6.

Unfortunately I don't have the cycles to see under what all conditions this happens but from my new cluster testing, it appears that 1.20.6 on RKE2 defnitely won't keep the catalog/helm chart installed, it uninstalls immediately. 

My local cluster at home, I had a global DNS setup on, I upgraded it to 1.20.6 and it was gone when I logged back in, leaving me to believe that this is something to do with 1.20.6 or 1.20.x

**Comment by superseb** [comment]
On 1.20 this is probably https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md:

 ```
Resolves non-deterministic behavior of the garbage collection controller when ownerReferences with incorrect data are encountered. Events with a reason of OwnerRefInvalidNamespace are recorded when namespace mismatches between child and owner objects are detected. The kubectl-check-ownerreferences tool can be run prior to upgrading to locate existing objects with invalid ownerReferences.

A namespaced object with an ownerReference referencing a uid of a namespaced kind which does not exist in the same namespace is now consistently treated as though that owner does not exist, and the child object is deleted.
A cluster-scoped object with an ownerReference referencing a uid of a namespaced kind is now consistently treated as though that owner is not resolvable, and the child object is ignored by the garbage collector. (#92743, @liggitt) [SIG API Machinery, Apps and Testing]
```

**Comment by superseb** [comment]
And please stop pinging people directly, people are looking at GitHub

**Comment by ekristen** [comment]
I apologize.

**Comment by ekristen** [comment]
> 1.20 -  resolves non-deterministic behavior

Interesting, it says that it should record an event in the namespace to which it happens, but it doesn't look to be the case. 

I did find the message in another namespace `default` with respect to something else rancher related, but nothing in the `cattle-global-data` namespace (where global dns goes) or any other namespace for that matter.

The one I did find was 

```
apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2021-05-25T18:57:00Z"
involvedObject:
  apiVersion: admissionregistration.k8s.io/v1
  kind: MutatingWebhookConfiguration
  name: rancher.cattle.io
  uid: c1e99445-a846-466b-a83a-0f20ba04b8be
kind: Event
lastTimestamp: "2021-05-25T18:57:00Z"
message: 'ownerRef [v1/Secret, namespace: , name: cattle-webhook-ca, uid: b3e7ab2f-62a2-455e-bf82-e16771568bcc]
  does not exist in namespace ""'
metadata:
  creationTimestamp: "2021-05-25T18:57:00Z"
  name: rancher.cattle.io.1682643b02c8556a
  namespace: default
  resourceVersion: "721835036"
  uid: 6b8179c6-0798-47d7-a11a-609e1f6f3310
reason: OwnerRefInvalidNamespace
reportingComponent: ""
reportingInstance: ""
source:
  component: garbage-collector-controller
type: Warning
```

**Comment by ekristen** [comment]
I can confirm this looks to be the result of https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md

I ran through this on 2 other clusters and finally found the event, I must have missed it the first time.
