### ISSUE TITLE
Manage Environments, API and Registry screens looks broken because submenu doesn't exist

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3287]
version - master 01/14

Comment:  the Manage Environments, API keys and Registry screens look broken because there are no submenus for these screens.  So there is empty white space.
![image](https://cloud.githubusercontent.com/assets/11514927/12341321/0fcdbb82-bade-11e5-837c-ece1808f5dde.png)

Expected: Maybe like Help, the while space should be removed if there is nothing  to go in it.  It's weird that it's there when nothing goes in there?

**Comment by will-chan** [comment]
Closed due to inactivity.
