### ISSUE TITLE
system-agent install script needs to support --node-name, --address, and --internal-address

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#32875]
As part of the RKE2 integration work, the `system-agent` install script needs to support:
```
--node-name 
--address
--internal-address
```
as arguments. 

This will get trickled down to be passed to Rancher as the following headers:
```
X-Cattle-Node-Name
X-Cattle-Address
X-Cattle-Internal-Address
```

**Comment by ShylajaDevadiga** [comment]
Validated on master-head (7a2fc74)  the header are set correctly while running the install script.
Type: Custom Cluster

```
X-Cattle-Node-Name: shysrv1 -H X-Cattle-Address: <PUBLIC IP> -H X-Cattle-Internal-Address: <PRIVATE IP>

```
