### ISSUE TITLE
rke2 cluster: etcd snapshot  cluster creation fails, if etcd snapshot creation is enabled while creating a cluster

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#32874]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. From cluster explorer --> create a cluster RKE2 DO (1 node all roles) and from edit as yaml, enable etcd snapshot and click on save.
2. On the cluster we see the following error and the cluster creation is stuck 
`failed to find node to perform etcd snapshot`

**Result:**
While creating a cluster if we edit yaml and provide etcd snapshot details, eg., name, once the node is up and running snapshot should be taken but the cluster creation fails with the below error.

**Other details that may be helpful:**
Some error logs on the rancher server:
```
 rkecluster fleet-default/test-anu: refreshing etcd create state
2021/05/25 16:47:53 [DEBUG] DesiredSet - No change(2) cluster.x-k8s.io/v1alpha4, Kind=Cluster fleet-default/test-anu for rke-cluster fleet-default/test-anu
2021/05/25 16:47:53 [DEBUG] DesiredSet - No change(2) rke.cattle.io/v1, Kind=RKEBootstrapTemplate fleet-default/test-anu-bootstrap-template for rke-cluster fleet-default/test-anu
2021/05/25 16:47:53 [ERROR] error syncing 'fleet-default/test-anu': handler planner: failed to find node to perform etcd snapshot, requeuing
2021/05/25 16:47:53 [DEBUG] Bootstrap provider is not ready, requeuing
2021/05/25 16:47:53 [DEBUG] DesiredSet - No change(2) rke-node.cattle.io/v1, Kind=DigitaloceanMachineTemplate fleet-default/test-anu-nodepool-pool1 for rke-cluster fleet-default/test-anu
2021/05/25 16:47:53 [ERROR] error syncing 'fleet-default/test-anu': handler planner: failed to find node to perform etcd snapshot, requeuing
2021/05/25 16:47:53 [DEBUG] DesiredSet - No change(2) cluster.x-k8s.io/v1alpha4, Kind=MachineDeployment fleet-default/test-anu-nodepool-pool1 for rke-cluster fleet-default/test-anu
2021/05/25 16:47:53 [DEBUG] Unable to retrieve Node status, missing NodeRef

```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head 744c233
- Installation option (single install/HA): Single 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Kubernetes version (use `kubectl version`): v1.21.1-alpha5+rke2r1

Reference issue:
https://github.com/rancher/rancher/issues/32391

**Comment by deniseschannon** [comment]
@anupama2501 What is the yaml of the cluster that you tried to use? Without this info, it is hard for devs to investigate where it might have been.

**Comment by anupama2501** [comment]
@deniseschannon I tried the same steps on the master-head commit id 618c9ef

- From cluster explorer --> create an rke2 cluster DO node driver --> clicked on edit as yaml and provided the following config and clicked on create. The cluster goes into provisioning state but not seeing the error `failed to find node to perform etcd snapshot`

>  etcdSnapshotCreate:
      name: anu-test2

Here is the cluster yaml file 
[anu-etcd2.txt](https://github.com/rancher/rancher/files/6581818/anu-etcd2.txt)

**Comment by deniseschannon** [comment]
The code is supposed to find an etcd node to perform the snapshot, but has not been well dev tested and needs investigation, but the yaml is correct that all you need to do is add a name to create the snapshot. 

https://github.com/rancher/rancher/blob/master/pkg/provisioningv2/rke2/planner/etcdcreate.go

**Comment by catastrophe-brandon** [comment]
When I tried this from master-head (`94bca99`) I received an error when I clicked "Create". Here is a sanitized copy of the error taken from the dev console:

```
PUT https://hostname/v1/provisioning.cattle.io.clusters/fleet-default/btweed-do-rke2-32874 500 (Internal Server Error)
```

**Comment by catastrophe-brandon** [comment]
After updating to a newer commit, the error above no longer happens. However, when I tried to take a snapshot of the cluster, the UI appeared to wait indefinitely.

![Screen Shot 2021-07-30 at 5 03 25 PM](https://user-images.githubusercontent.com/20647751/127715990-3261fa8a-775f-4775-8d25-4808de713791.png)

This was a docker install, running `master-da1adad7a69c72b273d288c0f34023bba014874b-head`

**Comment by catastrophe-brandon** [comment]
Upgraded to rancher `ddd0837` and re-tested (to pick up the beta02 image of the rancher-webhook pod). Unfortunately I'm seeing similar symptoms.

**Steps**

Here's what I did:
1. docker installed and ran the container
2. Logged into the Rancher UI and used kubectl to confirm that the local cluster is using the beta02 version of the rancher-webhook image (per recommendation). Example output:
```kubectl -n cattle-system describe pod rancher-webhook-5ff9554d8c-58c8m | grep beta02
    Image:          rancher/rancher-webhook:v0.2.0-beta02
  Normal   Pulling      17m   kubelet            Pulling image "rancher/rancher-webhook:v0.2.0-beta02"
  Normal   Pulled       17m   kubelet            Successfully pulled image "rancher/rancher-webhook:v0.2.0-beta02" in 2.899320121s```
3. Provisioned an RKE2 cluster in DO, waited for it to reach a ready state
4. Tried to take a snapshot of the newly-provisioned cluster

**Results**

In the UI, the message `waiting for etc snapshot` is displayed, seemingly indefinitely.

In the logs I see a dialer timeout (IPs redacted to protect the innocent):
```
2021/07/30 22:50:15 [INFO] rkecluster fleet-default/btweed-do-beta02-attempt2: refreshing etcd create state
2021/07/30 22:50:15 [INFO] rkecluster fleet-default/btweed-do-beta02-attempt2: starting etcd snapshot
2021/07/30 22:50:15 [INFO] rkecluster fleet-default/btweed-do-beta02-attempt2: waiting for etcd snapshot
2021/07/30 22:50:15 [INFO] rkecluster fleet-default/btweed-do-beta02-attempt2: waiting for etcd snapshot
2021/07/30 22:50:15 [INFO] rkecluster fleet-default/btweed-do-beta02-attempt2: waiting for etcd snapshot
2021/07/30 22:50:15 [INFO] rkecluster fleet-default/btweed-do-beta02-attempt2: waiting for etcd snapshot
2021/07/30 22:50:27 [INFO] error in remotedialer server [400]: read tcp ip1:443->ip2:16982: i/o timeout
2021/07/30 22:50:28 [INFO] error in remotedialer server [400]: read tcp ip1:443->ip2:4153: i/o timeout
```

**Comment by catastrophe-brandon** [comment]
Could this be related to https://github.com/rancher/rancher/issues/32391#issuecomment-853429189?

**Comment by thedadams** [comment]
This was a problem on the downstream cluster that was fixed by https://github.com/rancher/rancher/pull/33877

This is good to be tested now.

**Comment by catastrophe-brandon** [comment]
Appears to be working on `v2.6-8784750074bceb84615b4b4a26d5d5e62683121c-head`

**Comment by catastrophe-brandon** [comment]
Also works on master-bc9ca3cc39b34b50da089f11743b610dfe48fb32-head
