### ISSUE TITLE
Update feature-charts to Rancher specific version

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32877]
Due to complications around versioning upstream charts across Rancher versions, we have to break away from the current patch-style versioning. For example upstream 1.5.1 would today be equivalent to 1.5.100. We made this decision for several reasons, including easy visibility for end users into what upstream version they were using. To keep this we are adding a metadata tag to the end of the new version to make it easy to see: 10.0.0+up1.5.1.

Changes needed

- [ ] logging - @nickgerace 
- [ ] monitoring and sub-charts - @aiyengar2 
- [ ] Istio and sub-charts - @brendarearden 
- [ ] gatekeeper - @cmurphy 
- [ ] vsphere-csi and vsphere-cpi - @PennyScissors
- [ ] longhorn - @shuo-wu ?
- [ ] cis - @prachidamle 
- [ ] fleet - @StrongMonkey 
- [ ] backup - @jiaqiluo 
- [ ] webhook - @thedadams 
- [ ] gke/eks - @cmurphy

**Comment by PennyScissors** [comment]
@cbron I assume this applies to vsphere-cpi as well, so I'll go ahead and add it to the list.

**Comment by cbron** [comment]
@jiaqiluo already did this apparently, someone should buy him dinner 😄 .

**Comment by jiaqiluo** [comment]
To be clear, with this PR https://github.com/rancher/charts/pull/1256

now all charts have the version `100.0.0` or  `100.0.0+upx.x.x` if it has upstream 

The version is set in `package.yaml` of the chart.
