### ISSUE TITLE
[ERROR] could not convert gke config to map

### ISSUE THREAD

**Issue by mjura** [rancher/rancher#32887]
During updating Rancher cluster from master branch, I am getting following error:

```
2021/05/26 15:00:34 [WARNING] Catalog-manager error deleting old template content: no kind "DeleteOptions" is registered for version "provisioning.cattle.io/v1" in scheme "k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:52"
2021/05/26 15:01:55 [ERROR] could not convert gke config to map
2021/05/26 15:01:55 [ERROR] could not convert gke config to map
2021/05/26 15:01:55 [ERROR] could not convert gke config to map
2021/05/26 15:01:55 [INFO] clusterDeploy: redeployAgent: redeploy Rancher agents due to agent env vars mismatched for [c-xf8vp], was [[]] and will be [[]]
```

Fix for this issue https://github.com/rancher/rancher/pull/32912

**Comment by mjura** [comment]
Fix was merged

**Comment by prabalsharma** [comment]
Repro steps from Michal:

1. Deploy AKS cluster
2. Wait until it will finish successfully
3. Change configuration for example by adding new tags
4. In Rancher logs you will find [ERROR] could not convert gke config to map

**Comment by prabalsharma** [comment]
Tested on master-8cdbffe7fcbd433177ec2e0effd160190d36fa54-head, aks-operator:v1.0.1-rc6
