### ISSUE TITLE
[AKS] Error creating Azure cloud credential from UI: '"Tenant" is required'

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#32897]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Try to create an Azure cloud credential using client ID, client secret, and subscription  ID.

**Result:**

![image](https://user-images.githubusercontent.com/1220710/119722943-c009d480-be21-11eb-986b-1f9edde24253.png)

**Other details that may be helpful:**

The UI should eventually support entering a tenantID, but even then it should be optional to maintain backwards compatibility.

The validation error happens because the dynamic schema marks the field "required". It should be marked as optional.

![image](https://user-images.githubusercontent.com/1220710/119723796-b92f9180-be22-11eb-8974-046e29522c36.png)

This was introduced in https://github.com/rancher/rancher/pull/32288 / https://github.com/rancher/machine/pull/133

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master 6395fbccd74315673de289d522992e28004fbb3c
- 
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by prabalsharma** [comment]
user can create a CC without tenant ID, but won't be able to create an AKS v2 cluster using it. As such CC do not get listed in CC list while provisioning AKSv2 cluster.
