### ISSUE TITLE
Add a 'password' type to Catalogue templates

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3289]
A 'password' field type for the template should be the same as 'string', but would conceal the value on-screen.  This is useful for templates which need an initial password ot be specified, and it is insecure to display it on-screen.

This is related to #3246 (Adding 'certificate' field type)

**Comment by blaggacao** [comment]
-1, we should wait/go for/with a future integrated secrets management solution. It is a wide field and any temporary solution just may create a silo.

A developer might request a quick fix, but security people need full control of any secrets. And mind that usually those are different people.

my 2 cents

**Comment by sshipway** [comment]
I would agree that an integrated Secret management would be better, in much the same way that the integrated certificate system would be better if there were a way to use these certs in containers other than load balancers.  However there is always going to be a need to pass text fields to the environment, and some of those text fields you might want obscured, hence a password datatype, just as you have in HTML forms.

Even if some people choose not to use it, then it would be (I think) something very easy to add that woul dat the very least bridge the time until Rancher gains an integrated secret management system.

**Comment by blaggacao** [comment]
I challenge that again :smile: 
In that it might incentive bad practice to make such a field available and take out the perceived urge for a proper solution.

I read: Anything obfuscated is by definition *secret*. That means it should be part of any security handling layer, no matter how we twist it.

In case of Vault client, for example, as it is long running (read continuous control over the life-cycle), I don;t have any problem to include vault client in my images to be able to make use of the secret's solution. This, until docker might chose to integrate it (or something similar) into it's api.

**Comment by vincent99** [comment]
UI support for `type: password` was actually added [two months ago](https://github.com/rancher/ui/commit/68edcfeba905f84a5e2f895ee7c1b5d7259b3eac), as I discovered while adding `type: certificate`.  We obviously need secrets management but I don't think this is significantly worse than nothing, and since it's already there it's somewhat of a moot point.

**Comment by blaggacao** [comment]
:smile:
