### ISSUE TITLE
Nodes still reported as Active after its shutdown

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#32891]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* Deploy `rancher/rancher:master-head f90b36e` on ec2 singlenode as custom RKE
* In Ember UI create a custom RKE cluster on "Existing node" and choose k8s `v1.21.1-rancher1-1` version
* copy and execute the reg. commands on existing aws t3.medium VMs with ubuntu 20.04 ami-040beb0a6ba231815, needed are 2 controlplane, 3 etcd and 2 worker nodes
* once the cluster is up and `Active` add one additonal control plan node
* once the new cp node is up and `Active`, stop/shutdown the original controlplane VM
* **Edit:** any stopped node reported as Active

**Result:**
* even after 30 minutes the original stopped control plane is reported as `Active` in Ember UI and `In Progress` in Explorer, there are additional labels `node.kubernetes.io/unreachable:NoExecute` and `node.kubernetes.io/unreachable:NoSchedule` added on it, visible in Ember.

**Other details that may be helpful:**
Ember UI:
![ember-cp-node](https://user-images.githubusercontent.com/12828077/119699119-1db61500-be52-11eb-9969-d9af5079a060.png)

Explorer:
![dash-cp-node](https://user-images.githubusercontent.com/12828077/119699131-20b10580-be52-11eb-8a3b-d0a58b4896c8.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher/rancher:master-head f90b36e`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom RKE1
- Machine type (cloud/VM/metal) and specifications (CPU/memory): t3.medium
- Kubernetes version (use `kubectl version`): `v1.21.1-rancher1-1`

**Comment by Jono-SUSE-Rancher** [comment]
@vincent99 - Is this one of those scenarios where the backend needs to look at the API that it's sending to the front end so that you guys can report the status accurately? Either that or the labels that are being added to the nodes are an indication that something isn't getting interpreted correctly?

Just trying to figure out where to filter this ticket.

**Comment by kravciak** [comment]
I can see the same behavior on the etcd nodes - node is powered off, but still has `Active` label in ember UI

**Comment by kravciak** [comment]
When I power down worker node it's not noticed even on cluster view (there is red exclamation mark with etcd).
Screenshots of cluster with 3 etcd, 1 master, 1 worker, 1 powered off worker nodes.

![Screenshot from 2021-05-27 16-35-16](https://user-images.githubusercontent.com/538604/119845548-a774e980-bf09-11eb-94b2-0c177d6de5c4.png)

**Comment by vincent99** [comment]
There's a few things here but as far as the UI is concerned they're mostly "this is the state you told me..."

- The "machines" we provision to cause the cloud provider to make a VM are a separate resource from the "nodes" that k8s sees as a registered part of the cluster.  Imported clusters have only "nodes", not "machines".  Something like using digitalocean has "machines" created, which are provisioned and eventually register as "nodes".
  - Ember combines these in a way that doesn't make it particularly clear what you're seeing.
  - Vue shows them separately. K8s nodes when looking inside a cluster -> Nodes, and provisioned machines in the Cluster Management "product".  As of earlier today they should be consistently called Nodes vs Machines.

- I don't think we do anything to keep track of the state of the provisioned machines after they're deployed and up, so the machine does not know if it's running or shutdown.

- On the k8s side, the nodes list _should_ know which ones are connected or not, and I think they eventually disappear from the list if disconnected long enough.  Not sure if they have a visible state for in between where it's not connected anymore.

**Comment by thehejik** [comment]
In `rancher:2.5.8` it behaves correctly - once I stop any of the three node kind then the corresponding node goes to `Unavailable` state after a while.

**Comment by kinarashah** [comment]
Available to test on v2.6-head once https://drone-publish.rancher.io/rancher/rancher/6125 passes

**Comment by kinarashah** [comment]
master-head build https://drone-publish.rancher.io/rancher/rancher/6126

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.6-head` `version 7b9a232` and `master-head` `2916020` with the following steps:
- Create a custom cluster (3 etcd, 1 control, 1 worker) using ec2 instances
- Add a control node
- Once control node becomes available, power down the original control node instance.

Result:
- Control plane node becomes unavailable. 
![Screen Shot 2021-08-06 at 6 31 35 PM](https://user-images.githubusercontent.com/57409052/128584085-607a217a-fd8e-48a5-9a93-1670dbed8b0b.png)
![Screen Shot 2021-08-06 at 6 43 46 PM](https://user-images.githubusercontent.com/57409052/128584117-a6033e79-e996-4ac0-80f2-78edb6ea67ac.png)
