### ISSUE TITLE
`sudo` is not included in custom registration command for rke2

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32894]
[related to this issue](https://github.com/rancher/rancher/issues/32786#issuecomment-847236862)

nodes do not register unless user is root or command is modified to include `sudo`

current rke2 cmd ( not working as is):
```
curl -fL https://<server>/system-agent-install.sh |  sh -s - --server https://<server> --token <token> --ca-checksum <checksum>
```

current rke1 command (works fine for any user):
```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:master-979d2ba66ec82e79946c56a3cc59ca597225f79e-head --server https://<server> --token <token> --ca-checksum <checksum> --worker
```

**Comment by deniseschannon** [comment]
We decided that we didn't want `sudo` in the command, but it now should error that you need to be the root user.

**Comment by kinarashah** [comment]
https://github.com/rancher/system-agent/pull/15/files 
https://github.com/rancher/rancher/issues/32786

**Comment by sowmyav27** [comment]
@deniseschannon @kinarashah this is a change in behavior between ember and new UI. Is this how we want it?

**Comment by kinarashah** [comment]
@sowmyav27 Thanks for bringing it up, we'd be adding sudo to the command same as rke1.

**Comment by slickwarren** [comment]
on master-head (5d49b92f479a00773607fb41fe851f98271148c0):
`sudo` is now included in the rke2 registration command, and works without editing for non-root and root users alike. Tested on:
* linode node (root user): -- pass
* ec2 node (`ubuntu` user): -- pass
* digital ocean node (root user): -- pass
