### ISSUE TITLE
[2.5 Backport]  Upstream Kubernetes Deprecation: Controller Manager & Scheduler show as Unhealthy in clusters that do not have component status for them (Azure, Tectonic among others)

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#32905]
https://github.com/rancher/rancher/issues/11496

**Comment by slickwarren** [comment]
this is broken for imported aks clusters on 2.5.9-rc2
```
"componentStatuses": [ 3 items
{
"conditions": [
{
"message": "Get \"http://127.0.0.1:10252/healthz\": dial tcp 127.0.0.1:10252: connect: connection refused",
"status": "False",
"type": "Healthy"
}
],
"name": "controller-manager",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\":\"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-0",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "Get \"http://127.0.0.1:10251/healthz\": dial tcp 127.0.0.1:10251: connect: connection refused",
"status": "False",
"type": "Healthy"
}
```

<img width="1348" alt="Screen Shot 2021-06-09 at 9 55 04 AM" src="https://user-images.githubusercontent.com/16691014/121397058-da0ae300-c908-11eb-889a-766d697fc460.png">

**Comment by slickwarren** [comment]
on 2.5-head (d2a5514193677f3bb86a9222e8b73352ba52fbc2): 
this is working as expected. both hosted and imported AKS clusters show `not applicable` for controller manager/scheduler
<img width="1387" alt="Screen Shot 2021-06-09 at 10 23 53 AM" src="https://user-images.githubusercontent.com/16691014/121400757-ceb9b680-c90c-11eb-8b53-6116de5fefad.png">

note: 2.5.9 will not contain this fix

**Comment by mohag** [comment]
This only fixed AKS clusters, the others are still broken... See the bug mentioned in the first comment on this bug.

**Comment by slickwarren** [comment]
@mohag could you please file a new ticket and fill out the bug template if you're still seeing issues?
