### ISSUE TITLE
etcd and control plane nodes of an RKE2 cluster are schedulable

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32904]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- deploy a 3 nodes - 1 etcd, 1 control and 1 worker nodes (DO node driver RKE2 cluster)
- cluster come sup Active
- Deploy a daemonset workload
- the workload scales to 3, and schedules on etcd and control plane nodes also

**Expected Result:**
The daemonset should not get deplooyed on etcd and control plane nodes.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `f90b36e`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO rke2
- Kubernetes version (use `kubectl version`):

```
v1.21.1
```

**Comment by sangeethah** [comment]
When validating the fix , we should check the following additionally:
1. Node with both etcd and control plane role should not be schedulable
2. Node with etcd and worker plane should be schedulable
3. Node with controlPlane and worker plane should be schedulable
4. Node with all role should be schedulable

**Comment by deniseschannon** [comment]
We need to add the code to add the taints and labels.  This needs to be done by adding node-label, node-taints to the rke2 config file from the planner.  Then in addition add a controller that adds the rke2 taints to the v1.Node for dynamic changes.  You don't need to do a controller for the labels because node-labels in the rke2 config file are always applied where as taints only happen on node create.

**Comment by kinarashah** [comment]
https://github.com/rancher/charts/pull/1347

**Comment by kinarashah** [comment]
Available to test once https://drone-publish.rancher.io/rancher/rancher/6040 passes.

**Comment by anupama2501** [comment]
Verified on master-head 1adc8ef

1. Created a node driver rke2 1 cp+etcd and 1 worker node with AWS and DO
2. Created a daemon set and verified its not scaled on etcd+cp node
3. Verified taints are added to etcd, cp nodes `node-role.kubernetes.io/control-plane=:NoSchedule node-role.kubernetes.io/etcd=:NoExecute`
4. Verified by creating 2 worker, 1 cp+etcd on DO
5. created a daemon set and verified its scaled on both the worker nodes and not on the etcd+cp node
