### ISSUE TITLE
Rancher container logs

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#3291]
Hi,

I have been looking at docker logging driver features to ship logs to a fluentd instance.

What I am also trying to do is to add as much information as possible to the log message so that it will be easier to do some filtering at a later point.

For that reason, I am looking at adding rancher-defined labels to the message by defining the following options in the docker compose:

```
log_opt:
  labels: "io.rancher.stack_service.name,io.rancher.container.ip"
```

Is that supposed to work? Reading at https://docs.docker.com/engine/reference/logging/overview/ indicates that it should be possible.

Thanks,
Matteo

**Comment by cjellick** [comment]
@m4ce we do support log driver configuration in our API, but not yet in our UI. Feel free to add your +1 here: #2935

Also, it is supported in rancher-compose. You would specify it thusly:
```
foo:
  image: nginx
  log_driver: json-file
  log_opt:
    labels: foo
```
Does that answer your questions sufficiently to close this issue?

**Comment by m4ce** [comment]
@cjellick,

thanks for your answer!

Not quite, if I set the labels field to any rancher-defined labels (e.g. io.rancher.stack_service.name), the container fails to start.

In theory, docker should expose the labels (e.g. io.rancher.stack_service.name) in the JSON formatted log message in the extra field.

Right now, the only way I found to achieve that is to parse the container JSON log files via logstash and using the docker_metadata filter (https://github.com/tgermain/logstash-filter-docker_metadata) which adds envs and labels to the log message before shipping it to a central destination (e.g. Elasticsearch).

Cheers,
Matteo

**Comment by deniseschannon** [comment]
@m4ce I understand what you're trying to do, but just haven't had the time to try it out myself to see if it'd even work with fluentd. I have never used fluentd and just need to find time to actually learn and try it out.

**Comment by deniseschannon** [comment]
@m4ce Were you ever able to get this working as expected? I still haven't had time to try out fluentd, but I don't see any reason why this wouldn't work in Rancher.

**Comment by deniseschannon** [comment]
@m4ce I don't see any reason why this wouldn't work. If you are unable to get this going in our latest release, please re-open.
