### ISSUE TITLE
[BUG] Worker node is stuck in deletion

### ISSUE THREAD

**Issue by abhi1693** [rancher/rancher#32913]
**What kind of request is this (question/bug/enhancement/feature request):**
I removed a worker node as it could not get IP over SSH due to misconfiguration in the template. It is now stuck in the removal and `kubectl get nodes` do not even see it. Using the `remove` option from the 3dot menu does nothing.

![image](https://user-images.githubusercontent.com/5083532/119833707-f4ae8680-bf1c-11eb-889f-5f32b1a12b7e.png)

![image](https://user-images.githubusercontent.com/5083532/119833714-f6784a00-bf1c-11eb-8a82-6dbc4d24e8a0.png)

**Steps to reproduce (least amount of steps as possible):**
Create a template that won't be able to fetch a valid IP address
Add the template as a worker node and provision the cluster
Wait for the `Waiting for SSH to be available` message and then delete the node

**Result:**
There should be a way to force it to remove

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.20.6

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by kravciak** [comment]
Same applies for control plane, as described in https://github.com/rancher/rancher/issues/32964
