### ISSUE TITLE
Validate Oracle Linux 8.4

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#32914]
https://blogs.oracle.com/linux/announcing-the-release-of-oracle-linux-8-update-4
https://docs.oracle.com/en/operating-systems/oracle-linux/8/relnotes8.4/

**Comment by sowmyav27** [comment]
To Validate:
- Local cluster using this AMI/OS
- - Deploy an RKE local cluster using this AMI/OS
- - Deploy a downstream cluster using this AMI
- - Run validation checks (v3_needs cluster jenkins) on this cluster
- Deploy v1/v2 charts and verify all workloads get to Active state and the P0 usecase works.

**Comment by kravciak** [comment]
Validating with 8.4 AMI:
 - Deployed an RKE local cluster using this AMI
 - created rke1 cluster (plus v3_needs cluster tests)
 - created rke2 cluster (plus v3_needs cluster tests)
 - import existing kubernetes rke2 cluster

Alerts v1 - fails on https://github.com/rancher/rancher/issues/33400
Monitoring v1 - fails ^
Pipeline v1 - ok

OPA Gatekeeper v2 - ok
CIS Scan v2 - fails on https://github.com/rancher/rancher/issues/33290

**Comment by anupama2501** [comment]
Verified rancher backup version: `rancher-backup:2.0.0+up2.0.0-rc3` 
rancher server version: master-head commit cf5a75f
Oracle linux version: `Oracle Linux Server release 8.4`

1. From the local cluster --> explore cluster --> apps and market place --> installed rancher backup
2. Verified the installation is successful
3. Ran cis scan `rke-profile-permissive-1.6` -- Verified it is successful
4. Created a rancher backup 
5. Ran cis scan `rke-profile-permissive-1.6` -- Verified it is successful.

**Comment by kravciak** [comment]
Closing v1 / v2 charts or other rancher functionality does not seem to fail on underlaying OS (Oracle 8.4) issues.
