### ISSUE TITLE
Dev follow ups on keycloak

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#32920]
Follow up on: https://github.com/rancher/rancher/issues/30280
For light technical changes.

**Comment by brendarearden** [comment]
Follow up needed: https://github.com/rancher/rancher/blob/dc2dc5744bc0c94a49c24175b064dd96b24c02ef/pkg/auth/providers/keycloakoidc/keycloak_client.go#L178 << this could result in a 200 status code, but a nil body. Need to add a check for error that is returned on this line.

**Comment by brendarearden** [comment]
Follow up needed: 
https://github.com/rancher/rancher/blob/dc2dc5744bc0c94a49c24175b064dd96b24c02ef/pkg/auth/providers/keycloakoidc/keycloak_client.go#L85 << ensure the error is returned for a 401 instead of eating the error

**Comment by brendarearden** [comment]
Follow up needed: 
the keycloak token isn't being refreshed on timeout
```2021/06/15 08:34:38 [ERROR] Error refreshing token principals, skipping: [generic oidc]: not implemented      
(manually logged out & in)```

**Comment by cbron** [comment]
Closing this as it will be tested via the other 2 keycloak issues
