### ISSUE TITLE
Reduce size of v3.Catalog objects

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#32938]
## Summary

**This issue targets `v3.Catalog` objects.**

- sibling issue targeting `v3.App` objects: https://github.com/rancher/rancher/issues/32939
- parent issue that has been closed to focus on the child issues: https://github.com/rancher/rancher/issues/32418

### What kind of request is this? (question/bug/enhancement/feature request)
enhancement

### Description
Catalogs and apps can be enormous in size causes performance issues and other bugs. The [bitnami](https://charts.bitnami.com/bitnami) chart for example is about 1mb in size. For catalog size is largely due to recording the hash of each version of each charts on its status, at least for non git catalogs. One solution is to gzip certain fields, like chart version hashes, or only record the hash for the latest version of each chart on the status (both examples apply to catalogs specifically). Large object size in kubernetes 1.20 is leading to timeouts and high cpu consumption spikes, see related issues.

### Related issues
https://github.com/rancher/rancher/issues/32175
https://github.com/rancher/rancher/issues/31940
https://github.com/rancher/rancher/issues/31614
https://github.com/rancher/rancher/issues/32295

### Other details that may be helpful
Once solutions are implemented may want to tryout adding the bitnami catalog while using a 1.20 management cluster.

**Comment by nickgerace** [comment]
## QA Validation Recommendations

The resolution of this issue will not require checking how much the `v3.Catalog` CR sizes have been reduced. Rather, validation of the solution will be dependent on catalogs working as intended. If catalogs, project catalogs, and cluster catalogs work as intended via creation, updates, deletion, and app usage, then the solution is valid.

**Comment by nickgerace** [comment]
This will require a backport to 2.5.x.

**Comment by nickgerace** [comment]
Related: https://github.com/rancher/rancher/issues/32419#issuecomment-858136129

**Comment by kravciak** [comment]
Adding / removing catalogs and installing apps from them works fine for both local and rke1 clusters.

Tested on master-head (3dae3e2)

**Comment by anupama2501** [comment]
Verified on v2.5.9-rc8

- Created a catalog at global level , cluster level  and project level 
- Installed mySql app from cluster, project, global in 3 different projects.
- All apps have come up fine and active in all the projects.
