### ISSUE TITLE
For Accounts, description is not displayed anywhere

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3293]
version - master 01/14

Steps:
1.  Authenticate using Local Authentication
2.  Go to Accounts page
3.  Add Account and put in a description

Results: Description isn't show anywhere

Expected: Should see description or not have that option.

**Comment by will-chan** [comment]
I'm going to close this as we are working on a 2.0 UI and let's log bugs against that when ready.  This one will be obsolete.
