### ISSUE TITLE
Validate Windows 20H2 on k8s 1.21

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32932]
Validate Windows 20h2:
- Run validation tests on 20h2 cluster on k8s 1.21
- Validate applicable v1 and v2 on this windows cluster

**Comment by thehejik** [comment]
Doesn't work on current `rancher/rancher:master-head 62aef76` - with `v1.21.0-rancher1-1` the win nodes are stuck in `Registering` state forever.

https://github.com/rancher/rancher/issues/32910#issuecomment-850243257

**Comment by thehejik** [comment]
Still doesn't work on `rancher/rancher:master-head 51d074b` with k8s `v1.21.1-rancher2-1` - win nodes stuck in `Registering` state due #32910

**Comment by thehejik** [comment]
Still doesn't work on `rancher/rancher:master-head cd623b5` with k8s `v1.21.1-rancher2-1`. Windows-20H2 nodes (vxlan) are stuck in `Registering` state forever, Linux nodes are ok.

**Comment by sowmyav27** [comment]
Blocked by - https://github.com/rancher/rancher/issues/34066

**Comment by sowmyav27** [comment]
Can be tested on latest 2.6-head

**Comment by thehejik** [comment]
Validation report
* :ok: downstream RKE Windows 20H2 `ami-01c022034d479db8e` (updated 07/14/21) cluster deployed successfully (1 linux-cp, 1 linux-etcd, 1 linux-worker, 3 win-workers)
* :ok: v3_needs_cluster `#137` ok (6 failures due deprecation: "field `environment/environmentFrom` is deprecated" )
* :ok: v2 `monitoring-100.0.0+up16.6.0` successfully validated (all targets up, grafana dashboard->Nodes ok, alert sent to webhook)
* :ok: v2 `rancher-wins-upgrader:100.0.0+up0.0.1` deployed successfully

Versions:
* local cluster deployed by using latest `rke-v1.3.0-rc12`
* helm chart and images `rancher:v2.6.0-rc1` + `rancher/rancher:master-head 84770f0`
* kubernetes version on local and downstream win RKE clusters: `v1.21.3-rancher1-1`

Closing, works as expected.
