### ISSUE TITLE
v2 charts are not available, all repos stuck `in progress`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32943]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy any downstream cluster
* go to `apps & marketplace` to install a chart

**Result:**
* v2 charts aren't available, and all repos are stuck `in progress`

<img width="1756" alt="Screen Shot 2021-05-28 at 10 16 59 AM" src="https://user-images.githubusercontent.com/16691014/120019904-dccb1700-bf9d-11eb-85c3-f0e02a6a5e7d.png">
<img width="1658" alt="Screen Shot 2021-05-28 at 10 16 53 AM" src="https://user-images.githubusercontent.com/16691014/120019909-ddfc4400-bf9d-11eb-8441-3d432a541f8b.png">

requests on refresh: 
```
Request URL: https://173.230.151.95/k8s/clusters/c-zcl9s/v1/catalog.cattle.io.clusterrepos/rancher-partner-charts
Request URL: https://173.230.151.95/k8s/clusters/c-zcl9s/v1/catalog.cattle.io.clusterrepos/rancher-charts

```

**Other details that may be helpful:**
* even adding new charts is not working (stuck in progress)
from the logs, this shows up a few times
```
021/05/28 17:07:46 [DEBUG] Helm updated git-helm catalog [https://git.rancher.io/charts:master]
2021/05/28 17:07:46 [DEBUG] Helm updated git-helm catalog [https://git.rancher.io/system-charts:dev-v2.6]
```

however could not find any of the charts listed in the screenshot above. i.e. `https://git.rancher.io/charts`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (62aef76)
- Installation option (single install/HA): single

**Comment by cbron** [comment]
May be related to: https://github.com/rancher/rancher/issues/32836

**Comment by nickgerace** [comment]
Comparison between "a last known good" and the commit above: https://github.com/rancher/rancher/compare/629146a..62aef76

**Comment by roycec** [comment]
Similar problem after upgrading from 2.5.5 to 2.5.7 or 2.5.8 in an airgapped setup. Rancher system charts do not show up.

**Comment by nickgerace** [comment]
### Status

Awaiting potential fix from @ibuildthecloud.

### Working Theory

Our theory is that not all CRDs are being installed when MCM agent is enabled. We notice that the default monitoring v1 CRDs (the ones required by default) are not installed, and [notice these logs are particularly noisy and appear frequently](https://github.com/rancher/rancher/issues/32978). @aiyengar2's theory is that the controllers appear to be set up as intended, but their internal caches might be having issues being initialized, which causes some of the controllers to not get started.

> "It would make sense why the cache would fail to be started if the CRDs were never installed onto the cluster… it’s possible these could be two separate issues though..."
> "However, I think they might be related in that both of their root causes could be because `features.Legacy.Enabled()` is `false`..."
>
> - @aiyengar2 

Thus, the v2 charts being stuff in an `in progress` state may be the "smoke" for the true "fire": initialization of controllers failing. This would also coincide with evidence proving that the error only occurs with new clusters upon creation, and not anytime afterwards.

### Testing Context

The issue has been determined to be consistently reproducible on `master-head` ([between two commits](https://github.com/rancher/rancher/issues/32943#issuecomment-852365763)) and is not dependent on the provider type. Backend reproduction was done with 8 DO RKE1 clusters, with only the downstream clusters encountering the error (though, the error rate is 100%).

**Comment by kravciak** [comment]
This worked fine for me today on this setup, @slickwarren please recheck if it works for you too
 - DO - 3 nodes, infrastructure provider, all roles on all nodes
 - kubernetes v1.20.7
 - rancher master-head (29674d9)
 - cluster created in emberUI
 - repos are loaded fine, all of them are `Active`
 - dev-v2.6 (f83edc8ded81701eed6ce1c5c45ee5b26d38678e)

Not closing because status is `working`, but it seems fixed, please update / close if I am not wrong.

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/pull/32951/commits/1952830252abddea062a13ab23a66cbc8335e757

**Comment by slickwarren** [comment]
on rancher master-head (29674d9) I was also able to provision downstream clusters and deploy v2 charts using the following:
* node-provisioned RKE1 (linode) -- pass
* node-provisioned RKE2 (DO) -- pass
* custom RKE1 -- pass
