### ISSUE TITLE
Replaced node is created with a different name than before

### ISSUE THREAD

**Issue by AcidAngel21** [rancher/rancher#32957]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Delete a node from a node pool

**Result:**
The new node is created with a different name than before.

_before delete_
![image](https://user-images.githubusercontent.com/64893006/120204875-9689e800-c229-11eb-9805-8524bfdfc490.png)

_during provisioning_
![image](https://user-images.githubusercontent.com/64893006/120205158-ebc5f980-c229-11eb-8409-53fb5801a957.png)

_after_
![image](https://user-images.githubusercontent.com/64893006/120205936-d7363100-c22a-11eb-9dca-5f19fe348ea3.png)

**Other details that may be helpful:**
With Rancher 2.4.x the replaced node is created with the same name than before.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): ```Rancher 2.5.7```
- Installation option (single install/HA): ```HA```

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): ```vSphere Infrastructure Provider```
- Machine type (cloud/VM/metal) and specifications (CPU/memory): ```VM```
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:18:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6f6ce59dc8fefde25a3ba0ef0047f4ec6662ef24", GitTreeState:"clean", BuildDate:"2021-04-15T03:23:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by ohauer** [comment]
This is not a bug, it is indeed a feature and as far as I remember there was a ticket to do it this way.
Before 2.5 it was possible to create a race condition where rancher tried to create the node with the same name at the time the node was not fully removed from vSphere, the new mechanism is conflict free

**Comment by AcidAngel21** [comment]
Thank you very much for the information. That sounds reasonable to me.
