### ISSUE TITLE
[AKS] Error during enabling nodepool autoscaling

### ISSUE THREAD

**Issue by mjura** [rancher/rancher#32956]
During enabling autoscaling for already deployed AKS clusters, following error will occur
```
AgentPool 'workers' has set auto scaling as enabled but is not on Virtual Machine Scale Sets, this is not allowed. Please see https://aka.ms/aks-vmss-enablement for more details.
```

PR: https://github.com/rancher/aks-operator/pull/19

**Comment by prabalsharma** [comment]
I don't see this on master-head

**Comment by mjura** [comment]
This was merged in https://github.com/rancher/aks-operator/pull/19
