### ISSUE TITLE
Cannot edit volume name when adding/editing volume in Cluster Explorer

### ISSUE THREAD

**Issue by dbrosy** [rancher/rancher#32952]
**What kind of request is this (bug):**

**Steps to reproduce (least amount of steps as possible):**
- In Cluster Explorer select Deployments
- Click Create
- Click Storage
- Click Add Volume and try either bind-mount or ConfigMap (haven't tested others) 
- try to edit volume name

**Result:**
The add Volume dialog closes when you start typing.

**Other details that may be helpful:**
Have tried on windows 10 using latest chrome and also latest Edge broswer.

**Environment information**
- Rancher version (`rancher/rancher` 2.5.8):
- Installation option (single install):
- running on k3s (v1.21.1+k3s1)

**Cluster information**
- Cluster type (Installed on k3s running on ubuntu server 20.04.2 lts):
- Machine type (azure vm) and specifications (2 CPU/ 8GB ram):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by depeo** [comment]
Same, tried Safari and Chrome, I have to go back to the old interface to be able to add a volume.

**Comment by purvaldur** [comment]
Same here. Have only tried chrome so far, incognito and non-incognito.

Getting the error:

`TypeError: e.updateMountNames is not a function
    at input (index.vue?b095:1)
    at Qt (vue.runtime.esm.js:1854)
    at f.n (vue.runtime.esm.js:2175)
    at Qt (vue.runtime.esm.js:1854)
    at f.t.$emit (vue.runtime.esm.js:3888)
    at input (LabeledInput.vue?d2a9:3)
    at Qt (vue.runtime.esm.js:1854)
    at HTMLInputElement.n (vue.runtime.esm.js:2179)
    at HTMLInputElement.c._wrapper (vue.runtime.esm.js:6917)
te @ vue.runtime.esm.js:1888
Zt @ vue.runtime.esm.js:1879
Jt @ vue.runtime.esm.js:1839
Qt @ vue.runtime.esm.js:1862
n @ vue.runtime.esm.js:2175
Qt @ vue.runtime.esm.js:1854
t.$emit @ vue.runtime.esm.js:3888
input @ LabeledInput.vue?d2a9:3
Qt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
c._wrapper @ vue.runtime.esm.js:6917`
