### ISSUE TITLE
AKSv2- cannot create new NPs with AZs

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32960]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

1. Deploy master-8cdbffe7fcbd433177ec2e0effd160190d36fa54-head, aks-operator:v1.0.1-rc6
2. Create an AKS cluster
```
{
  "resourceLocation": "eastus",
  "resourceGroup": "<  >",
  "clusterName": "aks-az",
  "baseUrl": "https://management.azure.com/",
  "authBaseUrl": "https://login.microsoftonline.com",
  "tenantId": "<your tenant ID>",
  "azureCredentialSecret": "cattle-global-data:<  >",
  "kubernetesVersion": "1.19.9",
  "privateCluster": false,
  "nodePools": [
    {
      "name": "masters",
      "orchestratorVersion": "1.19.9",
      "count": 1,
      "vmSize": "Standard_DS2_v2",
      "osDiskSizeGB": 128,
      "osDiskType": "Managed",
      "maxPods": 110,
      "mode": "System",
      "osType": "Linux",
      "availabilityZones": ["1", "2", "3"]
    },
    {
      "name": "workers",
      "orchestratorVersion": "1.19.9",
      "count": 2,
      "vmSize": "Standard_DS2_v2",
      "osDiskSizeGB": 128,
      "osDiskType": "Managed",
      "maxPods": 110,
      "mode": "User",
      "osType": "Linux",
      "availabilityZones": ["1", "2"]
    }
  ]
}
```
3. Wait for cluster to get created with AZs
4. Edit cluster --> Change NP name from `workers` to `workers2` in the above json

**Result:**
New NP will get created with no AZs

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Fixes:**
- [x] https://github.com/rancher/aks-operator/pull/21

**Comment by prabalsharma** [comment]
AZs are still not getting set for User Mode NPs on Edit. 

1. Create a cluster with System and User mode NP with AZs. Created NPs will have selected AZs
2. Wait for cluster to become active
3. Edit --> Add a new NP with AZ
4. Save
5. New NP **will not** have selected AZ. Can be checked from Azure node pools UI or Upstream Spec

tested on RC7,  master-3d465ee

**Comment by mjura** [comment]
Hi @prabalsharma 

AZ fix is available in RC8

**Comment by mjura** [comment]
I have merged update to system-charts https://github.com/rancher/system-charts/pull/480

**Comment by prabalsharma** [comment]
tested on master-2b50005ae, aks operator rc8
