### ISSUE TITLE
Project Monitoring V2

### ISSUE THREAD

**Issue by all4innov** [rancher/rancher#32974]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Project Monitoring when using Rancher V2.5.x

**Result:**
Project Monitoring is no more supported in version 2.5.x when using Monitoring V2

**Other details that may be helpful:**
If Project Monitoring V2 will not be fully supported like in Monitoring V1, it will interesting to produce a detailed documentation of how to deploy and configure a project level monitoring stack using the deployed Cluster Monitoring V2 / Prometheus Operator

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher v2.5.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom RKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud
- Kubernetes version (use `kubectl version`): 1.18

@aiyengar2 
@cloudnautique

**Comment by aiyengar2** [comment]
Hi @all4innov, in Rancher 2.6.5, Apps & Marketplace will have a new App called Prometheus Federator (https://github.com/rancher/prometheus-federator) that will allow users to set up Project Monitoring Stacks. It will be deployable alongside an existing chart that deploys Prometheus Operator, such as Monitoring V2.

Please upgrade to 2.6.5 to use this new feature!
