### ISSUE TITLE
Limit cluster resource(s) visibility in Rancher GUI

### ISSUE THREAD

**Issue by dominicpg** [rancher/rancher#32986]
Cluster resource dashboard (ie Global Tab in Rancher GUI) is always accessible under user login session though the user is permitted to access a particular project with a defined resource quota. If Rancher GUI exposes the total CPU/Memory/Nodes of downstream cluster, it rather creates confusion on resource quota set against a particular project, especially in multi-tenancy scenario/env.

Appreciate if you could add new project role(s) to limit the visibility on downstream cluster {or/and} add option to list project quota set(if any) instead total resources. The best I could mask is the node count and attached a screenshot.

This is reproducible always 
1) create a project, set resource quota and associate a user
2) login Rancher GUI as user, Global tab will list underlying RKE cluster resources - Total {nodes, CPU, Memory}

Version - Rancher v2.5.8

**Comment by alharkan** [comment]
When Rancher using a single cluster for multiple users. and the single cluster is used for multi-tenancy. 
The user has access to his/her particular project with limited resources. 

The user still able to view the whole cluster resources (Total Cluster Memory/CPU/#PODs ) even the role of the user-specified to a specific project only. 



The below screenshots from the user dashboard that has access to a specific project only, and here he/she still able to see the whole cluster information: 

![Rancher-1](https://user-images.githubusercontent.com/35840256/120917258-e3047600-c6b6-11eb-90a6-89d6f8807bbb.PNG)
![Rancher-2](https://user-images.githubusercontent.com/35840256/120917259-e7c92a00-c6b6-11eb-860c-963e92110a62.PNG)

**Comment by vincent99** [comment]
These are basic properties of the cluster on the same level as other important things like what version of k8s it is.  There is no field-level RBAC control in k8s to grant access to part of the fields of a resource.
