### ISSUE TITLE
RKE2 Adding new pools to an active cluster is creating new nodes in the backend but is stuck in provisioning

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#32995]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a node deriver DO cluster 1 node all roles
2. Once the cluster is up and active, scale up the cluster by editing the config and add a new pool with 2 etcd node roles
3. Nodes are created in the DO but the cluster is stuck in provisioning.
**Result:**
Cluster should have come up active with the new pools added

**Other details that may be helpful:**

This happens only on the kubernetes version `v1.21.1-alpha4+rke2r1` but not on  `v1.21.1-alpha5+rke2r1`
Error message seen in the yaml file:
```
    message: non-ready etcd machine(s) anu-etcd4-pool2-5578c85b7-kwz46,anu-etcd4-pool2-5578c85b7-r6c2f
    reason: Waiting
    status: Unknown
    type: Provisioned
```

**cluster yaml file:**
[anu-etcd4.txt](https://github.com/rancher/rancher/files/6586744/anu-etcd4.txt)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head 618c9ef
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Node driver
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): 

v1.21.1-alpha4+rke2r1

**Comment by kinarashah** [comment]
@anupama2501 Etcd only nodes currently don't work because of https://github.com/rancher/rancher/issues/32362 . I've confirmed that scaling up works with other role combinations - 1 etcd+cp pool and 1 worker pool, or scaling up all role nodes. I tested with `v1.21.3-rc1+rke2r2` available on latest master-head. Moving it to test.

**Comment by anupama2501** [comment]
Verified on 30574c2

1. Created an rke2 node driver DO cluster with all roles
2. Once the cluster is active, edited and added additional pool for etcd
3. Cluster has come up fine
4. Edited and added one more pool for the worker nodes, cluster has come up fine
