### ISSUE TITLE
aksV2- cannot edit imported clusters

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32999]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

1. master-618c9efe52856daff6a534097bd927b69f03f4e4-head
2. Edit a cluster created from api or Edit a Registered (imported)  cluster 

**Result:**
`DNS Prefix *` gets set to `n/a`, resulting in `"DNS Prefix" is required` error on edits

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

Fix: https://github.com/rancher/aks-operator/pull/24

**Comment by mjura** [comment]
According to Azure API response changing property dnsPrefix is not allowed

Original Error: Code="PropertyChangeNotAllowed" Message="Changing property 'dnsPrefix' is not allowed." Target="dnsPrefix", requeuing

**Comment by prabalsharma** [comment]
> According to Azure API response changing property dnsPrefix is not allowed
> 
> Original Error: Code="PropertyChangeNotAllowed" Message="Changing property 'dnsPrefix' is not allowed." Target="dnsPrefix", requeuing

Correct, it not about editing `dnsPrefix`. It about editing editable fields. This is not possible as `dnsPrefix` value is not set correctly for imported clusters or clusters created via api.

**Comment by prabalsharma** [comment]
Tested on master-b2f8824 (rc7)

**Comment by prabalsharma** [comment]
tested on master-2b50005, aks operator rc8
