### ISSUE TITLE
Blank space should not be allowed as or in username or password

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3299]
version - master 01/14

Steps:
1.  Authenticate using Local Auth
2.  Go to Accounts
3.  Add Account and enter a blank space as username or password, save

Results:
Allows you to save with blank spaces

Expected:
Should not allow spaces in username or password at all.

**Comment by vincent99** [comment]
Username ok, but space is a perfectly cromulent password character.

**Comment by cjellick** [comment]
cromulent? really?

**Comment by vincent99** [comment]
@cjellick Sounds like you need to embiggen your vocabulary.

![image](https://cloud.githubusercontent.com/assets/753917/12367742/dc7ec98c-bba1-11e5-9f5a-064d06efe6a4.png)

**Comment by cjellick** [comment]
:+1:

**Comment by tfiduccia** [comment]
Version - master 3/9
Verified fixed
