### ISSUE TITLE
GKEv2 Access scopes for NP: "access to all Cloud APIs" & "Set access for each API"- not getting enabled

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#32994]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

- master-618c9efe52856daff6a534097bd927b69f03f4e4-head
- Create GKE cluster
- NP Access scopes
- Select `Allow full access to all Cloud APIs`

**Result:**
looks like `Default` access scope get enabled, instead of `Cloud Platform`

Same is true for `Set access for each API` options. 
**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cmurphy** [comment]
It looks like the UI always sends the same six scopes no matter which radio button is selected:

![image](https://user-images.githubusercontent.com/1220710/120712430-76e6ff80-c475-11eb-81a7-eb167906047c.png)

@westlywright could you have a look?

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `0ab00d7`**

- Create GKE cluster
- NP Access scopes
- Select `Allow full access to all Cloud APIs`

```
oauthScopes: ["https://www.googleapis.com/auth/cloud-platform"]
0: "https://www.googleapis.com/auth/cloud-platform"
```
- In the backend:
<img width="547" alt="Screen Shot 2021-08-07 at 5 01 44 PM" src="https://user-images.githubusercontent.com/26032343/128616604-8b3860aa-eee7-4286-87af-54c8632d0c82.png">
