### ISSUE TITLE
Basic Auth prompt when I'm on Login screen

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3300]
version - master 01/14

Steps:
Steps:
1. Authenticate using Local Authentication
2. Create a user under Accounts
3. Log in as that user in Firefox
4. Go to Change password
5. Cancel out of overlay
6. Logout and start typing in username

Results:
The Authentication Required overlay drops down.  Nothing I put in there is correct I have to Cancel out and enter info in Rancher Username/Password.  In Chrome it just throws the connection error.
![image](https://cloud.githubusercontent.com/assets/11514927/12363661/3fe8c178-bb87-11e5-9119-3d7811674519.png)

![image](https://cloud.githubusercontent.com/assets/11514927/12363668/4f6ccf86-bb87-11e5-9f44-f83dc538173a.png)

Expected:
Should not drop-down auth required overlay, should not throw error

**Comment by vincent99** [comment]
Can you still get this to happen?  I think it was from the subscribe websocket trying to reconnect.

**Comment by tfiduccia** [comment]
Version - master 3/8
Verified fixed
