### ISSUE TITLE
Can't retrieve Docker Info: error during connect

### ISSUE THREAD

**Issue by timvol** [rancher/rancher#33006]
**What kind of request is this (question/bug/enhancement/feature request):** Question

**Steps to reproduce (least amount of steps as possible):**

Rancher is running outside the cluster I'm trying to manage. I simply create a new cluster (in my case using the Hetzner Node Driver) and wait for provisioning. The entire installation and configuration of the nodes works perfectly, but at the end it stucks at "Waiting to register with Kubernetes".

In the logs, I can see the following output:

```
2021/06/03 07:13:00 [INFO] Creating cluster [c-hqkn7]
2021/06/03 07:13:05 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:46637
2021/06/03 07:13:05 [INFO] cluster [c-hqkn7] provisioning: Initiating Kubernetes cluster
2021/06/03 07:13:05 [INFO] [certificates] Generating CA kubernetes certificates
2021/06/03 07:13:05 [INFO] cluster [c-hqkn7] provisioning: [dialer] Setup tunnel for host [157.90.xxx.xxx]
2021/06/03 07:13:05 [ERROR] cluster [c-hqkn7] provisioning: Failed to set up SSH tunneling for host [157.90.xxx.xxx]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-hqkn7:m-pngvb]
2021/06/03 07:13:05 [ERROR] cluster [c-hqkn7] provisioning: Removing host [157.90.xxx.xxx] from node lists
2021/06/03 07:13:05 [ERROR] cluster [c-hqkn7] provisioning: [state] can't fetch legacy cluster state from Kubernetes: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [157.90.xxx.xxx]
2021/06/03 07:13:05 [INFO] [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
2021/06/03 07:13:05 [INFO] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
2021/06/03 07:13:05 [INFO] [certificates] Generating Kubernetes API server certificates
2021/06/03 07:13:05 [INFO] [certificates] Generating Service account token key
2021/06/03 07:13:05 [INFO] [certificates] Generating Kube Controller certificates
2021/06/03 07:13:06 [INFO] [certificates] Generating Kube Scheduler certificates
2021/06/03 07:13:06 [INFO] [certificates] Generating Kube Proxy certificates
2021/06/03 07:13:06 [INFO] [certificates] Generating Node certificate
2021/06/03 07:13:06 [INFO] [certificates] Generating admin certificates and kubeconfig
2021/06/03 07:13:07 [INFO] [certificates] Generating Kubernetes API server proxy client certificates
2021/06/03 07:13:07 [INFO] cluster [c-hqkn7] provisioning: Successfully Deployed state file at [management-state/rke/rke-471135093/cluster.rkestate]
2021/06/03 07:13:07 [INFO] kontainerdriver rancherkubernetesengine stopped
2021/06/03 07:13:07 [INFO] cluster [c-hqkn7] provisioning: Building Kubernetes cluster
2021/06/03 07:13:07 [ERROR] cluster [c-hqkn7] provisioning: Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config
2021/06/03 07:13:07 [ERROR] error syncing 'c-hqkn7': handler cluster-provisioner-controller: Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config, requeuing
```

**Other details that may be helpful:**

I'm starting the Rancher container using `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:latest`. The container is reachable via https://localhost.

I already checked other (already solved) issues but none of these solved my issue.

**Environment information**
- Rancher 2.5.8 (Docker Hub container image)

**Comment by superseb** [comment]
`The container is reachable via https://localhost.` Not sure if you also configured this as `server-url` when you logged into Rancher, this needs to be a resolvable and accessible address for the agent that is started on the created node so it can connect to Rancher and set up the tunnel that is needed to provision the node.

The logs of the created `rancher/rancher-agent` container on the created node will also reveal why it cannot connect to Rancher.

**Comment by timvol** [comment]
Ah, okay. I see... no, since it's a locally installed Rancher (Docker) instance, it cannot connect to Rancher. I guess this already answers/solves the problem. But just a small question... what's the reason that Rancher must be resolvable/accessible address? I assumed Rancher works the other direction (Rancher connects to the Nodes and not vice versa).
