### ISSUE TITLE
No Login with Keycloak button in the Ember UI if we enable Keycloak OIDC

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#33018]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Login to the latest rancher `master-head` build
- Enable Keycloak OIDC
- Logout
- Here we see the Login with Keycloak button in the Vue login path `/dashboard/auth/login`
- Change the login url path to `/login`

**Result:**

Ember UI has no `Log in with Keycloak` button.

<img width="750" alt="Screen Shot 2021-06-03 at 11 07 14 AM" src="https://user-images.githubusercontent.com/27659/120691934-f536a800-c45b-11eb-9d37-2d005e8d1446.png">

**Other details that may be helpful:**

Dashboard has it

<img width="745" alt="Screen Shot 2021-06-03 at 11 07 23 AM" src="https://user-images.githubusercontent.com/27659/120691962-01bb0080-c45c-11eb-827b-c433127ef3df.png">

**Environment information**
- Rancher version: `2.6 master-head (06/03/2021)` _be03c8bd1_
- Installation option: HA RKE1

**Comment by richard-cox** [comment]
In 2.6 logging in via the old cluster manager will no longer officially be supported, access should be via the cluster dashboard only
