### ISSUE TITLE
Backport 2.5: [monitoring v2] sometimes unable to upgrade from 9.4.202 -> 14.5.100, workaround to upgrade a 2nd time

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#33015]
Backport and test fix in 2.5 for https://github.com/rancher/rancher/issues/32025.

**Comment by aiyengar2** [comment]
Also should test that this resolves https://github.com/rancher/rancher/issues/29171.

**Comment by thehejik** [comment]
Tested on `rancher/rancher:2.5.8` on custom RKE1 cluster.

Used chart repo `dev-v2.5` commit: `fae0bf3eabad5fb902e4bda7b87fd1b14034456c`

Tried upgrade to latest v2 monitoring 14.5.100 and 16.6.0 several times (~10x) from versions 9.4.{201,202,203} and 14.5.100. 

I was unable to reproduce the original issue `unknown field "alertmanagerConfigNamespaceSelector"` on v2.5.

The older versions incl. 203 are time to time failing to deploy due the missing CRD #29171 issue but this is not the case for newer charts versions 14.5.100 and 16.6.0 which were always installed without the CRD failure.

As I was always able to install the v2 monitoring charts in versions 14.5.100 and 16.6.0 and also update to these versions from previous versions I'd say it is fixed.

Close.
