### ISSUE TITLE
Allow PNI to be enabled for generic imported clusters

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#33016]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Result:**
When using the generic import cluster option in Rancher, users should be able to specify that Project Network Isolation should be enabled. 

**Other details that may be helpful:**
There isn't a way to ensure the generic imported cluster supports NetworkPolicy resources, so this will need to be ensured by the user performing the import. There should be a messgae/tooltip around the `Enable Project Network Isolation` option to make this clear to users. Something like: `The imported cluster needs to support Kubernetes NetworkPolicy resources for Project Network Isolation to take effect` should suffice.

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 6b430f3` with the following steps.
Provision a single node RKEv1 cluster (rke version v1.2.8)
From ember UI, import the cluster using generic import. Enable `Project Network Isolation` under `Advanced Options`:
![Screen Shot 2021-06-11 at 4 06 59 PM](https://user-images.githubusercontent.com/57409052/121756729-f60cb100-cacf-11eb-81d2-bb9f0e710e32.png)
Cluster becomes active.

Result:
`appliedEnableNetworkPolicy` is set in API
```
"appliedEnableNetworkPolicy": true,
"appliedPodSecurityPolicyTemplateId": "",
```
Did not see `hn-nodes` and `np-default` network policies get created on import:
```
> kubectl get networkpolicies -A
NAMESPACE       NAME                                POD-SELECTOR                                             AGE
fleet-system    default-allow-all                   <none>                                                   58m
ingress-nginx   hp-nginx-ingress-controller-cplm9   field.cattle.io/podName=nginx-ingress-controller-cplm9   58m
```
Did not see network policies get created on new namespace in default project:
```
> kubectl get networkpolicies -n testns
No resources found in testns namespace.
```

**Comment by ryansann** [comment]
@aaronRancher this looks like the same issue as before where namespaces weren't getting projectId labels.. can you confirm if all namespaces have their proper projectId labels in your tests?

**Comment by aaronRancher** [comment]
@ryansann On `master-head` `5715b8a`, I am able to see the projectId label in newly created namespaces. Network policies are not created in these namespaces.
![Screen Shot 2021-06-14 at 5 27 23 PM](https://user-images.githubusercontent.com/57409052/121975199-e7273800-cd35-11eb-8784-60f6c138cea3.png)

**Comment by ryansann** [comment]
@aaronRancher I just tested generic cluster import with the original version you used above: `6b430f3` and I don't see any `projectId` labels on the namespaces in the imported cluster. This is why the `NetworkPolicy` resources are not being created. Would you mind updating to a newer version that includes the fix for this and retesting? E.g. the second version you used: `5715b8a`

Here is a screenshot of default namespace for an imported cluster using Rancher version: `6b430f3`
<img width="1159" alt="Screen Shot 2021-06-15 at 4 09 59 PM" src="https://user-images.githubusercontent.com/8824599/122134848-45b2eb80-cdf4-11eb-8fb5-67908e2da849.png">
Note the missing label.

After upgrading to `5715b8a`, I see the `projectId` label is there and enabling PNI works as expected.

**Comment by aaronRancher** [comment]
QA to do:
- Provision a single node RKEv1 cluster (rke version v1.2.8)
- Provision a single install Rancher master-head setup
- Import the cluster into Rancher with PNI enabled
- Check the cluster for network policies with `kubectl get networkpolicies -A`. Verify `hn-nodes` and `np-default` network policies are available.
- Create a new namespace in the default project and verify `hn-nodes` and `np-default` network policies are available. `kubectl get networkpolicies -n <namespace name>`

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version c7f3cce` with RKE version v1.3.0-rc7

Network policies are available on an imported RKEv1 cluster with PNI enabled.
```
> kubectl get networkpolicies -A
NAMESPACE             NAME                   POD-SELECTOR   AGE
cattle-fleet-system   default-allow-all      <none>         7m39s
cattle-fleet-system   np-default-allow-all   <none>         7m39s
cattle-system         np-default-allow-all   <none>         7m41s
default               hn-nodes               <none>         7m41s
default               np-default             <none>         7m41s
ingress-nginx         np-default-allow-all   <none>         7m41s
kube-node-lease       np-default-allow-all   <none>         7m41s
kube-public           np-default-allow-all   <none>         7m41s
kube-system           np-default-allow-all   <none>         7m40s
```
Network policies are available in new namespaces:
```
> kubectl get networkpolicies -n testns
NAME         POD-SELECTOR   AGE
hn-nodes     <none>         8s
np-default   <none>         8s
```

Tested an upgrade scenario from `v2.5.8` to `master-head` `version c7f3cce` with the following steps:
Deploy a single install Rancher `v2.5.8`
Upgrade to master-head
Import an RKEv1 cluster with PNI enabled.
Verified network policies are available on an imported RKEv1 cluster with PNI enabled. And in newly created namespaces.
