### ISSUE TITLE
cattle-cluster-agent has no resource requests or limits - if all CPU/RAM gets consumed on cluster, agent dies and cluster is unreachable

### ISSUE THREAD

**Issue by jbilliau-rcd** [rancher/rancher#33011]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature Request. Cattle-cluster-agent that gets deployed via a kubectl command upon importing a cluster into Rancher should be able to have defined resource requests/limits.

**Steps to reproduce (least amount of steps as possible):**

Look at the deployment yaml of the cattle-cluster-agent upon importing a cluster into Rancher. 

**Result:**

resources: []

**Other details that may be helpful:**

We had a developer pod run amuck, scale up to 20 pods, and soak up all the CPU on the cluster. This caused the cattle-cluster-agent to basically choke and cluster DC'ed from Rancher. Luckily this was nonprod but if production, it wouldve been a big deal. **Cattle-cluster-agent** should be able to have resource requests defined so that it is guaranteed CPU/RAM to function in the case of a cluster running out of resources event.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): EKS

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted / EKS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): EC2 - 4 CPU / 8GB
- Kubernetes version (use `kubectl version`): 1.19

**Comment by shpwrck** [comment]
https://github.com/rancher/rancher/blob/54d4afc27c36814fe067a47a232463e0e5681da9/pkg/systemtemplate/template.go

Would be simple enough to update. We just need to figure out reasonable defaults or how to configure it.

**Comment by jbilliau-rcd** [comment]
We have a fairly busy cluster and these are the current usage metrics of the cattle-cluster-agent:

![image](https://user-images.githubusercontent.com/69006307/122459867-72dfd500-cf7f-11eb-89c2-3dc695a1b61a.png)

So it doesn't look like it needs much. I looked at 8 other clusters, they all roughly those same amounts. Maybe:

```
resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
```

**Comment by jbilliau-rcd** [comment]
@shpwrck  any update on this?

**Comment by jbilliau-rcd** [comment]
any update on this guys? This currently allows for a runaway service to take down a cluster and detach it from Rancher.
