### ISSUE TITLE
Local cluster in a HA setup shows 4 nodes when only 3 nodes are in the cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33020]
**What kind of request is this (question/bug/enhancement/feature request):**

**Steps to reproduce (least amount of steps as possible):** bug

**Result:**

- Deploy an RKE cluster using 1.3.0-rc3 - 3 nodes all roles.
- Deploy rancher on this using self signed certs (installation steps from rancher docs)
- When the rancher server comes up, local cluster is seen having 4 nodes instead of 3
- View in API of the local cluster in Ember UI shows 4 nodes.

**Other details that may be helpful:**

- This does _NOT_ happen always
- This is _not_ seen on 2.5.8

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): HA

**Comment by Jono-SUSE-Rancher** [comment]
@sowmyav27 - Does doing anything with the certs have anything to do with this? Does this happen if you don't use self signed certs?
Can you confirm which specific commit of master you're on? Sorry this is just really hard to siphon into a bucket since it doesn't happen all the time and it doesn't happen in 2.5.8 which means it's a regression on master that we need to look at.

**Comment by izaac** [comment]
I've sometimes seen this with k3s imported clusters, it doesn't happen all the time.

Steps:

- Create a single instance (CentOS 7.9, or CentOS 8.3)
- Install k3s `curl -sfL https://get.k3s.io | sh -`
- Import the cluster on Rancher

I sometimes see 1 or 2 duplicates of the same node on Ember only.

**Comment by izaac** [comment]
![Screen Shot 2021-06-10 at 3 55 26 PM](https://user-images.githubusercontent.com/27659/121607228-85e52900-ca04-11eb-9258-69a778646b2a.png)

**Comment by izaac** [comment]
![Screen Shot 2021-06-10 at 3 55 26 PM](https://user-images.githubusercontent.com/27659/121607283-9d241680-ca04-11eb-913f-7dc740c89367.png)

**Comment by git-ival** [comment]
I've also encountered this during scale testing with k3s imported clusters on the updated UI.

In the screenshots below my downstream clusters should only be reporting 1 node and the local cluster should only be reporting 4 nodes. (The cluster health check errors are probably not relevant to this issue, they are an artifact of the scale testing).

![Screen Shot 2021-07-28 at 3 09 59 PM](https://user-images.githubusercontent.com/85186645/127381852-c367ef4e-f9b5-4884-a149-20b2519b2675.png)
![Screen Shot 2021-07-28 at 3 10 25 PM](https://user-images.githubusercontent.com/85186645/127381893-350fe2e4-7e98-4703-925e-4ed1b5eb359e.png)

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `0ab00d79`**

- Local imported RKE1 cluster in a HA setup has the right number of nodes.
