### ISSUE TITLE
Add Enable PNI Option for EKS Clusters

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#33028]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

In order to support Project Network Isolation for EKS clusters, there needs to be a UI option for `Enable Project Network Isolation` on the EKS provisioning page AND on the EKS cluster import page.

For RKE clusters, this option appears in the `Kubernetes Options` section of the provisioning page. Something similar can be done for the EKS import cluster page. 

Checking this option, i.e. Enabling PNI, should set `enableNetworkPolicy` on the cluster object to `true`

**Comment by codyrancher** [comment]
The option was added here on eks
![image](https://user-images.githubusercontent.com/55104481/138342913-70c93f51-4e3c-4bbf-933e-e94f7cc397b0.png)

**Comment by Jono-SUSE-Rancher** [comment]
@codyrancher (cc: @gaktive) - The backend Rancher team has bumped this to v2.6.4. Would you guys be able to temporarily roll-back the front end UI change for this because adding the checkbox won't work since the backend won't support it (yet).

**Comment by snasovich** [comment]
Found this issue while doing housekeeping on "Team Hostbusters" issues. Since AKS/EKS/GKE are now owned by Team Highlander, moving it there.

**Comment by kkaempf** [comment]
Closing, too old, hasn't seen updates.
