### ISSUE TITLE
Add Enable PNI Option to Generic Cluster Import

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#33024]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

In order to support Project Network Isolation for generic imported clusters, there needs to be a UI option for `Enable Project Network Isolation`

For RKE clusters, this option appears in the `Kubernetes Options` section of the provisioning page. Something similar can be done for the generic import cluster page. 

Checking this option, i.e. Enabling PNI, should set `enableNetworkPolicy` on the cluster object to `true`

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 6b430f3` with the following steps.
Provision a single node RKE cluster (rke version v1.2.8)
From ember UI, import the cluster using generic import. Enable `Project Network Isolation` under `Advanced Options`:
![Screen Shot 2021-06-11 at 4 06 59 PM](https://user-images.githubusercontent.com/57409052/121756729-f60cb100-cacf-11eb-81d2-bb9f0e710e32.png)
Cluster becomes active.

Result:
`appliedEnableNetworkPolicy` is set in API
```
"appliedEnableNetworkPolicy": true,
"appliedPodSecurityPolicyTemplateId": "",
```
Did not see `hn-nodes` and `np-default` network policies get created on import:
```
> kubectl get networkpolicies -A
NAMESPACE       NAME                                POD-SELECTOR                                             AGE
fleet-system    default-allow-all                   <none>                                                   58m
ingress-nginx   hp-nginx-ingress-controller-cplm9   field.cattle.io/podName=nginx-ingress-controller-cplm9   58m
```
