### ISSUE TITLE
Update rancher-images generator to support feature and system charts min/max version constraint

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#33037]
Problem:
The airgap image exporter selects images from the latest version of each system and feature chart. This logic doesn't work for cases like monitoring v1 where we need to update old versions of it to keep support for older k8s versions and the images aren't included because only the latest version is being used.

Solution:
Update the image exporter to support exporting images in feature and system charts based on the Rancher version constraint set for each chart.

**Comment by cbron** [comment]
This was bumped to 2.6.1. We should unassign reviewers for now until we wrap up 2.6.0 work.

**Comment by ronhorton** [comment]
**Pass** Verified in `[v2.6.4-rc3](https://github.com/rancher/rancher/releases/tag/v2.6.4-rc3)`
This ticket added additional constraints and added support for version specific of constraints in images files. 
This also confirmed [Images from unused charts are in rancher-images.txt](https://github.com/rancher/rancher/issues/35687)
