### ISSUE TITLE
K3S-SERVER-CA internal certificate is expired today (4 JUN 2021). All ranchers becomes unavailable

### ISSUE THREAD

**Issue by mcfly722** [rancher/rancher#33047]
Hello, guys,
looks like today **4 jun 2021** expired your internal certificate for Rancher k3s API Server which works on https://127.0.0.1:6443 inside Rancher container. 

Our Rancher version is 2.4.3 and we also see this problem on higher versions f.e. on 2.4.15.
Restarting and recreating of new Rancher image from scratch with full images cleaning does not helps.
Looks like this certificate hardcoded some where in this Rancher image.

To view problem you can run inside Rancher container:
```
sh-4.4# curl --insecure -vvI https://127.0.0.1:6443
* Rebuilt URL to: https://127.0.0.1:6443/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 6443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=k3s; CN=k3s
*  start date: Oct 15 09:07:59 2019 GMT
*  expire date: Jun  4 12:35:47 2021 GMT <---------------------------------------------!!!!!!!!!!!! Expired !!!!!!!!!!!!
*  issuer: CN=k3s-server-ca@1571130479
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> HEAD / HTTP/1.1
> Host: 127.0.0.1:6443
> User-Agent: curl/7.58.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 401 Unauthorized
HTTP/1.1 401 Unauthorized
< Content-Type: application/json
Content-Type: application/json
< Www-Authenticate: Basic realm="kubernetes-master"
Www-Authenticate: Basic realm="kubernetes-master"
< Date: Fri, 04 Jun 2021 16:59:13 GMT
Date: Fri, 04 Jun 2021 16:59:13 GMT
< Content-Length: 165
Content-Length: 165
```

We also find **/var/lib/rancher/k3s/server/tls/server-ca.crt** certificate, and it expiration date is **12 Oct 2029**, but it looks like this cert file is not applied to k3s API configuration on container startup, and k3s uses old certificate from etcd or some other source.

Please, tell us,
how to apply this certificate (**/var/lib/rancher/k3s/server/tls/server-ca.crt**) to k3s API cluster and replace old one?

**Comment by mcfly722** [comment]
We rollback time on hosted VM to be able to connect to k3s cluster and replaced there **k3s-serving** in **kube-system** namespace  secret (PEM & Key parts) with new values from **/var/lib/rancher/k3s/server/tls/server-ca.key** and pem files. (Pem you can generate by joining .crt with .key files together)

**Comment by fzendron** [comment]
I have the exactly same problem, my rancher is 2.4.4.

**Comment by fzendron** [comment]
@mcfly722 can you describe what you did to solve?

**Comment by Serogava** [comment]
@fzendron 
You must to login to the host with rancher container via ssh.
Change date on the date before certificate expiration.
Enter to the rancher container with command:
```docker exec -it rancher /bin/bash```

Change certificate in the secret k3s.
Show current secret you can with command:
```kubectl get secret k3s-serving -n kube-system```

We take certificates from /var/lib/rancher/k3s/server/tls

Delete old secret:
kubectl delete secret k3s-serving -n kube-system
Add new secret:
```kubectl create secret tls my-tls-secret --cert=/var/lib/rancher/k3s/server/tls/server-ca.crt --key=/var/lib/rancher/k3s/server/tls/server- ca.key```

Then logout rancher container and set the current date.
Rancher container must restart.
