### ISSUE TITLE
Stack, Catalog and Host drop-down is messy

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3304]
Version 0.55.0-rc1

![image](https://cloud.githubusercontent.com/assets/11514927/12367953/ee6b8322-bba3-11e5-846b-f33b99e4eaeb.png)

![image](https://cloud.githubusercontent.com/assets/11514927/12367956/f88d176c-bba3-11e5-83d3-1aae9944d55d.png)

Issues:
- [ ] If I don't need the scroll bar the pane on right looks weird and shouldn't be there.  Only show scrollbar if needed
- [ ] Why does the search box at the top have double blue lines around it?
- [ ] Why is the text and images in the drop-down bigger then the selected catalog/stack/host at the top?  They should be the same size.

**Comment by vincent99** [comment]
- I think scrollbar is auto now
- The blue is the focus ring that all inputs have when focused
- Images are gone now

**Comment by tfiduccia** [comment]
Version - master 3/8
Verified fixed
