### ISSUE TITLE
aksv2 - Controller Manager and Scheduler showing as Not Applicable

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33045]
**What kind of request is this (question/bug/enhancement/feature request):** question

**Steps to reproduce (least amount of steps as possible):**
When I create AKS cluster from Rancher:

<img width="1357" alt="Screen Shot 2021-06-04 at 9 21 17 AM" src="https://user-images.githubusercontent.com/3749546/120833076-39867e80-c516-11eb-9e77-bb8d59b96e6f.png">

Is this expected?

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
I tested AKS Cluster Versions 1.18.17, 1.19.9, and 1.20.7 - Component Status in UI is working correctly. If you look at the API object there is no Component Status for CM and Scheduler, only ETCD. The UI looks for these status to exist other wise we show it NA. If these status are supposed to exist  then I believe this is a backend issue. 

cc: @gaktive @mjura

**Comment by mjura** [comment]
I have found in Rancher API 
```
"componentStatuses": [
{
"conditions": [
{
"message": "{\"health\":\"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-0",
"type": "/v3/schemas/clusterComponentStatus"
}
],
```
but I have no idea how this is set ? It might be `rancher-agent`, I have to investigate it

**Comment by mjura** [comment]
For AKS 1.19.9:
```
michal@Azure:~$ kubectl get componentstatus
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                       ERROR
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused
controller-manager   Unhealthy   Get "http://127.0.0.1:10252/healthz": dial tcp 127.0.0.1:10252: connect: connection refused
etcd-0               Healthy     {"health":"true"}
```

**Comment by mjura** [comment]
According what I have found this is correct, Azure currently is not offering health status for scheduler or controller-manager. Behavior is correct that this two checks are grayed out.

This bug can be invalid
