### ISSUE TITLE
system requirements??

### ISSUE THREAD

**Issue by rbucker** [rancher/rancher#3305]
I read some place that all I needed was 1GB or RAM. That seems pretty simple and if you look at the various systems from digital ocean and AWS then 1GB is still pretty simple, After I added sysdig my system ran for a day and then froze. A reboot failed too. ultimately dmesg indicated that there was no disk space remaining and until I determined that it was /var/lib/docker and /var/lib/journal it took a while to get the system back in service.

I would think that by now "people" (docker, coreos, rancher) know what the ideal server configuration is and not recommending 1GB is a good starting point.

**Comment by vincent99** [comment]
What does the RAM requirement have to do with disk space?

**Comment by rbucker** [comment]
when you look at the configurations from AWS and Digital Ocean the diskspace is nearly proportional to the RAM.  1GB Ram comes with 30GB of disk.  By the time the disk is partitioned the / partition (including /var/log) was only 3.8GB is size.

**Comment by vincent99** [comment]
A 1GB droplet with the default Ubuntu image is a 30GB root partition with over 25GB available after installing docker and starting `rancher/server`.  The 512MB has plenty of storage but not enough RAM to run OS+Java.

EC2 disk size is not coupled with RAM at all, every instance type defaults to a 8GB root which can be changed before or after launching the instance.  Leaving the default would of course not leave much space after installing OS+Docker+Rancher.

So maybe the requirements should say "Enough space to store the images you want to run", but this has nothing to do with RAM requirement, or having Rancher installed at all...

**Comment by deniseschannon** [comment]
@rbucker If you still have any questions on system requirements, please re-open.
