### ISSUE TITLE
Editing Git Repo resets the Authentication settings

### ISSUE THREAD

**Issue by jleni** [rancher/rancher#33059]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Go to Continuous Delivery / Git Repos 
- Select one repository and Edit Config
- Edit the Repository URL
- The authentication settings have not changed (they are set to SSH key)
- Click Save

**Result:**
The "Authentication" settings are removed. (blank)

**Other details that may be helpful:**
- You need to enter Edit Config again
- Set the authentication again
- Click save

This time the configuration is set correctly

**Environment information**
- Rancher version: 2.5.7
- Installation option (single install/HA): single

**Comment by slickwarren** [comment]
This was fixed in 2.5.8 https://github.com/rancher/dashboard/issues/2503
