### ISSUE TITLE
Unable to deploy EKS or GKE on hosted Rancher

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#33053]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
On Rancher v2.5.8 HA setup.
Bring up a hosted Rancher v2.5.8 setup by installing Rancher on an imported k3s cluster (tenant cluster).
Access the hosted Rancher setup as a global admin with full access.
Deploy an EKS or GKE cluster.

**Result:**
Cluster provisioning will fail with: `Failed to deploy eks-operator: can't find system project`

**Other details that may be helpful:**
This is because there is no system project in the local cluster of the tenant cluster. As a result, kev2 operators cannot find the system namespace to deploy into.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8
- Installation option (single install/HA): HA

**Comment by aaronRancher** [comment]
![Screen Shot 2021-06-04 at 3 36 34 PM](https://user-images.githubusercontent.com/57409052/120869650-c26bdd00-c54b-11eb-9a01-043a3d56af52.png)

**Comment by aaronRancher** [comment]
Thanks @prabalsharma. Are these issues caused by the same problem? Can this be closed as a duplicate?

**Comment by prachidamle** [comment]
@aaronRancher In your case above, was it the global Admin or restrictedAdmin or standard user trying to deploy EKS/GKE?

**Comment by prachidamle** [comment]
This issue does not seem related to restricted admin role because of two tests:
1) EKS provisioning works with restricted admin role on standalone rancher setup using 2.6/master
2) EKS provisioning  is broken for Global admin having all perms as well on v2.5.8 fresh install for hosted Rancher

**Comment by aaronRancher** [comment]
QA to do:
Test EKS, GKE, AKS deployment on hosted Rancher as global admin AND as restricted admin.

**Comment by thedadams** [comment]
2.6 seems to not be affected by this issue (master-head).

**Comment by aaronRancher** [comment]
GKEv2 provisioning on v2.5.10 is currently blocked by: https://github.com/rancher/rancher/issues/33721

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5-head` `version defd81c` with the following steps:
- Bring up a hosted Rancher setup by installing Rancher on an imported k3s cluster (tenant cluster).
- Log into tenant cluster Rancher.
- Create an EKSv2 and GKEv2 cluster.

Result:
The EKSv2 cluster is available in Rancher UI and EKS console. EKS operator version: `v1.0.10-rc1`. K8s version `v1.20.7-eks-8be107`
The GKEv2 cluster is available in Rancher UI and GKE console. GKE operator: `:v1.1.1-rc7`. K8s version `v1.20.8-gke.900`

AKSv2 will not be available in v2.5. AKSv1 clusters are provisioned successfully. k8s version `v1.20.7`
These steps were tested with global admin user and restricted admin. Clusters were provisioned using both users.
