### ISSUE TITLE
No Resources menu item on Global view

### ISSUE THREAD

**Issue by bengray2** [rancher/rancher#33058]
I am trying to follow the documentation to create a new Secret (certificate).   The documentation is https://rancher.com/docs/rancher/v2.5/en/k8s-in-rancher/certificates. 

The documentation says:

> From the **Global** view, select the project where you want to deploy your ingress.
> 
> From the main menu, select **Resources > Secrets > Certificates**. Click **Add Certificate**.
> 
> Enter a **Name** for the certificate.

 There is no **Resources** menu on the **Global** view.   This is version 2.5.8 (on version 2.4.4 there is such a menu).

![image](https://user-images.githubusercontent.com/44791530/120892883-a2274580-c653-11eb-924e-fa6398bfc010.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.8` UI: `v2.5.8` |
|Route|`undefined`|

**Comment by bengray2** [comment]
This is a brand new Rancher install that was installed using the command: 

docker run -d --restart=unless-stopped \
  -p 80:80 -p 8443:443 \
  --privileged \
  rancher/rancher:latest

There has been no other config / changes to this instance.

**Comment by vincent99** [comment]
You're missing the "select the project where you want to deploy your ingress" part.  Certificates are a resource that lives in one namespace (project) of one cluster, not global.

**Comment by bengray2** [comment]
@vincent99 Thank you, you're totally correct.  My eye was drawn to the bold text, and I missed that. Thanks!

**Comment by bengray2** [comment]
Closed, user error...
