### ISSUE TITLE
Rancher stable Repo issue with helm terraform

### ISSUE THREAD

**Issue by ayush121195** [rancher/rancher#33056]
I am trying to install a rancher with helm terraform.

Helm terraform version - helm v2.1.2
terraform - v0.15.4

**resource "helm_release" "rancher" {
  name       = "rancher-stable"
  chart      = "rancher-stable/rancher"
}**

This is my basic terraform file and when I try to execute it, I got this error.

helm_release.rancher: Creating...
╷
│ Error: failed to download "rancher-stable/rancher" (hint: running `helm repo update` may help)
│ 
│   with helm_release.rancher,
│   on main.tf line 2, in resource "helm_release" "rancher":
│    2: resource "helm_release" "rancher" {

I have tried the version and repository parameter as well but it is still not working with anyone.

could anyone help?

**Comment by aaronRancher** [comment]
Hello, @ayush121195.
Please make sure you have added the Helm chart repo. 
`helm repo add rancher-latest https://releases.rancher.com/server-charts/latest`
And run `helm repo update` to update information of available charts.
