### ISSUE TITLE
Does not support Single LogOut service for IDP?

### ISSUE THREAD

**Issue by hnc-yusop** [rancher/rancher#33062]
**What kind of request is this (question/**bug**/enhancement/feature request):**

BUG

I would like to do a single logout with my idp with SAML (using Keycloak solution).
However, the Rancher seems not to support for the logout.
I could not find any calling for SingleLogoutService URL of the SAML from source code.

**Steps to reproduce (least amount of steps as possible):**

   1. Login as “test_user” account by clicking “Log in with keycloak” from Rancher UI.
   2. Logout (“test_user” account) from Rancher UI.
   3. Again login as “test_user” account.
    → In this time the login is processed without any login id/password form UI.

I inteded to be single signed out the account on step 2.
Actually, I confirmed that the “test_user” session is alive into keycloak server.

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version : 2.5.8
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by karlsebal** [comment]
Still an issue in 2.7.3 and has been since some time now — see https://github.com/rancher/rancher/issues/28661 for instance.

**Comment by Montralis** [comment]
Some news on this?
