### ISSUE TITLE
Make topologyKey configurable in the value.yaml file 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#33061]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

Move the default value of `topologyKey` to the value.yaml file,  so we can configure it when installing Rnacher.

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by brendarearden** [comment]
Validation: PASSED

Reproduced with `--set rancherImageTag=v2.5.9` `--version v2.5.9`
Validation with `--set rancherImageTag=v2.6-head` `--version v2.6.0-rc1`

Steps to Reproduce:
**Check templating for `topologyKey` in `preferredDuringSchedulingIgnoredDuringExecution`**
1. helm install rancher with `helm install rancher rancher-latest/rancher --namespace cattle-system --create-namespace --set hostname=brenda.host --set rancherImageTag=v2.5.9  --set rancherImagePullPolicy=Always --version v2.5.9 --dry-run --set topologyKey=topology.kubernetes.io/zone` 
2. Find the topologyKey in the output for `kind: Deployment` in `spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution` and see the value is `topologyKey: kubernetes.io/hostname` and it did not change to the value that was passed in

**Check templating for `topologyKey` in `requiredDuringSchedulingIgnoredDuringExecution`**
1. helm install rancher with `helm install rancher rancher-latest/rancher --namespace cattle-system --create-namespace --set hostname=brenda.host --set rancherImageTag=v2.5.9  --set rancherImagePullPolicy=Always --version v2.5.9 --dry-run --set topologyKey=topology.kubernetes.io/zone --set antiAffinity=required`  
2. Find the topologyKey in the output for `kind: Deployment` in `spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution` and see the value is `topologyKey: kubernetes.io/hostname` and it did not change to the value that was passed in

Steps to Validate: 
**Check templating for `topologyKey` in `preferredDuringSchedulingIgnoredDuringExecution`**
1. helm install rancher with `helm install rancher rancher-latest/rancher --namespace cattle-system --create-namespace --set hostname=brenda.host --set rancherImageTag=v2.6-head  --set rancherImagePullPolicy=Always --version v2.6.0-rc1 --dry-run --set topologyKey=topology.kubernetes.io/zone` 
2. Find the topologyKey in the output for `kind: Deployment` in `spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution` and see the value is `topologyKey: topology.kubernetes.io/zone` and it matches the value that was passed in

**Check templating for `topologyKey` in `requiredDuringSchedulingIgnoredDuringExecution`**
1. helm install rancher with `helm install rancher rancher-latest/rancher --namespace cattle-system --create-namespace --set hostname=brenda.host --set rancherImageTag=v2.6-head  --set rancherImagePullPolicy=Always --version v2.6.0-rc1 --dry-run --set topologyKey=topology.kubernetes.io/zone --set antiAffinity=required`  
2. Find the topologyKey in the output for `kind: Deployment` in `spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution` and see the value is `topologyKey: topology.kubernetes.io/zone` and it matches the value that was passed in

**Check that default value works as expected in `preferredDuringSchedulingIgnoredDuringExecution`**
1. helm install rancher and do not set topologyKey value with `helm install rancher rancher-latest/rancher --namespace cattle-system --create-namespace --set hostname=brenda.host --set rancherImageTag=v2.6-head  --set rancherImagePullPolicy=Always --version v2.6.0-rc1 --dry-run` 
2. Find the topologyKey in the output for `kind: Deployment` in `spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution` and see the value is `topologyKey: kubernetes.io/hostname` and it matches the value from the values.yaml for `topologyKey: kubernetes.io/hostname`

**Check that default value works as expected in  `requiredDuringSchedulingIgnoredDuringExecution`**
1. helm install rancher and do not set topologyKey value with `helm install rancher rancher-latest/rancher --namespace cattle-system --create-namespace --set hostname=brenda.host --set rancherImageTag=v2.6-head  --set rancherImagePullPolicy=Always --version v2.6.0-rc1 --dry-run --set antiAffinity=required`  
2. Find the topologyKey in the output for `kind: Deployment` in `spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution` and see the value is `topologyKey: kubernetes.io/hostname` and it matches the value from the values.yaml for `topologyKey: kubernetes.io/hostname`
