### ISSUE TITLE
Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s)

### ISSUE THREAD

**Issue by springfred** [rancher/rancher#33060]
**What kind of request is this (question/bug/enhancement/feature request):**
I am trying to deploy rancher cluster in k3s Enviroment. I have created the pre-requisites for k3s Cluster

![image](https://user-images.githubusercontent.com/23000050/120925205-21775080-c70a-11eb-9cd8-c0a9b9c90f85.png)

Env: Rancher v2.5.7 
Issue: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s)
Logs: I am facing the below error logs:

**Steps to reproduce (least amount of steps as possible):**

**Result:**
```
INFO: Arguments: --server https://rancher.devops.com --token REDACTED --ca-checksum 461e81db9bcf3825e21e7f8cc6adf2514edab293a12572c54a1688d422c167c4 --address 192.168.2.191 --etcd --controlplane
INFO: Environment: CATTLE_ADDRESS=192.168.2.191 CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=knode01 CATTLE_ROLE=,etcd,controlplane CATTLE_SERVER=https://rancher.devops.com CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 10.90.5.1 nameserver 192.168.2.1
INFO: https://rancher.devops.com/ping is accessible
INFO: rancher.devops.com resolves to 192.168.2.181
INFO: Value from https://rancher.devops.com/v3/settings/cacerts is an x509 certificate
time="2021-06-06T12:34:53Z" level=info msg="Listening on /tmp/log.sock"
time="2021-06-06T12:34:53Z" level=info msg="Rancher agent version v2.5.7 is starting"
time="2021-06-06T12:34:53Z" level=info msg="Option customConfig=map[address:192.168.2.191 internalAddress: label:map[] roles:[etcd controlplane] taints:[]]"
time="2021-06-06T12:34:53Z" level=info msg="Option etcd=true"
time="2021-06-06T12:34:53Z" level=info msg="Option controlPlane=true"
time="2021-06-06T12:34:53Z" level=info msg="Option worker=false"
time="2021-06-06T12:34:53Z" level=info msg="Option requestedHostname=knode01"
time="2021-06-06T12:34:54Z" level=info msg="Connecting to wss://rancher.devops.com/v3/connect/register with token d9k8d7t7m6wfckhzrs9dnwcwqs4fz4452v7dxdn958k6ftw5vs76nj"
time="2021-06-06T12:34:54Z" level=info msg="Connecting to proxy" url="wss://rancher.devops.com/v3/connect/register"
time="2021-06-06T12:34:54Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"
time="2021-06-06T12:34:56Z" level=info msg="Starting plan monitor, checking every 15 seconds"
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): HA(etcd)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:42 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:19:17 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Docker info (use `docker info`):

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 19.03.14
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.6.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.67GiB
 Name: knode01
 ID: DDOJ:DACT:SAE2:ZUNQ:6QOG:YW44:F2GT:S5TS:XOMC:CGRT:4NHY:44IY
 Docker Root Dir: /data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry.devops.com
  127.0.0.0/8
 Registry Mirrors:
 Live Restore Enabled: false
```

**Comment by superseb** [comment]
Please share all `rancher/rancher-agent` container logs from every node, as well as the logs from the `rancher/rancher` container/container in pod where it shows it tries to provision.

**Comment by springfred** [comment]
knode01(etcd/Control Plane)
`
[root@knode01 ~]# docker ps -a
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS               NAMES
0711b7ecf657        registry.devops.com/rancher/rancher-agent:v2.5.7   "run.sh --server htt…"   13 hours ago        Up 13 hours                             pensive_shtern
[root@knode01 ~]# docker logs -f 0711b7ecf657
INFO: Arguments: --server https://rancher.devops.com --token REDACTED --ca-checksum 461e81db9bcf3825e21e7f8cc6adf2514edab293a12572c54a1688d422c167c4 --address 192.168.2.191 --etcd --controlplane
INFO: Environment: CATTLE_ADDRESS=192.168.2.191 CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=knode01 CATTLE_ROLE=,etcd,controlplane CATTLE_SERVER=https://rancher.devops.com CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 10.90.5.1 nameserver 192.168.2.1
INFO: https://rancher.devops.com/ping is accessible
INFO: rancher.devops.com resolves to 192.168.2.181
INFO: Value from https://rancher.devops.com/v3/settings/cacerts is an x509 certificate
time="2021-06-06T12:34:53Z" level=info msg="Listening on /tmp/log.sock"
time="2021-06-06T12:34:53Z" level=info msg="Rancher agent version v2.5.7 is starting"
time="2021-06-06T12:34:53Z" level=info msg="Option customConfig=map[address:192.168.2.191 internalAddress: label:map[] roles:[etcd controlplane] taints:[]]"
time="2021-06-06T12:34:53Z" level=info msg="Option etcd=true"
time="2021-06-06T12:34:53Z" level=info msg="Option controlPlane=true"
time="2021-06-06T12:34:53Z" level=info msg="Option worker=false"
time="2021-06-06T12:34:53Z" level=info msg="Option requestedHostname=knode01"
time="2021-06-06T12:34:54Z" level=info msg="Connecting to wss://rancher.devops.com/v3/connect/register with token d9k8d7t7m6wfckhzrs9dnwcwqs4fz4452v7dxdn958k6ftw5vs76nj"
time="2021-06-06T12:34:54Z" level=info msg="Connecting to proxy" url="wss://rancher.devops.com/v3/connect/register"
time="2021-06-06T12:34:54Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"
time="2021-06-06T12:34:56Z" level=info msg="Starting plan monitor, checking every 15 seconds"

`

knode02(etcd/Control Plane)
`
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS               NAMES
fc83698cbaa0        registry.devops.com/rancher/rancher-agent:v2.5.7   "run.sh --server htt…"   13 hours ago        Up 13 hours                             interesting_shtern
[root@knode02 ~]# docker logs -f fc83698cbaa0
INFO: Arguments: --server https://rancher.devops.com --token REDACTED --ca-checksum 461e81db9bcf3825e21e7f8cc6adf2514edab293a12572c54a1688d422c167c4 --etcd --controlplane
INFO: Environment: CATTLE_ADDRESS=192.168.2.192 CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=knode02 CATTLE_ROLE=,etcd,controlplane CATTLE_SERVER=https://rancher.devops.com CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 192.168.2.1
INFO: https://rancher.devops.com/ping is accessible
INFO: rancher.devops.com resolves to 192.168.2.181
INFO: Value from https://rancher.devops.com/v3/settings/cacerts is an x509 certificate
time="2021-06-06T12:37:15Z" level=info msg="Listening on /tmp/log.sock"
time="2021-06-06T12:37:15Z" level=info msg="Rancher agent version v2.5.7 is starting"
time="2021-06-06T12:37:15Z" level=info msg="Option customConfig=map[address:192.168.2.192 internalAddress: label:map[] roles:[etcd controlplane] taints:[]]"
time="2021-06-06T12:37:15Z" level=info msg="Option etcd=true"
time="2021-06-06T12:37:15Z" level=info msg="Option controlPlane=true"
time="2021-06-06T12:37:15Z" level=info msg="Option worker=false"
time="2021-06-06T12:37:15Z" level=info msg="Option requestedHostname=knode02"
time="2021-06-06T12:37:15Z" level=info msg="Connecting to wss://rancher.devops.com/v3/connect/register with token d9k8d7t7m6wfckhzrs9dnwcwqs4fz4452v7dxdn958k6ftw5vs76nj"
time="2021-06-06T12:37:15Z" level=info msg="Connecting to proxy" url="wss://rancher.devops.com/v3/connect/register"
time="2021-06-06T12:37:15Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"
time="2021-06-06T12:37:18Z" level=info msg="Starting plan monitor, checking every 15 seconds"

`

knode03(etcd/Control Plane)
`
[root@knode03 ~]# docker ps
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS               NAMES
226f6a3ad947        registry.devops.com/rancher/rancher-agent:v2.5.7   "run.sh --server htt…"   13 hours ago        Up 13 hours                             priceless_gagarin
[root@knode03 ~]# docker logs -f 226f6a3ad947
INFO: Arguments: --server https://rancher.devops.com --token REDACTED --ca-checksum 461e81db9bcf3825e21e7f8cc6adf2514edab293a12572c54a1688d422c167c4 --etcd --controlplane
INFO: Environment: CATTLE_ADDRESS=192.168.2.193 CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=knode03 CATTLE_ROLE=,etcd,controlplane CATTLE_SERVER=https://rancher.devops.com CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 192.168.2.1
INFO: https://rancher.devops.com/ping is accessible
INFO: rancher.devops.com resolves to 192.168.2.181
INFO: Value from https://rancher.devops.com/v3/settings/cacerts is an x509 certificate
time="2021-06-06T12:36:40Z" level=info msg="Rancher agent version v2.5.7 is starting"
time="2021-06-06T12:36:40Z" level=info msg="Option etcd=true"
time="2021-06-06T12:36:40Z" level=info msg="Option controlPlane=true"
time="2021-06-06T12:36:40Z" level=info msg="Option worker=false"
time="2021-06-06T12:36:40Z" level=info msg="Option requestedHostname=knode03"
time="2021-06-06T12:36:40Z" level=info msg="Option customConfig=map[address:192.168.2.193 internalAddress: label:map[] roles:[etcd controlplane] taints:[]]"
time="2021-06-06T12:36:40Z" level=info msg="Listening on /tmp/log.sock"
time="2021-06-06T12:36:41Z" level=info msg="Connecting to wss://rancher.devops.com/v3/connect/register with token d9k8d7t7m6wfckhzrs9dnwcwqs4fz4452v7dxdn958k6ftw5vs76nj"
time="2021-06-06T12:36:41Z" level=info msg="Connecting to proxy" url="wss://rancher.devops.com/v3/connect/register"
time="2021-06-06T12:36:41Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"
time="2021-06-06T12:36:43Z" level=info msg="Starting plan monitor, checking every 15 seconds"

`

knode04(work)
`
[root@knode04 ~]# docker ps -a
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS               NAMES
adb366c0a78b        registry.devops.com/rancher/rancher-agent:v2.5.7   "run.sh --server htt…"   13 hours ago        Up 13 hours                             epic_jang
[root@knode04 ~]# docker logs -f adb366c0a78b
time="2021-06-06T12:44:21Z" level=info msg="Listening on /tmp/log.sock"
time="2021-06-06T12:44:21Z" level=info msg="Rancher agent version v2.5.7 is starting"
time="2021-06-06T12:44:21Z" level=info msg="Option requestedHostname=knode04"
time="2021-06-06T12:44:21Z" level=info msg="Option customConfig=map[address:192.168.2.194 internalAddress: label:map[] roles:[worker] taints:[]]"
time="2021-06-06T12:44:21Z" level=info msg="Option etcd=false"
time="2021-06-06T12:44:21Z" level=info msg="Option controlPlane=false"
time="2021-06-06T12:44:21Z" level=info msg="Option worker=true"
time="2021-06-06T12:44:21Z" level=info msg="Connecting to wss://rancher.devops.com/v3/connect/register with token d9k8d7t7m6wfckhzrs9dnwcwqs4fz4452v7dxdn958k6ftw5vs76nj"
time="2021-06-06T12:44:21Z" level=info msg="Connecting to proxy" url="wss://rancher.devops.com/v3/connect/register"
time="2021-06-06T12:44:21Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"
time="2021-06-06T12:44:23Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"
time="2021-06-06T12:44:25Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"
time="2021-06-06T12:44:27Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering or etcd and controlplane node have to be registered first"

`

**Comment by superseb** [comment]
thats fine, what about Rancher's logging

**Comment by springfred** [comment]
Rancher's log
```
[root@k3s-server1 ~]# kubectl -n cattle-system get pod
NAME                              READY   STATUS    RESTARTS   AGE
rancher-68b7df7fd5-fjkxh          1/1     Running   0          25h
rancher-68b7df7fd5-hsnqx          1/1     Running   0          25h
rancher-68b7df7fd5-nhzms          1/1     Running   0          25h
rancher-webhook-b5b7b76c4-822vk   1/1     Running   0          24h

[root@k3s-server1 ~]# kubectl -n cattle-system logs -f rancher-68b7df7fd5-fjkxh

10:54:48 [INFO] kontainerdriver rancherkubernetesengine stopped
2021/06/07 10:54:48 [INFO] cluster [c-s4qd7] provisioning: Successfully Deployed state file at [management-state/rke/rke-860941641/cluster.rkestate]
2021/06/07 10:54:48 [INFO] cluster [c-s4qd7] provisioning: Building Kubernetes cluster
2021/06/07 10:54:48 [ERROR] Failed to connect to peer wss://10.42.3.6/v3/connect [local ID=10.42.4.4]: websocket: bad handshake
2021/06/07 10:54:48 [INFO] cluster [c-s4qd7] provisioning: [dialer] Setup tunnel for host [192.168.2.191]
2021/06/07 10:54:48 [INFO] cluster [c-s4qd7] provisioning: [dialer] Setup tunnel for host [192.168.2.192]
2021/06/07 10:54:49 [INFO] cluster [c-s4qd7] provisioning: [dialer] Setup tunnel for host [192.168.2.193]
2021/06/07 10:54:49 [ERROR] cluster [c-s4qd7] provisioning: Failed to set up SSH tunneling for host [192.168.2.191]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-s4qd7:m-9e695b3b9045]
2021/06/07 10:54:49 [ERROR] cluster [c-s4qd7] provisioning: Failed to set up SSH tunneling for host [192.168.2.193]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-s4qd7:m-9a6f38d66bce]
2021/06/07 10:54:49 [ERROR] cluster [c-s4qd7] provisioning: Failed to set up SSH tunneling for host [192.168.2.192]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-s4qd7:m-d828bf45234e]
2021/06/07 10:54:49 [ERROR] cluster [c-s4qd7] provisioning: Removing host [192.168.2.191] from node lists
2021/06/07 10:54:49 [ERROR] Failed to connect to peer wss://10.42.5.5/v3/connect [local ID=10.42.4.4]: websocket: bad handshake
2021/06/07 10:54:49 [ERROR] cluster [c-s4qd7] provisioning: Removing host [192.168.2.193] from node lists
2021/06/07 10:54:49 [ERROR] cluster [c-s4qd7] provisioning: Removing host [192.168.2.192] from node lists
2021/06/07 10:54:50 [ERROR] cluster [c-s4qd7] provisioning: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [192.168.2.191]
2021/06/07 10:54:50 [ERROR] error syncing 'c-s4qd7': handler cluster-provisioner-controller: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [192.168.2.191], requeuing
2021/06/07 10:54:53 [ERROR] Failed to connect to peer wss://10.42.3.6/v3/connect [local ID=10.42.4.4]: websocket: bad handshake
2021/06/07 10:54:54 [ERROR] Failed to connect to peer wss://10.42.5.5/v3/connect [local ID=10.42.4.4]: websocket: bad handshake
```

**Comment by springfred** [comment]
**Cluster Options:**
![image](https://user-images.githubusercontent.com/23000050/121009911-4aa9e680-c7c7-11eb-9431-9c797f644e3c.png)

**Docker version on nodes**
![image](https://user-images.githubusercontent.com/23000050/121009927-51385e00-c7c7-11eb-942f-580b4182c2e1.png)

**Comment by springfred** [comment]
OS
```
cat /etc/centos-release

CentOS Linux release 7.9.2009 (Core)`
```

**Comment by springfred** [comment]
Hi @superseb

**Comment by superseb** [comment]
Is this all logging from rancher pods/containers? Can you enable trace logging and capture it from all pods (https://rancher.com/docs/rancher/v2.x/en/troubleshooting/logging/)? This should be a loop where it tries to provision the cluster every time. Does the `failed to connect to peer` continuously show? Did you check if your k3s cluster is healthy and networking is working? Is there any kind of network restriction in this setup ((transparent) proxy/firewall/NAT/etc)?

**Comment by superseb** [comment]
@quick691fr It can have many reasons, new install? Happening from the beginning or suddenly started? Can it starting be related to anything you can see?

Troubleshooting is kinda the same though, put Rancher in trace and see if there is any logging related/around the error. If its happening from scratch, please provide where you are running it (cloud/onprem/OS/kernel etc) so I can try to reproduce it in that environment.

**Comment by quick691fr** [comment]
@superseb We have done a new install of RKE2 in HA mode with 3 nodes behind a Network ELB with a DNS, then deployed Rancher via Helm chart on it, everything seems working fine UI speaking instead of having same kinda message than @springfred looping in rancher instances :

```
2021/08/19 08:30:26 [ERROR] Failed to connect to peer wss://10.42.1.14/v3/connect [local ID=10.42.0.15]: websocket: bad handshake
2021/08/19 08:30:27 [ERROR] Failed to connect to peer wss://10.42.0.17/v3/connect [local ID=10.42.0.15]: websocket: bad handshake
```

When creating new Amazon EC2 cluster using a CentOS 8.2 kernel 5.13.0 AMI we have the same problem as @springfred aka "Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s)".

And UI showing "Waiting to register with kubernetes".

I guess the rancher handshake error should be fixed before being able to troubleshoot the cluster creation ?

RKE2 nodes were created with a /etc/NetworkManager/conf.d/rke2-canal.conf file containing : 
```
[keyfile]
unmanaged-devices=interface-name:cali*;interface-name:flannel*
```

Rancher was deployed with :
- /etc/rancher/rke2/audit_log_policy.yaml
```
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata
```
- /etc/rancher/rke2/config.yaml
```
server: https://rancher.xxxxxxxxxxxx.com:9345 ## only on secondary nodes
token: *******************************
tls-san:
  - rancher.xxxxxxxxxxxx.com
  - rancher-1.xxxxxxxxxxxx.com
  - rancher-2.xxxxxxxxxxxx.com
  - rancher-3.xxxxxxxxxxxx.com
node-ip: 10.81.51.182
audit-policy-file: /etc/rancher/rke2/audit_log_policy.yml
```
- /var/lib/rancher/rke2/server/manifests/nginx_ingress_daemonset.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: DaemonSet
      daemonset:
        useHostPort: true
```
- /tmp/rancher_values.yaml
```
hostname: rancher.xxxxxxxxxxxx.com
ingress:
  tls:
    source: secret
privateCA: true
auditLog:
  destination: hostPath
  hostPath: /var/log/rancher/audit
  level: 2
  maxAge: 7
  maxBackup: 7
  maxSize: 100
```
- CA deployed in secrets :
```
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: tls-ca
        namespace: cattle-system
      data:
        cacerts.pem: |
          {{ rancher_cacert }}
    kubeconfig: /etc/rancher/rke2/rke2.yaml
```
- Cert / Key deployed in secrets :
```
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/tls
      metadata:
        name: tls-rancher-ingress
        namespace: cattle-system
      data:
        tls.crt: |
          {{ rancher_certificate }}
        tls.key: |
          {{ rancher_certificate_key }}
    kubeconfig: /etc/rancher/rke2/rke2.yaml
```

I activated logging as you stated in : https://rancher.com/docs/rancher/v2.x/en/troubleshooting/logging/

**Comment by quick691fr** [comment]
@superseb any clue ?

**Comment by JaseKing** [comment]
I had the same issue; for me the fix was to re-add the NAT Gateway to the route table of the private AWS subnet my Rancher hosts sit in, reinstating their access to the internet, as we'd inadvertently removed it.

**Comment by quick691fr** [comment]
> I had the same issue; for me the fix was to re-add the NAT Gateway to the route table of the private AWS subnet my Rancher hosts sit in, reinstating their access to the internet, as we'd inadvertently removed it.

Our route tables and NAT gateway are correct and internet is accessible from rancher and cluster nodes

**Comment by quick691fr** [comment]
ping
