### ISSUE TITLE
Disabling Grafana's anonymous user breaks Cluster Dashboard page

### ISSUE THREAD

**Issue by CooperBills** [rancher/rancher#33065]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Install rancher monitoring with `grafana[grafana.ini][auth.anonymous].enabled` set to `false`.
2. Open the Rancher Cluster Dashboard page in Cluster Explorer.

**Result:**

The user is logged out and redirected to the login page every time the Cluster Dashboard page is opened (which is the default landing page for the Cluster Explorer, so it's very annoying/hard to work around).

**Other details that may be helpful:**

Inspecting network logs in chrome, it looks like something on the dashboard page is trying to load some grafana data through it's proxy. For example: `https://<RANCHER_DOMAIN>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/api/dashboards/uid/rancher-cluster-nodes-1`.

When the default view for Grafana requires authentication, Grafana returns a 401 Unauthorized. My guess is that Rancher's code sees this 401 response and assumes its own session has expired, so it kicks the user back to the login page.

All the other pages seem to work, for instance navigating directly to pods works fine: https://<RANCHER_DOMAIN>/dashboard/c/local/explorer/pod 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5.8`
- Installation option (single install/HA): `HA / rke`/ rancher-monitoring v14.5.100

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom/bare-metal
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal / Various x86_64 mini-pc's (2-6 cores/32-64GB each)
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
```

**Comment by mrcdb** [comment]
Hi @CoopeyB , did you manage to solve this issue or find a viable workaround?

I see the same problem on a cluster where anonymous auth was not disabled by default, running rancher v2.5.8.

Thanks,
Marco

**Comment by CoopeyB** [comment]
HI @mrcdb, nope, I haven't found any workarounds other than re-enabling the anonymous user, which is acceptable in my environment (but I can see this being an unacceptable solution in others).

**Comment by cstisa** [comment]
Hi all,

We have the same issue , could be great to have a workaround for this 👍 

Best Regards,
