### ISSUE TITLE
unable to use ec2/vsphere provisioner for rke2 clusters (machines not populating in ec2/vsphere) using any certs

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#33078]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* deploy rancher on master-head (can be valid or self signed certs)
* deploy an rke2 cluster using the aws ec2 provisioner

**Result:**
node(s) never register. Checking on ec2, it appears that no nodes are created

on non-letsencrypt certs, no error is shown in rancher. when using letsencrypt certs, the following error shows momentarily, then dismisses. No node is ever created on ec2
```
: failed calling webhook "default.machinedeployment.cluster.x-k8s.io": Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1alpha4-machinedeployment?timeout=10s": dial tcp <ip>:443: connect: connection refused
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):master-head (9afe417)
- Installation option (single install/HA):single or HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):AWS EC2 
- Machine type (cloud/VM/metal) and specifications (CPU/memory):any
- Kubernetes version (use `kubectl version`):v1.21.1-rc2+rke2r1

**Comment by thehejik** [comment]
This is strip from `kubectl describe pod` output from the pod running `rancher/machine:v0.15.0-rancher60` image for provisioning a single-node RKE2 EC2 cluster on `rancher/rancher:master-head e546ffe` (running on RKE1). The instance doesn't appear in EC2:

```yaml
Containers:
  machine:
    Container ID:  docker://c7d97155f67c7fe4c4ca8465cf0e450124b4c103b13bdb33c8422df735b9a438
    Image:         rancher/machine:v0.15.0-rancher60
    Image ID:      docker-pullable://rancher/machine@sha256:8089610c936ef5875188119cea105e47028ca1bd06b861d37fd61ad667a3d184
    Port:          <none>
    Host Port:     <none>
    Args:
      --driver-download-url=
      --driver-hash=
      --secret-namespace=fleet-default
      --secret-name=thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd-machine-state
      create
      --driver=amazonec2
      --custom-install-script=/run/secrets/machine/value
      --amazonec2-ami=ami-0dbcb516c6c091feb
      --amazonec2-block-duration-minutes=0
      --amazonec2-instance-type=t3a.medium
      --amazonec2-region=us-east-2
      --amazonec2-retries=5
      --amazonec2-root-size=20
      --amazonec2-security-group-readonly
      --amazonec2-security-group=all-open
      --amazonec2-spot-price=0.50
      --amazonec2-ssh-user=ubuntu
      --amazonec2-volume-type=gp2
      --amazonec2-vpc-id=vpc-REDACTED
      --amazonec2-zone=a
      thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd
    State:      Terminated
      Reason:   Error
      Message:  Running pre-create checks...
Creating machine...
(thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd) Launching instance...
(thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd) Creating New SSH Key
(thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd) creating key pair: thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd-ftXyI
(thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd) configuring security groups in vpc-bfccf4d7
(thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd) found existing security group (all-open) in vpc-bfccf4d7
(thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd) Skipping permission configuration on security groups
(thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd) launching instance in subnet subnet-ee8cac86
(thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd) Missing instance ID, this is likely due to a failure during machine creation
(thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd) deleting key pair: thehejik-rke2-ec2-thehejik-rke2-allroles-bf6nd-ftXyI
Error creating machine: Error in driver during machine creation: Error launching instance: InvalidParameterValue: User data is limited to 16384 bytes
  status code: 400, request id: 84c024a6-2490-4b0e-b5ba-bee345876929
The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
```

**Comment by slickwarren** [comment]
Ran into similar issues using vsphere with RKE2, rancher seems to try and use the provisioner, but no machine(s) are created within vsphere. 
master-head (b6bcfad)

**Comment by kinarashah** [comment]
Available to test once https://drone-publish.rancher.io/rancher/rancher/6028 passes.

**Comment by slickwarren** [comment]
on master-head (01665d0):
* provision downstream cluster using ec2 provisioner, single node, rancher installed via docker (self signed certs) -- pass
* provision downstream cluster using ec2 provisioner, single node, rancher is HA installed (byo certs) -- pass
* opened a [new vsphere ticket](https://github.com/rancher/rancher/issues/33783), as it seems to be a separate issue

**Comment by slickwarren** [comment]
calling out that, multi-node use case is tracked here: https://github.com/rancher/rancher/issues/32362
