### ISSUE TITLE
Installing Rancher 2.5.8 hangs when using --set privateCA=true 

### ISSUE THREAD

**Issue by paulofrazao** [rancher/rancher#33089]
**Trying to install latest Rancher stable version (2.5.8) so I can use my own private certs using the "--set privateCA=true" option and server hangs:**

**Steps to reproduce (least amount of steps as possible):**
 
helm install rancher rancher-latest/rancher --namespace cattle-system \
   --create-namespace \
   --namespace cattle-system \
   --set hostname=rancher-server.domains.com \
   --set ingress.tls.source=secret \
   --set privateCA=true

**Result:**
error: deployment "rancher" exceeded its progress deadline

**Other details that may be helpful:**
I have tried several methods of installation such as using Let's Encrypt or the basic Rancher install using your own signed-certs and I have no issue. Once i set "--set privateCA=true" install hangs and eventually times out.

**Environment information**
- Rancher version 2.5.8
- single node K8s install for now, but want to go to 3 nodes

**Cluster information**
- Cluster type -  RKE K8s installation using defaults
- Machine type (Ubuntu 20.04 VM , on-prem with VShpere 6.7 (2 core 8GB RAM)
- Kubernetes version (use `v1.20.6`):

```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Comment by superseb** [comment]
You need to create the CA certificate as described on https://rancher.com/docs/rancher/v2.5/en/installation/resources/tls-secrets/, did you create it?

**Comment by paulofrazao** [comment]
we are importing our own certs created on our Active Directory Certificate Authority.
