### ISSUE TITLE
Dark Theme UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3308]
version - master 01/15 (updated UI)

List of Issues:
- [x] Overlays haven't been changed to dark theme
![image](https://cloud.githubusercontent.com/assets/11514927/12365790/4a1d947c-bb94-11e5-9d92-a782cccd48df.png)

- [x] Learn More links on Welcome page are hard to see
![image](https://cloud.githubusercontent.com/assets/11514927/12365717/ca8d670a-bb93-11e5-8286-7331b622f555.png)

- [x] Can't see text in Logos for Add Host
![image](https://cloud.githubusercontent.com/assets/11514927/12365746/018b97b8-bb94-11e5-9ba1-4a848346de9d.png)

- [x] Checkmark has white circle around it in Add Host
![image](https://cloud.githubusercontent.com/assets/11514927/12365827/77ff09d4-bb94-11e5-803d-3c81af08c2e2.png)

- [x] Dark Grey help text in Add host sequences are hard to see (this will be everywhere in the app, go to the Sysdig Cloud catalog details page for a place where it's really hard to read)
![image](https://cloud.githubusercontent.com/assets/11514927/12365855/b8b9804e-bb94-11e5-8a31-f6dbb295da45.png)

- [x] Custom Host selection in Add Host has a white edit field that should maybe be grey like rest of app
![image](https://cloud.githubusercontent.com/assets/11514927/12365936/2f20843a-bb95-11e5-8f7a-6ad7fde4053e.png)

- [x] Because the example text and real text for edit fields look the same, it makes you think these fields have content when they do not.  I keep trying to highlight and delete the example text and it's not selectable.  This is everywhere in the application.
![image](https://cloud.githubusercontent.com/assets/11514927/12366025/d3b85040-bb95-11e5-8d57-c44204cf30a3.png)

- [x] Primary Service & Sidekick tabs are white/light grey.  Selected tab is same color as edit fields in regular theme.  Maybe change to that?
![image](https://cloud.githubusercontent.com/assets/11514927/12366235/1fba1784-bb97-11e5-9dfb-b37c9a52adad.png)

- [ ] Advance Options selected tab does not stay orange.  It should either stay orange or always be grey.
![image](https://cloud.githubusercontent.com/assets/11514927/12366267/53ebbb52-bb97-11e5-83b8-c733417269d9.png)
![image](https://cloud.githubusercontent.com/assets/11514927/12366251/3f4e5880-bb97-11e5-8557-ffb5d0a8ae55.png)

- [x] Advanced Options, Security/Host tab.  Membory Limit and Swap Limit has white edit fields.
![image](https://cloud.githubusercontent.com/assets/11514927/12366359/e774604a-bb97-11e5-9fb6-7d4acf447bce.png)

- [x] Advanced Options, Health Check both TCP & HTTP radio options have white fields that should probably be grey
![image](https://cloud.githubusercontent.com/assets/11514927/12366496/c573c55c-bb98-11e5-8411-955e691a0f6a.png)
 
- [x] Advanced Options, Health Check both TCP & HTTP radio options you can't see the scrolls unless you hover them or select the field
![image](https://cloud.githubusercontent.com/assets/11514927/12366529/0233550c-bb99-11e5-9a0f-f993cc5d8582.png)
 
- [x] Advanced Options, Health Check both TCP & HTTP radio options for When Unhealthy, the Re-create, only when at least field should be grey with white text (with scroll visible) because it's editable.
![image](https://cloud.githubusercontent.com/assets/11514927/12366777/8e4e3ab0-bb9a-11e5-81bf-aeced1a89b59.png)

- [x] Advanced Options, Health Check/HTTP Responds 2xx/3xx white outline for HTTP Request is missing on right side
![image](https://cloud.githubusercontent.com/assets/11514927/12366459/8a923ff4-bb98-11e5-8c6a-c748320a9a40.png)

- [ ] Advanced Options, Networking (Network field) & Scheduling (Condition & Field fields) use a standard system drop-down that doesn't match the dark theme.  This is in quite a few places in the application, not sure if you can do something about this or if it would have to be changed to custom field (or just leave as is).  If you need a list of where it is, let me know.
![image](https://cloud.githubusercontent.com/assets/11514927/12367015/410b45de-bb9c-11e5-9919-8e5a82be4188.png)

- [x] Can't see graph separator lines on any screen
![image](https://cloud.githubusercontent.com/assets/11514927/12367063/996248fe-bb9c-11e5-9e04-5c10337cdacc.png)

- [ ] Stack drop-down is white and a bit messy
![image](https://cloud.githubusercontent.com/assets/11514927/12367133/1e17d398-bb9d-11e5-80da-96654e93846d.png)

- [x] In Add LB, Custom haproxy.cfg, global & defaults text is in white box
![image](https://cloud.githubusercontent.com/assets/11514927/12367351/7b22a79c-bb9e-11e5-87b1-1f9d4ae665f9.png)

- [ ] Catalog drop-down is white a bit messy (same issue as Stack drop-down).  I entered a separate bug against the messy part because it's like that in the light theme as well.
![image](https://cloud.githubusercontent.com/assets/11514927/12367751/e62adbba-bba1-11e5-842a-47a4f5376d51.png)

- [x] Audit log, Resource ID is in white box until I put something in Resource Type
![image](https://cloud.githubusercontent.com/assets/11514927/12368208/6b1a1d14-bba6-11e5-9aa1-505fdc1226f3.png)

- [x] Processes, Resource id field is white until I put something in Resource Type
![image](https://cloud.githubusercontent.com/assets/11514927/12368301/5cd6cbb6-bba7-11e5-8b50-55bff4af1fd7.png)

- [x] Access Control, Active Directory & OpenLDAP, white boxes in help text that should probably be grey or something
![image](https://cloud.githubusercontent.com/assets/11514927/12368341/cf0640ea-bba7-11e5-8d98-ee836ba94623.png)

- [x] Access Control, Active Directory & OpenLDAP, TLS box for Port is really light grey and kinda stands out compared to rest of page, not sure if intentional or not
![image](https://cloud.githubusercontent.com/assets/11514927/12368357/f30a8794-bba7-11e5-8f87-5d7814588d93.png)

- [x] Across the app - because the blue drop-down menu are transparent instead of opaque, it's sometime hard to see the images on the right because of the background images.
![image](https://cloud.githubusercontent.com/assets/11514927/12368521/61fca712-bba9-11e5-8e8d-fc759b7afffc.png)
![image](https://cloud.githubusercontent.com/assets/11514927/12368539/84fdaedc-bba9-11e5-84bc-2e94f09b7763.png)

- [x] Settings, white field mixed with text
![image](https://cloud.githubusercontent.com/assets/11514927/12368588/0cecd098-bbaa-11e5-8496-1fa577452ce7.png)

- [ ] Settings, I haven't seen this before and not sure if you wanted it blue.  I haven't seen it in the regular app.
![image](https://cloud.githubusercontent.com/assets/11514927/12368659/bbcd452a-bbaa-11e5-9a74-932d2a9383a3.png)

- [x] Top part of registry screen has not been changed to dark theme
![image](https://cloud.githubusercontent.com/assets/11514927/12368687/efdc2822-bbaa-11e5-9706-59d16432ed22.png)

- [x] Log in Screen should always have light theme, since we won't know which theme to implement until they are actually in the application.
![image](https://cloud.githubusercontent.com/assets/11514927/12368739/5d2e1200-bbab-11e5-8c50-c49c8d69bd05.png)

**Comment by vincent99** [comment]
Can we call this one good and start another round?

**Comment by lvuch** [comment]
@vincent99 We can close this and start another round. @tfiduccia the select2s (the nicer looking dropdowns with search) I'll clean up the other ones that are browser default styled will be left alone for now unless we want to convert them to power selects

**Comment by tfiduccia** [comment]
Version - 0.56.0-rc2
Verified fixed
