### ISSUE TITLE
Resolv impossible in container

### ISSUE THREAD

**Issue by Xeriphon** [rancher/rancher#3309]
Hi, 

I have nginx containers, behind a loadbalancer.
They are all setup as managed in the network parameter with DNS 8.8.8.8 and 8.8.4.4
But when I do a cat /etc/resolv.conf in the container I have the following  : 
// # nameserver 8.8.8.8
// # nameserver 8.8.8.4
search ovh.net rancher.internal
nameserver 169.254.169.250

And when trying to ping:
docker exec -ti 22a127f76538 ping google.fr
I have : ping: unknown host google.fr

Is there a bug in the DNS management?

**Comment by deniseschannon** [comment]
I'm not completely sure I understand how your services are set up. Can you share your docker-compose.yml file from the stack? From the stack dropdown, click on "View Config" and share the docker-compose.yml

Are you trying to ping inside the loadbalancer or inside the nginx containers?

Finally, what version of Rancher are you running?

**Comment by deniseschannon** [comment]
@Xeriphon If you are still having issues, please re-open and can you answer my questions?
