### ISSUE TITLE
Navlinks: namespace field when provided in the yaml file, navlink creation fails with 'the server could not find the requested resource' error

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33094]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a node driver rke2 cluster from the explorer 
2. Create a namespace in the default project from Cluster explorer --> Projects and namespaces
3. Once the cluster is active, create a navlink from More resources --> Rancher --> Navlinks with the following fields: name, namespace and click on save
4. Creation of the navlink yaml fails with the error:
` { "type": "error", "links": {}, "code": "NotFound", "message": "the server could not find the requested resource", "status": 404 }
`

**Result:**
The navlink creation should have succeeded and should be posted to the URL for that namespace

**Other details that may be helpful:**
<img width="200" alt="Screen Shot 2021-06-08 at 1 42 21 PM" src="https://user-images.githubusercontent.com/38144301/121254658-606aea80-c85f-11eb-8f31-60e0e76d7dbb.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  master-head 3d465ee
- Installation option (single install/HA): Single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 
- Kubernetes version (use `kubectl version`): v1.20.6

https://github.com/rancher/dashboard/issues/2835

**Comment by deniseschannon** [comment]
@anupama2501 These resources aren't namespaced, so this is an invalid use case.

**Comment by anupama2501** [comment]
Verified on master-head 54d4afc the namespace field is removed from the yaml file of the navlinks from cluster explorer --> cluster --> Rancher --> Resources --> Navlinks

<img width="150" alt="Screen Shot 2021-06-16 at 3 05 42 PM" src="https://user-images.githubusercontent.com/38144301/122300618-63e02080-ceb4-11eb-8a86-5786499f38cf.png">
