### ISSUE TITLE
rancher-compose build not support bitbucket

### ISSUE THREAD

**Issue by elct9620** [rancher/rancher#3310]
Hi,

I try using Bitbucket repository to build image, but it seems not working using "SSH" mode.
The HTTPS mode is working, is the git build feature parser only check github?

**Comment by deniseschannon** [comment]
Correct, we don't support bitbucket for build in rancher-compose. 

I've changed this to an enhancement request.

**Comment by mdahiemstra** [comment]
👍

**Comment by andrewmclagan** [comment]
+ 1

**Comment by will-chan** [comment]
Closing as BitBucket is tracked in #113
