### ISSUE TITLE
Prometheus Out Of Memory when scaling up pods

### ISSUE THREAD

**Issue by envybee** [rancher/rancher#33103]
**What kind of request is this (question/bug/enhancement/feature request)**:

Bug

We have upgraded Rancher to 2.5.8, which included an update of Istio to 1.8. With this Istio upgrade, the number of targets by the Prometheus ServiceMonitors has increased by a lot (since there is 1 target per pod now, and it has multiple metrics/timeseries within it). With this change, the memory consumption of Rancher Prometheus has increased, and it is getting OOMKilled even after increasing the memory resource requirements (increased it to 60GB for a 100node cluster, and it's still running out of memory).

Is there a way to fix this?

For scalability, I have used "shards" field in the Prometheus CRD (in PrometheusSpec), however, it is only adding 1 shard per reconciliation (i.e., if shards is set to "8", it is only bringing one extra shard. Then setting shards to "6" for example, it is bringing up only the 2nd extra shard etc.).

Is there a way to fix this issue as well?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AWS EC2
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T19:10:58Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
19.3.13
```

**Comment by malpania** [comment]
Can we have any update on this? this issue opened long time?
