### ISSUE TITLE
Restricted admin can't install RKE2 templates

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#33110]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy a rancher setup
* create a restricted admin user
* login as restricted admin
* attempt to install rke2 template (add git repo to local cluster)

**Result:**
* restricted admin can't access local cluster, therefore can't add new/create rke2 templates

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):master-head(6f4f01502cd1762c161004459703d6615a0bf602) 
- Installation option (single install/HA): single/HA

**Comment by snasovich** [comment]
Waiting for RC that references Dashboard UI `v2.6.1-rc3` or later as it includes necessary UI changes.

**Comment by snasovich** [comment]
RC is not needed per https://github.com/rancher/dashboard/issues/3995#issuecomment-922728299, ready to test.

**Comment by slickwarren** [comment]
tested the following on v2.6-head (45dfeb4):
* standard users cannot edit/create repositories -- pass
  * can view repos -- pass
* admin users can edit/create/delete/view repositories -- pass
* restricted admin can edit/create/delete/view repos -- pass

closing in favor of the backend ticket here https://github.com/rancher/rancher/issues/34844
