### ISSUE TITLE
random namespaces created by cattle

### ISSUE THREAD

**Issue by mabusaa** [rancher/rancher#33119]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
we notice random namespaces created , and we dont why this is happening.
any idea how to stop this ?
![image](https://user-images.githubusercontent.com/13915373/121499595-355ed300-c9e6-11eb-8ecf-7be552404853.png)
 

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.5
- Installation option (single install/HA): installed in k8s using helm

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud AKS 16 GB 8 cores nodes
- Kubernetes version (use `kubectl version`): 1.18

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by CraigMChen** [comment]
When you create a project, rancher will create a namespace with the same ID on the control plane. Some control plane project resources （such as projectAlertRule, projectAlertGroup) will be created in the corresponding namespace.

**Comment by vincent99** [comment]
Among other reasons, this is why we recommend the cluster used for Rancher be used only for it.  Each one correspond to a project in some cluster, and stores resources related to  that project.
