### ISSUE TITLE
Rancher dashboard API is too slow

### ISSUE THREAD

**Issue by CraigMChen** [rancher/rancher#33116]
**What kind of request is this (question/bug/enhancement/feature request):** 

Enhancement

**Steps to reproduce (least amount of steps as possible):**

- Run rancher with docker.
- Enter the dashboard ui.
- Record the network activity.
- Refresh page.

**Result:**

Noticed that the http response returned slowly in a dashboard. 

![rancher dashboard http request waterfall](https://user-images.githubusercontent.com/49681321/121618421-4fa5b900-ca99-11eb-9d0b-74e23dc42477.png)

The front end may have some cache and sync it with websocket. But what if I use steve in a cluster with a large number of pods and frequently request resources through the API?

I read the source code of steve. It implements `proxy_store` and processes api requests by sending requests to k8s api server. If the amount of data requested is large and frequent, will this waste too much resources? Is there any way to optimzie it? Such as using informer or LRU cache?

**Other details that may be helpful:**

There are 136 pods in my cluster. It takes about 2s to load the pod list page.

**Environment information**
- Rancher version: v2.5.8
- Installation option: single install

**Cluster information**
- Cluster type: Hosted
- Machine type: VM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by johnlanni** [comment]
Does rancher have a performance improvement plan? It is not user friendly now.
