### ISSUE TITLE
Update Rancher base image to SLE BCI 

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#33127]
**What kind of request is this (question/bug/enhancement/feature request):** Enhancement

**Other details that may be helpful:**

We are moving to using the same base image across all of our images. SUSE has developed an image called SLE BCI (Base Container Image) that we will need to roll out to all images within Rancher. This issue request this image to be used for Rancher.

**Comment by snasovich** [comment]
QA, to test this before we merge it, could you please run validation tests on the following images built from linked PR:
[snasovichsuse/rancher:67c52b45b](https://hub.docker.com/layers/snasovichsuse/rancher/67c52b45b/images/sha256-753c9194e843e410300aa0254795f8ee59fcbdb77afa946347d48a48a32341d4?context=explore)
[snasovichsuse/rancher-agent:67c52b45b](https://hub.docker.com/layers/153530633/snasovichsuse/rancher-agent/67c52b45b/images/sha256-c7fe9e0a43b5ccdbdc2f84fe6e13aab9f465ecb583f31516316ddb4a5745d6c1?context=explore)

**Comment by snasovich** [comment]
@izaac , just tried smoke test using Docker install and it's failing to come up. Please hold on.

**Comment by snasovich** [comment]
Related PR: https://github.com/rancher/rancher/pull/33007

**Comment by snasovich** [comment]
Have a fix for immediate "startup failed" issue, so Docker container build on this image at least starts OK. Here are the updated images:
[snasovichsuse/rancher:dce011aed](https://hub.docker.com/layers/153614202/snasovichsuse/rancher/dce011aed/images/sha256-55477cba9ff9aca01257175ee4b58feea3fa15473978d65057af215f7750a478?context=explore)
[snasovichsuse/rancher-agent:dce011aed](https://hub.docker.com/layers/153614686/snasovichsuse/rancher-agent/dce011aed/images/sha256-b52b00955c6e6beb319af46cf890356ba698f562f9c8845d3cc67065ff620bd1?context=explore)

@izaac , could you please try running tests on these images?

@deniseschannon , JFYI.

**Comment by izaac** [comment]
@snasovich I am getting this error while deploying an RKE1 DO cluster from the Rancher using this image

`2021/06/10 23:10:17 [INFO] [node-controller-rancher-machine] Error getting ssh command 'exit 0' : ssh command error: command: exit 0 err: exit status 127 output: /usr/bin/ssh: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`

**Comment by snasovich** [comment]
@izaac , thank you. Not surprised - there was a really high chance the fix I've applied only got us through the initial error. I'll let you know once we have something more solid.

**Comment by izaac** [comment]
@snasovich sounds good to me!

**Comment by dirkmueller** [comment]
> `2021/06/10 23:10:17 [INFO] [node-controller-rancher-machine] Error getting ssh command 'exit 0' : ssh command error: command: exit 0 err: exit status 127 output: /usr/bin/ssh: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`

Thank you for the report, this has been resolved

**Comment by dirkmueller** [comment]
@snasovich how can I help with providing more current images for testing? is the validation suite run documented somewhere?

**Comment by snasovich** [comment]
@dirkmueller , I build images by running `make ci` (with commented out validate, test, and chart/ci steps) then retagging them and pushing into my Docker Hub repo.
As far as running integration testing, this is described here: https://github.com/rancher/rancher/wiki/Setting-Up-Rancher-2.0-Development-Environment#setting-up-and-running-the-tests and are part of test stage of `make ci` (unless commented out). However, it looks like these tests are performed on locally built rancher codebase rather than docker images produced.

Validation tests that are based on docker images are maintained by QA and unfortunately I don't know much about them.

**Comment by dirkmueller** [comment]
Noticed that as well, the ci test is not actually testing the build result. :/ thanks, was hoping to learn more about the validation testsuite.

**Comment by dirkmueller** [comment]
Not directly SLE BCI related, but https://github.com/rancher/machine/pull/135 would help with reducing the size of the images somewhat.

**Comment by snasovich** [comment]
@izaac , we went through couple more rounds of tweaks and got to the point where Rancher not only deploys but can also successfully provision a single node Digital Ocean cluster. This said I think we're ready to run your validation suite. Please run it whenever you have time.
Images are as follow:
[snasovichsuse/rancher:3e67135bc](https://hub.docker.com/layers/153885496/snasovichsuse/rancher/3e67135bc/images/sha256-f604b14730178212c3ac85dc77cd00e3d6e23f7ce3b30bd311654f81fe696c58?context=explore)
[snasovichsuse/rancher-agent:3e67135bc](https://hub.docker.com/layers/153885450/snasovichsuse/rancher-agent/3e67135bc/images/sha256-1cadc7c029e95350db4acefcc7ab32bc4e45ca29ae08265be92daaf2770a6163?context=explore)

**Comment by izaac** [comment]
@snasovich our validation passed on a downstream cluster as it had a positive result using the images you've provided.  cc @sowmyav27

**Comment by snasovich** [comment]
Thank you, @izaac.

**Comment by snasovich** [comment]
@sowmyav27 , we're ready to merge related changes to master meaning that any images produced after this will be based on a new base image (SLE BCI). Since it's hard to be sure that this won't cause any regressions, it would be a good idea to have pre-base image changes build handy to verify if any found issue may be due to this change.
Any time we push to master, CI produces image with tag that corresponds to that exact version and it's stored on Docker Hub. For example, we have these images that currently match master-head:
[rancher/rancher:master-54d4afc27c36814fe067a47a232463e0e5681da9-head](https://hub.docker.com/layers/rancher/rancher/master-54d4afc27c36814fe067a47a232463e0e5681da9-head/images/sha256-f0e86057369fb79c89e7a0b5bcd455ae45416e85e37b29c1b4e073e510ff800a?context=explore)
[rancher/rancher-agent:master-54d4afc27c36814fe067a47a232463e0e5681da9-head](https://hub.docker.com/layers/rancher/rancher-agent/master-54d4afc27c36814fe067a47a232463e0e5681da9-head/images/sha256-d42c531c9ab2e7fba581d76a63613c4901bb363ea618adb82438c6ba8c12d063?context=explore)

As far as testing this change goes, I gather testing indirectly makes sense - just continue your normal testing and if there are any suspicious regressions that may be related to this, check them on images linked below and if not reproducible, report here. You would probably want to notify everyone on the QA team of this change so they are aware.

@sowmyav27 , please let me know if this sounds acceptable to you and I will merge this change in.

@deniseschannon , FYI.

**Comment by sowmyav27** [comment]
@snasovich Sure thing.

**Comment by snasovich** [comment]
This is now available on `master-head`.

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/07/2021)` _cf5a75f_
Rancher HA RKE1 kubernetes version: `1.20.7`
Rancher HA RKE1. Rancher pods using the SUSE image:
```
[centos@ip-172-31-8-84 ~]$ docker exec -it k8s_rancher_rancher-5ddd6c9f97-9zrgb_cattle-system_f59d0234-7dee-4a54-879b-cc57d85052ee_0 cat /etc/os-release
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"
```
Downstream cluster RKE DigitalOcean Node driver with kubernetes `1.20.7` 
Executed the downstream cluster QA validation automated suite, with positive results. Report shown a couple of etcd backup failures but I validated those were working manually.

Any further issues related to the image change should be followed up as separate issues.
