### ISSUE TITLE
Generic Import Missing Import Command Post Save

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#33136]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create an AKS cluster via the Azure Console UI.
When the cluster is active, via the legacy (ember ui) create a generic import cluster, run the command on the Azure cluster you just created to import.
When the cluster is active in the legacy ui, edit the cluster, add a label, and save.

**Result:**
The edit form is removed from the page and all your left with is a save and cancel button.

**Expected:**
~In this case, because the cluster is active we should be redirecting to the legacy ui cluster dashboard page. If the cluster were in some kind of non-activish state (updating or error, etc) we should see the cluster registration command.~
According to [this issue](https://github.com/rancher/rancher/issues/32242) we should be showing the command always.

**Comment by aaronRancher** [comment]
Validated the fix on Rancher `master-head` `version 5715b8a` with the following steps:
Create an AKS cluster via the Azure Console UI.
When the cluster is active, via the legacy (ember ui) create a generic import cluster, run the command on the Azure cluster you just created to import.
When the cluster is active in the legacy ui, edit the cluster, add a label, and save.

Result:
User is redirected to registration command after saving edit.
![image](https://user-images.githubusercontent.com/57409052/121941018-9d255e80-cd03-11eb-9042-ba8471e8c56f.png)
Hitting `Done` redirects the user to cluster view.

Also tested by importing a standalone RKE cluster.
