### ISSUE TITLE
Convoy Gluster Container degraded after add Label to hosts

### ISSUE THREAD

**Issue by galindro** [rancher/rancher#3313]
Steps to reproduce the error:

1. Add a single host to an environment. Let's call it first host.
2. Add a glusterfs stack
3. Add a ConvoyGluster stack without label the host. At this point, you'll have all stacks running the first host.
4. Add two more hosts to environment (second and third)
5. Increase size of glusterfs stack to 5
6. Wait for increase of glusterfs stack. At this point, rancher server will put one more container of gluster stack on the second and third hosts.
7. Put the chosen label from ConvoyGluster stack (convoy.glusterfs=true) on the first and on the second host.
8. After the above step, you will notice that the two new convoy-gluster containers (convoy-gluster_convoy-gluster_1 and convoy-gluster_convoy-gluster_2) will be restarted every 5 seconds and the convoy-gluster service will be in Degraded state.

Here are the logs of the convoy-gluster_convoy-gluster_1 container:

```bash
1/17/2016 10:36:00 PMWaiting for metadata.time="2016-01-18T00:36:00Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/2544/ns/mnt -F -- /var/lib/docker/overlay/7a1414086dcc3910601ab85d42f1931d18aaa7fed73efa2f816f994bab46906e/merged/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-663284b5-83d5-4aa8-90bb-dbdc771dc923 -- /launch volume-agent-glusterfs-internal]"
1/17/2016 10:36:00 PMRegistering convoy socket at /var/run/conoy-convoy-gluster.sock
1/17/2016 10:36:00 PMtime="2016-01-18T00:36:00Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
1/17/2016 10:36:00 PMtime="2016-01-18T00:36:00Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-663284b5-83d5-4aa8-90bb-dbdc771dc923"
1/17/2016 10:36:00 PMtime="2016-01-18T00:36:00Z" level=info msg="Got: drivers [glusterfs]"
1/17/2016 10:36:00 PMtime="2016-01-18T00:36:00Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=datastore_gluster glusterfs.servers=glusterfs]"
1/17/2016 10:36:00 PMtime="2016-01-18T00:36:00Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/conoy-convoy-gluster.sock daemon --root=/var/lib/rancher/convoy/convoy-gluster-663284b5-83d5-4aa8-90bb-dbdc771dc923 --drivers=glusterfs --driver-opts=glusterfs.defaultvolumepool=datastore_gluster --driver-opts=glusterfs.servers=glusterfs]"
1/17/2016 10:36:00 PMtime="2016-01-18T00:36:00Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-663284b5-83d5-4aa8-90bb-dbdc771dc923" pkg=daemon
1/17/2016 10:36:00 PMtime="2016-01-18T00:36:00Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:datastore_gluster glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-663284b5-83d5-4aa8-90bb-dbdc771dc923"
1/17/2016 10:36:00 PMtime="2016-01-18T00:36:00Z" level=debug msg="Volume datastore_gluster is being mounted it to /var/lib/rancher/convoy/convoy-gluster-663284b5-83d5-4aa8-90bb-dbdc771dc923/glusterfs/mounts/datastore_gluster, with option [-t glusterfs]" pkg=util
1/17/2016 10:36:01 PMtime="2016-01-18T00:36:01Z" level=error msg="Get http:///host/var/run/conoy-convoy-gluster.sock/v1/volumes/list: dial unix /host/var/run/conoy-convoy-gluster.sock: no such file or directory"
1/17/2016 10:36:01 PMtime="2016-01-18T00:36:01Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/17/2016 10:36:01 PMtime="2016-01-18T00:36:01Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/datastore_gluster /var/lib/rancher/convoy/convoy-gluster-663284b5-83d5-4aa8-90bb-dbdc771dc923/glusterfs/mounts/datastore_gluster], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/17/2016 10:36:01 PM{
1/17/2016 10:36:01 PM	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/datastore_gluster /var/lib/rancher/convoy/convoy-gluster-663284b5-83d5-4aa8-90bb-dbdc771dc923/glusterfs/mounts/datastore_gluster], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/17/2016 10:36:01 PM}
1/17/2016 10:36:01 PMtime="2016-01-18T00:36:01Z" level=info msg="convoy exited with error: exit status 1"
1/17/2016 10:36:01 PMtime="2016-01-18T00:36:01Z" level=info msg=Exiting.
```

This is my Env:
* Rancher ServerOS 0.4.2 on each host (Amazon EC2) with ZFS as storage pool for user docker containers
* Convoy Gluster Server: v0.1

**Comment by deniseschannon** [comment]
You have a couple of things going on:

We don't support the scaling of GlusterFS. https://github.com/rancher/rancher/issues/2786

We have had people add the labels after convoy-gluster is deployed, which end up launching the services on those hosts. We are looking to remove this host label scheduling requirement as well. https://github.com/rancher/rancher/issues/3068

And the error you displayed looks like this issue: https://github.com/rancher/rancher/issues/2903

Have you launched convoy-gluster before?

**Comment by galindro** [comment]
@deniseschannon , I have build that environment at the time that I have open this ticket (3 days ago). 

This problem isn't related to #2786, but it is very similar to #2903.

I'll make more tests, wihout scale glusterfs. I think this action caused a little misunderstanding...

**Comment by galindro** [comment]
I could not reproduce the error, even using the steps that I have posted... So, I think this ticket could be closed.
