### ISSUE TITLE
Helm does not wait for Rancher install/upgrade when replicas=1

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#33133]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Steps to reproduce (least amount of steps as possible):**

- Deploy the Rancher chart with helm using `--set replicas=1` and `--wait`

**Result:**

The helm install completes immediately without waiting for the Rancher pod to become ready

**Other details that may be helpful:**

Due to logic in helm, a wait will not occur when `maxUnavailable` is non-zero and there is a single replica.
  * https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback

With the `maxSurge: 1` upgrades and re-deploys will still start a new Rancher pod before terminating the running pod.

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by jiaqiluo** [comment]
The enhancement is validated in rancher:v2.6.0-rc1 

## prerequisite:
- use RKE CLI (version v1.2.11) to create a single-node RKE cluster for installing Rancher.  
```
rke up --config ./rancher-cluster.yml
```
- install cert-manager into the cluster 
```
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.4.0 \
  --create-namespace \
  --set installCRDs=true
```

## Case 1: Fresh Install
Steps:
- run the following command to install rancher 
```
 helm install rancher2 rancher-latest/rancher \
  --namespace cattle-system \
  --version v2.6.0-rc1 \
  --set hostname=my-hostname.com --set replicas=1 --create-namespace --wait
```
Results:
- the Helm command does not return until the rancher pod is in the `Ready` state 
- Rancher is installed successfully 


## Case 2: Upgrade
Steps:
- run the following command to upgrade rancher
```
 helm upgrade rancher2 rancher-latest/rancher \
  --namespace cattle-system \
  --version v2.6.0-rc1 \
  --set hostname=my-hostname.com --set replicas=1 --create-namespace --wait --set rancherImageTag=master-head
```
Results:
- A new pod is created
- the Helm command does not return until the new pod is in the `Ready` state
- then the old pod is removed 
- Rancher is upgraded successfully

**Comment by jiaqiluo** [comment]
@sowmyav27 Please review and close the issue
