### ISSUE TITLE
Descriptions are not seen on apps

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#33149]
See: https://github.com/rancher/dashboard/issues/3038#issuecomment-853767511

**Comment by jiaqiluo** [comment]
The backend looks fine, it is the UI that looks up the value at the wrong field. 
see my comment for details: https://github.com/rancher/dashboard/issues/3038#issuecomment-868845524

**Comment by richard-cox** [comment]
I think there's still an issue, the field referenced is only the user one when the app's state is deployed - https://github.com/rancher/dashboard/issues/3038#issuecomment-871524064

**Comment by jiaqiluo** [comment]
see [my comment](https://github.com/rancher/dashboard/issues/3038#issuecomment-875135012) for why this is not a bug.
