### ISSUE TITLE
Apply scheduling policies to catalog services

### ISSUE THREAD

**Issue by galindro** [rancher/rancher#3314]
How could I apply scheduling policies to the Gluster FS Stack deployed from Catalog? 

Is it possible to do this?

**Comment by galindro** [comment]
I've made this PR: https://github.com/rancher/rancher-catalog/pull/85 to make possible to the user to choose where to put all of the deployed stack's containers....

**Comment by Verikon** [comment]
+1

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/2852
