### ISSUE TITLE
Remove Login Landing Page preference from Ember UI

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#33147]
![image](https://user-images.githubusercontent.com/1955897/121169390-db2a0a80-c84b-11eb-95c8-b81d7434bc74.png)

^^ Need to remove the  Login Landing Page preference

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 6757965`

From Ember UI, navigate to account dropdown > Preferences
Login Landing Page preference has been removed.
![Screen Shot 2021-06-29 at 4 41 45 PM](https://user-images.githubusercontent.com/57409052/123881135-f511b700-d8f8-11eb-8c29-4fccf46ffae4.png)
