### ISSUE TITLE
[UI][KEv2] Add monitoring feature to AKSv2

### ISSUE THREAD

**Issue by mjura** [rancher/rancher#33142]
Please add monitoring section to AKSv2 UI in Advanced Option section. On AKS operator site this was already implemented and set with two options: 
```

	LogAnalyticsWorkspaceGroup  *string           `json:"logAnalyticsWorkspaceGroup"`
	LogAnalyticsWorkspaceName   *string           `json:"logAnalyticsWorkspaceName"`
```

**Comment by westlywright** [comment]
Ive placed these under advanced settings as `Container Monitoring`. Additionally when you select this checkbox you'll see the `logAnalyticsWorkspaceGroup` & `logAnalyticsWorkspaceName` name inputs. These are just text inputs where as in Azure they load all the log analytics workspaces into a dropdown. We dont have this api but it would be nice to have this API to load these workspaces before the release so we can turn this into a dropdown as well.

**Comment by prabalsharma** [comment]
Bug: 
https://github.com/rancher/rancher/issues/33239
feature request:
https://github.com/rancher/rancher/issues/33240

**Comment by prabalsharma** [comment]
tested on master-3e44415, aks-operator:v1.0.1-rc14
API to load workspaces, was not part of requirements.  So accepting `text inputs` for logAnalyticsWorkspaceGroup & logAnalyticsWorkspaceName.
