### ISSUE TITLE
[2.5] Reduce size of v3.App objects

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#33157]
This is a backport issue for https://github.com/rancher/rancher/issues/32939.

**Comment by nickgerace** [comment]
Milestone reasoning: https://github.com/rancher/rancher/issues/33156#issuecomment-859930728

**Comment by nickgerace** [comment]
Milestone has changed to 2.5.9 (CC: @cbron).

**Comment by cbron** [comment]
Moving this one back to 2.5.10 since its not critical and not fixed yet.

**Comment by kravciak** [comment]
Verified on 2.5-head (0e58768)
 - Created a catalog at global level , cluster level and project level
 - Installed nginx app from cluster, project, global in 3 different namespaces

All apps have come up fine and active.
