### ISSUE TITLE
[2.5] GKEv2 Access scopes for NP: "access to all Cloud APIs" & "Set access for each API"- not getting enabled

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#33154]
Backport https://github.com/rancher/rancher/issues/32994

**Comment by sowmyav27** [comment]
**Verified on 2.5-head commit id: `07131035f`**

- Create GKE cluster
- NP Access scopes
- Select `Allow full access to all Cloud APIs`

```
oauthScopes: ["https://www.googleapis.com/auth/cloud-platform"]
0: "https://www.googleapis.com/auth/cloud-platform"
```

-  Set access for each API options - User Info is sent by the UI to the backend

```
oauthScopes: ["https://www.googleapis.com/auth/userinfo.email"]
0: "https://www.googleapis.com/auth/userinfo.email"
```
