### ISSUE TITLE
[2.5] GKE and EKS, some fields not working fine using rancher go cli

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#33153]
Backport https://github.com/rancher/rancher/issues/32553

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5-head` `version 0713103` with the following steps:
- Using Terraform Rancher2 provider version 1.16.0, deploy EKSv2 and GKEv2 clusters letting `Cluster.GKEConfig.Labels`/ `Cluster.EKSConfig.Labels` be empty.

Result:
EKSv2 clusters can be created from Rancher UI and created with Terraform Rancher2 provider. Clusters are available in Rancher and EKS console.
EKS operator version `v1.1.1-rc8`. `k8s version v1.20`
GKEv2 clusters can be created from Rancher UI and created with Terraform Rancher2 provider. Clusters are available in Rancher and GKE console.
GKE operator version `v1.1.1-rc10`. `k8s version v1.19.9-gke.1900`
