### ISSUE TITLE
How to update kubelet certificate for downstream cluster

### ISSUE THREAD

**Issue by konstantin-921** [rancher/rancher#33164]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
According to https://rancher.com/docs/rancher/v2.x/en/cluster-admin/certificate-rotation/:

1. In the Global view, navigate to the cluster that you want to rotate certificates.
2. Select the ⋮ > Rotate Certificates.
3. Select which certificates that you want to rotate => Rotate all Service certificates (keep the same CA)
4. Click Save.
5. Check expired date of kubelet certs. I used 2 way:

      a. Go to any cluster node and run command:
      ```
      curl -vvvk https://localhost:10250
      ```
      b. Go to any cluster node to dir /var/lib/kubelet/pki and run:
      ```
      openssl x509 -in kubelet.crt -noout -text | grep ' Not '
      ```

**Result:**
Updated all certificates except for kubelet. Expired date for kubelet cert haven't changed.

**Expected result**
Updated all certificates

**Other details that may be helpful:**
I used the same way to update the certs on my another TEST downstream cluster (3 All roles nodes). And in that case the kubelet certificates were successfully updated.

**Environment information**
Rancher version: 2.5.5
Installation option (single install/HA): HA (3 master + 3 worker)
Kubernetes Version: v1.19.3-rancher1-2

**Comment by superseb** [comment]
The kubelet serving certificate is different from the node certificate, see https://github.com/rancher/rke/issues/2538#issuecomment-841803421

**Comment by konstantin-921** [comment]
> Сертификат обслуживания kubelet отличается от сертификата узла, см. [Rancher / rke # 2538 (комментарий)](https://github.com/rancher/rke/issues/2538#issuecomment-841803421)

Thanks, I'm just confused because I thought this approach only applies to rancher clusters and not to downstream clusters. For rancher clusters, the Rancher docs explicitly say that kubelet certs are not under RKE control. But for downstream clusters, the documentation does not say that kubelet certs need to be updated separately.

**Comment by superseb** [comment]
It seems only RKE part was updated (https://rancher.com/docs/rke/latest/en/cert-mgmt/#certificate-rotation), I will port it to the Rancher docs (or link), see https://github.com/rancher/docs/issues/3332
