### ISSUE TITLE
V2.4.15 rancher ui k3s certificates not rotating, ui startup issue

### ISSUE THREAD

**Issue by superxor** [rancher/rancher#33162]
v2.4.15

2021-06-13 05:44:38.711999 I | http: TLS handshake error from 127.0.0.1:51356: remote error: tls: bad certificate
time="2021-06-13T05:44:38.718397498Z" level=error msg="Failed to generate kubeconfig: server https://127.0.0.1:6443/cacerts is not trusted: Get https://127.0.0.1:6443/cacerts: x509: certificate has expired or is not yet valid"

2021/06/13 05:52:43 [INFO] Waiting for k3s to start
2021/06/13 05:52:44 [INFO] Waiting for k3s to start
2021/06/13 05:52:45 [INFO] Waiting for k3s to start
2021/06/13 05:52:46 [INFO] Waiting for k3s to start
2021/06/13 05:52:47 [INFO] Waiting for k3s to start

How do I fix this? Why arent k3s certs regenerated by themselves?
I already tried to restore from backup and it still fails

**Comment by superxor** [comment]
Problem seems to be that the k3s certs expired. How do I regen those?

**Comment by superxor** [comment]
root@0f8f12c0d140:/var/lib/rancher# openssl s_client -showcerts  -connect 127.0.0.1:6443 | openssl x509 -noout -dates
depth=0 O = k3s, CN = k3s
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 O = k3s, CN = k3s
verify error:num=21:unable to verify the first certificate
verify return:1
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Jun 12 11:54:03 2021 GMT

BUT

root@0f8f12c0d140:/var/lib/rancher/k3s/server/tls# for i in `ls *.crt`; do echo $i; openssl x509 -noout -startdate -enddate -in $i; done
client-admin.crt
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Apr 14 04:51:10 2022 GMT
client-auth-proxy.crt
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Apr 14 04:51:10 2022 GMT
client-ca.crt
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Oct  9 04:36:11 2029 GMT
client-cloud-controller.crt
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Mar 14 16:51:22 2022 GMT
client-controller.crt
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Apr 14 04:51:10 2022 GMT
client-k3s-controller.crt
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Mar 14 16:51:22 2022 GMT
client-kube-apiserver.crt
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Apr 14 04:51:10 2022 GMT
client-kube-proxy.crt
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Apr 14 04:51:10 2022 GMT
client-scheduler.crt
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Apr 14 04:51:10 2022 GMT
request-header-ca.crt
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Oct  9 04:36:11 2029 GMT
server-ca.crt
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Oct  9 04:36:11 2029 GMT
serving-kube-apiserver.crt
notBefore=Oct 12 04:36:11 2019 GMT
notAfter=Apr 14 04:51:10 2022 GMT

**Comment by superxor** [comment]
Solved by : kubectl delete secret -n kube-system k3s-serving--insecure-skip-tls-verify
update to latest stable
restart container

**Comment by InsOpDe** [comment]
Im getting `error: You must be logged in to the server (Unauthorized)`. is there any other way to renew the certs?
