### ISSUE TITLE
v1 monitoring expose services have Type and Target keys set to Unknown values on RKE1 clusters

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#33179]
**What kind of request is this (question/bug/enhancement/feature request):** bug

This bug seen in`rancher:2.5.5`, `rancher:2.5.8` as well as in `master-head 5715b8a`

**Steps to reproduce (least amount of steps as possible):**
* From local cluster with `rancher/rancher:master-head 5715b8a` or `rancher/rancher:2.5.8` provision a custom RKE1
* deploy cluster level `monitoring-0.2.3` or `monitoring-0.2.2` (on 2.5.8) app on the custom cluster
* after a while select `System project` and go to `Resources->Workloads` and select `Service Discovery`

**Result:**
* you will see that all services `expose-kube*` are `Active` but they have `Type` and `Target` keys set to `Unknown` value.
![mon-services](https://user-images.githubusercontent.com/12828077/121896676-dc62a800-cd21-11eb-9dab-d8f760bc0d61.png)

* Prometheus reports that all Targets are Healthy
* Graphs are visible with custom RKE1 cluster with k8s `v1.20.7-rancher1-1`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher/rancher:master-head 5715b8a` or `rancher:2.5.8`
- Installation option (single install/HA): any

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE1 custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3+3 nodes for v1 monitoring
- Kubernetes version (use `kubectl version`): any (but v1 monitoring doesn't work with `v1.21.1-rancher2-1`)

**Comment by thehejik** [comment]
Same problem visible in `rancher:2.5.5` with v1 `monitoring-0.2.0`

**Comment by aiyengar2** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/33465, which tracks the same root problem.

**Comment by MKlimuszka** [comment]
v1 monitoring is no longer maintained
