### ISSUE TITLE
[2.5 backport] KEv2 - Support Install on Hardened Cluster

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#33172]
https://github.com/rancher/rancher/issues/29066

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5-head` `version 0e58768` with the following steps:
- Deployed an RKE HA local cluster that is hardened based on steps listed [here](https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.5/1.6-hardening-2.5/) 
- When the HA rancher setup comes up Active, deploy an EKSv2 cluster

Result:
- EKSv2 cluster becomes available in Rancher and EKS console. EKS operator version `v1.0.10-rc1`. k8s version `v1.20.7-eks-8be107`

GKEv2 provisioning is currently blocked by: https://github.com/rancher/rancher/issues/33721
AKSv2 is not available in v2.5.10. AKSv1 provisioning is successful on v2.5-head.

**Comment by cbron** [comment]
AKSv2 won't be available in 2.5, so we only have to test that in 2.6.

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5-head` `version 500de20` with the following steps:
- Deployed an RKE HA local cluster that is hardened based on steps listed [here](https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.5/1.6-hardening-2.5/) 
- When the HA rancher setup comes up Active, deploy an EKSv2 and GKEv2 cluster

Result:
- EKSv2 cluster becomes available in Rancher and EKS console. EKS operator version `v1.0.10-rc1`. k8s version `v1.20.7-eks-8be107`
- GKEv2 cluster becomes available in Rancher and GKE console. GKE operator version `v1.1.1-rc7`. k8s version `v1.19.9-gke.1900`
