### ISSUE TITLE
Rancher-metadata

### ISSUE THREAD

**Issue by elerion** [rancher/rancher#3317]
Hi,

I try to use ELK to view my logs form my containers, but I am behind a proxy and I have a problem to use rancher-medata. I need to recover an IP address for rancher-metada. Do you know how to use rancher-metadata behind a proxy ?

Thx

**Comment by deniseschannon** [comment]
Rancher metadata is only valid over the managed network.

**Comment by deniseschannon** [comment]
Where are you trying to recover the IP address from?

**Comment by deniseschannon** [comment]
And are your running ELK in Rancher?

**Comment by elerion** [comment]
Hi,

When I start ELK from rancher I have an error come from the proxy 
```log
INFO Using Rancher Metadata URL: http://rancher-metadata
25/1/2016 09:01:502016-01-25T08:01:50Z elasticsearch_elasticsearch-masters_1 /confd[1]: ERROR invalid character '<' looking for beginning of value
25/1/2016 09:01:502016-01-25T08:01:50Z elasticsearch_elasticsearch-masters_1 /confd[1]: ERROR invalid character '<' looking for beginning of value
25/1/2016 09:01:502016-01-25T08:01:50Z elasticsearch_elasticsearch-masters_1 /confd[1]: ERROR invalid character '<' looking for beginning of value
```
It seems that when ELK start http://rancher-metadata pass throught the proxy.

**Comment by deniseschannon** [comment]
@elerion Did you mean to close this?

**Comment by elerion** [comment]
Yes I found how to configure my proxy
