### ISSUE TITLE
[2.5 backport] KEv2- Ensure CIS hardened profile scan passes

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#33171]
https://github.com/rancher/rancher/issues/29067

**Comment by aaronRancher** [comment]
Tested on Rancher, `v2.5-head` `version 0713103` with the following steps:
- Deployed an RKE HA local cluster that is hardened based on steps listed [here](https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.5/1.6-hardening-2.5/) 
- Install CIS Benchmark 1.0.400 on local cluster
- Run `rke-profile-hardened-1.6` scan on local cluster
- When the HA rancher setup comes up Active, deploy an EKSv2 and GKEv2 cluster
EKS operator: v1.0.10-rc1
GKE operator: v1.1.1-rc10
- Run `rke-profile-hardened-1.6` scan on local cluster again

Result:
The first scan has two failures (5.1.5 and 5.3.2). These are expected.
![Screen Shot 2021-08-03 at 4 09 57 PM](https://user-images.githubusercontent.com/57409052/128097643-34c6ed05-3fb9-4092-9303-ccea3ae38607.png)
The second scan with kev2 operators deployed show the same failures. No additional failures are seen.
