### ISSUE TITLE
Services not removed after deleting workload

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#33178]
**What kind of request is this (question/bug/enhancement/feature request):** bug

* **rancher:2.5.8** with custom RKE1 `v1.20.6-rancher1-1` **is also affected** same reproducer applicable

**Steps to reproduce (least amount of steps as possible):**
* In Ember UI deploy any workload on custom RKE1 cluster with `v1.21.1-rancher2-1` in default namespace
* corresponding service for the workload in created automatically in `Service Discovery` pane
* Wait/reload to see if the workload is ready (reload needed due https://github.com/rancher/rancher/issues/32972)
* Delete the workload you created

**Result:**
* Switch to `Service Discovery` pane in Resources and see that services created automatically for the workload are still in place, only `Target` value has been removed. The services should be removed together with the workload.

**Other details that may be helpful:**
I was using 1-pod busybox Deployment with no ports exposed, just running `/bin/sh -c 'sleep infinity'` command

* The same stands also for ingresses - When you create an ingress for a workload like `nginx` and then you delete the ingress the corresponding generated service like `ingress-53aca48d52db91d9b565d5cbf97e80a0` is not removed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher/rancher:master-head 5715b8a`
- Installation option (single install/HA): any

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom RKE1
- Machine type (cloud/VM/metal) and specifications (CPU/memory): any
- Kubernetes version (use `kubectl version`): `v1.21.1-rancher2-1` (local RKE1 cluster + custom RKE1)

**Comment by sowmyav27** [comment]
This issue is seen on 2.5.8 also.

**Comment by MKlimuszka** [comment]
QA hasn't seen this since the comments above on the 2.5.x line, which is no longer receiving bug fixes. Closing.
