### ISSUE TITLE
rke2 clusters[custom/nodedriver] stuck in error state upon clicking create button with Internal error occurred: failed calling webhook

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33182]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. On the rancher server, create a node driver rke2 DO cluster with 1 node all roles and click on create. 
2. Cluster displays the following error, provisioning won't start and is not reconciled from that state. It is stuck in the error state

```
Failed to create fleet-default/test1 cluster.x-k8s.io/v1alpha4, Kind=Cluster for rke-cluster 
fleet-default/test1: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": 
Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1alpha4-cluster?timeout=10s":
service "webhook-service" not found, failed to create fleet-default/test1-pool1 cluster.x-k8s.io/v1alpha4, Kind=MachineDeployment for rke-cluster fleet-default/test1: Internal error occurred: 
failed calling webhook "default.machinedeployment.cluster.x-k8s.io": Post 
"https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1alpha4-machinedeployment?timeout=10s": service "webhook-service" not found
```

**Result:**
Cluster should not go into error state and should have come up active.

**Other details that may be helpful:**
Happens for both custom cluster and node driver cluster single node and multiple nodes
Some logs from console logs:
```
vue-router.esm.js:1958 Uncaught (in promise) Error: Navigation cancelled from "/c/local/manager/provisioning.cattle.io.cluster/create?type=digitalocean" to "/c/local/manager/provisioning.cattle.io.cluster/create?type=digitalocean#pool1" with a new navigation.
    at $t (vue-router.esm.js:1958)
    at kt (vue-router.esm.js:1940)
    at x (vue-router.esm.js:2249)
    at r (vue-router.esm.js:1898)
    at vue-router.esm.js:1899
    at vue-router.esm.js:2274
    at $n.<anonymous> (client.js:125)
    at d (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.O.forEach.t.<computed> [as next] (runtime.js:97)
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 5715b8a
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Node driver and custom
- Kubernetes version (use `kubectl version`):

```
v1.21.1-rc2+rke2r1
```

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/pull/33186 
https://github.com/rancher/rancher/pull/33187

**Comment by anupama2501** [comment]
Verified on 9d54b1a

1. Created a node driver rke2 DO cluster 1 node all roles, once the config is saved and created, cluster did not go into error state
2. Cluster has come up active and the cluster is accessible from explore cluster 
3. Edited the cluster and added another node pool with worker role and saved the config
4. Cluster has come up active and all the nodes have come up active
5. From explore cluster, verified the cluster is active

Test2:
Created an rke2 custom cluster and ran the registration command on the node - EC2 instance
Cluster ahas come up active and is accessible from explore cluster page
