### ISSUE TITLE
v1 monitoring doesn't work on custom RKE1 clusters with k8s v1.21

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#33181]
**What kind of request is this (question/bug/enhancement/feature request):** bug

This bug seen in `rancher/rancher:master-head 5715b8a` with custom RKE1 cluster with `v1.21.1-rancher2-1` - it does work with clusters using k8s `v1.20.7-rancher1-1`

**Steps to reproduce (least amount of steps as possible):**
* From local cluster with `rancher/rancher:master-head 5715b8a` provision a custom RKE1 with k8s `v1.21.1-rancher2-1`
* deploy cluster level v1 `monitoring-0.2.3` app on the custom cluster from Ember UI
* once the v1 `monitoring-0.2.3` is installed go to Cluster Overview page on Ember UI and see if there are "advanced" graphs from monitoring present

**Result:**
* Graphs are not visible in Grafana (no data) neither on Cluster Overview page in Ember UI
* Prometheus reports that all Targets are Up and Healthy
* Graphs are visible with custom RKE1 cluster with k8s `v1.20.7-rancher1-1` but not with `v1.21.1-rancher2-1`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher/rancher:master-head 5715b8a`
- Installation option (single install/HA): any

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE1 custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3+3 nodes for v1 monitoring
- Kubernetes version (use `kubectl version`): `v1.21.1-rancher2-1`

**Comment by thehejik** [comment]
I opened also https://github.com/rancher/rancher/issues/33179 but it is probably not related as the `Unknown` values for expose-kube* services are present in 2.5.8 as well where is v1 monitoring working fine.

**Comment by aiyengar2** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/33465, which tracks the same root problem.
