### ISSUE TITLE
Getting 403 Forbidden when updating Kubernetes version of a cluster

### ISSUE THREAD

**Issue by samkit-jain** [rancher/rancher#33193]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Log in to the Rancher UI
2. Open a cluster
3. Click Edit
4. In the "Kubernetes Options" section, select the Kubernetes version as `v1.17.17-rancher-2-3`.
5. Click Save.
![image](https://user-images.githubusercontent.com/15127115/122027808-0df27680-cde9-11eb-8842-d511c79fedeb.png)

**Result:**
Error message
```
<html> <head><title>403 Forbidden</title></head> <body> <center><h1>403 Forbidden</h1></center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->
```
![image](https://user-images.githubusercontent.com/15127115/122028571-cae4d300-cde9-11eb-9a52-d3f9ec8c813a.png)

**Other details that may be helpful:**
The existing Kubernetes Version is `v1.17.17-rancher-2-1`. This user is an administrator and has all permissions. The user is also the owner of the cluster.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS EC2
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AWS EC2
- Kubernetes version (use `kubectl version`): v1.17.17-rancher2-1
- Docker version (use `docker version`):

**Comment by samkit-jain** [comment]
Any update on this?

**Comment by superseb** [comment]
Please provide more information in the issue, is this single Docker install or HA? What type/version of HA cluster? Is this only on cluster update or on any other GET (just visiting pages) or POST (submitting forms) requests? Since when is this happening?

**Comment by samkit-jain** [comment]
>is this single Docker install or HA?

It is a single Docker

>Is this only on cluster update or on any other GET (just visiting pages) or POST (submitting forms) requests?

It happens on operations like updating the Docker version from the Rancher UI or adding members to a cluster. Operations like creating a pod, etc. work fine.

>Since when is this happening?

I first experienced it a month ago.

**Comment by superseb** [comment]
What is the `docker run` command you used to create the container? Are you exposing ports directly or with something in front of it?

What does `updating the Docker version from the Rancher UI` mean exactly?

**Comment by samkit-jain** [comment]
>What is the docker run command you used to create the container? Are you exposing ports directly or with something in front of it?

```
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:v2.5.8 --server <IP ADDRESS> --token <TOKEN> --ca-checksum <CHECKSUM> --etcd --controlplane --worker
```
Redacted the token and replaced it with `<>`.

>What does updating the Docker version from the Rancher UI mean exactly?

Apologies, I meant Kubernetes. Have updated the reply accordingly.

**Comment by superseb** [comment]
Sorry I am talking about the container running the `rancher/rancher` image, not the `docker run` command to add a node to a cluster.

**Comment by juvoxa** [comment]
`docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:latest`

We are not exposing ports directly as there is an ALB in front. @superseb

**Comment by samkit-jain** [comment]
We got this resolved by changing the IP address in the Rancher Settings to <example>.rancher.com Thanks @superseb for the assistance.
