### ISSUE TITLE
[cli] login without context for noninteractive use

### ISSUE THREAD

**Issue by betweenclouds** [rancher/rancher#33191]
**enhancement**
To create a new cluster in a noninteractive way, it would be helpful if you can login without setting a context or set the context at the commandline to the cluster name:project name like ` --context local:Default` because you maybe don't know the project ID at this point.

**Steps to reproduce (least amount of steps as possible):**
```
rancher login https://myrancher.local/v3 --token mytoken
```
**Interactive Result:**
```
NUMBER    CLUSTER NAME     PROJECT ID        PROJECT NAME   PROJECT DESCRIPTION
1         clu-01           c-c4r8l:p-nccct   Default        Default project created for the cluster
2         clu-01           c-c4r8l:p-xdhrp   System         System project created for the cluster
3         local            local:p-n9rtz     System         System project created for the cluster
4         local            local:p-q5rtf     Default        Default project created for the cluster
Select a Project:

```

**Environment information**
CLI rancher version v2.4.11

**Comment by dmpe** [comment]
Yes, please, Currently I am solving this with echo "1" | rancher login....which however is extremely unflexible because you cannot select target cluster beforehand.

**Comment by dmpe** [comment]
this is certainly not stale.

**Comment by betweenclouds** [comment]
still an issue

**Comment by dmpe** [comment]
no stale!
