### ISSUE TITLE
Image export script returns error

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#33201]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Download latest data.json (from dev-v2.6 branch) in path $HOME/bin/data.json
2. Clone latest rancher/charts in rancherpath and checkout origin/dev-v2.6
3. Clone latest rancher/system-charts in rancher path and checkout origin/dev-v2.6: `HOME=$(pwd)  REPO=rancher TAG=dev go run pkg/image/export/main.go system-charts charts/assets rancher/rancher:master-head rancher/rancher-agent:master-head`

**Result:**
Error similar to the following is encountered: `2021/06/14 17:28:46 Image [calico/cni:v3.18.1] does not start with rancher/
exit status 1`

**Other details that may be helpful:**
This is because rke2 1.21.1-rc2 has invalid images in its `rke2-images-all.linux-amd64.txt` file. Updating kdm to use rc3 should resolve this issue https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/channels-rke2.yaml#L11.

**Comment by nickgerace** [comment]
Related issue: https://github.com/rancher/rancher/issues/32403

**Comment by nickgerace** [comment]
This is awaiting a Rancher v2.6 RC for QA validation. Validation should pass if the images list contains all expected images in the RC.

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by snasovich** [comment]
@cmurphy , please validate this one when you have time.

**Comment by cmurphy** [comment]
Validated on v2.6.0-rc1.

Validation steps: from rancher source code, ran:

```
git clone -b dev-v2.6 git@github.com:rancher/charts
git clone -b dev-v2.6 git@github.com:rancher/system-charts
CATTLE_KDM_BRANCH=dev-v2.6
curl -sLf https://releases.rancher.com/kontainer-driver-metadata/${CATTLE_KDM_BRANCH}/data.json > bin/data.json
HOME=$(pwd) REPO=rancher TAG=dev go run pkg/image/export/main.go system-charts charts/assets rancher/rancher:v2.6.0-rc1 rancher/rancher-agent:v2.6.0-rc1
```

Result: command executes successfully, outputs rancher-images.txt with valid image list.
