### ISSUE TITLE
namespaces not in use on the latest rancher are not cleaned up and are created outside any project in local cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33203]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
### Upgrade scenario

- Deployed an RKE HA 2.5.8 setup, local cluster is RKE
- Deployed a downstream cluster.
- Upgrade Rancher to master-head commit id: `2b50005`
- These namespaces are seen outside any project in local RKE cluster

<img width="1286" alt="Screen Shot 2021-06-15 at 1 42 42 PM" src="https://user-images.githubusercontent.com/26032343/122120818-bc91b980-cddf-11eb-8394-b0dc0a75aee2.png">

### On a fresh install of master-head commit id: `2b50005`
`fleet-system` namespace is seen which is not in any project
<img width="1291" alt="Screen Shot 2021-06-15 at 1 04 18 PM" src="https://user-images.githubusercontent.com/26032343/122121677-c5cf5600-cde0-11eb-84e7-1040f71a72ae.png">

**Expected Result:**
The namespaces not in use must be cleaned up

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `2b50005`
- Installation option (single install/HA): HA/single

**Comment by StrongMonkey** [comment]
Rancher-operator-system clean up is fixed here https://github.com/rancher/rancher/pull/33212. For fresh-install with fleet-system, there are some limitation but once https://github.com/rancher/rancher/pull/32528 is merged I can address that also.

**Comment by StrongMonkey** [comment]
@sowmyav27 In master `Rancher-operator-system` should be gone after upgrade. I will try to fix the fleet system later now.

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.8 too master-head commit id: `def25f1`**

- rancher-operator-system namespace is removed
- fleet-system namespace is still seen outside any Project. 
- Other namespaces moved to cattle-system
<img width="1243" alt="Screen Shot 2021-06-16 at 10 32 28 PM" src="https://user-images.githubusercontent.com/26032343/122337148-c7893e80-cef2-11eb-9745-13804fd8c98f.png">

Reopening for fixes fleet-system namespace

**Comment by StrongMonkey** [comment]
@sowmyav27 On fresh install you shouldn't see fleet-system namespace. On upgrade it is still kept around in case it is used by other workloads.

**Comment by sowmyav27** [comment]
**On an upgrade, from 2.5.8 to master-head commit id: `c7f3cce`**

All fleet related namespaces are seen under System project.
However, I do not see fleet-system namespace anymore this time. 

Is it removed in any case ?

**Comment by sowmyav27** [comment]
Moving this issue to reopened state because of [this](https://github.com/rancher/rancher/issues/33203#issuecomment-869337298)

**Comment by nickgerace** [comment]
Reproduction steps without Rancher:
```sh
k3d cluster delete
k3d cluster create
VERSION=0.3.5
helm -n fleet-system install --create-namespace --wait \
    fleet-crd https://github.com/rancher/fleet/releases/download/v${VERSION}/fleet-crd-${VERSION}.tgz
helm -n fleet-system install --create-namespace --wait \
    fleet https://github.com/rancher/fleet/releases/download/v${VERSION}/fleet-${VERSION}.tgz
sleep 50
helm uninstall -n fleet-system fleet
kubectl create ns cattle-fleet-system
helm install -n cattle-fleet-system fleet --set agentImage.tag=v0.3.6-rc4 --set agentImage.imagePullPolicy=Always ./charts/fleet
kubectl delete deployment -n cattle-fleet-system fleet-controller
NAMESPACE=cattle-fleet-system go run cmd/fleetcontroller/main.go
```

**Comment by sowmyav27** [comment]
Will validate after this issue is fixed - https://github.com/rancher/rancher/issues/33677

**Comment by sowmyav27** [comment]
**Validated on an upgrade from 2.5.9 to master-head commit id: `21ab02c`**

- On a docker install of rancher, deploy a downstream cluster.
- Upgrade rancher to master-head
- In the local cluster --> System project --> Noticed Old fleet agent gets deleted first and the new fleet agent is available `rancher/fleet-agent:v0.3.6-rc7`
- fleet-system namespace is not available in this setup.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `10588abd`** 

- fleet - `rancher/fleet-agent:v0.3.6-rc8`
- On a docker install of rancher, deploy a downstream cluster.
- Upgrade rancher to master-head
- fleet-system namespace is available
- New Fleet agent is created and the old one gets deleted.
- But the original issue is seen where `fleet-clusters-system` is seen outside a Project
<img width="1303" alt="Screen Shot 2021-08-03 at 11 17 13 PM" src="https://user-images.githubusercontent.com/26032343/128131460-80617ccb-0f93-48bd-809c-ce79209e2f4e.png">

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to 2.6-head - commit id: `e3316c9de`**

- Fleet version: `rancher/fleet-agent:v0.3.6-rc9`
- Old fleet is deleted, and new fleet agent is deployed
- `fleet-clusters-system` is not available anymore. 
- Clusters are in Wait Check-in state under Continuous Delivery tab. There are errors on the bundles
- ```
message: 'ErrApplied(1) [Cluster fleet-default/c-gqn2r: no Deployment with the
      name "fleet-agent" found]'
```
- And on adding a new repo, it is in Wait Applied state. 
Logging a separate bug for this - https://github.com/rancher/rancher/issues/33980
