### ISSUE TITLE
aks v2 - cannot create cluster with networkPolicy=calico & networkplugin=kubenet

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33202]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. master-3d465ee7cc5afbea762e328affbb76e88ebd3229-head
2. Create AKS
3. networkPolicy=calico & networkplugin=kubenet
4. Save

**Result:**
Created cluster will have Network type (plugin) set to Kubenet. However, Network Policy will get set to "-" (instead of calico)

**Other details that may be helpful:**
AKS allows users to create clusters with Network type (plugin) = Kubenet and Network Policy = calico

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by prabalsharma** [comment]
@mjura will this PR address this issue? https://github.com/rancher/aks-operator/pull/29

**Comment by mjura** [comment]
> @mjura will this PR address this issue? [rancher/aks-operator#29](https://github.com/rancher/aks-operator/pull/29)

yeap, it was merged and it is fixed now

**Comment by mjura** [comment]
Fix https://github.com/rancher/aks-operator/pull/32

**Comment by prabalsharma** [comment]
tested on master-3e44415, aks-operator:v1.0.1-rc14
