### ISSUE TITLE
Error looking up service account cattle-system/cattle: serviceaccount

### ISSUE THREAD

**Issue by mstimvol** [rancher/rancher#33216]
**What kind of request is this (question/bug/enhancement/feature request):**

Not sure if it's a bug or if it's just a qustion.

**Steps to reproduce (least amount of steps as possible):**

I'm not sure what happens / how we can reproduce the problem. I already created some other clusters using Rancher without any problems but now I created a new cluster as I've done previously and now the "kube-api-auth" DaemonSet says:
> Error creating: pods "kube-api-auth-" is forbidden: error looking up service account cattle-system/cattle: serviceaccount "cattle" not found

But when I check the service accounts available in the "cattle-system"-namespace, I can see that there's a user called "cattle".

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8
- Installation option (single install/HA): Multi-Cluster (I'm using Rancher to manage multiple clusters)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud, / 2GHz / 8GB memory per node
- Kubernetes version (use `kubectl version`):

```
Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc"
```

- Docker version (use `docker version`):

```
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
```

**Comment by nickgerace** [comment]
Hi! It would be great to gather information for the following:

1. Do you have logs from the Rancher pod related to this? (`kubectl logs -n cattle-system <rancher-pod>` and there may be relevant logs in there)
