### ISSUE TITLE
How to expose rancher-agent cAdvisor so it can be polled from prometheus

### ISSUE THREAD

**Issue by rickalm** [rancher/rancher#3321]
I've tried setting CATTLE_CADVISOR_IP when launching rancher-agent to the IP address of the host but the process keeps getting bound to 127.0.0.1

Because of the CPU burden cAdvisor is already placing on the host I do not want to deploy a second instance to collect statistics, but I cannot see an easy way to get around this issue.

**Comment by m4ce** [comment]
In theory, it should be possible to specify remote backends with the CATTLE_CADVISOR_OPTS environment variable.

https://github.com/rancher/rancher/issues/3204 

However, i tried it and it doesn't propagate to the rancher-agent container. I think the rancher agent /run.sh needs to be looked at.

**Comment by m4ce** [comment]
@cloudnautique, is there any way we can get this to work in the current version of the agent?

**Comment by cloudnautique** [comment]
@m4ce, 

Not in the current v0.8.2. The next release will allow changing the variables.

The cAdvisor opts stuff hasn't been tested, but getting at the cAdvisor data was a driver to add the options. I'm not sure on cAdvisors behavior, but if it stops keeping data in memory then we will not be able to show stats in the UI. Also, we do know that changing the polling intervals breaks the graphs in the UI.

Now that you have been warned...

You will need to set CATTLE_CADVISOR_OPTS in `/var/lib/rancher/etc/agent.conf` on the hosts running the agents. When adding vars through the file they need to be exported. The file gets sourced when the agent starts, and is the only supported way to get variables into the final rancher-agent container.  

You should be able to try it on the latest RC.

**Comment by m4ce** [comment]
@cloudnautique,

thanks for the information. Unfortunately the cadvisor version packaged in Rancher (0.19.3) does not support InfluxDB 0.9. The support was added starting from version 0.20.1.

Would it be possible to upgrade cadvisor in cattle?

Thank you!
Matteo

**Comment by cloudnautique** [comment]
@m4ce, we should be able to get it in one of the next releases. 

@DanielDent, you might find this thread interesting for the cowhand stuff your doing.

**Comment by DanielDent** [comment]
Interesting indeed, thanks for the tag. Being able to set the cAdvisor options would be great, I'd like not to be running a second cadvisor on the system. Setting options deals with one of the two challenges (pushing metrics to InfluxDB).

For the second challenge - Prometheus polling - it would be nice if cadvisor could use rancher's container networking. If there are reasons that is problematic, I suppose an alternative for me might be to create a container which proxies connections.

**Comment by spicykaiju** [comment]
@m4ce and I have been discussing that for pushing metrics to influxDB we might move to something like collectd-docker and not be dependent on cAdvisor.

**Comment by DanielDent** [comment]
My only complaint with cadvisor is that it's a bit of a resource hog, although turning down the reporting frequency helps. Collectd has Prometheus integrations as well, so I guess I'm wondering what's better/worse about collectd for this use case. Not that it necessarily has to be one at the exclusion of the other.

**Comment by spicykaiju** [comment]
I think using collectd is a safer bet in the long run. cAdvisor is a dependency for Rancher and depending what you need it to do in order to fulfil your monitoring requirements, it might just break things at some point.

**Comment by deniseschannon** [comment]
We've added Prometheus as a catalog entry. If this is insufficient, please comment or re-open.
