### ISSUE TITLE
[Monitoring V2] Rebase Grafana to 6.11.0

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#33210]
Splitting https://github.com/rancher/rancher/issues/32519 into a separate issue for Grafana due to licensing concerns that need to be addressed before a rebase is completable.

Based on https://github.com/rancher/rancher/issues/32519#issuecomment-859796883, we should be able to migrate to 6.11.0 of the Helm chart without having issues with AGPLv3. No further upgrades are planned.

**Comment by aiyengar2** [comment]
### Note for QA

As part of this rebase, we are updating rancher/mirrored-kiwigrid-k8s-sidecar to 1.12.2. This is beyond what the upstream chart of 6.11.0 is at, but no breaking changes seem to have been made.

Since this will involve changing the sidecar that watches for new Grafana Dashboard / Datasource ConfigMaps to dynamically upgrade Grafana, you will need to test any / all test cases that relate to the creation or update of Grafana dashboards via the UI.

A good set of test cases would probably be:
- Ensuring a Grafana dashboard added by ConfigMap [based on our docs](https://rancher.com/docs/rancher/v2.5/en/monitoring-alerting/persist-grafana/) shows up in Grafana after this change.
- Ensuring that a Grafana dashboard whose ConfigMap is updated sees updates in the UI
- Ensuring that a Grafana dashboard that is deleted is removed from Grafana after a certain point

**Comment by slickwarren** [comment]
on master-head (ad099ee) tested the following:
clean install — Pass
Upgrade 9.4.20x -> 100.0.0+up16.6.0 — pass
uninstall + reinstall — pass
p0 usecase -- pass
Uninstall upgraded 100.0.0+up16.6.0 — pass
Uninstall clean 100.0.0+up16.6.0 — pass
checked all prometheus targets and grafana dashboards
Ensuring a Grafana dashboard added by ConfigMap based on our docs shows up in Grafana after this change.
Ensuring that a Grafana dashboard whose ConfigMap is updated sees updates in the UI
Ensuring that a Grafana dashboard that is deleted is removed from Grafana after a certain point
