### ISSUE TITLE
RKEv1 RHEL 8.4 custom cluster errors on master-head

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#33211]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Provision 1 RHEL 8.4 node using the following AMI (`rhel-8.4-docker-20.10.7-selinux-on` `ami-088ca3352f0170bd3`)
- Run `systemctl disable nm-cloud-setup.service nm-cloud-setup.timer` on the node as per this [comment](https://github.com/rancher/rke2/issues/1053#issuecomment-848061376)
- From Rancher `master-head` `version 5715b8a`, create a custom RKEv1 cluster. 1 node, all roles.
- Run the cluster create command on the node.

**Result:**
Provisioning fails with: `[file-deploy] Failed to deploy file [/etc/kubernetes/kube-api-authn-webhook.yaml] on node [<Node host>]: Failed to start [file-deployer] container on host [<Node host>]: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: failed to set /proc/self/attr/keycreate on procfs: write /proc/self/attr/keycreate: invalid argument: unknown`

**Other details that may be helpful:**
RHEL 8.2 nodes also fail with the same error on master-head
I am able to create an RHEL 8.2 and 8.4 cluster on Rancher `v2.5.8`. (Although RHEL 8.4 is not supported on v2.5.8)
Relevant issues:
https://github.com/rancher/rancher/issues/32830

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-head` `version 5715b8a`
- Installation option (single install/HA): Single install

**Comment by superseb** [comment]
@aaronRancher please include `docker info`, `sestatus` and `runc --version`. This to compare with https://github.com/opencontainers/runc/issues/3031

**Comment by thehejik** [comment]
Same problem on RH-8.3 `ami-0fe96cd6419bbe218` named `rhel-8.3-docker-20.10-selinux-on` with `rancher:master-head 89b7a91` and with k8s `v1.21.1-rancher2-1`. I did `sudo yum update` and 400+ pks was updated (seems it is RH-8.4 now), but I didn't move forward.

```
cat /etc/docker/daemon.json 
{"selinux-enabled": true}
```
Output from `journalctl -u docker` after update [here](https://github.com/rancher/rancher/files/6663351/docker.logs.txt)
 



<details><summary>docker info</summary>

```
# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  selinux
 Kernel Version: 4.18.0-305.3.1.el8_4.x86_64
 Operating System: Red Hat Enterprise Linux 8.4 (Ootpa)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.487GiB
 Name: ip-172-31-11-229.us-east-2.compute.internal
 ID: SQAD:5BWS:PNTF:T3CV:2TQQ:2V36:BMZY:KNOF:J7OT:XCNC:ZJCJ:ZAKV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
</details>

<details><summary>sestatus</summary>

```
# sestatus 
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33
```
</details>

<details><summary>runc --version</summary>

```
# runc --version
runc version 1.0.0-rc95
commit: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
spec: 1.0.2-dev
go: go1.13.15
libseccomp: 2.5.1
```
</details>

**Comment by superseb** [comment]
@aaronRancher @thehejik Please confirm `rancher-selinux` RPM has been installed prior to adding the node to the cluster. https://github.com/rancher/rancher-selinux/pull/6#issuecomment-852251770

If so, please share the setup on Slack with me please.

**Comment by thehejik** [comment]
@superseb it wasn't in my case, trying now

**Comment by thehejik** [comment]
Indeed, this did the trick on RH-8.3 with selinux enabled:
```
sudo rpm -i https://github.com/rancher/rancher-selinux/releases/download/v0.2-rc1.testing.1/rancher-selinux-0.2.rc1-1.el8.noarch.rpm
```

@superseb thanks!

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 54d4afc`
- Provision 1 RHEL 8.4 node using the following AMI (`rhel-8.4-docker-20.10.7-selinux-on` `ami-088ca3352f0170bd3`)
- Run `systemctl disable nm-cloud-setup.service nm-cloud-setup.timer` on the node as per this [comment](https://github.com/rancher/rke2/issues/1053#issuecomment-848061376)
- Reboot the node
- Install `rancher-selinux` RPM with `sudo rpm -i https://github.com/rancher/rancher-selinux/releases/download/v0.2-rc1.testing.1/rancher-selinux-0.2.rc1-1.el8.noarch.rpm`
- From Rancher `master-head` `version 5715b8a`, create a custom RKEv1 cluster. 1 node, all roles.
- Run the cluster create command on the node.
- The cluster is provisioned successfully.

Thank you @superseb

**Comment by thehejik** [comment]
I think that a note in documentation would be useful.

I found only https://rancher.com/docs/rancher/v2.5/en/security/selinux/ with a note that `rancher-selinux` rpm is need only for `rancher-logging` but it's not true anymore - now it's needed for RKE1 deployment itself with enabled selinux.

Reopening due missing doc.

**Comment by superseb** [comment]
We can track this here https://github.com/rancher/docs/issues/3346
