### ISSUE TITLE
Update Harbor Version in Helm Registry

### ISSUE THREAD

**Issue by maese83** [rancher/rancher#33218]
We use the Harbor Helm Chart from the Rancher Helm Registry. But it is a very old Version available: Installed Harbor version **v1.10.2**
Newest Harbor Chart is: **v2.2.2**

Is there a easy way to switch to newest version without loosing the data/configs?
Best regards,
Marcel

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.8` UI: `v2.5.8` |
|Route|`undefined`|

**Comment by nickgerace** [comment]
Hi. I am closing this issue since this looks like a good candidate for our [users Slack](https://slack.rancher.io/), and I do not want it to get lost. Please ask there, we would love to help!
