### ISSUE TITLE
modify rancher server/agent ports

### ISSUE THREAD

**Issue by 947190576** [rancher/rancher#33215]
For security reasons, port 22 on the host is restricted (or any other port). Is there any way to modify the port that Rancher needs to open

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.8` UI: `v2.5.8` |

**Comment by nickgerace** [comment]
Hi. I am closing this issue since this looks like a good candidate for our [users Slack](https://slack.rancher.io/), and I do not want it to get lost. Please ask there, we would love to help!
