### ISSUE TITLE
Chart Repositories failed to refresh on latest master

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#33224]
**What kind of request is this:**
bug

**Steps to reproduce:**

- HA RKE1 install 
- Provision Downstream cluster

**Result:**
Rancher server log 

`Git -C /var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9 reset --hard FETCH_HEAD error: exit status 128, detail: fatal: Unable to create '/var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9/.git/index.lock': File exists. Another git process seems to be running in this repository, e.g. an editor opened by 'git commit'. Please make sure all processes are terminated then try again. If it still fails, a git process may have crashed in this repository earlier: remove the file manually to continue.:git -C /var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9 reset --hard HEAD error: exit status 128, detail: fatal: Unable to create '/var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9/.git/index.lock': File exists. Another git process seems to be running in this repository, e.g. an editor opened by 'git commit'. Please make sure all processes are terminated then try again. If it still fails, a git process may have crashed in this repository earlier: remove the file manually to continue.`

**Other details that may be helpful:**

**Environment information**
- Rancher version: `2.6 master-head (06/16/2021)` _54d4afc_
- Installation option: HA RKE1

**Comment by anupama2501** [comment]
Verified on master-head 741adaf HA rancher server 

- No error is seen in the chart repositories and that all the charts are showing up in the apps & market place. Partner and rancher chart repos are in active state.
- Deployed monitoring v2 chart from explorer --> apps & marketplace and the deployment went through.
