### ISSUE TITLE
Rancher k8s 1.20 cluster and SelfLink

### ISSUE THREAD

**Issue by martinounap** [rancher/rancher#33226]
Hi

Could you please help us. We are using rancher, and after upgrading to 1.20 some of out operators can not work. Problem is that from 1.20 k8s version enabled by default feature flag "RemoveSelfLink".

Is there any kind of solution to disable it in some clusters?

We are using Rancher 2.5.8

**Comment by nickgerace** [comment]
Hi. I am closing this issue since this looks like a good candidate for our [users Slack](https://slack.rancher.io/), and I do not want it to get lost. Please ask there, we would love to help!
