### ISSUE TITLE
aksv2 - logAnalyticsWorkspaceName shows wrong value

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33238]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create AKS cluster
2. Enable monitoring with following values
3. "logAnalyticsWorkspaceGroup": "defaultresourcegroup-eus"
4. "logAnalyticsWorkspaceName": "prabal-log-workspace"
5. Wait for cluster to become Active
6. Check spec in API

**Result:**
"logAnalyticsWorkspaceGroup" get set to "defaultresourcegroup-eus", as expected. However, "logAnalyticsWorkspaceName" get set to "p", instead of prabal-log-workspace.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Changes**
- [ ] https://github.com/rancher/aks-operator/pull/35/

**Comment by mjura** [comment]
Fix was submitted https://github.com/rancher/aks-operator/pull/35/

**Comment by prabalsharma** [comment]
@mjura I am still seeing the same thing
<img width="1116" alt="Screen Shot 2021-06-28 at 2 37 40 PM" src="https://user-images.githubusercontent.com/3749546/123707340-67619900-d81e-11eb-9fe9-176f84b8118b.png">
master-7a2fc74f9598b41b98f2ac5d644a677d29e83e45-head, aks aks-operator:v1.0.1-rc11

**Comment by mjura** [comment]
Bug is fixed in 
https://github.com/rancher/rancher/pull/33413

**Comment by mjura** [comment]
Bug is fixed in aks-operator 1.0.1-rc14

**Comment by prabalsharma** [comment]
tested on master-3e44415, aks-operator:v1.0.1-rc14
