### ISSUE TITLE
how to add metadata to the nodes created through openstack provider in RKE

### ISSUE THREAD

**Issue by kmr210** [rancher/rancher#33235]
**What kind of request is this (question/bug/enhancement/feature request):** Question

**Steps to reproduce (least amount of steps as possible):**  Not clear on how to add meta key:val pair to openstack VM

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  	v2.5.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
-
- Kubernetes version (use `kubectl version`):

 Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by nickgerace** [comment]
Hi. I am closing this issue since this looks like a good candidate for our [users Slack](https://slack.rancher.io/), and I do not want it to get lost. Please ask there, we would love to help!
