### ISSUE TITLE
aksv2 - upstreamSpec.monitoring get set to null for imported clusters with monitoring enabled

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33237]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create AKS cluster with monitoring enabled
2. import / register the cluster on Rancher
3. Check upstreamSpec.monitoring or go to "Edit cluster" in UI and you will find no check on Monitoring option

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Changes**
- [ ] https://github.com/rancher/aks-operator/pull/35

**Comment by gaktive** [comment]
@westlywright to check on the spec.

**Comment by westlywright** [comment]
@mjura @gak This does seem to be a backend issue. I imported 2 different clusters with `Container monitoring` enabled from the AKS UI. After successful import and allowing time for the sync to finish (~5min), the upstream spec is missing the various related fields for the monitoring as seen below

```
{
  "privateRequiresTunnel": null,
  "rbacEnabled": null,
  "type": "/v3/schemas/aksStatus",
  "upstreamSpec": {
    "authBaseUrl": null,
    "authorizedIpRanges": null,
    "azureCredentialSecret": "...redacted...",
    "baseUrl": null,
    "clusterName": "wes-import-2",
    "dnsPrefix": "wes-import-2-dns",
    "dnsServiceIp": "...redacted...",
    "dockerBridgeCidr": "...redacted...",
    "httpApplicationRouting": false,
    "imported": true,
    "kubernetesVersion": "1.19.11",
    "loadBalancerSku": "Standard",
    "logAnalyticsWorkspaceGroup": null,
    "logAnalyticsWorkspaceName": null,
    "monitoring": null,
    "networkPlugin": "kubenet",
    "networkPolicy": "",
    "nodePools": [
      {
        "availabilityZones": [
          "1",
          "2",
          "3"
        ],
        "count": 1,
        "enableAutoScaling": false,
        "maxPods": 110,
        "mode": "System",
        "name": "agentpool",
        "orchestratorVersion": "1.19.11",
        "osDiskSizeGB": 128,
        "osDiskType": "Managed",
        "osType": "Linux",
        "type": "/v3/schemas/aksNodePool",
        "vmSize": "Standard_DS2_v2"
      }
    ],
    "podCidr": "...",
    "privateCluster": false,
    "resourceGroup": "wes-import-tests",
    "resourceLocation": "eastus",
    "serviceCidr": "...redacted...",
    "subnet": null,
    "tags": {},
    "type": "/v3/schemas/aksClusterConfigSpec",
    "virtualNetwork": null,
    "virtualNetworkResourceGroup": null
  }
}
```

**Comment by gak** [comment]
Hi @westlywright! it's @gaktive you're after, not @gak. 👍

**Comment by prabalsharma** [comment]
tested on master-3e44415, aks-operator:v1.0.1-rc14
