### ISSUE TITLE
[GKEv2] Unable to provision a default cluster

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#33241]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
On Rancher `v2.5.9-rc2`, deploy a GKEv2 cluster through ember UI.
Enter cloud config.
Leave all fields default.
Enter node group name.
Create cluster.

**Result:**
Cluster provisioning fails with `Googleapi: Error 400: Private cluster config can only be set on private clusters., badRequest`
The UI sends the following `privateClusterConfig`:
```
privateClusterConfig: {
enablePrivateEndpoint: false
enablePrivateNodes: false
masterIpv4CidrBlock: null
type: "/v3/schemas/gkePrivateClusterConfig"
}
```

**Other details that may be helpful:**
GKE operator version `gke-operator:v1.0.1`
This was also reproduced on `v2.5.8`, `v2.5.9-rc1`, and `master-head` `version 54d4afc`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5.9-rc2`
- Installation option (single install/HA): single install

**Comment by aaronRancher** [comment]
This error is also seen on `v2.4-5747-head` when trying to bring up a GKEv1 cluster.

**Comment by gaktive** [comment]
As of 2021 Jun 17, the following US zones are working with default values on 2.5.8:
us-east1-d
us-east4-a
us-east4-b
us-central1-a
us-central1-b
us-west1-a
us-west3-a
us-west3-b
us-west4-a
us-west4-b

Following US regions are working with default values on 2.5.8:
us-east4
us-central1

I'll create backport issues for 2.4.17 and 2.5.10.

**Comment by gaktive** [comment]
We'll check with Google Support if this is expected. Otherwise, we'll surmise that other regions will slowly acquire the new defaults.

**Comment by gaktive** [comment]
And just to make the issue explicit here since it wasn't already, GKE now has "Field [privateClusterConfig] cannot be nil for non-import cluster" warnings when attempting to apply to private clusters in certain zones. @cmurphy pointed to an issue with the provider, not anything we changed on our end for both GKEv1 & v2 so this setting looks to be rolling out.

**Comment by gaktive** [comment]
PRs up for this which need review.

**Comment by aaronRancher** [comment]
Testing is currently blocked by this issue: https://github.com/rancher/rancher/issues/31592#issuecomment-870997073

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 5b0da3d`

GKE operator version: `gke-operator:v1.1.1-rc6`
Was able to provision a default GKEv2 cluster in the following regions: us-east1, us-west1, us-central1
And zones: us-central1-c, us-west1-a

The UI sends the following cluster config by default:
```
privateClusterConfig: {
enablePrivateEndpoint: false
enablePrivateNodes: false
masterIpv4CidrBlock: null
type: "/v3/schemas/gkePrivateClusterConfig"
}
```
With private cluster is enabled, the UI sends the following config:
```
privateClusterConfig: {
enablePrivateEndpoint: false
enablePrivateNodes: true
masterIpv4CidrBlock: "CIDR"
type: "/v3/schemas/gkePrivateClusterConfig"
}
```
