### ISSUE TITLE
Invalid Explore link for downstream cluster on master-head def25f1 

### ISSUE THREAD

**Issue by phakkarainen** [rancher/rancher#33244]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Provision K3s downstream cluster
Click Explore in Cluster Management

**Result:**
 HTTP Error 500: Internal Server Error
{"data":"failed to find Session for client **steve-cluster**-c-m-3c4d0096"} 

**Other details that may be helpful:**
I'm not Steve. :)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
def25f1 
- Installation option (single install/HA):
Single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Local VM (4 cores, 8GB)
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
n/a
```

**Comment by nickgerace** [comment]
Hi! Thanks for testing our software on `master`. It would be great to gather information for the following:

1. How did you provision k3s clusters?
2. Can you reproduce with an HA local cluster?
3. Do you have logs that may help?

**Comment by phakkarainen** [comment]
Thanks for the reply, Nic!

1) Custom, default settings, all roles.
2) Sure. Any specifics on to try? 2 nodes, all roles or spreading the roles on different nodes?
3) Which logs would be of interest?

**Comment by nickgerace** [comment]
Logs of interest would include the Rancher pod itself around the timestamp to when the "Explore" button is clicked. You can also use console tools in your browser to investigate the request itself when clicking on the page.

**Comment by phakkarainen** [comment]
The issue does not exist with the build tagged d44698d.
Thanks.
Closing.

**Comment by nickgerace** [comment]
Thank you @phakkarainen!
