### ISSUE TITLE
aksv2 UI - it will be nice to have monitoring in Cluster Options instead of Networking

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33240]
**What kind of request is this (question/bug/enhancement/feature request):** feature request
Right now monitoring is part of Networking (under advanced options). It will be nice if it can be moved to Cluster Option (under advanced options), to make it more intuitive. 

Not sure how much effort this will take. This is a "nice to have". Feel free to reject or move milestone on this feature request.

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
This has almost zero dev or QA impact so I've gone ahead an implemented the request. One change, I did not hide the option behind advanced here. The more I thought about it the less it feels like an 'advanced' feature. So it will be between username and ssh/tags rows.

**Comment by prabalsharma** [comment]
tested on master-7a2fc74
