### ISSUE TITLE
RKE2 Templates: Deleting cluster created with a template does not clean up all resources (digitaloceanConfigs left behind)

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#33259]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* add an rke2 template to rancher 
* provision a cluster via the new template 
* allow the cluster to come to active state
* delete the cluster
* use the same template with the same settings as the previous cluster to provision a new cluster

**Result:**
Helm chart install fails with error 
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: DigitaloceanConfig "qa-hardcoded-0" in namespace "fleet-default" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "hardcoded-template-0-1623953274": current value is "hardcoded-template-0-1623953126"
```

**Other details that may be helpful:**
removing the config left behind appears to fix this issue (local cluster -> DigitalOceanConfig -> delete config from last install

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 479795f
- Installation option (single install/HA):single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Digital Ocean
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4vCPU
- Kubernetes version (use `kubectl version`): v1.21.0-alpha2+rke2r1

**Comment by StrongMonkey** [comment]
We need to find a way to delete cluster from helm, as it will clean up every resource it creates... Just deleting the cluster won't clean up other resources.

**Comment by slickwarren** [comment]
workaround: from the local cluster, go to apps & marketplace -> installed apps. Uninstall the chart associated with the template that is installed 
* this appears to clean the resources that were mentioned in this ticket, but will wait for @StrongMonkey to confirm as a good workaround. We would still need a good way to integrate this with the cluster management workflow

**Comment by deniseschannon** [comment]
@ibuildthecloud Not sure if there's anything we can do, but I'd like to discuss our options

**Comment by slickwarren** [comment]
tested on 2.6.0-rc1:
* create 2 clusters via rke2 cluster templates (from same template) -- pass
* delete cluster created via rke2 template -> create another cluster using same template -- pass
* create a cluster via template with bad values (i.e. secret that does not exist), then remove that failed cluster and create another with all valid values -- pass


tested on master-head(61339fb):
* create 2 clusters via rke2 cluster templates (from same template) -- pass
* delete cluster created via rke2 template -> create another cluster using same template -- pass
* create a cluster via template with bad values (i.e. secret that does not exist), then remove that failed cluster and create another with all valid values -- FAIL with the below error:
```
Fri, Aug 6 2021 2:57:55 pm | helm install --generate-name=true --namespace=fleet-default --timeout=10m0s --values=/home/shell/helm/values-qa-v2charts-template-0.0.4.yaml --version=0.0.4 --wait=true /home/shell/helm/qa-v2charts-template-0.0.4.tgz
Fri, Aug 6 2021 2:57:56 pm | Error: rendered manifests contain a resource that already exists. Unable to continue with install: DigitaloceanConfig "qa-nooveride0" in namespace "fleet-default" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "qa-v2charts-template-0-1628287075": current value is "qa-v2charts-template-0-1628286611"

```
I'm not sure why I can repro this on master, but not on 2.6.0-rc1. maybe it is a timing thing as well, making this more difficult to reproduce.
