### ISSUE TITLE
enable-admission-plugins plugin "PodPreset" is unknown when upgrade cluster to 1.20.6

### ISSUE THREAD

**Issue by rldourado** [rancher/rancher#33252]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Kubernetes version 1.19 or early.
PodPreset activated and created.
Upgrade to Kubernetes version 1.20.6

**Result:**
rancher/hyperkube:v1.20.6-rancher1 container in crashloop showing the following log:

```
Error: [enable-admission-plugins plugin "PodPreset" is unknown, unknown api groups settings.k8s.io]
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):  Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM ( 4 vCPU's / 4 Gb RAM )
- Kubernetes version (use `kubectl version`): 1.19.10
- Docker version (use `docker version`): 20.10;7

**Comment by nickgerace** [comment]
Hi! It would be great to gather information for the following:

1. How was the upgrade performed?
2. For the "Custom" cluster type, how was it created? Having more information on it may help with upgrade reproduction.

**Comment by poblin-orange** [comment]
@rldourado  I think the reason is k8s 1.20 removed the PodPreset alpha api.
https://v1-20.docs.kubernetes.io/docs/setup/release/notes/#deprecation

Facing same issue here. Considering using kyverno to replace.
