### ISSUE TITLE
Move default nginx annotation to separate block

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#33254]
Since helm merges the values for the extraAnnotations it is not easy to overwrite the default one if a customer is using the upstream Rancher chart repository. They should be made optional so a customer can disable them if they are not using the default nginx ingress but still want to add annotations without disabling the ingress.

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by jiaqiluo** [comment]
this enhancement is validated in rancher `v2.6.0-rc1` chart 

Case 1: default value 
Results: the default Nginx annotations are applied to the `Ingress` resource
```
> k -n cattle-system get ingress rancher -o yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: rancher
    cert-manager.io/issuer-kind: Issuer
    field.cattle.io/publicEndpoints: '[{"addresses":["54.219.178.147"],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"jiaqi-ha2.eng.rancher.space","allNodes":false}]'
    meta.helm.sh/release-name: rancher
    meta.helm.sh/release-namespace: cattle-system
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"  <-- thhis
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   <-- thhis
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   <-- thhis
...
```

Case 2: set `ingress.includeDefaultExtraAnnotations=false` when installing Rancher 
Results: the default Nginx annotations are NOT applied to the `Ingress` resource
```
> k -n cattle-system get ingress rancher -o yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: rancher
    cert-manager.io/issuer-kind: Issuer
    field.cattle.io/publicEndpoints: '[{"addresses":["54.219.178.147"],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"jiaqi-ha2.eng.rancher.space","allNodes":false}]'
    meta.helm.sh/release-name: rancher
    meta.helm.sh/release-namespace: cattle-system
  creationTimestamp: "2021-08-10T18:43:02Z"
...
```

Case 3: install rancher with default value, then upgrade with `ingress.includeDefaultExtraAnnotations=false`
Results:
- at first, the default Nginx annotations are applied to the `Ingress` resource
- and they are removed after the upgrade

**Comment by jiaqiluo** [comment]
@sowmyav27  Please review the validation and close the issue.
