### ISSUE TITLE
Test support for legacy feature flag

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#33264]
UI relies on Legacy feature flag to decide which pages will be available to the user. It doesn't impact any backend changes. 
Legacy will be turned off by default for Rancher v2.6, and users will have the option to turn it on/off. 

We need to test the following use cases:
- Legacy is off by default in 2.6 and only new UI shows up. 
- When legacy is turned on in 2.6, UI will give access to only the pages that are needed to manage tools that are being deprecated/phased out. (Currently it gives access to entire old Cluster Manger UI but that'll be changing soon so mentioning the final expected behavior here). 
- Legacy is on for upgraded Rancher setups to 2.6. Option to turn it on/off would still be available.

**Comment by sowmyav27** [comment]
To validate:

**Fresh Install** 
- Check if Legacy is turned off by default
- User has no access to Ember UI
- Verify MCM feature flag is not available on the UI
- Turn off MCM through API, Verify the rancher pods will restart and MCM will automatically be turned on (will NOT turn off)
- Verify MCM feature flag can only be turned off when starting Rancher (through docker run command or Helm install command)
- Verify When legacy is turned on in 2.6, UI will give access to only the pages that are needed to manage tools 

**Upgrade usecase**
- Legacy is oon by default for upgrade to 2.6
- Verify ooption to turn off/on is available in UI

**Comment by thehejik** [comment]
**Test report:**

**Fresh install:**
* Legacy flag is turned off by default
* No access to Ember UI over any link - appending `/g` or `/login` to rancher URL works - iframe pages from Ember UI are still accessible from Explorer (eg for RKE1 provisioning in Explorer)
* :boom: **MCM flag is present and Active** according to the TC above it shouldn't be available/visible
* I did turn off MCM over WEB UI instead - rancher restarted and the flag was set on again after reload
* :boom: I didn't find a way how to disable MCM directly over helm nor docker during rancher installation - Also I didn't find the two radio buttons in initial wizard like it was before in Ember UI on 2.5.8 (radio-buttons for: `I want to create or manage multiple clusters` & `I'm only going to use the cluster Rancher was installed on` - not sure if it's the same as MCM)
* when `legacy` flag is turned on then `LEGACY APPS/Cluster Manager+` is visible in menu - also I don't see v1 `(legacy)` apps in `Cluster Tools` (monitoring and logging) on local cluster.

**Upgrade:**
* I deployed 2.5.8 from helm -> performed `helm upgrade` to `rancher:master-head 51d074b` and the legacy flag was set `on` after upgrade
(I tried in 2.5.8 to set `I'm only going to use the cluster Rancher was installed on` in wizard but it has no impact for 2.6 and MCM flag )
* the flag can be turn off/on in upgraded cluster and the proper UIs are available then

**Comment by thehejik** [comment]
* custom URL w `/g` + `/login` are expected to work even when `legacy` flag is turned off (confirmed by Vincent - otherwise iframes wouldn't work)
* I just opened #33329 (MCM flag is present and Active) with note about a missing way for disabling MCM
* The rest is ok.

Closing.
