### ISSUE TITLE
GKE v1/v2: Backport to 2.4.16 - privateClusterConfig defaults

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#33276]
Per https://github.com/rancher/rancher/issues/33241, Google is rolling out changes to how cluster provisioning to GKE works whereby the default settings we have for private clusters do not work on all regions.

The UI would show a message like:
```Cluster provisioning fails with Googleapi: Error 400: Private cluster config can only be set on private clusters., badRequest```

The UI sends the following privateClusterConfig:
```privateClusterConfig: {
enablePrivateEndpoint: false
enablePrivateNodes: false
masterIpv4CidrBlock: null
type: "/v3/schemas/gkePrivateClusterConfig"
}```

The current plan is to have a workaround where we detect whether the region supports private cluster configs or not and then change our defaults. It should be in `master` so we need to backport this fix.

**Comment by prabalsharma** [comment]
I am still seeing the issue on v2.4-5850-head

`Googleapi: Error 400: Private cluster config can only be set on private clusters., badRequest`

I tried us-central1-f zonal cluster and all US regional clusters.

**Comment by prabalsharma** [comment]
was able to create US regional clusters: east1, east4, west2, west1
zonal cluster: us-central1-f

I am getting error from GCP for us-central1 region:
`Googleapi: Error 500: Internal error encountered., backendError`

This is coming from GCP, so not much can be done.
