### ISSUE TITLE
GKE v1/v2: Backport to 2.5.9 - privateClusterConfig defaults

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#33277]
Per https://github.com/rancher/rancher/issues/33241, Google is rolling out changes to how cluster provisioning to GKE works whereby the default settings we have for private clusters do not work on all regions.

The UI would show a message like:
```Cluster provisioning fails with Googleapi: Error 400: Private cluster config can only be set on private clusters., badRequest```

The UI sends the following privateClusterConfig:
```privateClusterConfig: {
enablePrivateEndpoint: false
enablePrivateNodes: false
masterIpv4CidrBlock: null
type: "/v3/schemas/gkePrivateClusterConfig"
}```

The current plan is to have a workaround where we detect whether the region supports private cluster configs or not and then change our defaults. It should be in `master` so we need to backport this fix.

**Comment by cbron** [comment]
moved back to review to get into 2.5.9

**Comment by prabalsharma** [comment]
tested on 2.5.9-rc7, still seeing the error
`Googleapi: Error 400: Private cluster config can only be set on private clusters., badRequest`

**Comment by prabalsharma** [comment]
RC is using rancher/gke-operator:v1.0.1 instead of v1.1.1-rc5

**Comment by cbron** [comment]
Also needs: https://github.com/rancher/rancher/pull/33522

**Comment by prabalsharma** [comment]
on 2.5.9-rc9, was able to create us regional (useast1, useast4, uswest1, uswest2, central1) clusters with default values. Also deployed 1 zonal cluster (us-central1-c)
