### ISSUE TITLE
Unable to assign secret as Environment Variable to a workload/pod from Ember

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#33279]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* deploy any local cluster with `rancher:master-head abeea84`
* provision a singlenode RKE1 cluster from ember by using k8s `v1.20.7-rancher1-1` or `v1.21.1-rancher2-1`
* define a key-value secret in Ember UI for the downstream cluster in default ns
* try to define a workload in default ns by using the secret via `Environment Variable` section and `Inject Values From Another Resource` option and click on `+Add from Source`, choose `Type: Secret` from dropdown and select the secret you created before

**Result:**
*  After pressing `Launch` (for Workload) button Ember UI won't create the resource due Error visible in Ember UI:
```
Validation failed in API: field `environmentFrom` is deprecated, please use Kubernetes native fields `env` and `valueFrom` for the container's environment variables
```

![secret_as_env](https://user-images.githubusercontent.com/12828077/122594172-f4f6f900-d066-11eb-8784-2af86ff02d29.png)

**Other info**
* Mounting secrets to a workload as a volume is working fine

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher:master-head abeea84`
- Installation option (single install/HA): any 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): any
- Machine type (cloud/VM/metal) and specifications (CPU/memory): any
- Kubernetes version (use `kubectl version`): `v1.20.7-rancher1-1` and `v1.21.1-rancher2-1` (maybe others?)

**Comment by vincent99** [comment]
This is intentional, the API has to be a breaking change to avoid silently correcting data.  This interface will either be removed or inaccessible in the final packaging of the 2.6 UIs, use the Vue workload screens.  (Frankly they could use a lot more testing, especially the less common options)

**Comment by sowmyav27** [comment]
Expected because of this change - https://github.com/rancher/rancher/issues/16148
