### ISSUE TITLE
RoleTemplates allowed to be created with no verbs

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#33278]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Navigate to the cluster manager UI
2. Go to `Security > Roles > Projects`
3. `Add Project Role`
4. Make sure the Role includes at least one Resource Grant, **with no verbs selected**  
5. Create the Role

**Result:**
Note that any users bound to this role do not receive the proper permissions. Look in the logs and see entries like this:
```
2021/06/17 14:46:00 [ERROR] error syncing 'p-sh6v2/prtb-bpzbq': handler cluster-prtb-sync: couldn't ensure roles: couldn't create clusterRole rt-6bwsg: ClusterRole.rbac.authorization.k8s.io "rt-6bwsg" is invalid: rules[0].verbs: Required value: verbs must contain at least one value, requeuing
```

**Expected Result:**
We disallow RoleTemplates from being created if they have malformed PolicyRules, i.e. ones that include no verbs

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8
- Installation option (single install/HA): Both

gz#17458

**Comment by ryansann** [comment]
For testing, the expected result for creating a RoleTemplate with no verbs, is this: 
<img width="1392" alt="Screen Shot 2021-06-18 at 3 42 40 PM" src="https://user-images.githubusercontent.com/8824599/122621942-eea75380-d04b-11eb-8dab-0819542c686c.png">

**Comment by ryansann** [comment]
This won't get tested yet as these changes were made to `rancher/webhook:master` and we haven't released from that branch yet

**Comment by anupama2501** [comment]
Changing the status to re-opened based on the above comment of @ryansann. Will move it back `to-test` once the chart version is released from rancher/webhook:master.

**Comment by ryansann** [comment]
There is a new rancher-webhook chart on `rancher/charts:dev-v2.6` that can be used to test this. The new webhook chart is: `rancher-webhook-1.0.0+up0.2.0-alpha03`

**Comment by anupama2501** [comment]
Verified on master-head b6bcfad

1. From ember UI --> security --> roles, create a global role with no verbs and `auth configs` as a resource - Request fails with the error `admission webhook "rancherauth.cattle.io" denied the request: RoleTemplate.Rules: PolicyRules must have at least one verb`
2. Repeated the same steps for cluster role and project role - verified the request fails with the same error as above
3. Verified via API by creating a global, cluster and project role - Failed with the response
```
"baseType": "error",
"code": "BadRequest",
"message": "admission webhook \"rancherauth.cattle.io\" denied the request: RoleTemplate.Rules: PolicyRules must have at least one verb"
```
