### ISSUE TITLE
[cli] Unable to import rke config when creating cluster

### ISSUE THREAD

**Issue by jgallucci32** [rancher/rancher#33270]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create rke configuration file
```
cat << EOF > cluster-template.yml
rancher_kubernetes_engine_config:
  addon_job_timeout: 50
EOF
```
Create cluster using rke config file
```
rancher cluster create --rke-config cluster-template.yml testcluster
```
Export configuration settings to verify if `addon_job_timeout` uses a custom value
```
rancher cluster export testcluster | grep addon
```

**Result:**
The cluster is created with default values. Ignores settings in rke config file
```
$ rancher cluster export testcluser | grep addon
      addonJobTimeout: 45
```

**Expected Result:**
The cluster is created with settings from the rke config file.

**Other details that may be helpful:**
cli version v2.4.11

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): single

**Comment by capta1nk1rk** [comment]
Because you are provisioning the cluster from the Rancher-CLI, the `rancher_kubernetes_engine_config` isn't necessary.  The Rancher-CLI tool will be expecting a "pure" RKE config file, without the additional nesting.

Doing something like below should achieve what you want:

```
cat << EOF > cluster-template.yml
addon_job_timeout: 50
EOF
```

**Comment by jgallucci32** [comment]
Thanks @capta1nk1rk that did the trick. The cluster now recognizes the modified settings.

I think your note would be beneficial in the docs here
https://www.rancher.co.jp/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/

Or possibly here as well
https://rancher.com/docs/rancher/v2.x/en/cli/
