### ISSUE TITLE
quorum not set for services when service is created with  "Re-create, only when atleast <n> containers are healthy"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3328]
Server version - v0.55.0-rc3

Steps to reproduce the problem:

Create a service with scale 5 health check enabled and health check strategy set to "recreateOnQuorum" by choosing "Re-create, only when atleast "3" containers are healthy.

Activate service.

Service is stuck in "Activating" state forever:

API request sent from from UI does not have quorum:
```
healthCheck: {strategy: "recreateOnQuorum", interval: 2000, responseTimeout: 2000, healthyThreshold: 2,…}
healthyThreshold: 2
initializingTimeout: null
interval: 2000
name: null
port: 80
recreateOnQuorumStrategyConfig: {quorum: null}
reinitializingTimeout: null
requestLine: "GET /name.html HTTP/1.0"
responseTimeout: 2000
strategy: "recreateOnQuorum"
unhealthyThreshold: 3
```

When service is created , quorum is saved as "null"

```
"healthCheck": {
"strategy": "recreateOnQuorum",
"interval": 2000,
"responseTimeout": 2000,
"healthyThreshold": 2,
"unhealthyThreshold": 3,
"requestLine": "GET /name.html HTTP/1.0",
"port": 80,
"recreateOnQuorumStrategyConfig": {
"quorum": null,
},
"initializingTimeout": null,
"name": null,
"reinitializingTimeout": null,
},
```

**Comment by vincent99** [comment]
The max depth on serializing recursion was set to 5, and service-> launchConfig->healthCheck->recreateOnQuorumStrategyConfig->quorum is 5.. increased to 10.

**Comment by tfiduccia** [comment]
version - master ui 1/22
Checked API and quorum is being set
Verified fixed
