### ISSUE TITLE
Backport: RoleTemplates allowed to be created with no verbs

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#33286]
Backport of: 
- rancher/rancher#33278

**Comment by ryansann** [comment]
We released `rancher/rancher-webhook:0.1.100-rc2+up0.1.1-rc2`

@anupama2501 we'll need this RC tested

Here's how this can be tested:
- Ensure the Rancher charts repository is pointed to branch `dev-v2.5` and version `0.1.100-rc2+up0.1.1-rc2` of the `rancher-webhook` app is running
- Try to create a Role that has a PolicyRule which includes no verbs, e.g. 
<img width="1410" alt="Screen Shot 2021-06-22 at 10 16 27 AM" src="https://user-images.githubusercontent.com/8824599/122970569-efd5ca80-d342-11eb-9a15-63533504a9f0.png">

Users should not be able to create RoleTemplates that have rules with no verbs, so the validation error seen above should be presented when a user tries to perform this disallowed action. This should hold true across Global, Cluster, and Project Roles (In Cluster Manager UI). Any tests can also be performed directly through the kubernetes api as well.

**Comment by anupama2501** [comment]
**Reproduced on v2.5.8:**
1. Create a custom role from security --> roles --> cluster  by providing the resource as `API resource` and no verbs.
2. Add a standard user- user1
3. Create a downstream rke1 node driver EC2 cluster with 1 etcd, 1 cp, 1 worker nodes.
4. Add the user1 in this cluster with the cluster role created in step1.
5. Verify the rancher logs and see the following error:
`2021/06/23 20:45:17 [ERROR] error syncing 'rt-n5njg': handler cluster-roletemplate-sync: couldn't ensure roles: couldn't create clusterRole rt-n5njg: ClusterRole.rbac.authorization.k8s.io "rt-n5njg" is invalid: rules[0].verbs: Required value: verbs must contain at least one value, requeuing`

**Verified the following scenarios:**
#### Rancher version v2.5.9-rc3 fresh install:
1. from the dashboard --> apps & marketplace --> repositories --> Rancher charts to point to dev-v2.5
2. Upgrade the rancher webhook version to the `rancher-webhook:0.1.100-rc2+up0.1.1-rc2`
3. From ember UI --> security --> roles, created a custom global role with no verbs and an API resource
4. It immediately errors out with the message `admission webhook "rancherauth.cattle.io" denied the request: GlobalRole.Rules: PolicyRules must have at least one verb`
5. Verified that it errors out for cluster, project role creation.

#### Upgrade scenario:
1. Create a rancher server on v2.5.8
2. Create custom cluster, global roles from security --> roles
3. Associate global role to user1.
4.  Upgrade rancher server to v2.5.9-rc3.
5. from the dashboard --> apps & marketplace --> repositories --> Rancher charts to point to dev-v2.5
6. Upgrade the rancher webhook version to the `rancher-webhook:0.1.100-rc2+up0.1.1-rc2`
7. Create a custom global role and in the inherit from option select the global role created in step4.
8. Verified upon saving the user is displayed with an error `admission webhook "rancherauth.cattle.io" denied the request: GlobalRole.Rules: PolicyRules must have at least one verb`
9. Verified the inherit from option for the cluster role errors out with a similar error message.

#### Rancher Version v2.5.9-rc3 fresh install create roles using API:
1. Using the https://ip/v3/roleTemplates/ create a role template for cluster role by addin the rules with {}
2. The request fails with the error ```{
"baseType": "error",
"code": "BadRequest",
"message": "admission webhook \"rancherauth.cattle.io\" denied the request: RoleTemplate.Rules: PolicyRules must have at least one verb",```
3. Verified that the error is displayed for global roles as well.

**Comment by anupama2501** [comment]
Re-opening this ticket as the following issue is seen:
On rancher server v2.5.8:

1. Create a custom role from security --> roles --> cluster by providing the resource as API resource and no verbs.
2. Add a standard user- user1
3. Create a global custom role and associate user1 to the role.
4. Create a downstream rke1 node driver EC2 cluster with 1 etcd, 1 cp, 1 worker nodes.
5. Add the user1 in this cluster with the cluster role created in step1.
6. Upgrade the rancher server to the version v2.5.9-rc3 
7. from the dashboard --> apps & marketplace --> repositories --> Rancher charts to point to dev-v2.5
8. Upgrade the rancher webhook version to the rancher-webhook:0.1.100-rc2+up0.1.1-rc2
9. Remove the previously created cluster role and global role from step1 and step3 respectively.
10. The response status is seen successful when the roles are deleted:
```
Request URL: https://ip/v3/roleTemplates/rt-n5njg
Request Method: DELETE
Status Code: 200 OK
```
10. But the roles are not removed from global and cluster roles and the following errors are seen in the rancher server which go into a loop continuously:
```


2021/06/23 22:11:03 [ERROR] error syncing 'gr-pshvs': handler mgmt-auth-gr-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-gr-controller, requeuing
2021/06/23 22:11:33 [ERROR] error syncing 'c-qgw42/crtb-zltsp': handler cluster-crtb-sync: couldn't get role template rt-n5njg: roletemplates.management.cattle.io "rt-n5njg" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "rt-n5njg" not found, requeuing
W0623 22:12:10.447182      26 dispatcher.go:142] rejected by webhook "rancherauth.cattle.io": &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"admission webhook \"rancherauth.cattle.io\" denied the request: RoleTemplate.Rules: PolicyRules must have at least one verb", Reason:"BadRequest", Details:(*v1.StatusDetails)(nil), Code:400}}
W0623 22:12:10.464858      26 dispatcher.go:142] rejected by webhook "rancherauth.cattle.io": &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"admission webhook \"rancherauth.cattle.io\" denied the request: RoleTemplate.Rules: PolicyRules must have at least one verb", Reason:"BadRequest", Details:(*v1.StatusDetails)(nil), Code:400}}
```




Screenshot of the roles that were seen even after deleting from the Global and cluster roles on rancher:
<img width="500" alt="Screen Shot 2021-06-23 at 3 17 29 PM" src="https://user-images.githubusercontent.com/38144301/123175163-25a7ab80-d436-11eb-986f-d4ac0d73a05d.png">

**Comment by ryansann** [comment]
@anupama2501 and I have discussed the issue she is seeing. This is being caused by pre-delete update operations that remove finalizers from RoleTemplates / GlobalRoles. We will require a small change in the webhook to check deletion timestamps on resources. If there is a deletion timestamp on a RoleTemplate / GlobalRole, we will admit updates. This should fix the issue.

**Comment by anupama2501** [comment]
On v2.5.8

1. Create a custom role from security --> roles --> cluster by providing the resource as API resource and no verbs.
2. Add a standard user- user1
3. Create a global custom role and associate user1 to the role - g1
4. Create a downstream rke1 node driver EC2 cluster with 1 etcd, 1 cp, 1 worker nodes.
5. Add the user1 in this cluster with the cluster role created in step1.
6. Change the repository of rancher pointing to dev-v2.5 from explorer --> Apps & market place --> Chart repositories --> Rancher.
6. Upgrade the rancher-webhook app in the local cluster  to the version 
7. Delete the previously created role g1. 
8. The role is deleted from global --> security --> Roles but the following error logs are seen in the rancher server logs:
```
garbagecollector.go:309] error syncing item &garbagecollector.node{identity:garbagecollector.objectReference{OwnerReference:v1.OwnerReference{APIVersion:"management.cattle.io/v3", Kind:"GlobalRoleBinding", Name:"grb-bnhx4", UID:"41fa1d8e-e2dc-4411-ac1d-8925455e0767", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}, Namespace:""}, dependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:1, readerWait:0}, dependents:map[*garbagecollector.node]struct {}{(*garbagecollector.node)(0xc02cac2000):struct {}{}}, deletingDependents:false, deletingDependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, beingDeleted:false, beingDeletedLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, virtual:false, virtualLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, owners:[]v1.OwnerReference{v1.OwnerReference{APIVersion:"management.cattle.io/v3", Kind:"GlobalRole", Name:"gr-zb2cp", UID:"24855074-2d50-4070-989c-f7c6df8276aa", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}}}: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": EOF
```


- Followed the same steps for creating custom cluster roles -c1
- While adding the user to the cluster as cluster member, add the above role created to the user.
- Upon upgrade, if we delete the c1 from Global --> security --> roles, we see the following error when the cluster roles are removed:

```
2021/06/28 18:42:05 [ERROR] error syncing 'c-v9j8j/crtb-rgvxq': handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "rt-zn8lt" not found, handler cluster-crtb-sync: couldn't get role template rt-zn8lt: roletemplates.management.cattle.io "rt-zn8lt" not found, requeuing
```

**Comment by ryansann** [comment]
@anupama2501 in regards to the second of the two error messages, this behavior is expected currently and not related to webhook. On RoleTemplate deletion, we aren't currently deleting bindings associated to the RoleTemplate, so those bindings (crtbs, prtbs) will experience these not found errors at the controller level. This is similar to k8s RBAC where deleting roles does not cause associated bindings to be deleted. 

Continuing to look at the first error, if that is intermittent then we should be good to proceed with the webhook release.

**Comment by anupama2501** [comment]
@ryansann `Issue1` happens only on v2.5.8. 
Can be reproduced only with following steps on v2.5.8 and v2.5.9-rc3. 
rancher webhook before upgrade: v0.1.000

1. From global --> security --> users --> created user1 
2. From global --> security --> roles --> create global role with `Resource` `authconfigs` and no verbs
3. From explorer --> apps and market, change the rancher repo to point to dev-v2.5
4. Upgrade rancher webhook to `rancher/rancher-webhook:v0.1.1-rc3`
5. Delete the roles from Global --> roles and see the following error in the rancher server logs:
```
021/06/29 19:18:46 [ERROR] error syncing 'gr-cckmw': handler mgmt-auth-gr-controller: ClusterRole.rbac.authorization.k8s.io "cattle-globalrole-gr-cckmw" is invalid: rules[0].verbs: Required value: verbs must contain at least one value, requeuing
W0629 19:18:47.508864       7 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021-06-29 19:19:33.383436 I | mvcc: store.index: compact 6547
2021-06-29 19:19:33.423346 I | mvcc: finished scheduled compaction at 6547 (took 38.465388ms)
W0629 19:20:20.063916      24 dispatcher.go:134] Failed calling webhook, failing closed rancherauth.cattle.io: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": EOF
W0629 19:20:20.068825      24 dispatcher.go:134] Failed calling webhook, failing closed rancherauth.cattle.io: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": EOF
E0629 19:20:20.069628      24 garbagecollector.go:309] error syncing item &garbagecollector.node{identity:garbagecollector.objectReference{OwnerReference:v1.OwnerReference{APIVersion:"management.cattle.io/v3", Kind:"GlobalRoleBinding", Name:"grb-bq4g4", UID:"1163aa9b-6cef-4ba0-b0ba-966b702ed326", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}, Namespace:""}, dependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:1, readerWait:0}, dependents:map[*garbagecollector.node]struct {}{(*garbagecollector.node)(0xc0201c25a0):struct {}{}}, deletingDependents:false, deletingDependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, beingDeleted:false, beingDeletedLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, virtual:false, virtualLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, owners:[]v1.OwnerReference{v1.OwnerReference{APIVersion:"management.cattle.io/v3", Kind:"GlobalRole", Name:"gr-cckmw", UID:"c6ed6158-104b-4c23-8da4-627dfd43ddf5", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}}}: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": EOF
```

**Comment by ryansann** [comment]
This garbagecollector issue also happens in @anupama2501's setup with earlier versions of webhook, so this is not something introduced as part of the changes for RoleTemplate/GlobalRole validation. Thus the investigation / fix is outside the scope of this issue.

**Comment by anupama2501** [comment]
Closing this issue as have created separate issues for the above in 2.5.10 #33429 and 2.6 https://github.com/rancher/rancher/issues/33430
