### ISSUE TITLE
Logging v1 - log-aggregator pods fail to come up active on RHEL 8.4 selinux enabled cluster

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#33281]
**What kind of request is this:**
bug

**Steps to reproduce:**

- RHEL 8.4  SELinux enabled downstream cluster
- Enable logging v1

**Result:**

- Log aggregator pods fail to come up active

```
Starting log-aggregator
driver_dir is cattle.io~log-aggregator
mkdir: cannot create directory '/flexmnt/cattle.io~log-aggregator': Permission denied
```

**Expected Result:**

- Log aggregator pods to come up active and collecting cluster logs

**Other details that may be helpful:**

- `OS: RHEL 8.4 4.18.0-305.el8.x86_64`
- `Docker Version: 20.10.7`
- `Kubelet Version: v1.20.7`

**Environment information**
- Rancher version: `2.6 master-head (06/18/2021)` _3dae3e2_
- Installation option: Single Docker

**Comment by cbron** [comment]
Bumping selinux+v1 from 2.6

**Comment by izaac** [comment]
Logging V1 is no longer supported
