### ISSUE TITLE
old fleet agent is deleted before the new fleet agent workload comes up in cattle-fleet-system namespace in a rancher upgraded setup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33296]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On 2.5.8, deploy a downstream cluster - DO RKE - 2 nodes
- Upgrade rancher to master-head commit id: `a11f947`
- On the local cluster, The new namespace `cattle-fleet-agent` - fleet-controller and gitjob workload get created.
- On the local cluster, the fleet-agent workload - 0.3.5 gets deleted
- The new fleet-agent is not deployed.

**Expected Result:**
The new fleet-agent should be deployed before the previous one gets deleted

**Other details that may be helpful:**
The new fleet-agent is deployed after 15 minutes on the local cluster

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `a11f9476`
- Installation option (single install/HA): Single

**Comment by nickgerace** [comment]
This is no longer seen on `master-head`. Likely was an issue related to https://github.com/rancher/fleet/issues/437 due to the errors on agent `Update` API calls not being handled.

**Comment by nickgerace** [comment]
Note: this issue is separate from https://github.com/rancher/rancher/issues/33293

**Comment by sowmyav27** [comment]
**On upgrade from 2.5.9 to master-head commit id: `44bb5b4`**

- On 2.5.9, deploy a downstream cluster - DO RKE - 2 nodes
- Upgrade rancher to master-head commit id: 44bb5b4
- On the local cluster, The new namespace cattle-fleet-agent - fleet-agent, fleet-controller and gitjob workloads get created.

<img width="1261" alt="Screen Shot 2021-07-15 at 8 57 12 AM" src="https://user-images.githubusercontent.com/26032343/125819102-7d27f859-1868-47f0-a2ab-299664e4eb0f.png">
