### ISSUE TITLE
CIS v2 scan fails to run on an SElinux enabled cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33290]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On an SElinux enabled cluster, on docker daemon and on OS level for RHEL 8.4
- Enable CIS charts, deploy
- Run COS 1.6 RKE permissive scan
- Scan is seen stuck in Active state, with no results
- Cis-operator logs:
```
Fri, Jun 18 2021 5:00:03 pm | time="2021-06-19T00:00:03Z" level=info msg="Starting CIS-Operator"
Fri, Jun 18 2021 5:00:03 pm | time="2021-06-19T00:00:03Z" level=info msg="ClusterProvider detected rke"
Fri, Jun 18 2021 5:00:03 pm | time="2021-06-19T00:00:03Z" level=info msg="KubernetesVersion detected v1.20.7"
Fri, Jun 18 2021 5:00:03 pm | time="2021-06-19T00:00:03Z" level=info msg="Starting cis.cattle.io/v1, Kind=ClusterScan controller"
Fri, Jun 18 2021 5:00:03 pm | time="2021-06-19T00:00:03Z" level=info msg="Starting /v1, Kind=Service controller"
Fri, Jun 18 2021 5:00:03 pm | time="2021-06-19T00:00:03Z" level=info msg="Starting /v1, Kind=Pod controller"
Fri, Jun 18 2021 5:00:03 pm | time="2021-06-19T00:00:03Z" level=info msg="Starting /v1, Kind=ConfigMap controller"
Fri, Jun 18 2021 5:00:03 pm | time="2021-06-19T00:00:03Z" level=info msg="Starting batch/v1, Kind=Job controller"
Fri, Jun 18 2021 5:00:23 pm | time="2021-06-19T00:00:23Z" level=error msg="error syncing 'scan-9jp5n': handler cis-operator: clusterscans.cis.cattle.io \"scan-9jp5n\" not found, requeuing"
Fri, Jun 18 2021 5:00:23 pm | time="2021-06-19T00:00:23Z" level=error msg="error syncing 'scan-9jp5n': handler cis-operator: clusterscans.cis.cattle.io \"scan-9jp5n\" not found, requeuing"
Fri, Jun 18 2021 5:00:23 pm | time="2021-06-19T00:00:23Z" level=error msg="error syncing 'scan-9jp5n': handler cis-operator: clusterscans.cis.cattle.io \"scan-9jp5n\" not found, requeuing"
Fri, Jun 18 2021 5:00:23 pm | time="2021-06-19T00:00:23Z" level=error msg="error syncing 'scan-9jp5n': handler cis-operator: clusterscans.cis.cattle.io \"scan-9jp5n\" not found, requeuing"
Fri, Jun 18 2021 5:00:24 pm | time="2021-06-19T00:00:24Z" level=error msg="error syncing 'scan-9jp5n': handler cis-operator: clusterscans.cis.cattle.io \"scan-9jp5n\" not found, requeuing"
Fri, Jun 18 2021 5:00:25 pm | time="2021-06-19T00:00:25Z" level=error msg="error syncing 'scan-9jp5n': handler cis-operator: clusterscans.cis.cattle.io \"scan-9jp5n\" not found, requeuing"
Fri, Jun 18 2021 5:00:30 pm | time="2021-06-19T00:00:30Z" level=error msg="error syncing 'scan-9jp5n': handler cis-operator: clusterscans.cis.cattle.io \"scan-9jp5n\" not found, requeuing"
Fri, Jun 18 2021 5:00:50 pm | time="2021-06-19T00:00:50Z" level=error msg="error syncing 'scan-9jp5n': handler cis-operator: clusterscans.cis.cattle.io \"scan-9jp5n\" not found, requeuing"
Fri, Jun 18 2021 5:02:12 pm | time="2021-06-19T00:02:12Z" level=error msg="error syncing 'scan-9jp5n': handler cis-operator: clusterscans.cis.cattle.io \"scan-9jp5n\" not found, requeuing"

```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `2ca2ad9`
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE AWS - RHEL 8.4 ami Selinux enabled
- Kubernetes version (use `kubectl version`):

```
1.20
```

**Comment by sowmyav27** [comment]
Same issue is seen for an RKE1 cluster with ubuntu OS - https://github.com/rancher/cis-operator/issues/98

**Comment by doflamingo721** [comment]
**This issue is not active on rancher 2.6.3.**

Steps followed:
1. Rancher Server version: 2.6.3
2. Create a downstream multi-node (`1etcd, 1cp, 3 worker`) custom cluster using RHEL 8.4 with SElinux enabled.
3. Run `systemctl disable nm-cloud-setup.service nm-cloud-setup.timer` on the RHEL host before adding it to the cluster per https://github.com/rancher/rke2/issues/1053#issuecomment-848061376
4. Install CIS-Benchmark from Apps and marketplace.
5. Run the `rke-profile-permissive-1.6` scan

Result:
The scan passes without any failures.

**Comment by vivek-infracloud** [comment]
**Validated the issue on rancher v2.6.3. Issue is not active on rancher v2.6.3**

Steps followed:

1. Created Rancher server v2.6.3
2. Created a downstream multinode (1cp, 1etcd, 3 worker) custom cluster using RHEL 8.4 with SElinux enabled.
3. Ran `systemctl disable nm-cloud-setup.service nm-cloud-setup.timer` on the RHEL host before adding it to the cluster.
4. Installed CIS-Benchmark from Apps and Marketplace
5. Ran the rke-profile-permissive-1.6 scan.

Result:
The scan passed without any failure.

**Comment by vivek-infracloud** [comment]
Closing the issue, since it is not active based on above validation.
