### ISSUE TITLE
Fleet-agent pod gets deployed and removed on an upgraded rancher setup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33293]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On 2.5.8 deploy a downstream cluster
- The fleet-agent is deployed in cattle-system namespace
- On an upgrade from 2.5.8 to master-head `def25f1`

**Result:**
- When new fleet agent is deployed,  2 pods get deployed in the fleet-agent workload in new cattle-fleet-system namespace, and then one get removed.

**Expected Result:**
Only one pod should be deployed in the workload. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head `def25f1`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE1 DO
- Kubernetes version (use `kubectl version`):

```
Any
```

**Comment by nickgerace** [comment]
This issue is still seen on `master-head`, but is cosmetic

**Comment by superseb** [comment]
On the cluster, a Deployment with 2 ReplicaSets can be found for `fleet-agent`, the diff between these is:

```
                                 "name": "GENERATION",                                                                                                                                                                                                                                                                        
-                                "value": "c4972ddc-6d94-4531-a95e-08ba14e0f3b6-2"                                                                             
+                                "value": "bundle"
```

This seems to be coming from the controller deploying the Chart with a GENERATION value based on clusterUID + cluster generation on cluster import (see https://github.com/rancher/fleet/blob/v0.3.6-rc5/pkg/controllers/cluster/import.go#L216) and then when fleet-agent is running, the manageagent controller redeploys the agent with a GENERATION value of `bundle` (see https://github.com/rancher/fleet/blob/v0.3.6-rc5/pkg/controllers/manageagent/manageagent.go#L98).

This can also be reproduced by running single install Docker:

```
docker run -d --privileged -p 80:80 -p 443:443 rancher/rancher:master-head
docker exec -ti $CONTAINER_ID bash
while ! kubectl rollout status -w -n cattle-fleet-system deploy/fleet-agent; do     sleep 2; done
for rs in $(kubectl -n cattle-fleet-system get rs --no-headers -o custom-columns=NAME:.metadata.name); do kubectl -n cattle-fleet-system get rs $rs -o json | grep -A1 \"GENERATION\"; done
                                "name": "GENERATION",
                                "value": "e129ac4c-48b1-4ba5-a22d-dd1e87bdadf2-2"
                                "name": "GENERATION",
                                "value": "bundle"
```
