### ISSUE TITLE
Rerunning rancher/agent command on a host caused a "ghost" host to appear in UI

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3329]
Reported by dsantos_ in IRC.
1. rebuilt rancher-server with new IP but same database
2. hosts went to reconnecting
3. reran docker run rancher/agent command on host
4. host went to active in UI but another host appeared that is stuck in "almost there waiting for agent connection" phase

http://i.imgur.com/C3Oz0wr.png

**Comment by cjellick** [comment]
Reproduced. Just had to run `docker run rancher/agent...` on an otherwise healthy host.

**Comment by cjellick** [comment]
Cause: when provisioning a machine through go-machine-service (ie through the UI), we set the following environment variable on the rancher-agent container: `CATTLE_PHYSICAL_HOST_UUID=<machine.ExternalId>`.

When you manually rerun the `docker run rancher/agent ...` command manually, this environment variable is lost and rancher/agent doesn't report itself correctly.

**Comment by cjellick** [comment]
Fix and work around is to add `-e CATTLE_PHYSICAL_HOST_UUID=<machine.ExternalId>` to the docker run command. You would have to get the external ID of the machine from the API.

**Comment by Beanow** [comment]
I'm running into a similar issue when stopping and starting a `docker-machine` instance that runs the `rancher/server` and a `rancher/agent`. I'll test if this workaround fixes that.

**Comment by Beanow** [comment]
Tested, definitely not the same issue.

**Comment by cjellick** [comment]
What type of machine @Beanow? boot2docker based machines (virtualbox, vmware, some others) have an in-memory file system (outside of /var/lib/docker) and so restarting such a vm wipes out the state in the /var/lib/rancher directory that we require to recognize hosts upon restart.

**Comment by vincent99** [comment]
#4900 fixes the boot2docker persistence issue

**Comment by cjellick** [comment]
A legit bug, but doesn't seem critical to 1.2.0. Can we move out?

**Comment by deniseschannon** [comment]
This should be addressed and no longer happening as of v1.2.0. If it occurs, please reopen.
