### ISSUE TITLE
If I use my keyboard to highlight Cancel and hit enter in Overlays, it still clicks OK

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#333]
Steps:
Go to any Overlay
Tab to the Cancel button
Hit your enter/return key

Results:
It selects OK

Expected:
Should select Cancel

**Comment by deniseschannon** [comment]
No longer relevant. Overlays replaced with pages.

**Comment by vincent99** [comment]
There are still some overlays for edit, and other things...

**Comment by vincent99** [comment]
Now it's no longer relevant, the overlay library has changed.

**Comment by deniseschannon** [comment]
v0.27.0-rc4 - Verified Fixed
