### ISSUE TITLE
Adding label to EKS managed node group results in continual error

### ISSUE THREAD

**Issue by domhdp** [rancher/rancher#33302]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create an EKS cluster (v 1.20)
2. Add a Rancher managed node group without labels
3. Once the nodes have been provisioned, edit the node group via the UI and add a Label (last field in the Node group section)

**Result:**
The node group does not get updated, and an error message continually appears until the node group is edited and the label/s removed.
```
This cluster is currently Updating.
InvalidParameterException: Either all or at least one of minSize, maxSize, desiredSize must be provided { RespMetadata: { StatusCode: 400, RequestID: "f36e1af1-1eb6-49ef-8c30-aba64228593e" }, Message_: "Either all or at least one of minSize, maxSize, desiredSize must be provided" }
```

**Expected Result:**
The node group should be updated with the each node having the new label.

**Other details that may be helpful:**
The cluster and node group were provisioned via the terraform provider.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8
- Installation option (single install/HA): HA (on EKS cluster)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider (AWS EKS)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud, m5.large
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Not sure how to run this. I am using standard setup with node group version v1.20.4-eks-6b7464.
```

**Comment by aaronRancher** [comment]
This issue is reproduced on Rancher `v2.5.8` with the following steps:
From Ember UI, provision a hosted EKS cluster.
After cluster is available, edit the cluster from UI and add a label to the node group.
Save.

Result: 
Cluster is stuck in updating state.
```
InvalidParameterException: Either all or at least one of minSize, maxSize, desiredSize must be provided { RespMetadata: { StatusCode: 400, RequestID: "90f26d9b-fcb4-400b-9e3d-480b9df5a1c0" }, Message_: "Either all or at least one of minSize, maxSize, desiredSize must be provided" }
```

The UI sends `minSize`, `maxSize`, `desiredSize` in the EKS config on cluster edit:
```
desiredSize: 2
diskSize: 20
ec2SshKey: ""
gpu: false
imageId: ""
instanceType: "t3.medium"
labels: {testlabel: "testvalue"}
label3: "val3"
testlabel2: "testvalue2"
launchTemplate: null
maxSize: 2
minSize: 2
```

This is also reproduced through the API with the following steps:
From Ember UI, provision a hosted EKS cluster.
After cluster is available, view the cluster in API.
Edit the cluster in API. Add the following to EKS config label field: `labels: {"labeltest": "valtest"}`
Send request. The cluster will error with the same message as above.

**Comment by rmweir** [comment]
@sowmyav27 nodegroups tag, nodegroup labels, nodegroup resourceTags, and cluster tags should all be tested. Particularly the scenarios where these fields are having a key removed and adding/updating keys are important.

**Comment by aaronRancher** [comment]
Will test the following scenarios.

Prerequisite: Provision a default EKS cluster. EKS Operator version `v1.1.1-rc6` or above.
For the following: nodegroups tag, nodegroup labels, nodegroup resourceTags, and cluster tags
- Edit the cluster. Add a key (key1). Save the cluster. Validate cluster updates and becomes available.
- Edit the cluster. Add a key (key2). Save the cluster. Validate cluster updates and becomes available.
- Edit the cluster. Edit a key (key1 > key1edit). Save the cluster. Validate cluster updates and becomes available.
- Edit the cluster. Delete a key (key1edit). Save the cluster. Validate cluster updates and becomes available.

**Comment by all4innov** [comment]
With EKS version 1.20, there is also an error when updating Cluster Labels

Steps to reproduce:
1) Create an EKS cluster (v 1.20)
2) Import the created EKS cluster
3) update the cluster by adding a new label

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 8073489` with the above scenarios.
EKS operator version: `eks-operator:v1.1.1-rc7`

User is able to add, delete, and edit the following resources: 
- nodegroups tag
- nodegroup labels
- nodegroup resourceTags
- cluster tags

Nodegroup resourceTags can only be edited using rancher managed launch template. When resourceTags are added, edited, or deleted, a new launch template version will be created.
