### ISSUE TITLE
Rancher 2.6 documentation

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#33304]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Expected Result:**

**Other details that may be helpful:**
Is there currently any documentation (how ever beta) about v2.6 to come available? 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by cbron** [comment]
2.6 documentation will be published with 2.6.0, we don't have any beta specific information.
