### ISSUE TITLE
Air-gapped mixed (win+linux) env preperation, private registry issue

### ISSUE THREAD

**Issue by tal47** [rancher/rancher#33305]
**What kind of request is this (question/bug/enhancement/feature request):**
Hi,
I am running an air-gapped env, mixed windows + Linux nodes.
Rancher version 2.5.8.
Using your instructions as described here:
https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/populate-private-registry/
and here
https://github.com/rancher/docs/issues/1742

1. I am using the registry:2 image to run a local registry.
2. After downloading both windows +Linux images using the rancher_save scripts, I am uploading the windows images using the default rancher_load script.
3.  After the windows upload is done, I am running the rancher_load on a Linux node, using:
`./rancher-load-images.sh --registry <reg-ip>:5000 --windows-image-list ./rancher-windows-images.txt --windows-versions "1809" --image-list ./rancher-images.txt`
3. After the script finished and all of the images are uploaded successfully, I am starting a Rancher cluster, adding Linux nodes as usual, and when I need to add the windows node when it tries to pull the <reg-ip>:5000/rancher-agent image, I am getting:
`image operating system “Linux” cannot be used on this platform” error.`
Which means the manifesting didn't work.
What can I do?

**Steps to reproduce (least amount of steps as possible):**
as mentioned in the instructions.

**Result:**
In a UI connected to the registry, I can see different tags:
![image](https://user-images.githubusercontent.com/16876322/122742464-a2982100-d28e-11eb-9abd-2c52f0a10c4e.png)

**Expected Result:**
A fixed manifest process that allows me to use one registry for both rancher on windows+linux

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- 2.5.8
- Installation option (single install/HA):
Mixed windows+linux

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Self-hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Bare metal
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
Linux: 18.06.3-ce
windows: 19.03.16
```

Any suggestions please? thanks!

**Comment by nickgerace** [comment]
Hi! Thanks for filing an issue. We do not allow Rancher to be installed on a mixed Windows and Linux cluster. A mixed node cluster must be a downstream cluster. 

Provisioning Windows clusters: https://rancher.com/docs/rancher/v2.5/en/cluster-provisioning/rke-clusters/windows-clusters/
Rancher requirements: https://rancher.com/docs/rancher/v2.5/en/installation/requirements/#operating-systems-and-container-runtime-requirements

> "Rancher should work with any modern Linux distribution."

Perhaps, we may want to make this more clear. I recommend filing an issue or PR in [rancher/docs](https://github.com/rancher/docs).
