### ISSUE TITLE
Update Ingress usages to support k8s 1.22

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#33312]
The code contains multiple references to `Ingress` from `extensions/v1beta1` / `networking.k8s.io/v1beta1` which are getting removed in k8s 1.22. Replacement API (`networking.k8s.io/v1`) is available in k8s 1.19+ and since Rancher v2.6 release should still support k8s 1.18, we cannot simply replace it outright.

Note: Support of other objects with removed APIs is https://github.com/rancher/rancher/issues/33222

Some sort of conditional logic will need to be implemented. Initial notes based on discussion with @ibuildthecloud :

> ibuildthecloud
> I'm guess you are going to have to do conditional logic and basically have two code paths.  You can create some wrapper object to abstract ingress so as to not repeat all the code.  Then ideally it would just be which controller is started.  One odd corner case is what do you do when a cluster upgrades from 1.18 to 1.22 as the available apis will dynamically change.
> 
> snasovich
> My understanding is that the existing objects are automagically “upgraded” when they are queried with new API version. Observed it with CRDs created as v1beta1 returned as v1 when querying them with `kubectl get ...`
> 
> ibuildthecloud  12:35 PM
> My point was more around the client logic here.  So the controllers will have to do "if v1.18; then ..."  and the issue is if that check is done once upfront what happens when the API version changes under the hood because of a cluster upgrade.

**Comment by cbron** [comment]
@snasovich this is one of few that had issue already: https://github.com/rancher/rancher/issues/30053
In that one we said just to wait on it until 1.19 is gone, but we could also go after the kube api version conditional. Problem there in past has been that some API versions are non-standard.

**Comment by snasovich** [comment]
@cbron , #30053 sounds specific to Helm charts while this is one is specifically for references in rancher/rancher code. It should be fairly straightforward to conditionally use one or other version of API in Helm charts based either on k8s versions or `.Capabilities.APIVersons.Has` as in https://github.com/rancher/rancher/pull/29922; not so much in Rancher code where is uses specific APIs when creating/querying Ingress objects.
Note the plan is for whoever is assigned to Rancher Helm charts to review and update not just Ingress, but any other APIs that are getting removed in k8s v1.22.

**Comment by snasovich** [comment]
@cbron , clicked "Comment" a bit too early. We may not be able to wait for when we no longer need to support 1.18 as v2.6 (or one of v2.6.x) will need to support k8s from v1.18 to v1.22.
Also, could you elaborate on _Problem there in past has been that some API versions are non-standard._ What non-standard API versions you mean here?

**Comment by cbron** [comment]
> sounds specific to Helm charts while this is one is specifically for references in rancher/rancher code

makes sense, we can keep both

> We may not be able to wait for when we no longer need to support 1.18 as v2.6 (or one of v2.6.x) will need to support k8s from v1.18 to v1.22.

Yes the plan was to make one of those 2.6.x's do the dropping of conditional code, because we still need to support 1.18 and 1.18 doesn't have v1, only 1.19 does. 

> Also, could you elaborate on Problem there in past has been that some API versions are non-standard. What non-standard API versions you mean here?

GKE for example has some versions like this: `1.18.16-gke.300`, `1.18.15-gke.1501`. Depending on where the check is happening it can cause problems. We had trouble with the Rancher chart. I can try to find more specific example.

**Comment by anupama2501** [comment]
Verified as part of https://github.com/rancher/rancher/issues/34054, https://github.com/rancher/rancher/issues/35636, https://github.com/rancher/rancher/issues/35764
