### ISSUE TITLE
[v2.4] KDM release: k8s june patches

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#33310]
### **Kubernetes Updates:**
This is a KDM release for new k8s versions: `v1.18.19`. It's not going out with any Rancher release, it's a KDM + RKE release only.

| New k8s versions | Rancher versions | 
| --- | --- | 
|`v1.18.20-rancher1-1` | 2.4.5+ | 

### **Rancher updates:**
- `rke-tools` is updated to `v0.1.75`

### **Developer changelog:** 
- All existing `v1.18.x` versions in dev-v2.4 need to be released or have been released (are present in release-v2.4) so we need to introduce new k8s version. To introduce a new k8s version, basecopy the latest existing version in a separate commit, followed by another commit to update what's changed. Following versions need to be created with their compatible rancher server versions:

| basecopy [version](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/k8s_rke_system_images.go#L3590) from | create | set [rancher version constraints]( https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.4/rke/k8s_version_info.go#L278) 
| --------------- | --------------- | -----------| 
| v1.18.19-rancher1-1 | v1.18.20-rancher1-1 | 2.4.5+ |

**Comment by kinarashah** [comment]
Available to test with `dev-v2.4` KDM and RKE RC `v1.1.18-rc2` once drone passes. Link: https://drone-publish.rancher.io/rancher/rke/1014

**Comment by sowmyav27** [comment]
**Validated the following:**
### Fresh install checks - 2.4.15 - pointing to dev-v2.4
- Deployed clusters using k8s 1.18.20-rancher1-1 using all network providers - weave/flannel/calico/canal
- Validated Network checks on all clusters
- Validation tests look good on Canal cluster

### Upgrade checks

- On 2.4.15 KDM job pointing to release-v2.4 - deploy cluster with k8s v1.18.18-rancher1-1 version on all 4 network providers
- pre upgrade checks look good
- Upgrade KDM to dev-v2.4
- Upgrade K8s versions to new versions - v1.18.20-rancher1-1
- Post upgrade checks look good.

### Min checks on 2.4.5

- Deployed 2.4.5 pointing to dev-v2.4
- Created Clusters for k8s versions - v1.18.20-rancher1-1 ONLY with all network provider 
- Validated network checks on the clusters - and they look good.

### RKE. checks
- Deployed a k8s cluster using `v1.1.18-rc2` RKE version and k8s - 1.18.20-rancher1-1. 
- Basic checks on this cluster worked.
