### ISSUE TITLE
Bug: how to replace / update the trusted CA for fleet agents after replacing the rancher certificate

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rancher#33323]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug / missing documentation

**Steps to reproduce (least amount of steps as possible):**

After deploying rancher with self-signed certificate on rke2 and importing one downstream rke2 cluster fleet gets deployed automatically.

Now replace the certificate of rancher following the process in https://rancher.com/docs/rancher/v2.x/en/installation/resources/update-ca-cert/ with an other certificate from an other CA and re-configure the downstream cattle-agents..

Now do a deployment/adjustment of some fleet things - i.e. add labels to clusters and wait on the re-deployment of the fleet git repos...

**Result:**

We see that the deployment does not work and in the fleet-agent logs we see this:

```
time="2021-06-22T09:30:44Z" level=error msg="Current credential failed, failing back to reregistering: Get \"https://rancher.xxx.com/apis/fleet.cattle.io/v1alpha1/namespaces/cluster-fleet-default-c-7fjlx-a0996dafa2d3/bundledeployments\": x509: certificate signed by unknown authority"
time="2021-06-22T09:30:44Z" level=error msg="Failed to register agent: looking up secret fleet-system/fleet-agent-bootstrap or fleet-system/fleet-agent: looking up secret fleet-system/fleet-agent-bootstrap: secrets \"fleet-agent-bootstrap\" not found"
```

**Expected Result:**

After replacing the certificate of rancher - also fleet should continue to work.
In case manual adjustments are required - these should be documented.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE2 imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal and VM
- Kubernetes version (use `kubectl version`): 1.20.7 rke2r2

**Comment by axeal** [comment]
Successfully re-created the behaviour here and opened a [docs issue](https://github.com/rancher/docs/issues/3381) to include the required step in the Rancher Update CA documentation. My repro:
1. Provision a Rancher v2.5.8 cluster, with a private-CA signed certificate, i.e. create `tls-ca` and `tls-rancher-ingress` and `-set privateCA=true` and `--set ingress.tls.source=secret`
2. Add a single all role node custom cluster
3. Update `tls-ca` and `tls-rancher-ingress` secret with a new private-CA signed certificate.
4. Delete Rancher Pods to force re-schedule and verify `/v3/settings/cacerts` updated.
5. Reconfigure Rancher agents in the custom cluster to trust the new CA (I used https://github.com/rancherlabs/support-tools/tree/master/cluster-agent-tool)
6. Delete the fleet-agent Pod in the downstream cluster, to force re-scheduling and attempt to connect to Rancher
7. Observe certificate trust error in fleet-agent Pod logs
8. Observe mismatch between `certificate-authority-data` in kubeconfig configured for fleet-agent `kubectl -n fleet-system get secret fleet-agent -o jsonpath={.data.kubeconfig} | base64 -d` and the new CA for Rancher

Resolution:
In the Rancher Explorer UI navigate to the Continuous Delivery view, click clusters, select the custom cluster and click `Force Update` The fleet-agent will be redeployed with an updated fleet-agent secret containing the new CA.

**Comment by Martin-Weiss** [comment]
Great - thanks a lot for this analysis and fix!

Could you explain what exactly the "force update" does or point me to the documentation for this button in Rancher? 
Does this delete/redeploy any workload, too?
Might this cause any load or downtime for repos deployed to the target cluster?
