### ISSUE TITLE
Huge secrets in the UI not displayed

### ISSUE THREAD

**Issue by vkamlov** [rancher/rancher#33326]
**Bug**

**Steps to reproduce:**
After upgrading the rancher from v.2.2.13 to v2.4.15, huge secrets in the user interface were no longer displayed. 
Problem is also observed after upgrading to v2.5.7.

**Result:**
When viewing a huge secret in the user interface, the base64 encoding is displayed.
When you click on edit, the size of the secret is displayed instead of the text.
![image](https://user-images.githubusercontent.com/55585186/122914336-376c4e80-d363-11eb-9436-d0ff9d8dd857.png)

**Expected Result:**
The secrets data is expected to be displayed as in previous versions of the rancher such as v2.2.13.
![image](https://user-images.githubusercontent.com/55585186/122914728-9fbb3000-d363-11eb-811a-c7e1cdb99483.png)

**Other details that may be helpful:**
Our secrets, in which there is a problem, are really very big.
Perhaps the problem is also observed in the configs (not tested)

**Environment information**
- Rancher version - rancher/rancher:v2.4.15
- Installation option - single install or HA

**Cluster information**
- Cluster type - Custom
- Machine type - VM
- Kubernetes version - v1.15.12 or v1.16.15

- Docker version:

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:46 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by vincent99** [comment]
This has nothing to do with the size, but is shown when the value contains [non-"ASCII-like"](https://github.com/rancher/ui/blob/master/lib/shared/addon/utils/util.js#L11) characters, because putting arbitrary binary data into a (UTF-8 only) `<textarea>` will corrupt it even if you don't intentionally change it.

**Comment by vkamlov** [comment]
You were absolutely right! I actually found a cyrillic typo in this secret, and after removing it, the secret is visible again in the UI.
Thanks a lot for this help!
