### ISSUE TITLE
multi-cluster-management flag available in fresh installation

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#33329]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* Deploy `rancher/rancher:master-head 51d074b` on RKE single-node cluster by helm
* Go to `Global Settings` in Explorer and switch to `Feature Flags` pane

**Result:**
* MCM feature flag is present but according to https://github.com/rancher/rancher/issues/33264#issuecomment-863780746 it shouldn't be there:

![mcm](https://user-images.githubusercontent.com/12828077/122965487-87a9d780-d388-11eb-922c-7b4d79d38dd9.png)

**Other details that may be helpful:**
* It couldn't be `Deactivated` once it is `Active` so I guess MCM flag shouldn't be present on fresh cluster
* Also I didn't find a way how to disable the MCM feature flag - in 2.5.8's Ember UI there were two radio-buttons in initial wizard for it like:`I want to create or manage multiple clusters` & `I'm only going to use the cluster Rancher was installed on` but these are missing in Explorer.
* I checked `helm inspect values rancher-latest/rancher` output but I couldn't find anything related to MCM there

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher/rancher:master-head 51d074b`
- Installation option (single install/HA): any 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): any
- Machine type (cloud/VM/metal) and specifications (CPU/memory): any
- Kubernetes version (use `kubectl version`): v1.19.6

**Comment by vincent99** [comment]
We're taking away the disable action, not hiding it entirely (in https://github.com/rancher/dashboard/pull/3314)

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head c7f3cce` The action for disabling MCM is hidden now:
![mcm_disable](https://user-images.githubusercontent.com/12828077/123626807-860d6300-d811-11eb-9810-dd15f63c09b6.png)

Closing.
