### ISSUE TITLE
agent.remove removes storage pools

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3333]
Needs fixed. Not sure what the proper behavior should be.

~~Thinking we could: _not_ delete the SP if it is a non-local SP and leave it up to user to explicitly delete. If an agent comes back reporting the same SP, re-associated it.~~

**Comment by cjellick** [comment]
Bug:
If the "agent container" for convoy is removed for any reason, the storage pool gets deleted and recreated.

Steps to repro:
1. Create a convoy-nfs setup
2. From the host, do a docker rm on the storagepool-agent container*

Actual Result:
The storage pool gets quickly deleted and recreated, resulting in all the volumes that were in that storage pool disappearing from the UI (because they are associated to a deleted storage pool).

Expected Result:
Deleting the container should not result in the storage pool getting deleted. The only thing that should happen is a new storagepool agent container is created for the stack.

 *Another way to get into this scenario is to stop and start rancher-server. This is because the storagepool agent container to stop (because it is subscribing to rancher events and when rancher goes down, it exits). When rancher comes back up, it will see that the container stopped and delete it and schedule a new one to replace it. This is the scenario that was outlined in #3334.

**Comment by sangeethah** [comment]
Tested the following scenarios with latest build from master:

Steps to repro:
Create a convoy-nfs setup

Scenario 1:
1. From the host where nfs-storagepool container, remove the convoy-nfs-storagepool container.
docker rm -f r-convoy-nfs_convoy-nfs-storagepool_1

This results in another instance of convoy-nfs_convoy-nfs-storagepool being created succesfully.

Scenario 2:
1. power down the host where the convoy-nfs-storagepool container is running.

This results in the existing instance of convoy-nfs_convoy-nfs-storagepool being marked unhealthy and recreated successfully in another host.

The host is removed from the storage pool's list of of hosts.

2. power on the host again.
convoy-nfs on the agent is recreated.The host gets added to the storage pool's list of of hosts.

During the course of above testing , storage pool itself never gets deleted and recreated and the volumes always remain associated with the storage pool.
