### ISSUE TITLE
Keycloak OIDC - can't access with users members of nested groups with Site access restricted to specific users/groups

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#33337]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Enable Keycloak OIDC on latest `2.6 master-head` build.
- On site access use Restricted access to specify which users and groups are allowed to login
- Add a group that is a nested under a parent group

Example here is:

![Screen Shot 2021-06-22 at 4 11 34 PM](https://user-images.githubusercontent.com/27659/123011077-a00ff700-d374-11eb-98e2-d2ce5862594c.png)

`nestedautogroupnested2` it has member `testuserx` and the parent group is `nestedautogroupnested1`

**Result:**

`testuserx` is not able to login

**Expected Result:**

- Adding `nestedautogroupnested2` or `nestedautogroupnested1` to allowed groups should allow `testuserx` to login

**Other details that may be helpful:**

- users members of groups that are not nested are able to login
- `testuserx` is able to login with `Allow all valid users` site access.

Other detail here is the `nestedautogroupnested2` groupname is not shown in the UI if we refresh the site access page.
Non-nested groups are shown properly (`izaacgroup`)

![Screen Shot 2021-06-22 at 2 58 38 PM](https://user-images.githubusercontent.com/27659/123011412-2a585b00-d375-11eb-8282-b53a98dc89da.png)

**Environment information**
- Rancher version: `2.6 master-head (06/22/2021)` _d44698d_
- Installation option: HA RKE1

https://github.com/rancher/rancher/issues/30280

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/07/2021)` _cf5a75f_
Keycloak version: `3.3.0.Final`

I see two things happening on site access and nested groups.

## 1
First behavior is I add a nested group and then I reload the site access by either navigating to other Dashboard page or login back in. The nested group can't be retrieved.

Error response is:

`{"baseType":"error","code":"ServerError","message":"json: cannot unmarshal array into Go value of type keycloakoidc.account","status":500,"type":"error"}`


## 2
The second behavior, which is probably related to the above issue is that I can't login with users member of a group that has a parent group allowed to access Rancher

`nestedgroup1` -> Parent
`nestedgroup2` -> Child of `nestedgroup1`
`testuserx` is member of `nestedgroup2` and `nestedgroup1` is allowed to login from the Auth Site Access page.

Resulting in `testuserx` mnot able to login.

**Comment by brendarearden** [comment]
Group search was broken because in some instances the ID was being used and in others the NAME was being used. I corrected this with my PR to always use NAME. Overall I am not able to add support for nested groups because the auth provider framework is only setup to return 1 principal and not several. This means that in rancher, keycloak groups are viewed as flat. For example, if you have a parent group with several children groups in keycloak, you would have to add the parent and children groups individually in rancher if you want all of those users to get access instead of just adding the parent group.

**Comment by vincent99** [comment]
You don't want multiple principals, the auth framework returns one principal with a list of groups on it and that's all you'd need here.

IF you could get the data that
A) `testuserx` is a member of `nestedgroup2` and
B) `nestedgroup2` is a child of `nestedgroup1`

then you would return the user's principal with both groups in their group list.

Some of our drivers have an option to do that, but it's often expensive (i.e. N+1 calls) or impossible to know "B".

**Comment by izaac** [comment]
There seems to be consensus on checking support for nested groups.

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/29/2021)` _94bca99_

Site access modes checked:

- Allow any valid user
- Allow members of clusters and projects, plus authorized users & groups
- Restrict access to only Authorized users & groups

P0 checks for done for RBAC using Ember for the members of clusters and projects using groups which has an issue filed on Dashboard. https://github.com/rancher/dashboard/issues/3588
Users' groups principals where listed properly in `/v3/principals` including all the parent and nested groups the user is member.

I was able to create namespaces and other resources as member/owner as expected.
As read-only I was only able to see the existing resources where expected.


An additional pass will be required to do all these from Dashboard due to https://github.com/rancher/dashboard/issues/3588

I also will test Nested Groups Mappers scenarios as part of the Auth feature validation test cases. Coverage here only included the P0 site access validation.
