### ISSUE TITLE
[Backport 2.5] Add EKS v1.19 

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#33357]
Backport: https://github.com/rancher/ui/pull/4626

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `0e587683`**

- 1.20 and 1.19 are available when deploying EKSv2.
- User is able to deploy 1.20 and 1.19 EKS v2 clusters - v1.19.8-eks-96780e and v1.20.7-eks-8be107
