### ISSUE TITLE
[Backport Monitoring V2] Rebase to kube-prometheus-stack 16.x.x

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#33351]
Backports https://github.com/rancher/rancher/issues/32519 to 2.5.x line

**Comment by aiyengar2** [comment]
This should also backport https://github.com/rancher/rancher/issues/33210

**Comment by aiyengar2** [comment]
Forgot to backport https://github.com/rancher/rancher/pull/33333.

**Comment by slickwarren** [comment]
on 2.5-head (500de20):
clean install — Pass
Upgrade 9.4.20x -> 16.6.0 — pass* [filed this ticket](https://github.com/rancher/rancher/issues/33820) 
uninstall + reinstall — pass
p0 usecase -- pass
Uninstall upgraded 16.6.0 — pass
Uninstall clean 16.6.0 — pass
checked all prometheus targets and grafana dashboards
