### ISSUE TITLE
instance create assigns volumes to pools that are removed

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3335]

**Comment by cjellick** [comment]
@flaccid reported this on IRC around 1/19/16 back. I'm hazy on the details of how to repro, but it involved  deleting a local docker pool by removing a host and then creating a new host.

**Comment by flaccid** [comment]
@cjellick the fix (https://github.com/rancher/cattle/pull/1280) by @ibuildthecloud certainly did the trick. I can confirm this is no longer an issue; we are back to treating cattle like poor cattle.

**Comment by cjellick** [comment]
Ok great, thanks for confirming!
