### ISSUE TITLE
Support ebs/longhorn mode for volumes

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3336]
With convoy-gluster volumes, you can have many containers across many hosts reading and writing to a single replicated volume.

Volumes for longhorn/ebs are not fully replicated like convoy-gluster volumes. Once a single container is using a volume, only containers on the same host should be able to mount it.

VMs take this a step further: once a single VM is using a volume, no other containers/vms should be allowed to mount it.

**Comment by cjellick** [comment]
This will be  addressed by @ibuildthecloud's volume driver refactor.

**Comment by deniseschannon** [comment]
If there are further issues with this, please re-open. This was fixed with our volume driver refactoring.
