### ISSUE TITLE
Rancher, Vsphere, Ubutnu 20 waiting for ssh, already reset cloud init. 

### ISSUE THREAD

**Issue by rlewkowicz-rcd** [rancher/rancher#33368]
So there's lots of conversation about making sure you reset your instance or use the cloud init clean etc. I've done these things, but theres no indication that the cloud init from rancher is ever running. 

```
#cloud-config
final_message: "cloud-init completed after $UPTIME seconds and finished at: $TIMESTAMP"
# Uncomment to log all command output to a file
output: {all: '| tee -a /var/log/cloud-init-output-tee.log'}
```

This is my modest addition, and I don't see these things being run either. No errors either. Cloud init does run though. The template has no instance folder, yet the provisioned nodes do. 

still hangs at waiting for ssh. 

This article claims that it's mounted as an iso image:
https://www.virtualthoughts.co.uk/2019/12/27/on-prem-k8s-clusters-with-rancher-terraform-and-ubuntu/

how can I verify this happened?

**Comment by rlewkowicz-rcd** [comment]
This is a little spammy at this point, I have 2 issues open, but this is a massive pain with no errors no feed back no anything. It's just shots in the dark until it works I want this info out there as much as possible to save people some pain
```
/etc/cloud/cloud.cfg.d/99-installer.cfg
```
needs the nocloud datasource
```
datasource_list: [ "NoCloud", "VMwareGuestInfo" ]
```

I really feel like the image prep documentation is lacking

**Comment by David-VTUK** [comment]
Have replied in https://github.com/rancher/rancher/issues/33374#issuecomment-869056007 which should help clarify
