### ISSUE TITLE
Unable to start rancher/rancher:latest on fresh AWS t3.medium Ubuntu 20.04 vm

### ISSUE THREAD

**Issue by flybd5** [rancher/rancher#33364]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

- Make a new Ubuntu 20.04 VM on an AWS t2.medium w/30gb EBS storage
- Sudo apt update and upgrade
- Run this shell script (the first line is a workaround for another bug that causes a K3S fatal exit):

```
 sysctl net/netfilter/nf_conntrack_max=131072
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -v ~/.acme.sh/mydomain.com/tls.crt:/etc/rancher/ssl/cert.pem \
  -v ~/.acme.sh/mydomain.com/tls.key:/etc/rancher/ssl/key.pem \
  --privileged \
  rancher/rancher:latest \
  --no-cacerts
```

**Result:**

Rancher server never responds on port 80 or 443

**Expected Result:**

The Rancher server welcome page displays.

**Other details that may be helpful:**

Logs: https://docs.google.com/document/d/1XTDlI-iO-DXOuXFf9Zbf5lLL53z4Lj7e-aW8UnK4LbI/edit?usp=sharing

Rancher version: Latest 2.5.8
Fresh AWS VM, t2 medium, Ubuntu 20.04, 30gb storage

**Comment by flybd5** [comment]
Backing up to Ubuntu 18 removed the need for the workaround on the first line of the start script. Then i fixed the references to the certs and remove --no-cacerts and it finally came up. You folks have a definite problem with Ubuntu 20 compatibility...

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/33360
