### ISSUE TITLE
[Monitoring V1, 2.5.8] Rancher keeps trying to install Monitoring V1 even when not enabled

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#33369]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
The steps used to break the cluster were not exactly clear, but we saw the following symptoms:
- Monitoring V1 (both project and cluster) and Alerting V1 were disabled. We double checked this using our [check-monitoring-disabled.py](https://github.com/bashofmann/rancher-monitoring-v1-to-v2/blob/master/check_monitoring_disabled.py) script, even after commenting out [this](https://github.com/bashofmann/rancher-monitoring-v1-to-v2/blob/bbf6fff788f08f0c16d03d921f2f005b39fee4d5/check_monitoring_disabled.py#L100-L101)
- While Monitoring V1 was stuck deleting, the finalizer from the cattle-prometheus namespace was forcibly removed to delete it
- Only the Prometheus CRD was deleted / did not exist in the cluster
- Monitoring V2 was also installed in the cluster while it was broken
- Rancher downstream controllers showed the same errors as indicated in https://github.com/rancher/rancher/issues/32978.

**Result:**
Monitoring V1 continuously pings `failed to ensure monitoring project name` in the logs and shows up in a giant red warning on the top of the downstream cluster

**Expected Result:**
Monitoring V1 should have been removed and we should not be trying to put it back in the cluster

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8
- Installation option (single install/HA): unsure

Kubernetes version: 1.20.6

**Comment by dhawton** [comment]
**Other details that may be helpful:**
An error banner in the UI while in the downstream cluster was displaying: Failed to ensure monitoring project name: stale "cattle-prometheus" Namespace is still on terminating

Namespace did not exist when running kubectl get namespaces. This message went away after re-enabling Monitoring v1.

**Comment by MKlimuszka** [comment]
Closed as we are not adding fixes to 2.5.x
