### ISSUE TITLE
Custom RKE2 cluster has worker nodes marked with "All" roles and "apply-system-agent-upgrader" jobs are failing on workers then

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#33363]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* deploy any local cluster with `rancher/rancher:master-head e756276`
* from Dashboard provision custom RKE2 cluster with 3 cp+etcd and 3 worker nodes using k8s `v1.21.1-rc3+rke2r1`
* once the cluster is provisioned and `Active`, select the cluster in `EXPLORE CLUSTER` and click on `Cluster/Nodes`

**Result:**
* you will see that worker nodes are marked with `All` roles instead of `Worker` roles
![workers_with_all_role](https://user-images.githubusercontent.com/12828077/123278461-412eb700-d507-11eb-99a7-0c907b0b110b.png)

* A consequence of this issue is that Jobs `apply-system-agent-upgrader-on-*-with*` running on all workers in `cattle-system` namespace are in `Error` and won't recover:
![system-agent-upgrader-failure](https://user-images.githubusercontent.com/12828077/123279166-e6e22600-d507-11eb-8951-b174b88f3e42.png)

This is log from one of the failed Job (~ unable to grep any role which should be set on worker node):
```
+ TMPDIRBASE=/var/lib/rancher/agent/tmp
+ mkdir -p /host/var/lib/rancher/agent/tmp
+ chroot /host /bin/sh -c 'mktemp -d -p /var/lib/rancher/agent/tmp'
+ TMPDIR=/var/lib/rancher/agent/tmp/tmp.0x3yCbEjvb
+ cp /opt/rancher-system-agent-suc/install.sh /host/var/lib/rancher/agent/tmp/tmp.0x3yCbEjvb
+ cp /opt/rancher-system-agent-suc/rancher-system-agent /host/var/lib/rancher/agent/tmp/tmp.0x3yCbEjvb
+ chmod +x /host/var/lib/rancher/agent/tmp/tmp.0x3yCbEjvb/install.sh
+ '[' -n dhcp205 ]
+ NODE_FILE=/host/var/lib/rancher/agent/tmp/tmp.0x3yCbEjvb/node.yaml
+ kubectl get node dhcp205 -o yaml
+ '[' -z ]
+ grep -q 'node-role.kubernetes.io/etcd: "true"' /host/var/lib/rancher/agent/tmp/tmp.0x3yCbEjvb/node.yaml
+ '[' -z ]
+ grep -q 'node-role.kubernetes.io/controlplane: "true"' /host/var/lib/rancher/agent/tmp/tmp.0x3yCbEjvb/node.yaml
+ '[' -z ]
+ grep -q 'node-role.kubernetes.io/control-plane: "true"' /host/var/lib/rancher/agent/tmp/tmp.0x3yCbEjvb/node.yaml
+ '[' -z ]
+ grep -q 'node-role.kubernetes.io/worker: "true"' /host/var/lib/rancher/agent/tmp/tmp.0x3yCbEjvb/node.yaml
+ export 'CATTLE_AGENT_BINARY_LOCAL=true'
+ export 'CATTLE_AGENT_BINARY_LOCAL_LOCATION=/var/lib/rancher/agent/tmp/tmp.0x3yCbEjvb/rancher-system-agent'
+ chroot /host /var/lib/rancher/agent/tmp/tmp.0x3yCbEjvb/install.sh
[FATAL] You must select at least one role.
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master-head e756276
- Installation option (single install/HA): local any, custom RKE2 HA (extra worker nodes)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): any
- Kubernetes version (use `kubectl version`): `v1.21.1-rc3+rke2r1`

**Comment by anupama2501** [comment]
closing this issue as it is being tracked via https://github.com/rancher/dashboard/issues/2955
