### ISSUE TITLE
Re-test EKS/GKE provisioning

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#33371]
The operators are switching to using the SLES image (the same as Rancher). In order to ensure there are no surprises, provisioning the hosted clusters should be tested.

**Comment by aaronRancher** [comment]
Testing GKE is currently blocked by this issue: https://github.com/rancher/rancher/issues/31592#issuecomment-870997073

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 5b0da3`
I am able to provision GKEv2 and EKSv2 clusters. System workloads are healthy. Clusters can be edited and upgraded.

EKS operator version: `eks-operator:v1.1.1-rc5`
EKS k8s version: `v1.20.4-eks-6b7464`
GKE operator version: `gke-operator:v1.1.1-rc6`
GKE k8s version: `v1.19.9-gke.1900`
