### ISSUE TITLE
volume data not removed on disk when a volume is deleted in rancher

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3337]
if a volume first gets deleted from docker and then gets deleted from convoy, only the metadata is deleted and the actual volume is still there. the docker volume delete just deletes the metadata. so, when convoy tries to do a convoy delete, the metadata is gone and we dont know what to acutally delete

**Comment by cjellick** [comment]
Steps to repro/test:

1. Create a container with a convoy-nfs volume
2. Delete and Purge the container
3. Go to host and do a `docker volume rm <vol name>`
4. Back in Rancher UI, delete and purge the volume
5. On you NFS server, check that the directory for the volume is gone (it will have the same name as the volume)

In the interest of full disclosure: We fixed this by ignoring docker deletes for convoy-nfs when . So, when you do the `docker volume rm <volume name>`, we ignore it. So, if you were to follow the rm up with a `docker volume ls`, you would still see it. But this behavior is intentional, not a bug because we don't consider a volume removed until it is removed via Rancher's orchestration.

**Comment by sangeethah** [comment]
Tested with latest build from master and convoy-agent - rancher/convoy-agent:v0.6.0

Host - Docker version 1.10.3, build 20f81dd
Scenario 1:

Create a container with a convoy-nfs volume
Delete and Purge the container
Go to host and do a docker volume rm <vol name>
Back in Rancher UI, delete and purge the volume

The purged volume is still listed when listing volumes (docker volume ls)
Also the volumes are not getting deleted from nfs server.


Scenario 2:
Create a container with a convoy-nfs volume
Delete and Purge the container
Delete and purge the volume

The purged volume is still listed when listing volumes (docker volume ls)
Also the volumes are not getting deleted from nfs server.

**Comment by cjellick** [comment]
OK, lets try again @sangeethah.
Use my catalog again. New image is rancher/convoy-agent:v0.7.0

**Comment by sangeethah** [comment]
Tested with latest build from master and using rancher/convoy-agent:v0.7.0.

Tested the following scenario:
Create nfs-convoy (v0.3.0) stack from catalog url - https://github.com/cjellick/rancher-catalog/

Scenario 1:

Create a container with a convoy-nfs volume
Delete and Purge the container
Go to host and do a docker volume rm 
Back in Rancher UI, delete and purge the volume
The purged volume is not  still listed in the host anymore (docker volume ls)
Volume directory gets deleted from nfs server.
Also config/vfs_volume_<volume-name>.json gets deleted from nfs server.

Scenario 2:
Create a container with a convoy-nfs volume
Delete and Purge the container
Delete and purge the volume
The purged volume is not  still listed in the host anymore (docker volume ls)
Volume directory gets deleted from nfs server.
Also config/vfs_volume_<volume-name>.json gets deleted from nfs server.
