### ISSUE TITLE
Support configuration of multiple replicas for Rancher-logging chart components such as fluentd

### ISSUE THREAD

**Issue by petertang2012** [rancher/rancher#33373]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Install Rancher-logging chart and look at its values.yaml template.

**Result:**
Values.yaml from Rancher-logging chart does not provide option to configure multiple replicas for logging sub components such as fluentd.

**Expected Result:**
It would be great if we can adjust number of replicas for fluentd so that we can bring more resiliency. 

**Other details that may be helpful:**
Neither the released stable version of Rancher logging nor the latest  version on `dev-v2.5` branch support this config.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8 with logging chart at `3.9.400` from `dev-v2.5` branch
- Installation option (single install/HA): HA

**Comment by paynejacob** [comment]
This is already possible with `fluentd.replicas`

**Comment by maxisam** [comment]
@paynejacob It doesn't work

```yml
fluentd:
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    tcpSocket:
      port: 24240
  resources: {}
  replicas: 2
```

rancher-logging:3.9.400
rancher 2.5.8
k8s: v1.19.9

![image](https://user-images.githubusercontent.com/456807/127671191-a65b66f8-357f-4902-a73c-e106017f73e0.png)

**Comment by paynejacob** [comment]
@maxisam my mistake this option will be added with v2.6.0  I will advocate for getting this back ported to v2.5.x

**Comment by maxisam** [comment]
@paynejacob Thank you! It has been a while someone response to my issues.
