### ISSUE TITLE
Istio v2  istio upgrade fails when all helm deploy options selected with error ""Service "kiali" is invalid" 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33372]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

Istio versions 1.9.600 

**Steps to reproduce (least amount of steps as possible):**
1. Create  a downstream node driver with 3 worker, 1etcd, 1 cp 
2. Install monitoring and istio [enabling kiali and jaeger] in the system project 
3. Upgrade the istio by selecting all helm deploy options 
4. Happens on 1.9.500 and 1.8.6 as well.

**Result:**
 istio upgrade fails with the error:
```
Replaced "istio-component-monitor" with kind ServiceMonitor for kind ServiceMonitor
--
Thu, Jun 24 2021 7:33:39 pm | Error: UPGRADE FAILED: failed to replace object: Service "kiali" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset && failed to replace object: Service "tracing" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset && failed to replace object: Service "zipkin" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset && failed to replace object: Service "jaeger-collector" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset
```
**Expected Result:**
Upgrading should have gone through and not errored out.

**Other details that may be helpful:**
If we uncheck kiali and jaeger while upgrading, the above issue will not be seen.
<img width="373" alt="Screen Shot 2021-06-24 at 6 40 48 PM" src="https://user-images.githubusercontent.com/38144301/123361653-50702d80-d524-11eb-8bcf-cb6b40bb10e0.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8
- Installation option (single install/HA): single

**Comment by brendarearden** [comment]
This is being fixed upstream (I will add a release note to cover it). Using the `--force` flag causes known issues with immutable fields in kubernetes. It is potentially an issue with all of our charts. https://staging.rancher.com/docs/rancher/v2.6/en/helm-charts/ << you can check the note I added at the bottom of this page as the test.

**Comment by anupama2501** [comment]
Verified docs are update. Closing this issue as it is a no-fix and only updated in the docs.
