### ISSUE TITLE
apply-system-agent-upgrader pods on agent node are in error state while creating custom rke2 cluster

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rancher#33384]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

- Create a custom cluster with one master node with all roles (etcd, cp, worker)
- Wait for master to be active
- Join agent node using Worker role and run registration command on the node.
- Wait for the cluster to be Active
- Click on cluster, select Explore, go to Nodes, select worker node
- apply-system-agent-upgrader pods are in Error state.

**Expected Result:**
Pods should be in Running state

**Other details that may be helpful:**
![image](https://user-images.githubusercontent.com/56045581/123493730-2f661600-d5d2-11eb-8b28-44e03b3faee5.png)

**Environment information**
- Rancher version: master-head commit: c7f3cce

- Installation option (single install/HA):
Two node rke2 cluster, one master, one agent

**Cluster information**
- Cluster type:Custom
- Machine type: AWS
- Kubernetes version: v1.21.2+rke2r1

Logs from agent job. pod:
```
+ TMPDIRBASE=/var/lib/rancher/agent/tmp
+ mkdir -p /host/var/lib/rancher/agent/tmp
+ chroot /host /bin/sh -c 'mktemp -d -p /var/lib/rancher/agent/tmp'
+ TMPDIR=/var/lib/rancher/agent/tmp/tmp.lqtiGhf0FX
+ cp /opt/rancher-system-agent-suc/install.sh /host/var/lib/rancher/agent/tmp/tmp.lqtiGhf0FX
+ cp /opt/rancher-system-agent-suc/rancher-system-agent /host/var/lib/rancher/agent/tmp/tmp.lqtiGhf0FX
+ chmod +x /host/var/lib/rancher/agent/tmp/tmp.lqtiGhf0FX/install.sh
+ '[' -n ip-172-31-44-117 ]
+ NODE_FILE=/host/var/lib/rancher/agent/tmp/tmp.lqtiGhf0FX/node.yaml
+ kubectl get node ip-172-31-44-117 -o yaml
+ '[' -z  ]
+ grep -q 'node-role.kubernetes.io/etcd: "true"' /host/var/lib/rancher/agent/tmp/tmp.lqtiGhf0FX/node.yaml
+ '[' -z  ]
+ grep -q 'node-role.kubernetes.io/controlplane: "true"' /host/var/lib/rancher/agent/tmp/tmp.lqtiGhf0FX/node.yaml
+ '[' -z  ]
+ grep -q 'node-role.kubernetes.io/control-plane: "true"' /host/var/lib/rancher/agent/tmp/tmp.lqtiGhf0FX/node.yaml
+ '[' -z  ]
+ grep -q 'node-role.kubernetes.io/worker: "true"' /host/var/lib/rancher/agent/tmp/tmp.lqtiGhf0FX/node.yaml
+ export 'CATTLE_AGENT_BINARY_LOCAL=true'
+ export 'CATTLE_AGENT_BINARY_LOCAL_LOCATION=/var/lib/rancher/agent/tmp/tmp.lqtiGhf0FX/rancher-system-agent'
+ chroot /host /var/lib/rancher/agent/tmp/tmp.lqtiGhf0FX/install.sh
[FATAL]  You must select at least one role
```

Other info: 
Role selected while registering the node was Worker only, UI shows it as All

**Comment by thedadams** [comment]
@ShylajaDevadiga I am not able to reproduce this issue. I was able to successfully join the worker node and all pods are in "Running" state.

**Comment by catastrophe-brandon** [comment]
Confirmed with `b395238`.  After bringing up the worker node all pods are in state `Running` including cattle-cluster-agent.

**Comment by catastrophe-brandon** [comment]
Also, for reference, screenshot showing completion of system-agent upgrader. ![Screen Shot 2021-08-02 at 5.45.58 PM.png](https://zube.io/files/rancher/e5fd5b1ff798938e526c001a0b9386a6-screen-shot-2021-08-02-at-5-45-58-pm.png)
