### ISSUE TITLE
Validate Logging v1 can run on k8s 1.22 clusters

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#33382]
Deploy Logging v1 onto 1.21 clusters and verify that there are no deprecation warnings in the local cluster as well as the downstream cluster.

Things to consider:
1. What is the impact on using Logging v1 on different cluster versions?
1. Would there need to be UI/UX changes if we need to make changes for k8s 1.22 support?

**Comment by nickgerace** [comment]
Logging v1 does work on k8s 1.22 and uses `v1` versions for all affected APIs

**Comment by deniseschannon** [comment]
v1 logging will not need to be supported on k8s 1.22 clusters. 

We have added a warning when creating/upgrading clusters with 1.22 and the legacy feature flag on as well as if you attempt to enable logging v1 on a k8s 1.22 cluster.
