### ISSUE TITLE
Additional CA certs not recognized in SLE image.

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#33398]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy Rancher behind a proxy with an additional CA certificate. (see [the docs](https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/chart-options/#additional-trusted-cas).
2. Go to Cluster Manager -> Catalogs

**Result:**
There should be errors regarding untrusted self-signed certificates.

**Expected Result:**
There should be no errors and the additional CA added as in the docs should be trusted.

**Other details that may be helpful:**
This is not an issue in 2.5.x because the base image is Ubuntu.

If one were to exec into the Rancher containers and run `c_rehash`, then the error will go away. Adding this command to https://github.com/rancher/rancher/blob/master/package/entrypoint.sh before starting Rancher is one option.

**Comment by snasovich** [comment]
@mvarlese & @dirkmueller , any thoughts / recommendations on fix approach since it's related to https://github.com/rancher/rancher/pull/33007 ?

**Comment by mvarlese** [comment]
I see the patch to run c_rehash has been approved but not merged yet.

I apologize but I am not too familiar with the Rancher stack. That said, considered SLE installs certificates in a different folder than what Ubuntu does, I think it makes sense to run c_rehash to create the sym links.

**Comment by dirkmueller** [comment]
The recommended way is to use `/etc/pki/trust/anchors/` as an installation path for custom system wide trusted CAs. running `update-ca-certificates` will do the necessary logic to refresh the bundles and add links. 

c_rehash runs might work but if for whatever reason `update-ca-certificates` (pki tools) will be executed your rehash run is lost.

**Comment by thedadams** [comment]
Thanks for the input, @dirkmueller. I have followed the documentation you posted.

**Comment by prabalsharma** [comment]
@thedadams is testing https://github.com/rancher/rancher/issues/31846 good enough for this (along with checking Cluster Manager -> Catalogs) ? or do you have some specific test case in mind?

**Comment by prabalsharma** [comment]
I guess checking Catalogs is good enough test case for this bug.

**Comment by prabalsharma** [comment]
tested on 9e0d1b2

<img width="1440" alt="Screen Shot 2021-07-22 at 1 17 16 PM" src="https://user-images.githubusercontent.com/3749546/126704039-1e63c5dc-88b3-4b12-9885-55308f2bd589.png">

not sure if there is a problem with my setup. I could deploy gke v2 cluster (with some issues https://github.com/rancher/rancher/issues/31846#issuecomment-885053870), so I guess my setup is correct.

**Comment by prabalsharma** [comment]
looks good

<img width="1267" alt="Screen Shot 2021-07-29 at 11 23 10 AM" src="https://user-images.githubusercontent.com/3749546/127545629-0ee85834-60bd-45cc-b52d-369d7b5ea035.png">
