### ISSUE TITLE
[Logging v1] Switch to latest versioning model for Ruby in rancher/fluentd for Linux

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#33390]
QA Validation for this issue involves ensuring that `rancher/fluentd` works as intended compared to previous image tags.

**Comment by nickgerace** [comment]
This is blocked by Windows build failures, and may receive help from @rosskirkpat @phillipsj here to help fix and update the Windows Dockerfile.

**Comment by nickgerace** [comment]
Update @rosskirkpat has identified a new MSYS2 version as the likely suspect for the Windows image.

**Comment by sowmyav27** [comment]
Will be validated as part of issue - https://github.com/rancher/rancher/issues/33486
