### ISSUE TITLE
Rancher not working - error syncing

### ISSUE THREAD

**Issue by VirajAttanayake** [rancher/rancher#33408]
I Install Rancher in my K8 cluster which I installed using kubeadm. But I'm unable to get is it working with below error logs. I login to the container and found it doesn't have access to internet. 

Im using Calico as overlay network.

K8 - v1.21.2 running.
Ranche version - rancher/rancher:v2.5.8

2021/06/29 10:32:32 [INFO] namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-2htkg to namespace=kube-system
2021/06/29 10:32:32 [ERROR] error syncing 'local/p-2htkg': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:32 [ERROR] error syncing 'local/p-2htkg': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:32 [ERROR] error syncing 'local/p-chh9p': handler system-image-upgrade-controller: upgrade cluster local system service logging failed: get template system-library-rancher-logging failed: catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found, requeuing
2021/06/29 10:32:32 [ERROR] error syncing 'local/p-chh9p': handler system-image-upgrade-controller: upgrade cluster local system service logging failed: get template system-library-rancher-logging failed: catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found, requeuing
2021/06/29 10:32:32 [ERROR] error syncing 'local/p-2htkg': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:32 [ERROR] error syncing 'local/p-chh9p': handler system-image-upgrade-controller: upgrade cluster local system service logging failed: get template system-library-rancher-logging failed: catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found, requeuing
2021/06/29 10:32:32 [ERROR] error syncing 'local/p-2htkg': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:32 [ERROR] error syncing 'local/p-chh9p': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:33 [ERROR] error syncing 'local/p-2htkg': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:33 [ERROR] error syncing 'local/p-chh9p': handler system-image-upgrade-controller: upgrade cluster local system service logging failed: get template system-library-rancher-logging failed: catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found, requeuing
2021/06/29 10:32:33 [ERROR] error syncing 'local/p-2htkg': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:33 [ERROR] error syncing 'local/p-chh9p': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:35 [ERROR] error syncing 'local/p-2htkg': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:35 [ERROR] error syncing 'local/p-chh9p': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:35 [WARNING] failed to refresh data from upstream https://releases.rancher.com/kontainer-driver-metadata/release-v2.5/data.json: driverMetadata err Get "https://releases.rancher.com/kontainer-driver-metadata/release-v2.5/data.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Fallback to refresh from local file path /var/lib/rancher-data/driver-metadata/data.json
2021/06/29 10:32:35 [INFO] Retrieve data.json from local path /var/lib/rancher-data/driver-metadata/data.json
2021/06/29 10:32:37 [ERROR] error syncing 'local/p-2htkg': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:37 [ERROR] error syncing 'local/p-chh9p': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:42 [ERROR] error syncing 'local/p-2htkg': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:42 [ERROR] error syncing 'local/p-chh9p': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:45 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
fatal: unable to access 'https://git.rancher.io/helm3-charts/': Could not resolve host: git.rancher.io
: exit status 128, requeuing
2021/06/29 10:32:45 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/df6f64f73bb427a3c62ced202ca09db9cf9f2547296217da13a2eb43d5cf5c08'...
fatal: unable to access 'https://git.rancher.io/system-charts/': Could not resolve host: git.rancher.io
: exit status 128, requeuing
2021/06/29 10:32:45 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
fatal: unable to access 'https://git.rancher.io/charts/': Could not resolve host: git.rancher.io
: exit status 128, requeuing
2021/06/29 10:32:53 [ERROR] error syncing 'local/p-2htkg': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:32:53 [ERROR] error syncing 'local/p-chh9p': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:33:05 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
fatal: unable to access 'https://git.rancher.io/helm3-charts/': Could not resolve host: git.rancher.io
: exit status 128, requeuing
2021/06/29 10:33:05 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/df6f64f73bb427a3c62ced202ca09db9cf9f2547296217da13a2eb43d5cf5c08'...
fatal: unable to access 'https://git.rancher.io/system-charts/': Could not resolve host: git.rancher.io
: exit status 128, handler system-image-upgrade-catalog-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:33:05 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
fatal: unable to access 'https://git.rancher.io/charts/': Could not resolve host: git.rancher.io
: exit status 128, requeuing
2021/06/29 10:33:09 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-mhhgc failed, watch closed
2021/06/29 10:33:13 [ERROR] error syncing 'local/p-2htkg': handler system-image-upgrade-controller: upgrade cluster local system service logging failed: get template system-library-rancher-logging failed: catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-logging" not found, requeuing
2021/06/29 10:33:13 [ERROR] error syncing 'local/p-chh9p': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:33:25 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
fatal: unable to access 'https://git.rancher.io/helm3-charts/': Could not resolve host: git.rancher.io
: exit status 128, requeuing
2021/06/29 10:33:25 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/df6f64f73bb427a3c62ced202ca09db9cf9f2547296217da13a2eb43d5cf5c08'...
fatal: unable to access 'https://git.rancher.io/system-charts/': Could not resolve host: git.rancher.io
: exit status 128, handler system-image-upgrade-catalog-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
2021/06/29 10:33:25 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
fatal: unable to access 'https://git.rancher.io/charts/': Could not resolve host: git.rancher.io
 

------------------------------------------------------------------------------------------

Name:         rancher-6bcc7cc457-jx9m4
Namespace:    cattle-system
Priority:     0
Node:         mzworker2/10.222.22.47
Start Time:   Tue, 29 Jun 2021 10:30:59 +0000
Labels:       app=rancher
              pod-template-hash=6bcc7cc457
              release=rancher
Annotations:  cni.projectcalico.org/podIP: 192.168.38.67/32
              cni.projectcalico.org/podIPs: 192.168.38.67/32
Status:       Running
IP:           192.168.38.67
IPs:
  IP:           192.168.38.67
Controlled By:  ReplicaSet/rancher-6bcc7cc457
Containers:
  rancher:
    Container ID:  docker://d4be6bff67f0175e567c9e039e466b67d343df3882bee595e9527bb5e978a5c7
    Image:         rancher/rancher:v2.5.8
    Image ID:      docker-pullable://rancher/rancher@sha256:9401cf1e8d8d826e382ffcd1628abff8e1c2769175197f99aef192dc73fc5f08
    Port:          80/TCP
    Host Port:     0/TCP
    Args:
      --no-cacerts
      --http-listen-port=80
      --https-listen-port=443
      --add-local=true
    State:          Running
      Started:      Tue, 29 Jun 2021 10:31:45 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:80/healthz delay=60s timeout=1s period=30s #success=1 #failure=3
    Readiness:      http-get http://:80/healthz delay=5s timeout=1s period=30s #success=1 #failure=3
    Environment:
      CATTLE_NAMESPACE:     cattle-system
      CATTLE_PEER_SERVICE:  rancher
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-g6dng (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-api-access-g6dng:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  21m   default-scheduler  Successfully assigned cattle-system/rancher-6bcc7cc457-jx9m4 to mzworker2
  Normal   Pulling    21m   kubelet            Pulling image "rancher/rancher:v2.5.8"
  Normal   Pulled     21m   kubelet            Successfully pulled image "rancher/rancher:v2.5.8" in 23.618969776s
  Normal   Created    20m   kubelet            Created container rancher
  Normal   Started    20m   kubelet            Started container rancher
  Warning  Unhealthy  20m   kubelet            Readiness probe failed: Get "http://192.168.38.67:80/healthz": dial tcp 192.168.38.67:80: connect: connection refused
[root@mzmaster ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by superseb** [comment]
Rancher is running on and using the Kubernetes cluster, if it does not have outbound connectivity, things will not work but fixing this will require fixing/troubleshooting kubeadm so I would advice building your kubeadm cluster and testing manually if you have network connectivity and fix that before installing Rancher. You can still use https://rancher.com/docs/rancher/v2.5/en/troubleshooting/networking/ to troubleshoot networking and https://rancher.com/docs/rancher/v2.5/en/troubleshooting/dns for DNS.

Else you can follow https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/
