### ISSUE TITLE
Can't turn off pull_image

### ISSUE THREAD

**Issue by elerion** [rancher/rancher#3340]
Hi,

When I create a container I unchecked "Always pull image before creating" But in the labels I have :

System	io.rancher.container.pull_image	always

And my container not start because my image does not exist to docker hub.

**Comment by tpenne** [comment]
I encountered the same problem.
The label is set to "always" even if the checkbox is unchecked which implies that rancher tries to find the image at a remote location and of course does not find it. The result is that container does not start with error ~ "Image cannot be found".

**Comment by tpenne** [comment]
But I managed to find a workaround. You just need to : 
* uncheck the checkbox as you already do 
* manually add  the label io.rancher.container.pull_image (in advanced options) with value "never"

Value is then left as it is and image is locally retrieved

**Comment by deniseschannon** [comment]
Reproduced with v0.56.0-rc1.

**Comment by tfiduccia** [comment]
Version - master ui 1/22
Verified fixed

**Comment by wiredaem0n** [comment]
Issue still persist in the new version. 

 Image [index.docker.io/local/grr-lzd] failed to pull: repository docker.io/local/grr-lzd not found:

Have unchecked the box and also set label  i**o.rancher.container.pull_image: never**

It just keeps trying to pull and download image everytime. 

Is there something else I need to do to turn off the pull_image?
