### ISSUE TITLE
Ability to specify network tags for node pools in GKE cluster (2.6.0/1)

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#33416]
https://github.com/rancher/rancher/issues/33406 has a backend fix for GKE and network tags that we need to incorporate into the UI.

It is believed that this is a quick fix that could make it into 2.6.0 but if not, 2.6.1 can be considered.

**Comment by westlywright** [comment]
I haven't been able to fully round trip test but the PR is up in review. The logic isn't complicated so I don't suspect any issues.

**Comment by snasovich** [comment]
Please note that Tags can only be set on create, so they should be read-only on edit forms.
https://github.com/rancher/gke-operator/pull/60#issuecomment-872665710
