### ISSUE TITLE
[agent-instance] can't start on CentOS7 with docker 1.9.1 overlay

### ISSUE THREAD

**Issue by yinchuan** [rancher/rancher#3341]
```
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
```

error output
```
Error response from daemon: mkdir /var/lib/docker/overlay/50f70b98c720bd56618e298b13231e1f086cab58813e9568e210b473a4ce7e09-init/merged/dev/shm: invalid argument
```

Obviously, this is related to [docker run fails with "invalid argument" when using overlay ](https://github.com/docker/docker/issues/10294).

Is any plan to support CentOS7?

**Comment by ibuildthecloud** [comment]
@yinchuan What version of CentOS are you using?  All our CentOS users are running devmapper.  Does CentOS support overlay now?

**Comment by yinchuan** [comment]
CentOS Linux release 7.1.1503 (Core)

On Tue, Jan 26, 2016 at 5:42 AM, Darren Shepherd <notifications@github.com>
wrote:

> @yinchuan <https://github.com/yinchuan> What version of CentOS are you
> using? All our CentOS users are running devmapper. Does CentOS support
> overlay now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rancher/rancher/issues/3341#issuecomment-174677947>.
>



-- 
尹川 架构组SA
QQ: 254113859
微信: $QQ
Google Plus: yinchuan.blue@gmail.com

**Comment by deniseschannon** [comment]
@yinchuan Does CentOS support overlay now?

**Comment by yinchuan** [comment]
Accord to [CentOS 7 Release note](https://wiki.centos.org/Manuals/ReleaseNotes/CentOS7#head-b02657cf2e223edb2d7946cbc45086d42c2bb41b), CentOS 7 support overlay with `Technology Preview`.

> Technology Preview: Support of the Btrfs file system, OverlayFS, DNSSEC, kpatch, virt-p2v tool and the Cisco VIC kernel driver

So, I think using Device Mapper as graph driver is better for now.
