### ISSUE TITLE
Validate RHEL 8.4 in v2.5.x

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#33410]
Same as https://github.com/rancher/rancher/issues/32830 for v2.5.x

**Comment by anupama2501** [comment]
Verified on v2.5-head commit ID `ad21cffd`

1. Created a rancher HA server with local RHEL 8.4 nodes 
2. As a standard user created a downstream node driver rke1 aws cluster. with 3 worker, 1 etcd,1 cp - validation tests have passed
3. created a custom RHEL cluster and node driver RHEL cluster with 3 worker, 1 etcd, 1 cp - validation tests have passed.

**Comment by izaac** [comment]
Backport issue of Logging v1 for `v2.5`
https://github.com/rancher/rancher/issues/34770

**Comment by anupama2501** [comment]
v1/v2 charts are validated.  Seeing an issue for logging.
Closing this issue as for logging the above linked issued has been logged.

**Comment by izaac** [comment]
Not related to RHEL 8.4 as this was also checked on Ubuntu 18.04 
Logging v2 issue: https://github.com/rancher/rancher/issues/34772
