### ISSUE TITLE
While provisioning rke2 custom cluster, taints have invalid format

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rancher#33419]
Using rancher master-head commit id c7f3cce
While provisioning rke2 custom cluster on AWS/DO, taints fail to be applied on the cluster due to invalid format stored in config
Follow the steps to reproduce to create the cluster.

Value stored in config
```
"node-taint": [
    "key1=value1=NoSchedule:"
  ],
```
Logs:

```
Jun 24 20:49:54 shyubu rke2[1375]: E0624 20:49:54.440717    1375 server.go:156] "Failed to parse kubelet flag" err="invalid argument \"key1=value1=NoSchedule:\" for \"--register-with-taints\" flag: invalid t
aint effect: , unsupported taint effect"
```
Format when taint is applied on a standalone rke2 node as seen in logs is as below
```
--register-with-taints=key1=value1:NoSchedule
```

**Comment by davidnuzik** [comment]
**Reproduction:**
Not required.

**Validation Successful:**
Rancher version: master-head `b39523882` 8/2/21
Rancher cluster type: single-node docker
Docker version: 19.03

Downstream cluster type: rancher-provisioned rke2 custom cluster
Downstream K8s version: v1.21.3-rc1+rke2r2

Validation steps:
1. Provision an rke2 custom cluster in the dashboard UI. Create a separate pool for workers with a taint on it.
![image](https://user-images.githubusercontent.com/45179589/128066232-72b8f3d3-c42d-4b53-9f09-0f3341c3a8fa.png)

During this process, I observed no issues in the UI or in the rancher server logs as reported originally in the issue (issue appears fixed so far).

2. Once the cluster is ready, inspect the tainted worker node in the UI.
I noticed that the node yaml appears correct (snippet below):
```
metadata:
  annotations:
    rke.cattle.io/taints: '[{"key":"testtaint","value":"true","effect":"PreferNoSchedule"}]'
  creationTimestamp: "2021-08-03T18:22:04Z"
```
I also checked the node in the UI and the taint was successfully applied.
Last, I checked the rke2.io/node-args annotation on the worker in this pool with this taint and it looks correct:
```
[
  "agent",
  "--node-label",
  "rke.cattle.io/machine=76a86ae5-439a-42ac-a9aa-7d192f7cfe06",
  "--node-taint",
  "testtaint=true:PreferNoSchedule",
  "--server",
  "https://REDACTED:9345",
  "--token",
  "********"
]
```

**Comment by davidnuzik** [comment]
Reopening. This is not the proper way to test rke2 custom clusters -- At the time I had closed this I had mistook and rke2 node driver for an rke2 custom cluster :)
I will re-check appropriately this time and then close out if this passes my checks.

**Comment by davidnuzik** [comment]
**Reproduction:**
Not required.

**Validation Successful:**
Rancher version: v2.6-head `7b9a232ac` 8/6/21 2:12pm Pacific
Rancher cluster type: single-node rancher server in docker container
Docker version: 19.03

Downstream cluster type: Custom cluster - rke2
Downstream K8s version: v1.21.3-rc4+rke2r2

Validation steps:
1. Provision an rke2 custom cluster in the dashboard UI. On the 2nd step, click on "Advanced Options" and you'll see the fields for node labels and taints.
![image](https://user-images.githubusercontent.com/45179589/128581417-542b7874-5a08-4e2f-b431-ee4247315db4.png)

2. Set some labels and taints, provision the custom node(s). SSH in and cat `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` we can see that the node labels and taints specified took as per my specifications in the UI:

```
"node-label": [
    "apples=drool",
    "cattle.io/os=linux",
    "rke.cattle.io/machine=6592aaab-eca1-4111-ae2a-2fe6c880a9de",
    "tacos=rule"
  ],
```

```
"node-taint": [
    "bye=byebye:NoSchedule",
    "hi=ohai:NoSchedule",
    "tacos=yesplease:NoSchedule"
  ],
```
