### ISSUE TITLE
[backport 2.5] Ability to specify network tags for node pools in GKE cluster

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#33415]
https://github.com/rancher/rancher/issues/33406 will incorporate a backend fix for network tags on GKE.

We need this for the Ember UI in 2.5.10 (and a separate ticket for 2.6.0 or 2.6.1)

**Comment by westlywright** [comment]
I haven't been able to fully round trip test but the PR is up in review. The logic isn't complicated so I don't suspect any issues.

**Comment by cbron** [comment]
Whats status of this one ?

**Comment by deniseschannon** [comment]
@cmurphy Did we backport the backend into 2.5.10?

**Comment by deniseschannon** [comment]
The UI looks to be merged but we want to confirm that this was updated in the backend.

**Comment by deniseschannon** [comment]
Based on this backport issue, it looks as if we never moved this to testbut it was tested by QA: 

https://github.com/rancher/rancher/issues/33458#issuecomment-891986125

**Comment by cmurphy** [comment]
That issue was moved to test 
![Screenshot_20210901_134557](https://user-images.githubusercontent.com/1220710/131742672-60c580ec-43f4-47d0-813f-2ddc2f25d02a.png)
