### ISSUE TITLE
Validate Oracle Linux 8.4 in v2.5.x

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#33411]
Same as https://github.com/rancher/rancher/issues/32914 for v2.5.x

**Comment by davidnuzik** [comment]
Area's I've been indicated to check:

- Deploy HA on RKE with OS nodes and deploy a downstream cluster, run validation tests
- Deploy a downstream cluster with OS nodes - both Node driver and Custom cluster (RKE1 clusters) and run validation tests
- v1/v2 charts - P0 usecase

**Comment by davidnuzik** [comment]
Validated and mostly passed. Automation tests pass, most manual checks pass. Some issues identified during the team's charts testing:
https://github.com/rancher/rancher/issues/35017
https://github.com/rancher/rancher/issues/34772#issuecomment-932528149 (that issue affects RHEL 8.4 as well)
