### ISSUE TITLE
aksv2 - upgrading CP's k8s version along with adding a NP, throws error

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33426]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create AKS cluster from Rancher UI with k8s version 1.19.9
2. Once the cluster is active, go to edit
3. Change k8s version of cluster to 1.20.5
4. Add a NP (the version will automatically be set to 1.20.5)
5. Save

**Result:**
```
Failed to update cluster: containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="NodePoolMcVersionIncompatible" Message="Node pool version 1.20.5 and control plane version 1.19.9 are incompatible. Minor version of node pool version 20 is bigger than control plane version 19. For more information, please check https://aka.ms/version-skew-policy"
```
**Expected Result:**
This can be fixed from UI side by keeping the k8s version of new NP to match the existing k8s version of cluster. However, I think the true cause of this error has to do with the sequence of update.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-7a2fc74f9598b41b98f2ac5d644a677d29e83e45-head
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `1a57856 `**

- Create AKS cluster from Rancher UI with k8s version 1.20
- Once the cluster is active, go to edit
- Change k8s version of cluster to 1.21
- Add a NP (the version will automatically be set to 1.21)
- CLuster comes up Active. Nde comes up active with k8s 1.21
