### ISSUE TITLE
Include the cattle-fleet-system namespace in backup-restore-operator

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#33428]
**What kind of request is this:**
bug

**Steps to reproduce:**

the new `cattle-fleet-system` move on master-head is not included in the backup namespaces regex in backup-restore-operator

https://github.com/rancher/backup-restore-operator/blob/master/charts/rancher-backup/files/default-resourceset-contents/fleet.yaml#L3

previously the `fleet-system` namespace was used by fleet

**Result:**

- Namespace won't make it to the backup

**Expected Result:**

- Add `cattle-fleet-system` in the regexes and make sure the backup includes this namespace resources in the backup

Related: https://github.com/rancher/fleet/issues/395

**Comment by jiaqiluo** [comment]
can be tested in rancher-backup chart 2.0.0+up2.0.0-rc3

**Comment by anupama2501** [comment]
Verified on single install rancher master-head 0a0d07a
1. Create2 rke2 node driver cluster with 1 node all roles
2. From local --> apps and market install rancher-backups with S3 compatible object details provided.
3. From continuous delivery --> git repo, create a git repo fleet1.
4. Take a backup of the current state from local --> apps --> backup
5. Create a new git repo from continuous delivery --> git repo fleet2
6. From local --> apps --> restore from the backup taken in step4
7. Once the cluster is active, verified the fleet1 only exists.
