### ISSUE TITLE
Remove experimental rancherd asset

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#33423]
Currently, Rancher ships with a rancherd asset which was an experimental way of installing Rancher introduced in Rancher v2.5. 

As we are looking to define the exact use case and implementation of this asset, we have decided it needs to be updated and re-architected and are looking to remove the experimental ability of this installation.

**Comment by sowmyav27** [comment]
To validate:

On an RC, verify the RancherD assets is not generated.

**Comment by cbron** [comment]
Only deleting asset, nothing else

**Comment by jiaqiluo** [comment]
The build process should not publish any rancherd assets now in the master branch

**Comment by cbron** [comment]
Assigning @rmweir for dev-validate

**Comment by cbron** [comment]
Assigning @brendarearden for dev-validate

**Comment by deniseschannon** [comment]
Available to test in v2.6.0-rc1

**Comment by brendarearden** [comment]
Validation: PASSED

Steps to Reproduce: 

1. Go to a previous release tag, in this case [v2.5.9](https://github.com/rancher/rancher/releases/tag/v2.5.9). 
2. Check the assets list for `rancherd-amd64` and `rancherd-amd64.tar.gz` 
3. See that the assets are available in the Assets list.

![Screen Shot 2021-08-05 at 9 02 14 AM](https://user-images.githubusercontent.com/19455540/128382832-b17ad5f6-48a7-4013-b64b-96f3eb2f5596.png)

Steps to Test: 

1. Go to the [v2.6.0-rc1](https://github.com/rancher/rancher/releases/tag/v2.6.0-rc1) tag.
2. Check the assets list for `rancherd-amd64` and `rancherd-amd64.tar.gz` 
3. See that the assets are no longer list in the Assets list. 

![Screen Shot 2021-08-05 at 9 14 54 AM](https://user-images.githubusercontent.com/19455540/128384570-acdd562d-e05b-49d3-a5fb-e84cfc77d9a1.png)
