### ISSUE TITLE
[Forwardport] GlobalRoleBinding deletion by garbagecollector causing panic in rancher-webhook

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33430]
forward port ticket for the issue: https://github.com/rancher/rancher/issues/33429

**Comment by ryansann** [comment]
This won't get tested yet as these changes were made to rancher/webhook:master and we haven't released from that branch yet

**Comment by anupama2501** [comment]
Changing the status back to `re-opened` based on the above comment

**Comment by ryansann** [comment]
There is a new rancher-webhook chart on `rancher/charts:dev-v2.6` that can be used to test this. The new webhook chart is: `rancher-webhook-1.0.0+up0.2.0-alpha03`

**Comment by anupama2501** [comment]
Verified on master-head be7cdb8, rancher webhook version: `rancher/rancher-webhook:v0.2.0-alpha04`
1. Created a global role g1 with verbs `Create` and resource `Authconfigs`
2. Created a standard user and assigned the role g1 to the user
3. Added the env variable `Rancher_DEBUG=true` in the rancher webhook
4. Deleted the global role and verified no panics are seen and the role is deleted from rancher server.
