### ISSUE TITLE
rancher/system-agent-installer-k3s:v1.21.2-k3s1 Image missing in dockerhub

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#33443]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Using master-head, attempt to create a k3s node-driver cluster through Digital Ocean

**Result:**
Cluster is stuck in provisioning. Looking into the logs (`journalctl -eu rancher-system-agent -f`) appears to show why:
```
Jun 30 19:00:35 maxk3sace-maxk3sace-tpmk7 rancher-system-agent[1427]: time="2021-06-30T19:00:35Z" level=error msg="error while staging: GET https://index.docker.io/v2/rancher/system-agent-installer-k3s/manifests/v1.21.2-k3s1: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v1.21.2-k3s1]: failed to get image index.docker.io/rancher/system-agent-installer-k3s:v1.21.2-k3s1"
Jun 30 19:00:35 maxk3sace-maxk3sace-tpmk7 rancher-system-agent[1427]: time="2021-06-30T19:00:35Z" level=error msg="error syncing 'fleet-default/maxk3sace-bootstrap-template-67xb2-machine-plan': handler secret-watch: error applying plan: error executing instruction 0: GET https://index.docker.io/v2/rancher/system-agent-installer-k3s/manifests/v1.21.2-k3s1: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v1.21.2-k3s1]: failed to get image index.docker.io/rancher/system-agent-installer-k3s:v1.21.2-k3s1, requeuing"
```

**Expected Result:**
Cluster creates and k3s is running.

**Other details that may be helpful:**
The image is present for v1.21.1 and v1.21.2-rc1, but appears has not been pushed for v1.21.2 release yet: https://hub.docker.com/r/rancher/system-agent-installer-k3s/tags?page=1&ordering=last_updated&name=v1.21.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head `6757965`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Digital Ocean k3s
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 2vcpu-4gb
- Kubernetes version (use `kubectl version`): `v1.21.2+k3s1`

**Comment by Oats87** [comment]
This is addressed by:
https://github.com/k3s-io/k3s/issues/3581 and https://github.com/k3s-io/k3s/issues/3582

Notably, we only have this capability for 1.21 K3s and forward, so new releases for `1.19`/`1.20` and such will not automatically cut these images.

**Comment by rancher-max** [comment]
#### Tested using master-head commit: `7738b25`

Now the version is v1.21.3-k3s1, but the error is the same so reopening:
```
Jul 27 17:26:32 maxk3sv2-maxp2-5ljqt rancher-system-agent[1425]: time="2021-07-27T17:26:32Z" level=info msg="Extracting image docker.io/rancher/system-agent-installer-k3s:v1.21.3-k3s1 to directory /var/lib/rancher/agent/work/20210727-172632-applied.plan/14a640345fa1f681c5c04ba4b59677dafb714de41148fd99ee22405a47537398_0"
Jul 27 17:26:32 maxk3sv2-maxp2-5ljqt rancher-system-agent[1425]: time="2021-07-27T17:26:32Z" level=info msg="Pulling image index.docker.io/rancher/system-agent-installer-k3s:v1.21.3-k3s1"
Jul 27 17:26:33 maxk3sv2-maxp2-5ljqt rancher-system-agent[1425]: time="2021-07-27T17:26:33Z" level=error msg="error while staging: GET https://index.docker.io/v2/rancher/system-agent-installer-k3s/manifests/v1.21.3-k3s1: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v1.21.3-k3s1]: failed to get image index.docker.io/rancher/system-agent-installer-k3s:v1.21.3-k3s1"
Jul 27 17:26:33 maxk3sv2-maxp2-5ljqt rancher-system-agent[1425]: time="2021-07-27T17:26:33Z" level=error msg="error syncing 'fleet-default/maxk3sv2-bootstrap-template-g78jd-machine-plan': handler secret-watch: error applying plan: error executing instruction 0: GET https://index.docker.io/v2/rancher/system-agent-installer-k3s/manifests/v1.21.3-k3s1: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v1.21.3-k3s1]: failed to get image index.docker.io/rancher/system-agent-installer-k3s:v1.21.3-k3s1, requeuing"
```

**Comment by rancher-max** [comment]
This is not automated and we just need to do it every release due to cross-org things. @Oats87 cut the new build and it is working correctly now. I will close this out and ensure it is part of post-release checks with KDM pushes.
