### ISSUE TITLE
Can't explore v1.21 k8s RKE1 clusters using cri-dockerd from Dashboard on latest master build

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#33445]
Rancher version: `2.6 master-head (06/30/2021)` _c1151f6_

Provision an RKE cluster with k8s **v1.21.1**
I tried DigitalOcean and Amazon EC2 node drivers.
1 etcd, 1 Control Plane, 3 workers
`enable_cri_dockerd: true`

Result:

`failed to find Session for client steve-cluster-c-jb7r9`

<img width="987" alt="Screen Shot 2021-06-30 at 12 35 02 PM" src="https://user-images.githubusercontent.com/27659/124021096-ff3ac080-d99f-11eb-86a6-07de8673ad5f.png">

**Comment by izaac** [comment]
Clusters with k8s 1.21 and `enable_cri_dockerd: false` are also working in the same Rancher build `2.6 master-head (06/30/2021)` _c1151f6_

**Comment by superseb** [comment]
@izaac This does not seem to happen on current `master-head`, can you try again and share the setup if you hit it again?

**Comment by izaac** [comment]
@superseb sure I will try the scenario again today

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/14/2021)` _8073489_

@superseb I can't explore it with `enable_cri_dockerd: true` I see the cluster objects (cluster, nodes, pools) from cluster management but Explore the k8s namespaces, projects and other things is not available.

- See the greyed out `Explore` button and the navigation menu the cluster isn't clickable.

![Screen Shot 2021-07-14 at 10 55 41 AM](https://user-images.githubusercontent.com/27659/125670043-1f7e2899-263e-42cd-961b-b6bc0c50b096.png)

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/15/2021)` _e83ac8c_

After taking a closer look I think I ran into this other symptom where the cluster's cattle-cluster-agent couldn't resolve the route53 DNS https://github.com/rancher/rancher/issues/33272 

After the cattle-cluster-agent got active I was able to Explore the cluster from Dashboard

**Comment by izaac** [comment]
Ok #33272 has a broader version spectrum. With this issue I was able to reproduce the problem consistently with clusters using k8s 1.21.1 and `enable_cri_dockerd: true` so there might be a different root cause triggering the issue.

Reopening.

Rancher version: `2.6 master-head (07/15/2021)` _e83ac8c_

**Comment by kinarashah** [comment]
waiting for new k8s versions with latest `rke-tools`.

**Comment by izaac** [comment]
Rancher version: `2.6-head (08/03/2021)` _6c14c33_

Tested on:

SELinux ON Docker
- Docker 19.03.15
- Docker 20.10.7
- `enable_cri_dockerd: true`

- RHEL 8.4
- Oracle Linux 8.3 and 7.9
- CentOS 8.3 and 7.9


Checked with different Network providers Flannel, Weave, Calico, Canal.

I am able to navigate to the Clusters details and other areas from Dashboard now.
