### ISSUE TITLE
aks v2 sync - updating k8s version of 'NP with autoscaling' from Azure, causes error

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33446]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy AKS cluster - 1.19.9
2. **Enable Autoscaler for NP**
3. Save and wait for it to become active
4. Go to Azure and **upgrade k8s version** of CP **and NP** to 1.20.5
5. Check Rancher UI for error

**Result:**
```
Can't update node count when autoscaling is enabled in node pool [agentpool] for cluster [aks3]
```

**Expected Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-7a2fc74
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by mjura** [comment]
This is proper message from Azure cloud, AKS doesn’t allow you to upgrade the node pool while NP autoscaler is on.

We should update documentation and put info about it

**Comment by prabalsharma** [comment]
> This is proper message from Azure cloud, AKS doesn’t allow you to upgrade the node pool while NP autoscaler is on.
> 
> We should update documentation and put info about it

This is an error form Rancher

**Comment by mjura** [comment]
Fix for it
https://github.com/rancher/aks-operator/pull/37

**Comment by snasovich** [comment]
@cbron , could you clarify what's expected from @thedadams . This one is already in review.

**Comment by snasovich** [comment]
@rmweir , please help getting this over the finish line as Donnie is out this week. Thank you.

**Comment by prabalsharma** [comment]
passed on 21ab02c
