### ISSUE TITLE
[Rancher] Debian 10 docker image restart loop

### ISSUE THREAD

**Issue by Gugubaer** [rancher/rancher#33453]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
Install Debian 10 and Docker. apt update & apt full-upgrade to latest and reboot
Install Rancher via  docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher

**Result:**
docker ps shows restarting rancher container every 20 seconds

**Expected Result:**
running and accessible Rancher via https 

**Other details that may be helpful:**

**Environment information**
- uname -a
``` Linux TEST-RANCHER 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux ```

- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
single install / latest Rancher

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Just reboot to older Kernel 4.19.0-16, which was still installed, fix that problem. No other components got changed, only rebooted to older Kernel. Kernel 4.19.0-16-amd64 is not affected.

Best Regards,
Ingo

**Comment by superseb** [comment]
Probably the same as https://github.com/rancher/rancher/issues/33762, let me know if this is different
