### ISSUE TITLE
[Backport 2.5] Ability to specify network tags for node pools in GKE cluster

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#33458]
Backport to v2.5 for https://github.com/rancher/rancher/issues/33406

**Request description:**
Add network tags when adding node pools to a GKE cluster during provisioning and edit.

**Actual behavior:**
Can't specify tags when working with node pools in a GKE cluster through Rancher.

**Expected behavior:**

- When creating a GKE v2 cluster through the Rancher UI, a user should be able to specify 0 or more network tags to add to the nodes in a node pool. Mimicking the behavior in the GCP console.
- When creating a GKE v2 cluster through the API or TF provider, the user should be able to specify a list of 0 or more network tags.

**Additional notes:**
https://cloud.google.com/vpc/docs/add-remove-network-tags

_JIRA ID: SURE-3037_

**Comment by cmurphy** [comment]
Chart updated in https://github.com/rancher/system-charts/pull/500

**Comment by prabalsharma** [comment]
v2.5-0e587683fd86a24d25fb8d567c946d3edd867000-head

same as https://github.com/rancher/rancher/issues/33406#issuecomment-885902682

**Comment by prabalsharma** [comment]
tested on v2.5-07131035f51f3e264c114e9d9dde65aae37bdf4f-head

**Comment by prabalsharma** [comment]
looks like new argument needs to be added to tfp

```
Error: Unsupported argument

  on terra.tf line 48, in resource "rancher2_cluster" "prabal-tf2":
  48:         tags = ["http-server", "https-server"]

An argument named "tags" is not expected here.
```

**Comment by prabalsharma** [comment]
this is the new tfp issue https://zube.io/rancher/rancher/c/41711
