### ISSUE TITLE
EC2 instance created then terminated 

### ISSUE THREAD

**Issue by cloudlady911** [rancher/rancher#3345]
I created at instance using the EC2 option. The instance is created but I get the error:

>Error waiting for SSH: Too many retries waiting for SSH to be available. Last error: Maximum number of >retries (60) exceeded.

Then when I go back to the EC2 console, the instance is terminated. 

I discovered that it takes the "Name" of the instance and uses it as the Keypair name, therefore SSH will never work.

I posted this on the rancher forum: https://forums.rancher.com/t/ec2-instance-created-then-teminated/1495

I am running version 0.51.0 on an EC2 instance with and RDS database.
This problem is repeatable.

**Comment by cloudlady911** [comment]
Okay, I figured out the Naming thing. That is by design.  The Name field is actually meant for the KeyPair Name.  So each instance will have it own unique keypair.  So I will never be able to directly SSH into any of the instances.

However, that does not explain why the instance never connected via SSH.

**Comment by deniseschannon** [comment]
What AMI are you using? What OS is it? 

Depending on the OS, you might need to declare your user that you are logging in as. For example, if you using RancherOS, you need to be using the `rancher` user. 

As for directly SSH in, after the machine is configured, we provide the key to allow you to directly ssh in. 
http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/#accessing-hosts-from-the-cloud-providers

**Comment by cloudlady911** [comment]
I am using an ami that I created. It is a basic Ubuntu 14 with docker installed and configured with the Certificate for our private docker repository.  The user name is ubuntu and I did put that in the SSH User field.

**Comment by cloudlady911** [comment]
Perhaps it matters that the Rancher server and all the hosts that will be associated with it are in private subnets.

**Comment by vincent99** [comment]
The extent of Rancher's involvement is really that we call `docker-machine create`.  We run that from the `rancher/server` container, and then it creates a keypair (every time, whether you want it or not), deploys the instance and uses the key to login and install docker (and then eventually the Rancher agent).

So the basic problem is SSH communication from docker-machine in the `rancher/server` container to the newly created instance doesn't work.  It tries 60 times with a 3 second wait between them, so your image could take >3 min before SSH is up (unlikely for stock Ubuntu + a cert) or it's up but reachable for some reason.

**Comment by cloudlady911** [comment]
Is this a known problem?  Is there a work-around?  Both the new server and the Rancher server have SSH port open to each other.  Under Admin > Settings the site address I have is http://rancher.panosoft.com:8080.  Everything is running in private subnet and both servers have the rancher-machine security group with port 22 open to 0.0.0.0/0.  Is there something else I should check?

**Comment by cloudlady911** [comment]
it took 4.5 minutes from my instance to get up and running.  How do I change the timeout?

**Comment by cloudlady911** [comment]
I tried it with the RancherOS AMI.  After 15 minutes still nothing.  The image did boot faster.  I got the system logs and have attached them. Any idea what is going on here?
[SystemLog.txt](https://github.com/rancher/rancher/files/98551/SystemLog.txt)

**Comment by cloudlady911** [comment]
I checked on it 2 hours later.  The System Log had not changed and the Rancher interface still showed waiting.

**Comment by deniseschannon** [comment]
There's no way to change the timeout (at least form what I understand) as we are just calling a docker-machine command. 

Have you tried using `docker-machine` command to provision a host and SSH in to see if you have the same issue?

**Comment by cjellick** [comment]
I don't have anything new to add beyond denise and vincent's comments. Just leaving a comment so I can keep an eye on this issue in my inbox.

**Comment by deniseschannon** [comment]
@cloudlady911 If you were able to get this working with a direct `docker-machine` command, please re-open and we can investigate why it might not be working in Rancher. But as I mentioned earlier, we are just calling a docker-machine command.

**Comment by WoLfulus** [comment]
This is also happening here. How to properly launch an instance in EC2? I'm launching with ami provided by rancher.

**Comment by richbos** [comment]
Same here also. I have the relevant port (22) open in the rancher hosts ec2 security group allowing SSH for the rancher server ec2 security group. Using the rancheros AMI for the associated region and specifying the SSH user as rancher. Just get 'waiting for ssh to be available'.
Tried various combinations of placement for private/public subnets, security groups open for all ports between instances, a single open security group containing server/hosts granting all access to itself, but still no success.

**Comment by vincent99** [comment]
Are you settling the username to `rancher`??

**Comment by richbos** [comment]
Hi, yes - "_Using the rancheros AMI for the associated region and specifying the SSH user as rancher_"
