### ISSUE TITLE
Adding/removing taints to a node is causing cattle-cluster-agent container creation 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33466]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Pre-req:
Create an rke2 node driver cluster with 1 node all roles

1. From the explore cluster --> nodes --> edit page
2. Add taints with name:foo and value:bar

**Result:**
1. cattle-cluster-agent container pod is created every time a taint is added
2. Remove the taint and verify the previously created cattle-cluster-agent goes into terminating state and a new cattle-cluster-agent container is created.
3. Create three taints consecutively and each time previously created cattle-cluster-agent is terminated and a new one is created

**Expected Result:**
`cattle-cluster-agent` container pod should not be created every time a new taint is added.

**Other info:**
This is not always seen. Sometimes adding the taints, labels and annotation goes through without any error.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head c1151f6
- Installation option (single install/HA): Single 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider and Custom 
- Kubernetes version (use `kubectl version`): 

```
v1.21.2+rke2r1
```

**Comment by ShylajaDevadiga** [comment]
Closing this issue as duplicate as https://github.com/rancher/rancher/issues/33467 covers fails in adding/removing taints as well.
