### ISSUE TITLE
Unable to provision RKE2 cluster in master with separate etcd, controlplane, and worker nodes

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#33464]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Spin up a Rancher cluster based on master-head and try to provision an RKE2 cluster with 3 etcd, 1 controlplane, and 3 worker nodes.

**Result:**
Cluster is stuck provisioning forever

![Screen Shot 2021-07-01 at 2 33 20 PM](https://user-images.githubusercontent.com/13127443/124191875-4a74d200-da79-11eb-98ca-378a977fdac3.png)

**Expected Result:**
Should have finished provisioning like the cluster with 1 node that has all roles and 1 worker

![Screen Shot 2021-07-01 at 2 34 05 PM](https://user-images.githubusercontent.com/13127443/124191940-64aeb000-da79-11eb-944e-cdf26b3a5160.png)

**Other details that may be helpful:**

In the node that shows `Waiting for agent to check in and apply initial plan` in the above screenshot, I saw the following logs when I used `journalctl -n 100`:

```
:24
Jul 01 21:21:33 arvind-do-monitoring-v2-etcd-gzsl9 rke2[1574]: time="2021-07-01T21:21:33Z" level=info msg="Waiting for cloudcontroller rbac role to be created"
Jul 01 21:21:34 arvind-do-monitoring-v2-etcd-gzsl9 rke2[1574]: time="2021-07-01T21:21:34Z" level=info msg="Failed to set etcd role label: an error on the server (\"\") has prevented the request from succeeding (get customresourcedefinitions.apiextensions.k8s.io)"
Jul 01 21:21:35 arvind-do-monitoring-v2-etcd-gzsl9 rke2[1574]: time="2021-07-01T21:21:35Z" level=warning msg="servers addresses are not yet set"
Jul 01 21:21:40 arvind-do-monitoring-v2-etcd-gzsl9 rke2[1574]: time="2021-07-01T21:21:40Z" level=warning msg="servers addresses are not yet set"
Jul 01 21:21:44 arvind-do-monitoring-v2-etcd-gzsl9 rke2[1574]: time="2021-07-01T21:21:44Z" level=info msg="Failed to set etcd role label: an error on the server (\"\") has prevented the request from succeeding (get customresourcedefinitions.apiextensions.k8s.io)"
Jul 01 21:21:45 arvind-do-monitoring-v2-etcd-gzsl9 rke2[1574]: time="2021-07-01T21:21:45Z" level=warning msg="servers addresses are not yet set"
Jul 01 21:21:48 arvind-do-monitoring-v2-etcd-gzsl9 rke2[1574]: time="2021-07-01T21:21:48Z" level=info msg="Waiting for cloudcontroller rbac role to be created"
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head `671a4b1a0`
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4GB, 2CPU, 80GB disk for all 7 nodes
- Kubernetes version (use `kubectl version`): `v1.21.2+rke2r1`

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by deniseschannon** [comment]
Closing in favor of this issue: https://github.com/rancher/rancher/issues/32362
