### ISSUE TITLE
shell session and kubeconfig shell sessions are disconnected in a few minutes

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33468]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create 1 node rke2 node driver all roles cluster

-  Execute the kubectl shell/ ssh shell of the node and perform no action in the shell for a few seconds

**Result:**
With in a few seconds the shell gets disconnected with no error messages in the console

**Expected Result:**
The shell should not get disconnected within a few seconds/minutes. it should stay active as long as the user closes it.

**Other details that may be helpful:**

While executing into ssh shell, seeing the following errors in the console:
```
ContainerShell.vue:123 Failed to fetch node undefined
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head c1151f6
- Installation option (single install/HA): Single

**Comment by thedadams** [comment]
I am not seeing any disconnection after a few seconds in either of the Manager or Dashboard UIs.

I am seeing that the shell disconnects after 5 minutes of inactivity, regardless of whether I use the shell. After exactly 5 minutes of inactivity, the shell disconnects.

There is one caveat to this: if I focus on another window (like my IDE) and then go back to the shell (still without typing anything), the browser will send a message (`4eyJXaWR0aCI6MjUwLCJIZWlnaHQiOjQ5fQ==`) to the shell container in the cluster that will reset the timeout (see the messages in the screen capture below). If this is an issue that we should fix, it seems that the UI could send a ping message on the websocket every minute or so to keep the connection live.

![Screen Shot 2021-07-08 at 2 25 58 PM](https://user-images.githubusercontent.com/3682717/124992886-6daefc80-dff8-11eb-952f-1a7990e3faa2.png)

**Comment by cbron** [comment]
We can mark as won't fix if everyone is ok with this behavior. Seems fine to me. I know some people like long running shells but not end of the world to just restart, and since it's a pod it eats up resources.

**Comment by vincent99** [comment]
The `4ey…` message is to resize the terminal (`4` = "terminal operations" + base64(`{"Width":250,"Height":49}` == `4ey…`), which happens when you focus it.  Sending that as a "ping" is a little hacky but will work...

**Comment by anupama2501** [comment]
Verified on master-head 76b0695

Shell is not disconnected for both kubectl and shell for a long time.
