### ISSUE TITLE
Adding a taint/label/annotation fails as cattle-cluster-agent goes into creating state when a new taint is added

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33467]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Pre-req:
Create an rke2 node driver 1 node all roles cluster

1. From explore cluster --> nodes --> edit config and add a taint. 
2. While cattle-cluster-agent container pod goes into creating state, create any of the following operations:
- add a new taint
- remove existing taint
- add/remove new/existing label
- add/remove new/existing annotation

**Result:**
the operations fail when taints are added or removed

**Expected Result:**
The operation should not have failed while adding/ removing taints/toleration/annotation

**Other details that may be helpful:**
Error when the failure happens:
```
{"type":"error","links":{},"code":"ServerError","message":"Get \"https://10.43.0.1:443/apis/metrics.k8s.io/v1beta1/nodes/au-db-pool1-6srrb?timeout=15m0s\": context canceled","status":500,"type":"error"}
Error encountered while polling 
{data: "io: read/write on closed pipe", _status: 500, _statusText: "Internal Server Error", _headers: {…} …}
data: "io: read/write on closed pipe"
_status: 500
_statusText: "Internal Server Error"

{"data":"failed to find Session for client steve-cluster-c-m-78ba4000"}

Status Code: 500 Internal Server Error
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head c1151f6
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): /Infrastructure Provider and Custom

```
v1.21.2+rke2r1
```

**Comment by kinarashah** [comment]
Available to test once https://drone-publish.rancher.io/rancher/rancher/6040 passes.

**Comment by anupama2501** [comment]
Verified on master-head 21ab02c
On an rke2 node driver cluster with 1 cp+etcd and 1 worker
Created taints on worker nodes - works fine no restarts of the `cattle-cluster-agent` is seen

**Comment by anupama2501** [comment]
Re-opening this ticket:

on an HA setup 

- Edited the taints on etcd+cp node, `cattle-cluster-agent` container is seen terminating and going into creating state. 
- Cluster gives a failwhale for a few minutes and would start functioning again.
<img width="500" alt="Screen Shot 2021-07-28 at 5 48 10 PM" src="https://user-images.githubusercontent.com/38144301/127414526-18404e20-5167-4a89-9053-d240056bf7a8.png">
<img width="500" alt="Screen Shot 2021-07-28 at 5 46 26 PM" src="https://user-images.githubusercontent.com/38144301/127414535-479a1761-0a33-4780-81d8-e00370fd6e11.png">

**Comment by kinarashah** [comment]
@anupama2501 This is expected, we are changing tolerations for cluster-agent so the pods will redeploy.

**Comment by anupama2501** [comment]
verified on master-head b395238 for single node cluster and 1etcd_cp,1 worker node cluster
1. when taints are added only on worker node `cattle-cluster-agent` is not seen going to container creating or terminating state
2. When taints are added on etcd+cp nodes, `cattle-cluster-agent` is seen going to container creating or terminating state - This is expected as the `cattle-cluster-agent` is deployed on etcd_cp node. 
3. verified if taints are added on all roles node, container `cattle-cluster-agent` is seen going into updating and creating state.
4. Verified on all nodes taints are added/removed without any error

**Comment by lptarik** [comment]
I am using 2.6.9 and installing rke2 downstream cluster with 1 master and worker node but same issue.

![image](https://user-images.githubusercontent.com/17064457/199471074-27c76f82-1416-4a39-b538-27313f81fe67.png)

![image](https://user-images.githubusercontent.com/17064457/199471450-ada9a385-b5f7-48c7-b7f7-be9ec89e8c32.png)
