### ISSUE TITLE
Downstream clusters remain unavailable for a long time when rancher server restarts

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33470]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On the new UI, enable all cluster and node drivers
- Rancher server crashed.
- When the rancher server restarts, the down stream clusters are seen in `unavailable` state for a long time (2-3 hours) after which they come up Active.

**Result:**
- the down stream clusters are seen in `unavailable` state for a long time (2-3 hours) after which they come up Active.
- Logs from rancher server
```
2021/07/01 20:05:55 [ERROR] failed to start cluster controllers c-gq7l2: context canceled
2021/07/01 20:05:58 [ERROR] error syncing 'c-gq7l2': handler cluster-deploy: Get "https://<>:6443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": cluster agent disconnected, requeuing
```
- Logs of the downstream cluster's control plane node `k8s_cluster-register_cattle-cluster-agent-` container's logs
```
I0701 22:29:43.405835      53 leaderelection.go:243] attempting to acquire leader lease kube-system/cattle-controllers...
time="2021-07-01T22:29:43Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=Role controller"
time="2021-07-01T22:29:43Z" level=fatal msg="Embedded rancher failed to start: failed to ListenAndServe: listen tcp :443: bind: address already in use"
```

**Expected Result:**
Downstream clusters should go momentarily to Unavailable state and come back up Active

**Other details that may be helpful:**

- Happened after this issue - https://github.com/rancher/rancher/issues/33461
- might be related to this issue https://github.com/rancher/rancher/issues/33221

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head  commit id: `e546ffe`
- Installation option (single install/HA): Single

**Comment by Jono-SUSE-Rancher** [comment]
@sowmyav27 - wouldn't you consider this a duplicate of https://github.com/rancher/rancher/issues/33221? Because in this instance, you just waited and it looks like it just eventually came up.

**Comment by sowmyav27** [comment]
@Jono-SUSE-Rancher I am not sure if issue caused by restart and upgrade are the same one. I spoke to @kinarashah and logged this one. I will close this, if we find they both are in fact the same issue.

**Comment by sowmyav27** [comment]
Closing as this is closed - https://github.com/rancher/rancher/issues/33221 (similar to the other issue logged as rancher restarted)
