### ISSUE TITLE
Add k8s 1.20 as an option for EKS

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#33475]

**Comment by sowmyav27** [comment]
**On 2.5.9-rc6**

- 1.20, 1.19 are available while deploying a hosted EKS cluster.
- User is able to import a 1.19 EKS cluster and upgrade to 1.20 k8s

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `62dd3d` and on master-head commit id: `ac7cef3`**

- 1.20 is available while deploying a hosted EKSv2 cluster. - `v1.20.4-eks-6b7464`
- Import cluster (on 2.5head) works. User is able to edit and save changes made.
