### ISSUE TITLE
Cannot get Ingress working "like I always did" in the past

### ISSUE THREAD

**Issue by exocode** [rancher/rancher#33477]
This week I tried to install and use the current `rancher/rancher:stable` (which is the same as `rancher/rancher:latest`). On my "old" Rancher setup which I created two years ago, I had

```
18.09 docker
rancher1.13.4-rancher1-1
rancher server
v2.1.7
```
Everything is running on Hetzner Cloud.

**What kind of request is this (question/bug/enhancement/feature request):**

Question

Question: How to use Ingress (at Hetzner Cloud)

**Steps to reproduce (least amount of steps as possible):**

- Create a Rancher instance `rancher/rancher:stable`
- Not sure if this also happening on other platforms too
- install Node Driver `https://github.com/mxschmitt/ui-driver-hetzner`
TD/RL
```
Download URL | https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/3.3.0/docker-machine-driver-hetzner_3.3.0_linux_amd64.tar.gz
Custom UI URL | https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js
Whitelist Domains | storage.googleapis.com
```
- add a cluster with Hetzner API within Rancher
  - node: name system, count 1
  - node name worker, count 2
- kept all options default (like I always did)

<img width="1026" alt="Bildschirmfoto 2021-07-04 um 12 14 21" src="https://user-images.githubusercontent.com/1597621/124381189-64085a80-dcc1-11eb-9a48-436b80416a9f.png">

<img width="808" alt="Bildschirmfoto 2021-07-04 um 12 11 10" src="https://user-images.githubusercontent.com/1597621/124381116-0a079500-dcc1-11eb-9b44-00440dfa9e57.png">
<img width="1068" alt="Bildschirmfoto 2021-07-04 um 12 11 27" src="https://user-images.githubusercontent.com/1597621/124381122-0f64df80-dcc1-11eb-85a2-47faf780c8b4.png">
<img width="1018" alt="Bildschirmfoto 2021-07-04 um 12 11 37" src="https://user-images.githubusercontent.com/1597621/124381127-125fd000-dcc1-11eb-8218-1741c02fdf11.png">

I can see that there are new options added in "v2.5.8" compared to my old Rancher (v2.1.7) (like ingress)

- add workload `nginx` or `rancher/hello-world` with two pods
  - I tried `NodePort` (it is reachable, of course)
  - as well `ClusterIP`
- add an ingress pointing to that `workload` (I also tried `service`)
  - wait for xip.io address
- click the xip.io address

<img width="991" alt="Bildschirmfoto 2021-07-04 um 12 41 38" src="https://user-images.githubusercontent.com/1597621/124381928-37564200-dcc5-11eb-84e4-8ab5bfed4b6f.png">
<img width="991" alt="Bildschirmfoto 2021-07-04 um 12 41 13" src="https://user-images.githubusercontent.com/1597621/124381929-38876f00-dcc5-11eb-9042-0ff3d1d177d6.png">
<img width="986" alt="Bildschirmfoto 2021-07-04 um 12 42 29" src="https://user-images.githubusercontent.com/1597621/124381952-56ed6a80-dcc5-11eb-8486-4579f7f6ebd6.png">

**Do I have to check/uncheck something (like "Nginx Ingres" or "Nginx Default Backend") to get the Ingress working?**

**Result:**

`nginx.default.MY_IP.xip.io` address is not reachable:
`DNS_PROBE_POSSIBLE`

**Expected Result:**

show `nginx`or `rancher/hello-world` page in browser

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

v2.5.8 
all current / unchanged settings

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
  - Hetzner
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
   - CX11  
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
  - 20.10.7
--

**Comment by vincent99** [comment]
Xip.io was recently turned off by its owners.  https://github.com/rancher/rancher/issues/32500
