### ISSUE TITLE
[Logging v1] Windows fluentd blocking Linux fluentd changes

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#33486]
This issue is a little more broad that usual, but https://github.com/rancher/rancher/issues/33390 should provide more context.
Essentially, new SAC patch releases and/or Dockerfile-specified dependencies have caused new Windows fluentd builds to fail, despite using an identical Dockerfile.

This is a block for https://github.com/rancher/rancher/issues/33390.

**Comment by nickgerace** [comment]
Release note: `Windows fluentd image: Ruby upgraded from 2.4.2 to 2.7.3`

**Comment by nickgerace** [comment]
QA validation: ensure that Windows works with new fluentd changes.

**Comment by nickgerace** [comment]
This will move to "To Test" once https://github.com/rancher/rancher/issues/33390 is ready and a new Logging v1 system-chart is created.

**Comment by sowmyav27** [comment]
Validate Logging is updated to `0.2.5` with fluentd `v0.1.25` - as part of [this](https://github.com/rancher/rancher/issues/33390) issue

**Comment by izaac** [comment]
Rancher version: `v2.6 master-head (07/20/2021)` _cfbd0d3_
Single Docker Install Rancher server.

I am getting `ImagePullBackOff: Back-off pulling image "rancher/fluentd:v0.1.25"` using Windows 2004 worker nodes.
The same Windows 2004 image was used on `2.5-head`  and `fluentd:v0.1.24` worked fine.

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (08/02/2021)` _3499046_

Logging v1 installed on a Custom downstream cluster with k8s `1.20.9-rancher1-1` 
Logging v1 App version: `0.2.5`
Fluentd version `v0.1.28`
Windows SAC version `2004`

Logging entries were flowing properly to the backend
