### ISSUE TITLE
When creating a RKE2 cluster with Calico tigera-operator and calico-system are not in the system projects

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#33483]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a RKE2 cluster with Calico as a CNI Plugin.

**Result:**
Calico creates the namespaces `calico-system` and `tigera-operator`. These namespaces are not part of a project and therefor marked as user namespace.

![Bildschirmfoto 2021-07-05 um 18 15 34](https://user-images.githubusercontent.com/243056/124498689-0ce7b000-ddbd-11eb-8677-0606169d2c50.png)

**Expected Result:**
The calico related namespaces should be in the system project automatically.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE2 Infrastructure Provider & Custom
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+rke2r1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-06-24T00:52:42Z", GoVersion:"go1.16.4b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by kravciak** [comment]
Works fine on master-head (8073489).
Namespaces `calico-system` and `tigera-operator` are part of system project.

![Screenshot from 2021-07-14 14-38-28](https://user-images.githubusercontent.com/538604/125623582-133611a1-82fe-4f21-9724-e50557e51b7b.png)
