### ISSUE TITLE
[Backport] v2.5: Adding label to EKS managed node group results in continual error

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#33497]
**Original Issue:**
https://github.com/rancher/rancher/issues/33302

**Comment by rmweir** [comment]
@sowmyav27 nodegroups tag, nodegroup labels, nodegroup resourceTags, and cluster tags should all be tested. Particularly the scenarios where these fields are having a key removed and adding/updating keys are important.

**Comment by rmweir** [comment]
https://github.com/rancher/system-charts/pull/493

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.5-head` `version 0e58768` with the above scenarios.
EKS operator version: `eks-operator:v1.0.10-rc1`

The original issue has been validated with the following steps:
From Ember UI, provision a hosted EKS cluster.
After cluster is available, edit the cluster from UI and add a label to the nodegroup.
Save.
The cluster updates. Nodegroup label is seen in Rancher UI and EKS console.

The user is able to add nodegroups tags, nodegroup labels, nodegroup resourceTags, and cluster tags. Edits are reflected in Rancher UI and EKS console.
