### ISSUE TITLE
[2.4] gke v1 - getting error 500 for us-central1 region

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33490]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):** 
Create a GKE us-central1 cluster on 2.4-head

**Result:**
`Googleapi: Error 500: Internal error encountered., backendError`

**Expected Result:**

**Other details that may be helpful:**
I was able to create us-central1 GKE cluster from GCP

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by prabalsharma** [comment]
I was able to create central1 regional clusters on 2.5 and 2.6 head

**Comment by sowmyav27** [comment]
Happens for GKE version`1.18.20-gke.501` seen on UI.

**Comment by prabalsharma** [comment]
was able to provision a GKE cluster on us-central1 region with the default k8s version (v1.18.20-gke.501)
