### ISSUE TITLE
Worker requirement logging not seen on custom cluster

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#33494]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- On Rancher `master-head` `version 3e44415`
- Create an RKEv1 custom cluster
- Add node with etcd and control plane node (no node with worker role)
- View logs from rancher-agent in control plane/etcd node.

**Result:**
There is no indication that the cluster is waiting for a worker node.
```
time="2021-07-06T17:06:03Z" level=info msg="Connecting to proxy" url="wss://.../v3/connect/register"
time="2021-07-06T17:06:03Z" level=info msg="Starting plan monitor, checking every 15 seconds"
```

**Expected Result:**
Related issue: https://github.com/rancher/rancher/issues/32204
A message should be logged that the cluster is waiting for a worker node.
`Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-head` `version 3e44415`
- Installation option (single install/HA): Single install

**Comment by sowmyav27** [comment]
will be tracked [here](https://github.com/rancher/rancher/issues/32204)

**Comment by aaronRancher** [comment]
Reopening, as this behavior is different from [#32204](https://github.com/rancher/rancher/issues/32204)
No logs are seen after the following lines:
```
time="2021-07-06T17:06:03Z" level=info msg="Connecting to proxy" url="wss://.../v3/connect/register"
time="2021-07-06T17:06:03Z" level=info msg="Starting plan monitor, checking every 15 seconds"
```
Something is preventing these logs from appearing: https://github.com/rancher/rancher/blob/master/pkg/rkenodeconfigclient/client.go#L111

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 58f6425`

Worker requirement logs are repeatedly seen.
```
time="2021-07-13T23:40:04Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-07-13T23:40:06Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-07-13T23:40:08Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-07-13T23:40:10Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-07-13T23:40:12Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-07-13T23:40:14Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
```

Do not see the following log:
```
time="2021-07-06T17:06:03Z" level=info msg="Starting plan monitor, checking every 15 seconds"
```

**Comment by aaronRancher** [comment]
Reopening issue, as we do not expect these logs to repeat.

The previous implementation:
```
time="2021-05-11T22:31:20Z" level=info msg="Connecting to wss://.../v3/connect/register with token ..."
time="2021-05-11T22:31:20Z" level=info msg="Connecting to proxy" url="wss://.../v3/connect/register"
time="2021-05-11T22:31:20Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-11T22:31:22Z" level=info msg="Starting plan monitor, checking every 15 seconds"
```

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 58f6425` with the following steps:
Create an RKEv1 custom cluster
Add node with etcd and control plane node (no node with worker role)
View logs from rancher-agent in control plane/etcd node.

Result:
Node requirements are seen in logs. Logs stop when node requirements have been met.
```
time="2021-07-14T18:34:56Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-07-14T18:34:58Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-07-14T18:35:00Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-07-14T18:35:02Z" level=info msg="Starting plan monitor, checking every 15 seconds"
time="2021-07-14T18:35:17Z" level=info msg="Plan monitor checking 120 seconds"
```

Will track backport of this issue here: https://github.com/rancher/rancher/issues/33624
