### ISSUE TITLE
Services are not created for workloads deployed from Dashboard

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#33508]
**Rancher Server Setup**
- Rancher version: `rancher/rancher:master-head ac7cef3`
- Installation option (Docker install/Helm Chart): custom RKE1 + helm

**Information about the Cluster**
- Kubernetes version: `v1.21.1-rancher2-1`
- Cluster Type (Local/Downstream): local RKE1 + custom RKE1 DO

**Describe the bug**
Similar issue as https://github.com/rancher/rancher/issues/33125 but this time for workloads deployed from Dashboard/Explorer

Basically once you create a Deployment in Dashboard the workload should have created a service (dns record) for accessing the workload but the service is not created.

**To Reproduce**
* Select a RKE1 downstream cluster from `EXPLORE CLUSTER` list in Dashboard
* Go to `Workload` and click `Create` button
* Select `Deployment`
* Create a deployment in `default` ns with name `busybox` and `busybox` as image. Use command `/bin/sh` and `-c 'while true; do echo blah; sleep 1; done'` as Argument
* click `Create`

**Result**
Go to `Service Discovery` and select `Services` - Note there is no service created for the deployment 

The one named `busybox-ember` has been created automatically when deploying the same workload/deployment from Ember:
![services_dashboard](https://user-images.githubusercontent.com/12828077/124762167-e51a5880-df32-11eb-9279-d30d436e91e6.png)

**Expected Result**
The service should be created automatically also when deploying a workload from Dashboard

**Comment by thehejik** [comment]
According to @sowmyav27  this was intentional change and the services should not be created automatically for workloads created in Dashboard. 

The services should be handeled like in vanilla k8s according to https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

Closing as invalid.

**Comment by micronax** [comment]
Is there somewhere more information about this change? I think it should be at least documented as breaking change etc. in the upgrade notes.

Is there a way to re-enable this behaviour in 2.6?
