### ISSUE TITLE
Logout Timeout

### ISSUE THREAD

**Issue by maese83** [rancher/rancher#33509]
Hello we use Rancher with AD Authentication since 2 years. Since the beginning we get logged out very often and even when working in Rancher UI. What problem could that be? Is there a timeout set very low?
Thanks for your feedback
Marcel
---
|Versions|Rancher `v2.5.8` UI: `v2.5.8` |

**Comment by vincent99** [comment]
The default timeout is 16 hours and can be changed in advanced settings.
