### ISSUE TITLE
Add bitnami repo add my own gitlab repo and version upgrade

### ISSUE THREAD

**Issue by ruwan1235** [rancher/rancher#33504]
I added bitnami/wildfly latest helm chart to my own gitlab repositary.

After deploy that using rancher and it is working fine.

But i need upgrade that chart. I updated chart and changed the Chart.yaml and add new version number.

In rancher ui show only last version. now show any previous version.
![Screenshot from 2021-07-06 14-03-48](https://user-images.githubusercontent.com/86238699/124716755-0d4d8b80-df22-11eb-958c-83eabf1fb540.png)

**Comment by a-nldisr** [comment]
@ruwan1235 Perhaps you can ask your question on Slack and get help there?

**Comment by ruwan1235** [comment]
@a-nldisr anyone have idea how to fix this issue

**Comment by ruwan1235** [comment]
anyone have idea

**Comment by vincent99** [comment]
Stop spamming the same issue multiple times and @-ing random people.  Just changing the version number is not creating a "new" version, is replacing the old one.

**Comment by ruwan1235** [comment]
Then how to create new version

**Comment by ruwan1235** [comment]
> Stop spamming the same issue multiple times and @-ing random people. Just changing the version number is not creating a "new" version, is replacing the old one.

Then how to create new version
