### ISSUE TITLE
[rancher-compose] inservice upgrade with -d doesnt exit

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#3350]
The docs for rancher-compose state that you can use the -d flag during a `rancher up --upgrade` and it doesnt hang and print logs. This doesnt seem to work.

I am using the following command on my CI and it hangs everytime.

    rancher-compose --url https://rancher.mydomain.com/v1/projects/1axx --access-key xxxx --secret-key xxxx --project-name my-stack up --upgrade my-service --pull --interval 30000 --batch-size 1 -d

Note that I have -d at the end. Is there a way to make this command not hang?

Possibly important version info:

    $ rancher-compose --version                                                           
    rancher-compose version v0.7.0

**Comment by deniseschannon** [comment]
Verified that the upgraded state of service does not allow rancher-compose to exit.

**Comment by deniseschannon** [comment]
Also, if you use `rancher-compose up --confirm-upgrade -d`, it still hangs.

**Comment by deniseschannon** [comment]
Testing with v0.8.0-rc1

`rancher-compose up --upgrade service1 -d` complains that `-d` is not a service.
`rancher-compose up --upgrade service1 -pull` complains that `-pull` is not a service

Since we support `rancher-compose up service1 -d`, we should allow that kind of ordering when upgrading.

**Comment by joshwget** [comment]
@deniseschannon I think the issue is actually caused by putting some flags at the beginning and some at the end. Both `rancher-compose up -p service1 -d` and `docker-compose up --no-recreate up -d` give the same error, so it's not specific to using the `--upgrade` flag or even to Rancher Compose.

**Comment by deniseschannon** [comment]
Agree with @joshwget. Verified that it's working as expected in v0.8.0-rc1.

**Comment by deniseschannon** [comment]
We will be release v0.7.3 with GA, so re-opening to track when we release v0.8.0 and re-verify.

**Comment by deniseschannon** [comment]
Verified with v0.8.0-rc3
