### ISSUE TITLE
Add new chart verssion

### ISSUE THREAD

**Issue by ruwan1235** [rancher/rancher#33516]
I create helm chart using
helm create hello-word

and deployed helm and add helm to my gitlab repo. And i update repo and add new chart version. Always show only last repo version. I need show all repo version. Anyone can help.
![Screenshot from 2021-07-08 00-05-04](https://user-images.githubusercontent.com/86238699/124818429-a57e5b80-df88-11eb-87ca-124dd68a3aec.png)

![Screenshot from 2021-07-08 00-09-54](https://user-images.githubusercontent.com/86238699/124818443-aadba600-df88-11eb-9264-c5adf46142e3.png)

**Comment by ruwan1235** [comment]
anyone have solution for this?

**Comment by cbron** [comment]
This is not a rancher specific problem, as our charts do refresh correctly. You will need to look into your chart versions or index.yaml to make sure they are updated.
