### ISSUE TITLE
Update rancher-externalip-webhook chart to support kubernetes 1.22

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#33513]
helm install on 1.21 shows these deprecation warnings:

```
W0707 09:35:33.072550  817219 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
client.go:122: [debug] creating 7 resource(s)
W0707 09:35:33.197351  817219 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
```

**Comment by cbron** [comment]
On hold for now due to: https://github.com/rancher/rancher/issues/33893

**Comment by Jono-SUSE-Rancher** [comment]
We will have to tackle this for v2.6.2 since we're going to push the k8s 1.22 support to that milestone.

**Comment by cbron** [comment]
That may be true, but still TBD due to upstream changes, which aren't around 1.22.

**Comment by Jono-SUSE-Rancher** [comment]
That's a good point. I just wanted to move it out of 2.6.1 for the time being.

**Comment by cbron** [comment]
Closing this out, we are going to cap external-ip-webhook at <=1.21.
