### ISSUE TITLE
New charts in v2.5.10

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#33528]
System charts (v1) `rancher/system-charts:dev-v2.5`:

Name                 | Version  | Backend Dev(s)
---------------------| -------- | -----------
rancher-eks-operator | 1.0.1000 | @thedadams 
rancher-gke-operator | 1.1.100  | @cmurphy 
rancher-logging      | 0.2.5.   | @paynejacob 

Feature charts (v2) `rancher/charts:dev-v2.5`:

Name                       | Version           | Note                 | Backend Dev(s)
---------------------------| ----------------- |----------------------|----------- 
longhorn                   | 1.2.200+up1.2.2, 1.1.200+up1.1.2 | 2 new versions | @innobead @shuo-wu 
rancher-istio              | 1.9.800           | OOB release already live | @brendarearden  
rancher-backup             | 1.2.0             | new release          | @jiaqiluo 
rancher-alerting-drivers   | 1.0.200           | new release          | @jiaqiluo 
rancher-monitoring         | 16.6.0            | new release          | @aiyengar2 @jiaqiluo  
rancher-webhook            | 0.1.200+up0.1.2   | new release          | @ryansann  
rancher-cis-benchmark      | 1.0.600           | new release          | @prachidamle 
rancher-vsphere-cpi        | 1.0.100           | new release          | @PennyScissors 
rancher-vsphere-csi        | 2.3.0             | new release          | @PennyScissors 

New versions of sub-charts for `rancher-monitoring 16.6.0`
Name                       | Version           | Note                 | Backend Dev(s)
---------------------------| ----------------- |----------------------|----------- 
rancher-grafana            | 6.11.0            | new release, internal          | @aiyengar2  
rancher-node-exporter      | 1.18.100+up1.18.1 | new release, internal          | @aiyengar2  
rancher-kube-state-metrics | 3.2.0             | new release, internal          | @aiyengar2 
rancher-prometheus-adapter | 2.14.0            | new release, internal          | @aiyengar2 
rancher-windows-exporter   | 0.1.100           | new release, internal          | @aiyengar2 
rancher-pushprox           | 0.1.400           | new release, standalone          | @aiyengar2 

New versions of sub-charts for `rancher-alerting-drivers 1.0.200`
Name                       | Version           | Note                 | Backend Dev(s)
---------------------------| ----------------- |----------------------|----------- 
rancher-prom2teams         | 0.2.100+up0.2.0   | new release, internal           | @jiaqiluo 
rancher-sachet             | 1.0.200           | new release, internal           | @jiaqiluo

**Comment by aiyengar2** [comment]
Rancher Monitoring needs to add a rancher-min-version annotation since it is tied to the rancher/rancher PR for updating the Monitoring V1 CRDs (https://github.com/rancher/rancher/pull/33547).

**Comment by jiaqiluo** [comment]
- [ ] `rancher-alerting-driver` needs to add an annotation for showing only in v2.5.10 and above 
- [ ] `rancher-backup` needs to add an annotation for showing only in v2.5.10 and above

**Comment by sowmyav27** [comment]
**On 2.5.10-rc6**

- backup-restore-operator:v1.2.0
- cis-operator:v1.0.6
- eks-operator:v1.0.10
- gke-operator:v1.1.1
-

**Comment by anupama2501** [comment]
On 2.5.10-rc6

istio - 1.9.8-rancher1
