### ISSUE TITLE
[2.5] gke v1/v2 - getting error 500 for us-central1 region

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#33523]
Forwardport: https://github.com/rancher/rancher/issues/33490

Same bug applies when selecting kubernetes version "1.18.20-gke.501" in region us-central1, regardless of kev1/kev2.

**Comment by cmurphy** [comment]
https://github.com/rancher/rancher/pull/33500 https://github.com/rancher/rancher/pull/33499

**Comment by prabalsharma** [comment]
2.5.9-rc8 is still not pointing to correct charts. 
RC9 is building. Though, rc9 will not have  https://github.com/rancher/system-charts/pull/497 
For now blocked on new RC

**Comment by prabalsharma** [comment]
on 2.5.9-rc9, was able to create a GKE cluster on uscentral1 region with k8s verion  = 1.18.20-gke.501
