### ISSUE TITLE
[2.6] gke v1/v2 - getting error 500 for us-central1 region

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#33524]
Forwardport: rancher/rancher#33490

Same bug applies when selecting kubernetes version "1.18.20-gke.501" in region us-central1, regardless of kev1/kev2.

**Comment by cmurphy** [comment]
https://github.com/rancher/rancher/pull/33498

**Comment by sowmyav27** [comment]
**To Validate:**

- to provision a Hosted GKEv2 cluster on us-central1 region with the default k8s version 
- to provision a Hosted GKEv2 cluster on us-central1 region with the k8s version v1.18.20-gke.501 (if this is not default)

**Comment by kravciak** [comment]
Clusters were created fine, I could open them in explorer afterwards
- GKEv2 / us-central1 / 1.19.9-gke.1900 (default)
- GKEv2 / us-central1 / 1.18.20-gke.501
