### ISSUE TITLE
Not able to access kubectl, fails with error Unable to connect to the server: x509: certificate is valid for 127.0.0.1, 172.17.0.2 not Rancher Server IP

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33537]
**Rancher Server Setup**
- Rancher version: `v2.5.8 and v2.5.9-rc4`
- Installation option (Docker install/Helm Chart): `Docker install`
- Proxy/Cert Details: `Rancher Self signed` 

**Information about the Cluster**
- Kubernetes version: `v1.19.8+k3s1`
- Cluster Type (Local/Downstream): `Local`

**Describe the bug**

- When using the kubeconfig file from the rancher versions above, seeing an error and not able to use kubeconfig from local machine from performing any further activities on rancher server.

**To Reproduce**
1. On a linode/AWS instance, install rancher server versions either v2.5.8 or v2.5.9-rc4 via docker.
2. Grab the kubeconfig file from the local cluster.
3. Run the command `kubectl get pods --kubeconfig kubeconfig.yaml`

**Result**

- Fails with the error ```Unable to connect to the server: x509: certificate is valid for 127.0.0.1, 172.17.0.2, not rancher_server_ip```
- This happens for any other kubectl command as well.

**Expected Result**
The command should not have failed and worked with the kubeconfig file provided for local cluster.

**Screenshots**

**Additional context**

- If we create a downstream cluster [rke1 node driver 1 node all roles EC2] in the rancher server, the kubeconfig file from the local and the downstream clusters work fine.
- `Launch kubectl` button in the UI works without any issues.
- Related issue: https://github.com/rancher/rancher/issues/31784

**Comment by deniseschannon** [comment]
Since the local cluster on a Docker install is not a true k8s cluster to actually deploy resources into, I wouldn't expect this kube config file to work to access the k3s cluster inside the docker install.

**Comment by sowmyav27** [comment]
Related issue - https://github.com/rancher/rancher/issues/31784

**Comment by anupama2501** [comment]
closing as its a `wont-fix`
