### ISSUE TITLE
Unable to update k8s on Imported AKS cluster when using Location other than `eastus`

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#33534]
**Rancher Server Setup**
- Rancher version: `rancher/rancher:master-head cf5a75f`
- Installation option (Docker install/Helm Chart): any
- Proxy/Cert Details: -

**Information about the Cluster**
- Kubernetes version: any AKS k8s
- Cluster Type (Local/Downstream): custom local, Imported AKS (default values but region changed to `westeurope`)

**Describe the bug**
When MS `Kubernetes services` aka AKS is deployed from Azure Portal UI in different Location than `eastus` (eg to existing  Resource Group in `westeurope` location the cluster cannot be updated to newer k8s over rancher due problem with hardcoded location. On attempt to update from rancher the status of the cluster is `Updating` with following Error message: 

`Failed to update cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="InvalidResourceLocation" Message="The resource 'thehejik-aks-forimport' already exists in location 'westeurope' in resource group 'thehejik-rancher'. A resource with the same name cannot be created in location 'eastus'. Please select a new resource name."`

Problem is that `Location` field when doing `Edit Cluster` is probably hardcoded to `eastus` value, it's inactive and cannot be changed:
![imported_aks_update](https://user-images.githubusercontent.com/12828077/124949525-ee2e2700-e011-11eb-90a7-122ad6eb190c.png)

**To Reproduce**
* deploy a AKS in Azure Portal in different Location than `eastus` - I was deploying into my own Resource Group assigned to `westeurope` location
* Import the AKS cluster into Rancher 
* Once the cluster is Active perform `Edit Cluster`, change k8s version and Apply

**Result**
Update will fail with the error message above.

**Other info**
The same works ok for Hosted AKS

**Comment by cmurphy** [comment]
Backend PR merged, will be ready to test when UI issue https://github.com/rancher/rancher/issues/33540 is complete

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head e83ac8c` with `rancher/aks-operator:v1.0.1-rc15`

The location is now correctly fetched for the imported AKS server living in `norwayeast` azure location on attempt to update the cluster from rancher.
![location](https://user-images.githubusercontent.com/12828077/125811453-5b5f5da1-8e81-44ab-aeca-585922060080.png)

But in later phase of update it failed on https://github.com/rancher/rancher/issues/33536

Anyway this seems to be fixed as well as #33540

Close.
