### ISSUE TITLE
[UI][AKS] Use region to filter VNet list in /meta/aksVirtualNetworks

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#33542]
Followup from https://github.com/rancher/rancher/issues/33517

Currently, /meta/aksVirtualNetworks lists all VNets available to the user. Once [this change](https://github.com/rancher/rancher/pull/33541) is merged, it will accept `region` as a query parameter which will filter the list by ResourceLocation. UI should use the Region selected by the user for this parameter.

**Comment by vincent99** [comment]
The UI already sent the region so I don't think any further change is needed now that the server is filtering based on it.

**Comment by prabalsharma** [comment]
got fixed from backend ^. No changes were required in UI.
