### ISSUE TITLE
[forwardport] GKEv2 UI - Add region support for /meta/gkeVersions

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33543]
test on master-head
https://github.com/rancher/rancher/issues/33527
backend issue https://github.com/rancher/rancher/issues/33524

**Comment by kravciak** [comment]
Created GKEv2 1-node clusters on master-head (861fb92):
 - default zone, default version
 - default zone, non-default version
 - non-default zone, default version
 - non-default zone, non-default version
 - default region, default version
 - non-default region, non-default version

default version: v1.19.9-gke.1900
non-def version: v1.20.8-gke.900
default zone: us-central1-c
non-def zone: europe-central2-a
default region: us-central1
non-def region: europe-west1

All of them are Active, workloads in system project are Active.
