### ISSUE TITLE
Repeated error syncing 'git-webhook' seen in Rancher logs

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#33545]
**Rancher Server Setup**
- Rancher version: `master-head` `version 5aa95f2`
- Installation option (Docker install/Helm Chart): docker single install

**Describe the bug**

An error is repeatedly seen in Rancher server logs.

**To Reproduce**
 
Bring up a single install Rancher on latest master-head.
Launch a DO downstream cluster.
View Rancher logs of local cluster.

**Result**
This error is repeatedly seen:
```
[ERROR] error syncing 'git-webhook': handler apiservice: failed to create fleet-system/steve-aggregation /v1, Kind=Secret for apiservice git-webhook: namespaces "fleet-system" not found, requeuing
```

**Additional information**
`fleet-system` namespace does not exist on the local cluster or downstream cluster. But `cattle-fleet-system` is available.

**Comment by nickgerace** [comment]
This is no longer seen and was fixed by https://github.com/rancher/rancher/pull/33577/commits/6dff19b21288e9d3d038a22bdc8fab28e1b28e7e

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version d3ad5d3` with the following steps:
- Bring up a single install Rancher on latest master-head.
- Launch a DO downstream cluster.
- View Rancher logs of local cluster.

Result:
Error is not seen in Rancher logs.
Secret is successfully created:
```
2021/07/19 17:38:12 [DEBUG] DesiredSet - Created /v1, Kind=Secret cattle-fleet-system/steve-aggregation for apiservice git-webhook
```
