### ISSUE TITLE
Creating cluster with multiple nodes, some of the nodes remain in Active

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33548]
**Rancher Server Setup**
- Rancher version: `2.5.8`
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Kubernetes version: 1.20.8
- Cluster Type (Local/Downstream): RKE DO Node driver

**Describe the bug**
Creating cluster with multiple nodes, some of the nodes remain in Active and go into Provisioning state after sometime.

**To Reproduce**
Note: Usually happens after multiple clusters are deployed in the rancher setup
- Deploy 3 clusters - 1 eks - 2 nodes, 1 do RKE1 - 4 nodes and 1 rke1 DO - 3 nodes
- Deploy another RKE1 DO with 1 control, 1 etcd and 4 worker nodes
- Some of the nodes remain in Active state for quite some time before they go into provisioning state

**Result**
- Some of the nodes remain in Active state for quite some time before they go into provisioning state

**Expected Result**
All nodes should go into provisioning state immediately on deploying a cluster

**Screenshots**
- All clusters:
<img width="1282" alt="Screen Shot 2021-07-08 at 4 15 34 PM" src="https://user-images.githubusercontent.com/26032343/125017812-bb435d80-e028-11eb-9bed-bfc415fa8949.png">
- Test3 cluster
<img width="1322" alt="Screen Shot 2021-07-08 at 4 15 03 PM" src="https://user-images.githubusercontent.com/26032343/125017820-bda5b780-e028-11eb-8b61-66fc3ec21404.png">

**Additional context**
Related issue - https://github.com/rancher/rancher/issues/30346

**Comment by superseb** [comment]
@sowmyav27 The related issue was fixed in backported to 2.5 but not in 2.5.8. And the milestone of this issue is v2.6. Are you saying this is happening on `v2.5-head`/`master-head` so the previous validation in the related issue is not applicable anymore?

**Comment by sowmyav27** [comment]
Closing issue with testing done for 2.6 here - https://github.com/rancher/rancher/issues/30346
