### ISSUE TITLE
[UI][AKS] Use dynamic AKS cluster location for imported clusters

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#33540]
Followup for https://github.com/rancher/rancher/issues/33534

Currently UI hardcodes "eastus" as the AKS cluster location:

https://github.com/rancher/ui/blob/ea36d73a762f8c4e93d21f1019c6de8138df5d3c/app/models/cluster.js#L168

and uses it when creating an imported cluster object:

![image](https://user-images.githubusercontent.com/1220710/124988745-39850d00-dff3-11eb-8901-8ed9469f547f.png)

Once [this fix](https://github.com/rancher/rancher/pull/33539) is merged, the /meta/aksClusters call will return something like this:

```
$ curl -s -u $TOKEN "https://localhost:8443/meta/aksClusters?cloudCredentialId=cattle-global-data:cc-abcde" | jq .
[
  {
    "resourceGroup": "colleen-group",
    "clusterName": "colleen-1",
    "rbacEnabled": true,
    "location": "westus"
  },
  {
    "resourceGroup": "mj-demo",
    "clusterName": "mj-demo",
    "rbacEnabled": true,
    "location": "germanywestcentral"
  }
]
```

UI should use the `location` returned from /meta/aksClusters to populate `resourceLocation` in the cluster create request for imported clusters.

It's also unnecessary (but not harmful) to pass "region" and "tenantId" in to /meta/aksClusters:

![image](https://user-images.githubusercontent.com/1220710/124989329-e19ad600-dff3-11eb-8ebf-652a78287c2e.png)

**Comment by thehejik** [comment]
Tested on `rancher/rancher:master-head e83ac8c` with `rancher/aks-operator:v1.0.1-rc15`

The location is now correctly fetched for the imported AKS server living in `norwayeast` azure location on attempt to update the cluster from rancher.
![location](https://user-images.githubusercontent.com/12828077/125811453-5b5f5da1-8e81-44ab-aeca-585922060080.png)

Close.
