### ISSUE TITLE
New charts in v2.5.9

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#33557]
System charts (v1) `rancher/system-charts:dev-v2.5.9`:

Name                 | Version  | Backend Dev(s)
---------------------| -------- | -----------
rancher-gke-operator | 1.0.300  | @cmurphy 

Feature charts (v2) `rancher/charts:dev-v2.5`:

Name                       | Version           | Note                 | Backend Dev(s)
---------------------------| ----------------- |----------------------|-----------
rancher-webhook            | 0.1.100+up0.1.1   | new release          | @ryansann  
rancher-istio                     | 1.9.600                | OOB Release        | @brendarearden

**Comment by izaac** [comment]
Rancher version: `2.5.9-rc11` 
Airgap Single Docker install
Charts Repo branch: `dev-2.5` `commit: fae0bf3eabad5fb902e4bda7b87fd1b14034456c`

The `local` cluster has the `rancher-webhook`version as: `0.1.100+up0.1.1`.

GKE operator was validated on regular Rancher install as we need to authenticate first with Google externally. Image versions validated on Airgap.
`gke-operator` version `1.0.200`
`gke-operator`  image in airgap is `{"name":"rancher/gke-operator","tags":["v1.0.2-rc2"]}` matching regular install.

**Comment by izaac** [comment]
Rancher version: `2.5.9-rc12` 
Single Docker Rancher Install
Charts Repo branch: `dev-2.5.9` `commit: 52e8a18fe14ba91d2c8e4d04b3f8bbc4d8079a16`

`rancher-webhook` version: `rancher-webhook-0.1.100+up0.1.1`
`rancher-webhook` image in rancher-images.txt: `rancher/rancher-webhook:v0.1.1`

`gke-operator` version: `1.0.200`
`gke-operator` image in rancher-images.txt: `rancher/gke-operator:v1.0.2-rc2`

**Comment by izaac** [comment]
Rancher version: `2.5.9-rc14`
Single Docker Rancher Install
Charts Repo branch: `dev-2.5.9` `commit: 52e8a18fe14ba91d2c8e4d04b3f8bbc4d8079a16`

`rancher-webhook` version: `rancher-webhook-0.1.100+up0.1.1`
`rancher-webhook` image in rancher-images.txt: `rancher/rancher-webhook:v0.1.1`

`gke-operator` version: `1.0.200`
`gke-operator` image in rancher-images.txt `rancher/gke-operator:v1.0.2`


## Istio 

- Validated on regular Single Docker install and compared with the images listed in `rancher-images.txt`

Istio Images - new

```
rancher/mirrored-istio-install-cni:1.9.6
rancher/mirrored-istio-pilot:1.9.6
rancher/mirrored-istio-proxyv2:1.9.6
rancher/istio-installer:1.9.6-rancher1
```

Istio related images - existing

```
rancher/mirrored-kiali-kiali:v1.32.0
rancher/mirrored-jaegertracing-all-in-one:1.20.0
```

**Comment by jiaqiluo** [comment]
reopen this issue because we need to validate `rancher-gke-operator 1.0.300` in the latest 2.5.9-rc

**Comment by sowmyav27** [comment]
**On 2.5.9-rc15**

- Deploy a hosted GKE cluster, 1.0.3 GKE operator version gets deployed in local cluster.
- Images.txt has


```
rancher/gke-operator:v1.0.3
```
