### ISSUE TITLE
No certificates for rancher-ingress with cert-manager in air-gap deployement

### ISSUE THREAD

**Issue by bdekany** [rancher/rancher#33551]
**Rancher Server Setup**
- Rancher version: 2.5.8
- Installation option: Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
     - RKE v1.2.8
     - K8S v1.19.10-rancher1-1
- Proxy/Cert Details:
  - airgap installation

**Information about the Cluster**
- Kubernetes version: v1.19.10-rancher1-1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
     - no downstream cluster

**Describe the bug**

When installing Rancher 2.5.8 in airgap mode the rancher-ingress does not have a certificate due to wrong api version
Forcing cert-manager version to v1.0.4 during `helm template` produce a yaml calling alpha version
https://rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/air-gap/install-rancher/#5-render-the-rancher-template

**To Reproduce**
 
Install cert-manager v1.0.4 via `helm template` + `kubectl apply`
Install rancher v2.5.8 via `helm template ... --set certmanager.version=v1.0.4`

**Result**
```kubectl apply -R -f ./rancher/
...
error: unable to recognize "rancher/templates/issuer-rancher.yaml": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"
```

**Expected Result**

No error. The `rancher/templates/issuer-rancher.yaml`should be `cert-manager.io/v1`

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by bashofmann** [comment]
The correct syntax to set the certmanager.version is: `--set certmanager.version=1.0.4` withouth the `v`. Otherwise the version detection in the issuer template does not work correctly:
```
❯ helm template rancher rancher-latest/rancher --namespace cattle-system --version v2.5.8 --set certmanager.version=v1.0.4 | grep "Issuer" -B 1
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
❯ helm template rancher rancher-latest/rancher --namespace cattle-system --version v2.5.8 --set certmanager.version=1.0.4 | grep "Issuer" -B 1
    cert-manager.io/issuer: rancher
    cert-manager.io/issuer-kind: Issuer
--
apiVersion: cert-manager.io/v1
kind: Issuer
```
By the way, if you have a cert-manager >= 1.0.0 you can also omit the setting altogether:
```
❯ helm template rancher rancher-latest/rancher --namespace cattle-system --version v2.5.8 | grep "Issuer" -B 1
    cert-manager.io/issuer: rancher
    cert-manager.io/issuer-kind: Issuer
--
apiVersion: cert-manager.io/v1
kind: Issuer
```

**Comment by bdekany** [comment]
@bashofmann thx. It works. Should I open a bug in doc?

**Comment by bashofmann** [comment]
Yes, I think it would be good to make this more clear in the docs.
