### ISSUE TITLE
Need default for RKE2 cluster creation and Metrics

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#33558]
From https://github.com/rancher/dashboard/issues/3331

Under Dashboard in `rancher/rancher:master-head e756276` we present the user when it's time to Create a Custom RKE2 (or any other RKE2 cluster), when switched to etcd pane, there is a Metrics section where are two radio buttons present but none is selected.

UI needs a default option for Metrics: should it be **Only Available Inside the Cluster** or **Exposed to the Public Interface**? Does the backend or the API provide a default? If not, what should this default to?

Screenshot in linked ticket.

**Comment by gaktive** [comment]
For now, UI can hardcode one of these if it'll take the backend time to work on this. Let me know or update the linked Dashboard item.

**Comment by deniseschannon** [comment]
@vincent99 Darren said this was a boolean, which is set to false, so couldn't the default be "Only available inside the Cluster" which is the same as the false value?

**Comment by vincent99** [comment]
@deniseschannon @ibuildthecloud  It's not "set to false", it's no-default-is-provided so the UI treats it as null because it shouldn't be guessing and hardcoding what the defaults are for everything.  KDM should contain `"default": false`.

```
etcd-expose-metrics": {
  "type": "boolean",
  "create": false,
  "update": false
},
```

**Comment by davidnuzik** [comment]
Reopening:

1. There is no linked PR to the change made in KDM for this (I assume no change was made). We should not be moving this To Test until the PR is linked / work is actually done.
2. The issue remains - A default is not picked (KDM probably not updated):
![image.png](https://zube.io/files/rancher/6d83e6839a2f4fd69753888c1b51c346-image.png)

**Comment by deniseschannon** [comment]
But it's not working for the UI for some reason

**Comment by vincent99** [comment]
Defaults where the default was "false-y" weren't being used, changed in rancher/dashboard#3658 / rancher/dashboard#3659

**Comment by deniseschannon** [comment]
Validated with v2.6-head at 8/4/2021 8:30 PM. Default is now automatically selected.

<img width="266" alt="Screen Shot 2021-08-04 at 8 29 32 PM" src="https://user-images.githubusercontent.com/11410997/128286458-9742af2d-322a-4b6c-ac05-04ac024ee1df.png">
