### ISSUE TITLE
"failed to wait for roles to be populated" when installing Helm chart via App & Marketplace UI

### ISSUE THREAD

**Issue by JMacalinao** [rancher/rancher#33554]
**Rancher Server Setup**
- Rancher version: 2.5.8
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s 1.20.7+k3s1

**Information about the Cluster**
- Kubernetes version: 1.20.7
- Cluster Type (Local/Downstream): Local

**Describe the bug**
"failed to wait for roles to be populated" error appears when trying to install any Helm chart via the App & Marketplace UI.

**To Reproduce**
Click on the Install button after selecting any chart.

**Expected Result**
App should start to install.

**Screenshots**
![image](https://user-images.githubusercontent.com/12725027/125085996-c1efd480-e0fd-11eb-892e-11ea4281d2ff.png)

**Additional context**
Using "helm install" works properly.

No other errors are visible from Rancher pods, even with trace log level:
`2021/07/09 13:45:55 [ERROR] Unknown error: failed to wait for roles to be populated`

User used for this attempt is the initial "admin" user, and a different user with Administrator permissions.

**Comment by JMacalinao** [comment]
Upgraded to 2.5.9, issue still persists.

**Comment by dnauck** [comment]
same issue with bitnami charts on rancher 2.5.9

**Comment by gisyrus** [comment]
This problem still persists in 2.6.3... Does anyone get this issue?

**Comment by gisyrus** [comment]
> This problem still persists in 2.6.3... Does anyone get this issue?

Turns out found that the project and namespace ResourceQuota denying Rancher to change the RBAC settings.
I can set the RBAC and install the app after deleting the ResourceQuota, container default resource request and limit in the project and the namespace

**Comment by Sartigan** [comment]
We're running into this issue in an intermittent way in our CI. We build Rancher very frequently and we get it while deploying apps from catalogs in Rancher 2.6.3.

Any ways to target what the issue could be?
