### ISSUE TITLE
I can not find several images which is arm64 version 

### ISSUE THREAD

**Issue by EvanYen** [rancher/rancher#33550]
How can i get arm64 version of images below：
rancher/istio-kubectl:1.5.10 
rancher/prometheus-auth:v0.2.1
rancher/coreos-kube-state-metrics:v1.9.7

**Comment by cbron** [comment]
Rancher in general does not support arm64 at this time, those images are all vendor images and many are not built for arm64.  We are hoping to have support for arm64 long term but even then it will likely be with limited features.
