### ISSUE TITLE
Bug in haproxy monit script

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3355]
https://forums.rancher.com/t/load-balancer-issue/1398/12

**Comment by alena1108** [comment]
@sangeethah to test this change:

1) Deploy lb service with some target service.
2) Login to lb service instance and do:

```
ps -ef | grep haproxy (note PID here, lets call it PID1)
service haproxy stop
```

3) After a second, execute the below again:

```
ps -ef | grep haproxy
```

and validate that:

1)  haproxy PID  != PID1
2)  there is only one haproxy process running

**Comment by sangeethah** [comment]
Tested with build from master:

Logged into lb service container and stopped the ha proxy instance.
The instance of ha proxy has the same pid as the ha proxy process that was running before it was stopped.
There is only 1 instance of haproxy seen.

<img width="603" alt="screen shot 2016-01-27 at 2 54 40 pm" src="https://cloud.githubusercontent.com/assets/4266958/12631481/601e4f20-c506-11e5-89cb-c42d49e551f3.png">

**Comment by alena1108** [comment]
The original fix will be reverted. The issue was really with the "haproxy stop" (called by monit) not stopping the service process (due to this haproxy bug on debian https://bugs.launchpad.net/ubuntu/+source/haproxy/+bug/1477221). In the original fix I've tried to work around it by killing orphaned processes manually. Only to hit one more regression bug - haproxy wasn't running as a privileged container, therefore monit within the container could never kill processes started by Rancher.

2 following PRs were submitted to fix this bug:

1) Upgrade haproxy to 1.6 where https://bugs.launchpad.net/ubuntu/+source/haproxy/+bug/1477221 is fixed: https://github.com/rancher/cattle/pull/1304

2) Run lb instance as a privileged container:

https://github.com/rancher/cattle/pull/1308

**Comment by sangeethah** [comment]
Keeping this issue in open state to verify the fix.

**Comment by sangeethah** [comment]
Tested with latest build from master:

We are starting to use ha proxy version - 1.6.3

```
root@8b3cf87e28ff:/# haproxy -v                                                 
HA-Proxy version 1.6.3 2015/12/25                                               
Copyright 2000-2015 Willy Tarreau <willy@haproxy.org>                           
```                                                                                


Logged into lb service container and stopped the ha proxy instance.
The instance of ha proxy has that starts has a different pid from the ha proxy process that was running previously(which was stopped)
Also there is only 1 instance of haproxy seen.


```
root@8b3cf87e28ff:/# ps -eaf | grep haproxy                                     
haproxy    993     1  0 19:59 ?        00:00:00 haproxy -p /var/run/haproxy.pid 
-f /etc/haproxy/haproxy.cfg -sf 915                                             
root      1083  1079  0 20:07 pts/2    00:00:00 grep haproxy                    
root@8b3cf87e28ff:/# service haproxy stop                                       
 * Stopping haproxy haproxy                                              [ OK ] 
root@8b3cf87e28ff:/# ps -eaf | grep haproxy                                     
root      1104  1079  0 20:07 pts/2    00:00:00 grep haproxy                    
root@8b3cf87e28ff:/# ps -eaf | grep haproxy                                     
haproxy   1112     1  0 20:07 ?        00:00:00 /usr/sbin/haproxy -f /etc/haprox
y/haproxy.cfg -D -p /var/run/haproxy.pid                                        
root      1114  1079  0 20:07 pts/2    00:00:00 grep haproxy                    
root@8b3cf87e28ff:/#         
```
