### ISSUE TITLE
RancherD installation documentation fails every time (Ubuntu 20.04)

### ISSUE THREAD

**Issue by BloodyIron** [rancher/rancher#33565]
I'm trying to set up a rough test environment for RancherD on Ubuntu 20.04. I cannot for the life of me get an actually working environment (single node to start) when following the documentation.

This is the documentation I've tried about 3x times now: https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/

There's at least two issues here:
1. After the initial provisioning, if I run "rancherd reset-admin" the webUI doesn't work when going to the URL. I am using the hostname in the tls-san section (as I don't yet need it to work against a FQDN).
2. If I reboot, and try "rancherd reset-admin" I get the error "FATA[0000] cluster and rancher are not ready. Please try later.: Local cluster is not ready yet" and this is after running the export command again "export KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin"

I have to ask, when was the last time this documentation was actually TESTED from scratch? I know that the documentation at the very top says this is "experimental", but I generally expected this to actually work far more than this. Especially since this is on the latest LTS version of Ubuntu, and RancherD has been available for so long.

I can't find any useful resources online either :/ so I'm stuck. And I'm liking the looks of RancherD more vs other methods.

Please help! I don't know what to do, and where the documentation needs improvement, as I don't even know what I'm doing wrong here.

**Comment by ron1** [comment]
FYI, according to issue https://github.com/rancher/rancher/issues/33423, it appears the currently documented implementation of RancherD is dead . I suspect it will be replaced by a new rancherd implementation being developed here: https://github.com/rancher/rancherd.

**Comment by dj9pz** [comment]
I installed RancherD twice in the last couple of days (2.5.8 on July 14th, 2.5.9 on July 21st) following the documentation in https://rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/install-rancher-on-linux/ and it worked both times without any problems.
Before running `rancherd reset-admin` I ran `watch "kubectl get pods -n cattle-system;kubectl get pods -n fleet-system;kubectl get pods -n rancher-operator-system"` to wait for all pods to become ready.
