### ISSUE TITLE
kubelet logging exceed default size

### ISSUE THREAD

**Issue by saphoooo** [rancher/rancher#33567]
**Rancher Server Setup**
- Rancher version: v2.5.8
- Installation option (Docker install/Helm Chart): Helm Chart / RKE2

**Information about the Cluster**
- Kubernetes version: v1.20.6
- Cluster Type (Local/Downstream): Infrastructure Provider

**Describe the bug**
I noticed node pressure, and by investigating, I figured out that the kubelet json-log was 27G big. By reading the kubelet documentation, I noticed that the default max-size should be 1800m and the default log format text. It's not the case in the cluster deployed through Rancher, and I wonder where I can check these settings

**To Reproduce**
Install a fresh new cluster from Rancher, and just leave it alone for a week-end

**Result**
On one worker the kubelet log was 27G, and 19G on one other

**Expected Result**
Do not exceed 1800M, otherwise let me the ability to configure it by myself

**Screenshots**
```
root@foo-bar1:/var/lib/docker/containers/a147658d9553d8d40cef6112619b33cb0a047bde13030a2c0dc11278fa4899a5# ll
total 19113284
[...]
-rw-r-----  1 root root 19571940905 Jul 12 08:28 a147658d9553d8d40cef6112619b33cb0a047bde13030a2c0dc11278fa4899a5-json.log
[...]
# docker ps|grep a14
a147658d9553   rancher/hyperkube:v1.20.6-rancher1                     "/opt/rke-tools/entr…"   4 days ago          Up 4 days                    kubelet
```

**Comment by saphoooo** [comment]
I realized this was the container log and not the kubelet log, so a change in the docker daemon configuration fixed the issue

**Comment by spatialy** [comment]
Hi @saphoooo, we run into this just now ... can you elaborate what changes need to be done?
