### ISSUE TITLE
aks v2 - adding NP from rancher while upgrading k8s version from Azure, causes error

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#33561]
**Rancher Server Setup**
- Rancher version: master-5aa95f2361df27376acd517637a8abfe08101dcb-head
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: None

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Hosted AKS

**Describe the bug**

Adding a NP from Rancher while k8s upgrade from Azure is progress, throws error in Rancher
**To Reproduce**
 

1. Create an AKS cluster from Rancher - 1 agent NP with no autoscaling
2. Once cluster becomes active go to **Azure** and upgrade k8s version of CP (or CP with NP)
3. While the upgrade on Azure is in progress add NP from **Rancher** 

**Result**
if CP only k8s upgrade was done in step 2:
```
Failed to update cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="OperationNotAllowed" Message="Downgrading Kubernetes version 1.20.5 to 1.19.9 is not allowed. Available upgrades: 1.20.7,1.21.1. Please see https://aka.ms/aks-supported-k8s-ver for version details."
```
if CP + NP k8s upgrade was done in step 2:
```
Failed to update cluster: containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="AgentPoolUpgradeVersionNotAllowed" Message="Upgrade agent pool version from 1.20.5 to 1.19.9 is not allowed, you can only upgrade one minor version at a time. Please use [az aks get-upgrades] command to get the supported upgrade paths. For more information, please check https://aka.ms/version-skew-policy"
```

**Expected Result**

There should be no error from Rancher as AKS is able to handle k8s upgrade and addition on NP.
**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by gaktive** [comment]
May need to be a release note for 2.6.0 regarding upgrading and adding nodes at the same time.

**Comment by prabalsharma** [comment]
This is an edge case. Feel free to reject it.

**Comment by salasberryfin** [comment]
Found this to be open while validating the latest release candidate. Closing the issue.
