### ISSUE TITLE
[1.6] rancher haproxy upgrade

### ISSUE THREAD

**Issue by ElZakariyae** [rancher/rancher#33571]
Dears,

We are running a rancher server v1.6.15 and we would like to know if it's possible to upgrade rancher/lb-service-haproxy:v0.9.1 to rancher/lb-service-haproxy:v0.9.14?

**Comment by mattmattox** [comment]
Yes, I created a script to upgrade haproxy in-place without an upgrade. [Script](https://github.com/mattmattox/rancher-scripts/blob/master/Rolling-HAProxy-upgrade-for-Rancher-v1.6.18-patch1-rc2-to-v1.6.18-patch1-rc3)

NOTE: Rancher v1.6 is [EOL](https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v1.6.30/)

**Comment by dramich** [comment]
@ElZakariyae Closing as it looks like your question was answered (and rancher 1.6 is EOL)
