### ISSUE TITLE
Rancher pod restarts with "[FATAL] failed to ListenAndServe for fleet" error

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33582]
**Rancher Server Setup**
- Rancher version: master-head commit id: `4d41301d`
- Installation option (Docker install/Helm Chart): HA
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: 1.20.7
- 

**Describe the bug**
Rancher pod restarts with "[FATAL] failed to ListenAndServe for fleet" error

**To Reproduce**

Rancher pod has restarted with error in logs
```
2021/07/13 02:25:05 [INFO] Watching metadata for project.cattle.io/v3, Kind=SourceCodeRepository
2021/07/13 02:25:05 [INFO] Watching metadata for /v1, Kind=PersistentVolumeClaim
2021/07/13 02:25:05 [INFO] Watching metadata for management.cattle.io/v3, Kind=CatalogTemplateVersion
2021/07/13 02:25:06 [INFO] Active TLS secret serving-cert (ver=2581) (count 5): map[listener.cattle.io/cn-10.42.0.5:10.42.0.5 listener.cattle.io/cn-10.42.2.5:10.42.2.5 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-rancher.cattle-system:rancher.cattle-system listener.cattle.io/fingerprint:SHA1=..]
2021/07/13 02:25:07 [FATAL] failed to ListenAndServe for fleet: listen tcp :444: bind: address already in use
```

**Expected Result**
Rancher should not restart

**Comment by nickgerace** [comment]
Issue is no longer seen. Tested with the following:

- `rancher/rancher:master-4d41301d05e5128f3392c661a411322c7538a767-linux-amd64` - ISSUE ENCOUNTERED
- `rancher/rancher:master-head` - NOT ENCOUNTERED

**Comment by nickgerace** [comment]
Spoke with @sowmyav27. While we know the issue no longer occurs, we need to validate what happened to solve it.

**Comment by sowmyav27** [comment]
Closing this issue, not been able to reproduce. Will reopen or log a new one if we see it again.
