### ISSUE TITLE
Add built-in Harvester node driver

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#33583]
**Is your feature request related to a problem? Please describe.**
Add Harvester node driver as built-in node driver of the rancher 2.6

**Describe the solution you'd like**
- Add Harvester node driver as built-in node driver of the rancher 2.6, it should be compatible for both RKE1 and RKE2
- Update the Harvester node driver release URL to `releases.rancher.com/harvester-node-driver/$TAG_VERSION` (currently using `harvester-node-driver.s3.amazonaws.com`)

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/rancher/rancher/pull/33531 (merged for testing)
https://github.com/rancher/dashboard/issues/3374
https://github.com/rancher/dashboard/issues/3375

https://github.com/rancher/dashboard/pull/3881

**Comment by guangbochen** [comment]
@futuretea will need to update the harvester node driver of replacing the DV with PVC by https://github.com/harvester/harvester/pull/1066

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/rancher/pull/34328

**Comment by yasker** [comment]
Reopen the issue for validation.

**Comment by slickwarren** [comment]
tested on v2.6-head () at the same time as [testing this dashboard issue](https://github.com/rancher/dashboard/issues/3467#issuecomment-915140731):
* it seems that, when the annotation from the linked comment is used, the cluster is not able to be used as a node driver. I don't think this is expected **Reopening for this issue**
  * repro steps: 
  * provision rancher with harvester enabled
  * import a harvester cluster through the virtualization manager
  * in cluster management, create a cluster using harvester node driver rke2
  * create a cloud credential from the imported cluster
    * resources from harvester will not populate; user is unable to select network, image, namespace from the UI (no matching options)

**Comment by yasker** [comment]
@slickwarren I think node provisioning part is pending for the merge of https://github.com/rancher/dashboard/pull/3881 . cc @guangbochen

**Comment by yasker** [comment]
Add https://github.com/rancher/dashboard/pull/3881 to this issue.

**Comment by slickwarren** [comment]
https://github.com/rancher/rancher/issues/34891 related issue

**Comment by slickwarren** [comment]
related issues:
https://github.com/rancher/rancher/issues/34948
https://github.com/rancher/rancher/issues/34946

**Comment by slickwarren** [comment]
tested on v2.6.1-rc7 with harvester v0.3.0-rc1
* single node, all roles RKE1 -- pass
* single node, all roles RKE2 -- pass
* dedicated node per role RKE1 -- pass
* dedicated node per role RKE2 -- fail -> [new issue filed](https://github.com/rancher/rancher/issues/34992)
* delete cluster from setup (rke1/rke2) -- fail ->[ new issue filed](https://github.com/rancher/rancher/issues/34946)
* add nodepool to cluster (rke1/rke2) -- pass
* scale up nodes in pool (rke1/rke2) -- pass
* scale down nodes in pool (rke1/rke2) -- pass
* remove nodepool (rke1/rke2) -- pass

closing in favor of tickets linked above
