### ISSUE TITLE
For RKE1 Kubernetes 1.21 is showing up as experimental.

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#33595]
Can we please update the backend to remove the "experimental" verbiage from RKE1?

**Comment by Jono-SUSE-Rancher** [comment]
I think if we make k8s 1.21 the default this will automatically remove the "experimental" tag.

**Comment by kravciak** [comment]
Still experimental in master-head (0a0d07a)

![Screenshot from 2021-07-22 17-12-19](https://user-images.githubusercontent.com/538604/126663344-c4d9ab8c-ebfe-403d-9fa8-8fe5fee05cd6.png)

**Comment by kravciak** [comment]
Works fine on master-head (2e6926b), 1.21 is not showing as experimental.
