### ISSUE TITLE
[2.5] Global DNS app gets uninstalled/removed immediately after install due to OwnerReferences cleanup in k8s v1.20

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#33596]
Backporting https://github.com/rancher/rancher/issues/31638 to 2.5

**Comment by anupama2501** [comment]
Verified on 2.5-head 0e58768

- 
- Created a DNS provider and added a DNS entry
- DNS provider namespace was not deleted from local --> system project
- Workload creation and ingress pointing to the DNS entry above is accessible
- Verified the DNS entry is created in AWS route 53.
