### ISSUE TITLE
Harvester Integration - Feature Flag for Harvester

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#33605]
Create a feature flag called `harvester`, which will be used to manage access to the Harvester list page. 

This feature flag will be enabled by default.

**Comment by guangbochen** [comment]
addressed via https://github.com/rancher/rancher/pull/34612

**Comment by deniseschannon** [comment]
We should validate that the feature flag can be disabled and the Harvester links are not visible.

**Comment by slickwarren** [comment]
unable to fully test due to other tickets being blocked: https://github.com/rancher/rancher/issues/33583

**Comment by slickwarren** [comment]
tested on v2.6-head (10dfee4):
* rancher works as expected with harvester global flag disabled -- pass
  * harvester cluster(s) added in this state are shown in cluster management with a warning -- user is unable to use these clusters until the harvester flag is enabled
* harvester clusters are filtered to only show in the `virtualization management` page -- pass
* upgrade checks have passed from rancher with the flag disabled (2.5.9) -> flag enabled (2.6.1-rc3)
