### ISSUE TITLE
"Access not configured" icon overlaps Admin tab.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3361]
Server version - v0.56.0-rc1

<img width="664" alt="screen shot 2016-01-20 at 6 24 32 pm" src="https://cloud.githubusercontent.com/assets/4266958/12469742/40087570-bfa3-11e5-9a54-6be3ef8873ee.png">

**Comment by vincent99** [comment]
This is intentional, though the tooltip is changing once https://github.com/rancher/ui/pull/430 is merged.
