### ISSUE TITLE
UI issues with changing the Rancher cluster (local) name

### ISSUE THREAD

**Issue by peteingithub** [rancher/rancher#33612]
**Rancher Server Setup**
- Rancher version: master-head 8073489 (also others) 
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm, single node k3s 1.21.2, local KVM
- Proxy/Cert Details: no proxy, self-signed

**Information about the Cluster**
- Kubernetes version: 1.21.2-k3s1
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
1) Editing the local cluster switches the Firefox mode to dark.  
2) Changing the cluster name and clicking Save errors out (possibly due to lacking system resources), but after pressing cancel, the name has changed and the mode is back to light.
 
**To Reproduce**
Go to Rancher GUI and change the local cluster's name.

**Result**
Light mode - dark mode - light mode
Error message: `Failed while: Wait for Condition: InitialRolesPopulated: True`

**Expected Result**
No mode change, no error.

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by cbron** [comment]
> Go to Rancher GUI and change the local cluster's name.

Changing the local cluster's name is not supported, as it is managed by Rancher.

**Comment by peteingithub** [comment]
I can change the Rancher cluster's display name in Rancher GUI, but it is not supported. Why not have the field locked? It errors out, but still changes the name as in v2.5.x.

So should the Rancher cluster always be named **local** and one should not change it to anything else?

**Comment by cbron** [comment]
Yes it should stay as local. We can block editing of it.  https://github.com/rancher/rancher/issues/34021

**Comment by cbron** [comment]
I was incorrect, you should be able to change the name. But I couldn't re-produce the bug using firefox, can you try to repro with a larger machine which doesn't have resourcing issues ? 
Also on this part: `Go to Rancher GUI`, are you on dashboard or cluster-manager ? Whats the url.

**Comment by peteingithub** [comment]
The URL is 
`https://rancher.example.com/dashboard/c/local/manager/provisioning.cattle.io.cluster`
Then Edit Config from the Three Dots menu button on the right.

I can try it later with a single node Rancher cluster with more resources.

**Comment by peteingithub** [comment]
Still errors with more resources.

![image](https://user-images.githubusercontent.com/86831399/128748920-4fb2cb3f-c366-4b51-94a4-0bdb125c9d7b.png)

![image](https://user-images.githubusercontent.com/86831399/128748999-a21e1103-69d6-4955-9457-df029ceefc72.png)

Edit Config

Change name -> Save

![image](https://user-images.githubusercontent.com/86831399/128749221-44574cf5-7847-4394-942a-7a21b857411b.png)

Change finishes properly, though.

**Comment by cbron** [comment]
That `InitialRolesPopulated` error is unrelated, it usually means the cluster still populating/pending. Does it go away after some time ?

**Comment by peteingithub** [comment]
The end result is OK. It processes like 30 secs, then errors out. The cluster name would still be changed.

**Comment by cbron** [comment]
So the error goes away eventually ? If so you can close this issue, as the problem is more around issues with resourcing than the cluster name.

**Comment by peteingithub** [comment]
Error does not go away.
Is 8 cores and 50 gig of RAM not enough for a Rancher server (no downstream clusters)?

I'll close the ticket.

**Comment by cbron** [comment]
That should be plenty of resources: https://rancher.com/docs/rancher/v2.x/en/installation/requirements/#docker

Most likely something else is going on here, maybe docker is limiting resources, or its because its master-head. I'll watch out for this issue in other areas.

**Comment by peteingithub** [comment]
No docker. I see this on a one or three node K3s Rancher cluster.
What happens when you click Save in Edit Config for a Rancher cluster?

**Comment by peteingithub** [comment]
It's RC1, if that differs from master-head at all.

**Comment by cbron** [comment]
Rc1 is just slightly behind master-head right now. There is a new rc2 out, but neither is stable. I did this a few times back and forth and never saw an error message, the cluster name changes correctly.

**Comment by peteingithub** [comment]
I'll check RC2 tomorrow and report back.
I've had no other issues with RC1 myself.

**Comment by peteingithub** [comment]
RC2 seems to install v2.5.9
```
rancher/Chart.yaml:apiVersion: v1
rancher/Chart.yaml:appVersion: v2.5.9
rancher/Chart.yaml:version: 2.5.9
```

**Comment by peteingithub** [comment]
It's the same with RC2. I tried with Firefox and Chrome.
Since the name changes it is cosmetic.

**Comment by peteingithub** [comment]
Not sure if this is related:
![image](https://user-images.githubusercontent.com/86831399/128991911-6654f77e-ee5a-4e0f-a6d6-636ae7601694.png)

**Comment by richard-cox** [comment]
From what I can tell, the page will attempt to asynchronously save changes to cluster members at the same time as the cluster is changed (`lib/shared/addon/components/form-members/component.js` `saveMembers` is a hook, but i don't know how they work in ember)

The https request to change the cluster succeeds, but having no members is apparently is an invalid state so fails early and the overall `save` isn't classed as a success.

I've managed to repo in both chrome and firefox, changing either local cluster name or cluster labels. 

@cbron Is it right to assume all clusters should have owners, or when a global admin is editing a cluster allow the `no owners` state?

**Comment by peteingithub** [comment]
When a cluster is created/registered, would it be possible to assign an owner (if that is required)?
