### ISSUE TITLE
Environments should give more summary details, health overview and possibility to drill-down

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#3362]
As a Rancher administrator, when I click on the "Manage environments" near the upper right account widget I would like to see an overview of Environments with some more details like tot  # Stacks,  Hosts, Services and Containers. Moreover as an Admin, it makes much more sense to me that the Environment overview page I envision here is my default page when I login. An Admin needs a bigger overview when logging in and being redirected to a specific default environment is a bit annoying.

I played with Chrome Inspect and got something like the screenshots below. 
### New Environments page placed under the Admin section

![rancher-environments-page](https://cloud.githubusercontent.com/assets/320440/12475519/d4185b06-c023-11e5-889e-d2243cd12343.png)

Clicking on a Environment will bring me to that Environment page. Clicking on number of Hosts, will bring me to the hosts page, clicking on containers will bring me to that environment containers page and so on.

The gives me as a Rancher Administrator a very good overview of all the environments and a quick way to spot overuse of environment or which ones have some health issues for example Production Team B above. With current Rancher UI it is very cumbersome to get the same information.

Note. I also find it more logic to have the Environment page listed under the Admin section. It is after all an administrator settings page. Sometimes I have been looking for it under Admin.
### Expand one Environment to drill-down and see which Stack is unhealthy

If I expand the Production Team B Environment in order to see where the issues are, I can see the list of Stacks and which one is in degraded state.

![rancher-environments-page-expand](https://cloud.githubusercontent.com/assets/320440/12475685/ee1820e4-c024-11e5-9a97-3de45c8098b5.png)

Note that I intentionally gave the Stacks visibility higher on the Environments drill down (rather than hosts), motivation: Stack  is King of Rancher :) see #3275 

It would also be nice to see some summarys of tot services, containers per stack in the table above after an environment is expanded.

The above facilitates the usage of Rancher in organisations where a large number of environments are needed to be created, like one for each Team in the organisations responsible for the deployement of specific applications. This also hellps companies that what to create a cloud service PaaS with Rancher and have an overview of their clients environments (similar to IaaS tenants).

**Comment by vincent99** [comment]
2.0 has something similar to this.
