### ISSUE TITLE
Update rancher-gke-operator to support kubernetes 1.22

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#33621]
CRD helm installation shows deprecation warnings on 1.21:

```
W0714 11:19:11.459948 4040268 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

**Comment by brudnak** [comment]
**My checks PASSED**
  
**Reproduction Environment:**

 | Component               | Version              |
 | ----------------------- | -------------------- |
 | Rancher version         | v2.6.1               |
 | Rancher cluster type    | Docker install       |
 | Helm version            | v2.16.8-rancher1     |
 | Downstream cluster type | Hosted Google GKE    |
 | Downstream K8s version  | 1.21.3-gke.2001      |
 | GCP Credentials         | Setup prior to steps |

![01-33621-repro-env](https://user-images.githubusercontent.com/40877149/137813831-92271e18-be76-43a3-843f-b1c537eb5211.png)

**Reproduction steps:**

1. Starting from the Rancher homepage `/dashboard/home`
2. Click the hamburger menu -> `Create` -> `Google GKE`
    - Fill out `Cluster Name`
    - Fill out `Google Project ID`
3. Click `Next: Configure Cluster` -> `Configure Cluster`
4. Select Kubernetes version: `1.21.3-gke.2001`
5. Enter a `Name` under `Group Details`
   - Initial Node Count: `3`
6. Click `Create` -> you are redirected to `Clusters` page
7. Click the hamburger menu -> `Local` -> `Apps & Marketplace` -> `Recent Operations`
8. Under `cattle-systems` click the `ellipsis (three dots)` next to Release Name: `rancher-gke-operator-crd` -> `View Logs`
9. Observe the logs (listed under additional info below)
  
**Additional Info:**

```txt
helm upgrade --force-adopt=true --history-max=5 --install=true --namespace=cattle-system --reset-values=true --timeout=5m0s --version=100.0.0+up1.1.1 --wait=true rancher-gke-operator-crd /home/shell/helm/rancher-gke-operator-crd-100.0.0-up1.1.1.tgz
Release "rancher-gke-operator-crd" does not exist. Installing it now.
W1018 21:09:17.912040      18 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1018 21:09:17.965891      18 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1018 21:09:18.118812      18 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1018 21:09:20.127318      18 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```
  
-----
  
**Validation Environment:**

 | Component               | Version                                            |
 | ----------------------- | -------------------------------------------------- |
 | Rancher version         | v2.6-a636bda2a00e939665b381f704ea8556c39d1a84-head |
 | Rancher cluster type    | Docker install                                     |
 | Helm version            | v2.16.8-rancher1                                   |
 | Downstream cluster type | Hosted Google GKE                                  |
 | Downstream K8s version  | 1.21.3-gke.2001                                    |
 | GCP Credentials         | Setup prior to steps                               |

![02-33621-valid-env](https://user-images.githubusercontent.com/40877149/137813791-d701492c-39ac-40d3-a73f-fa2a54b205b6.png)

  **Validation steps:**

1. Starting from the Rancher homepage `/dashboard/home`
2. Click the hamburger menu -> `Create` -> `Google GKE`
    - Fill out `Cluster Name`
    - Fill out `Google Project ID`
3. Click `Next: Configure Cluster` -> `Configure Cluster`
4. Select Kubernetes version: `1.21.3-gke.2001`
5. Enter a `Name` under `Group Details`
   - Initial Node Count: `3`
6. Click `Create` -> you are redirected to `Clusters` page
7. Click the hamburger menu -> `Local` -> `Apps & Marketplace` -> `Recent Operations`
8. Under `cattle-systems` click the `ellipsis (three dots)` next to Release Name: `rancher-gke-operator-crd` -> `View Logs`
9. Observe the logs (listed under additional info below)
10. The warning message is no longer present :tada:
  
**Additional Info:**

```txt
helm upgrade --force-adopt=true --history-max=5 --install=true --namespace=cattle-system --reset-values=true --timeout=5m0s --version=100.0.1+up1.1.2-rc1 --wait=true rancher-gke-operator-crd /home/shell/helm/rancher-gke-operator-crd-100.0.1-up1.1.2-rc1.tgz
Release "rancher-gke-operator-crd" does not exist. Installing it now.
creating 1 resource(s)
beginning wait for 1 resources with timeout of 5m0s
NAME: rancher-gke-operator-crd
LAST DEPLOYED: Mon Oct 18 22:01:48 2021
NAMESPACE: cattle-system
STATUS: deployed
REVISION: 1
TEST SUITE: None

---------------------------------------------------------------------
SUCCESS: helm upgrade --force-adopt=true --history-max=5 --install=true --namespace=cattle-system --reset-values=true --timeout=5m0s --version=100.0.1+up1.1.2-rc1 --wait=true rancher-gke-operator-crd /home/shell/helm/rancher-gke-operator-crd-100.0.1-up1.1.2-rc1.tgz
---------------------------------------------------------------------
```
