### ISSUE TITLE
Remove k8s 1.22 "beta" prior to the 2.6 release

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#33634]
Need to remove the beta for kubernetes 1.22 prior to the 2.6 release.

**Comment by superseb** [comment]
@Jono-SUSE-Rancher Can we clarify a bit on what the scope is on 1.22? To make k8s 1.22 working we need a change in RKE and in KDM, if this is in, who is going to use it until we revert it? Would a custom build also be good enough for the goal?

**Comment by deniseschannon** [comment]
Now that k8s 1.22 has officially been released, we can close this issue as we will introduce support for k8s 1.22 GA when it's ready. 

Created this ticket to track k8s 1.22 into RKE1: https://github.com/rancher/rancher/issues/34054
