### ISSUE TITLE
Impossible to work with multiple environments with same browser, not possible to share URLs

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#3363]
Due to the very old reported issue #677 it is impossible to have multiple tabs open on the same browser and work within different environments. Right now I am forced to open an incognito tab or another browser in order to work in multiple environments in parallel. 

How to reproduce:
- Create two environments (Prod and Dev) in Rancher, with some hosts and stacks. Prod as default.
- Login to Rancher and you will be redirected to Prod environment.Click on Infrastructure.
- Open new tab. Go to rancher and switch to Dev, and than click Infrastructure.
- Now go to first tab and refresh the page, now you will see the infrastructure for Dev, not Prod.

Expected:
- Environment to not be "cookie/session based" rather persistent part of the URL. This will also solve the issue of sending URL to others.

Side note: Actually I find the "default environment" feature not so useful in my case. I prefer to have a list of my environments summary view as default page, see #3362 . No need to default to one environment at all.

**Comment by vincent99** [comment]
As you've already noted, this is the same as #677.  If you want to login to the environment list, bookmark http://rancher:8080/settings/environments (though that requires https://github.com/rancher/rancher/issues/3238, in the next release)
