### ISSUE TITLE
[cli] Make validating checksums easier

### ISSUE THREAD

**Issue by JensHeinrich** [rancher/rancher#33640]
There is a [flag](https://github.com/drone-plugins/drone-github-release/blob/000476c40572c3c2aad2bc6c4cac67d7bf1444e9/cmd/drone-github-release/config.go#L49) in the drone-github-release plugin to flatten the paths in the checksum file that would enable users to just do a 

```sh
$ sha256sum --check sha256sum.txt --ignore-missing                                              
rancher-linux-amd64-v2.4.11.tar.xz: OK
```

(This was after editing the file to remove the `dist/...` paths)

**Comment by genexpr** [comment]
We use this flag in a few other `rancher` repositories, such as `rke2`, `terraform-controller`, and about 30 others. Which is good, because there is no inconsistency, file path flattening for a checksum file is used where it's needed.

**Comment by brendarearden** [comment]
Available to test on v2.6.3-rc1

**Comment by phillipsj** [comment]
I just tested this and it seems that the following fails with the 2.6.3 RC2 release on Github.

```
sha256sum --check sha256sum.txt --ignore-missing rancher-images.txt 
sha256sum: sha256sum.txt: no file was verified
sha256sum: rancher-images.txt: no properly formatted checksum lines found
```

This file doesn't appear to be flattened and still includes the `bin` prefix.

@brendarearden

**Comment by genexpr** [comment]
@phillipsj, this change is for the `rancher/cli` repo, not the main `rancher/rancher`. The issue is in this project on purpose, but the PR above is in the CLI repo. Also, looks like there has already been an v2.6.0 RC-2 release of the CLI, and the paths are properly modified in the checksum file.

https://github.com/rancher/cli/releases/tag/v2.6.0-rc2

**Comment by phillipsj** [comment]
@genexpr okay, I will test that then.

**Comment by phillipsj** [comment]
This has passed dev validation.

```
sha256sum sha256sum.txt --check --ignore-missing rancher-windows-386-v2.6.0-rc2.zip 
rancher-windows-386-v2.6.0-rc2.zip: OK
```
