### ISSUE TITLE
Rancher terminates, exit code 255

### ISSUE THREAD

**Issue by catastrophe-brandon** [rancher/rancher#33651]
**Rancher Server Setup**
- Rancher version: master-head (image id a20ba111b9a0)
- Installation option (Docker install/Helm Chart):
   - Docker install
- Proxy/Cert Details:
- Machine created in Digital Ocean w/ 1 CPU and 2GB of RAM 

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - local

**Describe the bug**
After running for a while, Rancher will eventually exit with exit code 255.

**To Reproduce**
Fire up an instance of Rancher like this:
`sudo docker run -d -p 80:80 -p 443:443 --privileged rancher/rancher:master-head`
Use the cluster per normal use cases.
- For example, try to create an RKE1 cluster in Digital Ocean, then delete it.
Eventually, the docker container will exit.

**Result**
Here is a link to a gist with the exit code and relevant log details: https://gist.github.com/catastrophe-brandon/79dcfc580878fd9f800df2d7bb3493d1

**Expected Result**
Rancher should remain operational and not exit.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by sowmyav27** [comment]
Similar issues seen - https://github.com/rancher/rancher/issues/32080 and https://github.com/rancher/rancher/issues/33461#issuecomment-875993595

**Comment by catastrophe-brandon** [comment]
Updated issue description with CPU and RAM specs of the machine used to test.

**Comment by vincent99** [comment]
There's a minimum responsiveness etcd needs before it decides to give up and your node is not hitting that.

We specify [4gb of RAM](https://rancher.com/docs/rancher/v2.5/en/installation/requirements/#docker) as the minimum and you're probably spending all your time in swap.

**Comment by catastrophe-brandon** [comment]
After upgrading my machine to meet the minimum specs I have not encountered this issue again. Closing this issue.
