### ISSUE TITLE
Validate SLES 15SP3

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33669]
Validate SLES 15SP3 on latest master

**Comment by sowmyav27** [comment]
To Validate:

- Deploy HA cluster using Rke version: v1.3.0-rc9 and SLES 15SP3 nodes. 
- Deploy a downstream clusters using SLES 15SP3 , run validation checks on the downstream cluster
- Deploy v1/v2 charts on the downstream clusters

**Comment by thehejik** [comment]
This is the new SLE 15 SP3 AMI `ami-003b3754d4faa4bbe` in `us-east2` region for `ec2-user`

By using this AMI:
* I was able deploy HA local cluster by using rke-v1.3.0-rc9 k8s `v1.21.1-rancher2-1` and with `rancher/rancher:master-head`
* I deployed a downstream RKE1 EC2 cluster (1 cp+etcd, 3 workers) with k8s `v1.21.1-rancher2-1` and ran the needs_cluster test #2544 - custom services, ingress and secrets (environment not supported anymore - know issue) were failing.

**Comment by sowmyav27** [comment]
v1/v2 tools deployment was validated. Separate bugs filed.
