### ISSUE TITLE
After upgrade to 2.5.9 clicking on explorer for downstream cluster jumps back to login screen

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rancher#33667]
**Rancher Server Setup**
- Rancher version: 2.5.8 upgraded to 2.5.9
- Installation option (Docker install/Helm Chart): helm chart on RKE2

**Information about the Cluster**
- Kubernetes version: v1.20.8+rke2r1 (local and downstream)
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): v1.20.8+rke2r1 imported

**Describe the bug**
In the clusters view - click on "Explorer" for the downstream cluster -> jumps back to rancher login screen
In case I click on explorer for "local cluster" - the problem does not happen.

**To Reproduce**
Tried with firefox, chrome and edge
Tried with local user (admin) and with ldap user (admin)
Tried with cluster member (user01)
-> all show the same problem

**Result**
Can not use explorer as it always jumps back to the authentication screen

**Expected Result**
Does not jump back to authentication screen

**Additional context**
Before the upgrade from 2.5.8 to 2.5.9 this issue was not there.
When accessing the explorer for "local" cluster -> this works - but then switching to imported cluster -> login screen

**Comment by Martin-Weiss** [comment]
This is what I see on the agent:

`time="2021-07-19T12:11:14Z" level=error msg="Error during subscribe websocket: close sent"`

This is what I see on the rancher pod:

```
2021/07/19 12:13:19 [ERROR] Error during subscribe websocket: close sent
I0719 12:13:21.234595       9 leaderelection.go:253] successfully acquired lease kube-system/cattle-controllers
2021/07/19 12:13:21 [INFO] Steve auth startup complete
2021/07/19 12:13:22 [INFO] Reconciling GlobalRoles
2021/07/19 12:13:22 [INFO] Stopping cluster agent for local
2021/07/19 12:13:22 [INFO] Stopping cluster agent for c-8ktr9
2021/07/19 12:13:22 [INFO] Starting /v1, Kind=Pod controller
2021/07/19 12:13:22 [INFO] Starting catalog.cattle.io/v1, Kind=App controller
2021/07/19 12:13:22 [INFO] Starting catalog.cattle.io/v1, Kind=Operation controller
2021/07/19 12:13:22 [INFO] Shutting down rbac.authorization.k8s.io/v1, Kind=ClusterRole workers
2021/07/19 12:13:22 [INFO] Shutting down /v1, Kind=Endpoints workers

```

**Comment by Martin-Weiss** [comment]
After I destroyed the downstream cluster, deleted the cluster from rancher, re-deployed and re-imported the cluster - the issue seems to be gone..

Any idea how to find out what this happened / happens?

**Comment by slash1387** [comment]
Having the same issue, but I don't want to delete the cluster and loose all our settings...any other workaround that problem possible?

**Comment by sp0cket** [comment]
Same issue

**Comment by ikogan** [comment]
This is happening for our _production_ cluster. We cannot drop/re-add it. We've made no changes and we don't have any special Grafana ini settings in our monitoring chart.

**Comment by Martin-Weiss** [comment]
Have seen this problem also with "local cluster" in customer environment. 
Any idea what might be causing this problem?

**Comment by Martin-Weiss** [comment]
Still have this problem.
