### ISSUE TITLE
Unable to authenticate Rancher with Github

### ISSUE THREAD

**Issue by nikhil-naidu** [rancher/rancher#33666]
**Rancher Server Setup**
- Rancher version: 2.5
- k3s version: v1.21.1+k3s1

**Information about the Cluster**
Hosted in GCP VMs with a LB (HA). 2 Ubuntun nodes with k3s

**Describe the bug**
Unable to set up Github authentication from security > authentication with error: server error while authenticating: can't find unique user for principal github_user

**To Reproduce**
Go to Security > Authentication
Select Github
Create a new Oauth app in Github, obtain Client ID and Client Certificate
Authenticate

**Result**
server error while authenticating: can't find unique user for principal github_user

**Expected Result**
Github authentication should be successful

**Screenshots**
![image](https://user-images.githubusercontent.com/76752101/126023447-d29d92a7-c88d-4008-9258-fc36a928fca6.png)

**Additional context**
I'm trying to figure what the issue is with the existing HA Rancher setup. I had to resize the VM a night before the occurrence of this issue. I'm not sure if it's related (working with Rancher for the first time)

**Comment by superseb** [comment]
Did you check on these existing issues for this error? https://github.com/rancher/rancher/issues?q=is%3Aissue+is%3Aopen+%22can%27t+find+unique+user+for%22
