### ISSUE TITLE
Validate openSUSE Leap 15.3

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33668]
Validate OpenSUSE(LEAP) 15SP3 on master

**Comment by sowmyav27** [comment]
Validate
- HA using this AMI - RKE version - 1.3.0-rc1 and Rancher chart version - 2.6.0-rc1
- Deploy downstream cluster using this AMI and run v3_needs jenkins on this cluster
- Deploy v1/v2 charts

**Comment by thehejik** [comment]
Validation report
* :ok: HA local cluster deployed successfully (3 nodes w all-roles)
* :ok: downstream RKE cluster deployed successfully by using AWS node driver (1 cp, 1 etcd, 3 workers)
* :ok: v3_needs_cluster `#120` ok (mainly due "field `environment` is deprecated" )

Versions:
* used latest `rke-v1.3.0-rc12`
* helm chart and images `rancher:v2.6.0-rc1`
* kubernetes version on local and downstream RKE clusters: `v1.21.3-rancher1-1`
* created new AMI `opensuse-leap-15.3-docker-20.10.6-gp2` with all the RKE requirements `ami-0452941f41a1b0608` with `kernel-default-5.3.18-59.16-default, docker-20.10.6`, without apparmor and/or selinux, firewalld disabled

TODO v1/v2 charts validation

**Comment by thehejik** [comment]
v1/v2 charts were successfully validated on the env described above. Close
