### ISSUE TITLE
Upgrade rancher logging to latest upstream

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#33672]
As of today the latest is https://github.com/banzaicloud/logging-operator/releases/tag/3.13.0

This contains bug fixes that our users will likely benefit from.  If a newer version is available when this issue is picked up we should consider it.

**Comment by paynejacob** [comment]
When we do this we should also start mirroring images from ghcr, these images have support for more cpu arches.

**Comment by sowmyav27** [comment]
Reopening for a few more checks

**Comment by ronhorton** [comment]
**PASS** verified in `2.6-head Commit ID f487c88`

**Clean Install Test**
1. Installed logging `100.0.0 3.15.00`
2. configured cluster output & flow
3. verified logs were flowing to the elastic search output

**Upgrade Test** 
1. upgraded released chart version `100.0.1 3.12.00` through rancher to chart `100.0.1 3.15.00`
2. edited yaml: `loggingOverlay.spec.fluentbit.grace=1` (newly exposed value)
3. verified logs resumed flowing after update

**Clusters types tested**

`Upgrade from 3.12.00 to 3.15.00`
1. DO RKE2 cluster
2. DO RKE1 cluster
3. Custom cluster with k8s version 1.22.3

`Clean install of 3.15.00`
1. GKE cluster
2. K3S cluster
3. EC2 RKE2 cluster
4. Custom cluster
5. EKS cluster
