### ISSUE TITLE
/v1/projects/:id will return accounts with kind != project

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#3367]
e.g. if you ask for http://rancher:8080/v1/projects/1a2 on a fresh install, you'll get back 
```
{
  id: '1a2',
  type: 'account',
  name: 'system',
  kind: 'system',
  state: 'inactive',
  // ...
}
```

Should return 404 because that ID is not a project.

**Comment by tfiduccia** [comment]
Version - 0.57.0-rc5
Verified fixed
