### ISSUE TITLE
Istio 1.11+

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#33683]
Istio 1.11 has been released. 

1.10 is EOL in November: https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases

**Comment by jiaqiluo** [comment]
Istio 1.11.4 patch release is out https://istio.io/latest/news/releases/1.11.x/announcing-1.11.4/

**Comment by brendarearden** [comment]
Available to test on v2.6.3-rc1

**Comment by vivek-infracloud** [comment]
**Tested Istio charts for version 100.1.0+up1.11.4, Kiali - v1.41.0, and Jaeger - v1.27.0.**
**Tested following scenarios. all the tested scenarios passed the checks.**

- Fresh install checks
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Reinstall
- Istio pointing to externally-installed Prometheus
- Multiple ingress
- Egressgateway

Istio 1.11, Kiali 1.41 and Jaeger 1.27 are working fine for all the tested scenarios.

**Comment by vivek-infracloud** [comment]
On rancher/rancher:v2.6-head (5b56b17)

Create a downstream cluster with 2worker, 1etcd, 1 cp

**Tested Istio charts for version 100.1.0+up1.11.4, Kiali - v1.41.0, and Jaeger - v1.27.0.**
**Tested following scenarios. all the tested scenarios passed the checks.**

- Fresh install checks
- Upgrade test case from istio 1.10.x —> 1.11.4
- Upgrade with custom overlay
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Reinstall
- Istio pointing to externally-installed Prometheus
- Multiple ingress
- Egressgateway

Istio 1.11, Kiali 1.41 and Jaeger 1.27 are working fine for all the tested scenarios.
