### ISSUE TITLE
When another user accesses my rancher, it says dark and come in light themed

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3368]
version - 0.56.0-rc1

Steps:
1.  Go to your rancher and change to dark theme (make sure you are unauthenticated)
2.  Go to a different browser and go to rancher and try to change to dark theme

Results:
Notice the dark theme is already selected even thou the theme is currently light

Expected:
Dark should not be selected if the theme is not showing up.

**Comment by vincent99** [comment]
This was fixed last night but didn't make it into build..

**Comment by tfiduccia** [comment]
Waiting for #3007 to be fixed to verify this is fixed.

**Comment by vincent99** [comment]
#3007 should be fixed now if you restart master..

**Comment by tfiduccia** [comment]
Version - master 1/29
Verified fixed
