### ISSUE TITLE
Unable to create custom rke2 cluster with specific names

### ISSUE THREAD

**Issue by kravciak** [rancher/rancher#33694]
**Bug description**

I am not able to create custom rke2 cluster with specific names.
After creation screen is stack at `Loading...`, trying to access it from cluster list has the same result.
```
# UI error
Clusters.management.cattle.io "mkravec-oracle" not found

# rancher container log
[ERROR] error syncing 'fleet-default/mkravec-oracle': handler cluster-create: clusters.management.cattle.io "mkravec-oracle" not found, requeuing
```

![Screenshot from 2021-07-12 13-57-21](https://user-images.githubusercontent.com/538604/125283899-26d34680-e319-11eb-8e22-8f0adcc930d4.png)

**How to reproduce**

Dashboard -> Cluster management -> Create (rke2) -> Custom -> `name` -> Create
```bash
# does not work with: 
mkravec-oracle
mkravec-xxxxxx
xxxxxxc-xxxxxx
xxxxxc-xxxxx

# works fine with
xxxxxz-xxxxx
xxxxc-xxxx
```

**Rancher setup**
kubernetes: v1.21.2+rke2r1
rancher: single node docker 
version: master-head (3ae6f43)

**Comment by kravciak** [comment]
This does not seem right, I can create `local` cluster, but not `c-local`.

![Screenshot from 2021-07-29 21-55-11](https://user-images.githubusercontent.com/538604/127560384-ced1463d-2649-4efa-86cb-b2d46fc8dc06.png)

Tested on master-head (37561eb)

**Comment by deniseschannon** [comment]
Since we expect "local" and "c-XXXXX" cluster names to be reserved for clusters created in the provisioning v1 framework, this will currently cause issues. 

For now, can we add a UI check to not allow those names? @vincent99

**Comment by kravciak** [comment]
Could we also add some information about name reservations and error message?
Currently screen is stack at `Loading...` for 30s and then returns `clusters.management.cattle.io "c-xxxxx" not found` error.

**Comment by deniseschannon** [comment]
Created this UI ticket for the UI validation: https://github.com/rancher/dashboard/issues/3585

@kravciak By adding in UI validation, the error message should indicate what names can't be used.

**Comment by ronhorton** [comment]
I was able to create custom clusters with the provided names. I did not receive the error; I also went on to register my clusters and see them become active. In addition, I created an infrastructure provider cluster using a provided name and did not get an error.

**Comment by thedadams** [comment]
Although the UI has a name filter in place, it was possible to create a cluster with name "local" or with the format "c-xxxxx" through the API.

Changes are now merge so that the backend now validates the cluster name and creating a cluster with such a name should not be possible.

**Comment by ronhorton** [comment]
pass - verified in v2.6-45dfeb4f363bffec8ce8cf929ace75352e5fdb26-head
got UI error - Cluster name cannot be 'local' or take the form 'c-xxxxx'
API - got error 422 ```"message": "admission webhook \"rancherauth.cattle.io\" denied the request: cluster name cannot be \"local\" nor of the form \"c-xxxxx\"",```
