### ISSUE TITLE
Make token hashing a two way feature flag

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#33703]
**Is your feature request related to a problem? Please describe.**
Currently the token hashing feature flag is designed to be one way. That is that when it is enabled it cannot be disabled.

**Describe the solution you'd like**
Make it so the feature flag can be toggled on and off.

**Describe alternatives you've considered**

**Additional context**
Verifying tokens has been changed where it should be abled to handle both hash and non-hashed tokens. This will makes it less complicated to make it so token hashing can be toggled. Dashboard does not have an api validator in the same way that norman does and no logic for feature flags has been added to the webhook. Therefore, the one way feature flag may confuse users because it will appear as though they can toggle the feature flag; the change won't actual toggle token hashing currently.

**Comment by rmweir** [comment]
It is too late in the current release cycle to implement this. Adding this issue so it can be worked on in v2.6.x, ideally v2.6.2.

**Comment by Gby56** [comment]
Quick question regarding the feature: I assume it's hashed because otherwise API tokens are stored plaintext ?
Or is there an encryption wrapping all that, sealed secrets or something ?
