### ISSUE TITLE
[EmberUI] Error: There is no route named  ingress

### ISSUE THREAD

**Issue by kravciak** [rancher/rancher#33729]
**Rancher Server Setup**
- Rancher version: master-head (0a0d07a)
- Installation option: Docker install

**Information about the Cluster**
- Kubernetes version: v1.20.7+k3s1
- Cluster Type (Local/Downstream): both

**Describe the bug**
I am not able to display Resources -> Load Balacing tab if any ingress exists.

**To Reproduce**
- go to Local cluster -> default namespace
- create workload (nginx:alpine)
- create ingress pointing to this workload (/ing pointing to nginx on port 80)
- save

**Result**
Ingress is stack at initializing and page fails to load on refresh

**Screenshots**
![Screenshot from 2021-07-22 16-00-42](https://user-images.githubusercontent.com/538604/126651860-c796ddbf-0337-4fe5-bdea-57ae088949db.png)

**Comment by sowmyav27** [comment]
Same as this - https://github.com/rancher/dashboard/issues/3518
