### ISSUE TITLE
Add Kubernetes 1.21 for Amazon EKS

### ISSUE THREAD

**Issue by adaliszk** [rancher/rancher#33723]
## Describe the solution you'd like
Seems like Amazon EKS now has an option to upgrade the Kubernetes to 1.21, would like to have that option to be selected in the Rancher UI.

## Describe alternatives you've considered
I've consireded to click the upgrade in the AWS Console, but not sure if that would break Rancher.

## Additional context
AWS Docs: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
![image](https://user-images.githubusercontent.com/5189131/126602941-f586bbb8-8c57-42a9-a96d-54d6ea135f22.png)

Upgrade option in AWS Console:
![image](https://user-images.githubusercontent.com/5189131/126602965-122afd7f-d4eb-4251-bc21-95e7594ab45b.png)

Kubernetes options in Rancher UI:
![image](https://user-images.githubusercontent.com/5189131/126603060-9475d79c-f647-435b-b0e5-39c55297a483.png)

**Comment by cbron** [comment]
1.21 is added in 2.6.0
