### ISSUE TITLE
Not able to access Rancher from chrome

### ISSUE THREAD

**Issue by namanbajpayi** [rancher/rancher#33725]
i am not able to access rancher from chrome. 
I installed rancher on eks . 

in logs i am getting

2021/07/22 09:19:30 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/07/22 09:19:30 [ERROR] Failed to serve peer connection 10.0.181.50: websocket: close 1006 (abnormal closure): unexpected EOF

2021/07/22 09:20:19 [ERROR] error syncing 'u-t6ctvqvrex': handler mgmt-auth-userattributes-controller: secrets "cattle-system/u-t6ctvqvrex-secret" not found, requeuing

**Comment by superseb** [comment]
Please provide the information requested in the issue template, what version, what EKS version, how did you install it (exact commands used), what does Chrome report when you try to visit it, you are specifying as it does not work in Chrome, does it work in other browsers (Firefox for example), what does `curl -vLk https://rancher.yourdomain.com` output?
