### ISSUE TITLE
Refreshing the kiali v1.35.0 page results in 404 page doesn't exist

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33739]
**Rancher Server Setup**
- Rancher version: master-head 9e0d1b2
- Installation option (Docker install/Helm Chart): Docker install
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
   rke2/rek1 infrastructure provider

**Describe the bug**
Kiali service link results in a ` 404 The page you were looking for doesn't exist!` error
If the page is not refreshed, it works fine

**To Reproduce**
1. Install istio v1.10.2 version with kiali v1.35.0 and jaeger v1.35.0 enabled.
2. Click on the service link of kiali from cluster --> istio --> kiali
3. Refresh the page

**Result**
Refreshing the page results in an error `404 The page you were looking for doesn't exist!`

**Expected Result**
Refreshing the page shouldn't result in the above mentioned error

**Screenshots**
<img width="400" alt="Screen Shot 2021-07-22 at 11 27 26 AM" src="https://user-images.githubusercontent.com/38144301/126697350-5cdf21bf-a2da-4472-927b-537cdf8696df.png">

**Additional context**

Redirecting URL for v1.35.0 version of kiali looks different from the v1.32.0 version of kiali:

**v1.35.0:** `<ip>/kiali/console/overview?duration=600&refresh=15000`
**v1.32.0:** `<ip>/k8s/clusters/c-zqjp4/api/v1/namespaces/istio-system/services/http:kiali:20001/proxy/kiali/console/overview?duration=60&refresh=15000`

Ref: https://github.com/rancher/rancher/issues/32529

**Comment by cbron** [comment]
Since this has limited impact I am moving to 2.6.1, and we'll release note it.
You can still view Kiali data, the auto refresh works on the graph, you can navigate and look through the sidebar and into the data on each page, you just cannot refresh the browser page.

**Comment by blackholeshadow** [comment]
Hi all, 
![image](https://user-images.githubusercontent.com/67875978/133142346-24a7afc6-bae8-4d7b-866d-db2a60b234da.png)
![image](https://user-images.githubusercontent.com/67875978/133142369-1d457cea-9ccb-42ab-a935-3efb0e588526.png)
 I have two RKE2 rancher 2.6 managed clusters where I installed the latest Istio version from rancher 2.6  main chart.... Istio-ingress seems to work fine but when i go to the kiali UI and tried to get the GRAPH of current running services I am getting this on both clusters .... Anyone ? seems like Kiali is missing some roles/cluster-roles and therefor is denied access to mesh and namespaces. it alternates between the first screen shot and the second one.....Ok after almost going crazy... here is the situation: If i do a port-forward to Kiali everything is fine no errors... If i create a Gateway/VirtualService to Kiali everything is fine no errors... So the only path not working is via Rancher 2.6 Application shortcut. Hope that helps someone figure out the source of the problem.

**Comment by doflamingo721** [comment]
Waiting for upstream kiali to merge https://github.com/kiali/kiali/pull/4914 PR which fixes this issue.

**Comment by doflamingo721** [comment]
Added the fix for this issue as a part of https://github.com/rancher/charts/pull/1883 PR.

**Comment by vivek-infracloud** [comment]
Validated on rancher v2.6-head(25381f9)

Steps followed:

Install istio v1.10.2 version with kiali v1.35.0 and jaeger v1.35.0 enabled.
Click on the service link of kiali from cluster --> istio --> kiali
Refresh the page

- Provisioned a k8s `v1.23.6-rancher1-1` AWS node driver (1-cp, 1-etcd, 3-worker) downstream cluster
- Installed Monitoring chart `100.1.2+up19.0.3`
- Installed Istio : `100.3.0+up1.13.3` with Kiali v1.50.0 and jaeger v1.33.0 enabled.
- Click on the service link of Kiali from cluster. Istio ---> Kiali
- Refresh the page.

Result:
Refreshing the page **doesn't** result in 404 error.

Issue is resolved. Hence closing the issue.
