### ISSUE TITLE
Unable to update cni config

### ISSUE THREAD

**Issue by zhouwei517** [rancher/rancher#33731]
Rancher:2.5.9
CPU: arm64
Network Provider: rancher/coreos-flannel:v0.13.0-rancher1

1.The first node, Node Role is etcd,Control Plane, worker, the Cluster is OK。
2.The second node，Node Role is worker only,  the Cluster is NG。

docker logs kubelet:
I0722 15:09:33.439071    8980 csi_plugin.go:1039] Failed to contact API server when waiting for CSINode publishing: Get "https://127.0.0.1:6443/apis/storage.k8s.io/v1/csinodes/ecs-2929": dial tcp 127.0.0.1:6443: connect: connection refused
E0722 15:09:33.505770    8980 kubelet.go:2263] node "ecs-2929" not found
I0722 15:09:33.579767    8980 container_manager_linux.go:490] [ContainerManager]: Discovered runtime cgroups name: /system.slice/docker.service
E0722 15:09:33.603612    8980 eviction_manager.go:260] eviction manager: failed to get summary stats: failed to get node info: node "ecs-2929" not found
E0722 15:09:33.605887    8980 kubelet.go:2263] node "ecs-2929" not found
E0722 15:09:33.706009    8980 kubelet.go:2263] node "ecs-2929" not found
E0722 15:09:33.806136    8980 kubelet.go:2263] node "ecs-2929" not found
W0722 15:09:33.821000    8980 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
E0722 15:09:33.906253    8980 kubelet.go:2263] node "ecs-2929" not found
E0722 15:09:34.006395    8980 kubelet.go:2263] node "ecs-2929" not found
E0722 15:09:34.106528    8980 kubelet.go:2263] node "ecs-2929" not found
E0722 15:09:34.206671    8980 kubelet.go:2263] node "ecs-2929" not found
E0722 15:09:34.306808    8980 kubelet.go:2263] node "ecs-2929" not found
E0722 15:09:34.406952    8980 kubelet.go:2263] node "ecs-2929" not found

**Comment by superseb** [comment]
Worker's kubelet talk to kube-apiserver via the `nginx-proxy` container, what is in the log of the `nginx-proxy` container?

**Comment by zhouwei517** [comment]
> Worker's kubelet talk to kube-apiserver via the `nginx-proxy` container, what is in the log of the `nginx-proxy` container?

docker logs nginx-proxy：
/usr/bin/nginx-proxy: line 4: /usr/bin/confd: cannot execute binary file: Exec format error
2021/08/24 00:56:37 [notice] 8#8: using the "epoll" event method
2021/08/24 00:56:37 [notice] 8#8: nginx/1.20.1
2021/08/24 00:56:37 [notice] 8#8: built by gcc 10.2.1 20201203 (Alpine 10.2.1_pre1) 
2021/08/24 00:56:37 [notice] 8#8: OS: Linux 4.18.0-80.7.2.el7.aarch64
2021/08/24 00:56:37 [notice] 8#8: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/08/24 00:56:37 [notice] 8#8: start worker processes
2021/08/24 00:56:37 [notice] 8#8: start worker process 9
2021/08/24 00:56:37 [notice] 8#8: start worker process 10
2021/08/24 00:56:37 [notice] 8#8: start worker process 11
2021/08/24 00:56:37 [notice] 8#8: start worker process 12

**Comment by superseb** [comment]
Can you share `docker info` from the host?

**Comment by zhouwei517** [comment]
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-80.7.2.el7.aarch64
 Operating System: CentOS Linux 7 (AltArch)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 15.38GiB
 Name: ecs-2887
 ID: 7PTH:7FF6:QZAJ:VCET:O7VA:JTYS:R4BO:D2GK:S2KE:HHFG:3FD6:UHYQ
 Docker Root Dir: /home/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  192.168.0.22:8082
  192.168.0.22:8083
  127.0.0.0/8
 Registry Mirrors:
  http://192.168.0.22:8082/
 Live Restore Enabled: false

**Comment by superseb** [comment]
`cannot execute binary file: Exec format error` usually means running the binary on the wrong arch, given the insecure registries configured, you are running private registry/airgap. Can you check on the registry if the right arch is mirrored (manifest present)?

Also, ARM is experimental so there is no guarantee it actually all works but we can check it out.

**Comment by zhouwei517** [comment]
manifest：
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3872,
         "digest": "sha256:f36765102ed639554224db6fed0aa52ebc8b5febc51d856e278ca584518f3cf0",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3872,
         "digest": "sha256:a0ff196fa629320d9b9f6bf8493f806c632e51a557a5accbc1a3e6e6daab1d68",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 6343,
         "digest": "sha256:b9fa185e3cff67bf3f1e032c9c9828e41696bf3d58887ebda07adef5f4bd1a61",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.1935"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 6351,
         "digest": "sha256:c0490f3e6a1f6ca1d672ff725849063d7e34dcd05cab061fc56c2c4401e6fb6d",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.19041.985"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 6761,
         "digest": "sha256:fe21182104ec9faeaa17f82f87a94b64446489b9a66170edf38d5cd3c4b93130",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.19042.985"
         }
      }
   ]
}

**Comment by superseb** [comment]
What `rancher/rke-tools` image tag is on the machine and being used? If you run it manually, does it work in any version or not at all? (`docker run rancher/rke-tools:v0.1.77 /usr/bin/confd` or `docker run rancher/rke-tools:v0.1.77 /usr/bin/nginx-proxy`)

**Comment by zhouwei517** [comment]
# docker run rancher/rke-tools:v0.1.77 /usr/bin/nginx-proxy
Unable to find image 'rancher/rke-tools:v0.1.77' locally
v0.1.77: Pulling from rancher/rke-tools
595b0fe564bb: Already exists 
fa54502dbfa6: Pull complete 
d2cb09b9e6aa: Pull complete 
7ef83e7b3a3b: Pull complete 
80a3065a2c7e: Pull complete 
c83609e9cc59: Pull complete 
a79da5c6684b: Pull complete 
8568912ec4f2: Pull complete 
4c06f7b082e3: Pull complete 
8b0040696bd5: Pull complete 
495a43917821: Pull complete 
316605964ad5: Pull complete 
590250677b81: Pull complete 
063eb085b76f: Pull complete 
674e33ae7e2d: Pull complete 
56087c94f0a9: Pull complete 
4364c34fa087: Pull complete 
Digest: sha256:06db824a06398b6c286c59f49d727c25f6c345e280e551c757a625a26e87dab4
Status: Downloaded newer image for rancher/rke-tools:v0.1.77
/usr/bin/nginx-proxy: line 4: /usr/bin/confd: cannot execute binary file: Exec format error
2021/08/25 09:45:06 [notice] 8#8: using the "epoll" event method
2021/08/25 09:45:06 [notice] 8#8: nginx/1.21.0
2021/08/25 09:45:06 [notice] 8#8: built by gcc 10.2.1 20201203 (Alpine 10.2.1_pre1) 
2021/08/25 09:45:06 [notice] 8#8: OS: Linux 4.18.0-80.7.2.el7.aarch64
2021/08/25 09:45:06 [notice] 8#8: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/08/25 09:45:06 [notice] 8#8: start worker processes
2021/08/25 09:45:06 [notice] 8#8: start worker process 9
2021/08/25 09:45:06 [notice] 8#8: start worker process 10
2021/08/25 09:45:06 [notice] 8#8: start worker process 11
2021/08/25 09:45:06 [notice] 8#8: start worker process 12

**Comment by zhouwei517** [comment]
rancher/rke-tools image tag is 0.1.75（rancher/rke-tools:v0.1.75），but v0.1.77 has the same issues

**Comment by superseb** [comment]
Still unclear to me why it doesn't work for you, I tested it on EC2 ARM instance and it worked. What instances/devices are you using? Are you airgapped? Can you try specifically for the arm64 image (`docker run rancher/rke-tools:v0.1.77-linux-arm64 /usr/bin/nginx-proxy`) ?
