### ISSUE TITLE
Delete ca-certs setting if cert is public in system-agent

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#33736]
> "The cacerts setting will always end up being somewhere in kubeconfig if you use public certs. In old agent there is specifics logic to check if server url has public certs then remove the ca-certs setting when talking to rancher if cert is public" (@strongmonkey)

Solving this issue likely includes changes to system-agent.

**Comment by deniseschannon** [comment]
@snasovich We found this during team triage and since it referenced system-agent which was introduced for RKE2 provisioning, I brought it into the milestone to review.

**Comment by snasovich** [comment]
cattle-system-agent probably does something to address this; need to research and apply the same to system-agent / Rancher

**Comment by jiaqiluo** [comment]
we should investigate:
- if the `--no-cacerts` works in this case
- if the provision still works

Also, we need to find out all the possible cases around installing Rancher with/without public CA certs in either Helm or Docker installations.

**Comment by paynejacob** [comment]
I confirmed --no-cacerts removes the ca certs from the kubeconfig on rancher v2.6-head
