### ISSUE TITLE
Red ! tooltip should take user to access control page when clicked

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3374]
version - master 1/21

Steps:
1. Click on the red ! next to Admin menu item... the tooltip that says "Access not Configured".

Results: Takes me to First screen of Admin (Audit Log)

Expected:  If possible, I think if I click directly on the tooltip, it should take me to Access Control

**Comment by vincent99** [comment]
It is linked there, but link inside a link (`<a href="admin">Admin <a href="access control">!</a></a>`) is no bueno.

**Comment by westlywright** [comment]
@vincent99 i'll fix this in tooltip pr right now

**Comment by tfiduccia** [comment]
Version - master 1/27
Verified fixed
