### ISSUE TITLE
Downstream clusters on an upgrade to master-head are going into `updating` state

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33749]
**Rancher Server Setup**
- Rancher version: post upgrade- master-head be7cdb8, pre upgrade v2.5.3
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 
- Proxy/Cert Details: self signed

**Information about the Cluster**
- Kubernetes version: v1.17.17, v1.18.20, v1.19.12
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
Infrastructure Provider 1 node all roles

**Describe the bug**
Downstream clusters upon upgrading the rancher server go into `updating` state on the kubernetes versions v1.17.17, v1.18.20, v1.19.12.

**To Reproduce**
On v2.5.3, create 4 downstream clusters on each kubernetes version
Upgrade the rancher server to master-head

**Result**
All the downstream clusters go into updating state and are not available until the updating is done on the cluster.

**Expected Result**
Clusters on an upgrade should not go into `updating` state. They should go into an `unavailable` state and come up `Active

**Screenshots**
<img width="400" alt="Screen Shot 2021-07-23 at 11 41 12 AM" src="https://user-images.githubusercontent.com/38144301/126833550-2d740141-681e-4c63-a8f1-67fff24ccc58.png">

**Additional context**
The cluster on kubernetes version v1.16.15 does not go into `updating` state on an upgrade.

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to master-head commit id: `cd623b5d9`**

- Downstream clusters - k8s version - `1.20.8`
- Clusters dont go into Updating state. 
- They remain in Active state after the Upgrade

**Comment by anupama2501** [comment]
I tried upgrading the setup HA from rancher v2.5.3 with 4 downstream clusters having k8s `v1.19.13, v1.18.20, v1.17.17, v1.19.13`, I see for the k8s versions `v1.19.13, v1.18.20, v1.17.17` clusters go into `upgrading` state.

<img width="500" alt="Screen Shot 2021-07-30 at 4 21 35 PM" src="https://user-images.githubusercontent.com/38144301/127720614-99fd7934-5053-4065-9871-4f2285059684.png">

**Comment by ibuildthecloud** [comment]
The addition of the aci images to systemImages is triggering an upgrade when one shouldn't happen.   This is fixed in https://github.com/rancher/rancher/pull/33862

**Comment by anupama2501** [comment]
Verified on master-head 3499046
1. Created 4 downstream clusters on k8s versions `v1.16.15, v1.17.17, v1.18.20, v1.19.13` on rancher server `v2.5.3`
2. Upgraded the rancher version to master-head 
3. Verified the clusters didn't go into `upgrading` or `updating` state.
4. Only cluster with k8s v1.16.15 has gone through `unavailable` state and back to `active`, clusters on k8s v1.18, v1.19, v1.17 remained in `active` state.
5. Verified the system project for `cattle-node-agent` and `cattle-cluster-agent` have been upgraded to master-head.
