### ISSUE TITLE
How to link containers in Rancher UI ? 

### ISSUE THREAD

**Issue by ray2211** [rancher/rancher#33740]
i have 2 workloads librenms and mysql in same namespaces "librenms"
how can i link mysql to my librenms app

Rancher info v2.5.7

**Comment by vincent99** [comment]
There are no "links" in kubernetes like there were in docker/cattle.  You just refer to them by their DNS name, usually `<service name>.<namespace>.svc.cluster.local`

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#namespaces-of-services

**Comment by ray2211** [comment]
Thanks for your answer
