### ISSUE TITLE
Failed to parse private key when trying to add Oracle Cloud credentrials 

### ISSUE THREAD

**Issue by dveni** [rancher/rancher#33748]
**Rancher Server Setup**
- Rancher version: master-b6bcfad3e1510f84580e4de97cabe290553b392a-head, helm version: v2.16.8-rancher1
- Installation option (Docker install/Helm Chart):
   - Helm chart on a OKE cluster (Oracle Cloud)

**Information about the Cluster**
- Kubernetes version: v1.20.8
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
* Hosted = OKE (Oracle Cloud Infrastructure)

**Describe the bug**
Error parsing the private key when trying to create a cluster in the oracle cloud

**To Reproduce**
1. Activate OKE Oracle Cloud driver
2. Left nav bar -> Cluster management -> Create a cluster -> Oracle OKE
3. Add cluster name, tenancy OCID, user OCID, region, user fingerprint, user private key (in PEM format as requested)
4. Click on "Next: Authenticate & Configure cluster"

**Result**

 I get the following error:
`can not create client, bad configuration: x509: failed to parse private key (use ParsePKCS8PrivateKey instead for this key format)`

**Additional context**
I'm using one of the last rancher versions in dev because I was testing the new OIDC authentication feature.

**Comment by noahjd** [comment]
I came across this problem as well. I was able to resolve this by manually creating the API keys via the CLI without a key password.

**Comment by xhs** [comment]
@noahjd Thank you. You really save my day. The console generated key just doesn't work.
