### ISSUE TITLE
DNS resolution does not work for clusters with 1.21 k8s version

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33755]
**Rancher Server Setup**
- Rancher version: master-head commit id: `cd623b5`
- Installation option (Docker install/Helm Chart): Single install

**Information about the Cluster**
- Kubernetes version: 1.21.1-rancher1-1
- Cluster Type (Local/Downstream): Downstream - Custom RKE1 cluster

**Describe the bug**
DNS resolution does not work for clusters with 1.21 k8s version

**To Reproduce**

- Deploy a custom cluster RKE1 on k8s 1.21
- Using Ember UI, Deploy a couple of workloads in project p1 and namespace ns1
- Deploy a service discovery dns to workload wk01
- From wk02, curl on the dns record, 

```
curl dns.test-56796.svc.cluster.local
curl: (6) Could not resolve host: dns.test-56796.svc.cluster.local
```

**Expected Result**
DNS resolution should work.

**Comment by sowmyav27** [comment]
**On master-head, commit id: `3499046f`**

- DNS resolution doesnt work when the workloads and DNS records are created through the API 
- This selector is not available for DNS records created through API. 

```
"selector": {
"workloadID_dns": "true"
},
```
Setup has been provided to @superseb and he is looking into it.

**Comment by anupama2501** [comment]
Verified on master-head f04ae9f

DNS records are working when created through v3 API
Verified the validations tests have passed.
