### ISSUE TITLE
Rancher pods restart with fleet errors

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#33752]
**Rancher Server Setup**
- Rancher version: `master-head` `version be7cdb8` 
- Installation option (Docker install/Helm Chart): HA install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 k8s version `v1.19.6`

**Describe the bug**
Rancher pods are restarting in HA and hosted Rancher setups. Repeated fleet errors are seen in Rancher logs.

**To Reproduce**
Bring up a Rancher v2.6 HA setup (3 nodes, all roles, t3.xlarge) and leave the setup running.
View Rancher pods in System project deployments.

**Result**
Rancher pods are restarting:
![Screen Shot 2021-07-23 at 5 43 52 PM](https://user-images.githubusercontent.com/57409052/126852621-ac6870ba-b13d-441a-884b-d57d053ea361.png)

Repeated errors are seen in Rancher logs:
```
[ERROR] error syncing 'cluster-fleet-local-local-1a3d67d0a899': handler namespace-auth: Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io "p-h8dmm-namespaces-readonly": StorageError: invalid object, Code: 4, Key: /registry/clusterroles/p-h8dmm-namespaces-readonly, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 245d6429-b13f-4129-8e4e-c273816e5415, UID in object meta: , requeuing
2021/07/24 00:42:30 [ERROR] error syncing 'cattle-fleet-clusters-system': handler namespace-auth: Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io "p-h8dmm-namespaces-readonly": StorageError: invalid object, Code: 4, Key: /registry/clusterroles/p-h8dmm-namespaces-readonly, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 245d6429-b13f-4129-8e4e-c273816e5415, UID in object meta: , handler resourceQuotaSyncController: projects.management.cattle.io "local/p-h8dmm" not found, handler resourceQuotaUsedLimitController: projects.management.cattle.io "local/p-h8dmm" not found, requeuing
2021/07/24 00:42:30 [ERROR] error syncing 'fleet-local': handler namespace-auth: Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io "p-h8dmm-namespaces-readonly": StorageError: invalid object, Code: 4, Key: /registry/clusterroles/p-h8dmm-namespaces-readonly, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 245d6429-b13f-4129-8e4e-c273816e5415, UID in object meta: , handler resourceQuotaSyncController: projects.management.cattle.io "local/p-h8dmm" not found, handler resourceQuotaUsedLimitController: projects.management.cattle.io "local/p-h8dmm" not found, requeuing
2021/07/24 00:42:30 [ERROR] error syncing 'fleet-local': handler namespace-auth: Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io "p-h8dmm-namespaces-edit": StorageError: invalid object, Code: 4, Key: /registry/clusterroles/p-h8dmm-namespaces-edit, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 539e3d53-9834-4278-b1a3-4067a85eceea, UID in object meta: , requeuing
```

**Additional context**
These errors are not seen on single install master-head.
These errors are also seen on a hosted Rancher setup.

**Comment by nickgerace** [comment]
> These errors are not seen on single install master-head.

Pretty strange that non-HA doesn't encounter it. Fleet should not care how it is deployed.
CC: @StrongMonkey

**Comment by nickgerace** [comment]
@aaronRancher: I see this in single node as well on `master-head`.
```
[ERROR] error syncing 'local': handler provisioning-cluster-create: failed to create fleet-local/local provisioning.cattle.io/v1, Kind=Cluster for provisioning-cluster-create local: namespaces "fleet-local" not found, requeuing
```

**Comment by nickgerace** [comment]
@aaronRancher: I checked on both HA and single node with @kinarashah. These appear to be transient errors and are expected. The gitjob, fleet-controller, and fleet-agent pods come up in a reasonable amount of time and are running. Did they fail in your usage?

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version b395238`

Gitjob, fleet-controller, and fleet-agent workloads are healthy.
![Screen Shot 2021-08-03 at 12 29 47 PM](https://user-images.githubusercontent.com/57409052/128074927-e6865722-8972-4500-a704-3a7e7be7a6e7.png)
Closing issue as these errors are expected.
