### ISSUE TITLE
Hosted Rancher pods are not deployed to all nodes

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#33754]
**Rancher Server Setup**
- Rancher version: `master-head` `version be7cdb8` 

**Describe the bug**

Hosted Rancher pods are not deployed to all nodes.

**To Reproduce**
 
- Bring up a hosted Rancher v2.6 setup. Make sure the tenant cluster has at least 2 nodes.
- On the hosted cluster Rancher setup, view the tenant cluster system workloads.

**Result**
Rancher pods are not shown deployed on all nodes. The pods are all on a single node.
![Screen Shot 2021-07-23 at 6 13 48 PM](https://user-images.githubusercontent.com/57409052/126853446-d1b89918-e527-40e1-84cc-c5311895227a.png)

**Comment by deniseschannon** [comment]
Have we confirmed that there were 2 worker nodes? 

There is only a soft anti-affinity rule meaning that it's preferred, but it's not required unless you force it to be a hard requirement.

**Comment by aaronRancher** [comment]
There were multiple worker nodes. As affinity was not set as a hard requirement, this is expected.
Closing issue, as there is no specific fix needed.
