### ISSUE TITLE
Unable to use dataplane v2 with GKE

### ISSUE THREAD

**Issue by cgeeringh-ns** [rancher/rancher#33769]
Attribute datapath_provider is unavailable for GKE rancher2 deployments.

https://cloud.google.com/kubernetes-engine/docs/how-to/dataplane-v2

https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest/examples/simple_regional_beta?tab=inputs

https://github.com/rancher/rancher

**Comment by br0nwe** [comment]
Yes we also need dataplane v2 :)
