### ISSUE TITLE
Add ability to edit Certification so I can change description

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3376]
version - 0.56.0-rc1

Comments:  Can't edit a cert.  Since there is a description, i think I should be able to change that at the very minimum.

**Comment by sshipway** [comment]
+1 , though I think the description is used as an identifier so changing it might be problematic.

The case I'm thinking of is when you are replacing a soon-to-expire certificate.  In this case, you want to keep the original name and identification if it is referred to by various load balancers, so you cant create a new one with a different name.  It would be helpful to be able to go in and just replace the crt PEM (and then you would do a rolling restart of all the relevant load balancer containers)

**Comment by vincent99** [comment]
@sshipway You may be thinking of Name, which is used in rancher-compose..  Descriptions are always strictly for humans to store arbitrary notes and see it later.

The cert and chain are editable in the API, but not the private key (I think just as a side-effect of it not being readable).  So there's no UI for it but updating a cert theoretically works now if you haven't re-keyed.

In general I think we were thinking you're better off adding a new cert and updating balancers to use it, which you could easily un-do or test on a dummy balancer.  As opposed to editing the cert, immediately breaking everyone if you, say, don't notice that the middle chain cert changed this year, and having no way to easily go back to the previous state.

**Comment by sshipway** [comment]
Ah yes, I'm confusing Name and Description a bit.  It's good that they can be edited via the API (I've just verified that it works fine under 0.51), but it would be easier if they could be edited via the normal UI as well.

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc3
