### ISSUE TITLE
[Backport] Rancher 2.5 (Single Install) not starting after nf_conntrack_max value adjustment

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#33762]
We need to make a backport of rancher/rancher#33360 to fix this in v2.5.10.

**Comment by sowmyav27** [comment]
Related k3s PR: https://github.com/k3s-io/k3s/pull/3343

**Verified on 2.5-head - commit id: `07131035`**

- K3s - `v1.19.13+k3s1` docker install works and rancher comes up active

**Comment by nickgerace** [comment]
We should consider re-opening this or creating a new issue based on https://github.com/rancher/rancher/issues/33360#issuecomment-892749145
