### ISSUE TITLE
Cluster auth tokens are not being created when kubeconfig-generate-token setting is false

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33771]
**Rancher Server Setup**
- Rancher version: master-head commit id: `2e6926b`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: 1.21.1
- Cluster Type (Local/Downstream): Downstream - RKE1 DO

**Describe the bug**
Cluster auth tokens are not being created when `kubeconfig-generate-token` setting is false. This issue is related to this https://github.com/rancher/rancher/issues/33474. I believe https://github.com/rancher/rancher/issues/33474 was closed after validation because a step was missing, it can be reproduced as long as the cluster endpoint context is used in the produced kubeconfig.

**To Reproduce**
1. set `kubeconfig-generate-token`  to "false"
2. create rke1 cluster
3. generate kubeconfig for cluster
4. run `kubectl config get-contexts`
5. run `kubectl config use-context <context-name>` where context name is the context using the cluster's endpoint.
6. run a kubectl command such as `kubectl get nodes`

**Results:**
The kubectl command will return an unauthed error and the following error will be repeatedly printed in logs:
```
2021/07/27 00:32:20 [ERROR] error syncing 'kubeconfig-u-9svh2jkkxv': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-u-9svh2jkkxv" not found, requeuing

```

**Expected:**
The kubectl command should work, and the error may show a few times since the token is created before the clusterauthtoken but should go away. the message will be changed to reflect that the clusterAuthToken has not been created __yet__.

___
### Original issue
**Describe the bug**
Errors seen in rancher logs - `error syncing 'kubeconfig-user-xqz7d.c-tz4pf': handler cat-token-controller` on using kubeconfig file when kubeconfig-generate-token is false

**To Reproduce**

- Deploy Rancher server
- Deploy a downstream RKE1 DO cluster
- Download kubeconfig for DO cluster
- Errors seen in Rancher logs:

```
2021/07/27 00:32:20 [ERROR] error syncing 'kubeconfig-u-9svh2jkkxv': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-u-9svh2jkkxv" not found, requeuing
2021/07/27 00:32:20 [ERROR] error syncing 'kubeconfig-u-9svh2jkkxv': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-u-9svh2jkkxv" not found, requeuing
2021/07/27 00:32:20 [ERROR] error syncing 'kubeconfig-u-9svh2jkkxv': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-u-9svh2jkkxv" not found, requeuing
2021/07/27 00:32:20 [ERROR] error syncing 'kubeconfig-u-9svh2jkkxv': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-u-9svh2jkkxv" not found, requeuing
2021/07/27 00:32:20 [ERROR] error syncing 'kubeconfig-u-9svh2jkkxv': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-u-9svh2jkkxv" not found, requeuing
```

**Comment by snasovich** [comment]
@StrongMonkey , is it related to fix done for https://github.com/rancher/rancher/issues/33474 ? cc: @cbron @SheilaghM

**Comment by StrongMonkey** [comment]
@snasovich I don't think they are related. But I could see there is something wrong in code logic. https://github.com/rancher/rancher/blob/a213e857b2d5d5931ae74804532133140ad8068d/pkg/controllers/managementuser/clusterauthtoken/token.go#L33-L37
We just return errors if we can't find token, which seems not right.

**Comment by sowmyav27** [comment]
**Reproduced on 2.6-head commit id: `10588ab` using steps:**

- Set kubeconfig-generate-token to false 
- Download kubeconfig
- No errors seen in rancher logs
- Use this kubeconfig from local
- Login when prompted
- Errors seen in rancher server
```
2021/08/04 19:59:27 [INFO] Creating token for user user-lvw5t
2021/08/04 19:59:27 [INFO] Creating token for user user-lvw5t
2021/08/04 19:59:27 [ERROR] error syncing 'kubeconfig-user-lvw5t.c-2qkrp': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-user-lvw5t.c-2qkrp" not found, requeuing
2021/08/04 19:59:27 [ERROR] error syncing 'kubeconfig-user-lvw5t.c-2qkrp': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-user-lvw5t.c-2qkrp" not found, requeuing
2021/08/04 19:59:27 [ERROR] error syncing 'kubeconfig-user-lvw5t.c-2qkrp': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-user-lvw5t.c-2qkrp" not found, requeuing
2021/08/04 19:59:27 [ERROR] error syncing 'kubeconfig-user-lvw5t.c-2qkrp': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-user-lvw5t.c-2qkrp" not found, requeuing
2021/08/04 19:59:27 [ERROR] error syncing 'kubeconfig-user-lvw5t.c-2qkrp': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-user-lvw5t.c-2qkrp" not found, requeuing
2021/08/04 19:59:27 [ERROR] error syncing 'kubeconfig-user-lvw5t.c-2qkrp': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-user-lvw5t.c-2qkrp" not found, requeuing
2021/08/04 19:59:27 [ERROR] error syncing 'kubeconfig-user-lvw5t.c-2qkrp': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-user-lvw5t.c-2qkrp" not found, requeuing
2021/08/04 19:59:28 [ERROR] error syncing 'kubeconfig-user-lvw5t.c-2qkrp': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-user-lvw5t.c-2qkrp" not found, requeuing
2021/08/04 19:59:29 [ERROR] error syncing 'kubeconfig-user-lvw5t.c-2qkrp': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-user-lvw5t.c-2qkrp" not found, requeuing
2021/08/04 19:59:32 [ERROR] error syncing 'kubeconfig-user-lvw5t.c-2qkrp': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-user-lvw5t.c-2qkrp" not found, requeuing
2021/08/04 19:59:37 [ERROR] error syncing 'kubeconfig-user-lvw5t.c-2qkrp': handler cat-token-controller: clusterauthtokens.cluster.cattle.io "cattle-system/kubeconfig-user-lvw5t.c-2qkrp" not found, requeuing
```

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f811996`:**

- Set kubeconfig-generate-token to false
- Download kubeconfig
- No errors seen in rancher logs
- Use this kubeconfig from local
- Login when prompted
- No errors seen in Rancher.

**Comment by struggle-t** [comment]
One solution to this problem is to restart control plane and worker nodes - this is happening at least once a fortnight for me, is there a better solution available?

**Comment by voarsh2** [comment]
I'm getting this error, somehow.........
The "new" Rancher dashboard doesn't load
![image](https://user-images.githubusercontent.com/60437695/215335012-402cd667-7efa-472b-ac31-8895bc4db55f.png)

But the old one does..........:
![image](https://user-images.githubusercontent.com/60437695/215335027-0d4fd8e6-52a0-4993-8c79-39375bca9244.png)
