### ISSUE TITLE
longhorn upgrade to new version

### ISSUE THREAD

**Issue by bilemedimkq** [rancher/rancher#33776]
The new version of longhorn V1.1.2 has been released. But I can't see the new version here. When will the Helm chart be updated?

![image](https://user-images.githubusercontent.com/42588052/127160310-868e0b3c-3a6d-43c5-9462-90061dc2d19b.png)

**Comment by bilemedimkq** [comment]
can someone answer?

**Comment by cbron** [comment]
dupe: https://github.com/rancher/charts/issues/1352
