### ISSUE TITLE
404s in browser dev console when viewing "Apps & Marketplace" for local cluster

### ISSUE THREAD

**Issue by catastrophe-brandon** [rancher/rancher#33778]
**Rancher Server Setup**
- Rancher version: master-head, 2e6926b
- Installation option (Docker install/Helm Chart): Docker Install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: N/A - Docker install.

**Information about the Cluster**
N/A - Docker install.

**Describe the bug**
Some 404 messages appear in the browser's dev console when visiting "Apps & Marketplace" for the local dev cluster.
Example:
```
GET https://host/v1/catalog.cattle.io.clusterrepos/rancher-charts?chartName=rancher-alerting-drivers&link=icon&version=100.0.0 404 (Not Found)
```

**To Reproduce**
1. Run Rancher via a docker install
2. Login by setting up the password, etc.
3. In the left-hand menu, under Explore Cluster, click "local"
4. In the left-hand menu, click "Apps & Marketplace"
5. Check the dev console, you will see several 404s relating to rancher-charts

**Result**
404s in the dev console.

**Expected Result**
I expected not to find errors in the dev console. (Maybe my optimism is unfounded?)

**Screenshots**
Not applicable, relevant messages from the console are found above.

**Additional context**
No additional context.

**Comment by deniseschannon** [comment]
I'm pretty sure this is because it's missing the icon in the chart as there are 4 of them and none of them have an icon in the chart. 

@catastrophe-brandon Can you list the 4 of them that are in the console?

**Comment by sowmyav27** [comment]
Related - https://github.com/rancher/dashboard/issues/3512#issuecomment-891554060
https://github.com/rancher/dashboard/issues/3512#issuecomment-891554809

**Comment by catastrophe-brandon** [comment]
Dev console log with IPs redacted attached, including 404s.

[dev_console.log](https://zube.io/files/rancher/b401f4c981fb5794ab9f7ed037b5fdbc-dev_console.log)
