### ISSUE TITLE
When I go to containers/certificate details screen, right menu doesn't clear

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3377]
version 0.56.0-rc1

Steps:
1.  Go to Containers screen (make sure you have a couple of containers
2.  Click on a specific container's right menu
3.  With the right menu up, click on container name
4.  Do the same in the Certificates screen

Results:  The right menu stays up
![image](https://cloud.githubusercontent.com/assets/11514927/12496460/1abef676-c053-11e5-85cb-3a62bb392fe1.png)

Expected:  Right menu should clear

**Comment by vincent99** [comment]
I think this was fixed a while ago..

**Comment by tfiduccia** [comment]
Version - master 3/8
Not fixed

**Comment by tfiduccia** [comment]
Version - master UI 3/17
Verified fixed
