### ISSUE TITLE
[v2.5] RKE v1.2.10 defaults to kubernetes v1.20.8

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#33780]
discussion here: https://github.com/rancher/rke/issues/2619

**Comment by anupama2501** [comment]
Verified on rancher version v2.5.9
- From https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.5/data/data.json verified the `default` version of k8s is 
```
"RancherDefaultK8sVersions": {
  "default": "v1.20.x"

 "RKEDefaultK8sVersions": {
  "default": "v1.20.9-rancher1-1"
 },
```

- Created a rancher server on HA with rke version `v1.2.11-rc0` and verified the default version of k8s in the cluster is `v1.20.9-rancher1-1`
- Installed rke version `v1.2.11-rc0`, created an rke cluster and verified the default version pulled is v1.20.9-rancher1-1`

```
INFO[0028] Pulling image [rancher/hyperkube:v1.20.9-rancher1]
```

```
rke config -l 
v1.20.9-rancher1-1

rke config -l -a
v1.19.13-rancher1-1
v1.20.9-rancher1-1
v1.18.20-rancher1-2
v1.17.17-rancher2-3
```
