### ISSUE TITLE
Mount points for deleted instances continue to be listed in the storage pool view. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3378]
Server version - V0.56.0-rc1

Steps to reproduce the problem:
Start glusterfs service.
Start convoy-gluster service.

Create a service with volume in  "convoy-gluster" volumedriver.

Once the service is started , storage pool view shows the volume in "active" state with all the mount points from the service of the container.

Delete the service.
storage pool view shows the volume in "inactive" state but continues to show all the mount points from the service of the container that is already deleted.

<img width="870" alt="screen shot 2016-01-21 at 2 35 54 pm" src="https://cloud.githubusercontent.com/assets/4266958/12496814/c1cffd7c-c04c-11e5-8c2b-b96665607509.png">

**Comment by rodolfojcj** [comment]
I created or cloned several containers using the same name (after deleting the previous one) and all of those "incarnations" ended up listed in the storage pool I see, showing its corresponding mount point. This makes a little cumbersome to identify which is the entry for the existing container in that point of time. Maybe this case is already recognized, but if not please consider it.

![storage-list-of-mount-points-with-purged-containers](https://cloud.githubusercontent.com/assets/458749/12873026/a8b6a7d2-cd85-11e5-9c44-cac5e9127339.png)

**Comment by tfiduccia** [comment]
Version - Master UI 3/17
Verified fixed
