### ISSUE TITLE
Cannot provision RKE2 cluster with multus CNI

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#33784]
**Rancher Server Setup**
- Rancher version: master-head `7738b25`
- Installation option (Docker install/Helm Chart): RKE1 Helm v1.20.7
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version: rke2 v1.21.3+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Digital Ocean

**Describe the bug**

Cannot use multus cni due to the string format using a plus instead of a comma.

**To Reproduce**
 
Attempt to bring up an rke2 cluster using multus cni.

**Result**
Unable to. config.yaml on node shows:
```

  "agent-token": "<redacted>",
  "cni": "multus+canal",
  "etcd-snapshot-retention": 5,
  "etcd-snapshot-schedule-cron": "0 */5 * * *",
  "node-label": [
    "rke.cattle.io/machine=aee9f288-7124-4685-9518-18e50c95d50b"
  ],
  "token": "<redacted>"
}
```

Note that the cni part should be: `cni: multus,canal` in this configuration.

**Expected Result**

CNI option should have a "," instead of a "+".

**Screenshots**

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/55997940/127209701-dd3a50f3-4960-420a-bd94-8b7802164ff1.png">
All of the multus options here should use a comma.

**Additional context**
<!--Add any other context about the problem here.—>
This changed after design discussions due to PR reviews on the rke2 side.

**Comment by deniseschannon** [comment]
On master-head `b395238`, I've validated the three multus + cni versions. 

Validated the cluster became active and verified the kube nodes had the appropriate CNI config.
