### ISSUE TITLE
Unable to create ingress on k8s v1.21.1-rancher2-1 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33792]
**Rancher Server Setup**
- Rancher version: master-head 01665d0
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version:  v1.21.1-rancher2-1
- Cluster Type (Local/Downstream): Downstream
Infrastructure provider rke1 

**Describe the bug**
Creating an ingress from ember UI or dashboard results in an error `Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io
`
**To Reproduce**
Create a downstream cluster 
From explore cluster --> create a workload
From Services --> create an ingress [Added a screenshot for the details given in ingress creation]

**Result**
Creation fails with the error `Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1beta1/ingresses?timeout=10s": context deadline exceeded`

**Expected Result**
Ingress creation should not have failed

**Screenshots**
<img width="500" alt="Screen Shot 2021-07-27 at 2 24 22 PM" src="https://user-images.githubusercontent.com/38144301/127229719-3e44f96a-3021-49f9-816a-5392ac6aacd8.png">

**Additional context**
Fails with the same error if tried from ember UI as well.

Related issue: https://github.com/rancher/rancher/issues/33067

**Comment by superseb** [comment]
@anupama2501 Does this consistently reproduce in every created cluster? Can you please share the setup to me where this is happening?

**Comment by anupama2501** [comment]
Hi @superseb It is seen on HA setup for kubernetes v1.21.1 Dm'ed you the setup details.

**Comment by superseb** [comment]
This happened because the admission-webhook for NGINX is listening on port `8443` but because we run it in `hostNetwork`, the address the kube-apiserver is trying to contact is `IP_OF_NODE:8443` and because that port is not added in the `rancher-nodes` security group, the request times out and the creation of the ingress fails.

**Comment by superseb** [comment]
The dilemma here is:

- We need port 8443 open for the webhook, which is enabled by default in the new nginx ingress template.
- This can be added to rancher/machine, but; won't change for existing node-driver setups and still requires a manual change to existing other setups
- Without the change, ingress cannot be created (as it fails to contact the webhook)

This will break for newly created and existing node driver clusters (as port 8443 is not in the security group) and existing custom cluster (as port 8443 is not in the users firewall as its a new requirement). Solving newly created clusters can be done by adding 8443 to the security group when creating a node with the node driver, but that won't fix the issue for existing node driver clusters. Solving the custom clusters is document/release note, and letting people add the port to their firewall. 

We could make the webhook optional (this will be not following upstream), so this won't break any clusters. If you decide to turn it on using a newly introduced flag, it can be documented as requirement to open port 8443. However, if we do this, the case where an user creates a new node driver cluster with that flag, the port will still not be added (as currently we have a fixed list of ports to be added), if we add it, it will always be added (wether the flag is enabled or not) as we currently only have the option to add a fix listed of ports. We can make this conditional by checking cluster config and if needed, add additional ports based on cluster config. This is a bigger change as we need to check cluster config and provide the extra port to machine.

So quick fix would be to add 8443 to the ports that machine opens/adds to security group, but that won't solve the ingress creation error on existing node driver/custom clusters that don't have that port in their firewall/security groups. If it's acceptable to release note that a new port needs to be added (8443) between control plane and workers nodes when you upgrade to k8s v1.21, then we can do it.

**Comment by paynejacob** [comment]
Are there any risks with the webhook being exposed outside the cluster?

**Comment by superseb** [comment]
I'm looking at that now

**Comment by SheilaghM** [comment]
@superseb - why did this get dropped into waiting for RC?  Are you waiting something else or can this go To Test?

**Comment by SheilaghM** [comment]
Please factor into Rancher

**Comment by anupama2501** [comment]
Verified on master-head b395238

Created an ingress on HA rancher server downstream cluster from ember UI and verified it has come active

**Comment by anupama2501** [comment]
verified on master-head 30574c2

Ran automated ingress tests - PASS
Created a cluster on v2.5.9 and upgraded the rancher server master-head 3e5f699
Upgraded the k8s version to v1.21.3-rancher1-1 and ran automated tests - PASS

**Comment by eumel8** [comment]
@anupama2501 @superseb  this affects also Kubernetes 1.20.12-rancher-1-1

additionally I got the error while changing Ingress resources:

```
error: ingresses.networking.k8s.io "cms" could not be patched: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: nginx.ingress.kubernetes.io/configuration-snippet annotation cannot be used. Snippet directives are disabled by the Ingress administrator 
```

which comes with the new config map parameter

```
kubectl -n ingress-nginx get cm ingress-nginx-controller

...
allow-snippet-annotations: "false" 
```

should be default "true"

**Comment by eumel8** [comment]
snippet cluster.yaml for RKE

```   
ingress:
  options:
    allow-snippet-annotations: "true" 
```
