### ISSUE TITLE
Installation of rancher fails with error: "[FATAL] secrets "rancher-token-48bj8" not found" during a migration after restore using rancher backups

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33794]
**Rancher Server Setup**
- Rancher version: master-head commit id: `baed9e9`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 - 1.21.1 k8s
- Proxy/Cert Details: rancher generated

**Information about the Cluster**
- Kubernetes version: 1.21.1
- Cluster Type (Local/Downstream): DO RKE1 downstream cluster deployed

**Describe the bug**
Installation of rancher fails with error: "[FATAL] secrets "rancher-token-48bj8" not found" during a migration after restore using rancher backups

**To Reproduce**
- On master-head, with no downstream, in the local cluuster, rancher-token- secret is available
```
cattle-system                            rancher-token-48bj8                                               kubernetes.io/service-account-token           3      9m57s
```
- Deploy a downstream RKE1 DO cluster
- Take a backup b1 after installing rancher backups in the local cluster
- Follow steps of migration from [here](https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/migrating-rancher/)
- In the helm install command, rancher pods fail to come up
- Error seen:
```
kubectl logs rancher-56f89648bb-2zqzj -n cattle-system
2021/07/27 23:38:33 [INFO] Rancher version 1adc8ef2d (1adc8ef2d) is starting
2021/07/27 23:38:33 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features:}
2021/07/27 23:38:33 [INFO] Listening on /tmp/log.sock
2021/07/27 23:38:33 [FATAL] secrets "rancher-token-48bj8" not found
```

**Expected Result**
Rancher pods should come up Active. User should be able to install Rancher after a restore.

**Comment by jiaqiluo** [comment]
Can be tested in `rancher-backup 2.0.0+up2.0.0-rc6`

**Comment by sowmyav27** [comment]
**On master-head commit id: `3499046fcd`**

- Rancher charts: `2.0.0+up2.0.0-rc7 `
- User is able to take a backup and restore to a new RKE1 cluster.
