### ISSUE TITLE
Rancher post delete hook failure on Upgrade from 2.5.8 to 2.5.9

### ISSUE THREAD

**Issue by eocsx** [rancher/rancher#33799]
**Rancher Server Setup**
- Rancher version: 2.5.8 and 2.5.9
- Installation option (Docker install/Helm Chart): helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Kubernetes v1.20.4, installed with rke1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.20.4
- Cluster Type (Local/Downstream): Local
 

**Describe the bug**
Hey guys, this may not be a bug per se, I am just wondering about how the rancher post delete job works on upgrades as I'm getting:
`The Job "rancher-post-delete" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1...}: field is immutable` 

**To Reproduce**
Create a three node Kubernetes cluster for Rancher deployment using rke1. Deploy Rancher 2.5.8 with helm. At this point, there already is a post-delete job created. A pod for this job appears in pending state - "0/3 nodes are available: 3 node(s) didn't match pod affinity/anti-affinity, 3 node(s) didn't satisfy existing pods anti-affinity rules." (@jiaqiluo: I don't get how this is done, as there are no (anti)affinity rules specified in pod or job spec, is this related to https://github.com/rancher/rancher/pull/33023?)

Update Rancher to version 2.5.9. At this point, the update command fails:

`The Job "rancher-post-delete" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"rancher-post-delete", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"app":"rancher", "chart":"rancher-2.5.9", "controller-uid":"d722184e-8a26-4312-8e92-16da97a29c74", "heritage":"Helm", "job-name":"rancher-post-delete", "release":"rancher"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"config-volume", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(0xc03002adc0), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil), CSI:(*core.CSIVolumeSource)(nil), Ephemeral:(*core.EphemeralVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"rancher-post-delete", Image:"docker-remote.artifacts.ruv.de/rancher/shell:v0.1.6", Command:[]string{"/scripts/post-delete-hook.sh"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar{core.EnvVar{Name:"NAMESPACES", Value:"fleet-system cattle-system rancher-operator-system", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"TIMEOUT", Value:"120", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"IGNORETIMEOUTERROR", Value:"false", ValueFrom:(*core.EnvVarSource)(nil)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"config-volume", ReadOnly:false, MountPath:"/scripts", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil), SubPathExpr:""}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(0xc00d3cfd40), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc00c4b9bc0), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"rancher-post-delete", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc00dd59c80), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable`

The old job works though and it does the required clean-up.

**Result**
The Rancher update fails because the Job object cannot be updated.
**Expected Result**
The Rancher Update to be successful

**Comment by axeal** [comment]
The post-delete-hook Job should only be run as a result of a `helm uninstall` operation. In an air-gapped installation, one needs to ensure the `--no-hooks` flag is passed to the `helm template` command, per the [Rancher air-gapped installation documentation](https://rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/air-gap/install-rancher/#2-render-the-rancher-template) to prevent incorrectly rendering the post-delete-hook Job manifest for an air-gapped install/upgrade.

**Comment by eocsx** [comment]
Thank you @axeal !
