### ISSUE TITLE
Out of the box Rancher has 2x Catalogues broken.

### ISSUE THREAD

**Issue by BloodyIron** [rancher/rancher#33802]
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart): Docker (method on main website page)
- Proxy/Cert Details: self-signed, testing

So I'm teh newb to Rancher and k8s still. I understand a lot of it conceptually, but I've spun up Rancher in a testing space for me to test it, break it, stuff like that.

Out of the box 4x of the included default Catalogues work, but 2x throw 403 errors. I suspect this is just incorrect URLs used, but i'm not sure, and this probably should get updated somewhere. Anyways, this is what I see on the catalogue page when each of the 2x baddy repos are refreshed:

Global	helm	https://kubernetes-charts.storage.googleapis.com/	master	
Unexpected HTTP status code 403 from [https://kubernetes-charts.storage.googleapis.com/index.yaml], expected 200	

Global	helm-incubator	https://kubernetes-charts-incubator.storage.googleapis.com/	master	
Unexpected HTTP status code 404 from [https://kubernetes-charts-incubator.storage.googleapis.com/index.yaml], expected 200

My google-fu didn't really turn up solutions, so unsure how to proceed. Plus IMO this shouldn't be broken out of the box ;P

**Comment by abhi1693** [comment]
I think rancher guys disabled these but here is an article for you to reference https://helm.sh/blog/new-location-stable-incubator-charts/. Maybe rancher will update the links in the future

**Comment by BloodyIron** [comment]
You're missing the point. If they're no longer accurate, used, or whatnot, then they either should be updated in the release version with the correct info or removed. But I'll check that out as an interim option, thanks.

**Comment by cbron** [comment]
As we move away from cluster manager to the cluster explorer, we are not including these catalogs as default options to enable, and they are already disabled in cluster manager which will eventually go away. Since this isn't a blocking problem I am going to close issue.

**Comment by BloodyIron** [comment]
Ahh okay, didn't know if they were going to be relevant at all for future direction. Considering moving away from Cluster Manager I can see why the effort to address this really isn't worth it. No worries! Thanks for the insight :)
