### ISSUE TITLE
when fqdn is present for a service , use it as the url for ports link. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3380]
Server version - V0.56.0-rc1

Add route53 template.

Create and activate service that has exposed ports.
ports link for the service should use  fqdn in the url instead of the host ipaddress.

<img width="1383" alt="screen shot 2016-01-21 at 4 10 00 pm" src="https://cloud.githubusercontent.com/assets/4266958/12499007/8b24654c-c05b-11e5-893c-6336bcb575c5.png">

**Comment by will-chan** [comment]
Closed due to inactivity.
