### ISSUE TITLE
existing `rancher-nodes` security group interferes with provisioning, `error: could not resolve host` during provisioning (EC2) for rke1/rke2

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#33803]
**Rancher Server Setup**
- Rancher version: master-head (1adc8ef)
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, 1.2.9, k8s v1.20.8
- Proxy/Cert Details: byo-valid certs
**Information about the Cluster**
- Kubernetes version: v1.21.3+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? EC2

**Describe the bug**
When using a subnet with an existing (older) security group, a single node cluster fails to provision with the error below:
```
Could not resolve host: ctw-mh2.qa.rancher.space
[ERROR]  000 received while testing Rancher connection. Sleeping for 5 seconds and trying again 
```
the cluster will stay in this state forever, for both rke1 and rke2

**To Reproduce**
* provision a cluster using ec2 (ask QA for full setup details)
  * select a subnet with an existing `rancher-nodes` SG, it should have 18 inbound rules (newer SGs only have 15)
  * Use the default value for everything else (i.e. rancher's default value for SG is to auto create a SG)

**Result**
Node fails to provision

**Expected Result**

node should provision when user leaves default values during provisioning.

**Screenshots**

<img width="775" alt="Screen Shot 2021-07-28 at 10 35 51 AM" src="https://user-images.githubusercontent.com/16691014/127369974-bb0e534e-cb41-4608-acbb-30355491053b.png">

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by ibuildthecloud** [comment]
I can't reproduce this. If DNS is failing to resolve that isn't really related to security groups we setup because we don't change the egress.  In this situation maybe egress to DNS is being blocked, but our default security groups don't do that.

**Comment by slickwarren** [comment]
on master-head (94bca99) I was also unable to reproduce this issue on a docker install of rancher with a downstream cluster in us-west-2, but did run into issues with an HA cluster (us-east-2) and a downstream cluster in us-west-2. 
This was likely an issue with rancher server being in a different region than the downstream cluster. This is a known issue with AWS/EC2.
