### ISSUE TITLE
Able to use volumes in "removed" state for new services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3381]
Server version - V0.56.0-rc1

Steps to reproduce the problem:
Start glusterfs service.
Start convoy-gluster service.

Create a service with volume say - "vol1" in "convoy-gluster" volumedriver.

Once the service is started , storage pool view shows the volume in "active" state with all the mount points from the service of the container.

Delete the service.
storage pool view shows the volume in "inactive" state.
Now delete this volume , so that it gets to "removed" state.

Before this volume gets to "purged" state , create a new service with this volume - "vol1" in "convoy-gluster" volumedriver.
Existing volume which is in "removed" state is used and its state gets to "active" state.

Is this the expected behavior ? We also have a "restore" option when in "removed" state , which gets the volume to "inactive" state

**Comment by cjellick** [comment]
@sangeethah this is expected behavior. We do a restore in this scenario.

**Comment by sangeethah** [comment]
Closing this issue as per the confirmation from @cjellick
