### ISSUE TITLE
Old fleet agent gets removed first before the newer one is deploy on rancher server upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33819]
**Rancher Server Setup**
- Rancher version: master-head commit id: `21ab02c`
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Kubernetes version: 1.20.9
- Cluster Type (Local/Downstream): Downstream

**Describe the bug**
Old fleet agent gets removed first before the newer one is deploy on rancher server upgrade

**To Reproduce**
- On a docker install of rancher, deploy a downstream cluster.
- Upgrade rancher to master-head
- In the local cluster --> System project --> Noticed Old fleet agent gets deleted first and the new fleet agent is available `rancher/fleet-agent:v0.3.6-rc7`

**Expected Result**
New fleet agent should get deployed first and then the earlier/old one deployed (0.3.5) in this case should get removed.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `10588abd`** 

- fleet - `rancher/fleet-agent:v0.3.6-rc8`
- On a docker install of rancher, deploy a downstream cluster.
- Upgrade rancher to 2.6-head from 2.5.9
- fleet-system namespace is available
- New Fleet agent is created and the old one gets deleted. This seems to happen simultaneously.

**Comment by nickgerace** [comment]
@sowmyav27 We moved the logic as close together as possible, but knew that it might happen simultaneously, or even with a gap (that's primarily why we took on the issue: to see if there was a small improvement to be made).

The reason why this is okay is that the `fleet-agent` is stateless and can be run/paused/etc. This behavior is expected.

**Comment by sowmyav27** [comment]
Closing this based on [comment](https://github.com/rancher/rancher/issues/33819#issuecomment-892688122)
