### ISSUE TITLE
Remove EKS deprecated k8s version 1.17.

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#33825]
Just putting this ticket together as a tracking ticket to make sure to remove k8s 1.17 from EKS for 2.6.2. We'll also have a similar backport issue that I will create for 2.5.x.

Amazon EKS is targeting early October and encouraging upgrades to 1.18 by then.
(https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)

**Comment by cbron** [comment]
This can be part of the EKSv2 KDM issue

**Comment by rmweir** [comment]
@cbron EKSv2 KDM was de-prioritized so this will now be updated how it normally is until EKSv2 support in KDM can be implemented.

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment


| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.6.2                                  |
| Rancher cluster type    | Single Node Docker Installs             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | EKS                                     |
| Downstream K8s version  | 1.18                                    |
| Browser type            | Google Chrome                           |
| Browser version         | 96.0.4664.45 (Official Build) (x86_64)  |
| Cloud credentials       | AWS Credentials set before steps        |

## Reproduction steps

1. Starting from the Rancher **default** homepage `/dashboard/home`
2. Click the `hamburger menue` -> click `Cluster Management` -> click `Create` -> click `Amazon EKS`
3. Start filling out the form to create an EKS cluster
    - Cluster Name: `test-eks-cluster-qa`
    - Click `Next: Configure Cluster`
    - Under Cluster Options: Kubernetes Version -> click and see the available versions
      - Available versions
        - 1.21
        - 1.20
        - 1.19
        - 1.18
        - 1.17
        - 1.16
      - See attached screenshot below labeled `A1`

![01-a1](https://user-images.githubusercontent.com/40877149/142078249-62c6083b-bbfe-47f6-8fa5-e2eb33152a55.png)

4. Observe the list of available Kubernetes versions and see that 1.17 and 1.16 are available  

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-6b00d71d60667a5fa878ddc3e2dc9df9e5bd78a8-head |
| Rancher cluster type    | Single Node Docker Install                         |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | EKS                                                |
| Downstream K8s version  | 1.21                                               |
| Browser type            | Google Chrome                                      |
| Browser version         | 96.0.4664.45 (Official Build) (x86_64)             |
| Cloud credentials       | AWS Credentials set before steps                   |

## Validation steps

1. Starting from the Rancher **default** homepage `/dashboard/home`
2. Click the `hamburger menue` -> click `Cluster Management` -> click `Create` -> click `Amazon EKS`
3. Start filling out the form to create an EKS cluster
    - Cluster Name: `test-eks-cluster-qa`
    - Click `Next: Configure Cluster`
    - Under Cluster Options: Kubernetes Version -> click and see the available versions
      - Available versions
        - 1.21
        - 1.20
        - 1.19
        - 1.18
      - See attached screenshot below labeled `A2`

![02-a2](https://user-images.githubusercontent.com/40877149/142078229-ca9c59c0-ba04-4238-81a3-526c1bf9b222.png)

4. The EKS deprecated k8s versions have been removed
