### ISSUE TITLE
[Backport 2.5] Istio 1.10.4

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#33824]
https://github.com/rancher/rancher/issues/32795

Add in the equivalent of https://github.com/rancher/charts/tree/release-v2.6/charts/rancher-istio/rancher-istio/100.0.2%2Bup1.10.4

But the version in for v2.5 should be v1.10.400. If we introduce this version, we would need to forward port v1.10.400 into Rancher v2.6.

**Comment by cbron** [comment]
Since 1.9.8 is going OOB into 2.5.10, this can wait till 2.5.11

**Comment by brendarearden** [comment]
Release note: This version is end of life, but is required for upgrade path in order to not skip a minor version

**Comment by rishabhmsra** [comment]
On **rancher 2.5-head** provisioned a downstream cluster with 1-cp, 1-etcd and 2 worker nodes.

However, no "Chart Repositories" are not showing up. Added a Chart Repository manually, but it remained in "In Progress" state. Couldn't install any charts (attached ss):
![repo-ss](https://user-images.githubusercontent.com/36376154/145205659-7805a02f-1938-41cf-90e9-6d8572994eb2.png)

**Comment by rishabhmsra** [comment]
Issue for chart repositories not showing up : https://github.com/rancher/rancher/issues/35820

**Comment by rishabhmsra** [comment]
**Verified on rancher v2.5-head** (9dab145)

**Created a downstream cluster with 2 worker, 1 etcd, 1 cp nodes.**

Tested below scenarios with istio `1.10.400`, kiali : `1.35.0` and jaeger : `1.20.0`. All the checks look good.

- Fresh install checks
- Upgrade istio from 1.9.800 —> 1.10.400 (after upgrade deployed book app and validated traffic and traces through kiali and jaeger)
- Upgrade with custom overlay
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Unistall/reinstall checks
- Istio pointing to externally-installed Prometheus
- Multiple ingress
- Egressgateway

**Result :**
- All the checks passed with istio `1.10.400`, kiali : `1.35.0` and jaeger : `1.20.0`
