### ISSUE TITLE
[Backport] Remove EKS deprecated k8s version 1.17

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#33826]
This is a backport of rancher/rancher#33825 - Amazon EKS is deprecating support on k8s 1.17 and this is a backport ticket to support it in the 2.5.x line.

**Comment by aiyengar2** [comment]
@Jono-SUSE-Rancher closing as this is a duplicate of an already closed ticket in https://github.com/rancher/rancher/issues/35515. Feel free to re-open if you disagree!
