### ISSUE TITLE
Cloud Credential options are available but fail for disabled node drivers

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#33821]
**Rancher Server Setup**
- Rancher version: v2.5.x
- Installation option (Docker install/Helm Chart): Any
- Proxy/Cert Details: N/A

**Describe the bug**
On an install of Rancher, the v1 cloud credentials are available to be created even if the node driver isn't activated, but it can't be created until the node driver is enabled.

**To Reproduce**
De-activate the Digital Ocean node driver.
Try to create a DO cloud credential. 

**Result**
Fail to create the cloud credential.

**Expected Result**
Do not show cloud credentials unless the node driver is active.

Fix is to filter what the list of available cloud credentials to create based on active node drivers or active cluster driver (EKS/AKS/GKE). Cluster drivers using Kontainer-engine v2 use the same cloud credential.

**Comment by yasker** [comment]
@guangbochen can you take a look? This is related to Harvester RKE1 node driver as well.

**Comment by deniseschannon** [comment]
Verified by enabling/disabling the Linode driver and the cloud credential list of providers only shows the enabled node drivers.
