### ISSUE TITLE
Istio v1 1.5.920 fails to install on an upgrade with the error `Failed to install app cluster-istio. Error: UPGRADE FAILED: release: "cluster-istio.v2" already exists`

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33838]
**Rancher Server Setup**
- Rancher version: master-head 37561eb
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.20.9 
- Cluster Type (Local/Downstream): Downstream custom SLES15 SP3 / Ubuntu
 

**Describe the bug**
Istio installation fails on an upgrade when we enable istio-ingress gateway while updating.

**To Reproduce**
Install istio without enabling the ingress-gateway
Once all the workloads are active and the app installs successfully, enable istio-ingress gateway

**Result**
Istio installation fails with the error ` Failed to install app cluster-istio. Error: UPGRADE FAILED: release: "cluster-istio.v2" already exists`

**Expected Result**
App should be installed upon an upgrade without the seen error

**Additional info**
If we uninstall istio and redeploy by enabling ingress-gateway, fails with the error : https://github.com/rancher/rancher/issues/33837

Similar issue seen for logging: https://github.com/rancher/rancher/issues/33839

**Comment by anupama2501** [comment]
Also seen when rancher installed v2.6.0-rc1 on RHEL SLES  `rhel-8.4-docker-20.10.7-selinux-on-rpm` 

Installed mysql app and on an upgrade of the app, fails with the error `Failed to install app anupre-app. Error: UPGRADE FAILED: release: "test-app.v2" already exists`

**Comment by anupama2501** [comment]
Performed the following validations:
Rancher version: `v2.6-rc4`, k8s `v1.21.4`, Local cluster O.S: `Ubuntu`

- Downstream cluster - ubuntu O.S and RHEL O.S,  k8s v1.20, 1.19 admin/standard user

1. Installed istio version v1.5.902
2. Updated istio by enabling ingress.
3. no issues while updating, istio app comes up active. For r.
4. Rancher server on RHEL O.S
5. Downstream cluster - ubuntu O.S and RHEL O.S,  k8s v1.20, 1.19 --> no issues while updating[changing the ingress enabled
6. istio app comes up active and no errors were seen.

Rancher version: `v2.6-rc4`, k8s `v1.21.4`, Local cluster O.S: `RHEL`
Same steps as above. Standard user, no issues were seen.

For admin 

- Ubuntu downstream cluster O.S:  if we update istio by enabling ingress-gateway, the installations shows the following error. 
- This happens sometimes and the app recovers from this error after sometime and comes active.

`Failed to install app cluster-istio. Error: UPGRADE FAILED: an error on the server ("unable to create impersonator account: error setting up impersonation for user user-qx4jr: Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io \"cattle-impersonation-user-qx4jr\": the object has been modified; please apply your changes to the latest version and try again") has prevented the request from succeeding (post clusterroles.rbac.authorization.k8s.io)`

**Comment by brendarearden** [comment]
I was unable to recreate this error following the provided steps.

**Comment by anupama2501** [comment]
Verified on v2.6-head 1a57856

- Created a rancher server on v2.6-head with rancher pods RHEL sles 
- Created a downstream node driver cluster with the nodes on RHEL sles [3 worker,1etcd, 1cp] as admin and enbaled legacy flag from global settings
- Created a local user and added the user in the downstream cluster as a cluster owner 
- As the cluster owner, installed istio v1 1.5.920 by disabling ingress gateway
- All workloads in istio-system came up active and the app has come up active too
- updated istio v1 installation by enabling ingress and the app has come up active.

Closing this issue and will re-open if its seen again in future
