### ISSUE TITLE
[Logging v1] fluentd:v0.1.28 is stuck in installing state

### ISSUE THREAD

**Issue by aaronyeeski** [rancher/rancher#33839]
**Rancher Server Setup**
- Rancher version: master-head 37561eb
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.20.9 
- Cluster Type (Local/Downstream): Downstream custom SLES15 SP3
 

**Describe the bug**
Logging v1 is stuck in installing state.

**To Reproduce**
From Rancher Ember UI, navigate to cluster > tools > logging
Enable fluentd logging. (version v0.1.28)
Navigate to cluster > System project > apps

**Result**
Logging installation is stuck with the error `Failed to install app rancher-logging. Error: UPGRADE FAILED: release: "rancher-logging.v2" already exists`
![Screen Shot 2021-07-29 at 2 30 39 PM](https://user-images.githubusercontent.com/57409052/127576035-e372bfe1-dca1-46e2-b939-9a1d454ba73f.png)

**Expected Result**
App should be installed without error.

**Comment by aaronRancher** [comment]
Was able to get past this error by disabling fluentd logging and reenabling it.

![Screen Shot 2021-07-29 at 4 23 48 PM](https://user-images.githubusercontent.com/57409052/127577798-19ad4aea-d1e7-4f3a-bea5-1e5f83500877.png)
![Screen Shot 2021-07-29 at 4 23 54 PM](https://user-images.githubusercontent.com/57409052/127577800-42532220-b41d-4e2d-b7ae-57b6c9b49574.png)

**Comment by deniseschannon** [comment]
@paynejacob Can you see if this is still reproducible? And if it is does the workaround still work?

**Comment by paynejacob** [comment]
Tested  on rke1 with 3 nodes.  HA rancher install `v2.6.0`

1. navigate to the local cluster
2. open tools and select logging
3. configure forward
4. click test, it succeded
5. click apply

the pods all came up and the app shows as installed.  I also see logs coming through in the output.

**Comment by deniseschannon** [comment]
@paynejacob This was logging v1, right?

**Comment by paynejacob** [comment]
yes

**Comment by anupama2501** [comment]
Verified on rancher HA RHEL local cluster rke1 `v1.21.4` , custom RHEL downstream cluster `v1.20.10`, logging `0.1.30`
1. Created a cluster with 3 worker, 1 etcd, 1 cp
2. Installed logging with `elasticsearch`
3. All the workloads `cattle-logging` are active and the app `rancher-logging` is active 
4. Disabled logging and enabled logging by adding fluentd
5. Verified all the workloads have come active and the app is active as well.
