### ISSUE TITLE
Istio v1 1.5.920 installation fails when ingress gateway is enabled on an SLES 15 SP3

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33837]
**Rancher Server Setup**
- Rancher version: master-head 37561eb
- Installation option (Docker install/Helm Chart): Helmchart 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.20.9
- Cluster Type (Local/Downstream): Downstream Custom SLES15 SP3
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

**To Reproduce**
Install istio v1.5.920 by enabling ingress-gateway
**Result**

- All the workloads in `istio-system` are active but the app `cluster-istio` is stuck in installing with the error `Failed to install app cluster-istio. Error: release cluster-istio failed: Service "istio-ingressgateway" is invalid: spec.ports[0].nodePort: Invalid value: 31380: provided port is already allocated`
- Even if we change the port multiple times, same error is seen for every port.

**Expected Result**
Should not have errored out for the default port we use for ingress-gateway

**Additional context**
If we deploy book demo app and verify with the allocated [failing] port, the traffic is seen going through the ingress-gateway

**Comment by mitulshah-suse** [comment]
@MKlimuszka this issue is for v1 charts which are already deprecated and would be disabled/removed in 2.7 with https://github.com/rancher/rancher/issues/37327 
Please confirm if this can be closed.

**Comment by MKlimuszka** [comment]
Closing this ticket since the Istio and k8s versions mentioned here are well out of support.
