### ISSUE TITLE
Cluster Tools should only show a subset of Charts

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#33841]
Currently, we're introducing Cluster Tools in 2.6 as an easy way to navigate and promote the cluster tools to be deployed on a chart. It shows all the feature charts in rancher/charts, which it shouldn't.

Here are the rules of what should be shown in Cluster Tools:

Cluster Tools will only show a subset of feature charts from the rancher/charts repo. Legacy charts will show up in cluster tools with feature flag of legacy on and will not rely on this logic to be shown in Cluster Tools. This logic of which charts will be shown only applies to feature charts. 

- Only show feature charts in Cluster Tools when specific annotation is on the helm chart (catalog.cattle.io/cluster-tool=true).
- Chart should have name and namespace as an annotation on the chart so that it's a cluster wide deployment.
- These annotations are:
```
- catalog.cattle.io/namespace: cattle-<RESOURCES>-system # Must prefix with cattle- and suffix with -system
- catalog.cattle.io/release-name: <APP_NAME> # If this is an upstream app, prefixing with rancher is the preferred naming choice.
```
- A chart should only be defined as a cluster tool if it will end up creating a special navlink on the sidebar, which indicates special UI is being built for this cluster tool. 
- Note: since cluster tools are a subset of charts in rancher/charts, they will continue to be shown and available in Apps & Marketplace.

Based on the list of rules, the following feature charts should get the new annotation on them.

**List of Cluster Tools**

Monitoring
Alerting Drivers
CIS Benchmarks
Istio
Logging
Longhorn
OPA Gatekeeper
Rancher Backups

After the feature charts have added the annotation, the UI will need to be updated to only show charts with the annotation.

**Comment by vincent99** [comment]
Let's do `catalog.cattle.io/type`=`cluster-tool` instead, that label already exists to differentiate a chart as being a regular `app` (default) vs `cluster-template` so this is a good 3rd case for that. 

Dashboard support will be in shortly and the existing charts will disappear until the label is added.

**Comment by brendarearden** [comment]
@vincent99 will that still allow for charts to show up in the app & market place, as well as the cluster tools page?

**Comment by vincent99** [comment]
@brendarearden Yes, the charts page shows all except where type == cluster-template.

**Comment by cbron** [comment]
> catalog.cattle.io/namespace: cattle-<RESOURCES>-system # Must prefix with cattle- and suffix with -system

Istio can't handle this, we had to put it in `istio-system`. Too many hardcoded namespaces in their tooling.

**Comment by deniseschannon** [comment]
I had grabbed that text from our docs on how to create feature charts.

**Comment by deniseschannon** [comment]
Validated that the only the subset of feature charts that have the specific cluster type is shown.
