### ISSUE TITLE
Question: Is there way to increase timout for loading index for Apps?

### ISSUE THREAD

**Issue by akazakou** [rancher/rancher#33847]
I've tried to connect https://charts.helm.sh/stable repo as an application provider. It's a huge repo and after adding to the rancher, the index is 10Mb size. Loading of that index takes ~ 40s for me. UI canceling loading this repo and not displaying charts for it.

Ideally, I would like to have some ConfigMap to control UI settings. Like timeouts, retry count and etc.

Is there exists way or workaround how to allow displaying huge repos in rancher UI?

![image](https://user-images.githubusercontent.com/326397/127628498-3a2b3246-42ff-46a9-946f-799bcc3e7da7.png)

**Comment by vincent99** [comment]
There is not; there's also no timeout in the Ui that I'm aware of, though there may be a default somewhere.

Also most of the charts in that  particular repo (helm-stable and -incubator) are deprecated for partly this reason; maintaining and using one giant repo is a pain, so people moved on to their own smaller repos.
