### ISSUE TITLE
eks-operator is not redeployed on cluster edit or create

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#33842]
**Rancher Server Setup**
- Rancher version: `master-head` `version 94bca99`
- Installation option (Docker install/Helm Chart): single docker install

**Describe the bug**

eks-operator is not redeployed on EKSv2 cluster edit or create

**To Reproduce**
 
Bring up Rancher v2.6 (`master-head` `version 94bca99`)
Deploy an EKSv2 cluster.
When cluster becomes available, delete the eks-operator deployment (eks-operator v1.1.1-rc8).
Edit the EKSv2 cluster.

**Result**
eks-operator is not redeployed and the cluster does not go into updating state. On cluster sync, all changes from Rancher UI are reverted. No changes are seen in EKS console.
Provisioning another EKSv2 cluster does not redeploy eks-operator. The new cluster will be stuck in provisioning state.

**Expected Result**

eks-operator should get redeployed

**Comment by deniseschannon** [comment]
Is this related to the generic change from KEv2 from system-charts to feature charts?

**Comment by aaronRancher** [comment]
@deniseschannon This is related to the generic change from KEv2. But this appears to be expeced.
Confirmed with @rmweir this is expected behavior when only the eks-operator deployment is deleted.

Was able to get past this with the following steps:
Navigate to Dashboard > local > Apps & Marketplace > Installed Apps (in system namespace)
Delete `rancher-eks-operator` app and `eks-operator-crd`
Redeploy the eks-operator deployment and app by provisioning a new EKSv2 cluster.

But I was not able to redeploy eks-operator by editing an existing EKSv2 cluster.

**Comment by cmurphy** [comment]
Discussed in slack - this is covered in the reopened issue https://github.com/rancher/rancher/issues/31592 so closing this as a duplicate.
