### ISSUE TITLE
Helm charts under Apps and MarketPlace section are not showing all versions of the charts which are available in the private chart repository

### ISSUE THREAD

**Issue by bj1074** [rancher/rancher#33844]
[](url)
Rancher is not showing all the helm charts which is available in repository...

Rancher UI charts version drop down screen shot
![rancherscreenshots](https://user-images.githubusercontent.com/81166635/127602419-7d0e67aa-f954-441a-a9e4-2702f46a6e4a.png)

Private helm repo tied with rancher containing helm charts 
![rancherscreenshots_repo](https://user-images.githubusercontent.com/81166635/127602545-3bb52f25-19dc-45a0-ace5-31c09ae93253.png)

**Comment by vincent99** [comment]
Anything with a dash in it is a prerelease and is hidden by default (unless it's the current version).

You can enable seeing them in the user menu (top-right) -> Preferences
