### ISSUE TITLE
Istio upgrade from v1.7.301 to v1.10.2 fails with the error `version: 1.7.3 does not match the target version 1.10.2` when policy is enabled in 1.7.301

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33843]
**Rancher Server Setup**
- Rancher version: master-head 21ab02c
- Installation option (Docker install/Helm Chart): Docker install 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: self signed 

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
   - Infrastructure provider - AWS 3 worker,1cp, 1etcd

**Describe the bug**
When policy is enabled in 1.7.301 and if we upgrade istio to either 1.9.6 or 1.10.2, installation fails with time out error 

**To Reproduce**
Create a cluster with 3 worker,1etcd and 1 cp
Install istio 1.7.301 with policy enabled
Upgrade istio to either 1.9.600 or 1.10.2

**Result**
Installation fails with the an error `Control Plane - policy pod - istio-policy-949f854b9-6s9h2 - version: 1.7.3 does not match the target version 1.10.2`

**Expected Result**
upgrade is expected to be successful

**Additional context**
On 1.7.301, policy is not by default enabled in the global options and has to be enabled before proceeding to install if needed. In versions from 1.8.x, policy is enabled by default

**Comment by cbron** [comment]
https://istio.io/latest/docs/setup/upgrade/
> Upgrading across more than one minor version (e.g., 1.6.x to 1.8.x) in one step is not officially tested or recommended.

@anupama2501 can you go from 1.7 to 1.8 to 1.9 to 1.10 ?

**Comment by deniseschannon** [comment]
@cbron Can we make a UI issue to see if we can inform the user of the recommended upgrade path? Tho istio might not recommend it, our UI doesn't do anything to help you realize that you need to go between minor releases and this path isn't supported by Istio.

**Comment by cbron** [comment]
https://github.com/rancher/dashboard/issues/3627

**Comment by cbron** [comment]
We'll likely bump this one. First need to investigate if my hunch is correct, if we can repro, if there's a workaround etc..

**Comment by deniseschannon** [comment]
@anupama2501 Can we re-test this with the recommended upgrade path?

**Comment by anupama2501** [comment]
@cbron I tried upgrading from 1.7.301 --> 1.8.600 --> 1.9.800 and it errored out. these are the logs I have from the istioctl-installer job

```
Switched to context "rancher-istio-context".
starting istioctl commands
client version: 1.9.8
control plane version: 1.8.6
data plane version: 1.9.8 (6 proxies), 1.8.6 (1 proxies)
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
running istioctl upgrade
2021-09-09T19:05:19.279698Z	info	proto: tag has too few fields: "-"
2021-09-09T19:05:19.382848Z	info	Error: failed to read the current Istio version, error: different versions of Istio components found: [istio-ingressgateway pod - istio-ingressgateway-6f5786b7cb-hcmg4 - version: 1.8.6 policy pod - istio-policy-75ff6cb478-gq7nf - version: 1.7.3 istiod pod - istiod-cc6d7ccfc-pkrmx - version: 1.8.6]
Error: failed to read the current Istio version, error: different versions of Istio components found: [istio-ingressgateway pod - istio-ingressgateway-6f5786b7cb-hcmg4 - version: 1.8.6 policy pod - istio-policy-75ff6cb478-gq7nf - version: 1.7.3 istiod pod - istiod-cc6d7ccfc-pkrmx - version: 1.8.6]
Control Plane - istio-ingressgateway pod - istio-ingressgateway-6f5786b7cb-hcmg4 - version: 1.8.6
Control Plane - policy pod - istio-policy-75ff6cb478-gq7nf - version: 1.7.3
Control Plane - istiod pod - istiod-cc6d7ccfc-pkrmx - version: 1.8.6
error found during istioctl upgrade
```

**Comment by brendarearden** [comment]
After checking through several different istio/istio sources, this is the recommended path to resolve these upgrade errors:

##### Check to see if you have resources to migrate

Run the following commands to generate a list of resources that will need migrated:
```
kubectl get policies.authentication.istio.io --all-namespaces
kubectl get meshpolicies.authentication.istio.io --all-namespaces
kubectl get rbacconfigs.rbac.istio.io --all-namespaces
kubectl get clusterrbacconfigs.rbac.istio.io --all-namespaces
kubectl get serviceroles.rbac.istio.io --all-namespaces
kubectl get servicerolebindings.rbac.istio.io --all-namespaces
```
If this does not output any resources, skip forward to the cleanup step.

##### Migrating Resources:
Using the resources that were output from the prevous section, determine if you would like to [migrate them manually](https://istio.io/latest/blog/2021/migrate-alpha-policy/ "migrate them manually") or utilize an [Istio provided tool](https://github.com/istio-ecosystem/security-policy-migrate "Istio provided tool"). Follow the Istio documentation to determine the specific changes you will need to make for your set up. 

Additional Resources about the security policy deprecation:
https://istio.io/latest/news/releases/1.6.x/announcing-1.6/upgrade-notes/#support-ended-for-v1alpha1-security-policy
https://istio.io/latest/news/releases/1.5.x/announcing-1.5/upgrade-notes/#authentication-policy

##### Cleanup

Run the following commands to finish cleanup:
```
kubectl delete clusterrbacconfigs.rbac.istio.io --all-namespaces
kubectl delete meshpolicies.authentication.istio.io --all-namespaces
kubectl delete policies.authentication.istio.io --all-namespaces
kubectl delete rbacconfigs.rbac.istio.io --all-namespaces
kubectl delete servicerolebindings.rbac.istio.io --all-namespaces
kubectl delete serviceroles.rbac.istio.io --all-namespaces
```
And finally remove the istio-policy deployment:
```
kubectl delete deployment istio-policy --namespace istio-system
```
Once you have completed the steps to migrate and cleanup resources, you are ready to upgrade to a newer version of istio. Reminder: Istio supports one minor version upgrade at a time to enusre the best upgrade path. It is not recommended to go directly to the latest version if it is more than one minor version up.

**Comment by cbron** [comment]
Assigning to @ryansann for dev-validate.

**Comment by ryansann** [comment]
I've validated that the instructions [here](https://github.com/rancher/rancher/issues/34699#issuecomment-921995917) also address the upgrade issue outlined above.

The steps I used to validate are:
- install monitoring and istio 1.7.301
- install book info app
- check & cleanup per upgrade instructions
- upgrade to istio 1.8.600
- upgrade to istio 1.9.600
- observe errors from istio-installer pod
```2021-09-21T21:45:17.380395Z     info    Error: failed to read the current Istio version, error: different versions of Istio components found: [istio-ingressgateway pod - istio-ingressgateway-6f5786b7cb-2hw9n - version: 1.8.6 policy pod - istio-policy-75ff6cb478-l44js - version: 1.7.3 istiod pod - istiod-cc6d7ccfc-br476 - version: 1.8.6]
Error: failed to read the current Istio version, error: different versions of Istio components found: [istio-ingressgateway pod - istio-ingressgateway-6f5786b7cb-2hw9n - version: 1.8.6 policy pod - istio-policy-75ff6cb478-l44js - version: 1.7.3 istiod pod - istiod-cc6d7ccfc-br476 - version: 1.8.6]
```
- check & cleanup per upgrade instructions
- upgrade to istio 1.9.600
- check & cleanup per upgrade instructions
- upgrade to istio 100.0.0+up1.10.4
- check book info app is functioning properly
