### ISSUE TITLE
Keycloak OIDC - Improve logging for refresh token

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#33852]
**Rancher Server Setup**
- Rancher version: `2.6 master-head` _94bca99_ or later
- Installation option : Any
- Proxy/Cert Details: `byo-valid` (but shouldn't matter for this issue)

**Describe the bug**
- When a refresh token request if made to extend the `Access Token Lifespan`, there's no indication in the Rancher server trace logs that this was done.

**To Reproduce**
- Enable Keycloak OIDC
- Enable Rancher server trace logging
- In the keycloak OIDC backend make sure to use a low value of `Access Token Lifespan`
- Wait more than the time value of the Token Lifespan
- Do a search in Auth Provider site access members input or in a cluster RBAC members add input.

**Result**

No logs about Keycloak actions are observed in the logs.
When a token is expired I see Errors logged but not for other tokens/sessions actions like token refresh

**Expected Result**
- Trace logs about session refresh in the Rancher server logs

**Comment by cbron** [comment]
Assigning ryan for dev-validate.

**Comment by cbron** [comment]
Ready for dev-validate

**Comment by ryansann** [comment]
This has been validated on rancher `v2.6-head (f6120e0)` 

Here are is the output that shows the refresh log:
![Screen Shot 2021-08-09 at 1 00 40 PM](https://user-images.githubusercontent.com/8824599/128767156-e42101f9-c03e-4b98-b009-492d8da005b9.png)
