### ISSUE TITLE
rke1 clusters are not showing up in cluster management page after creation

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33855]
rancher server master-head 76b0695

1. From cluster management page create an rke1 cluster either node driver or custom cluster
2. From cluster management page, the newly created cluster is not shown
3. It is shown only under explore cluster 

<img width="400" alt="Screen Shot 2021-07-30 at 11 11 51 AM" src="https://user-images.githubusercontent.com/38144301/127704519-bc939da2-cfcf-4e16-bc20-e7bbf9e3ebb3.png">

Additional info: 
rke2 clusters are shown in cluster management page. This seems to happen only for rke1 clusters.
I can link up my setup details if needed.

**Comment by ibuildthecloud** [comment]
This is failing because of some issue with the rancher-webhook

```2021/07/30 20:31:33 [ERROR] error syncing 'c-dpw5c': handler provisioning-cluster-create: failed to create fleet-default/c-dpw5c provisioning.cattle.io/v1, Kind=Cluster for provisioning-cluster-create c-dpw5c: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": EOF, requeuing
```

**Comment by ibuildthecloud** [comment]
This is reproducible with rancher/rancher:master-76b0695f4e1814597162bd3a6801c04cf8780128-head but not with master as of right now.  So somebody already fixed this.

**Comment by anupama2501** [comment]
Verified on master-head 3499046

rke1 clusters show up on the cluster-management page
