### ISSUE TITLE
Error message is right aligned instead of left

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3386]
version - 0.56.0-rc2

Steps:
1.  create a service or container with the image pointed to rancher/helloworld

Results:  the error message is right aligned and looks strange
![image](https://cloud.githubusercontent.com/assets/11514927/12523812/59b92a40-c116-11e5-94b2-58d0b6d9cb6c.png)

Expected:  Error message should be left aligned.

**Comment by lvuch** [comment]
@tfiduccia Does this only happen at a certain browser width?

**Comment by vincent99** [comment]
The state and dropdown are always right aligned, it just happens to not fit and wrap here...

**Comment by tfiduccia** [comment]
Version - master 3/8
Understood and closing
