### ISSUE TITLE
Upgrade Helm in Rancher

### ISSUE THREAD

**Issue by bjornjorgensen** [rancher/rancher#33869]
**Is your feature request related to a problem? Please describe.**
Try to install or config jupyterhub's helm chart in rancher v2.5.9. 

Add the repo https://jupyterhub.github.io/helm-chart/ 

Try to install or config it in rancher v2.5.9 

helm upgrade --history-max=5 --install=true --namespace=jhub --timeout=10m0s --values=/home/shell/helm/values-jupyterhub-1.1.1.yaml --version=1.1.1 --wait=true jhub /home/shell/helm/jupyterhub-1.1.1.tgz
Error: UPGRADE FAILED: parse error at (jupyterhub/templates/hub/_helpers-passwords.tpl:35): function "dig" not defined

**Describe the solution you'd like**
Function "dig" are in helm 3.5+ 

https://githubmemory.com/repo/jupyterhub/zero-to-jupyterhub-k8s/issues/2234

**Comment by cbron** [comment]
Closing this one as the linked issue will track the work needed.
