### ISSUE TITLE
Service/container stuck at starting if I have use quayio:/ in image

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3387]
Version - 0.56.0-rc1

Steps:
1.  Add quay.io as registry
2.  Add Service (or container) and put in image quayio:/rancher/helloworld

Results: The service container stuck at starting and never resolves.

Expected: I think it should tell me that the image "failed to pull" since the image is incorrect

**Comment by janeczku** [comment]
Also happens when the image name is correct but the registry server is down. Only recovers after doing a Rancher restart.

**Comment by hibooboo2** [comment]
Currently this is not the behavior container goes straight to error.

**Comment by tfiduccia** [comment]
Version - master 3/8
Verified fixed
