### ISSUE TITLE
system-agent should try connecting with no CA if initial connection with CA fails

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#33878]

**Comment by deniseschannon** [comment]
Run docker container behind ngrok

**Comment by kinarashah** [comment]
@Oats87 @deniseschannon system-agent comes up fine running docker rancher install behind ngrok. Node doesn't come up active tho, waiting for cluster-agent to be available.  Looks like a separate issue, but thought I'd confirm. 

Rancher logs: 
```
2021/08/04 20:57:03 [INFO] Failed to find providerID for selector rke.cattle.io/machine=4baae563-dea7-4cf6-83a5-1d25a27319d9 in cluster fleet-default/kinara-do-clusterd2, machine kinara-do-clusterd2-pool1-d9bc566c9-z2tm8: Get "https://7f083b7fdbe8.ngrok.io/k8s/clusters/c-m-6e51e355/api/v1/nodes?labelSelector=rke.cattle.io%!F(MISSING)machine%!D(MISSING)4baae563-dea7-4cf6-83a5-1d25a27319d9": x509: certificate signed by unknown authority
```

**Comment by Oats87** [comment]
@kinarashah Weird, I wonder what certificate authority is getting presented, I'd imagine it's the ngrok certificate authority. 

Are those logs directly in Rancher? Not sure why Rancher is connecting "through itself" rather than just directly dialing the downstream cluster.

I don't believe that this is related to the system-agent however.

**Comment by Oats87** [comment]
@kinarashah this is definitely a different issue. 

I don't think we should be using the kubeconfig in the form that is provided from the kubeconfig manager because that is the kubeconfig that would be for the "end user", we should be directly dialing downstream. 

https://github.com/rancher/rancher/blob/master/pkg/controllers/provisioningv2/rke2/machinenodelookup/controller.go#L104-L127

**Comment by kinarashah** [comment]
I am still seeing the same behavior as before. @deniseschannon based on @Oats87's comments above, it seems like a different issue that would need to be fixed. Is that fixed too? 

Tested with v2.6-head `9ef223886a31` built 19 hours ago.

**Comment by kinarashah** [comment]
System-agent fixes are in and have been validated. Going to open a new issue for error in rancher/ cluster-agent issue.
