### ISSUE TITLE
[backport] Downstream clusters on an upgrade to master-head are going into updating state 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#33876]
Backport fix for https://github.com/rancher/rancher/issues/33749. This would ensure upgrade logic on both 2.5.10 and 2.6 is same.

**Comment by anupama2501** [comment]
Verified on v2.5-head 6b04f9b

- Installed rancher server on v2.5.9
- Created 3 downstream rke1 node driver clusters with 3 worker, 2cp, 3 etcd nodes
- Ran pre-upgrade checks
- Upgraded the rancher server to v2.5-head
- Verified no clusters went into updating state and all clusters have come up active.
