### ISSUE TITLE
RKE2 Provisioning: Cluster Options - vSphere Cloud Provider

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#33875]
Since the vSphere cloud provider are separate Helm charts (vsphere CSI/CPI) that are bundled with RKE2, we need to specifically validate the workflow of using the vsphere cloud provider.

**Comment by deniseschannon** [comment]
This issue isn't to test if the vSphere charts are working as we know they should be cause they work with RKE1, but it's more that the workflow of being able to configure the external cloud provider with vsphere works along with provisioning the RKE2 cluster.

**Comment by PennyScissors** [comment]
This **FAILED** my checks. The cluster was provisioned, but none of the CSI and CPI resources were deployed.

Validated in rancher dev-v2.6 image commit 69055ba

Steps:
1. Provision an RKE2 cluster (in a vSphere node driver cluster). Select `vsphere` from the cloud provider dropdown, and configure CSI and CPI in the "Add-On Config" tab. Set the Data Center, vCenter Host, username, and password for both CSI and CPI, and use default values for the rest.
![Screen Shot 2021-08-13 at 5 52 37 PM](https://user-images.githubusercontent.com/8951271/129430371-8cc61465-b61b-4c18-bd6a-2dcc524730c6.png)

2. Verify CSI and CPI resources were deployed.
![Screen Shot 2021-08-13 at 6 21 59 PM](https://user-images.githubusercontent.com/8951271/129430381-0533faaf-b83c-4a7e-b1c3-00391989018c.png)

**Comment by PennyScissors** [comment]
Failed checks, the UI needs to be updated to use the new `rancher-vsphere` name. The warning to configure vsphere it in the `Add-On Config` tab and the section to configure CSI and CPI are missing.

**Comment by ibuildthecloud** [comment]
@PennyScissors The chart generates that secret from the template if generate is true. Otherwise we expect the user to manually populate the secret and set generate to false.

**Comment by PennyScissors** [comment]
Rancher v2.6-head 3c7f582 
RKE2 vsphere cluster 
K8s v1.21.4+rke2r1 

Failed checks:
There seems to be a winder problem in RKE2 vsphere cluster provisioning when the vsphere cloud provider is enabled that is causing RKE2 to restart repeatedly.



logs in `journalctl -u rke2-server`

![image](https://user-images.githubusercontent.com/8951271/131229712-c51acd0c-e384-4c54-85cf-02d605ecfab3.png)



output of `systemctl status rke2-server`

![image](https://user-images.githubusercontent.com/8951271/131229747-fa08e96f-d430-4401-8294-90914a5e493e.png)


docker logs:

```
2021/08/28 19:14:03 [DEBUG] Infrastructure provider is not ready, requeuing                                                                                                                                                                                         
2021/08/28 19:14:03 [DEBUG] Cannot reconcile Machine's Node, no valid ProviderID yet                                                                                                                                                                                
2021/08/28 19:14:03 [DEBUG] DesiredSet - No change(2) rbac.authorization.k8s.io/v1, Kind=RoleBinding fleet-default/screspo-rke2-bootstrap-template-czz7k-machine-plan for rke-machine fleet-default/screspo-rke2-bootstrap-template-czz7k                           
2021/08/28 19:14:03 [DEBUG] Auth filter calling provider to get extra info local                                                                                                                                                                                    
2021/08/28 19:14:03 [DEBUG] Triggering auth refresh on u-53x3stkwwz                                                                                                                                                                                                 
2021/08/28 19:14:03 [DEBUG] Unable to retrieve Node status, missing NodeRef                                                                                                                                                                                         
2021/08/28 19:14:03 [DEBUG] Searching for providerID for selector rke.cattle.io/machine=aaa33ab6-500d-4883-a1de-e4a2e962ccf0 in cluster fleet-default/screspo-rke2, machine screspo-rke2-pool1-5c674bd74c-dfqcc: {"Code":{"Code":"Forbidden","Status":403},"Message"
:"clusters.management.cattle.io \"c-m-h9c7z5x8\" is forbidden: User \"u-53x3stkwwz\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
```

**Comment by deniseschannon** [comment]
The external IP fix for cloud provider was merged after this commit. So this needs to be re-tested on a newer Rancher server version.

**Comment by PennyScissors** [comment]
Re-testing this with the latest commit.

**Comment by PennyScissors** [comment]
Failed checks:

RKE2 started successfully this time, but provisioning gets stuck trying to retrieve the node's status and searching for a provider Id when the cloud provider is set to vsphere (provisions fine when set to None). I can provide access to this setup if needed.

RKE2 server status:
![image](https://user-images.githubusercontent.com/8951271/131234010-bbd51894-369e-451f-b029-d3f686d9a618.png)

Provisioning stuck (1hr+)

![image](https://user-images.githubusercontent.com/8951271/131234104-f3799bb5-62ab-4435-b955-4f4192fb2931.png)


docker logs:

```
2021/08/29 00:03:52 [DEBUG] Auth filter calling provider to get extra info local
2021/08/29 00:03:52 [DEBUG] Triggering auth refresh on u-ik2u2arjg6
2021/08/29 00:03:52 [DEBUG] DesiredSet - No change(2) rke.cattle.io/v1, Kind=RKEControlPlane fleet-default/screspo-test-rke2 for rke-cluster fleet-default/screspo-test-rke2
2021/08/29 00:03:52 [DEBUG] Searching for providerID for selector rke.cattle.io/machine=0ea8c9fa-2585-4c04-b99f-b405180ad83c in cluster fleet-default/screspo-test-rke2, machine screspo-test-rke2-pool1-b474d556d-lwt8g: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-ljwk722n\" is forbidden: User \"u-ik2u2arjg6\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/29 00:03:52 [DEBUG] Skipping refresh for system-user u-ik2u2arjg6 
2021/08/29 00:03:52 [DEBUG] DesiredSet - No change(2) cluster.x-k8s.io/v1alpha4, Kind=Cluster fleet-default/screspo-test-rke2 for rke-cluster fleet-default/screspo-test-rke2
2021/08/29 00:03:52 [DEBUG] DesiredSet - No change(2) rke.cattle.io/v1, Kind=RKEBootstrapTemplate fleet-default/screspo-test-rke2-bootstrap-template for rke-cluster fleet-default/screspo-test-rke2
2021/08/29 00:03:52 [DEBUG] DesiredSet - No change(2) rke-machine.cattle.io/v1, Kind=VmwarevsphereMachineTemplate fleet-default/screspo-test-rke2-pool1-4787d2ba for rke-cluster fleet-default/screspo-test-rke2
2021/08/29 00:03:52 [DEBUG] DesiredSet - No change(2) cluster.x-k8s.io/v1alpha4, Kind=MachineDeployment fleet-default/screspo-test-rke2-pool1 for rke-cluster fleet-default/screspo-test-rke2
2021/08/29 00:03:52 [INFO] rkecluster fleet-default/screspo-test-rke2: provisioning bootstrap node(s) screspo-test-rke2-pool1-b474d556d-lwt8g: waiting for cluster agent to be available
2021/08/29 00:03:52 [DEBUG] Unable to retrieve Node status, missing NodeRef
2021/08/29 00:03:52 [DEBUG] Infrastructure provider is not ready, requeuing
2021/08/29 00:03:52 [DEBUG] Cannot reconcile Machine's Node, no valid ProviderID yet
```

**Comment by PennyScissors** [comment]
Setup:
Rancher v2.6-head 5f5f0ae
RKE2 vpshere cluster
v1.21.4-rc1+rke2r2

PASSED checks:
The RKE2 vsphere cluster was provisioned correctly, and the vsphere CPI and CSI charts were deployed using the new cloud provider dropdown workflow. One observation is that I needed to raise the cluster's resources to 2cpu/8gb for it to work correctly. The default 2cpu/2gb the UI sets for you will make the CSI's node starve and go into a crashloop sporadically, so we should consider updating the default values in the UI to the recommended minimum when the vsphere cloud provider is enabled if this is something we do based on what the user has selected.

![image](https://user-images.githubusercontent.com/8951271/131268308-88e42879-c591-4ce8-9ada-7522e9a66400.png)

![image](https://user-images.githubusercontent.com/8951271/131268289-8080506b-6be6-4365-9723-e5999f12eb9c.png)

![image](https://user-images.githubusercontent.com/8951271/131268292-e2c73aa0-ef63-4c85-903f-57f363033372.png)

**Comment by cjellick** [comment]
we need to cut a v1.21.4-rc2+rke2r2

Nothing around vpshere is changing from RC1, so i think the testing is still valid, just wanted to make you all aware

generally release testing will be done by @rancher-max

**Comment by PennyScissors** [comment]
@sowmyav27 I can re-test this once `v1.21.4-rc2+rke2r2` is available if you think is necessary, just let me know.
