### ISSUE TITLE
[Tracking Issue] Expecting KDM to bump version RKE2 v1.21.4-rke2r1 and only this version

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#33880]
This is a tracking issue that we are expecting the KDM to be bumped to version rke2 v1.21.4-rke2r1

**Comment by sowmyav27** [comment]
**On 2.6.0-rc9**

- Create an RKE2 cluster
- `v1.21.4-rke2r1` is the only rke2 version available in dropdown
