### ISSUE TITLE
If using global, service will stay active instead of showing Started-Once

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3388]
version 0.56.0-rc1

Steps:
1.  Create three host
2.  Create a service
     Alway run one instance of this container on every host = true
     Image = hello-world
     Auto Restart = Never (Start Once)
3.  Start the service

Results:  The service runs and the containers are set to Started-Once, but the Service is still at Active.

Expected:  Should change from Active to Started Once

**Comment by vincent99** [comment]
I think this was done a while ago in the UI but pls make sure the new API side does the same thing

**Comment by alena1108** [comment]
@tfiduccia as UI was reverted back to use its own logic, could you verify the field via API?

**Comment by tfiduccia** [comment]
The Service still says "Active" and the containers inside say started-once.
![image](https://cloud.githubusercontent.com/assets/11514927/13823708/17e4c68e-eb68-11e5-81d2-d2bd6529dbb7.png)

**Comment by alena1108** [comment]
@tfiduccia could you check for service.healthState in the API? 

@vincent99 - does UI still use its own logic?

**Comment by alena1108** [comment]
@tfiduccia just tested locally myself; service healthState says "started-once", while UI says "active". Checked with @vincent99 - UI still uses its own logic, but its going to be changed to use API logic so its testable via UI. @vincent99 could you mark this bug as to-fix after UI changes are merged?

**Comment by tfiduccia** [comment]
Version - v1.0.0-rc4
Verified fixed
