### ISSUE TITLE
Warning - policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+ seen when deploying apps

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33884]
**Rancher Server Setup**
- Rancher version: master-head commit id: `b395238`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: 1.21.1
- Cluster Type (Local/Downstream): Local

**Describe the bug**
Warning - policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+ seen when deploying

**To Reproduce**
- `rancher-backup-2.0.0-up2.0.0-rc7`
- Deploy rancher backups
- Warnings seen in logs:

```
W0802 21:10:36.734662 35 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
--
Mon, Aug 2 2021 2:10:36 pm | creating 6 resource(s)
Mon, Aug 2 2021 2:10:36 pm | W0802 21:10:36.868879 35 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```

**Comment by cbron** [comment]
This is expected, and will be seen across any feature or thing that uses PSP's. Nothing we can do besides remove the PSP's, which we don't want to do right now.

**Comment by cbron** [comment]
Handled via PSS feature in newer versions
