### ISSUE TITLE
on an upgrade of the rancher server, clusters are not going into `unavailable` state

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33881]
**Rancher Server Setup**
- Rancher version: master-head 3499046
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version: v1.20.8
- Cluster Type (Local/Downstream): Downstream - infrastructure provider

**Describe the bug**
For the downstream clusters created on v2.5.x and upgraded to master-head, the status of the clusters are not seen going to `unavailable`. They remain in `active` state during the upgrade process

**To Reproduce**
1. Create 4 downstream clusters on v2.5.3 with k8s versions v1.16.15, v1.17.17, v1.18.20, v1.19.13
2. Upgrade the rancher server to master-head

**Result**
the clusters are not seen going into `unavailable` state. 

**Expected Result**
Clusters are expected to go into `unavailable` as the cluster-agent would be upgraded to master-head

**Additional context**
While we upgrade rancher from v2.5.3 to v2.5.9 or any 2.5.x, downstream clusters go into `unavailable` state but during the upgrade of clusters from v2.5.3 to master-head, we see only the cluster with k8s `v1.16.15` go into `unavailable` state and all the other clusters remain in `active` state.

**Comment by sowmyav27** [comment]
On latest v2.6-head, i see the clusters - downstream ones go into Unavailable state and come back up Active. Closing this for now
