### ISSUE TITLE
aks operators api *string type doesn't match at generated rancher go cli

### ISSUE THREAD

**Issue by aaronyeeski** [rancher/rancher#33889]
Use go client API binding to create a AKSv2 cluster, letting `Cluster.AKSConfig.ClusterIpv4CidrBlock` empty

Related issues: 
https://github.com/rancher/rancher/issues/32440
https://github.com/rancher/rancher/issues/31296

QA to do:
Test AKSv2 cluster provisioning and import using Rancher UI and Terraform Rancher2 provider.

AKS support for Rancher2 terraform PR: https://github.com/rancher/terraform-provider-rancher2/pull/711

**Comment by izaac** [comment]
Import doesn't succeeds yet with the latest TF build for AKSv2 https://github.com/rancher/rancher/issues/34758

**Comment by izaac** [comment]
There isn't a `cluster_ipv4_cidr_block` in the AKSv2 Rancher2 TF provider schema.

Would it be enough QA to provision and import?

Are these other `*_cidr` related fields related to this `cluster_ipv4_cidr_block` field?

- `cluster_ipv4_cidr_block`
- `network_pod_cidr`
- `network_service_cidr`

**Comment by izaac** [comment]
Rancher version: `v2.6-head (09/20/2021)` _1f15852d_
Rancher version: `master-head (09/20/2021)` _452be57_

Tested as part of https://github.com/rancher/rancher/issues/31296#issuecomment-923169182
