### ISSUE TITLE
Upgrade Helm to 3.6.3+

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#33895]
Need to upgrade to helm 3.6.3+ 

**Release schedule for upcoming helm versions:** 

- 3.6.4 will contain only bug fixes and is planned for release on August 11, 2021

- 3.7.0 is the next feature release and will be released on September 8, 2021.

**Comment by bjornjorgensen** [comment]
same as https://github.com/rancher/rancher/issues/33869

**Comment by cbron** [comment]
See linked issue for more info.

**Comment by ronhorton** [comment]
**PASS** Verified in `v2.6.3-rc3`

`Test 1 - Chart Install/Upgrade/Uninstall`
1. Created downstream cluster
2. Installed Logging v2 100.0.0+up3.12.0
3. Verified Logging sending logs to elasticsearch
4. Upgraded Logging v2 100.0.1+up3.15.0
5. Verified Logging sending logs to elasticsearch after chart upgrade
6. Uninstalled Logging v2
7. Uninstall successfull
`Chart Install/Upgrade/Uninstall successful`
<img width="1625" alt="Screen Shot 2021-12-02 at 6 35 21 PM" src="https://user-images.githubusercontent.com/89212856/144519792-8ed65817-fc4a-4c72-b070-4832eba9bdc2.png">

`Test 2 - Chart Install - Legacy`
1. created downstream cluster with k8s v1.18.20 (legacy apps not supported in v1.21.5)
2. activated feature flag > legacy
3. installed loggin v1
4. verified logging sending logs


`Test 3 - Jenkins automated testing`
1. Created rke1 downstream cluster
2. Created rke2 downstream cluster
3. Ran jenkins automation
4. There were failed tests in test_wl, but ran them manually and they passed
`Automated tests passed`
