### ISSUE TITLE
Clusters are in Error state after a rancher restore

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33892]
**Rancher Server Setup**
- Rancher version: master-head commit id: `b3952388`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: 1.21
- Cluster Type (Local/Downstream): Downstream - DO RKE1

**Describe the bug**
Clusters are Error state after a rancher restore

**To Reproduce**
Saw the issue after these steps were done on the rancher server setup

- Deploy master head
- Deploy a downstream RKE1 cluster
- Enable token hashing
- Deploy backup restore operator on the local cluster
- take backup b1
- Migrate Rancher to a new RKE1 cluster - follow steps [here](https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/migrating-rancher/)
- Deploy Rancher on this RKE1
- The Rancher server comes up Active
- The downstream cluster is up and Active
- Deploy another downstream cluster - 1 etcd+control plane and 3 worker nodes
- The cluster is stuck in error state after etcd/control plane comes up Active - `Cluster health check failed: Failed to communicate with API server during namespace check: Get "https://<control-plane>:6443/api/v1/namespaces/kube-system?timeout=45s": context deadline exceeded; Delete "https://<control-plane>:6443/api/v1/namespaces/default/serviceaccounts/netes-default": cluster agent disconnected`

**Note:**

- Existing cluster before migration also kept going into error state but came up Active.
- Deployed another 1 node cluster - and that cluster was Active.

**Comment by sowmyav27** [comment]
The node - Control plane on the downstream cluster - seems to have gotten removed. It is seen in rancher server logs. And the node is not available in the backend.
```
2021/08/02 23:57:13 [INFO] Removing node sowmya-new1-1
2021/08/02 23:57:13 [INFO] [node-controller-rancher-machine] About to remove sowmya-new1-1
....
2021/08/02 23:57:16 [INFO] Removing node sowmya-new1-1 done
```

**Comment by jiaqiluo** [comment]
The cluster in the error state is a "new" cluster created after the restore succeeds. 
According to Rancher's logs, the node `sowmya-new1-1` is removed during the provisioning process. 
Node removal and re-creation is a normal event when Rancher provisions clusters, but somehow this time Rancher did not consolidate the state of the cluster properly: Rancher creates a new droplet in Digital Ocean but still uses the IP address of the old node. 

Since we are able to create several new clusters in the same setup successfully, I will not consider this is a blocker bug.

**Comment by sowmyav27** [comment]
Closing this for now as I was able to provision other downstream clusters on this setup with no issue. Will reopen or log a new one if this issue is seen again.
