### ISSUE TITLE
Support for custom port mapping to Hosts

### ISSUE THREAD

**Issue by hany** [rancher/rancher#339]
When adding a new Host, instructions are as follows:

> From the internet to TCP ports `9345` and `9346` (for UI hosts stats/graphs)

With some clouds that utilize a VPC, exposing all hosts inside the VPC to the same set of public TCP ports requires allocating a separate IP address per host, which is wasteful. Allowing custom port mapping would be helpful in this case.

**Comment by ibuildthecloud** [comment]
There's a component to help with this.  it just requires a bit more manual steps.  https://github.com/rancherio/host-proxy

Let me know if the README.md is not clear as to how to use it.

**Comment by hany** [comment]
This is perfect! I will give it a try.

**Comment by hany** [comment]
So I proceeded to setup this up according to the very simple instructions, but it doesn't seem to be working. I can see it's attempting to connect to the Websocket directed at the proxy from the web interface, but it seems the proxy is returning a 500 error after a long wait period. Inspecting the logs of the proxy container, I can see the following:

```
2015/03/27 13:32:57 "dial tcp <NAT DEVICE INTERNAL IP>:9345: connection timed out"
goroutine 331 [running]:
github.com/rancherio/host-api/app/common.CheckError(0x7f51487ed810, 0xc2080314c0, 0x2)
	/source/Godeps/_workspace/src/github.com/rancherio/host-api/app/common/error.go:17 +0x8a
github.com/rancherio/host-api/app/common.ErrorHandler.ServeHTTP(0x856078, 0x7f51487ed6c0, 0xc2080550e0, 0xc208035450)
	/source/Godeps/_workspace/src/github.com/rancherio/host-api/app/common/error_handler.go:13 +0x8a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20800a410, 0x7f51487ed6c0, 0xc2080550e0, 0xc208035450)
	/source/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x297
github.com/rancherio/host-api/auth.func·002(0x7f51487ed6c0, 0xc2080550e0, 0xc208035450)
	/source/Godeps/_workspace/src/github.com/rancherio/host-api/auth/auth.go:55 +0xfc
net/http.HandlerFunc.ServeHTTP(0xc20802ac50, 0x7f51487ed6c0, 0xc2080550e0, 0xc208035450)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20800ca20, 0x7f51487ed6c0, 0xc2080550e0, 0xc208035450)
	/usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208032300, 0x7f51487ed6c0, 0xc2080550e0, 0xc208035450)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208054fa0)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

E0327 13:32:57.576903       1 error.go:26] %q
%s
 dial tcp <NAT DEVICE INTERNAL IP>:9345: connection timed out
```

Curiously enough, it seems the proxy is attempting to hit the *internal* IP of the NAT device on port `9345` instead of the host nodes on the same network. I have not specified the internal IP anywhere, so the proxy must be fetching this from somewhere.

**Comment by vincent99** [comment]
We should really rework this so that proxying thru the master to the agent via the connection they already have open to each other is the default/only behavior...

**Comment by vincent99** [comment]
This is no longer relevant, hosts open a websocket connection to the server and everything is multiplexed through there now.
