### ISSUE TITLE
Creating a cluster with a non-user CR causes CRTB handlers to spin

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#33905]
When a cluster is created using a kubectl config with a non-user CR id the CRTB handlers will attempt to fetch that user but will always fail. 

This is caused by the creatorID being added to the cluster so a cluster-creator CRTB is automatically created for the user but in this case it's not the name of a valid user CR. 

`2021/08/03 10:51:22 [ERROR] error syncing 'c-m-d650e495/creator-cluster-owner': handler mgmt-auth-crtb-controller: users.management.cattle.io "system:admin" not found, requeuing `

**Comment by MbolotSuse** [comment]
In these cases, Rancher should not create owner bindings for the cluster, since it may have been created by a user who cannot be given permissions using CRTBs (such as a service accounts). Instead, the annotation indicating the owner should be removed, and a log statement (probably level info) should be made indicating that no creator binding will be made since the creator is not a user.

This limitation should also be documented in the [RBAC docs](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/cluster-and-project-roles#default-cluster-and-project-roles).

Further triage is needed to reproduce/confirm the issue.

**Comment by tomleb** [comment]
I was able to reproduce this issue by doing the following as `system:admin` user using a local k3s cluster:
1. Create a `DigitaloceanConfig.rke-machine-config.cattle.io/v1` 
2. Create a `Cluster.provisioning.cattle.io/v1`

I get the following errors in my logs:

```
023/11/22 13:51:31 [WARNING] could not find user system:admin, will not create impersonation account on cluster
2023/11/22 13:51:31 [ERROR] error syncing 'c-m-87mz5s7b/creator-cluster-owner': handler mgmt-auth-crtb-controller: users.management.cattle.io "system:admin" not found, requeuing
2023/11/22 13:51:40 [WARNING] could not find user system:admin, will not create impersonation account on cluster
2023/11/22 13:51:40 [ERROR] error syncing 'p-gcgq6/creator-project-owner': handler mgmt-auth-prtb-controller: users.management.cattle.io "system:admin" not found, requeuing
2023/11/22 13:51:40 [WARNING] could not find user system:admin, will not create impersonation account on cluster
2023/11/22 13:51:40 [ERROR] error syncing 'p-wvldn/creator-project-owner': handler mgmt-auth-prtb-controller: users.management.cattle.io "system:admin" not found, requeuing
```

We can note that both CRTB and PRTB controllers are retrying.

Here's a brief view of the flow:

When I create the `Cluster` object, the [webhook adds the field.cattle.io/creatorId](https://github.com/rancher/webhook/blob/e401287e9f7f36f1a3d718c68918b0a3b3227147/pkg/resources/provisioning.cattle.io/v1/cluster/mutator.go#L124) annotation on it.

Then [default and system projects](https://github.com/rancher/rancher/blob/58bfcb19605d51bf24f0aa5bf1d60a68b1ae2a27/pkg/controllers/management/auth/project_cluster_handler.go#L279-#L285) are created with the [same annotation](https://github.com/rancher/rancher/blob/58bfcb19605d51bf24f0aa5bf1d60a68b1ae2a27/pkg/controllers/management/auth/project_cluster_handler.go#L323). For each of these,
a PRTB is also created in the project namespace [with the creatorID as the UserName](https://github.com/rancher/rancher/blob/58bfcb19605d51bf24f0aa5bf1d60a68b1ae2a27/pkg/controllers/management/auth/project_cluster_handler.go#L431).

Also, a CRTB is created in the cluster namespace [with the creatorID as the UserName](https://github.com/rancher/rancher/blob/58bfcb19605d51bf24f0aa5bf1d60a68b1ae2a27/pkg/controllers/management/auth/project_cluster_handler.go#L498).

> In these cases, Rancher should not create owner bindings for the cluster

@MbolotSuse  By Rancher, do you mean webhook? The way I understand your message is the following: webhook should check if the UserInfo is from an actual Rancher user. If it is, set the annotation, if it isn't don't set the annotation and log something (although this wouldn't appear in rancher logs, humm). Then, the various controllers should not do anything if no creatorID annotation is found.

**Comment by MbolotSuse** [comment]
> By Rancher, do you mean webhook? The way I understand your message is the following: webhook should check if the UserInfo is from an actual Rancher user. If it is, set the annotation, if it isn't don't set the annotation and log something (although this wouldn't appear in rancher logs, humm). Then, the various controllers should not do anything if no creatorID annotation is found.

@tomleb Nope, this wasn't what I meant. I mean that Rancher should process the annotation (webhook should continue to add like it does today) and log if it doesn't identify a real user, specifically so that the rancher logs display the error.

**Comment by tomleb** [comment]
Thanks.

Adding more details for when we do work on it.

I've found [this place](https://github.com/rancher/rancher/blob/58bfcb19605d51bf24f0aa5bf1d60a68b1ae2a27/pkg/controllers/management/auth/project_cluster_handler.go#L380-#L384) that might be a could spot to add the User check. This is called for both Project and Cluster objects.
