### ISSUE TITLE
info slide-up's menus options scroll up when you scroll

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3390]
version - 0.56.0-rc2

Steps:
1.  Create a service
2.  Click on the i circle next to service name on main service page
3.  Click on the v to bring up the menu for that service
4.  Scroll

Results:
The menu scrolls up with the page and leaves the info slide-up section.  Same thing happens to the containers right-click menu.
![image](https://cloud.githubusercontent.com/assets/11514927/12525638/f0c01d98-c122-11e5-9ded-93799d4bd486.png)
![image](https://cloud.githubusercontent.com/assets/11514927/12525659/20cbc4d8-c123-11e5-941e-7acf7dd23de8.png)

Expected:
Menu to stay put while rest of page scrolls.

**Comment by vincent99** [comment]
Scroll wheel, touchmove (for touchscreens/phones), up/down/left/right/pgup/pgdn/home/end/space are all disabled now while a tooltip and/or menu are up.  This will surely cause no problems whatsoever.

**Comment by tfiduccia** [comment]
Version - master UI 1/29
Verified fixed
