### ISSUE TITLE
Make Keycloak refresh token more efficient

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#33916]
https://github.com/rancher/rancher/pull/33896/files#r682168873
Without this there is a window where access and refresh token will expire and quite a lot of calls can be made. But once the access token is reset it will be back to normal.

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: 2.6-head 4375161 vs 2.6.2
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
#### Set Up: ####
set up Keycloak (OIDC)
set Access Token Lifespan = 1 minutes (Keycloak site)
enabled debug logs 
to track when Rancher interacts with Keycloak I also used Keycloak admin panel (User -> find your user -> Session): every time a new token / refresh token is requested "Last Access" is updated)
![keycloak](https://user-images.githubusercontent.com/40282141/143153202-d1f6b062-7350-4090-ba94-c778a5f12f64.jpg)

--------

#### Testing: ####
the initial token expires after 1 minute and when I go to User&Authentication -> Auth Provider -> interact with the "Add Member" dropdown
- 2.6.2: a request to Keycloak to get a refresh token is sent on every interaction with the dropdown 
  - Last Access on the Keycloak is updated on every interaction
  - the request is logged in rancher logs (debug logs)
    - ![token](https://user-images.githubusercontent.com/40282141/143152823-afbfa5b5-7f7d-4edc-b017-594b48719f5f.jpg)
- 2.6-head: a request to Keycloak to get a refresh token is sent only when the Access Token Lifespan setting is met (only when 1 minute passed)
  - Last Access on the Keycloak is updated only when a token/refresh token expires (after 1 min between requests)
  - the new messages and a request are logged in rancher logs (debug logs)
    - ![token1](https://user-images.githubusercontent.com/40282141/143152924-90824699-0ba8-4782-bc88-21e4cbbdd5f9.jpg)

----------

Upgraded 2.6.2 with Keycloak user
- the user was able to log in to the cluster
- new refresh token functionality is working as expected
- refresh group memberships is functioning the same way now as the dropdown in Auth Provider 
  - a new token is not requested if the current refresh token is still valid 
- logging out / logging in back refreshes a token
