### ISSUE TITLE
Cluster and Fleet agents cannot communicate with Rancher server behind a proxy with a certificate

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#33919]
**Rancher Server Setup**
- Proxy/Cert Details: Rancher server is air-gapped with a proxy that has its own certificate

**Describe the bug**

Even if Rancher is able to provision a cluster (like KEv2), the `cluster-agent` and `fleet-agents` will not be able to connect back to the Rancher server.

**To Reproduce**
 
1. Deploy a new cluster from Rancher
2. View the `cattle-agent` deployment (It will likely be Unavailable and in a CrashLoopBackoff)
3. View the Conditions on the cluster object (It will likely have an error related to `fleet-agent` Check in)

**Expected Result**

The clusters should be provisioned and the agents able to connect to the Rancher server.

**Screenshots**

<img width="1267" alt="126570542-5cbeba58-ef17-4d5e-a2d3-54ea695ab2dd" src="https://user-images.githubusercontent.com/3682717/128104812-d21f5210-49b3-4a71-a4dc-4c095d09ef07.png">
<img width="1323" alt="126570761-a5f21fd8-dd5a-4203-930b-4972a2ae2bad" src="https://user-images.githubusercontent.com/3682717/128104816-1fc9663e-a125-4006-b840-7d9b9053f964.png">

**Additional context**
<!--Add any other context about the problem here.—>
The issue is likely that the agents are not getting the additional certificate from the Rancher server (from the tls-ca-additional secret).

**Comment by prabalsharma** [comment]
In addition to above issues (due to the fact that the cluster-agent cannot connect to the Rancher server): 
When user will deploy a hosted AKS, GKE or EKS cluster; `Explore` won't work and Node count will be off

<img width="1199" alt="Screen Shot 2021-08-04 at 3 36 37 PM" src="https://user-images.githubusercontent.com/3749546/128264234-e16bfa5f-e1cc-44b5-8b8e-f7d88aa33283.png">

**Comment by slickwarren** [comment]
on v2.6-head (01d2ecb):
upon further investigation in the same setup, I was able to update the server URL and verify that the GKE cluster (v1.20.10) is working as expected.  
* cattle-cluster-agent is no longer crashing
* deployments (i.e. workloads, services, etc. ) are working as expected
* node count is accurate
