### ISSUE TITLE
Prepare stack name as variable inside docker-compose file

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#3393]
I would need the stack name inside the docker-compose  file as variable. So maybe if set "-p stackName" is set rancher-compose should also prepare variable for usage inside the docker-compose file?
Or is that still possible?

**Comment by pwFoo** [comment]
I found env-file option:
```
environment:
  - RACK_ENV=development
  - SHOW=true
  - SESSION_SECRET
```
But would be great to just define the stack name one time (`rancher-compose -p StackName ...` or just inside the env-file?

**Comment by sshipway** [comment]
Having various additional variables for use in the compose templates would be useful, especially for stack templates that intend to interface with the Rancher API.  I would suggest at least -

- $RANCHER_STACK
- $CURRENT_DATE
- $RANCHER_URL
- $RANCHER_ENVIRONMENT
- $RANCHER_USER

There may be many others which would be of use as well, though I can't think of them offhand

**Comment by pwFoo** [comment]
First key (service name) can't be set as variable, because it won't be replaced and fails with invalid characters. To deploy a service twice I have to change the env file and also the docker-compose.yml file.
A consistent variable replacement would hell.

**Comment by sshipway** [comment]
I know they don't replace currently, this is more a feature-request-suggestion to the Rancheros on what I think they *should* add to the template replacement symbol list.  Maybe if they go to a full templating language as was mentioned in #3239 we'd be able to get access to many more internal variables...

**Comment by flypenguin** [comment]
Also for catalog items this would be a major help for my use cases if I could just do something like

    my_service:
      environment: { SOME_THING: ${stack_name} }

**Comment by oomathias** [comment]
I'm having this problem too. Beeing able to use `${STACK_NAME}` in `docker-compose.yml` and `rancher-compose.yml` from `rancher-compose` cli and for catalogs items would be awesome.

Right now I have to re-ask the stack name with a question in my catalog. I use the stack name as a namespace to mount volumes etc.

ie: `/srv/docker/${STACK_NAME}/${SERVICE_NAME}/data:/data`

**Comment by germanramos** [comment]
This feature is a must when you deal with kubernetes catalog

**Comment by gbbirkisson** [comment]
+1

**Comment by cqcwillard** [comment]
+1

**Comment by onehao** [comment]
+1

**Comment by adnan-panalytics** [comment]
+1

**Comment by jschilperoord** [comment]
+1

**Comment by Latnok** [comment]
+10

**Comment by bseclier** [comment]
+1

**Comment by fkollmann** [comment]
+1

**Comment by nickymoelholm** [comment]
+1

**Comment by adnan-panalytics** [comment]
Since this seems to be an important issue for a lot of people, is it possible to have this in the next release of rancher?

**Comment by cdomigan** [comment]
+1

**Comment by mghignet** [comment]
Hi! I agree with the fact that having the stack name available in the docker-compose would be handy.
Thanks!

**Comment by heijigaoke** [comment]
I want use the STACK_NAME in my rancher_compose file as follow:
zabbix-db:
  scale: $deploy_num
  hostname: $${RANCHER_STACK}
or
 hostname: ${RANCHER_STACK} 

It dose work just null string.

**Comment by eshbaugh** [comment]
+1

**Comment by heijigaoke** [comment]
+1

**Comment by gregnuj** [comment]
+1

**Comment by subhransusekhar** [comment]
+1

**Comment by hanselke** [comment]
this would be really helpful as services are automatically given IPs based on stack_name.

the cloudflare catalog seems to implement it somehow?

**Comment by dustinvanbuskirk** [comment]
Surprised this isn't possible today.  I am using a dynamic load balancer which adds the stacks lb using the stack_name and would like to be able to use the stack_name inside of the rancher-compose.yml file for use in the haproxy config file to set the domain name.

**Comment by swartel-fa** [comment]
+1

**Comment by nheinemans** [comment]
+1

**Comment by jorisjumanne** [comment]
+1

**Comment by jean-francois-labbe** [comment]
+1

**Comment by edaubert** [comment]
+1

**Comment by oomathias** [comment]
Please stop this +1 spam, just use the :+1: on the OP post.

**Comment by leonardodelfino** [comment]
+1

**Comment by deniseschannon** [comment]
If implemented, we need to consider priority of where you customize stack name (through the UI/ CLI commands/compose file) as well as get a UI fix for pulling the stack name variable if it's in the compose.

**Comment by carolynhu** [comment]
also need to add .Environment.Name support

**Comment by deniseschannon** [comment]
Available in CLI v0.6.3-rc1 and rancher-compose-executor v0.14.11.

**Comment by sangeethah** [comment]
@carolynhu @alena1108 , could you provide an example compose file that show the environment variable name relating to stack name ?

**Comment by carolynhu** [comment]
@sangeethah such as the following compose file:
version: '2'
services:
  web:
    image:  {{ .Stack.Name }}
where the .Stack.Name can be "nginx"

**Comment by sangeethah** [comment]
@carolynhu , I am referring to the environment variable name that needs to be set for specifying stack name. image tag is used for service's image name.

**Comment by deniseschannon** [comment]
@sangeethah I believe you can use the stack name as variable inside your compose file. 

So if you had a stack named `nginx` in the UI, you could use the compose file that @carolynhu provided and the compose file would use nginx as the image

```
version: '2'
services:
  web:
    image: {{ .Stack.Name }}
```

Similarly, if using CLI, if you did `rancher up -p alpine`, it would use `alpine` as the image name as part of the compose file.

**Comment by sangeethah** [comment]
Tested with Rancher server built from v1.6 branch which uses rancher-compose-executor v0.14.11 .

Created a stack from UI using the {{ .Stack.Name }} as part of volume mount path:

```
version: '2'
volumes:
  foo3:
    driver: rancher-nfs
services:
  nginxstack:
    image: nginx
    volumes:
    - foo3:/{{ .Stack.Name }}/mydata
```

When the service gets created , the volume  mount path has the stack name in as expected.

**Comment by fkollmann** [comment]
For those who are not familiar with the internal structure "rancher-compose-executor v0.14.11" is included in which component? Is it the "rancher-composer.exe" or is it part for the rancher server docker image? And which version is/will be required for using that?

**Comment by deniseschannon** [comment]
@fkollmann This is how when you add stacks through the UI, how they become services in Rancher.  It is built into Rancher server.

**Comment by twinpoint** [comment]
@deniseschannon Thanks for the feedback! Does this mean that the change as to be implemented into "rancher-compose.exe", too, or is it covered by updating the server (through REST API, maybe?) ? And which Rancher version will include this change?

**Comment by fkollmann** [comment]
@deniseschannon Thanks for the feedback! Does this mean that the change as to be implemented into "rancher-compose.exe", too, or is it covered by updating the server (through REST API, maybe?) ? And which Rancher version will include this change?

**Comment by sangeethah** [comment]
@fkollmann , Next release of rancher server - v1.6.5 will have this fix.
The fixes will also be available in next release of  rancher cli - v0.6.3.

Tested with rancher cli version v0.6.3-rc1. 
Able to use {{ .Stack.Name }}  in docker-compose.yml with rancher up command.
```./rancher up -s stack2 -f dc.yml

Sangeethas-MBP:rancher-v0.6.3-rc1 sangeethahariharan1$ cat dc.yml 
version: '2'
volumes:
  foo3:
    driver: rancher-nfs
services:
  nginxstack:
    image: nginx
    volumes:
    - foo3:/{{ .Stack.Name }}/mydata
```

Note that {{ .Stack.Name }} can be used only with docker-compose.yml and NOT in rancher-compose.yml.

**Comment by fkollmann** [comment]
@sangeethah @deniseschannon Thanks a lot! This is really great, Esp to @carolynhu who did the original implementation, if I am not mistaken.

We had to do quite some workarounds (env file) to get this working for us somehow. I really appreciate the work you put into this feature!

**Comment by warroyo** [comment]
will this feature be available when using the rancher UI?

**Comment by carolynhu** [comment]
@warroyo yes, rancher UI will support this feature

**Comment by leucos** [comment]
Elaborating on the example above, is it possible to use `{{ .Stack.Name }}` in the volume name ?
e.g.:
```
services:
  nginxstack:
    image: nginx
    volumes:
    - {{ .Stack.Name }}:/mydata
```

**Comment by courcelm** [comment]
@leucos: Yes it is working from a docker-compose.yml file

**Comment by leucos** [comment]
upgraded to 1.6.6 (and upgraded cli) and it works. thanks @courcelm

**Comment by D4fnk** [comment]
Do you think that it would be possible to do the same with the service name and the number of the service (when scaling it) ? 
For example i'd like to have specifics volumes for my app logs, like {{ .Stack.Name }}-{{ .Service.Name }}-{{ .Number }}

**Comment by thomasb0123** [comment]
I have same issue as @D4fnk , i wish to have my volumes différent on each containers but i dont know how to get container ID to make volumes like that : 
  volumes:
    - /pathtomySSD/data/scaleid:/var/lib/mysql

Any infos?

Thanks

**Comment by alexanderdalloz** [comment]
Shouldn't {{ .Stack.Name }} work inside a docker-compose.yml in a stack deployment with rancher-compose?
While testing I get something like `/mnt/glustervol1/{{ .Stack.Name }}/mysqldb/` created. {{ .Stack.Name }} literally.

**Comment by deniseschannon** [comment]
@alexanderdalloz It was fixed for Rancher CLI. We are moving forward with most fixes for Rancher CLI.

**Comment by pkaramol** [comment]
Is there a reference with variables available inside `docker-compose.yml`?
Apart from `.Stack.Name` what else can be used? 
`.Service.Name` does not seem to work.

**Comment by carolynhu** [comment]
@pkaramol except for {{.Stack.Name}}, we also support {{.Environment.Name}}. We do not have support for .Service.Name

**Comment by pkaramol** [comment]
Thanks @carolynhu .
In general accessing rancher labels via `go` templates works so I have managed to pass in my logs whatever is available this way (e.g. `io.rancher.stack.name`, `io.rancher.stack_service.name` etc).
However there is [this minor issue](https://github.com/rancher/rancher/issues/9999).
