### ISSUE TITLE
Restore always fails on cluster running v1.20.9+rke2r1

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#33946]
**Steps to reproduce:**

Attempt to restore any backup on k8s version `v1.20.9+rke2r1`.

**Result:**
Restore keeps failing with error messages like:
```
ERRO[2021/08/03 20:06:39] error syncing 'restore-migration': handler restore: error restoring namespaced resources, check logs for exact errorRestore.resources.cattle.io "restore-migration" is invalid: [status.restoreCompletionTs: Invalid value: "null": status.restoreCompletionTs in body must be of type string: "null", status.summary: Invalid value: "null": status.summary in body must be of type string: "null", status.backupSource: Invalid value: "null": status.backupSource in body must be of type string: "null"], requeuing
```
(if there are other failures during restore)

or 

```
ERRO[2021/08/03 20:09:07] error syncing 'restore-migration': handler restore: Restore.resources.cattle.io "restore-migration" is invalid: status.summary: Invalid value: "null": status.summary in body must be of type string: "null"Restore.resources.cattle.io "restore-migration" is invalid: [status.summary: Invalid value: "null": status.summary in body must be of type string: "null", status.backupSource: Invalid value: "null": status.backupSource in body must be of type string: "null", status.restoreCompletionTs: Invalid value: "null": status.restoreCompletionTs in body must be of type string: "null"], requeuing
```
(if there are no other failures during restore)

Inspecting the corresponding `restores.resources.cattle.io` object reveals that `status` is not set on it.

**Expected behavior:**
Status on `restores.resources.cattle.io` object is properly updated and (if there were no other errors) the restore is not retried.

**Notes:**
This issue could not be reproduced on **k3s** `v1.19.8+k3s1` or `v1.20.9+k3s1`.

**Comment by snasovich** [comment]
After discussing it with @deniseschannon we want this fix in 2.6.0.

**Comment by snasovich** [comment]
@janeczku , this issue is specific to this exact version of RKE2 (`v1.20.9+rke2r1`) as it fails on setting any string field to `""`. Related RKE2 issue: https://github.com/rancher/rke2/issues/1530
The impact of this RKE2 issue is likely too big to be reasonably addressed in all Rancher-related components. RKE2 team is working on a fix. Meanwhile, suggesting to use `v1.20.8+rke2r1` as it's not affected.
Thus, suggesting to close this issue. Please do if you're OK with this resolution.

**Comment by snasovich** [comment]
Also note this version is now marked as pre-release with note on the referenced issue: https://github.com/rancher/rke2/releases/tag/v1.20.9+rke2r1

**Comment by deniseschannon** [comment]
Using this issue to track that KDM is updated in dev-v2.6.

**Comment by Jono-SUSE-Rancher** [comment]
Should be ready to test via https://github.com/rancher/rke2/issues/1530

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/33942 as they are tracking the same issue and would have the same test.
