### ISSUE TITLE
Cannot create node templates for rke2

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#33941]
**Rancher Server Setup**
- Rancher version: v2.6-head commit `10588ab`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): helm chart, rke1, v1.19.6
- Proxy/Cert Details: self-signed certs

**Information about the Cluster**
N/A -- cannot bring up cluster

**Describe the bug**
When trying to create an rke2 node-driver cluster, first we must setup cloud credentials. After completing the steps here, it fails to properly create. I see this on both EC2 and DO (only tried these two). See screenshot result:
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/55997940/128222130-60ffcb5c-2fef-4709-bb87-c04b956e915e.png">

However, it appears to have created somewhere (not sure where to see this in the UI as the `cloudcredentials` page on cluster management fails to load for me) because when I follow the same steps, I cannot use the same name for the credential.

**To Reproduce**
Create rke2 cluster with node driver

**Result**
The cloud credential doesn't work properly

**Expected Result**
It should allow me to use the cloud credential I just created and retrieve the correct results for the node template

**Screenshots**
See above

**Additional context**
It appears I can workaround this by doing the same steps for an RKE1 cluster. Then I cancel the cluster creation and use THAT template in the rke2 cluster creation.

**Comment by rancher-max** [comment]
Probably related: https://github.com/rancher/rancher/issues/33932

**Comment by davidnuzik** [comment]
I observe this as well on latest master-head, `2b156fd2b`
I am completely blocked from working on all the issues assigned to me.

**Comment by deniseschannon** [comment]
I tested it with the latest v2.6-head as of 8/4 at 2:30PM and it is now working but will let you guys validate as well

**Comment by rancher-max** [comment]
This is working on v2.6-head commit `e3316c9`
