### ISSUE TITLE
Audit Log: special character display

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3395]
![image](https://cloud.githubusercontent.com/assets/2150990/12535554/4b5aac86-c287-11e5-8439-c90af8f8a259.png)

**Comment by vincent99** [comment]
Works for me.. Are you using an external database by any chance?

The audit log contains the entire request/response objects, and are available only to admins, who could just look up the secret in the settings API/database.

![image](https://cloud.githubusercontent.com/assets/753917/12629587/c001d138-c505-11e5-88c8-659e0acf6b1f.png)

**Comment by rvion** [comment]
No, I'm not using an external database.
It was with 56 RC3, I'll test again soon in a new test setup.

**Comment by deniseschannon** [comment]
@rvion If you are still seeing this in the latest release, please re-open.
