### ISSUE TITLE
[2.5] Backport: Unable to view resources in downstream clusters when my user is associated with a group from an external auth provider

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#33958]
Backport issue for https://github.com/rancher/rancher/issues/33912

**Comment by anupama2501** [comment]
Verified on v2.5-head b5dacbe

1. Enabled openldap auth and created an rke1 cluster as admin.
2. As an admin, added a group as cluster owner. 
3. Logged in as the cluster owner.
4.  verified from cluster explorer by installing cert-manager and verifying all the resources were accessible.
5. Enabled github auth and logged in as group member. 
6. Verified installed kubernetes services are accessible and https://ip/k8s/clusters/c-7bk2l/apis is accessible.
