### ISSUE TITLE
rke2 node driver through yaml creation results in an error

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33961]
**Rancher Server Setup**
- Rancher version: v2.6-head e3316c9
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: selfsigned

**Information about the Cluster**
- Kubernetes version: v1.21.3-rc3+rke2r2
- Cluster Type (Local/Downstream): Downstream node driver

**Describe the bug**
Creating an rke2 cluster through yaml results in error `DigitaloceanConfig.rke-machine-config.cattle.io "fleet-default/test" not found`

**To Reproduce**
From cluster mangement, click on create and select rke2 DO node driver
edit as yaml and provide the following config and click on save
[au-yaml-test.yaml.txt](https://github.com/rancher/rancher/files/6935029/au-yaml-test.yaml.txt)

**Result**
the cluster almost immediately results in an error `DigitaloceanConfig.rke-machine-config.cattle.io "fleet-default/test" not found`

**Expected Result**
Cluster creation going through successfully.

**Screenshots**
<img width="200" alt="Screen Shot 2021-08-04 at 5 05 03 PM" src="https://user-images.githubusercontent.com/38144301/128270907-4188d375-6a22-4055-9e85-7e39940c7abe.png">

**Comment by vincent99** [comment]
Going through the edit as yaml to save was skipping saving the machineConfigs.  https://github.com/rancher/dashboard/pull/3695/commits/f8a262826663fdfa9198dbdcdcd469893cc07a8d

**Comment by anupama2501** [comment]
Verified on v2.6-head ba95a58

- Created an rke2 node driver DO clsuter by editing the yaml file. 
- Cluster has come up active.
