### ISSUE TITLE
v0.56.0-rc3 - UI: Issue reporting: Typo + smal area cliackable

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3396]
- File and issue -> File an* Issue
- I would like the whole area + the big icon to be clickable. I tried to click on the logo first, then on the word issue, before understanding that it was the "github" word I was supposed to click on. At least, the color could be a little bit different, cause on a retina screen, there is very few contrast

![image](https://cloud.githubusercontent.com/assets/2150990/12535568/b354806e-c287-11e5-9011-a9ceee91534e.png)

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/449

**Comment by rvion** [comment]
thanks

**Comment by vincent99** [comment]
Please keep open until our QA has verified in a release...

**Comment by tfiduccia** [comment]
Version - master 1/27
Verified fixed
