### ISSUE TITLE
Active Directory / LDAP authentication: server discovery via DNS SRV records

### ISSUE THREAD

**Issue by mstrent** [rancher/rancher#33969]
Currently Rancher supports only specifying a single AD or LDAP server for authentication. Only hitting a single AD or LDAP server is problematic if that single server goes down, or if Rancher is failed over to a different site. Most sites have multiple domain controllers since authentication is such an important service.

These days the proper way to auth against AD is to discover available domain controllers via DNS SRV records. All you need to know is the domain name and have access to DNS and autodiscovery is pretty straightforward. This would apply to vanilla LDAP as well.

This would go a long way toward enterprise level acceptance and reliability for Rancher.

https://ldap.com/dns-srv-records-for-ldap/
https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/how-domain-controllers-are-located

**Comment by mstrent** [comment]
Without SRV support, at least supporting configuring multiple servers would go a LONG way. :)

**Comment by Martin-Weiss** [comment]
Still important

**Comment by Martin-Weiss** [comment]
Still important
