### ISSUE TITLE
There's no kubernetes version available for chosing, when I create custom cluster

### ISSUE THREAD

**Issue by wonleing** [rancher/rancher#33972]
**Rancher Server Setup**
- Rancher version:v2.4.33
- Installation option (Docker install/Helm Chart):
   I built rancher image with github source code, then load and run with docker
- Proxy/Cert Details: none

**Information about the Cluster**
- Kubernetes version: Kubernetes 1.18.5 (from github)
- Cluster Type (Local/Downstream): local

**Describe the bug**
There's no kubernetes version available for chosing, when I create custom cluster

**To Reproduce**
 

**Result**
no kubernetes version available for chosing,

**Expected Result**
should list local k8s version here, or at least give me a way to add local k8s version somewhere in source code

**Screenshots**
![截图录屏_选择区域_20210805111944](https://user-images.githubusercontent.com/105055/128286228-e1adba39-eaed-4c4e-a318-213d6e73df6b.jpg)

**Additional context**
It should be competible with official k8s release

**Comment by superseb** [comment]
v2.4.33 is a non existent version, and as you are building from source, I guess a branch or commit is better indication. How did you build it? And populating the dropdown can take a bit longer, how long did you wait before creating the cluster?

**Comment by vincent99** [comment]
Presumably that's the UI tag, which was different than the Rancher one back then.

**Comment by wonleing** [comment]
Right, V2.4.33 is User interface version. the Backend version is V2.4.7
I wait long enough, actually I didn't close the window for hours.
I wonder if it relates with rke/rke-tools. Is there anyway to debug it?

**Comment by superseb** [comment]
You build from source from tag v2.4.7? How did you build it? What is the build/Docker image tag/commit that is used in the build?

**Comment by wonleing** [comment]
Just followd https://github.com/rancher/rancher#readme
build with scripts/build scripts/package, then I have a rancher image.
run with sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher

while doing rke up --config cluster.yaml        it reports this error:
Host [10.3.10.252] is not able to connect to the following ports: [10.3.10.252:2379]. Please check network policies and firewall rules]
 Don't know if this is the cause.

**Comment by superseb** [comment]
That process should work, it is unclear to me why `rke up` is involved. Rancher runs in the created Docker container and you can use it to create clusters via the UI/API, but RKE is a CLI tool to create a Kubernetes cluster (and can then be used to run Rancher on top as a Deployment for HA) which is not involved when you manually built Rancher and try to run it as Docker container.

**Comment by wonleing** [comment]
we are trying to use "rke up" to debug. (I guess web UI calls rke command).
If web UI doesn't call rke, then how can we debug it?

**Comment by wonleing** [comment]
Any idea what does "Host [10.3.10.252] is not able to connect to the following ports: [10.3.10.252:2379]. Please check network policies and firewall rules]" mean?
Anyway to debug it?

**Comment by superseb** [comment]
Thats not really the same mechanism, RKE used embedded data or an external URL (specified by `RANCHER_METADATA_URL`) on run. Even when the container has no internet connection, it should still be able to use the embedded `data.json`.

The error you see on RKE is a different issue, but is quite clear. It can't connect so a (host) firewall is blocking connection(s).
