### ISSUE TITLE
v0.56.0-rc3 - Strange top-left clickable rancher logo opening a popup instead of redirecting to some home page

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3397]
version: v0.56.0-rc3

This is just personal opinion, but I never found the top left button logical.
I think I would find more logical to have a specific versions page, accessible from some sub menu in help, for example, and a top left button opening a basic dashboard.

![image](https://cloud.githubusercontent.com/assets/2150990/12535581/30927e50-c288-11e5-9a41-2d51117fa8d0.png)

**Comment by demarant** [comment]
+1 
I agree. From a usability point of view, top left logo should always go to a so called "Home". 
I would also prefer the Home to be the dashboard envisioned in #2718 
and move the rancher version info and falling cow :) to the top right or footer.

**Comment by demarant** [comment]
also reported in  #2404

**Comment by vincent99** [comment]
There is no home to point to, the version is already in the footer in next release, and #2404.
