### ISSUE TITLE
Insecure RKE2 Registration command is missing label

### ISSUE THREAD

**Issue by phillipsj** [rancher/rancher#33977]
**Rancher Server Setup**
- Rancher version: 2.6-head
- Installation option (Docker install/Helm Chart): docker

**Information about the Cluster**
Custom: RKE2 Cluster

**Describe the bug**
The insecure command doens't include the cattle label.

**To Reproduce**

Create a new RKE2 custom cluster and toggle between insecure and secure commands. 

**Result**

Regular command:

```
curl -fL https://ranchmain/system-agent-install.sh | sudo  sh -s - --server https://ranchmain --label 'cattle.io/os=linux' --token dhjjkrtvlxmtbt77qj65rtr4wfl7h8rtbqs9kxcltbvjwjw4sfrpbn --ca-checksum de8e09728b200a870956f4f5e7b3169b5642a03bbafa1704de4ca11de5e0ebbe --etcd --controlplane --worker
```

Insecure command:

```
curl --insecure -fL https://ranchmain/system-agent-install.sh | sudo  sh -s - --server https://ranchmain --token dhjjkrtvlxmtbt77qj65rtr4wfl7h8rtbqs9kxcltbvjwjw4sfrpbn --ca-checksum de8e09728b200a870956f4f5e7b3169b5642a03bbafa1704de4ca11de5e0ebbe --etcd --controlplane --worker
```

**Expected Result**
That the cattle label is included.

```
curl --insecure -fL https://ranchmain/system-agent-install.sh | sudo  sh -s - --server https://ranchmain --label 'cattle.io/os=linux' --token dhjjkrtvlxmtbt77qj65rtr4wfl7h8rtbqs9kxcltbvjwjw4sfrpbn --ca-checksum de8e09728b200a870956f4f5e7b3169b5642a03bbafa1704de4ca11de5e0ebbe --etcd --controlplane --worker
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1568133/128351978-93263c0c-47ba-40e8-90dc-89cdd16ce272.png)

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.
 
**Validation Steps:**

Rancher version: v2.6-head 723f747b1 8/10/21 9:19 am Pacific
Rancher cluster type: single-node docker
Docker version: 19.03
 
Downstream cluster type: rke2 custom cluster
Downstream K8s version: v1.21.3-rc4+rke2r2
 
Validation steps:

1. Create a new custom rke2 cluster and toggle between insecure and secure. Compare the two commands
2. Confirmed they both include the cattle label now:
Secure:
`curl -fL https://REDACTED_IP/system-agent-install.sh | sudo  sh -s - --server https://REDACTED_IP --label 'cattle.io/os=linux' --token REDACTED --ca-checksum REDACTED --etcd --controlplane --worker`
Insecure:
`curl --insecure -fL https://REDACTED_IP/system-agent-install.sh | sudo  sh -s - --server https://REDACTED_IP --label 'cattle.io/os=linux' --token REDACTED --ca-checksum REDACTED --etcd --controlplane --worker`

3. Created a 1-node rke2 custom cluster with the insecure command. Confirmed the label was actually applied to the node.
![image](https://user-images.githubusercontent.com/45179589/128902637-6f34c0c4-693c-4253-bde9-71a18b00b5c4.png)
