### ISSUE TITLE
Fleet - Clusters are in Wait Check-in state and errors "no Deployment with the name "fleet-agent" found]'" seen in bundles deployed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33980]
## Rancher Server Setup

- Rancher version: 2.6-head - commit id: e3316c9de
- Installation option (Docker install/Helm Chart): docker install

## Information about the Cluster
- Kubernetes version: 1.20.9
- Cluster Type (Local/Downstream): Downstream clusters

## Describe the bug
Fleet - Clusters are in Wait Check-in state and errors "no Deployment with the name "fleet-agent" found]'" seen in bundles deployed

## To Reproduce
- On an upgrade from 2.5.9 to 2.6-head - commit id: `e3316c9de`
- Deploy downstream clusters on 2.5.9
- Deploy Git repo and point to these clusters. Deployed successfully. (fleet agent: `v0.3.5`)
- Upgrade to 2.6-head
- Fleet is upgraded. new Fleet version: `rancher/fleet-agent:v0.3.6-rc9`
- Old fleet is deleted, and new fleet agent is deployed
- Clusters are in Wait Check-in state under Continuous Delivery tab. There are errors on the bundles:
```
message: 'ErrApplied(1) [Cluster fleet-default/c-gqn2r: no Deployment with the name "fleet-agent" found]'
```
- And on adding a new repo, it is in Wait Applied state.

EDIT: this is @nickgerace, I accidentally deleted the message and the formatting has changed as a result. Contents of this are still the same.

**Comment by nickgerace** [comment]
This issue likely requires https://github.com/rancher/rancher/issues/34077 to be solved first.

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to v2.6-head commit id: `c10ef4b0`**

- On 2.5.9 deploy a couple of downstream cluster
- In Continuous Delivery Deploy a Git repo
- It comes Up active and clusters in Active state
- On a rancher upgrade, New Fleet agent is deployed, and the old one is deleted.
- Existing clusters in Continuous delivery tab are Active. Able to deploy new bundles to the downstream clusters.
- Fleet version: `v0.3.6-rc12`
