### ISSUE TITLE
Double checksum flags are being added on RKE2 Windows Registration Command

### ISSUE THREAD

**Issue by phillipsj** [rancher/rancher#33983]
If this is a UI issue, please file an issue at https://github.com/rancher/dashboard/

**Rancher Server Setup**
- Rancher version: 2.6rc
- Installation option (Docker install/Helm Chart): docker

**Information about the Cluster**

RKE2 Custom cluster

**Describe the bug**
An extra and incorrect CA checksum flag is being added to the windows registration command.

```
curl.exe --insecure -fL https://<ip>/rke2-agent-install.ps1 -o install.ps1 
powershell.exe -ExecutionPolicy Bypass -Command "./install.ps1 -Server https://<ip> -Label 'cattle.io/os=windows' -Token <token> -Worker -CaChecksum  --ca-checksum <checksum>"
```

**To Reproduce**

Create an RKE2 custom cluster and register a server node, then look at the windows agent command.

**Comment by slickwarren** [comment]
this issue has been fixed on master-head(61339fb)/2.6-head(ba95a58)
`curl.exe --insecure -fL https://<IP>/rke2-agent-install.ps1 -o install.ps1 && powershell.exe -ExecutionPolicy Bypass -Command "./install.ps1 -Server https://<IP> -Label 'cattle.io/os=windows' -Token <token> -Worker -CaChecksum <checksum>"
