### ISSUE TITLE
Update the Rancher post-delete hook. It's leaving some fleet, remnants on latest 2.6 rc1

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#33986]
If this is a UI issue, please file an issue at https://github.com/rancher/dashboard/

**Rancher Server Setup**
- Rancher version:`2.6.0-rc1`
- Installation option:
   - HA RKE1 k8s 1.21 - CIS
- Proxy/Cert Details: N/A

**Describe the bug**

It seems that after doing `helm uninstall rancher -n cattle-system` fleet is not getting removed now.
This used to work on https://github.com/rancher/rancher/issues/30924

**To Reproduce**
- Install Rancher `v2.6.0-rc1`
- Then uninstall it with `helm uninstall rancher -n cattle-system`

**Result**

```
NAMESPACE             NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
cattle-fleet-system   deployment.apps/fleet-agent               1/1     1            1           13m
cattle-fleet-system   deployment.apps/fleet-controller          1/1     1            1           13m
cattle-fleet-system   deployment.apps/gitjob                    1/1     1            1           13m

NAMESPACE             NAME                                                 DESIRED   CURRENT   READY   AGE
cattle-fleet-system   replicaset.apps/fleet-agent-7c848bb648               0         0         0       13m
cattle-fleet-system   replicaset.apps/fleet-agent-b7688c69b                1         1         1       13m
cattle-fleet-system   replicaset.apps/fleet-controller-57c9c866f6          1         1         1       13m
cattle-fleet-system   replicaset.apps/gitjob-5778966b7c                    1         1         1       13m

NAMESPACE             NAME                                           READY   STATUS      RESTARTS   AGE
cattle-fleet-system   pod/fleet-agent-b7688c69b-8kmhr                1/1     Running     0          13m
cattle-fleet-system   pod/fleet-controller-57c9c866f6-8z22k          1/1     Running     0          13m
cattle-fleet-system   pod/gitjob-5778966b7c-gplrp                    1/1     Running     0          13m
```

**Expected Result**
Fleet also uninstalled

**Additional context**
https://github.com/rancher/rancher/issues/30924

**Comment by cbron** [comment]
Believe we just need to add `cattle-fleet-system` here: https://github.com/rancher/rancher/blob/release/v2.6/chart/values.yaml#L148-L150

@nickgerace can confirm we want those all removed, I am under impression we do, and this bug was just part of namespace switch on fleet side.

**Comment by nickgerace** [comment]
That is correct. We need to include **both** cattle-fleet-system and fleet-system because Fleet needs to still support 2.5.x

**Comment by jiaqiluo** [comment]
It is right, we just need to add the new namespace `cattle-fleet-system` to the list.

**Comment by kinarashah** [comment]
Available to test with `v2.6.0-rc2`

**Comment by izaac** [comment]
Probably not related or blocker as Rancher but I've opened this issue when upgrading an Airgap HA 
https://github.com/rancher/rancher/issues/34184

**Comment by brendarearden** [comment]
Validation: PASSED

**Steps to recreate:** 

##Rancher v2.5.9 to confirm cleanup of fleet-system
1. Create HA RKE1 K8s 1.20.9, installing Rancher v2.5.9
2. run `helm install rancher rancher-latest/rancher --namespace cattle-system --create-namespace --set hostname=brendar.do.rancher.space --version v2.5.9 --set rancherImagePullPolicy=Always --kubeconfig kube_config_cluster.yml` 
3. run `kg pods -n cattle-system --kubeconfig kube_config_cluster.yml` to see pods deployed
```
NAME                       READY   STATUS    RESTARTS   AGE
rancher-859746f565-5vz5f   0/1     Running   0          20s
rancher-859746f565-6vtwm   0/1     Running   0          20s
rancher-859746f565-j58jt   0/1     Running   0          20s
```
4. run `kg pods -n fleet-system --kubeconfig kube_config_cluster.yml` to see pods deployed
```
NAME                                READY   STATUS    RESTARTS   AGE
fleet-agent-d59db746-xjqqq          1/1     Running   0          3m4s
fleet-controller-79554fcbf5-tnxn9   1/1     Running   0          3m35s
gitjob-568c57cfb9-vw97n             1/1     Running   0          3m35s
```
5. run `helm uninstall rancher --namespace cattle-system --kubeconfig kube_config_cluster.yml`
6.  run `kg pods -n cattle-system --kubeconfig kube_config_cluster.yml` to see pods are cleaned up as expected
```
No resources found in cattle-system namespace.
```
7.  run `kg pods -n fleet-system --kubeconfig kube_config_cluster.yml` to see pods are cleaned up as expected
```
No resources found in fleet-system namespace.
```

##Rancher v2.6.0-rc1
1. Create HA RKE1 K8s 1.20.9, installing Rancher v2.6.0-rc1
2. run `helm install rancher rancher-latest/rancher --namespace cattle-system --create-namespace --set hostname=brendar.do.rancher.space --version v2.6.0-rc1 --set rancherImagePullPolicy=Always --kubeconfig kube_config_cluster.yml` 
3. run `kg pods -n cattle-system --kubeconfig kube_config_cluster.yml` to see pods deployed
```
NAME                               READY   STATUS      RESTARTS   AGE
helm-operation-7zk47               0/2     Completed   0          75s
helm-operation-tx665               0/2     Completed   0          80s
helm-operation-x6fbv               0/2     Completed   0          90s
rancher-6d6874f7d7-l6jxp           1/1     Running     0          2m54s
rancher-6d6874f7d7-rhfmg           1/1     Running     0          2m54s
rancher-6d6874f7d7-wmskt           1/1     Running     0          2m54s
rancher-webhook-6577fc98c6-vg7jd   1/1     Running     0          72s
```
4. run `kg pods -n cattle-fleet-system --kubeconfig kube_config_cluster.yml` to see pods deployed
```
NAME                                READY   STATUS    RESTARTS   AGE
fleet-controller-79554fcbf5-5dkw4   1/1     Running   0          108s
gitjob-568c57cfb9-66zmt             1/1     Running   0          108s
```
5. run `helm uninstall rancher --namespace cattle-system --kubeconfig kube_config_cluster.yml`
6.  run `kg pods -n cattle-system --kubeconfig kube_config_cluster.yml` to see pods are cleaned up as expected
```
No resources found in cattle-system namespace.
```
7.  run `kg pods -n fleet-system --kubeconfig kube_config_cluster.yml` to see pods have not been cleaned up as expected
```
NAME                                READY   STATUS    RESTARTS   AGE
fleet-controller-79554fcbf5-5dkw4   1/1     Running   0          2m42s
gitjob-568c57cfb9-66zmt             1/1     Running   0          2m42s
```

**Steps to Validate:** 
##Rancher v2.6.0-rc3
1. Create HA RKE1 K8s 1.20.9, installing Rancher v2.6.0-rc3
2. run `helm install rancher rancher-latest/rancher --namespace cattle-system --create-namespace --set hostname=brendar.do.rancher.space --version v2.6.0-rc3 --set rancherImagePullPolicy=Always --kubeconfig kube_config_cluster.yml` 
3. run `kg pods -n cattle-system --kubeconfig kube_config_cluster.yml` to see pods deployed
```
NAME                               READY   STATUS      RESTARTS   AGE
helm-operation-dxdwp               0/2     Completed   0          52s
helm-operation-rjfjt               0/2     Completed   0          41s
rancher-766877bf7c-2h679           1/1     Running     0          117s
rancher-766877bf7c-88vhk           1/1     Running     0          117s
rancher-766877bf7c-gtmqd           1/1     Running     0          117s
rancher-webhook-6577fc98c6-vwgsj   1/1     Running     0          38s
```
4. run `kg pods -n cattle-fleet-system --kubeconfig kube_config_cluster.yml` to see pods deployed
```
NAME                                READY   STATUS    RESTARTS   AGE
fleet-controller-859995d896-zn7vk   1/1     Running   0          3m18s
gitjob-5778966b7c-cphwx             1/1     Running   0          3m18s
```
5. run `helm uninstall rancher --namespace cattle-system --kubeconfig kube_config_cluster.yml`
6.  run `kg pods -n cattle-system --kubeconfig kube_config_cluster.yml` to see pods are cleaned up as expected
```
No resources found in cattle-system namespace.
```
7.  run `kg pods -n fleet-system --kubeconfig kube_config_cluster.yml` to see pods are now cleaned up as expected
```
No resources found in fleet-system namespace.
```
