### ISSUE TITLE
Too many v3.Nodes created for RKE2/K3S cluster provisioned in Rancher

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#33991]
**Rancher Server Setup**
- Rancher version: 2.6-head
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: 1.19.6
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2/K3S

**Describe the bug**

After creating an RKE2/K3S cluster in Rancher, there are two many v3.Nodes in Rancher for the cluster.
**To Reproduce**
 
1. Provision an RKE2/K3S cluster from Rancher with 3 nodes with all roles.
2. Wait for the cluster to become active.

**Result**
Look at the old (Ember) UI. The number of nodes is likely to be greater than 3.

**Expected Result**

There should be exactly 3 v3.Nodes created for the cluster.

**Screenshots**

Vue UI:
![Screen Shot 2021-08-05 at 1 24 41 PM](https://user-images.githubusercontent.com/3682717/128416344-0410158a-a417-4021-8035-d8f40016409a.png)
Ember UI:
![Screen Shot 2021-08-05 at 1 25 19 PM](https://user-images.githubusercontent.com/3682717/128416373-8642826b-f4e2-40a5-a432-e0b617e74a8f.png)

**Additional context**
<!--Add any other context about the problem here.—>
This seems to only happen on HA installs (i.e. > 1 Rancher pod)

**Comment by sowmyav27** [comment]
Dup of this - https://github.com/rancher/rancher/issues/33020
