### ISSUE TITLE
New fleet agent is not deployed and the Old fleet agent is still present after rancher server upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33993]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `246fbd5fa`
- Installation option (Docker install/Helm Chart): docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.20.9 and 1.19 downstream clusters
- Cluster Type (Local/Downstream): - DO and EC2 rke1 clusters

**Describe the bug**
New fleet agent is not deployed and the Old fleet agent is still present after rancher server upgrade

**To Reproduce**

- Deploy rancher on 2.5.9
- Deploy a couple of downstream clusters - RKE1 DO and AWS
- Upgrade rancher to 2.6-head
- Notice the old fleet agent - 0.3.5 still present
- Fleet controller workload is created - `rancher/fleet:v0.3.6-rc9` (been around 10 minutes)
- New fleet agent is _not_ deployed.

**Expected Result**
New fleet agent should get deployed, and old one should be depleted. 

**Note:**
I see it got deployed after 15 minutes

**Comment by sowmyav27** [comment]
Similar to  [this](https://github.com/rancher/rancher/issues/32560) one

**Comment by nickgerace** [comment]
Using @sowmyav27's setup for this issue:

The old agent is still alive (v0.3.5) in the downstream clusters, and the new agent (deployed 15 minutes later) (v0.3.6-rc9) is logging the following error:

```
time="2021-08-05T22:04:23Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: looking up secret cattle-fleet-system/fleet-agent-bootstrap: secrets \"fleet-agent-bootstrap\" not found"
--
Thu, Aug 5 2021 6:05:23 pm | time="2021-08-05T22:05:23Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: looking up secret cattle-fleet-system/fleet-agent-bootstrap: secrets \"fleet-agent-bootstrap\" not found"
Thu, Aug 5 2021 6:06:23 pm | time="2021-08-05T22:06:23Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: looking up secret cattle-fleet-system/fleet-agent-bootstrap: secrets \"fleet-agent-bootstrap\" not found"
Thu, Aug 5 2021 6:07:23 pm | time="2021-08-05T22:07:23Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: looking up secret cattle-fleet-system/fleet-agent-bootstrap: secrets \"fleet-agent-bootstrap\" not found"
Thu, Aug 5 2021 6:08:23 pm | time="2021-08-05T22:08:23Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: looking up secret cattle-fleet-system/fleet-agent-bootstrap: secrets \"fleet-agent-bootstrap\" not found"
Thu, Aug 5 2021 6:09:23 pm | time="2021-08-05T22:09:23Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: looking up secret cattle-fleet-system/fleet-agent-bootstrap: secrets \"fleet-agent-bootstrap\" not found"
Thu, Aug 5 2021 6:10:23 pm | time="2021-08-05T22:10:23Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: looking up secret cattle-fleet-system/fleet-agent-bootstrap: secrets \"fleet-agent-bootstrap\" not found"
Thu, Aug 5 2021 6:11:23 pm | time="2021-08-05T22:11:23Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: looking up secret cattle-fleet-system/fleet-agent-bootstrap: secrets \"fleet-agent-bootstrap\" not found"
Thu, Aug 5 2021 6:12:23 pm | time="2021-08-05T22:12:23Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: looking up secret cattle-fleet-system/fleet-agent-bootstrap: secrets \"fleet-agent-bootstrap\" not found"
```

**Comment by nickgerace** [comment]
This issue likely requires https://github.com/rancher/rancher/issues/34077 to be solved first.

**Comment by nickgerace** [comment]
This issue likely requires https://github.com/rancher/rancher/issues/34077 to be solved first.

**Comment by nickgerace** [comment]
Likely dependent on https://github.com/rancher/rancher/issues/34078 being solved.

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to v2.6-head commit id: `c10ef4b0`**

- On 2.5.9 deploy a couple of downstream cluster
- In Continuous Delivery Deploy a Git repo
- It comes Up active and clusters in Active state
- On a rancher upgrade, New Fleet agent is deployed, and the old one is deleted.
- Existing clusters in Continuous delivery tab are Active. Able to deploy new bundles to the downstream clusters.
- Fleet version: `v0.3.6-rc12`
