### ISSUE TITLE
v0.56.0-rc3 - UI - white on gray color problem

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3399]
on rancher.dev/infra/containers/1i1/volumes:

![image](https://cloud.githubusercontent.com/assets/2150990/12535922/1e305f32-c294-11e5-9681-a8d2e6a09bcd.png)

**Comment by deniseschannon** [comment]
@lvuch @westlywright Can you find out which theme this is having issues with?

**Comment by ibuildthecloud** [comment]
@rvion thanks for bravely testing our RC :smile:

**Comment by rvion** [comment]
@deniseschannon it's `light` theme

**Comment by lvuch** [comment]
@deniseschannon I have an open pr with a fix for this

**Comment by tfiduccia** [comment]
version - master 1/27
Verified fixed
