### ISSUE TITLE
New CRTB controller needs to gather all referenced RoleTemplateNames from the RoleTemplate

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#33998]

**Comment by dramich** [comment]
QA: To test, create a new clusterRoleTemplate that inherits from cluster-member as the only permission and add to a standard user. Before the change this will not allow you to see the provisioning cluster, after it should be visible in the API.

**Comment by izaac** [comment]
Rancher version: `2.6.0-rc3`

- Create a CRT inheriting the `cluster-member` with displayName `member-test`
- Added an standard user `user1` and assigned the `member-test` role while adding the user1 as cluster member from the Dashboard UI
- On a separate browser I signed in as `user1` and I am able to access the cluster I assigned this user as member
