### ISSUE TITLE
Should have an option to remove machines associated with purging environment

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#340]
Steps:
1.  Create a environment
2.  Add a DO machine/host to the environment
3.  Add a container to Host
4.  Purge environment

Results:
Machine/host and container still exist with no way to access them.  I have to go to DO website to delete.

Expected:
We should probably allow user to delete all into associated to that environment.

**Comment by will-chan** [comment]
Is this a UI issue?  It seems better for cattle to clean up resources when you delete an environment.

**Comment by vincent99** [comment]
It is not UI, Cattle should do it when deleting an environment.  The UI could probably warn that it will happen though...

**Comment by will-chan** [comment]
This might not be a trivial fix.

**Comment by hibooboo2** [comment]
Addressed with rancher/cattle#855

**Comment by deniseschannon** [comment]
Verified with v0.39.0-rc1 that purging an environment removes machines. This happens no matter what.

Created an https://github.com/rancher/rancher/issues/2131 to create an opt out option if users want it.

Created a UI request to add in a warning that purging would delete the associated hosts created through the API.
