### ISSUE TITLE
User is logged out after rancher server upgrade and has to login to back

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34004]
**Rancher Server Setup** 
- Rancher version: upgrade from 2.5.9 to 2.6-head commit id: `246fbd5`
- Installation option (Docker install/Helm Chart): docker install
- Proxy/Cert Details: rancher generated

**Information about the Cluster**
- Kubernetes version: 1.20 and 1.19 deployed Downstream clusters
- Cluster Type (Local/Downstream): RKE1 DO/AWS clusters

**Describe the bug**
user is logged out after rancher server upgrade and has to login to access clusters

**To Reproduce**

- On 2.5.9, deploy a couple of RKE1 clusters
- Upgrade rancher to 2.6-head
- User is logged out
- Admin/Standard user, have to login back to access rancher and clusters

**Expected Result**
User is should not be logged out.

**Comment by vincent99** [comment]
This was intentionally done to get people into the new dashboard  instead of whatever old version of ember they had up at the time.  But there's more needed to make it so you don't just end up logging back into ember.

**Comment by deniseschannon** [comment]
This is expected, but should be release-noted.
