### ISSUE TITLE
Clusters in Continuous Delivery Tab is stuck in "Wait Check In" state

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34005]
**Rancher Server Setup**
- Rancher version: upgrade from 2.5.6 to 2.6-head commit id: `ba95a58`
- Installation option (Docker install/Helm Chart): docker install
- Proxy/Cert Details: rancher generates

**Information about the Cluster**
- Kubernetes version: 1.20 and 1.19 downstream clusters
- Cluster Type (Local/Downstream): RKE1 - AWS Node driver

**Describe the bug**
Clusters in Continuous Delivery Tab is stuck in "Wait Check In" state

**To Reproduce**

- On 2.5.9 deploy a couple of downstream cluster
- In Continuous Delivery Deploy a Git repo
- It comes Up active and clusters in Active state
- On a rancher upgrade, New Fleet agent is deployed, and the old one is deleted.
- I see One of the clusters is in Wait Check In state and the other one is Active
- Error on the one in Wait Check In state is
```
Modified(1) [Bundle fleet-agent-c-xz7r9]; clusterrole.rbac.authorization.k8s.io fleet-system-fleet-agent-role extra; deployment.apps cattle-fleet-system/fleet-agent missing; deployment.apps fleet-system/fleet-agent extra; networkpolicy.networking.k8s.io fleet-system/default-allow-all extra
```

**Expected Result**
Clusters/Bundles should be Active under Continuous delivery

**Comment by nickgerace** [comment]
This issue likely requires https://github.com/rancher/rancher/issues/34077 to be solved first.

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to v2.6-head commit id: `c10ef4b0`**

- On 2.5.9 deploy a couple of downstream cluster
- In Continuous Delivery Deploy a Git repo
- It comes Up active and clusters in Active state
- On a rancher upgrade, New Fleet agent is deployed, and the old one is deleted.
- Existing clusters in Continuous delivery tab are Active. Able to deploy new bundles to the downstream clusters.
