### ISSUE TITLE
Jaeger All-In-One 1.25+

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#34017]
Need to upgrade Jaeger All-In-One to latest release

Current version of Jaeger All-In-One bundled in with Istio is 1.20
Latest version available Jaeger All-In-One is 1.25 https://www.jaegertracing.io/docs/1.25/

**Comment by cbron** [comment]
When does this need to go in ?

**Comment by PennyScissors** [comment]
Re-assigned this to the purple team.

**Comment by rayandas** [comment]
Jaeger has released 1.26 yesterday. https://www.jaegertracing.io/docs/1.26/

**Comment by samkulkarni20** [comment]
With [#1578](https://github.com/rancher/charts/pull/1578) we have updated the Jaeger chart version to 1.27

**Comment by vivek-infracloud** [comment]
On rancher/rancher:v2.6.2

- Create a cluster
- Install Istio app w/ Jaeger & ingress gateway enabled
- Deploy demo bookservice
- Send 100 requests to the service through the ingress gateway:
``` for i in {1..100}; do curl http://<worker_node>:31380/productpage; done```
- From Istio dashboard page, navigate to Jaeger
- Service dropdown should contain multiple services, tracing should work
