### ISSUE TITLE
Fix test_perform_workload_action_read_only test

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34016]
Frequent "waiting for workload" timeouts from the `test_perform_workload_action_read_only` cause it to fail intermittently.

Potential solutions:
- check if we even need for it to be active
- check if we even have the right object
- increase timeout (worst case scenario)

**Comment by deniseschannon** [comment]
There is nothing to test except to view builds to see if this is test is still failing, so closing for now.
