### ISSUE TITLE
system-agent should not apply plans that are older than the last known applied plan

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#34027]
the system-agent can receive a plan to process that has an older resource version than the plan that was just applied. in this case the plan should not be applied.

**Comment by Oats87** [comment]
Needs to be backported to `release/v2.6`

**Comment by deniseschannon** [comment]
@Oats87 How does someone test this?

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.
 
**Validation Steps:**

Rancher version: v2.6-head 4b6af95d7 8/9/21 9:25 am Pacific
Rancher cluster type: single-node docker
Docker version: 19.03
 
Downstream cluster type: rke2 (digital ocean)
Downstream K8s version: v1.21.3-rc4+rke2r2
 
Validation steps:

1. Create an RKE2 cluster with Rancher using an s3 bucket
2. Manually take a snapshot once the cluster is ready
3. Can confirm that the agent no longer takes two snapshots:
![image](https://user-images.githubusercontent.com/45179589/128742968-4eeefe3e-c0b9-4dd0-8c19-d209c81de5b6.png)
