### ISSUE TITLE
navlinks: project members are not able to see the navlinks when toService is used to create navlinks

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34030]
If this is a UI issue, please file an issue at https://github.com/rancher/dashboard/

**Rancher Server Setup**
- Rancher version: v2.6-head ba95a58
- Installation option (Docker install/Helm Chart): Docker installe
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version:  v1.21.3-rc4+rke2r2
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
Infrastructure provider DO 3 nodes with 1 role each

**Describe the bug**
When we create a `toService` URL in the navlinks for grafana, project members are not able to see the navlink.
They have access to monitoring and grafana but only navlink is not seen.
 

**To Reproduce**

- Create an rke2 node driver cluster.
- Enable monitoring in the cluster
- Add a project owner in the `default` project and to `system` project with custom `view monitoring` 
- Create a navlink with the following fields:

```
  toService:
    name: rancher-monitoring-grafana
    namespace: cattle-monitoring-system
    path: /?orgId=1
    port: "80"
    scheme: http
```

**Result**
- Log in as the project owner and verify the user has access to monitoring but cannot see the navlink created for grafana.

**Expected Result**
Project owners/members when they have access to monitoring should be able to see the navlinks created in toService

**Additional context**
Ref issue: https://github.com/rancher/rancher/issues/33093

navlinks yaml:
[group&standalonenavlinks.zip](https://github.com/rancher/rancher/files/6948061/group.standalonenavlinks.zip)

**Comment by deniseschannon** [comment]
Note: For this use case, in the UI under Monitoring, I'm able to click on Grafana which brings me to: 
```
https://<SERVER-URL>/k8s/clusters/<CLUSTER-ID>/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/?orgId=1
```

This is what @vincent99 says he is building the link to, but the navlink isn't showing up on the sidebar. 

Is this code actually checking the right thing @ibuildthecloud ?

https://github.com/rancher/rancher/blob/256a0eb26f6e37efbdd13f40506d08d719d2bee6/pkg/api/steve/navlinks/store.go#L23-L31

**Comment by anupama2501** [comment]
Verified the following test scenarios for `toService`:

Created an rke1 node driver cluster with 3 worker,1 cp, 1 etcd 
Installed istio and monitoring in the cluster in the system project
Created `toService` navlinks for kiali and grafana - group and standalone navlinks.
Enabled AD auth and created 1 standard user from users and authentication tab.

**member with only monitoring access:**
1. Added user1 as a project owner of the `default` project and `view monitoring` custom role in the system project.
2. Login as user1
3. Verified user has only access to `monitoring` in the cluster.
4. Navlink created for monitoring can be viewed and accessed by the project owner
5. Istio is not visible to the user.

** member with access to both monitoring and istio**
1. Added user2 as project member in the system project
2. Logged in as user2 
3. Verified user2 can access both monitoring and istio -  grafana and kiali respectively.
4. Verified access to navlinks to both kiali and grafana is viewed and accessible.


** member only with no access to both monitoring and istio**
1. Addedd user3 as project member in the default project
2. Verified access to monitoring and istio is not given
3. Verified both kiali and grafana navlinks are not visible to the user
