### ISSUE TITLE
forwardport: RKE2 Templates: Deleting cluster created with a template does not clean up all resources (digitaloceanConfigs left behind)

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34035]
forwardport of https://github.com/rancher/rancher/issues/33259

Note: I am unsure why the behavior was different from master-head/2.6-head, as the code changes were the same in the PRs from above.  Perhaps this issue is intermittently occurring after the last fix was applied. 

Repro Steps:
tested on master-head(61339fb):
* create 2 clusters via rke2 cluster templates (from same template) -- pass
* delete cluster created via rke2 template -> create another cluster using same template -- pass
* create a cluster via template with bad values (i.e. secret that does not exist), then remove that failed cluster and create another with all valid values -- FAIL with the below error:
```
Fri, Aug 6 2021 2:57:55 pm | helm install --generate-name=true --namespace=fleet-default --timeout=10m0s --values=/home/shell/helm/values-qa-v2charts-template-0.0.4.yaml --version=0.0.4 --wait=true /home/shell/helm/qa-v2charts-template-0.0.4.tgz
Fri, Aug 6 2021 2:57:56 pm | Error: rendered manifests contain a resource that already exists. Unable to continue with install: DigitaloceanConfig "qa-nooveride0" in namespace "fleet-default" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "qa-v2charts-template-0-1628287075": current value is "qa-v2charts-template-0-1628286611"

```
I'm not sure why I can repro this on master, but not on 2.6.0-rc1. maybe it is a timing thing as well, making this more difficult to reproduce.

**Comment by deniseschannon** [comment]
@slickwarren Since we're no longer going to use the master-head branch, can we close this?

**Comment by slickwarren** [comment]
closing in light of the above information
