### ISSUE TITLE
login token for kubeconfig with rancher cli not being properly generated

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#34033]
If this is a UI issue, please file an issue at https://github.com/rancher/dashboard/

**Rancher Server Setup**
- Rancher version:
master-head (da1adad)

**Information about the Cluster**
- Kubernetes version:
local: v1.21.3+k3s1
- Downstream:
DO: v1.21.3

**Describe the bug**

When token has expired the kubectl with embedded CLI prompts for the token twice.

**To Reproduce**
 
1. provision DO cluster
2. set kubeconfig-generate-token setting to "false"
3. set kubeconfig-token-ttl-minutes to "1"
4. use generate kubeconfig
5. make requests like `kubectl get nodes` using kubeconfig, login on first attempt
6. after a little less than a minutes start trying to run the command again

**Result**
Will be prompt for token twice, this is because the first token returned was not actually generated causing rancher to return a 401 and the rancher cli to be ran again. The second time works because the original token has successfully deleted which is what is needed before the token can be created again.

Found this while investigating https://github.com/rancher/rancher/issues/33771.

**Expected Result**
Should be prompted to login once, and command should be successful. This should work for both contexts on the kubeconfig.

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.6.0-rc2**

- provision DO cluster
- set kubeconfig-generate-token setting to "false"
- set kubeconfig-token-ttl-minutes to "1"
- use generate kubeconfig
- make requests like kubectl get nodes using kubeconfig, login on first attempt
- after a little less than a minutes start trying to run the command again
- User is prompted to login two times.
