### ISSUE TITLE
Load balancer return 503 after manual restart container

### ISSUE THREAD

**Issue by taina0407** [rancher/rancher#3404]
Yesterday I've found an issue about rancher load balancer. It stop working after I manually restart container of one service.
Step to cause the issue:
1. Create a stack A, and service A1
2. Create a stack B, and load balancer B1 that links to A1 (http://IP:8080)
3. Start all stack A and stack B. Check if that work.
4. Go to "Infrastructure -> Host" and restart container of A1.
5. Check the connection to http://IP:8080 is return 503.
6. Restart B1 and the problem gone.

**Comment by kaos** [comment]
Ah, this might've hit me the other day too, but I failed to figure out what had happened, so +1 from me.

**Comment by deniseschannon** [comment]
This is the same issue as seen in https://github.com/rancher/rancher/issues/3360

Closing in favor of the other issue.
