### ISSUE TITLE
Not able to deploy clusters when external auth provider is enabled

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34042]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `0ab00d`
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: rancher generated

**Information about the Cluster**
- Kubernetes version: 1.20.9
- Cluster Type (Local/Downstream): Downstream - Windows custom RKE1, k3s Imported

**Describe the bug**
Not able to deploy clusters as a standard user when external auth provider is enabled

**To Reproduce:**
- On 2.6-head, enable GH Auth or AD Auth
- Deploy clusters using standard user token/as an admin
- Windows custom RKE1 and Imported k3s clusters dont come up. Error seen - `Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (InternalError): an error on the server ("unable to create impersonator account: error getting service account token: serviceaccounts \"cattle-impersonation-system/cattle-impersonation-u-kl3nli645y\" not found") has prevented the request from succeeding`
- Imported RKE2 works fine though
<img width="1273" alt="Screen Shot 2021-08-07 at 11 13 45 AM" src="https://user-images.githubusercontent.com/26032343/128610233-e170dccf-b5e6-465a-afe8-296d9c929144.png">

**Note:**
On 2.6.0-rc1 it works

**Comment by sowmyav27** [comment]
**On 2.6 - head commit id: `4b6af95d` and on master-head commit id: `524aec1`**

- On 2.6-head, enable AD Auth HA setup
- Deploy clusters using standard user token/as an admin - RKE1 custom clusters
- No issues seen, Clusters come up Active

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to 2.6.0-rc2 , this issue is seen,**

- On 2.5.9 deploy a few downstream clusters
- Upgrade rancher to 2.6.0-rc2
- One of the downstream clusters (Custom RKE1 cluster) is stuck in `Provisioning` state with error `Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (InternalError): an error on the server ("unable to create impersonator account: error getting service account token: serviceaccounts \"cattle-impersonation-system/cattle-impersonation-u-bdasg4j7sc\" not found") has prevented the request from succeeding`

**Comment by cmurphy** [comment]
I was never able to reproduce this myself, but we've merged a change that will hopefully address the issue. If it doesn't, we also added trace logging so that if the problem is seen again, we can get more information about it.

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to 2.6-head commit id: `f811996`**

- This issue was not seen, The setup was exactly as it was when the issue was originally seen
- A cluster - with all v2 charts enabled. Custom cluster - 1 etc/control plane and 3 worker nodes
- Will close this issue. Will reopen or log a new one if we see this again.
