### ISSUE TITLE
Validate Apps & Marketplace features on k8s 1.22 clusters

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34057]
This is a tracking issue to validate v2 features on k8s 1.22 clusters:

[ ] Alerting Drivers
[x] CIS Benchmarks - https://github.com/rancher/rancher/issues/32301
[x] External IP Webhook - https://github.com/rancher/rancher/issues/33513 - No longer supported as of k8s 1.22
[ ] Istio v2
[ ] Logging v2
[ ] Longhorn
[ ] Monitoring v2
[x] OPA Gatekeeper - https://github.com/rancher/rancher/issues/32300
[ ] sriov
[ ] vsphere CPI/CSI - https://github.com/rancher/rancher/issues/33848
[x] rancher/backup - https://github.com/rancher/rancher/issues/34154

**Comment by kinarashah** [comment]
Steps to get a downstream RKE1 1.22 cluster: 
- Available to test with v2.6-head, make sure it's an image after this build https://drone-publish.rancher.io/rancher/rancher/6862.
- Update `rke-metadata-config` (Global settings -> rke-metadata-config) URL's branch from `dev-v2.6` to `dev-v2.6-122`
- Make sure `v1.22.3-rancher1-1` shows up as experimental when provisioning RKE1 clusters

**Comment by kinarashah** [comment]
Monitoring v2 issues: 
https://github.com/rancher/dashboard/issues/4581 
https://github.com/rancher/rancher/issues/35571

**Comment by sowmyav27** [comment]
Validated the following charts on rancher 2.6-head and a downstream 1.22.3-rancher1-1 cluster
P0 usecase works fine for the charts
[ ] Alerting Drivers
[ ] CIS Benchmarks
[ ] External IP Webhook 
[ ] Istio v2
[ ] Logging v2
[ ] Longhorn
[ ] Monitoring v2
[ ] OPA Gatekeeper
[ ] sriov
[ ] vsphere CPI/CSI  --> Existing issues
[ ] rancher/backup

**Comment by anupama2501** [comment]
External IP webhook is not supported from v1.22 k8s version https://github.com/rancher/rancher/issues/33893

**Comment by ronhorton** [comment]
Testing is complete for first pass. Appropriate issues have been filed for 2.6.4 milestone.
