### ISSUE TITLE
Support k8s 1.22 in k8s clusters (updating go-client)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34054]
K8s 1.22 is dropping several APIs in 1.22 and requires significant changes within Rancher to support the dropped APIs as well as ability to support when the new APIs were introduced. 

Since Rancher supports multiple k8s versions in a single Rancher release, we need to be able to continue supporting the mix of dropped APIs and new APIs across the different versions. 

There are several issues tracking different parts of k8s 1.22, but this will be the issue to track introducing k8s 1.22 into Rancher (go-client).

**Comment by kinarashah** [comment]
When vendoring RKE to bring in new etcd client code (still need to make it work with both v3 and v2, currently bringing in v3), etcd error goes away, but seeing new errors on build: 

```
pkg/api/steve/proxy/proxy.go:53:3: cannot use sar (type "k8s.io/client-go/kubernetes/typed/authorization/v1".SubjectAccessReviewInterface) as type "k8s.io/client-go/kubernetes/typed/authorization/v1".AuthorizationV1Interface in field value:
	"k8s.io/client-go/kubernetes/typed/authorization/v1".SubjectAccessReviewInterface does not implement "k8s.io/client-go/kubernetes/typed/authorization/v1".AuthorizationV1Interface (missing LocalSubjectAccessReviews method)
# github.com/rancher/rancher/pkg/httpproxy
pkg/httpproxy/proxy.go:87:3: cannot use scaledContext.K8sClient.AuthorizationV1().SubjectAccessReviews() (type "k8s.io/client-go/kubernetes/typed/authorization/v1".SubjectAccessReviewInterface) as type "k8s.io/client-go/kubernetes/typed/authorization/v1".AuthorizationV1Interface in field value:
	"k8s.io/client-go/kubernetes/typed/authorization/v1".SubjectAccessReviewInterface does not implement "k8s.io/client-go/kubernetes/typed/authorization/v1".AuthorizationV1Interface (missing LocalSubjectAccessReviews method)
# github.com/rancher/rancher/pkg/api/norman/customization/monitor
pkg/api/norman/customization/monitor/prometheus_manager.go:129:36: not enough arguments in call to q.api.LabelValues
	have (context.Context, string, time.Time, time.Time)
	want (context.Context, string, []string, time.Time, time.Time)
	```

**Comment by kinarashah** [comment]
**Rancher Local: v1.22**
Downstream: 
- [ ] RKE1 v1.22.3-rancher1 
- [ ] RKE1 v1.21.x 
- [ ] RKE1 v1.18.16 
- [ ] Imported v1.22.3 
- [ ] Imported v1.18.16

**Rancher Local: v1.18**
Downstream: 
- [ ] RKE1 v1.22.3-rancher1 
- [ ] RKE1 v1.21.x 
- [ ] RKE1 v1.18.16 
- [ ] Imported v1.22.3 
- [ ] Imported v1.18.16

**Comment by anupama2501** [comment]
Verified the following on local rancher HA installed on k8s v1.22. v2.6-head e322f8f

HA with local RKE1 cluster with k8s 1.22 and rke 1.3.3-rc2
verified rancher server comes up Active,
verified all pods/workloads in System project of the local cluster are in Active state

**Downstream RKE1 clusters:**

RKE1 v1.22.3-rancher1 - Validation tests passed
RKE1 v1.21.6 - Validation tests passed
RKE1 v1.18.16 - Validation tests passed
Imported RKE2 v1.22.3 - Validations tests passed 
Imported RKE1 v1.22.3 – Validations tests passed 
Imported RKE1 v1.18.20 – Validations tests passed and ingress test is Pending but seeing this issue currently https://github.com/rancher/rancher/issues/35650

**Verified local HA installed on k8s v1.18.16**

RKE1 v1.22.3-rancher1 FAILED - Ingress pages are not loading https://github.com/rancher/rancher/issues/35636
RKE1 v1.21.6 - Validation tests passed
RKE1 v1.18.20 - Validation tests passed

FAILED https://github.com/rancher/rancher/issues/35650
Imported v1.22.3
Imported v1.18.20

**Comment by anupama2501** [comment]
Closing this issue as the failed testcases were validated in the above linked ticket:
