### ISSUE TITLE
Support k8s 1.22 in RKE2/k3s

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34056]
This is to track and validate when k8s 1.22 for RKE2 clusters

**Comment by cbron** [comment]
Assuming work here will be done by RKE2 team, and this issue will handle KDM/QA only.

**Comment by kinarashah** [comment]
Assigning @rancher-max to introduce 1.22 RKE2/k3s versions in KDM now that Rancher `v2.6-head` runs on local 1.22. 
Changes would go into `dev-v2.6-1.22` KDM branch. 

Keeping myself assigned so I don't miss on tracking these versions for final release.

**Comment by deniseschannon** [comment]
Closing in favor of this issue: https://github.com/rancher/rancher/issues/35369
