### ISSUE TITLE
impossible to clone a VM in the UI: error page on click

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3405]
![image](https://cloud.githubusercontent.com/assets/2150990/12554806/846ee71a-c37e-11e5-8c9c-af34cfc45e41.png)

gives:

![image](https://cloud.githubusercontent.com/assets/2150990/12554772/5e682824-c37e-11e5-875a-86158bfff3ee.png)

**Comment by vincent99** [comment]
Duplicate #3156
