### ISSUE TITLE
view logs on the pods does not work

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34052]
If this is a UI issue, please file an issue at https://github.com/rancher/dashboard/

**Rancher Server Setup**
- Rancher version: v2.6.0-rc1
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Self-signed

**Information about the Cluster**
- Kubernetes version: v1.21.3, v1.21.3+rke2r1, v1.20.9-rancher1-2, v1.19.13-rancher1-2
- Cluster Type (Local/Downstream): Downstream 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
   Imported RKE1 and Imported RKE2, infrastructure provider - 3 worker, 3 etcd, 1 cp.

**Describe the bug**
View logs on the pods do not work. It shows disconnected with an error in the console.

**To Reproduce**
1. Create a workload in the downstream cluster.
2. From the pods, click on view logs
**Note**: Rancher is upgraded from v2.5.9 to v2.6.0-rc1

**Result**
Logs are not shown and the screen displays disconnected. 

**Expected Result**
Logs should be displayed 

**Additional context**
Similar issue: https://github.com/rancher/rancher/issues/34044

**Console logs:**
`
component.js:164 WebSocket connection to 'wss://ip/k8s/clusters/c-m-4d887d19/api/v1/namespaces/test-74441/pods/test-90643-67bfd9d4b5-9c564/log?container=test-97046&tailLines=500&follow=true&timestamps=true&previous=false' failed`

**Comment by anupama2501** [comment]
Verified on rancher HA v2.6.0-rc2 and on rancher HA upgraded from v2.4.16 to v2.6.0-rc2

1. Create a workload 
2. From the pod,view logs and exec_shell work.

**Comment by lachnerd** [comment]
Still having this exact issue with rke1 - how to resolve this or what was the solution here ?

**Comment by Sergensen** [comment]
Still having the same issue.

**Comment by bashofmann** [comment]
If this is not working, it's likely that some proxy or loadbalancer between your browser and Rancher is breaking Websockets. Does opening a shell into a container or the cluster kubectl shell work?

**Comment by sadhugit** [comment]
Opening shell works but view log is failing. if we download the log then it showing the log content
