### ISSUE TITLE
UI - Container name readability problem on container dropdown

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3406]
![image](https://cloud.githubusercontent.com/assets/2150990/12555278/b07e2e2c-c380-11e5-8e26-54ff45a9d1cc.png)

**Comment by lvuch** [comment]
Although I can guarantee all names will fit I added a fix in pr https://github.com/rancher/ui/pull/449

**Comment by rvion** [comment]
thanks :)

**Comment by tfiduccia** [comment]
I think what this guy would like is if the name doesn't fit, if you hover over it.. it will pop up the whole name like a tooltip on top of the name in the drop-down.  I've seen this before in other application. But I think this is a bigger code change that would have to be done all drop-downs and not something simple.  Vince?

**Comment by vincent99** [comment]
@lvuch Maybe we can restyle these so that they don't look as much like a dropdown, and the main part can be inline-block however much space it needs instead of being a fixed width.  I don't like how it was too short and cut off names before, but I don't like how it's now too long and empty space for short names, but still can be cut off for long ones.

**Comment by demarant** [comment]
@vincent99
I would very much be in favour of not having the dropdown. I haven't find it so useful/needed to jump from one container to another in the same host. Never use it...it shows containers from disperate stacks..
What instead I find often needed at that level is to see the other containers that belong to same service. The ability to jump fron one container to another within the same Stack. The main context from a devop point of you is the Stack, not the Host #3275

**Comment by lvuch** [comment]
@vincent99 I added your recommendation in https://github.com/rancher/ui/pull/455

**Comment by tfiduccia** [comment]
The drop-down still does not show the whole name.  So this is not fixed.

![image](https://cloud.githubusercontent.com/assets/11514927/12854822/00b3b3fa-cbf9-11e5-82ce-02cf2012eae9.png)

Please have the drop-down actually resize to the largest size need to view text.

**Comment by vincent99** [comment]
@lvuch the box on the page being auto is fine but when you click on it the popup should be whatever width it needs to to fit the content, not match the size of the clicked control. (that *might* require JS changes in ember-power-select)

**Comment by lvuch** [comment]
![screen shot 2016-02-08 at 11 20 22 am](https://cloud.githubusercontent.com/assets/3013118/12894803/279706c0-ce56-11e5-847c-cca9fa55b779.png)

**Comment by vincent99** [comment]
Didn't we do this already?

**Comment by tfiduccia** [comment]
Version - master 3/7
Verified fixed - yes, yes we did do this already
