### ISSUE TITLE
Cluster is stuck in `upgrading` state after upgrading the rke2 version for an imported rke2 cluster

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34067]
**Rancher Server Setup**
- Rancher version: v2.6.0-rc1
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1
- Proxy/Cert Details: rancher generated

**Information about the Cluster**
- Kubernetes version: v1.21.3
- Cluster Type (Local/Downstream): Downstream 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): imported rke2 cluster

**Describe the bug**
Upgrade the kubernetes version from  to `v1.21.3-rc4+rke2r2` the cluster is stuck in `upgrading` with the header `Worker node [ip-172-31-3-86.us-east-2.compute.internal] being upgraded` and won't recover from that state.

**To Reproduce**
Create an imported RKE2 cluster on rancher v2.5.9 on kubernetes `v1.20.9-rc1+rke2r2`
Upgrade the rancher server version to v2.6.0-rc1
Then upgrade the kubernetes version of the cluster to `v1.21.3+rke2r1`

**Result**
Cluster is stuck in upgrading worker node and won't recover from that state.

**Expected Result**
Cluster should have been upgraded to the new kubernetes version mentioned.

**Screenshots**
<img width="400" alt="Screen Shot 2021-08-08 at 4 45 12 PM" src="https://user-images.githubusercontent.com/38144301/128649185-8da7f802-a0fa-4e37-bd7c-6917562dec41.png">
<img width="400" alt="Screen Shot 2021-08-08 at 4 50 58 PM" src="https://user-images.githubusercontent.com/38144301/128649388-adcfa270-33d5-4a5b-b575-1102de665d9b.png">

**Additional context**
No logs are found in the above pod.

**Comment by StrongMonkey** [comment]
I think this issue is causing this bug. https://github.com/rancher/rke2/issues/1576

The fact that we marked k8s node version `v1.21.3-rc4+rke2r2` as `v1.21.3+rke2r1` will prevent rke2 upgrade from working since we simply check the node version for master roles. It will constantly fail because versions do not match and upgrade job will hang forever.

https://github.com/rancher/rke2-upgrade/blob/master/scripts/upgrade.sh#L94-L109

cc @brandond @galal-hussein

**Comment by brandond** [comment]
Should have been resolved by:
* https://github.com/rancher/rke2-upgrade/pull/9
* https://github.com/rancher/rke2-upgrade/pull/10

**Comment by StrongMonkey** [comment]
`v1.21.3-rc4+rke2r2` was actually translated to `v1.21.3-rke2r1` so I think the script failed at parsing it.

**Comment by brandond** [comment]
v1.21.3-rc4+rke2r2 translates to v1.21.3+rke2r2, the actual issue is that the RCs are still using hardened-kubernetes v1.21.3+rke2r1 so you will not see a version change when upgrading. Someone needs to update the tags and cut a new RC.

**Comment by StrongMonkey** [comment]
Duplicate issue of https://github.com/rancher/rke2/issues/1405

**Comment by brandond** [comment]
* rancher/rke2#1416
since it needs to land on the release-1.21 branch

**Comment by deniseschannon** [comment]
Available to test by upgrading to v1.21.3-rc5+rke2r2

**Comment by anupama2501** [comment]
Verified on v2.6.0-rc2, rke2 `v1.21.3-rc5+rke2r2`

- Created rancher HA server on v2.5.9 
- Imported rke2 cluster of version `v1.20.9+rke2r2`
- Upgraded the rancher server to v2.6.0-rc2
- Upgraded the rke2 cluster to `v1.21.3-rc5+rke2r2`
- Upgrade checks work as expected

**Comment by erSitzt** [comment]
@anupama2501 @StrongMonkey 

This seems to still be an issue and is there a way to recover from this ?

Rancher 2.6.6 Local Cluster ( v1.21.7+rke2r2 )

I ran into this or a similar issue when upgrading my Cluster from `v1.21.7+rke2r2`  to `v1.22.10+rke2r2`
Most nodes did work it seems, but now its stuck with two nodes left
<img width="942" alt="image" src="https://user-images.githubusercontent.com/1625376/177279618-b5e98b51-7015-4c9f-b433-c81ff17e427f.png">

With this failed job in the cluster
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/1625376/177280080-12e2acb3-9edb-47f4-87e4-035551d326f9.png">


And in the cluster view
<img width="569" alt="image" src="https://user-images.githubusercontent.com/1625376/177279758-78f63623-52e6-4812-a383-3f32f71c9a79.png">

**Comment by brandond** [comment]
Yes, please open a new issue.
