### ISSUE TITLE
[Provisioning v2] Cluster-create secret for migrated 2.5.9 RKE clusters results in failed cluster connection

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34077]
## Reproduction steps:
1. Create Rancher `2.5.9` HA setup with one local cluster
2. Create a downstream cluster with the "use existing nodes" option (RKE)
3. Create a GitRepo CR ([multi-cluster/helm](https://github.com/rancher/fleet-examples/tree/master/multi-cluster/helm) is a good choice)
4. Wait for everything to be in Active/Running states
5. Upgrade to Rancher `2.6.0-rc1` (e.g. `helm upgrade rancher rancher-latest/rancher -n cattle-system --version 2.6.0-rc1 --set hostname=<your-hostname> --set rancherImageTag=v2.6-head`)
6. Observe "Modified" Fleet Cluster state for the downstream cluster as well as other failures caused by the `fleet-controller` being unable to communicate with the downstream cluster

## Workaround steps:
1. Delete old secret
2. Modify an arbitrary field of the downstream RKE cluster in the Ember UI
3. A new secret is created, and the `fleet-controller` will use this new secret (automatically); restoring connection with the downstream cluster

## Notes
- The `fleet-controller` logs its connection failure here with a connection test: https://github.com/rancher/fleet/blob/c09ee3a074e82d4e9da72a6c4bf5ad07d54c395e/pkg/controllers/cluster/import.go#L181-L183
- Interestingly, the `data.token` field is not consumed in the above cluster import code, but it is for cluster authorization when there's a change in the Fleet cluster: https://github.com/rancher/fleet/blob/ef891e96de47a27259dcba1ba3c6640d189c6d22/pkg/controllers/clusterregistration/controller.go#L157
- Moreover, _new_ RKE1 clusters with "use existing nodes" selected do not face the same issue; this only affects clusters created before upgrade

## Secret Before Workaround (was created after upgrade)

The `data.token` field does not exist. However, it did not exist in 2.5.9 as well. This is likely a red herring, and the issue likely happens in the `data.value` field.

```yaml
apiVersion: v1
data:
  value: <kubeconfig>
kind: Secret
metadata:
  annotations:
    field.cattle.io/projectId: local:p-9rrcw
    objectset.rio.cattle.io/applied: <snip>
    objectset.rio.cattle.io/id: cluster-create
    objectset.rio.cattle.io/owner-gvk: provisioning.cattle.io/v1, Kind=Cluster
    objectset.rio.cattle.io/owner-name: c-s9wrz
    objectset.rio.cattle.io/owner-namespace: fleet-default
  creationTimestamp: "2021-08-07T04:32:55Z"
  labels:
    objectset.rio.cattle.io/hash: <snip>
  name: c-s9wrz-kubeconfig
  namespace: fleet-default
  resourceVersion: "8830"
  uid: 6969de94-e02f-4f96-9545-658ff679b706
type: Opaque
```

## Secret After Workaround

The `data.token` field now exists, and the `data.value` field has been modified (among other fields).

```yaml
apiVersion: v1
data:
  token: <token>
  value: <kubeconfig-which-has-changed-with-new-token>
kind: Secret
metadata:
  annotations:
    objectset.rio.cattle.io/applied: <snip>
    objectset.rio.cattle.io/id: cluster-create
    objectset.rio.cattle.io/owner-gvk: provisioning.cattle.io/v1, Kind=Cluster
    objectset.rio.cattle.io/owner-name: c-s9wrz
    objectset.rio.cattle.io/owner-namespace: fleet-default
  creationTimestamp: "2021-08-07T04:58:14Z"
  labels:
    objectset.rio.cattle.io/hash: <snip>
  name: c-s9wrz-kubeconfig
  namespace: fleet-default
  resourceVersion: "13518"
  uid: 45935248-0ee5-49fd-837a-4ca968706244
type: Opaque
```

### Local

- k3s w/ k8s v1.20.9
- HA install
- Digital Ocean droplet 2c8g

### Downstream

- RKE w/ k8s v1.20.9
- Digital Ocean droplet 2c8g

**Comment by sowmyav27** [comment]
Blocked by https://github.com/rancher/fleet/issues/490

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to v2.6-head commit id: `c10ef4b0`**

- On 2.5.9 deploy a couple of downstream cluster
- In Continuous Delivery Deploy a Git repo
- It comes Up active and clusters in Active state
- On a rancher upgrade, New Fleet agent is deployed in `cattle-fleet-system` namespace, and the old one is deleted but the `fleet-system` namespace is still available.
- Existing clusters in Continuous delivery tab are Active. Able to deploy new bundles to the downstream clusters.
- Fleet version: `v0.3.6-rc12`
- Before Upgrade on 2.5.9
```
kubectl get --watch secrets -A | grep kubeconfig
fleet-default                                c-csfjx-kubeconfig                                                Opaque                                        1      143m
fleet-default                                c-lnvdc-kubeconfig                                                Opaque                                        1      27m
```
- After Upgrade on 2.6-head:
```
fleet-default                                c-csfjx-kubeconfig                                                Opaque                                        2      46s
fleet-default                                c-lnvdc-kubeconfig                                                Opaque                                        2      53s
fleet-local                                  local-kubeconfig                                                  Opaque                                        2      2m46s
```
The secrets are recreated.
