### ISSUE TITLE
Unable to upgrade EKSv1 cluster on upgrade from v2.4 to v2.6

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#34072]
**Rancher Server Setup**
- Rancher version: v2.4.16 upgrade to v2.6.0-rc1
- Installation option (Docker install/Helm Chart): HA helm

**Information about the Cluster**
- Kubernetes version: v1.18
- Cluster Type (Local/Downstream): EKS

**Describe the bug**

Unable to upgrade EKSv1 cluster after Rancher upgrade from v2.4 to v2.6

**To Reproduce**
 
Bring up Rancher v2.4.16
Provision an EKSv1 cluster. k8s version v1.18
After cluster becomes available, upgrade Rancher to v2.6.0-rc1
Upgrade the EKS cluster to k8s version v1.19

**Result**
Cluster becomes stuck in error state. Errors with `Default ami of region us-east-2 for kubernetes version 1.19 is not set`
![Screen Shot 2021-08-08 at 4 14 11 PM](https://user-images.githubusercontent.com/57409052/128672967-92d7e47b-a7ab-40c4-a35f-5bf8a2df29b3.png)

**Expected Result**

User should be able to upgrade k8s version of an EKSv1 cluster.

**Comment by thedadams** [comment]
I am block now because I don't have access to the China regions of AWS. Once I am able to update the AMIs for these regions, I will be ready for a PR.

**Comment by aaronRancher** [comment]
Tested on Rancher `v2.6-head` `version 6cb1847` and `master-head` `version c58f952` with the following steps:
- Bring up Rancher v2.4.16
- Provision an EKSv1 cluster. k8s version v1.18
- After cluster becomes available, upgrade Rancher
- Upgrade the EKS cluster to k8s version v1.19

Result:
Cluster is upgraded to v1.19 successfully.
![Screen Shot 2021-08-11 at 5 20 14 PM](https://user-images.githubusercontent.com/57409052/129119849-6589b841-604e-4853-97ec-f904a1ef2258.png)
