### ISSUE TITLE
Standard User - Cannot create cluster successfully summary

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#34089]
**Rancher Server Setup**
- Rancher version: `v2.6-head` `version 4b6af95`
- Installation option (Docker install/Helm Chart): Single docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.3-rc4+rke2r2`
- Cluster Type (Local/Downstream): DO downstream cluster

**Describe the bug**

UI errors during RKEv2 cluster provisioning.

**To Reproduce**
 
- On Rancher `v2.6-head` `version 4b6af95`
- Log in as standard user or restricted admin.
- Provision a 1 node DO RKEv2 cluster

**Result**
- UI errors with: `Failed while: mgmt cluster create`
![Screen Shot 2021-08-09 at 10 11 36 AM](https://user-images.githubusercontent.com/57409052/128763852-36838525-490f-4c70-85c4-2e8d55b62b11.png)
- Error in Rancher logs:
```
- 2021/08/09 18:27:26 [INFO] Failed to find providerID for selector rke.cattle.io/machine=5e0f718a-e4e4-4146-b267-5367f1cf5b36 in cluster fleet-default/sowmya, machine sowmya-pool1-7f96567bf4-vwgzx: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-ea894a0c\" is forbidden: User \"u-vwvm5z7lix\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
```

- If the user selects Create again, the UI will error with `Method PUT not supported`
![Screen Shot 2021-08-09 at 10 11 40 AM](https://user-images.githubusercontent.com/57409052/128763840-25389059-6dc7-4836-b882-8f8ff7f6c66b.png)
- Error from dev console:
```
code: "PermissionDenied"
links: {}
message: "Method PUT not supported"
status: 403
type: "error"
```
- The cluster is still created in Rancher and comes up active.
- This issue is not seen as admin on `v2.6-head` `version 4b6af95`

**Expected Result**

Cluster create should not error in the UI.

**Additional context**
Related issue: https://github.com/rancher/rancher/issues/32414

**Comment by deniseschannon** [comment]
v2.6-head
8/11-5pm

UI fixes were added to watch for the correct change event to allow this workflow to succeed.
