### ISSUE TITLE
Validate storage drivers on service creation.

### ISSUE THREAD

**Issue by dopry** [rancher/rancher#3409]
I was setting up a service with a convoy.gluster storage driver. I use 'convoy' instead of the storage pool name.  I had to wait for some relatively long timeout period and after some poking at containers and images I finally found the message that the storage driver was unabel to be found. While reading the docs more closely would have probably solve my problems. It would have also been nice to have the storage driver validated and been told that there was no storage driver named 'convoy' and provide a list of available storage drivers.

**Comment by will-chan** [comment]
Obsolete.  We don't support ConvoyNFS anymore.
