### ISSUE TITLE
Windows Installation command isn't installing the correct version of RKE2, it installs the latest stable channel.

### ISSUE THREAD

**Issue by phillipsj** [rancher/rancher#34094]
**Rancher Server Setup**
- Rancher version: 2.6-head
- Installation option (Docker install/Helm Chart): docker 

**Information about the Cluster**
- Kubernetes version: 121.3
- Cluster Type (Local/Downstream):
* RKE2 Custom Cluster

**Describe the bug**

The windows RKE2 installer for Rancher isn't receiving the version of RKE2 to install. By default it will install the latest stable channel release if no version is provided.

**To Reproduce**

Create a new RKE2 custom cluster with a 1.21.4 RC version and add Windows node.

**Result**

Running rke2.exe --version should report 1.21.3-rc4+rke2r2

**Expected Result**

The version report 1.21.3-rke2r1

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by Jono-SUSE-Rancher** [comment]
Should be ready to test via https://github.com/rancher/rke2/issues/1530

**Comment by phillipsj** [comment]
@Jono-SUSE-Rancher here is the related RKE2 issue. https://github.com/rancher/rke2/issues/1577

**Comment by slickwarren** [comment]
on 2.6-head (4def656):
rke2 appears to be on the correct version, and can begin the registration process with rancher `rke2.exe version v1.21.3-rc5+rke2r2`
