### ISSUE TITLE
RKE2 - Unable to provision ec2 clusters - cannot reproduce

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#34101]
**PLEASE NOTE: I have not been able to reproduce this issue yet, I have only seen it on one rancher server. I have the environment up as of 8/9/21 if a dev wants to take a look.**

**Rancher Server Setup**
- Rancher version: v2.6-head 4b6af95d7 8/9/21 8:46 am Pacific
- Installation option (Docker install/Helm Chart):
Single-node docker container

Downstream cluster: rke2
Downstream cluster k8s version: v1.21.3-rc4+rke2r2

**Describe the bug**
I haven't been able to reproduce this issue yet.
Upon attempting to create any aws rke2 cluster, rancher will get the cluster stuck in a Provisioning state. We can see some of my clusters are affected by this issue:
![image](https://user-images.githubusercontent.com/45179589/128783361-83082a09-79a3-45f6-ad74-ec1d99fc03fb.png)

A few of these clusters work now. After about 30-60 minutes I'm able to provision aws rke2 clusters again.
There was no change in form submission when creating these clusters, each aws cluster was created in us-east-2 region with the following changes:
- set a name for the cluster (required)
- pick an instance type of t3.xlarge
- pick a subnet in QA AWS, first subnet in list (first vpc)
- Leave everything else as defaults:
![image](https://user-images.githubusercontent.com/45179589/128783532-7606042a-b7ef-4cfc-807d-0ff21bca62b2.png)

**To Reproduce**
0. If you haven't yet create your aws cloud credential. Mine was for the us-east-2 region.
1. Create a simple 1-node AWS cluster with rke2 provisioning in Rancher (specified above)t. 
2. Wait and watch. The cluster will not provision.

**Result**
The cluster will never finish provisioning. The ec2 instance is indeed created in the region and the ec2 instance appears ready, but the cluster will stay in the "Provisioning" state. I didn't identify anything in the rancher server logs. I also was able to provsion clusters again (successfully though) after about 30-60 minutes. I suspect I had some strange environmental issue with my rancher server container or something. Sowmya and I could not identify the cause.

**Expected Result**
Should be able to provision aws clusters at any time without any issues; should not stay stuck in Provisioning state.

**Additional context**
Cluster YAML:
(Attached as ~cluster.yaml~ cluster.txt [since GitHub is so picky])
[cluster.txt](https://github.com/rancher/rancher/files/6957632/cluster.txt)

I diffed the json POST request sent to create the cluster and fleet POST - they are no different between the clusters that failed to finish provisioning and the ones that did work.

Redacted rancher server logs are also attached here, but unfortunately they are quite noisy from all the testing done.
[redacted_rancher_server_logs.txt](https://github.com/rancher/rancher/files/6957829/redacted_rancher_server_logs.txt)

**Comment by snasovich** [comment]
This is likely addressed since there were a lot of changes in RKE2 provisioning between August and now. Suggesting to keep it in "To Test" and watch for it reproduced while testing 2.6.4 builds.

**Comment by davidnuzik** [comment]
v2.6-head (various builds)

I have NOT been able to reproduce this after many RKE2 clusters (mostly ec2 node driver) were created by me. Should I encounter this issue again I can reopen the issue.
