### ISSUE TITLE
Scaling Down from Machine Pools page removes the machine and kube node from the cluster but the DO droplet is not removed

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34109]
**If this is a UI issue, please file an issue at https://github.com/rancher/dashboard/**

**Rancher Server Setup**
- Rancher version: v2.6-head 4b6af95

**Information about the Cluster**
- Kubernetes version: v1.23.3-rc4+rke2r2
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2 provisioned by DO

**Describe the bug**

Scaled down my machine pool to have less machines, but the machine in DO is not removed. 

**To Reproduce**
 
1. Create a cluster with multiple machine pools (3) and each pool has 3 machines. The 2 additional machine pools are worker only machine pools
2. After the cluster is up and running, scale down from the Cluster Management-> Machine Pools page by selecting the `-` button in the machine pool section. 

**Result**
UI shows that the machine and kube node are no longer part of the cluster. 
BUT the DO droplet is still running in DO. 

**Expected Result**

DO droplet should be removed as well

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by thedadams** [comment]
This seems to be working as expected now. I was able to scale worker nodes up and down.

**Comment by izaac** [comment]
Rancher version: `v2.6-head (08/13/2021)` _4def656_
local cluster k8s: RKE1 `v1.21.3`
Downstream clusters RKE2 kubernetes:  `v1.21.3-rc5+rke2r2`


I was able to reduce scale and observe the nodes deleted on DO cloud with these configurations:

Configuration `#1`
- etcd/control plane - 3 nodes
- worker - 3 nodes
- worker - 3 nodes

Configuration `#2`
- etcd - 3 nodes
- control plane - 3 nodes
- worker - 3 nodes
