### ISSUE TITLE
Validation or notices for required labels.

### ISSUE THREAD

**Issue by dopry** [rancher/rancher#3410]
When first setting up a convoy-gluster storage pool, I didn't setup the host labels. I was getting all sorts of timeouts and errors deploying my service. I could see hosts in my storage pools, but couldn't create volumes... After an hour or so I figured out I was missing the host labels. If a service requires certain labels that aren't present, it would be nice if there service were shown as degraded and there was a notice about the missing labels with a suggestion of what labels to add and a link to add them.

**Comment by dopry** [comment]
Note, I ran into another person in IRC with a similar problem, but it was because the labels in the docs [do/did](https://github.com/rancher/rancher.github.io/pull/178) not match the defaults in the convoy-gluster stack.  If there were some form of validation he could have been helped inline.

**Comment by deniseschannon** [comment]
This will be fixed with this issue. Basically, we're removing the host label requirements. 

https://github.com/rancher/rancher/issues/3068

**Comment by dopry** [comment]
I was using convoy-gluster as an example. The general idea of some sort of validation or notice regarding services that cannot be started is applicable to any service with label/scheduling requirements.

**Comment by deniseschannon** [comment]
If it can't find anything it will say "Failed to find a placement".

**Comment by dopry** [comment]
I didn't get that message with the convoy gluster stack when I hadn't set
the labels. Where should I have seen it?

On Mon, Jan 25, 2016 at 4:02 PM, Denise <notifications@github.com> wrote:

> If it can't find anything it will say "Failed to find a placement".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rancher/rancher/issues/3410#issuecomment-174661801>.
>



-- 
Darrel O'Pry
The Spry Group, LLC.
http://www.spry-group.com
718-355-9767 x101

**Comment by dopry** [comment]
Here are screen shots from an environment with out the host labels set.

![image](https://cloud.githubusercontent.com/assets/387640/12565194/61de6fec-c381-11e5-871d-ee45e37eb8e0.png)

![image](https://cloud.githubusercontent.com/assets/387640/12565208/71092da4-c381-11e5-90ac-f28499821b31.png)

![image](https://cloud.githubusercontent.com/assets/387640/12565241/9c6604f4-c381-11e5-9a8b-8895313f4e92.png)

As you can see from a visual perspective in the UI every thing looks like it's fine. There is no warning that my stack might not be functioning properly. 

However if I look at the hosts I can tell it's not running. 

![image](https://cloud.githubusercontent.com/assets/387640/12565293/e36e1a62-c381-11e5-81aa-36fb14f04c4d.png)

It seems like in the case of a global scale service, if there are no containers running there should be some sort of notice that the service isn't properly working.

**Comment by deniseschannon** [comment]
Correct, with a global scale there is notice for us to really show. We try to make it more obvious by having the number of containers displayed for a stack and on the host, which containers belong to which host. 

There are other use cases where someone might set up all their services and add in hosts later, so there's no real "notice" to display.

**Comment by vincent99** [comment]
Showing healthy/active on a global service with 0 containers seems indeed unhelpful.. will change to require at least 1.

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/12593897/98fcf46c-c430-11e5-868f-bfa547661c6d.png)
