### ISSUE TITLE
DNS resolution for services fails from lb containers

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3411]
Server version - V0.51.0

Steps to reproduce the problem:
Create a LB service - "lb-1" with target service -"test1" and activate it.
Log in to LB service container and try to ping lb-1 or test1.
DNS resolution fails.

/etc/resolv.conf points to 8.8.8.8

<img width="598" alt="screen shot 2016-01-25 at 10 15 20 am" src="https://cloud.githubusercontent.com/assets/4266958/12559915/a7faa37c-c34c-11e5-9bd6-3a39858d87a1.png">

DNS resolution should work from LB service containers.

**Comment by alena1108** [comment]
internal lb is not using internal dns as of now, so cleaned up the milestone

**Comment by alena1108** [comment]
closing till the need for dns resolution for lb containers is required.
