### ISSUE TITLE
RBAC not honored for nested groups of auth when added as cluster owners/memebers

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34142]
**Rancher Server Setup**
- Rancher version: v2.6-head 723f747
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Cluster Type (Local/Downstream): Downstream node driver rke2 1 node all roles DO

**Describe the bug**
When nested group members are added as the cluster owners in the clusters, cluster is not listed in the `cluster management` page. This is seen if the nested group has a parent as well as a child.

**To Reproduce**
Inheritance of the groups is as follows:
```
group1: 
    group2 [child of group1]
        user1 [member of group2]
```

- Enable LDAP auth providers from Users and auth --> Authentication
- Create downstream rke2 node driver clusters - cluster 1 
- Add group2 in the cluster1 as cluster owner

**Result**
- when logged in as `user1`, cluster1 is not listed in `cluster management` page but listed in `explore cluster` page.

**Expected Result**
user1 - `cluster1` should be listed in `cluster management` page

Ref issue: https://github.com/rancher/dashboard/issues/3643

**Comment by izaac** [comment]
Using the naming in this issue:

`group1(group2(group3))`

With `group2` added as cluster owner then `user1` should be able to see and edit the `cluster1`.
With `group3` added as cluster owner then `user2` should see and edit both `cluster1` and `cluster2`  (inheriting RBAC access from `group2` for `cluster1`  and direct access with `group3` on `cluter2`)

**Comment by anupama2501** [comment]
https://github.com/rancher/rancher/issues/34266 
Update: Edited the ticket to track two issues referenced in the ticket separately.

**Comment by anupama2501** [comment]
Closing this issue as it is not seen anymore on the v2.6-head
