### ISSUE TITLE
[v2.5.10] Backport: Warnings "will not create impersonation account on cluster" seen on rancher startup

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#34140]
Issue: https://github.com/rancher/rancher/issues/34076

**Comment by sowmyav27** [comment]
Moving it to Review as the linked PR is not merged yet

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.5-head `b2f17e430` pulled 9/9/21 11:20am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE1 Digital Ocean (rancher node driver)
Downstream K8s version: v1.20.10-racher1-1
 
**Validation steps:**

1. Deploy rancher. Log in and set password.
2. Deploy a 1-node DigitalOcean cluster as Admin.
3. No errors are seen in the rancher server logs like indicated in the [original issue](https://github.com/rancher/rancher/issues/34076).
