### ISSUE TITLE
rancher/fleet-agent does not seem to be updated to use private registry image in Rancher 2.6.0-rc1

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#34143]
As part of testing https://github.com/rancher/rancher/issues/30628, I observed that the rancher/fleet-agent image does not seem to be updated when switching a cluster to using a private registry.

Details on the setup can be found in the original ticket and the relevant screenshot can be found [here](https://github.com/rancher/rancher/issues/30628#issuecomment-896331948) as well:

![147 182 249 14_p_c-zb2d8_p-85sww_workloads (1)](https://user-images.githubusercontent.com/13127443/128938646-dd7bb6b4-8e40-446e-ae69-e23b73fa9896.png)

Steps to Reproduce found in https://github.com/rancher/rancher/issues/30628#issuecomment-895629303.

**Comment by aiyengar2** [comment]
cc: @Jono-SUSE-Rancher not sure if this should be 2.6.0 or 2.6.1/2.6.2

**Comment by Jono-SUSE-Rancher** [comment]
@aiyengar2 - We are actually attempting to resolve quite a few upgrade related issues, specifically for 2.6, but I would have to double check the schedule and update it accordingly. For now I'll add the correct label.

**Comment by StrongMonkey** [comment]
Fleet-agent doesn't respect cluster private registry setting at this moment, it only respects system-default-registry which is global setting.

**Comment by deniseschannon** [comment]
This is expected behavior for the fleet agent cause the fleet agent is considered a global resource and is defined at the system-default-registry setting as ALL fleet agents across all clusters would need to come from the same private registry.
