### ISSUE TITLE
[v2.5.10] Backport: Not able to deploy clusters when external auth provider is enabled

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#34141]
Issue: https://github.com/rancher/rancher/issues/34042

**Comment by sowmyav27** [comment]
Reopening this as the main issue was reopened  - https://github.com/rancher/rancher/issues/34042#issuecomment-897225585

**Comment by cmurphy** [comment]
I think this can be closed, the linked issue was closed in https://github.com/rancher/rancher/issues/34042#issuecomment-900351458. I opened a different backport issue https://github.com/rancher/rancher/issues/34454 for the related impersonation issue.

**Comment by snasovich** [comment]
@sowmyav27 , please close the issue if you're OK with it as per the comment above.

**Comment by sowmyav27** [comment]
@snasovich @cmurphy Are these both the same issues? As it was logged separately in 2.6

**Comment by cmurphy** [comment]
@sowmyav27 I'm just suggesting that this backport issue could be closed for the same reason the main issue #34042 was closed, if it's no longer reproducible.

**Comment by snasovich** [comment]
@sowmyav27 , right. Following the same process as we did for 2.6, we could test it in https://github.com/rancher/rancher/issues/34454 (once it's up for testing). We could have this one remain in To Test until the referenced issue is validated too.

**Comment by anupama2501** [comment]
Verified on v2.5.9 upgraded to `v2.5-47e2c3e7324fb74c643ec877db0272ab500b5097-head`

1. Enabled openLDAP auth in the rancher server
2. Created clusters - imported k3s version `v1.19.14+k3s1`, windows 2004 
3. Installed monitoring v2 in the k3 cluster
4. Upgraded the rancher server - verified no errors seen in the clusters
5. created k3s `v1.19.14+k3s1` and windows 2004 on the upgraded setup and no errors seen - clusters have come up active.
