### ISSUE TITLE
RKE2 - Standard user is unable to edit the cluster config in the UI

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#34145]
**Summary:**
Vue UI

A standard user can create an rke2 cluster, but is not able to edit the cluster config. An error is shown in the browser dev console:
![image](https://user-images.githubusercontent.com/45179589/128944429-a5af764a-338b-4f5f-ba93-311be261acee.png)
And we get a 403 forbidden http error when try to get machine config /v1/rke-machine-config.cattle.io.digitaloceanconfigs/fleet-default/nc-dave-std-user-created-pool1-jh5nn with a response like:
```
{
	"type": "error",
	"links": {},
	"code": "PermissionDenied",
	"message": "Method GET not supported",
	"status": 403
}
```

**Environment:**
Rancher version: v2.6.0-rc2 (8/10/21)
Rancher cluster type: single-node docker
Docker version: 19.03
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3-rc4+rke2r2

**Reproduction Steps:**
1. Create a standard user, use all the defaults. Log in as this user.
2. Create an rke2 cluster, it should not matter, but in my case I created a 1-node DigitalOcean cluster.
3. Edit the cluster conig

**Result:**
The above steps will result in the UI just showing a "Loading..." text forever. Looking in the browser dev console we got a 403 http error and a TypeError in the console. Refer to the Summary above for details including screenshots. There is nothing in the rancher server logs (at least on INFO level).

**Additional Info:**
I do NOT have this issue with rke1 clusters created in the Vue UI.

**Comment by deniseschannon** [comment]
v2.6-head 6cb1847

Due to this issue, you weren't able to edit the config: 
https://github.com/rancher/rancher/issues/34158

With that issue resolved, I am now able to edit the config of the cluster. 

Note: These were UI fixes introduced after v2.6.0-rc2
