### ISSUE TITLE
Rke2 clusters are not coming up active and stuck in `provisioning` after upgrade from Rancher 2.4

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34151]
**Rancher Server Setup after upgrade**
- Rancher version: `v2.6.0-rc2 `
- Installation option (Docker install/Helm Chart): Helm
- Kubernetes version of local cluster: `v1.18.20`

**Before upgrade**
- Rancher version: `v2.4.16`
- Kubernetes version of local cluster: `v1.18.20`

**Information about the Cluster**
- Kubernetes version: `v1.21.3-rc4+rke2r2`
- Cluster Type (Local/Downstream): Downstream infrastructure provider DO/AWS
   

**Describe the bug**
Rke2 clusters are not coming up active and stuck in `provisioning`

**To Reproduce**
1. Start Rancher v2.4.16
2. Upgrade to Rancher v2.6.0-rc2
3. Create rke2 node driver cluster either DO/AWS 1 node all roles

**Result**
Cluster is stuck in provisioning and won't recover

**Expected Result**
Clusters should be provisioned and come up active.

**Screenshots**
<img width="400" alt="Screen Shot 2021-08-10 at 6 40 37 PM" src="https://user-images.githubusercontent.com/38144301/128956709-e8c2a199-988d-4dbf-9b5f-ff006d2b10a0.png">

**Additional context**
Seen only on upgraded setup `[upgraded from v2.4.16 to v2.6.0-rc2]`

Some errors in the rancher pod logs:

```

2021/08/11 01:27:07 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
--
Tue, Aug 10 2021 6:27:07 pm | W0811 01:27:07.784039 32 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Namespace ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Tue, Aug 10 2021 6:27:07 pm | W0811 01:27:07.784088 32 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Pod ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Tue, Aug 10 2021 6:27:07 pm | W0811 01:27:07.784098 32 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.RoleBinding ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Tue, Aug 10 2021 6:27:07 pm | W0811 01:27:07.784121 32 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Endpoints ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Tue, Aug 10 2021 6:27:07 pm | W0811 01:27:07.784129 32 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.ClusterRoleBinding ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Tue, Aug 10 2021 6:27:07 pm | W0811 01:27:07.784207 32 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.APIService ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Tue, Aug 10 2021 6:27:07 pm | W0811 01:27:07.784227 32 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Service ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Tue, Aug 10 2021 6:27:07 pm | W0811 01:27:07.784397 32 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.ServiceAccount ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Tue, Aug 10 2021 6:27:07 pm | W0811 01:27:07.784535 32 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Secret ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Tue, Aug 10 2021 6:27:07 pm | W0811 01:27:07.784703 32 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Role ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Tue, Aug 10 2021 6:27:07 pm | W0811 01:27:07.784757 32 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.ClusterRole ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding


```

**Comment by anupama2501** [comment]
Update: One of the clusters is active in the `explore cluster` page and are stuck in `provisioning` in cluster management page. 
<img width="400" alt="Screen Shot 2021-08-10 at 7 37 25 PM" src="https://user-images.githubusercontent.com/38144301/128961097-13568fa8-19e4-4f99-8b30-dc9cb5adb598.png">

**Comment by deniseschannon** [comment]
Honestly, I think cause you had the websocket issue, nothing in the UI is going to end up showing up correctly. 

I'm able to bring up the latest v2.6-head 6cb1847 and provision a RKE2 cluster. 

I doubt you will be able to repro this. @anupama2501 @kinarashah

**Comment by StrongMonkey** [comment]
I am getting the exact same error when provisioning DO cluster in rke2. Custom node doesn't seem to have this problem.

**Comment by StrongMonkey** [comment]
The fact that websocket is having the issue is the reason cluster-agent is not ready....

**Comment by anupama2501** [comment]
@deniseschannon  upgraded from `v2.4.16` to `v2.6.0-rc2`

**Comment by deniseschannon** [comment]
@anupama2501 Sorry, I meant what k8s version is Rancher installed on? When you installed Rancher v2.14, what is the k8s version that's installed?

**Comment by anupama2501** [comment]
@deniseschannon k8s version is `v1.18.20`, updated the details in the ticket.

**Comment by anupama2501** [comment]
Verified by upgrading to `v2.6.0-rc4` from `v2.4.16`
k8s:  `v1.18.20`

1. Created a cluster on the 2416 version of rancher. 
2. Upgraded the helm chart to v2.6.0-rc4
3. Created two downstream rke2 and rke1 node driver clusters - AWS and DO
4. clusters are created without any errors.

Closing this issue. will open it if seen in future.
