### ISSUE TITLE
Connectivity between coreOS hosts broken with V0.56.0.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3416]
Server version - V0.56.0

Set up - rancher server and 2 hosts are coreOS - stable (835.11.0)  VMs.

Start a service with scale 2 which results in 1 container being 

Not able to ping between containers in 2 different host using its managed ip address.

**Comment by sshipway** [comment]
This also affects CoreOS 928.0.0 and 935.0.0 (with Docker 1.9.1)

**Comment by qrpike** [comment]
Having same issues using Beta channel. (CoreOS 899.5.0) with Docker 1.9.1

**Comment by qrpike** [comment]
@sangeethah Any idea of an ETA on this? Currently broken until this gets patched :/

**Comment by deniseschannon** [comment]
Verified with v0.56.1-rc2 and CoreOS Beta (Docker 1.9.1). We have release v0.56.1 and tagged as latest.

**Comment by sshipway** [comment]
Tested here; 0.56.1 fixed the problem for us.  Thanks for the fast response!

**Comment by qrpike** [comment]
Fixed the issue for me also. Thanks guys!
