### ISSUE TITLE
Unable to apply Pod Security Policies to a Project

### ISSUE THREAD

**Issue by stevet284** [rancher/rancher#34162]
Hi , we are running Rancher V2.5.8 - rancher running from a docker container
We have an RKE cluster built via the Rancher UI.

I have configured a custom Pod Security Policy, but I cannot apply it to a project.
As per the documentation I am looking in Projects/Namespaces , then edit a project.

The only thing I can change is:
   Default resource limits
   Labels

This is an issue, because if I cant apply the policy then I cant let developers create deployments as they could create privileged containers , running as root e.t.c.

Many thanks in advance
Steve

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.8` UI: `v2.5.8` |
|Route|`undefined`|

**Comment by deniseschannon** [comment]
Did you set a PSP at the cluster configuration? A default PSP must be set when creating the cluster in order to enable the PSP admission controller. Please review the pre-requisites: 
https://rancher.com/docs/rancher/v2.5/en/project-admin/pod-security-policies/

**Comment by stevet284** [comment]
Thanks Denise,  yes that is the issue, I didn't set the PSP when I created the cluster.
Actually I have just managed to set the PSP to restricted by editing the cluster using "edit YAML"

It was just case of adding:  default_pod_security_policy_template_id: restricted
  at the top and then:

kube-api:
  pod_security_policy:  true

after applying the above I was then able to edit the cluster and set the policy to be restricted and it is being enforced when I create new workloads.

Please close this issue.
Thanks
Steve

**Comment by stevet284** [comment]
all sorted
