### ISSUE TITLE
500 error in /v3/kontainerdrivers/rancher-images in air-gapped setups only with useBundledSystemChart=true

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#34172]
**Rancher Server Setup**
- Rancher version: master-head `9d2e08674b9318e440fb6396c6e168a9c9bdca91`

**Describe the bug**

In an air-gapped setup that uses `useBundledSystemChart` (which means the `SystemCatalog` setting is set to `bundled`), the catalog image-list does not exist, resulting in a 500 error with the following logs on trying to hit `/v3/kontainerdrivers/rancher-images`:

```
[ERROR] API error response 500 for GET /v3/kontainerdrivers/rancher-images. Cause: configmaps "cattle-system/system-library-catalog-image-list" not found
```

**To Reproduce**
 

1. Do a Helm chart install of rancher setting useBundledSystemChart to true. Check if the setting for SystemCatalog was set to bundled
2. Try navigating to RANCHER_URL/v3/kontainerdrivers/rancher-images.

**Result**

500 error

**Expected Result**

System charts should come up

**Screenshots**

**Additional context**

This is not the same as https://github.com/rancher/rancher/issues/31336.

The above issue switched Rancher to storing the list of images from rancher/system-charts in a ConfigMap instead of just storing it in management-state/ to resolve an issue where a non-leader Rancher pod did not have access to the repositories to grab the list of images from, as noted in https://github.com/rancher/rancher/issues/31336#issuecomment-785256694.

This is an issue that affects air-gapped clusters regardless of whether or not a ConfigMap is used. However, as a result, backporting this fix will either involve backporting the fix from https://github.com/rancher/rancher/issues/31336 as well or designing a slightly modified solution for Rancher 2.5 and before.

Also, the proposed solution for this issue would be to check if the SystemCatalog is bundled on startup and, if so, use the system-charts [copied into /var/lib/rancher-data/local-catalogs/system-library as part of building the Docker image](https://github.com/rancher/rancher/blob/522c7764153e4cfee6161895ae44efaa59d611d9/package/Dockerfile#L53) in order to generate the ConfigMap.

**Comment by anupama2501** [comment]
reproduced on v2.6.0-rc2

**helm template:**
```
helm template rancher ./rancher-2.6.0-rc2.tgz --output-dir . --namespace cattle-system --set hostname=hostname --set rancherImage=registry_hostname/rancher/rancher --set systemDefaultRegistry=registry_hostname.qa.rancher.space --set useBundledSystemChart=true --set ingress.tls.source=secret --set rancherImageTag=v2.6.0-rc2
```

**Steps:**

1. From rancher pods, exec into the shell and run the command `curl -u <cattle_accesskey>:<cattle_secretkey> --insecure 'https://podip:443/v3/kontainerdrivers/rancher-images'` 
2. All the pods throw `{"baseType":"error","code":"ServerError","message":"failed to get image list for system catalog","status":500,"type":"error"}` error

**Rancher pods logs:**
 `2021/08/12 15:25:55 [ERROR] API error response 500 for GET /v3/kontainerdrivers/rancher-images. Cause: configmaps "cattle-system/system-library-catalog-image-list" not found`

Can also be reproduced by navigating to `https://url/v3/kontainerdrivers/rancher-images` - which throws the error `{"baseType":"error","code":"ServerError","message":"failed to get image list for system catalog","status":500,"type":"error"}`

**Comment by aiyengar2** [comment]
### Note for QA:

In all scenarios, ensure that after logging in, no 500 results from `/v3/kontainerdriver/rancher-images`.

Here are my suggested scenarios based on the code that was modified (not sure if all are required):

### Ensure there is no regression for normal Rancher
- [ ] Docker Install: Fresh install of Rancher 2.6.0 
- [ ] Docker Install: Upgrade of Rancher 2.5.9 -> 2.6.0
- [ ] Helm install: Fresh install of Rancher 2.6.0
- [ ] Helm install: Upgrade of Rancher 2.5.9 -> 2.6.0

### Ensure there is no regression for normal Rancher
- [ ] Docker Install: Fresh install of Rancher 2.6.0 **with** `-e CATTLE_SYSTEM_CATALOG=bundled`
  - Note: I tested this while developing
- [ ] Docker Install: Upgrade of Rancher 2.5.9 -> 2.6.0 **with** `-e CATTLE_SYSTEM_CATALOG=bundled` (in both runs)
  - Note: I tested this while developing
- [ ] Helm install: Fresh install of Rancher 2.6.0 **with** `--set useBundledSystemChart=true`
- [ ] Helm install: Upgrade of Rancher 2.5.9 -> 2.6.0 **with** `--set useBundledSystemChart=true` (in both runs)

**Comment by izaac** [comment]
Reproduced on `v2.5.9` on Single node HA

Validated fresh install of `v2.6.0-rc4` Airgap HA, I am able to access the url path and retrieve the `rancher-images.txt`
I also checked `rancher-windows-images`

I will do the remaining Docker and HA install and upgrade paths.

**Comment by izaac** [comment]
Upgrades from `v2.5.9` to `v2.6.0-rc4`

- Airgap HA, 500 hitting the endpoint on `v2.5.9`. The endpoint worked after upgrade to `v2.6.0-rc4`
- Airgap Single Docker , 500 hitting the endpoint on `v2.5.9`. The endpoint worked after upgrade to `v2.6.0-rc4`

Extra: I checked `rancher-windows-images` too.
