### ISSUE TITLE
Restricted Admin needs access to new cluster CRDs

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34185]
**Rancher Server Setup**
- Rancher version: v2.6-head `6cb1847`
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Describe the bug**

Restricted admins can see downstream clusters on the home page, but unable to see any clusters on the cluster management page. 

Based on convo with @vincent99 

**To Reproduce**
 
1. Login as standard user
2. Create a cluster
3. Login as restricted admin.
4. Able to see downstream cluster on home page
5. Go to Cluster Management page

**Result**

Unable to see downstream cluster

**Expected Result**

Able to see all downstream clusters (even if I'm not assigned any membership)

**Screenshots**

**Additional context**

**Comment by prachidamle** [comment]
I moved it to to-test, but there are some issues causing the image not published out.

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required. I understand the issue well.
 
**Validation Environment:**

Rancher version: v2.6-head `70f024e` pulled at 8/24/21 6:13 pm Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3+rke2r2
 
**Validation steps:**

1. Create a standard user and a restricted admin user.
2. Log in as the standard user. Create a cluster.
3. Now, log in as the restricted admin user. Ensure you can see that cluster.

![image](https://user-images.githubusercontent.com/45179589/130711008-787b23af-1073-454c-b472-4d4f71c8818f.png)


Note: I also checked with a cluster created by admin. The restricted admin can indeed see all clusters even those created by the standard user and admin user. Additionally, the standard user can only see the cluster and cloud credentials it created, as expected. The restricted admin can only see it's own cloud credentials, as expected.
