### ISSUE TITLE
Add bulk actions on grid views

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#342]
You should be able to select several/all rows of the grid and do any action that makes sense in bulk (start, stop, restart, activate, deactivate, delete, purge, restore, ...).

**Comment by ibuildthecloud** [comment]
- [ ] I
- [ ] Would
- [ ] Like
- [ ] This
- [ ] Feature

**Comment by vincent99** [comment]
Carry the +1 from @kenhuang in #1505.

**Comment by vincent99** [comment]
Adding to the containers screen for 1.3, once we're happy with that it will go into all the other views.

**Comment by tfiduccia** [comment]
Version - master 12/30
Verified this is in.  Bugs will be logged in separate issue
