### ISSUE TITLE
VMware Esx + RancherOS

### ISSUE THREAD

**Issue by goodspd** [rancher/rancher#3420]
Hi,

I'm using VMware Esxi 6.0.0, 2494585 and RancherOS v0.4.2 - Docker 1.9.1 - Linux 4.2.

I boot from ISO file and rancher boots with DHCP the problem is that i can access machines from Rancher but from outside i cannot ping/ ssh or whatever the rancher machine, same thing happens if i configure static ip address. For troubleshooting i've installed in my Vmware workstation with no problems!

I think the problem may be some kind of lack of compatibility between VMware ESxi and Rancher?!

This is a valid setup? when i setup VM what SO shoud i configure in VMware? Any ideias about this issue?

**Comment by yobasystems** [comment]
Sounds like you have a dns or port forwarding issue. Make sure to port forward ports 500udp & 4500udp to you RancherOS vm and check that you can resolve all hostnames from host to host.

**Comment by goodspd** [comment]
Hi,

I forgot to say that i've made testes in server network that doesn't have any firewall...

**Comment by rlex** [comment]
just for testing: try importing vmware workstation machine into ESXi.
Also, what virtual NIC do you use for that rancherVM? E1000? VMXNET?

**Comment by sshipway** [comment]
I have had the same problems trying to make RancherOS work under VMWare.  In the end, we went with CoreOS instead because it cones as an OVA image, has VMWare Tools installed, has NFS support installed, and is easily configured via an ISO image.

**Comment by goodspd** [comment]
Hi,

@rlex Probably importing from Workstation works but i don't want to use that procedure to get machines in production. already tested with all types of vNIC's.

@sshipway Thanks for feedback, right now we're using CoreOS too since rancherOS doesn't work!

**Comment by sshipway** [comment]
@goodspd - We have VMWare set up with a cloud-config YAML in an ISO on the ESX host, so that to making a new VM from the vanilla OVA, with this ISO mounted on the virtual CD , creates a new Docker host and links it into Rancher automatically.  Less than a minute to add capacity to an Environment!

If you're interested, I can give you a copy of the YAML we use to configure CoreOS like this.  Contact me directly rather than filling this thread with irrelevant discussion

**Comment by deniseschannon** [comment]
@goodspd This sounds more like an issue with RancherOS working under VMware. Would you be okay with creating an issue in rancher/os instead?

**Comment by goodspd** [comment]
Hi,

I found the problem in rancher forums. This happens when we run ping without "sudo".
