### ISSUE TITLE
With a Standard user GET on "clusters" fails on the "provisioning.cattle.io" API for a custom cluster

### ISSUE THREAD

**Issue by igomez06** [rancher/rancher#34205]
**Rancher Server Setup**
- Rancher version: v2.6-head commit-id: 25d39aa
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): helm install

**Information about the Cluster**
- Kubernetes version: v1.21.3-rc4+rke2r2
- Cluster Type (Local/Downstream): RKE2 Custom Cluster

**Describe the bug**
With a standard user using the "provisioning.cattle.io" API, after provisioning a custom RKE2 cluster, doing a GET on that cluster fails. 

**To Reproduce**

- Using provisioning.cattle.io API
- Provision a custom cluster
- Attempt to do a GET on the cluster just created.

**Result**
`clusters.provisioning.cattle.io "customclustertzcen" is forbidden: User "u-5j8kf" cannot get resource "clusters" in API group "provisioning.cattle.io" in the namespace "fleet-default"`

**Expected Result**
A successful GET.

**Additional context**
This issue, only happens with custom clusters. Manually I registered a node for the custom cluster, and went back did a GET query on that cluster, and it was successful. The failure happens, when there are no nodes registered, and the cluster is in the provisioning state.

**Comment by thedadams** [comment]
I created a custom cluster via the UI and the API. In both cases, the standard user was able to view the cluster in the API before adding any nodes to the cluster.

**Comment by igomez06** [comment]
Since this was done programmatically I was trying to GET the cluster too quickly that RBAC had not been setup yet. When I put in a delay the GET was successful.
