### ISSUE TITLE
[2.5.x] Update xip.io to sslip.io

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34214]

**Comment by thehejik** [comment]
Tested on `rancher/rancher:v2.5-head 0019305`

* The variable `ingress-ip-domain` in global settings was changed to value `sslip.io`
![image](https://user-images.githubusercontent.com/12828077/131333165-00aec6b5-8089-45ef-8f73-dd172a71e220.png)

* ingress using this new value works and the http service is reachable 
![ingress-sslip](https://user-images.githubusercontent.com/12828077/131333528-11dd3151-4963-48a0-8531-48be12094ed4.png)


Closing.
