### ISSUE TITLE
Using rancher-managed network causes docker bridge network as well, which causes port conflicts

### ISSUE THREAD

**Issue by deitch** [rancher/rancher#3422]
If I have 2 containers, both expose the same ports:

````yml
ports:
  - 443:443
````

However, I do not use the docker bridge, I only use Rancher-managed network.

The `ports` really should not matter, since each container has its own IP on the Rancher network. However, when the Rancher-managed network starts, it *also* assigns an IP on the docker bridge network, which causes the ports to create a NAT entry, because the ports are listed in the `yml`. Starting two such containers on the same host causes at least one to fail, because of port conflicts. Both cannot have 443 on the host.

But if I am using Rancher-managed networking, I do **not** need the port mapping. Granted, I could remove the `ports` entry... but why does it bother assigning a docker bridge IP as well?

**Comment by withinboredom** [comment]
It does that, because you asked it to. https://docs.docker.com/compose/compose-file/#ports You can only forward a port from the host to a single container. Meaning if you start a container that forwards has
``` yml
ports:
 - 443:443
```
you can **only** serve one of those containers per host. If you want more than one container bound to that port, you should use a load balancer to route the traffic appropriately.

You should use [expose](https://docs.docker.com/compose/compose-file/#expose) if you don't want it NAT'd from the host...

**Comment by deitch** [comment]
Agreed, that *if* I use the docker bridge, *then* those ports would be NATted (NAT'd? NAT'ed?). But since I did choose managed, why does it *also* map the container to the docker bridge?

Or are you saying that rancher views the `ports` to indicate, "also connect to the docker bridge"? Cannot be, because if I remove the `ports` section, I still get a docker bridge address.

In the meantime, I removed the `ports` section from all relevant `yml` files, but trying to understand it.

**Comment by withinboredom** [comment]
Yes, you will get both ip addresses on that same network interface. This is what I use in my shell script to get my ip addresses (taken from one of the catalog images):

``` bash
META_URL="http://rancher-metadata/2015-07-25"

get_host_ip() {
    UUID=$(curl -s -H 'Accept: application/json' ${META_URL}/containers/${1}|jq -r '.host_uuid')
    IP=$(curl -s -H 'Accept: application/json' ${META_URL}/hosts |jq -r ".[] | select(.uuid==\"${UUID}\") | .agent_ip")
    echo ${IP}
}

get_host_name() {
    UUID=$(curl -s -H 'Accept: application/json' ${META_URL}/containers/${1}|jq -r '.host_uuid')
    IP=$(curl -s -H 'Accept: application/json' ${META_URL}/hosts |jq -r ".[] | select(.uuid==\"${UUID}\") | .name")
    echo ${IP}
}

get_container_primary_ip() {
    IP=$(curl -s -H 'Accept: application/json' ${META_URL}/containers/${1}|jq -r .primary_ip)
    echo ${IP}
}

get_self_name() {
    self=$(curl -s -H 'Accept: application/json' ${META_URL}/self/container| jq -r .name)
    echo ${self}
}

# then to get the current ip of the running container:
IP=$(get_container_primary_ip get_self_name)
```

Docker assigns those ip's when the container starts. Rancher gives the interface a second ip to communicate over the managed network. You'd have to modify the docker daemon flags to not be assigned an ip over the docker bridge.

**Comment by vincent99** [comment]
Managed is "on top of" Bridged.  You always get both IPs.  Publishing a port to the outside world is like the *single most used feature of Docker*.  Making `ports` === `expose` is redundant, useless to 99.9% of users, and no bridge IP also means no default gateway/no access to the internet.

**Comment by deitch** [comment]
> and no bridge IP also means no default gateway/no access to the internet

Well, only if you use the bridge network. But in high performance environments you specifically are trying to *avoid* the bridge, and do direct access (macvlan, ipvlan, dedicated NIC, etc.). And there are plenty of alternative overlay or direct L3 (Calico) networks. 

The bigger issue is that it opens security questions. What if I want to run 2 containers on the same host who should not be able to talk to each other?

I am curious why you chose to leverage the bridge as oppose to a separate network (like Weave or others)?

**Comment by withinboredom** [comment]
Using managed network @deitch, you can only "talk to" containers that are in the same service or linked to that service. I haven't looked to see if you can give a container permission to be promiscuous and see packets you shouldn't be able to see ... but I know from experience that you can't route to containers you aren't linked to in some way.

**Comment by deitch** [comment]
@withinboredom really? So the managed network stops communication between those in different services? Or different stacks? The managed network is a single system-wide ipsec network.

I will run a test right now.

**Comment by deitch** [comment]
And even if it does, 2 docker containers on the same host on the same docker bridge can talk to each other, can they not? Unless inter-container communication is disabled?

**Comment by withinboredom** [comment]
Assuming you have services bound to that ip-address, then yeah, they'd be able to talk over the bridge ip on the same host. BTW, you should look at the new --subnet command in docker v1.1... if you have the ability to assign a host a range of ip's, you can actually use host networking natively.

**Comment by withinboredom** [comment]
I created an issue for the rancher guys here: https://github.com/rancher/rancher/issues/3452

**Comment by deitch** [comment]
@withinboredom  What do you mean by:

> use host networking natively

I thought if I run `docker network create --subnet 203.0.113.0/24 --gateway 203.0.113.254 mynet` that is still creates a bridge, and assigns IP routing through that bridge, and NAT. Are you saying it doesn't? That it applies the IP directly on the host interface?
