### ISSUE TITLE
RKE2 Provisioning: Registries - Validate setting up mirror and registry configuration

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34224]
RKE2 has the ability to mirror registries and add registry configuration that applies to any image that is being pulled.

Mirrors - Allow you to pull images from a different endpoint (This is used for unauthenticated and authenticated registries)

Registry Configuration - For any registry that needs auth, you need to configure this. Opotionally, this can be used in conjunction with a mirror.

We need to validate that by adding mirrors and registry configuration you could set up RKE2 cluster to use either mirror or registry to:

1. Pull RKE2 components that build a RKE2 cluster
2. Pull user workload defined images

**Comment by slickwarren** [comment]
on v2.6.0-rc6:
* rke2 cluster using a registry with noauth active -- pass

Reopening for the following:
* unable to provision when using a registry where auth is required (username/password)
* unable to provision using a mirror [(panic when testing)](https://github.com/rancher/rancher/issues/34425)

**Comment by slickwarren** [comment]
As of v2.6.1-rc1, I am blocked on testing mirrors. Here is the blocker issue: https://github.com/rancher/dashboard/issues/4137

**Comment by deniseschannon** [comment]
The blocked issue should be resolved in 2.6.3.

**Comment by slickwarren** [comment]
using v2.6.4-rc3, I've tested the following:
* using system-default-registry (registry has no authentication) to deploy downstream clusters -- pass
* overriding system-default-registry -- pass
* configure a downstream cluster to use a mirror -- pass
  * verify mirror is used when pulling user images i.e. workload deployments -- pass
  * new request for future testing https://github.com/rancherlabs/corral/issues/36
* configure a cluster to use a registry with authentication -- pass
* configure a cluster using multiple registries -- pass
