### ISSUE TITLE
RKE2 Provisioning: Registries - Validate private registry for all cluster components

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34223]
There are multiple registries that can be configured on a RKE2 cluster and where/when registries are used. 

This issue is to track the ability to pull all related Rancher images on the cluster for setting up RKE2 and helm charts.

The UI is going to update to make this more intuitive, but it is essentially.

1. Creating a mirror from where the hostname for `docker.io/rancher` images are mapped to the endpoint of a user defined registry/rancher.
2. If the user defined registry requires credentials, this will also create a registry configuration. 

This will *not* be using the system-default registry option on the RKE2 cluster as we are mapping all Rancher images from Dockerhub to be pulled from your own registry.

**Comment by vincent99** [comment]
Added simpler option to configure just the systemDefaultRegistry and a user/pass, as RKE1 does.

**Comment by slickwarren** [comment]
blocked by https://github.com/rancher/rancher/issues/34224

**Comment by deniseschannon** [comment]
@slickwarren Why is this issue blocked?

**Comment by deniseschannon** [comment]
Per @slickwarren 

on v2.6.0-rc6:

rke2 cluster using a registry with noauth active -- pass
Reopening for the following:

unable to provision when using a registry where auth is required (username/password)

**Comment by slickwarren** [comment]
on 2.6.0-rc9: 
* a registry with valid certs (letsencrypt) is now working for rke2 clusters 🎉 
  * there are still some issues with this, but the basic functionality is working so I'll open new tickets for them:
    * [only admin can access previously created secrets from the dropdown](https://github.com/rancher/rancher/issues/34539)
