### ISSUE TITLE
Missing icon?

### ISSUE THREAD

**Issue by rlex** [rancher/rancher#3423]
Component	Version
Rancher	v0.56.0
Cattle	v0.141.0
User Interface	v0.85.0
Rancher Compose	v0.7.1

Near "add service":
<img width="1655" alt="screen shot 2016-01-26 at 5 42 12 pm" src="https://cloud.githubusercontent.com/assets/84462/12583511/47b8e952-c454-11e5-914b-bd7d3d23a164.png">

**Comment by deniseschannon** [comment]
I have v0.56.0 running but don't have the icon missing.

**Comment by vincent99** [comment]
That's very odd as that particular icon isn't even at all new..

**Comment by rlex** [comment]
Strange. I saw that missing icon in previous stable as well, but forgot to report. Anything i can help in tracing that issue? So far, i can say:
1) It happens only in chrome
1) That's not adblock or ghostery blocking this icon
2) Chrome inspector reports no 404/403/etc error code on this page

**Comment by rlex** [comment]
Ok, either there is something with caching on my chrome. I completely rm -rfed chrome cache directory and everything went back to normal.

**Comment by vincent99** [comment]
Were any other icons missing?  The newest one in that screenshot is the 'Stop' action on artifactory as an octagon with square in it..

The file is named containing it's is md5sum and loaded by that name (e.g. `http://rancher:8080/assets/fonts/rancher-icons-1d61a9c44aaf45d3b5438067bd8675a4.ttf?83xqp6`) so it really shouldn't be a caching problem.

**Comment by rlex** [comment]
Nope, just this one. Let's just assume for now that this is chrome acting weird, since it worked in safari. If something else appears, i'll report it.
