### ISSUE TITLE
RKE2 provisioning: Restoring a local snapshot fails

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#34231]
**Rancher Server Setup**
- Rancher version: v2.6-head #4def656
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details: no proxy, let's encrypt cert

**Information about the Cluster**
- Kubernetes version: v1.21.3-rc5+rke2r2
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Infrastructure Provider DO

**Describe the bug**
When you try to restore a local snapshot, the restore fails with:

```
Cluster.provisioning.cattle.io "dotest2" is invalid: spec.rkeConfig.etcdSnapshotRestore.s3.bucket: Required value
```

**To Reproduce**
* Create a cluster and don't configure a s3 backup target
* Create a snapshot
* Try to restore the snapshot

**Result**
Restoring fails and the above error message is displayd.

**Expected Result**
Cluster is restored from snapshot.

**Screenshots**
![Bildschirmfoto 2021-08-13 um 13 34 04](https://user-images.githubusercontent.com/243056/129351831-4c1d38a6-aad4-4638-8fdb-de1750af9e26.png)

**Comment by davidnuzik** [comment]
Denise asked me to test and see if this is still happening below are details: 

**My checks PASSED**
 
**Reproduction Steps:**

Not required. I understand the issue well.
 
**Validation Environment:**

Rancher version: v2.6-head `e3d4b6d19` pulled at 8/18/21 3:28 am Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3-rc6+rke2r2
 
**Validation steps:**

1. Create a 1-node RKE2 DO cluster in Rancher. Don't configure S3.
2. Take an on-demand snapshot.
3. Restore the snapshot.
4. Can confirm I do not encounter the issue described in the issue description. This was probably fixed recently with changes in this area Vincent/Darren have done.
When I restored the modal prompt came up and it restored quickly without any issues for me.
![image](https://user-images.githubusercontent.com/45179589/130104778-ae43f702-c4b3-49d0-ace6-e688676cb847.png)
