### ISSUE TITLE
aksv2 - HTTP Application Routing does not get enabled with Container Monitoring

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#34244]
**Rancher Server Setup**
- Rancher version: v2.6-e22c6bb23ee7e65f04e953afb7a449532cb44db0-head
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: NA

**Information about the Cluster**
- Kubernetes version: NA
- Cluster Type (Local/Downstream): AKSv2
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

When provisioning AKSv2 cluster with HTTP application routing along with Container Monitoring, HTTP application routing does not get enabled.

**To Reproduce**
 

1. Create AKS v2 cluster
2. Enable HTTP Application Routing
3. Enable Container Monitoring
4. Create
5. Wait for cluster to become Active
6. Check config

**Result**

HTTP Application Routing remains disabled

**Expected Result**

**Screenshots**

**Additional context**

If I try to Edit the Config to enable HTTP Application Routing again (after cluster creation), Rancher throws error
```
Failed to update cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
```
and later
```
Update failed for cluster [aks-routing], status: Failed
```

Only workaround I could find, is to enable HTTP application routing **first**. Then once the cluster is Active, Edit the config to enable Container Monitoring.

**Comment by paynejacob** [comment]
waiting on https://github.com/rancher/charts/pull/1421

**Comment by prabalsharma** [comment]
passed on 2.6-rc5
