### ISSUE TITLE
Project Owner is able to list snapshots on an rke2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34255]
**Rancher Server Setup** 
- Rancher version: 2.6-head commit id: `a55f77f`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Info: 
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE1
         Node Setup: 3 nodes all roles
         Version: 1.21.3
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes Version: `v1.21.3-rc5+rke2r2`
- Cluster Type (Local/Downstream): RKE2 DO 

**Describe the bug**
Project Owner is able to list snapshots on an rke2 cluster

**To Reproduce**

- As admin, add a user u1 as Project owner of a new project p1 in an rke2 cluster
- Login as u1 user
- Navigate to Cluster Management --> Cluster details --> snapshot page
- User is able to list snapshots

**Expected Result**
Project Owner should not be able to list snapshots 

**Note:**
- On an rke1 cluster, snapshots are not available/listed for a project Owner.

**Comment by deniseschannon** [comment]
Since the cluster is now a CRD and the snapshot list is in the `status` of the cluster, any one can view them. But only people who can edit the cluster CRD will be able to restore them.

**Comment by sowmyav27** [comment]
Closing as per https://github.com/rancher/rancher/issues/34255#issuecomment-899685186
