### ISSUE TITLE
Edit cluster as a user with no edit permissions on the cluster, page is stuck in loading and a 403 error is seen in the APi request machinepool

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34256]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `a55f77f`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Info: 
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE1
         Node Setup: 3 nodes all roles
         Version: 1.21.3
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes Version: `v1.21.3-rc5+rke2r2`
- Cluster Type (Local/Downstream): RKE2 DO 

**Describe the bug**
Edit cluster as a user with no edit permissions on the cluster, page is stuck in loading and a 403 error is seen in the APi request machinepool

**To Reproduce**
- As admin, add a user u1 as Project Member of a new project p1 in an rke2 cluster
- Login as u1 user
- Navigate to Cluster Management
- Edit cluster of the RKE2 downstream cluster
- 403 error is seen in the API request and the page is stuck in loading
`https://<rancher-server url>/v1/rke-machine-config.cattle.io.digitaloceanconfigs/fleet-default/nc-rke2-sowmya-1-pkdws`

**Note:**

- This happens for a user cluster member/ Project owner and a project member
- These users ^^^ are able to do an edit cluster on an rke1 cluster but changes cannot be saved.

**Expected:**
User must not have edit permissions.
If the user does have edit permissions, Cluster --> Edit config, user must not have permissions to Save the changes made.

**Comment by vincent99** [comment]
If you don't have edit permission you shouldn't be able to get to the actual edit screen to begin with.

Did you really mean looking at the Config tab of viewing details (the "edit" screen in read-only mode)?  I fixed some issues around that and made it not explode if the machineConfig is unreachable.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `c10ef4b`**

- As a project member and owner, user is not able to edit cluster config. (not sure how I hit the Original issue)
- Closing this issue. Will log a new one or reopen if I see this again
