### ISSUE TITLE
Rancher will spawn dozens of machines in each pool in a certain situation

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#34264]
**Summary:**

If you reproduce https://github.com/rancher/rancher/issues/34088#issuecomment-899714663 and delete that cluster, then create a cluster that DOES specify the bucket name on the cluster creation form, and has the same cluster name, then Rancher will spawn dozens (seemingly infinite) number of machines.

This makes me think that _maybe_ if you had a cluster fail to provision the first time (for any reason?), delete it, then create it again with the same name and it's able to provision this time, then you might also encounter this issue. i.e. you might not have to reproduce rancher/rancher#34088 precisely - just have the cluster fail to provision first time, delete, then create again with same name. I am not sure.

While a fix in https://github.com/rancher/rancher/issues/34088 should resolve this problem, what concerns me is the fact that Rancher seems to "flip out" here and create so many machines. This is a peculiar behavior. I am not certain if this should be a blocker for release - probably not, but it might be worth looking into further post 2.6.0 release...

**Environment:**
Rancher version: v2.6-head `f81199694` 8/16/21 9:08 am Pacific
Rancher cluster type: single-node docker
Docker version: 19.03
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3-rc6+rke2r2

**Steps to Reproduce:**
1. Reproduce https://github.com/rancher/rancher/issues/34088#issuecomment-899714663 but with multiple pools. See the steps below.

1a. Due to [this bug](https://github.com/rancher/dashboard/issues/3847), create an s3-compatible cloud credential first as this will not work during cluster creation. Supply the required key and secret (fake key & secret values pictured but not used). Supply the optional bucket and region. This should have everything we need for when we create a cluster with s3 etcd snapshot/restore capability.
![image](https://user-images.githubusercontent.com/45179589/129608219-e0b56147-38db-48b6-a92e-cecf3c302f7e.png)

Note, the UI appears to send the correct request body for `cloudcredentials` POST:
![image](https://user-images.githubusercontent.com/45179589/129608743-190892c6-29b2-4822-a34a-f1415dce9bb8.png)

The response as well appears correct. The secret is not mentioned probably for security reasons.
![image](https://user-images.githubusercontent.com/45179589/129608867-5a457192-6741-41af-9652-0bde66139997.png)

1b. Create an rke2 cluster. In my case I used the DigitalOcean node driver. I created 3 pools. One called "etcd" for etcd role with 3 machines, just the default machine type for all of these. A second called "cp" for control plane role with 2 machines, and last a third pool called "worker" with 3 worker nodes. 
Under the cluster configuration section, pick etcd, then pick the s3-compatible cloud credential we created earlier. Enter a folder. Click Create.
The UI appears to send the correct request body for `provisioning.cattle.io.clusters` POST:
![image](https://user-images.githubusercontent.com/45179589/129609135-acec1706-efc2-4dc4-a49d-454918053b1e.png)
This appears as expected to me because I just specified the folder, otherwise the necessary key, region, secret, and bucket are supplied in the cloud config.

The response as well appears correct.
![image](https://user-images.githubusercontent.com/45179589/129609279-9da548de-923b-45d6-b5a2-93a91fc2614f.png)

1c. The cluster will instantly have an error and not provision. We have now reproduced https://github.com/rancher/rancher/issues/34088#issuecomment-899714663 and have completed the first step.

2. Now, delete this cluster. Give it a minute.
3. Finally, create this cluster again exactly the same with same name and pool names and number of machines, etc. EXCEPT we will this time specify the bucket name during cluster creation (override what is in the cloud credential with the same valid bucket name) due to the bug. This time the cluster will provision without errors shown in the UI/server logs. However something strange will happen (see expected/actual result below).

 
**Expected Result:**
The cluster should come up without any issues. 3 machines in etcd pool, 2 in cp pool, 3 in worker pool as specified.

**Actual Result:**
Rancher will create dozens of machines. In my case with DigitalOcean I was well on my way to hitting our limit when Rancher created nearly 60 machines in just a couple of minutes. You will see something similar to below in the UI:

![image](https://user-images.githubusercontent.com/45179589/129632223-08eda8a3-d90c-4331-a8f1-e405da484963.png)

Rancher will create pages of machines on the Machine Pools tab in the UI. And if you query DigitalOcean it will show quite a bit.

**Additional Info:**
I can reproduce this issue and provide the rancher server upon request if it makes things easier. If I do this though, it won't take long before we hit the DO droplet limit in QA's account and QA will be unable to create new droplets.

**Comment by davidnuzik** [comment]
Per process, I need to submit issues with the 2.6 milestone; however, I'm not quite sure this is really a blocker (and thus have not applied that label). This is because once we fix https://github.com/rancher/rancher/issues/34088#issuecomment-899714663 it should result in us not being able to repro this issue.

However, as mentioned in the summary of the issue - it's a bit concerning to me that Rancher will behave this way at all. It may be worth looking into at some point. (Maybe post 2.6.0?)

**Comment by thedadams** [comment]
Since the original issue to reproduce this has been fixed, I cherry-picked my changes. QA can use the image `thedadams/rancher:38e0f461` for testing this fix.

**Comment by paynejacob** [comment]
FAILED

I tested this with `thedadams/rancher:38e0f461`

1. docker run with `--no-cacerts`
2. setup ngrok tunnel point at my docker container
3. add valid DO and s3 cloud credentials
4. create an rke2 DO cluster named `issue-34264` with 3 workers, 2 control plane, and 3 etcd.
5. select the s3 credentials under etcd s3 snapshotting and set a path 
6. observe the cluster goes into an error state about the missing bucket
7. delete the `issue-34264` cluster
8. repeat step 4.
9. select the s3 credentials under etcd and set a bucket and path
10. observe the cluster go into a pending state and continually generate do droplets.

At this point deleting the cluster does not seem to do anything.  I usually killed the docker container at this point and had to delete the nodes manually.

**Comment by thedadams** [comment]
The image is ready: thedadams/rancher:af4dde44

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.
 
**Validation Environment:**

Rancher version: `thedadams/rancher:af4dde44`
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.4+rke2r1
 
**Validation steps:**

1. Try to reproduce the issue where we make a cluster in a bad state - this was done by creating a cluster with faulty s3 configuration as described in the issue body. What has changed is we won't like this cluster provision now - this is expected:
![image](https://user-images.githubusercontent.com/45179589/131202385-f7916993-cb37-45ae-9b44-7e827a9ad889.png)

2. Now, delete this cluster. This works. `kubectl get machines.cluster.x-k8s.io -A` comes back empty (this is good).
3. Create it again with the exact same name and config EXCEPT a proper config this time (proper bucket this time)
4. Confirmed we do not see the issue where Rancher attempts to provision many more machines than specified. The cluster comes up with proper amount of nodes.
5. Delete the cluster. This works. Check `kubectl get machines.cluster.x-k8s.io -A` again. This comes back empty again (this is good).
