### ISSUE TITLE
A Read Only User attempting to create a namespace, results in a non-descriptive error message

### ISSUE THREAD

**Issue by igomez06** [rancher/rancher#34260]
**Rancher Server Setup**
- Rancher version: v2.6.0-head on commit-id: f811996
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE1 
**Information about the Cluster**
- Kubernetes version: v1.21.3-rc6+rke2r2
- Cluster Type (Local/Downstream): RKE2 Digital Ocean Cluster

**Describe the bug**
With a Read Only user, when attempting to create namespace instead of getting a descriptive error, the error message returned is: `Method POST not supported`. 
This is the API response:
```
code: "PermissionDenied"
links: {}
message: "Method POST not supported"
status: 403
type: "error"
```

**To Reproduce**

- With an Admin user created a cluster (either RKE1 or RKE2)
- Create a project in that cluster
- Add a Read Only user to that aforementioned project
- Login as the Read Only user and attempt to create a namespace

**Result**
There is a failure with error message: `Method POST not supported`

**Expected Result**
A failure with a more descriptive error message.

**Screenshots**
<img width="1792" alt="Screen Shot 2021-08-16 at 12 34 41 PM" src="https://user-images.githubusercontent.com/2364045/129620276-a2f123c0-b4ed-4e9e-8779-fd21226b32fa.png">

**Comment by deniseschannon** [comment]
@ibuildthecloud With the Steve API, do we have the ability to update/change error messages?

**Comment by ibuildthecloud** [comment]
Why is a r/o user being shown a create button.

**Comment by deniseschannon** [comment]
This seems like the button should be hidden. 
Closing in favor of this dashboard issue: https://github.com/rancher/dashboard/issues/3875
