### ISSUE TITLE
Grant permissions to cluster operation when creating a cluster through a template

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#34277]
Permissions need to be created when a user creates the catalog entry so they can view the `operation` and see the status of the installation process. 

https://github.com/rancher/dashboard/issues/3721

**Comment by gaktive** [comment]
UI components are merged in per https://github.com/rancher/dashboard/issues/3721 -- shall we transfer that ticket to this repo for the backend work?

**Comment by StrongMonkey** [comment]
We have an insteresting problem to solve now...

> Helm install requires to check if resources exist or not, but in rancher you won't have the permission to check until you created cluster

https://github.com/helm/helm/blob/550f250ff90a9cc8f9d6f176d43181f9940c5a7b/pkg/action/install.go#L276

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/pull/34317: Fix the issue where standard user can't see operation and its logs in management cluster, causing failure to view logs after install rke2 templates.

https://github.com/rancher/helm/pull/31: Fix an issue where helm needs to check resources before creating it. It will fail in rancher RBAC model for provisioning v2 cluster and machine configs.

**Comment by StrongMonkey** [comment]
@anupama2501 To test this, you should be able to 
1. Add cluster template through catalog. https://github.com/rancher/dashboard/issues/3721#issuecomment-898592109
2. Login as standard user.
3. Try to create cluster from cluster template. You should be able to create clusters and machineConfigs from cluster template. You should be able to see logs in UI.

**Comment by anupama2501** [comment]
I was able to verify this on v2.6-head b8a44fa

- Added a cluster template in the local --> Apps and market place --> repositories [https://github.com/StrongMonkey/cluster-template-examples.git] 
- Created a cluster as an admin and verified the logs are displayed in the api at `https://<ip>/v1/catalog.cattle.io.operations/fleet-default/helm-operation-dpp9q/logs`

```
helm install --generate-name=true --namespace=fleet-default --timeout=10m0s --values=/home/shell/helm/values-cluster-template-0.0.1.yaml --version=0.0.1 --wait=true /home/shell/helm/cluster-template-0.0.1.tgz
creating 2 resource(s)
beginning wait for 2 resources with timeout of 10m0s
NAME: cluster-template-0-1629765003
LAST DEPLOYED: Tue Aug 24 00:30:04 2021
NAMESPACE: fleet-default
STATUS: deployed
REVISION: 1
TEST SUITE: None

---------------------------------------------------------------------
SUCCESS: helm install --generate-name=true --namespace=fleet-default --timeout=10m0s --values=/home/shell/helm/values-cluster-template-0.0.1.yaml --version=0.0.1 --wait=true /home/shell/helm/cluster-template-0.0.1.tgz
---------------------------------------------------------------------
```


- However, when I create a cluster as a standard user, I see an error on the UI `Unknown schema for type: catalog.cattle.io.operation` but the API has success logs same as above. 
- If we click on cancel, and go back to the cluster management page, we see the cluster getting created and comes to active state.


Closing this issue as the backend is working as expected and re-opened the UI ticket.
