### ISSUE TITLE
RKE2 s3 restoration fails and Rancher UI becomes unresponsive

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#34272]
**Environment:**
Rancher version: v2.6-head f81199694 8/16/21 9:08 am Pacific
Rancher cluster type: single-node docker
Docker version: 19.03
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3-rc6+rke2r2

**Steps to reproduce:**

0. Due to bug https://github.com/rancher/dashboard/issues/3847 - we will first create an s3-compatible cloud credential as you cannot do this upon cluster creation on that form.
Supply the key/secret and region. Due to another bug, https://github.com/rancher/rancher/issues/34088 we will specify the bucket during cluster creation. Save this s3-compatible cloud credential.

1. Create a multi-node RKE2 cluster. In my case I used the DigitalOcean node driver. I created 3 pools:
"etcd" - just etcd role - 3 nodes
"cp" - just controlplane role - 2 nodes
"worker - just worker role - 3 nodes
Each with default DO machine type (2vcpu, 4gb ram).

While creating the cluster, ensure you specify the s3-compatible cloud credential in the "Authorization" drop down for s3 config. You must also specify the bucket due to the previously mentioned bug. We'll set a cron schedule for snapshots to be every hour at 30 minute mark `30 * * * *` and a snapshot retention of 2.
![image](https://user-images.githubusercontent.com/45179589/129636421-cfa18a79-8308-446a-a39c-c80d4b82cf7f.png)

2. Now that the cluster is ready, take an on-demand snapshot. This may take some time.

3. Create a workload. In my case I created a Deployment with nginx. Wait for this workload to come up.

4. Perform a snapshot restore. 
![image](https://user-images.githubusercontent.com/45179589/129637930-65b1f7aa-41c7-4221-8b42-3dc1451935bd.png)

At first an error is shown during restore 
![image](https://user-images.githubusercontent.com/45179589/129638054-b7d9d604-eb0a-4236-8a68-9b882559872a.png)

And about this time, the rancher server logs will show messages like:
```
2021/08/16 23:52:27 [ERROR] error syncing 'c-m-hqtpmgqc': handler cluster-deploy: the server was unable to return a response in the time allotted, but may still be processing the request (get daemonsets.meta.k8s.io cattle-node-agent), requeuing
I0816 23:52:46.583212      33 trace.go:205] Trace[1391253521]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168 (16-Aug-2021 23:49:44.540) (total time: 182042ms):
Trace[1391253521]: [3m2.042215617s] [3m2.042215617s] END
E0816 23:52:46.583249      33 reflector.go:139] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Failed to watch *v1.Event: failed to list *v1.Event: the server was unable to return a response in the time allotted, but may still be processing the request (get events.meta.k8s.io)
I0816 23:52:52.846981      33 trace.go:205] Trace[1377674519]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168 (16-Aug-2021 23:51:52.831) (total time: 60015ms):
Trace[1377674519]: [1m0.015024356s] [1m0.015024356s] END
E0816 23:52:52.847025      33 reflector.go:139] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Failed to watch *v1.LimitRange: failed to list *v1.LimitRange: the server was unable to return a response in the time allotted, but may still be processing the request (get limitranges.meta.k8s.io)
I0816 23:53:03.714774      33 trace.go:205] Trace[1689103137]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168 (16-Aug-2021 23:52:03.696) (total time: 60017ms):
Trace[1689103137]: [1m0.017981342s] [1m0.017981342s] END
```
Messages similar to the above repeat. All of these seem to be at `pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168` according to the errors in the logs.

The UI will not respond, you can click on something, but eventually get a timeout error.

![image](https://user-images.githubusercontent.com/45179589/129643281-b13be5b8-5e38-4193-a8c2-111445b40c73.png)

**Comment by deniseschannon** [comment]
RKE2: https://github.com/rancher/rke2/issues/1657

**Comment by Jono-SUSE-Rancher** [comment]
Should be ready to test with the latest [v1.21.3-rc7+rke2r2](https://github.com/rancher/rke2/releases/tag/v1.21.3-rc7%2Brke2r2)

**Comment by davidnuzik** [comment]
v2.6-head `0935a90` 8/24/21
single-node rancher on docker 20.10

S3 restore doesn't work still but this is due to separate issues tracked in other bugs. However The UI indeed no longer ends up in this state where it is unresponsive. As such, going to close this issue.
