### ISSUE TITLE
convoy-nfs : adding a new host problem.

### ISSUE THREAD

**Issue by atoy40** [rancher/rancher#3428]
Hello,
I have a convoy-nfs stack (v0.2) over 2 hosts. Then I add a new host to rancher, it's detected, and immediately a new convoy-nfs container start on it. The problem is it never appears in the list of host in the storage pool tab.
btw, the nfs is correctly mount on this new host, so I've try to start a container on this host using a convoy-nfs volume, but this container never start. It stay in the starting state, then dissapears dozen of seconds later, so the absent of the new host in the storage pool tab is not just a "cosmetic bug" (the exact same container start perfectly on other hosts)
I've tried to restart the convoy-nfs-storagepool container w/o success.

I'm using :
- Rancher 0.51.0
- RancherOS 0.4.2 on hosts
- convoy-nfs 0.2

Anthony

**Comment by cjellick** [comment]
@atoy40 are there any errors in the logs for the convoy-nfs container that has the storagepool command? ...one of the hosts should have two convoy-nfs containers. It will be one of those two containers.

**Comment by cjellick** [comment]
@atoy40 also is there anything interesting in the logs of the convoy-agent container on the new host?

**Comment by atoy40** [comment]
Logs was looking good in both of them (the new and the storagepool)
But I updated my rancher-server (0.51 to 0.56) one hour ago ... and now it looks good, the third host is now visible. I'll see next time i'll add an host if something change.

**Comment by deniseschannon** [comment]
There were some changes in between the Rancher versions and template changes that might have caused incompatibility. Glad to hear it's working now. I'm going to close now that you have it working.
