### ISSUE TITLE
RKE2 Windows node tries to pull linux image `rancher/system-agent:v0.0.1-alpha37-suc`, causes `imagepullbackoff`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34282]
**Rancher Server Setup**
- Rancher version:v2.6.0-rc3
- Installation option (Docker install/Helm Chart): docker install
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):k3s
         Node Setup:single node
         Version:v1.21.3+k3s1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:v1.21.3-rc6+rke2r2
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):custom 

**Describe the bug**

when registering the windows node, a pod fails to pull linux image `rancher/system-agent:v0.0.1-alpha37-suc`, causes `imagepullbackoff`

**To Reproduce**
 
* setup a custom cluster 
  * register linux node first (1 node, all roles)
  * register windows worker node

**Result**
* a pod fails to pull linux image `rancher/system-agent:v0.0.1-alpha37-suc`, causes `imagepullbackoff`
* the windows node is in state waiting for agent to check in and apply initial plan when viewing through cluster management

**Expected Result**

windows node should only try to pull windows images. All pods should come to active state

**Screenshots**

**Additional context**

**Comment by deniseschannon** [comment]
The plan is to add a node selector so the SUC deployment will go on Linox only nodes.

**Comment by kinarashah** [comment]
Available to test with v2.6.0-rc5.

**Comment by sirredbeard** [comment]
Pulled out of QA Next Up. Awaiting RKE2 RC.

**Comment by Jono-SUSE-Rancher** [comment]
Should be ready to test with the latest https://github.com/rancher/rke2/releases/tag/v1.21.3-rc7%2Brke2r2

**Comment by anupama2501** [comment]
blocked https://github.com/rancher/rancher/issues/34408

**Comment by deniseschannon** [comment]
@anupama2501 Let's use this issue to track that the system-agent pod is deployed only on Linux nodes. 

To verify, only add an etcd+cp linux cluster and then windows worker nodes. There should be no attempt to deploy system-agent on it. 

Afterwards, add a linux worker node. I'm not positive if system-agent should run on this node, but as long as nothing is attempted on the windows node, it should be fine.

Note: you may have to wait for things to deploy due to: https://github.com/rancher/rancher/issues/34368

**Comment by anupama2501** [comment]
I'm not seeing this issue anymore and seeing the issue https://github.com/rancher/rancher/issues/34431

Closing this issue
