### ISSUE TITLE
Validate the latest cert-manager in Rancher server helm chart to the latest version

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34299]
Review the cert-manager in Rancher to see if it can be updated to the latest version.

The current version 1.0.4 is pinned in our install docs, so if this is changed, it will require a docs change as well. 

As part of the testing for this, we would need to see if there are any issues with

HA install of Rancher v2.5.x and upgrading to Rancher v2.6 with cert-manager updates as well

**Comment by cbron** [comment]
@deniseschannon by "update in Rancher" do you mean just the CR's that exist in the Rancher chart ? That and the docs.

**Comment by deniseschannon** [comment]
It would be to test that we could use the latest version of cert manager with Rancher and being able to update docs. 

I forgot that it's not actually tied to anything in Rancher.

1. Test out install of Rancher using new cert-manager version
2. Test out upgrading cert manager version when upgrading from previous recommended version (1.0.4).

**Comment by snasovich** [comment]
@deniseschannon , JFYI I've tried latest version (1.5.1) of cert-manager when creating hardened HA Rancher setup and it seems to have worked fine. I'm not sure if something more subtle is broken, but at high level Rancher worked fine (including provisioning RKE2 cluster in DO).
We could also simplify the install command to below (if we no longer need to worry about k8s <=1.15
```
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.5.1 \
  --set installCRDs=true
```

Now, for this issue in particular, I think we want to have QA switch to using cert-manager 1.5.1 and observe if they hit any issues and if all is fine we can probably move this one for documentation repo and address it there.
@deniseschannon @sowmyav27

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `b3980c2`**

- Deployed HA RKE1 local cluster - both hardened and non hardened with `cert-manager --version v1.5.1`
- HA came up Active
- Deployed a downstream RKE2 cluster which came up Active.

**Comment by snasovich** [comment]
@sowmyav27 , per my other comment above I think we can close it based on my validation that covers dev-validate.
Also, I've opened https://github.com/rancher/docs/issues/3458 to update documentation.

**Comment by snasovich** [comment]
@paynejacob , please validate the upgrade scenario as per issue description.

**Comment by paynejacob** [comment]
Validated on `v2.6.0-rc4`

cluster: `rke1`
k8s version: `v1.20.9`

Each version was tested on a  clean cluster.  For clean installs I installed the new version of cert manager and then installed rancher.  For upgrade testing I installed rancher `v2.5.9` and with cert manager `v1.0.4`.  I would first upgrade cert manager and them upgrade rancher.

# Commands used

## Cert manager install
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.0/cert-manager.crds.yaml
helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.5.0

## Snake Oil
helm upgrade --install --create-namespace --namespace cattle-system --set hostname=<hostname> rancher rancher-latest/rancher --version v2.6.0-rc4

## Letsencrypt
helm upgrade --install --create-namespace --namespace cattle-system --set hostname=<hostname> --set ingress.tls.source=letsEncrypt --set letsEncrypt.email=jacob.payne@suse.com rancher rancher-latest/rancher --version v2.6.0-rc4

**Comment by deniseschannon** [comment]
@paynejacob Can you open a docs issue to ask to update the instructions for installing rancher to use the version of cert-manager that was validated?

**Comment by snasovich** [comment]
@deniseschannon , already done earlier today.

@paynejacob , did you test on 1.5.0? Both me and @sowmyav27 used 1.5.1 which is latest at this time.

**Comment by paynejacob** [comment]
I tested on 1.5.0, looks like their site is a little out of date.  Should I do a full retests or just a smoke test on update.  IMO it is a patch so if it works for 1 update it should be fine.

**Comment by paynejacob** [comment]
it looks like 1.5.2 was release 12 hrs ago

**Comment by snasovich** [comment]
Smoke test would be fine. I’d go with 1.5.1 as that’s what we’ve tested yesterday.

**Comment by paynejacob** [comment]
validated upgrade to `v2.5.1`

**Comment by snasovich** [comment]
@paynejacob , you mean 1.5.1?

**Comment by paynejacob** [comment]
Yes I did
