### ISSUE TITLE
Remove the Rancher dependency on the PowerShell commandlets

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#34292]
Since it has been blocking us a few times on tagging and cutting RCs, we need to have an official plan to remove our dependency to PowerShell gallery to prevent future builds from failing.

**Comment by phillipsj** [comment]
@Jono-SUSE-Rancher @cbron I have got these changes completed. What Zube status does this kind of work need to be assigned?

**Comment by Jono-SUSE-Rancher** [comment]
@phillipsj that's a good question. Since this isn't necessarily anything that QA can validate, this is more of a dev-validation type task. Honestly, if you have this fixed/changed already, what branch is it in? Is there any reason this has to wait until v2.6.3 if you've already got a fix merged? I feel like we should bump this to 2.6.1 and slap it with a `dev-validate` tag and just have a dev validate that the dependency on PowerShell has been removed.

@cbron - Thoughts?

**Comment by phillipsj** [comment]
I have this now merged into master and I am planning to backport this to the release 2.6 branch.

**Comment by phillipsj** [comment]
@sirredbeard thoughts?

**Comment by cbron** [comment]
Yes lets just move to 2.6.1 and dev-validate.

**Comment by sirredbeard** [comment]
Leaving in rancher/rancher because work is almost complete.

**Comment by cbron** [comment]
@sirredbeard is windows team validating this ?

**Comment by phillipsj** [comment]
@sirredbeard @cbron  The builds were tested locally before submitting the PRs validating that the builds still functioned after the change. The drone builds for both PRs built the windows container successfully which indicates that everything is functioning as expected.
