### ISSUE TITLE
Ability to specify network tags for node pools in GKE cluster (via Terraform provider)

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#34291]
Terraform provider support for additional argument for network tags added per https://github.com/rancher/rancher/issues/33406

_JIRA ID: SURE-3037_

**Comment by snasovich** [comment]
Related PR: https://github.com/rancher/terraform-provider-rancher2/pull/711

**Comment by prabalsharma** [comment]
tested with https://github.com/rancher/terraform-provider-rancher2/files/7059822/terraform-provider-rancher2_darwin_amd64.zip on v2.6-940ebaf5d3115463d2ab3d5ebcf4c5047fb0a1a2-head
