### ISSUE TITLE
"Error setting machine     configuration from flags provided: digitalocean driver requires the --digitalocean-access-token" seen on a machine pool during RKE2 provisioning

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34308]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id : `72986b2`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): k3s
         Version: 1.21.3
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: v1.21.3-rc6+rke2r2
- Cluster Type (Local/Downstream): RKE2 DO

**Describe the bug**
"Error setting machine configuration from flags provided: digitalocean driver requires the --digitalocean-access-token" seen on a machine pool during RKE2 provisioning

**To Reproduce**
Note: Unable to reproduce consistently But hit this two times in a row

- Deploy a DO cluster with muultiple node pools. Click on Save
- Edit cluster when it has started provisioning 
- Add a nodepool and save changes made
- The added node pool has failed provisioning
- Error seen on the Machine pool

```
  failureMessage: 'Failure detected from referenced resource rke-machine.cattle.io/v1,
    Kind=DigitaloceanMachine with name "sowmya-do3-pool4-n4mr7": Error setting machine
    configuration from flags provided: digitalocean driver requires the --digitalocean-access-token
```

**Expected Result**
Node/Machine pool should finish provisioning. 

**Additional Info**
When tried multiple times after this issue was seen, could not reproduce it. UI Seems to be sending the right details in the API request.

**Comment by snasovich** [comment]
@sowmyav27 , there were a lot of fixes related to cloud credentials since this was submitted. Did you or anyone else in QA run into it recently? If not, maybe we can close it.

**Comment by sowmyav27** [comment]
on 2.6.1, this issue is not seen. Will close this issue for now. Will reopen or log a new one if seen again.
