### ISSUE TITLE
Update RKE2 helm charts to not run on Windows worker nodes

### ISSUE THREAD

**Issue by sirredbeard** [rancher/rancher#34307]
Mirror of RKE issue https://github.com/rancher/rke2/issues/1664

**Comment by bmdepesa** [comment]
https://github.com/rancher/rke2/issues/1665 for v1.21.3+rke2r2

**Comment by Jono-SUSE-Rancher** [comment]
Should be ready to test with the latest [v1.21.3-rc7+rke2r2](https://github.com/rancher/rke2/releases/tag/v1.21.3-rc7%2Brke2r2)

**Comment by deniseschannon** [comment]
All RKE2 components (CNI, coredns, metrics server, ingress) have added a node selector to deploy on linux nodes. 

This can be validated that when adding a Windows worker node, none of these components try and run on it.

**Comment by anupama2501** [comment]
blocked https://github.com/rancher/dashboard/issues/3990

**Comment by deniseschannon** [comment]
@anupama2501 Can you close this with your findings about how the RKE2 components were deployed on the Linux nodes and none were attempted to schedule on the Windows worker nodes?

**Comment by anupama2501** [comment]
Verified on v2.6-head 2e55e84

RKE components CNI, coredns, metrics server, ingress are deployed on the linux nodes and not on windows worker node.
