### ISSUE TITLE
Cloning Standalone container with exposed port errors with "Validation failed in API:PortWrongFormat"

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3431]
From https://forums.rancher.com/t/validation-failed-in-api-portwrongformat/1491/5

Steps to Reproduce:
1. Create a standalone container with a port map
2. Clone the container and try to save

Result: Errors with "Validation failed in API: PortWrongFormat" even if I have selected another host to schedule the container so there is no port conflict. 

Expected Result: Port to be in valid format.

**Comment by tfiduccia** [comment]
Version - master UI 1/29
Verified fixed
