### ISSUE TITLE
Validate S3 credentials before taking backups 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34314]
Currently, we don't validate S3 credentials before taking backups so we take unlimited backups when the creds don't work.

**Comment by Jono-SUSE-Rancher** [comment]
Should be ready to test with the latest [v1.21.3-rc7+rke2r2](https://github.com/rancher/rke2/releases/tag/v1.21.3-rc7%2Brke2r2)

**Comment by deniseschannon** [comment]
Instead of trying to validate the S3 credential, we are making changes so that if the cluster will fail due to inability to upload/use S3, it will back off in trying to take snapshots. 

No change being done here.
