### ISSUE TITLE
Error creating a container

### ISSUE THREAD

**Issue by juandavidgc** [rancher/rancher#3432]
Hello! I'm creating a container of a postgres database, connecting to a gluster service. I've already created a gluster and a convoy-gluster service using the catalog. Those are working fine (I think). Now I want to run a postgres container, using "convoy-gluster" driver, but I got this error in log stacktrace of the rancher agent installed in the host machine:

```
time="2016-01-27T20:29:32Z" level="info" msg="Assigning IP [10.42.195.80/16], ContainerId [4a075d4d5d0b6b544045211bf67c0978f446997aa17310325bdaf745eab73760], Pid [21574]"
time="2016-01-27T20:29:32Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"4a075d4d5d0b6b544045211bf67c0978f446997aa17310325bdaf745eab73760\", From:\"-simulated-\", Time:0}"
time="2016-01-27T20:29:32Z" level="info" msg="Container locked. Can't run StartHandler. ID: [4a075d4d5d0b6b544045211bf67c0978f446997aa17310325bdaf745eab73760]"
time="2016-01-27T20:29:32Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"die\", ID:\"4a075d4d5d0b6b544045211bf67c0978f446997aa17310325bdaf745eab73760\", From:\"192.168.243.171:5000/detectid-postgres2:latest\", Time:1453926572}"
2016-01-27 20:25:06,857 ERROR agent [140370942160976] [event.py:112] Error in request : 5d78a699-ea9a-4ddf-a401-26f0b5cc6a0a
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 126, in on_ping
    self._add_instances(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 138, in _add_instances
    running, nonrunning = self._get_all_containers_by_state()
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 171, in _get_all_containers_by_state
    for c in client.containers(all=True):
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 67, in containers
    res = self._result(self._get(u, params=params), True)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 110, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
```

The container gets up but just for a few seconds, then the labal "unhelthy" appears and restart the service again.

Thanks in advance,

**Comment by juandavidgc** [comment]
I forgot to put the versions:

Rancher	v0.56.0
Cattle	v0.141.0
User Interface	v0.85.0
Rancher Compose	v0.7.1

**Comment by juandavidgc** [comment]
I've also saw this waring "Rancher state watcher returned with error. Waiting 4 and then restarting. Error that caused exit: Failed health check."

**Comment by deniseschannon** [comment]
That seems to indicate you might not have cross host communication. 

Did you do a fresh install or upgrade to v0.56.0? 
Could you exec into each network agent and ping another network agent?

**Comment by juandavidgc** [comment]
Hello! I made a fresh install of the 0.56.0. Both hosts are in the same network, so I don't have any problem with a ping between them.

From machine 1:
did@didmulti1:~$ ping 192.168.243.170
PING 192.168.243.170 (192.168.243.170) 56(84) bytes of data.
64 bytes from 192.168.243.170: icmp_seq=1 ttl=64 time=0.528 ms
64 bytes from 192.168.243.170: icmp_seq=2 ttl=64 time=0.473 ms
64 bytes from 192.168.243.170: icmp_seq=3 ttl=64 time=0.580 ms
64 bytes from 192.168.243.170: icmp_seq=4 ttl=64 time=0.619 ms
64 bytes from 192.168.243.170: icmp_seq=5 ttl=64 time=0.643 ms
64 bytes from 192.168.243.170: icmp_seq=6 ttl=64 time=0.639 ms

From machine 2:
root@didmulti3:/home/did/postgres# ping 192.168.243.175
PING 192.168.243.175 (192.168.243.175) 56(84) bytes of data.
64 bytes from 192.168.243.175: icmp_seq=1 ttl=64 time=0.516 ms
64 bytes from 192.168.243.175: icmp_seq=2 ttl=64 time=0.567 ms
64 bytes from 192.168.243.175: icmp_seq=3 ttl=64 time=0.486 ms
64 bytes from 192.168.243.175: icmp_seq=4 ttl=64 time=0.524 ms

Both machines have installed the containers of gluster and convoy-gluster and they seems to be working fine (they don't show unhealthy tag).

**Comment by deniseschannon** [comment]
Can you check your storage-pool page to make sure the convoy-gluster storage pool shows up?

Can you share a the docker-compose.yml of the postgres DB image that you tried to launch? In the stack that has the service, you can get the details from either clicking on this image.
![screen shot 2016-01-27 at 1 14 26 pm](https://cloud.githubusercontent.com/assets/11410997/12628447/0f3e7192-c4f8-11e5-9e0b-6e184b91bd9d.png)

Or for the stack, use the drop down to select "View Config".

**Comment by juandavidgc** [comment]
Of course, bellow is the information:

![image](https://cloud.githubusercontent.com/assets/11712573/12628549/b989663e-c511-11e5-8c36-235ee5e0c155.png)

![image](https://cloud.githubusercontent.com/assets/11712573/12628611/07868862-c512-11e5-9eb3-9d2f5ce9d8c6.png)

**Comment by deniseschannon** [comment]
I finally had some time to try out your docker-compose. The only difference that I did was to use the actual postgres image versus the image name you have. Mine came up with no problem. 

Couple of things: 

I just re-read your pinging between hosts, but have you actually tried to ping the network agent container from inside another network agent container? That would indicate whether Rancher could communicate across hosts or not. 

Have you tried doing a `docker pull` with your image name without the volume driver and set it up in Rancher's [registries](http://docs.rancher.com/rancher/configuration/registries/). It looks like you have a private registry.

**Comment by juandavidgc** [comment]
Hello Denise! Thanks for you try... I reinstall rancher, and tried it again and it works, I don't know why... before that I did pings between the machines and everything worked fine, but really I don't know what happened. Thanks again!
