### ISSUE TITLE
If catalog isn't found I get a 503 error when going to catalog page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3433]
Version - master 1/27 

Steps:
1.  Go to setting and add a catalog with a invalid URL
2.  Go to Catalog page

Result:  503 page saying "service unavailable"

Expected:  Can we not take them to an Error page and instead go to catalog page.  Show any valid catalogs and maybe an error on top saying "Catalog <name of catalog> not found".

**Comment by vincent99** [comment]
#3004
