### ISSUE TITLE
Explore adding option to import Fleet-only clusters into Rancher

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34334]
Fleet-only clusters are great for lightweight, IoT, and edge use cases, but some users may want an easy solution or process to import them into Rancher as well.

**Comment by shpwrck** [comment]
There is a manual process to enable this which should be automatable:

1. Register Fleet cluster
2. Create an empty Rancher cluster object
3. Convert the import manifest into a git repository
4. Add the `fleet.cattle.io/managed: false` labels to the resources in the repository
5. Create a GitRepo resource referring to the git repository and the target Fleet cluster
6. Clean up original Fleet resources after cluster has been successfully imported.

**Comment by kkaempf** [comment]
workaround exists, dropping `team/fleet`

/cc @agracey (edge use case)

**Comment by Jono-SUSE-Rancher** [comment]
Putting team/fleet back on this but removing the milestone, if they feel that they want to tackle this work, they can. Or they can close the issue (with workaround).
