### ISSUE TITLE
Can't read text in the Audit log & Processes Resource ID field

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3435]
Version - Master 1/27

Steps:
1.  In light theme, go to Processes or Audit Log page

Results:  In the Resource ID field, you can't read the text when it's dimmed
![image](https://cloud.githubusercontent.com/assets/11514927/12629411/15f79c90-c505-11e5-8698-456918305d60.png)

Expected: Should be able to read it.

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/455

**Comment by tfiduccia** [comment]
Version - master UI 2/4
Verified fixed
