### ISSUE TITLE
User is not redirected back to Dashboard UI from Ember UI on a rancher upgraded setup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34355]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `b3980c2e7`
- Installation option (Docker install/Helm Chart): docker install
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): K3s
         Version: 1.21.3

**Information about the Cluster**
- Kubernetes version: 1.20 GKE v2 (does not matter)

**Describe the bug**
User is not redirected back to Dashboard UI from Ember UI on a rancher upgraded setup

**To Reproduce**
**On an upgrade from 2.5.9 to 2.6-head**

1. user is redirected to dashboard
2. Navigate to `https://server/g` to go to the Ember UI
3. Then in the Url navigate to `https://server` , user is redirected to `https://server/g/clusters` Ember UI only

On a fresh install of rancher 2.6-head however, on the 3rd step, it takes the user back to the Dashboard UI - `https://server/dashboard/home`

**Expected Result**
On a rancher upgraded setup, user should get directed back to dashboard after going to EMber UI once, when user tries to navigate to URL `https://server`

**Comment by snasovich** [comment]
@vincent99 , could you please take a look into this? May be related to UI changes done to handle redirect to new UI on upgrade.

**Comment by vincent99** [comment]
The API is the one that decides where you go when you ask for `/`.  It was previously based on a preference that we no longer set/use, and last night (after this issue was created) was changed to just go to ember.

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.9 to 2.6-head commit id: `8898bf87`**

- HA Rancher install
- Navigate to https://server/g to go to the Ember UI
- Then in the Url navigate to https://server , user is redirected to https://server/dashboard/home VUE UI
