### ISSUE TITLE
Unable to access dashboard of imported Harvester cluster

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#34357]
**To Reproduce**
1. Deploy rancher v2.6.0-rc4 using docker run
2. Deploy Harvester using master iso image(the embedded Rancher is v2.6.0-rc3)
3. import Harvester cluster to the rancher

**Result**
Cluster explorer for the Harvester cluster is not available
![image](https://user-images.githubusercontent.com/4569037/130215891-8f9a48f3-a017-472f-a701-7e0f7929b5a0.png)

**Expected behavior**
Be able to access Harvester dashboard in rancher multi-cluster management.

**Other infos**

We've bumped the embedded rancher in the latest image.
1. With upstream rancher(v2.6.0-rc3) and embedded rancher(v2.6.0-rc3), downstream cluster explorer is available.
2. After updating the rancher image to `master-861fb9208fd59c7f0c5266f087ccf050c1577ead-head` in the same setup, downstream cluster explorer is not available.

**Root cause:**
When the cluster is imported, cluster-agent will create an aggregation secret.
- The embedded rancher uses it to establish the connection to the upstream.
- The secret naming is changed between these two versions in https://github.com/rancher/rancher/pull/33830. If we change the secret name in the above case 2, it will work again.

So technically the connection to the downstream cluster depends on both embedded rancher and central rancher versions atm.

Ideally, we would expect embedded & central rancher versions to be decoupled.

**Comment by deniseschannon** [comment]
@guangbochen There was a known breaking change between those versions. Please test with upgrading between v2.6.0-rc10 and v2.6.0.

**Comment by guangbochen** [comment]
close as it is confirmed from the Rancher team that we will just keep the secret name to remain unchanged.
