### ISSUE TITLE
the server could not find the requested resource

### ISSUE THREAD

**Issue by kerry-Cho** [rancher/rancher#34363]
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option Helm Chart:
   - If Helm Chart, Kubernetes Info:
         Cluster Type (k8s):
         Node Setup: master 3
         Version: 1.2.2
- Proxy/Cert Details:
- cert-manger

**Information about the Cluster**
- Kubernetes version: 1.2.2
- Cluster Type (Local):

**Describe the bug**

can I ask for advice you?
I tried installed rancher on my k8s cluster but dose not worked rancher
I have no idea, help me....

**Screenshots**

```
2021/08/20 16:29:27 [INFO] Rancher version v2.5.9 (3c5418944) is starting
2021/08/20 16:29:27 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Agent:false Features: ClusterRegistry:}
2021/08/20 16:29:27 [INFO] Listening on /tmp/log.sock
2021/08/20 16:29:27 [FATAL] the server could not find the requested resource
```

**Comment by yeongjet** [comment]
Maybe rancher doesn't support k8s 1.22 now

**Comment by kerry-Cho** [comment]
> Same problem, maybe rancher doesn't support k8s 1.22 now

Yes, that's the reason

**Comment by superseb** [comment]
You can follow https://github.com/rancher/rancher/issues/34060 for 1.22 support
