### ISSUE TITLE
Upgrade 0.51.0->0.56.1-rc1->0.56.1 - Not able to restore inter host connectivity even after network agent restart/reboot.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3436]
Server version - > Upgrade 0.51.0->0.56.1-rc1->0.56.1

Fresh install of 0.51.0 with 9 Ubuntu hosts having global Lb service with targets as 2 global services.
Upgraded to rancher-server version - 0.56.1-rc1

After upgrade 2 of the 9 instances lost connectivity with other hosts on managed network.

Trying to reboot hosts/ restarting network did not restore connectivity.

The issue was because of rancher-net process within the network agent running with gsm=false when it should have been launched with gsm=true.

Upgraded to rancher-server version - 0.56.1 

The hosts that did not have connectivity on managed network with other hosts continues to not have connectivity.
Restarting network agent/rebooting host did not help restore connectivity.

When I attempt kill rancher-net process in the network agent using the command below then new  rancher-net process is launched with gsm=true and network connectivity is restored.

```
killall -9 rancher-net 
```

When I attempt to restart network agent on this host , I see the host looses  connectivity with other hosts on managed network because the rancher-net process is launched again with gsm=false.

**Comment by will-chan** [comment]
Closed as obsolete.
