### ISSUE TITLE
RKE2 Azure clusters with Azure cloud provider only support 1 cloud config per cluster, but RKE2/k8s requires per node cloud provider config

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#34367]
**Summary:**
This is a strange behavior. If you create an RKE2 cluster with azure cloud provider configured it will provision and after a while become active (takes much longer than a non-cloud provider azure cluster to provision, but works). After a bit (1-3 mins?) it will go back to a Provisioning state then after a while back to Active and back and forth.

I wasn't successful in finding a route cause for this. Azure clusters that do NOT have Azure cloud provider set do NOT have this issue.
All I see is the rancher-system-agent re-applying plans but I don't think this should cause this. I'm not quite sure what's happening but suspect foul play either by the Rancher server or the rancher-system-agent. I have included logs which I hope will be helpful in identifying the cause. I tried to review them myself but didn't spot anything obvious to identify a cause.

**Also, it's possible I may have misconfigured my azure cloud provider set up as I am pretty new to azure cp config. I've included my config below as well.**

**Environment:**
Rancher version: v2.6-head `24e543524` pulled at 8/20/21 1:16 pm Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3-rc6+rke2r2

**Steps to Reproduce:**
1. Create a 1 node RKE2 cluster with the Azure node driver. On the RKE2 cluster creation form, pick "Azure" for the cloud provider. Provide an appropriate cloud provider config like what I have done below:
```
{
    "tenantId": "my-secret-tenantId-here",
    "aadClientId": "my-secret-aadClientId-here",
    "aadClientSecret": "my-secret-aadClientSecret-here",
    "subscriptionId": "my-secret-subscriptionId-here",
    "resourceGroup": "dave-nuzik-cp-docker-machine",
    "location": "westus",
    "subnetName": "dave-nuzik-cp-docker-machine",
    "vnetName": "dave-nuzik-cp-docker-machine-vnet",
    "vnetResourceGroup": "dave-nuzik-cp-docker-machine",
    "primaryAvailabilitySetName": "dave-nuzik-cp-as",
    "useInstanceMetadata": true
}
```
2. Give the cluster some time to create. This usually takes longer than any 1-node Azure cluster without azure cloud provider set for some reason. It will probably take at least 15 minutes possibly up to half an hour. Watch the UI. The cluster eventually becomes Active.
3. Observe for a longer time - a few mins or so after it's active it will switch to a Provisioning state. You might have to navigate away from the page or refresh. After a while it will go Active again and back and forth. It's usually active for a briefer time and provisioning for a longer time.
 
**Expected Result:**
I expected the cluster to come up and be Active and stay there.

**Actual Result:**
The cluster "flaps" between Active and Provisioning. I suspect foul play here by any of:
1. Me - maybe my azure cloud provider config is incorrect? If so why would it go active then go back to Provisioning?
(See my config above)

2. rancher-system-agent - the logs didn't seem to report anything obvious to me. Maybe I missed something. Full rancher-system-agent logs:
[1-node-azure-withcp-rancher-system-agent.log](https://github.com/rancher/rancher/files/7024219/1-node-azure-withcp-rancher-system-agent.log)

3. rancher - maybe for some reason it keeps trying to apply a plan to the system-agent or something. Full rancher server logs:
[1-node-azure-withcp-rancher.log](https://github.com/rancher/rancher/files/7024222/1-node-azure-withcp-rancher.log)

4. (unlikely) - maybe something is wrong with rke2 - Full logs below:
[1-node-azure-withcp-rke2-server.log](https://github.com/rancher/rancher/files/7024217/1-node-azure-withcp-rke2-server.log)

_Screenshots showing what I observe in the UI_
This shows rke2-server logs on top and rancher-system-agent logs on the bottom pane.

In active state:
![withcp_active](https://user-images.githubusercontent.com/45179589/130294663-eab98f9c-b7fb-4ff4-83e2-9356a56fd8fe.png)

In provisioning state:
![withcp_randomly_going_in_provisioning_state](https://user-images.githubusercontent.com/45179589/130294668-6ff6df4d-e9c2-4e01-a985-3adfefdc4d6a.png)

**Additional Info:**
_**Please let me know if I can assist in any way such as supplying more logs, providing an environment to reproduce with, jump on a call, etc.**_

**Comment by StrongMonkey** [comment]
We should check `kube-controller-manager` logs too, as system-agent detects that it is not ready. I assume it is related to azure cloud provider configuration since `kube-controller-manager` should be managing these cloud provider controller.

**Comment by StrongMonkey** [comment]
```
E0824 18:05:52.684370       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 307 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x424bc00, 0x70a95a0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x424bc00, 0x70a95a0)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/legacy-cloud-providers/azure.(*delayedRouteUpdater).updateRoutes(0xc000dc2270)
        /go/src/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_routes.go:154 +0x203
k8s.io/legacy-cloud-providers/azure.(*delayedRouteUpdater).run.func1(0xc000d5de6c, 0x2, 0x2)
        /go/src/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_routes.go:98 +0x2a
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc000d5dfb8, 0xc000d5de00, 0x0, 0x0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:211 +0x69
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc000cc6348, 0xc001dc1fb8, 0xc000cbf440, 0x0, 0x0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:541 +0x128
k8s.io/apimachinery/pkg/util/wait.PollUntil(0x6fc23ac00, 0xc000d5dfb8, 0xc000cbf3e0, 0x0, 0x0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:492 +0xc5
k8s.io/apimachinery/pkg/util/wait.PollInfinite(0x6fc23ac00, 0xc000d5dfb8, 0x0, 0x0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:464 +0x87
k8s.io/apimachinery/pkg/util/wait.PollImmediateInfinite(0x6fc23ac00, 0xc000d5dfb8, 0x0, 0x0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:481 +0x74
k8s.io/legacy-cloud-providers/azure.(*delayedRouteUpdater).run(0xc000dc2270)
        /go/src/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_routes.go:97 +0x52
created by k8s.io/legacy-cloud-providers/azure.(*Cloud).InitializeCloudFromConfig
        /go/src/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure.go:548 +0xb3f
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3314023]

goroutine 307 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x424bc00, 0x70a95a0)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/legacy-cloud-providers/azure.(*delayedRouteUpdater).updateRoutes(0xc000dc2270)
        /go/src/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_routes.go:154 +0x203
k8s.io/legacy-cloud-providers/azure.(*delayedRouteUpdater).run.func1(0xc000d5de6c, 0x2, 0x2)
        /go/src/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_routes.go:98 +0x2a
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc000d5dfb8, 0xc000d5de00, 0x0, 0x0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:211 +0x69
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc000cc6348, 0xc00202dfb8, 0xc000cbf440, 0x0, 0x0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:541 +0x128
k8s.io/apimachinery/pkg/util/wait.PollUntil(0x6fc23ac00, 0xc000d5dfb8, 0xc000cbf3e0, 0x0, 0x0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:492 +0xc5
k8s.io/apimachinery/pkg/util/wait.PollInfinite(0x6fc23ac00, 0xc000d5dfb8, 0x0, 0x0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:464 +0x87
k8s.io/apimachinery/pkg/util/wait.PollImmediateInfinite(0x6fc23ac00, 0xc000d5dfb8, 0x0, 0x0)
        /go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:481 +0x74
k8s.io/legacy-cloud-providers/azure.(*delayedRouteUpdater).run(0xc000dc2270)
        /go/src/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_routes.go:97 +0x52
created by k8s.io/legacy-cloud-providers/azure.(*Cloud).InitializeCloudFromConfig
        /go/src/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure.go:548 +0xb3f
```
Kube-controller-manager was panic given the cloud provider config.

**Comment by StrongMonkey** [comment]
This is because we don't use `routeTableName` in azure cloud config and it is causing panic. https://github.com/kubernetes-sigs/cloud-provider-azure/issues/550
The current workaround is to add `--configure-cloud-routes=false` to kube-controller-manager so we don't configure routes on cloud provider. 
At the same time, there is a upstream fix for that. https://github.com/kubernetes-sigs/cloud-provider-azure/pull/568

**Comment by davidnuzik** [comment]
@deniseschannon We'll probably want to document this workaround for Azure cloud provider

**Comment by davidnuzik** [comment]
@StrongMonkey can you briefly explain how you added `--configure-cloud-routes=false` to the KCM? Did this by modifying rke2 args annotation or directly on rke2 node?, etc. thanks

**Comment by StrongMonkey** [comment]
@davidnuzik You can add that in rancher UI.

Create cluster -> Cluster Configuration -> Advanced -> Additional Controller Manager Args

**Comment by davidnuzik** [comment]
v2.6-head `a6e7905cf` pulled 9/9/21 1:28pm Pacific

This is working for me now. Hussein helped me out (thank you!). The problem was really just that Shared disk is no longer supported on Azure and yet we offer this option in the UI. Thus, we need to fix this in Rancher. When creating an azure storage class with dedicated disk I can create a PVC just fine.

1. Create an RKE2 azure cluster (get to the azure cluster creation form in the UI). Pick azure for cloud provider. Provide proper config.
2. Set `--configure-cloud-routes=false` as extra KCM arg
3. When creating an Azure storage class, do not pick default shared disk - this is not support any longer.
4. Create a PVC - this will work.
5. Create a LB - this will work.

-----------------
The problems we have now are as follows. I will close this issue though, since this works.

1. The UI should remove the Shared option when setting up Azure Storage Class - it's no longer supported.
Bug: To be created (I will edit this message with a link to the bug)
2. The Rancher 2.6 docs need to very clearly mention how to set up Azure cloud provider for RKE2 clusters - it's way different from RKE1 because, as Hussein mentioned, we do not provide rke-tools with rke2 - and therefore the user must do much more work to make Azure cloud provider work on downstream rke2 clusters.
Docs issue: To be created (I will edit this message with a link to the bug)
