### ISSUE TITLE
Chart pictures do not appear in an airgapped setup, `500 error` in console for each chart

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34377]
**Rancher Server Setup**
- Rancher version:v2.6.0-rc5
- Installation option (Docker install/Helm Chart):helm
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):rke1
         Node Setup:
         Version: v1.21.4
- Proxy/Cert Details: valid certs

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream):issue occurs on both
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):custom (private nodes)

**Describe the bug**

* chart pictures/images/logos do not appear in an airgapped setup

**To Reproduce**
 
* deploy an airgapped setup  
  * optional: deploy a downstream cluster on the setup
* go to a cluster's charts

**Result**
chart pictures do not load

**Expected Result**

logos for charts should appear for airgapped setups

**Screenshots**

<img width="1790" alt="Screen Shot 2021-08-21 at 10 09 03 AM" src="https://user-images.githubusercontent.com/16691014/130329989-2e20c720-fc5d-48be-85b6-8bc287ab1bd6.png">

**Additional context**

the generic 'book' image is displayed for all chart logos instead

**Comment by vincent99** [comment]
The icons are URLs in the chart yaml that have to be downloaded to be shown.  No internet, no icons.  https://github.com/rancher/rancher/issues/32735
