### ISSUE TITLE
Route53 dns rules?

### ISSUE THREAD

**Issue by ronag** [rancher/rancher#3437]
I would like that all my load-balancer on all host are atomically registered with specific urls.

e.g.

domain1.mywebsite.com
domain2.mywebsite.com
domain3.mywebsite.com

etc... is this possible with the external-dns/route 53 catalog?

**Comment by vincent99** [comment]
The route53 service creates entries for `<service>.<stack>.<environment>.<hosted zone>`.  You can CNAME these to other names.  You can also have a single balancer service that has routing rules for each of those subdomains.

**Comment by ronag** [comment]
This is what I'm doing right now:

I manually map Route53 to my load balancer:

domain1.mywebsite.com -> LB -> domain1 stack
domain2.mywebsite.com -> LB -> domain2 stack
domain3.mywebsite.com -> LB -> domain3 stack

and then my LB forwards to the corresponding service

The problem I have with how I do things now is that i manually have to add the hosts to route53.

Can the Route53 Rancher package solve this?

The ` <service>.<stack>.<environment>.<hosted zone>` doesn't make much sense to me or how I should use that... I end up with 

`loadbalancer.loadbalancer.default.mywebsite.com` entries...

**Comment by rvion** [comment]
related related: https://github.com/rancher/rancher/issues/3440

**Comment by vincent99** [comment]
Create a single CNAME entry for `*.mywebsite.com` (most providers support star) to `loadbalancer.loadbalancer.default.mywebsite.com`.  Anylabel.yourwebsite.com will resolve to the IPs of the load balancer service, which can do service routing based on the requestsHost header.
