### ISSUE TITLE
OpenStack node driver uses a deprecated endpoint

### ISSUE THREAD

**Issue by ba-work** [rancher/rancher#34389]
**Rancher Server Setup**
- Rancher version: **2.5.9**
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): **RKE**
         Node Setup: **OpenStack instance with volume create and boot selected**
         Version: **N/A**
- Proxy/Cert Details: **N/A**

**Information about the Cluster**
- Kubernetes version: **1.20.8**
- Cluster Type (Local/Downstream): **Downstream**
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
   		**Infrastructure Provider = OpenStack**

**Describe the bug**

Using the OpenStack node driver with a template that has `bootFromVolume` selected and creating said volume will fail on certain OpenStack distros that do not ship deprecated endpoints.

The node driver is attempting to use the deprecated endpoint: [/os-volume_boot](https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/routes.py#L726), of which **[isn't even documented](https://github.com/gophercloud/gophercloud/issues/1974)**

**To Reproduce**
 
Using an OpenStack distro that does not ship the deprecated endpoint "/os-volume_boot", attempt to create a node from a node template that has `bootFromVolume` selected as well as creation of said volume.
**Result**
The node doesn't get created properly with the error: `Error creating machine: Error in driver  during machine creation: Expected HTTP response code [200 202] when  accessing [POST  https://<redacted>/v2.1/os-volumes_boot], but got 406  instead`

**Expected Result**

The node and volume get created properly, using the /servers endpoint

**Screenshots**

![image](https://user-images.githubusercontent.com/14022915/130470299-e0f0feca-3ea5-4d79-a11a-f56be017fab0.png)

**Additional context**

N/A

**Comment by vowywowy** [comment]
This is not fixed and should be reopened. 

gophercloud merged the fix for this in [June of 2020](https://github.com/gophercloud/gophercloud/pull/1973/files) with `v0.12.0`

[rancher/machine uses v0.7.0](https://github.com/rancher/machine/blob/master/go.mod#L31)

**Comment by ba-work** [comment]
This is not fixed and should be reopened.
 
gophercloud merged the fix for this in [June of 2020](https://github.com/gophercloud/gophercloud/pull/1973/files) with `v0.12.0`, where as [rancher/machine uses v0.7.0](https://github.com/rancher/machine/blob/master/go.mod?rgh-link-date=2022-02-16T19%3A43%3A40Z#L31)
