### ISSUE TITLE
Require image for ARM64 architecture 

### ISSUE THREAD

**Issue by odidev** [rancher/rancher#34386]
Hi team, 

I am trying to use the **rancher/server** image on the arm64 platform but it is not available for arm64 in [dockerhub](https://hub.docker.com/r/rancher/server/tags?page=1&ordering=last_updated). There is no dockerfile available for rancher/server on master branch of this git repository and it looks like the server module is removed after **tag v1.6.30**. 

Do you have any plans on releasing arm64 images? 

It will be helpful if the image is released for the ARM64 platform. If required, I am happy to contribute. But as a start, can you please provide me with Dockerfile source for rancher/server image?

**Comment by David-VTUK** [comment]
Are you deliberately looking for rancher/server images (for 1.x of Rancher, now retired) or for 2.x (in active development)

**Comment by cbron** [comment]
Rancher 1.x is not supported anymore. Rancher 2.x in general does not support arm64 at this time as there are several complications with it. There are other issues here that track adding support for it.
