### ISSUE TITLE
Can not redirect back to previous page using Github Oauth

### ISSUE THREAD

**Issue by link-duan** [rancher/rancher#34385]
**Rancher Server Setup**
- Rancher version: v2.5.5

**Describe the bug**

With Github-OAuth, Rancher cannot redirect to previous page. 

**To Reproduce**
 
1. configure with Github-Oauth
2. logout
2. open a Rancher page. eg. https://rancher.example.com/p/c-zt94r:p-vdvp7/workloads
3. login by Github-OAuth

**Result**
Rancher can not redirect to previous page (https://rancher.example.com/p/c-zt94r:p-vdvp7/workloads) after login.

**Expected Result**

Rancher redirect to previous page automatically.

**Additional context**

I found that Rancher write current page url to localStorage before redirect to login page.
![image](https://user-images.githubusercontent.com/20787331/130405959-0c0efca2-866d-44c3-a14a-c9c3fbf50205.png)

**BUT does not read it back after redirecting back from Github OAuth.**
![image](https://user-images.githubusercontent.com/20787331/130405905-6694d273-249a-4c71-b93c-7d1a42d30b9e.png)

**AND unset it after login**
![image](https://user-images.githubusercontent.com/20787331/130406480-113e730b-e955-45eb-88ea-e59e1626d9a9.png)

**Comment by link-duan** [comment]
For rancher/ui Issues tab is hidden, I open the issue here

**Comment by link-duan** [comment]
@vincent99 @nwmac

**Comment by nwmac** [comment]
All issues should go in rancher/dashboard.

The URL you are using is to the old Cluster Manager UI - using these older pages independently of the new Cluster Dashboard (e.g. not embedded) is not supported
