### ISSUE TITLE
Amazon EC2 node driver clusters are stuck in provisioning

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34381]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `8898bf8`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Info: 
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE1
         Node Setup: 3 nodes all roles
         Version: 1.21.4

**Information about the Cluster**
- Kubernetes version: `v1.21.3-rc6+rke2r2`
- Cluster Type (Local/Downstream): Downstream RKE2 EC2

**Describe the bug**
Amazon EC2 node driver clusters are stuck in provisioning

**To Reproduce**

- Deployed EC2 rke2 driver clusters with 1 node all roles.
- Cluster is stuck in Provisioning

<img width="1428" alt="Screen Shot 2021-08-22 at 4 10 45 PM" src="https://user-images.githubusercontent.com/26032343/130373019-347daa22-ad60-4aaf-b3f0-8bbf49122a73.png">

**Note:**

- But i was able to deploy a couple of clusters that came up Active in same Rancher setup. 
- VPC/Subnet in the node pool was being changed
- API request did have the VPC/SG sent by the UI
- No other error on the cluster or the machine pool
- Nothing obvious from journalctl logs

**Comment by deniseschannon** [comment]
Did you compare the VPC/Subnets to ensure the security groups had the same ports open and available? 

Is it a specifc VPC/subnet?

**Comment by deniseschannon** [comment]
@sowmyav27 We should really only be testing using the default rancher-machine security group that Rancher creates as well as testing if you come from an upgraded setup that had an old rancher-machine and you re-use it, it still works.

**Comment by thedadams** [comment]
I am not able to reproduce this. I tried using different VPCs and subnets, but was always able to successfully provision a cluster in EC2.

**Comment by sowmyav27** [comment]
On 2.6-head commit id: `b8a44fa`

Fresh Install use case.
I am not able to reproduce this issue.
