### ISSUE TITLE
An Azure AD user still can use kubeconfig while we disabled the user in AD

### ISSUE THREAD

**Issue by mabusaa** [rancher/rancher#34384]
**Rancher Server Setup**
- Rancher version: v2.5.5 
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):  AKS
         Node Setup: 4 workers
         Version: v2.5.5 
- Proxy/Cert Details: signed certificate, manual setup.

**Information about the Cluster**
- Kubernetes version: 1.18.10
- Cluster Type (Local/Downstream):  Local Imported
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported AKS cluster / rancher installed in-cluster
 

**Describe the bug**

An Azure AD user still can use kubeconfig while we disabled the user in AD.

**To Reproduce**
 
1. Configure rancher to use Azure AD.
2. Grant a user access to rancher project.
3. Sign in by the user.
4. Get the kubeconfig
5. Disable the user in Azure AD.

**Result**

Kubeconfig still works and user can access cluster using kubectl.

**Expected Result**

User should get a deny / forbidden access to cluster while his user is disabled.

**Screenshots**

**Additional context**

**Comment by David-VTUK** [comment]
Have you configured a Kubeconfig token TTL? https://rancher.com/docs/rancher/v2.x/en/api/api-tokens/#setting-ttl-on-kubeconfig-tokens

**Comment by mabusaa** [comment]
> Have you configured a Kubeconfig token TTL? https://rancher.com/docs/rancher/v2.x/en/api/api-tokens/#setting-ttl-on-kubeconfig-tokens

I did not know about this, thanks for sharing , i will try it.
