### ISSUE TITLE
Cluster health check failed: Failed to communicate with API server during namespace check

### ISSUE THREAD

**Issue by liujiabaoaa** [rancher/rancher#34388]
当前集群 Error 中...，在 API 准备就绪之前，直接与 API 交互的功能将不可用。

Cluster health check failed: Failed to communicate with API server during namespace check: Get "https://10.209.28.1:443/api/v1/namespaces/kube-system?timeout=45s": context deadline exceeded

![image](https://user-images.githubusercontent.com/26737572/130432421-b790dae5-8ad1-436d-bbb0-942c8ed1cc9b.png)

**Comment by liujiabaoaa** [comment]
镜像是 docker pull rancher/rancher:v2.5.9  版本。

**Comment by lizhenwei** [comment]
我也遇到了同样的问题，这个问题大概1年前就是这样了，从2.5.X版本就这样了，根本没人管

**Comment by VOCTERMA** [comment]
你好，你的问题应该是你的cattle-cluster-agent出现错误；请重新导入集群信息

**Comment by cuichenggen** [comment]
升级碰到一堆问题

**Comment by JannikZed** [comment]
<img width="1168" alt="Screenshot 2023-04-25 at 15 58 21" src="https://user-images.githubusercontent.com/7526174/234212402-58051ce5-f9c6-4670-beca-8993fefd825d.png">

When using the Kubectl from Rancher GUI, everything works: 
```
> kubectl get nodes
NAME             STATUS   ROLES                  AGE    VERSION
control-1        Ready    control-plane,master   427d   v1.22.7+rke2r2
etcd-1           Ready    etcd                   427d   v1.22.7+rke2r2
worker-basic-1   Ready    worker                 427d   v1.22.7+rke2r2
worker-basic-2   Ready    worker                 427d   v1.22.7+rke2r2
worker-basic-3   Ready    worker                 427d   v1.22.7+rke2r2
worker-basic-4   Ready    worker                 427d   v1.22.7+rke2r2
worker-basic-5   Ready    worker                 406d   v1.22.7+rke2r2
```

**Comment by VOCTERMA** [comment]
wait



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 25, 2023 16:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rancher/rancher] Cluster health check failed: Failed tocommunicate with API server during namespace check (#34388)




 

 
When using the Kubectl from Rancher GUI, everything works:
 &gt; kubectl get nodes NAME             STATUS   ROLES                  AGE    VERSION control-1        Ready    control-plane,master   427d   v1.22.7+rke2r2 etcd-1           Ready    etcd                   427d   v1.22.7+rke2r2 worker-basic-1   Ready    worker                 427d   v1.22.7+rke2r2 worker-basic-2   Ready    worker                 427d   v1.22.7+rke2r2 worker-basic-3   Ready    worker                 427d   v1.22.7+rke2r2 worker-basic-4   Ready    worker                 427d   v1.22.7+rke2r2 worker-basic-5   Ready    worker                 406d   v1.22.7+rke2r2

**Comment by VOCTERMA** [comment]
How long have you been using your rancher？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rancher/rancher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rancher/rancher] Cluster health check failed: Failed to communicate with API server during namespace check (#34388)





 

 
When using the Kubectl from Rancher GUI, everything works:
 &gt; kubectl get nodes NAME             STATUS   ROLES                  AGE    VERSION control-1        Ready    control-plane,master   427d   v1.22.7+rke2r2 etcd-1           Ready    etcd                   427d   v1.22.7+rke2r2 worker-basic-1   Ready    worker                 427d   v1.22.7+rke2r2 worker-basic-2   Ready    worker                 427d   v1.22.7+rke2r2 worker-basic-3   Ready    worker                 427d   v1.22.7+rke2r2 worker-basic-4   Ready    worker                 427d   v1.22.7+rke2r2 worker-basic-5   Ready    worker                 406d   v1.22.7+rke2r2

**Comment by JannikZed** [comment]
Really long .. since several years - upgrading and migrating it a lot. Seems like something got really broken when upgrading from 2.5.X to 2.6.9. The RKE2 cluster is one year old.

**Comment by VOCTERMA** [comment]
Can you ensure that your certificate has not expired




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rancher/rancher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rancher/rancher] Cluster health check failed: Failed to communicate with API server during namespace check (#34388)





 
Really long .. since several years - upgrading and migrating it a lot. Seems like something got really broken when upgrading from 2.5.X to 2.6.9. The RKE2 cluster is one year old.

**Comment by JannikZed** [comment]
@VOCTERMA do you know, how to do that? I thought, that RKE2 is handling the cert rotation automatically.

**Comment by JannikZed** [comment]
Sure! 
Downstream cluster:
```
> kubectl get pod -n cattle-system
NAME                                         READY   STATUS    RESTARTS      AGE
cattle-cluster-agent-669fcf7775-ckssv        1/1     Running   0             26h
cattle-cluster-agent-669fcf7775-vqt8d        1/1     Running   0             26h
dashboard-shell-g8887                        2/2     Running   0             4s
kube-api-auth-v2vmn                          1/1     Running   4 (61d ago)   321d
system-upgrade-controller-7b8d94c7f5-c5mv4   1/1     Running   1 (61d ago)   71d
> 
```

Rancher cluster:
> kubectl get pod -n cattle-system
NAME                                        READY   STATUS    RESTARTS      AGE
system-upgrade-controller-df77f4dfd-nzs4s   1/1     Running   1 (71d ago)   104d
rancher-webhook-66dcd7db66-8lf2n            1/1     Running   0             27h
rancher-b8d94c885-zvvnb                     1/1     Running   0             26h
rancher-b8d94c885-9jmbb                     1/1     Running   0             26h
dashboard-shell-g5v7g                       2/2     Running   0             23s
>

**Comment by VOCTERMA** [comment]
good,kubectl logs -f&nbsp;cattle-cluster-agent-669fcf7775-ckssv -n cattle-system
Execute the command and check if there is any error message in the log


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rancher/rancher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rancher/rancher] Cluster health check failed: Failed to communicate with API server during namespace check (#34388)





 
Sure!
 Downstream cluster:
 &gt; kubectl get pod -n cattle-system NAME                                         READY   STATUS    RESTARTS      AGE cattle-cluster-agent-669fcf7775-ckssv        1/1     Running   0             26h cattle-cluster-agent-669fcf7775-vqt8d        1/1     Running   0             26h dashboard-shell-g8887                        2/2     Running   0             4s kube-api-auth-v2vmn                          1/1     Running   4 (61d ago)   321d system-upgrade-controller-7b8d94c7f5-c5mv4   1/1     Running   1 (61d ago)   71d &gt;   
Rancher cluster:
  
kubectl get pod -n cattle-system
 NAME                                        READY   STATUS    RESTARTS      AGE
 system-upgrade-controller-df77f4dfd-nzs4s   1/1     Running   1 (71d ago)   104d
 rancher-webhook-66dcd7db66-8lf2n            1/1     Running   0             27h
 rancher-b8d94c885-zvvnb                     1/1     Running   0             26h
 rancher-b8d94c885-9jmbb                     1/1     Running   0             26h
 dashboard-shell-g5v7g                       2/2     Running   0             23s

**Comment by JannikZed** [comment]
no errors. A lot of logs like this: 
```
time="2023-04-25T08:18:15Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-k9kcs to namespace=calico-system"
time="2023-04-25T08:18:16Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-k9kcs to namespace=calico-system"
time="2023-04-25T08:18:16Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-k9kcs to namespace=calico-system"
time="2023-04-25T08:18:16Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-k9kcs to namespace=calico-system"
time="2023-04-25T08:18:17Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-k9kcs to namespace=calico-system"
time="2023-04-25T08:18:17Z" level=info msg="namespaceHandler: addProjectIDLabelToNamespace: adding label field.cattle.io/projectId=p-k9kcs to namespace=calico-system"
``` 
but no errors at all ..

**Comment by JannikZed** [comment]
not yet - should I start a separate issue for that?

**Comment by VOCTERMA** [comment]
If possible, in the k8s cluster, you can delete the&nbsp;cattle-cluster-agent pod pod and then import the cluster information again

You can import the k8s cluster information again：








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rancher/rancher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rancher/rancher] Cluster health check failed: Failed to communicate with API server during namespace check (#34388)





 
not yet - should I start a separate issue for that?

**Comment by JannikZed** [comment]
how can I reimport the cluster information? Won't the cluster be broken, when I delete the cattle-cluster-agent?

**Comment by VOCTERMA** [comment]
My k8s cluster was not created by the rancher, My original solution was to re import the cluster


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rancher/rancher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rancher/rancher] Cluster health check failed: Failed to communicate with API server during namespace check (#34388)





 
how can I reimport the cluster information? Won't the cluster be broken, when I delete the cattle-cluster-agent?

**Comment by VOCTERMA** [comment]
Are you a learning environment for Rancher and K8S




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rancher/rancher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rancher/rancher] Cluster health check failed: Failed to communicate with API server during namespace check (#34388)





 
how can I reimport the cluster information? Won't the cluster be broken, when I delete the cattle-cluster-agent?
