### ISSUE TITLE
[Backport - 2.5] Validate the latest cert-manager in Rancher server helm chart to the latest version

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#34383]
"Backport" of https://github.com/rancher/rancher/issues/34299 to validate if cert-manager 1.5.1 is working OK on 2.5.10 so documentation can be updated for v2.5 in addition to v2.6.

Upon successful validation create backport for https://github.com/rancher/docs/issues/3458

**Comment by jakefhyde** [comment]
# Fresh Install

## Environment

Install: `HA`
Rancher version: `v2.5-head`
Kubernetes version: `v1.20.9`

No issues noted. Lets Encrypt not tested, self-signed only.

## Commands

`kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml`
`helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.0.4`
`helm install --create-namespace --namespace cattle-system --set hostname=<HOSTNAME> rancher rancher-latest/rancher --version v2.5-head`
`kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.1/cert-manager.crds.yaml`
`helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.5.1`

# Upgrade `cert-mananger`

## Environment

Install: `HA`
Rancher version: `v2.5-head`
Kubernetes version: `v1.20.9`

## Commands

`kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.1/cert-manager.crds.yaml`
`helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.5.1`
`helm install --create-namespace --namespace cattle-system --set hostname=<HOSTNAME> rancher rancher-latest/rancher --version v2.5-head`

**Comment by jakefhyde** [comment]
Closed via [rancher/docs#3464](https://github.com/rancher/docs/pull/3464)
