### ISSUE TITLE
Updating existing cluster name in Edit Cluster does not work

### ISSUE THREAD

**Issue by frank-at-suse** [rancher/rancher#34390]
**Rancher Server Setup**
- Rancher version: v2.6-head
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.21.3+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

* Imported = Running kubectl apply onto an existing k8s cluster 

**Describe the bug**
When trying to rename a cluster, name does not update.  Verified via Dev Tools and Rancher logs that request is sent but no update posted (Chrome 92.0.4515.159).  Updating name of "local" cluster does work, however.

**To Reproduce**
Home -> Cluster Management -> Edit Config -> update Cluster Name

**Result**
Name of Cluster is not updated

**Expected Result**
Name of Cluster get updated

**Screenshots**

**Additional context**

**Comment by peteingithub** [comment]
Confirming the behavior on Rancher v2.6.0 and an imported k3s v1.21.4.
Using Firefox.

**Comment by De1taE1even** [comment]
Confirmed still an issue as of Rancher version 2.6.8
