### ISSUE TITLE
Unable to create VM

### ISSUE THREAD

**Issue by qrpike** [rancher/rancher#3439]
I thought there was an error trying to create the VM, but it turned out the port I was trying to map (port 22) was already in use on the host ( duh ). Would be nice to have some kind of error letting you know. I've had this happen with containers as well, which just kind of error out without knowing why.

**Comment by qrpike** [comment]
***UPDATE***: After creating the VM, the console will not work on any of the OS's. Also there is no SSH user passwords documented anywhere so I'm not sure how else to enable SSH or add keys to the vm.

**Comment by deniseschannon** [comment]
@qrpike VMs enablement is still in development stages. We've revealed it in the UI, but we haven't actually officially released it. It should be coming out in the next couple of releases. 

But for the ubuntu VM, the username/password is ubuntu/ubuntu.

**Comment by deniseschannon** [comment]
@qrpike I'm going to close this issue. It sounds like you were able to create the VM but just no password support. If you are using a different VM, please let me know and I can provide information on the password.
