### ISSUE TITLE
Provisioning RKE2 Digital Ocean clusters results in stuck bootstrap machine(s)

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34407]
**Rancher Server Setup**
- Rancher version: `v2.6-head` (`b43e4d955c8fdbb85bbbba1962937b0abbdf4a09`)
- Installation option (Docker install/Helm Chart): docker install
- Proxy/Cert Details: standard setup; UI accessed via URL given by `ngrok http 80`

**Information about the Cluster**
- Kubernetes version: v1.21.3 rc7 RKE2
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): single node digital ocean provisioned in the UI

**Issue Seen**
When provisioning Digital Ocean RKE2 clusters, MachineNodes are in "ScalingUp" state with the following log:
```
Non-ready bootstrap machine(s) <machine-name>: waiting for cluster agent to be available and join url to be available on bootstrap node
```

This has been stuck for at least 12 minutes; reproduced twice.

**To Reproduce**
1. Set up single node Docker locally
2. Set up DO account access in UI (token required)
3. Provision RKE2 single node downstream cluster with default version and settings

**Result**
Above log is seen

**Expected Result**
Cluster should be active

**Additional Context**
The nodes are provisioned and active/ready in the Digital Ocean UI

**Comment by kinarashah** [comment]
@nickgerace Not able to reproduce this on latest v2.6-head. What roles did you have for nodes? Do you have the logs of cluster-agent by any chance?

**Comment by nickgerace** [comment]
@kinarashah I'll try to reproduce it again and let you know.

**Comment by nickgerace** [comment]
This issue was configuration error. Will update this comment with more details and close the issue accordingly.
