### ISSUE TITLE
request: customizable dns record templates for dns services

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3440]
Could we manually configure the dns record template ?

instead of 

```
<service>.<stack>.<environment>.<base>
```

there is situations where we would like to have 

```
<service>_<stack>_<environment>.<base>
```

### Motivation:

https tls certificates may be complex to configure for several record deep dns record
__cloudflare, for example, don't fully support setting up ssl automatically for deep subdommains__

link to check the fact: https://support.cloudflare.com/hc/en-us/articles/200170566-Why-isn-t-SSL-working-for-my-site-

 > You're accessing a subdomain not covered by the CloudFlare-issued SSL certificate
CloudFlare-issued SSL certificates cover the root-level domain (eg- example.com) and one level of subdomains (eg- *.example.com). If you're attempting to access a second level of subdomains (eg- *.*.example.com) through CloudFlare using the CloudFlare-issued certificate, a HTTP 403 error will be seen in the browser as these host names are not present on the certificate. If you need to have SSL working for these type of host names you would either need to purchase your own SSL cert and upload it to us as a Custom SSL Certificate or grey-cloud this DNS record so the traffic goes directly to your origin server.

**Comment by vincent99** [comment]
The problem with this is that a single label can only be 63 characters, but there's no way for us to enforce that when it's a combination of 3 resources.

So then you need a rule for how you truncate them, and then there can be duplicates so you need another rule for truncating more and adding a number of something.  At the end the result is still a long ugly name, but also one that no human can accurately predict.

The intention is that you use the generated records to create CNAMEs for human-friendly domains.

**Comment by rvion** [comment]
It indeed makes sense, thanks for the arguments.
