### ISSUE TITLE
cluster not recoverable after adding base64 encoded ca.pem to `ca cert bundle` option when provisioning cluster (private registries -> advanced)

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34425]
**Rancher Server Setup**
- Rancher version:v2.6.0-rc6
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):rke1
         Node Setup:single
         Version:v1.21.3
- Proxy/Cert Details:self signed certs

**Information about the Cluster**
- Kubernetes version:v1.21.3-rke2r2
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):digital ocean

**Describe the bug**

when adding a mirror, there is an option for `ca cert bundle`. Upon adding this field and creating the cluster, rancher goes down with a panic in the logs `panic: runtime error: invalid memory address or nil pointer dereference [recovered]`

**To Reproduce**
 
* bring up a registry to use, which has necessary images for the setup. Use valid certs when creating the registry. base64-encode the ca.pem, we will use this when provisioning the cluster
* create a downstream cluster
  * when provisioning, go to the `private registries` section and enter the credentials _as a mirror_ (advanced option).  
  * copy your b64 encoded ca.pem into the `ca cert bundle` section
  * also enter all other relevant information (registry login info, cluster name, etc.)

**Result**
upon creating the cluster, rancher server will fail with this panic in the logs `panic: runtime error: invalid memory address or nil pointer dereference [recovered`
I also have the logs available in additional context section

**Expected Result**

even if this wasn't the correct way to mirror, it should not break all of rancher

**Screenshots**

**Additional context**

[panic_260rc6_34425.txt](https://github.com/rancher/rancher/files/7041954/panic_260rc6_34425.txt)

**Comment by thedadams** [comment]
I don't believe the CA bundle expects a base64 encoded string. I believe pasting the cert file as-is is the way to go.

That didn't cause the problem, but just wanted to mention for future testing.

**Comment by nickgerace** [comment]
This is available to test on v2.6.1-rc1

**Comment by slickwarren** [comment]
hmm, maybe this is a UI issue? When I copy and paste the cert (not base64 encoded) I get this error in the UI:
<img width="869" alt="Screen Shot 2021-09-17 at 10 33 29 AM" src="https://user-images.githubusercontent.com/16691014/133834808-0f76cd02-664d-462e-bc20-0347301be958.png">

However if I copy-paste the same cert, but base64 encoded, I am able to continue creating the cluster, which does not break rancher anymore.

**Comment by slickwarren** [comment]
Upon further investigation, it appears that this does take a base64 encoded cert.
