### ISSUE TITLE
rancher-monitoring-crd chart does not make use of global toleration settings

### ISSUE THREAD

**Issue by peregrinator** [rancher/rancher#34439]
When attempting to install the `rancher-monitoring` chart in a cluster that has taints on all of it's nodes we were unable to proceed because the `rancher-monitoring-crd` did not use toleration values that we set in the global key of the values.yml file.

It appears that the subcharts in the `rancher-monitoring` chart make use of these global tolerations in the following way:
https://github.com/rancher/charts/blob/f09ed8dd2d0df893f2652c2a2c93b32b111d78b6/charts/rancher-monitoring/rancher-monitoring/14.5.100/charts/grafana/templates/_pod.tpl#L395-L398

However the deployments in the `ranchering-monitroing-crd` chart do not: https://github.com/rancher/charts/blob/f09ed8dd2d0df893f2652c2a2c93b32b111d78b6/charts/rancher-monitoring/rancher-monitoring-crd/14.5.100/templates/jobs.yaml#L55

Without being able to add our own tolerations the only way we could deploy monitoring in our Rancher RKE cluster was to remove the taints from a node before deploying the chart and then add it back later.

There may be another solution that we missed but it appears that the `rancher-monitoring-crd` template should make use of user defined tolerations.

**Comment by aiyengar2** [comment]
Also, @peregrinator even with this fix, I don't believe our UI supports passing in values.yaml entries to the CRD chart at the current moment. 

So I'm not sure how you will pass in the tolerations, unless you plan on using another method for installing this CRD chart into your Rancher cluster (e.g. if you manage it via fleet or some other method).

**Comment by aiyengar2** [comment]
I believe that should work, but you will not be able to fix it before executing a fresh install.

**Comment by peregrinator** [comment]
That makes sense. I'll see if I can test whether the user values in the CRD are persistent with an upgrade to the main monitoring chart once this is in the wild I guess.

Thanks for the assistance!

**Comment by jiaqiluo** [comment]
### Root cause
the rancher-monitoring-crd chart does not expose the options for setting `nodeSelectors` and `tolerations`, so the crd chart might fail to install in the environment where those are needed. 

### What was fixed, or what changes have occurred
add those fields in the `values.yaml` so we can specify `nodeSelectors` and `tolerations` when installing the crd chart.

### Areas or cases that should be tested
- fresh install of the crd chart
- edit the crd app to add/remove  `nodeSelectors` and `tolerations` from the `values.yaml` file (could be done in the UI by editing the installed app)
- set `nodeSelectors` and `tolerations`  when upgrading from previous version

### What areas could experience regressions?
installation and upgrading should succeed 
 
### Are the repro steps accurate/minimal?
We need to use the Helm command-line tool to validate the issue because  Rancher Dashboard UI does not support setting values for the rancher-monitoring-crd chart at the moment.  see [this issue](https://github.com/rancher/dashboard/issues/4549)

**Comment by Auston-Ivison-Suse** [comment]
**Setup for Reproduction**
- Rancher version: v2.6-2
- Installation option (Docker install/Helm Chart):Docker
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version:v1.21.6-rancher1-1
- Cluster Type (Local/Downstream):Downstream aws/ec2
- 4 worker nodes, 1 etcd nodes, 1 control plane node
  - Each worker node should have a taint added to it during the configuration steps. For example: qa=test:noschedule


**Steps for Reproduction**
1. Go to the apps and marketplace, install monitoring and the previously mentioned version
2. While waiting for install to process you can check whether the pods are being deployed or whether the app "rancher-monitoring-crd" is working in the "installed apps" page. 
3. Once you see it's failed, use the kebab menu of the CRD to "edit/upgrade" 
4. On the yaml page add tolerations equivalent to the previously created taints. For example: 
```
tolerations:
- key: "qa"
  operator: "Equal"
  value: "test"
  effect: "NoSchedule"
  
```
5. Click save and return to the installed apps page. 
6. View the yaml of the crd from the kebab menu and notice the previously added tolerations are not listed.

**Setup For Validation**
- Rancher version: v2.6-head(0d14421)
- Installation option (Docker install/Helm Chart):Docker
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version:v1.22.4
- Cluster Type (Local/Downstream):Downstream aws/ec2
- 4 worker nodes, 1 etcd nodes, 1 control plane node
  - Each worker node should have a taint added to it during the configuration steps. For example: qa=test:noschedule


The following testcases validate the fix. 

**Fresh install of crd testcase:**
1. Download the kubeconfig files for the local cluster and the aforementioned downstream cluster. 
2. Download the charts-dev-v2.6 repository from the rancher repository
3. From either your file explorer go to charts-dev-v2.6-->charts-->rancher-monitoring-crd-->100.1.0+up19.0.3
4. within this directory you will edit the following yaml --> "values.yaml" _example below: _

```
tolerations:
- key: "qa"
  operator: "Equal"
  value: "test"
  effect: "NoSchedule"
```
5. now take the kubeconfig for your downstream cluster and copy it to the last mentioned path: charts-dev-v2.6-->charts-->rancher-monitoring-crd-->100.1.0+up19.0.3/<downstreamcluster.yaml> 
6. now run the command: 

`
export KUBECONFIG=<localcluster.yaml>
`
7. The previous command lets you run the following to install rancher-monitoring-crd via a helm install _example below:  _

`
helm install rancher-monitoring-crd . -n cattle-monitoring-system --create-namespace --kubeconfig <downstreamcluster.yaml>
`


**Edit Yaml From Ui**
1. In the downstream cluster with the aforementioned configuration try install monitoring v100.1.0+up19.0.3
2. Let rancher-monitoring-crd get to a failed state by waiting approximately 10 minutes. 
3. Once the app is in a failed state edit the yaml to have the appropriate tolerations and that should allow for the app to be installed. Tolerations listed below:

```
tolerations:
- key: "qa"
  operator: "Equal"
  value: "test"
  effect: "NoSchedule"
  
```

**Upgrading from Previous version Testcase**


1. In the downstream cluster with the aforementioned configuration, with an earlier version of monitoring installed, for example: 100.0.0+up16.6.0 go to the apps & marketplace and update the app to a later version. i.e. 100.1.0+up19.0.3
2. Let rancher-monitoring-crd get to a failed state by waiting approximately 10 minutes. 
3. Once the app is in a failed state edit the yaml to have the appropriate tolerations/node-selectors and that should allow for the app to be installed. Tolerations listed below:

```
tolerations:
- key: "qa"
  operator: "Equal"
  value: "test"
  effect: "NoSchedule"

```
