### ISSUE TITLE
users from ldap show `Unable to fetch user info`

### ISSUE THREAD

**Issue by robkooper** [rancher/rancher#34435]
**Rancher Server Setup**
- Rancher version: v2.5.9
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Info: RKE1
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 3 controller, 3 worker bootstrapped with terraform running centos
         Version: rancher-2.5.9
- Proxy/Cert Details: no proxy, running behind traefik

**Information about the Cluster**
- Kubernetes version: v1.20.9
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

When connecting to a LDAP server for users, when logged in as a local user they can not see any information about any of the users that come from the LDAP server. The local user will see the image below, they can also not search for any users in LDAP or add them using the API.

![image](https://user-images.githubusercontent.com/1580696/130710305-f1b7ce13-f181-442b-bfe7-328b3c1b071e.png)

**To Reproduce**
 
1. new install using helm
2. login with the admin user
3. create a new local user (admin rights)
4. login as new local user
5. create a openldap connection
6. login as a user using ldap (not one used in step 5)
7. logout and login as original admin user
5. look at users

**Result**

as local user can not see any ldap users names, can not add ldap users to rancher

**Expected Result**

The rancher server has credentials to the ldap server and thus should be able to do queries for users that have admin rights.

**Screenshots**

**Additional context**

**Comment by Brianalmeida** [comment]
I'm experiencing this issue, too. However, in 2.6.4, I'm unable to see this at all. Was this removed by chance?
