### ISSUE TITLE
Great issue reporting improvement : prefill issue body and title with usefull infos (version, template, etc.)

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3444]
#### try to click the following link:  [report issue](https://github.com/rancher/rancher/issues/new?body=%23%23%23%20Version%3A%0A%0A%7C%20Component%20%20%20%20%20%20%20%20%20%20%7C%20Version%20%20%20%20%20%20%7C%0A%7C-------------------%20%7C--------------%7C%0A%7C%20Rancher%20%20%20%20%20%20%20%20%20%20%20%20%7C%20v0.56.0-rc3%20%20%7C%0A%7C%20Cattle%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20v0.140.0%20%20%20%20%20%7C%0A%7C%20User%20Interface%20%20%20%20%20%7C%20v0.85.0%20%20%20%20%20%20%7C%0A%7C%20Rancher%20Compose%20%20%20%20%7C%20v0.7.1%20%20%20%20%20%20%20%7C%0A%0A%0A%23%23%23%20Problem%3A%0A%0A%23%23%23%20How%20to%20reproduce%0A)

Under the hood, it uses the `body` and `title` url params:

```
[report issue](https://github.com/rancher/rancher/issues/new?body=%7CComponent%20%7C%20Version%7C%0A%7C--------------%7C--------%7C%0A%7CRancher%20%7C%20v0.56.0-rc3%7C%0A%7CCattle%20%7C%20v0.140.0%7C%0A%7CUser%20Interface%20%7C%20%09v0.85.0%7C%0A%7CRancher%20Compose%20%7C%20v0.7.1%7C)
```

Here is an other example: https://github.com/rancher/rancher/issues/new?title=foo&body=bar

### Usefull for rancher "File an issue“ link

![image](https://cloud.githubusercontent.com/assets/2150990/12649642/c27e4ce0-c5df-11e5-8ea0-d77bf4042101.png)

We can even imagine having several links like: "report an UI bug" / "report functionality bug"

you can use: http://meyerweb.com/eric/tools/dencoder/ to generate proper url escaped multiline templates, eg

```
### Version:

| Component          | Version      |
|------------------- |--------------|
| Rancher            | v0.56.0-rc3  |
| Cattle             | v0.140.0     |
| User Interface     | v0.85.0      |
| Rancher Compose    | v0.7.1       |


### Problem:

### How to reproduce


```
gives:

```
%23%23%23%20Version%3A%0A%0A%7C%20Component%20%20%20%20%20%20%20%20%20%20%7C%20Version%20%20%20%20%20%20%7C%0A%7C-------------------%20%7C--------------%7C%0A%7C%20Rancher%20%20%20%20%20%20%20%20%20%20%20%20%7C%20v0.56.0-rc3%20%20%7C%0A%7C%20Cattle%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20v0.140.0%20%20%20%20%20%7C%0A%7C%20User%20Interface%20%20%20%20%20%7C%20v0.85.0%20%20%20%20%20%20%7C%0A%7C%20Rancher%20Compose%20%20%20%20%7C%20v0.7.1%20%20%20%20%20%20%20%7C%0A%0A%0A%23%23%23%20Problem%3A%0A%0A%23%23%23%20How%20to%20reproduce%0A
```

**Comment by rvion** [comment]
Other possible improvements to bug reporting would be : 

 - adding a contributing guide https://github.com/rancher/rancher/issues/3407
 - print an url with proper body prefilled with ```cli version``` and  ```command launched``` along other usefull details when the CLI crash, or when the server crash

**Comment by vincent99** [comment]
That's a good idea, we use it on the individual repo READMEs but not on the UI button..

**Comment by tfiduccia** [comment]
The File a Bug on bottom of screen is fixed.  But we should do the same thing for the "File an issue on GitHub" link in the help screen.
Sending back to Vincent..

**Comment by tfiduccia** [comment]
Version - master UI 2/4
Verified fixed
