### ISSUE TITLE
v0.56.0-rc3: hours after the convoy-gluster stack upgrade, UI still says "in progress"

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3445]
Several hours after convoy-gluster stack upgrade, 

  1. The "Upgrade in progress" disabled button do not disapear
  2. Icons do not revert to their original apearance

![image](https://cloud.githubusercontent.com/assets/2150990/12650262/72e72d8e-c5e2-11e5-8802-31e6d232c388.png)

**Comment by rvion** [comment]
Oh, I found the "finishing updgrade" button within the dedicated page for the stack.

- "rancher.dev/apps" -> button not visible
- "rancher.dev/apps/1e6" -> button visible (ie6 being the convoy-gluster stack id)

I don't know if I should close this issue or not, because I think there is a small UI problem here

**Comment by vincent99** [comment]
Maybe the wording isn't clear here, but the point of the button is it's not going to be looking for upgrades because you're in the middle of one (until you finish the upgrade).
