### ISSUE TITLE
[v2.5.10] Backport: "unable to create impersonator account: error getting service account token: serviceaccounts \"cattle-impersonation-system/cattle-impersonation-user-dxx4g\" not found - Error seen for Monitoring and Istio v1 charts and when using downloaded kubeconfig

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#34454]
https://github.com/rancher/rancher/issues/34187

**Comment by anupama2501** [comment]
Verified on v2.5-head 6b04f9b3

- Installed rancher on v2.5.9 
- Enabled openldap auth 
- As a standard user, created a downstream rke1 node driver 3 worker, 1etcd, 1cp cluster
- Installed istio v1 and monitoring v1 - verified all workloads and app have come active.
- Ran the v1 istio P1 test cases on the cluster.
- Upgraded to v2.5-head 
- Verified the istio kiali and jaeger, monitoring grafana and prometheus URLs as standard user and admin
- Verified no errors seen and all the graphs loaded as expected.
