### ISSUE TITLE
[2.5] [Backport] service "rancher-webhook" not found error when helm install rancher 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#34453]
backport the fix for the issue https://github.com/rancher/rancher/issues/33988

**Comment by jiaqiluo** [comment]
available in the chart `rancher-webhook 0.1.200-rc1+up0.1.2-rc1`

**Comment by brendarearden** [comment]
available to test in v2.5.10-rc1

**Comment by anupama2501** [comment]
Verified on rancher version v2.5.10-rc1

1. Create 3 nodes and performed rke up
2. Once the cluster is up, installed certs and installed rancher via helm
`helm install rancher rancher-latest/rancher --version 2.5.10-rc1 --namespace cattle-system --set hostname=anupama-25.qa.rancher.space --create-namespace --wait`
3. Rancher server has come up fine and no errors were seen. 
4. All the projects in the system project are up and running.
