### ISSUE TITLE
Attempting to restore a local snapshot a second time has no effect

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#34462]
**Summary:**

Local snapshot restoration now works thanks to the fix in https://github.com/rancher/rancher/issues/34451 (PR https://github.com/rancher/rancher/pull/34441).

However, I encounter unusual behavior if I attempt to restore from the local snapshot a second time. The frontend appears to send a proper PUT request to invoke restoration and the server appears to respond appropriately. However I observe no action taking place in the UI (visually) when I restore a 2nd time. Further, nothing observed in any of: rancher server logs, rke2-server logs on the node, rancher-system-agent logs on the node, and no change in fleet plan or in fleet pod logs on local cluster. The UI appears to be doing everything correctly, just the backend does not respond upon a 2nd request to perform snapshot restore action in the UI.

**Environment:**
Rancher version: v2.6-head `b7c440be0` pulled at 8/25/21 8:20 am Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.4-rc1+rke2r1

**Steps to Reproduce:**
1. Provision a 1-node RKE2 cluster in Rancher. In my case I just made a simple 1-node cluster with the Digital Ocean node driver. Defaults for everything (this will use local snapshots).
2. Take a snapshot in the UI. Then, once it is fully complete restore in the UI. This works.
Note: confirmed plan is updated, tells rke2 to shutdown and run killall script and restore with cluster-reset, etc as expected.
3. Now, once the restore is fully complete, try to restore again in the UI. Nothing happens. The UI is working - it sent the correct PUT request to perform the snapshot again and the server response appears normal as well. Same as the first time basically.
Note: plan is NOT updated, does NOT tell rke2 to shutdown and run killall script and restore again. It should.
 
**Expected Result:**
I expected the restore process to be kicked off again.

**Actual Result:**
The restore process is not kicked off when I try to restore from the same snapshot a 2nd or nth time.

**Additional Info:**
I diffed my first restore request in the UI to my second request. I don't see anything significant that stands out. Both restore requests have this relevant snippet:
```
            "etcdSnapshotRestore": {
                "generation": 1,
                "createdAt": "2021-08-25T18:05:18Z",
                "name": "on-demand-dave-localsnaptest2-pool1-e08b88f9-f9klp-1629914718",
                "size": 11071520,
                "nodeName": "dave-localsnaptest2-pool1-e08b88f9-f9klp"
            },
```
Just the first time it worked, the second time and nth additional times it does not.

And I checked just about everything I could think of -- the UI appears to be working correctly sending this request to the server. The server response to this PUT request to restore the snapshot appears normal in both cases as well. When I diff those responses I also see no significant difference.

I see nothing happen in rancher server logs, the node's rke2-server logs, the node's rancher-system-agent logs, and I don't see the fleet plan change. I also checked fleet pods on the local cluster and see no change in logs there as well. It's as if the UI never sent anything to the server to invoke this restoration process (but it did). I'm not quite sure what else I can do to investigate further before sending this to dev. Please let me know if there is anything I can do to help.

**Comment by snasovich** [comment]
@vincent99 @gaktive @nwmac , please see comment above and reply here.

**Comment by davidnuzik** [comment]
Blocked by new UI bug that prevents RKE2 snapshot restoration: https://github.com/rancher/dashboard/issues/4221

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `223ec88` pulled at 9/22/21 6:20pm
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.4+rke2r2
 
**Validation steps:**

1. Create a 1 node RKE2 cluster (DigitalOcean node driver in my case).
2. Take a snapshot. Wait for this to fully complete.
3. Restore the snapshot this succeeds. Wait for this to completely finish.
4. Restore again from the same snapshot. This now works - I also see the generation number and observed generation number increase by 1 when inspecting the network PUT on the 2nd restore.
