### ISSUE TITLE
Feature charts: Add max of 2.5.99 on all 2.5.x charts, add min of 2.6.0 on all 2.6.x charts.

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#34479]
We had previously done this with k8s min/max, but that has proven to not be robust enough. 
This only applies to the dev and release 2.6 branches, not the 2.5 branches, those will continue as-is. 

- [x] All charts not introduced in 2.6.0+ should have a max of 2.5.99 on them. Only exception would be if a chart was not released since 2.5.x, but I don't believe that is the case. 
- [x] ~All new chart versions being introduced should have min of 2.6.0~, nvm, only doing this going forward in 2.6.1+

**Comment by jiaqiluo** [comment]
An example of the annotation 
```
catalog.cattle.io/rancher-version: ">= 2.5.0-alpha <2.6.0" # Chart will only be available for users in the specified Rancher version(s)
```

The logic is implemented in rancher:
https://github.com/rancher/rancher/blob/release/v2.6/pkg/catalogv2/content/content.go#L212

**Comment by cbron** [comment]
@brendarearden can you add a max of 2.6.1 to Longhorn 100.0.0+up1.1.2.tgz along with its min.

**Comment by cbron** [comment]
> @brendarearden can you add a max of 2.6.1 to Longhorn 100.0.0+up1.1.2.tgz along with its min.

Scratch that, no max for longhorn right now

**Comment by cbron** [comment]
@Jono-SUSE-Rancher this might go over code freeze, but its more of a release task. It touches production charts so I don't want to rush to merge it in today. Would rather do it Monday.

**Comment by cbron** [comment]
Merged
