### ISSUE TITLE
MINOR: Timeout when tried to updated host label.

### ISSUE THREAD

**Issue by blaggacao** [rancher/rancher#3447]
I yesterday experienced a series of timeouts when I was trying to update a host label via the UI. Rancher Server is running remote on Digital Ocean in the US, host is in Bogota, Colombia. I updated it via the API frontend, which worked.

Today I didn't have any problem updating labels for the same host through the UI.

If the relevant parties consumed this report, I think it is closable straight away, as it is not really reproducible.

Thanks and keep up the good work.

**Comment by vincent99** [comment]
The last release put a timeout of 10 second on AJAX/API calls, which is apparently not long enough for some things/bad networks.  Changed to 30 seconds next release.

**Comment by tfiduccia** [comment]
version - master 1/29
Verified fixed
