### ISSUE TITLE
Failed to communicate with API server when etcd role node is removed

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#34488]
**Rancher Server Setup**
- Rancher version: `rancher/rancher:v2.6-head 607fcdd`
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Info: 
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE (local), DO RKE2 (downstream)
         Version: v1.20.9 (local), v1.21.4+rke2r1 (ds)
         Node Setup: single-node custom RKE (local) + DO RKE2 (downstream) containing:
		- **master1** pool - 1 node with etcd and cp roles
		- **master2** pool - 2 nodes with etcd and cp roles
		- **worker1** pool - 1 node with worker role
		- **worker2** pool - 2 nodes with worker role
- Proxy/Cert Details: none / rancher-generated

**Describe the bug**
Found when testing https://github.com/rancher/dashboard/issues/3834

When user has two pools with `cp+etcd` nodes (+ extra workers pool) and deletes one of them the cluster should be `Active` after a while again. The cluster becomes unreachable instead.

**To Reproduce**
* deploy a local rancher cluster
* provision DO RKE2 cluster with 4 pools described above with default values
* wait until the RKE2 cluster is Ready and `Active`
* go to `Cluster Management` and do `Edit Config` on DO RKE2 cluster
* delete **master2** pool (containing 2 nodes both with `cp + etcd` role) by selecting the pool and pressing the minus-sign, press `Save` button.

**Result**
The RKE2 cluster will end up in `Error` state and becomes unreachable from dashboard, there is Error message visible:
`Cluster health check failed: Failed to communicate with API server during namespace check: Get "https://10.43.0.1:443/api/v1/namespaces/kube-system?timeout=45s": dial tcp 10.43.0.1:443: connect: connection refused`
![pool-removal-failure](https://user-images.githubusercontent.com/12828077/130973194-95db683a-c7f6-4cd7-a9ec-db33ba8e4048.png)

**Expected Result**
The cluster should become `Active` again after a while.

**Additional context**
* the same approach worked okay when user delete a pool with worker nodes as there is still another pool with one worker. The state of the cluster turns to `Provisioning` and then `Active` again after **worker2** pool removal.
* the nodes from the deleted pool(s) are getting deleted from DO Cloud correctly
* the same issue reproduced on AWS EC2 RKE2 cluster as well

**Screenshot**
This is how it looks before the cluster became unreachable (pool **worker2** with extra worker nodes has been deleted before successfully):
![deleting-nodes-in-progress](https://user-images.githubusercontent.com/12828077/130977157-2b69a390-800d-4a7b-8234-7d81c5b8bb82.png)

**Comment by snasovich** [comment]
Few additional issues on k3s / RKE2 side will be created that are needed for this.

**Comment by Oats87** [comment]
The fix will require 
RKE2 `v1.21.5+rke2r1` or newer to be able to remove etcd nodes
K3s `v1.21.5+k3s1` or newer to be able to remove etcd nodes

**Comment by snasovich** [comment]
@Oats87 , is this one still in review or ready to be tested? If it's the former, what PRs / issues are we waiting on?

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment


| Component               | Version / Type                         |
| ----------------------- | -------------------------------------- |
| Rancher version         | v2.6.2                                 |
| Rancher cluster type    | Helm HA                                |
| Helm version            | v2.16.8-rancher1                       |
| Downstream cluster type | RKE2 Digital Ocean                     |
| Downstream K8s version  | v1.21.6+rke2r1                         |
| Browser type            | Google Chrome                          |
| Browser version         | 96.0.4664.45 (Official Build) (x86_64) |

## Reproduction steps

1. Create Digital Ocean RKE2 downstream cluster with the following
    - main1 pool - 1 node with etcd and cp roles
    - main2 pool - **2 nodes** with etcd and cp roles
    - work1 pool - 1 node with worker role
    - work2 pool - **2 nodes** with worker role
2. Wait until the RKE2 cluster has a state of `Active`
3. `Edit Config` on the RKE2 Digital Ocean cluster
4. Delete the `main2` pool which contains 2 nodes both with cp + etcd roles
5. Press the `Save` button

**Result**

The RKE2 cluster will eventually go into an error state with the following warning. See attached screenshot below labeled `A1`.

```txt
Cluster health check failed: Failed to communicate with API server during namespace check: Get "https://[IP_ADDRESS]/api/v1/namespaces/kube-system?timeout=45s": context deadline exceeded
```



<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-96e243841bdad2743835e31ee8a85a5ffce093de-head |
| Rancher cluster type    | Helm HA                                            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | RKE2 Digital Ocean                                 |
| Downstream K8s version  | v1.21.5+rke2r1                                     |
| Browser type            | Google Chrome                                      |
| Browser version         | 96.0.4664.45 (Official Build) (x86_64)             |

## Validation steps

1. Create Digital Ocean RKE2 downstream cluster with the following
    - main1 pool - 1 node with etcd and cp roles
    - main2 pool - **2 nodes** with etcd and cp roles
    - work1 pool - 1 node with worker role
    - work2 pool - **2 nodes** with worker role
2. Wait until the RKE2 cluster has a state of `Active`
3. `Edit Config` on the RKE2 Digital Ocean cluster
4. Delete the `main2` pool which contains 2 nodes both with cp + etcd roles
5. Press the `Save` button

**Result**

No errors and the cluster is still in `Active` state.
