### ISSUE TITLE
[Backport] [rancher-backup] resourceSet is left in the old version if the rancher-backup app is already the latest in a upgrade-rollback-upgrade scenario

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#34496]
backport   https://github.com/rancher/rancher/issues/34495

**Comment by cbron** [comment]
Good chance we'll need to bump this, as solution may be large.

**Comment by Jono-SUSE-Rancher** [comment]
If we can't fit the backport into 2.5.10, then let's go ahead and bump it to a more reasonable milestone. v2.6.2 would be my guess.

**Comment by MKlimuszka** [comment]
Assigning to Prachi since Anupama isn't on this team anymore.

**Comment by prachidamle** [comment]
@MKlimuszka @SheilaghM  Looks like the original ticket is still open and scoped for v2.6.4 - When that is fixed and tested we can backport it to 2.5.x

**Comment by Jono-SUSE-Rancher** [comment]
FYI - v2.5.12 is going to likely be the last _maintenance_ release for 2.5x since it's EOM was January 5th, 2022. We will likely need users to upgrade to 2.6x in order to resolve this.

@sowmyav27 Do you see any reason we can't close this?

**Comment by MKlimuszka** [comment]
There hasn't been the opportunity to fix the original issue, and the original issue might be fixed by our updated cleanup scripts, so we'll have to re-validate it.

**Comment by SheilaghM** [comment]
@superseb - will you please look at this? It was fixed in 2.6.4 so we should backport to 2.5.x because it will affect upgrade.  _**Can**_ we get this in for the 2.5.16 release by July 1 dev complete?  If not, let's queue up for 2.5.17.

**Comment by superseb** [comment]
@SheilaghM https://github.com/rancher/rancher/issues/34495 is still open and has milestone `v2.6.x`, what issue was closed where it was fixed for 2.6.4?

**Comment by SheilaghM** [comment]
@superseb - I do not remember where I got the info or the idea the original was fixed.  Yes, please work on that one.  If we can't get it into 2.6.6, let's queue it for 2.7.

**Comment by eliyamlevy** [comment]
See above mention ^
