### ISSUE TITLE
[RKE2 provisioning] unable to add dedicated worker node to cluster using amazon EC2 as the provider

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34497]
**Rancher Server Setup**
- Rancher version: v2.6.0-rc7
- Installation option (Docker install/Helm Chart):helm
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):rke1
         Node Setup:
         Version: v1.21.4
- Proxy/Cert Details:valid certs (letsencrypt)

**Information about the Cluster**
- Kubernetes version: v1.21.4-rc1+rke2r1
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):infrastructure provider, AWS
Security Group: default (rancher-nodes)

**Describe the bug**

user's dedicated worker node is not registering with the cluster. it is created in the backend, and other node types are registering.

**To Reproduce**
 
* using ec2 as the provider, create 3 separate node pools each with 1 role each
 * wait for the cluster to come to `active`

**Result**
* etcd and control plane nodes come to active, but the worker node is stuck in state `waiting for node to be registered with Kubernetes`

**Expected Result**

all nodes should register with the cluster

**Screenshots**

**Additional context**

* the worker node logs are empty for `rke2-server`
* other providers like DO come up fine with dedicated nodes

**Comment by sowmyav27** [comment]
**on 2.6.0-rc9**

- Deployed an RKE2 AWS cluster - 1 etcd, 1 cp and 1 worker nodes
- Worker node is still stuck in Provisioning state
- `journalctl -u rancher-system-agent` logs

```
Aug 29 05:23:12 ip-172-31-13-77 rancher-system-agent[1348]: time="2021-08-29T05:23:12Z" level=debug msg="[K8s] writing an applied checksum value of ceacbd5533388438e9a509325d945942b91df2fad36a0a504aef1cf3aeea4c65 to the remote plan"
Aug 29 05:23:12 ip-172-31-13-77 rancher-system-agent[1348]: time="2021-08-29T05:23:12Z" level=debug msg="[K8s] Enqueueing after 5.000000 seconds"
Aug 29 05:23:12 ip-172-31-13-77 rancher-system-agent[1348]: time="2021-08-29T05:23:12Z" level=debug msg="[K8s] secret data/string-data did not change, not updating secret"
Aug 29 05:23:17 ip-172-31-13-77 rancher-system-agent[1348]: time="2021-08-29T05:23:17Z" level=debug msg="[K8s] Processing secret sowmya-rke2-bootstrap-template-9rvns-machine-plan in namespace fleet-default at generation 0 with resource v>
Aug 29 05:23:17 ip-172-31-13-77 rancher-system-agent[1348]: time="2021-08-29T05:23:17Z" level=debug msg="[K8s] Calculated checksum to be ceacbd5533388438e9a509325d945942b91df2fad36a0a504aef1cf3aeea4c65"
Aug 29 05:23:17 ip-172-31-13-77 rancher-system-agent[1348]: time="2021-08-29T05:23:17Z" level=debug msg="[K8s] Remote plan had an applied checksum value of ceacbd5533388438e9a509325d945942b91df2fad36a0a504aef1cf3aeea4c65"
Aug 29 05:23:17 ip-172-31-13-77 rancher-system-agent[1348]: time="2021-08-29T05:23:17Z" level=debug msg="[K8s] Applied checksum was the same as the plan from remote. Not applying."
Aug 29 05:23:17 ip-172-31-13-77 rancher-system-agent[1348]: time="2021-08-29T05:23:17Z" level=debug msg="[K8s] needsApplied was false, not applying"
Aug 29 05:23:17 ip-172-31-13-77 rancher-system-agent[1348]: time="2021-08-29T05:23:17Z" level=debug msg="[K8s] writing an applied checksum value of ceacbd5533388438e9a509325d945942b91df2fad36a0a504aef1cf3aeea4c65 to the remote plan"
Aug 29 05:23:17 ip-172-31-13-77 rancher-system-agent[1348]: time="2021-08-29T05:23:17Z" level=debug msg="[K8s] Enqueueing after 5.000000 seconds"
Aug 29 05:23:17 ip-172-31-13-77 rancher-system-agent[1348]: time="2021-08-29T05:23:17Z" level=debug msg="[K8s] secret data/string-data did not change, not updating secret"
```

**Comment by davidnuzik** [comment]
Can confirm - still broken, v2.6-head `5f5f0ae57` pulled at 11:00am pacific
Blocking upgrade testing

**Comment by slickwarren** [comment]
tested on v2.6-head (1ae31b1):
* provision multinode rke2 cluster using amazonec2 as the provider (dedicated and mixed roles) -- pass
* provision dedicated node-per-role  using amazonec2 as the provider -- pass
* provision all-roles node  using amazonec2 as the provider -- pass
