### ISSUE TITLE
[Rancher Webhook] pre-delete-hook-psp is created when preDelete.enabled is set to false

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#34508]
Since the check for the value of `preDelete.enabled` is missing in the template for the pre-delete-hook-psp, it will be created even `preDelete.enabled` is false. 

But because the chart is managed by Rancher internally, and `preDelete.enabled` is true by default, this missing check has no effect on rancher-webhook's functionality.

**Comment by cbron** [comment]
Are there any other webhook changes going into 2.6.1 ? If not I actually think we should wait for 2.6.2.

**Comment by jiaqiluo** [comment]
Move this to 2.6.2 since there are no other webhook changes.

**Comment by jiaqiluo** [comment]
can be tested in rancher-webhook chart v0.2.1

**Comment by jiaqiluo** [comment]
**Prerequisite**:
- add the dev-v2.6 branch as a helm repo
```
helm repo add rancher-dev-v2.6 https://raw.githubusercontent.com/rancher/charts/dev-v2.6/
helm repo update
helm search repo  rancher-webhook
```

**To reproduce**:
run
```
helm template  rancher-webhook --set preDelete.enabled=false rancher-dev-v2.6/rancher-webhook --version 1.0.0+up0.2.0 --dry-run 
```
there should be a template for the PodSecurityPolicy in the output, such like
```
---
# Source: rancher-webhook/templates/pre-delete-hook-psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: rancher-webhook-pre-delete
...
```

**To validate the fix**:
run the same command but pass the new version 
```
helm template  rancher-webhook --set preDelete.enabled=false rancher-dev-v2.6/rancher-webhook --version 1.0.1+up0.2.1 --dry-run 
```
The PodSecurityPolicy should NOT be in the output.

**Comment by slickwarren** [comment]
following the above steps, i was able to verify that the PodSecurityPolicy doesn't show in the new version
