### ISSUE TITLE
Restricted admin cannot modify any RKE2 cluster it did not create - not an issue for RKE1 clusters

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#34509]
**Summary:**
A restricted admin is unable to edit any RKE2 cluster it did not create.
The restricted admin can edit any RKE1 cluster without any issues.

**Environment:**
Rancher version: v2.6-head `607fcdde6` pulled at 8/26/21 8:58 am Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.4-rc1+rke2r1

**Steps to Reproduce:**
1. As the `admin` user, create an RKE2 cluster.
2. Create a `restricted` user - assign it the restricted admin role.
3. Log in as the `restricted` admin user, try to edit this RKE2 cluster - you are not allowed to access the machine pools.
![image](https://user-images.githubusercontent.com/45179589/131171127-125bc82e-cd99-4915-b823-8e604a51acd0.png)
 
You therefore cannot scale pools/modify them.

4. Try to edit something - try to add a node label and hit the save button. This will not work with an error in the UI "I.config is null"
![image](https://user-images.githubusercontent.com/45179589/131171208-e6bdbfba-540d-4df6-b020-0dfaecdf92f4.png)

**Expected Result:**
I expected that as the restricted admin I would be able to edit any cluster.

**Actual Result:**
The restricted admin cannot edit any RKE2 clusters that it did not create itself. If you attempt to edit an RKE2 cluster the restricted admin created this will work. Also, the restricted admin can edit any RKE1 cluster without any issues even if it did not create it.

**Additional Info:**
The 403 message response upon the restricted admin trying to edit a cluster it did not create is:
```
"digitaloceanconfigs.rke-machine-config.cattle.io \"nc-dave-standardcreated-pool1-lpb56\" is forbidden: User \"u-x92hd\" cannot get resource \"digitaloceanconfigs\" in API group \"rke-machine-config.cattle.io\" in the namespace \"fleet-default\""
```
(upon attempt to GET /v1/rke-machine-config.cattle.io.digitaloceanconfigs/fleet-default/nc-dave-standardcreated-pool1-lpb56 )

When trying to submit our modified cluster form, nothing is sent - the UI blocks the attempt to PUT to update the cluster. Nothing useful in the web browser dev console I just see "Applying hook save-machine-pools" entry when I click the save button (and that "I.config is null" error)

**Comment by slickwarren** [comment]
on 2.6-head (dfe795a) - - same commit as https://github.com/rancher/rancher/pull/34517 
Following Dave's repro instructions, I see a similar (but I think expected) error 
<img width="602" alt="Screen Shot 2021-08-27 at 6 27 02 PM" src="https://user-images.githubusercontent.com/16691014/131201912-ddaa6d9c-26b9-4f7e-b6e9-2bca4ccf1f3d.png">

with 403 error 
```
secrets \"cc-dj875\" is forbidden: User \"u-kdhsd\" cannot get resource \"secrets\" in API group \"\" in the namespace \"cattle-global-data\
```

This is very similar to rke1/ember's flow (restricted admin can't use the node template that admin created). In RKE1, restricted admin would need to create a new node template to use and edit the cluster that admin created. Now with RKE2, restricted admin must create its own cloud credential to use with the rke2 cluster that admin created. 

I verified that; if restricted admin creates its own secret (for DO in this case), it can modify the rke2 cluster created by admin.
