### ISSUE TITLE
Provision previous versions of RKE1 with Rancher

### ISSUE THREAD

**Issue by peteingithub** [rancher/rancher#34510]
**Is your feature request related to a problem? Please describe.**
It used to be (2.5.x and and previous rc releases up to rc6) possible to deploy previous RKE1 versions with Rancher using the `Edit as YAML` button.

**Describe the solution you'd like**
Enter previous release, e.g 1.21.3-rancher1-1 in the YAML box.

**Describe alternatives you've considered**

**Additional context**

**Comment by peteingithub** [comment]
Anyone?

**Comment by superseb** [comment]
Cluster Manager -> Cluster -> Edit Config -> Edit as YAML, is this the path you are using? What is not working? What did you put in what isn't working now? I assume you are on v2.6.0?

**Comment by peteingithub** [comment]
This was originally on rc7 or rc8. 

The path is: Cluster Management -> Create -> Edit as YAML ->  kubernetes_version: 1.21.4-rancher1-1 (the newest is 1.21.5).

It seems to be working in 2.6.0.
