### ISSUE TITLE
Rancher in infinite restart loop - disabled rke2 flag a 2nd time and stuck in this loop

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#34520]
**Summary:**
Please note: I am extremely busy with higher priority 2.6.0 testing so I did not investigate this at all. I usually like to provide more detailed info and look into the issue but I don't have time. So I'm creating this issue just to track and for awareness - I could look into it more later.

I had a v2.6-head cluster up 8/27 and was doing lots of rbac testing. I disabled the rke2 flag once on accident this worked fine rancher came back up after restart. I enabled it again. 
I later disabled it a 2nd time and now the rancher box is unusable and in an infinite loop it will keep restarting with errors like:

```
2021/08/27 21:40:34 [ERROR] unable to update feature rke2 in initialize features: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": dial tcp 10.43.96.41:443: connect: no route to host
2021/08/27 21:40:40 [ERROR] unable to update feature unsupported-storage-drivers in initialize features: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": dial tcp 10.43.96.41:443: connect: no route to host
2021/08/27 21:40:46 [ERROR] unable to update feature multi-cluster-management in initialize features: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": dial tcp 10.43.96.41:443: connect: no route to host
2021/08/27 21:41:02 [FATAL] feature flag [rke2] value has changed, rancher must be restarted
```

**Environment:**
Rancher version: v2.6-head `6d10a6d50` pulled at 8/27/21 11:45 am Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2 and rke1 (various clusters where imported, custom, node driver created in Rancher)
Downstream K8s version: various

**Steps to Reproduce:**
1. My rancher box had many clusters in it - some rke1 and rke2 imported, a couple node driver ones, etc. I disabled the rke2 feature flag on accident (I wasn't ready to actually test with this disabled just yet) but this worked; rancher came back up after restart.
2. Enable rke2 feature flag again.
3. Do some stuff with the clusters then come back and disable rke2 flag. Now stuck in infinite restart loop and can't use the rancher instance.
 
**Expected Result:**
Rancher should come up without any issues and disable the rke2 feature flag.

**Actual Result:**
Rancher is infinitely rebooting with errors like:

```
2021/08/27 21:40:34 [ERROR] unable to update feature rke2 in initialize features: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": dial tcp 10.43.96.41:443: connect: no route to host
2021/08/27 21:40:40 [ERROR] unable to update feature unsupported-storage-drivers in initialize features: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": dial tcp 10.43.96.41:443: connect: no route to host
2021/08/27 21:40:46 [ERROR] unable to update feature multi-cluster-management in initialize features: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": dial tcp 10.43.96.41:443: connect: no route to host
2021/08/27 21:41:02 [FATAL] feature flag [rke2] value has changed, rancher must be restarted
```

**Additional Info:**
May not be easily reproducible - not tested (don't have time right now)

**Comment by ibuildthecloud** [comment]
The error `2021/08/27 21:40:46 [ERROR] unable to update feature multi-cluster-management in initialize features: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": dial tcp 10.43.96.41:443: connect: no route to host` would indicate that the webhook is not running. If you have the setup still available can you look at the rancher-webhook and see if it is restarting?

**Comment by davidnuzik** [comment]
The problem is rancher is running in a container; as soon as it barely comes up it will halt/shut down.
I haven't been able to reproduce this; I'm inclined to close this out -- if I see it again I can reopen.
