### ISSUE TITLE
Investigate the use of the new subnet switch in 1.10

### ISSUE THREAD

**Issue by withinboredom** [rancher/rancher#3452]
Docker 1.10 apparently allows using a subnet to assign ips... https://blog.jessfraz.com/post/ips-for-all-the-things/

Could this do away with the networking layer in rancher and would it be a good idea to support it natively?

**Comment by pwFoo** [comment]
Tested docker 1.10 and the --subnet option with RancherOS. I like the new network features and can't wait to use it with Rancher.

Rancher should support the new network feature, but could be take some time to implement?

**Comment by withinboredom** [comment]
It would be nice to isolate services by subnet...

**Comment by michaellopez** [comment]
+1

**Comment by pwFoo** [comment]
So docker network support in Rancher Server (cattle) is deferred?
Any change to use it with Rancher Swarm / Kubernetes environment?

**Comment by will-chan** [comment]
For now, our plan is to support CNI only.
