### ISSUE TITLE
create cluster provider custom  using curl

### ISSUE THREAD

**Issue by cloudcafetech** [rancher/rancher#34533]
creating cluster provider custom  using curl (following guide https://rancher.com/adding-custom-nodes-kubernetes-cluster-rancher-2-0-tech-preview-2) below command.

https://rancher.com/adding-custom-nodes-kubernetes-cluster-rancher-2-0-tech-preview-2

But in console when cluster created its says its imported not custom.

Not sure where should I mention provider ```custom```

**Comment by superseb** [comment]
Please use https://github.com/rancher/quickstart as that is probably the most up-to-date one.

**Comment by cloudcafetech** [comment]
@superseb 

But there is nothing mentioned "How to create Custom (provider) using curl"

![image](https://user-images.githubusercontent.com/68260844/131772395-15c11824-3ee4-4280-a584-c38c3ec59b1e.png)

I want using curl also, I can create Custom provided cluster.

**Comment by cloudcafetech** [comment]
@superseb 

👍👍👍

**Comment by cloudcafetech** [comment]
@superseb 

One more help, how can I add (or read) pem file content in fqdn certificate using curl?
