### ISSUE TITLE
Stopping stack causes 500 error

### ISSUE THREAD

**Issue by haswalt** [rancher/rancher#3453]
Attempting to stop a Stack with 2 services in it. 500 error returned from api:

```
Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@3a11c287] io.cattle.platform.engine.process.impl.ProcessCancelException: State [removed] is not valid
```

Using v0.56.0

**Comment by deniseschannon** [comment]
Is this a duplicate of https://github.com/rancher/rancher/issues/3284#issuecomment-176947434

What kind of services do you have?

**Comment by deniseschannon** [comment]
I am unable to reproduce.

**Comment by deniseschannon** [comment]
Closing in favor of #3284
