### ISSUE TITLE
Cannot upgrade imported rke2 cluster in rancher 2.6.0-rc9

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#34546]
**Rancher Server Setup**
- Rancher version: v2.6.0-rc9
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): rke1
         Node Setup: 3 nodes all roles
         Version: v1.21.4
- self signed certs

**Information about the Cluster**
- Kubernetes version: v1.19.13+rke2r2
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported

**Describe the bug**

I cannot upgrade the cluster through the UI, and the v3 API has the `rke2Config` field empty. I'm not sure what to look for in the v1 api. See screenshots for what I see in the UI.

**To Reproduce**
 
1. Import an older rke2 version cluster (v1.19.13+rke2r2 for example)
2. Attempt to upgrade through the UI

**Result**
No option to upgrade version

**Expected Result**

Should have an option to upgrade the kubernetes version to values associated with KDM

**Screenshots**

<img width="1452" alt="image" src="https://user-images.githubusercontent.com/55997940/131381646-03485790-1a83-456d-9e59-7f32431fccef.png">

**Additional context**

**Comment by davidnuzik** [comment]
I've also reproduced this; I did not see this issue on rc7.

v2.6.0-rc9 (single-node docker install of Rancher)
self-signed certs

rke2 v1.20.10+rke2r1
3 server nodes (all roles)
1 agent node (worker role)

The UI doesn't show any option to upgrade my 1.20.10 cluster.

**Comment by rancher-max** [comment]
https://github.com/rancher/rancher/pull/34549

**Comment by davidnuzik** [comment]
This works for me now.

v2.6-head `a97612b63` pulled at 8/30/21 2:38 pm Pacific
self-signed certs

rke2 v1.20.10+rke2r1
3 server nodes (all roles)

I now see in the UI the option to upgrade:
![image](https://user-images.githubusercontent.com/45179589/131410095-3028833c-5277-4c49-ba9d-08aaaa88541a.png)

I upgraded to v1.21.4+rke2r2 (the only option in the drop down). I used default options (don't drain and 1 cp concurrency, 1 worker concurrency)

And when I upgrade I get an error in the browser dev console, but the upgrade appears to work fine and the PUT request (rke2Config) appears nominal:
![image](https://user-images.githubusercontent.com/45179589/131410249-cc0e1c68-3d64-4ba7-baa3-ab6f8fd8b617.png)
![image](https://user-images.githubusercontent.com/45179589/131410356-5cd04da1-a78c-49b1-b176-07241119d5b4.png)

I watch the rke2-server (journalctl) logs on the nodes and the upgrade appears successful there.
I wait and see the new version v1.1.4+rke2r2 listed for the cluster and nodes in the UI.
![image](https://user-images.githubusercontent.com/45179589/131410601-70133429-5d71-4aa7-b520-eb8a7d606f6c.png)
![image](https://user-images.githubusercontent.com/45179589/131410657-c2d1286d-61ad-44ba-aed8-c6bca7a5a000.png)

**Comment by rancher-max** [comment]
#### Validated using v2.6-head commitid `a97612b`

Confirmed the following 4 scenarios are working:
1. This issue description (upgrade imported rke2 cluster) -- _pass_
2. Upgrade imported k3s cluster -- _pass_
3. Upgrade node driver cluster (using my own custom KDM) -- _pass_
4. Upgrade rancher 2.5.9 with an imported rke2 cluster in it to v2.6-head, and upgrade that downstream cluster -- _pass_
