### ISSUE TITLE
[2.5]Corrupted Backup - No Restore Rancher Management Cluster / Rancher Server

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#34554]
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): rke1 1.2.9
         Node Setup: (3 Nodes HA Cluster for Rancher)
         Version: 2.5.9

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

Rancher recovers from backup file failed on works case scenario where nodes were deleted.

ERRO[2021/07/21 09:21:04] Error restoring namespaced resources [error restoring m-gd5n4 of type management.cattle.io/v3, Resource=nodes: namespaces "c-kg7bm" not found]
ERRO[2021/07/21 09:21:04] error syncing 'restore-dgl9z': handler restore: error restoring namespaced resources, check logs for exact error, requeuing

**To Reproduce**
 
1.) Created a manual backup with rancher 2.5.9 running 
2.) Destroyed rancher management server/cluster (complete wipe with "terraform destroy") Or delete the nodes on the provider side.
3.) Create an new RKE cluster with "terraform apply"

10 min wait... check rancher: everything perfectly fine. new and fresh rancher

4.) Follow documentation for migration https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/migrating-rancher/

4a.) start a restore job pointing to the manual backup file
4b.) backup starts - renders rancher "unreachable" ( 503 Service Temporarily Unavailable )

**Result**

Fail to Restore from Backup.

**Expected Result**

Restore from Backup successfully..

**Screenshots**

**Additional context**

Complete infrastructure is set up with Terraform (Rancher Management Cluster - 3 vSphere VMs, RKE Cluster, Rancher Install, Rancher Bootstrapping,...)

Upgrade of Rancher RKE with Terraform (charming, worked perfectly)
Upgrade of Rancher Server with Terraform (")
After the upgrade planned a DR test (destroy complete Rancher Management Cluster infrastructure, re-deploy it via Terraform , restore Rancher Backup).
Currently doing Rancher Backups to an NFS PV with an EncryptionConfig and a recurring backup job (also setup with Terraform).

```
# k logs -f -n cattle-resources-system rancher-backup-74db9fdd57-rj4bj
ERRO[2021/07/21 09:21:04] Error restoring namespaced resources [error restoring m-gd5n4 of type management.cattle.io/v3, Resource=nodes: namespaces "c-kg7bm" not found]
ERRO[2021/07/21 09:21:04] error syncing 'restore-dgl9z': handler restore: error restoring namespaced resources, check logs for exact error, requeuing

Hint: namespace "c-kg7bm" is the namespace of the deleted cluster regarding the "cannot delete node template" ticket

After the job is "done" :

INFO[2021/07/21 09:21:04] Successfully restored ctr-r87n4-ctr-a
INFO[2021/07/21 09:21:04] Processing controllerRef apps/v1/deployments/rancher
INFO[2021/07/21 09:21:04] Scaling up controllerRef apps/v1/deployments/rancher to 3
ERRO[2021/07/21 09:21:04] Error restoring namespaced resources [error restoring m-gd5n4 of type management.cattle.io/v3, Resource=nodes: namespaces "c-kg7bm" not found]
ERRO[2021/07/21 09:21:04] error syncing 'restore-dgl9z': handler restore: error restoring namespaced resources, check logs for exact error, requeuing

Rancher Pods are scaled up to 3 and Rancher is "usable again" - we can also see the downstream clusters

BUT

The restore job runs again after a while in an "infinite loop" --> rancher is unusable!

We tried restore with "prune: true" and "prune: false". No difference.
```

**Comment by snasovich** [comment]
@StrongMonkey , is this customer issue hence the "internal" label?

**Comment by StrongMonkey** [comment]
@snasovich yes that's right

**Comment by StrongMonkey** [comment]
There is a way to reproduce this issue:

1. Create a cutsom cluster on rancher 2.5.9.
2. Wait for it to be provisioned. Once it is provisioned, modify v3 management.cattle.io/node and add a fake finalizer(in real user case there is an existing finalizer `controller.cattle.io/node-controller` that could make this node stuck at deletion if clean up failed, to reproduce the bug adding a fake finalizer should be enough to test)
3. Go and delete the cluster. You will see that the cluster is gone in UI but the underlying namespace `c-xxxx` and v3 node are stuck at deletion.

The root cause here is that we don't restore namespace even if it has deletionTimestamp and finalizers, because namespace has the finalizer in `spec.finalizer` instead of `metadata.finalizers`. The stucking resource in that namespace is being restored, but not the namespace itself, causing the error above.

**Comment by smangelkramer** [comment]
@StrongMonkey is a fix for Rancher 2.5.x planned?

**Comment by smangelkramer** [comment]
(i'm the guy who spotted this issue and provided the logs above). THX Sebastian

**Comment by StrongMonkey** [comment]
@smangelkramer yes it is planned to land in 2.5.10.

**Comment by abhi1693** [comment]
@StrongMonkey is this related to #32888? Because I've been unable to figure out why the backups are completely lost in my case

**Comment by StrongMonkey** [comment]
It is likely not related. In your issue it is an etcd backup, not the backup from rancher-backup-operator(CRD basedb backup)

**Comment by StrongMonkey** [comment]
Regardless, I think we need to add a new api field in restore to ignore failure. If there are corrupted backup configuration being applied, the controller will try to restore the backup file in a loop, causing rancher pod to be scaled up and down. If the restore never succeed, rancher will become unable to use.

**Comment by MSandro** [comment]
Is this related to #34768?
I've tried to migrate rancher to a new cluster on new servers and now I can't controll my custom rancher managed clusters.

**Comment by jiaqiluo** [comment]
can be validated in `rancher-backup 1.2.0-rc6`

**Comment by anupama2501** [comment]
Repro on v2.5.9:

- create a custom cluster with 3 worker, 1 etcd, 1 cp
- From the local cluster, on the UI launch kubectl shell and run the command kubectl get nodes.management.cattle.io -A
- Edit the node of the custom cluster by kubectl edit nodes.management.cattle.io $nodename -n $clustername
- Add the fake finalizer `- foo.bar` under metadata --> finalizers
- Delete the cluster and verify that the cluster is removed but the node will be dangling `kubectl get nodes.management.cattle.io -A`
- From local cluster --> apps & market, install rancher backup version `v1.0.400` by providing s3 details.
- Take a backup of the existing state of the local cluster and see the backup stored in the S3.
- Create a few 
- Create a new rke cluster and migrate the rancher server to this rke cluster
- Restore the backup stored in the s3 on this new rke cluster.
- Verify the restore won't recover and is stuck in the state ```Error restoring namespaced resources [error restoring `m-4067aa68dd78 of type management.cattle.io/v3, Resource=nodes: namespaces "c-89d82" not found]```


Verified on v2.5.9-rc2 rancher chart version and rancher server version `v2.5-head ce52c78` 

1. Retried the same steps as mentioned above and verified the restore works fine and the rancher server comes up active.
2. Created a few workloads and few namespaces, all look good
3. Create a new backup on the existing rancher server
4. Restore without migration on the same rancher server and the restore was successful.
5. Create a few workloads and namespaces post restore --> look good
