### ISSUE TITLE
Rancher agent error Stat fs failed. Error: EOF

### ISSUE THREAD

**Issue by tombmurphy** [rancher/rancher#3455]
rancher/agent       v0.8.2
Platform: AWS EC2 (ami-6c14310f)
OS: ubuntu 14.04.3 LTS
Kernel: 3.13 (after a dist upgrade)

I'm seeing this error continuously in the logs when I start a new rancher agent. I have plenty of disk space free.

What could be the issue ? I suspect it could be some permission issue. I run the docker run command as sudo.

Thanks,

**Comment by flaccid** [comment]
Could you paste the full log entry and output of `docker version` ?

**Comment by tombmurphy** [comment]
Sorry here it is:

docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

**Comment by CBR09** [comment]
Could you paste the full log?

**Comment by tombmurphy** [comment]
Here is the full log from a rancher-agent restart:

INFO: Starting agent for 72945F5AAB009137D33D
INFO: Access Key: 72945F5AAB009137D33D
INFO: Config URL: http://x.x.x.x:8080/v1
INFO: Storage URL: http://x.x.x.x:8080/v1
INFO: API URL: http://x.x.x.x:8080/v1
INFO: IP: 10.10.0.82
INFO: Port:
INFO: Required Image: rancher/agent:v0.8.2
INFO: Current Image: rancher/agent:v0.8.2
INFO: Using image rancher/agent:v0.8.2
INFO: Downloading agent http://x.x.x.x:8080/v1/configcontent/configscripts
INFO: Updating configscripts
INFO: Downloading http://x.x.x.x:8080/v1//configcontent//configscripts current=
INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/apply.sh
INFO: Sending configscripts applied 1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319
INFO: Updating pyagent
INFO: Downloading http://x.x.x.x:8080/v1//configcontent//pyagent current=
INFO: Running /var/lib/cattle/download/pyagent/pyagent-1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c06069547103e24f5f4562a2db5d4805d60/apply.sh
INFO: Updating host-api
INFO: Downloading http://x.x.x.x:8080/v1//configcontent//host-api current=1-1dcc85d77415faddc4d6d204d2bd622d835de4b5ee4b472651419b58189c474a
INFO: Already up to date
INFO: Sending host-api applied 1-1dcc85d77415faddc4d6d204d2bd622d835de4b5ee4b472651419b58189c474a
INFO: Updating agent-binaries
INFO: Downloading http://x.x.x.x:8080/v1//configcontent//agent-binaries current=1-4200f9b686342da8e941359211b1d8c5f98877ae293d0ead231d43507f1c9eae
INFO: Already up to date
INFO: Sending agent-binaries applied 1-4200f9b686342da8e941359211b1d8c5f98877ae293d0ead231d43507f1c9eae
INFO: Updating python-agent
INFO: Downloading http://x.x.x.x:8080/v1//configcontent//python-agent current=1-5fa9b53964d8b1335257916f7b4687aec2e17c9516e578f5406f29160eec1cd1
INFO: Already up to date
INFO: Sending python-agent applied 1-5fa9b53964d8b1335257916f7b4687aec2e17c9516e578f5406f29160eec1cd1
INFO: Updating cadvisor
INFO: Downloading http://x.x.x.x:8080/v1//configcontent//cadvisor current=1-4d2b4356ab14bc1fa7ec7cd83f35b7e975a16cea01634683b577c9498c98de25
INFO: Already up to date
INFO: Sending cadvisor applied 1-4d2b4356ab14bc1fa7ec7cd83f35b7e975a16cea01634683b577c9498c98de25
INFO: Updating volmgr
INFO: Downloading http://x.x.x.x:8080/v1//configcontent//volmgr current=1-c813690c24ae9a12f0792378c78a48f447b243517233d7969b99baefbea5af15
INFO: Already up to date
INFO: Sending volmgr applied 1-c813690c24ae9a12f0792378c78a48f447b243517233d7969b99baefbea5af15
INFO: Sending pyagent applied 1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c06069547103e24f5f4562a2db5d4805d60
INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
INFO: Executing /var/lib/cattle/pyagent/main.py
INFO: Updating host-config
INFO: Downloading http://x.x.x.x:8080/v1//configcontent//host-config current=host-config-1-0b0dbea0d48096d7db75512ba9f42c68c1fa706781dc90b52a8d91efa7441221
INFO: Already up to date
INFO: Sending host-config applied 1-0b0dbea0d48096d7db75512ba9f42c68c1fa706781dc90b52a8d91efa7441221
time="2016-02-01T05:10:19Z" level="info" msg="Starting event router."
time="2016-02-01T05:10:19Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers"
time="2016-02-01T05:10:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"82109450de747c456db833a8529b6018583b639505788374276cd62cb505a911\", From:\"-simulated-\", Time:0}"
time="2016-02-01T05:10:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"d8b8b456694f30701219fd65a234dc4807252ed9dc31726af7f171912fbd5346\", From:\"-simulated-\", Time:0}"
time="2016-02-01T05:10:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"168cfb4fdd50b069e9dbf48fe03a030c901c3e29d1356e3c186c0f427cc44279\", From:\"-simulated-\", Time:0}"
time="2016-02-01T05:10:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"b05a972c55808033d319771c97d037377994c44a48706330e3031e3292e06b37\", From:\"-simulated-\", Time:0}"
time="2016-02-01T05:10:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"bcb690dbea549a21715144d435244a6df5236dbd0f07d1656eb21adc461f4467\", From:\"-simulated-\", Time:0}"
time="2016-02-01T05:10:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"202a267d6e0c7c4ee94c7945076c6351f820ad1619743d776b905e8bd333b870\", From:\"-simulated-\", Time:0}"
time="2016-02-01T05:10:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"dcd1eff0429767203b91cbf51a93e54b8b2479c6ddbfd33c14ecb4cd88230178\", From:\"-simulated-\", Time:0}"
time="2016-02-01T05:10:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"85505d277c6e7d4d91dadaf9db31aa6ae48b8a1c6408eb17f454ae34c4f88a30\", From:\"-simulated-\", Time:0}"
time="2016-02-01T05:10:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"efd827b194e1627c57f96357db794c4720f9489b8559167fd7d4f89cffe01851\", From:\"-simulated-\", Time:0}"
time="2016-02-01T05:10:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"5c82c3cc36324e35f646d5da183e84701cfa6a8fcda426716cbf960407ca3647\", From:\"-simulated-\", Time:0}"
time="2016-02-01T05:10:19Z" level="info" msg="Assigning IP [10.42.16.109/16], ContainerId [82109450de747c456db833a8529b6018583b639505788374276cd62cb505a911], Pid [1224]"
time="2016-02-01T05:10:19Z" level="info" msg="Assigning IP [10.42.1.242/16], ContainerId [168cfb4fdd50b069e9dbf48fe03a030c901c3e29d1356e3c186c0f427cc44279], Pid [5087]"
time="2016-02-01T05:10:19Z" level="info" msg="Assigning IP [10.42.147.99/16], ContainerId [d8b8b456694f30701219fd65a234dc4807252ed9dc31726af7f171912fbd5346], Pid [7765]"
time="2016-02-01T05:10:19Z" level="info" msg="Assigning IP [10.42.155.207/16], ContainerId [5c82c3cc36324e35f646d5da183e84701cfa6a8fcda426716cbf960407ca3647], Pid [11750]"
time="2016-02-01T05:10:19Z" level="info" msg="Assigning IP [10.42.124.219/16], ContainerId [efd827b194e1627c57f96357db794c4720f9489b8559167fd7d4f89cffe01851], Pid [12336]"
time="2016-02-01T05:10:19Z" level="info" msg="Assigning IP [10.42.164.255/16], ContainerId [85505d277c6e7d4d91dadaf9db31aa6ae48b8a1c6408eb17f454ae34c4f88a30], Pid [11825]"
time="2016-02-01T05:10:19Z" level="info" msg="Assigning IP [10.42.160.53/16], ContainerId [dcd1eff0429767203b91cbf51a93e54b8b2479c6ddbfd33c14ecb4cd88230178], Pid [11701]"
time="2016-02-01T05:10:19Z" level="info" msg="Assigning IP [10.42.114.124/16], ContainerId [202a267d6e0c7c4ee94c7945076c6351f820ad1619743d776b905e8bd333b870], Pid [5022]"
time="2016-02-01T05:10:19Z" level="info" msg="Assigning IP [10.42.194.84/16], ContainerId [bcb690dbea549a21715144d435244a6df5236dbd0f07d1656eb21adc461f4467], Pid [5553]"
time="2016-02-01T05:10:19Z" level="info" msg="Assigning IP [10.42.158.113/16], ContainerId [b05a972c55808033d319771c97d037377994c44a48706330e3031e3292e06b37], Pid [5147]"
time="2016-02-01T05:10:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"10a3e49e42f5013d570362a8a58b7e712d2d2a37f7f980126f20e85dd421bb57\", From:\"-simulated-\", Time:0}"
time="2016-02-01T05:10:19Z" level="info" msg="Assigning IP [10.42.201.4/16], ContainerId [10a3e49e42f5013d570362a8a58b7e712d2d2a37f7f980126f20e85dd421bb57], Pid [7515]"
time="2016-02-01T05:10:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"7bd647f0e4bf761fe0afff130e6ca93c1d351e64b8e36371b585d1034f3bd801\", From:\"-simulated-\", Time:0}"
time="2016-02-01T05:10:19Z" level="info" msg="Connecting to proxy." url="ws://x.x.x.x:8080/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NTQzMDM3MTAsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6IjQ3MjhkYzg2LWMxNTUtNDE4Yi05ZGRmLWI3NzRkNjY1ZWZmMCIsImlhdCI6MTQ1NDMwMzQxMCwia2lkIjoiZGVmYXVsdCJ9.PUpT7O1NN_bLH2QRfCF9yUUSNhWynssUzUviBv_hn9nQYp6qqBSmvATAYZLh3h-hvRLbswf6t1YJIeI9P7aWDS1OsN3Mczg3XrCsAEr6SPvyShBb9wubXBZ1yy-oPiZS5nKkB7lH31WDzBBzQrbDU8iKCs-k1PGdXgaAcy8Vf3qzv17NEArsMoUJE5GMNlOc4pUwXJqThuadxumB_KT3TgVx-MIQvCqu-QhSWLEvCox6ktq3jC3VoCCFmRW757cAix39iRldfzitpyPpF6Oji6wZNrMs7TJVPh8wbDb5yKq4ZxzBXlcMFPg6nYK19ooKa3QrVPboOGTLAwB1ktX1EA"
I0201 16:10:19.861452 26689 storagedriver.go:132] No backend storage selected
I0201 16:10:19.861504 26689 storagedriver.go:134] Caching stats in memory for 2m0s
I0201 16:10:19.861558 26689 manager.go:128] cAdvisor running in container: "/docker/7bd647f0e4bf761fe0afff130e6ca93c1d351e64b8e36371b585d1034f3bd801"
I0201 16:10:19.991806 26689 fs.go:108] Filesystem partitions: map[/dev/mapper/docker-202:1-404746-7bd647f0e4bf761fe0afff130e6ca93c1d351e64b8e36371b585d1034f3bd801:{mountpoint:/var/lib/docker/devicemapper/mnt/7bd647f0e4bf761fe0afff130e6ca93c1d351e64b8e36371b585d1034f3bd801 major:252 minor:2 fsType: blockSize:0} /dev/mapper/docker-202:1-404746-10a3e49e42f5013d570362a8a58b7e712d2d2a37f7f980126f20e85dd421bb57:{mountpoint:/var/lib/docker/devicemapper/mnt/10a3e49e42f5013d570362a8a58b7e712d2d2a37f7f980126f20e85dd421bb57 major:252 minor:4 fsType: blockSize:0} /dev/mapper/docker-202:1-404746-5c82c3cc36324e35f646d5da183e84701cfa6a8fcda426716cbf960407ca3647:{mountpoint:/var/lib/docker/devicemapper/mnt/5c82c3cc36324e35f646d5da183e84701cfa6a8fcda426716cbf960407ca3647 major:252 minor:7 fsType: blockSize:0} /dev/mapper/docker-202:1-404746-efd827b194e1627c57f96357db794c4720f9489b8559167fd7d4f89cffe01851:{mountpoint:/var/lib/docker/devicemapper/mnt/efd827b194e1627c57f96357db794c4720f9489b8559167fd7d4f89cffe01851 major:252 minor:5 fsType: blockSize:0} /dev/mapper/docker-202:1-404746-dcd1eff0429767203b91cbf51a93e54b8b2479c6ddbfd33c14ecb4cd88230178:{mountpoint:/var/lib/docker/devicemapper/mnt/dcd1eff0429767203b91cbf51a93e54b8b2479c6ddbfd33c14ecb4cd88230178 major:252 minor:6 fsType: blockSize:0} /dev/mapper/docker-202:1-404746-85505d277c6e7d4d91dadaf9db31aa6ae48b8a1c6408eb17f454ae34c4f88a30:{mountpoint:/var/lib/docker/devicemapper/mnt/85505d277c6e7d4d91dadaf9db31aa6ae48b8a1c6408eb17f454ae34c4f88a30 major:252 minor:8 fsType: blockSize:0} /dev/mapper/docker-202:1-404746-b05a972c55808033d319771c97d037377994c44a48706330e3031e3292e06b37:{mountpoint:/var/lib/docker/devicemapper/mnt/b05a972c55808033d319771c97d037377994c44a48706330e3031e3292e06b37 major:252 minor:12 fsType: blockSize:0} /dev/mapper/docker-202:1-404746-bcb690dbea549a21715144d435244a6df5236dbd0f07d1656eb21adc461f4467:{mountpoint:/var/lib/docker/devicemapper/mnt/bcb690dbea549a21715144d435244a6df5236dbd0f07d1656eb21adc461f4467 major:252 minor:11 fsType: blockSize:0} /dev/mapper/docker-202:1-404746-202a267d6e0c7c4ee94c7945076c6351f820ad1619743d776b905e8bd333b870:{mountpoint:/var/lib/docker/devicemapper/mnt/202a267d6e0c7c4ee94c7945076c6351f820ad1619743d776b905e8bd333b870 major:252 minor:13 fsType: blockSize:0} /dev/mapper/docker-202:1-404746-168cfb4fdd50b069e9dbf48fe03a030c901c3e29d1356e3c186c0f427cc44279:{mountpoint:/var/lib/docker/devicemapper/mnt/168cfb4fdd50b069e9dbf48fe03a030c901c3e29d1356e3c186c0f427cc44279 major:252 minor:14 fsType: blockSize:0} /dev/mapper/docker-202:1-404746-d8b8b456694f30701219fd65a234dc4807252ed9dc31726af7f171912fbd5346:{mountpoint:/var/lib/docker/devicemapper/mnt/d8b8b456694f30701219fd65a234dc4807252ed9dc31726af7f171912fbd5346 major:252 minor:15 fsType: blockSize:0} /dev/mapper/docker-202:1-404746-82109450de747c456db833a8529b6018583b639505788374276cd62cb505a911:{mountpoint:/var/lib/docker/devicemapper/mnt/82109450de747c456db833a8529b6018583b639505788374276cd62cb505a911 major:252 minor:9 fsType: blockSize:0} /dev/disk/by-uuid/05d65782-9d6d-4859-b412-923240f25c94:{mountpoint:/ major:202 minor:1 fsType: blockSize:0} docker-202:1-404746-pool:{mountpoint: major:7 minor:0 fsType:devicemapper blockSize:128}]
E0201 16:10:19.997013 26689 fs.go:211] Stat fs failed. Error: EOF
I0201 16:10:20.006725 26689 manager.go:163] Machine: {NumCores:2 CpuFrequency:2400062 MemoryCapacity:4143996928 MachineID:2a4f44fbd2d0e82f7521d45d5697d615 SystemUUID:EC25CA20-A878-D52C-7A59-56EA7BD30C48 BootID:746421e1-dbe7-4ab0-87c5-f643b4d3a072 Filesystems:[{Device:/dev/mapper/docker-202:1-404746-b05a972c55808033d319771c97d037377994c44a48706330e3031e3292e06b37 Capacity:105555197952} {Device:/dev/mapper/docker-202:1-404746-bcb690dbea549a21715144d435244a6df5236dbd0f07d1656eb21adc461f4467 Capacity:105555197952} {Device:/dev/mapper/docker-202:1-404746-dcd1eff0429767203b91cbf51a93e54b8b2479c6ddbfd33c14ecb4cd88230178 Capacity:105555197952} {Device:/dev/mapper/docker-202:1-404746-85505d277c6e7d4d91dadaf9db31aa6ae48b8a1c6408eb17f454ae34c4f88a30 Capacity:105555197952} {Device:/dev/mapper/docker-202:1-404746-d8b8b456694f30701219fd65a234dc4807252ed9dc31726af7f171912fbd5346 Capacity:105555197952} {Device:/dev/mapper/docker-202:1-404746-82109450de747c456db833a8529b6018583b639505788374276cd62cb505a911 Capacity:105555197952} {Device:/dev/mapper/docker-202:1-404746-202a267d6e0c7c4ee94c7945076c6351f820ad1619743d776b905e8bd333b870 Capacity:105555197952} {Device:/dev/mapper/docker-202:1-404746-168cfb4fdd50b069e9dbf48fe03a030c901c3e29d1356e3c186c0f427cc44279 Capacity:105555197952} {Device:/dev/disk/by-uuid/05d65782-9d6d-4859-b412-923240f25c94 Capacity:20988547072} {Device:/dev/mapper/docker-202:1-404746-5c82c3cc36324e35f646d5da183e84701cfa6a8fcda426716cbf960407ca3647 Capacity:105555197952} {Device:/dev/mapper/docker-202:1-404746-efd827b194e1627c57f96357db794c4720f9489b8559167fd7d4f89cffe01851 Capacity:105555197952} {Device:/dev/mapper/docker-202:1-404746-7bd647f0e4bf761fe0afff130e6ca93c1d351e64b8e36371b585d1034f3bd801 Capacity:105555197952} {Device:/dev/mapper/docker-202:1-404746-10a3e49e42f5013d570362a8a58b7e712d2d2a37f7f980126f20e85dd421bb57 Capacity:105555197952}] DiskMap:map[252:12:{Name:dm-12 Major:252 Minor:12 Size:107374182400 Scheduler:none} 202:0:{Name:xvda Major:202 Minor:0 Size:21474836480 Scheduler:deadline} 252:3:{Name:dm-3 Major:252 Minor:3 Size:107374182400 Scheduler:none} 252:8:{Name:dm-8 Major:252 Minor:8 Size:107374182400 Scheduler:none} 252:11:{Name:dm-11 Major:252 Minor:11 Size:107374182400 Scheduler:none} 252:13:{Name:dm-13 Major:252 Minor:13 Size:107374182400 Scheduler:none} 252:14:{Name:dm-14 Major:252 Minor:14 Size:107374182400 Scheduler:none} 252:15:{Name:dm-15 Major:252 Minor:15 Size:107374182400 Scheduler:none} 252:2:{Name:dm-2 Major:252 Minor:2 Size:107374182400 Scheduler:none} 252:5:{Name:dm-5 Major:252 Minor:5 Size:107374182400 Scheduler:none} 252:6:{Name:dm-6 Major:252 Minor:6 Size:107374182400 Scheduler:none} 252:0:{Name:dm-0 Major:252 Minor:0 Size:107374182400 Scheduler:none} 252:1:{Name:dm-1 Major:252 Minor:1 Size:107374182400 Scheduler:none} 252:4:{Name:dm-4 Major:252 Minor:4 Size:107374182400 Scheduler:none} 252:7:{Name:dm-7 Major:252 Minor:7 Size:107374182400 Scheduler:none} 252:9:{Name:dm-9 Major:252 Minor:9 Size:107374182400 Scheduler:none}] NetworkDevices:[{Name:dummy0 MacAddress:f2:93:e6:23:62:ea Speed:0 Mtu:1500} {Name:eth0 MacAddress:06:42:3c:a9:5e:a7 Speed:0 Mtu:9001}] Topology:[{Id:0 Memory:4143996928 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:31457280 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown}
I0201 16:10:20.017951 26689 manager.go:169] Version: {KernelVersion:3.13.0-74-generic ContainerOsVersion:Ubuntu 14.04.3 LTS DockerVersion:1.9.1 CadvisorVersion: CadvisorRevision:}
I0201 16:10:20.134034 26689 factory.go:236] Registering Docker factory
I0201 16:10:20.135263 26689 factory.go:93] Registering Raw factory
I0201 16:10:20.330639 26689 manager.go:1006] Started watching for new ooms in manager
I0201 16:10:20.330674 26689 oomparser.go:199] OOM parser using kernel log file: "/var/log/kern.log"
I0201 16:10:20.344078 26689 manager.go:250] Starting recovery of all containers
E0201 16:10:20.378253 26689 fs.go:211] Stat fs failed. Error: EOF
I0201 16:10:20.391489 26689 manager.go:255] Recovery completed
I0201 16:10:20.400449 26689 cadvisor.go:96] Starting cAdvisor version: - on port 9344
E0201 16:10:21.352490 26689 fs.go:211] Stat fs failed. Error: EOF
E0201 16:10:22.351871 26689 fs.go:211] Stat fs failed. Error: EOF
E0201 16:10:23.351687 26689 fs.go:211] Stat fs failed. Error: EOF
E0201 16:10:24.353763 26689 fs.go:211] Stat fs failed. Error: EOF
E0201 16:10:25.351250 26689 fs.go:211] Stat fs failed. Error: EOF
E0201 16:10:26.351048 26689 fs.go:211] Stat fs failed. Error: EOF
E0201 16:10:27.354794 26689 fs.go:211] Stat fs failed. Error: EOF
E0201 16:10:28.352457 26689 fs.go:211] Stat fs failed. Error: EOF
E0201 16:10:29.350933 26689 fs.go:211] Stat fs failed. Error: EOF
E0201 16:10:30.351506 26689 fs.go:211] Stat fs failed. Error: EOF
E0201 16:10:31.350934 26689 fs.go:211] Stat fs failed. Error: EOF
E0201 16:10:32.355118 26689 fs.go:211] Stat fs failed. Error: EOF

**Comment by deniseschannon** [comment]
What version of Rancher are you running?

Can you explain your set up a little more? Based on the logs it looks like there are a lot of existing containers on the agent, so was this an existing host in Rancher and you are re-adding it into Rancher?

**Comment by tombmurphy** [comment]
I'm running rancher 0.51.0

That is correct I have been re-provisioning the rancher-agent server several times and attaching it to the rancher-server but with a different cattle IP each time. It's just a simple 1 agent -> 1 server.

**Comment by nextrevision** [comment]
I see this same error when added an existing host running multiple containers deployed through other means to a Rancher environment.

**Comment by tombmurphy** [comment]
I still see this error when I run rancher agent the very first time to a rancher server.
Could this be an issue with Ubuntu trusty ?

**Comment by gcallsen** [comment]
We're also seeing this issue.

    E0218 21:25:31.614922 02216 fs.go:211] Stat fs failed. Error: EOF
    E0218 21:25:32.620072 02216 fs.go:211] Stat fs failed. Error: EOF
    E0218 21:25:33.618092 02216 fs.go:211] Stat fs failed. Error: EOF

Rancher version v0.59.0, rancher-agent v0.9.2,  rancher-agent-instance v0.8.0, Docker 1.9.1, ubuntu 14.04, EC2 ami-fce3c696.

This is happening on multiple machines with different 'histories' in terms of when they were added to Rancher, what containers have been run, etc. We just spun up a fresh machine this morning, added to Rancher, and same error coming from rancher agent logs.

**Comment by composer22** [comment]
I'm getting

`time="2016-02-25T16:54:34Z" level="error" msg="Error getting container info." error="request \"http://127.0.0.1:9344/api/v1.3/containers/system.slice/docker-7162ad4a78f17142edf3837d5cb5b169443db701adb2cef3b5048919b25d78dc.scope\" failed with error: \"failed to get container \\\"/system.slice/docker-7162ad4a78f17142edf3837d5cb5b169443db701adb2cef3b5048919b25d78dc.scope\\\" with error: unknown container \\\"/system.slice/docker-7162ad4a78f17142edf3837d5cb5b169443db701adb2cef3b5048919b25d78dc.scope\\\"\"" id="7162ad4a78f17142edf3837d5cb5b169443db701adb2cef3b5048919b25d78dc" `

**Comment by tombmurphy** [comment]
This issue no longer happens when switching /var/lib/docker to btrfs. So it seems related to devicemapper / ext4 at least.

**Comment by drmikecrowe** [comment]
@tombmurphy can you describe how you migrated to btrfs?

**Comment by tombmurphy** [comment]
Sorry I did not migrate an existing instance, I spun up a separate instance and mounted a btrfs volume. Still using Ubuntu 14.04 and it no longer has the error.

**Comment by drmikecrowe** [comment]
Hmm, I moved /var/lib/docker to a btrfs volume and am still getting the errors.

Do you the whole machine needs to be btrfs?

**Comment by v01t** [comment]
Hi, I just found that error:

`level="error" msg="Error getting container info." error="request \"http://127.0.0.1:9344/api/v1.3/containers/system.slice/docker-<...id...>.scope\" failed with error: \"failed to get container \\\"/system.slice/docker-<...id...>.scope\\\" with error: unknown container \\\"/system.slice/docker-<...>.scope\\\"\"" id="<...id...>"`

in my case appears to be correct because this is a error response from cadvisor api, valid endpoint seems to be:

`api/v1.3/containers/docker/<...id...>`

because using this endpoint I can get stats information in json, that by my understanding exactly that rancher-agent tries to get...
how? where? I can fix that to make my setup works.
Thanks.

Rancher v0.61.0-rc3, rancher-agent v0.9.2, Docker 1.10.2, Debian 8

**Comment by gcallsen** [comment]
To add to details: we've tested on completely fresh machines, same issue. All running the default 14.04 AMI from AWS "Ubuntu Server 14.04 LTS (HVM), SSD Volume Type", in both US-East-1 and US-West-2. We have done this on machines with EBS+2xSSD drives along with standard EBS-only (i.e. t2-micro).  Would really like to know if there is any progress on this - it is spamming our logs (we ship all logs from Docker). I don't want to simply exclude the Rancher logs because ultimately that would be a critical component to keep track of, though as it stands its unusable given the volume of these logs.

**Comment by drmikecrowe** [comment]
I am using logspout, and did filter out these messages with:

    filter {
        if ([message] =~ /^E0303/) {
            drop{}
        }
    }

(though I feel a bit unclean doing it this way)

**Comment by cllunsford** [comment]
Looks like this error is bubbling up from cadvisor: https://github.com/google/cadvisor/blob/master/fs/fs.go#L270

**Comment by cllunsford** [comment]
It was on line 211 back in release 0.19, so rancher-agent must be using an older version: https://github.com/google/cadvisor/blob/release-v0.19/fs/fs.go#L211 .  Perhaps related to https://github.com/google/cadvisor/pull/976 ?

**Comment by deniseschannon** [comment]
We are no longer using cadvisor as of v1.2.0 instead we're using `docker stats` for container stats and https://github.com/shirou/gopsutil for host stats. 

Also, we have re-factored our old agent into an agent written in go. If you still face this issue, please comment on it.
