### ISSUE TITLE
[KEv2] Cluster agents on imported hosted provider clusters aren't cleaned up

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#34561]
**Describe the bug**

Rancher skips cleaning up the cluster agent and cattle-system namespace on imported hosted provider clusters, because the driver gets set to e.g. `GKE` and not to `imported`:

https://github.com/rancher/rancher/blob/662e49eedecb4d3d4782e331a4cff07b37db1ca0/pkg/controllers/management/usercontrollers/controller.go#L74-L78

We should make sure that imported clusters on hosted providers are cleaned up in the same way that other imported clusters are.

**To Reproduce**
 
1. Create an AKS, EKS, or GKE cluster through the provider console.
2. Import the cluster in rancher
3. List the pods in the cluster, note the cattle-cluster-agent pod when the cluster is finished importing
4. Delete the cluster

**Result**

cattle-cluster-agent is still on the cluster

**Expected Result**

A cleanup job should be launched and the cattle-cluster-agent pod and cattle-system namespace should be deleted.

**Screenshots**

**Additional context**
Related to https://github.com/rancher/rancher/issues/34486

**Comment by izaac** [comment]
Rancher version: `v2.6.0` 

Reproduced on this Rancher version. The cluster agents are left in the imported cluster after removing from Rancher.
I will proceed validating the fix on EKS/AKS/GKE

**Comment by izaac** [comment]
Rancher version: `v2.6-head (09/09/2021)` _a6e7905_

I tried GKEv2 and EKSv2 imports, wait until the cluster was in Active state then proceeded to remove it from Rancher. 
Waited 5 minutes and the cluster-agent was still in the cluster along with the `cattle-system` namespace


```
k get po -n cattle-system
NAME                                    READY   STATUS    RESTARTS   AGE
cattle-cluster-agent-67457d5c95-fkmln   1/1     Running   0          10m
cattle-cluster-agent-67457d5c95-g697x   1/1     Running   0          10m

 k get ns
NAME                          STATUS   AGE
cattle-fleet-system           Active   11m
cattle-impersonation-system   Active   11m
cattle-system                 Active   11m
default                       Active   14m
kube-node-lease               Active   14m
kube-public                   Active   14m
kube-system                   Active   14m
local                         Active   10m
```

**Comment by cmurphy** [comment]
I apologize, this issue won't actually be fully fixed until https://github.com/rancher/rancher/pull/34573 is merged, I will move this back to test when that happens.

**Comment by rmweir** [comment]
Confirmed that cluster agent is being removed. However, fleet-agent is not removed. Assuming that is not part of this issue.

Deployments before import:
```
NAMESPACE     NAME      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   coredns   2/2     2            2           7m17s
```
Pods before import:
```
kube-system   aws-node-8fvs8            1/1     Running   0          2m53s
kube-system   aws-node-lhlmx            1/1     Running   0          2m50s
kube-system   coredns-f47955f89-npwvw   1/1     Running   0          6m59s
kube-system   coredns-f47955f89-wz6jh   1/1     Running   0          6m59s
kube-system   kube-proxy-kpgsd          1/1     Running   0          2m50s
kube-system   kube-proxy-ncwbm          1/1     Running   0          2m53s
```
Deployments after import:
```
cattle-fleet-system   fleet-agent            1/1     1            1           3m46s
cattle-system         cattle-cluster-agent   2/2     2            2           4m34s
kube-system           coredns                2/2     2            2           13m
```
Pods after import:
```
cattle-fleet-system   fleet-agent-58c7dbf5d6-b5lnk           1/1     Running   0          3m45s
cattle-system         cattle-cluster-agent-f5b6557cf-gvqzq   1/1     Running   0          4m41s
cattle-system         cattle-cluster-agent-f5b6557cf-kjtjv   1/1     Running   0          4m17s
kube-system           aws-node-8fvs8                         1/1     Running   0          9m20s
kube-system           aws-node-lhlmx                         1/1     Running   0          9m17s
kube-system           coredns-f47955f89-npwvw                1/1     Running   0          13m
kube-system           coredns-f47955f89-wz6jh                1/1     Running   0          13m
kube-system           kube-proxy-kpgsd                       1/1     Running   0          9m17s
kube-system           kube-proxy-ncwbm                       1/1     Running   0          9m20s
```
Deployments after delete:
```
cattle-fleet-system   fleet-agent   1/1     1            1           5m29s
kube-system           coredns       2/2     2            2           15m
```
Pod after delete:
```
cattle-fleet-system   fleet-agent-58c7dbf5d6-b5lnk   1/1     Running   0          5m28s
kube-system           aws-node-8fvs8                 1/1     Running   0          11m
kube-system           aws-node-lhlmx                 1/1     Running   0          11m
kube-system           coredns-f47955f89-npwvw        1/1     Running   0          15m
kube-system           coredns-f47955f89-wz6jh        1/1     Running   0          15m
kube-system           kube-proxy-kpgsd               1/1     Running   0          11m
kube-system           kube-proxy-ncwbm               1/1     Running   0          11m
```

**Comment by izaac** [comment]
Closing, the original issue was validated by dev. There were two separate issues opened for follow up.
https://github.com/rancher/rancher/issues/34988
https://github.com/rancher/rancher/issues/34990
