### ISSUE TITLE
AWS rke2 node driver multi-nodes are stuck in provisioning in cluster management page with only etcd and control plane active in the explore cluster page

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34565]
**Rancher Server Setup**
- Rancher version: `v2.6.0-rc10`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.21.3+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 3 worker, 1 etcd, 1 cp`
   

**Describe the bug**
AWS ec2 node driver multi-nodes are stuck in provisioning state in the cluster -management page. From the explore cluster page, etcd and cp nodes are seen registered but no worker nodes were registered. cluster in the explore cluster page is seen active.

**`Note`:** This is not seen happening always. Created another cluster with the same config and all the nodes have come up active and the cluster has come up fine.

I have the setup up. Can link the details. 

**To Reproduce**
1. Create a node to install rancher server in amazon ec2 in the `US-East-2` location
2. Install rancher 
3. Create a cluster by selecting the location in `US-West-2` location with 3 worker nodes, 1 cp, 1 etcd config.

**Result**
Cluster is seen stuck in `provisioning` state and from the explore cluster page, we can see the nodes etcd and cp have come up active but no worker nodes are registered.

**Expected Result**
Cluster is expected to come up active without being stuck in `provisioning` state.

**Screenshots**
<img width="400" alt="Screen Shot 2021-08-30 at 8 39 11 PM" src="https://user-images.githubusercontent.com/38144301/131437990-9cf33803-3199-4fef-9b75-252ec0ef65f9.png">

<img width="400" alt="Screen Shot 2021-08-30 at 8 39 24 PM" src="https://user-images.githubusercontent.com/38144301/131438712-47e45437-22b1-48eb-935d-9aaff6c27bf7.png">

**Additional context**
Some error logs seen in the pods as the worker nodes were not registered: 
```
0/2 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/control-plane: }, that the pod didn't tolerate, 1 node(s) had taint {node-role.kubernetes.io/etcd: }, that the pod didn't tolerate.

```

Logs seen in the rancher server:
```
p in cluster c-m-s98sqdvq for subject user-wp7pz
2021/08/30 23:58:02 [ERROR] error in planner for 'fleet-default/anupamafinalrcrke2': ignore handler error
2021/08/30 23:58:02 [ERROR] error in planner for 'fleet-default/anupamafinalrcrke2': ignore handler error
2021/08/30 23:58:02 [INFO] [mgmt-project-rbac-create] Updating project p-gshc2
2021/08/30 23:58:02 [ERROR] error in planner for 'fleet-default/anupamafinalrcrke2': ignore handler error
2021/08/30 23:58:02 [ERROR] error in planner for 'fleet-default/anupamafinalrcrke2': ignore handler error
2021/08/30 23:58:02 [ERROR] error in planner for 'fleet-default/anupamafinalrcrke2': ignore handler error
2021/08/30 23:58:02 [INFO] [mgmt-auth-crtb-controller] Creating role cluster-owner in namespace p-gshc2
2021/08/30 23:58:02 [ERROR] error in planner for 'fleet-default/anupamafinalrcrke2': ignore handler error
2021/08/30 23:58:02 [INFO] [mgmt-auth-prtb-controller] Creating role project-owner in namespace p-vbcpv
2021/08/30 23:58:02 [ERROR] error in planner for 'fleet-default/anupamafinalrcrke2': ignore handler error
2021/08/30 23:58:02 [ERROR] error in planner for 'fleet-default/anupamafinalrcrke2': ignore handler error
2021/08/30 23:58:02 [ERROR] error in planner for 'fleet-default/anupamafinalrcrke2': ignore handler error
2021/08/30 23:58:02 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject user-wp7pz with role project-owner in namespace
2021/08/30 23:58:02 [ERROR] error in planner for 'fleet-default/anupamafinalrcrke2': ignore handler error
2021/08/30 23:58:02 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject user-wp7pz with role cluster-owner in namespace
```

From continuous delivery --> clusters --> we see the following error on the cluster
<img width="400" alt="Screen Shot 2021-08-30 at 8 51 47 PM" src="https://user-images.githubusercontent.com/38144301/131438932-c8ba7155-5288-4875-a6e9-dac86c6afb12.png">

**Comment by thedadams** [comment]
Anupama gave me access to the Rancher instance used to create this issue and the cluster in question was provisioned correctly. Since I looked at it a week after the cluster was created, I am not sure when the cluster provisioning completed successfully.

**Comment by anupama2501** [comment]
closing this issue as this is now not reproducible and the cluster has recovered from the error state. will re-open if seen in future.
