### ISSUE TITLE
Rancher-alpha helm repo broken?

### ISSUE THREAD

**Issue by depeo** [rancher/rancher#34567]
**Rancher Server Setup**
- Rancher version: none
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): rke2
         Version: v1.21.4+rke2r1 

Trying to install rancher 2.6.0 since 2.5.9 doesn't work on kubernetes 1.21, but the rancher-alpa repo is empty?
The rancher-latest repo works fine, is the alpha repo broken or something? 

```
# ./helm repo list
NAME            URL                                              
jetstack        https://charts.jetstack.io                       
rancher-alpha   https://releases.rancher.com/server-charts/alpha 
rancher-latest  https://releases.rancher.com/server-charts/latest

# ./helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "rancher-alpha" chart repository
...Successfully got an update from the "rancher-latest" chart repository
Update Complete. ⎈Happy Helming!⎈

./helm search repo rancher-alpha/rancher --versions
No results found
```

**Comment by superseb** [comment]
What alpha version are you expecting to find? Pretty sure there hasn't been any lately.

**Comment by depeo** [comment]
> What alpha version are you expecting to find? Pretty sure there hasn't been any lately.

Oh I see, I just wanted the latest 2.6.0, the one published 2 hours ago for example, is there a helm repo for those?

**Comment by depeo** [comment]
Ah, never mind, I see 2.6.0 is stable now. thanks
