### ISSUE TITLE
[etcd snapshots with rke2, not always reproducible] etcd node was unable to recover after restoring from a snapshot

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34564]
**Rancher Server Setup**
- Rancher version:v2.6.0-rc10
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup:
         Version:1.21.4
- Proxy/Cert Details:self signed

**Information about the Cluster**
- Kubernetes version:1.21.4+rke2r1
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):AWS, 3 dedicated nodes (1 role per node)

**Describe the bug**

after restoring from a snapshot, etcd was not able to recover. The node had these errors:
```
NodeNotReady	16 mins ago	Node is not ready
Unhealthy	1.2 hours ago	Readiness probe failed: calico/node is not ready: felix is not ready: readiness probe reporting 503
Unhealthy	1.2 hours ago	Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp 127.0.0.1:9099: connect: connection refused
```

**To Reproduce**
 
* deploy a downstream cluster with dedicated nodes per role
* take a snapshot after the cluster gets to `active` state
* deploy a workload, with a nodeport
* take another snapshot after the workloads are healthy
* restore the cluster using the 1st snapshot
* wait for the cluster to go to `active` again
* check pods/workloads/nodes

**Result**
there are some pods that have not recovered like calico-typha and rke2-coredns. The etcd node is in `not ready` state

**Expected Result**

etcd should restore the cluster to an active state

**Screenshots**

**Additional context**

* I was unable to reproduce this issue using the same repro steps as listed above.

**Comment by Oats87** [comment]
As part of my work for https://github.com/rancher/rancher/issues/35468 I am thinking this may be fixed

**Comment by Oats87** [comment]
Upstream issue: https://github.com/rancher/rancher/issues/34417

**Comment by slickwarren** [comment]
blocked on https://github.com/rancher/rancher/issues/36503

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head d604b7e
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: EC2 RKE2 aws node driver
----------

### Testing: ###

Tested this issue with the following steps:
1. deploy a downstream cluster with dedicated nodes per role
2. take a snapshot after the cluster gets to active state
3. deploy a workload, with a nodeport
4. take another snapshot after the workloads are healthy
5. restore the cluster using the 1st snapshot
6. wait for the cluster to go to active again
7. check pods/workloads/nodes

**Result** - Pass

The cluster is active after restoring snapshot and pods/workloads/nodes are running as expected
