### ISSUE TITLE
Failed AD authenication for Rancher runs as contrainer inside kuberenetes 

### ISSUE THREAD

**Issue by murugesanthirumal** [rancher/rancher#34569]
*Describe your issue here*

Hi,

I trying to integrate rancher authentication with AD directory, i gave details as correct but its getting failed.
Im running rancher inside the local kubernetes cluster and we have exposed rancher app service to external load balance ip via 80,443 ports.

Do we need to enable any ports or how to check the AD server reachable to rancher container?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.9` UI: `v2.5.9` |
|Route|`undefined`|

**Comment by prachidamle** [comment]
Hi,

- Do you get any error back on UI while trying to configure/ authenticate against the AD server? 
- Any errors seen in the rancher container logs?
- Is this an HA rancher setup? 
- Are you able to connect to AD outside of rancher using say Apache Directory Studio or using ldapSearch utility?
 
 Thanks!

**Comment by murugesanthirumal** [comment]
Hi prachidamle,
Thanks for update,

I have configured AD authentication in rancher web UI using domain user name as <domain>\<domain username> format in web UI configuration, but AD user or AD group users unable to login. Even new local user also unable to create, we getting following error on web UI.

Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": service "rancher-webhook" not found

This rancher containers running inside the baremetal kubernetes cluster then its default cluster ips service is exposed via loadbalancer external ip.

When create local user getting this error.
![rancher-user-create-error](https://user-images.githubusercontent.com/6537264/131648630-19c0a884-8e2b-4541-bd0b-066a449d2140.JPG)

Same when role binding to domain group we getting following error message..
message: "Internal error occurred: failed calling webhook \"rancherauth.cattle.io\": Post \"https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s\": service \"rancher-webhook\" not found"

how to fix this and enable domain users to login rancher.
