### ISSUE TITLE
[Monitoring V2] Rebase Monitoring V2 to upstream kube-prometheus-stack 19.x.x

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#34577]
Need to rebase Monitoring V2 chart to latest upstream

**Comment by cbron** [comment]
release-note here is just that it has been upgraded

**Comment by jiaqiluo** [comment]
**NOTE: This is the draft, not the final version, and the issue is not ready for validation yet.**

---

### Root cause
Update the rancher-monitoring chart to match the upstream `kube-prometheus-stack` chart version 19.0.3

### What was fixed, or what changes have occurred
- there are lots of changes in the rancher-monitoring chart and its sub-charts
- there are fixes to some existing issues reported by users ( they are all tracked in individual issues) 

### Areas or cases that should be tested
- General functionality of rancher-monitoring 
	- The cluster explorer UI
		- the app installation page and workflow should work
		- monitoring Dashboard
			- links on the monitoring dashboard should work 
			- creating/upgrading/deleting `pod monitor` and `service monitor` should succeed and take effect
			- creating/upgrading/deleting `receiver` and `route` should succeed and take effect
		- metrics on the following page should show up with data
			- cluster dashboard
			- node detail page 
			- pod detail page 
	- Grafana 
		- all built-in dashboards should show metrics with data  
		- a new dashboard named `alertmanager-overview` is added 
	- AlertManager 
		- should receive alerts from Prometheus and show them in its UI
		- should send out alerts to the receivers configured by users 
	- Prometheus 
		- all targets should be up and healthy 
	- Thanos
		- this might be the area that we did not pay much attention to in the past, but since the upstream chart added more supports to Thanos, we should do some basic functionality checks


- Installation
	- fresh installation experience should be the same as the previous version 
- Upgrading 
	- upgrading from the previous version (100.0.0+up16.6.0) should succeed. Note: see the APP-README for a known issue and workaround  
	- `kubeStateMetrics.serviceMonitor.namespaceOverride` is replaced by `kube-state-metrics.namespaceOverride`, the upgrade should fail if `kubeStateMetrics.serviceMonitor.namespaceOverride` is passed in the value.yaml
 
 
- Support for different cluster types 
	- All already supported cluster types should continue to be supported, see the list on the installation page
- Support for different k8s version 
	- All already supported k8s versions should continue to be supported

- Support for air-gap env 
	- all new images tags should be in the `images.txt`
	- rancher-monitoring should work in air-gap env

- Support for hardened cluster 
	- rancher-monitoring should work on a handed RKE cluster
	- after rancher-monitoring is installed, the CIS scans using the following profiles should still pass: `rke-profile-hardened-1.5` and `rke-profile-hardened-1.6`
  

### What areas could experience regressions?
Nearly all areas are mentioned in the above section. 

### Are the repro steps accurate/minimal?
n/a

**Comment by jiaqiluo** [comment]
Can be tested in the rancher-monitoring  `100.1.0+up19.0.3`

**Comment by slickwarren** [comment]
- General functionality of rancher-monitoring 
	- The cluster explorer UI
		- the app installation page and workflow are working as expected — pass
		- monitoring Dashboard
			- links on the monitoring dashboard should work — pass
			- creating/upgrading/deleting `pod monitor` and `service monitor` should succeed and take effect — pass
			- creating/upgrading/deleting `receiver` and `route` should succeed and take effect — pass
		- metrics on the following page should show up with data — pass
			- cluster dashboard
			- node detail page 
			- pod detail page 
	- Grafana 
		- all built-in dashboards should show metrics with data  — pass
		- a new dashboard named `alertmanager-overview` is added — pass
	- AlertManager 
		- should receive alerts from Prometheus and show them in its UI — pass
		- should send out alerts to the receivers configured by users — pass
	- Prometheus 
		- all targets should be up and healthy —pass
	- Thanos
		- we will not test Thanos explicitly -- Expected


- Installation
	- fresh installation experience should be the same as the previous version — pass
- Upgrading 
	- upgrading from the previous version (100.0.0+up16.6.0) should succeed. — pass
	- `kubeStateMetrics.serviceMonitor.namespaceOverride` is replaced by `kube-state-metrics.namespaceOverride`, the upgrade should fail if `kubeStateMetrics.serviceMonitor.namespaceOverride` is passed in the value.yaml
 
 
- Support for different cluster types 
	- All already supported cluster types should continue to be supported, see the list on the installation page
          tested on rke1, rke2, custom clusters — pass

- Support for different k8s version 
	- All already supported k8s versions should continue to be supported
          also tested on latest versions of 1.20, 1.21, 1.22 — pass

- Support for air-gap env 
	- all new images tags should be in the `images.txt` — pass (working deployment of monitoring
	- rancher-monitoring should work in air-gap env — pass
        -unable to test rke2 in airgap [due to this issue](https://github.com/rancher/rancher/issues/35819#issuecomment-991386898) -- rke2 is not GA, so will not block on this issue

- Support for hardened cluster 
	- rancher-monitoring should work on a handed RKE cluster — pass
	- after rancher-monitoring is installed, the CIS scans using the following profiles should still pass: `rke-profile-hardened-1.5` and `rke-profile-hardened-1.6`  — pass
