### ISSUE TITLE
Provide a list of all resources being installed by rancher

### ISSUE THREAD

**Issue by azelezni** [rancher/rancher#34570]
The current helm chart doesn't represent the actual resources that will be install, the chart seems to only install the deployment, ingress, service, SA, secrets, etc...
However in reality the chart/rancher whatever installs a huge amount of bloatware that basically forces the re-creating of a cluster in case Rancher needs to be removed.

Please provide a list off *all* the resources that will be installed by the chart/rancher server.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Yeah this would be great, we also have problems with old rancher installation parts and would like to remove all old rancher things.

**Comment by snasovich** [comment]
@azelezni , Rancher creates various resources at runtime which are essential to it functioning as expected.
If you would like to remove Rancher, please follow these instructions: https://rancher.com/docs/rancher/v2.5/en/faq/removing-rancher/#what-if-i-don-t-want-rancher-anymore (for v2.5.x). The procedure is mostly automated, with only CRDs and Rancher namespaces needing to be removed manually.

Let me know if this addresses you issue or if you run into issues following this procedure.

**Comment by dveni** [comment]
Hi there, 

I'm actually having problems following that procedure. After running `system-tools remove ...`, some namespaces with their resources are left behind. For some of them, editing the ns and removing the finalizer is enough to get rid of those ns and the resources they have. For other namespaces, the resources are stuck on the `terminating` status so I need to go one by one editing the resource to remove the finalizer individually, so the resources and namespaces are deleted. 

I think this must not be the best approach, but I haven't found any other way to clean the cluster completely after uninstalling rancher. Any suggestions?

**Comment by iJebus** [comment]
Indeed, removing the finalizer is [strongly not recommended](https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-739035290). Manual cleanup of namespaces and CRDs that are stuck terminating when you don't know the sprawl of resources is tedious and time consuming at best. Or there's any easier way I don't know about /shrug.
