### ISSUE TITLE
Cluster Explorer Apps: Cannot download catalog that responds with a redirect

### ISSUE THREAD

**Issue by dasMulli** [rancher/rancher#34584]
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart): Helm chart on AKS 1.20.7
- Proxy/Cert Details: ACME

**Information about the Cluster**
- Kubernetes version: 1.20.7
- Cluster Type (Local/Downstream): AKS

**Describe the bug**
Adding an Azure Container Registry based helm chart does not work in the Cluster Explorer but does work in the Apps feature of Cluster Manager.
It seems that the Cluster Explorer implementation is unable to follow ACR's 307 redirect response while the Cluster Manager implementation is able to do this.

**To Reproduce**
Create an Azure Container Registry (e.g. `foo.azurecr.io`) and upload a Helm chart (`az acr helm push`)
Configure the Helm v1 repo URL as a catalog in Cluster Explorer and Cluster Manager - `https://foo.azurecr.io/helm/v1/repo` with HTTP Basic Auth using the keys genereated for the registry.
Observe that it works in Cluster Manager and the helm chart is shown as available app to install.
Observe that Cluster Explorer displays an error message: `failed to parse response from https://foo.azurecr.io/helm/v1/repo/index.yaml`

Using a curl command (`curl -vv --user foo:THEKEY https://foo.azurecr.io/helm/v1/repo/index.yaml`), note that the response is a `307` Redirect to an azure blob storage URL containing a shared access signature that is valid for a few minutes.

**Result**
Cluster Explorer displays an error message: `failed to parse response from https://foo.azurecr.io/helm/v1/repo/index.yaml`

**Expected Result**
The same helm chart repository should work both in Cluster Explorer and in Cluster Manager

**Comment by sgapanovich** [comment]
Confirmed the issue on 2.6.2 
Thank you for detailed steps 

-------

### Test Environment: ###
Rancher version: 2.6.-head e4db3ee
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
- Added a repo with a redirect (AZURE container registry)
    - was able to launch the app
    - was able to delete the app
      - recent operations logged every step
    - see screenshot with the issue being present in 2.6.2 and not in the head using the same http address for the helm repo
    - ![repro1](https://user-images.githubusercontent.com/40282141/145289802-4b22edce-f89c-4014-927b-502cb7aa9a5c.jpg)

- Added a public git hub repo
  - index.yaml is in this repo and a tar file is in this repo
    - was able to launch the app
    - was able to upgrade the app
    - was able to delete the app
      - recent operations logged every step
- Added a private git hub repo (using a HTTP basic auth)
  - index.yaml is in this GitHub repo referencing a tar file in a public GitLab repo 
    - was able to launch the app
    - was able to upgrade the app
    - was able to delete the app
      - recent operations logged every step
- Added a private git hub repo (using a SSH key)
  - index.yaml is in this GitHub repo referencing a tar file in a public GitLab repo 
    - was able to launch the app
    - was able to upgrade the app
    - was able to delete the app
      - recent operations logged every step

- Was able to modify repositories as 
  - config 
  - yaml

- Confirmed that logos load successfully

- Was able to successfully install Rancher and Rancher partner charts

**Comment by brendarearden** [comment]
release note: When using a helm chart repository, the `disableSameOriginCheck` setting controls when credentials are attached to requests. See [docs link] for more details.  


There is a separate issue that has been created that is adding the docs section for this.
