### ISSUE TITLE
Ingress Not Work

### ISSUE THREAD

**Issue by WeiChunKao** [rancher/rancher#34583]
*Describe your issue here*
when i build multi-node，ingress doesn't work
![image](https://user-images.githubusercontent.com/34979078/131609139-a20c1268-7d24-401f-80bf-2fce7b3ade20.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.6` UI: `v2.5.6` |
|Route|`undefined`|

**Comment by ecmrauh** [comment]
We also had problems with Ingress after upgrading to Kubernetes "v1.21.4-rancher1-1" (with rke v1.3.0). The previous upgrade of Rancher to version 2.6.0 was successful.

We observed that the ports 80 and 443 on the nodes were not open and that some pods of kube-system weren't in ready state (see above).

At first we had "enable_cri_dockerd" set to true. But that doesn't seem to be the problem.

After a downgrade to Kubernetes "v1.20.9-rancher1-1" everything worked again (still with Rancher 2.6.0).

**Comment by WeiChunKao** [comment]
@ecmrauh 
Hi I will try to downgrade to Kubernetes "v1.20.9-rancher1-1" 
I sure master node and worker node the ports 80 and 443 are open and no ap to catch these port

**Comment by superseb** [comment]
The issue is reported on Rancher v2.5.6, there is no relation to upgrading to v2.6.0/RKE v1.3.0. Please file a new issue with what you are seeing @ecmrauh 

@WeiChunKao The jobs in the screenshot are never going to be ready as they are jobs and have the completed state. The job launches the resources needed to run ingress, please share the output of `kubectl -n ingress-nginx get pods`

**Comment by WeiChunKao** [comment]
@superseb 
Hi，sorry I cut half of sreenshot
![image](https://user-images.githubusercontent.com/34979078/131660346-f2e65c77-3066-4143-962d-6ff222a14678.png)

**Comment by superseb** [comment]
Ok, that restart count is pretty high, is it going up still? What is in the log of the pod (and previous pod) to see why it restarted? How are you trying to access it, what response/error do you get when you try to create and access the ingress?

**Comment by WeiChunKao** [comment]
@superseb 
this is pod logs
i create ingress that all status is always initializing
![image](https://user-images.githubusercontent.com/34979078/131662110-b130facc-f1bb-400c-9aed-be9b8773cdda.png)

**Comment by superseb** [comment]
We need the previous pod/container logs to see why it crashes/becomes unresponsive though, `kubectl logs -p`

**Comment by evannorstrand** [comment]
I can confirm that ingress is not working on the latest version of RKE2 for Rancher 1.6.0. Rancher itself comes up no problem, no deployed applications will resolve.

**Comment by WeiChunKao** [comment]
I see docs on Rancher，but i have no idea how to operate
[](https://rancher.com/docs/rancher/v2.x/en/installation/resources/advanced/helm2/kubernetes-rke/#check-the-health-of-your-cluster-pods)

**Comment by superseb** [comment]
@evannorstrand This is for Rancher v2.5.6, please file a new issue with what you are seeing so we can investigate that.

@WeiChunKao The previous pod logs from the ingress-nginx pods will show why it crashed/stopped running. In general, please share what ingress you created, the output of where it shows Initializing in combination with the pod status (is it related to the pods not running or are they running)
