### ISSUE TITLE
[ERROR] failed to parse constraint for kubeversion >=v1.16.0-r0: Could not parse Range ">=v1.16.0-r0": Could not parse comparator ">=v" in ">=v1.16.0-r0"

### ISSUE THREAD

**Issue by mfbrj** [rancher/rancher#34588]
**Rancher Server Setup**
- Rancher version: v2.5.9
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s with 2 nodes
- Proxy/Cert Details: no proxy

**Information about the Cluster**
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-13T15:45:10Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

```
- Cluster Type (Local/Downstream): Downstream provisioned by Rancher on vSphere 6.5
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
Rancher logs of both replicas shows these messages:
```
2021/09/01 14:55:31 [ERROR] failed to parse constraint for kubeversion >=v1.16.0-r0: Could not parse Range ">=v1.16.0-r0": Could not parse comparator ">=v" in ">=v1.16.0-r0"
2021/09/01 14:55:31 [ERROR] failed to parse constraint for kubeversion >=v1.16.0-r0: Could not parse Range ">=v1.16.0-r0": Could not parse comparator ">=v" in ">=v1.16.0-r0"
2021/09/01 14:55:31 [ERROR] failed to parse constraint for kubeversion >=v1.16.0-r0: Could not parse Range ">=v1.16.0-r0": Could not parse comparator ">=v" in ">=v1.16.0-r0"
2021/09/01 14:55:31 [ERROR] failed to parse constraint for kubeversion >=v1.14.0-r0: Could not parse Range ">=v1.14.0-r0": Could not parse comparator ">=v" in ">=v1.14.0-r0"
2021/09/01 14:55:31 [ERROR] failed to parse constraint for kubeversion >=v1.14.0-r0: Could not parse Range ">=v1.14.0-r0": Could not parse comparator ">=v" in ">=v1.14.0-r0"
2021/09/01 14:55:31 [ERROR] failed to parse constraint for kubeversion >=v1.14.0-r0: Could not parse Range ">=v1.14.0-r0": Could not parse comparator ">=v" in ">=v1.14.0-r0"
2021/09/01 14:55:31 [ERROR] failed to parse constraint for kubeversion >=v1.14.0-r0: Could not parse Range ">=v1.14.0-r0": Could not parse comparator ">=v" in ">=v1.14.0-r0"
2021/09/01 14:55:31 [ERROR] failed to parse constraint for kubeversion >=v1.14.0-r0: Could not parse Range ">=v1.14.0-r0": Could not parse comparator ">=v" in ">=v1.14.0-r0"
2021/09/01 14:55:31 [ERROR] failed to parse constraint for kubeversion >=v1.14.0-r0: Could not parse Range ">=v1.14.0-r0": Could not parse comparator ">=v" in ">=v1.14.0-r0"

```

**To Reproduce**
 
These log messages are only shown when I select the project Storage (where **Longhorn** is installed) on Rancher Cluster Manager UI, and select Apps. The error messages **are not shown** when I click on Apps of other projects.

**Result**

**Expected Result**

No message errors in log.

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by jenting** [comment]
Thanks for your reporting. I can reproduce it.

![rancher-cluster-manager-longhorn](https://user-images.githubusercontent.com/49380831/131787564-3933904c-f6ae-464e-82d2-5f2961d05799.gif)

This error message comes from the rancher perform semantic version parse in https://github.com/rancher/rancher/blob/release/v2.5.9/pkg/catalog/manager/manager.go#L218-L221.
This library does not allow passing with the prefix `v` but at Longhorn chart, we had the prefix `v` https://github.com/longhorn/charts/blob/longhorn-1.1.2/charts/longhorn/Chart.yaml#L5.

**Comment by innobead** [comment]
Thanks, @jenting. It seems just erroring out w/o returning the error to stop the following installation.

**Comment by mfbrj** [comment]
> Thanks for your reporting. I can reproduce it.
> 
> ![rancher-cluster-manager-longhorn](https://user-images.githubusercontent.com/49380831/131787564-3933904c-f6ae-464e-82d2-5f2961d05799.gif)
> 
> This error message comes from the rancher perform semantic version parse in https://github.com/rancher/rancher/blob/release/v2.5.9/pkg/catalog/manager/manager.go#L218-L221.
> This library does not allow passing with the prefix `v` but at Longhorn chart, we had the prefix `v` https://github.com/longhorn/charts/blob/longhorn-1.1.2/charts/longhorn/Chart.yaml#L5.
> 
> However, from my testing, it does not block me to install the Longhorn.

@jenting You reproduced in a different way. I reproduce when a open this screen:
![image](https://user-images.githubusercontent.com/835834/133025777-b2f766c8-bdac-4681-a1c1-4e1a6098c6c7.png)
And the error messages remain displayed after upgraded from Longhorn 1.1.2 to 1.2.0.

**Comment by jenting** [comment]
We're unable to fix the previously Longhorn released version helm chart since the helm chart is immutable.

The Rancher server will go thru all the Longhorn charts when you click this page, that's why even you install/upgrade to 1.2.0, you'll still see the error log related to kubeVersion v1.14.0-r0 and v1.16.0-r0. (Note that, start from Longhorn 1.2.0 version, the minimum kubeVersion is 1.18.0-r0)

But at least, you should not see the error log related to kubeVersion 1.18.0-r0.
