### ISSUE TITLE
Docker Image incorrectly identifies as not being privileged when ran on btrfs based systems

### ISSUE THREAD

**Issue by routerino** [rancher/rancher#34582]
**Rancher Server Setup**
- Rancher version: 2.6 (also tested with 2.5.9)
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version:
* Custom = Running a docker command on a node
--> `docker run rancher/rancher --privileged`

**Describe the bug**
When running rancher from a docker container on a system that defaults to btrfs, the rancher container does not appear to recognize the fact that it is running in a privileged context.

**To Reproduce**
* Install fedora 34 with btrfs enabled
* Install docker and run the `rancher` container with the --privileged flag, it fails
* Perform an identical installation and test with xfs, the container starts normally

**Screenshots**
![image](https://user-images.githubusercontent.com/45954722/131606816-a4ba2698-9d3b-421e-8081-976a9a3e7468.png)

**Comment by routerino** [comment]
Appears to be a duplicate of the stale bug https://github.com/rancher/rancher/issues/32151 apparently it's not just an issue with Fedora.

**Comment by superseb** [comment]
I guess you are going to run into https://github.com/rancher/rancher/issues/32151 when you pass the privileged flag to Docker instead of to Rancher: `docker run --privileged rancher/rancher`

**Comment by routerino** [comment]
> I guess you are going to run into #32151 when you pass the privileged flag to Docker instead of to Rancher: `docker run --privileged rancher/rancher`

Given that I'm trying to write a guide specifically for single node deployments (targeting a homelab crowd) this is problematic. A large part of the guide hinges on using btrfs to create atomic snapshots for backups.
