### ISSUE TITLE
Restore rancher backup on another rancher instance

### ISSUE THREAD

**Issue by meysamfarazmand** [rancher/rancher#34596]
Hi,

I have a rancher cluster with six nodes (3 control plane and 3 worker) in datacenter A and my rancher server hosted in datacenter B. I want to bring up rancher server in datacenter A to manage existing cluster. I tested the following approaches:

1- take a backup from rancher in datacenter B and restore it on rancher in datacenter A. but the rancher cluster in datacenter A does not come up and some containers restarts continuously due to problem in certificates.
2- Imported cluster on Rancher in datacenter A. but I lost connectivity from rancher in datacenter B to existing cluster.

I have a question:
Is it possible to take a backup from existing rancher and restore it on another rancher instance?

**Comment by jiaqiluo** [comment]
Yes, Rancher can be migrated from one cluster to another: https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/

Approach 1 looks right to me, could you check the documentation to confirm your steps & operations are correct? 

Also, can you provide more info about your Rancher setup? What version is the Rancher and the rancher-backup app?

**Comment by meysamfarazmand** [comment]
> 
> 
> Yes, Rancher can be migrated from one cluster to another: https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/
> 
> Approach 1 looks right to me, could you check the documentation to confirm your steps & operations are correct?
> 
> Also, can you provide more info about your Rancher setup? What version are the Rancher and the rancher-backup app?

I have used rancher 2.6 in both Datacenters. Both ranchers have been installed using docker:
`sudo docker run --privileged -d --restart=unless-stopped -p 80:80 -p 443:443 -v /mnt:/mnt rancher/rancher`

the problem with the following guide is:
1- we need to bring up rancher with helm, while i am going to do it using docker
2- I must have a new Kubernetes cluster, while in my environment I don't want to set it up again
`https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/`
