### ISSUE TITLE
[Forwardport] namespaces that are later added to SystemNamespaces don't get into system-project

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#34591]
https://github.com/rancher/rancher/issues/32898

**Comment by jmcsagdc** [comment]
Verified in v2.6-78b25c3e3491244bba3f5d9d94439bbe45c99295-head

1. launch something older. I used 2.5.10
2. add a namespace outside of any project. I created "Harry"
3. use the api to add Harry as a System project
4. upgrade Rancher to 2.6-head
5. log in and see where Harry ended up in the Projects/Namespaces

EXPECTED:
Harry should be in the System project under the local cluster

ADD:

![add-harry](https://user-images.githubusercontent.com/15971368/141877632-f2d5d294-99d0-4647-8483-71fd1ff19581.jpg)

API UPDATE:

![api-harry](https://user-images.githubusercontent.com/15971368/141877670-514c9a41-fc4c-4fd4-a0d7-ffc1b3b325be.jpg)

UPGRADED:

![upgrade-harry](https://user-images.githubusercontent.com/15971368/141877703-bd3ce986-d4a6-4450-a600-8924690004e5.jpg)
