### ISSUE TITLE
[Forwardport, 2.6] Kubernetes Version in "edit cluster" not the same as in "clusters" (RKE2)

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#34597]
Forwardport to 2.6.x for https://github.com/rancher/rancher/issues/34114. The issue seems to be affecting v2.6.0 as well so it needs to be fixed there too.

**Comment by thedadams** [comment]
This was not reproducible and this issue was created before it was verified that the issue was present in v2.6. Therefore, closing the issue.
