### ISSUE TITLE
Check if each AWS security group rule exists before adding

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#3459]
The UI is stuck when selecting existing "rancher-machine" group, in the following step:
"Updating Security Group..."

The Browser console shows the following JS error:
Failed to load resource: the server responded with a status of 400 (Bad Request) http://<rancher-server>:8080/v1/proxy/ec2.eu-west-1.amazonaws.com/

**Comment by jloisel** [comment]
Workaround is to select "Use another security group" and select the same again to prevent the UI from trying to update the security group.

It's not a credentials issue since i'm using a root aws key to perform the actions.

**Comment by vincent99** [comment]
@jloisel Is this still a problem?  What's the body of the error response (from browser dev tools -> networking)?

**Comment by jloisel** [comment]
These are the errors being faced:

`<Response>
<Errors>
<Error>
<Code>InvalidPermission.Duplicate</Code>
<Message>the specified rule "peer: 0.0.0.0/0, TCP, from port: 2376, to port: 2376, ALLOW" already exists</Message>
</Error>
</Errors>
<RequestID>...</RequestID>
</Response>`

And:
`<Response>
<Errors>
<Error>
<Code>InvalidPermission.Duplicate</Code>
<Message>the specified rule "peer: 0.0.0.0/0, TCP, from port: 2376, to port: 2376, ALLOW" already exists</Message>
</Error>
</Errors>
<RequestID>80f0620c-4c29-45cd-9442-29fc7d3b47c1</RequestID>
</Response>`

**Comment by vincent99** [comment]
@jloisel This looks like it's happening because you have a group called `rancher-machine` from before we added a tag to it to ensure that it was the one we created.  (And because when adding rules we don't check if each rule exists, but it wouldn't try to if the label were there).  Simplest thing to do is delete the security group and let it be recreated.
