### ISSUE TITLE
[2.6] [Feature request] Login page should support language switching

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#34608]
We should support language switching when logging into rancher for the first time, just like v2.5.x

![image](https://user-images.githubusercontent.com/19684717/131766443-3355e8ea-b0b4-49bd-bd43-f5d7ff76d084.png)

**Comment by slickwarren** [comment]
we have an existing issue for this in the dashboard project https://github.com/rancher/dashboard/issues/3336 . This will be enabled once we fully support more languages in 2.6
