### ISSUE TITLE
DNS resolution search priority

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#3460]
Hi,

would it be possible to have in /etc/resolv.conf the domain '**rancher.internal**' first in the search list? Or perhaps make it configurable.

Reason why I'm asking is that sometimes resolutions gives back wrong results if the record one is looking up is present in one of the domains that are part of the search list.

Cheers,
Matteo

**Comment by vincent99** [comment]
Closing in favor of #3472 since it has discussion there..
