### ISSUE TITLE
Not able to edit cluster (version 2.5.9)

### ISSUE THREAD

**Issue by cloudcafetech** [rancher/rancher#34609]
Through UI (Version 2.5.9) not able to edit cluster, looks like its read only.

![image](https://user-images.githubusercontent.com/68260844/131773520-e32617e1-bf96-44ca-84b1-e891e90300a3.png)

**Comment by vincent99** [comment]
You are using a cluster template, so only what the template specified can be edited, which defaults to nothing.  To make changes, make a new revision of the template and then apply that to this cluster.

**Comment by cloudcafetech** [comment]
Thanks Vincent,

Very new in Rancher, not sure how suddenly it happened.

How to create new revision of the template and then apply to this cluster?

**Comment by Napsty** [comment]
@cloudcafetech In the Global view (not inside a cluster), select Tools -> RKE Templates.
https://rancher.example.com/g/rke-templates/index
Obviously adjust the URL to your domain.
