### ISSUE TITLE
support create k8s resource from customized template in UI

### ISSUE THREAD

**Issue by myselfghost** [rancher/rancher#34610]
**Describe the solution you'd like**
User can create some deploy templates and set some reserved variables. When click Create, you are allowed to select a template that has been set in advance. You only need to fill in a few template variables

There are 2 benefits:
1. Improve efficiency, choose a template set in advance, you can edit a lot of items less.
2. Users can be restricted not to edit certain items indiscriminately

**Comment by slickwarren** [comment]
For RKE2, we have [rke2 cluster templates in 2.6](https://rancher.com/docs/rancher/v2.6/en/admin-settings/cluster-templates/#rke2-cluster-template) which can deploy new clusters. In 2.6.1, rke2 cluster templates will have the ability to deploy resources such as Monitoring when creating via the template.

**Comment by myselfghost** [comment]
> For RKE2, we have [rke2 cluster templates in 2.6](https://rancher.com/docs/rancher/v2.6/en/admin-settings/cluster-templates/#rke2-cluster-template) which can deploy new clusters. In 2.6.1, rke2 cluster templates will have the ability to deploy resources such as Monitoring when creating via the template.

how about a deployment,a ingress,a service and so on if i want to deploy resources from a template

**Comment by myselfghost** [comment]
reopen
