### ISSUE TITLE
docker run fails: k3s exited with: exit status 1

### ISSUE THREAD

**Issue by MichaelTrip** [rancher/rancher#34617]
**Rancher Server Setup**
- Rancher version: 2.6
- Installation option (Docker install/Helm Chart):
  ```docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:latest```
**Information about the Cluster**

nothing yet

**Describe the bug**
Docker logs give a error k3s exit 1 when running the container. The container keeps restarting.

**To Reproduce**
run:
  ```docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:latest
```

**Result**

some snippets from the log file:
```
raft2021/09/02 13:27:31 INFO: 8e9e05c52164694d switched to configuration voters=()
raft2021/09/02 13:27:31 INFO: 8e9e05c52164694d became follower at term 9
raft2021/09/02 13:27:31 INFO: newRaft 8e9e05c52164694d [peers: [], term: 9, commit: 460, applied: 0, lastindex: 460, lastterm: 9]
2021-09-02 13:27:31.616111 W | auth: simple token is not cryptographically signed
2021-09-02 13:27:31.620979 I | etcdserver: starting server... [version: 3.4.15, cluster version: to_be_decided]
raft2021/09/02 13:27:31 INFO: 8e9e05c52164694d switched to configuration voters=(10276657743932975437)
2021-09-02 13:27:31.621292 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2021-09-02 13:27:31.621363 N | etcdserver/membership: set the initial cluster version to 3.4
2021-09-02 13:27:31.621401 I | etcdserver/api: enabled capabilities for version 3.4
2021-09-02 13:27:31.623159 I | embed: listening for peers on 127.0.0.1:2380
raft2021/09/02 13:27:37 INFO: 8e9e05c52164694d is starting a new election at term 9
raft2021/09/02 13:27:37 INFO: 8e9e05c52164694d became candidate at term 10
raft2021/09/02 13:27:37 INFO: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 10
raft2021/09/02 13:27:37 INFO: 8e9e05c52164694d became leader at term 10
raft2021/09/02 13:27:37 INFO: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 10
2021-09-02 13:27:37.117819 I | embed: ready to serve client requests
2021-09-02 13:27:37.117888 I | etcdserver: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
2021-09-02 13:27:37.118295 N | embed: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
2021/09/02 13:27:37 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
exit status 1
2021/09/02 13:27:44 [FATAL] k3s exited with: exit status 1
```

**Expected Result**
A running docker container so i could test out rancher 2.6 for development purposes.

**Comment by davidnuzik** [comment]
Howdy @MichaelTrip I tried testing on my box and didn't encounter this issue. I wonder if perhaps our two docker hosts differ. Hmm.

Could you perhaps provide some more info about the host? What OS and architecture and what version of docker?

In my case I ran the docker run command you mentioned on Ubuntu 20.04.2 LTS with Docker 20.10 with the root user. My box doesn't have a firewall running (shouldn't matter about the firewall though).

**Comment by MichaelTrip** [comment]
I david,

I tested this under debian 11, Fedora 34 and Manjaro 21.1.1. But i only ran this as my own user, not as root. Maybe i should try that first. I will let you know if this solves the issue.

**Comment by davidnuzik** [comment]
Technically docker shouldn't care but I do have to say that these are not supported operating systems. I would expect Debian to work but also not [supported](https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.6.0/)

**Comment by davidnuzik** [comment]
Yeah, `sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:latest` might have an impact? But not 100% sure

**Comment by superseb** [comment]
Please share `docker info` from any of the tested OS's

**Comment by MihaiSandor** [comment]
I have the same problem with latest and stable versions. 

Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-81-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.75GiB
 Name: rancher
 ID: BURM:NAZH:YF3F:VHRY:B7MD:GSOH:RU2A:ECVE:F6MG:QRWI:Y6CP:WBIW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Comment by donatasnicequestion** [comment]
the same at our environment - rancher upgrade to 2.6.0 fails with "k3s exited with: exit status 1", rancher keeps restarting. Versions 2.5.8 and 2.5.9 run fine...

```
>docker info

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 8
  Running: 7
  Paused: 0
  Stopped: 1
 Images: 9
 Server Version: 20.10.8
 Storage Driver: btrfs
  Build Version: Btrfs v4.9.1
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: ftstn46j6ex5rjnqgc9kkyfay
  Is Manager: true
  ClusterID: 5ec5l3rk72hs4cihqw5dnn8wf
  Managers: 3
  Nodes: 13
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.1.12-124.51.2.el7uek.x86_64
 Operating System: Oracle Linux Server 7.9
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.542GiB
 ID: RJEI:LREE:LF2L:57G3:NP6Z:WASA:4OPX:XQ4L:AOGH:JEBD:2P2F:MKGH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by donatasnicequestion** [comment]
k3s.log shows an error at the end: 

`E0910 13:52:02.112779      64 server.go:185] "Failed to set feature gates from initial flags-based config" err="cannot set feature gate SupportPodPidsLimit to false, feature is locked to true"
`

**Comment by cedvan** [comment]
Same result with environment :cry:  :
```
Operating System: Fedora CoreOS
Version: 34.20211031.3.0
Kernel: 5.14.14-200.fc34.x86_64
CPU: 2 Intel(R) Xeon(R) CPU E5-2470 0 
RAM: 4G
HDD0 (sda): 30G
Rancher version: v2.6.2
```

**Comment by bgant** [comment]
I just gave it a try and it still fails:

# docker -D run --rm -it --privileged rancher/rancher:latest /bin/bash
2022/01/31 22:03:11 [INFO] Waiting for k3s to start
2022/01/31 22:03:12 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/01/31 22:03:30 [FATAL] k3s exited with: exit status 1

# docker -v
Docker version 20.10.11, build e8f1871b07
