### ISSUE TITLE
Feature request: signal processes on service discovery change

### ISSUE THREAD

**Issue by DanielDent** [rancher/rancher#3461]
It would be nice to be able to add labels to services indicating that they should be sent a signal when there's been a change in a service they are linked to.

Here are two examples:
(A) The open source version of nginx is horribly broken when it comes to dealing with service discovery. Unless it is explicitly sent a signal to reload it's configuration, it won't become aware of newly added upstreams. (In some cases lua and/or non-standard syntax is an option, but this adds significant complexity. And for some of nginx's functionality, it's not a very realistic option.)

(B) The current stable version of zookeeper doesn't re-resolve DNS after it's been started (there is a merged patch with semi-deals with this issue, but it hasn't made it's way into a stable release). Killing zookeeper when there are changes to the IPs it should be connecting to may be a reasonable approach in some environments.

Services which don't re-resolve DNS are surprisingly common, and it would be nice to have Rancher provide ways of dealing with this.

**Comment by smw355** [comment]
+1

**Comment by cloudnautique** [comment]
You can monitor the services containers using Rancher Metadata, and make adjustments with something like confd or custom rolled. That part is straight forward'ish, watches on metadata would be nice.

**Comment by will-chan** [comment]
Closed due to inactivity.
