### ISSUE TITLE
[question] Is there a way to customize the rancher/shell docker image?

### ISSUE THREAD

**Issue by devopstales** [rancher/rancher#34611]
Add ability to customize `rancher/shell` image and where to deploy the pod (namespace). I would like to install a few more tools in the "Rancher Shell" like `istioctl` and `kubens` etc. If there would be an option to select namespace and add tags it would be easier to debug network policies.

**Comment by devopstales** [comment]
still valid.

**Comment by niusmallnan** [comment]
@devopstales you can try this setting: https://github.com/rancher/rancher/blob/release/v2.5/pkg/settings/setting.go#L94
And build the image from this repo: https://github.com/rancher/shell
