### ISSUE TITLE
Support install docker by "rancher/install-docker" on Rocky Linux/OpenSUSE/RHEL/SLES

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#34615]
**While testing the docker installtion script on Rocky Linux-8.4, OpenSUSE-15SP3, SLES-15SP3 and RHEL-8.4  as per the support matrix of Rancher 2.6.0 it's failing.**

What kind of request is this (question/bug/enhancement/feature request):
bug

**Steps to reproduce:**

1) Create a Rocky Linux-8.4 / OpenSUSE-15sp3/RHEL8.4/SLES15SP3 VM
2) Run "`curl https://raw.githubusercontent.com/rayandas/install-docker/feature/20.10.8/dist/20.10.8.sh | sh`". This is the docker script with support of docker 20.10.8 installation and it's NOT merged yet.      

**Result:**

1. On OpenSUSE-15SP3

```
cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
...
```
```
# Executing docker install script, commit: 0e685c6ac0bddd7b2ba7bcaaeb519746ad249a29

ERROR: Unsupported distribution 'opensuse-leap'
```

2. On Rocky Linux8.4

```
cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel fedora"
...
```
```
# Executing docker install script, commit: 7cae5f8b0decc17d6571f9f52eb840fbc13b2737

ERROR: Unsupported distribution 'rocky'
```

3. On SLES-15-SP3 
```
cat /etc/os-release 
NAME="SLES"
VERSION="15-SP3 PublicRC"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3 (PublicRC)"
ID="sles"
ID_LIKE="suse"
...
```
```
# Executing docker install script, commit: 0e685c6ac0bddd7b2ba7bcaaeb519746ad249a29
Packages for SLES are currently only available for s390x
```

4. On RHEL 8.4
```
cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
...
```
```
# Executing docker install script, commit: 0e685c6ac0bddd7b2ba7bcaaeb519746ad249a29
Packages for RHEL are currently only available for s390x.
```

**Comment by snasovich** [comment]
@deniseschannon , does it need to be in v2.6.1 (I saw your conversation with @cloudnautique and I don't see a conclusion there).

**Comment by deniseschannon** [comment]
Let's use this issue to track the work with trying to update install docker so that if there is no package available when running 20.10.sh, it checks from the latest 20.10.x version to the oldest to see/try to find a version that will install.

**Comment by rayandas** [comment]
Fix: https://github.com/rancher/install-docker/pull/83

**Comment by rayandas** [comment]
Validation steps:

Create AWS infrastructure provider with 3 nodes, 1 role each.
- Change Docker Install URL to `https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.8.sh` in node template (as current changes are not synced yet with CDN release.rancher.com).
- Launch cluster and wait for cluster to become available.
- Do the same for Docker version `20.10.9`, `20.10.10`, `20.10.11`

Create DO infrastructure provider with 3 nodes, 1 role each.
- Change Docker Install URL to `https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.8.sh` in node template.
- Launch cluster and wait for cluster to become available.
- Do the same for Docker version `20.10.9`, `20.10.10`, `20.10.11`

Create a custom cluster, 1 node all roles.
- Install Docker using `https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.8.sh`
- Launch cluster and wait for cluster to become available.
- Do the same for Docker version `20.10.9`, `20.10.10`, `20.10.11`

**Comment by jonathon2nd** [comment]
This gives me big sad :sob: 
![Screenshot_20220224_151534](https://user-images.githubusercontent.com/52681917/155616626-90e827ac-49f6-4344-a6a3-2b0ef44e0240.png)

What is particularly strange is that installing docker with cloud init does not fix it, as the script runs anyway.
```
[root@worker1 rocky]# curl https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.7.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17683  100 17683    0     0  73679      0 --:--:-- --:--:-- --:--:-- 73679
# Executing docker install script, commit: 7cae5f8b0decc17d6571f9f52eb840fbc13b2737
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20

ERROR: Unsupported distribution 'rocky'

[root@worker1 rocky]#  docker

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

```

**Comment by rayandas** [comment]
Hello @jonathon2nd we're introducing Rocky Linux support from >=20.10.8 Docker versions.
The PR is up https://github.com/rancher/install-docker/pull/91

**Comment by rayandas** [comment]
Validation steps:

Create AWS infrastructure provider with 3 nodes, 1 role each.

- Change Docker Install URL to https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.7.sh in node template (as current changes are not synced yet with CDN release.rancher.com).
- Do the same for Docker version `20.10.8`, `20.10.9`, `20.10.10`, `20.10.11`, `20.10.12`
- Launch cluster and wait for cluster to become available.

Create DO infrastructure provider with 3 nodes, 1 role each.

- Change Docker Install URL to https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.7.sh in node template.
- Do the same for Docker version `20.10.8`, `20.10.9`, `20.10.10`, `20.10.11`, `20.10.12`
- Launch cluster and wait for cluster to become available.

Create a custom cluster, 1 node all roles.

- Install Docker using https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.7.sh
- Do the same for Docker version `20.10.8`, `20.10.9`, `20.10.10`, `20.10.11`, `20.10.12`
- Launch cluster and wait for cluster to become available.

**Comment by rishabhmsra** [comment]
Validated this on v2.6-head(39befda).

The docker [installation script](https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.7.sh) is failing on CentOS 8.3, while provisioning ec2 node driver, `1.22.6-rancher1-2` k8s cluster (single node)

**Rancher server logs :**
```
2022/03/03 13:42:17 [INFO] [node-controller-rancher-machine] (rishabh-centos1) Settings tags for instance
2022/03/03 13:42:20 [INFO] [node-controller-rancher-machine] Waiting for machine to be running, this may take a few minutes...
2022/03/03 13:42:24 [INFO] [node-controller-rancher-machine] Detecting operating system of created instance...
2022/03/03 13:42:24 [INFO] [node-controller-rancher-machine] Waiting for SSH to be available...
2022/03/03 13:43:23 [INFO] [node-controller-rancher-machine] Detecting the provisioner...
2022/03/03 13:43:27 [INFO] [node-controller-rancher-machine] Provisioning with centos...
2022/03/03 13:43:55 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2022/03/03 13:43:55 [INFO] [node-controller-rancher-machine] 
2022/03/03 13:43:55 [INFO] Generating and uploading node config rishabh-centos1
2022/03/03 13:43:55 [ERROR] error syncing 'c-nqrn2/m-5qxmb': handler node-controller: Error creating machine: RHEL ssh command error: command: sudo -E yum install -y curl erCentOS Linux 8 - AppStream                      128  B/s |  38  B     00:00    , requeuing     --:-- ETA
```

**Note :** I'm getting the same error when it tried to provision the cluster using released version of [script](https://releases.rancher.com/install-docker/20.10.sh) as well.

**Comment by vivek-infracloud** [comment]
Validated the latest docker install script for RHEL on v2.6-head(39befda).

Docker install script fails on RHEL 8.4 with following error.
`ERROR] error syncing 'c-vxp4z/m-hkskr': handler node-controller: Error creating machine: Error installing Docker: , requeuing`

**Comment by rishabhmsra** [comment]
Validated this on rancher v2.6-head(bab14a3)

Provisioned node driver clusters using docker versions `20.10.7, 20.10.8, 20.10.9, 20.10.10, 20.10.11` on below OSes :
- Ubuntu : Clusters provisioned successfully using all the docker versions.
- RHEL : Cluster provisioned successfully using `20.10.7` (version >= 20.10.8 are not supported)
- Rocky : Clusters provisioned successfully using all the docker version except 20.10.7 as it's not supported.

Custom clusters :
- Ubuntu : Clusters provisioned successfully using all the docker versions.
- RHEL : Cluster provisioned successfully using `20.10.7` (version >= 20.10.8 are not supported)
- Rocky : Clusters provisioned successfully using all the docker version except 20.10.7 as it's not supported.
- CentOS : Clusters provisioned successfully using all the docker versions.

@rayandas on SLES 15-sp3, docker 20.10.9-ce was pre-installed and on running the script I'm getting below errors:
- using release version of script :
```
curl https://releases.rancher.com/install-docker/20.10.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17683  100 17683    0     0  62045      0 --:--:-- --:--:-- --:--:-- 62045
# Executing docker install script, commit: 7cae5f8b0decc17d6571f9f52eb840fbc13b2737
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20

ERROR: Unsupported distribution 'sles'
```

- using script with latest changes :
```
curl https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.10.sh|sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21946  100 21946    0     0   159k      0 --:--:-- --:--:-- --:--:--  159k
# Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c32be
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20
Packages for SLES are currently only available for s390x
```

**Comment by rayandas** [comment]
The SLES support came from upstream (from >=20.10.8), we didn't add anything. SLES-15-sp3 isn't s390x so that's why this error is coming. It's same as RHEL when we try to install docker >=20.10.8 then it'll throw the same error as Packages for RHEL are currently only available for s390x.
Also Docker comes pre installed on all the SLES OSes, I don't thing this will be a problem.
/cc: @kinarashah
