### ISSUE TITLE
Bug:  Load balancers stuck in "Initializing" state

### ISSUE THREAD

**Issue by wundram** [rancher/rancher#3462]
Since upgrade to 0.56.1 we are noticing that some of our load balancers are staying stuck in the "initializing" state.   It seems that the they are functioning, but just show as yellow in the UI.

![image](https://cloud.githubusercontent.com/assets/2318544/12680327/d66312f6-c66e-11e5-933d-c0b3083658ab.png)

![image](https://cloud.githubusercontent.com/assets/2318544/12680341/f0045954-c66e-11e5-9d2e-4237d9a01b7b.png)

**Comment by wundram** [comment]
Here is the log from the LB


1/29/2016 9:56:52 AMINFO: Downloading agent http://rancherdev.ezesoft.net:8080/v1/configcontent/configscripts
1/29/2016 9:56:52 AMINFO: Updating configscripts
1/29/2016 9:56:52 AMINFO: Downloading http://rancherdev.ezesoft.net:8080/v1//configcontent//configscripts current=
1/29/2016 9:56:52 AMINFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/apply.sh
1/29/2016 9:56:52 AMINFO: Sending configscripts applied 1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319
1/29/2016 9:56:52 AMINFO: Updating agent-instance-startup
1/29/2016 9:56:52 AMINFO: Downloading http://rancherdev.ezesoft.net:8080/v1//configcontent//agent-instance-startup current=
1/29/2016 9:56:53 AMINFO: Running /var/lib/cattle/download/agent-instance-startup/agent-instance-startup-1-13b77b6b2958f4f7ddf0a3f929209bd3b041ba6474835abd5b4e8cb8ed26e829/apply.sh
1/29/2016 9:56:53 AMINFO: Updating services
1/29/2016 9:56:53 AMINFO: Downloading http://rancherdev.ezesoft.net:8080/v1//configcontent//services current=
1/29/2016 9:56:53 AMINFO: Running /var/lib/cattle/download/services/services-1-061405f3edd960bfdfe1cfb8447be40eab5b4b608731608e224cc51c5dc30b91/apply.sh
1/29/2016 9:56:53 AMINFO: HOME -> ./
1/29/2016 9:56:53 AMINFO: HOME -> ./services
1/29/2016 9:56:53 AMINFO: Sending services applied 1-061405f3edd960bfdfe1cfb8447be40eab5b4b608731608e224cc51c5dc30b91
1/29/2016 9:56:53 AMINFO: Getting agent-instance-scripts
1/29/2016 9:56:53 AMINFO: Updating agent-instance-scripts
1/29/2016 9:56:53 AMINFO: Downloading http://rancherdev.ezesoft.net:8080/v1//configcontent//agent-instance-scripts current=
1/29/2016 9:56:53 AMINFO: Running /var/lib/cattle/download/agent-instance-scripts/agent-instance-scripts-1-4b5124bd74cd423f98d57550b481ec77ec3a7135c6a650886ab95c043305d642/apply.sh
1/29/2016 9:56:53 AMINFO: HOME -> ./
1/29/2016 9:56:53 AMINFO: HOME -> ./events/
1/29/2016 9:56:53 AMINFO: HOME -> ./events/config.update
1/29/2016 9:56:53 AMINFO: HOME -> ./events/ping
1/29/2016 9:56:53 AMINFO: Sending agent-instance-scripts applied 1-4b5124bd74cd423f98d57550b481ec77ec3a7135c6a650886ab95c043305d642
1/29/2016 9:56:53 AMINFO: Getting monit
1/29/2016 9:56:53 AMINFO: Updating monit
1/29/2016 9:56:53 AMINFO: Downloading http://rancherdev.ezesoft.net:8080/v1//configcontent//monit current=
1/29/2016 9:56:53 AMINFO: Running /var/lib/cattle/download/monit/monit-1-4bf21eaa37373e2770bfb922848a07f801e32826d5a1048c98e5c2b8e7ff2dcc/apply.sh
1/29/2016 9:56:53 AMINFO: ROOT -> ./
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/logrotate.d/
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/logrotate.d/rancher-logs
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/monit/
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/monit/conf.d/
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/monit/conf.d/logrotate
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/monit/monitrc
1/29/2016 9:56:53 AMINFO: Sending monit applied 1-4bf21eaa37373e2770bfb922848a07f801e32826d5a1048c98e5c2b8e7ff2dcc
1/29/2016 9:56:53 AMINFO: Getting haproxy
1/29/2016 9:56:53 AMINFO: Updating haproxy
1/29/2016 9:56:53 AMINFO: Downloading http://rancherdev.ezesoft.net:8080/v1//configcontent//haproxy current=
1/29/2016 9:56:53 AMINFO: Running /var/lib/cattle/download/haproxy/haproxy-3-3e0d61c5cd2851e80416ea7bdd7aa59b417a3f11fa7852d0f0f91a26a6cdadb9/apply.sh
1/29/2016 9:56:53 AMINFO: ROOT -> ./
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/haproxy/
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/haproxy/certs/
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/haproxy/certs/certs.pem
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/haproxy/certs/default.pem
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/haproxy/haproxy.cfg
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/default/
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/default/haproxy
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/monit/
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/monit/conf.d/
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/monit/conf.d/haproxy
1/29/2016 9:56:53 AMINFO: Sending haproxy applied 3-3e0d61c5cd2851e80416ea7bdd7aa59b417a3f11fa7852d0f0f91a26a6cdadb9
1/29/2016 9:56:53 AMINFO: HOME -> ./
1/29/2016 9:56:53 AMINFO: HOME -> ./etc/
1/29/2016 9:56:53 AMINFO: HOME -> ./etc/cattle/
1/29/2016 9:56:53 AMINFO: HOME -> ./etc/cattle/startup-env
1/29/2016 9:56:53 AMINFO: ROOT -> ./
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/init.d/
1/29/2016 9:56:53 AMINFO: ROOT -> ./etc/init.d/agent-instance-startup
1/29/2016 9:56:53 AMINFO: Sending agent-instance-startup applied 1-13b77b6b2958f4f7ddf0a3f929209bd3b041ba6474835abd5b4e8cb8ed26e829
1/29/2016 9:56:53 AMmonit: generated unique Monit id 0fdc20a7309dc47ced770790155f9996 and stored to '/var/lib/monit/id'
1/29/2016 9:56:53 AMStarting monit daemon with http interface at [localhost:2812]

**Comment by deniseschannon** [comment]
It sounds like your issue is around host connectivity. This was a duplicate issue: https://github.com/rancher/rancher/issues/3413

Everyone in the issue had gotten it resolved once their cross host communication was fixed. 

I saw you comment on the other ipsec issues, can you try the recommended fixes?

**Comment by deniseschannon** [comment]
@wundram If you are still having issues, please re-open with more details on if your host connectivity is working.

**Comment by defunctzombie** [comment]
@deniseschannon I am experiencing this issue on Rancher v1.0.1. At first it was indeed host connectivity (had aws security groups for a box misconfigured so the IPSec network didn't allow traffic). After I resolved that, the LB is working correctly but still says `Initializing` on the interface. I've tried restarting the LB. All of the services it is proxying for are healthy.

**Comment by mattapperson** [comment]
@deniseschannon having this issue with v1.1.0-dev2-rc4. all hosts can reach each other and all connected services are healthy

**Comment by deniseschannon** [comment]
@defunctzombie @mattapperson Have you both confirmed that IPsec is working?

You would need to exec into the network agent of 1 host and ping the network agent IP (i.e. 10.42.x.x) on another host. 

Typically a load balancer stuck in initializing is due to health checks not working, which is due to IPsec not working.

**Comment by mattapperson** [comment]
@deniseschannon my issue was fixed after I realized 2 of my network agent containers never updated and docker versions were not the same on all servers. After forcing upgrades they all worked

**Comment by defunctzombie** [comment]
Is there a way to see some diagnostics about which particular health check is failing? Seems strange that all traffic on the load balancer works but it itself is not initialized.

**Comment by pwFoo** [comment]
Same problem with LBs. Also if the LB ist running on the same host as rancher server (tested with latest and dev build).

Following here...

**Comment by pwFoo** [comment]
After reinstall my hosts (3 hosts, one additional with Rancher Server) with latest images the LB at the host with RancherServer stucks with "Initializing" state. Both other hosts work fine.

**Comment by EugenMayer** [comment]
Same issue here. I only have one host even - worked before, but i had to remake the load balancer due to certificates, now it stucks on initialize

**Comment by aemneina** [comment]
There are multiple comments in this zombie thread. If you're facing issues with RancherHA check [here](https://github.com/rancher/rancher/issues/4634#issuecomment-218822409) for a comprehensive troubleshooting guide.

If after following that, open a new issue. Make sure the environment configuration is in place before launching, after making a change, delete containers and relaunch.

**Comment by EugenMayer** [comment]
@aemneina i am not using rancherHA at all, i cannot see how this is related. I have 2 LB, one for a TCP connection - works. The other, i had before and recreating now, stucked in initialize

**Comment by aemneina** [comment]
@EugenMayer sorry, misread the issue completely.
