### ISSUE TITLE
[2.6] Forwardport vSphere CSI

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#34628]
Forwardport of: https://github.com/rancher/rancher/issues/34630

Note: We are considering moving the CSI chart to live with the other RKE2 charts so this issue might need to be refactored once a decision has been made.

**Comment by vivek-infracloud** [comment]
**Test Environment**

- Rancher Version:v2.6-head (a2ae06c)
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**

- Kubernetes version: v1.20 and v1.21 was used.
- Cluster Type(s) tested on (Local/Downstream): Downstream

**Result of validation**
CPI and CSI Chart installation was successful.
Pod was successfully created with volume attached to it.
Fresh install checks **passed**.

**Comment by PennyScissors** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/35378
