### ISSUE TITLE
[2.5] Rancher Logging backports

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#34625]
rancher 2.6 introduced a multitude of changes that we want to bring into 2.5:
- windows path fixes rancher/rancher#33940
- windows path fixes for rke agent rancher/rancher#33939
- k3s uses journald for controlplane logs rancher/rancher#33938
- exposed toggle to strip underscore prefixes on journald logs rancher/rancher#33937
- k3s logs now all have timestamps rancher/rancher#33936
- rke2 control plane logs are richer with more metadata rancher/rancher#33935
- k3s agent logs are collected rancher/rancher#33934
- fluentd replicas can now be configured rancher/rancher#33933

**Comment by ronhorton** [comment]
**PASS** Verified in `2.5-head Commit ID bea1658`

rancher 2.6 introduced a multitude of changes that we want to bring into 2.5. The following issues were verified:

windows path fixes [v2.5.10] Backport: [Logging v2] Ensure Windows paths match internal standards #33940
windows path fixes for rke agent [v2.5.10] Backport: [Logging v2] - win-agent-rke invalid volume specification when using a non default win_prefix_path #33939
k3s uses journald for controlplane logs [v2.5.10] Backport: Switch K3S to Journald login plugin for control plane logs. #33938
exposed toggle to strip underscore prefixes on journald logs [v2.5.10] Backport: [Logging v2] Make strip underscores optional in journald logging config #33937
k3s logs now all have timestamps [v2.5.10] Backport: K3S logs don't always have timestamps #33936
k3s agent logs are collected [v2.5.10] Backport: Collect k3s-agent.service logs in addition to k3s.service #33934
fluentd replicas can now be configured [v2.5.10] Backport: Support configuration of multiple replicas for Rancher-logging chart components such as fluentd #33933
