### ISSUE TITLE
vSphere cluster loses management if using DHCP

### ISSUE THREAD

**Issue by Twiiiiin** [rancher/rancher#34637]
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s version v1.21.4+k3s1 (3e250fdb)
- Proxy/Cert Details: NoProxy / Self signed Cert

**Information about the Cluster**
- Kubernetes version: 1.21.4-rancher1-1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vSphere

**Describe the bug**
When provisioning a RKE1 cluster with vSphere and DHCP managed IP addresses the cluster works correctly until the DHCP server renews a lease for one of the masters, after that management for the cluster is lost on Rancher side, even if the underlying kubernetes keeps working flawlessly.

With the actual infrastructure I'm using, this kind of change in IP's happens once every two or three hours, so the cluster doesn't survive over an hour.

As I'm using PFSense as a router, i cannot assign reservations inside the DHCP pool, so after the reservation is done, IP will change to that and the issue will be there. Also, PFSense doesn't have APIs for automating the task of creating a reservation *before* the VM starts, so DHCP looks like the only way

**To Reproduce**
- Install Rancher on a random machine
- Provision a cluster following the UI instructions (no additional cloud init - base ubuntu server 20.04 template api data as below)
**template:**
>`{
"annotations": {
"ownerBindingsCreated": "true"
},
"baseType": "nodeTemplate",
"cloudCredentialId": "cattle-global-data:cc-fbfdf",
"created": "2021-09-02T08:27:41Z",
"createdTS": 1630571261000,
"creatorId": "user-vkj5t",
"driver": "vmwarevsphere",
"engineInstallURL": "https://releases.rancher.com/install-docker/20.10.sh",
"engineRegistryMirror": [ ],
"id": "cattle-global-nt:nt-x489n",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"nodePools": "…/v3/nodePools?nodeTemplateId=cattle-global-nt%3Ant-x489n",
"nodes": "…/v3/nodes?nodeTemplateId=cattle-global-nt%3Ant-x489n",
"remove": "…/v3/nodeTemplates/cattle-global-nt:nt-x489n",
"self": "…/v3/nodeTemplates/cattle-global-nt:nt-x489n",
"update": "…/v3/nodeTemplates/cattle-global-nt:nt-x489n"
},
"name": "master",
"principalId": "local://user-vkj5t",
"state": "active",
"transitioning": "no",
"transitioningMessage": "",
"type": "nodeTemplate",
"useInternalIpAddress": true,
"uuid": "3b8a610b-146e-464d-b650-12e3d7a1eea5",
"vmwarevsphereConfig": {
"boot2dockerUrl": "",
"cfgparam": [
"disk.enableUUID=TRUE"
],
"cloneFrom": "/Cluster/datastore/template-ubuntu-2004",
"cloudConfig": "",
"cloudinit": "",
"contentLibrary": "",
"cpuCount": "4",
"creationType": "template",
"customAttribute": [ ],
"datacenter": "/Cluster",
"datastore": "/Cluster/datastore/VM_417_Kubernetes",
"datastoreCluster": "",
"diskSize": "30000",
"folder": "/Cluster/Kubernetes",
"hostsystem": "",
"memorySize": "4096",
"network": [
"/Cluster/network/VLAN 402"
],
"pool": "Cluster/host/Host01/Resources/Kubernetes",
"sshPassword": "tcuser",
"sshPort": "22",
"sshUser": "docker",
"sshUserGroup": "staff",
"tag": [ ],
"username": "",
"vappIpallocationpolicy": "dhcp",
"vappIpprotocol": "IPv4",
"vappProperty": [ ],
"vappTransport": "com.vmware.guestinfo",
"vcenter": "",
"vcenterPort": "443"
}
}`
**Kubernetes Options:**
>`docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
name: kube-test
rancher_kubernetes_engine_config:
  addon_job_timeout: 45
  authentication:
    strategy: x509
  dns:
    nodelocal:
      ip_address: ''
      node_selector: null
      update_strategy: {}
  enable_cri_dockerd: false
  ignore_docker_version: true
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk: {}
      global:
        insecure-flag: false
        soap-roundtrip-count: 0
      network: {}
      virtual_center:
        vcenter.local:
            user: <user>
            password: <password>
            datacenters: /Clsuter
            port: '443'
            soap-roundtrip-count: 0
      workspace:
        datacenter: /Cluster
        default-datastore: /Cluster/VM_417_Kubernetes
        folder: /Cluster/Kubernetes
        resourcepool-path: /Cluster/host/Host01/Resources/Kubernetes
        server: vcenter.local
  ingress:
    default_backend: false
    http_port: 0
    https_port: 0
    provider: nginx
  kubernetes_version: v1.21.4-rancher1-1
  monitoring:
    provider: metrics-server
    replicas: 1
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: canal
  rotate_encryption_key: false
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
        timeout: 300
      creation: 12h
      extra_args:
        election-timeout: 5000
        heartbeat-interval: 500
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube_api:
      always_pull_images: false
      pod_security_policy: false
      secrets_encryption_config:
        enabled: false
      service_node_port_range: 30000-32767
  ssh_agent_auth: false
  upgrade_strategy:
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
windows_prefered_cluster: false`
- IP Addressing is provided via DHCP (only way to do it dynamically, as the router is an external PFSense appliance)
- Wait until lease is changed / forcibly ask for a new lease

**Result**
- Connection to master fails because the Management UI keeps contacting the old IP 

**Expected Result**
- As Kubernetes already does, take the new IP for the masters
- Alternatively mark the node as unreachable and redeploy it

**Screenshots**
- Cluster works properly after being just made
![image](https://user-images.githubusercontent.com/15817743/131959803-a815d84b-8d3d-4801-8165-de307a761212.png)
![image](https://user-images.githubusercontent.com/15817743/131960102-11d3cdb3-88fa-4bac-a6dd-d5d343b7ec95.png)
- The bug itself
![image](https://user-images.githubusercontent.com/15817743/131961104-8a06e32d-7adb-4789-90ed-ba6258db0461.png)
IP changed on master node (as you can see i've already tried with very long leases but doesn't seem to comply, now i've forced the bug for reporting reasons)
![image](https://user-images.githubusercontent.com/15817743/131961241-e0afcb07-5b4e-451d-835d-013592b457fe.png)
IP on the UI stays the same 
![image](https://user-images.githubusercontent.com/15817743/131961333-1103236e-c2ae-4985-8d0e-274476a95a1f.png)
This error is shown, which explains it's trying to contact the old IP

**Additional context**
vSphere provisioning seems to be **required** to use the CSI driver, this issue is blocking for that reason

**Comment by David-VTUK** [comment]
Hi @Twiiiiin 

As per https://rancher.com/docs/rancher/v2.x/en/installation/requirements/#node-ip-addresses, you can use DHCP, and this is common, but this should be used in conjunction with DHCP reservations or custom DHCP server config so nodes have a reliable, unchanged private address across their entire lifecycle.

I wrote this which may help if DHCP isn't an option in this configuration: https://www.virtualthoughts.co.uk/2020/03/29/rancher-vsphere-network-protocol-profiles-and-static-ip-addresses-for-k8s-nodes/

**Comment by Twiiiiin** [comment]
Hi @David-VTUK 
Thanks for the answer, i'll definitely follow the guide. Though i think the problem could be worse than that. As it seems Rancher connects only to one node as master of the k8s cluster and if that node fails for some reason (and doesn't come up working with the same IP), the management of the cluster is lost. I think this is also for other providers and not only for vSphere. 
Isn't there a way to actually bind the management API to all the masters?
Maybe a virtual IP which represents the master pool? Or a service mesh proxy?

**Comment by intonet** [comment]
If you use Ubuntu try option in netplan
critical: true

https://netplan.io/reference/
critical (bool)
Designate the connection as “critical to the system”, meaning that special
care will be taken by to not release the assigned IP when the daemon is
restarted. (not recognized by NetworkManager)

You can add configuration in template as Cloud Config YAML
```
#cloud-config
users:
  - default
 
write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    content: |
      network:
        version: 2
        ethernets:
          ens192:
            dhcp4: true
            critical: true
```
This option  prevent to release IP address before  restart/poweroff. Works for me.
