### ISSUE TITLE
[2.5] Update vSphere CSI to latest upstream

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#34630]
Current latest upstream is v2.3.0

**Comment by slickwarren** [comment]
**Test Environment**
- Rancher Version:v2.5-head (ce52c78)
- Installation option (Docker install/Helm Chart):docker 

**Information about the Cluster**
- Kubernetes version:1.19 was primarily used. Some upgrade tests, 1.19 -> 1.20
- Cluster Type(s) tested on (Local/Downstream):downstream

**Overview of Validation**

The following were done on multinode (1cp, 1etcd, 3worker) clusters and was tested with the latest cpi version/ticket (v1.0.100)
* on 2.5.9, install cpi:1.0.000 and csi:2.1.0. Upgrade rancher, then upgrade the charts to 1.0.100 and 2.3.0 respectively -- pass
* on 2.5.9, configure in-tree provider on a cluster. upgrade rancher, migrate to out-of-tree using the latest charts -- pass
  * upgrading the k8s version is causing an issue, which is not a regression as it is reproducible on 2.5.9, so I've [filed a separate ticket for this](https://github.com/rancher/rancher/issues/35102)
* edit the values.yaml for cpi chart, and override the version installed for the cluster -- pass
* Upgrading from Rancher v2.5.9 with the existing chart installed then upgrade chart to new one.
* enable volume resizing on the csi chart. provision a volume, and resize it -- pass
  * ensure online resizing is enabled; provision a workload with a bound volume; resize the volume -- fail 
    * we got a generic error, suggesting that our testing environment may have some versioning issue (ignoring this failure for now since volumes not attached to a workload is working, which is [in the same set of documentation in csi](https://vsphere-csi-driver.sigs.k8s.io/features/volume_expansion.html))
