### ISSUE TITLE
[2.6] Deployment create, missing Volume Type "emptyDir"

### ISSUE THREAD

**Issue by ItsReddi** [rancher/rancher#34638]
**Rancher Server Setup**
- Rancher version: 2.6
- Installation option (Helm Chart):
   - RKE1, kubernetes 1.21

**Describe the bug**
If you create a deployment and want to add an emptyDir volume, you cannot select that from volume type dropdown
```
      volumes:
      - emptyDir: {}
        name: somename
```

**To Reproduce**
1. Create a deployment
2. Storage -> Add Volume
3. emptyDir not existent

update issue:
1. Import a deployment with an empty dir
2. update the deployment
3. storage, you are unable to change the name of the emptyDir mount, no field available

**Result**

**Expected Result**
1. EmptyDir is available in dropdown
2. EmptyDir name can be changed on update of an deployment

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3147888/131963000-bc060ea9-5b95-4f21-a2fc-cdc602310daa.png)
![grafik](https://user-images.githubusercontent.com/3147888/131963125-9f7783f5-2abc-45ca-8b69-ac0be187c28b.png)

**Comment by LinAnt** [comment]
https://github.com/rancher/rancher/issues/25131

**Comment by LeCodeCo** [comment]
This issue is still present in Rancher 2.6.2.

**Comment by anjia0532** [comment]
This issue is still present in Rancher 2.6.3.

**Comment by gaby** [comment]
> This repository uses a bot to automatically label issues which have not had any activity (commit/comment/label) for 60 days. This helps us manage the community issues better. If the issue is still relevant, please add a comment to the issue so the bot can remove the label and we know it is still valid. If it is no longer relevant (or possibly fixed in the latest release), the bot will automatically close the issue in 14 days. Thank you for your contributions.

Issue still valid....

**Comment by hanxinhang** [comment]
This issue is still present in Rancher 2.6.5

**Comment by bromine0x23** [comment]
This issue is still present in Rancher 2.6.8

**Comment by MichelZ** [comment]
Successor: #36760

**Comment by gmanera** [comment]
Same problem.
Rancher Version: v2.6.8
K8S Version: 23.10
