### ISSUE TITLE
No way to unlink a Cluster from a Cluster Template

### ISSUE THREAD

**Issue by lonewulf** [rancher/rancher#34640]
**Is your feature request related to a problem? Please describe.**
Once a cluster is created from a template, there is now way to unlink it from said template. Please asd a way to unlink a cluster from cluster templates

**Describe the solution you'd like**
When a cluster is linked to a template there is no way to undo it appart from deleting the cluster and recreating it, which is not an acceptable solution,  even more with a Production envrionment. Please add a way to unlink the cluster from the template.

**Describe alternatives you've considered**
Maybe there is an alternative way doing it via kubectl on the Rancher cluster

**Comment by abhi1693** [comment]
This would be a great feature to have

**Comment by abhi1693** [comment]
Relevant

**Comment by lonewulf** [comment]
Hello,

I still need a solution for this, even if not integrated within Rancher.

Regards,
