### ISSUE TITLE
Tooltip stays up in different scenarios

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3464]
Version master 1/27

Steps:
1.  Create a stack
2.  Click on stack name
3.  Hover your mouse over Graph icon until "Graph" tooltip pops up
4.  Click on Graph and move your mouse away from icon
5.  Change pages

Results:
Graph tooltip stays open.  This happen with all three icon tooltips (List, Graph and Compose).  This view thing is similar to Host page, but on the host page it is working properly.
![image](https://cloud.githubusercontent.com/assets/11514927/12682500/0895710e-c671-11e5-87c3-3170ff97fcca.png)

Expected:
Should work properly and go away as soon as i move my mouse off of the icon button.

Another instance:
Hovering over the stack name in the stack drop-down (also service, container, host).  The tooltip will stay up after selection.
![image](https://cloud.githubusercontent.com/assets/11514927/12691017/6ffcbce2-c6a5-11e5-808e-30705b40366d.png)

**Comment by deniseschannon** [comment]
I have another scenario. Version v0.57.0-rc5

1. Have a stack with 1 service
2. Click on Start services (stack level)

Result: Tooltip stays there until I mouse over it again. This is also an issue when I stop services at the stack level. 

![screen shot 2016-02-08 at 11 37 32 am](https://cloud.githubusercontent.com/assets/11410997/12896713/5f3b424c-ce58-11e5-91b6-b6ad3b1943b4.png)

**Comment by tfiduccia** [comment]
version - master 2/11
Verified fixed
