### ISSUE TITLE
Rancher download script is not working

### ISSUE THREAD

**Issue by faysalkhan8p** [rancher/rancher#34647]
if I run the script "curl -sfL https://get.rancher.io | sh - " it crashes. 
This link is causing the problem"https://github.com/rancher/rancher/releases/download/v2.6.0/rancherd-amd64.tar.gz"

![image](https://user-images.githubusercontent.com/56766976/132064832-6b649bef-8588-4fb1-a2c9-dbf89f197a92.png)

System info: ubuntu 18.04

**Comment by kingsd041** [comment]
https://github.com/rancher/rancher/issues/33423

**Comment by superseb** [comment]
Also described on https://github.com/rancher/rancher/releases/tag/v2.6.0
