### ISSUE TITLE
get.rancher.io is not working due to a release repo throws a 404

### ISSUE THREAD

**Issue by isolver-eu** [rancher/rancher#34648]
the terminal line below is not working:
> curl -sfL https://get.rancher.com | sh - 

this is the output:
[INFO]  finding release for channel latest
[INFO]  using v2.6.0 as release
[INFO]  downloading checksums at https://github.com/rancher/rancher/releases/download/v2.6.0/sha256sum.txt
[INFO]  downloading tarball at https://github.com/rancher/rancher/releases/download/v2.6.0/rancherd-amd64.tar.gz
curl: (22) The requested URL returned error: 404

**Comment by hreidar** [comment]
Hi, I did hit the same.

RancherD was an experimental feature in Rancher 2.5 that has been dropped as of Rancher 2.6. From the release notes:

Experimental Features
RancherD was introduced in 2.5 as an easy-to-use installation binary. With the introduction of RKE2 provisioning, this project is being re-written and will be available at a later time. See #33423.

**Comment by brandond** [comment]
See https://github.com/rancher/rancher/issues/29209#issuecomment-912078591
