### ISSUE TITLE
helm doesn't want to upgrade rancher-latest

### ISSUE THREAD

**Issue by maxifom** [rancher/rancher#34656]
**Rancher Server Setup**
- Rancher version: 2.6-latest
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.4+k3s1
- Cluster Type (Local/Downstream): local

**Describe the bug**
Installed cluster with 
```sh
helm install rancher rancher-latest/rancher \
    --namespace cattle-system \
    --set hostname=rancher.mydomain.com \
    --set replicas=1 \
    --set ingress.tls.source=secret
```

tried upgrading with 
```sh
helm upgrade rancher rancher-latest/rancher --set ingress.extraAnnotations.'kubernetes\.io/ingress\.class'=nginx -n cattle-system
```

**To Reproduce**
```sh
helm install rancher rancher-latest/rancher \
    --namespace cattle-system \
    --set hostname=rancher.mydomain.com \
    --set replicas=1 \
    --set ingress.tls.source=secret
```
upgrade using 
```sh
helm upgrade rancher rancher-latest/rancher --set ingress.extraAnnotations.'kubernetes\.io/ingress\.class'=nginx -n cattle-system
```

**Result**
failed with error:
```sh
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Ingress.spec.tls[0].hosts): unknown object type "nil" in Ingress.spec.tls[0].hosts[0]
```
**Expected Result**
successful upgrade

**Comment by maxifom** [comment]
Not stale. Need an answer for this.

**Comment by vincent99** [comment]
When you do upgrade you have to pass _all_ the options you want, not just new ones.  You're trying to upgrade to having no `hostname` set.
