### ISSUE TITLE
Failing conformance test for k8s v1.21.4 provisioned with Rancher 2.6.0 and RKE 1.3.0

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#34655]
**What kind of request is this (question/bug/enhancement/feature request):**
**bug**

We followed similar steps as mentioned in this [link](https://github.com/cncf/k8s-conformance/tree/master/v1.20/rancher ) to run the e2e test by the Sonobuoy to Rancher and RKE clusters. Below two tests failed consistently for clusters provisioned by Rancher and RKE both, even after running tests for 4 times.

**Steps to reproduce**

1. Set up  the k8s cluster v1.21.4 with Rancher v2.6.0 or RKE v1.3.0
2. Download Sonobuoy binary v0.53.2
3. Perform the Sonobuoy command to run the e2e test

`sonobuoy run --mode=certified-conformance`  

**Summary of failures:**
```
Summarizing 2 Failures:

[Fail] [sig-auth] ServiceAccounts [It] ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/service_accounts.go:789

[Fail] [sig-network] Ingress API [It] should support creating Ingress API operations [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/ingress.go:1021

Ran 339 of 5770 Specs in 6409.410 seconds
FAIL! -- 337 Passed | 2 Failed | 0 Pending | 5431 Skipped
--- FAIL: TestE2E (6409.47s)
FAIL

```

**Failures are same for clusters provisioned using Rancher and RKE**

**Node roles and instance size details**

1. node roles - Control plane, etcd, worker (size: 8gb memory, 4 vCPU, 160 storage)
2. node roles - worker (size: 8gb memory, 4 vCPU, 160 storage)
3. node roles - worker (size: 8gb memory, 4 vCPU, 160 storage)

**Comment by rayandas** [comment]
This has been fixed.
