### ISSUE TITLE
rancherd install script is broken.

### ISSUE THREAD

**Issue by jrucker2004** [rancher/rancher#34651]
**Rancher Server Setup**
- Rancher version: 2.6
- Installation option (Docker install/Helm Chart): rancherd ( `curl -sfL https://get.rancher.io | sh -` )

**Describe the bug**
When performing a fresh install using the instructions here: https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/ the install fails when trying to download the latest version, with a http status of 404

**To Reproduce**
run `curl -sfL https://get.rancher.io | sh -`

**Result**
The script starts, and attempts to download the latest release, but fails with a http 404 status

**Expected Result**
The correct release should be downloaded and installation should begin.

**Screenshots**
```
root@rancher:~# curl -sfL https://get.rancher.io | sh -
[INFO]  finding release for channel latest
[INFO]  using v2.6.0 as release
[INFO]  downloading checksums at https://github.com/rancher/rancher/releases/download/v2.6.0/sha256sum.txt
[INFO]  downloading tarball at https://github.com/rancher/rancher/releases/download/v2.6.0/rancherd-amd64.tar.gz
curl: (22) The requested URL returned error: 404 
```

**Comment by roberttucci** [comment]
Thank you for opening this bug report, I am experiencing the same issue.

**Comment by MarcoStuurman** [comment]
I think this is because it has to be installed with helm from 2.6.

**Comment by hreidar** [comment]
Yes, I hit the same, RancherD was an experimental feature in Rancher 2.5 that has been dropped as of Rancher 2.6. From the [release notes](https://github.com/rancher/rancher/releases/tag/v2.6.0):

RancherD was introduced in 2.5 as an easy-to-use installation binary. With the introduction of RKE2 provisioning, this project is being re-written and will be available at a later time. See #33423.

**Comment by LeCodeCo** [comment]
On an install made by RancherD, what steps are needed to upgrade to Rancher 2.6? I guess that I'll need to bootstrap a new Kubernetes cluster and migrate Rancher to that?

**Comment by jrucker2004** [comment]
> Yes, I hit the same, RancherD was an experimental feature in Rancher 2.5 that has been dropped as of Rancher 2.6. From the [release notes](https://github.com/rancher/rancher/releases/tag/v2.6.0):
> 
> RancherD was introduced in 2.5 as an easy-to-use installation binary. With the introduction of RKE2 provisioning, this project is being re-written and will be available at a later time. See #33423.

Ah, I missed this.

Looks like this is working as intended then.  Closing.
