### ISSUE TITLE
2.6.0 - workloads not added as service (service discovery)

### ISSUE THREAD

**Issue by Napsty** [rancher/rancher#34653]
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): Docker Install (Single)
- Proxy/Cert Details: none

**Information about the Cluster**
- Kubernetes version: 1.21
- Cluster Type (Local/Downstream): Custom

**Describe the bug**
Created workloads are not listed as service inside Kubernetes and cannot be selected in service-related configurations (such as Ingress). This happens on a brand new and empty cluster. Created two workloads (named nginx and test) in the UI, services for them are not created.

**To Reproduce**
- Create a workload (tested with both Deployment and DaemonSet)
- Go to Service -> Ingress, try to create a new Ingress rule

**Result**
"Target Service" (for target selection in Ingress) does not show anything. Only shows "Sorry, no matching options". 
When manually entering the workload name, a yellow warning indicates that "The selected service does not exist". 

**Expected Result**
The workloads create a service in the background (Kubernetes), as stated in the documentation (https://rancher.com/docs/rancher/v2.6/en/k8s-in-rancher/service-discovery/):

> For every workload created, a complementing Service Discovery entry is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/3702203/132178940-2570e37b-70ab-40a6-b652-55e5ad9e38e6.png)
![image](https://user-images.githubusercontent.com/3702203/132178974-0d43707f-b54f-4df3-95d6-766c161daa2b.png)
![image](https://user-images.githubusercontent.com/3702203/132179067-e3b8cdd4-026c-42d0-86b2-506ef2db6c86.png)
![image](https://user-images.githubusercontent.com/3702203/132179193-3edeacd8-f688-4f5a-971d-a9fde35bdb81.png)

**Additional context**

Rancher 2.6 service list with kubectl is clearly missing the workloads (nginx and test):

```
> kubectl get services --all-namespaces
NAMESPACE       NAME                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
cattle-system   cattle-cluster-agent                 ClusterIP   10.43.195.33    <none>        80/TCP,443/TCP           79m
default         kubernetes                           ClusterIP   10.43.0.1       <none>        443/TCP                  81m
ingress-nginx   ingress-nginx-controller-admission   ClusterIP   10.43.205.249   <none>        443/TCP                  79m
kube-system     kube-dns                             ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP   80m
kube-system     metrics-server                       ClusterIP   10.43.149.207   <none>        443/TCP                  80m
```

**Comment by Napsty** [comment]
maybe related: https://github.com/rancher/rancher/issues/34639

**Comment by anupama2501** [comment]
@Napsty while creating a workload, in the `Ports` section if we select the type of Service, an SD will be created 

Docs reference: https://rancher.com/docs/rancher/v2.6/en/k8s-in-rancher/workloads/deploy-workloads/

<img width="500" alt="Screen Shot 2021-09-07 at 8 15 25 AM" src="https://user-images.githubusercontent.com/38144301/132383512-ca086348-8402-4b56-b1db-1867321f1a26.png">

cc: @vincent99

**Comment by Napsty** [comment]
Thank you @anupama2501 for that very important hint! I could not spot this in the upgrade/release notes and is clearly a different behaviour than in the other releases.
I will try and report back.

**Comment by burgoyn1** [comment]
@vincent99 Right but the point is, this is not documented anywhere. If this UI is going to be forced onto people who have never seen it before (I really hate it, but that is beside the point) and they expect one thing but it does something else, there should be documentation about that.
