### ISSUE TITLE
Global DNS Entry shows active but no DNS entries created

### ISSUE THREAD

**Issue by ccittadino-ctic** [rancher/rancher#34661]
**Rancher Server Setup**
- Rancher version: 2.5.8
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Wildcard cert with ACM

**Information about the Cluster**
- Kubernetes version: v1.19.9
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster?:
      * Infrastructure Provider = AWS

**Describe the bug**
I have configured the Global DNS Provider as Route53, and created a Global DNS Entry that points to the project that houses the Ingress I want fronted by DNS. Everything shows as "Active" in the Cluster Manager but I don't see any entries being created in Route53.

**To Reproduce**
1) Create a Global DNS Provider that points to Route53
2) Create a Global DNS Entry that uses the above Provider, and targets the Project housing the Ingress you want DNS entries for
3) Create an Ingress inside the project you targeted in step 2:
    a) Add the annotation key = `rancher.io/globalDNS.hostname`, value = `FQDN from Global DNS Entry above`
    b) Ensure the `host` field matches the FQDN from the Global DNS Entry above

**Result**
No DNS entries are created in Route53.
However, I can confirm that Rancher has used the IAM account I created to log into AWS and configure Route53.

**Expected Result**
Route53 should have a new DNS entry matching the FQDN from the Gllobal DNS Entry above

**Comment by abhi1693** [comment]
@ccittadino-ctic Your issue might be related to mine at https://github.com/rancher/rancher/issues/31638

This was fixed in v2.6.0

**Comment by ccittadino-ctic** [comment]
@abhi1693 Can you help me determine if I'm seeing the same issue as you? I'm trying to find logs that would narrow it down but unsure of where exactly they _should_ be

**Comment by ccittadino-ctic** [comment]
Decided to upgrade to 2.6 and try again. Turns out the IAM account I used didn't have all the permissions it needed to alter the Route53 zone. Found this out by check Rancher's local cluster pod logs. Filter by 'dns' and you'll find it on the Pods page.
