### ISSUE TITLE
Get Error page when trying to get to container page that can't find placement

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3466]
Version - master 1/27

Steps:
1.  Create a container that uses port 80, 8080
2.  Clone and keep creating until you get that one that goes to Removed because it can't find a placement
3.  Click on the container name to get to details page

Results:  Get an error page that says t.get is not a function.  If I reload and click again it takes me to the details page.
![image](https://cloud.githubusercontent.com/assets/11514927/12684511/a45bffe4-c67c-11e5-8b37-6d5d3c3a1bb5.png)

Expected:  Should load details.

**Comment by vincent99** [comment]
Is this still an issue?

**Comment by tfiduccia** [comment]
Version - master 3/9
Verified fixed
