### ISSUE TITLE
[2.5] Backport Missing Permissions in catalogs-manage GlobalRole

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#34669]
Issue:
- https://github.com/rancher/rancher/issues/34592

**Comment by ryansann** [comment]
Testing is the same as [here](https://github.com/rancher/rancher/issues/34592#issuecomment-914694796) though the UI steps are slightly different.

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment


| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.5.11                                 |
| Rancher cluster type    | Docker                                  |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | RKE1 Linode                             |
| Downstream K8s version  | v1.20.13                                |
| Browser type            | Google Chrome                           |
| Browser version         | 96.0.4664.110 (Official Build) (x86_64) |

## Reproduction steps

1. Provision a downstream cluster
2. Create a standard user
3. Add the user to the downstream, navigate into the downstream cluster view and add them with the right roles Configure Catalogs
4. Sign in as user, navigate to Apps & Marketplace and try to edit the the chart repo url

**RESULT** 

Unable to edit the chart repo url
  
<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.5-6ff6d08b210f5ce59f4c8dac817ae63af75a5d76-head |
| Rancher cluster type    | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | RKE1 Linode                                        |
| Downstream K8s version  | v1.20.13                                           |
| Browser type            | Google Chrome                                      |
| Browser version         | 96.0.4664.110 (Official Build) (x86_64)            |

## Validation steps

1. Provision a downstream cluster
2. Create a standard user
3. Add the user to the downstream, navigate into the downstream cluster view and add them with the right roles Configure Catalogs
4. Sign in as user, navigate to Apps & Marketplace and try to edit the the chart repo url

**RESULT** 

Successfully able to edit the chart repo url
