### ISSUE TITLE
Please bring back deployment scaling over UI

### ISSUE THREAD

**Issue by fthoma-coding** [rancher/rancher#34678]
I have upgraded my rancher installation to version 2.6 and now, the cluster explorer is the only ui that is available. I think this is a step in the right direction and I´m OK with the new version.

But the only thing what I´m realy miss I the way to scale my deployment over the ui. At the cluster manager, every deployment have a scaling up/down button to manage the deployment. We use this very often to shut down a service for a short time. Now we have to connect over the commandline and do this per command. this takes much more time to administrate our environment.

Is it possible to implement this handling in a future version of rancher again?

![Screenshot 2021-09-08 165113](https://user-images.githubusercontent.com/62056902/132532679-b1ea45c9-eb68-497e-a296-87fc0cc0c23e.jpg)
?

**Comment by guillaume-tmx** [comment]
I agree, still available trough the interface under deployment 
in edit config under Replicas, you can set it to 0 ,save  and after to 1 and save to reproduce the -/+ 
but a quick access is useful

**Comment by vincent99** [comment]
rancher/dashboard#4328
