### ISSUE TITLE
When programming network rules fail , container get stuck in "networking" state forever and no further instances can be started on any host in the setup.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3467]
Server version - Build from master

When I encountered #3458 , I have containers stuck in "networking" state forever in 2 hosts out of the 3 hosts in my setup.
Attempting to start  container in any of the 3 hosts in the set up fails now and instances are stuck in "networking" state forever.

Expected Behavior:
When containers fail to get deployed because of failing to program network rules they should eventually timeout and error out , instead of being stuck in "starting" state forever.

Also ,when networking issues are seen with 1 container it should not prevent other containers from being launched successfully in the the hosts where the containers exist/ in other hosts in the setup.

**Comment by ibuildthecloud** [comment]
We should give up on programming the network agent if it takes to long or fails.

**Comment by SerialVelocity** [comment]
Is there an acceptable workaround for this?

**Comment by deniseschannon** [comment]
Since networking has been redone, closing this issue.
