### ISSUE TITLE
[2.6] Can't manage helm apps

### ISSUE THREAD

**Issue by altairo2087** [rancher/rancher#34677]
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.20.6
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.20.6, v1.21.4
- Cluster Type (Local/Downstream):  Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
I can't install and update apps from the catalog after upgrade rancher from 2.5.8. All installed charts have been disconnected from the repositories.
I see all my catalogs (legacy->catalogs) and installed apps.
I can't install charts because I don't see any applications from catalogs in the "+Charts".
If I try to edit the installed applications, I only see a field with a chart selection.

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**
![catalogs](https://user-images.githubusercontent.com/7862433/132512946-27c49c2e-cb1d-45ad-88f5-7a4f0f56b8a1.PNG)
![charts](https://user-images.githubusercontent.com/7862433/132513035-2fbe776d-9a37-488c-9eab-2624f80786de.PNG)
![apps](https://user-images.githubusercontent.com/7862433/132513045-c8d19c2a-5e55-4e11-a482-d40bc8d2fc54.PNG)
![edit](https://user-images.githubusercontent.com/7862433/132513051-26337220-665d-45a5-aaac-954a03ac19e7.PNG)

**Additional context**

**Comment by PhilipSchmid** [comment]
I had a similar issue. To resolve it, I needed to add the same Helm chart catalog entries from the legacy section in the new "Apps & Marketplace" -> "Repositories" section too. Then I was able to upgrade the already installed instances.
