### ISSUE TITLE
[2.6]Corrupted Backup - No Restore Rancher Management Cluster / Rancher Server

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#34696]
Forward port of https://github.com/rancher/rancher/issues/34554

**Comment by StrongMonkey** [comment]
For testing this issue, see reproduction steps: https://github.com/rancher/rancher/issues/34554#issuecomment-916542049

**Comment by anupama2501** [comment]
To reproduce:

on v2.6.0 rancher version
1. create a custom cluster with 3 worker, 1 etcd, 1 cp
2. From the local cluster, on the UI launch kubectl shell and run the command `kubectl get nodes.management.cattle.io` 
3. Edit the node of the custom cluster by `kubectl edit nodes.management.cattle.io $nodename -n  $clustername`
4. Add the fake finalizer foo.bar under metadata --> finalizers
5. Delete the cluster and verify that the cluster is stuck in removing with the 1 node [with the finalizer added] showing.
6. From local cluster --> apps & market, install rancher backup version `2.0.0` by providing s3 details.
7. Take a backup of the existing state of the local cluster and see the backup stored in the S3.
8. Create a new rke cluster and migrate the rancher server to this rke cluster
9. Restore the backup stored in the s3 on this new rke cluster.
10. Verify the restore won't recover and is stuck in the state `Error restoring cluster-scoped resources [error restoring c-k5hfr of type management.cattle.io/v3, Resource=clusters: restoreResource: err updating resource Cluster.management.cattle.io "c-k5hfr" is invalid: metadata.deletionGracePeriodSeconds: Invalid value: 0: field is immutable]`

**Comment by anupama2501** [comment]
Verified the same steps mentioned above on the rancher chart version `2.0.1+up2.0.1-rc1`

- Installed rancher after restoring the backup on the new rke cluster
- Rancher server has come up fine and verified all the workloads are active
- Created a downstream cluster rke1 and rke2 node driver cluster 
- Both clusters have come up active
