### ISSUE TITLE
Unable to upgrade RKE2 cluster (rancherd installation)

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#34691]
**Rancher Server Setup**
- Rancher version:`v2.6.0`
- Installation option (Docker install/Helm Chart):
   - Helm Chart
   - RKE2: v1.21.4+rke2r2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:  v1.21.4+rke2r2
- Cluster Type (Local/Downstream): local

**Describe the bug**

We use rancherd to deploy RKE2 runtime and rancher in Harvester.
Per discussion with Darren, the preferred way to upgrade a RKE2 cluster is to update the `clusters.provisioning.cattle.io` resource. The resource can't be patched.

**To Reproduce**
- Deploy a RKE2 cluster with [rancherd](https://github.com/rancher/rancherd). Here is our rancherd config:

  **/etc/rancher/rancherd/config.yaml**
  ```
  role: cluster-init
  token: 'token'
  kubernetesVersion: v1.21.4+rke2r2
  labels:
   - harvesterhci.io/managed=true
   ```

- Edit the cluster resource:
   ```   
  # kubectl get clusters.provisioning.cattle.io -n fleet-local
  NAME    READY   KUBECONFIG
  local   true    local-kubeconfig


  # kubectl edit clusters.provisioning.cattle.io local -n fleet-local
  # modify the `spec.kubernetesVersion` from `v1.21.4+rke2r2` to `v1.21.4+rke2r3`
  error: clusters.provisioning.cattle.io "local" could not be patched: admission webhook "rancherauth.cattle.io" denied the request without explanation
  You can run `kubectl replace -f /tmp/kubectl-edit-4xof1.yaml` to try this update again.
   ```

Or maybe this is not the right way to upgrade a cluster, any guideline or suggestion will help. Thanks.

**Result**

Can't patch the cluster resource at all.

**Expected Result**

Should be able to upgrade the RKE2 cluster.

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by brandond** [comment]
> error: clusters.provisioning.cattle.io "local" could not be patched: admission webhook "rancherauth.cattle.io" denied the request without explanation

Have you looked at the rancher webhook logs to see why it's rejecting your edit?

**Comment by dramich** [comment]
> > error: clusters.provisioning.cattle.io "local" could not be patched: admission webhook "rancherauth.cattle.io" denied the request without explanation
> 
> Have you looked at the rancher webhook server logs to see why it's rejecting your edit?

@brandond The only real way to see anything is turn on debug. This is how the webhook handles internal errors currently (unfortunately) but based on the setup and what is trying to be done it should be easy enough to reproduce.

**Comment by guangbochen** [comment]
run `$kubeclt edit clusters.provisioning.cattle.io -n fleet-local local` and e.g modify the `spec.kubernetesVersion` from `v1.21.4+rke2r2` to `v1.21.4+rke2r3`
```
error: clusters.provisioning.cattle.io "local" could not be patched: admission webhook "rancherauth.cattle.io" denied the request without explanation
You can run `kubectl replace -f /var/folders/82/1lgbhrpj00gc0mz3dff3j1v40000gn/T/kubectl-edit-93kby.yaml` to try this update again.
```

And with debug log enabled on the rancher/webhook server, the logs show:
```
time="2021-09-15T02:14:57Z" level=info msg="Active TLS secret cattle-webhook-tls (ver=5094) (count 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-09-15T02:15:11Z" level=debug msg="DesiredSet - No change(2) admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration /rancher.cattle.io for  cattle-system/cattle-webhook-ca"
time="2021-09-15T02:15:11Z" level=debug msg="DesiredSet - No change(2) admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration /rancher.cattle.io for  cattle-system/cattle-webhook-ca"
time="2021-09-15T02:16:45Z" level=debug msg="no route match found for UPDATE provisioning.cattle.io/v1, Kind=Cluster fleet-local/local"
```

**Comment by jiaqiluo** [comment]
can be validated with the rancher-webhook chart version `1.0.1+up0.2.1-rc1`( currently the latest is `1.0.1+up0.2.1-rc2`)

**Comment by dramich** [comment]
The underlying issue was in the webhook when rancher is being ran with MCM disabled. Any cluster can be used to repro this issues so long as that is off.

**Comment by anupama2501** [comment]
Verified on v2.6.0 and upgrading to rancher server v2.6-head ba43472

- Installed rancher server via docker docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:v2.6.0 --features=multi-cluster-management=false
- Verified only local cluster is available and no cluster management tab to create clusters.
- Create a workload in the local cluster and a daemon set
- Upgrade the rancher server to v2.6-head with the commands `docker run -d --privileged --volumes-from rancher-data --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:v2.6-head --features=multi-cluster-management=false`
- No errors were seen during the upgrade and the rancher server has come up fine.

**Comment by anupama2501** [comment]
Verified on rancher HA before upgrade version v2.6.0 ,post upgrade v2.6-head ba43472

- Installed rancher server via helm `helm install rancher rancher-latest/rancher --version 2.6.0 --namespace cattle-system --set hostname=anu-rdnew4.qa.rancher.space --set 'extraEnv[0].name=CATTLE_FEATURES'   --set 'extraEnv[0].value=multi-cluster-management=false'`
- Rancher has come up active and in the local cluster --> created a few workloads
- Upgraded the rancher server to v2.6-head `helm upgrade rancher rancher-latest/rancher --version 2.6.1-rc1  --namespace cattle-system --set hostname=anu-rdnew4.qa.rancher.space  --set rancherImageTag=v2.6-head --set 'extraEnv[0].name=CATTLE_FEATURES'   --set 'extraEnv[0].value=multi-cluster-management=false'`
- No errors seen and the rancher server has come up active

**Comment by anupama2501** [comment]
Closing this issue as tracking the linked issue in a different ticket

**Comment by bk201** [comment]
I can confirm an RKE2 cluster can be upgraded by using `rancher/rancher-webhook:v0.2.1-rc3` image.

**Comment by anupama2501** [comment]
- I was able to reproduce this issue on v2.6.0-rc9 with rke v1.3.0-rc19
- Created a rancher HA server with the following helm command:

`helm install rancher rancher-latest/rancher --version 2.6.0-rc9 --namespace cattle-system --set hostname=<redacted> --set 'extraEnv[0].name=CATTLE_FEATURES' --set 'extraEnv[0].value=multi-cluster-management=false'`

- Once the rancher server is up, from the local cluster --> workload --> rancher pods, the following error logs are seen:

```
2021/09/22 19:12:13 [ERROR] error syncing 'local': handler provisioning-cluster-create: failed to create fleet-local/local provisioning.cattle.io/v1, Kind=Cluster for provisioning-cluster-create local: namespaces "fleet-local" not found, requeuing
Wed, Sep 22 2021 11:12:13 am | 2021/09/22 19:12:13 [ERROR] error syncing 'git-webhook': handler apiservice: failed to create cattle-fleet-system/stv-aggregation /v1, Kind=Secret for apiservice git-webhook: namespaces "cattle-fleet-system" not found, requeuing
Wed, Sep 22 2021 11:12:13 am | 2021/09/22 19:12:13 [ERROR] error syncing 'local': handler provisioning-cluster-create: failed to create fleet-local/local provisioning.cattle.io/v1, Kind=Cluster for provisioning-cluster-create local: namespaces "fleet-local" not found, requeuing
Wed, Sep 22 2021 11:12:13 am | 2021/09/22 19:12:13 [ERROR] error syncing 'git-webhook': handler apiservice: failed to create cattle-fleet-system/stv-aggregation /v1, Kind=Secret for apiservice git-webhook: namespaces "cattle-fleet-system" not found, requeuing


2021/09/22 19:37:24 [ERROR] error syncing 'local': handler provisioning-cluster-create: failed to create fleet-local/local provisioning.cattle.io/v1, Kind=Cluster for provisioning-cluster-create local: admission webhook "rancherauth.cattle.io" denied the request without explanation, requeuing

Wed, Sep 22 2021 11:39:24 am | 2021/09/22 19:39:24 [ERROR] error syncing 'local': handler provisioning-cluster-create: failed to create fleet-local/local provisioning.cattle.io/v1, Kind=Cluster for provisioning-cluster-create local: admission webhook "rancherauth.cattle.io" denied the request without explanation, requeuing

```


- Upgrade the rancher version to v2.6.0 with the helm command `helm upgrade rancher rancher-latest/rancher --version  2.6.0 --namespace cattle-system --set hostname=<redacted>  --set 'extraEnv[0].name=CATTLE_FEATURES' --set 'extraEnv[0].value=multi-cluster-management=false'`

- We can see the following error:

```
2021/09/22 19:52:30 [ERROR] error syncing 'local': handler provisioning-cluster-create: failed to create fleet-local/local provisioning.cattle.io/v1, Kind=Cluster for provisioning-cluster-create local: admission webhook "rancherauth.cattle.io" denied the request without explanation, requeuing
Wed, Sep 22 2021 11:53:00 am | 2021/09/22 19:53:00 [ERROR] error syncing 'local': handler provisioning-cluster-create: failed to create fleet-local/local provisioning.cattle.io/v1, Kind=Cluster for provisioning-cluster-create local: admission webhook "rancherauth.cattle.io" denied the request without explanation, requeuing
Wed, Sep 22 2021 11:53:30 am | 2021/09/22 19:53:30 [ERROR] error syncing 'local': handler provisioning-cluster-create: failed to create fleet-local/local provisioning.cattle.io/v1, Kind=Cluster for provisioning-cluster-create local: admission webhook "rancherauth.cattle.io" denied the request without explanation, requeuing
```


if we upgrade the rancher server to v2.6-head, the above error is not seen
