### ISSUE TITLE
Region dropdown machine is not populated  when adding "Digital Ocean" hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3470]
Server version - v0.57.0-rc2 Region dropdown 

When adding "Digital Ocean" hosts , region drop down is not populated.
 
<img width="1020" alt="screen shot 2016-01-29 at 12 31 16 pm" src="https://cloud.githubusercontent.com/assets/4266958/12687353/3dd4ca64-c684-11e5-943e-c12da9d9d2b5.png">

**Comment by sangeethah** [comment]
Also the drop down for "image"/"size"/"region" is empty when trying to add "Packet" hosts.

**Comment by tfiduccia** [comment]
Version - master 1/29
Verified fixed
