### ISSUE TITLE
Cannot upgrade apps with deployments that were created in ember

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#34700]
**Rancher Server Setup**
- Rancher version: v2.6.0
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
     RKE2

**Information about the Cluster**
- Kubernetes version:
v1.21.4+rke2r2
- Cluster Type (Local/Downstream):
  Downstream 
  - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
    Rancher provisioned AWS cluster

**Describe the bug**

Cannot upgrade apps with deployments if app was created in ember.

**To Reproduce**
 
1. Deploy an old version of a helmv3 app in ember that contains a deployment, such as `aws-event-sources` from helm3-library. Do not use the newest version, must use an app with multiple versions available.
2. Add a cluster repo that uses same url/branch of helm3-library catalog.
3. Install the same version of app from 1 and from the helm3-library clusterrepo using dashboard.
4. Once app from 3 becomes active, open networking tab, update app version, and copy request.
5. Replace name/namespace from request in step 4. with name/namespace of app deployed in step 1.
6. Send request.

**Result**
Encounter error like the following:
`Error: UPGRADE FAILED: cannot patch "aws-event-sourcesember-controller" with kind Deployment: Deployment.apps "aws-event-sourcesember-controller" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"aws-event-sourcesember", "app.kubernetes.io/name":"aws-event-sources"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`

**Notes**
This is probably happening due to the `io.cattle.field/appId` matchLabel selector on the deployment. It seems as though norman automatically injects this into the deployment and steve is trying to apply a manifest that doesn't include it. Since these are immutable it causes an error. This likely is the case with deployments deployed without apps as well and I believe that is covered by this issue: https://github.com/rancher/rancher/issues/31235.

**Expected Result**

A successful upgrade.

**Additional context**

Step 2 through 5 are a work around for functionality we want to support. We want to support migrating apps from norman to steve. The steps worked on apps such as "alcide-advisor-cronjob", this is because it is mostly just a cronJob which doesn't have this issue.

**Comment by rmweir** [comment]
Usually I always add a milestone to issues as a placeholder but for this issue and a related issue I will leave that for @cloudnautique.

**Comment by anupama2501** [comment]
Reproduced on v2.6.0

**Method1:**
1. Create a downstream rke2 node driver cluster 
2. Navigate to ember UI and from the cluster --> default project --> apps, install the app aws-event-sources on version `0.1.4`
3. From the dashboard --> export cluster --> apps & market place --> Chart repos --> add a new git repo with the below details `helm3-library:name | https://git.rancher.io/helm3-charts:URL | master:Branch` 
4. From the kubectl shell, add the following annotations to the app created in step2
```
kubectl get apps -A | grep aws-event-resources
kubectl edit app aws-event-sources-xvn69 -n aws-event-sources-brtnw

add annotations under spec.chart.metadata.annotations
catalog.cattle.io/ui-source-repo: helm3-library
catalog.cattle.io/ui-source-repo-type: cluster
```
5. From the UI, explore cluster --> apps & market --> upgrade the version of the app 
6. Upgrade fails with the error 
```
Error: UPGRADE FAILED: cannot patch "aws-event-sources-sg67h-controller" with kind Deployment: Deployment.apps "aws-event-sources-sg67h-controller" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"aws-event-sources-sg67h", "app.kubernetes.io/name":"aws-event-sources"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable 
```

**Method2:**
After step3 from the above steps:

- From charts, install the app AWS-event-sources, version `0.1.4` - app2
- Verify the workload gets active.
- From apps & market --> upgrade the app2 and in the network tab, copy the post request as `copy as cURL`
- edit the copied curl request by replacing the namespaces and names with the app details created in step2 from method1
- Run the curl command and from the UI --> apps & market, the app goes to error state.
- Most recent operations --> helm --> view logs 
```
Error: UPGRADE FAILED: cannot patch "aws-event-sources-sg67h-controller" with kind Deployment: Deployment.apps "aws-event-sources-sg67h-controller" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"aws-event-sources-sg67h", "app.kubernetes.io/name":"aws-event-sources"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable 
```

**Comment by rmweir** [comment]
The fix has been to add an annotation to the chart that informs the backend that extra work needs to be done. To test this a process similar to the process used to confirm the issue, specifically method 2. For step 3, except annotation should be added to the the apps spec.chart.metadata. The annotations that should be added are:
```
catalog.cattle.io/ui-source-repo: helm3-library
catalog.cattle.io/ui-source-repo-type: cluster
apps.cattle.io/migrated: "true"
```

Once the UI fix is in (tracked here: https://github.com/rancher/dashboard/issues/4402), the rest can be done through the UI. Until then method 2 as described above should be used with one additional step; in the request body there will be an "annotations" field. The `"apps.cattle.io/migrated": "true"` will be missing. This annotation should be added to the annotations field. Now this request should be be sent and result in a successful upgrade operation.

**Comment by anupama2501** [comment]
Verified fresh install on v2.6-head cc2b8be

- Install rancher server on 2.6-head
- Create a downstream rke2 node driver cluster.
- From system charts, install the app AWS-event-sources, version 0.1.4 - app1
- Verify the workload gets active.
- Add helm3 repository in the apps & market -> repositories: `**name**: helm3-library | **URL**: https://git.rancher.io/helm3-charts | **Branch**: master`
- Install app AWS-event-resources from apps&market --> helm3 library -- app2
- From apps & market --> upgrade the app2 and in the network tab, copy the post request as copy as cURL
- edit the copied curl request by replacing the namespaces and names with the app1 details and add the annotation `"apps.cattle.io/migrated" : "true"}`
- Run the curl command and from the UI --> apps & market --> get the helm operation job from the curl command outpyt and verified the logs
- app was upgraded successfully and no errors were seen

**Comment by anupama2501** [comment]
Blocked on verifying upgrade test case from 2.5.x to 2.6-head https://github.com/rancher/rancher/issues/35411

**Comment by anupama2501** [comment]
Verified on 2.6-head 78b25c3

1. Created an rke1 node driver cluster 3 worker, 1 etcd, 1cp
2. Installed the app `rancher-externalip-webhook` from ember UI 
3. Upgraded the app from dashboard UI by adding the annotation in the curl command `apps.cattle.io/migrated: "true"`
4. Upgrade went through without any errors
5. Uninstalling the app from dashboard UI goes through without any error

Feature charts from dashboard:
1. Installed monitoring v2 on an rke2 node driver cluster version `16.6.0`
2. App installed successfully
3. Upgraded the app to `100.0.0+up16.6.0`
4. Verified upgrade went through fine without any errors.

Moving the issue to QA-blocked for the above mentioned issue seen during rancher upgrade

**Comment by anupama2501** [comment]
Verified on v2.6-head 4375161
1. Installed rancher on v2.5.11 and created two rke1 node driver 3 worker, 1etcd, 1cp
2. Installed aws-event-sources:`0.1.0`, external-ip-webhook:`0.1.4`, longhorn v1 apps `1.1.0`
3. Upgraded the rancher server to v2.6-head
4. From the explorer --> installed apps --> select aws-event and upgrade the app
5. Upgrade redirects to legacy apps --> Project (default) --> upgrade to the latest versions. 
6. Verified the upgrade went through fine without any errors. 
7. Repeated the same for longhorn and external-ipwebhook, the apps have upgraded without any error.

Verified by upgrading from v2.4.16 --> v2.6-head 4375161 by installing helm3 charts and verified the apps have been upgraded without issues.

**Comment by anupama2501** [comment]
Re-opening for a few more validations.

**Comment by anupama2501** [comment]
Waiting on https://github.com/rancher/rancher/issues/35684 and https://github.com/rancher/dashboard/issues/4402 to validate a few use cases.

**Comment by anupama2501** [comment]
Verified on v2.6-head e62e1ae upgraded from 2.5.11

Validated few more scenarios with respect to the above:

To migrate:
```
kubectl get apps -A | grep aws
kubectl edit apps aws-event-sources -n aws-event-sources

Add the annotation via kubectl on the downstream cluster in spec.chart.metadata.annotations
catalog.cattle.io/ui-source-repo: helm3-library
catalog.cattle.io/ui-source-repo-type: cluster
apps.cattle.io/migrated: "true"

From local cluster:
kubectl get apps.project.cattle.io -A | grep aws
kubectl edit  apps.project.cattle.io aws-event-sources -n p-mr57l

Delete the app from the ember UI:
kubectl delete apps.project.cattle.io aws-event-sources -n p-mr57l

From apps  & market place --> Repositories --> name: `helm3-library`, URL: `https://git.rancher.io/helm3-charts`, branch: `master`
```

**Uninstall post migration:**
- Migrated the app hpe-csi-driver from ember to dashboard by following the above mentioned steps
- Uninstalled the app and verified the uninstallation went through without errors

**Update the app post migration:**
- edited the app aws-event-sources by changing the default images to `false` 
- Verified the update went through as expected

**Upgraded the app post migration**
- Upgraded the app externalip-webhook from version 0.1.4 to 0.1.5 
- Upgrade went through without any errors

**Upgraded the app and uninstalled**
- From the above test case post upgrade, uninstalled the app
- App was deleted and all the workloads were removed from the project
