### ISSUE TITLE
Add support for annotation that prevents helm install and v1 App deletion when deleting v3 App

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#34701]
**Is your feature request related to a problem? Please describe.**
In the long run we'd like to implement a means of migrating an app that was installed in the ember ui to be exclusively manageable in the dashboard UI. Being able to delete the ember app without uninstalling the app's resources or the dashboard app is a first step in that direction and should facilitate a more manual, intermediate process for achieving the migration.

**Describe the solution you'd like**
Support an annotation to a v3 App that indicates a helm uninstall should not be ran on deletion of the v3 App and the v1 App (visible in dashboard) should also NOT be deleted.

**Related issue:**
https://github.com/rancher/rancher/issues/34700

**Comment by rmweir** [comment]
Usually I always add a milestone to issues as a placeholder but for this issue and a related issue I will leave that for @cloudnautique.

**Comment by rmweir** [comment]
This is best tested as the final step of testing https://github.com/rancher/rancher/issues/34700. Once the migration is done, this can be used to delete the norman app without uninstalling the chart or deleting the app in dashboard.

**Comment by rmweir** [comment]
### Steps
__Note:__ This makes the most sense to be done after testing an upgrade for https://github.com/rancher/rancher/issues/34700, once the app has been migrated (meaning cluster repo was created and proper annotations were added to new app's spec.chart.metadata.annotations).

1. Add "cattle.io/skipUninstall": "true" annotation to ember app using kubectl or API UI.
2. Delete the app.

**Expected:**
App is deleted but the underlying resources are not uninstalled by helm.

### Root cause
This is a complementary issue to https://github.com/rancher/rancher/issues/34700. Once the new dashboard apps can be used to edit apps that were once installed through ember apps, there needs to be a way of deleted the legacy ember app without uninstalling the underlying chart.

### What was fixed, or what changes have occurred
Now, an annotation,"cattle.io/skipUninstall": "true",  can be added to prevent the helm uninstall part of the legacy app deletion logic. This can be done using kubectl or API UI in ember.

### Areas or cases that should be tested
Just uninstalling an ember app without the resources actually being uninstalled by helm. It makes the most sense to do this as the last step of testing an upgrade for https://github.com/rancher/rancher/issues/34700.

### What areas could experience regressions?
Any ember app deletion. Should ensure that without the annotation that apps are deleted along with their resources as expected.

### Are the repro steps accurate/minimal?
Yes.

**Comment by anupama2501** [comment]
Validation after @rmweir modified the steps for the ticket:
On v2.6-head `a015b10`

- Install aws-event-sources version v0.1.4 on ember UI
- Add the annotations from v3 API "cattle.io/skipUninstall": "true" --> annotations
- Also, add the annotations
- catalog.cattle.io/ui-source-repo: helm3-library
- catalog.cattle.io/ui-source-repo-type: cluster
- Add the annotation `apps.cattle.io/migrated: "true"` using kubectl [as via v3 API, the annotation gets removed when the request is sent - Rancher specific due to some permissions.]
- From the ember UI, delete the app aws-event-sources
- App is not deleted from the explorer UI but only from the ember UI.

Moving this ticket to-test as we have an issue being worked up on for deletion scenario linked above

**Comment by anupama2501** [comment]
Verified on v2.6-head ac67f83 as part of this issue https://github.com/rancher/rancher/issues/35684#issuecomment-991285983
