### ISSUE TITLE
imported cluster is active,but can't explore.

### ISSUE THREAD

**Issue by wangshiyang** [rancher/rancher#34707]
Rancher version:  2.6
- Installation option (Docker install/Helm Chart):
  docker install
  command: 
```
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:latest
```

- Kubernetes version: 1.22.1
- Cluster Type : Downstream
* Imported = Running kubectl apply onto an existing k8s cluster 
* Hosted = etc

error, import cluster state is active,but can't explore:

![1631373822504](https://user-images.githubusercontent.com/1273242/132953126-b6d94999-6890-4683-9d56-4182d1ebacca.jpg)

**Comment by wangshiyang** [comment]
docker logs 
```
E0912 02:05:23.574878      33 reflector.go:139] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.meta.k8s.io)
2021/09/12 02:05:25 [ERROR] error syncing 'machinesets.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/12 02:05:25 [ERROR] error syncing 'machines.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/12 02:05:25 [ERROR] error syncing 'machinedeployments.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/12 02:05:25 [ERROR] error syncing 'machinehealthchecks.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/12 02:05:25 [ERROR] error syncing 'clusters.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/12 02:05:26 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/12 02:05:26 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
```

**Comment by jiaqiluo** [comment]
It looks like the same issue as [this one](https://github.com/rancher/rancher/issues/33967)

According to [this comment](https://github.com/rancher/rancher/issues/33967#issuecomment-893616654), it may take some time for Ranche to create the services "webhook-service". 

@wangshiyang Does the cluster recover after a while?

**Comment by skurfuerst** [comment]
Having the same problem that k3s clusters are not accessible after upgrading to 2.6.0 - totally unsure why. 

The logs of cattle-cluster-agent say:

```
time="2021-09-17T19:48:04Z" level=error msg="Failed to dial steve aggregation server: websocket: bad handshake"
```

But I am not sure how to debug this further.

**Comment by Lazzu** [comment]
I have this problem as well. After a very long time (days) the cluster I created still can not be explored and the logs on cattle-cluster-agent is saying
```
level=error msg="Failed to dial steve aggregation server: websocket: bad handshake"
```
I would love to have some pointers to get this forward. I'm running rancher the first time.

**Comment by Lazzu** [comment]
I managed to fix this issue by reinstalling rancher after installing NTP on the node and making sure there was no firewall enabled, as described here:
https://rancher.com/docs/rancher/v2.6/en/installation/requirements/#operating-systems-and-container-runtime-requirements

**Comment by jaccoh** [comment]
I have this same issue as well. We use systemd-timesync .. seems to be correct. This is on freshly created cluster in a test scenario..

Any hints? Or is this really time related?

**Comment by jaccoh** [comment]
Just to let you know: for me the issue was not time related or OS related. I simply made an "error" in setting the rancher-url on installing Rancher. I had a "/" as a suffix. Therefore cattle-agent try to connect to https://rancher-url//v3/connect resulting in a 301 instead of https://rancher-url/v3/connect..
