### ISSUE TITLE
Preferences are broken

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3471]
Version - 0.57.0-rc2

Steps:
1.  Authenticate using local Auth

Results:
1.  Default Environment not saving for admin
2.  Stacks don't stay open on main stack page
3.  Themes aren't saving per user

**Comment by vincent99** [comment]
This requires logging into one user, logging out, then logging in as another without reloading the page.

**Comment by tfiduccia** [comment]
Version - master 1/29
Verified fixed
