### ISSUE TITLE
Project owners don't have access to import yaml

### ISSUE THREAD

**Issue by catherineluse** [rancher/rancher#34712]
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option: Docker install
- Proxy/Cert Details: Self-signed certs

**Information about the Cluster**
- Kubernetes version: K3s
- Cluster Type (Local/Downstream): local

**Describe the bug**

As a project owner, when you try to import YAML at the cluster level, no resources are created. 

The UI tries to POST to `/v1/management.cattle.io.clusters/local?action=apply`. The API view shows that the `apply` action for the cluster is available to project owners, but the action doesn't work.

The error shown in the UI doesn't say the resource couldn't be created, but it says the user lacks permission to list resources.

**To Reproduce**
See Sowmya's steps in the original dashboard issue: https://github.com/rancher/dashboard/issues/3854#issue-970969753

**Result**
No resources are created. 

**Expected Result**
The resources should be created with the same result as if the project owner used `kubectl apply`.

**Screenshots**
![Screen Shot 2021-09-13 at 9 55 46 AM](https://user-images.githubusercontent.com/20599230/133125984-8868a72c-38b6-437d-be1c-b8193a330c0f.png)

**Additional context**
This was originally a UI issue, but after looking into it, it seems like a backend issue because the resources weren't created.

**Comment by snasovich** [comment]
The error is produced by Wranger (https://github.com/rancher/wrangler/blob/0babd42fbad8ddea4f9c106d7c03eeddfa8101ff/pkg/apply/desiredset_process.go#L250 or more specifically line 351 as `informer` is `nil`) as Rancher attempts to list resources without a namespace filter with the user who is not authorized to do so. Note `o.listerNamespace` is `nil`, but as `objs` may contain objects from multiple namespaces it doesn't seem to be an option for the fix to set it. Instead, we want to either gather objects based on all distinct namespaces between the passed `objs` or find all objects of a given GVK the user has access to without namespace restrictions.

This is being investigated, just sharing an update.

**Comment by Auston-Ivison-Suse** [comment]
**Setup for Reproduction**
- Rancher install: Docker
- Rancher Version: v2.6-head(17f2546)

**Steps for Reproduction**
1. Create an RKE1 cluster
2. Create a new user (I made a standard user)
3. Within the cluster create a new project, give it a name and assign the previously made user ownership.
4. Within that project (cluster --> project/namespaces) find the previous created and named project and click the "create namespace" button. Name it and continue. 
5. Now login as the created user, and navigate to the cluster explorer. 
6. From the top right, click on "Import Yaml" using Deployment/workload as the object/kind or Namespace as the object/kind.
   - Namespace yaml example. 
```
apiVersion: v1
kind: Namespace
metadata:
  name: "development"
  labels:
    name: "development"
```
    - Deployment/workload yaml example 
```
apiVersion: v1
kind: Deployment
```

**Results**

You will get errors when attempting the above imports. 

Screenshot of Namespace error:
![Screen Shot 2021-11-09 at 7.46.56 PM.png](https://zube.io/files/rancher/764ba1aa511a486ddf368630a94b7da5-screen-shot-2021-11-09-at-7-46-56-pm.png)

Screenshot of Deployment error:
![Screen Shot 2021-11-09 at 7.54.12 PM.png](https://zube.io/files/rancher/183f91dc8b941945d9ca012ed1d0c119-screen-shot-2021-11-09-at-7-54-12-pm.png)

**Comment by paynejacob** [comment]
### Root cause
When wrangler applies resources in multiple namespaces it tries to list resources across all namespaces.  This causes an error for users that do not have access to all namespaces.
 
### What was fixed, or what changes have occurred
Wrangler now only searches across relevant namespaces.
 
### Areas or cases that should be tested
1. Create a resources with no namespace -> it should be created in the default namespace
2. Create a resources in a namespace the user has access to -> it  should be created
3. Create a resources in multiple namespaces that a user has access to.  -> they should all be created in the appropriate namespace
4. Update resources in multiple namespaces that a user has access to.  -> they should all be updated
5. Create multiple resources in namespaces the user does not have access to -> an error for at least one of the namespaces should be returned
6. test permutations of the cases above and ensure they behave correctly when mixed.
 
### Are the repro steps accurate/minimal?
yes

**Comment by Auston-Ivison-Suse** [comment]
**Further Testing**

**Setup**
- Rancher install: Docker
- Rancher Version: v2.6-head(78b25c3)

After following my previously listed steps and attempting to import the Namespace Yaml I get this result: 

"failed to list /v1, Kind=Namespace for 46fb7abd-c204-431f-a842-d8a505514a6f: namespaces is forbidden: User "u-l2zqn" cannot list resource "namespaces" in API group "" at the cluster scope"

Which is the same error initially listed by Sowmya [here](https://github.com/rancher/dashboard/issues/3854#issue-970969753) as well as the same error in my previous screenshot. 

When attempting the same step but with the Deployment/workload  Yaml example I get the following error: 

"failed to discover client for /v1, Kind=Deployment"

This is different from error.

**Comment by paynejacob** [comment]
@Auston-Ivison-Suse does that user have permissions to create namespaces.  If you use kubectl apply -f can they create it?

**Comment by snasovich** [comment]
@Auston-Ivison-Suse , https://github.com/rancher/rancher/commit/78b25c3e3491244bba3f5d9d94439bbe45c99295 is before Jacob's changes went in. Looks like we've had some Drone failures recently so v2.6-head tag did not get updated in the last few days. I see there is a build running for another change so if it passes we should have updated v2.6-head.

Bottom line is we want to wait for updated v2.6-head on DockerHub that includes Jacob's changes.

**Comment by snasovich** [comment]
@Auston-Ivison-Suse , that build has just succeeded and we have updated `v2.6-head` tag on DockerHub that includes @paynejacob 's changes. Could you please test again?

**Comment by Auston-Ivison-Suse** [comment]
**Setup for Validation**
- Rancher install: Docker
- Rancher Version: v2.6-head(17f2546)
- RKE1 cluster on k8s version 1.21.6

**Steps for Reproduction**
1. Create an RKE1 cluster
2. Create a new user (I made a standard user)
3. Within the cluster create a new project, give it a name and assign the previously made user ownership.
4. Within that project (cluster --> project/namespaces) find the previous created and named project and click the "create namespace" button. Name it and continue. 
5. Now login as the created user, and navigate to the cluster explorer. 
6. From the top right, click on "Import Yaml"
7. Use the following yaml file to import successfully:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  namespace: n1#this will be the name of whatever namespace you had created. 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
8. A dialog box should open up showing your deployment.

**Further Testing**
1. Create a resources with no namespace -> it should be created in the default namespace **Pass**

2. Create a resources in a namespace the user has access to -> it should be created **Pass**

3. Create a resources in multiple namespaces that a user has access to. -> they should all be created in the appropriate namespace **Pass**

4. Update resources in multiple namespaces that a user has access to. -> they should all be updated **Pass**

5. Create multiple resources in namespaces the user does not have access to -> an error for at least one of the namespaces should be returned **Pass**

6. test permutations of the cases above and ensure they behave correctly when mixed. **Pass**
