### ISSUE TITLE
vSphere Templates only show one line in dropdown box UI in Edge

### ISSUE THREAD

**Issue by bmayfi3ld** [rancher/rancher#34711]
**Rancher Server Setup**
- Rancher version:
2.6.0
- Installation option (Docker install/Helm Chart):
Helm, RKE1
- Proxy/Cert Details:
Internal CA

**Information about the Cluster**
- Kubernetes version:
v1.20.9
- Cluster Type (Local/Downstream):
Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

When running Edge Version 94.0.992.14 or 93.0.961.47 the dropdown for vSphere VM Templates only shows one line when selecting a template to use. There is then a tiny little scroll box to work through all the templates available. 

**To Reproduce**
Run Edge version as specified above. Try to create a vSphere Node Template. Navigate to the VM template dropdown box. Observe tiny dropdown box.

**Result**
Tiny Dropdown Box.

**Expected Result**

A large dropdown box showing several options as it does on Chrome or Firefox. 

**Screenshots**

![image](https://user-images.githubusercontent.com/563214/133108242-8efb74e4-13c8-438d-ae7b-908bfac2bbf3.png)

**Additional context**
<!--Add any other context about the problem here.—>
The network text box also doesn't show the full view of the words. See screenshot.

**Comment by jiaqiluo** [comment]
Hi, @bmayfi3ld. Thank you for reporting this bug! 
Currently, Rancher is heavily tested on Chrome, Firefox, and Safari. Would you mind using those browsers for the best user experience?

**Comment by bmayfi3ld** [comment]
It looks like the issue only partially exists in Chrome.  The Template dropdown only shows two at a time. Which is better than one but still not great.  

Issue still exists in 2.6.2
