### ISSUE TITLE
New cluster stuck in "Wait Check-In"

### ISSUE THREAD

**Issue by lukos** [rancher/rancher#34719]
Steps:

1. Install RKE using the docker method `docker run rancher/rancher ...`
2. Create a new cluster in the web app
3. Add 3 existing nodes using `docker run rancher/rancher-agent ...`
4. RKE starts running the installation process and pulls/sets up K8S containers.

Now after 12 hours, the cluster looks Active on the home page but cannot be clicked and the Explore Cluster entry is disabled in the menu.

Under Cluster Management, the Explore button is disabled, and if I click into the new cluster, it mostly looks OK, except that the State of the Cluster under Related Resources shows as "Wait Check-In" and I don't know what that means.

![image](https://user-images.githubusercontent.com/581018/133257062-c19fb9d4-10be-4e8a-b9db-d90d69d15658.png)

**Comment by PrateekKhatri** [comment]
Hi,

I am also getting the same error.

Did you find any solution for the issue?

**Comment by lukos** [comment]
I gave up in the end. Rancher docs are too difficult to understand because there are now too many versions and like many organisations, they generate too much text which becomes too complicated over time - I still don't really understand RKE vs Rancher UI and the fact there seem to be so many different documents about creating clusters in different ways. In the end, I used microk8s in cluster mode and added that into the Rancher UI.

**Comment by mconstant** [comment]
I have this same error. What is the solution?

**Comment by Reedler01** [comment]
Having the exact same issue deploying new cluster to vmware.

**Comment by Gulse** [comment]
Same here on Version 2.6.2
Sad that even "standart" operations without any edits to the default are not working...

**Comment by xuanyuanaosheng** [comment]
Please Try this: https://github.com/rancher/fleet/issues/142

**Comment by sammasamadhi** [comment]
Same here on Version 2.6.2

**Comment by exocode** [comment]
reopen please

**Comment by gudge25** [comment]
same here
