### ISSUE TITLE
Cloud Providers in 1.23

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#34724]
The cloud providers are being removed in ~1.23~ unknown: 
* https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers
* https://github.com/kubernetes/enhancements/issues/2395

This issue can represent what work we have to do to migrate those.

**Comment by snasovich** [comment]
This has been superseded with later issues on cloud provider removal (that is partially happening in 1.27 and more may be removed in later releases).
