### ISSUE TITLE
Can't install on Ubuntu

### ISSUE THREAD

**Issue by carloszan** [rancher/rancher#34735]
**Rancher Server Setup**
- Rancher version: 2.6.0

**Describe the bug**
I tried to install in a new virtual machine (virtual box) running Ubuntu 18.04.5 server mode and it keeps giving me 404 on a file which should be at https://github.com/rancher/rancher/releases/download/v2.6.0/rancherd-amd64.tar.gz

**To Reproduce**
 

`curl -sfL https://get.rancher.io | sh -`

**Result**
```
root@rancher:/etc/rancher/rke2# curl -sfL https://get.rancher.io | sh -
[INFO]  finding release for channel latest
[INFO]  using v2.6.0 as release
[INFO]  downloading checksums at https://github.com/rancher/rancher/releases/download/v2.6.0/sha256sum.txt
[INFO]  downloading tarball at https://github.com/rancher/rancher/releases/download/v2.6.0/rancherd-amd64.tar.gz
curl: (22) The requested URL returned error: 404
```

**Expected Result**

Should install

**Screenshots**

![image](https://user-images.githubusercontent.com/6218906/133360456-dd507e5b-6b85-420a-bb56-3c70edf4bee5.png)

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by kingsd041** [comment]
> RancherD was introduced in 2.5 as an easy-to-use installation binary. With the introduction of RKE2 provisioning, this project is being re-written and will be available at a later time. See [#33423]()https://github.com/rancher/rancher/issues/33423.
