### ISSUE TITLE
[Forwardport] RBAC project role (caching?) issue in Rancher

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#34732]
Original issue:
- https://github.com/rancher/rancher/issues/31982

**Comment by anupama2501** [comment]
Unfortunately, I'm not able to repro it on v2.6.0

Steps:

- Installed rancher single node on v2.6.0
- Created a downstream custom rke1 cluster with 1 etcd+cp and 1 worker node
- Created a local user from users & auth as a standard user - user1
- As an admin, add user1 to the system project in the custom cluster created above with the custom role `Create namespaces`.
- login as user1, tried to create a namespace, user is able to create namespace only in a different browser.
- As admin, add the custom role `View workloads`
- Verify as user1, the workloads are visible


@ryansann I tried the steps you have linked in the issue above. Could you let me know if this is always reproducible on v2.6?

**Comment by anupama2501** [comment]
I tried the following scenarios to reproduce:

On rancher v2.6.0
As an admin create a local user - user1, enable auth provider openLDAP - user2
Create two rke1 node driver clusters with 1 node all roles - c1, c2

Scenario1 local and auth users custom project builtin roles --> not able to repro
1. As an admin, add user1 to c1 and user2 to c2 with the custom project permissions - `Create namespaces` to the syste project
2. in different browsers, login as user1 and user2
3. Create a namespace ns1 as user1 and user2 in both the clusters.
4. as admin, delete the custom project role for both the users from both the clusters
5. Verified the users do not see the clusters anymore
6. As admin, add custom builtin project role in system project - `Manage workloads`
7. Refresh the UI in user1 and user2 browsers. 
8. Verify both the users can create workloads 

Scenario2 local and auth users custom project roles created--> not able to repro
1. From users and auth, create the custom project role --> r1 with get,list  namespaces
2. Add user1 and user2 in the clusters with the above created role in System project
3. As user1 and user2, verify they can list all projects
4. As an admin, change the custom project role and add verb `create`
5. As user1 and user2 verify they can create namespaces after refreshing the UI.

**Comment by ryansann** [comment]
@anupama2501 these steps may not be triggering the issue. I'll get you some more clear steps and validate that we are triggering it. There needs to be a RoleBinding that binds a user to a ClusterRole, and that ClusterRole needs to have its policy rules changed.

**Comment by ryansann** [comment]
Repro steps on Rancher v2.6.0:
1. Start Rancher and create a user `foo`
2. Create a custom project role with verbs=* resource=Secrets, and verbs=* resource=Deployments
3. Deploy downstream RKE cluster
4. Navigate to Ember UI, add `foo` to system project with custom project role
5. Navigate to Ember UI as `foo`, into the system project and to the secrets resource view
6. In a separate window, as admin, revoke the verbs=* resource=Secrets policy rule on the custom project role
7. As `foo`, refresh secrets view. Note that the secrets are still visible.
8. Upgrade to `v2.6-head`
9. Refresh the secret view for `foo`. Note that secrets are no longer visible.
10. Remove verbs=* resource=Deployments from custom project role as admin
11. Note that foo can't see workloads/deployments after refreshing workload/deployment view

**Comment by anupama2501** [comment]
Reproduced on v2.6.0 from the steps provided by @ryansann 

1. Created a rancher server on v2.6.0 
2. Created an rke1/rke2 node driver cluster with 1 node all roles
2. Created a local user as an admin - user1
3. Create a custom project role from the v3 API with resources as `Deployment` and `Secrets`, verbs --> `get`,`list`,`create`
4. Assign the role to the user1 in the System project
5. log in as the user1 and verify user has access to Secrets and workload deployments
6. As an admin, update the role by removing the resources `Secrets`. 
7. Verify as the user1, Secrets are still accessible by the user

Verified by upgrading the test setup to v2.6.0-rc3
1. after upgrade verified the user do not have access to secrets anymore
2. Added a new resource and verified, users have access to ingress
3. Created a new role with resource `Create namespaces`, verbs --> Get and list
4. Verified when logged in as user1, they can create namespaces

Verified on fresh install v2.6.0-rc2
1. By creating custom roles with resources `Secrets`, `deployments` and verbs `Get`, `list`, `update`
2. Assigned the user1 to System project with the above role.
3. As an admin, updated the role and removed Secrets --> verified user1 can only access `deployments`.

Ran the rbac test suite from automation and verified all the tests have passed for istio, monitoring, test_grb

**Comment by anupama2501** [comment]
Keeping this open as it has to be verified from dashboard as its currently blocked by the dashboard https://github.com/rancher/dashboard/issues/4277

**Comment by sowmyav27** [comment]
**On 2.6.1-rc7**

- By creating custom roles with resources Secrets, deployments and verbs Get, list, update
- Assigned the user1 to Default project with the above role.
- As an admin, updated the role and removed Secrets --> verified user1 can only access deployments.
- This is from the dashboard UI
