### ISSUE TITLE
Logging out in Dark theme has dark Login screen

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3473]
Version - 0.57.0-rc2

Steps:
1.  Authenticate
2.  Change to dark theme
3.  Log out

Results:  the log in screen is dark themed

Expected:  Since we have no idea what theme a user has selected before they are actually logged in, we should always have a light colored log in screen.  It should never be dark.

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/455

**Comment by tfiduccia** [comment]
Version - master 2/4
Verified fixed
