### ISSUE TITLE
Feature Request - EKS - allow cluster management (import and creation) using IAM assume roles, rather than access keys and secret keys

### ISSUE THREAD

**Issue by dfallert-rcd** [rancher/rancher#34733]
Currently, from what I can gather, it seems that the only way to manage EKS clusters in rancher, is by providing an access key and secret key (and optionally a session token)

This seems to have been brought up in the past here #15185, however, it was erroneously closed due to the implementation of session tokens, though nice, doesn't cover this use case. There have been a [couple](https://github.com/rancher/rancher/issues/15185#issuecomment-789816005_) [requests](https://github.com/rancher/rancher/issues/15185#issuecomment-916171400) to re-open the issue already, and now I'll throw my hat in the ring as well.

As it stands, due to the insecurity of using access keys/secret keys, we will not be able to use the EKS provider to import/create existing/new clusters. We've worked around it for now by importing existing clusters as "generic", but that's non-ideal.

**Comment by jlkaiser** [comment]
Here is another hat. We have a hard requirement from our ENTSEC team to not use IAM user roles, which means we'll be moving away from Rancher post haste if this feature is not implemented soon.

**Comment by dfallert-rcd** [comment]
HAs there been any movement on this?

**Comment by ospiegel91** [comment]
This is an important feature, please push forward

**Comment by rayterrill** [comment]
This is valid.

**Comment by pedrokiefer** [comment]
Any news on this? Would a PR implementing this feature be welcomed ?

**Comment by jjlakis** [comment]
Still there

**Comment by ikunduraci** [comment]
Any updates here?

**Comment by z0ph** [comment]
Do you happen to have any news on this? Long-term credentials are not a good practice, and it requires much effort to rotate them. It's also a hard requirement for Security Teams nowadays.
