### ISSUE TITLE
[Backport] update driver version to the new version for equinix metal

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34742]
Backport tracking 

See comment: https://github.com/rancher/rancher/issues/33758#issuecomment-919423869

**Comment by cbron** [comment]
The original didn't make it into 2.6.1. Bumping this to 2.5.11 to avoid the scenario where users can't upgrade to a compatible Rancher version.

**Comment by displague** [comment]
#35271 has been merged. Can this land in 2.5.13?

**Comment by displague** [comment]
https://github.com/rancher/rancher/issues/33758 has also been merged.

**Comment by Jono-SUSE-Rancher** [comment]
I feel like this can be closed based on the feedback from Jake via (https://github.com/rancher/rancher/issues/33758#issuecomment-990658112)
