### ISSUE TITLE
Update Kiali to 1.40.1

### ISSUE THREAD

**Issue by dhruvmewada15** [rancher/rancher#34740]
Kiali released version [1.40.1](https://kiali.io/news/release-notes/#_1_40_1)

- [x]  Mirror images in rancher/image-mirror repo
- [x]  Pull changes into rancher-kiali-server chart
- [x]  Update Istio Chart.yaml and Values.yaml to use the most recent version of Kiali

**Comment by doflamingo721** [comment]
With [1578](https://github.com/rancher/charts/pull/1578) we have updated the Kiali chart to 1.41.0

**Comment by vivek-infracloud** [comment]
Kiali v1.41.0, istio v1.11.4

Create a downstream cluster with 2worker, 1etcd, 1 cp

- Install istio version 1.11.4 by enabling kiali
- Verified the version of kiali installed is rancher/mirrored-kiali-kiali:v1.41.0
- Deploy a demo bookservice app in the istio-injected namespace and verified the app has installed by nodeIP:port/productpage
- From cluster explorer --> istio --> click on the kiali --> from graph [select namespace where the app is installed], the traffic is shown for the book demo app
- Install the weighted demo bookservice app and verified traffic generated from kiali --> graph --> verified the traffic going through ingress gateway
- Enable egress gateway and verified the traffic via egress gateway
