### ISSUE TITLE
Firefox - the down arrow for stack, service, host, and container is missing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3474]
Version - 0.57.0-rc2

Steps:
1.  Open app in Firefox browser
2.  Create two stacks
3.  Click on stack to get to stack detail page
4.  Click on stack name to bring down drop-down

Results:
The drop-down's down arrow is missing.  It's there in Chrome.  Just missing in Firefox.  This is for both light and dark theme.
Firefox:
![image](https://cloud.githubusercontent.com/assets/11514927/12690453/dd4f7050-c6a0-11e5-8dde-93d3d1c917b6.png)
![image](https://cloud.githubusercontent.com/assets/11514927/12690458/ec5e91fc-c6a0-11e5-8b18-62cc4b1c20ee.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/11514927/12690472/feb70168-c6a0-11e5-99b4-5fbb6cc411aa.png)

Expected:  The down arrow

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/470

**Comment by tfiduccia** [comment]
Version - master 2/17
Verified fixed
