### ISSUE TITLE
[Hosted Rancher] Consistent Max CPU load upon upgrade to v2.6.0

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34746]
Issues occurs upon hosted, HA upgrade from v2.5.9 to v2.6.0.

Child issues:
- Fleet: https://github.com/rancher/rancher/issues/34776
- Monitoring v1: https://github.com/rancher/rancher/issues/34833

SURE-3301

**Comment by dnoland1** [comment]
Tested with upstream Rancher v2.6.1-rc5 and upgrading downstream Rancher from v2.5.9 to v2.6.1-rc5. CPU Utilization and Load Average were the same before and after the upgrade. Checked the Rancher pod logs (both upstream & downstream) and did not see the repeated "Creating secret..." logs.

Performance graph (upgrade a little after 17:00):
<img width="801" alt="image" src="https://user-images.githubusercontent.com/468462/135183373-f1d0cef7-2322-4cf0-a998-a438f77fec93.png">
