### ISSUE TITLE
[backport] [rancher-alerting-drivers] bump prom2teams and sachet

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#34757]
backport https://github.com/rancher/rancher/issues/34942

The `rancher-alerting-drivers` chart needs to be upgraded to use the following new tags from the upstream:

- `Sachet` 0.2.6 https://github.com/messagebird/sachet/releases/tag/0.2.6 
- `Prom2teams` 3.2.3 https://github.com/idealista/prom2teams/releases/tag/3.2.3

**Comment by jiaqiluo** [comment]
### Root cause
N/A

### What was fixed, or what changes have occurred
This is a maintaining update to match the latest versions in the upstream charts 

### Areas or cases that should be tested
We need to validate that the new version of the `rancher-alerting-drivers` app can pass all those basic test cases in the test plan. 

 
### What areas could experience regressions?
- the installation process: when enabled, both sachet and prome2teams should be installed successfully
- sending out alerts: with the proper routes are configured, the alerts should be sent to the target successfully 

### Are the repro steps accurate/minimal?
N/A

**Comment by jiaqiluo** [comment]
can be tested in `rancher-alerting-drivers 1.0.301`

**Comment by Auston-Ivison-Suse** [comment]
Following validation for Sachet of rancher-alerting-drivers:
* fresh install checks:
  * on an rke1 cluster (1cp, 1etcd, 3worker, k8s 1.20.12)
    * deployed monitoring 16.6.1+up16.6.0 with rancher-alerting-drivers 1.0.301
      * workload is using version sachet:0.2.6
    * enter credentials for sms in the config.yaml
    * setup an alert for monitoring in prometheus
    * setup a receiver to sms webhook, and a route to that receiver + matching the label from the alert
    * **validated** alert is coming through the receiver setup for the telegram provider.
* Upgrade checks
  * on rancher 2.5.11 deploy rke1 cluster (1.20.12)
    * deploy monitoring  16.6.1+up16.6.0 with rancher-alerting-drivers 1.0.301
      * workload is using version sachet:0.2.6
    *  enter credentials for sachet in the config.yaml
    * setup an alert for monitoring in prometheus
    * setup a receiver to sms webhook, and a route to that receiver + matching the label from the alert
    * alert is coming through the receiver in the sms provider telegram
    * upgrade rancher to 2.5-head (73f121a)
    * alerts are still coming through in the sms provider telegram
    * upgrade alerting-drivers
      * workload is using version sachet:0.2.6
    *  **validated** old alert is coming through the connector in telegram
    *  **validated** new alert is coming through the connector in telegram

**Comment by Auston-Ivison-Suse** [comment]
@slickwarren has access to teams, which I do not. Until I have access I won't be able to complete validations for Prom2teams

**Comment by slickwarren** [comment]
Following validation for prom2teams (ms teams) of rancher-alerting-drivers:
* fresh install checks:
  * on an rke1 cluster (1cp, 1etcd, 3worker, k8s 1.20.13)
    * deployed monitoring 16.6.1+up16.6.0 with rancher-alerting-drivers 1.0.301
      * workload is using version prom2teams:3.2.3
    * **validated** alert is coming through in ms teams
* Upgrade checks
  * on rancher 2.5.11 deploy rke1 cluster (1.20.13)
    * deploy monitoring  16.6.0+up16.6.0 with rancher-alerting-drivers 1.0.200
      * workload is using version prom2teams:3.2.3
    * alert is coming through the receiver in ms teams
    * upgrade rancher to 2.5-head (07a745a)
    * alerts are still coming through in ms teams
    * upgrade alerting-drivers -> 1.0.301
      * workload is using version prom2teams:3.2.3
    *  **validated** old alert is coming through the connector in ms teams
    *  **validated** new alert is coming through the connector in ms teams
