### ISSUE TITLE
Terraform AKSv2 - Nodepool Error when using the default documented example

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#34752]
**Rancher Server Setup**
- Rancher version: `v2.6-head (09/15/2021)` _e03b203_
- Installation option: Helm Chart HA
   - If Helm Chart, Kubernetes Cluster and version: RKE1
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `1.21.4`
- Cluster Type: local
   - If downstream, what type of cluster? : N/A - Trying to provision an AKSv2 with Terraform

**Describe the bug**
While using the [AKSv2 example](https://github.com/rancher/terraform-provider-rancher2/blob/f5028682385d152a9a18a89ddf2db523ac588f55/docs/resources/cluster.md) from the `rancher2` provider doc I configure the provider with those values but using the `kubenet` `network_plugin`

**To Reproduce**

```terraform
resource "rancher2_cluster" "iztf1" {
  name = "iztf1"
  description = "Terraform AKS cluster"
  aks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.foo-aks.id
    resource_group = "iztf1"
    resource_location = "eastus2"
    dns_prefix = "iztf1"
    kubernetes_version = "1.21.2"
    network_plugin = "kubenet"
    node_pools {
      availability_zones = ["1", "2", "3"]
      name = "iztf1pool"
      count = 1
      orchestrator_version = "1.21.2"
      os_disk_size_gb = 64
      vm_size = "Standard_DS2_v2"
    }
  }
}
```

**Result**

`Waiting for API to be available:min and max node count must be nil for node pool [iztf1pool] for cluster [iztf1], because autoscaling is disabled`

**Expected Result**
AKSv2 cluster provisioned properly and in Active state in Rancher

**Screenshots**

<img width="1207" alt="Screen Shot 2021-09-15 at 12 59 16 PM" src="https://user-images.githubusercontent.com/27659/133501049-1903c413-f232-4e3a-807d-a7807a036ec3.png">

**Additional context**
https://github.com/rancher/rancher/issues/31296

**Comment by rawmind0** [comment]
Issue reproduced. Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/744 to fix it. 

@izaac TFP built binaries from the PR are available [here](https://github.com/rancher/terraform-provider-rancher2/pull/744#issuecomment-920401777) to facilitate tests

**Comment by izaac** [comment]
Rancher version: `v2.6-head (09/15/2021)` _e03b203_
I checked both fixed node count and auto scaling with the new binaries and it seems to be working as expected now.

**Comment by izaac** [comment]
This was validated as part of the Provisioning test scope of this issue: https://github.com/rancher/rancher/issues/31296#issuecomment-923169182
Provider version: `v1.20.0`
