### ISSUE TITLE
[vsphere-csi] Allow controller to recover if underlying node becomes unavailable

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#34751]
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: doesn't matter
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Infrastructure Provider (vSphere)

**Describe the bug**

The latest vSphere chart currently deploys the vSphere CSI controller onto any node, regardless of the taints set on the node, due to https://github.com/rancher/charts/blob/5411430480180a486d2e067f46d0906b79938626/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.0.0/templates/vsphere-csi-controller-deployment.yaml#L47-L50.

This is a bug since the CSI controller will not be evicted / rescheduled if the node it is deployed on becomes unhealthy.

**To Reproduce**
 

1. Deploy vsphere-csi on a Rancher downstream vsphere cluster
2. Perform an action that makes the node hosting the CSI controller unhealthy (e.g. delete the underlying VM but do not remove the node from Kubernetes)

**Result**

vsphere-csi-controller is never rescheduled automatically by Kubernetes.

**Expected Result**

vsphere-csi-controller should be automatically rescheduled when the underlying node is unhealthy

**Screenshots**

**Additional context**

The fix for this should involve two things:
1. The default for the tolerations should be set to match upstream instead of the current patch we applied, which deviates from the upstream behavior. As a result, vsphere CSI will only tolerate `NoSchedule` on master nodes by default, not `NoExecute` / `NoSchedule` on all nodes as it does now.
2. A user should be able to supply tolerations to override the provided default via the Helm chart by specifying it under `csiController.tolerations`, just like they can for `csiController.nodeSelector` today

SURE-3274

**Comment by slickwarren** [comment]
**Test Environment**
- Rancher Version:v2.5-head (ce52c78)
- Installation option (Docker install/Helm Chart):docker

**Information about the Cluster**
- Kubernetes version:1.19.15
- Cluster Type(s) tested on (Local/Downstream):downstream

**Overview of Validation**

* deployed a 1cp, 1etcd, 3worker cluster
* depoyed cpi/csi charts
  * deploy a test workload with a volume attached
* delete one worker node
  * validate that workload for `vsphere-csi-node` for that node is removed
* validate that new worker node (that auto-provisions) also has a workload for `vsphere-csi-node` automatically deployed once the node is active -- pass
* deploy a new workload bound to a new volume -- pass

**Comment by slickwarren** [comment]
also tested on the same version: 
* deployed a 2cp, 1etcd, 3worker cluster
* depoyed cpi/csi charts
  * deploy a test workload with a volume attached
  * observe which node the cpi/csi controllers are deployed to
  * taint that node with `key1=val1:NoExecute`
* ensure that the workloads are successfully rescheduled on an appropriate node -- pass
