### ISSUE TITLE
Terraform AKSv2 - Terraform requires the dns_prefix field while Importing an AKS cluster but import fails as it cannot be changed

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#34758]
**Rancher Server Setup**
- Rancher version: `v2.6-head (09/15/2021)` _e03b203_
- Installation option: Helm Chart HA
   - If Helm Chart, Kubernetes Cluster and version: RKE1
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `1.21.4`
- Cluster Type: local
   - If downstream, what type of cluster? : N/A - Trying to provision an AKSv2 with Terraform

**Describe the bug**

- After creating an AKS cluster in Azure Cloud I try importing it to Rancher with the Rancher2 TF provider

`Failed to update cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="PropertyChangeNotAllowed" Message="Changing property 'dnsPrefix' is not allowed." Target="dnsPrefix"`

**To Reproduce**

- Configure your Terraform locally with [these binaries](https://github.com/rancher/terraform-provider-rancher2/pull/744#issuecomment-920401777) for the rancher2 provider plugin.
- Use the following settings in the `rancher2_cluster` `aks_config_v2`

```terraform
resource "rancher2_cluster" "izimtf1" {
  name = "izimtf2"
  description = "Imported Terraform AKS cluster"
  aks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.foo-aks.id
    name = "izimtf1"
    resource_group = "izimtf1" 
    resource_location = "eastus2"
    dns_prefix = "izimtf1"
    imported = true
  }
}
```

**Result**

`Failed to update cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="PropertyChangeNotAllowed" Message="Changing property 'dnsPrefix' is not allowed." Target="dnsPrefix"`

If I remove the field Terraform fails with:

`The argument "dns_prefix" is required, but no definition was found.`

**Expected Result**

AKS cluster gets imported successfully and goes to Active state in Rancher

**Additional context**
https://github.com/rancher/rancher/issues/31296

**Comment by rawmind0** [comment]
Issue reproduced. Added a fix to PR https://github.com/rancher/terraform-provider-rancher2/pull/744 

@izaac TFP built binaries from the PR are available [here](https://github.com/rancher/terraform-provider-rancher2/pull/744#issuecomment-920832496) to facilitate tests

**Comment by izaac** [comment]
This was validated as part of the import testing scope of this parent issue:  https://github.com/rancher/rancher/issues/31296#issuecomment-923169182
