### ISSUE TITLE
Ping from container Redirect Host

### ISSUE THREAD

**Issue by Flowman** [rancher/rancher#3477]
I have this weird ping issue when traffic goes through network agent. Rancher 0.56.1 on coreos 899.5 in Azure. Host to host pings are fine.

ping 10.42.132.180 -R
PING 10.42.132.180 (10.42.132.180): 56 data bytes
64 bytes from 10.42.132.180: icmp_seq=0 ttl=62 time=0.924 ms
RR:     10.42.80.210 <- Container A
        10.42.19.220 <- Network Agent
        10.42.241.98 <- Network Agent
        10.42.132.180 <- Container B
        10.42.132.180
        10.42.241.98
        10.42.19.220
        10.42.80.210
64 bytes from 10.42.132.180: icmp_seq=1 ttl=62 time=1.245 ms
64 bytes from 10.42.132.180: icmp_seq=0 ttl=62 time=1.403 ms
92 bytes from 10.42.19.220: Redirect Host
64 bytes from 10.42.132.180: icmp_seq=1 ttl=62 time=25.454 ms
92 bytes from 10.42.19.220: Redirect Host
64 bytes from 10.42.132.180: icmp_seq=2 ttl=62 time=5.596 ms
92 bytes from 10.42.19.220: Redirect Host
64 bytes from 10.42.132.180: icmp_seq=3 ttl=62 time=4.983 ms
92 bytes from 10.42.19.220: Redirect Host
64 bytes from 10.42.132.180: icmp_seq=4 ttl=62 time=5.482 ms
92 bytes from 10.42.19.220: Redirect Host
64 bytes from 10.42.132.180: icmp_seq=5 ttl=62 time=4.672 ms
64 bytes from 10.42.132.180: icmp_seq=6 ttl=62 time=1.101 ms
92 bytes from 10.42.19.220: Redirect Host
64 bytes from 10.42.132.180: icmp_seq=7 ttl=62 time=5.973 ms
64 bytes from 10.42.132.180: icmp_seq=8 ttl=62 time=1.274 ms
64 bytes from 10.42.132.180: icmp_seq=9 ttl=62 time=0.820 ms
92 bytes from 10.42.19.220: Redirect Host
64 bytes from 10.42.132.180: icmp_seq=10 ttl=62 time=5.068 ms
64 bytes from 10.42.132.180: icmp_seq=11 ttl=62 time=1.308 ms
64 bytes from 10.42.132.180: icmp_seq=12 ttl=62 time=0.994 ms
64 bytes from 10.42.132.180: icmp_seq=13 ttl=62 time=1.098 ms
64 bytes from 10.42.132.180: icmp_seq=14 ttl=62 time=0.683 ms
64 bytes from 10.42.132.180: icmp_seq=15 ttl=62 time=1.428 ms

**Comment by deniseschannon** [comment]
I can't completely follow what your setup. Can you try the simple test of execing into the network agent and pinging the other network agent? 

Is this a fresh install or upgraded setup?

**Comment by Flowman** [comment]
This is a fresh install of v0.56.1 on coreos 899.6.0.

Agent to agent ping is fine. Only when i try to ping from container to container over host link or container to network agent over host link that i get bad ping and redirect host. This causes an issue when you have links between containers and the container selects a container on another host. It gives very high latency.

Here is screenshot of my setup.
![ping](https://cloud.githubusercontent.com/assets/212680/12871964/90db8758-cdcc-11e5-9474-c9bf50cbdbcc.PNG)

Example 
container to local network agent:
ping 10.42.71.136
PING 10.42.71.136 (10.42.71.136): 56 data bytes
64 bytes from 10.42.71.136: icmp_seq=0 ttl=64 time=0.212 ms
64 bytes from 10.42.71.136: icmp_seq=1 ttl=64 time=0.082 ms
64 bytes from 10.42.71.136: icmp_seq=2 ttl=64 time=0.095 ms
64 bytes from 10.42.71.136: icmp_seq=3 ttl=64 time=0.101 ms
64 bytes from 10.42.71.136: icmp_seq=4 ttl=64 time=0.102 ms

container to network agent over host link:
ping 10.42.167.164
PING 10.42.167.164 (10.42.167.164): 56 data bytes
64 bytes from 10.42.167.164: icmp_seq=0 ttl=63 time=1.020 ms
92 bytes from 10.42.71.136: Redirect Host
64 bytes from 10.42.167.164: icmp_seq=1 ttl=63 time=10.368 ms
92 bytes from 10.42.71.136: Redirect Host
64 bytes from 10.42.167.164: icmp_seq=2 ttl=63 time=5.363 ms
92 bytes from 10.42.71.136: Redirect Host
64 bytes from 10.42.167.164: icmp_seq=3 ttl=63 time=42.110 ms
92 bytes from 10.42.71.136: Redirect Host
64 bytes from 10.42.167.164: icmp_seq=4 ttl=63 time=16.967 ms

container to container over host link:
ping 10.42.96.53
PING 10.42.96.53 (10.42.96.53): 56 data bytes
64 bytes from 10.42.96.53: icmp_seq=0 ttl=62 time=0.760 ms
92 bytes from 10.42.71.136: Redirect Host
64 bytes from 10.42.96.53: icmp_seq=1 ttl=62 time=11.158 ms
92 bytes from 10.42.71.136: Redirect Host
64 bytes from 10.42.96.53: icmp_seq=2 ttl=62 time=4.794 ms
92 bytes from 10.42.71.136: Redirect Host
64 bytes from 10.42.96.53: icmp_seq=3 ttl=62 time=5.668 ms
92 bytes from 10.42.71.136: Redirect Host

agent to agent:
ping 10.42.167.164
PING 10.42.167.164 (10.42.167.164) 56(84) bytes of data.
64 bytes from 10.42.167.164: icmp_seq=1 ttl=64 time=0.523 ms
64 bytes from 10.42.167.164: icmp_seq=2 ttl=64 time=1.23 ms
64 bytes from 10.42.167.164: icmp_seq=3 ttl=64 time=0.498 ms
64 bytes from 10.42.167.164: icmp_seq=4 ttl=64 time=0.601 ms
64 bytes from 10.42.167.164: icmp_seq=5 ttl=64 time=0.555 ms
64 bytes from 10.42.167.164: icmp_seq=6 ttl=64 time=1.12 ms
64 bytes from 10.42.167.164: icmp_seq=7 ttl=64 time=0.905 ms

**Comment by deniseschannon** [comment]
Sorry for my misunderstanding, but what do you mean by "over host link"?

**Comment by Flowman** [comment]
Azure VNET host to host. Any traffic that talks between virtual machines.

**Comment by Xiangbo** [comment]
any update ? same issue reproduced , the first 8-9 package have a 8000 ms latency

**Comment by aemneina** [comment]
Flowman, did you ever get this solved? If you still face this issue, please reopen the issue.
