### ISSUE TITLE
Terraform AKSv2 - network_plugin setting should default to kubenet

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#34778]
**Rancher Server Setup**
- Rancher version: `v2.6-head (09/16/2021)` _ 1a57856_
- Installation option: Helm Chart HA
   - If Helm Chart, Kubernetes Cluster and version: RKE1
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `1.21.4`
- Cluster Type: local
   - If downstream, what type of cluster? : N/A - Trying to provision an AKSv2 with Terraform

**Describe the bug**

- Create a cluster without setting the `network_plugin` 

`network_plugin                 = (known after apply)`

**To Reproduce**

- Configure your Terraform locally with the latest dev binaries for the rancher2 provider plugin.
- Use the following settings in the `rancher2_cluster` `aks_config_v2`

```terraform
resource "rancher2_cluster" "iztf4" {
  name = "iztf4"
  description = "Terraform AKS cluster"
  aks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.foo-aks.id
    resource_group = "iztf4"
    resource_location = "eastus2"
    dns_prefix = "iztf4"
    kubernetes_version = "1.21.2"
    monitoring = false
    node_pools {
      availability_zones = ["1", "2", "3"]
      name = "iztf4pool"
      count = 3
      orchestrator_version = "1.21.2"
      os_disk_size_gb = 64
      vm_size = "Standard_DS2_v2"
    }
  }
}
```

**Result**

`Invalid network plugin value [] for [] cluster config`

**Expected Result**

**Screenshots**

<img width="444" alt="Screen Shot 2021-09-16 at 3 29 54 PM" src="https://user-images.githubusercontent.com/27659/133693883-6f58f956-5b32-4784-a595-b8c8a533b6e3.png">

**Additional context**
https://github.com/rancher/rancher/issues/31296
https://docs.microsoft.com/en-us/azure/aks/configure-kubenet

Azure defaults to `kubenet` as well as the Rancher UI

**Comment by rawmind0** [comment]
This is not an issue, this is the expected behaviour. As shown at docs and examples, `network_plugin` is required if `imported=false`. It can't be set as default value due to it may generate conflicts when the cluster is  imported.

**Comment by izaac** [comment]
@rawmind0 Ok thanks for the clarification. 

I think I got confused with the `aks_config` where the argument doc says  the default is `azure`  plus I was reading an old version of this document (this was merged a couple hours ago?):
https://github.com/rancher/terraform-provider-rancher2/commit/2d6772033d60f9d8f3bd78b15a7d1d95cee46aaf

Closing.
