### ISSUE TITLE
[BUG] Rancher agents being created over and over causing OOM on node

### ISSUE THREAD

**Issue by Yomanz** [rancher/rancher#34777]
**Rancher Server Setup**
- Rancher version: v2.5.9
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.20.6
- Cluster Type: Custom

**Describe the bug**
After removing a node from the cluster due to Hardware failure, we added it back after completely wiping it (with the same name, public & private IP), upon being added back to the cluster the node has had increasing amounts of `rancher/rancher-agent:v2.5.6` containers created on it. About one a minute and they all seem to be running.

**To Reproduce**
- Remove existing node from the cluster
- Add it back (after wiping it)
- Run `docker ps` and see all the new containers

**Result**
It creates a new rancher agent every minute

**Expected Result**
It should not do this.

**Screenshots**
![image](https://user-images.githubusercontent.com/5119107/133690175-31b0c2b1-f8a4-4abf-8e13-502885688c1e.png)
![image](https://user-images.githubusercontent.com/5119107/133690110-cbdd4a6b-a354-44aa-8acd-026bdcf339dd.png)
They are still created even after pods are deployed from other workloads.

There is a specific container crashing called `share-mnt`.
![image](https://user-images.githubusercontent.com/5119107/133690329-4c6fb47b-e786-4816-9e48-8a41834ac95b.png)

**Additional context**
I'm not 100% sure if it is actually related to re-adding a node that was previously in it.

**Comment by superseb** [comment]
What OS are you running? Possible duplicate of https://github.com/rancher/rancher/issues/31454
