### ISSUE TITLE
[Logging v1] Backport v2.6.0 fixes to v2.5.10

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34770]
`v2.5.10` (new) chart: https://github.com/rancher/system-charts/tree/dev-v2.5/charts/rancher-logging/0.2.5
`v2.5.9` (current) chart: https://github.com/rancher/system-charts/tree/dev-v2.5/charts/rancher-logging/0.2.4
Relevant issue: https://github.com/rancher/rancher/issues/34548

**Comment by izaac** [comment]
Rancher version: `v2.5.10-rc2`
Logging version: `v0.2.5`
RKE1 EC2 k8s `v1.20.11-rancher1-1`


I was able to do P0 test cases and I was no longer experiencing the ruby errors of the previous version.

**Comment by ronhorton** [comment]
Rancher version: `v2.5-head Commit ID 777b5d4d`
Logging v1 version: `v0.2.5`
RKE1 DO k8s `v1.20.13`


I was able to do P0 test cases and I was no longer experiencing the ruby errors of the previous version.
