### ISSUE TITLE
Remember AWS credentials

### ISSUE THREAD

**Issue by leebenson** [rancher/rancher#3478]
Would be nice if Rancher remembered AWS access credentials for spawning new servers.

I treat my AWS keys as ephemeral / write-and-forget and don't tend to keep them anywhere. Copying and pasting keys when setting up a new server each time adds an extra keygen step to deployment.

**Comment by rvion** [comment]
Rancher actually remember your aws credential, but I agree it's not really clear. 

if you `clone` an existing host provisionned with an aws key, the aws key will be prefilled in the host creation page

**Comment by leebenson** [comment]
Thanks @rvion, good to know.

**Comment by withinboredom** [comment]
You can also look into vault, by hashicorp, which will generate ephemeral keys on demand.

**Comment by deniseschannon** [comment]
@leebenson Since we have "Clone" to be able to get the same credentials, I'm going to close this issue. As @rvion mentioned, if you already got 1 host into your setup, then you can just clone it to create more.
