### ISSUE TITLE
Upgrade to rancher 2.6.0 do not clean up fleet-system namespace and older CRD's

### ISSUE THREAD

**Issue by chitha20** [rancher/rancher#34785]
We upgraded rancher from **2.5.9 to 2.6.0** recently and we figured out that **fleet system** namespace and older helm releases was not cleaned up 

We do see that now **fleet-agent-local** and **fleet-crd** is now moved under new namespace **cattle-fleet-system** and its now managing all fleet relevant CRD's in the cluster.

However expected behavior was it first deleted the older installation under **fleet system**  and removed the relevant CRD's and recreate everything under **cattle-fleet-system** 

Want to understand how do we cleanup without hindering any of the rancher functionality to just delete the releases from **fleet system**  namespace only .

**Comment by mohag** [comment]
Any idea if one of those agents are safe to remove?
