### ISSUE TITLE
conntrack v1.4.1

### ISSUE THREAD

**Issue by silviupanaite** [rancher/rancher#3479]
Component	Version
Rancher	v0.56.0
Cattle	v0.141.0
User Interface	v0.85.0
Rancher Compose	v0.7.1

Recently update to 0.56 and when host try to connect I get  the following error on an space with 2 host.
conntrack v1.4.1 (conntrack-tools): 1 flow entries have been deleted.
udp      17 19 src=host2 dst=host1 sport=4500 dport=4500 [UNREPLIED] src=172.17.0.20 dst=host2 sport=4500 dport=4500 mark=0 use=1
time="2016-01-31T13:30:49Z" level="error" msg="Error with the container stat scanner." error="bufio.Scanner: token too long"

**Comment by deniseschannon** [comment]
Have you tried restarting the network agents and hosts? I've commented on the other issue, that you might need to try and delete the network agent. 

Some other steps to report. Exec into the network agent and do a `ps-eaf | grep rancher-net`. You should get something like below. Ideally, for ubuntu, centos, rancheros, it should have --gcm=true and for coreos, it should have --gcm=false. 

```
root      3659     1  0 Jan26 ?        00:01:57 /var/lib/cattle/bin/rancher-net 
--log /var/log/rancher-net.log -f /var/lib/cattle/etc/cattle/ipsec/config.json -
c /var/lib/cattle/etc/cattle/ipsec -i 172.17.0.2/16 --pid-file /var/run/rancher-
net.pid --gcm=true                                                              
root     18025 18021  0 20:10 pts/0    00:00:00 grep rancher-net
```

**Comment by silviupanaite** [comment]
I restarted all the host and network agents and hosts, the issue of conntrack was resolved, host are visible in the rancher ui/network, but I'm currently running this problem:
https://github.com/rancher/rancher/issues/2901

**Comment by deniseschannon** [comment]
Closing this issue as the conntrack is fixed.
