### ISSUE TITLE
Custom Grafana Dashboards only appear after restarting pod

### ISSUE THREAD

**Issue by thaoula** [rancher/rancher#34809]
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.20.9
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
   - AKS

**Describe the bug**

We are attempting to provision a custom Grafana Dashboard using the ConfigMap method described in your documentation [here](https://rancher.com/docs/rancher/v2.6/en/monitoring-alerting/guides/persist-grafana/)

We initially used Fleet to deploy the ConfigMap which correctly placed the ConfigMap in cattle-dashboards. Grafana did not list the dashboard.

We then tried to create the ConfigMap using the Rancher UI. Grafana dd not list the dashboard.

After many attempts thinking we were doing something wrong we discovered this issue on k8s-sidecar which I believe is what you use to sync the ConfigMaps to files inside Grafana - https://github.com/kiwigrid/k8s-sidecar/issues/85

Here they talk about the process failing after 10 minutes and that restarting the pod would force reload. It killed the pod and the went to Grafana and it now displayed the dashboard I wanted to provision.

**To Reproduce**
 
1. Install Rancher Monitoring
2. Leave for more than 10 minutes (this number is based on the issue i mentioned above.. I had left it several days)
3. Provision a ConfigMap into cattle-dashboards namespace
4. Go to Grafana and you see nothing.
5. Kill the Grafana Pod 
6. Go to Grafana the custom dashboard will now appear

**Result**

**Expected Result**

Dashboard would be visible in grafana

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by mpretzer** [comment]
Did this ever get fixed? I see the same behaviour with rancher v2.7.10.
