### ISSUE TITLE
Change HTTPs Port

### ISSUE THREAD

**Issue by jbpoint** [rancher/rancher#34806]
Hello, 

am stucked, using rancher installed via helm. Where do i change the default https port of rancher to 8443 for example? 

Https://my.rancher.dev:8443

**Comment by vincent99** [comment]
When installed by Helm, Rancher is not publishing a port.. it's exposed by an ingress rule.  So to change the port you'd have to change the ingress configuration.  But usually the reason you'd want to is to avoid conflicting with using 80/443 for ingress, which isn't a problem in this situation.
