### ISSUE TITLE
Failed to download external drivers with Rancher proxy set

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#34801]
**Rancher Server Setup**
- Rancher version: v2.6.0
- Installation option (Docker install/Helm Chart): docker
- Proxy/Cert Details: In a private network that can only connect to the internet through a proxy

**Describe the bug**

**To Reproduce**
1. Install Rancher in a private network that can only connect to the internet through a proxy. Set http_proxy via env vars. e.g.,
```
$ sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 \
      -e HTTP_PROXY="http://192.168.0.1:3128" \
      -e HTTPS_PROXY="http://192.168.0.1:3128" \
      -e NO_PROXY="localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,192.168.10.0/24,.svc,.cluster.local,example.com" \
      --privileged rancher/rancher:v2.6.0
```
2. Go to Global -> Cluster Management -> Drivers -> Node Drivers
3. Activate the Harvester node driver
4. Create a new cluster using RKE2 Harvester provider.

**Result**
The provisioning failed.

Logs from the machine-provision pod in the fleet-default namespace:
```
Downloading driver from https://releases.rancher.com/harvester-node-driver/v0.3.0/docker-machine-driver-harvester-amd64.tar.gz
ls: cannot access 'docker-machine-driver-*': No such file or directory
downloaded file failed sha256 checksum
download of driver from https://releases.rancher.com/harvester-node-driver/v0.3.0/docker-machine-driver-harvester-amd64.tar.gz failed
```

**Expected Result**
Be able to download the driver through the http proxy.

**Comment by noahgildersleeve** [comment]
Blocked by https://github.com/rancher/rancher/issues/34891 .

**Comment by yasker** [comment]
No longer blocked due to https://github.com/rancher/rancher/issues/34891 has been fixed.

**Comment by yasker** [comment]
@noahgildersleeve Can you redo the test for this one?

**Comment by noahgildersleeve** [comment]
I tried to redo the test, but I wasn't able to get the Harvester imported into Rancher via virtualization management. I ran the `kubectl` commands and they seemed to be successful, but it wouldn't leave the pending state. I need to import it in order to deploy the RKE2 cluster. This hasn't been an issue in other configurations, but I'm not sure if it's related to it being tested in a virtual machine with a private bridge for testing airgap, or something else.
![Screenshot from 2021-09-30 14-07-52](https://user-images.githubusercontent.com/83787952/135530417-133faece-bc8d-476c-bb16-9eafd68c4552.png)

**Comment by gitlawr** [comment]
The cluster is in pending because it fails to pull the rancher/rancher-agent:v2.6.1 image on Harvester nodes. It needs support for https://github.com/harvester/harvester/issues/1218.

**Comment by gitlawr** [comment]
Tested in Rancher v2.6.1, Rancher is in an air-gapped environment with HTTP proxy configured and Harvester cluster has internet access. I can provision a guest cluster.

For the case when Harvester is air-gapped, it will be tracked in the following issues:
https://github.com/rancher/rancher/issues/32633
https://github.com/rancher/rancher/issues/34908
