### ISSUE TITLE
If there is a reconnecting host in the setup, global services are not launched on newly added hosts

### ISSUE THREAD

**Issue by MarcusSjolin** [rancher/rancher#3480]
Currently I am auto-scaling using ec2 auto scaling feature, this automatically enables more servers during daytime mon-fri. However when servers shut down in the evening and boot up in the morning, it's not the same servers, and the old ones end up trying to reconnect. This causes the feature of 1 instance per host not to work properly, as it won't create on the new ones spawned in the morning. Instead I have to remove the old reconnecting servers before more will spawn.

Probable cause:
It seems like the reconnecting servers are not counted towards the total of available servers, and the running services on the reconnecting servers are still counted.

**Comment by deniseschannon** [comment]
Reproduced with v0.58.0-rc1

Steps To Reproduce:

1. Create setup with hosts and a global service (no host labels needed)
2. Terminate a host (in the cloud provider) to force it into reconnecting state
3. Add a new host

Result: Global service is not triggered to add to brand new host. IF you remove the reconnecting state host, the global service gets launched.

Expected Result: Any new host should have the global service added regardless of other host states.

**Comment by MarcusSjolin** [comment]
Check, well put.

**Comment by MarcusSjolin** [comment]
Can this get some focus please

**Comment by deniseschannon** [comment]
Re-attempted with a master setup. 

Use case still doesn't work.

**Comment by alena1108** [comment]
@deniseschannon will look into it

**Comment by alena1108** [comment]
@deniseschannon could you test once again, I've put a fix. @MarcusSjolin thanks for raising this pretty bad bug

**Comment by deniseschannon** [comment]
Verified that it's working in master.
