### ISSUE TITLE
Export rancher cluster

### ISSUE THREAD

**Issue by meysamfarazmand** [rancher/rancher#34803]
Hi,

I have two rancher installations: v2.5 and v2.6. In v2.5 I have a cluster named "cloud-1".
I wanted to know is there any way to totally export "cloud-1" cluster and import it into Rancher 2.6?

**Comment by MSandro** [comment]
What kind of cluster is your cloud-1? It should work to use the import cluster feature. This generates you a kubectl command which you can execute in cloud-1. But depending on the cluster type you may be lose some management features

**Comment by meysamfarazmand** [comment]
> 
> 
> What kind of cluster is your cloud-1? It should work to use the import cluster feature. This generates you a kubectl command which you can execute in cloud-1. But depending on the cluster type you may be lose some management features

My Cluster in v2.5 is custom. I am searching for a way to export this cluster and import it in v2.6
