### ISSUE TITLE
Rancher 2.6: Wait-Checkin, http: request canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by CAberry** [rancher/rancher#34812]
**Rancher Server Setup**
- Rancher version: docker rancher/rancher (2.6)

**Information about the Cluster**
- Kubernetes version: v1.22.2 
- Type -> Imported
- 1 master / main bare-metal
- 2 workers bare-metal
- 1 virtual machine for rancher

**Describe the bug**
After importing custom k8s cluster to rancher and applying yml, the cluster status goes to "Active" even tho the conditions or not fully met. 

![image](https://user-images.githubusercontent.com/35067345/133931705-8ff24088-de73-4d61-93f3-02c7a42f7dcc.png)

Related Resources

![image](https://user-images.githubusercontent.com/35067345/133931858-5e7dfe14-382a-402b-9f66-0061b8db4884.png)

![image](https://user-images.githubusercontent.com/35067345/133932187-6432f9b6-1a16-42f2-a39b-8a192d32e896.png)

If we inspect the rancher with kubectl, the service with ip 10.43.25.58 is available and a curl command returns a response on port 443.

![image](https://user-images.githubusercontent.com/35067345/133932034-5788c633-b16c-4cad-ada1-96cfc33767a2.png)

```
778bd7e64174:/var/lib/rancher # curl --insecure https://10.43.25.58

{"type":"collection","links":{"self":"https://10.43.25.58/"},"actions":{},"pagination":{"limit":1000,"total":4},"sort":
(removed the full response of the curl command)
```

**To Reproduce**
Install a kubernetes cluster on premise (here debain 11) with one main and two workers, create a virtual machine (here debian 10 because rancher 2.6 fails on debian 11) and install rancher through docker command.
Import an existing cluster, apply kubectl command given by rancher. Wait for propagation on your k8s cluster. When status is active go to "related resources" tab.

**NB**: k8s cluster is hosted by different providers (bare-metal) and do not share the same private network. They are all accessible on public IP address.

**Result**
The cluster is not available in rancher till the step is not validated. The on premise k8s cluster is running without problem. Issue seems to be on rancher side.
**Expected Result**
Cluster should be imported

Hoping that this issue has enough details. I can add more informations if needed.
Thank you,

**Comment by CAberry** [comment]
docker exec to rancher container

```
728a8074350f:/var/lib/rancher # kubectl get all --all-namespaces -o wide
NAMESPACE             NAME                               READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
cattle-fleet-system   fleet-agent-b94869475-mhcnq        1/1     Running   2          26h   10.42.0.24   local-node   <none>           <none>
cattle-fleet-system   fleet-controller-974d9cc9f-tz4x2   1/1     Running   2          26h   10.42.0.23   local-node   <none>           <none>
cattle-fleet-system   gitjob-5778966b7c-cvp9n            1/1     Running   2          26h   10.42.0.21   local-node   <none>           <none>
cattle-system         rancher-webhook-7f84b74ddb-j8gkq   1/1     Running   2          26h   10.42.0.22   local-node   <none>           <none>
kube-system           coredns-7448499f4d-zlsj5           1/1     Running   2          26h   10.42.0.20   local-node   <none>           <none>

NAMESPACE             NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE   SELECTOR
cattle-fleet-system   service/gitjob            ClusterIP   10.43.146.60    <none>        80/TCP                   26h   app=gitjob
cattle-system         service/rancher           ClusterIP   10.43.250.231   <none>        443/TCP                  26h   <none>
cattle-system         service/rancher-webhook   ClusterIP   10.43.237.223   <none>        443/TCP                  26h   app=rancher-webhook
cattle-system         service/webhook-service   ClusterIP   10.43.7.78      <none>        443/TCP                  26h   app=rancher-webhook
default               service/kubernetes        ClusterIP   10.43.0.1       <none>        443/TCP                  26h   <none>
kube-system           service/kube-dns          ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP   26h   k8s-app=kube-dns

```
logs of fleet-controller-974d9cc9f-tz4x2
```
time="2021-09-20T20:39:32Z" level=error msg="error syncing 'fleet-default/k8s-XXX-XXX': handler import-cluster: Get \"https://10.43.250.231/k8s/clusters/c-m-965cj2jd/version?timeout=15s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers), requeuing"
```

logs of cattle-agent on k8s controller node

```
root@k8s-master:~# kubectl logs cattle-cluster-agent-558954f689-dt47x -n cattle-system
INFO: Environment: CATTLE_ADDRESS=172.18.214.196 CATTLE_CA_CHECKSUM=f5c72e049524fe48751f6dc150b25aa55c5ba65f5ef4b624556560a318f4aa8d CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.109.136.26:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.109.136.26:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.109.136.26 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.109.136.26:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.109.136.26 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.109.136.26 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-558954f689-dt47x CATTLE_SERVER=https://RANCHER_PUBLIC_IP
INFO: Using resolv.conf: nameserver 10.96.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5
INFO: https://RANCHER_PUBLIC_IP/ping is accessible
INFO: Value from https://RANCHER_PUBLIC_IP/v3/settings/cacerts is an x509 certificate
time="2021-09-20T15:33:20Z" level=info msg="Listening on /tmp/log.sock"
time="2021-09-20T15:33:20Z" level=info msg="Rancher agent version v2.6.0 is starting"
time="2021-09-20T15:33:20Z" level=info msg="Connecting to wss://RANCHER_PUBLIC_IP/v3/connect/register with token starting with 5qbkmtwljvjlmzzvsszt5qvfr2h"
time="2021-09-20T15:33:20Z" level=info msg="Connecting to proxy" url="wss://RANCHER_PUBLIC_IP/v3/connect/register"

```

Please advice, is it me doing something wrong? Do I need to rtfm again? 
Lost here... for me the cattle-controler should have no problem connecting to the service/rancher.


Cheers,

**Comment by Gfalconia** [comment]
@CAberry It seems rancher doesn't work correctly with k8s version 1.22+. I had similar problem, after installing k8s 1.21.5 rancher worked as expected.

**Comment by CAberry** [comment]
@Gfalconia Thank you for the hint ! It definitely works with 1.21.5 ! Thumbs up to you.
I'm not closing since this issue is still relevant for k8s v1.22+

**Comment by erSitzt** [comment]
Same here...

Sometimes it helps to check the support matrix first... :)
https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-2/
