### ISSUE TITLE
Downstream cluster not listed in Cluster  Management page for sometime after rancher upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34815]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `1f5852d`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: 1.20.11
- Cluster Type (Local/Downstream): Downstream RKE1 Custom cluster

**Describe the bug**
Downstream cluster not available in Cluster  Management page for sometime after rancher upgrade

**To Reproduce**

- On 2.5.9, deploy a downstream cluster - 1 etcd+control plane, 4 worker nodes
- Enable monitoring v1 on the local cluster and monitoring v2 on the downstream cluster
- Run pre upgrade checks using jenkins (Deploys resources on the downstream cluster)
- Upgrade rancher to 2.6-head using Helm
- Custom cluster is not available in Cluster management page

<img width="1276" alt="Screen Shot 2021-09-19 at 4 50 11 PM" src="https://user-images.githubusercontent.com/26032343/133947118-34dfa62e-9dee-414d-ae88-5e507cfea994.png">

- It seems to be available after 2.5 minutes
<img width="1670" alt="Screen Shot 2021-09-19 at 4 51 18 PM" src="https://user-images.githubusercontent.com/26032343/133947132-29620311-4b03-4b0a-8ffa-5265a8f2e43f.png">

- Some rancher logs:
```
2021/09/19 23:48:42 [INFO] Stopping cluster agent for c-lb4g8
2021/09/19 23:48:42 [ERROR] failed to start cluster controllers c-lb4g8: context canceled
2021/09/19 23:48:42 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/09/19 23:48:42 [INFO] Handling backend connection request [10.42.2.13]
2021/09/19 23:48:42 [INFO] Stopping cluster agent for c-lb4g8
2021/09/19 23:48:42 [ERROR] failed to start cluster controllers c-lb4g8: context canceled
```

Reach out for rancher logs

**Comment by cbron** [comment]
Ryan said he reproduced but it only had a problem for 30 seconds, so I am going to bump this from 2.6.1 as it resolves itself.

**Comment by sowmyav27** [comment]
Upgraded from 2.5.11 to 2.6.3-rc1 and 2.6-head commit id: `e322f8f`. This issue is not seen. Will close this issue now. Will reoopen or log a new one, when this happens again.
