### ISSUE TITLE
Use `UserAttribute.ExtraByProvider` to populate impersonation role rules

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#34822]
Followup from https://github.com/rancher/rancher/issues/34671

Depends on https://github.com/rancher/rancher/pull/33268. That PR will introduce a unified way to get a user's extra attributes from their auth provider, which we will be able to leverage to simplify how we generate the clusterrole rules related to user extras.

**Comment by samjustus** [comment]
SURE-4361

**Comment by cmurphy** [comment]
Moving to test, but I think this can just be tested via https://github.com/rancher/rancher/issues/36096

**Comment by brudnak** [comment]
Tested via  https://github.com/rancher/rancher/issues/36096#issuecomment-1103222428
