### ISSUE TITLE
[agent-instance] haproxy + sysdig = :heart:

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#3482]
I would be awesome if there could be a checkbox when creating a LB to have it add the stuff needed for Sysdig to pull stats from it.

http://support.sysdigcloud.com/hc/en-us/articles/205147903-Metrics-Configuration-Application-Checks#haproxy

**Comment by mishak87** [comment]
I think this is related to https://github.com/rancher/rancher/issues/3262. When it's done running collector should be pretty straight forward.

**Comment by alena1108** [comment]
@jwhitcraft @mishak87 you can workaround it even today by putting Sysdig config to custom "defaults" section. We append all user defines settings at the end of defaults section, and haproxy is not strict on indentation (only cares about the line starting with the haproxy specific keywords), so the following config would be valid:

```
.... other defaults 
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http
listen stats
bind *:1936
    mode http
    stats enable
    stats hide-version
    stats realm Haproxy\ Statistics
    stats uri /
    stats auth stats:stats
```

**Comment by jwhitcraft** [comment]
@alena1108,

I'll try this out tomorrow.

**Comment by jwhitcraft** [comment]
@alena1108 that didn't work, it just caused the LB to have errors.  I didn't get a chance to setup another test to see what is going on with it.

**Comment by alena1108** [comment]
@jwhitcraft once you hit the error again, could you share the error details here?

**Comment by superseb** [comment]
This should work after adding the custom haproxy.cfg, let us know if it doesn't work.
