### ISSUE TITLE
[v2.5.10] Backport: "helm upgrade/delete intermittently fails with errors like "unable to create impersonator account: error setting up impersonation for user u-xxxxx..Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io \"cattle-impersonation-u-8j72f\": the object has been modified; please apply your changes to the latest version and try again.""

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#34828]
Backport for https://github.com/rancher/rancher/issues/34671

**Comment by anupama2501** [comment]
Verified on v2.5-head `6b04f9b`

- Created a downstream rke1 imported cluster, local user and enabled openLDAP auth as admin
- Added the local user and a user from auth as cluster members in the cluster
- Logged in as the standard users and downloaded the kubeconfig file
- Verified the command did not throw any impersonator user errors `for i in `seq 1 10` ; do echo kubectl get pod -A --kubeconfig rkeimport.yaml; done | xargs -I {} -P 10 bash -c "{}"`
- Removed the users from the cluster as cluster members and added as cluster owners
- verified when the above command is run, list of pods displayed and no impersonation errors seen.
