### ISSUE TITLE
[Hosted Rancher, Monitoring V1, Alerting V1] CPU spike observed when Monitoring / Alerting installed in downstream Rancher's local cluster

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#34833]
**Rancher Server Setup**
- Rancher version: v2.5.9 Super Rancher cluster, v2.6.0 Downstream Rancher cluster
- Installation option (Docker install/Helm Chart): Helm Chart for both
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s for both
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: `v1.20.10+k3s1` for both
- Cluster Type (Local/Downstream): Impacted cluster is local to the Downstream Rancher, downstream to the Super Rancher cluster.
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported (k3s)

**Describe the bug**

When Monitoring V1 + Alerting V1 are enabled on a local cluster which itself is added as a downstream cluster on another Rancher instance, buggy behaviors during reconcile result in a spike in CPU / memory usage across nodes in the local cluster.

This seems to be caused by a race between the managing Rancher cluster and the Rancher cluster that is being managed since one thinks Monitoring / Alerting should be enabled while the other disagrees.

This is not seen in Rancher 2.5.9 managing Rancher 2.5.9; it is only seen in Rancher 2.5.9 managing Rancher 2.6.0.

**To Reproduce**
 

#### Note on Terminology

To replicate a Hosted Rancher setup, we will have two Ranchers:
- a Super Rancher cluster, which will manage other Ranchers. This will run Rancher 2.5.9
- a Downstream Rancher cluster, which will be added to the Super Rancher cluster as a downstream. This will run Rancher 2.6.0

I will refer to the Super Rancher cluster's local cluster as **superlocal**.

I will refer to the Downstream Rancher cluster's local cluster as **local**.

Both will run the last stable k8s 1.20 release: `v1.20.10+k3s1`

#### Note on Required Resources

I used 2 8GB_4vCPU Digital Ocean instances, where the first instance was used for the superlocal cluster (all roles) and the second instance was used for the local cluster.

I also provisioned DNS records that point to the superlocal host and the local host so that I could use it as the HOSTNAME below.

#### Setup Super Rancher Cluster

- Provision a node
- Install k3s on the node: `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.20.10+k3s1 sh -; export KUBECONFIG=/etc/rancher/k3s/k3s.yaml`
- Install Helm: `curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash`
- Run the following commands before installing Rancher
```
RANCHER_VERSION=v2.5.9

# Set the below to a hostname that can be used to access the Rancher instance
# HOSTNAME=HOSTNAME

helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
helm repo add jetstack https://charts.jetstack.io
helm repo update

kubectl create namespace cattle-system

kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml
kubectl create namespace cert-manager
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.0.4
```
- Run the following install to install Rancher
```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --version ${RANCHER_VERSION} \
  --set hostname=${HOSTNAME} --create-namespace
```
- Login to Rancher

#### Install Monitoring V1 onto the Rancher Super Cluster's local cluster
- On the Rancher Super Cluster `Cluster Manager` UI, click on the local cluster
- Go to Tools -> Monitoring
- Click on `Enable` at the bottom of the Monitoring install page with no other changes (note: version should be `0.2.2`).

Note: This step is only necessary to identify if we are seeing any spikes in the superlocal cluster as well.

#### Setup Downstream Rancher Cluster

- Install k3s: `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.20.10+k3s1 sh -; export KUBECONFIG=/etc/rancher/k3s/k3s.yaml`
- Install Helm: `curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash`
- Run the following commands before installing Rancher
```
RANCHER_VERSION=v2.6.0

# Set the below to a hostname that can be used to access the Rancher instance
# HOSTNAME=HOSTNAME

helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
helm repo add jetstack https://charts.jetstack.io
helm repo update

kubectl create namespace cattle-system

kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml
kubectl create namespace cert-manager
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.0.4
```
- Run the following install to install Rancher
```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --version ${RANCHER_VERSION} \
  --set hostname=${HOSTNAME} --create-namespace
```
- Login to Rancher

#### Add Rancher Downstream Cluster to Rancher Super Cluster
- On Rancher Super Cluster's Cluster Manager UI, click on `Add Cluster`
- Under `Register an existing Kubernetes cluster`, click on `Other Cluster`
- Name the cluster `downstream-rancher-260` and click `Create`.
- Run the provided kubectl command (I used the insecure command with `curl`) and run against the Rancher Downstream Cluster

#### Install Monitoring V1 onto the Rancher Super Cluster's downstream-rancher-260 cluster
- On the Rancher Super Cluster `Cluster Manager` UI, click on the local cluster
- Go to Tools -> Monitoring
- Click on `Enable` at the bottom of the Monitoring install page with no other changes (note: version should be `0.2.2`).

#### Install Alerting V1 onto the Rancher Super Cluster's downstream-rancher-260 cluster
- On the Rancher Super Cluster `Cluster Manager` UI, click on the local cluster
- Go to Tools -> Notifiers and configure a Notifier
- Go to Tools -> Alerts and add the configured Notifier to any of the provided alert groups. As long as at least one notifier is attached to at least one alert, Alerting V1 will be enabled.

**Result**

CPU + memory both settle in the cluster at an average of about 60%. 

Spammy logs are emitted from the local Rancher (e.g. the Rancher that is being managed by Rancher) that look like:

```log
2021/09/20 21:18:02 [ERROR] error syncing 'cattle-prometheus/cluster-alerting.v1': handler helm-app: failed to delete cattle-prometheus/cluster-alerting catalog.cattle.io/v1, Kind=App for helm-app cattle-prometheus/cluster-alerting.v1: apps.catalog.cattle.io "cluster-alerting" not found, requeuing
```

Logs are also emitted from the cluster-agent that look like:

```log
time="2021-09-20T21:19:15Z" level=error msg="error syncing 'cattle-prometheus/cluster-monitoring': handler helm-app-status: Operation cannot be fulfilled on apps.catalog.cattle.io \"cluster-monitoring\": StorageError: invalid object, Code: 4, Key: /registry/catalog.cattle.io/apps/cattle-prometheus/cluster-monitoring, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 7502104d-3720-4e93-84d8-3acb1adbd124, UID in object meta: , requeuing"
```

**Expected Result**

No CPU / memory spike should happen. It should be the same as managing any other downstream cluster, with some caveats.

Expected CPU should be around 20% average and expected memory should be around a 40% average.

**Screenshots**

**Additional context**

SURE-3301

**Comment by aiyengar2** [comment]
Diagnosed along with https://github.com/rancher/rancher/issues/34746 and https://github.com/rancher/rancher/issues/34776

**Comment by aiyengar2** [comment]
On the same cluster in which I was able to reproduce this issue, using Monitoring V2 instead of Monitoring V1 results in back-to-normal memory / CPU usage. This confirms that the issue here is with the Monitoring / Alerting V1 reconcile logic in a Rancher-in-Rancher setup.

**Comment by aiyengar2** [comment]
Both of the above logs seem to come from the Dashboard App controller here:

https://github.com/rancher/rancher/blob/7e7db270d9ac87355d063638929fd712c6616b72/pkg/controllers/dashboard/helm/apps.go#L38-L57

#### downstream rancher server log

```
2021/09/20 21:18:02 [ERROR] error syncing 'cattle-prometheus/cluster-alerting.v1': handler helm-app: failed to delete cattle-prometheus/cluster-alerting catalog.cattle.io/v1, Kind=App for helm-app cattle-prometheus/cluster-alerting.v1: apps.catalog.cattle.io "cluster-alerting" not found, requeuing
```

This error message stems from [`processSingleItem`](https://github.com/rancher/lasso/blob/30499d6858ba8c1d134ad89bc12292794d63d290/pkg/controller/controller.go#L199) in rancher/lasso, which wraps the error returned from `(*desiredSet).process` when an object is [marked for deletion](https://github.com/rancher/wrangler/blob/0babd42fbad8ddea4f9c106d7c03eeddfa8101ff/pkg/apply/desiredset_process.go#L308).

`(*desiredSet).process` is called when [`(*desiredSet).apply` is called](https://github.com/rancher/wrangler/blob/0babd42fbad8ddea4f9c106d7c03eeddfa8101ff/pkg/apply/desiredset_apply.go#L116), which is called when [`(*desiredSet).Apply` is called](https://github.com/rancher/wrangler/blob/0babd42fbad8ddea4f9c106d7c03eeddfa8101ff/pkg/apply/desiredset.go#L68-L74).

In turn, `(*desiredSet).Apply` is called when [`(*desiredSet).ApplyObjects` is called](https://github.com/rancher/wrangler/blob/0babd42fbad8ddea4f9c106d7c03eeddfa8101ff/pkg/apply/desiredset.go#L76-L80), which is exactly the call that we see at the end of `OnConfigMapChange` in the appHandler here:

https://github.com/rancher/rancher/blob/7e7db270d9ac87355d063638929fd712c6616b72/pkg/controllers/dashboard/helm/apps.go#L135-L167

#### super cluster-agent logs

```
time="2021-09-20T21:19:15Z" level=error msg="error syncing 'cattle-prometheus/cluster-monitoring': handler helm-app-status: Operation cannot be fulfilled on apps.catalog.cattle.io \"cluster-monitoring\": StorageError: invalid object, Code: 4, Key: /registry/catalog.cattle.io/apps/cattle-prometheus/cluster-monitoring, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 7502104d-3720-4e93-84d8-3acb1adbd124, UID in object meta: , requeuing"
```

This error seems to indicate that the app does not exist, but the `appStatus` function was still called on a non-existent object. I suspect this would occur if a controller were to enqueue a non-existent app, which would cause the `appStatus` function to get triggered since it is watching for changes to apps:
https://github.com/rancher/rancher/blob/7e7db270d9ac87355d063638929fd712c6616b72/pkg/controllers/dashboard/helm/apps.go#L49

My suspicion is that this is being triggered by `(*AppStateCalculator).sync`, which is triggered anytime a workload is changed within the cluster:

https://github.com/rancher/rancher/blob/7e7db270d9ac87355d063638929fd712c6616b72/pkg/controllers/managementuserlegacy/helm/state.go#L36

https://github.com/rancher/rancher/blob/7e7db270d9ac87355d063638929fd712c6616b72/pkg/controllers/managementuserlegacy/helm/state.go#L51-L79

Based on the above code, if the Rancher cluster-agent were to see a workload (e.g. Prometheus) associated with the Monitoring V1 app deployed by the Rancher super cluster, it would still be able to:
1. Get the app label, which seems to exist on the Prometheus deployment since it was added by the super Rancher cluster
2. Get the deployment's namespace
3. Get the project label from the deployment namespace, which seems to exist since it was added by the super Rancher cluster
4. Get the app based on the `projectNS` and `label`: since the lister here is the **management apps** lister, this will work.

https://github.com/rancher/rancher/blob/7e7db270d9ac87355d063638929fd712c6616b72/pkg/controllers/dashboard/helm/apps.go#L155-L158

Since the app is not nil and the deletion timestamp is not nil, we will proceed to enqueue the apps controller, which will fail since we omitted to create the app in the first place since it was Helm 2 in 2.6.x (this code did **not** get backported to 2.5.x):

https://github.com/rancher/rancher/blob/7e7db270d9ac87355d063638929fd712c6616b72/pkg/controllers/dashboard/helm/apps.go#L155-L158

**Comment by aiyengar2** [comment]
Further investigation has confirmed that this issue was caused by https://github.com/rancher/rancher/pull/33661.

Specifically, the issue here is that a Super Rancher-2.5 **creates** a app.catalog.cattle.io/v1 resource that is owned by the Helm 2 ConfigMap on enqueuing ConfigMap by executing the following code:

https://github.com/rancher/rancher/blob/6238e47b2198956ba59330bc171995aacbda1c08/pkg/controllers/dashboard/helm/apps.go#L155-L161

On the other hand, the Downstream Rancher-2.6 **destroys** any resources owned by the Helm 2 ConfigMap on enqueueing the ConfigMap by executing the following code:

https://github.com/rancher/rancher/blob/b24724f3eed83901ca02a67fd52d7a3fb3bc44c9/pkg/controllers/dashboard/helm/apps.go#L155-L158

As a result, the apps.catalog.cattle.io perpetually flaps, creating and destroying the resources every second, which is why we see logs like the above seen in the cattle-cluster-agent or rancher pods since the resources are created (resulting in enqueue) and then immediately destroyed before they are finished being processed. This also results in the CPU / Memory spikes seen.

P.S. Thanks @StrongMonkey for helping me figure this out!

**Comment by dnoland1** [comment]
Tested this with upstream rancher v2.6.1-rc5 and downstream rancher v2.6.1-rc5 with monitoring v1 enabled and did not see these error messages. Did not test upstream rancher v2.5.9 w/ downstream v2.6.1-rc5 since that is not a supported configuration (upstream must be v2.6 for v2.6 downstream clusters).
