### ISSUE TITLE
Hosted clusters are not deployed on Rancher Hosted setup after upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34837]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `ba43472` tenant on 2.5.9
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s on k3s
- Proxy/Cert Details: rancher generated

**Information about the Cluster**
- Kubernetes version: v1.20.10+k3s1
- Cluster Type (Local/Downstream): both downstream tenant and hosted rancher local

**Describe the bug**
Hosted clusters are not deployed on Rancher Hosted setup

**To Reproduce**

- Deploy EKS v2/AKS v2
- Clusters are stuck in `Provisioning` state with message `Waiting on eks crd to be initialized`

<img width="432" alt="Screen Shot 2021-09-20 at 11 55 59 PM" src="https://user-images.githubusercontent.com/26032343/134125359-07e79e7d-ff6f-4aad-bef8-52b19b6bc8fc.png">

- Rancher server logs:
```
2021/09/21 06:56:46 [ERROR] error syncing 'c-cnm8d': handler aks-operator-controller: waiting aks crd to be initialized, cluster: c-cnm8d, handler cluster-provisioning-operator: can't find system project, requeuing
--
Mon, Sep 20 2021 11:56:47 pm | 2021/09/21 06:56:47 [ERROR] error syncing 'c-fx4vq': handler eks-operator-controller: waiting eks crd to be initialized, cluster: c-fx4vq, handler cluster-provisioning-operator: can't find system project, requeuing
```

**Comment by sowmyav27** [comment]
**On 2.5.9 hosted rancher running 2.6-head commit id: `10dfee4` tenant rancher**

Provisioning of GKE/EKS/AKS v2 clusters work.

**Comment by rodriguezmelian** [comment]
The solutions is Create a NameSpace cattle-fleet-system if you don´t have in your Cluster.
