### ISSUE TITLE
vSphere provider does not allow NSX-T configuration

### ISSUE THREAD

**Issue by braunsonm** [rancher/rancher#34843]
**Rancher Server Setup**
- Rancher version: v2.6.0

**Describe the bug**
The vSphere cloud provider supports NSX-T Load Balancers and is no longer feature flagged as alpha. These config options aren't well documented but you can see them here: https://github.com/kubernetes/cloud-provider-vsphere/blob/d5f062858935b9c50b0e8e53463b6985ca34494c/pkg/nsxt/config/types_common.go#L20

Currently the chart for rancher does not allow you to set any of these settings for using NSX-T load balancers: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/100.0.0/templates/vsphere-cloud-config-cm.yaml

**Expected Result**
The Rancher vSphere provider chart should allow NSX-T configuration. Load Balancers should be able to be used.

**Additional context**
https://github.com/kubernetes/cloud-provider-vsphere/pull/425

**Comment by braunsonm** [comment]
Bump

**Comment by lukry59** [comment]
Double bump

**Comment by braunsonm** [comment]
Bump

**Comment by braunsonm** [comment]
Bump

**Comment by braunsonm** [comment]
Bump if anyone can open this
