### ISSUE TITLE
Upgrade Longhorn to v1.2.0

### ISSUE THREAD

**Issue by bjornjorgensen** [rancher/rancher#34841]
**Rancher Server Setup**
- Rancher version:2.6.0
- Installation option (Docker install/Helm Chart):Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):RKE
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:1.21.5
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
Longhorn v1.2.0 release but I cant find a upgrade for Longhorn in rancher. 
I have also added https://charts.longhorn.io to rancher, but I get errors when I try to update it.

<html>
<body>

  |  
-- | --
21/9/2021 14:28:06 | helm install --generate-name=true --namespace=longhorn-system --timeout=10m0s --values=/home/shell/helm/values-longhorn-1.2.0.yaml --version=1.2.0 --wait=true /home/shell/helm/longhorn-1.2.0.tgz
21/9/2021 14:28:07 | W0921 12:28:07.747962 25 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
21/9/2021 14:28:07 | Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodSecurityPolicy "longhorn-psp" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "longhorn-1-1632227286": current value is "longhorn"

</body>
</html>

**To Reproduce**
 

**Result**

**Expected Result**

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by D-o-c** [comment]
I have the same issues with Rancher 2.6. I have also checked in the [repo source](https://github.com/rancher/charts/tree/master/charts/longhorn) and it seems that rancher does not see the _latest_ folder :/

**Comment by nickgerace** [comment]
> I have the same issues with Rancher 2.6. I have also checked in the [repo source](https://github.com/rancher/charts/tree/master/charts/longhorn) and it seems that rancher does not see the _latest_ folder :/
> 
> EDIT
> 
> from [here](https://github.com/rancher/rancher/issues/34589) it seems it will be release in Rancher 2.6.1

Closing this because it will :)
