### ISSUE TITLE
Unable to provision RKE2 node driver clusters in an air-gapped setup in v2.6

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#34845]
Taken from the JIRA ticket [SURE-3347](https://jira.suse.com/browse/SURE-3347).

rancher/machine:v0.15.0-rancher69 is missing from rancher-images.txt for v2.6

**Issue description:**
In an air-gapped Rancher v2.6.0 environment, when attempting to provision an RKE2 node driver cluster, the rke2 machine provision Job Pod in the local cluster fleet-default Namespace fails to start, because the rancher/machine:v0.15.0-rancher69 image is missing from the private registry, as this is not in the v2.6.0 rancher-images.txt used to populate the private registry per air-gap docs (https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/air-gap/populate-private-registry/)

**Business impact:**
Unable to provision RKE2 node driver cluster until user manually pushes rancher/machine:v0.15.0-rancher69 to their private registry

**Troubleshooting steps:**
N/A

**Repro steps:**

Per air-gap Rancher install docs populate private registry from rancher-images.txt for v2.6.0
Install Rancher v2.6.0 into RKE cluster with private registry configured and `--set systemDefaultRegistry=<registry URL>`
Attempt to provision an RKE2 node driver cluster
Workaround:
Is workararound available and implemented? Manually push required rancher/machine:v0.15.0-rancher69 image to private registry

**Actual behavior:**
rancher/machine:v0.15.0-rancher69 requires manual pushing, as not in air-gapped images list

**Expected behavior:**
rancher/machine:v0.15.0-rancher69 included in air-gapped images list

**Files, logs, traces:**
N/A

**Additional notes:**
I encountered this issue whilst performing testing in a lab, versus a customer reported issue

**Comment by snasovich** [comment]
This has been completed in 2.6.1 per https://github.com/rancher/rancher/issues/34986. Closing.
