### ISSUE TITLE
prometheus and prometheus-agent pods keep restarting on the local cluster of HA rancher setup when local cluster is k3s 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34850]
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details: rancher generated

**Information about the Cluster**
- Kubernetes version: v1.20.10+k3s1
- Cluster Type (Local/Downstream): Local

**Describe the bug**
prometheus and prometheus-agent pods keep restarting on the local cluster of HA rancher setup

**To Reproduce**

- Deploy Rancher HA with k3s as local cluster on 2.5.9 (AWS t3.xlarge nodes)
- Enable monitoring v1 on the local cluster (0.2.2 version)
- It gets enabled fine. You can see the graphs on the cluster dashboard
- After sometime, the prometheus and prometheus-agent pods keep restarting.
- and the cluster dashboard do not have the graphs anymore.

Happens on fresh install of 2.6-head commit id: `b24724f` when k3s is the local cluster. Does not happen on fresh install when the local cluster is RKE1
Monitoring v2 works fine on the k3s local cluster HA setup

**Comment by jiaqiluo** [comment]
This bug is reproduced on a k3s `v1.21.5+k3s1` + rancher v2.6-head 223ec88b70d87cecee8fdbe8d98e30cf004b25d9

The k3s cluster, as the local cluster, has 3 nodes, all-role, 8 CPU 31GB memory per node. 

It turns out the Prometheus container is killed by `OOMKilled`. The following is from the StatefulSet `prometheus-cluster-monitoring`
```
containerStatuses:
  - containerID: containerd://48b8d58adae8e3036e1704759082b5208b2656d40753d23637e2abd5ca6d7235
    image: docker.io/rancher/mirrored-prom-prometheus:v2.18.2
    imageID: docker.io/rancher/mirrored-prom-prometheus@sha256:5c951449b3417bf4dbca2fe0dd9f34bd478b11aff3527189a699dc0e9efd5403
    lastState:
      terminated:
        containerID: containerd://48b8d58adae8e3036e1704759082b5208b2656d40753d23637e2abd5ca6d7235
        exitCode: 137
        finishedAt: "2021-09-22T21:49:18Z"
        message: |
          T21:48:38.047Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=7 maxSegment=9
          level=info ts=2021-09-22T21:48:38.147Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=8 maxSegment=9
          level=info ts=2021-09-22T21:48:38.147Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=9 maxSegment=9
          level=info ts=2021-09-22T21:48:38.147Z caller=head.go:627 component=tsdb msg="WAL replay completed" duration=10.085302816s
          level=info ts=2021-09-22T21:48:38.941Z caller=main.go:694 fs_type=EXT4_SUPER_MAGIC
          level=info ts=2021-09-22T21:48:38.941Z caller=main.go:695 msg="TSDB started"
          level=info ts=2021-09-22T21:48:38.941Z caller=main.go:799 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
          level=info ts=2021-09-22T21:48:38.946Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
          level=info ts=2021-09-22T21:48:38.947Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
          level=info ts=2021-09-22T21:48:38.947Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
          level=info ts=2021-09-22T21:48:38.948Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
          level=info ts=2021-09-22T21:48:38.949Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
          level=info ts=2021-09-22T21:48:38.950Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
          level=info ts=2021-09-22T21:48:38.951Z caller=main.go:827 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
          level=info ts=2021-09-22T21:48:38.951Z caller=main.go:646 msg="Server is ready to receive web requests."
        reason: OOMKilled
        startedAt: "2021-09-22T21:48:27Z"
    name: prometheus
    ready: false
    restartCount: 9
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=prometheus pod=prometheus-cluster-monitoring-0_cattle-prometheus(db73b89d-7449-4a5d-a296-79721f04cbee)
        reason: CrashLoopBackOff
```


The pod starts working after I change the memory limit from 1000Mi to 2000Mi on the  container `Prometheus`

**Comment by jiaqiluo** [comment]
We need to update the default `Prometheus Memory Limit` to 2000.

cc @codyrancher 

<img width="1070" alt="Screen Shot 2021-09-23 at 10 26 05 AM" src="https://user-images.githubusercontent.com/6218999/134555175-58f79645-06ac-4381-8816-f9babcd90234.png">

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `a9e61c5`**

Default `Prometheus Memory Limit` has been updated to 2000
<img width="1911" alt="Screen Shot 2021-09-24 at 3 53 59 PM" src="https://user-images.githubusercontent.com/26032343/134747343-b54d36f4-9753-47c6-a4e7-4691ea18688a.png">

**Comment by jiaqiluo** [comment]
The issue is also reproduced using the monitoring v2 

Reproduction 1:
```
- rancher v2.6.0 
- local cluster k3s v1.20.10+k3s1
- monitoring v2 14.5.100
```
The memory usage of the container Prometheus goes as high as 2.63GB and keeps at around 2.2 - 2.4 GB.
The pod is OOM killed because the current limit we set is 2500Mi

<img width="1594" alt="Screen Shot 2021-09-23 at 4 23 59 PM" src="https://user-images.githubusercontent.com/6218999/134748844-ffddc16e-d93f-48b9-a8a6-ddaa187c44f1.png">


Reproduction 2:
```
- rancher v2.6.0 
- local cluster k3s v1.20.10+k3s1
- monitoring v2 100.0.0+up16.6.0
```
The OOM kill also happens when using monitoring v2 `100.0.0+up16.6.0` which default memory limit for the Prometheus container is 2500Mi.

After raising the memory limit on the same setup same monitoring version, we get the following metrics for the Prometheus pod. The memory usage can go up to 2.64 GB

<img width="1802" alt="Screen Shot 2021-09-24 at 11 41 07 AM" src="https://user-images.githubusercontent.com/6218999/134748983-6dd6d7c8-ac70-4726-a5b6-6e30b6dd73fa.png">

**Comment by jiaqiluo** [comment]
Here is a related issue reported in the upstream that indicates the issue may exist since `Prometheus 2.16.0` https://github.com/prometheus/prometheus/issues/6934

**Comment by jiaqiluo** [comment]
**Data Point 1**
```
- rancher v2.5.9
- local cluster rke 1.21.5
- monitoring v2 16.6.0
```
Number of Series | Number of Chunks | Number of Label Pairs |  
-- | -- | -- |  
166576 | 333126 | 5438 

The peak value is about 1.14 GB
![image](https://user-images.githubusercontent.com/6218999/134755838-d50f956b-3dc4-45c5-8bae-fc15b16de7ab.png)



**Data Point 2**
```
- rancher v2.5.9
- local cluster k3s v1.21.5+k3s1
- monitoring v2 16.6.0
```
Number of Series | Number of Chunks | Number of Label Pairs |  
-- | -- | -- |  
250429 | 250429 | 4662

The peak value is about 1.59 GB
![image](https://user-images.githubusercontent.com/6218999/134755810-2b9b0510-df45-4121-82a3-f6d28bf0228b.png)

**Comment by cbron** [comment]
release-note: that this bug exists and we are adjusting limits

**Comment by jiaqiluo** [comment]
This is a [Promethues' upstream bug](https://github.com/prometheus/prometheus/issues/6934). Prior to it is fixed in the upstream, we will increase the default memory limit for the Prometheus pod in both monitoring v1 and v2 to mitigate the risk of triggering the bug.
Especially, we change the following value
```
monitoring v1, from 1000 Mi to 2000 Mi
monitoring v2, from 1500 Mi to 3000 Mi
```

**Comment by jiaqiluo** [comment]
The actual fixes are done in the UI and are ready for testing:
cluster management UI for monitoring v1 - https://github.com/rancher/ui/pull/4768
cluster explorer UI for monitoring v2 - https://github.com/rancher/dashboard/pull/4291

To QA:
- This issue can be closed as long as monitoring v1/v2 is not killed by OOM during your tests and daily opeartions 
- Dev can help to validate this issue if it is needed

**Comment by sowmyav27** [comment]
When the limits were increased, the monitoring on the clusters were fine and did not break. I will close this issue. Open a new one or reopen this later, if need be.
