### ISSUE TITLE
Need to migrate the installed charts in cluster manager (2.5) to cluster explorer (2.6)

### ISSUE THREAD

**Issue by innobead** [rancher/rancher#34853]
**Is your feature request related to a problem? Please describe.**
After upgrading to 2.6 from 2.5, the original chart installation does not show up in the cluster explorer UI. Also, the cluster manager will be deprecated, so users will be unable to upgrade the installed charts to newer versions by cluster explorer.

**Describe the solution you'd like**
Instead of enforcing users reinstall their existing installed charts, we need a way to migrate the original installation to manage by cluster explorer because the cluster manager is being deprecated. 

ex: Manage the original 2.5 release repo in 2.6 by cluster explorer. 

**Describe alternatives you've considered**
N/A

**Additional context**
This impacts Longhorn users who installed the chart from the cluster manager. 

cc @wjimenez5271 @cloudnautique

**Comment by bitfisher** [comment]
I hacked down a litte script recently which seems to work (testet with a few apps).
The original project App will not be removed yet, because i didn't find a way to delete the project App without deleting all related manifests too :(
Maybe someone at rancher could help out?

https://gist.github.com/bitfisher/25ba67624ece2c2e4b4c1d4f1661bc2e

**Comment by bitfisher** [comment]
Maybe related to #34700 ?
Maybe solved by #35202 ?

**Comment by innobead** [comment]
cc @Jono-SUSE-Rancher to prioritize. 
cc @cloudnautique and @wjimenez5271

**Comment by gricuk** [comment]
Do you have any updates how to migrate apps from cluster manager to cluster explorer?

**Comment by throrin19** [comment]
Same problem Here. Any updates ?

**Comment by bitfisher** [comment]
I migrated a few apps using the migration-script. (https://gist.github.com/bitfisher/25ba67624ece2c2e4b4c1d4f1661bc2e)

Sometimes some resources need to be manually labeled and annotated before, mainly because appId-label isn't present there.

But as far as i can tell it's working quite well.

**Comment by throrin19** [comment]
Unfortunatelly, in my case, I have no applications listed in `apps.project.cattle.io` in my clusters. But I found them directly with `kubectl get --all-namespaces apps`.

But, all apps are not listed in helm v3 😞 . I think, in my case, I have to change some parts of your script

**Comment by throrin19** [comment]
But if I made `kubectl get --all-namespaces apps` and `helm list -A`, I have a difference, and, for the non listed, in the metadata, I have them managed by Tiller 😞

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/3714 (ongoing)

**Comment by innobead** [comment]
cc @PennyScissors @SheilaghM

**Comment by throrin19** [comment]
I fix my problem here https://github.com/rancher/rancher/issues/36103

**Comment by throrin19** [comment]
After migrate all of them, I upgrade to rancher 2.6. In one of my cluster, many applications are not listed in installed apps but they are visible in helm applications list using command `helm list -A`. Why ?

**Comment by SheilaghM** [comment]
Closed by stalebot.  Reopening.

**Comment by innobead** [comment]
This has been done for Longhorn, https://longhorn.io/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui/ and https://github.com/longhorn/longhorn/issues/3714. 

Closing, but feel free to reopen if other users expect something for other app migrations.
