### ISSUE TITLE
Unable to complete RKE2 cluster provision with rancherd

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#34866]
**Rancher Server Setup**
- Rancher version: `v2.6-053d4c4ea4ce8218a55fc7efc34f22209239211c-head`
- Installation option (Docker install/Helm Chart): rancherd (Helm chart)
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `rke2 v1.21.4-rc1+rke2r4 (a7930411fc94c0a7907fa3991e3f0ae73518ea20)`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `rke2 v1.21.4-rc1+rke2r4 (a7930411fc94c0a7907fa3991e3f0ae73518ea20)`
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
We are testing `v2.6-053d4c4ea4ce8218a55fc7efc34f22209239211c-head` image from Harvester side. We use rancherd to deploy RKE2 runtime and rancher. The rancher-system-agent is not installed on the very first node.

Some error logs in fleet-controller pods:

```
time="2021-09-22T15:10:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=ClusterGroup controller"
time="2021-09-22T15:10:10Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2021-09-22T15:10:10Z" level=error msg="error syncing 'fleet-local/local': handler import-cluster: missing apiServerURL in fleet config for cluster auto registration, requeuing"
time="2021-09-22T15:10:10Z" level=error msg="error syncing 'fleet-local/local': handler import-cluster: missing apiServerURL in fleet config for cluster auto registration, requeuing"
time="2021-09-22T15:10:10Z" level=error msg="error syncing 'fleet-local/local': handler import-cluster: missing apiServerURL in fleet config for cluster auto registration, requeuing"
time="2021-09-22T15:10:10Z" level=error msg="error syncing 'fleet-local/local': handler import-cluster: missing apiServerURL in fleet config for cluster auto registration, requeuing"
time="2021-09-22T15:10:10Z" level=error msg="error syncing 'fleet-local/local': handler import-cluster: missing apiServerURL in fleet config for cluster auto registration, requeuing"
time="2021-09-22T15:10:12Z" level=error msg="error syncing 'fleet-local/local': handler import-cluster: missing apiServerURL in fleet config for cluster auto registration, requeuing"
```

Bundles:
```
# kubectl get bundles -A
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             0/1                       WaitApplied(1) [Cluster fleet-local/local]
fleet-local   local-managed-system-agent                    0/1                       WaitApplied(1) [Cluster fleet-local/local]
fleet-local   mcc-local-managed-system-upgrade-controller   0/1                       WaitApplied(1) [Cluster fleet-local/local]
```

**To Reproduce**
 
Ues rancherd to deploy RKE2 runtime alone with rancher image tag: `v2.6-053d4c4ea4ce8218a55fc7efc34f22209239211c-head`

**Result**

SUC pods are not running. System agents are not installed.

**Expected Result**

SUC pods should run and spawn jobs to install system agents.

**Screenshots**

**Additional context**
From Darren's comment, the cause might be new changes in fleet controller break the rancherd use case.

**Comment by bk201** [comment]
I can confirm RKE2 agent nodes can join the cluster with image `rancher/rancher:v2.6-0dd1ce6547cbb3253a8c6f48f5d538c98e7c567d-head`.

**Comment by yasker** [comment]
Per https://github.com/rancher/rancher/issues/34866#issuecomment-927588762, close this issue as fixed.
