### ISSUE TITLE
v2.6.0 to v2.6-head upgrade- failed to create fleet-local `admission webhook "rancherauth.cattle.io" denied the request` errors are seen in the logs of rancher pods for a brief period when the mcm flag is set to false

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34862]
**Rancher Server Setup**
- Rancher version: v2.6.0
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version:  `v1.21.4`
- Cluster Type (Local/Downstream): `local 3 nodes worker + etcd + cp`

**Describe the bug**
Rancher server is upgraded from v2.6.0-rc9 [rke 1.3.0-rc19] to v2.6.0 
When rancher server is installed with the environment variables `--set 'extraEnv[0].name=CATTLE_FEATURES' --set 'extraEnv[0].value=multi-cluster-management=false'`, rancher server comes up active, but the logs `failed to create fleet-local `admission webhook "rancherauth.cattle.io" denied the request` ` are seen in the rancher leader pod logs

**To Reproduce**
1. Create rancher server with rke1 cluster as local cluster 
2. Run the helm command 
`helm install rancher rancher-latest/rancher --version  2.6.0-rc9 --namespace cattle-system --set hostname=<redacted> --set 'extraEnv[0].name=CATTLE_FEATURES' --set 'extraEnv[0].value=multi-cluster-management=false' --set rancherImageTag=v2.6-head --kubeconfig rc9.yaml`

**Result**
Fleet local cluster is seen in error state in the continuous delivery --> fleet local --> error is seen on the fleet local cluster 
`Missing apiServerURL in fleet config for cluster auto registration`
Following logs are seen in the rancher pod logs scroll through continuously:
```
2021/09/22 19:58:52 [ERROR] error syncing 'local': handler provisioning-cluster-create: failed to create fleet-local/local provisioning.cattle.io/v1, Kind=Cluster for provisioning-cluster-create local: admission webhook "rancherauth.cattle.io" denied the request without explanation, requeuing
Wed, Sep 22 2021 11:59:02 am | 2021/09/22 19:59:02 [ERROR] error syncing 'local': handler provisioning-cluster-create: failed to create fleet-local/local provisioning.cattle.io/v1, Kind=Cluster for provisioning-cluster-create local: admission webhook "rancherauth.cattle.io" denied the request without explanation, requeuing
```

Note:
If we upgrade the rancher server version to v2.6.1-rc1 [rancher chart] and v2.6-head, we see the error for a brief period after the rancher version upgrades to the v2.6-head.

**Expected Result**
After upgrading the server to v2.6-head, the above error logs should not be seen in the rancher pod logs.

**Screenshots**
<img width="600" alt="Screen Shot 2021-09-22 at 12 33 19 PM" src="https://user-images.githubusercontent.com/38144301/134417615-d68879be-4be4-453f-bde8-8f5e4d99a7a6.png">

**Additional context**
Upgrading command via helm: `helm upgrade --install rancher rancher-latest/rancher --version  2.6.1-rc1 --namespace cattle-system --set hostname=<>  --set 'extraEnv[0].name=CATTLE_FEATURES' --set 'extraEnv[0].value=multi-cluster-management=false' --set rancherImageTag=v2.6-head --kubeconfig rc9.yaml`

Related: https://github.com/rancher/rancher/issues/34691

**Comment by dramich** [comment]
When you upgrade rancher we have to sync the catalog and deploy a new webhook, As part of that webhook builds caches and sleeps before fully running. The error went away after a short time meaning the new version is now running. Webhook is a separate pod, it's not part of rancher, so seeing some delay is expected.

**Comment by anupama2501** [comment]
closing this ticket as it is expected from Dan's comment:
```
When you upgrade rancher we have to sync the catalog and deploy a new webhook, As part of that webhook builds caches and sleeps before fully running. The error went away after a short time meaning the new version is now running.
```
