### ISSUE TITLE
[Hosted Rancher] resourceQuota controllers error logs on missing projects

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#34889]
Same setup as https://github.com/rancher/rancher/issues/34833. Seen in Rancher 2.5.9 and Rancher 2.6.0 for either the super rancher or downstream rancher setups.

**Describe the bug**

Observing the following repeated logs in a Hosted Rancher downstream Rancher logs: 
```
Thu, Sep 23 2021 2:09:30 pm | 2021/09/23 21:09:30 [ERROR] error syncing 'cattle-monitoring-system': handler resourceQuotaSyncController: projects.management.cattle.io "c-vpmfh/p-2f9qt" not found, handler resourceQuotaUsedLimitController: projects.management.cattle.io "c-vpmfh/p-2f9qt" not found, requeuing
Thu, Sep 23 2021 2:09:30 pm | 2021/09/23 21:09:30 [ERROR] error syncing 'fleet-system': handler resourceQuotaSyncController: projects.management.cattle.io "c-vpmfh/p-2f9qt" not found, handler resourceQuotaUsedLimitController: projects.management.cattle.io "c-vpmfh/p-2f9qt" not found, requeuing
Thu, Sep 23 2021 2:09:30 pm | 2021/09/23 21:09:30 [ERROR] error syncing 'cattle-prometheus': handler resourceQuotaSyncController: projects.management.cattle.io "c-vpmfh/p-2f9qt" not found, handler resourceQuotaUsedLimitController: projects.management.cattle.io "c-vpmfh/p-2f9qt" not found, requeuing
```

**To Reproduce**
 

See original ticket.

**Result**

Logs with errors are produced.

**Expected Result**

No errors should be logged.

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

This is likely due to the fact that our resource quota controllers do not have any logic for dealing with projects that are defined within the cluster but not owned by Rancher.

**Comment by aiyengar2** [comment]
Could be part of https://github.com/rancher/rancher/issues/34746.

**Comment by dnoland1** [comment]
Tested with upstream Rancher v2.6.1-rc5 and downstream Rancher v2.5.9 and v2.6.1-rc5. No longer seeing "error syncing..." logs.
