### ISSUE TITLE
Errors like "error syncing 'system-default-registry'" seen in rancher logs on a rancher server upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34894]
- Rancher version: 2.4.16 to 2.6.1-rc2 rancher
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher geenarted

**Information about the Cluster**
- Kubernetes version: 1.15.12, 1.18
- Cluster Type (Local/Downstream): Downstream - RKE1 custom cluster, Hosted clusters, imported k3s clusters

**Describe the bug**
Errors like "error syncing 'system-default-registry'" seen in rancher logs on a rancher server upgrade

**To Reproduce**

- On 2.4.16, deploy a bunch of clusters. (in my setup - Hosted clusters - AKS/GKE/EKS, imported k3s, windows, custom RKE1 linux cluster and ROS aws node driver cluster were present)
- RUn pre upgrade checks (deploys a bunch of resources on all the clusters)
- Upgrade rancher to 2.6.1-rc2
- Rancher logs show these errors.

**Result**
```
2021/09/24 00:27:17 [ERROR] error syncing 'install-uuid': handler copy-settings: the server could not find the requested resource, requeuing
2021/09/24 00:27:17 [ERROR] error syncing 'system-default-registry': handler copy-settings: the server could not find the requested resource, requeuing
2021/09/24 00:27:17 [ERROR] error syncing 'ingress-ip-domain': handler copy-settings: the server could not find the requested resource, requeuing
2021/09/24 00:27:47 [ERROR] error syncing 'system-default-registry': handler copy-settings: the server could not find the requested resource, requeuing
2021/09/24 00:27:47 [ERROR] error syncing 'ingress-ip-domain': handler copy-settings: the server could not find the requested resource, requeuing
2021/09/24 00:27:47 [ERROR] error syncing 'install-uuid': handler copy-settings: the server could not find the requested resource, requeuing
2021/09/24 00:28:17 [ERROR] error syncing 'system-default-registry': handler copy-settings: the server could not find the requested resource, requeuing
2021/09/24 00:28:17 [ERROR] error syncing 'install-uuid': handler copy-settings: the server could not find the requested resource, requeuing
2021/09/24 00:28:17 [ERROR] error syncing 'ingress-ip-domain': handler copy-settings: the server could not find the requested resource, requeuing
2021/09/24 00:28:47 [ERROR] error syncing 'install-uuid': handler copy-settings: the server could not find the requested resource, requeuing
2021/09/24 00:28:47 [ERROR] error syncing 'system-default-registry': handler copy-settings: the server could not find the requested resource, requeuing
2021/09/24 00:28:47 [ERROR] error syncing 'ingress-ip-domain': handler copy-settings: the server could not find the requested resource, requeuing

```

**Comment by rmweir** [comment]
Usually this happens for about a minute which is normal but in this case it lasts much long. From what I observed it can last indefinitely. I believe this is caused when one of the cluster provisioned has k8s version 1.15. This is also most likely related to https://github.com/rancher/rancher/issues/34893. Both issues are happening because the resource some logic depends on has not been deployed in the downstream cluster. Customers are expected to upgrade their cluster to 1.18 prior to upgrading. I think if this is done these issues will not appear.

**Comment by rmweir** [comment]
I have created a PR to add the cluster ID to the error message so that it is easier to diagnose these issues using logs: https://github.com/rancher/rancher/pull/34939.

**Comment by cbron** [comment]
2.5 logs pr: https://github.com/rancher/rancher/pull/35037

**Comment by sowmyav27** [comment]
Closing this
