### ISSUE TITLE
[Backup] Investigate "context aware" backup check intervals and retries

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34892]
Currently, Backup uses `clusterBackupCheckInterval` to re-queue backup creation in case of failure. We should investigate the possibility of using error codes, S3 features, etc. to determine what is a "failing backup" and whether or not the issue lies on the cluster or at the S3 source.

SURE-3305

**Comment by snasovich** [comment]
Moved to Team 2 as this issue is with RKE1 etcd backup logic and not rancher-backup operator.

**Comment by Jono-SUSE-Rancher** [comment]
This was actually resolved back with v2.6.4, closing this out of the backlog.
