### ISSUE TITLE
OPA - mirrored-openpolicyagent-gatekeeper-crds:v3.6.0 image missing from rancher-images.txt of v2.6.1-rc3

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#34897]
**Rancher Server Setup**
- Rancher version: `v2.6.1-rc3`
- Installation option: Helm HA Airgap
   - RKE1
- Proxy/Cert Details: self signed

**Information about the Cluster**
- Kubernetes version: `v1.21.5`
- Cluster Type: `Downstream`
   - Custom RKE1 Airgap
   - 2 Control Plane, 1 etcd, 4 Workers
   - AWS EC2

**Describe the bug**
- Installing the OPA Gatekeeper v2 Chart fails to create the `gatekeeper-update-crds-hook` job.
- 
**To Reproduce**

- Install Rancher Airgap RKE1 `v2.6.1-rc3` 
- Provision a custom RKE1 cluster
- Attempt install the OPA Gatekeeper Chart.

**Result**

  ImagePullBackOff:  Back-off pulling image  "<REGISTRY_URL>/rancher/mirrored-openpolicyagent-gatekeeper-crds:v3.6.0"

**Expected Result**
OPA Gatekeeper can be installed on Airgap / Cluster with private proxy

**Comment by sowmyav27** [comment]
gatekeeper related images in rancher-images.txt in `2.6.1-rc7`
```
rancher/mirrored-openpolicyagent-gatekeeper-crds:v3.6.0
rancher/mirrored-openpolicyagent-gatekeeper:v3.6.0
rancher/opa-gatekeeper:v3.1.0-beta.7
```
