### ISSUE TITLE
Amazon ec2 scaling up the machine pools for rke2 cluster as a cluster Owner with no access to cloud credentials displays the error The request must contain the parameter AWSAccessKeyId

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34909]
Setup

Rancher version: 2.6-head 1ae31b1
Browser type & version: Chrome

**Describe the bug**
When we edit the config of an ec2 rke2 node driver cluster as a cluster owner who didn't create the cluster to increase the machine pools count, cluster owner sees the error 
`The request must contain the parameter AWSAccessKeyId` and the request fails with the error `"VPC/Subnet" is required
`

**To Reproduce**

1. Create a rancher server on v2.6-head
2. As an admin, create an rke2 node driver amazon ec2 cluster with all roles 1 node - cluster1
3. Create a local user - user1 as an admin and add the user to the cluster1 as a cluster owner
4. Log in as the user1
5. From cluster management page --> edit the cluster

**Result**

- If we increase the count of the machine pools and save, we see the UI throws an error `"VPC/Subnet" is required`.
- If we do not edit the config but click on the + in the cluster management --> click on + sign in the machine pools page, a request is sent and a node is created from there.

**Expected Result**
An error should be thrown when cluster owner who didn't create the clusters [as the cloud credentials is not of the cluster owner] when scale up option is tried.

**Comment by gaktive** [comment]
Transferred from Dashboard: we don't think the proxy looks at the "new" rke2 provisioning clusters to decide if the current user should be allowed to make requests with the creator's credential

**Comment by snasovich** [comment]
@slickwarren , should be fixed already too, see https://github.com/rancher/rancher/issues/34910#issuecomment-999799621 for more info.
Please retest on 2.6.3.

**Comment by slickwarren** [comment]
can confirm, working as expected on 2.6.3:
* create rke2 downstream cluster as admin
* create a local user
  * add new user as cluster owner
* login as user
  * scale up/down a pool on the cluster -- pass
  * edit the cluster -- pass
