### ISSUE TITLE
AKS v2 [upgraded from v2.6.0 --> v2.6.1-rc3] stuck in loading resources while trying to edit the config 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34901]
**Rancher Server Setup**
- Rancher version: `v2.6.0` , post upgarde `v2.6.1-rc3`
- Installation option (Docker install/Helm Chart): Helm install
   - If Helm Chart, Kubernetes Info: rke1
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.21.4`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.21.1`
- Cluster Type (Local/Downstream): `Downstream AKSv2 3 worker`

**Describe the bug**
Not able to edit the config of AKS v2 cluster from cluster management. Cluster is stuck in loading for a long time and after some time, console errors seen and the cluster won't recover from that state.

**To Reproduce**

- Create rancher server v2.6.0
- Enable authentication [I enabled keycloak OIDC]
- As a standard user, create an AKS v2 cluster on v2.6.0 with 3 worker nodes on k8s `v1.21.1`
- Cluster comes active
- Upgrade the rancher server to v2.6.1-rc3
- From cluster management page --> edit config --> click on Configure cluster 

**Result**
Cluster is stuck in `loading resources` for a very long time and it won't recover from that state.
After some time, we see the console errors and a bad response for:
` https://<redacted>/meta/aksUpgrades?cloudCredentialId=cattle-global-data%3Acc-5vlfp&region=eastus&clusterId=c-wvm7q 502`

`Request Method: GET
Status Code: 502 `

Console errors:

```
component.js:315 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'findBy')
    at e.resourceLocationChanged (component.js:315)
    at g (index.js:219)
    at l (index.js:453)
    at invoke (backburner.js:338)
    at p.flush (backburner.js:229)
    at m.flush (backburner.js:426)
    at q._end (backburner.js:960)
```
**Expected Result**
Cluster edit should have worked fine without being stuck in `loading resources`

**Screenshots**
<img width="400" alt="Screen Shot 2021-09-23 at 9 15 19 PM" src="https://user-images.githubusercontent.com/38144301/134621961-7054b241-8960-4f16-84ad-5109e8fbeb30.png">

**Additional context**
I tried creating a cluster on v2.6.0-rc3 [upgraded from v2.6.0], I see the edit config doesn't work on the newly created cluster as well.
See this error in the rancher pods: 
`2021/09/24 05:04:24 [ERROR] [aks-handler] error getting kubernetes upgrade versions: failed to get orchestrators: containerservice.ContainerServicesClient#ListOrchestrators: Failure sending request: StatusCode=0 -- Original Error: context canceled`

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `fe57abd`**

- Deploy an AKS v2 cluster
- Click on Edit Config, upgrade k8s version. Save changes made
- Cluster goes into Updating state
