### ISSUE TITLE
Typo in the UI -> Prometheis vs Prometheus

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rancher#34904]
**Rancher Server Setup**
- Rancher version: 2.5.9 and 2.6.0
- Installation option (Docker install/Helm Chart): helm chart in RKE2 cluster
**Describe the bug**
Typo in the monitoring UI - Prometheis instead of Prometheus  

**To Reproduce**
Install rancher with monitoring and check the UI

Screenshot:

![grafik](https://user-images.githubusercontent.com/13362573/134663009-7874c4c0-e86e-4eb4-9534-47d350f85f13.png)

**Comment by vincent99** [comment]
[No](https://prometheus.io/docs/introduction/faq/#what-is-the-plural-of-prometheus).
