### ISSUE TITLE
be able to filtering system related namespaces

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#34911]
**Is your feature request related to a problem? Please describe.**
From the Harvester UI, we would like to be able to filter those system-related namespaces either created by the Rancher or the fleet. Currently, there is no way to identify it. @vincent99  suggested marking user namespaces. But there’s no proper way to know which namespace is a user namespace. We can add an annotation/use a name convention when users create namespaces from the UI but it will be missing if users create namespaces from native Kubernetes APIs.

**Describe the solution you'd like**
We are still leaning toward filtering the known ones for now. We should raise the problem of user out-of-band namespace creation (e.g. via Fleet)

**Describe alternatives you've considered**
open for the inputs.

**Additional context**

**Comment by yasker** [comment]
Per @dramich 
```
We maintain a setting SystemNamespaces that has them
https://github.com/rancher/rancher/blob/release/v2.6/pkg/settings/setting.go#L72
```

And per @prachidamle 
```
We also have a few namespaces added dynamically for fleet for example and they are added to the system project and carry an annotation "management.cattle.io/system-namespace": "true" 
```

Sounds like we should just label the known system namespaces.

**Comment by yasker** [comment]
Close this issue since we've the answers.
