### ISSUE TITLE
[Backport 2.5] Rancher crashes after adding a catalog containing a chart with missing name and version

### ISSUE THREAD

**Issue by genexpr** [rancher/rancher#34912]
SURE-3292

**Comment by genexpr** [comment]
### QA testing

Use Cluster Manager.
In the context of any cluster, add a new catalog. Give it a name and choose a repository that contains a bad chart definition. A bad chart definition in this case is one whose `Chart.yaml` is missing the `version` field. There is one that is good for testing: https://github.com/axeal/rancher-catalog

Use the above Catalog URL and select a branch that has an invalid `Chart.yaml`. In this case, the branch `noversion`. Then click Create and observe that there are no errors in the cluster. The catalog is added. It only contains one chart, and this chart is invalid. This means that when you try to add an App to a Project, this repository (catalog) you had added will not appear in the list of available catalogs, since it does not have any valid charts.

Add another catalog. Use the same Catalog URL but choose a branch that contains that same chart definition but in a valid form - the `master` branch. When you Create the new catalog, you will also not see any errors. But when you try to add an App, you will see your catalog with its charts (one, in this case) listed in the list of available catalogs.

**Comment by sowmyav27** [comment]
2.6 issue -https://github.com/rancher/rancher/issues/28776

**Comment by jmcsagdc** [comment]
**Reproduced the original error in** 2.5.0

**Verified fixed in** v2.5.10-rc2 and 2.5-head
