### ISSUE TITLE
vsphere scaling up the machine pools for rke2 cluster as a cluster Owner with no access to cloud credentials displays `NotFound: cloud credential not found` but scales up the nodes when tried by editing the config 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#34910]
**Setup**
- Rancher version: 2.6-head 1ae31b1
- Browser type & version: Chrome

**Describe the bug**
When we edit the config of a vsphere rke2 node driver cluster as a cluster owner who didn't create the cluster to increase the count of the machine pools, sees the error `NotFound: cloud credential not found` when we try to edit the config in the cluster management page

**To Reproduce**
1. Create a rancher server node on vmware vsphere 
2. As an admin, create an rke2 node driver vsphere cluster with all roles 1 node - cluster1
3. Create a local user - user1 as an admin and add the user to the cluster1 as a cluster owner
4. Log in as the user1 
5. From cluster management page --> edit the cluster

**Result**
We see the error mentioned in the title under the machine pools tab in the cluster management.
If we increase the count of the machine pools and save, we see the node is created with all roles and provisioned.
If we do not edit the config but click on the `+` in the cluster management --> <vsphere cluster> --> click on + sign in the machine pools page, a request is sent and a node is created from there as well.

**Expected Result**
An error should be thrown when cluster owner who didn't create the clusters [as the cloud credentials is not of the cluster owner] when scale up option is tried.

**Comment by gaktive** [comment]
Transferred from Dashboard: we don't think the proxy looks at the "new" rke2 provisioning clusters to decide if the current user should be allowed to make requests with the creator's credential. Related to #34909

**Comment by snasovich** [comment]
@anupama2501 , the expected result is no longer valid per https://github.com/rancher/rancher/issues/34800 - we now allow Cluster Owners who do not own the original cluster credential to edit cluster.

Could you please retest and see if Cluster Owner can edit nodes count in a node pool by either editing the cluster config or using +/- buttons on node pool in this case? Please be aware of an issue with long cluster/pool names that is not fixed yet: https://github.com/rancher/rancher/issues/35452

**Comment by snasovich** [comment]
Updated: Reassigning to @slickwarren to ramp up on V2 provisioning work.

**Comment by slickwarren** [comment]
blocked by https://github.com/rancher/rancher/issues/36004

**Comment by slickwarren** [comment]
I can confirm that the following does not throw any errors and the user is able to create new node pools/scale up/down on 2.6-head (375b0e6):
* Create a rancher server node on vmware vsphere
* As an admin, create an rke2 node driver vsphere cluster with all roles 1 node - cluster1
* Create a local user - user1 as an admin and add the user to the cluster1 as a cluster owner
* Log in as the user1
* From cluster management page --> edit the cluster
  * add a new node pool -- pass
* scale up a node pool -- pass
* scale down a node pool -- pass
