### ISSUE TITLE
Remove initial RancherD code and build process

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#34913]
These are the obvious ones, may be more: 
https://github.com/rancher/rancher/tree/master/cmd/rancherd
https://github.com/rancher/rancher/blob/release/v2.6/scripts/build-rancherd
https://github.com/rancher/rancher/blob/release/v2.6/scripts/build#L6

**Comment by snasovich** [comment]
Added `kind/task` to have this issue excluded from stalebot.

**Comment by macedogm** [comment]
Question: we will also remove rancherd from release/2.6, right?

**Comment by HarrisonWAffel** [comment]
Good point, I'll make a back port for this issue

**Comment by jameson-mcghee** [comment]
Additional testing comments from @HarrisonWAffel:

"we want to make sure that basic functionality still works on 2.7-head. When I was looking into this I thought of things that might have been impacted and should be validated
1. The helm chart for 2.7 head should be tested for basic functionality, just able to set up a new server without incident
2. this repo should eventually stop being updated https://hub.docker.com/r/rancher/rancher-runtime/tags. This one is hard to test. None of the currently open PR's for Rancher will include my changes, so this image will still be updated as those PR's are merged. Eventually we should not see any new tags.
3. basic cluster provisioning and management should not be impacted

The second scenario is the trickiest part"

**Comment by jameson-mcghee** [comment]
During testing on `v2.7-head` (Commit ID: 216bb7f), I was able to successfully create a Rancher server with all its resource assets without any errors. I was then able to deploy a downstream RKE2 cluster without error. Based on this testing, the additional testing input from @HarrisonWAffel, and the fact "_None of the currently open PR's for Rancher will include my changes, so this image will still be updated as those PR's are merged. Eventually we should not see any new tags._" prevents me from testing this aspect of the issue, I am closing this ticket as Done.

**`local` cluster:**
![image](https://user-images.githubusercontent.com/13294321/207180649-08452721-1f89-44fd-aac8-ce1ac7fdea3e.png)
![image](https://user-images.githubusercontent.com/13294321/207180667-829e0d1d-b6b1-4c99-9678-73185f20c1ba.png)
![image](https://user-images.githubusercontent.com/13294321/207180702-64aa0ded-5f60-47c5-be48-210a39cf6921.png)

**Downstream Cluster:**
![image](https://user-images.githubusercontent.com/13294321/207180599-d3d2bb7f-53de-4add-81a3-279fea55963d.png)

**Rancher Logs:**
[rancher-566cd4485d-z7xqx_rancher.log](https://github.com/rancher/rancher/files/10212840/rancher-566cd4485d-z7xqx_rancher.log)
