### ISSUE TITLE
Rancher Server Setup Failed

### ISSUE THREAD

**Issue by duan847** [rancher/rancher#34927]
**Rancher Server Setup**
- Rancher version: v2.6.0
- Installation option (Docker install/Helm Chart): Docker install
- Docker version: 20.10.7, build f0df350
- Mac OS version:  11.5.2 (20G95)

**Describe the bug**

```shell
2021/09/25 05:50:46 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment
2021/09/25 05:50:46 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=Cluster
2021/09/25 05:50:46 [ERROR] failed to sync cache for rke-machine.cattle.io/v1, Kind=AzureMachineTemplate
2021/09/25 05:50:46 [ERROR] failed to sync cache for rke-machine.cattle.io/v1, Kind=VmwarevsphereMachineTemplate
2021/09/25 05:50:46 [ERROR] failed to sync cache for rke-machine.cattle.io/v1, Kind=AzureMachine
2021/09/25 05:50:46 [ERROR] failed to sync cache for rke-machine.cattle.io/v1, Kind=Amazonec2MachineTemplate
2021/09/25 05:50:46 [ERROR] failed to sync cache for rke-machine.cattle.io/v1, Kind=Amazonec2Machine
2021/09/25 05:50:46 [ERROR] failed to sync cache for rke-machine.cattle.io/v1, Kind=DigitaloceanMachineTemplate
2021/09/25 05:50:46 [ERROR] failed to sync cache for cluster.x-k8s.io/v1alpha3, Kind=MachineSet
2021/09/25 05:50:46 [ERROR] failed to sync cache for cluster.x-k8s.io/v1alpha3, Kind=MachineHealthCheck
2021/09/25 05:50:46 [ERROR] failed to sync cache for cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment
2021/09/25 05:50:46 [ERROR] failed to sync cache for cluster.x-k8s.io/v1alpha3, Kind=Cluster
2021/09/25 05:50:46 [ERROR] failed to start controller for rke-machine.cattle.io/v1, Kind=AzureMachineTemplate: failed to wait for caches to sync
2021/09/25 05:50:46 [ERROR] failed to start controller for rke-machine.cattle.io/v1, Kind=VmwarevsphereMachineTemplate: failed to wait for caches to sync
2021/09/25 05:50:46 [ERROR] failed to start controller for rke-machine.cattle.io/v1, Kind=AzureMachine: failed to wait for caches to sync
2021/09/25 05:50:46 [ERROR] failed to start controller for rke-machine.cattle.io/v1, Kind=Amazonec2MachineTemplate: failed to wait for caches to sync
2021/09/25 05:50:46 [ERROR] failed to start controller for rke-machine.cattle.io/v1, Kind=Amazonec2Machine: failed to wait for caches to sync
2021/09/25 05:50:46 [ERROR] failed to start controller for rke-machine.cattle.io/v1, Kind=DigitaloceanMachineTemplate: failed to wait for caches to sync
2021/09/25 05:50:46 [ERROR] failed to start controller for cluster.x-k8s.io/v1alpha3, Kind=MachineSet: failed to wait for caches to sync
2021/09/25 05:50:46 [ERROR] failed to start controller for cluster.x-k8s.io/v1alpha3, Kind=MachineHealthCheck: failed to wait for caches to sync
2021/09/25 05:50:46 [ERROR] failed to start controller for cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment: failed to wait for caches to sync
2021/09/25 05:50:46 [ERROR] failed to start controller for cluster.x-k8s.io/v1alpha3, Kind=Cluster: failed to wait for caches to sync
E0925 05:50:46.924412      34 gvks.go:69] failed to sync schemas: failed to sync cache for rke-machine.cattle.io/v1, Kind=AzureMachineTemplate
2021/09/25 05:50:46 [INFO] Starting rke-machine-config.cattle.io/v1, Kind=LinodeConfig controller
2021/09/25 05:50:46 [INFO] Starting rke-machine.cattle.io/v1, Kind=LinodeMachine controller
2021/09/25 05:50:48 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=AzureMachineTemplate
2021/09/25 05:50:48 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=VmwarevsphereMachineTemplate
2021/09/25 05:50:48 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=AzureMachine
2021/09/25 05:50:48 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=Amazonec2MachineTemplate
2021/09/25 05:50:48 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=Amazonec2Machine
2021/09/25 05:50:48 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=DigitaloceanMachineTemplate
2021/09/25 05:50:48 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=MachineSet
2021/09/25 05:50:48 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=MachineHealthCheck
2021/09/25 05:50:48 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment
2021/09/25 05:50:48 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=Cluster
2021/09/25 05:50:49 [ERROR] failed to sync cache for cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment
2021/09/25 05:50:49 [ERROR] failed to start controller for cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment: failed to wait for caches to sync
E0925 05:50:49.228122      34 gvks.go:69] failed to sync schemas: failed to sync cache for cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment
2021/09/25 05:50:49 [INFO] Starting rke-machine.cattle.io/v1, Kind=AzureMachine controller
2021/09/25 05:50:49 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=Cluster controller
2021/09/25 05:50:49 [INFO] Starting rke-machine.cattle.io/v1, Kind=Amazonec2MachineTemplate controller
2021/09/25 05:50:49 [INFO] Starting rke-machine.cattle.io/v1, Kind=AzureMachineTemplate controller
2021/09/25 05:50:49 [INFO] Starting rke-machine.cattle.io/v1, Kind=Amazonec2Machine controller
2021/09/25 05:50:49 [INFO] Starting rke-machine.cattle.io/v1, Kind=DigitaloceanMachineTemplate controller
2021/09/25 05:50:49 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=MachineSet controller
2021/09/25 05:50:49 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=MachineHealthCheck controller
2021/09/25 05:50:49 [INFO] Starting rke-machine.cattle.io/v1, Kind=VmwarevsphereMachineTemplate controller
2021/09/25 05:50:50 [ERROR] error syncing 'local': handler provisioning-cluster-create: failed to create fleet-local/local provisioning.cattle.io/v1, Kind=Cluster for provisioning-cluster-create local: namespaces "fleet-local" not found, requeuing
2021/09/25 05:50:50 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment
2021/09/25 05:50:50 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment controller
2021/09/25 05:50:53 [ERROR] Failed to install system chart fleet-crd: failed to install , pod cattle-system/helm-operation-s5f9j exited 123
E0925 05:50:53.215348      34 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: gitjob.cattle.io/v1: the server could not find the requested resource
E0925 05:50:53.541505      34 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: gitjob.cattle.io/v1: the server could not find the requested resource
E0925 05:50:53.892298      34 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: gitjob.cattle.io/v1: the server could not find the requested resource
E0925 05:50:54.550331      34 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: gitjob.cattle.io/v1: the server could not find the requested resource
2021/09/25 05:51:15 [ERROR] error syncing 'machines.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/25 05:51:15 [ERROR] error syncing 'machinesets.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/25 05:51:15 [ERROR] error syncing 'machinedeployments.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/25 05:51:15 [ERROR] error syncing 'machinehealthchecks.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/25 05:51:15 [ERROR] failed to sync schemas: Post "https://127.0.0.1:6443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews?timeout=15m0s": EOF
exit status 255
W0925 05:51:16.047508      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *unstructured.Unstructured ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.051444      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *summary.SummarizedObject ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.051062      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.GlobalRoleBinding ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.051708      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.Cluster ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.052218      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.Setting ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.052863      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.MultiClusterApp ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.053464      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Secret ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.053998      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.SourceCodeCredential ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.054942      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.RoleTemplate ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.056002      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.App ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.056182      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.AuthConfig ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.056677      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.Token ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.056933      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.CatalogTemplate ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.057875      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.RkeAddon ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.058262      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.APIService ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.058500      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *summary.SummarizedObject ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.059515      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *summary.SummarizedObject ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.060260      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v3.CatalogTemplateVersion ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
W0925 05:51:16.064785      34 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Endpoints ended with: very short watch: pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: Unexpected watch close - watch lasted less than a second and no items received
2021/09/25 05:51:16 [FATAL] k3s exited with: exit status 255
```

**To Reproduce**
 

```
docker run -d --restart=unless-stopped \ 
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:v2.6.0
```

**Comment by romantomchak** [comment]
Hi @duan847 did you find a solution?

Because I faced with exactly the same problem.

**Comment by Forbzy** [comment]
I'm experiencing the same thing.

**Comment by hellocloudnative** [comment]
How to solve this problem, I also encountered this problem

**Comment by hellocloudnative** [comment]
@romantomchak

**Comment by romantomchak** [comment]
@hellocloudnative I temporarily postponed this, because I still can not manage it. I have tried a different versions of OS, different installation options but still no luck.

**Comment by xiazemin** [comment]
2021/11/19 02:20:47 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-6wz9k failed, watch closed
2021/11/19 02:20:58 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2021/11/19 02:20:58 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2021/11/19 02:21:13 [ERROR] error syncing 'system-library': handler system-image-upgrade-catalog-controller: upgrade cluster local system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [local] kubernetes version, requeuing
2021/11/19 02:21:28 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2021/11/19 02:21:28 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing

**Comment by Albert-liulei** [comment]
Rancher doesn't strike me as a very reliable person. Is there any other K8S management interface available? There are good, can recommend. thank you

**Comment by krim404** [comment]
i can confirm this bug on a debian/11 server, so it is not a general mac related problem.

**Comment by BigFatDog** [comment]
> 2021/11/19 02:20:47 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-6wz9k failed, watch closed 2021/11/19 02:20:58 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing 2021/11/19 02:20:58 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing 2021/11/19 02:21:13 [ERROR] error syncing 'system-library': handler system-image-upgrade-catalog-controller: upgrade cluster local system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [local] kubernetes version, requeuing 2021/11/19 02:21:28 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing 2021/11/19 02:21:28 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing

I'm having exactly the same error in new install. I see these error message during the initial login

* Centos 7.5
* Latest RKE in rancher guide
* Latest Rancher Helm Chart
* See a lot of helm operation pod errors in namespace cattle-system
* Check the rancher pod, got the above error message

**Comment by BigFatDog** [comment]
Is there any other stable version that I can use to get rid of this problem?

**Comment by BigBoatCap** [comment]
In my case it was _/etc/rancherssl/certs_ and content permissions :
```
chmod 0700 /etc/rancherssl/certs
chmod 0600 /etc/rancherssl/certs/mycert.pem
chmod 0600 /etc/rancherssl/certs/mycert.key
```

**Comment by atefibra** [comment]
same exact problem !! 
any fix ?

**Comment by flixofon** [comment]
Same problem here, some details:

- Ubuntu 20.04 and Fedora CoreOS
- Rancher v2.6.3
- Selfsigned Certs
- Standalone, Docker

Logs:

`2022/02/06 20:40:29 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [ERROR] error syncing 'server-url': handler apiservice-settings: secrets "tls-rancher-internal-ca" not found, requeuing
2022/02/06 20:40:29 [ERROR] Failed to find system chart fleet-crd will try again in 5 seconds: configmaps "" not found
2022/02/06 20:40:29 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [INFO] Starting monitoring.coreos.com/v1, Kind=Prometheus controller
2022/02/06 20:40:29 [INFO] Starting /v1, Kind=Service controller
2022/02/06 20:40:29 [INFO] Starting rke.cattle.io/v1, Kind=RKECluster controller
2022/02/06 20:40:29 [INFO] Starting management.cattle.io/v3, Kind=FleetWorkspace controller
2022/02/06 20:40:29 [INFO] Starting apps/v1, Kind=ReplicaSet controller
2022/02/06 20:40:29 [INFO] Starting batch/v1beta1, Kind=CronJob controller
2022/02/06 20:40:29 [INFO] Starting fleet.cattle.io/v1alpha1, Kind=Bundle controller
2022/02/06 20:40:29 [INFO] Starting cluster.x-k8s.io/v1alpha4, Kind=Cluster controller
2022/02/06 20:40:29 [INFO] Starting fleet.cattle.io/v1alpha1, Kind=Cluster controller
2022/02/06 20:40:29 [INFO] Starting monitoring.coreos.com/v1, Kind=ServiceMonitor controller
2022/02/06 20:40:29 [INFO] Starting rke.cattle.io/v1, Kind=RKEControlPlane controller
2022/02/06 20:40:29 [INFO] Starting apps/v1, Kind=Deployment controller
2022/02/06 20:40:29 [INFO] Starting batch/v1, Kind=Job controller
2022/02/06 20:40:29 [INFO] Detected v2.6.0 upgrade, forcing logout for all web users
2022/02/06 20:40:29 [INFO] Starting apps/v1, Kind=StatefulSet controller
2022/02/06 20:40:29 [INFO] Starting admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration controller
2022/02/06 20:40:29 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [INFO] Starting /v1, Kind=ReplicationController controller
2022/02/06 20:40:29 [INFO] Starting rke.cattle.io/v1, Kind=CustomMachine controller
2022/02/06 20:40:29 [INFO] Starting catalog.cattle.io/v1, Kind=App controller
2022/02/06 20:40:29 [INFO] Starting apps/v1, Kind=DaemonSet controller
2022/02/06 20:40:29 [INFO] Starting /v1, Kind=Endpoints controller
2022/02/06 20:40:29 [INFO] Starting management.cattle.io/v3, Kind=ManagedChart controller
2022/02/06 20:40:29 [INFO] Starting catalog.cattle.io/v1, Kind=Operation controller
2022/02/06 20:40:29 [INFO] Starting networking.k8s.io/v1, Kind=Ingress controller
2022/02/06 20:40:29 [INFO] Starting /v1, Kind=Node controller
2022/02/06 20:40:29 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [INFO] Starting /v1, Kind=Pod controller
2022/02/06 20:40:29 [INFO] Starting cluster.x-k8s.io/v1alpha4, Kind=MachineDeployment controller
2022/02/06 20:40:29 [INFO] Starting rke.cattle.io/v1, Kind=RKEBootstrapTemplate controller
2022/02/06 20:40:29 [INFO] Creating node driver azure
2022/02/06 20:40:29 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [INFO] Creating node driver cloudca
2022/02/06 20:40:29 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [INFO] Creating node driver cloudscale
2022/02/06 20:40:29 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [ERROR] error syncing 'server-url': handler apiservice-settings: secrets "tls-rancher-internal-ca" not found, requeuing
2022/02/06 20:40:29 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:29 [INFO] Creating node driver digitalocean
2022/02/06 20:40:29 [ERROR] error syncing 'server-url': handler apiservice-settings: secrets "tls-rancher-internal-ca" not found, requeuing
2022/02/06 20:40:29 [INFO] Creating node driver exoscale
2022/02/06 20:40:29 [ERROR] error syncing 'server-url': handler apiservice-settings: secrets "tls-rancher-internal-ca" not found, requeuing
2022/02/06 20:40:29 [INFO] Creating node driver google
2022/02/06 20:40:30 [ERROR] error syncing 'server-url': handler apiservice-settings: secrets "tls-rancher-internal-ca" not found, requeuing
2022/02/06 20:40:30 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/02/06 20:40:30 [INFO] Creating node driver harvester`

**Comment by iyinghui** [comment]
I'm not using the latest version, try the following version
`docker run -d --restart=unless-stopped  -p 80:80 -p 443:443  --privileged  rancher/rancher:v2.5.2`

**Comment by oingooing** [comment]
same problem

- upstream K8s v1.20.9
- Rancher v2.6.5
- containerd://1.4.6
- downstream rek2 cluster v1.23.7+rke2r2

journalctl -u rancher-system-agent
```Jul 07 16:02:08 test rancher-system-agent[3185]: time="2022-07-07T16:02:08+09:00" level=info msg="[Applyinator] Command sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null] finished with err: <nil> and exit
Jul 07 16:02:13 test rancher-system-agent[3185]: time="2022-07-07T16:02:13+09:00" level=error msg="[K8s] received secret to process that was older than the last secret operated on. (5706473 vs 5710993)"
Jul 07 16:02:13 test rancher-system-agent[3185]: time="2022-07-07T16:02:13+09:00" level=error msg="error syncing 'fleet-default/custom-258630ffdae8-machine-plan': handler secret-watch: secret received was too old,
Jul 07 16:03:11 test rancher-system-agent[3185]: W0707 16:03:11.748776    3185 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Secret ended with:
Jul 07 16:04:22 test rancher-system-agent[3185]: W0707 16:04:22.585674    3185 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Secret ended with:
Jul 07 16:05:18 test rancher-system-agent[3185]: W0707 16:05:18.561352    3185 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Secret ended with:
Jul 07 16:06:09 test rancher-system-agent[3185]: W0707 16:06:09.512870    3185 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Secret ended with:
Jul 07 16:07:18 test rancher-system-agent[3185]: W0707 16:07:18.349565    3185 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Secret ended with:
Jul 07 16:08:24 test rancher-system-agent[3185]: W0707 16:08:24.301306    3185 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Secret ended with:
Jul 07 16:09:27 test rancher-system-agent[3185]: W0707 16:09:27.981718    3185 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Secret ended with:
Jul 07 16:10:18 test rancher-system-agent[3185]: W0707 16:10:18.538541    3185 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Secret ended with:
Jul 07 16:11:06 test rancher-system-agent[3185]: W0707 16:11:06.609740    3185 reflector.go:437] pkg/mod/github.com/rancher/client-go@v0.21.0-rancher.1/tools/cache/reflector.go:168: watch of *v1.Secret ended with:```
