### ISSUE TITLE
Cannot login to Rancher

### ISSUE THREAD

**Issue by oxr463** [rancher/rancher#34920]
**Rancher Server Setup**
- Rancher version: v2.5.9 -> v2.6.0
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS
- Proxy/Cert Details: N/A, AWS Cert Manager

**Information about the Cluster**
- Kubernetes version: 1.18
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

Rancher is installed directly in an EKS cluster. After attempting to remove with system-tools and re-install, I can no longer login.

**To Reproduce**
 

1. Install Rancher v2.5.9 via helm (rancher-stable/rancher).
2. Uninstall Rancher via rancher/system-tools
3. Re-install Rancher v2.5.9 via helm.
4. Upgrade to Rancher v2.6.0 and specify `bootstrapPassword` in values.yml file.

**Result**

> Invalid username or password. Please try again. 

**Expected Result**

I would expect to be able to login.

**Screenshots**

<img width="837" alt="Screen Shot 2021-09-24 at 3 44 24 PM" src="https://user-images.githubusercontent.com/43783393/134731699-afdad262-9caf-407d-bae7-5d464252293f.png">

**Additional context**
<!--Add any other context about the problem here.—>

Here is the values.yml file contents:

```
hostname: rancher.foo.bar
replicas: 3
tls: external
bootstrapPassword: '[ . . . REDACTED . . . ]'
```

[kubetail_cattle-system.txt](https://github.com/rancher/rancher/files/7228088/kubetail_cattle-system.txt)

Reference(s):
- https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/amazon-eks
- https://github.com/rancher/system-tools

**Comment by peteingithub** [comment]
Did you try the `kubectl get secret ...` command provided in the screenshot to get the password from the system?

(I might be totally wrong, but I would think bootstrapPassword would not be set when upgrading.)

**Comment by oxr463** [comment]
> Did you try the `kubectl get secret ...` command provided in the screenshot to get the password from the system?
> 
> (I might be totally wrong, but I would think bootstrapPassword would not be set when upgrading.)

Yes, I did. I had the same password issue with v2.5.9, so I upgraded to v2.6.0 to see if I could work around the issue by giving it a bootstrap password to use.

**Comment by wirwolf** [comment]
I have same problem. But
Nobody cares.

**Comment by oxr463** [comment]
> I have same problem. But Nobody cares. Rancher 2.6.2

Are you on an EKS cluster? Did you delete Rancher and then re-install it? Just want to see if it's the same reproduction steps.

I haven't found a resolution yet.

**Comment by peteingithub** [comment]
Have you tried to reset the password with:
`kubectl -n cattle-system exec $(kubectl  -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- reset-password`

**Comment by oxr463** [comment]
> Have you tried to reset the password with: `kubectl -n cattle-system exec $(kubectl -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- reset-password`

Yeah, that didn't work for me.

**Comment by wirwolf** [comment]
> Have you tried to reset the password with: `kubectl -n cattle-system exec $(kubectl -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- reset-password`

I setup cluster on bare (1.21.1) by kubespray. After installation, I setup cert manager, Prometheus stack, and try install rancher by helm chart. In first iterations I try setup without bootstrap password in values of chart. And secret bootstrap password in cluster create with empty value. After they I add value using Lens and restart all rancher pod. But I can not login with this password

**Comment by peteingithub** [comment]
My setup is different than yours, so I do not have answers, sorry.

Have you tried the Rancher deployment as default with the random password? You would then get the command to track the password within the GUI during the first login?
How about setting an non-empty value with the `helm` command with `--set bootstrapPassword=password`

I am not familiar with Lens at all. I would try setting the password with kubectl instead of that in the first place. But still you could either let the system create you a random password or set one your self during the deployment.

(Nothing to do with the password issue, but I would deploy the monitoring stack from inside Rancher.)

**Comment by wirwolf** [comment]
I fix this bug in local cluster but very very ugly.
I create the app in the golang for generate new password.
```
package main

import (
	"golang.org/x/crypto/bcrypt"
	"log"

)

func main() {
	bootstrapPassword:= "testPass";
	hash, _ := bcrypt.GenerateFromPassword([]byte(bootstrapPassword), bcrypt.DefaultCost)
	log.Println("[Password for rancher] ", string(hash))
}

```
and generate password hash: $2a$10$Gtl3hBxSEwLFDjyxkDHGSejt7PFKdQr4020LDe0OPUSsSIypE6ofq
after that I found Resourse kind: User in Custome Resource, where displayName is "Default Admin" and change password manual using Lens
![Screenshot_20211104_102558](https://user-images.githubusercontent.com/8457572/140282235-ee95e531-727b-4e9e-b0d8-33dccd24a958.png)
![Screenshot_20211104_102822](https://user-images.githubusercontent.com/8457572/140282266-1f148dba-42cd-4abb-afcf-a6617c5d72fd.png)

**Comment by wirwolf** [comment]
> monitoring stack from inside Rancher

I not use rancher monitoring because I had many problems with using (https://github.com/rancher/rancher/issues/30990, https://github.com/rancher/rancher/issues/34009)

**Comment by peteingithub** [comment]
I have not had any password-related issues with any version of Rancher, and setting the password with kubectl has always worked for me. Weird. 
Sorry I could not help.

**Comment by oxr463** [comment]
Okay, so it turns out that the admin user account didn't exist! This was remedied via the following command:

```
kubectl --kubeconfig $KUBECONFIG -n cattle-system exec $(kubectl --kubeconfig $KUBECONFIG -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- ensure-default-admin
```

Thanks to this discovery by my colleague, I can finally login again. I now have a new issue where the local cluster is reporting it's state as "Removing" but that's another bug for another time.

![image](https://user-images.githubusercontent.com/43783393/140335939-fb5590b6-b2a7-4a88-a888-3b0a0d2fc95e.png)

**Comment by oxr463** [comment]
I'm running into this again in a new environment. This time, it's a k3s cluster on bare metal.

I also noticed the command no longer works:

```
kubectl --kubeconfig $KUBECONFIG -n cattle-system exec $(kubectl --kubeconfig $
KUBECONFIG -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }
') -- ensure-default-admin
Error: flags cannot be placed before plugin name: --kubeconfig
Error: flags cannot be placed before plugin name: --kubeconfig
```

I removed the `--kubeconfig $KUBECONFIG` parts and it returned this:

```
kubectl -n cattle-system exec $(kubectl -n cattle-system get pods -l app=ranche
r | grep '1/1' | head -1 | awk '{ print $1 }') -- ensure-default-admin
W0207 22:06:36.415205     162 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
Found existing default admin user (user-fm27f)
Existing default admin user (user-fm27f) is already enabled
Existing default admin user (user-fm27f) already labeled as admin
Existing default admin user (user-fm27f) is already an admin
```

So in this new environment, the user account is not missing.

**Comment by bunnyyy** [comment]
> Okay, so it turns out that the admin user account didn't exist! This was remedied via the following command:
> 
> ```
> kubectl --kubeconfig $KUBECONFIG -n cattle-system exec $(kubectl --kubeconfig $KUBECONFIG -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- ensure-default-admin
> ```
> 
> Thanks to this discovery by my colleague, I can finally login again. I now have a new issue where the local cluster is reporting it's state as "Removing" but that's another bug for another time.
> 
> ![image](https://user-images.githubusercontent.com/43783393/140335939-fb5590b6-b2a7-4a88-a888-3b0a0d2fc95e.png)

You can delete local cluster completely by patching cluster.management.cattle.io,
kubectl get clusters.management.cattle.io $(kubectl get clusters.management.cattle.io -o jsonpath='{range .items[*]}{@.spec.displayName}:{@.metadata.name}{"\n"}{end}' |  grep local | cut -d ":" -f2) -o=json|jq '.metadata.finalizers = null'| kubectl apply -f -

**Comment by namcnab** [comment]
> kubectl -n cattle-system exec $(kubectl -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- reset-password

This worked for me.
