### ISSUE TITLE
when network is set to "none", rancher ignores "hostname" parameter

### ISSUE THREAD

**Issue by deitch** [rancher/rancher#3492]
I have a new service I set up using docker-compose or the UI. If I set networking to "none", but add a custom hostname, Rancher ignores the custom hostname setting and instead uses the container ID as the hostname in the host.

This is not a docker issue. I tried running a container directly using `docker --net=none --hostname=myhostname` and it respects the hostname, setting it correctly in `/etc/hostname`.

**Comment by deniseschannon** [comment]
There was an error in v0.56.x with hostname that's being corrected in the next release. I will look into whether or not it's relevant to this issue. 

https://github.com/rancher/rancher/issues/3414

**Comment by deitch** [comment]
Thanks. If you need testing/validation/etc let me know.

**Comment by deniseschannon** [comment]
Verified in v0.58.0-rc2 that this is a bug. 

If it's not allowed, then the UI should not allow you to select "None" for network and pick your hostname.

**Comment by deitch** [comment]
> If it's not allowed, then the UI should not allow you to select "None" for network and pick your hostname

I don't understand the above. Network "none" should always be an option, and hostname matters and is allowed, even if network=none

**Comment by alena1108** [comment]
@deniseschannon if the fix is needed, most likely it has to be made on python-agent side. The field gets set correctly in the API

**Comment by cjellick** [comment]
Fixed. To test:

1. Create container in rancher UI
  * Set network mode to "none"
  * Set host name to something.
2. Verify
  * Container should have no IP in rancher ui
  * Exec into container and run `hostname`. Should display what was set in the rancher UI
  * You can also look at the docker inspect for the container and view the Hostanme field

**Comment by sangeethah** [comment]
Tested with latest build from master:

Created container in rancher UI with network mode set to "none" and host name set .
Container does not show any IP in rancher ui  and its hostname is set to hostname provided when creating the container.

Docker inspect for the container shows hostname set to hostname set.
With in the container , we see hostname being set.

``
root@testmehost:/# cat /etc/hostname
testmehost
root@testmehost:/# hostname
testmehost
root@testmehost:/# 
```
