### ISSUE TITLE
Error syncing rancher-rke2-charts

### ISSUE THREAD

**Issue by alexwiedermann** [rancher/rancher#34935]
**Rancher Server Setup**
- Rancher version: v2.5.9
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.17
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**Describe the bug**
Rancher-server unable to clone rancher-rke2-charts master branch 

**To Reproduce**
```
git clone --depth=1 -n --branch master https://git.rancher.io/rke2-charts
```

**Result**

**Expected Result**
Sucessful clone rke2-charts

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18265511/134923218-505b76f7-985f-4711-8c27-1a300133928d.png">
<img width="873" alt="image" src="https://user-images.githubusercontent.com/18265511/134923546-c793ca19-e94b-43ea-990c-550f227278b3.png">

**Additional context**

**Comment by haochun** [comment]
@alexwiedermann execuse me,how do you fix this problem?
