### ISSUE TITLE
Network between nodes is not working

### ISSUE THREAD

**Issue by mcuadros** [rancher/rancher#3493]
The networking between nodes is not working in managed mode, I cannot ping from containerA in nodeA to containerB in nodeB.

Pinging containerA to containerB:
````
ping 10.42.175.172
PING 10.42.175.172 (10.42.175.172): 56 data bytes
^C
--- 10.42.175.172 ping statistics ---
11 packets transmitted, 0 packets received, 100% packet loss
```

Pinging containerB to containerA:

````
root@c6ea2d27a907:/# ping 10.42.222.103
PING 10.42.222.103 (10.42.222.103) 56(84) bytes of data.
From 10.42.12.12 icmp_seq=2 Redirect HostFrom 10.42.12.12: icmp_seq=2 Redirect Host(New nexthop: 10.42.12.12)
From 10.42.12.12 icmp_seq=3 Redirect HostFrom 10.42.12.12: icmp_seq=3 Redirect Host(New nexthop: 10.42.12.12)
```


The nodeA also contains the rancher-server.


```
Rancher	v0.56.1
Cattle	v0.141.1
User Interface	v0.86.0
Rancher Compose	v0.7.1
```

```
OS: CentOS Linux release 7.2.1511 (Core)
Kernel: 3.10.0-327.3.1.el7.x86_64
```

**Comment by RXminuS** [comment]
Does it work in non-managed? What infrastructure you running it on?

**Comment by mcuadros** [comment]
The servers are bare-metals, if I don't use managed I don't have internal IPs

**Comment by withinboredom** [comment]
I was thinking it was just me yesterday. Is there any way to diagnose networking issues? I've got ports opened appropriately, but I got 0 connectivity between nodes though the agent appears to be functioning correctly.

**Comment by deniseschannon** [comment]
Have you confirmed that the Host IP address on the hosts are showing up correctly?

http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#adding-hosts-to-the-same-machine-as-rancher-server

**Comment by withinboredom** [comment]
From inside the container, I `dig consul` which is a service alias:
``` bash
;; ANSWER SECTION:                                                              
consul.                 600     IN      A       10.42.119.123                   
consul.                 600     IN      A       10.42.112.84                    
consul.                 600     IN      A       10.42.147.96                    
consul.                 600     IN      A       10.42.185.152                   
consul.                 600     IN      A       10.42.151.42  
```

.96 and .152 are on the same host:

``` bash
#> ping 10.42.147.96                                                            
PING 10.42.147.96 (10.42.147.96): 56 data bytes                                 
64 bytes from 10.42.147.96: icmp_seq=0 ttl=64 time=0.103 ms                     
64 bytes from 10.42.147.96: icmp_seq=1 ttl=64 time=0.113 ms                     
64 bytes from 10.42.147.96: icmp_seq=2 ttl=64 time=0.102 ms                     
^C--- 10.42.147.96 ping statistics ---                                          
3 packets transmitted, 3 packets received, 0% packet loss                       
round-trip min/avg/max/stddev = 0.102/0.106/0.113/0.000 ms                      
[ root@0e102f046feb :) ] /                                                      
#> ping 10.42.185.152                                                           
PING 10.42.185.152 (10.42.185.152): 56 data bytes                               
64 bytes from 10.42.185.152: icmp_seq=0 ttl=64 time=0.103 ms                    
64 bytes from 10.42.185.152: icmp_seq=1 ttl=64 time=0.053 ms                    
64 bytes from 10.42.185.152: icmp_seq=2 ttl=64 time=0.064 ms                    
^C--- 10.42.185.152 ping statistics ---                                         
3 packets transmitted, 3 packets received, 0% packet loss                       
round-trip min/avg/max/stddev = 0.053/0.073/0.103/0.000 ms  
```

However, trying to ping any of the same containers on another node:

``` bash
#> ping 10.42.119.123                                                           
PING 10.42.119.123 (10.42.119.123): 56 data bytes                               
^C--- 10.42.119.123 ping statistics ---                                         
9 packets transmitted, 0 packets received, 100% packet loss
```

Showing both 500 & 4500 on both nodes open to the universe at large:
``` bash
#> nc -vnzu 40.76.86.65 500                                                
(UNKNOWN) [40.76.86.65] 500 (isakmp) open                                       
[ root@0e102f046feb :) ] /                                                      
#> nc -vnzu 40.76.86.65 4500                                                    
(UNKNOWN) [40.76.86.65] 4500 (ipsec-nat-t) open                                 
[ root@0e102f046feb :) ] /                                                      
#> nc -vnzu 137.135.102.223 4500                                                
(UNKNOWN) [137.135.102.223] 4500 (ipsec-nat-t) open                             
[ root@0e102f046feb :) ] /                                                      
#> nc -vnzu 137.135.102.223 500                                                 
(UNKNOWN) [137.135.102.223] 500 (isakmp) open 
```

The rancher server is on a separate host.

**Comment by deniseschannon** [comment]
@withinboredom Are all your host showing the correct IP? Regardless of if rancher server is on a separate host, you want to make sure they are showing up correctly. 

What version of Rancher are you running? What OS are you using? Is this an upgraded setup or Fresh install? If upgraded, did you try to restart the network agents as well as restart the hosts?

Can you try these steps and provide the output?

Exec into the network agent and do a ps-eaf | grep rancher-net. You should get something like below. Ideally, for ubuntu, centos, rancheros, it should have --gcm=true and for coreos, it should have --gcm=false.

**Comment by withinboredom** [comment]
Ok, I'm about to dive into that... I just noticed that the ip shown in the ui is different than the actual ips (probably due to a dhcp leasing issue) ... could that be an issue, or does that matter. I'll be back shortly with those outputs.

**Comment by withinboredom** [comment]
Rancher: 0.56.1
OS: Ubuntu 14.04, fresh install, updated all the way
I deleted the network agents and rebooted ... ran into [this lovely kernel bug](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1403152) along the way

ps -eaf
``` bash
root      1279     1  0 18:21 ?        00:00:03 /var/lib/cattle/bin/rancher-net 
--log /var/log/rancher-net.log -f /var/lib/cattle/etc/cattle/ipsec/config.json -
c /var/lib/cattle/etc/cattle/ipsec -i 172.17.0.2/16 --pid-file /var/run/rancher-
net.pid --gcm=false
```

**Comment by withinboredom** [comment]
@deniseschannon : it looks like gcm is set to the wrong value somehow?

**Comment by withinboredom** [comment]
It must be the ip address issue. Rancher didn't know the node's ip had changed. I deleted the agents, and gave each node a static ip. Everything seems to be functioning correctly now.

**Comment by Ilya-Kuchaev** [comment]
I have the same issue. Cross hosts networking isn't working.

Not sure why but the iptables section is looking differently from http://docs.rancher.com/rancher/faqs/troubleshooting/

Agent server:
```
Chain CATTLE_PREROUTING (1 references)
num  target     prot opt source               destination         
1    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:443 to:10.42.45.67:443
2    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:80 to:10.42.45.67:80
3    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:9390 to:10.42.62.5:9390
4    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:9391 to:10.42.62.5:9391
5    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:4443 to:10.42.62.5:443

Chain DOCKER (2 references)
num  target     prot opt source               destination         
1    DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:4500 to:172.17.0.2:4500
2    DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:500 to:172.17.0.2:500
3    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 to:172.17.0.12:443
4    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:172.17.0.12:80
5    DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:1194 to:172.17.0.14:1194
6    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:9391 to:172.17.0.13:9391
7    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:9390 to:172.17.0.13:9390
8    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:4443 to:172.17.0.13:443
```
Main server with agent:
```
Chain CATTLE_PREROUTING (1 references)
num  target     prot opt source               destination         
1    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:5000 to:10.42.253.143:5000
2    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:22 to:10.42.176.95:22
3    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:443 to:10.42.76.0:443
4    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:80 to:10.42.76.0:80

Chain DOCKER (2 references)
num  target     prot opt source               destination         
1    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8080 to:172.17.0.5:8080
2    DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:4500 to:172.17.0.11:4500
3    DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:500 to:172.17.0.11:500
4    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:5000 to:172.17.0.26:5000
5    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 to:172.17.0.18:443
6    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:172.17.0.18:80
7    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22 to:172.17.0.29:22
```
How could I force the agent to update iptables (or add the entries manually) without restarting once I'm experiencing the magic kernel bug.

**Comment by withinboredom** [comment]
If you hit the kernel bug, you have no choice but to hard reset the machine. A `sudo reboot` takes several hours at times, and sometimes will never reboot.

**Comment by withinboredom** [comment]
Ok @deniseschannon ... I had a node offline for a long period (several days) ... before shutting down, it runs a script that uses the rancher ip to set the node as inactive, stop all running services on that node, and then delete and purge them. This includes the network manager, fwiw. Then the host shuts down. When it came back up today, and was activated.

The containers started on that node can't see any services running on the nodes that have been running for weeks... I brought another node out of "cold storage" and these two nodes' services can communicate with each other, but both can't communicate with the already running nodes.

If there's anything I can do to diagnose what's going on, let me know.

**Comment by withinboredom** [comment]
I just ran the script manually and brought back the node. It didn't have any issues rejoining. So, it seems that it might be related to the fact that the node was "inactive" for 46 hours?

**Comment by deniseschannon** [comment]
@withinboredom There were some major networking changes between v0.51.0 and v0.56.1 that might have caused the connectivity issues. Please monitor them over the next couple of weeks to see if it is consistently happening with the latest version.

@mcuadros It sounds like you are having cross host communication issues. Is this an upgraded setup or fresh setup?

**Comment by mcuadros** [comment]
@deniseschannon is a upgraded one.

**Comment by deniseschannon** [comment]
@mcuadros Have you tried all the recommended steps to get cross host networking to work? Restart network agent, if that doesn't work, restart host? 

Exec into the network agent and do a `ps-eaf | grep rancher-net`.  You should get something like below. Ideally, for ubuntu, centos, rancheros, it should  have `--gcm=true` and for coreos, it should have `--gcm=false`. Let me know what yours says.

```
root      3659     1  0 Jan26 ?        00:01:57 /var/lib/cattle/bin/rancher-net 
--log /var/log/rancher-net.log -f /var/lib/cattle/etc/cattle/ipsec/config.json -
c /var/lib/cattle/etc/cattle/ipsec -i 172.17.0.2/16 --pid-file /var/run/rancher-
net.pid --gcm=true                                                              
root     18025 18021  0 20:10 pts/0    00:00:00 grep rancher-net             
```

**Comment by mcuadros** [comment]
I tried all the recommendations a nothing works :/

> root     14677 13388  0 Feb02 ?        00:11:05 /var/lib/cattle/bin/rancher-net --log /var/log/rancher-net.log -f /var/lib/cattle/etc/cattle/ipsec/config.json -c /var/lib/cattle/etc/cattle/ipsec -i 172.17.0.2/16 --pid-file /var/run/rancher-net.pid --gcm=false

I have `--gcm=false` so ...

its false on centos 7.2

**Comment by fedya** [comment]
Same for me
[root@ABF_gluster-main_1 /]# ping gluster-client                                
PING gluster-client (10.42.204.239) 56(84) bytes of data.                       
From 10.42.23.166: icmp_seq=2 Redirect Host(New nexthop: 10.42.204.239)         
From 10.42.23.166: icmp_seq=3 Redirect Host(New nexthop: 10.42.204.239)   


[root@ABF_gluster-client_1 /]# ping gluster-main                                
PING gluster-main.rancher.internal (10.42.68.78) 56(84) bytes of data.  

No routing between nodes.

**Comment by mcuadros** [comment]
After update all the nodes to 0.8.0 (https://github.com/rancher/rancher/issues/3609) now the network is working
