### ISSUE TITLE
[Continuous Delivery] Newly migrated Fleet clusters to another FleetWorkspace will sometimes show 0/0 nodes for a short time

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34937]
This issue is both intermittent and transient. It was found while solving https://github.com/rancher/rancher/issues/34744 and may be a "non-issue" altogether. Still, it deserves some backend investigation and keeping a general eye on the frequency of which this issue is hit. There is a chance this may have been a "one off" issue due to provisioning behavior unrelated to Fleet (or Rancher's management of Fleet)

**Comment by kkaempf** [comment]
should be fixed by rancher/fleet#1123
