### ISSUE TITLE
[harvester node driver] unable to deploy v2 charts (i.e. monitoring v2, longhorn)

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34947]
**Rancher Server Setup**
- Rancher version:v2.6-head (06e19b0)
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:v1.21.4
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):harvester node driver

**Describe the bug**

* v2charts (i.e. monitoring) are unable to deploy on clusters deployed via harvester node driver

**To Reproduce**
 
* setup a harvester cluster
* import the cluster into rancher via `virtualization management`
* enable harvester node driver
* provision a cluster rke2 via the harvester node driver (at least 6vcpu for the worker node)
* deploy a v2 chart like monitoring once the cluster is active

**Result**
(for monitoring)
* logs don't show up for the user when the chart starts to deploy
* crd deploys fine, but monitoring chart does not finish deploying.  

**Expected Result**

v2 charts should be able to deploy on the cluster

**Screenshots**

**Additional context**
* I was also unable to _uninstall_ the bad deployment of monitoring after the first version failed to deploy properly. I will try to repro this on a new setup tomorrow

**Comment by guangbochen** [comment]
on the bare-metal Harvester cluster, both monitoring v2 and longhorn are a built-in component of the Harvester, can we verify using other charts instead, thanks.

**Comment by guangbochen** [comment]
I was able to deploy the monitoring app and logging app from the marketplace, probably it is related to the cluster resources, the default CPU and memory of the RKE2 node are 2 and 4 respectively,  both longhorn and monitoring require a certain amount of resources.
![image](https://user-images.githubusercontent.com/4569037/135207265-f0a64fc5-d3b2-4554-8373-b349c9194144.png)
![image](https://user-images.githubusercontent.com/4569037/135207295-9fc00e1e-7bc0-4da9-8075-e7d8bc3280cc.png)

**Comment by slickwarren** [comment]
retested on a larger node, and it seems to work fine. closing this issue
