### ISSUE TITLE
RKE2 cluster stuck in deleting state on deleting it when one of the node pools failed provisioning

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34945]
SURE-3585

**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `fe57abd`
- Installation option (Docker install/Helm Chart): HELM
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: rancher generated

**Information about the Cluster**
- Kubernetes version: 1.21.5 rke2
- Cluster Type (Local/Downstream): Downstream DO node driver

**Describe the bug**

**To Reproduce**
Deploy an RKE2 cluster - 1 node pool all roles.
Edit cluster - add a node pool - worker and save changes
The node pool is in error state
```
Failed creating server (DigitaloceanMachine) in infrastructure provider: CreateError: Failure detected from referenced resource rke-machine.cattle.io/v1, Kind=DigitaloceanMachine with name "do-test-pool2-27176adf-nmjh5": Running pre-create checks... Creating machine... (do-test-pool2-27176adf-nmjh5) Creating SSH key... (do-test-pool2-27176adf-nmjh5) Creating Digital Ocean droplet... Error creating machine: Error in driver during machine creation: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation. The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
```
- This seemed to be because of an invalid image specified.
- On deleting the cluster, the cluster is in `Removing` state  with message `Waiting for machine [do-test-pool2-797f58cbc9-b7rk4] to delete`
- The nodepool that failed provisioning is the only one pending in the machine pools page.

**Expected Result**
The cluster should get deleted, the node stuck in provisioning should also be deleted. (the node has not been created in the backend though in the first place)

**Comment by snasovich** [comment]
@janeczku , thank you for providing this info. However, I'd say this is technically a separate issue as for the original issue we don't even have VMs in the infra provider while we do in your case.
Regardless, the linked PR addresses both issues. To be more precise, it addresses the original issue and provides backe support to address the issue you've outlined. UI ticket https://github.com/rancher/dashboard/issues/4538 was created to track adding support for this new functionality on UI side.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `638b29`**

- Deploy an RKE2 cluster - 1 node pool all roles.
- Edit cluster - add a node pool - worker and save changes
- The node pool is in error state

```
Failed creating server (DigitaloceanMachine) in infrastructure provider: CreateError: Failure detected from referenced resource rke-machine.cattle.io/v1, Kind=DigitaloceanMachine with name "do-test-pool2-27176adf-nmjh5": Running pre-create checks... Creating machine... (do-test-pool2-27176adf-nmjh5) Creating SSH key... (do-test-pool2-27176adf-nmjh5) Creating Digital Ocean droplet... Error creating machine: Error in driver during machine creation: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation. The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
```

- This seemed to be because of an invalid image specified.
- On deleting the cluster, the cluster got Deleted successfully. And 1 node got got deleted

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `78b25c3`**

- Deploy an RKE2 cluster with 2 nodes
- Invalidate the cloud credentials used to provision the cluster by deleting the access token on the cloud provider side (e.g. Digital Ocean / AWS API token).
- Delete the cluster
- The cluster is stuck in deleting state
- Add this `provisioning.cattle.io/force-machine-remove: "true"` annotation on the infrastructure machine referenced by the current machines in the cluster `kubectl -n fleet-default edit digitaloceanmachines.rke-machine.cattle.io sow-testnew-pool1-7f7b2ba6-ts2sg`
- The nodes get removed and the cluster gets deleted from rancher

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `4da1618`**

- Deploy an RKE2 cluster with 2 nodes
- Invalidate the cloud credentials used to provision the cluster by deleting the access token on the cloud provider side (e.g. Digital Ocean / AWS API token).
- Delete the cluster
- The cluster is stuck in deleting state
- Nodes are in DeleteError state
- <img width="1369" alt="Screen Shot 2021-11-19 at 3 52 13 PM" src="https://user-images.githubusercontent.com/26032343/142705232-ea15640e-78d6-4775-8e17-ff0d4896e58f.png">
- Add this `provisioning.cattle.io/force-machine-remove: "true"` annotation on the infrastructure machine referenced by the current machines in the cluster `kubectl -n fleet-default edit digitaloceanmachines.rke-machine.cattle.io sow-testnew-xyz`
- The nodes get removed and the cluster gets deleted from rancher
