### ISSUE TITLE
Services are deploying, but are not working properly (i.e. nodeport)

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34948]
**Rancher Server Setup**
- Rancher version:v2.6-head(06e19b0)
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:any
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):any node driver 

**Describe the bug**

* services are deploying, but are not working properly

**To Reproduce**
 
* provision an rke2 cluster using a node driver
* deploy a workload with a service (i.e. nodeport) -- QA has a test for this if you need it

**Result**
service for the workload will deploy, but link is not generating for the service/link is not working through `services` -> `nodeport link`

**see comment below for more details**

**Expected Result**

* services should deploy and work with the workload they are associated with

**Screenshots**

<img width="1467" alt="Screen Shot 2021-09-27 at 10 04 07 PM" src="https://user-images.githubusercontent.com/16691014/135026452-c31373aa-e02f-4cd4-83aa-9786f055b0de.png">
<img width="924" alt="Screen Shot 2021-09-27 at 10 03 49 PM" src="https://user-images.githubusercontent.com/16691014/135026455-e63fe3e5-1310-4526-900a-c2567afb8115.png">

**Additional context**
also tested hostport, nodeport, clusterIP, loadbalancer, none of which are working properly through dashboard.

**Comment by yaocw2020** [comment]
![image](https://user-images.githubusercontent.com/7421463/135230453-901f0d8c-a9a1-4061-b762-8ea3c865a867.png)

There are two services. The first one created automatically when adding the deployment does not work while the second one created manually works. 

The second one has one more selector `workloadID_ngx-nodeport: "true"`, which matches no pod.

**Comment by yasker** [comment]
@slickwarren can you confirm that's due to a wrong selector?

**Comment by sowmyav27** [comment]
**On 2.6.0**

I see nodeport - deployment working. The additional selector as mentioned [here](https://github.com/rancher/rancher/issues/34948#issuecomment-929991464) in this comments is not added to the service that is created.

**Comment by slickwarren** [comment]
yes this is not harvester-specific, I will move this to reopened. it is happening with any rke2 setup

**Comment by kinarashah** [comment]
Available to test on v2.6-head after https://drone-publish.rancher.io/rancher/rancher/6600 passes.

**Comment by sowmyav27** [comment]
**On 2.6.1-rc9**

- Deploy a workload with nodeport enabled.
- The service created has only selector `workload.user.cattle.io/workloadselector=apps.deployment-default-test-new`
- And the nodeport hyperlinks are available and they work.
