### ISSUE TITLE
Failed to communicate with cluster: Unauthorized

### ISSUE THREAD

**Issue by PrateekKhatri** [rancher/rancher#34949]
Getting below error:

This cluster is currently Waiting; areas that interact directly with it will not be available until the API is ready.

Failed to communicate with cluster: Unauthorized

I have AWS EKS Cluster
Kubernetes version: v1.20

Rancher Version 2.5.9

Can u please help me why I am getting this error?

**Comment by hungbang** [comment]
Any update on this?
