### ISSUE TITLE
[harvester node driver] often, nodes are not being deleted on the backend when a cluster is deleted through rancher

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34946]
**Rancher Server Setup**
- Rancher version:v2.6-head(06e19b0)
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:any
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):harvester node driver 

**Describe the bug**

* nodes are not being removed on the backend when they are removed through rancher

**To Reproduce**
 
* setup a harvester cluster
* import the cluster into rancher via `virtualization management`
* enable harvester node driver
* provision some cluster(s) (rke1/rke2) via the harvester node driver
* delete one of the clusters at some point while it is provisioning or after it comes to active state

**Result**
* nodes/clusters are removed in rancher, but not through harvester.

**Expected Result**

* nodes provisioned via node driver should be deleted on the backend when removed through rancher

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by guangbochen** [comment]
tracked on https://github.com/harvester/harvester/issues/1306

**Comment by guangbochen** [comment]
I can also reproduce this issue with the amazon ec2 node driver, trying to delete the cluster while the cluster is under-provisioning, the cluster was removed but the ec2 instance will still be kept.
![image](https://user-images.githubusercontent.com/4569037/135050932-32d6bcfb-dcf7-47da-b848-bf8cba1d1939.png)

**Comment by yasker** [comment]
@slickwarren can you check if eventually the node was removed? Similar to what happened with EC2 instances.

**Comment by slickwarren** [comment]
They were not removed; in fact I cannot even manually remove them from harvester. They are stuck in a terminating state

**Comment by yasker** [comment]
@slickwarren might be some other issues on the Harvester side. Can you add the Harvester support bundle when you reproduce it?

**Comment by shangma** [comment]
@yasker  and I found some errors which indicates this isssue might be related to kubevirt itself. An example error is shown in the image below and all related errors are attached as a log file. 
![image](https://user-images.githubusercontent.com/2396545/135640203-9147868f-65f2-43dd-af88-c1d6dc1eb1d8.png)
[log.txt](https://github.com/rancher/rancher/files/7268063/log.txt)

**Comment by TachunLin** [comment]
Verified fixed on master-d577bb6c-head with rancher v2.6.3-rc1 (node driver v.0.3.4) 
Delete the RKE2 cluster while in provisioning and after it already deployed in active state.
Both the cluster and all VMs will be removed on rancher and harvester dashboard

Please check [harvester/harvester/#1306](https://github.com/harvester/harvester/issues/1306) for more details.
