### ISSUE TITLE
[harvester node driver] user can't provision rke1 cluster, node is stuck in `exit 0` loop

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34941]
**Rancher Server Setup**
- Rancher version:v2.6-head(06e19b0)
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:v1.21.5-rancher1-1
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): harvester node driver

**Describe the bug**

* user can't provision rke1 cluster using harvester node driver

**To Reproduce**
 
* create harvester setup
* import harvester into rancher via virtualization management
* enable harvester node driver
* use harvester node driver to provision single node (all roles) rke1 cluster

**Result**
node in `exit 0` status for 30 minutes, deletes the node, and all future nodes have the same issue. occasionally will show this error message for ~1 second:
<img width="689" alt="Screen Shot 2021-09-27 at 3 54 58 PM" src="https://user-images.githubusercontent.com/16691014/134996288-1a397067-644b-4cdf-8b96-e4abaf6dc7f2.png">

**Expected Result**

harvester node driver should be able to provision an rke1 cluster

**Screenshots**
<img width="1122" alt="Screen Shot 2021-09-27 at 4 04 04 PM" src="https://user-images.githubusercontent.com/16691014/134996838-d6924f48-9d6f-4fc6-8663-1c2cc537c7a9.png">

**Additional context**
* rke2 is working with the same settings
  * there is no option for harvester cloud provider in rke1, so this is the only difference I could spot

**Comment by yasker** [comment]
I cannot reproduce the issue in Rancher v2.6.1-rc5 and Harvester v0.3.0-rc1. @slickwarren Can you re-test?

**Comment by slickwarren** [comment]
on 2.6.1-rc5 using harvester 0.3.0-rc1:
* rke1 deployment is working (single node, all roles)
* rke1 deployment dedicated role-per-node -- also working as expected
