### ISSUE TITLE
Token API Endpoint only returning user's Token

### ISSUE THREAD

**Issue by tommyknows** [rancher/rancher#34950]
**Rancher Server Setup**
- Rancher version: v2.6

**Describe the bug**
Rancher has a Token endpoint, which can also be used through the Go client. 
To list tokens, the following request can be made:
```
<rancher-URL>/v3/tokens
```

According to the [API Spec](https://github.com/rancher/api-spec/blob/master/specification.md#filtering), it is possible to filter some results as well. The Go API contains this filter in the list-options, so it seems to be supported.

However, when listing tokens, 
- Only Tokens from the currently authenticated user are returned
- The filters seem to be ignored completely

**To Reproduce**
Go to `<rancher-URL>/v3/tokens`, and check if you can see tokens from other users.

**Result**
Only tokens from the current user are listed, the filters don't work at all.

**Expected Result**
All Tokens are listed (if permissions allow it), and filters work in any case.

**Additional context**
My use case is that I want to create API Tokens for local Users, and to manage them I need to be able to list tokens. 

I would expect a query like this to return all tokens of a specific `user-id`:
```
<rancher-URL>/v3/tokens?userId=<user-id>
```

But the `userId` query is completely ignored and the API just returns all tokens of the current user.

Note that the current user, in my case, is the local administrator, so has full access to everything.

**Comment by vincent99** [comment]
Filters happen at the end and literally _filter_ the responsive records.  They can only remove records that would have been returned, not cause additional ones to be returned.

The token endpoint is one of several that return only info about the person calling, i.e. your tokens.  There is no API to get back other people's, nor create them for others.
