### ISSUE TITLE
Fleet deploys repo to Harvester Clusters

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#34954]
See: https://zube.io/rancher/dashboard-ui/c/4266

When the user selects 'all clusters' in the UI for the target for a git repo, this deploys to Harvester clusters as well as regular k8s clusters.

The UI creates the resource with `spec.targets = [{ clusterSelector: {} }];` - the backend should not deploy to Harvester clusters in this case.

**Comment by yasker** [comment]
@cloudnautique What do you think we should do for v2.6.1? Disable Fleet to Harvester entirely seems to make sense but I am not sure if it's a blocker for v.2.6.1

**Comment by Jono-SUSE-Rancher** [comment]
@yasker as discussed, I moved this to v2.6.2. I will have @SheilaghM sync up with @StrongMonkey and @nickgerace to see what the best course of action is here.

**Comment by StrongMonkey** [comment]
This is more like a UI change. By default UI can create gitrepos that exclude some labels(there should some labels that are unique to harvester cluster).

**Comment by StrongMonkey** [comment]
Fleet doesn't have knowledge around which cluster it should/should not deploy to, it onlys looks for the targets(labels) that user specifies. It wouldn't make sense for fleet by default to exclude some pre-populate sets of labels in the backend.

**Comment by yasker** [comment]
Harvester baremetal clusters have a special `provider` field shows it's Harvester baremetal cluster. See https://github.com/rancher/rancher/issues/34880#issuecomment-927218920 for details.

**Comment by yasker** [comment]
To make it easier to filter the Harvester cluster like what Daishan did in https://github.com/rancher/rancher/issues/34954#issuecomment-931653234 , we will need to automatically add a label to any cluster with `provider=harvester`, so the filter can be used.

**Comment by yasker** [comment]
As discussed with @StrongMonkey , we will add the following logic in the backend:
1. If a cluster with `provider=""`, no change to the label `cluster.harvesterhci.io` regardless it exists or not.
2. If a cluster with `provider="harvester"`, label `cluster.harvesterhci.io` will be added if it doesn't exist.
3. If a cluster with `provider != "" && provider != "harvester"`, label `cluster.harvesterhci.io` will be removed if it exists.

This should also fix the potential inconsistency issue in the UI since filters are done via the label only at the moment.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/pull/35007 proposes to add provider label to v3 cluster. We can change to only rely on `provider.cattle.io` to detect harvester cluster, and also set this label in UI to pin down the cluster in Virtualization Management at first. After cluster is being imported and provider is set to the right value, it will be moved to where it should be.

**Comment by slickwarren** [comment]
tested on v2.6-head (62c101a):
* Harvester clusters no longer show up when creating a git repo for fleet  -- pass
* fleet does not deploy to harvester cluster(s) -- pass
* fleet still deploys to normal k8s clusters -- pass
  * fleet deploys to k8s cluster imported via virtualization management page -- fail (will file new issue for this)
