### ISSUE TITLE
The managed system-upgrade-controller's version need to be updated

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#34964]
**Rancher Server Setup**
- Rancher version: `v2.6.1-rc5`
- Installation option (Docker install/Helm Chart): `v1.21.5+rke2r1`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.21.5+rke2r1`
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

The system-upgrade-controller chart was [bumped to `v0.8.0-rc.1`](https://github.com/rancher/charts/blob/dev-v2.6/charts/system-upgrade-controller/system-upgrade-controller/100.0.1%2Bup0.3.1/values.yaml) and the image tag is also recorded in the [image list.](https://github.com/rancher/rancher/releases/download/v2.6.1-rc5/rancher-images.txt)
The SUC managed chart [version](https://github.com/rancher/rancher/blob/0e49c0fcfbf8a1651dd7a2c6487f8e2001cd91d5/pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagentplan.go#L28) needs to be updated, otherwise, rancher still deploy the old version that is not in the image list.
In Harvester we rely on the image list to collect images for air-gapped environments.

**Comment by deniseschannon** [comment]
This is no longer relevant as we removed teh updated SUC chart. When we reintroduce it, we should be ensuring we update this line.
