### ISSUE TITLE
Promise[t] is not a function

### ISSUE THREAD

**Issue by xinxinzhao1212** [rancher/rancher#34965]
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart):
 Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.2-13+d2965f0db10712
- Cluster Type (Local/Downstream):  aws
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

After i install the rancher 2.5.9 , i can not use the rancher monitor ,Monitoring in Cluster Manager has been deprecated as of Rancher v2.5.0  Check out the updated version of monitoring in Cluster Explorer Apps and Marketplace.
![image](https://user-images.githubusercontent.com/32668515/135227307-1a9cfe04-0cc6-4cca-8a6f-3302a8ef5064.png)

**To Reproduce**
 

**Result**

**Expected Result**

i want monitor the cluster through charts ,for example CPU .and memory 

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by forsake0120** [comment]
Was the problem fixed in 2.6.x?

**Comment by Surphix** [comment]
Experiencing this same issue with 2.6.2, fresh install of rancher on k3s using embeded etcd.

**Comment by scenox** [comment]
Happens also with old Chrome version - updating Chrome fixed it.
