### ISSUE TITLE
Switching Load-balancer from xx containers to "One container per host" does nothing

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#3496]
When trying to update the config of our load balancer from 1 container being deployed to "one container per host instance", it does actually nothing after save. I would expect Rancher to deploy load balancer containers on hosts with none running.

EDIT: Rancher v0.56.1.

**Comment by jloisel** [comment]
It seems like it happens when the underlying linked container is already running multiple instances.

**Comment by vincent99** [comment]
This is a bug in the UI that the option is offered on Load Balancers;  Changing from a fixed scale to global ("Always run one instance...") is not supported by the backend.

**Comment by jloisel** [comment]
:+1:

**Comment by jloisel** [comment]
The documentation should be fixed too:
http://docs.rancher.com/rancher/rancher-ui/applications/stacks/adding-balancers/

**Comment by vincent99** [comment]
**Creating** a load balancer as either a fixed number scale or a global is supported.  **Editing** an existing one to switch from one option to the other is not.

**Comment by jloisel** [comment]
Thanks for the insight i'll re-create it then.

**Comment by tfiduccia** [comment]
Version - 3.20
Verified fixed
