### ISSUE TITLE
AD Authentication Provider form requests Service Account DN but actually requires NETBIOS or UPN

### ISSUE THREAD

**Issue by TimBoothbyViz** [rancher/rancher#34967]
**Rancher Server Setup**
- Rancher version: 2.6

The form for configuring an Active Directory Authentication Provider requires an AD service account and the field is labelled "Service Account Distinguished Name". However specifying the service account as a DN generates an authentication error.

The service account needs to be entered in NETBIOS or UPN format as the docs correctly state, the label on the form is incorrect.

**Comment by Martin-Weiss** [comment]
not stale
