### ISSUE TITLE
401 Unauthorized when trying to view logs / execute shell on a container

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#3497]
Rancher v0.56.1

We have several machines being connected to our rancher-server on Amazon, all running inside the same VPC within the same region and zone. All machines have been setup with CATTLE_AGENT_IP pointing to the private network IP inside the VPC.

For an unknow reason, some hosts does not allow to view container logs or execute shell on them via the UI. Monitoring is not working either. When inspecting the console it shows:

![401-unauthorized](https://cloud.githubusercontent.com/assets/3208716/12755456/c5fa227e-c9cf-11e5-9e86-64ae7719290b.png)

The network connection between the host and Rancher is absolutely fine, amazon security groups have been open to allow any traffic between those machines. We can ping the network agent between each other.

**Comment by vincent99** [comment]
Clock sync between rancher/server and hosts?  The tokens are only good for a few minutes.

**Comment by jloisel** [comment]
Machines clock are all synced with NTP.

**Comment by deniseschannon** [comment]
@jloisel Are you still facing this issue? Is there any kind of similarity between the machines that have no connection versus the ones that do?

**Comment by jloisel** [comment]
I haven't reproduced it yet. Once we got it working by launching other amazon instances, it ended up working. Some amazon machines won't work, while others just work fine. It's difficult to reproduce as the issues appears randomly. All machines configuration were the same: a simple ubuntu 14.04LTS with docker installed (1.9.1, and now 1.10), and NTP server for time sync.

**Comment by deniseschannon** [comment]
@jloisel If you reproduce it again, please re-open.

**Comment by nunofgs** [comment]
This is happening on only one of our hosts right now. I can access the logs/shell on containers running on other hosts.

The offending host just throws a 401 error when establishing the websocket connection.

**Comment by deniseschannon** [comment]
@nunofgs Is the time synced on the host with the rancher server?

**Comment by nunofgs** [comment]
It is. I checked explicitly due to @vincent99's comment.

Only thing I can think of is that we upgraded Rancher to 1.1.0 yesterday.

Any ideas on how to debug the issue?

**Comment by nunofgs** [comment]
@deniseschannon The issue just got weirder. On the same host, we can view logs/execute shell on one container but all of the other containers running on that host throw the 401 unauthorized error.

We've also downgraded the docker daemon on the rancher server from `1.11.2` to `1.10.3`, which didn't fix the issue.

Could it have been a failed migration from `1.1.0-dev5` to `1.1.0`?

**Comment by nunofgs** [comment]
@deniseschannon also, I noticed that the token is a JWT, so here's the contents:

```
{
  "exp": 1467809966,
  "sub": "cattle",
  "logs": {
    "Container": "--redacted--",
    "Lines": 500,
    "Follow": true
  },
  "iss": "http://cattle.io",
  "hostUuid": "--redacted--",
  "iat": 1467809666,
  "kid": "default"
}
```

Here's the date on the host machine where that container was running:

```sh
# date
Wed Jul  6 12:57:01 UTC 2016
# date -d @1467810084
Wed Jul  6 13:01:24 UTC 2016
```

I think we can rule out any date or timezone issues as the JWT was indeed valid.

**Comment by nunofgs** [comment]
Fixed it! 😄 

When running `docker logs -f rancher-agent` on the offending host we noticed:

```
time="2016-07-06T14:39:36Z" level="info" msg="Connecting to proxy." url="ws://rancher.uphold.internal:8080/v1/connectbackend?token=<my-jwt-token>" 
time="2016-07-06T14:39:36Z" level="fatal" msg="Failed to connect to proxy." error="dial tcp 172.19.48.41:8080: connection refused"
```

Turns out we had changed the port where the Rancher server was running a few days ago. 😌

**Comment by deniseschannon** [comment]
Great! I'm glad you were able to resolve it.
