### ISSUE TITLE
While Importing Cluster: Cluster stucks  in Wait Check-In state.

### ISSUE THREAD

**Issue by PrateekKhatri** [rancher/rancher#34973]
Hi Team,

I have imported AWS EKS Cluster to rancher 2.6.0. When I see the details I found that the Wait Check-In state occurs. Please find the screenshot below for reference.

![image](https://user-images.githubusercontent.com/70568716/135309796-ef371dff-6274-4b0f-97cd-f96776856ec2.png)

**Comment by xuanyuanaosheng** [comment]
The same issue: https://github.com/rancher/rancher/issues/34719

**Comment by xuanyuanaosheng** [comment]
My problem is: 

1.  The error info 
![image](https://user-images.githubusercontent.com/4197714/142848563-5587ec61-83f3-4123-bcdc-1fad1b11ef00.png)

2.   The detail error is :
![image](https://user-images.githubusercontent.com/4197714/142847857-f8bca584-a25b-4bea-b738-96cf98b9046f.png)

**Comment by scila1996** [comment]
+1 same issue !
