### ISSUE TITLE
[2.5] Update vSphere CPI

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#34977]
Rancher vSphere CPI needs to be updated to support the new kubernetes versions.

**Comment by PennyScissors** [comment]
### What changed
The CPI upstream manifests are divided such that there is a different one for each k8s release, but the only significant difference is one image tag named after the k8s version it supports. The CPI chart has been updated to the latest v1.21.0 upstream, and to account for the k8s compatibility we added functionality to allow the user to specify the k8s version of the cluster or have Helm find it for the user in order to for the chart to use the image corresponding to the k8s cluster version.

### What needs to be tested
1. The chart deploys and work on each k8s version we support and a providerID is set.
2. Upgrading from previous CPI chart is successful.
3. The correct image tag is used for each k8s version we support. For example, in a 1.21.5 cluster the image should be `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.21.0`. Currently, k8s 1.18 to 1.21 is supported, and if you try to deploy it in a cluster of an unsupported k8s version the following error should show up `unsupported Kubernetes version: <unsupported-version> (supported versions: <supported-versions>)`.

**Comment by slickwarren** [comment]
We have an issue in our vsphere environment/setup that is blocking QA from full validation of this ticket; currently we cannot attach a volume to a workload.

**Comment by slickwarren** [comment]
**Test Environment**
- Rancher Version:v2.5-head (ce52c78)
- Installation option (Docker install/Helm Chart):docker 

**Information about the Cluster**
- Kubernetes version:1.19 was primarily used. Some upgrade tests, 1.19 -> 1.20
- Cluster Type(s) tested on (Local/Downstream):downstream

**Overview of Validation**

The following were done on multinode (1cp, 1etcd, 3worker) clusters and was tested with the latest csi version/ticket (v2.3.0)
* on 2.5.9, install cpi:1.0.000 and csi:2.1.0. Upgrade rancher, then upgrade the charts to 1.0.100 and 2.3.0 respectively -- **pass**
* on 2.5.9, configure in-tree provider on a cluster. upgrade rancher, migrate to out-of-tree using the latest charts -- **pass**
  * upgrading the k8s version is causing an issue (**fail**), which is not a regression as it is reproducible on 2.5.9, so I've [filed a separate ticket for this](https://github.com/rancher/rancher/issues/35102)
* edit the values.yaml for cpi chart, and override the version installed for the cluster -- **pass**
* Upgrading from Rancher v2.5.9 with the existing chart installed then upgrade chart to new one -- **pass**
* enable volume resizing on the csi chart. provision a volume, and resize it -- pass
  * ensure online resizing is enabled; provision a workload with a bound volume; resize the volume -- **fail** 
    * we got a generic error, suggesting that our testing environment may have some versioning issue (ignoring this failure for now since volumes not attached to a workload is working, which is [in the same set of documentation in csi](https://vsphere-csi-driver.sigs.k8s.io/features/volume_expansion.html))
