### ISSUE TITLE
Rancher stuck in Fatal Error (crashing) loop after a harvester cluster is imported  `[FATAL] k3s exited with: exit status 1`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34980]
**Rancher Server Setup**
- Rancher version:v2.5.9
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version: -> harvester version: master-b7b757e9-head
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): imported

**Describe the bug**

after importing a harvester cluster on v2.5.9, rancher gets into a panic loop 

**To Reproduce**
 
* deploy rancher v2.5.9
* import a harvester setup
* add some other cluster types (i.e. linode/digital ocean node driver)

**Result**
rancher will panic periodically when trying to create new clusters after the harvester setup has been imported.  

**Expected Result**

* though harvester is not supported on v2.6.0 and below, rancher should still handle the cluster and be able to continue to operate

**Screenshots**

**Additional context**
* found when testing upgrade test cases for harvester integration into rancher
* harvester imported cluster health checks fail shortly after the import
* logs can be provided upon request
* rancher seems to continue to be in this loop/unrecoverable state even after removing the imported cluster.

**Comment by sowmyav27** [comment]
Harvester is supported _only_ on Rancher 2.6.1+

**Comment by slickwarren** [comment]
since this is known to not be supported, I'm closing this issue.
