### ISSUE TITLE
task: Harvester v0.3.0 related release note for Rancher v2.6.1

### ISSUE THREAD

**Issue by yasker** [rancher/rancher#34987]
- [ ] Harvester v0.3.0 doesn't support Air Gap Environment installation.
    - Due to https://github.com/rancher/rancher/issues/34908 , not sure if we need to mention this.
- [ ] Harvester v0.3.0 doesn't support upgrade from v0.2.0, nor upgrade to future v1.0.0.

**Comment by Jono-SUSE-Rancher** [comment]
Hey @jtravee - I think @yasker meant to create this in the release-notes repo, but he dropped it in rancher instead. Is it okay if we close this out? Have you captured what he was trying to suggest?

**Comment by jtravee** [comment]
Hi @Jono-SUSE-Rancher. Yes we can close this out; I added this info to both the RN and docs.
