### ISSUE TITLE
`rancher/machine` not found in `rancher-images.txt`

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34986]
Image `rancher/machine` is not found in `rancher-images.txt` for Rancher `v2.6.1-rc7`.

This image was built-in for v2.5.x. Provisioning v2 now uses that machine image, so it is likely missing from the file as a result of never previously needing to be there.

Relevant issue: https://github.com/rancher/rancher/issues/32403

**Comment by thedadams** [comment]
@nickgerace I moved this to "Waiting for Rancher RC" so we could ensure that the machine image is in the images.txt file.

**Comment by sowmyav27** [comment]
`rancher/machine:v0.15.0-rancher70` is available in rancher-images.txt file in `2.6.1-rc9`
