### ISSUE TITLE
[Backport 2.5] Unable to update istio configuration in air-gapped environment in Rancher v2.5.x

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#35009]
https://github.com/rancher/rancher/issues/30842

**Comment by brendarearden** [comment]
This fix is planned to be added to the 1.9.8 rancher-istio chart as part of this backport.

**Comment by thedadams** [comment]
Ready to test in v2.5.10-rc3

**Comment by anupama2501** [comment]
Re-opening the issue as I'm seeing the following errors when upgrading istio from `v1.9.600` to `v1.9.801`

- Created a rancher airgapped server on v2.5.10-rc3 
- On the rancher server created a custom cluster with private registry enabled [3 worker nodes, 3 etcd, 1 cp]
- Pull all the required images into the private registry.
- Install istio v1.9.600 by enabling jaeger.
- Verified all the workloads of istio are installed and active from system project, kiali and jaeger are accessible.
- Upgrade the istio version to `v1.9.801` by setting the flag `installer.releaseMirror.enabled=true` [make sure the images are present in the private registry] and the installation fails with the errors:

```
2021-10-08T23:29:14.730951Z info Error: failed to generate Istio configs from file [/app/istio-base.yaml] for the current version: 1.9.6, error: Get "https://github.com/istio/istio/releases/download/1.9.6/istio-1.9.6-osx.tar.gz": dial tcp 140.82.114.3:443: i/o timeout
--
Fri, Oct 8 2021 4:29:14 pm |  
Fri, Oct 8 2021 4:29:14 pm | Error: failed to generate Istio configs from file [/app/istio-base.yaml] for the current version: 1.9.6, error: Get "https://github.com/istio/istio/releases/download/1.9.6/istio-1.9.6-osx.tar.gz": dial tcp <ip>:443: i/o timeout

```

- If we install istio on v1.9.801, it goes through and all workloads come up active.

**Comment by brendarearden** [comment]
Available to test in rancher/rancher v2.5.12-rc1

**Comment by anupama2501** [comment]
Verified on 2.5.12-rc1

Istio version 1.10.400

- Installed istio chart on version 1.10.400 by disbling jaeger
- Updated the same version by enabling jaeger and setting the flag installer.releaseMirror.enabled=true
- No errors were seen and the installation went through without any error.

**Comment by anupama2501** [comment]
Verified on 2.5.12-rc1

Istio version 1.9.8 --> 1.10.4

- Installed istio chart on version 1.9.800 
- Upgraded the version of istio to 1.10.4 and setting the flag installer.releaseMirror.enabled=true
- No errors were seen and the installation went through without any error.
