### ISSUE TITLE
[Istio v1 kiali:v1.17] refreshing kiali page results in 401 status

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35017]
**Rancher Server Setup**
- Rancher version: v2.5-head `5b2469f3c9`
- Installation option (Docker install/Helm Chart): Helm chart/docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 `v1.20.11`
- Proxy/Cert Details: selfsigned

**Information about the Cluster**
- Kubernetes version: `v1.20.11`
- Cluster Type (Local/Downstream): Downstream custom cluster [oracle_linux_8.4_docker_20.10_packer] and ubuntu node driver cluster
- Istio Version: `v1.5.901`

**Describe the bug**
kiali works fine on a cluster --> tools --> istio --> kiali if we do not refresh the kiali UI. but if the kiali UI is refreshed, the page goes down and a 401 response is seen in the API requests tab

**To Reproduce**
1. Created a downstream custom oracle cluster on an HA rancher server with 3 worker, 2 cp, 3 etcd as a standard user
2. Installed istio v1 version `1.5.901` version in the downstream cluster
3. Verified all the workloads were deployed.
4. From cluster --> tools --> istio v1 --> click on kiali and let kiali load completely
5. Refresh the page

**Result**
Upon a refresh, the following response is seen in the console logs 
```
https://<redacted>/k8s/clusters/api/v1/namespaces/istio-system/services/http:kiali:20001/proxy/console/graph/namespaces/?edges=noEdgeLabels&graphType=versionedApp&namespaces=istio-ns&unusedNodes=false&injectServiceNodes=true&duration=60&refresh=15000&layout=dagre


Failed to load resource: the server responded with a status of 401 ()

```

**Expected Result**
Refreshing the UI should not result in the 401 error. 

**Additional context**
Installing istio v1 1.5.901 with ubuntu node driver downstream cluster throw the below error when we refresh the kiali UI:
```
GET https://<redacted>/k8s/clusters/api/v1/namespaces/istio-system/services/http:kiali:20001/proxy/console/overview?duration=60&refresh=15000 500 (Internal Server Error)

clusters.management.cattle.io "api" not found
```

Similar issue is seen on v2 istio charts as well: https://github.com/rancher/rancher/issues/33739

**Comment by cbron** [comment]
Moving to 2.5.11

**Comment by deniseschannon** [comment]
As Istio v1 is deprecated and users are encouraged to start using Istio v2 as well as the fact that this version of Istio is EOL by Istio, we won't be making a fix for this.
