### ISSUE TITLE
Deleting a cluster that provisioned successfully but is in error state doesn't remove management cluster

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#35018]
**Rancher Server Setup**
- Rancher version: 2.6.1-rc10

**Information about the Cluster**
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Digital Ocean

**Describe the bug**

If a cluster provisioned from Rancher is successful, but goes into an error state for some reason, then deleting it will successfully delete the provisioning cluster object but not the management cluster object.

**To Reproduce**
 
1. Provision a Digital Ocean cluster with one machine pool, put a '.' in the machine pool name (like `harvester-v.0.3.0-rc1-creds-pool1`)
2. Wait for provisioning to complete and an error related to `namespace`s will appear in the UI.
3. Delete the cluster.

**Result**
The cluster will be removed from the "Cluster Management" page but not the "Home" page.

**Expected Result**
The cluster should disappear from both pages.

**Comment by norcis** [comment]
Still got this problem in 2.6.2. Cluster does not disappear from home page, status Unavailable.
Any workaround how to remove it?

**Comment by dnoland1** [comment]
For a workaround, try removing your finalizers on the cluster:
```
kubectl patch clusters.management.cattle.io ${CLUSTER_ID} -p '{"metadata":{"finalizers":null}}' --type=merge
```
set CLUSTER_ID to the id of your cluster (c-xxxxxx)
