### ISSUE TITLE
Longhorn Rancher 2.6

### ISSUE THREAD

**Issue by dispeakble** [rancher/rancher#35015]
**Rancher Server Setup**
- Rancher version:v2.6.0
- Installation option (Docker install/Helm Chart):Docker=20.10.8
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version:
- Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3+k3s1", GitCommit:"1d1f220fbee9cdeb5416b76b707dde8c231121f2", GitTreeState:"clean", BuildDate:"2021-07-22T20:52:14Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

- Cluster Type (Local/Downstream): Local
- Hosted/Infrastructure Provider): Custom

**Describe the bug**
>Run rancher 2.6 as a docker container
>Get good vibes about the new 2.6 version
>Add old stuff to it
>Can't
>Longhorn was my storage class thingy
>Bang head
>Pod: longhorn-driver-deployer-5f47f8c9c-pgq6n Init:0/1
>Namespace: longhorn-system; Age: 3.9 hours; containers with incomplete status: [wait-longhorn-manager]
>apt-get update
>apt-get install -y open-iscsi

Do I need to install longhorn on a VM or something? in rancher 2.4.* longhorn worked on prem

let's try with helm:

>helm repo add longhorn https://charts.longhorn.io
>helm repo update
>helm install longhorn longhorn/longhorn --namespace longhorn-system

2021/10/01 11:55:03 proto: duplicate proto type registered: VersionResponse
--
Fri, Oct 1 2021 12:55:03 pm | time="2021-10-01T11:55:03Z" level=error msg="Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host"
Fri, Oct 1 2021 12:55:03 pm | time="2021-10-01T11:55:03Z" level=fatal msg="Error starting manager: Environment check failed: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm --version], output , stderr, nsenter: failed to execute iscsiadm: No such file or directory\n, error exit status 127"

**To Reproduce**
run rancher 2.6 from a docker container
try to install longhorn however you can.

**Result**
Longhorn cannot be installed out of the box and neither with updating and installing exceptional packages

**Expected Result**
Please allow to install the longhorn default application in another project in the longhorn-system namespace

**Setup**
OS: Ubuntu 18.04.5 LTS
CPU: Intel® Core™ i7-6700K CPU @ 4.00GHz × 8 
RAM: 15.6 GiB

sudo service iscsid status
● iscsid.service - iSCSI initiator daemon (iscsid)
   Loaded: loaded (/lib/systemd/system/iscsid.service; disabled; vendor preset: enabled)
   Active: active (running)
     Docs: man:iscsid(8)
  Process: 3208 ExecStart=/sbin/iscsid (code=exited, status=0/SUCCESS)
  Process: 3196 ExecStartPre=/lib/open-iscsi/startup-checks.sh (code=exited, status=0/SUCCESS)
 Main PID: 3216 (iscsid)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/iscsid.service
           ├─3213 /sbin/iscsid
           └─3216 /sbin/iscsid

Oct 02 09:43:14 cms-pc systemd[1]: Starting iSCSI initiator daemon (iscsid)...
Oct 02 09:43:14 cms-pc iscsid[3208]: iSCSI logger with pid=3213 started!
Oct 02 09:43:14 cms-pc systemd[1]: iscsid.service: Failed to parse PID from file /run/iscsid.pid: Invalid
Oct 02 09:43:14 cms-pc systemd[1]: Started iSCSI initiator daemon (iscsid).
Oct 02 09:43:15 cms-pc iscsid[3213]: iSCSI daemon with pid=3216 started!

from https://github.com/longhorn/longhorn/blob/v1.2.0/scripts/environment_check.sh

daemonset.apps/longhorn-environment-check created
waiting for pods to become ready (0/1)
waiting for pods to become ready (0/1)
waiting for pods to become ready (0/1)
waiting for pods to become ready (0/1)
waiting for pods to become ready (0/1)
waiting for pods to become ready (0/1)
all pods ready (1/1)

  MountPropagation is enabled!

cleaning up...
daemonset.apps "longhorn-environment-check" deleted
clean up complete

**Comment by i404788** [comment]
Ran into the same issue, it seems to use the storage of the docker container. 
You can resolve it (kind of) by adding `open-iscsi` to the container:
```sh
docker exec -it $CONTAINER_ID /bin/sh

$ zypper install open-iscsi jq
$ iscsid
```

Note that you need to pass through `/var/lib/longhorn' if you want persistent storage.

**Comment by dispeakble** [comment]
@i404788 thank you for your reply. can you tell me in which container I must install open-iscsi? I have tried to install it in the rancher container but the longhorn app isn't installing. also for the volume can this be done on a windows machine or is it strictly meant for a linux machine?
