### ISSUE TITLE
Helm Chart is broken

### ISSUE THREAD

**Issue by Samaneh1986** [rancher/rancher#35011]
In Catalog page, we get this error (for all 3 charts):
Clone failed: Cloning into 'management-state/catalog-cache/f0157389f88ff77e66750b762de6b4960fddfc49445b5f4787dc1a6b1d492c6c'... fatal: unable to access 'https://git.rancher.io/system-charts/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none : exit status 128

**Rancher Server Setup**
- Rancher version: 2.4.12
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): K3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

**To Reproduce**
 

**Result**

**Expected Result**

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by vincent99** [comment]
The root certificate for LetsEncrypt expired and has broken many things around the internet today.  The git server has been updated with a new cert from a different chain and root as of a couple hours ago.
