### ISSUE TITLE
[2.5.8] Issue pulling catalog due to expired CA.

### ISSUE THREAD

**Issue by Lebvanih** [rancher/rancher#35016]
Rancher Server Setup

Rancher version: v2.5.8
Installation option (Docker install/Helm Chart): Helm
If Helm Chart, Kubernetes Info:
Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE1
Information about the Cluster

Kubernetes version: v1.20.9
Cluster Type (Local/Downstream): Local

**Describe the bug**
As mentioned in ticket #35011 and #35008, the DST Root CA X3 expired. This is thus blocking all the pull of catalog if the remote is using a Let's Encrypt Certificate.

As we had the issue in some of our container/pods, we tried the same workaround we already had to use, but this time directly in the rancher images, and it seems to work to fix the issue.

Initial error:
2021/10/01 16:36:50 [ERROR] error syncing '<catalog_name>': handler catalog: Update failed: fatal: unable to access 'https://***:***@gitlab.rd.***/<catalog_name>/charts.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

What we did was:
- Find the pod of rancher that was trying to pull the images
- apt-get update
- apt-get install ca-certificates
The change performed  from the apt logs:
`Unpacking ca-certificates (20210119~18.04.2) over (20210119~18.04.1) ...`

After this, it worked again as before and we are able to pull again the images.

I checked the image of rancher v2.5.8 and v2.5.9 they both use 20210119~18.04.1 by default.

Would it be possible, if you confirm that it also fixes the issue if you can reproduce on v2.5.9, to update this package in the image for the next version at least so we are not forced to manually update in the running container directly?

Kr,

**Comment by cambierr** [comment]
up ?
