### ISSUE TITLE
Reclaiming disk space by running optimize for mysql DB 

### ISSUE THREAD

**Issue by mishak87** [rancher/rancher#3501]
Rancher likes to eat a lot of disk space.
I don't know if anyone is working on reducing image sizes and disk usage but I would like to help!
##### Issues
- Rancher images are quite big
  - rancher/agent-instance 0.6.0 635MB  
    Some improvements have been made in 0.7 and 0.8.  
    Major slimming has been suggested in [August 2015](https://github.com/rancher/agent-instance/pull/7).
  - rancher/agent 0.8.2 365MB  
    When adding host agent is launched several times and containers are not removed.
  - on upgrade old images are not cleaned up cca 500MB
- MySQL
  - Cattle process tables (InnoDB) are not compacted regularly and will eat gigabytes of space
    
    ``` sql
    optimize table process_execution;
    optimize table process_instance;
    ```
  - ~~Binary logs eat about 100MB each hour with two day retention that makes cca 2.6GB~~
    This was caused by flapping service I ignored for a week.
- Cattle
  - Cattle stores Java profiling information in hstor file cca 500MB
  - Cattle logs debug information a lot cca 300MB
##### How I got there

I have been using Rancher for CI/CD environment and testing for last two months. Issue I always encounter is not enough disk space. Rancher runs on small VPS with 10GB SSD. Today I did cleanup after two months and two upgrades 0.46.\* :arrow_right: 0.51.0 :arrow_right: 0.56.1.
By compacting two tables, keeping only day of binary logs and cleaning debug information I reclaimed about 4.4GB of space. To manage single host in Rancher around 1GB of disk space is needed just for 'rancher/*' containers and images.

**Comment by sshipway** [comment]
For comparison...

I'm running using 10GB CoreOS Hosts; I am using a cleanup container to autodelete any container images that are not needed -- I have a Catalogue with the definition here: https://github.com/sshipway/rancher-catalogue.git

Our Rancher host is on a 32G CoreOS .  Rancher is using 6G, including database backup archive (1G).  I have a copy of the cleanup container running here as well, so that I know old Rancher container versions will be removed automatically.

**Comment by deniseschannon** [comment]
If the cleanup for process_instance is not aggressive enough, you can always update the settings in the API. 

http://docs.rancher.com/rancher/faqs/troubleshooting/#rancher-server-database-is-growing-too-quickly

Also, we are including the cleanup of process_execution in the next release, which will also have the option to make the settings more aggressive.  https://github.com/rancher/rancher/issues/2381

We're also looking to not logging as much into process execution. https://github.com/rancher/cattle/pull/1342

**Comment by mishak87** [comment]
@deniseschannon Thank you!
After upgrade I missed the information about reduction of purge time and mine was 90 days. So first optimize was necessary just because there was just too much deleted data.
But disk consumption on VPS with only Rancher is steady 100MB per hour as it was before.

Cattle tables can grow over time for example when service is flopping forcing InnoDB to write and delete lot of rows without reclaiming space of deleted rows. So running [optimize](http://dev.mysql.com/doc/refman/5.5/en/optimize-table.html) when table grows relatively fast could be beneficial.

**Comment by mishak87** [comment]
Update: table `container_event` reduced from 668MB to 12MB by optimizing. (I'm still using 0.56.1) 
```
optimize table container_event;
```

**Comment by will-chan** [comment]
Closed due to inactivity.
