### ISSUE TITLE
use rancherv2.6.0 import cluster v1.22.2 error

### ISSUE THREAD

**Issue by PayneRose** [rancher/rancher#35024]
I use rancher import my new cluster(version=v1.22.2), But it did not run, and error:  Get "https://10.43.231.26/k8s/clusters/c-m-ccdvbmxb/version?timeout=15s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

this is my cluster settings:
kubeadm init --control-plane-endpoint "192.1.0.4:16443" --kubernetes-version "v1.22.2" --pod-network-cidr "22.0.0.0/8" --service-cidr "172.22.0.0/16" --token "abcdef.0123456789abcdef" --token-ttl "0" --image-repository registry.aliyuncs.com/google_containers --upload-certs

my rancher version is v2.6.0, ip is 192.1.0.12

running in kubectl command:
curl --insecure -sfL https://192.1.0.12/v3/import/rkgrtknnq7slwsj8sxz6qrk5spw4qbw8dmtlmwscspv9pnn7v85jnj_c-m-ccdvbmxb.yaml | kubectl apply -f -

and then rancher call error in Continuous Delivery:
Get "https://10.43.231.26/k8s/clusters/c-m-ccdvbmxb/version?timeout=15s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
![image](https://user-images.githubusercontent.com/28387352/135820264-61ba0197-4171-4bb7-926d-0398631a86b8.png)
![image](https://user-images.githubusercontent.com/28387352/135820321-31d9d74f-2b15-4439-9b3b-f10b85c3cfe7.png)

not ready
![image](https://user-images.githubusercontent.com/28387352/135821946-6b17630e-6cf9-4b2b-ae04-a7d7506db74a.png)

**Comment by modzilla99** [comment]
Yeah it seems that Kubernetes >v1.22.0 is not supported yet. I tried to install rancher to a newly created cluster and that did not work out great... 
I tried by removing the version check in the chart and setting the image to a brand new master image but stll. The pods never came up and were stuck at creating the crd store thing.
I hope support's comming soon :/
