### ISSUE TITLE
Rancher versioning scheme seems to be incompatible with the helm kubeVersion logic check.

### ISSUE THREAD

**Issue by Giancarlo1974** [rancher/rancher#35027]
- Rancher version: 2.5.9
RKE1

**Information about the Cluster**
- Kubernetes version: v120.11-rancher1-1
- Cluster Type Downstream:
Imported on Centos 7 --> v120.11-rancher1-1

**Describe the bug**
Unable to update kubernetes-dashboard to version 5.0.0
Latest working version: 4.6.0

For more details, please read these issues:

https://github.com/kubernetes/dashboard/issues/6501

**Comment by Shaked** [comment]
Same happens with rancher server v2.5.8 and latest nginx ingress (4.0.9)
