### ISSUE TITLE
Rancher does not trust letsencrypt certificate

### ISSUE THREAD

**Issue by angeloudy** [rancher/rancher#35036]
After letsencrypt DST ROOT X3 expired on 30 Sep 2021, my rancher environment cannot refresh catalogs that are using letsencrypt certificates.

error ```

  | Update failed: fatal: unable to access  'https://rancher:***@gitlab.xxx.xxx/odyssey-catalogs/helm/my-charts.git/':  server certificate verification failed. CAfile:  /etc/ssl/certs/ca-certificates.crt CRLfile: none : exit status 128
-- | --
```

rancher version: 2.5.2

**Comment by angeloudy** [comment]
Fixed it by running the following command in rancher pod.
```
sed -i '/^mozilla\/DST_Root_CA_X3/s/^/!/' /etc/ca-certificates.conf && update-ca-certificates -f
```

**Comment by junkiebev** [comment]
For what it's worth, I believe you could update open the SSL to accomplish the same - I believe that the newer versions support multiple paths to root signing certificates￼.

**Comment by Lebvanih** [comment]
You can also do it like I mentioned in this ticket last week: #35016. Probably cleaner like that.

**Comment by pironic** [comment]
i know 1.6 is no longer supported but is there any knowledge about which infrastructure containers need the new certificate that is preventing the registry pulls? :(
