### ISSUE TITLE
[2.5] Update fluentbit to the latest version

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#35058]
We had to hold off on an a fluentbit update due to this issue.  Once a fix is merge we should try to upgrade to the newer version.

https://github.com/fluent/fluent-bit/issues/4042#issuecomment-924190083

**Comment by paynejacob** [comment]
### Root cause
 Due to some other changes we attempted to upgrade fluentbit but found it has a dns bug.
 
### What was fixed, or what changes have occurred
We updated to a version of fluentbit that has a fix for the linked bug
 
### Areas or cases that should be tested
 Ensure that when rancher logging is installed any fluentbit images are > 1.8.8
 
### What areas could experience regressions?
Any fluentbit pod could be affected if it is not running the correct version (excluding windows)

### Are the repro steps accurate/minimal?
-

**Comment by ronhorton** [comment]
**PASS** Verified in `2.5-head Commit ID 9dab145`

1. Installed logging v2
2. checked yaml file for fluentbit images - all images 1.8.8 
<img width="501" alt="Screen Shot 2021-12-21 at 4 41 39 PM" src="https://user-images.githubusercontent.com/89212856/147001370-a7baaf2d-0abd-4fcc-9935-dbabaf4b827d.png">
