### ISSUE TITLE
Enabling then disabling a node driver causes v2 provisioning to be extremely slow

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#35052]
**Rancher Server Setup**
- Rancher version: v2.6-head
- Installation option (Docker install/Helm Chart): Docker install
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.19.11+k3s1
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): 

**Describe the bug*
Disabling node drivers causes v2 provisioning (with any enabled node driver) to be extremely slow and error prone.

**To Reproduce**
1. Enable a node driver (Openstack for example)
2. Disable the node driver
3. Provision an RKE2 cluster in Digital Ocean cluster with one node.

**Result**
The DO cluster will eventually provision, but it will take a very long time (not worth waiting). The UI will seem to not show any statuses and the cluster will stay in a Pending state for a long time.

**Expected Result**
The cluster should provision as usual.

**Screenshots**

**Additional context**
There will likely be logs in Rancher related to "the server could not find the requested resource (openstackconfigs.meta.k8s.io)"

**Comment by ronhorton** [comment]
reproduced behavior in 	v2.6-9801a059cf239934f5093ba8e3d15bd3fd9460d5-head
