### ISSUE TITLE
[question] load balancer http -> https redirect

### ISSUE THREAD

**Issue by defunctzombie** [rancher/rancher#3505]
Apologies if I missed this in the documentation or other location but I am wondering if the load balancer service has the ability to redirect requests on port 80 (unsecured) to port 443 (secured)?

I have a load balancer configured via the Rancher interface to listen on 80 and 443 (with SSL enabled on 443).

**Comment by defunctzombie** [comment]
Ok, I see from other issues and forum posts that this is currently not possible but that it may be possible in the future or even a built-in setting (since it is a common thing to do).

**Comment by RVN-BR** [comment]
The Rancher LB doesnt let you add anything to the HAProxy.cfg except in the Defaults or Global sections...  

For this I think the best way is to add a frontend with the following as an example:
```
frontend http-frontend
    bind *:80
    redirect scheme https if !{ ssl_fc }
```

In this case all traffic to the host on port 80 would be redirected to https...  

This however, isnt supported as the Frontend section of haproxy.cfg cant be changed/added, as its not inside the sections open to custom options...

Maybe it would be ideal if the entire haproxy.cfg could be edited to have manual insertions? Or at least a way of adding "root" blocks? (with the understanding that they could be static, etc, etc)  I think it would be more worthwhile than having to implement a bunch of different HAProxy features in the UI...  Of course this depends on how the haproxy cfg file is generated, etc... but i suppose it should be doable?

**Comment by vincent99** [comment]
The ability to customize the other sections is coming eventually.. In the meantime for this use it's simple enough to run a tiny container with a couple line program in any language that returns 302s.  Or the stock nginx/haproxy images and a config file.

**Comment by tombusby** [comment]
@vincent99 Do you have an idea what the timescale for this is? It's something that we really need to be able to do. If it's coming relatively soon I'll hold off on writing an ugly hack in the server-side code to do it.

**Comment by vincent99** [comment]
The developer who is working on it is out this week but was now actively working on it last I heard.. https://github.com/rancher/rancher/issues/2179 .  I still claim it's easy enough to run a tiny container that does nothing but redirect...

**Comment by blackjid** [comment]
I've been runing redirection with a tiny service using this image `jamessharp/docker-nginx-https-redirect`
Just run a container with this image and point the lb port 80 to the redirect service.

**Comment by defunctzombie** [comment]
@vincent99 Agreed, I have been using redirect containers. I think the issue here is not ease but more of discovery and expectation. A user thinks, oh I have a load balancer and in the past when I had load balancers I did this with my load balancer so I look for a way to make the new load balancer do that so this question keeps coming up.

**Comment by tombusby** [comment]
It just seems a bit unwieldy to it that when, if we had more access to the HAProxy config, we could do it in approx one line of config.

**Comment by tgjamin** [comment]
Any progress on this?
Being able to edit the haproxy config (or supply a custom one) would be very useful for this feature.

**Comment by vincent99** [comment]
The new balancer API should be included in `1.2.0-pre3`.

**Comment by RVN-BR** [comment]
Great!

Is there a way to add a custom backend/frontend?  Are we able to launch differnt loadbalancers with different haproxy configs?

i.e. one loadbalancer running only on certain machines with a specific config?

I have been using the tutum haproxy image to test our docker stack outside of rancher (on dev machines as well as while we were waiting for build args to be supported in RCompose - I understand that is also in 1.2-pre), and that image doesnt allow much config either afaik (its great for linking containers, even has a force_ssl option, etc) but it doesnt let you add an arbitrary IP as a backend for proxy which is somethign I'd be interested in...

(just to situate, our use case is hybrid cloud, where some services are only available to one datacenter and dont have an externally accessible ip, so I want the haproxy service to receive a request on rancher internal network - which can be coming from any container on any host on any location, and proxy that to this external service "locally"...  The containers already access the IP, so it is just a matter of adding a proxy.  Initial manual testing worked, but having it within the official LB or a standard LB image would be nicer... nginx was discarded here as its mostly TCP not http...)

**Comment by c58** [comment]
Found workaround for rancher 1.2
1. Add selector rule in your balancer with protocol "HTTP", request host "*", port "80" and target "foo=bar" (actually any target that won't select any service)
2. In "Custom haproxy.cfg" add this ```
frontend http-frontend
    bind *:80
    mode http
    redirect scheme https if !{ ssl_fc }
```
3. Save balancer configs. All http requests will be redirected to https ;)

**Comment by defunctzombie** [comment]
Reasonable to add this workaround to the docs?

@deniseschannon @vincent99

**Comment by SamDelgado** [comment]
The comment from @c58 allowed me to get this working properly, but I did want to add that in order to get this to work I had to hit the tiny "add custom backend names" button in the UI, and then give the added selector rule the backend name of "http-frontend". I originally thought "http-frontend" was the default backend name given by Rancher so didn't think I had to add it manually.

**Comment by InAnimaTe** [comment]
It'd be nice if any of the following were offered to make this process more intuitive and service specific:

1. A tickbox for HTTPS/TLS rules to enable redirection.
2. A label I can set on said service telling the LB to enable redirection.

**Comment by tcdev0** [comment]
solution from @c58 only works for me with a small modification. (tested with rancher v1.3.0)

```
# Custom haproxy.cfg
frontend http-frontend
    bind *:80
    mode http
    redirect scheme https code 301 if !{ ssl_fc }
```

**Comment by rsilva4** [comment]
@c58 solution works like a charm but unfortunately the target rule seems to magically disappear after additional upgrading of the balancer.

**Comment by InAnimaTe** [comment]
@tcdev0 

Thanks for the tip. 1.3.0 does require this format..

**Comment by vincent99** [comment]
I would suggest 302 instead, it's basically impossible to fix clients that received a 301 if you get the redirect wrong or no longer want it.

**Comment by Fraeco** [comment]
Hi

I'm trying to accomplish the same thing as you guys. I've got 3 web apps that are responding on port 80. I'm using SSL termination in the load balancer with certificates generated by Let's-Encrypt. 

I can't however seem to get the redirection to work. As posted above I've added the following to the Custom haproxy.cfg config and created a rule "public http * 80 | foo=bar 80"
`# Custom haproxy.cfg
frontend http-frontend
    bind *:80
    mode http
    redirect scheme https code 301 if !{ ssl_fc }`

However, this doesn't seem to redirect, when I go to the non SSL address of the site I'm just greeted with the default 503.

**Comment by SamDelgado** [comment]
@fraeco, make sure your name the rule "http-frontend" to match its name in the custom config. Read my comment above about it if you are still confused.

**Comment by Fraeco** [comment]
@SamDelgado Thanks for getting back to me. I'm new with the HAProxy and don't know what you mean by naming the rule. Is this to be done in the "backend" field?

**Comment by SamDelgado** [comment]
Yep! Try it out and let us know own if you are still having problems.

**Comment by Fraeco** [comment]
@SamDelgado 
Thanks for getting back to me. I think it is working as intended now, I do however have the impression that the first visit still fails to redirect. When I open a browser that has never visited the domain I'm presented with the 503. When I forcefully go to http://domain.com on a subsequent try on that browser it redirects. 

I added a screenshot of the loadbalancer setup for brevity.

![image](https://cloud.githubusercontent.com/assets/18047078/22173825/4036910c-dfce-11e6-9660-ea3a7c019a06.png)

**Comment by dalareo** [comment]
I have the same issue as @Fraeco !

**Comment by thosvesta** [comment]
I'm also experiencing the same issue

**Comment by thosvesta** [comment]
I just came across a beautiful article on how to do this with clear steps. 

> `https://blog.uilicious.com/setting-up-your-monster-load-balancers-in-rancher-for-http-s-e61d778065b8#.dj2xbfk9g`

![image](https://cloud.githubusercontent.com/assets/18680544/22738708/791b0cbe-ee2e-11e6-9ccb-aa0fff6ed77f.png)

**Comment by dalareo** [comment]
I think this solution is far more complex @thosvesta, it seems it is setting two rules for every service (one with HTTP and another with HTTPS). The idea is to set a rule that redrects all insecure traffic to HTTPS

**Comment by J-Ha** [comment]
this should solve the 503 http problem, withot direct redirect:

```
# Custom haproxy.cfg
frontend 80
redirect scheme https code 301 if !{ ssl_fc }
```

the LB-frontend is named 'frontend 80' not 'frontend http-frontend' in the latest Rancher-LB release

_this will redirect every port 80 request to 443._

if you use the Rancher-LE container you need to add these changes :

```
# Custom haproxy.cfg
frontend 80
acl lepath path_beg -i /.well-known/acme-challenge
redirect scheme https code 301 if  !lepath !{ ssl_fc }
```

**Comment by thosvesta** [comment]
@J-Ha @dalareo Thank you J-Ha for the code, that solves the 503 http problem. 

> this will redirect every port 80 request to 443.

However, if I have a mix of https and http sites in the Loadbalancer, then every port 80 request is redirected to 443. **How to apply 80->443 redirect only for certain hosts in the list?**

**Comment by J-Ha** [comment]
@thosvesta Trick one, use SSL for each host! thats the easy way ;) https is a standard, not optional! ;)

trick two, figure out your backend names (exec the lb-container, get the name from the haproxy.conf)

an set them as ignore state 
`redirect scheme https code 301 if !<..backend-name> !{ ssl_fc }`

**Comment by dalareo** [comment]
Thanks @J-Ha that solved the redirect error!! No more 503!!
I don't even have a selector rule, just:
````
# Custom haproxy.cfg
frontend 80
acl lepath path_beg -i /.well-known/acme-challenge
redirect scheme https code 302 if  !lepath !{ ssl_fc }
````
I attach a screenshot of my LB with Letsencrypt:
![screenshot from 2017-02-15 13-32-44](https://cloud.githubusercontent.com/assets/919861/22974580/5097c138-f383-11e6-88ba-6dc85f78d196.png)

**Comment by jmaasing** [comment]
The config dalareo showed worked nice for me. Thanks a lot.

**Comment by Notifium** [comment]
Thanks dalareo, that helped me as well!

Regards,
Andy

**Comment by smujaddid** [comment]
Thanks @dalareo ! It works well
