### ISSUE TITLE
harvester cluster goes into error state with temporary connection error when a local user is added as a cluster owner

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35067]
**Rancher Server Setup**
- Rancher version: `v2.6-head` 62c101a
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.21.3 `
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.21.5+rke2r1`
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 3 worker, 1 etcd, 1 cp`

**Describe the bug**
Harvester cluster goes into error state and revives back in a few minutes. Saw this happen when a local user with standard user permissions is added as a cluster owner in the cluster.

**To Reproduce**

- created a standard user from global permissions on the rancher server from users & auth - user1
- From the Virtualization management page --> harvester cluster --> RBAC --> added the created user as a Cluster Owner.
- log in as user1

**Result**
- When I tried to login as user1, the cluster went into a error state with the error displayed on the cluster and was inaccessible. 
```
2021/10/06 19:12:38 [ERROR] error syncing 'c-m-fqrjnx4k': handler cluster-deploy: Get "https://10.53.0.1:443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": cluster agent disconnected, requeuing
2021/10/06 19:38:55 [ERROR] error syncing 'c-m-fqrjnx4k': handler cluster-deploy: Get "https://10.53.0.1:443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": net/http: TLS handshake timeout, requeuing
```

After some time 5 to 10 minutes, the cluster came back active. 

**Expected Result**
Cluster not expected to go into error state.

**Screenshots**

**Additional context**
Once the cluster came back up active, as an admin created a new standard user and added them as Cluster member - role binding was created for the user as well as the cluster role
Logged in as that cluster member and the cluster didn't go into error state.

**Comment by TachunLin** [comment]
Verified **fixed** on master-f5bde7fa-head with Rancher `v2.6-head`. (744f32f)
This issue did not happen after several trials. Close this issue.

### Result
With different user login, the downstream harvester cluster keep in `active` no error state show up.
![image](https://user-images.githubusercontent.com/29251855/143161985-81e11966-15b6-45e5-8965-7e385a34af59.png)


### Test Information
* Test Environment: 3 nodes harvester on provo bare machines
* Harvester version: master-f5bde7fa-head
* Rancher version: v2.6-head
* Kubernetes version: v1.21.5+rke2r1

### Environment Preparation
1. Install harvester v2.6-head through docker command

### Verify Steps
1. Environment preparation as above steps
2. Import harvester in rancher 
3. Create `user3` as standard user in user&authentication
4. Add user3 as cluster owner in harvester RBAC page
5. Login with user user3 
6. Access the virtual machine page
7. Check harvester cluster state
8. Login with another user1 and user2
9. Check harvester cluster state
10. Repeat the previous step several times and check harvester state
