### ISSUE TITLE
2.5.9 -> 2.5.10-rc2 rancher upgrade | Newly added windows 2004 worker node does not get deleted after the upgrade 

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#35066]
**Rancher Server Setup**
- Rancher version: v2.5.10-rc2
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: v1.17.17
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom Windows

**Describe the bug**

After the rancher upgrade from 2.5.9 to 2.5.10-rc2 and deleting a newly added windows worker node the node didn't get deleted

**To Reproduce**
 
1. HA rancher
  * rancher chart version 2.5.9
  * rke version 1.2.9
  * helm version 3.3.4
2. add a custom Windows 2004 cluster 
  * 1 linux node with 3 roles assigned 
  * 3 windows workers 
4. add a daemonset (so it's running on all nodes) workload (ranchertest/testcontainer-windows2004)
5. upgrade rancher to 2.5.10-rc2 using helm 
6. add a new windows 2004 worker node to the cluster 
7. delete the newly added node using UI

**Result**
- logs show that the node was deleted but then a machine was created for the node
- the node is still present on the UI 
- the workload still seems to be running on that node 
- `kubectl get nodes` returns the node with no roles assigned 

![repo](https://user-images.githubusercontent.com/40282141/136287133-309a9a06-c263-439c-80c1-fd4c406bde0d.png)

**Expected Result**

the node is deleted

**Screenshots**

**Additional context**
tried to reproduce the issue immediately with a new windows worker added, waited for the daemon set to start running on it, and then deleted - the node got deleted properly
successfully deleted a windows worker node which was created before the upgrade - the node got deleted properly

LOGS:
```
2021/10/06 20:04:04 [INFO] Provisioning cluster [c-cwjnl]
2021/10/06 20:04:04 [INFO] Updating cluster [c-cwjnl]
2021/10/06 20:04:04 [INFO] Deleted cluster node m-5f12ba71fbda [ip-ac1f09c6]
2021/10/06 20:04:09 [INFO] kontainerdriver rancherkubernetesengine listening on address xxxxxxx35927
2021/10/06 20:04:09 [INFO] kontainerdriver rancherkubernetesengine stopped
2021/10/06 20:04:09 [INFO] Updated cluster [c-cwjnl] with node version [1]
2021/10/06 20:04:09 [INFO] Provisioned cluster [c-cwjnl]
2021/10/06 20:04:09 [INFO] checking cluster [c-cwjnl] for worker nodes upgrade
2021/10/06 20:04:58 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
W1006 20:07:15.201753       7 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021/10/06 20:07:22 [INFO] Created machine for node [ip-ac1f09c6]
```

**Comment by Jono-SUSE-Rancher** [comment]
@sirredbeard - I moved this out of 2.5.12 since it wasn't getting any traction. In fact, I'm not sure if this is even an applicable issue. Does the matrix even recommend the 2004 support still for 2.5x? Is this something we can close or should we leave it in for a future concern given that EOM for 2.5x was Jan 5th, 2022?

**Comment by sirredbeard** [comment]
Closing as Windows Server version 2004 is EOL.

**Comment by sowmyav27** [comment]
Reopening to test if this usecase passes using a Windows 2019 Server

**Comment by slickwarren** [comment]
I do not see this issue when performing the same steps, but upgrading to 2.5.13-rc1 and using windows-2019.
