### ISSUE TITLE
RKE2 / Harvester: Nodes stuck in provisioning when master nodes lack worker role - Still need to be tested for k8s 1.22

### ISSUE THREAD

**Issue by alexdepalex** [rancher/rancher#35065]
**Rancher Server Setup**
- Rancher version: v2.6.1-rc5
- Installation option (Docker install/Helm Chart):
   - Helm chart, running on RKE2
- Proxy/Cert Details:
   - Air-gapped env

**Information about the Cluster**
- Kubernetes version:
- Cluster Type Downstream:
   - Deployed on Harvester v0.3.0-rc1-hotfix running on bare metal
   - Kubernetes version v1.21.5+rke2r1
- Guest cluster os: Ubuntu 20.04

**Describe the bug**
We're creating a cluster with 2 machine pools:
  - Master pool that consists of 3 nodes and has the etcd and control plane role
  - Worker pool that consists of 3 node that has the worker role
During deployment, one of the nodes will eventually have a bootstrapped k8s. The other master nodes are only running `rancher-system-agent` and never finish provisioning. The message `Processing secret` is continuously being logged.

When recreating the cluster and adding the worker role to the master pool, deployment finishes successfully.

This doesn't happen when deploying an RKE1 cluster.

**To Reproduce**
Create a machine pool that only has the etcd and control plane role. Create an additional machine pool that only has the worker role. Deploy.

**Result**
The cluster is stuck in provisioning.

**Expected Result**
Don't get stuck would be great.

**Comment by guangbochen** [comment]
this should be fixed via https://github.com/rancher/rke2/pull/2072 and waiting for the new RKE2 KDM release.

**Comment by noahgildersleeve** [comment]
Tested with 2.6.2 rancher (3 node HA) and Harvester v1.0.0-rc1 (4 node setup) and it still got stuck in provisioning.
![Screenshot from 2021-12-01 15-46-36](https://user-images.githubusercontent.com/83787952/144332548-481bc8d9-ffc2-44c4-93b6-69c3eb825012.png)
[supportbundle_bee84d48-5174-48c3-a80e-8c4d8f61b6c0_2021-12-01T23-49-35Z.zip](https://github.com/rancher/rancher/files/7637812/supportbundle_bee84d48-5174-48c3-a80e-8c4d8f61b6c0_2021-12-01T23-49-35Z.zip)

**Comment by guangbochen** [comment]
The rke2 version we are using for test is not correct, it should be `v1.21.7-rc3+rke2r1`, u will need to modify the `rke-metadata-config` setting first to get the latest RKE2 dev version for testing.
![image](https://user-images.githubusercontent.com/4569037/144337908-98168d9e-b46b-46f6-9bda-7054bd1d803e.png)

**Comment by noahgildersleeve** [comment]
Tested with Rancher v2.6-head with rke-metadata-config of dev-2.6, and harvester v1.0.0-rc1. RKE v1.21.7 on opensuse with 2 nodes 1 with etcd and control plane and another with worker role. RKE2 cluster showed as active and Kubeconfig worked for connecting to RKE2 cluster.
![Greenshot 2021-12-01 18 14 58](https://user-images.githubusercontent.com/83787952/144345094-3a8f6e63-e8b8-43ad-ac3c-87ca0f781144.png)
![Greenshot 2021-12-01 18 15 06](https://user-images.githubusercontent.com/83787952/144345098-6b204215-7dfa-42b1-99ba-0d8aa457c80f.png)
![Greenshot 2021-12-01 18 15 21](https://user-images.githubusercontent.com/83787952/144345099-0da6e7ad-a6b9-4610-a1ff-8b3774f20d82.png)

**Comment by noahgildersleeve** [comment]
Re-opening due to `v1.22.4` not currently working.

**Comment by guangbochen** [comment]
> Re-opening due to `v1.22.4` not currently working.

depends on https://github.com/rancher/rancher/issues/35683

**Comment by yasker** [comment]
**Test result: Pass**

Rancher: v2.6.3-rc5
Harvester: master-1c02888d-head
RKE2: v1.22.4+rke2r2

Verified on v1.22.4+rke2r2 with 3 nodes with ETCD and Control plane and 3 worker nodes. Provisioning succeed. 
<img width="1926" alt="Screen Shot 2021-12-15 at 11 13 01 AM" src="https://user-images.githubusercontent.com/3344618/146250161-6e6cc149-ec45-4c87-929e-9b08ad9627ad.png">
