### ISSUE TITLE
Rancher 2.0 call api report invalid csrf token

### ISSUE THREAD

**Issue by rainbowechoes** [rancher/rancher#35076]
I want to call rancher 2.0 create project api by in java code.

I use postman desktop call api can be worked by set 'Authorization', 'Content-type', 'Accept' header.

But when I do this in java code, it return 'invalid csrf token'.

![image](https://user-images.githubusercontent.com/38370475/136505182-a467f2f0-b294-4067-a9ba-85e729b74c91.png)

![image](https://user-images.githubusercontent.com/38370475/136505244-8b057117-c8f1-400d-bc3d-00382740dc9c.png)

How to resolve this problem?

**Comment by heidongbianjie** [comment]
Could you please suggest how you solved this problem

**Comment by rainbowechoes** [comment]
> Could you please suggest how you solved this problem

you can try to use okhttp3 lib to send request. It's too early, I have forget this, sorry.

**Comment by heidongbianjie** [comment]
> > Could you please suggest how you solved this problem
> 
> you can try to use okhttp3 lib to send request. It's too early, I have forget this, sorry.

Well,it didn't work out for me.But thanks anyway.
