### ISSUE TITLE
Fleet - can't assign clusters to other workspaces after upgrade to v2.5.10-rc4

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#35079]
**Rancher Server Setup**
- Rancher version: `v2.5.10-rc4`
- Installation option: Helm HA RKE1
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): Downstream cluster 1 node all roles RKE1 EC2 driver

**Describe the bug**

I had 3 clusters downstream assigned to three different workspaces. 

- cluster1 assigned to the `fleet-kubectl` (workspace created with kubectl)
- cluster2 assigned to `fleet-dashboard` (workspace created from the Dashboard UI)
- cluster3 kept in the `fleet-default` 

After the upgrade I was no longer able to assign the clusters to other workspaces.

**To Reproduce**

Have a Rancher `v2.5.9`, create 3 EC2 driver downstream clusters single node all roles.
Configure and assign the clusters to the fleet workspaces as described above.
Upgrade the Rancher `v2.5.9` to `v2.5.10 -rc4`  
Wait for the upgrade and all system components to complete.
Attempt to assign a cluster from a workspace to another workspace from the Dashboard UI

**Result**

`{ "data": "404 page not found\n" }`

**Expected Result**
As a user I am able to assign clusters after upgrading to `v2.5.10`

**Screenshots**
![Screen Shot 2021-10-08 at 11 42 28 AM](https://user-images.githubusercontent.com/27659/136610902-6c67af7c-72aa-430a-9445-ec5e774d3fcb.png)

**Comment by Shaked** [comment]
I'm seeing the exact same issue in 2.6.0. Any idea how to fix this?

**Comment by izaac** [comment]
Rancher version: `v2.5.10-rc4` and `v2.5-head (10/11/2021)` _ce52c78_

The setup was upgraded from `v2.5.9`. After the upgrade I am still able to reproduce. 
I tried clearing my browser cache and with an additional browser in Incognito mode.

**Comment by kriswill** [comment]
I'm having a similar issue when using Fleet from upgraded Rancher `2.5.9` -> `2.6.0`.  Appears, that there are remnants of an older version of the fleet helm chart in `fleet-system`.  I also, was unable to create workspaces from the UI, resulting in a "Method POST not supported" error.  After manually creating the workspace using a manifest apply, then using "Assign" to workspace in the UI, it promptly deleted the cluster.... Like terminated all of the nodes in EC2.  Joy!

**Comment by kriswill** [comment]
https://github.com/rancher/rancher/issues/34744 it's likely I'm actually experiencing this bug.

**Comment by izaac** [comment]
Rancher version: `v2.5.10-rc5`

Validated this is now working in this version. I was able to Assign Fleet clusters back and forth workspaces. Created with kubectl or from Dashboard.

I did an extra validation upgrading to `v2.6.1` with the same positive results and without clusters or nodes getting deleted which was fixed in a [separate issue](https://github.com/rancher/rancher/issues/34744).
