### ISSUE TITLE
Support VMware cloud init datasource

### ISSUE THREAD

**Issue by braunsonm** [rancher/rancher#35099]
**Is your feature request related to a problem? Please describe.**
Bear with me as I try to uncover the mess that is the vSphere cloud-init support. There are two ways to pass cloud-init data to vSphere VMs:
- OVF
- VMware Datasource (extraConfig properties)

The VMware Datasource is new and was just recently merged into the upstream cloud-init project. OVF properties uses VMware customization to setup the networking, and then feeds only the userdata portion to cloud-init to run. This has some problems because VMware customization conflicts with cloud-init as documented here: https://kb.vmware.com/s/article/54986

The VMware Datasource has a more standard approach. It uses `extraConfig` and supports both metadata and userdata for a full cloud-init approach. We opted to use this approach for our node templates. 

Rancher only sets the OVF properties from what I can tell, which means we cannot have custom userdata specified in our `extraConfig` and expect the nodes to join a cluster.

**Describe the solution you'd like**
I would like to be able to use the new datasource instead of OVF properties.

**Describe alternatives you've considered**
Just using the OVF properties isn't great because of the conflicts in setting up networking requiring one or the other.

**Additional context**
For setting IPs using network protocol profiles I would probably still need to do something like described here: https://www.virtualthoughts.co.uk/2020/03/29/rancher-vsphere-network-protocol-profiles-and-static-ip-addresses-for-k8s-nodes

But instead set this in the `extraConfig`. It would be great if Rancher could handle some of this correctly in the `metadata` portion for me and set the static IP from a pool

VMware Datasource Docs: https://cloudinit.readthedocs.io/en/latest/topics/datasources/vmware.html

**Comment by Martin-Weiss** [comment]
Can we get this re-opened? I see the same request for the customers I am dealing with..

**Comment by Martin-Weiss** [comment]
@braunsonm - do you think you can create a Support Case for this request?
