### ISSUE TITLE
Logging failing to reach output set in rancher due to fluentd crashing repeatedly

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#35109]
**Rancher Server Setup**
- Rancher version: `v2.6-9801a059cf239934f5093ba8e3d15bd3fd9460d5-head`
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1, RKE2`
- Proxy/Cert Details: `rancher generated/no proxy`

**Information about the Cluster**
- Kubernetes version: `v1.21.5-rancher1-1` and `v1.20.11-rancher1-2`
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? `Infrastructure Provider (EC2) on both clusters`

**Describe the bug**
Installed logging on a 2.6-head rancher server with ec2 rke1 and rke2 clusters. The fluentd logging crashes and fills the buffer, never sending logs to the desired output. It seems to be fine with 3.9.400 but not with 3.12.0

**To Reproduce**
1. created a rancher server with `v2.6-9801a059cf239934f5093ba8e3d15bd3fd9460d5-head`
2. added 2 clusters - `ec2` `one rke1 and one rke2`
3. installed logging v2
4. created secret
5. created cluster output
6. created cluster flow

**Result**
 ```logging does not flow```

**Expected Result**
```index appears in elasticsearch and logging flows```

**Screenshots**

**Additional context**
Eventually fluentd crashes again and the error still happens after some time. The fluentd pods are getting 'connection refused' from the fluentd service, and sometimes fluentd crashes the service. It seems to be fine with 3.9.400 but not with 3.12.0. Also determined that fluentd was crashing due to a full buffer. curl and nslookup don't work, either. This may not be patched by fluentd yet. 

These are the errors I saw when the fluentd pod was crashing:
`(this is the command: k describe po  -n cattle-logging-system rancher-logging-fluentd-0)`
```
Events:
  Type     Reason     Age                      From     Message
  ----     ------     ----                     ----     -------
  Warning  Unhealthy  6m38s (x147 over 3h12m)  kubelet  Liveness probe failed: dial tcp 10.42.5.7:24240: connect: connection refused
  Warning  BackOff    111s (x564 over 3h2m)    kubelet  Back-off restarting failed container
```

![Screen Shot 2021-10-13 at 1 13 48 PM](https://user-images.githubusercontent.com/89212856/137181736-a460f747-978a-4dc7-beaa-3c5911dd41c5.png)

**Comment by izaac** [comment]
This works with Logging v2 chart `3.9.400` and this also seems to not happen all the time.

I have this Rancher version `v2.6.1` with chart version `100.0.0+up3.12.0` and it's fluentd is not crashing there.
