### ISSUE TITLE
apply-system-agent-upgrader Jobs not starting

### ISSUE THREAD

**Issue by revog** [rancher/rancher#35105]
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): Helm RKE2

**Information about the Cluster**
- Kubernetes version: 1.21.4
- Cluster Type (Local/Downstream): Downstream, Imported RKE2 on-premise VM

**Describe the bug**
We deploy our downstream clusters fully automated with TF. Registration in Rancher is fine. After completed registration, `FailedCreate`events of the `apply-system-agent-upgrader` jobs appear in events view. 

**To Reproduce**
Stage new cluster or additional node and after job is beeing created it fails and gets reported.

**Result**
Every node has its own job which fails with the following error:
```
Error creating: pods "apply-system-agent-upgrader-on-rke-dev-wkr-08-with-61f21c-6b500-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.capabilities.add: Invalid value: "CAP_SYS_BOOT": capability may not be added spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used spec.volumes[0].hostPath.pathPrefix: Invalid value: "/": is not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.capabilities.add: Invalid value: "CAP_SYS_BOOT": capability may not be added]
```

**Expected Result**
Running jobs without error.

**Screenshots**
![event](https://user-images.githubusercontent.com/7138166/137107843-b1b35cac-c86d-41a3-8d98-6bf55ab65eac.png)
![jobs](https://user-images.githubusercontent.com/7138166/137107846-bd54a555-632a-4f7f-9945-4846ad411b36.png)

**Additional context**
Default Pod Security Policy of downstream cluster is `RKE2 Default` (default - did not change this):
![cluster_config](https://user-images.githubusercontent.com/7138166/137108116-7b659403-4cb1-45bb-bf94-79b0557d97a4.png)

**Comment by Martin-Weiss** [comment]
not stale
