### ISSUE TITLE
[csi migration] node is unable to upgrade k8s after csi migration -> cpi/csi charts are restarting 

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35102]
**Rancher Server Setup**
- Rancher version:v2.5.9 (up to 2.5.10-rc5)
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):n/a
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:1.19.15 upgrading to 1.20.11
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):vsphere provider

**Describe the bug**

after doing an in-tree to out-of-tree migration, the cluster is not able to upgrade; specifically on the node containing workload(s) with bound volumes from the pre-migration pv. 

**To Reproduce**
 
* deploy a cluster with in-tree cloud provider in vsphere on 1.19 with at least 3 dedicated worker nodes
* provision a storageClass, use it to deploy a test workload with a bound volume attached
* follow the [CSI Migration steps](https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/cloud-providers/vsphere/out-of-tree/vsphere-volume-migration/?#)
  * after the migration, confirm that it was successful by writing to the volume, deploying a new workload with a volume attached using the new storage class from csi chart, etc.
  * note that the newly installed charts for csi/cpi are healthy and actively working
  * take note of the node(s) that pv-attached workloads are deployed to
* upgrade the cluster to a later supported version, i.e. 1.20

**Result**
node(s) that contain workloads/volumes from the migration are stuck in a `cordoned` or `draining` state; the cpi/csi charts (both agents and controllers) are continuously restarting as well. 

**Expected Result**

migrated clusters should continue to work normally after a k8s upgrade

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>
* this was tested on 2.5.9 and 2.5.10-rc5
* we also tested oot and in-tree without migration to verify that the normal k8s upgrade case is working in vsphere for both types
* also saw the error `[controlPlane] Failed to upgrade Control Plane: [[error draining node ctw-119-dsa1: error when waiting for pod "pod-from-premigration" terminating: global timeout reached: 2m0s]]`

**Comment by kinarashah** [comment]
Last step of migration is to change kubelet and kube controller args, and enable drain in UI. Since the args are updated in `Edit as Yaml`, it requires manually adding `drain: true` under node_drain_input of upgrade strategy. Currently, it wasn't getting set correctly, which is why it  **seemed to be working with drain enabled**.

**Comment by kinarashah** [comment]
Issue is draining node might fail if the workload on the node is created pre-migration and has volume mounts. New pod gets created as expected and all data is preserved but the old pod is stuck in terminating and this causes the drain to fail. 

This is the same exact behavior we observe when trying to drain using the kubectl as well, so is not specific to the upgrade issue. Workaround is to manually force delete this pod `kubectl delete pod delete --grace-period=0 --force=true`. 

Also we don't keep retrying drain once timeout is reached, so would need to trigger drain manually after deleting the terminating pod. 

Note: This only happens on the first drain post migration, drain and deleting pods work as expected afterwards.

**Comment by kinarashah** [comment]
**Update:**
From the docs, https://vsphere-csi-driver.sigs.k8s.io/features/vsphere_csi_migration.html#how-to-enable-vsphere-csi-migration, it seems like drain is a must do step post migration. 

`Enable feature flags CSIMigration and CSIMigrationvSphere on kubelet on all workload nodes. Please note that before changing the configuration on the Kubelet on each node we must drain the node (remove running application workloads).`

Because of the first issue, https://github.com/rancher/rancher/issues/35102#issuecomment-942750533 - we weren't draining nodes at all so the other issues could be stemming from that. 

**To test:**
- Make sure we drain nodes as the last step of migration. 
- No issues while upgrading to k8s version afterwards.

**Comment by kinarashah** [comment]
https://github.com/kubernetes/kubernetes/issues/65110

**Comment by cbron** [comment]
Re-assigning, if we can't permanently fix this, we should document at an app level, either in chart or official docs, as this only relates to CPI/CSI.

**Comment by vivek-infracloud** [comment]
### Tested if the CSI chart documentation is updated to explain the workaround to upgrade the nodes. The test pass.

**Rancher Server Setup**
- Rancher version:v2.5.12-rc4
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:v1.19.16 upgrading to v1.20.14
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vSphere provider


**Steps followed**
 
* On rancher v2.5.12-rc4 Deploy a cluster with in-tree cloud provider in vsphere on 1.19 with at least 3 dedicated worker nodes.
* Provision a StorageClass, use it to deploy a test workload with a bound volume attached
* Follow the [CSI Migration steps](https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/cloud-providers/vsphere/out-of-tree/vsphere-volume-migration/?#)
  * After the migration, confirmed that it was successful by writing to the volume, deploying a new workload with a volume attached using the new storage class from csi chart, etc.
  * Note that the newly installed charts for csi/cpi are healthy and actively working
  * took a note of the node(s) that pv-attached workloads are deployed to
* Upgrade the cluster to a later supported version, i.e. 1.20
* Node(s) that contain workloads/volumes from the migration are stuck in a `cordoned` or `draining` state.
* Followed the workaround **mentioned in the CSI chart documentation.**
* The upgrade continued after the pod(s) stuck terminating are removed.
* **Cluster upgrade from 1.19 to 1.20 was successful after CSI in-tree to out-of-tree migration.**
