### ISSUE TITLE
Replace downloaded K3s binary with its Docker image in the Dockerfile

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#35101]
SURE-3522
A part of #[33850](https://github.com/rancher/rancher/issues/33850).

Use the `FROM rancher/k3s` instruction in the Dockerfile instead of pulling in the downloaded K3s binary.

**Comment by slickwarren** [comment]
test cases: 
* fresh install (docker) 2.6-head
* docker install 2.6.3 -> upgrade to 2.6-head
* docker install 2.6.3 using volume mounts -> upgrade to 2.6-head
* Standard cluster operations: creating and deleting deployments, services, jobs, secrets, namespaces.
  * in local cluster
  * in downstream cluster

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: different (see below)
Rancher cluster type: single-node docker install / HA
Docker version: 20.10

Downstream cluster type: n/a
Downstream K8s version: n/a

----------

### Testing: ###

Fresh docker install 2.6-head d540651
-provisioned a rke1 node driver
-local and dowstream cluster manual testing:
--can create/edit/delete deployment, cronjob, service (checked networking), secret, namespace
--can create/delete pod
--can create fleet deployment and services
--can add a custom chart installation (with deployment and services)

Rancher 2.6.3 with 2 downstream clusters (rke1 node driver and a custom cluster)
-ran automation
-upgraded to 2.6-head a140dab
-ran automation
-rolled back to 2.6.3
-ran automation

Rancher 2.6.3 with volume mount and 1 downstream cluster (rke1 node driver)
-ran automation
-upgraded to 2.6-head 3f30288
-ran automation
