### ISSUE TITLE
Removed downstream cluster still visible on the dashboard and sidebar (unavailable)

### ISSUE THREAD

**Issue by avodaqstephan** [rancher/rancher#35118]
Hi folks, 

I lost contact to a downstream cluster due to DNS and certificate changes of my Rancher Management Cluster and uninstalled RKE2 on the nodes through the `/usr/local/bin/rke2-uninstall.sh` script.

I clicked delete in the cluster management UI and the cluster got removed.

![image](https://user-images.githubusercontent.com/58725083/137331360-631d27c7-c94c-43e4-8ab6-6a8ec483d141.png)

But the cluster is still visible in the sidebar menu and the home dashboard but its state is `unavailable`

![image](https://user-images.githubusercontent.com/58725083/137331484-5d5b3e63-0672-459c-ba45-f49d90e5125f.png)
![image](https://user-images.githubusercontent.com/58725083/137331545-337e0769-5347-4966-8121-cb467a22f30c.png)

I can't find an option to remove the non-existent cluster from there. 

I'd expect that removing the cluster from the cluster management page would get rid of it on the other overview pages as well. 

Kind regards,
Stephan

**Comment by siddharthmakwana** [comment]
I am facing the same issue. EKS cluster was removed manually from AWS console and now as it was registered on Racher server too, it has gone in unavailable state and we are unable to remove that cluster entry from Rancher's cluster list.
