### ISSUE TITLE
Cluster Stuck Removing "wrangler.cattle.io/mgmt-cluster-remove"

### ISSUE THREAD

**Issue by marvinpeter-kisters** [rancher/rancher#35116]
**Rancher Server Setup**
- Rancher version: v2.5.9
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm Chart on RKE 
- Proxy/Cert Details: Certmanage but use custom officially signed certificate for the Rancher Ingress

**Information about the Cluster**
- Kubernetes version: v1.19.15

**Describe the bug**
I wanted to remove a cluster from our Rancher but its been stuck for hours on "Waiting on wrangler.cattle.io/mgmt-cluster-remove".  I already tried restarted the Rancher Cluster and I already tried deleted the cluster node of the cluster I want to be removed.

**Result**
Cluster is stuck in removing state.

**Expected Result**
The cluster should be removed from Rancher.

**Screenshots**
![image](https://user-images.githubusercontent.com/92513388/137283437-b30749da-aead-4ff5-9ae8-391a06f9ef12.png)

**Logs (Rancher Container in K8s)**
2021/10/14 08:43:14 [ERROR] error syncing 'c-jf2t5/m-16c7c070bc7e': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/10/14 08:43:14 [ERROR] error syncing 'c-jf2t5/m-17d543fc3464': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/10/14 08:43:14 [ERROR] error syncing 'c-jf2t5/m-f9af0ee1cad8': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/10/14 08:43:14 [ERROR] error syncing 'c-jf2t5/m-d426e9cca313': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/10/14 08:43:14 [ERROR] error syncing 'c-jf2t5/m-0ee5ab4659cc': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/10/14 08:43:14 [ERROR] error syncing 'c-jf2t5/m-9b107055cd5c': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing

**Comment by kbudde** [comment]
Same issue here. We tried deleting the cluster while rancher was under heavy load.
No it is stuck.

**Comment by kbudde** [comment]
We've removed finalizers with
> k edit clusters.management.cattle.io/c-jf2t5
and the cluster got deleted.
Nevertheless I'm not sure about the side effects.

**Comment by marvinpeter-kisters** [comment]
Thanks. That worked.
