### ISSUE TITLE
[2.6] Update NGINX to 0.49.3 and make allow-snippets-annotations configurable

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#35128]
Update NGINX to upstream ([0.49.3](https://github.com/kubernetes/ingress-nginx/tree/controller-v0.49.3))
Add KDM templates for 1.19.x, 1.20.x, and 1.21.x ([NGINX support matrix](https://github.com/kubernetes/ingress-nginx#support-versions-table))

**Comment by anupama2501** [comment]
Verified on v2.6.2 pointing KDM to ``

1. Created downstream clusters on all network providers on the k8s versions:

- v1.21.6-rancher1-1
- v1.20.12-rancher1-1
- v1.19.16-rancher1-1

2. All the ingresses have come up active 
3. Verified the `allow-snippet-annotations` is by default set to `false`
4. Edited the config and changed the value to `true`
5. Re-deployed the nginx-ingress-controller and verified the `allow-snippet-annotations` in the config map is set to `true`

**Comment by anupama2501** [comment]
Based on my above comments closing the issue as its working as expected.

**Comment by sowmyav27** [comment]
The following scenarios have been validated:
- Upgrade of rancher server from 2.5.10 to 2.6.2 and KDM pointing to `dev-v2.6-1021-patches`
- RKE checks on `v1.3.2-rc2`
