### ISSUE TITLE
Sort order on host page is by id not host name

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3512]
Version - master 2/3

Comment:
The sort order on the host page used to be by host name.  Now it's on id (order in which they were added).  I like the host name order better.  It's easier to find a specific host that way.

**Comment by vincent99** [comment]
Needed to use the displayName (name or hostname or id) here for sorting..

**Comment by tfiduccia** [comment]
Version - master UI 2/4
Verified fixed
