### ISSUE TITLE
Cluster Explorer Apps & Marketplace does not show Charts and Versions in Charts  with extensions like x.x.x-someTextOrNumbers

### ISSUE THREAD

**Issue by benzman81** [rancher/rancher#35139]
Cluster Explorer Apps & Marketplace does not show Charts and Versions in Charts  with extensions like x.x.x-someTextOrNumbers

**Rancher Server Setup**
- Rancher version: 3.6.x
- Installation option (Docker install/Helm Chart): Docker install
- Proxy/Cert Details: generated by Rancher

**Information about the Cluster**
- Kubernetes version: v1.19.3
- Cluster Type (Local/Downstream): Local and Custom

**Describe the bug**
The Cluster Explorer Apps & Marketplace does not show Charts or Versions within Charts with extensions like `x.x.x-someTextOrNumbers` although this is supported by SemVer2 and explicitly documented by Helm to be supported.
Quote: "More complex SemVer 2 names are also supported, such as version: 1.2.3-alpha.1+ef365."
(see https://helm.sh/docs/topics/charts/#charts-and-versioning)

**To Reproduce**
Create a simple Helm Chart like this and add it to your repository to be ready to install:
```
apiVersion: v1
version: 1.2.3-Foo-1.1.1
name: sample
description: A sample Helm chart.
keywords:
- sample
```

**Result**
The Chart will not show up. If you change the version to `1.2.3` and add it to your repository the Chart will become visible but only the version `1.2.3` will be seletable.

**Expected Result**
All Charts and Chart Versions comliant to SemVer 2 and Helm must be installable and selectable.

**Comment by benzman81** [comment]
Anyone had a chance to look into that? This is a blocker for us using version 2.6.x

**Comment by vincent99** [comment]
A version with a dash after it is a prerelease and prereleases are intentionally hidden by default (both by the regular Helm CLI and the Rancher UI).  There's an option in preferences (top-right user icon menu) to show prereleases.

**Comment by benzman81** [comment]
@vincent99 thank you, didnt see the option to show its.
