### ISSUE TITLE
enable generic `in-tree` option for cloud provider

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35142]
**Request:**
* add some functionality to enable a generic cloud provider for `in-tree`, to allow users to use a cloud provider even if it isn't built in

repro steps:
* enable a node driver that isn't enabled by default (i.e. OCI)
* provision a cluster for the newly enabled driver
  * try to select the cloud provider from the list

Issue:
* cloud provider for in-tree is only available for a limited set of providers through rancher
<img width="445" alt="Screen Shot 2021-08-18 at 12 52 34 PM" src="https://user-images.githubusercontent.com/16691014/129963333-2562ebcf-6f82-486f-8f3e-1236868d1734.png">

**Additional Comments:**
In ember, there was a `custom` option for in-tree providers. This was not ported into dashboard.
Though in tree will be deprecated in 1.23, users should still have an `in-tree` option for whatever provider they are using until then. We currently have a list of in-tree providers (i.e. ec2, google, vsphere, ...) but this is not a complete list.

**Comment by cbron** [comment]
@vincent99 do you know if we made a decision to specifically not do this ? I'd lean towards us not implementing this, just wait for it to go away entirely. But it looks like the upstream issue is now unscheduled.

**Comment by vincent99** [comment]
On the UI side it's just not there because it's not one of the options in the schema for that field.. I assume that was intentionally omitted, but you could ask @ibuildthecloud .

**Comment by snasovich** [comment]
@cloudnautique , do we need this for RKE2 -> RKE1 parity?

**Comment by snasovich** [comment]
Per discussion with @cloudnautique and @deniseschannon this is not needed. Closing.
