### ISSUE TITLE
When registering a host, the name is not being set properly

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3514]
Version - master 2/3

Steps:
1.  Create a host
2.  Edit the host

Results:  The name you gave to the host is not being saved as name.

Expected:  Should be saved as name.

**Comment by vincent99** [comment]
The name that is displayed for a host is now the first that is set of: `name`, `hostname`, `(id)`.  (Hostname comes from the host OS and is generally always set).  The `rancher/agent` keeps `hostname` up to date with the current value from the host, and the `name` field allows the user to override what is displayed with their own value.

When you use docker-machine (AWS, DigitalOcean, etc, anything but Custom) the computer's `hostname` is set to the name you provided.  This gets picked up when the host registers with Rancher and filled in as the `hostname`.  So there is no need to fill in the user override value on a new host.

There does need to be better explanation of this on the host edit screen though, I changed it to:

![image](https://cloud.githubusercontent.com/assets/753917/12802271/e8949e42-ca9f-11e5-92cd-6639240a81e0.png)

**Comment by tfiduccia** [comment]
Version - master UI 2/4
Verified fixed

**Comment by DanielDent** [comment]
I recently re-created my environment from scratch with the latest rancher. Previous versions had hosts start out showing their hostname. With the current version, hosts started out named '1h1', '1h2', etc. I'm unclear if this was the intended outcome of this issue.

**Comment by deniseschannon** [comment]
@DanielDent What version of Rancher are you using? This was fixed in v0.59.0.

**Comment by DanielDent** [comment]
This was a fresh install on v0.59.0.

**Comment by deniseschannon** [comment]
@DanielDent How are you adding your hosts?

**Comment by DanielDent** [comment]
Using the command provided on the 'add host' screen for a 'Custom Host'. That command is executed on a fresh Debian Jessie machine w/ Docker & other things preconfigured.

I'm not 100% sure, but I believe that in the version I was using before, the hostnames *did* get autodetected properly. While I know there was a bug fix, from my perspective there appears to be a regression.

**Comment by goodspd** [comment]
Same problam here with rancher v0.59.0 and  v0.59.1

**Comment by deniseschannon** [comment]
I have not been able to reproduce on v0.59.1 or v0.59.0. I'm using the custom host command on a fresh machine as well. This was fixed specifically in between v0.56.1 and v0.59.0, so I don't think there is a regression.
