### ISSUE TITLE
Nodenames for RKE2 provision on AWS - not matched on AWS provider

### ISSUE THREAD

**Issue by claudioser** [rancher/rancher#35141]
Not sure if this should logged at dashboard level. Please advise otherwise .

Poolnames used in provisioning dont match nodenames on aws provider.

See attached.
[rke2_on_aws.docx](https://github.com/rancher/dashboard/files/6900539/rke2_on_aws.docx)

.. but for rke1 on aws ,  nodenames are fine

**Comment by sowmyav27** [comment]
**On 2.6.2** 

- Reproduced the issue.
- Deployed an RKE2 EC2 node driver cluster
- Node names in Rancher:
<img width="685" alt="Screen Shot 2021-11-28 at 10 46 49 AM" src="https://user-images.githubusercontent.com/26032343/143781669-61e94d1a-1066-407d-82da-bc8678091e08.png">

- Node names in AWS:
<img width="441" alt="Screen Shot 2021-11-28 at 10 46 57 AM" src="https://user-images.githubusercontent.com/26032343/143781673-2606cdd4-60f7-4808-9cab-500e309362be.png">

On 2.6-head commit id:``
- Deploy an ec2 RKE2 node driver cluster
- The node names are now in this format `m-xxxxx` and not the actual names given when creating the cluster. It is set correctly in the backend in AWS
- 
```
 ...
  name: m-h9zq4
  namespace: c-25cwp
  resourceVersion: "31294"
  uid: 594de2f9-d5e7-4b1a-8392-a662dbc058e5
spec:
  controlPlane: true
  customConfig: null
  desiredNodeTaints: null
  displayName: ""
  etcd: true
  imported: false
  internalNodeSpec:
    podCIDR: 10.42.0.0/24
    podCIDRs:
    - 10.42.0.0/24
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      value: "true"
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      value: "true"
  metadataUpdate:
    annotations: {}
    labels: {}
  nodePoolName: c-25cwp:np-7gnwt
  nodeTemplateName: cattle-global-nt:nt-2cdbd
  requestedHostname: sowmya-122-1
```
