### ISSUE TITLE
rancher-compose doesn't propagate service.serviceSchema's fields to Rancher

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3516]
Steps to reproduce:

1) Deploy k8s cluster using rancher-compose from the https://github.com/rancher/rancher-catalog/tree/master/templates/kubernetes template. 
2) Check service.serviceSchemas field for the service in Rancher. This field is empty ("serviceSchema":{})

**Comment by ibuildthecloud** [comment]
I have quite happily removed service schemas so this does not apply anymore.
