### ISSUE TITLE
Cannot create S3 etcd snapshot credentials for RKE2 clusters

### ISSUE THREAD

**Issue by braunsonm** [rancher/rancher#35163]
**Rancher Server Setup**
- Rancher version: 2.6.0

**Information about the Cluster**
- Cluster Type (Local/Downstream): Custom, RKE2

**Describe the bug**
When creating a new custom cluster, you can enter a `cloudCredentialName` for `etcd.s3`. However even using the name of a `S3-Compatible` Cloud Credential gives the error that it cannot be found.

**To Reproduce**
1. Create a S3-Compatible Cloud Credential
2. Create a custom cluster with the `etcd.s3.cloudCredentialName` set to the name of the S3-Compatible Cloud Credential
3. Notice that it cannot find the cloud credential name

**Expected Result**
The cloud credential name should be found and snapshots should work

**Comment by Oats87** [comment]
Discussed with @braunsonm about this via Slack

I think there might be misconfiguration as `cloudCredentialName` is a very misleading key.

When creating an S3-compatible cloud credential via the UI and wanting to use it, `cloudCredentialName` should be of format
`cloudCredentialName: cattle-global-data:cc-XXXXX` where `cc-XXXXX` is replaced with the ID of your cloud credential (not the name)

**Comment by braunsonm** [comment]
That solves my issue thank you @Oats87
