### ISSUE TITLE
[RKE2 Template] Creating a cluster from a template referencing an admin managed cloud credential fails

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#35184]
Rancher 2.6.1

1. Create a RKE2 cluster template that contains a static reference to an admin-managed cloud credential. Example: https://github.com/janeczku/cluster-template-examples/blob/test1/charts/values.yaml#L13
2. As an admin user add the template to Rancher following the [docs](https://rancher.com/docs/rancher/v2.6/en/admin-settings/cluster-templates/#rke2-cluster-template).
3. As a standard user with permissions to use that template, create a RKE2 cluster off of the template. 

**Actual Result:**

Cluster creation fails with error `Error: Admission webhook "rancherauth.cattle.io" denied the request: Unauthorized`

**Expected Result:**

Admins should be able to provide cluster templates for users that do not require each user to manage their own cloud credentials.

This would result in better user experience, reduce administration effort and enhance security (by reducing the number of credentials out in the wild that need to be secured and maintained).

**Comment by snasovich** [comment]
@janeczku , thank you for submitting this issue. We've had a discussion with @thedadams @cloudnautique @vincent99 and properly supporting this scenario without potentially causing security issues will take a considerable amount of time and will likely involve implementing first-class support for shareable cloud credentials. This is something @cloudnautique  will be scoping in future, so I'm putting this issue to 2.6.x milestone for now and we'll get back to it when we scope 2.6.4+ / 2.7 releases.

**Comment by belgaied2** [comment]
The last comment in this issue is mentioning scoping for v2.6.4+, what is the current status here ?

**Comment by belgaied2** [comment]
Related to https://github.com/rancher/rancher/issues/34844
