### ISSUE TITLE
Downstream clusters use default global registry for some deployments even when cluster private registry is configured

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#35189]
SURE-3323
SURE-3113
SURE-3498
SURE-3051

**Rancher Server Setup**
- Rancher version: Rancher v2.6.0
- Installation option (Docker install/Helm Chart): Not Given
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Not Given
   - Proxy/Cert Details: Not Given
   - 
**Information about the Cluster**
- Kubernetes version: Not Given
- Cluster Type (Local/Downstream): Not Given
-    - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
Issue description:
When deploying a cluster with a private registry configured at the cluster level, Kubernetes cluster components provisioned via RKE and the Rancher cluster/node agent images are pulled using the cluster level private registry. However, other components, such as Fleet/Cluster Explorer Shell/Apps & Marketplace deployed charts, e.g. rancher-monitoring, are deployed according to the global default registry setting in Rancher, or Docker Hub by default. As such it is not possible to configure multiple clusters in a single Rancher instance if each environment does not have access to the single global default registry.

Business impact:
Unable to manage independent clusters in a single Rancher instance where environments do not have access to single global default registry. Customer has multiple non-airgapped environments, which use Docker Hub for images, but now wishes to add a new largely airgapped downstream cluster to the same Rancher instance. This new downstream will only have access to a local airgapped registry.

**To Reproduce**
Provision a Rancher v2.5.8 instance
Provision a downstream custom cluster with a private registry configured
Observe cluster components are deployed from private registry, but fleet-agent is pulled from Docker Hub. Open shell in Cluster Explorer and observe shell Pod image also pulled from Docker Hub.

**Result**
Kubernetes cluster components and cluster/node agents use cluster-level private registry, other components, such as Fleet/Cluster Explorer Shell/Apps & Marketplace deployed charts, e.g. rancher-monitoring, are deployed according to the global default registry setting in Rancher, or Docker Hub by default.

**Expected Result**
All Rancher provisioned components in the cluster observe cluster-level private registry configuration.

**Screenshots**
Not Given

**Additional context**
N/A

**Comment by paulchoi** [comment]
Just upgraded to Rancher 2.6.3 from 2.5.11.
Noticed that Fleet agent (`rancher/fleet-agent:v0.3.8`) on downstream clusters are pulling from the public docker.io as well.

**Comment by kinarashah** [comment]
Currently blocked by https://github.com/rancher/fleet/issues/712, found during investigating https://github.com/rancher/rancher/issues/36281.

**Comment by shurkanTwo** [comment]
Out team would also benefit from this.

**Comment by snasovich** [comment]
Since this issue is specifically for `fleet-agent` image (and not "some deployments" as the title states), this is tracked in https://github.com/rancher/fleet/issues/948. Closing as duplicate.
