### ISSUE TITLE
Service Stuck in Cancelling Upgrade

### ISSUE THREAD

**Issue by ronag** [rancher/rancher#3518]
1. Upgrade Service and provide an non existing image
2. Cancel Upgrade
3. Service is stuck in cancelling and won't start again

Solution:

1. Clone service
2. Delete stuck service

**Comment by deniseschannon** [comment]
I am unable to reproduce.

Steps I took:
1. Upgrade service to non-existent image
2. Cancel upgrade
3. Waited and eventually the state turned to "Cancelled-Upgrade". 
4. Click on "Rollback" cause you are rolling back to your previous service settings since your new service is invalid.

Rolled back to previous service.

**Comment by withinboredom** [comment]
I am able to reproduce this issue by having a service and a sidekick. I update the tag on both service and sidekick. The sidekick service's tag doesn't exist. Cancelling the upgrade as soon as I realize the typo. Rancher *stops* all running, healthy instances and insists on recreating the unhealthy ones, which is now stuck in an "Finishing upgrade state"

**Comment by withinboredom** [comment]
I should mention that I had "Start before Stopping" turned on in the upgrade screen.

**Comment by deniseschannon** [comment]
@withinboredom I tried to reproduce with your steps. I had a service with a sidekick for scale of 4. I tried to upgrade with an invalid sidekick image. When I go to cancel upgrade, if I wait, it will go into cancelled-upgrade state.

Did you try finish upgrade or rollback before or after you got into the `cancelled-upgrade` state?

**Comment by deniseschannon** [comment]
@withinboredom Please re-open if you can provide more details as mentioned, I was unable to reproduce.
