### ISSUE TITLE
Deviation from upstream restricted PSP

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#35191]
SURE-3199

**Rancher Server Setup**
- Rancher version: Rancher v2.5.8

**Describe the bug**
runAsUser set to RunAsAny in the restricted PSP which is a deviation from upstream example PSP

**To Reproduce**
Checked the documentation and found below

This policy is based on the Kubernetes example restricted policy.
The upstream example restricted PSP shows below.

  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
But the Rancher restricted PSP is not the same.

**Result**
Default restricted policy allows the container to run processes with root user.

**Expected Result**
Default restricted policy should not allow the container to run processes with root user.
Or there should be a note in documentation if this PSP deviation from the upstream example is intentional.

**Comment by nobbs** [comment]
Still interested in a solution to this issue, as this behavior also occurs in versions 2.6.x, as far as I can tell.

**Comment by macedogm** [comment]
@anupama2501 PR https://github.com/rancher/rancher/pull/36367 is ready for review.

**Comment by macedogm** [comment]
Docs PR https://github.com/rancher/docs/pull/3849

**Comment by macedogm** [comment]
Apologies, the issue was closed when the PR got merged. I'm reopening, so QA can properly validate it.

**Comment by anupama2501** [comment]
Verified test cases on 2.6-head 978e165

1. local k8s `v1.22.6-rancher1-2` and PSP set to restricted [local picks default-psp] - created 1 custom rke1 cluster with restricted-no-root, 1 rke1 node driver and and rke2 node driver cluster. Repeated the steps from the above comment - PASS
2. local psp with no restricted and a downstream restricted-no-root psp.Repeated the steps from the above comment - PASS
3. Local cluster rke1 with restricted PSP - default psp is picked, rancher pods deployed. Updated the default-psp runAsUSer rule to `MustRunAsNoRoot`. Deleted a rancher pod and verified the pods couldn't reconcile
```
Failed (12) | 52 mins ago | Error: container has runAsNonRoot and image will run as root (pod: "rancher-6988c76755-fq57r_cattle-system(2c02d913-d45c-498c-b492-56364f8aa5c5)", container: rancher)
```
4. local cluster set to restricted psp, and created a downstream cluster on restricted-psp. Changed the restricted psp to `restricted-no-root`. Deployed some workload pods with no security context added. Verified the pods errored out.
6. Enable downstream restricted psp and deleted the cluster - verified the clusters are deleted. 


Upgrade test case:

- Created a local cluster on 2.6.3 with PSP set to downstream on psp restricted upgrade rancher server, updated the psp on the downstream cluster from restricted to `restricted-no-root`
- Ran the same validations from the above step - PASS
