### ISSUE TITLE
After rancher upgrade and computer restart goes back to old rancher version?

### ISSUE THREAD

**Issue by ronag** [rancher/rancher#3519]
1. Upgrade rancher following instruction in documentation
2. Everything is good
3. Restart computer
4. Old rancher version is run and lots of weird issues.

Solution:

1. Total reinstall of Rancher

**Comment by deniseschannon** [comment]
Did you try a `docker ps -a` to see which rancher/server container started?

It sounds like you might have missed step 5 in the upgrading docs. 
http://docs.rancher.com/rancher/upgrading/
