### ISSUE TITLE
Rancher helmchart should support tolerations customization 

### ISSUE THREAD

**Issue by gartemiev** [rancher/rancher#35198]
Hi, We've noticed that there is no way to specify custom tolerations via rancher chart values. As a result with using taints on one of our EKS clusters We can not deploy rancher there. It would be great if you allow to customize tolerations on chart level via values.

**Comment by cbron** [comment]
Transferring this to Rancher. Open source PR's are always welcome.

**Comment by cbron** [comment]
Closing as dupe of: https://github.com/rancher/rancher/issues/34159
