### ISSUE TITLE
[CLI] Rancher CLI does not support KeycloakOIDC Auth Provider for kubeconfig

### ISSUE THREAD

**Issue by Blackclaws** [rancher/rancher#35194]
**Rancher Server Setup**
- Rancher version: 2.6.1
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Describe the bug**

Rancher CLI does not support Keycloak OIDC Auth Provider. Any kubeconfig file downloaded from rancher therefore fails to be usable when Keycloak OIDC is used as an auth provider

**To Reproduce**
1. Enable Keycloak OIDC as auth provider
2. Download a kubeconfig file
3. Try to use it. Rancher will prompt you for the credentials for the localProvider instead

**Result**
Kubeconfig is unusable

**Expected Result**
Rancher CLI opens browser or at least displays link to OIDC login

**Screenshots**

**Additional context**

**Comment by Blackclaws** [comment]
Still an issue

**Comment by michaelpearce-gain** [comment]
This seems to be the case also with SAML and AzureAD

**Comment by Blackclaws** [comment]
Keycloak SAML does work. Maybe other saml doesn't.

**Comment by michaelpearce-gain** [comment]
the default AzureAD (OAuth) doesnt 100% waisted almost a week trying to get limited time tokens working so that users dont have long term kubeconfig tokens. Even tried using SAML endpoint with Azure and nada too.

**Comment by Blackclaws** [comment]
Limited time might be broken in 2.6 see: https://github.com/rancher/rancher/issues/35187

**Comment by michaelpearce-gain** [comment]
We're on 2.5.x and didnt work, did try a separate testing install of 2.6 (to make sure its not fixed if we were to upgrade) and also same issue.

**Comment by michaelpearce-gain** [comment]
issue is not fixed, afaik.

**Comment by michaelpearce-gain** [comment]
very much still wanted.

**Comment by Blackclaws** [comment]
Still relevant

**Comment by michaelpearce-gain** [comment]
still relevant

**Comment by michaelandrepearce** [comment]
still relevant

**Comment by Blackclaws** [comment]
Ugh, stupid bot. This is still relevant
