### ISSUE TITLE
Clearing container static IP in managed network does nothing

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#3520]
Rancher v0.56.1

Steps to reproduce:
1. create a container with managed network and enter "10.42.1.1" IP,
2. upgrade the container and remove the static IP,
3. the container has still the static IP, not a random one.

**Comment by tfiduccia** [comment]
I have verified that this is a bug.  I removed the static IP and then went back (tried to upgrade again) after upgrading and the static IP was still there.

**Comment by vincent99** [comment]
Tracking as part of https://github.com/rancher/rancher/issues/3707
