### ISSUE TITLE
Rancher becomes unresponsive after duplicate cattle-monitoring-system resources are sent from the API to the UI

### ISSUE THREAD

**Issue by Auston-Ivison-Suse** [rancher/rancher#35209]
**Setup**
- Rancher version: v2.6.2-rc1
- Browser type & version: chrome: 94.0.4606.61
- Downstream RKE1 cluster with MonitoringV2 installed

**Describe the bug**
Rancher freezes and no longer is responsive after selecting the cattle-monitoring-system namespace from the namespace picker. 

**To Reproduce**
1. From the hamburger menu go to Apps & Marketplace
    a. Select installed apps
    b. click on rancher-monitoring app
    c. be directed to the rancher-monitoring detail page
2. Select the namespace picker at the top of the screen scroll down to cattle-monitoring-system

**Result**
This causes rancher to freeze and become unresponsive until you refresh the page. 

The errors in the console is as follows: 

```TypeError: Cannot read properties of undefined (reading 'key')
    at fr (vue.runtime.esm.js:5817)
    at vue.runtime.esm.js:6219
    at j (vue.runtime.esm.js:6319)
    at vue.runtime.esm.js:6193
    at j (vue.runtime.esm.js:6319)
    at vue.runtime.esm.js:6193
    at j (vue.runtime.esm.js:6319)
    at f.__patch__ (vue.runtime.esm.js:6482)
    at f.t._update (vue.runtime.esm.js:3948)
    at f.r (vue.runtime.esm.js:4066) 
```
    

**Expected Result**
Rancher should load the namespace filter fine and still be able to be navigated through. 

**Screenshots**
<img width="870" alt="Screen Shot 2021-10-19 at 1 11 43 PM" src="https://user-images.githubusercontent.com/89411550/137976419-ed48bfbd-f2c2-447e-9244-1776ee1b7faf.png">

**Additional Comments**

This doesn't apply to other app installed, such as Istio!
This also doesn't happen from the Monitoring CRD.

**Comment by alexandreLamarre** [comment]
Can't recreate this in either the latest rancher v2.6 / v2.7 and latest rancher monitoring charts for those versions

**Comment by alexandreLamarre** [comment]
Feel free to reopen if this pops again
