### ISSUE TITLE
[Monitoring v2] Stop releasing dependency charts

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#35204]
The monitoring v2 chart has a lot of dependency charts that are pulled into the monitoring main chart when it is generated. Those charts are not user-facing so we will stop releasing them in the `assets/`, `charts/` directory, and `index.yaml` file. 

Here is the list of those charts:
- rancher-grafana
- rancher-kube-state-metrics
- rancher-node-exporter
- rancher-prometheus-adapter

Note:
The `rancher-pushprox` chart still be released as a standalone chart.

**Comment by jiaqiluo** [comment]
### Note for dev-validation 

the validation can be done by checking the rancher/chart:dev-v2.6 branch and comparing it with the release-v2.6 branch
for all sub-charts mentioned in the issue:
-  the `doNotRelease: true` field should be in the chart's `package.yaml` 
- there should be no new version under `charts/`, `assets/`, and the `index.yaml` when comparing dev-v2.6 with release-v2.6 branch

**Comment by brendarearden** [comment]
**Validation: PASSED** 
**Steps Used to validate:**
From https://github.com/rancher/charts/tree/dev-v2.6
1.  Validated that `rancher-grafana` has the `doNotRelease: true` field in the `package.yaml` https://github.com/rancher/charts/blob/dev-v2.6/packages/rancher-grafana/package.yaml#L5.
2.  Validated that there is no new version of `rancher-grafana` by cloning a fresh copy of rancher/charts and running `git diff -G. dev-v2.6 release-v2.6 -- charts/rancher-grafana/rancher-grafana`, ` git diff -G. dev-v2.6 release-v2.6 -- assets/rancher-grafana`. 
3.  Validated that `rancher-kube-state-metrics` has the `doNotRelease: true` field in the `package.yaml` https://github.com/rancher/charts/blob/dev-v2.6/packages/rancher-kube-state-metrics/package.yaml#L5.
4.  Validated that there is no new version of `rancher-kube-state-metrics` by cloning a fresh copy of rancher/charts and running `git diff -G. dev-v2.6 release-v2.6 -- charts/rancher-kube-state-metrics/rancher-kube-state-metrics`, ` git diff -G. dev-v2.6 release-v2.6 -- assets/rancher-kube-state-metrics`. 
5.  Validated that `rancher-node-exporter` has the `doNotRelease: true` field in the `package.yaml` https://github.com/rancher/charts/blob/dev-v2.6/packages/rancher-node-exporter/package.yaml#L5.
6.  Validated that there is no new version of `rancher-node-exporter` by cloning a fresh copy of rancher/charts and running `git diff -G. dev-v2.6 release-v2.6 -- charts/rancher-node-exporter/rancher-node-exporter`, ` git diff -G. dev-v2.6 release-v2.6 -- assets/rancher-node-exporter`. 
7. Validated that `rancher-prometheus-adapter` has the `doNotRelease: true` field in the `package.yaml` https://github.com/rancher/charts/blob/dev-v2.6/packages/rancher-prometheus-adapter/package.yaml#L5.
8. Validated that there is no new version of `rancher-prometheus-adapter` by cloning a fresh copy of rancher/charts and running `git diff -G. dev-v2.6 release-v2.6 -- charts/rancher-prometheus-adapter/rancher-prometheus-adapter`, ` git diff -G. dev-v2.6 release-v2.6 -- assets/rancher-prometheus-adapter`. 
9. Validated that the `index.yaml` does not show new versions of `rancher-grafana`,`rancher-kube-state-metrics`,`rancher-node-exporter` and  `rancher-prometheus-adapter` by running git diff -G. dev-v2.6 release-v2.6 -- index.yaml. The only difference between the index.yaml for these charts were the "created" field which is expected.
