### ISSUE TITLE
[BUG] Deleting a cluster in rancher dashboard doesn't fully remove it

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#35205]
**Describe the bug**

When you delete an RKE1/RKE2 cluster from rancher dashboard for Harvester it will remove the nodes from Harvester, but the last node doesn't appear to be removed on the rancher side. It just says that it's still waiting to be removed. On the Harvester side it is removed though.
**To Reproduce**
1. Create 3 node RKE2 cluster on Harvester through node driver with Rancher
2. Wait fo the nodes to create, but not fully provision
3. Delete the cluster
4. Wait for them to be removed from Harvester
5. Check Rancher cluster management

**Expected behavior**

They should be fully removed from both Rancher and Harvester
**Support bundle**

**Environment:**
 - Harvester ISO version: master-b7b757e9-head
 - Rancher version: v2.6.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160

**Additional context**
Add any other contex
![Greenshot 2021-09-28 07 33 59](https://user-images.githubusercontent.com/83787952/135108378-4de7c776-2294-41fe-9f42-de3613cec030.png)
t about the problem here.
It says that it's waiting for the last node to delete, but since it's already removed from Harvester it doesn't seem to finish. I wonder if it's not catching the d
![Greenshot 2021-09-28 07 32 15](https://user-images.githubusercontent.com/83787952/135108328-2c103348-a6da-4053-ad96-e434b1b101ac.png)
elete, or if it's not properly listing the RKE1/RKE2 nodes

Link to https://github.com/harvester/harvester/issues/1311

**Comment by snasovich** [comment]
@guangbochen , there were a lot of improvements done by @thedadams recently in regards to cluster deletion scenarios . These enhancements should address your scenario and are not available in v2.6.1 release. Any chance you could retest it on the latest v2.6-head?

**Comment by guangbochen** [comment]
Will bump the Rancher version and verify it accordingly, thanks.
