### ISSUE TITLE
Support SSH for V2 (RKE2) provisioned nodes

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#35203]
Currently Rancher CLI's `ssh` command doesn't support V2 (RKE2) provisioned nodes. For example:
```
./rancher ssh sergey-rke2-for-erd-discussion-sergey-rke2-for-erd-discus-2pgnp
FATA[0001] failed to find SSH key for sergey-rke2-for-erd-discussion-sergey-rke2-for-erd-discus-2pgnp
```

This works fine for RKE1 provisioned clusters.

Rancher CLI should be updated to support SSH to nodes of V2 provisioned clusters.

**Comment by thedadams** [comment]
### Root cause
The CLI was looking for nodes with SSH config associated to them. In provisioningv2, the CLI should look for machines.

### What was fixed, or what changes have occurred
Generated clients were added to Rancher and the CLI will look for machines with the name passed if the node doesn't have SSH config associated with it.

### Areas or cases that should be tested
1. Provision an RKE2 cluster from Rancher.
2. Use Rancher CLI v2.6.0-rc1 or higher to ssh one of the nodes.

### What areas could experience regressions?
Using Rancher CLI to SSH to nodes that were provisioned for RKE1 clusters.
1. Provision an RKE1 cluster from Rancher.
2. Ensure that you can use Rancher CLI v2.6.0-rc1 or higher to SSH to one of the nodes.

### Are the repro steps accurate/minimal?
Yes.

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Reproduction**
- rancher version: v2.6-head (e655fd8) 
- ec2 RKE2 cluster
- rancher CLI version: 2.4.13

**Reproduction Steps**
1. From local terminal using rancher CLI, run:
```
$ rancher login <url> --token <bearer token> 
```
2. You will be prompted to select project, this should be your rke2 cluster
3. Now you can get your node info in the cli by running: 
```
$ rancher nodes
```
4. The following command will give you the failure: 
```
rancher ssh <ID/name>
```

**Results**

Following the above steps you will see "FATA[0001] failed to find SSH key for <ID/name>"

**Comment by thedadams** [comment]
Rancher CLI version 2.6.0-rc2 is necessary for this issue. It contains the fixes necessary.

**Comment by Auston-Ivison-Suse** [comment]
**Further Testing**
-Using the new rc here are the commands I ran
```
 1004  ./rancher login https://<url> --token token-d7hqq:k2n6h8kz9p4p82f9585wlm2fzfntws6wp4bbsdkglvjp54ml2prqh5
 1005  ./rancher nodes
 1006  ./rancher ssh <node ID> 
 1007  ./rancher ssh <node ip-address> 
 1008  ./rancher ssh
 1009  ./rancher ssh <node ip-address>  -e
 1010  ./rancher ssh <node ID>
 1011  ./rancher context switch
 1012  ./rancher nodes
 1013  ./rancher ssh <inode p-address>
```
The output for any ssh command ran above is as follows: 

```
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]
```

This isn't the intended result. @thedadams and I will go over this on Monday.

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Validation**
- rancher version: v2.6-head (78b25c3) 
- ec2 RKE2 cluster
- rancher CLI version: v2.6.0-rc2

**Validation Steps**
1. From local terminal using rancher CLI, run:
```
$ rancher login <url> --token <bearer token> 
```
2. You will be prompted to select project, this should be your rke2 cluster
3. Now you can get your node info in the cli by running: 
```
$ rancher nodes #Note the ID and name of node to run a command later. 
```
4. The following command will allow you to successfully ssh into the node
```
rancher ssh <ID/name> -e #using the e to specify that you are using ssh externally
```

**Results**
Success or welcome message clarifying you've been able to use ssh to gain access to a node.

**Sanity Tests**
1. Using ID to SSH 
2. Using host name (currently listed as the internal ip address but is in the process of changing that)
