### ISSUE TITLE
rancher-logging: runAsNonRoot non-numeric user (fluent) - rancher-logging-fluentd - rke2

### ISSUE THREAD

**Issue by chickeaterbanana** [rancher/rancher#35210]
After installing a rke2 cluster wit cis-1.6 the podsecuritypolicy prevents successful installation of rancher-logging.

I have to fix the statefulset `rancher-logging-fluentd` manually for the container fluentd:
```
securityContext:
  runAsNonRoot: true
  runAsUser: 100
```

Now everything seems to work as expected.

Log output:
```
cattle-logging-system      60m         Warning   Failed                   pod/rancher-logging-fluentd-0                        Error: container has runAsNonRoot and image has non-numeric user (fluent), cannot ve
rify user is non-root (pod: "rancher-logging-fluentd-0_cattle-logging-system(6fb4268f-7eac-405e-93be-a39d879c5378)", container: fluentd
```

**Comment by MKlimuszka** [comment]
Reference: SURE-3893

**Comment by eliyamlevy** [comment]
Hello, I haven't been able to reproduce the issue. Any way I can get some more info?
