### ISSUE TITLE
New install failed

### ISSUE THREAD

**Issue by yvad75** [rancher/rancher#3521]
I'm trying to install a newly installed machine.
I used the latest server version available on the docker hub. et copyied the command for agent creation from it.
Its seems to have a problem in apply.sh/config.sh but I dont get why :/

`INFO: Starting agent for C120B22CF7FB0B49F23D
INFO: Access Key: C120B22CF7FB0B49F23D
INFO: Config URL: http://10.195.205.8:8080/v1
INFO: Storage URL: http://10.195.205.8:8080/v1
INFO: API URL: http://10.195.205.8:8080/v1
INFO: IP: 10.195.205.8
INFO: Port:
INFO: Required Image: rancher/agent:v0.8.2
INFO: Current Image: rancher/agent:v0.8.2
INFO: Using image rancher/agent:v0.8.2
INFO: Downloading agent http://10.195.205.8:8080/v1/configcontent/configscripts
INFO: Updating configscripts
INFO: Downloading http://10.195.205.8:8080/v1//configcontent//configscripts current=
INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/apply.sh
bootstrap.EZAYJdt/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/config.sh: line 222: ./apply.sh: Permission denied
bootstrap.EZAYJdt/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/config.sh: line 222: ./apply.sh: Permission denied
`

line 222 seems to be this one
` ./apply.sh "${opts[@]}" || CATTLE_SCRIPT_DEBUG=true ./apply.sh "${opts[@]}"`

Does anyone have a hint of my problem ?

**Comment by deniseschannon** [comment]
What OS are you running?

**Comment by deniseschannon** [comment]
Do you have SELinux or AppArmor enabled? Try disabling them if enabled, rebooting and testing again.

Do you have docker running on a mount that has `noexec` set which prevents execution of binaries?

**Comment by yvad75** [comment]
I'm on RHEL and you're right! my /var FS has a no exec attribute :+1: 
Thank you!
