### ISSUE TITLE
[Forward-port][rancher-pushprox] duplicate label in ServiceMonitor resource

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#35217]
forward port of https://github.com/rancher/rancher/issues/35216

**Comment by jiaqiluo** [comment]
This will be fixed after https://github.com/rancher/rancher/issues/34577 is done

**Comment by jiaqiluo** [comment]
Can be tested in the rancher-monitoring  `100.1.0+up19.0.3`
---
### Root cause
a duplicate label in ServiceMonitor resource in the chart `rancher-pushprox` which is used as the base for multiple sub-charts of rancher-monitoring 

### What was fixed, or what changes have occurred 
remove the duplicate label 

### Areas or cases that should be tested 
the general functionality of the monitoring chart 

### What areas could experience regressions? 
the monitoring chart,
but technically the change should not introduce any regression since it just drops a duplicated label 

### Are the repro steps accurate/minimal?
n/a

**Comment by jmcsagdc** [comment]
I'm having difficulty getting a repro where I can see these values duplicated in the servicemonitor objects' yaml

Here is a comparison between 2.6.3 and 2.5.11 (where I expected to see the duplication in the "release" K:V pairs). 

Can someone point me to a specific place I can see the yaml with duplicated attributes?

![2021-11-23_15-18-20](https://user-images.githubusercontent.com/15971368/143144709-83a0399a-9195-4b91-bce9-db4da68fa895.jpg)

**Comment by jmcsagdc** [comment]
Reproduced in the older version of the chart 0.1.0
Verified the duplication is removed in newer version of the chart 100.0.1

To see the changes, go to the github repo for rancher/charts and click Go to file. Search for "rancher-pushprox.tgz" and download the various .tgz tarballs. (see screenshot)

![repo-search](https://user-images.githubusercontent.com/15971368/143940562-d5639e0a-7a98-4ee9-8395-917856ba2c8d.jpg)

Then `helm template rancher-monitoring <tarball>` and look for the duplications or their removals (see screenshot)

![fixed](https://user-images.githubusercontent.com/15971368/143939874-e0b3f168-423c-4a45-b374-258f5c5b3314.jpg)
