### ISSUE TITLE
Logging should expose all fluentbit and fluentd options in the values.yaml

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#35215]
We are consistently adding new options to our values file to expose fluentbit and fluend options. We should expose a key in values that is the full fluentbit or fluentd spec and then merge in the rancher-logging specific options.  This will give users greater flexibility when configuring features we did not think of exposing while still allowing rancher to configure logging.

Related issues:
https://github.com/rancher/rancher/issues/35213
https://github.com/rancher/rancher/issues/35212
https://github.com/rancher/rancher/issues/35211

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6-head Commit ID 638b29a`

`Logging exposes all fluentbit and fluentd options in the values.yaml`

1. Created an `rke1 ec2 cluster` 
2. installed logging
3. set `loggingOverlay.spec.fluentbit.grace=1` in logging yaml file in step 2 of logging install
4. verified logs flow to output elastic search
5. Created an` rke2 digital ocean cluster` 
6. installed logging
7. set `loggingOverlay.spec.fluentbit.grace=1` in logging yaml file in step 2 of logging install
8. verified logs flow to output elastic search

**Comment by sowmyav27** [comment]
Reopening to test a few more scenarios

**Comment by ronhorton** [comment]
**PASS** verified in `2.6-head Commit ID f487c88`
1. Installed logging `100.0.0 3.15.00`
2. edited yaml: loggingOverlay.spec.fluentbit.grace=1 (newly exposed value)
3. configured cluster output & flow
4. verified logs were flowing to the elastic search output
![Screen Shot 2021-10-29 at 11.07.57 AM.png](https://zube.io/files/rancher/2ae34efb8ab225182921882a68c92659-screen-shot-2021-10-29-at-11-07-57-am.png)

**Upgrade Test** 
1. upgraded released chart version `100.0.1 3.12.00` through rancher to chart `100.0.1 2.15.00`
2. edited yaml: loggingOverlay.spec.fluentbit.grace=1 (newly exposed value)
3. verified logs resumed flowing after update

**Clusters types tested**
1. GKE cluster
2. DO RKE2 cluster
3. K3S cluster
4. EC2 RKE2 cluster
5. DO RKE1 cluster
6. Custom cluster
7. EKS cluster
8. Custom cluster with k8s version 1.22.3
