### ISSUE TITLE
[Feature Charts] Stop Releasing non-user-facing dependency charts 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#35222]
Currently in the `rancher/charts:dev-v2.6` branch, all charts that are listed under the `packages/` directory are released as induvial charts. Some of them are actually dependency charts of another chart and never be used as an independent chart. We should stop releasing those charts. 

The benefits are:
- no new version of those dependency charts will be released in the helm repo anymore
- reduce the overall size of the repo
- reduce a lot of maintaining work on the released charts, such as changing the rancher-version annotation 
- makes the PR for new feature charts smaller than what it is today
- no confusion on the user side for those hidden-in-UI-but-shown-in-command-line charts 

We can achieve this by adding the field `doNotRelease: true` to the `package.yaml` of those charts. This option tells the charts-build-scrips to ignore the chart when it makes charts but does not affect it to generate and put the dependency charts into the main chart. 

----------

- [x] The following sub-charts for `rancher-monitoring` will not be released as individual charts:

- rancher-grafana
- rancher-node-exporter
- rancher-kube-state-metrics
- rancher-prometheus-adapter
- rancher-windows-exporter

- [x] The following sub-charts for `rancher-istio` will not be released as individual charts:
- rancher-kiali-server
- packages/rancher-tracing

- [x] The following sub-charts for `rancher-alerting-drivers`  will not be released as individual charts:
- rancher-prom2teams
- rancher-sachet

**Comment by jiaqiluo** [comment]
Here is the issue that tracks the effort on rancher-monitoring chart https://github.com/rancher/rancher/issues/35204

**Comment by jiaqiluo** [comment]
### Note for dev-validation 

the validation can be done by checking the rancher/chart:dev-v2.6 branch and comparing it with the release-v2.6 branch
for all sub-charts mentioned in the issue:
-  the `doNotRelease: true` field should be in the chart's `package.yaml` 
- there should be no new entry under charts/, assets., and the index.yaml when comparing dev-v2.6 with release-v2.6 branch

**Comment by brendarearden** [comment]
Note: Validation for `rancher-grafana`,`rancher-node-exporter`,`rancher-kube-state-metrics`,`rancher-prometheus-adapter` was completed here: https://github.com/rancher/rancher/issues/35204#issuecomment-984168202

**Validation: PASSED** 
**Steps Used to validate:**
From https://github.com/rancher/charts/tree/dev-v2.6
1.  Validated that `rancher-windows-exporter` has the `doNotRelease: true` field in the `package.yaml` https://github.com/rancher/charts/blob/dev-v2.6/packages/rancher-windows-exporter/package.yaml#L3.
2.  Validated that there is no new version of `rancher-windows-exporter` by cloning a fresh copy of rancher/charts and running `git diff -G. dev-v2.6 release-v2.6 -- charts/rancher-windows-exporter/rancher-windows-exporter`, ` git diff -G. dev-v2.6 release-v2.6 -- assets/rancher-windows-exporter`. 
3.  Validated that `rancher-kiali-server` has the `doNotRelease: true` field in the `package.yaml` https://github.com/rancher/charts/blob/dev-v2.6/packages/rancher-kiali-server/package.yaml#L3.
4.  Validated that there is no new version of `rancher-kiali-server` by cloning a fresh copy of rancher/charts and running `git diff -G. dev-v2.6 release-v2.6 -- charts/rancher-kiali-server/rancher-kiali-server`, ` git diff -G. dev-v2.6 release-v2.6 -- assets/rancher-kiali-server`. 
5.  Validated that `rancher-tracing` has the `doNotRelease: true` field in the `package.yaml` https://github.com/rancher/charts/blob/dev-v2.6/packages/rancher-tracing/package.yaml#L3.
6.  Validated that there is no new version of `rancher-tracing` by cloning a fresh copy of rancher/charts and running `git diff -G. dev-v2.6 release-v2.6 -- charts/rancher-tracing/rancher-tracing`, ` git diff -G. dev-v2.6 release-v2.6 -- assets/rancher-tracing`. 
7. Validated that `rancher-prom2teams` has the `doNotRelease: true` field in the `package.yaml` https://github.com/rancher/charts/blob/dev-v2.6/packages/rancher-prom2teams/package.yaml#L5.
8. Validated that there is no new version of `rancher-prom2teams` by cloning a fresh copy of rancher/charts and running `git diff -G. dev-v2.6 release-v2.6 -- charts/rancher-prom2teams/rancher-prom2teams`, ` git diff -G. dev-v2.6 release-v2.6 -- assets/rancher-prom2teams`. 
9. Validated that `rancher-sachet` has the `doNotRelease: true` field in the `package.yaml` https://github.com/rancher/charts/blob/dev-v2.6/packages/rancher-sachet/package.yaml#L3.
10. Validated that there is no new version of `rancher-sachet` by cloning a fresh copy of rancher/charts and running `git diff -G. dev-v2.6 release-v2.6 -- charts/rancher-sachet/rancher-sachet`, ` git diff -G. dev-v2.6 release-v2.6 -- assets/rancher-sachet`. 
11. Validated that the `index.yaml` does not show new versions of `rancher-windows-exporter`,`rancher-kiali-server`,`rancher-tracing` `rancher-prom2teams` and  `rancher-sachet` by running `git diff -G. dev-v2.6 release-v2.6 -- index.yaml`. The only difference between the index.yaml for these charts was the "created" field which is expected.
