### ISSUE TITLE
Send resource.change event when host.info is updated

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#3523]
Would be nice to get a change event when the agent updates the `info` section of a host or the hostname so I could show the memory/loadavg/cpu usage and have it update ever.

**Comment by alena1108** [comment]
@vincent99 the fix is in, could you check if it works for you?

**Comment by vincent99** [comment]
@alena1108 I don't think this is working.. I see a new change event every 2 minutes, and the quantity of them match how many hosts I have, but the change is for `resourceType: docker` and it has no useful info (`data`) in it.

```
{
  "id": "a0513a91-0c18-4bd3-93df-d05daf4a0fc3",
  "name": "resource.change",
  "replyTo": null,
  "resourceId": "1d3",
  "resourceType": "docker",
  "publisher": null,
  "transitioning": null,
  "transitioningMessage": null,
  "transitioningInternalMessage": null,
  "previousIds": null,
  "previousNames": null,
  "data": null,
  "time": 1458323656472,
  "timeoutMillis": null,
  "transitioningProgress": null,
  "context": null
}
```

**Comment by vincent99** [comment]
Looks good now
