### ISSUE TITLE
OpenLDAP integration only finding groups despite valid user config

### ISSUE THREAD

**Issue by brtduvally** [rancher/rancher#35244]
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version RKE1
- Proxy/Cert Details: Behind f5 LTM, own cert from external CA

**Information about the Cluster**
- Kubernetes version: v1.20.4
- Cluster Type (Local/Downstream): Local
 
**Describe the bug**
OpenLDAP search to add members only finding groups, not users.  

**To Reproduce**
Configure OpenLDAP with any ObjectClass and user search fails. Group searches succeed and only those results are available.

**Result**
Result for searchUser query fails with `ldap IsType failed to determine if object is type: inetOrgPerson`
Result for searchGroup query succeeds and provides list.

```
2021/10/21 18:01:38 [DEBUG] shibboleth searchUser query: (&(objectClass=inetOrgPerson)(|(uid=test3*)))
2021/10/21 18:01:38 [DEBUG] Triggering auth refresh on user-XXXXX
2021/10/21 18:01:38 [DEBUG] Skipping refresh for user-XXXXX due to max-age
2021/10/21 18:01:39 [DEBUG] Wrote ping
2021/10/21 18:01:40 [DEBUG] Wrote ping
2021/10/21 18:01:40 [DEBUG] Wrote ping
2021/10/21 18:01:40 [DEBUG] Wrote ping
2021/10/21 18:01:40 [DEBUG] Wrote ping
2021/10/21 18:01:41 [DEBUG] Wrote ping
2021/10/21 18:01:43 [DEBUG] shibboleth searchGroup query: (&(objectClass=XXXXXgroup)(XXXXXgrouprdn=*test3*)) scope: shibboleth_group
2021/10/21 18:01:43 [DEBUG] ldap IsType failed to determine if object is type: inetOrgPerson
2021/10/21 18:01:43 [DEBUG] ldap IsType found object of type XXXXXgroup
2021/10/21 18:01:43 [DEBUG] ldap IsType failed to determine if object is type: inetOrgPerson
2021/10/21 18:01:43 [DEBUG] ldap IsType found object of type XXXXXgroup
```

**Expected Result**
The searchUser query is a valid LDAP query and should provide many results. It should populate the list of users available to add as members. Groups matching the searchGroup are incidental.

**Comment by hectoralicea** [comment]
I'm seeing many issues like this with `ldap IsType failed to determine if object is type: inetOrgPerson"` but not seeing any resolutions.  Has anyone with this issue gotten OpenLDAP to work?  

I have AD working as a reference, but not OpenLDAP which is using Project 389 LDAP underneath.

**Comment by Martin-Weiss** [comment]
@hectoralicea  - do your objects / users have the class inetOrgPerson?

**Comment by brtduvally** [comment]
@Martin-Weiss I can't speak for @hectoralicea , but mine do.

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss I can't speak for @hectoralicea , but mine do.

Could you share a ldif export of a user and a group with all their attributes? In my cases I always using 389ds instead of openLDAP and there it works  like a charm...

**Comment by hectoralicea** [comment]
> @hectoralicea - do your objects / users have the class inetOrgPerson?

yes it does.   Here's my output.  Search for the same error you had:
`ldap IsType failed to determine if object is type: inetOrgPerson`
``` 
2023/05/10 18:26:56 [DEBUG] Triggering auth refresh on user-mfsfp
2023/05/10 18:26:56 [DEBUG] Skipping refresh for user-mfsfp due to max-age
2023/05/10 18:26:56 [DEBUG] Now generating Ldap token
2023/05/10 18:26:56 [DEBUG] Now creating Ldap connection
2023/05/10 18:26:56 [DEBUG] Binding service account username password
2023/05/10 18:26:56 [DEBUG] Binding username password
2023/05/10 18:26:56 [DEBUG] ldap IsType found object of type inetOrgPerson
2023/05/10 18:26:56 [DEBUG] getPrincipals: user attributes: [0xc00a63f200 0xc00a63f240 0xc00a63f280 0xc00a63f2c0] 
2023/05/10 18:26:56 [DEBUG] SearchResult memberOf attribute {[cn=REMEDY,ou=SAR_GROUPS,ou=Groups,o=DAASC,dc=XXX,dc=XXX cn=Contractor,ou=SAR_GROUPS,ou=Groups,o=DAASC,dc=XXX,dc=XXX cn=RANCHERADMIN,ou=SAR_GROUPS,ou=Groups,o=DAASC,dc=XXX,dc=XXX cn=RANCHER_BG_DAAS_APIGW,ou=SAR_GROUPS,ou=Groups,o=DAASC,dc=XXX,dc=XXX]}
2023/05/10 18:26:56 [DEBUG] ldap IsType found object of type inetOrgPerson
2023/05/10 18:26:56 [DEBUG] ldap IsType found object of type inetOrgPerson
2023/05/10 18:26:56 [DEBUG] Ldap: Query for pulling user's groups: (&(objectClass=groupOfUniqueNames)(|(entryDN=cn=REMEDY,ou=SAR_GROUPS,ou=Groups,o=DAASC,dc=XXX,dc=XXX)(entryDN=cn=Contractor,ou=SAR_GROUPS,ou=Groups,o=DAASC,dc=XXX,dc=XXX)(entryDN=cn=RANCHERADMIN,ou=SAR_GROUPS,ou=Groups,o=DAASC,dc=XXX,dc=XXX)(entryDN=cn=RANCHER_BG_DAAS_APIGW,ou=SAR_GROUPS,ou=Groups,o=DAASC,dc=XXX,dc=XXX)))
2023/05/10 18:26:56 [DEBUG] ldap IsType failed to determine if object is type: inetOrgPerson
2023/05/10 18:26:56 [DEBUG] ldap IsType found object of type groupOfUniqueNames
2023/05/10 18:26:56 [DEBUG] ldap IsType failed to determine if object is type: inetOrgPerson
2023/05/10 18:26:56 [DEBUG] ldap IsType found object of type groupOfUniqueNames
2023/05/10 18:26:56 [DEBUG] ldap IsType failed to determine if object is type: inetOrgPerson
2023/05/10 18:26:56 [DEBUG] ldap IsType found object of type groupOfUniqueNames
2023/05/10 18:26:56 [DEBUG] ldap IsType failed to determine if object is type: inetOrgPerson
2023/05/10 18:26:56 [DEBUG] ldap IsType found object of type groupOfUniqueNames
2023/05/10 18:26:57 [DEBUG] Wrote ping
2023/05/10 18:26:57 [DEBUG] Wrote ping
```

**Comment by hectoralicea** [comment]
> Could you share a ldif export of a user and a group with all their attributes? In my cases I always using 389ds instead of openLDAP and there it works like a charm...

yes, I'm also using Project 389 LDAP.

Can you provide an example ldapsearch call or whatever CLI call is needed to get the ldif export of a user and a group with all their attributes?

**Comment by Martin-Weiss** [comment]
This is really strange. Here is what I have on 389ds where the user and group search seems to be working as expected:

User:

```
dn: uid=user01,ou=users,dc=suse
objectClass: inetOrgPerson
cn: user01
uid: user01
mail: user01@suse.com
sn: user01
givenName: user01
userPassword: <removed>
```

Group:

```
dn: cn=rke-test-admins,ou=groups,dc=suse
objectClass: groupOfUniqueNames
cn: rke-test-admins
description: Group that gets admin rights on the cluster rke-test
uniqueMember: uid=mweiss,ou=users,dc=suse
uniqueMember: uid=admin,ou=users,dc=suse
uniqueMember: uid=user01,ou=users,dc=suse
```

**Comment by hectoralicea** [comment]
> This is really strange.

what is strange about it?

**Comment by Martin-Weiss** [comment]
> > This is really strange.
> 
> what is strange about it?

That it works with "my" user+group on 389ds and not with openLDAP and I can not see the obvious difference... but maybe I am overseeing something..

**Comment by hectoralicea** [comment]
Here are my settings.  Please advise if you see anything wrong in the settings.
![OpenLdapSetup1](https://github.com/rancher/rancher/assets/12519400/4efb76ce-b08f-4c53-acd9-ddd2560add46)
![OpenLdapSetup2](https://github.com/rancher/rancher/assets/12519400/b46cf254-123a-4183-8510-bc89b73f7b68)
![OpenLdapSetup3](https://github.com/rancher/rancher/assets/12519400/fe8bd4f8-4b40-4810-b5d0-3b18841f06c5)

**Comment by brtduvally** [comment]
@hectoralicea No. I was using Project 389 LDAP for auth prior to v2.5.9, but had to switch to AD to get groups working again. We have both running in parallel.

I'm on v2.6.8 now but haven't tested it again to see if it's working there.

**Comment by Martin-Weiss** [comment]
This is how it works for me with 389ds:

<img width="1519" alt="grafik" src="https://github.com/rancher/rancher/assets/13362573/f0214b51-691b-41c9-829c-b08afe65e763">

**Comment by hectoralicea** [comment]
> This is how it works for me with 389ds:
> 

I have the same configuration now and it still does NOT work.  

what does this error mean from a 389ds perspective?

_Rancher needs a service account that has read-only access to all of the domains that will be able to login, so that we can determine what groups a user is a member of when they make a request with an API key._

![image](https://github.com/rancher/rancher/assets/12519400/442872a9-24b3-41cb-9f29-5bc2ec8ed938)

**Comment by hectoralicea** [comment]
I think I got this working.  Very interesting.  I just make sure I included all the roles if there are overlapping roles.  Still testing.  Will update when I confirm.

**Comment by atsai1220** [comment]
> still having this problem, even with a later version. any update on anyone able to get group membership based privileges to work with Rancher?

I cannot seem to get this to work as well and my openldap configuration seems to be correct based on documentation.

For example, this is the group
```
dn: cn=venus-dev,ou=Groups,ou=venus,ou=Environments,dc=viasat,dc=io
objectClass: groupOfNames
cn: vclusters-nebula-dev
member: uid=one,ou=People,dc=viasat,dc=io
owner: cn=admins,ou=Groups,ou=venus,ou=Environments,dc=viasat,dc=io
```

And here is the user output
```
# xming, People, viasat.io
dn: uid=one,ou=People,dc=viasat,dc=io
objectClass: inetOrgPerson
cn: One Last
uid: one
memberOf: cn=venus-dev,ou=Groups,ou=venus,ou=Environments,dc=viasat,dc=io
```

And here is the schema table
![image](https://github.com/rancher/rancher/assets/14171643/c4623da0-bbda-42a0-b4ac-e524dd9be9ae)

**Comment by hectoralicea** [comment]
I also still cannot get this to work with OpenLDAP.  
Its been a real pain managing by the user rather than by the group.
