### ISSUE TITLE
ability to configure agent deployments per cluster

### ISSUE THREAD

**Issue by jesseagonzalez** [rancher/rancher#35243]
**Is your feature request related to a problem? Please describe.**

The specific use case that lead to this feature request was the following: 

AWS - `EKS clusters` utilized two node groups. One of the node groups leveraged EC2 `on-demand` instances and the other - `spot` instances (within auto-scaling groups).  The `on-demand` node group nodes were assigned a custom `taint` (i.e., `platform/node-lifecycle=NoSchedule`) to ensure that only specific application workloads were being scheduled on those particular nodes.  Alternatively, for the more ephemeral / least critical application workloads, the preference was to schedule them onto the `spot` instances / node-groups.

Therefore, within the default configuration, when the `cattle-cluster-agent` pods were being scheduled, they were always getting assigned `spot` instance because of the custom `taint` being added (above), causing various flavors of instability within the cluster instance of Rancher UI manager.

https://rancher.com/docs/rancher/v2.5/en/cluster-provisioning/rke-clusters/rancher-agents/#scheduling-rules

**Describe the solution you'd like**

The solution would be to provide a method for setting custom parameters that allow ability to over-ride `cattle-cluster-agent` settings when deploying rancher via any of the supported deployment options (i.e., `helm`)

**Describe alternatives you've considered**

Providing a `taint` directly onto the target "on-demand" nodes of "cattle.io/cluster-agent=true:NoSchedule", given that there is already an existing toleration for that scenario

Outside of doing a `patch` of the cattle-cluster-agent deployment directly, or leveraging gitops solutions to synchronize diffs from underlying git repo (i.e., via kustomize/k8s manifests), there was no alternative solution that would guarantee that somewhere down the line (that we could think of), a subsequent process wouldn't override said patch (i.e., rancher upgrade) and blow away updates.

**Additional context**

**Comment by mddamato** [comment]
Potential workaround: https://rancher.com/docs/rancher/v2.5/en/cluster-provisioning/rke-clusters/rancher-agents/#scheduling-rules

Use the node-label `cattle.io/cluster-agent=true`
