### ISSUE TITLE
Integrate our drone CI into upstream's Github Workflow CI in our NGINX fork

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#35246]
We currently run upstream's CI and our drone CI concurrently in our [rancher/ingress-nginx](https://github.com/rancher/ingress-nginx) fork. Our CI was added a while back to fix problems around building the nginx image that came up when upstream's build process changed (More on this [here](https://github.com/rancher/ingress-nginx/pull/34)). Our CI should be integrated into their Github Workflow CI to avoid future problems around testing and confusion overall.

**Comment by rayandas** [comment]
Need a new tag so that QA can test it.

**Comment by samkulkarni20** [comment]
> @PennyScissors As this PR is merged, do we need QA testing for this? Or is the CI tasks run by the PRs enough to say that the changes work? If we need QA testing, what would the testing process look like. Do we need to update KDM data?

@snasovich @jiaqiluo Since this is a Team2 issue, can you suggest on above question?

**Comment by snasovich** [comment]
@samkulkarni20 , thanks for pinging me on this.
We may not have full understanding of the issue on Team 2 yet, so if @PennyScissors has any suggestions that would be great.
@kinarashah @jiaqiluo , or maybe this is something you can help with?

**Comment by PennyScissors** [comment]
@snasovich Upstream had their own CI separate from ours, so this issue is to consolidate the CIs by adding ours as a step in theirs. We only need to test that our CI is running along with upstream's CI because we don't have any tests of our own (we run upstream's tests). This can be verified by QA or a dev in a fork, should be pretty simple.
cc @kinarashah @jiaqiluo

**Comment by jiaqiluo** [comment]
Guess what, @kinarashah just made a PR in that repo, which can be used to validate the changes in the CI: 
- the PR should trigger related Actions and those Actions should pass
- cutting a new release should trigger related Actions and those Actions should pass

**Comment by rayandas** [comment]
Right @jiaqiluo. I see rancher-validate and rancher-build already passed on that PR.
When it'll be merged, after pushing a new tag the release CI should trigger and that should push the new image.

**Comment by kinarashah** [comment]
@rayandas I merged and pushed a new tag, that is failing because it's not able to tag docker image: 
```
Building targets for arm64, generated targets in rootfs/bin/arm64 directory.
Building targets for amd64, generated targets in rootfs/bin/amd64 directory.
Error: Cannot perform an interactive login from a non TTY device
time="2022-02-22T22:49:05Z" level=fatal msg="exit status 1"
```
https://github.com/rancher/ingress-nginx/runs/5295871229?check_suite_focus=true 
could you take a look?

**Comment by rayandas** [comment]
Ah! I think I know the reason. Github actions in not able to login to Rancher's Docker Hub using these secrets. https://github.com/rancher/ingress-nginx/blob/nginx-1.1.x-fix/.github/workflows/release.yaml#L16-L17
Github actions uses repository secrets which should be set under `<repo>/settings/secrets/actions`

**Comment by rayandas** [comment]
@kinarashah I revert back the changes, and merged the PR. Can you please try tagging a new version now?

**Comment by rayandas** [comment]
As per EIO, we don't support pushing images on Docker hub using GitHub Actions. So we need to stick to Drone CI as per our conversation on Slack. 
Closing this issue.
