### ISSUE TITLE
Cannot create a projectwide registry-secret

### ISSUE THREAD

**Issue by PNe-ins** [rancher/rancher#35251]
Hi,

I'm discovering a bug in the UI of the new Rancher version 2.6:
It is not possible to create projectwide registry-secrets anymore. If you try to create a registry-secret, you have to choose a specific namesapce.

**To Reproduce**
Follow the instructions "Creating a Registry" on [https://rancher.com/docs/rancher/v2.6/en/k8s-in-rancher/registries/](https://rancher.com/docs/rancher/v2.6/en/k8s-in-rancher/registries/)

**Result**
It is not possible to choose a scope

**Expected Result**
"Your secret is added to the project or namespace, depending on the scope you chose." => Expected to create a secret in a project

**Screenshots**
![grafik](https://user-images.githubusercontent.com/58724452/138423267-d0fadc2f-64e9-4dfb-a567-2972ae1801ac.png)

I would appreciate any help resolving this issue.

**Comment by victord-huma** [comment]
@jtravee Is this a bug or outdated documentation?  I thought it is the latter.

**Comment by jtravee** [comment]
Hi @victord-huma, this will be clarified by the devs. I just wanted to link the two issues so that they could be addressed at the same time once the determination was made. Thank you for the heads-up, will keep you posted!

**Comment by jtravee** [comment]
@victord-huma, I have validated that this was an update for 2.6 (not a bug); adjusted docs to reflect this. Thank you for your contribution!
