### ISSUE TITLE
Using PL support, window title still says Rancher

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3525]
Version - master UI 2/4

Steps:
1.  Change  /v1/settings/ui.pl in the API to something other than `rancher`
2.  Reopen the app

Results:  Browser tab still says Rancher
![image](https://cloud.githubusercontent.com/assets/11514927/12828296/3551ace2-cb41-11e5-8087-b87322afd441.png)

Expected: Should have changed to whatever you entered

**Comment by vincent99** [comment]
Changed to "UI" until the setting can be read, then the name from the PL setting.

**Comment by tfiduccia** [comment]
version - master 3/2
Verified fixed
