### ISSUE TITLE
When "Configure who should be able to login and use Rancher" is restrictive with Keycloak SAML provider - additional listed users cannot log in

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#35266]
**Summary:**

If you set up the Keycloak SAML provider and restrict users via either of the two below options - any additional users you list can never log in.
- Allow members of clusters and projects, plus authorized users & groups
- Restrict access to only the authorized users & groups

I reproduced this on v2.6.1 and v2.6-head `c0edb9b` (10/22/21).
I CANNOT REPRODUCE THIS ON OTHER AUTH PROVIDERS SUCH AS:
Active Directory (LDAP)
Github (OAuth)

-----

**Environment:**
Rancher version: v2.6.1 or latest v2.6-head `c0edb9b` (10/22/21).
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a

**Steps to Reproduce:**
1. Set up Keycloak (SAML) auth provider
2. After enabling it, set "Allow members of clusters and projects, plus authorized users & groups" option and add one or more additional users to the "Authorized Users & Groups" list. The PUT request is successfully sent and the allowedPricipalIds list appears correct. (See additional info below though)
3. Log out. Close the browser session so your login isn't cached. Log in as one of the additional users you added.
4. The login will always fail. You will pass the keycloak auth page, but when redirected to Rancher you will see the login screen has a 403 error. You will also observe `[ERROR] SAML: User does not have access <nil>` in the Rancher Server logs.
![image](https://user-images.githubusercontent.com/45179589/138530957-e3f112ad-7e0f-427d-bb10-86d38bc6d571.png)

5. Try again, but this time as the admin keycloak user, set the "Restrict access to only the authorized users & groups" option with the same user list. Save. This too will not work, when you attempt to login as any of those additionally listed users they never can fully log in to rancher. They again pass the Keycloak login fine, but when redirected to Rancher they see a 403 error in the UI.
 
**Expected Result:**
I expected any additional users listed in the "Authorized Users & Groups" list to indeed be able to login to Rancher when using the Keycloak SAML provider.

**Actual Result:**
None of the additional users listed in the "Authorized Users & Groups" list are able to login to Rancher when using the Keycloak SAML provider.  I could not reproduce with Active Directory (LDAP) provider or Github (OAuth) provider. I did not try other providers.

**Additional Info:**
I notice that when I add additional users they do not have the "@domain.com" appended to the end of their usernames. I suspect this doesn't matter but I thought I should mention it. Here is the relevant snippet of my PUT request when I saved my "Authorized Users & Groups" setting for either the "Allow members of clusters and projects, plus authorized users & groups" option or "Restrict access to only the authorized users & groups" option. 

```
"allowedPrincipalIds": ["keycloak_user://qauser1@domain.com", "keycloak_user://qauser2", "keycloak_user://qauser3"]
```

Note these additional users "qauser2" and "qauser3" can log in just fine when we set the "Allow any valid user" option. This is the only way they can log in. I did not try adding users as cluster owners/members or project owners/members -- I should not have to if they are added to the "Authorized Users & Groups" list.

**Comment by cbron** [comment]
Bumping this
