### ISSUE TITLE
[rancher-monitoring] Disable the testFramework in Grafana

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#35288]
Rancher-monitoring `100.0.0+up16.6.0` has the default value for `grafana.testFramework.enable` `true`, as the result, a set of configMap, role, rolebinding, psp and etc. are created but never be used.
To avoid creating those unused resources, we should set the default value to be false. 

the line in question: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-monitoring/rancher-monitoring/100.0.0%2Bup16.6.0/charts/grafana/values.yaml#L99-L101

**Comment by jiaqiluo** [comment]
Can be tested in the rancher-monitoring  `100.1.0+up19.0.3`
---
### Root cause
Rancher-monitoring 100.0.0+up16.6.0 has the default value: grafana.testFramework.enable=true

### What was fixed, or what changes have occurred
set the default value of the above field false

### Areas or cases that should be tested? 
install monitoring, the pod, configMap, role, rolebinding, PSP, service account which name is `rancher-monitoring-grafana-test`  should not be created in the cluster

### What areas could experience regressions? 
n/a

### Are the repro steps accurate/minimal?
 n/a

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Reproduction**
- rancher version: v2.6.2
- Monitoring version: v100.0.0+up16.6.0

**Steps for Reproduction**
1. Install monitoring onto cluster.
2. navigate cluster --> Installed Apps --> rancher-monitoring --> Values Yaml
3. Check for the Test Framework to be enabled, which looks like the following:
```
testFramework:
    enabled: true
    image: rancher/mirrored-bats-bats
    imagePullPolicy: IfNotPresent
```
**Further Checks**
Checked for the installation in all the following locations via the ui

_ConfigMap_
![TestFrame Config.png](https://zube.io/files/rancher/12c33b4316c814e00c830155844aa089-testframe-config.png)
_Role_
![TestFrameRole.png](https://zube.io/files/rancher/79cbd33a42771bf2d3ecfcbde84e98a7-testframerole.png)
_ServiceAccount_
![TestFrameworkServiceAccount.png](https://zube.io/files/rancher/3325bd0e2358b6beb8839779e4cd8f01-testframeworkserviceaccount.png)
_PodSecurityPolicy_
![TestFrameworkPSP.png](https://zube.io/files/rancher/0933efbe8f410380482c2a9af94dba3b-testframeworkpsp.png)![TestFrameworkSecrets.png](https://zube.io/files/rancher/4089d54479bb7177809a771fe137603d-testframeworksecrets.png)
_Rolebinding_
![TestFrameworkRolebinding.png](https://zube.io/files/rancher/0326a6ca810a8c1572293c2e68d753a7-testframeworkrolebinding.png)
_Secrets_
![TestFrameworkSecrets.png](https://zube.io/files/rancher/4089d54479bb7177809a771fe137603d-testframeworksecrets.png)

**Setup For Validation**
- Rancher Version: v2.6-head(4375161)
-Monitoring Version: v100.1.0+up19.0.3

**Steps for Validation**
1. Install monitoring onto cluster.
2. navigate cluster --> Installed Apps --> rancher-monitoring --> Values Yaml
3. Check for the Test Framework to be disabled, which looks like the following screenshot:
![TestFrameworkValid.png](https://zube.io/files/rancher/ad4226091c5ff69d506b223de2ccf642-testframeworkvalid.png)

**Sanity Checks**
Went through each resource that was mentioned and that I had found any grafana test framework and made sure there was nothing installed.
