### ISSUE TITLE
Rancher 2.6.1 : RKE2 downstream clusters jobs stucked because of global restricted pod security policy

### ISSUE THREAD

**Issue by alexdga** [rancher/rancher#35282]
**Rancher Server Setup**
- Rancher version: 2.6.1

**Information about the Cluster**
- Kubernetes version: v1.21.5+rke2r2
- Cluster Type (Local/Downstream): Downstream
   - 5 Custom CentOS 8.4 Nodes with all roles, RKE2 deployed with RKE2 Default as Default Pod Security Policy and cis-1.6 as Worker CIS Profile.

**Describe the bug**
apply-system-agent-upgrader jobs are stucked on each node with state In Progress, same age than cluster creation age.
Viewing job yaml shows that containers template (image rancher/system-agent:v0.1.0-suc) uses hostNetwork true, hostIPC true, hostPID true and adds securityContext capabilities.
In the logs i can see this is all rejected by Pod Security Policy.

**To Reproduce**
Deploy an RKE2 downtream cluster with RKE2 Default as Default Pod Security Policy and cis-1.6 as Worker CIS Profile.

**Result**
apply-system-agent-upgrader jobs are stucked.

**Expected Result**
I imagine jobs should run as expected.

**Screenshots**

![2021-10-26_111802](https://user-images.githubusercontent.com/5137624/138854802-4c512021-0f69-449f-a52c-ea60fece36db.jpg)

**Comment by alexdga** [comment]
I could get the jobs in active state by adding system-unrestricted-psp pod security policy to clusterrole system-agent-upgrader

**Comment by alexdga** [comment]
Problem still present in rancher 2.6.3

**Comment by jiaqiluo** [comment]
Hi, @alexdga Thank you for reporting the bug.  This sounds like a duplication of https://github.com/rancher/rancher/issues/36559, please check that issue for fixing and progress. 

Closing this issue in favor of https://github.com/rancher/rancher/issues/36559
