### ISSUE TITLE
Monitoring is firing lots of false alerts

### ISSUE THREAD

**Issue by tdudgeon** [rancher/rancher#35287]
I'm using a vanilla deployment of monitoring (version 9.4.203 from the Apps & Marketplace). My only customisations were to use persistent storage.
Once deployed a large number of alerts fire, and these all seem to be false alerts. I'm seeing these targets as down:

cattle-monitoring-system/rancher-monitoring-kube-controller-manager/0 (0/2 up)
cattle-monitoring-system/rancher-monitoring-kube-etcd/0 (0/3 up)
cattle-monitoring-system/rancher-monitoring-kube-proxy/0 (2/8 up) 
cattle-monitoring-system/rancher-monitoring-kube-scheduler/0 (0/2 up)

I'm not familiar with all the details, but it could be that there is a misconfiguration of the pushprox-kube-*-client pods? For instance in the pushprox-kube-etcd-client pods I see this specified as the arguments to the pod: `--fqdn=$(HOST_IP) --proxy-url=$(PROXY_URL) --metrics-addr=$(PORT) --allow-port=2379 --tls.cert=/etc/ssl/push-proxy/push-proxy.pem --tls.key=/etc/ssl/push-proxy/push-proxy-key.pem --tls.cacert=/etc/ssl/push-proxy/push-proxy-ca-cert.pem`, but the PORT environment variable is set to 10014 but the port being scraped is 2379.

Also, strangely the status of the rancher-monitoring-kube-controller-manager targets is shown as down, but the endpoints are reachable from within the prometheus-rancher-monitoring-prometheus-0 pod, whereas the rancher-monitoring-kube-etcd targets are also shown as down, but those endpoints are not reachable.

**Comment by tdudgeon** [comment]
Re-opening this as it still seems to be an issue.
I just did a standard install of monitoring (version 16.6.1-up16.6.0) on a Rancher 2.5.7 cluster which was created in the standard way.
Soon after monitoring became live a large number of alerts start firing. See the screenshot below for these.
The cluster seems to be functioning OK. No problems are seen. The alerts seem to be false alarms?

![image](https://user-images.githubusercontent.com/647419/156373833-48847ddb-1ccb-4c35-b6f4-a746c51496a8.png)

**Comment by tdudgeon** [comment]
Actually, seems like I can't re-open this issue. Can someone with more powers do so?

**Comment by tdudgeon** [comment]
@jiaqiluo can you re-open this or know someone who can?

**Comment by jiaqiluo** [comment]
Reopen the issue for visibility

**Comment by slickwarren** [comment]
@tdudgeon can you tell us more about the issue by filing out the below template? Also were you seeing the original post's targets being down or do you have some other root cause? 
**Test Environment**
- Rancher Version:
- Installation option (Docker install/Helm Chart):

**Information about the Cluster**
- Kubernetes version:
- Cluster Type(s) tested on (Local/Downstream):

**Overview of Validation**


**Reopening for the following issues**


**Screenshots**


**non-blocking, but related issues found while testing**

**Comment by tdudgeon** [comment]
**Test Environment**

Rancher Version: 2.5.7
Installation option (Docker install/Helm Chart): Helm via Apps & Marketplace

**Information about the Cluster**

Kubernetes version: v1.19.9
Cluster Type(s) tested on (Local/Downstream): OpenStack VMs, cluster created by Rancher using standard settings. Nothing unusual about the cluster. 2 control plane nodes, 3 etc nodes, 3 worker nodes

**Overview of Validation**

A number of prometheus targets are failing "out of the box". These seem to fall into these categories

1) metrics endpoint responds correctly (metrics can be fetched at that endpoint using wget after shelling into the prometheus-rancher-monitoring-prometheus-0 pod), but target is reported as down. 
![image](https://user-images.githubusercontent.com/647419/158339489-1cfc7adc-07ff-426c-8461-17dfb9eab343.png)
and
![image](https://user-images.githubusercontent.com/647419/158341886-8f183a19-2190-4e90-b0f6-e18a523a2655.png)


2) metrics endpoint not found.
![image](https://user-images.githubusercontent.com/647419/158340045-3ab7fed2-2c22-45a3-b471-2462fe8abcfc.png)
```
$ wget -O - http://192.168.253.114:2379/metrics?_scheme=https
Connecting to 192.168.253.114:2379 (192.168.253.114:2379)
wget: error getting response: Resource temporarily unavailable
```

3) Some nodes reported as OK, others as failed, but all the endpoints fail
![image](https://user-images.githubusercontent.com/647419/158340771-6aad967a-a9d4-4316-ade7-5a820af632ca.png)
```
$ wget -O - http://192.168.253.67:10249/metrics
Connecting to 192.168.253.67:10249 (192.168.253.67:10249)
wget: can't connect to remote host (192.168.253.67): Connection refused
```
(that is for one that is reported as OK).

All the IP addresses look to be correct.

**Reopening for the following issues**
Original post was never addressed and issues was closed as it went stale.

**Comment by slickwarren** [comment]
I'm not able to reproduce this issue using 2.5.7, 1.19.9 and 9.4.203 for monitoringv2. Only difference is I am using AWS instead of openstack. Maybe there is something unique about openstack's networking that would cause issues here?

**Comment by tdudgeon** [comment]
But for #1 can `wget` the metrics endpoints from inside the `prometheus-rancher-monitoring-prometheus-0` pod so it's not a networking problem.
Would it help if I showed you this with a screenshare?

**Comment by tdudgeon** [comment]
Any update on this?
We have 2 (almost) identical OpenStack clusters with the same problem. Happy to show the details.

**Comment by tdudgeon** [comment]
This is still a real issue. Please keep open.
