### ISSUE TITLE
EKS upgrades loop without a default AMI list for v1.19 onwards

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#35295]
Spotted in 2.5.9.

Issue description:

When upgrading a downstream EKS cluster (eksv1 provisioned), the AMI list doesn't provide default AMIs for v1.19 and onwards. It's possible to select a version higher than v1.18 in the UI (due to eksv2 dynamic discovery?) and is supported in our matrix.

  * https://github.com/rancher/rancher/blob/release/v2.5/pkg/kontainer-engine/drivers/eks/eks_driver.go

Business impact:
This causes an update/provisioning loop with any planned upgrade not possible.

Troubleshooting steps:

Repro steps:

Create an eksv1 cluster in the UI:

Either directly as v1.19 or higher (provisioning loop)
OR, as v1.18 or lower and later upgrade (update loop)
Note! v2.5.9 defaults to creating new EKS clusters using the ekvs2 provisioning workflow, the eksv1 workflow can be reached in the UI with: https://<rancher URL>/g/clusters/add/launch/amazoneks

Workaround:

Edit the cluster in the API to set the ami field to a valid EKS-Optimized AMI (not possible in the UI) that matches the desired version. Once the request is sent, follow through with another edit/save in the UI to set the client credentials and proceed.

  * https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

SURE-3342

**Comment by gaktive** [comment]
Clarification:
> That's correct, Rancher will error during provisioning attempting to look up the >=1.19 AMIs in the map. Yes it's the latter, the version is in the list (I assume the same list is presented for eksv1/v2), and if a cluster was provisioned using eksv1 the AMIs aren't defined beyond 1.18.

Error: `This cluster is currently Updating. Default ami of region us-east-1 for kubernetes version 1.19 is not set`

**Comment by deniseschannon** [comment]
Note: We need to add in the AMIs for all EKS versions that are supported in the UI for KEv1. 

To test: Deploy an older KEv1 cluster in 2.4 and upgrade to 2.5-head and upgrade to a 1.19+ cluster.

AMIs need to be added for 1.19, 1.20, 1.21

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

We should also confirm that the UI has support to deploy all 3 versions.

**Comment by deniseschannon** [comment]
There is a script that @paraglade has written before to help obtain these AMIs but I don't kmow where it's located.

**Comment by thedadams** [comment]
Default AMIs for these versions exist in 2.6, but not in 2.5. This issue will be used to update the AMIs in 2.6.

**Comment by cmurphy** [comment]
Validated on v2.6-head (e62e1ae34eca46bd733b7f67d1cea055395ac45d):

Test 1:
1. Navigate to https://rancherserver/g/clusters/add/launch/amazoneks
2. Select region us-west-2
3. Select version 1.19
4. Accept all other defaults
Result: cluster becomes active :heavy_check_mark: 

Test 2:
1. Navigate to https://rancherserver/g/clusters/add/launch/amazoneks
2. Select region us-east-2
3. Select version 1.19
4. Accept all other defaults
Result: cluster becomes active :heavy_check_mark:

Test 3:
1. Navigate to https://rancherserver/g/clusters/add/launch/amazoneks
2. Select region us-east-2
3. Select version 1.18
4. Accept all other defaults
5. Wait for cluster to become active
6. Upgrade to 1.19
Result: cluster becomes active :heavy_check_mark:

**Comment by throrin19** [comment]
It's possible to bump that AMI lists in 2.5 version ? I can't upgrader to rancher 2.6 for now. I have an issue with applications part...
