### ISSUE TITLE
Docker 1.10 support?

### ISSUE THREAD

**Issue by withinboredom** [rancher/rancher#3531]
Has anyone tested rancher with Docker 1.10?

**Comment by withinboredom** [comment]
Testing it now, seems like everything is fine. No problems so far.

**Comment by vincent99** [comment]
@ibuildthecloud runs Docker from master regularly and we [test RC releases](https://github.com/docker/docker/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Aibuildthecloud+) to make sure they will work (both in general and with Rancher).

**Comment by withinboredom** [comment]
Awesome, good to hear
