### ISSUE TITLE
Monitoring (100.0.0+up16.6.0): cattle-monitoring-system/rancher-monitoring-kube-proxy failed to resolve DNS

### ISSUE THREAD

**Issue by minhtt159** [rancher/rancher#35327]
**Rancher Server Setup**
- Rancher version: 2.6.2:stable
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 (rke2r2)
- Proxy/Cert Details: None

**Information about the Cluster**
- Kubernetes version: v1.21.5
- Cluster Type (Local/Downstream): Local

**More details**
I deploy my own Kubernetes cluster on my home-lab, all nodes are Ubuntu 18.04.6 LTS VMs (kernel 4.15.0-161-generic) on Proxmox server. I was following [this guide](https://docs.rke2.io/install/quickstart/) to setup the environment. 

My cluster has 3 nodes, 1 server and 2 agents. After that, I installed MetalLB & Traefik for load balancing via their helm charts. Then I installed Logging & Monitoring from Rancher's Cluster tools

**Describe the bug**

After checking through Prometheus Alerts/Targets, I found out `serviceMonitor/cattle-monitoring-system/rancher-monitoring-kube-proxy` is unreachable.

**To Reproduce**

Install Monitoring helm chart from Rancher Cluster tools

**Result**

**Expected Result**

All targets are up

**Screenshots**

![image](https://user-images.githubusercontent.com/4847344/139515070-a5894ce4-311b-4bf3-a1b3-737cc0609a1f.png)

**Additional context**

I have ssh to all nodes and run `dig @10.43.0.10 google.com` but only the server node (which has `coredns`) return an answer.

I've tried `nslookup pushprox-kube-proxy-proxy.cattle-monitoring-system.svc.cluster.local 10.43.0.10` on all nodes:
- server node: return the right address (which is 10.43.173.128)
- agent node: connection timed out

But there is a twist. I tried to run `nslookup pushprox-kube-proxy-proxy.cattle-monitoring-system.svc.cluster.local 10.42.0.9` (10.42.0.9 is pod IP of coredns pod on server node) on agent node and it return the right address as well

![image](https://user-images.githubusercontent.com/4847344/139515494-012d7b8f-9e9b-4c82-a378-581db2727dd8.png)

**Comment by minhtt159** [comment]
@aiyengar2 I believe this bug is not the same root cause with #33052. Can you please help out?

**Comment by kwinkel** [comment]
Is the CoreDNS pod on the node with the IP `192.168.6.11`?

**Comment by minhtt159** [comment]
> Is the CoreDNS pod on the node with the IP `192.168.6.11`?

Yes, they are 2 coreDNS pod on that node. And their metrics are up

![image](https://user-images.githubusercontent.com/4847344/142028744-bc6a01c1-6b37-47ca-a7eb-0abfe74ae375.png)

**Comment by kwinkel** [comment]
I somehow think you have a underlying networking issue on your nodes.
Try to deploy CoreDNS pods to nodes with services which get some timeouts while scraping.
If it works some minutes after, take a look at: https://github.com/flannel-io/flannel/issues/1279

**Comment by aiyengar2** [comment]
I'd agree that this seems like an underlying networking issue, unrelated to Monitoring V2. If this is reproducible on a fresh RKE2 cluster, I think an issue should be opened in https://github.com/rancher/rke2.

**Comment by minhtt159** [comment]
> I'd agree that this seems like an underlying networking issue, unrelated to Monitoring V2. If this is reproducible on a fresh RKE2 cluster, I think an issue should be opened in https://github.com/rancher/rke2.

Thank you for responding. I will investigate into RKE2 networking. If it still happened, I will open a new issue in RKE2 repo
