### ISSUE TITLE
Please ask if its ok to stop a service/stack

### ISSUE THREAD

**Issue by withinboredom** [rancher/rancher#3532]
Nothing like using a touchpad and accidentally tapping the stop button beside a service/stack.

**Comment by nhumrich** [comment]
:+1: 
And of course use the usual "hold control to avoid the prompt".

**Comment by yobasystems** [comment]
+1

**Comment by sjwoodr** [comment]
+1 ... way to easy to stop an entire stack because you meant to click the dropdown next to the stop button but got a little sloppy.  This needs a confirmation before it stops!

**Comment by sshipway** [comment]
+1.  Far too easy to click on the wrong button.  Maybe allow ctrl-click to bypass the confirmation, as with the Delete option?

**Comment by tfiduccia** [comment]
Version - 3/4
Verified fixed
