### ISSUE TITLE
Admission webhook "rancherauth.cattle.io" denied the request: user "system:serviceaccount:cattle-system:rancher" (groups=["system:serviceaccounts" "system:serviceaccounts:cattle-system" "system:authenticated"]) is attempting to grant RBAC permissions not currently held

### ISSUE THREAD

**Issue by bubbybharath** [rancher/rancher#35329]
Admission webhook "rancherauth.cattle.io" denied the request: user "system:serviceaccount:cattle-system:rancher" (groups=["system:serviceaccounts" "system:serviceaccounts:cattle-system" "system:authenticated"]) is attempting to grant RBAC permissions not currently held.

I got this error for most of the ranncher environments. starting from 1.18 to 1.20 . Not able to launch kubectl command throught the console.

##################
This cluster is currently Error.

Admission webhook "rancherauth.cattle.io" denied the request: user "system:serviceaccount:cattle-system:rancher" (groups=["system:serviceaccounts" "system:serviceaccounts:cattle-system" "system:authenticated"]) is attempting to grant RBAC permissions not currently held: {APIGroups:[""], Resources:["secrets"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["catalogs"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["cisbenchmarkversions"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["cisconfigs"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["clusters"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["clustertemplaterevisions"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["features"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["fleetworkspaces"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["globaldnses"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["globaldnsproviders"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["kontainerdrivers"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["multiclusterapps"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["nodedrivers"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["nodetemplates"], Verbs:["create"]} {APIGroups:["management.cattle.io"], Resources:["podsecuritypolicytemplates"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["preferences"], Verbs:["*"]} {APIGroups:["management.cattle.io"], Resources:["principals"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["rkeaddons"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["rkek8sserviceoptions"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["rkek8ssystemimages"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["roletemplates"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["settings"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["templates"], Verbs:["get" "list" "watch"]} {APIGroups:["management.cattle.io"], Resources:["templateversions"], Verbs:["get" "list" "watch"]} {APIGroups:["project.cattle.io"], Resources:["sourcecodecredentials"], Verbs:["*"]} {APIGroups:["project.cattle.io"], Resources:["sourcecoderepositories"], Verbs:["*"]}; resolution errors: [clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]
###############################################################

**Rancher Server Setup**  local cluster version is 1.19.15
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart): 20.x
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:  1.19.15 RKE
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

**To Reproduce**
 

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by bubbybharath** [comment]
I noticed only rancher.cattle.io whereas the above error displays webhook with another name.

 kubectl get mutatingwebhookconfiguration -n cattle-system
NAME                WEBHOOKS   AGE
rancher.cattle.io   1          45h

kubectl get ValidatingWebhookConfiguration -n cattle-system
NAME                WEBHOOKS   AGE
rancher.cattle.io   2          45h


kubectl get mutatingwebhookconfiguration -A
NAME                WEBHOOKS   AGE
rancher.cattle.io   1          45h

kubectl get ValidatingWebhookConfiguration -A
NAME                WEBHOOKS   AGE
rancher.cattle.io   2          45h

**Comment by f4tal-err0r** [comment]
This looks like RBAC is disabled on the cluster. If you're using something like microk8s you have to enable it

**Comment by bubbybharath** [comment]
Thanks for the update. Can you tell me the process to enable it for RKE cluster created by using RKE? I am running the command provided during the registration of nodes (etcd/controlplane/worker node).

**Comment by f4tal-err0r** [comment]
This is something on the control plane side. Again I dont know what you're using for that but for microk8s you can run a `microk8s.enable rbac`

**Comment by bubbybharath** [comment]
I have created clusterrole "cluster-admin" in local ( rancher cluster) to fix the issue.

**Comment by ddelange** [comment]
I can confirm that adding the missing ClusterRole fixes the issue on a local kOps cluster (which has RBAC enabled by default, confirmed with `kubectl api-versions | grep rbac`):
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
```
By default, the rancher helm chart [creates](https://artifacthub.io/packages/helm/rancher-stable/rancher?modal=template&template=clusterRoleBinding.yaml) the ClusterRoleBinding, but the corresponding ClusterRole won't be created. I assume it exists by default in RKE clusters.
