### ISSUE TITLE
Unable to set ACE when editing an RKE2 cluster provisioned by Rancher

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#35338]
**Summary:**

If editing a node-driver provisioned RKE2 cluster to set ACE (Authorized Endpoint) the PUT request goes thru as expected but the response from the server does not seem to include the localClusterAuthEndpoint specified in rkeConfig. Either that or I am misinterpreting the server response. 

It looks like this was last tested prior to 2.6.0 release and theoretically should have been working prior. e.g. see https://github.com/rancher/rancher/issues/31604 and https://github.com/rancher/rancher/issues/32388

-----

**Environment:**
Rancher version: v2.6-head `931a0f09d` pulled at 11/1/21 ~1:15pm Arizona time
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2 - DigitalOcean node driver
Downstream K8s version: v1.21.5+rke2r2

**Steps to Reproduce:**
1. Create a one node RKE2 cluster with the DigitalOcean node driver. Use default settings.
2. Once the cluster is fully ready and Active, edit the cluster. Go to cluster options > networking so we can enable ACE. Fill in the FQDN field. Leave the cert field blank (it is not a required field). Click Save to save the changes. Look at the PUT request and response for the cluster.
![image](https://user-images.githubusercontent.com/45179589/139747237-9cc1b6d1-38ad-48cd-be96-fbfc2e764829.png)
Notice, the PUT request appears correct in rkeConfig:
![image](https://user-images.githubusercontent.com/45179589/139747373-67b9d73e-a471-4415-a563-50094cd1d9da.png)

Notice the PUT response from the server doesn't appear correct. Either that or I am misinterpreting when I take a look at the server response.
![image](https://user-images.githubusercontent.com/45179589/139747529-f5f76629-45db-46f0-82ce-b090c795f562.png)

3. Edit the cluster again. We don't see our ACE settings we submitting in our first PUT request to edit the cluster.
![image](https://user-images.githubusercontent.com/45179589/139747640-b9a73c2e-712c-4464-abe7-26e4fc1a51e2.png)

**Expected Result:**
I expected to be able to edit my RKE2 cluster to enable ACE. I expected my PUT request to take.

**Actual Result:**
I cannot enable ACE when I edit my RKE2 cluster. My PUT request does not seem to take and the server response doesn't appear correct to me (either that or I misinterpreted).

**Additional Info:**
~Although I do not know the exact version, I was testing this a few work days ago maybe October 24th or 25th and this seemed to work last time. I suspect it could be a new issue.~
EDIT: I think prior I had enabled ACE with neither field set, then edited to add content to one of the two fields. This was working prior but is not the same.

**Comment by thedadams** [comment]
@davidnuzik This is expected because of a change in the backend. This UI issue, once completed, will resolve the problem: https://github.com/rancher/dashboard/issues/4410

**Comment by davidnuzik** [comment]
Copy that @thedadams Closing in favor of https://github.com/rancher/dashboard/issues/4410
