### ISSUE TITLE
Logs not shipping to Splunk

### ISSUE THREAD

**Issue by annablender** [rancher/rancher#35336]
**Environment**
- Rancher v2.5.6
- CentOS 7
- fluent-bit: 1.6.10, 1.7.9 (manually upgraded image)

**Description**
Configured ClusterFlow and ClusterOutput, but cannot get logs to ship to Splunk on Logging v2. Logging v1 was sending logs to this Splunk instance before the upgrade.

**Business impact**
High since customer does not feel comfortable upgrading the rest of their clusters to v2.5.x until they get a working logging configuration. Looking to potentially find another logging solution if required.

**Troubleshooting steps**
Initially, I was concerned about the network, so we went over everything there and made sure that we could send logs to Splunk HEC manually via curl. We then added a buffer to the configuration (https://github.com/fluent/fluent-bit/issues/2972), and also requested a new certificate and key. Then we scaled up the Fluentd deployment limits and requests (https://github.com/rancher/rancher/issues/29879#issuecomment-731732589), and then upgraded the fluent-bit image manually (https://github.com/fluent/fluent-bit/issues/2972) by editing the logging resource to use version 1.7.9. We then fixed the ca_file syntax in the config due to due to https://github.com/rancher/rancher/issues/31810.

I was unable to reproduce the issue.

**Repro steps**
Install Logging v2
Configure ClusterOutput
Configure ClusterFlow

**Comment by bentastic27** [comment]
I have a ticket where the customer is experiencing this same thing on 2.5.9. Is there a backport to 2.5.12 incoming for this?
