### ISSUE TITLE
Removing Scheduling rules on a service has no effect

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#3534]
Rancher v0.56.1

Steps to reproduce:
1. create a service with a scheduling rule,
2. clone this service and remove the scheduling rule,
3. the service has still the scheduling rule set.

Also happens when upgrading a service, removing scheduling rules has no effect.

**Comment by tfiduccia** [comment]
Version - master ui 2/4
Verified that this is a problem.

**Comment by ebr** [comment]
is there any reasonable workaround for this? the only way i've been able to get around it is to create a new stack by copying and pasting the config of the existing stack.

**Comment by vincent99** [comment]
Tracking as part of #3707
