### ISSUE TITLE
Hide existing non-partner charts in "library" catalog

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#35347]
In rancher/charts in the `master` branch, we currently have multiple charts that are visible in the legacy UI to launch these charts. This determines the "library" catalog in the old UI. 

With v2.6, we have migrated to serving up all new charts in Apps & Marketplace which is located per cluster in the new UI. These charts are from:
* rancher/charts in the `release-v2.x` branches
* rancher/partner-charts in the `main` branch

We want to hide the ability to launch any new chart from the old library catalog by maxing out the Rancher version by adding to any chart without a maximum Rancher version to be set to Rancher v2.6.2.

**Impact:** No users will be able to launch versions of these older charts in Rancher v2.6.3 onwards, but anyone who already has the chart installed would continue being able to maintain it. 

**To Do:** Review each chart and each version in rancher/charts, check the questions.yml to see if `rancher_max_version` exists or not.

If the questions.yaml contains a label to indicate that it's a partner (`io.rancher.certified: partner`), then it is a partner chart.

If no max versions exists and it is not a partner chart, add rancher_max_version: 2.6.2 into questions.yml file.

**Additional To Do:**

Close any issue in rancher/charts that have been opened against any non-partner chart with the following info:

With the release of Rancher v2.6, these charts are no longer visible in the UI and only available by enabling a legacy flag. These charts are also launched using Helm2 and we have moved towards launching Helm3 charts. 

We are no longer maintaining these charts and any new charts maintained by Rancher or our partners can be found in the new Apps and Marketplace in our new UI.

**Comment by deniseschannon** [comment]
This can only be tested on a v2.6.3 RC, not v2.6-head.

Fresh install test case: you enable the legacy feature flags and navigate to the catalog and you should not be able to deploy any charts (charts without a gold banner around it) from the library EXCEPT for the longhorn chart.

Upgrade test case: Launch a previous version of Rancher ((if it's 2.6, enable the legacy feature flag), deploy a non partner chart from library. Upgrade to a v2.6.3 RC, confirm that you're able to still edit/manage the deployed chart.

@rishabhmsra You should confirm if the UI issues from this issue are present in this one: https://github.com/rancher/rancher/issues/35353

**Comment by rishabhmsra** [comment]
**Fresh install checks - Pass**
Non-partner charts are not showing up in the "library" catalog section, `except longhorn`, after enabling legacy feature flag in rancher v2.6.3-rc2

**Upgrade checks - Not working;** [UI issue](https://github.com/rancher/dashboard/issues/4645).
Performed following steps:

1) Deployed rancher v2.6.2 and enabled legacy feature.
2) Deployed non-partner charts from "library" catalog.
3) Upgraded rancher to v2.6.3-rc2.
4) Installed non-partner charts are present under Multi-Cluster Apps section but when I am trying to upgrade the chart, getting this error: `Cannot read property 'match' of undefined Reload to try again or log out`. Created this [UI issue](https://github.com/rancher/dashboard/issues/4645).
