### ISSUE TITLE
Integrate K3s/RKE2 etcd snapshot metadata enhancement into Rancher to store cluster config

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#35344]
Integrate the feature from 
https://github.com/k3s-io/k3s/issues/4380
https://github.com/rancher/rke2/issues/2076
to store cluster config at the time of etcd snapshots being taken.

**Comment by snasovich** [comment]
@Oats87 , does this issue include support for specifying what kind of restore should be done on a snapshot. This is necessary to support UI like this:
![image](https://user-images.githubusercontent.com/85187633/141043418-235970c2-171a-415a-acfe-1a556f7712eb.png)
