### ISSUE TITLE
Removing stuck with the message "Waiting on cluster-scoped-gc"

### ISSUE THREAD

**Issue by guzym** [rancher/rancher#35345]
**Rancher Server Setup**
- Rancher version: v2.5.8
- Installation option: Docker

**Information about the Cluster**
- Kubernetes version: v1.19.4
- Cluster Type: Downstream
   - Custom

**Describe the bug**
In the Rancher UI, a cluster is stuck with the message "Waiting on cluster-scoped-gc". We don't get the cluster removed and we can't interact with it anymore. If we manually go over the "Delete" button nothing happens. Via the API we see the following transition message:

`"state": "removing",
"transitioning": "error",
"transitioningMessage": "waiting on cluster-scoped-gc"`

When we click on the cluster in the UI, we get the message:

`ClusterUnavailable 503: cluster not found`

Due to lack of ideas, we have already tried to rebuild the cluster using the same automated way, but we get the following error message:

`Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [code=MissingRequired, fieldName=ClusterTemplateRevision, message=this cluster is created from a clusterTemplateRevision, please pass the clusterTemplateRevision, baseType=error]`

A connection via "kubectl" can also no longer be established. 

The infrastructure of the cluster no longer exists. This is only the entry in the interface, which cannot be removed. We currently have no idea how to get the cluster removed.

**To Reproduce**
Unfortunately, we do not know exactly how we got into this state. The problem appeared after we automatically deployed and removed the cluster for testing purposes.

**Result**
The result of the error is that we see an orphaned cluster in the interface and unfortunately we cannot get the entry removed.

**Expected Result**
It would be good if there was some way to force deletion of orphaned artifacts / clusters and all associated references in the UI.

**Screenshots**
<a href="https://imgbb.com/"><img src="https://i.ibb.co/0m4sb3w/Cluster-error-message.png" alt="Cluster-error-message" border="0"></a>

**Comment by bartcee** [comment]
I encouered the same issue on Rancher v.2.5.9. The cluster was imported with rancher cli tool and deleted with `rancher cluster rm cluster-name`. Stuck with `Waiting on cluster-scoped-gc` error message.

**Comment by Heiko-san** [comment]
Any workaround to fix clusters in that state ? :(

**Comment by vichaos** [comment]
Switch to rancher-cluster 's kube-context and run following command (**Replace `${STUCK_CLUSTER}` with the stuck cluster's name or id** )

```
kubectl get clusters.management.cattle.io $(kubectl get clusters.management.cattle.io \
-o jsonpath='{range .items[*]}{@.spec.displayName}:{@.metadata.name}{"\n"}'| \
grep ${STUCK_CLUSTER} | cut -d ":" -f2) -o=json|jq '.metadata.finalizers = null' | kubectl -f -
```

> Any workaround to fix clusters in that state ? :(
