### ISSUE TITLE
[Monitoring/Rancher v2.5.6] After enabling monitoring , Pod pushprox-kube-etcd-client failed to scrape metrics

### ISSUE THREAD

**Issue by jr-94** [rancher/rancher#35349]
After deploy rancher-monitoring version 16.6.0, the prometheus target "**serviceMonitor/cattle-monitoring-system/rancher-monitoring-kube-etcd**" is down.

it is a hosted/imported cluster

Logs from **pushprox-kube-etcd-client** pod :

level=info ts=2021-11-02T14:28:57.947Z caller=main.go:269 msg="URL and FQDN info" proxy_url=http://pushprox-kube-etcd-proxy.cattle-monitoring-system.svc:8080/ fqdn=192.168.2.171
level=info ts=2021-11-02T14:29:09.124Z caller=main.go:232 msg="Got scrape request" scrape_id=05a4ab71-6e88-4311-a757-16e3fa6738ef url="http://192.168.2.171:2379/metrics?_scheme=https"
level=error ts=2021-11-02T14:29:09.130Z caller=main.go:101 err="failed to scrape https://192.168.2.171:2379/metrics: Get \"https://192.168.2.171:2379/metrics\": x509: certificate is valid for 127.0.0.1, 10.43.0.1, not 192.168.2.171"
level=info ts=2021-11-02T14:29:09.138Z caller=main.go:113 msg="Pushed failed scrape response" 
![image](https://user-images.githubusercontent.com/93599786/140048793-a2220ae9-6410-4f01-a3d7-19bba8b53e40.png)

**Comment by IJOL** [comment]
I'm being hitted by this same issue, I think this bug report should be reopened

**Comment by IJOL** [comment]
Although i only use rke, not rancher itself, but our issue is the same

**Comment by jonnisell** [comment]
Getting the same error on a rke1 provisioned cluster. The Service monitor is listed as active but the prod is getting the same log errors as listed above. 

System info:
rke: v1.3.12
Kubernetes: v1.22.10+
Monitoring app: 100.1.3+up19.0.3

**Comment by stefanlasiewski** [comment]
This issue should not have been closed. It is still present on Rancher 2.6.9, and because of what johnisell mentioned above, it looks to be disabled on all RKE v1 clusters. 

Rancher Monitoring v2 was supposed to fix this according to https://github.com/rancher/rancher/issues/18619#issuecomment-673168369 , but it's still broken.

**Comment by stefanlasiewski** [comment]
Looks like the Rancher docs team will document the solution, as mentioned in https://github.com/rancher/rancher/issues/31650#issuecomment-1362080340 .
