### ISSUE TITLE
[cli] bsdthread_register error on MacOS Monterey

### ISSUE THREAD

**Issue by alex347** [rancher/rancher#35346]
Rancher CLI v0.6.14 doesn't work on MacOS Monterey 12.0.1 when trying to launch it without any params:

`fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x71c877, 0x21)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0x7ff7bfeff5f0 sp=0x7ff7bfeff5d0
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:88 +0xa0 fp=0x7ff7bfeff620 sp=0x7ff7bfeff5f0
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:450 +0x9c fp=0x7ff7bfeff660 sp=0x7ff7bfeff620
runtime.rt0_go(0x7ff7bfeff690, 0x1, 0x7ff7bfeff690, 0x1000, 0x1, 0x7ff7bfeff840, 0x0, 0x7ff7bfeff85c, 0x7ff7bfeff873, 0x7ff7bfeff8ab, ...)
	/usr/local/go/src/runtime/asm_amd64.s:145 +0x14f fp=0x7ff7bfeff668 sp=0x7ff7bfeff660`

**Comment by gasweb** [comment]
Same issue( Found how to solve?

**Comment by marcelomrwin** [comment]
Same issue

**Comment by watson13j** [comment]
Same! (v0.6.12)

Tried an uninstall/reinstall of xcode, no luck. Tried shutting off av software, no luck.

**Comment by mayconritzmann** [comment]
same issue on terraform and kubectl

**Comment by vishal-hegde** [comment]
Yes. facing same issue

**Comment by pwiesinger** [comment]
Having the same issue.

**Comment by Udayallcloud** [comment]
same issue with terraform 
<img width="959" alt="Screen Shot 2021-11-11 at 11 09 57 PM" src="https://user-images.githubusercontent.com/93347457/141408032-6cf9f9ff-35c3-49fb-bce6-7804eff7af5c.png">

**Comment by ssstonebraker** [comment]
same issue

**Comment by LeVraiGG** [comment]
Same issue on kompose

**Comment by LeVraiGG** [comment]
found the answer here : https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue

**Comment by alex347** [comment]
v.1.6 branch doesn't compile:

`cli (v1.6) $  CROSS=1 make build
./.dapper build
[+] Building 12.2s (7/9)                                                                                                                                                                                                                            
 => [internal] load build definition from Dockerfile.dapper223729694                                                                                                                                                                           0.0s
 => => transferring dockerfile: 661B                                                                                                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                              0.0s
 => => transferring context: 86B                                                                                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/golang:1.10.3                                                                                                                                                                               1.8s
 => [auth] library/golang:pull token for registry-1.docker.io                                                                                                                                                                                  0.0s
 => [1/5] FROM docker.io/library/golang:1.10.3@sha256:3c54fa85d6262d2ef7695ee2f8793f1f4f9809ce4a08ca2e213235ef4cfdcb66                                                                                                                         0.0s
 => CACHED [2/5] RUN apt-get update &&     apt-get install -y xz-utils zip rsync                                                                                                                                                               0.0s
 => ERROR [3/5] RUN go get github.com/rancher/trash && go get golang.org/x/lint/golint                                                                                                                                                        10.3s
------                                                                                                                                                                                                                                              
 > [3/5] RUN go get github.com/rancher/trash && go get golang.org/x/lint/golint:                                                                                                                                                                    
#7 10.08 # golang.org/x/tools/internal/typeparams
#7 10.08 src/golang.org/x/tools/internal/typeparams/normalize.go:138:17: u.EmbeddedType undefined (type *types.Interface has no field or method EmbeddedType)
------
executor failed running [/bin/sh -c go get github.com/rancher/trash && go get golang.org/x/lint/golint]: exit code: 2
FATA[0013] exit status 1                                
make: *** [build] Error 1
`

**Comment by eoinverling** [comment]
Hi, I got it to work

* clone the rancher-cli repo
* `git checkout v1.6`
* edit "Dockerfile.dapper", I changed the golang version from `1.10.3` to `1.11.3` (other versions may work?)
* `CROSS=1 make build`
* `./build/bin/rancher_darwin-amd64 env ls`
* 👍

**Comment by Micromegass** [comment]
As @LeVraiGG already states, the answer is here: https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue. The programme needs a newer go version, so the programme in question must be updated. 

For me the error occured with the programme docker-machine. What I had to do was upgrade docker-machine and link the new version:

1. Upgrade docker-machine:  `brew install docker-machine`
1. Run upgrade again to see if it is linked. If not, continue
1. Remove old link rm '/usr/local/bin/docker-machine'
1. Link new version `brew link docker-machine`

**Comment by gokulk16** [comment]
Had the same issue for kubectl.
Relinking with brew by `brew link kubernetes-cli` and then re-installing worked.

**Comment by prasannjeet** [comment]
Had the same issue after upgrading to MacOS Monterey. My Rancher CLI suddenly stopped working. (0.6.14).

To fix it, I created a simple and lightweight docker image that runs exactly as a native rancher, using the `rancher` command. And the container is destroyed after the command is run while keeping the configurations.

https://hub.docker.com/r/prasannjeet/easy-rancher-cli

**Comment by yosaku5150** [comment]
> として@LeVraiGGすでに述べていますが、答えはここにあります：[https](https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue) ://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue 。プログラムには新しいバージョンが必要なため、問題のプログラムを更新する必要があります。
> 
> 私の場合、エラーはプログラムdocker-machineで発生しました。私がしなければならなかったのは、docker-machineをアップグレードし、新しいバージョンをリンクすることでした。
> 
> 1. docker-machineをアップグレードします。  `brew install docker-machine`
> 2. `brew install docker-machine`もう一度実行  して、リンクされているかどうかを確認します。そうでない場合は、続行します
> 3. 古いリンクを削除する`rm /usr/local/bin/docker-machine`
> 4. 新しいバージョンをリンクする`brew link docker-machine`
> 
> だから私は他の失敗したプログラムで、プロセスは似ているかもしれないと思います




very very coooollllllll
thank you so much!!!!!
Problem solved.
Thank you so much.
from japan

**Comment by myrainbowandsky** [comment]
> 

This helps in mac os.
