### ISSUE TITLE
Unable to remove manually deleted cluster form rancher

### ISSUE THREAD

**Issue by kfkawalec** [rancher/rancher#35356]
Rancher 2.6.1
I have cluster provisioned by rancher. I manually deleted a virtual machine with this cluster
I am trying to remove a cluster from the rancher UI but I get an error: `Method DELETE not supported`

```
curl -X 'DELETE' 'https://rancher.domain.xom/v1/management.cattle.io.clusters/c-m-z5r8xnwq' ...
{"type":"error","links":{},"code":"PermissionDenied","message":"Method DELETE not supported","status":403,"type":"error"}
```

I see error in rancher pod:
`[ERROR] error syncing 'c-m-z5r8xnwq': handler cluster-agent-controller-cleanup: Post "https://10.43.0.1:443/apis/rbac.authorization.k8s.io/v1/clusterroles?timeout=45s": cluster agent disconnected, requeuing`

How I can manually / force remove this cluster from inventory?
Maybe using kubectl?

**Comment by xuanyuanaosheng** [comment]
![image](https://user-images.githubusercontent.com/4197714/142789309-fe7ab901-0853-4642-9fbb-42f141180bcc.png)

**Comment by vbortnikov** [comment]
I had same issue with working cluster but after some minutes it was deleted without errors.
