### ISSUE TITLE
Hide existing partner charts in "helm3-library" catalog

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#35353]
In rancher/helm3-charts in the `master` branch, we currently have multiple charts that are visible in the legacy UI to launch these charts. This determines the "helm3-library" catalog in the old UI.

With v2.6, we have migrated to serving up all new charts in Apps & Marketplace which is located per cluster in the new UI. These charts are from:

* rancher/charts in the release-v2.x branches
* rancher/partner-charts in the main branch

We want to hide the ability to launch any new chart from the old library catalog by maxing out the Rancher version by adding to any chart without a maximum Rancher version to be set to Rancher v2.6.2.

**Impact:** No users will be able to launch versions of these older charts in Rancher v2.6.3 onwards, but anyone who already has the chart installed would continue being able to maintain it.

**To Do:** 
Review each chart and each version in rancher/charts, check the questions.yml to see if rancher_max_version exists or not.

If the questions.yaml contains a label to indicate that it's a partner (`io.rancher.certified: partner`), then it is a partner chart.

If no max versions exists and it is not a partner chart, add `rancher_max_version: 2.6.2` into questions.yml file.

**Comment by deniseschannon** [comment]
This can only be tested on a valid v2.6.3 RC.

Fresh install test case: you enable the `legacy` feature flags and navigate to the catalog and you should not be able to deploy any partner-charts from the helm3 library. 

Upgrade test case: Launch a previous version of Rancher ((if it's 2.6, enable the `legacy` feature flag), deploy a partner chart from helm3-library. Upgrade to a v2.6.3 RC, confirm that you're able to still edit/manage the deployed chart.

**Comment by rishabhmsra** [comment]
**Fresh install checks - Pass**
- Partner charts are not showing up in the helm3 library section after enabling legacy feature flag in rancher v2.6.3-rc1

**Upgrade checks - Not working**
Performed following steps:
1. Deployed rancher v2.6.2 and enabled legacy feature.
2. Deployed `alcide` and `aws-event-sources` partner chart.
3. Upgrade rancher to v2.6.3-rc1.
4. Both the partner charts are present under `Multi-Cluster Apps` section but when I am trying to upgrade the chart, getting this error: `Cannot read property 'match' of undefined Reload to try again or log out` (attached ss)
![ss1](https://user-images.githubusercontent.com/36376154/142644208-6788c6c9-1388-4856-a0d8-4f3d26986e85.png)
5. Also in Apps and marketplace these two charts are present under `installed apps` section on downstream cluster, but `alcide "edit/upgrade"` showing all the charts in the UI. (Attached ss)
![ss2](https://user-images.githubusercontent.com/36376154/142644315-b5f4f82e-956b-4c54-b6c0-433d4bb57e2a.png)

**Comment by deniseschannon** [comment]
@rishabhmsra Can you open 2 separate UI tickets for 4 and 5 in rancher/dashboard with the 2.6.3 milestone?

Technically, this issue could be closed as the charts are hidden as expected.

**Comment by rishabhmsra** [comment]
Raised the UI tickets for 4 and 5 in rancher/dashboard - [issue1](https://github.com/rancher/dashboard/issues/4627), [issue2](https://github.com/rancher/dashboard/issues/4628)
