### ISSUE TITLE
Hide existing partner charts in "library" catalog

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#35352]
In rancher/charts in the `master` branch, we currently have multiple charts that are visible in the legacy UI to launch these charts. This determines the "library" catalog in the old UI. 

With v2.6, we have migrated to serving up all new charts in Apps & Marketplace which is located per cluster in the new UI. These charts are from:
* rancher/charts in the `release-v2.x` branches
* rancher/partner-charts in the `main` branch

We want to hide the ability to launch any new chart from the old library catalog by maxing out the Rancher version by adding to any chart without a maximum Rancher version to be set to Rancher v2.6.2.

**Impact:** No users will be able to launch versions of these older charts in Rancher v2.6.3 onwards, but anyone who already has the chart installed would continue being able to maintain it. 

**To Do:** 

Review each chart and each version in rancher/charts, check the questions.yml to see if `rancher_max_version` exists or not.
If the questions.yml contains a label to indicate that it's a partner (`io.rancher.certified: partner`), then it is a partner chart

If no max versions exists and it **is** a partner chart, add `rancher_max_version: 2.6.2` into questions.yml file.

**Comment by deniseschannon** [comment]
The datadog chart is still a visible partner chart in the library.

**Comment by deniseschannon** [comment]
The datadog chart is no longer visible after https://github.com/rancher/charts/pull/1609 was merged.

**Comment by rishabhmsra** [comment]
**Fresh install checks - Pass**
Partner charts are not showing up in the "library" catalog section after enabling legacy feature flag in rancher v2.6.3-rc2

**Upgrade checks - Not working**; UI [issue](https://github.com/rancher/dashboard/issues/4645).
Performed following steps:

1) Deployed rancher v2.6.2 and enabled legacy feature.
2) Deployed partner charts from "library" catalog.
3) Upgraded rancher to v2.6.3-rc2.
4) Partner charts are present under Multi-Cluster Apps section but when I am trying to upgrade the chart, getting this error: `Cannot read property 'match' of undefined Reload to try again or log out`. Created this UI [issue](https://github.com/rancher/dashboard/issues/4645).
