### ISSUE TITLE
Rancher host name setting is not kept

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#3535]
Rancher v0.56.1
Environment: Amazon EC2

Steps to reproduce:
1. add an EC2 host to rancher, in VPC with private IP in my case,
2. host should appear with name like "ip-xx-xx-xx-xx",
3. rename host to anything else like "beautiful_tear",
4. After a couple of minutes, rancher renames the host back to "ip-xx-xx-xx-xx".

Expected behavior: the set host name should be kept.

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/3414

Fixed for the next release.
