### ISSUE TITLE
2.5 KDM - Tracking issue for K3s k8s November Patches

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#35368]
This is the tracking issue for the K3s November k8s Patches. We should be checking/validating the following versions:

- v1.20.13

**Comment by rancher-max** [comment]
https://github.com/rancher/kontainer-driver-metadata/pull/737

**Comment by rancher-max** [comment]
Validated that only v1.20.13+k3s1 is available and upgrade is successful when pointing to dev-v2.5 KDM branch
