### ISSUE TITLE
Extend `webhook` certificate expiration to 10 years from 1 year

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#35366]
This is a partial fix for the parent issue: https://github.com/rancher/rancher/issues/35068

This will not require QA validation since this is a siloed const update. There is little security concern here as well since it is a self-signed certificate.

SURE-3475

**Comment by nickgerace** [comment]
Sneaky GitHub keywords... this was accidentally closed. A PR in `rancher/webhook` needs to use the new dynamiclistener to complete this issue.

**Comment by nickgerace** [comment]
## QA Validation
1. Install Rancher HA on `v2.6-head` (no downstream clusters needed)
2. Wait for Rancher to come up and sign in
3. Execute the following command with `KUBECONFIG` access to the local cluster: `kubectl get secrets -n cattle-system cattle-webhook-tls -o json | jq -r ".data.\"tls.crt\"" | base64 -d | openssl x509 -enddate` (tested on macOS 11.4 amd64 with `jq` and `kubectl` installed)
4. Observe the X509 "NotAfter" date's year being somewhere around 10 years from now

**Comment by nickgerace** [comment]
Available on webhook `v0.2.2-rc2` (may need to wait for `v2.6-head` to contain the chart)

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.6-head 4375161
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
followed these steps:
https://github.com/rancher/rancher/issues/35366#issuecomment-974494316
expected: `Observe the X509 "NotAfter" date's year being somewhere around 10 years from now`
actual: when command run I see "NotAfter" to be 2 days short of 10 years which is `being somewhere around 10 years from now`
![certs](https://user-images.githubusercontent.com/40282141/143906194-65ed6441-dab9-4bed-b1a0-a31d3933577e.jpg)
