### ISSUE TITLE
2.5 KDM - Tracking issue for RKE2 k8s November Patches

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#35367]
This is the tracking issue for the RKE2 November k8s Patches. We should be checking/validating the following versions:

- v1.20.13

**Comment by rancher-max** [comment]
Validated using rancher v2.5.11 pointing to dev-v2.5 KDM

<img width="777" alt="image" src="https://user-images.githubusercontent.com/55997940/144646274-e5ec8e2b-2219-41d1-aec5-a04dd33d2294.png">

Expected new version shows up and am able to upgrade to it successfully.
