### ISSUE TITLE
debian bullseye release support of install-docker

### ISSUE THREAD

**Issue by trieszecg** [rancher/rancher#35362]
**Is your feature request related to a problem? Please describe.**
official rancher docker installer does not work on debian 11 (bullseye)

**Describe the solution you'd like**
rancher / install-docker extension to support new debian release

**Comment by TheRojam** [comment]
@trieszecg my colleague @spiegie had Open a pull request for the docker-install script in its repo. See https://github.com/rancher/install-docker/pull/86 for more information.
You will face other issues w/ Debian bullseye as we already did.
