### ISSUE TITLE
[2.6] Fix vSphere charts upgrade path and forward port new charts 

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#35378]
This issue is for forwardporting the new vSphere charts in 2.5 to 2.6, and also address unwanted upgrade paths and CPI/CSI version pairings we allow currently. To do that, we need to do the following:

1. Refactor the name of the new vSphere charts we forwardported to 2.6 (+up version stands for the 2.5 variant of the chart)
CPI 100.0.1 -> 100.1.0+up1.0.100
CSI 100.0.1 -> 100.1.0+up2.3.0
  
2. Introduce new charts to replicate the older versions but adding a `kubeVersion: == 1.18` for both the 2.5 and 2.6 Rancher version lines. 

- In 2.5:
CPI 1.0.000 replaced by 1.0.1 with `kubeVersion: <= 1.17`
CSI 2.1.000 replaced by 2.1.1 with `kubeVersion: <= 1.19`

- In 2.6:
CSI 2.1.1 (Forward ported from 2.5)
CSI 100.0.0 replaced by 100.0.1+up2.1.1 (with `kubeVersion: 1.17 - 1.19`)

3. Hide the following CPI charts to encourage users to upgrade away from them as they don't use the correct image for each k8s version line.
CPI 1.0.0
CPI 100.0.0

### Current CPI and CSI charts in dev branches
Strikethrough means always hidden for user
| Chart | Rancher 2.5 | Rancher 2.6 |
|-------|-------------|-------------|
| CPI   | 1.0.000     | ~~1.0.000~~     |
|       | 1.0.100     | ~~1.0.100~~     |
|       |             | 100.0.0     |
|       |             | 100.0.1     |
|       |             |             |
| CSI   | 2.1.000     | ~~2.1.000~~     |
|       | 2.3.0       | ~~2.3.0~~       |
|       |             | 100.0.0     |
|       |             | 100.0.1     |

### Expected CPI and CSI charts after all changes are done
Strikethrough means always hidden for user
Note: CPI 1.0.1 is a copy of CPI 1.0.000 with an additional kubeVersion, whereas 1.0.100 is an entirely new CPI chart. They are not the same chart.
| Chart | Rancher 2.5 | Rancher 2.6       |
|-------|-------------|-------------------|
| CPI   | ~~1.0.000~~     | ~~1.0.000~~           |
| CPI   |  1.0.1 (kubeVersion <= 1.17)  | ~~1.0.1~~            |
|       | 1.0.100 (kubeVersion 1.18 - 1.21)    |   ~~1.0.100~~    |
|       |             | ~~100.0.0~~          |
|       |             | 100.1.0+up1.0.100 (kubeVersion 1.18 - 1.21)          |
|       |             |                   |
| CSI   | ~~2.1.000~~     | ~~2.1.000~~           |
|       | 2.1.1  (kubeVersion <= 1.19)   | ~~2.1.1~~           |
|       | 2.3.0 (kubeVersion 1.19 - 1.21)      | ~~100.0.0~~           |
|       |             | 100.0.1+up2.1.1 (kubeVersion <= 1.19) |
|       |             | 100.1.0+up2.3.0  (kubeVersion 1.19 - 1.21) |

**Comment by vivek-infracloud** [comment]
**On Rancher v2.6.2 verified CSI and CPI checks with feature charts pointing to _dev-v2.6-vsphere-release branch_**

**CPI 100.1.0+up1.0.100  (kubeVersion 1.18 - 1.21) validation**

1. On k8s 1.18: CPI 100.1.0+up1.0.100 is available and installed successfully with kubeVersion: 1.18 - 1.21.
2. On k8s 1.19: CPI 100.1.0+up1.0.100 is available and installed successfully with kubeVersion: 1.18 - 1.21.
3. On k8s 1.20: CPI 100.1.0+up1.0.100 is available and installed successfully with kubeVersion: 1.18 - 1.21.
4. On k8s 1.21: CPI 100.1.0+up1.0.100 is available and installed successfully with kubeVersion: 1.18 - 1.21.

**CSI 2.1.1 (kubeVersion <= 1.19) validation**

1. On k8s 1.18: CSI 2.1.1 is available and installed successfully with kubeVersion: <= 1.19.
2. On k8s 1.19: CSI 2.1.1 is available and installed successfully with kubeVersion: <= 1.19.

**CSI 2.3.0 (kubeVersion 1.19 - 1.21) validation**

1. On k8s 1.19: CSI 2.3.0 is available and installed successfully with kubeVersion: 1.19 - 1.21.
2. On k8s 1.20: CSI 2.3.0 is available and installed successfully with kubeVersion: 1.19 - 1.21.
3. On k8s 1.21: CSI 2.3.0 is available and installed successfully with kubeVersion: 1.19 - 1.21.
