### ISSUE TITLE
[2.5] Backport: Listing many large resources can be slow on the ember UI

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#35377]
https://github.com/rancher/rancher/issues/25487

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.5-6ff6d08b210f5ce59f4c8dac817ae63af75a5d76-head | 2.5.11 was used for comparison 
Rancher cluster type: HA

Downstream cluster type: ec2 node cluster
Downstream K8s version: v1.20.13 for 2.5-head | 1.20.12 for 2.5.11

----------

### Testing: ###

deployed 1500 pods, 500 services, 500 ingresses, 500 secrets, 500 config map

Config maps: on average ~2x faster response time
Secrets: on average ~20-25% faster response time

![compare](https://user-images.githubusercontent.com/40282141/146276812-132feea5-1197-43d7-8fd1-bd63a6afe92c.jpg)

didn't notice any improvements for other resources
confirmed that resources are listed correctly
confirmed that pages load faster after upgrade from 2.5.11 to 2.5-head
