### ISSUE TITLE
[2.6] Installed app detail page does not show related resources while app is being deployed

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#35388]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): both
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): all

**Information about the Cluster**
- Kubernetes version: all
- Cluster Type (Local/Downstream): both

**Describe the bug**
Installed app detail page does not show related resources while app is being deployed

**To Reproduce**
Install any app from the App Marketplace.

**Result**
While an app is being deployed, the Installed app detail page does not show the related resources of the helm installation:

![Bildschirmfoto 2021-06-30 um 12 10 03](https://user-images.githubusercontent.com/243056/124621926-f43dcf80-de7a-11eb-860f-b6bef94a852a.png)

The related resources are only displayed, once the app is fully deployed

![Bildschirmfoto 2021-06-30 um 12 13 21](https://user-images.githubusercontent.com/243056/124621991-00c22800-de7b-11eb-87b7-615b1b9eb6b1.png)

**Expected Result**
It would be great to show the related resources earlier, to make it easier and more obvious why an installation may have failed or is currently stuck and to visualize the progress better.

**Additional context**
It looks like the related resources are potentially already filtered out on the backend, if the app status is not "deployed" but something else like failed or in progress (https://github.com/rancher/wrangler/blob/master/pkg/summary/cattletypes.go#L31).

The UI is only showing what the API provides, see https://github.com/rancher/dashboard/issues/3401.

For Fleet GitRepos this works nicely and you can see the resources directly when they are created on the fleet detail page.

**Comment by bashofmann** [comment]
Still relevant.

**Comment by bashofmann** [comment]
Still relevant.

**Comment by bashofmann** [comment]
Still relevant.

**Comment by bashofmann** [comment]
Still relevant.

**Comment by bashofmann** [comment]
Still relevant.

**Comment by bashofmann** [comment]
Still relevant.

**Comment by bashofmann** [comment]
Still relevant.

**Comment by bashofmann** [comment]
Still relevant.

**Comment by BBQigniter** [comment]
those issues sound similar

https://github.com/rancher/rancher/issues/34842
https://github.com/rancher/rancher/issues/36470

we are seeing too some inconsistent behavior - with some "resources" it works, with others not

**Comment by BBQigniter** [comment]
Still relevant.
