### ISSUE TITLE
Rancher does not allow editing/upgrading prometheus parameters

### ISSUE THREAD

**Issue by angeloudy** [rancher/rancher#35397]
I'd like to edit the statefulset for prometheus, but rancher doesn't allow me to do it.
After editing it from the UI, I can see the service got redeployed, but the yaml file just got reverted.

Also, I'd like to upgrade prometheus to a newer version, but I don't want to upgrade rancher yet. Simply changing the image in the yaml file doesn't work. The service got redeployed, then reverted back to v2.18.2.

My rancher version: 2.5.2
kubernetes version: 1.19.4

**Comment by Martin-Weiss** [comment]
I assume you have to edit the prometheuses.monitoring.coreos.com rancher-monitoring-prometheus CRD object or the helm values. AFAIK the prometheus statefulset is created and maintained by the prometheus operator based on the CRD.

**Comment by angeloudy** [comment]
@Martin-Weiss 
Thanks updating through helm worked. Since I created my cluster with terraform rancher2 provider, I added `"prometheus.image.tag" = "v2.22.0"` in `cluster_monitoring_input`. I was trying to upgrade prometheus in order to fix https://github.com/prometheus/prometheus/issues/7955
