### ISSUE TITLE
Feature Request: View multiple Logs in UI

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#3539]
It would be incredibly awesome if you could view multiple container logs at the same time on rancher UI. In other devops tools, when viewing logs, I have seen the ability to "minimize" the log window, which then puts it in the lower left corner of the browser window. You can then open another set of logs, and minimize that. Then they allow you to open both minimized windows in like a split screen view, or even drag-able "modals". 

This would be very helpful when trying to debug multiple containers that communicate with each-other. 

Bonus points if you could get this to work for "exec shell" as well.

**Comment by vincent99** [comment]
I would rather do pop-out into a new window (#2360) and let you use your own window manager than reimplement Windows 3.11 in Javascript.  Though Azure's control panel apparently disagrees.
