### ISSUE TITLE
fluentd stops sending logs to elasticsearch

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#35395]
SURE-3427
SURE-3858

Rancher Cluster:

Rancher Cluster:
Rancher version: SUSE Rancher 2.6.0
Number of nodes:
Node OS version: SLES15-SP2

Downstream Cluster:
Number of Downstream clusters:
Node OS: SLES15-SP2
RKE/RKE2/K3S version: RKE2
Kubernetes version: v1.21.4+rke2r2
CNI:

Other details:

Rancher-Cluster: SUSE Rancher 2.6.0 with Kubernetes version v1.21.4+rke2r2 (SLES15-SP2) * Cluster with logging problem: v1.21.4+rke2r2 (SLES15-SP2) * Installed Logging-Chart (over Rancher Marketplace) 100.0.0+up3.12.0 (Current) (installed as default / vanilla / no changes were made to config during or after the installation)

Issue description:

**Customer configured the logging with elk stack with OpenSearch and OpenSearch dashboards. after few hours fluentd stop flooding the logs. after restarting the pod again it is flooding. LivelenessProbe is enabled in the fluentd pod but still seeing the issue.

We have increased the buffer settings and tried all other recommendations mentioned in our documentation [Rancher2] Logging v2 ClusterFlow, ClusterOutput, Flow, Output Examples and Best Practices rancher/docs#3449 then after 24 hrs again the problem reappears.

The problem is similar to the Github issue: 

https://github.com/rancher/rancher/issues/34662
Checked for the Ruby plug-in issue

Repro steps:

1. Installed Logging-Chart (over Rancher Marketplace) 100.0.0+up3.12.0 (Current) with default values

2. Once its successful, Upgrade the chart with OpenSearch components like mentioned below

helm upgrade --install opensearch opensearch-1.0.0.tgz -n logging-test -f opensearch.values.yaml
helm upgrade --install dashboard opensearch-dasbhoards-1.0.0.tgz -n logging-test -f opensearch-dashboard.values.yaml
3. Configured a ClusterFlow and ClusterOutput to flood the logs to ELK and check the logs

Actual behavior:
Fluentd stops flooding the logs after a few hrs and sees the below error message in the logs,  Connection timeout..

What are we trying to do? *

We have installed an ELK stack with opensearch & opensearch-dashboards (https://github.com/opensearch-project/helm-charts) (problem also occurs with bitnami ELK stack) * Configured an ClusterFlow and ClusterOutput * So far so good - most things works as expected, logs are flowing to the opensearch-master's and logs are visible and searchable in the opensearch-dashboard

What's going wrong? *

Out of nowhere, the fluentd pod seems to stop sending data to opensearch-master's which in turn means that are no more logs are visible in the opensearch-dashboard * There is no log output in the pods from the cattle-logging-system (first of all, no error logs) * Also no error logs in `kubectl exec -n cattle-logging-system rancher-logging-fluentd-0 – tail -f /fluentd/log/out` * The problem can be "fixed" if we restart the fluentd pod - logs are flowing again to the opensearch-master until (out of nowhere) it stops to work again *

**Comment by Tejeev** [comment]
Related: 
- https://github.com/rancher/rancher/issues/29952
- https://github.com/rancher/docs/issues/3449

**Comment by ronhorton** [comment]
**Pass** Verified in `2.6.4-rc14` and logging version `100.1.1+up3.17.3`

tested in rke1 and rke2 downstream clusters 
confirmed logging output to elasticsearch

**Comment by superseb** [comment]
Rancher logging `100.1.1+up3.17.3` includes fluent-bit 1.8.15 which should resolve multiple issues, see https://github.com/fluent/fluent-bit/issues/4505#issuecomment-1081115291

**Comment by ronhorton** [comment]
confirmed rancher/mirrored-fluent-fluent-bit:1.8.15 is in rancher-images.txt for 2.6.4-rc17
