### ISSUE TITLE
[Backport 2.5][Logging v2] Add option to disable automation JSON parsing

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#35393]
Backport https://github.com/rancher/rancher/issues/34720 to 2.5.x

An option already exists for this in the upstream logging chart. The solution will likely involve exposing the 
spec.fluentbit.filterKubernetes.Merge_Log field on every relevant Logging CR.

SURE-3272

**Comment by SheilaghM** [comment]
https://github.com/rancher/charts/pull/1590

**Comment by ronhorton** [comment]
**Reopening**

1. on an active cluster, click `Explore`
2. click on `Apps & Marketplace`
3. click on `Charts`
4. click on `Logging`
5. select **chart version 100.0.1+up3.12.0**
6. click `Install`
7. click `Next`
8. click `edit yaml`
9. click `Install`

`spec.fluentbit.filterKubernetes.Merge_Log` is NOT exposed in yaml

![Screen Shot 2021-12-23 at 11.49.18 AM.png](https://zube.io/files/rancher/161cbdebdd9429a6912bb51f816f8075-screen-shot-2021-12-23-at-11-49-18-am.png)

**Comment by annablender** [comment]
Thanks for testing this @ronhorton ! This looks like a regression. I'm not on logging anymore but I can take a look and try to figure out what happened.

**Comment by annablender** [comment]
Some confusion with testing. Rancher logging chart yaml now shows the exposed Merge_Log fields. Also confirmed in UI for chart versions 3.12-15. Ready to close.

@ronhorton 
<img width="1563" alt="image" src="https://user-images.githubusercontent.com/12955547/148135426-6ac658d5-5a96-4aca-a7e1-82df5924f4b9.png">

**Comment by ronhorton** [comment]
**PASS** Verified in `2.5-head Commit ID 07a745a`

updating the ui-dashboard-index setting to https://releases.rancher.com/dashboard/release-2.5/index.html in global setting > advanced exposed the changes.
