### ISSUE TITLE
[Bug] A provisioning failed node can't be fully removed in the rancher dashboard

### ISSUE THREAD

**Issue by FrankYang0529** [rancher/rancher#35398]
**Describe the bug**
When you delete a provisioning failed node in the rancher dashboard, it can't be fully removed. When it is provisioning, we can see a HarvesterMachine CR and a VM are created. When it is failed and we try to delete it, we can observe the HarvesterMachine CR and the VM are deleted, but the Machine CR is still there.

**To Reproduce**

1. Create a 3-node RKE2 cluster on Harvester through node driver with Rancher v2.6.2.
2. Wait for the nodes to create.
3. Since the resource is not enough, a node can't be scheduled successfully. Wait for the provisioning failed.
4. Delete the provisioning failed node.

**Result**
Machine CR is still there but HarvesterMachine CR and VM are deleted.

**Expected Result**
Machine CR is deleted.

**Screenshots**
![Screen Shot 2021-11-08 at 3 41 41 PM](https://user-images.githubusercontent.com/4927361/140702424-24c89f26-c3b5-439d-8a74-922306666ade.png)
![Screen Shot 2021-11-08 at 3 42 10 PM](https://user-images.githubusercontent.com/4927361/140702481-9d457d36-24d6-4586-bede-59d4821291c5.png)
![Screen Shot 2021-11-08 at 3 43 15 PM](https://user-images.githubusercontent.com/4927361/140702722-6a8cc448-69e1-464b-9321-2025007771ca.png)

**Additional context**
I tried to remove the finalizer `machine.cluster.x-k8s.io` in Machine CR. The Machine CR is still not deleted, but it will go to the provisioning phase again. Also, a HarvesterMachine CR and a VM will be created again.

Link to Harvester https://github.com/harvester/harvester/issues/1389.

**Comment by guangbochen** [comment]
https://github.com/rancher/rancher/issues/34945

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/1389#issuecomment-975304785
