### ISSUE TITLE
[Backport] v2.5: Cannot upgrade apps with deployments that were created in ember

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#35407]
**Original Issue:**
https://github.com/rancher/rancher/issues/34700

**Original PR:**
https://github.com/rancher/rancher/pull/35202

**Comment by anupama2501** [comment]
Blocked by https://github.com/rancher/rancher/issues/35820

**Comment by anupama2501** [comment]
2.5-head 9dab145
Verified the upgrade works if the `apps.cattle.io/migrated": "true"`annotation is added in a curl command but not from the dashboard UI.

curl command verification steps:

- Create the app[app2] aws-event-sources from apps & marketplace in addition to the one created from ember[app1].
- From apps & market --> upgrade the app2 and in the network tab, copy the post request as copy as cURL
- edit the copied curl request by replacing the namespaces and names with the app details created in ember and add the annotation apps.cattle.io/migrated": "true"`.
- Run the curl command and from the UI --> apps & market, upgrade goes through without any error.
- Most recent operations --> helm --> view logs show successful upgrade logs


Keeping the issue open as a dashboard fix is needed https://github.com/rancher/dashboard/issues/4812#issuecomment-999944955

**Comment by anupama2501** [comment]
Blocked by https://github.com/rancher/rancher/issues/36120

**Comment by anupama2501** [comment]
Verified on 2.5.12-rc4

Update, upgrade and deletion of the apps post migration works as expected after the dashboard annotations were added 
https://github.com/rancher/dashboard/issues/4812#issuecomment-1007836287
