### ISSUE TITLE
CoreDNS 1.8 does not work with SRV queries

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#35404]
SURE-3622

**Rancher Server Setup**
- Rancher version: 2.5.11

**Information about the Cluster**
- Kubernetes version: v1.20.11-rancher1-1
-CoreDNS 1.8
* Custom = Using kerberos auth for applications requires SRV 

**Describe the bug**
 k8s 1.20.11 early this week. Users started reporting that a couple of their workloads started failing DNS resolution when authenticating via kerberos to external services.

It seemed to be related to that workloads alpine base (suspicion, not verified) AND that workload (python/flask connecting to kerberos kdc thing).

Not entirely sure if related, but the CoreDNS logs were full of i/o timeout errors when reaching out to external DNS servers.

**Troubleshooting Steps**
Most other DNS requests worked. When the issue was happening, we were able to resolve via getent from swiss-army-knife containers, but not their workload.

We thought it was due to alpine not shipping /etc/nsswitch.conf, but that ended up not being related.

Eventually, they reverted CoreDNS back to the 1.7.0 tag and everything began to work.

**Result**
SRV requests generate i/o timeout errors.

**Expected Result**
SRV requests should succeed.

**Additional context**
Upstream issue: https://github.com/coredns/coredns/issues/4927  fixed in CoreDNS 1.8.7 which is not yet released.

**Comment by bentastic27** [comment]
It appears that 1.8.7 is available now as well as 1.9.0 as of an hour ago.

**Comment by snasovich** [comment]
k8s versions starting from v1.23.4-rancher1-1 (bundled since Rancher v2.6.4 release) include CoreDNS 1.9.0+ with this issue fixed. Closing.
