### ISSUE TITLE
Use Container Name option is not being set during service/container create

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3540]
Version - master ui 2/4

Steps:
1.  Add a Service
2.  Under Advanced Options/Networking, click on the "Use the container name" radio button
3.  Click on Create then Upgrade or Clone the service
4.  Go to Advanced Options/Networking

Results:  The "Use the container name" option is not selected.

Expected:  "Use the container name" should be selected

**Comment by vincent99** [comment]
This should have been fixed as part of the issue with all the clone problems

**Comment by tfiduccia** [comment]
Version - master 3/10
Verified fixed
