### ISSUE TITLE
Helm chart server SSL certificate error https://releases.rancher.com/server-charts/stable

### ISSUE THREAD

**Issue by jmatsushita** [rancher/rancher#35419]
Attempting to download helm charts for rancher from https://releases.rancher.com/server-charts/stable or https://releases.rancher.com/server-charts/latest results in an SSL certificate error:
```
$ curl -v https://releases.rancher.com/server-charts/stable
...
* Server certificate:
*  subject: CN=*.storage.googleapis.com
*  start date: Oct 18 09:44:18 2021 GMT
*  expire date: Jan 10 09:44:17 2022 GMT
*  subjectAltName does not match releases.rancher.com
* SSL: no alternative certificate subject name matches target host name 'releases.rancher.com'
* Closing connection 0
```

Also:
```
$ helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
Error: looks like "https://releases.rancher.com/server-charts/latest" is not a valid chart repository or cannot be reached: Get "https://releases.rancher.com/server-charts/latest/index.yaml": x509: certificate is valid for *.storage.googleapis.com, *.googleapis.com, commondatastorage.googleapis.com, *.commondatastorage.googleapis.com, storage.googleapis.com, storage.mtls.googleapis.com, *.appspot.com.storage.googleapis.com, *.content-storage.googleapis.com, *.content-storage-p2.googleapis.com, *.content-storage-upload.googleapis.com, *.content-storage-download.googleapis.com, *.storage-upload.googleapis.com, *.storage-download.googleapis.com, not releases.rancher.com
```

**Comment by teknologista** [comment]
Same here

**Comment by scholtenmartijn** [comment]
Same here as well

**Comment by SoutisV** [comment]
same here

**Comment by Oether** [comment]
Same for me.

**Comment by dkEdgPet** [comment]
Same here

**Comment by JanMa** [comment]
FYI, the following works as a temporary fix:
```
helm repo add rancher-latest http://releases.rancher.com/server-charts/latest
```

**Comment by lukasjarosch** [comment]
this just prevented us from migrating a prod environment

**Comment by amaxi** [comment]
Same error: 
helm fetch rancher-latest/rancher
Error: Get "https://releases.rancher.com/server-charts/latest/rancher-2.6.2.tgz": x509: certificate is valid for *.storage.googleapis.com, *.googleapis.com, commondatastorage.googleapis.com, *.commondatastorage.googleapis.com, storage.googleapis.com, storage.mtls.googleapis.com, *.appspot.com.storage.googleapis.com, *.content-storage.googleapis.com, *.content-storage-p2.googleapis.com, *.content-storage-upload.googleapis.com, *.content-storage-download.googleapis.com, *.storage-upload.googleapis.com, *.storage-download.googleapis.com, not releases.rancher.com

helm repo update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "rancher-latest" chart repository (https://releases.rancher.com/server-charts/latest):
        Get "https://releases.rancher.com/server-charts/latest/index.yaml": x509: certificate is valid for *.storage.googleapis.com, *.googleapis.com, commondatastorage.googleapis.com, *.commondatastorage.googleapis.com, storage.googleapis.com, storage.mtls.googleapis.com, *.appspot.com.storage.googleapis.com, *.content-storage.googleapis.com, *.content-storage-p2.googleapis.com, *.content-storage-upload.googleapis.com, *.content-storage-download.googleapis.com, *.storage-upload.googleapis.com, *.storage-download.googleapis.com, not releases.rancher.com

**Comment by soxyl** [comment]
Got the same error on the `install-docker` scripts.

```
wget https://releases.rancher.com/install-docker/19.03.9.sh
--2021-11-09 16:18:02--  https://releases.rancher.com/install-docker/19.03.9.sh
SSL_INIT
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving releases.rancher.com (releases.rancher.com)... 172.217.168.80, 2a00:1450:400a:808::2010
Connecting to releases.rancher.com (releases.rancher.com)|172.217.168.80|:443... connected.
The certificate's owner does not match hostname ‘releases.rancher.com’
```

**Comment by gibbonsryan** [comment]
Same issue here:

```
+ helm_v3 install --namespace cattle-system rancher https://releases.rancher.com/server-charts/latest/rancher-2.6.2.tgz --values /config/values-01_HelmChart.yaml
Error: failed to download "https://releases.rancher.com/server-charts/latest/rancher-2.6.2.tgz" (hint: running `helm repo update` may help)
```

**Comment by beatkind** [comment]
I think this is a global problem:

```
> openssl s_client -connect releases.rancher.com:443 </dev/null 2>/dev/null | openssl x509 -noout -text | grep DNS:

DNS:*.storage.googleapis.com, DNS:*.googleapis.com, DNS:commondatastorage.googleapis.com, DNS:*.commondatastorage.googleapis.com, DNS:storage.googleapis.com, DNS:storage.mtls.googleapis.com, DNS:*.appspot.com.storage.googleapis.com, DNS:*.content-storage.googleapis.com, DNS:*.content-storage-p2.googleapis.com, DNS:*.content-storage-upload.googleapis.com, DNS:*.content-storage-download.googleapis.com, DNS:*.storage-upload.googleapis.com, DNS:*.storage-download.googleapis.com
```

**Comment by valpfft** [comment]
Looks like san is fixed

```
❯ openssl s_client -connect releases.rancher.com:443 </dev/null | openssl x509 -inform pem -text | grep DNS
depth=2 C = US, O = Amazon, CN = Amazon Root CA 1
verify return:1
depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
verify return:1
depth=0 CN = releases.rancher.com
verify return:1
DONE
                DNS:releases.rancher.com, DNS:*.releases.rancher.com
```
                
And `helm repo add` works correctly

```
❯ helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
"rancher-stable" has been added to your repositories
```

**Comment by vincent99** [comment]
DNS for rancher.com was moved and CloudFlare was no longer providing the SSL cert/termination in front of the the google bucket.  CloudFront is doing that now.
