### ISSUE TITLE
3 master Node RKE cluster goes down if any one master node goes down

### ISSUE THREAD

**Issue by kunal-sharma-live-com** [rancher/rancher#35418]
**Rancher Server Setup** 
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: private ca cert

**Information about the Cluster**
- Kubernetes version: 1.19.6
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

I have 3 node RKE K8s cluster with all three nodes having etcd,control plane and worker roles. All works well, however if any node goes down,whole cluster becomes inaccessible. I have tried changing ip to active node within kube config file but still cluster doesnt comes up until the node went down comes back again.

Docker version - 19.03.14
RHEL - 8.2
RKE 1.2.4

**To Reproduce**
 

**Result**

**Expected Result**

Expected result is if any master node goes down, cluster should still work fine
**Screenshots**

**Additional context**

**Comment by tuduongquyet** [comment]
I'm facing the same issue with all three nodes having etcd,control plane and worker roles
