### ISSUE TITLE
[Backport] v2.5: Add support for annotation that prevents helm install and v1 App deletion when deleting v3 App

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#35410]
**Original Issue:**
https://github.com/rancher/rancher/issues/34701

**Original PR:**
https://github.com/rancher/rancher/pull/35202

**Comment by anupama2501** [comment]
blocked by https://github.com/rancher/rancher/issues/35820

**Comment by anupama2501** [comment]
On v2.5-head 777b5d4

- Install aws-event-sources version v0.1.4 on ember UI
- Migrate the app by adding all the required annotations as mentioned here https://github.com/rancher/dashboard/issues/4812#issuecomment-999944955
- From the ember UI, delete the app aws-event-sources/ `kubectl delete apps.project.cattle.io aws-event-sources -n p-mr57l `
- App is not deleted from the explorer UI but only from the ember UI.

**Comment by cbron** [comment]
currently qa blocked by: https://github.com/rancher/dashboard/issues/4812

**Comment by anupama2501** [comment]
Verified this is working on 2.5.12-rc2 as well.
