### ISSUE TITLE
Namespace is stuck in removing when a resource eg, config map with a finalizer is created in this namespace

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35427]
**Rancher Server Setup**
- Rancher version: `v2.5.8`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.19.8+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.20.11`
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 1 worker, 1 etcd, 1 cp`

**Describe the bug**
Namespaces are stuck in removing when we try to delete the namespaces that have a resource with a finalizer created in those namespaces.

**To Reproduce**
1. Create a downstream cluster[can be checked on local too]
2. In the downstream cluster create a project P1 
3. Create a namespace in P1 - ns1
4. Import the following configmap yaml file in ns1
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: stuck
  finalizers:
  - stuck.io/stuck
```
5. Delete the namespace ns1

**Result**
Namespace ns1 will be stuck in removing 

**Expected Result**
Expected the namespace to be deleted.

**Additional context**
Issue is seen on v2.6.2 as well. 
Issue is seen if we create a workload with a finalizer defined in the yaml

**Comment by snasovich** [comment]
@anupama2501 , I believe this functions as designed - if there is an object in the namespace that cannot be deleted, namespace cannot be deleted until all objects are gone from it.

**Comment by snasovich** [comment]
@anupama2501 , see the explanation above. Please close if you agree with the resolution.

**Comment by anupama2501** [comment]
@snasovich that sounds good! closing the ticket
