### ISSUE TITLE
Rancher (latest) don't work on rke2 v1.22.3+rke2r1

### ISSUE THREAD

**Issue by bjornjorgensen** [rancher/rancher#35425]
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

RKE2 latest is v1.22.3+rke2r1 so I did upgrade my RKE2 install and rancher don't work. So I try to upgrade rancher and rancher 2.6.1 (latest) is incompatible with Kubernetes v1.22
helm upgrade rancher rancher-latest/rancher --namespace cattle-system --set hostname=  ... 

Error: UPGRADE FAILED: chart requires kubeVersion: < 1.22.0-0 which is incompatible with Kubernetes v1.22.3+rke2r1

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

**To Reproduce**
 

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by manishmaharjan** [comment]
I have now same problem too

**Comment by superseb** [comment]
This is tracked in https://github.com/rancher/rancher/issues/34060
