### ISSUE TITLE
Rollback do Rancher pod scale-back for you

### ISSUE THREAD

**Issue by wpwoodjr** [rancher/rancher#35423]
**Is your feature request related to a problem? Please describe.**
During a rollback (https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/rollbacks/) the instructions say:
> While restoring Rancher on the same setup, the Rancher deployment is manually scaled down before the restore starts, then the operator will scale it back up once the restore completes. As a result, Rancher and its UI will be unavailable until the restore is complete. While the UI is unavailable, use the original cluster kubeconfig with the restore YAML file: kubectl apply -f restore.yaml.

Manual scale-down means that the user must prepare and save a restore yaml file before restoring, and also must use the original kubeconfig file.

**Describe the solution you'd like**
Rancher does the scale-down when the restore is applied via the UI.

**Describe alternatives you've considered**
Manual scale down.

**Additional context**
@nickgerace recommended I file this issue.

**Comment by nickgerace** [comment]
original issue: https://github.com/rancher/docs/issues/3642
