### ISSUE TITLE
[2.5] [Feature Charts] Stop Releasing non-user-facing dependency charts

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#35432]
Tracking the effort of stoping Releasing non-user-facing dependency charts in the rancher v2.5 line.
 
- [ ] The following sub-charts for `rancher-monitoring` will not be released as individual charts:

- rancher-grafana
- rancher-node-exporter
- rancher-kube-state-metrics
- rancher-prometheus-adapter
- rancher-windows-exporter

- [ ] The following sub-charts for `rancher-istio` will not be released as individual charts:
- rancher-kiali-server
- packages/rancher-tracing

- [x] The following sub-charts for `rancher-alerting-drivers`  will not be released as individual charts:
- rancher-prom2teams
- rancher-sachet

---------

See the issue for v2.6 for more info: https://github.com/rancher/rancher/issues/35222

**Comment by PennyScissors** [comment]
Closing this issue as we already added `doNotRelease: true` to the charts listed above in the 2.6 and 2.7 version lines.
