### ISSUE TITLE
Rancher 2.6.2 does not show all events for failing pods

### ISSUE THREAD

**Issue by xhejtman** [rancher/rancher#35441]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart):
   - helm
   - rke2 1.21.6-rke2r1

It seems that rancher gui does not show all events for failing pods. 

E.g.:
```
  Warning  Failed     9m16s (x8 over 10m)   kubelet            Error: container has runAsNonRoot and image will run as root (pod: "testt-6fc6648c68-bwvlw_mff-prod-ns(4889627f-9c24-4bf2-a3c6-6dfae7dd34aa)", container: container-0)
  Normal   Pulled     9m16s                 kubelet            Successfully pulled image "ubuntu:20.04" in 1.059246069s
  Normal   Pulling    5m42s (x24 over 10m)  kubelet            Pulling image "ubuntu:20.04"
  Normal   Pulled     43s (x36 over 8m49s)  kubelet            (combined from similar events): Successfully pulled image "ubuntu:20.04" in 1.041318848s
```

is not displayed in gui, so user has no chance to see what's wrong.

**Comment by angakis** [comment]
We experience the same issue on Rancher v2.6.9. Is there any setting that would make pod events visible in the UI? Do you plan to fix this?

**Comment by hhstu** [comment]
rancher has 9999999999+ bug after v2.5.x 🤪
