### ISSUE TITLE
Node Templates | Location and Size info is not present on UI (API call does not return them)

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#35445]
**Rancher Server Setup**
- Rancher version: v2.6-2708725597f29f23bea92828e34a1355085ad746-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version: v1.21.5

**Describe the bug**

Location and Size for Node Templates are not present due to `GET v3/nodetemplates` not returning cloud config info such as "amazonec2Config"

**To Reproduce**
 
1. Log in as an admin
2. click on Main Menu (hamburger menu)
3. click Cluster Management 
4. expand RKE1 Configuration
5. click Node Templates
6. click Create
  provide with valid credentials and fill out RKE1 template (ec2)
7. Create a template 
8. Refresh the page

**Result**
Location and Size values are not present on UI because v3/nodetemplate call does not return cloud condig

**Expected Result**

Location and Size values are not present on UI

**Screenshots**
2.6-head vs 2.6.1

![26head](https://user-images.githubusercontent.com/40282141/141159930-f533afbd-743a-43ed-8080-8881e74ff912.jpg)

API call does not return location and size in 2.6-head

![ec2 no](https://user-images.githubusercontent.com/40282141/141160197-5ad19726-873e-463a-8f15-0a460ee57056.jpg)

this is how the API call returns location and size info in 2.6.1

![ec2 yes](https://user-images.githubusercontent.com/40282141/141160147-a298350d-0d85-4357-8945-68a502a04402.jpg)

**Additional context**

**Comment by paynejacob** [comment]
the 2.6.1 API response appears identical to the 2.6-head response.  This is likely a dashboard issue.

**Comment by paynejacob** [comment]
the 2.6-head response appears to be missing the amazonec2configuration section.

**Comment by paynejacob** [comment]
### Root cause
The performance improvements to norman we causing some deserialization issues with nodeTemplates on list.
 
### What was fixed, or what changes have occurred
Fixed how norman serializes nodeTemplates on list.
 
### Areas or cases that should be tested
List node templates and ensure all fields in the ui are valid.  I would also compare the responses of `/v3/nodeTemplate` with 2.6-head to 2.6.1 and ensure they are the same structure.
 
### What areas could experience regressions?
-
 
### Are the repro steps accurate/minimal?
yes

**Comment by snasovich** [comment]
Caused by improvements done for https://github.com/rancher/rancher/issues/25487 (added for linking purposes).

**Comment by sgapanovich** [comment]
### Test Environment: ###

- Rancher version: 
  - v2.6-96e243841bdad2743835e31ee8a85a5ffce093de-head 
  - 2.6.1 (to compare)
- Rancher cluster type: HA
- Docker version: 20.10

----------

### Testing: ###

AWS DO AZURE templates  were used for testing

- created identical templates using UI
  - confirmed UI sends the same schema and same data to backend via `POST v3/nodetemplate`
- updated an existing template using UI 
  - verified UI sends all updated data correctly via `PUT v3/nodetemplate` 
- compared `GET v3/nodetemplate` responses on "Node Templates" page
  - confirmed that schema and data is the same in responses for 2.6-head and 2.6.1
  - confirmed both UI show correct data
![same UI](https://user-images.githubusercontent.com/40282141/142451799-786e9d3a-7d40-4e34-aaf5-560216c8beff.jpg)

- compared `GET v3/nodetemplate` responses when creating a cluster
  - `GET v3/nodetemplates` returns correct information
    - was able to create a cluster using a template 
    - the created cluster used data from the template

----

while testing `v3/nodetemplates` noticed that `azureConfig` has a new parameter `"plan"`
![diff](https://user-images.githubusercontent.com/40282141/142454572-163f5650-5859-41b2-b816-9f7fc89cb154.jpg)
