### ISSUE TITLE
Auto theme breaks the header every half hour

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#3544]
The auto theme changes the stylesheet every half hour, and that for some reason makes the header break at the `<span>` for the access control warning and become 2 lines.

Can it not change the actual link elements unless the theme is actually changing (the screen flashes every half hour, which is also kind of annoying), and then not break the header :smile:

![image](https://cloud.githubusercontent.com/assets/753917/12859693/38392c44-cc15-11e5-9fa6-50a676e3d12f.png)

(ignore that this particular picture shows tabs that don't exist yet... nothing to see here, move along)

**Comment by tfiduccia** [comment]
Version 0.58.0-rc2
This is still reproducible

**Comment by westlywright** [comment]
@tfiduccia I have not seen this issue happen in the past couple weeks when running on auto. Have you been able to reproduce it?

**Comment by vincent99** [comment]
I think this is fixed, I haven't seen it lately..

**Comment by tfiduccia** [comment]
Version - master 3/8
Verified fixed
