### ISSUE TITLE
[Forwardport] Fix handler registration issue affecting access control

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#35446]
2.5 issue:
- rancher/rancher#31982

Relevant PR: 
- https://github.com/rancher/rancher/pull/35172

The changes from the above PR need to be forwardported into 2.6. This issue: https://github.com/rancher/rancher/issues/34732 included the fix for the access control cache, but not the registration fix.

Repro steps for testing this can be found here: https://github.com/rancher/rancher/issues/31982#issuecomment-942221068

**Comment by anupama2501** [comment]
verified on v2.6-head 4375161
1. Created an rke1 cluster on HA rancher server
2. Created a custom role with deployment as resources and verbs `get,list,create`
3. Enabled openldap and assigned user1 in default project in the rke1 cluster
4. Logged in as user1 and verified user1 has access to deployments only.
5. Updated the roles to only have configmaps with verbs `get,list,create` and removed deployments
6. Refreshed the URL of user1 and verified only config maps can be accessed.
