### ISSUE TITLE
Active Directory Integration not working

### ISSUE THREAD

**Issue by Dragnell87** [rancher/rancher#35456]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart):Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):RKE2
- Proxy/Cert Details:let´s encrypt

**Information about the Cluster**
- Kubernetes version:v1.21.4
- Cluster Type (Local/Downstream):Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider)

**Describe the bug**

I’ve got Rancher HA and trying to get AD provider working. I keep getting authentication failed error even though the credentials work. I verified the credentials in a separate LDAP client (ldapsearch).  Using the NETBIOS\username and UPN name format. I just can’t get this config working.

**Expected Result**

Should be able to enable the  Microsoft AD provider.

**Comment by modzilla99** [comment]
yeah same here! It seems to be broken... I was only able to login with an account whose given name was just one word. Then it would work, but if I've set first and last name then it does not work. 

In the end I just deployed keycloak and used their SAML provider for Rancher. Really sad tho...
