### ISSUE TITLE
Unable to provision clusters in latest v2.6-head

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#35454]
**Summary:**

I suspect this could be a fleet issue. If not, we should transfer it to rancher/rancher or the relevant project.

I can no longer provision any clusters, whether they be rke1 or rke2 in Rancher. I have not tried hosted providers or importing. This seems to happen regardless of the node driver type.

In the rancher logs we see:
```
2021/11/10 20:02:17 [ERROR] error in planner for 'fleet-default/dave-azuretest': secrets "dave-azuretest-bootstrap-template-gblwb-machine-plan" not found
2021/11/10 20:02:17 [ERROR] error in planner for 'fleet-default/dave-azuretest': secrets "dave-azuretest-bootstrap-template-gblwb-machine-plan" not found
```
And I noticed an entry below when I enable debug logging:
```
2021/11/10 20:05:58 [DEBUG] Searching for providerID for selector rke.cattle.io/machine=f225a6d3-425f-417e-b100-c650095d5178 in cluster fleet-default/dave-fleet-c, machine dave-fleet-c-pool1-75b6d55b5c-ktwnr: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-rvn8ltbz\" is forbidden: User \"u-5p7ztbex4v\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
```

This issue was identified in a recent v2.6-head build created 1-3 hours ago, tag `v2.6-25b1518bacbd5833435a494a463b2f253328d79c-linux-amd64` specifically was used for my testing.

-----

**Environment:**
Rancher version: v2.6-head `25b1518` 11/10/2021 ~11:45am Arizona time
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: any rke1 or rke2 node driver clusters
Downstream K8s version: any

**Steps to Reproduce:**
1. Try to provision an RKE1 or RKE2 cluster with node driver
 
**Expected Result:**
The cluster(s) to provision without any issues.

**Actual Result:**
The clusters will never get past the status "Non-ready bootstrap machine(s) dave-azuretest-pool1-ddfb8784-s7jxk: waiting for cluster agent to be available and join url to be available on bootstrap node" and are stuck in the provisioning state. 

**Additional Info:**
Slightly older v2.6-head build doesn't seem to have this problem. I don't recall the specific commit I was using prior I think it was from the day prior. But, based on reports form other QA folks this seems to be pretty recent.

**Comment by nickgerace** [comment]
Transferred to `rancher/rancher` because the latest `v2.6-head` build is from ~15 hours ago and Fleet charts (v0.3.8-rc1) were merged ~4 hours ago. While Fleet might still be an issue, `v2.6-head` appears to be broken for another reason. Regardless, _where_ the issue is happening is TBD, so transferring to this repository is appropriate.

**Comment by nickgerace** [comment]
@davidnuzik after the `v2.6-head` update yesterday, I no longer see this issue. Are we good to close and reopen if needed?

**Comment by davidnuzik** [comment]
Yep! Thanks - closing. This is no longer an issue.
