### ISSUE TITLE
Removed pipeline is visible until page refresh

### ISSUE THREAD

**Issue by kravciak** [rancher/rancher#35466]
To reproduce:
- run single node rancher in docker
- create rke2 single node cluster (DO infra provider) (can't reproduce on local cluster)
- open System -> default namespace
- open Resources -> pipelines -> configure repositories
- enable pipeline-example-go.git example repo
- click on repo menu (...) -> delete

Current result: Pipeline stays in removing state until page refresh

![Screenshot from 2021-07-15 14-33-51](https://user-images.githubusercontent.com/538604/125788819-7e8aee8c-ded5-4982-aba6-a5509cd4da1a.png)

Tested on master-head (e83ac8c) in both emberUI and iFrame in dashboard.

**Comment by davidnuzik** [comment]
The issue was transferred to rancher/rancher (backend) for consideration.
