### ISSUE TITLE
Wrong behavior of bind propagation in local volumes

### ISSUE THREAD

**Issue by adampl** [rancher/rancher#35467]
**Rancher Server Setup**
- Rancher version: 5.2.8
- Installation option: Docker

**Information about the Cluster**
- Kubernetes version: 1.21
- Cluster Type: Custom

**Describe the bug**
- Mount propagation doesn't propagate mounts existing in a volume before the pod creation
- Pod cannot be deleted before mounts propagated to the volume are unmounted

**To Reproduce**

1. Create empty folders `/local` and `/local/bar` on the host
2. Edit cluster YAML to add the necessary bind mount with the `rslave` option:
```yaml
services:
  kubelet:
    extra_binds:
      - "/local:/local:rslave"
```
3. Save and wait for cluster update to complete
4. Create a Persistent Volume of type Local, pointing to `/local`
5. Create a PV Claim to claim the PV
6. Create a Pod that mounts this PVC at `/foo`, with the `mountPropagation: HostToContainer` option
7. On the host, bind-mount some non-empty folder like `/bar` at `/local/bar` (`mount --bind /bar /local/bar`)
8. Execute shell in the pod and observe that `/foo/bar` is _not_ empty (good - the new mount propagates)
9. Delete the pod and notice that it never completes (bad - pod should be deleted)
10. Unmount `/local/bar` on the host (`umount /local/bar`)
11. Observe that now the pod can be deleted
12. Again mount `/local/bar` on the host
13. Then create a pod like the previous one (after the mount)
14. Execute shell in the pod and observe that `/foo/bar` _is_ empty (bad - preexisting mount doesn't propagate)

**Result**
- Existing mounts don't propagate to pod
- Pods with new mounts propagated cannot be deleted

**Expected Result**
- Existing mounts should propagate
- Pods with new mounts propagated should be deleted normally

**Additional context**
My thread on the Rancher forum: https://forums.rancher.com/t/bind-external-folders-to-kubelet-with-mount-propagation/36137

Useful command: `findmnt -o SOURCE,TARGET,PROPAGATION | grep local`

Useful docs:
https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/#extra-binds
https://kubernetes.io/docs/concepts/storage/volumes/#local
https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
https://docs.docker.com/storage/bind-mounts/
https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt

**Comment by micheleIT** [comment]
Could you please reopen this issue and take a look? I'm facing the same issue with. All mounts within a PV are shown empty until remounted at the host.

K8s: v1.23.6+rke2r2 
Rancher: v2.6.6

**Comment by adampl** [comment]
@micheleIT I would reopen but I don't have this option :(
