### ISSUE TITLE
Changing themes will cause page to break

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3546]
Version - master UI 2/4

Steps:
1.  Change theme

Results:  Not sure exactly what causes this to happen.  But every once in a while if I switch to Auto theme, my page breaks.  Here is screenshot plus stylesheet info:

![image](https://cloud.githubusercontent.com/assets/11514927/12860154/160d8090-cc18-11e5-94c3-99385296c3ac.png)

Expected:  Should not break

**Comment by vincent99** [comment]
I don't know the root cause either, but saw @tfiduccia do it several times

**Comment by westlywright** [comment]
@vincent99 The only time I was able to duplicate this was when i was getting the `422` error from the `userpreference` api regarding the double encoded strings. That seems to be resolved with the latest rancher release.

**Comment by vincent99** [comment]
I don't know how to cause it but it wasn't 422s.  She was just switching back and forth between light/auto/dark/auto/light.

Maybe at least add a check to the part that writes out the tag that it has a value?

**Comment by tfiduccia** [comment]
Version - 0.58.0-rc2

Still reproducible.  I can get this to reproduce by clicking on light, dark, auto and switching pages and then doing the light, dark, auto again.  It doesn't happen every time, but if you click back and forth between pages and change from dark/light to auto it will eventually happen.

**Comment by tfiduccia** [comment]
Can get this to reproduce now:

Steps:
1.  Go to API page
2.  Click on Auto theme, click on light theme, click on Auto theme twice
3.  Go to Help page
4.  Click on light theme, click on auto theme twice
5.  Go back to API page, click on light theme, click on Auto theme twice
6.  Repeat steps 3-5 until break

I normally only have to do this a couple of times to get it happen.  If you would like demo, let me know.

**Comment by tfiduccia** [comment]
Version - master 3/4
Verified fixed
