### ISSUE TITLE
vsphere CSI charts show incompatible version of chart for clusters on k8s 1.18.20

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35478]
**Rancher Server Setup**
- Rancher version: `v2.5.11`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.19.13+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.18.20`
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 3 worker, 1 etcd, 1 cp Vsphere`

**Describe the bug**
CSI charts version for v2.3.0 is applicable for k8s 1.19 - 1.21 but the chart version is also showing up for the Kubernetes version 1.18.20. 

**To Reproduce**
Create a vsphere node driver cluster on k8s version 1.18.20 

**Result**
From cluster explorer apps & market place CSI --> CSI version v2.3.0 is available in the chart versions

**Expected Result**
Expected the version to be not available for k8s v1.18.20

**Comment by deniseschannon** [comment]
@samkulkarni20 Can you have the QA team re-validate if this is still the case on v2.5-head? And if not, we can close the issue.

**Comment by rayandas** [comment]
While testing it on Rancher `v2.5-head` with Kubernetes `1.18.20` I saw chart repositories are not showing up. I tried to add chart repos manually but it's getting stuck (showing processing and not getting active). There is a known bug which is logged here. https://github.com/rancher/rancher/issues/35820 
So that bug needs to be fixed before validating this issue.

**Comment by rishabhmsra** [comment]
**Validated on rancher 2.5-head** (777b5d4) : **CSI v2.3.0 is still showing up on cluster with k8s v1.18.20-rancher1-3**

- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**

- Kubernetes version: `v1.18.20-rancher1-3`
- Cluster Type (Local/Downstream): Downstream infrastructure provider `3 worker, 1 etcd, 1 cp Vsphere`

**Validation steps:** 
- From cluster explorer apps & market place CSI --> CSI version v2.3.0 is available in the chart versions

**Result:**
- CSI v2.3.0 is still showing up on cluster with k8s v1.18.20-rancher1-3

**Expected Result:**
- CSI v2.3.0 should NOT show up cluster with k8s version 1.18

**Comment by rishabhmsra** [comment]
**Validated on rancher 2.5.12-rc1** : 
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Kubernetes version: `v1.18.20-rancher1-3`
- Cluster Type (Local/Downstream): Downstream infrastructure provider `3 worker, 1 etcd, 1 cp Vsphere`

**Result:**
- CSI v2.3.0 is NOT available on downstream cluster with `k8s v1.18.20-rancher1-3`. Hence closing the issue.
