### ISSUE TITLE
[2.5] Fix vSphere charts upgrade path

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#35476]
This issue goes together with this other issue: https://github.com/rancher/rancher/issues/35378

New charts:
- CPI 1.0.1 (Copy of 1.0.000 with `kubeVersion: <= 1.17` added)
- CSI 2.1.1 (Copy of 2.1.000 with `kubeVersion: <= 1.19` added)

Charts to hide:
- CSI 2.1.000 (Replaced by 2.1.1)
- CPI 1.0.000 (Replaced by 1.0.1)

### Current CPI and CSI charts in dev branches
Strikethrough means always hidden for user
| Chart | Rancher 2.5 |
|-------|-------------|
| CPI   | 1.0.000     |
|       | 1.0.100    |
|       |             |
| CSI   | 2.1.000     | 
|       | 2.3.0       |

### Expected CPI and CSI charts after all changes are done
Strikethrough means always hidden for user
Note: CPI 1.0.1 is a copy of CPI 1.0.000 with an additional kubeVersion, whereas 1.0.100 is an entirely new CPI chart. They are not the same chart.
| Chart | Rancher 2.5 |
|-------|-------------|
| CPI   | ~~1.0.000~~     |
| CPI   | 1.0.1  (kubeVersion <= 1.17)   |
|       | 1.0.100 (kubeVersion 1.18 - 1.21)    |
|       |             |
| CSI   | ~~2.1.000~~     |
|       | 2.1.1  (kubeVersion <= 1.19)   |
|       | 2.3.0 (kubeVersion 1.19 - 1.21)      |

**Comment by anupama2501** [comment]
on v2.5.11

On 2.5.11 with feature charts pointing to dev-v2.5-vsphere-release branch
Scenario #1

On 1.18 k8s version
Verify CPI 1.0.100 is available and can be installed successfully
Verify CSI 2.1.1 is available and can be installed successfully 

Scenario#2

On 1.20 k8s
Verify CPI 1.0.100 is available and can be installed successfully
Verify CSI 2.3.0 is available and can be installed successfully 


The charts for CPI and CSI as mentioned below are still showing up:
CPI `1.0.100 ` on k8s 1.18 and 1.20, 
CSI `2.1.000` and `2.3.0 ` for k8s 1.18 
CSI `2.1.000` and `2.1.1` for k8s 1.20

**Comment by rishabhmsra** [comment]
On Rancher v2.5.11 verified CSI and CPI checks with feature charts pointing to dev-v2.5-vsphere-release branch

**CPI 1.0.1 (kubeVersion <= 1.17) validation**
1. On k8s 1.17:
CPI 1.0.1 is available and installed successfully with kubeVersion: <= 1.17.

**CPI 1.0.100 (kubeVersion 1.18 - 1.21) validation**
1. On k8s 1.18:
CPI 1.0.100 is available and installed successfully with kubeVersion: 1.18 - 1.21.
2. On k8s 1.19:
CPI 1.0.100 is available and installed successfully with kubeVersion: 1.18 - 1.21.
3. On k8s 1.20:
CPI 1.0.100 is available and installed successfully with kubeVersion: 1.18 - 1.21.

**CSI 2.1.1 (kubeVersion <= 1.19) validation**
1. On k8s 1.17:
CSI 2.1.1 is available but installation is failing with below error:
```
helm install --namespace=kube-system --timeout=10m0s --values=/home/shell/helm/values-rancher-vsphere-csi-2.1.1.yaml --version=2.1.1 --wait=true vsphere-csi /home/shell/helm/rancher-vsphere-csi-2.1.1.tgz
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"
```
2. On k8s 1.18:
CSI 2.1.1 is available and installed successfully with kubeVersion: <= 1.19.
3. On k8s 1.19:
CSI 2.1.1 is available and installed successfully with kubeVersion: <= 1.19.

**CSI 2.3.0 (kubeVersion 1.19 - 1.21) validation**
1) On k8s 1.19
CSI 2.3.0 is available and installed successfully with kubeVersion: 1.19 - 1.21.
2) On k8s 1.20
CSI 2.3.0 is available and installed successfully with kubeVersion: 1.19 - 1.21.
