### ISSUE TITLE
ingress删除路径时页面直接跳转了

### ISSUE THREAD

**Issue by mulhyac** [rancher/rancher#35477]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.6` UI: `v2.5.6` |
|Route|`undefined`|

**Comment by bengray2** [comment]
It says: 
![image](https://user-images.githubusercontent.com/44791530/141434828-df68f7e0-32d2-4188-8ba8-9b1f6de2473b.png)

**Comment by kingsd041** [comment]
Please submit the issue in English
