### ISSUE TITLE
CAPI (Cluster API) update to version 1.0+

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#35489]
CAPI version 1.0.0 is available since 10/6/21 (https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.0.0) (in fact there is now 1.0.2 released - https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.0.2).

We should look into updating V2 cluster provisioning framework to be based on this GA version of CAPI.

**Comment by snasovich** [comment]
Want to do it early in the release cycle so there is more time to find any issues potentially caused by this change.
As the change itself, ensure we're not using `v1alpha4` CAPI CRDs and use `v1beta1` everywhere.

**Comment by thedadams** [comment]
These changes have no all been merged.

There should be nothing specific for QA to test here. The myriad of testing that will happen as we approach release will ensure that everything is working properly.
