### ISSUE TITLE
Some charts are not correctly deployed in airgapped environments

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#35485]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details: airgapped environment with a systemDefaultRegistry configured

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): In the local cluster when creating/importing a GKE, EKS or AKS cluster

**Describe the bug**
Hosted cloud cluster operator charts are not correctly deployed in airgapped environments. The configured systemDefaultRegistry is not correctly set on the rancher-gke-operator/rancher-eks-operator/rancher-aks-operator helm chart. The installation fails because the image is still being loaded from docker hub, which is not accessible.

**To Reproduce**
* Install Rancher in an airgapped environment with a systemDefaultRegistry
* Create an EKS cluster

**Result**
The rancher-eks-operator pod never comes up, because the systemDefaultRegistry is not added to the image.

**Expected Result**
The image should be coming from the systemDefaultRegistry

**Additional context**
The helm charts are trying to get the registry from `.Values.global.systemDefaultRegistry` instead of `.Values.global.cattle.systemDefaultRegistry`.

This is also the case for other charts like `rancher-external-ip-webhook`, `system-upgrade-controller` and `rancher-sriov`, see this hotfix: https://github.com/bashofmann/charts-1/commit/88e3cc6e2ce64a420a73a1a8c2269195669c46af.

**Comment by jiaqiluo** [comment]
relevant code blob in rancher/rancher: https://github.com/rancher/rancher/blob/cb7de4e6c3d7e783828dc662b1142c1f9ae5edbe/pkg/controllers/dashboard/hostedcluster/controller.go#L115-L132

**Comment by cbron** [comment]
That rancher code is correct, its the kev2 code thats wrong: 
https://github.com/rancher/eks-operator/blob/master/charts/eks-operator/values.yaml#L1-L2

**Comment by bashofmann** [comment]
Should I open separate tickets for rancher-external-ip-webhook, system-upgrade-controller and rancher-sriov?

**Comment by cmurphy** [comment]
@bashofmann I'll address them in this ticket

**Comment by MbolotSuse** [comment]
| Image Name | Image Tag | Image ID |  Image Digest (SHA-256) |
|------------|-----------|----------|-------------------------|
| rancher/rancher | v2.6.3-rc6 | 1248a953337e | 0dc7c8318ac683311332a4bc177f7ed08b5713ef6012d2e621ba978c4f5ae39c |
| httpd | 2 | 8362f2615893 | 0c8dd1d9f90f0da8a29a25dcc092aed76b09a1c9e5e6e93c8db3903c8ce6ef29 | 
| registry | 2 | b8604a3fe854 | 169211e20e2f2d5d115674681eb79d21a217b296b43374b8e39f97fcf866b375 | 

Validation Setup: 

- Create two digital ocean droplets, one with the DNS record of mbolot-rancher.cp-dev.rancher.space and one with the DNS record of mbolot-registry.cp-dev.rancher.space. Ensure docker is installed on both droplets.
- On the registry system, run `mkdir certs` and `mkdir auth` to create directories for the registry certs and username/pass.
- Use `openssl req -newkey rsa:4096 -nodes -sha256 -keyout certs/domain.key --addext "subjectAltName = DNS:mbolot-registry.cp-dev.rancher.space" -x509 -days 365 -out certs/domain.crt` to generate a cert for the docker install. Provide US as the country option (when prompted), and `mbolot-registry.cp-dev.rancher.space` and the domain name. Leave all other options blank.
- Use `read -s U` and `read -s P` to create a username/password for the registry.
- Use `docker run httpd:2 /bin/sh -c "htpasswd -Bbn $U $P" > auth/htpasswd` to generate the password file for the registry.
- Run the registry using `docker run -d --restart=always --name registry -v "$(pwd)"/auth:/auth -e "REGISTRY_AUTH=htpasswd" -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd -v "$(pwd)"/certs:/certs -e REGISTRY_HTTP_ADDR=0.0.0.0:443 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -p 443:443 registry:2`
- Follow the [rancher guide](https://rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/air-gap/populate-private-registry/), using the registry system. Use the 2.6.3-rc6 release to for the source of the images.
- Ssh into `mbolot-rancher.cp-dev.rancher.space`. Change /etc/docker/daemon.json to accept insecure connections to `mbolot-registry.cp-dev.rancher.space` using [this docker guide](https://docs.docker.com/registry/insecure/)
- Restart the docker daemon using `systemctl restart docker`
- Log into the registry using `docker login mbolot-registry.cp-dev.rancher.space`
- Pull the core rancher image using `docker pull mbolot-registry.cp-dev.rancher.space/rancher/rancher:v2.6.3-rc6`
- Run the rancher installation using `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e CATTLE_SYSTEM_DEFAULT_REGISTRY=mbolot-registry.cp-dev.rancher.space -e CATTLE_SYSTEM_CATALOG=bundled --privileged mbolot-registry.cp-dev.rancher.space/rancher/rancher:v2.6.3-rc6`
- Exec into the container using `docker exec -it $CONTAINER_ID sh`
- Follwing [this rancher guide](https://rancher.com/docs/k3s/latest/en/installation/private-registry/), add the details for the registry to the k3s config (include `configs."mbolot-registry.cp-dev.rancher.space".tls.insecure_skip_verify` as `true`, `configs."mbolot-registry.cp-dev.rancher.space".auth.user` and `configs."mbolot-registry.cp-dev.rancher.space".auth.password`.
- Restart the k3s cluster
- Log into rancher at `mbolot-rancher.cp-dev.rancher.space` and reset the password

Validation for `rancher/eks-operator` and `rancher/eks-operator-crd`:

- Create an AWS access key in the console
- In the rancher UI (for mbolot-rancher.cp-dev.rancher.space), go to `Cluster Management` and click `Create`. 
- Use the accss key generated for credentials, and provide a clustername and config options as desired.
- Create the cluster.
- Go to the `Explore Cluster` -> `local` in the sidebar. Ensure you can view all workloads for all namespaces.
- Validate that the `eks-config-operator` in the `cattle-system` namespace is using an image with the `mbolot-registry.cp-dev.rancher.space` prefix.

Status: Pass

Validation for `rancher/gke-operator` and `rancher/gke-operator-crd`:

- Following the [rancher documentation](https://rancher.com/docs/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/gke/), create a GKE service account and cluster.
- Go to the `Explore Cluster` -> `local` in the sidebar. Ensure you can view all workloads for all namespaces.
- Validate that the `gke-config-operator` in the `cattle-system` namespace is using an image with the `mbolot-registry.cp-dev.rancher.space` prefix.

Status: Pass

Validation for `rancher/aks-operator` and `rancher/aks-operator-crd`:

- Following the [rancher documentation](https://rancher.com/docs/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/aks/), create an AzureAD app registration and AKS cluster.
- Go to the `Explore Cluster` -> `local` in the sidebar. Ensure you can view all workloads for all namespaces.
- Validate that the `aks-config-operator` in the `cattle-system` namespace is using an image with the `mbolot-registry.cp-dev.rancher.space` prefix.

Status: Pass

@sowmyav27 @slickwarren 
The above is dev-validation for `aks-operator`, `gke-operator`, `eks-operator` (and their respective CRDS). Outside of that, there's also `rancher/externalip-webhook`, `rancher-sriov` , `rancher-sriov/sriov-crd` , `rancher-k3s-upgrader`, and `system-upgrade-controller`.

**Comment by slickwarren** [comment]
Validated that rancher/external-ip-webhook image was able to pull successfully on v2.6.3-rc7. 

**reopening for the following issue:**
* SUC v0.8.1 is not getting its image from the systemDefaultRegistry

repro steps:
* deploy an airgap setup v2.6.3-rc7
* deploy a downstream rke2 cluster (k8s 1.21.7)
  * when the cluster is active, check the workloads for SUC -> image being pulled is not from the registry

**Comment by brendarearden** [comment]
Available to test in rancher/rancher v2.6.3-rc8

**Comment by sowmyav27** [comment]
unable to provision k3s custom cluster -> images are not being pulled from systemDefaultRegistry - Logged - https://github.com/rancher/rancher/issues/35922

**Comment by slickwarren** [comment]
using rancher v2.6.3-rc8 in an HA Airgap setup:
* SUC v0.8.1 was able to deploy successfully using the systemDefaultRegistry image
* we will skip validation of `k3s-upgrader` as k3s in airgap has issues (filed above)
