### ISSUE TITLE
Cannot add member to custom cluster - x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by StoneCut** [rancher/rancher#35484]
**Rancher Server Setup**
- Rancher version: 2.5.1
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.19.3 and 1.19.7
- Cluster Type (Local/Downstream): Custom (Rancher-launched)

**Describe the bug**
When trying to add a member (AD) to a custom cluster (Rancher-launched) I receive an errors and member does not get added.

**To Reproduce**
 

**Result**
I receive an error and user does not get added:
_Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": x509: certificate has expired or is not yet valid: current time 2021-11-12T13:19:12Z is after 2021-10-22T13:04:54Z_

**Expected Result**
User gets added.

**Additional context**
I tried rotating all certificates via Rancher on another cluster and add the member there but this resulted in the same error. Do I need to rotate the certificates of the Rancher HA cluster instead? If so, how?

**Comment by alex-digicode** [comment]
On local cluster you need to do

**Comment by alex-digicode** [comment]
On the local cluster, you need  to remove cattle-webhook-tls certificate on secrets and then remove rancher-webhook pod

https://github.com/rancher/rancher/issues/35068#issuecomment-943155280

and possibly change the version of rancher-webhook:v0.2.0 to rancher-webhook:v0.1.1 to be able to recreate the certificate
https://github.com/rancher/rancher/issues/35068#issuecomment-943691271

**Comment by StoneCut** [comment]
I followed this procedure and it worked. Thank you.
https://rancher.com/docs/rancher/v2.6/en/troubleshooting/expired-webhook-certificates/

**Comment by obyerere** [comment]
if we delete it will it break anything

**Comment by ramnaresh9993** [comment]
> if we delete it will it break anything
no it will not break anything

**Comment by harshashenoy98** [comment]
> I followed this procedure and it worked. Thank you. https://rancher.com/docs/rancher/v2.6/en/troubleshooting/expired-webhook-certificates/

Thanks @StoneCut it worked for me as well

**Comment by asomara-equinix** [comment]
Thanks @StoneCut , it really worked.
