### ISSUE TITLE
Support Windows Server 2022

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#35487]
We are adding Windows Server 2022 support to Rancher as part of the 2.6 V2 Provisioning work for RKE2 Windows. 

rancher/windows to track https://github.com/rancher/windows/issues/104

Relevant PR for testing where 2004 SAC was removed and 2022 LTSC was added:
https://github.com/rancher/rancher/pull/35429

**Comment by slickwarren** [comment]
currently blocked from adding nodes to custom cluster: https://github.com/rancher/dashboard/issues/4581

**Comment by anupama2501** [comment]
RKE1 custom clusters blocked from adding windows nodes on https://github.com/rancher/rancher/issues/35614

**Comment by slickwarren** [comment]
waiting on the latest rke2 RC (required for testing windows 2022)

**Comment by slickwarren** [comment]
filed a blocking ticket for rke2: https://github.com/rancher/rancher/issues/35681
rke1 will not support 2022.

**Comment by sirredbeard** [comment]
@slickwarren All related blocking issues have been closed. Can this be moved to test?

**Comment by sowmyav27** [comment]
Still blocked by - https://github.com/rancher/dashboard/issues/4714, but we have a workaround that Caleb is looking into right now

**Comment by slickwarren** [comment]
We are able to deploy windows 2022, however we are having trouble with deployments (2.6-head 03ed782)
```
	Error: failed to start containerd task "nginx": hcs::System::CreateProcess nginx: The system cannot find the file specified.: unknown
```
@luthermonson has a setup and is investigating now.

**Comment by sirredbeard** [comment]
Currently investigating.

**Comment by luthermonson** [comment]
https://github.com/rancher/rancher/pull/35869
