### ISSUE TITLE
[Backport] 2.5x - Convert ServerVersion to downstream env var

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#35488]
We need to create a backport version of https://github.com/rancher/rancher/issues/34875 to be included in v2.5x. Please let me know if there are any questions.

**Comment by jakefhyde** [comment]
Do we want to backport #34876 instead? It is the successor to #34875, and redeploys the agent with the settings as environment variables on change, as opposed to setting the settings in the downstream.

**Comment by Jono-SUSE-Rancher** [comment]
Yes that's fine Jake - I didn't know of it's existence and was just backporting the original one so that we'd have it in place. If you think that is the correct one and it will work for what we need, let's do that. 
ccing: @PennyScissors to keep me honest.

**Comment by jakefhyde** [comment]
Issue Template: https://github.com/rancher/rancher/issues/34876#issuecomment-969195463

**Comment by jmcsagdc** [comment]
v2.5-777b5d4d5cffa482e8d348d003d76b22f71756b4-head

In a downstream cluster
1) Use API to update install-uuid to change the uuid a little in a conforming way: 
   Like so "value": "2b18f3a8-1b63-49e6-bf2e-3b7052e29c1b" becomes "value": "3c28f3a8-1b63-49e6-bf2e-3b7052e29c1b"
RESULT:
cattle-cluster-agent pod is redeployed

2) Deploy something like nginx-ingress
    Use API to update ingres-ip-domain (to nip.io)
RESULT:
cattle-cluster-agent pod is redeployed

3) Updating other settings did not cause a redeployment so far, but I'm checking a few more things

**Comment by jakefhyde** [comment]
@jmcsagdc By "Updating other settings", does that include the `server-version`? If so that may be alright, as in the "happy path" the `server-version` is only going to be upgraded through an actual release which should bump the agent image tag and trigger a redeployment anyway.

**Comment by jmcsagdc** [comment]
@jakefhyde as demonstrated, the URL change does not propagate through to the UI even though the API change sticks and the pods redeploy. 

The practical result of this is going *from nip.io* to xip.io or something doesn't actually affect the workload and the original URL continues to be routable while the new URL is not.

![URL-change-redeploy-but-no-update-ui](https://user-images.githubusercontent.com/15971368/147969605-d7e7720f-9f38-43c6-9cc4-76beef1a503c.jpg)

The other things tried here include the labels and annotations in the ingress-ip-domain which did not result in a redeployment.

**Comment by jakefhyde** [comment]
@jmcsagdc Going to try to repro this on my end and see if the ingress issue is caused by this or if it was present prior to merging.

**Comment by jmcsagdc** [comment]
The change to ingresses works as intended. We worked this together just now, so will close here after a brief description:

The migration path for someone wanting to do this change to a URL is to edit the value as described above in the API and then (1) add a new ingress pointing to the same workload (2) when the older URL ingress is no longer needed (like after a burn-in period), delete the older ingress. 

Both URLs for both ingresses pointing to the same workload will work and not conflict with each other.
