### ISSUE TITLE
Upgrade buttons say Error checking upgrades even if their specific library was not removed

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3548]
Version - master 2/4

Steps:
1.  Add glusterfs catalog with newest version
2.  Go to main stack page (not how the Upgrade button says "Up to date"
3.  Go to settings page
4.  Disable or enable the community Contributed library

Results:  You will get sent back to Stack page and the glusterfs stack now says "Error checking upgrades"

Expected:  glusterfs is not part of the community library, so it shouldn't be in error.

**Comment by vincent99** [comment]
This is just another way in which you're changing the catalog setting, it restarts the catalog API, and it's not up yet when you go ask for upgrade info.  Don't we already have an issue for that?

**Comment by tfiduccia** [comment]
Version - master 3/8
Yes, I think we have another issue for this.
