### ISSUE TITLE
RKE1 Downstream 1.22 stuck in provisioning

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#35496]
Create Rancher local cluster 1.22 and Provision a RKE1 Downstream cluster (any provider): 

Cluster is stuck in provisioning, with error msg: 
`2021/11/13 11:20:51 [ERROR] error syncing 'c-25m7f': handler cluster-provisioner-controller: error creating admin role: the server could not find the requested resource, requeuing`
<img width="1424" alt="Screen Shot 2021-11-13 at 11 25 50 AM" src="https://user-images.githubusercontent.com/16870565/141656620-1f04369a-0e65-4b16-b838-668a2d31b1f0.png">

https://github.com/rancher/rancher/issues/34054

**Comment by kinarashah** [comment]
- Available to test with v2.6-head, make sure it's an image after this build https://drone-publish.rancher.io/rancher/rancher/6862. 
- Update rke-metadata-config (Global settings -> rke-metadata-config) URL's branch from `dev-v2.6` to `dev-v2.6-122`
- Make sure `v1.22.3-rancher1-1` shows up as experimental when provisioning RKE1 clusters 
- Normal RKE1 provisioning tests for v1.22.3-rancher1-1

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/commit/01053b646f5def7e7cadd11b7c5dd9e6d273227d

**Comment by sowmyav27** [comment]
- On `v2.6-f487c8819d726109d8178894b6a4c082d5320b92-head` commit, deployed EC2 node driver and custom clusters using 1.22.3-rancher1-1 k8s version
- Cluster has come up Active. 
- `1.22.3-rancher1-1` does show up as Experimental and is not the default k8s version yet.
