### ISSUE TITLE
Do not start controllers for legacy features if not needed

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rancher#35503]
Many of the legacy features (logging v1, monitoring v1, etc) negatively impact performance because they are watching downstream resources in clusters cause addition bandwidth to be used. We would like to start the controllers for the downstream clusters (which we refer to as "user controllers") only if the legacy feature is in use.

**Comment by ibuildthecloud** [comment]
The following controllers will be deferred

- [ ] certexpiration
- [ ] clusterauthtoken
- [ ] networkpolicy
- [ ] alert
- [ ] approuter
- [ ] cis
- [ ] globaldns
- [ ] pspdelete
- [ ] helm
- [ ] logging
- [ ] monitoring
- [ ] pipeline
- [ ] systemimage

**Comment by deniseschannon** [comment]
We should also test an upgrade path where if the feature is enabled in an older version, then it continues to be usable in the upgraded Rancher.

**Comment by git-ival** [comment]
Legacy controllers deferral validation summary:
1. Created separate HA Rancher setups on 2.6.2 and 2.6.3 (using rke)
2. Installed monitoring v2 chart on both setups
  i. Setup components needed for outputting controller/handler metrics (https://github.com/rancher/rancher/wiki/How-to-setup-prometheus-dashboard-for-controllers)
3. Collected Controller-Handler Execution Frequency and Controller Execution Total metrics for 2.6.2 and 2.6.3 (before enabling legacy features)
  i. Note that for 2.6.3 (on k8s v1.21+) various v1 features are not enable-able by default and so some deferred controller-handlers are not present yet (logging, globaldns, etc).
  ii. Note that the overall number of controller-handlers is vastly reduced on 2.6.3. 234 controller-handlers on 2.6.2 vs 143 controller-handlers on 2.6.3
4. Enabled each legacy feature ([listed here](https://github.com/rancher/rancher/issues/35503#issuecomment-969069870)) one-by-one and monitored for relevant controller-handlers
  i. Note that some legacy features (monitoring, logging, global-dns) were enabled via the v3 API as they were not enable-able via the UI
5. Collected Controller-Handler Execution Frequency and Controller Execution Total metrics for 2.6.2 and 2.6.3 again (after all legacy features were enabled)
6. Verified that new controller-handler(s) for each legacy feature exist on 2.6.3. Verified that the relevant legacy feature controller-handlers were always available on 2.6.2

Notes:
- Tested on 2.6.2 and 2.6.3
- Tested an upgrade path from 2.6.2 -> 2.6.3-rc5
- Each time Controller metrics were collected they were exported to excel files for 2.6.2 and 2.6.3

Upgrade path validation summary:
1. Using the same 2.6.2 setup from above, helm upgrade rancher to 2.6.3-rc5
2. Wait for rancher pods to become active
3. Edit the previously-created Rancher ServiceMonitor ([created to enable controller metrics](https://github.com/rancher/rancher/issues/35503#issuecomment-969069870)) and update the "rancher-<rancher version here>" label selector to re-enable controller metrics gathering
4. Collected Controller-Handler Execution Frequency and Controller Execution Total metrics on 2.6.2 and verified that the controller-handlers for the previously enabled legacy features are still present
  i. The new "-deferred" controller-handlers should be present in addition to the legacy feature controllers that were already present
