### ISSUE TITLE
Frequent creation and deletion of node scenarios, memory leaks

### ISSUE THREAD

**Issue by watjt** [rancher/rancher#35500]
**Rancher Server Setup**
- Rancher version: v2.5.9
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: v1.16.13
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**Describe the bug**

Frequent creation and deletion of nodes can lead to memory leaks.
**To Reproduce**
 
Precondition: have a downstream cluster C1, and cluster C1 already exist other nodes (at least include one etcd and one control plane, cluster is healthy).
Step 1: add new node N1 to cluster C1, waiting for N1 status to Active
Step 2: delete N1, wait for deletion to complete
Repeat many times:  Step 1 -->Step 2
**Result**
Memory leak for rancher pod.
**Expected Result**

Avoid memory leaks in scenarios where nodes need to be created and deleted frequently.
**Screenshots**

![new_20211115103112](https://user-images.githubusercontent.com/38395110/141714140-71b51709-1003-41a9-a93f-7e3d1e9a77c4.jpg)
![20211115104007](https://user-images.githubusercontent.com/38395110/141714182-9730c83b-5db4-44be-a0d5-f0f3566c07a1.jpg)

**Additional context**

**Comment by watjt** [comment]
Can this problem be solved?

**Comment by JacieChao** [comment]
@watjt I can't reproduce by rancher/rancher:v2.5.11
You can try a newer version to see if it happened again.

**Comment by watjt** [comment]
I deployed rancher/rancher:v2.5.11 in my K8S, K8S build by RKE. Look at the dashboard, memory contuines to grow. 
![rancher_mem_v2 5 11](https://user-images.githubusercontent.com/38395110/148917945-f5fb0092-9fb0-4883-b82b-5f97b3b2fdf3.png)

This is my rancher information:
![rancher_ui_cluster](https://user-images.githubusercontent.com/38395110/148918067-798a05a1-d0b8-4508-9c62-5d3ac077019c.png)
![rancher_nodes](https://user-images.githubusercontent.com/38395110/148918099-6c72490b-f1e1-4713-8c9a-a6bf4940df14.png)

This is main logic script I tested:
`def stability_test_v2511(ui_addr):
    node_ip = "10.xxx.xxx.xxx"
    while True:
        try:
            st1 = RancherStabilityTest(ui_addr) # rancher server 
            cmd = Command(hostname=node_ip, username="root", password="123456", port=22)
        except Exception as exception:
            log.logger.error(f"{exception}")
            time.sleep(1800)
            continue

        else:
            while True:
                try:

                    st1.delete_node("c-65w7p:m-5ce9ad9c9aca")
                    time.sleep(300)

                    rmResult = cmd.exec_command("sudo docker rm -f `sudo docker ps -qa`")
                    log.logger.info(f"cleanup node: {node_ip} result: {rmResult}")
					
                    addResult = cmd.exec_command(
                        "sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:v2.5.11 --server https://rancher.my.org --token c4ghsktkl6g84nhlsfsvvcxtqg998kwd84686tmcqg7pp67xsnkbvf --ca-checksum db4a86f25af0cf66d64ef82f4dbb8155a4638f23e652e798fc52a4e083838607 --controlplane --worker"
					)	
                    log.logger.info(f"add node: {node_ip} result: {addResult}")
                    time.sleep(1500)

                except Exception as exception:
                    log.logger.error(f"exception: {exception}")
                    time.sleep(60)
                    break

            cmd.close()
            st1.close()`

**Comment by JacieChao** [comment]
I think it's related to the PR: https://github.com/rancher/lasso/pull/11
When the node adds to the cluster/removes from the cluster, rancher will restart user manager controller for the downstream cluster.

**Comment by watjt** [comment]
> I think it's related to the PR: [rancher/lasso#11](https://github.com/rancher/lasso/pull/11) When the node adds to the cluster/removes from the cluster, rancher will restart user manager controller for the downstream cluster.

That doesn't seem to be the problem, because have the same problem with the v2.3.3 test, v2.3.3 github.com/rancher/lasso package is not available.
