### ISSUE TITLE
[Backport] v2.5: Remove EKS deprecated k8s version 1.17

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#35515]
**Original Issue:**
https://github.com/rancher/rancher/issues/33825

**Comment by rmweir** [comment]
https://github.com/rancher/ui/commit/1660af868edd3a5f2c98b11f3722ca96d99696a6

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment

| Component               | Version / Type                                 |
| ----------------------- | ---------------------------------------------- |
| Rancher version         | v2.5.11                                        |
| User Interface          | v2.5.10                                        |
| Rancher cluster type    | Single Node Docker Install                     |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2        |
| Helm version            | v2.16.8-rancher1                               |
| Downstream cluster type | EKS                                            |
| Downstream K8s version  | 1.17                                           |
| Browser type            | Google Chrome                                  |
| Browser version         | Version 96.0.4664.45 (Official Build) (x86_64) |

## Reproduction steps

1. Starting from the cluster page click `Add Cluster`
2. Under `Create a new Kubernetes cluster` select `Amazon EKS`
3. Fill out the form
   1. Cluster Name: `eks-test-cluster-qa`
   2. Region: `us-east-2`
   3. Access Key: enter yours
   4. Secret Key: enter yours
   5. Click `Create` to create cloud credential
4. Under `Cluster Options` -> click `Kubernetes Version` and see the available options:
    - 1.20
    - 1.19
    - 1.18
    - 1.17
    - 1.16
    - 1.15

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.5-a267558471698ddf927688da9bf80724b8b7d95f-head |
| User Interface          | v2.5-dev                                           |
| Rancher cluster type    | Single Node Docker Install                         |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | EKS                                                |
| Downstream K8s version  | 1.20                                               |
| Browser type            | Google Chrome                                      |
| Browser version         | Version 96.0.4664.45 (Official Build) (x86_64)     |

## Validation steps

1. Starting from the cluster page click `Add Cluster`
2. Under `Create a new Kubernetes cluster` select `Amazon EKS`
3. Fill out the form
   1. Cluster Name: `eks-test-cluster-qa`
   2. Region: `us-east-2`
   3. Access Key: enter yours
   4. Secret Key: enter yours
   5. Click `Create` to create cloud credential
4. Under `Cluster Options` -> click `Kubernetes Version` and see the available options:
    - 1.20
    - 1.19
    - 1.18
5. Success! Only desired versions of k8s are available now
