### ISSUE TITLE
Update rancher/helm to support 1.22 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#35511]
Currently, we use rancher/helm in 2 ways: 
- In rancher/rancher dockerfile for v1 apps,  https://github.com/rancher/rancher/blob/release/v2.6/go.mod#L17 
- In rancher/shell for v2 apps, https://github.com/rancher/shell/blob/master/package/Dockerfile#L2 

https://github.com/rancher/rancher/issues/34054

**Comment by kinarashah** [comment]
https://github.com/rancher/helm/pull/33

**Comment by sowmyav27** [comment]
**Verified the following on 1.22.3-rancher 1-1 downstream clusters on 2.6.3-head and 2.6.3-rc4**
- v1 app deployment
- v2 app deployment
- v2 app upgrade
