### ISSUE TITLE
Non-Windows charts are listed on an RKE2 Windows cluster in Cluster tools and Apps & Marketplace

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#35527]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): helm  chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s v1.21.6+k3s1 
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version:  v1.21.6+rke2r1 
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom RKE2 

**Describe the bug**
Apps and Marketplace experience 

**To Reproduce**
Provision Rancher 2.6.2 and downstream RKE2 Windows cluster

**Result**

Non-Windows charts are listed in the Windows cluster under Cluster Tools and Apps & Marketplace

**Expected Result**

Only the supported Windows charts are listed under Cluster Tools and Apps & Marketplace (wins-upgrader, logging, monitoring)

**Screenshots**

![Cluster Tools - RKE2 Custom Windows Cluster in Rancher 2.6.2](https://user-images.githubusercontent.com/55704795/142032542-8de19022-90a5-48d5-b385-db32f5ef4abe.png)

Longhorn, Istio, Alerting Drivers, and OPA gatekeeper are not supported Windows charts but are now listed in an RKE2 Windows custom cluster when selecting `Cluster Tools`

![Apps & Marketplace - RKE2 Custom Windows Cluster in Rancher 2.6.2](https://user-images.githubusercontent.com/55704795/142033656-96daacbe-3a9b-4ef7-abfc-46fc0e50730c.png)

Longhorn, Istio, Alerting Drivers, External IP Webhook, sriov (experimental), OPA gatekeeper, vsphere CSI, and vsphere CPI are not supported Windows charts but are now listed in an RKE2 Windows custom cluster when selecting `Apps & Marketplace`

Related to: rancher/rancher#36446

**Comment by rosskirkpat** [comment]
Information regarding what charts are supported and listed on an RKE1 Windows cluster:

https://github.com/rancher/windows/issues/92#issuecomment-962165040

**Comment by sirredbeard** [comment]
Superseded by #36401
