### ISSUE TITLE
[Monitoring v2] Update the Prometheus default memory limit to 3000Mi

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#35529]
**Setup**
- Rancher version: 2.6.0
- Browser type & version: Chrome

**Describe the bug**

Currently, the default memory limit for Prometheus in monitoring v2 is `1500Mi`, which is too low for the Prometheus pod to run in the long term.  We need to change it to `3000Mi` 
 
<img width="1646" alt="Screen Shot 2021-09-27 at 11 34 51 AM" src="https://user-images.githubusercontent.com/6218999/134966440-bcf07268-868b-4597-92c4-69d2196d8242.png">

Related issue: https://github.com/rancher/rancher/issues/34850

**Comment by gaktive** [comment]
@jiaqiluo can you update the chart with this?

**Comment by jiaqiluo** [comment]
Can be tested in the rancher-monitoring  `100.1.0+up19.0.3`
---
### Root cause
In the chart, Prometheus default memory limit to 1500Mi

### What was fixed, or what changes have occurred
change the default to 3000Mi

### Areas or cases that should be tested
When installing the monitoring chart, the value in the UI should be 3000Mi 

### What areas could experience regressions?
n/a

### Are the repro steps accurate/minimal?
n/a

**Comment by Auston-Ivison-Suse** [comment]
**Rancher Setup For Reproduction**
- Rancher Version: v2.6.2
**Reproduction Steps**
1. Go to local cluster from cluster explorer
2. Go to apps & marketplace --> Monitoring
3. Press install then proceed to "Prometheus" in the left menu.
4. Witness the memory limit is lower than the needed. (2500Mi)

Screenshot of  wrong memory limit:
![MemoryLimit.png](https://zube.io/files/rancher/c066047aa33d1c6fbdd4d7dbf7b56e0f-memorylimit.png)

**Rancher Setup For Validation**
- Rancher Version: v2.6-head
1. Go to local cluster from cluster explorer
2. Go to apps & marketplace --> Monitoring
3. Press install then proceed to "Prometheus" in the left menu.
4. Witness the memory limit is properly set to 3000Mi

![MemoryLimit.png](https://zube.io/files/rancher/e5a476c5537a314ce947033b9f85968e-memorylimit.png)

**Sanity Testing**

I tested this from the "install monitoring" on the cluster dashboard and got the same results.
