### ISSUE TITLE
Menu should stay right justified even if action button is removed

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3552]
Version: Master 2/4

Steps:
1.  On the host page, click on Deactivate then Delete for a host

Results:  The three dot menu moves to left because the action button is gone.
![image](https://cloud.githubusercontent.com/assets/11514927/12862989/c8197996-cc2d-11e5-9e66-e6dcf3984ce6.png)

Expected:  The menu icon/button should stay in same place.

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/470

**Comment by tfiduccia** [comment]
Version - 2/17
Verified fixed
