### ISSUE TITLE
Run Conformance Testing for k8s 1.22

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35531]
k8s 1.22 is avaiable starting at rancher 2.6.3. We need to run Conformance Testing for Rancher

**Comment by vivek-infracloud** [comment]
**Rancher Server Setup**

- Rancher version:v2.6.3-rc4
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details:Selfsigned

**Information about the Cluster**

- Kubernetes version:v1.22.4
- Cluster Type (Local/Downstream): 
  - Downstream 1 Node with CP, ETCD and Worker, 2 Worker nodes.

**To Reproduce**
- Create downstream cluster on Rancher v2.6.3-rc4.
- Once the cluster is up and active, update the kube_api with following extra argument.
 ```
   extra_args:
        service-account-issuer: https://<cp_ip>:6443
```
(<cp_ip> is Public/External IP of Control Plane)
- Run conformance test

**Results**
```
Ran 346 of 6433 Specs in 5277.484 seconds
SUCCESS! -- 346 Passed | 0 Failed | 0 Pending | 6087 Skipped
PASS

Ginkgo ran 1 suite in 1h27m59.495464593s
Test Suite Passed
```

**Comment by rayandas** [comment]
Rancher conformance test results PR on cncf: https://github.com/cncf/k8s-conformance/pull/1726
