### ISSUE TITLE
Make key a writable field in the API certificate resource

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#3553]
When updating a certificate in the API it should be possible to update the private key as well, since it is common practice to generate a new private key when requesting a certificate re-issue at the CA.

Currently the Let's Encrypt service - see https://github.com/rancher/rancher/issues/2734#issuecomment-177763643 - needs to keep state on the private key for renewals because the API does neither expose nor allow to update the certificate key. This isn't a problem per se. But if the certificate service container that created cert X is destroyed, the resource for that certificate will become stale: Even though you can update the resource with a renewed certificate by deploying another certificate service container, the private key will not match the new certificate.

**Comment by blaggacao** [comment]
:+1: 
@vincent99 The missing piece for Let's Encrypt support?

**Comment by janeczku** [comment]
There is also this blocking issue: https://github.com/rancher/rancher/issues/3556
And as discussed in the other thread, an API agent role with permissions for certificate and load balancer schemes is also high on the list. @alena1108 

```YAML
  labels:
    io.rancher.container.create_agent: "true"
    io.rancher.container.agent.role: "certificate-service"
```

**Comment by alena1108** [comment]
@janeczku that should be relatively easy fix. We'll just have to fix the permissions at this line:

https://github.com/rancher/cattle/blob/6454299777e425a3ed764836a489e30f12a2bd6b/resources/content/schema/user/user-auth.json#L338
c - create
d - delete
"ro" - read only. I still think we shouldn't expose the private key in the API, but not sure if ro can co-exists ti the upgrade, need to try that.

I might not get time to get to work on it, till next week though, so if you are willing to put it in this fix (with some basic test for Update operation), it would be much appreciated.

**Comment by vincent99** [comment]
`ro` means "read only on create".. it's meant for API key generation, you get the secret value back in the `POST` response but can't ever get it back again.  In this case the create is providing the secret value so there's not really any reason to send it back in the create response.

I would think you just want `cu`, but not sure if that's a supported combination.

**Comment by deniseschannon** [comment]
@janeczku With v0.63.0, could you please test and let me know if it works as expected?

**Comment by janeczku** [comment]
1. Added new certificate resource
2. Updated certificate resource with a renewed certificate **and new private key** using API web interface
3. Checked that operation succeeded

Works as expected @deniseschannon
