### ISSUE TITLE
Gracefully handle disconnected clusters

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rancher#35546]
If a cluster disconnects (meaning the cluster agent is no longer connected) we should not show any error but a message that it is disconnected.  Also on the Rancher server additional CPU cycles should be be consumed by user controllers that can not work.  What we should see is that upon disconnect we will see disconnect errors, but the after that no additional errors should be shown while the cluster remains in a disconnected state.

**Comment by deniseschannon** [comment]
As part of validation for this, we should try and power down the node that has the cluster agent and then bring it back up to see if the cluster is re-recognized and rejoins Rancher.

**Comment by git-ival** [comment]
#### Validation Process:
1. Created an HA setup on Rancher 2.6.3-rc4 with rke
2. Created a downstream rke cluster
3. Using the downstream kube-config: restarted and/or scaled down the cattle-cluster-agent
4. Observed the expected "Cluster agent is not connected" message on the downstream cluster
   i. Cluster was in an "Unavailable state
5. Once the cattle-cluster-agent has shown the expected message for a short while no additional error messages are observed
6. When the cattle-cluster-agent becomes active again the UI is updated and the downstream becomes Active again

#### Notes:
Stopping the node that the cattle-cluster-agent is running on produces the expected message in the UI and marks the downstream as Unavailable. Restarting the node re-activates the cattle-cluster-agent and marks the downstream as Active again.

Video Artifacts attached below.

https://user-images.githubusercontent.com/85186645/146269185-03b9f99d-9db1-41bb-9512-2d1a5dbc8f8f.mov


https://user-images.githubusercontent.com/85186645/146269197-5484a666-22f8-4b8e-a347-72bc51e6f830.mov
