### ISSUE TITLE
Minimize writes to the kontainer-engine v1 state secret

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rancher#35547]
The state secret is quite large and we would like to avoid updating it when it's not needed.  There are several times that we move the state to Updating and then back to Running and nothing else changes.

**Comment by git-ival** [comment]
Need additional metrics to be exposed in order to properly verify this issue. I believe @rmweir is targetted to expose more metrics after the 2.6.3 release.

**Comment by git-ival** [comment]
Closing with the following:
Able to provision EKS clusters as expected without issue. Additionally, this change has been in-place throughout multiple versions' worth of scale and regression testing without negatively effecting their results.
