### ISSUE TITLE
[rke2] kube-api `additional args` breaks kube api server, cluster is unable to come to active. However, same var on rke1 works as expected 

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35550]
**Rancher Server Setup**
- Rancher version: 2.6-head (78b25c3)
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:1.21.6+rke2r1
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

When using the UI to add new kube-api or kube-controller args, the cluster is unable to come to an active state. 

**To Reproduce**
 
* deploy an rke2 downstream cluster
  * when deploying the cluster, go to `advanced` section and enter a variable for both kube-api and kube-controller. we used `feature-gates: BoundServiceAccountTokenVolume=false`

<img width="848" alt="Screen Shot 2021-11-16 at 3 11 09 PM" src="https://user-images.githubusercontent.com/16691014/142089676-c445ceea-deb0-46b2-acff-7c837014057c.png">

**Result**
cluster fails to provision.  Looking at the kubelet logs, the kube-api server is down 
```
Unable to register node with API server" err="Post \"https://127.0.0.1:6443/api/v1/nodes\": dial tcp 127.0.0.1:6443: connect: connection refused" node="<your_node_name>
```

**Expected Result**

the cluster should be able to come to an active state when adding extra argument variables to kube-*

**Screenshots**

**Additional context**

* the same vars are working as expected on an rke1 setup
* I'm putting this in rancher repo first, as I've spoken with an rke2 team member and it seems that this is expected to work, so I'd like some investigation from rancher first to make sure that the format/syntax of the yaml are correct before passing it to their team. 
* this ticket was found while testing [this ticket](https://github.com/rancher/rancher/issues/33465)

**Comment by brandond** [comment]
Extra args should be in the format `feature-gates=BoundServiceAccountTokenVolume=false` - can you confirm the format that you're using?

**Comment by Auston-Ivison-Suse** [comment]
@brandond Thank you Brad, looks like this is a non issue!

**Comment by slickwarren** [comment]
can confirm - [this format](https://github.com/rancher/rancher/issues/35550#issuecomment-971067588) works for rke2.
