### ISSUE TITLE
RKE1 v1.22 errors for metrics.k8s.io/v1beta1

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#35559]
Create Rancher local cluster 1.22 and Provision a RKE1 Downstream cluster (any provider). 

Check cattle-cluster-agent logs in cattle-system namespace: 
```
E1117 05:51:59.756072 53 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1117 05:51:59.763116 53 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

rancher/rancher#34054

**Comment by slickwarren** [comment]
This seems to be related/causing an issue for monitoring v1 on 2.6-head (de55fe0).  I see this error in both /g and iframe windows once 0.3.1 is installed. The gears for monitoring do not show metrics. 
Local cluster is 1.22.3+k3s1, downstream (where monitoring is installed) is 1.20.12
```
Failed to obtain metrics. The metrics service may not be available.
undefined
```
<img width="1508" alt="Screen Shot 2021-11-19 at 12 39 42 PM" src="https://user-images.githubusercontent.com/16691014/142688872-f13d7f5a-a653-465f-bf6b-bf6977d3b46e.png">

found while testing https://github.com/rancher/dashboard/issues/4573

**Comment by ryansann** [comment]
Steps I used to for testing:
1. Install Rancher `v2.6-head` image (`46eb9d41`), local cluster k8s version `v1.22.3+k3s1`
2. Provision downstream DO HA Cluster, k8s version `v1.21.6`
3. Install metrics v1 via Cluster Tools in newly provisioned cluster 
4. Check cluster agent logs in provisioned cluster
5. Check metrics view from ember

I'm still seeing the problem logs from the cluster-agent:
```
> kubectl logs cattle-cluster-agent-5fbdc5f88c-dgr7c -n cattle-system | grep metrics 
E1202 21:06:46.844262      57 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:46.857018      57 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:56.839446      57 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:56.894999      57 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:56.905675      57 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:56.948662      57 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:57.724979      57 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:57.729407      57 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
> kubectl logs cattle-cluster-agent-5fbdc5f88c-ltglg -n cattle-system | grep metrics
E1202 21:06:47.257455      58 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:47.261093      58 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:55.456629      58 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:55.477931      58 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:55.485630      58 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:55.513785      58 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:56.855869      58 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:56.878890      58 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E1202 21:06:57.573064      58 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

Additionally, I'm not seeing any metrics in the ember cluster view

I'm going to try this again to make sure I didn't do anything wrong

**Comment by sowmyav27** [comment]
**On 2.6.3-rc4**

See these errors
```
E1206 22:38:02.878609 32 memcache.go:196] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
Mon, Dec 6 2021 2:38:03 pm | E1206 22:38:03.074464 32 memcache.go:101] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```
Downstream clusters have - Longhorn v1/v2, monitoring v2, CIS v1/v2 enabled on different clusters

**Comment by slickwarren** [comment]
I'm seeing issues after an upgrade from 2.6.2 -> 2.6.3-rc4 (local cluster 1.21.6, downstream 1.20.12) mirroring this comment's errors: https://github.com/rancher/rancher/issues/35559#issuecomment-974448232

**Comment by deniseschannon** [comment]
What happens now that we can' tlist? What is actually broken?

**Comment by kinarashah** [comment]
The actual issue isn't the list errors in cluster agent, but what @slickwarren mentioned, old queries fail with the same error: 
https://github.com/rancher/rancher/issues/35559#issuecomment-974448232 

Local 1.22, downstream any supported version.

**Comment by cbron** [comment]
Not moving yet, as this has been identified by @slickwarren as at least partially reproducible in 1.21.

**Comment by jiaqiluo** [comment]
the bug is reproduced on the downstream cluster running v1.20.13  and the local cluster runs v1.21.7

**Comment by cbron** [comment]
This is a regression not seen in <2.6.2, monitoring v1 is broken at any level in the Rancher UI. Grafana can be used as a workaround.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `39cecf0`**

- Local cluster on 1.20 and downstream on 1.20 (monitoring v1 enabled on both)
- Rancher logs or cluster agent logs do not show the errors.
