### ISSUE TITLE
Updating a certificate results in invalid resource data 

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#3556]
**Steps to reproduce**

1. Create a certificate in the UI
2. Open in the API
3. Note the resource fields (CN, expiresAt, serialNumber, etc.)
3. Click` Edit` and paste a new certificate (real life: renewed certificate) in the cert field
4. Send the request and reload the page

Note that only the `cert` field reflects the updated certificate. All other resource fields contain stale data of the previous certificate.

**Comment by alena1108** [comment]
@janeczku should be an easy fix as well. Just have to add "update" method to https://github.com/rancher/cattle/blob/0c4066f9fd2652f99d29989c2a29065f0378c20e/code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/ssl/CertificateCreateValidationFilter.java#L31

and follow the same logic of updating the fields read from certificate, there.

**Comment by janeczku** [comment]
@alena1108 Yes, that looks easy! :yum:

**Comment by janeczku** [comment]
@alena1108 Do you think that you gonna find time this week to land the fix for this? It's *the* missing link for the Rancher Let's Encrypt service... Thanks! :smile:

**Comment by rvion** [comment]
+1

**Comment by robeastham** [comment]
+1

**Comment by alena1108** [comment]
@janeczku sorry, got swamped by back to back projects, assigning this ticket to myself and going to look at it asap.

**Comment by janeczku** [comment]
@alena1108 :joy: Thank you!  I will let you know if anything else comes up.

**Comment by deniseschannon** [comment]
@janeczku With v0.63.0, could you please test and let me know if it works?

**Comment by janeczku** [comment]
1. Added new certificate resource
2. Updated certificate resource with a renewed certificate using API web interface
3. Checked that the certificate property fields of the resource were updated

Works as expected @deniseschannon

**Comment by deniseschannon** [comment]
Thanks for testing @janeczku
