### ISSUE TITLE
Minimize caches ran on followers

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rancher#35565]
One rancher pod is dedicated to managing user controllers for a downstream cluster.  All other Rancher pods will be designated a follower for that downstream cluster.  Every follower starts a set of caches.  Today that includes things like Pods which causes a good deal of memory usage and traffic to the Rancher server.  We wish to minimize the caches created to only RBAC related.  Eventually we can get this to zero, but for now we really only need to cache information about RBAC (used by norman API and impersonation logic in the proxy).

**Comment by git-ival** [comment]
Unable to directly verify individual caches.

Ran a Small scale test, results logged here: https://confluence.suse.com/display/EN/Small+Scale+Testing+Results 

Was able to hit the documented supported # of downstreams, but overall resource usage was noticeably higher than the previous 2.6.1 results.

**Comment by git-ival** [comment]
Unable to directly verify individual caches.

Ran a Small scale test as a general regression test. Was able to hit the documented supported # of downstreams, but overall resource usage was noticeably higher than the previous 2.6.1 results.

**Comment by git-ival** [comment]
Closing with the following:
After this change and other related controllers changes a decrease in memory usage is noticeable. Additionally, this change has been in-place for multiple versions' worth of regression and scale-testing efforts without negatively impacting results.
