### ISSUE TITLE
Route53 fails to create FQDN if the Rancher environment name contains spaces

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#3557]
The Route53 DNS service is working well for me, unless the Rancher environment has a space in the name. 

I suppose my preference would be to have the route53 service just normalize the environment name automatically, by replacing invalid characters with a dash or underscore.

**Comment by DanielDent** [comment]
The Cloudflare DNS service has the same problem. There may be something to be said for only allowing DNS label friendly environment names.

**Comment by alena1108** [comment]
@DanielDent putting a restriction on environment.name to be a valid DNS name is reasonable. 
For existing entries that don't follow the format, we will either use the approach proposed by @eebjr  - put a delimiter - or simply document that users might fix the environment name in order for it to work with external DNS programming.

**Comment by sshipway** [comment]
Maybe map all non-DNS-compaitible characters in Environment/Stack/Container name to underscores in the DNS service container before creating the DNS entry?  Although this risks many->one mapping it is unlikely to happen in reality

**Comment by alena1108** [comment]
Duplicating to https://github.com/rancher/rancher/issues/3972
