### ISSUE TITLE
CSI chart 2.1.1 on k8s version 1.17 fails

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35572]
**Rancher Server Setup**
- Rancher version: `v2.5.11`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.21.3+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 3 worker, 1 etcd, 1 cp vsphere` 

**Describe the bug**
Installing CSI chart on the k8s version 1.17 fails with an error

**To Reproduce**
1. Create a node driver vsphere cluster with 3 worker, 1 etcd, 1 cp and k8s `v1.17.17-rancher2-3`
2. Install CPI chart `1.0.1` on the downstream cluster
3. Install CSI chart `2.1.1` 

**Result**
Installation fails with the error 
```
/home/shell/helm/rancher-vsphere-csi-2.1.1.tgz
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"
```

**Expected Result**
Expected the installation to go through without any error.

Related: https://github.com/rancher/rancher/issues/35476

**Comment by rishabhmsra** [comment]
**Validated on Rancher v2.5.11 with feature charts pointing to dev-v2.5-vsphere-release branch**

**Result:**
CSI chart `2.1.1` installed successfully on a k8s 1.17 downstream cluster with `kubeVersion: <= 1.19`.
