### ISSUE TITLE
[monitoring v1] Install fails on k8s 1.22 with message `Failed to install app cluster-monitoring. Error: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35574]
**Rancher Server Setup**
- Rancher version: (96e2438)
- Installation option (Docker install/Helm Chart): Helm
- If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1
- Proxy/Cert Details:self signed

**Information about the Cluster**
- Kubernetes version:  1.22.3
- Cluster Type (Local/Downstream): downstream
- If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): provider: aws

**Describe the bug**

 monitoring v0.3.1 Install fails on k8s 1.22 with message `Failed to install app cluster-monitoring. Error: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"`

**To Reproduce**
 
* deploy downstream 1.22 cluster 
* enable legacy flag
* install monitoring v1 (0.3.1, latest version)

**Result**
* install never finished. checking the `lecacy` -> `apps` page and looking at the errors for each monitoring related resource shows the following errors:
* for `cluster-monitoring`, `monitoring-operator` and `cluster-alerting`: `Failed to install app cluster-monitoring. Error: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"`

**Expected Result**

monitoring should be able to install, but grafana will not have any data due to [feature-gates flag](https://github.com/rancher/rancher/issues/33465) no longer supported on 1.22

**Additional context**

* 1.21 installs are working fine with and without the flag mentioned in `expected results`, so this seems specific to 1.22

**Comment by jiaqiluo** [comment]
We will mark this as a known issue that monitoring v1 does not support k8s 1.22

**Comment by kinarashah** [comment]
Thanks @jiaqiluo! I have added the reason and release-note on the main issue tracking legacy feature too.

**Comment by slickwarren** [comment]
closing, as monitoring v1 will not be supported on 1.22
