### ISSUE TITLE
Errors  `failed to parse constraint for kubeversion <1.21: Could not parse Range "<1.21"` are seen in the docker logs when downstream clusters are created on k8s 1.22

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35573]
**Rancher Server Setup**
- Rancher version: `v2.6-head 96e2438`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.22.3+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.22.3-rancher1-1
- Cluster Type (Local/Downstream): `Downstream custom 2 worker, 1 etcd, 1 cp`

**Describe the bug**
While creating a downstream cluster on the k8s 1.22.3-rancher1-1, see continuous error logs `failed to parse constraint for kubeversion <1.21: Could not parse Range "<1.21"` 

**To Reproduce**
1. Create a downstream rke1 custom cluster
2. Verify the docker logs

**Result**
Following logs flow through continuously 
```
2021/11/17 19:15:21 [ERROR] failed to parse constraint for kubeversion <1.21: Could not parse Range "<1.21": Could not parse version "1.21" in "<1.21": No Major.Minor.Patch elements found
2021/11/17 19:15:21 [ERROR] failed to parse constraint for kubeversion <1.21: Could not parse Range "<1.21": Could not parse version "1.21" in "<1.21": No Major.Minor.Patch elements found
2021/11/17 19:15:21 [ERROR] failed to parse constraint for kubeversion <1.21: Could not parse Range "<1.21": Could not parse version "1.21" in "<1.21": No Major.Minor.Patch elements found
2021/11/17 19:15:21 [ERROR] failed to parse constraint for kubeversion <1.21: Could not parse Range "<1.21": Could not parse version "1.21" in "<1.21": No Major.Minor.Patch elements found
2021/11/17 19:15:21 [ERROR] failed to parse constraint for kubeversion <1.21: Could not parse Range "<1.21": Could not parse version "1.21" in "<1.21": No Major.Minor.Patch elements found
2021/11/17 19:15:21 [ERROR] failed to parse constraint for kubeversion <1.21: Could not parse Range "<1.21": Could not parse version "1.21" in "<1.21": No Major.Minor.Patch elements found
```
**Expected Result**
Expected the above logs to be not present.

**Additional context**
Downstream cluster comes up fine without any issue and all the workloads are active except for the error logs as mentioned above.

**Comment by ryansann** [comment]
I see this repro after running a `v2.6-head` image. Exec'ing into the rancher container via: `docker exec -it <container-id> /bin/sh` and running `grep -r "<1\.21$" .` shows:
```
./management-state/catalog-cache/d9304a116b86a0f4bae67d3c850ee7ff2e61072d1dcfe48fc76c7f6373041b60/charts/rancher-logging/0.2.2/Chart.yaml:13:kubeVersion: <1.21
./management-state/catalog-cache/d9304a116b86a0f4bae67d3c850ee7ff2e61072d1dcfe48fc76c7f6373041b60/charts/rancher-logging/0.1.3/Chart.yaml:13:kubeVersion: <1.21
./management-state/catalog-cache/d9304a116b86a0f4bae67d3c850ee7ff2e61072d1dcfe48fc76c7f6373041b60/charts/rancher-logging/0.2.4/Chart.yaml:13:kubeVersion: <1.21
./management-state/catalog-cache/d9304a116b86a0f4bae67d3c850ee7ff2e61072d1dcfe48fc76c7f6373041b60/charts/rancher-logging/0.2.5/Chart.yaml:13:kubeVersion: <1.21
./management-state/catalog-cache/d9304a116b86a0f4bae67d3c850ee7ff2e61072d1dcfe48fc76c7f6373041b60/charts/rancher-logging/0.1.1/Chart.yaml:13:kubeVersion: <1.21
./management-state/catalog-cache/d9304a116b86a0f4bae67d3c850ee7ff2e61072d1dcfe48fc76c7f6373041b60/charts/rancher-logging/0.2.3/Chart.yaml:13:kubeVersion: <1.21
./management-state/catalog-cache/d9304a116b86a0f4bae67d3c850ee7ff2e61072d1dcfe48fc76c7f6373041b60/charts/rancher-logging/0.0.1/Chart.yaml:13:kubeVersion: <1.21
./management-state/catalog-cache/d9304a116b86a0f4bae67d3c850ee7ff2e61072d1dcfe48fc76c7f6373041b60/charts/rancher-logging/0.1.2/Chart.yaml:13:kubeVersion: <1.21
./management-state/catalog-cache/d9304a116b86a0f4bae67d3c850ee7ff2e61072d1dcfe48fc76c7f6373041b60/charts/rancher-logging/0.2.0/Chart.yaml:13:kubeVersion: <1.21
./management-state/catalog-cache/d9304a116b86a0f4bae67d3c850ee7ff2e61072d1dcfe48fc76c7f6373041b60/charts/rancher-logging/0.3.0/Chart.yaml:13:kubeVersion: <1.21
./management-state/catalog-cache/d9304a116b86a0f4bae67d3c850ee7ff2e61072d1dcfe48fc76c7f6373041b60/charts/rancher-logging/0.2.1/Chart.yaml:13:kubeVersion: <1.21
./management-state/catalog-cache/d9304a116b86a0f4bae67d3c850ee7ff2e61072d1dcfe48fc76c7f6373041b60/charts/rancher-logging/0.1.4/Chart.yaml:13:kubeVersion: <1.21
```
It looks like `rancher-logging` in `system-charts` could be the culprit here as it's the only chart in the catalog-cache that specifies this kubeVersion

**Comment by ryansann** [comment]
Did some more validation here and this looks to be coming from `pkg/catalog/manager/manager.go:222` which implies v1 catalogs. Performing a `kubectl get catalogtemplateversion -A -o yaml | grep -A 3 -B 3 "<1\.21$"` we can see that only the `rancher-logging` chart has these versions.

Further more, we are using [this ParseRange method](https://github.com/blang/semver/blob/master/range.go#L112) in catalog v1 stuff. This method clearly documents examples of valid ranges for parsing, of which `<1.21` is not. I'll open a PR to get these versions changed so we can fix this error.

Another note, this doesn't actually have anything to do with provisioning a downstream. So for validation, that part can be skipped

**Comment by anupama2501** [comment]
Verified on v2.6-head 4375161 docker install

- Created an rke1 node driver cluster on k8s v1.22.3-rancher1-1
- Verified the error logs are not seen anymore in the docker logs

.
