### ISSUE TITLE
Monitoring v1 Grafana will not be able to scrape from prometheus in k8s 1.22+

### ISSUE THREAD

**Issue by Auston-Ivison-Suse** [rancher/rancher#35576]
**Rancher Server Setup**
- Rancher version: v2.6-head (78b25c3)
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): K3s k8s version: v1.21.3+k3s1
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version: 1.22
- Cluster Type (Local/Downstream): Both

**Describe the bug**
We were able to find a workaround for this in k8s version 1.21 as mention in this [issue.](https://github.com/rancher/rancher/issues/33465)
As of k8s version 1.22+ we will run into an issue where the feature gate `BoundServiceAccountTokenVolume` will be no longer have a the ability to be disabled as mentioned [here](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#:~:text=A%20ConfigMap%20containing,arg%20in%201.22)).

**To Reproduce**
N/A

**Result**

**Expected Result**

**Screenshots**

**Additional context**
https://github.com/rancher/rancher/issues/33465

**Comment by cbron** [comment]
Monitoring V1 is not supported on 1.21+
