### ISSUE TITLE
Upgrade stopped services?

### ISSUE THREAD

**Issue by ronag** [rancher/rancher#3558]
I have a broken configuration that I want to change. And I DO NOT want to run the service again.

But I cannot perform an upgrade through the ui without first running the service...

**Comment by deniseschannon** [comment]
What version are you running? We added the ability to upgrade `inactive` services a couple of releases ago? I definitely see the option in the UI in my v0.58.0-rc2 set up. ;)

**Comment by deniseschannon** [comment]
@ronag Please re-open if you don't see the option as I mentioned and what version you are running, it's now available in later releases.
