### ISSUE TITLE
Service rancher-webhook not found after fresh install

### ISSUE THREAD

**Issue by King-Chau** [rancher/rancher#35585]
**Rancher Server Setup**
- Rancher version: v2.6.0
- Installation option (Docker install/Helm Chart): Docker install 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.16.3
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
reinstall rancher, got this: Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "rancher.cattle.io": Post https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s: service "rancher-webhook" not found
https://forums.rancher.com/t/service-rancher-webhook-not-found-after-fresh-install/20521

**To Reproduce**
reinstall rancher

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by moogoos** [comment]
Bump. Same issue for me

**Comment by vtrenton** [comment]
Hello,
The version of Rancher you have is not supported with Kubernetes 1.16 - see the support Matrix here: 
https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-0/

Please upgrade the version of Kubernetes you are using. Then check to see if the rancher-webhook pod is running in the cattle-system namespace.

**Comment by everping** [comment]
I got the same issue and don't know what to do next

```shell
> kubectl apply -f https://rancher.domain/v3/import/xxxxxxxxxxxxxxxxxxxxxxxxxxx.yaml

clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver unchanged
clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master unchanged
namespace/cattle-system unchanged
serviceaccount/cattle unchanged
clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged
clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged
deployment.apps/cattle-cluster-agent unchanged
service/cattle-cluster-agent unchanged
Error from server (InternalError): error when creating "https://rancher.domain/v3/import/xxxxxxxxxxxxxxxxxxxxxxxxxxx.yaml": Internal error occurred: failed calling webhook "rancher.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s": service "rancher-webhook" not found
```

**Rancher version:** 2.6.2 (2.6.0 also)
**K8S version:** 1.20.2
