### ISSUE TITLE
Changing vSphere Machine Pool Disk/CPU/RAM does not update the VM

### ISSUE THREAD

**Issue by braunsonm** [rancher/rancher#35592]
**Rancher Server Setup**
- Rancher version: v2.6.2
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm Chart on RKE2

**Information about the Cluster**
- Kubernetes version: v1.21.5

**Describe the bug**
You cannot update the CPU/Memory/Disk size of the vSphere VMs after they are created. Adjusting this in the UI should reprovision the VMs and roll the update out

**To Reproduce**
1. Create a RKE2 vSphere cluster
2. Change the CPU or RAM or Disk size of the pool after provisioning
3. Notice nothing happens after saving

**Expected Result**
The VMs should gracefully drain and roll out with the new machine configuration

**Comment by junkiebev** [comment]
You aren't updating the VMs though, you are updating _the template_. That's how it works with every provider, not just vSphere.

**Comment by braunsonm** [comment]
It's inconsistent. Because editing the templates clone from VM does roll the update to all nodes.

Is there was way then to cause Rancher to roll this update out to all nodes so they get up to date with the template? Or is the solution to make new node pools and destroy ones each time? (This is not friendly to terraform deployments) @junkiebev

**Comment by braunsonm** [comment]
Remains an issue

**Comment by junkiebev** [comment]
I'd probably alter this to a RFE which would grant the ability to "reconcile" VMs which were deployed using a version of the template which had since been modified. The hair in the soup is that the in-tree vSphere cloud provider doesn't do a great job at protecting storage when VMs are murdered - if Rancher tells vSphere to delete a VM, it _can possibly_ delete not only the VM, but any PVs attached to the VM when the delete command is issued.

**Comment by braunsonm** [comment]
I'd be fine with an RFE for that functionality.

The second point you make is unrelated and would happen even during regular updates to the underlying VM template or scale up and down operations. (I also use RKE2 which is the out of tree provider so I haven't witnessed that first hand)

**Comment by braunsonm** [comment]
Bump

**Comment by braunsonm** [comment]
Bump

**Comment by braunsonm** [comment]
Bump

**Comment by braunsonm** [comment]
Bump

**Comment by braunsonm** [comment]
Bump

**Comment by braunsonm** [comment]
Bump

**Comment by braunsonm** [comment]
Bump
