### ISSUE TITLE
Unable to setup Azure AD login

### ISSUE THREAD

**Issue by WolfspiritM** [rancher/rancher#35599]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.6+rke2r1
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

**To Reproduce**
 
Trying to setup Azure AD login isn't working for me.
I'm following this docs: https://rancher.com/docs/rancher/v2.6/en/admin-settings/authentication/azure-ad/

**Result**
There is no way to assign the "Azure Active Directory Graph" permission to the app as that API seems to be deprecated.

**Expected Result**
The API used is not deprecated and selectable via the "API permissions" dialog in the azure portal.

**Screenshots**

![image](https://user-images.githubusercontent.com/5904171/142592136-9fb7805c-2a22-4a18-b560-e61ca749f5aa.png)

**Additional context**

**Comment by WolfspiritM** [comment]
This is still a problem... There is no way to set up azure AD login with rancher at the moment

**Comment by sphr2k** [comment]
@WolfspiritM You can still assign create AAD Graph permissions using the `az` CLI:
```bash
export AppId=<Application ID>
export ApiId=00000002-0000-0000-c000-000000000000         # Azure AD Graph API
export PermissionId=5778995a-e1bf-45b8-affa-663a9f3f4d04  # Directory.Read.All
 
az ad app permission add --id $AppId --api $ApiId --api-permissions $PermissionId=Role
az ad app permission grant --id $AppId --api  $ApiId
```

List of permission GUIDs: https://github.com/Azure/azure-powershell/issues/16067#issue-1023553283

**Comment by sunib** [comment]
I created the following ps1 in which I looked up all the required permissions that are required in the [docs](https://rancher.com/docs/rancher/v2.6/en/admin-settings/authentication/azure-ad/#3-set-required-permissions-for-rancher)

```
param (
    [String] $appId,
    [String] $apiId = "00000002-0000-0000-c000-000000000000"
)

Function Set-Permission {
    param (
        [string] $permissionId
    )
    Write-Host("Setting permission $permissionId");
    Write-Host("add");
    az ad app permission add --id $appId --api $apiId --api-permissions "$permissionId=Role"
    Write-Host("grant");
    az ad app permission grant --id $appId --api $apiId
}

$requiredPermissionIds = @('a42657d6-7f20-40e3-b6f0-cee03008a62a','5778995a-e1bf-45b8-affa-663a9f3f4d04','6234d376-f627-4f0f-90e0-dff25c5211a3','c582532d-9d9e-43bd-a97c-2667a28ce295','cba73afc-7f69-4d86-8450-4978e04ecd1a','311a71cc-e848-46a1-bdf8-97ff7156d8e6')
foreach ($id in $requiredPermissionIds) {
    Set-Permission($id)
}
```

All grant actions fail, however:
```
Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://graph.windows.net/{my-tenant-id}/oauth2PermissionGrants?api-version=1.6
```

Has anyone a clue?

Would be very nice to know if there is some planning on switching to the new API's, since this API is apperently going to be depricated very soon (june 2022)
