### ISSUE TITLE
Stopping a failed upgrade

### ISSUE THREAD

**Issue by withinboredom** [rancher/rancher#3559]
If an upgrade of a service has a failing container, cancelling the upgrade never completes and there's no way to stop it. In my case, the failing container is some kind of cryptic 500 error...

**Comment by alena1108** [comment]
@withinboredom could you provide the cattle log for the failure around the time you saw 500 error?

**Comment by withinboredom** [comment]
I had to blow away the entire rancher instance to get back to a sane state :(

**Comment by alena1108** [comment]
@withinboredom ah :( if it happens again, could you update the bug?

**Comment by alena1108** [comment]
Please reopen once it happens again + logs are available.
