### ISSUE TITLE
Failed to update Clusters

### ISSUE THREAD

**Issue by dcardellino** [rancher/rancher#35601]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: LE

**Information about the Cluster**
- Kubernetes version: 1.21.4
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vSphere

**Describe the bug**

Suddenly cannot update/manage clusters created with rancher because i receive the following message on dashboard:

` Secrets "cattle-system/c-c-65mvh" not found ` and after a while: `Error while applying agent YAML, it will be retried automatically: exit status 1, Unable to connect to the server: net/http: request canceled (Client.Timeout exceeded while awaiting headers):secrets "cattle-system/c-c-65mvh" not found `

**To Reproduce**
 

**Result**
Cluster cannot be managed anymore
**Expected Result**

Cluster can be managed
**Screenshots**

<img width="2346" alt="Screen Shot 2021-11-19 at 10 51 00" src="https://user-images.githubusercontent.com/33149391/142602550-de0b6c97-47b9-4d84-9134-83a1208bc1a1.png">
**Additional context**

**Comment by dcardellino** [comment]
Anyone?????

**Comment by dcardellino** [comment]
Close, recreated cluster, because no one is able to get me a damn answer... thanks rancher 👏

**Comment by Forbzy** [comment]
Just experienced the same issue. It's frustrating there isn't a solution yet.

**Comment by frost52** [comment]
The only way to fix that we found was to recover the secret from backups
