### ISSUE TITLE
Validate Rocky Linux 8.5

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#35607]
https://docs.rockylinux.org/release_notes/8_5/

Following https://github.com/rancher/rancher/issues/35460

**Comment by bjornbouetsmith** [comment]
Hi @superseb,

I wonder why this was closed.

I have just tried to install Rancher on Rocky Linux 8.5 - and it does not work at all.

It seems like Rocky Linux is using a systemd package that causes [k3s to just exit](https://forums.rancher.com/t/help-on-issue-fatal-k3s-exited-with-exit-status-255/36373/3) with and never come up.

So and the version that works was from Rocky Linux 8.4 - so if Rancher works on RHEL 8.5 - its not the same as Rocky Linux 8.5.

So is it possible that you guys can work on getting it working on Rocky Linux 8.5?

Or do we have to downgrade to Rocky Linux 8.4 if thats even possible?

I will be happy to help diagnose if required.

Thanks
