### ISSUE TITLE
clusters stuck in 'unavailable' when upgrading from 2.5.11 to 2.6-head

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#35619]
**Rancher Server Setup**
- Rancher version: **2.5.11**
- Installation option (Docker install/Helm Chart): **Docker**

**Information about the Cluster**
- Kubernetes version: 1.20.12
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
     DO RKE v1.20.12
     EC2 RKE v1.20.12
     Custom RKE v1.20.12

**Describe the bug**
When upgrading to `2.6-head Commit ID 4ddeafb` UI upgraded, and clusters are stuck in `Unavailable`

**To Reproduce**
1. created a 2.5.11 docker install
2. created clusters - DO, EC2, GKE and Custom
3. stopped docker container
4. UI has updated to `2.6-head Commit ID 4ddeafb`
5. clusters are stuck in provisioning status
6. I cannot explore any of the clusters via the hamburger menu
7. The clusters have been `unavailable` for > 45 minutes.

**Result**
Clusters in unavailable

**Expected Result**
Clusters update and become Active

**Screenshots**
<img width="1406" alt="Screen Shot 2021-11-19 at 3 52 34 PM" src="https://user-images.githubusercontent.com/89212856/142691336-06292746-6016-47b3-b54c-c2612061fc20.png">

**Comment by ronhorton** [comment]
docker logs from this upgrade: 
```2021/11/19 21:48:59 [ERROR] failed to start cluster controllers c-zbsxf: context canceled
2021/11/19 21:49:01 [ERROR] error syncing 'c-zbsxf': handler cluster-deploy: Get "https://104.248.10.148:6443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": cluster agent disconnected, requeuing
2021-11-19 21:49:39.258638 I | mvcc: store.index: compact 126385
2021-11-19 21:49:39.319559 I | mvcc: finished scheduled compaction at 126385 (took 57.436355ms)
2021/11/19 21:49:51 [ERROR] error syncing 'system-library': handler system-image-upgrade-catalog-controller: upgrade cluster c-crlbh system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-crlbh] kubernetes version, handler system-image-upgrade-catalog-controller: upgrade cluster local system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [local] kubernetes version, requeuing
2021/11/19 21:50:56 [INFO] Stopping cluster agent for c-zbsxf
2021/11/19 21:50:56 [ERROR] failed to start cluster controllers c-zbsxf: context canceled
2021/11/19 21:50:57 [ERROR] error syncing 'c-j5nkd': handler cluster-deploy: Get "https://18.222.109.201:6443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": cluster agent disconnected, requeuing
2021/11/19 21:50:58 [INFO] Stopping cluster agent for c-j5nkd
2021/11/19 21:50:58 [ERROR] failed to start cluster controllers c-j5nkd: context canceled
2021/11/19 21:51:03 [INFO] Stopping cluster agent for c-pgsmn
2021/11/19 21:51:03 [ERROR] failed to start cluster controllers c-pgsmn: context canceled
2021/11/19 21:51:21 [ERROR] error syncing 'c-pgsmn': handler cluster-deploy: Get "https://18.188.226.129:6443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": cluster agent disconnected, requeuing
2021/11/19 21:51:51 [ERROR] error syncing 'c-zbsxf': handler cluster-deploy: Get "https://104.248.10.148:6443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": cluster agent disconnected, requeuing
2021/11/19 21:51:52 [ERROR] error syncing 'system-library': handler system-image-upgrade-catalog-controller: upgrade cluster c-crlbh system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [c-crlbh] kubernetes version, handler system-image-upgrade-catalog-controller: upgrade cluster local system service logging failed: template system-library-rancher-logging incompatible with rancher version or cluster's [local] kubernetes version, requeuing
2021/11/19 21:52:40 [INFO] Stopping cluster agent for c-j5nkd
2021/11/19 21:52:40 [ERROR] failed to start cluster controllers c-j5nkd: context canceled
2021/11/19 21:52:40 [INFO] Stopping cluster agent for c-zbsxf
2021/11/19 21:52:40 [ERROR] failed to start cluster controllers c-zbsxf: context canceled
2021/11/19 21:53:11 [INFO] Stopping cluster agent for c-pgsmn
2021/11/19 21:53:11 [ERROR] failed to start cluster controllers c-pgsmn: context canceled

**Comment by thedadams** [comment]
It looks like the original Rancher server was started with the `server_url` set to `https://18.118.1.142`.

Then, when the Docker install was upgraded, the new Rancher server was started at `https://18.118.1.142:444`. This disallows the cluster-agents running on the downstream clusters to connect to Rancher when the upgrade completes.

The new Rancher server must be created at the same IP/Hostname as the original one for the upgrades to work.

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.11 to 2.6-head commit id: `e322f8f`**

- Docker install of rancher
- the clusters are Active.
- Post upgrade checks on the downstream clusters - RKE1 DO and GKE v2 cluster look good
