### ISSUE TITLE
redeploy container with destroing

### ISSUE THREAD

**Issue by fedya** [rancher/rancher#3563]
Very need option which perfom full redeploy of the service.
At this moment when i press restart what's going on: stop service, start service from OLD image
But i need a button for full restart, with destoying old container and starting new one.

The closest analogue is "redeploy" button on Tutum or Docker.cloud.
See pic.

![snapshot6](https://cloud.githubusercontent.com/assets/598477/12902510/b7b1ce9e-ced2-11e5-8c16-10337c8cbed9.png)

**Comment by vincent99** [comment]
Restart is restart; containers are not created or destroyed.  It sounds like you want the Upgrade action.

**Comment by fedya** [comment]
@vincent99 maybe you are right. I just need a button with full-cycle redeploy/upgrade like in docker.cloud.

At this moment i have around 25 containers with services: webui, 3 databases, backends, frontends, backend workers, rpm builders, etc.
From time to time i commit changes into the code and i need full redeploy of the service, e.g:
1. stop container
2. pull new image
3. remove stopped
4. run new

What i'm doing now, when i need full redeploy:
1. remove old image by hands
2. clone container
3. stop. delete. purge old container
4. start cloned

**Comment by vincent99** [comment]
Again, upgrade:

![image](https://cloud.githubusercontent.com/assets/753917/12923464/1acee5ee-cf13-11e5-9c4f-266c49af718f.png)

![image](https://cloud.githubusercontent.com/assets/753917/12923449/0ad93cde-cf13-11e5-9d91-3008173c4e4f.png)

**Comment by fedya** [comment]
Thanks you!
It was not obvious!
