### ISSUE TITLE
 PVC Resize in Rancher 2.6 missing

### ISSUE THREAD

**Issue by airbjorn** [rancher/rancher#35630]
After the update to Rancher 2.6, I don't find the menu entry for PVC resizing any more.

Before in Rancher 2.5, it had been available through the cluster's "Projects" view in the tab "Volumes". Through the "burger menu" of each PVC, the Resize function could get selected.

Did you implement the PVC Resizing in Rancher 2.6?

**Comment by sebastianadorno** [comment]
same problem here, i cant find the resize option.
