### ISSUE TITLE
Rancher pod fails with error: `panic: indexer conflict: map[byPod:{}]`

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#35643]
**Rancher Server Setup**
- Rancher version: `v2.6-44b8030a00b29f9f5354c645f3a90ede2eea53e0-head` (supposed to be `(v2.6.3-rc2)`)
- Installation option (Docker install/Helm Chart): HelmChart (rancherd)
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.21.6+rke2r1`
- rancher/fleet:v0.3.8-rc2
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): A local cluster provisioned with rancherd

**Describe the bug**

After deploying the rancher, the rancher pod continues failing with panic:
```
2021/11/23 10:48:54 [INFO] Watching metadata for upgrade.cattle.io/v1, Kind=Plan
2021/11/23 10:48:54 [INFO] Watching metadata for apps/v1, Kind=ReplicaSet
2021/11/23 10:48:54 [INFO] Watching metadata for networking.k8s.io/v1, Kind=IngressClass
2021/11/23 10:48:54 [INFO] Watching metadata for /v1, Kind=ServiceAccount
2021/11/23 10:48:54 [INFO] Watching metadata for storage.k8s.io/v1, Kind=CSINode
2021/11/23 10:48:54 [INFO] Watching metadata for /v1, Kind=Pod
2021/11/23 10:48:54 [INFO] Watching metadata for rbac.authorization.k8s.io/v1, Kind=RoleBinding
2021/11/23 10:48:58 [INFO] rkecluster fleet-local/local: provisioning bootstrap node(s) custom-72af5bcab767: waiting for agent to check in and apply initial plan
panic: indexer conflict: map[byPod:{}]

goroutine 508 [running]:
k8s.io/apimachinery/pkg/util/runtime.Must(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:171
github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1.(*operationCache).AddIndexer(0xc0056a5e60, 0x44ebf21, 0x5, 0x472ce40)
        /go/src/github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1/operation.go:247 +0x127
github.com/rancher/rancher/pkg/controllers/dashboard/helm.RegisterOperations(0x4cc6bc8, 0xc0045ec040, 0x4d30238, 0xc0010fda20, 0x4d16bc8, 0xc008765a40, 0x4d145b8, 0xc008765b20)
        /go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/operations.go:42 +0x1b8
github.com/rancher/rancher/pkg/controllers/dashboard/helm.Register(0x4cc6bc8, 0xc0045ec040, 0xc0017c2820)
        /go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/register.go:22 +0x3c5
github.com/rancher/rancher/pkg/controllers/dashboard.Register(0x4cc6bc8, 0xc0045ec040, 0xc0017c2820, 0xc0056a5b00, 0x3cc4b00, 0x6f60f20)
        /go/src/github.com/rancher/rancher/pkg/controllers/dashboard/controller.go:23 +0x5a
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1.1(0x4cc6bc8, 0xc0045ec040, 0x3cc4b00, 0x6f60f20)
        /go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:245 +0x4e
github.com/rancher/rancher/pkg/wrangler.(*Context).StartWithTransaction(0xc0017c2820, 0x4cc66f8, 0xc0023be440, 0xc0043a5f58, 0x0, 0x0)
        /go/src/github.com/rancher/rancher/pkg/wrangler/context.go:152 +0xdc
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1(0x4cc66f8, 0xc0023be440, 0x4561112, 0x1e)
        /go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:245 +0x107
github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader.func1(0xc000b08000, 0xc000d54300)
        /go/pkg/mod/github.com/rancher/wrangler@v0.8.9/pkg/leader/manager.go:51 +0xcc
created by github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader
        /go/pkg/mod/github.com/rancher/wrangler@v0.8.9/pkg/leader/manager.go:48 +0x49
```

**To Reproduce**
 
Use rancherd to deploy a RKE2 cluster:
```
mkdir -p /etc/rancher/rke2/config.yaml.d/
cat > /etc/rancher/rke2/config.yaml.d/90-harvester-server.yaml <<EOF
disable: rke2-ingress-nginx
EOF

mkdir -p /etc/rancher/rancherd
cat > /etc/rancher/rancherd/config.yaml << EOF
role: cluster-init
token: somethingrandom
kubernetesVersion: stable:rke2
rancherVersion: v2.6-44b8030a00b29f9f5354c645f3a90ede2eea53e0-head
rancherValues:
  features: multi-cluster-management=false
EOF

curl -fL https://raw.githubusercontent.com/rancher/rancherd/master/install.sh | sh -
```

Wait for the rancher pod to be deployed, the rancher pod will fail with panic.

Or use this vagrant file to start a VM: https://github.com/bk201/try-rancherd/blob/c00956d219a54786929c014d2344176b42037fc1/Vagrantfile

**Result**

**Expected Result**

The rancher pod should run without error.

**Screenshots**

**Additional context**

There is a similar error in https://github.com/rancher/rancher/issues/34971

**Comment by w13915984028** [comment]
Is it possible to be related?

Please check if the code can simply loop here, the ` m.leaderCTX `  is not reset to default/renew  before the new loop, it may contain half produced data in previous loop. Or those module should not use "Must" to assert if their data is not already there. (the panic here)

The log show `"failed to call leader func..."`  first, then panic ( unfortunately, panic had no timestamp), if it is 5 seconds late than the fail, then it is clear.

Rancher.Start can not be simply run twice without cleaning previous data,
________
 46 // OnLeader this function will be called when leadership is acquired.
 47 func (m *Manager) OnLeader(f func(ctx context.Context) error) {
 48         go func() {
 49                 <-m.leaderChan
 50                 for {
 51                         if err := f(m.leaderCTX); err != nil {
 52                                 logrus.Errorf("failed to call leader func: %v", err)
 53                                 time.Sleep(5 * time.Second)
 54                                 continue
 55                         }
 56                         break
 57                 }
 58         }()
 59 }
 
 
 Rancher Start
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1(0x4cc66f8, 0xc00fa1fec0, 0x4561112, 0x1e)
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:245 +0x107
	
	
	
the full log:
https://gist.github.com/bk201/560580731bf16e135107bf4c10810b8c

I1123 07:04:00.647777      34 leaderelection.go:258] `successfully acquired lease kube-system/cattle-controllers`
2021/11/23 07:04:00 [INFO] Steve auth startup complete
...
	
2021/11/23 07:04:01 [ERROR] `failed to call leader func`: the server could not find the requested resource (get projects.meta.k8s.io)
...
...
2021/11/23 07:04:01 [INFO] Starting management.cattle.io/v3, Kind=FleetWorkspace controller
`panic: indexer conflict: map[byPod:{}] `(edited)

**Comment by ibuildthecloud** [comment]
Can you provide more logs.  The issue is basically that the leader isn't starting on the first try.

**Comment by bk201** [comment]
> Can you provide more logs. The issue is basically that the leader isn't starting on the first try.

Sorry I forgot to attach the full log: [rancher.log](https://github.com/rancher/rancher/files/7593048/rancher.log)

**Comment by ibuildthecloud** [comment]
@bk201 does the pod crash once and then restart and work. Or does it get stuck crashing in a loop?

**Comment by bk201** [comment]
@ibuildthecloud It gets stuck crashing in a loop with the same panic.

**Comment by xMAC94x** [comment]
I have a simmilar problem with rancher `v2.6.3-rc2`  and  kubernetes `v1.21.5+k3s2`
```
2021/11/25 11:08:14 [INFO] Watching metadata for traefik.containo.us/v1alpha1, Kind=IngressRouteTCP
2021/11/25 11:08:14 [INFO] Watching metadata for rke.cattle.io/v1, Kind=RKEBootstrap
2021/11/25 11:08:14 [INFO] Watching metadata for discovery.k8s.io/v1, Kind=EndpointSlice
2021/11/25 11:08:14 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha4, Kind=Cluster
2021/11/25 11:08:14 [INFO] Watching metadata for fleet.cattle.io/v1alpha1, Kind=ClusterRegistration
2021/11/25 11:08:14 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha4, Kind=MachineSet
2021/11/25 11:08:14 [INFO] Watching metadata for /v1, Kind=ResourceQuota
2021/11/25 11:08:14 [INFO] Watching metadata for networking.k8s.io/v1, Kind=Ingress
panic: indexer conflict: map[byPod:{}]

goroutine 121 [running]:
k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:171
github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1.(*operationCache).AddIndexer(0xc0049f76e0, 0x44ebf21, 0x5, 0x472ce40)
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1/operation.go:247 +0x127
github.com/rancher/rancher/pkg/controllers/dashboard/helm.RegisterOperations(0x4cc6bc8, 0xc005304840, 0x4d30238, 0xc0014c8000, 0x4d16bc8, 0xc005236d20, 0x4d145b8, 0xc005236d90)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/operations.go:42 +0x1b8
github.com/rancher/rancher/pkg/controllers/dashboard/helm.Register(0x4cc6bc8, 0xc005304840, 0xc0017a8ea0)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/register.go:22 +0x3c5
github.com/rancher/rancher/pkg/controllers/dashboard.Register(0x4cc6bc8, 0xc005304840, 0xc0017a8ea0, 0xc0049f7400, 0x3cc4b00, 0x6f60f20)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/controller.go:23 +0x5a
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1.1(0x4cc6bc8, 0xc005304840, 0x3cc4b00, 0x6f60f20)
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:245 +0x4e
github.com/rancher/rancher/pkg/wrangler.(*Context).StartWithTransaction(0xc0017a8ea0, 0x4cc66f8, 0xc00226d480, 0xc00594bf58, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/wrangler/context.go:152 +0xdc
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1(0x4cc66f8, 0xc00226d480, 0x4561112, 0x1e)
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:245 +0x107
github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader.func1(0xc001595980, 0xc00001d3a0)
	/go/pkg/mod/github.com/rancher/wrangler@v0.8.9/pkg/leader/manager.go:51 +0xcc
created by github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader
	/go/pkg/mod/github.com/rancher/wrangler@v0.8.9/pkg/leader/manager.go:48 +0x49
```

**Comment by bk201** [comment]
I can confirm the issue is fixed by using image tag: `v2.6-b6a6ee9a1ce1aed238fb266b48e9dea8802694f0-linux-amd64`

**Comment by guangbochen** [comment]
close in favor `v2.6.3-rc4`.

**Comment by dnauck** [comment]
Same issue after upgrading from 2.5.9 to 2.6.3-patch1

**Comment by jeroenhartgers** [comment]
> I had the same issue, Rancher 2.6.3-patch1 (upgraded from v2.5.9) k8s version 1.21.8. I noticed that error message : `level=error msg="failed to call leader func: namespaces \"fleet-default\" not found"` (Sometimes that line was just above the stack trace sometimes it was way above)
> 
> Creating the fleet-default namespace seems to have solved the issue

Same here for 2.6.2 -> 2.6.3 upgrade

**Comment by all4innov** [comment]
Got the same error when migrating from 2.6.6 to 2.6.7 or 2.6.8
(Rancher 2.6.6 deployed on AWS EKS 1.22)
Any tips ?

**Comment by vichaos** [comment]
`level=error msg="failed to call leader func: namespaces \"<namespace>\" not found"`



> I had the same issue, Rancher 2.6.3-patch1 (upgraded from v2.5.9) k8s version 1.21.8. I noticed that error message : `level=error msg="failed to call leader func: namespaces \"fleet-default\" not found"` (Sometimes that line was just above the stack trace sometimes it was way above)
> 
> Creating the fleet-default namespace seems to have solved the issue



`stern rancher -n cattle-system|grep "failed to call leader func: namespaces"`
```
level=error msg="failed to call leader func: namespaces \"<namespace_a>\" not found"
level=error msg="failed to call leader func: namespaces \"<namespace_b>\" not found"
level=error msg="failed to call leader func: namespaces \"<namespace_c>\" not found"
level=error msg="failed to call leader func: namespaces \"<namespace....>\" not found"
```
Create all missing namespaces seems to be solved the  issue. `upgrading from 2.5.8->2.6.11->2.7.1`

**Comment by janeczku** [comment]
[rancher-pod-crash.log.zip](https://github.com/rancher/rancher/files/11224029/rancher-pod-crash.log.zip)
