### ISSUE TITLE
Cluster state switches between Active and Unavailable after provisioning

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35640]
**Rancher Server Setup**
- Rancher version: 2.6-head `744f32fe`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: 1.22.3
- Cluster Type (Local/Downstream): DO RKE1 node driver

**Describe the bug**
Cluster state switches between Active and Unavailable after provisioning

**To Reproduce**

- Deploy a DO downstream cluster
- When the cluster comes up Active, it switches between Active and Unavailable for a few seconds message: `Cluster agent is not connected`
- Then it comes up Active

**Expected Result**
The cluster state should not toggle between the two states constantly. 

**Note:**
In case on an EC2 1.21 cluster, i see cluster is stuck in Unavailable state with message `Cluster agent is not connected` beforre ocming up Active.

**Comment by yuchunyun** [comment]
I have the same problem

**Comment by sowmyav27** [comment]
@yuchunyun Could you give us more information about your rancher server and cluster details. Appreciate it you could fill this out.


- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Comment by yuchunyun** [comment]
@sowmyav27 
rancher version: v2.6
docker run -dit --name rancher --privileged --network host rancher/rancher:v2.6-ca431e84dbeb247f9c7ee8425773847e891e89aa-linux-amd64

kubernetes version: v1.22.2
cluster type: imported

![image](https://user-images.githubusercontent.com/45453883/144526402-3f0fe4a4-cb1e-4b6e-a4ff-2b29bbba3395.png)

![image](https://user-images.githubusercontent.com/45453883/144526496-6bd61b15-427e-451d-9e45-ad370a36a939.png)

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/35546

**Comment by brudnak** [comment]
# My checks PASSED

<hr>
  
## Validation Environment

| Component               | Version / Type                                             |
| ----------------------- | ---------------------------------------------------------- |
| Rancher version         | v2.6-0d14421ed802615bcc6f07fc38faae6753281d2f-head         |
| Rancher cluster type    | Docker                                                     |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2                    |
| Helm version            | v2.16.8-rancher1                                           |
| Downstream cluster type | RKE1 Digital Ocean                                         |
| Downstream K8s version  | 1.22                                                       |
| Browser type            | Google Chrome                                              |
| Browser version         | 96.0.4664.55 (Official Build) (x86_64)                     |
| Cloud Credentials       | Digital Ocean & AWS Cloud Credentials Setup Prior to Steps |

## Validation steps

1. Create RKE1 Digital Ocean Nod Driver Cluster
    - Starting from the **default** Rancher homepage `/dashboard/home`
    - Click `hamburger menu` -> click `Cluster Management` -> click `Create` -> click `DigitalOcean` (as RKE1)
    - Fill out the Digital Ocean cluster creation form
        - Cluster Name: `provide a cluster name`
        - Create or select a node template
        - k8s version: `v1.22.4-rancher1-1`
        - Click `Create` -> redirected back to the `Clusters` Page
2. Observe the UI, specifically the `State` of the newly created RKE1 Digital Ocean cluster

### RESULT

The cluster starts in the `Provisioning` state. It stays in provisioning for 6 minutes with a message: `Waiting for etcd, controlplane and worker nodes to be registered`.

At 6 minutes the state changes from `Provisioning` to `Waiting` with a message of: `Waiting for API to be available`.

At 7 minutes the state changes from `Waiting` to `Active`. And the state **stays** in `Active` from this point forward.

The same results were also seen using an AWS EC2 RKE1 node driver.

## Additional Info

The cluster **did not** go into an unavailable state for DigitalOcean or AWS.
