### ISSUE TITLE
Not able to upgrade library app from the dashboard UI legacy apps

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35658]
**Rancher Server Setup**
- Rancher version: `v2.6-head 4375161 `
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.22.3+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: v1.20.11
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 3 worker, 1 etcd, 1 cp`

**Describe the bug**
Installed wordpress app on the rancher server v2.6-head. From the dashboard UI - legacy apps, if we upgrade the app to a later version, upgrade fails.

**To Reproduce**
1. On 2.6-head rancher server, install word press app version `v7.3.8` from  dashboard UI --> legacy --> apps --> launch
3. From dashboard UI --> legacy --> Select Project `default` in the namespace picker --> apps
4. Upgrade the word press app version to `9.0.3`

**Result**
Upgrade fails with the error 
```
Failed to install app wordpress. Error: UPGRADE FAILED: Deployment.apps "wordpress" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"wordpress", "app.kubernetes.io/name":"wordpress"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

```
**Expected Result**
Expected the app installation to go through without any error

**Additional context**
Found while validating the issue https://github.com/rancher/rancher/issues/34700

**Comment by rmweir** [comment]
depends on https://github.com/rancher/rancher/issues/35680.

**Comment by rmweir** [comment]
Turns out this is an issue with the chart. This would happen in 2.5 as well. The matchLabel selectors are different, making the upgrade incompatible because those are immutable. See https://github.com/rancher/charts/blob/master/charts/wordpress/v7.3.8/templates/deployment.yaml#L12 and https://github.com/rancher/charts/blob/master/charts/wordpress/v9.0.3/templates/deployment.yaml#L8.

**Comment by anupama2501** [comment]
Verified from 2.5.11 --> 2.6.3-rc4

- Installed docker-registry, redis, tidb-operator , and wordpress . 
- Upgraded the rancher version and after upgrading the above mentioned apps, verified the upgrade errors out only for the wordpress app.
- Upgrade for docker-registry, redis, tidb-operator went through fine without any error.
