### ISSUE TITLE
rancher/wrangler#183 breaks application of DesiredSet containing mix of namespaced and cluster-scoped resources

### ISSUE THREAD

**Issue by brandond** [rancher/rancher#35656]
The fix for rancher/rancher#34712 at https://github.com/rancher/wrangler/pull/183 breaks K3s when pulled in. Application of our RBAC manifest via `apply.WithOwner(&addon).Apply(objectSet)` fails with:

```
INFO[0006] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"ccm", UID:"650e58b1-a7a5-41f3-a087-965d96fc9a12", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"248", FieldPath:""}): type: 'Normal' reason: 'ApplyingManifest' Applying manifest at "/var/lib/rancher/k3s/server/manifests/ccm.yaml"
E1124 01:15:21.603588      53 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}: context canceled
E1124 01:15:21.603714      53 writers.go:117] apiserver was unable to write a JSON response: http: Handler timeout
ERRO[0006] error while range on /registry/clusterroles/ /registry/clusterroles/: context canceled
E1124 01:15:21.604781      53 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1124 01:15:21.605848      53 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E1124 01:15:21.607400      53 timeout.go:135] post-timeout activity - time-elapsed: 3.680078ms, GET "/apis/rbac.authorization.k8s.io/v1/clusterroles" result: <nil>
E1124 01:15:21.607887      53 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}: context canceled
ERRO[0006] error while range on /registry/clusterrolebindings/ /registry/clusterrolebindings/: context canceled
E1124 01:15:21.609981      53 writers.go:117] apiserver was unable to write a JSON response: http: Handler timeout
E1124 01:15:21.611010      53 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1124 01:15:21.612350      53 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E1124 01:15:21.613573      53 timeout.go:135] post-timeout activity - time-elapsed: 5.593728ms, GET "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings" result: <nil>
INFO[0006] Event(v1.ObjectReference{Kind:"Addon", Namespace:"kube-system", Name:"ccm", UID:"650e58b1-a7a5-41f3-a087-965d96fc9a12", APIVersion:"k3s.cattle.io/v1", ResourceVersion:"248", FieldPath:""}): type: 'Warning' reason: 'ApplyManifestFailed' Applying manifest at "/var/lib/rancher/k3s/server/manifests/ccm.yaml" failed: failed to list rbac.authorization.k8s.io/v1, Kind=ClusterRole for  kube-system/ccm: the server could not find the requested resource, failed to list rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding for  kube-system/ccm: the server could not find the requested resource
```

Controller code: https://github.com/k3s-io/k3s/blob/master/pkg/deploy/controller.go#L210
The manifest in question: https://github.com/k3s-io/k3s/blob/master/manifests/ccm.yaml

As per @snasovich:
> When importing objects of certain GVK we’re calculating distinct namespaces based on the whole list of objects, not the ones of this specific GVK.

**Comment by snasovich** [comment]
The issue is reproducible on manifests that mix namespace and non-namespaced objects, e.g.:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k3s-cloud-controller-manager
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k3s-cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k3s-cloud-controller-manager
subjects:
- kind: User
  name: k3s-cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k3s-cloud-controller-manager-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: User
  name: k3s-cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k3s-cloud-controller-manager-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: User
  name: k3s-cloud-controller-manager
  namespace: kube-system
```

**Comment by snasovich** [comment]
Finally ready to test on `v2.6-head`, had issues getting build to pass.

**Comment by snasovich** [comment]
### Root cause
Changes done per https://github.com/rancher/wrangler/pull/183 resulted in Rancher attempting to search for cluster-scoped objects in namespace scope and vice-versa when a mix of namespaced and cluster-scoped objects are included in Import YAML manifest. This was due to the whole object set being used to evaluate distinct namespaces, not just ones of group-version-kind being processed.
 
### What was fixed, or what changes have occurred
Only objects of currently processed group-version-kind are used to determine distinct namespaces to use for searching.
 
### Areas or cases that should be tested
Import YAML functionality at cluster level
 
### What areas could experience regressions?
This should be a pretty safe change, but technically any area that uses Wrangler's Apply functionality (which is a lot in Rancher - e.g. Fleet). Suggesting to not specifically test for regressions, but just to be aware of this change in case possibly related issues are found.
 
### Are the repro steps accurate/minimal?
Yes, can use YAML mentioned in https://github.com/rancher/rancher/issues/35656#issuecomment-981265558 and try to import it via Rancher UI.

**Comment by snasovich** [comment]
@jakefhyde - please complete dev validation for this, thank you!

**Comment by jakefhyde** [comment]
Setup
-
docker install on `v2.6-head`

Validation
-
Import yaml from [#35656 (comment)](https://github.com/rancher/rancher/issues/35656#issuecomment-981265558)

No issues noted regarding the import, no logs generated regarding the import. @snasovich is there anything specific I should be looking for in regards to validation?

**Comment by snasovich** [comment]
@jakefhyde , thank you for testing this. This test should technically be sufficient, but please add a screenshot showing the summary of the import which indicates the success of the operation.
Ideally, we would also like to test their YAMLs that feature only namespace or only cluster scoped objects as well as combinations of them to ensure these cases still work OK.

**Comment by jakefhyde** [comment]
Confirmed it is still possible to import yaml with only namespace or only cluster scoped objects:
![namespace-only](https://user-images.githubusercontent.com/33796120/145458148-ed65d376-fe2f-4504-b1c0-b997ea1ad247.png)
![global-only](https://user-images.githubusercontent.com/33796120/145458178-230ad233-bc0b-4c0b-ba83-cbb671022fde.png)
