### ISSUE TITLE
TLS Settings has no effect

### ISSUE THREAD

**Issue by johnliu55tw** [rancher/rancher#35654]
**Rancher Server Setup**
- Rancher version: v2.6.2
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Describe the bug**
I'm testing out TLS Settings of Rancher according to this [page](https://rancher.com/docs/rancher/v2.6/en/installation/resources/tls-settings/) and it's not working:

- Set `CATTLE_TLS_MIN_VERSION=1.3` results in error:
    ```
    [FATAL] failed to setup TLS listener: error while configuring minimal TLS version: invalid minimal TLS version [1.3], must be one of: 1.2 1.1 1.0
    ```

- Set `CATTLE_TLS_MIN_VERSION=1.0` then I use command `nmap --script ssl-enum-ciphers` to check the supported TLS versions, but the minimum supported TLS version is still 1.2:
  ```
  $ nmap --script ssl-enum-ciphers -p 443 192.168.122.163
  Starting Nmap 7.92 ( https://nmap.org ) at 2021-11-23 16:06 CST
  Nmap scan report for 192.168.122.163
  Host is up (0.00020s latency).
  
  PORT    STATE SERVICE
  443/tcp open  https
  | ssl-enum-ciphers:
  |   TLSv1.2:
  |     ciphers:
  |       TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
  |       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
  |       TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (secp256r1) - A
  |     compressors:
  |       NULL
  |     cipher preference: server
  |   TLSv1.3:
  |     ciphers:
  |       TLS_AKE_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
  |       TLS_AKE_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
  |       TLS_AKE_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
  |     cipher preference: client
  |_  least strength: A
  
  Nmap done: 1 IP address (1 host up) scanned in 0.16 seconds
  ```
**To Reproduce**
- Starting Rancher with docker, add an environment variable to set minimum TLS version to 1.3 results in error:
    ```
    docker run -d --restart=unless-stopped \
      -p 80:80 -p 443:443 \
      --privileged \
      -e CATTLE_TLS_MIN_VERSION=1.3 \
      rancher/rancher:v2.6.2
    ```
- When starting Rancher with docker, add an environment variable to set minimum TLS version to 1.0:
    ```
    docker run -d --restart=unless-stopped \
      -p 80:80 -p 443:443 \
      --privileged \
      -e CATTLE_TLS_MIN_VERSION=1.0 \
      rancher/rancher:v2.6.2
    ```
- Run command `nmap --script ssl-enum-ciphers -p 443 <IP>` shows the minimum TLS version is still 1.2.

**Expected Result**
`CATTLE_TLS_MIN_VERSION` should change the minimum TLS version without error out.

**Screenshots**

**Additional context**

I also tested on the Rancher deployment inside of Harvester and it's not working either.

**Comment by yasker** [comment]
@johnliu55tw Is this a blocker for Harvester TLS feature? (I assume https://github.com/harvester/harvester/issues/761 )

**Comment by johnliu55tw** [comment]
@yasker This is more like a blocker for https://github.com/harvester/harvester/issues/1046. However, I had a discussion with @gitlawr and he planned to add an ingress controller for https://github.com/harvester/harvester/issues/761, so in the end, we will be configuring the TLS settings of the ingress controller for both features. In this case, this issue is not a blocker.

**Comment by snasovich** [comment]
@yasker @johnliu55tw , given the comments above, is this something we have to do in 2.6.3 or it can be shipped later?

**Comment by yasker** [comment]
I don't think this is a blocker for 2.6.3 per @johnliu55tw and @gitlawr .

**Comment by guangbochen** [comment]
move this to v2.6.4 as the current workaround on the Harvester side works and this is a common issue on the Rancher side, thanks.

**Comment by snasovich** [comment]
@yasker , this is with `team/area1` so I'll let @cbron or @samjustus comment on this (though I don't see any milestone set on it).

**Comment by samjustus** [comment]
We will discuss as a team on Feb 24 and I will advise shortly after!

**Comment by samjustus** [comment]
SURE-5063

**Comment by cbron** [comment]
should be fixed now
