### ISSUE TITLE
Rancher Helm chart - Multiple Hosts?

### ISSUE THREAD

**Issue by dcardellino** [rancher/rancher#35659]
We are deploying Rancher with the current Helm Chart.
We set the Rancher Hostname to our internal service domain: `rancher.internal.k8s.cluster`

But we also need to need the ingress listening to our public service domain: `rancher.public.domain.com`

is there any possibility to solve this with this helm chart?

**Comment by digiserg** [comment]
It does not look possible, the current helm chart supports a [single](https://github.com/rancher/rancher/blob/release/v2.6/chart/templates/ingress.yaml#L40) hostname.

**Comment by dcardellino** [comment]
@digiserg Sure, i know. But it would be nice to have the ability to have more host names
