### ISSUE TITLE
Rancher returns a "404 page not found" error when editing and saving a role in YAML

### ISSUE THREAD

**Issue by yankcrime** [rancher/rancher#35666]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): Standard Helm install of Rancher 2.6.2, self-signed certificate

**Information about the Cluster**
- Kubernetes version: v1.21.3+k3s1
- Cluster Type (Local/Downstream): local

**Describe the bug**
Using the Rancher UI to edit a role as YAML and then hitting 'save' - even if no changes have been made ' returns a 404 "page not found" error.  The changes are not saved.

**To Reproduce**
Navigate to "Users & Authentication", "Roles", and then edit any role as YAML.  Hit 'Save'.

**Result**
A 404 is returned.

**Expected Result**
A 200 is returned if the changes are valid and can saved, else some other 4xx error.

**Comment by jayntguru** [comment]
I'm able to reproduce the issue above.

What brought me here though was attempting to edit the yaml for a cluster. I get the same 404 there too.

**Comment by eumel8** [comment]
#metoo

There are rumors that future version of Rancher won't support editing cluster.yaml in a raw file. The first result is here that PUT requests will blocked with `https://<rancher-server>/blocked`, when you save the changes in the Rancher UI.

You can resend your PUT request in the browser by changing the URL from 

from `https://<rancher-server>/blocked`
to `https://<rancher-server>/k8s/clusters/local/apis/management.cattle.io/v3/clusters/<cluster-id>`

For shure, you can change cluster.yaml also with `kubectl -n local edit clusters.management.cattle.io <cluster-id>`
but in that case the dashboard shouldn't offer the option to edit the file as yaml.

**Comment by eumel8** [comment]
Update:

There are 2 ways to edit cluster as yaml, but only one will work:

```
https://<rancher-server>/dashboard/c/<local-cluster-id>/manager/provisioning.cattle.io.cluster/fleet-default/<cluster-id>?as=config
```

and then "edit as yaml" like in Rancher 2.5

**Comment by hdp-sami** [comment]
I'm having the same issue.

I've tried @eumel8's methods but was without success.

**Comment by eumel8** [comment]
@hdp-sami this works only for editing cluster.yaml and not for each other yaml file. If you experience the same 404 error then you should check URI path which resource you really edit. I think there isn't a full mapping of all resources in Rancher.

**Comment by hdp-sami** [comment]
@eumel8 Sorry I should have been a bit clearer. I'm actually trying to modify the management cluster's yaml but haven't been able to get success using your methods. The kubectl way only seems to edit the actual cluster and not the management cluster.

**Comment by hdp-sami** [comment]
Can we please get an answer as to why this is happening and if there is a way we can edit the cluster's config? 

I have created a sync issue as I've added a new subnet to my autoscaling group in AWS. Rancher is complaining about this and I'm unable to modify my node groups in Rancher now because of it. 

I would like to be able to edit the cluster's configuration spec and add the new subnet to the node group to remove this sync issue. Any info or help here would be so greatly appreciated.
