### ISSUE TITLE
Enable addition of Windows worker nodes to existing clusters

### ISSUE THREAD

**Issue by HoustonDad** [rancher/rancher#35673]
**Is your feature request related to a problem? Please describe.**
Windows workloads are becoming more and more prominent, and at this time, adding a Windows OS node requires a new cluster to be built. It seems that the primary conflict, at this time, is the networking plugins, as Windows requires Flannel and RKE uses Canal by default.

**Describe the solution you'd like**
The ability to add Windows nodes to an existing cluster if all prerequisites are already met.

**Describe alternatives you've considered**
Additional clusters are required to be built at this time to enable Windows support in a RKE cluster.

**Comment by rosskirkpat** [comment]
@HoustonDad Apologies for the delay in a response here. Please reference the following [SUSE community post](https://community.suse.com/posts/the-future-of-windows-containers-on-rancher) regarding the future of RKE1 Windows. Currently, it is not planned to have this functionality added for Windows clusters on RKE1, however, RKE2 offers Windows support for existing clusters with certain cluster configurations.
