### ISSUE TITLE
Followed Okta integrations exactly, getting a 403 from rancher

### ISSUE THREAD

**Issue by rlewkowicz** [rancher/rancher#35679]
**Rancher Server Setup**
- Rancher version:  2.5.11
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
      Helm chart v 2.5.11 - EKS 

Ultimately, the login goes fine via the okta login box, gets here 
https://rancher.mydomain.tech/v1-saml/okta/saml/acs
And then 403's back to the login page. Where do I look to debug this further? What log do I tail to see what this is doing? The saml payload looks right to me

**Comment by t3hcr** [comment]
@rlewkowicz Are you attempting to auth from Okta to Rancher?  If so, I wonder if you're hitting the same issue other Okta integrating folks (like the two of us) are seeing.

There's another open issue here that I've been watching: https://github.com/rancher/rancher/issues/19196
