### ISSUE TITLE
[2.5 Back-port] Add functionality to specify limit of app revisions stored 

### ISSUE THREAD

**Issue by genexpr** [rancher/rancher#35677]
This is a forward port to 2.6 from an original 2.5 issue.

Issue [#20654](https://github.com/rancher/rancher/issues/20654)
Original [v2.5 PR](https://github.com/rancher/rancher/pull/35433)
Forward-port PR [v2.6 PR](https://github.com/rancher/rancher/pull/35514)

**Comment by genexpr** [comment]
# QA Testing
## Root cause

A cluster's database (etcd) stores app revisions for any created or updated app. On each app update, Rancher launches a new version of the app, replacing the old one. It also stores a new item in etcd – information on new app revision. These app revisions tend to accumulate over time. Rancher never cleans them up, which causes etcd to be overflown with app revision data and have performance problems, as a result. If etcd – the cluster database – crashes or works slowly, so does the cluster.

### What was fixed, or what changes have occurred

We now limit the maximum number of app revisions stored in the cluster database. The limit, `MaxRevisionCount`, is configured in the app when it is created. Any app revisions above the limit are deleted on any change to the app (upgrade or rollback). The oldest versions are deleted to maintain the maximum count and not one revision more. if `MaxRevisionCount` is not set or set to a number less than 1, then the default limit is 10. 

### Areas or cases that should be tested

1. A brand new app with MaxRevisionCount set.
2. A brand new app with MaxRevisionCount not set.
3. An existing app that already has many app revisions without a configured `MaxRevisionCount`. By default, the limit of stored app revisions is 10. On any change to the app, Rancher must remove the oldest revisions to maintain the maximum limit of 10. So if the app has 20 revisions, by default, the max is 10. On the next update, Rancher will create a 21st revision and then delete 11 of the oldest to ensure there are at most 10 and no more.

### What areas could experience regressions?

Note that there is an old existing bug where an upgrade to an app creates two revisions, not one.
[#35443](https://github.com/rancher/rancher/issues/35443)
This means you might exceed the max limit with fewer upgrades, but this is not directly related to the problem this issue fixes.

### Steps

In the old UI accessible with `https://{clusterURL}/g` and any project, create a new app (for example, the `redis` app) and set the value for `MaxRevisionCount`. It is not available in the UI but only in the initial request (use the API view to configure it). For example, set the value to 4.

Rollback to any previous version (the same one will work), which will create a new revision. Check the number of app revisions (by either looking at the number of revisions to which you can rollback in the UI or running `kubectl get apprevisions -A` in the kubectl shell. This number should never exceed the `MaxRevisionCount` for this app you had set before.

Keep making new revisions to verify that the oldest revisions are deleted to make "room" for new app revisions until you hit the max. You will come to a point where only 4 versions will exist at a time (if you had set the max to 4).

**Comment by genexpr** [comment]
The forward port PR has already been merged, this is for QA to track and test.
https://github.com/rancher/rancher/pull/35514

**Comment by jmcsagdc** [comment]
verified in v2.5-6ff6d08b210f5ce59f4c8dac817ae63af75a5d76-head

The sort and ejection is as expected (screenshot)
App rollback, upgrade works repeatedly as expected
API changes to the limit of revisions works as expected - Adjusting up or down the setting behaves as expected
Upgrade from 2.5.11 to 2.5-head with an installed app like redis allows upgrade, rollback, etc.
Initial value for setting is 10 revisions (as expected)

![2 5-backport](https://user-images.githubusercontent.com/15971368/146842206-0e6dce93-2e4a-46d4-ba75-347e42ae7b1c.jpg)
