### ISSUE TITLE
Container Volumes Shared With column shows purged containers

### ISSUE THREAD

**Issue by mishak87** [rancher/rancher#3567]
Create some containers sharing same host volume.
Delete and purge few.
Go to container volumes info `/infra/containers/<id>/volumes`.
It will show even purged containers.

**Comment by sshipway** [comment]
+1
The purged containers remain in the API and are never deleted, even after many days.

**Comment by vincent99** [comment]
There are exceptions for a few tables but in general nothing is ever deleted from the database and is accessible from the API if asking by ID.  Purged things shouldn't be returned in a regular list call, but https://github.com/rancher/rancher/issues/297 and this particular instance isn't being filtered out in the UI.

**Comment by fmorency** [comment]
+1

**Comment by vincent99** [comment]
Fixed in v2 volume api refactor

**Comment by tfiduccia** [comment]
Version - master 11/20
Verified fixed
