### ISSUE TITLE
Rancher backup too many colons in address

### ISSUE THREAD

**Issue by GillesMocellin** [rancher/rancher#35672]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details: self-signed certificate via cert-manager

**Information about the Cluster**
- Kubernetes version: v1.21.6+rke2r1 
- Cluster Type (Local/Downstream): local

**Describe the bug**
I want to backup my local cluster to a local S3 endpoint (Ceph Radosgw cluster), who's not listening on standard 443 TCP port (8080).
The endpoint URL is like https://my.local.dns:8080.
The backup fails with : 
    Failed to set s3 server: address https://public.labs.fiducial.cloud:8080: too many colons in address

**To Reproduce**
Set a backup with a custom S3 URL endpoint, with a specific TCP port (the URL will have 2 colons).

**Result**
Backup fails with the message : 
Failed to set s3 server: address https://public.labs.fiducial.cloud:8080: too many colons in address

**Expected Result**
Backup succeed, no errors, should be able to use whatever valid URL.

**Comment by GillesMocellin** [comment]
Reply to myself.

If I put in the endpoint : `my.server.dns:8080` without https://, it works !

**Comment by dmeniche** [comment]
work fine 4 me !!!!! thx a lot (y)
