### ISSUE TITLE
Support additional parameters for Azure AD login

### ISSUE THREAD

**Issue by jlact** [rancher/rancher#35674]
**Is your feature request related to a problem? Please describe.**
Better support for extra parameters when using Azure AD login would be useful to solve an issue involving multiple accounts. The issue we're currently experiencing occurs when you are logged in to a single Azure tenant which does not have access to Rancher. This results in an immediate error when clicking the "Login with Azure AD" on Rancher login screen. This is due to the default behaviour of the MS login to try and use the single account to login, it does not occur if you are already logged in to multiple accounts, as the default then is to prompt for account selection.

**Describe the solution you'd like**
AAD Login supports query parameters to change the behaviour of the login flow, in this instance a url parameter or "prompt" with value "select_account" will force the user to select an account even if only 1 account is currently logged in.

**Describe alternatives you've considered**
Attempted to add the query parameter to the auth url in the AAD auth config but it failed due to the way Rancher adds the additional parameters (client id, redirect etc...). It assumes there is no query string already present on the defined URL.

**Additional context**
relevant details for parameters https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#send-the-sign-in-request 
Related method (as best I can tell anyway) https://github.com/rancher/rancher/blob/46eb9d411b6afd0d75a323743adf5fddf4255219/pkg/auth/providers/azure/azure_provider.go#L523-L531

**Comment by jlact** [comment]
Still relevant

**Comment by sphr2k** [comment]
Relevant for us, too. We have external users logging into our Rancher instance. They use their own Azure AD account, as well as one from our AAD tenant. No way to select the right one, so they have to use incognito tabs or different browsers.

**Comment by sphr2k** [comment]
Please reopen.
