### ISSUE TITLE
Images from unused charts are in rancher-images.txt

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#35687]
**Rancher Server Setup**
- Rancher version:v2.6.0

**Describe the bug**

In the rancher-images.txt file, there are images from system-charts that are not available to use within Rancher.

Whatever is fixed should be fixed to evaluate what is needed for system-charts as well as charts (non-master branch) to only find images in valid helm charts based on Rancher min/max version. 

Example:

The original OPA gatekeeper chart uses rancher/opa-gatekeeper:v3.1.0-beta.7, but the max Rancher version of the chart is Rancher v2.4.99 as it was moved to the charts repo as of 2.5. 

The script to get the list of charts doesn't account what Rancher version is applicable. 

**To Reproduce**
 
1. Cut a RC of Rancher
2. Review list of images.txt

**Result**
rancher/opa-gatekeeper is in the list of images 

**Expected Result**

There shouldn't be rancher/opa-gatekeeper on the list as it's not a valid image to be used in charts. 

A way to test that it's fixed is to remove it from the list of images and confirm that OPA Gatekeeper can still be installed via the Apps and Marketplace view which is using the rancher/mirrored-opa-gatekeeper.

**Screenshots**

**Additional context**

Should be fixed with https://github.com/rancher/rancher/issues/33037, but that use case was to provide additional images if more than 1 version of a chart was applicable for a release

**Comment by ronhorton** [comment]
Is this rancher/opa-gatekeeper - or is it to validate that no files are present that shouldn't be? How can I get a list of entries that should NOT be present in rancher-images.txt?

**Comment by ronhorton** [comment]
**Pass** Verified in `v2.6.4-rc3`rancher/opa-gatekeeper not present in rancher-images.txt or rancher-images-source.txt

This also confirms [#33037 Update rancher-images generator to support feature and system charts min/max version constraint](https://github.com/rancher/rancher/issues/33037) passes
