### ISSUE TITLE
[windows 2022] SUC and rke2-coredns are down once windows node is added, user is unable to deploy new workloads

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35681]
**Rancher Server Setup**
- Rancher version: v2.6-head(4375161)
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:v1.21.6-rc2+rke2r2
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):custom (windows worker node)

**Describe the bug**

once the windows worker node is added and active, SUC (0.8.0) and rke2-coredns are down. User is unable to successfully deploy new workloads. 

**To Reproduce**
 
* deploy a custom node rke2 cluster in rancher using k8s v1.21.6-rc2+rke2r2 or above
* register 1 node all roles linux node
* register 1 worker windows node (version 2022)
* wait for the cluster to come to active state

**Result**
in pods of cluster, SUC and rke2-coredns are down
user is unable to successfully deploy windows deployments. 
windows node shows `unavailable` intermittently

**Screenshots**

<img width="1545" alt="Screen Shot 2021-11-29 at 2 49 33 PM" src="https://user-images.githubusercontent.com/16691014/143957898-ec6bb1d0-ce2c-4ad8-813b-510e6ed2df27.png">
<img width="1215" alt="Screen Shot 2021-11-29 at 2 41 37 PM" src="https://user-images.githubusercontent.com/16691014/143957905-76fb6154-fb49-479a-b233-b6b633ec054e.png">

**Additional context**

@phillipsj is aware of the issue

**Comment by dweomer** [comment]
It seems as if the `nodeAffinity`.`` are not honored at all for the SUC deployment pod to land on a windows node. Adding this snipped to the SUC deployment got it working correctly:

**Comment by rosskirkpat** [comment]
@dweomer Thanks for digging around to figure this out. Based on a known working Rancher chart (nginx), your findings match up - https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/templates/nginx-v0.48.1.go#L293-L304

It looks like this change needs made to the rke2-coredns chart in rancher/rke2-charts as well as SUC in rancher/charts.

**Comment by rosskirkpat** [comment]
I suspect that there are additional charts where this bug may be present (linux only charts that are missing the `nodeAffinity` params.

- https://github.com/rancher/rke2-charts/tree/main-source/packages/rke2-metrics-server
- https://github.com/rancher/rke2-charts/tree/main-source/packages/rke2-ingress-nginx

**Comment by brandond** [comment]
We're using `nodeSelector: kubernetes.io/os: linux`, not affinity as per https://github.com/rancher/rke2/issues/1665#issuecomment-902848599.

Would it be possible to get the output of:
* `kubectl get deployment -n kube-system rke2-coredns-rke2-coredns -o yaml`
* `kubectl get pod -n kube-system -l k8s-app=kube-dns -o yaml`
* `kubectl get configmap -n kube-system chart-values-rke2-coredns -o yaml`

**Comment by slickwarren** [comment]
[coredns.yaml](https://github.com/rancher/rancher/files/7627992/coredns.txt)
[kube-dns.yaml](https://github.com/rancher/rancher/files/7627994/kube-dns.txt)


kubectl get configmap -n kube-system chart-values-rke2-coredns -o yaml:

```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQwUrEMBCGX0Xm3K7bZEUNeNqLIN7E+ySZbmOTSUmmFVn23aWyBxFWPYbM98//zRFwCq9UasgMBpYOGhgDezCwz9yHwzNO0EAiQY+CYI6AzFlQQua6PrN9IyeVZFNC3jgUibQJ+TqsGQPF1LrMUnKMVKC5OJ7fmUp7WMYz9e1r6Zqrp8D+4ZFi2g9Y5M8cxkRgoIykWpcLea7/YuqEbgXH2VJbP6pQglMDrtCX8EtIVAXTBIbnGBuIaCn+eoYB6wAGekUKdWfvd6q/sdrqfofqVjtF3t8R6q3T2uttt247l3erabtgnKm2P0wudj19BgAA//9kf79k0QEAAA
    objectset.rio.cattle.io/id: helm-controller
    objectset.rio.cattle.io/owner-gvk: helm.cattle.io/v1, Kind=HelmChart
    objectset.rio.cattle.io/owner-name: rke2-coredns
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2021-11-29T19:52:56Z"
  labels:
    objectset.rio.cattle.io/hash: f2e2a31b942f5b3b3f4a273c2edd8ea30c33d301
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:objectset.rio.cattle.io/applied: {}
          f:objectset.rio.cattle.io/id: {}
          f:objectset.rio.cattle.io/owner-gvk: {}
          f:objectset.rio.cattle.io/owner-name: {}
          f:objectset.rio.cattle.io/owner-namespace: {}
        f:labels:
          .: {}
          f:objectset.rio.cattle.io/hash: {}
    manager: deploy@ip-172-31-43-238
    operation: Update
    time: "2021-11-29T19:52:56Z"
  name: chart-values-rke2-coredns
  namespace: kube-system
  resourceVersion: "391"
  uid: 3dcb1bc4-23fe-472f-8bb0-7d896de02a8d
```

**Comment by brandond** [comment]
I think what’s happening is that the coredns cluster autoscaler is setting the deployment `replicas=2` because there are two nodes in the cluster… but the windows agent node isn’t allowed by the OS nodeSelector, and the server node already has a replica on it and we’ve told the deployment not to run two CoreDNS pods on the same node via hostname anti-affinity. So one of the pods remains unscheduled.

While this might appear alarming, I don't think it's a problem. We might recommend disabling the coredns cluster autoscaler on Windows, as it will probably try to create more CoreDNS pods than there will be nodes to host them.

**Comment by phillipsj** [comment]
@slickwarren @dweomer @sirredbeard The SUC chart has been updated and tested to make sure it deploys as expected. 
![image](https://user-images.githubusercontent.com/1568133/144135957-3b4500f0-2f89-49f8-b79e-4ee8f581ca5e.png)

**Comment by sowmyav27** [comment]
On 2.6-head commit id: `5b56b17`

- SUC pod deploys on linux node only in a windows 2022 cluster`rancher/system-upgrade-controller:v0.8.0` on `v1.21.7+rke2r1`
- A coredns-rke2 pod is in `Pending` state - `0/2 nodes are available: 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) didn't match pod affinity/anti-affinity rules, 1 node(s) didn't match pod anti-affinity rules.`
