### ISSUE TITLE
Client-side throttling for kubectl requests for EKS cluster imported into Rancher

### ISSUE THREAD

**Issue by oxr463** [rancher/rancher#35685]
```
I0713 17:02:46.174551   90544 request.go:668] Waited for 1.117824102s due to client-side throttling, not priority and fairness, request: GET:https://rancher.local/k8s/clusters/c-12345/apis/rbac.authorization.k8s.io/v1?timeout=32s
```

**Comment by David-VTUK** [comment]
Can you show the output of the kubectl command with the verbose flag set? I've encountered this when kubectl can't write to .kube/cache

**Comment by oxr463** [comment]
[kubectl_verbose.txt](https://github.com/rancher/rancher/files/7651696/kubectl_verbose.txt)

**Comment by David-VTUK** [comment]
Try and Create/chown/chmod /Users/oxr463/.kube/cache as appropriate so you have write access

**Comment by oxr463** [comment]
> Try and Create/chown/chmod /Users/oxr463/.kube/cache as appropriate so you have write access

```
ls -la ~/
total 360
drwxr-xr-x+  39 oxr463  staff   1248 Dec  6 09:50 .
drwxr-xr-x    5 root     admin    160 Jan  1  2020 ..
-r--------    1 oxr463  staff      7 Jun 17 22:02 .CFUserTextEncoding
-rw-r--r--@   1 oxr463  staff  10244 Sep 13 19:35 .DS_Store
drwx------   40 oxr463  staff   1280 Dec  3 10:43 .Trash
drwx------    7 oxr463  staff    224 Dec  3 21:17 .kube
```

```
ls -la ~/.kube
total 40
drwx------   7 oxr463  staff   224 Dec  3 21:17 .
drwxr-xr-x+ 39 oxr463  staff  1248 Dec  6 09:50 ..
drw-------   4 oxr463  staff   128 Jun 25 16:48 cache
```

**Comment by David-VTUK** [comment]
What's the directory tree like in .kube/cache? Maybe there's a subfolder without the correct permissions.

**Comment by oxr463** [comment]
I deleted `.kube/cache` and the message went away. I'm also using `kubectx`, I wonder if that might have messed up my permissions.
