### ISSUE TITLE
Installing the same helm3 chart in the ember UI after its deleted is updating the existing migrated chart in the explorer UI 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35684]
Setup

Rancher version: 2.6-head 44b8030
Browser type & version: Chrome

**Describe the bug**
Deleting a migrated app from ember UI to explorer UI from the steps mentioned in this [issue](https://github.com/rancher/rancher/issues/34701) is deleting the app from ember UI which will not delete the chart from explorer UI. If we re-install the same app but with a different version, the chart in the explore UI is updated with this version thats installed on ember UI. 

**To Reproduce**
1. Create an rke1 node driver cluster 3 nodes 1 role each
2. From ember UI, install the `aws-event-sources` app in the default project version `v0.1.2`
3. Add the annotations to the app by executing into kubectl shell from spec.chart.metadata.annotations
```
catalog.cattle.io/ui-source-repo: helm3-library
catalog.cattle.io/ui-source-repo-type: cluster
apps.cattle.io/migrated: "true"
```
4. From apps&market --> repositories --> add the repo name: helm3-library | URL: https://git.rancher.io/helm3-charts | Branch: master
5. From the local cluster exec into the kubectl shell and add the annotation `kubectl edit apps.project.cattle.io aws-event-sources -n <ProjectIDAppInstalled>` , add the annotation cattle.io/skipUninstall: "true" under metadata.annotations
6. Delete the aws-event-sources from the downstream cluster --> default project
7. From the ember UI, install the same helm3 chart again but set the version `v0.1.4` in the default project.

**Result**
From explorer UI, the new app is not seen created and the existing app version is updated to v0.1.4

**Expected Result**
Expected it to create a new app under Installed apps from apps & market place and not update the existing app.

**Additional context**
Related : https://github.com/rancher/dashboard/issues/4402

**Comment by deniseschannon** [comment]
I'm not sure why this issue is stuck with the note that it's being transferred, but considering the PR is merged, I'll move it to test.

@anupama2501 I believe this should unblock you from several other issues.

**Comment by anupama2501** [comment]
Verified on v2.6-head ac67f83

1. On 2.5.11, created a downstream cluster with 3 worker, 1etcd +cp - c1
2. Installed aws-event sources in the default project of c1 
3. Upgraded the rancher server to v2.6-head ac67f83
4. Added the annotation for the app 
```
catalog.cattle.io/ui-source-repo: helm3-library
catalog.cattle.io/ui-source-repo-type: cluster
apps.cattle.io/migrated: "true"
```
5. Added a chart repository from apps & market --> repositories --> name: `helm3-library`, url: `https://git.rancher.io/helm3-charts`, branch: `master`
6. Add the annotation `cattle.io/skipUninstall: "true"` from kubectl edit apps.project.cattle.io aws-event-sources -n <ProjectIDAppInstalled>
7. Delete this app from ember UI and verified its present in the apps & market --> installed apps.
8. Install a new aws-event from the ember UI and verified the following error is thrown 
```
an apps.catalog.cattle.io already exists with ID [aws-event-sources] in namespace [aws-event-sources]
```
9. A new app is installed when we changed the name and the existing app is not updated.
