### ISSUE TITLE
Old Catalog API needs to be updated so versionLinks returns the version of the app that is currently installed

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#35680]
**Rancher Server Setup**
- Rancher version: v2.6.3 -rc

**Describe the bug**

When a catalog has been maxed out so it's no longer available in any Rancher version, there are issues throughout the UI that relies on the versionLinks API to return what versions the app can be deployed. 

This is fine and expected for fresh installs of Rancher or when we want to figure out which app is eligible to deploy. 

The downside is that when a user has come from an upgraded Rancher setup and already had an app deployed, that version should always be available to continue "upgrading". Currently, there are a various UI errors occurring as the current versionLinks for that app returns no available version.

The proper fix is to have versionLinks return the version of the app if it's currently deployed as a viable upgrade option. 

**To Reproduce**
 
1. Launch 2.5.11
2. Deploy an app from the Cluster Manager UI -> Using the Apps tab within a Project view
3. Upgrade Rancher to 2.6.3-rc2. Note: The legacy feature flag should automatically be enabled
4. Navigate to the Cluster view and inside Legacy section, there is an Apps section.
5. Try to upgrade the existing app 

Note: There are UI issues filed, but this is ultimately an API issue
https://github.com/rancher/dashboard/issues/4628
https://github.com/rancher/dashboard/issues/4627
https://github.com/rancher/dashboard/issues/4655

**Result**

Unable to properly upgrade to the same version of the chart

**Expected Result**

Ability to continue updating to the original version of a deployed charts regardless of min/max version on the chart

**Screenshots**

**Additional context**

In 2.6.3, we are aiming to max out all charts in the old catalogs (library and helm3-library) as most of these are not tested and will not be valid in k8s 1.22. Also, we are moving to new apps&marketplace experience and want to stop allowing people to install charts through Rancher in this method. 

Note: Longhorn doesn't have a max version on it's chart yet which is why it still works.

**Comment by anupama2501** [comment]
Verified on rancher v2.6-head 2a7857d upgraded from 2.5.11
1. Created a downstream linode RKE1 on 2.5.11 with 3 worker,1 etcd and 1 cp
2. From the default project --> installed the apps `docker-registry`,`redis`, `mongodb-replicaset`
Update apps
1. Updated the app by modifying the password of the redis app
2. Verified the update went through without any errors

Upgrade apps
1. Upgraded the version of docker-registry to version `1.9.2` 
2. Verified upgrade went through without any errors.

Uninstall apps
1. Uninstalled the apps `mongodb-replicaset` without upgrade --> successful
2. Uninstalled the app docker-registry post upgrade --> successful

**Comment by anupama2501** [comment]
On 2.6.3-rc5 I'm not able to upgrade any apps:
1. Installed rancher on 2.6.2 with a downstream rke1 node driver 3 worker, 1 etcd and 1 cp
2. Enable the legacy flag
3.  install the charts `docker-registry`, `redis`, `mongodb-replicaset`, `aws-event-sources` in the default project from legacy --> project --> apps
3. Upgrade rancher server to v2.6.3-rc5
4. Navigate to legacy --> project --> select default project in the namespace picker
5. Upgrade the apps

Result:
Page reloads and the apps won't upgrade. Following is the response for the app `aws-event-sources`
Similar to https://github.com/rancher/dashboard/issues/4655

**Comment by anupama2501** [comment]
Closing this issue as the issue seems to be with the UI and will be tracked at https://github.com/rancher/dashboard/issues/4774.

**Comment by anupama2501** [comment]
Re-opening this issue as from @catherineluse's PR https://github.com/rancher/ui/pull/4791, upgrading the apps, post rancher upgrade is not working.

**Comment by catherineluse** [comment]
The UI part of this problem is fixed in https://github.com/rancher/ui/pull/4791, as the upgrade form renders now. The UI uses the `currentVersion` parameter when calling the backend, and the `versionLinks` are no longer empty.

However, when the form is submitted, the error occurs:

```
Validation failed in API: rancher max version exceeded
```

In order to be upgraded, a back end change will be needed to allow upgrades when the version doesn't change, even if the current version exceeds the max version. https://suse.slack.com/archives/C02AXMUQ4A1/p1639674558256500?thread_ts=1639642155.249400&cid=C02AXMUQ4A1

**Comment by anupama2501** [comment]
Closing this issue as its being addressed in the above linked ticket
