### ISSUE TITLE
Adding support for ingressClassName in Helm installer's Values file

### ISSUE THREAD

**Issue by kylep** [rancher/rancher#35694]
**Is your feature request related to a problem? Please describe.**

When Rancher is installed using the Helm method as documented in the [install guide](https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/), the Ingress resource it creates has no `ingressClassName` value in its spec. 

Without this value in the Ingress, if you installed a fresh cluster with `kubeadm` then add the Nginx ingress (`helm install nginx-ingress  nginx-stable/nginx-ingress`), the Rancher page cannot be accessed. Navigating to the Ingress URL returns an HTTP 404 response. The Ingress resource starts working only after injecting the ingressClassName value.

**Describe the solution you'd like**
I'd like to submit a PR that adds a jinja2 section to `ingress.yaml` where if `.Values.ingressClassName` is set in `values.yaml`, `ingressClassName: {{ .Values.ingressClassName }}` will be set inside the `spec:` section. This will provide users with a mechanism to define which Ingress class they would like Rancher to use. This would also be useful when multiple Ingress classes exist so that users could choose between them.

**Describe alternatives you've considered**
The obvious alternative is to patch that value into the Ingress after installing with Helm, but the value will likely get removed by Helm later.

**Additional context**
This issue was discussed and the solution was largely provided by /u/Odonay on this Reddit thread. https://www.reddit.com/r/rancher/comments/qw9nho/is_the_helm_installer_broken/hm6tqm4/ 
I've verified the fix and look forward to opening a PR.

**Comment by zkl94** [comment]
Can we have a follow-up on this issue? Rancher seems like the only helm chart I am using that still lacks support for ingressClassName.
