### ISSUE TITLE
Containers can't resolve names

### ISSUE THREAD

**Issue by sweigert** [rancher/rancher#3569]
Hi,

I want to deploy a fairly small stack: 3 containers - A,B,C. B and C are linked to A, so A is started first, then B and then C.

The issue is: While B can resolve A, C cannot.
`Output: 2/9/2016 3:51:09 PM[nsqadmin] 2016/02/09 14:51:09.394227 FATAL: failed to resolve --lookupd-http-address address (nsqlookupd:4161) - lookup nsqlookupd on xx.xx.xx.xx:53: no such host
2/9/2016 3:51:35 PM[nsqadmin] 2016/02/09 14:51:35.221974 FATAL: failed to resolve --lookupd-http-address address (nsqlookupd:4161) - lookup nsqlookupd on xx.xx.xx.xx:53: no such host`
(I anonymized the IP addresses)

I am attaching a sample docker-compose.yml with an NSQ stack that will hopefully allow you to reproduce the issue.

```
nsqlookupd:
  image: nsqio/nsq
  command: ["nsqlookupd",
            "-http-address=0.0.0.0:4161",
            "-tcp-address=0.0.0.0:4160"]
nsqd:
  image: nsqio/nsq
  ports:
    - "4150:4150"
    - "4151:4151"
  links:
    - nsqlookupd:nsqlookupd
  command: ["nsqd",
            "-data-path=/data",
            "-http-address=0.0.0.0:4151",
            "-tcp-address=0.0.0.0:4150",
            "-lookupd-tcp-address=nsqlookupd:4160"]
nsqadmin:
  image: nsqio/nsq
  ports:
    - "4171:4171"
  links:
    - nsqlookupd:nsqlookupd
  command: ["nsqadmin",
            "-http-address=0.0.0.0:4171",
            "-lookupd-http-address=nsqlookupd:4161"]

```

FYI: I have been able to deploy the very same stack on docker-swarm but I would like to use rancher instead.

Thank you very much,
Stefan

**Comment by deniseschannon** [comment]
I used your docker-compose.yml. The containers are able to communicate with each other using their internal DNS as I'm able to exec into each container from service B and service C and ping the `nsdlookupd` container (service A). 

But when I click on the exposed ports, it doesn't get re-directed as expected.

**Comment by alena1108** [comment]
We should be able to resolve containers by:

containerName.serviceName.stackName.rancher.interinal

@sangeethah can you please test this use case as a part of cross stack dns resolution testing?

**Comment by sangeethah** [comment]
Tested with latest build from master:

Create the stack provide in the bug.

From containers in service - "nsqd" and "nsqadmin" , able to ping containers in nsqlookupd using containerName.serviceName.stackName.rancher.interinal format:

<img width="823" alt="screen shot 2016-03-09 at 1 33 42 pm" src="https://cloud.githubusercontent.com/assets/4266958/13651362/e7b4bbac-e5fb-11e5-913d-5c1d7012e8f6.png">
<img width="903" alt="screen shot 2016-03-09 at 1 33 37 pm" src="https://cloud.githubusercontent.com/assets/4266958/13651363/e7b5dab4-e5fb-11e5-97fa-50d31b6d4916.png">

**Comment by sangeethah** [comment]
Also able to resolve by servicename , nsqlookupd from containers in service - "nsqd" and "nsqadmin" .

<img width="899" alt="screen shot 2016-03-09 at 1 47 31 pm" src="https://cloud.githubusercontent.com/assets/4266958/13651767/a8ea75e0-e5fd-11e5-9cc1-c329fa29c080.png">
<img width="916" alt="screen shot 2016-03-09 at 1 46 58 pm" src="https://cloud.githubusercontent.com/assets/4266958/13651768/a8ecd146-e5fd-11e5-94c1-6ddaa8618b75.png">

**Comment by sangeethah** [comment]
@sweigert , this issue will be addressed in the next release.
