### ISSUE TITLE
Error while applying agent YAML on cluster creation / user impersonation unauthorized

### ISSUE THREAD

**Issue by alexfdezsauco** [rancher/rancher#35693]
**Rancher Server Setup**
- Rancher version: 2.6
- Installation option (Docker install/Helm Chart): Docker install

**Describe the bug**

Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user u-rj66ntqtc6: Unauthorized") has prevented the request from succeeding

**To Reproduce**

1) $ sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:latest
2) Create a cluster in the same computer, with all roles.

**Result**

Got this error  => "Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user u-rj66ntqtc6: Unauthorized") has prevented the request from succeeding"

**Expected Result**

A successful cluster creation.

**Screenshots**

![image](https://user-images.githubusercontent.com/1785664/144105665-3ec4d676-21ef-4487-ab94-34c5a8f31083.png)

**Comment by ShadowRa88it** [comment]
I'm experiencing this as well any solution?

**Comment by seyong-um** [comment]
I am facing this too

**Comment by Homicevich** [comment]
i have same error, anyone can help ?

**Comment by liqinz** [comment]
check the cattle agent config, maybe it can't connect to the server

**Comment by ke4nec** [comment]
check the config of cattle agent on node, maybe it can not connect to the rancher server.

**Comment by eduardoscheidet** [comment]
Hello, I have the same error when i'll going to deploy a new cluster with kubernetes version v1.22.9-rke2r2
`Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user u-espjzfycet: Post \"https://10.43.0.1:443/api/v1/namespaces\": x509: certificate signed by unknown authority") has prevented the request from succeeding`

**Comment by Brianalmeida** [comment]
I'm seeing this too. I will add the reproduce steps below:

## Environment for downstream cluster:
- Rancher Version: v2.6.6
- Kubernetes version: v1.23.7
- RKE, RKE2, or K3s: RKE
- OS: SLES 15 SP4 
- Authentication: ADFS & Local 
- Roles: All three roles
- On-prem nodes

## Creating an RKE cluster in the Rancher UI:

1. Install a fresh SLES 15 SP4 image onto a VM
2. Install Docker on the node
3. Go into the Rancher UI, create a custom RKE cluster
4. Select defaults
5. Add all three roles, then copy the command to initialize the provisioning process on the node
6. Wait till provisioning has ended
7. The cluster gets stuck "waiting for Kubernetes."
8. Then the error pops up
> Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user u-teykoivpq5: Unauthorized") has prevented the request from succeeding

**Comment by cbron** [comment]
Does this only happen on Rancher docker installs or also HA ? 

Haven't tested, but this may be solved in 2.6.7 by: https://github.com/rancher/rancher/issues/37733

**Comment by samjustus** [comment]
@brudnak when you get a chance if you could see if this is in fact fixed? repro steps are solid

**Comment by Brianalmeida** [comment]
After sanitizing the node, disabling the OS firewall, and disabling swap memory, the cluster was able to provision successfully.
