### ISSUE TITLE
When rke2 feature flag is disabled, upgrade to 2.6-head ruins downstream rke2 cluster

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#35696]
**Rancher Server Setup**
- Rancher version: `2.6-head Commit ID 4375161`
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE2 - DO - v1.21.6+rke2r1`

- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.21.6+rke2r1`
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? `Downstream RKE2 Digital Ocean cluster`

**Describe the bug**
Created an rke2 cluster in 2.6.2 and deactivate the rke2 feature flag. Upgraded to 2.6-head, rke2 feature flag was set to active, but the downstream cluster goes to an error state. 

**To Reproduce**
1. Create a downstream rke2 cluster in `2.6.2`
2. click `Hamburger menu > global settings > feature flags`
3. Disable rke2 feature flag
4. upgrade to 2.6-head

**Result**
The rke2 feature flag is changed to `active` and locked (ie, cannot disable); the rke2 cluster is in an error state and cannot be recovered. 
**Expected Result**
Rke2 feature flag is set to active and the downstream cluster is active and available. 

**Screenshots**
<img width="969" alt="Screen Shot 2021-11-30 at 12 39 10 PM" src="https://user-images.githubusercontent.com/89212856/144111403-2a352b83-3ae8-4ef1-93ed-c9c55985452c.png">
<img width="1013" alt="Screen Shot 2021-11-30 at 12 38 49 PM" src="https://user-images.githubusercontent.com/89212856/144111416-26f8fde5-3a8c-441d-9a62-2711de1ae274.png">
<img width="1020" alt="Screen Shot 2021-11-30 at 12 50 04 PM" src="https://user-images.githubusercontent.com/89212856/144111594-ec861004-777d-44a8-9ee1-51a9613bf120.png">

**Comment by thedadams** [comment]
@ronhorton Does this eventually rectify itself? The webhook being unavailable is something we have seen before.

**Comment by thedadams** [comment]
I am unable to reproduce this. I tested this with a local dev setup going from v2.6.2 -> 2.6.3-rc3. I also tested this with HA Rancher installed via helm on a K3S cluster. In both cases I:
1. Provisioned a cluster in Digital Ocean and wait for it to become active.
2. Turned the RKE2 feature flag off (in the HA case I waited for the Rancher deployment to rollout again)
3. Upgraded Rancher to v2.6.3-rc3 and waited for Rancher to become active again
The provisioned cluster was active with no error.

<img width="1540" alt="Screen Shot 2021-12-01 at 11 51 46 AM" src="https://user-images.githubusercontent.com/3682717/144295687-4c909d92-4919-470b-a969-dffb4f1efc23.png">

**Comment by ronhorton** [comment]
**I reproduced it following the same steps with 2.6.3-rc3**

1. Create a downstream rke2 cluster in `2.6.2`
2. click `Hamburger menu > global settings > feature flags`
3. Disable rke2 feature flag
4. upgrade to `2.6.3-rc3`

![Screen Shot 2021-12-02 at 7.54.00 AM.png](https://zube.io/files/rancher/1cdbe8317a9ba9a8446cb2f248fee3d5-screen-shot-2021-12-02-at-7-54-00-am.png)

**Comment by thedadams** [comment]
This is not related to the RKE2 feature flag. This is because the k3s cluster that is created in the Docker container is v1.22.3+k3s1. The webhook crashes on startup because `v1beta` of the CustomResourceDefition is not available. The webhook must be updated to support Kubernets 1.22+.

**Comment by ronhorton** [comment]
**PASS** Verified fixed in `2.6-head Commit ID 9295d4f`

1. Created downstream rke2 cluster in 2.6.2 with k8s v1.21.6+rke2r1
2. Upgraded rancher to 2.6-head
3. Cluster updates successfully and is active
<img width="1245" alt="Screen Shot 2021-12-09 at 3 53 08 PM" src="https://user-images.githubusercontent.com/89212856/145473994-26eda728-7fd5-41c1-8c3a-3429b50a3e87.png">

1. Created downstream rke2 clutser in 2.6.2 with k8s v1.21.6+rke2r1
2. Upgraded rancher to 2.6.3-rc4
3. Cluster Errors as reported
