### ISSUE TITLE
Allow upgrading apps even if Rancher version exceeds `rancher_max_version`

### ISSUE THREAD

**Issue by catherineluse** [rancher/rancher#35692]
This is a follow-up to https://github.com/rancher/rancher/issues/35352

The use case that needs to be supported is:

- You enable the legacy feature flag in Rancher v2.6.2
- You install a legacy multi-cluster app where the app's `rancher_max_version` is also v2.6.2
- You upgrade Rancher to v2.6.3
- If you go to the legacy multi-cluster app page and click upgrade, you should be able to upgrade things like the description even if you can't change the app version

There is an open PR https://github.com/rancher/ui/pull/4783 that makes the upgrade form available, but if you try to upgrade the multi-cluster app in this case, you get the error `Validation failed in API: Rancher max version exceeded`.

<img width="1243" alt="Screen Shot 2021-11-25 at 8 38 22 PM" src="https://user-images.githubusercontent.com/20599230/144105261-7caa6319-61c6-41be-a4e7-dff5535866d9.png">

**Comment by Jono-SUSE-Rancher** [comment]
Seems similar (but not identical) to https://github.com/rancher/rancher/issues/35658

**Comment by catherineluse** [comment]
Closing as a duplicate of https://github.com/rancher/rancher/issues/35680
