### ISSUE TITLE
Add SLE BCI image for cis-operator

### ISSUE THREAD

**Issue by doflamingo721** [rancher/rancher#35706]
Add SLE BCI as base image in Dockerfile in CIS-Operator (https://github.com/rancher/cis-operator)

**Comment by doflamingo721** [comment]
How to Validate:

1. Rancher Server Version : v2.6.3
2. Create 3 downstream single node clusters of type rke1, rke2 and k3s each.
3. Install rancher-cis-benchmark chart on each cluster.
4. Run below tests for rke1, rke2  and k3s  with respective profile and you should get the following results.

    - RKE1 `rke-profile-permissive-1.6 `: Passed
    - RKE2 `rke2-cis-1.6-profile-permissive` : Passed
    - k3s `k3s-cis-1.6-profile-permissive` : Failed

> NOTE: The scan on k3s cluster also failed using rancher/cis-operator:v1.0.6 with same number of passed/failed test results.

**Comment by vivek-infracloud** [comment]
### Validated this issue on rancher v2.6.3

**Downstream cluster details: All were AWS node driver cluster with (3 nodes 1cp, 1w, 1etcd)**

- RKE1 - v1.21.8
- RKE2 - v1.21.7+rke2r2
- K3s - v1.21.7+k3s1

**Validation Steps followed**

1. Rancher Server Version : v2.6.3
2. Create 3 downstream single node clusters of type rke1, rke2 and k3s each.
3. Install rancher-cis-benchmark chart on each cluster.
4. Run below tests for rke1, rke2 and k3s with respective profile and got the following results.

- RKE1 `rke-profile-permissive-1.6` : Passed
- RKE2 `rke2-cis-1.6-profile-permissive` : Passed
- k3s `k3s-cis-1.6-profile-permissive` : Passed

Results:

- Chart installed successfully, and CIS-Benchmark test passed for all the profiles for both the charts (upstream - `rancher/cis-operator:v1.0.6` and local image - `doflamingo721/cis-operator:1.0.7`).

**Comment by vivek-infracloud** [comment]
Validated on rancher v2.6.3

Steps followed.
Made sure that the security-scan image version used for the scans is v0.2.4

1. Created 3 downstream single node clusters of type rke1, rke2 and k3s each.
2. Install rancher-cis-benchmark chart on each cluster.
3. Run scans for rke1, rke2 and k3s with respective profile. Got the following results.

- RKE1 `rke-profile-permissive-1.6 `: Passed
- RKE2 `rke2-cis-1.6-profile-permissive` : Passed
- k3s `k3s-cis-1.6-profile-permissive` : Failed

4. Updated the cis-operator image that has cle bci as base image. Got the same results as above.

Validation passed.

**Comment by vivek-infracloud** [comment]
Closing the issue based on above validation.
