### ISSUE TITLE
Update hyperkube base to using iptables >1.8.5

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#35709]
Currently Rancher's hyperkube-base is using Ubuntu 20.04 (https://github.com/rancher/hyperkube-base/blob/2fad0cab4ec1801f91ac2842ad453849690380c6/Dockerfile#L1), which is still using iptables 1.8.4.

This makes kube-proxy / kubelet susceptible to the same issues noted in https://github.com/flannel-io/flannel/issues/1408, where iptables can experience a segfault; if this happens to happen right when the iptables-wrapper script (executed in https://github.com/rancher/hyperkube-base/blob/2fad0cab4ec1801f91ac2842ad453849690380c6/Dockerfile#L76) is trying to calculate `num_nft_lines` (https://github.com/kubernetes-sigs/iptables-wrappers/blob/9e6ce59c864623ea71a6f7d59c35fcb13a919b87/iptables-wrapper-installer.sh#L116), this can result in kube-proxy / kubelet configuring rules using the legacy packet filter, which will break setting up networking on hosts that do not include the legacy packet filter (e.g. CentOS 8 nodes).

To resolve this, we need to update the base image to a version that includes iptables >1.8.5 and ensure that we no longer see the segfaults noted in https://github.com/rancher/rancher/issues/34604#issuecomment-983906269.

**Comment by leodotcloud** [comment]
Looks like the next LTS version of Ubuntu is out: `ubuntu:22.04`

**Comment by snasovich** [comment]
@leodotcloud, `ubuntu:22.04` tag is indeed available and has iptables 1.8.7.
However, per https://wiki.ubuntu.com/Releases it doesn't look like 22.04 will be officially out till 4/21/2022, so I don't think we can actually use this image.

**Comment by leodotcloud** [comment]
Thanks for the info @snasovich, I did not realize that the actual release is not out yet. Not sure if we will be able to pull in a higher version of iptables in 20.04 itself. There might be a dependency hell to deal with.

**Comment by snasovich** [comment]
Yes, looking into what options we have here.

**Comment by snasovich** [comment]
@samkulkarni20 , could you please have your team take care of this?
The updated version of iptables is available in `ubuntu:21.10`. Sdly it's not in `ubuntu:20.04` (LTS) and `ubuntu:22.04` (which is also LTS) is not yet released.

So the way I see the process:
* Update ubuntu to 21.10 in https://github.com/rancher/hyperkube-base, tag new version of this base image.
* Update base image in all active minor k8s version branches for https://github.com/rancher/hyperkube. Then tag these. I guess they will be like v1.22.5-rancher2 (if we have v1.22.5-rancher1 already).
* Then add new releases in KDM that will be like v1.22.5-rancher2-1 and use these new hyperkube images there for kubernetes image (as usual, in v2.6 we need 1.20 - 1.22 and in v2.5 we need 1.20 only).

I can help with tagging as you/your team members probably don't have permissions.

https://github.com/rancher/rancher/issues/36021 is for 2.5.

**Comment by samkulkarni20** [comment]
Sure @snasovich.

**Comment by rayandas** [comment]
@snasovich The PRs are up. hyperkube-base new tag should be `0.0.8`. Also hyperkube 1.20-1.22 should be tagged after it get's merged. Then CI for KDM PR should pass and it can be merged. I added reviewers to all those PRs. 

cc: @samkulkarni20

**Comment by snasovich** [comment]
New versions (`v1.20.14-rancher2-1`, `v1.21.8-rancher2-1` and `v1.22.5-rancher2-1`) have been added in `dev-v2.6` KDM branch that now use iptables v1.8.7 which should address the issue.

### Root cause
`ubuntu:20.02` has iptables v1.8.4 which makes `hyperkube-base` base image susceptible to the same issue noted in https://github.com/flannel-io/flannel/issues/1408.

### What was fixed, or what changes have occurred
`hyperkube-base` image is not built based on `ubuntu:21.10` which has iptables v1.8.7.
 
### Areas or cases that should be tested
Provisioning/upgrading downstream clusters with/to these newly introduced versions; anything network-related on these clusters
 
### What areas could experience regressions?
Same as above
 
### Are the repro steps accurate/minimal?
Repro steps listed here: https://github.com/rancher/rancher/issues/34604#issuecomment-983906269

**Comment by rishabhmsra** [comment]
**Fresh Install Validation** - Pass

- Rancher version: v2.5-head(5f414ff)
- Docker install

**Downstream Cluster info**

- Custom cluster
- 8 nodes: 3 worker, 3 etcd, 2 control plane
- ec2 instances: `rhel-8.4-docker-20.10.7-selinux-on-rpm`
- k8s: `v1.20.14-rancher2-1, v1.21.8-rancher2-1 and v1.22.5-rancher2-1`

**Validation Steps**

- Within the custom cluster deploy a workload in the default namespace.
- From explorer --> pods --> in the kube-system namespace --> Execute shell in one of the Canal pods.
- Change the container to kube-flannel, and run the dmesg command.

**Result**
Checked the dmesg logs in the canal pod and there are no segfaults/issues with the ip-tables. 

----------------------------------------------------------------------------------------------------------------------------------------------------------------

**Upgrade Validations** - Seeing the segfault error

- Rancher version: v2.5-head(5f414ff)
- Docker install

Steps:
- KDM pointing to release-v2.6
- Provisioned  `v1.22.5-rancher1-1, v1.21.8-rancher1-1 and v1.20.14-rancher1-1` downstream custom cluster using -> ec2 instances: `rhel-8.4-docker-20.10.7-selinux-on-rpm` 3 nodes (1-cp, 1-w, 1-etcd)
- Deployed workload in default ns.
- Changed the KDM to dev-v2.6
- Updated the k8s to `v1.22.5-rancher2-1, v1.21.8-rancher2-1 and v1.20.14-rancher2-1`. Upgrade was successfull.
- From explorer --> pods --> in the kube-system namespace --> Execute shell in one of the Canal pods.
- Change the container to kube-flannel, and run the dmesg command.

**Result**
Although the cluster upgrade was successfull the dmesg logs shows similar error:
```
[  536.943936] ip6tables[7105]: segfault at 80 ip 00007f04e672f964 sp 00007ffd8f273348 error 4 in libnftnl.so.11.2.0[7f04e672a000+19000]
```

**Comment by sowmyav27** [comment]
Reopening since the segfault error is seen on an upgrade.

**Comment by sowmyav27** [comment]
This was validated on 2.6.3 with KDM pointing to dev-v2.6
```
On fresh install -> Segfault not occurring.
After upgrading k8s version the segfault error is coming from libnftnl.so.11.2.0 version and on checking kube-flannel and  hyperkube containers, libnftnl version was different, so segfault error is probably coming from some where else
```
@rishabhmsra 's comments.

**Comment by rajha-korithrien** [comment]
@sowmyav27 Is the kube-flannel pod unchanged from the upgrade process? Is that pod still using libnftnl.so.11.2.0?

**Comment by samkulkarni20** [comment]
@rajha-korithrien There was no change done to kube-flannel pod/image.

**Comment by rishabhmsra** [comment]
**Fresh Install checks :**
-
**Rancher Server :**
- Rancher version: v2.6.3
- Docker install

**Downstream Cluster info**
- Custom cluster
- 3 nodes: 1 worker, 1 etcd, 1 control plane
- ec2 instances: `rhel-8.4-docker-20.10.7-selinux-on-rpm`
- k8s: `v1.20.14-rancher2-1`

**Validation Steps :**
- Within the custom cluster deploy a workload in the default namespace.
- From explorer --> pods --> in the kube-system namespace --> Execute shell in one of the Canal pods.
- Change the container to kube-flannel, and run the dmesg command.

**Result :**
Checked the dmesg logs in the canal pod and there are no segfault errors.

------------------------------------------------------------------------------------------------------------------------------------------------
Upgrade Checks :
-
**Rancher Server :**
- Rancher version: v2.6.3
- Docker install

**Validation Steps:**
- KDM pointing to release-v2.6
- Provisioned k8s `v1.20.14-rancher1-1` downstream custom cluster using -> ec2 instances: `rhel-8.4-docker-20.10.7-selinux-on-rpm`  `3 nodes (1-cp, 1-w, 1-etcd)`
- Deployed workload in default ns.
- Changed the KDM to `dev-v2.6-v1.20.14-0122` branch.
- Upgrade cluster from `k8s v1.20.14-rancher1-1` to `k8s v1.20.14-rancher2-1`
- From explorer --> pods --> in the kube-system namespace --> Execute shell in one of the Canal pods.
- Change the container to kube-flannel, and run the dmesg command.

**Result :**
- The segfault error coming from libnftnl.so.11.2.0:
```
bash-5.1# dmesg|grep -i iptables
[  572.585171] iptables[6077]: segfault at 80 ip 00007f39c5c01964 sp 00007ffd8eb04a58 error 4 in libnftnl.so.11.2.0[7f39c5bfc000+19000]
[  617.706325] iptables-save[7048]: segfault at 80 ip 00007f36a6ce9964 sp 00007ffe096098d8 error 4 in libnftnl.so.11.2.0[7f36a6ce4000+19000]
```
- However, on checking the version of libnftnl installed on the kube-flannel container, I saw that the version installed was libnftnl.so.11.4.0, which seems to indicate the segfault is not coming from Flannel:
```
bash-5.1# ls /usr/lib | grep "libnftnl"
libnftnl.so.11
libnftnl.so.11.4.0
```
- Also, I checked the libnftnl version on hyperkube container and there also the the libnftnl version is different :
```
$ docker run -it --entrypoint /bin/bash rancher/hyperkube:v1.20.14-rancher2
root@7c9928e954c7:/# ls /lib/x86_64-linux-gnu | grep "libnftnl"
libnftnl.so.11
libnftnl.so.11.5.0
```

**Comment by rishabhmsra** [comment]
**Fresh Install checks :**
-
**Rancher Server :**
- Rancher version: v2.6.3
- Docker install

**Downstream Cluster info**
- Custom cluster
- 3 nodes: 1 worker, 1 etcd, 1 control plane
- ec2 instances: `rhel-8.4-docker-20.10.7-selinux-on-rpm`
- k8s: `v1.20.14-rancher2-1`

**Validation Steps :**
- Within the custom cluster deploy a workload in the default namespace.
- From explorer --> pods --> in the kube-system namespace --> Execute shell in one of the Canal pods.
- Change the container to kube-flannel, and run the dmesg command.

**Result :**
Checked the dmesg logs in the canal pod and there are no segfault errors.

------------------------------------------------------------------------------------------------------------------------------------------------
Upgrade Checks :
-
**Rancher Server :**
- Rancher version: v2.6.3
- Docker install

**Validation Steps:**
- KDM pointing to release-v2.6
- Provisioned k8s `v1.20.14-rancher1-1` downstream custom cluster using -> ec2 instances: `rhel-8.4-docker-20.10.7-selinux-on-rpm`  `3 nodes (1-cp, 1-w, 1-etcd)`
- Deployed workload in default ns.
- Changed the KDM to `dev-v2.6-v1.20.14-0122` branch.
- Upgrade cluster from `k8s v1.20.14-rancher1-1` to `k8s v1.20.14-rancher2-1`
- From explorer --> pods --> in the kube-system namespace --> Execute shell in one of the Canal pods.
- Change the container to kube-flannel, and run the dmesg command.

**Result :**
- The segfault error coming from libnftnl.so.11.2.0:
```
bash-5.1# dmesg|grep -i iptables
[  572.585171] iptables[6077]: segfault at 80 ip 00007f39c5c01964 sp 00007ffd8eb04a58 error 4 in libnftnl.so.11.2.0[7f39c5bfc000+19000]
[  617.706325] iptables-save[7048]: segfault at 80 ip 00007f36a6ce9964 sp 00007ffe096098d8 error 4 in libnftnl.so.11.2.0[7f36a6ce4000+19000]
```
- However, on checking the version of libnftnl installed on the kube-flannel container, I saw that the version installed was libnftnl.so.11.4.0, which seems to indicate the segfault is not coming from Flannel:
```
bash-5.1# ls /usr/lib | grep "libnftnl"
libnftnl.so.11
libnftnl.so.11.4.0
```
- Also, I checked the libnftnl version on hyperkube container and there also the the libnftnl version is different :
```
$ docker run -it --entrypoint /bin/bash rancher/hyperkube:v1.20.14-rancher2
root@7c9928e954c7:/# ls /lib/x86_64-linux-gnu | grep "libnftnl"
libnftnl.so.11
libnftnl.so.11.5.0
```

**Comment by sowmyav27** [comment]
**On 2.6.3 with KDM pointing to `dev-v2.6-v1.20.14-0122`**
On an upgraded cluster 1.20.14 o 1.21..8 Segfault error is seen. But the issue is not because of hyperkube image or the flannel pod. since the versions are:

```
docker run -it --entrypoint /bin/bash rancher/hyperkube:v1.21.8-rancher2
root@61647d5ae1fe:/# ls /lib/x86_64-linux-gnu | grep "libnftnl"
libnftnl.so.11
libnftnl.so.11.5.0
```
and flannel pod
```
ls /usr/lib | grep "libnftnl"
libnftnl.so.11
libnftnl.so.11.4.0
```

**Comment by Auston-Ivison-Suse** [comment]
**Release Check**
Rancher version: 2.6.3
Helm install

**Fresh Install** = Pass
**Upgrade Test** = Pass*

**Fresh Install Steps**
1. Provision clusters using the rhel-8.4-docker-20.10.7-selinux-on-rpm ami while the KDM is pointed to `dev-v2.6-v1.20.14-0122` and selecting the k8s versions as: `v1.21.8-rancher2-1` and `v1.22.5-rancher2-1`
2. Then follow the rest of the steps in the comment [here](https://github.com/rancher/rancher/issues/35709#issuecomment-1020061489) 


**Upgrade Test Steps**
1. Provision a cluster with k8s version: v1.21.8-rancher1-1 using rhel-8.4-docker-20.10.7-selinux-on-rpm ami
2. Create a deployment in the default namespace
3. Change the kdm version to: dev-v2.6-v1.20.14-0122
4. Upgrade the k8s: to v1.21.8-rancher2-1
5. Within a canal pod and the execute shell, with kube-flannel container selected run dmesg
6. There will be a segfault but after checking the previous made deployment you will see no issues in the logs and the deployment will be active. As long as the versions of libnftnl match this [comment](https://github.com/rancher/rancher/issues/35709#issuecomment-1021719423) we can say this issue is resolved sans the segfault causing deployments issues. 

**Further Info**

See this [comment](https://github.com/rancher/rancher/issues/36021#issuecomment-1015804526) for previous issues related to this.
