### ISSUE TITLE
edit container 

### ISSUE THREAD

**Issue by fedya** [rancher/rancher#3570]
I need to add new ENV value to created container, but i see only this
![snapshot6](https://cloud.githubusercontent.com/assets/598477/12923126/9019f0f8-cf65-11e5-9732-162c6cc61e1c.png)

Looks like i can edit only name and description, but it is absolutely useless.

**Comment by vincent99** [comment]
Containers are immutable.  Use services and [upgrade](https://github.com/rancher/rancher/issues/3563).
