### ISSUE TITLE
Add SLE BCI image for security-scan:v0.2.4

### ISSUE THREAD

**Issue by dhruvmewada15** [rancher/rancher#35719]
Add SLE BCI image in Dockerfile of security-scan:v0.2.4 (https://github.com/rancher/security-scan)

**Comment by dhruvmewada15** [comment]
How to Validate:

1. Rancher Server Version : v2.6.3
2. Create 3 downstream Single node multi role clusters of type rke1, rke2 and k3d each.
3. Install rancher-cis-benchmark chart on each cluster.
4. Run below tests for rke1, rke2  and k3d  with respective profile and you should get the following results.

    - RKE1 `rke-profile-permissive-1.6 `: Passed
    - RKE2 `rke2-cis-1.6-profile-permissive` : Passed
    - k3s `k3s-cis-1.6-profile-permissive` : Failed

> NOTE: The scan on k3s cluster also failed using rancher/security-scan:v0.2.4 with same number of passed/failed test results.

**Comment by rishabhmsra** [comment]
**Validated fresh install on rancher v2.6.3**

**Downstream cluster details:** All were AWS node driver cluster with `(3 nodes 1cp, 1w, 1etcd)`
- RKE1 -  k8s v1.21.8 
- RKE2 - v1.21.7+rke2r2
- K3s - v1.21.7+k3s1

**Validation steps:**
- Installed the CIS benchmark chart `2.0.2` by providing a test image for security scan that has the SLE BCI changes.
- Ran the 1.6 permissive profile scan on all the clusters.

**Result:**
- Chart got installed successfully. But seeing inconsistency in the scan results:
1. For rke1 permissive scan was successful.
2. For rke2 there are failures -> but same number of failures are also there with chart with `rancher/security-scan:v0.2.5` image. 
3. For k3s cluster the number of failures are different with `rancher/security-scan:v0.2.5` and test image(with SLE BCI changes).

**Comment by rishabhmsra** [comment]
**Validated again on rancher v2.6.3 with updated image for security-scan**

**Downstream cluster details:** All were AWS node driver cluster with (3 nodes 1cp, 1w, 1etcd)

- RKE1 - k8s v1.21.8
- RKE2 - v1.21.7+rke2r2
- K3s - v1.21.7+k3s1

**Validation steps:**

1. Created 3 downstream clusters of type rke1, rke2 and k3s.
2. Installed the CIS benchmark chart `2.0.2` by providing a local test image(`dhruvmewada15/security-scan:test-sle-bci`) for security-scan that has the SLE BCI changes.
3. Ran below tests for rke1, rke2 and k3s with respective profile and following are the results:
- RKE1 `rke-profile-permissive-1.6` : Passed
- RKE2 `rke2-cis-1.6-profile-permissive` : Getting same number of failure with both upstream - `rancher/security-scan:v2.0.5` and local image - `dhruvmewada15/security-scan:test-sle-bci`
- k3s `k3s-cis-1.6-profile-permissive` : Getting same number of failure with both upstream - `rancher/security-scan:v2.0.5` and local image - `dhruvmewada15/security-scan:test-sle-bci`

**Result :**
- CIS benchmark chart installed successful and the scan results are same with both image (upstream - `rancher/security-scan:v2.0.5` and local image - `dhruvmewada15/security-scan:test-sle-bci`).
