### ISSUE TITLE
Istio (100.0.2+up1.10.4) Installation via Rancher (v2.6.2) Charts Fails on AKS 

### ISSUE THREAD

**Issue by hari-narayanan94** [rancher/rancher#35722]
I am not able to Install Istio via Rancher Charts onto my AKS Cluster . 

Cluster Type : AKS (Azure Kubernetes)
K8s Version : 1.19.11

Istio Specs I am trying to Install : 

1. Enabled CNI
2. Enabled Ingress Gateway
3. Disabled Kiali , Jaeger , Egress Gateway

From what i understand istioctl is trying to get kubeconfig  and its tying to connect to api server but its failing , this is AKS and all these stuffs are self managed . 

Error Message on istioctl-installer POD : 

setting up kubeconfig
Switched to context "rancher-istio-context".
starting istioctl commands
unable to retrieve Pods: Get "https://10.43.0.1/api/v1/namespaces/istio-system/pods?fieldSelector=status.phase%3DRunning&labelSelector=app%3Distiod": dial tcp 10.43.0.1:443: i/o timeout
1.10.4
Unable to connect to the server: dial tcp 10.43.0.1:443: i/o timeout
2021-12-02T09:58:05.459554Z     error   analysis        error getting mesh config from running kube source: Get "https://10.43.0.1/api/v1/namespaces/istio-system": dial tcp 10.43.0.1:443: i/o timeout
Error: failed to get analysis result: timed out after 30s
error found during istioctl analyze

**Comment by hari-narayanan94** [comment]
Another thing I noticed , things seem to work fine if I use 100.0.0+up1.10.4 . Other two latest version seem to fail with the same error 

100.0.2+up1.10.4 --> Fails 

100.0.1+up1.10.4  --> Fails 

100.0.0+up1.10.4  --> Working

**Comment by gisyrus** [comment]
Hi, I got the exact error message as well. 

Cluster Type: Alicloud ACK (Containers for Kubernetes)
K8s Version: 1.20.11

Enable tracing, Pilot, Ingress Gateway

**Comment by mcasperson** [comment]
I got the same error with and EKS server:

```
setting up kubeconfig
Switched to context "rancher-istio-context".
starting istioctl commands
unable to retrieve Pods: Get "https://10.43.0.1/api/v1/namespaces/istio-system/pods?fieldSelector=status.phase%3DRunning&labelSelector=app%3Distiod": dial tcp 10.43.0.1:443: i/o timeout
1.10.4
Unable to connect to the server: dial tcp 10.43.0.1:443: i/o timeout
2022-04-02T05:27:36.589018Z	error	analysis	error getting mesh config from running kube source: Get "https://10.43.0.1/api/v1/namespaces/istio-system": dial tcp 10.43.0.1:443: i/o timeout
Error: failed to get analysis result: timed out after 30s
error found during istioctl analyze

```

**Comment by haswalt** [comment]
I've just tested on the same EKS cluster using `v100.2.1+1.12.6` and everything installed fine. I know this is a bit of a version bump (and a dev chart) but i'm interested to know what's changed to make this proceed correctly.
