### ISSUE TITLE
Workload/Deployment Not Working from Custom RKE2 Cluster

### ISSUE THREAD

**Issue by brudnak** [rancher/rancher#35729]
## Rancher Server Setup

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-46eb9d411b6afd0d75a323743adf5fddf4255219-head |
| Rancher cluster type    | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | RKE2 Custom                                        |
| Downstream K8s version  | v1.21.6+rke2r1                                     |
| Browser type            | Google Chrome                                      |
| Browser version         | 96.0.4664.55 (Official Build) (x86_64)             |

## Describe the bug

Deployments not working on custom RKE2 cluster.

## Custom Cloud Environment Setup Steps

1. Starting from AWS in the browser -> Go to `EC2` -> using the `New EC2 Experience` view
2. Click `Launch instances`
3. `Step 1: Choose an Amazon Machine Image (AMI)`
   - With the `Quick Start` tab selected -> scroll down and click `Select` for `Ubuntu Server 20.04 LTS (HVM), SSD Volume Type` | `ami-0629230e074c580f2 (64-bit x86`
4. `Step 2: Choose an Instance Type`
    - Mark the checkbox for `t3.xlarge`
    - click `Next: Configure Instance Details`
5. `Step 3: Configure Instance Details`
    - Leave defaults selected
    - Number of instances: `1`
    - Click `Next: Add Storage`
6. `Step 4: Add Storage`
    - Change the `Size (GiB)` from `8` to `50`
    - Click `Next: Add Tags`
7. `Step 5: Add Tags`
    - Add any tags if desired
    - Click `Next: Configure Security Group`
8. `Step 6: Configure Security Group`
    - Select the radio button for `Select an existing security group`
    - Choose the desired security group
    - Click `Review and Launch`
9. `Step 7: Review Instance Launch`
    - Click `Launch`
    - Select a key pair
    - Click `Launch Instance`

## Reproduction steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> click `Cluster Management` -> click `Create` -> toggle `RKE1` to `RKE2/K3s` -> click `Custom`
3. Fill out the cluster creation form
    - Cluster Name: `my-qa-cluster`
    - Kubernetes Version: `v1.21.6+rke2r1`
    - Defaults for other options
    - Click `Create` -> redirected to the cluster page and `Registration` tab
4. Mark the checkbox for `Insecure: Select this to skip TLS verification if your server has a self-signed certificate.`
5. `ssh` into the EC2 instance previously created and run the Rancher generated registration command, see screen shot below labeled `A1`

![001-a1](https://user-images.githubusercontent.com/40877149/144528529-d6df5c83-ba5f-4b9a-a5f6-4c28df7fb3e5.png)

6. This successfully provisions, see the next screenshot below labeled `A2`

![002-a2](https://user-images.githubusercontent.com/40877149/144528549-8acc911c-1980-4cad-8c6f-4d912e3ab069.png)

>At this point was trying to reproduce [https://github.com/rancher/rancher/issues/35710](https://github.com/rancher/rancher/issues/35710). However, was not getting the same results. Continued with some checks and found another potential issue. There is also another issue when trying to create a custom RKE2 cluster with a windows worker here: [https://github.com/rancher/windows/issues/122](https://github.com/rancher/windows/issues/122)
  
7. Click `hamburger menu` -> under `EXPLORE CLUSTER` select the custom RKE2 cluster that was just created -> click `Workload` -> click `Deployments` -> click `Create`
8. Fill out the deployment creation form
    - Name: `hello-world`
    - Container Image: `brudnak/hello-rancher-golang`
    - Click `Add Port`
        - Service Type: `Node Port`
        - Private Container Port: `3000`
        - Protocol: `TCP`
        - Listening Port: `30441`
        - Click `Create` -> then redirected back to the deployments page
9. Once the `hello-world` deployment becomes `Active` -> click the `Endpoint` URL as seen in the screenshot below labeled `A3`

![003-a3](https://user-images.githubusercontent.com/40877149/144528569-5209d234-3b44-432a-89b9-5e0fc8055612.png)

10. Once you click this URL the deployment does not come up, and you just get a `this site can't be reached` message. See screenshot below labeled `A4`

![004-a4](https://user-images.githubusercontent.com/40877149/144528582-f2685885-d1a1-429a-b2b7-d30f5d5458e4.png)

#### RESULT

A deployment created on custom RKE2 is not working.

#### EXPECTED

For the deployment to work on custom RKE2. I've used this image for testing a lot `brudnak/hello-rancher-golang` and it should display some basic HTML.

<hr>

**Comment by vincent99** [comment]
Did you open that port in the security group used for the nodes?

**Comment by brudnak** [comment]
Yes that port was open in the security group used

**Comment by snasovich** [comment]
@brudnak , thank you for reporting it. Is this something that is reproducible in 2.6.2 release? Trying to understand if it's a regression to better gauge priority.

**Comment by jakefhyde** [comment]
@slickwarren @Auston-Ivison-Suse @timhaneunsoo Can you verify that this is still an issue in v2.6-head?
