### ISSUE TITLE
Add support for new k8s versions in downstream clusters without requiring go-client updates

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#35738]
This will be a placeholder ticket for the feature request to be able to add support into downstream clusters for new k8s versions without having to require go-client updates.

**Comment by snasovich** [comment]
@kinarashah to investigate the design solution on this.

**Comment by snasovich** [comment]
Closing this one as after discussing specifics of this it was decided this is not feasible.
> After discussing it with the engineering team, this is unlikely to save us considerable efforts as we almost always run into quirks when adding support for newer k8s versions that go beyond just updating go-client version. Also, there are challenges with testing the potential solution as noted in the previous comment.
Therefore, this enhancement is rejected.
