### ISSUE TITLE
Add Rancher support for k8s 1.23

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#35739]
Feature ticket to ensure support for Kubernetes 1.23. 
For reference: https://github.com/kubernetes/website/blob/main/content/en/releases/patch-releases.md

K8s 1.23 - https://github.com/kubernetes/sig-release/tree/master/releases/release-1.23 targeted December 7th.

**Comment by kinarashah** [comment]
https://github.com/rancher/client-go/releases/tag/v1.23.3-rancher1

**Comment by kinarashah** [comment]
https://github.com/rancher/lasso/pull/16

**Comment by kinarashah** [comment]
https://github.com/rancher/rke/pull/2830

**Comment by kinarashah** [comment]
https://github.com/rancher/rke/pull/2851

**Comment by kinarashah** [comment]
https://github.com/rancher/kontainer-driver-metadata/pull/835

**Comment by kinarashah** [comment]
https://github.com/rancher/webhook/pull/74

**Comment by kinarashah** [comment]
`v1.23.4-rancher1-1` available to test, few things to note: 

 **RKE standalone** 
 - `v1.3.8-rc4` https://github.com/rancher/rke/releases/tag/v1.3.8-rc4 
 -  v1.23 should be the default version 
 
**Rancher `v2.6-head`** 
- confirm image is the latest and has commit https://drone-publish.rancher.io/rancher/rancher/7417 
- local cluster should be updated to `v1.23.3` k3s 

**Cluster updates for RKE1 `v1.23.4`** 
- etcd `v3.5.2` 
- rke-tools `v0.1.79` 
- calico `v3.22.0` 
- nginx ingress controller `v1.1.1` 
- coredns `v1.9.0` 
- cluster-proportional-autoscaler `v1.8.5` 
- mirrored-pause `v3.6` 
- metrics-server `v0.6.1`

**Comment by sowmyav27** [comment]
@rishabhmsra @vivek-infracloud Please validate all the scenarios listed in the test plan for k8s 1.23 support before closing this issue.

**Comment by sowmyav27** [comment]
On 2.6head commit id: `4df221`, local cluster's version - `v1.23.3+k3s1`

**Comment by sowmyav27** [comment]
Closing this issue as separate issues have been logged for Windows on 1.23 k8s.
etcd/control plane checks/fresh install and KDM upgrades have been done.
