### ISSUE TITLE
Cannot rollback upgrade to a now invalid state

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3573]
If you attempt to rollback an upgrade of a service, and the previous state is now invalid, the service gets stuck in a 'rollback finishing' state.

To duplicate:

- Assume an Enviroment with 2 hosts.
- Set up a service with public port 80 and Global=yes.
- Then, use 'Upgrade' to change the public port to 8080 but do not finish the upgrade yet.  
- Now set up a second Service, also with public port 80.  This will start correctly because the first service is no longer attached to port 80.
- Now cancel the upgrade on the first service.  It will attempt to roll back and make the container listen on port 80.
- However, as port 80 is already bound, the service cannot start.  The stack gets stuck in 'rollback finishing' as it repeatedly tries to restart the service containers, and you cannot do anything but delete the stack as it never gives up.

What (I think) should happen -- if the rollback or upgrade container(s) fail to start, the service should be left in Degraded state and Rancher should stop trying.

**Comment by sshipway** [comment]
Related: #3559

**Comment by alena1108** [comment]
@sshipway I don't think we could do anything about it. Rollback is similar to starting (activating) a new service; and when that results in ports conflicts, the service gets stuck in intermediate state till the port conflict gets resolved (stopping the other service, upgrading the other service to the diff set of ports). So in case of rollback failure, following steps need to be made:

* cancel the rollback - you don't have to delete the stack to get rid of the failure. 
* fix the port conflicts - upgrade the second service to the diff set of ports.
* proceed with the rollback for the stack.

**Comment by sshipway** [comment]
The problem is, there is no way to cancel the rollback.  If I start a service on a conflicted port, it of course will not start.  Then I use 'upgrade' to alter the port but accidentally pick another wrong port.  Then I cannot complete the upgrade (conflict) but cancelling it causes a rollback which again cannot complete (conflict) and I have no way out as I cannot cancel a rollback, or even stop the service any more.  I have to delete the stack.

**Comment by sshipway** [comment]
Surely, if an upgrade/rollback fails due to a port conflict, the sensible thing would be for the service to go into a Stopped state and finish the upgrade/rollback process, rather than repeatedly retrying (and failing) to start?

**Comment by alena1108** [comment]
@sshipway 

>>Surely, if an upgrade/rollback fails due to a port conflict, the sensible thing would be for the service to go into a Stopped state and finish the upgrade/rollback process, rather than repeatedly retrying (and failing) to start?

The reason why we don't do the stop - it would be hard to distinguish whether it was a normal Stop, or Stop as a result of a failed process. Generally failed processes in Rancher either stay in intermediate state, then after  user corrects the problem, the process retry would finish it. Or the resource goes into Error state from where it can only be Removed/Purged. 


>> and I have no way out as I cannot cancel a rollback, or even stop the service any more. I have to delete the stack.

there is a way to cancel a rollback... @vincent99 do we expose it in the UI? There is a state transition, and the API is tested: https://github.com/rancher/cattle/blob/802e90cb026993a5c24dd0ffdc3475f4e0afb2bb/code/packaging/app-config/src/main/resources/META-INF/cattle/process/spring-process-context.xml#L304

**Comment by alena1108** [comment]
@sshipway confirmed with the UI team - we do have CancelRollback action for the service stuck in Rolling-back state. That would be the way to stop failing roll back.

**Comment by alena1108** [comment]
@sangeethah could you test to verify that cancelRollback option is provided for:

* service in rolling-back state
* stack in rolling-back state

**Comment by deniseschannon** [comment]
Verified with v0.63.0-rc1 that when either service or stack are in rolling-back state, there is a "Cancel Rollback" option in the UI,
