### ISSUE TITLE
Add metrics and graphs for performance/scaling

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#35737]
~Creating this as a placeholder ticket for the enhancement request from product for additional Rancher app metrics by enhancing the dashboard that is deployed on local clusters when monitoring has been turned on.~

**Description:**
Implement metrics and graphs that related to scaling. These metrics are not necessarily intended to be on continuously and are more so for enabling for a short amount of time. This means that limiting their resource consumption is not a main priority as hardware can be scaled up for the duration of the readings. These metrics and graphs will be used to:
* help support debug performance issues
* help qa do performance testing
* help devs debug performance issues and test new feature implementations
* help define new benchmarks for performance goals

**Related tasks:**
- [ ] Include graphs for each metric in one or more dashboard(s).
- [ ] Enable authentication with sa tokens for metrics endpoint. https://github.com/rancher/rancher/issues/36234
- [ ] Implement metrics via monitoring chart. https://github.com/rancher/rancher/issues/36234

**Add metrics for:**
- [x] Kubernetes API access
- [x] Rancher API
- [x] Tunnels
- [x] Controllers
- [x] Queues
- [x] Handlers
- [x] Cache sizes
- [x] Proxy API

**Comment by rmweir** [comment]
I think the way this should be QA'd is that the regular QA team should just validate that the chart works:
* Set CATTLE_PROMETHEUS_METRICS env var to "true"
* install monitoring
* Go to dashboard -> rancher performance debugging dashboard
* Confirm that all the metrics are populated

I think the performance team (cc: @git-ival ) should benchmark having these metrics enabled against metrics when CATTLE_PROMETHEUS_METRICS is unset. It would also be useful to benchmark these against the older version of metrics but set up with the service monitor and controllers dashboard. I have a hunch that those the new metrics will not be less performance by much and that a lot of the slow down is caused by the cardinality in the norman metrics. Realized this after @ryansann suggested reducing labels for newer metrics.

**Comment by brudnak** [comment]
waiting on https://github.com/rancher/rancher/issues/36770

**Comment by brudnak** [comment]
# My checks PASSED

<hr>
  
## Validation Environment

| Component                       | Version / Type                                    |
| ------------------------------- | ------------------------------------------------- |
| Rancher version                 | v2.6.4-rc6                                        |
| Rancher cluster type            | Helm high availability                            |
| Helm version                    | v2.16.8-rancher1                                  |
| Downstream cluster type         | RKE Linode                                        |
| Downstream K8s version          | v1.23.4-rancher1-1                                |
| Browser type                    | Google Chrome                                     |
| Browser version                 | 99.0.4844.51 (Official Build) (x86_64)            |
| Rancher `git.rancher.io/charts` | Commit : 792b58bc2992e0200f050b939654048f266f6336 |

## Validation steps

1. Set `CATTLE_PROMETHEUS_METRICS` environment variable to `true`
   1. Starting from the **default** Rancher homepage `/dashboard/home`
   2. Click `hamburger menu` -> `local` -> `Workload` -> `Deployments` -> `All Namespaces` -> right click on `rancher` under the `cattle-system` namespace -> click `Edit Config`
   3. Under `Environment Variables` -> click `Add Variable` -> Type: `Key/Value Pair` -> Variable Name: `CATTLE_PROMETHEUS_METRICS` -> Value: `true`
2. Install monitoring on the local cluster
3. Navigate to Grafana and login
    - Username: `admin`
    - Password: `pom-operator`
4. Once in Grafana navigate to:
    - `Dashboards` -> `Manage` -> Click on the `Rancher Performance Debugging` dashboard
5. Wait 30 minutes while running various Postman API calls against the cluster
6. Verify the graphs are populating

## Results

#### Expected
For the Rancher Performance Debugging dashboard to be available and start populating with data

#### Actual
The Rancher Performance Debugging dashboard was visible and the graphs started to populate

**Comment by bmdepesa** [comment]
Reopening for the performance testing.

**Comment by git-ival** [comment]
Completed comparison of the latest rancher-monitoring version between Rancher 2.6.4-rc8 and 2.6.3-patch1. Overall scalability seems to be somewhat reduced in 2.6.4. Resource usage peaks earlier on 2.6.4 with `CATTLE_PROMETHEUS_METRICS` enabled, causing the Rancher API to not be able to handle further batched cluster provisioning requests for some time. Results may be more in-line with previous versions if the # of clusters provisioned per batch is reduced.

Note: Provisioned at a rate of 50 Downstream K3s clusters per batch, targetting 300 downstreams total.
