### ISSUE TITLE
[RKE2] scale down button is not shown on rke2 clusters, but is for rke1 in the `manage` cluster page

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35756]
**Rancher Server Setup**
- Rancher version: v2.6.3-rc3
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:any for rke2
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):digital ocean, aws

**Describe the bug**

the `scale down` button is not displayed on rke2 cluster manage page, but is shown for rke1

**To Reproduce**
 
* provision an rke2 cluster with at least 2 nodes in 1 pool
* once active, click on the cluster name from the `cluster management` page

**Result**
`scale down` button is not there (this button is greyed out on rke1 clusters until you select a node via a checkbox
![img.png](https://user-images.githubusercontent.com/12828077/129232026-206097cd-934f-4c08-ae0d-a8b8d1d2607b.png)

**Expected Result**

rke2 should also have the scale down button

**Screenshots**

for comparison, here's the rke1 page
![scale_down1](https://user-images.githubusercontent.com/12828077/129232032-fd4b5eeb-cddf-42b8-ae92-e740dabeb4f2.png)

**Comment by snasovich** [comment]
This is new functionality to be developed as part of https://github.com/rancher/dashboard/issues/4446. Closing as a duplicate.
