### ISSUE TITLE
Ingress isnt working on a rancher server upgrade from 2.5.11 on RKE1 Node driver clusters on 1.18 and 1.17 clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35764]
**Rancher Server Setup**
- Rancher version: 2.5.11 to 2.6.3-rc4
- Installation option (Docker install/Helm Chart): docker install 1.19k3s to v1.22.3+k3s1 upgrade of local cluster

**Information about the Cluster**
- Downstream clusters in the setup:
```
GKE - Ingress works
Imported k3s - Ingress works 1.20.12k3s
RKE1 custom - ingress works - 1.20.12
RKE1 DO Node driver - ingress doesnt load - v1.17.17
```

**Describe the bug**
Ingress isnt working on a rancher server upgrade from 2.5.11 on RKE1 clusters

**To Reproduce**

- On 2.5.11, deploy 4 clusters mentioned above
- Deploy workloads + ingress
- Upgrade to 2.6.3-rc4
- Ingresses dont work
- When you try to load the ingress page (in Ember UI), error seen

```
NotFound (404)
the server could not find the requested resource

Reload to try again or log out
```
- Error in Network call `{"baseType":"error","code":"NotFound","message":"the server could not find the requested resource","status":404,"type":"error"}`

**More testing:**

- On another rancher server - 2.5.11, had 4 downstream clusters with all 4 k8s - `v1.20.12`, `v1.19.16`,  `v1.18.20`, `v1.17.17`
- Deploy workloads and ingress, and upgrade to 2.6.3-rc4
- On  `v1.18.20`, `v1.17.17` clusters, existing ingress isnt working, failed with error `NotFound (404)`
- On upgrading `v1.18.20` to `v1.19.16`, the ingress page loads and able to create ingress
- On upgrading `v1.17.17` to `v1.18.20`  ingress isnt working, failed with error `NotFound (404)`

**Comment by sowmyav27** [comment]
Similar ingress issue -https://github.com/rancher/rancher/issues/35636

**Comment by cmurphy** [comment]
This should be addressed by https://github.com/rancher/rancher/pull/35697

**Comment by sowmyav27** [comment]
**On an upgrade from 2.5.11 to 2.6head commit id: `e4db3e`**

1. On 2.5.11, deploy 1.17 and 1.18 clusters RKE1 node driver DO
2. Deploy workloads + ingress
3. Upgrade to 2.6head
4. Existing ingress created in step 2 work
5. Create new ingress+workloads. Verified these work too.
6. Upgrade k8s version 1.17 --> 1.18 and 1.18 --> 1.19 on the existing clusters
7. verified ingress created in Step 5 continue to work and new ingress+workloads also work (created through v2 api calls)
