### ISSUE TITLE
Webhook restarts with error no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\" during rancher upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35763]
**Rancher Server Setup**
- Rancher version: 2.5.11 to 2.6.3-rc4
- Installation option (Docker install/Helm Chart): docker install

**Describe the bug**
Webhook restarts with error no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\" during rancher upgrade

**To Reproduce**

- On 2.5.11 docker install rancher, deploy a few downstream clusters
- Upgrade to 2.6.3-rc4
- In local cluster, check webhook workload. 
- It is in Unavailable state with error in logs:

**Result**
```
time="2021-12-05T16:09:29Z" level=info msg="Rancher-webhook version dev (HEAD) is starting"
time="2021-12-05T16:09:29Z" level=info msg="Listening on :9443"
time="2021-12-05T16:09:29Z" level=info msg="Active TLS secret cattle-webhook-tls (ver=3170) (count 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-12-05T16:09:29Z" level=fatal msg="no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\""
```

**Comment by thedadams** [comment]
This is the same as https://github.com/rancher/rancher/issues/35696

**Comment by sowmyav27** [comment]
**on an upgrade from 2.5.11 to 2.6-head commit id: `e4db3ee`**

- webhook `rancher/rancher-webhook:v0.2.2-rc2` is deployed successfully. No restarts seen.
