### ISSUE TITLE
Fix ability for service in initializing state to resolve itself

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3576]
In the comments of https://github.com/rancher/rancher/issues/2890, the discussion occurred about how services in initializing state should work in DNS resolution.

Currently, if service foo is still in initializing state, it can still resolve other services in Rancher, but not itself.

**Comment by alena1108** [comment]
@deniseschannon it was fixed in the latest, will be available in the next release.

**Comment by sangeethah** [comment]
Tested with latest build from master:

Have a service - test1 with scale 2 that has both containers stuck in "Initializing" state.
From within these containers , "test1" resolves to one of the container ips of this service.

From within container of any other service with in the same stack ,  "test1" resolves to one of the container ips of this service.
