### ISSUE TITLE
Downstream cluster toggles between Active and Unavailable states for sometime after a rancher server upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35767]
**Rancher Server Setup**
- Rancher version: 2.5.11 to 2.6.3-rc4
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: RKE1 DO cluster of all 4k8s versions (4 clusters)

**Describe the bug**
Downstream cluster toggles between Active and Unavailable state for sometime after a rancher server upgrade

**To Reproduce**

- On 2.5.11, deploy 4 downstream clusters
- upgrade rancher to 2.6.3-rc4
- The cluster toggles between Active and Unavailable states for sometime (~30 secs - 1min) before coming back up Active

**Note:**

- This is a change in behavior from prev rancher versions.
- Earlier it used to switch to Unavailable one time before coming back up Active
- This new change seems like a bad UX experience for the users. (But it will eventually turn back up Active)

**Comment by kinarashah** [comment]
@sowmyav27 Is the Unavailable state because of cluster agent is redeploying? This should show up in the UI or in the conditions under view in yaml of the cluster. I think this sounds very similar to https://github.com/rancher/rancher/issues/35640.

**Comment by kinarashah** [comment]
Available to test after https://drone-publish.rancher.io/rancher/rancher/6988 merges.

**Comment by sowmyav27** [comment]
**On an upgrade from 2.6.2 to 2.6-head commit id: `77392a`**

- Cluster stay in Active state during cluster agent upgrade also
- Had one rke1 node driver cluster downstream
