### ISSUE TITLE
Ingress are not accessible after a rancher server upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35766]
**Rancher Server Setup**
- Rancher version: 2.5.11 to 2.6.3-rc4 upgrade
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: 1.20.12-rancher1-2 rocky Custom cluster RKE1 and v1.17.17 RKE1 DO Node driver cluster

**Describe the bug**
Ingress dont work since they seem to be missing `ingressClassName`

**To Reproduce**

1. On 2.5.11, create downstream cluster
2. Create workload + Ingress
3. Upgrade rancher to 2.6.3-rc4
4. Create workload + Ingress
5. Upgrade k8s versions of the clusters to 1.22.3rancher1-1
6. Create workload + Ingress
7. Ingress created in Step 2 and 4 dont work now. 

- Error in ingress controller:
```
I1205 17:07:25.267710       8 store.go:367] "Ignoring ingress because of error while validating ingress class" ingress="pre-ns1/pre-testingress1" error="ingress does not contain a valid IngressClass"
I1205 17:07:25.267744       8 store.go:367] "Ignoring ingress because of error while validating ingress class" ingress="pre-ns1/pre-testingress2" error="ingress does not contain a valid IngressClass"
```

**Note**

- These failures seem to be inconsistent since [this](https://github.com/rancher/rancher/issues/35764) issue was seen when accessing the ingress (an hour back). But isnt seen anymore.
- The ingresses created in Step 2 ^^^ worked when rancher server was upgraded and Automation was run right after to validate. But doesnt work anymore after k8s upgrade.
- Not able to create an ingress on the DO cluster now. fails with error: 
```
Not able to create an ingress, fails with error "admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "sslip.io" and path "/name.html" is already defined in ingress post-k8s-ns1/ing01"
```

**Comment by superseb** [comment]
Can be tested with latest v2.6-head: `fd930f765`

**Comment by cmurphy** [comment]
@superseb https://github.com/rancher/rancher/pull/35818 is still in review, this is not ready to test yet

**Comment by sowmyav27** [comment]
To Validate:
Fresh install checks on 2.6-head

- Deploy 1.22 k8s cluster and make sure the ingress works
- deploy a 1.21 cluster and upgrade to 1.22 and make sure ingress works

Upgrade checks from 2.5.11 to 2.6-head

- Deploy clusters 1.17, 1.18, 1.19, 1.20 on 2.5.11. Deploy ingresses
- upgrade to 2.6head.
- Verify existing ingresses and new ingress works.
- Upgrade k8s version - 1.17 to 1.22, 1.18 to 1.22, 1.19 to 1.22 and 1.20 to 1.22
- Verify existing ingresses and new ingress works.
