### ISSUE TITLE
Cluster is stuck in provisioning state with error "Waiting for daemon set "cattle-node-agent" rollout to finish" when a worker node is unavailable after a rancher upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35762]
**Rancher Server Setup**
- Rancher version: 2.5.11 to 2.6.3-rc4 upgrade
- Installation option (Docker install/Helm Chart): RKE1 elm install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 - `v1.20.10` k8s version
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: v1.17.17 k8s version
- Cluster Type (Local/Downstream): RKE1 Azure node driver

**Describe the bug**
Cluster is stuck in provisioning state with error "Waiting for daemon set "cattle-node-agent" rollout to finish" on a rancher server upgrade

**To Reproduce**

- On 2.5.11.
- Deploy a Azure cluster - 1 etcd, 1 cp and 3 worker nodes
- Deploy some workloads and resources
- Helm upgrade rancher server to 2.6.3-rc4
- The cluster is stuck in provisioning state (Checked after about a couple of hours)
- Error on cluster: `Timeout waiting rollout agent daemonset: exit status 1, Waiting for daemon set "cattle-node-agent" rollout to finish: 4 of 5 updated pods are available... error: timed out waiting for the condition`
- One node in Azure downstream cluster is Unavailable - `Kubelet stopped posting node status.`
- Not able to login to the node from local terminal
- In Azure console it shows

```
Agent status - Not Ready
Agent version - Unknown
```

**Expected Result**
- If a worker node goes down during a rancher upgrade, the cluster should still be active.

**- Note:**
- Tried to reproduce on another single node docker install using EC2 node driver, 1.17 downstream cluster, and upgraded from 2.5.11 to 2.6.3-rc4, issue isnt seen

**Comment by gp187** [comment]
+1

**Comment by thedadams** [comment]
I have not been able to reproduce this issue.

The fact that the `Agent status` on the Azure VM is in the `Not Ready` state, I would expect that is the problem. In other words, Rancher doesn't control the Azure Guest Agent, so if it has a status of `Not Ready` then this is likely what is causing the node to be `Unavailable` and the rollout of the new node-agent daemonset to timeout.

**Comment by thedadams** [comment]
@sowmyav27 gave me access to the cluster where she saw this issue. After investigation, it seems that the VM is not reachable and is not available because of that.

It is my belief that the unavailability of the node is related to the underlying VM and not Kubernetes/Rancher related.

**Comment by thedadams** [comment]
One more thing: SSH is successful on `wrker-2`, but times out on the affected machine. This is another indication that the underlying VM is the problem here.

![Screen Shot 2021-12-06 at 4 01 58 PM](https://user-images.githubusercontent.com/3682717/144936951-c15d1e69-6ad9-4c41-83d5-041ca45dfdab.png)

**Comment by thedadams** [comment]
![Screen Shot 2021-12-06 at 4 01 58 PM](https://user-images.githubusercontent.com/3682717/144937392-74ea9fd8-4841-41f9-96c9-11f43fc5e27c.png)

**Comment by sowmyav27** [comment]
After scaling down the worker node that was stuck in Unavailable state, the cluster eventually came up Active. Closing this issue based on Donnie's comments ^^^^
