### ISSUE TITLE
How to clear rancher agent on User Cluster

### ISSUE THREAD

**Issue by scila1996** [rancher/rancher#35773]
Hi !

I have installed rancher on dedicated Kubernetes cluster, and it called with "Management Cluster", then I add 10 other clusters to Management Cluster and them is called "User Cluster", Now I want to remove a User Cluster from Management Cluster and want to clear rancher agent and all resource of it on User Cluster. How can I do that !

Thanks !

**Comment by cbron** [comment]
You can find more info on that here: https://rancher.com/docs/rancher/v2.5/en/faq/removing-rancher/
