### ISSUE TITLE
[2.6.2] vSphere RKE2 Add-On Config not available

### ISSUE THREAD

**Issue by SoarinFerret** [rancher/rancher#35777]
**Rancher Server Setup**
- Rancher version: 2.6.2 (also tested on 2.6.1)
- Installation option (Docker install/Helm Chart): Docker Install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: Traefik with LetsEncrypt in front of Rancher

**Information about the Cluster**
- Kubernetes version: v1.21.6+rke2r1
- Cluster Type (Local/Downstream): Downstream using vSphere Infrastructure Provider
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

When creating a vSphere cluster on RKE2, you have the option of selecting the "vSphere" cloud provider. After doing so, the following text appears: `Important: Configure the vSphere Cloud Provider and Storage Provider options in the Add-On Config tab.`

However, when going to the "Add-On Config" tab, the only options are to edit the Calico config and/or Additional Manifests. If you include a cloud-config configmap to be deployed in the Additional Manifests options, the CPI fails to install.

According to the documentation located [here](https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/cloud-providers/vsphere/out-of-tree/) and issue #33875, I am led to believe additional configurations should be available.

**To Reproduce**
 

1. Create new Cluster using vSphere RKE2 
![image](https://user-images.githubusercontent.com/33401067/144895475-12748838-c719-45f2-a88d-3d120903d92e.png)
2. Configure basic node pool
3. Select "vSphere" from Cloud Providers 
![image](https://user-images.githubusercontent.com/33401067/144895702-ea8c68e1-edae-4f9e-a875-0f07e408d6c6.png)
4. Select "Add-On Config" from right-hand side, and do not see any additional Add-On configs 
![image](https://user-images.githubusercontent.com/33401067/144896019-f64df951-5e89-45d7-b0a3-8664a87e6d4e.png)

**Result**
Cluster fails to provision with "Waiting for cluster agent to be available" - this is because the CPI is never successfully deployed, and as such there is a taint on the node for `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` which prevents the cluster agent deployment & replicasets from running.

**Expected Result**

Cluster successfully deploys with a properly configured vSphere CPI & CSI

**Additional context**

If you try to manually provide the cloud-config, the helm chart fails to deploy because of helm not managing the config file. 
![image](https://user-images.githubusercontent.com/33401067/144899173-7da9c616-8717-4bb2-905a-0f235f33cb25.png)

I assume if I manually edit the RKE2 config to include the proper configuration, it would work, though I have not done it at this point. Instead, I have been creating the clusters with the "external" cloud provider and adding the config there.

**Comment by SoarinFerret** [comment]
Appears to be localized to my instance - spinning up a new version of Rancher does not show this. It may be related to our Traefik reverse proxy, or some failed update down the line. I'll close for now, and update with more information if I find any. Thanks!

**Comment by SoarinFerret** [comment]
Ok, further testing and I am unable to consistently get it to appear. After spinning up a new instance, it showed up most of the time. I added Traefik in front of it and then it stopped working. So I then removed traefik again... and it still doesn't work?

I have removed traefik from our main instance as well, and updated it to use a LetsEncrypt cert directly, and we are still seeing the issue there.

Looking at the browser console logs, the following sticks out to me:
![image](https://user-images.githubusercontent.com/33401067/145258837-042d9086-6523-4a4f-9e8b-50da76a28cb9.png)

**Comment by SoarinFerret** [comment]
If I manually add the YAML for rancher-vsphere-cpi & rancher-vsphere-csi, the cluster does provision correctly. In addition, standing up a brand new rancher server works for awhile, but seems after some time (I checked after 12 hours), it stops working.

**Comment by dmpe** [comment]
Haha, I am also getting this.... And so far no solution for the missing config in addon tab. We have 2 Rancher environments, one works (2.7.9) and another one, brand new 2.7.9., does not.
