### ISSUE TITLE
OIDC Authentication plugin with custom CA not working

### ISSUE THREAD

**Issue by Peyoz** [rancher/rancher#35771]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Helm Chart): 
  ```
  hostname: REDACTED
  ingress:
  tls:
    source: tls-rancher-ingress
  privateCA: true
  proxy: REDACTED
  noProxy: REDACTED
  additionalTrustedCAs: true
  ```
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
     RKE1 v.1.3.2 
- Proxy/Cert Details:
  Imported intermediate and CA certificate from internal CA

**Information about the Cluster**
- Kubernetes version:  kubernetes_version: v1.19.16-rancher1-1
- Cluster Type (Local/Downstream): local

**Describe the bug**
Enabling OIDC authentication reports generic issue about certificate not signed by known authority
```
[generic oidc]: server error while authenticating: Get "https://[KEYCLOAK]/auth/realms/REALM/.well-known/openid-configuration": x509: certificate signed by unknown authority 
```

**To Reproduce**
Configure OIDC provider as documentation requires

**Result**
[generic oidc]: server error while authenticating: Get "https://[KEYCLOAK]/auth/realms/REALM/.well-known/openid-configuration": x509: certificate signed by unknown authority 

**Additional context**
tls-ca-additional seems to be correctly imported in rancher container.
When i try to validate the url of the keycloak server, it works fine
```
[rke@REDACTED rancher-latest]$ k exec -it -n cattle-system rancher-75df9db875-75n9p -- bash
rancher-75df9db875-75n9p:/var/lib/rancher # openssl s_client -CAfile /etc/rancher/ssl/ca-additional.pem -connect REDACTED:443 < /dev/null 2> /dev/null|grep "Verify return code:"
    Verify return code: 0 (ok)
```

**Comment by diLLec** [comment]
Hi there,

we have the exact same issue. 

* Rancher version: 2.6.2
* Installation option (Helm Chart):
```
hostname: ...
bootstrapPassword: ...
additionalTrustedCAs: true
debug: true
extraEnv:
  - name: SSL_CERT_DIR
    value: "/etc/rancher/ssl/"
```
* RKE1 v.1.3.2
* Imported CA certificate from internal CA to cattle-system/tls-ca-additional

Note: Also, setting the SSL_CERT_DIR environment variable does not help

```
extraEnv:
  - name: SSL_CERT_DIR
    value: "/etc/rancher/ssl/"
```

Verification via openssl also comes back clean:
```
openssl s_client -connect <keycloak>:443 | grep "Verify return code:"
depth=1 C = .., ST = .., L = .., O = ..
verify return:1
depth=0 C = .., ST = .., L = .., O = .., CN = ..
verify return:1
Verify return code: 0 (ok)
```

**Comment by Peyoz** [comment]
Still relevant issue

**Comment by sjansen1** [comment]
Same issue on latest Rancher on kubernetes with keycloak and custom root ca. Adding root ca in tls-ca-additional has no effect.

**Comment by groucho64738** [comment]
having a similar issue here.

**Comment by groucho64738** [comment]
I may have spoken a little soon, but I think I might have it working now (if this helps anyone). I am using Keycloak as my authenticator, and instead of just having a cert for the Keycloak server, I create a cert chain with the server cert, intermediate, and root certs all cat'ed together. Rancher then did not seem to have any issues connecting at that point (even though rancher already had the root/intermediate certs loaded)

**Comment by arnicel** [comment]
> I may have spoken a little soon, but I think I might have it working now (if this helps anyone). I am using Keycloak as my authenticator, and instead of just having a cert for the Keycloak server, I create a cert chain with the server cert, intermediate, and root certs all cat'ed together. Rancher then did not seem to have any issues connecting at that point (even though rancher already had the root/intermediate certs loaded)

Tested on my cluster and I can confirm this is working. I added the cert and the chain as a additional trusted CAs. You can find how to do it here: https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/chart-options/#additional-trusted-cas

**Comment by aslafy-z** [comment]
I feel like this should be at least documented. Keeping the issue open.

**Comment by aslafy-z** [comment]
Not stale
