### ISSUE TITLE
Rancher Ingress getting-err-too-many-redirects-on-ingress 

### ISSUE THREAD

**Issue by prajnadnayak** [rancher/rancher#35770]
**Rancher Server Setup**
Rancher installed using helm charts. 

- Rancher version:
  v2.5 
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
     RKE 1.3.1.
     K8s version v1.20
     Helm  v3.7.1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   local  hosted on VMware 

**Describe the bug**

Installed Rancher with tls=external and hostname = DNS . When we hit the rancher URL we get getting-err-too-many-redirects-on-ingress . 

 helm install --wait rancher rancher-stable/rancher --namespace cattle-system --set tls=external --version 2.5 --set hostname="aus-temp-rancher.mydomain.com"

Rancher Ingress file that is generated: 

`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.x.x.60","10.x.x.61","10.x.x.62"],"port":80,"protocol":"HTTP","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"aus-temp-rancher.mydomain.com","allNodes":false}]'
    meta.helm.sh/release-name: rancher
    meta.helm.sh/release-namespace: cattle-system
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  creationTimestamp: "2021-12-06T10:54:10Z"
  generation: 3
  labels:
    app: rancher
    app.kubernetes.io/managed-by: Helm
    chart: rancher-2.5.11
    heritage: Helm
    release: rancher
  name: rancher
  namespace: cattle-system
  resourceVersion: "1664252"
  uid: 66972655-990b-4da6-8d30-69bb0f01b816
spec:
  rules:
  - host: aus-temp-rancher.mydomain.com
    http:
      paths:
      - backend:
          service:
            name: rancher
            port:
              number: 80
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 10.X.X.60
    - ip: 10.X.X.61
    - ip: 10.X.X.62`

**To Reproduce**
 

**Result**
getting-err-too-many-redirects-on-ingress when we try to hit the Rancher URL at "aus-temp-rancher.mydomain.com"

**Expected Result**
Should load the Rancher dashboard

**Additional context**

**Comment by prajnadnayak** [comment]
Any update on this ?

**Comment by thebetterjort** [comment]
+1

**Comment by kerituni12** [comment]
the same issue

**Comment by madhosoi** [comment]
I have the same issue, deployed on RKE2 on-premise cluster

**Comment by Flou21** [comment]
same issue

**Comment by Joao-1** [comment]
Same issue
