### ISSUE TITLE
Possibility to mark stack as "system"

### ISSUE THREAD

**Issue by raphink** [rancher/rancher#3577]
I'd like to be put stacks in the "System" tab. I know it's possible to do it by editing the stack in the API view and changing `catalog://` into `system-catalog://` but I wonder if it wouldn't make sense to expose this in `rancher-compose.yml`, say in the `.catalog:` hash for example.

When preparing an environment, I'd like monitoring/logging/fs stacks to be in system, so that the "Stacks" tab could contain only the application that is being deployed.

**Comment by clicman** [comment]
Also it will be great to move already created stacks.

**Comment by sshipway** [comment]
+1 to this; including being able to move stacks.
I've also requested in #4807 for System stacks to be restricted to Owners

**Comment by failedguidedog** [comment]
@raphink Could I ask you to describe how you make the change from `catalog://` to `system-catalog://`? I can't for the life of me find the correct API object and action :(

**Comment by vincent99** [comment]
Click "View in API" on a stack, then the edit button and change the externalId field.

**Comment by dalareo** [comment]
Is this still available? With infra tag, system-catalog is not valid anymore!

**Comment by eshork** [comment]
@dalareo Now there is a "system" boolean attribute. Simply set it to `true` by checking the box within the API view.

**Comment by vincent99** [comment]
You must be an owner of the project to set system: true.  It is not intended to be a user organization system (and neither was the external id naming) and may have other side effects in the future that are not desirable for the user stacks you set it on.

There are tags on stacks in 1.2+ which allow arbitrary user grouping.

**Comment by eshork** [comment]
Makes sense, but on another hand, being able to arbitrarily mark a stack as non-User (despite the tagging mechanism, which I use myself) has some merit. If users are looking to remark stacks to get them out of User, then perhaps some third location is warranted to hold them? Sometimes the OCD doesn't want any support stacks in the User display. 😉

**Comment by dalareo** [comment]
Where is the boolean atribute set? @eshork

**Comment by eshork** [comment]
@dalareo 
Click "View in API" on a stack, then the edit button and change the system field

**Comment by dalareo** [comment]
Thanks!!

**Comment by vincent99** [comment]
I'm going to go ahead and close this...

We have tags now as a mechanism for users to organize their stacks.  If enough people really want it, I could understand a separate enhancement to choose which tag you see or don't see by default or something like that.

The `system` flag affects what permissions things running in the stack have and what permissions users need to manipulate them. It is not intended for user organization and the behaviors it imparts on the containers running in the stack may change in the future and break your usage of them.

**Comment by gerich-home** [comment]
Shouldn't we have an ability to do it from Rancher CLI?

I see that stack can be created as system stack by specifying --system flag (https://docs.rancher.com/rancher/v1.2/en/cli/commands/#rancher-stacks-create), but what about upgrading it (https://docs.rancher.com/rancher/v1.2/en/cli/commands/#rancher-up-reference).

I am about to try it, but in my Ansible script it would be much easier for up command to have --system flag as well to ensure operation is idempotent.

Should I create a separate issue?

**Comment by dmitryint** [comment]
same issue: https://github.com/rancher/rancher/issues/7741

**Comment by pythianarceri** [comment]
Similar issue #8801 , would like to see a toggleable flag in the cli utilities and gui.
