### ISSUE TITLE
Rhel 8.4 Docker 2.10.7 cluster | Cluster agent fail to update

### ISSUE THREAD

**Issue by Auston-Ivison-Suse** [rancher/rancher#35784]
**Rancher Server Setup**
- Rancher version: 2.6.2 (upgraded to 2.6.3-rc4 later)
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version: v1.21.6-rancher1-2
- Cluster Type (Local/Downstream): Rke1
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
     - rhel-8.4-docker-20.10.7-selinux-on-rpm - ami-0f3d6c27d7ba5006e (3 workers, 3 etcd, 1 control plane) 

**Describe the bug**

Cattle-cluster-agent gets stuck updating, with a status "Deployment does not have minimum availability" 

**To Reproduce**
1. Have a 2.6.2 HA setup (3 nodes) 
2. As a standard user provision an aws cluster with the following template.
- Ami: ami-0f3d6c27d7ba5006e
- disk size: 40 GB
- SSH user: ec2-user
- docker install url: None
3. upgrade rancher to 2.6.3-rc4 using a helm command.
- `helm upgrade rancher rancher-latest/rancher --version 2.6.3-rc4 --namespace cattle-system --set hostname=server --set ingress.tls.source=secret --set bootstrapPassword=admin`
4. Select All Namespaces in the Namespace selector
5. navigate to your rhel cluster --> workloads, then scroll to "Namespace: cattle-system"

**Result**
"cattle-cluster-agent" is stuck in "updating" status. 
The pods have the following errors. 
`Containers with unready status: [cluster-register]`

Viewing the logs of the pods you will see: 

`level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get \"https:/\": x509: certificate signed by unknown authority"`

**Expected Result**
After upgrading all resources should become active

**Screenshots**

Deployments
<img width="1792" alt="DeploymentsUpdatingCattleClusterAgent" src="https://user-images.githubusercontent.com/89411550/144953139-ff35a9d7-8496-4faa-816c-0a878821cb84.png">

Failure
<img width="1792" alt="RhelAgentFailureCrashLoopBackOff" src="https://user-images.githubusercontent.com/89411550/144953292-3fe3f5e1-c956-4eee-adb2-978df0ef2e7e.png">

Pods
<img width="1792" alt="Pods" src="https://user-images.githubusercontent.com/89411550/144953191-b7877157-9642-4640-a29d-b54c9711592a.png">

Pods recent Events
<img width="1792" alt="PodRecentEvents" src="https://user-images.githubusercontent.com/89411550/144953232-714d0615-5412-4715-bb22-d1e62097416c.png">

**Additional context**

**Comment by superseb** [comment]
@Auston-Ivison-Suse Can you share the full log and/or share the setup?

**Comment by Auston-Ivison-Suse** [comment]
@superseb Looks like I had used self signed and my helm command was trying to run `--set ingress.tls.source=secret` as part of the command was the issue. This is a non issue.

**Comment by Auston-Ivison-Suse** [comment]
**Rancher Validation Setup**
- Rancher version: 2.6.2 (upgraded to 2.6.3-rc4 later)
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version: v1.21.6-rancher1-2
- Cluster Type (Local/Downstream): Rke1
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
     - rhel-8.4-docker-20.10.7-selinux-on-rpm - ami-0f3d6c27d7ba5006e (3 workers, 3 etcd, 1 control plane) 

**Describe the bug**

Cattle-cluster-agent gets stuck updating, with a status "Deployment does not have minimum availability" 

**Validation steps**
1. Have a 2.6.2 HA setup (3 nodes) 
2. As a standard user provision an aws cluster with the following template.
- Ami: ami-0f3d6c27d7ba5006e
- disk size: 40 GB
- SSH user: ec2-user
- docker install url: None
3. upgrade rancher to 2.6.3-rc4 using a helm command.
- `helm upgrade rancher rancher-latest/rancher --version 2.6.3-rc4 --namespace cattle-system --set hostname=server  --set bootstrapPassword=admin`
4. Select All Namespaces in the Namespace selector
5. navigate to your rhel cluster --> workloads, then scroll to "Namespace: cattle-system"


**Result**
Cluster provisions correctly, I simply entered the wrong command for the upgrade.
