### ISSUE TITLE
UI - "Add Container" option missing in host view when Network Agent is deleted and purged.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3578]
Server version - V0.58.0-rc2

On a host that has few containers running , delete Network Agent instance.
Wait for Network Agent instance to be purged.
"Add Container" option missing in host view when Network Agent is deleted and purged.
<img width="298" alt="screen shot 2016-02-10 at 11 24 58 am" src="https://cloud.githubusercontent.com/assets/4266958/12958939/f7aac5de-cfe8-11e5-9a4f-e534bacdd475.png">

**Comment by tfiduccia** [comment]
version - master 2/11
Verified fixed
