### ISSUE TITLE
[UI] 

### ISSUE THREAD

**Issue by Cryptnym** [rancher/rancher#35787]
Let me say to start, i'm a complete noob at this.
Please forgive my lack of knowledge...

The problem is im no longer able to access rancher UI, this is a recent occurrence, because i was able to access it within the last month and I've made no changes since.

Information i can provide now:
OS : Ubuntu 18.04 LTS
running ~$: docker version 19.03.13/20.10.11 ( two versions displayed)
Not sure what version of rancher is installed since I can't access it and don't know how to find it on ssh.
Since im able to access all my other containers and everything is still working, i can only assume its a problem with Rancher but im not able manage anything anymore.

Some help would be appreciated getting it working again.

**Comment by cbron** [comment]
Please provide more info from the original template, including rancher version. If this is docker install you can do `docker ps`. 
```
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
<!--
* Custom = Running a docker command on a node
* Imported = Running kubectl apply onto an existing k8s cluster 
* Hosted = EKS, GKE, AKS, etc
 * Infrastructure Provider = Rancher provisioning the nodes using different node drivers (e.g. AWS, Digital Ocean, etc)
-->

**Describe the bug**
<!--A clear and concise description of what the bug is.-->

**To Reproduce**
<!--Steps to reproduce the behavior--> 

**Result**

**Expected Result**
<!--A clear and concise description of what you expected to happen.-->

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem.-->

**Additional context**
<!--Add any other context about the problem here.-->
```

**Comment by Cryptnym** [comment]
> Please provide more info from the original template, including rancher version. If this is docker install you can do `docker ps`.
> 
> ```
> **Rancher Server Setup**
> - Rancher version:
> - Installation option (Docker install/Helm Chart):
>    - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
> - Proxy/Cert Details:
> 
> **Information about the Cluster**
> - Kubernetes version:
> - Cluster Type (Local/Downstream):
>    - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
> 
> 
> **Describe the bug**
> 
> 
> **To Reproduce**
>  
> 
> **Result**
> 
> **Expected Result**
> 
> 
> **Screenshots**
> 
> 
> **Additional context**
> 
> ```

~$ docker ps
CONTAINER ID   IMAGE                                  COMMAND                  CREATED         STATUS                          PORTS                                      NAMES
3e090ec95a4c   rancher/metrics-server                 "/metrics-server --k…"   34 hours ago    Up 34 hours                                                                k8s_metrics-server_metrics-server-8449844bf-8x76k_kube-system_8ea4dcc7-d84d-45b4-8040-d0eb63e3b6cd_5
53a71f937a92   linuxserver/plex                       "/init"                  34 hours ago    Up 34 hours                                                                k8s_plex_plex-748b9d5957-ljcgh_default_d1c88df0-63e1-4461-a63b-6193b5cfac85_2
9114b4323a2f   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_metrics-server-8449844bf-8x76k_kube-system_8ea4dcc7-d84d-45b4-8040-d0eb63e3b6cd_5
114431c398c9   linuxserver/qbittorrent                "/init"                  34 hours ago    Up 34 hours                                                                k8s_qbittorrent-movies_qbittorrent-movies-59f4c9dbdc-7nt26_default_cf9a024a-9e4c-4f3d-bc40-6b848ddce925_2
1837ea8ecd00   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_plex-748b9d5957-ljcgh_default_d1c88df0-63e1-4461-a63b-6193b5cfac85_2
e5fe0af95673   linuxserver/qbittorrent                "/init"                  34 hours ago    Up 34 hours                                                                k8s_qbittorrent-tv_qbittorrent-tv-fc876b44-znthl_default_3f3a8f44-ea21-44f3-bf4b-705580ec4369_2
d93814e87c7d   0bfefe9f649b                           "/opt/bin/flanneld -…"   34 hours ago    Up 34 hours                                                                k8s_kube-flannel_canal-qn84k_kube-system_61cdd15f-75f1-486e-bf5f-fd2dc169b0db_7
fe9aaca9da1a   bfe3a36ebd25                           "/coredns -conf /etc…"   34 hours ago    Up 34 hours                                                                k8s_coredns_coredns-6f85d5fb88-mswqn_kube-system_c91b7d59-34c1-4eaa-8e57-cb1567788a8d_5
193ab0b49454   0f351f210d5e                           "start_runit"            34 hours ago    Up 34 hours                                                                k8s_calico-node_canal-qn84k_kube-system_61cdd15f-75f1-486e-bf5f-fd2dc169b0db_7
8c6712b8ddef   linuxserver/radarr                     "/init"                  34 hours ago    Up 34 hours                                                                k8s_radarr_radarr-77fdf6bf5d-9fkll_default_40732dc6-a53d-4ea6-9948-1f8b1be59cd4_2
0f1483fdc19b   b5af743e5984                           "/server"                34 hours ago    Up 34 hours                                                                k8s_default-http-backend_default-http-backend-65dd5949d9-tlm6v_ingress-nginx_1aa5e7fe-e94e-4013-922b-b39acd6a5fce_5
8ac02e0c2da7   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_qbittorrent-movies-59f4c9dbdc-7nt26_default_cf9a024a-9e4c-4f3d-bc40-6b848ddce925_3
c507a9d9120a   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_coredns-6f85d5fb88-mswqn_kube-system_c91b7d59-34c1-4eaa-8e57-cb1567788a8d_6
5eca38e8c3d9   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_qbittorrent-tv-fc876b44-znthl_default_3f3a8f44-ea21-44f3-bf4b-705580ec4369_2
df3232512d61   linuxserver/jackett                    "/init"                  34 hours ago    Up 34 hours                                                                k8s_jackett_jackett-6979d69c55-vnj66_default_e0ed4196-401a-4ee7-b69f-14aead2e815e_2
73412d087cce   4f1064cf7caf                           "/cluster-proportion…"   34 hours ago    Up 34 hours                                                                k8s_autoscaler_coredns-autoscaler-79599b9dc6-64z7n_kube-system_e88fc1dd-9086-4755-b301-2e3297741731_5
d53d2ec12ae2   5c265e1df972                           "fleetagent"             34 hours ago    Up 34 hours                                                                k8s_fleet-agent_fleet-agent-76fc77855-csnkh_fleet-system_d94a37fb-c713-42c5-aed9-ff0d66a17d7d_22
ebcf44ae83ab   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_radarr-77fdf6bf5d-9fkll_default_40732dc6-a53d-4ea6-9948-1f8b1be59cd4_2
c877306de1f6   03feeb39a75a                           "/usr/bin/kube-contr…"   34 hours ago    Up 34 hours                                                                k8s_calico-kube-controllers_calico-kube-controllers-649b7b795b-df9zq_kube-system_8a45900a-16a2-41e9-9151-b5aa43feba1a_7
d1ed13bfafbf   linuxserver/sonarr                     "/init"                  34 hours ago    Up 34 hours                                                                k8s_sonarr_sonarr-79469d4997-4p8lz_default_04fbb862-460d-44cd-80e7-7e7db720653b_2
af94892f1b6c   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_jackett-6979d69c55-vnj66_default_e0ed4196-401a-4ee7-b69f-14aead2e815e_2
b343617a7d3d   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_cattle-cluster-agent-77f885dd6-tt8rl_cattle-system_2bb559c6-eab4-4ace-916c-6f3688a019fd_13
178b5336b327   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_default-http-backend-65dd5949d9-tlm6v_ingress-nginx_1aa5e7fe-e94e-4013-922b-b39acd6a5fce_5
f11cdfeb5cfb   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_coredns-autoscaler-79599b9dc6-64z7n_kube-system_e88fc1dd-9086-4755-b301-2e3297741731_5
85aa4b13c93b   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_fleet-agent-76fc77855-csnkh_fleet-system_d94a37fb-c713-42c5-aed9-ff0d66a17d7d_6
1ffe5927d129   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_calico-kube-controllers-649b7b795b-df9zq_kube-system_8a45900a-16a2-41e9-9151-b5aa43feba1a_13
17c771d418af   96148b821282                           "/bin/sh -c 'kube-ap…"   34 hours ago    Up 34 hours                                                                k8s_kube-api-auth_kube-api-auth-xgcm2_cattle-system_21008783-c49e-4273-972e-c0b21da9fa7f_7
fa8cbe4e7ae9   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_sonarr-79469d4997-4p8lz_default_04fbb862-460d-44cd-80e7-7e7db720653b_2
3871a88c6ed1   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_canal-qn84k_kube-system_61cdd15f-75f1-486e-bf5f-fd2dc169b0db_7
5fbc1ea5b362   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_cattle-node-agent-djzv6_cattle-system_44d3ba5d-e134-4baa-b752-c440e5482537_7
0c6ead1510ec   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_nginx-ingress-controller-xrkd8_ingress-nginx_9197876a-dffb-4fed-9329-b68352f548a7_7
8f407b0d8102   rancher/pause:3.2                      "/pause"                 34 hours ago    Up 34 hours                                                                k8s_POD_kube-api-auth-xgcm2_cattle-system_21008783-c49e-4273-972e-c0b21da9fa7f_7
873964b8d051   rancher/rancher-agent:v2.5.2           "run.sh --server htt…"   34 hours ago    Restarting (1) 37 seconds ago                                              sharp_mclean
43a6b6b0a0a4   rancher/rancher-agent:v2.5.2           "run.sh --server htt…"   34 hours ago    Restarting (1) 37 seconds ago                                              flamboyant_rosalind
07e73d3e0cdb   rancher/hyperkube:v1.19.4-rancher1     "/opt/rke-tools/entr…"   12 months ago   Up 34 hours                                                                kube-proxy
1d5ca7b21181   rancher/hyperkube:v1.19.4-rancher1     "/opt/rke-tools/entr…"   12 months ago   Up 34 hours                                                                kubelet
6f546c2e4105   rancher/hyperkube:v1.19.4-rancher1     "/opt/rke-tools/entr…"   12 months ago   Up 34 hours                                                                kube-scheduler
1aae97d34395   rancher/hyperkube:v1.19.4-rancher1     "/opt/rke-tools/entr…"   12 months ago   Up 34 hours                                                                kube-controller-manager
2204dd2dfb3a   rancher/hyperkube:v1.19.4-rancher1     "/opt/rke-tools/entr…"   12 months ago   Up 34 hours                                                                kube-apiserver
3bab74b76cf8   rancher/coreos-etcd:v3.4.13-rancher1   "/usr/local/bin/etcd…"   12 months ago   Up 34 hours                                                                etcd
337297b0cd1a   rancher/rancher                        "entrypoint.sh"          12 months ago   Up 34 hours                     0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   trusting_golick

**Comment by cbron** [comment]
The agent is restarting, you're going to need to check logs there. Also there is a ton of other stuff going on that you'd need to filter through. Issues in rancher/rancher are meant for bugs or feature requests, but as this is a generic support request you would be better off asking for help in our user slack channel. Thanks.

**Comment by Cryptnym** [comment]
How do i check the logs?
