### ISSUE TITLE
[Intermittent] Machines not deleted for provisioned RKE2 clusters

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#35795]
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart): Docker install and Rancher Desktop
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): K3S
- Proxy/Cert Details: None

**Describe the bug**
Deleting a provisioned RKE2 cluster from Rancher may hang waiting for a machine to delete.

**To Reproduce**
1. Provision an RKE2 cluster
2. Wait for said cluster to become active
3. Delete said cluster

**Result**
The delete may hang waiting for a machine to delete

**Expected Result**
The cluster should be successfully deleted.

**Additional context**
The job to delete the infrastructure gets created by the `machineprovision` controller, but the job doesn't do anything. There are no pods created and no events on the job. With this context, it seems to me that this may be a problem with K3S (the local cluster) because if the job gets created successfully, then Kubernetes should create the pods for the job.

One other thing is: at the time of this writing, jobs and secrets are leftover when a cluster is successfully deleted. These jobs and secrets don't affect anything Rancher does (they will be recreated when a new cluster of the same name is created), but their existence may be affecting this issue. This is unlikely, but it may be something to investigate.

**Comment by thedadams** [comment]
There is a workaround for this problem. If a machine get stuck in the deleting state:
1. Find the infrastructure machine object related to the machine. It is on the machine object as `spec.infrastructureRef`
2. Delete the job associated with this infrastructure machine. It will be in the same namespace and its name will be the name of the infrastructure object with `machine-provision` appended.
3. Add a dummy annotation to the infrastructure object. This will cause the infrastructure object to go back through the controllers and the job will be recreated. It is unlikely that the job will hang when it is created a second time.

**Comment by thedadams** [comment]
### Root cause
The root cause here was the deletion job was getting created and then modified too quickly for Kubernetes. The reason for the modification was a secret that is not needed for deletion was getting deleted.

### What was fixed, or what changes have occurred
The secret that is not needed for deletion is left out of the Job spec on delete.

### Areas or cases that should be tested
None, as long as deletion of the machines is successful.

### What areas could experience regressions?
Deletion of RKE2/K3S machines only.

### Are the repro steps accurate/minimal?
Yes.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 4d41423
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke2 aws node driver

----------

### Testing: ###

Tested this issue with the following steps

On K3s Rancher Server
1. Provision an RKE2 cluster
2. Wait for said cluster to become active
3. Delete said cluster


**Result** - Pass

Deleting cluster also deletes all the node machines
![image.png](https://zube.io/files/rancher/fa7eed68e8d9772f0d5e6794d9dd4020-image.png)
