### ISSUE TITLE
helm upgrade of rancher server from 2.6.2 to 2.6.3-rc4 errored out when rancher backup is taken with fleet git repos created

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35796]
Information about the Cluster 
**Rancher Server Setup**
- Rancher version: v2.6.2 --> 2.6.3-rc4
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.21.6, 1.3.2
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.21.6-rancher1-1
- Cluster Type (Local/Downstream): `Local cluster RKE1`

**Describe the bug**
After upgrading my rancher server from 2.6.2 to 2.6.3-rc4, the upgrade errored out.

**To Reproduce**
1. create a rancher server on v2.6.2
2. Created 2 downstream cluster node driver RKE1 and RKE2
3. Install rancher-backup operator in the local cluster 
4. From continuous delivery --> add a git repo URL `https://github.com/rancher/fleet-examples` and in the path add `multi-cluster/helm`
5. Verify the apps are installed in the downstream clusters.
6. Upgraded rancher server to the version v2.6.3-rc4 via helm
```
helm upgrade rancher rancher-latest/rancher -n cattle-system --version 2.6.3-rc4 --set hostname=<redacted> --kubeconfig newkube
```

**Result**
Upgrade failed but the rancher server has come up active. No errors in the rancher pods and all the services are up.
Rancher server came up active and all the cluster-agents were upgraded to `v2.6.3-rc4`
rancher app in local --> apps & market goes to failed state

```
Error: UPGRADE FAILED: could not get information about the resource: an error on the server (“context canceled”) has prevented the request from succeeding (get ingresses.networking.k8s.io rancher)
```

**Expected Result**

- Expected the upgrade to go through without any errors.
- I have upgraded two other rancher servers and did not hit this issue.

**Screenshots**
<img width="500" alt="Screen Shot 2021-12-07 at 3 36 34 PM" src="https://user-images.githubusercontent.com/38144301/145122513-dc20b11a-3f2d-4d37-888f-a0a698cda451.png">

Resources in the app do not show up but all the resources are active.
Installed a few apps in the downstream clusters and all the installations went through fine without any error.

**Comment by kinarashah** [comment]
Looked at the setup with @anupama2501 and @sowmyav27, didn't find any other errors or anything else wrong with the local cluster. All resources including ingress were active and running. 
Can keep this issue open in case anyone else runs into it, but as @anupama2501 mentioned - this wasn't seen in other upgraded rancher setups so not going to actively work on this issue for now.

**Comment by anupama2501** [comment]
@kinarashah I ran into this issue twice yesterday. It happens when I have a rancher backup taken after a git repo was created to install apps in multiple downstream clusters

**Comment by cbron** [comment]
Reproduced when making fleet gitrepo and then taking rancher backup, though we don't think its actually related to fleet itself, more likely its around ingress.

**Comment by anupama2501** [comment]
Verified by upgrading rancher from 2.6.2 --> 2.6-head e62e1ae

- Install rancher-backup operator in the local cluster
- From continuous delivery --> add a git repo URL https://github.com/rancher/fleet-examples and in the path add multi-cluster/helm
- Verify the apps are installed in the downstream clusters and took a backup.
- Upgraded rancher server to the version v2.6-head and upgrade was successful

`helm upgrade rancher rancher-latest/rancher -n cattle-system --version 2.6.3-rc4 --set hostname=<redacted> --kubeconfig newkube --set rancherImageTag=v2.6-head`
