### ISSUE TITLE
Endpoints URL for workloads points to node IP address instead of the name in the Ingress

### ISSUE THREAD

**Issue by shubb30** [rancher/rancher#35815]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke v1.3.1, k8s 1.20.11
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:  1.20.11
- Cluster Type (Local/Downstream): Local

**Describe the bug**
When creating an Ingress, the URL under the "Endpoints" column in the "Workloads" view, will show the IP address of one of the nodes, instead of the hostname defined in the Ingress.  In Rancher 2.5 and lower, the workload would have the correct link to the name defined in the Ingress.

**To Reproduce**
Create a workload, and then create an Ingress that points to the workload.  Configure a `host` with a name, and add an SSL certificate.

**Result**
The URL for the `443/HTTPS` link in the `Endpoints` column points to the IP address of the first node in the cluster, not the hostname that I configured for the Ingress.  This causes the link to not be useful, since the page you get is the `default 404`.

**Expected Result**
The URL for the `443/HTTPS` link in the `Endpoints` column to be the host I configured in the ingress, not the IP address of the first node in the cluster.

**Screenshots**
![endpoint-url](https://user-images.githubusercontent.com/967153/145293869-34e3dd17-5575-4a63-96cf-07633708120c.jpg)

**Additional context**
Happens whether created from the UI, or via Terraform.

**Comment by vasyakrg** [comment]
me too.

if loadbalacer in ingress = hostname, url = http://:443
but, if loadbalancer = list of ip's, url = http://<first_ip>:443

**Comment by shubb30** [comment]
Please reopen since this is still an issue
