### ISSUE TITLE
Chart Repositories are not showing up on Rancher v2.5-head

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#35820]
**Rancher Server Setup**
- Rancher version:v2.5-head (6ff6d08)
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:Selfsigned

**Information about the Cluster**
- Kubernetes version:v1.20.13-rancher1-1
- Cluster Type (Local/Downstream): Downstream 1CP, 1 ETCD, 2 Worker nodes

**Describe the bug**

Chart Repositories are not showing up on Rancher v2.5-head

**To Reproduce**
 
Create a downstream AWS node driver cluster with 2 Worker, 1 ETCD, 1 CP

**Result**
Navigate to Apps and Market Place of **Downstream Cluster** ---> Chart Repositories ---> We don't see any chart repositories listed.
If we try to create chart repositories manually, the chart repos remains in **"In Progress"** state.

**Rancher doesn't show any error in log when we add chart repositories manually.**

**Expected Result**

1. Pre-configured Partners and Rancher chart repositories are listed and in **Active** state.
2. We should be able to create new chart repositories.

**Screenshots**
Rancher doesn't show any error in log when we added chart repositories manually.
![Screenshot from 2021-12-08 17-21-14](https://user-images.githubusercontent.com/83208989/145334204-6e22b2ea-5225-4bc9-a4a9-8e28285d906f.png)

**Comment by vivek-infracloud** [comment]
### Validated the issue again. Results are as follows.
On rancher v2.5-head
- Chart repos are visible on local cluster.
- Chart repos are **not visible** on downstream cluster and custom cluster.

On rancher v2.6.2 and v2.6-head
- Chart repos are visible on both local and downstream cluster.

This problem doesn't seems to be related to downtime for chart repos. Need to explore the bug/issue in detail.

**Comment by ronhorton** [comment]
**PASS** Charts are back as of `2.5-head Commit ID 9dab145`
1. created downstream cluster
2. clicked 'explore' 
3. clicked 'Apps & Marketplace'

- Charts are available. 
- Installed apps are correctly showing 3
- Chart repositories created (2)
- Successfully installed Logging v2 for a smoke test
<img width="1277" alt="Screen Shot 2021-12-21 at 4 32 43 PM" src="https://user-images.githubusercontent.com/89212856/147000638-a0ba5ee5-908a-493d-9dcb-c75c28075b33.png">

**Comment by sowmyav27** [comment]
Reopening to test few more scenarios around hosted Rancher

- 2.5-head Hosted Rancher managing 2.5-head downstream Rancher
- Hosted Rancher upgraded to 2.5-head still can manage 2.5.11 downstream Rancher
- Hosted Rancher at 2.5.11 can still manage a downstream Rancher upgraded to 2.5-head
- Hosted Rancher at 2.5.11 can successfully add and manage a 2.5-head downstream Rancher

**Comment by rishabhmsra** [comment]
Could not verify the hosted rancher scenarios as `rancher-v3_ha_deploy` jenkins job is getting stuck. It did not complete even after running for an hour. 

Validation steps:
1) Created k3s ha setup using `rancher_v3_create_k3s_ha_cluster` jenkins job.
2) Encoded the kubeconfig to base64
3) Passed the encoded kubeconfig in `RANCHER_HA_KUBECONFIG` parameter in `rancher-v3_ha_deploy` jenkins job and it's getting stuck with below logs:

```
13:23:03.343  run cmd: 	rke -v | cut -d " " -f 3
13:23:03.343  return code: 	0
13:23:03.343  RKE VERSION: v1.2.14
13:23:03.343  run cmd: 	export KUBECONFIG=/src/rancher-validation/tests/v3_api/resource/kube_config_cluster-ha-filled.yml && kubectl version --short | grep -i server | cut -d " " -f 3
13:23:03.343  return code: 	0
13:23:03.343  KUBERNETES VERSION: v1.21.7+k3s1
13:23:03.343  run cmd: 	export KUBECONFIG=/src/rancher-validation/tests/v3_api/resource/kube_config_cluster-ha-filled.yml && kubectl -n ingress-nginx rollout status ds/nginx-ingress-controller
13:23:03.359  return code: 	1
13:23:03.359  output: 	b'Error from server (NotFound): namespaces "ingress-nginx" not found\n'
13:23:03.360  run cmd: 	export KUBECONFIG=/src/rancher-validation/tests/v3_api/resource/kube_config_cluster-ha-filled.yml && kubectl -n ingress-nginx wait --for=condition=complete job/ingress-nginx-admission-create
13:23:03.360  return code: 	1
13:23:03.360  output: 	b'Error from server (NotFound): namespaces "ingress-nginx" not found\n'
```

**Comment by sowmyav27** [comment]
**On 2.5.12-rc1, verified the following**

Deploy Hosted Rancher on 2.5.12-rc1 and Tenant rancher on 2.5.12-rc2

- Chart repositories are available on Tenant Rancher cluster and on Downstream clusters on Tenant rancher servers
- Was able to deploy Monitoring v1 on Tenant Rancher and Downstream cluster on Tenant rancher. And deployed CIS v2 on both these clusters
- Deployed monitoring v2 on local cluster of Hosted Rancher.

**Comment by vivek-infracloud** [comment]
###  Hosted Rancher upgraded to 2.5-head still can manage 2.5.11 downstream Rancher

- Created k3s `v1.20.13+k3s1` HA cluster and deployed a rancher 2.5.11 on it.
- Imported a k3s HA cluster on k8s version `v1.20.13+k3s1` and deployed rancher 2.5.11 on it.
- Deployed a downstream cluster on tenant rancher.
- Installed monitoring v2 on the local and tenant clusters and downstream cluster.
  - validated the monitoring metrics.
-  Upgrade Hosted rancher to `v2.5.12-rc1`
- Validated the monitoring metrics. Metrics looks good.
- Validated if chart repo is accessible. 
- Deployed downstream cluster on tenant rancher again and made sure chart repo is accessible.

**Comment by vivek-infracloud** [comment]
- Deployed a hosted rancher on 2.5.11 - k3s v1.20.13+k3s1
- Imported a k3s HA cluster on k8s version v1.20.13+k3s1 and deploy rancher 2.5.11 on it --> Tenant rancher
- Deployed a downstream cluster on tenant rancher
- Installed monitoring v2 on the local and tenant clusters and downstream cluster
- Upgrade Hosted rancher (main rancher server) to 2.5.12-rc1 (using the kubeconfig from Jenkins job)

Results:

**On host rancher (rancher v2.5.11)**
- Monitoring looks good on local cluster.
- However, on imported cluster the monitoring is not stable. The monitoring spiral chart is not visible.

**On host rancher upgraded to v2.5.12-rc1**
- The "Monitoring API is not ready" error shows up after v2.5.12-rc1 upgrade on local cluster.
- The monitoring on imported cluster is unstable. Either "Monitoring API is not ready" error shows or the monitoring graphs are not visible although all the pods are in active. 

**On tenant rancher**
- The monitoring on local cluster is unstable. Either "Monitoring API is not ready" error shows or the monitoring graphs are not visible although all the pods are in active. 
- The monitoring on downstream looks good.

**Comment by sowmyav27** [comment]
Tracking monitoring issue in another GH ticket. Closing this one as all validations are complete.
