### ISSUE TITLE
Currently I cannot connect to my service links

### ISSUE THREAD

**Issue by MarcusSjolin** [rancher/rancher#3582]
It is not possible for me to connect to the service link at the moment.

I have got a set up with 3 Rancher hosts they are all alike, however 1 get is online 24/7 and 2 spawns in the morning and shut down in the evening. A few days back around when I upgraded to 0.56.1 I experienced issues with spawning Jenkins agents on my 2 daily spawned hosts. These try to connect to master:8080 and master refers to Jenkins master instance. This however doesn't work. When I log onto the 24/7 host it works just fine, but the two other hosts have no connectivity, although they can resolve the host master to an ip.

These servers are hosted in AWS and have the same settings and bootup sequence.

I am running 
Rancher 0.56.1
Rancher Agent 0.82.0

/Marcus

**Comment by MarcusSjolin** [comment]
I have two issues apparently, one being Jenkins API doesn't work so I cannot create a JNLP entry (off topic), however if I re-point my access to the ip of the Jenkins Master instead of the Service Link host name it works fine.

http://master:8080/ (internal docker service link) -> http://jenkins.company.com/ (internally available)

I am unable to ping master as well as wget/curl the url, it just can't connect.

**Comment by deniseschannon** [comment]
When your hosts spawn in the morning, have you confirmed their cross host communication is working? Can you exec into the network agent on the 24/7 host and try to ping the Rancher managed IP of the network agent (i.e. `ping 10.42.x.x`) on one of the newly spawned hosts?

**Comment by deniseschannon** [comment]
@MarcusSjolin Please re-open if you are able to provide more details on your setup based on the questions I had asked.
