### ISSUE TITLE
VMware Cluster Autoscaler

### ISSUE THREAD

**Issue by eminalemdar** [rancher/rancher#35827]
**Cluster Autoscaler on VMware Environments**
Other Kubernetes Management Platforms like Anthos uses a custom solution for Cluster Autoscaling on on-prem VMware environments. But with Rancher, we can only use the Kubernetes Cluster Autoscaling solution and that Cluster Autoscaler does not support VMware as a Provider.

**Custom Solution for VMware Environments**
It would be perfect if there is a solution for this problem we wouldn't have to use some other third party solutions for autoscaling or use some third party pre-scaling solutions.

**Alternatives**
Anthos Cluster Autoscaler: https://cloud.google.com/anthos/clusters/docs/on-prem/1.8/concepts/cluster-autoscaler
VMware Tanzu Cluster Autoscaler: https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.2/vmware-tanzu-kubernetes-grid-12/GUID-tanzu-k8s-clusters-scale-cluster.html#enable-autoscaler

**Comment by finkr** [comment]
Any plans on this issue ?

for information the cluster-autoscaler [FAQ](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) list the supported cloud provider.

**Comment by James-Laming** [comment]
Would also be interested in a solution for VMware based enviroments
