### ISSUE TITLE
vSphere CPI does not have correct tolerations 

### ISSUE THREAD

**Issue by bmayfi3ld** [rancher/rancher#35835]
**Rancher Server Setup**
- Rancher version:
- 2.6.2
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
   - Helm Chart, RKE1
- Proxy/Cert Details:
- Self Signed CA

**Information about the Cluster**
- Kubernetes version:
- v1.21.6
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

Downstream, Custom, on RHEL7 hosts, hosts are in vSphere

**Describe the bug**

These are the taints that were placed on my controlplane nodes.

Taints:             node-role.kubernetes.io/etcd=true:NoExecute
                    node-role.kubernetes.io/controlplane=true:NoSchedule

The Apps & Marketplace chart for vSphere CPI only includes tolerations for etcd of NoSchedule, so no pods were started.
This is what the helm chart installs
  - effect: NoSchedule
    key: node-role.kubernetes.io/etcd
    value: "true"

**To Reproduce**
 
Have a node for a imported cluster running v1.21.6. Note that the taint on the etcd role is NoExecute.
Install the vSphere CPI app from the apps and marketplace. 

**Result**
No pods for the CPI are running.

**Expected Result**

A pod is running on each of the controlplane nodes.

**Screenshots**

**Additional context**

**Comment by neni84** [comment]
I have same problem, Vspere7u2, cluster rke1 k8s=1.21.6 + rancher 2.6.2.
No pods for the CPI are running.

**Comment by bmayfi3ld** [comment]
As a workaround for now you can go into the Daemonset that the helm chart installs and change

effect: NoSchedule
key: node-role.kubernetes.io/etcd
value: "true"

to 

effect: NoExecute
key: node-role.kubernetes.io/etcd
value: "true"

**Comment by Tejeev** [comment]
fixed by: https://github.com/rancher/charts/pull/1694
