### ISSUE TITLE
external-dns provider for powerdns api

### ISSUE THREAD

**Issue by ingardm** [rancher/rancher#3583]
It would be nice if the external-dns service could support some commonly used internal dns servers like powerdns.

**Comment by taketnoi** [comment]
+1

**Comment by vincent99** [comment]
This is a fine idea but not of any immediate use to us or paying customers (that I know of) so it would fall into the "PRs accepted" category.  We're happy to help if someone has questions on integrating an implementation into external-dns.

**Comment by JayBeeDe** [comment]
That could be a great idea thx ingardm

**Comment by fuhbar** [comment]
This seems to be implemented by @jgreat and merged in 3 month ago via [PR#40](https://github.com/rancher/external-dns/pull/40) by @alena1108. 

@vincent99 This issue can be closed, I think.
