### ISSUE TITLE
The IP addresses didn't match within rancher and aws/ec2 after provisioning causing nodes to be unvailable

### ISSUE THREAD

**Issue by Auston-Ivison-Suse** [rancher/rancher#35833]
**Rancher Server Setup**
- Rancher version: v2.6-head(0d14421)
- Installation option (Docker install/Helm Chart):Docker
- Proxy/Cert Details:self-signed

**Information about the Cluster**
- Kubernetes version: v1.22.4
- Cluster Type (Local/Downstream):Downstream/Amazon Ec2/RKE1
- Nodes: 1 etcd, 1 control plane, 4 workers
- Worker nodes have taints set to `qa=test`

**Describe the bug**
When provisioning a cluster and you get to the step of adding a node template, create one specifically for workers. Within that template add taints. This is the only "irregular" step I took while provisioning a cluster and witnessed 2 workers go unavailable and never recover.

**IMPORTANT NOTES**

I was debugging and noticed that two IP addresses didn't match from the active ec2 instances and two worker nodes. 

**To Reproduce**
1. When you get to the point of selecting the node template create one for the worker nodes.
2. Within the worker node template go to the taints section and add "qa=test:noschedule"
3. Finish configuring cluster and click "create"

**Result**
The cluster brought up 2 nodes that are listed as unavailable.

**Expected Result**
Provisioning should complete successfully and all nodes should be active. 

**Screenshots**
Screenshot of one of the nodes in an unavailable state
<img width="1792" alt="NodeKubletStopped" src="https://user-images.githubusercontent.com/89411550/145450741-75a0186e-191b-41dc-8101-b876dcd1d93b.png">

Screenshot of taint set within node template
<img width="1792" alt="TaintNodeTemplate" src="https://user-images.githubusercontent.com/89411550/145450909-93a2cb33-68a1-4f73-9aee-2e795a989e5e.png">

Rancher Logs:
[LogsForTaintBlowingUpCluster.txt](https://github.com/rancher/rancher/files/7687471/LogsForTaintBlowingUpCluster.txt)

r.

**Comment by sowmyav27** [comment]
Could be similar to this one - https://github.com/rancher/rancher/issues/31772

**Comment by annablender** [comment]
Investigated issue last Friday and Monday. Issue was found to be different than original issue, workaround and discussion is documented https://confluence.suse.com/pages/viewpage.action?pageId=894796383. Rancher machine needs to be debugged on a live cluster.

**Comment by kinarashah** [comment]
Unable to reproduce the issue with v2.6-head (4ab776608650), pinged @Auston-Ivison-Suse to try reproducing it again. 

I made sure to create a separate template for worker nodes,  added a taint foo=bar:NoSchedule and confirmed that the taint showed up on worker nodes and that they were active after provisioning.

**Comment by Auston-Ivison-Suse** [comment]
I attempted to reproduce on the same version of rancher(v2.6-head (4ab776608650)) but was unable to. 

The issue itself is being closed, so we will just keep an eye out for anything similar in the future.
