### ISSUE TITLE
Support k8s 1.22 as default version

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#35840]
Following issues need to be closed for marking 1.22 as stable and default in Rancher v2.6.4: 

Team 2: 
- [x] https://github.com/rancher/rancher/issues/35639

Team 3: 
- [x] https://github.com/rancher/rancher/issues/35571 
- [ ] https://github.com/rancher/rancher/issues/33848 
- [ ] https://github.com/rancher/rancher/issues/35909

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/35571

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/33848

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/35909

**Comment by kinarashah** [comment]
Local k3s and etcd versions that were reverted as part of PR https://github.com/rancher/rancher/pull/35841 were introduced with https://github.com/rancher/rancher/pull/35723.

**Comment by slickwarren** [comment]
before closing this, we should also validate that 1.22 no longer shows as `experimental`

**Comment by sowmyav27** [comment]
Closing this as 1.22 is not listed as experimental anymore.
