### ISSUE TITLE
CIS v2: Add AKS as an option to run the CIS Scan

### ISSUE THREAD

**Issue by dhruvmewada15** [rancher/rancher#35844]
CIS v2:

- Should be able to run the kube-bench aks benchmark on an AKS cluster

The upstream kube-bench aks-1.0  should be added to the rancher/security-scan repo to be able to run the scan on the AKS cluster.

**Comment by dhruvmewada15** [comment]
How to Validate:

1. Rancher Server Version : v2.6.3
2. Create an downstream AKS Cluster.
3. Install `rancher-cis-benchmark:v2.0.3` from [dhruvmewada15/charts:add-aks-cis-benchmark](https://github.com/dhruvmewada15/charts/tree/add-aks-cis-benchmark) git repo branch with security-scan image: `rancher/security-scan:v0.2.6-rc1` on AKS Cluster.
4. Run the CIS Scan using `aks-profile`.

Expected Result:
The CIS Scan should be completed successfully and the tests should PASS.

> NOTE: Since this is a new functionality added, also check that CIS Scan functionality for other cluster types are not breaking. You can check this by running CIS Scan on rke1, rke2 and k3s cluster using rancher-cis-benchmark:v2.0.2 providing rancher/security-scan:v0.2.5 and observe the results. Then run the CIS Scan again by reinstalling rancher-cis-benchmark:v2.0.3 from git repo [dhruvmewada15/charts:add-aks-cis-benchmark](https://github.com/dhruvmewada15/charts/tree/add-aks-cis-benchmark) providing rancher/security-scan:v0.2.6-rc1 and the results of the CIS Scan should match.

**Comment by rishabhmsra** [comment]
**Rancher Server:**
- Version : v2.6.3
- Docker installation

**1) Validated AKS CIS scan using below steps :** 
- Created a downstream Azure AKS cluster with 3 worker nodes and k8s `v1.21.7` version.
- Apps and Marketplace -> Reppositories -> Added the git repo : https://github.com/dhruvmewada15/charts/tree/add-aks-cis-benchmark
- From added repo, installed the `rancher-cis-benchmark:v2.0.3` chart with security-scan image: `rancher/security-scan:v0.2.6-rc1`
- Ran the aks-profile scan it got passed.
![Screenshot from 2022-01-31 16-54-59](https://user-images.githubusercontent.com/36376154/151785670-579aa342-a752-443a-86f9-7ee14cfeed26.png)


**2) Validated existing scan functionality using below steps :**
- On rancher v2.6.3 provisioned aws node driver rke1, rke2 and k3s downstream clusters with 4 nodes `(1-cp, 1-etcd, 2-worker)`
  - rke1 : v1.21.8
  - rke2 : v1.21.8+rke2r2
  - k3s : v1.21.8+k3s2
- Installed the `rancher-cis-benchmark:v2.0.2` with `rancher/security-scan:v0.2.5`.
- Ran the 1.6 permissive profile scan on all the downstream cluster and observed the results.
- Apps and Marketplace -> Reppositories -> Added the git repo : https://github.com/dhruvmewada15/charts/tree/add-aks-cis-benchmark on all downstream clusters
- Re-installed the `rancher-cis-benchmark:v2.0.3` with `rancher/security-scan:v0.2.6-rc1` from the added repo on all downstream clusters.
- Ran the 1.6 permissive scan profile on all downstream clusters and observed the results.

**Results :**
- In Azure AKS cluster the chart got installed successfully and the CIS scan also got passed. Required validations passed
- For RKE1, RKE2 and K3s cluster the chart got installed successfully and the CIS scan results with both (`rancher-cis-benchmark:v2.0.2` with `rancher/security-scan:v0.2.5`) **and** (`rancher-cis-benchmark:v2.0.3` with `rancher/security-scan:v0.2.6-rc1`) are same, hence all the required validations passed.

**Comment by dhruvmewada15** [comment]
Hey @rishabhmsra Can you please test these changes again on 2.6-head with the same validation steps?

**Comment by rishabhmsra** [comment]
**Validated this again on rancher v2.6-head** 

**Rancher Server :**
- Version : v2.6-head (7efbeab)
- Docker installation

**1) Validated AKS CIS scan using below steps :**

- Created a downstream Azure AKS cluster with k8s `v1.22.4` version.
- Apps and Marketplace -> Reppositories -> Added the git repo : https://github.com/dhruvmewada15/charts/tree/add-aks-cis-benchmark
- From added repo, installed the `rancher-cis-benchmark:v2.0.3` chart with security-scan image: `rancher/security-scan:v0.2.6-rc1`
- Ran the aks-profile scan it got passed.

![Screenshot from 2022-02-01 18-01-11](https://user-images.githubusercontent.com/36376154/151970842-d9f455c5-e152-4b23-8dc7-c319118f3d91.png)


**2) Validated existing scan functionality using below steps :**

- On rancher v2.6-head provisioned aws node driver rke1, rke2 and k3s downstream clusters with `4 nodes (1-cp, 1-etcd, 2-worker)`
   - rke1 : v1.21.8
   - rke2 : v1.21.9+rke2r1
   - k3s : v1.21.9+k3s1
- Installed the `rancher-cis-benchmark:v2.0.2` with `rancher/security-scan:v0.2.5`.
- Ran the 1.6 permissive profile scan on all the downstream cluster and observed the results.
- Apps and Marketplace -> Reppositories -> Added the git repo : https://github.com/dhruvmewada15/charts/tree/add-aks-cis-benchmark on all downstream clusters
- Re-installed the `rancher-cis-benchmark:v2.0.3` with `rancher/security-scan:v0.2.6-rc1` from the added repo on all downstream clusters.
- Ran the 1.6 permissive scan profile on all downstream clusters and observed the results.

**Results :**
- In Azure AKS cluster the chart got installed successfully and the CIS scan also got passed. Required validations passed
- For RKE1, RKE2 and K3s cluster the chart got installed successfully and the CIS scan results with both (`rancher-cis-benchmark:v2.0.2` with `rancher/security-scan:v0.2.5`) **and** (`rancher-cis-benchmark:v2.0.3` with `rancher/security-scan:v0.2.6-rc1`) are same, hence all the required validations passed.
