### ISSUE TITLE
unable to provision cluster using k8s v1.21.7-rc2+rke2r3

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35867]
**Rancher Server Setup**
- Rancher version: v2.6.3-rc5
- Installation option (Docker install/Helm Chart):helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):rke1, v1.3.3-rc6
- Proxy/Cert Details:valid certs

**Information about the Cluster**
- Kubernetes version:1.21.7-rc2+rker3
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):custom, digital ocean

**Describe the bug**

when provisioning a custom cluster, rke2 nodes do not register.  it is stuck in `waiting for agent to checkin and apply plan`

**To Reproduce**
 
* deploy a custom cluster through rancher using rke2, version 1.21.7-rc2+rke2r3
* run the registration command (tested with a single node, all roles and 1 cp/etcd, 1worker node) on a node
* wait for the node to register

**Result**
* node  is stuck in `waiting for agent to checkin and apply plan`
* when checking logs on the node, rke2 is not starting

**Expected Result**

Expecting rke2 nodes to be able to register to an active state with rancher

**Additional context**
* tested with the old workaround of removing the chartValues section of the cluster.yaml as well as with default values for the cluster deployment. both seem to end up in the same state.

**Comment by annablender** [comment]
Unable to reproduce on v2.6-head rainbow cluster with k8s version v1.21.7+rke2r2 (rke2r3 was not available because it has been removed from the release KDM). This needs to be retested on k8s 1.21.8 for 2.6.4.

**Comment by snasovich** [comment]
Want to retest it in RKE2 v1.21.8, waiting for that release.

**Comment by snasovich** [comment]
v1.21.8 is available in 2.6 KDM as of 1/4/2022, so it should be ready for testing now.

**Comment by snasovich** [comment]
There is an issue with v1.21.8 RKE2/k3s (https://github.com/rancher/rancher/issues/36051), so sending back to waiting for RKE2 release.

**Comment by snasovich** [comment]
https://github.com/rancher/rancher/issues/36051 is back in test. This should no longer be reproducible with v1.21.8+rke2r2 or v1.21.9+rke2r1.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 11a7451
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke2 custom cluster version 1.21.8+rke2r2 and rke2 custom cluster version 1.21.9+rke2r1

----------

### Testing: ###

Tested this issue with the following steps:

1. Deploy a custom cluster through rancher using rke2, version v1.21.8+rke2r2 and v1.21.9+rke2r1
2. Run the registration command (tested with a single node, all roles and 1 cp/etcd, 1worker node) on a node
3. Wait for the node to register

**Result** - Pass

**v1.21.8+rke2r2**
![image.png](https://zube.io/files/rancher/3af23585707e57c565c39e0625d313df-image.png)

**v1.21.9+rke2r1**
![image.png](https://zube.io/files/rancher/a3e03cf7ad0316212137428ad0f4b28a-image.png)
