### ISSUE TITLE
Unhealthy and degraded states show up as green in the graph

### ISSUE THREAD

**Issue by raphink** [rancher/rancher#3587]
This is a screenshot of a stack using Rancher-server 0.56:

![screenshot from 2016-02-11 16 28 07](https://cloud.githubusercontent.com/assets/650430/12980364/75249294-d0dc-11e5-9ed8-22d5f5729dde.png)

It seems that the color for degraded/unhealthy is wrong.

**Comment by vincent99** [comment]
I don't know at what point this was fixed but it's working for me now...

![image](https://cloud.githubusercontent.com/assets/753917/13971625/d8a09bc4-f04e-11e5-8ab2-2d4a00a0a825.png) ![image](https://cloud.githubusercontent.com/assets/753917/13971627/daef2fee-f04e-11e5-85b9-5a84f63941c4.png) ![image](https://cloud.githubusercontent.com/assets/753917/13971628/de523960-f04e-11e5-9fb0-adc882643d5d.png)

**Comment by vincent99** [comment]
@tfiduccia To test you can create a service with scale=2, image=nginx, and a HTTP healthcheck that looks for `/ok` with "when unhealthy, take no action", 1 second interval, healthy/unhealthy threshold of 1.

Then exec into each container and `echo ok > /usr/share/nginx/html/ok` to make the check pass for that container, 
and `rm /usr/share/nginx/html/ok` to make it fail.

**Comment by tfiduccia** [comment]
Version - master 3/22
Verified fixed
