### ISSUE TITLE
how to run cattle without emberjs server if i want to modify ui

### ISSUE THREAD

**Issue by Jamlee** [rancher/rancher#3588]
i ran the cattle directly, it could generate ui automaticlly  in `index.html`  who load resource from  `release.rancher.com`   . but i can't find any ui code in cattle project.
i found that  `rancher/ui`  is able to proxy request to cattle, but i must run a emberjs server. it is too bad, The service need maintained.

As described above,  how to  run cattle with resource load from `localhost` instead of `release.rancher.com`

**Comment by vincent99** [comment]
The ember server is only intended for development.  The UI is entirely static content and is packaged in the Rancher release, but it can be loaded from a remote URL instead by changing a setting:  https://forums.rancher.com/t/how-can-i-customize-ui/1435/3?u=vincent

**Comment by Jamlee** [comment]
@vincent99 buddy, thanks for your anwser.

**Comment by deniseschannon** [comment]
@Jamlee If you have more questions, please re-open or create a new issue.
