### ISSUE TITLE
Hostnames should be RFC 1123 compatible

### ISSUE THREAD

**Issue by Yerrak** [rancher/rancher#3589]
The `hostname_override` compose label sets the hostname to the `container_name` as stated [here](http://docs.rancher.com/rancher/labels/): `StackName_ServiceName_CreateIndex`.

As this is not a valid hostname because of the underscores (see [RFC 1123](https://tools.ietf.org/html/rfc1123)), for example _datadog_ complains about it - and does not work at all.

So I would like to suggest either to override the hostname with the actual name of the host in rancher (using `host_name` not `container_name` as parameter for the override) or/and to use RFC-compliant container names.

Also see [https://forums.rancher.com/t/suggestion-variables-in-host/1581/3](https://forums.rancher.com/t/suggestion-variables-in-host/1581/3)

**Comment by vincent99** [comment]
This is one of those technically correct but widely ignored things.  We can change it, but in the real world underscore **is supported** by many systems and regardless of how we set names users will be able to put in whatever they want with e.g. `docker run --hostname "invalid things like spaces" image`.  Datadog should probably be less pedantic and more useful in this situation.

```
mercury:~ vincent$ dig asdf_zxcv.vtf.me

; <<>> DiG 9.8.3-P1 <<>> asdf_zxcv.vtf.me
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40353
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;asdf_zxcv.vtf.me.		IN	A

;; ANSWER SECTION:
asdf_zxcv.vtf.me.	3596	IN	A	1.2.3.4

;; Query time: 3 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Thu Feb 11 18:36:51 2016
;; MSG SIZE  rcvd: 50
```

**Comment by fedya** [comment]
+1 for this

**Comment by kvaes** [comment]
Maybe switch to dashes instead of underscores?

**Comment by nickholl** [comment]
+1
Solr also has issues with underscores in the hostname so Solrcloud nodes aren't contactable when using the default container id or container name.

**Comment by jdobyns** [comment]
+1
Same goes for activemq

6/29/2016 1:17:21 AMCaused by: java.net.URISyntaxException: Illegal character in hostname at index 25: ws://amq_amq_2:61614?maximumConnections=1000&wireFormat.maxFrameSize=104857600

**Comment by datadrivenhpc** [comment]
+1 
GlusterFS has the same issue

```
#> gluster peer probe slurm_slurmd_1
slurm_slurmd_1 is an invalid address
```

**Comment by cgiraldo** [comment]
+1
I found the same problem with Apacke Kafka

**Comment by sandysandman** [comment]
+1
Spring Cloud Netflix Zuul has this problem as well. We are running a service discovery service, where other services register themselves to it when they start up using their hostname, so that they are discoverable. Zuul then chokes when trying to proxy to the services because it cannot parse hostnames with underscores.

`Caused by: java.lang.IllegalArgumentException: Host name may not be null`

Does anyone have a solution in the mean time? We can work around by specifying the hostname of the docker container to be the same as the service name, which the Rancher DNS can resolve, but means we can only have 1 instance of the service and cannot use scaling.

**Comment by alena1108** [comment]
@deniseschannon we already support it in 1.2 https://github.com/rancher/cattle/pull/1777. No more underscore in service instance names, they are replaced with "-"

**Comment by sangeethah** [comment]
With latest builds form master , containers within the service have names in the following format:
```<stackname>-<servicename>-<createindex> ```
