### ISSUE TITLE
Standard user loses access to provisioned RKE2 cluster before cluster is deleted

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#35899]
**Rancher Server Setup**
- Rancher version: 2.6-head
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: 1.21.7
- Cluster Type (Local/Downstream): K3S
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2 provisioned cluster

**Describe the bug**
If a standard user deletes a cluster they created, the roles and rolebindings that gives the user access to the cluster are deleted before the cluster is cleaned up. That means, if deletion fails for some reason, the user will never know because they will no longer have access to this cluster. As an aside, the user will also need to refresh the UI for the cluster to go away. This is because the UI will try to refresh the status of the cluster, but will be unable to.

**To Reproduce**
As a standard user:
1. Create an RKE2 cluster
2. Wait for the cluster to become active.
3. Delete the cluster.

**Result**
The UI will seem to "hang." Refreshing the page will make the cluster disappear from the UI, even if the cluster has not been deleted.

**Expected Result**
The UI should have status updates and the user should not lose access to the cluster until it is cleaned up.

**Additional context**
This was found while investigating [this](https://github.com/rancher/rancher/issues/35868) issue.

**Comment by jakefhyde** [comment]
@thedadams Did you look into this issue? Is there an approach you have in mind, or possibly something you are already working on?

**Comment by Josh-Diamond** [comment]
Ticket #35899 - Test Results

With Docker and 5 node cluster (1 etcd, 1 control plane, 3 worker):

Reproduced on 2.6.3:
Fresh install of rancher 2.6.3
Create a standard user
Log into rancher with standard user
As standard user, create an RKE2 provisioned 5 node custom cluster (k8s v1.21.9+rke2r1)
Delete RKE2 provisioned custom cluster, as standard user
Issue reproduced - UI stuck in “hang” state and does not update status of cluster until page is manually refreshed

<img width="1484" alt="Screen Shot 2022-03-08 at 9 30 54 AM" src="https://user-images.githubusercontent.com/46494969/157498573-611091cd-6ab9-418f-ac4a-25658b54d6b7.png">


Verification FAILED - Reproduced on v2.6.4-rc6:

Fresh install of rancher 2.6.4-rc6
Create a standard user
Run kubectl command with word count on role bindings to determine total role bindings, as admin
Log into rancher with standard user
As standard user, create an RKE2 provisioned 5 node custom cluster (k8s v1.21.10+rke2r1)
Log out standard user, log in as admin
As admin, confirm role binding creation with kubectl commands - get | describe | wc (word count), and note which role binding was added for standard user on rke2 custom cluster
Log out admin, log in as standard user
Delete RKE2 provisioned custom cluster, as standard user
## BUG STILL EXISTS
### Unable to proceed with the expected following steps:
Cluster is deleted, UI is updated, results seem as expected
Log out standard user, log in as admin
Confirm role binding was removed with kubectl commands, use word count on get clusterrolebindings to ensure a role binding was removed, then verify it was the correct role binding by running kubectl get or describe commands on the targeted role binding noted in step 7, and confirm it no longer exists


Verification FAILED - Reproduced on v2.6-572ab58344b409b452ee3a3144e21066a5d89245-head:
Fresh install of rancher 2.6-head
Create a standard user
Log into rancher with standard user
As standard user, create an RKE2 provisioned 5 node custom cluster (k8s v1.21.10+rke2r1)
Delete RKE2 provisioned custom cluster, as standard user
Issue reproduced - UI stuck in "hang" state and does not update status of cluster until page is manually refreshed

<img width="1495" alt="Screen Shot 2022-03-09 at 10 10 22 AM" src="https://user-images.githubusercontent.com/46494969/157498780-4c4dade1-f719-49b4-b4c9-fe5da9e93ab7.png">

Logs from v2.6-572ab58344b409b452ee3a3144e21066a5d89245-head:
```log
2022/03/09 17:08:57 [INFO] Deleting cluster [c-m-282wfqzq]
2022/03/09 17:08:57 [ERROR] error syncing 'fleet-default/custom-6fc7734ae556': handler unmanaged-machine: an error on the server ("unable to create impersonator account: NotFound 404: failed to find cluster") has prevented the request from succeeding (get nodes ip-172-31-41-65), requeuing
2022/03/09 17:08:57 [ERROR] error syncing 'fleet-default/custom-f0127722ee3a': handler unmanaged-machine: an error on the server ("unable to create impersonator account: NotFound 404: failed to find cluster") has prevented the request from succeeding (get nodes ip-172-31-35-197), requeuing
2022/03/09 17:08:57 [ERROR] error syncing 'fleet-default/custom-2716fb3377a6': handler unmanaged-machine: an error on the server ("unable to create impersonator account: NotFound 404: failed to find cluster") has prevented the request from succeeding (get nodes ip-172-31-44-86), requeuing
2022/03/09 17:08:57 [ERROR] error syncing 'fleet-default/custom-4755327dded5': handler unmanaged-machine: an error on the server ("unable to create impersonator account: NotFound 404: failed to find cluster") has prevented the request from succeeding (get nodes ip-172-31-45-182), requeuing
2022/03/09 17:08:57 [ERROR] error syncing 'fleet-default/custom-13eee21cbafc': handler unmanaged-machine: an error on the server ("unable to create impersonator account: NotFound 404: failed to find cluster") has prevented the request from succeeding (get nodes ip-172-31-40-180), requeuing
2022/03/09 17:08:57 [ERROR] error syncing 'fleet-default/custom-f0127722ee3a': handler unmanaged-machine: an error on the server ("unable to create impersonator account: NotFound 404: failed to find cluster") has prevented the request from succeeding (get nodes ip-172-31-35-197), handler unmanaged-machine: Operation cannot be fulfilled on custommachines.rke.cattle.io "custom-f0127722ee3a": StorageError: invalid object, Code: 4, Key: /registry/rke.cattle.io/custommachines/fleet-default/custom-f0127722ee3a, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 708ba336-07b7-48ee-8fac-cbeb353809c3, UID in object meta: , requeuing
2022/03/09 17:08:57 [ERROR] error syncing 'fleet-default/custom-6fc7734ae556': handler rke-machine: failed to delete fleet-default/custom-6fc7734ae556-machine-plan /v1, Kind=Secret for rke-machine fleet-default/custom-6fc7734ae556: secrets "custom-6fc7734ae556-machine-plan" not found, failed to delete fleet-default/custom-6fc7734ae556-machine-bootstrap /v1, Kind=ServiceAccount for rke-machine fleet-default/custom-6fc7734ae556: serviceaccounts "custom-6fc7734ae556-machine-bootstrap" not found, requeuing
2022/03/09 17:08:57 [ERROR] error syncing 'fleet-default/custom-6fc7734ae556': handler rke-machine: failed to delete fleet-default/custom-6fc7734ae556-machine-bootstrap /v1, Kind=ServiceAccount for rke-machine fleet-default/custom-6fc7734ae556: serviceaccounts "custom-6fc7734ae556-machine-bootstrap" not found, requeuing
2022/03/09 17:08:57 [ERROR] error syncing 'fleet-default/custom-f0127722ee3a': handler rke-machine: failed to delete fleet-default/custom-f0127722ee3a-machine-plan /v1, Kind=ServiceAccount for rke-machine fleet-default/custom-f0127722ee3a: serviceaccounts "custom-f0127722ee3a-machine-plan" not found, requeuing
2022/03/09 17:08:57 [ERROR] error syncing 'fleet-default/custom-4755327dded5': handler rke-machine: failed to delete fleet-default/custom-4755327dded5-machine-bootstrap /v1, Kind=ServiceAccount for rke-machine fleet-default/custom-4755327dded5: serviceaccounts "custom-4755327dded5-machine-bootstrap" not found, failed to delete fleet-default/custom-4755327dded5-machine-plan /v1, Kind=ServiceAccount for rke-machine fleet-default/custom-4755327dded5: serviceaccounts "custom-4755327dded5-machine-plan" not found, requeuing
2022/03/09 17:08:58 [ERROR] Reconciler error: machines.cluster.x-k8s.io "custom-f0127722ee3a" not found
2022/03/09 17:08:58 [ERROR] Reconciler error: machines.cluster.x-k8s.io "custom-4755327dded5" not found
2022/03/09 17:08:58 [ERROR] Reconciler error: machines.cluster.x-k8s.io "custom-6fc7734ae556" not found
2022/03/09 17:08:58 [ERROR] error syncing 'fleet-default/custom-2716fb3377a6': handler rke-machine: failed to delete fleet-default/custom-2716fb3377a6-machine-plan rbac.authorization.k8s.io/v1, Kind=RoleBinding for rke-machine fleet-default/custom-2716fb3377a6: rolebindings.rbac.authorization.k8s.io "custom-2716fb3377a6-machine-plan" not found, requeuing
2022/03/09 17:08:58 [ERROR] error syncing 'fleet-default/custom-13eee21cbafc': handler rke-machine: failed to delete fleet-default/custom-13eee21cbafc-machine-plan rbac.authorization.k8s.io/v1, Kind=RoleBinding for rke-machine fleet-default/custom-13eee21cbafc: rolebindings.rbac.authorization.k8s.io "custom-13eee21cbafc-machine-plan" not found, requeuing
2022/03/09 17:08:58 [ERROR] Reconciler error: machines.cluster.x-k8s.io "custom-2716fb3377a6" not found
2022/03/09 17:08:58 [ERROR] Reconciler error: machines.cluster.x-k8s.io "custom-13eee21cbafc" not found
2022/03/09 17:08:58 [ERROR] Reconciler error: machines.cluster.x-k8s.io "custom-6fc7734ae556" not found
E0309 17:09:01.236799      33 reflector.go:139] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: Failed to watch *v1.Node: an error on the server ("unable to create impersonator account: NotFound 404: failed to find cluster") has prevented the request from succeeding (get nodes)
W0309 17:09:02.162662      33 reflector.go:325] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: failed to list *v1.Node: an error on the server ("unable to create impersonator account: NotFound 404: failed to find cluster") has prevented the request from succeeding (get nodes)
E0309 17:09:02.162696      33 reflector.go:139] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: Failed to watch *v1.Node: failed to list *v1.Node: an error on the server ("unable to create impersonator account: NotFound 404: failed to find cluster") has prevented the request from succeeding (get nodes)
2022/03/09 17:09:02 [ERROR] error syncing 'fleet-default/jkeslar-rke2-custom-delete-test': handler rke-control-plane-remove: Operation cannot be fulfilled on rkecontrolplanes.rke.cattle.io "jkeslar-rke2-custom-delete-test": StorageError: invalid object, Code: 4, Key: /registry/rke.cattle.io/rkecontrolplanes/fleet-default/jkeslar-rke2-custom-delete-test, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 7168f744-e058-42f2-8c6f-8864f0fb3770, UID in object meta: , requeuing
2022/03/09 17:09:02 [ERROR] Reconciler error: clusters.cluster.x-k8s.io "jkeslar-rke2-custom-delete-test" not found
2022/03/09 17:09:02 [INFO] [mgmt-auth-users-controller] Deleting clusterRoleTemplateBinding c-m-282wfqzq-fleet-default-owner for user u-jbpkylh3ot
2022/03/09 17:09:02 [INFO] [mgmt-auth-users-controller] Deleting token u-jbpkylh3ot for user u-jbpkylh3ot
2022/03/09 17:09:02 [INFO] [mgmt-auth-crtb-controller] Deleting roleBinding crb-eyarnt2snd
2022/03/09 17:09:02 [INFO] [mgmt-auth-crtb-controller] Deleting rolebinding c-m-282wfqzq-fleet-default-owner-cluster-owner in namespace p-9hnl6 for crtb c-m-282wfqzq-fleet-default-owner
2022/03/09 17:09:02 [INFO] [mgmt-auth-crtb-controller] Deleting rolebinding c-m-282wfqzq-fleet-default-owner-cluster-owner in namespace p-xgltj for crtb c-m-282wfqzq-fleet-default-owner
2022/03/09 17:09:07 [INFO] [mgmt-cluster-rbac-remove] Deleting namespace c-m-282wfqzq
2022/03/09 17:09:12 [INFO] [mgmt-project-rbac-remove] Deleting namespace p-9hnl6
2022/03/09 17:09:12 [INFO] [mgmt-project-rbac-remove] Deleting namespace p-xgltj
2022/03/09 17:09:13 [INFO] [mgmt-auth-crtb-controller] Deleting roleBinding crb-lfip3bn3cc
2022/03/09 17:09:17 [INFO] [mgmt-auth-prtb-controller] Updating owner label for roleBinding crb-5rojqmy2ok
2022/03/09 17:09:18 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding crb-5rojqmy2ok
```

**Comment by paynejacob** [comment]
this appears to be a dashboard issue, I tested with `corral create issue-35899 ghcr.io/rancherlabs/corral/rancher:latest -v rancher_version=2.6.4-rc8`

1. login as admin
2. create a standard user
3. login as standard user
4. create a custom cluster 
5. goto the cluster management clusters list
6. delete cluster


I also observed the cluster hang forever however when checking the websocket I observe a `resource.remove` event for the cluster.

**Comment by Josh-Diamond** [comment]
Ticket #35899

Verified on 2.6.4-rc8:
1. Fresh install of rancher v2.6.4-rc8
2. As admin, create a standard user
3. As standard user, create an rke2 custom cluster
4. Grab clusterrolebinding id for rke2 custom cluster - `kubectl get clusterrolebindings -A`
5. As standard user, delete rke2 custom cluster
6. Confirm clusterrolebinding from step 4 was removed - `kubectl get clusterrolebindings <crb_id>`
7. Verified - backend results as expected, as noted above, the UI is still experience "hang" state and requires a hard refresh to synchronize UI data with backend state

CRB was successfully removed (step 6):

<img width="732" alt="Screen Shot 2022-03-14 at 4 02 33 PM" src="https://user-images.githubusercontent.com/46494969/158275294-c142116e-f8f6-447e-bbde-6c110188f815.png">

**Comment by thedadams** [comment]
Issue was reopened by zube bot.
