### ISSUE TITLE
v2.6 KDM - Tracking issue for K3s k8s December Patches 

### ISSUE THREAD

**Issue by katran001** [rancher/rancher#35896]
This is the tracking issue for the K3s December k8s Patches. We should be checking/validating the following versions:

v1.22.5
v1.21.8
v1.20.14

**Comment by rancher-max** [comment]
Validated using rancher v2.6.3 with KDM pointing to dev-v2.6

All listed versions are available to upgrade to. 1.22 shows experimental.

Can create clusters with v1.21 and v1.22. 1.22 shows experimental.
