### ISSUE TITLE
Missing entries in new UI's left menu when a namespace is selected

### ISSUE THREAD

**Issue by sebastien-helbert** [rancher/rancher#35890]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option :
   - Helm Chart, RKE1

**Information about the Cluster**
- Kubernetes version: v1.21.6
- Cluster Type : Downstream, Custom

**Describe the bug**
When a namespace is selected, left menu entries such as "Cluster" or "Apps & Marketplace> Charts" appear or disappear depending on the item selected in the left menu which makes the UI very painful to use

**To Reproduce**
Select a namespace and navigate through the left menu

**Result**

![image](https://user-images.githubusercontent.com/6445261/146351884-21304445-93dc-49c8-af74-d26d6c768619.png)
Here entries disappear when "Workload > DeamonsSet" is selected for example : 
![image](https://user-images.githubusercontent.com/6445261/146352151-bc616885-37b5-4d2f-9ac5-f8979ebeb3a1.png)

**Comment by pbrissaud** [comment]
This bug exists since 2.6 and it's very annoying ! Even the **Starred** entry is missing  depending on the menu selected
