### ISSUE TITLE
invalid image version of jettech-kube-webhook-certgen

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#35891]
**Rancher Server Setup**
- Rancher version: v2.6.3-rc6

**Describe the bug**
The [rancher-image.txt](https://github.com/rancher/rancher/releases/download/v2.6.3-rc6/rancher-images.txt)  of v2.6.3-rc6 release contains an invalid image version of `docker.io/rancher/mirrored-jettech-kube-webhook-certgen:v1.5.1`, while deploying the Rancher on an air-gap env it will encounter the `ImagePullBackOff` error:

The image is used by the `rancher-monitoring-admission-create` job:
```
#cattle-monitoring-system   rancher-monitoring-admission-create-glt4g pod
create  ●  rancher/mirrored-jettech-kube-webhook-certgen:v1.5.2  false  ImagePullBackOff
```

**Expected Result**
The air-gap image version of `rancher/mirrored-jettech-kube-webhook-certgen` should be `v1.5.2` instead of `v1.5.1`

**Comment by brendarearden** [comment]
The latest version of rancher-monitoring https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-monitoring/rancher-monitoring/100.1.0%2Bup19.0.3 dropped the use of `rancher/mirrored-jettech-kube-webhook-certgen:v1.5.2` in favor of `mirrored-ingress-nginx-kube-webhook-certgen: v1.0` which I do see included in the latest rc's [rancher-images.txt](https://github.com/rancher/rancher/releases/download/v2.6.3-rc6/rancher-images.txt ). 

What version of rancher-monitoring are you integrated with?

**Comment by brendarearden** [comment]
cc: @yasker

**Comment by guangbochen** [comment]
aha, I think that's why we get the `v1.5.2` version cuz we are using a different monitoring chart version, thanks.

**Comment by Jono-SUSE-Rancher** [comment]
@guangbochen - I'm going to move this over To Test and assign the Harvester team (you, or whoever) to just test this. Go ahead and close it once you've validated that the correct monitoring chart version fixes the problem with certgen.

**Comment by guangbochen** [comment]
close it as this is should be fixed on the Harvester side, thanks.
