### ISSUE TITLE
v2.6 KDM - Tracking issue for RKE2 k8s December Patches

### ISSUE THREAD

**Issue by katran001** [rancher/rancher#35895]
This is the tracking issue for the RKE2 December k8s Patches. We should be checking/validating the following versions:

v1.22.5
v1.21.8
v1.20.14

**Comment by rancher-max** [comment]
Validated using rancher v2.6.3 and KDM branch dev-v2.6

- All 3 versions are available to upgrade imported cluster to
- Can create v1.21.8 and v1.22.5 clusters
- v1.22 in both imported cluster upgrade and in cluster creation is NOT the default option and is marked as experimental
