### ISSUE TITLE
Error seen for EKS clusters "[ERROR] error syncing 'c-m8jwl': handler cluster-stats: strconv.Atoi: parsing "21+": invalid syntax, requeuing"

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#35905]
**Rancher Server Setup**
- Rancher version: ed77b518
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

When creating or importing an EKS cluster, the following error is seen in the logs:

```
[ERROR] error syncing 'c-m8jwl': handler cluster-stats: strconv.Atoi: parsing "21+": invalid syntax, requeuing"
```

Prior to the fix for https://github.com/rancher/rancher/issues/35902 this was preventing Rancher from setting the kubernetes version on the cluster status. Now, it would be preventing Rancher from restarting the agent for kubernetes 1.22 changes (https://github.com/rancher/rancher/issues/35766), though EKS doesn't currently support 1.22 so the only effect is the repeating log error.

**To Reproduce**
 

Provision or import an EKS cluster, selecting '1.21' as the version (the default).

**Result**

Cluster becomes active but the error shows up in the logs.

**Expected Result**

No error

**Screenshots**

**Additional context**

**Comment by slickwarren** [comment]
also hitting this same issue on eks 1.21 local cluster (3 node, HA install, valid signed certs) for a previous 2.6.3 of rancher (v2.6.3-rc6)

**Comment by sowmyav27** [comment]
On 2.6-head commit id: `981fbc8 `

Hosted EKS clusters downstream clusters show the k8s version (this wasnt happening when the original issue was found).
Without fix:
<img width="1437" alt="Screen Shot 2021-12-17 at 10 19 31 AM" src="https://user-images.githubusercontent.com/26032343/146590135-c85caefa-bd16-4d4f-8e50-f9e47d030b36.png">

With Fix:
<img width="1442" alt="Screen Shot 2021-12-17 at 10 18 26 AM" src="https://user-images.githubusercontent.com/26032343/146590139-f74f11dc-8eea-4535-9477-b67c5d329039.png">
