### ISSUE TITLE
Editing/updating existing catalog apps Validation failed in API: rancher max version exceeded

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35904]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6.3-rc6, upgraded from v2.6.2
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.20.11, 1.2.13
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.21.7
- Cluster Type (Local/Downstream): `Downstream node driver 3 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
Not able to update/edit apps that are created in v2.6.2 and below which are compatible with the rancher versions. 

**To Reproduce**
1. Create a rancher server v2.6.2
2. Install any legacy catalog app eg., argo-crd, docker-registry etc. in the default namespace
3. Upgrade the rancher server to v2.6.3-rc6
4. Verify the legacy feature flag is enabled by default. 
5. From downstream cluster --> legacy --> project --> apps select the argo-crd or docker-registry

**Result**
App upgrade fails with the error 
```
Validation failed in API: rancher max version exceeded
```

**Expected Result**
Updating/editing the app should go through as the apps were already installed from the previous version.

**Additional context**
https://github.com/rancher/rancher/issues/35680
https://github.com/rancher/ui/pull/4791

**Comment by rmweir** [comment]
QA Note:
This fix should address updates and rollbacks for both regular apps and multi cluster apps.

**Comment by brendarearden** [comment]
Available to test in rancher/rancher v2.6.3-rc8

**Comment by anupama2501** [comment]
Verified the following on v2.6.2 --> v2.6.3-rc8 and v2.5.11 --> v2.6.3-rc8

-  On 2.6.2, install the apps

1. library apps: argo-cd, docker-registry
2. Legacy apps: monitoring
3. v2 charts: monitoring, istio

- Upgrade the rancher server to v2.6.3-rc8
- Verified from 2.5.11 --> 2.6.3-rc8, legacy flag is enabled by default
- from explorer --> project --> default project --> apps --> Updated the mariadb, mysql, argo-cd, docker-registry
- Verified the upgrade goes through without an error
- Uninstalled the mariadb and argo-cd --> works as expected
- Rolled back redis and verified roll back was successful
- Rolled back mysql and uninstalled mysql was successful
- Upgraded the legacy v1 monitoring app --> successful
- Upgraded the v2 charts monitoring and istio --> successful.

**Comment by anupama2501** [comment]
Verified multi cluster apps upgrade from v2.6.2 --> v2.6.3-rc8

- Enabled legacy flag
- Installed a few apps like redis, mariadb from multi cluster apps 
- Upgraded rancher server to v2.6.3-rc10
- Verified updating the multi cluster apps by changing the password and changing the service on the node from cluster IP --> Node IP
