### ISSUE TITLE
HTTP Error 500:Internal Server Error

### ISSUE THREAD

**Issue by wybaron** [rancher/rancher#35910]
**Rancher Server Setup**
- Rancher version: **v2.6.0**
- Installation option (Docker install/Helm Chart): **Docker install**

**Information about the Cluster**
- Kubernetes version:**v1.18.8**
- Cluster Type (Local/Downstream):**Downstream**
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):**Custom**

**Describe the bug**

![image](https://user-images.githubusercontent.com/19605510/146477896-e92ec967-3692-485e-9aca-83d5d339121d.png)

**Comment by vbortnikov** [comment]
Same issue with 2.6.2 on top of RKE2
