### ISSUE TITLE
Graph View in dark theme still has white containers

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3591]
Version - master 2/11

Comments:
Change the color of containers in graph view to the match the dark theme.
![image](https://cloud.githubusercontent.com/assets/11514927/12989859/6af98e68-d0c4-11e5-9ada-d4ed936888b7.png)

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/470

**Comment by tfiduccia** [comment]
Version - master 2/17
Verified fixed
