### ISSUE TITLE
New user getting admin permission with JumpCloud SSO

### ISSUE THREAD

**Issue by rajeevmishra2** [rancher/rancher#35911]
I have integrated the JumpCloud SSO with the rancher, authentication is working perfectly but all the new users are getting the admin permission on rancher. Let me know if there is any fix for this. 

For other SAML provider like Google and Okta it's working perfectly. 

![image](https://user-images.githubusercontent.com/7745758/146489673-1b6fbf34-9165-40f9-b3dc-8852292735b6.png)

**Comment by macedogm** [comment]
Hi @rajeevmishra2, thanks for reporting this issue. Can you please provide more details about which version of Rancher and the cluster OS you are using, please? JumpCloud is not one of the [external authentication services](https://rancher.com/docs/rancher/v2.6/en/admin-settings/authentication/) supported by Rancher. How did you do the integration, was with Keycloak, Shibboleth or?

**Comment by navehsg** [comment]
I found the issue. When you set up SAML integration, the local user you used to configure it is connected to all users using the SAML integration. To fix this, you need to remove the admin permissions for the user that set up the connection, once you do that, it will take the additional permissions from any SAML groups you added in Rancher
