### ISSUE TITLE
Fail to provision RKE2 clusters when agent envvars sets NO_PROXY with Rancher server CIDR

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#35913]
**Rancher Server Setup**
- Rancher version: v2.6.3-rc7

**To Reproduce**
1. Use docker to start rancher. Rancher server url is set to the IP, e.g., `https://1.2.3.4`
2. Create a rke2 cluster using the EC2 driver.
3. In `Cluster Configuration` - `Agent Environment Vars`, input NO_PROXY for variable name and `1.2.0.0/16`(adapt to your setup) for the value. Use the default for the rest of the cluster configuration.

**Result**
The cluster stucks in provisioning, with the message:
`Provisioning bootstrap node(s) lawr-guest-noproxy-cidr-pool1-5cb5657974-9nhf4: waiting for agent to check in and apply initial plan`

**Expected Result**
Provision succeeds.

**Additional context**
If you ssh to the node and run 
```
sudo sh /usr/local/custom_script/install.sh
[INFO]  --no-roles flag passed, unsetting all other requested roles
[INFO]  Using default agent configuration directory /etc/rancher/agent
[INFO]  Using default agent var directory /var/lib/rancher/agent
[ERROR]  Error while connecting to Rancher to verify CA necessity. Sleeping for 5 seconds and trying again.
[ERROR]  Error while connecting to Rancher to verify CA necessity. Sleeping for 5 seconds and trying again.
```

It fails in the following command
```
curl --noproxy='*' --connect-timeout 60 --max-time 60 --write-out %{ssl_verify_result}\n -v -fL https://<rancher-server-ip>/healthz
curl: option --noproxy=*: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by gitlawr** [comment]
Probably not a blocker given that it works if we specify the IP or domain name of the rancher server in NO_PROXY.

**Comment by enriluis** [comment]
i have same issue, exist some workaround? i'm using rancher v2.6.2  rke2 deplyin cluster node cloning template

**Comment by enriluis** [comment]
https://githubmemory.com/repo/rancher/rancher/issues/35872

**Comment by noahgildersleeve** [comment]
Tested in Harvester `master-bfd6a8a9-head` and Rancher `948355c`. The provisioning still stops
## Verification Steps
1. Deploy Harvester single node setup via nightly ISO
2. Deploy Rancher via docker with `v2.6-head`
3. Import Harvester into virtualization management in Rancher
4. Deploy RKE2 cluster with `NO_PROXY` agent env variable
5. Wait for RKE2 to provision

This works with the exact same configuration without the NO_PROXY variable

![Screenshot from 2022-02-23 17-10-56](https://user-images.githubusercontent.com/83787952/155438436-d3b9d4e7-75e4-464e-9688-7d04dbe5dbb4.png)
![Screenshot from 2022-02-23 17-10-47](https://user-images.githubusercontent.com/83787952/155438439-5dbcd739-c608-4190-bddc-176c0a516b3f.png)

**Comment by thedadams** [comment]
With the latest fixes, I am not able to reproduce this issue. When I sent the `NO_PROXY` variable in the Agent Environment Vars, I see that the system-agent is able to parse this variable and sets the correct flags on the `curl` commands.

**Comment by noahgildersleeve** [comment]
This was tested with an stale old version of `v2.6-head`. I will retest this with the most recent version of `v2.6-head`.
