### ISSUE TITLE
Ensure SUC charts version is updated

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#35917]
After adding a new version of `system-upgrade-controller` to rancher/charts, there is still the need to update the chart version in `pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagentplan.go`.

This second step is often forgotten.
1. It should be more obvious where/when this chart version needs to be updated in Rancher.
2. It should be considered whether or not to put in a check in CI that the version is correct/most recent version.

**Comment by thedadams** [comment]
### What was fixed, or what changes have occurred
The SUC chart version was changed to be like rancher-webhook, fleet, etc.

### Areas or cases that should be tested
Deploy an RKE2 cluster and ensure that SUC chart with version 100.0.1 is deployed and the SUC image has version v0.3.1

### What areas could experience regressions?
SUC could not be deployed at all.

### Are the repro steps accurate/minimal?
Yes.

**Comment by sowmyav27** [comment]
Validate usecases:
- Deploy rke2 1.21 cluster and verify SUC is deployed with expected images.
```
- - 3 etcd, 2 control, 3 worker nodes (Custom RKE2 cluster)
- - Cluster should come up Active
```
- Deploy rke2 1.21  cluster and verify SUC is deployed with expected images.
```
- - 3 etcd, 2 control, 3 worker nodes (AWS node driver cluster)
- - Cluster should come up Active
- - upgrade k8s version to 1.22RKE2 version
```

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head c682e30
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 AWS node driver and RKE2 Custom 

----------

### Testing: ###

Tested this issue with the following steps:

**Custom RKE2 Cluster**
1. Deploy an RKE2 1.21 cluster
2. Verify SUC is deployed with expected images

**AWS node driver cluster**
1. Deploy an RKE2 1.21 cluster
2. Upgrade k8s version to 1.22 RKE2 version
3. Verify SUC is deployed with expected images

**Result** - Pass
The image version should be v0.8.1 according to github
![Screen Shot 2022-02-02 at 5.15.08 PM.png](https://zube.io/files/rancher/7d5ebe8378d6070e2d53f1e227cd77b8-screen-shot-2022-02-02-at-5-15-08-pm.png)

**Custom RKE2 cluster**
Cluster is active and SUC is also running with the expected image
![Screen Shot 2022-02-02 at 5.10.04 PM.png](https://zube.io/files/rancher/9e25229926a21ccbf4bd9f2e11598a1b-screen-shot-2022-02-02-at-5-10-04-pm.png)


**AWS node driver cluster**
Cluster is successfully upgraded to k8s version 1.22
![Screen Shot 2022-02-02 at 6.18.23 PM.png](https://zube.io/files/rancher/41beb48fc7e192daa67a40e6e8b8b752-screen-shot-2022-02-02-at-6-18-23-pm.png)
SUC is also running with the expected image
![Screen Shot 2022-02-02 at 6.19.33 PM.png](https://zube.io/files/rancher/0c5cfe43235d56ac55bd3be1f94e54a4-screen-shot-2022-02-02-at-6-19-33-pm.png)

@sowmyav27 @thedadams
