### ISSUE TITLE
Private Docker registry option disappeared

### ISSUE THREAD

**Issue by bergtwvd** [rancher/rancher#35929]
**Rancher Server Setup**
- Rancher version: 2.6
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details: NA

**Information about the Cluster**
- Kubernetes version: v1.21.7
- Cluster Type (Local/Downstream): Local

**Describe the bug**
Currently using Rancher 2.5.8, and moving to 2.6.
We use several private Docker Registries for storing the images referenced from charts in private Helm Chart repositories (Git).
In 2.5.8 we can manage the secret values for registry access and the registry configuration via the Rancher UI. But in 2.6 this seems entirely gone. There seems to be no way to configure a private registry.

**To Reproduce**
Standard installation steps for installing Rancher using Docker.
**Result**
Install is fine. But no UI for configuring Docker registries.

**Expected Result**
Expected UI for private Docker registry configuration in local cluster, where user name and password can be entered.

**Screenshots**
NA

**Additional context**
NA

**Comment by Blackclaws** [comment]
Its a bit hidden:

Dashboard -> Storage -> Secrets -> Create -> Registry

**Comment by bergtwvd** [comment]
Thanks, found the option. I hadn't looked down there - was misled by the name.
