### ISSUE TITLE
[airgap] unable to provision k3s custom cluster -> images are not being pulled from systemDefaultRegistry

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35922]
**Rancher Server Setup**
- Rancher version: v2.6.3-rc7
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1
- Proxy/Cert Details: valid certs, airgap setup

**Information about the Cluster**
- Kubernetes version: 1.21.7+k3s1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom

**Describe the bug**

custom k3s cluster is not able to register with rancher. Investigation on the node reveals that images are being pulled from docker.io, but should be pulled from the systemDefaultRegistry

**To Reproduce**
 
* deploy an airgap setup
* deploy a custom k3s cluster through rancher (k3s, 1.21.7+k3s1) -- tested with single node deployment 
* run the registration cmd on a private node 

**Result**
node will stay in `provisioning` state in rancher. 
example error from one of the pods from the node:
```
Warning  FailedCreatePodSandBox  23s (x4 over 4m2s)     kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "rancher/pause:3.1": failed to pull image "rancher/pause:3.1": failed to pull and unpack image "docker.io/rancher/pause:3.1": failed to resolve reference "docker.io/rancher/pause:3.1": failed to do request: Head "https://registry-1.docker.io/v2/rancher/pause/manifests/3.1": dial tcp 34.198.213.42:443: i/o timeout
```

**Expected Result**

Investigating the node shows that all images being pulled are from docker.io instead of from the registry. 

**Screenshots**

<img width="742" alt="Screen Shot 2021-12-17 at 4 26 53 PM" src="https://user-images.githubusercontent.com/16691014/146622463-d6e22a7e-25f9-487a-acc6-27a42bb38699.png">

**Additional context**

* rke2 custom nodes in the same setup are getting to an `active` state but k3s is not
* `/etc/rancher/k3s/registries.yaml` shows no config:

```
{"configs":{},"mirrors":null}
```

**Comment by brendarearden** [comment]
Available to test in rancher/rancher v2.6.3-rc9

**Comment by slickwarren** [comment]
on v2.6.3-rc9, I'm still seeing the same error for a single-node k3s cluster on 1.21.7:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "rancher/pause:3.1": failed to pull image "rancher/pause:3.1": failed to pull and unpack image "docker.io/rancher/pause:3.1": failed to resolve reference "docker.io/rancher/pause:3.1": failed to do request: Head "https://registry-1.docker.io/v2/rancher/pause/manifests/3.1": dial tcp <ip>:443: i/o timeout
...
cat /etc/rancher/k3s/registries.yaml --
{"configs":{},"mirrors":null}
```

**Comment by thedadams** [comment]
@slickwarren and I were able to figure out what is going on here.

Rancher explicitly removes system and agent args for RKE2/K3S clusters that it doesn't support. It gets a list of the system and agent args it does support for each version of Kubernetes from KDM.

The issue is that `system-default-registry` is not a supported agent argument for K3S clusters in KDM, only for RKE2 clusters. So, even though my change was to add the `system-default-registry` setting to the config for K3S clusters, Rancher was then filtering it out because that is not listed in KDM.

So, the only thing left to do for this issue is to add `system-default-registry` to the list of agent arguments in KDM for supported versions of K3S.

**Comment by thedadams** [comment]
@cwayne18 See my above comment about adding `system-default-registry` to KDM for K3S.

It is my understanding that your team handles this type of request. Please let me know if there are any questions or concerns.

**Comment by cwayne18** [comment]
@thedadams can we close this out since the KDM changes were merged?

**Comment by thedadams** [comment]
@cwayne18 I moved it to "To Test" so that QA will check it and close it.

**Comment by slickwarren** [comment]
tested using rancher v2.6.4-rc2:
* deploy rke2 cluster v1.21.9+rke2r1 -> upgrade to v1.22.6+rke2r1 -- pass
  * ensure that all pods have <system-default-registry> images -- pass
  * ensure cluster gets back to active state on latest version used -- pass
* deploy k3s cluster v1.21.9+k3s1 -> upgrade to v1.22.6+k3s1 -- pass
  * ensure that all pods have <system-default-registry> images -- pass
  * ensure cluster gets back to active state on latest version used -- pass
* deploy rke1 cluster v1.21.9 -> upgrade to v1.22.6-- pass
  * ensure that all pods have <system-default-registry> images -- pass
  * ensure cluster gets back to active state on latest version used -- pass
