### ISSUE TITLE
Catalog libraries set to Disabled when first entering Settings

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3593]
Version - Master 2/11

Steps:
1.  Start with fresh build
2.  Add an environment
3.  Switch to new environment
4.  Click on Add Host from welcome page
5.  Click Ok to set site address to "this site's address:" in Overlay
6.  Go to Admin, then click on Settings

Results:
the Official and Community library radio buttons are set to Disabled.  Even thou if you go to Catalogs you can see they are enabled.

Expected:
The radio buttons should be on Enabled option.

**Comment by vincent99** [comment]
@westlywright I probably broke this parsing of the initial string but can you take a look & fix

**Comment by tfiduccia** [comment]
Steps to recreate:
1.  Go to Admin/Settings and make sure catalog libraries are set to Enabled
2.  Go to Manage Environment and add new environment
3.  Hard refresh browser
4.  Switch to new environment and go to settings

**Comment by tfiduccia** [comment]
Version - master 3/2
Verified fixed
