### ISSUE TITLE
When importing GKE cluster, the asia-northeast3 region cannot be selected.

### ISSUE THREAD

**Issue by aieverglow** [rancher/rancher#35936]
**Is your feature request related to a problem? Please describe.**
When importing GKE cluster, the asia-northeast3 region cannot be selected. But the zonal option has asia-northeast3[a-c].

**Describe the solution you'd like**
It would be nice if the regional code was added so that the asia-northeast3 region could be selected when importing the GKE cluster.

**Describe alternatives you've considered**
select the asia-northeast3 region, or need to provide additional options for custom input.

**Additional context**
Regional options (not appear ap-northeast3)
![image](https://user-images.githubusercontent.com/92528963/146895024-eb91544e-1029-4f62-800d-e8f69460168c.png)

Zonal Options (appear ap-northeast3[a-c]
![image](https://user-images.githubusercontent.com/92528963/146895118-25616064-356d-4abc-984d-f979af4b803a.png)

**Comment by rawis** [comment]
Related with [#4656](https://github.com/rancher/dashboard/issues/4656)
