### ISSUE TITLE
CoreDNS add-on config changes were lost after Rancher upgrade

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#35942]
*Issue description:*
CoreDNS add-on config changes were lost after Rancher upgrade.

*Business impact:*
Name resolution from workloads were timingout because of forward pluging policy change.

*Troubleshooting steps:*
 <text>

*Repro steps:*
 * Install Rancher version v2.5.2
 * Deploy downstream cluster with k8s version v1.19.14-rancher1-1
 * Change CoreDNS forward plugin policy using below KB  [https://www.suse.com/support/kb/doc/?id=000020186]
 * Verify the modification in configmap 
 ** _kubectl get cm -n kube-system coredns -o yaml_
 * After upgrading Rancher to v2.5.9, the changes applied to CoreDNS add-ons were lost , but the same config is visible in cluster’s YAML spec.

*Workaround:*
 Is workararound available and implemented? No
 What is the workaround:

*Actual behavior:*
CoreDNS add-on config changed back to default, but the cluster YAMl spec stayed as it is.

*Expected behavior:*
 CoreDNS add-on config should be in consistent with cluster's YAMl spec.

*Files, logs, traces:*
 NA

*Additional notes:*
 NA

JIRA ID: SURE-3727

**Comment by snasovich** [comment]
@slickwarren , please check if it's reproducible in 2.6.3.

**Comment by slickwarren** [comment]
I was not able to reproduce this by upgrading to 2.6.3:
* deploy rancher v2.5.2
* deploy a downstream cluster on 1.19.14-rancher1-1
  * use the addon config mentioned in the original ticket
    * verify that the addon was applied
* upgrade rancher to 2.6.3
    * wait for the cluster to upgrade
    * verify that the addon config is still applied to the downstream cluster

**Comment by jehof** [comment]
I am experiencing something similar with rancher 2.5.12 and an upgrade to kubernetes 1.20.14.
