### ISSUE TITLE
Rancher UI reads certificate chains incorrectly

### ISSUE THREAD

**Issue by michael-chambers** [rancher/rancher#35946]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Publicly signed certificate from DigiCert

**Information about the Cluster**
- Kubernetes version: 1.21.6
- Cluster Type (Local/Downstream): Local (also observed with custom downstream clusters)
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

Rancher reads the Domain Name and Expiration information from the last certificate in a certificate chain, rather than the first one.

**To Reproduce**
 
Create a TLS Certificate secret in Rancher with a certificate from a public CA (DigiCert is the CA in this instance), with the CA's intermediate certificate chained at the bottom of the file.

**Result**
Rancher displays the Domain Name and Expiration information for the intermediate certificate, rather than the client certificate.

**Expected Result**

Rancher's UI should be displaying Domain Name and Expiration information from the client certificate, which is located at the beginning of the certificate chain, not the end.

**Screenshots**

![Screen Shot 2021-12-21 at 1 28 51 PM](https://user-images.githubusercontent.com/56092496/146993715-75890bf4-0b2f-432c-a2b2-e4b95265b579.png)

**Additional context**

I tested reversing the certificate so that the client certificate was chained at the bottom. When I did this, Rancher could correctly display the certificate's information in the UI. However, this malformed certificate was then rejected by browsers when I tried to serve it out. Researching how to properly chain a certificate online confirmed that the intermediate certificate should be attached at the bottom of the file (see [How Certificate Chains Work](https://knowledge.digicert.com/solution/SO16297.html) or [Get your certificate chain right](https://medium.com/@superseb/get-your-certificate-chain-right-4b117a9c0fce)) Having the UI information incorrect is a pain point as it obscures when a particular certificate will expire. Or even if I have renewed on time, it isn't always obvious where that cert was deployed, as it might have been added to various namespaces under different names, and the displayed Domain Name is completely unhelpful in identifying the certificate.

For additional context, this wasn't a problem in the old Cluster Manager view, but was first noticed in the Cluster Explorer view in Rancher v2.5. Since the Cluster Manager was still an option, there was an easy workaround for the problem. Now that Cluster Manager has been deprecated with version 2.6 (which we've thankfully only deployed in our development environment), this is becoming more frustrating and making it harder for us to manage certificates.

**Comment by almoore** [comment]
+1 
I am seeing this issue as well. Having the certificate chain in the cert will cause the cert at the bottom of the file to show as the expiration date which is not what the previous behavior did in the 2.5 version.

**Comment by almoore** [comment]
This only reads the last certificate in a chain.

**Comment by michael-chambers** [comment]
Still having this issue in Rancher 2.6.3.

**Comment by peter-englmaier** [comment]
Same in Rancher 2.6.4! This is bad, because we cannot see certificate expiration date in the UI.

**Comment by buddyledungarees** [comment]
This is still an open bug on 2023-03-30 rancher ui v2.6.10
