### ISSUE TITLE
[Backport v2.5] Cluster Explorer Apps: Cannot download catalog that responds with a redirect

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#35940]
Back port https://github.com/rancher/rancher/issues/34584

**Comment by sergeirancher** [comment]
Reproduced the issue on 2.5.11
```
[ERROR] failed to unmarshal https://REDACTED.azurecr.io/helm/v1/repo/index.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
[ERROR] error syncing 'test': handler helm-clusterrepo-download: failed to parse response from https://REDACTED.azurecr.io/helm/v1/repo/index.yaml, requeuing
```

### Test Environment: ###
Rancher version: v2.5.12-rc1
Rancher cluster type: single-node docker install
Docker version: 20.10

----------

### Testing: ###
Cluster Explorer > In the top-left drop down select "Apps & Marketplace" > "Chart Repositories" 
- fill out necessary fields using 
  - added a repo with a redirect (AZURE container registry)
  - was able to launch the app
    - the app logo loads
    - can modify repo as
        - config
        - yaml
  - was able to delete the app
  - 
![chart repo](https://user-images.githubusercontent.com/95496078/147973310-fe8713ee-85d5-443b-9074-f877b10ba295.jpg)

----

`disableSameOriginCheck` works as expected 
![origin check](https://user-images.githubusercontent.com/95496078/147973378-1608defb-2d23-473d-a624-9d0ee71d5103.jpg)


----

Was able to successfully install Rancher and Rancher partner charts
- backup
- openEbs

----

Was able to add a github repo with a valid helm chart and deploy/delete the app

**Comment by sgapanovich** [comment]
Reproduced the issue on 2.5.11

```
[ERROR] failed to unmarshal https://REDACTED.azurecr.io/helm/v1/repo/index.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
[ERROR] error syncing 'test': handler helm-clusterrepo-download: failed to parse response from https://REDACTED.azurecr.io/helm/v1/repo/index.yaml, requeuing
```

### Test Environment: ###
Rancher version: v2.5.12-rc1
Rancher cluster type: single-node docker install
Docker version: 20.10

### Testing: ###
Cluster Explorer > In the top-left drop down select "Apps & Marketplace" > "Chart Repositories"
- fill out necessary fields using
  - added a repo with a redirect (AZURE container registry)
    - was able to launch the app
      - the app logo loads
      - can modify repo as
        - config
        - yaml
    - was able to delete the app
![chart repo](https://user-images.githubusercontent.com/40282141/147975297-640b35f9-b1f5-4fb6-a593-24aef749eec2.jpg)


----

`disableSameOriginCheck` works as expected
![origin check](https://user-images.githubusercontent.com/40282141/147975292-b27dccc0-b566-429e-892d-85cb52437290.jpg)


-----

Was able to successfully install Rancher and Rancher partner charts
- backup
- openEbs

-----

Was able to add a github repo with a valid helm chart and deploy/delete the app
