### ISSUE TITLE
When stack names are long , the text overflows on the hosts view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3595]
rancher server version - V0.58.0-rc2

<img width="937" alt="screen shot 2016-02-11 at 12 59 12 pm" src="https://cloud.githubusercontent.com/assets/4266958/12990452/4f66c120-d0bf-11e5-9a2c-ea282f112395.png">

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/13611437/d32adee6-e51f-11e5-8a84-94cc242bd568.png)

**Comment by tfiduccia** [comment]
Version - master 3/8
Verified fixed
