### ISSUE TITLE
Helm install - bootstrapPassword not working - unable to login the dashboard

### ISSUE THREAD

**Issue by jboesh** [rancher/rancher#35968]
**Rancher Server Setup**
- Rancher version: v2.6.3
![image](https://user-images.githubusercontent.com/71582854/147344174-092064f6-50df-4127-8379-069726f0f79d.png)
- Installation option (Docker install/Helm Chart): Helm 

**Describe the bug**
Rancher is up and running but Iam not able to login into the dashboard:
![image](https://user-images.githubusercontent.com/71582854/147344049-95588ce0-b5db-41f2-8d04-35ceebfb8c05.png)
I installed the Rancher helm chart with a bootstrapPassword, but that password is not working!

When I get/describe the bootstrap-secret, it gives me this output, 5 bytes is not much U guess? looks like its empty.
```
PS D:\kluster> kubectl describe secret --namespace cattle-system bootstrap-secret
Name:         bootstrap-secret
Namespace:    cattle-system
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: rancher
              meta.helm.sh/release-namespace: cattle-system

Type:  Opaque

Data
====
bootstrapPassword:  5 bytes

PS D:\kluster> kubectl describe secret --namespace cattle-system bootstrap-secret
Name:         bootstrap-secret
Namespace:    cattle-system
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: rancher
              meta.helm.sh/release-namespace: cattle-system

Type:  Opaque

Data
====
bootstrapPassword:  5 bytes
```

So it looks like the bootstrap password as put into the chart is not working.
is there a way to reset it?
Thanks

**Comment by jboesh** [comment]
Ok update: with Lens I was able to see the secret (bootstrappassword) in a base64 code:
![image](https://user-images.githubusercontent.com/71582854/147345874-8c3e5e10-7557-4708-b0df-5346879be5f6.png)
I decoded the string (YWRtaW4=)  and the output is "admin" , like I put it in the helm values.
But iam still not able to login with the encoded and decoded password

**Comment by wirwolf** [comment]
In your cluster when you install rancher for the first time you do not set bootstrapPassword and racher generated random password. If you redeploy app with new password rancher not apply this changes
I have the same problem in https://github.com/rancher/rancher/issues/34920

**Comment by jboesh** [comment]
> In your cluster when you install rancher for the first time you do not set bootstrapPassword and racher generated random password. If you redeploy app with new password rancher not apply this changes I have the same problem in #34920

I have tried many times to install rancher.
i will remove rancher again and try again without setting bootstrap password.

where can i find the generated password then?
at secret?

**Comment by jboesh** [comment]
Update: when I remove the chart and everything else related to Rancher en start a new installation, there is no bootstrappassword in a secret?
```
PS D:\kluster> kubectl get secret --namespace cattle-system bootstrap-secret 
kubectl : Error from server (NotFound): secrets "bootstrap-secret" not found
At line:1 char:1
+ kubectl get secret --namespace cattle-system bootstrap-secret
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error from serv...cret" not found:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
```

**Comment by wirwolf** [comment]
Try to set a password with Lens: https://github.com/rancher/rancher/issues/34920#issuecomment-960552127

**Comment by jboesh** [comment]
Ok i was able to reset the password FINALLY!!!
In Lens, Pods, select the Rancher pod, click on Pod Shell
and the type this command: reset-password
