### ISSUE TITLE
Resource leak caused by pod shell on cluster-explorer UI

### ISSUE THREAD

**Issue by ly5156** [rancher/rancher#35966]
**Rancher Server Setup**
- Rancher version: Rancher v2.5.11 and Rancher v2.6.3
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Kubernetes version: v1.19.13+k3s1
- Cluster Type (Local/Downstream): Local

**Describe the bug**

**To Reproduce**
 
1. create a ubuntu deployment
2. Once the deployment is running, into the pod list page and invoke the `Execute Shell` menu from the dashboard ui
3. Closed the shell, repeat steps 2 and 3 a few times.
![image](https://user-images.githubusercontent.com/3406205/147331622-4b3fd257-810c-4eff-8a25-b775d74dab37.png)

**Result**
The shell processes get created which each invocation remain active
![image](https://user-images.githubusercontent.com/3406205/147331229-05738279-ac92-402c-a869-75c62d3e1436.png)

**Expected Result**
if close shell should close the process

**Comment by richard-cox** [comment]
@ly5156 You may need to reach out independently to the Rancher team in order for this to be resolved
