### ISSUE TITLE
stop slowly

### ISSUE THREAD

**Issue by duanzonglong** [rancher/rancher#35969]
**Rancher Server Setup**
- Rancher version: server 1.6
docker install

It's slowly,When I stop or restart or upgrade a service.
How to identify the problem?

<img width="933" alt="1" src="https://user-images.githubusercontent.com/15925454/147374192-1b48f5a3-b79b-4927-b687-b36008ac9442.png">

**Comment by vincent99** [comment]
Maintenance of and support for 1.x ended ~2 years ago.
