### ISSUE TITLE
Restarting Rancher will cause the certificate to be automatically rotated

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#35978]
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Docker install
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

Rancher installed through docker, restarting Rancher will cause the certificate to be automatically rotated

**To Reproduce**
 
1. Install single node Rancher, using Rancher-generated self-signed certificate
2. Check the expiration time of the certificate after successful installation: Wednesday, December 28, 2022 at 10:43:31
![image](https://user-images.githubusercontent.com/19684717/147524065-563b9449-07d6-461b-b274-afcd8b4d3c77.png)

3. Restart Rancher Server
4. After the startup is successful, check the expiration time of the certificate again

**Result**
![image](https://user-images.githubusercontent.com/19684717/147524046-ffd21240-d006-421e-b28b-55f3968dc140.png)

The certificate expiration time is updated to Wednesday, December 28, 2022 at 11:01:38. From the Rancher Server log, it can also be seen that the certificate has been rotated:
```
2021/12/28 03:01:37 [INFO] certificate CN=dynamic,O=dynamic signed by CN=dynamiclistener-ca,O=dynamiclistener-org: notBefore=2021-12-28 01:35:48 +0000 UTC notAfter=2022-12-28 03:01:37 +0000 UTC
2021/12/28 03:01:38 [INFO] certificate CN=dynamic,O=dynamic signed by CN=dynamiclistener-ca,O=dynamiclistener-org: notBefore=2021-12-28 01:35:48 +0000 UTC notAfter=2022-12-28 03:01:38 +0000 UTC
2021/12/28 03:01:38 [INFO] Updating TLS secret for serving-cert (count: 5): map[listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.2:172.17.0.2 listener.cattle.io/cn-192.168.64.8:192.168.64.8 listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-rancher.cattle-system:rancher.cattle-system listener.cattle.io/fingerprint:SHA1=E1252E3BC1036D8DB4770B57E734EA655BAD2E54]
2021/12/28 03:01:38 [INFO] Starting management.cattle.io/v3, Kind=ClusterAlert controller
2021/12/28 03:01:38 [INFO] Starting management.cattle.io/v3, Kind=ClusterLogging controller
2021/12/28 03:01:38 [INFO] Starting management.cattle.io/v3, Kind=ClusterScan controller
2021/12/28 03:01:38 [INFO] Starting management.cattle.io/v3, Kind=Notifier controller
2021/12/28 03:01:38 [INFO] Listening on :444
2021/12/28 03:01:38 [INFO] certificate CN=dynamic,O=dynamic signed by CN=dynamiclistener-ca,O=dynamiclistener-org: notBefore=2021-12-28 01:35:50 +0000 UTC notAfter=2022-12-28 03:01:38 +0000 UTC
2021/12/28 03:01:38 [INFO] Active TLS secret serving-cert (ver=24235) (count 5): map[listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.2:172.17.0.2 listener.cattle.io/cn-192.168.64.8:192.168.64.8 listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-rancher.cattle-system:rancher.cattle-system listener.cattle.io/fingerprint:SHA1=E1252E3BC1036D8DB4770B57E734EA655BAD2E54]
2021/12/28 03:01:38 [INFO] certificate CN=dynamic,O=dynamic signed by CN=dynamiclistener-ca,O=dynamiclistener-org: notBefore=2021-12-28 01:35:50 +0000 UTC notAfter=2022-12-28 03:01:38 +0000 UTC
2021/12/28 03:01:38 [INFO] Updating TLS secret for tls-rancher-internal (count: 1): map[listener.cattle.io/cn-10.43.174.136:10.43.174.136 listener.cattle.io/fingerprint:SHA1=584E61B73D473D7C9F6D6F5BCD691CD564FB3F5C]
2021/12/28 03:01:39 [INFO] Active TLS secret tls-rancher-internal (ver=24240) (count 1): map[listener.cattle.io/cn-10.43.174.136:10.43.174.136 listener.cattle.io/fingerprint:SHA1=584E61B73D473D7C9F6D6F5BCD691CD564FB3F5C]
```
**Expected Result**

Restart Rancher Server, the certificate should not be rotated
**Screenshots**

**Additional context**

**Comment by niusmallnan** [comment]
This behavior is indeed inconsistent with the 2.5/2.4 version, which may be the effect of this PR.
https://github.com/rancher/dynamiclistener/pull/49

From the comments here, this may be the desired behavior.
https://github.com/rancher/dynamiclistener/blob/master/factory/gen.go#L73-L85
```
// If the merge would not add any CNs to the additional Secret, the additional
// Secret is returned, to allow for certificate rotation/regeneration.
```
