### ISSUE TITLE
"Creating, Bootstrapping" text when creating host in Dark theme is unreadable

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3597]
Version - Master 2/11

Steps:
1.  Change to Dark theme
2.  Add Host (add any host)

Results:  the text for "Creating" and "Bootstrapping" is a different color then the color around it so you can barely see it.
![image](https://cloud.githubusercontent.com/assets/11514927/12991795/2ca8f9c8-d0ce-11e5-9521-46c6ef4eb02c.png)

Expected:  Should be able to clearly see the text.

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/470

**Comment by tfiduccia** [comment]
Version - master 2/26
Verified fixed
