### ISSUE TITLE
rancher-agent pod crashloop on an m1 mac cluster

### ISSUE THREAD

**Issue by horantj** [rancher/rancher#35982]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install): Running on Ubuntu 20.04.1 LTS/x86_64
- Proxy/Cert Details: default

**Information about the Cluster**
- Kubernetes version: v1.21.5+k3s2 (started using k3d, but also replicated with kind)
- Cluster Type (Downstream): 
Docker Desktop 4.2.0 (70708) on M1 mac
* Imported = Running kubectl apply onto an existing k8s cluster 

**Describe the bug**
rancher-agent pod goes into CrashLoop immediately after running the kubectl apply command provided by rancher server. Logs:
```
INFO: https://nuc:8443/ping is accessible
INFO: nuc resolves to 192.168.50.100
ERROR: The environment variable CATTLE_CA_CHECKSUM is set but there is no CA certificate configured at https://nuc:8443/v3/settings/cacerts
```

**To Reproduce**
Manual exec of the agent container in the cluster shows curl and openssl segfaulting:
```
# kubectl run -i -t --image rancher/rancher-agent:v2.6.2 test1  --command -- sh
If you don't see a command prompt, try pressing enter.
sh-4.4# curl --insecure -sS -fL -o /dev/null --stderr - https://nuc:8443
Segmentation fault
sh-4.4# openssl s_client -connect nuc:8443
CONNECTED(00000003)
Can't use SSL_get_servername
Segmentation fault
sh-4.4# curl --insecure -s -fL https://nuc:8443/v3/settings/cacerts
Segmentation fault
```

**Expected Result**
Agent pod runs, and registers with rancher server.

**Additional context**
Found a similar issue with openssl/python on stackoverflow: https://stackoverflow.com/questions/69598150/apple-mac-book-pro-m1-chip-segmentation-error-when-using-python-requests-library

I manually compiled openssl1.1m within a pod to test, and the segfaults do go away. Looks like the support was added in 1.1i(https://www.openssl.org/news/cl111.txt)
 ```
Changes between 1.1.1h and 1.1.1i [8 Dec 2020]
<snip>

  *) Add support for Apple Silicon M1 Macs with the darwin64-arm64-cc target.
     [Stuart Carnie]
```

```
sh-4.4# openssl version
OpenSSL 1.1.1m  14 Dec 2021
sh-4.4# curl -k https://nuc:8443/v3/settings/cacerts
{"baseType":"setting","created":"2021-12-01T19:49:22Z","createdTS":1638388162000,"creatorId":null,"customized":true,"default":"","id":"cacerts","links":{"remove":"https://nuc:8443/v3/settings/cacerts","self":"https://nuc:8443/v3/settings/cacerts"},"name":"cacerts","source":"db","type":"setting","uuid":"74c8bb78-4aa4-47c5-b338-c84c3ea0863e","value":"-----BEGIN CERTIFICATE-----\nMIIBpzCCAU2gAwIBAgIBADAKBggqhkjOPQQDAjA7MRwwGgYDVQQKExNkeW5hbWlj\nbGlzdGVuZXItb3JnMRswGQYDVQQDExJkeW5hbWljbGlzdGVuZXItY2EwHhcNMjEx\nMjAxMTk1MDE0WhcNMzExMTI5MTk1MDE0WjA7MRwwGgYDVQQKExNkeW5hbWljbGlz\ndGVuZXItb3JnMRswGQYDVQQDExJkeW5hbWljbGlzdGVuZXItY2EwWTATBgcqhkjO\nPQIBBggqhkjOPQMBBwNCAATtQPwY+pDH0TJMatUc1p/9eqU7XJo2Aoq6xuq9ZYYm\n2sWvVS+IPHaBQNipABLS0OklHy+8I49yMpWBZA5griJao0IwQDAOBgNVHQ8BAf8E\nBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUmQCTanM8invH1079hSzr\nB3QPTSEwCgYIKoZIzj0EAwIDSAAwRQIhAMLLz6W+GNd1NtdRhxqgK4j7pmlyYIkF\nIF7MckAhQEZtAiBOiDQ8bs00b8ZpVpg2Nu2CP3I7OsO8A1rjTiSy8j1JBA==\n-----END CERTIFICATE-----"}
```

**Comment by horantj** [comment]
Also, the `registry.suse.com/suse/sle15:15.4` image has a newer openssl which also works:
`
Version        : 1.1.1l-150400.2.26
`
So this may just resolve when the base image gets an update.

**Comment by BibbyChung** [comment]
any news? i get the same issue.... pod crashloop on m1 mac
