### ISSUE TITLE
Rancher reporting cpu/mem reserved and pod count wrong

### ISSUE THREAD

**Issue by erSitzt** [rancher/rancher#35986]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RK2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.5+rke2r1 / v1.21.7+rke2r2
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported RKE2

**Describe the bug**
I have three more or less empty clusters deployed with RKE2, only one of them seems to be reporting a correct value for reserved cpu/mem.
And pods seem to be missing too, but only in the rancher home screen...

<img width="670" alt="image" src="https://user-images.githubusercontent.com/1625376/147645914-42fe894b-2b32-4d74-ad0d-96b06e7721cb.png">

As you can see rke2-downstream2 cluster is reporting no reservations at all and test-rk2 seems to report too much reservations for an empty cluster

This is the output of the resource-capacity plugin if krew:
rke2-downstream2:
```
❯ kubectl resource-capacity
NODE                        CPU REQUESTS   CPU LIMITS    MEMORY REQUESTS   MEMORY LIMITS
*                           8020m (44%)    4120m (22%)   2387Mi (3%)       5323Mi (7%)
rke2-downstream2-agent-1    900m (22%)     1300m (32%)   284Mi (1%)        630Mi (3%)
rke2-downstream2-agent-2    1850m (46%)    1700m (42%)   1341Mi (7%)       4119Mi (24%)
rke2-downstream2-agent-3    820m (20%)     420m (10%)    252Mi (1%)        284Mi (1%)
rke2-downstream2-server-1   1450m (72%)    200m (10%)    126Mi (1%)        53Mi (0%)
rke2-downstream2-server-2   1450m (72%)    200m (10%)    126Mi (1%)        53Mi (0%)
rke2-downstream2-server-3   1550m (77%)    300m (15%)    261Mi (3%)        187Mi (2%)
```

and
test-rke2:
```
❯ kubectl resource-capacity
NODE                 CPU REQUESTS   CPU LIMITS   MEMORY REQUESTS   MEMORY LIMITS
*                    6070m (33%)    220m (1%)    856Mi (1%)        290Mi (0%)
rke2-agent-node-1    600m (15%)     0Mi (0%)     95Mi (0%)         0Mi (0%)
rke2-agent-node-2    600m (15%)     0Mi (0%)     95Mi (0%)         0Mi (0%)
rke2-agent-node-3    600m (15%)     0Mi (0%)     95Mi (0%)         0Mi (0%)
rke2-server-node-1   1570m (78%)    220m (11%)   384Mi (4%)        290Mi (3%)
rke2-server-node-2   1350m (67%)    0Mi (0%)     95Mi (1%)         0Mi (0%)
rke2-server-node-3   1350m (67%)    0Mi (0%)     95Mi (1%)         0Mi (0%)
```

All server nodes are 2 CPU and agent nodes 4 CPU vms btw.

rke2-downstream2 has monitoring installed, test-rke2 has not

<img width="941" alt="image" src="https://user-images.githubusercontent.com/1625376/147648418-ee3910e7-dea8-48d9-af26-1ae8cdb1fe51.png">
<img width="955" alt="image" src="https://user-images.githubusercontent.com/1625376/147648518-a5bb8c80-b9bf-478c-8ad8-0c5abd840279.png">

**Comment by erSitzt** [comment]
btw the issue in the rke2-downstream2 cluster existed even before i tried the upgrade to v1.21.7+rke2r2 via rancher ui

**Comment by Yannis100** [comment]
![image](https://user-images.githubusercontent.com/3008631/148042433-5a2db9de-7716-42b7-a939-62ae9d25697c.png)
![image](https://user-images.githubusercontent.com/3008631/148042557-6138b7f7-2907-479d-a832-50cc3e307e65.png)

Same issue with an aks cluster on 1.21.7 and Rancher 2.6.3
Other cluster deployed with rke also on 1.21.7 are reporting correctly

**Comment by erSitzt** [comment]
https://rancher-addreess.domain.com/v1/management.cattle.io.cluster 
is returning all zeroes for the clusters in question so its not an display issue..

**Comment by erSitzt** [comment]
Deployed another RKE2 cluster and imported it... same result

**Comment by erSitzt** [comment]
Recreated the RKE2 cluster which was reporting correct values (terraform) and now it is not reporting any CPU/MEM/Pod values

It could be that my two working clusters were imported when Rancher was still on `2.6.2` while all the other cluster were imported after the update to `2.6.3` ,but im not 100% sure

**Comment by semaforce-sean** [comment]
![image](https://user-images.githubusercontent.com/93925566/148465965-2d0ba582-07a0-4dc3-9ec8-9d41b0431e1e.png)
Same issue with RKE1 for me.
Working stats built with `2.6.2` 
Non-working stats built with `2.6.3`

**Comment by erSitzt** [comment]
Seems to be getting weirder... my recreated cluster now started to report values... that seem a little off :)

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/1625376/148551409-f6a48779-9363-474d-9068-59b0dbf4dec5.png">

**Comment by erSitzt** [comment]
And i just compared the Pod count of all clusters that are reporting values... none of them are correct

Are those numbers filtered ? excluding some "system" pods ?

So there are my numbers in the home screen
<img width="664" alt="image" src="https://user-images.githubusercontent.com/1625376/148551727-b0c6bc20-239e-428f-af92-910d14e04bdb.png">

And this is in the cluster itself
<img width="947" alt="image" src="https://user-images.githubusercontent.com/1625376/148551847-d876a709-b9cc-4b67-81c7-98ed4e7533c4.png">

<img width="933" alt="image" src="https://user-images.githubusercontent.com/1625376/148551883-537baee8-ee0e-424a-bd0a-d1bfb864331d.png">

**Comment by dtrouillet** [comment]
Hi,

We have the same trouble : 
![image](https://user-images.githubusercontent.com/4112390/149275326-bf0ecbd9-e71b-4107-998a-bab2c92afbcf.png)

Our version is Rancher 2.6.3, we don't have the problem with 2.6.2.
The monitoring is installed on Downstream and not on Local.

**Comment by silentdark** [comment]
Same issue.
![image](https://user-images.githubusercontent.com/10727853/149399440-3c22b7c7-4708-4729-ace4-27399dbe1899.png)

**Comment by siegenthalerroger** [comment]
I have a similar issue, except it's not showing 0%, nor is the effect anywhere but in the cluster that was upgraded to 1.22 (vs the others 1.21). Lens-IDE shows all the values correctly.

**Rancher:** 

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/6848427/156740472-827059e0-a62a-48ab-b5ae-c609dcffd9c5.png">


vs **Lens**:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/6848427/156740534-b780e913-fb30-4f2e-b3ff-52b5abb58339.png">

**Comment by dnoland1** [comment]
Might be same as or related to https://github.com/rancher/rancher/issues/36229

**Comment by fgielow** [comment]
This also happens with the AKS provider. On the image, clusters that show counts had been imported a while ago, while all newly imported with kubernetes v1.21.7 show wrong counts. 

![shot_220330_114154](https://user-images.githubusercontent.com/805927/160862139-a3487d78-9d57-4439-b877-a2ea88aefed4.jpg)

**Comment by imriss** [comment]
remove-stale

**Comment by fengxx** [comment]
I guess the commit 3453a429bf4107dde095dfcf0256daf93ec6ffb3 introduced the sync issue,
remove annotate  management.cattle.io/nodesyncer will trigger a force sync per the nodessyncer logic
```
CLUSTER_ID="the cluster id"
for machine in $(kubectl get nodes.management.cattle.io -n $CLUSTER_ID  -o name --no-headers);do
 kubectl annotate -n $CLUSTER_ID $machine  management.cattle.io/nodesyncer-
done

```

**Comment by ronnyaa** [comment]
We see the same issue. memory requests are not shown.  

![bilde](https://user-images.githubusercontent.com/80334347/185412151-b4008a65-ba6c-4102-8832-221c7ba071cb.png)

**Comment by nilber** [comment]
> In our case right now the memory might be right but the "max memory" is wrong. We have more then 23GB of ram.
> 
> ![image](https://user-images.githubusercontent.com/109420694/197229707-b8b40bd7-8e6a-4d1c-bd07-c871ef0f70d9.png)

Same here
<img width="1424" alt="Screen Shot 2022-10-25 at 00 05 50" src="https://user-images.githubusercontent.com/2486943/197672830-356b1e07-0670-49e3-aead-d66be73f0aa6.png">

**Comment by erSitzt** [comment]
please reopen

**Comment by yodatak** [comment]
I got the same issue with 
k3s --version
k3s version v1.27.7+k3s2 (575bce76)
go version go1.20.10
Can we reopen the bug ? and how to fix ?

**Comment by erSitzt** [comment]
please reopen

/reopen
