### ISSUE TITLE
Monitoring v1 is not available in a downstream cluster on Tenant Rancher server 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35994]
**Rancher Server Setup**
- Rancher version: 2.5.12-rc2
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s - `v1.20.13+k3s1`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.20 Custom cluster downstream on Tenant Rancher

**Describe the bug**
Monitoring v1 is not available in a downstream cluster on Tenant Rancher server 

**To Reproduce**

- Deploy k3s HA cluster - 3 server, 3 worker nodes using `v1.20.13+k3s1` version
- Deploy Rancher on this setup - 2.5.12-rc1
- Import a k3s HA cluster in rancher with `v1.20.13+k3s1` version
- Deploy Rancher 2.5.12-rc1 on this
- Deploy a downstream custom cluster on the Tenant rancher
- Enable monitoring v1

**Result**
- Errors seen when retrieving the graphs in cluster dashboard
```
Failed to obtain metrics. The metrics service may not be available.
undefined
```

Could be the same as this issue - https://github.com/rancher/rancher/issues/35760

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.5-edf83d5f6d2041217f9e543743d69246fe18afa7-head (both host and tenant)
Rancher cluster type: k3s HA (3 and 3) 
k8s version: v1.20.13+k3s1

Downstream cluster type: ec2 node driver cluster and custom cluster
Downstream K8s version: 1.20

----------

### Testing: ###
1. On the tenant cluster: enable v1 monitoring on all 3 clusters (local, node driver, custom)
2. Wait for monitoring to be enabled and check the following 
- go to a cluster main page
  - you see two-layer gadgets on the CPU and memory metrics
  - there should be the following 4 sections of metrics:
    - cluster metrics
    - etcd metrics (not available for the local since there is no etcd)
    - Kubernetes components metrics
    - rancher logging metrics. (it does not contain any metrics since logging is not enabled)
    - ![cluster](https://user-images.githubusercontent.com/40282141/148113625-8c84f24b-8a02-40db-9d13-580d90016e17.jpg)

- go to the System project (on each cluster) > Apps > you should see 2 apps deployed and running:
  - cluster-monitoring
  - monitoring-operator
  - ![apps](https://user-images.githubusercontent.com/40282141/148113882-6d387147-0b8a-464e-ab6b-763d25701562.jpg)
 
- go to Node (on each cluster) > click on the node 
  - you should see metrics for the node and Node metrics 
  - ![node metrics](https://user-images.githubusercontent.com/40282141/148116033-17db7de8-a3c5-4d3b-825c-c61e185f0145.jpg)

- go to Workloads (on each cluster) > click on a workload 
  - you should see metrics for the Workload Metrics
    - from Workloads click on any pod  
      - you should see metrics for the Pod Metrics
        - from the Pod click on the container 
          - you should see metrics for the Container Metrics
![workloads](https://user-images.githubusercontent.com/40282141/148122178-6c00b7e1-3a81-4516-a86a-a7c48ef9b242.jpg)
 

- go to the System project (on each cluster) > Apps > click on cluster-monitoring
  - you will be redirected to grafana dashboard
![grafana](https://user-images.githubusercontent.com/40282141/148126365-310aab91-9ca4-474c-8656-fd4088caa77b.jpg)
