### ISSUE TITLE
Please update Rancher 1.6 Containers

### ISSUE THREAD

**Issue by zeug-it** [rancher/rancher#35992]
**Rancher Server Setup**
- Rancher version: 1.6
- Installation option (Docker install/Helm Chart):
   - Docker
- Proxy/Cert Details:
   - Letsencrypt 

I have one customer running a very special Infrastructure with old Rancher 1.6 Installation not able to update now.

Because of the expiry of the Letsencryt Root Cert all containers have to be rebuild. Is there a way to update all node containers and reinstall all ca-certificates and push the images to dockerhub. 
An alternative would be to change the path of the dockerhub repo for installing - but I do not find the source with the path. Then I would be able to update the images myself.

Greetings,

Martin

**Comment by vincent99** [comment]
We no longer support 1.x and will not be updating anything for it.  It is dangerously irresponsible to be running today on top of a stack of distros, docker, kernels, images, java, log4j, etc that are no longer maintained by anybody.

There was ~2 years of notice that support would be ending, extended more than once, and that has still now passed by nearly 2 more years.

But by far the easiest fix for this would be to switch the cert to something that Ubuntu the images were based on still recognizes.  Like a real paid CA, or ZeroSSL is more or less a drop-in replacement for LetsEncrypt.
