### ISSUE TITLE
convoy-gluster-storagepool stuck in "Initializing"

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3599]
Version - master 2/11

Steps:
1.  Create two hosts
2.  Create and start Gluster FS 
3.  Create and start Convoy Gluster FS (point it to glusterfs-server)

Results:  The storage pools are create but convoy-gluster-storagepool service is stuck in initializing

Expected:  Service to start

**Comment by will-chan** [comment]
can you try again with latest rancher + template?

**Comment by tfiduccia** [comment]
Version - master 3/7
Verified fixed

**Comment by Typositoire** [comment]
Sorry to re-open this but I just deployed Rancher and this still happens to me.

<img width="1390" alt="screen shot 2016-06-29 at 3 04 38 pm" src="https://cloud.githubusercontent.com/assets/721017/16465031/d90bf1e4-3e0a-11e6-99b0-7bbff7dbe3c1.png">
