### ISSUE TITLE
Allow project network isolation for K3s clusters

### ISSUE THREAD

**Issue by Blackclaws** [rancher/rancher#36007]
**Is your feature request related to a problem? Please describe.**
For a couple of scenarios k3s is superior to rke. However the PNI feature is very much a security measure that we would like to keep.

Currently there is a checkbox to enable PNI for k3s however if you try to enable it you get an error stating:
```
Validation failed in API: enableNetworkPolicy enableNetworkPolicy should be false for k3s or rke2 clusters is not a valid option
```

**Describe the solution you'd like**
Checkbox for enable PNI works as expected

**Describe alternatives you've considered**
Manually creating the network policies. Very suboptimal but would technically do the trick.

**Additional context**
Network Policies work in the default k3s installation type so this is not the issue

**Comment by NullIsNot0** [comment]
This should not be left without attention. I think network project isolation should be implemented for k3s and rke2 provisioned/imported clusters.

**Comment by jzandbergen** [comment]
I would also like to see this issue reopened if possible (in our case for RKE2). If this is not possible nor desired I would like to understand the reasons why this is disabled.

**Use at your own risk:** I found out that in the rancher local cluster you can edit the `clusters.management.cattle.io` resource that corresponds with your cluster and change the field `enableNetworkPolicy` from `null` to `true`. However this introduces some errors when editing cluster configuration (eg. adding/removing users).
