### ISSUE TITLE
2.5 KDM - Tracking issue for K3s k8s January Patches

### ISSUE THREAD

**Issue by katran001** [rancher/rancher#36013]
This is the tracking issue for the K3s January k8s Patches. We should be checking/validating the following versions:

v1.20.15

**Comment by rancher-max** [comment]
https://github.com/rancher/kontainer-driver-metadata/pull/801

**Comment by rancher-max** [comment]
#### Validated using rancher v2.5.12 pointing to dev-v2.5 KDM

- v1.20.15+k3s1 is available to upgrade to
- Upgrade is successful (all workloads are up and running and all server and agent nodes upgrade their k8s version)
