### ISSUE TITLE
Upgrading from 2.5.11 to 2.6.3 made EKS clusters unavailable.

### ISSUE THREAD

**Issue by benzman81** [rancher/rancher#36010]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Single Node Docker install
- Proxy/Cert Details: none

**Information about the Cluster**
- Kubernetes version: v1.20.7-eks-d88609 and v1.19.13-eks-8df270
- Cluster Type (Local/Downstream): Hosted  Amazon EKS Cluster formerly created by rancher

**Describe the bug**
After an upgrade from rancher 2.5.11 to 2.6.3 both of our EKS clusters are now unavailable.

**To Reproduce**
Not tried.

**Result**
Both of our EKS clusters are now unavailable.

**Expected Result**
Both of our EKS clusters are still connected and useable.

**Screenshots**
![2022-01-04 16_03_56-Rancher und 10 weitere Seiten - Markus Krüger – Microsoft​ Edge](https://user-images.githubusercontent.com/14224592/148079477-bef41928-6ed6-49f2-8801-c92b264f2d67.png)

**Additional context**
Our custom clusters still work. Via kubectl we couldnt find any cattle-system pods but we dont know if they need to be there and why they got removed by upgrading rancher.

**Comment by benzman81** [comment]
Issue still occurs in v2.6.4-rc8. Any hint how to fix this?

**Comment by adityapatadia** [comment]
We also face this.

**Comment by benzman81** [comment]
Still exists ins 2.6.4.

**Comment by benzman81** [comment]
Still an issue, should not be closed.
