### ISSUE TITLE
Prometheis?

### ISSUE THREAD

**Issue by korenlev** [rancher/rancher#36015]
2.6.2 UI

**https://YYYYYYYYYY/dashboard/c/c-76er/monitoring/monitoring.coreos.com.prometheus**

Title is "**Prometheis**" , looks bad ;-(

**Comment by David-VTUK** [comment]
https://prometheus.io/docs/introduction/faq/#what-is-the-plural-of-prometheus

**Comment by korenlev** [comment]
ho
ha
sorry
