### ISSUE TITLE
v2.6 KDM - Tracking issue for RKE2 k8s January Patches

### ISSUE THREAD

**Issue by katran001** [rancher/rancher#36012]
This is the tracking issue for the RKE2 January k8s Patches. We should be checking/validating the following versions:

v1.22.6
v1.21.9
v1.20.15

**Comment by rancher-max** [comment]
https://github.com/rancher/kontainer-driver-metadata/pull/800

**Comment by rancher-max** [comment]
#### Validated using rancher v2.6.3 and KDM pointing to dev-v2.6 branch

- Versions are as expected and defaults are as expected
<img width="687" alt="image" src="https://user-images.githubusercontent.com/55997940/151624926-d7e78aeb-7c26-43cb-8724-6d21b471d234.png">

- Provisioning a cluster with 3 nodes all roles is successful for each of the versions
- Upgrading an imported cluster shows all expected versions
<img width="776" alt="image" src="https://user-images.githubusercontent.com/55997940/151629951-c0e0fea6-925a-45ad-accc-9646dcbaf686.png">
<img width="803" alt="image" src="https://user-images.githubusercontent.com/55997940/151629969-097bb043-fc20-48e8-96b9-6c1d44370d88.png">

- Upgrading to the latest in each of those version lines is successful
