### ISSUE TITLE
Data is empty after upgrade

### ISSUE THREAD

**Issue by chenFe-1** [rancher/rancher#36022]
Old Version：v2.4.5
New Version：v2.6
I upgraded my single docker rancher to the latest version according to the official requirements, but it seems that the data volume mounted from the old version did not let my newly upgraded rancher have any previous data

this is my operation for updating.
docker stop <RANCHER_CONTAINER_NAME>
docker create --volumes-from <RANCHER_CONTAINER_NAME> --name rancher-data rancher/rancher:<RANCHER_CONTAINER_TAG>
docker pull rancher/rancher:latest
docker run -d --volumes-from rancher-data \
  --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:<RANCHER_VERSION_TAG> \
  --acme-domain <YOUR.DNS.NAME>

before update
![image](https://user-images.githubusercontent.com/63942337/147809367-c84d1afd-73d1-4113-9757-b850841ded73.png)

after update
![image](https://user-images.githubusercontent.com/63942337/147809321-213afdc6-fb65-4fcc-b514-e8bc88800054.png)

**Comment by thedadams** [comment]
@chenFe-1 Was this an upgrade to Rancher v2.6.3?

**Comment by paynejacob** [comment]
This is likely due to changes in 2.5 not being applied to your data volume.  When upgrading rancher we do not support skipping minor versions.

https://www.suse.com/support/kb/doc/?id=000020061#:~:text=Rancher%3A%20perform%20one%20minor%20version%20jump%20at%20a%20time
