### ISSUE TITLE
Creating cluster in EKS stalls at "Waiting for API to be available"

### ISSUE THREAD

**Issue by benzman81** [rancher/rancher#36036]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Single node docker install
- Proxy/Cert Details: none

**Information about the Cluster**
- Kubernetes version: tries 1.21 and 1.19
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
* Infrastructure Provider = EKS

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
Created a new Cluster from rancher UI for EKS. Cluster is created in EKS but Rancher stalls at "Waiting for API to be available".
On the one node instance running I do not see any agent running:
```
dcf31883fd01   602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/pause:3.1-eksbuild.1   "/pause"                 58 minutes ago   Up 58 minutes             k8s_POD_cattle-cluster-agent-5bb6dcc4cc-9rsjt_cattle-system_7e43cb51-bd58-4a23-a1ef-44865db84166_0
e835025ac3be   e746aa816da8                                                            "/coredns -conf /etc…"   59 minutes ago   Up 59 minutes             k8s_coredns_coredns-56b458df85-jclfm_kube-system_e68fefe4-dbe2-4cef-901a-7124d9ed764b_0
701caf43b103   602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/pause:3.1-eksbuild.1   "/pause"                 59 minutes ago   Up 59 minutes             k8s_POD_coredns-56b458df85-jclfm_kube-system_e68fefe4-dbe2-4cef-901a-7124d9ed764b_0
c2717dc9695d   602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/coredns                "/coredns -conf /etc…"   59 minutes ago   Up 59 minutes             k8s_coredns_coredns-56b458df85-gj5gs_kube-system_9cce73b6-26e7-445d-b337-95820408dc25_0
594125552ed4   602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/pause:3.1-eksbuild.1   "/pause"                 59 minutes ago   Up 59 minutes             k8s_POD_coredns-56b458df85-gj5gs_kube-system_9cce73b6-26e7-445d-b337-95820408dc25_0
6013c87001cf   602401143452.dkr.ecr.us-east-2.amazonaws.com/amazon-k8s-cni             "/bin/sh -c /app/ent…"   59 minutes ago   Up 59 minutes             k8s_aws-node_aws-node-v6j8t_kube-system_9e2a8cbe-114c-4a0d-8808-58ef7c8a434f_0
907ec9e85181   602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/kube-proxy             "kube-proxy --v=2 --…"   59 minutes ago   Up 59 minutes             k8s_kube-proxy_kube-proxy-bcnxb_kube-system_6738676e-5050-4abf-9347-3983697137bd_0
7bdbd29cb649   602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/pause:3.1-eksbuild.1   "/pause"                 59 minutes ago   Up 59 minutes             k8s_POD_kube-proxy-bcnxb_kube-system_6738676e-5050-4abf-9347-3983697137bd_0
49aa04a88fe3   602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/pause:3.1-eksbuild.1   "/pause"                 59 minutes ago   Up 59 minutes             k8s_POD_aws-node-v6j8t_kube-system_9e2a8cbe-114c-4a0d-8808-58ef7c8a434f_0
```

**To Reproduce**
Create a cluster with EKS following the documentation: https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/hosted-kubernetes-clusters/eks/

**Result**
Cluster in EKS stalls at "Waiting for API to be available".

**Expected Result**
Cluster becomes available in Rancher

**Comment by SsisyphusTao** [comment]
same issue, any updates?

**Comment by PrateekKhatri** [comment]
same issue I am facing, tried different versions of AWS EKS, still no luck.

**Comment by ksondere** [comment]
Same issue

**Comment by mkosinski-wi-tronix** [comment]
Facing the same issue.  cattle-cluster-agent is created but the logs in it shows 

`time="2022-03-04T20:22:22Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2022-03-04T20:22:32Z" level=info msg="Connecting to wss://rancher.domain.com/v3/connect/register with token starting with 4qmxdk6cxphtzzzzzzzzzzzzz"
time="2022-03-04T20:22:32Z" level=info msg="Connecting to proxy" url="wss://rancher.domain.com/v3/connect/register"
"Failed to connect to proxy. Response status: 302 - 302 Found. Response body: <html><head><title>Object moved</title></head><body>\r\n<h2>Object 
moved to <a href=\"/login.aspx?ReturnUrl=%2fv3%2fconnect%2fregister\">here</a>.</h2>\r\n</body></html>\r\n" error="websocket: bad handshake"`

**Comment by serefarikan** [comment]
Looks like this is an issue independent of how the cluster is created. There's something problematic with connecting to a running cluster. I [just commented in another issue ](https://github.com/rancher/rancher/issues/23266#issuecomment-1059942723)about this, then found this one. Kinda cross-posting to make the point that this is happening across different provisioning scenarios.

**Comment by unixbird** [comment]
I believe I'm encountering the same issue and I'm creating a brand new cluster from rancher to EKS.

**Comment by benzman81** [comment]
Still exists in 2.6.4

**Comment by morrmaker** [comment]
still exists in 2.6.5.

Possible workaround for me has been to terminate ec2 instances and let auto-scaling group create new instances.   Then the cluster becomes active.

**Comment by unixbird** [comment]
> still exists in 2.6.5.
> 
> Possible workaround for me has been to terminate ec2 instances and let auto-scaling group create new instances. Then the cluster becomes active.

So you have to let Rancher go through the initial setup of the EC2 instances and then go to AWS and destroy said EC2 instances and allow Rancher to recreate them? Am I understanding this correctly?

**Comment by morrmaker** [comment]
Yes, let the cluster and node group finish building out.  In EKS you can see that node group and cluster successfully deploy.  Then in EC2 console, once the instances are up, just terminate all instances that are part of the node group.  the Auto-scaling group will see that minimum nodes are too few and re-deploy new instances.  Once these are up, your cluster should show active in Rancher UI.  I have confirmed this with both 2.6.4 and 2.6.5 using both the Rancher UI and terraform to deploy.  Note, if using terraform you need to increase default timeout to give yourself time to create the new instances before the job times out.

**Comment by kevinayres** [comment]
Same issue on 2.6.8

**Comment by seinfkeco** [comment]
what cat i do? when i  face the  same issue

**Comment by bnneupart** [comment]
Still exists in 2.7.0, with nodes v1.23.13-eks-fb459a0

Creates the Kubernetes Cluster, the Node Group, - but no nodes.
