### ISSUE TITLE
Splunk Buffer errors in logging pods after install

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#36039]
**Rancher Server Setup**
- Rancher version: `2.5.12-rc1` (also saw this in 2.5-head) 
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.20.14`
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? Node Driver - DO
User Information**
- What is the role of the user logged in? Standard User 

   
**Describe the bug**
Installed logging v2 3.15.0 into digital ocean cluster set splunk as logging option. errors in logging pod; rancher-logging-fluend-configcheck pods unavailable. Logs not flowing to splunk. 

**To Reproduce**
1. created downstream node driver cluster
2. install logging v2 - 3.15.0
3. create cluster-output using splunk as the logging service
4. create cluster-flow
5. Navigate to cluster explorer > Workload > pods

**Result**
rancher-logging-fluentd-configcheck pod is in error state. logs show error

`2022-01-05 17:33:56 +0000 [info]: starting fluentd-1.13.3 as dry run mode ruby="2.7.4"
2022-01-05 17:33:56 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="this plugin 'Fluent::Plugin::SplunkHecOutput' cannot handle arguments for <buffer ...> section" `

**Expected Result**
Logs flow to Splunk

**Screenshots**

<img width="1344" alt="Screen Shot 2022-01-05 at 3 58 18 PM" src="https://user-images.githubusercontent.com/89212856/148288481-65cbe06a-8b1d-4846-9729-ed3b978cb8c0.png">

**Additional context**
Doing a search for the error, located a splunk error - https://github.com/splunk/fluent-plugin-splunk-hec/issues/150 - not sure if this is the issue at the heart of why we're seeing our errors, but looks similar. Including here as research I did.

**Comment by ronhorton** [comment]
This is happening in 2.6.3 also.

**Comment by superseb** [comment]
We can use https://github.com/banzaicloud/logging-operator/releases/tag/3.17.1 to solve this:

```
$ docker run -ti --entrypoint sh ghcr.io/banzaicloud/fluentd:v1.14.4-alpine-2 -c "gem list" | grep splunk
fluent-plugin-splunk-hec (1.2.10)
```

**Comment by cocampbe** [comment]
Just ran into this same issue.  @superseb Do you have a timeframe for when the newer chart will be available?

**Comment by superseb** [comment]
You can follow progress on v2.6.4 milestone here: https://github.com/rancher/rancher/milestone/255

**Comment by superseb** [comment]
You don't have to update, pretty sure it's going to become available for Rancher 2.6.0 and up, but it's going to get released along side 2.6.4

**Comment by MKlimuszka** [comment]
We will still prioritize fixing this, but I am removing the release blocker tag since this is not a regression (reproduced in 2.6.3) and fixing this won't require a full upgrade based on Seb's last comment.

**Comment by brownz11** [comment]
As a workaround, I found setting the option in the Logging Helm Chart 

images.fluentd.tag = v1.14.4-alpine-2

Pulls the newer image and lets the Splunk output work

**Comment by cocampbe** [comment]
> As a workaround, I found setting the option in the Logging Helm Chart
> 
> images.fluentd.tag = v1.14.4-alpine-2
> 
> Pulls the newer image and lets the Splunk output work

I am going to try this as a work around for now.

**Comment by ronhorton** [comment]
**Pass** Verified in `2.6-head Commit ID f2a4147`

1. created downstream ec2 cluster
2. installed logging v2
3. created a cluster output and cluster flow for splunk
4. checked [rancher-logging-root-fluentd-configcheck] pod logs

`configuration complete; no errors in logs`
<img width="733" alt="Screen Shot 2022-03-08 at 12 10 04 PM" src="https://user-images.githubusercontent.com/89212856/157307496-dec6781c-7589-4896-9d07-cb12268f924f.png">
