### ISSUE TITLE
Changes to project secrets created in 2.5.9 get reverted after upgrade to 2.6.2

### ISSUE THREAD

**Issue by brudnak** [rancher/rancher#36056]
# Reproduction Environment

| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.5.9                                  |
| Rancher cluster type    | HA                                      |
| RKE Version             | v1.2.9                                  |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | N/A                                     |
| Downstream K8s version  | N/A                                     |
| Browser type            | Google Chrome                           |
| Browser version         | 96.0.4664.110 (Official Build) (x86_64) |

## Reproduction steps

1. Starting from `/g/clusters`
2. Hover over `Global` in the navigation bar select `local` -> `System`
3. Click `Add Secret` -> fill out the secret creation form
    - Name: `MY-API-KEY`
    - Scope: `Available to all namespaces in this project`
    - Key: `APPKEY`
    - Value: `SUPER_SECRET_STRING`
    - Click `Save` -> then you are redirected back to the main secrets page
4. Hover over `local System` in the navigation bar and select `Global` -> click the `local` Cluster Name
5. Click `Kubeconfig File` -> click `Copy to Clipboard` -> save this file locally and run

```shell
export KUBECONFIG=local.yaml
```

6. Upgrade the version of Rancher from `v2.5.9` to `v2.6.2` with a command like the following

```shell
helm upgrade rancher rancher-latest/rancher --version 2.6.2 --namespace cattle-system --set hostname=ENTERED_THE_HOST_NAME_HERE --set bootstrapPassword=admin
```

7. Once the update has completed, verify that the secret is still there with a value of `SUPER_SECRET_STRING` and then change it
8. Starting from `/dashboard/home`
9. Click the `hamburger menu` -> click `Cluster Management` -> click `Explore` for the `local` cluster -> click `Storage` from the left side menu -> click `Secrets`
10. Locate the `my-api-secret` / `APPKEY` from the list -> click the `ellipsis (three dots)` for it -> click `Edit Config` 
11. Change the value from `SUPER_SECRET_STRING` to `my_new_string`
12. Click `Save`
13. Navigate back `/dashboard/home` -> close Rancher -> wait some time before returning to verify the value
14. After waiting ~60 minutes, navigate back to the secret and see if the value changed

## RESULTS

The value `my_new_string` was reverted back to its original value of `SUPER_SECRET_STRING` after waiting ~60 minutes.

## EXPECTED RESULT

For a secret not to be reverted to a previous state after updating it

## Additional Info

I noticed the value reverted after ~60 minutes. Initial reports of this bug mentioned that this behavior was observed after waiting `overnight`.

<hr>

**Comment by samjustus** [comment]
SURE-3770

**Comment by maxsokolovsky** [comment]
Could not reproduce. I used the latest v2.5.16 and v2.6.6 in my test, as v2.5.9 and v2.6.2 are obsolete.
Waited for more than an hour, did not see the secret value revert.

@brudnak, as far as I understand, there is a master secret in this scenario. I updated the one that belongs to the project namespace itself and not any namespaces within the project. It is displayed differently in v2.5 than in v2.6. In the former, it's shown as not belonging to a particular namespace, which makes it appear as the project-level, master secret. In v2.6, there does not seem to be this visual distinction. Is this all reasonable, did I pick the right secret to update?

**Comment by samjustus** [comment]
@brudnak  reminder on this one

**Comment by samjustus** [comment]
moved to 2.6 branch instead of 2.7

**Comment by brudnak** [comment]
Was able to reproduce this following the exact steps listed above using `2.5.9` ==> `2.6.2`

Unable to reproduce following the exact steps above using `2.5.16` ==> `2.6.6`

**Comment by samjustus** [comment]
waiting for reporter via jira case
