### ISSUE TITLE
"Create from YAML" in Rancher 2.6.3

### ISSUE THREAD

**Issue by v-theo** [rancher/rancher#36052]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): K3S
- Proxy/Cert Details: Cert-Manager

**Information about the Cluster**
- Kubernetes version: 1.20
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) : Admin

**Describe the bug**
The "Create from YAML" button is no longer present in the Rancher interface since version 2.6.3. Only the "Create" button on some K8S objects so creation can be done by persistent form.
Regarding objects that can only be created by YAML such as for example Istio elements (VirtualServices, Gateways, DestinationsRules ...), it is no longer possible to create said objects.

**Screenshots**
Rancher 2.6.3 : 
![2022-01-06_14h50_28](https://user-images.githubusercontent.com/69858590/148393006-7e3f0d95-4030-4f5c-8778-9dbe2382701b.png)
![2022-01-06_14h50_40](https://user-images.githubusercontent.com/69858590/148393016-a7b06bd3-00bf-4e84-ae9d-6770bc1a0fdf.png)

Rancher 2.6.2 :
![2022-01-06_14h48_46](https://user-images.githubusercontent.com/69858590/148393068-61ed01b8-155d-4746-86f6-f639c3351556.png)
![2022-01-06_14h48_56](https://user-images.githubusercontent.com/69858590/148393081-c6b2abe5-2b3b-45b2-86b4-47a9d40a7ed8.png)

**Comment by gisyrus** [comment]
Any news on this issue? I am suffering from this bug too..
