### ISSUE TITLE
Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s: dial tcp 10.43.118.135:443: connect: connection refused

### ISSUE THREAD

**Issue by ericllylys** [rancher/rancher#36050]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.7` UI: `v2.5.6` |
|Route|`undefined`|

**Comment by ericllylys** [comment]
I checked that IP in the cluster... there is no pod running with that IP, I can't seem to find which pod backs it.

**Comment by valterm** [comment]
Seeing the same error when trying to update user permissions on v2.6.4.
