### ISSUE TITLE
Rancher settings not allowing TLSv1.3 version or cipher suites

### ISSUE THREAD

**Issue by bencardinal** [rancher/rancher#36058]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Docker install
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: RKE2 1.21.3
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
      * Imported = Running kubectl apply onto an existing k8s cluster 

**User Information**
- What is the role of the user logged in? Admin

   
**Describe the bug**
Receive an error when providing the TLS environment variables for TLSv1.3 described on the [TLS Settings](https://rancher.com/docs/rancher/v2.6/en/installation/resources/tls-settings/).

**To Reproduce**

_TLS Minimum Version_
Start the docker container with `--env CATTLE_TLS_MIN_VERSION=1.3`

_TLS Ciphers_
Start the docker container with `--env CATTLE_TLS_CIPHERS=TLS_AES_256_GCM_SHA384`

**Result**

_TLS Minimum Version_
Server fails to start and `docker logs` shows:

```
2022/01/06 16:08:59 [FATAL] failed to setup TLS listener: error while configuring minimal TLS version: invalid minimal TLS version [1.3], must be one of: 1.1 1.0 1.2
```

_TLS Ciphers_
Server fails to start and the `docker logs` shows:

```
2022/01/06 14:26:55 [FATAL] failed to setup TLS listener: error while configuring TLS ciphers: unsupported cipher [TLS_AES_256_GCM_SHA384], must be one or more from: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 TLS_RSA_WITH_3DES_EDE_CBC_SHA TLS_RSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_RSA_WITH_RC4_128_SHA TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA TLS_RSA_WITH_RC4_128_SHA TLS_RSA_WITH_AES_128_CBC_SHA TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 TLS_RSA_WITH_AES_128_CBC_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305 TLS_RSA_WITH_AES_256_CBC_SHA TLS_RSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_RC4_128_SHA TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
```

**Expected Result**

_TLS Minimum Version_
Server starts up and the minimum TLS version is set to 1.3.

_TLS Ciphers_
Server starts up and the only listed cipher in the settings is `TLS_AES_256_GCM_SHA384`

**Screenshots**
N/A

**Additional context**

Following the [documentation](https://rancher.com/docs/rancher/v2.6/en/installation/resources/tls-settings/) which references the [Golang tls constants](https://golang.org/pkg/crypto/tls/#pkg-constants).

Also note that the [`2.6.3` version of  `pkg/tls/base.go`](https://github.com/rancher/rancher/blob/v2.6.3/pkg/tls/base.go) does not appear to have any of the TLS v1.3 constants added which appears to be where the errors are originating.

**Comment by superseb** [comment]
Thanks, we can merge this into https://github.com/rancher/rancher/issues/35654
