### ISSUE TITLE
RKE2 | Worker node is not ready after migrating to a new cluster

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36062]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1 ha

**Information about the Cluster**
- Kubernetes version: v1.21.7+rke2r1
- Cluster Type (Local/Downstream): downsream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Dowstream RKE2 ec2 8 nodes cluster (3 etcd, 2 cp, 3 workers)

   
**Describe the bug**

After migrating Rancher from docker single node to RKE1 HA:
- cluster is stuck in "Provisioning" status
- worker node is stuck in "Nodeconditionsfailed" status

**To Reproduce**
 
Was discovered while testing https://github.com/rancher/rancher/issues/36057
Issue was found when migrating Rancher from docker install to an HA cluster
1. Create Rancher single node install rancher
2. Provision a RKE2 downstream cluster 
  k8s version: v1.21.7+rke2r1
  setup: 3 etcd, 2 cp, 3 workers
3. Following back up documentation create a backup https://rancher.com/docs/rancher/v2.6/en/backups/back-up-rancher/
4. Create a RKE1 3 node all roles cluster (future rancher server cluster)
5. Following migration documentation migrate the rancher server to the cluster created in step 4. https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/
6. Log in to Rancher server 

**Result**
One worker node is not ready 
Couldn't find any related errors in rancher logs or cattle-cluster-agent

**Expected Result**

RKE2 cluster has all nodes Active after migration

**Screenshots**

![rke2](https://user-images.githubusercontent.com/40282141/148482891-58d29888-d63f-4703-9897-beacce11b769.jpg)

**Comment by snasovich** [comment]
Per @thedadams it's likely the same root cause as https://github.com/rancher/rancher/issues/35822. Should be retested once that issue is fixed.

**Comment by thedadams** [comment]
### Root cause
The root cause of this issue was a race condition in the controllers for Rancher and for CAPI.

### What was fixed, or what changes have occurred
The caches used in CAPI for the Rancher objects were started if the weren't already started.

### Areas or cases that should be tested
RKE2/K3S provisioning:
1. Single node all roles.
2. 3 nodes, one role each
3. 1 control plane, 1 etcd and multiple worker nodes

### What areas could experience regressions?
Provisioning and editing

### Are the repro steps accurate/minimal?
Yes.

Note, the underlying issue was the same as https://github.com/rancher/rancher/issues/35822

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.6-head 948355c
Rancher cluster type: HA
Docker version: 20.10

3 RKE2 cluster with:
-1 node: all roles
-3 nodes: one role each
-5 nodes: 1 etcd, 1cp, 3 w

----------

### Testing: ###

1. Provision clusters
2. Run automation
3. Take backup
4. Migrate to a new cluster
5. CHECK: All clusters are active with no issues

FAIL: clusters are stuck in "Provisioning" state. Multiple pods are not in the "Active" status 
there are custom nodes are in provisioning state per each node in every cluster

![new](https://user-images.githubusercontent.com/40282141/152894937-4d89166b-a2a2-41a7-8c25-af2a2c5445ec.jpg)


rancher logs:

```
2022/02/08 00:16:08 [INFO] rkecluster fleet-default/sergei5: reconciliation complete
--
Mon, Feb 7 2022 6:16:08 pm | 2022/02/08 00:16:08 [INFO] rkecluster fleet-default/sergei5: provisioning etcd node(s) custom-cc5cbc03c821: waiting for probes: kubelet
Mon, Feb 7 2022 6:16:16 pm | 2022/02/08 00:16:16 [INFO] rkecluster fleet-default/sergei3: reconciliation complete
Mon, Feb 7 2022 6:16:16 pm | 2022/02/08 00:16:16 [INFO] rkecluster fleet-default/sergei3: provisioning etcd node(s) custom-f0b89f1340df: waiting for probes: kubelet
Mon, Feb 7 2022 6:16:19 pm | 2022/02/08 00:16:19 [ERROR] Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "cluster": the object has been modified; please apply your changes to the latest version and try again
Mon, Feb 7 2022 6:16:23 pm | 2022/02/08 00:16:23 [INFO] rkecluster fleet-default/sergei5: reconciliation complete
Mon, Feb 7 2022 6:16:23 pm | 2022/02/08 00:16:23 [INFO] rkecluster fleet-default/sergei5: provisioning etcd node(s) custom-cc5cbc03c821: waiting for probes: kubelet
Mon, Feb 7 2022 6:16:29 pm | E0208 00:16:29.297726 33 reflector.go:139] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "u-vspbe34l7l" cannot list resource "nodes" in API group "" at the cluster scope
Mon, Feb 7 2022 6:16:31 pm | 2022/02/08 00:16:31 [INFO] rkecluster fleet-default/sergei3: reconciliation complete
Mon, Feb 7 2022 6:16:31 pm | 2022/02/08 00:16:31 [INFO] rkecluster fleet-default/sergei3: provisioning etcd node(s) custom-f0b89f1340df: waiting for probes: kubelet
Mon, Feb 7 2022 6:16:31 pm | 2022/02/08 00:16:31 [ERROR] Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "cluster": the object has been modified; please apply your changes to the latest version and try again
Mon, Feb 7 2022 6:16:33 pm | 2022/02/08 00:16:33 [INFO] Stopping cluster agent for c-m-52zxvf4n
Mon, Feb 7 2022 6:16:33 pm | 2022/02/08 00:16:33 [ERROR] failed to start cluster controllers c-m-52zxvf4n: context canceled
Mon, Feb 7 2022 6:16:38 pm | 2022/02/08 00:16:38 [INFO] rkecluster fleet-default/sergei5: reconciliation complete
Mon, Feb 7 2022 6:16:38 pm | 2022/02/08 00:16:38 [INFO] rkecluster fleet-default/sergei5: provisioning etcd node(s) custom-cc5cbc03c821: waiting for probes: kubelet
Mon, Feb 7 2022 6:16:46 pm | 2022/02/08 00:16:46 [INFO] rkecluster fleet-default/sergei3: reconciliation complete
Mon, Feb 7 2022 6:16:46 pm | 2022/02/08 00:16:46 [INFO] rkecluster fleet-default/sergei3: provisioning etcd node(s) custom-f0b89f1340df: waiting for probes: kubelet
Mon, Feb 7 2022 6:16:53 pm | 2022/02/08 00:16:53 [INFO] rkecluster fleet-default/sergei5: reconciliation complete
Mon, Feb 7 2022 6:16:53 pm | 2022/02/08 00:16:53 [INFO] rkecluster fleet-default/sergei5: provisioning etcd node(s) custom-cc5cbc03c821: waiting for probes: kubelet
Mon, Feb 7 2022 6:17:01 pm | 2022/02/08 00:17:01 [INFO] rkecluster fleet-default/sergei3: reconciliation complete
Mon, Feb 7 2022 6:17:01 pm | 2022/02/08 00:17:01 [INFO] rkecluster fleet-default/sergei3: provisioning etcd node(s) custom-f0b89f1340df: waiting for probes: kubelet
Mon, Feb 7 2022 6:17:03 pm | 2022/02/08 00:17:03 [INFO] Stopping cluster agent for c-m-52zxvf4n
Mon, Feb 7 2022 6:17:03 pm | 2022/02/08 00:17:03 [ERROR] failed to start cluster controllers c-m-52zxvf4n: context canceled
Mon, Feb 7 2022 6:17:08 pm | E0208 00:17:08.116481 33 reflector.go:139] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "u-vspbe34l7l" cannot list resource "nodes" in API group "" at the cluster scope
Mon, Feb 7 2022 6:17:08 pm | 2022/02/08 00:17:08 [INFO] rkecluster fleet-default/sergei5: reconciliation complete
Mon, Feb 7 2022 6:17:08 pm | 2022/02/08 00:17:08 [INFO] rkecluster fleet-default/sergei5: provisioning etcd node(s) custom-cc5cbc03c821: waiting for probes: kubelet
Mon, Feb 7 2022 6:17:16 pm | 2022/02/08 00:17:16 [INFO] rkecluster fleet-default/sergei3: reconciliation complete
Mon, Feb 7 2022 6:17:16 pm | 2022/02/08 00:17:16 [INFO] rkecluster fleet-default/sergei3: provisioning etcd node(s) custom-f0b89f1340df: waiting for probes: kubelet
Mon, Feb 7 2022 6:17:23 pm | 2022/02/08 00:17:23 [INFO] rkecluster fleet-default/sergei5: reconciliation complete
Mon, Feb 7 2022 6:17:23 pm | 2022/02/08 00:17:23 [INFO] rkecluster fleet-default/sergei5: provisioning etcd node(s) custom-cc5cbc03c821: waiting for probes: kubelet
Mon, Feb 7 2022 6:17:24 pm | 2022/02/08 00:17:24 [ERROR] error syncing 'c-m-52zxvf4n': handler cluster-deploy: Get "https://REDACTED:443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": x509: certificate signed by unknown authority, requeuing
Mon, Feb 7 2022 6:17:29 pm | 2022/02/08 00:17:29 [INFO] Stopping cluster agent for c-m-52zxvf4n
Mon, Feb 7 2022 6:17:29 pm | 2022/02/08 00:17:29 [ERROR] failed to start cluster controllers c-m-52zxvf4n: context canceled
Mon, Feb 7 2022 6:17:31 pm | 2022/02/08 00:17:31 [INFO] rkecluster fleet-default/sergei3: reconciliation complete
Mon, Feb 7 2022 6:17:31 pm | 2022/02/08 00:17:31 [INFO] rkecluster fleet-default/sergei3: provisioning etcd node(s) custom-f0b89f1340df: waiting for probes: kubelet
Mon, Feb 7 2022 6:17:38 pm | 2022/02/08 00:17:38 [INFO] rkecluster fleet-default/sergei5: reconciliation complete
Mon, Feb 7 2022 6:17:38 pm | 2022/02/08 00:17:38 [INFO] rkecluster fleet-default/sergei5: provisioning etcd node(s) custom-cc5cbc03c821: waiting for probes: kubelet

````

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 3df76e4
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver
----------

### Testing: ###

Tested this issue with the following:
- 1 node: all roles
- 3 node: all roles
- 3 node: one role each
- 5 node: 1 etcd, 1 cp, 3 workers
- 8 node: 3 etcd, 2 cp, 5 workers

**Result** - Pass

Pass: Clusters are active with no errors

- 1 node: all roles - Pass
- 3 node: all roles - Pass
- 3 node: one role each - Pass
- 5 node: 1 etcd, 1 cp, 3 workers - Pass
- 8 node: 3 etcd, 2 cp, 5 workers - Pass

**Comment by harridu** [comment]
I ran into this problem, too. Would you mind to provide some information how to make the cluster work again? Thank you
