### ISSUE TITLE
Certificate detail incorrectly shows email addresses with domains

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3606]
Rancher 0.59.0

If you have a certificate with x509v3 extensions, it can have email addresses as well as domain names.  However, Rancher lists the email addresses on the certificate detail page along with the domain names, and links them to (eg) https://email@address.com which is obviously wrong.  This should either be a mailto: link, or not shown at all.

**Comment by tfiduccia** [comment]
Version - v1.5.0-rc5
fixed
