### ISSUE TITLE
Rancher Backup | Can't migrate to a new HA cluster from single docker install

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36061]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version:  v1.21.7+k3s1
- Cluster Type (Local/Downstream): local

   
**Describe the bug**

Can't install Rancher on a HA cluster when migrating to a new cluster following Rancher docs https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/

**To Reproduce**
 
1. Create a rancher cluster using a single docker install method
2. Configure the cluster to use Route53 
3. Create a secret to access your s3 bucket
4. Go to Apps&Marketplace > Charts
5. Install rancher - backup app 
  when installing the app add your s3 info (using the secret your created)
6. Take a backup
7. Create a new RKE1 HA cluster (3 nodes)
8. Follow the docs to migrate to the new cluster from the backup you created 
  -Install the rancher-backup Helm chart
  -Restore from backup using a Restore custom resource
  -Install cert-manager
  -Bring up Rancher with Helm 
https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/#4-bring-up-rancher-with-helm

**Result**
when running the `helm install rancher ...` the error is returned 
```
mycommandline % helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=xxx.xxx.xxx 
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "bootstrap-secret" in namespace "cattle-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rancher"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-system"
```

**Expected Result**

Helm installs rancher on the cluster

Workaround: delete the bootstrap-secret `kubectl delete secret bootstrap-secret -n cattle-system` and run helm command again -> it installs the rancher successfully

**Comment by sowmyav27** [comment]
Similar issue found during 2.6.0 release - https://github.com/rancher/rancher/issues/32711

**Comment by tylerharpool** [comment]
Ran into this issue after uninstall k3s and redeploying rancher. rancher stable

**Comment by MKlimuszka** [comment]
This is most likely solved by the linked issue. I am putting it in the queue for QA to validate.

**Comment by sowmyav27** [comment]
@nickwsuse can you pls validate on latest 2.7.x Rancher version?

**Comment by nickwsuse** [comment]
`Verified on v2.7.5-rc5`

I was able to successfully migrate a single node docker install to an HA cluster using [this documentation](https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/). 

Out of curiosity I also tried to do a restore using an already existing fresh HA using the backup from the single docker install and that did **_NOT_** work, though I'm fairly certain that's expected.
