### ISSUE TITLE
Changing Job objects in Fleet result in immutable field errors

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#36063]
Rancher 2.5.9

Any downstream cluster type

A git repo with these contents: fleet-test-main.zip

Issue description:
Since jobs are immutable, changes to jobs via in git repos will cause Fleet to throw immutable field errors.

Business impact:
Jobs will need to be manually deleted before applying changes via fleet.

Repro steps:

rename fleet.yaml from my zip file to fleet.yaml-ignore to prevent Fleet from using it
Create a GitRepo pointing to a git repo with the contents of the zip
Wait for the broken job to be created
Rename fleet.yaml-ignore to fleet.yaml and force an update (the patch file in the overlays dir should be applied)
Workaround:
Is workararound available and implemented? yes
What is the workaround: delete and recreate jobs,

Actual behavior:
Immutable field errors are thrown and the job is not updated

Expected behavior:
Developer stated that this is likely going to be a documentation change, BUT the customer would like for jobs to be deleted and recreated instead. This likely won't happen because some jobs shouldn't be run more than once and there is no way for Fleet to know if that's the case or not, IE workload specific.

SURE-3396

**Comment by MKlimuszka** [comment]
Assigning to Ron to re-validate. It is believed to be fixed.

**Comment by izaac** [comment]
Do we still have access to the test data provided in the repro steps ? @SheilaghM

**Comment by izaac** [comment]
I was following the step to reproduce on Rancher `v2.6.4` with fleet controller `v.0.3.9`

I see the job is created with `image: perlsadf`.
After performing the fleet yaml rename I was expecting to the job patch to be applied and the image to change to : `image: perl`

However the jobs isn't changed and the value is still `image: perlsadf`

Here is the example repo created from the test data in the reported issue. https://github.com/izaac/fleet-test2

**Comment by mattfarina** [comment]
Since Jobs are immutable, any special handling would need design work. The current case should be one where you remove the job. That is deployed. Then you add the job with the changes. This is then deployed. So the Job is removed and then a new one is created.

Not sure how to proceed with this one. Removing the milestone and adding a tag that we need more information. Once we have a path forward we can proceed with scheduling the work on this.
