### ISSUE TITLE
How to use RKE to remove worker nodes that are no longer accessible?

### ISSUE THREAD

**Issue by stevenmcastano** [rancher/rancher#36073]
**Rancher Server Setup**
- Rancher version: 2.4.5
- Installation option (Docker install/Helm Chart): RKE 1.3.2

I've built an RKE cluster that I've had running for a few years now and recently I've had 2 worker nodes go down that can not be recovered. I'm trying to eliminate those 2 worker nodes from one of the clusters but every time I run rke with those 2 nodes removed from the cluster.yml, it seems to get stuck while trying to establish the SSH tunnel to clean out those nodes.

How do I run RKE to remove those 2 nodes from the cluster without them being accessible?

**Comment by rwd5213** [comment]
@stevenmcastano did you ever find a solution to this ? Running into the same problem
