### ISSUE TITLE
Default scrape interval for ingressNginx ServiceMonitor in rancher-monitoring chart too small for NGINX / Request Performance Handling dashboard queries

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#36070]
Issue description:
There is no default values for ingressNginx.serviceMonitor.interval in the rancher-monitoring charts, as a result this takes the Prometheus default scrape interval of 10s. The 10s data points are too granual for the 1m rate calculations in the queries of the built-in NGINX / Request Performance Handling dashboard, and No Data is displayed for the dashboard as a result. The upstream ingress-nginx ServiceMonitor defines a scrape interval of 30s, which works for the dashboard (https://github.com/kubernetes/ingress-nginx/blob/helm-chart-3.39.0/charts/ingress-nginx/values.yaml#L604)

Business impact:
NGINX / Request Performance Handling dashboard in rancher-monitoring is blank and displays No Data

Troubleshooting steps:
N/A

Repro steps:

    Provision an RKE cluster, install Rancher and install rancher-monitoring
    Observe no data for the NGINX / Request Performance Handling dashboard in Grafana
    Upgrade rancher-monitoring chart to set ingressNginx.serviceMonitor.interval: 30s and observe dashboard is functional

Workaround:
Is workararound available and implemented? Yes
What is the workaround: Set ingressNginx.serviceMonitor.interval: 30s in values when installing/upgrading rancher-monitoring chart

Actual behavior:
NGINX / Request Performance Handling dashboard in rancher-monitoring is blank and displays No Data

Expected behavior:
NGINX / Request Performance Handling dashboard works

Files, logs, traces:
N/A

Additional notes:
N/A

SURE-3750

**Comment by ronhorton** [comment]
**Pass** Verified in `2.6-head Commit ID 8ece6ae`

1. created downstream ec2 cluster
2. installed rancher monitoring v2
3. opened grafana dashboard for nginx

`data populated; graph present; no 'no data' label`

reproduced original issue in 2.6.3
