### ISSUE TITLE
Can't configure S3-compatible storage using the Rancher Backups chart in the local cluster during chart install

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#36091]
**Rancher Server Setup**
- Rancher version: `v2.5.11`
- Installation option: Helm
   - If Helm Chart, Kubernetes Cluster and version: k3s HA local
- Proxy/Cert Details: `byo-valid` 

**Information about the Cluster**
- Kubernetes version: `v1.20.12+k3s1`
- Cluster Type (Local/Downstream):  `Local`

**User Information**
- What is the role of the user logged in? `Admin`

  
**Describe the bug**

When installing

**To Reproduce**

- Go to local cluster
- Go to Apps and Marketplace -> Rancher Backups
- Configure Chart 
- Select S3-Compatible storage
- Add all the necessary informaiton

**Result**

```
helm upgrade --install=true --namespace=cattle-resources-system --timeout=10m0s --values=/home/shell/helm/values-rancher-backup-1.2.0.yaml --version=1.2.0 --wait=true rancher-backup /home/shell/helm/rancher-backup-1.2.0.tgz
Release "rancher-backup" does not exist. Installing it now.
Error: YAML parse error on rancher-backup/templates/s3-secret.yaml: error converting YAML to JSON: yaml: line 22: could not find expected ':'
```

**Expected Result**

S3 compatible backup enabled and chart gets installed properly

**Additional context**

Minio Backend with self signed certs.

Secret Sample:

```yaml
apiVersion: v1
data:
  accessKey: <REDACTED
  secretKey: <REDACTED>
kind: Secret
metadata:
  creationTimestamp: "2022-01-10T15:19:48Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:accessKey: {}
        f:secretKey: {}
      f:type: {}
    manager: rancher
    operation: Update
    time: "2022-01-10T15:19:48Z"
  name: s3-backups
  namespace: cattle-system
  resourceVersion: "19001808"
  uid: d14a64d5-0160-4bbe-af6c-b2f93029e9eb
type: Opaque
```

**Comment by jiaqiluo** [comment]
investigated with @izaac  offline, and it turns out a misconfiguration on the user side:
the value of `s3.endpointCA` needs to be the base64 format of the CA, not the original CA value.

**Comment by anupama2501** [comment]
Closing this issue as mentioned by @jiaqiluo

- On 2.5.0, if we provide a base64 encoded file in the endpointCA and install the backup charts while selecting S3-Compatible storage, backup goes through without any error
- Installed the backup charts by selecting no default storage location, chart installation goes through fine. While taking a backup if the details are mentioned as follows, the backup creation goes through fine and the backup file is accessible.
- Restore works as well with the same details provided:
```
Credential Secret --> secret file yaml 
Bucket Name --> bucket name as present in the minio server
Folder --> as present in the minio server
Endpoint --> minio server address
Endpoint CA --> base64 encoded CA certificate
```

Closing this issue and logged a dashboard ticket to track an enhancement for the same on the UI:https://github.com/rancher/dashboard/issues/4903

**Comment by wzrdtales** [comment]
@anupama2501 This is not correct to close this issue. If you can use the button "choose ca file" in the 2.6.x UI, it must be able to do the proper encoding on its own. No one stores base64 versions of their certs as files...
