### ISSUE TITLE
rancher/agent-instance is not being updated

### ISSUE THREAD

**Issue by mcuadros** [rancher/rancher#3609]
After upgrade to `0.59.0` the `rancher/agent-instance` is not being updated even after `docker kill <id> && docker rm <id>` 

A reinstall of the agent and a complete clean up of the `/var/lib/rancher` is required.

**Comment by fentas** [comment]
Now that you mentioned this. Everything is up to date except `rancher/agent-instance` with `:v0.5.0`. Version `v0.8.0` is the latest version?

I would have expected that rancher keeps this up to date.

**Comment by fentas** [comment]
btw: This solved communication issues I had between hosts (rancher managed network)

**Comment by deniseschannon** [comment]
@fentas Rancher does not keep rancher/agent-instance up to date. There is an open issue for that.

https://github.com/rancher/rancher/issues/2837

**Comment by deniseschannon** [comment]
@mcuadros I just tested out upgrading from v0.56.1 to v0.59.0. If you delete the network agent from the UI, it should recreate a network agent using an updated rancher/agent-instance (v0.9.2).

Have you tried doing it from the UI? I've never done it from the docker CLI.

**Comment by mcuadros** [comment]
@deniseschannon using the UI works, but not using the CLI
