### ISSUE TITLE
Variable queries in the Rancher / Pod (Containers) query all container metrics, resulting in a very large response and slow loading/timeout of Metrics tab on Pod view in Rancher UI

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#36107]
Internal reference: SURE-3855

*Issue description:*
 The Metrics tab in the Pod view of the Rancher UI (in a cluster with Monitoring v2 installed) uses the Rancher / Pod (Containers) dashboard from rancher-monitoring grafana. The namespace and pod variable queries for this dashboard are `label_values(\{__name__=~"container_.*|windows_container_.*", namespace!=""}, namespace)` and `label_values(\{__name__=~"container_.*|windows_container_.*", namespace="$namespace", pod!=""}, pod)`

The namespace variable query will retrieve all container metrics in all Namespaces, resulting in a large response body (in the customer environment with many running Pods, the response is over 60MB and causes very slow loading of the metrics). The issue also affects the variables in the Rancher / Pod Grafana dashboard.

By comparison, the built-in upstream Kubernetes / Compute Resources / Pod dashboard uses the following variable queries for namespace and pod, which are significantly smaller `label_values(kube_pod_info\{cluster="$cluster"}, namespace)` and `label_values(kube_pod_info\{cluster="$cluster", namespace="$namespace"}, pod)`

*Business impact:*
 Slow loading of metrics view for Pods in Rancher UI, and of the Rancher / Pod and Rancher / Pod (Containers) dashboards in Grafana

*Troubleshooting steps:*
 N/A

*Repro steps:*
 * Install a Rancher v2.6.3 instance and a custom cluster with a few nodes (I used github.com/superseb/tf-do-rancher2)
 * Install rancher-monitoring in the custom cluster (I used latest 100.1.0+up19.0.3)
 * Navigate to the metrics tab of a Pod view and observe the request of the following format: `https://IP_ADDRESS/k8s/clusters/c-sk95t/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/api/datasources/proxy/1/api/v1/series?match[]=\{__name__=~"container_.*|windows_container_.*", namespace!=""}&start=1640771440&end=1640771740`
 * Observe similar for the Rancher / Pod and Rancher / Pod (Containers) dashboards directly within Grafana
 * Compare the variable queries and payload size / response time for these two dashboards versus the built-in upstream Kubernetes / Compute Resources / Pod dashboard

*Workaround:*
 Is workaround available and implemented? No

*Actual behavior:*
Very large query for variables in Grafana dashboard results in slow loading of Pod metrics in the Rancher UI

*Expected behavior:*
 Small query used for variables in Grafana dashboard to ensure fast loading times

**Comment by Jono-SUSE-Rancher** [comment]
Thanks @catherineluse - yes, this would be a team 3 thing. I don't want to assign it to @aiyengar2 because he might not have bandwidth for it. I'll leave that up to @MKlimuszka.

**Comment by prachidamle** [comment]
@geethub97 please check with @aiyengar2 for details around the required resolution for this issue.

**Comment by nickwsuse** [comment]
`Verified on v2.7-head ID: 4a9b7ba`

The queries seem to be much faster as they're appearing nearly instantly upon page load and when accessing the queries directly - `https://nick27testing.qa.rancher.space/k8s/clusters/c-576qr/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/api/dashboards/uid/rancher-pod-containers-1` - it's a pretty instant response. Looking at the graphs directly on Grafana also load pretty instantly.

**Comment by skanakal** [comment]
It would appears that, With the introduction of [this pull request](https://github.com/rancher/charts/pull/2263) in monitoring, can't see the Grafana Dashboard of "Rancher/pod(containers)" ... see this https://github.com/rancher/rancher/issues/42207
