### ISSUE TITLE
Reconnecting host appears as two in GUI

### ISSUE THREAD

**Issue by MarcusSjolin** [rancher/rancher#3610]
I am using boot2docker (docker-machine) on a Mac to host some Selenium Grid agents, and as soon as the computer gets restarted or the VM gets restarted it auto connects to Rancher, this causes a confusion in Rancher, as it believes it's two instances.

One of the instances will show all the agents running, and the other will just be empty, without a network agent. If I close the empty one down, it will close the working one down as well.

**Comment by cjellick** [comment]
will investigate.

**Comment by cjellick** [comment]
This is because boot2docker uses a read only file system and anything outside of /var/lib/docker is lost upon restart.

Definitely not a GA bug, maybe we don't fix at all since it might be worth the effort to make the special dispensation for b2d.
