### ISSUE TITLE
[2.5-2.6]Helm and Tiller problem : Not all installed apps returned

### ISSUE THREAD

**Issue by throrin19** [rancher/rancher#36103]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): kops
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: all managed EKS clusters : 1.18.20
- Cluster Type (Local/Downstream):
* Hosted = EKS

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
In Rancher 2.5, I can manage many applications, installed from Rancher cluster manager.
In Rancher 2.6, many of this apps disapears in the installed apps list and certains charts are not visible in install apps choice with no reason

**To Reproduce**
- Install apps from rancher 2.5, upgrade to rancher 2.6

**Result**
- many applications are not returned in *Installed Apps* section with no reason
- many charts from custom repository are not listed in *Charts* part with no reason

**Expected Result**
- Show all installed apps without any problems

**Screenshots**

**Additional context**
- This bug is really critic for us, all our applications are managed and We can't manage them now.

**Comment by throrin19** [comment]
For the chart problem, I find it. If the version is at the form `x.x.x-x` the chart is not visible. If I replace by `x.x.x` it works. But, in my case, this change is not the right thing to do

**Comment by throrin19** [comment]
Looking closer, it seems that these are charts that don't have helm's own annotations/labels in the templates. In this case, it seems that Tiller has taken over, except that I never installed this thing on my clusters thinking that everything was well managed by helm. Any idea how to fix the problem on these deployments? Unfortunately I can't afford to uninstall/reinstall them

**Comment by throrin19** [comment]
After research and post. Somebody says it's a migration between hem2 and helm3 But If I try to list my applications using helm2, I obtain this error :  
```
Error : could not find tiller
```

I never install tiller on rancher or on my different clusters :face_with_raised_eyebrow:

**Comment by syndr** [comment]
This is a problem for me as well. I have various applications that were originally deployed with Helm 2 charts, and are not visible within the rancher interface after the upgrade to v2.6.  They are still shown using the `rancher apps` command using the CLI rancher utility on my workstation, just not in the UI.

@throrin19, did you ever find a resolution for this?

**Comment by throrin19** [comment]
@syndr yep I found a solution, but only in rancher 2.5 to prepare the migration to rancher 2.6. I pass this script for all my releases : 

```bash
#!/bin/sh

#set -x
set -e

usage() {
  echo ""
  echo "usage:"
  echo "$0 [options]"
  echo "  -c | --context:      k8s context to use"
  echo "  -n | --namespace:    k8s namespace to use"
  echo "  -r | --release:      name of release to use"
  echo "  --dry-run:           do not run migriation"
  echo ""
  echo "example:"
  echo "  $0 -c dev -n my-ns -r my-release"
}


SCRIPT_DIR="$(dirname "$0")"
CONTEXT="$KUBECONTEXT"
NAMESPACE=""
RELEASENAME=""
KUBECTL_DRY_RUN=""
HELM_OP="upgrade --install --history-max=5"

while [ "$1" != "" ]; do
    case $1 in
        -c | --context )        shift
                                CONTEXT="$1"
                                ;;
        -n | --namespace )      shift
                                NAMESPACE="$1"
                                ;;
        -r | --release )        shift
                                RELEASENAME="$1"
                                ;;
        --dry-run )             KUBECTL_DRY_RUN="--dry-run=client"
                                HELM_OP="template --debug"
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

if [ -z "$CONTEXT" ]; then
    echo "Context is mandatory"; usage; exit 1
fi
if [ -z "$NAMESPACE" ]; then
    echo "Namespace is mandatory"; usage; exit 1
fi
if [ -z "$RELEASENAME" ]; then
    echo "Release name is mandatory"; usage; exit 1
fi


echo ""
echo "Looking up existing Resources ..."
RESOURCES=$(kubectl get-all --context ${CONTEXT} --exclude PodMetrics --exclude ingress.extensions --exclude AppRevision -o name -l io.cattle.field/appId=${RELEASENAME} 2>/dev/null | sort)

echo ""
echo "Patching existing Resources ..."
for resource in $RESOURCES; do
    echo ""
    kubectl --context ${CONTEXT} -n ${NAMESPACE} ${KUBECTL_DRY_RUN} annotate --overwrite ${resource} "meta.helm.sh/release-name"="${RELEASENAME}" "meta.helm.sh/release-namespace"="${NAMESPACE}" || true
    kubectl --context ${CONTEXT} -n ${NAMESPACE} ${KUBECTL_DRY_RUN} label --overwrite ${resource} "app.kubernetes.io/managed-by"="Helm" || true
done
```

This script tag and label all resources of the release to link them to helm.

After that, If you have deployments or statefullset with pvc, You have to patch them to retain them on possible delete :  

```bash
kubectl patch pv pvc-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'
```

After that, you have to delete your deployments/statefullset on orphan mode (no service interruption) : 

```bash
kubectl delete statefulsets.apps --cascade=orphan application-name -n namespace 
```

And to finish, You have to go in the new Rancher UI, in the app & marketplace part, and upgrade your app directly using the ui. In the last rancher version (2.5.12), all value.yml have your configurations. Normally you have just to validate the upgrade, Helm recreate automatically the deployment/statefullset if needed and voilà.

You have to do that to all your releases

**Comment by junkiebev** [comment]
@throrin19 some improvements:
```bash
#!/bin/sh

#set -x
set -e

usage() {
  echo ""
  echo "usage:"
  echo "$0 [options]"
  echo "  -c | --context:      k8s context to use"
  echo "  -n | --namespace:    k8s namespace to use"
  echo "  -r | --release:      name of release to use"
  echo "  --dry-run:           do not run migriation"
  echo ""
  echo "example:"
  echo "  $0 -c dev -n my-ns -r my-release"
}


SCRIPT_DIR="$(dirname "$0")"
CONTEXT="$KUBECONTEXT"
NAMESPACE=""
RELEASENAME=""
KUBECTL_DRY_RUN=""
HELM_OP="upgrade --install --history-max=5"

while [ "$1" != "" ]; do
    case $1 in
        -c | --context )        shift
                                CONTEXT="$1"
                                ;;
        -n | --namespace )      shift
                                NAMESPACE="$1"
                                ;;
        -r | --release )        shift
                                RELEASENAME="$1"
                                ;;
        --dry-run )             KUBECTL_DRY_RUN="--dry-run=client"
                                HELM_OP="template --debug"
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

if [ -z "$CONTEXT" ]; then
    echo "Context is mandatory"; usage; exit 1
fi
if [ -z "$NAMESPACE" ]; then
    echo "Namespace is mandatory"; usage; exit 1
fi
if [ -z "$RELEASENAME" ]; then
    echo "Release name is mandatory"; usage; exit 1
fi

declare -A applications=( ["statefulset.apps"]=statefulset ["deployment.apps"]=deployment )

echo ""
echo "Looking up existing Resources ..."
RESOURCES=$(kubectl get-all --context ${CONTEXT} --exclude PodMetrics --exclude ingress.extensions --exclude AppRevision -o name -l io.cattle.field/appId=${RELEASENAME} 2>/dev/null | sort)
echo ""
echo "Patching existing Resources ..."
for resource in $RESOURCES; do
    res_type=$(echo ${resource} | cut -d'/' -f1)
    echo ""
    kubectl --context ${CONTEXT} -n ${NAMESPACE} ${KUBECTL_DRY_RUN} annotate --overwrite ${resource} "meta.helm.sh/release-name"="${RELEASENAME}" "meta.helm.sh/release-namespace"="${NAMESPACE}" || true
    kubectl --context ${CONTEXT} -n ${NAMESPACE} ${KUBECTL_DRY_RUN} label --overwrite ${resource} "app.kubernetes.io/managed-by"="Helm" || true
    if [ ${applications[$res_type]+_} ]
    then
        # Get the pods which make up the deployment or statefulset
        podlabels=$(kubectl --context ${CONTEXT} -n ${NAMESPACE} ${KUBECTL_DRY_RUN} get ${resource} -o jsonpath="{.spec.selector.matchLabels}" | jq -r '. | to_entries[] | [.key, .value] | join("=")' | awk -v d="," '{s=(NR==1?s:s d)$0}END{print s}')
        pvcs=$(kubectl --context ${CONTEXT} -n ${NAMESPACE} ${KUBECTL_DRY_RUN} get pods -l ${podlabels} -o jsonpath="{.items[*].spec.volumes[*].persistentVolumeClaim}" | jq -r '. | to_entries[] | .value')
        for pvc in $pvcs; do
            vol=$(kubectl --context ${CONTEXT} -n ${NAMESPACE} ${KUBECTL_DRY_RUN} get persistentvolumeclaim ${pvc} -o jsonpath="{.spec.volumeName}")
            kubectl patch pv ${vol} -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'
        done
        kubectl --context ${CONTEXT} -n ${NAMESPACE} ${KUBECTL_DRY_RUN} delete ${resource} --cascade=orphan
    fi
done
```

**Comment by junkiebev** [comment]
I believe that the new problem is that the legacy app, and all of its artifacts, still resides on the local cluster and if you delete it in Cluster Manager, it will delete the application which was just migrated. Is there a way to delete the app without having the controller remove deployments and such?

![image](https://user-images.githubusercontent.com/6684332/161347586-818e44ee-e97b-4a2e-b7a7-5b7147bfd35e.png)

**Comment by throrin19** [comment]
@junkiebev ignore this part, in rancher 2.6, this interface and this part of application is not available and not used

**Comment by junkiebev** [comment]
> @junkiebev ignore this part, in rancher 2.6, this interface and this part of application is not available and not used

There will still be a boatload of `catalogtemplaterevisions` cluttering-up the local cluster's etcd server

**Comment by throrin19** [comment]
Even all applications are visible by Helm, Rancher 2.6 still not see many of them

**Comment by throrin19** [comment]
@junkiebev it is not suffisant, after try to upgrade applications, I have this error message on many of migrated apps (but for others, it works fine. I don't understand) :  

![image](https://user-images.githubusercontent.com/1394778/168570955-f774f9b3-2f79-41bf-8ad1-cf042a505e2f.png)
