### ISSUE TITLE
Rancher Install Fails on calling "validate.nginx.ingress.kubernetes.io" Webhook on RKE Clusters With 1.22.4-rancher1-1

### ISSUE THREAD

**Issue by git-ival** [rancher/rancher#36108]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option:
   - Helm Chart (RKE1): v1.22.4-rancher1-1
- Proxy/Cert Details: LetsEncrypt

**Information about the Cluster**
- Kubernetes version: 1.22.4
- Cluster Type (Local/Downstream): Local

**Describe the bug**
Rancher 2.6.3 install fails on RKE cluster on K8s 1.22.4 with the following error: `failed calling webhook "validate.nginx.ingress.kubernetes.io"`

**To Reproduce**
1. Setup HA infrastructure + [Requirements](https://rancher.com/docs/rke/latest/en/os/) for RKE1 Local cluster (3+ Nodes, NLB, Security Groups with RKE1-specific ports, etc)
2. Use [terraform-rke-provider](https://github.com/rancher/terraform-provider-rke) to setup RKE1 cluster using K8s version 1.22.4-rancher1-1
3. Use [terraform helm provider](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) to install Cert-Manager
  i. Wait for cert-manager to be fully deployed and active
4. **[Error here]** Use terraform helm provider to install Rancher **[Error here]**
  i. Wait for rancher to be fully deployed and active

**Actual Result**
Rancher 2.6.3 fails to install and errors with: `failed calling webhook "validate.nginx.ingress.kubernetes.io"`

**Expected Result**
Rancher should be installed successfully

**Additional context**
#33067

**Comment by izaac** [comment]
This isn't reproducible with kubernetes 1.19.x in Rancher 2.6.3

**Comment by lapfrank12** [comment]
Same error for me on an air-gap install using my own certs (no cert-manager). I applied the `--no-hooks` option to the rancher helm chart deployment like the documentation says. It also happens in K8S 1.19, 1.20 and 1.21 for me. How did you get it to work with 1.19?

- rke 1.3.3
- rke terraform provider 1.3.0
- rancher helm chart 2.6.3
- helm terraform provider 2.4.1

**Comment by bitnik** [comment]
We had the same error but we think that this not caused by rancher. As a workaround we added a 1 min sleep in between installation of cert-manager and rancher server and made helm install of rancher server dependent on sleep. Then we could install rancher server without problem.

Btw there is also a [related issue in ingress-nginx repo](https://github.com/kubernetes/ingress-nginx/issues/5401) and it looks like deleting the problematic `ValidatingWebhookConfiguration` is another workaround.

**Comment by lapfrank12** [comment]
> We had the same error but we think that this not caused by rancher. As a workaround we added a 1 min sleep in between installation of cert-manager and rancher server and made helm install of rancher server dependent on sleep. Then we could install rancher server without problem.
> 
> Btw there is also a [related issue in ingress-nginx repo](https://github.com/kubernetes/ingress-nginx/issues/5401) and it looks like deleting the problematic `ValidatingWebhookConfiguration` is another workaround.

thanks for that 1 min sleep idea! That fixed it for me too. Rancher installs correctly now and the ingress gets set up appropriately.

**Comment by git-ival** [comment]
> > We had the same error but we think that this not caused by rancher. As a workaround we added a 1 min sleep in between installation of cert-manager and rancher server and made helm install of rancher server dependent on sleep. Then we could install rancher server without problem.
> > Btw there is also a [related issue in ingress-nginx repo](https://github.com/kubernetes/ingress-nginx/issues/5401) and it looks like deleting the problematic `ValidatingWebhookConfiguration` is another workaround.
> 
> thanks for that 1 min sleep idea! That fixed it for me too. Rancher installs correctly now and the ingress gets set up appropriately.

Confirmed on my end as well. Adding an extended sleep post cert-manager install (in addition to the wait recommended in the docs) allowed for Rancher to install successfully.
