### ISSUE TITLE
Downstream cluster fleet agent logging "unauthorised" to access fleet-agent-bootstrap secret 

### ISSUE THREAD

**Issue by petedavis** [rancher/rancher#36117]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option: Helm Chart (RKE 1.3.2 v1.19.16-rancher1-1) 
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.19.16
- Cluster Type: Downstream Imported

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
The downstream cluster cannot be explored from the rancher dashboard (links and buttons are disabled). 

**Screenshots**
![image](https://user-images.githubusercontent.com/164331/149072638-681c47c9-baa5-44dc-8d11-5eeb2981e5f2.png)

**Additional context**
Im not too sure how it got into this state, we had a period where we were resolving some downtime from expired certificates, and then we ended up in this state.

I believe the issue is with the fleet agent on the downstream cluster as there is an error being constantly logged:
```
kubectl logs -n cattle-fleet-system fleet-agent-7988bdf679-r54kn
time="2022-01-12T05:49:44Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: Unauthorized"
time="2022-01-12T05:50:44Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: Unauthorized"
time="2022-01-12T05:51:44Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: Unauthorized"
time="2022-01-12T05:52:44Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-system/fleet-agent-bootstrap: Unauthorized"
```

However if I run an auth check it indicates that the fleet-agent service account does have access to the secret?:
```
kubectl auth can-i get secret --as=system:serviceaccount:cattle-fleet-system:fleet-agent -n cattle-fleet-system
yes
```

Am I miss understanding the log? Or is that the incorrect service account that is actually being used to access the secret? Or is there something else that is going on that I am missing?

**Comment by szalayg** [comment]
The same issue exists here: Rancher 2.6.3. We cannot deploy anything vie Fleet

**Comment by szalayg** [comment]
Here is what helped in our case: after saving the bootstrap secret (kubectl get secret ... -o yaml >> bootstrapsecet.yaml) we have deleted it and restarted the affected pods. Then they did run as expected.

**Comment by gelopfalcon** [comment]
Getting the same error, anyone can solve it?

**Comment by tuupola** [comment]
Even though the bot keeps closing the issue to make buglist look nicer, the issue does exist. Rancher `v2.7.5` and K3S `v1.26.7+k3s1`.

```
$ kubectl logs -l app=fleet-agent -n cattle-fleet-local-system   
time="2024-03-01T08:37:23Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-local-system/fleet-agent-bootstrap: Unauthorized"
time="2024-03-01T08:38:23Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-local-system/fleet-agent-bootstrap: Unauthorized"
...
$ kubectl auth can-i get secret --as=system:serviceaccount:cattle-fleet-local-system:fleet-agent -n cattle-fleet-local-system
yes
```

**Comment by tuupola** [comment]
FWIW I upgraded from `v2.7.5` to `v2.7.10` and the problem disappeared.
