### ISSUE TITLE
[2.6.3] Failed to find find system chart fleet

### ISSUE THREAD

**Issue by onpaws** [rancher/rancher#36114]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Docker install
- Proxy/Cert Details: No proxy, using Let's Encrypt for cert

**Information about the Cluster**
_The issue appears to be related to steps the Rancher container takes at boot time, not with the downstream clusters. Including anyway_
- Kubernetes version: 1.19.*
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Clusters are both imported and Rancher-created (RKE1)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
From an Ubuntu shell, I'm using  `docker logs -f $containerName`, so `root`

**Describe the bug**

I searched for a while and found [similar](https://github.com/rancher/rancher/issues/34835) issues but they don't appear to be the same.
As best as I can tell, [`rancher-system-charts`](https://github.com/rancher/system-charts/tree/dev-v2.6/charts) doesn't appear to have a fleet Helm chart, which some component of Rancher appears to expect. So instead of 2.6.3 finishing booting and logs settle down, we see an endless `[ERROR]` loop in the container.

This upgrade was performed following the usual [steps](https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/single-node-upgrades/) which have been successful before today. I carefully read the [2.6.3 release notes](https://github.com/rancher/rancher/releases/tag/v2.6.3), and performed the step that [applied to me](https://github.com/rancher/rancher/issues/35955#issuecomment-1000641550) 

Presumably something is stale, I guess a Helm repo maybe, but I'm not sure how to fix.

**To Reproduce**
Upgrade a single node/Docker Rancher container from v2.6.0 -> 2.6.3
`docker logs -f $containerName`

**Result**
After starting Rancher container and following the Docker logs, the following messages loop every 5 seconds:
```
2022/01/11 21:02:24 [ERROR] available chart version (0.3.500) for fleet is less than the min version (100.0.2+up0.3.8) 
2022/01/11 21:02:24 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
2022/01/11 21:02:29 [ERROR] available chart version (0.3.500) for fleet is less than the min version (100.0.2+up0.3.8) 
2022/01/11 21:02:29 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
(repeats over and over)
```

**Expected Result**
After Rancher container finishes booting, the logs should 'settle' and not loop `[ERROR]`s

**Screenshots**
The error seems to start fairly early in the boot process
<img width="983" alt="image" src="https://user-images.githubusercontent.com/182515/149024267-354f1841-03fd-4e46-8040-8da02bec5469.png">
I imagine it's b/c [this](https://github.com/rancher/rancher/blob/0e49c0fcfbf8a1651dd7a2c6487f8e2001cd91d5/pkg/catalogv2/system/system.go#L172) gets called relatively early.

**Additional context**=
Command: `docker run --privileged -d --restart=unless-stopped -p 80:80 -p 443:443 -v /rancherdata:/var/lib/rancher rancher/rancher:v2.6.3`

(that's the command I ran on the Ubuntu host to run Rancher)

**Comment by onpaws** [comment]
If I understand right, Rancher installs depend on [rancher/charts](https://github.com/rancher/charts).
I speculate my Rancher container might have a stale repo, so maybe I need to run `helm repo update` somewhere.
(Why Rancher wouldn't run that itself, I'm not sure)

I'm not sure where I'd run such a command, assuming that hypothesis is right (I tried the Rancher `local` cluster - no dice)

**Comment by Martin-Weiss** [comment]
I see the same in an environment where I have Kubernetes 1.19.

**Comment by ddelange** [comment]
For me, setting `.Values.useBundledSystemChart` to true ([docs](https://github.com/rancher/rancher/blob/cb7de4e6c3d7e783828dc662b1142c1f9ae5edbe/cmd/rancherd/chart/README.md#L60)) did the trick.

I'm running `v2.6.4-rc17` now from the https://releases.rancher.com/server-charts/latest helm repo ref https://github.com/rancher/rancher/issues/36259#issuecomment-1084434561

**Comment by timmy59100** [comment]
Exact same error with 2.6.4

**Comment by onpaws** [comment]
Shame to hear it's still an issue with 2.6.4 :/

Have you tried @ddelange 's suggestion? https://github.com/rancher/rancher/issues/36114#issuecomment-1084518479

**Comment by timmy59100** [comment]
@onpaws Thanks for the link, i got #37039 on my other cluster when upgrading to 2.6.4 xD.

Is the suggestion possible with the docker installation?

**Comment by onpaws** [comment]
I think so, NB I haven't tried, but based on [this](https://rancher.com/docs/rancher/v2.5/en/installation/resources/feature-flags/#enabling-features-for-kubernetes-installs) looks like you should be able to pass `useBundledSystemChart`

**Comment by timmy59100** [comment]
@onpaws Ah yes, thanks. I tried that, now I just see #37039 ...
