### ISSUE TITLE
Unable to use private repository harbor in webhook

### ISSUE THREAD

**Issue by impactCn** [rancher/rancher#36118]
Current version 1.6.30.

I try to write inside the body of the url that sends the webhook.
```
{
    "push_data": {
        "tag": "latest"
    },
    "repository": {
        "repo_name": "web_package_images/marketing",
        "repo_url": "https://xxx.com"
    }
}
```
but, update unsuccessful.
```
Failed to allocate instance [container:1i494]: Bad instance [container:1i494] in state [error]: Error response from daemon: pull access denied for web_package_images/marketing, repository does not exist or may require 'docker login': denied: requested access to the resource is denie
```

Then I try to use docker login on that server in rancher. also reported the same error.

It seems that the sent urls all go to the docker hub instead of the private warehouse harbar.

**Comment by cbron** [comment]
Rancher version 1.x is no longer supported.
