### ISSUE TITLE
UI: catalog dropdown too small 

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3611]
![image](https://cloud.githubusercontent.com/assets/2150990/13007003/41decbb4-d18d-11e5-87df-bb0d5e5b7f47.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.0` Cattle: `v0.148.0` UI: `v0.90.0` |
|Access|`github` `admin`|
|Route|`null`|

**Comment by lvuch** [comment]
![screen shot 2016-02-16 at 9 04 35 am](https://cloud.githubusercontent.com/assets/3013118/13082231/15b6fe0a-d48d-11e5-95f3-dca89a3c9d3c.png)
I believe this is fixed in https://github.com/rancher/ui/pull/470

**Comment by tfiduccia** [comment]
Version - master 3/3
Verified fixed
