### ISSUE TITLE
[CLI 2.2.0/Rancher 2.6.1] Rancher container log is flooded with messages about token creation requeuing

### ISSUE THREAD

**Issue by aviav** [rancher/rancher#36112]
**Rancher Server Setup**
- Rancher version: originally 2.4.14, now 2.6.1
- Rancher CLI version: 2.2.0, now 2.6.0
- unexpected behavior only started when we used Rancher 2.6.1 and Rancher CLI 2.2.0 concurrently, i.e. after a Rancher update and before a Rancher CLI update
- Installation option (Docker install/Helm Chart): Docker Install

**Information about the Clusters**
- Kubernetes versions: 1.18.20, 1.21.5, and 1.21.6
- Cluster Type (Local/Downstream):
   - Hosted on Hetzner and Digital Ocean

**User Information**
- There were lots of tokens generated for a user with custom, limited permissions as a consequence of this user issuing `rancher kubectl` commands using Rancher CLI
  - This user's permissions are (for completeness, I don't think they matter here)
    - Global: Create RKE Template Revisions, Use Catalogs
    - Clusters: Manage Nodes, and View All Projects, as well as Cluster Owner on two unrelated clusters
    - Project Roles: Manage Workloads
    

   
**Describe the bug(?)**
- Probably due to the way Rancher CLI 2.2.0 and Rancher 2.6.1 interact, lots of ClusterAuthTokens were created, and also lots of ClusterAuthTokens were queued by `cat-token-controller` to be created -- one token per `rancher kubectl` command that was issued via Rancher CLI 2.2.0.

- See [this Gist](https://gist.github.com/aviav/870cf2531c62bc5f76f4ea5bbbd6b8ef) for the list of tokens in one of the clusters involved

- I'm not fully certain that either is a bug, but I think both is unintended behavior.

- As far as I know as of this writing, there is also no 'easy' way to stop messages about some perpetual requeuing of ClusterAuthTokens to be created. After we updated Rancher CLI to 2.6.0, deleted all of the user's tens of thousands of tokens in various clusters, and restarted Rancher, these messages are still flooding the Rancher container's Docker log.

**To Reproduce**
* Issue `rancher kubectl` commands, e.g. `rancher kubectl get pods --all-namespaces`, using Rancher CLI 2.2.0 against multiple clusters that are managed by Rancher 2.6.1
* Each such command will lead to creation of a ClusterAuthToken after it is issued
* When tens of thousands of ClusterAuthTokens have been created in this way -- in our case, one cluster had over 60,000 ClusterAuthTokens -- the Rancher container's log is flooded with messages like
  ```
  2022/01/11 07:55:28 [ERROR] error syncing 'kubeconfig-u-55qztn4gs5': handler cat-token-controller: clusterAuthToken for token [kubeconfig-u-55qztn4gs5] has not been created yet, requeuing
  ```
* After deleting the tens of thousands of tokens that had been created, still, the Rancher log is flooded with these messages, even though no further ClusterAuthTokens are spawned by `rancher kubectl` commands after we updated Rancher CLI to 2.6.0
* Also, restarting the Rancher Docker container after deleting the tokens didn't stop the log flooding
* The remaining issue that I've recently been trying to resolve is that I cannot see how to directly stop the log flooding, i.e. without doing something like setting up a new Rancher server or cluster and moving clusters there. There seems to be some `cat-token-controller` that has some queue, but I don't know how to drain it. If this is something that I should rather ask about in the Rancher Forums, you're welcome to let me know

**Result**
* As described in 'To Reproduce', the Rancher Docker container's log is flooded with messages like
  ```
    2022/01/11 07:55:28 [ERROR] error syncing 'kubeconfig-u-55qztn4gs5': handler cat-token-controller: clusterAuthToken for token [kubeconfig-u-55qztn4gs5] has not been created yet, requeuing
  ```
  * I saved three minutes worth of Rancher log to a text file, and it was 1.8MB big -- almost exclusively containing messages like the above
* None of the clusterAuthTokens that are mentioned in the message are created, though, and it looks like everything is just requeued over and over

**Expected Result**
* I'd expect that after deleting the previously created tokens, now new ClusterAuthTokens are generated again, which I could then delete. 
* Instead, there are just these apparently fruitless log messages creating perpetual noise, and I don't see how to inspect the queue that is mentioned in the messages, or maybe better, how to drain the queue

**Additional context**
- The root problem, creation of lots of ClusterAuthTokens, started when we used CLI 2.2.0 together with Rancher 2.6.1. We only noticed that we hadn't yet updated Rancher CLI about two months after the Rancher update
- Issuing all these `rancher kubectl` commands is our way of monitoring clusters with Nagios through Rancher. We are in the process of adopting Rancher's monitoring tools, though

**Comment by brianbturner82** [comment]
We also seem to have a similar issue, although we don't typically use rancher cli. We just have a lot of the above mentioned 'error syncing' messages in our logs. 

`2022/02/08 17:19:50 [ERROR] error syncing 'kubeconfig-u-vo3b3wris4lgbbt': handler cat-token-controller: clusterAuthToken for token [kubeconfig-u-vo3b3wris4lgbbt] has not been created yet, requeuing`

**Comment by aviav** [comment]
Thanks for your response! It reminds me to add a note about how we solved this for our Rancher.

In the meantime, we got rid of the messages by deleting entries in etcd -- after ensuring that they didn't correspond to actual tokens.

`etcdctl del --prefix /registry/management.cattle.io/tokens/kubeconfig-user-55qzt` worked for us. The prefix could be found using `etcdctl get / --prefix --keys-only` IIRC. Also see [this cheatsheet](https://lzone.de/cheat-sheet/etcd).

All the clusters that are managed by this Rancher instance appear to be operational ten days after we did this.

Note that we had quite some pressure to do _something_ about the tokens -- the node running the Docker container had close to full memory usage at times, and our cloud provider didn't have a server plan with more memory directly available after we had already scaled up multiple times during the past few months. After we deleted the entries in etcd, memory usage dropped quickly, and we have now scaled down our node from 32GB to 4GB again :grin: 

Since I don't see any remaining issues for us, I'll close this issue. Feel free to re-open it if you think the closing happens prematurely
