### ISSUE TITLE
[forwardport] Rancher 2.6 downstream - iptables segfault in RHEL 8.4

### ISSUE THREAD

**Issue by jmcsagdc** [rancher/rancher#36115]
Original ticket for 2.5.x: https://github.com/rancher/rancher/issues/34604

Last repro was on 2.6.2 with a downstream cluster running RHEL 8.4

Downstream cluster:

- ec2 instances: rhel-8.4-docker-20.10.7-selinux-on-rpm
- k8s: v1.20.12-rancher1-2

From the last repro steps of the original issue:

**Validation Steps**

1. Within the custom cluster deploy a workload in the default namespace.

2. From explorer --> pods --> in the kube-system namespace --> Execute shell in one of the Canal pods.

3 . Change the container to kube-flannel, and run the dmesg command.

**Result**
Within the output you will see something similar to:
`[7185.469177] iptables[64524]: segfault at 80 ip 00007f00bd0ed964 sp 00007fff528b1b78 error 4 in libnftnl.so.11.2.0[7f00bd0e8000+19000]`

**Comment by snasovich** [comment]
Ready to test based on https://github.com/rancher/rancher/issues/35709 follow-up issue addressed.

**Comment by Auston-Ivison-Suse** [comment]
**Validation Setup**
Rancher version: 2.6.head(4763f8d)
Helm install


**Validation Steps*
1. Provision clusters using the rhel-8.4-docker-20.10.7-selinux-on-rpm ami
2. Then follow the rest of the steps in the comment [here](https://github.com/rancher/rancher/issues/35709#issuecomment-1020061489) 

**Results**
The issue itself is fixed however the segfault still appears. This has been noted to not have an effect on any deployments. Further info below

**Further Info**

See this [comment](https://github.com/rancher/rancher/issues/36021#issuecomment-1015804526) for previous issues related to this.
