### ISSUE TITLE
File an issue link: "Route" fields not correct

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3612]
![image](https://cloud.githubusercontent.com/assets/2150990/13007038/89241c0e-d18d-11e5-9f0c-d87c7f61effc.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.0` Cattle: `v0.148.0` UI: `v0.90.0` |
|Access|`github` `admin`|
|Route|`null`|

**Comment by vincent99** [comment]
https://github.com/vincent99/ui/commit/748def5a6b487f352e16aa3594ffa85f56bc34a4

**Comment by tfiduccia** [comment]
Version - master UI 3/3
Verified fixed
