### ISSUE TITLE
Rancher UI reload on checkbox click

### ISSUE THREAD

**Issue by brunopiresr** [rancher/rancher#3613]
Hi,

When I am adding a new service and  choose  one permission on device binding section rancher ui redirects to homepage and I lost my service configuration.

I am using Firefox 42.0 with Fedora 22 distribution

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.0` Cattle: `v0.148.0` UI: `v0.90.0` |
|Access|`Disabled`}|
|Route|`null`|

**Comment by deniseschannon** [comment]
I am unable to reproduce in Chrome. @tfiduccia can you look at reproducing in firefox?

**Comment by brunopiresr** [comment]
Hi @deniseschannon, in Chrome works fine.

**Comment by tfiduccia** [comment]
Version - master UI 3/17
Not fixed.  In Firefox it's still refreshing and taking me back to Stacks page.  In Chrome if I remove all three, it's throwing some debug error "component.js:21 Uncaught TypeError: Cannot read property 'join' of null"

**Comment by tfiduccia** [comment]
Version - master UI 3/17
Verified fixed
