### ISSUE TITLE
Migrate area1 images to SLE-BCI

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#36138]
Part of: https://github.com/rancher/rancher/issues/31738

- [x] rancher/rancher - from SLE to SLE-BCI - https://github.com/rancher/rancher/pull/38043
- [x] rancher/rancher-agent - from SLE to SLE-BCI - https://github.com/rancher/rancher/pull/38043
- [x] rancher/kubectl - alpine - https://github.com/rancher/kubectl/pull/7
- [x] rancher/webhook - alpine - https://github.com/rancher/webhook/pull/80
- [x] rancher/shell - alpine - https://github.com/rancher/shell/pull/25

**Comment by macedogm** [comment]
Images migrated outside `team/area1`:

- [ ] `rancher/webhook-receiver` - https://github.com/rancher/webhook-receiver/pull/11

**Comment by macedogm** [comment]
## QA validation template

This validation template is only for images owned by `team/area1`.

### Root cause
Base images used in Rancher's provided containers are not standardized and sometimes outdated.

### What was fixed?
Base images, including build images, were migrated to SLE-BCI, which provides a standardized container base image and faster release of security updates.

### What should be tested?
The images listed below were migrated to SLE-BCI and new tags were generated. The tags must be updated in each dependency (repo and/or Helm chart) and tested. The updated images must function as the previous images.

---

**1. [rancher/shell](https://github.com/rancher/shell)**
- Updated tag: [v0.1.17](https://github.com/rancher/shell/releases/tag/v0.1.17) (pre-release)
- Dependencies
    - Charts
        - rancher-monitoring-crd
          - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-monitoring-crd/100.1.3%2Bup19.0.3/values.yaml#L10-L11
        - prometheus-federator
          - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/prometheus-federator/0.1.0/charts/helmProjectOperator/values.yaml#L179-L180
    - Repos
        - rancher/rancher
            - [ ] https://github.com/rancher/rancher/blob/release/v2.6/pkg/settings/setting.go#L112
            - [ ] https://github.com/rancher/rancher/blob/release/v2.6/tests/v2/validation/charts/monitoring.go#L370
            - [ ] https://github.com/rancher/rancher/blob/release/v2.6/tests/framework/extensions/clusters/import.go#L142
        - rancher/helm-project-operator
            - [ ] https://github.com/rancher/helm-project-operator/blob/main/charts/helm-project-operator/values.yaml#L179-L180
        - rancher/prometheus-federator 
            - [ ] https://github.com/rancher/prometheus-federator/blob/main/charts/prometheus-federator/0.1.0/charts/helmProjectOperator/values.yaml#L179-L180
        - rancher/helm-project-operator
            - [ ] https://github.com/rancher/helm-project-operator/blob/main/charts/helm-project-operator/values.yaml#L179-L180

---

**2. [rancher/webhook](https://github.com/rancher/webhook)**
- Updated tag: [v0.2.6-rc4](https://github.com/rancher/webhook/releases/tag/v0.2.6-rc4) (pre-release)
- Dependencies
  - Charts
    - rancher-webhook
       - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-webhook/1.0.5%2Bup0.2.6-rc3/values.yaml#L2-L3)

---

**3. [rancher/kubectl](https://github.com/rancher/kubectl)**
- **Note:** `rancher/kubectl` image is still [scratch](https://github.com/rancher/kubectl/blob/master/Dockerfile#L12), only the build image was migrate to [SLE-BCI](https://github.com/rancher/kubectl/blob/master/Dockerfile#L1). The tests here don't need to be exhaustive (i.e., not all dependent repos and charts need to be tested). 
- Updated tag: [v1.23.7](https://github.com/rancher/kubectl/releases/tag/v1.23.7) (pre-release)
- Dependencies
   - Charts
      - rancher-gatekeeper
        - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-gatekeeper/100.1.1%2Bup3.7.1/values.yaml#L99-L100
      - rancher-gatekeeper-crd
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-gatekeeper-crd/100.1.1%2Bup3.7.1/values.yaml#L10-L11
      - rancher-k3s-upgrader
         - [ ] https://github.com/rancher/system-charts/blob/dev-v2.6/charts/rancher-k3s-upgrader/0.3.2/values.yaml#L12-L13
      - rancher-webhook
          - [ ] https://github.com/rancher/webhook/blob/master/charts/rancher-webhook/values.yaml#L20-L21
      - system-upgrade-controller
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/system-upgrade-controller/100.0.3%2Bup0.3.2/values.yaml#L12-L13
      - rancher-alerting-drivers
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-alerting-drivers/100.0.2/values.yaml#L10-L11
      - rancher-cis-benchmark
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-cis-benchmark/2.0.5-rc1/values.yaml#L43-L44
      - rancher-backup
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-backup/2.1.2/values.yaml#L50-L5
      - fleet-agent
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/fleet-agent/100.0.3%2Bup0.3.9/values.yaml#L59-L60
      - rancher-project-monitoring
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-project-monitoring/0.1.0/values.yaml#L66-L67
      - rancher-monitoring
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-monitoring/100.1.3%2Bup19.0.3/values.yaml#L604-L605
   - System Charts
      - rancher-monitoring
         - [ ] https://github.com/rancher/system-charts/blob/dev-v2.6/charts/rancher-monitoring/v0.3.2/values.yaml#L394-L395
   - Repos
      - rancher/system-upgrade-controller
         - [ ] https://github.com/rancher/system-upgrade-controller
      - rancher/backup-restore-operator
         - [ ] https://github.com/rancher/backup-restore-operator/blob/master/charts/rancher-backup/values.yaml#L54-L55
      - rancher/prometheus-federator
         - [ ] https://github.com/rancher/prometheus-federator/blob/main/charts/rancher-project-monitoring/0.1.0/values.yaml#L66-L67
      - rancher/webhook
         - [ ] https://github.com/rancher/webhook/blob/master/charts/rancher-webhook/values.yaml#L20-L21

---

### What areas could experience regressions?
No regression is expected.

**Comment by macedogm** [comment]
This is for me to track all the places that I need to propagate the updates.

---

**1. [rancher/shell](https://github.com/rancher/shell)**
- Updated tag: [v0.1.17](https://github.com/rancher/shell/releases/tag/v0.1.17) (pre-release)
- Dependencies
    - Charts
        - rancher-monitoring-crd
          - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-monitoring-crd/100.1.3%2Bup19.0.3/values.yaml#L10-L11
        - prometheus-federator
          - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/prometheus-federator/0.1.0/charts/helmProjectOperator/values.yaml#L179-L180
    - Repos
        - rancher/rancher
            - [ ] https://github.com/rancher/rancher/blob/release/v2.6/pkg/settings/setting.go#L112
            - [ ] https://github.com/rancher/rancher/blob/release/v2.6/tests/v2/validation/charts/monitoring.go#L370
            - [ ] https://github.com/rancher/rancher/blob/release/v2.6/tests/framework/extensions/clusters/import.go#L142
        - rancher/helm-project-operator
            - [ ] https://github.com/rancher/helm-project-operator/blob/main/charts/helm-project-operator/values.yaml#L179-L180
        - rancher/prometheus-federator 
            - [ ] https://github.com/rancher/prometheus-federator/blob/main/charts/prometheus-federator/0.1.0/charts/helmProjectOperator/values.yaml#L179-L180
        - rancher/helm-project-operator
            - [ ] https://github.com/rancher/helm-project-operator/blob/main/charts/helm-project-operator/values.yaml#L179-L180

---

**2. [rancher/webhook](https://github.com/rancher/webhook)**
- Updated tag: [v0.2.6-rc4](https://github.com/rancher/webhook/releases/tag/v0.2.6-rc4) (pre-release)
- Dependencies
  - Charts
    - rancher-webhook
       - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-webhook/1.0.5%2Bup0.2.6-rc3/values.yaml#L2-L3)

---

**3. [rancher/kubectl](https://github.com/rancher/kubectl)**
- **Note:** `rancher/kubectl` image is still [scratch](https://github.com/rancher/kubectl/blob/master/Dockerfile#L12), only the build image was migrate to [SLE-BCI](https://github.com/rancher/kubectl/blob/master/Dockerfile#L1). The tests here don't need to be exhaustive (i.e., not all dependent repos and charts need to be tested). 
- Updated tag: [v1.23.7](https://github.com/rancher/kubectl/releases/tag/v1.23.7) (pre-release)
- Dependencies
   - Charts
      - rancher-gatekeeper
        - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-gatekeeper/100.1.1%2Bup3.7.1/values.yaml#L99-L100
      - rancher-gatekeeper-crd
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-gatekeeper-crd/100.1.1%2Bup3.7.1/values.yaml#L10-L11
      - rancher-k3s-upgrader
         - [ ] https://github.com/rancher/system-charts/blob/dev-v2.6/charts/rancher-k3s-upgrader/0.3.2/values.yaml#L12-L13
      - rancher-webhook
          - [ ] https://github.com/rancher/webhook/blob/master/charts/rancher-webhook/values.yaml#L20-L21
      - system-upgrade-controller
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/system-upgrade-controller/100.0.3%2Bup0.3.2/values.yaml#L12-L13
      - rancher-alerting-drivers
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-alerting-drivers/100.0.2/values.yaml#L10-L11
      - rancher-cis-benchmark
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-cis-benchmark/2.0.5-rc1/values.yaml#L43-L44
      - rancher-backup
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-backup/2.1.2/values.yaml#L50-L5
      - fleet-agent
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/fleet-agent/100.0.3%2Bup0.3.9/values.yaml#L59-L60
      - rancher-project-monitoring
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-project-monitoring/0.1.0/values.yaml#L66-L67
      - rancher-monitoring
         - [ ] https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-monitoring/100.1.3%2Bup19.0.3/values.yaml#L604-L605
   - System Charts
      - rancher-monitoring
         - [ ] https://github.com/rancher/system-charts/blob/dev-v2.6/charts/rancher-monitoring/v0.3.2/values.yaml#L394-L395
   - Repos
      - rancher/system-upgrade-controller
         - [ ] https://github.com/rancher/system-upgrade-controller
      - rancher/backup-restore-operator
         - [ ] https://github.com/rancher/backup-restore-operator/blob/master/charts/rancher-backup/values.yaml#L54-L55
      - rancher/prometheus-federator
         - [ ] https://github.com/rancher/prometheus-federator/blob/main/charts/rancher-project-monitoring/0.1.0/values.yaml#L66-L67
      - rancher/webhook
         - [ ] https://github.com/rancher/webhook/blob/master/charts/rancher-webhook/values.yaml#L20-L21

---

**Comment by anupama2501** [comment]
QA validations require 1 chart validation for each of the tests listed in the comment https://github.com/rancher/rancher/issues/38058
For webhook validation:
```
Global role escalation. Log in as a restricted admin and try to set admin as the default global role.
```

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                     |
| ------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version           | v2.6-c8118e47e9677356d1118382d711532a174bafe7-head                                 |
| Rancher commit link       | https://github.com/rancher/rancher/commit/c8118e47e9677356d1118382d711532a174bafe7 |
| Installation option       | Helm                                                                               |
| RKE binary version used   | v1.3.11                                                                            |
| If Helm Chart k8s cluster | v1.23.6                                                                            |
| Cert Details              | Let's Encrypt                                                                      |
| Helm version              | v2.16.8-rancher2                                                                   |
| Downstream cluster type   | RKE1 Linode                                                                        |
| Downstream K8s version    | v1.24.2-rancher1-1                                                                 |
| Logged in user role       | Administrator                                                                      |
| Browser type              | Firefox Developer Edition                                                          |
| Browser version           | 104.0b3 (64-bit)                                                                   |

**ADDITIONAL SETUP**

- Helm command for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=v2.6-head
```

## Validation steps

<table>
    <tbody>
        <tr>
            <th>Test</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual</th>
            <th>Pass/Fail</th>
        </tr>
        <tr>
            <td>rancher/shell rancher-monitoring-crd</td>
            <td>
                <ol>
                    <li>Install monitoring on the local cluster in system</li>
                    <li>Verify helm install in the rancher shell is successful</li>
                    <li>Make sure the monitoring graphs populate</li>
                </ol>
            </td>
            <td>Monitoring to install successfully and function</td>
            <td>Monitoring was installed successfully and functions</td>
            <td>:white_check_mark: PASS</td>
        </tr>
        <tr>
            <td>rancher/webhook restricted admin escalation</td>
            <td>
                <ol>
                    <li>Create restricted admin user</li>
                    <li>Login as the restricted admin user</li>
                    <li>Attempt to escalate to full admin</li>
                </ol>
            </td>
            <td>admission webhook "rancherauth.cattle.io" denied the request</td>
            <td>admission webhook "rancherauth.cattle.io" denied the request</td>
            <td>:white_check_mark: PASS</td>
        </tr>
        <tr>
            <td>other escalation methods attempted</td>
            <td>redacted</td>
            <td>unable to escalate</td>
            <td>enable to escalate</td>
            <td>:white_check_mark: PASS</td>
        </tr>
    </tbody>
</table>
