### ISSUE TITLE
Adding new hosts - AWS & RancherOS

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#3614]
**Brief Description**
Through the Rancher GUI, i deployed two hosts to AWS using `ami-7989240a` as specified for eu-west-1 at https://github.com/rancher/os/blob/master/README.md These hosts fail to deploy through rancher, the same config but leaving rancher without specifying an AMI works as expected. 

Rancher Release - v0.59.0

Bit sparse of information on this ticket, wasn't sure if it should live here or in rancher/os. Building manually does seem to work.

**Comment by deniseschannon** [comment]
Did you make sure to specify "rancher" as the user? If you leave it blank, then it will use the default ssh user which is ubuntu, which will not work with RancherOS. 

https://docs.docker.com/machine/drivers/aws/

**Comment by Rucknar** [comment]
I use rancherOS all the time, totally knew that but completely missed it! Apologies,
Thanks for the heads up.
