### ISSUE TITLE
 Context canceled

### ISSUE THREAD

**Issue by baturorkun** [rancher/rancher#36149]
I am trying  install rancher 2.6.2

helm install  rancher rancher-stable/rancher \
    --namespace cattle-system  \
    --set hostname=rancher.${LE_WILDCARD} \
    --set ingress.tls.source=secret \
    --set version=v2.6.2 \
    --set replicas=1

I have an error.

```
2022/01/14 11:58:02 [FATAL] Get "https://10.43.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/managedcharts.management.cattle.io?timeout=15m0s": context canceled
```

**Comment by MrSnoozles** [comment]
Think I have a similar issue on 2.6.2. Rancher is starting, but when working with it crashing frequently. The logs show the following:

~~~
I0120 14:35:15.949547     206 leaderelection.go:258] successfully acquired lease kube-system/cattle-controllers
E0120 14:35:16.804256     206 gvks.go:69] failed to sync schemas: failed to sync cache for rke-machine-config.cattle.io/v1, Kind=LinodeConfig
I0120 14:39:50.654776     218 leaderelection.go:248] attempting to acquire leader lease kube-system/cattle-controllers...
I0120 14:39:50.716632     218 leaderelection.go:258] successfully acquired lease kube-system/cattle-controllers
E0120 14:39:51.507942     218 reflector.go:139] pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: Failed to watch *unstructured.Unstructured: Get "https://127.0.0.1:6443/apis/rke-machine.cattle.io/v1/linodemachines?allowWatchBookmarks=true&resourceVersion=59671&timeout=8m8s&timeoutSeconds=488&watch=true": context canceled
E0120 14:39:51.508851     218 gvks.go:69] failed to sync schemas: failed to sync cache for rke-machine.cattle.io/v1, Kind=LinodeMachine
E0120 14:39:53.530454     218 gvks.go:69] failed to sync schemas: failed to sync cache for cluster.x-k8s.io/v1alpha3, Kind=MachineSet
I0120 14:44:15.840615     212 leaderelection.go:248] attempting to acquire leader lease kube-system/cattle-controllers...
I0120 14:44:15.943017     212 leaderelection.go:258] successfully acquired lease kube-system/cattle-controllers
E0120 14:44:16.733016     212 gvks.go:69] failed to sync schemas: failed to sync cache for rke-machine-config.cattle.io/v1, Kind=Amazonec2Config
E0120 14:44:17.000805     212 reflector.go:139] pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: Failed to watch *unstructured.Unstructured: Get "https://127.0.0.1:6443/apis/rke-machine.cattle.io/v1/linodemachines?allowWatchBookmarks=true&resourceVersion=60650&timeout=6m34s&timeoutSeconds=394&watch=true": context canceled
E0120 14:44:17.036947     212 gvks.go:69] failed to sync schemas: failed to sync cache for rke-machine-config.cattle.io/v1, Kind=DigitaloceanConfig
E0120 14:44:17.396030     212 gvks.go:69] failed to sync schemas: failed to sync cache for rke-machine.cattle.io/v1, Kind=AzureMachine
I0120 14:48:41.099870     205 leaderelection.go:248] attempting to acquire leader lease kube-system/cattle-controllers...
I0120 14:48:41.117886     205 leaderelection.go:258] successfully acquired lease kube-system/cattle-controllers
E0120 14:48:42.001610     205 gvks.go:69] failed to sync schemas: failed to sync cache for rke-machine.cattle.io/v1, Kind=Amazonec2MachineTemplate
E0120 14:48:44.114788     205 gvks.go:69] failed to sync schemas: failed to sync cache for cluster.x-k8s.io/v1alpha3, Kind=Cluster
I0120 14:53:10.284655     210 leaderelection.go:248] attempting to acquire leader lease kube-system/cattle-controllers...
I0120 14:53:10.354790     210 leaderelection.go:258] successfully acquired lease kube-system/cattle-controllers
E0120 14:53:12.941030     210 gvks.go:69] failed to sync schemas: failed to sync cache for rke-machine-config.cattle.io/v1, Kind=LinodeConfig
2022/01/20 14:53:17 [INFO] kontainerdriver googlekubernetesengine stopped
2022/01/20 14:53:17 [INFO] dynamic schema for kontainerdriver googlekubernetesengine updating
2022/01/20 14:53:17 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:35315
2022/01/20 14:53:17 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:38481
2022/01/20 14:53:17 [INFO] kontainerdriver azurekubernetesservice stopped
2022/01/20 14:53:17 [INFO] dynamic schema for kontainerdriver azurekubernetesservice updating
2022/01/20 14:53:17 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2022/01/20 14:53:17 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
2022/01/20 14:56:03 [INFO] Shutting down /v1, Kind=Secret workers
2022/01/20 14:56:03 [FATAL] context canceled
~~~

**Comment by rlewkowicz** [comment]
I'm getting a lot of esoteric context canceled issues as well. In general, lots of issues with 2.6

**Comment by baturorkun** [comment]
I tried many times the installation like that I installed 3 nodes ARE by using RKE binary. RKE installation was always successful. But then installation rancher on RKE by using helm has problem. I got always errors or huge timeouts with endless deploy times.

**Comment by dbagarozza** [comment]
we have the same Problem with version 2.6.3 and 2.6.4 on hosted azure aks cluster with helm deployment.

**Comment by JannikZed** [comment]
same here for a rancher HA running on a RKE started cluster. On one node, rancher keeps restarting with this error.

**Comment by tacerus** [comment]
Similar - I thought it "just" runs into a timeout, but it seems to be always the same point, after applying this particular CRD:

```
2022/07/17 22:01:02 [INFO] Applying CRD machinesets.cluster.x-k8s.io
2022/07/17 22:01:06 [FATAL] creating CRD store Get "https://10.43.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions": context canceled
```

**Comment by maeln** [comment]
Same issue. I upgraded from Rancher 2.5 to 2.6.6 and since then Rancher crash once every 24h with the error `[FATAL] context canceled` and no other clue.
Excerpt from the logs:
```
2022-08-01T21:56:18.227097648Z 2022/08/01 21:56:18 [ERROR] error syncing 'token-gvg2j': handler cat-token-controller: clusterAuthToken for token [token-gvg2j] has not been created yet, requeuing
2022-08-01T21:58:18.227640867Z 2022/08/01 21:58:18 [ERROR] error syncing 'token-gvg2j': handler cat-token-controller: clusterAuthToken for token [token-gvg2j] has not been created yet, requeuing
2022-08-01T22:00:02.641257694Z 2022/08/01 22:00:02 [INFO] Shutting down rke.cattle.io/v1, Kind=RKEBootstrap workers
2022-08-01T22:00:02.641334203Z 2022/08/01 22:00:02 [INFO] Shutting down management.cattle.io/v3, Kind=UserAttribute workers
2022-08-01T22:00:02.641361373Z 2022/08/01 22:00:02 [INFO] Shutting down management.cattle.io/v3, Kind=ProjectRoleTemplateBinding workers
2022-08-01T22:00:02.641386312Z 2022/08/01 22:00:02 [INFO] Shutting down apiregistration.k8s.io/v1, Kind=APIService workers
......
2022-08-01T22:00:02.667226315Z 2022/08/01 22:00:02 [INFO] Shutting down /v1, Kind=ReplicationController workers
2022-08-01T22:00:02.667248885Z 2022/08/01 22:00:02 [INFO] Shutting down management.cattle.io/v3, Kind=Group workers
2022-08-01T22:00:02.667272285Z 2022/08/01 22:00:02 [INFO] Shutting down management.cattle.io/v3, Kind=Token workers
2022-08-01T22:00:02.667295844Z 2022/08/01 22:00:02 [INFO] Shutting down admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration workers
2022-08-01T22:00:02.667370154Z 2022/08/01 22:00:02 [INFO] Shutting down management.cattle.io/v3, Kind=User workers
2022-08-01T22:00:02.667393843Z 2022/08/01 22:00:02 [INFO] Shutting down management.cattle.io/v3, Kind=Cluster workers
2022-08-01T22:00:02.667416763Z 2022/08/01 22:00:02 [INFO] Shutting down project.cattle.io/v3, Kind=SourceCodeRepository workers
2022-08-01T22:00:02.667439473Z 2022/08/01 22:00:02 [INFO] Shutting down management.cattle.io/v3, Kind=GroupMember workers
2022-08-01T22:00:02.667922778Z 2022/08/01 22:00:02 [FATAL] context canceled
2022-08-01T22:00:02.667971297Z 2022/08/01 22:00:02 [INFO] Shutting down project.cattle.io/v3, Kind=App workers
```

**Comment by BhautikChudasama** [comment]
Got the same issue in helm chart v2.6.8.

**Comment by tacerus** [comment]
This is still relevant.

**Comment by shimondoodkin** [comment]
I had similar error but , had two orchestrators on same cluster in different namespaces,
one was turning on, another was turning off, a prometheus statefullset.
(the prometheus was installed from stackgress docs I think.)
this cause multiple restarts that exhausted max watchers. interfered with rancher monitoring.

the kubernetes also had high cpu in htop most of was in kube-apiserver, so I looked into the logs of it, 
then I saw in kubernetes api server, log a lots of failed http requests. 

probably this pathway of failed requests is not optimized. at takes a lot of cpu.

I deleted the namespaces that caused the errors
and increased the I notify max watchers limit
restarted a few things and it got back to normal.

----
to see the api server log:
kubectl get pods -n kube-system -l component=kube-apiserver
kubectl logs podname  -n kube-system

----
max watchers fix:

see limits
sysctl fs.inotify

see used count

curl -s https://raw.githubusercontent.com/fatso83/dotfiles/525747ff48e7bb10231f26385f09ca1346c62a7f/utils/scripts/inotify-consumers | bash


i created file:

/etc/sysctl.d/20-inotify.conf :

fs.inotify.max_user_instances=8192
fs.inotify.max_user_watches=1048576


reload the config from system files:
sysctl --system

**Comment by tacerus** [comment]
This is still relevant.

**Comment by shimondoodkin** [comment]
The error is from that there is enough CPU and memory.

The problem is from resources are spent a lot on errors. The errors pathway
is not optimized and it takes a lot of CPU.

If I remember well Check the logs of kube api sever. You will see there
restarts and api call failures.

See the errors. Then delete the things that cause the errors. Like web
hooks that don't work. Find not needed resources while looking at resources
in a namespaces. See partially deleted namespaces and delete them fully.
When the api server will calm down you will be able to have lower cpu

**Comment by tacerus** [comment]
I understand there are "insufficient" computing resources based on Rancher's requirements. However not everyone has such fast hardware, especially if the deployment is just intended for a lab or development scenario. The timeouts hardcoded in the resource files are very low - I personally often don't care if the application takes 5 or 30 minutes to deploy and would be more than happy to wait longer than the current timeouts allow.

It would be great to have the timeouts increased and to have them exposed as configurable Helm values.

**Comment by shimondoodkin** [comment]
I meant It is not related to resources. When there is an error the system
overwhelms itself.
It calls api too many times and wastes resources. The error pathway is
neglected.

As i think on it.
It is an api error handling problem.

I recall that
Bitcoin trading platforms solve it with  412 backoff request error. The
client side must obay. It could ve based on quota or business of the server.

Also need it to not take so much resources when there is an error and hit
the api in a loop.

**Comment by shimondoodkin** [comment]
I agree it is good idea to solve to this issue. It is very confusing.
