### ISSUE TITLE
[BUG] Rancher Harvester Node driver sticks in Downloading state

### ISSUE THREAD

**Issue by bclinuxco** [rancher/rancher#36153]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s on arm64
- Proxy/Cert Details: Cert Manager /w Rancher generated certificate

**Information about the Cluster**
- Kubernetes version: v1.22.5+k3s1
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
When running 2.6.3 Rancher console on an arm64 host to manage Harvester cluster the Harvester Node Driver remains stuck in a "Downloading" state.

**To Reproduce**
1. Deploy Rancher 2.6.3 on a arm64 Kubernetes cluster (K3S in my case)
2. Install Harvester 1.0.0 on a machine as initial cluster
3. Perform "Import Existing" under Virtualization Management in Rancher and allow to complete
4. Navigate to Cluster Management -> Drivers -> Node Drivers
5. Harvester driver still remains in Downloading state 48 hours after Harvester cluster import
6. Harvester does not show up as an available Cloud provider under Cluster Creation
7. Harvester node driver package can be successfully downloaded with wget or curl

**Result**
Harvester driver still remains in Downloading state 48 hours after Harvester cluster import
Harvester does not show up as an available Cloud provider under Cluster Creation

**Expected Result**
Harvester Node Driver finishes download and Harvester shows up as an available Cloud Provider for RKE2 provisioning

**Screenshots**
![Screenshot_20220114_130049](https://user-images.githubusercontent.com/26132238/149575115-868c4b1d-ee66-4099-8ff8-9cd9f854102e.png)
![Screenshot_20220114_130146](https://user-images.githubusercontent.com/26132238/149575157-32710e29-6719-4da7-8fcc-1b9fdcecbb5c.png)

**Comment by be99inner** [comment]
I face the same problem. Actually, it can't do any update/deactivate/activate on the node driver.
- Rancher 2.6.4
- K3s v1.22.7+k3s1
- Installation option: Helm

**Comment by ionfury** [comment]
I have the exact same issue

- Rancher 2.7.0
- K3s v1.24.9-rc1+k3s1
- Harvester 1.1.1
- Installation via Helm

**Comment by osci-khoj** [comment]
I haver the exact same issue, too 
Rancher 2.7.9 ( installed on k3s( v1.26.11+k3s1)  on rasberrypi4 using ubuntu 22.04 
K3s v1.26.10+k3s2
Harvester v1.2.1

**Comment by gregkonush** [comment]
This is still happening on the arm, can we re-open this issue?
