### ISSUE TITLE
No stats available for both hosts and containers

### ISSUE THREAD

**Issue by jonvargas** [rancher/rancher#3616]
**Brief:**

The statistical blocks are not displayed for both containers and hosts detail views.

**Environment:**

Rancher	v0.59.0
Cattle	v0.148.0
User Interface	v0.90.0
Rancher Compose	v0.7.2
Rancher server installed on bare metal and used as a host too.

Container view:
http://i.imgur.com/6JGzCWI.png

Host view:
http://i.imgur.com/Z6VFjCn.png

**Comment by sfarges** [comment]
Same as #3384 ?

**Comment by deniseschannon** [comment]
What version of Docker are you using? If using Docker 1.10, it's a duplicate of https://github.com/rancher/rancher/issues/3615

**Comment by deniseschannon** [comment]
Closing in favor of the other 2 issues.
