### ISSUE TITLE
Allow copy/paste in "Execute Shell"

### ISSUE THREAD

**Issue by Thom-x** [rancher/rancher#3617]
When executing shell into container it would be nice to be able to copy/paste into it.
Maybe using : 
- <kbd>Insert</kbd> => Paste
- Text selection + <kbd>Shift</kbd> => Copy

**Comment by Rucknar** [comment]
You can already do this, if you right click inside the shell you can copy selected text. Likewise, you can paste through that same menu.

**Comment by vincent99** [comment]
@Rucknar *: In some browsers (I think maybe only Chrome for Mac OS)

**Comment by vincent99** [comment]
#2181

**Comment by banderlog** [comment]
This bug hits again on macOSX with any browser I tested -- Firefox, Google Chrome, Safari

Copy\Paste works only outside the terminal multiplexers (screen, tmux). In terminal multiplexers it does not work on session re-connection.

**Comment by zquall** [comment]
You can copy and paste with the current Chrome on windows. The issue here is that the highlight doesn't show up. But if you just  select with the mouse (use your imagination for the highlight) then copy (it can be right click, Copy) you will be able to paste the data somewere else

**Comment by vincent99** [comment]
This is a 5 year old issue with no relation to and no code in common with either of the current UIs.  The problem with the highlight color in Cluster Explorer + light theme was [fixed](https://github.com/rancher/dashboard/commit/9a50a6b742ce91ff4d76f4714ebb850c536adc21) in 2.5.4.
