### ISSUE TITLE
K3S Cluster 1.22.5 cannot be managed or imported to rancher 2.5.11 I/o timeout 

### ISSUE THREAD

**Issue by nzkller** [rancher/rancher#36171]
**Rancher Server Setup**
- Rancher version: rancherd version v2.5.11 (HEAD) go version go1.16.4
- Installation option (Docker install/Helm Chart):  curl -sfL https://get.rancher.io | sh -
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details: Self-signed

**Information about the Cluster**
- Kubernetes version: k3s v1.22.5+k3s1
- Cluster Type (Local/Downstream):
 Custom k3s (8 x Raspberry pi 4 4GB) 1 x Master,  7 x Workers

NAME           STATUS   ROLES                  AGE   VERSION
kubeworker01   Ready    <none>                 26d   v1.22.5+k3s1
kubeworker03   Ready    <none>                 26d   v1.22.5+k3s1
kubeworker04   Ready    <none>                 23d   v1.22.5+k3s1
kubeworker07   Ready    <none>                 23d   v1.22.5+k3s1
kubeworker05   Ready    <none>                 23d   v1.22.5+k3s1
kubemaster01   Ready    control-plane,master   26d   v1.22.5+k3s1
kubeworker06   Ready    <none>                 23d   v1.22.5+k3s1
kubeworker02   Ready    <none>                 26d   v1.22.5+k3s1

  
**Describe the bug**

Rancher cannot longer import the cluster. It was working but of the blue I started getting these messages

Cluster health check failed: Failed to communicate with API server during namespace check: Get "https://10.43.0.1:443/api/v1/namespaces/kube-system?timeout=45s": write tcp 10.42.0.6:443->10.150.3.11:4514: i/o timeout and then I couldn't get it to manage the cluster anymore.

**To Reproduce**

I have deleted the cluster from ranchers reinstalled rancher, tried a docker version 2.6.3 and nothing.

I configured to correctly the API to run the ARM image version of the rancher agent

**Result**

The state of the pod is in crash loopbackoff

Pod logs

INFO: Environment: CATTLE_ADDRESS=10.42.0.167 CATTLE_CA_CHECKSUM=82d83d7a97030f965aaf9bd590782a2e2d4faaa91ff9aa625dca7756df742271 CATTLE_CLUSTER=true CATTLE_CLUSTER_REGISTRY= CATTLE_FEATURES= CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-899575bd-6gtlq CATTLE_SERVER=https://10.150.2.10:8443
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.43.0.10 options ndots:5
INFO: https://10.150.2.10:8443/ping is accessible
INFO: Value from https://10.150.2.10:8443/v3/settings/cacerts is an x509 certificate
time="2022-01-18T07:02:13Z" level=info msg="Listening on /tmp/log.sock"
time="2022-01-18T07:02:13Z" level=info msg="Rancher agent version v2.5.11 is starting"
time="2022-01-18T07:02:13Z" level=info msg="Connecting to wss://10.150.2.10:8443/v3/connect/register with token ddqdfg6r66l9gfq92t8zs99q6khpnlqvtz9z467plst44gjnpggsd2"
time="2022-01-18T07:02:13Z" level=info msg="Connecting to proxy" url="wss://10.150.2.10:8443/v3/connect/register"
time="2022-01-18T07:02:13Z" level=info msg="Starting user controllers"
time="2022-01-18T07:02:13Z" level=fatal msg="the server could not find the requested resource"

**Expected Result**

For the Pod to be running correctly and the API available for Rancher

**Comment by vavallee** [comment]
Same issue

**Comment by icircletech** [comment]
I have this issue as well.

**Comment by nzkller** [comment]
Was anyone able to fix this issue?

I'm watching closely if a new version 2.5.12, to see this will fix this issue.

Best regards,

**Comment by jgreat** [comment]
Doesn't look like 2.5.12 supports k3s v1.23 or v1.22 yet.   

Doesn't look like v1.21 is technically in the downstream cluster [support matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-5-12/) but it does seem to work.

Does 2.6.3 support v1.23/v1.22 yet? I only see v1.21 in that matrix, but I'm not sure if that gets updated with every release.

**Comment by cloudnautique** [comment]
The highest version of K8s that will be supported in Rancher 2.5.x is 1.20.x.
Rancher 2.6 has full support for 1.21, and experimental support for 1.22.

**Comment by nzkller** [comment]
Hello,

The weird thing is that it was working before with no problem and then it stopped working.

I just fix this by using Rancher version 2.6.3 as advised and it worked right away.

Thank you for pointing the version issue. I tried to understand the matrix but honestly it wasn't that clear to me.

Best regards,

CD

**Comment by ccenjie** [comment]
???
