### ISSUE TITLE
New Charts in v2.5.12

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#36184]
System charts (v1) `rancher/system-charts:dev-v2.5`:

Name                 | Version  | Backend Dev(s)
---------------------| -------- | -----------
||||||

Feature charts (v2) `rancher/charts:dev-v2.5`:

Name                       | Version           | Note                 | Backend Dev(s) | rancher-max of prev chart
-------------------------------| -------------------------- |----------------------|----------- | -----------
Longhorn|1.2.300+up1.2.3||@innobead||
Longhorn|1.1.300+up1.1.3||@innobead||
rancher-alerting-drivers|1.0.301||@jiaqiluo||
rancher-backup|1.2.100+up1.2.1||@superseb|<2.5.99-0|
rancher-istio|1.10.400||@brendarearden|>= 2.5.0-0 <= 2.5.99-0|
rancher-kiali-server|1.35.100+up1.35.0||@brendarearden||
rancher-logging|3.15.0||@paynejacob@Anna Blendermann|<2.5.99-0|
rancher-monitoring|16.6.1+up16.6.0||@jiaqliuo||
rancher-vsphere-csi|2.3.1||@pennyscissors|>= 2.5.0-0 <= 2.5.99-0|
rancher-webhook|0.1.300+up0.1.3||@aiyengar2||

**Comment by sgapanovich** [comment]
Verified the following charts on 2.5.12-rc4:

| Name | expected version | actual version | expected rancher | actual rancher |  result |
| -------- | ------- | ------- | ------- | ------- | ------- | 
| Longhorn | 1.2.300+up1.2.3 | 1.2.300+up1.2.3 |  | <2.5.99-0 | MATCH |
| Longhorn | 1.1.300+up1.1.3 | 1.1.300+up1.1.3 |  | <2.5.99-0 | MATCH |
| rancher-alerting-drivers | 1.0.301 | 1.0.301 |  | >= 2.5.0-0 <= 2.5.99-0 | MATCH | 
| rancher-backup | 1.2.100+up1.2.1 | 1.2.100-rc1+up1.2.1-rc1 | <2.5.99-0 | <2.5.99-0 | MATCH (!) rc needs to be removed | 
| rancher-istio | 1.10.400 | 1.10.400 | >= 2.5.0-0 <= 2.5.99-0 | >= 2.5.0-0 <= 2.5.99-0 | MATCH | 
| rancher-kiali-server | 1.35.100+up1.35.0 | 1.35.100+up1.35.0 |  |  | MATCH | 
| rancher-logging | 3.15.0 | 3.15.0 | <2.5.99-0 | <2.5.99-0 | MATCH | 
| rancher-monitoring  | 16.6.1+up16.6.0 | 16.6.1+up16.6.0 |  |  | MATCH | 
| rancher-monitoring-crd | 16.6.1+up16.6.0 | 16.6.1+up16.6.0 |  |  | MATCH | 
| rancher-vsphere-csi | 2.3.1 | 2.3.1 | >= 2.5.0-0 <= 2.5.99-0 | >= 2.5.0-0 <= 2.5.99-0 | MATCH | 
| rancher-webhook | 0.1.300+up0.1.3 | 0.1.300-rc1+up0.1.3-rc1 |  |  | MATCH (!) rc needs to be removed |

**Comment by SheilaghM** [comment]
@sgapanovich - rancher-webhook and rancher-backup-restore-operator have been unRC'd.  Can you please verify that they're still good?

**Comment by brendarearden** [comment]
Available to test in v2.5.12-rc7

**Comment by sgapanovich** [comment]
check webhook and rancher-backup
both apps are ready to be releases
rancher-images.txt has no issues

![webhook](https://user-images.githubusercontent.com/40282141/150877403-17987037-677b-4e71-87ad-5c953f1c4e54.jpg)
![backup](https://user-images.githubusercontent.com/40282141/150877407-fe36b049-7ad9-41bb-8156-bb6448e81013.jpg)

**Comment by sgapanovich** [comment]
@brendarearden checked that charts are unRC'd. please tag a final RC
