### ISSUE TITLE
[2.6.3][EKS] Cluster capacity metrics not being populated on the Cluster Dashboard

### ISSUE THREAD

**Issue by niranjan94** [rancher/rancher#36186]
**Rancher Server Setup**
- Rancher version: `2.6.3`
- Installation option: `Single-node docker`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `1.21.2`
- Cluster Type: `Hosted - EKS`
- Rancher monitoring chart version: `v100.1.0+up19.0.3`

**User Information**
- What is the role of the user logged in? `Admin`
   
**Describe the bug**
On the Cluster Dashboard, the information about the reserved CPU/Memory is not being displayed correctly. Total is displayed, but current value is not.

**To Reproduce**
1. Import EKS cluster with EKS Managed node groups
2. Install rancher monitoring 
3. See cluster dashboard

**Result**
For CPU/Memory total is displayed, but current value is not.

**Expected Result**
The information about current reserved CPU/Memory should be populated correctly 

**Screenshots**
<img width="1664" alt="Screenshot 2022-01-19 at 11 33 16 AM" src="https://user-images.githubusercontent.com/2404372/150073463-a49306d5-08f0-42e9-aea6-2b61f9d13259.png">

**Comment by ganapathi-s** [comment]
Facing same issue in  AKS imported cluster as well

**Comment by xantygc** [comment]
Same issue

Amazon EKS Cluster
Rancher 2.6.3
Kubernetes 1.21.5

![image](https://user-images.githubusercontent.com/783492/162399681-cedc00ee-88ab-4577-92db-a709fb97e99d.png)

**Comment by skirsch-alethix** [comment]
Same.

Amazon EKS Cluster
Rancher 2.6.3
Kubernetes 1.21.9

![image](https://user-images.githubusercontent.com/40701325/168808152-83dac3ca-bef0-4781-a818-7854ac56ef17.png)
