### ISSUE TITLE
Failed to dial steve aggregation server: websocket: bad handshake rancher 2.6.2

### ISSUE THREAD

**Issue by nickvth** [rancher/rancher#36187]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: none

**Information about the Cluster**
- Kubernetes version: 1.20.x
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Cluster Owner

**Describe the bug**
Everthing is functional, but every +/- 5 seconds in rancher log: [ERROR] Failed to dial steve aggregation server: websocket: bad handshake

We don't have this on rancher 2.5.11

**To Reproduce**
run rancher on rke and have downstream clusters

**Result**

**Expected Result**
No error [ERROR] Failed to dial steve aggregation server: websocket: bad handshake

**Comment by hahchenchen** [comment]
I have the same problem, do you solved it?

**Comment by nickvth** [comment]
@hahchenchen Do you run in cattle-system namespace? Do you run rancher in rke cluster what is provisioned with rancher?

**Comment by csgergo123** [comment]
I confirm that this problem still persists. I want to import a Digital Ocean Kubernetes cluster in Rancher 2.6.5.
I added it using the kubectl command from the Cluster Management / Import Existing / Generic interface in Rancher.
In the cattle-system namespace, the cattle-cluster-agent pods starts but gets stuck here:
`time="2022-06-30T10:46:12Z" level=error msg="Failed to dial steve aggregation server: websocket: bad handshake"`

**Comment by Bluefries** [comment]
Same Here

**Comment by seb-835** [comment]
@csgergo123 do you finally succeed to add it ? 

i am getting the same issue, using a rancher 2.6.6, and trying to import a 1.23.3 kubernet cluster, 
the agent  failed with logs : Failed to dial steve aggregation server: websocket: bad handshake.

Any tips ?

**Comment by chitha20** [comment]
we are getting same issue , any clues on how to get it fixed ?

**Comment by dyegodiniz** [comment]
Same here. Anyone find something?

**Comment by wonleing** [comment]
so many same problems here, why it is closed with no explaination?

**Comment by joereyna** [comment]
I'm getting this problem too.

**Comment by guydolinksy** [comment]
In case it might help some of you:

In my case it turned out the rancher server uri in `global settings` had a trailing `/` which resulted in the agent connecting to `<rancher-url>`**//**`v3/connect` forcing a redirect and getting a "bad handshake" error.

You can verify this is the case by decoding the base64 strings in the `stv-aggregation` secret of the downstream cluster, specifically the one named `url`.

Removing the trailing `/` in the global settings of the rancher server then removing and readding the downstream node solved the issue.

**Comment by jiaxinonly** [comment]
> In case it might help some of you:
> 
> In my case it turned out the rancher server uri in `global settings` had a trailing `/` which resulted in the agent connecting to `<rancher-url>`**//**`v3/connect` forcing a redirect and getting a "bad handshake" error.
> 
> You can verify this is the case by decoding the base64 strings in the `stv-aggregation` secret of the downstream cluster, specifically the one named `url`.
> 
> Removing the trailing `/` in the global settings of the rancher server then removing and readding the downstream node solved the issue.

Removing the trailing `/` in the global settings of the server-url，It worked for me。

**Comment by tanwarsatya** [comment]
> > In case it might help some of you:
> > In my case it turned out the rancher server uri in `global settings` had a trailing `/` which resulted in the agent connecting to `<rancher-url>`**//**`v3/connect` forcing a redirect and getting a "bad handshake" error.
> > You can verify this is the case by decoding the base64 strings in the `stv-aggregation` secret of the downstream cluster, specifically the one named `url`.
> > Removing the trailing `/` in the global settings of the rancher server then removing and readding the downstream node solved the issue.
> 
> Removing the trailing / in the global settings of the server-url，It worked for me。 e.g: https://rancher.xxx.com/ --> https://rancher.xxx.com

This is a god sent.. thanks for replying with the findings. This worked for me as well.

**Comment by liuyuexizhi** [comment]
> > In case it might help some of you:
> > In my case it turned out the rancher server uri in `global settings` had a trailing `/` which resulted in the agent connecting to `<rancher-url>`**//**`v3/connect` forcing a redirect and getting a "bad handshake" error.
> > You can verify this is the case by decoding the base64 strings in the `stv-aggregation` secret of the downstream cluster, specifically the one named `url`.
> > Removing the trailing `/` in the global settings of the rancher server then removing and readding the downstream node solved the issue.
> 
> Removing the trailing / in the global settings of the server-url，It worked for me。 e.g: https://rancher.xxx.com/ --> https://rancher.xxx.com

Thank you very much, it is help for me.
