### ISSUE TITLE
Hairpin NAT not working with load balancer

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3618]
v0.59.0
Docker 1.10

Steps to Reproduce:
1. Create a service (nginx) and a load balancer in front of it. 
2. Exec into the network agent on the host that has the load balancer
3. Try to curl the load balancer using the internal IP of the host

Result: `curl (52) Empty reply from server`

**Comment by ndarilek** [comment]
I don't know if it makes a difference, but all of my tests have been while SSH'd directly into the host, not exec'd into any containers.

I'm hosting a Docker registry behind a load balancer. Images can be pulled from other hosts but ideally I'd like them to work wherever, even if the image is deployed to the same host. So all of my tests have been attempting to connect to back-ends through load balancers directly from the host.

Thanks.

**Comment by kaos** [comment]
+1

**Comment by legoheld** [comment]
+1

**Comment by mtrofimm** [comment]
+1

**Comment by kaos** [comment]
Just want to add that `curl $(hostname):${LB_publicPort}` fails when run from the physical agent node as well.

Compare these two scenarios.. against two different containers:
First, I `curl` locally from the host (I get the same results if a use `localhost` instead of "`agent`")
```
[root@agent ~]# docker ps | grep '80/tcp'
5ea5e143ebc2        reg:8181/someimg/develop:0.2.1-46   "nginx -g 'daemon off"   19 hours ago        Up 19 hours         443/tcp, 0.0.0.0:7908->80/tcp                                      foo-bar-name
...
2cbed1294ab7        reg:8181/rancher/agent-instance:server-0.59.0   "/etc/init.d/agent-in"   45 hours ago        Up 18 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:9200->9200/tcp   4782a6e7-40ad-4e1f-bf64-677fc3199c0b # this is the LB service
...
[root@agent ~]# curl -v -I agent:7908
* About to connect() to agent port 7908 (#0)
*   Trying 10.3.x.x...
* Connected to agent (10.3.x.x) port 7908 (#0)
> HEAD / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: agent:7908
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Server: nginx/1.9.4
Server: nginx/1.9.4
< Date: Fri, 19 Feb 2016 08:37:15 GMT
Date: Fri, 19 Feb 2016 08:37:15 GMT
< Content-Type: text/html
Content-Type: text/html
< Content-Length: 1235
Content-Length: 1235
< Last-Modified: Mon, 28 Sep 2015 06:48:49 GMT
Last-Modified: Mon, 28 Sep 2015 06:48:49 GMT
< Connection: keep-alive
Connection: keep-alive
< ETag: "5608e2d1-4d3"
ETag: "5608e2d1-4d3"
< Accept-Ranges: bytes
Accept-Ranges: bytes

< 
* Connection #0 to host agent left intact
[root@agent ~]# curl -v -I agent:80
* About to connect() to agent port 80 (#0)
*   Trying 10.3.x.x...
* Förbindelse vägras
* Failed connect to agent:80; Connection refused
* Closing connection 0
curl: (7) Failed connect to agent:80; Connection refused
[root@agent ~]# 
```

Now, from another host (my laptop), against the same services/ports:
```
$ curl -v -I agent:7908
* Rebuilt URL to: agent:7908/
*   Trying 10.3.x.x...
* Connected to agent (10.3.x.x) port 7908 (#0)
> HEAD / HTTP/1.1
> Host: agent:7908
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Server: nginx/1.9.4
Server: nginx/1.9.4
< Date: Fri, 19 Feb 2016 08:45:50 GMT
Date: Fri, 19 Feb 2016 08:45:50 GMT
< Content-Type: text/html
Content-Type: text/html
< Content-Length: 1235
Content-Length: 1235
< Last-Modified: Mon, 28 Sep 2015 06:48:49 GMT
Last-Modified: Mon, 28 Sep 2015 06:48:49 GMT
< Connection: keep-alive
Connection: keep-alive
< ETag: "5608e2d1-4d3"
ETag: "5608e2d1-4d3"
< Accept-Ranges: bytes
Accept-Ranges: bytes

< 
* Connection #0 to host agent left intact
$ curl -v -I agent:80
* Rebuilt URL to: agent:80/
*   Trying 10.3.x.x...
* Connected to agent (10.3.x.x) port 80 (#0)
> HEAD / HTTP/1.1
> Host: agent
> User-Agent: curl/7.43.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 503 Service Unavailable
HTTP/1.0 503 Service Unavailable
< Cache-Control: no-cache
Cache-Control: no-cache
< Connection: close
Connection: close
< Content-Type: text/html
Content-Type: text/html

< 
* Excess found in a non pipelined read: excess = 108 url = / (zero-length body)
* Closing connection 0
```

Voila, `agent:80` is responding ok, and there it is in a nutshell.

So traffic originating from the agent node, isn't routed properly.

Footnote: `agent` is really known by another name ;) but it is a physical machine running a docker daemon and rancher-agent container, etc...

**Comment by kaos** [comment]
Ps.

For the record, I managed to work around this issue using a service alias, and linking that to the services that need it using the external dns name so they get straight to the LB service without hitting the public IP of the agent node.

It was easy enough once I had a clear picture of what the real issue was. (Had I been a iptables ninja, I could probably solved it better..)

**Comment by deadbeef84** [comment]
Did some research on this, dont think it has anything to do with iptables, but an invalid bind in haproxy.cfg
```
$ docker exec -it r-loadbalancer_loadbalancer_1 bash
$ netstat -tlpn | grep 80
tcp        0      0 10.42.199.228:80        0.0.0.0:*               LISTEN      286/haproxy
$ grep bind /etc/haproxy/haproxy.cfg 
        bind 10.42.199.228:80
        bind 0.0.0.0:42
```

Changing it to 0.0.0.0:80 should be sufficient, but I'm not sure if there's any other reason not to listen to all interfaces? Perhaps this should be dependent on the Private/Public setting? Also not sure where/how the haproxy.cfg is generated. Would be nice to see this fixed soon as it would simplify development for me.

**Comment by kaos** [comment]
@deadbeef84 nice find. There's been a fix about two weeks ago related to that: https://github.com/rancher/cattle/commit/5ae1b1c75c8e65760b72a315f149a28f09055fac#diff-bd8c082f1061009fdaa267e2d1068427

**Comment by kaos** [comment]
I'm not at work now to check this, but if @deadbeef84 is right, I guess this issue would be for @alena1108 rather than Darren.. ;)

**Comment by deadbeef84** [comment]
@kaos the commit you are referring to fixes only configuration of the health-check port, but yeah the fix should be quite similar to implement.

**Comment by alena1108** [comment]
@kaos @deadbeef84 will be one liner fix by changing

https://github.com/rancher/cattle/blob/dc084fdc6a5efceef4723352b1e8b4bd2a08d833/resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl#L102

to 

```
bind *:${defaultPort}
```

**Comment by alena1108** [comment]
@deadbeef84 @kaos thank you for debugging, assigned the bug to myself, not @ibuildthecloud issue

**Comment by manei** [comment]
Thank god you fixed this. It messed up our environments and we did not have a clue as why a telnet from a docker container to an address resolved (by and external DNS) to HAproxy on the same machine won't work. Nice catch @deadbeef84 

Looking forward for the release!

**Comment by deniseschannon** [comment]
Verified with v0.63.0-rc1.

SSHed into the host as well as exec into the network agent.

Curl the internal IP:port returns as expected.

**Comment by kaos** [comment]
:pray:

**Comment by legoheld** [comment]
:pray: thank you!

**Comment by kaos** [comment]
confirmed :dart: :+1: :smile:
