### ISSUE TITLE
Sharing hosts across environments

### ISSUE THREAD

**Issue by markrey** [rancher/rancher#3619]
We are creating "sort of" PaaS based on Rancher for internal development purpose.

- I would like to check if it is possible to share one host across multiple environments so can be used by multiple users.
- Their docker containers inside the hosts should be always hidden ( isolated ) from other environments.

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/583

**Comment by markrey** [comment]
Thanks Denise. I was trying to find the same.
