### ISSUE TITLE
rancher-compose have a status option

### ISSUE THREAD

**Issue by mrproper** [rancher/rancher#3620]
pr to have rancher-compose also have a status of the stack to see both the individual service health and the overall stack health

**Comment by mrproper** [comment]
also a non 0 exit code if the overall stack health is not healthy

**Comment by tombmurphy** [comment]
+1

**Comment by andyshinn** [comment]
Possible duplicate of https://github.com/rancher/rancher/issues/2958.

**Comment by deniseschannon** [comment]
Similar to #2958, but it sounds like it would be an individual command to check on services/stack status

**Comment by deniseschannon** [comment]
Instead of adding this into Rancher Compose, we recommend using the new [Rancher CLI](http://docs.rancher.com/rancher/cli/) which supports `rancher stacks`, which would show the stack status and `rancher ps` would show service status. 

```
$ rancher stacks
ID           NAME      STATE     CATALOG   SYSTEM    DETAIL
1e364     Default   healthy             false     
$ rancher ps
rancher ps
ID           TYPE      NAME           IMAGE            STATE     SCALE     ENDPOINTS   DETAIL
1s722     service   Default/test   ubuntu:14.04.3   healthy  
```
