### ISSUE TITLE
etcd backups 'thrash' when multiple backups occur at once (i.e. user starts manual backup, and recurring backup starts before manual backup finishes)

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36209]
**Rancher Server Setup**
- Rancher version: v2.5.12-rc2
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): n/a
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:any version
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): any provider

**User Information**
- What is the role of the user logged in? admin

   
**Describe the bug**

If multiple backups are occurring at once, there is some thrashing between the backups, prolonging the time it takes for a backup to complete. 

**To Reproduce**
 
* provision a downstream cluster and set the backup storage to s3 with valid credentials
 * once the cluster is active, take a manual snapshot at the same time as the first automatic backup occurs

**Result**
* the two backups will compete for the first slot in the queue.  This can result in the first backup taken with an earlier timestamp, but actually taken after the second backup. It also is not optimal as the backups take time to resolve which will be backed up first. 

**Expected Result**

we should queue the 2nd backup and wait for the first backup to complete before attempting any others. 

**Screenshots**

**Additional context**

found when testing https://github.com/rancher/rancher/issues/36038

also worth noting -- with 2 simultaneous backups, they seem to succeed. however 3 or more, only the last 2 backups taken will succeed and the others have errors instead of completing

**Comment by slickwarren** [comment]
see https://github.com/rancher/rancher/issues/36210#issuecomment-1032076311 for testing

**Comment by timhaneunsoo** [comment]
Tested this issue on RKE1 and RKE2. RKE1 seems to be fixed, but RKE2 is blocked by

**Comment by jakefhyde** [comment]
@timhaneunsoo This only affects RKE1, so RKE2 doesn't need to be tested (although RKE2 may still need to be tested for GA, it would be unrelated to this issue)

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 8ebbb18
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE1 node driver

----------

### Testing: ###

Tested this issue with the following:
1. Adding multiple backups at the same time sees them finish in order from oldest to newest, running one at a time
2. Recurring backups are not created until the previous recurring backup is finished
3. Deleting a backup before it has been started
4. Deleting a backup after it has been started, but before it has finished
5. Deleting a recurring backup when an older backup exists should not delete the older backup until at least retention backups exist. (These backups are not required to necessarily be successful, this is a known issue, has always existed, and is not targeted for this release).

**Result** - Pass

1. Adding multiple backups at the same time sees them finish in order from oldest to newest, running one at a time - Pass
2. Recurring backups are not created until the previous recurring backup is finished - Pass
3. Deleting a backup before it has been started - Pass
4. Deleting a backup after it has been started, but before it has finished - Pass
5. Deleting a recurring backup when an older backup exists should not delete the older backup until at least retention backups exist. (These backups are not required to necessarily be successful, this is a known issue, has always existed, and is not targeted for this release). - When recurring backup is deleted and none are left, a new recurring backup is triggered. Will keep a look out when this scenario is supported in future release
