### ISSUE TITLE
Helm release secret with no data causes a cluster-agent crash

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#36214]
Issue description:

If a helm release secret has no data in it, it causes the cluster-agent to crash loop with:

 

goroutine 3894 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3e891a0, 0xc0171e5608)
/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/runtime/runtime.go:48 +0x86
panic(0x3e891a0, 0xc0171e5608)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/catalogv2/helm.decodeHelm3(0x0, 0x0, 0x7ff13782dcc0, 0xc0033bca38, 0x61324d3152346701)

 

Business impact:

Low

Repro steps:

    Create a release secret with helm metadata, but no actual data. Ie:

    apiVersion: v1
    data:
    kind: Secret
    metadata:
      labels:
        name: break-me
        owner: helm
        version: "4"
      name: break-me
      namespace: cloud-platform
    type: helm.sh/release.v1

Workaround:
Is workararound available and implemented? yes
What is the workaround: delete secret, as it's invalid anyway

Actual behavior:

Cluster-agent crash loops while trying to decode the release

Expected behavior:

Invalid data is handled gracefully, without a crash

Files, logs, traces:
<text>

Additional notes:
Haven't yet found a way to reproduce this in the wild, but 2 separate customers have reported it. Both are unsure how the secret was created and think an end user manually added it.

SURE-3733

**Comment by niusmallnan** [comment]
similar issue: https://github.com/rancher/rancher/issues/35971

**Comment by l4zy0n3** [comment]
Verified on rancher v2.7-head
Rancher helm and docker installations
