### ISSUE TITLE
Rancher logs spammed with RoleBinding.rbac.authorization.k8s.io  is invalid: when any auth group is assigned restricted admin global role

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36216]
**Rancher Server Setup**
- Rancher version: `v2.6.3`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.21.3+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 3 worker, 1 etcd, 1 cp`
`RKE1`

**Describe the bug**
When an auth group is assigned a global role in the groups a global role, we see the rancher logs are spammed with error logs.

**To Reproduce**
1. Enable auth - I tried with azure AD and openLDAP
2. From global auth --> groups --> assign a role from the auth as a restricted admin.
3. A global role binding is created for the group in the global role bindings:
4. Verify the rancher logs as soon as the group is added

**Result**
As soon as the group is added, we see the following logs scroll through continuously:
```
 error syncing 'grb-hmhsb': handler restrictedAdminGlobalBindingsFleet: 1 error occurred:
	* RoleBinding.rbac.authorization.k8s.io "grb-hmhsb-fleetworkspace-restricted-admin-rb-cluster" is invalid: subjects[0].name: Required value
```

**Expected Result**
Did not expect the error logs when the group is added in the rancher server

**Additional context**

SURE-3845

**Comment by cbron** [comment]
Hey @MbolotSuse looks like you backported to 2.5 also, can you make a secondary issue and put it into 2.5.13 milestone. 
The rancher PR for 2.6 is here: https://github.com/rancher/rancher/pull/36466

**Comment by anupama2501** [comment]
Verified on v2.6-head d4089da docker install, helm install
 Error logs mentioned in the ticket are not seen for a fresh install and upgrade case.



**Re-opening:**

However, if we create a downstream cluster after adding an auth group as restricted admin, we see the following error logs.

```
 [INFO] [node-controller-rancher-machine] Installing Docker from: https://releases.rancher.com/install-docker/20.10.sh
2022/02/18 00:33:42 
[ERROR] error syncing 'c-4qtwm': handler restrictedAdminsRBACCluster: 1 error occurred:
 * RoleBinding.rbac.authorization.k8s.io "grb-4jkrb-restricted-admin-rb-cluster" is invalid: subjects[0].name: Required value
Thu, Feb 17 2022 4:33:42 pm

```

These are the steps I tried:

- Enabled openldap from auth providers
- From groups >> added an auth group as restricted admin
- Create a downstream cluster - rke1 or rke2 node drivers
- The above mentioned logs are seen

**Comment by anupama2501** [comment]
Closing this ticket as the issue mentioned ^^ is addressed in another security ticket.
