### ISSUE TITLE
JSON syntax error when entering cloud credentials for azure -- SyntaxError: Unexpected token S in JSON at position 204

### ISSUE THREAD

**Issue by jamesongithub** [rancher/rancher#36221]
**Rancher Server Setup**
- Rancher version: v2.6.2
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k8s: 1.20.9 on AKS
- Proxy/Cert Details: self signed

**Information about the Cluster**
- Kubernetes version: 1.20.9
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

Getting an JSON syntax error after entering azure cloud credentail

`SyntaxError: Unexpected token S in JSON at position 204`

Seems to happen randomly. Sometimes happens, sometime not.

Seems to occur more often when there are no cloud credentials stored.

**To Reproduce**
 
. Add AKS Cluster
. Add Cloud credential 

**Result**
. UI displaying error message after entering an azure cloud credential.  

`SyntaxError: Unexpected token S in JSON at position 204`

**Expected Result**

No errors after entering cloud credential

**Screenshots**

![image](https://user-images.githubusercontent.com/4452738/150458166-471b89df-3d5e-4ee4-8b05-85bd7f422746.png)

**Additional context**

Cloud credential seems to work afterwards, so perhaps just an erroneous message.

**Comment by jamesongithub** [comment]
bump

**Comment by strossan** [comment]
I'm having similar issue, with Rancher 2.6.3 and AKS 1.21.7

**Comment by strossan** [comment]
I was able to import an AKS cluster in Rancher with Import any Kubernetes cluster function. 
My setup is Rancher 2.6.4 and AKS 1.21.7

**Comment by jamesongithub** [comment]
bump

**Comment by lomori-nference** [comment]
I'm seeing this too. Show stopper.

**Comment by tuxicorn** [comment]
I am having similar issue when trying to create an AKS cluster with the UI, Rancher 2.6 and AKS 1.22.11.

**Comment by jamesongithub** [comment]
bp

**Comment by jamesongithub** [comment]
cmt

**Comment by josephaw1022** [comment]
I can confirm that I also am having trouble with trying to create an aks cluster and experiencing a json error

**Comment by felipemachado12** [comment]
I can confirm, same issue, but in my case it says: `Failed to load Clusters from Azure: Expected ',' or '}' after property value in JSON at position 208` when I try to import existing cluster

And `SyntaxError: Expected ',' or '}' after property value in JSON at position 208` when I try to create a cluster
