### ISSUE TITLE
v2.6.x Harvester provisioning fails, pods can't validate legit certificates

### ISSUE THREAD

**Issue by atoy3731** [rancher/rancher#36227]
**Rancher Server Setup**
- Rancher version: v2.6.x (checked against v2.6.2, v2.6.3)
- Installation option: Helm (K3s v1.21.4+k3s1)
- Proxy/Cert Details: LetsEncrypt Certificate

**Information about the Cluster**
- Kubernetes version: 1.21.4+k3s1
- Rancher Cluster Type: Local on ProxMox
- Downstream Cluster Type: Harvester (utilizing Harvester provisioning)

**User Information**
- Admin User

**Describe the bug**

When using Harvester provisioning of either an RKE2 cluster or K3s cluster, it appears both the Rancher pods and the provisioner pods creating by the Harvester provider have SSL errors when calling not only back to Rancher itself (which is using a legit LetsEncrypt certificate), but also to any HTTPS site (for instance, https://www.google.com).

It appears that inside of the pods, they are not using the system standard CA certificates to be able to validate legit certificates.

**To Reproduce**

* Simple Docker Rancher Test (Run the following script):
  ```
  docker pull rancher/rancher:v2.6.3
  docker run -d --name rancher-test --privileged rancher/rancher:v2.6.3
  docker exec -it rancher-test curl -v https://www.google.com
  docker rm -f rancher-test
  ```

* Harvester Provisioning:
  1. Create a Harvester deployment.
  2. Register Harvester with Rancher MCM.
  3. Create either an RKE2 or K3s cluster (can be single node pool) via the Harvester provisioner.
  4. Check the provisioning logs for errors.

**Result**

Both of the above will result in some form of CA/x509 error similar to the following:

```
*   Trying 142.250.188.196:443...
* TCP_NODELAY set
* Connected to www.google.com (142.250.188.196) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/rancher/ssl
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Expected Result**

Pods will utilize the default CA certificate within the pod and not result in x509 errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/5939985/150557947-bee880b9-c5fa-4b30-b069-6886f3a34364.png)

**Additional context**

CA validation works fine in v2.5.x, potential this could be caused by the migration from Ubuntu to SLES.

v2.5.x:
```
root@dbf8ced01bdf:/var/lib/rancher# cat /etc/os-release | grep PRETTY
PRETTY_NAME="Ubuntu 18.04.6 LTS"
root@dbf8ced01bdf:/var/lib/rancher# curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

v2.6.x:
```
abee17ec7da4:/var/lib/rancher # cat /etc/os-release | grep PRETTY
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
abee17ec7da4:/var/lib/rancher # curl --version
curl 7.66.0 (x86_64-suse-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1d-fips zlib/1.2.11 libidn2/2.2.0 libpsl/0.20.1 (+libidn2/2.0.4) libssh/0.8.7/openssl/zlib nghttp2/1.40.0
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by Madchristian** [comment]
Is there a workaround for this issue?

**Comment by palmergw** [comment]
I'm having the same issue. From what I've read, these pods are supposed to really only be set up for internal communication with Rancher.

That said, I had this error on 2.6.3 and it seems to come from the rancher/machine codebase. I saw some commits/releases related to updating certs within that repo, so I updated to 2.6.4 to take advantage of those changes. That did not resolve the issue for me.

Within Rancher, I did use the ```--set additionalTrustedCAs=true``` flag in helm, and populated ```tls-ca-additional``` secret in cattle-system. This allows my cattle-system pods to successfully curl my rancher instance, but **not** google.

When I set up Harvester and attempt to provision a cluster (RKE1/RKE2/K3s, all error our for me), I get the error you captured in your screenshot.
```
Downloading driver from https://rancher.home.lab/assets/docker-machine-driver-harvester
--
Sun, Apr 3 2022 4:59:15 pm | Doing /etc/rancher/ssl
Sun, Apr 3 2022 4:59:24 pm | WARNING: Skipping duplicate certificate additional-ca.crt
Sun, Apr 3 2022 4:59:30 pm | docker-machine-driver-harvester
Sun, Apr 3 2022 4:59:30 pm | docker-machine-driver-harvester: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
Sun, Apr 3 2022 4:59:31 pm | Trying to access option which does not exist
Sun, Apr 3 2022 4:59:31 pm | THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
Sun, Apr 3 2022 4:59:31 pm | Type assertion did not go smoothly to string for key
Sun, Apr 3 2022 4:59:31 pm | Running pre-create checks...
Sun, Apr 3 2022 4:59:33 pm | Error with pre-create check: "Get \"https://rancher.home.lab/k8s/clusters/c-m-zrshdjzq/apis/harvesterhci.io/v1beta1/settings/server-version\": x509: certificate signed by unknown authority"
Sun, Apr 3 2022 4:59:33 pm | The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
```
If I forcibly inject the ISRG Root X1 cert into the docker/machine container, clone it to pass it into /etc/rancher/ssl, then spin it back up and quickly shell into it, I can see that I can curl https://rancher.plmr.cloud.

However, the container still bombs out trying to validate the cert (log with injected cert above).

**Comment by palmergw** [comment]
I wound up accidentally tearing down and reinstalling Rancher during an upgrade where I wasn't paying attention.
```
Rancher 2.6.4
Kubernetes 1.22.7
 ```
With these versions, I was able to auto-provision new clusters.
