### ISSUE TITLE
[rancher-compose] rm is not waiting for the removal to finish

### ISSUE THREAD

**Issue by pvalsecc** [rancher/rancher#3622]
I have a Travis script that does that:
```
rancher-compose -p "${stack}" rm --force
rancher-compose -p "${stack}" up --pull --recreate --force-recreate --confirm-upgrade -d
```

In my composition, I have the db setup as an external service:
```
db:
  image: rancher/external-service
```

My Travis runs the script, I often end up having the db container missing even though rancher-compose says it started it:
```
$ rancher-compose -p "${stack}" rm --force
...
INFO[0002] [0/7] [db]: Deleted
...
INFO[0002] [0/7] [db]: Deleted
...
$ rancher-compose -p "${stack}" up --pull --recreate --force-recreate --confirm-upgrade -d
...
INFO[0003] [0/7] [db]: Starting
INFO[0003] [1/7] [db]: Started
...
```

But, after that, on the rancher pages, the `db` container is not there. I have a feeling the deletion is not actually finished before I do my `up` and the `db` is actually deleted just after it is started. I've seen sometimes other containers not restarted either.

Yes, doing a `rm` followed by a `up` is a bit non-standard, but I want the latested and greatest to be pushed to Rancher without having to do a new release. This stack is just there to have a look at the current development status. We have other stacks that have proper releases that can be upgraded in a proper way.

The versions used are ranche-compose v0.7.1 (will test 0.7.2 soon) and rancher 0.59.0.

**Comment by deniseschannon** [comment]
It sounds like you're trying to an upgrade to your service, as you are using the `--confirm-upgrade`, but your service isn't in an `upgraded` state. 

http://docs.rancher.com/rancher/rancher-compose/upgrading/ 

As an external service, what are you trying to do? I'm not sure I understand.

**Comment by pvalsecc** [comment]
As an external service (Continuous Integration), I want to take all the images I've generated with a `latest` tag, taking into account the fact that:
* the UUID in my rancher-compose file is not changing (I don't want to change this file every commit).
* the images may change.
* the answers to the questions may change.
* new questions may come up.
* the docker-compose file may change.
* I don't care about this stack answering 100% of the time.
* must be fully automated.

That is the reason why I do a `rm` first to make sure I cleanup everything first. This is the best solution I've found so far. But it doesn't support changes to the answers, without me deleting the stack manually before the CI kicks in.

I've added a `sleep 30` between the `rm` and the `up` and I didn't have the problem described in this issue anymore.

**Comment by deniseschannon** [comment]
It sounds like your `sleep 30` has fixed your issues so I will close.

**Comment by pvalsecc** [comment]
I would IMHO not call that a fix, but a work around...

**Comment by juliangamble** [comment]
It sounds like this is still an open issue: https://github.com/rancher/rancher/issues/4736

**Comment by pvalsecc** [comment]
`<rant>`Yes, but don't worry, your issue will be closed soon. You can just put a sleep after the rm.`</rant>`
