### ISSUE TITLE
CPU, memory, and pods are not correct on most K8s 1.20.13 and 1.20.14 clusters

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#36229]
Internal reference: SURE-3854
Reported in 2.6.3.

*Issue description:*

On the dashboard, most k3s 1.20.13 clusters are showing 0 for CPU, memory, and pods. K3s clusters running 1.20.12 appear to be fine.

*Business impact:*
Cosmetic

*Troubleshooting steps:*
none

*Repro steps:*
 * Add k3s 1.20.13 downstream cluster
 * Go to dashboard

*Workaround:*
 Is workaround available and implemented? unknown
 What is the workaround:

*Actual behavior:*
Memory, CPU, pods showing as 0 for many clusters.

*Expected behavior:*
Memory, CPU, pods should be accurately displayed.

![Screen Shot 2022-01-21 at 12 13 41 PM](https://user-images.githubusercontent.com/20599230/150586637-8be9034b-6e66-4c27-b01f-04ac35e1fa4c.png)

**Comment by dnoland1** [comment]
FYI - Also seeing this on k3s 1.20.14

**Comment by thehejik** [comment]
Also seeing this on `rancher:2.6.4-alpha3` with imported RKE2 `v1.21.9+rke2r1` cluster (+ the same for Generic Imported cluster - CaaSP). Local RKE2 cluster is showing proper info.

![caasp_on_rancherz](https://user-images.githubusercontent.com/12828077/151178881-eabc70a7-efde-481f-a895-230035cb167c.png)

**Comment by annablender** [comment]
I reproduced what appears to be a similar issue, if not the same one, on rancher 2.6.3.

I deployed two k3s downstream clusters, one with kubernetes v1.21.10 and 5 nodes and one with kubernetes v1.22.7 with one node.

The v1.21.10 k3s cluster displayed pod resources incorrectly. With 5 nodes at 2GB per node, it should have used about 10 GB but it says it only used 1.23 GB. The other stats are off as well. The v1.22.7 k3s cluster stats displayed correctly. I agree this is a backend issue, but unsure of the cause yet.

![image](https://user-images.githubusercontent.com/12955547/159366241-5f1ee4f7-676a-4d34-975f-b49c78d69223.png)

![image](https://user-images.githubusercontent.com/12955547/159366258-8405c1c5-0759-44cc-906b-83173346de72.png)

![image](https://user-images.githubusercontent.com/12955547/159366280-0c6fcdb2-57d6-462a-b40f-df1fd21ef741.png)

**Comment by annablender** [comment]
Investigation update.

I did some deep investigation into the pod aggregation logic from Darren's PR https://github.com/rancher/rancher/commit/3453a429bf4107dde095dfcf0256daf93ec6ffb3 and found no issues with the computation logic. I went back and deployed several rke2 clusters on rancher 2.6-head, with 1, 3, and 5 node clusters. I compared the actual pod requests for three of these clusters with the pod requests (Reserved Cores, Reversed Memory) displayed in the UI.

![image](https://user-images.githubusercontent.com/12955547/159770450-f7f953dd-1dce-432e-8e39-3d9d53eaa185.png)

Here are my results

```
k3s-downstream-v1.23.4 single node
pod requests (actual)
- cpu: 1220m
- mem: 238mi
pod requests (UI)
- 1.22 / 2c
- 238mi

rke2/k3s downstream (v1.21.10 and v1.23.4) 3 node
pod requests (actual)
- cpu: 2170m
- mem: 366mi
pod requests (UI)
- cpu: 0.8 / 4c
- mem: 0.3 / 7.68GB

rke downstream v1.21.0 5 node
pod requests (actual)
- cpu: 2520m
- mem: 636mi
pod requests (UI)
- cpu: 1.5 / 8c
- mem: 0.48 / 15GB
```

**Comment by annablender** [comment]
My original pod request counts were correct but there are no bugs in the pod aggregation logic. CPU and mem requests are aggregated in the stats controller across v3 mgmt nodes, but only for worker nodes. So the values seen above were correct for my clusters.

I was not able to repro this issue for any custom k3s/rke2 clusters on rancher 2.6.3.

I _was_ able to reproduce the 0 pod count on an rke2 imported cluster.

0% CPU requests, 0% Mem requests for worker nodes
(requests exists in some pod yamls, so there should be non-zero request values)

![image](https://user-images.githubusercontent.com/12955547/160164288-ccc53875-4679-4202-bdc0-822c6aa96ed2.png)

![image](https://user-images.githubusercontent.com/12955547/160164471-40d31b5a-4295-49a4-9be4-2c3a85d6d80d.png)

**Comment by annablender** [comment]
I did some testing for consistent reproducibility with rke2 imported clusters of 2, 3, and 4 nodes (1 cpu, the rest workers) but the 0 pod count never showed up again for me. I was using k8s 1.22.8 though.. @fgielow is that for custom AKS clusters in rancher or imported ones?

**Comment by annablender** [comment]
Update: the _one time_ I have seen this issue reproduced is on rancher 2.6-head with an RKE2 imported cluster with kubernetes 1.22.7.

Today, I tested the following
* rancher 2.6-head, AKS imported cluster with kubernetes 1.21.7 (example above)
* rancher 2.6-head, RKE2 imported cluster with kubernetes 1.22.7 4 nodes
* rancher 2.6.3, RKE2 imported cluster with kubernetes 1.22.7 4 nodes

All CPU and memory requests were normal in the UI. I thought maybe it was reproducible on a specific kubernetes version after I saw the above comment, but am seeing no indication of that. Will discuss further with the team how to proceed with this elusive issue.

**Comment by annablender** [comment]
This issue is going to be backlogged.

The _one time_ I have seen this issue reproduced was on rancher 2.6-head with an RKE2 imported cluster with kubernetes 1.22.7.

Repro steps
* Create a 4 node RKE2 cluster in digital ocean
* Run Rancher 2.6-head on another digital ocean node
* Import the cluster
* View cpu/mem

![image](https://user-images.githubusercontent.com/12955547/162528105-9a839031-35ac-4bff-89ef-b3da7e88b565.png)

![image](https://user-images.githubusercontent.com/12955547/162528116-775f60e6-fa7a-4eba-ac65-4c8009a607e2.png)

Since then, I have been unable to reproduce it again and get to the bottom of the issue. 

The `statsaggregator` controller received 0 requested pods, cpu, and mem for all 4 machines on the cluster. That means that the resources are also 0 on the v1 nodes. The question is how they got to be 0 on the downstream nodes which gets copied to the v3 node ResourceList.

**Comment by annablender** [comment]
This issue has been satisfactorily resolved for the original customer by upgrading to 2.6.4. If it reproduces again, I will investigate the nodesyncer.

**Comment by annablender** [comment]
## Testing template

#### Root cause

Unsure of the primary cause, but testing points to an intermittent issue with the NodeSyncer controller which syncs the `pod-request` and `pod-limit` annotations from v1 to v3 nodes. It's also possible the requested CPU, memory, and pods were ending up as zero on the downstream nodes somehow. Issue was very difficult to reproduce so could not get to the bottom of the issue.
 
#### What was fixed, or what changes have occurred

Original customer upgraded to 2.6.4. That fixed the stats for most of their clusters in the Rancher UI.

#### Areas or cases that should be tested

Repro steps
* Run a Hosted Rancher instance
* Create 24 2-node downstream clusters with k3s 1.20.15+k3s1
* Check pods, requested cpu, and requested memory for the clusters in the Rancher UI. No more than 2 clusters should have zero values. Most will be correct.

#### What areas could experience regressions ?
 
Stats display in the Rancher UI.

#### Are the repro steps accurate/minimal ?

Yes.

**Comment by Josh-Diamond** [comment]
Ticket #36229 - Test Results

With Docker on single-node instance:

Reproduction Failure on rancher `v2.6-cd0555bcb56b64317939fac01e1e98f214f96c08-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision 24 downstream 2-node AWS Node driver clusters with k8s `v1.20.13+k3s1`  - [version in original issue above]
3. From the `Home`, view cluster stats
4. From `Cluster Explorer`, view cluster stats
5. Reproduction Failure - All clusters `Active`, with accurately displayed metrics

Screenshots:

`Home`
<img width="1230" alt="Screen Shot 2022-04-12 at 1 08 22 PM" src="https://user-images.githubusercontent.com/46494969/163046948-0b33d93b-9378-40c4-8ec5-15f017f2420c.png">
<img width="1252" alt="Screen Shot 2022-04-12 at 1 08 39 PM" src="https://user-images.githubusercontent.com/46494969/163046969-34cf1017-797f-415a-b6c8-00165f3e86aa.png">

`Cluster Explorer`
<img width="1613" alt="Screen Shot 2022-04-12 at 1 28 14 PM" src="https://user-images.githubusercontent.com/46494969/163048141-d93aef7f-ea31-4e4e-867e-cf195c67da88.png">

<img width="1615" alt="Screen Shot 2022-04-12 at 1 29 13 PM" src="https://user-images.githubusercontent.com/46494969/163048222-46bb3fd9-ea32-4717-861b-1e6206c81b84.png">

<img width="1614" alt="Screen Shot 2022-04-12 at 1 30 04 PM" src="https://user-images.githubusercontent.com/46494969/163048325-b6b4c9d0-93e1-4e0a-abb6-2c3912896a30.png">

<img width="1611" alt="Screen Shot 2022-04-12 at 1 30 35 PM" src="https://user-images.githubusercontent.com/46494969/163048396-691905c3-4ea0-4d89-b39a-a8a767d890ff.png">

<img width="1608" alt="Screen Shot 2022-04-12 at 1 31 08 PM" src="https://user-images.githubusercontent.com/46494969/163048471-20a00856-8591-49be-9361-0589cacecc95.png">

<img width="1609" alt="Screen Shot 2022-04-12 at 1 31 34 PM" src="https://user-images.githubusercontent.com/46494969/163048540-ef45c234-24a1-43e6-a439-291d1a2cfe9f.png">

<img width="1609" alt="Screen Shot 2022-04-12 at 1 32 38 PM" src="https://user-images.githubusercontent.com/46494969/163048741-9162a10c-2899-4905-8a15-0c5576d1550b.png">

<img width="1612" alt="Screen Shot 2022-04-12 at 1 33 03 PM" src="https://user-images.githubusercontent.com/46494969/163048818-7cbfecb6-c1aa-4c7b-ae7b-019c45ed5034.png">

<img width="1610" alt="Screen Shot 2022-04-12 at 1 33 42 PM" src="https://user-images.githubusercontent.com/46494969/163048929-ba2ce509-3959-41ca-9702-9161e8fee01b.png">

<img width="1609" alt="Screen Shot 2022-04-12 at 1 34 11 PM" src="https://user-images.githubusercontent.com/46494969/163049007-0e29069e-df28-4ab3-85d7-3f79397b77f3.png">

<img width="1608" alt="Screen Shot 2022-04-12 at 1 34 40 PM" src="https://user-images.githubusercontent.com/46494969/163049083-46ec5809-13b4-44ba-98d9-d7dcea2b9b4e.png">

<img width="1608" alt="Screen Shot 2022-04-12 at 1 35 08 PM" src="https://user-images.githubusercontent.com/46494969/163049176-02e1250b-5508-450c-b159-37f192ecbcbf.png">

<img width="1613" alt="Screen Shot 2022-04-12 at 1 35 42 PM" src="https://user-images.githubusercontent.com/46494969/163049253-1eb23bc7-4620-40d8-8183-ac84aba6ba3b.png">

<img width="1610" alt="Screen Shot 2022-04-12 at 1 36 20 PM" src="https://user-images.githubusercontent.com/46494969/163049329-d1add908-16c6-4947-ac53-1ae833a20674.png">

<img width="1610" alt="Screen Shot 2022-04-12 at 1 36 50 PM" src="https://user-images.githubusercontent.com/46494969/163049403-8298ce7a-31b0-4e83-9f1d-bc31727005af.png">

<img width="1609" alt="Screen Shot 2022-04-12 at 1 37 22 PM" src="https://user-images.githubusercontent.com/46494969/163049484-406cf7cd-8dc6-417f-b6e2-16ab0f470be3.png">

<img width="1609" alt="Screen Shot 2022-04-12 at 1 38 11 PM" src="https://user-images.githubusercontent.com/46494969/163049593-e1ba0433-3acd-4b80-a824-abaa781eded2.png">

<img width="1610" alt="Screen Shot 2022-04-12 at 1 38 39 PM" src="https://user-images.githubusercontent.com/46494969/163049650-159b0972-50c8-47f1-bf05-1b269045eca2.png">

<img width="1611" alt="Screen Shot 2022-04-12 at 1 39 23 PM" src="https://user-images.githubusercontent.com/46494969/163049751-36d95516-a5ec-4b7e-afa5-1745b099faf1.png">

<img width="1612" alt="Screen Shot 2022-04-12 at 1 39 51 PM" src="https://user-images.githubusercontent.com/46494969/163049813-b9f5d3fa-f854-4e14-8a06-8635e566a047.png">

<img width="1609" alt="Screen Shot 2022-04-12 at 1 40 20 PM" src="https://user-images.githubusercontent.com/46494969/163049882-d21b462f-6bc4-4855-bd37-b383410483ff.png">

<img width="1609" alt="Screen Shot 2022-04-12 at 1 40 46 PM" src="https://user-images.githubusercontent.com/46494969/163049963-4f2b22db-f8ec-4eaf-8c3a-f87e1204206c.png">

<img width="1610" alt="Screen Shot 2022-04-12 at 1 41 21 PM" src="https://user-images.githubusercontent.com/46494969/163050043-48ceff7f-9102-4588-8c81-f48d70d89456.png">

<img width="1608" alt="Screen Shot 2022-04-12 at 1 41 51 PM" src="https://user-images.githubusercontent.com/46494969/163050108-313d10af-35f6-4b86-bce4-eacb8e9e4135.png">
