### ISSUE TITLE
fleet gitrepo says, "first path segment in URL cannot contain colon " while adding gitrepo with ssh URL

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#36228]
Issue description:
While adding the gitrepo with git ssh URL "git@github.com:sadhugit/fleet-examples.git": its failing with "first path segment in URL cannot contain colon"  where as https repo url is working fine*.*

 

Business impact:

Troubleshooting steps:
It can reproduce easily . Just need to add git repoSSH URL

Repro steps:

    Navigate to "Continuous Delivery" page
    Try to create gitrepo, with a git url like ""git@git.xyz.com*:*unix/rancher-fleet.git"

Actual behavior:
 Fleet is saying the repo url is invalid and failing with "first path segment in URL cannot contain colon"

apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"fleet.cattle.io/v1alpha1","kind":"GitRepo","metadata":{"annotations":
{"meta.helm.sh/release-name":"rancher-fleet-gitrepo","meta.helm.sh/release-namespace":"default"}

,"labels":{"app.kubernetes.io/managed-by":"Helm"},"name":"rancher-fleet-gitrepo","namespace":"fleet-default"},"spec":{"branch":"master","clientSecretName":"rancher-fleet","paths":["managedApps"],"repo":"git@git.xyz.com:unix/rancher-fleet.git"}}
meta.helm.sh/release-name: rancher-fleet-gitrepo
meta.helm.sh/release-namespace: default
creationTimestamp: "2021-05-11T20:42:09Z"
generation: 2
labels:
app.kubernetes.io/managed-by: Helm
managedFields:

    apiVersion: fleet.cattle.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
    f:status:
    .: {}
    f:conditions: {}
    f:desiredReadyClusters: {}
    f:display:
    .: {}
    f:readyBundleDeployments: {}
    f:state: {}
    f:observedGeneration: {}
    f:readyClusters: {}
    f:resourceCounts:
    .: {}
    f:desiredReady: {}
    f:missing: {}
    f:modified: {}
    f:notReady: {}
    f:orphaned: {}
    f:ready: {}
    f:unknown: {}
    f:waitApplied: {}
    f:summary:
    .: {}
    f:desiredReady: {}
    f:ready: {}
    manager: fleetcontroller
    operation: Update
    time: "2021-05-11T20:42:09Z"
    apiVersion: fleet.cattle.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
    f:metadata:
    f:annotations:
    .: {}
    f:kubectl.kubernetes.io/last-applied-configuration: {}
    f:meta.helm.sh/release-name: {}
    f:meta.helm.sh/release-namespace: {}
    f:labels:
    .: {}
    f:app.kubernetes.io/managed-by: {}
    f:spec:
    .: {}
    f:branch: {}
    f:clientSecretName: {}
    f:paths: {}
    f:repo: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-05-11T20:42:09Z"
    name: rancher-fleet-gitrepo
    namespace: fleet-default
    resourceVersion: "420850950"
    uid: 1d9f3c12-0831-43de-87b0-67e3419fb111
    spec:
    branch: master
    clientSecretName: rancher-fleet
    paths:
    managedApps
    repo: git@git.xyz.com:unix/rancher-fleet.git
    status:
    conditions:
    lastUpdateTime: "2021-05-11T20:42:09Z"
    status: "True"
    type: Ready
    lastUpdateTime: "2021-05-11T20:44:17Z"
    status: "True"
    type: Accepted
    lastUpdateTime: "2021-05-11T20:42:09Z"
    status: "False"
    type: Reconciling
    lastUpdateTime: "2021-05-11T20:44:17Z"
    message: 'parse "git@git.xyz.com:unix/rancher-fleet.git": first path segment
    in URL cannot contain colon'
    reason: Stalled
    status: "True"
    type: Stalled
    lastUpdateTime: "2021-05-11T20:44:17Z"
    status: "True"
    type: Synced
    desiredReadyClusters: 0
    display:
    readyBundleDeployments: 0/0
    state: GitUpdating
    observedGeneration: 2
    readyClusters: 0
    resourceCounts:
    desiredReady: 0
    missing: 0
    modified: 0
    notReady: 0
    orphaned: 0
    ready: 0
    unknown: 0
    waitApplied: 0
    summary:
    desiredReady: 0
    ready: 0

 

Expected behavior:
Should able to create the git repo with SSH based URL successfully with our any issues.

 

Files, logs, traces:
NA

Additional notes:
Customer says it worked earlier and in rancher 2.5.8 its not working.
SURE-3001

**Comment by prachidamle** [comment]
I could not reproduce this with 2.6-head and Fleet release v0.3.9-rc3.

**Comment by davidnuzik** [comment]
**I cannot reproduce this issue on Rancher v2.6.3. I would recommend the customer try upgrading Rancher to the latest released version (2.6.3 currently).**
 
**Reproduction Environment:**

Rancher version: v2.6.3
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2 (does not matter)
Downstream K8s version: v1.21.9+rke2r1 (not relevant)
 
**Reproduction steps:**

1. Create a GitRepo. On the form, fill in the following, then click on the Create button:
- Any valid name
- For the Respository URL, enter the ssh url for your repo. In my case this is `git@github.com:rancher/fleet-examples.git` but the repo you test with (outside of the Rancher organization) will vary.
- Under the "Git Authentication" drop-down, pick "Create a SSH Key Secret" and provide your public and private key.
- Click the "Add Path" button and enter `/simple`
2. The GitRepo is successfully created without any errors.

![image](https://user-images.githubusercontent.com/45179589/155424535-8bcfdc29-7b9d-4ae1-908f-a183ec3bada5.png)

![image](https://user-images.githubusercontent.com/45179589/155424572-01cbb9da-4ef2-4670-9a14-ea6e6dd4be23.png)

**Additional Info:**
I would recommend upgrading to v2.6.3 or newer (next incoming 2.6.4 release for example) for anyone encountering this issue.
