### ISSUE TITLE
Remove provisioning machine job will let Machine status be stuck in Provisioning

### ISSUE THREAD

**Issue by FrankYang0529** [rancher/rancher#36223]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.22.4+rke2r2
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Harvester

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**
If users or controllers remove a provisioning machine job before it is finished/failed, this will let Machine CR status be stuck in Provisioning.

**To Reproduce**
1. Create a cluster with 1 node.
2. Manual removing the provisioning machine job before it is finished.

**Result**
The status of the Machine is stuck in Provisioning.

**Expected Result**
The Job can't be deleted before it's finished or the controller detects the job is missing and create a new one.

**Screenshots**
The Machine is stuck in Provisioning.
![Screen Shot 2022-01-21 at 3 55 00 PM](https://user-images.githubusercontent.com/4927361/150488826-95411eff-93c4-4177-a0fa-c9821c8d0f66.png)

No running job.
![Screen Shot 2022-01-21 at 3 58 23 PM](https://user-images.githubusercontent.com/4927361/150488742-5c53a9fc-43b0-4713-b1e6-68f0be6242b3.png)

**Additional context**
https://github.com/harvester/harvester/issues/1823

```
fbcf08f8f69b:/var/lib/rancher # kubectl get machine -A -o yaml
apiVersion: v1
items:
- apiVersion: cluster.x-k8s.io/v1alpha4
  kind: Machine
  metadata:
    annotations:
      rke.cattle.io/join-url: https://192.168.0.51:9345
    creationTimestamp: "2022-01-21T07:35:21Z"
    finalizers:
    - machine.cluster.x-k8s.io
    generateName: rke2-in-sles-pool1-5ccc847cb9-
    generation: 2
    labels:
      cluster.x-k8s.io/cluster-name: rke2-in-sles
      cluster.x-k8s.io/control-plane: "true"
      cluster.x-k8s.io/deployment-name: rke2-in-sles-pool1
      machine-template-hash: "1777403765"
      rke.cattle.io/control-plane-role: "true"
      rke.cattle.io/etcd-role: "true"
      rke.cattle.io/init-node: "true"
      rke.cattle.io/machine-id: 75874c62f3c915c0785988ea69ac1c5be293b45c63ffff41189a37827682a28
      rke.cattle.io/worker-role: "true"
    name: rke2-in-sles-pool1-5ccc847cb9-gdwv6
    namespace: fleet-default
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1alpha4
      blockOwnerDeletion: true
      controller: true
      kind: MachineSet
      name: rke2-in-sles-pool1-5ccc847cb9
      uid: 85b08bbc-443d-4f9a-885a-448e5c5a3f22
    resourceVersion: "17497"
    uid: 13316946-4a38-4024-b276-1b979f78bec0
  spec:
    bootstrap:
      configRef:
        apiVersion: rke.cattle.io/v1
        kind: RKEBootstrap
        name: rke2-in-sles-bootstrap-template-fk577
        namespace: fleet-default
        uid: 340777d4-242b-499a-add8-b2748260f501
      dataSecretName: rke2-in-sles-bootstrap-template-fk577-machine-bootstrap
    clusterName: rke2-in-sles
    infrastructureRef:
      apiVersion: rke-machine.cattle.io/v1
      kind: HarvesterMachine
      name: rke2-in-sles-pool1-87d19696-cfw74
      namespace: fleet-default
      uid: bc56eb95-02f9-43a1-a289-4fac23577f06
  status:
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2022-01-21T07:35:23Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2022-01-21T07:35:21Z"
      status: "True"
      type: BootstrapReady
    - lastTransitionTime: "2022-01-21T07:35:23Z"
      message: creating server (HarvesterMachine) in infrastructure provider
      status: "False"
      type: InfrastructureReady
    - lastTransitionTime: "2022-01-21T07:35:21Z"
      reason: WaitingForNodeRef
      severity: Info
      status: "False"
      type: NodeHealthy
    - lastTransitionTime: "2022-01-21T07:35:23Z"
      message: creating server (HarvesterMachine) in infrastructure provider
      reason: Creating
      severity: Info
      status: Unknown
      type: Provisioned
    infrastructureReady: false
    lastUpdated: "2022-01-21T07:35:21Z"
    observedGeneration: 2
    phase: Provisioning
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by annablender** [comment]
Deleting the job manually is not a supported use case and there's no expectation that provisioning will recover from this. However, if something automatically removes the job before provisioning finishes, then it looks to be the same as  https://github.com/harvester/harvester/issues/1823 and we will investigate.
