### ISSUE TITLE
UI: when I add labels to host, focus is not set automatically to newly created field

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3623]
UI: 

 - when I add labels to host, focus is not set automatically to newly created field

![image](https://cloud.githubusercontent.com/assets/2150990/13073088/4f66c850-d49d-11e5-8101-8b00a39894de.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.0` Cattle: `v0.148.0` UI: `v0.90.0` |
|Access|`github` `admin`|
|Route|`null`|

**Comment by tfiduccia** [comment]
Version - master 3/20
Verified fixed
