### ISSUE TITLE
failed to download "https://charts.jetstack.io/charts/cert-manager-v1.5.3.tgz" at version "v1.5.3"

### ISSUE THREAD

**Issue by ahmedsza** [rancher/rancher#36240]
I am a rancher newbie. I am following https://rancher.com/docs/rancher/v2.5/en/quick-start-guide/deployment/microsoft-azure-qs/

and i get this

module.rancher_common.helm_release.cert_manager: Creating...
╷
│ Error: failed to download "https://charts.jetstack.io/charts/cert-manager-v1.5.3.tgz" at version "v1.5.3"
│
│   with module.rancher_common.helm_release.cert_manager,
│   on ..\rancher-common\helm.tf line 4, in resource "helm_release" "cert_manager":
│    4: resource "helm_release" "cert_manager" {
│

Is there a different version to be used

**Comment by apaniagua6** [comment]
I was able to fix it by running
`helm repo update`
