### ISSUE TITLE
UI - VMs:  "Edit container" text instead of edit VM

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3625]
UI - VMs:  "Edit container" text instead of edit VM:

![image](https://cloud.githubusercontent.com/assets/2150990/13074136/04489f5a-d4a3-11e5-8c02-a407f3142156.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.0` Cattle: `v0.148.0` UI: `v0.90.0` |
|Access|`github` `admin`|
|Route|`null`|

**Comment by vincent99** [comment]
It's the same form.  They're containers too.
