### ISSUE TITLE
Cannot create GKE cluster with small pod network

### ISSUE THREAD

**Issue by lucabarze-suse** [rancher/rancher#36254]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Both Docker and Helm installs are affected
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: not relevant
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? GKE

**User Information**
- What is the role of the user logged in? admin
   
**Describe the bug**
Wrong behaviour when creating a cluster with a small pod network.

**To Reproduce**
Create a GKE three nodes cluster using a /22 subnet for pods network.

**Result**
From Rancher interface we see the error:

> Googleapi: Error 400: Cluster CIDR range is greater than maximum (22 > 21)., badRequest

Instead if we use a /21 or bigger pod network we can create the cluster.

**Expected Result**
It is possible to create the same three nodes cluster (with a /22 pod network) from the GKE console.

It is possible to verify that a /22 pod network is supported on a three node GKE cluster from https://cloud.google.com/kubernetes-engine/docs/concepts/alias-ips#cluster_sizing_secondary_range_pods.

**Screenshots**
screenshot related to the creation of the cluster from Rancher UI
![screenshot_rancher](https://user-images.githubusercontent.com/95303943/150954223-b330228f-df64-45cf-965e-f5558c0e1e14.png)

screenshot related to the creation of the cluster from GKE UI
![screenshot_gke](https://user-images.githubusercontent.com/95303943/150954351-fc90e07f-eca7-4aab-84d6-a86a928baf11.png)

screenshot showing the error in the Rancher UI
![screenshot_error](https://user-images.githubusercontent.com/95303943/150954534-ac44d20f-fa1b-4c54-beea-82203b1f89a0.png)

**Comment by stuartblackburn** [comment]
Did anyone ever find a resolution for this? I'm hitting the same issue.

**Comment by donjmilligan** [comment]
Not sure if this info helps, but Terraform is also directly limiting me from creating a node cluster using a > /21 subnet for pods network.
