### ISSUE TITLE
Rancher Container is crashing with Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)

### ISSUE THREAD

**Issue by PlayMTL** [rancher/rancher#36260]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart on RKE1 Cluster (1.21.8) with 3 Replicas
- Proxy/Cert Details: Using Proxy / SelfSigned-Certs

**Information about the Cluster**
- Kubernetes version: 1.21.8
- Cluster Type (Local/Downstream): Local (RKE Cluster)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin (& Cluster Owner)
   
**Describe the bug**

Rancher Container is randomly crashing with: `Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)`

**To Reproduce**
 

What we have done:
1. Upgrade the RKE Cluster to 1.21.8 (for Rancher)
2. Upgrade Rancher from v2.5.11 to v2.6.3 via HELM
3. Upgrade the Windows Downstream RKE Cluster to k8s 1.21.8
4. Edit "Monitoring v1 Settings" on Windows Downstream-Cluster (not tested on Linux Clusters so far)
5. Rancher crashes, the Health-Checks restart the Container, after a random time the container crashes again with the same error.
6. To resolve this issue (Rancher Container Crashes), we had to delete the Windows Cluster out of Rancher (in the short periode of time, where the containers didn't crash after fresh restart)

**Result**

Logs from the Rancher Container:

`
E0125 14:07:50.366108 36 runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
goroutine 2803 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3cde400, 0x4bd6170)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:48 +0x86
panic(0x3cde400, 0x4bd6170)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/controllers/managementuserlegacy/alert/deployer.(*AlertService).Upgrade(0xc002d1cf00, 0xc01470eb40, 0x27, 0x8, 0xc00f520bc8, 0x0, 0x0)
/go/src/github.com/rancher/rancher/pkg/controllers/managementuserlegacy/alert/deployer/upgradeimpl.go:152 +0x48f
github.com/rancher/rancher/pkg/controllers/managementuserlegacy/systemimage.(*Syncer).Sync(0xc016a9ce00, 0xc00b33bb90, 0x10)
/go/src/github.com/rancher/rancher/pkg/controllers/managementuserlegacy/systemimage/systemimage.go:74 +0x302
github.com/rancher/rancher/pkg/controllers/managementuserlegacy/systemimage.(*Syncer).SyncCatalog(0xc016a9ce00, 0xc002c2fa50, 0xe, 0xc002d28c78, 0x10, 0x7f7e01dc8878, 0x10, 0xc00b33bb90)
/go/src/github.com/rancher/rancher/pkg/controllers/managementuserlegacy/systemimage/systemimage.go:43 +0xa8
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*catalogController).AddHandler.func1(0xc002c2fa50, 0xe, 0x4450080, 0xc002d28c78, 0xc00b5fab58, 0x3, 0x3, 0x0)
/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_catalog_controller.go:155 +0x67
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc002c2fa50, 0xe, 0x4c89048, 0xc002d28c78, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211201154850-abe17976423e/controller/generic_controller.go:62 +0x224
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0110e9aa0, 0xc002c2fa50, 0xe, 0x4c89048, 0xc002d28c78, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc003a5de40, 0xc002c2fa50, 0xe, 0x4c89048, 0xc002d28c78, 0x48b601, 0x0)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc003c382c0, 0xc002c2fa50, 0xe, 0xc00ddb6748, 0xc00000fac0)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:215 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc003c382c0, 0x3aa2560, 0xc00b33baf0, 0x0, 0x0)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:197 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc003c382c0, 0x203003)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:174 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:163
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00ddb53c0)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00ddb53c0, 0x4c60ca0, 0xc00dda1f80, 0x3045494344346201, 0xc0008be420)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00ddb53c0, 0x3b9aca00, 0x0, 0x1, 0xc0008be420)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00ddb53c0, 0x3b9aca00, 0xc0008be420)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:134 +0x33b
panic: assignment to entry in nil map [recovered]
panic: assignment to entry in nil map
goroutine 2803 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:55 +0x109
panic(0x3cde400, 0x4bd6170)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/rancher/pkg/controllers/managementuserlegacy/alert/deployer.(*AlertService).Upgrade(0xc002d1cf00, 0xc01470eb40, 0x27, 0x8, 0xc00f520bc8, 0x0, 0x0)
/go/src/github.com/rancher/rancher/pkg/controllers/managementuserlegacy/alert/deployer/upgradeimpl.go:152 +0x48f
github.com/rancher/rancher/pkg/controllers/managementuserlegacy/systemimage.(*Syncer).Sync(0xc016a9ce00, 0xc00b33bb90, 0x10)
/go/src/github.com/rancher/rancher/pkg/controllers/managementuserlegacy/systemimage/systemimage.go:74 +0x302
github.com/rancher/rancher/pkg/controllers/managementuserlegacy/systemimage.(*Syncer).SyncCatalog(0xc016a9ce00, 0xc002c2fa50, 0xe, 0xc002d28c78, 0x10, 0x7f7e01dc8878, 0x10, 0xc00b33bb90)
/go/src/github.com/rancher/rancher/pkg/controllers/managementuserlegacy/systemimage/systemimage.go:43 +0xa8
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*catalogController).AddHandler.func1(0xc002c2fa50, 0xe, 0x4450080, 0xc002d28c78, 0xc00b5fab58, 0x3, 0x3, 0x0)
/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_catalog_controller.go:155 +0x67
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc002c2fa50, 0xe, 0x4c89048, 0xc002d28c78, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/github.com/rancher/norman@v0.0.0-20211201154850-abe17976423e/controller/generic_controller.go:62 +0x224
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0110e9aa0, 0xc002c2fa50, 0xe, 0x4c89048, 0xc002d28c78, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc003a5de40, 0xc002c2fa50, 0xe, 0x4c89048, 0xc002d28c78, 0x48b601, 0x0)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc003c382c0, 0xc002c2fa50, 0xe, 0xc00ddb6748, 0xc00000fac0)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:215 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc003c382c0, 0x3aa2560, 0xc00b33baf0, 0x0, 0x0)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:197 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc003c382c0, 0x203003)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:174 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:163
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00ddb53c0)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00ddb53c0, 0x4c60ca0, 0xc00dda1f80, 0x3045494344346201, 0xc0008be420)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00ddb53c0, 0x3b9aca00, 0x0, 0x1, 0xc0008be420)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00ddb53c0, 0x3b9aca00, 0xc0008be420)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20211217013041-3c6118a30611/pkg/controller/controller.go:134 +0x33b
`

**Expected Result**

- Rancher should not crash after i edit the Cluster Monitoring V1 on a Windows Cluster.

**Screenshots**

**Additional context**

**Comment by PlayMTL** [comment]
I'm still interested in the issue

**Comment by rosskirkpat** [comment]
@PlayMTL Thank you for filing this issue. I have placed it in our triage list for the next sprint.

**Comment by rosskirkpat** [comment]
@PlayMTL The panic has been fixed with https://github.com/rancher/rancher/pull/37532/commits/1c159311f9c2cbf8b28d7961b4b3c899c6c97951. This should be available once Rancher v2.6.5 is released
