### ISSUE TITLE
upgrade job is not deploying when upgrading k8s for an imported rke2 cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36268]
**Rancher Server Setup**
- Rancher version: v2.6.3-patch1-rc2
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1  v1.20.6
- Proxy/Cert Details: valid letsencrypt cert

**Information about the Cluster**
- Kubernetes version: v1.20.6
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): imported rke2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): cluster owner

   
**Describe the bug**

imported rke2 cluster on v1.20.6+rke2r1 is not upgrading after using the UI to upgrade to the latest patch of 1.20 (1.20.14+rke2r1). Upon further investigation, the upgrade job/SUC is never deployed to the cluster

**To Reproduce**
 
* deploy rancher v2.5.8-patch1
* import an rke2 cluster on v1.20.6+rke2r1
  * verify that the imported cluster is working normally 
* upgrade rancher to v2.6.3-patch1-rc2
  * verify that the cluster is still working as expected after the upgrade
* upgrade the imported cluster to 1.20.14+rke2r1

**Result**
* imported rke2 cluster on v1.20.6+rke2r1 is not upgrading after using the UI to upgrade to the latest patch of 1.20 (1.20.14+rke2r1). Upon further investigation, the upgrade job/SUC is never deployed to the cluster
* the UI reports the cluster in an upgrading `Cluster is being upgraded` state, but after an hour no job is ever deployed

**Expected Result**

* also tested this with the same setup, but upgrading to 2.6.3 instead of 2.6.3-patch1, and the **upgrade of k8s was successful**

**Comment by ronhorton** [comment]
**To Reproduce**
1. Import an rke2 cluster in 2.6.3 k8s version `1.20.14`
2. `helm upgrade rancher rancher-latest/rancher --version 2.6.3 --namespace cattle-system --set hostname=HOSTNAME --set rancherImageTag=v2.6.3-patch1-rc2`
3. Upgrade k8s version of imported cluster to `v1.21.8+rke2r2`

**Result**
No nodes are upgraded; cluster shows 'upgrading' in Rancher UI

**Expected Result**
All nodes upgrade; cluster returns to `available`
**Screenshots**
![ronron](https://user-images.githubusercontent.com/89212856/151083314-b23bf5f9-c80a-4259-8818-5ba3a1458941.jpg)

**Comment by thedadams** [comment]
After some investigation and some help from @jakefhyde, it looks like we need these two changes in `v2.6.3-patch1` for this to work properly:
- https://github.com/rancher/rancher/commit/9850347a058e149e6ccc9cf1731462a11cebfbc3
- https://github.com/rancher/rancher/commit/0e1fc7df00e805ca21f502f9969f609395890366

**Comment by slickwarren** [comment]
@thedadams did some more testing, and it turns out this issue is specific to the `*-rc` tag. With no diff from `2.6.3-patch1` and `2.6.3-patch1-rc2`, the same setup was able to upgrade the imported cluster.
