### ISSUE TITLE
Ensure Istio works when there are Windows nodes in RKE2-provisioned cluster

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#36266]
As per RKE2 <-> RKE1 provisioning parity requirements, we need to ensure Istio is not affected if there are Windows nodes present in RKE2-provisioned cluster. Note that there are no expectations of Istio actually working against Windows nodes, we just need to ensure a presence of Windows nodes doesn't result in failures.

**Comment by deniseschannon** [comment]
Need to add

Tolerations - to support RKE1 windows clusters
Node Selectors - to support RKE2 windows clusters

for the components to be scheduled only on the linux nodes

see: https://github.com/rancher/rancher/issues/36403

**Comment by luthermonson** [comment]
This issue is going to be superceded by a previous dashboard issue which captures everything and has all PRs linked up. You can see context https://github.com/rancher/dashboard/issues/5137#issuecomment-1062323770

**Comment by PennyScissors** [comment]
Closing this since the Zube bot mistakenly re-opened.
