### ISSUE TITLE
v2.6.4 Support Matrix checks - Validate installing Rancher, Downstream clusters listed in the support matrix 2.6.4

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36277]
On latest 2.6-head or latest 2.6.4 -rc
---
### Deploy Rancher on these(Hosted clusters) clusters (Using HA jenkins)
- Deploy a downstream cluster with the following cluster types (Can be downstream node driver RKE1 cluster with default k8s version)
- Run v3_need cluster on the downstream cluster

Local Cluster Type | Cluster k8s version | Downstream cluster Type | Downstream cluster version | Status
-- | -- | -- | --| --
AKS | v1.21.9 | RKE1 | v1.23.4 | **Passed**
GKE | v1.21.6-gke.1503 | RKE1 | v1.23.4 | **Passed**
EKS | v1.18.20-eks-bb024d | RKE1 | v1.23.4 | **Passed**

---
Start date - Post Bug complete date - 03/04/2022
Due by - 03/11/2022

**Comment by izaac** [comment]
Rancher version: `v2.6.4-rc8`

Updated issue description with current versions used as of 3/11/2022

**Comment by izaac** [comment]
Results:

Local Cluster Type | Cluster k8s version | Downstream cluster Type | Downstream cluster version | Status
-- | -- | -- | --| --
AKS | v1.21.9 | RKE1 | v1.23.4 | **Passed**
GKE | v1.21.6-gke.1503 | RKE1 | v1.23.4 | **Passed**
EKS | v1.18.20-eks-bb024d | RKE1 | v1.23.4 | **Passed**

**Comment by izaac** [comment]
Local Cluster Type | Cluster k8s version | Downstream cluster Type | Downstream cluster version | Status
-- | -- | -- | --| --
EKS | v1.21.5-eks-bc4871b | RKE1 | v1.23.4 | **Passed**

**Comment by anupama2501** [comment]
Results:

Local Cluster Type | Cluster k8s version | Downstream cluster Type | Downstream cluster version | Status
-- | -- | -- | --| --
AKS | v1.22.6 | RKE1 | v1.22.7 | **Passed**

**Comment by slickwarren** [comment]
| Local Cluster Type | Cluster K8S Version | Downstream Cluster Type | Downstream K8S Version | Status |
| --- | --- | --- | --- | --- |
| GKE | 1.22.6-gke.300 | RKE1 | 1.22.7 | PASS |
