### ISSUE TITLE
v2.6.4- Release testing - Run Automation suite against 2.6.4-rc

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36275]
Run Automation suite against 2.6.4-rc (3 weeks before release)

Jenkins | Assignee | Status
-- | -- | --
rancher-v3_additional_tests | Izaac | 
rancher-v3_additional_tests_cli | Izaac |
rancher-v3_additional_tests_long | Caleb |
rancher-v3_auth_enabled_rancher | Anupama |
rancher-v3_cluster_auth_grb_istio_monitoring | Anupama |

---
Start date - Post Bug complete date - 03/04/2022
Due by - 03/11/2022

**Comment by MKlimuszka** [comment]
@sowmyav27 , how do you want me to make sure this gets done in time? I'm not sure who the assignee should be on this ticket. Since it's automation, is it just Brandon?

**Comment by izaac** [comment]
| Jenkins | Assignee | Status |
| --- | --- | --- |
| rancher-v3_additional_tests | Izaac | Passed |
| rancher-v3_additional_tests_cli | Izaac | In Progress |

**Comment by slickwarren** [comment]
rancher-v3_additional_tests_long -- automation has failed, but manually checking these tasks is passing using v2.6.4-rc8. Filed this issue to track updates to automation https://github.com/rancher/qa-tasks/issues/269

**Comment by anupama2501** [comment]
Jenkins | Assignee | Status
-- | -- | -- |
rancher-v3_auth_enabled_rancher | Anupama | Pass
rancher-v3_cluster_auth_grb_istio_monitoring | Anupama | Pass
