### ISSUE TITLE
feature request: ability to configure service& standalone containers from command line docker options via the UI

### ISSUE THREAD

**Issue by rvion** [rancher/rancher#3628]
Let's say I want to start such a container from rancher UI like `docker run -v /var/run:/var/run -p 8080:80 -v /var/lib/rancher/vm:/vm rancher/ranchervm`.

For now, I need to switch from tabs to tabs in the UI to set options one after the others.

it would be cool if I could just paste the line in a `raw docker options` fields, press a `configure` button, and see all fields being set automatically in the UI.

That would be a great time saving feature

**Comment by deniseschannon** [comment]
Dupicate of https://github.com/rancher/rancher/issues/417
