### ISSUE TITLE
Creating RKE2 cluster on Harvester doesn't successfully deploy harvester-csi-driver

### ISSUE THREAD

**Issue by egrist** [rancher/rancher#36309]
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart rancher/stable:v2.6.3
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 v1.21.8+rke2r2
- Proxy/Cert Details: No proxy/Certificates from files

**Information about the Cluster**
- Kubernetes version: v1.21.8+rke2r2 
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Harvester v1.0.0

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:

   
**Describe the bug**
Deploy new cluster using the imported Harvester with Kubernetes Version v1.21.8+rke2r2 renders FailedMount Events in the Cluster Dashboard for harvester-csi-driver

**To Reproduce**
Deploy new cluster -> RKE2 -> Harvester with Kubernetes Version v1.21.8+rke2r2 selected
 

**Result**
DaemonSet harvester-csi-driver is stuck In Progress, Available: 0/3, pods in state: Containercreating

**Expected Result**
Successfully deployed RKE2 cluster with harvester-csi-driver working.

**Screenshots**
![image](https://user-images.githubusercontent.com/19166870/151514558-e0060c2d-aa7e-49b8-b394-fa4de165853a.png)

**Additional context**

**Comment by belgaied2** [comment]
@egrist Having the same issue, just be aware that going on a `control plane` node and manually editing the DaemonSet configuration to change the VolumePath from `/etc/kubernetes/cloud-config` to `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config` solves the issue.

**Comment by egrist** [comment]
This is working now, I didn't take note from which version but the fix posted: [Working fix](https://github.com/rancher/rancher/issues/36309#issuecomment-1063393884)

Closing issue.
