### ISSUE TITLE
KDM improvements

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#36304]
- [ ]  Create process for branching and rebasing for emergency releases or frequent patch releases 
- [ ]  Automate process if possible to rebase dev branches automatically after release from special dev branches 
- [ ]  Automate process to avoid updating codegen KDM branch in RKE for each release 
- [ ]  Create test checklist for validating changes
- [ ]  Create process template for updates going out with each release (Easy access to list of issues getting fixed as part of release) 
- [ ]  Create release note template for each KDM release, with a proper naming convention (KDM release tags for each release on GH) 
- [x]  Update README.md / docs
- [x]  Refactor code into more folders for readability 
- [ ]  Look into performance issues if any around releasing templates out of band vs bundled with RKE
- [ ]  Helm templates vs improving templates scope for faster updates

**Comment by snasovich** [comment]
Closing as stale
