### ISSUE TITLE
helm v3/v2 apps from system charts should not be deployable on rancher patch version when the rancher max version exceeds

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36301]
**Rancher Server Setup**
- Rancher version: `v2.6.3-patch1-rc3`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.21.7+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.21.8`
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 1 worker, 1 etcd + cp`
`RKE1`

**Describe the bug**
Currently we are able to deploy helm v3/v2 apps on rancher 263 patch1-rc3 version from system charts catalogs. The apps have rancher max version set as 2.6.3 which should not allow apps to be deployable. 

**To Reproduce**
Install rancher v2.6.3patch-rc version
Create a downstream cluster with 1 worker, 1 etcd +cp nodes 
Enable legacy flag --> downstream clusters --> legacy --> project --> select default namespace 

**Result**
we can launch the apps from the helm v3/v2 catalogs and upgrade

**Expected Result**
Expected not to be able to launch the apps as the helm max version is set to 2.6.3 for the apps.

**Screenshots**

v2.6.3-patch1-rc3
<img width="500" alt="2022-01-27_09-27-35" src="https://user-images.githubusercontent.com/38144301/151411654-086cd1c0-aafe-4397-9d1c-09b3e4d81ffb.png">

v2.6.3:
<img width="500" alt="Screen Shot 2022-01-27 at 9 29 22 AM" src="https://user-images.githubusercontent.com/38144301/151411888-cd7e400c-8bcc-4f88-b599-4fb661800327.png">

**Comment by thedadams** [comment]
This issue will be fixed once the Rancher version is `v2.6.3-patch1`. Similar to this issue: https://github.com/rancher/rancher/issues/36268

**Comment by anupama2501** [comment]
Closing this issue as mentioned by @thedadams the issue is specific to the rc tag and will not be impacted in v2.6.3-patch1 version.

**Comment by anupama2501** [comment]
Re-opening the issue as we need to push the changes in the PR to the patch version:

**Comment by anupama2501** [comment]
closing this issue as its working as expected and will log a new ticket for the above linked issue.
