### ISSUE TITLE
Well Known Open ID Configuration

### ISSUE THREAD

**Issue by davinder2385** [rancher/rancher#36318]
Hi,

We are trying to access the /.well-known/openid-configuration on rancher but unable to do so.

The url we are trying to access is this:
https://kubernetes.default.svc/.well-known/openid-configuration

The equivalent curl command:

curl --cacert ca.crt -H "Authorization:</var/run/secrets/kubernetes.io/serviceaccount/token>" https://kubernetes.default.svc/.well-known/openid-configuration
Do we have to start rancher with some configuration to enable default OIDC provided with Kubernetes?

Rancher installation details is below:

{
  "major": "1",
  "minor": "21",
  "gitVersion": "v1.21.7",
  "gitCommit": "1f86634ff08f37e54e8bfcd86bc90b61c98f84d4",
  "gitTreeState": "clean",
  "buildDate": "2021-11-17T14:35:38Z",
  "goVersion": "go1.16.10",
  "compiler": "gc",
  "platform": "linux/amd64"
}

Appreciate your help.

**Comment by domruf** [comment]
This is still relevant for us.
