### ISSUE TITLE
Validate cluster provisioning use cases using Terraform

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36327]
Validate cluster provisioning usecases using Terraform

### node driver provisioning 

**RKE1** 

- [ ] Cluster provisioning
- [ ] Adding node pools
- [ ] Deleting node pools
- [ ] deleting the cluster

**RKE2** --> WIP so _cannot_ be tested now 

- [ ] Cluster provisioning
- [ ] Adding node pools
- [ ] Deleting node pools

### Other usecases
- [ ] Delete RKE1 and RKE2 cluster
- [ ] Deploy a hosted cluster - AKS (since this is the newest)

---
### Note:
- To be validated - 3 weeks before release - 03/02/2022
- Due by - 03/04/2022

**Comment by MKlimuszka** [comment]
Is there documentation anywhere that goes into more details on how these are tested? I think I understand the scope of this ticket, but I bet there's more info in confluence that would be useful to link here.

**Comment by sgapanovich** [comment]
@MKlimuszka https://confluence.suse.com/display/RANQA/Terraform+cluster+provisioning
