### ISSUE TITLE
incorrect monitoring data

### ISSUE THREAD

**Issue by wormen** [rancher/rancher#36323]
why the data may be incorrect, and how can this be corrected?
the cluster installation was new

**Rancher Server Setup**
- Rancher version: v2.6.3-patch1
- Оnly service pods installed 

**Information in UI rancher**

![image](https://user-images.githubusercontent.com/8462339/151663864-520c9540-fffd-4f6e-b644-909e2221825f.png)
![image](https://user-images.githubusercontent.com/8462339/151663831-3ed516d7-ca44-4603-a8b9-7fc724756dde.png)
![image](https://user-images.githubusercontent.com/8462339/151664032-308a9954-7a38-4948-89ea-8fa4a825ba43.png)

**Actually on the server**

![image](https://user-images.githubusercontent.com/8462339/151663895-29fa9501-2ddb-4c3b-bb6e-8abbcf58654e.png)

kubectl describe node <>
![image](https://user-images.githubusercontent.com/8462339/151663918-41771bcd-f922-4334-b713-8de1391ddcc1.png)

it turns out, no matter what the load in the cluster is, it definitely cannot even reach 8GB, not to mention large amounts of RAM

**Comment by wormen** [comment]
added monitoring, now the picture is like this

![image](https://user-images.githubusercontent.com/8462339/151686056-9e5b800f-5b68-40e6-8ea6-9af0cac8dedb.png)
![image](https://user-images.githubusercontent.com/8462339/151686067-d54d563f-57f3-40f5-9eca-998bfa2f61bc.png)
![image](https://user-images.githubusercontent.com/8462339/151686074-e79c9417-6fcb-4f76-966c-25cc119f07ec.png)

**Comment by WolfspiritM** [comment]
I think this is a duplicate of https://github.com/rancher/rancher/issues/35986

**Comment by wormen** [comment]
@WolfspiritM 
no, it's a different situation.
