### ISSUE TITLE
show Author, creation date, last modified directy in UI and quicker access to audit logs

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#3632]
initial motivation can be found in the forums [post 1](https://forums.rancher.com/t/how-can-i-see-which-user-has-created-a-stack-service-container/1177) and [post 2](https://forums.rancher.com/t/how-can-i-see-the-owner-of-a-container/1612)

**The need**
In our situation, an entire large team share the same environment (or set of environments) and therefore each member is equally able to add hosts and deploy new stacks. At any moment of the day we want to quickly see who created/modified a Stack, Host or container. The audit log is nice feature... but too complicated for the daily use case.

I would like to see at least the first Author, Creation date, Last Modified, and last modified by directly on the UI of each Stacks/Service/Containers/Hosts. Maybe also a shortcut from the Stack/Service/Container menu called "Audit log"  to be directed to a predefined filtered search on the audit logs would help keep control over a rancher environment used by many.

**Comment by chris-redekop** [comment]
:+1:

**Comment by fedya** [comment]
+1

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
