### ISSUE TITLE
v2.6 KDM - Tracking issue for RKE2 k8s February Patches

### ISSUE THREAD

**Issue by katran001** [rancher/rancher#36337]
This is the tracking issue for the RKE2 February k8s Patches. We should be checking/validating the following versions:

v1.23.4
v1.22.7
v1.21.10

**Comment by snasovich** [comment]
This also included 1.23.4, so adding it to the description.

**Comment by rancher-max** [comment]
### Validated using rancher v2.6.3 and rancher v2.6.4-rc11 pointing to dev-v2.6 KDM

**Rancher 2.6.3**
- Provisioning shows the expected versions, and using those both correctly provision the cluster.
<img width="944" alt="image" src="https://user-images.githubusercontent.com/55997940/160007623-ebc71100-da70-4aec-aae1-3e2b9c67d700.png">
- Upgrade imported cluster shows the correct versions and upgrades are successful. Note that there was a UI bug causing 1.21.10 to show below the other versions. This is resolved in 2.6.4
<img width="967" alt="image" src="https://user-images.githubusercontent.com/55997940/160012311-4aa29d0b-131a-4911-8892-f742fec336c7.png">
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/55997940/160012349-49e1270f-7f74-43e7-b6e6-db695b020a87.png">


**Rancher 2.6.4-rc11**
- Provisioning shows the expected versions, and using those both correctly provision the cluster. Note that both 1.21.10+rke2r2 and 1.23.x (both k3s and rke2) have minVersion set to rancher 2.6.4 so they are not expected to show up in rancher 2.6.3.
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/55997940/160008320-4b1ef33c-c570-42f0-b2d1-4a65ad69594c.png">
- Upgrade imported cluster shows the correct versions and upgrades are successful
<img width="980" alt="image" src="https://user-images.githubusercontent.com/55997940/160012532-c7c2851e-8cc0-4f0d-8608-8a4ee8da4e34.png">
