### ISSUE TITLE
v2.6 KDM - Tracking issue for K3s k8s February Patches

### ISSUE THREAD

**Issue by katran001** [rancher/rancher#36336]
This is the tracking issue for the K3s February k8s Patches. We should be checking/validating the following versions:

v1.22.7
v1.21.10

**Comment by snasovich** [comment]
Doesn't look like k3s 1.23.4 was added yet; however it was added for RKE2 as part of https://github.com/rancher/kontainer-driver-metadata/pull/853.
Any reason we shouldn't introduce 1.23.4 for k3s to KDM?

**Comment by rancher-max** [comment]
#### Validated using rancher v2.6.3 and rancher v2.6.4-rc11 pointing to dev-v2.6 KDM

**Rancher 2.6.3**
- Provisioning shows the expected versions, and using those both correctly provision the cluster.
(see screenshots from https://github.com/rancher/rancher/issues/36337#issuecomment-1078373505)
- Upgrade imported cluster shows the correct versions and upgrades are successful. Note that there was a UI bug causing 1.21.10 to show below the other versions. This is resolved in 2.6.4
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/55997940/160011946-20989973-15d2-4616-81c1-7cd2fbde39d0.png">
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/55997940/160012206-67f89303-9249-4e89-a257-c9942b4142e2.png">


**Rancher 2.6.4-rc11**
- Provisioning shows the expected versions, and using those both correctly provision the cluster. Note that both 1.21.10+rke2r2 and 1.23.x (both k3s and rke2) have minVersion set to rancher 2.6.4 so they are not expected to show up in rancher 2.6.3.
(see screenshot from https://github.com/rancher/rancher/issues/36337#issuecomment-1078373505)
- Upgrade imported cluster shows the correct versions and upgrades are successful
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/55997940/160012472-310b3304-e2c8-4a23-9b77-deb115246eeb.png">
