### ISSUE TITLE
Add Docker 20.10.12

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#36330]
https://github.com/moby/moby/releases/tag/v20.10.12

**Comment by rayandas** [comment]
Validation steps:

Create AWS infrastructure provider with 3 nodes, 1 role each.

- Change Docker Install URL to https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.12.sh in node template (as current changes are not synced yet with CDN release.rancher.com).
- Launch cluster and wait for cluster to become available.

Create DO infrastructure provider with 3 nodes, 1 role each.

- Change Docker Install URL to https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.12.sh in node template.
- Launch cluster and wait for cluster to become available.

Create a custom cluster, 1 node all roles.

- Install Docker using https://raw.githubusercontent.com/rancher/install-docker/master/dist/20.10.12.sh
- Launch cluster and wait for cluster to become available.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6-head(bab14a3)

Node driver clusters :
- Ubuntu : cluster provisioned successfully.
- Rocky : cluster provisioned successfully.

Custom cluster :
- Ubuntu : cluster provisioned successfully.
- Rocky : cluster provisioned successfully.
- CentOS : cluster provisioned successfully.

**Comment by rishabhmsra** [comment]
Since the CentOS issue is occurring because of the repository change as mentioned [here](https://github.com/rancher/rancher/issues/36820#issuecomment-1062969377), and we are tracking it in a separate issue, hence closing this one as the docker install script is working as expected.
