### ISSUE TITLE
Unable to provision 1.22/1.21 RKE2 AWS Cluster

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#36349]
**Setup**
- Rancher version: v2.6-head da382a8
- Browser type & version: Chrome Version 97.0.4692.99

**Description**

User is unable to provision 1.22/1.21 RKE2 AWS Cluster

**To Reproduce**

1. Provision RKE2 cluster with 1.22/1.21

**Result**
Cluster provision fails and seems to be stuck on `Waitingfornoderef`
- Only message in the provisioning log is:
  - [INFO ] provisioning bootstrap node(s) sowmya121-pool1-58fdfbc5f9-k45bf: waiting for agent to check in and apply initial plan

**Expected Result**

Cluster provisioning is successful

**Screenshots**

<img width="1462" alt="Screen Shot 2022-02-01 at 6 04 04 PM" src="https://user-images.githubusercontent.com/97477402/152066236-71b00675-0e69-4292-aa57-57ab229a56ab.png">

**Comment by sowmyav27** [comment]
Not an issue. Was not working originally with some known issue in QA Env. But is currently working. 
1 etcd/1cp/1worker node.
