### ISSUE TITLE
Custom registry authentication: "no basic auth credentials" 

### ISSUE THREAD

**Issue by mtrofimm** [rancher/rancher#3634]
I setup private registry with cert signed by my private ca. The ca.crt is added to docker daemon. Docker login works fine.

When I try to start service (using the rancher web ui)  which uses an image from this repo I get an error in agent:

APIError: 500 Server Error: Internal Server Error ("Get https://docker-registry.my.domain.com/v2/app1/web/manifests/latest: no basic auth credentials")

Server version: v0.56.1

**Comment by mtrofimm** [comment]
I also checked that docker run on node works OK:
$ docker run docker-registry.my.domain.com/app1/web:latest

**Comment by mtrofimm** [comment]
probable duplicate of: #3008

**Comment by mtrofimm** [comment]
Hi, any ETA on this?

**Comment by deniseschannon** [comment]
We are busy working on the last major features for GA, which is aimed for end of March. After the major features are complete, we will start addressing bugs and attempt to address as many as possible before GA.

**Comment by will-chan** [comment]
I believe this is working in 1.0.1.

**Comment by sangeethah** [comment]
With rancher server version - v1.0.0 , able to start containers using images from custom registry with self-signed cert http://docs.rancher.com/rancher/configuration/registries/ which require authentication. Steps required for getting this set up is documented in http://docs.rancher.com/rancher/configuration/registries/
