### ISSUE TITLE
No entries found in provisioning log during RKE2 provisioning

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#36351]
**Setup**
- Rancher version: v2.6-head da382a8
- Browser type & version: Chrome Version 97.0.4692.99

**Description**

No entries are found in the provisioning log during RKE2 provisioning

**To Reproduce**

1. Provision RKE2 cluster with 1.22/1.21

**Result**
Cluster provisioning is successful but there seems to be zero entries in the provisioning log.

**Expected Result**

Cluster provisioning is successful and entries are logged in the provisioning log.

**Screenshots**

Provisioned cluster
<img width="1464" alt="Screen Shot 2022-02-01 at 7 29 50 PM" src="https://user-images.githubusercontent.com/97477402/152073990-f13a1cf2-fde3-4fc8-8bc3-7c3af60c6fb8.png">

Provisioning log
<img width="1482" alt="Screen Shot 2022-02-01 at 7 29 26 PM" src="https://user-images.githubusercontent.com/97477402/152073941-f8c33e56-85c2-4f79-9322-085bb93df623.png">

No errors seen in console/Network tab.

**Comment by jiaqiluo** [comment]
The bug cannot be reproduced in rancher v2.6-head 19f459a

The content of the provisioning log comes from a configMap named provisioning-log in the cluster's namespace in the local cluster. 


Send the issue back to QA for reproducing/testing.  


![screencapture-rainbow-cp-dev-rancher-space-dashboard-c-c-m-dlhrmpww-manager-provisioning-cattle-io-cluster-fleet-default-jiaqi-rke2-test-2022-02-09-17_04_33](https://user-images.githubusercontent.com/6218999/153312406-304c2d02-ce8a-4df6-af5f-1401f24e1206.png)
![screencapture-rainbow-cp-dev-rancher-space-dashboard-c-manager-provisioning-cattle-io-cluster-fleet-default-jiaqi-rke2-2-2022-02-09-17_10_53](https://user-images.githubusercontent.com/6218999/153312412-70b2b2a1-1544-4673-9589-4b9cbcad9a76.png)
