### ISSUE TITLE
unable to create rke2 cluster with linode error from node: `connection reset by peer`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36360]
**Rancher Server Setup**
- Rancher version:v2.6.4-alpha3
- Installation option (Docker install/Helm Chart):helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):rke1, v1.3.6
- Proxy/Cert Details:valid signed certs

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): linode node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): standard user

   
**Describe the bug**

when creating a linode rke2 cluster, the node gets the following error, and the node never gets to an active state:
```
Waiting for Machine Running... Error creating machine: Error in driver during machine creation: wait for machine running failed: [002] Get https://api.linode.com/v4/linode/instances/34440158: read tcp <IP>:49402-><IP>:443: read: connection reset by peer The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
```
this is the last line of the error.

**To Reproduce**
 
* provision a linode rke2 single node cluster (v1.21.9+rke2r1)

**Result**
the node gets the following error, and the node never gets to an active state:
```
Waiting for Machine Running... Error creating machine: Error in driver during machine creation: wait for machine running failed: [002] Get https://api.linode.com/v4/linode/instances/34440158: read tcp <IP>:49402-><IP>:443: read: connection reset by peer The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
```

**Expected Result**
linode should be able to create clusters

**Additional context**
* able to provision with other node drivers, i.e. aws, digital ocean for rke1 and rke2
* also able to use rke1 to provision with linode, but not rke2

**Comment by timhaneunsoo** [comment]
**Additional Information**
Creating RKE2 Linode Cluster results in the following error. The issue seems to be consistent and seems to be an issue with the driver.
![image](https://user-images.githubusercontent.com/97477402/152395973-bc0829e0-080c-41c1-97d2-12d28783e645.png)

The nodes are successfully created and are displayed in Linode as Running but Rancher seems to be not be getting that information and still shows as "Creating"
![image](https://user-images.githubusercontent.com/97477402/152398614-2f754ac4-cbb6-40ee-8c0e-03d9fbde1dc2.png)

@slickwarren @thedadams

**Comment by slickwarren** [comment]
I am now able to provision rke2 clusters using linode node driver on 2.6-head (19f459a):
* single node cluster -- pass
* 1 role per node cluster -- pass

**Comment by anupama2501** [comment]
Re-opening for this use case on 2.6-head e93a53c

- Created one more multi node with 1 etcd, 2 cp, 3 worker node - One of the worker nodes is stuck in Createerror state.
- The other 2 worker nodes in the same pool came up active.

Following is the error displayed:
```
Failed creating server (LinodeMachine) in infrastructure provider: CreateError: Downloading driver from https://<redacted>/assets/docker-machine-driver-linode Doing /etc/rancher/ssl docker-machine-driver-linode docker-machine-driver-linode: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped Running pre-create checks... (multi-w-4bf259bc-76f2g) Generating a secure disposable linode-root-pass... Creating machine... (multi-w-4bf259bc-76f2g) Creating Linode machine instance... Error creating machine: Error in driver during machine creation: [408] Please try again The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
This does not happen always. Happened for 1 out of 3 nodes in 1 out of 3 clusters.
```

**Comment by snasovich** [comment]
This sounds to me like an intermittent issue with Linode provider. Given where we're with 2.6.4, pushing it out to 2.6.5.

**Comment by slickwarren** [comment]
tested on v2.6-head (851ff2f) we are no longer seeing this issue with rke2 node driver for linode however there are separate issues that have been filed.
