### ISSUE TITLE
[Backport 2.5] Coredns-autoscaler needs readiness and liveness check

### ISSUE THREAD

**Issue by annablender** [rancher/rancher#36362]
What kind of request is this (question/bug/enhancement/feature request):
Bug

Steps to reproduce (least amount of steps as possible):
coredns autoscaler does not have a readiness and liveness check

Result:
If a node goes offline where coredns-autoscaler is running, it will not be rescheduled properly.

Other details that may be helpful:

Environment information

Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Installation option (single install/HA): HA
gz#7893
SURE-1649

Original issue: https://github.com/rancher/rancher/issues/24939

**Comment by annablender** [comment]
## Testing template

#### Root cause

N/A. CoreDNS autoscaler health checks requested for more debug info if a coredns-autoscaler pod is not able to be rescheduled onto a failed node.
 
#### What was fixed, or what changes have occurred

- Added new CoreDNS template with liveness and readiness probes for the autoscaler https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/templates/coredns_v1.8.3-rancher2.go
- Updated `templates.go` with new template https://github.com/rancher/kontainer-driver-metadata/blob/0d1175e5c569318589905b5255e41666f9a5b2a8/rke/templates/templates.go#L141

#### Areas or cases that should be tested

Test steps
1. Create an RKE1 downstream cluster on Rancher 2.6-head. The coredns autoscaler will deploy automatically
2. View the coredns autoscaler pod config
3. View Health Checks. You should see the health check fields configured

![image](https://user-images.githubusercontent.com/12955547/154151544-2165a4eb-518d-46ce-ad4f-3c9fb3a2d6d1.png)
 
#### What areas could experience regressions ?

If template gets overwritten or removed, then health checks will not show up as configured in the coredns-autoscaler pod for RKE1 downstream clusters.
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by annablender** [comment]
Discovered there are port requirements for the coredns autoscaler to expose health check endpoints at only `/healthz:8080`. Put in a PR to fix.

**Comment by rishabhmsra** [comment]
**Rancher Server:**
- v2.5.12 (KDM pointing to dev-v2.5)
- docker install 

**Validation steps followed as mentioned [here](https://github.com/rancher/rancher/issues/36362#issuecomment-1040808794):**
- Provisioned a single node AWS node driver `k8s v1.20.15-rancher1-1` cluster.
- Checked the `coredns-autoscaler` heatlh check fields and `Readiness` and `Liveness Check` are configured correctly.

![fresh-install](https://user-images.githubusercontent.com/36376154/156183814-1f967996-7d1f-4d6c-b5c5-cf1010d56d29.png)

**Result:**
- The Health Check fields values are configured as expected, hence closing the issue.
