### ISSUE TITLE
Scans are unsuccessful on SLE Micro 5.1 for k3s

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#36363]
**This likely affects rke2 also.**

**Description:**
When running a scan on k3s v1.21.9+k3s1, the scan mostly has failures. This appears to be because of the journalctl command used to retrieve the results.
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/55997940/152234526-a4d06e75-32e2-48fc-bf7e-35dc28cb3edd.png">
**Full Result:** [scan-4fl4k-f7rv6--2022-02-02-121334.csv](https://github.com/rancher/cis-operator/files/7989949/scan-4fl4k-f7rv6--2022-02-02-121334.csv)

I took one of the commands being run on a failure from https://rancher.com/docs/k3s/latest/en/security/self_assessment/#4-2-1 and ran it locally on my sle micro machine:
```
$ journalctl -D /var/log/journal -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'anonymous-auth' | grep -v grep
Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
```

Note that if I just run this by passing `sudo` in front, it is successful:
```
sudo journalctl -D /var/log/journal -u k3s | grep 'Running kube-apiserver' | tail -n1 | grep 'anonymous-auth' | grep -v grep
Feb 02 18:28:14 slemicro k3s[1343]: time="2022-02-02T18:28:14.671433040Z" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction --etcd-cafile=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/k3s/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/k3s/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
```

**Comment by doflamingo721** [comment]
As discussed offline, moving this ticket to backlog since it's not scheduled for 2.6.4.

**Comment by rishabhmsra** [comment]
**Validated on rancher v2.6-head(30344db) and the scans passed successfully**

**Steps followed:**
- On vSphere env 6, created the VMs using `SLE micro 5.1` template.
- Provisioned 2 k3s custom clusters `(3-nodes all role + 1-worker node)` using k8s versions -> `v1.22.7+k3s1` and `v1.21.10+k3s1`.
- Deployed CIS Benchmark chart and ran the scan using `k3s-cis-1.6-profile-permissive` profile. Scans passed successfully.
- Also ran the scans on a `single node all role` k3s custom clusters and the it passed successfully there as well.

**Result:**
- **v1.22.7+k3s1 :** 
![scans-passed1](https://user-images.githubusercontent.com/36376154/161500889-b7d8d2f4-aae3-4f40-8130-ab12a90832fd.png)

- **v1.21.10+k3s1 :**
![scans-passed](https://user-images.githubusercontent.com/36376154/161500953-371d7c0b-e256-4c63-b16a-0f1f4af2e970.png)

**Comment by rancher-max** [comment]
I can confirm that @rishabhmsra's steps are correct and this is working now. Thank you for your validations! I'm not sure which change caused this to work or if it was not an error initially and some mistake I made on my end (possibly vsphere changing IPs on me would be my guess if this is the case). Either way, this is complete and thank you again!
