### ISSUE TITLE
dashboard-metrics-scraper deployment error with RKE2

### ISSUE THREAD

**Issue by Torkolis** [rancher/rancher#36366]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): docker
- Proxy/Cert Details: self signed certificate and self signed ca certificate

**Information about the Cluster**
- Kubernetes version: v1.21.8+rke2r2
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**

kubernetes-dashboard: dashboard-metrics-scrapper deployment does not start

**To Reproduce**

nstall rancher in docker (image: rancher/rancher:latest).
Create RKE2 cluster and add nodes.
Install kubernetes dashboard with
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.4.0/aio/deploy/recommended.yaml

**Result**

dashboard-metrics-scrapper deployment does not start, error message:

Pods "dashboard-metrics-scraper-c45b7869d-" is forbidden: PodSecurityPolicy: unable to admit pod: [pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/dashboard-metrics-scraper]: Forbidden: seccomp may not be set]:Deployment does not have minimum availability.

**Expected Result**

deployment starts without error message

**Screenshots**

![image](https://user-images.githubusercontent.com/98939160/152300833-2088dde7-62fe-4744-95f0-a7aac153d4fd.png)

**Comment by cristianrat** [comment]
@Torkolis did you find a fix in the end?

**Comment by Torkolis** [comment]
No, I just stopped trying.

**Comment by cristianrat** [comment]
@Torkolis I had this issue with dashboard and fixed it by removing that block altogether
(ie: downloaded that chart locally, removed that sec setting, deployed - not ideal, but got it to work in the end)
