### ISSUE TITLE
unable to create Ingress on RKE2

### ISSUE THREAD

**Issue by Torkolis** [rancher/rancher#36365]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): docker
- Proxy/Cert Details: self signed certificate and self signed CA certificate

**Information about the Cluster**
- Kubernetes version: v1.21.8+rke2r2
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? Admin

   
**Describe the bug**

Unable to create a simple ingress

**To Reproduce**

install rancher in docker (image: rancher/rancher:latest). 
Create RKE2 cluster and add nodes.
Install e.g. kubernetes dashboard with 
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.4.0/aio/deploy/recommended.yaml
create a simple ingress in the kubernetes-dashboard namespace for the kubernetes-dashboard service

**Result**

error message:
Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://rke2-ingress-nginx-controller-admission.kube-system.svc:443/networking/v1/ingresses?timeout=10s": x509: certificate is valid for dockervm.mshome.net, not rke2-ingress-nginx-controller-admission.kube-system.svc

**Expected Result**
no error message and a new ingress being created

**Screenshots**
![image](https://user-images.githubusercontent.com/98939160/152300205-b0d80b0b-38d3-4d5a-8b6d-e84cf9860472.png)

**Comment by slickwarren** [comment]
confirmed that this is an issue on v2.6.5-rc5. 
you can also reproduce this by: 
* deploy a load balancer with a workload on a rke2 cluster

**Comment by slickwarren** [comment]
this was incorrectly reopened by myself -- we are able to create ingress using v2.6.5-rc5 on both rke1 and rke2 clusters.

**Comment by jiaqiluo** [comment]
hi @Torkolis, your issue is likely caused by the misconfiguration of the Niginx Ingress Controller. I do not have a solution right now, but recommend you to check both RKE2 documentation  and Nginx upstream repo for more information:
- https://docs.rke2.io/networking/#nginx-ingress-controller
- https://github.com/kubernetes/ingress-nginx/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by Torkolis** [comment]
I didn't change any configurations, everything was installed as default. Why is it misconfigured? Who is responsible for the default configuration? I thought because it is a rancher image it would be fitting to open the issue here so the default configuration can be fixed.
