### ISSUE TITLE
v2.6.4 Release Task - AKS/EKS/GKE Operator: Align Rancher internal operators to correct version.

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#36377]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/36375) for the rancher engineering team 2 to:

- [ ] Make the appropriate updates in the internal operators for AKS/EKS/GKE.

**Comment by paynejacob** [comment]
all 3 operators have been released, vendored into rancher, and added to the dev 2.6 charts branch
