### ISSUE TITLE
v2.6.4 Release Task - Charts: Align Rancher internal operators to correct version.

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#36376]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/36375) for the rancher engineering team 3 to:

- [ ] Make appropriate updates to the ENV vars in the rancher/rancher/package/Dockerfile

**Comment by eliyamlevy** [comment]
Task completed by @paynejacob in [this issue](https://github.com/rancher/rancher/issues/36377#issuecomment-1078351632) and verified again by me.

**Comment by eliyamlevy** [comment]
Created PR with changes, ready for release. 
https://github.com/rancher/rancher/pull/37053
