### ISSUE TITLE
On catalog page, footer is in middle of page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3637]
Version - master 2/17

Steps:
1.  Go to catalog page

results:  the footer is in the middle of the page
![image](https://cloud.githubusercontent.com/assets/11514927/13121535/d7031d72-d56f-11e5-8001-40740bdafd42.png)

Expected:  Should not be in middle of page.

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/481

**Comment by tfiduccia** [comment]
Version - master UI 0.91.0
Verified fixed
