### ISSUE TITLE
Unprivileged rootless container support

### ISSUE THREAD

**Issue by EvanCarroll** [rancher/rancher#36374]
**Is your feature request related to a problem? Please describe.**

Currently you can not run rancher in a unprivileged rootless container.  It would be nice if this was allowed.

**Describe the solution you'd like**

Two things are required to run rancher rootless,

* The default port must not be privileged. This is rather simple and rancher is violating best practice with this. Web servers in containers should run on unprivileged ports that are mapped to privilege ports by the container engine. Instead of `-p 80:80` have the web server inside run on 8080. Then to map it to 80 you can do `-p 8080:80/tcp`. This will allow non-root users to drop the `--privileged` flag and the dubious requirement that port 80 be declared unprivileged with `net.ipv4.ip_unprivileged_port_start=80`. This would also have side benefits such as allowing more than one copy of rancher to run simultaneously one with `-p 8080:8080/tcp` one with `-p 8080:8081/tcp`. This can be useful if you have a test runner that needs to run multiple containers.
* Currently [podman rejects files with UID(s)/GID(s) above 65536](https://www.redhat.com/sysadmin/rootless-podman) this creates compatibility issues with rootless containers. I'm not sure why or what files these are in the container with UIDs/GIDs above 65536. I would have to audit it.

----

This is both a superset of #16246 and better defined. If Rancher run unprivileged in a rootless container with podman, it would probably run in all other less-constrictive environments mentioned.

**Comment by eriksjolund** [comment]
Regarding the UIDs and GIDs with high numbers in the container, maybe it's possible remap them by using __--uidmap__ and __--gidmap__?

I did an experiment and remapped some of them. With the commands below I was able to print the rancher help page (`--help`)

```
subuidSize=$(( $(podman info --format "{{ range .Host.IDMappings.UIDMap }}+{{.Size }}{{end }}" ) - 1 ))
subgidSize=$(( $(podman info --format "{{ range .Host.IDMappings.GIDMap }}+{{.Size }}{{end }}" ) - 1 ))
uid=630384594
gid=600260513
podman --log-level=debug run \
  --uidmap $uid:5001:$(($subuidSize-5000)) \
  --uidmap 0:0:5001 \
  --gidmap $gid:5001:$(($subgidSize-5000)) \
  --gidmap 0:0:5001 \
  --name ranchertest \
  --privileged \
  --replace \
  --restart=unless-stopped \
  -p 443:443 \
  -p 80:80 \
  -v ./logs:/var/log/auditlog:Z \
    docker.io/rancher/rancher:latest --help
```

```
$ podman --version
podman version 4.0.0-rc4
```



In my case the number of subordinate UIDs and GIDs was:

```
$ echo $subuidSize 
65536
$ echo $subgidSize 
65536
$ 
```

I think 65536 is just an arbitrary number. It is set in the file _/etc/login.defs_

```
$ grep SUB_UID_COUNT  /etc/login.defs 
SUB_UID_COUNT		    65536
$ grep SUB_GID_COUNT  /etc/login.defs 
SUB_GID_COUNT		    65536
$ 
```
The values influence how many subordinate UIDs and GIDs a new user get by default when
the account is created.

If I replace `--help` with  `--trace --debug --no-cacerts   --audit-level 3` the command fails.
Here are the logs:


```
$ podman logs ranchertest
2022/02/05 16:11:01 [DEBUG] Loglevel set to [debug]
2022/02/05 16:11:01 [TRACE] Loglevel set to [trace]
2022/02/05 16:11:01 [INFO] Rancher version v2.6.3 (3c1d5fac3) is starting
2022/02/05 16:11:01 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:true Trace:true NoCACerts:true AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:3 Features: ClusterRegistry:}
2022/02/05 16:11:01 [INFO] Listening on /tmp/log.sock
2022/02/05 16:11:01 [INFO] Waiting for k3s to start
time="2022-02-05T16:11:01Z" level=info msg="Acquiring lock file /var/lib/rancher/k3s/data/.lock"
time="2022-02-05T16:11:01Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/e61cd97f31a54dbcd9893f8325b7133cfdfd0229ff3bfae5a4f845780a93e84c"
2022/02/05 16:11:02 [INFO] Waiting for k3s to start
2022/02/05 16:11:03 [FATAL] k3s exited with: exit status 1
$
```

**Comment by S0LERA** [comment]
Any updates on this?

It's impossible to deploy rancher as isolated container on cloud services like Azure Container Instances or AWS Fargate because of the --privileged flag.

**Comment by coopbri** [comment]
> Any updates on this?
> 
> It's impossible to deploy rancher as isolated container on cloud services like Azure Container Instances or AWS Fargate because of the --privileged flag.

Same situation on [Railway](https://railway.app/) as well

**Comment by S0LERA** [comment]
Any updates?
