### ISSUE TITLE
v2.6.4 Release Task - Branch Repos If Needed

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#36380]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/36375) for the rancher engineering release captain to:

- [ ] Branch appropriately if there is a new minor version for Rancher, or identify if a specific release (v/x.y.x) branch might be needed.

**Comment by paynejacob** [comment]
given this is a patch release we will not need to branch for this release.
