### ISSUE TITLE
v2.6.4 Release Task - Release System-Agent

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#36389]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/36375) for the rancher engineering release captain:

- [ ] Tag the release onto the correct branch and push the https://github.com/rancher/system-agent

**Comment by paynejacob** [comment]
https://github.com/rancher/system-agent/releases/tag/v0.2.3
