### ISSUE TITLE
v2.6.4 Release Task - Release RKE

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#36387]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/36375) for the rancher engineering team 2 and the Release Captain to:

- [ ] Release RKE and update the RKE Tag in Rancher.

**Comment by paynejacob** [comment]
https://github.com/rancher/rke/releases/tag/v1.3.8
