### ISSUE TITLE
v2.6.4 Release Task - Do Charts Cleanup

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#36384]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/36375) for the rancher engineering team 3 & the Release captain to:

- [ ] Confer with team 3 on KDM changes and then perform charts cleanup by validating:
- Each chart only includes 1 new version
- Ensure each new chart version is in the "New charts for 2.6.x" issue ([rancher/36185](https://github.com/rancher/rancher/issues/36185)) or verify with QA
- Nothing is being removed in any way, only additions to index.yaml or new files
- Ensure the new chart versions are not already live (check charts directory in release-v2.5 branch)

**Comment by MKlimuszka** [comment]
This occurs after the release.
