### ISSUE TITLE
v2.6.4 Release Task - Release CLI

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#36388]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/36375) for the rancher engineering release captain:

- [ ] Validate that the commits in go.mod are valid, then tag the RC.

**Comment by paynejacob** [comment]
https://github.com/rancher/cli/releases/tag/v2.6.4
