### ISSUE TITLE
v2.6.4 Release Task - Prepare Draft PRs for releasing charts.

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#36383]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/36375) for the rancher engineering team 3 & the Release captain to:

- [x] System-Charts: Make a PR from the dev branch into the release-branch. Review to make sure the system charts seem aligned with what’s expected. The title of the PR should be the release vehicle that all the system charts are being added for.
- [x] Charts: See the checklist for specific information.

**Comment by MKlimuszka** [comment]
PR is ready, will be reviewed again this afternoon.
