### ISSUE TITLE
Rancher keeps installing old prometheus-operator 0.02 even when monitoring v1 is removed from cluster

### ISSUE THREAD

**Issue by herrbpl** [rancher/rancher#36395]
**Is your feature request related to a problem? Please describe.**
I cannot uninstall v1 monitoring when I've already upgraded Rancher to 2.6.x. Rancher keeps forcing prometheus-operator-0.0.2 on downstream cluster and this conflicts with v2 monitoring

**Describe the solution you'd like**
Documentation/steps how to fully clean out v1 monitoring so that it will not come back. How to kill that Hydra!

**Comment by piyush94** [comment]
Facing the same issue in 2.5.12.
v1 monitoring keeps reinstalling.

**Comment by danielhass** [comment]
@herrbpl I think we ran into the same issue (if I understand your description correctly).

The following Rancher Forum thread helped us to resolve the issue: [15908](https://forums.rancher.com/t/completely-disabling-monitoring-and-alarming/15908)
