### ISSUE TITLE
Hosts from default showing up in other environments

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3639]
Version - master 2/17

Steps:
1.  Install rancher with 2 10acre machines
2.  Go into rancher and create another environment (call it test)
3.  Go to default environment and add/start a container
4.  Go to test environment and go to host page

Results:  The host that the container is being added to pops up on in my test environment's host page.
![image](https://cloud.githubusercontent.com/assets/11514927/13122008/26cfd938-d572-11e5-87e0-c96e2629baa8.png)

Expected:  The host should not show up anywhere outside it's own environment.

**Comment by vincent99** [comment]
There's a timer that watches to see pings from the subscription websocket that wasn't getting cancelled when you switched environments, which would then reconnect the one for the old env.  But only if you have the timing "right".

**Comment by tfiduccia** [comment]
Version - master 2/26
Verified fixed
