### ISSUE TITLE
Could we add a details link within the dropdown menus of our objects?

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#364]
Version: v0.13.0

In the host view, it's not apparent that the host name is click-able and would go to the host detail page. Since the host name is black text, it doesn't stand out as a link. When you hover over it, it becomes a link, which is fine, but you kind of have to find it.

![screen shot 2015-03-27 at 2 51 01 pm](https://cloud.githubusercontent.com/assets/11410997/6877779/8ae2d8ae-d491-11e4-9a93-ffe76a883d4a.png)

In the other pages, it's clear that that the names are links as they are colored differently and in a list format. 

![screen shot 2015-03-27 at 2 52 58 pm](https://cloud.githubusercontent.com/assets/11410997/6877733/f9d0fefe-d490-11e4-977c-28b6afb0d2a4.png)

For private registry, you would expect that editing the registry would provide you with the access to the credentials, but those are actually located in the registry details page. It was a bit unintuitive, but if there was a details link in the drop down, I would have tried that link.

Would creating a details link in the dropdown menu help users? It would be another navigation tool for users to find the detailed page.

**Comment by vincent99** [comment]
Obsolete
