### ISSUE TITLE
[Apps & Marketplace V2] Add or update annotations to support RKE2 clusters to all charts

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#36401]
#### Background

Before RKE2, on defining a cluster Rancher knew exactly what OSs are going to be contained in it; if it was a normal cluster, it was all Linux and if it was a Windows cluster, it was always Linux + Windows.

Therefore, we initially built an annotation on charts called `catalog.cattle.io/os` that would indicate whether this chart should be shown on a Linux or Windows cluster and that's what the catalog would show.

We never dealt with having to switch what charts are shown on the catalog; since the list of OSs is fixed **on defining a cluster**, the view on the catalog also used to be fixed.

We never dealt with any issues where a chart was installed but the cluster no longer supports it; it would **never have been shown on the catalog to install in the first place**.

#### Problem

In RKE2, **the list of OSs that will be contained within a cluster is ambiguous**; it is always possible to add or remove Windows / Linux nodes.

This is identical to the same issue we have in Apps & Marketplace V2 around node architectures; we don't have any mechanism for indicating a chart is supported or is permitted in a cluster that contains nodes with a given architecture.

Therefore, we currently have an undefined UX on the Rancher catalog for RKE2. Namely:

- How do we know which charts are currently deployable onto or fully functional in a cluster?
- If a chart is installed and the definition of a cluster switches (e.g. you introduce or remove OSs or archs from the cluster), how should the Rancher UI reconcile this behavior?

#### Solution

Every chart in rancher/charts should now add and support the following annotations:
- `catalog.cattle.io/deploys-on-os`: indicates that a chart needs `global.cattle.OS.enabled` to be set for the OSs provided by a comma-separated list
  - No default
- `catalog.cattle.io/deploys-on-arch` (NEW): indicates that a chart needs `global.cattle.ARCH.enabled` to be set for the archs provided by a comma-separated list
  - No default
- `catalog.cattle.io/permits-os`: indicates that the chart is deployable onto clusters who have nodes with OSs provided by a comma-separated list
  - Default if not exists: `catalog.cattle.io/permits-os: linux`
- `catalog.cattle.io/permits-arch`: indicates that the chart is deployable onto clusters who have nodes with archs provided by a comma-separated list
  - Default if not exists: `catalog.cattle.io/permits-arch: amd64`

This will be a **two-step process**:
1. Modifying all existing charts in the dev-v2.6 branch to add these annotations
2. Modifying annotations on all **already released charts** in the release-v2.6 branch to add these annotations, e.g. Monitoring

#### UI Integration

In coordination with these backend fixes, several tickets will be filed in rancher/dashboard in order to implement banners or different UXs based on the existence of these annotations:
- https://github.com/rancher/dashboard/issues/5054
- https://github.com/rancher/dashboard/issues/5055
- https://github.com/rancher/dashboard/issues/5056
- https://github.com/rancher/dashboard/issues/5057
- https://github.com/rancher/dashboard/issues/5058

Note: UI should **not** blocked on backend to introduce these fixes since defaults for the annotations are outlined, however QA will be blocked on testing till UI and backend fixes are in.

**Comment by aiyengar2** [comment]
https://github.com/rancher/rancher/issues/34057 will require us to do an OOB release for charts to update annotations anyways, so they should be done together in one PR

**Comment by aiyengar2** [comment]
https://github.com/rancher/rancher/issues/36403 will be additional work we need to do anyways to get all of our charts tolerated on Windows clusters, so the first action item should be done in conjunction with these chart changes.

**Comment by aiyengar2** [comment]
note: I edited the PR description to use `catalog.cattle.io/deploys-on-os` instead of `catalog.cattle.io/os` since `catalog.cattle.io/os` has an older definition that would break older Rancher setups if we choose to modify what it means.

Description should be up-to-date now with the expectations.

**Comment by aiyengar2** [comment]
Talked to @PennyScissors about the default for `catalog.cattle.io/deploys-on-os` and we decided that there should be no default since it's only an annotation you need to add if you want to set the `global.cattle.*.enabled` field.

cc: @mantis-toboggan-md

**Comment by phillipsj** [comment]
Rancher Wins Upgrade has been dev validate. No upgrade needed to occur and the upgrader deamon did a noop. Everything installed and the card is displaying correctly.

![rancher-wins-upgrader-card](https://user-images.githubusercontent.com/1568133/155407121-8a84e9fd-af87-455d-be20-a7229b3f77d6.png)
![rancher-wins-upgrader-chart-install](https://user-images.githubusercontent.com/1568133/155407126-cc217420-85a5-4709-817e-df3092363d21.png)

**Comment by phillipsj** [comment]
Rancher Loggin Chart has been dev-validated. The card is displaying correctly, and everything has installed without error.
![logging-card](https://user-images.githubusercontent.com/1568133/155408453-0710478c-791f-4e9d-92db-072fa8393553.png)
![logging-chart-installation](https://user-images.githubusercontent.com/1568133/155408463-54e889ae-c055-4754-b3fd-afda498d320d.png)

**Comment by phillipsj** [comment]
Harvester charts are displaying correctly.
![harvester-charts-cards](https://user-images.githubusercontent.com/1568133/155409851-cbc98935-7c29-437b-9724-3e63b15d2343.png)

**Comment by phillipsj** [comment]
Rancher Monitoring Chart has been dev-validated.
![monitoring-card](https://user-images.githubusercontent.com/1568133/155419925-c9f899ee-21bb-440e-9451-c5e96fd3c712.png)
![monitoring-chart-installation](https://user-images.githubusercontent.com/1568133/155419934-25d0a815-79c4-4aab-9601-6088d8303d02.png)

**Comment by phillipsj** [comment]
Longhorn card looks directly, and it only designates that it works for Linux only. If a Windows node is present it fails to deploy correctly, if the Windows node is cordoned, then everything installs without error.
![longhorn-card](https://user-images.githubusercontent.com/1568133/155420526-3b2eb7b4-cd77-46be-9dfc-58bae564d555.png)
![longhorn-chart-installation](https://user-images.githubusercontent.com/1568133/155420529-600ea9d7-6633-450a-b74a-82ef2fa04cc9.png)

**Comment by phillipsj** [comment]
SRIOV card looks correct. It installed just fine without a Windows node using the correct CNI. With a Windows node it partially installs and fails because multus isn't available.
![sriov-card](https://user-images.githubusercontent.com/1568133/155423551-8e2dad3e-2c51-4672-9ddb-c8463fae01aa.png)
![sriov-chart-installation](https://user-images.githubusercontent.com/1568133/155423554-1c6b476e-402c-4f21-ae92-57516df43dec.png)

**Comment by phillipsj** [comment]
Alerting card looks correct and installs without error.
![alerting-card](https://user-images.githubusercontent.com/1568133/155423948-1a75b09f-9125-4560-8210-d37c1bde3f57.png)
![alerting-chart-installation](https://user-images.githubusercontent.com/1568133/155423958-2fc14618-dc13-41b2-93ab-c0d90c0e894f.png)

**Comment by phillipsj** [comment]
GMSA card is correct and installed without error.
![gmsa-card](https://user-images.githubusercontent.com/1568133/155426390-0e10618e-cce6-44a0-92ae-56c1138a10ed.png)
![gmsa-chart-installation](https://user-images.githubusercontent.com/1568133/155426397-f0f2beeb-73c7-4b23-b6a9-c9e2cbd05677.png)

**Comment by phillipsj** [comment]
@sirredbeard looks like the changes we have made for the CIS Benchmark chart will be able to close this issue. https://github.com/rancher/rancher/issues/36265

**Comment by phillipsj** [comment]
External IP Webhook card looks correct and installs.
![external-ip-webhook-card](https://user-images.githubusercontent.com/1568133/155443196-e53c8bae-46e7-4c85-aa0b-2fcfc3485c1a.png)
![external-ip-webhook-chart-installation](https://user-images.githubusercontent.com/1568133/155443204-d14d2d3b-6a37-4dbd-b65e-dabf65a4fbd2.png)

**Comment by phillipsj** [comment]
CIS chart card and installation are working.
![cis-benchmark-card](https://user-images.githubusercontent.com/1568133/155556731-daf6181a-f68e-4500-ba6b-9867f7438d65.png)
![cis-chart-installation](https://user-images.githubusercontent.com/1568133/155556737-08f22796-d68b-4d33-94a8-7f92937b8de3.png)

**Comment by phillipsj** [comment]
Istio card and chart are working. 
![istio-card](https://use
![istio-chart-installed](https://user-images.githubusercontent.com/1568133/155566579-a6f33a96-14ef-4d36-9bbd-f6053372f4c6.png)
r-images.githubusercontent.com/1568133/155566565-e19561b8-02e6-4bd1-8070-7c4327a6f38f.png)

**Comment by rosskirkpat** [comment]
vsphere-cpi installation is working through helm install only. The vsphere-cpi chart cannot be deployed to an rke2 cluster that has the cluster cloud provider set to `external`, which is required for the out-of-tree vsphere charts as far as I am aware. If an rke2 cluster is provisioned with the cloud provider set to `external` it will not show the nodes as active until a cloud provider is deployed through helm that removes the following taint.

```yaml
 taints:
  - effect: NoSchedule
    key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
```

![Screen Shot 2022-02-24 at 3 49 38 PM](https://user-images.githubusercontent.com/55704795/155628886-1bd13daf-5f3b-43dd-a35f-077b47e3673a.png)
![Screen Shot 2022-02-24 at 3 49 45 PM](https://user-images.githubusercontent.com/55704795/155628887-4388cf2f-5771-4efd-859e-ea942197bafc.png)
![Screen Shot 2022-02-24 at 3 49 21 PM](https://user-images.githubusercontent.com/55704795/155628888-63bc32d5-b6f5-4f23-bd10-a4f49393dadb.png)

**Comment by rosskirkpat** [comment]
vsphere-csi card and chart is working. 
<img width="709" alt="image" src="https://user-images.githubusercontent.com/55704795/155629867-6c8f65f0-03e9-47fa-855d-8e64a22541bd.png">
![Screen Shot 2022-02-24 at 3 57 03 PM](https://user-images.githubusercontent.com/55704795/155629320-2e8c198d-1992-4170-a92e-4f41e7327921.png)
![Screen Shot 2022-02-24 at 3 57 11 PM](https://user-images.githubusercontent.com/55704795/155629324-99cd4cf4-2306-43b7-9d20-944409a3ee3c.png)

**Comment by luthermonson** [comment]
This issue is going to be superceded by a previous dashboard issue which captures everything and has all PRs linked up. You can see context https://github.com/rancher/dashboard/issues/5137#issuecomment-1062323770

**Comment by sirredbeard** [comment]
Awaiting updates from Arvind and PR https://github.com/rancher/charts/pull/1813

**Comment by sirredbeard** [comment]
Unblocked. Pending dev validation by Team 3.
