### ISSUE TITLE
Launching dozen of AWS instances has high failure rate

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#3640]
**Version**: Rancher v0.56.1
**Issue**: when launching 10+ machines via the Rest API, almost 1 out of 10 machines (sometimes more) are failing at various stages. This is probably due to AWS Api rate limits. This is expected to improve with the following fix in Docker Machine:
https://github.com/docker/machine/commit/c568bb8805ab49de7009f699d4da8f2bfac54725

This bug has been created to keep track of the release of this improvement, as well as aknowledge the  issue.

**Comment by deniseschannon** [comment]
As you mentioned, this is due to docker-machine. When a new release of docker-machine comes out, Rancher picks it up as quickly as possible and we can close this issue when the fix is released in docker-machine.

**Comment by jloisel** [comment]
Docker machine 0.7.0 is out :)
https://github.com/docker/machine/releases/tag/v0.7.0

**Comment by jloisel** [comment]
Is there a reasonable timeframe for this to get fixed? It's getting bumped from one version to another for more than 6 months now.

**Comment by vincent99** [comment]
We've been stuck on 0.6 because the Azure driver changed to only support Oauth, but there is now API key auth available in master so we will probably be shipping a build from master in 1.2-dev3.

**Comment by tfiduccia** [comment]
Version - master 8/25
Verified fixed
