### ISSUE TITLE
After reinstall rancher bootstrap password no working

### ISSUE THREAD

**Issue by giuseppe-ao** [rancher/rancher#36417]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): HELM on EKS
- Proxy/Cert Details: RapidSsl 

**Information about the Cluster**
- Kubernetes version: 1.21
- Cluster Type (Local/Downstream): Local
- Hosted=EKS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)

No Login (bootstrap password)

   
**Describe the bug**

After removing Rancher with the system tools and reinstalling the new version 2.6.3 with the Helm chart it was no longer possible to login with the bootstrap password. 

After uninstalling Rancher the nodes of the eks cluster were no longer visible, we had to create a new group of nodes for the pods to be deployed. 

**To Reproduce**
`system-tools remove -c $KUBECONFIG`
`helm install rancher rancher-stable/rancher --namespace cattle-system --set bootstrapPassword=PassW0rd --set hostname=rancher.mydomain.com --set replicas=3 --set ingress.tls.source=secret --set letsEncrypt.email=info@mydomain.com --version 2.6.3`

**Result**
Unable to login and initial setup

**Expected Result**
Login and do the initial setup

**Screenshots**
<img width="837" alt="Schermata 2022-02-06 alle 12 40 35" src="https://user-images.githubusercontent.com/74664595/152679170-cf86664c-57e4-4dba-a3e7-84006cf21cf5.png">

**Additional context**
When trying to log in on the pods logs display these errors: 

`2022/02/06 11:25:47 [ERROR] error syncing 'services-view': handler mgmt-auth-roletemplate-lifecycle: errors deleting dowstream clusterRole: [NotFound 404: failed to find cluster], requeuing
2022/02/06 11:25:47 [ERROR] error syncing 'project-monitoring-readonly': handler mgmt-auth-roletemplate-lifecycle: errors deleting dowstream clusterRole: [NotFound 404: failed to find cluster], requeuing
2022/02/06 11:25:47 [ERROR] error syncing 'view': handler mgmt-auth-roletemplate-lifecycle: errors deleting dowstream clusterRole: [NotFound 404: failed to find cluster], requeuing
2022/02/06 11:25:47 [INFO] remove kontainerdriver googlekubernetesengine
2022/02/06 11:25:47 [ERROR] error syncing 'googlekubernetesengine': handler mgmt-kontainer-driver-lifecycle: error getting schema: dynamicschemas.management.cattle.io "cluster" not found, requeuing
2022/02/06 11:25:47 [ERROR] error syncing 'clustercatalogs-manage': handler mgmt-auth-roletemplate-lifecycle: errors deleting dowstream clusterRole: [NotFound 404: failed to find cluster], requeuing
2022/02/06 11:25:49 [ERROR] error syncing 'p-gj88s/u-krouf4zbja-member': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2022/02/06 11:25:49 [ERROR] error syncing 'p-2288z/u-hbjp472guf-member': handler mgmt-auth-prtb-controller: failed to remove finalizer on controller.cattle.io/mgmt-auth-prtb-controller, requeuing
2022/02/06 11:25:50 [ERROR] failed to call leader func: create not allowed while custom resource definition is terminating
2022/02/06 11:25:55 [ERROR] failed to call leader func: create not allowed while custom resource definition is terminating`

**Comment by nudzo** [comment]
The same on my side.

I see in browser dev tools, that `/v3-public/localProviders/local?action=login` XHR is going to `http://..` not `https://...` in spit of fact Rancher UI is doing redirect to HTTPS itself.

**Comment by dellkeji** [comment]
the same problem on my host.

how to resolve this project, in order to access ui

**Comment by nudzo** [comment]
Solved. Uninstall doesn't clean up resources in k8s, which causes mess in configuration. You have to setup new cluster or clean it up. Use this gist, to clean: https://gist.github.com/nudzo/b72d31d965ee26ede06f32ee9756b581

**Comment by meappy** [comment]
> Solved. Uninstall doesn't clean up resources in k8s, which causes mess in configuration. You have to setup new cluster or clean it up. Use this gist, to clean: https://gist.github.com/nudzo/b72d31d965ee26ede06f32ee9756b581

Have you tried Rancher [system-tools](https://rancher.com/docs/rancher/v2.5/en/system-tools/)? I'm still having issues but wondering if you've solved this with the script as opposed to using system-tools

**Comment by nudzo** [comment]
I've never used those tools. Script just search any CRD having `cattle` in its name and then goes through Rancher namespaces and delete every custom resource belonging to those CRDs... for namespaced resources. For cluster wide ones it also drops finalizers before deleting. Running that after Rancher Helm chart got uninstalled.

**Comment by prog76** [comment]
this gist can cleanup even more resources
https://gist.github.com/prog76/0e1c83d6716c880176ae7ee03844b353
for namespaces like: local, p-72hlm, ...
