### ISSUE TITLE
[v2.5] tcp-services-configmap and udp-services-configmap upon upgrade to k8s version using nginx-0.49.3-rancher1 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#36433]
Backport fix for https://github.com/rancher/rancher/issues/35943

**Comment by kinarashah** [comment]
Fixed via https://github.com/rancher/kontainer-driver-metadata/pull/815

**Comment by vivek-infracloud** [comment]
### Validated on rancher version v2.5.12

**Observed following results:**

**Validation scenario 1:** k8s cluster use nginx version 0.35-rancher2 and 0.49.3-rancher1
- Provision a single node custom cluster with v1.18.20-rancher1-3.
- Added an nginx Deployment to the default Namespace with a ClusterIP service to port 80
- Added 8080: default/nginx:80 to the tcp-services ConfigMap in the ingress-nginx Namespace
- Confirm access to nginx works via :8080
- Upgrade to v1.19.16-rancher1-2 (nginx version 0.49.3-rancher1)
- Access to nginx no longer works via :8080.
- Following arguments are missing on nginx-ingress-controller Daemonset
> -- tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
    -- udp-services-configmap=$(POD_NAMESPACE)/udp-services
- Needs work around to fix the missing access to nginx via :8080.

**Validation scenario 2:** k8s cluster use nginx version 0.49.3-rancher1
- Provision a single node custom cluster with v1.19.16-rancher1-2.
- Added an nginx Deployment to the default Namespace with a ClusterIP service to port 80
- Added 8080: default/nginx:80 to the tcp-services ConfigMap in the ingress-nginx Namespace
- **Access to nginx failed via :8080**
- Added following 2 arguments in the nginx-ingress-controller DaemonSet.
 > -- tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
    -- udp-services-configmap=$(POD_NAMESPACE)/udp-services
- Access to nginx works via :8080
- Upgrade to v1.20.14-rancher2-2 (nginx version = 0.49.3-rancher1)
- Access to nginx still works via :8080.

**Comment by vivek-infracloud** [comment]
Access to nginx works with port :8080 after adding following two arguments.
  

> -- tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
>   -- udp-services-configmap=$(POD_NAMESPACE)/udp-services

Hence, the behaviour is expected, closing the issue.
