### ISSUE TITLE
Unable to execute shell for windows pods as admin user

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36432]
**Rancher Server Setup**
- Rancher version: v2.6.4-rc2
- Installation option (Docker install/Helm Chart):helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):rke1
- Proxy/Cert Details:valid certs

**Information about the Cluster**
- Kubernetes version: 1.22.6+rke2r1
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom with windows nodes (version 2022)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin user

   
**Describe the bug**

users are unable to execute shell through rancher on windows pods

**To Reproduce**
 
* on a cluster with windows nodes, deploy a windows workload
* exec into the pod for that windows workload

**Result**
user is unable to execute shell for the windows pod

**Expected Result**
we should be able to exec into windows workloads

**Additional context**
full pod logs -- tbd

**Comment by rosskirkpat** [comment]
Further debugging of this issue is blocked due to:
https://github.com/rancher/rancher/issues/36512
https://github.com/rancher/loglevel/issues/11

Without the ability to set Rancher logging to debug/trace, we are unable to view the relevant errors (or any pertinent log lines) relating to executing a rancher shell for a Windows pod.

**Comment by sirredbeard** [comment]
Does not work with Windows Firewall turned on.

**Comment by samjustus** [comment]
@sirredbeard mike is out - can we move this back to-test?

**Comment by sirredbeard** [comment]
Yes. @samjustus

**Comment by slickwarren** [comment]
tested on v2.6-head (228a585):
* deploy windows cluster (v1.22.8+rke2r1) using windows 2022
* deploy a windows workload
* as admin, shell into the workload -- pass
* as admin, execute commands in the shell (cmd, powershell) -- pass
*  as standard user, cluster owner shell into the workload -- pass
* as standard user, cluster owner execute commands in the shell (cmd, powershell) -- pass
* as base user, project owner shell into the workload -- pass
* as base user, project owner execute commands in the shell (cmd, powershell) -- pass

**Comment by samjustus** [comment]
SURE-4589
