### ISSUE TITLE
Slow environment switch

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#3643]
We have a growing number of environments, and one major pain-point is the time it takes to switch environment. Most of the time is to load the settings, as it would seem.. Any way to optimize this?

![image](https://cloud.githubusercontent.com/assets/72965/13146097/61f6e776-d654-11e5-9aeb-4af370e1c152.png)

**Comment by ibuildthecloud** [comment]
Yeah, I just noticed that one this week.  Just out of curiosity, if you are logged in as a non-admin to you see that it's faster?

**Comment by kaos** [comment]
No, `settings` seems to take about 3 sec for non admin users too..

**Comment by ibuildthecloud** [comment]
I found the problem.  We we're going for one query, but instead listing settings fires 563 DB queries.  So.... room for optimization :)  Will fix :)

**Comment by kaos** [comment]
Excellent! Thank you :)

**Comment by tfiduccia** [comment]
version - master 2/26
Verified fixed
