### ISSUE TITLE
[v2.6] KDM Update for K8s February patch release

### ISSUE THREAD

**Issue by doflamingo721** [rancher/rancher#36435]
# KDM Updates
TO BE RELEASED: Rancher v2.6.4

| New Kubernetes Version | Min Rancher Version | Min RKE Version |
| ---------------------- | ------------------- | --------------- |
| 1.23.4-rancher1-1      | 2.6.4-rc0                 | 1.3.3-rc0             |
| 1.22.7-rancher1-1      | 2.6.3-rc0                 | 1.3.3-rc0             |
| 1.21.10-rancher1-1      | 2.6.0-rc0                 | 1.3.0-rc0             |
| 1.20.15-rancher1-2     | 2.5.11-rc0           | 1.2.14-rc0       |
| 1.19.16-rancher1-4     | 2.5.11-rc0           | 1.2.14-rc0       |

### Rancher System Images & Add-ons
**_Note: Please update system images and add-ons in the template as needed._**

TBD

# Developer Changelog
- Add templates for new K8s versions. If a template that hasn't been released yet already exists, update it in place.
- Update the default K8s version, and add or update the version information (`MinRancherVersion` and `MinRKEVersion`) in [k8s_version_info.go](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/k8s_version_info.go) for new K8s versions if needed (Use table from above).
- Confirm versions for system images, add-on templates are correct using versioning reference table from below (expand details to view the table). Update the table if new versions are introduced.
- Confirm add-on template version constraints in [template.go](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) are correct using versioning reference table from below (expand details to view the table). Update the table if needed.

# Versioning Reference
<details>
<summary>
Expand for system images & add-on templates versioning table
</summary>
</br>

**_Note: Truncated repository names with a `*` indicates there are multiple images with that prefix. All repository names that match a truncated prefix should be checked for the same version stated in the table._**
**_For example: `rancher/weave-*` matches `weaveworks/weave-kube` and `weaveworks/weave-npc`, and they should both have the same version._**

## v1.23.4-rancher1-1
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.4.16-rancher1      |
| rancher/hyperkube                                        | v1.23.4-rancher1      |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/mirrored-k8s-dns-*                               | 1.17.4                |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/mirrored-coreos-flannel                          | v0.15.1               |
| rancher/flannel-cni                                      | v0.3.0-rancher6       |
| rancher/mirrored-calico-*                                | v3.19.1               |
| weaveworks/weave-*                                       | 2.8.1                 |
| noiro/* (All ACI images)                                 | 5.1.1.0.1ae238a       |
| rancher/mirrored-pause                                   | 3.4.1                 |
| rancher/nginx-ingress-controller                         | nginx-1.1.0-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.5.1                |
| rancher/mirrored-coredns-coredns                         | 1.8.4                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.18.0                |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov319                         |
| Canal         | canalv3211                          |
| Flannel       | flannelv0140                       |
| CoreDNS       | coreDnsv183                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv050                  |
| Weave         | weavev120                          |
| Aci           | aciv500                            |
| NginxIngress  | nginxIngressv110Rancher3                  |
| Nodelocal     | nodelocalv121                      |

## v1.22.7-rancher1-1
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.4.16-rancher1      |
| rancher/hyperkube                                        | v1.22.7-rancher1      |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/mirrored-k8s-dns-*                               | 1.17.4                |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/mirrored-coreos-flannel                          | v0.15.1               |
| rancher/flannel-cni                                      | v0.3.0-rancher6       |
| rancher/mirrored-calico-*                                | v3.19.1               |
| weaveworks/weave-*                                       | 2.8.1                 |
| noiro/* (All ACI images)                                 | 5.1.1.0.1ae238a       |
| rancher/mirrored-pause                                   | 3.4.1                 |
| rancher/nginx-ingress-controller                         | nginx-1.1.0-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.5.1                |
| rancher/mirrored-coredns-coredns                         | 1.8.4                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.18.0                |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov319                         |
| Canal         | canalv3211                          |
| Flannel       | flannelv0140                       |
| CoreDNS       | coreDnsv183                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv050                  |
| Weave         | weavev120                          |
| Aci           | aciv500                            |
| NginxIngress  | nginxIngressv110Rancher3                  |
| Nodelocal     | nodelocalv121                      |

## v1.21.10-rancher1-1
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.4.16-rancher1      |
| rancher/hyperkube                                        | v1.21.10-rancher1      |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/mirrored-k8s-dns-*                               | 1.17.4                |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/mirrored-coreos-flannel                          | v0.15.1               |
| rancher/flannel-cni                                      | v0.3.0-rancher6       |
| rancher/mirrored-calico-*                                | v3.19.1               |
| weaveworks/weave-*                                       | 2.8.1                 |
| noiro/* (All ACI images)                                 | 5.1.1.0.1ae238a       |
| rancher/mirrored-pause                                   | 3.4.1                 |
| rancher/nginx-ingress-controller                         | nginx-1.1.0-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.5.0                |
| rancher/mirrored-coredns-coredns                         | 1.8.4                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.18.0                |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov319                         |
| Canal         | canalv319                          |
| Flannel       | flannelv115                       |
| CoreDNS       | coreDnsv183                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv050                  |
| Weave         | weavev120                          |
| Aci           | aciv500                            |
| NginxIngress  | nginxIngressv110Rancher3                  |
| Nodelocal     | nodelocalv121                      |

## v1.20.15-rancher1-2
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.4.15-rancher1      |
| rancher/hyperkube                                        | v1.20.16-rancher1     |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/mirrored-k8s-dns-*                               | 1.15.10               |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.1                 |
| rancher/coreos-flannel                                   | v0.15.1-rancher1      |
| rancher/flannel-cni                                      | v0.3.0-rancher6       |
| rancher/mirrored-calico-*                                | v3.17.2               |
| rancher/mirrored-coreos-flannel                          | v0.13.0               |
| rancher/mirrored-calico-pod2daemon-flexvol               | v3.17.2               |
| weaveworks/weave-kube                                    | 2.8.1                 |
| weaveworks/weave-npc                                     | 2.8.1                 |
| noiro/* (All ACI images)                                 | 5.1.1.0.1ae238a       |
| rancher/mirrored-pause                                   | 3.2                   |
| rancher/nginx-ingress-controller                         | nginx-1.1.0-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.5.0                |
| rancher/mirrored-coredns-coredns                         | 1.8.0                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.1                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.15.13               |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov3171                        |
| Canal         | canalv3171                         |
| Flannel       | flannelv115                        |
| CoreDNS       | coreDnsv117                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv120                  |
| Weave         | weavev120                          |
| Aci           | aciv500                            |
| NginxIngress  | nginxIngressv0493                  |
| Nodelocal     | nodelocalv115                      |

## v1.19.16-rancher1-4
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.4.15-rancher1      |
| rancher/hyperkube                                        | v1.19.14-rancher1     |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/mirrored-k8s-dns-kube-dns                        | 1.15.10               |
| rancher/mirrored-k8s-dns-dnsmasq-nanny                   | 1.15.10               |
| rancher/mirrored-k8s-dns-sidecar                         | 1.15.10               |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.1                 |
| rancher/coreos-flannel                                   | v0.13.0-rancher1      |
| rancher/flannel-cni                                      | v0.3.0-rancher6       |
| rancher/mirrored-calico-*                                | v3.16.5               |
| rancher/coreos-flannel                                   | v0.13.0-rancher1      |
| rancher/mirrored-calico-pod2daemon-flexvol               | v3.16.5               |
| weaveworks/weave-*                                       | 2.7.0                 |
| noiro/* (All ACI images)                                 | 5.1.1.0.1ae238a       |
| rancher/mirrored-pause                                   | 3.2                   |
| rancher/nginx-ingress-controller                         | nginx-1.1.0-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1         |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.3.6                |
| rancher/mirrored-coredns-coredns                         | 1.7.0                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.1                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.15.13               |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | --------------------------------- |
| Calico        | calicov3165                       |
| Canal         | canalv3165                        |
| Flannel       | flannelv116                       |
| CoreDNS       | coreDnsv117                       |
| KubeDNS       | kubeDnsv116                       |
| MetricsServer | metricsServerv18                  |
| Weave         | weavev116                         |
| Aci           | aciv500                           |
| NginxIngress  | nginxIngressv110Rancher4                |
| Nodelocal     | nodelocalv115                     |

</details>

**Comment by snasovich** [comment]
KDM PR merged, ready to test.

**Comment by snasovich** [comment]
JFYI there was no 1.20.16 upstream release, so we're reverting it now back per https://github.com/rancher/rancher/issues/36825

**Comment by vivek-infracloud** [comment]
**Fresh install checks - on 2.6.4-rc8, KDM pointing to dev-v2.6 - Pass**

- Deployed clusters with k8s version v1.23.4-rancher1-1, v1.22.7-rancher1-1 and v1.21.10-rancher1-1 on all network providers - weave/flannel/calico/canal
- Validations of Network checks on all clusters looks good
- Validation tests on Canal clusters looks good

**Minimum rancher version checks**

- On Rancher v2.6.0 
  - KDM pointing to dev-v2.6, cluster creation succeeds for k8s version v1.21.10-rancher1-1 with all network provider.
  - Made sure the k8s version v1.22 and v1.23  are NOT available
  - Ran network related checks

- On Rancher v2.6.3  
  - KDM pointing to dev-v2.6, cluster creation succeeds for both k8s version v1.21.10 and v1.22.7 with all network provider.
  - Ran network related checks

**RKE checks using v1.3.8-rc6 passed for k8s** `v1.23.4-rancher1-1, v1.22.7-rancher1-1 and v1.21.10-rancher1-1`

**Verified on dev-v2.6 and RKEDefaultK8sVersions is pointing to v1.23.4-rancher1-1**
```
},
 "RKEDefaultK8sVersions": {
  "0.3": "v1.16.3-rancher1-1",
  "default": "v1.23.4-rancher1-1"
}
```

**Comment by rishabhmsra** [comment]
**Verified on rancher v2.6.4-rc8**

**Upgrade checks :**
- On rancher v2.6.3, KDM pointing to release-v2.6, cluster creation succeeds for `v1.21.9-rancher1-1` and `v1.22.6-rancher1-1` with all network provider.
- Provisioned an additional v1.22.6-rancher1-1 cluster with all network provider.
- Pre-upgrade checks look good.
- Upgraded rancher from v2.6.3 to v2.6.4-rc8 successfully.
- Post-upgrade checks look good.
- Upgraded k8s version to `1.21.10-rancher1-1` and `1.22.7-rancher1-1`. Also for additionally provisioned `v1.22.6-rancher1-1` cluster, upgraded it to `v1.23.4-rancher1-1`.
- Post upgrade checks look good.

**Will validate the `v1.20.15-rancher1-2` k8s cluster, once the changes are done for it.**

**Comment by rishabhmsra** [comment]
**Fresh install checks :** 
- On rancher `v2.6.4-rc12`, provisioned k8s `v1.20.15-rancher1-2` clusters on all network providers - weave/flannel/calico/canal
- On rancher `v2.6.4-rc11`, provisioned k8s `v1.19.16-rancher1-4` clusters on all network providers - weave/flannel/calico/canal
- Validations of Network checks on all clusters looks good
- Validation tests on Canal clusters looks good

**RKE checks using `v1.3.8-rc11` passed for k8s cluster `v1.20.15-rancher1-2` and `v1.19.16-rancher1-4`**


**For upgrade checks** `Edit Config` options are not editable hence cannot upgrade the k8s versions. Blocked by https://github.com/rancher/dashboard/issues/5455

**Comment by rishabhmsra** [comment]
Edit Config issue is resolved : https://github.com/rancher/dashboard/issues/5455#issuecomment-1077519795
**Upgrade checks for `v1.20.15-rancher1-2` and `v1.19.16-rancher1-4` on rancher v2.6-head(b7c9b89) :** 
- On rancher v2.6.3, KDM pointing to release-v2.6, cluster creation succeeds for `v1.20.15-rancher1-1` and `v1.19.16-rancher1-3` with all network providers.
- Pre-upgrade checks look good.
- Upgraded rancher from v2.6.3 to v2.6-head(b7c9b89) successfully.
- Post-upgrade checks look good.
- Upgraded k8s versions to 1.20.15-rancher1-2 and 1.19.16-rancher1-4.
- Post upgrade checks look good.

**Verified on dev-v2.6 and RKEDefaultK8sVersions is pointing to v1.22.7-rancher1-1**
```
 "RKEDefaultK8sVersions": {
  "0.3": "v1.16.3-rancher1-1",
  "default": "v1.22.7-rancher1-1"
 }
```
All the KDM checks passed, hence closing the issue.
