### ISSUE TITLE
[rke2] updating an incorrect image name for a workload deploys a new pod instead of removing the old one. Removing the old pod manually fails, until the pod with the correct image goes to an active state

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36430]
**Rancher Server Setup**
- Rancher version:v2.6.4-rc1
- Installation option (Docker install/Helm Chart):helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):rke1, 1.21.9
- Proxy/Cert Details:valid certs

**Information about the Cluster**
- Kubernetes version: 1.22.6+rke2r1
- Cluster Type (Local/Downstream):Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):custom, with windows workers (version 2022)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom):admin

   
**Describe the bug**

updating an incorrect image name for a workload deploys a new pod instead of removing the old one. Removing the old pod manually fails, until the pod with the correct image goes to an active state.

**To Reproduce**
 
* deploy a workload with an incorrect image name. i.e. `docker pull ranchertest/mytestcontainer`
* note that the deployment goes to a new error state
* fix the image name
* try to remove the old pod manually

**Result**
* old pod with bad image is unable to remove until the new pod successfully deploys.  

**Expected Result**
* expecting the old pod to remove immediately.

**Additional context**
this is more prevalent in a workload with a large image, i.e. windows images. 

https://user-images.githubusercontent.com/16691014/152889740-e0ff6582-dad0-42bc-9604-6905da700449.mov

**Comment by jakefhyde** [comment]
I think this is the intended behavior, I think it has to do with the minimum availability, I don't think the old pod will be removed until either the new one succeeds, or the deployment is scaled down to 0.

**Comment by slickwarren** [comment]
ok, thanks Jake. Closing this as intended behavior
