### ISSUE TITLE
vSphere CSI Controller does not work in recent chart version 

### ISSUE THREAD

**Issue by fabiorauber** [rancher/rancher#36447]
**Rancher Server Setup**
- Rancher version: v2.5.9
- Installation option: Helm Chart RKE1, Kubernetes version 1.20.6

**Information about the Cluster**
- Kubernetes version: 1.20.11
- Cluster Type: on-premises vSphere cluster created by Rancher (RKE1)

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
After installing vSphere CSI driver using the provided Helm Chart (rancher-vsphere-csi:2.3.1), vsphere-csi-controller fails to provision a volume.

**To Reproduce**
 - Install a vSphere Kubernetes cluster using Rancher v2.5.9, configured to use an external cloud provider. 
 - Install vsphere out-of-tree cloud provider (Helm chart rancher-vsphere-cpi:1.0.100)
 - Install rancher-vsphere-csi:2.3.1 using the form provided with the Rancher chart
 - Create a PVC that uses the default storage class `vsphere-sci-sc`.

**Result**
vsphere-csi-controller fails to provision volumes, displaying an error message in the logs: 
``` User \"system:serviceaccount:kube-system:vsphere-csi-controller\" cannot get resource \"cnsvolumeoperationrequests\" in API group \"cns.vmware.com\" in the namespace \"vmware-system-csi\" ```

**Expected Result**
vsphere-csi-controller should have provisioned the volume successfully.

**Additional context**
It seems like VMWare changed the default vsphere-csi namespace from `kube-system` to `vmware-system-csi` and the rancher chart was not updated. See https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/615. There isn't even the possibility to customize the namespace using the chart form.

**Comment by johnlaur** [comment]
What a nightmare this day has been; 2.5-release versions of both rancher-vsphere-cpi and rancher-vsphere-csi charts are completely jacked right out of the box with broken tolerations and hosts of other problems; previous versions of working charts are not available due to how the chart repo is maintained. How are customers using this?

The below roles are present in kubernetes-sigs/vsphere-csi-driver/master/manifests/vanilla/vsphere-csi-driver.yaml but they do not exist in the rancher-vsphere-csi chart. Adding the below to rancher-vsphere-csi/2.3.1/templates/controller/role.yaml and forcing the chart to install in vmware-system-csi namespace does enable these PVCs to succeed.

```
  - apiGroups: ["cns.vmware.com"]
    resources: ["cnsvolumeoperationrequests"]
    verbs: ["create", "get", "list", "update", "delete"]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshots" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshotclasses" ]
    verbs: [ "watch", "get", "list" ]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshotcontents" ]
    verbs: [ "create", "get", "list", "watch", "update", "delete", "patch"]
  - apiGroups: [ "snapshot.storage.k8s.io" ]
    resources: [ "volumesnapshotcontents/status" ]
    verbs: [ "update", "patch" ]
  - apiGroups: [ "cns.vmware.com" ]
    resources: [ "csinodetopologies" ]
    verbs: ["get", "update", "watch", "list"]
```

**Comment by fabiorauber** [comment]
I confirm @johnlaur's solution works as expected.

**Comment by walkafwalka** [comment]
This should be solved by https://github.com/rancher/charts/pull/1763.
