### ISSUE TITLE
CPU, Memory and Number of Pod not being displayed on Home page for AKS imported clusters (1.22.4)

### ISSUE THREAD

**Issue by tgdfool2** [rancher/rancher#36449]
**Rancher Server Setup**
- Rancher version: v2.6.4-rc2
- Installation option (Docker install/Helm Chart): Helm Chart on AKS 1.22.4

**Information about the Cluster**
- Kubernetes version: AKS 1.22.4, imported

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
On the home page, the CPU, Memory and Pods usage remains to 0 for imported AKS cluster. The only cluster where the information is properly displayed is the one hosting rancher (see screenshot below for details).

**To Reproduce**
* Setup a fresh Rancher v2.6.4-rc2 instance
* Import AKS 1.22.4 clusters

**Result**

**Expected Result**
Proper CPU, Memory and Pods usage would be displayed on the home page.

**Screenshots**
![image](https://user-images.githubusercontent.com/66017789/153067206-fe57bb18-b71b-42d6-8a51-b6f035ffca75.png)
![image](https://user-images.githubusercontent.com/66017789/153067325-fde95f8b-081c-4504-b780-f4d1e90b1435.png)

**Additional context**
Using v2.6.4-rc2, as it is currently the only version supporting Kubernetes 1.22+.

**Comment by silentdark** [comment]
It's not just AKS that have this issus #35986

**Comment by siegenthalerroger** [comment]
I have a similar issue, except it's not reporting 0% but a way to small percentage. Totals are correct though.

**Comment by tgdfool2** [comment]
FYI, had a quick look at our Rancher Dashboard again and the values on the home page are not 0 anymore, but wrong values (too low):
![image](https://user-images.githubusercontent.com/66017789/156741324-e8a147aa-dd29-4028-bc61-066555203920.png)

Actual "real" value for the first cluster:
![image](https://user-images.githubusercontent.com/66017789/156741388-467f6302-a80a-4dc7-89ef-d044dfcac3a9.png)
