### ISSUE TITLE
How to use Cluster Manager in Rancher 2.6.x

### ISSUE THREAD

**Issue by SukiKim** [rancher/rancher#36441]
Hi, I am a good user of Rancher.
I was using Rancher 2.4.3, but this time I am going to update the version to 2.6.3.
Previously, when using 2.4.3, Cluster Manager was used, and I modified the UI and used it.
But from this version 2.6.x, I saw a document saying that Cluster Explorer is used.
Is there any way to use Cluster Manager in 2.6.x?
It does not change no matter how much you modify it in UI Source Code.
No matter how much you modify it, if you enter the domain address, it continues to move to the /dashboard/* parameter.

In the past, when using 2.4.3, the Rancher Image was built by modifying the UI.

please tell me how

**Comment by SukiKim** [comment]
Hi
I found the answer myself.
When building a Docker image, the source code of rancher/rancher was modified.

Line 55 of pkg/ui/route.go
/dashboard => /login changed.

Is there a way to edit it in Rancher UI other than the above method?
thanks

**Comment by mohag** [comment]
See [this](https://github.com/rancher/rancher/releases/tag/v2.6.0)

Because the Cluster Manager and Cluster Explorer from Rancher v2.5 have been consolidated into a unified experience, those terms have been replaced in these release notes with "the global view" and "the cluster detail page."
