### ISSUE TITLE
Namespaces created by rancher can't be deleted

### ISSUE THREAD

**Issue by NeckBeardPrince** [rancher/rancher#36450]
This is to reopen an issue that was not resolved in https://github.com/rancher/rancher/issues/14715.

I ended up having to delete a GKE cluster completely because every namespace, including `default` and `kube-system` had a finalizer on it. Also, every resource had `helm.sh/resource-policy: keep` added to it. Even after going through every resource and removing the finalizers and the `helm.sh/resource-policy: keep` annotation, the namespaces would never delete. Had to be done to the other GKE clusters I imported into Rancher.

**Comment by NeckBeardPrince** [comment]
BUMP

**Comment by chfrank-cgn** [comment]
After registering a cluster with Rancher, it's impossible to remove the cluster from Rancher and delete the cattle-system namespace without manual intervention since it has a finalizer:

```
  finalizers:
    - controller.cattle.io/namespace-auth
```

There should be a documented procedure to unregister clusters from Rancher.

**Comment by NeckBeardPrince** [comment]
> After registering a cluster with Rancher, it's impossible to remove the cluster from Rancher and delete the cattle-system namespace without manual intervention since it has a finalizer:
> 
> ```
>   finalizers:
>     - controller.cattle.io/namespace-auth
> ```
> 
> There should be a documented procedure to unregister clusters from Rancher.

It's unbelievable that this issue has received **ZERO** attention from anyone with Rancher.

**Comment by chfrank-cgn** [comment]
The manual procedure to remove Rancher from nodes is in the documentation [here](https://rancher.com/docs/rancher/v2.6/en/cluster-admin/cleaning-cluster-nodes/); however, that won't help automation from Terraform, for example.

**Comment by rayandas** [comment]
I faced the same. Installed Rancher using Helm on EKS and had to remove it later but there are other things on the cluster so I just can't remove the cluster. After helm uninstall command it removed Rancher for me but the namespace cattle-system is still stuck at terminating state. 
Reopening this issue.

**Comment by rayandas** [comment]
To remove the namespaces which are in pending state, I followed https://computingforgeeks.com/how-to-force-delete-a-kubernetes-namespace/. 
Also there's a tool to remove all the resources created by Rancher. Feel free to try this out. https://github.com/rancher/rancher-cleanup
Closing the issue.

**Comment by reisman234** [comment]
In my case, I had multiple namespaces to which are stuck in termination state because of 
```
  finalizers:
    - controller.cattle.io/namespace-auth
```

To remove all in one command, I used: 
```
kubectl get namespaces --field-selector status.phase=Terminating -o name | xargs -i  kubectl patch {}  -p '{"metadata":{"finalizers":[]}}' --type merge
```

**Comment by valkiriaaquatica** [comment]
> kubectl get namespaces --field-selector status.phase=Terminating -o name | xargs -i  kubectl patch {}  -p '{"metadata":{"finalizers":[]}}' --type merge

Just to add, maybe you need before to delete this resource (at list in my case): 
`kubectl delete validatingwebhookconfiguration rancher.cattle.io`
