### ISSUE TITLE
[BUG][Identity Providers] Keycloak OIDC does not work with a ForgeRock-based Identity Provider

### ISSUE THREAD

**Issue by belgaied2** [rancher/rancher#36451]
**Rancher Server Setup**
- Rancher version: v2.6.3

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
Trying to connect Rancher through Keycloak OIDC to a ForgeRock backend is failing. Further

**To Reproduce**
Users & Authentication -> Auth Provider  -> Keycloak OIDC -> Use a ForgeRock Provider as backend -> Save

**Result**
Transaction with ForgeRock results in Failure

**Expected Result**
Transaction with ForgeRock succeeds.

**Additional context**
This issue seems to be caused by a malformed response from ForgeRock that might be related to the existence of a scope parameter, like what is happening [here with GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/207516).

**Comment by belgaied2** [comment]
This is still relevant. It would be great to support standard OIDC which IS compatible with ForgeRock.
This might become a recommendation for multi-forest AD configurations for example, that is not supported by Rancher.

**Comment by luthermonson** [comment]
Talked this over in office hours, it's possible that forgerock needs additional scope headers and this is an easy fix if we copy/pasta the keycloak provider and figure out what extra headers are needed.

**Comment by belgaied2** [comment]
What's happening for this issue ?

**Comment by brooksphilip** [comment]
Any movement here?

**Comment by brooksphilip** [comment]
Can we keep this open?
