### ISSUE TITLE
Air-gapped provisioning of RKE2 cluster fails when vSphere Cloud Provider (CPI/CSI) enabled in cluster configuration

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#36467]
### Issue description:
When provisioning an RKE2 Node Driver cluster with the vSphere Cloud Provider (i.e. CPI/CSI) configured in the cluster configuration (versus installed via Apps & Marketplace after cluster provisioning) the CPI and CSI charts do not use the configured `system-default-registry`, but attempt to pull from DockerHub. In an air-gapped environment without access to DockerHub the CPI and CSI workloads therefore remain in a CrashLoopBackoff attempting to pull the image, and node provisioning does not complete.

Based on backend investigation, it doesn't really have anything to do with the charts because of being able to edit as YAML, the user is able to set the `global.cattle.systemDefaultRegistry`, which means that it's able to use a private registry. It looks like the UI (or wherever this is configurable) should use it when provisioning. 

There is a workaround (noted below).

### Business impact:
Unable to provision RKE2 cluster with vSphere cloud provider set in cluster configuration if using a private registry in an air-gapped environment.

### Troubleshooting steps:
N/A

### Repro steps:

- Populate a private registry with the Rancher v2.6.0 images (https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/air-gap/populate-private-registry/)
- Install Rancher v2.6.0 on a single node RKE cluster with `--set systemDefaultRegistry` per air-gap installation docs https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/air-gap/install-rancher/ 
- Provision an RKE2 cluster using the vSphere Node Driver, and the private registry config, without setting the vSphere Cloud Provider enabled in the cluster configuration, and observe successful cluster provisioning. After cluster provisioning deploy the vSphere CSI and CPI charts from the Apps & Marketplace and observe chart workloads successfully deployed using private registry images.
- Provision an RKE cluster using the vSphere Node Driver, and the private registry config, and set the vSphere Cloud Provider to enabled in the cluster configuration, passing in configuration under Addons, and observe successful failed provisioning. Download SSH key for node and using kubectl on the node, observe CPI and CSI workloads failing attempting to pull image from DockerHub not private registry

### Workaround:
Is workaround available and implemented? Yes
#### What is the workaround:
Install cluster without configuring vSphere Cloud Provider and install vSphere CPI/CSI charts after cluster provisioning

### Actual behavior:
vSphere CSI/CPI workloads do not use configured `system-default-registry` if configured at cluster provisioning time, preventing successful cluster provisioning in air-gapped environment

### Expected behavior:
vSphere CSI/CPI workloads use configured `system-default-registry` if configured at cluster provisioning time

### Files, logs, traces:
N/A

### Additional notes:
By clicking 'Edit as YAML' on the cluster configuration user could set `global.cattle.systemDefaultRegistry` manually for the `rancher-vsphere-cpi` and `rancher-vsphere-csi` but expectation would be this uses the `system-default-registry` automatically

**Comment by Jono-SUSE-Rancher** [comment]
@MKlimuszka  & @SheilaghM  - Can you guys sync up with @PennyScissors and see if this is something that would fall to Team 3 to handle based on how the vSphere Cloud Provider is enabled? If not, we might need to pass it to Team 2, but I want to confirm first.

**Comment by SheilaghM** [comment]
We made the workaround known to Ansil, but we will need to do something about this.  They appear to be using RKE2, but they're not manually configuring the vSphere charts to point to the airgap resources. In the UI it allows some configuration, but probably not everything an airgap setup needs and RKE2 doesn't collect the variables necessary to pass that info to the UI. 

We've asked for a copy of the chart (or the snippet where the systemdefaultregistry would be set) so we can verify how it is set and whether it is left to default as a sanity check.

**Comment by Martin-Weiss** [comment]
An other workaround might be to use the registries.yaml redirect for images instead of the systemdefaultregistry - see https://docs.rke2.io/install/containerd_registry_configuration/

**Comment by ansilh** [comment]
@codyrancher , The chart is here -> https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-vsphere-cpi/100.1.0%2Bup1.0.100/templates/_helpers.tpl

**Comment by ansilh** [comment]
@codyrancher , The helper template I pasted is coming from this chart -> https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-vsphere-cpi/100.1.0%2Bup1.0.100/templates/_helpers.tpl

**Comment by ansilh** [comment]
Ass per my understanding , who ever is creating `helm-install-xxxx` Pod (in this case ` helm-install-rancher-vsphere-cpi-xxx` & ` helm-install-rancher-vsphere-csi-xxxx`  Pods) that installs the chart should pass `global.cattle.systemDefaultRegistry`

**Comment by ansilh** [comment]
Found a similar commit for rke2 upgarde, and I hope this will give some more idea on how to locate and fix the issue on cloud provider charts.
https://github.com/rancher/rancher/commit/3532d5253c1b1ffd9c7e0080d29a3216c6a05888

**Comment by ansilh** [comment]
Found one more -> https://github.com/rancher/rancher/commit/e4377ca38d3094ea647244d7e7e6f627965c110f

**Comment by janeczku** [comment]
Yeah, this needs to be fixed in the RKE2 vSphere provider Helm chart as described in https://github.com/rancher/rancher/issues/36467#issuecomment-1034809994

**Comment by phillipsj** [comment]
This issue is going to be addressed in RKE2. RKE2 uses a different value for the systemDefaultRegistry than Rancher and Rancher based charts expect `global.cattle.systemDefaultRegistry`. The RKE2 team is going to add support for passing `global.cattle.systemDefaultRegistry`, so RKE2 shipped Rancher charts work correctly. 

Installing the vSphere charts from Apps and Marketplace isn't a tested scenario and isn't recommended. One way to work around this issue would be to set the `global.cattle.systemDefaultRegistry` in the addon-config for both charts. That would need to be done in the YAML.

**Comment by sirredbeard** [comment]
Jamie will dev validate if assigned by QA because he did not work on these issues, based on KDM RC for RKE2.

**Comment by phillipsj** [comment]
A cluster has been created using RKE2 1.22.9-rc4+rke2r1 and Rancher 2.6.5-rc5. The vsphere charts are now picking up the private registry correctly.

![image](https://user-images.githubusercontent.com/1568133/166071886-70fd6174-7ab8-4f48-9137-349a4fdfb89f.png)
