### ISSUE TITLE
Upgrade Helm to v3.8.0

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#36464]
Dependent on https://github.com/rancher/rancher/issues/35739
This will also fix a few transient dependency problems in known security-related issues.

**Comment by cbron** [comment]
We just need to validate that a single chart from apps&marketplace works with new helm, rest will be tested during final testing.

**Comment by cmurphy** [comment]
Validated :heavy_check_mark:

* Installed rancher v2.6-head (`fff9479`) with docker
* On local cluster (1.23), installed apps: CIS Benchmark, Monitoring, Istio, OPA Gatekeeper, all deployed successfully :heavy_check_mark: 
* Created two RKE clusters, 1.21 and 1.23
* Deployed the same apps, all deployed successfully :heavy_check_mark:
