### ISSUE TITLE
rancher/shell setting not applied ? 

### ISSUE THREAD

**Issue by snahelou** [rancher/rancher#36460]
Hi Rancher community,

First of all, thanks for your awesome work! 

Please find a strange behavior below :) 

**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option Helm chart on k8s 1.21
- Proxy/Cert Details: no specific proxy

**Information about the Cluster**
- Kubernetes version: 1.21
- Cluster Type (Local/Downstream): Local and Imported (K3S, GKE, AKS) 

**User Information**
- What is the role of the user logged in? Admin/Cluster 

**Describe the bug**
The aim is to use a custom shell for users through the UI. 
I used the CLI to customize the shell-image parameter: 
`rancher settings set shell-image snahelou22/rch-shell-flux:0.1.14`
( The image is just the rancher shell official image extended with FluxCD cli. ) 

```
$ rancher settings get shell-image
ID            NAME          VALUE                              DEFAULT                 CUSTOMIZED
shell-image   shell-image   snahelou22/rch-shell-flux:0.1.14   rancher/shell:v0.1.14   true
```
Everything is working fine on *Local* cluster 
![image](https://user-images.githubusercontent.com/528345/153206044-775172a0-1c00-489c-b16c-62ae4755e828.png)

```
$ k get pods -n cattle-system -l pod-impersonation.cattle.io/token -o jsonpath='{.items..spec.containers..image}'
snahelou22/rch-shell-flux:0.1.14 snahelou22/rch-shell-flux:0.1.14
```
But not for other clusters. The dashboard-shell pod is still using the default value. 

```
$ k get pods -n cattle-system -l pod-impersonation.cattle.io/token -o jsonpath='{.items..spec.containers..image}'
rancher/shell:v0.1.14 rancher/shell:v0.1.14
```

I tried to restart rancher server pods, cattle-cluster-agent on imported clusters but the setting is still ignored. 

Do you have any idea ? 

BR

**Comment by braunsonm** [comment]
Running into this too, seems related to the issue you linked

**Comment by braunsonm** [comment]
Bump

**Comment by braunsonm** [comment]
Bump
