### ISSUE TITLE
User authentication with Kubeconfig fails on Openshift due to unexpected secret order in cattle-impersonation ServiceAccount

### ISSUE THREAD

**Issue by fritzduchardt** [rancher/rancher#36478]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option: Helm Chart
   - Kubernetes Cluster: RKE 1.2.9, K8s v1.20.6

**Information about the Cluster**
- Kubernetes version: Openshift v4.8.26  K8s v1.21.6
- Cluster Type: Downstream / Imported
   - If downstream, what type of cluster? Imported

**Describe the bug**
User authentication with a K8s client, e.g. kubectl fails with error "unable to create impersonator account: error getting service account token: error getting token: invalid secret object".

**To Reproduce**
Can be reproduced by editing "cattle-impersonation-[user-id]" ServiceAccount in cattle-impersonation-system namespace so that the "dockercfg"-secret appears first in the list of secrets. After the editing, authentication with the corresponding kubeconfig file will fail.

**Result**
User fails to connect to cluster with K8s client, e.g. kubectl

**Expected Result**
User should succeed to connect to cluster

**Additional context**
The error is specific to Openshift, since Openshift adds a pull secret for the internal registry to every K8s ServiceAccount. With the "cattle-impersonation-[user-id]" ServiceAccount, Rancher expects the "token" secret to come first in the secret list and fails if this is not the case.

**Comment by azerbe** [comment]
This is still valid.
