### ISSUE TITLE
Losing connection to Rancher Server UI

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#36474]
**Rancher Server Setup**
- Rancher version: v2.6-head (19f459a)
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, 1.21.8+rke2r1
- Proxy/Cert Details: rancher self-signed

**Information about the Cluster**
- Kubernetes version: 1.21.8+rke2r1
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Standard

   
**Describe the bug**

When deploying rke1 local cluster, after some time of use, I seem to be losing connection to the Rancher Server UI randomly. The issue seemed reproducible based on length of use and not specifically what I was doing on the cluster.

**To Reproduce**
 
Scenario 1:
- Deploy rke1 local HA cluster
- On Rancher, create rke2 k8s v1.21 cluster with AWS node driver
- Upgrade cluster k8s version from v1.21 to v1.22
- Run some other tasks on the server and the connection breaks.

Scenario 2:
- Deploy rke1 local HA cluster
- Log into Rancher to see setup was successful
- Disconnect from your wifi/internet
- Reconnect to your wifi/internet
- Try to log into Rancher

**Result**
Scenario 1 & 2: Rancher Server UI is not reachable and gives a timeout error in the browser.

**Expected Result**

Rancher Server UI is reachable and user is able to log in.

**Screenshots**

**Additional context**

logs will be given separately due to sensitive information

**Comment by jiaqiluo** [comment]
this might  be a misconfiguration, send it back to @timhaneunsoo for testing.

**Comment by timhaneunsoo** [comment]
This issue was due to misconfiguration. there were two config files in the same directory, one containing unrelated information. After deleting the unrelated config file, I am no longer running into this issue. 
Closing this issue as **not reproducible**.
