### ISSUE TITLE
After upgrade of local cluster to 1.22, UI is not reachable though all pods are healthy

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#36471]
**Rancher Server Setup**
- Rancher version: `2.6-head Commit ID b97e3c2`
- Installation option (Docker install/Helm Chart): `HA Deploy Jenkins Job`

**Information about the Cluster**
- Kubernetes version: `1.22`
- Cluster Type (Local/Downstream): `Local cluster upgraded from 1.21 to 1.22`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
`Admin`

   
**Describe the bug**
Created an HA rancher on 2.6-head with jenkins job. After upgrading the local cluster to k8s 1.22, the UI is unreachable. The cluster is up, all pods are good. Can deploy to cluster successfully from CLI. 

**To Reproduce**
1. Create Rancher HA 2.6-head k8s v1.21.9-rancher1-1
2. Created downstream Ec2 clusters
3. Installed v1 and v2 charts for testing and k8s upgrade verification
4. Upgraded local cluster k8s version to 1.22

**Result**
Upgraded successfully. Able to login to cluster after upgrade and verify that the k8s version was upgraded. After ~ 30 minutes, there was a slack message that the UI was unreachable. This morning verified same. Able to verify that the cluster is actually up and running, able to deploy workload from CLI. 

**Expected Result**
UI is reachable and able to login to rancher. 

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/89212856/153462606-7c391e9d-465d-4db2-b246-391dc34f14eb.png)

![api server](https://user-images.githubusercontent.com/89212856/153459841-ae3c7f38-f804-4529-bf08-b777242cc774.jpg)

![server version](https://user-images.githubusercontent.com/89212856/153459873-4e007e78-f822-43e9-a3a0-320e706f8790.jpg)

**Additional context**
Since the cluster was up and returning 200s from command line, debugged by replacing infrastructure (target groups, lb and route53) no improvement.

**Comment by davidnuzik** [comment]
And looking at the rancher pod logs there are just a nearly endless amount of syncing errors like below (snippet)

```
2022/02/10 16:08:02 [ERROR] error syncing 'c-jsbwx/p-prf2v': handler system-image-upgrade-controller: upgrade cluster c-jsbwx system service pipeline failed: upgrade system service cattle-pipeline:registry-proxy failed, Put "https://REDACTED-IP:6443/apis/apps/v1/namespaces/cattle-pipeline/daemonsets/registry-proxy": cluster agent disconnected, requeuing
2022/02/10 16:08:06 [ERROR] error syncing 'c-jsbwx/cluster-scan-alert': handler cluster-alert-group-deployer: clean up alertmanager failed, Delete "https://REDACTED-IP:6443/api/v1/namespaces/cattle-prometheus/secrets/alertmanager-cluster-alerting": cluster agent disconnected, requeuing
2022/02/10 16:08:11 [ERROR] error syncing 'c-jsbwx/scheduler-system-service': handler cluster-alert-rule-deployer: clean up alertmanager failed, Delete "https://REDACTED-IP:6443/api/v1/namespaces/cattle-prometheus/secrets/alertmanager-cluster-alerting": cluster agent disconnected, requeuing
2022/02/10 16:08:11 [ERROR] error syncing 'p-prf2v/projectalert-workload-alert': handler project-alert-group-deployer: clean up alertmanager failed, Delete "https://REDACTED-IP:6443/api/v1/namespaces/cattle-prometheus/secrets/alertmanager-cluster-alerting": cluster agent disconnected, requeuing
2022/02/10 16:08:12 [ERROR] error syncing 'c-jsbwx/cluster-scan-manual-failure-only': handler cluster-alert-rule-deployer: clean up alertmanager failed, Delete "https://REDACTED-IP:6443/api/v1/namespaces/cattle-prometheus/secrets/alertmanager-cluster-alerting": cluster agent disconnected, requeuing
2022/02/10 16:08:22 [ERROR] error syncing 'c-jsbwx/deployment-event-alert': handler cluster-alert-rule-deployer: clean up alertmanager failed, Delete "https://REDACTED-IP:6443/api/v1/namespaces/cattle-prometheus/secrets/alertmanager-cluster-alerting": cluster agent disconnected, requeuing
2022/02/10 16:08:37 [ERROR] error syncing 'c-jsbwx/high-number-of-leader-changes': handler cluster-alert-rule-deployer: clean up alertmanager failed, Delete "https://REDACTED-IP:6443/api/v1/namespaces/cattle-prometheus/secrets/alertmanager-cluster-alerting": cluster agent disconnected, requeuing
2022/02/10 16:08:38 [ERROR] error syncing 'p-prf2v/memory-close-to-resource-limited': handler project-alert-rule-deployer: clean up alertmanager failed, Delete "https://REDACTED-IP:6443/api/v1/namespaces/cattle-prometheus/secrets/alertmanager-cluster-alerting": cluster agent disconnected, requeuing
2022/02/10 16:08:41 [ERROR] error syncing 'p-prf2v/less-than-half-workload-available': handler project-alert-rule-deployer: clean up alertmanager failed, Delete "https://REDACTED-IP:6443/api/v1/namespaces/cattle-prometheus/secrets/alertmanager-cluster-alerting": cluster agent disconnected, requeuing
W0210 16:08:45.483964      32 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
2022/02/10 16:08:46 [ERROR] error syncing 'c-jsbwx/etcd-system-service': handler cluster-alert-rule-deployer: clean up alertmanager failed, Delete "https://REDACTED-IP:6443/api/v1/namespaces/cattle-prometheus/secrets/alertmanager-cluster-alerting": cluster agent disconnected, requeuing
2022/02/10 16:08:49 [ERROR] error syncing 'c-jsbwx/cluster-scan-scheduled--failure-only': handler cluster-alert-rule-deployer: clean up alertmanager failed, Delete "https://REDACTED-IP:6443/api/v1/namespaces/cattle-prometheus/secrets/alertmanager-cluster-alerting": cluster agent disconnected, requeuing
```

**Comment by harridu** [comment]
metoo

**Comment by harridu** [comment]
BTW, https://github.com/rancher/rke/releases lists "v1.22.6-rancher1-1" under "experimental". I didn't ask for the experimental version. Using it by default for a release version is hardly acceptable.

**Comment by paynejacob** [comment]
@ronhorton how much ram was on these nodes.  When you say you installed a v1 and v2 chart was it monitoring?

**Comment by ronhorton** [comment]
The upgrade succeeded, but takes 3 minutes to load local cluster when clicking `explore`
`v2.6-head Commit ID 3f30288`


![Screen Shot 2022-02-23 at 10 14 11 AM](https://user-images.githubusercontent.com/89212856/155348680-73dae63e-324f-4daa-9965-95476ff8d903.png)

**Comment by sowmyav27** [comment]
Can be tested with `2.6.4-rc9`

**Comment by ronhorton** [comment]
**Pass** verified in `v2.6.4-rc10` with rke `1.3.8-rc8`

1. created ha rancher with k8s 1.21
2. installed downstream cluster
3. installed apps on downstream
4. upgraded rancher to 1.22

`pods restarted; k8s version upgraded successfully. ui functions as expected. did not lose connectivity between UI and backend`
