### ISSUE TITLE
Strange green circle on Storage Pool page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3647]
Version: master 2/18

Steps: 
1.  Launch and wait for GlusterFS catalog to fully start
2.  Launch and wait for Convoy GlusterFS catalog to fully start
3.  Create a service (Add a Volume name and set Volume Driver to convoy-gluster)
4.  Go to Storage Pool page (refresh as sometimes the volumes don't show up - this is already entered separately) 

Results:  Strange green circle showing up at top of page?
![image](https://cloud.githubusercontent.com/assets/11514927/13157433/1dc43824-d645-11e5-8ad3-a0841246e464.png)

Expected:  No green circle?

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/481

**Comment by tfiduccia** [comment]
Version - master UI 0.91.0
Verified fixed
