### ISSUE TITLE
See #11496: Upstream Kubernetes Deprecation: Controller Manager & Scheduler show as Unhealthy if HTTP port is disabled.

### ISSUE THREAD

**Issue by mohag** [rancher/rancher#36486]
**Rancher Server Setup**
- Rancher version: 2.5.12
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: haproxy, cert-manager (Let's Encrypt)

**Information about the Cluster**
- Kubernetes version: v1.19.15, v1.19.14, v1.19.16, v1.21.9, v1.19.9, v1.19.7
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster?: Imported, kubeadm created

**User Information**
- What is the role of the user logged in? Global Admin
   
**Describe the bug**
Scheduler and controller manager shows as unhealthy even if they are healthy if the HTTP port is disabled (default since [kubeadm v1.16.13](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#bug-or-regression-2)), since Rancher is relying on the output of the deprecated ([since v1.19](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#deprecation)) component-statuses for the health state, which does not check the HTTPS port.

**To Reproduce**
* Deploy a kubeadm cluster
* Import it into Rancher

**Result**
On the Cluster dashboard, controller manager and scheduler's status shows as unhealthy.

**Expected Result**
On the Cluster dashboard, controller manager and scheduler's status should show as Healthy or N/A.

**Screenshots**
![image](https://user-images.githubusercontent.com/1136567/153638874-0b676183-d92c-4064-9f83-24e1dbb427c0.png)

**Additional context**
This is part of the #11496 issues (which was initially opened for AKS, but bugs for other systems was merged in as well, but that was closed after only the AKS case was fixed)

It also seems to [affect MiniKube](https://github.com/rancher/rancher/issues/11496#issuecomment-841670069)

Bug that this is a duplicate of: (It seems like [AKS, LKE and Tencent was fixed](https://github.com/rancher/rancher/pull/32872/files#diff-0d8651619f368728e4220002566db1880dac89d0ab86ad91f69143a7544d36feR30))
#11496
#13311
#22137
#27259
#28023

[First mentioned here](https://github.com/rancher/rancher/issues/11496#issuecomment-990037768)

**Comment by mohag** [comment]
Still present, apparently we need more "+1" comments to keep the bot from closing it.

**Comment by deadpyxel** [comment]
Have been facing a similar issue on rancher 2.6.4, with my kubeadm downstream clusters.

**Comment by Privatecoder** [comment]
+1

**Comment by EC-Sean** [comment]
+1

**Comment by mohag** [comment]
2.6 still does the same, on a slightly different UI

**Comment by mohag** [comment]
Still there

**Comment by mohag** [comment]
pandering to the bot overlords....

**Comment by mohag** [comment]
Reminding bots that ignoring problems does not make them go away

**Comment by mohag** [comment]
Reminding bots that ignoring problems does not make them go away

Still present in 2.6.11

+1 comments help - reactions don't help to keep the bug open (if the repo don't want those, they should not use bots that close issues)

**Comment by mohag** [comment]
.

**Comment by mohag** [comment]
.

**Comment by deadpyxel** [comment]
I am not sure at this point if there's anything that can start to fix this. There was this comment previously, but is this still a thing in newer versions? My org is going to upgrade to the latest version and we may be able to verify that in some weeks.

> > Do we have any clues in how to work on this yet? I saw many mentions of the issue but it seems to be always present.
> 
> The statuses are based on a deprecated Kubernetes API.... (which only supports HTTP checks on localhost, which fails if the HTTP port is disabled)
> 
> Getting rid of the status indication is one option (i.e. with a configuration setting), the other is to allow configuration of monitoring of the health checks for pods matching certain labels (at least for kubeadm-deployed clusters - some deployment methods run those outside the cluster)...

**Comment by mohag** [comment]
> I am not sure at this point if there's anything that can start to fix this. There was this comment previously, but is this still a thing in newer versions? My org is going to upgrade to the latest version and we may be able to verify that in some weeks.

It might actually be better on 2.6.11 with at least some kubeadm versions. (A in-need of upgrade 1.22 cluster shows green) (Some clusters have relatively recently shown the errors on this UI)
![image](https://github.com/rancher/rancher/assets/1136567/d7e0e130-33a2-49f3-a988-3a08d8043bfd)

The 1.21 clusters (yes, they also need to be upgraded) shows this on 2.6.11:
![image](https://github.com/rancher/rancher/assets/1136567/3e6fda1e-0c90-4495-9214-b116ec61029f)

Old UI (Under /g/ on Rancher 2.6.11)
![image](https://github.com/rancher/rancher/assets/1136567/d8d6bce6-6b3f-4dbb-869a-daf80d37b7f6)

I need to try 2.7. It does seem as if currently supported Kubernetes versions might be working fine.... (I mainly have EKS clusters on the modern version, I need to get some kubeadm-based 1.27 clusters to check)

**Comment by deadpyxel** [comment]
Our clusters are kubeadm based, we are currently on the following versions:

- Rancher 2.6.9
- Kubernetes (both rancher cluster and its managed clusters) v1.24.6

I just checked and in our case, at lest now the checks look ok, but I'll have to check with another team that is running the same setup, and has a the unhealthy status showing.

**Comment by deadpyxel** [comment]
Our Bot overlords strike again. I'll be upgrading Rancher to latest version this week to see if the problem still persists.

**Comment by mohag** [comment]
It seems like Kubernetes 1.22 or newer no longer has this issue. (Rancher probably uses another method there)
