### ISSUE TITLE
[v2prov] KDM-powered feature gates

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#36481]
**Is your feature request related to a problem? Please describe.**
As RKE2/K3s are independent projects with independent changes, there can be cases where functionality changes within a minor version of the downstream projects which can break/require changes in provisioning behavior. In order to not break backwards compatibility, these newer features should be gated through version validation (through KDM metadata) to prevent unnecessary regressions from users upgrading versions of Rancher.

**Describe the solution you'd like**
A KDM powered feature gate system for K3s/RKE2 which gates new features from being run.

**Describe alternatives you've considered**
I can't think of anything else that is easier

**Additional context**

**Comment by sowmyav27** [comment]
@Sahota1225 can we please add the template with info for QA to validate?

**Comment by snasovich** [comment]
While the changes are done for 2.6.4 release, they are currently not in use so there is nothing testable for this yet.
To save effort for 2.6.4 testing, moving this issue to 2.6.5. It also makes sense to dev validate this one.

**Comment by Sahota1225** [comment]
@Oats87 to provide a template to QA team and waiting for K3sRKE2 version.

**Comment by snasovich** [comment]
@Oats87 , I'm assuming we still don't actually use this feature so it cannot be tested? Moving to 2.6.6 meanwhile.

**Comment by snasovich** [comment]
We should be able to start using it to enable https://github.com/rancher/rancher/issues/35436. Moving to Blocked until that work is done at which point we can test feature gates using encryption key rotation.

**Comment by jakefhyde** [comment]
Validation: PASSED

Steps to test:

1. Provision a `v1.23.8+rke2r1` cluster
    - this version has the `encryption-key-rotation: 2.0.0` feature gate value
2. Attempt to rotate encryption keys
3. Encryption key rotation succeeds because the feature gate has the major version `2`.
4. Provision a `v1.23.7+rke2r1` cluster
    - this version does not have the `encryption-key-rotation: 2.0.0` feature gate value
5. Attempt to rotate encryption keys
6. Encryption key rotation fails, with the following logs:
```
2022/07/11 16:04:40 [DEBUG] rkecluster fleet-default/jhyde-rke2-capi-debug-test: determining if election of init node is necessary
2022/07/11 16:04:40 [DEBUG] rkecluster fleet-default/jhyde-rke2-capi-debug-test searching for init node
2022/07/11 16:04:40 [DEBUG] rkecluster fleet-default/jhyde-rke2-capi-debug-test found current init node jhyde-rke2-capi-debug-test-all-658749755b-2svrz with joinURL: https://<JOIN_URL>
2022/07/11 16:04:40 [DEBUG] rkecluster fleet-default/jhyde-rke2-capi-debug-test: init node was already elected and found with joinURL: https://<JOIN_URL>
2022/07/11 16:04:40 [DEBUG] rkecluster fleet-default/jhyde-rke2-capi-debug-test: marking encryption key rotation phase as failed as it was not supported by version: v1.23.7+rke2r1
```
