### ISSUE TITLE
Rancher UI RKE2 Vsphere Machine Pools form not updating based on Data Center selection

### ISSUE THREAD

**Issue by mgarren** [rancher/rancher#36489]
The Machine pools form in Rancher under vmware/RKE2 does not update properly when you have a vcenter with multiple datacenters.  The options for Resource Pool, DataStore, and Folder all stay locked to whatever the first item in the Datacenter list was and don't update accordingly.

To reproduce: 
---
Cluster Management->Clusters->Create

Choose "Vmware Vsphere", ensuring the slider is set to RKE2/k3s

Choose a credential

Under "pool1" Machine pool, observe all options related to the first item in the datastore list, select a different one, observe that no options change or are updated based on datacenter selection.

----

Rancher install is running on docker using rancher/rancher:latest with sha256:f411ee37efa38d7891c11ecdd5c60ca73eb03dcd32296678af808f6b4ecccfff

**Comment by mkretzer** [comment]
Same issue here!
