### ISSUE TITLE
RKE1 etcd snapshot failure retention

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#36492]
**Rancher Server Setup**
- Rancher version: v2.6-head
 
 **Information about the Cluster**
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE1
   
**Describe the bug**

RKE1 etcd snapshot config specifies a `retention`, which is the maximum number of snapshots retained until rancher starts to delete older snapshots. Currently, there is no check ensuring that rancher is retaining at least `retention` successful snapshots, creating the possibility that rancher has no successful snapshots. Failed snapshots should be retained separately from successful snapshots, so that the user doesn't end up in a situation where the only snapshots are failed ones.

**To Reproduce**
 
- Provision a cluster with a retention of 2 and a snapshot interval of 1 hour.
- Wait for initial etcd snapshot with an s3 endpoint
- Watch as the backup is successful
- Delete the s3 bucket/folder
- Wait for next recurring etcd snapshot
- Snapshot should fail with error status
- Wait for next recurring etcd snapshot
- Watch as last successful snapshot is deleted to make room for failed snapshot

**Result**

The last successful snapshots is deleted, leaving 2 failed snapshots.

**Expected Result**

There are at least `retention` successful snapshots retained (how many failed snapshots should be retained requires discussion)

**Screenshots**

**Additional context**

**Comment by jiaqiluo** [comment]
We should count and keep the successful and failed snapshots separately up to the limit.

**Comment by jakefhyde** [comment]
## Root cause

Previously, failed snapshots were counted towards the total # of recurring backups specified in a cluster's `spec.BackupConfig.Retention`. This meant that for some cluster configurations, it would be possible for backups to start failing (for example, in the event that the s3 credential was no longer authorized), and no usable backups to be available for restore.

## What was fixed, or what changes have occurred

A fix was temporarily put in to retain failed etcd backups indefinitely, separate from what is specified in the `retention` field. Obviously this fix could not be permanent, as it would create significant bloat to etcd after some time, with no way easy for users to delete failed backups. This was fixed by retaining `retention` number of failed recurring backups as well. Failed manual backups are still retained indefinitely, for the same reason that a manually requested backups is more important than a recurring one, and also a less frequent operation.

## Areas or cases that should be tested
- Creating a cluster with a `retention` of 2, and having 2 successful backups and 2 failed backups, should only rotate the failed or successful backups on subsequent recurring backups. (Any # other than 2 can be chosen, however the shortest interval is 1 hour, so the minimal test case would take 6 hours)

## What areas could experience regressions?

- N/A

## Are the repro steps accurate/minimal?

Replace the `rke-tools` image with something that would cause it to fail (`ubuntu:latest` should suffice), by provisioning the node, ssh-ing to the node and doing a `docker pull ubuntu:latest && docker tag ubuntu:latest rancher/rke-tools:v0.1.80` (or whatever version of `rke-tools` rke expects to use for this kubernetes version (this is also doable in KDM, but is more of an involved process, since it requires using a custom KDM, RKE, and rancher). Alternatively, it is possible to SSH to the node and stop the etcd container `docker stop etcd`, but another PR will be created and merged soon to address behavior in rke1 when a snapshot cannot possible be completed on a node (i.e. in the case of etcd not running on one of the nodes in an HA setup), versus a snapshot cannot be completed on any node (a bad rke-tools image), as in the case of the former as long as the snapshot exists on one of the nodes, it can be restored (and will even be restorable from s3), so it should not be failed.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head f4d09c7
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE1

----------

### Testing: ###

Tested this issue with the following steps:
1. Provision a cluster with a retention of 2 and a snapshot interval of 1 hour
2. Wait for initial etcd snapshot with an s3 endpoint
3. Watch as the backup is successful
4. Delete the s3 bucket/folder
5. Wait for next recurring etcd snapshot
6. Snapshot should fail with error status
7. Wait for next recurring etcd snapshot
8. Watch as last successful snapshot is deleted to make room for failed snapshot

**Result** - Pass

The successful snapshot is retained and the failed snapshots are retained past the retention value, which is expected.

![image.png](https://zube.io/files/rancher/c1e992b621de5362e36da16072726da8-image.png)
