### ISSUE TITLE
Long environment names cause drop-down to move out of page range

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3649]
Version: master 2/18

Steps: 
1.  Create an environment with a long name
2.  Click on drop-down and select that environment

Results: The drop-down is now off the page.  
![image](https://cloud.githubusercontent.com/assets/11514927/13160023/51bf8f54-d652-11e5-8f33-e3fecc6124d9.png)

Expected:  Should not move off the page like that.

Comments: This is really easy to recreate because local auth uses the Name of the account to create the default folder.

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/481

**Comment by tfiduccia** [comment]
Version - master UI 0.91.0
Verified fixed
