### ISSUE TITLE
Machine drain errors are not exposed  in the UI during cluster upgrade on an RKE2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36506]
**Rancher Server Setup**
- Rancher version: 2.6head commit id: `11a7451`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.9+rke2r1`
- Cluster Type (Local/Downstream): Linode node driver cluster - 1 etcd, 1 cp and 3 worker nodes. Container network - `[multus-canal]`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard user

**Describe the bug**
No error seen on the UI when cluster upgrade fails.

**To Reproduce:**
- Deploy an RKE2 cluster.
- When the cluster is Active, Edit Config --> Modify the Upgrade strategy to
<img width="1203" alt="Screen Shot 2022-02-13 at 3 16 49 PM" src="https://user-images.githubusercontent.com/26032343/153779639-513f1236-d738-496b-b812-63242164b6b0.png">

- Save changes made.
- Edit cluster config again. Change the k8s version to `v1.22.6+rke2r1` and save changes made.
- The cluster goes into Provisioning state. 
- Worker node is stuck in Cordoned state
- Error in rancher Logs:
```
2022/02/13 23:07:29 [ERROR] error syncing 'fleet-default/sowmya-ec2-1-bootstrap-template-b29nk-machine-plan': handler machine-drain: cannot delete Pods with local storage (use --delete-emptydir-data to override): kube-system/rke2-metrics-server-8574659c85-82sqv, requeuing
```

**Expected Result:**
There should be an error displayed on the UI why the cluster upgrade failed. User must not have to log into the server to see the error.

**Comment by Oats87** [comment]
Given the difference in functionality between RKE1 and RKE2/K3s, it is very difficult to interpolate the exact reason a plan failed when updating. 

I think this is functionality that we can add down the line, otherwise, maybe we just add a "plan has failed to apply N number of times, please check rancher-system-agent.service logs" or something to indicate that the plan is failing

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `024e6fa`**

- Deployed an RKE2 cluster - 3 etcd, 2 cp and 3 worker nodes
- Upgrade strategy is set on the cluster
- Edit cluster --> Upgrade k8s version from 1.22 to 1.23
- Error seen on the cluster -
- `Draining etcd node(s) sowmya-do3-pool1-6c6f5f7f4f-x66td: error draining machine sowmya-do3-pool1-6c6f5f7f4f-x66td: error when evicting pods/"calico-typha-6546b78f-qpg5l" -n "calico-system": global timeout reached: 30s`
- But the state of the cluster is `Provisionining`
- And in another scenari, on the control plane error `Draining control plane node(s) sowmya-test-pool2-56d9c84585-xx5hz: error draining machine sowmya-test-pool2-56d9c84585-xx5hz: cannot delete Pods with local storage (use --delete-emptydir-data to override): cattle-system/system-upgrade-controller-5b6457d644-n8qhx`
<img width="1427" alt="Screen Shot 2022-03-21 at 12 16 58 AM" src="https://user-images.githubusercontent.com/26032343/159177709-a4a4017f-5943-4cae-b9ac-a1e9022987d0.png">

Logging a separate [bug](https://github.com/rancher/rancher/issues/36969) for the status being shown as `Provisioning`. -
