### ISSUE TITLE
Issue with RKE2 upgrade with Upgrade strategy set

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36505]
**Rancher Server Setup**
- Rancher version: 2.6head commit id: `11a7451`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.9+rke2r1`
- Cluster Type (Local/Downstream): Linode node driver cluster - 1 etcd, 1 cp and 3 worker nodes. Container network - `[multus-canal]`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard user
   
**Describe the bug**
Issue with RKE2 upgrade with Upgrade strategy set

**To Reproduce**

- Deploy an RKE2 cluster.
- When the cluster is Active, Edit Config --> Modify the Upgrade strategy to

<img width="1180" alt="Screen Shot 2022-02-13 at 2 49 34 PM" src="https://user-images.githubusercontent.com/26032343/153778785-51f8f5a2-2911-4dab-9eb9-6e12d7c9e041.png">

- Save changes made.
- Edit cluster config again. Change the k8s version to `v1.22.6+rke2r1` and save changes made.
- The cluster goes into Provisioning state. 
- In Cluster explorer --> Nodes page to the cluster details page on Cluster Management, the nodes state do not show `Upgrading` like how it did in Ember UI for RKE1 clusters. Logged a separate bug for this - https://github.com/rancher/dashboard/issues/5110
- Notice the following in Cluster explorer --> Nodes page:
- Etcd node's k8s changes to 1.22 first
- The worker nodes get cordoned state. 
- Then the Control plane node's state changes and the k8s version upgrades to 1.22.6+rke2r1
- The worker node's k8s version changes
- Rancher server logs:
```
2022/02/13 22:21:29 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning bootstrap node(s) sowmya-linode-multus-canal-pool1-7b59f5c454-hkg9z: waiting for probes: etcd
....
2022/02/13 22:22:02 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning control plane node(s) sowmya-linode-multus-canal-pool2-78869f96f5-9mn84: waiting for probes: kube-apiserver
2022/02/13 22:22:02 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning control plane node(s) sowmya-linode-multus-canal-pool2-78869f96f5-9mn84: waiting for probes: kubelet
...
2022/02/13 22:22:17 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning control plane node(s) sowmya-linode-multus-canal-pool2-78869f96f5-9mn84
2022/02/13 22:22:17 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning control plane node(s) sowmya-linode-multus-canal-pool2-78869f96f5-9mn84: waiting for plan to be applied
2022/02/13 22:22:17 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning control plane node(s) sowmya-linode-multus-canal-pool2-78869f96f5-9mn84: waiting for plan to be applied
2022/02/13 22:22:19 [INFO] Handling backend connection request [c-m-xz6l7h6k]
2022/02/13 22:22:21 [ERROR] Failed to handling tunnel request from <>:17674: response 401: failed authentication
2022/02/13 22:22:21 [INFO] Handling backend connection request [stv-cluster-c-m-xz6l7h6k]
2022/02/13 22:22:29 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning control plane node(s) sowmya-linode-multus-canal-pool2-78869f96f5-9mn84: waiting for plan to be applied
2022/02/13 22:22:29 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning worker node(s) sowmya-linode-multus-canal-pool3-7fbfffc47d-26v74,sowmya-linode-multus-canal-pool3-7fbfffc47d-dlvk4,sowmya-linode-multus-canal-pool3-7fbfffc47d-lsvt5
2022/02/13 22:22:30 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning worker node(s) sowmya-linode-multus-canal-pool3-7fbfffc47d-26v74,sowmya-linode-multus-canal-pool3-7fbfffc47d-dlvk4,sowmya-linode-multus-canal-pool3-7fbfffc47d-lsvt5
2022/02/13 22:22:30 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning worker node(s) sowmya-linode-multus-canal-pool3-7fbfffc47d-26v74,sowmya-linode-multus-canal-pool3-7fbfffc47d-dlvk4,sowmya-linode-multus-canal-pool3-7fbfffc47d-lsvt5
2022/02/13 22:22:30 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning worker node(s) sowmya-linode-multus-canal-pool3-7fbfffc47d-26v74,sowmya-linode-multus-canal-pool3-7fbfffc47d-dlvk4,sowmya-linode-multus-canal-pool3-7fbfffc47d-lsvt5
2022/02/13 22:22:30 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning control plane node(s) sowmya-linode-multus-canal-pool2-78869f96f5-9mn84: waiting for probes: kubelet
2022/02/13 22:22:30 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning control plane node(s) sowmya-linode-multus-canal-pool2-78869f96f5-9mn84: waiting for probes: kubelet
WARNING: ignoring DaemonSet-managed Pods: kube-system/kube-multus-ds-tr9nf, kube-system/rke2-canal-s4f94, kube-system/rke2-ingress-nginx-controller-rjbsg, mystep1-ns1/mystep1-testingresswl1-nqklf, mystep1-ns1/mystep1-testsd1-blbnx
evicting pod mystep1-ns1/mystep1-testwl2withsec-66d7c545f8-x8vl7
evicting pod kube-system/helm-install-rke2-ingress-nginx-nzfft
evicting pod kube-system/helm-install-rke2-metrics-server-xxm22
evicting pod mystep1-ns1/mystep1-testsdclient-7d658c4f4b-9r585
evicting pod mystep1-ns1/mystep1-testwl-6454b5bc75-2wrgf
2022/02/13 22:22:42 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning control plane node(s) sowmya-linode-multus-canal-pool2-78869f96f5-9mn84: waiting for probes: kubelet
WARNING: ignoring DaemonSet-managed Pods: kube-system/kube-multus-ds-bw8vs, kube-system/rke2-canal-q6nfg, kube-system/rke2-ingress-nginx-controller-s7wqg, mystep1-ns1/mystep1-testingresswl1-gz6b5, mystep1-ns1/mystep1-testsd1-6w7dq
evicting pod mystep1-ns2/mystep1-testsdclient-6858bb9b87-4zpbl
evicting pod mystep1-ns1/mystep1-testsdclient-7d658c4f4b-hn7w7
evicting pod kube-system/helm-install-rke2-ingress-nginx-b2l8b
evicting pod mystep1-ns1/mystep1-testingresswl2-8476c98b88-cc7rn
evicting pod mystep1-ns1/mystep1-testwl-6454b5bc75-4cf6k
evicting pod mystep1-ns1/mystep1-testwl2withsec-66d7c545f8-whzjl
...
2022/02/13 22:23:05 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning worker node(s) sowmya-linode-multus-canal-pool3-7fbfffc47d-26v74,sowmya-linode-multus-canal-pool3-7fbfffc47d-dlvk4,sowmya-linode-multus-canal-pool3-7fbfffc47d-lsvt5
2022/02/13 22:23:05 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning control plane node(s) sowmya-linode-multus-canal-pool2-78869f96f5-9mn84: waiting for probes: kube-apiserver, kube-controller-manager, kube-scheduler
2022/02/13 22:23:05 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning control plane node(s) sowmya-linode-multus-canal-pool2-78869f96f5-9mn84: waiting for probes: kube-apiserver, kube-controller-manager, kube-scheduler
2022/02/13 22:23:05 [INFO] rkecluster fleet-default/sowmya-linode-multus-canal: provisioning control plane node(s) sowmya-linode-multus-canal-pool2-78869f96f5-9mn84: waiting for probes: kube-apiserver, kube-controller-manager, kube-scheduler
```
**Expected Result**
Control plane node should get upgraded first before the worker nodes are cordoned/Upgraded

**Comment by thedadams** [comment]
I am not able to reproduce this on the latest v2.6-head (1d2b7468851553f4b89f8af99d74305af9d1b594). The worker node is cordoned after the control plane is upgraded.

**Comment by sowmyav27** [comment]
**On 2.6head commit id: `4df221`, local cluster's version - `v1.23.3+k3s1`**

**Scenario 1**

- Cluster config - 1 etcd, 1 cp and 3 worker nodes
- Create cluster and set upgrade strategy for worker nodes
- When the cluster has come up Active, edit cluster config, upgrade k8s from 1.21rke2 to 1.22 rrke2 version
- Cluster goes into provisioning state.
- Etcd upgrades fist followed by control plane node and then the worker nodes get upgraded

**Scenario 2**
- Cluster config - 3 etcd, 2 cp and 3 worker nodes
- Create cluster and set upgrade strategy for worker nodes and contol plane nodes
- When the cluster has come up Active, edit cluster config, upgrade k8s from 1.21rke2 to 1.22 rrke2 version
- Cluster goes into provisioning state.
- Etcd nodes upgrade fist followed by control plane nodes 
- The cluster then goes into an error state - Cluster stuck in Provisioning with message: `Failing bootstrap machine(s) sowmya-issue2-pool1-646dd544b8-72qcp: Node condition MemoryPressure is Unknown. Node condition DiskPressure is Unknown. Node condition PIDPressure is Unknown. Node condition Ready is Unknown.,`
- Nodes are in error state. Logged a separate bug for this - https://github.com/rancher/rancher/issues/36777
- The cluster finished upgrading and came back up Active

**Scenario 3**
- Cluster config - 3 etcd, 2 cp and 3 worker nodes
- Create cluster and set upgrade strategy for control plane nodes nodes
- When the cluster has come up Active, edit cluster config, upgrade k8s from 1.21rke2 to 1.22 rrke2 version
- Cluster goes into provisioning state.
- one etcd node gets cordoned. 
- When k8s version of that is upgraded, two of the other etcd nodes go into coordoned state --> this is NOT expected
- Then both the control planes go into Cordoned state at the same time since the upgrade strategy was set to Unavailable control plane nodes: 2
- Logging another bug for this -- https://github.com/rancher/rancher/issues/36776
- Then the worker nodes get upgraded successfully

Reopening this issue.

@thedadams Please confirm if the issues ^^ found are related to the fix for this issue. Also please let me know if there are any other usecases that should be validated

**Comment by thedadams** [comment]
@sowmyav27 Thank you for these thorough checks and explanations! I think this is great.

These two issues you found are unrelated to the fact that worker nodes were being cordoned before the control plane nodes were upgraded. In other words, the two issues you found during your thorough tests are independent of the change related to worker nodes.

Perhaps we can close this issue then and we can work on the two issues you found?

**Comment by sowmyav27** [comment]
Closing this issue since the issues found are unrelated as per [this](https://github.com/rancher/rancher/issues/36505#issuecomment-1060820325)
