### ISSUE TITLE
Cluster state changes to Provisioning when user takes a snapshot on an RKE2 cluster 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36504]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `11a7451`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.9+rke2r1`
- Cluster Type (Local/Downstream): RKE2 do node driver cluster - 1 etcd, 1 cp, 1 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin/Standard user

**Describe the bug**
Cluster state changes to Provisioning when user takes a snapshot on an RKE2 cluster

---

**To Reproduce**

- Deploy an RKE2 cluster
- When the cluster comes up Active, take a snapshot on the cluster
- Cluster state changes to provisioning
- Rancher logs show:
```
2022/02/13 21:53:39 [INFO] rkecluster fleet-default/sowmya-scale-down: provisioning control plane node(s) sowmya-scale-down-pool2-67d5fc557c-bs8rp
2022/02/13 21:53:39 [INFO] rkecluster fleet-default/sowmya-scale-down: provisioning control plane node(s) sowmya-scale-down-pool2-67d5fc557c-bs8rp: waiting for plan to be applied
2022/02/13 21:53:39 [INFO] rkecluster fleet-default/sowmya-scale-down: provisioning control plane node(s) sowmya-scale-down-pool2-67d5fc557c-bs8rp: waiting for plan to be applied
2022/02/13 21:53:39 [INFO] rkecluster fleet-default/sowmya-scale-down: provisioning control plane node(s) sowmya-scale-down-pool2-67d5fc557c-bs8rp: waiting for plan to be applied
2022/02/13 21:53:39 [INFO] rkecluster fleet-default/sowmya-scale-down: provisioning control plane node(s) sowmya-scale-down-pool2-67d5fc557c-bs8rp: waiting for plan to be applied
2022/02/13 21:53:47 [INFO] rkecluster fleet-default/sowmya-scale-down: provisioning control plane node(s) sowmya-scale-down-pool2-67d5fc557c-bs8rp: waiting for plan to be applied
2022/02/13 21:53:47 [INFO] rkecluster fleet-default/sowmya-scale-down: reconciliation complete
2022/02/13 21:53:47 [INFO] rkecluster fleet-default/sowmya-scale-down: reconciliation complete
```
---

**Comment by paynejacob** [comment]
This behavior has likely changed with the #36340.  We need to verify the new behavior and ensure it is what an end user would expect to see.

**Comment by snasovich** [comment]
Adding `release-note` label on it for now as we may want to call out this behavior. Unlikely we will have enough time to fix it (and have it work reliably).

**Comment by snasovich** [comment]
Moving to Blocked until we have a decision on https://github.com/rancher/rancher/issues/36993

**Comment by thedadams** [comment]
This is one of the things that will be different from RKE1 to RKE2.

In RKE1, Rancher is responsible for taking the snapshots.

In RKE2, it is RKE2 that is responsible for taking the snapshot. In this case, Rancher has to deliver another plan to the downstream cluster to tell it to take the snapshot. That is why the cluster status changes.

After some recent changes, the cluster will likely go into an "Updating" status instead, but this is expected.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head b8cbc1a
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE node driver cluster

----------

### Testing: ###

Tested this issue with the following steps:
1. Deploy an RKE2 cluster
2. When the cluster comes up Active, take a snapshot on the cluster
3. Cluster state changes to provisioning

**Result** - Pass

As explained in previous comment, the cluster does go into `Updating` state
![image.png](https://zube.io/files/rancher/383555ebbddb2ef5c9b92e253fafcc0d-image.png)
