### ISSUE TITLE
Created default environment for new users is using Name instead of login name

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3650]
Version: master 2/18

Steps: 
1.  Authenticate with local auth
2.  Go to Account and add an account (make sure your Name and Login Name are different)
3.  Logout of current account and log into new account

Results: Notice the created default environment is using Name instead of Login Name.  I swear this used to be LoginName.  Why the change?

Expected: Should not have changed?

**Comment by hibooboo2** [comment]
@tfiduccia This changed in november when we Made the behavior across all auth providers the same. If identity name is blank then we use login otherwise we use their name.

**Comment by tfiduccia** [comment]
Version - master 3/18
Verified fixed

**Comment by fuhbar** [comment]
@tfiduccia @hibooboo2 What is the rationale behind auto creating environments for new users? Why does this happen?

**Comment by deniseschannon** [comment]
@fuhbar This happens when there are no environments that a user has been invited to. When you log into Rancher, we would prefer that a user is in an environment so they could start using Rancher right away.

**Comment by fuhbar** [comment]
@deniseschannon Makes sense. Thanks for clarification.
