### ISSUE TITLE
Snapshots are not created on RKE2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36503]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `11a7451`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.9+rke2r1`
- Cluster Type (Local/Downstream): RKE2 do node driver cluster - 1 etcd, 1 cp, 1 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**
Snapshots are not created on RKE2 cluster

**To Reproduce**

- Deploy an RKE2 cluster
- When the cluster comes up Active, Do a `Snapshot Now` or click on `Take snapshot`
- The cluster state changes to `Provisioning`

**Result**
- Snapshots are not taken/listed on the cluster.
- Rancher Logs:
```
2022/02/13 21:53:39 [INFO] rkecluster fleet-default/sowmya-scale-down: provisioning control plane node(s) sowmya-scale-down-pool2-67d5fc557c-bs8rp
2022/02/13 21:53:39 [INFO] rkecluster fleet-default/sowmya-scale-down: provisioning control plane node(s) sowmya-scale-down-pool2-67d5fc557c-bs8rp: waiting for plan to be applied
2022/02/13 21:53:39 [INFO] rkecluster fleet-default/sowmya-scale-down: provisioning control plane node(s) sowmya-scale-down-pool2-67d5fc557c-bs8rp: waiting for plan to be applied
2022/02/13 21:53:39 [INFO] rkecluster fleet-default/sowmya-scale-down: provisioning control plane node(s) sowmya-scale-down-pool2-67d5fc557c-bs8rp: waiting for plan to be applied
2022/02/13 21:53:39 [INFO] rkecluster fleet-default/sowmya-scale-down: provisioning control plane node(s) sowmya-scale-down-pool2-67d5fc557c-bs8rp: waiting for plan to be applied
2022/02/13 21:53:47 [INFO] rkecluster fleet-default/sowmya-scale-down: provisioning control plane node(s) sowmya-scale-down-pool2-67d5fc557c-bs8rp: waiting for plan to be applied
2022/02/13 21:53:47 [INFO] rkecluster fleet-default/sowmya-scale-down: reconciliation complete
2022/02/13 21:53:47 [INFO] rkecluster fleet-default/sowmya-scale-down: reconciliation complete
```
- No recurring snapshots are taken.

**Expected Result:**
- Snapshot should be taken on the cluster and be listed under `Snapshot` in the cluster. detail page on Cluster Management page.
- Since automation snapshots are enabled, recurring snapshots should be created

**Comment by jiaqiluo** [comment]
This might be resolved by @Oats87's PR in this issue: https://github.com/rancher/rancher/issues/35468

Could QA re-test this issue once the above PR is merged?

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 11a7451
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke2 aws node driver

----------

### Testing: ###

Tested this issue with the following steps:

1. Deploy an RKE2 cluster
2. When the cluster comes up Active, Do a Snapshot Now or click on Take snapshot
3. The cluster state changes to Provisioning

**Result**

The cluster state changes to provisioning and then to active. The log says
[INFO ] provisioning control plane node(s) aws-timhancp-machinedetail,aws-timhancp-machinedetail
[INFO ] provisioning control plane node(s) aws-timhancp-machinedetail: waiting for plan to be applied
[INFO ] provisioning done

When selecting the cluster and going to restore snapshot, there are no snapshots to restore to.
![image.png](https://zube.io/files/rancher/6325aaaebdd0fa5626b1e9fdf8cedee4-image.png)

When going into snapshots page, there are three snapshots, but all 3 are are the same. These seem to be the initial snapshot taken when the cluster was first provisioned. All snapshots taken manually are not listed.
![image.png](https://zube.io/files/rancher/a95f9a8091c28fa9723da9c0077bf2a7-image.png)

@jiaqiluo could you take a look?

**Comment by Oats87** [comment]
This is not going to work until we finish the UI work for the etcd snapshot changes I've made in my PRs

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `4df2214`**

- Deployed an RKE2 DO Node driver cluster - 3 etcd, 2 cp and 3 worker nodes
- When the cluster is active, cluster --> Details --> Snapshot Now.
- Snapshot is taken and is seen in the Snapshot tab under the cluster.
