### ISSUE TITLE
Able to not restart RKE2 servers/agents when upgrading a rancher server

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#36523]
**Is your feature request related to a problem? Please describe.**

This was spotted when Harvester upgrades its embedded rancher service: https://github.com/harvester/harvester/issues/1707#issuecomment-998484833

After bumping rancher's to a newer image, RKE2 servers/agents are restarted due to machine plans change (`RESTART_STAMP` changes, code path might be [here](https://github.com/rancher/rancher/blob/d540651a7614b5377f9fe1bb3534b5029c57722e/pkg/provisioningv2/rke2/planner/planner.go#L710), not quite sure)

Restarting the server or agent can cause a node to enter `NotReady` status and [fails a Longhorn volume](https://github.com/longhorn/longhorn/issues/2650).

**Describe the solution you'd like**
- The ability to avoid restarting RKE2 server/agent when the rancher server is upgrading, or
- A guideline on how to avoid this.

**Describe alternatives you've considered**
Stop rancher-system-agent before upgrading rancher.

**Additional context**

**Comment by Oats87** [comment]
@bk201 Do you have any more details on the exact situation where you're seeing `rke2-*` restart? Rancher shouldn't be changing the `RESTART_STAMP` unless the plan changes in a significant manner.

**Comment by bk201** [comment]
@Oats87 Thanks for the reply. It happened when upgrading from ``v2.6.3-rc4`` to a later head version (supposed to be a version before the formal `v2.6.3` release. Sorry we didn't record the exact version). When I saw this behavior, I noticed some rancher-generated RKE2 config files changed.

**Comment by Oats87** [comment]
As these are unofficial/unsupported releases, it is very likely that we changed config file generation (i.e. changed some of the config files) which caused the restart stamp to change between the versions of Rancher. In GA releases, we shouldn't experience this; however, I would argue that Longhorn/Harvester should be able to elegantly handle Kubelet restarts (when `rke2-agent` is restarted, the `kubelet` is restarted).

**Comment by snasovich** [comment]
@bk201 , is this something that can be closed based on this comment: https://github.com/rancher/rancher/issues/36523#issuecomment-1055649525 ?

**Comment by bk201** [comment]
@Oats87 Do you mean the `RESTART_STAMP` won't change when upgrading from 2.6.3 to 2.6.4?

> I would argue that Longhorn/Harvester should be able to elegantly handle Kubelet restarts (when rke2-agent is restarted, the kubelet is restarted).

Longhorn did have an [enhancement](https://github.com/longhorn/longhorn/issues/2650) to this problem (available in `1.2.4`). Harvester 1.0.0 still uses Longhorn 1.2.3 and we want to make sure we don't see this problem when upgrading to the next version.

**Comment by bk201** [comment]
Close this one since we ship Longhorn 1.2.4 in Harvester 1.0.1 and it has the [enhancement](https://github.com/longhorn/longhorn/issues/2650).
