### ISSUE TITLE
Active Directory project and cluster members are not showing up when logged in as local rancher admin user

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#36539]
SURE 3661

**Rancher Server Setup**
Rancher Version : 2.5.9 and 2.6.2 

External Authentication: AD
   
**Describe the bug**
Active Directory project and cluster members are not showing up when logged in as local rancher admin user

**Troubleshooting steps:**
After login with local admin user, the AD users were not listing and shows 
"Unable to fetch principal info"

**To Reproduce**
1. Install Rancher
2. Configure external authentication with AD
3. Add users to a project using AD admin user
4. Login to Rancher with local admin user and check Project membership 

**Result**
Local admin can't see AD user's Project membership

**Expected Result**
Local admin should see AD user membership since we provide an AD service account while configuring authentication.

**Comment by igonzalez-geko** [comment]
Same issue is happening in my environment.
Once ActiveDirectory is configured and you logout and login as local admin, groups and users AD assigments cannot be shown/found. It seems that the AD user used for the connection is mapped in some way to the local admin.

![image](https://user-images.githubusercontent.com/105292869/175250834-5bcdf92f-8cbc-4bea-aa90-ec28b2402ed9.png)

**Comment by cnbrkdmn** [comment]
I have the same problem on my **Rancher Cluster 2.6.5 ver.**  We're using **Keycloak (OIDC) Authentication Provider** and access users with no problem. but, some users can fetch someones user's and group's data and the others cannot fetch the data and getting error like this; 

"Unable to fetch principal info ERROR"

![image](https://user-images.githubusercontent.com/32529331/191254595-a60f8780-47ef-4f34-9f5d-510530533f4f.png)

**Comment by craustin** [comment]
A side-effect of this issue is that creating [`rancher2_project_role_template_binding`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/project_role_template_binding) resources in the rancher2 terraform provider with `user_principal_id` set to a "activedirectory_user://..." path fails _if_ you're using a local user's access key/secret. It works when using an AD user's creds though.

**Comment by anupama2501** [comment]
Reproduced on v2.7.0
Steps to reproduce:
1. Install rancher server on v2.7.0
2. Enable openldap auth
3. Create a downstream cluster and add a few users to the downstream cluster as a cluster owner, cluster member and custom permissions.
4. Log out as auth admin and login as a local admin
5. As local admin and auth admin we can view the local users that were added.
6. Navigate to the downstream cluster >> cluster members >> Only see `Unable to fetch principal info` for all the auth users

<img width="400" alt="2023-01-26_15-28-23" src="https://user-images.githubusercontent.com/38144301/214973905-0954facc-bff8-43ff-9e61-09dce89152c6.png">

**Comment by Martin-Weiss** [comment]
Does Rancher contact AD with the logged in user or with the service account used for AD join? 
Could it be that Rancher does not use the specified service account for searches and due to that this search fails in this issue?

**Comment by Martin-Weiss** [comment]
Seems this must be changed - not every user of Rancher should be able to search in AD.. that is why we create the service accout and give that one the required rights in AD..

**Comment by hectoralicea** [comment]
> Reproduced on v2.7.0 Steps to reproduce:
> 
> 1. Install rancher server on v2.7.0
> 2. Enable openldap auth
> 3. Create a downstream cluster and add a few users to the downstream cluster as a cluster owner, cluster member and custom permissions.
> 4. Log out as auth admin and login as a local admin
> 5. As local admin and auth admin we can view the local users that were added.
> 6. Navigate to the downstream cluster >> cluster members >> Only see `Unable to fetch principal info` for all the auth users
> 
> <img alt="2023-01-26_15-28-23" width="400" src="https://user-images.githubusercontent.com/38144301/214973905-0954facc-bff8-43ff-9e61-09dce89152c6.png">

I'm getting the exact same issue. on v2.7.1

**Comment by moshiaiz** [comment]
> A side-effect of this issue is that creating [`rancher2_project_role_template_binding`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/project_role_template_binding) resources in the rancher2 terraform provider with `user_principal_id` set to a `activedirectory_user://...` path fails _if_ you're using a local user's access key/secret. It works when using an AD user's creds though.

I noticed that as well. So then I tried to create a group with `group_principal_id` set with `activedirectory_group://...`, while still using the local admin access token, and it worked!

So local admin user can add AD groups with `group_principal_id` but cannot add AD users using `user_principal_id`.

So this fails:
```
resource "rancher2_project_role_template_binding" "rb-test-user" {
  name               = "rb-test-user"
  project_id         = data.rancher2_project.default.id
  role_template_id   = "workloads-view"
  user_principal_id = "activedirectory_user://CN=SOMEUSER,OU=UsersDC=domain,DC=com"
}
```

And this works:
```
resource "rancher2_project_role_template_binding" "rb-test-group" {
  name               = "rb-test-group"
  project_id         = data.rancher2_project.default.id
  role_template_id   = "workloads-view"
  group_principal_id = "activedirectory_group://CN=SOMEGROUP,DC=domain,DC=com"
```

**Comment by samjustus** [comment]
blocked by #22417

**Comment by samjustus** [comment]
sure-6002

**Comment by hectoralicea** [comment]
I hope this gets addressed.  I have seen a bunch of access privilege malfunctions specifically when using OpenLDAP

**Comment by olblak** [comment]
Closing as the associated issue is closed

**Comment by YaronL16** [comment]
Hey, why did the issue close?

This is a big problem for my team on 2.8.5 so I would love to know how we can address this

**Comment by BBQigniter** [comment]
omg, so this seems to be normal? and I was checking all kind of logs and tried to figure out what the heck is going on and if the new HA setup has some issue.

at least post some info that once a auth-provider is configured, that the local-admin won't see everything anymore and that everything is alright

**Comment by samjustus** [comment]
@BBQigniter you are right, I will get this documented. 

I believe the [explanation from this similar issue](https://github.com/rancher/rancher/issues/45496#issuecomment-2228581165) explains the reasoning

**Comment by BBQigniter** [comment]
thank, you - the whole handling of the ActiveDirectory auth provider is quite confusing and I expected it to work like in a lot of other applications like

* create a connector
* create a group mapping 
* user logs in and the user has the permission set like configured in the mapping (if a user is created)

In Rancher it's something like

* create a connector and the first given user in the config will also be admin (tangled in so deep that even if you edit the local-admin user definition via kubectl something is left somewhere else)
* create a group mapping
* user logs in but gets permissions defined by the default rule from a "Role Template" and the permissions from the group mapping is NOT resembled in the user's permission details

also it seems that the highest permission counts if I'm not wrong

so if you forget to change the default role template to be "User-Base" instead of "User" the group that points to "User-Base" will be practically ignored if I remember now correctly from my tests.
