### ISSUE TITLE
[Authorized Cluster Endpoint] cannot enable endpoint for RKE generated downstream Cluster

### ISSUE THREAD

**Issue by kagehisa** [rancher/rancher#36549]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 v1.3.4
- Proxy/Cert Details: Custom Certificates and corporate proxy

**Information about the Cluster**
- Kubernetes version: v1.21.8
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): locally hosted RKE1 generated Cluster (Docker based)

**User Information**
- What is the role of the user logged in?  Admin
   
**Describe the bug**

We have a Rancher managed Kubernetes Cluster that was generated with RKE1. Due to several connection problems with Azure DevOps Server we need to have an external API endpoint for the Cluster.
When enabling the endpoint in the RKE config of the Cluster according to this [documentation](https://rancher.com/docs/rancher/v2.6/en/cluster-admin/editing-clusters/rke-config-reference/#local-cluster-auth-endpoint) and redeploying the cluster via RKE the endpoint is still listed as disabled in https://rancher.local.de/v3/clusters/cluster-id.
The generated kubectl for this Cluster from the Rancher UI also has no second context available.

**To Reproduce**
 
- Generate a RKE1 kubernetes Cluster
- Import it via Rancher UI
- Add: 
```
local_cluster_auth_endpoint:
  enabled: true
```
to the RKE configuration file for the Cluster
- redeploy the Cluster with `rke up --config <config-file>`

**Result**
- Output of https://rancher.local.de/v3/clusters/cluster-id for the cluster shows: 
```
localClusterAuthEndpoint": {

    "enabled": false,
    "type": "/v3/schemas/localClusterAuthEndpoint"

}
```
- no second context to the generated kubeconfig for this Cluster is added

 
**Expected Result**

A enabled exposed API endpoint as described in the Documentation and the second context for it in the generated kubeconfig file which was generated by the Rancher UI. 

**Screenshots**

**Additional context**

The Problem was discovered due to my Problems with attaching Azure DevOps Server Pipelines to our Cluster. As I mentioned in the [Rancher forums](https://forums.rancher.com/t/rancher-2-6-3-created-kubeconfig-does-not-allow-rbac-testing-of-service-account/36975).

**Comment by janeczku** [comment]
@kagehisa The Authorized Cluster Endpoint feature is not supported for imported RKE clusters. In order to use that feature, please provision the RKE cluster with Rancher (and not using the rke CLI), for example by using the "Custom Cluster" option.
