### ISSUE TITLE
Kubelet stops posting status after upgrade; Intermittent issue

### ISSUE THREAD

**Issue by Auston-Ivison-Suse** [rancher/rancher#36548]
**Rancher Server Setup**
- Rancher version: v2.6.3  upgraded to v2.6-head(3f30288)
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):  v1.21.8 RKE1
- Proxy/Cert Details: BYOD

**Information about the Cluster**
- Kubernetes version:  v1.19.16
- Cluster Type:Downstream 
   - If downstream, what type of cluster?: RKE1 Azure Node Driver

**User Information**
- What is the role of the user logged in? Admin

   
**Describe the bug**
Following an upgrade an etcd node has the error "Kubelet stopped posting node status." The cattle node agent for the previous version doesn't finish terminating either. 

**To Reproduce**
1. provision a cluster using the azure node driver with the above k8s version.
2. upgrade Rancher to the next available version. I used a helm upgrade command along with the local clusters kubeconfig file. 
`helm upgrade rancher rancher-latest/rancher --version 2.6.3 --set rancherImageTag=v2.6-head --namespace cattle-system --set hostname=<hostname> --set ingress.tls.source=secret --set bootstrapPassword=admin`
3. wait for the local cluster to finish the upgrade. 

**Result**
There is an unavailable node as well as a cattle-node-agent failing to completely terminate; all within the downstream cluster that was described above. 
**Expected Result**
Cluster and its components all upgrade. 

**Screenshots**
1.  Kubelet stopped
![NodeKubeleteStopped](https://user-images.githubusercontent.com/89411550/154429012-0168aa8a-4cf5-4076-95aa-21facff1340a.png)

2. cattle agent failing to terminate and upgrade
![KubeletStopped-CattleAgent](https://user-images.githubusercontent.com/89411550/154429089-aa43e6ef-2d9a-40e4-a47c-a79bffb45e8e.png)

**Additional Info**
This has been hard to reproduce, but posting issue for tracking purposes.

**Comment by snasovich** [comment]
@Auston-Ivison-Suse @slickwarren @sowmyav27 @timhaneunsoo @Josh-Diamond , if you run into it again, could you please ping us in the team channel and provide details to access the environment where it's reproducible?

**Comment by snasovich** [comment]
Moving this one to test based on the comment above

**Comment by sowmyav27** [comment]
Closing this for now. Will log a new bug if we notice this again
