### ISSUE TITLE
[rke2] Install script for windows (custom cluster) currently links to public sources -> windows will fail in airgap setups

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36552]
**Rancher Server Setup**
- Rancher version: v2.6.4-rc3
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1
- Proxy/Cert Details: valid letsencrypt certs

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom, rke2, windows

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): any

   
**Describe the bug**

user in an airgap setup is unable to register windows nodes due to part of the script pulling from github (inaccessible in airgap setups)

**To Reproduce**
 
* deploy a rancher setup that is airgapped
* deploy a custom cluster (rke2) with linux nodes (so that windows reg. command displays)
* register the windows node using the windows registration command

**Result**
* windows node never pulls the script and is unable to register 

`Get "https://raw.githubusercontent.com/rancher/wins/main/install.ps1": dial tcp 185.199.110.133:443: i/o timeout`

**Expected Result**

windows should register in an airgap setup

**Comment by sirredbeard** [comment]
wins Install script for Rancher airgap has been merged.

**Comment by deniseschannon** [comment]
Available to test in v2.6.4-rc5

**Comment by sirredbeard** [comment]
This is available to test.

**Comment by slickwarren** [comment]
on 2.6.5-rc1 I am still running into issues when registering an airgapped windows node in an airgapped rancher setup. 

I will send setup details in the channel shortly. TLDR: when running the windows reg. command, the command times out with error 
```
ObjectNotFound: (./install.ps1:String) [], CommandNotFoundException
```

**Comment by slickwarren** [comment]
I've tried a few different approaches in airgap with windows, but the node is not able to get the registration command for some reason. Waiting for @rosskirkpat to have time to help look into this issue with QA so that we may reach a solution.

**Comment by slickwarren** [comment]
tested using v2.6.5-rc3:
* in an airgap setup, deploy an rke2 custom cluster (k8s v1.22.8+rke2r1)
  * prepare airgap windows node by deploying a public windows AMI (4/13/22 containerlatest), install certs from rancher installation, curl rancher LBs, and verify that the windows cert store has all necessary certs. Create a private AMI to use in airgap later
  * once there are dedicated nodes-per-role for linux nodes, deploy the private AMI for airgap setup
  * airgap node should register with rancher -- **fail**

the registration command is able to curl onto the windows node, but is not able to finish setup and hangs when deploying rancher-wins with the following error: 
```
Start-Service : Service 'Rancher Wins (rancher-wins)' cannot be started due to the following error: Cannot start service rancher-wins on computer '.'.
At C:\Users\administrator\install.ps1:616 char:9
+         Start-Service -Name $serviceName
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

```
(see screenshot below)
<img width="912" alt="Screen Shot 2022-04-26 at 1 31 10 PM" src="https://user-images.githubusercontent.com/16691014/165403650-01f19c97-cf86-4641-b78c-4b0532c440d3.png">

**Comment by rosskirkpat** [comment]
https://github.com/rancher/rancher/pull/37527 has been merged. Moving this to waiting on Rancher RC. Here is a write-up of why:

When attempting to manually create the CSI Proxy Windows Service on 2022 as part of debugging, I found that v1.0.0 of CSI Proxy does not support Windows Server 2022. 

```powershell
PS C:\> New-Service

cmdlet New-Service at command pipeline position 1
Supply values for the following parameters:
Name: CSI Proxy
BinaryPathName: C:\usr\local\bin\csi-proxy.exe

Status   Name               DisplayName
------   ----               -----------
Stopped  CSI Proxy          CSI Proxy

.....


PS C:\> set-service -name 'CSI Proxy' -Status Running
set-service : Service 'CSI Proxy (CSI Proxy)' cannot be started due to the following error: Cannot start service CSI Proxy on computer '.'.
At line:1 char:1
+ set-service -name 'CSI Proxy' -Status Running
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Set-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.SetServiceCommand

.....
PS C:\> .\csi-proxy.exe --version
Program 'csi-proxy.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1
+ .\csi-proxy.exe --version
+ ~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\csi-proxy.exe --version
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
Windows Server 2022 support is available as of v1.1.1 of CSI proxy per https://github.com/kubernetes-csi/csi-proxy/commit/2a1dfdb670b6e8efbc987b6347e59dbcea35c97d.

There is no documentation or release notes to be found on the CSI proxy repository to indicate which versions of Windows are supported for releases.

**Comment by slickwarren** [comment]
After some investigation, it seems that our automation for registries is not setup to pull cross-platform images. Meeting to discuss options moving forward.

**Comment by slickwarren** [comment]
as of v2.6.5-rc6, windows rke2 is working in an airgap setup. 
Found a couple of errors along the way: https://github.com/rancher/rancher/issues/37577
