### ISSUE TITLE
[rke2] errors in rancher pods while provisioning rke2 clusters

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36555]
**Rancher Server Setup**
- Rancher version: v2.6.4-rc3
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1
- Proxy/Cert Details: valid certs

**Information about the Cluster**
- Kubernetes version: 1.21.9+rke2r+
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):any

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) any

   
**Describe the bug**

while provisioning downstream rke2 clusters, rancher pods show errors related to v1

**To Reproduce**
 
* deploy rancher
  * watch the logs of rancher once rancher is active & ready
* deploy a downstream rke2 cluster

**Result**
errors are shown in the logs. example:
```
[ERROR] Failed to reconcile MachineHealthCheck: error creating client and cache for remote cluster: failed to index field spec.providerID: no matches for kind "Node" in version "v1"
2022/02/17 19:05:45 [ERROR] Reconciler error: error creating client and cache for remote cluster: failed to index field spec.providerID: no matches for kind "Node" in version "v1"
2022/02/17 19:05:47 [ERROR] error creating remote cluster cache: error creating client and cache for remote cluster: failed to index field spec.providerID: no matches for kind "Node" in version "v1"
2022/02/17 19:05:47 [ERROR] Failed to reconcile MachineHealthCheck: error creating client and cache for remote cluster: failed to index field spec.providerID: no matches for kind "Node" in version "v1"
2022/02/17 19:05:47 [ERROR] Reconciler error: error creating client and cache for remote cluster: failed to index field spec.providerID: no matches for kind "Node" in version "v1"
2022/02/17 19:06:20 [ERROR] error creating remote cluster cache: error creating client and cache for remote cluster: failed to index field spec.providerID: no matches for kind "Node" in version "v1"
2022/02/17 19:06:20 [ERROR] Failed to reconcile MachineHealthCheck: error creating client and cache for remote cluster: failed to index field spec.providerID: no matches for kind "Node" in version "v1"
```
after the downstream cluster gets to an active state, errors like these are no longer seen in rancher. 
more logs available upon request

**Expected Result**

I expect there to not be errors while provisioning

**Comment by paynejacob** [comment]
These errors are expected when provisioning a cluster.  The machines do not have nod refs yet so the health checks do not know where to look to check them.
