### ISSUE TITLE
apply-system-agent-upgrader job on the rke2 clusters won't come up active when the PSP is set to restricted or restricted-noroot during cluster creation

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36559]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6.4-rc3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.22.6, 1.3.7
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: `v1.21.9+rke2r1`
- Cluster Type (Local/Downstream): `Downstream node driver 1 worker + etcd + cp RKE2`

**Describe the bug**
When the Pod security policy is set to restricted, the job `apply-system-agent-upgrader-on-anuketest3-pool1-c82d6bdc-8f147e` for each node stays in `In progress` state with a forbidden error seen in the logs. Updated the full log under `Result`

**To Reproduce**
1. Create an RKE2 cluster with 1 node all roles - I tried with DO
2. Under Security >> select the `restricted` Default Pod Security Policy [Happens when psp is set to `restricted-noroot` as well]
3. Cluster comes up active

**Result**
From the UI explorer >> Workloads >> jobs >> under `cattle-system` namespace we can see the job `apply-system-agent-upgrader-on-anuketest3-pool1-c82d6bdc-8f147e` stays in `In progress` and won't reconcile.

Error:
```
Error creating: pods "apply-system-agent-upgrader-on-anuketest3-pool1-c82d6bdc-8f147e-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.capabilities.add: Invalid value: "CAP_SYS_BOOT": capability may not be added]
```
 

**Expected Result**
Expected the jobs to come up active  

**Screenshots**
<img width="1012" alt="Screen Shot 2022-02-17 at 2 08 52 PM" src="https://user-images.githubusercontent.com/38144301/154579132-31c10642-dec7-4f3a-909a-c46ea33714e6.png">

**Additional context**

If we change the pod security policy to `unrestricted policy` the jobs come up active and the respective pods `apply-system-agent-upgrader-on-anuketest3-pool1-c82d6bdc-8bjgpv` are created for these jobs.

**Comment by sowmyav27** [comment]
can be tested using 2.6.4-rc5

**Comment by anupama2501** [comment]
Verified on 2.6.4-rc6 

- Created two rke2 node driver clusters with 1 worker, 1 etcd + cp by setting the psp to `restricted` and `restricted-noroot`
- Jobs come up active
