### ISSUE TITLE
Upgrade Istio to 1.11.7 on 2.6

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#36568]
Upgrade 2.6 to use Istio 1.11.7.  

Branch release-2.6
Make the updates and cut an RC. 
QA tests
Merge the changes back into release-2.6

**Comment by rishabhmsra** [comment]
**Validated on rancher v2.6-head (8ece6ae)**

**Created a k8s `1.22.6-rancher1-1` downstream cluster with 2 worker, 1 etcd, 1 cp nodes.**

Tested below scenarios on istio `100.1.1+up1.11.7`. All the checks look good.
- Fresh install checks
- Upgrade istio from `100.1.0+up1.11.4` —> `100.1.1+up1.11.7` (after upgrade deployed book app and validated traffic and traces through kiali and jaeger)
- Upgrade with custom overlay
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Unistall/reinstall checks
- Istio pointing to externally-installed Prometheus
- Multiple ingress
- Egressgateway
- Validated traffic for weighted book demo app.

**Result :**
All the checks passed with istio `100.1.1+up1.11.7`, hence closing the issue.
