### ISSUE TITLE
Create rancher-selinux RPM for SLE Micro

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#36563]
**Description:**
We need the `rancher-selinux` RPM to fully support SLE Micro. It should be necessary for multiple feature of RKE1, and for logging to fully work on both k3s and rke2, which already support SLE Micro besides that.

**Related Issues for Background:**
- https://github.com/rancher/rancher/issues/30949
- https://github.com/rancher/rancher/issues/31309
- https://github.com/rancher/rancher/issues/36364

**Open Pull Request(s) to Complete This Feature:**
- https://github.com/rancher/rancher-selinux/pull/10

**Comment by slickwarren** [comment]
will be part of validation of https://github.com/rancher/rancher/issues/36364 

this ticket's test should just be to make sure RPM installs

**Comment by bmdepesa** [comment]
rancher/rancher-selinux:v0.3-rc1.testing.1

Using public base ami `ami-0aaad3948bba137ca` I was able to install the `rancher-selinux` rpm. 

* Copied `rancher-selinux-0.3.rc1-1.sle.noarch.rpm` to the node
```
sudo transactional-update pkg install ./rancher-selinux-0.3.rc1-1.sle.noarch.rpm
sudo transactional-update pkg install libselinux1 checkpolicy libsemanage1 policycoreutils
sudo pam-config -a --selinux
sudo transactional-update setup-selinux
sudo vi /etc/default/grub # -- added "security=selinux selinux=1 enforcing=1"
sudo transactional-update grub.cfg
sudo reboot

suse@ip-xxx:~> sudo semodule --list-modules=full | grep rancher
400 rancher           pp

suse@ip-xxx:~> sudo sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     requested (insecure)
Max kernel policy version:      31

suse@ip-xxx:~> sudo getenforce
Enforcing
```
