### ISSUE TITLE
Catalog upgrade check will show error even if it's Up to Date

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3656]
Version: master 2/18

Steps: 
1.  Go to setting and add library https://github.com/tfiduccia/qa-catalog
2.  Add catalog glusterfs
3.  Add catalog Adding special character here é (version 2)
4.  Start both stacks
5.  Go back to settings and remove Custom library
6.  Go back to Stacks (should take you back automatically on Save)

Results: Both catalog-test-1 and glusterfs stack's upgrade check button say "Error checking upgrades"
![image](https://cloud.githubusercontent.com/assets/11514927/13184248/f68c4cfc-d6f7-11e5-8af1-ee5e19c6a5ae.png)

Expected: Only catalog-test-1 should have error.  If I browser refresh it fixes it.

**Comment by vincent99** [comment]
Step 5 is causing the rancher-catalog-service to restart, and it's not up yet by the time the upgade info is being requested in Step 6.

**Comment by vincent99** [comment]
Need a way to do `kill -HUP` or similar so the catalog service can reload the list without being down for a while.
