### ISSUE TITLE
Upgrade Istio to 1.11.7 on 2.5

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#36575]
Upgrade 2.5 to use Istio 1.11.7. For 2.5, this will be an upgrade from 1.10.x.

Branch release-2.5
Make the updates and cut an RC.
QA tests
Merge the changes back into release-2.5

**Comment by anupama2501** [comment]
Verified on 2.5.12

Created a k8s v1.20.15 downstream cluster with 3 worker, 1 etcd, 1 cp nodes.

Tested below scenarios on 1.11.700. All the checks look good.

- Fresh install checks
- Upgrade istio from 1.10.400 —> 1.11.7 (after upgrade deployed book app and validated traffic and traces through kiali and jaeger)
- Upgrade with custom overlay
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Unistall/reinstall checks
- Istio pointing to externally-installed Prometheus
- Multiple ingress
- Egressgateway
- Validated traffic for weighted book demo app.
