### ISSUE TITLE
cattle-cluster-agent CrashLoopBackOff

### ISSUE THREAD

**Issue by pythonLiNM** [rancher/rancher#36572]
The environment variable CATTLE_CA_CHECKSUM is set but there is no CA certificate configured at https://xxxx:8443/v3/settings/cacerts
rancher:v2.6.3
os:centos7.9
docker: 19.03.8

 
![微信图片_20220218193541](https://user-images.githubusercontent.com/50547107/154675429-11e30ce6-030c-40f0-be00-9ef3f3b19c16.png)

![image](https://user-images.githubusercontent.com/50547107/154675324-632996be-fd46-499a-b3e9-9771fe053467.png)

please help me!

**Comment by kp-code-desa** [comment]
Hi @pythonLiNM, did you find any solution?
