### ISSUE TITLE
Enhance eks downstream cluster autoscaler

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#36582]
SURE-3222

**Rancher Server Setup**
Rancher v2.5.5
Rancher2 Provider v1.16.0

**Information about the Cluster**
- Kubernetes v1.18 (EKS)
- AWS
-->

**User Information**
See SURE ticket
   
**Describe the bug**
The customer ran into an issue trying to get their Rancher EKS cluster to work with their regional STS endpoint via Terraform.
 
This is the error:
E0728 14:57:31.939172 1 xxx_yyyyyyy.zz:265] Failed to regenerate ASG cache: cannot autodiscover ASGs: RequestError: send request failed caused by: Post
https://autoscaling.us-east-2.amazonaws.com/
: x509: certificate signed by unknown authority
F0728 14:57:31.939195 1 xxx_yyyyyyy.zz:382] Failed to create AWS Manager: cannot autodiscover ASGs: RequestError: send request failed caused by: Post
https://autoscaling.us-east-2.amazonaws.com/
: x509: certificate signed by unknown authority
 
Which lead them to replace some of their components (see YAML attachments):

**Repro steps:**

Follow the documentation above for deploying the cluster autoscaler on a downstream EKS cluster.
Set the desired number of nodes in ASG to 2, minimum to 2, and Maximum to 20.
**Actual behavior:**
No scaling policy is created. So even if the cluster is 99% utilized no new nodes are created.
**Expected behavior:**
The autoscaler should increase the nodes up to 20, since that is the max.
_"We got the autoscaler to work using the attached which replaces the aws-node daemonset provided by Rancher
Can this be integrated with Rancher so it works automatically?"_

Files, logs, traces:
See the SURE ticket

**Comment by Sahota1225** [comment]
waiting for more input from the SURE ticket

**Comment by snasovich** [comment]
Additional information was not received and the associated support issue is closed. Closing.
