### ISSUE TITLE
Unable to Delete Null KEv2 Clusters

### ISSUE THREAD

**Issue by annablender** [rancher/rancher#36583]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Rancher in Goland

**Information about the Cluster**
- Kubernetes version: 1.21
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AKS/GKE created (not imported)

**Describe the bug**

Rancher is unable to delete AKS and GKE clusters that no longer exist. When I use the Rancher UI to create AKS and GKE downstream clusters and then delete the node group/cluster in the cloud provider, Rancher is unable to remove the cluster in the Rancher UI.

**To Reproduce**

- Run Rancher 2.6-head
- Create an AKS/GKE cluster in the Rancher UI
- Delete the node group/cluster in the cloud provider
- Delete the cluster in the Rancher UI

**Result**

Nothing happens. The cluster stays listed in the Rancher UI with the error `Cluster agent is not connected.`

![image](https://user-images.githubusercontent.com/12955547/154761576-126d201f-74f6-488e-b645-4b1af09ebb45.png)

**Expected Result**

When you delete a KEv2 cluster in the Rancher UI, it is deleted.

**Workaround**

Workaround: Remove finalizer that's still on the cluster object
1. Get ID of downstream cluster
2. `kubectl edit clusters.management <id>` (Example: `kubectl edit clusters.management c-r48nm`)
3. Remove finalizer
4. Save yaml

**Comment by thedadams** [comment]
I followed the steps provided in the issue and was not able to reproduce. When I deleted the GKE cluster from the Rancher UI, it was removed without issue.

**Comment by sowmyav27** [comment]
**Verified on 2.6.3 and 2.6-head commit id: `8c785a1`**

- Deployed EKS and GKE clusters from Rancher UI
- Deleted all the nodes from GKE and EKS/AWS console (backend)
- Clusters in Rancher went into Unavailable state
- Delete clusters from Rancher UI
- clusters were successfully deleted
