### ISSUE TITLE
Navigation needs tweaking in smaller browser

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3658]
Version: master UI 0.91.0

Steps: Make your browser window small until Registries creates a second line

Results: Environment is now on a third line instead of on the second one with Registries.  Also why is Registries not lined up with Hosts?
![image](https://cloud.githubusercontent.com/assets/11514927/13190837/ec316b00-d71c-11e5-97d8-4023256fbbfd.png)

Expected: Should be on same line as Registries and registries should line up under Hosts

**Comment by lvuch** [comment]
small screen nav fixes this in https://github.com/rancher/ui/pull/491

**Comment by tfiduccia** [comment]
Not fixed
Navigation section seems borked when I make the window now.  And I can't really read anything in light version.
![image](https://cloud.githubusercontent.com/assets/11514927/13506316/d33d2102-e13a-11e5-8864-4ed1de090856.png)
![image](https://cloud.githubusercontent.com/assets/11514927/13506302/c029cff2-e13a-11e5-8ef5-ededc0710c3e.png)

**Comment by tfiduccia** [comment]
Version - master UI 3/3
Verified fixed

Vincent fixed the issues so I'm taking it back and closing
