### ISSUE TITLE
Editing advanced cluster settings with Rancher v2.6.x and RKE1

### ISSUE THREAD

**Issue by twi-github** [rancher/rancher#36595]
**Rancher Server Setup**
- Rancher version: v2.6.1
- Installation option (Docker install/Helm Chart): Helm Chart on RKE1

**Information about the Cluster**
- Kubernetes version: v1.20.9
- Cluster Type (Local/Downstream): local

**User Information**
- Admin with rights to everything.

   
**Describe the bug**
There is no way obvious or documented way to edit more advanced cluster settings for RKE1-based clusters in Rancher v2.6 anymore. 

**To Reproduce**
Try to edit the cluster yaml of an RKE1 cluster using the Rancher GUI.

**Result**
An error is shown and nothing is changed: { "data": "404 page not found\n" }

**Expected Result**
I would like to be able to either edit the yaml or alternatively have a documentation where I can find this cluster definition to edit it using kubectl.

**Comment by catherineluse** [comment]
You can still edit advanced RKE1 cluster settings with the v2.6.x UI.

1. From cluster manager, go to the cluster list view.
2. Go to the RKE1 cluster where you want to edit advanced options and click **⋮ > Edit Config.**

<img width="1171" alt="Screen Shot 2022-04-25 at 10 42 16 AM" src="https://user-images.githubusercontent.com/20599230/165146367-c245ee36-b8cc-4cf1-99aa-54ff7736955b.png">

3. In the Cluster Options section, click **Edit as YAML.**
<img width="1286" alt="Screen Shot 2022-04-25 at 10 48 00 AM" src="https://user-images.githubusercontent.com/20599230/165146503-0fe5427e-2c80-4e8d-8a40-c83e92947070.png">

4. Edit advanced Kubernetes options under `rancher_kubernetes_engine_config`.

<img width="1285" alt="Screen Shot 2022-04-25 at 10 48 13 AM" src="https://user-images.githubusercontent.com/20599230/165146706-c5654694-308a-444c-83ef-b055a60b723c.png">

The steps are also documented here: https://rancher.com/docs/rancher/v2.6/en/cluster-admin/editing-clusters/rke-config-reference/#editing-clusters-with-yaml

**Comment by twi-github** [comment]
I did exactly this. It's not working with RKE1 clusters anymore:
![image](https://user-images.githubusercontent.com/100143158/165235630-cbb7f9e6-9dd4-42f3-bab0-3c5aaf1c4238.png)

**Comment by twi-github** [comment]
I just upgraded to 2.6.4. It's working again, thanks!
