### ISSUE TITLE
[Backport v2.5] Pass container limits from project in a new namespace if it does not override them

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#36599]
Backport of https://github.com/rancher/rancher/issues/27750

**Comment by brudnak** [comment]
## Reproduction Environment

| Component                 | Version / Type                                      |
| ------------------------- | --------------------------------------------------- |
| Rancher version           | 2.5.12                                              |
| Installation option       | Helm high availability (AWS)                        |
| RKE binary version used   | v1.2.16                                             |
| If Helm Chart k8s cluster | v1.20.14                                            |
| Cert Details              | ingress.tls.source=secret (certificates from files) |
| Docker version            | 20.10.7, build f0df350                              |
| Helm version              | v2.16.8-rancher1                                    |
| Downstream cluster type   | RKE1 Linode                                         |
| Downstream K8s version    | v1.20.15-rancher1-2                                 |
| Logged in user role       | Administrator                                       |
| Browser type              | Opera GX                                            |
| Browser version           | LVL3 (core: 84.0.4316.52) (x86_64)                  |

**ADDITIONAL SETUP**

- Helm install commands:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher --version 2.5.12 --namespace cattle-system --set hostname=$OMITTED --set ingress.tls.source=secret
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=tls.crt --key=tls.key
```

## Reproduction steps

1. Starting from `/g/clusters`
2. Hover over `Global` -> click the downstream RKE1 cluster name -> click `Projects/Namespaces`
3. Create a new project
   - Click `Add Project` -> fill out the project creation form
     - Project Name: `mytestproject`
     - Click `Container Default Resource Limit`
     - CPU Limit: `1000`
     - CPU Reservation: `1000`
     - Memory Limit: `512`
     - Memory Reservation: `512`
     - Click `Create` -> then redirected back to `Projects/Namespaces` page
4. Create a namespace under the newly created project with all default values
   - Click `Add Namespace` under the newly created project -> fill out the namespace creation form
   - Name: `mytestns`
   - Click `Create`
5. Now use `kubectl` commands to inspect the newly created namespace

```shell
kubectl get namespaces
kubectl describe namespace mytestns
```

6. You will see the resource limits listed

7. Now create a new namespace under the project using `kubectl` **AND NOT** the UI

```shell
touch new-ns-config.yaml
vi new-ns-config.yaml
```

8. Paste the following into the new file `new-ns-config.yaml`

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: REPLACE_WITH_CLUSTER_ID:REPLACE_WITH_PROJECT_ID
  labels:
    field.cattle.io/projectId: REPLACE_WITH_PROJECT_ID
  name: WHATEVER_NAMESPACE_NAME_YOU_WANT
```

9. Now run the following

```
kubectl create -f new-ns-config.yaml
```

10. Now inspect the namespace with `kubectl`

```shell
kubectl describe namespace newtestns
```

11. The namespace created does not have resource limits

## Additional Info

## RESULTS

#### :white_check_mark: Expected
Expected for the namespace created using kubectl within the project with resource limits to inherit those same limits, just like when creating a namespace in the UI

#### :x: Actual
The resource limits of the project **DID NOT** get added to the namespace when creating it via `kubectl`

<hr>

**Comment by maxsokolovsky** [comment]
@brudnak, @sowmyav27, the PR for this issue had not been merged, so it was not ready for QA Test yet. Most likely, we won't merge that PR, unless we hear by EOW from the customer using `v2.5.x` that this backport is absolutely necessary.

**Comment by samjustus** [comment]
Not backporting due to no response from customer
