### ISSUE TITLE
Unable to use tmux or screen in execute shell

### ISSUE THREAD

**Issue by cglewis** [rancher/rancher#366]
Would really like to be able to support persisting commands from the execute shell, tmux and screen would be nice ways to do this, but currently don't seem to work.  The containers themselves support tmux  and screen when attaching to them through the docker client on the docker host, so this should also be supported through the UI execute shell.

**Comment by vincent99** [comment]
I believe the problem is docker/docker#8755, but will try some of the script gymnastics in the comments to see if we can get screen/tmux to work.

**Comment by vincent99** [comment]
`/usr/bin/script -q -c "/bin/bash" /dev/null` seems to work for tmux

**Comment by tfiduccia** [comment]
version - master jan 07
Verified fixed
