### ISSUE TITLE
Where is data persistence in Rancher V2.5 + high availability deployment mode?

### ISSUE THREAD

**Issue by shizhiliuyu** [rancher/rancher#36609]
**Rancher Server Setup**
- Rancher version: v2.5.12
- Installation option   Helm Chart
k8s

**Information about the Cluster**
- Kubernetes version: 1.19
- Cluster Type  local

**Comment by Martin-Weiss** [comment]
Not sure if I understand the question right - Rancher stores its data in Kubernetes objects so they end up in the Kubernetes backing database (i.e. etcd). 
And then there is the rancher backup which allows to schedule regular backups to a S3 target.

**Comment by shizhiliuyu** [comment]
Is the Rancher data deployed by HELM persisted to the etCD of the local kubernetes cluster?

**Comment by shizhiliuyu** [comment]
Thanks to answer

**Comment by Martin-Weiss** [comment]
> Is the Rancher data deployed by HELM persisted to the etCD of the local kubernetes cluster?

Helm installs into objects stored in Kubernetes and due to that they are stored in etcd.
