### ISSUE TITLE
Edit VM overlay says Edit Container

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3660]
Version: master UI 0.91.0

Steps: 
1.  Add packet host
2.  Add VM
3.  Edit VM

Results: Overlay says Edit Container instead of Edit Virtual Machine

Expected: Should say Edit Virtual Machine

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/555

**Comment by tfiduccia** [comment]
Version - master 3/23
Verified fixed
