### ISSUE TITLE
Certificates error

### ISSUE THREAD

**Issue by caatclaudia** [rancher/rancher#36616]
**Rancher Server Setup**
Rancher version: v.2.6.3

**Installation of Rancher**
Requirements: Helm and k3s installed.

Installation:
1. Add the Helm Chart Repository
`#helm repo add rancher-latest https://releases.rancher.com/server-charts/latest`

2. Create a Namespace for Rancher
`#kubectl create namespace cattle-system`

3. Install cert-manager
```
#kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.1/cert-manager.crds.yaml
#helm repo add jetstack https://charts.jetstack.io
#helm repo update
#helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.5.1
```

4. Install Rancher with Helm and Your Chosen Certificate Option
```
# helm install rancher rancher-latest/rancher --version=2.6.3 --namespace cattle-system --set hostname=<HOSTNAME> --set bootstrapPassword=admin --set replicas=1
```

**Describe the bug**

1.  Created a machine debian just with docker installed.
2.  Created a Cluster RKE1 with "Custom" option on Rancher with default settings, select "etcd", "control plane" and "worker" options
3.  Copy and paste the command on debian machine.

Command is: `sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:v2.6.3 --server https://<RANCHER_HOSTNAME> --token XX --ca-checksum XX --etcd --controlplane --worker
`

In Rancher logs, shows the message "Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system":
![image](https://user-images.githubusercontent.com/56655085/155371238-f411dd85-cce7-4097-8e89-995d7bce5022.png)

In logs on the side of the containers, shows a message about the certificates:
![image](https://user-images.githubusercontent.com/56655085/155371204-5fb23d6a-38b2-47b8-9620-0dfb6248f02f.png)

Is any way to allow "insecure" communications when I run the docker command, or what I could do?

**Comment by paynejacob** [comment]
Did you modify your service or cluster cidr when you were configuring the cluster?

**Comment by caatclaudia** [comment]
> Did you modify your service or cluster cidr when you were configuring the cluster?

No, I didn't because in machine i just had docker installed. Should I modify CIDR on Rancher settings with the IP address from docker that has installed in machine?

**Comment by paynejacob** [comment]
you should not need to.  is it possible that 10.43.0.1 or 10.42.0.1 collide with another network that node is on?

**Comment by caatclaudia** [comment]
> is it possible that 10.43.0.1 or 10.42.0.1 collide with another network that node is on?
I verified and I don't think so, in my interfaces I don't see any IP 10.X.0.1. I used the "ip a" command.
I only have three interfaces: loopback, my connection with exterior, and docker0 with 172.17.0.1/16 network.

**Comment by caatclaudia** [comment]
> do you see any interfaces on the node you are importing with the 10.96.0.1 CIRDR?

Nothing, just this:
![image](https://user-images.githubusercontent.com/56655085/155562805-6b6ca172-b721-414e-9a76-ca49935d6f09.png)

**Comment by paynejacob** [comment]
are there any other nodes in this cluster?

**Comment by paynejacob** [comment]
How did you install rancher? If it is a helm install can you describe your setup.

**Comment by caatclaudia** [comment]
> How did you install rancher? If it is a helm install can you describe your setup.

Ok, I edited my issue with this information.
