### ISSUE TITLE
[2.5] Rancher crashes when provisioning a RKE1 node driver cluster

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#36619]
https://github.com/rancher/rancher/issues/36588

**Comment by dasarinaidu** [comment]
I validated this issue on v2.5.16 and did not see any issues in creating a RKE cluster, not seeing any panic logs as well.

Rancher Version : v2.5.16

Validated below test cases:
1. Create a RKE Cluster(AWS) from a Standard user and make sure etcd set to S3
(advanced options >> etcd Snapshot Backup Target set to s3 and no s3 creds is given)

2. Create a RKE Cluster(AWS) from a Admin user

3. Create a RKE Cluster(Lenode) from a Standard user and make sure etcd set to S3
(advanced options >> etcd Snapshot Backup Target set to s3 and no s3 creds is given)

Actual Behavior: clusters came up properly and did not see any rancher panic logs.

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/22034884/200436728-c4b021c7-9e9c-4894-9595-85c88c4dbd94.png">
