### ISSUE TITLE
CLI should support Apps created from Dashboard UI

### ISSUE THREAD

**Issue by dasMulli** [rancher/rancher#36610]
Creating an App from the Dashboard UI (non-legacy) does not make it manageable through the Rancher CLI's `rancher app` experience.

The Rancher CLI should support dashboard-created Apps through the Apps & Marketplace experience.

Tested on: Rancher 2.6.3, Rancher CLI 2.6.0

**Comment by gasrocco** [comment]
We are facing the same problem, we can't refresh the repositories and apps deployed from "Apps & Marketplace".

From rancher 2.6.3 legacy apps are deprecated but do you not implemented support in rancher cli for Apps & Marketplace ?
