### ISSUE TITLE
[2.5] Rancher logs spammed with RoleBinding.rbac.authorization.k8s.io is invalid: when any auth group is assigned restricted admin global role

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#36621]
Rancher Server Setup

Rancher version: `v2.5.12`
Installation option (Docker install/Helm Chart): Docker install
If Helm Chart, Kubernetes Info: k3s
Cluster Type (RKE1, RKE2, k3s, EKS, etc):
Node Setup: 1 node
Version: `v1.21.3+k3s1`
Proxy/Cert Details: `self-signed`
Information about the Cluster

Kubernetes version:
Cluster Type (Local/Downstream): Downstream infrastructure provider 3 worker, 1 etcd, 1 cp
RKE1
Describe the bug
When an auth group is assigned a global role in the groups a global role, we see the rancher logs are spammed with error logs.

To Reproduce

Enable auth - I tried with azure AD and openLDAP
From global auth --> groups --> assign a role from the auth as a restricted admin.
A global role binding is created for the group in the global role bindings:
Verify the rancher logs as soon as the group is added
Result
As soon as the group is added, we see the following logs scroll through continuously:

 error syncing 'grb-hmhsb': handler restrictedAdminGlobalBindingsFleet: 1 error occurred:
	* RoleBinding.rbac.authorization.k8s.io "grb-hmhsb-fleetworkspace-restricted-admin-rb-cluster" is invalid: subjects[0].name: Required value
Expected Result
Did not expect the error logs when the group is added in the rancher server

Additional context

**Comment by MbolotSuse** [comment]
PR: https://github.com/rancher/rancher/pull/36479

Issue is mostly a copy of https://github.com/rancher/rancher/issues/36216.

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                                      |
| ------------------------- | --------------------------------------------------- |
| Rancher version           | 2.5.12                                              |
| Installation option       | Helm high availability (AWS)                        |
| RKE binary version used   | v1.2.16                                             |
| If Helm Chart k8s cluster | v1.20.14                                            |
| Cert Details              | ingress.tls.source=secret (certificates from files) |
| Docker version            | 20.10.7, build f0df350                              |
| Helm version              | v2.16.8-rancher1                                    |
| Downstream cluster type   | not applicable                                      |
| Downstream K8s version    | not applicable                                      |
| Logged in user role       | Administrator                                       |
| Browser type              | Opera GX                                            |
| Browser version           | LVL3 (core: 84.0.4316.52) (x86_64)                  |

**ADDITIONAL SETUP**

- Helm install commands:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher --version 2.5.12 --namespace cattle-system --set hostname=$OMITTED --set ingress.tls.source=secret
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=tls.crt --key=tls.key
```

## Reproduction steps

1. Enable Authentication
   - Starting from the **default** homepage `/g/clusters`
   - Hover over `Security` -> click `Authentication` -> `LDAP OpenLDAP`
   - Fill out the OpenLDAP configuration form
   - Click `Authenticate with OpenLDAP`
2. Assign Global Role to an OpenLDAP Group
   - Hover over `Security` -> click `Groups` -> `Assign Global Role`
   - Fill out the `Assign Global Roles To Group` form, choose a group from OpenLDAP 
   - Set the Global Permissions to the group selected as `Restricted Administrator`
   - Click `Create`
3. Check the Rancher logs for error messages
   - Hover over `Global` (in the main/top navigation bar) -> `local` -> click `System`
   - You should default to `Workloads` -> click `rancher` under the `cattle-system` namespace
   - Inspect the logs of all the rancher pods
   - Error located, see screenshot under `Additional Info` labeled `A1`

```log
2022/04/01 19:59:43 [ERROR] error syncing 'grb-54xj2': handler restrictedAdminGlobalBindingsFleet: 1 error occurred:
	* RoleBinding.rbac.authorization.k8s.io "grb-54xj2-fleetworkspace-restricted-admin-rb-cluster" is invalid: subjects[0].name: Required value
```

## Additional Info


<img width="1751" alt="001-a1" src="https://user-images.githubusercontent.com/40877149/161339036-ceefe2fe-5c3c-4c23-9d6a-adfc55499325.png">

## RESULTS

#### :white_check_mark: Expected
For there to be no error logs

#### :x: Actual
Error logs were present

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                                                                                   |
| ------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------ |
| Rancher version           | v2.5-025a17b5250370d9a25745675e605710225c73e2-head [025a17b](https://github.com/rancher/rancher/commit/025a17b5250370d9a25745675e605710225c73e2) |
| Installation option       | Helm high availability (AWS)                                                                                                                     |
| RKE binary version used   | v1.2.16                                                                                                                                          |
| If Helm Chart k8s cluster | v1.20.14                                                                                                                                         |
| Cert Details              | ingress.tls.source=secret (certificates from files)                                                                                              |
| Docker version            | 20.10.7, build f0df350                                                                                                                           |
| Helm version              | v2.16.8-rancher1                                                                                                                                 |
| Downstream cluster type   | not applicable                                                                                                                                   |
| Downstream K8s version    | not applicable                                                                                                                                   |
| Logged in user role       | Administrator                                                                                                                                    |
| Browser type              | Opera GX                                                                                                                                         |
| Browser version           | LVL3 (core: 84.0.4316.52) (x86_64)                                                                                                               |

**ADDITIONAL SETUP**

- Helm install commands:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher --version 2.5.12 --namespace cattle-system --set hostname=$OMITTED --set ingress.tls.source=secret --set rancherImageTag=v2.5-head
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=tls.crt --key=tls.key
```

## Validation steps

1. Enable Authentication
   - Starting from the **default** homepage `/g/clusters`
   - Hover over `Security` -> click `Authentication` -> `LDAP OpenLDAP`
   - Fill out the OpenLDAP configuration form
   - Click `Authenticate with OpenLDAP`
2. Assign Global Role to an OpenLDAP Group
   - Hover over `Security` -> click `Groups` -> `Assign Global Role`
   - Fill out the `Assign Global Roles To Group` form, choose a group from OpenLDAP 
   - Set the Global Permissions to the group selected as `Restricted Administrator`
   - Click `Create`
3. Check the Rancher logs for error messages
   - Hover over `Global` (in the main/top navigation bar) -> `local` -> click `System`
   - You should default to `Workloads` -> click `rancher` under the `cattle-system` namespace
   - Inspect the logs of all the rancher pods
   - Error message found in reproduction section not found here

## Additional Info

## RESULTS

#### :white_check_mark: Expected
For there to be no error logs

#### :white_check_mark:Actual
No error logs found
