### ISSUE TITLE
Unable to provision rke2 node driver linode cluster errors with - `ls: cannot access 'docker-machine-driver-*': No such file or directory`

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36626]
**Rancher Server Setup**
- Rancher version: `v2.6-head 8c785a1`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.21.3+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.21.9+rke2r1`
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 1 worker, 1 etcd + cp`
`RKE2`

**Describe the bug**
Provisioning an rke2 node driver cluster fails with the error 
`CreateError: Downloading driver from https://45.33.74.83/assets/docker-machine-driver-linode` 

**To Reproduce**
 Create an rke2 node driver cluster with linode as provider

**Result**
Provisioning fails with the error:
```
Waiting] provisioning bootstrap node(s) anu-linode-ec-767964fb66-77gb7: waiting for failed creating server (LinodeMachine) in infrastructure provider: CreateError: Downloading driver from https://<redacted>/assets/docker-machine-driver-linode ls: cannot access 'docker-machine-driver-*': No such file or directory downloaded file failed sha256 checksum download of driver from https://<redacted>/assets/docker-machine-driver-linode failed, agent to check in and apply initial plan
```

**Expected Result**
Expected the provisioning to go through without any error

**Comment by jakefhyde** [comment]
@thedadams Is this related to another issue you were working on?

**Comment by thedadams** [comment]
@jakefhyde Yep, right now.

**Comment by noahgildersleeve** [comment]
This happens with the node-driver for Harvester as well. Rancher `v2.6.4-rc4` and `v2.6-head` with Harvester `master-bfd6a8a9-head`

**Comment by anupama2501** [comment]
Verified on an upgraded setup from 2.6.2 --> 2.6-head e93a53c

- Created a linode single node all roles -- PASSS
- Created a linode multi node 1 etcd, 1 cp, 3 worker -- PASS
- Created a workload deployment, an SD - works fine

Fresh install checks on 2.6-head e93a53c

- Created a linode single node all roles -- PASSS
- Created a linode multi node 1 etcd, 1 cp, 2 worker -- PASS



Re-opening for this usecase:

Created one more multi node with 1 etcd, 2 cp, 3 worker node - One of the worker nodes is stuck in `Createerror` state. 
The other 2 worker nodes in the same pool came up active. 
Following is the error displayed:
```
Failed creating server (LinodeMachine) in infrastructure provider: CreateError: Downloading driver from https://<redacted>/assets/docker-machine-driver-linode Doing /etc/rancher/ssl docker-machine-driver-linode docker-machine-driver-linode: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped Running pre-create checks... (multi-w-4bf259bc-76f2g) Generating a secure disposable linode-root-pass... Creating machine... (multi-w-4bf259bc-76f2g) Creating Linode machine instance... Error creating machine: Error in driver during machine creation: [408] Please try again The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
```

This does not happen always. Happened for 1 out of 3 nodes in 1 out of 3 clusters.

**Comment by thedadams** [comment]
@anupama2501 That is not the same problem. There is already an issue for that.

**Comment by anupama2501** [comment]
Closing this issue and re-opened the issue linked above.
