### ISSUE TITLE
[Monitoring] upgrade failed when uninstalling and upgrading from monitoring v1 to v2

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#36639]
**Rancher Server Setup**
- Rancher version: `2.6-head Commit ID 20d20a3`
- Installation option (Docker install/Helm Chart): `Docker`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `rke1`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.21.9`
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `downstream ec2 - 1 etc 1 cp 3 worker nodes`

**User Information**
- What is the role of the user logged in? `Admin`

   
**Describe the bug**
Had monitoring v1 installed; when installing monitoring v2, first step was to uninstall v1 - successfully completed that step; then, when installing v2, selected `Persistent Storage for Prometheus`; logs show upgrade failed, which is proceeded by success. It appears as though monitoring installed - all UI elements are present. 

**To Reproduce**
1. Create downstream cluster
2. enable monitoring v1
3. install monitoring v2
4. message: you must uninstall v1 before installing v2 - click to proceed
5. logging v1 uninstalled successfully
6. click to proceed
7. select persist storage for prometheus
8. Install

**Result**
Log message that Upgrade Fails

`helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-100.1.1-up19.0.3.yaml --version=100.1.1+up19.0.3 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-100.1.1-up19.0.3.tgz
--
Thu, Feb 24 2022 10:38:28 am | checking 5 resources for changes
Thu, Feb 24 2022 10:38:28 am | W0224 15:38:28.617013 25 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Thu, Feb 24 2022 10:38:28 am | W0224 15:38:28.633199 25 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Thu, Feb 24 2022 10:38:28 am | W0224 15:38:28.661021 25 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Thu, Feb 24 2022 10:38:28 am | Looks like there are no changes for ServiceAccount "rancher-monitoring-crd-manager"
Thu, Feb 24 2022 10:38:28 am | Looks like there are no changes for ConfigMap "rancher-monitoring-crd-manifest"
Thu, Feb 24 2022 10:38:28 am | Looks like there are no changes for ClusterRole "rancher-monitoring-crd-manager"
Thu, Feb 24 2022 10:38:28 am | Looks like there are no changes for ClusterRoleBinding "rancher-monitoring-crd-manager"
Thu, Feb 24 2022 10:38:28 am | beginning wait for 5 resources with timeout of 10m0s
Thu, Feb 24 2022 10:38:28 am | Starting delete for "rancher-monitoring-crd-create" Job
Thu, Feb 24 2022 10:38:28 am | jobs.batch "rancher-monitoring-crd-create" not found
Thu, Feb 24 2022 10:38:29 am | creating 1 resource(s)
Thu, Feb 24 2022 10:38:29 am | Watching for changes to Job rancher-monitoring-crd-create with timeout of 10m0s
Thu, Feb 24 2022 10:38:29 am | Add/Modify event for rancher-monitoring-crd-create: ADDED
Thu, Feb 24 2022 10:38:29 am | rancher-monitoring-crd-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Thu, Feb 24 2022 10:38:29 am | Add/Modify event for rancher-monitoring-crd-create: MODIFIED
Thu, Feb 24 2022 10:38:29 am | rancher-monitoring-crd-create: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Thu, Feb 24 2022 10:38:37 am | Add/Modify event for rancher-monitoring-crd-create: MODIFIED
Thu, Feb 24 2022 10:38:37 am | Starting delete for "rancher-monitoring-crd-create" Job
Thu, Feb 24 2022 10:38:38 am | Release "rancher-monitoring-crd" has been upgraded. Happy Helming!
Thu, Feb 24 2022 10:38:38 am | NAME: rancher-monitoring-crd
Thu, Feb 24 2022 10:38:38 am | LAST DEPLOYED: Thu Feb 24 15:38:27 2022
Thu, Feb 24 2022 10:38:38 am | NAMESPACE: cattle-monitoring-system
Thu, Feb 24 2022 10:38:38 am | STATUS: deployed
Thu, Feb 24 2022 10:38:38 am | REVISION: 2
Thu, Feb 24 2022 10:38:38 am | TEST SUITE: None
Thu, Feb 24 2022 10:38:38 am |  
Thu, Feb 24 2022 10:38:38 am | ---------------------------------------------------------------------
Thu, Feb 24 2022 10:38:38 am | SUCCESS: helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-100.1.1-up19.0.3.yaml --version=100.1.1+up19.0.3 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-100.1.1-up19.0.3.tgz
Thu, Feb 24 2022 10:38:38 am | ---------------------------------------------------------------------
Thu, Feb 24 2022 10:38:38 am | helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-100.1.1-up19.0.3.yaml --version=100.1.1+up19.0.3 --wait=true rancher-monitoring /home/shell/helm/rancher-monitoring-100.1.1-up19.0.3.tgz
Thu, Feb 24 2022 10:38:38 am | Error: UPGRADE FAILED: template: rancher-monitoring/charts/rancherServiceMetrics/templates/servicemonitor.yaml:3:72: executing "rancher-monitoring/charts/rancherServiceMetrics/templates/servicemonitor.yaml" at <"rancher">: nil pointer evaluating interface {}.labels

`
**Expected Result**
Monitoring v2 installed with no errors

**Screenshots**

**Additional context**
Created a receiver and saw an error in the console:
`subscribe.js:207 Cannot Watch [cluster] {"type":"monitoring.coreos.com.receiver"}`

Created a route and saw same error in console:
`subscribe.js:207 Cannot Watch [cluster] {"type":"monitoring.coreos.com.receiver"}`

**Comment by ronhorton** [comment]
I also got this error when I upgraded v2 from a previous version to the current version in `2.6-head Commit ID 8cc8121`

`Error: UPGRADE FAILED: template: rancher-monitoring/charts/rancherServiceMetrics/templates/servicemonitor.yaml:3:72: executing "rancher-monitoring/charts/rancherServiceMetrics/templates/servicemonitor.yaml" at <"rancher">: nil pointer evaluating interface {}.labels`

**Comment by rishabhmsra** [comment]
**Facing the error on fresh installation of monitoring chart as well**

**Rancher Server :**
- Version : v2.6-head (1d2b746)
- docker install

**Steps to Reproduce:**
- Provision a 4-node`(1-cp, 1-etcd, 2-worker)`, ec2 node driver cluster with k8s `v1.21.9-rancher1-2` or `v1.22.6-rancher1-2`
- From Apps and Marketplace install Monitoring chart `100.1.1+up19.0.3`
- Chart installation error in logs :
```
helm upgrade --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-100.1.1-up19.0.3.yaml --version=100.1.1+up19.0.3 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-100.1.1-up19.0.3.tgz
Release "rancher-monitoring-crd" does not exist. Installing it now.
W0302 12:09:15.194439 25 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
creating 5 resource(s)
W0302 12:09:15.734139 25 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
beginning wait for 5 resources with timeout of 10m0s
Starting delete for "rancher-monitoring-crd-create" Job
jobs.batch "rancher-monitoring-crd-create" not found
creating 1 resource(s)
Watching for changes to Job rancher-monitoring-crd-create with timeout of 10m0s
Add/Modify event for rancher-monitoring-crd-create: ADDED
rancher-monitoring-crd-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Add/Modify event for rancher-monitoring-crd-create: MODIFIED
rancher-monitoring-crd-create: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Add/Modify event for rancher-monitoring-crd-create: MODIFIED
Starting delete for "rancher-monitoring-crd-create" Job
NAME: rancher-monitoring-crd
LAST DEPLOYED: Wed Mar 2 12:09:13 2022
NAMESPACE: cattle-monitoring-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
---------------------------------------------------------------------
SUCCESS: helm upgrade --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-100.1.1-up19.0.3.yaml --version=100.1.1+up19.0.3 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-100.1.1-up19.0.3.tgz
---------------------------------------------------------------------
helm upgrade --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-100.1.1-up19.0.3.yaml --version=100.1.1+up19.0.3 --wait=true rancher-monitoring /home/shell/helm/rancher-monitoring-100.1.1-up19.0.3.tgz
Release "rancher-monitoring" does not exist. Installing it now.
Error: template: rancher-monitoring/charts/rancherServiceMetrics/templates/servicemonitor.yaml:3:72: executing "rancher-monitoring/charts/rancherServiceMetrics/templates/servicemonitor.yaml" at <"rancher">: nil pointer evaluating interface {}.labels
```

**Comment by superseb** [comment]
This was changed in https://github.com/rancher/charts/commit/4f04899ceec6190abe5abbe8081a8f2d6bf88c8f to actually prevent an empty lookup. We can easily add a default value but would like to know if this consistently reproduces as I could not reproduce on current `v2.6-head` @ronhorton @rishabhmsra
