### ISSUE TITLE
Catastrophic failure: Can't load UI anymore: object in path "firstRun.0" could not be found or was destroyed. 

### ISSUE THREAD

**Issue by marcellodesales** [rancher/rancher#3663]
Version:
----

```
time="2016-02-20T17:44:42Z" level=info msg="Starting rancher-compose-executor" version=v0.7.2

[root@pprdespap324 rancher]# docker images | grep rancher
rancher/server                         latest              7c0ed1de7188        2 weeks ago         845.3 MB
```

Steps: 
-----

* Tried to delete a container from a Host.
* Tried clicking in "Logging out"
* Tried deleting the cookies and reload the page.

Results: 
-----

* Container never deleted;
* Error in the UI through an Error Message banner... 
* Then, the website cannot reload anymore. 

<img width="480" alt="screen shot 2016-02-20 at 9 45 56 am" src="https://cloud.githubusercontent.com/assets/131457/13198186/69160e38-d7b7-11e5-93bc-dd8d73e8187f.png">

Expected:
----
* Delete the container
* Site is working properly.

**Comment by marcellodesales** [comment]
@deniseschannon It's been 3 days now and the server is at the same state... 

* Is there any recommendation on how to fix this? 
* Should I completely delete the database and start over?
* What possibly this can be?

**Comment by vincent99** [comment]
Open up the browser dev tools -> Console (in Chrome, preferably) and screenshot the stack trace?  And click on the `file_name:line_number` for the first entry which should show what line of code it came from.

The string `firstRun` does not appear anywhere in the UI, its dependencies, or any of our other repos, so we have no idea without more useful info.  Are you loading a customized UI?  Behind some kind of proxy?  A picture of the expanded out <head> element from the Elements tab might also have useful info.

**Comment by marcellodesales** [comment]
@vincent99 I just followed the vanilla installation... I was attempting to delete containers from the UI when it failed twice for the same... And then, it never recovered. 

Below is the screenshot requested... I clicked and it showed the exact line of code.

<img width="1424" alt="screen shot 2016-02-22 at 2 15 41 pm" src="https://cloud.githubusercontent.com/assets/131457/13234747/10515708-d96f-11e5-9ebe-0673eb625f2c.png">

Please let me know if there's a workaround! :+1: Would like to present this on a Meetup on Thursday and Hand off to the Tools team here.

**Comment by vincent99** [comment]
So that line is clearing the browser localStorage entries, you must have used that domain name for something else before and it left an entry with the key `firstRun.0` behind, and the `.` has special meaning in Ember.  Will add a check to prevent exploding in this situation.

In the meantime, go to the Resources tab of the dev tools -> Local Storage -> the url, click on each entry and hit the delete key to remove them all.

**Comment by marcellodesales** [comment]
@vincent99 you are absolutely right! I'm reusing a server from PROD to experiment Rancher! :+1:  So yeah, there was an entry there and I deleted the entry... It was `firstRun0.3`... I deleted and 

<img width="671" alt="screen shot 2016-02-22 at 8 31 41 pm" src="https://cloud.githubusercontent.com/assets/131457/13241808/7d51130a-d9a3-11e5-84c0-21dd889777e3.png">

And we are back now!!! @vincent99  Thanks a lot for helping... Please tell David that I really thank you guys for the attention... 

<img width="652" alt="screen shot 2016-02-22 at 8 33 57 pm" src="https://cloud.githubusercontent.com/assets/131457/13241846/d71fccbe-d9a3-11e5-93ba-68be18e93a14.png">


Marcello
