### ISSUE TITLE
[2.6.4] v2prov bootstrap secrets are taking too long to be created by Rancher

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#36637]
**Rancher Server Setup**
- Rancher version: v2.6-head
- Installation option (Docker install/Helm Chart): docker

The logs below are from running v2.6-head on Feb 23, 2022 and trying to provision an rke2 downstream linux-only cluster with v1.21.9 rke2. Rancher took over 2 minutes to provide the bootstrap secret to the first node in a custom cluster. 

This process used to take 5-15 seconds at most in v2.6.3. There have been significant changes to v2prov since 2.6.3 was released.

Once a bootstrap secret is requested, there are at least three v2prov controllers involved in generating/grabbing multiple secrets, service accounts, and various objects before Rancher can provide the secret that was originally requested. 

We need to investigate:
- what objects can be pre-generated instead of at the time of the bootstrap secret request
- mapping out the dependencies for each type of cluster in v2prov 
- methods of improving the efficiency of the controllers themselves (which may be down to pre-generation of objects)
- for custom clusters, don't show the registration commands if the backend controllers aren't ready to have nodes register

```console
[INFO]  Generating Cattle ID
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[ERROR]  401 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
[INFO]  Successfully downloaded Rancher connection information
```

Related issue: https://github.com/rancher/windows/issues/151 
The Windows team is specifically increasing the timeouts in our install script because of this issue.

**Comment by snasovich** [comment]
@thedadams @Oats87 , is this something that got fixed by some recent improvements to provisioning performance? The issue was submitted almost 2 weeks ago and I recall recent talks about speeding up provisioning.

**Comment by snasovich** [comment]
Meanwhile, @rosskirkpat , is this happening recently for you?

**Comment by Oats87** [comment]
This should have been resolved by: https://github.com/rancher/rancher/pull/36721

**Comment by sowmyav27** [comment]
Can we have dev template filled out with info for QA to validate ?

**Comment by snasovich** [comment]
@Oats87 , could you please fill out the template as per the ask above and move it to test when you come back tomorrow? Thank you.

**Comment by rosskirkpat** [comment]
While testing other changes, I was able to validate that bootstrap secrets are being generated much quicker than when this issue was filed.

**Comment by luthermonson** [comment]
@sowmyav27 we've deployed many custom clusters since this fix went in and confirm it's a non-issue anymore and we'd like to label this dev-validated and move on. Can we get it retagged and we will move it to QA to close?

**Comment by sowmyav27** [comment]
Closing as per [these comments](https://github.com/rancher/rancher/issues/36637#issuecomment-1072615634)

**Comment by shkarface** [comment]
This issue still happens on v2.6.6
