### ISSUE TITLE
Drain on delete - Node is stuck in deleting when tried to scale down

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36631]
**Rancher Server Setup**
- Rancher version: `v2.6-head 8c785a1`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.21.3+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 3 worker, 3 etcd, 2 cp`
`RKE2`

**Describe the bug**
Created a deployment with node scheduling `Run pods on specific node(s)` set to a node n1. The node pool has the feature `drain on delete` enabled. If we try to scale down the node, the node is stuck in `deleting`.

**To Reproduce**
1. Create an rke2 node driver cluster with 3 node pools 1 for each role with 3 worker, 3 etcd, 2 cp nodes
2. Enable `drain on delete` feature for each of the node pools.
3. Create a workload deployment 
4. From the node scheduling tab >> select `Run pods on specific node(s)` and select the worker node w1
5. From cluster management >> machine pools >> select the worker node w1 >> scale down

**Result**
The node is stuck in `deleting` and never gets deleted. 

Following are the docker logs that go in a loop:

```
I0223 23:56:24.800925      34 request.go:665] Waited for 2.55470303s due to client-side throttling, not priority and fairness, request: 
GET:https://<>/k8s/clusters/c-m-qsc62p7f/api/v1/namespaces/default/pods/wk1-5c779f5b-jht54?timeout=10s

2022/02/23 23:56:25 [ERROR] Drain failed, retry in 20s: [error when waiting for pod "wk1-5c779f5b-6v5b7" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-lq2wl" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-6hfnw" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-hxlrt" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-7xnmc" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-r5plh" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-9ftwc" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-r27tf" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-22dmr" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-jkdz8" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-ts6mb" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-dxfdg" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-zdv4n" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-znghj" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-jht54" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-kwzqh" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-zfg5d" terminating: global timeout reached: 20s, error when waiting for pod "wk1-5c779f5b-8ns7j" terminating: global timeout reached: 20s]
```

**Expected Result**
Expected the node to be deleted 

**Screenshots**
<img width="500" alt="2022-02-23_16-58-14" src="https://user-images.githubusercontent.com/38144301/155460067-079f373d-e44f-4b6b-897c-1b8cc7a0ceb4.png">

**Additional context**
The node doesn't get deleted even if we delete the workload but if we delete the pods pertaining to that workload, the node then gets deleted.

**Comment by jakefhyde** [comment]
@anupama2501 Just want to confirm is it a 3 worker, 1 etcd, 1 cp or 3 worker, 3 etcd, 2 cp downstream? Also in the description is says to select the worker node, but the screenshot appears to show a control plane node, is this issue reproducible either way?

**Comment by anupama2501** [comment]
Hi @jakefhyde it was on a 3 worker, 3etcd, 2 cp. I updated the ticket - I used a saved reply and missed updating the information about cluster part and yes the issue is reproducible either way.

**Comment by jakefhyde** [comment]
### Root cause

When a deployment is scheduled using a `NodeSelector`, this circumvents the `kube-scheduler`, and prevents the pods from being evicted from the draining node. By default, CAPI uses a `NodeDrainTimeout` of 0, which means that node draining never times out. 
 
### What was fixed, or what changes have occurred

Allow the user to specify their own `NodeDrainTimeout`. 0 Will drain indefinitely.

### Areas or cases that should be tested

- Creating a deployment using a `NodeSelector` with a non-zero `NodeDrainTimeout` should forecefully delete the node after the specified timeout.
- Creating a deployment using a `NodeSelector` with a zero `NodeDrainTimeout` should not delete the node ever.
 
### What areas could experience regressions?

There are multiple upstream issues regarding this https://github.com/kubernetes-sigs/cluster-api/issues/6285, https://github.com/kubernetes/kubernetes/issues/75482, however the proposed workarounds are not applicable because they only work from a developer perspective: we can't force users to use `LabelSelector`s
 
### Are the repro steps accurate/minimal?

Yes

**Comment by Josh-Diamond** [comment]
Ticket #36631 - Test Results

With Docker on single-node instance:

Reproduced on rancher `v2.6-8c785a1d791f0051f2be320433e60ac9dd68cb3d-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, provision a downstream RKE2 Node driver cluster with `Drain Before Delete` enabled on each node
3. Once provisioned, deploy a workload on a specific worker node `Node Scheduling => Run pods on specific node(s)`
4. Once workload is active, go to `Cluster Management => Machine Pool`, then find specific worker node workload is deployed on and scale it down
5. Reproduced - Node initiates deletion but never deletes; caught in "hang" state

Screenshots:

`Initial`
<img width="1136" alt="reprod-inital" src="https://user-images.githubusercontent.com/46494969/161338903-6e26a012-0de3-4565-aa94-3d837dc81f5a.png">

`About 10 mins later`
<img width="1150" alt="reprod-20mins-later" src="https://user-images.githubusercontent.com/46494969/161339173-cbd44af9-cb6b-489a-b238-a6f0c43aa556.png">






Veri-FAILED on rancher `v2.6-457ba7ce4c4d5ddbe1abe82533e88c7d849d139c-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, provision a downstream RKE2 Node driver cluster with `Drain Before Delete` enabled on each node and set `Auto Replace` to any value greater than ZERO - [ I tested with `Auto Replace` set to `2` minutes ]
3. Once provisioned, deploy a workload on a specific worker node `Node Scheduling => Run pods on specific node(s)`
4. Once workload is active, go to `Cluster Management => Machine Pool`, then find specific worker node workload is deployed on and scale it down
5. Reproduced - Node initiates deletion but never deletes; caught in "hang" state

Screenshots:

`Initial`
<img width="1166" alt="verify-inital-final" src="https://user-images.githubusercontent.com/46494969/161341237-47b13f5e-d9d6-4d50-b6d4-1abda0399f86.png">

`Few mins. later`
<img width="1158" alt="verify-3mins-later" src="https://user-images.githubusercontent.com/46494969/161341319-8cb66782-1689-4a5d-8ed3-313429cecfaf.png">

`About 90 mins. later`
<img width="1311" alt="verify-90-mins-later" src="https://user-images.githubusercontent.com/46494969/161341353-23d4add1-a5a3-4fea-982d-71988cb3e4f6.png">
