### ISSUE TITLE
Nginx ingress options do not propagate to the configmap in Rancher launcher cluster in 2.5.11 and .12

### ISSUE THREAD

**Issue by bunicb** [rancher/rancher#36648]
**Rancher Server Setup**
- Rancher version: 2.5.11 and .12
- Installation option (Docker install/Helm Chart): Docker install and Helm Chart

**Information about the Cluster**
- Kubernetes version: v1.20.15
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
The nginx ingress options from cluster.yml are not propagated into the configmap, and as such are not set in the configuration.
The example of this is the option "use-forwarded-headers". In the documentation for Rancher 2.5 it is stated to add:
```
options:
  use-forwarded-headers: "true"
```
to the cluster.yml file of the cluster. In the versions 2.5.x, up to 2.5.10, this worked as intended, it added the option to the nginx-configuration configmap, and it was applied correctly in the nginx configuration. In 2.5.11 and 2.5.12, the configmap is now ingress-nginx-controller, but the options aren't correctly applied there.

**To Reproduce**

- install Rancher 2.5.11 or 2.5.12 (happens on both Docker and Helm installs)
- create a new Custom cluster
- add
```
options:
  use-forwarded-headers: "true"
```
to the cluster yaml
- add a node
- check the configmap and the config in the ingress pod

**Result**
No option applied in the nginx ingress configmap, and as a result incorrectly configured nginx ingress.

**Expected Result**
See the below setting in the configmap:
```
data:
  use-forwarded-headers: "true"
```
See the following in nginx.conf in the pod:
`use_forwarded_headers = true`

**Comment by junkiebev** [comment]
Same issue: https://github.com/rancher/rancher/issues/36484
