### ISSUE TITLE
RKE1 | Incorrect cluster state is returned when node pool is scaled up

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36640]
**Rancher Server Setup**
- Rancher version: v2.6-head 8c785a1
- Installation option (Docker install/Helm Chart): HA 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version: different k8s versions 
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): different RKE1 node driver clusters

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

   
**Describe the bug**

Cluster status is shown on UI as Active when a cluster has a node pool scaled up with nodes in Provisioning status 

**To Reproduce**
 
1. Provision a Digital Ocean and EC2/Linode/Azure RKE1 node deriver clusters
2. Scale up node pools in those clusters 

**Result**
Only Digital Ocean cluster is in the "Updating" state while other clusters are in "Active" status
![all](https://user-images.githubusercontent.com/40282141/155592352-8a3fefca-7d59-436c-809d-77d505a80b9b.jpg)

GET requests `{{URL}}/v1/management.cattle.io.clusters` and `{{URL}}/v1/provisioning.cattle.io.clusters` return "Active" state for aws and linode clusters with nodes being provisioned
![responses](https://user-images.githubusercontent.com/40282141/155593165-31bf5421-243f-4274-93f2-928f3905e149.jpg)

**Expected Result**

Cluster status is shown as "provisioning" when nodes are being provisioned

**Comment by jakefhyde** [comment]
This is either an issue in Steve or in the controllers, and requires some investigation into how best to manipulate the state to accurately reflect machine pool status.

**Comment by jiaqiluo** [comment]
The changes in the cluster's state are related to the type of nodes:

- The cluster's state stays in `Active`  If a `worker` node is added;
- The cluster's state becomes `Updating` if an `etcd` or `control plane` node is added.

@sgapanovich  In your case, it looks like the DO cluster stayed in `Active` because you added a worker node. Could you try it again?

**Comment by sgapanovich** [comment]
Confirmed on 2.6-head 4df2214: when we add a worker node we don’t update the cluster state to “Updating”. Cluster state is changed to "Updating" only when etcd/cp node pools are scaled up/down
