### ISSUE TITLE
Enter Chinese in the configmap, it will be automatically converted into binary data

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#36643]
**Rancher Server Setup**
- Rancher version: rancher/rancher:v2.6.3-patch1
- Installation option (Docker install/Helm Chart): docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin

   
**Describe the bug**

Enter Chinese in the configmap, it will be automatically converted into binary data

**To Reproduce**
 
1. Enter Chinese in configmap and save
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/19684717/155647596-24b078fe-8ad6-4527-9e6a-c0a537e9729e.png">

2. Edit this configmap to see the result
**Result**
Unable to edit, Chinese is converted into binary data
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/19684717/155647723-0de06ecd-85e6-4f91-a7a0-649ef5e94e78.png">

**Expected Result**

Chinese can be modified in configmap

**Screenshots**

**Additional context**

**Comment by niusmallnan** [comment]
https://github.com/rancher/dashboard/issues/5311
