### ISSUE TITLE
Unable to fetch user info... AD authentication not working for me

### ISSUE THREAD

**Issue by PatrickMondesir** [rancher/rancher#36641]
*Describe your issue here*
Unable to fetch user info... AD authentication not working for me
getting the following error "TestAndApply Error
can't find unique user for principal activedirectory_user" 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.8` UI: `v2.5.8` |
|Route|`undefined`|

**Comment by Brianalmeida** [comment]
I am experiencing this issue as well on Rancher 2.6.4
