### ISSUE TITLE
[feature] Deployment CI/CD guide

### ISSUE THREAD

**Issue by andrewmclagan** [rancher/rancher#3665]
Would be good to include a guide on integrating a CD pipeline based on Rancher.

There are so many questions and issues raised surrounding this functionality.

**Comment by cloudnautique** [comment]
Hi @andrewmclagan, not sure if you have seen our eBook/posts on this:

[Part1](http://rancher.com/docker-based-build-pipelines-part-1-continuous-integration-and-testing/)
[Part2](http://rancher.com/continuous-deployment/)
[Part3](http://rancher.com/docker-based-build-pipelines-part-3-managing-production-environments/)

**Comment by andrewmclagan** [comment]
Oops...
