### ISSUE TITLE
Unable to take s3 enabled etcd snapshots on rke1 clusters

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36660]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6-head d0d20a7
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.22.6, 1.3.7
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.22.6
- Cluster Type (Local/Downstream): `Downstream node driver 1 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
Not able to take a snapshot when s3 snapshots are enabled. This happens when a cluster is created with an rke template with s3 snapshots enabled. Happens only with rke1 clusters
Snapshots with the same configs work on 2.6.2 version of rancher.

**To Reproduce**
1. Create an rke1 node driver cluster with s3 enabled.
2. Once the cluster is active, from cluster management --> snapshots --> take a snapshot

**Result**
Snapshot fails with the following errors seen in the rancher logs:
```


2022/02/26 01:22:18 [INFO] [etcd] Snapshots configured to S3 compatible backend at [redacted] to bucket [au-s3bucket] using accesskey [redacted]
--
Fri, Feb 25 2022 5:22:18 pm | 2022/02/26 01:22:18 [INFO] [etcd] Running snapshot save once on host []
Fri, Feb 25 2022 5:22:18 pm | 2022/02/26 01:22:18 [INFO] Image [rancher/rke-tools:v0.1.78] exists on host []
Fri, Feb 25 2022 5:22:18 pm | 2022/02/26 01:22:18 [INFO] Starting container [etcd-snapshot-once] on host [], try #1
Fri, Feb 25 2022 5:22:18 pm | 2022/02/26 01:22:18 [INFO] [etcd] Successfully started [etcd-snapshot-once] container on host []
Fri, Feb 25 2022 5:22:18 pm | 2022/02/26 01:22:18 [INFO] Waiting for [etcd-snapshot-once] container to exit on host []
Fri, Feb 25 2022 5:22:18 pm | 2022/02/26 01:22:18 [INFO] Container [etcd-snapshot-once] is still running on host [68.183.148.220]: stderr: [time="2022-02-26T01:22:18Z" level=info msg="invoking set s3 service client" s3-accessKey="redacted=" s3-bucketName=au-s3bucket s3-endpoint= redacted s3-endpoint-ca= s3-folder= s3-region=
Fri, Feb 25 2022 5:22:18 pm | ], stdout: []
Fri, Feb 25 2022 5:22:19 pm | 2022/02/26 01:22:19 [INFO] Waiting for [etcd-snapshot-once] container to exit on host [redacted]
Fri, Feb 25 2022 5:22:20 pm | 2022/02/26 01:22:20 [INFO] Removing container [etcd-snapshot-once] on host [redacted], try #1
Fri, Feb 25 2022 5:22:20 pm | 2022/02/26 01:22:20 [INFO] kontainerdriver rancherkubernetesengine stopped
Fri, Feb 25 2022 5:22:20 pm | 2022/02/26 01:22:20 [WARNING] [etcd] Failed to take one-time snapshot on host [redacted], exit code [1]: time="2022-02-26T01:22:19Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:au-s3bucket, err:Access Denied."
Fri, Feb 25 2022 5:22:20 pm |  
Fri, Feb 25 2022 5:22:20 pm | 2022/02/26 01:22:20 [ERROR] error syncing 'c-pl58f/c-pl58f-rs-lxjxb': handler etcdbackup-controller: [etcd-backup] failed to perform etcd backup: failed to perform etcd backup: timed out waiting for the condition, requeuing


```

**Expected Result**
Expected the snapshot to work without any error

**Additional context**
related to the norman to steve fixes.

**Comment by anupama2501** [comment]
Verified on 2.6-head a2ef67a

Fresh install
1. Created a downstream rke1 cluster with 2 worker , 1 etcd + cp with s3 details added for etcd snapshots
Upgrade checks from 2.6.3 >> 2.6-head
3. from the cluster management page >> cluster >> snapshots >> Snapshot worked successfully and stored in s3
4. Created an rke1 template with etcd s3 snapshot enabled >> cluster creation with the template came up fine
5. Snapshot from the cluster work as expected
6. Upgraded the rancher server and post upgrade snapshots were saved in the s3 bucket.
7. As a cluster owner able to take snapshots and the snapshots are stored in the s3 bucket.

**Comment by anupama2501** [comment]
Re opening as seeing the issue on `bab14a3` 

Snapshot errors out:
```

2022/03/10 23:44:44 [WARNING] [etcd] Failed to take one-time snapshot on host [], exit code [1]: time="2022-03-10T23:44:43Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:<>, err:Access Denied."
```

**Comment by anupama2501** [comment]
Verified on v2.6.4-rc9

1. Created a template t1 with values no override values and created a cluster with t1
2. Snapshots and restore work on the cluster
3. Created a template t2 with over ride values enabled and created a cluster with t2
4. Snapshots and restore work on the cluster.
5. Created a cluster with no templates - snapshot/restore works

rancher upgrade 2.6.3 >> 2.6.4-rc9
1. Created a template t1 with values no override values and created a cluster with t1
2. Created a template t2 with over ride values enabled and created a cluster with t2
3. Created a cluster with no templates
4. Upgraded the rancher to 2.6.4-rc9 
5. verified etcd snapshot and restore works on all the clusters.

**Comment by baskinsy** [comment]
I have this problem on a 2.6.6 new installation with a single RKE1 cluster to manage. I am using the exact same credentials to back up rancher server (local rke2 cluster) itself, and they work, so I am out of clues. 

Where I can find the logs for the etcd backups of the managed RKE1 cluster?

**Comment by mcervar** [comment]
Hi

I have the same problem: 
2022-07-12T18:02:18Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:name_of_bucket, err:Access Denied."

Rancher server version: 2.6.5
Provisioned cluster version: 1.21.13

Three scenarios tested with same configuration:
1. Creating new K8S cluster using Rancher RKE and specifying immediately etcd s3 snapshot parameters, after deployment of cluster snapshot storing on S3 storage works
2. Creating new K8S cluster using Rancher RKE, after cluster is built new config is applied for etcd s3 snapshot parameters, after deployment of cluster snapshot storing on S3 storage doesnt work with provided error above.
3. Changing configuration of existing cluster, from local storing of snapshots to using S3 storage, after cluster is reconfigured, snapshot triggered, I get above error.

Also tested access to S3 on multiple different ways and it works, so its not up to S3 side.

**Comment by mackaw** [comment]
Same problem here:
Rancher 2.6.5
Cluster version RKE v1.23.6

Error after reconfigure from local to s3 backup
failed to set s3 server: failed to check s3 bucket:backup, err:Access Denied.

**Comment by mackaw** [comment]
> I have this problem on a 2.6.6 new installation with a single RKE1 cluster to manage (provider of nodes is DO). I am using the exact same credentials to back up rancher server (local rke2 cluster) itself, and they work, so I am out of clues.
> 
> Where I can find the logs for the etcd backups of the managed RKE1 cluster?
> 
> Thank you in advance.

all backup/snapshot logs you can find in one of the rancher deployment pod

**Comment by ahmad-sadia** [comment]
Same issue on Rancher 2.6.4
Same S3 bucket/creds was accessible by rancher 2.4.3 but not in Rancher 2.6.4.

Error message: `level=fatal msg="failed to set s3 server: failed to check s3 bucket:etcd-dev-backup, err:Access Denied."`

**Comment by hugo-calado** [comment]
For anyone who is still having this issue, I was having this issue on Rancher 2.6.6 (K8's 1.23).

Upgraded to Rancher 2.6.8 and problem was solved.

**Comment by PlayMTL** [comment]
I can confirm this bug is present in 2.6.6. Like @hugo-calado said, working again in Rancher 2.6.8.
