### ISSUE TITLE
cannot add custom host

### ISSUE THREAD

**Issue by opichon** [rancher/rancher#3666]
It's impossible to add a custom host. After running the script supplied by the rancher UI, nothing happens. The host just never shows in the rancher UI hosts page.

Both rancher server and host are running a DigitalOcean "docker 1.10 on ubuntu 10.04" image.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.0` Cattle: `v0.148.0` UI: `v0.90.0` |
|Access|`github` `admin`|
|Route|`null`|

**Comment by vincent99** [comment]
We need more info like the logs from the agent container to tell you anything beyond random guesses.. Is the `rancher/server` port accessible from the host?  Is the server at least a 1gb droplet?

**Comment by opichon** [comment]
the server is a 1gb droplet. 

docker logs rancher-agent shows a long list of line slike this:

NFO: Starting agent for 6C99057D0CCB406C356A
INFO: Starting agent for 6C99057D0CCB406C356A
INFO: Starting agent for 6C99057D0CCB406C356A
INFO: Starting agent for 6C99057D0CCB406C356A
INFO: Starting agent for 6C99057D0CCB406C356A
INFO: Starting agent for 6C99057D0CCB406C356A
INFO: Starting agent for 6C99057D0CCB406C356A
INFO: Starting agent for 6C99057D0CCB406C356A
INFO: Starting agent for 6C99057D0CCB406C356A

There is nothing under/var/log/rancher in the host.

How to check if the port is accessible? 

here is the output of the server url test as per your docs:

builder@st1:~/gitlab-ci$ curl -i http://st2.united-asian.com:8080/v1
HTTP/1.1 401 Unauthorized
Content-Length: 158
Content-Type: application/json; charset=utf-8
Date: Mon, 22 Feb 2016 04:16:21 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Www-Authenticate: Basic realm="Enter API access key and secret key as username and password"
X-Api-Schemas: http://st2.united-asian.com:8080/v1/schemas

{"id":"9b8b2119-1066-425c-9e7e-de94d65bbb9b","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}

From your docs, I presume this is normal.

The server UI's Audit Log shows these records:
api.register.create | Host registration

which i take to refer to the attempt by the agent to register.

**Comment by opichon** [comment]
Now it works again with the latest agent image.
