### ISSUE TITLE
Steve should support retrieving resources in a given namespace/project

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#36685]
Currently, Steve only allows us to get all resources on a given type - it does not provide an API to allow us to request all resources in a given namespace.

The Kubernetes API itself does provide such an API and it would be helpful to the UI to have this as a tool to address performance issues.

**Comment by samjustus** [comment]
@nwmac can you please clarify or provide an example of what you would like to be able to do? e.g. a use case

**Comment by nwmac** [comment]
@samjustus This is lower priority than other items - but we'd like to show more detail on the namespace view in the UI for resources in the namespace and also for a deployed helm app we'd like to do the same - currently we have to retrieve all resources of a given type - so if we want to show pods in the namespace view, we have to get the pods for the entire cluster - this is slow for large clusters - adding being able to do this my namespace will allow us to improve the performance of these views.

Also, for a given workload like a deployment, we have to fetch all pods in the cluster and then apply the selectors to find the pods being controlled by that deployment - which we use to show status/health - fetching all pods is expensive on large clusters - if we could retrieve by namespace, we can be more efficient here.

**Comment by cmurphy** [comment]
This is already supported. For the example of retrieving pods:

All pods -> /v1/pods
Pods only in the cattle-fleet-system namespace -> /api/v1/namespaces/cattle-fleet-system/pods

Let us know if you need more help with this.

**Comment by nwmac** [comment]
Thanks @cmurphy 

I think we need documentation for Steve.

I'm assuming the request by namespace will also set up appropriate watched, so that changes are sent over the weboscket?

**Comment by cmurphy** [comment]
> I think we need documentation for Steve.

Agreed :100: But for the most part, steve is a 1:1 reflection of the k8s API, so you can mostly (not 100%) assume that what works in the k8s API works in steve, this namespace format being one example https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-uris

> I'm assuming the request by namespace will also set up appropriate watched, so that changes are sent over the websocket?

Yes, the watch will work the same way.

**Comment by nwmac** [comment]
Thanks- wasn't sure if that namespace API would cause the watches to be put in place as well. Good to know.

**Comment by richard-cox** [comment]
@cmurphy We've recently been making use of this feature and noticed a disparity between the two responses

Looking at just the top level properties 

`k8s/clusters/c-m-9jdnx2f4/v1/services`
```
apiVersion: "v1"
id: "default/kubernetes"
kind: "Service"
links: {remove: "https://localhost:8005/k8s/clusters/c-m-9jdnx2f4/v1/services/default/kubernetes",…}
metadata: {creationTimestamp: "2022-10-20T09:08:09Z",…}
spec: {clusterIP: "10.43.0.1", clusterIPs: ["10.43.0.1"], internalTrafficPolicy: "Cluster",…}
status: {loadBalancer: {}}
type: "service"
```

`k8s/clusters/c-m-9jdnx2f4/api/v1/namespaces/default/services`
```
metadata: {name: "kubernetes", namespace: "default", uid: "073d7e60-53dd-4977-bea1-c774cc0c1cf1",…}
spec: {ports: [{name: "https", protocol: "TCP", port: 443, targetPort: 6443}], clusterIP: "10.43.0.1",…}
status: {loadBalancer: {}}
```

Most importantly id, type and links are missing. For the 2.7.0 use case we've worked around this given that particular implementation. Post 2.7.0 though we would need to treat the resources returned from the namespaced requests as those returned from the none namespaced requests.

Is there anything params wise we should be adding to get the fuller steve like resource (with id, type, links, etc) rather than native k8s? Guessing it's more of a complicated BE routing issue?

**Comment by cmurphy** [comment]
@richard-cox I think I gave bad information before, there's a better way that should give you what you need.

In my example, `/api/v1/namespaces/namespacename/pods` proxies directly to the k8s API.

The same information can be retrieved through a steve-specific API `/v1/pods/namespacename `and includes links etc:

```
$ curl -s -u $TOKEN -k https://localhost:8443/v1/pods/default | jq . | head -20
{
  "type": "collection",
  "links": {
    "self": "https://localhost:8443/v1/pods/default"
  },
  "createTypes": {
    "pod": "https://localhost:8443/v1/pods"
  },
  "actions": {},
  "resourceType": "pod",
  "revision": "8067108",
  "data": [
    {
      "id": "default/test",
      "type": "pod",
      "links": {
        "remove": "https://localhost:8443/v1/pods/default/test",
        "self": "https://localhost:8443/v1/pods/default/test",
        "update": "https://localhost:8443/v1/pods/default/test",
        "view": "https://localhost:8443/api/v1/namespaces/default/pods/test"
```

Does this work? Apologies for the confusion.

**Comment by richard-cox** [comment]
Thanks @cmurphy ! I've created https://github.com/rancher/dashboard/issues/7255 to switch the existing feature over, and we'll use that new one for future features.
