### ISSUE TITLE
Steve API should allow resources to be un-watched

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#36684]
Currently, with the Steve API, when we request a list of a given resource type, it will place a watch on that resource type and send over the web socket changes to that resource list.

There is no way to tell Steve to stop watching. In some cases - e.g. cluster events - we only show those on one view and we would like to be able to control the watching, so that we don't receive updated if the user navigates to another view.

We should add an API to Steve to allow this to be done for a given resource.

**Comment by catherineluse** [comment]
There is a function for unwatching sockets but it is rarely used. https://github.com/rancher/dashboard/blob/master/plugins/steve/subscribe.js#L135

**Comment by nwmac** [comment]
@catherineluse that applies to the entire socket - I'd like to keep an existing socket open and request that Steve stops watching a specific resource type.

**Comment by cmurphy** [comment]
This should already be supported. For example, if you have started a watch for events with a message like:

:arrow_up: `{"resourceType":"event","resourceVersion":"627295"}`
:arrow_down: `{"name":"resource.start","resourceType":"event","data":{"type":"subscribe","links":{}}}`

the watch can be stopped by

:arrow_up: `{"resourceType":"event","stop":true}`
:arrow_down: `{"name":"resource.stop","resourceType":"event","data":{"type":"subscribe","links":{}}}`

Does this meet your needs?

**Comment by samjustus** [comment]
SURE-4364

**Comment by gaktive** [comment]
@rak-phillip to review the PR with @nwmac out.

**Comment by samjustus** [comment]
@rak-phillip no PR exists - just need to confirm if the exisiting capabilities meet your needs, as colleen described
