### ISSUE TITLE
Cluster state changes to Provisioning when a worker node is deleted in an RKE2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36689]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `11a7451`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.9+rke2r1`
- Cluster Type (Local/Downstream): RKE2 do node driver cluster - 1 etcd, 1 cp, 1 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin/Standard user

**Describe the bug**
Cluster state changes to Provisioning when a worker node is deleted in an RKE2 cluster

---

**To Reproduce**

- Deploy an RKE2 cluster - 1 etcd/ 1 cp and 2 worker nodes
- Scale down a worker node or click on `-`
- The cluster state changes to `Provisioning` and come back up Active.
- Rancher Logs:
```
2022/02/13 22:12:28 [INFO] rkecluster fleet-default/sowmya-cilium: provisioning control plane node(s) sowmya-cilium-pool2-5c4666f5cd-pqs2k
2022/02/13 22:12:28 [INFO] rkecluster fleet-default/sowmya-cilium: provisioning control plane node(s) sowmya-cilium-pool2-5c4666f5cd-pqs2k: waiting for plan to be applied
2022/02/13 22:12:29 [INFO] rkecluster fleet-default/sowmya-cilium: provisioning control plane node(s) sowmya-cilium-pool2-5c4666f5cd-pqs2k: waiting for plan to be applied
2022/02/13 22:12:33 [INFO] Machine rke-machine.cattle.io/v1, Kind=DigitaloceanMachine sowmya-cilium-pool3-f6fbdd55-6bvb4 has already been deleted
2022/02/13 22:12:33 [ERROR] error syncing 'fleet-default/sowmya-cilium-pool3-f6fbdd55-6bvb4': handler machine-provision-remove: Operation cannot be fulfilled on digitaloceanmachines.rke-machine.cattle.io "sowmya-cilium-pool3-f6fbdd55-6bvb4": StorageError: invalid object, Code: 4, Key: /registry/rke-machine.cattle.io/digitaloceanmachines/fleet-default/sowmya-cilium-pool3-f6fbdd55-6bvb4, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 83884366-0bda-4da5-b9cd-0f12d4a2931e, UID in object meta: , requeuing
2022/02/13 22:12:33 [ERROR] error syncing 'fleet-default/sowmya-cilium-bootstrap-template-x9s5k': handler rke-machine: failed to delete fleet-default/sowmya-cilium-bootstrap-template-x9s5k-machine-plan rbac.authorization.k8s.io/v1, Kind=Role for rke-machine fleet-default/sowmya-cilium-bootstrap-template-x9s5k: roles.rbac.authorization.k8s.io "sowmya-cilium-bootstrap-template-x9s5k-machine-plan" not found, requeuing
2022/02/13 22:12:33 [ERROR] Reconciler error: machines.cluster.x-k8s.io "sowmya-cilium-pool3-5bdd85bc86-2cwpf" not found
2022/02/13 22:12:34 [INFO] Deleted cluster node machine-j25md [sowmya-cilium-pool3-f6fbdd55-6bvb4]
2022/02/13 22:12:34 [INFO] rkecluster fleet-default/sowmya-cilium: provisioning control plane node(s) sowmya-cilium-pool2-5c4666f5cd-pqs2k: waiting for plan to be applied
2022/02/13 22:12:48 [ERROR] Error during subscribe websocket: close sent
2022/02/13 22:12:53 [INFO] rkecluster fleet-default/sowmya-cilium: provisioning control plane node(s) sowmya-cilium-pool2-5c4666f5cd-pqs2k: waiting for plan to be applied
2022/02/13 22:12:53 [INFO] rkecluster fleet-default/sowmya-cilium: reconciliation complete
2022/02/13 22:12:53 [INFO] rkecluster fleet-default/sowmya-cilium: reconciliation complete
```
---

**Expected Result:**
- Cluster state should remain Active.
- On an RKE1 cluster, cluster state remains Active, when a snapshot is triggered or when a worker node is deleted.

**Comment by snasovich** [comment]
Adding `release-note` label on it for now as we may want to call out this behavior. Unlikely we will have enough time to fix it (and have it work reliably).

**Comment by snasovich** [comment]
Moving to Blocked until we have a decision on https://github.com/rancher/rancher/issues/36993

**Comment by thedadams** [comment]
The cluster will go into a Provisioning or Updating state whenever a new plan needs to be delivered to the downstream cluster. The plan does change in the case of deleting a worker node. I'll explain.

In order to ensure we can restore the cluster YAML on a snapshot restore, (most of) the cluster spec is stored in a configmap  on the dowstream cluster. That way, when a snapshot is created, the cluster spec that we need is in the snapshot so it can be restored if the user chooses to do so. The piece of the cluster spec that changes in the is case is the quantity for the worker node pool.

The configmap is passed to the downstream cluster via the node plan. When a new node plan is applied, then the cluster will go into a Provisioning or Updating state. This is the long way of saying: this is expected in this case for RKE2 clusters.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head b8cbc1a
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE node driver cluster

----------

### Testing: ###

Tested this issue with the following steps:
1. Deploy an RKE2 cluster - 1 etcd/ 1 cp and 2 worker nodes
2. Scale down a worker node or click on -
3. The cluster state changes to Provisioning and come back up Active.

**Result** - Pass
As explained in previous comment, the cluster does go into `Updating` state and there are no errors in the Rancher logs. The cluster is able to come back up Active after removing worker node is complete.
![image.png](https://zube.io/files/rancher/bc48a938854184b136846f5a9bc34421-image.png)
