### ISSUE TITLE
Info message displayed multiple times on the UI when an etcd snapshot creation is in progress

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36698]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `e93a53c`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.10+rke2r1`
- Cluster Type (Local/Downstream): Downstream DO Node driver cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

   
**Describe the bug**
Info message displayed multiple times on the UI when an etcd snapshot creation is in progress

**To Reproduce**

- Deploy a cluster - 3 etcd, 1 control plane, 3 worker nodes
- After cluster has come up Active, take a manual snapshots
- `waiting for etcd snapshot` is displayed multiple times (number of etcd nodes present on the cluster)

<img width="966" alt="Screen Shot 2022-03-01 at 10 35 51 AM" src="https://user-images.githubusercontent.com/26032343/156231941-c92b7755-bddb-4af9-9039-f1ad23621d74.png">

**Expected:**
The message be displayed only one time irrespective of the number of etcd nodes in the cluster

**Comment by snasovich** [comment]
@sowmyav27 , I see it as a cosmetic issue and given where we're with the timeline it will probably fall into 2.6.5 (unless @Oats87 magically fixes it while fixing something else related to etcd snapshots).

**Comment by Oats87** [comment]
This is cosmetic and actually somewhat desired, if anything, I will change the message to state which node it is waiting for an etcd snapshot on.

**Comment by Oats87** [comment]
The behavior has been changed to now show the node that the snapshot is being taken on. This is what should be validated, i.e. `waiting for etcd snapshot on node <node>, waiting for etcd snapshot on node <node>`

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 0ad0def
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 DO node driver

----------

### Testing: ###

Tested this issue with the following steps:

1. Deploy a cluster - 3 etcd, 1 control plane, 3 worker nodes
2. After cluster has come up Active, take a manual snapshots
3. Check status of nodes 

**Result** - Pass

Rancher is now showing what node that the snapshot is being taken on and is not displayed multiple times.

![image.png](https://zube.io/files/rancher/7b68e71bae6eb73f5e2ce870eda706f0-image.png)
