### ISSUE TITLE
[rke2 snapshots] age of existing snapshots changes as new ones are taken

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36697]
**Rancher Server Setup**
- Rancher version: v2.6-head e93a53c
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):n/a
- Proxy/Cert Details:self signed

**Information about the Cluster**
- Kubernetes version:1.21.10+rke2r1
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):any

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): admin

   
**Describe the bug**
if a new snapshot is taken of a cluster, existing snapshot(s) have their age reset.

**To Reproduce**
 
* deploy an rke2 snapshot
* once the cluster is active, take a snapshot
* give it some time, maybe deploy a test workload, and take another snapshot

**Result**
* first snapshot age changes to match the new snapshot age

**Expected Result**

snapshot age should be tied to each snapshot taken

**Screenshots**
<img width="321" alt="Screen Shot 2022-03-01 at 10 21 24 AM" src="https://user-images.githubusercontent.com/16691014/156226571-c300bcf7-ad49-4b7a-a4d1-9d23db894f52.png">

**Comment by Oats87** [comment]
Should be resolved through: https://github.com/rancher/rancher/pull/36707

**Comment by snasovich** [comment]
Per the comment and the fact that linked PR this should be fixed already, moving To Test.

**Comment by thedadams** [comment]
Verified the fix on Rancher v2.6-head (99974f0)
- Deployed an RKE2 cluster and waited for cluster to become active
- Took an on-demand snapshot
- Deployed a workload on the downstream cluster
- Took another on-demand snapshot
- Waited a few minutes and took another on-demand snapshot
- Waited for a recurring snapshot
- Took another on-demand snapshot

The age of each snapshot were not updated as expected.
![Screen Shot 2022-03-15 at 17 05 59](https://user-images.githubusercontent.com/3682717/158491885-e611b933-682a-48be-b58a-bcd3e35f04d8.png)

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head d604b7e
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: EC2 RKE2 aws node driver
----------

### Testing: ###

Tested this issue with the following steps:
1. deploy an rke2 snapshot
2. once the cluster is active, take a snapshot
3. give it some time, maybe deploy a test workload, and take another snapshot

**Result** - Pass
Multiple snapshots were taken and all ages of existing snapshots were preserved
![image.png](https://zube.io/files/rancher/5194ee2e90237b23cb4467310d7efe97-image.png)
