### ISSUE TITLE
[rke2] etcd snapshot is not taken once cluster reaches `active` state (we should have parity with rke1 behavior)

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36695]
**Rancher Server Setup**
- Rancher version: v2.6-head(e93a53c)
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):n/a
- Proxy/Cert Details:self signed

**Information about the Cluster**
- Kubernetes version:v1.21.10+rke2r1
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): any 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): admin

   
**Describe the bug**

on a cluster if recurring snapshots are enabled, when the cluster comes up Active after provisioning, first recurring snapshot isn’t happening. Expected: First recurring snapshot should take place after cluster comes up Active to be in parity with how RKE1 is working

**To Reproduce**
* provision an rke2 downstream cluster with etcd snapshots enabled
* wait for the cluster to provision

**Result**
snapshot is not taken once cluster is active

**Expected Result**

First recurring snapshot should take place after cluster comes up Active to be in parity with how RKE1 is working

**Screenshots**

**Additional context**
as stated, this is not currently in parity with rke1

**Comment by Oats87** [comment]
I believe the issue with this is the default retention policy we define for etcd snapshots is `0 */5 * * *` which would be every 5th hour.... 

RKE1 is set up to take a snapshot every 12 hours starting from when the cluster is provisioned.

**Comment by Oats87** [comment]
Closing this issue as we have decided that we do not need to mimic this behavior from RKE1.
