### ISSUE TITLE
No snapshots are taken when RKE2 cluster names are long

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36696]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `e93a53c`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.10+rke2r1`
- Cluster Type (Local/Downstream): Downstream DO Node driver cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

   
**Describe the bug**

**To Reproduce**

- Deploy a cluster with name `sowmya-new-etcd-snapshot-backup-restore`
- Node pool names are pool1, pool2 and pool3 --> 3 etcd/1 cp and 3 worker nodes
- When cluster comes up Active, take a snapshot.
- No snapshots are seen on Rancher UI
- Error in Rancher logs: `2022/03/01 18:14:28 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: rkecluster fleet-default/sowmya-new-etcd-snapshot-backup-restore: error while creating etcd snapshot fleet-default/sowmya-new-etcd-snapshot-backup-restore-on-demand-sowmya-0b5fd6: ETCDSnapshot.rke.cattle.io "sowmya-new-etcd-snapshot-backup-restore-on-demand-sowmya-0b5fd6" is invalid: metadata.labels: Invalid value: "on-demand-sowmya-new-etcd-snapshot-backup-restore-pool1-a57751e3-l9r9l-1646158340": must be no more than 63 characters, requeuing`

**Expected result:**
Snapshots should be taken even when the cluster name is long.

**Comment by Oats87** [comment]
Should be resolved by: https://github.com/rancher/rancher/pull/36707

**Comment by rosskirkpat** [comment]
https://github.com/rancher/dashboard/issues/5214

**Comment by sowmyav27** [comment]
**On 2.6head commit id: `4df221`**

- Deploy a cluster with name `sowmya-new-etcd-snapshot-backup-restore`
- Node pool names are pool1, pool2 and pool3 --> 3 etcd/1 cp and 3 worker nodes
- When cluster comes up Active, take a snapshot.
- Snapshots are taken in the cluster
<img width="1447" alt="Screen Shot 2022-03-07 at 1 10 44 AM" src="https://user-images.githubusercontent.com/26032343/156939362-c0cd9a00-c3b3-4995-84b6-a51df7fd6ab0.png">
