### ISSUE TITLE
Service upgrade: service link lost when upgrading a linked service

### ISSUE THREAD

**Issue by rdigiorgio** [rancher/rancher#3669]
It seems that rancher looses service links in case of upgrade using web client: 
- I have a _web-service-v1_ linked to a _mysql-service-v1_.
- Let's say I upgrade _web-service-v1_ to _web-service-v2_, everything works as expected.
- Now, I am upgrading _mysql-service-v1_ to _mysql-service-v2_, everything works as expected too.
- I want to upgrade my _web-service-v2_ to _web-service-v3_, and when using web client, it seems to have lost the link to mysql, showing nothing in service links.

So internal network links were updated with success, but something seems to have been lost.
I did not try upgrading using rancher-compose CLI.

Version:
Rancher	v0.51.0
Cattle	v0.130.0
User Interface	v0.78.0
Rancher Compose	v0.7.0

Steps: 
Have two services, _web_ and _db_, _web_ being linkd to _db_.
Upgrade _db_ service.
Try to upgrade _web_.

Results: 
Web interface does not put _db_ in _web_ service links.

Expected:
Web interface should set _db_ as a service link to _web_.

**Comment by deniseschannon** [comment]
This seems like it might be #1389, which was fixed in v0.56.0+.

Do you have multiple environments? And are you sure that hte link is lost or is it just in the UI?

**Comment by rdigiorgio** [comment]
Yes, I do have multiple environments, 4 actually. It might indeed only be a UI bug, I will try to investigate a bit more when I have some time, but this is not a blocker.

**Comment by deniseschannon** [comment]
@rdigiorgio I believe this is #1389 as you are using an older release with multiple environments. This issue has now been fixed in the latest release (v0.59.1). It is just a UI bug. 

I will close and if you see this UI issue with later releases, please let me know.
