### ISSUE TITLE
Persist data in Rancher Server

### ISSUE THREAD

**Issue by bscott** [rancher/rancher#367]
The Rancher Server host restarted and I lost all Rancher Data. How should we persist data in Rancher Server with Config data.

https://registry.hub.docker.com/u/rancher/server/

**Comment by cloudnautique** [comment]
We are getting asked this a lot lately, and will be doing a better job of making it more visible. For now there is a write up in issue #302. Hopefully that helps

**Comment by ibuildthecloud** [comment]
The rancher/server image persists it data by default in a docker volume.  A mere restart of the container should not loose data, but if you restart your host and you have it setup to delete the existing rancher/server and not use volumes-from then you will loose data.

**Comment by cusspvz** [comment]
Well, I'm setting up from the ground a rancher server and data persistence on future server image upgrade was the first thing that come up.

Launch an image just for volume handling, i will call it `rancher-server-data`:
```bash
docker run -d --name=rancher-server-data rancher/server true
# true will say docker that the image exited successfully, container will stop but volumes will be kept
```

Now every time you need to launch a container with that data:
```bash
docker run -d --restart=always --name=rancher-server --volumes-from=rancher-server-data rancher/server:0.39.0
```

Additionally we use [btsync](https://github.com/cusspvz/btsync.docker) for backing up volumes that doesn't include data management features.

Hope it helped. :)

**Comment by kaos** [comment]
I think this has been resolved and documented now.. ;)
