### ISSUE TITLE
Rancher slowness, High Mem and Cpu on pods

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#36702]
SURE-4188

**Rancher Server Setup**
Rancher Cluster:
Rancher version: v2.6.2
Number of nodes: 3
Node OS version: RHEL 7.9

Downstream Cluster:
Number of Downstream clusters: 3
Node OS: RHEL
RKE/RKE2/K3S version: RKE2 v1.21.5+rke2r2
Kubernetes version: v1.2
   
**Describe the bug**
Rancher performance is slow. Login sometimes work, sometimes not.  Rancher cluster consists of three nodes (2 cpus, 24gb ram). Rancher pods were consuming a lot of cpu and memory. Deleting the pods didn't solve the problem . After scaling the cpus to 4 and memory to 48GB (required a reboot) the problem was gone after a while but is back. Occured 2 times so far

**To Reproduce**
n/a

**Result**
1000s of will not create impersonation account on cluster in Rancher pods. See 45758 rolebindings which is abnormal.

**Expected Result**
No slowness in Rancher and no warning logs.

**Additional context**
Rancher nodes are way above hardware requirements (https://rancher.com/docs/rancher/v2.6/en/installation/requirements/#cpu-and-memory).

see logs in jira issue

**Comment by cmurphy** [comment]
Created subissues for this topic:

https://github.com/rancher/rancher/issues/39215
https://github.com/rancher/rancher/issues/39216
https://github.com/rancher/rancher/issues/39217
https://github.com/rancher/rancher/issues/39218
https://github.com/rancher/rancher/issues/39219

**Comment by samjustus** [comment]
closing and will track via above issues
