### ISSUE TITLE
Intermittent API errors when importing EKS clusters with terraform

### ISSUE THREAD

**Issue by annablender** [rancher/rancher#36700]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Docker localhost, Docker on a DO node

**Information about the Cluster**
- Kubernetes version: 1.21.9
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported EKS downstream

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

Admin user
   
**Describe the bug**

When running Rancher 2.6-head (2.6.3) in Docker and trying to import an existing EKS cluster using terraform, the imports hangs forever in the Rancher UI with the message `Waiting for API to be available.` 

![image](https://user-images.githubusercontent.com/12955547/156240063-96cea76e-2ec2-4ee3-ad5e-2ac0b414a290.png)

Cluster mgmt config used `agentImage: rancher/rancher-agent:v2.6-e4f6f4ebd590a55871ce1798c9cf03dc731799bc-head` to deploy the cluster agent on the downstream cluster which is correct (vs `agentImage: master-head` which is outdated) but Conditions showed:

```
Ready	        False      45 mins ago	[Disconnected] Cluster agent is not connected
Reconciling	True	45 mins ago	[Reconciling]
``` 

I debugged this issue with @kinarashah and we have a suspicion that the cluster agent failed to deploy, but was unable to look at the cluster agent logs due to EC2 permissions. This issue appears to be intermittent and has popped up during Rancher setups on my local machine as well.

**To Reproduce**
 

* Run `rancher/rancher:v2.6-head` in Docker on a DO node
* Access the local server at https://<DO node IP>
* Download the kubeconfig
* Import an EKS cluster into Rancher using terraform; wait and watch the cluster management UI

Terraform config
```
terraform {
  required_providers {
    rancher2 = {
      source = "terraform.example.com/local/rancher2"
      version = "1.0.0"
    }
  }
}

provider "rancher2" {
  api_url    = "https://<DO node IP>"
  token_key = "<Rancher API bearer token>"
  insecure = true
}

resource "rancher2_cluster" "bar" {
  name = "ablender-eks-test"
  description = "Terraform EKS cluster"
  eks_config_v2 {
    cloud_credential_id = "cattle-global-data:<Rancher AWS cloud credential>"
    region = "us-east-2"
    imported = true
  }
}
```

**Result**

The Rancher UI hangs forever with `Waiting for API to be available` and downstream cluster is not accessible.

**Expected Result**

The cluster should be imported and able to be accessed.

**Comment by timhaneunsoo** [comment]
This is issue is reproducible on 2.6-head 1d2b746

**Comment by annablender** [comment]
Here are some of @kinarashah's debug notes for the issue.

_In order to debug this, we'd add a simple imported cluster (RKE or RKE2, not EKS) and see if it reproduces for all imported clusters. If it does, it probably is some bug that we need to fix in Rancher itself._

This error may be related to our recent web socket issues.

Websocket debug session:

1. SSH into one of the cluster nodes
2. Check cluster agent logs by running `docker ps` and `docker logs` on the agent named like k8s_cluster-register_cattle-cluster-agent....
3. Check if this error/similar is there `time="2022-02-28T23:09:48Z" level=error msg="Failed to dial steve aggregation server: websocket: bad handshake"`

Could not complete these steps due to EC2 permissions, but if anyone else debugs this issue please run through these notes to check for web socket issues.

I also recently realized that running an ngrok session with `grok http 8080` routes downstream cluster traffic to an insecure Rancher local server. That may be the reason why I was intermittently seeing the cluster agent fail to deploy. Am currently investigating this issue.

**Comment by annablender** [comment]
@snasovich Could not reproduce the issue on rancher 2.6-head with `ngrok http 8080.` EKS cluster imported successfully so a malformed ngrok setup is not the issue.

**Comment by timhaneunsoo** [comment]
Here are the repro steps for when I ran into the error:
1. Create EKS cluster in AWS
2. Use terraform to import cluster into Rancher
  - Terraform config file
```
terraform {
  required_providers {
    rancher2 = {
      source = "terraform.example.com/local/rancher2"
      version = "1.0.0"
    }
  }
}

provider "rancher2" {
  api_url    = "https://<DO node IP>"
  token_key = "<Rancher API bearer token>"
  insecure = true
}

resource "rancher2_cluster" "bar" {
  name = "tim-eks"
  description = "Terraform EKS cluster"
  eks_config_v2 {
    cloud_credential_id = "cattle-global-data:<Rancher AWS cloud credential>"
    region = "us-east-2"
    imported = true
  }
}
```
3. Check Rancher to see EKS cluster being imported
4. Cluster status is stuck in Waiting
  - Error: `failed to communicate with cluster: Unauthorized` with `Ready` condition is `False` with `[Disconnected] Cluster agent is not connected` as the message
![Screen Shot 2022-03-04 at 12.13.06 PM.png](https://zube.io/files/rancher/4a48a4d08a5cb8802cebbe5dcda72514-screen-shot-2022-03-04-at-12-13-06-pm.png)

**Comment by annablender** [comment]
Could also not reproduce the issue on rancher-2.6 with `ngrok http https://localhost:8443` as expected. I'm currently working on importing a generic RKE1 cluster on DO into Rancher, and see if that throws me any errors about being disconnected from the cluster agent. There's also a known issue with Rancher using the `master-head` cluster agent image, which is outdated and not compatible with Kubernetes 1.22. I recently updated my dev setup to use the rancher/rancher-agent: cluster agent image, so this may just be a bug with using master-head image when trying to import clusters. I will also look into this.

**Comment by annablender** [comment]
Repro success! I was able to repro this issue for imported EKS clusters using the Rancher UI, but not for imported EKS clusters into Rancher using Terraform.

The issue here does appear to be that trying to import an EKS cluster using the Rancher UI throws an `Waiting for API to be available` error forever if the default downstream cluster agent `master-head` is used. If the cluster agent `v2.6-head` is used, the import is successful.

Repro steps
1. Run Rancher v2.6-head in Goland with `CATTLE_SYSTEM_AGENT=rancher/rancher-agent:master:head`
2. Import an EKS cluster into Rancher using the UI
3. See the `Waiting for API to be available` error

![image](https://user-images.githubusercontent.com/12955547/157278583-5cc75e7b-5194-490f-bf7f-070161c19db6.png)

4. Stop Rancher 
5. Set `CATTLE_SYSTEM_AGENT=rancher/rancher-agent:master:head` and rerun Rancher
6. Try to import the EKS cluster again and it will be successful

![image](https://user-images.githubusercontent.com/12955547/157278803-cd7591b7-262e-4a4a-b95a-bacfb4102e5b.png)

**Comment by annablender** [comment]
This issue is probably fixed in this PR https://github.com/rancher/rancher/pull/36780, and can be tested by QA. Note to test both an import using both Terraform and the Rancher UI.

**Comment by annablender** [comment]
## Testing template

#### Root cause

Cluster agent `master-head` deployed onto the EKS cluster node.
 
#### What was fixed, or what changes have occurred

Fixed in PR https://github.com/rancher/rancher/pull/36780. This sets the cattle agent version to v2.6-head instead of the outdated version `master-head.` 

#### Areas or cases that should be tested

1. Run Rancher v2.6-head
2. Import an EKS cluster using Terraform
3. Import an EKS cluster using the Rancher UI
4. Verify that both imports completed successfully and the cluster agent was able to be deployed
 
#### What areas could experience regressions ?

N/A
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head e4af246
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###

Tested this issue with the following steps:
1. Run Rancher v2.6-head
2. Import an EKS cluster using Terraform
3. Import an EKS cluster using the Rancher UI
4. Verify that both imports completed successfully and the cluster agent was able to be deployed

**Result** - Pass

Import EKS cluster using Terraform and Rancher UI were both successful.

Import using Terraform
![Screen Shot 2022-03-10 at 6.09.31 PM.png](https://zube.io/files/rancher/cad3187a31a79acdc6d86e2403244e92-screen-shot-2022-03-10-at-6-09-31-pm.png)

Import using Rancher UI
![Screen Shot 2022-03-10 at 6.10.29 PM.png](https://zube.io/files/rancher/8c093585436868e2a424c5b5a2e2df86-screen-shot-2022-03-10-at-6-10-29-pm.png)

**Comment by bishal7679** [comment]
Hello @a-blender I am accessing Rancher UI through docker in `localhost:80` and I don't know where my rancher/rancher agent is running. I think it is not running. Where Can I run rancher agent so that can import all EKS cluster?? Do i have to manually run it?? If yes then where I have to run it with which command??? please help me !I am facing this error for 20 days
