### ISSUE TITLE
Deleting RKE2 custom clusters doesn't work

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#36704]
**Rancher Server Setup**
- Rancher version: v2.6-head
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.20.10+rke2r1
- Cluster Type (Local/Downstream): RKE2
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom
   
**Describe the bug**
Deleting a custom cluster doesn't work

**To Reproduce**
Provision an RKE2 custom cluster, wait for it to become active, then delete it. 

**Result**
The cluster does not delete.

**Expected Result**
The cluster should delete.

**Comment by Josh-Diamond** [comment]
# Ticket #36704 - Test Results

### With Docker and single node cluster (1 etcd, 1 control plane, 1 worker):
#### Reproduced on 2.6.4-1d2b7468851553f4b89f8af99d74305af9d1b594-head:
1. Fresh install of rancher 2.6-head
2. Created an rke2 provisioned single-node custom cluster (k8s v1.21.10+rke2r1)
3. Deleted rke2 custom cluster
4. Deletion failure - “Waiting for machine to delete” - cluster not deleted


#### Verified on v2.6-76f5fb60dec8262fcf69263de6d380ea7a4bba08-head: 
1. Fresh install of rancher 2.6-head
2. Created an rke2 provisioned single-node custom cluster (k8s v1.21.10+rke2r1)
3. Deleted rke2 custom cluster
4. No errors, results were as expected

#### Upgraded from v2.6.2 >> v2.6-76f5fb60dec8262fcf69263de6d380ea7a4bba08-head:
1. Fresh install of rancher 2.6.2
2. Created an rke2 provisioned single-node custom cluster (k8s v1.21.9+rke2r1)
3. Upgraded rancher from 2.6.2 => 2.6-head
4.  Deleted rke2 custom cluster
5. No errors, results were as expected

<img width="1467" alt="Screen Shot 2022-03-03 at 4 13 42 PM" src="https://user-images.githubusercontent.com/46494969/156805348-3dd8bbb2-8839-4ea8-a94b-859ec2734c19.png">


### With Jenkins HA rancher and 5 node rke2 cluster (1 etcd, 1 control plane, 3 workers):  Verified on 2.6.4-rc4 [chart_version] with v2.6-8ece6ae8bd73b5e3502e1b28ef22a8a6648d35f1-head:
1. Fresh install of HA rancher 2.6-head via Jenkins
2. Created an rke2 provisioned 5 node custom cluster (k8s v1.21.10+rke2r1)
3. Deleted rke2 custom cluster
4. No errors, results were as expected
