### ISSUE TITLE
RKE2 Snapshots all show different sizes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36713]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `e93a53c`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.10+rke2r1`
- Cluster Type (Local/Downstream): Downstream DO Node driver cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

**To reproduce:**
- Deploy an rke2 do cluster - 3 etcd, 3 worker and 1 cp nodes
- Enable recurring snapshot. - retention = 5 and interval = * * * * * (every minute)
- When the cluster comes up Active, take a manual snapshot
- 3 snapshots will be seen in the Snapshot page from Cluster Management.
- Wait for Recurring snapshots to take page. 
- Noticed the size of all the snapshots are different.
<img width="1410" alt="Screen Shot 2022-03-01 at 4 12 09 PM" src="https://user-images.githubusercontent.com/26032343/156323801-9e6507a9-25f4-42bc-97a7-c24ddbf17be1.png">

**Note:**

- I wasn't able to reproduce this again in my setup
- I did not have time to check on the node.

**Comment by Oats87** [comment]
This is a potential RKE2 issue.

/cc @briandowns @galal-hussein

**Comment by briandowns** [comment]
@sowmyav27 Can you try to reproduce this and see what behavior you see?

Also

Can you collect logs and see if there's any etcd compaction taking place?
Can you deploy something to the cluster and perform a restore?
Can you check the sizes on disk?

**Comment by snasovich** [comment]
Moving to "Need Info" as we need some more info from QA to investigate.

**Comment by sowmyav27** [comment]
- On a 3 node all roles RKE2 cluster, RKE2 AWS node driver cluster,
- The latest ones taken at 01.30 and 01.35, were taken after a few resources were created on the cluster.
- Noticed the size of the snapshot on all the nodes remained the same as the previous one
- Also Noticed the snapshot size were different on all the nodes

- ON node 1
```
/var/lib/rancher/rke2/server/db/snapshots# ls -ltr
total 56256
-rw------- 1 root root 14397472 Mar  7 23:56 on-demand-sowmya-aws-pool1-bb1a4a72-t5mp9-1646697404
-rw------- 1 root root 14397472 Mar  8 00:00 etcd-snapshot-sowmya-aws-pool1-bb1a4a72-t5mp9-1646697600
-rw------- 1 root root 14397472 Mar  8 01:30 on-demand-sowmya-aws-pool1-bb1a4a72-t5mp9-1646703056
-rw------- 1 root root 14397472 Mar  8 01:35 on-demand-sowmya-aws-pool1-bb1a4a72-t5mp9-1646703304
```
- On node 2
```
/var/lib/rancher/rke2/server/db/snapshots# ls -ltr
total 55344
-rw------- 1 root root 14164000 Mar  7 23:56 on-demand-sowmya-aws-pool1-bb1a4a72-q8vns-1646697404
-rw------- 1 root root 14164000 Mar  8 00:00 etcd-snapshot-sowmya-aws-pool1-bb1a4a72-q8vns-1646697600
-rw------- 1 root root 14164000 Mar  8 01:30 on-demand-sowmya-aws-pool1-bb1a4a72-q8vns-1646703056
-rw------- 1 root root 14164000 Mar  8 01:35 on-demand-sowmya-aws-pool1-bb1a4a72-q8vns-1646703303
```
- On node 3
```
/var/lib/rancher/rke2/server/db/snapshots# ls -ltr
total 55152
-rw------- 1 root root 14114848 Mar  7 23:56 on-demand-sowmya-aws-pool1-bb1a4a72-6dtd8-1646697404
-rw------- 1 root root 14114848 Mar  8 00:00 etcd-snapshot-sowmya-aws-pool1-bb1a4a72-6dtd8-1646697600
-rw------- 1 root root 14114848 Mar  8 01:30 on-demand-sowmya-aws-pool1-bb1a4a72-6dtd8-1646703052
-rw------- 1 root root 14114848 Mar  8 01:35 on-demand-sowmya-aws-pool1-bb1a4a72-6dtd8-1646703304
```
- On Rancher UI
<img width="1401" alt="Screen Shot 2022-03-08 at 6 59 20 AM" src="https://user-images.githubusercontent.com/26032343/157147720-0f792d4a-abba-4ab1-9386-850be4ac17f5.png">

**Comment by snasovich** [comment]
@briandowns , could you take a look into it and let us know if it's happens to be an RKE2 issue?

**Comment by briandowns** [comment]
@galal-hussein is going to take this on.

**Comment by snasovich** [comment]
@galal-hussein , wondering if you have any updates on this one?

**Comment by galal-hussein** [comment]
@snasovich yeah upon my investigation, I found out that different snapshots taken at the same time does indeed have different sizes on different nodes, but when checking the snapshots status I found the following:

Server 1:
```
# /tmp/etcd-download-test/etcdctl --write-out=table snapshot status /var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-ip-172-31-16-174-1649103600 
Deprecated: Use `etcdutl snapshot status` instead.

+----------+----------+------------+------------+
|   HASH   | REVISION | TOTAL KEYS | TOTAL SIZE |
+----------+----------+------------+------------+
| 8c150882 |     3377 |       2116 |     7.7 MB |
+----------+----------+------------+------------+
```
Server 2
```
# /tmp/etcd-download-test/etcdctl --write-out=table snapshot status /var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-ip-172-31-20-132-1649103600 
Deprecated: Use `etcdutl snapshot status` instead.

+----------+----------+------------+------------+
|   HASH   | REVISION | TOTAL KEYS | TOTAL SIZE |
+----------+----------+------------+------------+
| 8c150882 |     3377 |       2116 |     7.4 MB |
+----------+----------+------------+------------+
```
Server 3
```
# /tmp/etcd-download-test/etcdctl --write-out=table snapshot status /var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-ip-172-31-29-253-1649103600 
Deprecated: Use `etcdutl snapshot status` instead.

+----------+----------+------------+------------+
|   HASH   | REVISION | TOTAL KEYS | TOTAL SIZE |
+----------+----------+------------+------------+
| 8c150882 |     3377 |       2116 |     7.5 MB |
+----------+----------+------------+------------+
```
So as you can see all the snapshots have the same number of keys and the same revision, so I did restore the snapshots in a temp data dir to investigate more and I found out that the db file located in `<etcd-data-dir>/member/snap/db` has different sizes, this file contains the main etcd content, applied to a specific point of the Raft log The better bolt storage is physically organized as a b+tree which has different leafs, upon digging deeper I found the following:

Server 1
```
gobin --run go.etcd.io/bbolt/cmd/bbolt stats /tmp/etcddata/member/snap/db 
Aggregate statistics for 10 buckets

Page count statistics
	Number of logical branch pages: 9
	Number of physical branch overflow pages: 0
	Number of logical leaf pages: 505
	Number of physical leaf overflow pages: 253
Tree statistics
	Number of keys/value pairs: 2117
	Number of levels in B+tree: 3
Page size utilization
	Bytes allocated for physical branch pages: 36864
	Bytes actually used for branch data: 17073 (46%)
	Bytes allocated for physical leaf pages: 3104768
	Bytes actually used for leaf data: 2350009 (75%)
Bucket statistics
	Total number of buckets: 10
	Total number on inlined buckets: 9 (90%)
	Bytes used for inlined buckets: 1131 (0%)
```
Server 2:
```
# gobin --run go.etcd.io/bbolt/cmd/bbolt stats /tmp/etcddata/member/snap/db 
Aggregate statistics for 10 buckets

Page count statistics
	Number of logical branch pages: 9
	Number of physical branch overflow pages: 0
	Number of logical leaf pages: 500
	Number of physical leaf overflow pages: 252
Tree statistics
	Number of keys/value pairs: 2117
	Number of levels in B+tree: 3
Page size utilization
	Bytes allocated for physical branch pages: 36864
	Bytes actually used for branch data: 16908 (45%)
	Bytes allocated for physical leaf pages: 3080192
	Bytes actually used for leaf data: 2349929 (76%)
Bucket statistics
	Total number of buckets: 10
	Total number on inlined buckets: 9 (90%)
	Bytes used for inlined buckets: 1131 (0%)
```
As you can see the number of key/value pairs has the same number 2117 which is the important part which indicates the same data between snapshots, my guess is that different sizes are related to different metadata between nodes and how they branch the pages, I couldn't dig more deeper than that, but as far as I can see from the integrity check and hash of the snapshots, they are all should be the same in terms of data within.

**note**: I did post a question in Kubernetes slack in etcd channel asking for further details but still didnt get a response yet.

**Comment by snasovich** [comment]
@galal-hussein , thank you for the detailed investigation (though initial report's size discrepancy was much larger if I understand correctly (repro from Sowmya was much closer though)). Keep us posted if you hear back to your question from k8s Slack.
@Oats87 @thedadams @sowmyav27, FYI

**Comment by snasovich** [comment]
@galal-hussein , just wondering if you've heard back re: your question in k8s Slack?

**Comment by snasovich** [comment]
As mentioned in the previous comment, closing as "working as expected".
