### ISSUE TITLE
User can login without password while ldap auth enabled

### ISSUE THREAD

**Issue by akafrmn** [rancher/rancher#3672]
Version: 0.59

Steps: 
1. Enable ldap authorization
2. Login with ldap credentials
3. Logout
4. Type only user login
5. Try to login -> exception with "Username or Password incorrect."
6. Try to login, without password, again.
7. Voila! Authorized.

Seems issue comes from auth mechanism in cattle. 

Results: 
Anyone can login to any account if it was already loggined previously :(

Expected:

"Username or Password incorrect" while triyng login with empty password field

**Comment by vincent99** [comment]
Sigh.. PR forthcoming.  It works the first time (5) because if you never focus the password field is still null and the UI sends the string `"null"` as the password.  The 2nd time (6) it's empty string.

**Comment by deniseschannon** [comment]
Verified the fix works with a fresh install and upgraded setup using v0.59.1-rc1.

Note: For the upgraded setup, when I refreshed the browser (if I was already logged in), it took awhile before I was actually logged into Rancher.

**Comment by akafrmn** [comment]
Thnx!

**Comment by kaos** [comment]
@vincent99 out of curiosity, how come `InitialLdapContext` doesn't bail when password is the empty string?

**Comment by vincent99** [comment]
@kaos Dunno, that's in the ldap library and not our code, but it treats no/empty password as no authentication was passed.

@akafrmn For future reference, the right thing to do here would have been to communicate this to us privately so we could have a release published before disclosing it.  People have publicly-accessible installations and you put them at risk by just posting this in the open.

@deniseschannon we should add a section in the readme with an email address.

**Comment by akafrmn** [comment]
@vincent99 Sure in future references I`ll use more private way. Thnx!
