### ISSUE TITLE
[2.6.3] Download rancher-agent arm64 image but got amd64 image

### ISSUE THREAD

**Issue by east4ming** [rancher/rancher#36724]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s v1.21.7+k3s1
- Proxy/Cert Details: no proxy; public 1year cert

**Information about the Cluster**
- Kubernetes version: v1.21.7+k3s1
- Cluster Type (Local/Downstream):both v1.21.7+k3s1
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): imported Raspberry Pi v1.21.7+k3s1 cluster

**User Information**
- What is the role of the user logged in? Admin

   
**Describe the bug**
Download rancher-agent arm64 image but got amd64 image。
After apply rancher-agent yaml，Downstream Raspberry Pi v1.21.7+k3s1 cluster download arm64 image，but got amd64 image。

**To Reproduce**
To find out reason, I manually with：

```bash
docker pull registry.cn-hangzhou.aliyuncs.com/rancher/rancher:v2.6.3 --platform linux/arm64
```
still got amd64 image. 

This is image inspect screenshot:
![2f736631f114fb532c204aec626b759](https://user-images.githubusercontent.com/13358726/156482759-38b8a297-1ddb-4b71-81f5-49d8d0f6112a.png)

And the image running with go format error. (wrong arch）

**Result**

**Expected Result**
Got the right arm64 rancher-agent v2.6.3 image

**Screenshots**
![2f736631f114fb532c204aec626b759](https://user-images.githubusercontent.com/13358726/156482759-38b8a297-1ddb-4b71-81f5-49d8d0f6112a.png)

**Additional context**
no proxy; no mirror.

**Comment by niusmallnan** [comment]
There is no problem with the docker hub.
```
docker pull rancher/rancher:v2.6.3 --platform linux/arm64
docker inspect 3aac6 | grep Architecture
        "Architecture": "arm64",
```

This registry `registry.cn-hangzhou.aliyuncs.com` is not official. It is maintained by some engineers in China as a hobby.

**Comment by east4ming** [comment]
ok，got it
