### ISSUE TITLE
Number of snapshots change in the UI snapshot is in progress in an RKE2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36722]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `e93a53c`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.10+rke2r1`
- Cluster Type (Local/Downstream): Downstream DO Node driver cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

**Description**

- Deploy an rke2 cluster - 3 etcd, 1 cp, 3 worker nodes
- when cluster comes up Active, navigate to Snapshot Page in cluster details page from CLuster Management
- Click on Snapshot now
- cluster goes into provisioning state, and snapshots appear one by one.
- Take another snapshot, the existing snapshots are deleted from the UI and they reappear.

**Expected Result:**
Existing Snapshots should not get removed from the UI when a snapshot is in progress.

**Comment by jiaqiluo** [comment]
This bug cannot be reproduced in rancher:v2.6-head 3df76e4. However, this may have been fixed by some recent improvements for etcd snapshot on the RKE2 cluster.

Sending this back to QA for testing.

**Comment by sowmyav27** [comment]
I do not see this issue on `v2.6.4-rc61. Closing it now.
