### ISSUE TITLE
RKE2 | Custom cluster | Admin still sees machines and clusters which were deleted by a standard user/cluster owner

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36728]
**Rancher Server Setup**
- Rancher version: v2.6-head 54b740f
- Installation option (Docker install/Helm Chart): helm chart 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1
- Proxy/Cert Details: self-sined

**Information about the Cluster**
- Cluster Type (Local/Downstream): Downstream 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2 custom cluster

  
**Describe the bug**

Admin can still see machines from clusters which were deleted by a standard user (cluster owner). 
Clusters are in the "Deleting" state / Machines are in the "Running" state (screenshot admin vs standard user(cluster owner))
![waiting](https://user-images.githubusercontent.com/40282141/156498337-77dfb3e9-b13f-4812-a5d6-b364888756c2.jpg)

When logged in as the standard user (cluster owner) who created/deleted clusters they don't see clusters/machines.
![compare](https://user-images.githubusercontent.com/40282141/156498238-a99d26d3-826d-4b56-967b-37e7cd26c7f1.jpg)

**To Reproduce**
 
1. Create a standard user
2. Log in as a standard user
3. Create a RKE2 custom cluster
4. Delete the cluster
  Cluster is deleted 
  Machines are deleted
5. Log in as an admin

**Result**
Admin still sees all machines. Machines are not deleted from the backend because they are returned by `kubectl get machines`
![kubectl](https://user-images.githubusercontent.com/40282141/156498579-e89a7eaa-4a7a-4799-b4f4-f1ff32ee68dd.jpg)

**Expected Result**

Machines are deleted when a standard user deletes a cluster

**Comment by paynejacob** [comment]
This was likely fixed with this pr https://github.com/rancher/rancher/pull/36706

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Validation**
- Rancher Version:  v2.6.4-rc9
- Installation type: Helm, RKE1
- Proxy certs: BYOD valid
- Cluster Type (Local/Downstream): Downstream
If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2 custom cluster

**Steps For Validation**
1. Create a standard user
2. Log in as a standard user
3. Create a RKE2 custom cluster
4. Delete the cluster
5. Cluster is deleted
6. Machines are deleted
7. Log in as an admin

**Sanity Checks After Following the above steps**
- while logged into admin check https://<hostname>/v1/cluster.x-k8s.io.machines, there shouldn't be any signs of the rke2 custom cluster. **Pass**
- While logged into admin run `kubectl get machine -A`and notice none of the rke2 custom machines are listed. **Pass**
- View the cluster management the cluster should be gone **Pass**


**Result**
I wasn't able to reproduce this issue, I attempted 4 times on v2.6.3. However the appropriate function seems to occur when on v2.6.4-rc9 as well. As this isn't internal I am closing this issue.
