### ISSUE TITLE
v2.6 KDM - Tracking issue for K3s k8s March Patches

### ISSUE THREAD

**Issue by katran001** [rancher/rancher#36738]
This is the tracking issue for the K3s March k8s Patches. We should be checking/validating the following versions:

1.23.5
1.22.8
1.21.11

**Comment by rancher-max** [comment]
#### Validated using rancher v2.6.4 and dev-2.6 KDM

- Import previous version and upgrade to v1.23.5+k3s1, v1.22.8+k3s1, and v1.21.11+k3s is successful
- Provisioning those versions is also successful
- UI correctly defaults to v1.22.8+rke2r1, but v1.22.8+k3s1 is the default for that line, so v1.23.5+k3s1 correctly shows as experimental and the other k3s versions do not
