### ISSUE TITLE
Error adding a  ip from a private subnet to a container 

### ISSUE THREAD

**Issue by gemoya** [rancher/rancher#3673]
Hi, I am using rancher to move an environment but we have a lot of containers
with supervisord to use SSH and other services like web on ports like 8080. Also all containers have  different ips using alias from the host with commands like `ip addr add some_ip dev some_interface`,etc and they all were created with docker-compose.

Now we want to replicate this with rancher (using UI or rancher-compose)
When we try to do this rancher maps only port:port from docker-compose
by example if we have:
`example:
   image: private-registry/example:latest
   container_name: example
   ports:
      - "some_ip:22:22"
      - "some_ip:8080:8080"
   hostname: somehost.somedomain
   restart: always
   dns:
      - "dns.ip"`

but if I review the docker-compose yaml from UI of the new container it has:
` ports:
    - "22:22"
    - "8080:8080"`

Version: `v0.59.0`

Steps: 
`rancher-compose -p appstack up -d`
or simply via web UI using adding a stack editing the docker-compose.yml  on UI with
ports like '

Results:  
` ERROR [c84a5ad8-cc60-4245-ba06-13b163ba44fb:2049] [instance:180] [instance.start->(InstanceStart)] [] [cutorService-55] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [180] `

Expected:
a new container with ip:port correct

The problem is: Rancher doesn't take the ip:port and try to create the container with ports already used by the host.

Thanks

**Comment by vincent99** [comment]
Binding to specific host IPs is not supported yet.  https://github.com/rancher/rancher/issues/53

**Comment by gemoya** [comment]
+1
is there a expecting release with this feature?
