### ISSUE TITLE
SUC doesn't appear to be installed in long-named v2prov clusters 

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#36752]
SUC does not appear to be successfully installed in a `v2prov` cluster with a long cluster name. 

The `fleet-agent` has logs like:

```
time="2022-03-03T23:11:04Z" level=info msg="Deleting unknown bundle ID mcc-test-custom-three-node-managed-system-upgrade-controller, release cattle-system/mcc-test-custom-three-node-managed-system-upgra-f834d, expecting release cattle-system/mcc-test-custom-three-node-managed-system-upgrade-controller"
```

**Comment by paynejacob** [comment]
likely related to this fleet issue https://github.com/rancher/fleet/issues/523

**Comment by Jono-SUSE-Rancher** [comment]
Adding a note that this is likely blocked by that related Fleet issue that Jacob linked.

**Comment by Sahota1225** [comment]
As per discussion with Matt, moving the milestone to 2.6.6 as this issue is dependent on the https://github.com/rancher/fleet/issues/523

**Comment by snasovich** [comment]
Moving this one to 2.7 since the referenced issue got moved to 2.7.

**Comment by Sahota1225** [comment]
@Josh-Diamond - the next rancher rc will have the fleet changes and this issue can be validated with the new rancher rc

**Comment by sowmyav27** [comment]
@Sahota1225 Once fleet RC is tagged this can be verified on v2.7-head rancher

**Comment by Sahota1225** [comment]
Moving the issue to block as we are waiting for Fleet RC

**Comment by Josh-Diamond** [comment]
Ticket #36752 - Test Plan
---

To be tested on rancher `v2.7-head`:

- Scenario 1 - **NOT YET TESTED**
    - Test: `Provision rke2 + k3s clusters - [3 nodes; all roles] - w/ long cluster name`
    - Expected Result: system-upgrade-controller successfully installed; clean logs
    
- Scenario 2 - **NOT YET TESTED**
    - Test: `Provision rke2 + k3s clusters - [3 nodes; individual roles] - w/ long cluster name`
    - Expected Result: system-upgrade-controller successfully installed; clean logs

- Scenario 3 - **NOT YET TESTED**
    - Test: `Provision rke2 + k3s clusters w/ long cluster names on v2.6.8 => upgrade to v2.7-head`
    - Expected Result: Post-upgrade cluster comes up `Active`; system-upgrade-controller successfully installed; clean logs

---

Reproduced - ✅ - Friday September 16, 2022

On rancher `v2.6-82bf0001177d3963056c53136241e6e7e94eeb8a-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE2 AWS Node driver cluster w/ long cluster name
    - `jkeslar-really-long-cluster-name-goes-here`
3. Reproduced - SUC doesn't appear to be installed; dirty logs

Logs:
```logs
time="2022-09-16T22:24:30Z" level=info msg="Deleting unknown bundle ID mcc-jkeslar-really-long-cluster-name-goes-here-managed-sy-a03f8, release cattle-system/mcc-jkeslar-really-long-cluster-name-goes-here--2827d, expecting release cattle-system/mcc-jkeslar-really-long-cluster-name-goes-here-managed-sy-a03f8"
```

**Comment by snasovich** [comment]
This should be ready to test on [v2.6.9-rc1](https://github.com/rancher/rancher/releases/tag/v2.6.9-rc1) (or 2.6-head) as it includes Fleet `v0.4.0-rc3` with the https://github.com/rancher/fleet/issues/523 fixed.

Changing milestone to 2.6.9 and creating a forwardport.

**Comment by Josh-Diamond** [comment]
Ticket #36752 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.6-48b6bc6b4a6adb4fd4c623984862494cd0b70a5f-head`:

- Scenario 1 - ✅ 
    - Test: `Provision rke2 cluster - [3 nodes; all roles] - w/ long cluster name`
    - Result: system-upgrade-controller successfully installed; clean logs
    
- Scenario 2 - ✅ 
    - Test: `Provision k3s cluster - [3 nodes; all roles] - w/ long cluster name`
    - Result: system-upgrade-controller successfully installed; clean logs

- Scenario 3 - **NOT YET TESTED**
    - Test: `Provision rke2 + k3s clusters w/ long cluster names on v2.6.8 => upgrade to v2.7-head`
    - Result: Post-upgrade cluster comes up `Active`; system-upgrade-controller successfully installed; clean logs

---

Reproduced - ✅ - Friday September 16, 2022

On rancher `v2.6-82bf0001177d3963056c53136241e6e7e94eeb8a-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE2 AWS Node driver cluster w/ long cluster name
    - `jkeslar-really-long-cluster-name-goes-here`
3. Reproduced - SUC doesn't appear to be installed; dirty logs

Logs:
```logs
time="2022-09-16T22:24:30Z" level=info msg="Deleting unknown bundle ID mcc-jkeslar-really-long-cluster-name-goes-here-managed-sy-a03f8, release cattle-system/mcc-jkeslar-really-long-cluster-name-goes-here--2827d, expecting release cattle-system/mcc-jkeslar-really-long-cluster-name-goes-here-managed-sy-a03f8"
```

---

Scenario  1:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE2 AWS Node driver cluster w/ long cluster name
    - `jkeslar-really-long-cluster-name-goes-here`
3. Verified - SUC successfully installed;  clean logs

Screenshots:
![suc-proof-1](https://user-images.githubusercontent.com/46494969/191553176-7b19f1b1-0c05-4120-936d-6f560905f0c4.png)

<img width="1382" alt="Screen Shot 2022-09-21 at 8 54 00 AM" src="https://user-images.githubusercontent.com/46494969/191553282-d9bee038-55b7-4064-848e-38005092647a.png">

<img width="1390" alt="Screen Shot 2022-09-21 at 8 53 03 AM" src="https://user-images.githubusercontent.com/46494969/191553304-69644b32-1551-438d-9052-a254383bfea2.png">

---

Scenario  2:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream K3s AWS Node driver cluster w/ long cluster name
    - `jkeslar-k3s-really-long-cluster-name-here`
3. Verified - SUC successfully installed;  clean logs

Screenshots:

<img width="899" alt="Screen Shot 2022-09-21 at 10 29 47 AM" src="https://user-images.githubusercontent.com/46494969/191571998-44e1553a-18dd-4638-a3c0-a2f77a0d6845.png">

<img width="1390" alt="Screen Shot 2022-09-21 at 10 33 00 AM" src="https://user-images.githubusercontent.com/46494969/191572383-5b4efb48-597f-464c-a372-ed65ad071ea3.png">

<img width="1403" alt="Screen Shot 2022-09-21 at 10 29 04 AM" src="https://user-images.githubusercontent.com/46494969/191572435-d0c6f195-699c-4e1f-b41d-aca1d5e00d48.png">

---

Scenario  3:
1. Fresh install of rancher `v2.6.8`
2. Provision a downstream RKE2 AWS Node driver cluster w/ long cluster name
    - `jkeslar-really-long-cluster-name-goes-here`
3. Provision a downstream K3s AWS Node driver cluster w/ long cluster name
    - `jkeslar-k3s-really-long-cluster-name-here`
4. Once clusters come up `Active`, upgrade to rancher `v2.6-head`
4. Verified - SUC successfully installed;  clean logs

Screenshots:

`RKE2`
<img width="1384" alt="Screen Shot 2022-09-21 at 11 01 11 AM" src="https://user-images.githubusercontent.com/46494969/191577631-8a6cd6e6-0212-4b1f-969c-99bd30b34196.png">

`K3s`
<img width="1374" alt="Screen Shot 2022-09-21 at 11 25 39 AM" src="https://user-images.githubusercontent.com/46494969/191582106-2e17c9af-4566-4bb8-ba24-1c991c94fbb4.png">
