### ISSUE TITLE
Non-admin user does not have backupEtcd as an available action which prevents snapshot / restore snapshot

### ISSUE THREAD

**Issue by neillsom** [rancher/rancher#36757]
Related to https://github.com/rancher/dashboard/issues/5011

The issue appears to be that a standard user does not have 'backupEtcd' as an available k8s action

**As admin**
![](https://zube.io/files/rancher/f9cea1372cc29e576695c101de014a9e-admin-with-action.jpg)

**As standard user**
![](https://zube.io/files/rancher/63a0327cfb36602624c0c9b1a961b27a-standarduser-without-action.jpg)

**Non-admin user attempting to take snapshot**
![](https://zube.io/files/rancher/9a630f1bcc5c84a09281a70ccdee3fc2-403-error.jpg)

The UI team can bypass the logic to enable a standard user to have the UI 'take snapshot' and 'restore snapshot' functionality, but these will result in a 403 errors

**Comment by gaktive** [comment]
Based on the description, the 5035 link should point to Dashboard Zube, which is in fact https://github.com/rancher/dashboard/issues/5011

**Comment by MbolotSuse** [comment]
@neillsom What role does the user have on the cluster (i.e. did the user create the cluster and is the cluster owner, or where they assigned a different role after)?

**Comment by nwmac** [comment]
@MbolotSuse This works correctly for RKE2 cflusters, but not for RKE1 - if you try the same again - create a standard user and make them an owner of an RKE1 cluster, they are unable to backup or restore snapshots - they API does not provide the `backupEtcd` action metadata.

**Comment by MbolotSuse** [comment]
@nwmac Just tried this with an RKE1 cluster (v1.23.4) in digital ocean. Same results as above - I'm able to see the snapshots and take a new snapshot after clicking into the cluster. The backend, in this case, appears to be functioning as intended.

Would you mind providing more clarity on what specifically is not working (as well as what the expected result is)?

**Comment by MbolotSuse** [comment]
@nwmac That specific endpoint/property really helps - thank you for providing that detail. I'll take a look into this and see if I can figure out what is going on.

**Comment by samjustus** [comment]
SURE-4359

**Comment by MbolotSuse** [comment]
Validation Template

## Root Cause
The `canBackup` etcd function was always using the `apiContext.ID` as the `namespaceId` to check access to the `etcdbackup` resources. This was nil in some cases, causing a different access check than intended (this function should have checked access to the `etcdbackup` resources in the cluster namespace - e.x. `c-1234`). 

In addition, the CanDo function used by `canBackup` used access control which expected a resource formatted in a particular way - this was not being done, so the can do was changed to enforce the right format. 

## What was fixed, or what change have occurred
2 Changes were made:
- Code was adjusted to sometimes use the `apiContext.ID` as the namespace, and other times use the ID of the resource (that being the cluster in those cases)
- Code was adjusted to properly format the resources before passing them off to the inner access control method (new format: "apiGroup/resource")

## Areas or cases that should be tested
Cluster backup action - is it available when it should be? Is it not available when it isn't?

## What areas could experience regressions
Cluster object permissions - specifically cluster actions.

## Are the repro steps accurate/minimal?
Yes. They are provided here for convienience.

1. Run rancher/rancher:v2.6.3
2. Create a downstream RKE cluster (any version, any provider).
3. Create a new user with the standard user role.
4. Add the standard user to the downstream RKE cluster with a role of `Cluster Owner`.
5. Using the hamburger menu in the UI, go to cluster management.
6. As show in the above screenshot, click the 3 buttons on the left of the cluster name. Observe that there is no option to "Take snapshot" (but there should be, since the user is a cluster owner for this cluster and they can take a snapshot by clicking into the cluster).

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                                      |
| ------------------------- | --------------------------------------------------- |
| Rancher version           | 2.6.4                                               |
| Rancher commit link       | not applicable                                      |
| Installation option       | Helm high availability                              |
| RKE binary version used   | v1.3.8                                              |
| If Helm Chart k8s cluster | v1.21.7                                             |
| Cert Details              | ingress.tls.source=secret (certificates from files) |
| Docker version            | 20.10.7, build f0df350                              |
| Helm version              | v2.16.8-rancher1                                    |
| Downstream cluster type   | RKE1 Linode                                         |
| Downstream K8s version    | v1.22.7-rancher1-2                                  |
| Logged in user role       | Administrator & Standard User                       |
| Browser type              | Google Chrome                                       |
| Browser version           | 100.0.4896.127 (Official Build) (x86_64)            |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$OMITTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret \
  --version 2.6.4
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key
```

## Reproduction steps

1. Logged in as Administrator create a downstream RKE1 Linode cluster
2. Create a new local user with the Standard User role
3. Add the newly created user to the downstream cluster with the role `Cluster Owner`
4. Log out as the Administrator and log in as the Standard User
5. As Standard User, click `hamburger menu` -> click `Cluster Management` click the `ellipsis (three dots icon) next to the cluster name`

## Additional Info

## RESULTS

#### :white_check_mark: Expected
For the `Take Snapshot` to be listed and available when accessing this as a Standard User with Cluster Owner role

#### :x: Actual
`Take Snapshot` option was not available

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                                |
| ------------------------- | --------------------------------------------------------------------------------------------- |
| Rancher version           | v2.6-6bb6e45fba97f58443e547e2f57d2807a424467f-head                                            |
| Rancher commit link       | [6bb6e45](https://github.com/rancher/rancher/commit/6bb6e45fba97f58443e547e2f57d2807a424467f) |
| Installation option       | Helm high availability                                                                        |
| RKE binary version used   | v1.3.8                                                                                        |
| If Helm Chart k8s cluster | v1.22.7                                                                                       |
| Cert Details              | ingress.tls.source=secret (certificates from files)                                           |
| Docker version            | 20.10.7, build f0df350                                                                        |
| Helm version              | v2.16.8-rancher1                                                                              |
| Downstream cluster type   | RKE1 Linode                                                                                   |
| Downstream K8s version    | v1.22.8-rancher1-1                                                                            |
| Logged in user role       | Administrator & Standard User                                                                 |
| Browser type              | Google Chrome                                                                                 |
| Browser version           | 100.0.4896.127 (Official Build) (x86_64)                                                      |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$OMITTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=secret \
  --set rancherImageTag=v2.6-head
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key
```

## Validation steps

1. Logged in as Administrator create a downstream RKE1 Linode cluster
2. Create a new local user with the Standard User role
3. Add the newly created user to the downstream cluster with the role `Cluster Owner`
4. Log out as the Administrator and log in as the Standard User
5. As Standard User, click `hamburger menu` -> click `Cluster Management` click the `ellipsis (three dots icon) next to the cluster name`
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
`Take Snapshot` option was available


#### :white_check_mark:Actual
`Take Snapshot` option was available
