### ISSUE TITLE
vSphere CPI/CSI Version Tracking Issue

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#36764]
In order to better understand the versions of vSphere that are being packaged in both RKE and RKE2 I made this issue for tracking purposes.

### Rancher (RKE) vSphere CPI/CSI Versions
The versions of these charts are in the Rancher Apps and Marketplace

- CPI 100.1.0+up1.0.100
- CSI 100.0.1+up2.1.1
- CSI 100.1.0+up2.3.0

The new not yet released vSphere charts for 2.6.4 at the moment are CPI 100.1.1+up1.0.1 and CSI 100.1.1+up2.3.0-rancher1, which are identical to CPI 100.1.0+up1.0.100 and CSI 100.1.0+up2.3.0 except for the addition of the Windows annotations. 

Those new charts will be replaced by the charts in the PRs below which includes the windows annotations and also updates the chart to latest to add support for k8s 1.22.
- https://github.com/rancher/charts/pull/1764
- https://github.com/rancher/charts/pull/1763

----

### RKE2 vSphere CPI/CSI Versions

To find the chart versions available for RKE2 in Rancher, run:
```bash
curl -ks https://releases.rancher.com/kontainer-driver-metadata/release-v2.6/data.json | jq '.rke2.releases[] | [.version + ": " + .charts."rancher-vsphere-cpi".version + ", " + .charts."rancher-vsphere-csi".version][]'
```

```
"v1.19.16+rke2r1: , "
"v1.20.15+rke2r1: , "
"v1.21.4+rke2r2: 100.0.0, 100.0.0"
"v1.21.5+rke2r1: 100.0.0, 100.0.0"
"v1.21.5+rke2r2: 100.0.0, 100.0.0"
"v1.21.6+rke2r1: 100.0.0, 100.0.0"
"v1.21.7+rke2r2: 100.1.0+up1.0.100, 100.1.0+up2.3.0"
"v1.21.8+rke2r2: 100.1.0+up1.0.100, 100.1.0+up2.3.0"
"v1.21.9+rke2r1: 100.1.0+up1.0.100, 100.1.0+up2.3.0"
"v1.22.4+rke2r2: 100.1.0+up1.0.100, 100.1.0+up2.3.0"
"v1.22.5+rke2r2: 100.1.0+up1.0.100, 100.1.0+up2.3.0"
"v1.22.6+rke2r1: 100.1.0+up1.0.100, 100.1.0+up2.3.0"
```

**Comment by sirredbeard** [comment]
Awaiting a decision on inclusion of 1.23 in 2.6.4.

**Comment by sirredbeard** [comment]
See also https://github.com/rancher/vsphere-charts/pull/16

**Comment by sirredbeard** [comment]
This has been addressed by Jamie's work on vSphere chart versions.
