### ISSUE TITLE
Errors Config not found: //sa.kubeconfig are seen in the istio installer job when we install/upgrade to version 1.11.700

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36767]
**Rancher Server Setup**
- Rancher version: `v2.5.12`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.19.13+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: v1.20.15
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 3 worker, 1 etcd, 1 cp`
`RKE1`

**Describe the bug**
When we install istio version 1.11.700, many error logs were seen in the istioctl installer job

**To Reproduce**
1. Install istio version  1.11.700
2. From the jobs in the istio-system namespace >> istioctl installer

**Result**
```
sed: couldn't open temporary file /usr/local/app/dashboards/sedJAtq3B: Permission denied
W0304 21:18:48.084276 74 loader.go:221] Config not found: //sa.kubeconfig
configmap/istio-dashboard-11829 created
W0304 21:18:48.144195 81 loader.go:221] Config not found: //sa.kubeconfig
I0304 21:18:49.347422 81 request.go:665] Waited for 1.097438976s due to client-side throttling, not priority and fairness, request: GET:[https://<redacted>:443/apis/authorization.k8s.io/v1beta1?timeout=32s](https://10.43.0.1/apis/authorization.k8s.io/v1beta1?timeout=32s)
```

**Expected Result**
Expected not to see any error logs in the installer job

**Additional context**
Happens when upgrading istio from 1.10.4 >> 1.11.700

**Comment by MKlimuszka** [comment]
These logs are not concerning since the dashboards still get created and Istio is still functional.  Not a blocker for 2.6.4

**Comment by rayandas** [comment]
@anupama2501 Raised https://github.com/rancher/charts/pull/1795 it will fix this issue.

**Comment by anupama2501** [comment]
Verified on 2.6-head a2ef67a and 2.5.12 - no error logs seen during istio installation.
