### ISSUE TITLE
RKE2 | Custom cluster | Cluster stays in Provisioning state after adding a Windows node

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36763]
**Rancher Server Setup**
- Rancher version: v2.6-head 3659d2f
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21 and v1.22
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

  
**Describe the bug**

Cluster stays in Provisioning state after adding a Windows node even though the node is added and machine is created for it

**To Reproduce**
 
1. Create a RKE2 custom cluster (1 etcd, 1 cp, 1 worker)
2. Add a windows node 

**Result**
The cluster stays in the Provisioning state

**Expected Result**

The cluster goes into the Active state after a node is added successfully with a machine created

**Screenshots**

![cluster](https://user-images.githubusercontent.com/40282141/156814489-bdd59ebc-9a5d-4667-8283-bfe647e6ab3f.jpg)

**Additional context**

Rancher logs:
```
2022/03/04 17:01:00 [INFO] [planner] rkecluster fleet-default/win121: waiting: provisioning worker node(s) custom-249aaa0b4d98
2022/03/04 17:02:35 [INFO] [planner] rkecluster fleet-default/win122: waiting: provisioning worker node(s) custom-5f36b9e03dbd
2022/03/04 17:02:45 [INFO] [planner] rkecluster fleet-default/win122: waiting: provisioning worker node(s) custom-5f36b9e03dbd
2022/03/04 17:07:29 [ERROR] Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "cluster": the object has been modified; please apply your changes to the latest version and try again
2022/03/04 17:08:58 [INFO] [planner] rkecluster fleet-default/windows: waiting: provisioning worker node(s) custom-fc77ed38b0d9
2022/03/04 17:09:08 [INFO] [planner] rkecluster fleet-default/windows: waiting: provisioning worker node(s) custom-fc77ed38b0d9
2022/03/04 17:10:51 [INFO] [planner] rkecluster fleet-default/win121: waiting: provisioning worker node(s) custom-249aaa0b4d98
2022/03/04 17:11:01 [INFO] [planner] rkecluster fleet-default/win121: waiting: provisioning worker node(s) custom-249aaa0b4d98
```

**Comment by snasovich** [comment]
@luthermonson @rosskirkpat @phillipsj, any of you guys can take a look into it since it seems to be related to Windows?

cc: @sirredbeard

**Comment by phillipsj** [comment]
@snasovich this was due to the cluster agent that was being pulled was master-head not 2.6-head. This broke all provisioning once the 1.22 fixes where merged. @thedadams fixed that this morning.

**Comment by phillipsj** [comment]
https://github.com/rancher/rancher/pull/36780

**Comment by phillipsj** [comment]
@snasovich there was also a system-agent issue that was fixed by @Oats87

**Comment by snasovich** [comment]
Per the comments above this should now be fixed. Moving "To Test".
@sowmyav27 @slickwarren , FYI.

**Comment by phillipsj** [comment]
@snasovich this appears to be occurring again.
![image](https://user-images.githubusercontent.com/1568133/157250867-787888e6-cc44-4c9a-a8b0-72d07d28f11c.png)

The cluster is fine if you go into the explorer.

![image](https://user-images.githubusercontent.com/1568133/157250916-32f384fa-03f8-4bf5-8e93-1740b2e6ffd0.png)

**Comment by phillipsj** [comment]
@snasovich from my understanding, the probes for RKE2 provisioning haven't previously been functioning correctly. A few weeks ago this was fixed to start functioning. That is why it worked previously and I couldn't find any related issues. After talking to the Calico Windows Engineers, the Calico health probe doesn't run for host deployed Calico, which is what we do, so there isn't any expectation that it would be there. We are updating the plan being created by Rancher to account for that.

**Comment by snasovich** [comment]
@phillipsj , thank you for detailed explanation. Reassigning the issue to @luthermonson as he did the fix per linked PR.
@luthermonson , once the PR is merged and build passes, please move it to test. Thank you.

**Comment by phillipsj** [comment]
@luthermonson it isn't clearing the provisioning, but it isn't waiting on the Calico probe any longer.

![image](https://user-images.githubusercontent.com/1568133/157457000-e040b2a2-1c77-4ff2-a02e-08744762ecde.png)

**Comment by snasovich** [comment]
Assigning myself just for visibility.
@luthermonson , is this something you can look into further?

**Comment by luthermonson** [comment]
we fixed the calico probe not running on windows and now this is a deeper provisioning issue that @thedadams knows more about and we're assigning to him for the time being. let us know if we can help further but I think this is out of our wheel house @snasovich

**Comment by slickwarren** [comment]
Using v2.64-rc11, I am able to deploy a custom rke2 cluster with the following:
* k8s v1.22.7+rke2r2, windows 2022 node, 1cp, 1etcd, 1worker (linux nodes)

all pods in the system namespace are coming to an active state and the cluster is also `active`
