### ISSUE TITLE
[Bug] Rancher 2.6 is missing emptyDir from volume types.

### ISSUE THREAD

**Issue by gaby** [rancher/rancher#36760]
**Rancher Server Setup**
 
 * Rancher version: 2.6.3
 * Unsupported Storage Drivers flag is enabled.
 
 **Describe the bug**
If you create a deployment and want to add an emptyDir volume, you cannot select that from volume type dropdown

 **To Reproduce**
 
 1. Create a deployment
 2. Storage -> Add Volume
 3. emptyDir not existent
 
 **Result**
 
 **Expected Result**
 
 1. EmptyDir is available in dropdown
 2. EmptyDir name can be changed on update of an deployment when deployed from a YAML.
 
 **Screenshots**
 ![grafik](https://user-images.githubusercontent.com/3147888/131963000-bc060ea9-5b95-4f21-a2fc-cdc602310daa.png)

The `emptyDir` is an official option supported by k8s, I don't understand why Rancher had to remove this? I makes making containers with read-only filesystems more difficult. 

K8s docs: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

There was another issue that got closed for the same problem #34638

**Comment by gaby** [comment]
Anyone ?

**Comment by hanxinhang** [comment]
This issue is still present in Rancher 2.6.5

**Comment by gaby** [comment]
Still valid!

**Comment by bromine0x23** [comment]
This issue is still present in Rancher 2.6.8

**Comment by ItsReddi** [comment]
The original issue is there for over than one year, how it is possible that there is not even a response to this?

**Comment by gmanera** [comment]
Same problem.
Rancher Version: v2.6.8
K8S Version: 23.10

**Comment by kingsd041** [comment]
This issue is still present in Rancher 2.7.0

**Comment by richard-cox** [comment]
Closing as duplicate of https://github.com/rancher/rancher/issues/34638. Note - The issue is tracked in https://github.com/rancher/dashboard/issues/7533 and a solution is in progress.
