### ISSUE TITLE
Multiple etcd nodes upgrade at the same time during k8s upgrade in an RKE2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36776]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `4df2214`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.22.7+rke2r1`
- Cluster Type (Local/Downstream): Downstream - RKE2 DO 3 etcd, 2 control plane and 3 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) : admin
   
**Describe the bug**
Multiple etcd nodes upgrrade at the same time during k8s upgrade in an RKE2 cluster

**To Reproduce**
- Cluster config - 3 etcd, 2 cp and 3 worker nodes
- Create cluster and set upgrade strategy for control plane nodes nodes
- When the cluster has come up Active, edit cluster config, upgrade k8s from 1.21rke2 to 1.22 rrke2 version
- Cluster goes into provisioning state.
- one etcd node gets cordoned. 
- When k8s version of that is upgraded, two of the other etcd nodes go into coordoned state --> this is NOT expected
- Then both the control planes go into Cordoned state at the same time since the upgrade strategy was set to Unavailable control plane nodes: 2
- Then the worker nodes get upgraded successfully
- But the cluster upgrade finishes and cluster comes back up Active

**Expected Result**
etcd nodes should get upgraded one by one

**Comment by thedadams** [comment]
After discussion with the team, we are in agreement that this is not the desired behavior. Since there is no user-specified upgrade strategy for ECTD-only nodes, then Rancher should use the strategy that ectd-only nodes are upgraded one at a time.

From @Oats87:
>order of operations should be to reconcile etcd (and etcd + controlplane, and etcd + controlplane + worker, and etcd + worker) (one at a time), then control plane that aren't etcd, then worker

**Comment by snasovich** [comment]
@sowmyav27 , could you (or someone else) check if this is happening on 2.6.3 as well?

**Comment by sowmyav27** [comment]
Reproduced this issue on 2.6.3

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `024e6fa`**

- Deployed 3 etcd, 2 cp and 3 worker nodes DO RKE2 node driver cluster
- Upgraded k8s from 1.22 to 1.23 
- Etcd nodes on Cluster Management --> CLuster details page --> Status of nodes change to Provisioning and come back Active
- Etcd nodes get upgraded one by one. Then the control plane gets upgraded
