### ISSUE TITLE
Cluster goes into Provisioning state multiple times after it has finished provisioning

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36772]
**Rancher Server Setup**
- Rancher version: 2.6head commit id: `4df2214`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.22.7+rke2r1` --> Downstream cluster
- Cluster Type (Local/Downstream): Downstream RKE2 DO Node driver- etcd, 1 cp and 3 worker nodes - total 5 nodes cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin
   
**Describe the bug**
Cluster goes into Provisioning state after it has finished provisioning

**To Reproduce**

- Deploy 1 etcd, 1 cp and 3 worker nodes RKE2 cluster - `cluster1`, Network : Multus and Canal
- Wait for cluster to become active
- No other actions were performed on this cluster
- However, I performed snapshot backup and restore on other two downstream clusters in the same Rancher setup.
- Cluster 1 went into Provisioning state another time and came back up Active.

**Result**
Rancher logs show :
```
[INFO ] provisioning bootstrap node(s) sowmya-do-36505-pool1-744b6b7cdc-45m49: waiting for plan to be applied
--
1:02:45 am | [INFO ] non-ready worker machine(s) sowmya-do-36505-pool2-599dbdc775-4ggl8,sowmya-do-36505-pool2-599dbdc775-cn7h2,sowmya-do-36505-pool2-599dbdc775-jznwx
1:03:07 am | [INFO ] provisioning bootstrap node(s) sowmya-do-36505-pool1-744b6b7cdc-45m49
1:03:09 am | [INFO ] provisioning bootstrap node(s) sowmya-do-36505-pool1-744b6b7cdc-45m49: waiting for plan to be applied
1:03:23 am | [INFO ] provisioning done
1:03:59 am | [INFO ] provisioning bootstrap node(s) sowmya-do-36505-pool1-744b6b7cdc-45m49: waiting for plan to be applied
1:04:13 am | [INFO ] provisioning done
1:04:35 am | [INFO ] provisioning bootstrap node(s) sowmya-do-36505-pool1-744b6b7cdc-45m49: waiting for plan to be applied
1:04:51 am | [INFO ] provisioning done
1:18:08 am | [INFO ] provisioning bootstrap node(s) sowmya-do-36505-pool1-744b6b7cdc-45m49: waiting for plan to be applied
1:18:30 am | [INFO ] provisioning bootstrap node(s) sowmya-do-36505-pool1-744b6b7cdc-45m49
1:18:32 am | [INFO ] provisioning bootstrap node(s) sowmya-do-36505-pool1-744b6b7cdc-45m49: waiting for plan to be applied
1:18:38 am | [INFO ] provisioning control plane node(s) sowmya-do-36505-pool3-6789d5888c-m9xnb: waiting for plan to be applied
1:18:48 am | [INFO ] provisioning bootstrap node(s) sowmya-do-36505-pool1-744b6b7cdc-45m49: waiting for plan to be applied
1:19:20 am | [INFO ] provisioning control plane node(s) sowmya-do-36505-pool3-6789d5888c-m9xnb: waiting for plan to be applied
1:19:28 am | [INFO ] provisioning bootstrap node(s) sowmya-do-36505-pool1-744b6b7cdc-45m49: waiting for plan to be applied
1:20:00 am | [INFO ] provisioning control plane node(s) sowmya-do-36505-pool3-6789d5888c-m9xnb: waiting for plan to be applied
1:20:10 am | [INFO ] provisioning bootstrap node(s) sowmya-do-36505-pool1-744b6b7cdc-45m49
1:20:12 am | [INFO ] provisioning bootstrap node(s) sowmya-do-36505-pool1-744b6b7cdc-45m49: waiting for plan to be applied
1:20:28 am | [INFO ] provisioning done
```

**Expected Result**
Cluster should not go into Provisioning state multiple times after it has finished provisioning

**Note:**
It did not happen on other clusters in the setup (i have 2 other RKE2 clusters downstream)

**Comment by thedadams** [comment]
I have not been able to reproduce this issue. Here are the steps I was using:
- Provision an RKE2 cluster with 1 etcd, 1 cp, and 3 worker nodes
- Provision another cluster with a single node
- - On this second cluster I did things like take snapshot, deploy workloads, take another snapshot, and restore snapshot.
- The entire time I was messing with the second cluster, the first one stayed in an Active state.

**Comment by sowmyav27** [comment]
Blocked by - https://github.com/rancher/rancher/issues/36939

**Comment by thedadams** [comment]
I was able to reproduce this issue. Reopening.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `024e6fa`**

- Deployed 1 etcd, 1 cp and 3 worker nodes - multus, canal CNI cluster
- Cluster is up and Active.
- Cluster does not toggle between Active and Updating.
