### ISSUE TITLE
cannot install cattle-cluster-agent in tainted nodes

### ISSUE THREAD

**Issue by pgmota** [rancher/rancher#36788]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option: Helm Chart
- Proxy/Cert Details: Self-Signed +  Private CA

**Information about the Cluster**
- Kubernetes version:  v1.20.11-eks-f17b81 
-  Imported: Running kubectl apply onto an existing k8s cluster, generic 
-  Hosted: EKS
-  Infrastructure Provider: AWS
   
**Describe the bug**
Default deployment of cattle-cluster-agent fail when provisioned in tainted nodes.

**To Reproduce**
1. Import a cluster using Generic option
2. Copy the command but instead of apply it just download the manifest and change de toleration section to add your own specific config
3. Apply the manifest

**Result**
Only one replica is scheduled with tolerations config applied, the second one doesn't have the config, it's necessary edit each pod to change the configuration or remove the taints to install the agent, after that the cluster is imported and then it's possible to change the deployment throught the Rancher UI

**Expected Result**
Possibility to install the agent with tolerations at once with less manipulations of config files.

**Screenshots**

**Additional context**
Relatable issue about fleet -> https://github.com/rancher/rancher/issues/35834

**Comment by zbialik** [comment]
This  is still an issue and breaks our usage of imported EKS clusters in Rancher. All our EKS Worker Nodes are tainted and the `cattle-cluster-agent` cannot schedule now.
