### ISSUE TITLE
The nodes' state do not change to Upgrading when the cluster upgrades

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36782]
**Rancher Server Setup**
- Rancher version: 2.6head commit id: `11a7451`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.9+rke2r1`
- Cluster Type (Local/Downstream): AWS Linode node driver cluster - 1 etcd, 1 cp and 3 worker nodes. Container network - `[multus-canal]`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard user
   
**Describe the bug**
Issue with RKE2 upgrade with Upgrade strategy set

**To Reproduce**

- Deploy an RKE2 cluster.
- When the cluster is Active, Edit Config --> Modify the Upgrade strategy to

<img width="1180" alt="Screen Shot 2022-02-13 at 2 49 34 PM" src="https://user-images.githubusercontent.com/26032343/153778785-51f8f5a2-2911-4dab-9eb9-6e12d7c9e041.png">

- Save changes made.
- Edit cluster config again. Change the k8s version to `v1.22.6+rke2r1` and save changes made.
- The cluster goes into Provisioning state. 
- In Cluster explorer --> Nodes page to the cluster details page on Cluster Management, the nodes state do not show `Upgrading` like how it did in Ember UI for RKE1 clusters.

**Expected State**

- One of the pages either in Cluster Explorer --> Nodes page or the Cluster Management Page --> Cluster details , the nodes' state should change to `Upgrading` so it is easier for users to track the progress of cluster upgrade.
- This is a change in behavior from Ember UI.

**Comment by bk201** [comment]
@thedadams I can confirm the image `rancher:v2.6-5bb08b3692ac3c18ec1361694a095e2c25eb0346-head` address these issues:
- https://github.com/harvester/harvester/issues/1984 (Fixed. RKE2 upgrade can be triggered with drain-hooks).
- https://github.com/rancher/rancher/issues/35999 (Fixed. Only single node is upgraded, will need more tests to confirm)

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `024e6fa`**

- Deployed 3 etcd, 2 cp and 3 worker nodes DO RKE2 node driver cluster
- Upgraded k8s from 1.22 to 1.23 
- Etcd nodes on Cluster Management --> CLuster details page --> Status of nodes change to Provisioning and come back Active
- Nodes in Cluster Explorer --> Nodes --> Status changes to Cordoned --> Unavailable --> Active

**Comment by thedadams** [comment]
The choice was made to use the `Provisioning` condition because the code was already using this condition.

There are a few issues related to conditions and we will handle this in the next milestone. I will create another issue for this.

@sowmyav27 With this explanation, can this issue be closed?

**Comment by sowmyav27** [comment]
Closing based on https://github.com/rancher/rancher/issues/36782#issuecomment-1074588288
