### ISSUE TITLE
Load Balancer - support accept-proxy flag for bind

### ISSUE THREAD

**Issue by AirbornePorcine** [rancher/rancher#3679]
Version: 0.56.1

Steps: We are setting up an app that uses websockets, it is fronted by a Rancher LB and also by an ELB. We've set up the ELB to use proxy protocol over TCP so that websockets will be supported.

Results: All requests to the app (including normal http requests) result in a 400 from haproxy. If you manually add the "accept-proxy" flag after the bind statement for the haproxy front end, this goes away. Note that setting up the ELB over http to the same port results in proper http responses (but websockets don't work - ELB limitation)

Expected: It would be nice to add a checkbox to allow us to toggle this option, as this prevents us from using ELBs together with Rancher LBs when utilizing websockets.

**Comment by leoschweizer** [comment]
I'm hitting this exact issue with an HA setup of Rancher 1.0.1 too.

Can anyone elaborate on what the workaround is? Where can I add the accept-proxy flag?

**Comment by AirbornePorcine** [comment]
Yes, this is with running an app inside Rancher. I imagine, like you said, it's the same underlying problem with different solutions. :)

**Comment by kmcgrath** [comment]
Same issue here. ELB with TCP, Proxy Protocol enabled and SSL termination. Advanced routing will not work without the accept-proxy option.

For now I have a hacked solution:
1. ELB connects to a nginx reverse proxy (running on every host) that converts TCP to HTTP 1.1
2. The nginx backed is the Rancher LB

I could remove the extra hop if accept-proxy was an option.  I believe it can only be applied on bind and not in global or defaults.

**Comment by alena1108** [comment]
We started supporting it with customizable haproxy config.

@sangeethah to test it, put the following custom config (80 is the source port in the example):

```
frontend 80 accept-proxy
```
and see if accept-proxy was set in bind/listen directive on haproxy side

**Comment by sangeethah** [comment]
Tested with v1.4.1-rc1:

@alena1108 , Starting a LB service with the following haproxy config , results in  ```accept-proxy``` being set in the bind directive:
```
frontend 8000 
accept-proxy
```
haproxy.config

```
frontend 8000
bind *:8000 accept-proxy
mode http
default_backend 8000_
```

**Comment by sangeethah** [comment]
@AirbornePorcine , you should be able to  set ```accept-proxy``` as a cusotmizable haproxy config when deploying Lb services.
