### ISSUE TITLE
Rancher HA with traefik and letsencrypt shows 404 page not found on FQDN 

### ISSUE THREAD

**Issue by d3473r** [rancher/rancher#36797]
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option: Helm Chart on STACKIT Kubernetes Engine (SKE)

**Information about the Cluster**
- Kubernetes version: 1.21.10
- Cluster Type: Hosted SKE

**User Information**
- What is the role of the user logged in: admin

**Describe the bug**
Instead of the Rancher UI `404 page not found` is shown.
Rancher HA with traefik lb and letsencrypt. A valid certificate was injected from cert-manager, but the rancher FQDN showes `404 page not found`.
When we port-forward port 80 of the rancher service we'll get a timeout, but if the https-internal port 403 is forwarded we get the rancher-ui i suppose with the internal `dynamic` cert.
Somehow port 80 of the rancher service is not working.
We deployed traefik in the `ingress-traefik` namespace as we didn't find any specific traefik documentation and adapted the [default nginx one](https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/amazon-eks/#5-install-an-ingress)

**To Reproduce**
Deploy the Rancher helm chart on a managed kubernetes cluster with traefik and letsencrypt

**Result**
Rancher UI shows `404 page not found`

**Expected Result**
The Rancher UI should be shown

**Screenshots**
Rancher FQDN shows `404 page not found`
![2022-03-08 14_45_10-https___rancher-t hiqs de](https://user-images.githubusercontent.com/10356892/157250438-a3a9b7f1-4ff6-4ff8-ba45-abd1990f8a43.png)

Port-forward port 80 of the rancher service
<img width="660" alt="2022-03-08 14_45_49-localhost" src="https://user-images.githubusercontent.com/10356892/157250518-8ba5d932-329b-40c5-8948-d139a1257d42.png">

Port-forward port 403 of the rancher service
<img width="425" alt="2022-03-08 14_45_41-Rancher" src="https://user-images.githubusercontent.com/10356892/157250557-97227566-9bc5-42f6-8fb9-983dd5f536ce.png">

**Additional context**
As a test we deployed a test pod with a simple http website, this one is available correctely through the ingress

**Comment by joaquinjsb** [comment]
did u manage to solve this issue? I'm facing the same problem

**Comment by vk6xebec** [comment]
This is still happening

**Comment by majorgear** [comment]
Still still happening! 



`---
    kind: Service
    apiVersion: v1
    metadata:
      name: rancher-service-web
    spec:
      type: ExternalName
      ports:
        - name: http
          port: 443
          targetPort: 443
      externalName: redacted
    ---  
    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: rancher-ingressroute-web
      namespace: default
      annotations: 
        kubernetes.io/ingress.class: traefik-external
    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`rancher.redacted.com`)
          kind: Rule
          services:
            - name: rancher-service-web
              port: 443
          middlewares:
            - name: default-headers
            - name: https-redirectscheme
            - name: rancher-headers
      tls:
        secretName: redacted-com-production-tls
    `
`
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-basicauth
  namespace: traefik
spec:
  basicAuth:
    secret: traefik-dashboard-auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: default
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirectscheme 
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rancher-headers
  namespace: default
spec:
  headers:
    customRequestHeaders:
      X-API-request-url: $scheme://<host>$request_uri
`
