### ISSUE TITLE
RKE2 Cluster is stuck in Provisioning State after Taking Snapshot continuously

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#36794]
**Rancher Server Setup**
- Rancher version: v2.6-head 3df76e4
- Installation option (Docker install/Helm Chart): docker install 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version:  v1.22.7+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Digital Ocean

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

The RKE2 cluster is stuck in the `Provisioning` state with the message `waiting for etcd snapshot`  after taking snapshot continuously. 

**To Reproduce**
 

- create the RKE2 cluster with 1 etcd node, 2 control plane, 2 workers 
- makes a snapshot
- restore that snapshot
- scale etcd nodes to 3
- make some new snapshots
 

**Result**
The RKE2 cluster is stuck in the `Provisioning` state with the message `waiting for etcd snapshot` after the latest try of making a snapshot. 

**Expected Result**

The snapshot creating should succeed and the cluster's state should go back to `Active`. 

**Screenshots**

**Additional context**

I just hit this bug once and could not reproduce it.

**Comment by sowmyav27** [comment]
**Hit this issue on `v2.6.4-rc6`**

- create the RKE2 cluster with 3 etcd node, 1 control plane, 3 workers
- Take a snapshot
- Snapshots are seen in the details page of cluster under snapshot tab.
- restore from the snapshot
- Nothing happens on the cluster
- Take another snapshot.
- The cluster is stuck in `Provisioning` state with error `Waiting for etcd snapshot`.

<img width="1435" alt="Screen Shot 2022-03-09 at 3 10 14 AM" src="https://user-images.githubusercontent.com/26032343/157329990-a3d898ad-8441-4068-886f-1f1f02c57d05.png">

Rancher logs:
```
2022/03/08 21:31:48 [INFO] [planner] rkecluster fleet-default/sowmya-rke2: waiting: refreshing etcd create state
2022/03/08 21:31:48 [INFO] [planner] rkecluster fleet-default/sowmya-rke2: waiting: starting etcd snapshot, starting etcd snapshot, starting etcd snapshot
2022/03/08 21:31:48 [INFO] [planner] rkecluster fleet-default/sowmya-rke2: waiting: waiting for etcd snapshot, waiting for etcd snapshot, waiting for etcd snapshot
2022/03/08 21:31:48 [INFO] [planner] rkecluster fleet-default/sowmya-rke2: waiting: waiting for etcd snapshot, waiting for etcd snapshot, waiting for etcd snapshot
2022/03/08 21:31:57 [INFO] [snapshotbackpopulate] rkecluster fleet-default/sowmya-rke2: processing configmap kube-system/rke2-etcd-snapshots
2022/03/08 21:31:57 [INFO] [snapshotbackpopulate] rkecluster fleet-default/sowmya-rke2: processing configmap kube-system/rke2-etcd-snapshots
2022/03/08 21:31:57 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: rkecluster fleet-default/sowmya-rke2: error while creating etcd snapshot fleet-default/sowmya-rke2-on-demand-sowmya-rke2-pool1-bca545cb-flqtn-16-7bb89: etcdsnapshots.rke.cattle.io "sowmya-rke2-on-demand-sowmya-rke2-pool1-bca545cb-flqtn-16-7bb89" already exists, requeuing
2022/03/08 21:31:57 [INFO] [snapshotbackpopulate] rkecluster fleet-default/sowmya-rke2: processing configmap kube-system/rke2-etcd-snapshots
2022/03/08 21:31:57 [INFO] [planner] rkecluster fleet-default/sowmya-rke2: waiting: waiting for etcd snapshot, waiting for etcd snapshot, waiting for etcd snapshot
2022/03/08 21:31:57 [INFO] [planner] rkecluster fleet-default/sowmya-rke2: waiting: waiting for etcd snapshot, waiting for etcd snapshot
2022/03/08 21:31:57 [INFO] [planner] rkecluster fleet-default/sowmya-rke2: waiting: waiting for etcd snapshot, waiting for etcd snapshot
2022/03/08 21:31:58 [INFO] [planner] rkecluster fleet-default/sowmya-rke2: waiting: waiting for etcd snapshot, waiting for etcd snapshot
2022/03/08 21:31:58 [INFO] [planner] rkecluster fleet-default/sowmya-rke2: waiting: waiting for etcd snapshot
2022/03/08 21:31:58 [INFO] [planner] rkecluster fleet-default/sowmya-rke2: waiting: waiting for etcd snapshot
2022/03/08 21:31:58 [INFO] [snapshotbackpopulate] rkecluster fleet-default/sowmya-rke2: processing configmap kube-system/rke2-etcd-snapshots
2022/03/08 21:31:58 [INFO] [snapshotbackpopulate] rkecluster fleet-default/sowmya-rke2: processing configmap kube-system/rke2-etcd-snapshots
2022/03/08 21:31:58 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: rkecluster fleet-default/sowmya-rke2: error while creating etcd snapshot fleet-default/sowmya-rke2-on-demand-sowmya-rke2-pool1-bca545cb-nmpnh-16-a5371: etcdsnapshots.rke.cattle.io "sowmya-rke2-on-demand-sowmya-rke2-pool1-bca545cb-nmpnh-16-a5371" already exists, requeuing
2022/03/08 21:31:58 [INFO] [snapshotbackpopulate] rkecluster fleet-default/sowmya-rke2: processing configmap kube-system/rke2-etcd-snapshots
2022/03/08 21:31:58 [INFO] [snapshotbackpopulate] rkecluster fleet-default/sowmya-rke2: processing configmap kube-system/rke2-etcd-snapshots
2022/03/08 21:31:58 [INFO] [snapshotbackpopulate] rkecluster fleet-default/sowmya-rke2: processing configmap kube-system/rke2-etcd-snapshots
2022/03/08 21:31:58 [INFO] [planner] rkecluster fleet-default/sowmya-rke2: waiting: waiting for etcd snapshot
2022/03/08 21:31:58 [INFO] [planner] rkecluster fleet-default/sowmya-rke2: waiting: refreshing etcd create state
2022/03/08 21:31:58 [INFO] Error while handling cluster log: write tcp:443->:52530: write: broken pipe
2022/03/08 21:31:58 [INFO] rkecluster fleet-default/sowmya-rke2: ensuring designated init node: sowmya-rke2-pool1-bca545cb-f9n52
2022/03/08 21:31:58 [INFO] rkecluster fleet-default/sowmya-rke2: ensuring designated init node: sowmya-rke2-pool1-bca545cb-f9n52
```

**Comment by Oats87** [comment]
### Root cause
The v2prov planner was receiving an `ErrSkip` from the init node manipulation functions with multiple etcd/controlplane node clusters during re-election/designation of an init node. This was fine for initial provisioning/health correcting a cluster, but posed problems in etcd snapshot functionality as it was short circuiting the logic and thus causing the provisioner to get stuck. 

### What was fixed, or what changes have occurred
The helper function for clearing the init node mark (label) will no longer always return an `ErrSkip`, and will instead now return `nil` if no change is made to the labels.

### Areas or cases that should be tested
The area of the issue. 

### What areas could experience regressions?
N/A. I don't see much potential for regression here unless there was a pre-existing reliance somewhere in the code on the faulty logic. 

### Are the repro steps accurate/minimal?
I think so

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head d604b7e
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: node driver

----------

### Testing: ###

Tested this issue with the following steps:
1. create the RKE2 cluster with 1 etcd node, 2 control plane, 2 workers
2. makes a snapshot
3. restore that snapshot
4. scale etcd nodes to 3
5. make some new snapshots

**Result** - Pass

After restoring snapshot, user is able to scale etcd nodes to 3. Snapshots are also successfully created.
![image.png](https://zube.io/files/rancher/2991d5113d34235bfb518e1f73c056ed-image.png)

There is an issue with the age of the first snapshot taken, the issue can be tracked [here](https://github.com/rancher/rancher/issues/36948)
