### ISSUE TITLE
Unable to get notifiers to the email when we configure legacy notifiers with sendgrid

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36790]
**Rancher Server Setup**
- Rancher version: `v2.6-head 3f9109c `
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.23.3+k3s1
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.20.15`
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 3 worker, 1 etcd, 1 cp`
`RKE1`

**Describe the bug**
Enabling notifiers by creating alerts, doesn't send any alerts to the email configured. I do not see any error logs in the rancher server but the notifiers are not received. This works on. 2.6.3 and doesn't work on the latest head. Could be a regression from norman to steve.

**To Reproduce**
1. Create a downstream node driver rke1 cluster with the configuration specified above.
2. From global settings >> enable legacy flag
3. From explorer >> cluster tools >> enable v1 monitoring
4. explorer >> legacy >> notifiers >> select email >> I used a temporary email as sender [configured in the sendgrid >> settings >> sender authentication] 
5. host - smtp.sendgrid.net, username - apikey, Password - sendgrid settings >> apikey >> create a key and provide the value
6. Create an alert from legacy >> alerts - WhenA -Node, Is - CPUReservation - 1%, alert to - select the notifier enabled, Senda - Info

**Result**
No notifications are received to the email configured or none received in the sendgrid activity.

**Expected Result**
Expected to receive an email notification at the configured address and in the sendgrid activity

**Additional context**
Works when we have a webhook configured. Sendgrid email notifiers work on 2.6.3.
Could be a regression from team1 fix.

**Comment by cmurphy** [comment]
https://github.com/rancher/rancher/pull/36880

**Comment by anupama2501** [comment]
Verified on 2.6-head 99974f0

Works as expected
