### ISSUE TITLE
When restoring from an rke1 etcd snapshot, sometimes the cluster gets stuck in state `cluster agent is not connected`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36792]
**Rancher Server Setup**
- Rancher version: v2.6.3-patch2-rc2
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1 1.21.9
- Proxy/Cert Details: valid certs

**Information about the Cluster**
- Kubernetes version: 1.21.9, 1.22.6
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): any (tested with Digital ocean)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)tested with admin and standard user

   
**Describe the bug**

when restoring from a snapshot, sometimes the cluster will get stuck in `cluster agent is not connected` state and does not recover.  Not reproducible on 2.6.3 but is on patch2-rc1 and rc2

**To Reproduce**
 
* deploy a downstream cluster (rke1) configured to use an s3 connection that is slow (related to rancher/rancher#36210 )
* allow the cluster to automatically take a snapshot
* add some resources, say secrets, to inflate the size of the snapshot
* take a manual snapshot of the cluster
* restore to a previous snapshot 

**Result**
cluster begins to restore, but gets stuck with error `cluster agent is not connected`

**Expected Result**

snapshots should restore properly. 

**Screenshots**

**Additional context**
So Far, I have tested:
* snapshot restores from local (not s3, no throttled connection), on patch2 and 2.6.3 and have not reproduced the issue
* currently testing snapshot restores on 2.6.3 with s3/throttled connection to see if this is the root cause.

**Comment by jakefhyde** [comment]
Currently blocked by https://github.com/rancherlabs/corral/issues/77. Although technically testable without corral, this is the exact use case it was designed for, so I see value in updating corral in order to be able to personally test this functionality.

**Comment by snasovich** [comment]
@slickwarren , was this observed again by you or anyone else on QA team recently?

**Comment by slickwarren** [comment]
no, I think it is safe to close this issue for now. We can reopen if it comes back up.

**Comment by snasovich** [comment]
@slickwarren , thank you. Clearing the milestone as well since there was not an explicit fix to this.
