### ISSUE TITLE
Modified values in stack are not kept after upgrades

### ISSUE THREAD

**Issue by raphink** [rancher/rancher#3680]
Rancher Version: 0.59

Steps to Reproduce: 

* Create a stack from the catalog
* When an upgrade is available, change existing values => new values are used
* When a new upgrade is available again, initial values are used in the fields instead of modified ones

Expected:

Stack upgrades should remember modified values (answers.txt regenerated I guess).

**Comment by tfiduccia** [comment]
Verified this is not working properly.  Discussed with Vincent and sending to him.

**Comment by mcanevet** [comment]
+1

**Comment by raphink** [comment]
Thank you @tfiduccia

**Comment by vincent99** [comment]
This requires API support to save the environment maps after an upgrade..

**Comment by raphink** [comment]
Yes, I saw that when editing a stack in the API, it's not possible to access the environment maps. Just accessing it in the API view would already be a great move forward. It's really quite problematic right now.

**Comment by tfiduccia** [comment]
Version - master 3/22
Verified fixed - 1 bug associated with Boolean type but I entered separate bug.

**Comment by raphink** [comment]
Great, looking forward to seeing it live!
