### ISSUE TITLE
Error while retrieving plan secret for machine during RKE2 provisioning

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#36801]
**Rancher Server Setup**
- Rancher version: v2.6-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.10+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
     - RKE2 AWS node driver cluster
     - 8 node cluster (3 etcd, 2 cp, 3 workers)
**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Standard user

   
**Describe the bug**

- When a user provisions an RKE2 cluster, for the first couple of seconds, the Cluster status is red and shows the following error
`error while retrieving plan secret for machine fleet-default/<node_name> service account list length was not 1`
Provisioning was successful but the error at the very beginning is concerning to the user
- This error occurred on more than 1 node

**To Reproduce**
 
1. Provision RKE2 AWS node driver cluster

**Result**
- Provisioning is successful but errors in provisioning log

**Expected Result**

- There should be no errors in the provisioning log if provisioning is successful

**Comment by jiaqiluo** [comment]
The error message is benign at the beginning of the RKE2 provisioning process because the Service Account might not be created at that moment. 
It is also ok to see the error occurred on more than 1 node because the same operation is done on each node in the cluster.

**Comment by snasovich** [comment]
Per @thedadams this may be addressed by the upcoming fix for https://github.com/rancher/rancher/issues/36807.
If not, we either move it to 2.6.5 or close if there is no plan to address removing these messages (which needs to be discussed).
Moving to "Working" meanwhile to take a look into it it once the issue linked in this comment is addressed.

**Comment by jiaqiluo** [comment]
The error message is removed from the backend by [this PR](https://github.com/rancher/rancher/pull/36840).
As the result, we should not see the error anymore.

**Comment by jiaqiluo** [comment]
the fix is in 2.6-head

**Comment by snasovich** [comment]
This should be indirectly fixed for 2.6.4, so if we can validate it that would be great.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head b7c9b89
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2

----------

### Testing: ###

Tested this issue with the following steps:
1. Provision RKE2 AWS node driver cluster

**Result** - Pass

During provisioning, the error specified is no longer reproducible.
