### ISSUE TITLE
Cannot add a Windows node

### ISSUE THREAD

**Issue by zimbres** [rancher/rancher#36815]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: v1.21.9+rke2r1
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
   
**Describe the bug**
Provision windows node get stucked on:" provisioning worker node(s) custom-acd5fa465cdb: waiting on probes: calico" 

**To Reproduce**
Rancher server deployed in a Ubuntu Server;
Add a RKE2 cluster with all default values;
Add a Linux node;
Add a Windows 2019 (1809) with containers feature enabled

**Result**
At Windows EV these messages are observed for racnher-wins:
error loading system cert pool for probe (calico): crypto/x509: system root pool is not available on Windows
error loading system cert pool for probe (kubelet): crypto/x509: system root pool is not available on Windows

**Comment by zimbres** [comment]
Add windows node worked in latest version

**Comment by sandman-cs** [comment]
Can you share what you did to resolve this?

**Comment by zimbres** [comment]
Hi, the regular steps with no additional configuration. Just used the last version of Rancher.
