### ISSUE TITLE
Namespace query in grafana dashboard is heavy

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#36829]
Internal reference: SURE-3706
Reported in 2.5.9 but we should verify performance in 2.6.x.

*Issue description:*
The list query for the namespace selector on the Rancher / Pod (Containers) dashboard is heavy and can take a long time to run in large clusters

*Business impact:*
Low - slow dashboard loading

*Repro steps:*
 * In a large cluster, open the Rancher / Pod (Containers) dashboard

*Actual behavior:*
Dashboard can take a long time to render, due to the namespace selector capturing a large amount of metrics

*Expected behavior:*
 Dashboard could load faster

*Additional notes:*

The query in question is `{__name__=~"container_.|windows_container_.", namespace!=""} `

An example in a large cluster:
```
{__name__=~"container_.*|windows_container_.*", namespace!=""} 
Load time: 10385ms Resolution: 14s Result series: 101793
```

Vs a smaller query that allows the dashboard to render the same:
```
{__name__=~"container_cpu_system_seconds_total|windows_container_cpu_usage_seconds_kernelmode", namespace!=""}
Load time: 297ms Resolution: 14s Result series: 914
```

**Comment by Jono-SUSE-Rancher** [comment]
@samjustus & @MKlimuszka  - I assigned this originally to Team 3 (because of supporting the Grafana dashboard) but it _might_ have some interest to Ricky who is working on performance and scaling stuff. Can you guys discuss and figure out who it makes sense to live with?

**Comment by ronhorton** [comment]
@nickwsuse reach out to dev for testing instructions and clarification

**Comment by nickwsuse** [comment]
@git-ival Just to clarify, is this specifically on Windows clusters? I ask because the queries listed call out windows_container. I think once I know if this is just an issue on Windows then I can move forward with testing.

**Comment by geethub97** [comment]
Unable to recreate this issue in the latest version of Rancher. Waiting to hear back from the client on this ticket to see if this is still an issue. 
https://jira.suse.com/browse/SURE-3706
