### ISSUE TITLE
RKE1 | Can't provision a 1.20.16 k8s cluster

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36825]
**Rancher Server Setup**
- Rancher version: v2.6-head 47c2238
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: 1.20.16
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom / Node driver
   
**Describe the bug**

Can't provision a RKE1 cluster with v1.20.16 k8s version

**To Reproduce**
 
1. Provision a rke1 node driver or custom cluster with v1.20.16-rancher1-1 k8s version'

**Result**
Cluster is not provisioned

Rancher logs:
```
...
2022/03/09 16:10:33 [WARNING] Can't pull Docker image [rancher/hyperkube:v1.20.16-rancher1] on host [REDACTED]: Error response from daemon: manifest for rancher/hyperkube:v1.20.16-rancher1 not found: manifest unknown: manifest unknown
2022/03/09 16:10:33 [WARNING] [pre-deploy] Can't pull Docker image [rancher/hyperkube:v1.20.16-rancher1] on host [REDACTED]: Error response from daemon: manifest for rancher/hyperkube:v1.20.16-rancher1 not found: manifest unknown: manifest unknown
2022/03/09 16:10:33 [ERROR] cluster [c-8q7w4] provisioning: [Error response from daemon: manifest for rancher/hyperkube:v1.20.16-rancher1 not found: manifest unknown: manifest unknown]
2022/03/09 16:10:33 [INFO] kontainerdriver rancherkubernetesengine stopped
2022/03/09 16:10:33 [ERROR] error syncing 'c-8q7w4': handler cluster-provisioner-controller: [Error response from daemon: manifest for rancher/hyperkube:v1.20.16-rancher1 not found: manifest unknown: manifest unknown], requeuing
```

**Expected Result**

Cluster is provisioned with 1.20.16 k8s version

**Screenshots**

![2016](https://user-images.githubusercontent.com/40282141/157483003-15327ed5-96c7-4d8b-b4ee-c39198d41e4d.jpg)

**Comment by kinarashah** [comment]
Hyperkube tag failed for 1.20.16 so the image doesn't exist, https://drone-publish.rancher.io/rancher/hyperkube/504/1/2. 
Worked for remaining k8s versions v1.21.10 and v1.22.7 so these should work.

**Comment by kinarashah** [comment]
Using this issue to track PRs to remove v1.20.16 from KDM, upstream Kubernetes is no longer tagging patch versions for v1.20.x unless necessary.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f904267`**

KDM pointing to dev-v2.6
1.20.15-rancher1-1 is available to deploy. 1.20.16 is not available.
