### ISSUE TITLE
Remove unnecessary re-alignment of long object names in v2prov

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#36823]
V2prov code has a few areas where objects are retrieved by label to re-correlate object names. This was added due to a mistaken understanding of `SafeConcatName` being non-deterministic. 

We should remove these areas as it adds a trivial slowdown to the planner.

**Comment by thedadams** [comment]
Validated the fix on Rancher v2.6-head (99974f0)
- Deployed a RKE2 cluster (v1.21.20+rke2r2) with a really long name with two machine pools, also with really long name.
  - This ensured that things like the CAPI machines and machine plan secrets all had their names cutoff as needed to test this fix.
- Scaled both machine pools up
- Scaled both machine pools down
- Took an on-demand snapshot
- Upgraded the RKE2 version to v1.22.7+rke2r2
- Set an upgrade strategy for control plane and worker nodes
- Deleted the cluster

All of these tasks completed successfully.
![Screen Shot 2022-03-15 at 17 17 00](https://user-images.githubusercontent.com/3682717/158492719-5d6a5c1b-1ec9-4007-a691-c5a35c525c9e.png)
