### ISSUE TITLE
The links in the bottom bar of the rancher graph view aren't clickable

### ISSUE THREAD

**Issue by herau** [rancher/rancher#3682]
Rancher Version: 0.59.1

Docker Version: 1.9.0

OS: Macos 10.10.5 

Steps to Reproduce: Applications / Stacks / View Graph (Dropdown)

Results: The bottom bar isn't clickable (all links aren't clickable)

Expected: The links should be clickable

**Comment by tfiduccia** [comment]
In version 0.59.1 and master this is indeed broken.  It seems to only be in Graph view and doesn't matter how you get to that view.

**Comment by vincent99** [comment]
This is the same as https://github.com/rancher/rancher/issues/3172 , the graph canvas is on top so it gets clicks.
