### ISSUE TITLE
Plan synchronization status not exposed in UI for v2prov clusters

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#36822]
Plan synchronization status is not currently displayed in the UI for v2prov clusters. This can be useful feedback for the end user to determine what the state of their cluster is, and the scaffolding/information is already available in the backend.

**Comment by Oats87** [comment]
How to test this:

Provision a v2prov cluster. 
Edit your cluster as YAML, and set the version of the cluster to some ridiculous version that doesn't exist. for example, `v1.21.6+rke2r5` 
Observe that the machines will go into an error state and tell you to check the `rancher-system-agent.service` logs on the node.

Set the version back to the original version, and observe that the errors go away

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head b8cbc1a
Rancher cluster type: single-node docker install / HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver cluster

----------

### Testing: ###

Tested this issue with the following steps:
1. Provision a v2prov cluster.
2. Edit your cluster as YAML, and set the version of the cluster to some ridiculous version that doesn't exist. for example, v1.21.6+rke2r5
3. Observe that the machines will go into an error state and tell you to check the rancher-system-agent.service logs on the node.
4. Set the version back to the original version, and observe that the errors go away

**Result** - Pass

After changing the version back to the original version, the errors went away and cluster was provisioned successfully
