### ISSUE TITLE
Custom rke1 RHEL 8.4 cluster with 1.18.20 k8s is getting stuck in "Waiting" status 

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36844]
_confirmed on 2.6.3 the issue is present as well_
_checked with ubuntu and the cluster is provisioned with no issues_

**Rancher Server Setup**
- Rancher version: v2.6-head e4af246
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1

**Information about the Cluster**
- Kubernetes version: v1.18.20-rancher1-3
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom rke1 RHEL 8.4 cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: admin and standard user
  
**Describe the bug**

Custom rke1 RHEL 8.4 cluster with v1.18.20 k8s doesn't finish provisioning and gets stuck in "Waiting" status 

**To Reproduce**
 
1. Provision a custom RHEL 8.4 cluster with v1.18.20-rancher1-3 k8s

**Result**
Provisioning logs on the cluster:
```
[INFO ] Finished building Kubernetes cluster successfully
```

Rancher logs:
```


2022/03/10 19:36:07 [INFO] Handling backend connection request [c-pjh5f:m-358d3d8b4f7f]
--
Thu, Mar 10 2022 1:36:07 pm | 2022/03/10 19:36:07 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
Thu, Mar 10 2022 1:36:23 pm | 2022/03/10 19:36:23 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
Thu, Mar 10 2022 1:36:23 pm | W0310 19:36:23.600907 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.Secret ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Thu, Mar 10 2022 1:36:23 pm | W0310 19:36:23.601028 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.ServiceAccount ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Thu, Mar 10 2022 1:36:23 pm | W0310 19:36:23.601120 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.ClusterRoleBinding ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Thu, Mar 10 2022 1:36:23 pm | W0310 19:36:23.601148 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.RoleBinding ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Thu, Mar 10 2022 1:36:23 pm | W0310 19:36:23.601214 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.Role ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Thu, Mar 10 2022 1:36:23 pm | W0310 19:36:23.602068 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.ClusterRole ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Thu, Mar 10 2022 1:36:23 pm | W0310 19:36:23.602527 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.Namespace ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
Thu, Mar 10 2022 1:36:50 pm | 2022/03/10 19:36:50 [INFO] Handling backend connection request [c-pjh5f:m-f10499aa9f14]
Thu, Mar 10 2022 1:37:07 pm | I0310 19:37:07.929687 32 trace.go:205] Trace[1986448115]: "Reflector ListAndWatch" name:github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168 (10-Mar-2022 19:36:24.875) (total time: 43054ms):
Thu, Mar 10 2022 1:37:07 pm | Trace[1986448115]: ---"Objects listed" error:<nil> 43054ms (19:37:07.929)
Thu, Mar 10 2022 1:37:07 pm | Trace[1986448115]: [43.054589756s] [43.054589756s] END
```

```
2022/03/10 19:36:23 [INFO] Creating system token for u-i2wcy6gvf2, token: agent-u-i2wcy6gvf2
W0310 19:36:23.595319 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.Role ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0310 19:36:23.595429 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.Secret ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0310 19:36:23.595467 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.ClusterRole ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0310 19:36:23.595496 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.ServiceAccount ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0310 19:36:23.595523 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.RoleBinding ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0310 19:36:23.595550 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.ClusterRoleBinding ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0310 19:36:23.608642 32 reflector.go:443] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168: watch of *v1.Namespace ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
2022/03/10 19:36:29 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:37323
2022/03/10 19:36:29 [INFO] kontainerdriver rancherkubernetesengine stopped
2022/03/10 19:36:34 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:40147
2022/03/10 19:36:34 [INFO] kontainerdriver rancherkubernetesengine stopped
2022/03/10 19:36:45 [INFO] cluster [c-pjh5f] worker-upgrade: updating node [m-f10499aa9f14] with node-version 1
2022/03/10 19:36:45 [INFO] cluster [c-pjh5f] worker-upgrade: sending node-version for node [] version 1
I0310 19:37:07.789941 32 trace.go:205] Trace[41511727]: "Reflector ListAndWatch" name:github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.23.3-rancher1/tools/cache/reflector.go:168 (10-Mar-2022 19:36:24.736) (total time: 43053ms):
Trace[41511727]: ---"Objects listed" error:<nil> 43053ms (19:37:07.789)
Trace[41511727]: [43.053568373s] [43.053568373s] END
```

**Expected Result**

Cluster provisions

**Comment by jakefhyde** [comment]
This will need to be investigated by whoever picks it up (no immediate ideas of root cause).

**Comment by slickwarren** [comment]
we need to validate this as part of testing this ticket https://github.com/rancher/rancher/issues/36812

**Comment by paynejacob** [comment]
The root cause here is a dns lookup failure in the cluster agent pod.

**Comment by paynejacob** [comment]
https://github.com/rancher/docs/issues/4055

**Comment by Josh-Diamond** [comment]
Ticket #36844 - Test Results

With Docker on single-node instance:

Reproduced on rancher `v2.6.3`
1. Fresh install of rancher `v2.6.3`
2. Provision a downstream RKE1 Custom RHEL 8.4 cluster with k8s `v1.18.20`
3. Reproduced - Cluster fails to provision

Screenshot:
`Cluster Management`
<img width="1644" alt="Screen Shot 2022-05-05 at 10 57 09 AM" src="https://user-images.githubusercontent.com/46494969/166984195-a301d3a8-da38-4242-ab08-b6d7abd23e39.png">


`Provisioning Logs`
<img width="914" alt="Screen Shot 2022-05-05 at 10 56 20 AM" src="https://user-images.githubusercontent.com/46494969/166984025-86eaf17a-23ce-4084-b84e-80b49151dfa6.png">

`Rancher Logs`
```logs
I0505 17:33:51.892669      33 trace.go:205] Trace[1293033554]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168 (05-May-2022 17:33:08.839) (total time: 43052ms):
Trace[1293033554]: ---"Objects listed" 43052ms (17:33:51.892)
Trace[1293033554]: [43.052897631s] [43.052897631s] END
```

---

Veri-FAILED on rancher `v2.6-4bbee5995053eb52ef447ca82de2c90b1af8b21a-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE1 Custom RHEL 8.4 cluster with k8s `v1.18.20`:
    - Create 3 AWS instances with RHEL 8.4 ami and for each node:
         - Install firewalld - [`yum install firewalld -y`]
         - Start + enable firewalld, then reboot - [`systemctl start firewalld`, `systemctl enable firewalld`, `reboot`]
         - Add group to docker - [`usermod -aG docker <user>`, `systemctl enable docker`, `systemctl start docker`, `reboot`
         -  Open port 2379 - [`firewall-cmd --zone=public --add-port=2379/tcp --permanent`]
         - Run `firewall-cmd --zone=public --add-masquerade --permanent`
         - Run `firewall-cmd --reload`
    - From rancher UI, create a downstream custom RKE1 cluster with k8s `v1.18.20`
    - Register nodes
4. Veri-FAILED - Nodes successfully register, but provisioning fails with the following error: `[ERROR] [controlPlane] Failed to upgrade Control Plane: [[host ip-#-#-#-# not ready]]`

Screenshots:
`Registration successful`
<img width="1565" alt="Screen Shot 2022-05-11 at 2 19 27 PM" src="https://user-images.githubusercontent.com/46494969/167949635-d0202a04-fc7e-486f-b6d4-6727eddb8a37.png">

`Provisioning failure`
![proof](https://user-images.githubusercontent.com/46494969/167950628-af9ecdba-6f7b-40b2-aacb-119451bc232c.png)

- system-agent logs - no entries

Logs:

`Rancher server`
```logs
2022/05/11 21:26:02 [INFO] cluster [ID_REDACTED] provisioning: [controlplane] Successfully started Controller Plane..
2022/05/11 21:26:02 [INFO] cluster [ID_REDACTED] provisioning: [worker] Building up Worker Plane..
2022/05/11 21:26:02 [INFO] cluster [ID_REDACTED] provisioning: [sidekick] Sidekick container already created on host [IP_REDACTED]
2022/05/11 21:26:02 [INFO] cluster [ID_REDACTED] provisioning: [healthcheck] Start Healthcheck on service [kubelet] on host [IP_REDACTED]
2022/05/11 21:26:02 [INFO] cluster [ID_REDACTED] provisioning: [healthcheck] service [kubelet] on host [IP_REDACTED] is healthy
2022/05/11 21:26:02 [INFO] Image [rancher/rke-tools:v0.1.75] exists on host [IP_REDACTED]
2022/05/11 21:26:02 [INFO] Starting container [rke-log-linker] on host [IP_REDACTED], try #1
2022/05/11 21:26:02 [INFO] Error while handling cluster log: write tcp IP_REDACTED:443->IP_REDACTED:57309: write: broken pipe
2022/05/11 21:26:02 [INFO] cluster [ID_REDACTED] provisioning: [worker] Successfully started [rke-log-linker] container on host [IP_REDACTED]
2022/05/11 21:26:02 [INFO] Removing container [rke-log-linker] on host [IP_REDACTED], try #1
2022/05/11 21:26:02 [INFO] cluster [ID_REDACTED] provisioning: [remove/rke-log-linker] Successfully removed container on host [IP_REDACTED]
2022/05/11 21:26:02 [INFO] cluster [ID_REDACTED] provisioning: [healthcheck] Start Healthcheck on service [kube-proxy] on host [IP_REDACTED]
2022/05/11 21:26:02 [INFO] cluster [ID_REDACTED] provisioning: [healthcheck] service [kube-proxy] on host [IP_REDACTED] is healthy
2022/05/11 21:26:02 [INFO] Image [rancher/rke-tools:v0.1.75] exists on host [IP_REDACTED]
2022/05/11 21:26:02 [INFO] Starting container [rke-log-linker] on host [IP_REDACTED], try #1
2022/05/11 21:26:03 [INFO] cluster [ID_REDACTED] provisioning: [worker] Successfully started [rke-log-linker] container on host [IP_REDACTED]
2022/05/11 21:26:03 [INFO] Removing container [rke-log-linker] on host [IP_REDACTED], try #1
2022/05/11 21:26:03 [INFO] cluster [ID_REDACTED] provisioning: [remove/rke-log-linker] Successfully removed container on host [IP_REDACTED]
2022/05/11 21:26:03 [INFO] cluster [ID_REDACTED] provisioning: [worker] Successfully started Worker Plane..
2022/05/11 21:26:03 [INFO] [controlplane] Now checking status of node ip-REDACTED, try #1
2022/05/11 21:26:08 [INFO] [controlplane] Now checking status of node ip-REDACTED, try #2
2022/05/11 21:26:13 [INFO] [controlplane] Now checking status of node ip-REDACTED, try #3
2022/05/11 21:26:18 [INFO] [controlplane] Now checking status of node ip-REDACTED, try #4
2022/05/11 21:26:23 [INFO] [controlplane] Now checking status of node ip-REDACTED, try #5
2022/05/11 21:26:28 [ERROR] Host ip-REDACTED failed to report Ready status with error: host ip-REDACTED not ready
2022/05/11 21:26:28 [INFO] [controlplane] Now checking status of node ip-REDACTED, try #1
2022/05/11 21:26:28 [INFO] cluster [ID_REDACTED] provisioning: [controlplane] Processing controlplane hosts for upgrade 1 at a time
2022/05/11 21:26:28 [INFO] cluster [ID_REDACTED] provisioning: Processing controlplane host ip-REDACTED
2022/05/11 21:26:33 [INFO] [controlplane] Now checking status of node ip-REDACTED, try #2
2022/05/11 21:26:38 [INFO] [controlplane] Now checking status of node ip-REDACTED, try #3
2022/05/11 21:26:43 [INFO] [controlplane] Now checking status of node ip-REDACTED, try #4
2022/05/11 21:26:48 [INFO] [controlplane] Now checking status of node ip-REDACTED, try #5
2022/05/11 21:26:53 [ERROR] Failed to upgrade hosts: ip-REDACTED with error [host ip-REDACTED not ready]
2022/05/11 21:26:53 [ERROR] cluster [ID_REDACTED] provisioning: [controlPlane] Failed to upgrade Control Plane: [[host ip-REDACTED not ready]]
2022/05/11 21:26:53 [INFO] kontainerdriver rancherkubernetesengine stopped
2022/05/11 21:26:53 [ERROR] error syncing 'ID_REDACTED': handler cluster-provisioner-controller: [controlPlane] Failed to upgrade Control Plane: [[host ip-REDACTED not ready]], requeuing
2022/05/11 21:28:53 [INFO] Provisioning cluster [ID_REDACTED]
```
`Etcd node`
```logs
-- Logs begin at Wed 2022-05-11 21:07:20 UTC, end at Wed 2022-05-11 21:37:36 UTC. --
-- No entries --
```

`Control plane node`
```logs
-- Logs begin at Wed 2022-05-11 21:13:27 UTC, end at Wed 2022-05-11 21:35:18 UTC. --
-- No entries --
```

`Worker node`
```logs
-- Logs begin at Wed 2022-05-11 21:17:25 UTC, end at Wed 2022-05-11 21:32:41 UTC. --
-- No entries --
```

This could be AWS specific and possibly the same root cause as [#36526](https://github.com/rancher/rancher/issues/36526)

**Comment by paynejacob** [comment]
### Root cause
RHEL firewall settings are not compatible with rke by default.
  
### What was fixed, or what changes have occurred
Updated docs to configure redhat
  
### Areas or cases that should be tested
- provisioning an RKE1 custom cluster on nodes with RHEL
  
### What areas could experience regressions?
- none
  
### Are the repro steps accurate/minimal?

1. create a vm with a RHEL 8.4 install cd
2. follow the RHEL install instructions to install RHEL in the vm
3. SSH into the newly provisioned RHEL vm
4. run the install docker script
5. create a custom RKE1 cluster on rancher
6. run the import command on the RHEL VM
7. the cluster will provision and then fail to connect the cluster agent.

FIXED:
1. create a vm with a RHEL 8.4 install cd
2. follow the RHEL install instructions to install RHEL in the vm
3. SSH into the newly provisioned RHEL vm
4. run firewall-cmd --zone=public  --add-masquerade --permanent; firewall-cmd --reload
5. run the install docker script
6. create a custom RKE1 cluster on rancher
7. run the import command on the RHEL VM
8. the cluster will provision and then fail to connect the cluster agent.

**Comment by Josh-Diamond** [comment]
Validation failure with steps:
1. create a vm with a RHEL 8.4 install cd
2. follow the RHEL install instructions to install RHEL in the vm

No SUSE infrastructure is provided to test this.  With my m1 mac, UTM seems to be the only compatible tool for creating VMs.  Unable to proceed without an active RedHat subscription.

**Comment by paynejacob** [comment]
REPRO:

1. create a custom cluster with k8s 1.18.20
2. create an ec2 with the redhat ami `309956199498/RHEL-8.6.0_HVM-20220503-x86_64-2-Hourly2-GP2`
3. run `curl https://releases.rancher.com/install-docker/19.03.sh | sh`
4. run the import command
5. cluster agent cannot connect

FIXED:

1. create a custom cluster with k8s 1.18.20
2. create an ec2 with the redhat ami `309956199498/RHEL-8.6.0_HVM-20220503-x86_64-2-Hourly2-GP2`
3. run `sudo firewall-cmd --zone=public --add-masquerade --permanent`
4. run `sudo firewall-cmd --reload`
5. run `curl https://releases.rancher.com/install-docker/19.03.sh | sh`
6. run the import command
7. cluster agent connects and cluster is ready

**Comment by Josh-Diamond** [comment]
Concern: 
- ticket mentions issue with RHEL 8.4, however verification steps prompt using RHEL 8.6
- proceeded to test using RHEL 8.4
---

Ticket #36844 - Test Results [pt. 2]

With Docker on a single-node instance:

Veri-FAILED on rancher `v2.6.6`:
1. Fresh install of rancher `v2.6.6`
2. Create an RKE1 custom cluster w/ k8s `v1.18.20-rancher1-3` via rancher UI
3. Create an EC2 instance with `RHEL-8.4.0_HVM-20210825-x86_64-0-Hourly2-GP2` - [`community ami`]
4. Veri-FAILED - running `firewall-cmd` commands returns the following terminal error: `sudo: firewall-cmd: command not found`
5. Proceeding anyway, and installing firewalld:
    - `sudo yum install firewalld`
    - `sudo systemctl start firewalld`
    - `sudo systemctl enable firewalld`
    - `sudo systemctl status firewalld`
6. Then running the following on the RHEL 8.4 instance:
    - `sudo firewall-cmd --zone=public --add-masquerade --permanent`
    - `sudo firewall-cmd --reload`
    -  `curl https://releases.rancher.com/install-docker/19.03.sh | sh`
    - import command from rancher UI
7. Veri-FAILED - cluster fails provisioning with the following network related error: 
```logs
[[network] Host [REDACTED] is not able to connect to the following ports: [REDACTED:2379]. Please check network policies and firewall rules]
```

---

`Test #2` - Custom RKE1 w/ k8s `v1.18.20` - [reproduction of original issue]

Reproduced on rancher `v2.6.6`:
1. Fresh install of rancher `v2.6.6`
2. Create an RKE1 custom cluster w/ k8s `v1.18.20-rancher1-3` via rancher UI
3. Create an EC2 instance with `ami-0035d7e2be370e0f1` - [`private ami`]
4. Run import command from rancher UI on RHEL 8.4 instance
5. Reproduced - provisioning logs state cluster was built successfully; cluster stuck in `waiting` hang state

Screenshots:

`Provisioning logs`
<img width="929" alt="Screen Shot 2022-07-05 at 3 45 31 PM" src="https://user-images.githubusercontent.com/46494969/177429660-b3ff3d18-dfe0-4f19-92c3-3118d1a0c512.png">

`Cluster Management`
<img width="1492" alt="Screen Shot 2022-07-05 at 3 50 09 PM" src="https://user-images.githubusercontent.com/46494969/177429735-13e0c654-5e8e-4680-9b94-db0903d8f9dc.png">

---

`Test #3` - Custom RKE1 w/ k8s `v1.20.15-rancher1-4` + same private AMI from `Test #2` above - [verification]

Verified on rancher `v2.6.6`:
1. Fresh install of rancher `v2.6.6`
2. Create an RKE1 custom cluster w/ k8s `v1.20.15-rancher1-4` via rancher UI
3. Create an EC2 instance with `ami-0035d7e2be370e0f1` - [`private ami`]
4. Run import command from rancher UI on RHEL 8.4 instance
5. Verified - cluster successfully provisions

Screenshot:

`Cluster Management`
<img width="1495" alt="Screen Shot 2022-07-05 at 4 01 05 PM" src="https://user-images.githubusercontent.com/46494969/177430795-16a42f1f-9928-40f1-9919-2d838dfb1e95.png">

---

Just to be clear :
- `Test #2` and `Test #3` were both ran using the same private RHEL 8.4 ami, 
    - `ami-0035d7e2be370e0f1`;
- k8s `v1.18.20-rancher1-3` fails to provision in `Test #2`
- k8s `v1.20.15-rancher1-4` provisions successfully in `Test #3`
