### ISSUE TITLE
Windows worker nodes do not upgrade to k8s 1.23

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36849]
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart): docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): 1.23.3k3s

**Information about the Cluster**
- Kubernetes version: windows custom rke1 cluster
- Cluster Type (Local/Downstream): 3 linux nodes, 3 windows 2019 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) std user

   
**Describe the bug**
Windows worker nodes do not upgrade to k8s 1.23

**To Reproduce**

- Deployed a windows 1.21.9 cluster on 2.6.3
- Do a rancher upgrade to 2.6.4-rc8
- Upgrade windows cluster's k8s version to 1.23.4-rancher1-1

**Result**
- WIndows worker nodes are stuck in cordoned state on Cluster explorer -->> Nodes page
- Rancher logs: 
```
2022/03/11 19:18:55 [ERROR] error syncing 'c-h5frb/m-8ce49329d0df': handler rke-worker-upgrader: setNodePlan: error getting node plan for [m-160fcaf2696d]: getDefaultKubernetesServicesOptions: No serviceOptions found for cluster version [v1.23.4-rancher1-1] or cluster major version [v1.23], requeuing
2022/03/11 19:18:55 [INFO] Provisioning cluster [c-h5frb]
2022/03/11 19:18:55 [INFO] Updating cluster [c-h5frb]
2022/03/11 19:18:55 [INFO] cluster [c-h5frb] worker-upgrade: call upgrade to reconcile for node [m-8ce49329d0df]
2022/03/11 19:18:55 [ERROR] error syncing 'c-h5frb/m-8ce49329d0df': handler rke-worker-upgrader: setNodePlan: error getting node plan for [m-160fcaf2696d]: getDefaultKubernetesServicesOptions: No serviceOptions found for cluster version [v1.23.4-rancher1-1] or cluster major version [v1.23], requeuing
```

**Comment by deniseschannon** [comment]
Are general k8s upgrades from 1.21 to 1.23 working?

The error seems to indicate it's not Windows specfic.

**Comment by rosskirkpat** [comment]
RKE1 1.23 Windows was not working due to the k8s service options for windows missing from the initial 1.23 PR in rke1. This has been addressed by the Windows Team and is ready to be tested again with latest 2.6-head once it is published https://drone-publish.rancher.io/rancher/rancher/7495

**Comment by vivek-infracloud** [comment]
Validated this issue.

Validation steps followed are as follows.

- Created a rancher server v2.6.3
- Provisioned a RKE1 Windows cluster k8s v1.21
- Upgraded rancher to v2.6.4-rc9
- Updated windows k8s cluster from v1.21 to v1.23 successfully. 

However blocked by the [#36898 ] and [#36896] issue on windows cluster.

**Comment by deniseschannon** [comment]
@sowmyav27 @slickwarren  I'd be willing to close this issue as the upgrade to k8s 1.23 is now working as the service options in RKE1 have been updated to include the necessary steps that @vivek-infracloud has taken. 

The other issues that @vivek-infracloud has outlined as blockers are not blockers for the upgrade but something else in provisioning and the updates/changes would happen in another part of the code. This was only missing something in KDM when introducing a new minor release.

**Comment by sowmyav27** [comment]
Since the [k8s upgrade was a success](https://github.com/rancher/rancher/issues/36849#issuecomment-1070958107) closing this issue.
