### ISSUE TITLE
Manual Longhorn installation failed on RHEL 8.4

### ISSUE THREAD

**Issue by MSpencer87** [rancher/rancher#36847]
**Rancher Server Setup**
- Rancher version:
Rancher v2.6.3
RKE1.3.3 -> k8s v.21.7(default)
- Cluster Type: local, downstream
- Infrastructure Provider: AWS
- Local Cluster AMI: rhel-8.4.-docker-20.10-selinux-on
- Downstream Cluster AMI: rhel-8.4.-docker-20.10-selinux-on, rhel-8.4.-docker-20.10.7-selinux-on-rpm
- AMI User: ec2-user
- Rancher User: Admin
- Longhorn:  longhorn:100.1.1+up1.2.3
   
**Describe the bug**

Longhorn fails to install on local and downstream clusters

**To Reproduce**
 
1) Bring up Rancher 2.6.3 (1 cp, 1 etcd, 3 workers) 
2) Open Main Menu, Navigate to Apps & Marketplace, Select Charts
3) Install Longhorn (fails)

2) Bring up downstream cluster (1 cp, 1 etcd, 3 workers) 
2) Open Main Menu, Navigate to Apps & Marketplace, Select Charts
3) Install Longhorn (fails)

**Result**
Installed Applicaitons shows Failed tag on Longhorn
UI has This resource is currently in an error state, but there isn't a detailed message available.
Longhorn fails to install with CrashBackoffLoop on manager with pod errors:

`kubectl logs longhorn-manager-s579b -n longhorn-system`
```
2022/03/10 21:51:30 proto: duplicate proto type registered: VersionResponse
time="2022-03-10T21:51:30Z" level=error msg="Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host"
time="2022-03-10T21:51:30Z" level=fatal msg="Error starting manager: Environment check failed: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm --version], output , stderr, nsenter: failed to execute iscsiadm: No such file or directory\n, error exit status 127"
```

`kubectl logs longhorn-manager-tqllz -n longhorn-system`
```
2022/03/10 21:56:35 proto: duplicate proto type registered: VersionResponse
time="2022-03-10T21:56:35Z" level=error msg="Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host"
time="2022-03-10T21:56:35Z" level=fatal msg="Error starting manager: Environment check failed: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm --version], output , stderr, nsenter: failed to execute iscsiadm: No such file or directory\n, error exit status 127"```
```

`kubectl logs longhorn-ui-7d7b4bbbc6-h5ftn -n longhorn-system`
```
2022/03/10 21:09:39 [warn] 1#1: duplicate MIME type "text/html" in /etc/nginx/nginx.conf:7
nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/nginx.conf:7
mspencer@Michaels-MacBook-Pro local % kubectl logs longhorn-manager-s579b -n longhorn-system
````

`kubectl logs longhorn-driver-deployer-7c566845f4-xbfvx -n longhorn-system`
```
Error from server (BadRequest): container "longhorn-driver-deployer" in pod "longhorn-driver-deployer-7c566845f4-xbfvx" is waiting to start: PodInitializing
```

**Expected Result**

Longhorn complete installation without error

**Additional Information**
From Terraform installation
```
20:55:36.663  SUCCESS: helm upgrade --install=true --namespace=longhorn-system --timeout=10m0s --values=/home/shell/helm/values-longhorn-crd-100.1.1-up1.2.3.yaml --version=100.1.1+up1.2.3 --wait=true longhorn-crd /home/shell/helm/longhorn-crd-100.1.1-up1.2.3.tgz

20:55:36.663  ---------------------------------------------------------------------

20:55:36.663  helm upgrade --install=true --namespace=longhorn-system --timeout=10m0s --values=/home/shell/helm/values-longhorn-100.1.1-up1.2.3.yaml --version=100.1.1+up1.2.3 --wait=true longhorn /home/shell/helm/longhorn-100.1.1-up1.2.3.tgz

20:55:36.663  Release "longhorn" does not exist. Installing it now.

20:55:36.663  W0311 04:45:21.257341      45 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

20:55:36.663  creating 18 resource(s)

20:55:36.663  W0311 04:45:21.328962      45 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```

**Comment by bmdepesa** [comment]
Possibly due to missing prereqs - @MSpencer87 to retest.

**Comment by khushboo-rancher** [comment]
@bmdepesa is correct the prereqs were missing - The prereq software should be installed on the worker node before installing Longhorn. https://github.com/longhorn/longhorn/tree/master/deploy/prerequisite

I did installed the iscsi and it started working fine but issue is Dashboard keeps showing it as failed.
