### ISSUE TITLE
No show of cluster members under cluster RBAC

### ISSUE THREAD

**Issue by rchench** [rancher/rancher#36866]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option: Helm Chart, RKE1 1.21.9
- Proxy/Cert Details: no proxy, DigiCerts signed certificates

**Information about the Cluster**
- Kubernetes version: 1.21.1
- Cluster Type: Downstream, Imported, Kubeadm installed on Premise

**User Information**
- What is the role of the user logged in? Admin

   
**Describe the bug**

The cluster members do not show up under the cluster RBAC. It is all empty. However there are plenty of cluster members. They can show up in the cluster config edit, legacy cluster members GUI and via rest API.

**To Reproduce**
 
Import a cluster and add several cluster members (via either GUI or API), they are not showing up on cluster RBAC.
<img width="1037" alt="Screen Shot 2022-03-12 at 3 06 15 PM" src="https://user-images.githubusercontent.com/12016189/158039036-8471bcd7-f249-441c-970c-d79af485e053.png">

But if I go the cluster edit function, show can show up
<img width="1006" alt="Screen Shot 2022-03-12 at 3 03 05 PM" src="https://user-images.githubusercontent.com/12016189/158039043-57f89f6d-773e-4a56-bbe1-e2a5826bea3b.png">

I can also go to the legacy GUI and they also show up there.
<img width="1017" alt="Screen Shot 2022-03-12 at 3 07 21 PM" src="https://user-images.githubusercontent.com/12016189/158039052-84b46758-ad14-4964-8089-03f98cc4fa44.png">

I can also use rest API to successfully pull the cluster members
```
curl -u $token https://$url/v1/management.cattle.io.clusterroletemplatebindings/$clusterid
{
  "type": "collection",
  "links": {
    "self": "https://xxxx/v1/management.cattle.io.clusterroletemplatebindings/c-m-xxxx"
  },
  "actions": {},
  "resourceType": "management.cattle.io.clusterroletemplatebinding",
  "revision": "12177575",
  "data": [
    {
      "id": "c-m-xxxx/c-m-xxxx-fleet-default-owner",
      "type": "management.cattle.io.clusterroletemplatebinding",
      "links": {
        "remove": "blocked",
        "s
```

**Result**
cluster members are empty

**Expected Result**

all cluster members shall be listed under RBAC

**Screenshots**

**Additional context**

The authentication is LDAP. Not all clusters have this issue but there are plenty of them having the issue. For some clusters, some cluster members can show up but some cannot.

**Comment by joereyna** [comment]
@rchench did you ever find a fix for this?  I'm seeing this on one of my clusters while the others are just fine.  I see some websocket errors in the rancher logs when I try to view the missing RBAC members, but I tested my sockets with this and the sockets worked fine:

```
curl -s -i -N \
  --http1.1 \
  -H "Connection: Upgrade" \
  -H "Upgrade: websocket" \
  -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
  -H "Sec-WebSocket-Version: 13" \
  -H "Authorization: Bearer $TOKEN" \
  -H "Host: $FQDN" \
  -k https://$FQDN/v3/subscribe
```

**Comment by joereyna** [comment]
I think I just figured it out.  My user was listed as a local user and the cluster members came back once I removed my local user self.  Weird.

**Comment by GolubevV** [comment]
I have the same problem as mentioned by @rchench for version 2.6.9 for people with **Cluster Owner** role -  is there any remedy for that?
