### ISSUE TITLE
Nodes showing incorrect roles in an RKE1 node driver cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36860]
**Rancher Server Setup**
- Rancher version: 2.6.4-rc8
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: 1.20
- Cluster Type (Local/Downstream): Node driver EC2 0 3 etcd, 2 cp and 3 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

**Describe the bug**
Nodes showing incorrect roles in an RKE1 node driver cluster

**To Reproduce**

- Deployed 2 RKE1 EC2 clusters:
  - 3 etcd, 2 cp and 3 worker nodes
  - 1 etcd node pool, 1 cp nodepool and 1 worker node pool
- On one cluster - one CP node shows all roles
- This node does not have etcd container on the node when sshed into
- Kubectl get nodes, show one cp node has `all roles`
- On another cluster, 1 etcd node shows all roles
- This node does not have control plane components

**Expected Result**
All roles should not be available for etcd ONLY or control plan only node

**Note:**
- validated this on 2.6.3, same cluster node config and this issue is not seen

**Comment by snasovich** [comment]
This needs to be reproduced and investigated; there were no planned changes around this functionality per @kinarashah , so may take "bisecting commits" approach to figure out what broke it.

**Comment by kinarashah** [comment]
I kept running into this issue while trying to reproduce https://github.com/rancher/rancher/issues/36862, maybe the same regression is causing both issues. 
Able to reproduce this issue consistently with - 

**Rancher server version**: `>=v2.6.4-rc5` 
**Install type**: Docker single node install 

**Steps:**
- Provision a downstream RKE1 ec2 node driver cluster with 3 different machine pools having 3 etcd, 2 cp and 2 worker nodes respectively 
- Initially, the nodes have correct roles so wait for provisioning to complete 
- After the cluster is active, one of the etcd only/control plane only roles will have incorrect `All` roles

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `5bb08b3`**

- deployed an RKE1 - 3 etcd, 2 cp and 3 wworker nodes cluster
- No All roles node is seen

<img width="1419" alt="Screen Shot 2022-03-17 at 11 55 09 AM" src="https://user-images.githubusercontent.com/26032343/158749625-0ecea0fa-d139-40d8-96b2-efb353cf9aea.png">

- Performed a k8s upgrade. 
- Node roles remained intact
