### ISSUE TITLE
downstream cluster continuously switching between `active` and `updating` states following k8s cluster upgrade

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#36862]
**Rancher Server Setup**
- Rancher version: v2.6.4-rc8
- Installation option (Docker install/Helm Chart): Helm Chart (Jenkins HA Rancher job)
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
   - Helm chart: `2.6.3`
   - K8s: `v1.22.6`
   - `Imported`
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `v1.22.7-rancher1-1` (upgraded from `1.21.9-rancher1-1`)
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
RKE1 Custom Cluster (8 nodes - 3 etcd, 2 cp, 3 wkr)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  Standard User as `Cluster Owner`

   
**Describe the bug**
Post k8s upgrade (from `v1.21.9-rancher1-1` to `v1.22.7-rancher1-1`), downstream cluster continuously switching between `active` and `updating` states, cluster state is predominantly  `updating`.

**To Reproduce**
1. Launch fresh install of HA Rancher `v2.6.4-rc8`
2. As standard user, create an RKE1 custom 8 node cluster (3 etcd, 2 cp, 3 wkr)
3. As standard user, create a second RKE1 custom 8 node cluster (3 etcd, 2cp, 3 wkr)
4. Upgrade k8s versions on both clusters (from `v1.21.9-rancher1-1` to `v1.22.7-rancher1-1`)
5. Issue Reproduced 

**Result**
First provisioned downstream cluster upgrades and stabilizes
Second provisioned downstream cluster upgrades and continuously switches states from `active` to `upgrading`

**Expected Result**
Both downstream clusters upgrade and stabilize

**Screenshots**
<img width="1602" alt="Screen Shot 2022-03-11 at 6 29 12 PM" src="https://user-images.githubusercontent.com/46494969/157998222-1189e72d-b462-48c8-a601-3591dc35c351.png">

![release_testing_issue](https://user-images.githubusercontent.com/46494969/157998661-e85a8055-482a-4408-949f-2a116f31068a.png)

**Additional context**
```log
2022/03/11 22:24:40 [ERROR] Failed to handling tunnel request from remote address REDACTED_IP_ADDRESS_1:REDACTED_PORT_A (X-Forwarded-For: REDACTED_IP_ADDRESS_2): response 400: cluster not found


2022/03/11 22:24:47 [ERROR] Failed to handling tunnel request from remote address REDACTED_IP_ADDRESS_1:REDACTED_PORT_B (X-Forwarded-For: REDACTED_IP_ADDRESS_3): response 400: cluster not found

2022/03/11 22:24:48 [ERROR] Failed to handling tunnel request from remote address REDACTED_IP_ADDRESS_1:REDACTED_PORT_C (X-Forwarded-For: REDACTED_IP_ADDRESS_4): response 400: cluster not found
```
<img width="453" alt="Screen Shot 2022-03-11 at 7 59 06 PM" src="https://user-images.githubusercontent.com/46494969/158001183-abbe6026-6c1d-4f92-81c5-56bb989f3b54.png">

**Comment by sowmyav27** [comment]
**Rancher Server Setup**
- Rancher version: 2.6.4-rc8
- Installation option (Docker install/Helm Chart): docker install


**Information about the Cluster**
- Kubernetes version: 1.20.15 to 1.21.10
- Cluster Type (Local/Downstream): AWS node driver - 3 etcd, 2 cp and 3 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

   
**Describe the bug**
Cluster is stuck in `Updating` state after k8s upgrade

**To Reproduce**

- Deploy an RKE1 AWS Node driver cluster on 1.20.15
- After the cluster is up and Active, upgrade k8s to 1.21
- the k8s versions on all the nodes get upgraded. 
- But the cluster is stuck in provisioning. But keeps toggling between Updating and Active

**Result**
- Rancher server logs spammed in debug mode with these logs
```
2022/03/12 19:22:15 [INFO] kontainerdriver rancherkubernetesengine stopped
2022/03/12 19:22:15 [INFO] Updated cluster [c-6dbcx] with node version [2]
2022/03/12 19:22:15 [INFO] Provisioned cluster [c-6dbcx]
2022/03/12 19:22:15 [DEBUG] isActiveCluster: true isWindowsCluster: false user: user-fmgbx, canUpdateCluster: true
2022/03/12 19:22:15 [DEBUG] isActiveCluster: true isWindowsCluster: false user: , canUpdateCluster: true
2022/03/12 19:22:15 [DEBUG] isActiveCluster: true isWindowsCluster: false user: , canUpdateCluster: true
2022/03/12 19:22:15 [DEBUG] DesiredSet - No change(2) provisioning.cattle.io/v1, Kind=Cluster fleet-default/c-6dbcx for provisioning-cluster-create c-6dbcx
2022/03/12 19:22:15 [DEBUG] isActiveCluster: true isWindowsCluster: false user: user-fmgbx, canUpdateCluster: true
2022/03/12 19:22:15 [DEBUG] DesiredSet - No change(2) /v1, Kind=Secret fleet-default/c-6dbcx-kubeconfig for cluster-create fleet-default/c-6dbcx
2022/03/12 19:22:15 [DEBUG] Checking and deleting unused certificates for cluster c-6dbcx
2022/03/12 19:22:15 [DEBUG] DesiredSet - No change(2) management.cattle.io/v3, Kind=ClusterRoleTemplateBinding c-6dbcx/c-6dbcx-fleet-default-owner for cluster-create fleet-default/c-6dbcx
2022/03/12 19:22:15 [DEBUG] isActiveCluster: true isWindowsCluster: false user: , canUpdateCluster: true
2022/03/12 19:22:15 [DEBUG] DesiredSet - No change(2) fleet.cattle.io/v1alpha1, Kind=Cluster fleet-default/c-6dbcx for fleet-cluster fleet-default/c-6dbcx
2022/03/12 19:22:15 [DEBUG] isActiveCluster: true isWindowsCluster: false user: , canUpdateCluster: true
2022/03/12 19:22:15 [DEBUG] clusterDeploy: getControlPlaneTaints: Length of nodes for cluster [c-6dbcx] is: 8
2022/03/12 19:22:15 [DEBUG] clusterDeploy: getControlPlaneTaints: toAdd: map[0:{node-role.kubernetes.io/controlplane true NoSchedule <nil>}]
2022/03/12 19:22:15 [DEBUG] clusterDeploy: getControlPlaneTaints: toAdd: map[0:{node-role.kubernetes.io/etcd true NoExecute <nil>}]
2022/03/12 19:22:15 [DEBUG] clusterDeploy: getControlPlaneTaints: allTaints: [{node-role.kubernetes.io/controlplane true NoSchedule <nil>} {node-role.kubernetes.io/etcd true NoExecute <nil>}]
2022/03/12 19:22:15 [DEBUG] isActiveCluster: true isWindowsCluster: false user: user-fmgbx, canUpdateCluster: true
2022/03/12 19:22:15 [DEBUG] isActiveCluster: true isWindowsCluster: false user: , canUpdateCluster: true
2022/03/12 19:22:15 [DEBUG] isActiveCluster: true isWindowsCluster: false user: , canUpdateCluster: true
2022/03/12 19:22:15 [DEBUG] DesiredSet - No change(2) provisioning.cattle.io/v1, Kind=Cluster fleet-default/c-6dbcx for provisioning-cluster-create c-6dbcx
2022/03/12 19:22:15 [DEBUG] Checking and deleting unused certificates for cluster c-6dbcx
2022/03/12 19:22:15 [DEBUG] clusterDeploy: getControlPlaneTaints: Length of nodes for cluster [c-6dbcx] is: 8
2022/03/12 19:22:15 [DEBUG] clusterDeploy: getControlPlaneTaints: toAdd: map[0:{node-role.kubernetes.io/etcd true NoExecute <nil>}]
2022/03/12 19:22:15 [DEBUG] clusterDeploy: getControlPlaneTaints: toAdd: map[0:{node-role.kubernetes.io/controlplane true NoSchedule <nil>}]
2022/03/12 19:22:15 [DEBUG] clusterDeploy: getControlPlaneTaints: allTaints: [{node-role.kubernetes.io/etcd true NoExecute <nil>} {node-role.kubernetes.io/controlplane true NoSchedule <nil>}]
2022/03/12 19:22:15 [DEBUG] DesiredSet - No change(2) /v1, Kind=Secret fleet-default/c-6dbcx-kubeconfig for cluster-create fleet-default/c-6dbcx
2022/03/12 19:22:15 [DEBUG] DesiredSet - No change(2) management.cattle.io/v3, Kind=ClusterRoleTemplateBinding c-6dbcx/c-6dbcx-fleet-default-owner for cluster-create fleet-default/c-6dbcx
2022/03/12 19:22:15 [DEBUG] DesiredSet - No change(2) fleet.cattle.io/v1alpha1, Kind=Cluster fleet-default/c-6dbcx for fleet-cluster fleet-default/c-6dbcx
2022/03/12 19:22:15 [DEBUG] DesiredSet - No change(2) provisioning.cattle.io/v1, Kind=Cluster fleet-default/c-6dbcx for provisioning-cluster-create c-6dbcx
2022/03/12 19:22:15 [DEBUG] Checking and deleting unused certificates for cluster c-6dbcx
2022/03/12 19:22:15 [DEBUG] DesiredSet - No change(2) /v1, Kind=Secret fleet-default/c-6dbcx-kubeconfig for cluster-create fleet-default/c-6dbcx
2022/03/12 19:22:15 [DEBUG] DesiredSet - No change(2) management.cattle.io/v3, Kind=ClusterRoleTemplateBinding c-6dbcx/c-6dbcx-fleet-default-owner for cluster-create fleet-default/c-6dbcx
2022/03/12 19:22:15 [DEBUG] DesiredSet - No change(2) fleet.cattle.io/v1alpha1, Kind=Cluster fleet-default/c-6dbcx for fleet-cluster fleet-default/c-6dbcx
2022/03/12 19:22:16 [DEBUG] 2022/03/12 19:22:16 http: TLS handshake error fro:60925: remote error: tls: unknown certificate
2022/03/12 19:22:17 [DEBUG] 2022/03/12 19:22:17 http: TLS handshake error fro:60927: remote error: tls: unknown certificate
2022/03/12 19:22:18 [DEBUG] clusterDeploy: getControlPlaneTaints: Length of nodes for cluster [c-6dbcx] is: 8
2022/03/12 19:22:18 [DEBUG] clusterDeploy: getControlPlaneTaints: toAdd: map[0:{node-role.kubernetes.io/etcd true NoExecute <nil>}]
2022/03/12 19:22:18 [DEBUG] clusterDeploy: getControlPlaneTaints: toAdd: map[0:{node-role.kubernetes.io/controlplane true NoSchedule <nil>}]
2022/03/12 19:22:18 [DEBUG] clusterDeploy: getControlPlaneTaints: allTaints: [{node-role.kubernetes.io/etcd true NoExecute <nil>} {node-role.kubernetes.io/controlplane true NoSchedule <nil>}]
```

**Note:**

- 1.21.10 to 1.22.7 and  1.21.10 to 1.23.4 upgrades are also stuck in the same state

**Comment by kinarashah** [comment]
Root cause for this issue is the same as https://github.com/rancher/rancher/issues/36860, more details on testing here https://github.com/rancher/rancher/issues/36860#issuecomment-1068545469. 

Node roles were changing during upgrade because of the same issue.

**Comment by Josh-Diamond** [comment]
Ticket #36862 - Test Results

On Docker with single-instance:

Verified on v2.6-1c7aaf427c85717b518d31b3be0661d5b30855af-head:
1. Fresh install of rancher v2.6-head
2. Provision an RKE1 AWS Node driver cluster on k8s `v1.20.15` - cluster A
3. Provision an RKE1 AWS Node driver cluster on k8s `v1.21.10` - cluster B
4. Upgrade cluster A to k8s `v1.21.10`
5. Upgrade cluster B to k8s `v1.22.7`
6. Upgrade cluster A to k8s `v1.22.7`
7. Upgrade cluster B to k8s  `v1.23.4`
8. Upgrade cluster A to k8s `v1.23.4`
9. Verified - both clusters successfully upgraded and stable; clean logs

Screenshot:
<img width="1368" alt="Screen Shot 2022-03-16 at 2 25 25 PM" src="https://user-images.githubusercontent.com/46494969/158693645-af1d14d6-fe5b-4d48-a1fd-dcb15c5e76d2.png">
