### ISSUE TITLE
Move `ensuring designated init node` logs into Debug level 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36870]
**On 2.6-head commit id: `f904267`**

- Deployed an EC2 node driver RKE2 cluster.
- No snapshots were taken
- `ensuring designated init node` message is not seen on the cluster
- And during restore this message is seen a few times in Info level
- logging this bug to move it to debug level

**Comment by Josh-Diamond** [comment]
Ticket #36870 - Test Results

With Docker on single-node instance:

Reproduction Failure on rancher `v2.6-f904267847e9c60b4db76f885654b3ab6a8442cb-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision ec2 rke2 downstream cluster
3. Once provisioned, view `Snapshots` from Cluster Management
4. No snapshots taken; manually take snapshot, and manually restore snapshot
5. Reproduction Failure - no `ensuring designated init node` error in logs


Verified on rancher `v2.6-0ad0def54f87f899a8f9b2a37a1678c9a4fb4e3e-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision ec2 rke2 downstream cluster
3. Once provisioned, view `Snapshots` from Cluster Management
4. Snapshot taken following cluster provisioning is present
5. Take a manual snapshot
6. Set rancher logs to follow on `[DEBUG]` loglevel
7.  Restore cluster to manual snapshot
8. Verified - `ensuring designated init node` error is present in logs on `[DEBUG]` loglevel

Screenshot:
<img width="1192" alt="Screen Shot 2022-04-07 at 1 13 02 PM" src="https://user-images.githubusercontent.com/46494969/162289614-ffe9ca96-7559-4b54-b4a5-4787ad5c4532.png">
