### ISSUE TITLE
[Rancher-UI] Upgrading/Cloning service to "always restart" doesnt remove the io.rancher.container.start_once label

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#3688]
Rancher Version: v0.56.1

Docker Version: 1.9.1

OS: Ubuntu

Steps to Reproduce: 
1. Create a service in the UI and set restart to "Never (Run once)"
2. Upgrade service restart to "Always"

Results: 
1. After upgrade, restart policy is still set to Never.
2. Even cloning the service continues to propagate the "Never"

Expected:
The upgrade should change the restart policy.

**Comment by alena1108** [comment]
@nhumrich restart policy is disregarded by service V1 API. As service.reconcile will always restart service instances if they die, we didn't want to docker-restart policy interfere.

**Comment by vincent99** [comment]
This is a UI bug that it offers the option to change the scale radio choice on upgrade..

**Comment by nhumrich** [comment]
Wait, so once I set a service to restart once, I can never get to back to a restart always case? Not even with cloning?

**Comment by vincent99** [comment]
Gah, sorry I misread this as global scale ("run one instance on every host...").  Run once is a label that's probably still a bug that it's not getting removed by the UI.

**Comment by deniseschannon** [comment]
Confirmed that this is the issue that once the label is added `io.rancher.container.start_once: true`, it's never removed.

**Comment by vincent99** [comment]
Part of #3707
