### ISSUE TITLE
Can't execute some commands on Rancher Kubectl Shell due to old Kubectl Client installed by default

### ISSUE THREAD

**Issue by mhmtsvr** [rancher/rancher#36883]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option:
   - Helm Chart
   - Kubernetes Cluster version: EKS 1.21

**Describe the bug**
Kubectl Client (v1.19.7) installed in Rancher Kubectl Shell causes some commands not being able to get executed. Especially this is an issue with clusters 1.19+. According to the [Rancher documentation](https://rancher.com/docs/rancher/v2.5/en/cluster-admin/cluster-access/), it requires no configuration actions on our part. Any actions that we can take to upgrade kubectl in Rancher Kubectl Shell? If not, I'd highly appreciate if you could consider this upgrade soon.

**To Reproduce**
- Create any job on clusters 1.21
  - `$ kubectl create job --from=cronjob/example-job example-job1`
```  
error: from must be an existing cronjob: no kind "CronJob" is registered for version "batch/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

  - `$ kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
**Result**

**Expected Result**

**Screenshots**
![Screen Shot 2022-03-14 at 1 45 39 PM](https://user-images.githubusercontent.com/29622823/158230691-61d2993d-f57b-4e11-a228-b49b3ebbe50e.png)

**Additional context**

**Comment by hoerup** [comment]
Rancher/shell has been updated to use kubectl 1.21 - i assume this will come out together with rancher 2.6.4 ??

https://github.com/rancher/shell/commit/d435e41400631902b07e32828c8003c88de9a707
