### ISSUE TITLE
Panic in Machine on v2.6-head

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#36887]
After adding some of the vsphere features in machine we're not finding a weird panic deep in machine. We're trying to isolate if this is config or what actually is happening. This is a place holder issue until we find the root cause but it needs to be sorted for v2.6.4

**Comment by rosskirkpat** [comment]
Related issues:

https://github.com/rancher/rancher/issues/36891
https://github.com/rancher/rancher/issues/36691  -> specific to RKE1 provisioning

**Comment by rosskirkpat** [comment]
panic as seen for rke1 vsphere clusters:

```console
2022/03/15 16:24:24 [ERROR] error syncing 'c-kj5j5/m-2fcg5': handler node-controller: Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: invalid memory address or nil pointer dereference, requeuing
```

**Comment by rosskirkpat** [comment]
Machine PR to fix the panic: https://github.com/rancher/machine/pull/169
Rancher PR for the jailer fix and to also bump the machine version once we have a new release: https://github.com/rancher/rancher/pull/36927

**Comment by rosskirkpat** [comment]
Closing in favor of https://github.com/rancher/windows/issues/18
