### ISSUE TITLE
v2prov cluster etcd snapshot restore "all" option doesn't work all the time

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#36885]
When restoring an etcd snapshot with the v2prov framework, the `restore all` option does not work as it is erroneously attempting to compare the full specifications between objects which is incorrect behavior as we are only selectively restoring certain fields.

**Comment by timhaneunsoo** [comment]
https://github.com/rancher/rancher/issues/37001

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head b7c9b89
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2

----------

### Testing: ###

Tested this issue with the following steps

1. Provision a downstream RKE2 custom cluster (3 nodes and 8 node cluster tested)
2. As an admin take a snapshot (cluster manager, cluster menu, take snapshot)
3. Wait for the snapshot to be created
4. Create a workload
5. Restore to the snapshot you took at step 3 (cluster manager -> cluster menu -> restore snapshot -> select "Cluster config, Kubernetes version and etcd"

**Result** - Pass

Restore all option was successful and clusters became active after snapshot was restored
