### ISSUE TITLE
[RKE1] kube-scheduler HTTPs ports cannot perform authn / authz by default

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#36899]
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart): docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: RKE v1.23.4-rancher1-1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): imported

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

More information on the original ticket here: https://github.com/rancher/rancher/issues/35751

kube-scheduler was not fixed in the original issue and the validation that was performed was only done on kube-controller-manager. Leaving new steps to reproduce here to address the difference.

**To Reproduce**
 

- Spin up an RKE1 cluster
- Grab an auth token: for example, use the following one-line for the default token`TOKEN=$(kubectl get secrets -o jsonpath="{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='default')].data.token}"|base64 -d)`
- Log onto a controlplane host and try to run `curl https://localhost:10259/metrics -k -H "Accept: application/json" -H "Authorization: Bearer ${TOKEN}"`

**Result**
No matter what token you use, you will always see a 403 to query the endpoint due to the fact that you are an **anonymous** user.

**Expected Result**

What we see with kube-controller-manager, which is a failure but a failure that indicates kube-controller-manager at least reached out to find out who this user is.

**Screenshots**

**Additional context**

On the RKE version that I have listed above, you can easily see what the issue is by running the following two commands and seeing the output:

```bash
# kube-controller-manager
root@arvind-1-23-monitoring-downstream-server:~# curl https://localhost:10257/metrics -k -H "Accept: application/json" -H "Authorization: Bearer ${TOKEN}"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:serviceaccount:default:default\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
# kube-scheduler
root@arvind-1-23-monitoring-downstream-server:~# curl https://localhost:10259/metrics -k -H "Accept: application/json" -H "Authorization: Bearer ${TOKEN}"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

The difference is that one returns `forbidden: User \"system:serviceaccount:default:default\" cannot get path \"/metrics\"` v.s. `forbidden: User \"system:anonymous\" cannot get path \"/metrics\"`; even though they are using the same token, kube-scheduler is not trying to figure out who that token belongs to so it will always return anonymous and not allow access.

**Comment by kinarashah** [comment]
### Root cause

There was a bug in the command generated for `kube-scheduler` in RKE1. command was generated before the authentication and authorization kubeconfig were set so they were passed to `kube-scheduler`. 
 
### What was fixed, or what changes have occurred

Moved the commandArgs setting before command was generated. 
 
### Areas or cases that should be tested

- any RKE1 cluster to check if kube-scheduler gets the right args (k8s version should be 1.23) 
- the curl requests mentioned in the issue description continue to work 
- doesn't impact above curl requests for k8s 1.22 clusters 

### What areas could experience regressions?

N/A
 
### Are the repro steps accurate/minimal?

yes

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6-head

**Rancher Server :**
- Version : v2.6-head(024e6fa)
- docker install

**Validation steps followed :**
- Provisioned RKE1, `v1.23.4-rancher1-1` and `v1.22.7-rancher1-1` clusters -> single node, ec2 node driver.
- Fetched the token on both the clusters using `TOKEN=$(kubectl get secrets -o jsonpath="{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='default')].data.token}"|base64 -d)`
- SSH'ed into node and ran `curl https://localhost:10259/metrics -k -H "Accept: application/json" -H "Authorization: Bearer ${TOKEN}"`

**Result :**
1) **On `v1.23.4-rancher1-1` cluster :** Below request to kube-scheduler shows it was able to identify the user based on the service account token.
```
curl https://localhost:10259/metrics -k -H "Accept: application/json" -H "Authorization: Bearer ${TOKEN}"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:serviceaccount:default:default\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```
- Also `--authentication-kubeconfig` and `--authorization-kubeconfig` args are present :
```
ps -ef | grep -i kube-scheduler
root        8733    8711  0 05:31 ?        00:00:51 kube-scheduler --address=0.0.0.0 --leader-elect=true --authentication-kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-scheduler.yaml --authorization-kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-scheduler.yaml --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-scheduler.yaml --profiling=false --v=2
```

2) **On `v1.22.7-rancher1-1` cluster :** The user is present
```
curl https://localhost:10259/metrics -k -H "Accept: application/json" -H "Authorization: Bearer ${TOKEN}"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:serviceaccount:default:default\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```
- `--authentication-kubeconfig` and `--authorization-kubeconfig` args also present to the kube-sceduler:
```
ps -ef | grep -i kube-scheduler
root        8775    8754  0 08:14 ?        00:00:36 kube-scheduler --leader-elect=true --authentication-kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-scheduler.yaml --authorization-kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-scheduler.yaml --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-scheduler.yaml --profiling=false --v=2 --address=0.0.0.0
```
