### ISSUE TITLE
cacerts is an x509 certificate

### ISSUE THREAD

**Issue by streetglow-code** [rancher/rancher#36893]
Hello Team,
I am trying to create a kubernetes cluster in Rancher.

I followed the article:  https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/aks/

The Rancher is hosted in-side the AKS cluster.

When I tried to add a cluster after executing the command :

![image](https://user-images.githubusercontent.com/69821901/158352250-4f290085-25bf-4b9e-ab58-30be2fbeec88.png)

I checked the docker logs and found

![image](https://user-images.githubusercontent.com/69821901/158352357-0f39f746-6b16-41fc-9cba-9a7052bf7a37.png)

Error: 
root@master-1:~# docker logs 35df8f5d1b59 | grep error
INFO: Arguments: --server https://rancher1.streetglow64.in --token REDACTED --ca-checksum e80ff971ccc8ff3a735b38afb8b574b0118ecb2e169e118a76e31670b70b1a15 --etcd --controlplane
INFO: Environment: CATTLE_ADDRESS=10.1.0.4 CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=master-1 CATTLE_ROLE=,etcd,controlplane CATTLE_SERVER=https://rancher1.streetglow64.in CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 127.0.0.53 options edns0 search cuy5e1yhh2iuvci5mq0zed41bb.rx.internal.cloudapp.net
WARN: Loopback address found in /etc/resolv.conf, please refer to the documentation how to configure your cluster to resolve DNS properly
INFO: https://rancher1.streetglow64.in/ping is accessible
INFO: rancher1.streetglow64.in resolves to 20.204.239.209
INFO: Value from https://rancher1.streetglow64.in/v3/settings/cacerts is an x509 certificate
time="2022-03-15T09:37:36Z" level=error msg="Failed to connect to proxy. Response status: 400 - 400 Bad Request. Response body: Operation cannot be fulfilled on nodes.management.cattle.io \"m-f62b16dbe661\": the object has been modified; please apply your changes to the latest version and try again" error="websocket: bad handshake"
time="2022-03-15T09:37:36Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"

**Comment by streetglow-code** [comment]
I have checked the logs and found 

![image](https://user-images.githubusercontent.com/69821901/158355962-c44f9c9e-b8b0-4241-9294-23c2f87d18a7.png)

**Comment by kpanic9** [comment]
Might be same as #36589
