### ISSUE TITLE
Calico Probes Fail on Windows Nodes in 2.6.0-2.6.3 for RKE2 Installation

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#36910]
We have found that in v2.6.3 when you do an RKE2 cluster with a windows node that you will get back messages on the UI stating `Waiting on probes: calico`.

![image (14)](https://user-images.githubusercontent.com/1616909/158481786-70f53f34-fb63-49c0-a15d-2d18a530cb1e.png)

This is happening because the wins agent is not pinned properly in the released version of v2.6.3, that is now fixed by this PR: https://github.com/rancher/rancher/pull/36909

**WORKAROUND/FIX FOR 2.6.3:** 

If you stumble across this issue you can try to fix this in your Rancher settings by navigating to `https://<rancherserverurl>/v3/settings/windows-rke2-install-script`. Change the setting from `https://raw.githubusercontent.com/rancher/wins/v0.1.3/install.ps1` to but should be `https://raw.githubusercontent.com/rancher/rke2/master/windows/rke2-install.ps1` in v2.6.3. Wins was only introduced in yet to be released v2.6.4

**Comment by sirredbeard** [comment]
Testing template is pending, after outstanding regressions are addressed.

**Comment by luthermonson** [comment]
### Root cause
probes in system agent were fixed and when the calico probe was run on a windows node we found out that calico doesn't boot the end point the probe checks causing the probe to fail.

### What was fixed, or what changes have occurred
in v2.6.4 and moving forward the calico probe is disabled. this however regressed versions pre v2.6.4 due to pinning issues and a default install using upstream wins installer with the latest version of system agent. to fix this you can change the settings for where to download wins and use the previous version but ultimately v.2.6.4 is actually supposed to use the old rke2-installer

### Areas or cases that should be tested
1. boot v.2.6.3 and try to make a windows custom cluster, see the calico probes fail.
2. update the install script as advised in above and boot a new cluster and see it working.

### What areas could experience regressions?
pre v.2.6.4 

### Are the repro steps accurate/minimal?
yes

**Comment by deniseschannon** [comment]
@luthermonson What needs to be tested on 2.6.4 that this is now fixed?

**Comment by sirredbeard** [comment]
Testing this should be covered by a standard deploy after 2.6.4. No specific test plan should be required.

**Comment by slickwarren** [comment]
I am able to deploy a custom cluster using rke2 on rancher v2.6-head (cd0555b):
* deploy rke2 custom cluster using 1.22.8+rke2r1
  * add a windows node (used version 2022)
* deploy some workloads -- pass

**Comment by jtravee** [comment]
Confirmed w/ @slickwarren that no release note needed for 2.6.5 as we already included in 2.6.4.
