### ISSUE TITLE
UI Prometheis, should be Prometheus

### ISSUE THREAD

**Issue by dbravo0531** [rancher/rancher#36918]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.7+k3s1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

   
**Describe the bug**

**To Reproduce**
 

**Result**

**Expected Result**

**Screenshots**

<img width="766" alt="image" src="https://user-images.githubusercontent.com/98564961/158640443-6769b81e-cedd-4aa1-b9d2-87d9b05cbdd4.png">

**Additional context**

**Comment by Martin-Weiss** [comment]
Check this out https://github.com/rancher/rancher/issues/34904 and https://youtu.be/B_CDeYrqxjQ
(I also do not understand why there is a CRD is called prometheuses.monitoring.coreos.com ;-))
