### ISSUE TITLE
Docker startup fails with Rancher agent set to "restart: always"

### ISSUE THREAD

**Issue by slaschinski** [rancher/rancher#3691]
Rancher Version: 0.56.1

Docker Version: 1.9.1, build 7206621

OS: Fedora 23

Steps to Reproduce: Install Fedora 23, expand volume group to get some free space in lvm for docker, start docker (it will create a thin pool in the root volume group), install Rancher agent, stop Docker, start Docker

Results: Docker fails to get startet. I can't pin it down to one single error message, but overall the Docker service fails to come up and isn't able to start anymore until restarting the whole machine, even if the rancher agent isn't set to "restart: always". If I start the rancher-agent manually, a few seconds after the docker service is done starting, everything works without any errors. 

Expected: Beeing able to start Docker with rancher-agent set to "restart: always".

I can provide some log files, if needed, but I'm not sure what to include and it should happen on every Fedora 23 host anyway, since i've tried it in different environments many, many times with fresh installations of Rancher and Fedora, it never worked. Not even once. Some other Docker containers I've used have no such problem.

**Comment by deniseschannon** [comment]
You shouldn't set `--restart=always` on the rancher/agent command as we actually end up starting 3 containers to get the rancher-agent container running. There is the first container which is a docker named container and can be deleted if you wanted. The second container which is a data container for the rancher/agent that is stopped and named `rancher-agent-state` The last container which is the one that stays running already has `restart: always` set and will be called `rancher-agent`. 

If you don't add in the `--restart=always`, do you have the same issues?

**Comment by slaschinski** [comment]
I didn't add anything. I've just copied the command line like it's shown in Rancher. But you've said exactly the same as I did. The `rancher-agent` is started with `restart: always`. And that one is causing the problems. I have to change that policy manually, by editing the json file of that container. Otherwise I'm not able to start Docker anymore.

**Comment by deniseschannon** [comment]
@slaschinski have you tried this on different OS to see if it's an issue only on Fedora 23? We don't face these issues on other OSes. Could you see if this is an issue with Fedora 24?

**Comment by deniseschannon** [comment]
@slaschinski if this is still an issue, please let me know.

**Comment by wadjeroudi** [comment]
@deniseschannon Shouldn't the rancher agent be on restart always too (I get it about the 3 commands but it should handle the case) ? Because when you reboot, the host won't be recognized by rancher server.
On a blogpost, someone proposes to add an autostart unix service.
http://anlek.com/2016/07/rancher-agent-start-on-reboot/

What is the best practice ? Thx.

**Comment by cjellick** [comment]
@wadjeroudi the container that is named rancher-agent, the final 1 of the 3 start and the one that matters, should and typically does have an always restart policy. If you are seeing something different, its a bug.
```
docker inspect rancher-agent | grep -i -A3 RestartPolicy
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
```

**Comment by wadjeroudi** [comment]
@cjellick Thanks. Don't why but before I was on v1.2.0-pre3, it didn't autostart, it does now. Sorry.
