### ISSUE TITLE
Rancher is not able to upgrade with RKE2 clusters

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#36924]
**Rancher Server Setup**
- Rancher version: v2.6-head (1c7aaf427c85717b518d31b3be0661d5b30855af)
- Installation option (Docker install/Helm Chart): Both
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Any
- Proxy/Cert Details: self-signed

**Information about the Cluster**
- Kubernetes version: Any
- Cluster Type (Local/Downstream): Local

**Describe the bug**
Upgrading Rancher with RKE2 clusters fails.

**To Reproduce**
1. On Rancher v2.6.3, provision an RKE2 cluster (single-node cluster is fine).
2. Try to upgrade Rancher to v2.6-head (commit 1c7aaf427c85717b518d31b3be0661d5b30855af was used to find the problem)

**Result**
The upgrade won't complete. The Rancher pod (or Docker container) will crash.

**Expected Result**
Upgrade should work.

**Additional context**
This issue was caused by https://github.com/rancher/rancher/pull/36725

**Comment by sowmyav27** [comment]
**On an upgrade from 2.6.3 to 2.6-head commit id: `5bb08b3`**

- RKE2 cluster, the nodes get re provisioned, and the cluster comes up Active.

**Comment by sowmyav27** [comment]
@thedadams Seems like Josh hit this issue just sometime back.
@Josh-Diamond can you please add your comments, and please reach out to Donnie with your rancher server setup details.

**Comment by Josh-Diamond** [comment]
Yes, I was upgrading from rancher `v2.6.3` to `v2.6.4-rc10`, (not to `v2.6-head) .. my findings are as follows:

**Rancher Server Setup**
- Rancher version: `v2.6.3`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `v1.21.9+k3s1`
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `v1.21.9+rke2r1`
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
AWS Node driver provisioned RKE2 cluster - 8 nodes (3 etcd, 2 cp, 3 wkr)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
   Admin
 


   
**Describe the bug**
RKE2 provisioned cluster failed to stabilize as `active` following rancher upgrade from `v2.6.3` => `v2.6.4-rc10`

**To Reproduce**
1. Fresh install of HA rancher w/ `v1.21.9+k3s1`
2. Enable auth - (openLDAP)
3. Enable monitoring on local
4. As standard user, provision AWS Node driver RKE2 cluster
5. Once stable and `active`, upgrade rancher from `v2.6.3` => `v2.6.4-rc10`
6. Reproduced - Post upgrade, RKE2 cluster fails to stabilize as `active`

**Result**
Errors are encountered and pods are continuously re-deployed in an effort to correct the error with no resolve

**Expected Result**
RKE2 cluster should stabilize as `active`

**Screenshots**
<img width="1226" alt="Screen Shot 2022-03-21 at 5 32 59 PM" src="https://user-images.githubusercontent.com/46494969/159386788-0876bd9c-c059-45a6-98db-f047597e987b.png">

<img width="1219" alt="Screen Shot 2022-03-21 at 5 46 44 PM" src="https://user-images.githubusercontent.com/46494969/159386815-8346d1ac-8cc6-47fe-95c4-538a9c2e7d00.png">


**Additional context**
Logs:
`apply-system-agent-upgrader-on-[cluster_name]-[pod_name]_upgrade.log`
```logs
+ TMPDIRBASE=/var/lib/rancher/agent/tmp
+ mkdir -p /host/var/lib/rancher/agent/tmp
+ chroot /host /bin/sh -c 'mktemp -d -p /var/lib/rancher/agent/tmp'
+ TMPDIR=/var/lib/rancher/agent/tmp/tmp.vIeSeMrK4g
+ cp /opt/rancher-system-agent-suc/install.sh /host/var/lib/rancher/agent/tmp/tmp.vIeSeMrK4g
+ cp /opt/rancher-system-agent-suc/rancher-system-agent /host/var/lib/rancher/agent/tmp/tmp.vIeSeMrK4g
+ chmod +x /host/var/lib/rancher/agent/tmp/tmp.vIeSeMrK4g/install.sh
+ '[' -n jkeslar-cluster-02-jkeslar-cluster-02-cp-056fa53a-rgr79 ]
+ NODE_FILE=/host/var/lib/rancher/agent/tmp/tmp.vIeSeMrK4g/node.yaml
+ kubectl get node jkeslar-cluster-02-jkeslar-cluster-02-cp-056fa53a-rgr79 -o yaml
+ '[' -z  ]
+ grep -q 'node-role.kubernetes.io/etcd: "true"' /host/var/lib/rancher/agent/tmp/tmp.vIeSeMrK4g/node.yaml
+ '[' -z  ]
+ grep -q 'node-role.kubernetes.io/controlplane: "true"' /host/var/lib/rancher/agent/tmp/tmp.vIeSeMrK4g/node.yaml
+ '[' -z  ]
+ grep -q 'node-role.kubernetes.io/control-plane: "true"' /host/var/lib/rancher/agent/tmp/tmp.vIeSeMrK4g/node.yaml
+ '[' -z  ]
+ grep -q 'node-role.kubernetes.io/worker: "true"' /host/var/lib/rancher/agent/tmp/tmp.vIeSeMrK4g/node.yaml
+ export 'CATTLE_AGENT_BINARY_LOCAL=true'
+ export 'CATTLE_AGENT_BINARY_LOCAL_LOCATION=/var/lib/rancher/agent/tmp/tmp.vIeSeMrK4g/rancher-system-agent'
+ '[' -s /host/etc/systemd/system/rancher-system-agent.env ]
+ chroot /host /var/lib/rancher/agent/tmp/tmp.vIeSeMrK4g/install.sh
[FATAL]  You must select at least one role.

```

**Comment by thedadams** [comment]
@Josh-Diamond @sowmyav27 That is a different problem related to https://github.com/rancher/rke2/issues/2583

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver

----------

### Testing: ###

Tested this issue with the following steps:
1. On Rancher v2.6.3, provision an RKE2 cluster (single-node cluster is fine).
2. Try to upgrade Rancher to v2.6-head (commit 1c7aaf427c85717b518d31b3be0661d5b30855af was used to find the problem)

**Result** - Pass

Single-node cluster with all roles - Pass
3 node cluster with 1 role for each node - Pass
5 node cluster with 1 etcd, 1 cp, 3 worker - Pass
5 node cluster with 3 etcd, 1 cp, 1 worker - Pass
8 node cluster 3 etcd, 2 cp, 3 workers - Pass
