### ISSUE TITLE
[v2.6] KDM Update for K8s March patch release

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#36938]
# KDM Updates
TO BE RELEASED: Enabled in Rancher v2.6.5

| New Kubernetes Version | Min Rancher Version | Min RKE Version |
| ---------------------- | ------------------- | --------------- |
| 1.23.5-rancher1-1      | 2.6.4-rc0                 | 1.3.3-rc0             |
| 1.22.8-rancher1-1      | 2.6.3-rc0                 | 1.3.3-rc0             |
| 1.21.11-rancher1-1      | 2.6.0-rc0                 | 1.3.0-rc0             |

### Rancher System Images & Add-ons
**_Note: Please update system images and add-ons in the template as needed._**

TBD

# Developer Changelog
- Add templates for new K8s versions. If a template that hasn't been released yet already exists, update it in place.
- Update the default K8s version, and add or update the version information (`MinRancherVersion` and `MinRKEVersion`) in [k8s_version_info.go](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/k8s_version_info.go) for new K8s versions if needed (Use table from above).
- Confirm versions for system images, add-on templates are correct using versioning reference table from below (expand details to view the table). Update the table if new versions are introduced.
- Confirm add-on template version constraints in [template.go](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) are correct using versioning reference table from below (expand details to view the table). Update the table if needed.

# Versioning Reference
<details>
<summary>
Expand for system images & add-on templates versioning table
</summary>
</br>

**_Note: Truncated repository names with a `*` indicates there are multiple images with that prefix. All repository names that match a truncated prefix should be checked for the same version stated in the table._**
**_For example: `rancher/weave-*` matches `weaveworks/weave-kube` and `weaveworks/weave-npc`, and they should both have the same version._**

## v1.23.4-rancher1-1
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.4.16-rancher1      |
| rancher/hyperkube                                        | v1.23.5-rancher1      |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/mirrored-k8s-dns-*                               | 1.17.4                |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/mirrored-coreos-flannel                          | v0.15.1               |
| rancher/flannel-cni                                      | v0.3.0-rancher6       |
| rancher/mirrored-calico-*                                | v3.19.1               |
| weaveworks/weave-*                                       | 2.8.1                 |
| noiro/* (All ACI images)                                 | 5.1.1.0.1ae238a       |
| rancher/mirrored-pause                                   | 3.4.1                 |
| rancher/nginx-ingress-controller                         | nginx-1.1.0-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.5.1                |
| rancher/mirrored-coredns-coredns                         | 1.8.4                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.18.0                |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov319                         |
| Canal         | canalv3211                          |
| Flannel       | flannelv0140                       |
| CoreDNS       | coreDnsv183                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv050                  |
| Weave         | weavev120                          |
| Aci           | aciv500                            |
| NginxIngress  | nginxIngressv110Rancher3                  |
| Nodelocal     | nodelocalv121                      |

## v1.22.7-rancher1-1
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.4.16-rancher1      |
| rancher/hyperkube                                        | v1.22.8-rancher1      |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/mirrored-k8s-dns-*                               | 1.17.4                |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/mirrored-coreos-flannel                          | v0.15.1               |
| rancher/flannel-cni                                      | v0.3.0-rancher6       |
| rancher/mirrored-calico-*                                | v3.19.1               |
| weaveworks/weave-*                                       | 2.8.1                 |
| noiro/* (All ACI images)                                 | 5.1.1.0.1ae238a       |
| rancher/mirrored-pause                                   | 3.4.1                 |
| rancher/nginx-ingress-controller                         | nginx-1.1.0-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.5.1                |
| rancher/mirrored-coredns-coredns                         | 1.8.4                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.18.0                |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov319                         |
| Canal         | canalv3211                          |
| Flannel       | flannelv0140                       |
| CoreDNS       | coreDnsv183                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv050                  |
| Weave         | weavev120                          |
| Aci           | aciv500                            |
| NginxIngress  | nginxIngressv110Rancher3                  |
| Nodelocal     | nodelocalv121                      |

## v1.21.10-rancher1-1
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.4.16-rancher1      |
| rancher/hyperkube                                        | v1.21.11-rancher1      |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/mirrored-k8s-dns-*                               | 1.17.4                |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/mirrored-coreos-flannel                          | v0.15.1               |
| rancher/flannel-cni                                      | v0.3.0-rancher6       |
| rancher/mirrored-calico-*                                | v3.19.1               |
| weaveworks/weave-*                                       | 2.8.1                 |
| noiro/* (All ACI images)                                 | 5.1.1.0.1ae238a       |
| rancher/mirrored-pause                                   | 3.4.1                 |
| rancher/nginx-ingress-controller                         | nginx-1.1.0-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.5.0                |
| rancher/mirrored-coredns-coredns                         | 1.8.4                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.18.0                |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov319                         |
| Canal         | canalv319                          |
| Flannel       | flannelv115                       |
| CoreDNS       | coreDnsv183                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv050                  |
| Weave         | weavev120                          |
| Aci           | aciv500                            |
| NginxIngress  | nginxIngressv110Rancher3                  |
| Nodelocal     | nodelocalv121                      |

</details>

**Comment by vivek-infracloud** [comment]
RKE PR is not up yet, also the rancher v2.6.5-rcX is not ready. Hence, reopened the issue.

**Comment by vivek-infracloud** [comment]
### Fresh install checks and upgrade checks looks good.

**Provisioning Checks on Fresh Install of Rancher 2.6.5-rc1 - PASS**

1. KDM points to dev-v2.6 branch.
2. Cluster creation succeeds for 1.23.5-rancher1-1, 1.22.8-rancher1-1, 1.21.11-rancher1-1 k8s versions with all network providers
3. Network checks succeeded for all new clusters
4. Ran validation tests for Canal cluster.
5. Network checks and Canal checks pass.

**Provisioning Checks after Upgrading to new KDM - PASS** 

1. On latest released v2.6.5-rc1, KDM points to release-v2.6
2. Cluster creation succeeds for old k8s versions with all network providers.
3. Ran pre-upgrade checks 
4. Point KDM to dev-2.6 branch.
5. Upgrade k8s to the latest patches v1.23.5-rancher1-1, 1.22.8-rancher1-1, 1.21.11-rancher1-1
6. Ran post-upgrade checks
7. Pre-Upgrade and Post-Upgrade checks pass.

**RKE checks using 1.3.10-rc3 passed for v1.23.5-rancher1-1, 1.22.8-rancher1-1, 1.21.11-rancher1-1 k8s version.**

**RKE default k8s version  -**  
dev-v2.6 should have the default as v1.22.8-rancher1-1

{
"RKEDefaultK8sVersions": {
"0.3": "v1.16.3-rancher1-1",
"default": "v1.22.8-rancher1-1"
 }

**Comment by vivek-infracloud** [comment]
**Closing the issue since all the checks passed.**

**Comment by snasovich** [comment]
This is now superseded by https://github.com/rancher/rancher/issues/37388 since March patches were not formally released in KDM. These versions are removed per https://github.com/rancher/kontainer-driver-metadata/pull/889.
