### ISSUE TITLE
Run Conformance Tests for 1.23

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36931]
**Task** 
v1.23 is available for rancher v2.6.4. We should run conformance tests on this version

**Comment by vivek-infracloud** [comment]
**Rancher Server Setup**

- Rancher version:v2.6.4-rc9
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details:Selfsigned

**Information about the Cluster**

- Kubernetes version:v1.23.4
- Cluster Type (Local/Downstream): 
  - Downstream 1 Node with CP, ETCD and Worker, 2 Worker nodes.

**To Reproduce**
- Create downstream cluster on Rancher v2.6.4-rc9 with NGINX Ingress turned off.
- Once the cluster is up and active, update the kube_api with following extra argument.
 ```
   extra_args:
        service-account-issuer: https://<cp_ip>:6443
```
(`<cp_ip>` is Public/External IP of Control Plane)
- Run conformance test

**Results**
```
Ran 346 of 7042 Specs in 5412.439 seconds
SUCCESS! -- 346 Passed | 0 Failed | 0 Pending | 6696 Skipped
PASS

Ginkgo ran 1 suite in 1h30m14.5888112s
Test Suite Passed
```

**Comment by vivek-infracloud** [comment]
Rancher conformance test results PR on cncf: https://github.com/cncf/k8s-conformance/pull/1835

**Comment by vivek-infracloud** [comment]
Above PR failed to pass all the required tests. Following is the error.
![cncd-failure](https://user-images.githubusercontent.com/83208989/158819208-4e21cf6f-4a94-4696-b499-8616b8a12da8.png)
In my opinion the image has been moved and we may have to change the URL. @slickwarren 

Here is a comment on the cncf PR.
https://github.com/cncf/k8s-conformance/pull/1835#issuecomment-1070915440

**Comment by vivek-infracloud** [comment]
Updated the URL to following.
https://rancher.com/assets/img/brand-guidelines/assets/logos/png/color/rancher-logo-horiz-color.png

PR should pass all the requirements.
