### ISSUE TITLE
[RKE2 snapshot] Standard User that is Cluster Owner cannot take snapshots

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#36943]
**Rancher Server Setup**
- Rancher version: v2.6-head d604b7e
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.10+rke2r2
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AWS EC2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Standard User that is Cluster Owner
   
**Describe the bug**

When the user takes a snapshot, Rancher seems to be taking a snapshot but there is no snapshot saved and snapshot list is empty. When attempting to do the same action on the same cluster with Admin user, everything seems to be working as expected

**To Reproduce**
 
1. Create RKE2 cluster
2. Take snapshot of cluster

**Result**
Cluster goes into provisioning state and seems to be taking a snapshot, but snapshot list is empty. 

**Expected Result**

Standard User should be able to take snapshot as a cluster owner

**Screenshots**

![image](https://user-images.githubusercontent.com/97477402/158842240-322489f0-8c2f-4133-b9ce-1a86c0e1fc1d.png)

**Comment by Oats87** [comment]
I'm unable to reproduce this on my end, will keep investigating tomorrow.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head b8cbc1a
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver cluster

----------

### Testing: ###

Tested this issue with the following steps:
1. Create RKE2 cluster as standard user
2. Take snapshot of cluster once cluster is Active

**Result** - Pass

The UI is now showing the snapshots taken by Cluster owner as a standard user.

![image.png](https://zube.io/files/rancher/af754e6ceaa2b9129f09ed05fb8974a5-image.png)


There is a difference in the file size, ticket is logged here [37382](https://github.com/rancher/rancher/issues/37382)
