### ISSUE TITLE
dig on service name does not return ipaddress of the containers of the service. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3694]
Rancher Version: Build from master

Docker Version:1.10.2

OS:  Ubuntu 14.04 hosts

Steps to Reproduce: 
Create 2 services - hello1, hello2 in default stack.
From containers of hello1 service , execute dig <hello2>  +short.

Results: 
No ip addresses are returned.

Expected:
Ip address of all the containers in hello2 should be returned.

**Comment by alena1108** [comment]
should be fixed on the latest

**Comment by sangeethah** [comment]
Tested with latest build from master.
Dig on service name resolves to ip address of the service instances.
