### ISSUE TITLE
[RKE2 snapshots] age of existing snapshots as new ones are taken after scaling up etcd nodes

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#36948]
**Rancher Server Setup**
- Rancher version: v2.6-head d604b7e
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.23.4+rke2r2
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): EC2 aws node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Cluster Owner

   
**Describe the bug**

The age of existing snapshots changes as new ones are taken after scaling up etcd nodes.
The issue [here](https://github.com/rancher/rancher/issues/36697) is found after scaling up etcd nodes [here](https://github.com/rancher/rancher/issues/36794)

**To Reproduce**
 
1. create the RKE2 cluster with 1 etcd node, 2 control plane, 2 workers
2. makes a snapshot
3. restore that snapshot
4. scale etcd nodes to 3
5. make some new snapshots

**Result**
The snapshot taken in step 2 will change age along with the new snapshots made in step 5

**Expected Result**

The age of the snapshot should be preserved

**Screenshots**

![image](https://user-images.githubusercontent.com/97477402/158882051-c6f27f4b-752d-4f70-9b0d-851ed2bd4e92.png)

**Comment by snasovich** [comment]
@Oats87 , could you take a look into it? Is this Rancher issue or RKE2 one?
