### ISSUE TITLE
[2.5 Backport] Backport Steve API Fix

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#36954]
Related to harvester/harvester#1857.

Backport the fix for Steve (rancher/steve#37) introduced as a fix for that issue to 2.5.

**Comment by sowmyav27** [comment]
More info from @MbolotSuse 
```
This has nothing to do with harvester. Bug is that steve will loop through various resource type (e.g. secrets, pods, namespaces, nodes, etc.) for a random resource name. 
```

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

>See internal documentation for more details.

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                                                                                   |
| ------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------ |
| Rancher version           | v2.5-a6aaa980f60564fb602fea63981c15f4623b2553-head [a6aaa98](https://github.com/rancher/rancher/commit/a6aaa980f60564fb602fea63981c15f4623b2553) |
| Installation option       | Helm high availability (in AWS)                                                                                                                  |
| RKE binary version used   | v1.2.14                                                                                                                                          |
| If Helm Chart k8s cluster | v1.20.12-rancher1-1                                                                                                                              |
| Cert Details              | ingress.tls.source=secret (certificates from files)                                                                                              |
| Docker version            | 20.10.7, build f0df350                                                                                                                           |
| Helm version              | v2.16.8-rancher1                                                                                                                                 |
| Downstream cluster type   | not applicable                                                                                                                                   |
| Downstream K8s version    | not applicable                                                                                                                                   |
| Logged in user role       | Administrator                                                                                                                                    |
| Browser type              | Google Chrome                                                                                                                                    |
| Browser version           | 100.0.4896.60 (Official Build) (x86_64)                                                                                                          |


## Validation steps

>See internal documentation for additional details.

## RESULTS

✅  Checks passed!
