### ISSUE TITLE
[harvester IPAM load balancer] LB service included a space in the random string for its name

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36956]
**Rancher Server Setup**
- Rancher version: v2.6.4-rc9
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.22.7+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): harvester node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): tested with admin

   
**Describe the bug**
when creating an LB through a workload, the service name had a ` ` in it, preventing the service from coming up. (not always reproducible)

**To Reproduce**
* deploy a cluster with rke2 harvester node driver (cloud provider enabled)
* deploy a workload on the cluster with an IPAM LB defined, using the `pool` option
* wait for service to come up

**Result**
service is unable to deploy, character in name not allowed:

<img width="599" alt="Screen Shot 2022-03-18 at 10 34 36 AM" src="https://user-images.githubusercontent.com/16691014/159063644-b588df46-6288-481c-a7d8-843d9d12e0b8.png">

**Expected Result**
the character(s) appended to a string by rancher should always be from the allowed set.

**Additional context**
* I have brought up over 50 LBs with this node driver/test but only hit this specific issue 1x so it is likely hard to reproduce. 
* not sure if this is exclusive to harvester, or could happen with any provider (I suspect the latter)

**Comment by n313893254** [comment]
Notice the API has a name validate like this: `Deployment.apps "test-name" is invalid: spec.template.spec.containers[0].ports[1].name: Invalid value: "test- 234": must contain only alpha-numeric characters (a-z, 0-9), and hyphens (-)`

Seems the service name is created by the backend. @slickwarren Could you provide more info to produce the issues?

**Comment by slickwarren** [comment]
I used the following for testing:
* `loganhz/web` workload image
* service: 
  * loadbalancer
  * container port 8080
  * external (lb) port: 80
  * name: anything
  * IPAM: pool or DHCP

**Comment by yaocw2020** [comment]
I am sure it's a bug of harvester-cloud-provider backend codes. The suffix is a 32 bits checksum which could be represented as a seven- or eight-digit hexadecimal number. If it's a seven-digit hexadecimal number, the statement `fmt.Sprintf("%8x", digest)` will add a space at the beginning of the returned string. The correct statement is `fmt.Sprintf("%08x", digest)` which will add the `0` character rather than space.

```
digest := crc32.ChecksumIEEE([]byte(name + string(service.UID)))
suffix := fmt.Sprintf("%8x", digest)
name += suffix
```

**Comment by noahgildersleeve** [comment]
Verified as fixed per 
https://github.com/harvester/harvester/issues/2122#issuecomment-1097841936
and 
https://github.com/harvester/harvester/issues/2122#issuecomment-1108196968
