### ISSUE TITLE
AKS Basic LoadBalancer can't be used

### ISSUE THREAD

**Issue by annablender** [rancher/rancher#36959]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Local and downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Local cluster 3 nodes, downstream cluster AKS 1.20 provisioned by Rancher. Basic LB selected and no availability zones selected for the node group.
  

**Describe the bug**

AKS clusters cannot be created with the Basic LB sku on 2.6.2. Abbot has noticed that the LB sku dropdown is greyed out until he unclicks all of the availability zones from the first node group, adds a node group, then removes the first again. At this point, it lets him select Basic. Continuing on results in this error:

```
error failed to create cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 – Original Error: Code="SLBRequiredForAvailabilityZone" Message="Standard Load Balancer is required for availability zone." Target="networkProfile.loadBalancerSku"
```

Abbot cannot create clusters without a public IP in front of the LB, apparently Standard ones will always do that.

**To Reproduce**
 

_None_

**Troubleshooting**

We tried editing the cluster yaml after the fact to make everything reflect, but that did not change anything.

SURE-3685

**Comment by annablender** [comment]
We think that what's happening here is an empty slice of Availability Zones is being passed to AKS instead of nil, so AKS thinks there are availability zones even though there aren't. This would cause the error because if availability zones are specified, you have to use a Standard Load Balancer instead of a basic one.

**Comment by Josh-Diamond** [comment]
Ticket #36959 - Test Results

With Docker on single-node instance:

Reproduced on rancher `v2.6.2`:
1. Fresh install of rancher `v2.6.2`
2. Provision a downstream AKS cluster with k8s `v1.20.15` and a `Basic` LB; [un-click availability zones; add node group, delete node group, select LB as `Basic`]
3. Reproduced - Failure to provision downstream AKS cluster

Screenshot:
<img width="1519" alt="Screen Shot 2022-04-11 at 9 28 32 AM" src="https://user-images.githubusercontent.com/46494969/162787508-2987751b-b76c-4ecb-b6e1-fed64b67da13.png">


Verified on rancher `v2.6-851ff2f401b2c932869407cb75751806bae72776-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream AKS cluster with k8s `v1.20.15` and `Basic` LB;
3. Verified - Successfully provisioned AKS cluster

Screenshot:
<img width="1554" alt="Screen Shot 2022-04-11 at 10 08 44 AM" src="https://user-images.githubusercontent.com/46494969/162800156-6e5beb22-4b0b-457a-ab07-402305398252.png">
