### ISSUE TITLE
RKE2 Cluster stuck in Provisioning state during control plane upgrade on upgrading k8s version

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36968]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `024e6fa`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: RKE2 DDO Node driver cluster
- Cluster Type (Local/Downstream): 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

   
**Describe the bug**

**To Reproduce**

- Deployed an RKE2 node driver cluster - 3 etcd, 2 cp, 3 worker nodes
- Upgraded k8s from`1.22.7+rke2r2` to `v1.23.4+rke2r2`
- etcd nodes gets upgraded
- The cluster is stuck in Provisioning state `Provisioning control plane node(s) sowmya-do2-pool2-755b6f7dcc-6cgf5,sowmya-do2-pool2-755b6f7dcc-kmkzk` when trying to upgrade control plane nodes.

**Comment by thedadams** [comment]
With commit `0b44573` and 3 etcd-only, 2 control plane, and 3 worker nodes, I was able to provision clusters with v1.22.7+rke2r2 and upgraded v1.23.4+rke2r2 without issue with the following configurations:
- calico CNI with no upgrade strategy
- calico CNI with upgrade strategy set for both control plane and worker nodes
- multus,canal CNI with no upgrade strategy
- multus,canal CNI with upgrade strategy set for both control plane and worker nodes

As stated above, I was successfully able to upgrade the downstream cluster in all of these situations.

**Comment by sowmyav27** [comment]
@Josh-Diamond Can you please reproduce this from the original description of the issue. If it doesnt reproduce we can close the issue.

**Comment by Josh-Diamond** [comment]
Ticket #36968 - Test Results

With Docker on single-node instance:

Reproduction Failure on rancher `v2.6-024e6fa23af3678aafa85d4085c02143127bd3a1-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, deploy a DigitalOcean RKE2 Node driver cluster with 3 etcd, 2 cp, 3 wkr nodes
3. Once provisioned, upgrade k8s version from `v1.22.7+rke2r2` to `v1.23.4+rke2r2`
4. Reproduction Failure - Cluster successfully upgrades k8s version; `active` and stable

Screenshots:
In progress
<img width="1442" alt="Screen Shot 2022-03-25 at 12 31 39 PM" src="https://user-images.githubusercontent.com/46494969/160190619-b5e3f985-54b3-46a2-b135-2a00c5de48ca.png">

Post-upgrade:
<img width="1440" alt="Screen Shot 2022-03-25 at 12 35 50 PM" src="https://user-images.githubusercontent.com/46494969/160190678-705f4c07-9ebf-47d1-94bf-87a6a3275ad6.png">
