### ISSUE TITLE
Rancher server restarts with error `[FATAL] k3s exited with: exit status 2`

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36967]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `024e6fa2`
- Installation option (Docker install/Helm Chart): docker install

   
**Describe the bug**
Rancher server restarts with error `[FATAL] k3s exited with: exit status 2`

**To Reproduce**

- Deploy rancher 2.6-head
- Rancher restarts

**Result**
Rancher logs:
```
2022/03/20 16:42:08 [ERROR] failed to start controller for cluster.x-k8s.io/v1alpha3, Kind=MachineSet: failed to wait for caches to sync
2022/03/20 16:42:08 [ERROR] failed to start controller for cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment: failed to wait for caches to sync
2022/03/20 16:42:08 [ERROR] failed to start controller for cluster.x-k8s.io/v1alpha3, Kind=Cluster: failed to wait for caches to sync
2022/03/20 16:42:08 [ERROR] failed to start controller for cluster.x-k8s.io/v1alpha3, Kind=MachineHealthCheck: failed to wait for caches to sync
2022/03/20 16:42:08 [ERROR] failed to start controller for cluster.x-k8s.io/v1alpha3, Kind=Machine: failed to wait for caches to sync
2022/03/20 16:42:08 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=Machine
2022/03/20 16:42:08 [INFO] Rancher startup complete
2022/03/20 16:42:08 [INFO] checking configmap cattle-system/admincreated to determine if orphan bindings cleanup needs to run
2022/03/20 16:42:08 [INFO] checking configmap cattle-system/admincreated to determine if duplicate bindings cleanup needs to run
2022/03/20 16:42:08 [INFO] create kontainerdriver tencentkubernetesengine
2022/03/20 16:42:08 [INFO] create kontainerdriver googlekubernetesengine
2022/03/20 16:42:09 [INFO] bindings cleanup needed, waiting 3 minutes before starting
2022/03/20 16:42:09 [INFO] [clean-orphan-bindings] cleaning up orphaned bindings
2022/03/20 16:42:09 [INFO] [clean-orphan-bindings] checking for orphaned rolebindings
2022/03/20 16:42:09 [INFO] update kontainerdriver googlekubernetesengine
2022/03/20 16:42:09 [ERROR] error syncing 'git-webhook': handler apiservice: failed to create cattle-fleet-system/stv-aggregation /v1, Kind=Secret for apiservice git-webhook: namespaces "cattle-fleet-system" not found, requeuing
2022/03/20 16:42:09 [INFO] update kontainerdriver tencentkubernetesengine
2022/03/20 16:42:09 [INFO] update kontainerdriver tencentkubernetesengine
2022/03/20 16:42:09 [INFO] update kontainerdriver amazonelasticcontainerservice
2022/03/20 16:42:10 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=Machine controller
2022/03/20 16:42:10 [INFO] create kontainerdriver azurekubernetesservice
2022/03/20 16:42:10 [INFO] create kontainerdriver aliyunkubernetescontainerservice
2022/03/20 16:42:10 [INFO] create kontainerdriver oraclecontainerengine
2022/03/20 16:42:10 [INFO] create kontainerdriver linodekubernetesengine
2022/03/20 16:42:10 [INFO] create kontainerdriver rancherkubernetesengine
2022/03/20 16:42:10 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment
2022/03/20 16:42:10 [INFO] create kontainerdriver opentelekomcloudcontainerengine
2022/03/20 16:42:10 [INFO] create kontainerdriver baiducloudcontainerengine
2022/03/20 16:42:10 [INFO] create kontainerdriver huaweicontainercloudengine
2022/03/20 16:42:11 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:42:11 [INFO] update kontainerdriver aliyunkubernetescontainerservice
2022/03/20 16:42:11 [INFO] update kontainerdriver oraclecontainerengine
2022/03/20 16:42:11 [INFO] update kontainerdriver azurekubernetesservice
2022/03/20 16:42:11 [INFO] update kontainerdriver rancherkubernetesengine
2022/03/20 16:42:11 [INFO] update kontainerdriver baiducloudcontainerengine
2022/03/20 16:42:11 [INFO] update kontainerdriver opentelekomcloudcontainerengine
2022/03/20 16:42:11 [INFO] update kontainerdriver linodekubernetesengine
2022/03/20 16:42:11 [INFO] update kontainerdriver baiducloudcontainerengine
2022/03/20 16:42:11 [INFO] update kontainerdriver rancherkubernetesengine
2022/03/20 16:42:11 [INFO] update kontainerdriver aliyunkubernetescontainerservice
2022/03/20 16:42:11 [INFO] update kontainerdriver oraclecontainerengine
2022/03/20 16:42:11 [INFO] update kontainerdriver opentelekomcloudcontainerengine
2022/03/20 16:42:11 [INFO] update kontainerdriver linodekubernetesengine
2022/03/20 16:42:15 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=MachineSet
2022/03/20 16:42:15 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=Cluster
2022/03/20 16:42:15 [INFO] Watching metadata for cluster.x-k8s.io/v1alpha3, Kind=MachineHealthCheck
2022/03/20 16:42:15 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=MachineDeployment controller
2022/03/20 16:42:15 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:35697
2022/03/20 16:42:15 [INFO] kontainerdriver googlekubernetesengine stopped
2022/03/20 16:42:15 [INFO] Updating global catalog helm3-library
2022/03/20 16:42:15 [INFO] update kontainerdriver huaweicontainercloudengine
2022/03/20 16:42:15 [INFO] update kontainerdriver huaweicontainercloudengine
2022/03/20 16:42:16 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:42:16 [INFO] Loaded configuration from &{} in [0x6f50520]
2022/03/20 16:42:16 [INFO] Loaded configuration from &{} in [0x6f50520]
2022/03/20 16:42:16 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:43581
2022/03/20 16:42:16 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2022/03/20 16:42:18 [ERROR] error syncing 'git-webhook': handler apiservice: failed to create cattle-fleet-system/stv-aggregation /v1, Kind=Secret for apiservice git-webhook: namespaces "cattle-fleet-system" not found, requeuing
2022/03/20 16:42:19 [INFO] [CleanupOrphanBindingsDone] successfully cleaned up orphan bindings
2022/03/20 16:42:19 [INFO] checking configmap cattle-system/admincreated to determine if orphan bindings cleanup needs to run
2022/03/20 16:42:19 [INFO] [clean-catalog-orphan-bindings] cleaning up orphaned catalog bindings
2022/03/20 16:42:19 [ERROR] error syncing 'git-webhook': handler apiservice: failed to create cattle-fleet-system/stv-aggregation /v1, Kind=Secret for apiservice git-webhook: namespaces "cattle-fleet-system" not found, requeuing
2022/03/20 16:42:19 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=MachineSet controller
2022/03/20 16:42:19 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=Cluster controller
2022/03/20 16:42:19 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=MachineHealthCheck controller
2022/03/20 16:42:19 [INFO] update kontainerdriver amazonelasticcontainerservice
2022/03/20 16:42:20 [INFO] [clean-catalog-orphan-bindings] Processing 1 rolebindings
2022/03/20 16:42:20 [INFO] [clean-catalog-orphan-bindings] Deleting orphaned role global-catalog
2022/03/20 16:42:20 [ERROR] error syncing 'git-webhook': handler apiservice: failed to create cattle-fleet-system/stv-aggregation /v1, Kind=Secret for apiservice git-webhook: namespaces "cattle-fleet-system" not found, requeuing
2022/03/20 16:42:20 [ERROR] error syncing 'googlekubernetesengine': handler mgmt-kontainer-driver-lifecycle: dynamicschemas.management.cattle.io "cluster" already exists, requeuing
2022/03/20 16:42:20 [INFO] update kontainerdriver googlekubernetesengine
2022/03/20 16:42:20 [WARNING] failed to create or update driverMetadata: Post "https://127.0.0.1:6443/apis/management.cattle.io/v3/namespaces/cattle-global-data/rkek8ssystemimages": EOF, Fallback to refresh from local file path /var/lib/rancher-data/driver-metadata/data.json
2022/03/20 16:42:20 [INFO] Retrieve data.json from local path /var/lib/rancher-data/driver-metadata/data.json
2022/03/20 16:42:20 [ERROR] error syncing 'git-webhook': handler apiservice: failed to create cattle-fleet-system/stv-aggregation /v1, Kind=Secret for apiservice git-webhook: Post "https://127.0.0.1:6443/api/v1/namespaces/cattle-fleet-system/secrets?timeout=15m0s": read tcp 127.0.0.1:59616->127.0.0.1:6443: read: connection reset by peer, requeuing
2022/03/20 16:42:20 [ERROR] error syncing 'catalogs-use': handler mgmt-auth-gr-controller: 1 error occurred:
	* Put "https://127.0.0.1:6443/apis/rbac.authorization.k8s.io/v1/namespaces/cattle-global-data/roles/catalogs-use-global-catalog": EOF

, requeuing
2022/03/20 16:42:20 [WARNING] [clean-catalog-orphan-bindings] Error when deleting role global-catalog, Delete "https://127.0.0.1:6443/apis/rbac.authorization.k8s.io/v1/namespaces/cattle-global-data/roles/global-catalog": EOF
2022/03/20 16:42:20 [WARNING] [CleanupOrphanCatalogBindingsDone] error during orphan binding cleanup: Delete "https://127.0.0.1:6443/apis/rbac.authorization.k8s.io/v1/namespaces/cattle-global-data/roles/global-catalog": EOF
2022/03/20 16:42:20 [ERROR] failed to cleanup orphan catalog bindings
2022/03/20 16:42:20 [INFO] Updating global catalog system-library
2022/03/20 16:42:20 [ERROR] error syncing 'azure': handler node-driver-controller: Put "https://127.0.0.1:6443/apis/management.cattle.io/v3/nodedrivers/azure": read tcp 127.0.0.1:60144->127.0.0.1:6443: read: connection reset by peer, requeuing
2022/03/20 16:42:20 [ERROR] error syncing 'aliyunecs': handler node-driver-controller: Put "https://127.0.0.1:6443/apis/management.cattle.io/v3/nodedrivers/aliyunecs": read tcp 127.0.0.1:60142->127.0.0.1:6443: read: connection reset by peer, requeuing
2022/03/20 16:42:20 [ERROR] error syncing 'linode': handler node-driver-controller: Post "https://127.0.0.1:6443/apis/management.cattle.io/v3/dynamicschemas": EOF, requeuing
2022/03/20 16:42:20 [ERROR] error syncing 'catalogs-use': handler mgmt-auth-gr-controller: 1 error occurred:
	* Put "https://127.0.0.1:6443/apis/rbac.authorization.k8s.io/v1/namespaces/cattle-global-data/roles/catalogs-use-global-catalog": read tcp 127.0.0.1:60186->127.0.0.1:6443: read: connection reset by peer

, requeuing
2022/03/20 16:42:20 [ERROR] error syncing 'azure': handler node-driver-controller: Put "https://127.0.0.1:6443/apis/management.cattle.io/v3/nodedrivers/azure": dial tcp 127.0.0.1:6443: connect: connection refused, requeuing
2022/03/20 16:42:20 [ERROR] error syncing 'rke-metadata-config': handler rke-metadata-handler: failed to refresh from local file path: /var/lib/rancher-data/driver-metadata/data.json: Post "https://127.0.0.1:6443/apis/management.cattle.io/v3/namespaces/cattle-global-data/rkek8ssystemimages": read tcp 127.0.0.1:60190->127.0.0.1:6443: read: connection reset by peer, requeuing
2022/03/20 16:42:20 [FATAL] k3s exited with: exit status 2
INFO: Running k3s server --cluster-init --cluster-reset
2022/03/20 16:42:38 [INFO] Rancher version 024e6fa23 (024e6fa23) is starting
```

**Comment by jiaqiluo** [comment]
Hi @sowmyav27 , Do you see this happen all the time? Could we get the logs of the k3s cluster in the rancher container? the filename is `k3s.log` at the root directory (`/var/lib/rancher`) 
cc @slickwarren

**Comment by slickwarren** [comment]
I am on commit 024e6fa and was not able to reproduce this in a docker install, so it might be intermittently hit.

**Comment by sowmyav27** [comment]
moving this out based on https://github.com/rancher/rancher/issues/36967#issuecomment-1074493889

**Comment by sowmyav27** [comment]
Closing it for now. Will reopen/log a new bug if we notice this

**Comment by thowitz** [comment]
> Same problem here, rancher 2.6 on single node docker
> 
> ```
> INFO: Running k3s server --cluster-init --cluster-reset
> 2022/06/08 19:25:42 [INFO] Rancher version v2.6.5 (c4d59fa88) is starting
> 2022/06/08 19:25:42 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
> 2022/06/08 19:25:42 [INFO] Listening on /tmp/log.sock
> 2022/06/08 19:25:43 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/06/08 19:25:45 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/06/08 19:25:47 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/06/08 19:25:49 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/06/08 19:25:51 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/06/08 19:25:53 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/06/08 19:25:55 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/06/08 19:25:57 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/06/08 19:25:59 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/06/08 19:26:01 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/06/08 19:26:03 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/06/08 19:26:05 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
> 2022/06/08 19:26:21 [INFO] Running in single server mode, will not peer connections
> 2022/06/08 19:26:26 [INFO] Applying CRD features.management.cattle.io
> 2022/06/08 19:28:28 [INFO] Applying CRD navlinks.ui.cattle.io
> 2022/06/08 19:28:46 [INFO] Applying CRD clusters.management.cattle.io
> 2022/06/08 19:28:48 [INFO] Applying CRD apiservices.management.cattle.io
> 2022/06/08 19:28:49 [INFO] Applying CRD clusterregistrationtokens.management.cattle.io
> 2022/06/08 19:28:50 [INFO] Applying CRD settings.management.cattle.io
> 2022/06/08 19:28:51 [INFO] Applying CRD preferences.management.cattle.io
> 2022/06/08 19:28:52 [INFO] Applying CRD features.management.cattle.io
> 2022/06/08 19:28:52 [INFO] Applying CRD clusterrepos.catalog.cattle.io
> 2022/06/08 19:28:53 [INFO] Applying CRD operations.catalog.cattle.io
> 2022/06/08 19:28:54 [INFO] Applying CRD apps.catalog.cattle.io
> 2022/06/08 19:28:56 [INFO] Applying CRD fleetworkspaces.management.cattle.io
> 2022/06/08 19:28:58 [INFO] Applying CRD managedcharts.management.cattle.io
> 2022/06/08 19:29:01 [INFO] Applying CRD clusters.provisioning.cattle.io
> 2022/06/08 19:29:01 [INFO] Applying CRD clusters.provisioning.cattle.io
> 2022/06/08 19:29:02 [INFO] Applying CRD rkeclusters.rke.cattle.io
> 2022/06/08 19:29:02 [INFO] Applying CRD rkecontrolplanes.rke.cattle.io
> 2022/06/08 19:29:03 [INFO] Applying CRD rkebootstraps.rke.cattle.io
> 2022/06/08 19:29:03 [INFO] Applying CRD rkebootstraptemplates.rke.cattle.io
> 2022/06/08 19:29:03 [INFO] Applying CRD rkecontrolplanes.rke.cattle.io
> 2022/06/08 19:29:04 [INFO] Applying CRD custommachines.rke.cattle.io
> 2022/06/08 19:29:04 [INFO] Applying CRD etcdsnapshots.rke.cattle.io
> 2022/06/08 19:29:04 [INFO] Applying CRD clusters.cluster.x-k8s.io
> 2022/06/08 19:29:04 [INFO] Applying CRD machinedeployments.cluster.x-k8s.io
> 2022/06/08 19:29:04 [INFO] Applying CRD machinehealthchecks.cluster.x-k8s.io
> 2022/06/08 19:29:05 [INFO] Applying CRD machines.cluster.x-k8s.io
> 2022/06/08 19:29:05 [INFO] Applying CRD machinesets.cluster.x-k8s.io
> I0608 19:30:12.959385      42 trace.go:205] Trace[998414793]: "DeltaFIFO Pop Process" ID:cattle-fleet-clusters-system/default-token-dk8zb,Depth:96,Reason:slow event handlers blocking the queue (08-Jun-2022 19:30:11.814) (total time: 651ms):
> Trace[998414793]: [651.6129ms] [651.6129ms] END
> I0608 19:30:16.589867      42 trace.go:205] Trace[1214622564]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:06.402) (total time: 10187ms):
> Trace[1214622564]: ---"Objects listed" error:<nil> 10187ms (19:30:16.589)
> Trace[1214622564]: [10.187649565s] [10.187649565s] END
> I0608 19:30:20.272534      42 trace.go:205] Trace[583728699]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:05.407) (total time: 14864ms):
> Trace[583728699]: ---"Objects listed" error:<nil> 14864ms (19:30:20.272)
> Trace[583728699]: [14.864978386s] [14.864978386s] END
> I0608 19:30:20.274050      42 trace.go:205] Trace[2077716621]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:05.961) (total time: 14312ms):
> Trace[2077716621]: ---"Objects listed" error:<nil> 14312ms (19:30:20.273)
> Trace[2077716621]: [14.312525639s] [14.312525639s] END
> I0608 19:30:20.760008      42 trace.go:205] Trace[1771271053]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:05.962) (total time: 14797ms):
> Trace[1771271053]: ---"Objects listed" error:<nil> 14797ms (19:30:20.759)
> Trace[1771271053]: [14.7979301s] [14.7979301s] END
> I0608 19:30:20.927296      42 trace.go:205] Trace[1626360741]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:06.325) (total time: 14601ms):
> Trace[1626360741]: ---"Objects listed" error:<nil> 14601ms (19:30:20.927)
> Trace[1626360741]: [14.601442623s] [14.601442623s] END
> I0608 19:30:22.664934      42 trace.go:205] Trace[285344232]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:05.646) (total time: 17018ms):
> Trace[285344232]: ---"Objects listed" error:<nil> 17017ms (19:30:22.664)
> Trace[285344232]: [17.018019041s] [17.018019041s] END
> I0608 19:30:24.269103      42 trace.go:205] Trace[1004815271]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:06.858) (total time: 17410ms):
> Trace[1004815271]: ---"Objects listed" error:<nil> 17410ms (19:30:24.268)
> Trace[1004815271]: [17.410511417s] [17.410511417s] END
> I0608 19:30:26.377859      42 trace.go:205] Trace[23052994]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:06.857) (total time: 19520ms):
> Trace[23052994]: ---"Objects listed" error:<nil> 19520ms (19:30:26.377)
> Trace[23052994]: [19.520738569s] [19.520738569s] END
> I0608 19:30:26.378602      42 trace.go:205] Trace[732504815]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:06.859) (total time: 19519ms):
> Trace[732504815]: ---"Objects listed" error:<nil> 19519ms (19:30:26.378)
> Trace[732504815]: [19.51951088s] [19.51951088s] END
> I0608 19:30:26.384730      42 trace.go:205] Trace[234351590]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:05.210) (total time: 21173ms):
> Trace[234351590]: ---"Objects listed" error:<nil> 21173ms (19:30:26.384)
> Trace[234351590]: [21.173981577s] [21.173981577s] END
> I0608 19:30:26.623916      42 trace.go:205] Trace[1562167579]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:06.404) (total time: 20219ms):
> Trace[1562167579]: ---"Objects listed" error:<nil> 20219ms (19:30:26.623)
> Trace[1562167579]: [20.219462524s] [20.219462524s] END
> I0608 19:30:27.682766      42 trace.go:205] Trace[168579958]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:06.400) (total time: 21282ms):
> Trace[168579958]: ---"Objects listed" error:<nil> 21282ms (19:30:27.682)
> Trace[168579958]: [21.282183652s] [21.282183652s] END
> I0608 19:30:27.685259      42 trace.go:205] Trace[1583241817]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:06.403) (total time: 21281ms):
> Trace[1583241817]: ---"Objects listed" error:<nil> 21281ms (19:30:27.685)
> Trace[1583241817]: [21.281197714s] [21.281197714s] END
> I0608 19:30:27.733290      42 trace.go:205] Trace[2078607356]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:06.855) (total time: 20877ms):
> Trace[2078607356]: ---"Objects listed" error:<nil> 20831ms (19:30:27.686)
> Trace[2078607356]: [20.877529446s] [20.877529446s] END
> I0608 19:30:28.681840      42 trace.go:205] Trace[820579411]: "Reflector ListAndWatch" name:pkg/mod/github.com/rancher/client-go@v1.23.3-rancher2/tools/cache/reflector.go:168 (08-Jun-2022 19:30:06.403) (total time: 22278ms):
> Trace[820579411]: ---"Objects listed" error:<nil> 22278ms (19:30:28.681)
> Trace[820579411]: [22.278388938s] [22.278388938s] END
> E0608 19:30:38.276817      42 request.go:1085] Unexpected error when reading response body: unexpected EOF
> E0608 19:30:38.293612      42 request.go:1085] Unexpected error when reading response body: unexpected EOF
> 2022/06/08 19:30:39 [FATAL] k3s exited with: exit status 2
> ```

I'm having the same issue

**Comment by acabrele** [comment]
I also had this issue a few days ago.  After not having run the rancher docker for some time (perhaps v2.2 or v2.3), I found the same small machine size I used to use was not enough with v2.6.  I had these same errors with multiple attempts of OS and recent rancher versions, on AWS EC2.  As soon as I started using 8Gb machines, they all worked with the exact same install steps.

**Comment by thowitz** [comment]
> I also had this issue a few days ago.  After not having run the rancher docker for some time (perhaps v2.2 or v2.3), I found the same small machine size I used to use was not enough with v2.6.  I had these same errors with multiple attempts of OS and recent rancher versions, on AWS EC2.  As soon as I started using 8Gb machines, they all worked with the exact same install steps.

Thank you so much man, I've been banging my head against the table for the past 3 days trying to fix this and increasing the ram in proxmox to 8gb (the minimum value, not ballooning) fixed it instantly. Maybe there should be something in the docs about this, I might make a pr.

**Comment by acabrele** [comment]
@thowitz no problem...It had me for a couple hours too.  In the end I noticed the k8s logging which I didn't remember from older versions, and figured there is no way my 2Gb is going cut it now!

**Comment by thowitz** [comment]
> @thowitz no problem...It had me for a couple hours too.  In the end I noticed the k8s logging which I didn't remember from older versions, and figured there is no way my 2Gb is going cut it now!

Haha yeah, fair enough, great catch

**Comment by sk1me** [comment]
In my case I had to check k3s.log where was info about: _[Iptables v1.4.14: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)](https://stackoverflow.com/questions/21983554/iptables-v1-4-14-cant-initialize-iptables-table-nat-table-does-not-exist-d)_

What helped:
`sudo modprobe ip_tables
sudo echo 'ip_tables' >> /etc/modules`

**Comment by Suzamax** [comment]
> In my case I had to check k3s.log where was info about: _[Iptables v1.4.14: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)](https://stackoverflow.com/questions/21983554/iptables-v1-4-14-cant-initialize-iptables-table-nat-table-does-not-exist-d)_
> 
> What helped: `sudo modprobe ip_tables **&&** sudo echo 'ip_tables' >> /etc/modules`

Install `iptables `in RHEL 9 or the likes and enable it on systemd.
