### ISSUE TITLE
When you hover, submenu should be different color and with notchy thing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3696]
Version: master 2/24

Steps to Reproduce: 
1.  hover over different menu then what you are on

Results: Submenu is same color as selected submenu

Expected: submenu should be different color and have notchy thingy

+1 from Darren and Vincent

**Comment by lvuch** [comment]
Beginning of fix in https://github.com/rancher/ui/pull/484 @vincent99 will you take a look at how the toggleClass is set up

**Comment by tfiduccia** [comment]
Version - master UI 3/3
Verified fixed
