### ISSUE TITLE
Add backend support for UI plugins

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#36972]
In 2.6.5, the UI team will be adding support for UI plugins.

**Backend needs**

The UI will allow plugins to be added into Rancher after deployment. (ie: the ability to expand Rancher without a new release.) These will be a package of Javascript and other assets. This will be packaged up into a gzipped-tar file (same as would be uploaded as an npm pacakge).

Users will be able to browse a catalog of UI plugins in the UI and install/uninstall/upgrade them.

Since there is already a mechanism for Helm Charts and a catalog in Rancher, it probably makes sense to use that approach here as well. I'll describe this approach below and that should give enough context to determine if that is indeed the correct approach or not.

UI Plugins will be distributed as UI Packages - a gzipped-tarball of javascript and other assets - this needs to be unpacked and served up via https when the plugin is installed.

**Catalog**

I propose that we distribute UI Plugins as helm charts. We already have a mechanism for dealing with charts and helm in Rancher, so we can leverage this.

I suggest we keep UI plugin Helm charts in a new chart repository and in the UI, when a user adds a Helm chart repository, we can label it as a UI plugin repository and use that to hide it in the Apps and Marketplace views and include it in new UI plugin views.

Users will be able to browse UI plugins using the existing chart support in Rancher, so nothing extra should be needed from a catalog point of view with this approach.

**UI Plugin Helm Chart**

We should add a new custom resource, something like [uipkg.cattle.io](http://uipkg.cattle.io/) - essentially a config map (we could just use config maps if that is easier) that can hold the gzipped-tar file as data. This will allow the plugin to persist across upgrades etc. Where a package is greater than 1MB, it will need to be split into multiple of these resources.

The Helm chart for a plugin would create one or more uipkg.cattle.io resources - essentially storing the gzipped-tar bundle in etcd. These would be stored in the Rancher management cluster in the `cattle-system` namespace (or we could use a new system namespace - cattle-ui, if that would help with separation).

The custom resource would include the following data (could be stored as annotations, if using config map) - we will refer to this as PLUGIN_METADATA.

Required:

- Plugin name
- Plugin version
- Display name
- Creation datetime

Optional:

- Icon
- Description
- Annotations

The backend will need to serve up plugins that have been installed - this should be under the /pkg endpoint. This can just serve up a local folder contents - we'll call this PACKAGE_FOLDER.

The backend should watch for new instances of the custom resources - when any one of them is created/updated/deleted, it should fetch the list of all of the custom ui package resources and:

Create a folder in PACKAGE_FOLDER (if not already existing) for each unique name and version (joined by a hyphen) - e.g. fleet-0.1.0.
Unpack the contents of each resources into the appropriate folder (guznip and untar) - there might be multiple resources with the same name and version when the plugin is large, so these will be unpacked on top of one another.
Iterate through the folders within PACKAGE_FOLDER and remove any which no longer relate to one of the ui package resources - this will clean-up old packages that have been removed
This process will mean the backend will unpack and serve up UI plugins that are stored in the new custom resource.

Additionally, the backend should provide a new endpoint (e.g. /pkgs) which returns a JSON document listing all of the installed plugins - this should return the PLUGIN_METADATA for all of the custom resource s (de-duped so that if there are multiple resources for a single plugin, only one PLUGIN_METADATA is returned - it is assumed that all resources for a single plugin would have the same metadata).

With this in place, the UI will be able to make requests to /pkgs during first-load (and subsequently) to determine the plugins that need to be loaded and then be able to load the javascript and assets from /pkg/<NAME>-<VERSION>/... as needed.

The /pkg and /pkgs endpoints should be public, not requiring any authentication.

**Comment by MKlimuszka** [comment]
Corresponding UI ticket: https://github.com/rancher/dashboard/issues/5094
