### ISSUE TITLE
[BUG] Setting machine count to 0 on pool with master roles, will obliterate downstream cluster

### ISSUE THREAD

**Issue by alexdepalex** [rancher/rancher#36984]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm / v1.21.8+rke2r1

**Information about the Cluster**
- Kubernetes version: v1.22.4+rke2r2
- Cluster Type (Local/Downstream): Downstream / Harvester v1.0
 * Infrastructure Provider = Rancher RKE2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): admin

**Describe the bug**
When setting the `Machine Count` to 0 for a machine pools that hosts the `etcd` and `control plane` role, the downstream cluster will be unusable.

**To Reproduce**
- Create a cluster using the Harvester node driver with master pool of 1-3 nodes.
- Edit the cluster configuration and set the `Machine Count` to 0
- The downstream cluster dies

**Result**
- The cluster nodes will go into a deleting stage.
- The cluster nodes aren't actually deleted and are stuck in the deleting stage.
- Cluster can be explored for a short while, after which Rancher can't connect to it anymore.
- Rebooting a node from the downstream cluster kills the cluster earlier.
- After adding a new pool (with etc, control and worker role), things seem to be going again. 1 out of 3 nodes is actually deleted and a new node is deployed.
- Then Rancher dies and it only shows me the blue circle of hope.
- Eventually, the Rancher UI time's out with error 500 (tunnel disconnect) or 504 (no response in time allotted), probably because some process can't connect to the downstream cluster.
- In our case, we weren't able to recover the cluster.

**Expected Result**
Don't allow a machine pool that hosts the etcd and control plane role to be scaled back to 0.

**Additional context**

SURE-4279

**Comment by alexdepalex** [comment]
We same this same issue with a worker-node only pool.

**Comment by alexdepalex** [comment]
I want to again stress out that if a situation like this occurs, the Rancher UI will be unresponsive to whoever is authorized to access the cluster. That means also for any admin users who are authorized to access all clusters.

**Comment by snasovich** [comment]
On backend, we want to return error from POST/PUT requests to `/v1/provisioning.cattle.io.clusters/(namespace)/(cluster-name)` when node pool configuration is incorrect, e.g. number of nodes with cp/etcd role is 0. This requires webhook changes to validate the payload and return error if it's invalid (likely https://github.com/rancher/webhook/blob/master/pkg/resources/validation/cluster/provisioningcluster.go).

**Comment by HarrisonWAffel** [comment]
After looking into this a bit more I found that this issue cannot be addressed by web hook changes. Controllers within rancher will begin to take action before the web hook is called, and node information is not shared with the validating web hook. 

I did find that this problem can also occur for RKE1 clusters, although it is a bit harder to encounter. The above mentioned dashboard ticket describes the UI behavior which allows this to happen for RKE2, however I found similar issues with the UI for RKE1.

In RKE1, the UI will allow you to update the configuration with zero nodes with the etcd role present. This is only possible when editing the cluster configuration after it has already been created, and only effects the etcd role. A new dashboard issue has been created to address that behavior, https://github.com/rancher/dashboard/issues/6966 as it will render a cluster unusable if encountered. 

> We are seeing the same issue with a worker-node-only pool. The pool is set to 0 and scaled up again. All nodes in that pool are stuck in provisioning.

I have not been able to reproduce that particular issue on 2.7-head when creating nodes in Digital Ocean. In my tests scaling a worker only node-pool down to zero and then scaling it back up again resulted in new workers being provisioned and successfully joining the cluster.

**Comment by HarrisonWAffel** [comment]
After discussion with the team we have decided that if we were to prevent users from scaling down specific pools outside of the UI that we would likely break existing work flows for users who do find it desirable to scale down etcd/control-plane nodes to zero (for instance, etcd rehydration and VM rotation). There are currently two UI tickets that should provide further protection for users who do not intend to completely scale down critical node-pools (https://github.com/rancher/dashboard/issues/6763, https://github.com/rancher/dashboard/issues/5774). 

Though it should be noted that completely removing etcd and control-plane components from any kubernetes cluster will render it unusable, as those are critical components that kubernetes needs to function properly.
