### ISSUE TITLE
[vsphere cloud provider rke2] cpi/csi add-on options not appearing in UI for k8s 1.22.x, 1.23.x

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36987]
**Rancher Server Setup**
- Rancher version: v2.6-head 024e6fa
- Installation option (Docker install/Helm Chart): docker

**Information about the Cluster**
- Kubernetes version: 1.22.7+rke2r2, 1.23.4+rke2r2
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vsphere 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): admin

   
**Describe the bug**
UI options for cpi, csi when creating a vsphere node driver cluster + vsphere cloud provider are not showing up for the user. 

**To Reproduce**
* provision an rke2 vsphere node driver cluster
  * select `vsphere` option for the cloud provider and try to configure options in the `add-ons` tab

**Result**
UI doesn't show options to use vsphere csi/cpi in the add-ons tab

**Screenshots**

<img width="1123" alt="Screen Shot 2022-03-21 at 2 41 50 PM" src="https://user-images.githubusercontent.com/16691014/159368457-45a66b64-21c4-47c8-bcd9-ee567ea36281.png">

**Additional context**
* @rosskirkpat  is aware of this issue and has a setup to reproduce
* UI options do appear for 1.21.7 and below for rke2

**Comment by rosskirkpat** [comment]
This is a KDM issue from our initial investigation and is unrelated to any of the vsphere-charts changes that were made recently. Both of these rke2 versions are not using the new CSI and CPI vsphere charts

**Comment by phillipsj** [comment]
The call doesn't seem to be made in the UI to fetch the updated chart info. 

![image](https://user-images.githubusercontent.com/1568133/159391414-ab966eec-3c44-4d4d-b504-3f62db9a68fe.png)

**Comment by phillipsj** [comment]
Looks to be the wrong repository defined in KDM for RKE2. 

![image](https://user-images.githubusercontent.com/1568133/159391923-9606809a-bb32-4cf3-847a-24e546a31b71.png)

**Comment by rosskirkpat** [comment]
with v1.22.7-rke2r2 selected using the dev-v2.6 KDM containing the vsphere chart fixes, I am seeing the add-on config
![image](https://user-images.githubusercontent.com/55704795/159590951-8d480bbd-1d06-46ee-a735-4d7ae7f1fd6d.png)
![image](https://user-images.githubusercontent.com/55704795/159590965-ef712154-42f7-412a-9460-1eb7a509bb33.png)

**Comment by rosskirkpat** [comment]
with v1.23.4-rke2r2 (marked as experimental now) selected using the dev-v2.6 KDM containing the vsphere chart fixes, I am seeing the add-on config as well
![image](https://user-images.githubusercontent.com/55704795/159590988-99623462-ce64-44c8-875b-93ea7b3d1035.png)
![image](https://user-images.githubusercontent.com/55704795/159590999-c227f706-4e34-4344-8295-04dd1d86526b.png)

**Comment by slickwarren** [comment]
this was validated on v2.6-11a7451ffee557897197fc624af03ac6fd34a9f0-head

**Comment by tariksimsek** [comment]
> Looks to be the wrong repository defined in KDM for RKE2.
> 
> ![image](https://user-images.githubusercontent.com/1568133/159391923-9606809a-bb32-4cf3-847a-24e546a31b71.png)

Same issue for  Rancher version 2.8.2 and rke2 version 1.27.11 and 1.26.14 . CSI helm chart cannot be found. It works for 1.25.16.

Should be fixed.
