### ISSUE TITLE
Error handling and logging for creating AKS cluster without permissions to create tags

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#36982]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): HA
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.21.9
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AKS 1.21.9

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: admin

   
**Describe the bug**

When creating an AKS cluster with one more tag and the Azure account does not have the permission to create tags on an AKS cluster, Rancher's aks-operator will be stuck in a loop retrying tag creating every 1-2 seconds.

**To Reproduce**
 
- Create an AKS cluster, specify one or more tags. Make sure the Azure account used does not have permissions to create tags on an AKS cluster.

**Result**
AKS cluster is stuck with waiting for provision, also seeing this throttling error in ask-config-operator (likely due to aggressive attempts to update tags:

`time="2022-02-21T23:10:00Z" level=error msg="error syncing 'cattle-global-data/c-w9h6r': handler aks-controller: containerservice.ManagedClustersClient#UpdateTags: Failure sending request: StatusCode=0 -- Original Error: Code=\"PatchResourceGroupError\" Message=\"Reconcile resource group failed with client error. Details: ResourceGroupReconciler retry failed: Category: ClientError; SubCode: SubscriptionRequestsThrottled; Dependency: Azure Resource Group; OrginalError: Code=\\\"SubscriptionRequestsThrottled\\\" Message=\\\"Number of write requests for subscription '<redacted>' exceeded the limit of '1200' for time interval '01:00:00'. Please try again after '303' seconds.\\\"; AKSTeam: Unknown, Retriable: false.\", requeuing"`

Seeing continuous attempts to upgrade tags:
```
time="2022-02-22T00:19:31Z" level=info msg="Checking configuration for cluster [aks-dev-canadacentral]"
time="2022-02-22T00:19:32Z" level=info msg="Updating tags for cluster [aks-dev-canadacentral]"
time="2022-02-22T00:19:34Z" level=info msg="Checking configuration for cluster [aks-dev-canadacentral]"
time="2022-02-22T00:19:35Z" level=info msg="Updating tags for cluster [aks-dev-canadacentral]"
time="2022-02-22T00:19:37Z" level=info msg="Checking configuration for cluster [aks-dev-canadacentral]"
time="2022-02-22T00:19:38Z" level=info msg="Updating tags for cluster [aks-dev-canadacentral]"
```

**Expected Result**

- aks-config-operator should log why it is not able to Update tags, if it failed
- aks-config-operator can continue to re-attempt updating tags, but it should have an incremental backoff so it doesn't throttle the whole Azure subscription
- An error should be propagated to the user UI. Something along the lines of - "Cluster could be provisioned. Failed to update tags. Error: <whatever Azure complains about>"
 
 **Workaround:**
Is workaround available and implemented? yes
What is the workaround: Manually add tags to the AKS cluster using the Azure portal or remove the tags from the AKS cluster on the rancher UI.

SURE-4131

**Comment by jiaqiluo** [comment]
Rancher sends requests to Azure to create or update an AKS cluster, Azure creates jobs internal to perform the operation of creating/updating the AKS cluster.  Rancher gets the job ID return from Azure. 

In order to achieve the expected results mentioned in the issue, Rancher needs to tracks the progress and status of the job on Azure's side to populate proper logs and messages and to thread hold the retries if it is desired. 

This will require a feature design in the backend.

**Comment by kkaempf** [comment]
moved to https://github.com/rancher/aks-operator/issues/92, closing here
