### ISSUE TITLE
Conditions for CAPI Machines needs to be reorganized

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#36993]
Right now, the `Provisioned` condition is used exclusively for reporting statuses. This isn't intuitive and should be changed. For example, when upgrading a cluster, the `Updated` condition should be used instead.

This should be changed in the planner.

**Additional context**
There are several issues that concern this problem. This is meant to be a gerneral issue that encompasses them all. For example:
- https://github.com/rancher/rancher/issues/36504
- https://github.com/rancher/rancher/issues/36689
- https://github.com/rancher/rancher/issues/36782

**Comment by Oats87** [comment]
Thinking about this, I'm wondering if what we should do is just change the condition we update for different errors, i.e. a snapshot creation error should return a new `ErrUpdating` type of error that would affect the `Updated` condition and `ErrWaiting` can remain for `Provisioned`

**Comment by thedadams** [comment]
### Root cause
The planner only used the `Provisioned` condition when configuring nodes.

### What was fixed, or what changes have occurred
Now, the `Reconciled` condition is always used.

In addition, the `Provisioned` condition was always used for the cluster object. Now, the `Provisioned` condition is used until all the machines are created in the infrastructure provider. After that, the `Updated` condition is used.

Lastly, the Home and Cluster Management pages would show different statuses for the cluster. This has been fixed now and both pages should show the same information.

### Areas or cases that should be tested
Provisioned and custom RKE2 clusters: provisioning, upgrading Kubernetes version, snapshot and restoring, and deleting.

### What areas could experience regressions?
Nothing really. The changes were just how the information is put on conditions and displayed in the UI.

### Are the repro steps accurate/minimal?
Yes.

**Comment by sowmyav27** [comment]
@Josh-Diamond Please validate the following before closing the issue

- Provisioned and custom RKE2 clusters: provisioning, upgrading Kubernetes version, snapshot and restoring, and deleting.
- Cluster state when performing these ^^^ actions and the state on Home and Cluster Management pages
- What is the cluster state when user takes a snapshot on an RKE2 cluster
- What is the cluster state when a worker node is deleted in an RKE2 cluster
- Edit cluster and change cluster config. What is the state of the cluster when cluster is upgrading? related to [this](https://github.com/rancher/rancher/issues/36782) issue
```
- Deploy an RKE2 cluster.
- When the cluster is Active, Edit Config --> Modify the Upgrade strategy to
```

**Comment by Josh-Diamond** [comment]
Ticket #36993 - Test Results

With Docker on single-node instance:

Verified on rancher `v2.6-6739a84ede27905dfcccbc9675c875d1752d438a-head`:

RKE2 Node driver - Cluster state sync'd between `Cluster Management` + `Home`
1. Provisioning: `Reconciling` > `Provisioning` > `Updating` > `Active`
2. Upgrading k8s version: `In Progress` > `Updating` > `Active`
3. Snapshot capture: `In Progress` > `Updating` > `Active`
4. Snapshot restore: `In Progress` > `Updating` > `Active`
5. Scale-up/Scale-down/Delete: `In Progress` > `Updating` > `Active` - [wkr node pool; delete refers to one wkr node]
6. Delete Cluster: `Removing`

RKE2 Custom - Cluster state sync'd between `Cluster Management` + `Home`
1. Provisioning: `Reconciling` > `Provisioning` > `Updating` > `Active`
2. Upgrading k8s version: `In Progress` > `Updating` > `Active`
3. Snapshot capture: `In Progress` > `Updating` > `Active`
4. Snapshot restore: `In Progress` > `Updating` > `Active`
5. Delete Wkr: `Active`
6. Delete Cluster: `Removing`
