### ISSUE TITLE
Moving mouse over blue upgrade status makes text unreadable

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3699]
Version - master 2/24

Steps to Reproduce: 
1.  Make sure you are on Light theme
2.  Create a service
3.  Click on upgrade
4.  While it's Upgrading, move your mouse over the "Upgrading" status

Results: the text on the blue upgrading status dissapears
![image](https://cloud.githubusercontent.com/assets/11514927/13337347/17bbd11a-dbd8-11e5-9043-84b9526bb178.png)

Expected: should still be able to read text.

Comment:  Might want to check dark theme.  I can read the text but not sure if this is what you wanted.

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/484

**Comment by tfiduccia** [comment]
Version - master UI 3/3
Verified fixed
