### ISSUE TITLE
Question: Does the spotify docker-client work with rancher?

### ISSUE THREAD

**Issue by juliangamble** [rancher/rancher#3700]
I have a question - I'd like to use the [spotify docker client](https://github.com/spotify/docker-client/) to work with Rancher. I'd like to know if this is feasible. 

My question is: **Question: Does the spotify docker-client work with Rancher?**

**Comment by deniseschannon** [comment]
I haven't tested it out myself. With Rancher we recently updated our requirements to support Docker version 1.9.1+, which is using Docker API 1.21. It looks like the spotify docker-client has only been tested with Docker API 1.18, so there might be some compatibility issues. I didn't look into details of if the spotify docker client is able to support later Docker APIs or not. 

Besides the compatibility issues, I don't see a specific reason of why it wouldn't work.
