### ISSUE TITLE
TypeError: Promise[t] is not a function 

### ISSUE THREAD

**Issue by clevertension** [rancher/rancher#37009]
install rancher in centos7
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher

when login with the random password, i can't do the next step, it give me **TypeError: Promise[t] is not a function** 

![image](https://user-images.githubusercontent.com/346723/159641565-e0b435e2-cc61-4182-b5af-919cb92ef291.png)

**Comment by hmadinei** [comment]
I have this problem in centos 7!
