### ISSUE TITLE
vSphere CPI Support for both 1.23 and skew policy.

### ISSUE THREAD

**Issue by phillipsj** [rancher/rancher#37004]
**Is your feature request related to a problem? Please describe.**

The current vSphere CPI chart doesn't have support for 1.23. Part of this issue is related to the fact that the official upstream image hasn't been released. vSphere supports a skew policy for CPI that allows one minor version below to run on a version which allows for upgrades and other scenarios. We need to support this scenario to assist users in getting the correct version installed.

**Describe the solution you'd like**

I think we should add a template helper to detect determine if the current Kubernetes version has a supported image, if not, it looks for one minor version below and then inserts that image if found. If not, then report that it isn't a supported option even using the skew policy.  The skew policy should be something that can be enabled by default and allows customers to disable that behavior if not desired.

**Describe alternatives you've considered**

Producing an experimental chart with the alpha images. This solution will probably lead to more confusion.

# Checklist for items that need completed

- [x] Update Image-mirror repo
- [x] Update manifests in rancher/vsphere-charts
- [x] Notify about chart "release"
- [x] Update chart in rancher/charts
- [x] Update chart in rancher/rke2-charts
- [x] Updated RKE2 to consume new chart

**Comment by phillipsj** [comment]
# Proposal for adding skew policy support to vSphere CPI chart

Currently the vSphere CPI releases lag behind Kubernetes version releases. This impacts the existing chart because it automatically selects the CPI version to deploy based on the Kubernetes version. This means that the chart will not deploy on a version of Kubernetes that it doesn't list in the values.yaml without modification. Once solution for solving this issue is to implement the skew policy support directly into the chart as an additional template helper. The existing `get_image` retrieves the Kubernetes version and compares that to Kubernetes version of the cluster to determine with image needs deploy. 

I am proposing we add a bool called `skewPolilcy.enabled` to the values.yaml file that is defaulted to `true`. If enabled, it will allow calling the `get_skew_policy_image` template helper when the supported versions check fails. The `get_skew_policy_image` helper will then see if one minor version below the existing cluster version is available. If so, it will use that image.

This allows us to handle the different scenarios we face as newer versions are released before the official CPI version is released.

## Resources

* [skew policy](https://kubernetes.io/releases/version-skew-policy)
    * *They are expected to match the kube-apiserver minor version, but may be up to one minor version older (to allow live upgrades).*
* [supported versions](https://github.com/kubernetes/cloud-provider-vsphere/blob/master/SECURITY.md#supported-versions)
* [kep](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/1771-versioning-policy-for-external-cloud-provider)

**Comment by phillipsj** [comment]
RKE2 team is onboard with this approach from the 3/24/2022 design discussion.

**Comment by phillipsj** [comment]
After a discussion with @aiyengar2, we will be following an approach that is very similar that is used in the [rancher-pushprox](https://github.com/rancher/charts/blob/dev-v2.6/packages/rancher-monitoring/rancher-pushprox/charts/values.yaml#L28-L36) chart. That uses a more KDM/Matrix style implementation that will build in the skew policy support. This will provide the same end result and create a more robust solution. I will be posting an ADR in the rancher/vsphere-charts repository soon.

**Comment by phillipsj** [comment]
New vSphere Chats confluence page: https://confluence.suse.com/display/EN/Rancher+vSphere+Chart

**Comment by phillipsj** [comment]
### Root cause

NA
 
### What was fixed, or what changes have occurred

The images were updated to the latest bugfix versions that are currently available. The chart was also modified to use semver ranges to auto-detecting the correct version to install based on the Kubernetes version. This was implemented to allow for skew policy support.
 
### Areas or cases that should be tested
 
The standard test plan located here should cover what needs tested.

* https://confluence.suse.com/pages/viewpage.action?pageId=851509848

### What areas could experience regressions?
 
That an incorrect version could be installed.

### Are the repro steps accurate/minimal?

Yes

**Comment by sirredbeard** [comment]
RKE2 has been validated and tested by Max.

**Comment by slickwarren** [comment]
validated the following use cases on rancher v2.6-head (6c12bee):
upgrade cases:
* deploy rke1 1.22.8 with external charts enabled
  * deploy the cpi/csi charts
  * test the charts by deploying a PVC using the new storage class -- pass
  * ensure all workloads for cpi/csi are `active` -- pass
* upgrade to v1.23.5
  * check for updates to the cpi/csi charts -- no update available
  * check that existing volume claim is working -- pass
  * deploy a new PVC -- pass


* deploy rke2 1.22.8+rke2r1 with vsphere charts enabled (cpi/csi is configured when deploying the cluster)
  * test the charts by deploying a PVC using the new storage class -- pass
  * ensure all workloads for cpi/csi are `active` -- pass
* upgrade to v1.23.5+rke2r1
  * check for updates to the cpi/csi charts -- no update available
  * check that existing volume claim is working -- pass
  * deploy a new PVC -- pass

Fresh install cases: 
* deploy rke1 1.23.5 with external charts enabled 
  * deploy the cpi/csi charts
  * test the charts by deploying a PVC using the new storage class -- pass
  * ensure all workloads for cpi/csi are `active` -- pass
* deploy rke2 1.23.5+rke2r1 with vsphere charts enabled (cpi/csi is configured when deploying the cluster)
  * test the charts by deploying a PVC using the new storage class -- pass
  * ensure all workloads for cpi/csi are `active` -- pass
