### ISSUE TITLE
rancher shows pod is "Terminating", but i did not find any pod infomation with using "kubectl describe"

### ISSUE THREAD

**Issue by wang-xiaowu** [rancher/rancher#37007]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details: [self-signed-ssl](https://docs.rancher.cn/docs/rancher2/installation/resources/advanced/self-signed-ssl/_index/#4-%E5%A6%82%E4%BD%95%E7%94%9F%E6%88%90%E8%87%AA%E7%AD%BE%E5%90%8D%E8%AF%81%E4%B9%A6)

**Information about the Cluster**
- Kubernetes version: v1.21.7+k3s1
- Cluster Type (Local/Downstream):  Imported or specify provider for Hosted
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

   
**Describe the bug**

> rancher shows pod is "Terminating", but i did not find any pod infomation with using "kubectl describe"

```
[root@release-master ~]# kubectl describe pod u-sopei-cn-6cf74d5ddc-n5glp -n sopei-biz
Error from server (NotFound): pods "u-sopei-cn-6cf74d5ddc-n5glp" not found
[root@release-master ~]# kubectl get pods -n sopei-biz -l app=u-sopei-cn
NAME                         READY   STATUS    RESTARTS   AGE
u-sopei-cn-674d8ff69-tr7b8   1/1     Running   0          89m
u-sopei-cn-674d8ff69-7tsrt   1/1     Running   0          89m
[root@release-master ~]# 
```
**To Reproduce**
 

**Result**

**Expected Result**

**Screenshots**

![image](https://user-images.githubusercontent.com/44340137/159632425-b2aaee89-6f50-4bf7-bc31-d62232528316.png)

**Additional context**

**Comment by kennyatzeroeyes** [comment]
See the same issue

**Comment by schwajo** [comment]
See also the same issue with Rancher 2.6.5 and Kubernetes 1.23.6

**Comment by fengcharles** [comment]
same issue

**Comment by rmoreas** [comment]
Same issue with Rancher 2.6.6.

The UI shows a pod in Terminating state:

![image](https://user-images.githubusercontent.com/1485197/181615046-138a3b0a-f3f6-4c21-8524-d3d2d3b3c5e4.png)

But this pod does not exist:

```
$ kubectl get pod ssave-entity-operator-6c7d58ffb7-w9hp8
Error from server (NotFound): pods "ssave-entity-operator-6c7d58ffb7-w9hp8" not found
```

How can we get rid of these "ghost" pods in rancher?

**Comment by rmoreas** [comment]
I think this is still relevant
