### ISSUE TITLE
RKE2 | Custom cluster | etcd restore leaves etcd node stuck in `Waiting for kubelet to update`

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#37001]
**Rancher Server Setup**
- Rancher version: v2.6-head 6b336a0
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.10
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom RKE2 cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Standard user is cluster owner and restore action was completed by Admin as describe [here](https://github.com/rancher/dashboard/issues/5320)

   
**Describe the bug**

After restoring snapshot, etcd node is stuck in `provisioning` with `Waiting for kubelet to update`
This is reproducible on custom clusters and also node driver clusters
```
[INFO ] provisioning bootstrap node(s) custom-e6ba3dffe8ef: waiting for plan to be applied
[INFO ] provisioning bootstrap node(s) custom-e6ba3dffe8ef: waiting for probes: kubelet
[INFO ] provisioning bootstrap node(s) custom-e6ba3dffe8ef: waiting for kubelet to update
```

After checking the etcd node, I saw that a command for kubelet was running for 1:05
```
root     30892 30873  2 20:25 ?        00:01:05 kubelet --volume-plugin-dir=/var/lib/kubelet/volumeplugins --file-check-frequency=5s --sync-frequency=30s --address=0.0.0.0 --alsologtostderr=false --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --client-ca-file=/var/lib/rancher/rke2/agent/client-ca.crt --cloud-provider=external --cluster-dns=<address> --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --container-runtime=remote --containerd=/run/k3s/containerd/containerd.sock --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --healthz-bind-address=127.0.0.1 --hostname-override=ip-<address> --kubeconfig=/var/lib/rancher/rke2/agent/kubelet.kubeconfig --log-file-max-size=50 --log-file=/var/lib/rancher/rke2/agent/logs/kubelet.log --logtostderr=false --node-labels=cattle.io/os=linux,rke.cattle.io/machine=5155e4fa-3e6b-41a3-ab54-e87c923acc95 --pod-manifest-path=/var/lib/rancher/rke2/agent/pod-manifests --read-only-port=0 --register-with-taints=node-role.kubernetes.io/etcd:NoExecute --resolv-conf=/run/systemd/resolve/resolv.conf --serialize-image-pulls=false --stderrthreshold=FATAL --tls-cert-file=/var/lib/rancher/rke2/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/rke2/agent/serving-kubelet.key
```

**To Reproduce**
 
Steps from [5320](https://github.com/rancher/dashboard/issues/5320)
1. Provision a downstream RKE2 custom cluster (3 nodes, different roles)
2. As an admin take a snapshot (cluster manager, cluster menu, take snapshot)
3. Wait for the snapshot to be created
4. Create a workload
5. Edit cluster's config (update upgrade strategy for example to 1 and add some labels to the cluster)
6. Upgrade cluster's k8s version to 1.22.7
7. Wait for the cluster to be upgraded (verify all nodes are on the new version)
8. Restore to the snapshot you took at step 3 (cluster manager -> cluster menu -> restore snapshot -> select "Cluster config, Kubernetes version and etcd"

**Result**
Cluster is stuck in `Provisioning` and etcd node is stuck in `Waiting for kubelet to update`

**Expected Result**

Cluster should be restored successfully and set to `Active`

**Comment by snasovich** [comment]
Bumped to 2.6.5 due to it being specific to RKE2 snapshot/restore that has some issues in 2.6.4 already. To be fixed for 2.6.5.

**Comment by thedadams** [comment]
I took a look at the setup that Tim had for this issue. The problem was that the rke2-server systemd service on the control plane node crashed. I am not sure why it crashed (the error was related to `unable to decode an event from the watch stream: context canceled`).

Restarting RKE2 fixed the problem and the restore completed successfully.

**Comment by thedadams** [comment]
### Root cause
A previous change was added to ensure that the planner doesn't move on to the next "tier" (etcd, control plane, worker) until the current tier is completely updated. This included the kubelet version.

This caused an issue with restore in some cases because the apiserver may not be running when the ectd nodes are restored.

### What was fixed, or what changes have occurred
The planner will better be able to detect when it should move on or wait for the current tier during retore.

### Areas or cases that should be tested
All of the following should be tested with 1 etcd-only, 1 cp, 1 worker and 3 etcd-only, 2 cp, and 1 worker clusters.
- Provisioning
- Snapshot
- Upgrade of Kubernetes version
- Restore snapshot

### What areas could experience regressions?
The above scenarios.

### Are the repro steps accurate/minimal?
Yes.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 0ad0def
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver

----------

### Testing: ###

Tested this issue with the following steps:

1. Provision a downstream RKE2 custom cluster (3 nodes, different roles)
2. As an admin take a snapshot (cluster manager, cluster menu, take snapshot)
3. Wait for the snapshot to be created
4. Create a workload
5. Edit cluster's config (update upgrade strategy for example to 1 and add some labels to the cluster)
6. Upgrade cluster's k8s version to 1.22.7
7. Wait for the cluster to be upgraded (verify all nodes are on the new version)
8. Restore to the snapshot you took at step 3 (cluster manager -> cluster menu -> restore snapshot -> select "Cluster config, Kubernetes version and etcd"

**Result** - Pass

The cluster is able to restore and come back into Active state.

**Comment by shkarface** [comment]
We have a cluster stuck in provisioning state because of this bug.

We were on Rancher 2.6.4, we tried upgrading an RKE2 cluster from v1.21.5rke2 to v1.21.12rke2, the upgrade failed because it could not install calico for some reason. 

We tried restoring from a snapshot, and the cluster was stuck with an error stating that it could not restore.

We upgraded to Rancher 2.6.5, and remove the `etcdSnapshotRestore` from the cluster YAML file, and manually downgraded the node back to 1.21.5rk2.

But now the machine is still in `Non-ready bootstrap machine(s) custom-65e731ef0841: waiting for kubelet to update
`

How can we set the cluster state back to normal?

**Comment by thedadams** [comment]
@shkarface What Kubernetes version is on the status of that machine object?

**Comment by shkarface** [comment]
@thedadams it was first upgraded to 1.21.12rke2, and stuck with restore error. I manually downgraded to v1.21.5rke2.

**Comment by shkarface** [comment]
@thedadams after 4 days, the node is still stuck in `waiting for kubelet to update`, while the rke2 version on the node is the expected version

**Comment by thedadams** [comment]
What Kubernetes version is on the status of the machine object?

**Comment by shkarface** [comment]
Here is the machine object:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/6STT4/TMBDFvwqac7LbNM5fiQuI0woOC+LUy9get6aOHdmTLqjqd0fJwtKlovw7Wp739Jv37CMMxKiREfojoPeBkW3waT4G+YkUJ+KbaMONQmZHNzbcWg09TH5Aj1vS+YBqZz1B9ktBePAU8+1hDz3cHorsxZ31+uV7UpH4tzKPA0EPakochryuqCkLMqtWFH8kTSOqRZ8PebUfjJEHCRnEPZ2NO5TkEvRw3MCZSdpAvwFn/fR5Ayc4ZaAiLfl8sAMlxmGE3k/OZfDd4fhMD/2j+grpDtMOeihoLTpquoZQke7qEmtZSNUJUVaiqkWndaVaYS7QVfAcg8tHh57yGNy8LMeJLiaJlb468K3IfOm3VCWua2pIqFUn6rqrVijEuqwLaZQp2qLVlWhQyMJUglppJK5E3RZr6syqqeawrjZ33o1xRJxrMjg5npVpJDVnKUPgxBHHJdjgjd3ek1me6mg/Ukw2eOh/WuMw2++tn7e4v3vz6snj34nm5t2UmOK7R4fEuLV+m3t6gAysNxETx0nxFOnvCF8vLG+f/tB/ICZGntKz3O4J9RfoDbpEl5w/7k6nrwEAAP//z9GbWAoEAAA
    objectset.rio.cattle.io/id: unmanaged-machine
    objectset.rio.cattle.io/owner-gvk: /v1, Kind=Secret
    objectset.rio.cattle.io/owner-name: custom-65e731ef0841
    objectset.rio.cattle.io/owner-namespace: c-m-5kmffbvb
    rke.cattle.io/join-url: https://10.10.80.112:9345
    rke.cattle.io/labels: '{"cattle.io/os":"linux"}'
  creationTimestamp: "2021-10-15T14:47:10Z"
  finalizers:
  - machine.cluster.x-k8s.io
  generation: 3
  labels:
    cattle.io/os: linux
    cluster.x-k8s.io/cluster-name: staging-new
    objectset.rio.cattle.io/hash: 1e249e797eaced963a6b1bc9443545649dd5c84f
    rke.cattle.io/control-plane-role: "true"
    rke.cattle.io/etcd-role: "true"
    rke.cattle.io/machine-id: 3c3a26e7e4c09466950a442361bfcf1818d547a4b1f54e8bfba046812e9f075
  managedFields:
  - apiVersion: cluster.x-k8s.io/v1alpha4
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:objectset.rio.cattle.io/applied: {}
          f:objectset.rio.cattle.io/id: {}
          f:objectset.rio.cattle.io/owner-gvk: {}
          f:objectset.rio.cattle.io/owner-name: {}
          f:objectset.rio.cattle.io/owner-namespace: {}
          f:rke.cattle.io/join-url: {}
          f:rke.cattle.io/labels: {}
        f:finalizers:
          .: {}
          v:"machine.cluster.x-k8s.io": {}
        f:labels:
          .: {}
          f:cattle.io/os: {}
          f:objectset.rio.cattle.io/hash: {}
          f:rke.cattle.io/control-plane-role: {}
          f:rke.cattle.io/etcd-role: {}
          f:rke.cattle.io/machine-id: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"e69ede6a-e935-43b7-9191-c37ca01fcd68"}: {}
      f:spec:
        .: {}
        f:bootstrap:
          .: {}
          f:configRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
          f:dataSecretName: {}
        f:clusterName: {}
        f:infrastructureRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
        f:providerID: {}
      f:status:
        .: {}
        f:addresses: {}
        f:bootstrapReady: {}
        f:infrastructureReady: {}
        f:lastUpdated: {}
        f:nodeInfo:
          .: {}
          f:architecture: {}
          f:bootID: {}
          f:containerRuntimeVersion: {}
          f:kernelVersion: {}
          f:kubeProxyVersion: {}
          f:kubeletVersion: {}
          f:machineID: {}
          f:operatingSystem: {}
          f:osImage: {}
          f:systemUUID: {}
        f:nodeRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
          f:uid: {}
        f:observedGeneration: {}
        f:phase: {}
    manager: rancher
    operation: Update
    time: "2021-12-22T09:54:16Z"
  - apiVersion: cluster.x-k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions: {}
    manager: rancher
    operation: Update
    subresource: status
    time: "2022-05-19T19:00:13Z"
  name: custom-65e731ef0841
  namespace: fleet-default
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1alpha4
    kind: Cluster
    name: staging-new
    uid: e69ede6a-e935-43b7-9191-c37ca01fcd68
  resourceVersion: "203120873"
  uid: 9a753fbe-bf8f-486b-abab-ba64b2f8c322
spec:
  bootstrap:
    configRef:
      apiVersion: rke.cattle.io/v1
      kind: RKEBootstrap
      name: custom-65e731ef0841
      namespace: fleet-default
    dataSecretName: custom-65e731ef0841-machine-bootstrap
  clusterName: staging-new
  infrastructureRef:
    apiVersion: rke.cattle.io/v1
    kind: CustomMachine
    name: custom-65e731ef0841
    namespace: fleet-default
  providerID: rke2://n2stgk8s
status:
  addresses:
  - address: 10.10.80.112
    type: InternalIP
  - address: n2stgk8s
    type: Hostname
  bootstrapReady: true
  conditions:
  - lastTransitionTime: "2021-10-15T14:49:26Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-10-15T14:47:11Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2021-10-15T14:49:26Z"
    status: "True"
    type: InfrastructureReady
  - lastTransitionTime: "2022-01-20T11:45:04Z"
    status: "True"
    type: NodeHealthy
  - lastTransitionTime: "2022-05-19T19:39:53Z"
    status: "True"
    type: PlanApplied
  - lastTransitionTime: "2022-05-19T19:08:06Z"
    message: waiting for kubelet to update
    reason: Waiting
    status: Unknown
    type: Provisioned
  - lastTransitionTime: "2022-05-23T19:57:16Z"
    status: "True"
    type: Reconciled
  infrastructureReady: true
  lastUpdated: "2021-10-15T14:49:26Z"
  nodeInfo:
    architecture: amd64
    bootID: 6f99b6e8-3136-49fb-9caf-9d63aae62267
    containerRuntimeVersion: containerd://1.4.11-k3s1
    kernelVersion: 5.4.0-96-generic
    kubeProxyVersion: v1.21.5+rke2r2
    kubeletVersion: v1.21.5+rke2r2
    machineID: 73e2d8a37dd141b1a92be3055cfed9c3
    operatingSystem: linux
    osImage: Ubuntu 20.04.3 LTS
    systemUUID: 30fa3942-ef85-eee1-4d68-ebb62b012f6d
  nodeRef:
    apiVersion: v1
    kind: Node
    name: n2stgk8s
    uid: d3301a8d-5052-4949-b1f7-4c95fe0a9c34
  observedGeneration: 3
  phase: Running
```

**Comment by thedadams** [comment]
@shkarface My guess is that since you manually downgraded the cluster because the snapshot restore failed, then the Kubernetes version on the `RKEControlPlane` object in Rancher is not `v1.21.5+rke2r2` as it shows here on the machine status. If that is the case (again only a guess), then that is what is causing the issue with the cluster be "stuck"

**Comment by shkarface** [comment]
@thedadams I just checked the RKEControlPlane object, the same kubernetes version is shown as the machine object.

Is there any workaround for this issue?

**Comment by thedadams** [comment]
If the control plane object and the machine status both have the same Kubernetes version, then there is something else that is causing this the hang like it is. It would be tough to debug through GitHub comments.
