### ISSUE TITLE
vSphere CSI update to 2.5.x to add support for 1.23.

### ISSUE THREAD

**Issue by phillipsj** [rancher/rancher#37005]
**Is your feature request related to a problem? Please describe.**

We are shipping version 2.4.1 in Rancher 2.6.4 which doesn't officially support Kubernetes 1.23. We need to upgrade to version 2.5.x to add support for Kubernetes 1.23. 2.5.x doesn't support versions older than 1.21. This will also bring in support for CSI on Windows nodes.

**Describe the solution you'd like**

Update Rancher Charts to pull in 2.5.x of the vSphere CSI chart.

# Checklist for items that need completed

- [x] Update Image-mirror repo
- [x] Update manifests in rancher/vsphere-charts
- [x] Notify about chart "release"
- [x] Update chart in rancher/charts
- [x] Update chart in rancher/rke2-charts
- [x] Updated RKE2 to consume new chart

**Comment by sirredbeard** [comment]
Pending implementation of 'super chart' for CSI.

**Comment by phillipsj** [comment]
### Root cause

NA
 
### What was fixed, or what changes have occurred

The images were updated to the latest bugfix versions that are currently available. The chart was also modified to be a "super" chart to allow auto-detecting the correct version to install based on the Kubernetes version. This was implemented with semver ranges. 
 
### Areas or cases that should be tested
 
The standard test plan located here should cover what needs tested.

* https://confluence.suse.com/pages/viewpage.action?pageId=851509848

### What areas could experience regressions?
 
That an incorrect version could be installed.

### Are the repro steps accurate/minimal?

Yes

**Comment by slickwarren** [comment]
validated the following use cases on rancher v2.6-head (6c12bee):
upgrade cases:
* deploy rke1 1.22.8 with external charts enabled
  * deploy the cpi/csi charts
  * test the charts by deploying a PVC using the new storage class -- pass
  * ensure all workloads for cpi/csi are `active` -- pass
* upgrade to v1.23.5
  * check for updates to the cpi/csi charts -- no update available
  * check that existing volume claim is working -- pass
  * deploy a new PVC -- pass


* deploy rke2 1.22.8+rke2r1 with vsphere charts enabled (cpi/csi is configured when deploying the cluster)
  * test the charts by deploying a PVC using the new storage class -- pass
  * ensure all workloads for cpi/csi are `active` -- pass
* upgrade to v1.23.5+rke2r1
  * check for updates to the cpi/csi charts -- no update available
  * check that existing volume claim is working -- pass
  * deploy a new PVC -- pass

Fresh install cases: 
* deploy rke1 1.23.5 with external charts enabled 
  * deploy the cpi/csi charts
  * test the charts by deploying a PVC using the new storage class -- pass
  * ensure all workloads for cpi/csi are `active` -- pass
* deploy rke2 1.23.5+rke2r1 with vsphere charts enabled (cpi/csi is configured when deploying the cluster)
  * test the charts by deploying a PVC using the new storage class -- pass
  * ensure all workloads for cpi/csi are `active` -- pass

verified version is 2.5.0: `rancher/mirrored-sig-storage-csi-node-driver-registrar:v2.5.0`
