### ISSUE TITLE
Post rancher upgrade rke1 cluster goes into updating state and comes backup active every few minutes

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37019]
**Rancher Server Setup**
- Rancher version: v2.6.3 upgraded to v2.6.4-rc12
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.21.9, 1.3.7
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.21.9
- Cluster Type (Local/Downstream): `Downstream node driver 1 worker, 1 etcd, 1 cp RKE1 Digital ocean`

**Describe the bug**
After upgrading the rancher server to v2.6.4-rc12, I noticed one of the downstream rke1 cluster goes into updating state and comes back up active. I have two other downstream RKE1 node driver clusters created with RKE1 templates. I do not see them going into `updating` state.

**To Reproduce**
1. Create an rke1 node driver cluster on 2.6.3 - 1 etcd, 1 cp, 1 worker.
2. Enable etcd snapshots in the advanced options.
3. Created a few workloads and ingress on this cluster
4. Upgrade rancher server to version v2.6.4-rc12

**Result**
After the rancher server is up, cluster comes up active and noticed that the cluster goes into `updating` state sporadically.

**Expected Result**
Expected the cluster to be active and not go into updating state.

**Screenshots**
<img width="500" alt="updating" src="https://user-images.githubusercontent.com/38144301/159809403-f38950c2-cc23-4c85-b6f1-171dce6c18da.png">

**Additional context**

Also tried upgrading the rancher server from 2.6.4 >> 2.6-head `b7c9b89` where I had 3 rke1 node driver clusters - 2 clusters with rke1 templates and 1 without template. See this happening for the cluster with rke1 template as well in this test setup where etcd snapshot is enabled.

_`Only seen on 1 out of 4 clusters`_

In the rancher pod logs, see the provisioning logs for the cluster scroll through continuously:
```


8:24 [INFO] Updated cluster [c-64qfk] with node version [1]
--
Wed, Mar 23 2022 3:48:24 pm | 2022/03/23 22:48:24 [INFO] Provisioned cluster [c-64qfk]
Wed, Mar 23 2022 3:48:24 pm | 2022/03/23 22:48:24 [INFO] checking cluster [c-64qfk] for worker nodes upgrade
Wed, Mar 23 2022 3:49:59 pm | 2022/03/23 22:49:59 [INFO] Provisioning cluster [c-64qfk]
Wed, Mar 23 2022 3:49:59 pm | 2022/03/23 22:49:59 [INFO] Updating cluster [c-64qfk]


Wed, Mar 23 2022 3:50:30 pm | 2022/03/23 22:50:30 [INFO] Updated cluster [c-64qfk] with node version [1]
Wed, Mar 23 2022 3:50:30 pm | 2022/03/23 22:50:30 [INFO] Provisioned cluster [c-64qfk]
Wed, Mar 23 2022 3:50:30 pm | 2022/03/23 22:50:30 [INFO] checking cluster [c-64qfk] for worker nodes upgrade


2022/03/23 22:53:25 [INFO] Updated cluster [c-64qfk] with node version [1]
--
Wed, Mar 23 2022 3:53:25 pm | 2022/03/23 22:53:25 [INFO] Provisioned cluster [c-64qfk]
Wed, Mar 23 2022 3:53:25 pm | 2022/03/23 22:53:25 [INFO] checking cluster [c-64qfk] for worker nodes upgrade
Wed, Mar 23 2022 3:55:03 pm | 2022/03/23 22:55:03 [INFO] Provisioning cluster [c-64qfk]
Wed, Mar 23 2022 3:55:03 pm | 2022/03/23 22:55:03 [INFO] Updating cluster [c-64qfk]

```

**Comment by cmurphy** [comment]
https://github.com/rancher/rancher/pull/37036

**Comment by cmurphy** [comment]
@anupama2501 the areas this touches are S3 etcd backups, RKE cluster deployment and updates, and node updates.

**Comment by anupama2501** [comment]
Verified on v2.6-head `6f9c19d ` upgraded from 2.6.3

1. Created a few downstream clusters with etcd snapshots enabled.
2. Upgraded the rancher server to v2.6-head, verified no clusters go into updating state. 
3. Took a few snapshots and verified the snapshot and restore work as expected. 


Fresh checks 2.6-head `6f9c19d` 

- Created an rke1 cluster with etcd snapshots enabled.
- Create an rke1 template with etcd snapshot enabled [with and without enable user override option]and created 2 clusters with the templates.
- Verified snapshots and restore on the clusters work as expected.
