### ISSUE TITLE
Load Balancer inconsistent behaviour for new containers

### ISSUE THREAD

**Issue by yunspace** [rancher/rancher#3701]
Apologies if this is an duplicate error. I did a search and couldn't find any similar issues. So here goes:

Rancher Version: v0.56.1

Docker Version: 1.9.1

OS: RancherOS 0.4.2 AMI

Steps to Reproduce: 

1. Add 2 nodes in Rancher using the "Custom" method (logging in and running docker agent)
2. Create a Load Balancer service which would spawn 2 containers, one on each node 
3. Add a 3rd Custom node by running docker agent. 

Results: 

The 3rd Load Balancer container running on the 3rd node has a different configuration to the first 2 containers. It contains linked services where as the first 2 containers are blank (see attached images)

If the Load Balancer was edited at a Service level (e.g. link a new service), the first 2 containers would automatically pick up the changes. Where as the 3rd Load Balancer will not update and return `503` errors. Until the container is restarted.

Expected:

New Load Balancer containers created as part of newly created nodes should behave exactly the same as the existing Load Balancer nodes on existing nodes.

All Load Balancers should consistently reflect the changes made at the Service level. 

![balancer1](https://cloud.githubusercontent.com/assets/218128/13344638/ee66daba-dcab-11e5-9dc1-ed6b149b1357.png)
![balancer2](https://cloud.githubusercontent.com/assets/218128/13344637/ee66b3aa-dcab-11e5-95fc-9dcd46fc6c94.png)
![balancer3](https://cloud.githubusercontent.com/assets/218128/13345423/cc40b008-dcb2-11e5-9a8b-d1786765eddd.png)

**Comment by deniseschannon** [comment]
At what step did you edit the load balancer to remove the targets? 
How did you update your load balancer to have no targets? When I try to save in the UI, it won't save. 

Should they all have the links or not have the links?

If you have multiple environments, you might be hitting #1389, which wasn't fixed until v0.59.0+. 

I have not been able to reproduce. My additional container has been updating like the other ones.

**Comment by yunspace** [comment]
Thanks I will try it out with 0.59.0

**Comment by deniseschannon** [comment]
@yunspace Please re-open if you are able to reproduce with v0.59.1+. Our current latest is v0.63.0
