### ISSUE TITLE
[rke2] custom cluster gets to an active state with only `etcd` and `controlplane` node(s)

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#37017]
**Rancher Server Setup**
- Rancher version: v2.6-head (b7c9b89)
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: any (tested with v1.22.7+rke2r2)
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): any (tested with admin user)

   
**Describe the bug**
when creating a custom cluster, the cluster gets to an active state before adding worker nodes

**To Reproduce**
* create a custom cluster 
* add an etcd/cp node (but no worker nodes)
* wait for the node to get to an active state

**Result**
* clluster is active without a worker node. 

**Expected Result**
the cluster shouldn't be able to be active until it has worker nodes added to the cluster. 

**Screenshots**
<img width="781" alt="Screen Shot 2022-03-23 at 1 04 34 PM" src="https://user-images.githubusercontent.com/16691014/159793927-701fc968-22f8-4f45-b92f-395ea35f94aa.png">

* probably related to the rke2 labeling issues

**Comment by paynejacob** [comment]
@slickwarren this is expected behavior for rke2 and k3s clusters.  RKE1 depended on worker nodes to schedule coredns.  rke2 and k3s will schedule coredns on controlplane nodes meaning that worker nodes are not technically required for an active cluster.

**Comment by slickwarren** [comment]
lets release note that this is the case then, since this is a change in behavior from rke1.
