### ISSUE TITLE
[windows rke2] can't deploy wins-upgrader on windows 2022 cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#37020]
**Rancher Server Setup**
- Rancher version: v2.6-head (b7c9b89)
- Installation option (Docker install/Helm Chart):docker 

**Information about the Cluster**
- Kubernetes version: v1.22.7+rke2r2
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom (windows, rke2)

**Describe the bug**
wins-upgrader does deploy, but the daemonset does not successfully deploy and continuously goes into `crashloopbackoff` state

**To Reproduce**
* deploy windows rke2 cluster using windows 2022 server
* deploy wins-upgrader chart

**Result**
* daemonset fails to successfully deploy pods for the chart. 

**Expected Result**
winsupgrader should deploy and all pods from deployment should get to an active state.

**Additional context**
* initial attempt was using default version in wins-upgrader, which had 2 pods in the daemonset. Both failed to deploy
* a 2nd attempt was made, upgrading and specifying version 0.2.1. Only 1 pod in the daemonset this time, but I was not able to view logs in either case through the UI or through kubectl.

**Comment by aiyengar2** [comment]
@luthermonson what we talked about offline, https://github.com/rancher/wins/blob/f4b33a072aa08d3dc5b4af3ed25a5b15b5a1c55d/charts/rancher-wins-upgrader/scripts/upgrade.ps1#L53 should be set correctly for RKE2

**Comment by phillipsj** [comment]
@aiyengar2 @luthermonson @slickwarren we don't need this functionality for RKE2. Wins is the system agent and needs to upgrade using the system agent upgrader.

**Comment by luthermonson** [comment]
the system agent upgrade process needs to line up with the wins upgrade process as wins is the windows system agent in rke2. per @slickwarren the upgrade process for system agent is to upgrade rancher to confirm new versions. we need to validate that process works for wins and open another issue against the v2prov upgrade process.

the wins-upgrader will need to be designated an rke1 only solution and this issue is probably closable.

**Comment by phillipsj** [comment]
Since we aren't going to support wins-upgrader on RKE2 and RKE1 for Windows is end of life, I am going to close this issue. /cc @snasovich

**Comment by phillipsj** [comment]
Work for supporting wins (windows system agent) upgrades for RKE2 is being handled here: https://github.com/rancher/windows/issues/181
