### ISSUE TITLE
OPA gatekeeper 100.0.1+up3.6.0 stuck uninstalling CRDs in RKE1/RKE2 Windows clusters

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#37029]
**Rancher Server Setup**
- Rancher version: v2.6.4-rc11
- Installation option (Docker install/Helm Chart): n/a
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.22.7 (RKE1), v1.22.7 (RKE2) 
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Windows

**Describe the bug**

**To Reproduce**
* Install rancher-gatekeeper `100.0.1+up3.6.0` in a RKE1/RKE2 Windows cluster
* Uninstall rancher-gatekeeper
* Check gatekeeper pod associated with the CRD uninstall job

**Result**
The rancher-gatekeeper chart gets stuck uninstalling, seemingly due to a pod from the crd uninstall job getting scheduled in a windows node which may not be supported.
![image](https://user-images.githubusercontent.com/8951271/159968366-b69702bb-0496-4f74-8184-97e8e7ee24fa.png)

**Comment by sirredbeard** [comment]
The changes that created this issue have been reverted but will be fixed in the next release.

Propose that this issue be assigned to Helm Yes. @SheilaghM

**Comment by eliyamlevy** [comment]
PR: https://github.com/rancher/charts/pull/1872

**Comment by SheilaghM** [comment]
There is a PR for this, but we need to push to v2.6.6 because testing requires a setup that QA is unfamiliar with and they won't be able to test this in time.

**Comment by doflamingo721** [comment]
@eliyamlevy The installation for gatekeeper `100.1.1+up3.7.1` which was added in https://github.com/rancher/charts/pull/1872 was erroring out because of the missing `linux-node-tolerations` & `linux-node-selector` templates. I have raised a PR https://github.com/rancher/charts/pull/1938 to fix this installation issue. 
cc: @SheilaghM @MKlimuszka @samkulkarni20

**Comment by vivek-infracloud** [comment]
Validated this issue on rancher v2.6-head and v2.7-head windows cluster - 1cp, 1etcd, 1wk (Linux), 1wk (Windows)

Validation steps:

1. Created a rancher v2.6-head and v2.7-head
2. Provisioned a k8s cluster `v1.22.15-rancher1-1`
3. Installed a OPA-gatekeeper `v100.2.0+up3.8.1`
4. Made sure the chart is getting installed and working correctly.
5. Uninstalled the OPA-gatekeeper then gatekeeper-CRD.

Result 
1. Uninstall progress do not get stuck. Uninstallation was successful.
2.  OPA gatekeeper chart was removed successfully.

Issue is not active anymore. Hence, closing the issue.

**Comment by vivek-infracloud** [comment]
Also validated the same with OPA-gatekeeper 101.0.0+up3.9.0. Uninstallation was successful.
