### ISSUE TITLE
no secret assigned to service account cattle-system/rancher

### ISSUE THREAD

**Issue by jgourmelen** [rancher/rancher#37027]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.19
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

* Custom = Running a docker command on a node
* Imported = Running kubectl apply onto an existing k8s cluster 
* Hosted = EKS
 * Infrastructure Provider = AWS

**User Information**
- What is the role of the user logged in? Admin

   
**Describe the bug**
I was trying to change my rancher URL with helm install.

But now, my pod is down :
```
2022/03/24 13:27:59 [INFO] Rancher version v2.6.3 (3c1d5fac3) is starting
3
2022/03/24 13:27:59 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2
2022/03/24 13:27:59 [INFO] Listening on /tmp/log.sock
1
2022/03/24 13:27:59 [FATAL] no secret assigned to service account cattle-system/rancher

```

**Comment by jgourmelen** [comment]
I use ArgoCD to install it !

**Comment by fungiboletus** [comment]
I got the same error after I uninstalled and reinstalled Rancher through ArgoCD.

I think it is related to the issue https://github.com/rancher/rancher/issues/33988 

Running helm manually produces the following error:

```
Error: INSTALLATION FAILED: create: failed to create: Internal error occurred: failed calling webhook "rancher.cattle.io": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s": service "rancher-webhook" not found
```

The workaround for me was deleting the broken webhook : `kubectl delete MutatingWebhookConfigurationrancher.cattle.io`.

**Comment by ramarov** [comment]
I am getting similar error on cattle-cluster-agent pod.
I guess this error generated from getTokenFromAPI() `https://github.com/rancher/rancher/blob/f8b1948c22e9d8cc5fff2da37d47ee7ec19bbcc1/pkg/agent/cluster/cluster.go#L51` 

I checked the cattle service account doesn't have the secret. Looks the function above expecting ServiceAccountRootCAKey and ServiceAccountTokenKey. How can I get this info from my Rancher server? Can I add this secret into the service account, will that solve the issue?


following the logs from the pod.

`INFO: Environment: CATTLE_ADDRESS=192.168.200.139 CATTLE_CA_CHECKSUM=416b2f4d272acce6f53913b24a9829e7e393e7a7e059aca2441f51e719b3a895 CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.98.229.251:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.98.229.251:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.98.229.251 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.98.229.251:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.98.229.251 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.98.229.251 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_CLUSTER_REGISTRY= CATTLE_INGRESS_IP_DOMAIN=sslip.io CATTLE_INSTALL_UUID=23fc6a1d-9991-4362-a68e-a1ee0ea81e69 CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-5975998d67-57k9c CATTLE_SERVER=https://<servername> CATTLE_SERVER_VERSION=v2.6.5
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.96.0.10 options ndots:5
INFO: https://<servername>/ping is accessible
INFO: <servername> resolves to 10.146.68.37
INFO: Value from https://<servername>/v3/settings/cacerts is an x509 certificate
time="2022-05-22T13:19:14Z" level=info msg="Listening on /tmp/log.sock"
time="2022-05-22T13:19:14Z" level=info msg="Rancher agent version v2.6.5 is starting"
time="2022-05-22T13:19:14Z" level=fatal msg="looking up cattle-system/cattle ca/token: no secret exists for service account cattle-system/cattle"`

**Comment by JDB1976** [comment]
I am getting this when attempting to deploy the Rancher agent (container) to a newly stood up K8S cluster. I am using the latest version of K8S (1.24) with the latest version of Rancher running in a docker container on a separate host in my test lab.

INFO: Environment: CATTLE_ADDRESS=172.16.155.32 CATTLE_CA_CHECKSUM=90a78de8a4eb83b74a556b3100cd6c700629d3a27dec6855424d0f3cae159a60 CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.97.31.138:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.97.31.138:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.97.31.138 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.97.31.138:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.97.31.138 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.97.31.138 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_CLUSTER_REGISTRY= CATTLE_INGRESS_IP_DOMAIN=sslip.io CATTLE_INSTALL_UUID=f3c8a564-bdee-4a2b-8b9f-f8695e2c026a CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-7bcfc9c568-zqvc9 CATTLE_SERVER=https://<servername>/ CATTLE_SERVER_VERSION=v2.6.5
INFO: Using resolv.conf: search <domain> nameserver <nameserver> nameserver <nameserver>
INFO: https://centos-rancher-server.jnet.home.arpa/ping is accessible
INFO: <rancher server> resolves to <an IP on my local network>
INFO: Value from https://<servername>/v3/settings/cacerts is an x509 certificate
time="2022-05-22T13:52:32Z" level=info msg="Listening on /tmp/log.sock"
time="2022-05-22T13:52:32Z" level=info msg="Rancher agent version v2.6.5 is starting"
time="2022-05-22T13:52:32Z" level=fatal msg="looking up cattle-system/cattle ca/token: no secret exists for service account cattle-system/cattle"

For the life of me, I cannot figure out why this is occurring.

**Comment by saurabht16** [comment]
> I am getting this when attempting to deploy the Rancher agent (container) to a newly stood up K8S cluster. I am using the latest version of K8S (1.24) with the latest version of Rancher running in a docker container on a separate host in my test lab.
> 
> INFO: Environment: CATTLE_ADDRESS=172.16.155.32 CATTLE_CA_CHECKSUM=90a78de8a4eb83b74a556b3100cd6c700629d3a27dec6855424d0f3cae159a60 CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.97.31.138:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.97.31.138:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.97.31.138 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.97.31.138:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.97.31.138 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.97.31.138 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_CLUSTER_REGISTRY= CATTLE_INGRESS_IP_DOMAIN=sslip.io CATTLE_INSTALL_UUID=f3c8a564-bdee-4a2b-8b9f-f8695e2c026a CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-7bcfc9c568-zqvc9 CATTLE_SERVER=https://<servername>/ CATTLE_SERVER_VERSION=v2.6.5 INFO: Using resolv.conf: search <domain> nameserver <nameserver> nameserver <nameserver> INFO: https://<rancher server>/ping is accessible INFO: <rancher server> resolves to <an IP on my local network> INFO: Value from https://<servername>/v3/settings/cacerts is an x509 certificate time="2022-05-22T13:52:32Z" level=info msg="Listening on /tmp/log.sock" time="2022-05-22T13:52:32Z" level=info msg="Rancher agent version v2.6.5 is starting" time="2022-05-22T13:52:32Z" level=fatal msg="looking up cattle-system/cattle ca/token: no secret exists for service account cattle-system/cattle"
> 
> For the life of me, I cannot figure out why this is occurring.

I am getting the same error. My kubernetes verion is 1.24.1. 

With 1.23 this works well. Can anyone confirm if Rancher is compatible with Kubernetes version 1.24.1?

I know Docker support is removed from latest Kubernetes 1.24 so that might be causing the issue.

**Comment by groucho64738** [comment]
I have a similar problem and am using the latest k3s to install (which is also kubernetes 1.24), rancher 2.6.5. This is in an air-gapped environment.

**Comment by brandond** [comment]
Rancher is not supported on Kubernetes 1.24. Supported Kubernetes versions are listed in the notes for each release. Support for this version is planned for the 2.6.6 release. The current chart shouldn't even allow you to install it on Kubernetes 1.24, so I'm not sure how you'd get there unless you upgraded the cluster after installing Rancher.

**Comment by groucho64738** [comment]
@brandond yeah, I decided to go with an earlier version of k3s and have gotten much further.

**Comment by JDB1976** [comment]
@brandond That is *exactly* how I got there. I had Rancher already installed and tied into an RKE2 cluster in my lab. Pushed my K8S cluster in the lab to 1.24 on a rebuild and then tried to import it into Rancher.

Thanks for the heads up - I guess I didn't read the supported platform notes very well. :)

**Comment by datamattsson** [comment]
I'm hitting this on 2.6.6, did anyone find out what caused this?

**Comment by JDB1976** [comment]
The release notes for 2.6.6 suggest:

_Rancher v2.6.6 is a mirror release of v2.6.5 with one change to address the following issue:_

_- A major performance issue was occurring when Rancher was attempting to control large volumes of traffic from downstream clusters. This mechanism was not handling disconnects properly and would result in indefinite locks. See https://github.com/rancher/rancher/issues/37250._

So I am guessing they have not added K8S 1.24 compatibility to this release esp since the compatible versions in v2.6.6 are:
 
v1.18.20-rancher1-3
v1.19.16-rancher1-5
v1.20.15-rancher1-3
v1.21.12-rancher1-1
v1.22.9-rancher1-1
v1.23.6-rancher1-1

**Comment by farzadso** [comment]
I can confirm the issue still exists.

Downgrading k3s to v1.23.x solved the issue for me.

**Comment by sguyennet** [comment]
On a 1.24 Kubernetes cluster, the rancher-agent is failling with the error:
```
level=fatal msg="looking up cattle-system/cattle ca/token: no secret exists for service account cattle-system/cattle"
```

This is because with the version of Kubernetes 1.24, the kube-controller-manager feature gate LegacyServiceAccountTokenNoAutoGeneration is enabled by default:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes

As a workaround, you can disable this feature gate.

**Comment by farzadso** [comment]
> On a 1.24 Kubernetes cluster, the rancher-agent is failling with the error:
> 
> ```
> level=fatal msg="looking up cattle-system/cattle ca/token: no secret exists for service account cattle-system/cattle"
> ```
> 
> This is because with Kubernetes version 1.24, the kube-controller-manager feature gate `LegacyServiceAccountTokenNoAutoGeneration` is enabled by default: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes
> 
> As a workaround, you can disable this feature gate.

How does it get disabled?

**Comment by ael-p** [comment]
@farzadso Guess it didn't worked out for me, using RKE2 :sweat_smile:

**Comment by ael-p** [comment]
> @farzadso Guess it didn't worked out for me, using RKE2 sweat_smile

My bad, seems this is a **controller-manager** feature flag, not kubelet.

**Comment by surendarrajasekaran** [comment]
Thanks, it really helped us  :)

**Comment by ThangEthan** [comment]
This is how I did it.

1. SSH into master node. 
2. Go to /etc/kubernetes/manifest/
3. Edit kube-controller-manager.manifest. Add LegacyServiceAccountTokenNoAutoGeneration=false into spec.container.args

kube-controller-manager pod will automatically restart will new changes

**Comment by isweluiz** [comment]
Hello, 

Does anyone was able to solve it without disabling the LegacyServiceAccountTokenNoAutoGeneration ? 

 @ael-p @ThangEthan

or with another option

**Comment by ael-p** [comment]
@isweluiz I believe that is not possible since this feature is made default in 1.24. 

Rancher should, in the latest versions, use the proper Token Auth API to register a token... Not tested yet, nor have checked the releases changelog. Give it a try!

**Comment by papandadj** [comment]
The fellowing method works for me.
1. Add a secret in serviceaccount namespace:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: rancher-token
  namespace: cattle-system
  annotations:
    kubernetes.io/service-account.name: "rancher"
type: kubernetes.io/service-account-token
```
serviceaccount is rancher, and namespace is cattle-system
2. Fix serviceaccount yaml, add secret field:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/25424898/202375861-0616a774-8d49-493c-a714-64da0f9bc06d.png">

**Comment by majorgear** [comment]
> The fellowing method works for me.
> 
> 1. Add a secret in serviceaccount namespace:
> 
> ```yaml
> apiVersion: v1
> kind: Secret
> metadata:
>   name: rancher-token
>   namespace: cattle-system
>   annotations:
>     kubernetes.io/service-account.name: "rancher"
> type: kubernetes.io/service-account-token
> ```
> 
> serviceaccount is rancher, and namespace is cattle-system 2. Fix serviceaccount yaml, add secret field: <img alt="image" width="332" src="https://user-images.githubusercontent.com/25424898/202375861-0616a774-8d49-493c-a714-64da0f9bc06d.png">
Where is serviceaccount yaml? is that on the rancher rke2 server ? or is it on the k3s cluster manager node?

**Comment by irrelevanti** [comment]
> > The fellowing method works for me.
> > 
> > 1. Add a secret in serviceaccount namespace:
> > 
> > ```yaml
> > apiVersion: v1
> > kind: Secret
> > metadata:
> >   name: rancher-token
> >   namespace: cattle-system
> >   annotations:
> >     kubernetes.io/service-account.name: "rancher"
> > type: kubernetes.io/service-account-token
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > serviceaccount is rancher, and namespace is cattle-system 2. Fix serviceaccount yaml, add secret field: <img alt="image" width="332" src="https://user-images.githubusercontent.com/25424898/202375861-0616a774-8d49-493c-a714-64da0f9bc06d.png">
> > Where is serviceaccount.yaml file located?  is that on the rancher rke2 server ? or is it on the k3s cluster manager node?

on the master you want to import. just download the yaml you get from rancher.
e.g.

`curl --insecure -sfL https://192.168.178.37:8443/v3/import/blub.yaml > rancher.yaml`

and append the file with following before doing the apply:

`---

apiVersion: v1
kind: Secret
metadata:
  name: rancher-token
  namespace: cattle-system
  annotations:
    kubernetes.io/service-account.name: "cattle"
type: kubernetes.io/service-account-token

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cattle
  namespace: cattle-system
secrets:
- name: rancher-token
`

`kubectl apply -f ./rancher.yaml`

in my case it was serviceaccount cattle instead of rancher so you may have to change cattle to rancher
