### ISSUE TITLE
[SURE-6047] Performance issues when clusters are unavailable

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#37021]
Internal reference: [SURE-6047](https://jira.suse.com/browse/SURE-6047)

**Note:**
I am creating this issue now for tracking but plan to add more details as they are uncovered.

**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

   
**Describe the bug**
Rancher experiences memory leak when clusters go unavailable.

**To Reproduce**
Setup scaling environment and then let cloud custodian deleting underlying infrastructure for the clusters.

**Result**
Memory leak, see screenshot.

**Expected Result**
Memory utilization should not grow nonstop.

**Screenshots**
![image](https://user-images.githubusercontent.com/19376037/159812995-fce6b9db-232e-4438-81b3-39d96c5366ca.png)

**Additional context**

**Comment by dnoland1** [comment]
Ran the following test over ~6 day period:
- installed Rancher 2.6.4-rc11, single node (2vCPU, 8GB RAM m5a.large AWS instance) on k3s 1.20.15 cluster, v1 monitoring enabled
- provisioned 10 custom RKE clusters, each with 1 node w/ all roles
- deleted the 10 VMs used for the 10 clusters
- let the environment run for about 6 days
Observed a steady increase in memory:
![image](https://user-images.githubusercontent.com/468462/160757871-641213fd-0a84-4e69-9421-78caece141f0.png)
Unfortunately, the node crashed and was replaced by a new node before I could take a pprof.

**Comment by gaktive** [comment]
Internal references: SURE-2319 & SURE-6047

**Comment by gaktive** [comment]
And SURE-6018

**Comment by moio** [comment]
And SURE-6630

**Comment by moio** [comment]
User that reported this issue confirmed it's resolved with the latest version, so I am closing this issue.

Work on similar and possibly related issues reported by other users continues in:

- SURE-2319: https://github.com/rancher/rancher/issues/27676
- SURE-6630: https://github.com/rancher/rancher/issues/42864
- SURE-6018: untracked, general intention of addressing problems with disconnected clusters
