### ISSUE TITLE
Add support for multiple ip addresses per inteface

### ISSUE THREAD

**Issue by keras** [rancher/rancher#3703]
Rancher Version: v0.59.1

Docker Version: 1.10.2

OS: Ubuntu 14.04.4 LTS

Steps to Reproduce: On a new host machine:
- Add new routable IP address to a host machine: `ip addr add 1.2.3.4/32 dev eth0`
- Verify that the new address works: `curl -sv --interface 1.2.3.4 httpbin.org/ip`
- Verify that there are multiple IPs assigned to eth0:

``` ShellSession
# ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether aa:aa:aa:aa:aa:aa brd ff:ff:ff:ff:ff:ff
    inet 100.100.100.189/29 brd 100.100.100.191 scope global eth0
       valid_lft forever preferred_lft forever
    inet 1.2.3.4/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2a01:aaa:b::4/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::468a:..../64 scope link 
       valid_lft forever preferred_lft forever
```
- Add this new custom host to rancher

Results: Host is added, but only one, the original external IP is detected by rancher but the additional is not. The IP does not show in the UI nor in the API (`/v1/projects/1a5/hosts/1h4/ipaddresses`)

Expected:
- The additional ip would show up in the UI and API
- The IP would be usable for the containers allowing allocation of multiple containers on same host with overlapping public ports.

Additional request:
Also add support for larger IP ranges e.g. `ip addr add 1.2.3.1/29 dev eth0`

**Comment by maxgorovenko** [comment]
Am I right and this issue is exactly what I need to make couple stacks on one host, each stack with its own nginx, listening 80 port at personal ip?

I'm gonna build stacks for selenuim tests, each stack points at a specific git branch. Each stack has nginx at 80 port with specific domain, binded at public ip of the nginx container.

**Comment by soumyalj** [comment]
Tested with v1.4.0-rc7. Multiple IPs can be added to an interface on a host. Containers get scheduled to the IPs sucessfully.
```
root@soumyarc7-ipsched-01:~# ip addr show eth1
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether a6:bc:42:d9:98:49 brd ff:ff:ff:ff:ff:ff
    inet 10.132.24.31/16 brd 10.132.255.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet 10.132.24.11/32 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a4bc:42ff:fed9:9849/64 scope link 
       valid_lft forever preferred_lft forever

```
<img width="954" alt="screen shot 2017-02-02 at 5 35 35 pm" src="https://cloud.githubusercontent.com/assets/18536626/22576079/692d2342-e96e-11e6-8d31-312a28d2ace5.png">

**Comment by wizarden1** [comment]
Hi, with rancher 2.0.4  I have the same problem
https://github.com/rancher/rancher/issues/14428

**Comment by cjellick** [comment]
1.x and 2.x are completely unrelated. this issue is not related to the one you filed.
