### ISSUE TITLE
Improve performance of cleanup script for upgrade and rollback via backup and restore

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37040]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6.3 >> 2.6.4-rc13 >> 2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.21.9, v1.3.7
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.21.9
- Cluster Type (Local/Downstream): `Downstream node driver 1 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
https://github.com/rancher/rancher/issues/36803 requires manually running cleanup script post rancher upgrade before rolling back to the previous rancher version. Cleanup script takes approximately 40 - 45min for 5 downstream clusters. This performance can be improved as with additional clusters this might significantly increase the duration it takes to run the script.

**Comment by superseb** [comment]
@anupama2501 Can you add if the script was run on a controlplane node of the cluster or on a separate Linux machine (not a cluster node) in this case?

**Comment by anupama2501** [comment]
@superseb When I logged the ticket I ran the script on a separate Linux machine.
But I tried running it on a controlplane node later as a kubernetes job and see that the script takes 45min to finish. 

```
kubectl get job  cleanup-job -n  kube-system
NAME          COMPLETIONS   DURATION   AGE
cleanup-job   1/1           45m        54m
```

**Comment by superseb** [comment]
This can be tested with `rancher/rancher-cleanup:v1.0.0-rc2`, it should be 1/3 faster on average. This is probably the best we can do for now, based on the use-case and usage.

Deploy using (we might create a Helm chart to make this testing a bit easier):

```
curl -sL https://raw.githubusercontent.com/rancher/rancher-cleanup/v1.0.0-rc2/deploy/rancher-cleanup.yaml | sed -e 's/latest/v1.0.0-rc2/'| kubectl create -f -
```

**Comment by AndrewHoffmanQA** [comment]
assigning Nick to this ticket, we are working them together.

**Comment by nickwsuse** [comment]
@superseb while testing https://github.com/rancher/rancher/issues/37676 @AndrewHoffmanQA and I ran the cleanup script on a HA cluster with two downstream clusters (one RKE1 and one RKE2 cluster) and the cleanup script finished in ~18min. 

I copied the script from https://github.com/rancher/rancher-cleanup/blob/main/cleanup.sh and made an executable file on one of the local nodes with it. The two clusters took about 9min each and if we had five clusters like noted in this ticket it would still be ~45min.

Is this enough information to call this ticket tested with no noticeable speed improvement?

**Comment by superseb** [comment]
Possibly, but a lot of information is missing:

- Are you using the same setup as @anupama2501 (instances/specs etc) or did you use the old script on the same setup so it can be compared
- I don't really understand why it is described as `I ran the cleanup script on a HA cluster with two downstream clusters` an d as `I copied the script from`. It needs to be used as described in the README (https://github.com/rancher/rancher-cleanup#run-as-a-kubernetes-job) and run as a job.
- I would just create the setup with 5 clusters  and run the job instead of making calculations, there is also no way to properly say if it has improved if we don't really test it.

**Comment by nickwsuse** [comment]
`Verified on 2.6.6-rc1`

I made five downstream clusters with 1 worker, 1 etcd, and 1 control plane and then ran the cleanup script as a kubernetes job. It took ~35min (from 1:39pm-2:15pm PST) so it does seem like the script is a bit faster now.
