### ISSUE TITLE
v0.59 HTTP/1.1 error

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#3704]
When adding a HTTP/1.1 health check to a service I am encountering the following error (the error does not occur in rancher server v0.56):

Tailing the logs from the rancher server gives:

```
[scripts.sh:176] haproxy -p /var/run/haproxy.pid -f /etc/healthcheck/healthcheck.cfg -sf 13914
[ALERT] 056/130929 (14364) : parsing [/etc/healthcheck/healthcheck.cfg:31] : unknown keyword 'Host: www.healthcheck.com' in 'backend' section
[ALERT] 056/130929 (14364) : Error(s) found in configuration file : /etc/healthcheck/healthcheck.cfg
[WARNING] 056/130929 (14364) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.
[ALERT] 056/130929 (14364) : Fatal errors found in configuration.
```
In the network agent **/etc/healthcheck/healthcheck.cfg** the following appears:
```
backend c7e80dcb-7e98-4e96-86d9-07195f58c7a1_backend
        mode http
        balance roundrobin
        timeout check 2000
        option httpchk GET /healthcheck HTTP/1.1^M
Host:\ www.healthcheck.com
        server cattle-c7e80dcb-7e98-4e96-86d9-07195f58c7a1_1 10.42.61.174:80 check port 80 inter 2000 rise 2 fall 3
```
Due to the error that is being generated I'm guessing its the **^M** that is being introduced that is causing the problem. This happens when trying to add HTTP/1.1 checks through the UI or via rancher-compose.
The failure stops any new containers spinning up with them all getting stuck in the Networking state.
This problem doesn't occur using a 1.0 health check

**Steps to recreate in UI:**
Under a stack, add service:
Pick a name and image
under advanced options, health checks
set type to HTTP Responds 2xx/3xx
set a report and request address, chance the type to HTTP/1.1
add a Host Header of www.healthchecks.com and then create service.

The above errors should appear within seconds.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.1` Cattle: `v0.148.1` UI: `v0.90.0` |
|Access|`Disabled`}|
|Route|`null`|

**Comment by vincent99** [comment]
This is how you add a host header in 1.5 but probably broken by changes in 1.6 where they added "quoted string technology", @alena1108

**Comment by alena1108** [comment]
@vincent99 the new format would be this:

```
option httpchk GET /foo HTTP/1.1\r\nHost: www.domain.com
```

https://cbonte.github.io/haproxy-dconv/configuration-1.6.html#4-option%20httpchk

It would be the UI fix, right?

**Comment by vincent99** [comment]
I think it needs to have quotes, but yes either way the UI controls that

```
option httpchk GET / "HTTP/1.1\r\nHost: www.domain.com"
```

**Comment by alena1108** [comment]
@vincent99 I've checked, it works w/o the quotes. Will double check again once UI fix is propagated, and put the quotes if needed.

**Comment by tfiduccia** [comment]
Version - master UI 3/17
Verified fixed
