### ISSUE TITLE
External IP Webhook installation fails on 1.22 and higher clusters

### ISSUE THREAD

**Issue by eliyamlevy** [rancher/rancher#37045]
**Rancher Server Setup**

Rancher version: v2.6.4-rc11
Installation option (Docker install/Helm Chart): n/a
If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
Proxy/Cert Details:
Information about the Cluster

Kubernetes version: v1.22.7 (RKE1), v1.22.7 (RKE2)
Cluster Type (Local/Downstream): Downstream
If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Windows
Describe the bug

**Describe the bug**

**To Reproduce**

Install rancher-external-ip-webhook  (100.0.0+up1.0.0) in a 1.22 or higher cluster (this was reproduced on RKE1/RKE2 Windows clusters)

**Result**

The installation will fail and have this error message:
`unable to recognize “”: no matches for kind “ValidatingWebhookConfiguration” in version “[admissionregistration.k8s.io/v1beta1](http://admissionregistration.k8s.io/v1beta1)”]` 

**Expected Result**
Expected result was a clean and successful installation of the chart.

**Screenshots**
<img width="1162" alt="Screen Shot 2022-03-25 at 1 09 08 PM" src="https://user-images.githubusercontent.com/31217626/160168643-01603e0f-203a-49dc-9b6c-e8b5f05a8104.png">
[The cert-manager errors are unrelated]

**Additional context**
@bmdepesa referred us to a [page](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#webhook-resources-v122) detailed the deprecations in k8s v1.22. According to this page `ValidatingWebhookConfiguration` is deprecated in v1.22 which is the default version of k8s that Rancher installs. 

From the source:

> Webhook resources
> The admissionregistration.k8s.io/v1beta1 API version of MutatingWebhookConfiguration and ValidatingWebhookConfiguration is no longer served as of v1.22.
> 
> Migrate manifests and API clients to use the admissionregistration.k8s.io/v1 API version, available since v1.16.

**Comment by bmdepesa** [comment]
An older version of the chart was used. The newer version works correctly. 

https://github.com/rancher/rancher/issues/33893
