### ISSUE TITLE
System Agent instructions improperly handles PowerShell environment variables.

### ISSUE THREAD

**Issue by phillipsj** [rancher/rancher#37044]
**Rancher Server Setup**
- Rancher version: 2.6-head
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): K3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.22.7-rke2r2
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

   
**Describe the bug**

Setting agent envvars in the UI when creating a new RKE2 custom cluster in cluster management get passed into the system agent plans as instructions. When formatting those instructions, Windows PowerShell isn't accounted for being used, which produces improperly formatted environment variables.
 
**To Reproduce**

1. Create a custom rke2 cluster for 1.22.7 rke2r2
2. Configure agent envvars
3. Register 1 linux controlplane, 1 linux etcd, 1 linux worker, and 1 windows worker
4. Check the logs for Wins to see the following error.

**Result**

```
S C:\> gc .\var\lib\rancher\agent\applied\20220324-153909-applied.plan
{"Plan":{"files":[{"content":"eyJjb25maWdzIjp7fSwibWlycm9ycyI6bnVsbH0=","path":"/etc/rancher/agent/registries.yaml"},{"content":"eyJj
b25maWdzIjp7fSwibWlycm9ycyI6bnVsbH0=","path":"/etc/rancher/rke2/registries.yaml"},{"content":"
/etc/rancher/rke2/config.yaml.d/50-rancher.yaml"}],"instructions":[{"name":"install","image":"rancher/system-agent-installer-rke2:v1.
22.7-rke2r2","env":["$env:RESTART_STAMP=f80f465cfbe80ad3f6f6c82c3ab16fe2dff7e3aa69b14184368b451ea26f7ac3","HTTP_PROXY=ec2-3-239-92-48
.compute-1.amazonaws.com:3128","HTTPS_PROXY=ec2-3-239-92-48.compute-1.amazonaws.com:3128","NO_PROXY=localhost,127.0.0.1,0.0.0.0,10.0.
0.0/8,cattle-system.svc","$env:INSTALL_RKE2_EXEC=agent"],"args":["-File","run.ps1"]
```

**Expected Result**

Expected result is that environment variables are formatted correctly meaning wrapped in qoutes and prefixed with `$env:`.

**Comment by phillipsj** [comment]
### Root cause 

Setting agent envvars in the UI when creating a new RKE2 custom cluster in cluster management get passed into the system agent plans as instructions. When formatting those instructions, Windows PowerShell isn't accounted for being used, which produces improperly formatted environment variables.

### What was fixed, or what changes have occurred

The code that generates the instructions for the system agent was modified to account for the OS being Windows. If it is windows it formats the environment variables correctly for PowerShell.

 ### Areas or cases that should be tested 

Deployment of a custom RKE2 cluster should be tested as this is the only code path that would be impacted by these changes.

### What areas could experience regressions?

Registration of the different nodes would be impacted for RKE2 custom clusters.

 ### Are the repro steps accurate/minimal?

1. Create a custom rke2 cluster for 1.22.7 rke2r2
2. Configure agent envvars
3. Register 1 linux controlplane, 1 linux etcd, 1 linux worker, and 1 windows worker
4. Check the logs for Wins to see the following error.

**Comment by sirredbeard** [comment]
Will be tested through standard custom cluster process.

**Comment by slickwarren** [comment]
on v2.6.5-rc1, tested as part of this ticket (proxy). Blocking this ticket based on the findings here: https://github.com/rancher/rancher/issues/36574

**Comment by slickwarren** [comment]
on 2.6-head (5f04f3a) I am able to see that an environment variable is added to windows when running the registration command through powershell

steps:

* on a custom cluster, add environment variables
* register all linux nodes
* in the windows registration command, ensure that there is a line with `$env...` with your environment variable(s)
* run the windows reg. command on a windows node
  * after the command completes, run `dir env:` to list all environment vars. Here, you can see the var added through rancher
