### ISSUE TITLE
Internal rancher-dns nameserver ip is populated with some delay.

### ISSUE THREAD

**Issue by keras** [rancher/rancher#3705]
Rancher Version: 0.59.1

Docker Version: 1.10.2

OS: Ubuntu 14.04.4 LTS

Steps to Reproduce: Create a container where the entrypoint tries to use the internal rancher-dns service

Results: DNS query fails as the internal nameserver is populated to `/etc/resolv.conf` with some delay.

Expected: `/etc/resolv.conf` should be in it's final state before executing the container.

**Comment by mcanevet** [comment]
+1

**Comment by haswalt** [comment]
+1 possibly related to: #3714

**Comment by janeczku** [comment]
Can confirm this. Since v0.59.0 or v0.59.1 the resolv.conf is populated with a delay. I have some services that are failing becaus of this since they don't pick up the (correct) nameserver and search keywords on container start.

**Comment by alena1108** [comment]
@janeczku we've put some fixes to this area in Rancher 63 release, could you check if you still see the delay?

**Comment by janeczku** [comment]
@alena1108 Tested with v0.63: Resolv.conf is populated with Rancher NS and search paths before container's entrypoint is executed. :+1:

**Comment by alena1108** [comment]
@janeczku awesome, thanks for testing! Closing the issue for now as verified
