### ISSUE TITLE
RKE2 clusters - Snapshots are not available on the UI for a cluster with cloud provider enabled

### ISSUE THREAD

**Issue by rak-phillip** [rancher/rancher#37052]
**Rancher Server Setup**
- Rancher version: 44013dc
- Installation option: Docker install

**Information about the Cluster**
- Kubernetes version: v1.22.7+rke2r2 
- Cluster Type (Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? Admin/Cluster
   
**Describe the bug**

    Deploy an RKE2 cluster - AWS ec2 node driver with Cloud provider enabled on the cluster
    take snapshots on the cluster
    Navigate to Cluster Management --> cluster details --> Snapshots tab
    No snapshots are listed
    Snapshots are available when I ssh into the etcd node:

/var/lib/rancher/rke2/server/db/snapshots# ls -ltr
total 38268
-rw------- 1 root root 13058080 Mar 23 05:00 etcd-snapshot-<etcd node name>-1648011600
-rw------- 1 root root 13058080 Mar 23 05:06 on-demand-sowmya-cp-pool1-59523e22-blrvg-1648011980
-rw------- 1 root root 13058080 Mar 23 05:32 on-demand-sowmya-cp-pool1-59523e22-blrvg-1648013523

Note:

    On a DO Node driver cluster, the snapshots are available on the UI.
    On an EC2 node driver with no Cloud provider enabled, snapshots are available on the UI.

**To Reproduce**
 
1. Deploy an RKE2 cluster - AWS ec2 node driver with Cloud provider enabled on the cluster
2. take snapshots on the cluster
3. Navigate to Cluster Management --> cluster details --> Snapshots tab

**Result**
* No snapshots are listed

**Expected Result**

* On an EC2 node driver with Cloud provider enabled, snapshots are listed

**Screenshots**

### RKE2 Amazon EC2 With Cloud Provider

![image](https://user-images.githubusercontent.com/835961/160195559-6d48f5de-1905-44e5-ab9e-88967bd20687.png)

### RKE2 Amazon EC2 No Cloud Provider

![image](https://user-images.githubusercontent.com/835961/160195650-e919d118-d4b2-428f-a40a-32f1626ff409.png)

**Additional context**

On the frontend, we get a list of all snapshots via `/v1/rke.cattle.io.etcdsnapshots`, this only returns snapshots for the No Cloud Provider cluster.

rancher/dashboard#5476

**Comment by Oats87** [comment]
Filed https://github.com/k3s-io/k3s/issues/5418 as this is causing our problems

**Comment by Oats87** [comment]
This is currently blocked by https://github.com/k3s-io/k3s/issues/5418

**Comment by Oats87** [comment]
Summary of discovered issue:
K3s/RKE2 create an `%s-etcd-snapshots` configmap in the `kube-system` namespace that is used to store the metadata of snapshots taken by the supervisor processes on the node. Within this configmap, there is a field on each snapshot that is `nodeName`. 

Rancher has a controller called the `snapshotbackpopulate` controller that is responsible for watching the `%s-etcd-snapshots` configmap on the downstream cluster, and will proceed to create corresponding `etcdsnapshots.rke.cattle.io` objects that are what the UI display/what Rancher refers to for taking snapshots.

The `snapshotbackpopulate` controller sets an owner reference on the snapshot objects it creates, depending on the type of snapshot (S3 or local). If the snapshot is an S3 snapshot, the cluster object owns the snapshot, so if the cluster is deleted, the snapshot is properly cleaned up. The second type of owner reference is the machine itself and is used for local snapshots -- the snapshot is owned by the machine. If the machine is deleted, the local snapshots are also deleted.

We use the `nodeName` heavily for local snapshot reconciliation. For example, we use it for the owner reference, but also for the purposes of individual object clean up. The `snapshotbackpopulate` controller will NOT delete `etcdsnapshot` objects, but rather it will update them to set a `missing` field, that the planner will use when it is reconciling the cluster, as the planner delivers a periodic instruction to the various nodes to run an `etcd-snapshot list`. If the snapshot is missing from both the configmap and the actual node, the `etcdsnapshot` object will be deleted from Rancher/the local cluster.

The issue we are running into is that the cloud provider enabled (`aws` in this case) is changing the node name, and RKE2/K3s are remaining "sticky" with the node name they are using to take snapshots. Once the node name is changed in K8s, we no longer have a reference to the node name that was originally set for the node, and cannot create the etcdsnapshot objects as we cannot cleanly provide an owner reference for them.

I'm thinking the best way to work around this issue without K3s/RKE2 changes would be to use the `machine-id` for correlation...

**Comment by Oats87** [comment]
Okay I've been giving this some hard thought.

I think no matter what, we need to change from using `nodeName` for correlation of snapshots to `machine-id`. This should be relatively simple, as we are already retrieving `machine` based on `nodeName`.

What I will do is change behavior of the snapshotbackpopulate controller to be able to also simply backfill `metadata`, and change the `plansecret` controller to create snapshots based on the output of `rke2/k3s etcd-snapshot ls`. `plansecret` will know specifically what node is being worked on, and will only create `etcdsnapshot` objects in the event that they don't already exist for the machine in question.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head a478def
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 EC2 node driver 

----------

### Testing: ###

Tested this issue with the following steps:
1. Deploy an RKE2 cluster - AWS ec2 node driver with Cloud provider enabled on the cluster
2. Take snapshots on the cluster
3. Navigate to Cluster Management --> cluster details --> Snapshots tab

**Result** - Pass

Snapshots are now available on the UI for a cluster with cloud provider enabled
