### ISSUE TITLE
For all "Add" pages, have the cursor start in the first field (most of them it will be Name field)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3706]
Version - Master

Steps to Reproduce: 
1.  Click on any Add button (Add Stack, Add Service, Add container, Add Host)

Results: Cursor is not automatically in first field

Expected: Have cursor be in first field

**Comment by vincent99** [comment]
Added focus to the name field for anything that has {{form-name-description}}, which covers most screens.  If there are specific ones that are still missing let's make a list of them.

**Comment by tfiduccia** [comment]
Version - master 3.20
Not finished
Need to add to the Add API and Add registry

**Comment by vincent99** [comment]
@tfiduccia can you update with what pages (if any) this applies to for 2.o

**Comment by tfiduccia** [comment]
Version - master 9/19
Add pages that need to be fixed:
- [ ] Add Registry
- [ ] Add WebHook Registry

**Comment by tfiduccia** [comment]
Version - master 10/16 2.0
Verified fixed
