### ISSUE TITLE
cattle-node-cleanup job is created in default namespace

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#37061]
Rancher creates `cattle-node-cleanup` job in `default` namespace which maybe be restricted (e.g. by OPA Gatekeeper).
It's requested to create this job in `cattle-system` namespace instead.

SURE-4289

**Comment by timhaneunsoo** [comment]
This issue is reproducible in v2.6.3

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/97477402/160494950-86d9be46-7340-4dba-b526-234655c7169a.png">

**Comment by thedadams** [comment]
After a discussion offline, it seems that this is not possible. We can't assume that the cattle-system namespace is there when we deploy these jobs.
