### ISSUE TITLE
List of Cloning/Upgrade Service change bugs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3707]
Version: Master 2/24

Fields that are not saved:
- [x] Image - Pull image
- [x]  Command - Always/Never restart (policy will not go back to Always once you selected Never)
- [x]  Scheduling - Scheduling does not get removed
- [ ]  ~~Scheduling - Specific host reverts back to first host in list~~
- [x]  Networking - DNS for Host network
- [x]  Networking - Use the container name is not saved and always goes back to Set a specific hostname
- [ ]  ~~Networking - If checked previously RetainIP does not reset to null when you switch out of managed~~
- [x]  Networking - Can't clear requested IP
- [x]  Security/Host - Permissions for Device Binding reverts back to None
- [x]  Healthcheck - Http/1.1 hostheader info not removed when saved as http/1.0

**Comment by vincent99** [comment]
`retainIp` is ignored if `networkMode` != 'managed', so that one doesn't matter

**Comment by vincent99** [comment]
Set a specific hostname with an empty value was confusing, so:

![image](https://cloud.githubusercontent.com/assets/753917/13856850/6e99f5ae-ec34-11e5-860d-b26763acf7c8.png)

**Comment by vincent99** [comment]
Schedule to a specific host is a bug, but in the API.. https://github.com/rancher/rancher/issues/594

**Comment by tfiduccia** [comment]
Version - master 3/17
Verified fixed
