### ISSUE TITLE
[ERROR] error syncing 'cattle-system/helm-operation-zrhhr': handler helm-operation: an error on the server

### ISSUE THREAD

**Issue by liucx1201** [rancher/rancher#37070]
rancher version ：2.5.6  /2.5.11
k8s version：tke v1.18

Import k8s failed

cattle-cluster-agent logs：

`2022/03/28 04:30:08 [INFO] Rancher startup complete
2022/03/28 04:30:08 [INFO] Starting apps/v1, Kind=DaemonSet controller
2022/03/28 04:30:08 [INFO] Starting management.cattle.io/v3, Kind=GlobalDnsProvider controller
2022/03/28 04:30:08 [INFO] Starting management.cattle.io/v3, Kind=EtcdBackup controller
2022/03/28 04:30:08 [INFO] Updating role project-member in p-f752p because of rules difference with roleTemplate Project Member (project-member).
2022/03/28 04:30:08 [INFO] [mgmt-auth-prtb-controller] Updating role project-member in namespace p-f752p
2022/03/28 04:30:08 [INFO] Updating role project-member in p-f752p because of rules difference with roleTemplate Project Member (project-member).
2022/03/28 04:30:08 [INFO] Updating role project-member in p-f752p because of rules difference with roleTemplate Project Member (project-member).
2022/03/28 04:30:08 [INFO] Updating role project-member in p-f752p because of rules difference with roleTemplate Project Member (project-member).
2022/03/28 04:30:08 [INFO] Updating role project-member in p-f752p because of rules difference with roleTemplate Project Member (project-member).
2022/03/28 04:30:08 [INFO] Updating role project-member in p-f752p because of rules difference with roleTemplate Project Member (project-member).
2022/03/28 04:30:08 [INFO] Updating role project-member in p-f752p because of rules difference with roleTemplate Project Member (project-member).
2022/03/28 04:30:08 [INFO] [mgmt-auth-prtb-controller] Updating role project-member in namespace p-84228
2022/03/28 04:30:08 [INFO] Updating role project-member in p-84228 because of rules difference with roleTemplate Project Member (project-member).
2022/03/28 04:30:10 [INFO] driverMetadata: refreshing data from upstream https://releases.rancher.com/kontainer-driver-metadata/release-v2.5/data.json
2022/03/28 04:30:10 [INFO] Retrieve data.json from local path /var/lib/rancher-data/driver-metadata/data.json
2022/03/28 04:30:11 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "rancher-charts-w5fpp-nccph" not found
2022/03/28 04:30:13 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:38956
2022/03/28 04:30:13 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:46472
2022/03/28 04:30:13 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:36956
2022/03/28 04:30:13 [INFO] kontainerdriver googlekubernetesengine stopped
2022/03/28 04:30:13 [INFO] dynamic schema for kontainerdriver googlekubernetesengine updating
2022/03/28 04:30:13 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2022/03/28 04:30:13 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
2022/03/28 04:30:13 [INFO] kontainerdriver azurekubernetesservice stopped
2022/03/28 04:30:13 [INFO] dynamic schema for kontainerdriver azurekubernetesservice updating
2022/03/28 04:30:20 [ERROR] error parsing azure-group-cache-size, skipping update strconv.Atoi: parsing "": invalid syntax
2022/03/28 04:30:21 [INFO] Refreshing driverMetadata in 1440 minutes
2022/03/28 04:30:22 [INFO] driverMetadata: refreshing data from upstream https://releases.rancher.com/kontainer-driver-metadata/release-v2.5/data.json
2022/03/28 04:30:22 [INFO] Retrieve data.json from local path /var/lib/rancher-data/driver-metadata/data.json
2022/03/28 04:30:38 [ERROR] error syncing 'fleet-system/helm-operation-fn7n6': handler helm-operation: an error on the server ("rpc error: code = Unknown desc = container not running (ce2dc750d74e53c2f275f2f04ce43fa9b791904fc0153857dd2cedb1c8279b86)") has prevented the request from succeeding (get pods helm-operation-fn7n6), requeuing
2022/03/28 04:30:39 [ERROR] error syncing 'fleet-system/helm-operation-fn7n6': handler helm-operation: an error on the server ("container not found (\"proxy\")") has prevented the request from succeeding (get pods helm-operation-fn7n6), requeuing
2022/03/28 04:30:39 [ERROR] error syncing 'fleet-system/helm-operation-fn7n6': handler helm-operation: an error on the server ("container not found (\"proxy\")") has prevented the request from succeeding (get pods helm-operation-fn7n6), requeuing
2022/03/28 04:30:39 [ERROR] error syncing 'fleet-system/helm-operation-fn7n6': handler helm-operation: an error on the server ("container not found (\"proxy\")") has prevented the request from succeeding (get pods helm-operation-fn7n6), requeuing
`
I've tried multiple versions and have this problem

Please take a look

**Comment by reesericci** [comment]
I'm having a similar issue. Can someone take a look at this?
