### ISSUE TITLE
Accessing Rancher API using service account's secret (external tool - Azure DevOps Environments)

### ISSUE THREAD

**Issue by NorekZ** [rancher/rancher#37092]
**Is your feature request related to a problem? Please describe.**
Hello,

I'd like to connect our Rancher-managed cluster (RKE1) with Azure DevOps Environments. Only way to do it is by providing service account's secret (docs https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops#add-a-non-aks-kubernetes-resource).

As far as I understand, there are 2 ways to communicate with clusters Rancher-managed clusters:
1) by Rancher proxy using Rancher external url
2) directly (using local IP) as described here: https://rancher.com/docs/rancher/v2.5/en/cluster-admin/cluster-access/ace/

I am able to communicate with the cluster both using kubeconfig and HTTP API, but how to do that using service account's secret that Azure only supports?

I tried to create service account and bindings in my namespace and give the secret to Azure, but it fails with 401 error. I assume that Azure uses token from the secret as a Bearer token while calling HTTP API, which doesn't work for me also. Token from secret is very long whereas "working" token from kubeconfig is short.

**Describe the solution you'd like**
Can someone, please, tell me whether
1) I'm missing something and there is a way to get the desired secret. If so, I suggest to improve the docs.
2) I'm right there is no way to get the secret and it's a desired for Rancher to not provide it
3) it's a feature Rancher maybe implements in next version
4) I should create an issue on the Azure side and suggest supporting of e.g. kubectl configs

Thank you!

**Comment by junkiebev** [comment]
Can confirm - it's annoying.

My workaround was to save the connection with Bad values, and then edit the service connection in "Service Connections" to switch it from Service Account to Kubeconfig.

**Comment by artm** [comment]
> My workaround was to save the connection with Bad values, and then edit the service connection in "Service Connections" to switch it from Service Account to Kubeconfig.

The only fields of the secret that Azure DevOps expects are `data.token` and `data.ca\.crt`. The latter doesn't need to contain a valid CA certificate if rancher endpoint has a valid certificate signed by the well-known authority. In that case the following minimal JSON kan be used (replace the token with the result of the command): 

```json
{
    "data": {
        "ca.crt": "-",
        "token": "$(kubectl config view --minify -o 'jsonpath={.users[0].user.token}' --raw | base64 -w 0)"
    }
}
```
