### ISSUE TITLE
INSTALLATION FAILED: chart requires kubeVersion: < 1.23.0-0 which is incompatible with Kubernetes v1.23.1

### ISSUE THREAD

**Issue by iceofsea** [rancher/rancher#37110]
**Rancher Server Setup**
- Rancher version:  rancher-latest
- Installation option (Docker install/Helm Chart):
   -Helm 3.8.1 
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.23.1 
- 
[root@k8s-master01 ~]# helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
"rancher-latest" already exists with the same configuration, skipping
[root@k8s-master01 ~]# helm install rancher rancher-latest/rancher \
>   --namespace cattle-system \
>   --set hostname=rancher.my.org

Error: INSTALLATION FAILED: chart requires kubeVersion: < 1.23.0-0 which is incompatible with Kubernetes v1.23.1

**Comment by sowmyav27** [comment]
k8s 1.23 is being introduced and is experimental only in rancher:v2.6.4+. And 2.6.4 has not released yet.
