### ISSUE TITLE
How do autoscaling work in rancher os

### ISSUE THREAD

**Issue by mwaaas** [rancher/rancher#3711]
Rancher Version:  rancher/server:latest

Docker Version: 1.10

OS: Ubuntu

Steps to Reproduce: 

Results: 

Expected:

**Comment by deniseschannon** [comment]
This is the rancher repository and not RancherOS.

Can you file a bug in rancher/os and give more clarity on what you're trying to do? What are you trying to autoscale?

**Comment by deniseschannon** [comment]
Closing for now. Please open a new issue in Rancher/os if you have a specific question about RancherOS.
