### ISSUE TITLE
Monitoring installation fails on rke2 clusters

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#37122]
**Rancher Server Setup**
- Rancher version: `v2.6.3`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Local as RKE1 `v1.22.6`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.21.10+rke2r2`
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
AWS Node driver rke2, Custom rke2, and imported rke2 with `v1.21.10+rke2r2`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
standard user as `Cluster Owner`

   
**Describe the bug**
Installation of monitoring fails on rke2 clusters

**To Reproduce**
1. Fresh install of rancher
2. As admin, create a standard user
3. As admin, enable monitoring on local
4. As standard user, provision rke2 cluster (Node driver, Custom, or Imported)
5. As standard user, enable monitoring on rke2 cluster
6. Reproduced

**Result**
Installation of monitoring fails with the following error:
`Error: podsecuritypolicies.policy "pushprox-kube-etcd-client" already exists`

**Expected Result**
Monitoring should be successfully installed and enabled

**Screenshots**

`AWS Node driver rke2`
<img width="1583" alt="Screen Shot 2022-03-30 at 11 12 10 AM" src="https://user-images.githubusercontent.com/46494969/160903043-85cd8c73-3118-4409-a06c-6b14577a43d1.png">

`Custom rke2`
<img width="1580" alt="Screen Shot 2022-03-30 at 11 14 08 AM" src="https://user-images.githubusercontent.com/46494969/160903473-7fa363a4-f9e5-40d2-8ce5-c4bfdfd75551.png">

`Imported rke2`
<img width="1580" alt="Screen Shot 2022-03-30 at 12 57 54 PM" src="https://user-images.githubusercontent.com/46494969/160920380-28ef18ff-5f99-43b3-b415-9db40c9020dd.png">

**Comment by ronhorton** [comment]
**PASS** Verified monitoring version `100.1.1+up19.0.3` rancher `2.6.4-rc14`

1. I first replicated on downstream rke2 cluster
2. upgraded monitoring fixed the install error and allowed install
3. clean install on rke2 cluster
4. configured monitoring to send alerts and received expected alert
5. regression tested rke1 downstream cluster and rec'd expected alert
