### ISSUE TITLE
CIS scans do not work with RKE2 recommended tolerations

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#37129]
**Issue description:**
The recommendation for RKE2 deployments (found here: https://docs.rke2.io/install/ha/#2a-optional-consider-server-node-taints) is to taint Server nodes with CriticalAddonsOnly=true:NoExecute. As a result, the CIS Operator appears to not properly scan server nodes. (https://github.com/rancher/cis-operator/issues/102)

**Business impact:**
Not able to perform CIS scans in RKE2 cluster

**Troubleshooting steps:**
N/A

**Repro steps:**

    Provision a Rancher v2.6.2 instance
    Provision an RKE2 v1.21.5+rke2r2 clusters, with one server node, and one worker node, and profile: cis-1.6, adding CriticalAddonsOnly=true:NoExecute to the server node
    Import RKE2 cluster to Rancher and install rancher-cis-benchmark 2.0.1 chart
    Run a scan with the rke2-cis-1.6-profile-hardened profile and observe failure to run tests on server nodes
    Remove CriticalAddonsOnly=true:NoExecute taint from server nodes, re-run scan and observe tests run on server nodes

**Workaround:**
Is workaround available and implemented? Kind of
What is the workaround: Requires removing taint from server nodes to run CIS scan, and then re-adding after

**Actual behavior:**
CIS Scans works with tainted RKE2 server nodes

**Expected behavior:**
CIS Scans do not work with tainted RKE2 server nodes

**Files, logs, traces:**
N/A

**Additional notes:**
N/A

There is already a PR tested by support here: https://github.com/rancher/cis-operator/pull/101/files

**Comment by MKlimuszka** [comment]
@samkulkarni20 , there is already an open PR to solve this, so it should be quick to get into 2.6.5

**Comment by dhruvmewada15** [comment]
Steps to Validate:

Rancher Server: rancher:v2.6.4-rc12
Cluster: Downstream RKE2 v1.23.5+rke2r1 cluster (1 server + 1 agent node) on SLE15-SP2.s390x

1. Set the taint on the master node: kubectl taint node my-rke2-master-node CriticalAddonsOnly=true:NoExecute
2. Deploy `rancher-cis-benchmark:2.0.3-rc2` App a Scan using r`ke2-cis-1.6-profile-permissive` profile. Observe the scan. It should fail because of the taint.
3. Then update the cis-operator image `rancher/cis-operator:v1.0.8-rc1` in rancher-cis-benchmark chart to apply the patch from the [PR](https://github.com/rancher/cis-operator/pull/101).
4. Run the scan again and observe the results. Scan should PASS now.

**Comment by bennysp** [comment]
Rancher: v2.64
RKE: v1.22.8+rke2r1 
CIS Benchmark: v.2.0.3 (updated chart to `rancher/cis-operator:v1.0.8-rc1` image

Re-ran and same failed results too.

**Comment by bennysp** [comment]
Thanks @dhruvmewada15 . I just went into the installed app and updated the operator to v1.0.8-rc2 and it passed now.

![image](https://user-images.githubusercontent.com/4121872/162853939-3f949dba-70c8-4e50-8213-1cc6929a6e1d.png)

However, why is it issuing warning still? ([Example](https://docs.rke2.io/security/cis_self_assessment16/#1120))
![image](https://user-images.githubusercontent.com/4121872/162854242-28032b45-84d9-4be8-abb1-13dd51077a11.png)

![image](https://user-images.githubusercontent.com/4121872/162854518-f1428dd7-6330-419d-825d-63817ffb66eb.png)

Maybe a separate issue?

**Comment by bennysp** [comment]
Disregard, I see the document was for 1.20 of RKE2.

**Comment by rishabhmsra** [comment]
Validated again on rancher v2.6-head(cd0555b) and the scans are passing with `rancher/cis-operator:v1.0.8-rc2`

Steps followed:
- Created a node driver RKE2 v1.23.5+rke2r1 cluster (1-node-cp,etcd and 1-node-worker) on SLES-15-SP2
- Applied taint : CriticalAddonsOnly=true:NoExecute on master node
- Deployed `rancher-cis-benchmark:2.0.3` and ran the scan using `rke2-cis-1.6-profile-permissive profile`. It has some failures.
- Updated the CIS Benchmark chart with `rancher/cis-operator:v1.0.8-rc2` and ran the scan again. It passed successfully.

Results:
- Scans are passing after updating the cis-operator image, hence closing the issue.

![scan-passed](https://user-images.githubusercontent.com/36376154/162949194-9f275a7f-5970-4e5e-901d-fbe2410b18a6.png)
