### ISSUE TITLE
RKE2 Provisioning - `[ERROR] init node not found` on cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#37133]
**Rancher Server Setup**
- Rancher version: 2.6.4-rc17
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.22.7+rke2r2`
- Cluster Type (Local/Downstream): Downstream Node driver - DO 1 node all roles, 1 worker node

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) - Admin

   
**Describe the bug**
RKE2 Provisioning - `[ERROR] init node not found` on cluster

**To Reproduce**

- Deploy an RKE2 cluster
- The cluster is in error state since the droplet count in DO was hit
- Go to cluster details page from Cluster Management --> Machine Pools --> Select both the nodes and click on Delete
- The nodes go into Deleting state and the cluster is in an error state
- New nodes take a while to get created. Once the new nodes are created and the machines are in Povisioning state the clusterr goes to Provisioning state

**Result**
Provisioning log:
```


11:00:58 am | [INFO ] waiting for at least one bootstrap node
-- | --
11:01:00 am | [INFO ] provisioning bootstrap node(s) rke2-sowmya-69b6f9488f-zfngj: waiting for agent to check in and apply initial plan
11:01:02 am | [INFO ] provisioning bootstrap node(s) rke2-sowmya-69b6f9488f-zfngj: creating server (DigitaloceanMachine) in infrastructure provider, waiting for agent to check in and apply initial plan
11:01:24 am | [INFO ] provisioning bootstrap node(s) rke2-sowmya-69b6f9488f-zfngj: failed creating server (DigitaloceanMachine) in infrastructure provider: CreateError: Trying to access option which does not exist
  | THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
  | Type assertion did not go smoothly to string for key
  | Running pre-create checks...
  | Creating machine...
  | (rke2-sowmya-2b2e6e38-cxrdd) Creating SSH key...
  | (rke2-sowmya-2b2e6e38-cxrdd) Creating Digital Ocean droplet...
  | Error creating machine: Error in driver during machine creation: POST https://api.digitalocean.com/v2/droplets: 422 creating this/these droplet(s) will exceed your droplet limit
  | The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag., waiting for agent to check in and apply initial plan
11:04:40 am | [ERROR] init node not found

```

**Expected Result:**

- nodes should get created first 
- This error should not be seen on the cluster when nodes are deleted

**Comment by Sahota1225** [comment]
As per the above comment, this is the expected behavior.
