### ISSUE TITLE
bitnami Update failed in Catalogs

### ISSUE THREAD

**Issue by kamilaiduo** [rancher/rancher#37136]
**Rancher Server Setup**
- Rancher version:v2.5.8
- Installation option (Docker install/Helm Chart):EKS
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

   
**Describe the bug**

bitnami    
Update failed: fatal: not a git repository (or any parent up to mount point /var/lib) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). : exit status 128
--

</body>
</html>
**To Reproduce**
 

**Result**

**Expected Result**

**Screenshots**
![image](https://user-images.githubusercontent.com/64783043/161000340-3a164e48-7708-45f3-88db-b867056f5fe1.png)

**Additional context**

**Comment by kamilaiduo** [comment]
It was good before, but suddenly it's like this today

**Comment by junkiebev** [comment]
Happening for me as well on 2.5.12

**Comment by kamilaiduo** [comment]
Applications using bitnami cannot be upgraded and deployed

**Comment by kamilaiduo** [comment]
![image](https://user-images.githubusercontent.com/64783043/161208441-d44288ca-1058-4e68-8957-9970b36eb90c.png)
new error

**Comment by abhi1693** [comment]
Bitnami has been making several changes to their `index.yaml` recently. 

Try changing the URL to `https://raw.githubusercontent.com/bitnami/charts/index/bitnami`

Then manually invoke `refresh` if needed.

**Comment by Rincewind78** [comment]
> Bitnami has been making several changes to their `index.yaml` recently.
> 
> Try changing the URL to `https://raw.githubusercontent.com/bitnami/charts/index/bitnami`
> 
> Then manually invoke `refresh` if needed.

@abhi1693 Thank you very much! Changing to this address solved it for me. Catalog in Rancher is now working again :-)

**Comment by lucathecreator** [comment]
Is this the permanent solution? 

I checked with Rancher 2.6 and it works fine with the following URL 
https://charts.bitnami.com/bitnami

Is there a different method used in 2.5 than in 2.6?

**Comment by ArgonV** [comment]
I started seeing this problem last week as well with Rancher v2.4 - v2.5. I was leaving comments here: https://github.com/bitnami/charts/issues/8433

**Comment by abhi1693** [comment]
@lucathecreator Not a permanent solution at all. But something is better than nothing, right?

**Comment by rjbaat** [comment]
I have the same problem, trying to upgrade a bitnami mariadb chart. The url: https://charts.bitnami.com/bitnami wasn't working and giving me the error above. Then tried to change the url to the suggested: `https://raw.githubusercontent.com/bitnami/charts/index/bitnami` but I didn't get it to work. I tried the url: `https://github.com/bitnami/charts` and the repo did refresh, I also was able to upgrade via the legacy app page. 

But then I run into the error and it doesn't install: 

```
Wait helm template failed. Error: An error occurred while checking for chart dependencies. You may need to run helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: common : exit status 1
```
Not sure how to proceed. I do see in the chart.yaml the dependency is: 

```
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
```
So then iam back to the need to get the url: `https://charts.bitnami.com/bitnami` working I suppose?

**Comment by robinjoerke** [comment]
> I have the same problem, trying to upgrade a bitnami mariadb chart. The url: https://charts.bitnami.com/bitnami wasn't working and giving me the error:
> 
> ```
> Update failed: fatal: not a git repository (or any parent up to mount point /var/lib) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). : exit status 128
> ```
> 
> Then tried to change the url to the suggested: `https://raw.githubusercontent.com/bitnami/charts/index/bitnami` but I didn't get it to work. I tried the url: `https://github.com/bitnami/charts` and the repo did refresh, I also was able to upgrade via the legacy app page.
> 
> But then I run into the error and it doesn't install:
> 
> ```
> Wait helm template failed. Error: An error occurred while checking for chart dependencies. You may need to run helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: common : exit status 1
> ```
> 
> Not sure how to proceed. I do see in the chart.yaml the dependency is:
> 
> ```
> dependencies:
>   - name: common
>     repository: https://charts.bitnami.com/bitnami
>     tags:
>       - bitnami-common
>     version: 1.x.x
> ```
> 
> So then iam back to the need to get the url: `https://charts.bitnami.com/bitnami` working I suppose?

exact same issue here. did you find a way to solve this?

**Comment by ArgonV** [comment]
For me, I kept the Helm charts I had deployed in the cluster. Then I deleted the Bitnami catalog, and re-added it, being sure to set it to Helm3 and using the URL https://raw.githubusercontent.com/bitnami/charts/index/bitnami

After that, my charts worked again and I could deploy new ones or upgrade existing ones.

**Comment by rjbaat** [comment]
Thnx i will try this. You didnt have the common dependency errors that are using the fixed  https://charts.bitnami.com/bitnami url? Or maybe you have used a chart that doesnt have this dependency?

**Comment by abhi1693** [comment]
@rjbaat All charts in bitnami uses `common` as a dependency.
