### ISSUE TITLE
Fleet: imported cluster in wait check-in after rotating CA and certs.

### ISSUE THREAD

**Issue by mjordan79** [rancher/rancher#37131]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Rancher has been installed through Helm. 
   -RKE k8s cluster: v1.22.7-rancher1-1, rke 1.3.8. The imported kubernetes cluster has version 1.23.5 instead.
- Proxy/Cert Details: Rancher has been installed using the command:
helm repo add rancher-stable https://releases.rancher.com/server-charts/stable && \
	helm install rancher rancher-stable/rancher \
  	--namespace cattle-system \
  	--set hostname=myhost.mydomain.it \
  	--set bootstrapPassword=admin \
  	--set ingress.tls.source=secret \
  	--set privateCA=false

Certificates have been provided prior to the installation with:
kubectl create namespace cattle-system && \
	kubectl -n cattle-system create secret tls tls-rancher-ingress \
	--cert=certs/tls.crt \
	--key=certs/tls.key

No CA specified, just my own certificates.

**Information about the Cluster**
- Kubernetes version: 1.23.5
- Cluster Type (Local/Downstream): Downstream
   Imported running kubectl apply onto an existing k8s cluster 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): using the admin user.

**Describe the bug**
After having rotated the certs and the CA with the command rke cert rotate --rotate-ca the fleet cluster remains in Wait Check-In status. The command:
kubectl logs pod/fleet-agent-78f694664b-pckgs -n cattle-fleet-local-system

shows the following error log:
time="2022-03-30T23:14:46Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-local-system/fleet-agent-bootstrap or cattle-fleet-local-system/fleet-agent: looking up secret cattle-fleet-local-system/fleet-agent-bootstrap: secrets \"fleet-agent-bootstrap\" not found"
time="2022-03-30T23:15:46Z" level=error msg="Current credential failed, failing back to reregistering: Get \"https://10.43.0.1:443/apis/fleet.cattle.io/v1alpha1/namespaces/cluster-fleet-local-local-1a3d67d0a899/bundledeployments\": x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kube-ca\")"

**To Reproduce**
With an imported cluster, just rotate certificates and the CA using rke cert rotate --rotate-ca

**Expected Result**
The fleet cluster correctly working

**Screenshots**
![immagine](https://user-images.githubusercontent.com/9471455/160953669-9a24b1a0-2201-4b8c-bb70-f0704b7c0b0b.png)

**Comment by alirezav2020** [comment]
Have you find a solution for this issue?

**Comment by alirezav2020** [comment]
> **Rancher Server Setup**
> 
> * Rancher version: 2.6.3
> * Installation option (Docker install/Helm Chart): Rancher has been installed through Helm.
>   -RKE k8s cluster: v1.22.7-rancher1-1, rke 1.3.8. The imported kubernetes cluster has version 1.23.5 instead.
> * Proxy/Cert Details: Rancher has been installed using the command:
>   helm repo add rancher-stable https://releases.rancher.com/server-charts/stable && 
>   helm install rancher rancher-stable/rancher 
>   --namespace cattle-system 
>   --set hostname=myhost.mydomain.it 
>   --set bootstrapPassword=admin 
>   --set ingress.tls.source=secret 
>   --set privateCA=false
> 
> Certificates have been provided prior to the installation with: kubectl create namespace cattle-system && kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=certs/tls.crt --key=certs/tls.key
> 
> No CA specified, just my own certificates.
> 
> **Information about the Cluster**
> 
> * Kubernetes version: 1.23.5
> * Cluster Type (Local/Downstream): Downstream
>   Imported running kubectl apply onto an existing k8s cluster
> 
> **User Information**
> 
> * What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): using the admin user.
> 
> **Describe the bug** After having rotated the certs and the CA with the command rke cert rotate --rotate-ca the fleet cluster remains in Wait Check-In status. The command: kubectl logs pod/fleet-agent-78f694664b-pckgs -n cattle-fleet-local-system
> 
> shows the following error log: time="2022-03-30T23:14:46Z" level=error msg="Failed to register agent: looking up secret cattle-fleet-local-system/fleet-agent-bootstrap or cattle-fleet-local-system/fleet-agent: looking up secret cattle-fleet-local-system/fleet-agent-bootstrap: secrets "fleet-agent-bootstrap" not found" time="2022-03-30T23:15:46Z" level=error msg="Current credential failed, failing back to reregistering: Get "[https://10.43.0.1:443/apis/fleet.cattle.io/v1alpha1/namespaces/cluster-fleet-local-local-1a3d67d0a899/bundledeployments\](https://10.43.0.1:443/apis/fleet.cattle.io/v1alpha1/namespaces/cluster-fleet-local-local-1a3d67d0a899/bundledeployments%5C)": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-ca")"
> 
> **To Reproduce** With an imported cluster, just rotate certificates and the CA using rke cert rotate --rotate-ca
> 
> **Expected Result** The fleet cluster correctly working
> 
> **Screenshots** ![immagine](https://user-images.githubusercontent.com/9471455/160953669-9a24b1a0-2201-4b8c-bb70-f0704b7c0b0b.png)

Have you find a solution for this issue?
