### ISSUE TITLE
Add a button to download rancher-compose.yml for a stack

### ISSUE THREAD

**Issue by atrauzzi** [rancher/rancher#3713]
Would be useful if I could configure my services in the GUI and then download them as as file to maintain/reuse/automate.

**Comment by deniseschannon** [comment]
This already exists today. You can use the "Export Config" option in the Stack dropdown. It provides the docker-compose.yml and rancher-compose.yml.

<img width="190" alt="screen shot 2016-02-28 at 10 03 33 pm" src="https://cloud.githubusercontent.com/assets/11410997/13387008/6bb72454-de67-11e5-8ba8-91aadc3f464b.png">

**Comment by atrauzzi** [comment]
Awesome!!  Still learning the UI and I'm sure you guys will document more later.  Thank you :)
