### ISSUE TITLE
vSphere CPI Chart: Add Dualstack support

### ISSUE THREAD

**Issue by phillipsj** [rancher/rancher#37154]
**Is your feature request related to a problem? Please describe.**

Upstream vSphere CSI has just added docs for guidance and how to enable dual stack support for the cloud provider.

* https://github.com/kubernetes/cloud-provider-vsphere/pull/595

**Describe the solution you'd like**

Expose this functionality in future chart versions.

**Comment by snasovich** [comment]
There is not much activity/context left here, so closing this issue. If such a need arises in future, this issue can be reopened.
