### ISSUE TITLE
Calico doesn't start

### ISSUE THREAD

**Issue by caatclaudia** [rancher/rancher#37151]
### Rancher Server Setup
Rancher version: v.2.6.3

### Information about the Cluster
Installation option:
- Helm version: v3.8.0
- k3s version: v1.22.6+k3s1

Openstack:
- Microstack Installation - version ussuri, Revision 245

### Describe the bug
I created an RKE2 Cluster with Calico in two machines (the first one has the three roles - etcd, control plane, and worker- and the second one is just a worker. These machines are in the same network and it works okay.
The ports that are open in Master Node are the followings:
![image](https://user-images.githubusercontent.com/56655085/161252828-b8810e8d-a289-4cff-86c2-9c7f0b77d4a9.png)
![image](https://user-images.githubusercontent.com/56655085/161252908-295c7119-2399-460d-97ef-576c7765d69b.png)

Then, I am trying to create a new node worker inside of OpenStack, to do that I create an instance with Debian 11, and paste the registration command to the machine.
To do that in the first two machines I create a route to the external and internal networks of OpenStack. Also, I am using network rules to allow all traffic that comes from outside and that goes outside.

### Result
In Rancher Interface, the `Provisioning Log` shows the message:
![image](https://user-images.githubusercontent.com/56655085/161253048-ad3b5738-3a6c-4786-93db-28fafd37748e.png)

Pods that are running (trying) in new node:
![image](https://user-images.githubusercontent.com/56655085/161253386-96edae4e-f595-459c-a8a1-b9698ea4f83d.png)

The `logs` from the pods:
![image](https://user-images.githubusercontent.com/56655085/161253508-7f14e7ce-9efe-4381-81fb-d66a3d47854c.png)

The `describe` pod:
![image](https://user-images.githubusercontent.com/56655085/161253578-d8b48a4b-4f0c-4918-a493-ab239d8d2774.png)

The logs of rke2-agent:
![image](https://user-images.githubusercontent.com/56655085/161253759-b5fbe473-b8fc-4627-a0bd-fdf27e3ea98d.png)

### Expected Result
In Rancher Interface, the "State" of the Cluster should become "Active"

### To Reproduce
Create a Cluster with the configuration mentioned.

**Comment by caatclaudia** [comment]
> Your first server and worker nodes are not running inside openstack but the additional worker is based on an OpenStack VM?

Yes, exactly. My first two nodes are not OpenStack instances and worked fine, when I try to add a new node (OpenStack instance) the problems appear. I already tried to run a Cluster in OpenStack only but I stuck in this issue too: https://github.com/rancher/rancher/issues/37075#issue-1183487517

**Comment by manuelbuil** [comment]
Did you open all required ports to run Calico? I wonder if the neutron network policies are blocking the communication

**Comment by caatclaudia** [comment]
> Did you open all required ports to run Calico? I wonder if the neutron network policies are blocking the communication

Yes, in Master node I allow all traffic, and in my new instance (Openstack instance), at the moment I have the following rules: ![image](https://user-images.githubusercontent.com/56655085/161985310-19c276e9-e57d-4ed0-957a-46aeb1be95af.png)

**Comment by manuelbuil** [comment]
What is the output you get when running `kubectl get nodes -o wide`?

According to your logs, the agent is unable to connect to the server `172.16.16.154:9345`. That's the first thing you should investigate. Could you try running `nc -zv 172.16.16.154 9345` from the Debian VM running on OpenStack?

**Comment by manuelbuil** [comment]
If nodes are running, you should not see the log in the agent not being able to connect to `172.16.16.154:9345`. Can you please verify?

**Comment by caatclaudia** [comment]
> If nodes are running, you should not see the log in the agent not being able to connect to `172.16.16.154:9345`. Can you please verify?

I installed `netcat` and used the command that you have mentioned and  this is the output:
![image](https://user-images.githubusercontent.com/56655085/162158111-428fe787-2c98-4331-9f5a-37f05f2d720d.png)

The node alternate in "Ready" and "NotReady" state, depending on this restarts, which means that when the pods  are Running (the only one that does not turn "Running" is the calico one) the node is "Ready" when the pods restart, the node becomes "NotReady"
![image](https://user-images.githubusercontent.com/56655085/162158455-514bd578-9327-4f9f-8aa5-910c7ecbe0c9.png)

When I see the logs from the calico pod this is the output:
![image](https://user-images.githubusercontent.com/56655085/162159016-93570b89-991f-42a6-972f-d8921a652efb.png)

In the Worker node, the 10250 port is open but the connection to 53726 is denied
![image](https://user-images.githubusercontent.com/56655085/162159289-56cf5feb-fd55-4068-9e47-743fad924a88.png)

**Comment by manuelbuil** [comment]
> 

So the node alternates between Ready and Not-ready state and when it is not-ready, you see in the logs that it can't reach `172.16.16.154:9345`?

**Comment by caatclaudia** [comment]
> So the node alternates between Ready and Not-ready state and when it is not-ready, you see in the logs that it can't reach `172.16.16.154:9345`?

Yes. When is in a Ready state, the rke2-agent is fine and does not show any logs.

**Comment by manuelbuil** [comment]
> > So the node alternates between Ready and Not-ready state and when it is not-ready, you see in the logs that it can't reach `172.16.16.154:9345`?
> 
> Yes. When is in a Ready state, the rke2-agent is fine and does not show any logs.

So, from time to time, something in your networking connection between nodes breaks. And then your openstack node is unable to communicate with the server on port 9345? That's when you see the logs, right? Have you tried other type of traffic? For example pinging between nodes? Does it fail also intermittently?

**Comment by manuelbuil** [comment]
> > > > So the node alternates between Ready and Not-ready state and when it is not-ready, you see in the logs that it can't reach `172.16.16.154:9345`?
> > > 
> > > 
> > > Yes. When is in a Ready state, the rke2-agent is fine and does not show any logs.
> > 
> > 
> > So, from time to time, something in your networking connection between nodes breaks. And then your openstack node is unable to communicate with the server on port 9345? That's when you see the logs, right? Have you tried other type of traffic? For example pinging between nodes? Does it fail also intermittently?
> 
> Yes, I already tried pinging between nodes but the connection is always okay! The only thing that I see that can cause this is the pods (that I already mentioned) are always restarting and don't keep running, but I don't understand why this happen

Let's focus on another problem which is fishy. You can't see the logs of your pods because the server can't access $openstack_node:10250. From the server, can you try: `nc -zv 192.168.222.26 10250`? Please check several times to verify if it is also failing intermittently

**Comment by caatclaudia** [comment]
When the Node is in the state not Ready, the connection is refused:
![image](https://user-images.githubusercontent.com/56655085/162611584-c55ebf6f-7f65-489d-8236-a807f1c8d997.png)

But in Worker node when I see the ports that are open, the port is okay:
![image](https://user-images.githubusercontent.com/56655085/162611568-716e4221-d30a-41c5-979b-0e935b16bacd.png)

**Comment by manuelbuil** [comment]
When the port is ready, does netcat work?

**Comment by renatogalera** [comment]
calico depends on (https://github.com/kubernetes/cloud-provider-openstack)

You have checked if the openstack cloud controller services are up?

**Comment by caatclaudia** [comment]
> calico depends on (https://github.com/kubernetes/cloud-provider-openstack)
> 
> You have checked if the openstack cloud controller services are up?

I'm sorry but could you be more clear? The repository that you mention is necessary for what? I do not see any documentation mentioning this in Rancher documentation. I'm starting to use this tool so I don't have a lot of knowledge.

Yes, my Openstack is running and it's okay.
