### ISSUE TITLE
Wrong Name of Prometheus -- written as Promethies

### ISSUE THREAD

**Issue by busyboy77** [rancher/rancher#37167]
**Rancher Server Setup**
- Rancher version:
rancher version v2.6.3 
- Installation option (Docker install/Helm Chart):
  Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
  v1.23.5
- Cluster Type (Local/Downstream):
 Local based on KVM based VMs

   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**

- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
   Admin

   
**Describe the bug**
The name is written as Promethies whereas it should be Prometheus.

**To Reproduce**
Install Monitoring in Rancher v2.6.3  and then goto Monitoring --> Advanced --> Promethies ( both in Menu and on the right panel)

**Result**
See above
**Expected Result**
It should be Promethues

**Screenshots**
![image](https://user-images.githubusercontent.com/19593617/161385085-090f9951-9ceb-4e29-ab6d-bfce6962bc81.png)

**Additional context**
Learning the Rancher and discovering problems

**Comment by David-VTUK** [comment]
https://prometheus.io/docs/introduction/faq/#what-is-the-plural-of-prometheus

**Comment by busyboy77** [comment]
I wont recommend to confuse people using this service with singularity or plurality .. Prometheus would still be a beautiful representation for all cases.
