### ISSUE TITLE
Change k8s default to v1.21 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#37162]
There's an [upstream issue with etcd 3.5.0-3.5.2](https://groups.google.com/a/kubernetes.io/g/dev/c/B7gJs88XtQc/m/rSgNOzV2BwAJ), tracked in rancher here: https://github.com/rancher/rancher/issues/37157. 

k8s v1.22 uses v3.5.0 and v1.22 was set as our default version for Rancher v2.6.4 and RKE v1.3.8, so we want to change the default back to v1.21. This will show 1.22 as experimental in Rancher when creating new clusters and let users know it's not recommended for production. 

**Rancher local cluster - Docker Install** 
--- 
We cannot change local embedded k3s version used for docker installs without releasing a new rancher version. Requires change in our code and building a new tag. (For example, https://github.com/rancher/rancher/pull/37013) 

**Rancher local cluster - HA**
--- 
Update Rancher v2.6.4 release notes to reflect upstream recommendations, suggesting not to use v1.22 as local cluster. 

**RKE1 standalone** 
--- 
Existing clusters provisioned using RKE <= v1.3.8 and k8s v1.22.x will need to add `kubernetes_version` in cluster.yml before running `rke up` with RKE v1.3.9. This ensures provisioned clusters don't auto-downgrade. New clusters created with RKE v1.3.9 will be created with k8s v1.21.x by default. 

**Rancher provisioned RKE1/RKE2/k3s**
--- 
Existing clusters running v1.22.x won't downgrade, latest v1.22.x will show up as experimental in Edit Cluster if a newer version is available (until a fixed version is released). When creating new clusters, latest available v1.22.x will show as experimental.

**Comment by rosskirkpat** [comment]
There's an update on the upstream issue, which I summarized [here](https://github.com/rancher/rancher/issues/37157#issuecomment-1091978796)

**Comment by snasovich** [comment]
This is no longer releavant
