### ISSUE TITLE
Install nfs-common and cifs-utils on provisioned machines

### ISSUE THREAD

**Issue by KornKalle** [rancher/rancher#37188]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am deploying machines through Cloud Providers (e.g. Digitalocean / Linode), that there are certain packages missing, which leads to manual interaction on the machines itself.

I found the packages nfs-common (needed for NFS mounts) and cifs-utils (needed for Longhorn CSI) missing on debian based distributions

**Describe the solution you'd like**
Install nfs-common and cifs-utils during provisioning.

**Describe alternatives you've considered**
Manually creating a cluster and importing it, then I would not need rancher anymore.

**Comment by junkiebev** [comment]
We use `cloud-init` to install required packages.

```cloud-config
#cloud-config
# packages may be supplied as a single package name or as a list
# with the format [<package>, <version>] wherein the specific
# package version will be installed.
packages:
 - cifs-utils
```
