### ISSUE TITLE
v2prov does not correct itself if config is changed before cluster is provisioned/available

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#37190]
**Rancher Server Setup**
- Rancher version: v2.6.4
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

When using v2prov, if the configuration of the cluster is incorrect and the cluster never fully becomes available, it will not become available even if the configuration is corrected, as the planner doesn't fix the incorrect configuration. More investigation into this is necessary as I am not exactly sure where the planner is getting stuck at this point.

**Comment by Oats87** [comment]
(and once the node was finished with its probes, it got stuck waiting for uncordon, so I just 
```
kubectl annotate secret -n fleet-default timcis15-bootstrap-template-qfgbt-machine-plan rke.cattle.io/uncordon-
```
)

**Comment by Oats87** [comment]
this issue was discovered while debugging https://github.com/rancher/rancher/issues/36565

**Comment by Oats87** [comment]
Similar to https://github.com/rancher/rancher/issues/36822#issuecomment-1102988563, 

How to test this:

Provision a v2prov cluster with a garbage version of RKE2 i.e. `v1.21.6+rke2r5`
Observe that the machines will go into an error state and tell you to check the rancher-system-agent.service logs on the node.
Fix the version of RKE2 to something sane, and note that the cluster will provision

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head b8cbc1a
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver cluster

----------

### Testing: ###

Tested this issue with the following steps:
1. Provision a v2prov cluster.
2. Edit your cluster as YAML, and set the version of the cluster to some ridiculous version that doesn't exist. for example, v1.21.6+rke2r5
3. Observe that the machines will go into an error state and tell you to check the rancher-system-agent.service logs on the node.
4. Set the version back to the original version, and observe that the errors go away

**Result** - Pass

After changing the version back to the original version, the errors went away and cluster was provisioned successfully
