### ISSUE TITLE
[v2.6] RKE2 and K3S - KDM Update for K8s April patch release

### ISSUE THREAD

**Issue by katran001** [rancher/rancher#37191]
# KDM Updates

TO BE RELEASED: Rancher OOB v2.6

| New Kubernetes Version  | Min Rancher Version | Default Version |
|                  :---:                  |              :---:               |          :---:          |
| v1.21.12+rke2r1                 | v2.6.3-alpha1             |                           |
| v1.22.9+rke2r1                  | v2.6.3-alpha1             | x                        |
| v1.23.6+rke2r1                  | v2.6.4-alpha1             |                           |
| v1.21.12+k3s1                   | v2.6.3-alpha1             |                           |
| v1.22.9+k3s1                    | v2.6.3-alpha1             | x                        |
| v1.23.6+k3s1                    | v2.6.4-alpha1             |                           |

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |
| rke2-cilium | 1.11.203 | v1.21.12+rke2r1, v1.22.9+rke2r1, v1.23.6+rke2r1 |
| rancher-vsphere-cpi | 1.2.101 | v1.21.12+rke2r1, v1.22.9+rke2r1, v1.23.6+rke2r1 |
| rancher-vsphere-csi | 2.5.1-rancher101 | v1.21.12+rke2r1, v1.22.9+rke2r1, v1.23.6+rke2r1 |
| harvester-cloud-provider | 0.1.1100 | v1.21.12+rke2r1, v1.22.9+rke2r1, v1.23.6+rke2r1 |
| harvester-csi-driver | 0.1.1100 | v1.21.12+rke2r1, v1.22.9+rke2r1, v1.23.6+rke2r1 |

# Argument Changelog

- TBD - This will generally will be empty as arguments are changed infrequently.

**Comment by rancher-max** [comment]
RKE2 KDM PR: https://github.com/rancher/kontainer-driver-metadata/pull/885

**Comment by rancher-max** [comment]
K3S KDM PR: https://github.com/rancher/kontainer-driver-metadata/pull/886

**Comment by rancher-max** [comment]
This has been fully validated on all rc's of rke2 and k3s. We will do a quick smoketest as soon as non-rc versions are merged, and then we can close this issue.

RKE2 PR: https://github.com/rancher/kontainer-driver-metadata/pull/894

**Comment by rancher-max** [comment]
Releases have been pushed to dev-v2.6 and this is now fully validated and complete.
