### ISSUE TITLE
minor bug:  Catalog entry versions are not correctly sorted in UI

### ISSUE THREAD

**Issue by wundram** [rancher/rancher#3719]
Rancher Version:
0.59.1
Docker Version:
1.9.1
OS: 
Ubuntu
Steps to Reproduce: 
Add a set of catalog entries versions for the same template, with versions 1.0.0.1, 1.0.0.2, 1.0.0.10
Results: 
In the upgrade or deploy UIs, 1.0.0.10 is sorted before 1.0.0.2
![image](https://cloud.githubusercontent.com/assets/2318544/13375947/faf3de82-dd72-11e5-9e58-f6bf311c3da8.png)

Expected:
Version string should be sorted correctly.

**Comment by tfiduccia** [comment]
Version - master 7/26
@wundram This looks resolved
![image](https://cloud.githubusercontent.com/assets/11514927/17159496/9631c3c8-5352-11e6-9e72-fbc0daccc550.png)

**Comment by vincent99** [comment]
Yes, numeric sorting of catalog versions was added a couple weeks ago and will ship in 1.2.0-pre1
