### ISSUE TITLE
Monitoring - Grafana Drill Down - broken after upgrading from 100.0.0 to 100.1.2 on Rancher 2.6

### ISSUE THREAD

**Issue by garrmark** [rancher/rancher#37196]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option:
   - Helm Chart, Kubernetes Cluster 1.21.8 and version RKE1
- Proxy/Cert Details: ssl-offloaded to load balancer

**Information about the Cluster**
- Kubernetes version: 1.21.8
- Cluster Type (Local/Downstream):
   - imported downstream rke1

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
I have an issue with rancher-monitoring in grafana, when running 100.0.0 I can go to the Kubernetes/Compute Resources/Cluster and then click on a namespace and drill down to Compute Resources/Namespace (Pods), but when I upgrade to 100.1.2 the drill down is broken and I get a 404 error.
The drill down url doesn't have the proper proxy any more, the first 2 urls are the old ones that work, the last 2 are the new ones with the issue:

> https://myrancher/k8s/clusters/c-2b22g/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/efa86fd1d0c121a26444b636a3f509a8/kubernetes-compute-resources-cluster?orgId=1&refresh=10s
> https://myrancher/k8s/clusters/c-2b22g/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=default&var-cluster=&var-namespace=kube-system&refresh=10s

> https://myrancher/k8s/clusters/c-m-677vxkgx/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/efa86fd1d0c121a26444b636a3f509a8/kubernetes-compute-resources-cluster?orgId=1&refresh=10s
> https://myrancher/d/85a562078cdf77779eaa1add43ccec1e/k8s-resources-namespace?var-datasource=default&var-cluster=&var-namespace=qa

**To Reproduce**
open Grafana and go to the Kubernetes/Compute Resources/Cluster
click on any namespace hyperlink

**Result**

404 not found error

**Expected Result**
Compute Resources/Namespace (Pods) for the selected namespace

**Comment by ramilano** [comment]
Hi, same issue for me

**Comment by oncipriani** [comment]
Same issue on Rancher 2.6.4 with `rancher-monitoring:100.1.2+up19.0.3`.

**Comment by timmy59100** [comment]
same.

**Comment by Jono-SUSE-Rancher** [comment]
@aiyengar2 & @PennyScissors - Can you guys take a look at this PR and we can see about including it into the next milestone?

**Comment by SheilaghM** [comment]
@PennyScissors please estimate LOE on this and see if you can hand off to another engineer.

**Comment by PennyScissors** [comment]
@SheilaghM I discussed this with @aiyengar2 offline and we agreed on 5 LOE and either @geethub97 or @eliyamlevy can work on it.

**Comment by garrmark** [comment]
do you need any more information @geethub97?

**Comment by aiyengar2** [comment]
Fixing in https://github.com/rancher/charts/pull/1983, explanation on the PR!

**Comment by ronhorton** [comment]
**Pass** verified in `2.6-head Commit ID ecbce2e`
1. installed monitoring 100.0.0
2. verified grafana page loaded
3. went to kubernetes/networking/namespace
4. verified able to drill down on values
5. upgraded to 100.1.2
6. repeat steps 2-3
7. upgraded to 100.1.3
8. repeat steps 2-3

`grafana drill down returns works and proper data loads as result of drill down`

<img width="1618" alt="2022-08-01_15-37-17" src="https://user-images.githubusercontent.com/89212856/182232090-0f6a84a9-d466-4ea5-9fc3-1b98f8b82281.png">
