### ISSUE TITLE
newUserDefault value for Cluster/Project/Namespace Role is discarded

### ISSUE THREAD

**Issue by cnotv** [rancher/rancher#37209]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Either local or DO

**User Information**
- What is the role of the user logged in? Admin/Cluster
   
**Describe the bug**
While creating a Cluster/Project/Namespace Role, the PUT request is correctly sent, but the value `newUserDefault: true` is discarded without error.

**To Reproduce**
Either create a new role adding the key/value `newUserDefault: true` or follow the UI steps:
- Navigate to role creation view `/c/local/auth/roles#CLUSTER` or `/c/local/auth/roles#NAMESPACE`
- Select the option `Yes` for `Cluster Creator Default or `Project Creator Default`
- Save and  check network request to be sure the value is submitted

**Result**
On redirection to list or either page reload the value is discarded.

**Expected Result**
Expected value to be kept.

**Screenshots**
![Screenshot from 2022-04-06 10-46-31](https://user-images.githubusercontent.com/5009481/162014512-0bf6adb1-c7ba-4e00-8ea0-5491ab7bf06b.png)

**Additional context**
This is a followup of the following rancher/dashboard issue: https://github.com/rancher/dashboard/issues/5576#issuecomment-1090016122

**Comment by gaktive** [comment]
Internal reference: SURE-4235, SURE-4236

**Comment by MbolotSuse** [comment]
@cnotv @gaktive 

Took a look at this. As you can see in our [rancher codebase](https://github.com/rancher/rancher/blob/ce9b26514466569feb0dd224c02c5061fbe683ac/pkg/apis/management.cattle.io/v3/authz_types.go#L109-L125), the object that you are trying to update (RoleTemplate) does not have a `newUserDefault` field. This value is used only in the case of global roles (newUsers aren't assigned roles on specific projects or clusters by default - but they can be assigned global roles in rancher).

The values that you want to use are:
- `clusterCreatorDefault` - for roleTemplates which have a `Context` of `cluster` (i.e. for cluster roles)
- `projectCreatorDefault` - for roleTemplates which have a `Context` of `project` (i.e. for project roles)

After making changes to roleTemplates (using these values) directly through the API I was able to see the defaults work as expected.

I would recommend that you review your use of this value and change to use the proper values, namely: [here](https://github.com/rancher/dashboard/blob/ab8011fed639ae66f399b3117102661168cfa263/models/management.cattle.io.roletemplate.js#L14) and [here](https://github.com/rancher/dashboard/blob/ab8011fed639ae66f399b3117102661168cfa263/models/management.cattle.io.roletemplate.js#L152).

**Comment by cnotv** [comment]
This has been already defined by @MbolotSuse to be an issue in the data sent from the dashboard and has been currently solved with https://github.com/rancher/dashboard/issues/5576 by completing the implementation, which was previously completely missing and not just a bug.

**Comment by cnotv** [comment]
As the QA seems to be completed, we can close this issue.

**Comment by gaktive** [comment]
Will pass to QA then to ensure that they are aware as part of the test plan but as noted, already tested.

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required. Validated again - but also tested in [https://github.com/rancher/dashboard/issues/5576](https://github.com/rancher/dashboard/issues/5576)

<hr>
  
## Validation Environment

| Component                 | Version / Type                           |
| ------------------------- | ---------------------------------------- |
| Rancher version           | 2.6.5-rc2                                |
| Rancher commit link       | not applicable                           |
| Installation option       | helm high availability                   |
| RKE binary version used   | v1.3.8                                   |
| If Helm Chart k8s cluster | v1.22.7                                  |
| Cert Details              | let's encrypt                            |
| Docker version            | 20.10.7, build f0df350                   |
| Helm version              | v2.16.8-rancher1                         |
| Downstream cluster type   | not applicable                           |
| Downstream K8s version    | not applicable                           |
| Logged in user role       | administrator                            |
| Browser type              | google chrome                            |
| Browser version           | 100.0.4896.127 (official build) (x86_64) |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
kubectl create namespace cattle-system
```

```shell
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1 \
  --set installCRDs=true
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$OMITTED \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$OMITTED \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.5-rc2
```

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> click `Users & Authentication` -> click `Roles` -> click the `Project/Namespaces` tab
3. Click the `ellipsis (three dots)` icon next to the `Display Name: Project Member Name: `project-member` role -> click `Edit Config`
4. Under the option for `Project Creator Default` select:
   - `Yes: Default role for new project creation`
5. Open network console in google chrome
6. Click `Save`
7. Observe the network traffic console

## Additional Info

## RESULTS

#### :white_check_mark: Expected
`projectCreatorDefault: true`

#### :white_check_mark:Actual
`projectCreatorDefault: true`

**Comment by samjustus** [comment]
SURE-4588
