### ISSUE TITLE
Upgrade Istio to 1.13.x

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#37219]
In order to continue moving forward, we need to upgrade Istio to 1.13.x. This adds support for Kubernetes 1.23.

**Comment by vivek-infracloud** [comment]
Validated on rancher/rancher:v2.6-head (25381f9)

Created a downstream cluster with 3worker, 1etcd, 1 cp

**Tested Istio charts for version 100.3.0+up1.13.3, Kiali - v1.50.0, and Jaeger - v1.33.0.**
**Tested following scenarios. all the tested scenarios passed the checks.**

- Fresh install checks
- Upgrade test case from istio 1.12.6 —> 1.13.3
- Upgrade with custom overlay
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Reinstall
- Istio pointing to externally-installed Prometheus
- Multiple ingress
- Egressgateway

Istio 1.13.3, Kiali and Jaeger are working fine for all the tested scenarios. Hence, closing the issue.
