### ISSUE TITLE
Upgrade Istio to 1.12.6

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#37218]
As a forward progress to keep up to date with more recent versions, we need to upgrade Istio to 1.12.6

**Comment by MKlimuszka** [comment]
Making this a blocker, since this needs to be completed in order to move forward to Istio 1.13, which has k8s 1.23 support.

**Comment by vivek-infracloud** [comment]
**Validation steps followed**

On rancher v2.6.5-rc1 Created a downstream k8s v1.22 cluster with 1cp, 1 etcd, 3 worker planes.

Fresh install works fine.

**Comment by vivek-infracloud** [comment]
On rancher/rancher:v2.6.5-rc1

Create a downstream cluster with 3worker, 1etcd, 1 cp

**Tested Istio charts for version 100.2.0+up1.12.6, Kiali - v1.44.0, and Jaeger - v1.32.0.**
**Tested following scenarios. all the tested scenarios passed the checks.**

- Fresh install checks
- Upgrade test case from istio 1.11.7 —> 1.12.6
- Upgrade with custom overlay
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Reinstall
- Istio pointing to externally-installed Prometheus
- Multiple ingress
- Egressgateway

Istio 1.12.6, Kiali 1.44 and Jaeger 1.32 are working fine for all the tested scenarios. Hence, closing the issue.

**Comment by vivek-infracloud** [comment]
Sorry for reopening, but I forgot to mention one issue with the istio checks.

Istio uninstall and re-installation doesn't pass as expected. Because, the istio mutatingwebhookconfiguration do not get deleted in uninstall process. However, if we delete the istio mutatingwebhookconfiguration manually, all the tests passed.

**Comment by vivek-infracloud** [comment]
On rancher/rancher:v2.6.5-rc1

Create a downstream cluster with 3worker, 1etcd, 1 cp

**Tested Istio charts for version 100.2.0+up1.12.6, Kiali - v1.44.0, and Jaeger - v1.32.0.**
**Tested following scenarios. all the tested scenarios passed the checks.**

- Fresh install checks
- Upgrade test case from istio 1.11.7 —> 1.12.6
- Upgrade with custom overlay
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Reinstall
- Istio pointing to externally-installed Prometheus
- Multiple ingress
- Egressgateway

Istio 1.12.6, Kiali and Jaeger are working fine for all the tested scenarios. Hence, closing the issue.
