### ISSUE TITLE
Upgrade OPA Gatekeeper chart to v3.7.1

### ISSUE THREAD

**Issue by samkulkarni20** [rancher/rancher#37229]
As a forward progress to keep up to date with more recent versions, we need to upgrade OPA Gatekeeper chart to upstream version v3.7.1

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6-head(eb03517)

Steps followed:
- Provisioned a v1.22.9-rancher1-1 node driver cluster(1-cp,1-etcd,2-worker).
- Installed OPA Gatekeeper `100.1.0+up3.7.1`
- Created the constraints using the default templates for Namespace and Repository.
- The constraints are working as expected.

**Chart installed successfully:**
![pods-up](https://user-images.githubusercontent.com/36376154/166227521-3106ebdf-e62f-42dd-822c-d41b48b421ab.png)

**OPA Gatekeeper 3.6.0 chart version:**
![chart-versions1](https://user-images.githubusercontent.com/36376154/166227721-b4331188-6ad7-42d9-a0a3-79b1e5b56667.png)
