### ISSUE TITLE
[Backport 2.5] Update Azure AD API from ADAL to MSAL

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#37228]
rancher/rancher#29306

**Comment by gaktive** [comment]
@mantis-toboggan-md how does @genexpr's proposal sound to you?

**Comment by mantis-toboggan-md** [comment]
@gaktive I would greatly prefer not to do that, given my inexperience with the Ember UI. I'll ping max to discuss options

**Comment by anupama2501** [comment]
Verified on v2.5-head `444fba4`

Fresh checks standard endpoints

1. Install rancher on v2.5-head
2. Enable Azure AD auth by selecting the standard endpoint using the existing app
3. Verify no message appears in rancher UI for the end point upgrade as the endpoint should be the latest
4. Verify the endpoints configured are the latest by running the command against the local cluster's kubeconfig kubectl describe authconfig azuread | grep graph
5. Create a downstream cluster - c1
6. As an admin, created a projects P1 
7. Add users from Azure AD to the downstream cluster as user1:cluster Owner, user2:cluster member, user3: custom [Create Projects], user4: Project P1 - owner, user5: Project P1 member, user6: Read-only in project P1, user7: custom view workloads in project P1
8. Log in as the new user1 and verify user can list the cluster
9. Run pre-upgrade checks by creating a user token for the cluster owner
10. Verify all the pre-upgrade checks work
11. Login as user2 - create a few workloads, Verify user can list cluster members but cannot delete any member
12. Login as user3 - Verify user3 cannot create projects, cannot create workloads, ingresses etc
13. Login as user4 - Verify user can only list the namespaces and workloads in P1, can create namespace, workloads, ingress in only P1
14. Login as user5 - Verify user can only list the namespaces and workloads in P1, can create namespace, workloads, ingress in only P1 and cannot manage members in other projects
15. Login as user6 - Verify user6 can only view project members, workloads but cannot manage workloads
16. Login as user7 - Verify user6 can only view workloads but cannot manage workloads or list members


Upgrade checks standard points:

1. Install rancher on v2.5.15
2. Enable Azure AD auth by selecting the standard endpoint
3. Verify no message appears in rancher UI for the end point upgrade as the endpoint should be the latest (for v2.5.15)
4. Create 3 downstream clusters - c1, c2
5. Add group1 as restricted admin
6. Add users from Azure AD to the downstream cluster as user1:cluster Owner, user2: cluster member in cluster1
7. Create an API token as user1 from profile in the top right corner >> Account & API keys >> Create API Key and copy the bearer token
8. Run pre-upgrade checks jenkins job by using the token created from the above step for the cluster owner
9. Login as user2 - create a few workloads, Verify user can list cluster members but cannot delete/add users
10. Add user3 as cluster custom Manage cluster members in cluster1
11. Login as user3 - Verify user3 cannot create projects, cannot create workloads, ingresses etc and can only manage members from c1
12. Create 2 projects P1 and P2 as an admin in cluster c2.
13. Add as an admin user4 as project owner in P1, user5 as project member in cluster c2 and project P2, user6: Read-only in project P1, user7: custom view workloads in P2
14. Login as user4 - Verify user can only list the namespaces and workloads in P1, can create namespace, workloads, ingress in only P1
15. Login as user5 - Verify user can only list the namespaces and workloads in P2, can create namespace, workloads, ingress in only P2 and cannot manage members in P2
16. Login as user6 - Verify user6 can only view project members, workloads but cannot manage workloads in project P1
17. Login as user7 - Verify user7 can only view workloads but cannot manage workloads or list members in project P2
18. Upgrade rancher server to v2.5-head as an admin
19. Verify a banner is displayed in the UI upon logging in as an admin that says API end points should be upgraded post rancher upgrade.
20. From auth providers >> Azure AD auth >> click on the upgrade end point button to upgrade the end points.
21. Add the additional permissions to the app in azure portal:
22. Group.Read.All
23. User.Read.All
24. Verify the upgrade is successful by running the command kubectl describe authconfig azuread | grep graph
25. Run post upgrade jenkins job checks on the clusters c1 with the API token created from step 7.
26. Repeat steps 9 through 17.
27. Create a downstream cluster c3
28. Add users u11:cluster owner, u12:cluster member, u13: project owner, u14: project member in the cluster
29. Login as respective users and verify the login is successful
30. Run pre upgrade checks on the cluster c13
31. From c1 remove the users u1, u2 and add u3:CO and u4:CM
32. Verify u1, u2 cannot access cluster c1 and u3, u4 can access the cluster

**Comment by rootwuj** [comment]
Verified on v2.5-head (`6761ce6`)

**Fresh checks china endpoints**

1. Install rancher on v2.5-head
2. Enable Azure AD auth by selecting the **china** endpoint using the existing app
3. Verify no message appears in rancher UI for the end point upgrade as the endpoint should be the latest
4. Verify the endpoints configured are the latest by running the command against the local cluster's kubeconfig kubectl describe authconfig azuread | grep graph
5. Create a downstream cluster - c1
6. As an admin, create 2 projects P1 and P2.
7. Add users from Azure AD to the downstream cluster as user1:cluster Owner, user2:cluster member, user3: custom [Manage cluster members], user4: Project P1 - owner, user5: Project P2 member, user6: Read-only in project P1, user7: custom view workloads in project P2
8. Log in as the new user1 and verify user can list the cluster 
9. Run pre-upgrade checks by creating a user token for the cluster owner
10. Verify all the pre-upgrade checks work
11. Login as user2 - create a few workloads, Verify user can list cluster members but cannot delete any member
12. Login as user3 - Verify user3 cannot create projects, cannot create workloads, ingresses etc
13. Login as user4 - Verify user can only list the namespaces and workloads in P1, can create namespace, workloads, ingress in only P1
14. Login as user5 - Verify user can only list the namespaces and workloads in P2, can create namespace, workloads, ingress in only P2 and cannot manage members in P2
15. Login as user6 - Verify user6 can only view project members, workloads but cannot manage workloads
16. Login as user7 - Verify user7 can only view workloads but cannot manage workloads or list members

China new endpoint upgraded to:
```
Endpoint:	https://login.partner.microsoftonline.cn/
Graph Endpoint:	https://microsoftgraph.chinacloudapi.cn
Token Endpoint:	https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/token
Auth Endpoint:	https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/authorize
```

**Upgrade checks china points:**


1. Install rancher on v2.5.15
2. Enable Azure AD auth by selecting the china endpoint
3. Verify no message appears in rancher UI for the end point upgrade as the endpoint should be the latest (for v2.5.15)
4. Create 2 downstream clusters - c1, c2
5. Add group1 as restricted admin 
6. Add users from Azure AD to the downstream cluster as user1:cluster Owner, user2: cluster member in cluster1
7. Create an API token as user1 from profile in the top right corner >> Account & API keys >> Create API Key and copy the bearer token
8. Run pre-upgrade checks by using the token created from the above step for the cluster owner
9. Login as user2 - create a few workloads, Verify user can list cluster members but cannot delete/add users
10. Add user3 as cluster custom Manage cluster members in cluster1
11. Login as user3 - Verify user3 cannot create projects, cannot create workloads, ingresses etc and can only manage members from c1 
12. Create 2 projects P1 and P2 as an admin in cluster c2.
13. Add as an admin user4 as project owner in P1, user5 as project member in cluster c2 and project P2, user6: Read-only in project P1, user7: custom view workloads in P2
14. Login as user4 - Verify user can only list the namespaces and workloads in P1, can create namespace, workloads, ingress in only P1
15. Login as user5 - Verify user can only list the namespaces and workloads in P2, can create namespace, workloads, ingress in onlyP2 and cannot manage members in P2
16. Login as user6 - Verify user6 can only view project members, workloads but cannot manage workloads in project P1
17. Login as user7 - Verify user7 can only view workloads but cannot manage workloads or list members in project P2
18. Upgrade rancher server to v2.5-head as an admin
19. Verify a banner is displayed in the UI upon logging in as an admin that says API end points should be upgraded post rancher upgrade.
20. From auth providers >> Azure AD auth >> click on the upgrade end point button to upgrade the end points. 
21. Add the additional permissions to the app in azure portal:
	- Group.Read.All
	- User.Read.All
22. Verify the upgrade is successful by running the command kubectl describe authconfig azuread | grep graph
23. Run post upgrade jenkins job checks on the clusters c1 with theAPI token created from step 7.
24. Repeat steps 9 through 17.
25. Create a downstream cluster c3
26. Add users u11:cluster owner, u12:cluster member, u13: project owner, u14: project member in the cluster
27. Login as respective users and verify the login is successful
28. Run pre upgrade checks on the cluster c3
29. From c1 remove the users u1, u2 and add u3:CO and u4:CM
30. Verify u1, u2 cannot access cluster c1 and u3, u4 can access the cluster

**Comment by anupama2501** [comment]
Verified - Updating end point manually:
```
kubectl edit authconfigs azuread
Remove the annotation `auth.cattle.io/azuread-endpoint-migrated: true`
Update the graph endpoint, token endpoint and auth endpoint as follows:
`https://graph.windows.net/`
`https://login.microsoftonline.com/<subscriptionID>/oauth2/token`
`https://login.microsoftonline.com/<subscriptionID>/oauth2/authorize`
```

Log out of rancher server and log back in - works as expected
Post rancher server upgrade - log out and log back in works as expected
Update endpoints - log out and log back in works as expected.

**Comment by anupama2501** [comment]
Re opening for a few more validations

**Comment by anupama2501** [comment]
Upgrade from 2.5.16 >> 2.5.16-rc1 - PASS
Disable auth - PASS
Disable and re enable auth post rancher upgrade from - PASS
Roll back via Backup/restore on same cluster - PASS
Roll back via Backup/restore on a migrated cluster - PASS
Backup/restore post upgrade - PASS
Refresh Users - PASS
Refresh Groups - PASS
Delete users - PASS
Update endpoints as a restricted admin - PASS
