### ISSUE TITLE
[BUG] RKE2 private registry setting doesn't apply to rancher-system-agent

### ISSUE THREAD

**Issue by FrankYang0529** [rancher/rancher#37221]
**Rancher Server Setup**
- Rancher version: v2.6.4
- Installation option: Docker

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Downstream - Harverster

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When users use Rancher in the non-air-gapped environment to create an RKE2 cluster in an air-gapped environment, they will try to set a private registry in RKE2 cluster options. However, Rancher only sets it to RKE2 `system-default-registry` variable. From rancher-system-agent logs, we can see it still gets images from `index.docker.io`.

**To Reproduce**
1. Create a Harvester cluster.
2. Import Harvester to Rancher.
3. Create an RKE2 cluster with a private registry like `myregister.test`.
4. Check plan in `/var/lib/rancher/agent/applied/xxx.plan`. We can see `instructions[0].image`. It doesn't have `myregister.test` in the front.
5. Check rancher-system-agent logs. `journalctl -u rancher-system-agent.service`. It still pulls the image from `index.docker.io`.

**Result**
Cannot change the registry for rancher-system-agent.

**Expected Result**
rancher-system-agent use the registry in `instructions[0].image` or set it in `/etc/rancher/agent/registries.yaml`.

https://github.com/harvester/harvester/issues/2125

**Comment by slickwarren** [comment]
upon further investigation, this is not an issue. tested on v2.6.5-rc6. 

RKE2 sets the registry to `system-default-registry` if you do not have a password (http secret through rancher) setup with your registry.  If you set a secret on that step, you can see a registry listed in `/etc/rancher/rke2/registries.yaml` and `/etc/rancher/agent/registries.yaml`. Regardless of a setting in those files, the images are pulling from the registry for me.
