### ISSUE TITLE
Steve API Fix - At-scale testing

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#37236]
rancher/rancher#37046

**Comment by git-ival** [comment]
Followed the validation procedure outlined by Andrew in the comments on this issue: https://github.com/rancher/rancher/issues/36954

Compared audit logs between 2.5.12 and 2.6.5 on Small at-scale RKE1 clusters. The 2.6.5 cluster had significantly less 404s overall and significantly less duplicates as well.
