### ISSUE TITLE
Agent not starting after upgrading to Docker 1.10.2

### ISSUE THREAD

**Issue by andyshinn** [rancher/rancher#3723]
Rancher Version: v0.51.0

Docker Version: 1.10.2

OS: Ubuntu 14.04.4

Steps to Reproduce: Upgrade from Docker 1.6.2 to Docker 1.10.2

Results: Agent does not start (see error below)

Expected: Agent starts up properly.

After upgrading Docker to 1.10.2 (in preparation so I can upgrade to rancher > v0.59.x) I am finding that the agent will not start up:

```
ashinn@cloud-transfer4:~$ d logs --since 30m 204
2016-02-29 17:00:13,463 ERROR agent [140466666328304] [event.py:111] 966d2026-3d66-46d4-b5da-3b9a8b27cccb : Unknown error 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 94, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 125, in on_ping
    self._add_instances(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 137, in _add_instances
    running, nonrunning = self._get_all_containers_by_state()
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 170, in _get_all_containers_by_state
    for c in client.containers(all=True):
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 67, in containers
    res = self._result(self._get(u, params=params), True)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 146, in _result
    self._raise_for_status(response)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 142, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("engine is shutdown")
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
...
```

It is stuck in a constant restart:

```
ashinn@cloud-transfer4:~$ d ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS                              PORTS               NAMES
2046905cf9c9        rancher/agent:v0.8.2   "/run.sh run"       3 months ago        Restarting (1) About a minute ago                       rancher-agent
```

I tried adding the agent again (without removing anything) and the initial start fails with:

```
...
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SYSTEMD=false
INFO: ENV: CATTLE_URL=https://rancher.mydomain.com/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=10.20.91.227
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v0.8.2
INFO: Deleting container rancher-agent
invalid value "." for flag -v: . is not an absolute path
See 'docker run --help'.
```

I'll next try rebooting the server and clearing `/var/lib/rancher`. But any idea why this is happening?

**Comment by fernandoneto** [comment]
I see that issue some time ago and after some search i run this command.
```bash
sudo rm -fR /var/lib/docker/network/*
```

**Comment by andyshinn** [comment]
I ultimately had to rebuild this agent after the server wouldn't reboot due to a disk issue. But I'll try this after I encounter it again and report back. Thanks for the suggestion!

**Comment by andyshinn** [comment]
I'm reopening as this is happening again on another test host and removing `/var/lib/docker/network/*` didn't help.

**Comment by andyshinn** [comment]
What I ultimately have to end up doing for these servers is:

* Kill all the rancher containers (even the stopped ones)
* Remove the images
* Run the agent run command again for the environment

I left the `/var/lib/rancher/state` and everything seems to come back up after this. I can't really explain why removing the images is necessary. But just killing the containers and running the agent did not work. I'm not sure if this is related to Rancher or Docker but since I have a workaround now I'm OK with this being closed (at least here in case someone else runs into the same thing).

I'm basically on v0.56 still and trying to get everything on Docker 1.9+ before going to v0.59+. It seems like all my Docker 1.6 hosts have this issue going to Docker 1.10.2.

**Comment by deniseschannon** [comment]
Docker 1.9.1+ is our new requirement for Rancher (as of v0.59.0), so moving them all to at least Docker 1.9.1+ would be suggested before upgrading. 

https://github.com/rancher/rancher/releases/tag/v0.59.0

Going to close for now.

**Comment by bemosior** [comment]
I encountered this issue (`invalid value "." for flag -v: . is not an absolute path`) on Rancher agent launch after an upgrade from Docker 1.6 to 1.12.1 on Ubuntu 14.04. Killing all containers and removing all images did allow me to successfully run the agent.
