### ISSUE TITLE
TLS Timout Failure pulling image from docker hub

### ISSUE THREAD

**Issue by dnadave** [rancher/rancher#3724]
Rancher Version: 0.59.1

Docker Version: 1.9.1, build a34a1d5

OS: OpenSuSE Leap 42.1

Steps to Reproduce: Start stack from catalog

Results: Stack fails to start.  See messages in log files about TLS Timeout Failure:

```
2016-02-29 23:09:02,012 INFO agent [140671623058768] [utils.py:430] worker5 : Done request 514071ae-aa1e-4ebe-ad91-6dca09333abd for compute.instance.activate [20.9789910316] seconds 
2016-02-29 23:09:02,012 ERROR agent [140671623058768] [event.py:112] Error in request : 514071ae-aa1e-4ebe-ad91-6dca09333abd 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 481, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 553, in _do_instance_activate
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 577, in _create_container
    }), progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 850, in _do_instance_pull
    DockerPool.image_pull(pull_info.image, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 94, in image_pull
    return DockerPool()._do_image_activate(image, None, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 160, in _do_image_activate
    raise e
ImageValidationError: Image [dnadave/wettyr:jan2016] failed to pull: Get https://registry-1.docker.io/v1/repositories/dnadave/wettyr/tags/jan2016: net/http: TLS handshake timeout
```

Expected: Stack starts and port gets assigned.  This had been working until sometime last week.

**Comment by dnadave** [comment]
WHY IS YOUR DOCKER HUB REGISTRY LOGIN BROKEN!!??!!  I've reconfigured this several times.  I've googled this and there's no help there.  I post here and as usual, no answer.  For 20 hours.  We're stuck.  We can't do anything until we get this fixed.

**Comment by vincent99** [comment]
Their [status page](http://status.docker.com/) rarely reflects it, but DockerHub was down yesterday afternoon.

This is a free open-source product and we address community issues when we have time for them.  If you need support with an SLA I would be happy to introduce you to our sales team.

**Comment by dnadave** [comment]
With this attitude towards a blocking issue, if there was an alternative to your platform, I would jump to it in a heartbeat.

**Comment by dnadave** [comment]
It makes me very reluctant to want to pay you money since it seems you don't really care about your users.

**Comment by dnadave** [comment]
And, this is not a docker hub issue.  I can pull and start containers from the command line.  I just cannot start anything from the dashboard.  I get a TLS timeout error every time.

**Comment by vincent99** [comment]
The [code that stack trace points to](https://github.com/rancher/python-agent/blob/master/cattle/plugins/docker/storage.py#L96-L160) is just using the docker client to pull the image.  There's nothing else I can tell you from the information provided beyond what the stack trace already says; it can't connect.  Since you're running a not-very-common OS we never test and have [persistent networking problems with it](https://github.com/rancher/rancher/issues/3503), I would start there.  We haven't remotely changed code from underneath you, if it worked last week nothing in Rancher has changed.

**Comment by dnadave** [comment]
Well, I can tell you that I can pull and start new containers on the command line.  From those containers, I have full network access.  It's only Rancher that cannot connect and pull from my repo.

**Comment by vincent99** [comment]
**in** the rancher/agent container on the host?

**Comment by dnadave** [comment]
Let's suppose I start a container on the command line from my repo: dnadave/wettyr.  I can spin that up, pull a new version of it even, and then log in to it.  From that container, I can ping hosts outside and inside my won network.  I can also use wget to download new files.

Now, I keep getting this TLS timeout error in Rancher trying to pull a new image.  It seems that Rancher cannot authenticate with docker hub, despite my entering my credentials in the docker hub registry.  I've tried deleting and creating that registry multiple times and I know that I've entered the correct credentials for it as I can use those same credentials to log in from a web page.

**Comment by vincent99** [comment]
Authentication can't have anything to do with it until there's a TLS connection established.

**Comment by dnadave** [comment]
So, why would a connection not be able to be established?  The only things I can think of are network outages (not applicable here as networking is working at the moment) and time misalignments and our server is synced to the atomic clock which I supposed docker hub is, as well.  We've given Rancher the proper credentials, so login denials should not be a problem.  What else can I look into?

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/4072#issuecomment-201076432
