### ISSUE TITLE
Update the CIS Hardening Guide for standalone RKE2

### ISSUE THREAD

**Issue by macedogm** [rancher/rancher#37242]
Following https://github.com/rancher/rancher/issues/36629, we also updated RKE2 standalone hardening guide. This issue is just to track the QA review of PR https://github.com/rancher/rke2/pull/2507.

### Root cause
As we are adding a new RKE2 hardening guide in https://github.com/rancher/rancher/issues/36629 for Rancher GA provisioning of RKE2 clusters, we also did a review of the current standalone [hardening guide](https://docs.rke2.io/security/hardening_guide/) provided for RKE2.

### What was fixed?
The CIS hardening guide for RKE2 was reviewed and small improvements were added to make sure that it passes CIS profile v1.6 - [rke2-cis-1.6-hardened](https://github.com/rancher/security-scan/tree/master/package/cfg/rke2-cis-1.6-hardened).

### What should be tested?

1. Install a local Rancher 2.6.4 cluster through Helm.
1. Create a cluster with RKE2 (using its [default install instructions](https://github.com/rancher/rke2#quick-start) and version `v1.21.9+rke2r1`).
    ```
    curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="v1.21.9+rke2r1" sh - && \
    systemctl enable rke2-server.service && \
    systemctl start rke2-server.service && \
    export KUBECONFIG=/etc/rancher/rke2/rke2.yaml PATH=$PATH:/var/lib/rancher/rke2/bin
    ```
1. Import the cluster in Rancher.
1. Install `CIS Benchmark (2.0.2)` chart in the imported RKE2 cluster.
1. Execute a CIS scan with the `rke2-cis-1.6-hardened` profile.
1. Verify the failed tests.
1. Create a new cluster with RKE2 (with version `v1.21.9+rke2r1`), apply the hardening steps. Follow the hardening steps as described in:
    1. Section [Set kernel parameters](https://github.com/rancher/rke2/blob/97bd4142d4b58707b477a68bbb0259a0810e57c6/docs/security/hardening_guide.md#set-kernel-parameters).
    1. Section [Create the etcd user](https://github.com/rancher/rke2/blob/97bd4142d4b58707b477a68bbb0259a0810e57c6/docs/security/hardening_guide.md#create-the-etcd-user).
    1. Section [RKE2 configuration](https://github.com/rancher/rke2/blob/97bd4142d4b58707b477a68bbb0259a0810e57c6/docs/security/hardening_guide.md#rke2-configuration).
    1. Restart RKE2 server in order to apply the new configuration - `systemctl restart rke2-server.service`.
1. Import the cluster in Rancher.
1. Apply the hardening step in section [Configure default service account](https://github.com/rancher/rke2/blob/97bd4142d4b58707b477a68bbb0259a0810e57c6/docs/security/hardening_guide.md#configure-default-service-account). This needs to be executed after the RKE2 cluster is imported in Rancher.
1. Install `CIS Benchmark (2.0.2)` chart in the new imported hardened RKE2 cluster.
1. Execute a CIS scan with the `rke2-cis-1.6-hardened` profile.
1. Verify that no tests failed in the hardened RKE2 cluster.

### What areas could experience regressions?
No regression is expected.

**Comment by anupama2501** [comment]
Verified on an imported RKE2 cluster cis scans for rke2-cis-1.6-profile-hardened following the instructions from the above mentioned template.

 rke2-cis-1.6-profile-hardened on the local cluster fails for 5.1.5 - security issue 1029
