### ISSUE TITLE
Context timeout via rancher authentication proxy when calling kubectl rollout status

### ISSUE THREAD

**Issue by RalphDriessen** [rancher/rancher#37241]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 v1.20.9
- Proxy/Cert Details: Hosted on Azure

**Information about the Cluster**
- Kubernetes version: v1.22.7
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported

**Describe the bug**
When retrieving the rollout status of a deployment through the rancher authentication proxy some context is timing out resulting in a wait time of 5 minutes before the request is completed. When performing the same call via the authorized cluster endpoint we retrieve the expected result without any issues. We are not having this issue at all on our clusters running on Rancher v2.5.1 and kubernetes v1.19.7

**To Reproduce**
Call `kubectl rollout status deployment/my-app` via rancher authentication proxy.
**Note:** Happens specifically for some clusters, our manifest (redacted some information): [manifest.yaml.txt](https://github.com/rancher/rancher/files/8450681/manifest.yaml.txt).

**Result**
Message `deployment successfully rolled out` is shown within a few seconds, after this the process continues for ~5 minutes without any output. Latest logs of this process: [kubectlrolloutstatuslogs.txt](https://github.com/rancher/rancher/files/8450692/kubectlrolloutstatuslogs.txt).

**Expected Result**
Expected result is that the process is done after returning the successfully rolled out message.

**Additional context**
This issue was first discussed on an issue at kubectl: https://github.com/kubernetes/kubectl/issues/1163

**Comment by KokoBello** [comment]
Might be duplicate of https://github.com/rancher/rancher/issues/21324

**Comment by RalphDriessen** [comment]
> Might be duplicate of #21324

Looks like it indeed, I will close this one, thanks!
