### ISSUE TITLE
Re-Installing Rancher deployment --  Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists

### ISSUE THREAD

**Issue by busyboy77** [rancher/rancher#37246]
**Rancher Server Setup**
- Rancher version:

```
# helm list -n cattle-system
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
rancher         cattle-system   1               2022-04-08 18:21:30.812033195 +0500 PKT deployed        rancher-2.6.4                   v2.6.4
rancher-webhook cattle-system   1               2022-04-08 13:23:10.556921134 +0000 UTC deployed        rancher-webhook-1.0.4+up0.2.5   0.2.5
```

- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

Helm Chart

**Information about the Cluster**
- Kubernetes version:

v1.23.5

- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

Intrgrated inside the K8s Cluster using[Install/Upgrade Rancher on a Kubernetes Cluster]( https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/#install-the-rancher-helm-chart)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions

admin

   
**Describe the bug**

When re-installing the Rancher deployment using helm chart, getting below given error

```
# helm install rancher rancher-stable/rancher   --namespace cattle-system   --set hostname=devops215 --set replicas=3
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "bootstrap-secret" in namespace "cattle-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rancher"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-system"

```

**To Reproduce**
remove the Rancher using `helm uninstall rancher`

and then re-install using helm

**Result**
Secret is never used and error is thrown

**Expected Result**
It should either delete the secrete during uninstallation or re-use the secret bootstrap-secret

**Screenshots**
not applicable

**Additional context**
I had to 

```
1)  kubectl get secrets -n cattle-system
2) kubectl delete secret bootstrap-secret  -n cattle-system
3) helm install rancher rancher-stable/rancher   --namespace cattle-system   --set hostname=devops215 --set replicas=3
4) kubectl -n cattle-system exec $(kubectl -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- reset-password
```

**Comment by superseb** [comment]
Same as https://github.com/rancher/rancher/issues/37060
