### ISSUE TITLE
[Backport] v2.5: Reset remotedialer buffer to reduce memory allocation

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#37257]
**Original Issue:**
https://github.com/rancher/rancher/issues/36531

**Comment by rmweir** [comment]
Just test the same way as here: https://github.com/rancher/rancher/issues/36531#issuecomment-1055736135.

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

<hr>

## Validation Environment

| Component                 | Version / Type                                                                                                                                   |
| ------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------ |
| Rancher version           | v2.5-cb699448e05d294fae461ec1bae039753b56bb9b-head [cb69944](https://github.com/rancher/rancher/commit/cb699448e05d294fae461ec1bae039753b56bb9b) |
| Installation option       | Helm high availability                                                                                                                           |
| RKE binary version used   | v1.2.19                                                                                                                                          |
| If Helm Chart k8s cluster | v1.20.15                                                                                                                                         |
| Cert Details              | ingress.tls.source=secret (certificates from files)                                                                                              |
| Docker version            | 20.10.7, build f0df350                                                                                                                           |
| Helm version              | v2.16.8-rancher1                                                                                                                                 |
| Downstream cluster type   | RKE1 Amazon EC2                                                                                                                                  |
| Downstream K8s version    | v1.20.15-rancher1-2                                                                                                                              |
| Logged in user role       | Administrator                                                                                                                                    |
| Browser type              | Google Chrome                                                                                                                                    |
| Browser version           | 100.0.4896.75 (Official Build) (x86_64)                                                                                                          |

**ADDITIONAL SETUP**

- Helm install commands:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$omitted \
  --set ingress.tls.source=secret \
  --version 2.5.13-rc1 \
  --set rancherImageTag=v2.5-head
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key
```

## Validation steps

1. Create a RKE1 Amazon EC2 downstream cluster
2. Create a RKE1 Linode downstream cluster
3. Install monitoring app on local cluster / system
4. Deploy workloads on both downstream clusters
5. Create 1,000 secrets using Terraform
6. Create 200 users using Terraform
7. Check for any errors / make sure everything is working as expected
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
All cluster functionality to work as expected

#### :white_check_mark:Actual
All cluster functionality to work as expected
