### ISSUE TITLE
Fleet - Upgrade to 2.5.13-rc1 doesn't upgrade the fleet controller and agents as expected

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#37254]
**Rancher Server Setup**
- Rancher version: `v2.5.13-rc1`
- Installation option: Helm RKE1
- Proxy/Cert Details: rancher generated or byo valid

**Information about the Cluster**
- Kubernetes version: `v1.20.14` 
- Cluster Type (Local/Downstream): local `v1.20.14` 
- Cluster Type (Local/Downstream): downstream `v1.20.15`
  - 

**User Information**
- What is the role of the user logged in? Admin

   
**Describe the bug**
The fleet controller in the local cluster is kept in version `v0.3.5` but the expected is the new `v0.3.9` Like on fresh install of Rancher

**To Reproduce**

- Install Rancher `v2.5.12` on HA RKE1 cluster version (RKE `1.2.16`)
- Provision a downstream to check the agent on downstream too.
- Upgrade to Rancher `v2.5.13-rc1` check the helm repository point to the `dev-2.5` branch. 
- Refresh repositories
- Monitor the fleet-controller 

**Result**

- The fleet controller doesn't get upgraded to `v0.3.9`

**Expected Result**

- The fleet controller gets upgraded to `v0.3.9`

**Screenshots**
![Screen Shot 2022-04-10 at 7 48 59 AM](https://user-images.githubusercontent.com/27659/162625232-e1c0d9cb-a0fb-468b-bb79-8b03fe5c28b3.png)

**Additional context**

**Comment by prachidamle** [comment]
@eliyamlevy I think this is needed to bump fleet version - https://github.com/rancher/rancher/blob/release/v2.5/package/Dockerfile#L41

After updating this to `0.3.900` we will need a new rancher build to test this

**Comment by izaac** [comment]
## QA Validation

Validate using the upgrade scenario of https://github.com/rancher/dashboard/issues/5594#issuecomment-1097424650

**Comment by eliyamlevy** [comment]
PR: https://github.com/rancher/rancher/pull/37314#37254

**Comment by ronhorton** [comment]
**PASS** Verified fixed in `2.5.13-rc2`

1. created 2 downstream clusters
2. placed in 2 different fleet workspaces
3. helm upgrade ha cluster
4. clusters returned to active state
5. fleet resources in active state
6. verified fleet version upgraded to 0.3.9 automatically
<img width="1276" alt="Screen Shot 2022-04-13 at 7 52 01 PM" src="https://user-images.githubusercontent.com/89212856/163288502-f132a6ab-1bcc-440b-a260-91a5fde09475.png">

**Comment by izaac** [comment]
thanks @ronhorton
