### ISSUE TITLE
Rancher server restarts with error [FATAL] k3s exited with: exit status 2

### ISSUE THREAD

**Issue by bramamad** [rancher/rancher#37276]
*Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart): Docker install (standalone)
- Proxy/Cert Details: own server certs (from QuoVadis)
  
**Describe the bug**
[FATAL] k3s exited with: exit status 2

**To Reproduce**
- cannot reproduce
- periodically it is happening

**Result**
- stablize rancher

**Additional context**
- attached you find the rancher container log and the k3s log (from inside the container
[rancher-prod-logs.zip](https://github.com/rancher/rancher/files/8470215/rancher-prod-logs.zip)

**Comment by sunny5055** [comment]
Facing same issue. Every time docker is update rancher goes into infinite restart loop. No matter what it doesn't start. After deleting all the persistent data and creating image freshly it used to work (causing an overhead of configuring again) but not with 2.6.4 having this issue and not able to start

**Comment by kedarui** [comment]
Waiting for cluster agent to connect
