### ISSUE TITLE
cant execute helm install after uninstalling rancher server

### ISSUE THREAD

**Issue by s0ren1** [rancher/rancher#37273]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster, and version (RKE1, RKE2, k3s, EKS, etc): AKS
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.21.2
- Cluster Type (Local/Downstream): local
 
**User Information**
- What is the role of the user logged in?  Admin
**Describe the bug**
I uninstalled Rancher server by running the system tools' remove command. Some namespaces got stuck after that, so I deleted all of the CRD, and namespaces referred to Rancher. However, after that, whenever I try to do a Helm installation of any application I get the error 

`"failed to create: Internal error occurred: failed calling webhook "[rancher.cattle.io](http://rancher.cattle.io/)": Post "[https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s](https://rancher-webhook.cattle-system.svc/v1/webhook/mutation?timeout=10s)": service "rancher-webhook" not found"`

**To Reproduce**
Install Rancher Server
Uninstall using System Tools with the remove command
Remove all of the CRDs and Namespaces

**Result**

Helm installation of any application fails with error 

`"failed to create: Internal error occurred: failed calling webhook "[rancher.cattle.io](http://rancher.cattle.io/)": Post "[https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s](https://rancher-webhook.cattle-system.svc/v1/webhook/mutation?timeout=10s)": service "rancher-webhook" not found"`

**Expected Result**
Helm installations should proceed as normal

**Additional context**
I feel that something was modified by Rancher during installation which makes the helm chart installations fail but I can't tell what it is yet.

**Comment by s0ren1** [comment]
Nevermind, I just needed to run 

```
kubectl delete mutatingwebhookconfiguration mutating-webhook-configuration 
kubectl delete mutatingwebhookconfiguration rancher.cattle.io
```

**Comment by superseb** [comment]
We have created https://github.com/rancherlabs/support-tools/blob/master/cleanup-rancher-k8s-resources/cleanup.sh to cleanup Rancher resources in a k8s cluster, for future reference.
