### ISSUE TITLE
Remove object key from norman controller metrics

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#37274]
**Describe the bug**

Metrics are resource intensive and one thing we can do to improve the performance are to not make their labels overly granular since metrics are stored in rows for every combination of labels. Norman controller metrics should not include the object key. These metrics are now scraped by default in 2.6.4 and sometimes manually enabled in earlier versions.

**Comment by bmdepesa** [comment]
For QA - 

Check monitoring performance from v2.6.5 -> v2.6-head w/ CATTLE_PROMETHEUS_METRICS env var set. 

Otherwise, low risk.

**Comment by floatingman** [comment]
- Check that the object key is removed from the controller dashboard
- Check that the metric doesn’t exist when CATTLE_PROMETHEUS_METRICS = true
- Check general performance of the rancher-monitoring pods
	- Whats the difference in terms of resource usage between 2.6.5 and 2.6.6?

**Comment by rmweir** [comment]
Release Note:
Removed monitoring dashboard "Rancher Internal State (Controllers)". Most functionality from this dashboard has been replaced and can be found in the dashboard "Rancher Performance Debugging".
