### ISSUE TITLE
Upgraded Rancher 2.6.4 not doing group Shib/LDAP searches

### ISSUE THREAD

**Issue by brtduvally** [rancher/rancher#37284]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart): Helm Chart Upgrade (from 2.5.9)
   - Helm Chart v2.6.4, K8S v1.21.10-rancher1-1, RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.21.10-rancher1-1
- Cluster Type (Local):

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
After upgraded from 2.5.9, and upgrade of K8S from 1.20.4-rancher1-1, using Shibboleth auth with OpenLDAP rancher is no longer doing group searches. LDAP settings are valid as they were the same before and after upgrade. 

**To Reproduce**
Shibboleth auth with valid user and group settings. Attempt to add group to any resource produces "No results found" 

**Result**
Searches being done against LDAP are only including "uid", when setting specify group as well.
```
filter = "(&(objectClass=inetOrgPerson)(|(uid=*GROUP OR USER NAME*)))" attrs="distinguishedName isMemberOf objectClass inetorgperson XXXXXshortid cn "
```

**Expected Result**
Search should include group search. 2.5.x searches look like this: (some attr obfuscated)
```
filter="(&(objectClass=XXXXXgroup)(XXXXXGroupRDN=*GROUP OR USER NAME*))" attrs="XXXXXShortID objectClass groupname XXXXXShortID XXXXXGroupRDN XXXXXGroupRDN"
filter="(&(objectClass=inetOrgPerson)(|(uid=GROUP OR USER NAME*) attrs="distinguishedName isMemberOf objectClass inetorgperson XXXXXShortID cn "
```
Which produces group results in the search. The [documentation](https://rancher.com/docs/rancher/v2.6/en/admin-settings/authentication/shibboleth/about/) specifies this is the expected behavior in 2.6 using Shibboleth backed by OpenLDAP.

**Comment by maxthi** [comment]
I have a similar issue. Configuring LDAP via the rancher GUI, when I set the user or group search filter values and press save, they end up blank & the filter seems not to work.

My rancher version is v2.3.2

**Comment by brtduvally** [comment]
Confirmed with debug logging that the group search is not being triggered on 2.6.4 for Shib/OpenLDAP. Updating title for clarification on version. I'd include the logs, but it's only logging the user search and no other error. Should I try trace level logging?

**Comment by anupama2501** [comment]
Hi @brtduvally here are the steps I tried and see the groups search works for me.
1. Installed rancher v2.5.13 and enabled OpenLdap auth as auth provider
2. While enabling auth Select the option `Search direct and nested group memberships` under the customize schema
3. Add a group from the auth as cluster member by creating a downstream cluster.
4. Upgrade rancher version to v2.6-head  8a31d3c
5. Upgrade k8s version from 1.21.12-rancher1-1 
6. Navigate to cluster members >> Add a group as a cluster member >> Search results the groups and groups are added as cluster Owners --> returns groups without any errors

is this happening for users other than admins? eg., cluster owners[standard users]

**Comment by brtduvally** [comment]
I'm concerned about this issue going stale. 
If Shibboleth no longer supports group search, docs should be updated.

**Comment by brtduvally** [comment]
If Shibboleth no longer supports group search, docs should be updated.

**Comment by WMP** [comment]
This is still relevant. Groups auth for Shibboleth is broken in 2.6.x and 2.7.5
