### ISSUE TITLE
Rancher should treat `{}` S3 config for v2prov etcd snapshot as disabled

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#37297]
**Describe the bug**
Rancher seems to treat 
```
spec:
  etcd:
    s3: {}
```
as if S3 snapshots are enabled.

**To Reproduce**
Create a cluster with that above spec.

**Result**
Rancher treats the cluster like an etcd S3 enabled cluster.

**Expected Result**
S3 is disabled.

**Screenshots**

**Additional context**

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head b8cbc1a
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver

----------

### Testing: ###

- Tested this issue by creating cluster and adding `{}` to S3 config
![image.png](https://zube.io/files/rancher/d970f6e10bd3b7a1de965d4c9cf89a5e-image.png)

**Result** - Pass

Rancher now treats the cluster as S3 for etcd is disabled.
![image.png](https://zube.io/files/rancher/cb661cc5874bcfe89a265601ddafae28-image.png)

The UI needs to be updated to remove the fields for S3 when the option is disabled. The issue can be tracked [here](https://github.com/rancher/dashboard/issues/5657)
