### ISSUE TITLE
Fails to connect to downstream cluster's nodes when rancher is behind a proxy and nodes do not have public IPs

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#37295]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart): either one 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 
- Proxy/Cert Details: Squid proxy 

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): infrastructure Provider, AWS 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

The internal `rancher-machine` is used to create nodes when we create a node-driver cluster, but it does not use the `no_proxy` env variable, so when the proxy cannot talk to the nodes in the downstream cluster, rancher will fail to create the cluster and show ssh timeout errors. 

**To Reproduce**
 
- run a squid proxy 
- Helm install rancher with proper values for  `http_proxy` `https_proxy` and `no_proxy` 
- make sure the `no_proxy` value contains the CIDR for the to-be-created downstream cluster's nodes' private IPs. 

Here is the Helm command I used 
```
helm upgrade --install rancher rancher-latest/rancher \
   --namespace cattle-system \
   --version v2.6.4 \
   --set hostname=ec2-xxx1.us-west-1.compute.amazonaws.com \
   --set proxy=http://ec2--xxx2.us-west-1.compute.amazonaws.com:3131 \
   --set noProxy="127.0.0.0/8\,10.0.0.0/8\,172.16.0.0/12\,192.168.0.0/16\,.svc\,.cluster.local\,172.31.0.0/16" 
```

- After rancher runs up, create an ec2 node template that does not have the public IP
- create a downstream cluster by using the node template,  one node with all roles is sufficient 

**Result**
- the node is created, but we will see the following error in rancher UI
`[ERROR] error syncing 'c-pjz46/m-g8ckn': handler node-controller: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded, requeuing`

**Expected Result**

 The node should be created successfully and the cluster should be active 

 SURE-4382

**Comment by jiaqiluo** [comment]
# Root cause
The internal `rancher-machine` is used to create nodes when we create a node-driver cluster, but it does not use the `no_proxy`/`NO_PROXY` env variable, so when the proxy cannot talk to the nodes in the downstream cluster, rancher will fail to create the cluster and show ssh timeout errors.

# What was fixed, or what changes have occurred
The fix is in `rancher-machine` that it will consider the `no_proxy`/`NO_PROXY` env variable when determining the proxy to be used for a given request.


# Areas or cases that should be tested

The specific case to test for this issue is to create a  node-driver private cluster [1] in which nodes when Rancher runs behind a proxy. 

We also need to make sure all existing rancher-behind-proxy  tests are passed 

[1] private cluster means the cluster's nodes do not have public IP and therefore no access to or from the internet 

The following is how I validate the fix during the development:

### what we need

- a Squid proxy server that supports both HTTP and HTTPS. The proxy server is in subnet-1 that has access to the internet.  
- a k3s single-node cluster, the node is configured to trust the certifications of the proxy server. The node is in subnet-2 that does not have access to the internet, also no public IP is assigned to the node. 
- an AMI which has Docker pre-installed, and trusts the certifications of the proxy server, Docker is configured to pull images via the proxy
- the CIDR of nodes' private IP, in my case, happens to be `172.31.100.0/24` 

Note:  I have a tutorial here for how to set up the proxy server and configure nodes: https://gist.github.com/jiaqiluo/0dc8af71723c917fe9c683233f158e2f

### what we need to test

We will install rancher into the k3s cluster, and test if rancher can provision node-driver cluster in which nodes are also in the subnet-2, without public IP, using the custom AMI. 

We will test different values for the options `proxy` and `noProxy` when installing or upgrading rancher

An example of the Helm command for installing Rancher:
```
helm upgrade --install rancher rancher-latest/rancher \
   --namespace cattle-system \
   --version v2.6.4 \
   --set rancherImage=jq20/rancher \
   --set rancherImageTag=v2.6.5-rc1 \
   --set 'extraEnv[0].name=CATTLE_SERVER_VERSION' \
   --set 'extraEnv[0].value=v2.6.4' \
   --set 'extraEnv[1].name=CATTLE_AGENT_IMAGE' \
   --set 'extraEnv[1].value=rancher/rancher-agent:v2.6.4' \
   --set replicas=1 \
   --set additionalTrustedCAs=true \
   --set hostname=jiaqi-ha-2d984911c9b4d44f.elb.us-west-1.amazonaws.com \
   --set proxy=ec2-3-101-129-192.us-west-1.compute.amazonaws.com:4128 \
   --set debug=true \
   --set noProxy="127.0.0.0/8\,cattle-system.svc\,.svc\,.cluster.local\,10.0.0.0/8\,172.31.100.0/24"
```

 note that in my case:
- I am using a customized rancher image, so I have to set some extra options and env vars 
- the CIDR of nodes' private happens to be `172.31.100.0/24` 
- the HTTPS proxy runs at `ec2-3-101-129-192.us-west-1.compute.amazonaws.com:4128` 
- the HTTP proxy runs at `ec2-3-101-129-192.us-west-1.compute.amazonaws.com:3128`


Since Rancher uses the proxy in two steps: 
- step 1: when establishing the SSH connection to the node
- step 2: when validating the certificates in the node

The goal of the tests is to see if both steps are passed when provisioning a cluster.  

### expected results

 Which Proxy is used | if `noProxy` contains the CIDR of the node | expected results
-------------------- | --------------------------------------------| --------
HTTPS proxy            | no      | step 1 passed, step 2 fails
HTTPS proxy            | yes    | both steps passed  
HTTP proxy              | no      |  both steps passed  
HTTP proxy              | yes    | both steps passed  


#  What areas could experience regressions?

we need to confirm that when rancher is behind a proxy, we still are able to provision a node-driver cluster in which nodes have public IP and access to the internet 

#  Are the repro steps accurate/minimal?

Yes. Please reach out to me if you need help with setting up the testing environment

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 7db4fe4
Rancher cluster type: k3s
Docker version: 20.10

Downstream cluster type: EC2 node driver

----------

### Testing: ###

Tested this issue with the steps given in the previous comment.

**Result** - Pass

Since Rancher uses the proxy in two steps:

step 1: when establishing the SSH connection to the node
step 2: when validating the certificates in the node
The goal of the tests is to see if both steps are passed when provisioning a cluster.

| Which Proxy is used  | if noProxy contains the CIDR of the node    | expected results  | actual results  |
| ------------------------ | ------------------------------------------------- | -------------------- | ---------------- |
| HTTPS proxy	| no| 	step 1 passed, step 2 fails|  	step 1 passed, step 2 fails|
| HTTPS proxy	| yes |	both steps passed | both steps passed |
| HTTP proxy |	no	| both steps passed | both steps passed |
| HTTP proxy |	yes	| both steps passed | both steps passed |

**Comment by jandunk** [comment]
The introduction of the PROXY feature for SSH has cost me quite a big headache. I'm running Rancher 2.6.4 behind a HTTP proxy. When upgrading no issues were found. Only after trying to deploy a new cluster a while later I ran into this. I have now manually replaced the Rancher machine version to the latest release and it seems to respect my NO_PROXY values  now.
