### ISSUE TITLE
Clusters stuck in deletion. Cannot remove Mgmt Clusters

### ISSUE THREAD

**Issue by NosIreland** [rancher/rancher#37300]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2

**Information about the Cluster**
- Kubernetes version: v1.21.7+rke2r2, v1.21.9+rke2r1
- Cluster Type (Local/Downstream): bare-metal, custome RKE2 deployemend through Rancher
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom

**User Information**
- What is the role of the user logged in? Admin

   
**Describe the bug**
2 old clusters were deleted from Rancher usinf UI but they are stuck now and cannot be removed.
One is showing as Unavailable and the other as Removing
![image](https://user-images.githubusercontent.com/19308746/163152754-c4b99085-463b-4744-a260-648760bb68bb.png)
`kubectl get clusters.management.cattle.io` is also still showing cluters
```
NAME           AGE
c-m-55k5657w   112d
c-m-8842h9bd   7d20h
c-m-jn5wmcmh   113d <---
c-m-pl4sqt5l   9d
c-m-tn8r2fgt   7d21h
c-m-wqjv8wlk   35d <---
c-m-z7f4p2w6   5d15h
local          207d
```

**To Reproduce**
This is hard to reproduce as it happend on 2 clusters and there were multiple clusters deleted but only these 2 are stuck.

**Result**

**Expected Result**
Cluster is fully deleted

**Screenshots**

**Additional context**
Since theses cluster were replaced with new clusters with the same name the Mgmt Clsuter resource is showing up on these new clusters. But again it cannot be deleted
![image](https://user-images.githubusercontent.com/19308746/163153659-a72728e8-6a2a-4167-b0b6-057654323e4b.png)

There are similar issues logged:
https://github.com/rancher/rancher/issues/36798
https://github.com/rancher/rancher/issues/35018
I tried workarround from 35018 but got error:
```
kubectl patch clusters.management.cattle.io ${c-m-jn5wmcmh} -p '{"metadata":{"finalizers":null}}' --type=merge1
Error from server (NotFound): clusters.management.cattle.io "m-jn5wmcmh" not found
```

**Comment by dmpe** [comment]
Can also confirm. There is no way, if cluster is stuck in UI, to remove it.
