### ISSUE TITLE
Rancher webhook issue

### ISSUE THREAD

**Issue by Zoli8501** [rancher/rancher#37302]
I have some issues with Webhook, maybe someone can help me out with this...

In Rancher 2.5.12 user permissions can not be changed or new user can not be created, Rancher upgrade is also not possible, 
tried to upgrade Kubernetes successfully to v1.19.16, but issue still exist.

Error: Error deleting
Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": context deadline exceeded

In some clusters the cluster agent is not able to connect to proxy randomly. ( one time it's connect one time it's not )

**Comment by excme** [comment]
Same problem

**Comment by quoc9x** [comment]
This solved the problem for me.
https://stackoverflow.com/questions/72499287/error-creating-new-user-or-granting-for-user-permissions-on-rancher/73196918#73196918
