### ISSUE TITLE
proxy service

### ISSUE THREAD

**Issue by opichon** [rancher/rancher#3731]
I am running a wordpress stack as per the sample in the docs. The wordpress container runs on port 8080, so I can access it via this url: http://my.host.com:8080.

Now I want to make wordpress available via a custom url on port 80, e.g. http://wp.mydomain.com[:80].

Using a Load Balancer does not quite work. Entering http://wp.mydomain.com in the browser redirects to http://wp.mydomain.com:8080. It does get me wordpress, but the port is changed.

I guess what I require is more of a proxy than a LB, although a LB is sometimes used for that purpose.

Am I missing something about the way LBs work in rancher, or is there some way to implement a proxy, or is there any other way to achieve waht I want to do?.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.1` Cattle: `v0.148.1` UI: `v0.90.0` |
|Access|`github` `admin`|
|Route|`null`|

**Comment by vincent99** [comment]
The balancer is working fine, and has nothing really to do with this issue.

WordPress has the URL it's expecting in it's config and redirects (to :8080 in this case) when the request isn't to that URL.  So you need to change the Wordpress config with something like  https://www.namecheap.com/support/knowledgebase/article.aspx/9201/2187/how-to-change-wordpress-site-address-url

**Comment by opichon** [comment]
Thanks, this works indeed.
