### ISSUE TITLE
vSphere CPI Support for both 1.23 and 1.24 skew policy.

### ISSUE THREAD

**Issue by phillipsj** [rancher/rancher#37319]
**Is your feature request related to a problem? Please describe.**

 vSphere CPI chart just released an official image for 1.23, 1.23.0. This will need to be implemented in our charts to bring in official 1.23 support and provide skew policy support for 1.24.

**Describe the solution you'd like**

Update the chart to include the new version and tweak the semver ranges.

# Checklist for items that need completed

- [x] Update Image-mirror repo
- [x] Update manifests in rancher/vsphere-charts
- [x] Notify about chart "release"
- [x] Update chart in rancher/charts
- [x] Update chart in rancher/rke2-charts
- [x] Updated RKE2 to consume new chart

**Comment by slickwarren** [comment]
Test plan, p0 checks: 
* do the following for rke1, rke2:
  * fresh install checks - do the following with 1.23, 1.24:
    * install cpi, csi charts (for rke2, this is done when creating the cluster)
    * verify that chart version installed has the k8s version skew policy
    * deploy and use a storage class
  * upgrade checks -- do the following using 1.22, 1.23 nodes:
    * do same steps in fresh install checks above
    * upgrade k8s to the next version
    * verify there is no upgrade available for the charts and that the skew policy is applied
    * verify existing storage class is working properly
    * deploy and use a new storage class

note: rke2 upgrade + fresh install checks were already done on the last KDM release for 1.23: https://github.com/rancher/rancher/issues/37840#issuecomment-1145372010

**Comment by rishabhmsra** [comment]
Validated RKE1 checks on rancher v2.6-head(772b2f0)

Fresh install checks - PASS
- Provisioned a vSphere node driver, k8s v1.23.7-rancher1-1 cluster.
- Installed CPI chart version `100.4.0+up1.2.2` and validated `cloudControllerManager` image was set to `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.23.0`
- Installed CSI chart version `100.3.0+up2.5.1-rancher1`
- Successfully deployed workloads with storage. PVs, PVCs got created successfully.

Upgrade checks - PASS
- Provisioned a vSphere node driver, k8s v1.22.10-rancher1-1 cluster.
- Installed CPI chart version `100.4.0+up1.2.2` and validated `cloudControllerManager` image was set to `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.22.6`
- Installed CSI chart version `100.3.0+up2.5.1-rancher1`
- Successfully deployed workloads with storage. PVs, PVCs got created successfully.
- Upgraded the cluster from v1.22 to v1.23.7-rancher1-1.
- Validated and the chart upgrade were not available.
- Validate the existing storage class.
- Successfully deployed workloads with storage. PVs, PVCs got created successfully.

**Comment by sowmyav27** [comment]
Moving this to-test until 1.24 k8s changes are available in rancher.
