### ISSUE TITLE
Remove Logging v1

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#37318]
Logging v1 was deprecated in 2.5.0, and therefore will be EOL as of 2.7.0. It should be removed/disabled.

SURE-5273

**Comment by vivek-infracloud** [comment]
**Tested the CIS benchmark chart removal as follows.**

Test steps

1. Create a rancher server v2.6.8 that supports v1 charts.
2. Provisioned a k8s cluster v1.20 that supports v1 charts.
3. Installed a V1 logging chart.
4. Made sure the charts are working as expected.
5. Upgraded to rancher server v2.7.0-rc3.
6. After upgrade the Logging chart was not manageable. 
7. Removed the V1 logging chart.
8. Made sure the V1 logging chart is not installable after removal.
9. V2 logging chart could be install and was working as expected.
10. Deployed a pod for sanity check.

Based on above testing the issue could be closed.
