### ISSUE TITLE
v2.6.5 Release Task - Release RKE

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#37320]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/37315) for the rancher engineering team 2 and the Release Captain to:

- [x] Release RKE and update the RKE Tag in Rancher.

**Comment by superseb** [comment]
https://github.com/rancher/rke/releases/tag/v1.3.11
