### ISSUE TITLE
Remove Alerts and Notifiers v1

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#37328]
Alerts and Notifiers v1 was deprecated in 2.5.0, and therefore will be EOL as of 2.7.0. It should be removed/disabled.

**Comment by MKlimuszka** [comment]
https://github.com/rancher/rancher/pull/43536

**Comment by MKlimuszka** [comment]
https://github.com/rancher/rancher/pull/44211 is the PR for this.

**Comment by MKlimuszka** [comment]
Followup testing: make sure there are no errors in the logs, and that the rest of the legacy UI still works as expected.

**Comment by pankajsqe** [comment]
Retest Pass : Alerts and Notifiers v1 are removed from rancher ui. 
I see there are no error and rancher ui works as expected.

Rancher v2.7.11-rc3 and v2.8.2
