### ISSUE TITLE
Remove Istio v1

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#37327]
Istio v1 was deprecated in 2.5.0, and therefore will be EOL as of 2.7.0. It should be removed/disabled.

**Comment by SheilaghM** [comment]
Chart is already hidden so that it cannot be used.  When we work on 2.7 we can remove the entire v1 catalog.  Longhorn is the only team with a chart still available.

**Comment by vivek-infracloud** [comment]
Istio v1 chart is still working on rancher v2.7-head. This is not accepted behaviour. v1 Istio chart should not work on rancher v2.7-head.

**Comment by vivek-infracloud** [comment]
Tested the CIS benchmark chart removal as follows.

Tested the current issue with following steps.

1. Create a rancher server v2.6.8 that supports v1 charts.
2. Provision a k8s cluster that supports v1 charts.
3. Enabled the Legacy feature from Global Settings.
4. Enabled V1 monitoring and Istio charts from Cluster Tools.
5. Made sure the charts are working as expected.
6. Upgrade to rancher server v2.7.0-rc3.
7. Istio was still working after upgrade.
8. Disabled only the istio chart from Cluster Tools. Istio was disabled successfully.
9. Tried disabling the monitoring but the didn't work, Saw the following message while trying to disable the Monitoring chart.
![Screenshot from 2022-10-04 18-08-03](https://user-images.githubusercontent.com/83208989/193823461-24ff7129-b9b3-4057-ae7d-3b9c9ffdda93.png)


10. As expected, the re-enabling of istio was not possible, saw the following error.
![Screenshot from 2022-10-04 17-35-58](https://user-images.githubusercontent.com/83208989/193823529-8a1b2942-92f7-4c8e-b0d0-2eaa223fd598.png)

11. Istio V2 chart  was not visible in the Apps.
![Screenshot from 2022-10-04 18-08-32](https://user-images.githubusercontent.com/83208989/193823391-73123dd5-5233-4fad-bd84-d645cb99c83f.png)

Removal of Istio v1 chart is still not working as per expectation.
