### ISSUE TITLE
Remove CIS 1.4 Scanner

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#37322]
CIS 1.4 was deprecated in 2.5.0, and therefore will be EOL as of 2.7.0. It should be removed/disabled.

**Comment by dhruvmewada15** [comment]
Hi @cbron Can you please provide more details for this issue?
Is it for v1 charts or v2? and In which rancher-cis-benchmark chart version it is reproducable?

**Comment by cbron** [comment]
All the deprecations are for v1 charts, listed here: https://github.com/rancher/rancher/releases/tag/v2.5.0

**Comment by vivek-infracloud** [comment]
**Tested the CIS benchmark chart removal as follows.**

Test steps

1. Create a rancher server that supports v1 charts.
2. Provision a k8s cluster that supports v1 charts.
3. Install CIS Benchmark and monitoring chart.
4. Made sure the charts are working as expected.
5. Verified the CIS scans under the legacy option are working.
6. Upgrade to rancher server v2.7-head.
7. Made sure the use is not allowed to run the CIS scans, but the non-removed chart (monitoring) is working.
8. Installed v2 CIS benchmark chart on cluster and made sure scans are working fine.
9. Made sure the upgraded rancher server is working normally and all the pods are up.
10. Deployed a pod for sanity check.

**Comment by vivek-infracloud** [comment]
Based on validations above, closing the issue.
