### ISSUE TITLE
v2.6.5 Release Task - Charts: Align Rancher internal operators to correct version.

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#37323]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/37315) for the rancher engineering team 3 to:

- [ ] Make appropriate updates to the ENV vars in the rancher/rancher/package/Dockerfile

**Comment by superseb** [comment]
Done with final RC check
