### ISSUE TITLE
Kubeconfig from UI contains a`&#43;` in the certificate-authority-data

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#37325]
**BUG**  
**Steps to reproduce (least amount of steps as possible):**  

When a CA Certificate with Bag attribute is registered in Rancher like so:  
```
Bag Attributes
    localKeyID: 61 F8 B1 93 5F A2 C1 10 4A 47 37 AD 53 2E C8 17 E7 69 89 1A
subject=O = mkcert development CA, OU = MyOU, CN = mkcert mylittlecn

issuer=O = mkcert development CA, OU = MyOU, CN = mkcert mylittlecn

-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
```
This certificate output often comes from a conversion from PKCS12 to PEM.
`openssl pkcs12 -in CA.pfx -clcerts -nokeys -out certificate.pem`

These certificates once encoded contains a `+` in their base64 version.
These `+` signs are converted to `&#43;` when downloading the kubeconfig file from the UI  

_Not sure if this output is invalid form or if we should take care of this version._

**Result:**
It is not usable with `kubectl` and need manual editing to replace `&#43;` with `+`

**Workaround**
Removing everything above `-----BEGIN CERTIFICATE-----` fixes the issue.

**Environment information**
- Rancher version: 2.5.x

gz#16418
gz#15054

**Comment by gaktive** [comment]
@Jono-SUSE-Rancher I transferred this over from rancher/dashboard. I'll leave the 2.6.5 milestone for now but if it's not doable for that, I know this has been open for a while so I'll defer to whoever tackles this about realistic delivery.

**Comment by snasovich** [comment]
Moving to Blocked as this was triaged about a month ago and we're waiting input from support / customer.
> It looks like the issue happens because the private CA certs passed when installing Rancher contain those extra attributes that show in the ca-cert in the kubeconfig file.

**Comment by Sahota1225** [comment]
Closing this issue based on Daniel Bravo's comment that the workaround works for the customer

**Comment by snasovich** [comment]
More information on the solution that worked:

> Can you try to edit your CA chain and replace it with the same without :
> * Bag Attributes
> * Subject
> * Issuer
> 
> Just combine your Root and Intermediate CA like so:
> ```
> -----BEGIN CERTIFICATE-----
> [Intermediate DATA]
> -----END CERTIFICATE-----
> -----BEGIN CERTIFICATE-----
> [RootCA]
> -----END CERTIFICATE-----
> ```
