### ISSUE TITLE
Remove Pipelines

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#37324]
Pipelines were deprecated in 2.5.0, and therefore will be EOL as of 2.7.0. It should be removed/disabled.

**Comment by cbron** [comment]
All these "Remove" issues should also take into account docs, and other areas that reference them. For instance, pipelines have their own docs page, but they are also referenced in other places, such as the tokens page: https://rancher.com/docs/rancher/v2.6/en/api/api-tokens/

**Comment by vivek-infracloud** [comment]
Based on validations above, closing the issue.
