### ISSUE TITLE
v2.6.5 Release Task - Branch Repos If Needed

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#37330]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/37315) for the rancher engineering release captain to:

- [ ] Branch appropriately if there is a new minor version for Rancher, or identify if a specific release (v/x.y.x) branch might be needed.

**Comment by superseb** [comment]
Guess we are not doing this, or already happened for where it was needed.
