### ISSUE TITLE
v2.6.5 Release Task - Merge PR for KDM, Feature-Charts and System-Charts

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#37331]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/37315) for the rancher engineering team 3 & the Release captain to:

- [ ] Merge the PRs for KDM, Feature-Charts, and System-Charts

**Comment by SheilaghM** [comment]
Finished 11 May 2022
