### ISSUE TITLE
Host registration url is not generated when "Add Host" for custom is launched for the first time.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3733]
Rancher Version: v0.61.0-rc3

Docker Version:10.1.

OS: Ros - v0.4.4-dev-2

Steps to Reproduce: On fresh install of rancher-server , launch "Add Host" for custom.
Notice that UI is stuck when generating the registration url. When this page is relaunched , registration url shows up as expected.

<img width="711" alt="screen shot 2016-03-01 at 2 11 51 pm" src="https://cloud.githubusercontent.com/assets/4266958/13443791/9c596f4e-dfb7-11e5-9bc4-cc5bd22577bb.png">

**Comment by vincent99** [comment]
This was broken by changes to only connect to the subscribe socket when in a `/env/1aX/...` URL, which was a bad idea.  So yeah, now it stays connected more.

**Comment by tfiduccia** [comment]
Version - master 3/2
Verified fixed
