### ISSUE TITLE
v2.6.5 Release Task - Tag a Final RC with All Versions Set

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#37339]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/37315) for the Release Captain:

- [ ] Once sent to QA, wait for final confirmation and validation.

**Comment by superseb** [comment]
https://github.com/rancher/rancher/pull/37706
