### ISSUE TITLE
v2.6.5 Release Task - Update the final PR in the system-charts branch

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#37336]
**Rancher Backend Engineering Task**
This is a Rancher backend engineering task for (https://github.com/rancher/rancher/issues/37315) for the rancher engineering team 3 and the Release Captain:

- [x] For the system-charts branch: Update the charts branch in rancher/rancher from dev-2.6x to release-v2.6x

**Comment by PennyScissors** [comment]
@superseb completed this task [here](https://github.com/rancher/rancher/pull/37706)
