### ISSUE TITLE
v2.6.5 Support Matrix checks - Validate installing Rancher, Downstream clusters listed in the support matrix 2.6.5

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#37347]
On latest 2.6-head or latest 2.6.5 -rc
---
### Deploy Rancher on these(Hosted clusters) clusters (Using HA jenkins)
- Deploy a downstream cluster with the following cluster types (Can be downstream node driver RKE1 cluster with default k8s version)
- Run v3_need cluster on the downstream cluster

Local Cluster Type | Cluster k8s version | Downstream cluster Type | Downstream cluster version | Status
-- | -- | -- | --| --
AKS | TBD | RKE1 | TBD | **Passed**
GKE | TBD | RKE1 | TBD | **Passed**
EKS | TBD| RKE1 | TBD | **Passed**

---
Start date - Post Bug complete date - TBD
Due by - TBD

**Comment by sowmyav27** [comment]
Dup of https://github.com/rancher/qa-tasks/issues/312
