### ISSUE TITLE
Adding labels for stack and stack_service only creates stacks on "hosts" page.

### ISSUE THREAD

**Issue by jonpugh** [rancher/rancher#3734]
Rancher	v0.59.1
Cattle	v0.148.1
User Interface	v0.90.0
Rancher Compose	v0.7.2

Docker version 1.10.2, build c3959b1
docker-compose version 1.6.2, build 4d72027

Steps to Reproduce: 

1. Using the `docker` cli, launch a container with the "io.rancher.stack.name" and "io.rancher.stack_service.name"
2. View the "host" widget, you will see a "stack" group for your container.
3. Visit the "Applications" page, you will see not see that stack listed.

![screenshot from 2016-03-01 21 23 57](https://cloud.githubusercontent.com/assets/106420/13448876/6c8fa03e-dff4-11e5-8aaf-41681082ff41.png)

**Comment by vincent99** [comment]
The hosts UI reads that label and uses it to group containers, but setting it does not cause the container to actually be a service.  You need to use rancher-compose to create services.
