### ISSUE TITLE
Request: Rancher event when load balancer is finished reloading

### ISSUE THREAD

**Issue by joshuakarjala** [rancher/rancher#3735]
After updating a load balancer with 'addServiceLink' (or remove) I want to receive a notification (rancher event) when HAProxy has reloaded with the new configuration and is no longer in risk of dropping connections.

Example use case:
https://forums.rancher.com/t/notification-when-haproxy-has-reloaded/1833

**Comment by deniseschannon** [comment]
This is a duplicate and covered in our events and alerts request in https://github.com/rancher/rancher/issues/3735
