### ISSUE TITLE
remove Conteners from UI

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#3736]
Rancher Version:v0.59.1

Docker Version: 1.7.1 and 1.9.1

OS: CentOS 6.6 and CentOS 7

Steps to Reproduce:
1) create and start Stack from Sysdig (or sysdig-cloud version) in Library
2) remove Stack

Results: all containers are removed, but the user interface I see multiple servers hovering disposal container, but no Contener on the server, as in the Rancher was the problem that tried to remove these containers, I brushed rancher database from these Contener UI but they hang-bank (Sorry for bad english)

Expected:How to remove the names of the UI

![screenshot 54](https://cloud.githubusercontent.com/assets/4653589/13467280/5f0c29a2-e0bf-11e5-8ddf-c7c49d847e46.png)

**Comment by deniseschannon** [comment]
When containers are in a purged state, they will be removed from the UI. If you click on refresh, it would be removed.

I've just tested this out with v0.59.1 and had no issues with the containers being removed from the UI.

**Comment by Negashev** [comment]
@deniseschannon I know that, and therefore wrote the question, because it does not meet with this problem for half a year of operation Rancher.
For me it is a novelty, but can anyone met this problem

**Comment by Negashev** [comment]
I remove all, from DB by id
