### ISSUE TITLE
Unable to use both chart values "useBundledSystemChart=true" with "proxy"

### ISSUE THREAD

**Issue by arnicel** [rancher/rancher#37368]
When specify _useBundledSystemChart=true_ and a _proxy_ value in Rancher charts, Rancher seem to skip _useBundledSystemChart_ and use remote system chart.
I want to install Rancher Air gapped, but with a specified proxy. My proxy doesn't have access to internet, it is only use to access remote local services.

**Rancher Server Setup**
- Rancher version: v2.6.4
- Installation option (Docker install/Helm Chart): Helm chart latest: _rancher-2.6.4_
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 v1.21.5+rke2r1
- Proxy/Cert Details: Proxy without access to internet/Auto-generated cert by Rancher

**Information about the Cluster**
- Kubernetes version: v1.21.5
- Cluster Type (Local/Downstream): local
   
**To Reproduce**
 
`
helm upgrade --install rancher rancher-latest/rancher \
   --namespace cattle-system \
   --set replicas=1 \
   --set debug=true \
   --set useBundledSystemChart=true \
   --set certmanager.version=1.7.1 \
   --set systemDefaultRegistry=dockerproxy.example.com \
   --set hostname=rancher-vip.exemple.com \
   --set rancherImage=dockerproxy.example.com/rancher/rancher \
   --set proxy=http://proxy-without-inet.example.com:3128 \
   --set noProxy=127.0.0.0/8\\,10.0.0.0/8\\,cattle-system.svc\\,172.16.0.0/12\\,192.168.0.0/16\\,.svc\\,.cluster.local
`

**Result**
![image](https://user-images.githubusercontent.com/23292338/163572023-6c03da46-0439-4e34-9bb8-16581e25567d.png)
No error is printed in pod logs but the pod is not complety ready. So the pod doesn't anwser on port 80.
According to the request send to the proxy, Rancher try to get system chart by contacting _releases.rancher.com_.
![image](https://user-images.githubusercontent.com/23292338/163572582-ab1bca68-0e44-457c-8402-b8d4e73cd0fe.png)

**Expected Result**

Rancher should not try to contact _releases.rancher.com_ and instead using bundled system chart.

**Comment by rajivml** [comment]
@arnicel how did you manage to fix this ? we are also running into a similar issue

**Comment by arnicel** [comment]
Actually, I don't resolve the issue. But reading the documentation, it seems that _useBundledSystemChart_ and _proxy_ is not meant to be used together. Because _useBundledSystemChart_ is only used in air gapped environment.
I think this issue must be concidered as a **feature request** more than a real bug.

I close the issue because of the behavior of my proxy. When defining _useBundledSystemChart_ and proxy option, Rancher still tries to connect to _releases.rancher.com_ BUT if it fails, Rancher will when use the bundle system chart. The problem in my proxy configuration is that the HTTP CONNECT to _releases.rancher.com_ will fail after a timeout of 10min (because my proxy can't access internet and I don't know what is he waiting for). This means that my Rancher pod will wait 10min before using the bundled system chart.
In Kubernetes, the startup probes of Rancher pod are defined to start in less than 2 min. So, in my case my Rancher deployment was never ready because my proxy doesn't answer quickly enough.

- If your proxy timeout or fail the HTTP CONNECT in less than 2 min, Rancher should start correctly.
- If you add _releases.rancher.com_ to the NO_PROXY, the timeout connection should appear more quickly because Linux Kernel will timeout quicker. The DNS resolution will fail or the public IP can't be routed.
