### ISSUE TITLE
Search paths not populated in container resolv.conf

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#3737]
Rancher Version:
v0.59.1
Docker Version:
1.10.2
OS: 
Ubuntu 14.04.4 LTS

Steps to Reproduce: 
1. Add a new Digital Ocean Host  (has Docker 1.10.2 preinstalled)
2. Add a new service (e.g. using `redis:3.0` image) to that host
3. Start the service and execute a shell
4. Issue the command `cat /etc/resolv.conf`

Results: 

```TEXT
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)  
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN         
# nameserver 8.8.8.8                                                            
# nameserver 8.8.4.4                                                            
nameserver 169.254.169.250
```

Expected:

```TEXT
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)  
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN         
# nameserver 8.8.8.8                                                            
# nameserver 8.8.4.4                                                            
# nameserver 213.186.33.99                                                      
search local rancher.internal                                                   
nameserver 169.254.169.250  
```

**Comment by alena1108** [comment]
@janeczku this PR added support for adding rancher-internal domain to search section:

https://github.com/rancher/host-api/pull/58

**Comment by janeczku** [comment]
A bit confused what this PR is supposed to do. Right now even without this patch the search domains get added to resolv.conf on my Docker v1.9 hosts as they always have. Just not on the Docker v1.10 hosts.

**Comment by alena1108** [comment]
@janeczku before the fix, rancher.internal was added to the search path only when the search path wasn't empty - I see you have "local" prepended, it might have been pre-set somewhere (through search domain, or may be automatically by docker 1.9).

With the fix I've mentioned above, default search domains - rancher-internal is one of them - is being set no matter if the search already had been set with some initial values.

I've tested it on latest Rancher RC and docker 1.10.2 for redis:3.0 image. Search domain is set to:

```
search default.rancher.internal redis.default.rancher.internal rancher.internal
```
first 2 domains are service's/stack's namespaces.

**Comment by janeczku** [comment]
> before the fix, rancher.internal was added to the search path only when the search path wasn't empty

Oh that explains it! The Digital Ocean hosts indeed don't have any search prefix preconfigured. Thanks for the clear up - i'd never have guessed this to have caused it.

**Comment by sangeethah** [comment]
Tested with latest build from master:

1. Add a new Digital Ocean Host (has Docker 1.10.2 preinstalled)
2. Add a new service (e.g. using redis:3.0 image) to that host
3. Start the service and execute a shell
4. Issue the command cat /etc/resolv.conf

<img width="905" alt="screen shot 2016-03-07 at 2 00 59 pm" src="https://cloud.githubusercontent.com/assets/4266958/13584836/1eeb427a-e46d-11e5-91ce-0a19577c5db5.png">


I see rancher.internal being appended to the search path.

**Comment by pengfei-xue** [comment]
seems like this pr caused another bug, container's resolv.conf will be flushed periodically even container's resolv.conf is not empty.
