### ISSUE TITLE
Adds NeuVector chart

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#37377]

**Comment by anupama2501** [comment]
Validated test cases on v2.6-head a478def

Use case | Result | Any related GH issue/comments |
-- | -- | -- | 
 Local Cluster as admin | PASS | ||
Downstream/Custom RKE1 node driver as an admin | Fail |  https://github.com/rancher/rancher/issues/37400 ||
Uninstall neuvector chart  | PASS |   ||
Uninstall and re-install neuvector app | PASS |  ||
Enable AWS cloud provider  | PASS |   ||
Update neuvector app  | PASS |   ||
Enable PVC configuration | PASS | <img width="300" alt="nvpvc" src="https://user-images.githubusercontent.com/38144301/164836506-fde3dc42-d827-4f1b-89e9-839074ccbb87.png">||
v1.23  | PASS |  ||
v1.22   |PASS |    ||
 v1.21 | PASS |   ||
 v1.20 | PASS |   ||
v1.19  |PASS  |   ||
Docker installation |PASS |   ||
Restricted Admin local auth | PASS |   ||
Restricted Admin auth openLDAP  |PASS  |   ||
OpenLDAP with openldap users as cluster owners added in the cluster c1   | PASS|    ||
OpenLDAP with nested groups as cluster owners added in the cluster c1  |  PASS|   ||
oauth  |PASS |  ||
Rancher local cluster Proxy | PASS |   ||
Downstream cluster proxy| PASS |   ||
Backup/restore on same cluster  |PASS|||   
RKE2 nodedriver/custom clusters  | PASS |   ||
Hosted clusters - AKS  |  PASS|   ||
Imported k3s  | PASS|   ||
Imported RKE2 clusters  | PASS |   ||
Imported RKE1 clusters  |PASS |  ||
Windows  | PASS|<img width="1024" alt="nvwin" src="https://user-images.githubusercontent.com/38144301/164836450-78d3236e-d9d5-40f9-9b81-87d720ce2def.png">   ||
 Neuvector installed as partner chart | FAIL | https://github.com/rancher/rancher/issues/37447 ||
  Install neuvector chart via terraform | FAIL |  https://github.com/rancher/rancher/issues/37434 ||

**Comment by anupama2501** [comment]
Closing this issue as the tickets for issues seen were logged separately.
