### ISSUE TITLE
Linode LKE driver (0.0.3 and 0.0.4) cannot create a 1.22 cluster

### ISSUE THREAD

**Issue by jaredkipe** [rancher/rancher#37372]
**Rancher Server Setup**
- Rancher version: 2.6.3+ (known error also on 2.6.4)
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): helm
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: v1.21.5-eks-bc4871b (rancher) 
* Hosted = linode lke

**User Information**
- What is the role of the user logged in? Admin

   
**Describe the bug**
Using LKE provider to create a 1.22 version results in "Failed to create LKE cluster: [400][label] Must be unique"
The cluster IS created inside Linode.

**To Reproduce**
Create cluster and wait.

**Result**
Failed to create LKE cluster: [400][label] Must be unique

**Expected Result**
Cluster finished provisioning

**Screenshots**
![Screen Shot 2022-04-13 at 2 14 07 PM](https://user-images.githubusercontent.com/744550/163594643-4dce62bd-02fc-4a41-981f-4e0db48e3fbe.png)

**Additional context**
I initially thought this was a problem that would go away in 2.6.4, but it does not.  Clusters of version 1.23 can be created (and before the option was removed, 1.21 was working).

**Comment by gapgag55** [comment]
Still the same problem. Any updates?
