### ISSUE TITLE
Update Linode LKE driver 0.0.3 -> 0.0.4

### ISSUE THREAD

**Issue by jaredkipe** [rancher/rancher#37373]
**Is your feature request related to a problem? Please describe.**
There is a new release of this driver.  I have personally tested it and can create a 1.23 cluster with it.  (note that I was trying to work around creating a 1.22 cluster in #37372 )

**Describe the solution you'd like**
Simply bump version assuming it passes any tests you have.

**Describe alternatives you've considered**
I guess waiting for 0.0.5?

**Comment by rl0nergan** [comment]
@jaredkipe I'm still waiting on this too, but I did figure out a workaround that might help. If you go to the Cluster Drivers page, you can edit the Linode LKE driver under the actions menu and change the following:

Download URL: https://github.com/linode/kontainer-engine-driver-lke/releases/download/v0.0.4/kontainer-engine-driver-lke-linux-amd64

Checksum: 5609314fe7ff7339a7c8292738d36ccf5a25460f79ca094db72eb6ccf722bc27

I pulled those values from [here](https://github.com/rancher/rancher/blob/0b3e1d7a6c1e102f871d32f52e7bfda9b0d0ab29/pkg/data/management/kontainerdriver_data.go#L105-L106), and once it finished downloading and activating I was able to create LKE clusters on v1.22+

**Comment by gapgag55** [comment]
> @jaredkipe I'm still waiting on this too, but I did figure out a workaround that might help. If you go to the Cluster Drivers page, you can edit the Linode LKE driver under the actions menu and change the following:
> 
> Download URL: https://github.com/linode/kontainer-engine-driver-lke/releases/download/v0.0.4/kontainer-engine-driver-lke-linux-amd64
> 
> Checksum: 5609314fe7ff7339a7c8292738d36ccf5a25460f79ca094db72eb6ccf722bc27
> 
> I pulled those values from [here](https://github.com/rancher/rancher/blob/0b3e1d7a6c1e102f871d32f52e7bfda9b0d0ab29/pkg/data/management/kontainerdriver_data.go#L105-L106), and once it finished downloading and activating I was able to create LKE clusters on v1.22+

It's worked!
