### ISSUE TITLE
New Charts in v2.6.5

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#37376]
### System Charts (v1)  `rancher/system-charts:dev-v2.6`

Name                       | Version           | Note                 | Backend Dev(s) | rancher-max of prev chart
-------------------------------| -------------------------- |----------------------|----------- | ----------- |

No charts to be released in v2.6.5

### Rancher Charts (v1) `rancher/charts:dev`

| Name                     | Version           | Validated | PR              |
| ------------------------ | ----------------- | ------------------- | ------------------- |

No charts to be released in v2.6.5

### Feature Charts (v2) `rancher/charts:dev-v2.6`
| Name                     | Version           | Backend Dev | Notes              |
| ------------------------ | ----------------- | ------------------- | ------------------- |
neuvector|100.0.0+up2.2.0|@selvamt94|#48462 (rancher/rancher#37377)
neuvector-crd|100.0.0+up2.2.0|@selvamt94|#48462 (rancher/rancher#37377)
harvester-cloud-provider|100.0.2+up0.1.12|| 	 
harvester-csi-driver|100.0.2+up0.1.11||	 
prometheus-federator|0.1.0+up0.0.1|| 	 
rancher-aks-operator|100.0.4+up1.0.5|| 	 
rancher-aks-operator-crd|100.0.4+up1.0.5||	 
rancher-backup|2.1.2|| 	 
rancher-backup-crd|2.1.2|| 
rancher-cis-benchmark|2.0.4||
rancher-cis-benchmark-crd|2.0.4||
rancher-gatekeeper	|100.1.0+up3.7.1|| 	 
rancher-gatekeeper-crd|100.1.0+up3.7.1||	 
rancher-istio|100.2.0+up1.12.6|| 	 
rancher-logging|100.1.2+up3.17.4||
rancher-logging-crd|100.1.2+up3.17.4||	 
rancher-vsphere-cpi|100.3.0+up1.2.1||
rancher-vsphere-csi|100.3.0+up2.5.1-rancher1||
sriov|100.0.3+up0.1.0|| 
sriov-crd|100.0.3+up0.1.0|| 	 

See also  [release.yaml](https://github.com/rancher/charts/blob/dev-v2.6/release.yaml) file in `rancher/charts` branch `dev-v2.6` for the most up-to-date list of v2 charts to be released in v2.6.5

*Note: rancher-project-monitoring is a new chart for 2.6.5 but does not need to be explicitly tested since it should be hidden. It has only been added to ensure that we mirror images for air-gapped setups.*

**Comment by anupama2501** [comment]
Neuvector chart has been validated on the version `100.0.0+up2.2.0-b2` as mentioned in this issue https://github.com/rancher/rancher/issues/37377#issuecomment-1107057858

**Comment by aiyengar2** [comment]
Added note about rancher-project-monitoring chart above to indicate that QA does not need to test deploying it onto a cluster since it is hidden. cc: @bmdepesa @sowmyav27

**Comment by PennyScissors** [comment]
> Neuvector chart has been validated on the version `100.0.0+up2.2.0-b2` as mentioned in this issue [#37377 (comment)](https://github.com/rancher/rancher/issues/37377#issuecomment-1107057858) neuvector crd version `100.0.0+up2.2.0-b2`

@cbron @selvamt94 if `-bX` is a pre-release, it needs to be removed before we can move forward with the charts release.

**Comment by selvamt94** [comment]
We will remove b2 and submit a PR today. I am waiting for the Neuvector 2.2.0 helm chart published.

**Comment by prachidamle** [comment]
Corrected `rancher-cis-benchmark` version to 2.0.4

**Comment by izaac** [comment]
Rancher version `v2.6.5-rc11`

These are the chart versions validated with `rancher-images.txt`

Name | Version Validated |  Notes
-- | -- | -- 
neuvector | 100.0.0+up2.2.0-b2 | 
neuvector-crd | 100.0.0+up2.2.0-b2 |  
harvester-cloud-provider | 100.0.2+up0.1.12 |   
harvester-csi-driver | 100.0.2+up0.1.11 |   
prometheus-federator |  |   Pending UnRC https://github.com/rancher/charts/pull/1895
rancher-aks-operator | 100.0.4+up1.0.5 |   
rancher-aks-operator-crd | 100.0.4+up1.0.5 |   
rancher-backup | 2.1.2 |   
rancher-backup-crd | 2.1.2 |   
rancher-cis-benchmark | 2.0.4 |   
rancher-cis-benchmark-crd | 2.0.4 |   
rancher-gatekeeper | 100.1.0+up3.7.1 |   
rancher-gatekeeper-crd | 100.1.0+up3.7.1 |   
rancher-istio | 100.2.0+up1.12.6 |   Release note for 1.10.4 https://github.com/rancher/rancher/issues/37697 checked on 1.22 cluster
rancher-logging | 100.1.2+up3.17.4 |   
rancher-logging-crd | 100.1.2+up3.17.4 |   
rancher-vsphere-cpi | 100.3.0+up1.2.1 |   
rancher-vsphere-csi | 100.3.0+up2.5.1-rancher1 |   
sriov | 100.0.3+up0.1.0 |   
sriov-crd | 100.0.3+up0.1.0 |

**Comment by izaac** [comment]
Rancher version `v2.6.5-rc12`

Pending validation of this chart is now completed
prometheus-federator 0.1.0
