### ISSUE TITLE
Save button on setting is stuck and continuously runs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3738]
Version: Master 3/2

Steps to Reproduce: 
1.  Go to settings and click on Save

Results: Save button never stops running.  Error in dev console: Uncaught TypeError: this.get(...).setProperties(...).one is not a function

Expected: no error and save button to stop running

**Comment by tfiduccia** [comment]
Since setting change this is for Catalog and VM section of the settings page

**Comment by vincent99** [comment]
I think I fixed this last week while adding the Saving.../Saved! status to the buttons.

**Comment by tfiduccia** [comment]
Version - master 3/16
Verified fixed
