### ISSUE TITLE
Helm chart not upgraded to 2.5.13

### ISSUE THREAD

**Issue by wargamez** [rancher/rancher#37393]
Since this is fixing a security issue, perhaps the helm chart should be upgraded to the new version aswell?

**Comment by wargamez** [comment]
any plans to update?

**Comment by gmontalvoy** [comment]
This has been addressed in person at KC EU 22, 
2.5.13 is available in helm now

**Comment by wargamez** [comment]
Confirmed working now. Thanks for the in-person help :)
