### ISSUE TITLE
Issues with Rancher deployment on K3s

### ISSUE THREAD

**Issue by mhill8992** [rancher/rancher#37396]
**Rancher Server Setup**

- Rancher version: latest stable release
- Installation option: Helm Chart
   - If Helm Chart, Kubernetes Cluster and version: k3s
- Proxy/Cert Details: Server is behind a proxy and is using local generated certs
- 
**Information about the Cluster**

- Kubernetes version: 1.22
- Cluster Type (Local/Downstream): Local

**User Information**

- What is the role of the user logged in? Admin
   
**Describe the bug**

I am currently unable to load the web ui. Everything that I checked aside from the below has looked good. I'm relatively new to kubernetes and rancher, so that's not saying too much. Apologies if this isn't the place for help.

When I run `kubectl -n cattle-system logs -l app=rancher` I get the below:

2022/04/19 14:50:47 [ERROR] Failed to connect to peer wss://10.42.0.49/v3/connect [local ID=10.42.1.42]: dial tcp 10.42.0.49:443: i/o timeout
2022/04/19 14:50:49 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
fatal: unable to access 'https://git.rancher.io/charts/': Could not resolve proxy: PROXY
: exit status 128, requeuing
2022/04/19 14:50:49 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/6bda4fa402575032915dc735ad66131a2f8a36ff38c6fb593402ad315fbfdf85'...
fatal: unable to access 'https://git.rancher.io/system-charts/': Could not resolve proxy: PROXY
: exit status 128, requeuing
2022/04/19 14:50:49 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
fatal: unable to access 'https://git.rancher.io/helm3-charts/': Could not resolve proxy: PROXY
: exit status 128, requeuing
2022/04/19 14:50:17 [ERROR] Failed to connect to peer wss://10.42.0.49/v3/connect [local ID=10.42.1.43]: dial tcp 10.42.0.49:443: i/o timeout
W0419 14:50:20.785519      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
2022/04/19 14:50:32 [ERROR] Failed to connect to peer wss://10.42.0.49/v3/connect [local ID=10.42.1.43]: dial tcp 10.42.0.49:443: i/o timeout
2022/04/19 14:50:34 [ERROR] error syncing 'rancher-partner-charts': handler helm-clusterrepo-ensure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974 fetch origin 7180f186b72b553dcab880740f5f45429c2b7502 error: exit status 128, detail: fatal: unable to access 'https://git.rancher.io/partner-charts/': Could not resolve proxy: PROXY
, requeuing
2022/04/19 14:50:36 [ERROR] error syncing 'rancher-rke2-charts': handler helm-clusterrepo-ensure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9 fetch origin e32a39e914ed22d695a571a2401deb084988aa00 error: exit status 128, detail: fatal: unable to access 'https://git.rancher.io/rke2-charts/': Could not resolve proxy: PROXY
, requeuing
2022/04/19 14:50:47 [ERROR] Failed to connect to peer wss://10.42.0.49/v3/connect [local ID=10.42.1.43]: dial tcp 10.42.0.49:443: i/o timeout
2022/04/19 14:50:54 [ERROR] error syncing 'rancher-partner-charts': handler helm-clusterrepo-ensure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974 fetch origin 7180f186b72b553dcab880740f5f45429c2b7502 error: exit status 128, detail: fatal: unable to access 'https://git.rancher.io/partner-charts/': Could not resolve proxy: PROXY
, requeuing
2022/04/19 14:49:54 [ERROR] Failed to connect to peer wss://10.42.1.42/v3/connect [local ID=10.42.0.49]: dial tcp 10.42.1.42:443: i/o timeout
2022/04/19 14:49:54 [ERROR] Failed to connect to peer wss://10.42.1.43/v3/connect [local ID=10.42.0.49]: dial tcp 10.42.1.43:443: i/o timeout
2022/04/19 14:50:09 [ERROR] Failed to connect to peer wss://10.42.1.42/v3/connect [local ID=10.42.0.49]: dial tcp 10.42.1.42:443: i/o timeout
2022/04/19 14:50:09 [ERROR] Failed to connect to peer wss://10.42.1.43/v3/connect [local ID=10.42.0.49]: dial tcp 10.42.1.43:443: i/o timeout
2022/04/19 14:50:24 [ERROR] Failed to connect to peer wss://10.42.1.43/v3/connect [local ID=10.42.0.49]: dial tcp 10.42.1.43:443: i/o timeout
2022/04/19 14:50:24 [ERROR] Failed to connect to peer wss://10.42.1.42/v3/connect [local ID=10.42.0.49]: dial tcp 10.42.1.42:443: i/o timeout
2022/04/19 14:50:39 [ERROR] Failed to connect to peer wss://10.42.1.43/v3/connect [local ID=10.42.0.49]: dial tcp 10.42.1.43:443: i/o timeout
2022/04/19 14:50:39 [ERROR] Failed to connect to peer wss://10.42.1.42/v3/connect [local ID=10.42.0.49]: dial tcp 10.42.1.42:443: i/o timeout
2022/04/19 14:50:54 [ERROR] Failed to connect to peer wss://10.42.1.43/v3/connect [local ID=10.42.0.49]: dial tcp 10.42.1.43:443: i/o timeout
2022/04/19 14:50:54 [ERROR] Failed to connect to peer wss://10.42.1.42/v3/connect [local ID=10.42.0.49]: dial tcp 10.42.1.42:443: i/o timeout

**To Reproduce**

I have tried reloading the server  with `helm upgrade --install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher-01.mg.qservco.com --set bootstrapPassword=0nly$Metronet --set proxy="http://qsc-proxy-02.ad.qservco.com:8080" --set noProxy="127.0.0.0/8\,10.42.0.0/16\,10.43.0.0/16\,172.16.0.0/12\,.svc\,.cluster.local\,172.20.0.0/16`

**Result**
Same issue persisting

**Expected Result**
To be able to login to the UI

**Screenshots**
This is what the initial login page loads. It also will say "gateway timeout" if I try to reload the page.
![image](https://user-images.githubusercontent.com/92887201/164040798-2c12e13a-5cfa-4362-a1f4-faadbd1544eb.png)

**Comment by martindahlswe** [comment]
@mhill8992 How did you solve this issue?
