### ISSUE TITLE
Description field in all Add pages gets smaller and is unreadable when I type in it.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3739]
Version - master 3/2

Steps to Reproduce: 
1.  Go to Add New Environment (I am unauthenticated)
2.  Click in Description field and type something it
3.  Move out of field

Results: When I click inside the field, the field get shorter and the text is unreadable when I get out
![image](https://cloud.githubusercontent.com/assets/11514927/13473305/00413992-e076-11e5-9ae5-d05f20558c46.png)

Expected: Field to be and stay same size as Name field

Comment:  This is true in all Add pages that had the description field moved to same line as Name.  New Service, New External Service... etc...

**Comment by vincent99** [comment]
These need to work on `keyup` events instead of keydown (or else you're off by 1 key all the time), and doesn't seem to be accounting for padding or a 1-line minimum height.

**Comment by tfiduccia** [comment]
not fixed.
Forgot Add New Environment

**Comment by tfiduccia** [comment]
Version - master UI 3/3
Verified fixed
