### ISSUE TITLE
Add ability to configure fluentd.bufferStorageVolume configuration in rancher-logging chart

### ISSUE THREAD

**Issue by samkulkarni20** [rancher/rancher#37394]
**Request description:**
Add ability to configure fluentd.bufferStorageVolume configuration in rancher-logging chart (https://banzaicloud.com/docs/one-eye/logging-operator/configuration/fluentd/#custom-fluentd-hostpath-volume-for-buffers)

**Actual behavior:**
Not able to configure fluentd.bufferStorageVolume configuration in rancher-logging chart

**Expected behavior:**
Aable to configure fluentd.bufferStorageVolume configuration in rancher-logging chart

**Workaround:**
Is workararound available and implemented? No

**Business Case:**
It is not possible to configure the fluentd.bufferStorageVolume block via chart values on the logging resource in the rancher-logging chart. As such a user cannot configure a volume or specific hostPath (to a separate filesystem) for the fluentd buffer. Therefore if a user defines a ClusterOutput/Output buffer without a total_limit_size, or simply does not define a buffer in the rancher-logging charts in Rancher v2.6 (which use Banzai Cloud Logging Operator >= 3.12.0 and create a buffer by default, but without a total_limit_size) the buffers will use an emptryDir volume and a large buffer can eventually trigger a node disk pressure condition

**Additional notes:**
N/A

**Comment by ronhorton** [comment]
**Pass** Verified in `2.6-head Commit ID eb03517`


In values for rancher-logging
Added
fluentd:
  bufferStorageVolume:
    hostPath:
      path: ''
  disablePvc: true
/opt/logging-operator/rancher-logging-root/rancher-logging-root-fluentd-buffer
was created successfully on the file system as expected
