### ISSUE TITLE
[v2.5] ingress-nginx bump to 1.2.0

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#37390]
All k8s versions included in KDM that reference ingress-nginx 1.1.x should be upgraded to use version 1.2.0 (e.g. `v1.19.16-rancher1-4` -> `v1.19.16-rancher1-5`). Note ingress-nginx 1.2.0 is very unlikely to support k8s prior to 1.19 as the [version support table](https://github.com/kubernetes/ingress-nginx#support-versions-table) doesn't list it for previous versions.
1.2.0 is planned to be released on 4/22/22, beta is already available: https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.2.0-beta.1

**Comment by kinarashah** [comment]
**Testing**
------- 
**1. KDM out of band** 
- fresh install `v1.19.16-rancher1-5` and `v1.20.15-rancher1-3` (min rancher version v2.5.11) 
- validate nginx ingress pods are running with v1.2.0-rancher1 
- ingress checks 
- upgrade to rancher v2.6.4 and confirm clusters are active and didn't update automatically 

**2. RKE standalone** 
- install `v1.19.16-rancher1-5` and `v1.20.15-rancher1-3` with RKE RC `v1.2.20-rc1` 
- validate nginx ingress pods are running with v1.2.0-rancher1 
- ingress checks

**Comment by kinarashah** [comment]
Available to test with KDM dev-v2.5 for out of band and RKE v1.2.20-rc1 (after https://drone-publish.rancher.io/rancher/rke/1298 is green)
