### ISSUE TITLE
Restricted Admins need to be distinguished from standard user.

### ISSUE THREAD

**Issue by Shavindra** [rancher/rancher#37409]
Internal reference: **SURE-3906**
dashboard reference: **https://github.com/rancher/dashboard/issues/4954**

**Issue description:**

Restricted Admin users are unable to see the Global Settings menu item under CONFIGURATION. 
Restricted Admin only have `resourceMethods: [GET]`. So we don't have a way to distinguish between standard user and a restricted admin user.

```
"id": "management.cattle.io.setting",
    "type": "schema",
    "links": {
      "collection": "https://localhost:8005/v1/management.cattle.io.settings",
      "self": "https://localhost:8005/v1/schemas/management.cattle.io.setting"
    },
    "pluralName": "management.cattle.io.settings",
    "resourceMethods": [
      "GET"
    ],
```

**Business impact:**

Customers using Hosted Rancher cannot view global settings in the UI

**Troubleshooting steps:**
none

**Repro steps:**
 * Create a restricted admin user.
 * Log in as the restricted admin user.
 * Click the menu icon in the top left corner

**Workaround:**
 Is workaround available and implemented? 
- yes
 What is the workaround: 
- You can navigate directly to the URL, for example https://support.rancher.cloud/dashboard/c/c-p24tr/settings/management.cattle.io.setting

**Actual behavior:**

Global Settings menu is missing from UI for restricted admin users.

**Expected behavior:**

Global Settings menu should be available for restricted admin users. See also [https://rancher.com/docs/rancher/v2.6/en/admin-settings/rbac/global-permissions/] (Under Settings, Restricted Admin should be able to list, but not edit, settings)

**Comment by MbolotSuse** [comment]
@Shavindra Would you mind explaining a bit more what you are looking for here? According to the [docs](https://rancher.com/docs/rancher/v2.6/en/admin-settings/rbac/global-permissions/) that you linked - standard users and restricted admins should both be able to list settings. 

From reading that page I would expect this button's behavior to be the same for restricted admin and standard user - can you elaborate on why they should be different?

**Comment by Jono-SUSE-Rancher** [comment]
@gaktive or @nwmac - Do you think we could get an update from @Shavindra so that we can maybe put this into someone's queue to look at?
