### ISSUE TITLE
Neuvector - Unable to access the neuvector UI from rancher for a custom RKE1 cluster

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37400]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6-head 6c12bee
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.22.8, 1.3.10-rc3
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.22.8
- Cluster Type (Local/Downstream): `Downstream custom rke1 1 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
Neuvector UI fails to load with the warning `Controller is not available ...` displayed. From the deployments, the controller pods are active. 
```
NAME                                        READY   STATUS    RESTARTS      AGE
neuvector-controller-pod-5cd7b6f9fd-fgjhq   1/1     Running   0             20m
neuvector-controller-pod-5cd7b6f9fd-knr2j   1/1     Running   0             20m
neuvector-controller-pod-5cd7b6f9fd-mjp4d   1/1     Running   0             20m'
```

**To Reproduce**
All the below steps are done as an admin user

1. Create a rancher HA on 2.6-head server image and charts version 2.6.5-rc1
2. Create a downstream rke1 custom cluster with 3 worker, 1 etcd, 1 cp.
3. Install neuvector chart with all the default options.
4. Launch the neuvector UI from the left navigation.

**Result**
The app fails to load with the error `Controller is not available ...`
If we check the deployments for the app, all the deployments are up and running.

**Expected Result**
Neuvector UI launched without any error and user is able to access 

**Screenshots**

<img width="300" alt="neuvector1" src="https://user-images.githubusercontent.com/38144301/164070496-5dbfd35d-f1ce-42a5-9230-9fb0259813d7.png">

**Additional context**
Enforcer pods were restarted with the following errors:
```
2022-04-19T17:26:19.633Z [ERROR] agent.client: RPC failed to server: method=KVS.Get server=10.42.2.9:18300 error="rpc error making call: Raft leader not found in server lookup mapping"
2022-04-19T17:26:19.633Z [ERROR] agent.http: Request error: method=GET url=/v1/kv/state/ctrl_ready?wait=1000ms from=127.0.0.1:42564 error="rpc error making call: Raft leader not found in server lookup mapping"
2022-04-19T17:26:19.655Z [ERROR] agent.client: RPC failed to server: method=Catalog.NodeServiceList server=10.42.2.9:18300 error="rpc error making call: Raft leader not found in server lookup mapping"
2022-04-19T17:26:19.655Z [ERROR] agent.anti_entropy: failed to sync remote state: error="rpc error making call: Raft leader not found in server lookup mapping"
2022-04-19T17:26:19.869Z [ERROR] agent.client: RPC failed to server: method=Catalog.ListNodes server=10.42.2.9:18300 error="rpc error making call: Raft leader not found in server lookup mapping"
```

**Workaround**: Restart the controller pods.

**Comment by selvamt94** [comment]
Can you give us some detail about cluster customization, I will try to reproduce the issue. Meanwhile if possible can you add these 2 lines to neuvector-controller-pod deployment under env section. This will restart controller pod in the debug mode.

            - name: CTRL_PATH_DEBUG
              value: "1"

Please collect all 3 controller's debug logs and post them here when you have time.
kubectl logs -n cattle-neuvector-system controller1-pod > contoller1.log
kubectl logs -n cattle-neuvector-system controller2-pod > contoller2.log
kubectl logs -n cattle-neuvector-system controller3-pod > contoller3.log

**Comment by anupama2501** [comment]
Provided my setup to Selvam via slack.

**Comment by anupama2501** [comment]
We are not ablre to reproduce the issue again.

**Comment by cbron** [comment]
Closing. We will re-open if we see again.
