### ISSUE TITLE
Can't see Add container button on host page in dark view

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3740]
Verison - Master 3/2

Steps to Reproduce: 
1.  Change theme to dark
2.  Add a new host

Results: The Add container button in the Standalone Containers section is barely visible
![image](https://cloud.githubusercontent.com/assets/11514927/13473634/6da4519e-e077-11e5-8c55-67eb05eaa7d0.png)

Expected:  Should be able to clearly see it

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/496

**Comment by tfiduccia** [comment]
Version - master UI 3/3
Verified fixed
