### ISSUE TITLE
Rancher docker keeps crashing 2.5.12 -> 2.6.4

### ISSUE THREAD

**Issue by timmy59100** [rancher/rancher#37410]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: Downstream: v1.18.12 
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? Custom

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
After upgrading the rancher docker install from 2.5.12 to 2.6.4, rancher keeps crashing after a few minutes.

**Logs**
`Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
, handler helm-clusterrepo-download: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974 reset --hard HEAD error: exit status 128, detail: fatal: Unable to create '/var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
, requeuing
2022/04/20 08:38:22 [ERROR] error syncing 'rancher-rke2-charts': handler helm-clusterrepo-ensure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9 reset --hard FETCH_HEAD error: exit status 128, detail: fatal: Unable to create '/var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
, handler helm-clusterrepo-download: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9 reset --hard HEAD error: exit status 128, detail: fatal: Unable to create '/var/lib/rancher-data/local-catalogs/v2/rancher-rke2-charts/675f1b63a0a83905972dcab2794479ed599a6f41b86cd6193d69472d0fa889c9/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
, requeuing
2022/04/20 08:38:23 [INFO] Created machine for node [local-node]
2022/04/20 08:38:24 httputil: ReverseProxy read error during body copy: unexpected EOF
2022/04/20 08:38:24 [ERROR] error syncing 'system-default-registry': handler fleet-install: pod cattle-system/helm-operation-lvvh5 failed, watch closed, requeuing
2022/04/20 08:38:24 [ERROR] error syncing 'rancher-charts': handler bootstrap-charts: pod cattle-system/helm-operation-jm7qf failed, watch closed, requeuing
2022/04/20 08:38:24 [ERROR] Failed to install system chart rancher-webhook: pod cattle-system/helm-operation-st7lc failed, watch closed
2022/04/20 08:38:24 [ERROR] error syncing 'local/p-s7d5g': handler project-namespace-auth: Post "https://127.0.0.1:6443/apis/rbac.authorization.k8s.io/v1/clusterroles": EOF, requeuing
2022/04/20 08:38:24 [WARNING] Failed to create precan alert rule high-number-of-leader-changes: Post "https://127.0.0.1:6443/apis/management.cattle.io/v3/namespaces/local/clusteralertrules": EOF
2022/04/20 08:38:24 [ERROR] error syncing 'local/p-7v9hv': handler project-namespace-auth: Post "https://127.0.0.1:6443/apis/rbac.authorization.k8s.io/v1/clusterroles": EOF, requeuing
2022/04/20 08:38:24 [FATAL] k3s exited with: exit status 2
INFO: Running k3s server --cluster-init --cluster-reset`

[rancher.log](https://github.com/rancher/rancher/files/8519872/rancher.log)

**Comment by blackwood821** [comment]
I'm encountering the same issue on Rancher 2.6.6
