### ISSUE TITLE
[RKE2 secrets encryption rotation keys] Cluster is rotating when provisioning

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#37414]
**Rancher Server Setup**
- Rancher version: v2.6-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.22.8+rke2r1
- Cluster Type (Local/Downstream):
   - RKE2 EC2 node driver 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Standard

**Describe the bug**

`rotateEncryptionKeys` was set when creating cluster and cluster is rotating keys while the cluster is provisioning. 
```
rotateEncryptionKeys:
  generation: 1
```

**To Reproduce**
 
1. Create RKE2 node driver cluster
2. Edit YAML and add under specs
 ```
rotateEncryptionKeys:
  generation: 1
```
3. Click create and check status while cluster is provisioning

**Result**
Status shows that cluster is trying to rotate keys while provisioning.

**Expected Result**
According to [35436](https://github.com/rancher/rancher/issues/35436#issuecomment-1048918154), the cluster should not be rotating keys when provisioning.

**Comment by snasovich** [comment]
Blocked by https://github.com/rancher/rancher/issues/35436 for now

**Comment by jakefhyde** [comment]
@Oats87 Currently blocked by https://github.com/k3s-io/k3s/pull/5649, which was/is blocked by code freeze. I should be able to test this now though, by creating a cluster with it in the spec.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 13482ca
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2
----------

### Testing: ###

Tested this issue with the following steps:
1. Create RKE2 node driver cluster
2. Edit YAML and add under specs
 ```
rotateEncryptionKeys:
  generation: 1
```
3. Click create and check status while cluster is provisioning

**Result** - Pass

Cluster is provisioned successfully and then Rancher moves on to rotate the encryption keys
