### ISSUE TITLE
Rancher is unable to serve the wins-agent-install.ps1 script in airgap for RKE2 Windows clusters

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#37428]
**Rancher Server Setup**
- Rancher version: v2.6.4
- Installation option (Docker install/Helm Chart): any
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): any
- Proxy/Cert Details: 

Currently, Rancher is attempting to serve a `wins-install.ps1` script when airgapped and the remote script is not available. 

Rancher needs to switch to serving `wins-agent-install.ps1` instead.

**Comment by slickwarren** [comment]
as of rancher v2.6.5-rc6, rke2 windows install script is able to pull from rancher in an airgapped setup.
