### ISSUE TITLE
[Neuvector] SSO config is not enabled if the controllers are not ready in the intial startup

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37420]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6-head 6c12bee
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.22.8, 1.3.10-rc11
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.22.8
- Cluster Type (Local/Downstream): `Downstream custom 3 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
When the controllers are not ready when the neuvector app is installed, SSO configuration is not saved. As a result rancher users are not able to launch neuvector UI via Rancher .

**To Reproduce**
1. Create a rancher server on v2.6-head with a custom cluster created.
2. Install neuvector chart version `100.0.0+up2.2.0-b1`
3. Install neuvector UI as admin/cluster owner
4. Neuvector UI is not accessible. 
5. run `k get services -n cattle-neuvector-system`
6. Launch neuvector UI <workernode>:port_webUi

**Result**
From settings >> Users >> configuration >> `Authenticate using OpenShift RBAC’s or Rancher’s` is disabled

**Expected Result**
Should be enabled

**Screenshots**
<img width="400" alt="neuvector-SSO" src="https://user-images.githubusercontent.com/38144301/164343451-479322b2-06fe-4022-9fc2-128b69d24283.png">

**Additional context**
Caused by https://github.com/rancher/rancher/issues/37400

**Comment by chunyenlin** [comment]
Controller has been changed to load rancher-related env variables no matter it's leader or not (as long as the value is different)
Fixed in fleet.4210

**Comment by selvamt94** [comment]
https://github.com/neuvector/neuvector/pull/192

**Comment by samjustus** [comment]
Which team is QAing this issue?

**Comment by anupama2501** [comment]
https://github.com/rancher/charts/pull/1880

**Comment by anupama2501** [comment]
Verified on v2.6-head 054b5d1

1. created a custom/node driver RKE1 cluster 
2. Installed neuvector version `100.0.0+up2.2.0-b2`
3. Verified the SSO config is enabled and the status is shown on all the 3 controller pods by executing the following:
```
controller_IP_1=`kubectl get pod -n cattle-neuvector-system -l app=neuvector-controller-pod -ojson | jq -r '.items[0].status.podIP'`
controller_IP_2=`kubectl get pod -n cattle-neuvector-system -l app=neuvector-controller-pod -ojson | jq -r '.items[1].status.podIP'`
controller_IP_3=`kubectl get pod -n cattle-neuvector-system -l app=neuvector-controller-pod -ojson | jq -r '.items[2].status.podIP'`
port=10443
curl -k -H "Content-Type: application/json" -d '{"password": {"username": "admin", "password": "admin"}}' "https://$controller_IP_1:$port/v1/auth"  > token.json
_TOKEN_=`cat token.json | jq -r '.token.token'`

curl -s -k -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_" "https://$controller_IP_1:$port/v1/system/config" | jq '.config | {SSO_status: .auth_by_platform, SSO_URL: .rancher_ep}'
{
  "SSO_status": true,
  "SSO_URL": "https://<rancher-URL>"
}
curl -s -k -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_" "https://$controller_IP_2:$port/v1/system/config" | jq '.config | {SSO_status: .auth_by_platform, SSO_URL: .rancher_ep}'
{
  "SSO_status": true,
  "SSO_URL": "https://<rancher-URL>"
}
curl -s -k -H "Content-Type: application/json" -H "X-Auth-Token: $_TOKEN_" "https://$controller_IP_3:$port/v1/system/config" | jq '.config | {SSO_status: .auth_by_platform, SSO_URL: .rancher_ep}'
{
  "SSO_status": true,
  "SSO_URL": "https://<rancher-URL>"
}

```

**Comment by anupama2501** [comment]
https://github.com/rancher/rancher/issues/37584
