### ISSUE TITLE
RKE2 cluster provisioning fails with vSphere cloud provider

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#37422]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Custom Cluster (3 control plane/etcd nodes, 1 worker node)
   
**Describe the bug**
Cluster provisioning never succeeds and all nodes stuck indefinitely in status "Waiting for ProviderID to be set".

**To Reproduce**
1. Create an RKE2 custom cluster consisting of 3 nodes with role of etcd + control-plane and 1 node with role of worker.

Cluster Configuration:
- Kubernetes version v1.21.10+rke2r2
- vSphere selected in the cloud provider dropdown box
- vSphere CPI and CSI configuration provided in the Add-On Config section

2. Execute the cluster registration command on all 4 cluster nodes.

**Result**
Cluster provisioning never succeeds and all nodes stuck indefinitely in status "Waiting for ProviderID to be set".

**Screenshots**

<img width="1689" alt="Screenshot 2022-04-20 at 16 25 15" src="https://user-images.githubusercontent.com/3813921/164385983-faecac1b-2ddb-4648-98e0-79a07dbb200c.png">

**Root Cause**

The RKE2 vSphere CPI/CSI helm chart configures incorrect tolerations on the CPI controller manager pod causing the pod to never be scheduled and as a result, nodes are never fully initialized (remain tainted with `node.cloudprovider.kubernetes.io/uninitialized:true`).

**Comment by sureshgoli25** [comment]
Below steps and solution worked for us.

For rke2 clusters.
```
1. Run the `kubectl drain <Node Name> --ignore-daemonsets`
2. Run the `kubectl delete node <Node Name>`
3. SSH to node which deleted above and switch to root by using `sudo -i`
4. Run `rke2-killall.sh` command
5. Login to each master and update `/etc/rancher/rke2/config.yaml` file with below details

  # vSphere Integration
  disable-cloud-controller: true
  cloud-provider-name: rancher-vsphere
  kubelet-arg:
  - "provider-id=vsphere://XXX" # /usr/sbin/dmidecode -s system-serial-number | tr -d "-" | tr -d " " | awk '{print substr($0,7,8)"-"substr($0,15,4)"-"substr($0,19,4)"-"substr($0,23,4)"-"substr($0,27,12);}'

6. Remove ETCD DB Directory: `rm -rf /var/lib/rancher/rke2/server/db`
7. reboot machine (Optional)
8. Ensure it come back online and joined cluster automatically.
```
As you see the provider ID setting manually, as RKE2 and K3S are actually setting the provider ID as RKE2://<node name>. But this is not CPI handles. By following sig documentation `https://cloud-provider-vsphere.sigs.k8s.io/tutorials/deploying-cpi-with-k3s.html` we have set the provider ID.
For worker nodes. You can follow same steps execept set the only `kublet arg ` in step 5 and skip step 6.

Also ensure, you have `disk UUID enabled` for VMs where RKE2 is running for vsphere CSI. If CSI also need to be enabled later on.

**Comment by janeczku** [comment]
Thanks @sureshgoli25 Your workaround seems to address a different issue. The issue at hand is about incorrect taints being set on the CPM pod, preventing it from being scheduled on a node. The workaround for this issue is SSHing to one of the master nodes and fixing the taints on the rancher-vsphere-cloud-controller pod using `kubectl`.

**Comment by phillipsj** [comment]
This issue has some more information that is related.

* https://github.com/rancher/rancher/issues/35474

RKE2 v1.21.10+rke2r2 is using the same version as v1.21.11:

* https://github.com/rancher/rke2/blob/379f39e048145c3c1b087493d223870c78002ec4/Dockerfile#L114-L115

This version is missing this [commit](https://github.com/rancher/vsphere-charts/commit/aebeca513cb2bb583afd0a96787550881a33f4a6) which is producing this issue. This has been fixed in v1.21.12 and doesn't impact v1.22.8 and newer.

**Comment by phillipsj** [comment]
Backport PR that brings it up the newest version of the charts: https://github.com/rancher/rke2/pull/2760

**Comment by sirredbeard** [comment]
This has been fixed in RKE2, QA'd, and backported; see https://github.com/rancher/rancher/issues/37452 and https://github.com/rancher/rke2/pull/2760.

Closing this for now.
