### ISSUE TITLE
Default k8s version switch to 1.23

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#37432]
For 2.6.5 release, we want to switch the default k8s version to 1.23.

The change needs to happen for the following (list may need to be expanded):
* Downstream RKE1 (in https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/k8s_version_info.go)
* Downstream RKE2/k3s (in https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/channels.yaml and https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/channels-rke2.yaml using `appDefaults` section as introduced per https://github.com/rancher/rancher/issues/36827)
* RKE1 itself (?)
* k3s version embedded into Rancher when running in Docker

**Comment by jiaqiluo** [comment]
## Note for updating the default version of RKE
Because rancher/rke pulls the metadata from the URL `https://releases.rancher.com/kontainer-driver-metadata/release-v2.6/data.json`, updating the default version of RKE will happen after the KDM is released. 

ref:
https://github.com/rancher/rke/blob/release/v1.3/codegen/codegen.go

**Comment by jiaqiluo** [comment]
The fix is available in the latest 2.6-head

### Areas or cases that should be tested
- in the docker-install mode, the local cluster should use k3s v1.23.6+k3s1
- when creating a node-driver RKE1/RKE2/K3s cluster, the default version should be the latest 1.23.x

**Comment by jiaqiluo** [comment]
the fix can be validated in [v2.6.5-rc7](https://github.com/rancher/rancher/releases/tag/v2.6.5-rc7)

**Comment by slickwarren** [comment]
tested on v2.6.5-rc8: 
* rke 1 and rke2 clusters now default to v1.23.6
* docker install default version is v1.23.6+k3s1
