### ISSUE TITLE
Rancher v0.59.1 serves http when in https

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#3743]
When accessing **https://url-to-rancher.com** on my setup the page fails to load and shows a timeout page with this request being the one that timed out: **http://url-to-rancher.com/v1/userpreferences?limit=1000**.

ELB config
<img width="780" alt="screen shot 2016-03-02 at 5 50 39 pm" src="https://cloud.githubusercontent.com/assets/524933/13479875/9d96ff0a-e09f-11e5-813a-8fbdb28a248b.png">

[ProxyProtocol](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html) is enabled.  Our setup is: `elb -> ec2 instance with docker running rancher on port 80` on a private subnet so we can talk to our internal systems.

I've retraced my steps and I don't believe I've missed anything.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.1` Cattle: `v0.148.1` UI: `v0.90.0` |
|Access|`github` `admin`|
|Route|`null`|

**Comment by vincent99** [comment]
The API returns absolute URLs based on the headers/ProxyProtocol info it's sent, and then the UI is following them.  I know you've said it's enabled, but the obvious answer is it isn't in fact enabled/working.  You can look for it on the host with something like `tcpdump -A -s0 port 80`, it would be at the beginning of each request.

**Comment by bkuhl** [comment]
Thanks for the followup.  I'll dig into this a bit more!
