### ISSUE TITLE
Rancher cannot provision node-driver cluster when it is behind a HTTPS proxy 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#37430]
**Problem:**
As of 2.6.4, Rancher will fail to provision node-driver clusters when the following conditions are true:
- rancher runs behind an HTTPS proxy
- rancher needs to connect to the to-be-created downstream cluster's nodes via the proxy 
- the HTTPS proxy here means the proxy server is installed with certifications. Rancher can use the proxy because it is installed with trusting those additional certs.

**Cause:**
This limitation is caused by the approach `rancher-machine` validates the integrity of nodes in the node-driver cluster: 

`rancher-machine` sends an HTTPS GET request to the port 2376 in the node, and validates if the certificates in the response are the ones it puts into the node. But the HTTPS proxy replaces the certs from the node with its own certs (same as a man-in-the-middle attack), as the result, although rancher can recognize and trust the certs but fails to validate them.

**Workaround:**
There will be a workaround coming in 2.6.5: we can add the IP or CIDR of the cluster's nodes to the `NO_PROXY` environment variable,  so Rancher will connect to the nodes directly instead of via the proxy. See #37295
However, this will work only when the direct connection between Rancher and nodes is possible. 

Here is the link to Rancher's documentation for setting the `proxy` and `noPorxy` variable: https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/behind-proxy/install-rancher/#install-rancher

**Comment by sowmyav27** [comment]
Reopening since it's an existing issue
