### ISSUE TITLE
rancher-system-agent ignores insecure_skip_verify (tls) and fails to deploy rke2 / k3s

### ISSUE THREAD

**Issue by rkgupta76** [rancher/rancher#37441]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE v1.22.7+rke2r2 or K3s v1.22.8+k3s1
- Proxy/Cert Details: Proxy Cache running on Harbor with self-signed certificate

**Information about the Cluster**
- Kubernetes version: RKE v1.22.7+rke2r2 or K3s v1.22.8+k3s1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom (VMs running on KVM)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

rancher-system-agent seems to ignore the insecure_skip_verify parameter for TLS when using a self-signed public Proxy Cache running on Harbor. 

This happens when deploying either RKE2 or K3s.

The same settings work fine when deploying RKE2 or K3s manually. The 

**To Reproduce**
 
1. Deploy Rancher 2.6.4
2. Deploy SLES 15 SP3 on VM running on KVM
3. Create a Custom RKE2 / K3s cluster from Rancher UI.
4. Provide the following Registry configuration:
Mirrors:
Registry Hostname: docker.io
Mirror Endpoint: https://harbor.suserancher.demo:8443/v2/rancher_proxy_cache
Registry Authentication
Registry Hostname: harbor.suserancher.demo:8443
Authentication: None
TLS Secret: None
CA Cert Bundle: None
Skip TLS Verification: True

6. Run the Rancher Command on the VM
7. Run "journalctl -xf" to check the logs

**Result**
The installation does not progress as rancher-system-image is unable to pull the image "index.docker.io/rancher/system-agent-installer-rke2:v1.22.7-rke2r2" (attaching the relevant logs)

**Expected Result**

The RKE2 or K3s cluster should be successfully deployed using the Proxy Cache with self-signed certificate

**Screenshots**

attached

**Additional context**

The same registry configuration works fine when deploying RKE2 or K3s manually

**Comment by rkgupta76** [comment]
![rke2-with-proxy-caching](https://user-images.githubusercontent.com/49442948/164641851-9700ad57-bac1-41ad-a920-70d1682614cb.png) - Screenshot of RKE2 Registries configuration in Rancher
[rke2-rancher-with-proxy-22apr22.log](https://github.com/rancher/rancher/files/8538327/rke2-rancher-with-proxy-22apr22.log) - Output of "journalctl -xf" from the node where RKE2 was to be deployed
[registries-rancher-created.yaml.txt](https://github.com/rancher/rancher/files/8538340/registries-rancher-created.yaml.txt) - /etc/rancher/agent/registries.yaml created by Rancher
[registries-manually-created.yaml.txt](https://github.com/rancher/rancher/files/8538354/registries-manually-created.yaml.txt) - Manually created /etc/rancher/rke2/registries.yaml which works with manual install of RKE2

**Comment by brandond** [comment]
The logs about the image pull are as follows:
```
Apr 22 12:38:11 rke-c1 rancher-system-agent[2441]: time="2022-04-22T12:38:11+05:30" level=info msg="[Applyinator] Extracting image rancher/system-agent-installer-rke2:v1.22.7-rke2r2 to directory /var/lib/rancher/agent/work/20220422-123811/cd7f1d17635b51226176348fe199f6d079ec67946c83996d001bd5a8dad322e5_0"
Apr 22 12:38:11 rke-c1 rancher-system-agent[2441]: time="2022-04-22T12:38:11+05:30" level=info msg="Using private registry config file at /etc/rancher/agent/registries.yaml"
Apr 22 12:38:11 rke-c1 rancher-system-agent[2441]: time="2022-04-22T12:38:11+05:30" level=info msg="Pulling image index.docker.io/rancher/system-agent-installer-rke2:v1.22.7-rke2r2"
Apr 22 12:38:11 rke-c1 rancher-system-agent[2441]: time="2022-04-22T12:38:11+05:30" level=error msg="error while staging: unrecognized challenge: : failed to get image index.docker.io/rancher/system-agent-installer-rke2:v1.22.7-rke2r2"
Apr 22 12:38:11 rke-c1 rancher-system-agent[2441]: time="2022-04-22T12:38:11+05:30" level=error msg="error executing instruction 0: unrecognized challenge: : failed to get image index.docker.io/rancher/system-agent-installer-rke2:v1.22.7-rke2r2"
```

I don't see anything there about it failing to validate the certificate; rather it appears to be unable to authenticate to the registry.

The certificate errors all appear to be related to files that haven't been created yet, because RKE2 hasn't been started due to the image pull failure.

**Comment by rkgupta76** [comment]
Its a Public Registry and does not require any authentication. So Authentication has been configured as "None".

If I try to install RKE2 or K3s manually using the same registry.yaml (generate by Rancher), it works fine.

**Comment by brandond** [comment]
Is this a public registry that I can test against, or do you have instructions to set up an identical registry? Are there other logs that indicate there's a problem with the registry's certificate?

**Comment by brandond** [comment]
The error I am seeing comes from here: https://github.com/google/go-containerregistry/blob/0ff1db03aaaabc9820e8a13353f61d8474814abd/v1/remote/transport/transport.go#L82

Which would appear to indicate that the client is being prompted to authenticate, but with an empty auth type.

**Comment by rkgupta76** [comment]
Unfortunately you can't access it since its running on my Laptop. I have followed the Harbor documentation to setup Registry as a Proxy cache
Harbor Installation and Configuration - https://goharbor.io/docs/2.5.0/install-config/
Configure Proxy Cache - https://goharbor.io/docs/2.5.0/administration/configure-proxy-cache/

**Comment by brandond** [comment]
Those instructions say that you need to prefix the proxy cache project name to the images when pulling, but it appears that instead you're appending the project name to the endpoint (/v2/proxy_cache). Is that supported by Harbor?

**Comment by rkgupta76** [comment]
When I manually install RKE2 or K3s using the same settings, it works. Only when I install using Rancher, it does not work. 

If you want, I can share the journalctl output from such a setup. In fact, I have shared the registries.yaml from such a setup in my first comment. Its a working configuration.

And I have used the Rancher created registries.yaml for manual setup (just for testing) and that worked as well. 

So the endpoint as mentioned is correct and working

The only difference that I have observed is that the manual setup does not involve rancher-system-agent and it goes through smoothly.

**Comment by brandond** [comment]
Is this actually airgapped, or is it possible that RKE2/K3s are falling back to the default endpoint and just pulling everything from Docker Hub? Unless the environment is actually isolated from the internet, can be difficult to tell if there are issues with your registry mirror.

The Rancher UI doesn't allow you to configure rewrites, but if you click 'edit as yaml' and find the registries section, you can do this:

```yaml
    registries:
      mirrors:
        docker.io:
          endpoint:
            - "https://harbor.suserancher.demo:8443"
          rewrite:
            "(.*)": "rancher_proxy_cache/$1"
      configs:
        "harbor.suserancher.demo:8443":
          tls:
            insecure_skip_verify: true      
```

**Comment by rkgupta76** [comment]
> Is this actually airgapped, or is it possible that RKE2/K3s are falling back to the default endpoint and just pulling everything from Docker Hub? Unless the environment is actually isolated from the internet, can be difficult to tell if there are issues with your registry mirror.
> 
> The Rancher UI doesn't allow you to configure rewrites, but if you click 'edit as yaml' and find the registries section, you can do this:
> 
> ```yaml
>     registries:
>       mirrors:
>         docker.io:
>           endpoint:
>             - "https://harbor.suserancher.demo:8443"
>           rewrite:
>             "(.*)": "rancher_proxy_cache/$1"
>       configs:
>         "harbor.suserancher.demo:8443":
>           tls:
>             insecure_skip_verify: true      
> ```

I can confirm that the images are being pulled from Caching Proxy during manual install of RKE2 / K3s. I can see the Caching Proxy log all the Pull requests for images that exist in the repository, and download the images which do not exist in the repository. So it is not bypassing the Caching Repository.

**Comment by rkgupta76** [comment]
> ```yaml
> insecure_skip_verify: true
> ```

I also tried the registry setting suggested by you. It did not work. Below are the log messages that I see:
```
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=info msg="Rancher System Agent version v0.2.3 (00181cd) is starting"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=info msg="Using directory /var/lib/rancher/agent/work for work"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=info msg="Starting remote watch of plans"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=info msg="Starting /v1, Kind=Secret controller"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=info msg="Detected first start, force-applying one-time instruction set"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=info msg="[Applyinator] Applying one-time instructions for plan with checksum 7fac974ec92a673a3002b1c9e43a32c6ccf1f2211bf872b93a59fd5739b17728"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=info msg="[Applyinator] Extracting image rancher/system-agent-installer-rke2:v1.22.7-rke2r2 to directory /var/lib/rancher/agent/work/20220425-110854/7fac974ec92a673a3002b1c9e43a32c6ccf1f2211bf872b93a59fd5739b17728_0"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=info msg="Using private registry config file at /etc/rancher/agent/registries.yaml"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=info msg="Pulling image index.docker.io/rancher/system-agent-installer-rke2:v1.22.7-rke2r2"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=error msg="error while staging: Get \"https://harbor.suserancher.demo:8443/v2/\": x509: certificate signed by unknown authority: failed to get image index.docker.io/rancher/system-agent-installer-rke2:v1.22.7-rke2r2"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=error msg="error executing instruction 0: Get \"https://harbor.suserancher.demo:8443/v2/\": x509: certificate signed by unknown authority: failed to get image index.docker.io/rancher/system-agent-installer-rke2:v1.22.7-rke2r2"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=info msg="[Applyinator] No image provided, creating empty working directory /var/lib/rancher/agent/work/20220425-110854/7fac974ec92a673a3002b1c9e43a32c6ccf1f2211bf872b93a59fd5739b17728_0"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=info msg="[Applyinator] Running command: sh [-c rke2 etcd-snapshot list]"
Apr 25 11:08:54 rke2-singlenode rancher-system-agent[1988]: time="2022-04-25T11:08:54+05:30" level=info msg="[7fac974ec92a673a3002b1c9e43a32c6ccf1f2211bf872b93a59fd5739b17728_0:stderr]: sh: rke2: command not found"
```

When I go back and see the YAML config, the "insecure_skip_verify: true" under configs is missing (see below). I did add that entry before deploying the cluster. 

    registries:
      configs:
        harbor.suserancher.demo:8443: {}
      mirrors:
        docker.io:
          endpoint:
          - https://harbor.suserancher.demo:8443
          rewrite:
            (.*): rancher_proxy_cache/$1

**Comment by rkgupta76** [comment]
Tried this one more time. It did not work. Here are some observations:

Logs clearly indicate an issue with the certificate.
```
Apr 25 15:45:51 rke2-singlenode rancher-system-agent[4214]: time="2022-04-25T15:45:51+05:30" level=info msg="[Applyinator] Extracting image rancher/system-agent-installer-rke2:v1.22.7-rke2r2 to directory /var/lib/rancher/agent/work/20220425-154551/b1a2309d587a82bf58cffb6a21c0099330c75567aaa4b30b6949617e7a5f44f3_0"
Apr 25 15:45:51 rke2-singlenode rancher-system-agent[4214]: time="2022-04-25T15:45:51+05:30" level=info msg="Using private registry config file at /etc/rancher/agent/registries.yaml"
Apr 25 15:45:51 rke2-singlenode rancher-system-agent[4214]: time="2022-04-25T15:45:51+05:30" level=info msg="Pulling image index.docker.io/rancher/system-agent-installer-rke2:v1.22.7-rke2r2"
Apr 25 15:45:51 rke2-singlenode rancher-system-agent[4214]: time="2022-04-25T15:45:51+05:30" level=error msg="error while staging: Get \"https://harbor.suserancher.demo:8443/v2/\": x509: certificate signed by unknown authority: failed to get image index.docker.io/rancher/system-agent-installer-rke2:v1.22.7-rke2r2"
Apr 25 15:45:51 rke2-singlenode rancher-system-agent[4214]: time="2022-04-25T15:45:51+05:30" level=error msg="error executing instruction 0: Get \"https://harbor.suserancher.demo:8443/v2/\": x509: certificate signed by unknown authority: failed to get image index.docker.io/rancher/system-agent-installer-rke2:v1.22.7-rke2r2"
Apr 25 15:45:51 rke2-singlenode rancher-system-agent[4214]: time="2022-04-25T15:45:51+05:30" level=info msg="[Applyinator] No image provided, creating empty working directory /var/lib/rancher/agent/work/20220425-154551/b1a2309d587a82bf58cffb6a21c0099330c75567aaa4b30b6949617e7a5f44f3_0"
Apr 25 15:45:51 rke2-singlenode rancher-system-agent[4214]: time="2022-04-25T15:45:51+05:30" level=info msg="[Applyinator] Running command: sh [-c rke2 etcd-snapshot list]"
Apr 25 15:45:51 rke2-singlenode rancher-system-agent[4214]: time="2022-04-25T15:45:51+05:30" level=info msg="[b1a2309d587a82bf58cffb6a21c0099330c75567aaa4b30b6949617e7a5f44f3_0:stderr]: sh: rke2: command not found"
```

The /etc/rancher/agent/registries.yaml does not have "insecure_skip_verify" parameter, even though we defined it in the YAML
`{"configs":{"harbor.suserancher.demo:8443":{"auth":null,"tls":null}},"mirrors":{"docker.io":{"endpoint":["https://harbor.suserancher.demo:8443"],"rewrite":{"(.*)":"rancher_proxy_cache/$1"}}}}`


Post deployment, when I look at the registries section in the cluster YAML. This is what it looks like. The tls section is missing completely.
![registries-post-deployment](https://user-images.githubusercontent.com/49442948/165070955-31e5920c-eed3-4af7-afaa-bf13fda4bc0d.png)

I suspect, as I have mentioned in the past, that "insecure skip verify" is ignored and hence we run into "x509: certificate signed by unknown authority" issue

**Comment by rkgupta76** [comment]
Finally had success with the following configuration

```
    registries:
      configs:
        harbor.suserancher.demo:8443:
          insecureSkipVerify: true
      mirrors:
        docker.io:
          endpoint:
            - https://harbor.suserancher.demo:8443
          rewrite:
            "(.*)": "rancher_proxy_cache/$1"

Thanks for all your support.

I suggest that we document this. Thanks. 
```

**Comment by brandond** [comment]
That's interesting, it appears that Rancher's fields translate the `snakes_case` registries.yaml fields to `camelCase` within the cluster spec.
