### ISSUE TITLE
Nuevector feature chart installation fails when a neuvector partner chart already exists

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37447]
**Rancher Server Setup**
- Rancher version: `v2.6-head a478def `
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.22.7+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.19.16 `
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 3 worker, 1 etcd, 1 cp`
`RKE1`

**Describe the bug**
Installation of neuvector feature chart fails if we have a neuvector partner chart already installed. 

**To Reproduce**
1. Install neuvector partner chart from apps & market by selecting the partner chart repo any version
2. After the partner chart installs, install neuvector chart `100.0.0+up2.2.0-b1 `

**Result**
Installation fails with the error:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "nvsecurityrules.neuvector.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "neuvector-crd": current value is "neuvector"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "cattle-neuvector-system": current value is "default"
```

**Expected Result**
Installation goes through for feature chart.

**Additional context**
Workaround: Uninstall nuevector partner chart and re-install neuvector feature chart.

**Comment by cbron** [comment]
Only solution here will be docs/release-note, so once those are in we can close this. There won't be a migration from one chart to the other, as they live in separate helm repos.
