### ISSUE TITLE
Avoid closing tab without confirmation when terminal is open

### ISSUE THREAD

**Issue by foobear** [rancher/rancher#37444]
**Is your feature request related to a problem? Please describe.**

When using a terminal emulator window in Rancher, pressing Ctrl+W immediately closes the browser window/tab without confirmation.

On regular terminal emulators, that keyboard shortcut usually removes the last word which is why I regularly type it out of habit -- and lose my terminal sessions on Rancher regularly.

**Describe the solution you'd like**

I understand that, due to security limitations, the Ctrl+W keypress can not be captured to handle via Rancher's terminal emulator.
However, we can ask the user to confirm closing the browser window, and ideally avoid closing windows unintentionally. Example:

```javascript
window.addEventListener('beforeunload', () => { return 'Really close window?' });
```

That event handler could obviously be a bit smarter, and maybe skip confirmation if no terminal windows are open.

**Describe alternatives you've considered**

Removing the `W` key from my keyboard.

**Additional context**

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

**Comment by HectorB-2020** [comment]
I'm still quite surprised nobody has bumped up this issue one more time. Are there only two of us who are interested in this feature?
