### ISSUE TITLE
Validate rke2 harvester chart bumps in rancher

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#37454]
The following harvester changes have been made in rke2 and should be validated through rancher as well:

Chart Name | New Version | Affected Kubernetes Version(s)
-- | -- | --
harvester-cloud-provider | 0.1.1100 | v1.21.12+rke2r1, v1.22.9+rke2r1, v1.23.6+rke2r1
harvester-csi-driver | 0.1.1100 | v1.21.12+rke2r1, v1.22.9+rke2r1, v1.23.6+rke2r1

This can be validated using rke2 rcs directly, pointing KDM to: https://raw.githubusercontent.com/nikolaishields/kontainer-driver-metadata/april_release_rke2/data/data.json

KDM Ref: https://github.com/rancher/rancher/issues/37191
RKE2 Ref: https://github.com/rancher/rke2/issues/2776 and https://github.com/rancher/rke2/issues/2765

**Comment by sowmyav27** [comment]
To validate: harvester - provision as normal with harvester, ensure cluster and all workloads come up successfully, and P0 harvester checks succeed.

**Comment by rancher-max** [comment]
@slickwarren It's possible this has already been validated. Please check https://github.com/rancher/rke2/issues/2776#issuecomment-1107845714 and https://github.com/rancher/rke2/issues/2765#issuecomment-1107845955 to make sure this is in line with what you would do here as well, and if so you can probably just close this

**Comment by slickwarren** [comment]
I don't see any upgrade cases here, so I will test that as well once I get an RC for harvester (estimated end of this week)

**Comment by rancher-max** [comment]
Based on some internal discussion, it sounds like harvester in general has the following checks:
1. Fresh install using new rke2 (k8s) version — necessary for kdm release
2. Upgrade from older rke2 (k8s) version to new rke2 (k8s) version — necessary for kdm release
3. Upgrade harvester version (?) — NOT necessary for kdm release, but necessary for rancher and harvester releases

Based on that, I believe scenarios 1 and 2 have been complete, and scenario 3 is not necessary for this issue. @yasker @rebeccazzzz can you please confirm if this is correct? cc @slickwarren @sowmyav27

**Comment by yasker** [comment]
I can confirm an upgrade to the upcoming Harvester release shouldn't be required for this KDM release. We should ensure the compatibility between different Harvester cloud provider and csi driver versions and Harvester versions. If it does not working in the new Harvester version, it's likely a bug in the new Harvester release unless we specifically call it out as a breaking change. cc @guangbochen @bk201

**Comment by sowmyav27** [comment]
Closing this based on https://github.com/rancher/rancher/issues/37454#issuecomment-1110334556

**Comment by TachunLin** [comment]
Hi @rancher-max, we have validated the bumped harvester cloud-provider and csi driver to `0.1.1100` with the affected kubernetes version in the matrix table. 

Please refer to https://github.com/rancher/rke2/issues/2776 and https://github.com/rancher/rke2/issues/2765 for more the detailed test result. 

Also We have verified can spin up RKE2 cluster on different kuberntes version, the cloud-provider and csi driver both running correctly on it.
