### ISSUE TITLE
Update sriov chart

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rancher#37459]
**Is your feature request related to a problem? Please describe.**
I want sriov to be updated to the latest release

**Describe the solution you'd like**
I want sriov to be aupdated to the latest release

**Describe alternatives you've considered**

**Additional context**

**Comment by rancher-max** [comment]
Did the same validations as mentioned in https://github.com/rancher/rancher/issues/36069#issuecomment-1119748428. Also noticed image versions running on containers in sriov controller daemonset were bumped
