### ISSUE TITLE
Validate rke2 vsphere chart bumps in rancher

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#37452]
The following vsphere changes have been made in rke2 and should be validated through rancher as well:

Chart Name | New Version | Affected Kubernetes Version(s)
-- | -- | --
rancher-vsphere-cpi | 1.2.101 | v1.21.12+rke2r1, v1.22.9+rke2r1, v1.23.6+rke2r1
rancher-vsphere-csi | 2.5.1-rancher101 | v1.21.12+rke2r1, v1.22.9+rke2r1, v1.23.6+rke2r1

This can be validated using rke2 rcs directly, pointing KDM to: https://raw.githubusercontent.com/nikolaishields/kontainer-driver-metadata/april_release_rke2/data/data.json

KDM Ref: https://github.com/rancher/rancher/issues/37191
RKE2 Ref: https://github.com/rancher/rke2/issues/2713

**Comment by sowmyav27** [comment]
To validate - vsphere csi/cpi - provision using vsphere cloud provider, ensure cluster and all workloads come up successfully, and P0 vsphere checks succeed.

**Comment by rancher-max** [comment]
#### Validated using rancher v2.6.5-rc3

Am able to successfully deploy and upgrade split-role nodes on all of v1.21.12-rc4+rke2r1, v1.22.9-rc4+rke2r1, and v1.23.6-rc4+rke2r1 with the vsphere cloud provider. Additionally, these all use the correct vsphere charts and versions.
