### ISSUE TITLE
Ingress="cattle-system/rancher" error="ingress does not contain a valid IngressClass"

### ISSUE THREAD

**Issue by cpars-innovation** [rancher/rancher#37456]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart): Helm 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): OKE v1.21.5
- Proxy/Cert Details: Ingress

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

   
**Describe the bug**
With the normal startup the ingress always returns a 404. The cluster also then uses the wrong certificate (Kubernetes Fake Certificates). This prevents rancher from being accessed without a proxy.

**To Reproduce**
  helm upgrade --install rancher rancher-latest/rancher \
    --namespace cattle-system \
  --set hostname=<url> \
  --set replicas=3 \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=<email> \
  --set letsEncrypt.ingress.class=nginx

**Result**

**Expected Result**

**Screenshots**

**Additional context**

I figured out the solution and just wanted to share it in case someone else runs into the problem. 
There is a breaking change in the new ingress version that requres the Ingress config to have a ingress class. 
 
https://robearlam.com/blog/nginx-ingress-breaking-change-ingress.class-now-required

after adding this the ingress worked fine 
kubernetes.io/ingress.class: "nginx"

if u upgraded your kubernetes cluster and are having issues you can just grep your nginx controller log and find all ingresses where it is missing 
 kubectl logs -n ingress-nginx -f <pod-name>  | grep error="ingress does not contain a valid IngressClass"

hope it helps someone and maybe rancher can patch it so it doesnt need to be done manually

**Comment by east4ming** [comment]
same error. on k3s v1.22.5. Because the ingress like this:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: rancher
    meta.helm.sh/release-namespace: cattle-system
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  creationTimestamp: "2022-05-10T10:19:35Z"
  generation: 3
  labels:
    app: rancher
    app.kubernetes.io/managed-by: Helm
    chart: rancher-2.6.4
    heritage: Helm
    release: rancher
  name: rancher
  namespace: cattle-system
spec:
  rules:
  - host: rancher-demo.example.com
    http:
      paths:
      - backend:
          service:
            name: rancher
            port:
              number: 80
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - rancher-demo.example.com
    secretName: tls-rancher-ingress
```

there is nginx.ingress.kubernetes.io ingress class, but no traefik ingress class.

**Comment by willzhang** [comment]
same in rancher 2.6.6

```
root@node01:~# kubectl -n ingress-nginx logs -f ingress-nginx-controller-58b75f4b99-txzw6
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       v1.2.0
  Build:         a2514768cd282c41f39ab06bda17efefc4bd233a
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.19.10

-------------------------------------------------------------------------------

W0724 02:40:09.776795       7 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0724 02:40:09.777034       7 main.go:230] "Creating API client" host="https://10.96.0.1:443"
I0724 02:40:09.784350       7 main.go:274] "Running in Kubernetes cluster" major="1" minor="23" git="v1.23.8" state="clean" commit="a12b886b1da059e0190c54d09c5eab5219dd7acf" platform="linux/amd64"
I0724 02:40:09.953171       7 main.go:104] "SSL fake certificate created" file="/etc/ingress-controller/ssl/default-fake-certificate.pem"
I0724 02:40:10.007844       7 ssl.go:531] "loading tls certificate" path="/usr/local/certificates/cert" key="/usr/local/certificates/key"
I0724 02:40:10.035560       7 nginx.go:256] "Starting NGINX Ingress controller"
I0724 02:40:10.052708       7 event.go:285] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"ingress-nginx", Name:"ingress-nginx-controller", UID:"cde8cc0d-40b2-422e-994d-b38460da1f2d", APIVersion:"v1", ResourceVersion:"171957", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap ingress-nginx/ingress-nginx-controller
I0724 02:40:11.237467       7 nginx.go:299] "Starting NGINX process"
I0724 02:40:11.237678       7 leaderelection.go:248] attempting to acquire leader lease ingress-nginx/ingress-controller-leader...
I0724 02:40:11.237915       7 nginx.go:319] "Starting validation webhook" address=":8443" certPath="/usr/local/certificates/cert" keyPath="/usr/local/certificates/key"
I0724 02:40:11.238162       7 controller.go:166] "Configuration changes detected, backend reload required"
I0724 02:40:11.296331       7 controller.go:183] "Backend successfully reloaded"
I0724 02:40:11.296494       7 controller.go:194] "Initial sync, sleeping for 1 second"
I0724 02:40:11.296593       7 event.go:285] Event(v1.ObjectReference{Kind:"Pod", Namespace:"ingress-nginx", Name:"ingress-nginx-controller-58b75f4b99-txzw6", UID:"1dabd7a6-8974-42c0-a77e-cb6a51f60fe5", APIVersion:"v1", ResourceVersion:"172145", FieldPath:""}): type: 'Normal' reason: 'RELOAD' NGINX reload triggered due to a change in configuration
I0724 02:40:11.462307       7 leaderelection.go:258] successfully acquired lease ingress-nginx/ingress-controller-leader
I0724 02:40:11.462494       7 status.go:84] "New leader elected" identity="ingress-nginx-controller-58b75f4b99-txzw6"
E0724 02:40:26.030174       7 leaderelection.go:367] Failed to update lock: etcdserver: request timed out
W0724 02:45:15.831616       7 controller.go:256] ignoring ingress rancher in cattle-system based on annotation : ingress does not contain a valid IngressClass
I0724 02:45:15.831656       7 main.go:100] "successfully validated configuration, accepting" ingress="cattle-system/rancher"
I0724 02:45:16.122895       7 store.go:425] "Ignoring ingress because of error while validating ingress class" ingress="cattle-system/rancher" error="ingress does not contain a valid IngressClass"

```

**Comment by willzhang** [comment]
fixed by add `kubernetes.io/ingress.class: nginx` to annotations, but it should fixed by rancher itself
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: rancher
    cert-manager.io/issuer-kind: Issuer
    field.cattle.io/publicEndpoints: '[{"addresses":["10.96.2.216"],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher"
,"hostname":"rancher.my.org","allNodes":false}]'
    kubernetes.io/ingress.class: nginx
```

**Comment by BennyDeeDev** [comment]
> fixed by add `kubernetes.io/ingress.class: nginx` to annotations, but it should fixed by rancher itself
> 
> ```
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   annotations:
>     cert-manager.io/issuer: rancher
>     cert-manager.io/issuer-kind: Issuer
>     field.cattle.io/publicEndpoints: '[{"addresses":["10.96.2.216"],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher"
> ,"hostname":"rancher.my.org","allNodes":false}]'
>     kubernetes.io/ingress.class: nginx
> ```

This worked

**Comment by aintbrokedontfix** [comment]
This is happening with Rancher v2.6.8. 

I was able to deploy rancher 2.6.8 w/o issues (clean deploys ) up until Thursday of last week (Sept 8). 

```
 helm upgrade --install=true rancher rancher-stable/rancher \
    --namespace {{namespace}} \
    --create-namespace \
    --set replicas=1 \
    --set hostname= {{hostname}}\
    --set bootstrapPassword={{passwd}} \
    --set ingress.tls.source=rancher
```

**Comment by aintbrokedontfix** [comment]
Hope this helps others... here is the solution using helm and rancher 2.6.8

```
# Play close attention to the dot/period escaping 
helm upgrade --install=true rancher rancher-stable/rancher \
    --namespace cattle-system \
    --create-namespace \
    --set replicas=1 \
    --set hostname={{hostname}} \
    --set bootstrapPassword={{passwd}} \
    --set ingress.extraAnnotations.'kubernetes\.io/ingress\.class'=nginx
```

**Comment by Pramod-Telia** [comment]
Hello,
Can anyone provide how to impement this solution via Terraform

**Comment by serhiynovos** [comment]
It also happened to me when I updated to latest rke2 version

**Comment by skanakal** [comment]
https://github.com/rancher/rancher/issues/35053#issuecomment-2184300522
