### ISSUE TITLE
downstream rke2 cluster goes to `provisioning` state when upgrading rancher from 2.6.4 -> 2.6.5-rc2

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#37465]
**Rancher Server Setup**
- Rancher version: v2.6.5-rc2
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): rke2, any cluster type

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): standard user, cluster owner

   
**Describe the bug**
when upgrading the rancher server from 2.6.4 -> 2.6.5-rc2 the downstream cluster goes into a `provisioning` state. (rke1 clusters go into an `unavailable` state) before coming back to an `active` state

**To Reproduce**
* deploy rancher 2.6.4
* deploy an rke2 downstream cluster
* upgrade rancher to 2.6.5-rc2

**Result**
the downstream cluster goes into a provisioning state with the below logs:
```
[INFO ] configuring bootstrap node(s) custom-59e5e92a772a: waiting for plan to be applied
[INFO ] provisioning done
```
after which, it comes back to an active state. 

**Expected Result**
cluster should not enter `provisioning` state upon upgrading.

**Comment by snasovich** [comment]
For now considering this release-blocker as we really want to try to fix this logic before going GA with RKE2. If the initial attempt to fix it is not successful, we can remove the label and address in 2.6.6.

**Comment by snasovich** [comment]
Transferring to @Oats87 following the closure of previous approach from https://github.com/rancher/rancher/pull/37482

**Comment by thedadams** [comment]
@Oats87 While driving, I realized that the approach we discussed on Slack won't fix the issue without more changes.

We talked about adding a `Remove` field to the `File` in a node plan. This won't work for if the manifest is still updated when the Rancher version is updated. The file still needs to be "blanked" before adding the `Remove = true` field.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head b919539
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver cluster

----------

### Testing: ###

Tested this issue with the following steps:
1. Deploy rancher 2.6.4
2. Deploy an RKE2 downstream cluster
3. Upgrade rancher to 2.6-head

**Result**

The cluster goes into an `Error` state for a bit with these errors but were not logged in the provisioning log.
![image.png](https://zube.io/files/rancher/6495f1b25bbd3411673f109a61b0b3ba-image.png)
![image.png](https://zube.io/files/rancher/e5caab84d7c264f40849356acfbc46d3-image.png)

@Oats87 could you take a look? If this is expected then could we log the errors as well?

**Comment by Oats87** [comment]
@timhaneunsoo so is the behavior you saw that the cluster went into this "Error" state, but the upgrade did in fact happen properly?

I wonder if we need to clean up that error message to make it look less "scary". That error message is more or less expected when the cluster-agent is not connected properly.

**Comment by thaneunsoo** [comment]
Yes, the upgrade was successful. It would be nice to make the error message look less scary.

**Comment by thaneunsoo** [comment]
Issue regarding logging can be tracked in [38249](https://github.com/rancher/rancher/issues/38249) Closing this issue as fix confirmed.
