### ISSUE TITLE
hostPort related test fails on RKE2 cluster.

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#37460]
**Rancher Server Setup**
- Rancher version: v2.6.5-rc2
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.22.8+rke2r1
- Cluster Type (Local/Downstream): Downstream
AWS Node driver cluster.

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Admin and/or Standard User
   
**Describe the bug**

While jenkins job is running _test_wl_with_hostPort_ test, the _curl_ command fails to get response from the host.

Note: The same job passes for rke1 cluster. 

I see the following in the console log.
`curl: (28) Failed to connect to IP-Address port 9999: Connection timed out
`

The job keeps trying to connect to host but it fails. 

**To Reproduce**
 

1. Create a rancher v2.6.5-rc2 server.
2. install a aws node driver rke2 cluster.
3. Run the jenkins job with following pytest option.
`-k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"`

**Result**
curl command fails to get response from the host.

**Expected Result**
Curl command gets response from the hostport service.

**Comment by Josh-Diamond** [comment]
Ticket #37460 - Test Results

Reproduced [manually] on rancher `v2.6.5-rc3`:
1. Fresh install of rancher `v2.6.5-rc3`
2. Provision a downstream RKE2 Node driver cluster with k8s `v1.22.8+rke2r1`
3. Once cluster is `Active`, deploy a workload with a hostport enabled
4. Once workload is `Active`, access workload through browser
5. Reproduced - Workload is unavailable through browser at hostport

Screenshots:

`Workload`:
![hostport1](https://user-images.githubusercontent.com/46494969/165370343-82d2e164-5c1b-4b0b-bc46-245dc77533b6.png)

`Browser`:
![hostport2](https://user-images.githubusercontent.com/46494969/165370754-3d6f3348-4f6f-444f-b869-4047e8f41a04.png)

`Console`:
<img width="1666" alt="Screen Shot 2022-04-26 at 11 48 25 AM" src="https://user-images.githubusercontent.com/46494969/165370984-f49ca9ad-c2c5-4621-9569-ec3c44cbfd0c.png">

**Comment by vivek-infracloud** [comment]
@Josh-Diamond Thank you for adding the steps to reproduce the issue manually.

**Comment by paynejacob** [comment]
This was determined to be an issue with the test environment's configuration not rancher.

**Comment by Josh-Diamond** [comment]
Closing ticket as per @paynejacob's findings mentioned above

NOTE: security groups must allow specified hostport; it seems that was the issue in this scenario
