### ISSUE TITLE
Rancher 2.6.5-rc3 can't edit cluster

### ISSUE THREAD

**Issue by mattskipton** [rancher/rancher#37477]
**Rancher Server Setup**
- Rancher version: 2.6.5-rc3
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.22.8
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: global admin

   
**Describe the bug**
Once upgrading from 2.6.5-rc2 to 2.6.5-rc3 atteming to click on ellipsis for any cluster produces a javascript error and you can not edit the cluster.

browser console shows javascript error:
vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'top')
    at c (position.js:19:17)
    at n.fitOnScreen (position.js:75:15)
    at f.updateStyle (ActionMenu.vue:149:1)
    at f.<anonymous> (ActionMenu.vue:102:1)
    at Array.<anonymous> (vue.runtime.esm.js:1980:12)
    at ie (vue.runtime.esm.js:1906:12)

using debugger the error orginates on line 19 of position.js in function boundingRect(elem) line "    top:    pos.top,". Exception is "TypeError: Cannot read properties of undefined"

**To Reproduce**
upgrade ro 2.6.5-rc3 and try to edit a cluster

**Result**
nothing

**Expected Result**
able to edit cluster

**Screenshots**

**Additional context**

**Comment by sowmyav27** [comment]
Same as this one - https://github.com/rancher/dashboard/issues/5699
