### ISSUE TITLE
Hide rancher-external-ip-webhook chart for k8s versions > 1.22

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#37476]
Problem:
The rancher-external-ip-webhook chart version [100.0.0+up1.0.0](https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-external-ip-webhook/100.0.0%2Bup1.0.0) is showing up as an installable option for clusters with k8s version > 1.22 which is not a supported version.

Solution:
Set a kube-version annotation constraint to prevent users from installing the chart in clusters with k8s version > 1.22

**Comment by MSpencer87** [comment]
_Verified_ on `k8s 1.23`  

External IP Webhook chart is no longer visibile with k8s versions > 1.22

**Steps To Reproduce**
1) Bring up HA Rancher with k8s <= 1.22 (I used Rancher 2.6.3 on RKE 1.3.3)
2) Navigate to Local-> Apps & Marketplace -> Charts
3) View that External IP Webhook IS NOT HIDDEN
![Screen Shot 2022-07-22 at 2 16 11 PM](https://user-images.githubusercontent.com/6477538/180571002-285a83ed-c316-436e-a9f1-ffd48e696bd9.png)


**Steps for Validation**
1) Bring up HA Rancher with k8s > 1.22 (I used Rancher 2.6.5 on RKE 1.3.11)
2) Navigate to Local-> Apps & Marketplace -> Charts
3) View that External IP Webhook IS HIDDEN
![Screen Shot 2022-07-22 at 2 17 12 PM](https://user-images.githubusercontent.com/6477538/180571030-7b3bed87-e55a-4d20-9d9a-10b3b9544ca7.png)
