### ISSUE TITLE
RKE1 - Retry Backoff

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#37479]
We want to give users more control over the RKE1 cluster provisioning process: 

#  Retry Backoff

Currently, when RKE1 fails to provision, the error state is saved on the cluster, and Rancher continues retrying to provision the cluster. Unfortunately, there is no way for users to stop Rancher from retrying. 

We want to introduce a backoff logic so Rancher can gracefully stop after the requested number of retries. 

 ---

Separate issues will be made in the rancher/rke and rancher/dashboard to track relevant works.

**Comment by snasovich** [comment]
Due to a shift in priorities, this is no longer in the v2.6.6 release plans, so moving it to Unscheduled for now.
