### ISSUE TITLE
Neuvector container run time should be auto detected based on the cluster types

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37481]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6-head a6d2050
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.22.7, 1.3.10-rc4
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.22.7
- Cluster Type (Local/Downstream): `Downstream node driver 1 worker, 1 etcd, 1 cp RKE2`

**Describe the bug**
When we have different cluster types for example, RKE2 or AKS or EKS we need to manually select the container Run time while installing neuvector chart. This is currently not auto detected based on the cluster type. 
Container run time should be auto detected based on the container run time engine.

**Comment by cbron** [comment]
May be able to fix this with: https://github.com/rancher/kubernetes-provider-detector
That logic is already included in app deployer, so it sounds like this just needs to map cluster type to container runtime.

**Comment by becitsthere** [comment]
Thanks for the suggestions. Setting up the correct runtime socket is the most asked question in the initial deployment stage. The runtime socket is mounted into our container in the helm chart, and it is set by the users. What is the procedure for users to set this correctly?

**Comment by garyduan** [comment]
Thanks for the suggestions. Setting up the correct runtime socket is the most asked question in the initial deployment stage. The runtime socket is mounted into our container in the helm chart, and it is set by the users. What is the procedure for users to set this correctly?

**Comment by cbron** [comment]
Oh actually, I don't think we can pick runtime based on cluster type can we ? I though some were interchangeable, k3s can run on docker runtime last I checked. We don't have a way to check container runtime that I know of.

**Comment by becitsthere** [comment]
I think there is no good ways to determine the runtime socket path automatically. Should we close this issue?

**Comment by garyduan** [comment]
I think there is no good ways to determine runtime socket path. Should we close this issue?

**Comment by samjustus** [comment]
@cbron agree we should close? If so @anupama2501 please close

**Comment by anupama2501** [comment]
Moving the ticket v2.6.x

**Comment by cbron** [comment]
Going to close until it's requested as feature, then we can investigate.
