### ISSUE TITLE
[monitoring v2] rancher-monitoring-kube-controller-manager is down

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#37487]
**Rancher Server Setup**
- Rancher version: `v2.6.4`
- Installation option (Docker install/Helm Chart): `HA`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `rke1`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.22.7`
- Cluster Type (Local/Downstream): `downstream`
   - If downstream, what type of cluster? `ec2`

**User Information**
- What is the role of the user logged in? `admin`
  - If custom, define the set of permissions:

   
**Describe the bug**
Installed `rancher-monitoring:100.1.0+up19.0.3` and kube-controller-manager is down; alerts are not functional

**To Reproduce**
1. create downstream cluster on 2.6.4
2. install monitoring chart

**Result**
`rancher-monitoring-kube-controller-manager is down`

log entries showing cert errors in rancher-monitoring-operator
`level=info ts=2022-04-27T10:56:51.098689263Z caller=operator.go:742 component=alertmanageroperator key=cattle-monitoring-system/rancher-monitoring-alertmanager msg="sync alertmanager"
ts=2022-04-27T10:56:51.191571927Z caller=stdlib.go:105 caller=server.go:3137 msg="http: TLS handshake error from --.--.--.--:1224: remote error: tls: bad certificate"
ts=2022-04-27T10:56:51.290907617Z caller=stdlib.go:105 caller=server.go:3137 msg="http: TLS handshake error from --.---.--.--:1529: remote error: tls: bad certificate"
level=info ts=2022-04-27T10:56:51.291183084Z caller=operator.go:351 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2022-04-27T10:56:51.291560353Z caller=operator.go:1221 component=prometheusoperator key=cattle-monitoring-system/rancher-monitoring-prometheus msg="sync prometheus"`

**Expected Result**
monitoring installs successfully

**Screenshots**
![Screen Shot 2022-04-27 at 8 00 59 AM](https://user-images.githubusercontent.com/89212856/165514152-baf758ab-fc8e-4d3c-a546-22ba9005d713.png)

**Additional context**

**Comment by ronhorton** [comment]
This issue is also occurring on rke2 downstream cluster.
![Screen Shot 2022-04-27 at 8 09 11 AM](https://user-images.githubusercontent.com/89212856/165515030-deb0f6a5-38e5-40a7-ae71-97874f35c5c3.png)

**Comment by aiyengar2** [comment]
@ronhorton we didn't add support for k8s 1.22 clusters till 100.1.1+up19.0.3.

Related PR: https://github.com/rancher/charts/pull/1766

Related Issues: https://github.com/rancher/rancher/issues/35571, https://github.com/rancher/rancher/issues/35751, https://github.com/rancher/rancher/issues/36522

**Comment by ronhorton** [comment]
issue ended up being a formatting issue with the sachet config.yaml - an extra space somewhere in the file.
