### ISSUE TITLE
can't start rancher in single server 

### ISSUE THREAD

**Issue by iceofsea** [rancher/rancher#37485]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart):
   docker version 20.10.14

when I use the command to start rancher, but rancher can't start 
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher 

Rancher server logs:

2022/04/27 05:19:34 [INFO] Rancher version v2.6.4 (4b4e29678) is starting
2022/04/27 05:19:34 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/04/27 05:19:34 [INFO] Listening on /tmp/log.sock
2022/04/27 05:19:34 [INFO] Waiting for k3s to start
2022/04/27 05:19:35 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/04/27 05:19:47 [INFO] Running in single server mode, will not peer connections
2022/04/27 05:19:47 [INFO] Applying CRD features.management.cattle.io
2022/04/27 05:19:47 [INFO] Waiting for CRD features.management.cattle.io to become available
2022/04/27 05:19:48 [INFO] Done waiting for CRD features.management.cattle.io to become available
2022/04/27 05:19:50 [INFO] Applying CRD navlinks.ui.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD clusters.management.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD apiservices.management.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD clusterregistrationtokens.management.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD settings.management.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD preferences.management.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD features.management.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD clusterrepos.catalog.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD operations.catalog.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD apps.catalog.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD fleetworkspaces.management.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD bundles.fleet.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD clusters.fleet.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD managedcharts.management.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD clusters.provisioning.cattle.io
2022/04/27 05:19:50 [INFO] Applying CRD clusters.provisioning.cattle.io
2022/04/27 05:19:51 [INFO] Applying CRD rkeclusters.rke.cattle.io
2022/04/27 05:19:51 [INFO] Applying CRD rkecontrolplanes.rke.cattle.io
2022/04/27 05:19:51 [INFO] Applying CRD rkebootstraps.rke.cattle.io
2022/04/27 05:19:51 [INFO] Applying CRD rkebootstraptemplates.rke.cattle.io
2022/04/27 05:19:51 [INFO] Applying CRD rkecontrolplanes.rke.cattle.io
2022/04/27 05:19:51 [INFO] Applying CRD custommachines.rke.cattle.io
2022/04/27 05:19:51 [INFO] Applying CRD etcdsnapshots.rke.cattle.io
2022/04/27 05:19:51 [INFO] Applying CRD clusters.cluster.x-k8s.io
2022/04/27 05:19:51 [INFO] Applying CRD machinedeployments.cluster.x-k8s.io
2022/04/27 05:19:51 [INFO] Applying CRD machinehealthchecks.cluster.x-k8s.io
2022/04/27 05:19:51 [INFO] Applying CRD machines.cluster.x-k8s.io
2022/04/27 05:19:51 [INFO] Applying CRD machinesets.cluster.x-k8s.io
2022/04/27 05:19:51 [INFO] Waiting for CRD machinesets.cluster.x-k8s.io to become available
2022/04/27 05:19:52 [INFO] Done waiting for CRD machinesets.cluster.x-k8s.io to become available
2022/04/27 05:19:52 [INFO] Creating CRD authconfigs.management.cattle.io
2022/04/27 05:19:52 [INFO] Creating CRD groupmembers.management.cattle.io
2022/04/27 05:19:52 [INFO] Creating CRD groups.management.cattle.io
2022/04/27 05:19:52 [INFO] Creating CRD tokens.management.cattle.io
2022/04/27 05:19:52 [INFO] Creating CRD userattributes.management.cattle.io
2022/04/27 05:19:52 [INFO] Creating CRD users.management.cattle.io
2022/04/27 05:19:52 [INFO] Waiting for CRD userattributes.management.cattle.io to become available
2022/04/27 05:19:53 [INFO] Done waiting for CRD userattributes.management.cattle.io to become available
2022/04/27 05:19:53 [INFO] Waiting for CRD users.management.cattle.io to become available
2022/04/27 05:19:53 [INFO] Done waiting for CRD users.management.cattle.io to become available
2022/04/27 05:19:54 [INFO] Creating CRD catalogs.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD apps.project.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD apprevisions.project.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD catalogtemplates.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD pipelineexecutions.project.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD catalogtemplateversions.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD pipelinesettings.project.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD clusteralerts.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD clusterroletemplatebindings.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD dynamicschemas.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD pipelines.project.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD clusteralertgroups.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD sourcecodecredentials.project.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD etcdbackups.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD clustercatalogs.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD clusterloggings.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD globalrolebindings.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD sourcecodeproviderconfigs.project.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD globalroles.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD sourcecoderepositories.project.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD clusteralertrules.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD clustermonitorgraphs.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD kontainerdrivers.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD clusterscans.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD nodedrivers.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD nodepools.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD composeconfigs.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD nodetemplates.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD multiclusterapps.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD multiclusterapprevisions.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD nodes.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD monitormetrics.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD podsecuritypolicytemplateprojectbindings.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD notifiers.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD podsecuritypolicytemplates.management.cattle.io
2022/04/27 05:19:54 [INFO] Waiting for CRD pipelineexecutions.project.cattle.io to become available
2022/04/27 05:19:54 [INFO] Creating CRD projectalerts.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD projectnetworkpolicies.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD projectroletemplatebindings.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD projects.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD rkek8ssystemimages.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD projectalertgroups.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD rkek8sserviceoptions.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD projectcatalogs.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD projectloggings.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD rkeaddons.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD projectalertrules.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD roletemplates.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD projectmonitorgraphs.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD cisconfigs.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD samltokens.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD clustertemplates.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD cisbenchmarkversions.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD clustertemplaterevisions.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD templates.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD templateversions.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD templatecontents.management.cattle.io
2022/04/27 05:19:54 [INFO] Creating CRD globaldnses.management.cattle.io
2022/04/27 05:19:54 [INFO] Waiting for CRD nodepools.management.cattle.io to become available
2022/04/27 05:19:54 [INFO] Creating CRD globaldnsproviders.management.cattle.io
2022/04/27 05:19:54 [INFO] Waiting for CRD projectalerts.management.cattle.io to become available
2022/04/27 05:19:54 [INFO] Done waiting for CRD pipelineexecutions.project.cattle.io to become available
2022/04/27 05:19:54 [FATAL] k3s exited with: exit status 2
INFO: Running k3s server --cluster-init --cluster-reset
2022/04/27 05:20:07 [INFO] Rancher version v2.6.4 (4b4e29678) is starting
2022/04/27 05:20:07 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/04/27 05:20:07 [INFO] Listening on /tmp/log.sock
2022/04/27 05:20:07 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/04/27 05:20:09 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/04/27 05:20:11 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/04/27 05:20:13 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/04/27 05:20:15 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/04/27 05:20:17 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/04/27 05:20:19 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/04/27 05:20:21 [INFO] Running in single server mode, will not peer connections
2022/04/27 05:20:21 [INFO] Applying CRD features.management.cattle.io
2022/04/27 05:20:22 [INFO] Applying CRD navlinks.ui.cattle.io
2022/04/27 05:20:23 [INFO] Applying CRD clusters.management.cattle.io
2022/04/27 05:20:23 [FATAL] failed to list apiextensions.k8s.io/v1, Kind=CustomResourceDefinition for  clusters.management.cattle.io: Get "https://127.0.0.1:6443/apis/apiextensions.k8s.io/v1/customresourcedefinitions?labelSelector=objectset.rio.cattle.io%!F(MISSING)hash%!D(MISSING)6c69a0193584ae34056862dc19c681bd63639e44&timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
INFO: Running k3s server --cluster-init --cluster-reset
2022/04/27 05:20:39 [INFO] Rancher version v2.6.4 (4b4e29678) is starting
2022/04/27 05:20:39 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/04/27 05:20:39 [INFO] Listening on /tmp/log.sock
2022/04/27 05:20:39 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/04/27 05:20:41 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/04/27 05:20:43 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/04/27 05:20:45 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/04/27 05:20:47 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/04/27 05:20:49 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/04/27 05:20:51 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/04/27 05:20:57 [FATAL] k3s exited with: exit status 2

**Comment by DarkNeedle** [comment]
Seems I as well as others are getting this same result. Rancher use to work, seems to be the latest containers, not how far back this goes
