### ISSUE TITLE
EPIC:  CSP adapter

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#37495]
Backend: 
* https://github.com/rancher/rancher/issues/35736
* https://github.com/rancher/rancher/issues/37385
* https://github.com/rancher/rancher/issues/37384
* https://github.com/rancher/rancher/issues/37383
* https://github.com/rancher/rancher/issues/37757
* https://github.com/rancher/rancher/issues/37841

UI: 
* https://github.com/rancher/dashboard/issues/5616
* https://github.com/rancher/dashboard/issues/4916

**Comment by MbolotSuse** [comment]
Backend:
- https://github.com/rancher/rancher/issues/37722

**Comment by samjustus** [comment]
#37757 still needs discussion on what exactly we need to do, and PM is OOO

**Comment by cbron** [comment]
Swapping NS in rancher with two PRs. We can break out these things into "charts" issue if we need to. 
https://github.com/rancher/csp-adapter/pull/6
https://github.com/rancher/rancher/pull/37828

**Comment by MbolotSuse** [comment]
Docs issue:
*  https://github.com/rancher/docs/issues/4131

**Comment by MbolotSuse** [comment]
New Backend Issue:
* https://github.com/rancher/rancher/issues/37918

**Comment by MbolotSuse** [comment]
More Backend Issues for the adapter:
- https://github.com/rancher/rancher/issues/38050
- https://github.com/rancher/rancher/issues/38051

**Comment by cbron** [comment]
Message bug: https://github.com/rancher/rancher/issues/38024
