### ISSUE TITLE
UI breaks with host description

### ISSUE THREAD

**Issue by hwinkel** [rancher/rancher#3749]
Rancher Version: 0.59.1

Docker Version: 1.10.2

Browser: latest chrome

Steps to Reproduce: just add a description to a host and look at the details screen. The box with the description breaks UI and spawns the outer div or viewport

**Comment by rvion** [comment]
![image](https://cloud.githubusercontent.com/assets/2150990/13497791/643fc62a-e157-11e5-8046-4caeac2f473e.png)

**Comment by tfiduccia** [comment]
Version - master UI 3/3
Verified fixed
