### ISSUE TITLE
Unable to install rancher backup chart version 2.0.1 as the CRDs have apiextensions.k8s.io/v1beta1 api versions

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37492]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6.4
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2, `v1.22.8+rke2r1`
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.21.10
- Cluster Type (Local/Downstream): `Local 3 worker +  etcd + cp RKE2`

**Describe the bug**
Installation of the backup/restore chart 2.0.1 fails on the local cluster 

This is because the Custom resource definitions for backup/restore/resoruceset yaml template files have the API versions `[apiextensions.k8s.io/v1beta1](http://apiextensions.k8s.io/v1beta1)` which are not supported with k8s 1.22. 

Chart should have a warning saying that the chart version `v2.0.1` will not work if the k8s version on the local cluster is `v1.22` and above.

**To Reproduce**
Create a local cluster RKE1 or RKE2 version `v1.22.8+rke2r1`
Install rancher backup/restore chart version `v2.0.1`

**Result**
Installation fails with the error 
```
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

**Expected Result**
Backup/restore chart `v2.0.1` should have annotation added in the chart and be hidden for the clusters v1.22 and above.

**Comment by nickwsuse** [comment]
`Verified on v2.6.7-rc1`

If you're on 2.6-head you'll still see the incompatible versions, but as long as you're using a release cut or official build then only the compatible versions are shown.
