### ISSUE TITLE
Etcd snapshot restore gets stuck draining node.

### ISSUE THREAD

**Issue by phillipsj** [rancher/rancher#37499]
**Rancher Server Setup**
- Rancher version: v2.6-300a8fb94e5d3ffd1e0faa9224745bcff04ea1c3-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm, K3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:  v1.22.9-rc4+rke2r1
- Cluster Type (Local/Downstream): Custom

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions:
   
**Describe the bug**

When performing an etcd snapshot and restore on an RKE2 custom cluster, the cluster gets stuck in draining. The etcd node's RKE2 service will not start.

**To Reproduce**
1. Create an RKE2 v1.22.9-rc4+rke2r1 custom cluster with 1 controlplane, 1 etcd, and 1 linux worker.
2. Take an etcd snapshot
3. Restore the etcd snapshot.

**Result**

The etcd node gets stuck in draining and a cluster agent connection failure. 

![image](https://user-images.githubusercontent.com/1568133/165625186-62d9ca52-85a2-4abb-b10f-45adba409fdd.png)

RKE2 logs from the etcd server.

```
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
   Loaded: loaded (/usr/local/lib/systemd/system/rke2-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2022-04-27 20:17:53 UTC; 4min 43s ago
     Docs: https://github.com/rancher/rke2#readme
 Main PID: 2329 (code=exited, status=1/FAILURE)

Apr 27 20:13:03 etcd rke2[2329]: time="2022-04-27T20:13:03Z" level=info msg="Applying CRD helmchartconfigs.helm.cattle.io"
Apr 27 20:13:03 etcd rke2[2329]: time="2022-04-27T20:13:03Z" level=info msg="Successfully set etcd role label and annotations on node etcd"
Apr 27 20:14:25 etcd rke2[2329]: time="2022-04-27T20:14:25Z" level=info msg="Updating TLS secret for rke2-serving (count: 13): map[field.cattle.i
Apr 27 20:14:25 etcd rke2[2329]: time="2022-04-27T20:14:25Z" level=info msg="Active TLS secret rke2-serving (ver=1800) (count 13): map[field.catt
Apr 27 20:17:53 etcd rke2[2329]: time="2022-04-27T20:17:53Z" level=error msg="Remotedialer proxy error" error="websocket: close 1006 (abnormal cl
Apr 27 20:17:53 etcd systemd[1]: Stopping Rancher Kubernetes Engine v2 (server)...
Apr 27 20:17:53 etcd rke2[2329]: time="2022-04-27T20:17:53Z" level=fatal msg="context canceled"
Apr 27 20:17:53 etcd systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 20:17:53 etcd systemd[1]: rke2-server.service: Failed with result 'exit-code'.
Apr 27 20:17:53 etcd systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
```

**Expected Result**

That the snapshot is applied and the server comes back online.

**Screenshots**
 
Taking snapshot

![repro-take-snapshot](https://user-images.githubusercontent.com/1568133/165625478-1a0c9e3d-62d2-4de9-9052-30c571ff74b9.png)

Restoring snapshot

![repro-restore-snapshot](https://user-images.githubusercontent.com/1568133/165625516-7852041e-fb32-4554-88e5-a22aec2cb9dd.png)

Stuck restoring

![repro-restore-snapshot](https://user-images.githubusercontent.com/1568133/165625561-e6ea3658-b4d1-41eb-bc48-e52601aea060.png)

**Additional context**

**Comment by Oats87** [comment]
OK.

I think I know why this is broken.

When we deliver an etcd snapshot restore plan, we deliver our plans without abiding by drain/cordon/etc. as we know we are basically taking a baseball bat to the cluster.

The issue is that after an etcd restore operation is completed, we then rely on the next step (i.e. reconcile) to deliver a conventional plan to the node so that the corresponding supervisor service (`k3s` or `rke2`) is started. Now that our bootstrap node is always drained w/ a concurrency of 1, we need to figure out a way to deliver a plan directly to the node so that the service is able to start. 

I'm working on a few solutions for this.

**Comment by phillipsj** [comment]
@snasovich @sirredbeard I just tested this out and it is working.

**Comment by markusewalker** [comment]
Verified on `v2.6-head` that this is resolved.

**ENVIRONMENT DETAILS**
- Ubuntu 20.04: Docker Install
- Ubuntu 18.04 HA
- Rancher version: `v2.6.5-rc6` & `v2.6-head` https://github.com/rancher/rancher/commit/a31f5b8613d994122d9a7460700b028e61970ab5
- RKE2 version: v1.23.6+rke2r1
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to Rancher UI in a browser.
2. Created a downstream Linode RKE2 cluster with 1 control plane, 1 etcd and 1 Linux worker.
3. Verified that the cluster comes up as Active and the machine pools are all listed as Active.
4. Successfully took an etcd snapshot:
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/52591819/166522403-f9cc70f1-10de-40c6-9a8f-0ebb75dbdd4e.png">
5. Created a test daemonsets and test deployments:
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/52591819/166522421-d8fad213-a54e-4f5b-a9dd-098fea98217e.png">

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/52591819/166522444-f177ec35-2851-40ed-ba8b-9af9b9a5ff85.png">

6. Successfully restored the etcd snapshot and verified cluster and machine pools appear in Active state:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/52591819/166522461-c15fafd7-3ab9-400b-8085-9a91249463bb.png">

7. Additionally, verified that the created workload resources no longer appear after restoring to the snapshot.
8. Successfully repeated steps 2-7, but used a downstream Linode RKE2 cluster with 1 control plane, 3 etcd and 1 Linux worker.
9. Successfully repeated steps 2-7, but used a downstream Linode RKE2 cluster with 1 control plane, 1 etcd, 1 Linux worker and S3 bucket enabled.

However, it was noted that while it seems to be working as expected, the actual snapshot process seems incorrect. Specifically, I noted the following workflow: cluster reconciles, etcd node drains, control plane reconciles and then provisioning finishes.

Some logs below:

```
[INFO ] waiting for etcd snapshot on node sowmya-rke2-pool1-20455ee3-nc9mh
[INFO ] draining bootstrap node(s) sowmya-rke2-pool1-76dc84db6d-k4nfd: draining node
[INFO ] configuring bootstrap node(s) sowmya-rke2-pool1-76dc84db6d-k4nfd: waiting for plan to be applied
[INFO ] draining etcd node(s) sowmya-rke2-pool1-76dc84db6d-5rl8z: draining node
[INFO ] configuring etcd node(s) sowmya-rke2-pool1-76dc84db6d-5rl8z,sowmya-rke2-pool1-76dc84db6d-9cv46
[INFO ] draining etcd node(s) sowmya-rke2-pool1-76dc84db6d-9cv46: draining node
[INFO ] configuring etcd node(s) sowmya-rke2-pool1-76dc84db6d-9cv46: drain completed
[INFO ] configuring etcd node(s) sowmya-rke2-pool1-76dc84db6d-9cv46: waiting for plan to be applied
[INFO ] configuring control plane node(s) sowmya-rke2-pool2-5b7c6dbccd-l4v85,sowmya-rke2-pool2-5b7c6dbccd-sc6qq
[INFO ] configuring control plane node(s) sowmya-rke2-pool2-5b7c6dbccd-sc6qq: waiting for plan to be applied
[INFO ] provisioning done
```
