### ISSUE TITLE
Worker node of RKE2 cluster is stuck in `Reconciling` state on a Linode cluster when `createPrivateIp: true`

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#37500]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `7db4fe4`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: `v1.22.9-rc4+rke2r1` --> RKE2 downstream cluster - Linode RKE2 - 1 node all roles and 1 worker node

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

   
**Describe the bug**
Worker node of RKE2 cluster is stuck in `Reconciling` state

**To Reproduce**

- Deploy an RKE2 linode cluster - 1 node all roles and 1 worker node
- Set `createPrivateIp: true` on the machine pools
- The worker node is stuck in Reconciling state
- Server logs

```
Apr 27 20:28:22 sowmya-linode-26head-pool1-029277cb-4nxh7 rke2[5531]: time="2022-04-27T20:28:22Z" level=error msg="runtime core not ready"
Apr 27 20:28:23 sowmya-linode-26head-pool1-029277cb-4nxh7 rke2[5531]: time="2022-04-27T20:28:23Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Apr 27 20:28:27 sowmya-linode-26head-pool1-029277cb-4nxh7 rke2[5531]: time="2022-04-27T20:28:27Z" level=info msg="Defragmenting etcd database"
Apr 27 20:28:27 sowmya-linode-26head-pool1-029277cb-4nxh7 rke2[5531]: time="2022-04-27T20:28:27Z" level=info msg="certificate CN=rke2,O=rke2 signed by CN=rke2-server-ca@1651088172: notBefore=2022-04-27 19:36:12 +0000 UTC notAfter=2023-04-27 20:28:27 +0000 UTC"
Apr 27 20:28:27 sowmya-linode-26head-pool1-029277cb-4nxh7 rke2[5531]: time="2022-04-27T20:28:27Z" level=info msg="certificate CN=rke2,O=rke2 signed by CN=rke2-server-ca@1651088172: notBefore=2022-04-27 19:36:12 +0000 UTC notAfter=2023-04-27 20:28:27 +0000 UTC"
Apr 27 20:28:27 sowmya-linode-26head-pool1-029277cb-4nxh7 rke2[5531]: time="2022-04-27T20:28:27Z" level=info msg="certificate CN=rke2,O=rke2 signed by CN=rke2-server-ca@1651088172: notBefore=2022-04-27 19:36:12 +0000 UTC notAfter=2023-04-27 20:28:27 +0000 UTC"
Apr 27 20:28:27 sowmya-linode-26head-pool1-029277cb-4nxh7 rke2[5531]: time="2022-04-27T20:28:27Z" level=info msg="certificate CN=rke2,O=rke2 signed by CN=rke2-server-ca@1651088172: notBefore=2022-04-27 19:36:12 +0000 UTC notAfter=2023-04-27 20:28:27 +0000 UTC"
Apr 27 20:28:27 sowmya-linode-26head-pool1-029277cb-4nxh7 rke2[5531]: time="2022-04-27T20:28:27Z" level=info msg="Failed to test data store connection: this server is a not a member of the etcd cluster. Found [-d1954041=https://74.207.253.152:2380/], expect: -d1954041=192.168.215.5"
Apr 27 20:28:27 sowmya-linode-26head-pool1-029277cb-4nxh7 rke2[5531]: time="2022-04-27T20:28:27Z" level=info msg="certificate CN=rke2,O=rke2 signed by CN=rke2-server-ca@1651088172: notBefore=2022-04-27 19:36:12 +0000 UTC notAfter=2023-04-27 20:28:27 +0000 UTC"
Apr 27 20:28:27 sowmya-linode-26head-pool1-029277cb-4nxh7 rke2[5531]: time="2022-04-27T20:28:27Z" level=info msg="certificate CN=rke2,O=rke2 signed by CN=rke2-server-ca@1651088172: notBefore=2022-04-27 19:36:12 +0000 UTC notAfter=2023-04-27 20:28:27 +0000 UTC"
Apr 27 20:28:27 sowmya-linode-26head-pool1-029277cb-4nxh7 rke2[5531]: time="2022-04-27T20:28:27Z" level=error msg="runtime core not ready"
Apr 27 20:28:28 sowmya-linode-26head-pool1-029277cb-4nxh7 rke2[5531]: time="2022-04-27T20:28:28Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
```

**Note:**
- I deployed another DO RKE2 1 node all roles and 1 worker node cluster on the same setup, and that came up Active. No issues seen on that.

**Comment by markusewalker** [comment]
Verified on `v2.6-head` https://github.com/rancher/rancher/commit/a31f5b8613d994122d9a7460700b028e61970ab5.

**ENVIRONMENT DETAILS**
-  Ubuntu 20.04: Docker Install
- Ubuntu 18.04 HA
- Rancher version: v2.6.5-rc6 & v2.6-head https://github.com/rancher/rancher/commit/a31f5b8613d994122d9a7460700b028e61970ab5
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to Rancher UI. Created a standard user and login to Rancher as that new user.
2. Created a downstream Linode RKE2 cluster and enabled Private Networking in cluster configuration.
3. Verified that the cluster and machine pools came up as active:
![image](https://user-images.githubusercontent.com/52591819/166487238-8e9e0686-9098-4e09-bde1-e3aea78d4813.png)
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/52591819/166486890-b3b03a7d-c791-46d3-8182-0dd3fe3b06bd.png">
5. In Cluster Management, navigated to the cluster's configuration and verified Private Networking is still set for the machine pools after cluster creation:
<img width="146" alt="image" src="https://user-images.githubusercontent.com/52591819/166486924-978df51e-d9e8-4e4d-b9d8-0470bac08d44.png">
