### ISSUE TITLE
`"privateNetworking":true` is ignored for DigitalOcean node-provisioned RKE2 clusters

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#37510]
**Rancher Server Setup**
- Rancher version: 2.6-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Irrelevant
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: Irrelevant
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2 DO node-provisioned

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Any
  - If custom, define the set of permissions:

   
**Describe the bug**
When provisioning a new DO cluster with RKE2, checking Additional DigitalOcean Options --> Private Networking has no effect.
See more info in https://github.com/rancher/dashboard/issues/5603#issuecomment-1111916075

**Expected Result**
It's expected for DO nodes to have private IP with this option checked.

**Comment by markusewalker** [comment]
@jakefhyde I assume once the `rancher/machine` is bumped to `v0.15.0-rancher89`, I'll be good to test this issue, correct?

**Comment by markusewalker** [comment]
Verified in `v2.6-head` https://github.com/rancher/rancher/commit/3506e43cee0d391bd3fdc32d3d98690b8abef402.

**ENVIRONMENT DETAILS**
- Rancher Install: Helm
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/3506e43cee0d391bd3fdc32d3d98690b8abef402
- Browser: Chrome

**TEST RESULT**
PASS

VERIFICATION STEPS
1. Setup and Rancher and navigate to the UI in a brows.er
2. Provisioned a downstream RKE2 DO node driver cluster.
     - Ensured that under `Additional DigitialOcean Options` that `Private Networking` is selected.
3. Verify that the cluster came up as `Active` and that the nodes come up as `Active` as well:
![image](https://user-images.githubusercontent.com/52591819/178529319-49e76ce6-80d9-4d7a-a2be-2a7b654be4c5.png)
![image](https://user-images.githubusercontent.com/52591819/178529357-ab7c2752-4712-404c-8b81-1f9d14ceed9c.png)
![image](https://user-images.githubusercontent.com/52591819/178529399-f9b091d4-3a74-4a26-84c8-650542340684.png)
4. Edited the Config and verified that `Private Networking` is still checked off:
![image](https://user-images.githubusercontent.com/52591819/178528931-b7904852-1d41-4195-9d71-19daa978ab0a.png)
![image](https://user-images.githubusercontent.com/52591819/178528976-f9480e95-5b67-4bb2-955a-f6b75ea5704e.png)
![image](https://user-images.githubusercontent.com/52591819/178529010-ebc96f67-e420-4bb1-a49c-95f2c59aacf5.png)
