### ISSUE TITLE
Intermittently on upgrade, nodes become unavailable and unrecoverable with error MemoryPressure is Unknown

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#37514]
**Rancher Server Setup**
- Rancher version: v2.6.5-rc3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): helm rke2
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: Upgrade from v1.21.10+rke2r2 to v1.21
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): EC2 node driver
- Node role configuration: 3 etcd-only nodes, 2 controlplane-only nodes, 3 worker-only nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
admin

**Describe the bug**

All but one node became unavailable after attempting upgrade on a provisioned cluster from v1.21.10+rke2r2 to v1.22.9-rc4+rke2r1

- Error message on all nodes in UI:  `Node condition MemoryPressure is Unknown. Node condition DiskPressure is Unknown. Node condition PIDPressure is Unknown. Node condition Ready is Unknown.`
- rancher-system-agent logs:
```
Apr 27 20:36:44 max122ha-etcd-489effff-sflcd rancher-system-agent[4766]: time="2022-04-27T20:36:44Z" level=info msg="[Applyinator] No image provided, creating empty working directory /var/lib/rancher/agent/work/20220427-203644/d8cd0194e1f617a11955943e7993f0088a22e1f6be7e7e14b4ef0cebc25f04ad_0"
Apr 27 20:36:44 max122ha-etcd-489effff-sflcd rancher-system-agent[4766]: time="2022-04-27T20:36:44Z" level=info msg="[Applyinator] Running command: sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null]"
Apr 27 20:36:44 max122ha-etcd-489effff-sflcd rancher-system-agent[4766]: time="2022-04-27T20:36:44Z" level=info msg="[d8cd0194e1f617a11955943e7993f0088a22e1f6be7e7e14b4ef0cebc25f04ad_0:stdout]: Name                                                  Location                                                                                               Size     Created"
Apr 27 20:36:44 max122ha-etcd-489effff-sflcd rancher-system-agent[4766]: time="2022-04-27T20:36:44Z" level=info msg="[d8cd0194e1f617a11955943e7993f0088a22e1f6be7e7e14b4ef0cebc25f04ad_0:stdout]: etcd-snapshot-max122ha-etcd-489effff-sflcd-1651089600 file:///var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-max122ha-etcd-489effff-sflcd-1651089600 18960416 2022-04-27T20:00:00Z"
Apr 27 20:36:44 max122ha-etcd-489effff-sflcd rancher-system-agent[4766]: time="2022-04-27T20:36:44Z" level=info msg="[Applyinator] Command sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null] finished with err: <nil> and exit code: 0"
```
- only node that shows active is control-plane node 
- active cp node appears to have upgraded 
- all etcd nodes appear to have upgraded 

**To Reproduce**
 
_These steps do not reproduce this every time, but I saw this happen twice out of 8 tries go into the unrecoverable state_
1. Provision an rke2 cluster using v1.21.10+rke2r2
2. Upgrade that cluster to v1.22.9-rc4+rke2r2

**Result**
All etcd nodes appear to upgrade, and one control-plane node appears to have upgraded, but then the etcd nodes go into this unavailable state. The final cp node doesn't upgrade, and then therefore the workers do not upgrade.

**Expected Result**

There should be no error state and all nodes should upgrade successfully.

**Screenshots**

I lost access to my rancher instance so cannot provide screenshots at this time, but will edit this issue if I'm able to recreate again.

**Additional context**

_WORKAROUND:_
I was able to get around this by doing the following:
1. ssh into the affected nodes (this is still available using the rancher UI)
2. Run `rke2-killall.sh`
3. Run `sudo systemctl enable rke2-server --now`

**Comment by thedadams** [comment]
This is an RKE2 [issue](https://github.com/rancher/rke2/issues/2834).

**Comment by ShylajaDevadiga** [comment]
Validated as part of patch validation on v1.21.12-rc1+rke2r2, v1.22.9-rc1+rke2r2, v1.23.6-rc1+rke2r2 using 3 etcd, 2 cp, 2 worker node using rancher provisioning. Upgrade was successful and upgrade tests have passed
