### ISSUE TITLE
Multiple host names 

### ISSUE THREAD

**Issue by blandes** [rancher/rancher#3751]
Rancher Version: 59.1

Docker Version: 1.10

OS: RancherOS. 42.1

Cannot produce different host names on one server with agent and server on the same instance. 

I've have been trying for a while but exactly how does one make several host names on server? 

gitlab.foobar.com
drone.foobar.com
rancher.foobar.com

How does one do this? I cannot for the life of me replicate the above. Should I have my services on host, managed, or bridged? Can I use the UI? Or should I setup a nginx on host network?

**Comment by looztra** [comment]
any success with the advanced routing? http://docs.rancher.com/rancher/rancher-ui/applications/stacks/adding-balancers/#advanced-routing-optons http://docs.rancher.com/rancher/rancher-compose/rancher-services/#advanced-load-balancing-l7
