### ISSUE TITLE
Selected catalog text and drop-down text are significantly different sizes

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3752]
Version: master UI 3/3

Steps to Reproduce: 
1.  Go to Catalog page
2.  Select a catalog
3.  Click on the Catalog drop-down list

Results: The selected catalog text is way bigger then the text in the drop-down.
![image](https://cloud.githubusercontent.com/assets/11514927/13506588/074a13dc-e13c-11e5-9c4f-1de3f8b9bfa9.png)

Expected:  Not sure which is the correct size, but they should be closer

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/501

**Comment by tfiduccia** [comment]
Version - master UI 3/3
Verified Fixed
