### ISSUE TITLE
moved namespaces do not receive the RBAC permissions of their new project

### ISSUE THREAD

**Issue by randyrue** [rancher/rancher#37525]
**Rancher Server Setup**
- Rancher version:2.6.4
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: 1.22.7
- Cluster Type (Local/Downstream): bare metal

**User Information**
- What is the role of the user logged in? ADMIN
   
**Describe the bug**

moved namespaces do not receive the RBAC permissions of their new project

**To Reproduce**
 
create a new project and assign project owner roles to some users
move an existing namespace from another project into the new project
try to launch jobs/pods as a user that's a project owner on the new project

**Result**
access denied
**Expected Result**
successful job/pod

**Additional context**
workaround seems to be to move the namespace to the new project and then to add the users/roles to the project but for an existing project this means removing and re-adding all users/roles and work/jobs/pods fail to launch until the needed service accounts have bee re-added

**Comment by BBQigniter** [comment]
this issue still is still present in 2.6.6
