### ISSUE TITLE
After modifying cluster configuration to have a new node pool, cluster's status shows as `Active` when it should show `Updating`

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#37528]
**Setup**
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/d5e68641e8f5f2d05bfa82731e5d8148e0f45017
- Browser type & version: Chrome

**Describe the bug**

After creating a cluster within Rancher UI, I edited the freshly created cluster's config to add a new worker pool. The actual addition of the worker nodes in this new pool went smoothly. However, the issue is that the status of the cluster showed as `Active` the whole time instead of having a status of `Updating`.

Additionally, when looking at the worker nodes being created in the pool, this is further shown. Screenshots below:

![image](https://user-images.githubusercontent.com/52591819/165825379-bee4c779-4966-403e-a90a-9f7dcf541a62.png)
![image](https://user-images.githubusercontent.com/52591819/165825404-01523c49-b4c7-47de-bca3-9dc90d05710b.png)

Related issue: https://github.com/rancher/dashboard/issues/5443. This issue was created here as this is more of a backend fix that needs to be fixed in Rancher as opposed to the UI.

**To Reproduce**

1. Setup Rancher and create a Standard user and login to Rancher UI as that user.
2. Create an RKE1 cluster with 1 node pool that has 1 cp, 1 etcd, 1 worker.
3. Once the cluster Is created, click the cluster and edit the config to add a worker node pool of 2 machines.
4. The status of the machine shows as `Active` despite the worker nodes not being `Active` themselves.

**Result**
The cluster shows as `Active` while the worker nodes are not in a state of `Active` and are provisioning themselves still to join the cluster.

**Expected Result**

The cluster should stay in a state of `Updating` until the worker nodes are in a state of `Active`.

**Comment by thedadams** [comment]
In the case of an RKE2 provisioned cluster in Rancher, the cluster will go into an Updating state. However, in the case of adding/deleting worker-nodes in an RKE1 cluster, Rancher will not be calling RKE at all so it is likely that the cluster has/will never go into an Updating state in this case.

@slickwarren @sowmyav27 Please add any additional information if we have gotten anything incorrect here.

For now, moving to "To Test" so it can be verified that this is the expected behavior.

**Comment by markusewalker** [comment]
@thedadams thanks for your explanation. For further clarification, in the case that RKE1 is the cluster being modified, the status will remain as `Active` as Rancher is not calling RKE.

However, if RKE2 is the cluster being modified, then that is when the status will change to `Updating` state as Rancher makes the calls needed to update the state.

Is my understanding correct?

**Comment by markusewalker** [comment]
Spoke with @thedadams regarding this being expected behavior. Additionally, looked at Rancher `v2.5.13`, repeated the workflow and verified it is the same behavior there as well.

Closing this as functionality working as designed.
