### ISSUE TITLE
Potential Issues with Rancher 2.5.x -> 2.6.x upgrade when using v1 apps (Project Monitoring) in RKE1 clusters

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#37533]
There is a [Rancher issue](https://github.com/rancher/rancher/issues/36260) filed by the community that indicates we may have possible issues with upgrading Rancher from 2.5.x -> 2.6.x when v1 project monitoring is enabled. 

[I have a PR up](https://github.com/rancher/rancher/pull/37532) that addresses the panic. 

My concern comes from the fact that the code path for v1 app monitoring upgrades has not changed in a few years and is now causing Rancher to crash in 2.6 when it was functioning as expected in 2.5.x. This upgrade path should not hit the panic unless the v1 app configuration was modified or lost during the upgrade. With projects being shuffled around in 2.6 it leads me to believe that we are losing v1 app config for apps in projects during the Rancher upgrade to 2.6

**Comment by slickwarren** [comment]
closing as a dupe  https://github.com/rancher/rancher/issues/36260
