### ISSUE TITLE
Container shows command twice

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#3753]
Also check other places that use the container-row component:
  - Containers list
  - Host containers list
  - Service containers list
  - VM list

![image](https://cloud.githubusercontent.com/assets/753917/13506799/06721d5a-e13d-11e5-99d8-247ec0ae91ba.png)

**Comment by tfiduccia** [comment]
For the container list in Services.  It looks like the Image (Command) is supposed to show up in that row.  Not just the image name.  But only the image name shows up.  So we should either remove the (Command) or add it there.
![image](https://cloud.githubusercontent.com/assets/11514927/13507527/2b7dfa9e-e140-11e5-8e17-61115d96b5af.png)

**Comment by tfiduccia** [comment]
Version - master 3/4
Verified fixed
