### ISSUE TITLE
RKE2 node driver cluster does not work with OL 8.4 and 8.3 public AMIs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#37537]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `311f462`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.22.9+rke2r1`
- Cluster Type (Local/Downstream): Downstream node driver - 1node all roles

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

   
**Describe the bug**
RKE2 node driver cluster does not work with OL 8.4 and 8.3 public AMIs

**To Reproduce**

- Deploy a 1 node all roles using Public AMIs from AWS
- Clusters fail to come up
- Error on machine pool page on the node shows `Error applying plan -- check rancher-system-agent.service logs on node for more information`
- No obvious errors in server/agent logs

**Comment by thedadams** [comment]
Given that OL 8.4 is not in the support matrix for Rancher v2.6.5 for provisioned RKE2 cluster, this is being moved out.

Reference: https://confluence.suse.com/pages/viewpage.action?spaceKey=EN&title=2.6.5+Support+Matrix

**Comment by Jono-SUSE-Rancher** [comment]
We currently support OL through 9.2 on v2.7.7 so going to close this as it's no longer valid.
