### ISSUE TITLE
RKE2 cluster name's max character limit is truly 63; Not 253;

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#37535]
**Rancher Server Setup**
- Rancher version: `v2.6-a01b164f2e371f04aea7c0c1864c687b8ad70cca-head`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm
- Proxy/Cert Details: Self-signed certs

**Information about the Cluster**
- Kubernetes version: `v1.22.9+rke2r1`
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
Node driver and Custom clusters

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Admin

   
**Describe the bug**
RKE2 cluster `Create` page allows a max character limit of 253 when naming a cluster; Almost immediately after submitting the form, the cluster fails to provision with errors stating `invalid: metadata.lables: Invalid value - must be no more than 63 characters`;

**To Reproduce**
1. Fresh install of rancher `v2.6-head`
2. Create a downstream RKE2 cluster with a cluster name exceeding 253 characters
3. Reproduced - Cluster name must not exceed 253 characters
4. Adjust cluster name to 253 characters and submit `Create` form
5. Reproduced - Cluster fails to provision; Error regarding max character limit of 63
6. Adjust cluster name to 63 characters and submit `Create` form
7. Cluster successfully provisions
8. Same steps may be followed to reproduce with RKE2 Custom clusters

**Result**
Cluster fails to provision if cluster name's characters exceed 63, although `Create` POST req allows 253, which will always break cluster provisioning

**Expected Result**
Cluster should successfully provision when `Create` cluster form is submitted

**Screenshots**
`Node driver - step 3`
<img width="1464" alt="Screen Shot 2022-04-28 at 5 12 15 PM" src="https://user-images.githubusercontent.com/46494969/165987200-39219af7-2a40-40a2-a6ea-83f6305e904b.png">

`Node driver - step 5`
<img width="651" alt="Screen Shot 2022-04-28 at 4 48 53 PM" src="https://user-images.githubusercontent.com/46494969/165987265-4c73849f-dbfa-4b72-ba12-74a87d91f686.png">

`Custom - Max character limit`
<img width="1504" alt="Screen Shot 2022-04-29 at 9 24 37 AM" src="https://user-images.githubusercontent.com/46494969/165987422-80aa5108-c9cc-49b7-a2e1-8a2929461066.png">

`Clusters successful with max character name of 63`
<img width="1506" alt="Screen Shot 2022-04-29 at 9 41 49 AM" src="https://user-images.githubusercontent.com/46494969/165987524-22762a74-3e00-44c8-892c-49f65d333ba5.png">

**Comment by kinarashah** [comment]
According to https://kubernetes.io/docs/concepts/overview/working-with-objects/names/, max limit is 253.

**Comment by kinarashah** [comment]
If fixing in Steve, make sure we don't break other object names.

**Comment by Josh-Diamond** [comment]
Possible duplicate - this seems to be addressed in Dashboard repo [here](https://github.com/rancher/dashboard/issues/5214)

**Comment by thedadams** [comment]
Yes, this seems to be address by the dashboard issue linked above. However, it is still possible to create clusters with names longer than 63 characters by directly applying YAML or using the API. It should be determined if this is enough to consider the issue "fixed" for now.

**Comment by snasovich** [comment]
Given the fix done on the UI and the fact the fix may be not-so-safe, removing it from 2.6.6 milestone.

**Comment by Josh-Diamond** [comment]
Ticket #37535 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6-0e2fdc8060bc74c278d7f043c7846297577fb92c-head`:
1. Fresh install of rancher `v2.6-head`
2. Create an RKE2 cluster in the UI with name less that 64 characters.
3. In your browser, go to `https://<RANCHER_URL/v1/provisioning.cattle.io.clusters/fleet-default/<CLUSTER_NAME>`
4. On the right-hand side, click "Edit"
5. Copy the contents of the middle text area.
6. In your browser, go to `https://<RANCHER_URL>/v1/provisioning.cattle.io.clusters`
7. On the right-hand-side, click `Create`
8. In the first text area, enter the following: `{"name": "<some-really-long-name-with-at-least-sixty-four-characters-and-maybe-a-few-more>", "namespace":"fleet-default"}`
9. In the middle box, paste the stuff you copied in step 4. No need to change anything.
10. Click "Show Request"
11. Click "Send Request"
12. Verified - 422 error response indicating that the cluster object has an invalid name

Screenshot:

`Step 12`
<img width="476" alt="Screen Shot 2022-05-19 at 12 16 37 PM" src="https://user-images.githubusercontent.com/46494969/169385989-dfc9cc68-25d6-4d72-a80e-d182e67d333e.png">
