### ISSUE TITLE
Add 1.23 version for AKS v1 clusters

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37542]
Dashboard related https://github.com/rancher/dashboard/issues/5781

**Comment by thedadams** [comment]
I verified that there are no backend changes for either AKSv1 or v2 provisioning from Rancher. Pulling the versions for AKS clusters is dynamic in both cases and there is nothing hard-coded into Rancher's backend for this use case.

It does seem there is some work to be done in the UI. A comment was left to this effect on the dashboard issue linked above.

**Comment by thedadams** [comment]
This is actually something that needs to be updated in KDM.

**Comment by thedadams** [comment]
PR: https://github.com/rancher/kontainer-driver-metadata/pull/890

**Comment by jiaqiluo** [comment]
The fix is available in the latest 2.6-head 

We should see the 1.23 version showing in the UI when creating AKS clusters.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 4bbee59
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: AKS

----------

### Testing: ###
Tested this issue by creating AKS cluster with v1.23.5

**Result** - Pass
Users can now see 1.23 version showing in the UI when creating AKS clusters. Although there were no changes in the backend, I still checked that basic usecases worked as expected and everything seemed to work as expected.
![image.png](https://zube.io/files/rancher/e3976a9ea1669ff55d0f002081dcc003-image.png)
