### ISSUE TITLE
[RKE2] Any 1.21 versions to be Rancher max at 2.6.4 version for RKE2 provisioning

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#37547]
In Rancher 2.6.5, for RKE2 GA we are supporting only 1.22 and 1.23 RKE2 versions. So we need any 1.21 versions to be Rancher max at 2.6.4 version.

**Comment by sowmyav27** [comment]
**On `2.6.5-rc8`**
<img width="966" alt="Screen Shot 2022-05-06 at 2 11 04 PM" src="https://user-images.githubusercontent.com/26032343/167217922-93d37572-1a3f-45e0-b2f3-b772e94aed0d.png">


k3s still shows 1.21 in the dropdown

**Comment by snasovich** [comment]
Per discussion with @sowmyav27 we want the same change done for k3s for consistency. Opened https://github.com/rancher/kontainer-driver-metadata/pull/902 and will move back to test once merged.

**Comment by snasovich** [comment]
This is now ready to test on `dev-v2.6` KDM.
The only change compared to when previous testing was done is adding `maxChannelServerVersion: v2.6.4` to all 1.21.x k3s versions to hide them from 2.6.5+.

**Comment by jiaqiluo** [comment]
can be validated in the latest v2.6-head

**Comment by sowmyav27** [comment]
**On 2.6-head commit `132b182`**

<img width="900" alt="Screen Shot 2022-05-10 at 11 03 18 AM" src="https://user-images.githubusercontent.com/26032343/167693433-34bc1d93-3d1d-4ed0-995b-1db19b9ffa26.png">

Default rke2 version is 1.23

**Comment by sowmyav27** [comment]
**On 2.6.5-rc9**
<img width="1031" alt="Screen Shot 2022-05-10 at 12 47 24 PM" src="https://user-images.githubusercontent.com/26032343/167710096-dbb8b324-48ec-4585-946c-8870a0295df4.png">
