### ISSUE TITLE
Using Rancher 2.6 as upstream with Rancher 2.5 as downstream doesn't work - clusters are unavailable

### ISSUE THREAD

**Issue by Shaked** [rancher/rancher#37552]
I'm adding this ticket after having a discussion about it in the office hours meeting #37451 with @luthermonson, @Oats87 and @dnoland1. 

**Rancher Server Setup**
- Rancher version: 2.6.3, 2.6.4, 2.5.8 
- Installation option (Docker install/Helm Chart): helm

**Information about the Cluster**
- Kubernetes version: `1.20.15-k3s1` 
- Cluster Type (Local/Downstream): Both. Upstream 2.6.x, downstream 2.5.8

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When using a Rancher 2.6 as upstream and importing Rancher 2.5 as downstream, the downstream Rancher cluster will always be shown as unavailable. 

Having said that, fleet will continue working as expected. 

**To Reproduce**

- Install a Rancher 2.6 instance on a cluster
- Install a Rancher 2.5 instance on another cluster 
- Import the 2.5 instance as a cluster in 2.6 

**Result**

- Cluster 2.5 will be shown as unavailable 

**Expected Result**
Cluster 2.5 should be available the same as 2.6 work. 

**Screenshots**
<img width="1083" alt="Rancher 2022-04-30 14-06-44" src="https://user-images.githubusercontent.com/960015/166102991-5a86bbf8-9cf5-4f4d-8099-efb7795edef2.png">

**Additional context**
I have enabled debug env variables such as:

```
       - env:
          - name: CATTLE_DEBUG
            value: "true"
          - name: RANCHER_DEBUG
            value: "true"
          - name: CATTLE_TUNNEL_DATA_DEBUG
            value: "true"
          - name: DEBUG
            value: "true"
``` 

That resulted with the following log: 

```
time="2022-04-07T22:06:44Z" level=info msg="Rancher agent version v2.6.3-patch2-rc4 is starting"
time="2022-04-07T22:06:44Z" level=info msg="Listening on /tmp/log.sock"
time="2022-04-07T22:06:44Z" level=info msg="Connecting to wss://REDACTED/v3/connect/register with token starting with REDACTED"
time="2022-04-07T22:06:44Z" level=info msg="Connecting to proxy" url="wss://REDACTED/v3/connect/register"
time="2022-04-07T22:06:44Z" level=debug msg="DesiredSet - No change(2) /v1, Kind=Secret cattle-system/stv-aggregation for rancher-stv-aggregation"
time="2022-04-07T22:06:45Z" level=info msg="Starting /v1, Kind=Service controller"
time="2022-04-07T22:06:49Z" level=debug msg="Wrote ping"
time="2022-04-07T22:06:54Z" level=debug msg="Wrote ping"
time="2022-04-07T22:06:59Z" level=debug msg="Wrote ping"
time="2022-04-07T22:07:04Z" level=debug msg="Wrote ping"
time="2022-04-07T22:07:09Z" level=debug msg="Wrote ping"
```

I went through the code which helped me to see that some calls weren't going through. As well,  I saw that maybe without having `cattle-system` as a hardcoded instance (i.e allow installing rancher in a different namespace) might help solving this issue? 

I also spoke about this with Catherine Luse and Donnie Adams in the Slack channel and they gave me more information about the difference between 2.5 and 2.6 agent and that there are caching implementations using two calls instead of one call to the upstream instance.

**Comment by FingerLiu** [comment]
What I concern about is , where is the log showing real errors...

**Comment by FingerLiu** [comment]
> What I concern about is , where is the log showing real errors...

In my case, there it was a DNS issue，after I fixed DNS config(add rancher hostname to coredns config in the downstream cluster)，the cluster status became available and everything went well.

But I did not find logs about this.

**Comment by Shaked** [comment]
Still valid.

**Comment by Shaked** [comment]
Still valid
