### ISSUE TITLE
[CLI] Running `rancher clusters create -h` shows the description `Creates a new empty cluster` twice instead of once

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#37550]
**Rancher Server Setup**
- Rancher version: Rancher CLI `v2.6.5-rc1`
- Installation option (Docker install/Helm Chart): N/A
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): N/A
- Proxy/Cert Details: N/A
   
**Describe the bug**

When running the `rancher clusters create` or `rancher clusters create -h` command to view the usage, it is displaying `Creates a new empty cluster` twice:

```
# rancher clusters create -h
Creates a new empty cluster
Creates a new empty cluster
Usage: 
  rancher clusters create [OPTIONS] [NEWCLUSTERNAME...]

Options:
   --description value         Description to apply to the cluster
   --disable-docker-version    Allow unsupported versions of docker on the nodes, [default=true]
   --import                    Mark the cluster for import, this is required if the cluster is going to be used to import an existing k8s cluster
   --k8s-version value         Kubernetes version to use for the cluster, pass in 'list' to see available versions
   --network-provider value    Network provider for the cluster (flannel, canal, calico) (default: "canal")
   --psp-default-policy value  Default pod security policy to apply
   --rke-config value          Location of an rke config file to import. Can be JSON or YAML format
```
It should only show it once and not twice.

**To Reproduce**
 
1. Install Rancher CLI on a client machine.
2. Run command `rancher clusters create` or `rancher clusters create -h`; should see `Creates a new empty cluster` twice.

**Result**
You see `Creates a new empty cluster` twice when it should be once.

**Expected Result**

I should see `Creates a new empty cluster` once when I run `rancher clusters create` or `rancher clusters create -h`.

**Comment by markusewalker** [comment]
In the function `ClusterCommand`, there are two parameters, namely `Usage` and `Description`. Looking at other commands such as `rancher clusters import` or `rancher clusters delete`, they do not have this; they only have `Usage`.

Removing this [line](https://github.com/rancher/cli/blob/2444900caaa89be5aa63d6f2eb8a854c8e38f421/cmd/cluster.go#L62) should address the issue.

**Comment by markusewalker** [comment]
Noted that this has been installed. Once there is a new RC for 2.6.6, I will be able to verify this and close it out.

**Comment by sowmyav27** [comment]
We will need a Rancher CLI RC to test this.

**Comment by markusewalker** [comment]
Verified with Rancher CLI `v2.6.6-rc2`.

**ENVIRONMENT DETAILS**
- Rancher HA
- Rancher CLI version: `v2.6.6-rc2`

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher HA.
2. On a separate client machine, installed Rancher CLI version `v2.6.6-rc2`.
3. Ran command `rancher login -t <admin token> https://<Rancher Server URL>`.
4. Ran command `rancher clusters create -h` and verified the change is implemented:
```
# rancher clusters create -h
Creates a new empty cluster
Create a new custom cluster with desired configuration
Usage: 
  rancher clusters create [OPTIONS] [NEWCLUSTERNAME...]

Options:
   --description value         Description to apply to the cluster
   --disable-docker-version    Allow unsupported versions of docker on the nodes, [default=true]
   --import                    Mark the cluster for import, this is required if the cluster is going to be used to import an existing k8s cluster
   --k8s-version value         Kubernetes version to use for the cluster, pass in 'list' to see available versions
   --network-provider value    Network provider for the cluster (flannel, canal, calico) (default: "canal")
   --psp-default-policy value  Default pod security policy to apply
   --rke-config value          Location of an rke config file to import. Can be JSON or YAML format
```
