### ISSUE TITLE
Machine Driver section starts with two that go to error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3755]
Version - master UI 3/3 

Steps to Reproduce: 
1.  Go to setting

Results: The Machine drivers section starts with two but they are showing up as Error
![image](https://cloud.githubusercontent.com/assets/11514927/13507682/f46aa984-e140-11e5-805c-764458aad28e.png)

Expected: Don't have two error'ed machine drivers?

**Comment by tfiduccia** [comment]
Now they sit in Request... state

**Comment by hibooboo2** [comment]
@tfiduccia Sorry took me 4 days to reply. This is fixed with a pr to gms that was to handle new states of drivers. I will ping @ibuildthecloud to merge.

**Comment by ibuildthecloud** [comment]
This has been merge to cattle master

**Comment by tfiduccia** [comment]
Version - master updated 3/7
Verified fixed
