### ISSUE TITLE
Backup restore cleanup script is stuck on deleting cattle-global-data/cattle-global-nt namespaces

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37553]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6.4 upgraded to v2.6.5-rc5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE2`, `v1.22.8+rke2r1`
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: `v1.22.8+rke2r1`
- Cluster Type (Local/Downstream): `Local RKE2 3 worker + etcd + cp`

**Describe the bug**
During roll back of rancher server to v2.6.4 from 2.6.5-rc5, running the cleanup script gets stuck on `namespace "cattle-global-nt" deleted` and `namespace "cattle-global-data" deleted`. These namespaces are on terminating state. The script does not proceed further.

**To Reproduce**
1. Install rancher on v2.6.4 versions
2. As an admin create an rke1 node driver cluster 1 worker, 1 cp, 1 etcd nodes, and and rke2 node driver cluster with 1 worker, 1 cp, and 1 etcd nodes.
3. Create 2 standard users u1 and u2 and the users in the clusters as cluster owners.
4. As the cluster owners created a few workloads and services.
5. Install rancher backup/restore chart 2.1.1 using s3/minio as storage option.
6. Take a backup b1
7. Upgraded rancher server to v2.6.5-rc5
8. Create a few more workloads and services on the clusters.
9. From any of the local cluster's nodes, create an executable file for verify.sh and cleanup.sh scripts from the locations https://github.com/rancherlabs/support-tools/tree/master/cleanup-rancher-k8s-resources
10. Run the verify.sh script - verify.sh script completes
11. Run the cleanup.sh script

**Result**
The script is stuck on `namespace "cattle-global-nt" deleted` and does not move forward. If we stop the script and check the namespaces `k get namespaces`, we see the namespace stuck on terminating
```
cattle-global-data                           Terminating   22h
```
If we stop the script and delete the namespace manually and start the script again, we now see the script stuck atcattle-namespace-nt deletion.

**Expected Result**
cleanup.sh script to run without getting stuck at the namespaces `cattle-global-nt` and `cattle-global-data`.

**Additional context**
Workaround: Manually delete the namespaces and re-run the script

**Comment by superseb** [comment]
Fix to be tested can be found in this PR: https://github.com/rancherlabs/support-tools/pull/167

**Comment by anupama2501** [comment]
Verified on RKE1 and RKE2 local clusters:
Upgraded to v2.6.5-rc6

- Install rancher on v2.6.4 version
- As an admin create an rke1 node driver cluster 1 worker, 1 cp, 1 etcd nodes, and and rke2 node driver cluster with 1 worker, 1 cp, and 1 etcd nodes.
- Create 2 standard users u1 and u2 and the users in the clusters as cluster owners.
- As the cluster owners created a few workloads and services.
- Install rancher backup/restore chart 2.1.1 using s3/minio as storage option.
- Take a backup b1
- Upgraded rancher server to v2.6.5-rc6
- Create a few more workloads and services on the clusters.
- From any of the local cluster's nodes, create an executable file for verify.sh and cleanup.sh scripts from the locations https://github.com/rancherlabs/support-tools/tree/master/cleanup-rancher-k8s-resources
- Create a Dockerfile, cleanup.yaml, cleanup.sh, verify.sh scripts
- Run `kubectl apply -f cleanup.yaml`
- Cleanup finishes and verify.sh returns empty out once the cleanup is complete.
- Followed the steps noted here to rollback to version v2.6.4 https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/ excluding step3 from the docs.
- Verified rollback is successful and pre-upgrade checks on the downstream clusters look good.
