### ISSUE TITLE
[UI] - Let the "starred" accordion alway unfolded

### ISSUE THREAD

**Issue by sebastienroul** [rancher/rancher#37556]
Rancher UI v2.6.4

**Is your feature request related to a problem? Please describe.**
For daily working the accordion system always fold the "starred" item when you go somewhere else

**Describe the solution you'd like**
When unfolded, please let the "starred" accordion item unfolded, even if I go somewhere else.

**Describe alternatives you've considered**
Globally, accordion system with only 1 item unfolded (auto fold other) is very painful for user experience
Just let the item folded/unfolded when user fold/unfold

**Additional context**
![image](https://user-images.githubusercontent.com/2582255/166140858-8f7a8cb5-60db-4a2d-a502-a146cf8d6507.png)

**Comment by rak-phillip** [comment]
@sebastienroul thanks for raising this issue 😁

I've added this to the list that we are tracking over in rancher/dashboard#4431
