### ISSUE TITLE
Setting page does not automatically refresh when status changes for Machine Driver

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3756]
Version - master UI 3/3

Steps to Reproduce: 
1.  Go to setting
2.  Add a machine driver (wait)
3.  Remove a machine driver (wait)

Results: Notice that for both the add and remove the state stays in Creating or Removing until you refresh the page

Expected:  Should refresh on change

**Comment by vincent99** [comment]
We don't get change events for these so they need to be polled

**Comment by tfiduccia** [comment]
Version - master 3/3
Verified fixed
