### ISSUE TITLE
Creating a custom RKE2 cluster on distributed nodes causes `waiting for probes` error, resulting in cluster never provisioning

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#37573]
**Rancher Server Setup**
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/a31f5b8613d994122d9a7460700b028e61970ab5
- Installation option (Docker install/Helm Chart): Docker Install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.23.6+rke2r1`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom Linode

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

When attempting to create a custom cluster with 1 control plane, 1 etcd and 1 Linux worker, I am consistently unable to. In my latest run, I am seeing the following:

![image](https://user-images.githubusercontent.com/52591819/166520646-70e0d6ba-a721-40c1-b0ad-0eabcd683e99.png)

![image](https://user-images.githubusercontent.com/52591819/166520738-9c533ad5-33dd-4742-a3e7-acdcf44642f7.png)

Interestingly, I did see that if I have one node that has all roles, then that successfully provisions my cluster....additionally, this was not an issue last week. So this seems to be a recent regression where creating a custom cluster and separating nodes to have independent roles causes failure.

Further testing suggests that this is Linode specific as AWS nodes can successfully provision a downstream RKE2 custom cluster.

**To Reproduce**
 
1. Setup Rancher `v2.6-head` and navigate to Rancher UI.
2. Create a custom cluster with three separate nodes; 1 control plane, 1 etcd, 1 Linux worker.

**Result**
The cluster is not provisioning, it gets stuck waiting on probes. I have seen it get stuck on kubelet probe and calico probe, but most likely not limited to just those two.

**Expected Result**

Creating a custom cluster with distributed nodes should provision successfully.

**Comment by thedadams** [comment]
When creating instances in Linode, the hostname of the instance is always `localhost`. This causes problems with RKE2 because it will use the hostname as the node name by default. Since a cluster can't have two nodes with the same name, then the `kubelet` will complain.

One can use the command `hostnamectl set-hostname new-hostname` to change the hostname of each instance to something unique before running the registration commands for the custom cluster.

**Comment by markusewalker** [comment]
Verified on `v2.6.5-rc6` that this is working correctly following updating each Linode hostname.

**ENVIRONMENT DETAILS**
- Rancher version: `v2.6.5-rc6`
- Ubuntu 18.04: Rancher HA
- Linode Custom Cluster
     - 1 etcd node
     - 1 control plane node
     - 1 worker Linux node
- Browser: Chrome

**TEST RESULT**
PASS

**TEST PLAN**
1. Setup Rancher and navigate to Rancher UI in a browser.
2. Create a standard user and login to Rancher as that user.
3. Create an RKE2 custom cluster utilizing Linode nodes.
4. In a terminal, rename each node using command `hostnamectl set-hostname <new-hostname>`. Did this for each of my nodes.
5. Back in Rancher UI, apply the registration curl command for each role to each independent role. Verified that the cluster and machine pool comes up as `Active`:
![image](https://user-images.githubusercontent.com/52591819/166842251-9adcd7bc-1cf4-4d74-9505-3031157ba04a.png)
![image](https://user-images.githubusercontent.com/52591819/166842263-f11ac7d1-407d-4a4a-bad1-91886bbd6acc.png)
