### ISSUE TITLE
[HA Airgap] - "rke2-ingress-nginx-admission-create" fails to pull image from registry

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#37571]
**Rancher Server Setup**
- Rancher version: v2.6.5-rc6, HA Airgap
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: v1.22.9+rke2r1
- Cluster Type (Local/Downstream): Downstream 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

- "ImagePullBackOff" error in "rke2-ingress-nginx-admission-create-*" pod with below error:
```
Failed to pull image "rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.1.1": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.1.1": failed to resolve reference "docker.io/rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.1.1": failed to do request: Head "https://registry-1.docker.io/v2/rancher/mirrored-ingress-nginx-kube-webhook-certgen/manifests/v1.1.1": dial tcp <ip>: i/o timeout
```
- Also below image is present in `rancher-images.txt`:
```
cat rancher-images.txt | grep -i ingress
rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.0
rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.1.1
...
```

**To Reproduce**
 
- Deploy rancher v2.6.5-rc6 in HA Airgap setup.
- Provision a single node all role `v1.22.9+rke2r1` or `v1.23.6+rke2r1` RKE2 custom cluster.
- Check "rke2-ingress-nginx-admission-create" pod for error:
![error](https://user-images.githubusercontent.com/36376154/166471908-675f3b72-964f-4f88-aae1-24802ecf1655.png)

**Result**
- "ImagePullBackOff" error in "rke2-ingress-nginx-admission-create-*" pod.

**Expected Result**

- "rke2-ingress-nginx-admission-create" job should complete successfully.

Additional Context:
https://github.com/rancher/rancher/issues/37301

**Comment by rancher-max** [comment]
This will get resolved in rke2: https://github.com/rancher/rke2/issues/2835

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6.5-rc8, HA Airgap setup. Provisioned 2 downstream custom clusters using k8s versions -> `v1.22.9-rc1+rke2r2` and `v1.23.6-rc1+rke2r2`. All the pods were up and running. Hence the issue is resolved, closing the ticket.
