### ISSUE TITLE
Inherit tolerations\nodeselector from chart

### ISSUE THREAD

**Issue by time4116** [rancher/rancher#37578]
**Is your feature request related to a problem? Please describe.**
I have included tolerations and nodeselector info in the rancher deployment. However, deployments\pods generated by rancher (post helm install) don't have these tolerations or nodeselectors.

**Describe the solution you'd like**
I would like all deployments\pods generated by rancher to also include the same tolerations and nodeselector initially specified in the chart

**Describe alternatives you've considered**
Locate any deployments generated by rancher that do not have tolerations and nodeselector and add them. I have done this for (rancher-webhook) but I'm not sure where this would be done for the (dashboard-shell) pods etc..

**Comment by weltonrodrigo** [comment]
I believe a better approach would be to expose tolerations and nodeSelectors in the chart. Would that be possible?
