### ISSUE TITLE
[rke2] windows rke2 images should be included in manifests and rancher-images

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#37577]
**Rancher Server Setup**
- Rancher version: v2.6.5-rc6
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, 1.3.10
- Proxy/Cert Details: letsencrypt valid certs

**Information about the Cluster**
- Kubernetes version: v1.22.9+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom rke2, windows

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): standard user, cluster owner

   
**Describe the bug**
when adding a windows node to the cluster, it gets stuck `waiting for probes: kubelet`. Upon further investigation, this was because the rke2 manifest doesn't contain windows images anymore. after manually pulling the image into my registry, the node was able to finish registering

**To Reproduce**
 
* in an airgap setup, deploy a custom cluster (default k8s, 1.22.9)
* once there are linux workers in the custom cluster, add a windows 2022 node to the cluster
* wait for node to register with the custom cluster

**Result**
fails with message `waiting for probes: kubelet`. After pulling the following image to my registry, the node is able to register. 
```
https://hub.docker.com/layers/rke2-runtime/rancher/rke2-runtime/v1.22.9-rke2r1-windows-amd64/images/sha256-511e63eac71807e1d0f79bccac3e732801e0f1f8267b97e60aa4e29683a95dbe?context=explore
```

**Expected Result**
these images should be listed in `rancher-windows-images.txt` either as their own requirement, or added to the manifest. 

**Additional context**
I suspect this is also an issue for the other k8s versions for rke2. please update these as well

**Comment by sirredbeard** [comment]
Will be fixed by PR https://github.com/rancher/rancher/pull/37586
