### ISSUE TITLE
Node name RKE2

### ISSUE THREAD

**Issue by jandunk** [rancher/rancher#37582]
**Is your feature request related to a problem? Please describe.**
When creating a node with an rke2 template the hostname is getting longer than I would like. We have Active Directory joined machines and I think there's a maximum length on the computername of 15 chars. 

**Describe the solution you'd like**
I would like to be able to use the old rke naming convention where I could define a prefix and then Rancher would simply add a single digit.

**Describe alternatives you've considered**
I can control the length a bit by minimizing the  nodepool name and cluster name but then still the name is too long. I couldn't find anything on hostname generation in the docs.

**Additional context**
Maybe the option is already there but I couldn't find it!

**Comment by JeanGau-ops** [comment]
Did you find a solution to this?
