### ISSUE TITLE
[RKE2] etcd cert components are available on both etcd and control plane nodes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#37590]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `a31f5b861`
- Installation option (Docker install/Helm Chart): Helm install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: 1.22-RKE2
- Cluster Type (Local/Downstream): AWS node driver RKE2 - 3 etcd, 2 cp and 3 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) std user - cluster owner
   
**Describe the bug**
[RKE2] etcd cert components are available on both etcd and control plane nodes

**To Reproduce**
- Deploy an rke2 node driver down stream cluster
- Login to the etcd and control plane nodes `/var/lib/rancher/rke2/server` . etcd folder exists and the certs exist on these nodes.
- Rotate certs on the cluster, select etcd component from the dropdown.
- etcd certs on both the nodes get rotated.

**Expected Result**
- etcd component should be available only on the etcd node and not on the control plane nodes
- when cert rotate is triggered on `etcd` components, the etcd components on both the nodes rotate. only the etcd ones should rotate if ^^^ is not fixed.

**Comment by jiaqiluo** [comment]
This is by design that rke2 only has server and agent roles (v.s. separate etcd and control plane and worker), in rancher we add extra labels to mark nodes as "etcd" or "control plane",  so it is expected to see the etcd certs in both "etcd" and "control plane" nodes. 

Moving this back to QA since it is the expected behavior.

**Comment by sowmyav27** [comment]
Closing as per - https://github.com/rancher/rancher/issues/37590#issuecomment-1126297148
