### ISSUE TITLE
rke2 cluster upgrade fails to respond until Edit as Yaml Button is clicked

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rancher#37598]
**Rancher Server Setup**
- Rancher version: v2.6.5-rc6
- Installation option (Docker install/Helm Chart):
```
sudo docker run -d --privileged --restart=unless-stopped -p 80:80 -p 443:443 -e CATTLE_BOOTSTRAP_PASSWORD=<REDACTED> rancher/rancher:v2.6.5-rc6"
```

**Information about the Cluster**
Cluster Configuration:
3 etcd nodes, 2 cp and 2 worker nodes
- Kubernetes version: Upgrade from v1.21.12+rke2r1 to v1.22.9-rc1+rke2r2 or v1.22.9-rc1+rke2r2 to v1.23.6-rc1+rke2r2
- Infrastructure Provider: Cluster provisioned using Amazon EC2 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  
**Describe the bug**
While upgrading the cluster with above mentioned version, upgrade fails to respond and displays below messages

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/56045581/166872630-3c7e70cd-2199-42e3-b940-0f1e4caa5393.png">

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/56045581/166872724-40bc4d11-18a0-449b-b0aa-beb0d9f052e7.png">

**To Reproduce**

- Provision a 3 etcd nodes, 2 cp and 2 worker nodes rke2 cluster with **v1.21.12+rke2r1**
- Point the KDM to Developers branch with latest version updates. 
- Upgrade the cluster by clicking on Edit Config and selecting the version to upgrade to **v1.22.9-rc1+rke2r2**
- Upgrade process does not start. 
- Click on Edit as yaml, do nothing and click on Save, upgrade process is now triggered.

**Expected Result**
When new version is selected and on clicking Save upgrade process should start.
**Actual Result**
Unless Edit as Yaml button is clicked and saved upgrade process does not start

** Additional info**
When Save button is clicked
<img width="782" alt="image" src="https://user-images.githubusercontent.com/56045581/166873756-4ee61f17-d176-48ac-a155-0a9767a8b5d7.png">

**Comment by anupama2501** [comment]
Verified working on 2.6-head 054b5d1- 

- Created an rke2 node driver 3 worker + 1 etcd + 1 cp on `v1.21.12+rke2r1`
- Upgraded the cluster to `v1.22.9-rc1+rke2r2`.
- Upgrade went through fine without any errors.

**Comment by ShylajaDevadiga** [comment]
Confirming it works as expected in 2.6-head. Upgraded the cluster from v1.22.9-rc1+rke2r2 to v1.23.6-rc1+rke2r2
Closing issue.
