### ISSUE TITLE
If I click on Generate Config, all the other Kubernetes submenu pages are broken

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3759]
Version - master UI 3/3

Steps to Reproduce: 
1.  Setup Kubernetes environment
2.  Go to KUBECTL submenu
3.  Click on Generate Config
4.  Now try clicking on any of the other kubernetes submenus (Services, RCS or PODS)

Results: Config stay up and I can't get to any of the other pages

Expected: Should be able to see other pages

**Comment by vincent99** [comment]
Left-over instance of the old copy-to-clipboard component from merging things together.

**Comment by tfiduccia** [comment]
Version - master 3/3
Verified fixed
