### ISSUE TITLE
[CLI] `rancher login` should not allow the `SERVERURL` to append contexts at the end of the URL

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#37604]
**Is your feature request related to a problem? Please describe.**
When using the Rancher CLI to login, you need to ensure that you use the `-t <bearer-token>` flag and supply your server name. Putting in a bogus URL gives you the following message:

```
$ rancher login -t token-..... FQDN
FATA[0000] Failed to parse SERVERURL (FQDN), make sure it is a valid HTTPS URL (e.g. https://rancher.yourdomain.com or https://1.1.1.1). Error: parse "FQDN": invalid URI for request 
```
The above message is clear and is fine. The issue is that when you enter in a valid HTTPS URL and put any context afterwards, the `rancher login` will ignore that. It doesn't even have to exist:

```
$ rancher login -t token-g2kkk:4285jrks64xm58tv2ptbwpjbt67hrp8q6zb4n7tgchvzf5n6rqhl9l https://<FQDN>/bogus
NUMBER    CLUSTER NAME   PROJECT ID        PROJECT NAME   PROJECT DESCRIPTION
1         test-76479     c-pvfwc:p-2mh84   System         System project created for the cluster
2         test-76479     c-pvfwc:p-bh7fn   Default        Default project created for the cluster
3         test-45231     c-pxnc9:p-ckjjp   Default        Default project created for the cluster
4         test-45231     c-pxnc9:p-s4ldg   System         System project created for the cluster
5         local          local:p-9jqt9     Default        Default project created for the cluster
6         local          local:p-c4mvc     System         System project created for the cluster
Select a Project:1
INFO[0006] Saving config to /.../.rancher/cli2.json 
$ rancher server ls
CURRENT   NAME             URL
*         rancherDefault   https://<FQDN>
```
While this is not necessarily a bug, the `rancher login` should limit the scope to simply look for `https://FQDN` and to not allow users to put a context at the end.

**Comment by jakefhyde** [comment]
@markusewalker We investigated this issue and discovered a PR which intentionally introduced this behavior, so we are choosing not to change the behavior at this time so as not to break any users which may be relying on this behavior. https://github.com/rancher/cli/pull/140

**Comment by markusewalker** [comment]
@jakefhyde makes sense, thanks for taking a look into this. With that considered, I'll close this issue out as functionality working as designed.
