### ISSUE TITLE
[v2.6] KDM Update for K8s 2022 May patch release

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#37603]
# KDM Updates
TO BE RELEASED: **OOB KDM with RKE v1.3.12** 

| New Kubernetes Version | Min Rancher Version | Min RKE Version |
| ---------------------- | ------------------- | --------------- |
| 1.23.7-rancher1-1      | 2.6.4-rc0                 | 1.3.3-rc0             |
| 1.22.10-rancher1-1      | 2.6.3-rc0                 | 1.3.3-rc0             |
| 1.21.13-rancher1-1      | 2.6.0-rc0                 | 1.3.0-rc0             |

### Rancher System Images & Add-ons
**_Note: Please update system images and add-ons in the template as needed._**

TBD

# Developer Changelog
- Add templates for new K8s versions. If a template that hasn't been released yet already exists, update it in place.
- Update the default K8s version, and add or update the version information (`MinRancherVersion` and `MinRKEVersion`) in [k8s_version_info.go](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/k8s_version_info.go) for new K8s versions if needed (Use table from above).
- Confirm versions for system images, add-on templates are correct using versioning reference table from below (expand details to view the table). Update the table if new versions are introduced.
- Confirm add-on template version constraints in [template.go](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) are correct using versioning reference table from below (expand details to view the table). Update the table if needed.

# Versioning Reference
<details>
<summary>
Expand for system images & add-on templates versioning table
</summary>
</br>

**_Note: Truncated repository names with a `*` indicates there are multiple images with that prefix. All repository names that match a truncated prefix should be checked for the same version stated in the table._**
**_For example: `rancher/weave-*` matches `weaveworks/weave-kube` and `weaveworks/weave-npc`, and they should both have the same version._**

## v1.23.7-rancher1-1
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.5.3-rancher1      |
| rancher/hyperkube                                        | v1.23.7-rancher1      |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/mirrored-k8s-dns-*                               | 1.17.4                |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/mirrored-coreos-flannel                          | v0.15.1               |
| rancher/flannel-cni                                      | v0.3.0-rancher6       |
| rancher/mirrored-calico-*                                | v3.19.1               |
| weaveworks/weave-*                                       | 2.8.1                 |
| noiro/* (All ACI images)                                 | 5.1.1.0.1ae238a       |
| rancher/mirrored-pause                                   | 3.4.1                 |
| rancher/nginx-ingress-controller                         | nginx-1.1.0-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.5.1                |
| rancher/mirrored-coredns-coredns                         | 1.8.4                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.18.0                |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov319                         |
| Canal         | canalv3211                          |
| Flannel       | flannelv0140                       |
| CoreDNS       | coreDnsv183                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv050                  |
| Weave         | weavev120                          |
| Aci           | aciv500                            |
| NginxIngress  | nginxIngressv110Rancher3                  |
| Nodelocal     | nodelocalv121                      |

## v1.22.9-rancher1-1
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.4.16-rancher1      |
| rancher/hyperkube                                        | v1.22.9-rancher1      |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/mirrored-k8s-dns-*                               | 1.17.4                |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/mirrored-coreos-flannel                          | v0.15.1               |
| rancher/flannel-cni                                      | v0.3.0-rancher6       |
| rancher/mirrored-calico-*                                | v3.19.1               |
| weaveworks/weave-*                                       | 2.8.1                 |
| noiro/* (All ACI images)                                 | 5.1.1.0.1ae238a       |
| rancher/mirrored-pause                                   | 3.4.1                 |
| rancher/nginx-ingress-controller                         | nginx-1.1.0-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.5.1                |
| rancher/mirrored-coredns-coredns                         | 1.8.4                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.18.0                |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov319                         |
| Canal         | canalv3211                          |
| Flannel       | flannelv0140                       |
| CoreDNS       | coreDnsv183                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv050                  |
| Weave         | weavev120                          |
| Aci           | aciv500                            |
| NginxIngress  | nginxIngressv110Rancher3                  |
| Nodelocal     | nodelocalv121                      |

## v1.21.12-rancher1-1
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.4.16-rancher1      |
| rancher/hyperkube                                        | v1.21.12-rancher1      |
| rancher/rke-tools                                        | v0.1.78               |
| rancher/mirrored-k8s-dns-*                               | 1.17.4                |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/mirrored-coreos-flannel                          | v0.15.1               |
| rancher/flannel-cni                                      | v0.3.0-rancher6       |
| rancher/mirrored-calico-*                                | v3.19.1               |
| weaveworks/weave-*                                       | 2.8.1                 |
| noiro/* (All ACI images)                                 | 5.1.1.0.1ae238a       |
| rancher/mirrored-pause                                   | 3.4.1                 |
| rancher/nginx-ingress-controller                         | nginx-1.1.0-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.5.0                |
| rancher/mirrored-coredns-coredns                         | 1.8.4                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.3                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.18.0                |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov319                         |
| Canal         | canalv319                          |
| Flannel       | flannelv115                       |
| CoreDNS       | coreDnsv183                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv050                  |
| Weave         | weavev120                          |
| Aci           | aciv500                            |
| NginxIngress  | nginxIngressv110Rancher3                  |
| Nodelocal     | nodelocalv121                      |

</details>

**Comment by doflamingo721** [comment]
The KDM changes have been merged in the branch [2022-05-k8s-patches-v2.6](https://github.com/rancher/kontainer-driver-metadata/tree/2022-05-k8s-patches-v2.6). Please use the same branch for test. 
cc: @sowmyav27 @rishabhmsra @vivek-infracloud

**Comment by rishabhmsra** [comment]
**Fresh install checks - PASS**

- KDM points to `2022-05-k8s-patches-v2.6` branch.
- Cluster creation succeeds for v1.23.7-rancher1-1, v1.22.10-rancher1-1, v1.21.13-rancher1-1 k8s versions with all network providers
- Network checks succeeded for all new clusters
- Ran validation tests for Canal cluster.
- Network checks and Canal checks pass.

**RKE checks using `v1.3.12-rc1` passed for v1.23.7-rancher1-1, v1.22.10-rancher1-1, v1.21.13-rancher1-1 k8s version.**

**Comment by jiaqiluo** [comment]
@doflamingo721  @vivek-infracloud  
Could you also update the image used for `KubeDNS` in v1.23.7-rancher1-1? 
The image should be `rancher/mirrored-k8s-dns-kube-dns` 
https://github.com/rancher/kontainer-driver-metadata/blob/aec8036b15c1612896c6503d7eef083bc44db78f/rke/k8s_rke_system_images.go#L7549

**Comment by snasovich** [comment]
The change above has been addressed and this is ready to be tested on [rancher:2022-05-k8s-patches-v2.6](https://github.com/rancher/kontainer-driver-metadata/tree/2022-05-k8s-patches-v2.6) branch.

**Comment by vivek-infracloud** [comment]
Based on the test results commented by [Rishabh](https://github.com/rancher/rancher/issues/37603#issuecomment-1147473124) and [me](https://github.com/rancher/rancher/issues/37603#issuecomment-1147476818) the KDM testing is finished. 

Kube dns [issue](https://github.com/rancher/rancher/issues/37890) and nginx-ingress-controller [issue](https://github.com/rancher/rancher/issues/37925) are being tracked in different issues. Hence, closing the KDM may patch release issue since all the tests passed.
