### ISSUE TITLE
Ability to Rollback for Helm releases via the Rancher GUI

### ISSUE THREAD

**Issue by disparo13** [rancher/rancher#37600]
**Is your feature request related to a problem? Please describe.**
Users can install and upgrade applications via the Rancher GUI, but `helm rollback` can only be performed via the Kubectl shell. 

**Describe the solution you'd like**
It would be nice to get the releases list like `helm history <release name>` does and have the ability to roll back with just a mouse click.

**Describe alternatives you've considered**
The only alternative - is to open the Kubectl shell and run helm commands there.

**Comment by sergio-ferreira-jscrambler** [comment]
This would be a great addition

**Comment by anaezes** [comment]
Yes, I agree, I also have the need for a feature like this.
