### ISSUE TITLE
Default secondary launch config mode to "container" (use network of primary launch config)

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3760]
Steps to Reproduce: 

Create service with 1 or more secondary launch config w/o specifying networkMode

Results: 

Each launch config on created service has networkMode defaulted to "managed"

Expected:

Should default to managed only for primary launch config, and for secondary - default to networkMode=container (with networkLaunchConfig=primaryservice.name)

UI changes would be needed as well.

**Comment by alena1108** [comment]
@vincent99 for sidekicks, we would have to display networkFrom primary config as a default mode, instead of managed.

**Comment by sangeethah** [comment]
This change is getting reverted - https://github.com/rancher/cattle/pull/1440 .
Closing this issue.
