### ISSUE TITLE
Planner sends unnecessary plan updates to controlplane nodes when utility operations are performed.

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#37613]
When taking an etcd snapshot, the planner will trigger a reconciliation of all controlplane nodes as the cluster spec will technically change.

We can fix this by simply not storing utility fields when we save a copy of the cluster spec, as these are never used in etcd restore anyway.

**Comment by Oats87** [comment]
The easiest way to test this is to provision a cluster with a dedicated controlplane node, perform an etcd snapshot create, and observe that the plan on the dedicated controlplane node does not change during this procedure.

**Comment by thedadams** [comment]
On Rancher v2.6-head 42ef7aea7415212d4b96c73fdff33766011b6f93:
1. Provisioning a cluster with 3 etcd, 2cp, and 2 worker nodes.
2. Took an ectd snapshot.
3. Observed that the control plane machines changed status to Reconciling indicating that the plan did change.
4. SSH'd to the nodes to see that multiple plans were applied by `rancher-system-agent`

On Rancher v2.6-head cac23eae92ec00c93fcaf3e44f53cafa44453bec:
1. Provisioning a cluster with 3 etcd, 2cp, and 2 worker nodes.
2. Took an ectd snapshot.
3. Observed that the control plane machines never changed status indicating that the plan did NOT change
4. SSH'd to the nodes to see that only one plan was applied by `rancher-system-agent`
