### ISSUE TITLE
Notify if Rancher backup operation have failed so an alert can be raised

### ISSUE THREAD

**Issue by elvinasp** [rancher/rancher#37624]
**Is your feature request related to a problem? Please describe.**
Rancher cluster has the backup configuration to backup cluster state to S3 backend. This backup have failed due to expired certificate on Minio service. 

The issue is that there is no easy way to detect such failure. Rancher itself does not provide notification that backup have failed. And backup was failing for a quite a while.

**Describe the solution you'd like**
Rancher should provide a query-able endpoint so state of backup object can be queried via Prometheus and alert raised in case of failure. 

Or at least there should be some events generated that can be programatically obtained and processed to raise an alert. 

**Describe alternatives you've considered**
We were thinking about using [Kube state metrics](https://github.com/kubernetes/kube-state-metrics/tree/master/docs) to get status of the job, but as this is not a generic Kubernetes CronJob, this service does not get any metrics for it. Therefore Prometheus cannot monitor it in a similar fashion, like defined in this  [Medium article](https://medium.com/@tristan_96324/prometheus-k8s-cronjob-alerts-94bee7b90511)

**Additional context**

**Comment by Turb0Fly** [comment]
That's still needed.
