### ISSUE TITLE
RKE1 etcd snapshot trying too frequently

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#37639]
**Describe the bug**

The rke-tools image will retry the etcd snapshot four times, and rancher will retry the run of the rke-tools container 5 times. In situations where the etcd snapshot will never succeed (i.e. when etcd is not running), this causes the logs to be inundated with error messages.

**To Reproduce**
 

- Provision a Rancher instance with a three all role node custom cluster attached
- Stop etcd on first downstream node `docker stop etcd`
- Trigger a snapshot for the cluster within Rancher
- Observe looping attempts to perform etcd-snapshot on the node with etcd container stopped

**Result**

Rancher will try 20 times on the node with etcd stopped, before moving on to the next node, printing logs every second.

**Expected Result**

RKE should see that etcd isn't running on the node, and attempt to retry with backoff so as not to saturate the logs. When etcd is running but there is another problem, the retry with backoff should still be performed.

**Additional context**

SURE-3513

**Comment by jakefhyde** [comment]
### Root cause

This issue had multiple root causes:
- The rke1 docker interface prints container logs every second. During cluster up, these logs are useful, but certain operations (such as taking a snapshot) do not have many unique logs and last a while, which clutters the rancher logs.
- Taking a snapshot had retry for things that were not possible to recover from, such as the etcd container not running.
- Snapshot with invalid s3 credentials would try to take the snapshot, and then upload to s3. If this upload failed, the local snapshot would be deleted and recreated, and then rancher would reattempt the upload multiple times.
- If any of the nodes failed to take a snapshot, the remaining nodes would not take a snapshot. Since only one nodes is required to have the snapshot in order to restore, this wasn't too impactful, but realistically there was no barrier for the nodes having said snapshot
- On s3 buckets without versioning enabled, every node would upload the snapshot. Although there is currently no mechanism for choosing which version to restore, and the last one will (and always would) take precedence, now if the s3 bucket does not have versioning enabled, only one snapshot is uploaded.
 
### What was fixed, or what changes have occurred

- Made a configurable option to only print unique container logs.
- Stop trying to take a snapshot on a node if it cannot succeed (etcd is not running: this almost always indicates outside intervention).
- Attempt the s3 upload 3 times and do not delete the local snapshot.
- If a bucket doesn't have s3 bucket versioning enabled, first check if the snapshot exists in the bucket, and overwrite if it does not. If s3 bucket versioning is enabled, then upload regardless. This is a small change, but should improve performance for large etcd clusters without bucket versioning. 
 
### Areas or cases that should be tested

- Cluster with invalid s3 credentials (create the cluster with valid credentials, then delete the s3 bucket)
- s3 bucket without versioning should only upload once
- s3 bucket with versioning should upload once per node
- 3 node etcd cluster where one node has etcd stopped should not have a snapshot on the node with the stopped etcd container. The other two nodes should have it. Attempting to restore should populate the snapshot onto the node that did not have the snapshot. This snapshot should also show as `Active` in the UI.
 
### What areas could experience regressions?

N/A
 
### Are the repro steps accurate/minimal?

:heavy_check_mark:

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head a678d0e
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE1

----------

### Testing: ###

Tested this issue with the following scenarios:
P0
1. provision an rke1 custom cluster
2. Stop etcd on first downstream node docker stop etcd
3. Trigger a snapshot for the cluster within Rancher
4. Observe looping attempts to perform etcd-snapshot on the node with etcd container stopped

Other scenarios:
1. Cluster with invalid s3 credentials
    - Create the cluster with valid credentials
    - Then delete the s3 bucket)
2. s3 bucket without versioning should only upload once
3. s3 bucket with versioning should upload once per node
4. 3 node etcd cluster where one node has etcd stopped should not have a snapshot on the node with the stopped etcd container. The other two nodes should have it. Attempting to restore should populate the snapshot onto the node that did not have the snapshot. This snapshot should also show as Active in the UI.

**Result** - Pass
All scenarios are Pass
