### ISSUE TITLE
[RKE2] Snapshot restore does not work on a cloud provider enabled cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#37641]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id `628b1b9`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.22.9+rke2r2`
- Cluster Type (Local/Downstream): AWS RKE2 node driver - 3 etcd, 2 cp, 3 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) std user

   
**To Reproduce**

- Deploy an AWS cloud provider enabled RKE2 downstream cluster
- As a std user take a snapshot
- Restore from one of the snapshots
- The cluster is stuck in `Updating` state with error: `Error while designating init node during control plane/etcd stop: rkecluster fleet-default/sowmya-test: init node sowmya-test-pool1-7f7ce995-gjgg8 was not found during designation`
- `sowmya-test-pool1-7f7ce995-gjgg8` is NOT available

**Comment by Oats87** [comment]
Areas of potential regression are in etcd snapshot restore in general.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f40a8a7`**

- Deploy an AWS cloud provider enabled RKE2 downstream cluster
- As a std user take a snapshot
- Restore from one of the snapshots
- Cluster is seen stuck in `Updating` state with error. `Error while designating init node during control plane/etcd stop: rkecluster fleet-default/sowmyatest: init node sowmyatest-pool1-2f621161-77tps was not found during designation`
- `sowmyatest-pool1-2f621161-77tps` is not available on the cluster.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `5f5fb23`**

- Deploy an AWS cloud provider enabled RKE2 downstream cluster
- As a std user take a snapshot
- Restore from one of the snapshots
- Cluster restores and comes back Active
