### ISSUE TITLE
RKE2 windows nodes sometimes require a reboot post-upgrade to maintain functionality

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#37645]
We have had reports from end-users that RKE2 Windows nodes will sometimes require a reboot after a successful upgrade. It is unclear if this is a bug or simply was an issue with how the end users were upgrading their clusters (standalone vs through Rancher). 

I have placed this on our backlog as we need to investigate this further

**Comment by snasovich** [comment]
Closed due to lack of information on recent reproduction instances that can be further investigated. New issues will be open if/when we/someone runs into it.
