### ISSUE TITLE
[Project Monitoring V2] Grafana shows error in logs due to faulty dashboards

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#37656]
**Rancher Server Setup**
- Rancher version: v2.6.4 (dev setup, but should be identical to 2.6.5 setup)
- Installation option (Docker install/Helm Chart): docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: 1.22.7
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): DO RKE1

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

Admin
   
**Describe the bug**

After deploying Project Monitoring Stack, Grafana shows error logs on loading dashboards

```
t=2022-05-10T04:37:29+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=sidecarProvider file=/tmp/dashboards/cluster-total.json error="invalid character ']' looking for beginning of value"
--
Mon, May 9 2022 9:37:29 pm | t=2022-05-10T04:37:29+0000 lvl=eror msg="failed to load dashboard from " logger=provisioning.dashboard type=file name=sidecarProvider file=/tmp/dashboards/k8s-resources-cluster.json error="invalid character ']' looking for beginning of value"
```

**To Reproduce**
 

Reproducible using `v0.0.1-rc2 ` image tag of prometheus-federator

1. Deploy Prometheus Federator onto the cluster (`v0.0.1-rc2 `)
2. Create a ProjectMonitor (ProjectHelmChart) in any project registration namespace (`cattle-project-p-XXXXX`) with `spec.helmApiVersion: monitoring.cattle.io/v1alpha1`
3. Check the logs of the `grafana` container in the Grafana deployment in the Project Release Namespace (`cattle-project-p-XXXXX-monitoring`)

**Result**

See the error messages shown above due to bad JSON in dashboards; dashboards won't show up in Grafana either

**Expected Result**

No error logs, dashboards should show up on Grafana

**Screenshots**

**Additional context**

**Comment by aiyengar2** [comment]
Will be testable in `v0.0.1-rc3`

**Comment by aiyengar2** [comment]
On fixing this issue, two new dashboards should pop up:
- `General / Kubernetes / Networking / Project`
- `Kubernetes / Compute Resources / Project`

**Comment by aiyengar2** [comment]
Release has been cut.

**Comment by ronhorton** [comment]
**Pass** Verified in `2.6-head Commit ID 4bfdf0c`

1. created project monitor
2. Deployments > cattle-project-p-xxxx-monitoring > project-p-xxxx-monitoring-grafana
3. clicked on deployment
4. checked logs for errors - no errors
5. loaded grafana dashboards - no errors, dashboards loaded
