### ISSUE TITLE
rancher backup/restore cleanup script fails when deployed as a kubectl job

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37675]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6.5-rc8
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.21.12, 1.3.11
- Proxy/Cert Details: Selfsigned
- backup chart: v2.1.1

**Information about the Cluster**
- Kubernetes version: v1.21.12
- Cluster Type (Local/Downstream): `Downstream node driver 1 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
while performing a rancher roll back, we would need to run the cleanup script as mentioned here https://github.com/rancherlabs/support-tools/pull/167. The cleanup script when deployed as a kubectl job, fails as rancher/rancher-cleanup is not published.

**To Reproduce**

1. Install rancher on v2.6.4 version
2. As an admin create an rke1 node driver cluster 1 worker, 1 cp, 1 etcd nodes, and and rke2 node driver cluster with 1 worker, 1 cp, and 1 etcd nodes.
3. Create 2 standard users u1 and u2 and the users in the clusters as cluster owners.
5. Install rancher backup/restore chart 2.1.1 using s3/minio as storage option.
6. Take a backup b1
7. Upgraded rancher server to v2.6.5-rc6
9. From any of the local cluster's nodes, create an executable file for verify.sh and cleanup.sh scripts from the locations https://github.com/rancherlabs/support-tools/tree/master/cleanup-rancher-k8s-resources
10. Create a Dockerfile, cleanup.yaml, cleanup.sh, verify.sh scripts
11. Run kubectl apply -f cleanup.yaml
12. Check the logs `kubectl  -n kube-system logs -l job-name=cleanup-job  -f`

**Result**
We get the following error 
`Error from server (BadRequest): container "cleanup" in pod "cleanup-job-ptdbf" is waiting to start: trying and failing to pull image`

**Expected Result**
Job runs without any error

**Additional context**
rancher/rancher-cleanup is not published in the docker hub https://hub.docker.com/r/rancher/rancher-cleanup/tags

**Comment by superseb** [comment]
This was resolved by merging the PR and pushing the image 2 hours later than this created issue: https://drone-publish.rancher.io/rancherlabs/support-tools/128/1/6

**Comment by anupama2501** [comment]
Verified working on v2.6.5. kubectl job is created and works as expected.
