### ISSUE TITLE
Some resources are left behind when cleanup script is run while rolling back rancher using backup restore charts

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37676]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.6.2` upgraded to `v2.6.5-rc8`
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.20.11, 1.2.13
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: `v1.21.12`
- Cluster Type (Local/Downstream): `Downstream node driver 1 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
while performing a rancher roll back, we would need to run the cleanup script as mentioned here https://github.com/rancherlabs/support-tools/pull/167. Once the cleanup script is run, when we try to run the verify.sh script we notice some of the resources were not cleaned up and will be only cleaned up if we re run the script.

**To Reproduce**

1. Install rancher on v2.6.4 version
2. As an admin create an rke1 node driver cluster 1 worker, 1 cp, 1 etcd nodes, and and rke2 node driver cluster with 1 worker, 1 cp, and 1 etcd nodes.
3. Create 2 standard users u1 and u2 and the users in the both clusters as cluster owners.
4. Install rancher backup/restore chart 2.1.1 using s3/minio as storage option.
5. Take a backup b1
6. Upgraded rancher server to v2.6.5-rc6
7. From any of the local cluster's nodes, create an executable file for verify.sh and cleanup.sh scripts from the locations https://github.com/rancher/rancher-cleanup
8. Run `verify.sh` to list all the resources
9. Run `cleanup.sh` to clean the resources
10. Once cleanup.sh script is completed, run `verify.sh` to see if all resources are deleted

**Result**
Following resources weren't cleaned from the cleanup script:
```
namespace/cattle-fleet-clusters-system
namespace/cattle-fleet-local-system
namespace/cattle-fleet-system
namespace/cluster-fleet-default-c-r99rl-4303e6f3b34a
namespace/cluster-fleet-local-local-1a3d67d0a899
namespace/fleet-default
namespace/fleet-local
```

**Expected Result**
Expected all the resources to be cleaned.

**Additional context**
Workaround: Run the cleanup script again, which then deletes all the resources.

**Comment by superseb** [comment]
@anupama2501 Can you create the setup, run the script, and after `verify.sh` shows resources, share the setup? Please run the script as a Kubernetes Job as described on https://github.com/rancherlabs/support-tools/blob/master/rancher-cleanup/README.md

**Comment by anupama2501** [comment]
@superseb 
I created a setup and ran the kubectl job to cleanup the resources and did not see the resources left behind. But I see this consistently happen when I run the scripts if I do not use a kubectl job. 


Could you let me know why a few resources are left behind uncleaned when we run the cleanup script manually on the control plane nodes?

**Comment by superseb** [comment]
We are not going to support running the script separately anymore as, if not run on a controlplane, its extremely slow, and not everyone has access to the controlplane (the script was initially designed for cleaning up AKS). I would be interested in all the logs (both cleanup and verify) from when it leaves stuff behind, if its always the same resources that are left behind or different.

**Comment by anupama2501** [comment]
@superseb dm'ed the logs. As we won't be supporting running the script separately anymore ,can we adjust the readme file here https://github.com/rancherlabs/support-tools/blob/master/rancher-cleanup/README.md. 

Can we have a section `Run the script on a Linux node` with steps on running the script separately removed ?

**Comment by AndrewHoffmanQA** [comment]
assigning Nick to this ticket, we are working them together.

**Comment by nickwsuse** [comment]
`Verified on v2.6.6-rc1`

1. Provisioned a HA cluster on Rancher v2.6.4
2. Provisioned one RKE1 and one RKE2 downstream cluster with one of each node type
3. Made two users and set them as cluster owners for both of the downstream clusters
4. Made a backup of the local cluster
5. Upgraded to 2.6.6-rc1
6. Ran the verify.sh script and saw all expected resources
7. Ran the cleanup.sh script that completed in ~18min 
8. Re-ran the verify.sh script and saw the following output

`ubuntu@<redacted>:~$ ./verify.sh
Running verify.sh version unreleased
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+`

`All resources were cleaned up via the cleanup.sh script.`
