### ISSUE TITLE
[Project Monitoring V2, Airgap] rancher/mirrored-kiwigrid-k8s-sidecar 1.15.9 is not found in the rancher-images.txt

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#37677]
**Rancher Server Setup**
- Rancher version: [v2.6.5-rc9](https://github.com/rancher/rancher/releases/tag/v2.6.5-rc9)
- Installation option (Docker install/Helm Chart): Docker install (either is fine)
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 (anything is fine)
- Proxy/Cert Details: Airgapped cluster

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): any

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

N/A
   
**Describe the bug**

rancher-images.txt will not contain the image `rancher/mirrored-kiwigrid-k8s-sidecar` at tag `1.15.9` since our build scripts only watch for images contained in rancher/charts, but the `rancher-project-monitoring` chart embedded in the `prometheus-federator` binary is never shipped to rancher/charts.

**To Reproduce**
 

Cut an RC and watch the images.txt.

**Result**

Image `rancher/mirrored-kiwigrid-k8s-sidecar` at tag `1.15.9` won't exist.

**Expected Result**

Image at tag should exist in `rancher-images.txt`

**Screenshots**

**Additional context**

**Comment by sowmyav27** [comment]
Can be tested on `2.6.5-rc11`

**Comment by ronhorton** [comment]
Verified in `2.6.5-rc11` https://github.com/rancher/rancher/releases/download/2.6.5-rc11/rancher-images.txt

rancher/mirrored-kiwigrid-k8s-sidecar:1.15.9 is present
