### ISSUE TITLE
Selecting Catalog in submenu takes me to Welcome splash page instead

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3767]
Version - master 3/4

Steps to Reproduce: 
1.  Create new environment with 1 host
2.  Go to Setting
3.  Add a catalog
4.  Hover over Applications menu and select Catalog

Results: Goes to Welcome splash screen instead of catalog page.  Same thing if you choose Stack.

Expected: Should not go to Welcome page if I purposely want to go to the catalog page.

**Comment by lvuch** [comment]
@tfiduccia is this still happening no that the catalog link is in the main nav?

**Comment by tfiduccia** [comment]
Version - master 3/22
Verified fixed
