### ISSUE TITLE
[RKE2] etcd snapshot restore using restoreRKEConfig: "all" does not restore cluster config

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#37682]
**Rancher Server Setup**
- Rancher version: 2.6head commit id: `5f5fb23`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.23.6+rke2r2`
- Cluster Type (Local/Downstream): Downstream AWS EC2 - 3 etcd, 2 cp and 3 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

   
**Describe the bug**
[RKE2] etcd snapshot restore using restoreRKEConfig: "all" does not restore cluster config

**To Reproduce**

1. Deploy an RKE2 cluster
2. Take etcd snapshot b1
3. Edit cluster, change Upgrade strategy and etcd options in the cluster config section
4. save changes made. Wait for cluster to come up Active.
5. Verified these changes are saved
6. Restore to etcd snapshot b1 using `restoreRKEConfig: "all"`
7. The cluster goes into updating state and comes back Active
8. The cluster config still remains the same as changed in step 3

**Expected State:**
The cluster config sould be what was during snapshot b1

**Comment by Oats87** [comment]
As of `v2.6.5`, the fields that will be restored when using `all` are:

```
upgradeStrategy
chartValues
machineGlobalConfig
machineSelectorConfig
additionalManifest
registries
```

What will NOT be restored is:
```
etcd
provisionGeneration
etcdSnapshotCreate
etcdSnapshotRestore
rotateCertificates
rotateEncryptionKeys
machinePools
infrastructureRef
```

**Comment by snasovich** [comment]
PR merged and CI passed, so should be ready to test. The comment from @Oats87 above clarifies what's should be restored and what's not in regards to cluster configuration after the change.

**Comment by Josh-Diamond** [comment]
Ticket #37682 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6-bf93f4b182df72fd363cf0cc6f68c34447215ce2-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, create a standard user
3. As standard user, provision a downstream RKE2 cluster with k8s `v1.23.6+rke2r2` - [`3 etcd`, `2 cp`, `3 wkr`]
4. Once provisioned, take a snapshot
5. From `Cluster Management` => `Edit Config`, modify config for `Upgrade strategy` and `etcd` and then `Save`
6. Once cluster comes up `Active`, ensure new changes are reflected in cluster's config
7. Once verified that changes are present, restore to snapshot taken in `step 4`
8. Verified - `Upgrade strategy` config is restored; `etcd` config is not restored; results as expected

Screenshots:

`Step 8 - Upgrade strategy` - [restored]
<img width="1327" alt="Screen Shot 2022-05-11 at 1 02 01 PM" src="https://user-images.githubusercontent.com/46494969/167936405-587ee44f-13c7-4c54-9085-4fb3d9c92465.png">

`Step 8 - Etcd` - [not restored]
<img width="1326" alt="Screen Shot 2022-05-11 at 1 03 50 PM" src="https://user-images.githubusercontent.com/46494969/167937061-04b13f5d-9157-49b7-bea3-dfb9ce2d23dc.png">
