### ISSUE TITLE
Windows worker nodes in RKE2 clusters that require a proxy to complete provisioning will not successfully provision

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#37688]
**Rancher Server Setup**
- Rancher version: v2.6.5
- Installation option (Docker install/Helm Chart): any
- Proxy/Cert Details: use of a proxy is required when provisioning downstream RKE2 Windows worker nodes

**Information about the Cluster**
- Kubernetes version: RKE2 1.22 and 1.23
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom and vsphere node driver

------

- Please describe a brief synopsis of the issue and outcome.

Windows worker nodes in RKE2 clusters that require the use of a proxy for downstream nodes will not successfully provision. This issue exists only in the system-agent implementation for RKE2 Windows as it is unable to use a proxy when attempting to pull images while applying a plan.

This issue is due to a difference in how Go programs use a proxy depending on the OS of the machine it is running on. The use of a proxy on linux only requires the proxy environment variables to be set while on Windows it requires the proxy environment variables as well as proxy-specific registry configuration. 

- Is the issue resolved? 

Not as of the release of Rancher v2.6.5.

- What is the status of the issue?

The issue has been triaged and development of a solution is currently underway.

- Is there a workaround available?

No, there are currently no workarounds available.

- When will this be fixed?

This will be addressed in the next round of RKE2 releases that are brought into Rancher out-of-band via KDM.

**Comment by jameson-mcghee** [comment]
This issue is no longer reproducing in v2.6-head
![image.png](https://zube.io/files/rancher/e45b3fdbb807d4fd1abb1abbaa91b7fb-image.png)
