### ISSUE TITLE
Istio chart 100.0.2+up1.10.4 is shown as an installation option on kubertenes 1.23 clusters kube-version should prevent this

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#37697]
**Rancher Server Setup**
- Rancher version: `v2.6.5-rc11`
- Installation option: Chart
   - If Helm Chart, Kubernetes Cluster and version: RKE1 k8s 1.23
- Proxy/Cert Details: valid certificates no proxy

**Information about the Cluster**
- Kubernetes version: 1.23.6
- Cluster Type: local or downstream
   - If downstream, what type of cluster?: RKE2
   -  Infrastructure Provider: AWS

**User Information**
- What is the role of the user logged in? Admin

  
**Describe the bug**
The Istio chart version 1.10.4 is displayed as an installation option on clusters with kubernetes 1.23.x
This chart version doesn't support k8s 1.23 and shouldn't be available as an install option

**To Reproduce**

- Provision a k8s 1.23 cluster RKE1 or RKE2
- Go to Apps -> Charts -> Istio

**Result**

The chart is available to install

![Screen Shot 2022-05-11 at 2 39 40 PM](https://user-images.githubusercontent.com/27659/167955055-dd840359-5d40-43dd-864e-78c907d3d0fd.png)

**Expected Result**
The chart version 1.10 shouldn't be available on clusters 1.23 or newer

** Additional Context **

This is probably missing the `catalog.cattle.io/kube-version` annotation

**Comment by vivek-infracloud** [comment]
**Validated on rancher version v2.6.5**

**Validation steps followed.**

1. Installed rancher server v2.6.5, KDM pointing to release-v2.6.
2. Provisioned a k8s cluster v1.23.6-rancher1-1
3. Navigated to the App ---> Charts.

**Result:**
Istio chart 100.0.2+up1.10.4 is not shown on k8s version v1.23.

Also validated if the Istio charts installs correctly on  k8s version v1.22, v1.21, v1.20.
All the istio versions installs correctly on the above mentioned k8s versions.

Hence, closing the issue.

**Comment by lomori** [comment]
That's is fine, but when is Istio going to be available for K8s 1.23.x? There is K8s 1.24.x available so 1.23 is not even the latest.

Regards,
Luiz
