### ISSUE TITLE
[project monitoring v2] helm install cattle project monitoring job created in loop

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#37694]
**Rancher Server Setup**
- Rancher version: `2.6-head Commit ID 4bfdf0c`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE2`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.23.6
- Cluster Type (Local/Downstream): AWS Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: 
  `admin`

   
**Describe the bug**
The helm-install-cattle-project-p-xxxxx-monitoring job is being created in a loop

**To Reproduce**
1. install prometheus-federator
2. create project
3. add namespace to project
4. go to Cluster > workload > jobs > cattle-monitoring-system

**Result**
job creation in a loop

**Expected Result**
No loop. job creates and runs.

**Screenshots**

**Additional context**

eventually the jobs are cleaned up (?) and a job runs - so checking too long after the loop results in not seeing the issue
<img width="1617" alt="Screen Shot 2022-05-11 at 2 31 58 PM" src="https://user-images.githubusercontent.com/89212856/167921117-2ad2ae06-a6d5-4e17-870f-d2af73114729.png">

**Comment by aiyengar2** [comment]
This affects RKE2 clusters since the Helm Controller running for RKE2 does not respect namespace boundaries on managing HelmChart resources. Till the fix comes from RKE2 on merging https://github.com/k3s-io/helm-controller/pull/141, users will need to ensure that `helmProjectOperator.helmController.enabled` is set to `false` (which is exposed in the questions.yaml with a comment).

**Comment by ronhorton** [comment]
**Pass** Verified in `2.6-head Commit ID 4bfdf0c` with a hard reset on charts page.

1. installed prometheus-federator
2. created project
3. created namespace
4. created project monitor

`helm-install-cattle-project-p-kz6m7-monitoring ran once - no restarts, no loop`

![Screen Shot 2022-05-11 at 4.27.01 PM.png](https://zube.io/files/rancher/d8d9e6264ac684265b9b89ea965456b7-screen-shot-2022-05-11-at-4-27-01-pm.png)
