### ISSUE TITLE
in small browser ... is hard to see in light theme

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3770]
Version - master 3/4

Steps to Reproduce:
1.  Make your browser small so you get the ... that enables the drop-down for the menus

Results: The little black ... are kinda hard to see and find.

Expected:  Not sure, but in dark view they are white and it looks better.  Not sure how else we should make it so it stands out.

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/507

**Comment by tfiduccia** [comment]
Version - master 3/4
Verified fixed
