### ISSUE TITLE
Can not rename downstream cluster

### ISSUE THREAD

**Issue by wirwolf** [rancher/rancher#37701]
**Rancher Server Setup**
- Rancher version: v2.6.4
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Kubespray
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.8
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Kubespray

**User Information**
- What is the role of the user logged in: Admin(google auth)
   
**Describe the bug**
I can not rename the Downstream cluster in tab Cluster Management

**To Reproduce**
* Open tab Cluster Management
* In any downstream cluster click edit config
* In field "Cluster Name*" change the value
* Click Save
* In the next tab NOT execute 'kubectl apply ' because connection to the cluster will be damaged and the cluster status to be "Unavailable"
* Click "Done"

**Result**
* Name not changed

**Expected Result**
Cluster name is changed to the new name

**Additional context**
![](https://visitor-badge.glitch.me/badge?page_id=rancher_rancher_issues_37701)

**Comment by dgadelha** [comment]
This issue is still valid on v2.6.8.
