### ISSUE TITLE
Project resourceQuotas don't get cleared on the BE side

### ISSUE THREAD

**Issue by aalves08** [rancher/rancher#37704]
**Rancher Server Setup**
- Rancher version: `2.6-head`

**User Information**
- What is the role of the user logged in? `Admin`

**Describe the bug**
It seems like sending either `Project` object properly formatted with the `resourceQuotas` doesn't clear it up the value on the BE side. 
Same goes if we cleared both `CPULimit` and `ConfigMap`, for which we can send either an empty object `{}` (which imo it should work) or the `limit` prop as `null` and it doesn't clear it up.

**Starting scenario**
![Screenshot 2022-05-09 at 09 42 51](https://user-images.githubusercontent.com/97888974/167871207-9662053f-0f8a-446b-8ced-5b8755d1d29f.png)

**Clearing `configMaps`**
![Screenshot 2022-05-09 at 09 42 57](https://user-images.githubusercontent.com/97888974/167871224-057d1973-7902-45fb-b8c7-13cdf4cf07d5.png)

**Payload sent on `PUT` request**
![Screenshot 2022-05-09 at 09 43 15](https://user-images.githubusercontent.com/97888974/167871234-94b86c03-62e7-457f-84a9-7407f3676b36.png)

**Payload received on `PUT` request**
![Screenshot 2022-05-09 at 09 43 26](https://user-images.githubusercontent.com/97888974/167871238-d9923100-1bc1-47c3-a999-fa60e70a9ebf.png)

**To Reproduce**
- Create a project with two `resourceQuotas`: `configMaps` and `CPULimit`
- Hit `Create`
- Edit the recently created project and remove `configMaps`
- Hit `Save`
- Check same project again

**Result**
- `configMaps` `resourceQuota` doesn't get cleared up

**Expected Result**
- `configMaps` should be cleared from the UI

**Screenshots**
Check bug description

**Additional context**
Check original PR from UI team [here](https://github.com/rancher/dashboard/pull/5841)

FYI @gaktive @nwmac @richard-cox : This is a blocker for https://github.com/rancher/dashboard/issues/5173

**Comment by richard-cox** [comment]
@Jono-SUSE-Rancher As requested here's a 2.6.6 issue that needs a lil triaging

**Comment by Jono-SUSE-Rancher** [comment]
Thanks @richard-cox.

@samjustus - Can you take a look at this with Neo, specifically seems like something Ricky or Michael might be interested in. Let me know if it doesn't fall to you guys and we can shift it over to T2 if needed.

**Comment by samjustus** [comment]
https://github.com/rancher/rancher/issues/35688
@richard-cox same as this right?

**Comment by aalves08** [comment]
@samjustus I believe they are similar, but this issue description along with the "Additional context" provides more detail on what is going on.

**Comment by aalves08** [comment]
Closed. Duplicate of https://github.com/rancher/rancher/issues/35688
