### ISSUE TITLE
Rancher 2.6-HEAD - Honor is_default flag for multiple private registries

### ISSUE THREAD

**Issue by zerotens** [rancher/rancher#37710]
Relevant Code:
https://github.com/rancher/rancher/blob/c4d59fa88e2313e1446ba542a21c39e15a17f375/pkg/cluster/private_registry.go#L24-L28

Is Default Option:
https://github.com/rancher/rke/blob/023d212611406f070905031eadf4fa93cd299fbd/types/rke_types.go#L104-L115

@jiaqiluo Could you have a look?

**Comment by jiaqiluo** [comment]
hi @zerotens, Although `config.PrivateRegistries` is a list, because  Rancher UI only allows us to set one private registry,  we return the 1st element from `config.PrivateRegistries` and do not check the `is_default` flag. 
I hope this can answer your question.

**Comment by zerotens** [comment]
Hink @jiaqiluo ,

thanks for your feedback.

> hi @zerotens, Although `config.PrivateRegistries` is a list, because Rancher UI only allows us to set one private registry, we return the 1st element from `config.PrivateRegistries` and do not check the `is_default` flag. I hope this can answer your question.

Please have a look at this PR:
https://github.com/rancher/rancher/pull/37659
