### ISSUE TITLE
dashboard can't use offline environment

### ISSUE THREAD

**Issue by jokerkiller** [rancher/rancher#37714]
rancher on rke1 cluster.
 rancher 2.4.8    kubernetes 1.18          offline environment
for security,   environment is offline
error message:   https://release.rancher.com/dashboard/release-2.4/index.html can't rache.
how to resolve, thanks a lot.

**Comment by cbron** [comment]
2.4 is no longer supported, and much work was done to dashboard between 2.4 and 2.6 versions. Please upgrade to newer version, and if you see problem there feel free to open a new issue. Thanks.
