### ISSUE TITLE
Run Rancher in k8s 1.24

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#37711]
K8S 1.24 was released: https://github.com/kubernetes/kubernetes/releases/tag/v1.24.0
It is time for us to make sure that Rancher can run in a 1.24 cluster smoothy  😄 

This also includes updating the version of embedded k3s for running Rancher in Docker

Important comments highlighted to ensure they are accounted for:
* https://github.com/rancher/rancher/issues/37711#issuecomment-1126413928

Related issue:
-  Fleet: https://github.com/rancher/rancher/issues/37885
- RKE: https://github.com/rancher/rke/issues/2936
 
## Progress
- [x] fleet does not work in the local 1.24 cluster, [an issue](https://github.com/rancher/rancher/issues/37885) is reported
- [x] rke1 provisioning works ( tested 1.23)
- [x] rke2 provisioning does not work, Kinana and I are working on fixing it
- [x] install rancher in HA mode in a 1.24 RKE1 cluster
- [x] install rancher in HA mode in a 1.24 RKE2 cluster
- [x] Update CAPI to 1.2.0 released version (once it's out on https://github.com/kubernetes-sigs/cluster-api/releases)

The following are tracked by https://github.com/rancher/rancher/issues/37727

> - [ ] test if rancher-monitoring and other charts work in the local RKE1 1.24 cluster
> - [ ] test if rancher-monitoring and other charts work in the local RKE2 1.24 cluster
> - [ ] import a 1.24 RKE1 cluster, test if rancher-monitoring and other charts work in the cluster 
> - [ ] import a 1.24 RKE2 cluster, test if rancher-monitoring and other charts work in the cluster (see https://github.com/rancher/rancher/issues/37711#issuecomment-1145108130) 

 
SURE-3940

**Comment by snasovich** [comment]
Looks like there is a change with big impact on Rancher:

Service accounts don’t get secrets by default on 1.24
```
brandond@dev01:~$ kubectl logs -n cattle-system   rancher-7f695c6844-snz4f
2022/05/04 00:20:42 [INFO] Rancher version v2.6.5-rc5 (13aff4797) is starting
2022/05/04 00:20:42 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/05/04 00:20:42 [INFO] Listening on /tmp/log.sock
2022/05/04 00:20:42 [FATAL] no secret assigned to service account cattle-system/rancher
```

```
2022/05/04 00:37:10 [ERROR] Failed to install system chart fleet: timeout trying to get secret for service account: cattle-system/pod-impersonation-helm-op-f4k8q
2022/05/04 00:37:40 [ERROR] Failed to install system chart fleet-crd: timeout trying to get secret for service account: cattle-system/pod-impersonation-helm-op-ld79b
```

> The LegacyServiceAccountTokenNoAutoGeneration feature gate is beta, and enabled by default. When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount. Use the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API to acquire service account tokens, or if a non-expiring token is required, create a Secret API object for the token controller to populate with a service account token by following this [guide](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets). https://github.com/kubernetes/kubernetes/pull/108309

**Comment by jiaqiluo** [comment]
Here is one way to address the no-auto-secret-creation-for-serviceAccount issue mentioned in the [above comment ](https://github.com/rancher/rancher/issues/37711#issuecomment-1126413928) 

We need to create the secret as part of the [rancher Helm chart](https://github.com/rancher/rancher/tree/release/v2.6/chart/templates), the example YAML file looks like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: rancher-token
  namespace: cattle-system
  annotations:
    kubernetes.io/service-account.name: 
type: kubernetes.io/service-account-token
```

Also notice that we need to create the secret for all service accounts that Rancher creates or is related to: fleet, rancher-webhook, and etc.

**Comment by drinktea1a** [comment]
the issue result in my  exsting cluster can't import to rancher ui,  this is my crashbackoff pod error:
level=fatal msg="looking up cattle-system/cattle ca/token: no secret exists for service account cattle-system/cattle".  i try myself to create a secret for the sa, but can't auto generate the binding token,  i don't know how to do next step, downgrade the k8s version ? or wait the rancher the latest version

the rancher docker container log:
[ERROR] Failed to handling tunnel request from remote address :3712: response 400: invalid input, token empty

**Comment by kinarashah** [comment]
We need to do a research spike and figure out the changes required for making rancher run on startup.

**Comment by snasovich** [comment]
@kinarashah , please also refer to the comments on https://github.com/rancher/rancher/issues/37194

**Comment by rosskirkpat** [comment]
I fixed this same issue in rke2 for the windows agent yesterday https://github.com/rancher/rke2/pull/2940. We had modeled the implementation based on how Rancher pulled SA tokens from secrets.

I believe that we may be able to remove the need to create a few secrets and simply use the [ServiceAccountInterface ](https://pkg.go.dev/k8s.io/client-go/kubernetes/typed/core/v1#ServiceAccountInterface) to create a token for the SA instead.

**Comment by kinarashah** [comment]
Thanks @rosskirkpat, that sounds right. It should work well for us to update parts that communicate with api server. 
```
token, err := xx.clusterContext.K8sClient.CoreV1().ServiceAccounts(sa.Namespace).CreateToken(context.TODO(), sa.Name, &authenticationv1.TokenRequest{}, metav1.CreateOptions{})
if err != nil {
    return "", err
}
return token.Status.Token, nil 
```

- Need to first bump dependencies to 1.24 client to be able to call CreateToken, tagged client-go [v1.24.0-rancher1](https://github.com/rancher/client-go/releases/tag/v1.24.0-rancher1) and now updating all required rancher repos 
- Need to check if it works for agents too (we might need to still populate the information in secrets because we also need ca certs from secret, but haven't tested yet due to above)

**Comment by liggitt** [comment]
> we might need to still populate the information in secrets because we also need ca certs from secret

The CA is available in the `kube-root-ca.crt` configmap in every namespace (by default in 1.20+, and unconditionally in 1.21+)

**Comment by liggitt** [comment]
> Need to first bump dependencies to 1.24 client to be able to call CreateToken, tagged client-go [v1.24.0-rancher1](https://github.com/rancher/client-go/releases/tag/v1.24.0-rancher1) and now updating all required rancher repos

The dependency bump is fine to do, but FYI, `CreateToken` has existed in client-go since at least 1.15: https://github.com/kubernetes/client-go/blob/v0.15.7/kubernetes/typed/core/v1/serviceaccount_expansion.go#L29-L30

**Comment by jiaqiluo** [comment]
At all the following places, we need to use the TokenRequset, instead of reading the secret-based token:
(also, I add the explanation of why the token is needed) 

- https://github.com/rancher/steve/blob/release/2.5/pkg/podimpersonation/podimpersonation.go#L294
  - Why: We need the token of the service account and mount it into the proxy container in the "proxy" container in the "helm-operation" pod

- https://github.com/rancher/rancher/blob/release/v2.6/pkg/agent/cluster/cluster.go#L67
  - Why: Cluster-agent in the downstream cluster takes the token of the service account "cattle-system/cattle" and put it in the header of the first connection with the rancher-server.  
 
- https://github.com/rancher/rancher/blob/release/v2.6/pkg/tunnelserver/peermanager.go#L43
  - Why: When Rancher is installed in HA mode, the token of the service account "cattle-system/rancher"  is used for communication between peers(rancher pods)

- https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/dashboard/apiservice/apiservice.go#L144
  - Why: For each v3 APIService object, we create a service account in the namespace cattle-system, and we save the token of the service account to another secret in another namespace 

- https://github.com/rancher/rancher/blob/release/v2.6/pkg/api/norman/customization/monitor/handler_utils.go#L194
  - Why: in monitoring v1, we use the token of the service account used by the monitoring app to communicate with the k8s cluster to get metrics  

- https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/provisioningv2/rke2/common.go#L214
  - Why: not sure

**Comment by jiaqiluo** [comment]
Problem:

1.24 cluster cannot be imported into Rancher successfully, the cattle-cluster-agent pod in the cluster is in a crashing loop. 
Here are the errors in the logs of the cattle-cluster-agent pod 
```
time="2022-06-02T17:06:28Z" level=info msg="Rancher agent version v2.6.4 is starting"
time="2022-06-02T17:06:28Z" level=fatal msg="looking up cattle-system/cattle ca/token: no secret exists for service account cattle-system/cattle"
```
image: rancher/rancher-agent:v2.6.4 

We need to fix the logic [here](https://github.com/rancher/rancher/blob/release/v2.6/pkg/agent/cluster/cluster.go#L67) and build an new image for rancher-agent

**Comment by jiaqiluo** [comment]
https://github.com/rancher/client-go/releases/tag/v1.24.0-rancher1

**Comment by drinktea1a** [comment]
today i'm upgrade to rancher v2.6.6, but the bug still not yet address,  the pod log:
```bash
time="2022-07-11T02:37:07Z" level=info msg="Listening on /tmp/log.sock"
time="2022-07-11T02:37:07Z" level=info msg="Rancher agent version v2.6.6 is starting"
time="2022-07-11T02:37:07Z" level=fatal msg="looking up cattle-system/cattle ca/token: no secret exists for service account cattle-system/cattle"
```

**Comment by snasovich** [comment]
@drinktea1a , Rancher 2.6.6 doesn't support 1.24. The support is planned for 2.6.7 as per the milestone set on this issue.

**Comment by jiaqiluo** [comment]
The following are tracked by https://github.com/rancher/rancher/issues/37727

- [ ] test if rancher-monitoring and other charts work in the local RKE1 1.24 cluster
- [ ] test if rancher-monitoring and other charts work in the local RKE2 1.24 cluster
- [ ] import a 1.24 RKE1 cluster, test if rancher-monitoring and other charts work in the cluster 
- [ ] import a 1.24 RKE2 cluster, test if rancher-monitoring and other charts work in the cluster (see https://github.com/rancher/rancher/issues/37711#issuecomment-1145108130) 


cc @sowmyav27

**Comment by Josh-Diamond** [comment]
Chart validations #37727 - will be tracked separately.  Signing off and closing this out
