### ISSUE TITLE
[Question]: Downstream Cluster/Agent behind SSL intercepting proxy

### ISSUE THREAD

**Issue by wegerts** [rancher/rancher#37723]
**Rancher Version:** 2.6.4
**Certificate:** Public trusted CA
**Downstream Clusters:** Azure AKS behind SSL intercepting proxy (private CA)
**Downstream Cluster Type:** Imported  

**Issue:** Agent logs show error `x509: certificate signed by unknown authority` while loading public resources e.g. helm chart images

**Example logs:**  
```bash
time="2022-05-13T16:11:04Z" level=error msg="Unknown error: Get \"https://global-uploads.webflow.com/5f683649f57c927210b6707e/5f683649f57c9261bab67097_logo.svg\": x509: certificate signed by unknown authority"
time="2022-05-13T16:11:04Z" level=error msg="Unknown error: Get \"https://cdn.softiron.com/helm/assets/icon.png\": x509: certificate signed by unknown authority"
time="2022-05-13T16:11:05Z" level=error msg="Unknown error: Get \"https://sextant-resources.s3.amazonaws.com/icons/large-logo-blue.svg\": x509: certificate signed by unknown authority"
```  

**Question:** How can I provide the custom CA cert to the agent?

**Additional details:**
I was able to make Rancher itself aware of the certificate by [following the docs](https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/chart-options/#additional-trusted-cas) but still try to find a hint how to configure the agent (or all downstream cattle-workloads) to add the custom proxy CA certificate.  
Adding the related environment variables (HTTP(S)/NO_PROXY) during the import/cluster registration process works fine.  

Any help appreciated and kind regards

**Comment by scenox** [comment]
You have to add the ca certs also in the Helm repository yaml, see https://rancher.com/docs/rancher/v2.6/en/helm-charts/#repositories

**Comment by wegerts** [comment]
Thanks for the fast reply - will test it.

**Comment by wegerts** [comment]
Worked like a charm - ty!
... Good example for RTFM ...

By the way: Would it be an option to add proxy- + custom ca settings to the import custom downstream cluster page as well as the (imported) downstream cluster settings?
