### ISSUE TITLE
Charts Support Kubernetes 1.24

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#37727]
### To be validated on both RKE1 and RKE2 clusters

---

# **Team 1 (Neo)** 

- [x] rancher-webhook
- [x] csp-adapter

## By the way of Neuvector integration:

- [x] neuvector

# **Team 2 (Hostbusters)**

- [x] rancher-aks-operator
- [x] rancher-eks-operator
- [x] rancher-gke-operator
- [x] system-upgrade-controller
- [x] rancher-vsphere-cpi
- [x] rancher-vsphere-csi

## By the way of Harvester integration:

- [x] harvester-cloud-provider
- [x] harvester-csi-driver

# **Team 3 (Helm Yes)**

- [x] fleet
- [x] rancher-logging
- [x] prometheus-federator
- [x] rancher-project-monitoring
- [x] rancher-monitoring
- [x] rancher-alerting
- [x] rancher-backup
- [x] rancher-sriov 

## By the way of Longhorn integration:
- [x] longhorn

## By the way of Epinio integration:
- [ ] epinio

## By the way of Infracloud's support:
- [x] rancher-istio (https://github.com/rancher/rancher/issues/37915)
- [x] rancher-cis-benchmark (https://github.com/rancher/rancher/issues/37916)
- [x] rancher-gatekeeper (https://github.com/rancher/rancher/issues/37917)

**Comment by cbron** [comment]
Team 1 should be fine here, as there are no k8s deletions in 1.24, and both charts are not capped until 1.25:
* csp-adapter: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-csp-adapter/0.1.0%2Bup0.1.0-rc8/Chart.yaml#L5
* webhook: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-webhook/1.0.5%2Bup0.2.6-rc3/Chart.yaml

**Comment by sowmyav27** [comment]
Moving this to-test for QA Team to pick it up

**Comment by anupama2501** [comment]
Verified neuvector installation on RKE2 `v1.24.2+rke2r1` and RKE1 `v1.24.2`

**Comment by anupama2501** [comment]
Rechecked on a rancher v2.6.7-rc3, neuvector chart is hidden because of the annotation `catalog.cattle.io/kube-version: '>= 1.18.0-0 < 1.24.0-0'`. Needs to be verified once the annotation is removed.

**Comment by anupama2501** [comment]
Verified rancher-webhook `rancher/rancher-webhook:v0.2.6-rc5` is installed on local cluster k8s v1.24.2, rancher version v2.6.7-rc3

**Comment by markusewalker** [comment]
Verified the following on local cluster K8s v1.24.2:

**aks-config-operator** - **PASS**
Chart version: `rancher/aks-operator:v1.0.6`

**eks-config-operator** - **PASS**
Chart version: `rancher/aks-operator:v1.0.6`

**gke-config-operator** - **PASS**
Chart version: `rancher/gke-operator:v1.1.4-rc2`

**Comment by sowmyav27** [comment]
On 2.6head validated `system-upgrade-controller:v0.9.1` on an upgrade from 1.24.2rke2r1 to 1.24.3rke2rc upgrade using a custom KDM branch. Cluster upgrade went through successfully in an imported RKE2 cluster.

**Comment by sowmyav27** [comment]
@MKlimuszka @brandonsuse Some monitoring usecases Jack has mentioned here to test are - https://github.com/rancher/rancher/issues/37711#issuecomment-1187743778

**Comment by ronhorton** [comment]
team3 backup/restore is in progress.

**Comment by slickwarren** [comment]
# **Windows Team (Clippy's Revenge)**

- [ ] rancher-vsphere-cpi - upstream cut after code freeze for 2.6.7
- [ ] rancher-vsphere-csi - upstream cut after code freeze for 2.6.7

After conversation with @phillipsj the following are not yet officially supported in rancher 
- [ ] rancher-windows-gmsa - not yet supported as per Denise
- [ ] rancher-wins-upgrader - not yet supported as per Denise

**Comment by anupama2501** [comment]
Verified neuvector installation works on RKE2 v1.24.2+rke2r1 and RKE1 v1.24.2 on a v2.6.7-rc6 , chart version `100.0.1+up2.2.2`

**Comment by slickwarren** [comment]
regarding vsphere tests using existing charts:
* 1.24 with rke1 works fine with cpi/csi charts from what I could tell (charts install, able to use storage class/pvc, etc.)
* I was not able to test 1.24 with rke2. 2.6-head has an issue with rke2 provisioning still… 2.6.7-rc6 had a bug where the addon-config doesn’t load the vsphere csi chart options. So I am not able to test it until 2.6-head provisioning is fixed


Harvester checks have passed using rancher v2.6.7-rc5 + harvester v1.0.3-rc1 with 1.24.2-rancher1-1 and 1.24.2+rke2r1 clusters:
cpi: 100.0.2+up0.1.12
csi: 100.0.2+up0.1.11

**Comment by MSpencer87** [comment]
Longhorn checks passing on `2.6.7-rc6` for `Ubuntu 20.04`, `RHEL 8.6`, `openSUSE Leap 15.4` and `SLES 15 SP4`
| Cluster Version | Chart Version | Status |
| :---: | --- | :---: |
| RKE1 v1.24.2 | v1 - 1.2.4 | PASS |
| RKE1 v1.24.2 | v2 - 100.2.0+up1.3.0 | PASS |
| RKE2 v1.24.2+rke2r1 | v2 - 100.2.0+up1.3.0  | PASS |

**Comment by bmdepesa** [comment]
Epinio will be released OOB. 

Closing this since other charts are completed.
