### ISSUE TITLE
Waiting for API to be available on downstream EKS cluster

### ISSUE THREAD

**Issue by YuriiPaneiko** [rancher/rancher#37728]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Helm Chart):
 
**Information about the Cluster**
- Kubernetes version: eks 1.21
- Cluster Type (Downstream):
   - AWS EKS cluster:

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Admin

   
**Describe the bug**

I have created downstream cluster ( EKS provider v1.21, Rancher local cluster v2.6.3). For some reason it stucks on `Waiting for API to be available` , in conditions there are `Cluster agent is not connected`  event. At the same time AWS console shows that EKS cluster is in Active , so basically it means that EKS cluster is running and ready to use. What can the reason of this issue? I understand that Waiting for API to be available  is to generic issue, but I have no idea where I need to look for the problem. The interesting thing that there is no rancher agents on any of worker nodes. Rancher is accessible from downstream nodes, so connection shouldn’t be an issue here.
**To Reproduce**
 
Use the following terraform code to create downstream EKS cluster

```
resource "rancher2_cluster" "env" {
  name = "${terraform.workspace}-${var.environment}-cluster"
  eks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.eks_user.id
    region              = var.aws_region
    kubernetes_version  = "1.21"
    logging_types       = ["audit", "api"]
    subnets             = var.private_subnet_ids
    private_access      = true
    public_access       = false
    security_groups     = [var.security_group_id, var.cross_access_admin_security_group]
    node_groups {
      name                   = "${terraform.workspace}-${var.environment}-cluster-node-group"
      spot_instance_types    = ["t3a.xlarge"]
      desired_size           = 3
      max_size               = 5
      disk_size              = 60
      request_spot_instances = true
      instance_type          = ""
      subnets                = var.private_subnet_ids
      ec2_ssh_key            = aws_key_pair.generated_key.key_name
    }
  }
  timeouts {
    create = "60m"
  }
}
```

**Result**
Downstream cluster is in `Waiting for API to be available`

**Expected Result**

Dowstream cluster is in Active state and ready for connection

**Comment by morrmaker** [comment]
Seeing the same thing 
Rancher Server Setup

Rancher version: 2.6.5
Installation option (Helm Chart):
Information about the Cluster

Kubernetes version: eks 1.22
Cluster Type (Downstream):
AWS EKS cluster:
User Information

What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Admin

However, if we terminate nodes in node group after new nodes come online, the cluster becomes active.

**Comment by Jean-Jacques-Nuoan** [comment]
???

**Comment by empeekdev** [comment]
> ???

Hi @Jean-Jacques-Nuoan . For me it helped to connect to downstream cluster, find `Deployment` for rancher agent and change `dnsPolicy` parameter value from `ClusterFirst` to `Default`, then after few minutes cluster was connected to rancher.
