### ISSUE TITLE
Add SupportConfig endpoint

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#37722]
This is part of the Amazon Billing and Rancher Metrics (CSP adapter) integration.

Rancher needs a method to download a supportConfig bundle.

This bundle should be:
- A single tar file
- In the tar file should be a single JSON which contains the following fields:
  - `SupportEligible bool` - Describes if this installation is support eligible. True if the CSP adapter is installed, not included in the file otherwise.
  - `Platform string` - The architecture used for rancher deployment. Required. Hardcoded to `x86_64` for now.
  - `Product string` - The rancher product string. Required. Should be `cpe:/o:suse:rancher:$RANCHER_VERSION`, where $RANCHER_VERSION is the version of rancher (e.x. `v2.6.3`)
  - `CSP map[string]string` - Info for the CSP. Required if the CSP adapter is installed, missing otherwise. Required Fields:
    - `Name string` the name of the cloud provider - always `aws` for 
        now. Required.
    - `AcctNumber string` the account number of the account the csp 
        adapter is deployed in. Required.
  - `Compliance map[string] string` - Info on the compliance status of this account with the csp license terms. Required Fields:
    - `Status string`. String representing if this account is in compliance. Either "Compliant" Or "NonCompliant".
- This bundle should only be accessible by admin users
- Users should need to be logged in to access the bundle

**Comment by brudnak** [comment]
Testing complete - see internal test plan.
