### ISSUE TITLE
Impersonation resources need more resilience against failed creation or accidental deletion

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#37733]
Ubuntu 
18.04 Nodes, 
Docker 19.03.6, 
RKE1, 
K8s 1.21, 
on-pem VSphere 
Rancher 2.6.3-patch3

The issue is affecting their customers, client wants to mitigate before the upgrade happens in production

**Comment by samjustus** [comment]
the missing piece was the clusterrolebindings, an overloaded API could have missed the creation of these, the script mentioned checks this (dryrun by default) and optionally removes the clusterrole, which then gets recreated along with its corresponding binding ... they have an immediate ability to report on the problematic users and fix them

**Comment by samjustus** [comment]
SURE-4665

**Comment by sowmyav27** [comment]
Reopening for a QA Test Template

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

<hr>
  
## Validation Environment

| Component                 | Version / Type                |
| ------------------------- | ----------------------------- |
| Rancher version           | 2.6.7-rc3 upgraded from 2.6.6 |
| Installation option       | helm high availability        |
| RKE binary version used   | v1.3.11                       |
| If Helm Chart k8s cluster | v1.23.6                       |
| Cert Details              | let's encrypt                 |
| Helm version              | v2.16.8-rancher2              |
| Downstream cluster type   | rke1 linode                   |
| Downstream K8s version    | v1.23.7                       |
| Logged in user role       | administrator                 |
| Browser type              | google chrome                 |
| Browser version           | 103.0.5060.114                |

**ADDITIONAL SETUP**

- Helm command for Rancher **INITIAL 2.6.6** installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.6
```

- Upgrade helm command:

```shell
helm upgrade rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=andy.sbs \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=brudnak@icloud.com \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.7-rc3
```

## Validation steps

1. Setup RKE backed Rancher 2.6.6
2. Create 100 users with Terraform (https://github.com/brudnak/rancher-tf-users)
3. Create a downstream RKE1 Linode cluster
4. Add the users as members to the downstream cluster
5. Using the Rancher UI navigate to the downstream cluster, and in kubectl shell run

```shell
kubectl get clusterrolebindings -A | grep impersonation
```

```shell
kubectl get clusterrolebindings -A | grep impersonation | wc -l
```

6. Delete crbs, make a note of that crb and the user for which it is deleted
7. Upgrade Rancher and try logging in as the users for which the crbs were deleted
8. After upgrade check again with the following command and making sure they were recreated

```shell
kubectl get clusterrolebindings -A | grep impersonation
```

## Additional Info

## RESULTS

#### :white_check_mark: Expected
Expect manually deleted crbs to be recreated and users to be able to login and see clusters they have access to

#### :white_check_mark:Actual
Manually deleted crbs are recreated and users are able to login and see clusters they have access to
