### ISSUE TITLE
Empty tag listed for harvester-csi-driver image in `rancher-images.txt` for v2.6.5

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#37738]
**Rancher Server Setup**
- Rancher version: v2.6.5
 
In the `rancher-images.txt` artifact, an empty tag is seen for the image `rancher/harvester-csi-driver`. This seems to originate from https://github.com/rancher/charts/blob/release-v2.6/charts/harvester-csi-driver/100.0.2%2Bup0.1.11/values.yaml#L10 where the tag is not explicitly set and causing the generating of the artifact to output an empty tag. See below:

```
$ curl -sL https://github.com/rancher/rancher/releases/download/v2.6.5/rancher-images.txt | grep csi-driver
rancher/harvester-csi-driver:
rancher/harvester-csi-driver:v0.1.1
rancher/harvester-csi-driver:v0.1.2
rancher/harvester-csi-driver:v0.1.3
```

Two fold solution for this;
* Add check to artifact generation to fail when no tag is found
* Fix chart to make sure tag is explicitly set so the artifact will contain the correct image + tag.

**Comment by braunsonm** [comment]
Thanks @superseb I just saw you made this issue and reported it here as well: https://github.com/rancher/rancher/issues/37742

Seems to be a couple of issues with this releases images list including missing images.

**Comment by sowmyav27** [comment]
Closing this since it's been checked here https://github.com/rancher/rancher/issues/37738#issuecomment-1185456575https://github.com/rancher/rancher/issues/37738#issuecomment-1185456575
