### ISSUE TITLE
Upgrade to 2.6.5 broke kubectl

### ISSUE THREAD

**Issue by xhejtman** [rancher/rancher#37736]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
   - rke2 1.21.11-rke2r1

**Information about the Cluster**
- Kubernetes version: 1.21.11
- Cluster Type (Local/Downstream):
   -  downstream, imported rke2, baremetal

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
- project member + custom
- copied project member + added role binding rights + disable right to create clusters

**Describe the bug**
after upgrade of rancher to 2.6.5, I am getting:
```
kubectl get pods -n fnbrno-ns 
Error from server (Forbidden): userextras.authentication.k8s.io "shibboleth_user://33c5b2a6e2feb8d4b5f639cd9c2ca76680fdb0b5@einfra.cesnet.cz" is forbidden: User "system:serviceaccount:cattle-impersonation-system:cattle-impersonation-u-cefyghu2vg" cannot impersonate resource "userextras/principalid" in API group "authentication.k8s.io" at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io "fleet-content" not found
```
this is happening only to some users, not all.

**Comment by xhejtman** [comment]
It seems, that if I delete explicitly cluster impersonation role, it gets fixed.

**Comment by xhejtman** [comment]
```
for i in `kubectl get clusterrole | grep imperso | awk '{ print $1 }'`; do kubectl get clusterrole $i -o yaml | grep -q userextras || echo $i; done
cattle-impersonation-u-chm3ww7nfy
cattle-impersonation-u-hj7qtkrmsa
cattle-impersonation-u-idvykyu477
cattle-impersonation-u-ixnsz45ps7
cattle-impersonation-u-mdcnhhnhip
cattle-impersonation-u-muovqijopc
cattle-impersonation-u-x3qrqzwcgk
```

```
kubectl get clusterrole | grep imperso | wc -l
199
```

**Comment by ilyesFh** [comment]
Hello, 

We are facing a similar problem with kubectl,

when we type rancher kubectl get pods --namespace <namespace-name>

it doesn't recognize "pods".

attached screenshot.

Could you please help us

<img width="424" alt="image" src="https://user-images.githubusercontent.com/24758568/170658302-e34708fc-eb39-43c9-80f4-439d2cb903c2.png">

**Comment by xhejtman** [comment]
Remove kubectl cache (usually ~/.kube/cache), you should see impersonation error then, delete that clusterrole, it should be created again and it could work.

**Comment by ilyesFh** [comment]
Thanks, it works
