### ISSUE TITLE
[Research] K8 1.25 Support 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#37734]
Since 1.25 is coming up soon, we need to start researching the removals since this will likely affect many of the APIs.
Only research is part of this issue.

Additionally, it may make sense to try to run Rancher / downstream cluster on 1.25 alpha release to find issues ahead of time.

SURE-4385

**Comment by jiaqiluo** [comment]
When running Rancher `v2.6.7-rc3` on a k8s `v1.25.0-alpha.3` cluster, Rancher does not start the installation of the `fleet` and `rancher-webhook` charts. 

Also, the following error shows in the logs 
```
E0720 02:01:32.935402      33 reflector.go:139] pkg/mod/github.com/rancher/client-go@v1.24.0-rancher1/tools/cache/reflector.go:168: Failed to watch *v1beta1.CronJob: failed to list *v1beta1.CronJob: the server could not find the requested resource
```


see the logs for details.  
[rancher-on-1-25.txt](https://github.com/rancher/rancher/files/9145902/rancher-on-1-25.txt)

**Comment by jiaqiluo** [comment]
Another change that will affect us is the drop of [the metadata.clusterName field](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#v1250-alpha1:~:text=The%20metadata.clusterName%20field%20is%20completely%20removed.%20This%20should%20not%20have%20any%20user%2Dvisible%20impact.%20(%23109602%2C%20%40lavalamp)%20%5BSIG%20API%20Machinery%2C%20Apps%2C%20Auth%20and%20Testing%5D) , we may need to update rancher's CRDs ( like the v3.Cluster)

**Comment by jiaqiluo** [comment]
[Pod Security Policy](https://kubernetes.io/docs/concepts/security/pod-security-policy/) is used in the following charts:

- [ ] Rancher: https://github.com/rancher/rancher/blob/release/v2.6/chart/templates/post-delete-hook-psp.yaml
- [ ] Longhorn: https://github.com/rancher/charts/blob/dev-v2.6/charts/longhorn/100.2.0%2Bup1.3.0/templates/psp.yaml
- [ ] Neuvector: https://github.com/rancher/charts/blob/dev-v2.6/charts/neuvector/100.0.0%2Bup2.2.0/templates/psp.yaml
- [ ] Rancher-alerting-drivers: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-alerting-drivers/100.0.3/templates/hardened.yaml
- [ ] Rancher-backup: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-backup/2.1.3-rc5/templates/psp.yaml
- [ ] Rancher-gatekeeper: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-gatekeeper/100.2.0%2Bup3.8.1/templates/gatekeeper-admin-podsecuritypolicy.yaml
- [ ] Rancher-istio: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-istio/100.4.0%2Bup1.14.1/templates/istio-psp.yaml
- [ ] Rancher-kiali: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-kiali-server/1.41.0/templates/psp.yaml
- [ ] Rancher-logging: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-logging/100.1.3%2Bup3.17.7/templates/psp.yaml
- [ ] Rancher-monitoring: https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-monitoring/100.1.3%2Bup19.0.3
- [ ] Rancher-project-monitoring: https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-project-monitoring/0.1.0
- [ ] Rancher-traching: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-tracing/100.0.0/templates/psp.yaml
- [ ] Rancher-webhook: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-webhook/1.0.5%2Bup0.2.6-rc9/templates/pre-delete-hook-psp.yaml

**Comment by snasovich** [comment]
Closed as the research is completed. The implementation issue is https://github.com/rancher/rancher/issues/38701
