### ISSUE TITLE
Image not available at dockerhub, but listed in rancher-images.txt for v2.6.5

### ISSUE THREAD

**Issue by spielkind** [rancher/rancher#37742]
**Rancher Server Setup**

- Rancher version: v2.6.5

In the rancher-images.txt artifact, rancher/system-agent-installer-k3s:v1.18.20-k3s1 is listed - but this image tag is not available at dockerhub:

`Error response from daemon: manifest for rancher/system-agent-installer-k3s:v1.18.20-k3s1 not found: manifest unknown: manifest unknown
`

**Comment by superseb** [comment]
Seems to be related to https://github.com/rancher/rancher/pull/37586, @rosskirkpat can you confirm and if so, assign so it can be picked up?

**Comment by phillipsj** [comment]
https://github.com/rancher/rancher/issues/37738

**Comment by sirredbeard** [comment]
Hi @superseb this is not a Windows team issue. I believe this would fall under Team 2's purview.

**Comment by rosskirkpat** [comment]
In order to have full provisioning v2 airgap functionality, the system agent installer images needed to be included in the Rancher image list. As we have now found out, this introduced a new problem due to the way the image lists are built by leveraging k3s/rke2 versions in KDM without any logic that cross-references these versions with when system agent functionality was introduced.

**Comment by Josh-Diamond** [comment]
Ticket #37742 - Test Results

Verified on Pre-Release v2.6.7-rc3:
1. View `Rancher Releases > Pre-Release v2.6.7-rc3 > Assets > rancher-images.txt`
2. Verified - No k3s versions prior to 1.21 included
3. Verified - harvester-csi-driver image with empty tag has been removed from `rancher-images.txt`

`rancher/system-agent-installer-k3s`
```
rancher/system-agent-installer-k3s:v1.21.10-k3s1
rancher/system-agent-installer-k3s:v1.21.12-k3s1
rancher/system-agent-installer-k3s:v1.21.13-k3s1
rancher/system-agent-installer-k3s:v1.21.14-k3s1
rancher/system-agent-installer-k3s:v1.21.4-k3s1
rancher/system-agent-installer-k3s:v1.21.5-k3s1
rancher/system-agent-installer-k3s:v1.21.5-k3s2
rancher/system-agent-installer-k3s:v1.21.6-k3s1
rancher/system-agent-installer-k3s:v1.21.7-k3s1
rancher/system-agent-installer-k3s:v1.21.8-k3s2
rancher/system-agent-installer-k3s:v1.21.9-k3s1
rancher/system-agent-installer-k3s:v1.22.10-k3s1
rancher/system-agent-installer-k3s:v1.22.11-k3s2
rancher/system-agent-installer-k3s:v1.22.4-k3s1
rancher/system-agent-installer-k3s:v1.22.5-k3s2
rancher/system-agent-installer-k3s:v1.22.6-k3s1
rancher/system-agent-installer-k3s:v1.22.7-k3s1
rancher/system-agent-installer-k3s:v1.22.9-k3s1
rancher/system-agent-installer-k3s:v1.23.4-k3s1
rancher/system-agent-installer-k3s:v1.23.6-k3s1
rancher/system-agent-installer-k3s:v1.23.7-k3s1
rancher/system-agent-installer-k3s:v1.23.8-k3s2
rancher/system-agent-installer-k3s:v1.24.2-k3s2
```

`rancher/harvester-csi-driver`
```
rancher/harvester-csi-driver:v0.1.1
rancher/harvester-csi-driver:v0.1.2
rancher/harvester-csi-driver:v0.1.3
```
