### ISSUE TITLE
[META] Tigera Operator deploys Prometheus and Calico kube-controllers by default on RKE2

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#37746]
@manuelbuil and I found some interesting default behavior by the Tigera Operator deployed as part of the rke2-calico chart.

By default, Prometheus metrics are exposed and collected as well as five kube-controllers deployed with the Calico deployment in RKE2 (the default in Rancher 2.6.5+ for RKE2). We have seen scaling issues previously with the prometheus deployment in Calico Enterprise which prompted this investigation (this is the same prometheus as in open source Calico).

Currently, we would have to modify the Tigera Operator installation CRD to allow the prometheus metrics and kube-controllers to be configured. 

Some immediate concerns:

- We are using the kubernetes data-store and per the Calico documentation, the namespace, serviceAccount, and policy controllers controllers should only be enabled if the etcd datastore type is used. However, as you can see below, they are enabled by default.
- Scale issues with the architecture of Calico's prometheus https://projectcalico.docs.tigera.io/reference/architecture/overview
- Potential conflicts with Rancher Monitoring v2, especially project monitoring v2. cc: @rancher/rancher2-helm-yes-dev 

https://projectcalico.docs.tigera.io/reference/resources/kubecontrollersconfig#controllers
https://projectcalico.docs.tigera.io/reference/kube-controllers/prometheus

```yml
apiVersion: v1
items:
- apiVersion: crd.projectcalico.org/v1
  kind: KubeControllersConfiguration
  metadata:
    annotations:
      projectcalico.org/metadata: '{"uid":"ea936cb4-50d2-461b-a89a-2cfbb639a99b","creationTimestamp":"2022-05-16T16:27:30Z"}'
    creationTimestamp: "2022-05-16T16:27:30Z"
    generation: 2
    name: default
    resourceVersion: "1278"
    uid: ea936cb4-50d2-461b-a89a-2cfbb639a99b
  spec:
    controllers:
      namespace:
        reconcilerPeriod: 5m0s
      node:
        leakGracePeriod: 15m0s
        reconcilerPeriod: 5m0s
        syncLabels: Enabled
      policy:
        reconcilerPeriod: 5m0s
      serviceAccount:
        reconcilerPeriod: 5m0s
      workloadEndpoint:
        reconcilerPeriod: 5m0s
    etcdV3CompactionPeriod: 10m0s
    healthChecks: Enabled
    logSeverityScreen: Info
    prometheusMetricsPort: 9094
  status:
    environmentVars:
      DATASTORE_TYPE: kubernetes
      ENABLED_CONTROLLERS: node
    runningConfig:
      controllers:
        node:
          hostEndpoint:
            autoCreate: Disabled
          leakGracePeriod: 15m0s
          syncLabels: Disabled
      etcdV3CompactionPeriod: 10m0s
      healthChecks: Enabled
      logSeverityScreen: Info
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by manuelbuil** [comment]
To check what controllers are enabled we should look at the ENABLED_CONTROLLERS env variable that is passed to the kube-controllers pod. By default it is:
```
    - name: ENABLED_CONTROLLERS
      value: node
```
Therefore, we are complying with what the docs say

**Comment by manuelbuil** [comment]
When looking at the installation of calico, I see it deploys three deployments:
- calico-kube-controllers
- calico-typha
- tigera-operator

And one daemonset: calico-node

I don't see it deploying Prometheus (maybe something special must be configured?), so I guess there shouldn't be a conflict with Rancher Monitoring v2, right?

**Comment by MKlimuszka** [comment]
It's not clear what the deliverable here would be. I am closing this. It can be reopened if someone wants to add more clarification.
