### ISSUE TITLE
Docker install private registry not used for coredns on local cluster

### ISSUE THREAD

**Issue by StodaraHodan** [rancher/rancher#37741]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart): docker on standalone vm / airgapped
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:  v1.21.7+k3s1 
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

   
**Describe the bug**
i noticed that on our rancher installation on docker the coredns deployment is not working because the image it uses is not from our private registry, the server cannot directly connect to the internet, we have a private registry that caches external images. 
all other deployments like fleet-agent, use the private registry
i don't know for how long this problem exists, management of other clusters is possible and isn't really noticeble in normal use of rancher.

**To Reproduce**
install rancher on a standalone vm with no access to docker hub using 

docker run -ti --restart=unless-stopped -p 80:80 -p 443:443 -v /opt/rancher:/var/lib/rancher -v /usr/local/share/ca-certificates:/usr/local/share/ca-certificates -e SSL_CERT_DIR='/usr/local/share/ca-certificates/' --privileged privateregistry.local.domain/rancher/rancher:v2.6.4

observe deployment of coredns on local cluster, used image will use docker hub instead of private registry

**Result**
coredns pods cannot start because they use docker hub as registry

**Expected Result**

 private registry is used for coredns pods and are able to pull image and start

**Screenshots**

![2022-05-16_11-28](https://user-images.githubusercontent.com/40172043/168563783-1424d268-e64f-439a-83b7-de08ae3d7058.png)
(black bars are our private registry dns)

**Additional context**

**Comment by StodaraHodan** [comment]
i just discovered that there are manifest files in the volume directory and set the private registry in the coredns manifest (/opt/rancher/k3s/server/manifests/coredns.yaml in my case), now coredns uses the private registry but the pause image doesn't:

` (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "rancher/mirrored-pause:3.6": failed to pull image "rancher/mirrored-pause:3.6": failed to pull and unpack image "docker.io/rancher/mirrored-pause:3.6": failed to resolve reference "docker.io/rancher/mirrored-pause:3.6": failed to do request: Head "https://registry-1.docker.io/v2/rancher/mirrored-pause/manifests/3.6": dial tcp 52.71.127.58:443: connect: connection refused `

**Comment by StodaraHodan** [comment]
I edited the manifest in the container to use the private registry
/var/lib/rancher/k3s/server/manifests/coredns.yaml

but this should honor the private registry setting

**Comment by sohnaeo** [comment]
@StodaraHodan 

I believe you have to use the below option while running the command

-e CATTLE_SYSTEM_DEFAULT_REGISTRY=privateregistry.local.domain -e CATTLE_SYSTEM_CATALOG=bundled 

All the helm charts are already on the image so bundled option will install it from the docker itself instead going on the inetrnet,

In my case, below doesnt work

```
-v /opt/rancher:/var/lib/rancher -v /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
```
I have private registry and need to use in house CACERT but somehow it is not working, 

I tried different locations

/usr/local/share/ca-certificates:/usr/local/share/ca-certificates:
/usr/local/share/ca-certificates:/etc/pki/trust/anchors/tls-ca-bundle.pem

But somehow SUSE doesn't import these certs and when I run curl against my private registry, it throws an error.

I can make it work on Redhat though, also Rancher 2.5 works as it is Ubuntu so somehow Suse doesnt work.

**Comment by Martin-Weiss** [comment]
@sohnaeo - not sure if this is relevant - but on „SUSE“ OS the process to add trusted CAs is to copy the CA certificate to /etc/pki/trust/anchors and execute „update-ca-certificates“. HTH

**Comment by sohnaeo** [comment]
> @sohnaeo - not sure if this is relevant - but on „SUSE“ OS the process to add trusted CAs is to copy the CA certificate to /etc/pki/trust/anchors and execute „update-ca-certificates“. HTH

@Martin-Weiss 

Thank you for the prompt reply. Exactly thats what I did but it still not working, very annoying.

```
212c9c74883f:/var/lib/rancher # ls -al /etc/pki/trust/anchors
total 8
drwxr-xr-x 1 root root   31 Jul 29 06:22 .
drwxr-xr-x 1 root root   21 Apr  8  2021 ..
-rw-r--r-- 1 root root 5624 Jul 29 06:22 ca-additional.pem

212c9c74883f:/var/lib/rancher # update-ca-certificates 
212c9c74883f:/var/lib/rancher #

212c9c74883f:/var/lib/rancher # curl https://docker-repo
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

12c9c74883f:/var/lib/rancher # curl --cacert /etc/pki/trust/anchors/ca-additional.pem https://docker-repo
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 400 Not a Docker request</title>
</head>
<body><h2>HTTP ERROR 400 Not a Docker request</h2


````
