### ISSUE TITLE
After a huge spike of requests on the API server the RKE downstream cluster got off on the Rancher UI

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#37747]
SURE-4484

**Rancher Server Setup**
- Rancher version: 2.6.4
Number of nodes: 2 
Node OS version: Ubuntu 20.04.4 LTS

*Upstream Cluster:* K3S v1.22.5+k3s1 (containerd://1.5.8-k3s1) ** **

*Downstream Cluster:*
Number of Downstream clusters: 23 (3 controlplane + etcd, 20 workers)
Node OS: Ubuntu 20.04.4 LTS
RKE/RKE2/K3S version: RKE 
Kubernetes version: v1.21.10

   
**Describe the bug**
After a huge spike of requests on the API server on the RKE downstream cluster, the cluster got "off" on the Rancher UI. It shows green/Active but wasn't able to load any page related to it.   

**Result**
The cluster becomes inaccessible.

**Expected Result**
Be accessible and manageable. 

Business impact:
The customer wasn't able to manage the workload through this cluster using the Rancher UI.

Troubleshooting steps:
Checked both logs on the Rancher server and the downstream cluster.

Workaround:
Is workararound available and implemented? yes
What is the workaround: Restart of the rancher pods.

**Comment by nickvth** [comment]
It looks like we have the same issue, kubectl is also not working any more via rancher url, authorized endpoint is still working

Unable to connect to the server: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
