### ISSUE TITLE
in small browser the submenu should highlight when I mouse over them

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3774]
Version - master 3/4

Steps to Reproduce: 
1.  make your browser small
2.  Click on the ...
3.  Move your mouse over Hosts or any other submenu

Results: The submenus do no highlight when I hover over them

Expected: They should do same thing as main menu items and highlight

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/507

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/507

**Comment by tfiduccia** [comment]
Version - master 3/4
Verified fixed
