### ISSUE TITLE
Publish csp-adapter to ECR

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#37757]
CSP-adapter will need to get either published or mirrored to ECR.

No QA needed, just that image get's published.

Rancher PR: https://github.com/rancher/rancher/pull/36217

**Comment by MbolotSuse** [comment]
## Pre-release validation template

This can be used with v1.0.0-rc8 of the csp adapter, which is now available in `rancher/charts` on the `dev-v2.6` branch.

## New Functionality Overview

The csp adapter has been pushed to to ecr in two repos, and the chart has been configured to default to an aws repo when aws is the target CSP.

## What was fixed, or what changes have occurred

- The chart has been changed to use a system default registry of `709825985650.dkr.ecr.us-east-1.amazonaws.com/suse/` when AWS is the desired csp. This can be overridden if the user supplies a system default registry
- Images for the adapter have been pushed to `709825985650.dkr.ecr.us-east-1.amazonaws.com/suse/rancher/rancher-csp-adapter` and `709825985650.dkr.ecr.us-east-1.amazonaws.com/suse/rancher/rancher-csp-adapter-eu`

## Areas or cases that should be tested

Basic adapter install functionality for the csp-adapter for both the EU and the America Listings. Install, ensure the image pulls, and that a simple supportconfig can be generated.

## What areas could experience regressions

Basic install functionality.

## Are the usage steps accurate/minimal?
Yes. The install steps for the adapter remain valid for the US listing. The eu listing will require a new set line:

```
--set image.repository=rancher/rancher-csp-adapter-eu
```

**Comment by brudnak** [comment]
<table>
    <tbody>
        <tr>
            <th>Test</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual</th>
            <th>Pass/Fail</th>
        </tr>
        <tr>
            <td>Basic adapter install functionality for the csp-adapter for the EU listing</td>
            <td>See internal test plan</td>
            <td>CSP Adapter installs successfully & pulls image from ECR</td>
            <td>CSP Adapter installs successfully & pulls image from ECR</td>
            <td>:white_check_mark: PASS</td>
        </tr>
        <tr>
            <td>Basic adapter install functionality for the csp-adapter for the America listing</td>
            <td>See internal test plan</td>
            <td>CSP Adapter installs successfully & pulls image from ECR</td>
            <td>CSP Adapter installs successfully & pulls image from ECR</td>
            <td>:white_check_mark: PASS</td>
        </tr>
    </tbody>
</table>
