### ISSUE TITLE
Openstack node driver fails to accept cacert in UI

### ISSUE THREAD

**Issue by svogt** [rancher/rancher#37754]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart):
   - Helm chart on 3-node k3s cluster (v1.21.7+k3s1)

**Information about the Cluster**
- Kubernetes version: k3s v1.22.9+k3s1
- Cluster Type: downstream
   - node driver "Openstack"

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
Cannot provider the Openstack API certificate via UI

**To Reproduce**
Try creating a cluster via cluster manager and node driver Openstack. There is a form field called cacert (File contents for cacert). providing the CA cert (root, root+intermediate, full chain including the API endpoint cert or only the API endpoint cert) as PEM encoded X.509 certs

**Result**
Nodes cannot be created due to "illegal PEM file format" 

**Expected Result**
Nodes should be created via Openstack API

**Comment by svogt** [comment]
Still relevant, though meanwhile I've setup my clusters via Terraform...

**Comment by HadesShade** [comment]
Issue is still exist in Rancher v2.9.1
