### ISSUE TITLE
only ipv6 environment

### ISSUE THREAD

**Issue by liseago** [rancher/rancher#37763]
Want to know if can deploy a Rancher K8S cluster in an ipv6-only network environment, where to find the installation procedure documentation？  thanks your help。

**Comment by DanielCambray** [comment]
I do have kind of the same question. I have a running cluster with rancher. When I try to add a ipv6 only node, the rancher-agent is rebooting endlessly with the message : "RTNETLINK answers: Network is unreachable" even if I can ping the ipv6 address of the rancher server from the host.
