### ISSUE TITLE
kubernetes doesn't recognize host

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3776]
Version - master 3/4

Steps to Reproduce: 
1.  Create a Kubernetes environment
2.  Switch to that environment
3.  Add a Digital Ocean host/machine, wait for it to fully setup
4.  Go to kubectl page and type in kubectl get node

Results: Nothing in there

Expected: Should show the host info

**Comment by vincent99** [comment]
This is the one that requires the host name to have a capital letter in it...

**Comment by tfiduccia** [comment]
Version - master 3/9
Verified fixed - test with capitals, lower case and dashes
