### ISSUE TITLE
Rancher fails to start on Kubernetes 1.24

### ISSUE THREAD

**Issue by brandond** [rancher/rancher#37769]
```
2022/05/04 00:20:42 [INFO] Rancher version v2.6.5-rc5 (13aff4797) is starting
2022/05/04 00:20:42 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/05/04 00:20:42 [INFO] Listening on /tmp/log.sock
2022/05/04 00:20:42 [FATAL] no secret assigned to service account cattle-system/rancher
```

This is caused by a change in Kubernetes 1.24, documented in the upstream changelog:
> The LegacyServiceAccountTokenNoAutoGeneration feature gate is beta, and enabled by default. When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount. Use the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API to acquire service account tokens, or if a non-expiring token is required, create a Secret API object for the token controller to populate with a service account token by following this [guide](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets). ([#108309](https://github.com/kubernetes/kubernetes/pull/108309), [@zshihang](https://github.com/zshihang))

If I manually create the secret and link it to the ServiceAccount, it makes it a little further:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: rancher
  namespace: cattle-system
  annotations:
    kubernetes.io/service-account.name: "rancher"
type: kubernetes.io/service-account-token
```

...but still dies on other SA tokens - there are apparently a bunch of these that we expect to find:
```
2022/05/04 00:37:10 [ERROR] Failed to install system chart fleet: timeout trying to get secret for service account: cattle-system/pod-impersonation-helm-op-f4k8q
2022/05/04 00:37:40 [ERROR] Failed to install system chart fleet-crd: timeout trying to get secret for service account: cattle-system/pod-impersonation-helm-op-ld79b
```

As suggested in the changelog note, we need to either create and link the secrets ourselves, or use the TokenRequest API to create the tokens ourselves as needed.

Note: Tokens were previously read from from the injected secret volume; when this feature went away we migrated over to reading the secrets directly but this still wasn't quite the right thing to do either:
* https://github.com/rancher/rancher/pull/32332

**Comment by brandond** [comment]
cc @snasovich @annablender @rosskirkpat

**Comment by snasovich** [comment]
@brandond , thank you for your report. Addressing this is tracked as part of adding support for 1.24 in Rancher, more specifically https://github.com/rancher/rancher/issues/37711#issuecomment-1126413928.

Closing this issue as a duplicate.

**Comment by brandond** [comment]
Thanks! I see that someone had already pasted in my comments from Slack, I mostly just wanted to be sure they were captured somewhere externally.
