### ISSUE TITLE
 Error while applying agent YAML, it will be retried automatically: exit status 1, Unable to connect to the server: remote error: tls: internal error 

### ISSUE THREAD

**Issue by Kritika2206** [rancher/rancher#37764]
I'm trying to import EKS cluster to my rancher server but getting this error " **Error while applying agent YAML, it will be retried automatically: exit status 1, Unable to connect to the server: remote error: tls: internal error** "after importing.

**Comment by immortalkrazy** [comment]
Error while applying agent YAML, it will be retried automatically: exit status 1, Unable to connect to the server: remote error: tls: internal error
- Rancher 2.6.5
- RKE 1.3.11
- docker 20.10.17
