### ISSUE TITLE
Job Annotations Longer than 64 char are Truncated

### ISSUE THREAD

**Issue by luthermonson** [rancher/rancher#37774]
A wrangler bug caused by serializing jobs truncated annotations to 64chars. We will need to roundtrip and pull the job out again in wrangler to make it work properly.

**Comment by cbron** [comment]
Similar to: https://github.com/rancher/rancher/issues/37766

**Comment by KevinJoiner** [comment]
## Reroduce 
branch: https://github.com/KevinJoiner/rancher/tree/rancher-wrangler-test 
1. Run custom image [kevinjoiner/rancher:v2.6.7-wranger-test-before](https://hub.docker.com/layers/251632139/kevinjoiner/rancher/v2.6.7-wranger-test-before/images/sha256-a89a96ea6661acab56d9c70a766f1844112e59e23730690b020b6f82f50d7585?context=repo)
2. navigate to `https://<SERVER_URL>/test/wrangler`
3. verify job update fails (Failed to update job DesiredSet - Replace Wait batch/v1, Kind=Job default/wrangler-test for wrangler-test-update)

## Validate
branch: https://github.com/KevinJoiner/rancher/tree/rancher-wrangler-test-after
1. Run custom image [kevinjoiner/rancher:v2.6.7-wranger-test-after](https://hub.docker.com/layers/251632909/kevinjoiner/rancher/v2.6.7-wranger-test-after/images/sha256-2a56e36ac0fc722a71cea73c1bcb06f469fd79281f38767d4c90c8cc2e31181e?context=repo)
2. navigate to `https://<SERVER_URL>/test/wrangler`
3. verify job update was successful (Job update was successfully applied!) .

**Comment by cbron** [comment]
@sowmyav27 both kevin and tucker dev-validated this, so we should be good to close. This is still tough to test since it's not in the product. We are going to think about how we might add a test around this, but it seems unlikely.
