### ISSUE TITLE
Kubernetes dark theme color issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3777]
Version - master 3/4

- [ ] Can't see Namespaces in the select drop-down
![image](https://cloud.githubusercontent.com/assets/11514927/13538610/dccf4618-e208-11e5-8e0a-5816453222d5.png)

- [ ] Can't see selected environment 
![image](https://cloud.githubusercontent.com/assets/11514927/13538659/204d7338-e209-11e5-8f5a-0d2cf14de014.png)

- [ ] Menu items are hard to see
![image](https://cloud.githubusercontent.com/assets/11514927/13538638/0282987e-e209-11e5-81de-fca7d1773016.png)

- [ ] Service, RCS, and PODs individual pop-up menus hard to see.  A little bit too opaque and the white text against the light blue is hard to see.
![image](https://cloud.githubusercontent.com/assets/11514927/13538797/c9994ad4-e209-11e5-86cb-7f30417d8b8e.png)

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/507

**Comment by tfiduccia** [comment]
Version - master 3/4
Verified fixed
