### ISSUE TITLE
[v2.6.5] Failing to create RKE cluster with spot instances enabled.

### ISSUE THREAD

**Issue by goon94** [rancher/rancher#37775]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Docker Install
- Docker version 20.10
- 
**Information about the Cluster**
- Kubernetes version: v1.20.11
- Cluster Type (Local/Downstream):
   - RKE Cluster with Amazon EC2 instances

**User Information**
- Admin
   
**Describe the bug**
After the latest release of rancher (2.6.5) I am unable to successfully create an RKE cluster using the spot instance option enabled.

When I try to create a cluster using spot instances I get the following error: 
`[ERROR] error syncing 'c-5t7fq/m-nkr6k': handler node-controller: Error creating machine: Error in driver during machine creation: Error request spot instance: InvalidParameter: 'instance' is not a valid taggable resource type for this operation., requeuing`

I believe I identified the changes that are causing this error in the following commit: [Apply tags to resources created for EC2 instances.](https://github.com/rancher/machine/commit/ebdf56c88e1a766220c259ea4c904a47e7dce962)

For the moment I reverted rancher to version 2.6.4 until a fix is applied.

**To Reproduce**
Create a valid node template with credentials, instance type c5.xlarge, ami (example ami-05ba3a39a75be1ec4 in Mumbai), select the spot instance checkbox, and set the spot instance price to 1.
Then create a RKE cluster using that node template. 

**Result**
Error during machine creation with the above error message. 

**Expected Result**
Nodes should be launched successfully.

SURE-4660

**Comment by markusewalker** [comment]
Verified that this is passing on `v2.6-head` https://github.com/rancher/rancher/commit/e93864b3364e18e81dfd5c12366206f2d495cf52

**ENVIRONMENT DETAILS**
- Rancher HA
- Rancher version
     - Reproduced version: `v2.6.5`
     - Verified version: `v2.6-head` https://github.com/rancher/rancher/commit/e93864b3364e18e81dfd5c12366206f2d495cf52
- RKE1 version: `v1.23.6`
- Browser: Chrome

**TEST RESULT**
PASS

**REPRODUCTION STEPS**
1. Setup Rancher and navigate to the UI in your browser.
2. Created a standard user and logged into Rancher with that user.
3. Created a downstream RKE1 EC2 node driver cluster with `Spot Instance` enabled.
     - In the `NodeTemplate` setting, set the `Spot Price` to be `1.50` and proceed with the rest of the prompts to save the `NodeTemplate`.
4. Created the new cluster and verified that the cluster DID NOT provision successfully. It is stuck in the following:
![image](https://user-images.githubusercontent.com/52591819/170547930-2a8e7987-0e73-4d1c-9859-573ae0691ef2.png) 
     - Looking inside the machine pools of the clusters, eventually I see the following error:
![image](https://user-images.githubusercontent.com/52591819/170547973-e8fb9bcd-836f-4f50-8c33-835c40b25993.png) 
5. Repeated steps 2-4, but ensured that the `Spot Instance` is disabled. Verified that I could provision an RKE1 cluster.
6. Repeated steps 2-4, but ensured that not only the `Spot Instance` is enabled, but that I also specified adding a tag. The RKE1 cluster DOES NOT provision as shown in the screenshots in step 4.
7. Repeated steps 2-4, but ensure that not only the `Spot Instance` is disabled, but that I also specified adding a tag. Verified that I could provision an RKE1 cluster.

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in your browser.
2. Created a standard user and logged into Rancher with that user.
3. Created a downstream RKE1 EC2 node driver cluster with `Spot Instance` enabled.
     - In the `NodeTemplate` setting, set the `Spot Price` to be `1.50` and proceed with the rest of the prompts to save the `NodeTemplate`.
4. Created the new cluster and verified that the cluster DOES provision successfully. See below:
![image](https://user-images.githubusercontent.com/52591819/170548044-d80481a5-82b6-4dc5-aa3e-432cab975e80.png) 
5. Repeated steps 2-4, but ensured that the `Spot Instance` is disabled. Verified that I could provision an RKE1 cluster as shown in the above screenshot.
6. Repeated steps 2-4, but ensured that not only the `Spot Instance` is enabled, but that I also specified adding a tag. The RKE1 cluster DOES provision as shown in the screenshots in step 4.
7. Repeated steps 2-4, but ensure that not only the `Spot Instance` is disabled, but that I also specified adding a tag. Verified that I could provision an RKE1 cluster.

**Comment by niusmallnan** [comment]
According to feedback from community user, there are still problems with the m6 type.
https://github.com/rancher/rancher/issues/38176#issuecomment-1173534378
