### ISSUE TITLE
[Monitoring V2] Rebase Monitoring V2 to upstream kube-prometheus-stack 40.x.x

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#37778]
Need to rebase Monitoring V2 chart to latest upstream

Currently, the latest is at 19.x.x.

**Comment by aiyengar2** [comment]
Should use script in https://github.com/rancher/charts/pull/1079 to execute the rebase!

**Comment by aiyengar2** [comment]
The changes for this rebase have now been merged to dev-v2.6. Here are some notes for QA on things to specifically focus on testing related to fixes put in the PR or from upstream:

- Check that everything works in a cluster that enforces network policies, like a hardened cluster, since we introduced some new ones
- Check that everything works in a hardened cluster in that our PSPs provide enough permissions to work since we made modifications
- Review new dashboards in all environments
  - Grafana Overview dashboard
  - Nodes / MacOS dashboard: doesn't break anything... probably not useful though cause there are no kubernetes darwin nodes but this just comes from upstream
- Review upgrade scenarios across all specialized environments to ensure that there is no issue going from older to newer versions in terms of workloads, since there were label changes on workloads that are deployed
  - Note: there is a new job that is deployed in order to wipe out older versions of kube-state-metrics, node-exporter, and prometheus-adapter that are deployed on an upgrade due to a change in the labels. On upgrading from the last version of monitoring to this one, dashboards should remain stable as metrics should continue to be collected as expected (although there might be a slight gap in the dashboards during the upgrade process)
- Ensure that adding job label onto coredns dashboards does not result in errors in displaying data on the dashboards on specialized environments
- Ensure CPU utilization dashboards under k8s resources don't lose visualized data on an upgrade since we have modified to using a new recording rule for it
- Ensure Grafana can still be monitored since we modified the ServiceMonitor definition that is used to scrape grafana
- Ensure that setting `.Values.cleanPrometheusOperatorObjectNames: true` results in a valid installation for both an upgrade and a install
  - data loss is acceptable here since it's clearly noted that setting this value will require data migration. We are not explicitly supporting this feature, but it should not break if it was set on a clean install
- Ensure that etcd monitoring still works in RKE / RKE2 clusters. I checked the codebases to see if there were any changes, but upstream has moved towards using 2381 as the etcd port now.
  - ref: https://github.com/kubernetes/kubernetes/commit/99b64f1e8e93b254aa3435c5a52e283391fb1d95
  - ref: https://github.com/prometheus-community/helm-charts/pull/2264
- If you use a k3s cluster, the etcd dashboard should not show up
- Monitoring should not show up in a 1.25 cluster
- The alertmanager secret should only be created on an install and left behind on an uninstall, if re-installed the old secret should be leveraged if receivers have already been configured
- All dashboards should show `Prometheus` as the datasource in the dropdown if the dropdown exists; previously it may have shown `default` instead
- Ensure all workloads are properly deployed on a Windows cluster (RKE1 and RKE2); they should have nodeSelectors and tolerations that indicate that they are linux only (some new workloads were introduced, so this should be re-validated)
- nginx containers on Prometheus and Grafana pods should no longer show any errors due to `duplicate MIME type "text/html" in /nginx/nginx.conf:43`
- RKE2 kube proxy dashboard should show a number of proxies up equivalent to the number of nodes in the cluster, as should kubelet; previously, kube proxy would only be scraped from worker nodes due to incorrect tolerations
- Rancher dashboard references to kube-controller-manager should have valid metrics now in k3s clusters
- Grafana should be able to be disabled on install
- RKE2 ingress nginx should work correctly across ALL RKE2 versions. This may be tough to test and the context is described in https://github.com/rancher/charts/pull/2162/commits/4d3bd3dc08e7e6ab7e251228a7b8b0d1ed64e2da and https://github.com/rancher/rancher/issues/39227. Specifically, at least 1 version in the following ranges should be tested
  - `>= 1.18.0-0 < 1.19.0-0`
  - `>= 1.19.0-0 < 1.20.0-0`
  - `>= 1.20.0-0 < 1.21.0-0`
  - `>= 1.21.0-0 < 1.22.0-0`
  - `>= 1.22.0-0 < 1.22.12-0`
  - `= 1.22.12-0`
  - `> 1.22.12-0 < 1.23.0-0`
  - `>= 1.23.0-0 < v1.23.9-0`
  - `= v1.23.9-0`
  - `> v1.23.9-0 < 1.24.0-0`
  - `>= 1.24.0-0 < v1.24.3-0`
  - `= v1.24.3-0`
  - `> v1.24.3-0 < 1.25.0-0`
  - All the above ranges, but with RC versions of RKE2 (optional to test, but this was also fixed)
  - Note: if you look at the commit message above, I did a fairly rigorous automated test in order to determine if these versions were regressed via script, but we should definitely confirm that these versions still work. Since my regression testing only ensured if the behavior that was modified was what we expected, it did not check if the previous behavior was actually still correct (which can only be validated on live clusters). If there are any other issues noted on these cluster types (dashboards are missing, targets are down, etc.) please file issues for them!

**Comment by aiyengar2** [comment]
Also note https://github.com/rancher/rancher/issues/38934 when testing this issue since RKE1 clusters at 1.24 will not have a full suite of metrics. For QA: can you also double check across all versions of RKE to see if 1.21-1.23, 1.18-1.19 are affected? I did not observe issues in an RKE 1.20 cluster

**Comment by aiyengar2** [comment]
Also note comment in https://github.com/rancher/charts/pull/2162/commits/a9d369166f806f55d37a72ce383282fc3b8167e7, with a related issue in https://github.com/rancher/rancher/issues/39385.

I'm not sure if testing additional datasources is in QA's list of things to test, but if it is that behavior will be impacted due to the linked issue that is yet to be resolved. You will need to redeploy the Grafana pods in order to see new datasources added via configmap be reloaded correctly

**Comment by aiyengar2** [comment]
https://github.com/rancher/charts/issues/1780 should be tested

**Comment by aiyengar2** [comment]
https://github.com/rancher/charts/issues/1845 should be tested

**Comment by aiyengar2** [comment]
https://github.com/rancher/charts/issues/1865 should be tested too across all RKE1 versions to ensure we don't have a regression

**Comment by aiyengar2** [comment]
https://github.com/rancher/charts/issues/2042 should be tested

**Comment by aiyengar2** [comment]
https://github.com/rancher/charts/issues/2043 should be tested

**Comment by aiyengar2** [comment]
https://github.com/rancher/charts/issues/2175 should be tested

**Comment by aiyengar2** [comment]
https://github.com/rancher/charts/issues/2129 should be tested

**Comment by aiyengar2** [comment]
@ronhorton adding one more fix I caught in https://github.com/rancher/charts/pull/2189 to this issue since it hasn't been moved to QA working yet!

**Comment by aiyengar2** [comment]
https://github.com/rancher/rancher/issues/39725

**Comment by vivek-infracloud** [comment]
Tested the Monitoring V2 chart on following versions with Rancher v.2.6.9
| Cluster type | k8s version |
| --- | --- |
| hardened ubuntu rke1 | 1.18 |
| ubuntu rke1 | 1.19 |
| ubunutu rke2 | 1.21 |
| ubuntu rke1 | 1.22 |


### Scenario 1
Tested the Monitoring and Alerting P0 test cases in following way.

1. Install previous version - 100.1.3+up19.0.3
2. After installation completes, upgraded to latest version - 100.2.0+up40.1.2
3. Tested monitoring p0 test cases - **PASS**
4. Tested alertmanager p0 test cases - **PASS**

However, the other test scenario in which, setting up the telegram config with monitoring version `100.1.3+up19.0.3` and then upgrading to monitoring version 100.2.0+up40.1.2 fails.

### Scenario 2
Steps that were followed in this scenario.

1. Install previous version - 100.1.3+up19.0.3
2. Install alerting version - 100.0.3
3. Tested monitoring p0 test cases - **PASS**
4. Tested alertmanager p0 test cases - **PASS** (Successfully received alert on telegram)
5. Upgraded monitoring chart to latest version - 100.2.0+up40.1.2
6. After upgrade, failed to receive alert on telegram. Following error was seen in alerting-sachet pod.
`2023/01/19 14:08:38 main.go:247: Error: {"Error":true,"Status":400,"Message":"Receiver missing: default/amc-7/prom2sms"}Thu, Jan 19 2023 7:39:38 pm`

The above failure is because of the way `receivers: name` is set in alerting configuration in monitoring version `100.1.3+up19.0.3` Vs. `100.2.0+up40.1.2`

In 100.1.3+up19.0.3 version the telegram receiver config should be provided in the following way.
```
receivers:
  - name: 'default-amc-7-prom2sms'
```
However, in the 100.2.0+up40.1.2 version the telegram receiver config has changed into following way.
```
receivers:
  - name: 'default/amc-7/prom2sms'
```

**Comment by vivek-infracloud** [comment]
Considering the Scenario 2, is it considered as a bug or can we close this issue?

**Comment by rishabhmsra** [comment]
Also tested the Monitoring v2 on rancher v2.7-head using below k8s versions:

Cluster type | k8s version | Result
-- | -- | --
hardened ubuntu rke2 | 1.23 | Fail
ubunutu rke1 | 1.24 | Pass
hardened k3s | 1.24 | Fail

- On hardened RKE2 v1.23 and hardened k3s v1.24 clusters:
- Installed Monitoring v2 `101.0.0+up19.0.3`. Chart installed successfully.
- Upgraded the chart to `101.1.0+up40.1.2` version and it failed with below error:
```
...
jobs.batch "rancher-monitoring-upgrade" not found
creating 1 resource(s)
Watching for changes to Job rancher-monitoring-upgrade with timeout of 10m0s
Add/Modify event for rancher-monitoring-upgrade: ADDED
rancher-monitoring-upgrade: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Add/Modify event for rancher-monitoring-upgrade: MODIFIED
rancher-monitoring-upgrade: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Starting delete for "rancher-monitoring-upgrade" Job
Error: UPGRADE FAILED: pre-upgrade hooks failed: timed out waiting for the condition
```

**Comment by vivek-infracloud** [comment]
Logged an issue for Scenario 2 failure. - https://github.com/rancher/rancher/issues/40358

Rest tests are working fine, hence closing the issue.
