### ISSUE TITLE
[Monitoring V2] Upgrade 100.1.0+up19.0.3 > 100.1.2+up19.0.3 fails with error "Error: UPGRADE FAILED: cannot patch ... with kind PrometheusRule: Internal error occurred"

### ISSUE THREAD

**Issue by caliskanugur** [rancher/rancher#37788]
**Rancher Server Setup**
- Rancher version: `2.6.5`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `rke1 v1.3.11`
- Proxy/Cert Details: `N/A`

**Information about the Cluster**
- Kubernetes version: `Local (v1.23.6) & Downstream (v1.23.6)`
- Cluster Type (Local/Downstream):`Local & Downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `aws rke1`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `Admin`

   
**Describe the bug**

Upgrading monitoring v2 `100.1.0+up19.0.3` to `100.1.2+up19.0.3` fails after the first-time upgrade.

**To Reproduce**
 

1. Install `100.1.0+up19.0.3` to project `System` and wait for deployments & statefulsets to be ready
2. Upgrade the chart to `100.1.2+up19.0.3` and wait for it to finish upgrading properly
3. Uninstall the chart
4. Wait for the uninstallation to finish successfully
5. Delete the `cattle-monitoring-system` namespace
6. Install `100.1.0+up19.0.3` to project `System` and wait for deployments & statefulsets to be ready
7. Upgrade to `100.1.2+up19.0.3`

**Result**
```
error updating the resource "rancher-monitoring-kubernetes-resources":
cannot patch "rancher-monitoring-kubernetes-resources" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "[https://rancher-monitoring-operator.cattle-monitoring-system.svc:443/admission-prometheusrules/validate?timeout=10s](https://rancher-monitoring-operator.cattle-monitoring-system.svc/admission-prometheusrules/validate?timeout=10s)": context deadline exceeded
```
`Error: UPGRADE FAILED: cannot patch "rancher-monitoring-kubernetes-resources" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "[https://rancher-monitoring-operator.cattle-monitoring-system.svc:443/admission-prometheusrules/validate?timeout=10s](https://rancher-monitoring-operator.cattle-monitoring-system.svc/admission-prometheusrules/validate?timeout=10s)": context deadline exceeded`

**Expected Result**

 Monitoring v2 `100.1.2-up19.0.3` to be successfully upgraded & deployed.

**Screenshots**

<img width="2533" alt="Screen Shot 2022-05-20 at 5 05 16 PM" src="https://user-images.githubusercontent.com/40526929/169610562-8e392e7a-22e2-49d6-b212-164315a77242.png">

**Additional context**

**Comment by MKlimuszka** [comment]
We need to put this into our backlog until upstream has a fix.

**Comment by MKlimuszka** [comment]
We have done many monitoring rebases since this ticket was last reproduced. Closing as stale. Reopen if seen again.
