### ISSUE TITLE
Neuvector chart installation fails on hardened clusters

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37799]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.23.6 , 1.3.20
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.23.6
- Cluster Type (Local/Downstream): `Local 3 worker +  etcd + cp RKE1`

**Describe the bug**
Currently we do not have support for neuvector hardened clusters from rancher and the chart installation fails with the error:
```
Pods "neuvector-controller-pod-6cd687c76-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]:Deployment does not have minimum availability.
```
**To Reproduce**

1. Create a  hardened cluster by following the hardening guide https://rancher.com/docs/rancher/v2.6/en/security/hardening-guides/1.6-hardening-2.6/
2. Install neuvector chart version `100.0.0+up2.2.0`

**Result**
Chart installation fails

**Expected Result**
Chart installation to go through.

**Comment by selvamt94** [comment]
@anupama2501 Neuvector controller and enforcer need certain permission to deploy and function. We can just enable psp on Neuvector chart to deploy on the hardened cluster. Can you try installing Neuvector with psp:true from the Rancher chart.

**Comment by anupama2501** [comment]
QA to validate:

```
Hardened cluster RKE - Calico
  all Neuvector components deployable if psp is set true (attached screen shot how to enable psp from Rancher Neuvector Chart)

Hardened cluster RKE2 - Calico and k3sContainerd
  Neuvector components Controller and Enforcer deployable if psp is set true
  For Manager and Scanner needs additional config change
  kubectl patch deploy neuvector-manager-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
  kubectl patch deploy neuvector-scanner-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'

Hardened cluster RKE2 + RHEL8.5+ SELinux enable - Canal and k3sContainerd
  Neuvector components Controller and Enforcer deployable if psp is set true
  For Manager and Scanner needs additional config change
  kubectl patch deploy neuvector-manager-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
  kubectl patch deploy neuvector-scanner-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
```

**Comment by anupama2501** [comment]
Verified on v2.6-head a8ae635

**Hardened custom RKE1 calico**  

1. Created a hardened RKE1 custom cluster by following the docs: https://rancher.com/docs/rancher/v2.6/en/cis-scans/
2. Once the cluster is active, from apps & market >> Neuvector >> from the container runtime to docker >> From edit as yaml, change psp to true
3. Installation goes through fine without errors
4. Launch neuVector webUI and verified dashboard loads without any error

**Hardened custom RKE2 canal**  
1. Created a hardened RKE1 custom cluster by following the docs: https://rancher.com/docs/rancher/v2.6/en/cis-scans/
2. Once the cluster is active, from apps & market >> Neuvector >> from the container runtime to docker >> From edit as yaml, change psp to true
3. Run the patch: 
```   
kubectl patch deploy neuvector-manager-pod -n cattle-neuvector-system --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}' 
 kubectl patch deploy neuvector-scanner-pod -n cattle-neuvector-system --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}' 
```
4. Installation goes through fine without errors
5. Launch neuVector webUI and verified dashboard loads without any error

**Hardened custom RKE2 canal SELinux enabled RHEL**
Same steps as above, verified installation goes through without any error.

**Hardened custom RKE2 calico SELinux enabled RHEL**
Same steps as above, verified installation goes through without any error.

**Comment by anupama2501** [comment]
Keeping this issue open as the to fix the above patch requirement.

**Comment by devmohammedothman** [comment]
you should enable the k3s instead of containerd in the helm values.yaml
```
k3s:
  enabled: true
  runtimePath: /run/k3s/containerd/containerd.sock
```

**Comment by anupama2501** [comment]
PR: https://github.com/rancher/charts/pull/2005

**Comment by selvamt94** [comment]
With new chart please do following for deploying on hardened cluster. These notes are added to chart app-readme.

For deploying on hardened RKE2 and K3s clusters, enable PSP and set user id from other configuration for Manager, Scanner and Updater deployments. User id can be any number other than 0.
For deploying on hardened RKE cluster, enable PSP from other configuration.

**Comment by anupama2501** [comment]
Verified on v2.6.7-rc6, neuvector version `100.0.1+up2.2.2`
1. As an admin, on a downstream cluster k8s version 1.24, install neuvector app version mentioned above
2. RKE1 hardened clusters While installing neuvector app in edit options navigate to Other configuration >> Enable the check box for Pod Security Policy and can leave the other fields empty.
3. RKE2/k3s hardened clusters: While installing neuvector app in edit options navigate to Other configuration >> Enable the check box for Pod Security Policy and for each option Manager runAsUser ID, Scanner runAsUser ID, Updater runAsUser ID` add a value greater than 0.
4. App deployment went through fine.
5. Launch NeuVector UI from the side navigation bar >> Accept the EULA and verify the dashboard loads fine without any errors
6. Repeated the same steps by adding a user as a cluster owner and launched NeuVector UI as CO and from the neuvector UI >> Settings >> Users & Roles >> Verified the cluster owner and admin are listed with Identity Provider as Rancher
7. Update the neuvector installation by changing the value of `runAsUser ID, Scanner runAsUser ID, Updater runAsUser ID` - Update goes through fine.
8. Uninstall the neuvector app and verified uninstall goes through fine without errors.

Downstream clusters verified on with the above steps:
RKE1 hardened - Pass
RKE2 hardened - Pass
RKE2 RHEL hardened - Pass
RKE1 SELinux enabled RHEL hardened - Pass
RKE2 SELinux enabled RHEL hardened - Pass
Local cluster with RKE1 hardened - Pass
