### ISSUE TITLE
Certificate: tls-rancher-internal is expiring, how to renew ?

### ISSUE THREAD

**Issue by H4Mm3r** [rancher/rancher#37796]
Hello,
Certificate: tls-rancher-internal is expiring in a few days, and I don't find the way to renew it.

Rancher cluster is RKE deployed.
rke version v1.3.11
Rancher version v2.5.9
Kubernetes version v1.20.9-rancher1

This solution is already tested, all commands OK but the cert is still expiring :
https://www.suse.com/c/rancher_blog/manual-rotation-of-certificates-in-rancher-kubernetes-clusters/

Any clue on wath to do ?

Thanks by advance.

**Comment by Rancheroo** [comment]
Restarting Rancher should trigger a renewal of this certificate
Run the below on the local cluster.
`kubectl rollout restart deployment rancher -n cattle-system`

**Comment by Rancheroo** [comment]
After checking in on things I have discovered some more information
The tls-rancher-internal certificate is used by Rancher to secure the https-internal port, on which Rancher listens on port 444. This is used to secure communications between the rancher replicas. The secret is created/updated by Rancher as required, and will be rotated by Rancher when needed, so this expiring certificate in the secret is no cause for concern.

**Comment by H4Mm3r** [comment]
Restarting don't fix the "problem".

The certificate has expired and everything seems to work, as you say, wait and see. Maybe it will be renewed at next Rancher upgrade.

Thanks for your answers.

**Comment by Rancheroo** [comment]
The certificate seems to renew in later versions of Rancher e.g 2.5.14
Please try upgrading to a later version as this is used to communicate web-socket processes between Rancher pods.
A workaround if you did encounter issues would be to scale Rancher replicas down to 1 until you could upgrade to a later release of 2.5.x
