### ISSUE TITLE
New warning: This chart is not compatible with Windows nodes

### ISSUE THREAD

**Issue by ktivdv** [rancher/rancher#37791]
I have an RKE2 cluster that I deployed and am managing with Rancher v.2.6.5. I just updated the RKE2 cluster to 1.23.6 last week, and now I see a warning on all my installed apps, and I cannot upgrade them - "This chart is not compatible with Windows nodes":
![Screenshot 2022-05-20 at 23 33 06](https://user-images.githubusercontent.com/19184901/169658477-ec1c527f-49ba-4648-8329-d19bcfc50472.png)

and here "Linux-only":
![Screenshot 2022-05-20 at 23 33 39](https://user-images.githubusercontent.com/19184901/169658517-fd272dea-d2e5-4763-b84a-5ba97afcf007.png)

Yet, I don't have any Windows nodes? I did add some at one point when I was testing out Rancher - several months ago - and promptly removed them when things did not go well. I hadn't even deployed any apps to the cluster yet before I removed those Win nodes. Everything was working fine before updating RKE2 to 1.23.6. Any ideas? This is rather worrisome as I can't upgrade, and I'm quite afraid to try redeploying anything. thanks!

**Comment by sgentzen** [comment]
I've been having the same issue since upgrading to 2.6.4.

**Comment by sgentzen** [comment]
> 

Looking more into this, my cluster manifest has this at the bottom:  "windowsWorkerCount: 1"

I haven't figured out how to change that though, as I definitely don't have any windows nodes running.

**Comment by niclas88** [comment]
Was this issue ever resolved? We have run into a similar issue with our RKE2 cluster v1.22.13+rke2r1. After adding a Windows worker node to the cluster we are unable to upgrade any "linux only" charts. We can still install "linux only" charts but we cannot perform the upgrade on them.
After removing the windows node from the cluster the problem still exists and Rancher is still reporting the the "chart is not compatible with Windows nodes".

![image](https://user-images.githubusercontent.com/10205535/206715374-1aef6d02-22d6-4ea9-94eb-eb04bd895ac8.png)
