### ISSUE TITLE
Active Directory setup fails if Default Domain is specified in Rancher 2.6

### ISSUE THREAD

**Issue by mshafiee** [rancher/rancher#37803]
Setting up Active Directory in Rancher in rancher/rancher:v2.6-head fails, if the field Default Domain is specified.

The Web UI displays the Error : "authentication failed"

If the Default Domain is left blank and instead MY-DOMAIN\username is used as the test user, the setup completes. This works but requires each user to login using MY-DOMAIN\username instead of username.

I tried setting Default Domain to the correct MY-DOMAIN and also tried with my-domain. I also tried with the DNS name my-domain.net, which changed the error message to "Unauthorized".

Log:

`rancher    | 2022/05/24 09:17:05 [ERROR] API error response 401 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C090439, comment: AcceptSecurityContext error, data 52e, v4563`

According to the ActiveDirectory docs LDAP error 49 with data 52e means wrong credentials.

We already have multiple internal and external services that successfully authenticate against the AD, most of them use libldap from OpenLDAP under the hood.

**Comment by jlvale** [comment]
I'm experiencing the same situation on Rancher v2.6.6 when trying do setup a Default Domain for the AD integration.

**Comment by TechXProd** [comment]
same problem here with rancher v2.6.6 : without default domain, it's working, with default domain = it failed.

**Comment by Martin-Weiss** [comment]
Just did such a configuration last week and it worked well. Could it be that in your case you have a difference between NetBIOS and AD domain name? In case yes - could you try with the NetBIOS domain name as default domain?
(In this case only the short name of the user needs to be used for service account and for test user)

P.S. testing the login with ldapsearch using the same credentials might also help to see where the problem might be coming from.

**Comment by moshiaiz** [comment]
Thanks @Martin-Weiss 
When configuring NetBIOS domain name and changing bind user and test user to their short names - it works! 🙂
