### ISSUE TITLE
After I authenticate for the first time, I lose all my preferences

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3780]
Version - master 3/4

Steps to Reproduce: 
1.  Create new rancher
2.  Change it to dark theme
3.  Authenticate (log in then log out)

Results: I'm now in light theme.  Because preferences are not moved over to new account

Expected: Should not lose my preferences

Comment:  This is because we create a new account when we authenticate, so preferences are associated to the original admin account.

**Comment by vincent99** [comment]
As discussed we should revert the behavior where turning on auth creates a new account and let it convert the admin account that was being used while auth is off.

**Comment by deniseschannon** [comment]
Can you see if this is fixed? The PRs look merged.

**Comment by tfiduccia** [comment]
Version - master 3/20
Verified fixed
