### ISSUE TITLE
KEv2 unit/integration tests

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#37818]
This ticket is a placeholder for KEv2 testing:

**Comment by annablender** [comment]
Finishing GKE unit tests is blocked by a provisioning issue where the default vpn network does not exist in the new GCP configuration. Need assistance

**Comment by annablender** [comment]
Feedback from SUSE IT is for a GCP project group member to create the default VPC. Will work on that using https://cloud.google.com/vpc/docs/create-modify-vpc-networks

**Comment by annablender** [comment]
If rancher throws an error that _default network does not exist_, follow_ [the docs](https://cloud.google.com/vpc/docs/create-modify-vpc-networks#create-auto-network) to create an auto mode VPC network named `default.` Auto created subnets generated for each region will work for this case. Try reprovisioning the GKE cluster. Thank you also to @cmurphy for her advice here

**Comment by Sahota1225** [comment]
Closing this issue as there is no validation for QA.
