### ISSUE TITLE
Passwords are stored in plain text in MySQL

### ISSUE THREAD

**Issue by remkade** [rancher/rancher#3782]
Rancher Version: 0.59.1

Docker Version: ALL

OS: ALL

Steps to Reproduce:  When using local authentication, in mysql run: "select * from credential;"

Results: Usernames and Passwords are visible in plain text in the database

Expected: Passwords should be hashed or otherwise encrypted.

**Comment by remkade** [comment]
These are Docker Hub or Registry credentials I should clarify.

**Comment by alena1108** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/3180 - refer to that ticket for progress tracking
