### ISSUE TITLE
Not able to use dig to resolve service names from contaniners deployed in host network.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3783]
Rancher Version: Build from master

Docker Version:1.10.2

OS: Ubuntu 14.04 hosts

Steps to Reproduce: 
1. Create 2 services in host network and them as target to Service Alias.
2. Create service1 with managed network.
3. Create service2 with host network and label - "io.rancher.container.dns": "true"

From containers within service2 , try to use dig on servicename that is in managed network created in step 2. dig does not return ip address of instance in the service.
   
From containers within service2 , try to use dig on service alias name that services containers in host network created in step 1. dig does not return ip address of instance in the service.

Note - In both the above access , ping <servicename> works . Only dig is not able to resolve servicename.

**Comment by vincent99** [comment]
`dig` does not use the search list in /etc/resolv.conf by default.

`dig servicename +search`

**Comment by sangeethah** [comment]
@vincent99 , until the previous release - v0.59.1 , we were able to use dig to resolve service names from contaniners deployed in host network without using +search option. Has something changed in this release for this to break ? I had a similar issue logged for containers on managed network which was addressed - #3694 . 
If this is the expected behavior , I can change validation tests to use +search option for DNS validation .

**Comment by alena1108** [comment]
The issue is fixed with https://github.com/rancher/rancher-dns/pull/16. The problem was - default section used as a client section for host level containers, and domain search set on "default",wasn't used.

**Comment by sangeethah** [comment]
Tested with latest build from master.
Able to use dig to resolve service names from contaniers deployed in host network.
