### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s May patch release

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#37840]
# KDM Updates

TO BE RELEASED: Rancher OOB v2.6

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version | Default Version |
|                  :---:                  |              :---:               |               :---:               |          :---:          |
| v1.21.13+rke2r2                 | v2.6.3-alpha1             | v2.6.4 |                           |
| v1.22.10+rke2r2                  | v2.6.3-alpha1             |  | x                        |
| v1.23.7+rke2r2                  | v2.6.4-alpha1             |  |                         |
| v1.21.13+k3s1                   | v2.6.3-alpha1             | v2.6.4 |                           |
| v1.22.10+k3s1                    | v2.6.3-alpha1             |  | x                        |
| v1.23.7+k3s1                    | v2.6.4-alpha1             |   |                          |

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |
| rke2-cilium | 1.11.501 | v1.21.13+rke2r2, v1.22.10+rke2r2, v1.23.7+rke2r2 |
| rancher-vsphere-cpi | 1.2.201 | v1.21.13+rke2r2, v1.22.10+rke2r2, v1.23.7+rke2r2 |
| rke2-canal | v3.22.2-build2022050902 | v1.22.10+rke2r2, v1.23.7+rke2r2 |
| rke2-calico | v3.21.504 | v1.22.10+rke2r2 |
| rke2-calico-crd | v3.21.504 | v1.22.10+rke2r2 |
| rke2-calico | v3.23.103 | v1.23.7+rke2r2 |
| rke2-calico-crd | v3.23.103 | v1.23.7+rke2r2 |
| rke2-multus | v3.8-build2021110402 | v1.22.10+rke2r2, v1.23.7+rke2r2 |
| rke2-ingress-nginx | 4.1.003 | v1.21.13+rke2r2, v1.22.10+rke2r2, v1.23.7+rke2r2 |

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |
| egress-selector-mode | v1.22.10+rke2r2, v1.23.7+rke2r2, v1.22.10+k3s1, v1.23.7+k3s1 |

**Comment by rancher-max** [comment]
RKE2 PR: https://github.com/rancher/kontainer-driver-metadata/pull/907

**Comment by rancher-max** [comment]
K3s PR: https://github.com/rancher/kontainer-driver-metadata/pull/908

**Comment by slickwarren** [comment]
tested the following on v2.6.4:
* 1.21.12+rke2r2 -> 1.21.13-rc1+rke2r1
* 1.22.9+rke2r2 -> 1.22.10-rc1+rke2r1
* 1.23.6+rke2r2 -> 1.23.7-rc1+rke1r1
* 1.22.9+rke2r2 with cloud provider enabled -> 1.23.7+rke2r1 
  * new pv are created successfully
* 1.21.13-rc1+rke2r1 -> 1.23.7-rc1+rke1r1
* 1.22.10-rc1+rke2r1 -> 1.23.7-rc1+rke1r1

**Comment by rancher-max** [comment]
Validated egress-selector-mode is available to be used with Edit as YAML in all 4 affected versions, and it shows up in the config correctly as well on the nodes.

**Comment by rancher-max** [comment]
This has been fully validated using RC versions of the releases. Leaving this open since we will have changes still to come potentially before releasing.

**Comment by cwayne18** [comment]
@rancher-max can we close this on our end?

**Comment by rancher-max** [comment]
Not yet. We have a slack thread currently going internally where it looks like there was an issue with system-agent-installer-k3s images. A new issue was created: https://github.com/rancher/system-agent-installer-k3s/issues/6 but we still need the current tags to be rerun/retagged otherwise we will not be able to provision a cluster through rancher.

**Comment by rancher-max** [comment]
This has now been fully validated and additionally confirmed with the actual (non-rc) versions of the releases.
