### ISSUE TITLE
[RFE] Enable Azure accelerated networking in node templates

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#37847]
Production clusters need accelerated network configuration and could not be deployed with the current templates.

Request description:
Node templates should have the option to create VMs in Azure public cloud with accelerated networking enabled.

Here's a Microsoft post about this feature: https://azure.microsoft.com/fr-fr/blog/maximize-your-vm-s-performance-with-accelerated-networking-now-generally-available-for-both-windows-and-linux/
 

Actual behavior:
It's not an option

Expected behavior:
Should be one

Additional notes:

Notes that may help with implementation

Example of its usage in the Azure API documentation: https://docs.microsoft.com/en-us/rest/api/virtualnetwork/network-interfaces/create-or-update

Docker machine 0.9.0 may have AzureGermanCloud support as stated here : https://github.com/docker/machine/releases/v0.9.0

This pull request: https://github.com/docker/machine/pull/3835 seems to allow to use the AcceleratedNetworkingEnabled boolean in this file: https://github.com/docker/machine/blob/master/vendor/github.com/Azure/azure-sdk-for-go/arm/network/models.go#L1323

What I understool is that : c.CreateNetworkInterface in https://github.com/rancher/machine/blob/master/drivers/azure/azure.go calls: func (a AzureClient) CreateNetworkInterface in https://github.com/docker/machine/blob/master/drivers/azure/azureutil/azureutil.go that calls : type InterfacePropertiesFormat struct { ... AcceleratedNetworkingEnabled *bool `json:"acceleratedNetworkingEnabled,omitempty"` in : https://github.com/docker/machine/blob/master/vendor/github.com/Azure/azure-sdk-for-go/arm/network/models.go#L1323

SURE-3197

**Comment by HarrisonWAffel** [comment]
@gaktive This ticket is currently blocked by the respective UI work. rancher-machine has been updated so the required API schema changes should be present, resolving previous UI blockers.

**Comment by thaneunsoo** [comment]
The test plan can be viewed [here](https://confluence.suse.com/pages/viewpage.action?pageId=1141178915)

**Comment by thaneunsoo** [comment]
Azure accelerated networking configuration has been added successfully.
Test results can be found [here](https://confluence.suse.com/pages/viewpage.action?pageId=1141178915)

Here are the results for UI:

RKE1:
https://github.com/rancher/dashboard/issues/7752

RKE2/K3s:
https://github.com/rancher/dashboard/issues/7182
