### ISSUE TITLE
Services not accessible with Ingress

### ISSUE THREAD

**Issue by marcoroganovic** [rancher/rancher#37850]
Hi,

Not sure if it is a bug, but I have asked before on Slack group, no one replied, so I figured out I might ask here.
I have spent a lot of time researching, but no results so far, so maybe someone here can help... thanks.

**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: v1.23.6
- Cluster Type (Local/Downstream): imported

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
So I have started fresh RKE cluster, connected private registry, deployed few deployments, but I can't access Cluster IP services with nginx ingress, the only way I can reach to workloads is if I expose them via NodePort.

**To Reproduce**
I have just created service through the UI.

**Result**
```json
{
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "error trying to reach service: dial tcp 10.42.3.111:80: i/o timeout",
"reason": "ServiceUnavailable",
"code": 503
}
```

**Expected Result**
To properly expose services to ingress.

**Comment by maojiawei** [comment]
we have the same problem,do you resolve it?
