### ISSUE TITLE
Private hosted AKS cluster status indefinitely switches from `Active` to `Unavailable` after successful cluster provisioning

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#37855]
**Rancher Server Setup**
- Rancher version: `v2.6-head`
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.23.5`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AKS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard
  - If custom, define the set of permissions:

**Describe the bug**

When creating a private AKS cluster within Rancher, I am able to successfully provision following the steps in issue https://github.com/rancher/rancher/issues/37164#issuecomment-1139161978. However, as mentioned in that same comment, there is a flickering of the cluster's status between `Active` and `Unavailable`.

Looking in the backend, each time this flickering happens, the `aks-command` namespace repetitively performs the following actions:
- Creates a new pod until it reaches `Running` state
- Once that pod reaches `Running` state, Rancher shows the cluster as `Active`
- Immediately after, the pod terminates and a new `aks-command` namespace is spun up along with a new corresponding pod`. This repeats over and over again, explaining the unstable cluster status in Rancher

Additionally, there may be some issue with regards to how controllers are being handled in this Rancher setup. That will need further investigation.

**To Reproduce**
 
1. In a local client machine, ensure that you have downloaded the az cli and have logged into your Azure subscription.
2. Setup Rancher and navigate to the Rancher UI.
3. Create a standard user and login to Rancher as that user.
4. Create a 3 node, private AKS cluster via Rancher. Be sure to set the following:
     - Check off Enable Private Cluster in Networking Options.
     - In Cluster Options, add tags that match your Kubernetes service. If you know them beforehand, you can do it before you create it. If not, you will need to come back to this step and add the tags.
5. Navigate back to your Linode client machine and run the following command once the cluster is created: `az aks command invoke --resource-group <resource group> --name <cluster name> --command "<registration command"`.
6. You should see the following:
![test](https://user-images.githubusercontent.com/52591819/170603014-0bf5bed8-734b-42cf-be19-d0d34afa72c1.gif)

**Result**
AKS private cluster status flickers indefinitely between `Active` and `Unavailable`.

**Expected Result**

AKS private cluster status should stay on `Active`.

**Comment by jiaqiluo** [comment]
This issue might be fixed as part of https://github.com/rancher/rancher/issues/37608

can you try it again with the latest 2.6-head?

**Comment by markusewalker** [comment]
Still reproducing this issue on `v2.6-head` https://github.com/rancher/rancher/commit/79a3bcba901add6249cfbb6d9d4961599553f8da following my reproduction steps described in the issue description.

Perhaps this commit I used is outdated? Either way, I can try again early next week, but I am still seeing this issue.

**Comment by annablender** [comment]
I think this is due to the `aks-operator` latest chart version 1.0.6-rc2 failing to deploy on `2.6-head.` I'm looking into this today with Kinara and Arvind.

**Comment by markusewalker** [comment]
Still reproducing this issue on `v2.6-head` https://github.com/rancher/rancher/commit/0fd630dd1328233958bdef6b9f7f413eb7463005.

**ENVIRONMENT**
- Rancher HA
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/0fd630dd1328233958bdef6b9f7f413eb7463005
- AKS version: `v1.23.5`
- Browser: Chrome

**TEST RESULT**
FAIL

**REPRODUCED STEPS**
1. In a local client machine, ensured that I downloaded the `az` cli and have logged into my Azure subscription.
2. Setup Rancher and navigated to the Rancher UI.
3. As my default admin user, created a hosted AKS cluster.
     - Created a 3 node, private AKS cluster via Rancher. Be sure to set the following:
     - Checked `Enable Private Cluster` in Networking Options.
4. Navigated back to my client machine and run the following command once the cluster is created: az aks command invoke --resource-group <resource group> --name <cluster name> --command "<registration command".
6. I see see the following:
![Jun-16-2022 08-46-04](https://user-images.githubusercontent.com/52591819/174111951-7847452e-8b38-4e14-8225-90b310bd8172.gif)
7. Verified that my `aks-operator` is updated to the latest version:
![image](https://user-images.githubusercontent.com/52591819/174112154-d6cbd93a-4286-4560-96c3-480c29723056.png)
