### ISSUE TITLE
Is there a temporary solution to this problem if the log does not show it?

### ISSUE THREAD

**Issue by AbelHugh** [rancher/rancher#37857]
- Rancher version: v2.6.5
- Installation option (Docker install/Helm Chart): docker

- Kubernetes version: 1.23.6

I know this bug will be fixed in the next version, but is there any temporary way to make the log show up? Because once it becomes like this, the button in the lower right corner is gone.

![image](https://user-images.githubusercontent.com/71317399/170815869-950d1dc1-2d8e-4725-86a3-aa92aeef343b.png)

**Comment by AbelTaylor** [comment]
please help move to rancher/dashboard.....

**Comment by AbelTaylor** [comment]
@Catherine Luse
I did the following according to the prompts but it didn't work

![image](https://user-images.githubusercontent.com/71317399/170816365-ed1fe981-df11-4e4a-b7f8-c54e59693799.png)
![image](https://user-images.githubusercontent.com/71317399/170816375-ca9f41f1-d8fe-4735-8606-205f2dad6e7a.png)

**Comment by matteogazzadi** [comment]
Same problem here after upgrading to 2.6.5
