### ISSUE TITLE
DNS resolution fails for containers linked to services. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3786]
Rancher Version: Build from master

Docker Version:1.10.2

OS: Ubuntu 14.04 hosts

Steps to Reproduce: 

Create a container C1.

Create a service and link to this container by passing following parameter to launch_config.
 "instanceLinks": {
                         link_name:
                             link_container.id}, 

Once the service is up , from within the  service container , try to ping the linked container by link name.

Not able to ping container.

**Comment by alena1108** [comment]
@sangeethah same root cause as in https://github.com/rancher/rancher/issues/3787. Will leave both bugs open so you can verify them separately.

**Comment by sangeethah** [comment]
Tested with latest build from master , able to resolve containers linked to services by link name as long as the link name is in lower case. When link names are in upper case , DNS resolution fails which is tracked in #3787
