### ISSUE TITLE
cattle-cluster-agent crashes

### ISSUE THREAD

**Issue by DemyanSafronov** [rancher/rancher#37866]
**_Rancher `v2.5.7` UI: `v2.5.6`_**
Hi! How can I find the reason of a panic error? I can see it in a cattle-cluster-agent logs. 
Also I see "HTTP Error 500: from /k8s/clusters/c-wdww4/v1/schemas" if I open the Cluster Explorer (the Cluster Manager is working).
Please find some information from the log below:

E0517 09:30:39.768202       1 runtime.go:78] Observed a panic: runtime.boundsError{x:3, y:0, signed:true, code:0x2} (runtime error: slice bounds out of range [:3] with capacity 0)
goroutine 1070 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x42eb3c0, 0xc0083a1500)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/runtime/runtime.go:74 +0x92
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x42eb3c0, 0xc0083a1500)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/catalogv2/helm.decodeHelm3(0x0, 0x0, 0x7f8f1bc98958, 0xc0027d1c48, 0x1)
	/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/helm3.go:124 +0x2c9
github.com/rancher/rancher/pkg/catalogv2/helm.fromHelm3Data(0x0, 0x0, 0xc001da9a78, 0x5, 0xc0027d1cc8, 0x0)
	/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/helm3.go:23 +0x39
github.com/rancher/rancher/pkg/catalogv2/helm.ToRelease(0x4fef420, 0xc002df2340, 0xc001da9a78, 0x1, 0x4fb6520, 0xc0004d6bf0)
	/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/release.go:74 +0x426
github.com/rancher/rancher/pkg/controllers/dashboard/helm.(*appHandler).OnSecretChange(0xc00229f3b0, 0xc001fbacd0, 0x4d, 0xc002df2340, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/apps.go:165 +0xa6
github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromSecretHandlerToHandler.func1(0xc001fbacd0, 0x4d, 0x4fef420, 0xc002df2340, 0xc00148ab70, 0xc00148ab01, 0xc00148ab70, 0xc001da9be0)
	/go/pkg/mod/github.com/rancher/wrangler@v0.7.3-0.20201028210318-d73835950c29/pkg/generated/controllers/core/v1/secret.go:102 +0x65
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0014b6d40, 0xc001fbacd0, 0x4d, 0x4fef420, 0xc002df2340, 0x4035e3, 0x5a000000004097db, 0xc00004c000, 0x41258e0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc0011ca900, 0xc001fbacd0, 0x4d, 0x4fef420, 0xc002df2340, 0xc0018d5201, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00230f290, 0xc001fbacd0, 0x4d, 0xc001a6b740, 0xc001da9d50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00230f290, 0x3a39ce0, 0xc00148abf0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00230f290, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc00230f290)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001327c80)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001327c80, 0x4fbc100, 0xc001a6b980, 0x1, 0xc001cb7020)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001327c80, 0x3b9aca00, 0x0, 0x1, 0xc001cb7020)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc001327c80, 0x3b9aca00, 0xc001cb7020)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
panic: runtime error: slice bounds out of range [:3] with capacity 0 [recovered]
	panic: runtime error: slice bounds out of range [:3] with capacity 0
goroutine 1070 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x42eb3c0, 0xc0083a1500)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/catalogv2/helm.decodeHelm3(0x0, 0x0, 0x7f8f1bc98958, 0xc0027d1c48, 0x1)
	/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/helm3.go:124 +0x2c9
github.com/rancher/rancher/pkg/catalogv2/helm.fromHelm3Data(0x0, 0x0, 0xc001da9a78, 0x5, 0xc0027d1cc8, 0x0)
	/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/helm3.go:23 +0x39
github.com/rancher/rancher/pkg/catalogv2/helm.ToRelease(0x4fef420, 0xc002df2340, 0xc001da9a78, 0x1, 0x4fb6520, 0xc0004d6bf0)
	/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/release.go:74 +0x426
github.com/rancher/rancher/pkg/controllers/dashboard/helm.(*appHandler).OnSecretChange(0xc00229f3b0, 0xc001fbacd0, 0x4d, 0xc002df2340, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/apps.go:165 +0xa6
github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromSecretHandlerToHandler.func1(0xc001fbacd0, 0x4d, 0x4fef420, 0xc002df2340, 0xc00148ab70, 0xc00148ab01, 0xc00148ab70, 0xc001da9be0)
	/go/pkg/mod/github.com/rancher/wrangler@v0.7.3-0.20201028210318-d73835950c29/pkg/generated/controllers/core/v1/secret.go:102 +0x65
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0014b6d40, 0xc001fbacd0, 0x4d, 0x4fef420, 0xc002df2340, 0x4035e3, 0x5a000000004097db, 0xc00004c000, 0x41258e0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc0011ca900, 0xc001fbacd0, 0x4d, 0x4fef420, 0xc002df2340, 0xc0018d5201, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00230f290, 0xc001fbacd0, 0x4d, 0xc001a6b740, 0xc001da9d50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00230f290, 0x3a39ce0, 0xc00148abf0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00230f290, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc00230f290)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001327c80)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001327c80, 0x4fbc100, 0xc001a6b980, 0x1, 0xc001cb7020)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001327c80, 0x3b9aca00, 0x0, 0x1, 0xc001cb7020)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc001327c80, 0x3b9aca00, 0xc001cb7020)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f

---

Thank you!

**Comment by niusmallnan** [comment]
try this workaround: https://github.com/rancher/rancher/issues/35971
