### ISSUE TITLE
Support CAS providers

### ISSUE THREAD

**Issue by letian0805** [rancher/rancher#37860]
CAS Server: 
https://www.apereo.org/projects/cas
https://github.com/casdoor/casdoor

Go client: 
https://github.com/go-cas/cas

**Comment by forrancher** [comment]
请问您在做rancher与cas集成么？我刚好遇到这方面的问题，可以请教一下么？

**Comment by letian0805** [comment]
> 请问您在做rancher与cas集成么？我刚好遇到这方面的问题，可以请教一下么？

有这个想法，但一直没什么时间来搞这个。

**Comment by hsluoyz** [comment]
Hi @forrancher @letian0805 does Rancher have a web portal to integrate with Casdoor? Does Rancher support OAuth, OIDC, SAML, etc?
