### ISSUE TITLE
Container links are not functional.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3787]
Rancher Version: Build from master

Docker Version:1.10.2

OS: Ubuntu 14.04 hosts

Steps to Reproduce: 
1. Create a container C1.
2. Create a container C2 and link it to C1 with a link name.

From within the container C2 , try to ping C1 using the link name.

Not able to ping C1 using link name.

**Comment by sangeethah** [comment]
@alena1108 , with the latest build from master , I am still able to reproduce this issue .

**Comment by alena1108** [comment]
@vincent99 looks like the resolution is broken when link name is upper case. For example, with config like this neither "foo1" nor "FOO1" can be resolved:

```
{
	"default": {
		"search": [],
		"recurse": ["8.8.8.8"],
		"a": {
			"rancher-metadata.rancher.internal.": {
				"answer": ["169.254.169.250"]
			}
		},
		"cname": {}
	},
	"10.42.237.159": {
		"search": ["rancher.internal"],
		"recurse": ["8.8.8.8"],
		"a": {
			"FOO1.": {
				"answer": ["10.42.43.44"]
			}
		},
		"cname": {}
	}
}
```

**Comment by vincent99** [comment]
@alena1108 The answers file should be all lowercase.  DNS isn't case-sensitive, but checking the answers map to see if a key exists is.

**Comment by sangeethah** [comment]
@alena1108 @vincent99 , with the latest build form master , container links are functional when link name is in lowercase .

links are not working when link names are in uppercase. This is broken for container links as well as service links.

**Comment by sangeethah** [comment]
@alena1108 , I am able to reproduce this issue with the latest build from master.

When container link name are in upper case , they get programmed in answers.json in upper case as well.

**Comment by sangeethah** [comment]
Tested with rancher-server version  - V0.63.0-rc2

Steps to Reproduce: 
1. Create a container C1.
2. Create a container C2 and link it to C1 with a link name having uppercase - "HELLO".

From within the container C2 , try to ping C1 using the link name.

Able to ping C1 using link name.
