### ISSUE TITLE
Failing to update private CA chain, even though the secrets for new CA and CRT+KEY have replaced the old ones

### ISSUE THREAD

**Issue by nikitamaximov** [rancher/rancher#37871]
**Rancher Server Setup**
- Rancher version: 2.6.1
- Installation option (Docker install/Helm Chart): Helm Chart
   - RKE1, 1.21.5

**Information about the Cluster**
- Kubernetes version: 1.21.5
- Cluster Type (Local/Downstream): Custom Downstream
   - v1.21.5-rancher1-1
   - Deployed HA Kubernetes with RKE

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:

   
**Describe the bug**
Hello, I was following this guide to update the private CA certs for rancher
https://rancher.com/docs/rancher/v2.6/en/installation/resources/update-ca-cert/
However the https://<Rancher_SERVER>/v3/settings/cacerts is still showing the old CA

Our first revision already used private CA (privateCA=true), but the client created new certs and signed them with new CA hence we need to update them.

Step 1 is to update crt and key (tls-rancher-ingress) secret. The supplied command for update worked fine, checked with kubectl -n cattle system get secret tls-rancher-ingress

Step 2 is to update CA (tls-ca) secret. The supplied command for update worked fine, checked with kubectl -n cattle system get secret tls-ca

Step 3 Helm shows status "Deployed" with description "Upgrade Complete"
```
helm upgrade rancher rancher-stable/rancher \
  --namespace cattle-system \
  --version 2.6.1 \
  --set hostname=***** \
  --set ingress.tls.source=secret \
  --set privateCA=true
```
However when I check https://<Rancher_SERVER>/v3/settings/cacerts or https://<Rancher_SERVER>/cacerts they still contain the old CA chain. Nothing errored, rancher containers haven't restarted after helm upgrade, the cluster is still accesible.

Checking the crt of the rancher server with openssl prints the new crt, with the issuer as new CA
```
curl --insecure -v https://<Rancher_SERVER> 2>&1 | awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'
```

Step 4 Reconfigure Rancher agents to trust the private CA. I haven't run this step yet since the CA hasn't updated in https://<Rancher_SERVER>/v3/settings/cacerts 

Any idea what am I missing?

**To Reproduce**
Spin up a rancher cluster with private CA and certs, update the private CA to a different one and update the cert signed by the new CA.

**Result**
https://<Rancher_SERVER>/v3/settings/cacerts or https://<Rancher_SERVER>/cacerts still showing the old CA chain

**Expected Result**
https://<Rancher_SERVER>/v3/settings/cacerts or https://<Rancher_SERVER>/cacerts to show the new CA chain

**Screenshots**

**Comment by PaulRitzkat0110** [comment]
Try helm upgrade --force, that worked for me
