### ISSUE TITLE
Running `kubectl delete -f <registration command>` on an imported cluster results in an indefinite hang for the `cattle-cluster-agent` service

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#37874]
**Rancher Server Setup**
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/68c6c1377b6d1dec9846193fd093a3b6bba8476e
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.23.6`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard
  - If custom, define the set of permissions:

   
**Describe the bug**

Upon importing an RKE1 cluster into Rancher, I attempted to run `kubectl delete -f <registration command`. Upon doing that, my Rancher UI is stuck in the following:

![image](https://user-images.githubusercontent.com/52591819/171284561-07c608cb-62b7-46ea-87be-6fefca5eff12.png)

Looking over at my client machine where I ran the `kubectl delete...` command, I get stuck at the following point:

```
kubectl delete -f https://<rancher URL>/v3/import/z74tptqfx2gcnm5zvbjbmtrqmlsvrj4vplzmlhcb2jf6pjmgsrzq79_c-m-mwdsr98d.yaml
clusterrole.rbac.authorization.k8s.io "proxy-clusterrole-kubeapiserver" deleted
clusterrolebinding.rbac.authorization.k8s.io "proxy-role-binding-kubernetes-master" deleted
namespace "cattle-system" deleted
serviceaccount "cattle" deleted
clusterrolebinding.rbac.authorization.k8s.io "cattle-admin-binding" deleted
secret "cattle-credentials-57e8c92" deleted
clusterrole.rbac.authorization.k8s.io "cattle-admin" deleted
deployment.apps "cattle-cluster-agent" deleted
service "cattle-cluster-agent" deleted
```

The workaround is to manually kill this command with ctrl + c and to forcibly remove the `cattle-system` namespace as it is stuck in a state of `Terminating`. This isn't a good workaround for users because having to forcibly interject in cluster operations defeats the point of it being imported into Rancher to begin with.

**To Reproduce**
 
1. In a client machine, setup an RKE1 cluster (technically, this should work with K3s or RKE2, but I did RKE1).
2. Setup Rancher and navigate to Rancher in a browser.
3. Create standard user and login to Rancher as that user.
4. Import the cluster you provisioned from step 1. Save the registration command that you use to import the cluster.
5. Once it is successfully imported, navigate to your client machine and run command: `kubectl delete -f <registration command>`. You should see this issue.

**Result**
Deleting the `cattle-cluster-agent` service is permanently stuck due to the `cattle-system` namespace being stuck in a state of `Terminating`.

**Expected Result**

After running `kubectl delete -f <registration command>`. all resources and manifests originally placed on my cluster from the registration command should be removed without failure or getting stuck.

**Comment by jiaqiluo** [comment]
We do not believe that using` kubectl delete -f` against the registration manifest is a supported way of cleaning up the imported cluster, and in fact, we have a cleanup script mentioned in Rancher Docs: 

https://rancher.com/docs/rancher/v2.5/en/cluster-admin/cleaning-cluster-nodes/#
https://rancher.com/docs/rancher/v2.5/en/faq/removing-rancher/#what-if-i-don-t-want-my-registered-cluster-managed-by-rancher
@markusewalker  Could you clarify the scenario you want to test here?

**Comment by markusewalker** [comment]
@jiaqiluo thanks for the documentation and clarifying the supported method is to use the cleanup script mentioned in the Rancher docs. The scenario I was testing here is from a user's perspective if they wish to simply undo the registration command via `kubectl` as opposed to going through the aforementioned steps in official documentation.

However, it seems that we are noting that this is an unsupported method of cleaning up an imported cluster. As such, I'll go ahead and close this issue as we official solutions that we highlight in our documentation.
