### ISSUE TITLE
csp adapter uninstall not fully cleaned up 

### ISSUE THREAD

**Issue by brudnak** [rancher/rancher#37888]
### Rancher Server Setup

| Component           | Version / Type                                     |
| ------------------- | -------------------------------------------------- |
| Rancher version     | v2.6-4d3c25a225499eee9acb74d47bfd2665389d093f-head |
| Installation option | EKS                                                |
| Helm version        | v2.16.8-rancher1                                   |
| Cluster type        | local / hosted EKS                                 |
| K8s version         | v1.21.9-eks-14c7a48                                |
| Logged in user role | Administrator                                      |
| Browser type        | Google Chrome                                      |
| Browser version     | 102.0.5005.61 (Official Build) (x86_64)            |

#### Describe the bug
When the csp adapter is uninstalled, not all of the resources under the `cattle-csp-adapter-system` namespace are deleted. This makes it so you can still download the support config because it relies on the `csp-config` config map even after the csp adapter is uninstalled.

#### To Reproduce

1. Start with the csp adapter installed and setup
2. Uninstall the csp adapter
    1. Starting from the **default** Rancher homepage `/dashboard/home`
    2. Click the `hamburger` menu -> `local` cluster -> `Apps` -> `Installed Apps` -> filter namespace to `cattle-csp-adapter-system`
    3. Click the `ellipsis (three dots)` next to the `rancher-csp-adapter` app -> click `Delete` -> at the "Are you sure?" prompt, click `Delete` -> watch the the success helm uninstall message to appear in the pop-up console window 
3. Try downloading the support config now that the csp adapter is uninstalled, go to the endpoint `/v1/generateSUSERancherSupportConfig`. This will still download the `supportconfig.tar` file with the `config.json` inside still showing whatever the last status was before the csp adapter was uninstalled.
4. In the local cluster check for resources under the `cattle-csp-adapter-system` namespace.
   1. Click the `hamburger` menu -> `local` cluster -> `Storage` -> with the namespace filter set to `cattle-csp-adapter-system`
   2. There are four remaining resources under the namespace
   - Two under ConfigMaps
     - `csp-config`
     - `kube-root-ca.crt`
   - Two under Secrets
     - `csp-adapter-cache`
     - `default-token-${random-string}`

#### Result
There are config maps and secrets left behind after the csp adapter is uninstalled. This allows you to still download a support config even after the csp adapter is uninstalled.

#### Expected Result
For all of the resources under the `catl-csp-adapter-system` namespace to be cleaned up once the csp adapter in uninstalled.

**Comment by MbolotSuse** [comment]
Not sure that I would consider this a bug. This was something that I considered early on, but Rancher doesn't clean up all of it's resources when it is uninstalled either. Let's talk about it and see if this is something that we want to change.

**Comment by MbolotSuse** [comment]
Just talked about this with @cbron. The preferred solution here is going to be to document the steps to uninstall.

This method was chosen for the following reasons:
1) We can't just leave as is. Users may want to stop using the license manager service, so we need to have something helping users uninstall.
2) Post delete jobs don't work if you do a `helm template | k apply `(i.e. if you template the chart and then apply the artifacts created by the chart). So we are going to have to document uninstall steps anyway.

Going to close this issue and modify the docs issue to include uninstall steps. For now, you can use the following to uninstall this and any artifacts:

```
helm uninstall rancher-csp-adapter -n cattle-csp-adapter-system
kubectl delete ns cattle-csp-adapter-system
kubectl delete RancherUserNotification csp-compliance
```
Note that the last step may fail with a `resource not found`. That's ok - the resource is only there if you were in a failure state, and this command is only included for the sake of being complete.
