### ISSUE TITLE
Upgrade to 2.6.5 breaks default admin cluster role , with okta integration

### ISSUE THREAD

**Issue by Hitesh-Agrawal** [rancher/rancher#37894]
**Rancher Server Setup**
- Rancher version: v2.6.4 -> (upgrade to ) v2.6.5
- Installation option (Docker install/Helm Chart):
   - Using terraform rke provider version v1.3.0
   
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/rancher/rancher2 v1.22.2
+ provider registry.terraform.io/rancher/rke v1.3.0

**Information about the Cluster**
- Kubernetes version: 1.22.4
- Cluster Type (Local/Downstream): Local and Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin)

   
**Describe the bug**

We recently upgraded our rancher from v2.6.4 to v2.6.5 . After the upgrade we are no longer able to run plan against our downstream cluster. Our cluster is integrated with okta authentication.
The issue is similar to what is mentioned in https://github.com/rancher/rancher/issues/36096

**To Reproduce**
 
Upgrade your cluster from rancher v2.6.4 to v2.6.5 
**Result**
The Default Admin Cluster role should have following rules to update the downstream cluster.
`kubectl get clusterrole cattle-impersonation-user-REDACTED -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-02-07T16:50:18Z"
  labels:
    authz.cluster.cattle.io/impersonator: "true"
    cattle.io/creator: norman
  name: cattle-impersonation-user-REDACTED
  resourceVersion: "419324355"
  uid: REDACTED
rules:
- apiGroups:
  - ""
  resourceNames:
  - user-REDACTED
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - okta_group:/REDACTED
  - system:authenticated
  - system:cattle:authenticated
  resources:
  - groups
  verbs:
  - impersonate
- apiGroups:
- authentication.k8s.io
resourceNames:
- local://user-REDACTED
resources:
- userextras/principalid
verbs:
- impersonate
- apiGroups:
- authentication.k8s.io
resourceNames:
- Default Admin
resources:
- userextras/username
verbs:
- impersonate`

We get following errors when terraform plan is run
 Error: userextras.authentication.k8s.io "Default Admin" is forbidden: User "system:serviceaccount:cattle-impersonation-system:cattle-impersonation-user-REDACTED" cannot impersonate resource "userextras/username" in API group "authentication.k8s.io" at the cluster scope

**Expected Result**

But when you run a watch on the 
kubectl get clusterrole cattle-impersonation-user-REDACTED -o yaml --watch 
you would see that these rules are removed
`it removes following rules from the cluster role
======================
- apiGroups:
- authentication.k8s.io
resourceNames:
- local://user-wv5p2
resources:
- userextras/principalid
verbs:
- impersonate
- apiGroups:
- authentication.k8s.io
resourceNames:
- Default Admin
resources:
- userextras/username
verbs:
- impersonate
===================================`

I had to roll back my upgrade to v2.6.4 to get the cluster back in working state. Also after upgrading we do have other errors in rancher logs . Rancher catalogs are refreshed every 5 minutes .  
Rancher Internal Support Ticket is 00349589

**Comment by mitchellmaler** [comment]
Just ran into this same issue and came to the same conclusion. It seems to be removing those rules on the impersonation clusterrole for the old users. If I create a new user with the same access it seems to include the right ones.

**Comment by mitchellmaler** [comment]
We upgraded from 2.6.3 to 2.6.5

**Comment by hetii** [comment]
Hello.
It's not just about okta, but general after upgrade to 2.6.5 any kubectl configs taken from rancher webui or used by terraform provider also don't work.
It's a massive bug as affect all clusters and his access.

**Comment by vkruoso** [comment]
I can also confirm that after upgrading to 2.6.5 all my terraform code that uses the kubeconfig from the `rancher2` provider have stopped working. For a few things we have worked around by using `rancher2_app_v2`, since it uses the rancher API instead of the kubernetes API, but for others there is just no workaround. My upgrade were from the 2.5.x version, is it safe to downgrade to 2.6.4 in that case?

**Comment by mitchellmaler** [comment]
We downgraded to 2.6.4 from 2.6.5 and that resolved the kubectl access issue. The bug is rancher is not adding the right rules to the impersonation cluster role it creates in the downstream cluster. After downgrading we could see it was adding the correct rules again.

**Comment by Hitesh-Agrawal** [comment]
Rancher Team any update on when this would get fixed.

**Comment by eumel8** [comment]
Have you tried to login with this user in Rancher UI and go to cluster explorer? It seems Rancher will upgrade the clusterrole after this steps for this user and added the missing entries. Just in our case.

@cmurphy Maybe you want to look into this.

**Comment by cmurphy** [comment]
Hi all, could I get some clarification on the reproduction steps here:

- Does this only happen when you use terraform to provision a downstream cluster? Does it happen for anyone who has provisioned a downstream cluster through the Rancher UI? Could I see an example terraform config?
- I see different people saying the problem happens in different places. Is the forbidden error happening when you run `terraform plan`, using a token key in the terraform config? Is it happening when you download a kubeconfig for the cluster and use it with kubectl? Is it happening if you use the kubectl shell in the dashboard? Is it happening when you use Cluster Explorer?
- Is this happening for anyone who isn't using any auth provider, only using local users? If it is happening for you with an auth provider, which auth providers, other than okta?

**Comment by utking** [comment]
> Hi all, could I get some clarification on the reproduction steps here:
> 
> * Does this only happen when you use terraform to provision a downstream cluster? Does it happen for anyone who has provisioned a downstream cluster through the Rancher UI? Could I see an example terraform config?
> * I see different people saying the problem happens in different places. Is the forbidden error happening when you run `terraform plan`, using a token key in the terraform config? Is it happening when you download a kubeconfig for the cluster and use it with kubectl? Is it happening if you use the kubectl shell in the dashboard? Is it happening when you use Cluster Explorer?
> * Is this happening for anyone who isn't using any auth provider, only using local users? If it is happening for you with an auth provider, which auth providers, other than okta?

For us, it's happening with LDAP as an auth provider. The cluster was created from the Rancher UI.

**Comment by vkruoso** [comment]
We also had this issue in 2.5.5, and after downgrading to 2.5.4 it fixed the problem. We have Github authentication only. All `terraform plan` that were using kubeconfig's created before the upgrade, stopped working. After the downgrade all got back to normal.

**Comment by cmurphy** [comment]
@vkruoso are you sure you are seeing the same issue in 2.5.5? The impersonation clusterrole wasn't introduced in the 2.5 series until 2.5.10. The most recent 2.5.x release is 2.5.15 so 2.5.4 and 2.5.5 are quite old.

**Comment by vkruoso** [comment]
Sorry @cmurphy. I meant 2.6.5 and 2.6.4.

**Comment by cmurphy** [comment]
I've reproduced the issue by starting rancher at version v2.6.2 and upgrading to v2.6.5. I can observe the problem with or without auth providers. Fix is up for review at https://github.com/rancher/rancher/pull/38193

**Comment by Hitesh-Agrawal** [comment]
@cmurphy When is this fix expected for GA. Will it be rolled out with 2.6.7 rancher release.

**Comment by cmurphy** [comment]
# Problem


Impersonation began relying on the extras fields in UserAttributes in 2.6.5, but that field did not exist in 2.6.2 and there was no upgrade logic to add it.
  
# Solution


The token refresher controller now checks if the extras field is empty and syncs it if so.
  
# Testing

 
## Engineering Testing
### Manual Testing

Reproduction: install rancher 2.6.2, create a downstream cluster, download kubeconfig for downstream cluster. Upgrade to 2.6.6. Kubectl for the downstream cluster gets a forbidden error.
Testing: upgrade from 2.6.2 to 2.6-head.
 
### Automated Testing

 n/a

## QA Testing Considerations

  
### Regressions Considerations


Copied from the impersonation confluence page:

Test cases for a human user:

- Download a kubeconfig from rancher for the downstream cluster, run kubectl commands.
- Use the cluster explorer in the UI.
- Use an HTTP tool like curl to make requests on the proxy API, e.g. curl -u $APITOKEN https://$RANCHERSERVER/k8s/cluster/$CLUSTER/v1/api/namespaces

Test cases for a system user:

- Deploying the cluster itself will involve a system user
- Deploy charts through the cluster explorer

Unique situations to test:

- Upgrading to 2.6
- HA vs docker
- Multi-node vs single node
- Using external auth providers
- Switching external auth providers
- Changing a user's groups in an external auth provider
- Using CI (or automated stress testing)
- Messing with the impersonation resources - deleting or modifying them

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type      |
| ------------------------- | ------------------- |
| Rancher version           | 2.6.2               |
| Installation option       | helm                |
| RKE binary version used   | 1.3.1               |
| If Helm Chart k8s cluster | v1.21.5             |
| Cert Details              | let's encrypt       |
| Helm version              | v2.16.8-rancher1    |
| Downstream cluster type   | rke1 linode         |
| Downstream K8s version    | v1.21.13-rancher1-1 |
| Logged in user role       | administrator       |
| Browser type              | google chrome       |
| Browser version           | 103.0.5060.114      |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.2
```

## Reproduction steps

1. Create a downstream rke1 linode cluster
2. Get the kubeconfig file for this downstream cluster
3. Make sure that using the downloaded kubeconfig file works with something like `kubectl get pods -A`
4. Upgrade rancher

```shell
helm upgrade rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.5
```

5. Wait for Rancher to finish upgrading
6. Using the same kubeconfig file from `step #2` run `kubectl get pods -A`

**RESPONSE**

```log
Error from server (Forbidden): userextras.authentication.k8s.io "local://user-<REDACTED_SHORT_UUID>" is forbidden: User "system:serviceaccount:cattle-impersonation-system:cattle-impersonation-user-<REDACTED_SHORT_UUID>" cannot impersonate resource "userextras/principalid" in API group "authentication.k8s.io" at the cluster scope
```
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Expected to be able to access the downstream cluster with the same kubeconfig file

#### :x: Actual
Was unable to access the downstream cluster after upgrade using the same kubeconfig file

<hr>
  
## Validation Environment

| Component                 | Version / Type      |
| ------------------------- | ------------------- |
| Rancher version           | 2.6.2               |
| Installation option       | helm                |
| RKE binary version used   | 1.3.1               |
| If Helm Chart k8s cluster | v1.21.5             |
| Cert Details              | let's encrypt       |
| Helm version              | v2.16.8-rancher1    |
| Downstream cluster type   | rke1 linode         |
| Downstream K8s version    | v1.21.13-rancher1-1 |
| Logged in user role       | administrator       |
| Browser type              | google chrome       |
| Browser version           | 103.0.5060.114      |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.2
```

## Validation steps

1. Create a downstream rke1 linode cluster
2. Get the kubeconfig file for this downstream cluster
3. Make sure that using the downloaded kubeconfig file works with something like `kubectl get pods -A`
4. Upgrade rancher

```shell
helm upgrade rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=v2.6-head
```

5. Wait for Rancher to finish upgrading
6. Using the same kubeconfig file from `step #2` run `kubectl get pods -A`
7. A list of pods has been successfully returned
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
kubeconfig to access a downstream cluster to work after an upgrade 

#### :white_check_mark:Actual
the kubeconfig worked for accessing the downstream cluster after the upgrade

**OTHER AREAS CHECKED**

<table>
    <tbody>
        <tr>
            <th>Test</th>
            <th>Pass/Fail</th>
        </tr>
        <tr>
            <td>Single Node</td>
            <td>:white_check_mark: PASS</td>
        </tr>
        <tr>
            <td>Auth Provider</td>
            <td>:white_check_mark: PASS</td>
        </tr>
        <tr>
            <td>Docker</td>
            <td>:white_check_mark: PASS</td>
        </tr>
    </tbody>
</table>

**Comment by cmurphy** [comment]
## Release note template

**Synopsis of issue**: users that existed in Rancher since version v2.6.2 or earlier may start experiencing authorization errors upon upgrade to v2.6.5 when using kubectl with a downloaded kubeconfig for a downstream cluster.
**Resolved (or not)**: yes
**Workaround**: user experiencing the issue can log out of the dashboard and log back in
**Versions**: v2.6.5, v2.6.6
