### ISSUE TITLE
RKE2 Snapshot in Rancher UI has incorrect age

### ISSUE THREAD

**Issue by ADustyOldMuffin** [rancher/rancher#37907]
**Rancher Server Setup**
Rancher Version 2.6.5 installed via Helm chart on RKE2.

**Information about the Cluster**

Kubernetes version: v1.22.9+rke2r2
User Information

What is the role of the user logged in? Admin

**Describe the bug**

The age of the RKE2 snapshots are when the resource is added to K8s not the age of the RKE2 snapshot.

**To Reproduce**
 
1. Navigate to the RKE2 snapshots
2. Manually delete snapshot in the UI
3. Discovered snapshot in S3 will have age of when it was discovered.

**Result**

The age of the snapshot is how long it has been in the Kubernetes cluster.

**Expected Result**

The age of the snapshot matching when the snapshot was taken.

**Comment by ADustyOldMuffin** [comment]
Still relevant.

**Comment by lindhe** [comment]
I agree! Since I believe I cannot reopen closed issues, I'll create a new one.
