### ISSUE TITLE
TTL for generated Kubeconfig tokens

### ISSUE THREAD

**Issue by hudymi** [rancher/rancher#37906]
**Is your feature request related to a problem? Please describe.**

Currently, to set up kubeconfig token TTL automated generation of it by Rancher must be disabled, and the user must use rancher CLI to be able to connect to the cluster.  It requires additional dependency on the local machine, which some users don't want to have and then they see:

```bash
Unable to connect to the server: getting credentials: exec: executable rancher not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

When rancher CLI is installed it points by default to `localProvider` which shouldn't be used for example, so additional configuration is required

**Describe the solution you'd like**

I would like to have an option to configure TTL on kubeconfigs tokens generated by Rancher. So the user will download kubeconfig from the website, and when it expires user will download another one without a need to use a Rancher CLI. So both solutions should be available - with autogenerated token and without.

**Describe alternatives you've considered**

**Additional context**

**Comment by ADustyOldMuffin** [comment]
This sounds like #36382, In short there is a setting for it but it only relates to tokens and not kubeconfig tokens and the general answer I got was "It's not possible".

**Comment by hudymi** [comment]
It is the same issue, and having kubeconfigs that never expires is not a good idea.

Interesting is that if I set manually `ttl` in `tokens.management.cattle.io` custom resource it will expire after that time and the user will loos access to the cluster, but a new token will be created when clicking download. So everything will work as I expect. Unfortunately, only the Rancher configuration cannot handle it.

Yes, as a workaround I can create a simple controller, that will configure TTLs for kubeconfig tokens, but would like to have the ability to configure that in Rancher, as logic is ready and works as expected.
