### ISSUE TITLE
Rancher K3S exit status 1 across multiple OS

### ISSUE THREAD

**Issue by DarkNeedle** [rancher/rancher#37914]
All I am just placing this here to note that the current docker image fails with the same error and reasons across multiple OS: MacOS (16G RAM, 8CPU), AlmaLinux 8.5 & 9.X, Ubuntu 22.04 Server

This does not appear to be related to a docker version issue. Have run rancher about 6 months ago with no issues. 

Error:
Status: Downloaded newer image for rancher/rancher:latest
2022/06/05 22:32:19 [INFO] Rancher version v2.6.5 (c4d59fa88) is starting
2022/06/05 22:32:19 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/06/05 22:32:19 [INFO] Listening on /tmp/log.sock
2022/06/05 22:32:19 [INFO] Waiting for k3s to start
2022/06/05 22:32:20 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/06/05 22:32:22 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/06/05 22:32:24 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/06/05 22:32:26 [INFO] Running in single server mode, will not peer connections
2022/06/05 22:32:27 [INFO] Applying CRD features.management.cattle.io
2022/06/05 22:32:27 [INFO] Waiting for CRD features.management.cattle.io to become available
2022/06/05 22:32:27 [INFO] Done waiting for CRD features.management.cattle.io to become available
2022/06/05 22:32:28 [ERROR] unable to create feature harvester in initialize features: Post "https://127.0.0.1:6443/apis/management.cattle.io/v3/features": unexpected EOF
2022/06/05 22:32:28 [FATAL] k3s exited with: exit status 1

On MacOS this is a fast fail, on the Linux variants it results in the same K3s exit 

Results are the same from AlmaLinux (both versions 8.5 & 9) and Ubuntu 22.04 Server

INFO: Running k3s server --cluster-init --cluster-reset
2022/06/05 22:26:14 [INFO] Rancher version v2.6.5 (c4d59fa88) is starting
2022/06/05 22:26:14 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/06/05 22:26:14 [INFO] Listening on /tmp/log.sock
2022/06/05 22:26:14 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/06/05 22:26:16 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/06/05 22:26:18 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/06/05 22:26:20 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/06/05 22:26:22 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/06/05 22:26:24 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/06/05 22:26:32 [INFO] Running in single server mode, will not peer connections
2022/06/05 22:26:32 [FATAL] k3s exited with: exit status 1

VMs for Linux are 2vcpu 8GRAM 80G NVME

This is perplexing as this error has been seen throughout 2021 and 2022 across the Rancher forum and here in GitHub among other forums. 

Thoughts where to look?

Thanks

**Comment by DarkNeedle** [comment]
This seems to work, it's noted in the issues log but I think further investigation and mitigation in an official rancher container needs to be released, verified, certified.

docker run --privileged --rm -p 80:80 -p 443:443 oats87/rancher:v2.6.3-cgv2

**Comment by xamindar** [comment]
That doesn't work for me. They should remove the docker way to run it as it appears it has never worked? At least in the past couple years from what I am reading.

# docker run --privileged --rm -p 80:80 -p 443:443 oats87/rancher:v2.6.3-cgv2
[2022-06-09T22:31:17+00:00] [CgroupV2 Fix] Evacuating Root Cgroup ...
[2022-06-09T22:31:18+00:00] [CgroupV2 Fix] Done
2022/06/09 22:31:20 [INFO] Rancher version v2.6.3 (3c1d5fac3) is starting
2022/06/09 22:31:20 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/06/09 22:31:20 [INFO] Listening on /tmp/log.sock
2022/06/09 22:31:20 [INFO] Waiting for k3s to start
time="2022-06-09T22:31:20Z" level=info msg="Acquiring lock file /var/lib/rancher/k3s/data/.lock"
time="2022-06-09T22:31:20Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/e61cd97f31a54dbcd9893f8325b7133cfdfd0229ff3bfae5a4f845780a93e84c"
2022/06/09 22:31:21 [INFO] Waiting for k3s to start
2022/06/09 22:31:22 [INFO] Waiting for k3s to start
2022/06/09 22:31:23 [INFO] Waiting for k3s to start
2022/06/09 22:31:24 [INFO] Waiting for k3s to start
2022/06/09 22:31:25 [INFO] Waiting for k3s to start
2022/06/09 22:31:26 [INFO] Waiting for k3s to start
2022/06/09 22:31:27 [INFO] Waiting for k3s to start
2022/06/09 22:31:28 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/06/09 22:31:30 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/06/09 22:31:32 [INFO] Waiting for server to become available: an error on the server ("apiserver not ready") has prevented the request from succeeding
2022/06/09 22:31:39 [FATAL] k3s exited with: exit status 1
