### ISSUE TITLE
Internal error occurred: failed calling webhook "rancher.cattle.io": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s": dial tcp 10.43.25.145:443: connect: connection refused

### ISSUE THREAD

**Issue by gene1234** [rancher/rancher#37912]
Steps to reproduce:
* Home lab, single node
* Install similar to video https://www.youtube.com/watch?v=oILc0ywDVTk
* installed ubuntu server 20.04.4 LTS with no updates or upgrades (except QEME guest agent for IP recognition via proxmox)
curl https://releases.rancher.com/install-docker/20.10.sh | sh
sudo usermod -aG docker $USER
* logged out then back in to enable
docker run -d --restart=unless-stopped -p 9090:80 -p 9091:443 --privileged -v /opt/rancher:/var/lib/rancher --name=rancher_server rancher/rancher:latest
* Many attempts at creating a Custom Cluster "Use existing nodes and create a cluster using RKE" with no success
* Error:  "Internal error occurred: failed calling webhook "rancher.cattle.io": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s": dial tcp 10.43.25.145:443: connect: connection refused"

  6-4-2022 Yielded:
     ubuntu	       20.04.4 LTS
     docker	       20.10.12
     api version        1.41
     go version	go  1.16.12
     containerd	      1.6.4
     runc	              1.1.1
     docker-init	      0.19.0
     rancher	      2.6.5
     RKE	              1.23.6

![github](https://user-images.githubusercontent.com/3132031/172054748-1ac99ac1-4a3a-403f-8c55-13f615dab13d.png)

**Comment by thowitz** [comment]
I have pretty much the exact same issue

**Comment by niusmallnan** [comment]
Please try this workaround: https://rancher.com/docs/rancher/v2.6/en/troubleshooting/expired-webhook-certificates/

**Comment by thowitz** [comment]
This comment fixed the issue instantly:
https://github.com/rancher/rancher/issues/36967#issuecomment-1153715012
