### ISSUE TITLE
CSP Adapter: Upgrade Strategy

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#37918]
This supports the CSP adapter/AWS integration work.

A strategy needs to be devised which allows the CSP adapter to be upgraded after install. Preferably, this will allow the csp adapter to be upgraded regularly along with rancher without the need for constant user intervention.

Requirements:
- Rancher should specify a minimum version of the csp adapter. 
- When rancher is run, it should check if the adapter is installed. 
  - If the adapter is not installed, rancher should not attempt an upgrade or install
  - If the adapter is installed, rancher should check the values to ensure that the chart is at the minimum version it expects (specified through an environment variable)
    - If the adapter version is at or above the minimum version, rancher should not take any action 
    - If the adapter version is below the minimum version, rancher should upgrade the chart and re-use any user values which were previously provided

If a technical reason is discovered that prevents this from functioning as expected, this reason should be documented in this issue. At minimum, documentation will need to be provided which instructs the user on manually upgrading the csp adapter using the helm cli.

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

There was no logic to automatically upgrade the csp adapter. 

## What was fixed, or what change have occurred

Changes:
- A new setting has been added which specifies the minimum version of the adapter
- A controller has been added which watches this setting
- When the controller is called, if the adapter is installed, it attempts to upgrade the adapter to the specified min version
- When the controller is installed, if the adapter is not installed, it does nothing
- Both the controller and the `v1/generateSUSERancherSupportConfig` endpoints now use helm/chart based logic to determine installation status

## Areas or cases that should be tested

Automatic upgrade. See below for technical procedure steps:
1. Install an older version of the adapter.
2. Upgrade rancher through a helm command (`helm upgrade ...`) to use a new image which specifies a new min version.
3. Ensure that the adapter was upgraded to the requisite minimum version `helm ls -A ...`.
4. Ensure that values which the user specified during the original installation of the chart (aws account number/role name) are not deleted.

No Install:
1. Don't install the adapter.
2. Install rancher.
3. Ensure that rancher doesn't attempt to install or upgrade the adapter. 

No Upgrade:
1. Install the adapter with a version higher than the minimum.
2. Upgrade rancher to use a new minimum version of the adapter which is still lower than the version installed in step 1.
3. Ensure that rancher doesn't attempt to upgrade the adapter.
4. Ensure that the adapter's values appear unchanged.

## What areas could experience regressions

Webhook installation. During testing, an invalid minimum version of the adapter (with an installed adapter) appeared to cause prevent rancher from installing/upgrading the webhook as well. This should be fine as long as the min version is consistently, accurately specified, but is something to keep an eye on during testing.

## Testing Procedure

1. Clone the adapter repo on your local. [Adapter Repo](https://github.com/rancher/csp-adapter)
2. In the adapter repo, open the `Chart.yaml` file in the `charts/rancher-csp-adapter` directory. 
3. Change appVersion to the desired version of the adapter (`1.0.0-rc2`). Change aversion to the desired version of the chart (`1.0.0+up1.0.0-rc2`). The provided examples are valid for attempting to install `1.0.0+up1.0.0-rc2`. See the [current file](https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-csp-adapter/1.0.0%2Bup1.0.0-rc2/Chart.yaml) in our charts repo for an example of this versioning scheme.
4. Install the chart from your local `helm install rancher-csp-adapter . --namespace cattle-csp-adapter-system ...`.

## Notes
- For the testing procedure, if you use a version that has never been  a valid chart you may see issues due to the version of the adapter image. You can overcome this by using a version (such as `0.1.0+up0.1.0-rc7`/ `0.1.0-rc7`) that has a valid corresponding image in [dockerhub](https://hub.docker.com/r/rancher/rancher-csp-adapter/tags).
- You can also add an older version of the rancher-charts which used an older adapter version rather than using a local install (`helm repo add rancher-old https://raw.githubusercontent.com/rancher/charts/87256a7f74d8de5b2a508735cb48dfc00b2486de` - here the last string of digits is the commit of the version of the charts repo that you want to use). This can be helpful for testing basic test cases.

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

<hr>
  
## Validation Environment

| Component               | Version / Type                                      |
| ----------------------- | --------------------------------------------------- |
| Rancher version         | v2.6.6                                              |
| Installation option     | `eksctl` eks local cluster (bring your own cluster) |
| local k8s cluster       | v1.22.10-eks-84b4fe6                                |
| Cert Details            | let's encrypt                                       |
| Helm version            | v2.16.8-rancher2                                    |
| Downstream cluster type | not applicable                                      |
| Downstream K8s version  | not applicable                                      |
| Logged in user role     | administrator                                       |
| Browser type            | google chrome                                       |
| Browser version         | 102.0.5005.115 (Official Build) (x86_64)            |

**ADDITIONAL SETUP**

```shell
eksctl create cluster \
  --name $NAME_VAR \
  --version 1.22 \
  --region $REGION_VAR \
  --nodegroup-name $NG_NAME_VAR \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --managed
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$HOSTNAME_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set extraEnv\[0\].name="CATTLE_PROMETHEUS_METRICS" --set-string extraEnv\[0\].value=true
```

## Validation steps

1. Setup license manager and purchase support in AWS
2. Create an EKS Cluster
3. Install Rancher
4. Create an OIDC provider
5. Create an IAM Role
6. Install the CSP Adapter
   - Install the csp from local
   - `values.yaml` ==> `image` ==> `tag` ==> `latest`
   - `Chart.yaml` ==> version: `0.5.0+up0.5.0`
   - `Chart.yaml` ==> appVersion: `0.5.0`
   - Run the following command


```shell
helm install rancher-csp-adapter . --namespace cattle-csp-adapter-system --set aws.enabled=true --set-string aws.accountNumber=$MY_ACC_NUM --set aws.roleName=$MY_ROLE_NAME --create-namespace
```

7. Upgrade Rancher to `2.6.7-rc1`
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
CSP Adapter should automatically upgrade to the latest minimum version

#### :white_check_mark:Actual
CSP Adapter automatically upgraded to the latest minimum version


<table>
    <tbody>
        <tr>
            <th>Test</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual</th>
            <th>Pass/Fail</th>
        </tr>
        <tr>
            <td>No Install</td>
            <td>
                <ol>
                    <li>Don't install the adapter</li>
                    <li>Install rancher</li>
                    <li>Ensure that rancher doesn't attempt to install or upgrade the adapter</li>
                </ol>
            </td>
            <td>csp adapter shouldn't auto install</td>
            <td>csp adapter did not auto install</td>
            <td>:white_check_mark:</td>
        </tr>
        <tr>
            <td>No Upgrade</td>
            <td>
                <ol>
                    <li>Install the adapter with a version higher than the minimum</li>
                    <li>Upgrade rancher to use a new minimum version of the adapter which is still lower than the version installed in step 1</li>
                    <li>Ensure that rancher doesn't attempt to upgrade the adapter</li>
                    <li>Ensure that the adapter's values appear unchanged</li>
                </ol>
            </td>
            <td>rancher shouldn't attempt an upgrade</td>
            <td>rancher didn't attempt an upgrade</td>
            <td>:white_check_mark:</td>
        </tr>
    </tbody>
</table>
