### ISSUE TITLE
Upgrade gatekeeper chart to 3.8.1

### ISSUE THREAD

**Issue by samkulkarni20** [rancher/rancher#37917]
Upgrade rancher-gatekeeper chart to latest release. As of Jun 6, 2022 the latest gatekeeper version is v3.8.1.

Related issue: rancher/rancher#37727

**Comment by vivek-infracloud** [comment]
Validated on rancher v2.6.7-rc1

Steps followed:

1. Provisioned a v1.22.9-rancher1-1 node driver cluster(1-cp,1-etcd,2-worker).
2. Installed OPA Gatekeeper 100.2.0+up3.8.1
3. Created the constraints using the default templates for Namespace and Repository.
4. The constraints are working as expected.

Gatekeeper chart validated successfully.

**Comment by vivek-infracloud** [comment]
Reopening since minor issue was found in the PR. Waiting for update to be merged. https://github.com/rancher/charts/pull/1969

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6-head(bda0897)

**Steps followed:**
- Provisioned a v1.24.2-rancher1-1 node driver cluster(1-cp, 1-etcd, 2-worker).
- Installed OPA Gatekeeper chart version `100.2.0+up3.8.1`
- Created the constraints using the default templates for Namespace and Repository.
- The constraints are working as expected.

**Result:**
- All checks passed, hence closing the issue.
