### ISSUE TITLE
Rancher UI could not open logging, showing disconnection

### ISSUE THREAD

**Issue by DengYongJie666** [rancher/rancher#37935]
Rancher UI cannot open the log, indicating that the binary worker node added later has been disconnected. Above Rancher UI, the two binary worker nodes added after POD cannot open the log on the worker node added after POD. 

I ran the custom cluster from the old Docker, restored the ETCD snapshot data to the binary cluster, and manually deleted the ETCD data 

![image](https://user-images.githubusercontent.com/97373898/172536032-9ed753e7-075f-4048-afb9-497e2663c68b.png)
![image](https://user-images.githubusercontent.com/97373898/172535297-e286e543-de26-445f-86a0-8fca1ef0d2f9.png)
![image](https://user-images.githubusercontent.com/97373898/172535441-2bf57a30-bbcd-4cb2-bfbb-05be8e829bf8.png)
![image](https://user-images.githubusercontent.com/97373898/172535454-67114dda-dc2f-4b72-9eb7-1bd02360e32a.png)
![image](https://user-images.githubusercontent.com/97373898/172535609-551da7f2-2ae9-416d-8887-124129353df9.png)
![image](https://user-images.githubusercontent.com/97373898/172535676-ef382f47-9bf0-4217-b698-8388c3323919.png)

**Comment by burjandedes** [comment]
We have a similar problem with both Rancher UI 2.6.5 and 2.6.6. With kubectl we can see the logs, but in the UI everything is empty. 
![kép](https://user-images.githubusercontent.com/1625558/173356364-bdaf9279-7244-442f-b0a3-90445c9c788f.png)

**Comment by VickyKung** [comment]
I have same issue with k8s version v1.20.2 in rancher v2.5.7. the cosole log  shows websocket connection fail and return 500, i have no idea about this.
