### ISSUE TITLE
Error after a k8s upgrade of the eks cluster from EKS console

### ISSUE THREAD

**Issue by SharpThunder** [rancher/rancher#37940]
**Rancher Server Setup**
- Rancher version: 2.5.6
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS with managed nodegroups

**Information about the Cluster**
- Kubernetes version: 1.21
- Cluster Type : Downstream
   - If downstream, what type of cluster? : EKS with managed nodegroups

**User Information**
- What is the role of the user logged in?: Admin
   
**Describe the bug**

First of all, FYI this cluster first created with Rancher, however since rancher does not support subnet selection in nodegroups creation, I deleted nodegroups and created with eksctl.
I upgraded downcluster from 1.19 to 1.21. I actually have weird problems when upgraded from 1.19 to 1.20. I used eksctl to upgrade cluster and then upgrade nodegroups with eksctl.  I suspect Rancher in this case.
When I upgraded 1.20 nodes are upgraded to 1.20 however after some time nodes are recreated with 1.19 version. 
To solve this I upgraded to 1.21 as quickly as possible after nodes created with 1.20. Upgraded successfully and nodes does not downgrade to 1.20 anymore. 
However after some time later I saw this error message:

>InvalidParameterException: Unsupported Kubernetes minor version update from 1.21 to 1.20 { RespMetadata: { StatusCode: 400, RequestID: "b77e492d-bbdd-4d46-a810-2c0582650cfe" }, ClusterName: "eks-power", Message_: "Unsupported Kubernetes minor version update from 1.21 to 1.20" }

**To Reproduce**

I guess it can be reproduced like this
- Create downcluster 1.19 cluster in Rancher
- Create nodegroups in eksctl with different subnets selected for AZs.
- Delete Rancher created nodegroups with eksctl.
- Upgrade to 1.21 from EKS console or eksctl.

**Expected Result**
Cluster should get updated successfully in Rancher with no error.

**Comment by SharpThunder** [comment]
Anyone to take a look at this issue?

**Comment by ramnaresh9993** [comment]
<html>
<body>

Hi, I am facing the same issue after EKS cluster's version upgrade.

InvalidParameterException: Unsupported Kubernetes minor version update from 1.21 to 1.20 { RespMetadata: { StatusCode: 400, RequestID: "b975d17f-1832-4ca8-8d6b-3af55aab2251" }, ClusterName: "my-cluster", Message_: "Unsupported Kubernetes minor version update from 1.21 to 1.20" }
--



</body>
</html>

**Comment by SharpThunder** [comment]
I found a solution.
This probably occurs because Rancher wants to maintain cluster config in clusters.management.cattle.io CRD.
In this crd i found my cluster named c-gmttr and edited. The trick is i needed to make spec field should contain same parameters in eksStatus field. In my case i needed to edit kubernetesVersion field and nodeGroups field.
After this are the same i also need to remove and edit status fields in clusters.provisioning.cattle.io and remove error status using kubectl edit-status. So i deleted message field and made status true of Updated condition.

**Comment by michaelniemand** [comment]
> I found a solution. This probably occurs because Rancher wants to maintain cluster config in clusters.management.cattle.io CRD. In this crd i found my cluster named c-gmttr and edited. The trick is i needed to make spec field should contain same parameters in eksStatus field. In my case i needed to edit kubernetesVersion field and nodeGroups field. After this are the same i also need to remove and edit status fields in clusters.provisioning.cattle.io and remove error status using kubectl edit-status. So i deleted message field and made status true of Updated condition.

thanks for this! As an additional remark: It is usually not necessary to edit many fields; for me it was also just kubernetesVersion 2 or 3 other fields. I just exported the resource using `kubectl get clusters.management.cattle.io <your-cluster-id> -o yaml > mycluster.yaml` then edit the file and apply it again with `kubectl apply -f mycluster.yaml`
Don't forget to remove the status field of the resource; otherwise the update will fail with `the object has been modified; please apply your changes to the latest version and try again`
