### ISSUE TITLE
EC2 Node Driver provisioning fails in EC2 environments with IMDSv2 enforced on instance creation

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#37943]
## Issue description:
IMDSv2 metadata is configured by rancher-machine after initial instance creation, via a `ModifyInstanceMetadataOptions` call, (https://github.com/rancher/machine/blob/v0.15.0-rancher87/drivers/amazonec2/amazonec2.go#L834 / [https://github.com/rancher/machine/pull/94).](https://github.com/rancher/machine/pull/94)) As a result, in environments where IMDSv2 is enforced upon instance creation, EC2 Node Driver provisioning fails.

rancher-machine uses RequestSpotInstances versus RunInstances to create spot versus non-spot instances:

https://github.com/rancher/machine/blob/v0.15.0-rancher87/drivers/amazonec2/amazonec2.go#L716 https://github.com/rancher/machine/blob/v0.15.0-rancher87/drivers/amazonec2/amazonec2.go#L780 

RunInstances permits passing metadata-options, but RequestSpotInstances does not appear to and is deprecated in favour of RunInstances with spot options via instance-market-options, so this would appear to require a rewrite of the rancher-machine logic to use RunInstances to create spot instances:

 https://docs.aws.amazon.com/cli/latest/reference/ec2/run-instances.html

https://docs.aws.amazon.com/cli/latest/reference/ec2/request-spot-instances.html

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-best-practices.html#which-spot-request-method-to-use
## Repro steps:

Provision a Rancher v2.6.5 instance
Create an EC2 Node Template with "httpEndpoint": "enabled" and "httpTokens": "required" for IMDSv2
Configure EC2 Policy to require the use of IMDSv2 (per  "Require the use of IMDSv2" at https://docs.amazonaws.cn/en_us/AWSEC2/latest/WindowsGuide/ExamplePolicies_EC2.html)
Provision a cluster with the node template
Observe instance creation fails with error of the format `Error creating machine: Error in driver during machine creation: Error launching instance: UnauthorizedOperation: You are not authorized to perform this operation....`

SURE-4767

**Comment by HarrisonWAffel** [comment]
As this issue requires the use of a new AWS policy, testing is on hold until we can coordinate with EIO on creating this policy and configuring it correctly

**Comment by HarrisonWAffel** [comment]
### Root cause
  Creation of spot instances in AWS environments which have IMDSv2 enforced would fail, even if the correct options were chosen in the UI. This was due to the utilization of a deprecated API call to create spot instances, which prevented us from attaching the required meta-data to the request so as to comply with the IMDSv2 policy. Previously, the meta-data options were being attached to the instance once it had transitioned into a running state. 
### What was fixed, or what changes have occurred
  The deprecated call to create spot instances has been replaced with the preferred API call, which allows for the setting of metaData within the request to create the spot instance.  This allows for the creation of instances in environments where IMDSv2 is strictly enforced. 
### Areas or cases that should be tested
  The creation of AWS spot instances in environments where an IMDSv2 policy is enforced. 

  + EIO will attach a policy to the QA members IAM 
  + Use the rancher UI to create a new node-template
  + When configuring the instance, ensure that `HTTP Endpoint` and `HTTP Tokens` are set to `Enabled` and `Required` respectfully. 
  + Ensure that `Spot Instance` is selected for the node template
  + create the cluster using an ubuntu AMI 

### What areas could experience regressions?
Creation of spot and non-spot AWS instances.

**Comment by slickwarren** [comment]
tested on v2.6-head (14572ee):
* creating an rke1 cluster (1.23.7-rancher1-1) with a default  AMI was able to create the node, but the node(s) were not able to register with the cluster. 
* creating an rke1 cluster (1.23.7-rancher1-1) with a private AMI was unable to create the instance.  

@HarrisonWAffel is aware of the issue and has access to the setup with errors reproduced.

**Comment by slickwarren** [comment]
tested on v2.6-head (b66dd0f) using the following instructions:
* EIO will attach a policy to the QA members IAM
* Use the rancher UI to create a new node-template
* When configuring the instance, ensure that HTTP Endpoint and HTTP Tokens are set to Enabled and Required respectfully.
* Ensure that Spot Instance is selected for the node template

create the following clusters using an ubuntu AMI: 

* creating an rke1 cluster (1.24.2-rancher1-1) with a default AMI -- pass
  * create dedicated node-per-role spot instance cluster -- pass
* creating an rke1 cluster (1.24.2-rancher1-1) with a private AMI -- fail (seems similar to previous random failures we were seeing)
```


INFO] [node-controller-rancher-machine] Creating machine...
--
Mon, Jul 25 2022 3:28:50 pm | 2022/07/25 22:28:50 [INFO] [node-controller-rancher-machine] (ctw-pami-a2) Launching instance...
Mon, Jul 25 2022 3:28:50 pm | 2022/07/25 22:28:50 [INFO] [node-controller-rancher-machine] (ctw-pami-a2) Creating New SSH Key
Mon, Jul 25 2022 3:28:50 pm | 2022/07/25 22:28:50 [INFO] [node-controller-rancher-machine] (ctw-pami-a2) creating key pair: ctw-pami-a2-TvYXG
Mon, Jul 25 2022 3:28:53 pm | 2022/07/25 22:28:53 [INFO] [node-controller-rancher-machine] (ctw-pami-a2) configuring security groups in vpc-bfccf4d7
Mon, Jul 25 2022 3:28:56 pm | 2022/07/25 22:28:56 [INFO] [node-controller-rancher-machine] (ctw-pami-a2) found existing security group (rancher-nodes) in vpc-bfccf4d7
Mon, Jul 25 2022 3:28:57 pm | 2022/07/25 22:28:57 [INFO] [node-controller-rancher-machine] (ctw-pami-a2) configuring security group authorization for 0.0.0.0/0
Mon, Jul 25 2022 3:28:57 pm | 2022/07/25 22:28:57 [INFO] [node-controller-rancher-machine] (ctw-pami-a2) launching instance in subnet subnet-ee8cac86
Mon, Jul 25 2022 3:29:01 pm | 2022/07/25 22:29:01 [INFO] [node-controller-rancher-machine] (ctw-pami-a2) Missing instance ID, this is likely due to a failure during machine creation
Mon, Jul 25 2022 3:29:01 pm | 2022/07/25 22:29:01 [INFO] [node-controller-rancher-machine] (ctw-pami-a2) deleting key pair: ctw-pami-a2-TvYXG
Mon, Jul 25 2022 3:29:06 pm | 2022/07/25 22:29:06 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
Mon, Jul 25 2022 3:29:06 pm | 2022/07/25 22:29:06 [INFO] [node-controller-rancher-machine]
Mon, Jul 25 2022 3:29:06 pm | 2022/07/25 22:29:06 [INFO] Generating and uploading node config ctw-pami-a2
Mon, Jul 25 2022 3:29:06 pm | 2022/07/25 22:29:06 [ERROR] error syncing 'c-dtblh/m-scz4x': handler node-controller: Error creating machine: Error in driver during machine creation: MissingParameter: The request must contain the parameter InstanceId, requeuing
Mon, Jul 25 2022 3:29:25 pm | 2022/07/25 22:29:25 [ERROR] Error during subscribe websocket: close sent


```
* create rke2 cluster -- failed (new ticket mentioned above)

**Comment by HarrisonWAffel** [comment]
@slickwarren I tested this today and found that, for some AMI's, the default storage size of 16GB may not be enough. After adding an additional log message within machine I observed the error 

```
(haffel-ec2-test-ami) error countered within innerCreate: Error request spot instance: InvalidBlockDeviceMapping: Volume of size 16GB is smaller than  snapshot 'snap-<ID>', expect size >= 32GB
(haffel-ec2-test-ami) 	status code: 400, request id: <ID>
```

Could you re-test with your custom AMI, using a larger block size of 32GB or even 64GB, and see if the issue still occurs? Currently, there is no difference between how the AMI is specified for spot-instances versus regular instances. I can however raise a PR to enhance the logging, as the AWS driver does seem to be dropping important errors such as this.

**Comment by slickwarren** [comment]
tested on v2.6-head (https://github.com/rancher/rancher/commit/b66dd0f614f9d60ef54dfb82da12b9b8b194021b) with above recommendations:

* creating an rke1 cluster (1.24.2-rancher1-1) with a private AMI -- pass
