### ISSUE TITLE
Multiple CIS scans fail on RKE1 hardened downstream clusters

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37944]
**Rancher Server Setup**
- Rancher version: `v2.6-head 4199cac`
- Installation option (Docker install/Helm Chart): HA install
   - If Helm Chart, Kubernetes Info: RKE1
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): 
         Node Setup: 3 nodes all roles
         Version: `v1.23.6 `
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: v1.23.6 and v1.22.9
- Cluster Type (Local/Downstream): `Custom RKE1 3 worker, 3 etcd, 2 cp`
- CIS chart version: `2.0.4`

**Describe the bug**
Multiple CIS scan failures seen on downstream hardened clusters on RKE1 clusters.
Following are the profiles that fail:

- rke-profile-permissive-1.5
- rke-profile-permissive-1.6
- rke-profile-hardened-1.5
- rke-profile-hardened-1.6

**To Reproduce**
1. Create a custom cluster on k8s version either `v1.23.6` or `v1.22.9`
2. From explorer >> Apps & Market >> Install CIS benchmark version `v2.0.4`
3. Run the CIS scan profiles as mentioned above

**Result**
All the scans fail with multiple failures
```
 k get clusterscans
NAME         CLUSTERSCANPROFILE           TOTAL   PASS   FAIL   SKIP   WARN   NOT APPLICABLE   LASTRUNTIMESTAMP       CRONSCHEDULE
scan-7w6nk   rke-profile-permissive-1.6   122     54     9      0      24     35               2022-06-08T17:38:05Z   
scan-d4sdn   rke-profile-hardened-1.6     122     68     9      0      24     21               2022-06-08T17:39:32Z   
scan-g6mht   rke-profile-hardened-1.5     122     68     9      0      24     21               2022-06-08T17:38:56Z   
scan-qmcs9   rke-profile-permissive-1.5   122     54     9      0      24     35               2022-06-08T17:38:42Z   
```

**Expected Result**
Expected all the scans to go through

**Additional context**
Scans go through without error is we install the benchmark version `v2.0.3`

**Comment by doflamingo721** [comment]
**Validated the issue on rancher v2.6-head(f40e542)**

**Steps followed**:

1. Created a hardened cluster with 1cp 1etcd and 3worker nodes.
2. Install cis-benchmark chart from Apps.
3. Run the `rke-profile-hardened-1.6` profile scan.

**Result**:
Both the `rke-profile-hardened-1.6` and `rke-profile-hardened-1.5` scans passed without any failures.

1. Following are the scan results from a multi-node hardened cluster:
![Screenshot from 2022-07-11 16-54-59](https://user-images.githubusercontent.com/34883075/178260876-03e323d9-7d7c-41ba-b095-656bb02bbbab.png)

2. Following are the scan results from a single node all roles hardened cluster:
![Screenshot from 2022-07-08 17-58-11](https://user-images.githubusercontent.com/34883075/178261016-a5ff1695-3911-49d5-8770-ee6790ccd53f.png)

**Comment by AndrewHoffmanQA** [comment]
this needs to be re-opened, this bug is persisting 



Rancher version: v2.6-8af5d2
Installation option (t): HA install
If Helm Chart, Kubernetes Info: RKE1
Cluster Type (RKE1, RKE2, k3s, EKS, etc):
Node Setup: 3 nodes all roles
Version: v1.23.8
Proxy/Cert Details: self-signed
Information about the Cluster

Kubernetes version: v1.23.6 and v1.22.9
Cluster Type (Local/Downstream): Custom RKE1 3 worker, 1 etcd, 1 cp
CIS chart version: 2.0.4
hardened 

Anupama's bug writeup is great, no reason to redo it. 

bug example, i downgraded the chart and things passed again
![image](https://user-images.githubusercontent.com/89030218/180252513-cdfbbd3b-6e72-4ada-b985-703e46e043e1.png)

**Comment by doflamingo721** [comment]
@AndrewHoffmanQA The chart version you have validated this on is `2.0.4`. The fixes for these failures have been added in the cis-benchmark `2.0.5-rc4`. Can you pls use `2.0.5-rc4` chart version to test this? Thanks!

**Comment by AndrewHoffmanQA** [comment]
@doflamingo721 thank you for the clarification, that works.
