### ISSUE TITLE
OOB Chart release for mid-June

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#37942]
Issues in this OOB release:
Longhorn 1.3.0 in 2.6 https://github.com/rancher/rancher/issues/36934   (done)
Longhorn 1.2.5 in 2.6 https://github.com/rancher/rancher/issues/36933
Epinio in 2.6 https://github.com/rancher/charts/issues/1945

**Comment by innobead** [comment]
cc @rebeccazzzz @prachidamle @MKlimuszka

**Comment by PennyScissors** [comment]
Longhorn 1.3.0 will be released OOB as part of [this PR](https://github.com/rancher/charts/pull/1990). This does not include Longhorn 1.2.5 or Epinio 2.6.
