### ISSUE TITLE
Changing the admin user in the configured auth resets the graph end points to the old graph endpoints

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37959]
**Rancher Server Setup**
- Rancher version: `v2.6.5` to `v2.6-head f4d09c7`
- Installation option (Docker install/Helm Chart): HA
   - If Helm Chart, Kubernetes Info: RKE1
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 3 node 
         Version: `v1.23.7`
- Proxy/Cert Details: `self-signed`

**Describe the bug**
After upgrading the migration end points, if we try to update the admin user, we notice the end points are reset to old end points. This is seen happening on a rancher upgraded server.

**To Reproduce**
1. Create a rancher server on v2.6.5
2. Enable azure AD 
3. Verify the old graph endpoints in the azure auth
4. Upgrade rancher server to v2.6-head
5. Upgrade the migration end points to the latest by navigating to https://<rancherurl>/v3/azureADConfigs/azuread?action=configureTest
6. Update the graph endpoints to `https://graph.microsoft.com/`, auth end points to `https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/authorize` and token endpoints to `https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/token`
7. From Auth providers >> Edit config >> provide the secret >> Update the admin to a new admin user and save
8. verify the azureAD graph endpoints

**Result**
Graph endpoints are changed back to the old graph end points.
```
kubectl describe authconfigs azuread | grep graph
Graph Endpoint:      https://graph.windows.net/
```

**Expected Result**
Expected the graph endpoints to be the newly migrated end points.

**Comment by maxsokolovsky** [comment]
Discussed offline -  we can close this, since this behavior is normal, because the UI code was old at the time, and resetting the auth config saves the configuration driven by the values from the old UI.

**Comment by samjustus** [comment]
@anupama2501 please close if you're in agreement with max

**Comment by anupama2501** [comment]
Re verified on v2.6-head 8b3919b and I confirm that it works as expected.
