### ISSUE TITLE
Not able to resolve cross stack services by <service-name>.<stack-name>

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3795]
Rancher Version: Build from master

Docker Version:1.10.2

OS: Ubuntu 14.04 hosts

Steps to Reproduce: 

Create a service in Default stack.

Create service "test1" in stack "hello".

Not able to resolve cross stack services by test1.hello , but I am able to resolve using by hello.test1.rancher.internal

<img width="675" alt="screen shot 2016-03-05 at 9 46 43 am" src="https://cloud.githubusercontent.com/assets/4266958/13549296/37579d2a-e2b7-11e5-98a1-85d887bbfdfe.png">

**Comment by alena1108** [comment]
@sangeethah I can't reproduce it....on the setup that you've given, the issue is no longer reproducible either. If you happen to see it again, could you pass an environment to me and @vincent99 for debugging?

**Comment by sangeethah** [comment]
Closing this issue for now. If I am able to reproduce this issue again will open a new issue.
